### ISSUE TITLE
VisualScript: the `preload` node's resource property opens a huge dropdown

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#26136] opened 2019-02-21 20:45 UTC
Godot 3.1 beta5

I wanted to preload a resource in VisualScript, so I created a `Preload` item, which has a `resource` property. However, clicking it brings a gigantic menu listing every resource type in Godot *for creating them*. If you want to just load one, you have to scroll down for about 10 seconds with the mouse wheel until you can reach the `Load` option. This is quite overwhelming, I think it should either open a more workable popup instead, or just not show the `New` option because that's a `Preload` item.

Note: I can't find any way to create new resource instances in VisualScript, so maybe that could be another issue. Maybe I'm not doing it the easiest way, I went trying this because I was curious about a Q&A thread so I toyed around with VisualScript and found this.

![image](https://user-images.githubusercontent.com/1311555/53200511-9e558d80-3619-11e9-87ed-23446f5d4ee0.png)

**Comment by fire** [comment] 2019-02-21 21:59
Want to open another issue for creating new object (of a specific type) instances in VisualScript?

**Comment by akien-mga** [comment] 2020-01-14 13:05
Duplicate of #24319.

**Closed by akien-mga** 2020-01-14 13:05 UTC
Labels: bug, topic:editor, topic:visualscript, usability
