### ISSUE TITLE
Dictionary as dictionary key is broken when dict-key value is changed

### ISSUE THREAD

**Issue by AlexTheRegent** [godotengine/godot#44471] opened 2020-12-17 20:19 UTC
**Godot version:**

3.2.3 stable, Godot_v3.2.4-beta4_win64.exe.zip

**OS/device including version:**

Windows 10

**Issue description:**

If one dictionary is key for another dictionary, it is impossible (runtime error) to get it's value after one of the "dictionary as key" values has been changed. More in example code.

**Steps to reproduce:**
```
# 1. create main dictionary
var dict := {}
# 2. create dictionary that will act as key
var keydict := {"value": 2}
# 3. assign key to main dictonary
dict[keydict] = true
# 4. check that everything is alright: 
prints(dict, dict.has(keydict), dict.keys(), dict.values())
# output: {{value:2}:True} True [{value:2}] [True]
# 5. change value of keydict
keydict.value = 5
# 6. and now everything is broken
prints(dict, dict.has(keydict), dict.has(dict.keys()[0]), dict.keys(), dict.values())
# output: {{value:5}:Null} False False [{value:5}] [True]
# in print there is key but it's value is Null. both `has` methods returned false. 
# but there are correct key and value (and value is not Null) for changed key.
```

**Minimal reproduction project:**

[godot_dict_key_bug.zip](https://github.com/godotengine/godot/files/5711920/godot_dict_key_bug.zip)

**Comment by Zylann** [comment] 2020-12-17 21:39
That sounds like a really hard thing to solve properly... and a rare situation as well.

**Comment by AlexTheRegent** [comment] 2020-12-17 22:59
Example is simplified version of my problem. Description of my situation is in next paragraph. I think this issue can have simplified solution. It can be "refresh" method to Dictionary class that will fix loose keys in dictionary on request. Another workaround can be method to get address of variable (so it will be possible to use addresses as keys instead of Dictionaries). 

My problem is that I have inventory. Items are stored as dictionaries in array. When item is taken inventory emit signal with changed item dictionary. And I have inventory GUI. During building it makes dictionary (item -> gui node). Inventory can have items with same id but different states (for example, one axe with 40% durability and second with 100% durability). So I can't properly notify GUI (or any other listener) that key will be changed (new key can't act as old key at same time because I have only one dictionary). I'm thinking about adding unique id for each item and use it as dict's key. But this require more code to write.

**Comment by vnen** [comment] 2023-03-10 15:05
This is a duplicate of #24215. It's not something that should be relied upon since it's "undefined behavior".

**Closed by vnen** 2023-03-10 15:05 UTC
Labels: topic:core, documentation
