### ISSUE TITLE
Deleting a script causes crash

### ISSUE THREAD

**Issue by Haydoggo** [godotengine/godot#71893] opened 2023-01-23 03:29 UTC
### Godot version

v4.0.beta14.official [28a24639c]

### System information

Windows 10

### Issue description

Deleting a script from the filesystem tab in editor seems to cause the editor to crash

### Steps to reproduce

1. Create new project
2. Create new script
3. Delete script from FileSystem tab
Easy as that

### Minimal reproduction project

N/A

**Comment by akien-mga** [comment] 2023-01-23 10:26
Duplicate of #71713

**Closed by akien-mga** 2023-01-23 10:26 UTC
