### ISSUE TITLE
32bit Mono version crashing on start

### ISSUE THREAD

**Issue by piratesephiroth** [godotengine/godot#30689] opened 2019-07-19 05:41 UTC
**Godot version:**
v3.2, 708092f03

**OS/device including version:**
Windows 10 x64
VS2017 & VS2019

**Issue description:**
The Godot editor always crashes on start on the 32bit mono version. Even in a clean setup, with no projects at all.
I have tried different versions of mono and even installing only a 32bit version but it just never works.
The 64bits version works just fine as expected.
![image](https://user-images.githubusercontent.com/10672233/61511625-b3b6c400-a9cd-11e9-96dd-5c39de74bd25.png)

**Steps to reproduce:**
Compile the 32bit mono version of the editor and run it.

**Minimal reproduction project:**
.

**Comment by Ranoller** [comment] 2019-07-21 23:13
Related #28949

**Comment by clayjohn** [comment] 2020-07-11 06:48
Can anyone still reproduce this bug in [Godot 3.2.2](https://godotengine.org/article/maintenance-release-godot-3-2-2) or any later release?

If yes, please ensure that an up-to-date Minimal Reproduction Project (MRP) is included in this report (a MRP is a zipped Godot project with the minimal elements necessary to reliably trigger the bug). You can upload ZIP files in an issue comment with a drag and drop.

**Comment by piratesephiroth** [comment] 2020-07-11 10:36
> 
> 
> Can anyone still reproduce this bug in [Godot 3.2.2](https://godotengine.org/article/maintenance-release-godot-3-2-2) or any later release?
> 
> If yes, please ensure that an up-to-date Minimal Reproduction Project (MRP) is included in this report (a MRP is a zipped Godot project with the minimal elements necessary to reliably trigger the bug). You can upload ZIP files in an issue comment with a drag and drop.

I think this has been fixed.
The 32-bit Editor now runs fine on Windows 10 x64

**Comment by akien-mga** [comment] 2020-07-14 08:33
Duplicate of #17299.

**Closed by akien-mga** 2020-07-14 08:33 UTC
Labels: bug, crash, topic:mono
