### ISSUE TITLE
Compile error, in hash 3d06957f12ba5c04702f3db980af9c07142e7886.

### ISSUE THREAD

**Issue by antonyjones67** [godotengine/godot#11403] opened 2017-09-18 22:53 UTC
Windows 10. Intel 7.

On this hash.
3d06957f12ba5c04702f3db980af9c07142e7886

Compile error.
1>modules\gdnative\gdnative.cpp(47): error C2059: syntax error: '.'
1>modules\gdnative\gdnative.cpp(48): error C2143: syntax error: missing ';' before '}'
1>modules\gdnative\gdnative.cpp(48): error C2059: syntax error: '}'
1>  scons: *** [modules\gdnative\gdnative.windows.tools.64.obj] Error 2

Problem with 	GODOT_GDNATIVE_API_FUNCTIONS.

**Comment by Noshyaar** [comment] 2017-09-19 00:23
cc @karroffel

**Comment by karroffel** [comment] 2017-09-19 00:54
duplicate of #11373

**Closed by karroffel** 2017-09-19 00:54 UTC
Labels: bug, topic:gdnative
