### ISSUE TITLE
[FBX] [document parser, Cinema4D] Crash on importing version 7100 file due to deconstruction of tokens

### ISSUE THREAD

**Issue by kruglinski** [godotengine/godot#33816] opened 2019-11-22 15:28 UTC
**Godot version: Godot 3.2 beta 2

**OS/device including version: Microsoft Windows [Ver 10.0.17763.864]

**Issue description:**
massive errors when import fbx
![image](https://user-images.githubusercontent.com/2869425/69438315-c415eb80-0d7f-11ea-963a-3fb82ed62610.png)

**Steps to reproduce:**
drag this fbx below to Godot 3.2 editor

**Minimal reproduction project:**
[CMotion.zip](https://github.com/godotengine/godot/files/3880186/CMotion.zip)

**Comment by akien-mga** [comment] 2019-11-22 15:54
CC @RevoluPowered @fire

**Comment by fire** [comment] 2020-05-26 18:20
FBX is being improved here https://github.com/godotengine/godot/pull/38966 .

**Comment by RevoluPowered** [comment] 2020-05-27 23:16
Yeah so we are rewriting the importer, I'll take a note that your file is broken and test it while I work on the importer

**Comment by fire** [comment] 2020-11-16 19:15
Confirmed this causes a crash on b38f7af4fd a79293e0fc

**Comment by RevoluPowered** [comment] 2020-11-20 14:10
Again I need to know how the file was made, where it was exported from and you need to enable verbose debugging with -v on output.

**Comment by RevoluPowered** [comment] 2020-11-20 15:35
Notes:
- File version 7100:  2018 FBX SDK
- Crash is destruction of the tokens object.reset()

**Comment by RevoluPowered** [comment] 2020-11-30 15:59
FBX File version 7100, and 7200 are now depreciated and should be upgraded to 7700 using the original modelling application.

**Comment by RevoluPowered** [comment] 2020-11-30 19:14
As for the leak this will still be resolved as it will happen even if the file is not ingested.

**Comment by RevoluPowered** [comment] 2020-12-11 13:01
Can you please open the file in the original application and upgrade the file and try again?

**Comment by RevoluPowered** [comment] 2021-04-14 08:55
I have allowed for 7200 files again. I will see if this is now fixed with the latest PR.

**Comment by RevoluPowered** [comment] 2021-04-14 09:22
File will not load correctly due to bugs in other places:
- memory leak is fixed
- version 7100 seems to import

Manual intervention required:
- clear skins & skeleton 
- orient X - 90 degrees.

Result:

<img width="912" alt="Screenshot 2021-04-14 at 10 22 28" src="https://user-images.githubusercontent.com/748770/114687147-5919db80-9d0b-11eb-9b51-0a43f9251155.png">

**Comment by akien-mga** [comment] 2022-04-06 22:23
This is probably fixed with the new FBX importer using [FBX2glTF](https://github.com/V-Sekai/FBX2glTF/releases).
You can test it in Godot 4.0 alpha 6: https://godotengine.org/article/dev-snapshot-godot-4-0-alpha-6
This new importer might also be backported for the `3.x` branch eventually.

If you still find issues with these models using the new importer, we suggest opening a new issue with details about the problems in Godot 4.0 alpha 6 or later.

**Closed by akien-mga** 2022-04-06 22:23 UTC
Labels: bug, confirmed, topic:import, crash
