### ISSUE TITLE
4.1, Overlapping multiline error/warning messages in Debugger (Tree node bug)

### ISSUE THREAD

**Issue by duianto** [godotengine/godot#77067] opened 2023-05-14 15:05 UTC
### Godot version

v4.1.dev2.official [668cf3c66]

### System information

Windows 10 22H2, Compatibility, Geforce GTX 550 Ti

### Issue description

Issue observed in: 
- v4.1.dev2.official [668cf3c66]

Multiline error and warning messages overlap, in the Debugger.

![Godot_v4 1-dev2_win64_2ibVIIumDO_cropped](https://github.com/godotengine/godot/assets/13420573/9d49f426-80fa-4741-ae12-002e33ac0da4)

The lines separate when the mouse pointer is moved over the messages area.

![Godot_v4 1-dev2_win64_hLDo8PGppT_cropped](https://github.com/godotengine/godot/assets/13420573/1170cbbb-7c08-421e-94e3-b16c8847cf83)

It doesn't happen in:
- v4.0.3.rc1.official [2d74ee0e5]
- v4.0.2.stable.official [7a0977ce2]

Because they don't show multiline messages. The messages appear on a single line.

![Godot_v4 0 3-rc1_win64_ArM9g0CTyo_cropped](https://github.com/godotengine/godot/assets/13420573/24e6a4c0-69a4-4dc8-a2b3-c49b76de6b93)

### Steps to reproduce

- open the attached project: [issue, overlapping multiline text.zip](https://github.com/godotengine/godot/files/11472223/issue.overlapping.multiline.text.zip)
- run the project
- open the Debugger (at the bottom left, to the right of the Output button)
- open the tab: Errors

### Observed

The multiline error (red) and warning (yellow) messages are overlapping.

![Godot_v4 1-dev2_win64_2ibVIIumDO](https://github.com/godotengine/godot/assets/13420573/ce684090-5798-489a-918f-130a0131e557)

### Expected

The error/warning messages shouldn't overlap.

They become "unoverlapped" when the mouse pointer is moved over the overlapping messages area.
This is probably how they should appear as soon as the Debugger, Errors tab opens.

![Godot_v4 1-dev2_win64_hLDo8PGppT](https://github.com/godotengine/godot/assets/13420573/a54d0f1d-c79c-401d-8944-3a7949c84401)

### Minimal reproduction project

[issue, overlapping multiline text.zip](https://github.com/godotengine/godot/files/11472223/issue.overlapping.multiline.text.zip)

**Comment by Calinou** [comment] 2023-05-14 15:11
If you can [compile the engine from source](https://docs.godotengine.org/en/stable/development/compiling/index.html), you could look into [bisecting the regression](https://docs.godotengine.org/en/stable/community/contributing/bisecting_regressions.html) to greatly speed up troubleshooting.

**Comment by hakro** [comment] 2023-05-14 17:13
I had the same issue on 4.1.dev2 using the MRP.

But it seems fixed in master already, using the build against https://github.com/godotengine/godot/commit/fb10f45efe52e330496e325b6b7efd0e52f769b0

![2023-05-14_19-07](https://github.com/godotengine/godot/assets/3624853/aa326b23-aea3-4b71-bc3d-bd8fc35bc353)

**Comment by kleonc** [comment] 2023-05-14 17:35
Looks like (partially) a duplicate of #76507 (fixed by #76532).

Probably the timings should be made to be shown in a single line like before? :thinking: cc @dalexeev

Before:
> ![Godot_v4 0 3-rc1_win64_ArM9g0CTyo_cropped](https://user-images.githubusercontent.com/13420573/238193441-24e6a4c0-69a4-4dc8-a2b3-c49b76de6b93.png)

Now:
> ![2023-05-14_19-07](https://user-images.githubusercontent.com/3624853/238200347-aa326b23-aea3-4b71-bc3d-bd8fc35bc353.png)

**Comment by dalexeev** [comment] 2023-05-14 17:54
This led to a lot more consequences than I imagined. We should probably add wrap/ellipsis mode for columns/cells, see https://github.com/godotengine/godot/pull/76532#discussion_r1180062076. I will try to implement it.

**Comment by joao-pedro-braz** [comment] 2023-05-21 14:58
Just to add to the discussion, this also happens in other places within the Editor currently:

SceneTree:
![image](https://github.com/godotengine/godot/assets/37230465/8ab8c611-478c-45b9-8e00-9e94ea77b621)

FileSystemTree:
![image](https://github.com/godotengine/godot/assets/37230465/d55f5b05-f12b-49d4-9888-5fa454f90a8e)

**Closed** 2023-06-07 09:10 UTC
Labels: bug, topic:editor, regression, topic:gui
