### ISSUE TITLE
Object export variables share data between instances

### ISSUE THREAD

**Issue by nathanfranke** [godotengine/godot#52451] opened 2021-09-06 22:40 UTC
### Godot version

3.3.3 stable

### System information

Arch btw on 5.13.13-zen1-1-zen

### Issue description

`Scene.gd`:
```py
extends Node

func _ready() -> void:
	var list1 := TestList.new()
	var list2 := TestList.new()
	
	list1.contents.push_back("a")
	list1.contents.push_back("b")
	
	print(list1.contents)
	print(list2.contents)
```

`TestList.gd`:
```py
extends Object
class_name TestList

export var contents := []
```

Expected output:
```
[a, b]
[]
```

Actual output:
```
[a, b]
[a, b]
```

Note: Output works as expected if `contents` is not `export`.

### Steps to reproduce

1) Run the MRP

### Minimal reproduction project

[Test4.zip](https://github.com/godotengine/godot/files/7117951/Test4.zip)

**Comment by KoBeWi** [comment] 2021-09-06 23:20
Duplicate of #16478

**Closed by KoBeWi** 2021-09-06 23:20 UTC
