### ISSUE TITLE
OS.execute doesn't work with shell pipes "|"

### ISSUE THREAD

**Issue by git2013vb** [godotengine/godot#37440] opened 2020-03-30 19:00 UTC
**Godot version:**
3.2.1 stable mono
**OS/device including version:**
Debian 10
**Issue description:**
I tried to use `"nmcli device status | grep DEVICE"` with OS.Execute
but seems it don't work with pipes "|"
**Steps to reproduce:**
```
string[] _collectNetworkCards = { "device",  "status" , "|", "grep", "DEVICE"};
 Array output = new Array();
 OS.Execute("nmcli", _collectNetworkCards, true, output);
GD.Print(output.ToString());
```
I expect this result:
`DEVICE   TYPE      STATE      CONNECTION `

Instead I have an empty array

If I don't use "| grep DEVICE" I have the expected result.
```
DEVICE   TYPE      STATE      CONNECTION         
wlp13s0  wifi      connected  ******       
enp14s0  ethernet  connected  Wired connection 1 
lo       loopback  unmanaged  --  
```
**Minimal reproduction project:**
NA

**Comment by akien-mga** [comment] 2020-03-30 21:06
It works if you call a shell specifically:
```
	var out = []
	OS.execute("bash", ["-c", "nmcli device status | grep DEVICE"], true, out)
	print(out)
```

But yeah it should be possible to support pipes in `OS.execute` in theory, not sure why it's not working.

**Comment by akien-mga** [comment] 2020-03-30 21:12
It's not working because all arguments are enclosed in double quotes, same as #37291.

It can be worked around by closing and then reopening the automatically added quotes:
```
OS.execute("nmcli", ["\"device status | grep DEVICE\""], true, out)
```

**Comment by git2013vb** [comment] 2020-03-31 10:31
> It's not working because all arguments are enclosed in double quotes, same as #37291.
> 
> It can be worked around by closing and then reopening the automatically added quotes:
> 
> ```
> OS.execute("nmcli", ["\"device status | grep DEVICE\""], true, out)
> ```

Thank you @akien-mga I will use this workaround for now - I think it is the most appropriate and clean.
:)

**Comment by akien-mga** [comment] 2022-09-30 09:27
Duplicate of #37291 (same cause).

**Closed by akien-mga** 2022-09-30 09:27 UTC
Labels: bug, topic:porting
