### ISSUE TITLE
Issue with collision creation from mesh

### ISSUE THREAD

**Issue by nulledcc** [godotengine/godot#15010] opened 2017-12-24 18:29 UTC
**Godot version: 2.1.4 stable**

**OS/device including version: Windows 10 64bit 16GB 258SSD GTX1050**

**Issue description:**
When i tried to create collision from mesh it crashed with this errors
`ERROR: QuickHull::build: Condition ' O == E ' is true. Continuing..:
   At: core\math\quick_hull.cpp:401
ERROR: QuickHull::build: Condition ' !F2 ' is true. Continuing..:
   At: core\math\quick_hull.cpp:429
ERROR: QuickHull::build: Condition ' !F2 ' is true. Continuing..:
   At: core\math\quick_hull.cpp:429
ERROR: QuickHull::build: Condition ' O == E ' is true. Continuing..:
   At: core\math\quick_hull.cpp:401`

![image](https://user-images.githubusercontent.com/9316816/34328485-9b33d1de-e8f9-11e7-92cb-b6e1b5994bf7.png)

- [x] I searched the existing [GitHub issues](https://github.com/godotengine/godot/issues?utf8=%E2%9C%93&q=is%3Aissue+) for potential duplicates.

**Comment by qarmin** [comment] 2018-09-10 11:05
It also happening with 3.1 https://github.com/godotengine/godot/commit/53070437514e448c87f6cb31cf5b27a3839dbfa1

**Comment by akien-mga** [comment] 2019-01-19 13:38
Is this still reproducible in the current master branch?

If so, could you provide a test project that can reproduce it?

**Comment by hpvb** [comment] 2019-03-04 23:01
This is probably fixed now

**Comment by akien-mga** [comment] 2019-03-04 23:03
Closing, please comment if you can still reproduce it in 3.1 beta 10 or later.

**Closed** 2019-03-04 23:03 UTC
Labels: bug, topic:core

**Comment by hpvb** [comment] 2019-03-04 23:07
There are still messages on the console when the collision sibling is being created but they are purely cosmetic. I don't think this is really worth changing.

**Comment by Toshiwoz** [comment] 2019-03-05 22:28
I have tested just now, and in the console there's no error showing up anymore, just in the shell window.
It was little bothering before as it was slowing down the loading process too (IMHO), at least in my chase when I was using lots of trimesh collision shapes.
I am now using cubes to simplify, so for me it's ok to leve it as is.

**Comment by Jose-Moreno** [comment] 2019-04-21 19:17
Someone just reported this issue in Godot Engine's spanish facebook group, happening on 3.1 stable
https://www.facebook.com/groups/771679136238312/permalink/2571054849634056/

Here are the screenshots the user took: 

![image](https://user-images.githubusercontent.com/4912907/56474477-fce39000-643f-11e9-9750-6d10a74d8892.png)

![image](https://user-images.githubusercontent.com/4912907/56474478-010fad80-6440-11e9-95fa-a378b67fc410.png)

Unfortunately I don't have access to his project but I asked him to comment on this thread with a minimum reproduction project and to tag akien when he does. Cheers.

**Comment by faraazahmad** [comment] 2019-05-29 10:19
@Jose-Moreno  Also happening in v3.1.1 stable (Linux)
![image](https://user-images.githubusercontent.com/19265077/58549482-3bcbe900-8229-11e9-844b-69ab23aad5dd.png)

**Comment by jitspoe** [comment] 2020-04-17 00:41
I'm also getting these errors on some convex collision objects.  It seems to be purely cosmetic, as I haven't noticed any issues with the collision in-game, but the display is a bit funky.  For example, I have a pipe shape here, and the end of it has some overlapping edges when displayed:
![image](https://user-images.githubusercontent.com/7751182/79519382-b9573e00-8021-11ea-89d1-bb61552be7af.png)

I highlighted the end, since it's a bit difficult to see with the overlapping wireframes.  It really should just be an octagon, because it's a flat face, but some arbitrary edges were added, and these warnings were displayed in the Output log:

 core\math\quick_hull.cpp:399 - Condition "!F" is true. Continuing.
 core\math\quick_hull.cpp:402 - Condition "O == 0" is true. Continuing.

Some cases are much worse, and one of my scenes just spams like 2 pages of these errors.  It would be nice to get this fixed, so I don't miss real errors.


[pipes1_bend_angled_top.zip](https://github.com/godotengine/godot/files/4490346/pipes1_bend_angled_top.zip)

Here's the gltf file for that pipe.  Note that I'm using convcolonly for the collision and this was imported with 3.1 where it used the quick hull method for convex collision, so to repro this in 3.2, you'll probably have to generate collision from the mesh or change resource_importer_scene.cpp to use quick hull like this:

```
				} else if (_teststr(name, "convcolonly")) {
					shapes.push_back(mesh->create_convex_shape());
					collision_map[mesh] = shapes;
				}
```

**Comment by sent44** [comment] 2021-04-12 21:09
Godot v3.2.3 stable here
```
var v: PoolVector3Array = []
v.append(Vector3(0,0,0))
v.append(Vector3(1,0,1))
v.append(Vector3(0,0,1))
v.append(Vector3(-1,0,1))

shape = ConvexPolygonShape.new() # CollisionShape.shape
shape.points = v
```
Also produce error, collision still work. But if I move `Vector3(0,0,0)` to the bottom, error gone.
Well I modify this directly so this might be correct behavior, but same thing happen with `ArrayMesh`
```
var vex: PoolVector3Array = []
vex.append(Vector3(0,0,0))
vex.append(Vector3(1,0,1))
vex.append(Vector3(0,0,1))
vex.append(Vector3(-1,0,1))
#vex.append(Vector3(0,0,0))

var inx: PoolIntArray = [0,1,2,0,2,3]
#var inx: PoolIntArray = [1,2,0,2,3,0]

var arr: Array = []
arr.resize(ArrayMesh.ARRAY_MAX)
arr[ArrayMesh.ARRAY_VERTEX] = vex
arr[ArrayMesh.ARRAY_INDEX] = inx

var arr_mesh: ArrayMesh = ArrayMesh.new()
arr_mesh.add_surface_from_arrays(Mesh.PRIMITIVE_TRIANGLES, arr)

shape = arr_mesh.create_convex_shape() # CollisionShape.shape
print(shape.points) # Same array as vex (Even if it isn't index based mesh)
```
I think it is because [Mesh::create_convex_shape()](https://github.com/godotengine/godot/blob/94a0fc47f7b4e90f8973f9adbfd3312579ed2825/scene/resources/mesh.cpp#L233) just copy vertices data and put it in `ConvexPolygonShape.points` without properly reorganize to the same format that `quick_hull` thing want.

(I didn't test in Godot 4 yet, but I look at the code. I think it is still happen because `create_convex_shape` and error section of `quick_hull` thing is still (almost) same)

**Comment by justinbarrett** [comment] 2021-06-24 13:38
> 
> 
> Closing, please comment if you can still reproduce it in 3.1 beta 10 or later.

I am getting the error in 3.3.2 win10 64.

**Comment by Calinou** [comment] 2021-06-24 13:52
@justinbarrett Can you test the `3.x` branch with https://github.com/godotengine/godot/pull/48533 merged in? You can do so by compiling the latest `3.x` branch from source.

**Comment by sent44** [comment] 2021-06-24 18:53
Wow, never notice that this is already fixed.
Quick test on `almost` stable 3.3.2 build (not 3.x), no error.

**Comment by kreivi** [comment] 2021-07-09 09:28
Based on the discussion above I think this is redundant information but I'll book it down anyway.
I encountered this issue with **v3.2.3.stable-official** when I did this:
```
var body: MeshInstance = car_root.get_node("body")
var body_collision_shape: ConvexPolygonShape = body.mesh.create_convex_shape()
```
Output of errors was:
```noformat
 core/math/quick_hull.cpp:428 - Condition "!F2" is true. Continuing.
 core/math/quick_hull.cpp:401 - Condition "O == E" is true. Continuing.
```
I'm using mesh from [Kenneys Car Kit](https://kenney.nl/assets/car-kit) and as far as I can tell the mesh seems fine. However I'm seeing some weird looking orphan edges in the generated collision:
![orphan_edge](https://user-images.githubusercontent.com/9303286/125056325-c9d55780-e0b0-11eb-8dfa-17507c543738.jpg)

**Comment by justinbarrett** [comment] 2021-07-09 14:07
> 
> 
> @justinbarrett Can you test the `3.x` branch with #48533 merged in? You can do so by [compiling](https://docs.godotengine.org/en/stable/development/compiling/index.html) the latest `3.x` branch from source.
> 
> If you can still reproduce this on the latest `3.x` branch, please open a new issue as this one is very old. Make sure to include a minimal reproduction project.

The reason I do not open a new one(issue) is simply the fact that if you do any type of search, this link is what comes up...that is important for people that don't understand git hub or any type of repository/svn etc... I don't want to hide information simply because it is easier...even if it is the right thing.. It's inevitably robbing some poor kid of information.
Now that that is out of the way...
I wanted to point out that, when using bullet physics, these errors do not exist...I have not checked in 4.0 branch(master at this point I guess) 
just wanted to pass this information along.
