### ISSUE TITLE
Orthogonal camera shadows are lower resolution than perspective projection

### ISSUE THREAD

**Issue by ecmjohnson** [godotengine/godot#73472] opened 2023-02-17 01:22 UTC
### Godot version

v4.0.rc2.official [d2699dc7a]

### System information

Windows 10, Vulkan 1.3.224, NVIDIA GeForce RTX3080

### Issue description

While following [a tutorial](https://youtu.be/YiE9tcoCfhE), I observed curious shadows using an orthographic camera with a directional light. It appears changing the camera projection type between perspective and orthographic dramatically reduces the shadow quality.

With an orthographic camera:
![orthographic_shadows](https://user-images.githubusercontent.com/6766142/219522338-30cef7d4-4f54-4d04-87fe-a2607a04da62.gif)

Whereas with a perspective camera:
![perspective_shadows](https://user-images.githubusercontent.com/6766142/219522399-a3f6de81-d36e-40aa-bd26-07a308ef4ac9.gif)

Turning the shadow blur on the light to a low value shows the low resolution:
![orthographic_shadows_low_blur](https://user-images.githubusercontent.com/6766142/219522569-00e72e33-15df-4f5f-a2aa-d99e3e90dd7d.gif)

Even pushing the shadow map resolution to the maximum (16384) in the project settings results in less-than-ideal shadows:
![orthographic_shadows_max_rez](https://user-images.githubusercontent.com/6766142/219523487-65b09332-c185-430b-bc5e-2baff7fea847.gif)

I haven't tested myself in 3.x yet, but [the tutorial](https://youtu.be/YiE9tcoCfhE) shows the orthogonal shadows [working fine](https://youtube.com/clip/Ugkx-FTJbqyibUymxNG2QNCEdZOEMJUBuh-z) on 3.3.rc8

### Steps to reproduce

See minimal reproduction project. Create a plane, camera, directional light (shadows enabled), and some shadow caster. Set the camera to orthogonal projection.

### Minimal reproduction project

[3d-squash-the-creeps-issue.zip](https://github.com/godotengine/godot/files/10762216/3d-squash-the-creeps-issue.zip)

**Comment by Calinou** [comment] 2023-02-18 00:52
- Duplicate of https://github.com/godotengine/godot/issues/58332.

**Closed by Calinou** 2023-02-18 00:52 UTC
Labels: bug, archived, topic:rendering, topic:3d
