### ISSUE TITLE
Vulkan: Gaussian blur mipmaps aren't generated (linear downsampling is performed instead)

### ISSUE THREAD

**Issue by jimbeauphloyd** [godotengine/godot#55755] opened 2021-12-09 14:28 UTC
### Godot version

4.0 dev

### System information

Mac OSX

### Issue description

Reading texture information in a canvas shader using texture or textureLod introduces gaussian blurriness that is not pixel-perfect. 

Expected result (from Godot 3.x):

https://imgur.com/a/WfkHl1j

Actual result (from Godot 4 dev):

https://imgur.com/a/gfjBTDx

Reference post:  #50976

### Steps to reproduce

Shader code:

```
shader_type canvas_item;

uniform sampler2D my_texture : hint_albedo;

void fragment() {
	COLOR = textureLod(my_texture, UV, 0);
}
```

or

```
shader_type canvas_item;

uniform sampler2D my_texture : hint_albedo;

void fragment() {
	COLOR = texture(my_texture, UV);
}
```

### Minimal reproduction project

[PixelPerfectShader.zip](https://github.com/godotengine/godot/files/7685802/PixelPerfectShader.zip)

**Comment by colinmbo** [comment] 2022-05-11 18:50
Experiencing the same issue when trying to read from SCREEN_TEXTURE and I think it affects DEPTH_TEXTURE as well; however, I am working with spatial shaders, so I think it is a broader issue than just canvas_item. Seems like there's no clear way to change filtering options when using textureLod() or just texture() and it appears blurry regardless. This is especially noticeable with lower resolutions, as the output is unacceptable for pixel art.

**Comment by Calinou** [comment] 2022-05-11 21:28
`SCREEN_TEXTURE` mipmaps are generated with a fast box filter, which will always make lower-resolution mipmaps look blurry (as opposed to picking a single pixel out of the 4 pixels of the previous mip).

**Comment by Calinou** [comment] 2022-05-11 21:30
This is actually a duplicate of https://github.com/godotengine/godot/issues/57679.

**Closed by Calinou** 2022-05-11 21:30 UTC
Labels: bug, topic:rendering, regression, topic:shaders

**Comment by colinmbo** [comment] 2022-05-14 06:32
@Calinou Maybe I'm just confused, but how would one apply this solution for using the SCREEN_TEXTURE or DEPTH_TEXTURE? As mentioned previously, it appears that they both are affected by some kind of filtering that is made especially noticeable in lower resolutions. 

Is there any way to pass the SCREEN_TEXTURE into a sampler2D as you described? Or a way to define its filter mode elsewhere? Or maybe I'm mistaken and something else is causing the texture to appear blurry?

As far as I can tell, it doesn't appear that the SCREEN_TEXTURE can be accessed without it being filtered. The following is from a screen-space outline shader I wrote, but simply setting a quad to just render the SCREEN_TEXTURE also returns the same blurriness. As you can see, the geometry looks softened due to the filtering, and the outline itself is broken, leading me to believe the DEPTH_TEXTURE is also filtered by default.

![Screenshot (3)](https://user-images.githubusercontent.com/62091709/168413607-eb547ca5-3e1b-46c0-8e6c-e730d6aefcf9.png)
g

**Comment by Zireael07** [comment] 2022-05-14 07:17
Same here, I believe both are filtered

**Comment by clayjohn** [comment] 2022-05-14 08:09
Right now the samplers for the built in types are fixed when the shader is created. https://github.com/godotengine/godot/blob/6d5d9dd82ad263ae69afc01e73e47320c1f68c04/servers/rendering/renderer_rd/forward_clustered/scene_shader_forward_clustered.cpp#L731

We could likely extend this to allow users to specify a custom sampler somehow. Maybe through render nodes? Or perhaps properties attached to the shader resource? 

In the meantime, texture, textureLod, and texelFetch should allow users to get the full range of uses from the built in textures
