### ISSUE TITLE
Great bugs of the candidate!

### ISSUE THREAD

**Issue by Timofffee** [godotengine/godot#3636] opened 2016-02-09 16:05 UTC
**TileMap:**
1. Stripes appear (leaves texture). I use 32px textures. (Proof: http://vk.com/doc76044859_437262742)
2. Collision is not working correctly. I used SnapPixel for creating it. When moving the character podprygivaya, and sometimes even may fail. (Proof: http://vk.com/doc76044859_437262741)
3. When moving the camera up slightly TileMap starts to slow down and there is a feeling that starts to fall fps.

**Other:**
1. When you use the check and "murder" of an object he could become immortal with the most negative health. (Proof: http://vk.com/doc76044859_437262740)
Part of the code:

```
func _fixed_process(delta):
    if (health <= 0.0):
        queue_free()
```
- Operating System : Windows 8.1 x64
- Godot: 2.0 RC1 (last)
- Device: Wat? Notebook, Keyboard. 
- GPU Model: AMD Radeon HD 7610M
- Project: http://vk.com/doc76044859_437262786
- For a basis took Platformer2D.

**Comment by cimpresovec** [comment] 2016-02-09 18:23
Even thou you didn't create the issue by following the rules: https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md
I still went ahead and took a look at your project on Ubuntu 15.10 64bit and Windows 10 64bit, using the latest Godot build and with an Nvidia 850m card. I was not able to reproduce any of the problems you described. The game worked fine throughout many runs. The only problem I got was when using `queue_free` on the boxes, it was somehow called twice. I just replaced that call with `free` (since the boxes are not really running any code) and it fixed it, but some additional research would maybe help.

If you could prepare a simple project that isolates the problem, maybe then I would be able to help.

**Comment by akien-mga** [comment] 2016-02-10 07:14
I can't reproduce any of these bugs either using the provided test project.

**Comment by akien-mga** [comment] 2018-08-15 09:57
Closing as old.

**Closed by akien-mga** 2018-08-15 09:57 UTC
Labels: bug
