### ISSUE TITLE
.NET TypeLoadException when loading a specific setup

### ISSUE THREAD

**Issue by CynicalBusiness** [godotengine/godot#91232] opened 2024-04-26 22:35 UTC
### Tested versions

- Reproducible in: 4.2.2.stable, 4.2.1.stable

### System information

Windows 11

### Issue description

I am working with what was originally 4.2.1, but having since upgraded to 4.2.2 in attempt to resolve, and I keep running into:
```
modules/mono/mono_gd/gd_mono.cpp:539 - .NET: Failed to load project assembly. (User)
modules/mono/mono_gd/gd_mono.cpp:539 - .NET: Failed to load project assembly. (User)
modules/mono/mono_gd/gd_mono.cpp:539 - .NET: Failed to load project assembly. (User)
modules/mono/mono_gd/gd_mono.cpp:513 - .NET: Giving up on assembly reloading. Please restart the editor if unloading was failing. (User)
```

In the console, there's more detail: 
```
Unloading assembly load context...
Assembly load context unloaded successfully.
System.TypeLoadException: Could not load type 'ExampleStruct' from assembly 'Sanctuary, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at System.Reflection.RuntimeAssembly.<GetTypeCore>g____PInvoke|26_0(QCallAssembly __assembly_native, Byte* __typeName_native, IntPtr* __nestedTypeNames_native, Int32 __neste)
   at System.Reflection.RuntimeAssembly.GetTypeCore(QCallAssembly assembly, String typeName, ReadOnlySpan`1 nestedTypeNames, Int32 nestedTypeNamesLength, ObjectHandleOnStack re)
   at System.Reflection.RuntimeAssembly.GetTypeCore(String typeName, ReadOnlySpan`1 nestedTypeNames, Boolean throwOnError, Boolean ignoreCase)
   at System.Reflection.TypeNameParser.GetTypeFromDefaultAssemblies(String typeName, ReadOnlySpan`1 nestedTypeNames)
   at System.Reflection.TypeNameParser.GetType(String typeName, ReadOnlySpan`1 nestedTypeNames, String assemblyNameIfAny)
   at System.Reflection.TypeNameParser.GetTypeHelper(Char* pTypeName, RuntimeAssembly requestingAssembly, Boolean throwOnError, Boolean requireAssemblyQualifiedName)
   at System.Reflection.CustomAttribute._CreateCaObject(RuntimeModule pModule, RuntimeType type, IRuntimeMethodInfo pCtor, Byte** ppBlob, Byte* pEndBlob, Int32* pcNamedArgs)
   at System.Reflection.CustomAttribute.AddCustomAttributes(ListBuilder`1& attributes, RuntimeModule decoratedModule, Int32 decoratedMetadataToken, RuntimeType attributeFilterT)
   at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeModule decoratedModule, Int32 decoratedMetadataToken, Int32 pcaCount, RuntimeType attributeFilterType)
   at Godot.Bridge.ScriptManagerBridge.LookupScriptsInAssembly(Assembly assembly) in /root/godot/modules/mono/glue/GodotSharp/GodotSharp/Core/Bridge/ScriptManagerBridge.cs:line5
   at GodotPlugins.Main.LoadProjectAssembly(Char* nAssemblyPath, godot_string* outLoadedAssemblyPath) in /root/godot/modules/mono/glue/GodotSharp/GodotPlugins/Main.cs:line 154
ERROR: .NET: Failed to load project assembly.
   at: reload_project_assemblies (modules/mono/mono_gd/gd_mono.cpp:539)
```

The project actually builds (`dotnet build` runs fine), but it appears to fail once it gets to Godot.

The type name is "ExampleStruct" as it is a minimal repro; it looks like this:
```cs
using System.Collections.Immutable;
using Godot;

public partial class ExampleClass : Node
{
    public ExampleStruct Struct { get; set; }
}

public readonly record struct ExampleStruct(int Foo)
{
    public static ImmutableArray<ExampleStruct> Structs { get; set; } = ImmutableArray<ExampleStruct>.Empty;
    // ^ this thing, right here, is the problem ^
}
```
These two classes are in the same file for illustrative purposes, but the issue still appears if they are split.

The issue only appears if the following requirements are met:
- The relevant type must be a `struct` (i.e. `ExampleStruct`). Classes do not present this problem, whether it's a `record` or `readonly` has no effect.
- Said struct must have a `public static` property which is an `ImmutableArray` of that *same* struct. It only occurs with `ImmutableArray` and not something like `IEnumerable`.
- A class which extends from something Godot, i.e. Node, must exist which also has the relevant struct as a property type.
- The setting `[dotnet] project/assembly_name` must be assigned to `Sanctuary`. I really don't understand why this particular project name is problematic, but it only appears if set to that name specifically, as far as I can tell

These are very specific criteria for the error to appear I can only imagine this is some extreme edge case somewhere, but somehow I'm good at finding such things.

### Steps to reproduce

1. Create a new project
2. Set the setting `[dotnet] project/assembly_name` to `Sanctuary`
3. Create a new CSharp script
4. Paste the ExampleClass/ExampleStruct from above
5. Build the project from the editor

### Minimal reproduction project (MRP)

N/A

**Comment by raulsntos** [comment] 2024-04-26 23:37
You can't have a struct that contains itself, because then the runtime can't compute the struct. Your struct doesn't contain itself directly, but the way .NET works with generics ends up resulting in the same limitation for `ImmutableArray<T>` (or any other generic type) when `T` is the struct that contains it.

The same happens in non-Godot .NET projects. See this [example](https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEUCuA7AHwAEAGAAiIEYA6AYQgBsGYwMBLCPAZ2oEkBbfjgwBDYMwDcAWABQsgG4ioZAGYQIZALxk8MAO5kAoghH8ADswDKGXKwAUKAEwBKaXJlEAzGVgiAJpwMAJ4+LNB+ZFw2OKxGJuZW0fZseBhkAGLqzrIA3rJkBRTeVEhkAkKi4jAAglBQIkEAPMamFjDWthgAfGQdMRhcZDlkAOYwGBKR45MAvlplgsJizLX1TS0J7Und1IbmGEFuM0A===) in SharpLab. So this is an upstream issue in the .NET runtime and would have to be reported there.

I have found issue https://github.com/dotnet/runtime/issues/6924 in the .NET runtime repo that sounds like the same issue you are experiencing. It's supposed to be fixed in .NET 8, but as you can see in SharpLab which is running .NET 8 it still may happen in some scenarios, so you'll have to open a new issue if you are still having issues with .NET 8.

To answer some of your other questions:

> Said struct must have a `public static` property which is an `ImmutableArray` of that _same_ struct. It only occurs with `ImmutableArray` and not something like `IEnumerable`.

It should happen with any generic type that is a struct. `ImmutableArray<T>` is a struct so it's affected. `IEnumerable<T>` is an interface and `List<T>` is a class, so they are not affected.

> A class which extends from something Godot, i.e. Node, must exist which also has the relevant struct as a property type.

Just to be clear, the only requirement is that the type is _used_ so that the .NET runtime loads it. This is why in the SharpLab example I shared above I have to call the type constructor so the issue is triggered. Using the struct type as the type of a property in a Godot object would have the same effect because Godot will consume those types when loading the assembly.

> The setting `[dotnet] project/assembly_name` must be assigned to `Sanctuary`. I really don't understand why this particular project name is problematic, but it only appears if set to that name specifically, as far as I can tell

This should have no effect on the issue. The assembly name in the settings must match the name of the `.csproj` file, otherwise Godot won't be able to find your C# project and therefore it will not load it which would prevent triggering the issue.

**Closed by raulsntos** 2024-04-26 23:37 UTC
