### ISSUE TITLE
Godot crashed on empty project with one Spatial node

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#20499] opened 2018-07-26 21:52 UTC
Godot master 03e11c13bfb1649fc9cf9a460249bce5e7f07462
Windows 10 64 bits
OpenGL ES 3.0 Renderer: GeForce GTX 1060 6GB/PCIe/SSE2

I opened an existing empty project, created a Spatial node, opened editor settings, closed it, then Godot crashed. It just happened, cannot repro reliably, and I'm not sure what it is for now.

Here is the call stack:

![image](https://user-images.githubusercontent.com/1311555/43290629-8c0b7fb0-9126-11e8-93d6-0f72fa328fd3.png)

**Comment by guilhermefelipecgs** [comment] 2018-07-27 17:34
Probably duplicate of #20451, the log and conditions seems to be the same.

**Comment by akien-mga** [comment] 2018-08-16 11:49
Assuming duplicate of #20451, fixed by #20546.

**Closed by akien-mga** 2018-08-16 11:49 UTC
Labels: bug, topic:core
