### ISSUE TITLE
The content margin property of StyleBox not change while focus.

### ISSUE THREAD

**Issue by kaluluosi** [godotengine/godot#87236] opened 2024-01-15 22:42 UTC
### Tested versions

4.2.1-stable

### System information

Win10, Core I7-9700,RTX2080

### Issue description

I always to use the content margin of  StyleBox  to archive "Text floating" effect without any coding in Godot 3.5. 
But in Godot 4.2.1 , I found that theme_override_styles/focus don't apply content margin. It apply any other property but content margins. 
So while the button focus the content margin no changed.

### Steps to reproduce

![Snipaste_2024-01-16_06-32-15](https://github.com/godotengine/godot/assets/1620585/624ea87e-04ea-48e5-84e6-bf2258a1c453)

https://github.com/godotengine/godot/assets/1620585/13b16d9c-8cc3-43de-9353-9f4cbc0046e2

![Snipaste_2024-01-16_06-33-32](https://github.com/godotengine/godot/assets/1620585/487e0580-ac5e-4eb3-9388-043a0d0e0495)

https://github.com/godotengine/godot/assets/1620585/ab32ec08-f263-4669-bb66-53052da8a14a

### Minimal reproduction project (MRP)

[theme-margin-bug-on-focus.zip](https://github.com/godotengine/godot/files/13943514/theme-margin-bug-on-focus.zip)

**Comment by AThousandShips** [comment] 2024-01-15 22:45
Duplicate of https://github.com/godotengine/godot/issues/85095

**Closed by AThousandShips** 2024-01-15 22:45 UTC
