### ISSUE TITLE
Godot 4 rc3: Rigid 3d automatically moves without any impact

### ISSUE THREAD

**Issue by dqdthanhthanh** [godotengine/godot#73778] opened 2023-02-22 19:44 UTC
### Godot version

v4.0.rc3.official (7e79aead9)

### System information

Mac Air M1 2020

### Issue description

3D Physics: Rigid 3d automatically moves without any impact

https://user-images.githubusercontent.com/57259604/220741554-e9c3b5b1-f9f7-455c-85f1-25fb1bc4311d.mp4

### Steps to reproduce

Create a base 3d scene which rigid cylinder and static map. Turn on axis_lock_angular_x and axis_lock_angular_y on rigid body. Run scene the cylinder will automatically moves without any impact.
I converted my project from 3.5 to 4 rc and got this error. So I created another project to test to see if it appeared, the result was like this

### Minimal reproduction project

[GodotProject.zip](https://github.com/godotengine/godot/files/10807662/GodotProject.zip)

**Comment by Calinou** [comment] 2023-02-22 20:51
Duplicate of https://github.com/godotengine/godot/issues/61827 and/or https://github.com/godotengine/godot/issues/62819 (the MRP uses a thin floor collision shape).

As a workaround, make your floor's collision shape thicker (i.e. make it extend *below* the floor).

**Closed by Calinou** 2023-02-22 20:51 UTC

**Comment by dqdthanhthanh** [comment] 2023-02-22 21:12
> Duplicate of #61827 and/or #62819 (the MRP uses a thin floor collision shape).
> 
> As a workaround, make your floor's collision shape thicker (i.e. make it extend _below_ the floor).

Thanks, i tested with big floor, that does improve a bit. But the cylinder still moves on its own.

https://user-images.githubusercontent.com/57259604/220759867-c432950c-63c9-41f3-9435-a10c3cde0078.mp4

**Comment by Calinou** [comment] 2023-02-22 22:04
> But the cylinder still moves on its own.

Cylinder collisions have many issues in GodotPhysics (also in 3.x – you didn't notice them there because Godot 3.x uses Bullet by default). I recommend using box or capsule collisions instead.

**Comment by dqdthanhthanh** [comment] 2023-02-22 22:21
> > But the cylinder still moves on its own.
> 
> Cylinder collisions have many issues in GodotPhysics which are already tracked on GitHub. This is also the caes in 3.x, but you didn't notice them there as Godot 3.x uses Bullet by default (while Godot 4.0 no longer has Bullet physics).
> 
> I recommend using box or capsule colliders instead (or a cylinder converted to trimesh, for static bodies).

Thanks for the details, that why my project physics look weird when I switch to godot 4.

**Comment by wjagodfrey** [comment] 2023-08-14 04:01
Have the same issue with thin items. Making things thicker doesn't help if the object, in this case a candy bar, needs a thin collider.
