### ISSUE TITLE
Editor always focuses "Debugger" tab when running the project

### ISSUE THREAD

**Issue by XReaper95** [godotengine/godot#75290] opened 2023-03-24 14:03 UTC
### Godot version

v4.0.1.stable.official.cacf49999

### System information

Windows 11 and Linux (6.1.19-1-MANJARO)

### Issue description

When hitting the play button, the editor focuses on the "Output" tab, this behavior can be disabled with the property `run/output/always_open_output_on_play`. After being disabled, it then changes the focus to the "Debugger" tab, every time, but there is no option to disable this, at least I didn't find one. It is a usability problem because it will close the console tabs like "Animation" and "Shader Editor", interrupting the workflow, IMO that should only happen when a breakpoint is hit. This doesn't happen in v3.5.2.

### Steps to reproduce

1 - Disable `run/output/always_open_output_on_play`.
2 - Hit the "Play" button.

### Minimal reproduction project

An empty project will do.

**Comment by Calinou** [comment] 2023-03-24 17:08
- Duplicate of https://github.com/godotengine/godot/issues/66496.

**Closed by Calinou** 2023-03-24 17:08 UTC

**Comment by Zentrophy** [comment] 2023-06-02 09:34
You can easily bypass this by writing a simple plug-in that calls hide_bottom_panel () when _apply_changes () is called and get_editor_interface ().is_playing_scene () is true.  You have to set a timer first, but it's how I've dealt with it until this problem gets fixed...

**Comment by XReaper95** [comment] 2023-06-06 15:40
> You can easily bypass this by writing a simple plug-in that calls hide_bottom_panel () when _apply_changes () is called and get_editor_interface ().is_playing_scene () is true. You have to set a timer first, but it's how I've dealt with it until this problem gets fixed...

Interesting, I'll try that, thanks!
