### ISSUE TITLE
[C#] -- Socket error 10054 with Wait for debugger enabled

### ISSUE THREAD

**Issue by Teashrock** [godotengine/godot#32152] opened 2019-09-15 19:15 UTC
**Godot version:**
3.1.1 Mono Stable x64

**OS/device including version:**
Windows 10

**Issue description:**
Socket error 10054 when "Wait for debugger" is set in Project Settings -> Mono -> Debugger Agent.

**Steps to reproduce:**
1. Create any Mono project.
2. Set "Wait for debugger" in Project Settings -> Mono -> Debugger Agent.
3. Launch project.
4. Get a crash with subject error message.

**Minimal reproduction project:**
Not needed.

**Comment by Calinou** [comment] 2019-09-15 21:20
Duplicate of #28678.

**Closed by Calinou** 2019-09-15 21:20 UTC
