### ISSUE TITLE
Overriding engine functions with GDScript do not works in some situations

### ISSUE THREAD

**Issue by Uniformbuffer3** [godotengine/godot#63705] opened 2022-07-31 02:17 UTC
### Godot version

v4.0.alpha.custom_build [a32f84dda]

### System information

Linux PopOS Intel HD Graphics 4600 on Mesa 22.0.1

### Issue description

Hi, in the game i'm developing i often override the `add_child` function to make sure only the nodes i want are added and throw errors otherwise, but i have noticed there are some situations where the override is ignored and the original engine function is called.

I have isolated the problem in a test project that i add just below, but in short, when invoking the `add_child` method from a variable declared as member of a class, the original engine method is invoked. Meanwhile if the same is done on a variable declared locally within a function, it works perfectly fine.

This problem seems to only affect engine overrided functions, it works fine when overriding functions of other classes.

Thanks for listening and for your hard work, have a good day.

### Steps to reproduce

- Create a `main` scene with an associated script (that i will just call `main` from now on)
- Create a new class `MyClass` that overrides `add_child` by printing something on the terminal.
- Add to `main` the following `var myclass: MyClass`
- Add to `main` a `_ready` function with the following content: 
```
self.myclass = MyClass.new()
self.myclass.add_child(Node.new())
```

When the last row is executed, the overrided `add_child` of the class `MyClass` is not invoked.
On the other hands, when doing the same, but declaring `var myclass: MyClass` within the `_ready` instead will make it works correctly.

### Minimal reproduction project

[OverridingTest.zip](https://github.com/godotengine/godot/files/9227894/OverridingTest.zip)

**Comment by KoBeWi** [comment] 2022-07-31 08:53
Duplicate of #55024
This is not supposed to work at all 🤔

**Closed by KoBeWi** 2022-07-31 08:53 UTC
