### ISSUE TITLE
Godot 4 - choppy movement when sliding one object around another

### ISSUE THREAD

**Issue by zeravikm** [godotengine/godot#66917] opened 2022-10-05 07:09 UTC
### Godot version

v4.0.beta2.official.f8745f2f7

### System information

Windows 11 x86_64, Vulkan API 1.2.0 (mobile renderer), NVIDIA GeForce RTX 2060

### Issue description

When sliding CharacterBody3D with capsule collision shape around StaticBody3D with cylindrical collision shape, CharacterBody3D movement is choppy, moving back and forth randomly.

https://user-images.githubusercontent.com/69868153/193999292-11705a6c-25ec-40f4-80ec-04f51ac2a2ce.mp4

![scene](https://user-images.githubusercontent.com/69868153/193999409-a6503cd3-72af-4832-87a1-fb2dc8920896.png)
![code](https://user-images.githubusercontent.com/69868153/193999417-b44c1d61-7216-4319-88a5-86d777353e12.png)

### Steps to reproduce

Run sample project and slide the ship with arrow keys around the island.

### Minimal reproduction project

[sample-project.zip](https://github.com/godotengine/godot/files/9713400/sample-project.zip)

(Sample project contains assets from https://kenney.nl/ published under CC0 1.0 Universal Public Domain licence, free to use)

**Comment by anyanyang** [comment] 2022-10-14 13:31
I'm seeing very similar behaviour in a new project, also Godot 4, beta 2.  I have a CharacterBody3D with a capsule mesh + collider, sitting on a SphereMesh.

The snappy behaviour for me occurs right at the pole of the sphere, where all the edges meet.  In the gif below you'll see me trying to move around smoothly, but struggling in that area around the pole:

![snappy](https://user-images.githubusercontent.com/98826731/195858961-b304bc1d-3202-4e8b-b343-e768acf023a6.gif)

For context, here is the mesh as seen in Godot's preview:

<img width="884" alt="mesh" src="https://user-images.githubusercontent.com/98826731/195859261-57b03d52-987f-495f-94fa-76bd2dfa06dd.png">

**Comment by Rytelier** [comment] 2022-10-17 18:50
Likely related to the issue here - I have character body also with capsule collider, with gravity programmed in and jumping. And when jumping at colliders, it sometimes gets jitters, push backs, jump being blocked at beginning or even something that looks like teleports

 https://user-images.githubusercontent.com/45795134/196258284-6a38fed0-4d9c-46f6-9e96-128414dfe324.mp4

**Comment by DezBoyle** [comment] 2022-11-07 06:42
Same issue here -
The characterbody snaps around and gets stuck on corners
https://user-images.githubusercontent.com/41555304/200242105-b1aa2596-a1ed-4180-954d-84d5551be742.mp4

**Comment by DezBoyle** [comment] 2022-11-07 06:44
https://user-images.githubusercontent.com/41555304/200242315-58e9a91c-6530-4764-aee9-c4ce0922f279.mp4

Same issue here -
The CharacterBody3D gets stuck and jitters around when colliding with edges

**Comment by evan-gordon** [comment] 2023-01-15 20:32
+1 to this issue. I've got a character body player that has lots of weird interactions when interacting with ConvexPolygonShape3Ds in my game. I've experienced this in every Godot 4 beta version that I've tried. (3, 8, 10, 12)

**Comment by rburing** [comment] 2023-01-27 10:55
The capsule-cylinder collision from the minimal reproduction project in this issue is fixed in 4.0 beta 15. For the other cases reported in the comments here, please check again in the latest beta (since we've had more collision fixes merged recently), and create a new issue **with a minimal reproduction project** if the problem is still present.

**Closed by rburing** 2023-01-27 10:55 UTC
Labels: bug, confirmed, topic:physics, topic:3d

**Comment by prominentdetail** [comment] 2023-01-27 19:07
> The capsule-cylinder collision from the minimal reproduction project in this issue is fixed in 4.0 beta 15. For the other cases reported in the comments here, please check again in the latest beta (since we've had more collision fixes merged recently), and create a new issue **with a minimal reproduction project** if the problem is still present.

Filed a new bug since there are still issues:
https://github.com/godotengine/godot/issues/72198
