### ISSUE TITLE
Progress bar visually fills more than its value indicates

### ISSUE THREAD

**Issue by peter-rocchio** [godotengine/godot#75180] opened 2023-03-21 10:05 UTC
### Godot version

Godot4.0 Stable

### System information

Windows 10, Vulkan

### Issue description

The Progress bar control node will visually fill more than its value indicates that it should.  This is especially noticeable for low resolution games with very small progress bars.

The texture progress node does not suffer from the same issue as can be seen in the screenshot.

![image](https://user-images.githubusercontent.com/25456663/226573419-a68d667a-d0a1-48c2-a06d-7a94a2dd28ae.png)

### Steps to reproduce

1. Add a Progress Bar node
2. Set the box styles to not have any corners, aliasing or shadows (for clarity)
3. Set the minimal value to 0, maximum to 1, and value to 0.5
4. Observe that the fill covers more than 50% (62.5% in the screenshot)
5. Repeat with texture progress and observe the fill correctly covers half the texture.

### Minimal reproduction project

N/A

**Comment by YuriSizov** [comment] 2023-03-21 10:25
Thanks for your report, please attach a reproduction project.

**Comment by Calinou** [comment] 2023-03-21 17:30
This is likely due to margins for the progress stylebox in the default theme.

**Comment by peter-rocchio** [comment] 2023-03-23 10:02
> This is likely due to margins for the progress stylebox in the default theme. Removing the margin fixes the issue, but it may also result in the stylebox not covering the full progress bar on its edges (as the background has a margin).

This was it, I imported the settings and didn't see the content margin settings.  When I went to make a clean project I noticed them since I created new style boxes instead of editing the old ones.  Here is the clean project example.

[ProgressBarBug.zip](https://github.com/godotengine/godot/files/11049452/ProgressBarBug.zip)

**Comment by YuriSizov** [comment] 2023-03-25 13:11
Closing per the comment above.

**Closed by YuriSizov** 2023-03-25 13:11 UTC
Labels: archived, topic:gui
