### ISSUE TITLE
AnimationPlayer - Animation speed (FPS) affects Animation Length (Frames) on adjustment.

### ISSUE THREAD

**Issue by Blewy31** [godotengine/godot#64887] opened 2022-08-25 15:30 UTC
### Godot version

3.5.stable

### System information

Windows 11

### Issue description

When creating animations, if I adjust the speed of the animation (using FPS), the length (using frames) gets automatically adjusted, as if the length is dependent on speed. If I adjust the length first, I need to adjust it twice, versus, if I adjust the speed first, I just have to adjust both once.

### Steps to reproduce

Create a kinematicbody2d node, add a sprite child, an animation player child, and a collisionshape2d child. Then try to set up an animation and make adjustments to the length and speed of the animation.

**Comment by TokageItLab** [comment] 2022-11-17 04:01
Duplicate of #59784, will be fixed by #68766.

**Closed by TokageItLab** 2022-11-17 04:01 UTC
Labels: bug, topic:editor, topic:animation
