### ISSUE TITLE
Changing AnimationNodeAnimation.Animation results in crash, if the animation is dynamically added

### ISSUE THREAD

**Issue by mysticfall** [godotengine/godot#19876] opened 2018-07-01 06:12 UTC
**Godot version:**
`master` / 0ffec7daf

**OS/device including version:**
_Manjaro Linux 17.1_

**Issue description:**
If you add an anination to `AnimationPlayer` programatically then change `Animation` property of an `AnimationNodeAnimation` node contained in an associated `AnimationTree`, the game will crash if you attempt to play it using `AnimationNodeOneShot` with the following output:

```
Stacktrace:

/proc/self/maps:
400b5000-400c5000 rwxp 00000000 00:00 0 
40434000-407fc000 rwxp 00000000 00:00 0 
40e39000-40e49000 rwxp 00000000 00:00 0 
41138000-41148000 rwxp 00000000 00:00 0 
41809000-4180b000 r-xs 00000000 00:2d 192                                /tmp/.glDqt8YB (deleted)
41b8e000-41c2f000 rw-p 00000000 00:00 0 
55809b885000-5580a0049000 r-xp 00000000 08:07 3151468                    /usr/bin/godot
5580a0249000-5580a034c000 r--p 047c4000 08:07 3151468                    /usr/bin/godot
5580a034c000-5580a0352000 rw-p 048c7000 08:07 3151468                    /usr/bin/godot
5580a0352000-5580a036a000 rw-p 00000000 00:00 0 
5580a0a79000-5580af5da000 rw-p 00000000 00:00 0                          [heap]
7f3c24000000-7f3c24021000 rw-p 00000000 00:00 0 
7f3c24021000-7f3c28000000 ---p 00000000 00:00 0 
7f3c2c000000-7f3c2c270000 rw-p 00000000 00:00 0 
7f3c2c270000-7f3c30000000 ---p 00000000 00:00 0 
7f3c30000000-7f3c30060000 rw-p 00000000 00:00 0 
7f3c30060000-7f3c34000000 ---p 00000000 00:00 0 
7f3c34000000-7f3c3414f000 rw-p 00000000 00:00 0 
7f3c3414f000-7f3c38000000 ---p 00000000 00:00 0 
7f3c38000000-7f3c3804a000 rw-p 00000000 00:00 0 
7f3c3804a000-7f3c3c000000 ---p 00000000 00:00 0 
7f3c3c000000-7f3c3c021000 rw-p 00000000 00:00 0 
7f3c3c021000-7f3c40000000 ---p 00000000 00:00 0 
7f3c42c00000-7f3c42d00000 rw-p 00000000 00:00 0 
7f3c42d49000-7f3c44d4a000 rw-p 00000000 00:00 0 

Unhandled Exception:
System.NullReferenceException: Object reference not set to an instance of an object
```

**Comment by akien-mga** [comment] 2018-08-26 13:53
Reopening as it seems the crash still happens, as per https://github.com/godotengine/godot/pull/20628#issuecomment-415945008.

**Comment by mysticfall** [comment] 2018-09-01 14:38
I just checked my build today, and It turned out the relevant commit(f6c0a3f) was indeed missing. Sorry for the hassle!

I suppose I missed the conflict message when I tried to cherry pick the commit and assumed it was merged. Anyway, feel free to close this issue and I'll repoen if necessary later, after I'll be able to use the master branch again.

**Comment by mysticfall** [comment] 2018-09-16 08:38
Finally, I managed to make my project properly build again with the latest master and I did another test of this issue.

Unfortunately, it seems to happen most of the times still(only rarely it worked without crashing but I haven't been able to reproduce it reliably yet).

This time, I double checked the changes made in f6c0a3f are included in my build. And the stacktrace shows it crashes at `AnimationTree::_process_graph` in the following line, apparently because it refers to a track with a wrong index (from the old animation):

```c++
if (track->type != a->track_get_type(i)) {
```

**Comment by reduz** [comment] 2018-11-21 01:01
I can't reproduce this bug, sorry. Please make a small demo project.

**Comment by mysticfall** [comment] 2018-11-21 01:16
Ok, then please feel free to close the issue.

For now, I can't even use the latest master any more due to some other issue. So, once I'll be able to use the latest master again and happen to revisit the animation part, I'll try to reproduce it and reopen the issue with an example project if needed.

**Comment by akien-mga** [comment] 2018-11-21 07:56
Closing for now then.

**Closed by akien-mga** 2018-11-21 07:56 UTC
Labels: bug, topic:editor
