### ISSUE TITLE
SpotLight Shadows cause wavy artifacts when parallel to a surface

### ISSUE THREAD

**Issue by Aimarekin** [godotengine/godot#47168] opened 2021-03-19 15:34 UTC
**Godot version:** 3.2.3 Stable

**OS/device including version:** Windows 10, GLES3, NVIDIA  GeForce GTX 1050/PCIe/SSE2 (Driver version 27.21.14.6192, published 10/03/2021)

**Issue description:** SpotLights cause wavy artifacts when they're parallel to the ground. These waves gradually disappear as you rotate the surface/light. Although they can be removed by enabling reverse cull fading, I don't see why this would be expected behavior. Perhaps it has something to do with my GPU or drivers.
[See pictures](https://imgur.com/a/ZCK7kkl)

**Steps to reproduce:** Create a SpotLight and a MeshInstance with a plane mesh below. Move the SpotLight up, and look at the plane. The waves are more visible in dark environments.

**Minimal reproduction project:**
[WavyArtifacts.zip](https://github.com/godotengine/godot/files/6172412/WavyArtifacts.zip)

**Comment by Calinou** [comment] 2021-03-19 17:38
Duplicate of https://github.com/godotengine/godot/issues/12028.

**Closed by Calinou** 2021-03-19 17:38 UTC
