### ISSUE TITLE
Godot window positions aren't being remembered

### ISSUE THREAD

**Issue by aegarpyke** [godotengine/godot#1097] opened 2015-01-03 03:51 UTC
I'm on Windows 7.

All Godot windows always start at the top left (0,0) of my monitor. This includes the Project List, the Main Editor, and the game when it's built and run using Godot. It doesn't remember that I move the windows around, nor does it remember that I maximize the Editor every time.

Not having to worry about this every time I launch the Editor or build games would be great.

**Comment by akien-mga** [comment] 2016-02-04 06:36
Closing as a duplicate of the newer #3578, since it makes it more visual why this enhancement would definitely be needed ;)

**Closed by akien-mga** 2016-02-04 06:36 UTC
Labels: feature proposal, topic:editor, usability
