### ISSUE TITLE
Texture Atlas import does not work

### ISSUE THREAD

**Issue by chucklepie** [godotengine/godot#39205] opened 2020-05-31 18:24 UTC
**Godot version:**
3.2.1 stable on linux

Following instructions here for creating atlases from existing images, nothing happens.
https://godotengine.org/article/atlas-support-returns-godot-3-2

1. Select images from godot 
2. Select import and choose texture atlas
3. Enter name and select region
4. Accept and restart
5. Nothing is created

![1](https://user-images.githubusercontent.com/12863685/83359726-07c36080-a374-11ea-9760-3ed3b0caf6e8.png)
![2](https://user-images.githubusercontent.com/12863685/83359727-085bf700-a374-11ea-99d0-542df9b539ca.png)
![3](https://user-images.githubusercontent.com/12863685/83359728-08f48d80-a374-11ea-8cff-568b081b4224.png)
![4](https://user-images.githubusercontent.com/12863685/83359730-08f48d80-a374-11ea-8e36-c3bca150c92b.png)
![5](https://user-images.githubusercontent.com/12863685/83359731-098d2400-a374-11ea-8151-fba5c73ac948.png)

There is a video here, if you have access to godot fb page
https://godotengine.org/article/atlas-support-returns-godot-3-2

Also, changing to mesh2d does nothing and if I select to save as texture array instead, nothing happens either.

Maybe I'm missing something completely with this feature, because godot is happy for me to carry out the whole process even if I have both atlas file and import mode disabled, so honestly I have no idea what Godot is trying to do when you select to import as something other than a texture...

**Comment by Calinou** [comment] 2020-05-31 19:25
Duplicate of #37071.

**Closed by Calinou** 2020-05-31 19:25 UTC
