### ISSUE TITLE
Signal body_shape_entered can give wrong body_shape value when colliding with TileMap

### ISSUE THREAD

**Issue by Anaxagor14** [godotengine/godot#26138] opened 2019-02-21 21:27 UTC
**Godot version:**

Godot 3.1 beta1

**OS/device including version:**

Windows 10 Home build 17763.195

**Issue description:**

When using the `body_shape_entered(body_id, body, body_shape, area_shape)` signal on an Area2D setup to collide with the TileMap, the parameter `body_shape` can be set to a value that is wrong. That is because in that case, `body_shape` is the *quadrant-based* shape id (index) of the collider tile.

This means that as soon as there is more than one quadrant the value is of no use. I have seen examples where people would use it as an index like so, but is will not work 100%:
```
        var cellv : Vector2 = body.get_used_cells()[body_shape]
        var tile_id : int = body.get_cellv(cellv)
```
(from: https://github.com/godotengine/godot/issues/24739#issuecomment-451529763)

Granted, maybe @ekliot and I are trying to use that parameter the wrong way, but lacking documentation on the subject, I see no other way to use it in a meaningful way.

I have tried a workaround where I recreate quadrants since their size is known, and wanted to use `body_shape` as an index into those user-made quadrants but since the signal does not give a position or other meaningful data, I cannot be sure in which quadrant to even *use* the `body_shape` param.

My ultimate goal is to fetch the tile's shape and see if it is `one_way`, so projectiles in our game can pass through them, like so:
```
func _on_Area2D_body_shape_entered(body_id, body, body_shape, area_shape):
    var tset : TileSet = body.tile_set
    var cellv : Vector2 = body.get_used_cells()[body_shape]
    var tile_id : int = body.get_cellv(cellv)
    for shape_data in tset.tile_get_shapes(tile_id):
        if shape_data['one_way']:
            return
    queue_free()
```
Looking at the code, I see two places that deal with shape IDs and I'm not certain if one or both are the problem. My apologies if this is not useful or misleading; hopefully it helps. See `TileMap::update_dirty_quadrants` and the use of `shape_idx`. See also `BroadPhase2DHashGrid::create` where the `p_subindex` param is also arbitrary (also quadrant-based in this case; `CollisionObject2DSW::_update_shapes` just uses a `for` loop on shapes, same as `TileMap::update_dirty_quadrants`). Call order is: `update_dirty_quadrants -> Physics2DServerSW::body_add_shape -> CollisionObject2DSW::add_shape -> CollisionObject2DSW::_update_shapes() -> BroadPhase2DHashGrid::create`

**Steps to reproduce:**
See attached project, with two large 16x16 sets of tiles (in effect, two quadrants) and where two Nodes with an Area2D + CollisionShape2D are positioned far from each other, one on each set of tiles, with their `body_shape_entered` signal connected to a script printing the values sent. Both return the *same* values despite being so far from each other & colliding with different tiles entirely.

**Minimal reproduction project:**

[TestTileMapQuadrantBodyShape.zip](https://github.com/godotengine/godot/files/2891323/TestTileMapQuadrantBodyShape.zip)

**Comment by akien-mga** [comment] 2020-01-14 13:10
Duplicate of #24739.

**Closed by akien-mga** 2020-01-14 13:10 UTC
Labels: bug, topic:physics
