### ISSUE TITLE
MSAA causing texture bleed on sharp edges

### ISSUE THREAD

**Issue by czlowiekimadlo** [godotengine/godot#68887] opened 2022-11-19 15:49 UTC
### Godot version

3.5.1 stable

### System information

Windows 10, GLES3, RTX 3080 

### Issue description

When using a fairly simple geometry mesh with pixel-art textures, where filtering for albedo texture is turned off, and high precision of presentation is important, turning on MSAA (at any level) causes a single pixel of bleed on the edges of faces. That pixel is borrowed from a different face, that is bordering it on the texture file. If the colour is starkly different, it leads to jarring edges.
![msaa_bug](https://user-images.githubusercontent.com/649405/202859020-68ad421b-18a5-4abc-a252-82d841b1688f.png)

This report is from Windows 10 machine with RTX 3080, but is also reproducible on Linux and SteamDeck.

### Steps to reproduce

1. Import a simple model into the scene (cube is fine)
2. Add albedo texture, where some of the faces are bordered with other faces or fillers with jarringly different colour
3. Disable texture filtering
4. Enable MSAA
5. Observe edges of the cube

### Minimal reproduction project

I have created a project that reproduces the issue:
https://github.com/czlowiekimadlo/Godot_texture_bug
Or:
[Godot_msaa_texture_bug.zip](https://github.com/godotengine/godot/files/10047363/Godot_msaa_texture_bug.zip)

In the project, run it, or open the test scene and run it. Pressing any input bound to ui_accept will switch between MSAA modes 0 and 2. Observe the edges of the model in the middle of the screen.

**Comment by Calinou** [comment] 2022-11-19 16:42
Duplicate of https://github.com/godotengine/godot/issues/16337.

**Closed by Calinou** 2022-11-19 16:42 UTC
