### ISSUE TITLE
surface_get_material(0) not working

### ISSUE THREAD

**Issue by Lexpartizan** [godotengine/godot#32251] opened 2019-09-22 14:42 UTC
**Godot version:**
Godot_v3.1.1-stable_win64
**OS/device including version:**
Win 10 ver1607
**Issue description:**
if i try get material from mesh with mesh.surface_get_material(0) i receive null object.
**Steps to reproduce:**
in code
**Minimal reproduction project:**
in attach
[123.zip](https://github.com/godotengine/godot/files/3639850/123.zip)

**Comment by clayjohn** [comment] 2019-09-22 17:01
Duplicate of https://github.com/godotengine/godot/issues/31558

**Closed by clayjohn** 2019-09-22 17:01 UTC

**Comment by Lexpartizan** [comment] 2019-09-22 18:18
Sorry.
