### ISSUE TITLE
Reducing the Font Size while having the "Recent Scenes" list full creates space below "Clear Recent Scenes"

### ISSUE THREAD

**Issue by YeldhamDev** [godotengine/godot#12207] opened 2017-10-18 04:42 UTC
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
[Build](https://bintray.com/calinou/godot/editor) cc7f224

**Issue description:**
Very minor report, but in the **Scene > Open Recent** drop menu, the **Clear Recent Scenes** option has an extra space below it:
![screenshot at 2017-10-18 02-35-24](https://user-images.githubusercontent.com/30739239/31701245-b1d6774c-b3ad-11e7-989b-c3159e0605dd.png)

Here is the **Clear Recent Files** option for comparison:
![screenshot at 2017-10-18 02-35-49](https://user-images.githubusercontent.com/30739239/31701259-d866e748-b3ad-11e7-9a53-2d8d36fb0bb7.png)

**Comment by aswinmohanme** [comment] 2017-10-18 17:56
Cannot reproduce in latest build from master

**Comment by YeldhamDev** [comment] 2017-10-19 14:43
With more testing, I found out that it weirdly only happens when setting the font size smaller and having the recent scenes list being full. It also fixes itself when restarting and it's the only dropmenu with this behaviour.

**Comment by secondwind21** [comment] 2017-10-20 02:08
I reproduced this bug both for the "Clear Recent Scenes" and "Clear Recent Files" drop-downs. 

Steps to Reproduce:
1. Make sure there is data populating the "Clear Recent Scenes" or "Clear Recent Files" (whichever you're testing) dropdowns.
2. Go into Editor Settings and reduce the font size (I went from 14 to 10 and the change was substantial). 
3. View the dropdown again and there should be a large gap under the actual "Clear Recent x" button.

This can be quickly fixed by clicking the actual button, and then going back in to view the button again. 

After looking through the code, I'm pretty sure this is same issue for both dropdowns, and possibly others. The `set_as_minsize`, which is called when the recent scenes list is updated, is not being called when the font changes, so the size doesn't know to update until the list changes (or is cleared).

**Comment by seixasfelipe** [comment] 2017-10-20 10:51
I couldn't found the "Clear Recent Files" drop-down.

Just a minor correction in the issue description: It's **Scene > Open Recent** instead of **Scene > Open Scene** (at least on Windows)

**Comment by YeldhamDev** [comment] 2017-10-20 11:44
@seixasfelipe Fixed. The "Clear Recent Files" is in the Script Editor: **File > Open Recent**

**Comment by seixasfelipe** [comment] 2017-10-21 17:07
Done, everything is working, both drop-down are resized when the font size changes.

**Closed** 2017-10-21 21:41 UTC
Labels: enhancement, hacktoberfest, topic:editor
