### ISSUE TITLE
Viewport buttons push the sidebar off the screen area

### ISSUE THREAD

**Issue by lufog** [godotengine/godot#59332] opened 2022-03-19 22:17 UTC
### Godot version

v4.0.alpha.custom_build [81c2d7a82]

### System information

Windows 11, Vulkan Clustered

### Issue description

Viewport buttons push the sidebar off the screen area (my monitor resolution is 1600x900). I think you should move the buttons that do not fit to a new line, or make some kind of drop-down panel for them.

Or the ability to scroll them with the mouse wheel, like tabs in Firefox:

https://user-images.githubusercontent.com/10379487/159140221-f393b80a-67b0-494f-8b85-f1152d124ebb.mp4

### Steps to reproduce

https://user-images.githubusercontent.com/10379487/159139574-5a12e41c-a5d0-460a-9a8b-492116df1c34.mp4

### Minimal reproduction project

Not needed

**Comment by Calinou** [comment] 2022-03-19 22:57
Duplicate of https://github.com/godotengine/godot/issues/58052.

**Closed by Calinou** 2022-03-19 22:57 UTC
