### ISSUE TITLE
Safe lines don't follow line breaks

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#34127] opened 2019-12-05 20:37 UTC
Godot 3.2 beta2

The whole follwing code should be typed:

```gdscript
func _ready():
	var i := \
		42
```

However lines after the break are not hinted as safe:

![image](https://user-images.githubusercontent.com/1311555/70271792-01767200-179f-11ea-8549-2c9af7a82126.png)

**Comment by Calinou** [comment] 2020-06-05 14:25
Duplicate of #23667.

**Closed by Calinou** 2020-06-05 14:25 UTC
Labels: bug, topic:editor, topic:gdscript
