### ISSUE TITLE
Internal Script Error Opcode 0

### ISSUE THREAD

**Issue by creikey** [godotengine/godot#37003] opened 2020-03-12 08:24 UTC
**Godot version:**
3.2.1
**OS/device including version:**
Manjaro Linux
**Issue description:**
Occurs on a yield function sometimes.
**Steps to reproduce:**
Not sure yet, haven't made minimal reproduction project yet.
**Minimal reproduction project:**

**Comment by Calinou** [comment] 2020-03-12 08:35
Similar to #31093 maybe?

**Comment by vnen** [comment] 2020-03-12 12:09
I know the error message tells you to report, but without more information there's really nothing we can do. I'll assume this is a duplicate of #24684.

**Closed by vnen** 2020-03-12 12:09 UTC
