### ISSUE TITLE
Autocompletion hides under other GUI elements in some cases

### ISSUE THREAD

**Issue by Krzycho666** [godotengine/godot#4067] opened 2016-03-15 20:31 UTC
![screen](https://cloud.githubusercontent.com/assets/6615905/13792951/beb62c88-eaf4-11e5-8e54-2837920805b1.png)

Autocompletition hides under some other GUI elements when rendered near the workspace border. Should be retranslated in space ( to be sure that it's rendered inside visible workspace ) and moved to the front ( to prevent hiding by other elements ).

Godot 2.0.1, Windows 7.

**Comment by neikeq** [comment] 2016-03-15 21:14
Duplicate of #1257

**Closed by neikeq** 2016-03-15 21:14 UTC
