### ISSUE TITLE
Shortcut for Copy Node Path sets clipboard to incorrect values

### ISSUE THREAD

**Issue by Anixias** [godotengine/godot#63169] opened 2022-07-18 21:48 UTC
### Godot version

3.5 RC6

### System information

Windows 10

### Issue description

Manually copying a node's path by right-clicking it in the editor and selecting "Copy Node Path" will correctly copy the node's relative path to the clipboard. However, using the shortcut Ctrl + Shift + C will set the clipboard to a property path ("display/window/stretch/aspect", in my case). It appears to be the last modified property, or the last focused property.

### Steps to reproduce

1. Modify a project settings property.
2. Close the project settings.
3. Use Ctrl + Shift + C on a node within a scene's tree.
4. OS Clipboard will contain the property path, rather than the node's path.

**Comment by Calinou** [comment] 2022-07-18 21:52
Duplicate of https://github.com/godotengine/godot/issues/62866.

**Closed by Calinou** 2022-07-18 21:52 UTC
