### ISSUE TITLE
Changes are saved even if they are discarded when closing an unsaved script

### ISSUE THREAD

**Issue by Rindbee** [godotengine/godot#63151] opened 2022-07-18 14:19 UTC
### Godot version

v4.0.alpha12.official [2c11e6d9e]

### System information

Linux Mint 20.3, Vulkan, NVIDIA GeForce GTX 1050 Ti

### Issue description

Changes are saved even if they are discarded when closing an unsaved script.

[Peek 2022-07-18 22-04.webm](https://user-images.githubusercontent.com/30386067/179530679-990eab39-10f2-425f-ba43-265f7a09c604.webm)

### Steps to reproduce

1. Open a script;
2. Add something;
3. Use **Close**/**Close All**/**Close Other Tabs** to close it.
4. Click the **Discard** button in the popup dialog;
5. Reopen it to see the changes.

**Comment by heppocogne** [comment] 2022-07-31 04:03
I have tried to reproduce this problem and found that discarding is working correctly (files are not changed in filesystem) but re-opened script looks like as if its changes are saved.

**Comment by dzil123** [comment] 2022-09-11 10:31
Duplicate of #50578?

**Closed** 2022-09-15 22:05 UTC
Labels: bug, topic:editor
