### ISSUE TITLE
Export variable not updated in the custom class

### ISSUE THREAD

**Issue by DexterFstone** [godotengine/godot#84603] opened 2023-11-08 04:53 UTC
### Godot version

4.1.1 stable, 4.1.3 stable

### System information

Windows 10, Godot 4.1.1, Godot 4.1.3

### Issue description

hi
I created a new script called Unit and extended characterBody2d
after that create a new script and extend it from the Unit class
now if I add @export var to the Unit class, the extended class does not update in the inspector or editor at all, and need to reload the project or comment extends Unit and uncomment to refresh the class.

### Steps to reproduce

Create new script and add class_name A
![image](https://github.com/godotengine/godot/assets/92402263/ef8d4dd5-4637-49f9-9e4a-cc3d5b0a57fc)
now create new script and add extends A and class_name B.
and add it to scene.
![image](https://github.com/godotengine/godot/assets/92402263/a49b9705-07c8-4f0c-80c5-bbd285460eda)
now add export var in A class and as u can see B class not update in inspector.
![image](https://github.com/godotengine/godot/assets/92402263/96668557-0abf-495b-9843-fc98cdbb3157)

### Minimal reproduction project

N/A

**Comment by dalexeev** [comment] 2023-11-08 06:10
* Duplicate of #82998.
* Fixed by #83123 for 4.2.

Thanks for reporting the bug nonetheless!

**Closed by dalexeev** 2023-11-08 06:10 UTC
