### ISSUE TITLE
3D editor camera spins like crazy when switching scenes in the editor

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#20104] opened 2018-07-11 19:55 UTC
Godot 3.0.4

I suspect this is due to camera interpolation. In my opinion, this interpolation should be reset on scene switch.

https://youtu.be/nGeWGWW7Ou4

**Comment by vnen** [comment] 2018-07-11 20:01
Duplicate of #11764

**Closed by vnen** 2018-07-11 20:01 UTC
