### ISSUE TITLE
Can not assign .tscn file as main scene

### ISSUE THREAD

**Issue by volzhs** [godotengine/godot#3402] opened 2016-01-21 12:16 UTC
Filter has only ``*.scn, *.res, *.xscn, *.xml``

**Comment by neikeq** [comment] 2016-01-21 12:18
Could be duplicate of #2946

**Comment by akien-mga** [comment] 2016-01-21 12:41
Indeed, I've slightly edited the OP of #2946 to make sure this part of the issue is not forgotten.

**Closed by akien-mga** 2016-01-21 12:41 UTC
