### ISSUE TITLE
File rename (and some other operations) in FileSystem moves keyboard focus out of FileSystem

### ISSUE THREAD

**Issue by miv391** [godotengine/godot#82774] opened 2023-10-04 09:44 UTC
### Godot version

v4.2.dev6.official [57a6813bb]

### System information

Godot v4.2.dev6 - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1060 6GB (NVIDIA; 31.0.15.3640) - Intel(R) Core(TM) i5-3570K CPU @ 3.40GHz (4 Threads)

### Issue description

File rename in FileSystem moves keyboard focus out of FileSystem

When a file is renamed in FileSystem, keyboard focus is lost. There doesn't seem to be any way to move focus back to FileSystem by using keyboard only. You need to click FileSystem by mouse.

Some other operations do the same. Losing the focus makes it quite annoying to make operations to multiple files.

Keyboard focus is lost:
- rename 
- duplicate 
- create new folder 

Keyboard focus is kept:
- delete 
- create new script / text file / resource

### Steps to reproduce

1. Select `icon.svg` 
2. Press F2 to rename the file
3. Try to move in the FileSystem using keyboard or renaming the file again by pressing F2
-> nope, that doesn't work

### Minimal reproduction project

N/A

**Comment by arujjval** [comment] 2023-10-04 09:56
@miv391 please assign me this issue.

**Comment by duarteroso** [comment] 2023-10-06 09:17
I've experiences it all over the 4.2 releases!

**Comment by akien-mga** [comment] 2023-10-06 16:08
Confirmed, seems reproducible both in 4.1.2-stable and 4.2-dev6. 4.2 has even worse issues with trying to do renames from keyboard only, but that's a separate bug.

**Comment by akien-mga** [comment] 2023-10-21 09:33
- Duplicate of https://github.com/godotengine/godot/issues/33126

**Closed by akien-mga** 2023-10-21 09:33 UTC
Labels: bug, topic:editor, confirmed, usability
