### ISSUE TITLE
The "Editor Description" section does not allow you to scroll down.

### ISSUE THREAD

**Issue by Torguen** [godotengine/godot#34622] opened 2019-12-26 19:23 UTC
**Godot version:**
3.2 beta 4 mono

**OS/device including version:**
Win10 64 Home

**Issue description:**
If you place the cursor in the "Editor Description" section you can scroll up but you cannot do it down.

This should not happen if no text is being written in this section and the section text cursor is inactive.

**Steps to reproduce:**
Place the cursor in the "Editor Description" section and leave a margin to scroll down, now try to scroll down from the mouse wheel, you will see that it does not work.

![1](https://user-images.githubusercontent.com/19652075/71487787-847a6d80-281d-11ea-80fd-2eb7c0b96338.png)

**Minimal reproduction project:**

**Comment by Calinou** [comment] 2019-12-26 20:11
This is a bug in the multiline string exports (which creates a TextEdit node). Scrolling events shouldn't be handled by that node if scrolling is enabled but no scrollbar is visible.

**Comment by akien-mga** [comment] 2020-01-03 12:59
Seems fixed in the `master` branch, probably by #34572.

**Comment by Torguen** [comment] 2020-01-29 15:23
Hi, I don't understand the Master Branch issue very well, but this continues to happen in 3.2 stable.

**Comment by hinlopen** [comment] 2020-06-20 19:03
Couldn't reproduce this issue when working on #39717.

**Comment by Torguen** [comment] 2022-02-17 10:15
Fixed in v3.5.beta1.official [b9b23d222]

**Closed** 2022-02-17 10:17 UTC
Labels: bug, topic:editor, usability

**Comment by akien-mga** [comment] 2022-02-17 10:19
Thanks for re-testing all your issues, that's very appreciated :)

**Comment by Torguen** [comment] 2022-02-17 10:21
I have many, I will continue in the next few days.
