### ISSUE TITLE
_ready from instantiated .tscn within EditorPlugin won't be called (neither _init or _enter_tree)

### ISSUE THREAD

**Issue by mateusfccp** [godotengine/godot#24337] opened 2018-12-14 00:06 UTC
**Godot version:**
fa02453

**OS/device including version:**
Arch Linux

**Issue description:**
When adding a Control to bottom panel with `add_to_bottom_panel` within a `EditorPlugin`, the `_ready()` function won't ever be called neither `_init()` or `_enter_tree()`.

**Steps to reproduce:**
1. Create a new plugin.
2. Within the `_enter_tree()` of the main script, instantiate a `.tscn` file.
3. The `_ready()` function won't be called, neither `_init()` or `_enter_tree()`.

**Minimal reproduction project:**
[Plugin Issue.zip](https://github.com/godotengine/godot/files/2678150/Plugin.Issue.zip)

**Comment by volzhs** [comment] 2018-12-14 00:21
you need to add `tool` keyward in `Control.gd`

```gdscript
tool

extends Label

func _ready():
	print("Label Loaded")
```

**Comment by mateusfccp** [comment] 2018-12-14 00:55
@volzhs Still not working, here.

**Comment by mateusfccp** [comment] 2018-12-14 00:57
@volzhs Ok, I swear I tried it before but it didn't work, but now it's working. Please, forgive my dumbness.

**Comment by mateusfccp** [comment] 2018-12-14 01:41
@volzhs, I just noticed what is the problem: the _ready() function will only get called when opening the project. If I desactivate and reactivate the plugin, it won't be called. Is this behaviour expected?

**Comment by akien-mga** [comment] 2018-12-14 08:01
Closing as duplicate of #16974.

**Closed by akien-mga** 2018-12-14 08:01 UTC
