### ISSUE TITLE
GLES3 errors launching Godot 3.0 Beta 1

### ISSUE THREAD

**Issue by brainsick** [godotengine/godot#14861] opened 2017-12-20 09:47 UTC
**Godot version:**
Godot 3.0 Beta 1

**OS/device including version:**
Windows 7 64-bit, ATI Radeon HD 3200

**Issue description:**
ERRORs in console.

**Steps to reproduce:**
Just launching and using the editor.

```
Activated GL 3.3 contextOpenGL ES 3.0 Renderer: ATI Radeon HD 3200 Graphics
ERROR: RasterizerSceneGLES3::initialize: Condition ' status != 0x8CD5 ' is true.
 Continuing..:
   At: drivers\gles3\rasterizer_scene_gles3.cpp:4847
<snip>
ERROR: RasterizerSceneGLES3::initialize: Directional shadow framebuffer status i
nvalid
   At: drivers\gles3\rasterizer_scene_gles3.cpp:4872
GLES3: max ubo light: 409
GLES3: max ubo reflections: 455, ubo size: 144
ARVR: Registered interface: Native mobile
OPENING: C:/Users/Todd/Documents/OSExecuteTest (C:::Users::Todd::Documents::OSEx
ecuteTest)
running cmdline: "C:\Users\Todd\Downloads\Godot_v3.0-beta1_win64.exe\Godot_v3.0-
beta1_win64.exe" "--path" "C:/Users/Todd/Documents/OSExecuteTest" "--editor"
Activated GL 3.3 contextOpenGL ES 3.0 Renderer: ATI Radeon HD 3200 Graphics
ERROR: RasterizerSceneGLES3::initialize: Condition ' status != 0x8CD5 ' is true.
 Continuing..:
   At: drivers\gles3\rasterizer_scene_gles3.cpp:4847
<snip>
ERROR: RasterizerSceneGLES3::initialize: Directional shadow framebuffer status i
nvalid
   At: drivers\gles3\rasterizer_scene_gles3.cpp:4872
GLES3: max ubo light: 409
GLES3: max ubo reflections: 455, ubo size: 144
ARVR: Registered interface: Native mobile
ERROR: EditorData::get_edited_scene_root: Index current_edited_scene=-1 out of s
ize (edited_scene.size()=0)
   At: editor\editor_data.cpp:607
erasing C:\Users\Todd\AppData\Roaming/Godot/projects/OSExecuteTest-3423fbececf48
9515ab07f8653b7a602/filesystem_update3
fragment uses function: zero_if_equal
```

**Comment by Calinou** [comment] 2017-12-20 14:02
The Radeon HD 3000/4000/500 series are too old; their OpenGL version isn't recent enough to run Godot 3.0. Sorry!

Godot 3.1 will re-implement a GLES 2.0 renderer (roughly translating to OpenGL 2.1 on desktops) which will run on very old GPUs.

**Comment by brainsick** [comment] 2017-12-20 14:35
I looked for some kind of GPU/hardware requirement specs for Godot 3.0 but couldn't find anything.

Initially, Godot reported that I wasn't GL 3.3 compatible and wouldn't run.  Then I installed the ATI drivers for the card and now Godot runs but I get the errors.

**Comment by hpvb** [comment] 2017-12-20 20:15
According to https://www.x.org/wiki/RadeonFeature/#index5h2 the HD3000/4000/5000 series GPUs should have GL3.3 on Mesa on Linux at least. So if you just need it to start developing your game on you could try that.

**Comment by brainsick** [comment] 2017-12-20 20:21
@hpvb As far as I can tell, I have GL3.3 on Windows too.  I believe the issue is GLES3, which gpuinfo.org confirms is missing for this GPU?

This isn't worth pursuing on my behalf.  I'm not trying to do development on this box, I just wanted a Windows environment to troubleshoot another reported issue.

**Comment by hpvb** [comment] 2017-12-20 20:26
Godot shouldn't be trying to use GLES on Windows afaik. If you have GL3.3FC contexts it should all 'just work'. But if you don't really have any need to fix this for now I guess we can just leave it open in case someone else comes along with the same card.

**Comment by brainsick** [comment] 2017-12-20 20:28
I'm happy to work with you to troubleshoot further, but it's not necessarily a priority.

**Comment by brainsick** [comment] 2017-12-21 00:24
From what I can tell, glview is to OpenGL what dxdiag is to DirectX.  If it helps, here's the report for this GPU.

[glview.hd3200.txt](https://github.com/godotengine/godot/files/1577448/glview.hd3200.txt)

**Comment by Calinou** [comment] 2017-12-21 17:30
By the way, I've seen reports of Godot 3.0 not running on GeForce 8/9/200 GPUs (which are NVIDIA GPUs from the same era); these GPUs also stop at OpenGL 3.3 support.

**Comment by reduz** [comment] 2017-12-21 17:56
@Calinou it's possible they dont have enough GPU memory to launch the editor, though should run the games

**Comment by akien-mga** [comment] 2018-01-04 20:24
Let's close this one as duplicate of #12596, sounds like the same issue with Radeon HD 3xxx on Windows 7, which advertises OpenGL 3.3 support but apparently not good enough for Godot.

**Closed by akien-mga** 2018-01-04 20:24 UTC
