### ISSUE TITLE
CSGShape doesn't have physics material

### ISSUE THREAD

**Issue by Saitodepaula** [godotengine/godot#36893] opened 2020-03-07 22:27 UTC
**Godot version:**
3.2 Stable

**OS/device including version:**
Windows 10 Home

**Issue description:**
I think it is not a bug exactly, but the way CSGShape is designed. But in the way it is now, it doesn't have a physics material, [although the docs says it will act like a static body](https://docs.godotengine.org/en/stable/classes/class_csgshape.html#class-csgshape-property-use-collision) if `use_collision` is on.

I understand that, as prototype tool, maybe a physics material is not needed. But there is no easy way to create a mesh out of a CSGShape, and reading #19232, it looks like CSGs need more features to be actually useful as prototype tools.

So, all this considered, I think that the fact the engine lets you easily add a collision shape leads the user to think that a physics material is possible.

Also, where is the collision shape added when you click `use_collision` and how can it be accessed? Because a raycast only intercepts the CSGShape (see below, step 5), shouldn't it be intercepting a physics body?

**Steps to reproduce:**

1. Add a `path`, add some points to get a shape
2. Add a `CSG Polygon` as child of paht. Set `mode` to path, and `path node` to the parent path. Set `Use Collision` on
3. Add a `Raycast`, place it in a way it intersects the CSG Polygon
4. Add a script to the raycast, and in the `func _process(delta)` add `print(self.get_collider())` and `print(self.get_collider().get_physics_material_override())`
5. Run. It will print [CSGPolygon:XXXX] and then an error of non existent function for `get_physics_material_override()`

**Minimal reproduction project:**
[CSGStaticBodyTet.zip](https://github.com/godotengine/godot/files/4302576/CSGStaticBodyTet.zip)

**Comment by Zireael07** [comment] 2020-03-08 10:29
I just tried to use a CSG polygon as a tunnel, and in spite of checking use collision, my cars aren't colliding with it, not in 3.2 and not in 3.2.1 rc1. So use_collision seems weird either way.

**Comment by Calinou** [comment] 2020-03-08 13:36
@Zireael07 Can you take a screenshot of the tunnel with **Debug > Visible Collision Shapes** enabled?

**Comment by Zireael07** [comment] 2020-03-08 13:58
Done :)
No collision shape visible.

![Screenshot_20200308_145708](https://user-images.githubusercontent.com/4525388/76164192-3bb03080-614d-11ea-9686-6b46bfd8ed9d.png)
![Screenshot_20200308_145735](https://user-images.githubusercontent.com/4525388/76164193-3d79f400-614d-11ea-863c-9e3a755cf20b.png)

**Comment by Zireael07** [comment] 2020-03-08 14:04
I found a workaround, basically this: https://github.com/godotengine/godot/issues/19232#issuecomment-476459435 and body.create_trimesh_collision() (from code) or Mesh -> Create Trimesh Static Body (in editor) but use_collision seems broken on 3.2 stable onwards.

**Comment by Calinou** [comment] 2020-03-08 14:25
@Zireael07 Can you reproduce this in any 3.2 alphas/betas/RCs? You can download them [here](https://downloads.tuxfamily.org/godotengine/3.2/).

**Comment by Zireael07** [comment] 2020-03-08 14:54
Same problem in beta1 (and all subsequent betas).

Beta 1 :(
![Screenshot_20200308_154755](https://user-images.githubusercontent.com/4525388/76165168-18897f00-6155-11ea-8a4b-af1332f3b31b.png)



Alphas throw a hissy fit about indentation in one of the other files, and as far as I can see the line in question has no spaces but tabs, so IDK what their problem is. 

I copied just the csg scene to a new project, opened it in alpha 1, and well... no collision shapes shown. (Making some sort of a character to check if it clips would take more time than I currently have, sorry)

![Screenshot_20200308_155329](https://user-images.githubusercontent.com/4525388/76165145-f4c63900-6154-11ea-9d65-31cb1151f862.png)

**Comment by Zireael07** [comment] 2020-03-08 14:56
(I realize we've essentially hijacked someone else's bug report, but it looks like they're connected extremely close - alternately, I think you people can move bug reports around? I unfortunately can't...)

**Comment by Saitodepaula** [comment] 2020-03-08 20:13
@Zireael07 hehe, it's fine for me. Like I said, I'm not sure it is a bug I have reported, more a matter of features that are not there by design, but would be extremely useful.

**Comment by madmiraal** [comment] 2021-05-30 10:59
Related to #22246.

**Comment by lexum0** [comment] 2022-03-12 23:26
I made this tool plugin to work in the meantime with Physics Materials using CSG nodes in case anyone is interested 

https://github.com/lexum0/CSGExport-Godot

**Comment by Calinou** [comment] 2023-08-28 15:35
Closing in favor of https://github.com/godotengine/godot-proposals/issues/7568, as feature proposals are now tracked in the Godot proposals repository.

**Closed by Calinou** 2023-08-28 15:35 UTC
Labels: enhancement, topic:core, topic:physics, topic:3d
