### ISSUE TITLE
Is C# support broken on the 32-bit versions?

### ISSUE THREAD

**Issue by piratesephiroth** [godotengine/godot#20012] opened 2018-07-07 05:59 UTC
**Godot version:**
32-bit versions of Godot 3.0.3 and 3.0.4, running in self-contained mode.

**OS/device including version:**
Windows 8.1 Pro x64 (6.3.9600), installed less than a week ago so system integrity should be guaranteed

**Issue description:**
@hpvb
Everything using C# scripts gets compiled without errors but runs for less than a second and crashes. I even tried other examples like the demo projects and bunnymark, always with the same result.

![image](https://i.imgur.com/rtWOFjK.png)

Already tried reinstalling mono v5.12.0 Stable 32-bit and nothing changed. Didn't try older versions because Godot's download page states that only v5.12 will work.
The same projects run absolutely fine on the 64-bit version of Godot.

**Steps to reproduce:**
Run a 32-bit version of Godot 3.0.4 then open a project that uses C# scripts and try to play it.

**Minimal reproduction project:**
Literally anything that uses C# scripts, like [this demo project](https://github.com/exts/godot3-breakout)

**Comment by hpvb** [comment] 2018-07-07 13:38
I'll have a look at this. This worked in my tests on Win 7 pro and Win 10 home. (running 32bit mono binaries on 64bit windows at least) I don't have a Windows 8.1 license. I'll buy one.

**Comment by piratesephiroth** [comment] 2018-07-15 08:03
A friend of mine tested on Win 7 Ultimate x64, with Service Pack 1 and got the exact same error.

**Comment by hpvb** [comment] 2018-08-13 18:12
I have a windows 8.1 license now. I'll treat me test for 3.0.7

**Comment by piratesephiroth** [comment] 2018-10-25 03:06
Yeah, seems to be the same.
But there's more to this. It seems to be a problem on the system that BUILDs the game.

A while after I posted this issue I began having other problems updating visual studio and even windows itself so I reinstalled it (just the "reset" install, without removing anything) and I began exporting normal 32 bit mono projects again.

**Comment by akien-mga** [comment] 2019-03-01 09:15
Duplicate of #17299.

**Closed by akien-mga** 2019-03-01 09:15 UTC
Labels: bug, platform:windows, topic:mono
