### ISSUE TITLE
cyclical reference causes loss of project

### ISSUE THREAD

**Issue by entro-pi** [godotengine/godot#32113] opened 2019-09-13 02:38 UTC
**Godot version:**
v3.2.alpha.custom_build.24e1039eb
**OS/device including version:**
Fedora 30

**Issue description:**
This may seem like a no brainer, but I did it by accident, and once I saved it hangs indefinitely on load even with removing the offending script.

**Steps to reproduce:**
Have these two scripts (I had to rename them from .gd to .txt to upload) attached to two animation sprite objects as they are, then save and try and run the scene. From then on it will freeze when you try to load the scene.

[Archangel attack.txt](https://github.com/godotengine/godot/files/3608144/Archangel.attack.txt)
[ArchangelIdle.txt](https://github.com/godotengine/godot/files/3608145/ArchangelIdle.txt)

**Minimal reproduction project:**
as above.

**Comment by Calinou** [comment] 2019-09-13 12:24
Could you include a complete minimal reproduction project as a ZIP file? This way, we can test the project in the same way you created it.

**Comment by entro-pi** [comment] 2019-09-13 14:28
Sure thing, I'll upload that later today.

**Comment by entro-pi** [comment] 2019-09-14 02:42
[noodles.zip](https://github.com/godotengine/godot/files/3612285/noodles.zip)
Here ya go!

**Comment by entro-pi** [comment] 2019-09-14 05:33
Also, I realise my code is wrong here, I'm more of a golang programmer than anything at this point. However the result totally broke the program, so yeah.

**Comment by Chaosus** [comment] 2019-09-14 07:19
I guess, the issue is about making the editor warn and resolve such problems?

**Comment by entro-pi** [comment] 2019-09-14 18:07
Yeah, or catching the error and not compiling it into a saved state that
cannot be undone without the fix above.

**Comment by akien-mga** [comment] 2019-11-01 15:00
Fixed by #32643.

**Closed by akien-mga** 2019-11-01 15:00 UTC
Labels: bug, topic:core, topic:gdscript
