### ISSUE TITLE
HTML export 

### ISSUE THREAD

**Issue by securas** [godotengine/godot#46732] opened 2021-03-06 14:33 UTC
Possibly related to
https://github.com/godotengine/godot/issues/41400

**Godot version:**
3.2.4 RC3

**OS/device including version:**
Windows 10

**Issue description:**
HTML export 

**Steps to reproduce:**
HTML export does not run in browser using Godot HTTP server or itch.io
Returns this error
![image](https://user-images.githubusercontent.com/2881755/110210280-40303600-7ed4-11eb-8724-0765ba587eea.png)

followed by this
![image](https://user-images.githubusercontent.com/2881755/110210287-4cb48e80-7ed4-11eb-835f-48ddfe9d7881.png)

**Minimal reproduction project:**
[Test_HTML5_export.zip](https://github.com/godotengine/godot/files/6095490/Test_HTML5_export.zip)

**Comment by Calinou** [comment] 2021-03-06 15:43
Duplicate of https://github.com/godotengine/godot/issues/46352 (fixed in the latest `3.2` branch).

**Closed by Calinou** 2021-03-06 15:43 UTC
