### ISSUE TITLE
Create Script dialog can create false entries in .csproj

### ISSUE THREAD

**Issue by KellyThomas** [godotengine/godot#22711] opened 2018-10-04 10:23 UTC
**Godot version:**
bdf898e mono

**OS/device including version:**
Windows 7 x64

**Issue description:**
If an invalid location is entered into the new script dialog then an erroneous entry is placed in the `.csproj` file.  

**Steps to reproduce:**
 1. Right click on the file dock, select new script.
 2. Select Language: "C#", enter Path: "res://new_script?.cs", click "Create"
![image](https://user-images.githubusercontent.com/1151394/46468065-0ab62880-c802-11e8-999d-4e2d7b954b11.png)
3. The file is not created and an appropriate error dialog is displayed:
![image](https://user-images.githubusercontent.com/1151394/46468104-26213380-c802-11e8-819e-bdf1621edcd4.png)
4. However the project's `.csproj` file now contains this entry:

        <Compile Include="new_script%3F.cs" />

**Comment by KoBeWi** [comment] 2020-06-21 15:34
Can anyone still reproduce this bug in Godot 3.2.1 or any later release (e.g. [3.2.2-rc2](https://godotengine.org/article/release-candidate-godot-3-2-2-rc-2))?

**Comment by KoBeWi** [comment] 2020-09-28 00:25
Closing due to no reply. Please comment if you can still reproduce in 3.2.3+.

**Closed by KoBeWi** 2020-09-28 00:25 UTC
Labels: bug, topic:editor
