### ISSUE TITLE
Godot 3.1 joining bones of dae skeleton that shouldn't be joined

### ISSUE THREAD

**Issue by Rossosaurus** [godotengine/godot#27934] opened 2019-04-11 17:29 UTC
**Godot version:**

3.1 Stable Mono Official

**OS/device including version:**

Windows 10 Pro 1803

**Issue description:**

[Here's a link to an imgur album of the issue I'm experiencing](https://imgur.com/a/81ahIwV)
[Here's a link to the reddit post I made on r/godot about the issue before i knew more](https://www.reddit.com/r/godot/comments/bbzsba/godot_stretching_character_after_applying_an/)
I downloaded some animations off of mixamo to learn about animations in godot (I'm a newbie) and I'm having an issue with godot joining bones that shouldn't be joined and aren't joined when I open the files in c4d or maya. It's a bit hard to explain and the imgur album probably does a better job at explaining the problem.

**Steps to reproduce:**

1. [Download the files I was using](https://github.com/godotengine/godot/files/3069805/GodotFiles.zip) 
2. Import them into godot
3. Select T-Pose.dae and set root node to kinematic body
4. Import T-Pose.dae to new inherited scene and add collisionshape
5. Import Idle.dae as new inherited scene
6. Copy animation and paste into T-Pose animation player
7. Select Idle as current animation.

**Minimal reproduction project:**

[GodotAnimationBug.zip](https://github.com/godotengine/godot/files/3069869/GodotAnimationBug.zip)

**Comment by pjlg** [comment] 2019-04-12 13:54
I have also problems, with the new skeleton feature of stable godot release 3.1:
I used instructions from godot documentation [https://docs.godotengine.org/en/3.1/tutorials/animation/2d_skeletons.html#doc-2d-skeletons](url) 

After that, if I move one bone, it is also connected to another polygon, which I haven't connected before. Also deleting and reassign the connections of polygon property skeleton, it is still connected with two polygons.

As I can see, it seems to be, that the Polygon2D-UV-Editor have a refresh problem with the right view of bones with synchronized polygons. Seeming, it select another bones from the list, as I have selected and confirmed with "ok" before.

**Comment by Calinou** [comment] 2020-08-18 14:21
@Rossosaurus @pjlg Can you (or anyone else) still reproduce this bug in [Godot 3.2.2](https://godotengine.org/article/maintenance-release-godot-3-2-2) or any later release?

If yes, please ensure that an up-to-date Minimal Reproduction Project (MRP) is included in this report (a MRP is a zipped Godot project with the minimal elements necessary to reliably trigger the bug). You can upload ZIP files in an issue comment with a drag and drop.

**Comment by fire** [comment] 2021-01-12 00:23
Closed due to no activity.

**Closed by fire** 2021-01-12 00:23 UTC
Labels: bug, topic:import
