### ISSUE TITLE
Godot editor UI elements don't focus correctly when launched from Terminal

### ISSUE THREAD

**Issue by donkeybonks** [godotengine/godot#11992] opened 2017-10-10 11:52 UTC
MacBook Pro running OSX Sierra 10.12.6
godot current master.

**Issue description:**
Godot editor window focus is buggy, doesn't always assume a "foreground" position when launched from the Terminal

**Steps to reproduce:**
1. git clone godot
2. scons build following instructions
3. Focus your web browser i.e. firefox
4. Go back to terminal and run "./bin/godo<tab>..."
5. Top title bar will say "Firefox" and godot will seem to only register double click events on the UI and not single clicks (window border will be grayed out even though it's focused...). You can fix by minimising godot editor, selecting Terminal in the dock, manually left pressing the terminal area and then maximising godot. Then it will say "godot.osx.tools.64" in the top left system menu bar and things work as expected

You have to repeat these steps every time the active window changes i.e. when moving from the project selector to the main editor

This one had me scratching my head. I almost posted a bug that touchpad isn't working ..

**Comment by bruvzg** [comment] 2017-10-10 17:21
#8907 duplicate, use .app bundle, instead of stand-alone executable.

**Comment by akien-mga** [comment] 2017-10-13 11:55
Closing as duplicate of #8907, will add another comment there.

**Closed by akien-mga** 2017-10-13 11:55 UTC
Labels: documentation, platform:osx, topic:editor
