### ISSUE TITLE
Ambient light + metallic material > black material

### ISSUE THREAD

**Issue by SmartySmart702** [godotengine/godot#70600] opened 2022-12-26 19:37 UTC
### Godot version

4.0 Beta 10

### System information

GTX 1070, forward_plus

### Issue description

Ambient light not working for metallic materials.

### Steps to reproduce

Simple scene, add a basic object with metallic material, use default env with background mode custom color.

### Minimal reproduction project

[ambient_light_metallic.zip](https://github.com/godotengine/godot/files/10304618/ambient_light_metallic.zip)

**Comment by Calinou** [comment] 2022-12-26 19:39
This is expected. 100% metallic materials only recieve specular light, so they are unaffected by ambient light.

**Comment by SmartySmart702** [comment] 2022-12-26 19:48
Same for mobile and gl_compatibility.
I never saw this behaviour in other applications like Blender or UE4.

**Comment by clayjohn** [comment] 2022-12-26 20:05
The background custom color should be used for specular reflections if the specular mode is set to background. I think this is what we did in 3.x

**Comment by SmartySmart702** [comment] 2022-12-26 20:10
How can I set a single color ambient light? E.g. for low poly lighting. All those different modes and combinations are kinda confusing ngl :D

**Comment by Calinou** [comment] 2022-12-26 20:36
> How can I set a single color ambient light? E.g. for low poly lighting. All those different modes and combinations are kinda confusing ngl :D

Set ambient mode to Custom Color and set an ambient light color. The specular light color *should* match the ambient light color in this case, but it's currently not being done as clayjohn commented.

**Comment by Calinou** [comment] 2023-01-18 22:03
Duplicate of https://github.com/godotengine/godot/issues/53817 (same cause).

**Closed by Calinou** 2023-01-18 22:03 UTC
Labels: topic:rendering, topic:3d
