### ISSUE TITLE
KinematicBody2D::move_and_collide() detects collision but returns null.

### ISSUE THREAD

**Issue by vigreco** [godotengine/godot#12534] opened 2017-10-31 12:39 UTC
**Operating system:** OS X 10.11.6
**Godot version:** Godot 3 ([91adb58](https://github.com/godotengine/godot/commit/91adb58d3de1cb22196203d0184374ff034bf950))

**Issue description:**
I'm using `move_and_collide()` to move a `KinematicBody2D` and detect collision against a `StaticBody2D`.
I want the collision to happen only at edges so I'm using a `CollisionPolygon2D` with `Build Mode` set to `Segment` for the static body.

The collision works as expected and the kinematic body stops at edges, but `move_and_collide() ` returns **null** if the collision points are parallel.
For example if an edge of the kinematicbody's collision shape is parallel to an edge of the staticbody's collision shape.

I would expect to receive a `KinematicCollision2D` as return value when collision occurs. 

**Steps to reproduce:**
1. Add a StaticBody2D with a CollisionPolygon2D (Build Mode = Segment) to the scene.

2. Add a KinematicBody2D with a Rectangle collision shape to the scene.

3. Use move_and_collide() to move the kinematic body against the static body.

**Link to minimal example project:**
[segment_collision.zip](https://github.com/godotengine/godot/files/1430657/segment_collision.zip)

**Comment by eon-s** [comment] 2017-10-31 21:48
LineShape2D have a similar issue (I wonder if related), an intermitent null-KinematicCollisio2D as collision result.

**Comment by reduz** [comment] 2017-12-06 14:19
it seems segments are broken, i will give it a test

**Comment by akien-mga** [comment] 2018-01-05 15:34
Is this still reproducible in the current master branch?

**Comment by vigreco** [comment] 2018-01-05 23:04
@akien-mga yes, just tested with [b1ab44a](https://github.com/godotengine/godot/commit/b1ab44aa05994a19f0bae5e700c4007b870a8ecf)

![collision.gif](https://user-images.githubusercontent.com/2361758/34632307-f5baf400-f274-11e7-9921-7862f5fa74d8.gif)

**Comment by akien-mga** [comment] 2018-01-16 11:00
Not critical for the upcoming 3.0 release, so moving to the next milestone. A fix can still be cherry-picked for 3.0.x maintenance releases once available in the master branch.

**Comment by ttencate** [comment] 2018-10-13 15:56
Also seeing this with a CircleShape2D which is move_and_collided against a RectangleShape2D. No time to make a proper repro case now, just noting that it might not be related to lines.

It seems to work when entering the rectangle from the right, top and bottom, but not from the left.

**Comment by reduz** [comment] 2018-11-09 00:36
I tried to fix this, the problem is that you are trying to collide with the internal part of the polygon, which will likely not work due to how the physics engine works. I have no idea how to fix this in a way that is not a mess, so kicking to 3.2

**Comment by akien-mga** [comment] 2019-11-26 12:59
Seems fixed in 966c68b.

**Closed by akien-mga** 2019-11-26 12:59 UTC
Labels: bug, topic:physics
