### ISSUE TITLE
godot 4.4.dev2.mono dotnet integration + building is broken

### ISSUE THREAD

**Issue by jasonswearingen** [godotengine/godot#97060] opened 2024-09-15 22:05 UTC
### Tested versions

- reproduced in 4.4.dev2.mono
- not reproduced in 
  - 4.3.stable.mono

### System information

Godot v4.4.dev2.mono - Windows 10.0.22631 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 970 (NVIDIA; 32.0.15.6070) - AMD Ryzen 9 7900 12-Core Processor (24 Threads)

dotnet --version:  `8.0.400`

### Issue description

4.4.dev2.mono seems to have dotnet integration broken.

I see two symptoms, which don't seem super related but you be the judge:

- when clicking on a csharp script from the scene tree, the IDE (VS2022) does not get launched
- when building from VS2022, the project does not get reloaded in the editor
- when building from godot (the hammer icon in upper right), the project does not get reloaded in the editor

No errors are shown in the godot output window.

FYI closing godot and reopening the project loads the changed dotnet assembly, but the reload mechanism doens't seem to work.

going back to 4.3.stable.mono and everything is working properly.

### Steps to reproduce

- create new (blank) project
- create new scene
- attach csharp script
- try to double-click the script icon in the editor Scene Tree:   the IDE will not open up

### Minimal reproduction project (MRP)

I am not uploading a project, as this can be reproduced with a new, blank project.   I would not be surprised if this is somehow platform dependent.   I am on Win11x64 using Visual Studio 2022, but the issue should not be VS2022 related, as godot isn't loading managed project changes regardless of it or VS does the building.

**Comment by lordhaywire** [comment] 2024-09-17 04:20
This is happening to me as well.  My specs are almost identical to OP, except different graphics card and different AMD Ryzen 9. Also all the dates on the projects are broken.

![2024-09-16 21_18_42-Window](https://github.com/user-attachments/assets/80510c0d-77f8-40e3-bc9f-96067e74d183)

**Comment by akien-mga** [comment] 2024-09-17 06:44
This is likely the same issue as #96828, which was fixed after dev2.

The timestamp bug is also caused by the same bug, see the other pinned issue #96812.

**Comment by AThousandShips** [comment] 2024-10-12 16:47
Can someone still replicate this? Or if it isn't the same issue as above

**Comment by AThousandShips** [comment] 2024-10-14 17:00
Please remain constructive, you didn't respond or give any feedback on this, and it's not our fault you couldn't find the issue before writing your own issue, this has been fixed and we can't remove a whole feature because of a big that can be solved

So please be be constructive, this bug was identified and solved

Since this is a duplicate and solved I'll go ahead and close this

**Closed by AThousandShips** 2024-10-14 17:00 UTC
Labels: bug, topic:editor, needs testing, topic:dotnet, regression

**Comment by jasonswearingen** [comment] 2024-10-14 17:04
@AThousandShips 

I don't think you understand my point.   Your QC team needs to do a better job at verifying builds before posting them for public consumption, and in the situation of broken builds being shipped, your team needs to be proactive about wasting people's time.

**This is being constructive.** It's unfortunately negative feedback, but there are clearly some steps that the godot team can take to easily mitigate this in the future.

**Comment by jasonswearingen** [comment] 2024-10-14 17:06
> Also what is the purpose of tagging me? I asked for confirmation, I didn't do anything else

I don't intend to try out the latest dev build to verify a fix.   Sorry if this is venting on you specifically, but I hope you can bring my concern up in your next core team meeting.

**Comment by AThousandShips** [comment] 2024-10-14 17:07
Please be aware that dev builds are explicitly stated to be unstable, you are missing the point of these builds:
> While engine maintainers try their best to ensure that each preview snapshot and release candidate is stable, this is by definition a pre-release piece of software. Be sure to make frequent backups, or use a version control system such as Git, to preserve your projects in case of corruption or data loss.

> With every release we accept that there are going to be various issues, which have already been reported but haven’t been fixed yet. See the GitHub issue tracker for a complete list of known bugs.

I'm sorry you had a bad experience, but this is the reality of dev builds, and we do the due diligence we can do with the testing we can do

Have a good day

**Comment by jasonswearingen** [comment] 2024-10-14 17:10
Not doing basic QC wastes people's time, and not removing broken builds wastes more people's time. 

Think about how many people download and tried out the dev3 mono build.  how many hours of time were wasted on it?  I'm willing to spend the time to file issues, but that was a complete waste of my time.  No QC / proactive removal does not respect the efforts of those willing to invest in your dev builds.
