### ISSUE TITLE
`AnimationTree` weird animation stuttering

### ISSUE THREAD

**Issue by lufog** [godotengine/godot#57274] opened 2022-01-26 21:08 UTC
### Godot version

4.0.alpha1 (31a7ddb)

### System information

Windows 11 21H2, Vulkan Clustered, Geforce 1660 (511.23)

### Issue description

I get weird animation stuttering at beginning of animation, then it disappears.

Godot v4.0.alpha1 (with stuttering):

https://user-images.githubusercontent.com/10379487/151245120-d82e8b90-e39b-48c5-b600-e657bb161ff1.mp4

Version 3.x don't have this problem. 

Godot v3.5.beta1 (without stuttering):

https://user-images.githubusercontent.com/10379487/151245397-de03c423-861f-4787-b5ad-e4aa1d066bbf.mp4

### Steps to reproduce

- open `Animation Test G4` project;
- press play button;
- run from one side to another.

Here the [AnimationTest_G3.zip](https://github.com/godotengine/godot/files/7945556/AnimationTest_G3.zip) for comparison how it should work.

### Minimal reproduction project

[AnimationTest_G4.zip](https://github.com/godotengine/godot/files/7945548/AnimationTest_G4.zip)

**Comment by TokageItLab** [comment] 2022-01-27 03:48
The cause is that some of the time parameters in BlendSpace2D were `float`, and the time parameter `rem` in the process of AnimationBlendTree was `float`. Fixed by #57295.

**Comment by lufog** [comment] 2022-01-27 10:21
@TokageItLab I'm not sure that #57295 fix the stuttering. I tried this [artifact](https://github.com/godotengine/godot/actions/runs/1755385176) with `Animation Test G4` project, and the stuttering remains.

https://user-images.githubusercontent.com/10379487/151338852-4d1dc208-8bcc-4cd0-a675-c04262f611e9.mp4

**Comment by lufog** [comment] 2022-01-27 10:35
@akien-mga, #57295 not fix the problem. I believe this issue should be reopened.

**Comment by TokageItLab** [comment] 2022-01-27 14:40
#57295 has improved the problem to some extent, but it still seems to happen occasionally. In particular, when the ProcessMode of AnimationPlayer is set to Physics, the bug always occurs.

I've confirmed that this bug occurs when p_seek in process_graph is true. I know similar problems are mostly caused by double and float casts, but I don't know the cause of this case for sure yet. I'm investigating.

**Comment by TokageItLab** [comment] 2022-01-28 18:59
@lufog I send a new fix (#57368). It will probably fix this problem. Can you test it?

**Comment by lufog** [comment] 2022-01-28 21:21
@TokageItLab yes, after your fix, the stuttering disappeared.

**Comment by lufog** [comment] 2022-01-28 21:57
Should I close the issue?

**Closed** 2022-01-28 22:00 UTC
Labels: bug, regression, topic:animation
