### ISSUE TITLE
Invalid editor->get_property_editor()->obj in ScriptEditorDebugger

### ISSUE THREAD

**Issue by bennbollay** [godotengine/godot#12911] opened 2017-11-13 22:30 UTC
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Godot 64-bit 2.1.4 49a12ddbc53740ef1a924cf1cbd26ff6e8b21c57
Windows 10 64-bit

**Issue description:**
Read Access Violation:

```
>	ScriptEditorDebugger::_notification(int p_what) Line 1002
					if (inspect_scene_tree->is_visible())
						_scene_tree_request();

>>>					if (inspected_object_id != 0 && editor->get_property_editor()->is_visible() && (editor->get_property_editor()->obj != NULL) && editor->get_property_editor()->obj->is_type("ScriptEditorDebuggerInspectedObject") && ((ObjectID)editor->get_property_editor()->obj->call("get_remote_object_id") != 0)) {
						Array msg;
						msg.push_back("inspect_object");

Exception thrown: read access violation.
EditorNode::get_property_editor(...)->obj-> was 0xFFFFFFFFFFFFFFA7.

+		editor->get_property_editor()	0x000001fba2f4c680 {_type_name={_data=0x000001fba29c1c00 {refcount={count=16 } cname=0x0000000000000000 <NULL> ...} } ...}	PropertyEditor *
-		editor->get_property_editor()->obj	0x000001fba74c7780 {signal_map={hash_table=0xeaeaeaeaeaeaeaea {???} hash_table_power=234 'ê' elements=...} ...}	Object *
+			__vfptr	0xeaeaeaeaeaeaeaea {???, ???, ???, ???, ???, ???, ???, ???, ???, ???, ???, ???, ???, ???, ???, ???, ...}	void * *
+			signal_map	{hash_table=0xeaeaeaeaeaeaeaea {???} hash_table_power=234 'ê' elements=3941264106 }	HashMap<StringName,Object::Signal,StringNameHasher,HashMapComparatorDefault<StringName>,3,8>
+			connections	{_data=0xeaeaeaeaeaeaeaea {first=??? last=??? size_cache=??? } }	List<Object::Connection,DefaultAllocator>
+			_lock_index	{count=-353703190 }	SafeRefCount
			_block_signals	true (234)	bool
			_predelete_ok	-353703190	int
+			change_receptors	{_data={_root=0xeaeaeaeaeaeaeaea {color=??? right=??? left=??? ...} _nil=0xeaeaeaeaeaeaeaea {color=??? ...} ...} }	Set<Object *,Comparator<Object *>,DefaultAllocator>
			_instance_ID	3941264106	unsigned int
			_can_translate	true (234)	bool
			_edited	true (234)	bool
			_edited_version	3941264106	unsigned int
+			script_instance	0xeaeaeaeaeaeaeaea {...}	ScriptInstance *
+			script	{data=0x000001fba74c77e0 "êêêêêêêê... }	RefPtr
+			metadata	{_p=0xeaeaeaeaeaeaeaea {refcount={count=??? } variant_map={hash_table=??? hash_table_power=??? elements=...} ...} }	Dictionary
+			_type_name	{_data=0xeaeaeaeaeaeaeaea {refcount={count=??? } cname=??? name={...} ...} }	StringName
+			_type_ptr	0xeaeaeaeaeaeaeaea {_data=??? }	const StringName *
			_is_queued_for_deletion	true (234)	bool


 	ScriptEditorDebugger::_notificationv(int p_notification, bool p_reversed) Line 57
 	Object::notification(int p_notification, bool p_reversed) Line 865
 	SceneTree::_notify_group_pause(const StringName & p_group, int p_notification) Line 863
 	SceneTree::idle(float p_time) Line 512
 	Main::iteration() Line 1554
 	OS_Windows::run() Line 2226
 	widechar_main(int argc, wchar_t * * argv) Line 149
 	_main() Line 171
 	main(int _argc, char * * _argv) Line 183
 	[External Code]		Annotated Frame
```

**Steps to reproduce:**
Not entirely clear.  Was in a edit-compile-rerun loop when this happened.

**Comment by bennbollay** [comment] 2017-11-13 23:03
Might have had an "unable to write this file" dialog window open at the time...

**Comment by akien-mga** [comment] 2018-01-15 14:20
Is this still reproducible in Godot 3.0 RC1?

**Comment by akien-mga** [comment] 2018-09-11 15:18
`PropertyEditor` was replaced by `EditorInspector` in the master branch, so this bug may have been fixed in the rewrite. Since nobody could confirm it since the OP, closing.

Don't hesitate to comment if you can still reproduce it in the master branch / 3.1 builds.

**Closed by akien-mga** 2018-09-11 15:18 UTC
Labels: bug, topic:editor
