### ISSUE TITLE
In-Editor API documentation display aberration in 3.4 

### ISSUE THREAD

**Issue by snougo** [godotengine/godot#54551] opened 2021-11-03 14:26 UTC
### Godot version

3.4 rc3

### System information

MacOS 11.6.1 Big Sur Intel CPU and Intel GPU

### Issue description

this issue appeared in some beta version, but I can't remember which version is, sorry report it so late

in 3.4 rc3
![Screen Shot 2021-11-03 at 10 09 37 PM](https://user-images.githubusercontent.com/64188282/140077785-84cde87e-5cea-4e28-9695-d09fef16e6c6.png)

in 3.3.4 stable
![Screen Shot 2021-11-03 at 10 11 00 PM](https://user-images.githubusercontent.com/64188282/140077840-8d23b2e6-2056-4c3b-b789-54e94f2e7a22.png)

### Steps to reproduce

just search some help in editor

**Comment by akien-mga** [comment] 2021-11-03 15:39
I can't reproduce the issue on Linux with 3.4 RC 3 and the default theme.

Which theme configuration are you using?

**Comment by snougo** [comment] 2021-11-03 23:20
> I can't reproduce the issue on Linux with 3.4 RC 3 and the default theme.
> 
> Which theme configuration are you using?

I just changed default theme color settings and didn't use any other theme

**Comment by knadoor** [comment] 2021-11-04 00:31
I'll take a look at this on macOS after work.

**Comment by Calinou** [comment] 2021-11-17 14:18
I can't reproduce this on 3.5.beta.custom_build [a79e4d0ae].

### 100% scaling

![image](https://user-images.githubusercontent.com/180032/142217274-8663aa56-3611-4d11-b4c4-68eba090f4bb.png)

### 150% scaling

![image](https://user-images.githubusercontent.com/180032/142217378-a2c5b526-e3da-44dc-9f23-4bacd3b441d8.png)

### 200% scaling

![image](https://user-images.githubusercontent.com/180032/142217434-9e812c8e-e3c6-4e47-9f1b-17b4ab233a8a.png)

**Comment by akien-mga** [comment] 2021-11-17 14:19
CC @bruvzg

**Comment by bruvzg** [comment] 2021-11-17 14:33
It's a regression from #52752, probably some of horizontal offsets were not converted to `float`.

**Comment by Calinou** [comment] 2021-11-17 14:35
I could reproduce the issue in 3.4beta6, but not 3.4beta5. Note that fonts also look significantly blurrier since 3.4beta6:

### 3.4beta5

![2021-11-17_15 23 30](https://user-images.githubusercontent.com/180032/142220492-f60597e1-3aff-4647-bcde-9ec2d44343eb.png)

### 3.4beta6

![2021-11-17_15 23 14](https://user-images.githubusercontent.com/180032/142220490-0446daf3-5658-4528-a242-c05688ace5f5.png)

**Comment by akien-mga** [comment] 2021-11-17 14:59
CC @Listwon

**Comment by akien-mga** [comment] 2021-11-29 14:04
Fixed by #55440.

**Closed by akien-mga** 2021-11-29 14:04 UTC
Labels: bug, topic:editor, confirmed, regression
