### ISSUE TITLE
Godot svg rendering issues

### ISSUE THREAD

**Issue by Raj2032** [godotengine/godot#16880] opened 2018-02-21 10:26 UTC
Godot seems to be having problems rendering SVG files (keep in mind that svg files are vector images, which means that if you were to zoom in on it the image will not become blury).

I made a simple square saved as svg, and Godot is able to render it fine. When I use some of the Godot's symbol saved as a svg format, it turns out blury. How come this is happening?

https://i.stack.imgur.com/OSEl3.png

**Comment by LinuxUserGD** [comment] 2018-02-21 10:30
I think that Godot converts them and during the conversion procesd there is some quality loss depending on the dpi defined in the svg file

**Comment by Raj2032** [comment] 2018-02-21 10:57
But then how come that square that I created, when I zoomed in, there was
no quality loss?

**Comment by Raj2032** [comment] 2018-02-21 11:36
That's a shame, I thought Godot would be a little better than that.

**Comment by Raj2032** [comment] 2018-02-21 12:07
Actually this is a bug. With the square it doesn't get pixelated, but when
I use the Godot symbol and I add a rectangle to it, the entire image
including the rectangle gets pixelated. So there is something going on.

**Comment by LinuxUserGD** [comment] 2018-02-21 13:01
Try to open the svg in Inkscape, mark it and type "s10"
After saving and importing it into Godot it should become less blurry.

**Comment by Raj2032** [comment] 2018-02-21 13:09
Thanks then :)

**Comment by Raj2032** [comment] 2018-02-21 13:09
Wait how do I do that in Inkscape?

**Comment by groud** [comment] 2018-02-21 14:15
Godot does not handles SVG files directly. When you use a SVG file in Godot it is converted into a bitmap picture. So you can try increasing the size of the object in Inskape but you can't have an infinite level of detail.

**Comment by groud** [comment] 2018-02-21 14:18
I'll close this as a duplicate of #16180 or #4826

**Closed by groud** 2018-02-21 14:18 UTC

**Comment by groud** [comment] 2018-02-21 14:26
If someone's willing to contribute for it, maybe. But it's not a priority on the roadmap.

**Comment by Raj2032** [comment] 2018-02-21 23:46
But are there people contributing to it though as I am not sure?

**Comment by groud** [comment] 2018-02-22 09:18
No, not now.
