### ISSUE TITLE
Sprite 3D disregards filter settings.

### ISSUE THREAD

**Issue by nakano15** [godotengine/godot#74629] opened 2023-03-09 00:08 UTC
### Godot version

4.0

### System information

Windows 10, AMD Athlon(tm) II X4 640 Processor   3.01 GHz, 8GB RAM

### Issue description

The Sprite3D object completelly disregards whatever setting in Rendering>Textures>Default Texture Filter is set, and still shows the sprite with Linear Mipmap filter, until you change the flags of the Sprite3D Texture Filter to use another filter.

### Steps to reproduce

1. Go in Godot settings, and change default texture filter to anything other than Linear.
2. Create a Sprite3D object, and place it on the scene with a texture. You will still see it with Linear filter.
3. If you want to check the result in-game, place a camera on the scene, and make it face the sprite.

### Minimal reproduction project

The project bellow shows 2 objects. The one at the center of the camera, doesn't change the flags for filter, while the one to the right does so.
The project setting also should be set to Nearest on the Default Texture Filter.
[Sprite3dShowcase.zip](https://github.com/godotengine/godot/files/10926381/Sprite3dShowcase.zip)

**Comment by Calinou** [comment] 2023-03-09 00:12
Duplicate of https://github.com/godotengine/godot-proposals/issues/5228.

The default texture filter project setting only applies to 2D. In 3D, use the **Flags > Texture Filter** property for Sprite3D and AnimatedSprite3D.

**Closed by Calinou** 2023-03-09 00:12 UTC

**Comment by nakano15** [comment] 2023-03-09 00:21
That's dumb. I can't see the reason why can't.
Even 2D sprites has the same filters as 3D, with the difference being that the Rendering>Textures>Default Texture Filter has 2 less filters than on both settings of the sprites.

Sigh... Whatever..

**Comment by chaoko99** [comment] 2025-02-05 23:09
Okay so like, what if I have thousands of sprite assets? Am I just going to have to set that flag literally every time?

**Comment by Calinou** [comment] 2025-02-06 14:37
> Okay so like, what if I have thousands of sprite assets? Am I just going to have to set that flag literally every time?

Please continue the discussion in https://github.com/godotengine/godot-proposals/issues/5228.
