### ISSUE TITLE
[Godot 4 stable] Attempting to initialize the wrong RID

### ISSUE THREAD

**Issue by git2013vb** [godotengine/godot#74757] opened 2023-03-11 08:36 UTC
### Godot version

v4.0.stable.official [92bee43ad]

### System information

Debian 11

### Issue description

When I open my project
I have there errors in Output tab

```

  Attempting to initialize the wrong RID
  ./core/templates/rid_owner.h:219 - Condition "!mem" is true.
  Attempting to use an uninitialized RID
  drivers/gles3/storage/texture_storage.cpp:1144 - Condition "!texture" is true.
  drivers/gles3/storage/texture_storage.cpp:1048 - Condition "!texture" is true.
  drivers/gles3/storage/texture_storage.cpp:1060 - Condition "!texture" is true.
  drivers/gles3/storage/texture_storage.cpp:1074 - Condition "!texture" is true.
  drivers/gles3/storage/texture_storage.cpp:1093 - Condition "!texture" is true.
  drivers/gles3/storage/texture_storage.cpp:1085 - Condition "!texture" is true.
  drivers/gles3/storage/texture_storage.cpp:1060 - Condition "!texture" is true.
```
The project work as usual so far. No infos about what cause it.

### Steps to reproduce

See before

### Minimal reproduction project

na

**Comment by AThousandShips** [comment] 2023-03-11 09:31
> To speed up our work, please upload a minimal project that isolates and reproduces the issue. This is always the best way for us to fix it. We recommend attaching a ZIP file with the minimal project directly to the bug report, by drag and dropping the file in the GitHub edition field. This ensures the file can remain available for a long period of time. Only use third-party file hosts if your ZIP file isn't accepted by GitHub because it's too large.

> We recommend always attaching a minimal reproduction project, even if the issue may seem simple to reproduce manually.

This seems very specific and without knowing what's going on in your project we can't help

**Comment by git2013vb** [comment] 2023-03-12 06:09
> > To speed up our work, please upload a minimal project that isolates and reproduces the issue. This is always the best way for us to fix it. We recommend attaching a ZIP file with the minimal project directly to the bug report, by drag and dropping the file in the GitHub edition field. This ensures the file can remain available for a long period of time. Only use third-party file hosts if your ZIP file isn't accepted by GitHub because it's too large.
> 
> > We recommend always attaching a minimal reproduction project, even if the issue may seem simple to reproduce manually.
> 
> This seems very specific and without knowing what's going on in your project we can't help

You are right. I know. But some errors came out randomly.  The frustration are in both side I guess. Mine and yours :)

When I can replicate the error I will post a MRP. In other cases I have three choices, 

1) be silent hoping the error go away by itself sometime in the future.
2) Report it here to be tracked and hoping someone else can confirm / reproduce it.
3) Post my entire projects (currently my projects are composed by 5 different sub projects) as MPR

Take days to to try to replicate it is not an option for me sorry. I 'm focused to resolve problems in my game (lack of documentation in first place). And I don't want to bother people unless I'm stuck for days. 

So you tell me what is the best option? I'm open to suggestions :)

**Comment by AThousandShips** [comment] 2023-03-12 07:02
This isn't a forum or help desk, if you don't have any kind of idea of how to reproduce the bug it's not helpful, it's just cluttering the bug reports, in the future you might be better off only posting a bug report for this kind of bug if you can make a MRP directly

**Comment by git2013vb** [comment] 2023-03-12 07:11
So this issue. What is going to happen? I have to close it? Like nothing happen?

**Comment by AThousandShips** [comment] 2023-03-12 07:14
If you can't actually provide any information of how to cause it we can't do anything, this isn't something you are unaware of?

**Comment by git2013vb** [comment] 2023-03-12 07:18
The main reason I posted it is to track this kind of issue. If you say it is not relevant/important I will stop to post when I can't give  a MRP due its random behaviour.

**Comment by AThousandShips** [comment] 2023-03-12 07:20
When did I say it want relevant or important?

But you seem to not understand that if you don't provide *any* information on how to replicate a bug then no one can help you, what do you expect us to do without knowing anything about now this happens?

**Comment by git2013vb** [comment] 2023-03-12 07:29
I don't expect a thing from nobody:) I said I post issue to help the community. 
I give all info I can for that matter. 
I don't ask you to fix it. I just reported it. 
I'm not aware if this is an issue that need to be reported or not.
So tell me I did the right thing to report it or I need to avoid in the future to report similar issues?

**Comment by AThousandShips** [comment] 2023-03-12 07:31
If you can't provide any information on what cause it it's not going to help anyone, and when I say "what do you expect" I don't mean "expect from us", it means "what do you think we could do with it" I'm sorry for any language barrier

**Comment by AThousandShips** [comment] 2023-03-12 07:34
But yes my recommendation is to wait until you actually have anything to report before reporting it, as in, any information at all about when and how it happens

**Comment by git2013vb** [comment] 2023-03-12 07:36
>I'm sorry for any language barrier
No problem at all :)

> But yes my recommendation is to wait until you actually have anything to report before reporting it, as in, any information at all about when and how it happens

Well in this case I do not have more info so far. That not exclude the possibility I may have in the future.. Its happen often.

**Comment by AThousandShips** [comment] 2023-03-12 07:39
Then as I said, wait until you actually have an idea of what causes this, or go to the [community channels](https://godotengine.org/community/) and discuss it, because as much as you think this is helping reporting bugs without any kind of information doesn't help anyone

**Comment by git2013vb** [comment] 2023-03-12 07:42
OK. I will do.

**Comment by AThousandShips** [comment] 2023-03-12 07:51
My suggestion:
1) You have a clear bug with ways to replicate it, then see if there's already a bug report like that, and add information to it if you can, otherwise make a bug report, attaching an MRP most of the time
2) You don't have a clear bug or clear ways to replicate it, then test it some more, or go to the community channels and discuss it

Helps everyone and causes the least frustration for everyone involved including yourself

**Comment by git2013vb** [comment] 2023-03-12 08:00
Ok. I have no idea in which channel I have to discuss the.  Discord will be fine? It what I use the most. Also In which channel?

Beside I think the why is difficult to find the problem is the way Godot catch the errors : `Condition "!texture" is true` It say `why` but not `when` and `who`

**Comment by Calinou** [comment] 2023-03-21 21:48
Closing per the above comments. We need a minimal reproduction project and reproduction steps before this can be tracked on GitHub.

**Closed by Calinou** 2023-03-21 21:48 UTC

**Comment by netAction** [comment] 2023-08-09 16:44
Same issue here after opening a project. Godot 4, Windows 10.
