### ISSUE TITLE
Window not opening after unlock from sleep

### ISSUE THREAD

**Issue by dddnk** [godotengine/godot#87394] opened 2024-01-20 05:54 UTC
### Tested versions

- Reproducible in 4.2 stable, 4.2.1 stable, 4.3-dev2 (All non-C# builds)

### System information

**OS**  Pop!Os 22.04 LTS  **GPU**  RTX 3060M  **CPU**  Intel 12700h

### Issue description

The game play window instantly closes upon attempting to run in the editor after unlocking from sleep / suspend.
Quit to project list does not work either after unlock, as it just closes the editor without opening the project list.
Reloading the project also just closes the editor window without opening anything again.
### Steps to reproduce

In Pop!Os, Open a game in the editor,
put the device in a sleep cycle, try to run the game after unlocking from sleep, trying to quit to project list, or reloading the project.

### Minimal reproduction project (MRP)

[WindowBugTest.zip](https://github.com/godotengine/godot/files/13996844/WindowBugTest.zip)

**Comment by Calinou** [comment] 2024-05-21 23:36
Thanks for the report! Consolidating in https://github.com/godotengine/godot/issues/52738. This is a NVIDIA issue we can't fix on our end without [large sweeping changes](https://github.com/godotengine/godot-proposals/issues/6423). All other applications using Vulkan on Linux run into the same issue unless they can restart their rendering context entirely in a clean manner (preferably without losing any data).

You may try following the advice on this page at your own risk: https://wiki.archlinux.org/title/NVIDIA/Tips_and_tricks#Preserve_video_memory_after_suspend

**Comment by akien-mga** [comment] 2024-11-29 21:08
Duplicate of #52738 which is documented here:
https://docs.godotengine.org/en/stable/tutorials/troubleshooting.html#the-editor-project-freezes-or-displays-glitched-visuals-after-resuming-the-pc-from-suspend

**Closed by akien-mga** 2024-11-29 21:08 UTC
Labels: bug, platform:linuxbsd, topic:editor, topic:porting, confirmed
