### ISSUE TITLE
Line2D Disappears With Batching ON 

### ISSUE THREAD

**Issue by MrZak-dev** [godotengine/godot#38013] opened 2020-04-19 15:56 UTC
**Godot version:**
Godot 3.2.2beta1 mono

**OS/device including version:**
Windows 10

**Issue description:**
I Was using a Line2D as a trail to my character , i downloaded the last version 3.2.2beta1 for testing and i notice the Line2D disappears when GLES Batching is one , i disable it and the Line2D works as it is supposed to .

**Steps to reproduce:**
Line2D attached to a Player And it is adding points as the players moves , when the points are more than 5 points it starts removing index 0 . 
![image](https://user-images.githubusercontent.com/27586088/79692909-8060d880-8270-11ea-92e8-52d286aee8a9.png)

Attached to the player that move only in the y axis .

**EDIT**
one thing i noticed again , when i exported the game to android , the Line2D trail start appearing again but its behavior has changed it was following the Player Position now it is moving by the player side so quickly.

And when running the game on pc i can't even see the Line2D.

**Minimal reproduction project:**

**Comment by lawnjelly** [comment] 2020-04-19 16:44
Is it possible to have a minimum reproduction project in gdscript? I can't yet reproduce this (it may only occur on certain hardware and I'm not sure if I'm using in the same way).

**Comment by MrZak-dev** [comment] 2020-04-19 23:16
[Batching.zip](https://github.com/godotengine/godot/files/4500474/Batching.zip)

Here is an example , you can run it  with and without batching on .
one More Thing i noticed about this , The Line2D disappears only when its fill color set to gradient .

**Comment by MrZak-dev** [comment] 2020-04-20 08:01
set max_join_items to 0 fixes the problem as you said in #38014

**Comment by lawnjelly** [comment] 2020-04-20 08:09
Thanks for the minimum reproduction project, I have tested and can confirm it is caused by the same bug as #38014, and is now fixed and merged! :grin: 

It should be working fine in the next beta. Until then if you run into this problem, setting max_join_items to 0 will work (although you won't get as much performance boost). :+1:

**Comment by MrZak-dev** [comment] 2020-04-20 08:25
Thank you for the good work 👍 , i will wait for the beta2 so we can test .

**Comment by akien-mga** [comment] 2020-04-20 08:49
Fixed by #38019.

**Closed by akien-mga** 2020-04-20 08:49 UTC
Labels: bug, regression, topic:rendering
