### ISSUE TITLE
SSAO and Unshaded material create artifacts

### ISSUE THREAD

**Issue by n-pigeon** [godotengine/godot#10650] opened 2017-08-26 13:53 UTC
Ubuntu, Godot 3 master commit f634973acb711432fe50f8072416f30c8f92122b
nvidia GTX 1070

Test file: [SSAO_bully.tscn.zip](https://github.com/godotengine/godot/files/1253705/SSAO_bully.tscn.zip)

![selection_001](https://user-images.githubusercontent.com/6152134/29741944-a73969b2-8a76-11e7-9e33-f4b5f8a6f8fa.png)

**Comment by novemberist** [comment] 2017-08-26 14:04
I cannot reproduce the white circle (is this what you mean by artifact?). However I have a lot of error spam in the console output.

Arch Linux, same Godot 3 commit, HD4000 with Mesa 17.1.7

![unshaded](https://user-images.githubusercontent.com/7927471/29742050-3d43f322-8a78-11e7-882f-ad1958748961.png)

**Comment by reduz** [comment] 2017-09-05 03:34
oh this is fixed now, closing

**Closed by reduz** 2017-09-05 03:34 UTC
Labels: bug, topic:rendering
