### ISSUE TITLE
Cancelling playtest exporting to Android eventually breaks the whole export process

### ISSUE THREAD

**Issue by Arech** [godotengine/godot#39187] opened 2020-05-31 11:47 UTC
**Godot version:** latest stable 3.2.1

**OS/device including version:** Win7 x64

**Issue description:** Cancelling building debug package for Android (using the top-right android icon in the main editor window) would lead to corruption of "something". Next time one would try to build package and deploy it to a device will result a failure with a message `Could not unzip temporary unaligned APK`.
`editor_data/cache/tmpexport-unaligned.apk.tmp` file remains locked (can't be deleted) and editor freezes when I'm trying to close it. If there were two editors opened (in a self-contained mode with `._sc_` file, run from the same directory), the other editor will also freeze on exit.

**Steps to reproduce:** start exporting a project to android device with a playtest button. Cancel export process somewhere in the middle. Try to export project again to get `Could not unzip temporary unaligned APK` failure. I can't be more specific regarding a correct phase when to press the cancel button, because I can't make the editor work now properly to try to reproduce the issue.

**Comment by KuraiKokoro** [comment] 2020-06-11 17:00
This issue has proven to completely disrupt my workflow.
Any workarounds found?

Reproducible on Windows 10 x64

**Comment by KuraiKokoro** [comment] 2020-06-11 17:07
If you "Export All" you can get around this issue, but you must go to %local%\Godot\temp\ and delete the unaligned.apk.tmp file while Godot is closed.

**Comment by golddotasksquestions** [comment] 2020-09-21 10:12
I also get the `Could not unzip temporary unaligned APK` Load Error, but can't find the unaligned.apk.tmp file in %local%\Godot\temp\. Even if I delete everything in that temp folder while Godot is closed the problem persists.

**Comment by Arech** [comment] 2020-09-21 10:20
> I also get the Could not unzip temporary unaligned APK Load Error, but can't find the unaligned.apk.tmp file in %local%\Godot\temp.

The proper path is referenced somewhere under `Editor data paths` header in the [docs](https://docs.godotengine.org/en/stable/tutorials/io/data_paths.html) (I don't know exactly which one, bc I use only a self-contained mode, where everything lives in `./editor_data/`

**Comment by wamiqurrehman093** [comment] 2020-10-04 09:10
> I also get the `Could not unzip temporary unaligned APK` Load Error, but can't find the unaligned.apk.tmp file in %local%\Godot\temp. Even if I delete everything in that temp folder while Godot is closed the problem persists.

I can't find it either

**Comment by wamiqurrehman093** [comment] 2020-10-06 04:17
I found something weird that initially my textures were 4k import folder size was over 8gb but when I compressed them to 512 then it exported fine and import folder size was super low as well. Is it because of size? or the texture res?

**Comment by Padamass** [comment] 2020-11-10 20:15
I'm new to Godot and I'm facing the same problem. The project was on GLES3 and this error was thrown. I decided to change to GLES2 and was asked to activate the "Import Etc" Project > Project settings > Rendering > Vram compression > Import Etc mode. It helped me! But when I switch back to GLES3, the error crashes again .

**Comment by sahilshahpatel** [comment] 2020-12-30 17:13
First time commenting here, looking to help. I had this same issue when exporting for Oculus Quest (via Android). For me the path was `AppData\Local\Temp\Godot`. My experience was on GLES2, so I'd guess the issue is independent of that.

**Comment by sahilshahpatel** [comment] 2020-12-30 17:53
It seems like while the `.apk` file is being built, it's actually a `.apk.tmp`, and only becomes the `.apk` after the build finishes. `godot\platform\android\export\export.cpp:1769` begins the process by creating the file, but the cleanup macro tries to close the `.apk` version which won't exist if the process was canceled.

I haven't ever compiled Godot from source, so I have yet to confirm that's the issue, but I'm hoping to hear if that even makes sense to someone more experienced! I'll comment again after I've messed around with it to confirm

**Comment by sahilshahpatel** [comment] 2020-12-30 21:38
I'm not very familiar with the details of app data files, but it seems like I need to learn more -- I don't think my initial description is apt. However, I've narrowed the timeline of the issue to during the "Creating APK..." step. Canceling after that step is complete does not cause issues.

With that, and my limited knowledge of the codebase and `.tmp` files in general, I'm wondering if it's best to simply disable the cancel button for this stage, or if we should delete the `.tmp` file on exit.

(calling `FileAccess::exists` on the `.tmp` version of the path seems to always return false, even when I can see it in Window's File Explorer, and `DirAccess::remove_file_or_error` always fails, so I'm not sure how to proceed)

**Comment by Calinou** [comment] 2020-12-30 21:46
> or if we should delete the .tmp file on exit.

If the file isn't reused, it should definitely be removed as soon as it's no longer needed.

**Comment by Calinou** [comment] 2021-01-29 21:21
This may be resolved by the new Android exporting process in 3.2.4 – please test again.

**Closed** 2021-04-15 20:53 UTC
Labels: bug, confirmed, junior job, platform:android, platform:windows, topic:porting
