### ISSUE TITLE
Spatial input fields broken (focus problem)

### ISSUE THREAD

**Issue by matrem** [godotengine/godot#23628] opened 2018-11-10 10:53 UTC
**Godot version:**
3.1 custom build

godot.x11.tools.64.llvm.mono
Master branch on 11b2f90

**OS/device including version:**
Linux mint 19.

**Issue description:**
When an input field in transform section is focused, it's no more possible to edit any input field, and the focus is  lost rapidly.

**Steps to reproduce:**
Open the given project select scene an try to edit its transform.

**Minimal reproduction project:**
[NewGameProject (copy).zip](https://github.com/godotengine/godot/files/2568321/NewGameProject.copy.zip)

**Comment by matrem** [comment] 2018-11-10 11:13
I don't why byt it seems better with the bin/godot.x11.opt.tools.64.llvm.mono binary (the one with mono_glue=true).

**Comment by Anutrix** [comment] 2019-07-17 09:14
I can't reproduce it in the master branch https://github.com/godotengine/godot/commit/96cbbffac76bd6b8c9467153c10c8e87626cccb9 (MSVC build, debug, no mono).
Is this issue still present? @matrem

**Comment by akien-mga** [comment] 2020-01-08 13:42
Two testers couldn't reproduce it, closing.

**Closed by akien-mga** 2020-01-08 13:42 UTC
Labels: bug, topic:editor
