### ISSUE TITLE
SurfaceTool generated meshes don't appear in remote inspector when applied to MeshInstances

### ISSUE THREAD

**Issue by Diogoamorim27** [godotengine/godot#38493] opened 2020-05-05 17:26 UTC
Godot 3.2.1 Stable

Manjaro Linux, Kernel 4.19

After creating meshes procedurally using surface tool at runtime and applying them to a MeshInstance, the remote inspector still lists the mesh as empty

- Create empty project
- Add spatial node as parent
- Add MeshInstance node
- Attach following script to spatial
  
```
extends Spatial

var vertices = PoolVector3Array()

func _ready():
	# SurfaceTool implementation #
	
	vertices.resize(0)
	vertices.push_back(Vector3(-1,-1,0))
	vertices.push_back(Vector3(-1,1,0))
	vertices.push_back(Vector3(1,1,0))
	vertices.push_back(Vector3(1,-1,0))
	
	var triIndices = [
		0,1,2,
		0,2,3,
	]
	
	var st = SurfaceTool.new()
	st.begin(Mesh.PRIMITIVE_TRIANGLES)
	st.add_color(Color.white)
	st.add_uv(Vector2())
	for i in triIndices:
		st.add_vertex(vertices[i])
	
	st.generate_normals()
	
	var new_mesh = st.commit()
	
	$MeshInstance.mesh = new_mesh
	
```

- Add camera to check that the mesh is actually being rendered
- Position it so the mesh is visible

[ProcGeoBug.zip](https://github.com/godotengine/godot/files/4582530/ProcGeoBug.zip)

**Comment by samdze** [comment] 2020-05-05 19:22
Probably happens with other types of resources and properties as well.

**Comment by Calinou** [comment] 2021-03-25 19:56
Duplicate of #28353 (same cause).

**Closed by Calinou** 2021-03-25 19:56 UTC
Labels: bug, topic:editor, topic:gdscript
