### ISSUE TITLE
Visual Script CallInstance should create an Instance when none is set

### ISSUE THREAD

**Issue by henriiquecampos** [godotengine/godot#10178] opened 2017-08-08 20:48 UTC
# Issue
Ok I'm taking a look at the Visual Scripting to make some videos about it. Something I found very problematic is that you can't use an instance to make a simple call without having to instance it before, and there is no way to do.

That's how I would do it in GDScript
```GDScript
extends Node
func _ready():
    var t = Tween.new()
    print(t)
```

Currently, I couldn't find a way to do this using Visual Script.

# Solution (?)
Since the CallInstance node already has everything available to do an instance call, I think it would be good to let it create an instance by default using the `Base Type` and passing this object in the `pass` output. 

E.g. this setup would be the same as the above example

![image](https://user-images.githubusercontent.com/10171059/29093451-465093ba-7c60-11e7-8c9c-8b367fa4b19e.png)

The problem is that currently the `instance` input of this node is always null if another node doesn't pass a object output to it. And there is no way to set a value to it in the Inspector, so...as I said, I can't think of a way to have this working.

# Real Life problems
This totally screw the workflow of a team of a programmer and a designer since the designer can't call a function from a GDScript created by the programmer... neither can we extend a Visual Scripting using class inheritance and making it inherits the GDScript created by the programmer, neither can we just make an instance call using the GDScript as `Base Script` of the CallInstance node. So thi won't work.

![image](https://user-images.githubusercontent.com/10171059/29093749-4fb8e5a0-7c61-11e7-8a2f-9f4166181671.png)

![image](https://user-images.githubusercontent.com/10171059/29093759-5784b368-7c61-11e7-9e83-4b47a64d5e26.png)

**Comment by henriiquecampos** [comment] 2019-01-02 02:16
> 
> 
> Related/dupe of #9067? (sorry for the somewhat late reply..)

Yep, I think it is the same problem, the lack of a constructor

**Comment by akien-mga** [comment] 2019-01-02 09:33
Duplicate of #9067.

**Closed by akien-mga** 2019-01-02 09:33 UTC
Labels: bug, topic:visualscript
