### ISSUE TITLE
c# plugin Collections .NET: Failed to unload assemblies

### ISSUE THREAD

**Issue by dream-young-soul** [godotengine/godot#72435] opened 2023-01-31 06:37 UTC
### Godot version

4.0 beta16

### System information

windows11

### Issue description

c# plugin include assembly collection object throws error
![QQ截图20230131143627](https://user-images.githubusercontent.com/17066147/215684939-34f89323-8fb4-44f7-b6c9-bdb5796181fa.png)

`#if TOOLS
using Godot;
using System;
using System.Collections.Generic;

[Tool]
public partial class test_plugin : EditorPlugin
{
	protected Control _control;
  //this__object
    protected Dictionary<int, object> _dic_object = new Dictionary<int, object>();
    
	public test_plugin()
	{
      

        

    }
    protected override void Dispose(bool disposing)
    {
        
      
        _control = null;
        _dic_object.Clear();
        _dic_object = null;
    }
    public override void _EnterTree()
	{
		// Initialization of the plugin goes here.
	}

	public override void _ExitTree()
	{
	
	}

    public override void _EnablePlugin()
    {
       
            
        _control = new Control()
        {
            CustomMinimumSize = new Vector2(100, 100)
        };

        _control.AddChild(new Label()
        {
            Text = "hello",
            CustomMinimumSize = new Vector2(100, 100)
        });
        GetEditorInterface().GetEditorMainScreen().AddChild(_control);
            
       
		_MakeVisible(false);

         object script = new Class1();
         string json_data = Newtonsoft.Json.JsonConvert.SerializeObject(script);

        _dic_object.Add(1, Newtonsoft.Json.JsonConvert.DeserializeObject(json_data, typeof(Class1))) ;
    }

    public override void _DisablePlugin()
    {
        base._DisablePlugin();
        _dic_object.Clear();
        GD.Print("_DisablePlugin");
	
    }

    public override void _MakeVisible(bool visible)
    {
        if (_control == null) return;
        if (visible)
            _control.Show();
        else _control.Hide();
    }
    public override bool _HasMainScreen()
    {
        return true;
    }

    public override string _GetPluginName()
    {
        return "name";
    }
}
#endif`

### Steps to reproduce

1.enable [test_plugin] plugin
2.disable [test_plugin] plugin
3.changed [new_script.cs]  code, rebuild project.

### Minimal reproduction project

[test_demo.zip](https://github.com/godotengine/godot/files/10543472/test_demo.zip)

**Comment by raulsntos** [comment] 2023-02-22 16:13
Duplicate of https://github.com/godotengine/godot/issues/70026

**Closed by raulsntos** 2023-02-22 16:13 UTC
Labels: bug, topic:dotnet
