### ISSUE TITLE
4.0b3 "PointLight2D blend_mode Mix" doesn't work for "CanvasItemMaterial LightOnly blend_mode Mix"

### ISSUE THREAD

**Issue by magian1127** [godotengine/godot#67803] opened 2022-10-23 14:42 UTC
### Godot version

4.0b3

### System information

windows 11

### Issue description

3.x is valid.
PointLight2D in 4.0 has no effect.

3.x有效的.
4.0的PointLight2D没有效果.

### Steps to reproduce

1. Add CanvasItemMaterial to any node
2. Set CanvasItemMaterial to LightOnly and blend_mode_Mix.
3. Add a PointLight2D.
4. Set the blend_mode of the PointLight2D to Mix as well.

　

1. 给任意节点添加CanvasItemMaterial
2. CanvasItemMaterial设置为LightOnly和blend_mode_Mix.
3. 添加一个PointLight2D
4. PointLight2D的blend_mode也设为Mix.

**Comment by Calinou** [comment] 2022-10-23 17:15
Duplicate of https://github.com/godotengine/godot/issues/49909.

**Closed by Calinou** 2022-10-23 17:15 UTC
