### ISSUE TITLE
EditorProgress dialog is not showing properly (4.3.dev2 regression)

### ISSUE THREAD

**Issue by AdilDevStuff** [godotengine/godot#88128] opened 2024-02-09 08:05 UTC
### Tested versions

Godot 4.3 Dev 3

### System information

Godot v4.3.dev3 - TUXEDO OS 2 22.04.3 - Wayland - Vulkan (Forward+) - integrated AMD Radeon R7 Graphics (RADV KAVERI) () - AMD A8-7600 Radeon R7, 10 Compute Cores 4C+6G (4 Threads)

### Issue description

The loading progress bar that shows up when saving scenes is not properly shown. (see screenshot)
![image](https://github.com/godotengine/godot/assets/94475453/a2572ebf-3e8b-44df-8f09-4315620412f0)

### Steps to reproduce

Save or Launch Scene By Ctrl + S

### Minimal reproduction project (MRP)

N/A

**Comment by Calinou** [comment] 2024-02-09 10:38
Can you reproduce this in 4.3.dev2 and 4.2.1?

**Comment by AdilDevStuff** [comment] 2024-02-09 10:45
Its also happening in 4.3 dev2. Working fine in 4.2.1. And no, **Prefer Wayland** setting is disabled.

**Comment by AdilDevStuff** [comment] 2024-02-09 10:49
It works fine when it appears for the first time then if i save again, it breaks again.

**Comment by arkology** [comment] 2024-02-09 11:38
I see the same on Windows 10 (& 4.3 dev2), so this is not Linux-specific

**Comment by Calinou** [comment] 2024-02-18 00:44
I bisected the regression to 62ab9bf1c4a464009b16fc6fd398a712eb3f9509. cc @YeldhamDev

**Comment by YeldhamDev** [comment] 2024-02-18 04:57
The dialog has the right size on its first appearance, but it breaks afterwards, odd...

**Comment by KoBeWi** [comment] 2024-02-18 16:30
Duplicate of #86767

**Closed** 2024-02-20 10:56 UTC
Labels: bug, topic:editor, topic:porting, confirmed, regression
