### ISSUE TITLE
Labels aren't displaying text?

### ISSUE THREAD

**Issue by mirrorcat36** [godotengine/godot#15966] opened 2018-01-22 06:18 UTC
I couldn't find this issue through the search bar, but I wonder if anyone else has this issue...

I'm operating on windows 7, and while attempting the beginning tutorial,
I can't get the text on any labels I create to show up.
I've triple checked that I was doing exactly what the tutorial asked, but the label is just a grey empty box, no matter what I put into the text property.

I just downloaded godot 2.1.4 brand new, and it's already got this problem. I've searched google, and it has led me to check if my driver was up to date (and I've concluded it IS up to date) so I'm not sure what else I can check...

**Comment by timoschwarzer** [comment] 2018-01-22 07:03
We need more information:
- Graphics card
- Graphics driver version

**Comment by volzhs** [comment] 2018-01-22 18:24
and sample project to reproduce

**Comment by akien-mga** [comment] 2018-01-25 21:40
Sounds like a drivers problem indeed, like #625.

**Comment by KoBeWi** [comment] 2020-11-13 11:35
Closing due to lack of update. Please comment if you can still reproduce this issue in the latest stable version of Godot.

**Closed by KoBeWi** 2020-11-13 11:35 UTC
Labels: bug, platform:windows, topic:gui

**Comment by CounterFace** [comment] 2026-07-04 14:45
I have the same problem following the beginners tutorial. Create a label, run the scene and the game box opens all grey. No label is shown.
My system:
Godot 4.7
iMac M1 running MacOS 26.5.2

[godot-playground.zip](https://github.com/user-attachments/files/29661137/godot-playground.zip)

**Comment by CounterFace** [comment] 2026-07-04 15:03
Figured it out.
The retina display has a very high resolution. If you simply follow the instructions one cannot see the blue rectangle that indicates the viewport. The label is not displayed because it was placed outside of the blue rectangle.

Solution:
The blue rectangle is very faint and hardly noticeable. Use the editor zoom function to zoom in and out until you can see the origin. Move your label until it sits less than 1000 px away from the origin and inside the rectangle.
