### ISSUE TITLE
Root motion incorrectly retrieved from some imported .glb models.

### ISSUE THREAD

**Issue by jcarlosrc** [godotengine/godot#64291] opened 2022-08-11 19:20 UTC
### Godot version

Godot 4 alpha 14

### System information

Windows 10

### Issue description

Godot 4 is not getting root motion correctly from some imported models. In the video, Godot 3.5 (first) retrieves  root motion correctly while Godot 4 Alpha 14 (second) does not. Alpha 13 shows the same problem.

https://user-images.githubusercontent.com/8985409/184221366-e2a0c2e8-21c4-4206-ad74-529bba6238dc.mp4

### Steps to reproduce

Open the minimal project.

### Minimal reproduction project

[bug_report_root_motion_g4_alpha14.zip](https://github.com/godotengine/godot/files/9311443/bug_report_root_motion_g4_alpha14.zip)

**Comment by TokageItLab** [comment] 2022-08-11 20:13
It is optimizer's issue (duplicate of #58968), it will be fixed in #64132.

**Closed by TokageItLab** 2022-08-11 20:13 UTC
Labels: bug, topic:import, regression, topic:animation, topic:3d
