### ISSUE TITLE
My script execution time become 6x slower on exported 32bit

### ISSUE THREAD

**Issue by AureaFUNSoft** [godotengine/godot#41896] opened 2020-09-09 05:12 UTC
**Godot version:**
3.2.2.stable official 64bit (from godot website)

**OS/device including version:**
Windows 10 64bit

**Issue description:**
Execution time of my script on editor is 0.3s
Then when I export it to 32bit windows executable, i run it, the execution time become 1.8s.
The script is a port of fast gaussian blur c# script that I found online, I ported it to GDScript just for fun.
The project is uploaded below.

**Steps to reproduce:**
To Execute the script just Run the project and click on the image.
Run on 64bit editor on 64bit Windows machine, see the execution time
Now export to 32bit, run, and see the different.

**Minimal reproduction project:**
[FastBlur.zip](https://github.com/godotengine/godot/files/5192714/FastBlur.zip)

**Comment by Calinou** [comment] 2020-09-09 11:56
Duplicate of https://github.com/godotengine/godot/issues/30606.

**Closed by Calinou** 2020-09-09 11:56 UTC
