### ISSUE TITLE
Using Basis.rotated with a normalized axis will have 'The axis Vector3 must be normalized' error

### ISSUE THREAD

**Issue by nagasawamaki** [godotengine/godot#49858] opened 2021-06-23 13:44 UTC
### Godot version

3.3.2.stable

### System information

Windows 10

### Issue description

I am using `Basis.rotated()` and it will show error `The axis Vector3 must be normalized` even my axis vector already called `normalized()` before passing to `Basis.rotated()`

### Steps to reproduce

It occurs randomly so I don't have steps to reproduce

**Comment by kleonc** [comment] 2021-06-23 14:52
> ### Issue description
> 
> I am using `Basis.rotated()` and it will show error `The axis Vector3 must be normalized` even my axis vector already called `normalized()` before passing to `Basis.rotated()`
> ### Steps to reproduce
> 
> It occurs randomly so I don't have steps to reproduce
> ### Minimal reproduction project
> 
> _No response_

Please at least show the code resulting in that error, even if "it occurs randomly" (but better upload a minimal reproduction project). Otherwise it's just a guessing game.

**Comment by rubixkyoob** [comment] 2021-09-05 19:02
I am also seeing this error.
```
ERROR: The axis Vector3 must be normalized.
   At: core/math/basis.cpp:980
```
My project was originally created in v3.2.2, where I did not see this error.  It was only after I opened my project in v3.3.2 that the issue started occurring.  Here's my code:
```
func rotate_vector_to_floor_normal(vector):
	if not is_on_floor():
		return vector

	var angle_to = Vector3.UP.angle_to(get_floor_normal())
	var axis = Vector3.UP.cross(get_floor_normal()).normalized()
	return vector.rotated(axis, angle_to) <<--- ERROR
```

Not sure if it's happening "randomly" for me, but it happens quite often because I run this function in `_physics_process`.  
Perhaps there's some kind of floating point error?

**Comment by kleonc** [comment] 2021-09-05 21:09
@rubixkyoob If `get_floor_normal()` is collinear with `Vector3.UP` then:
- angle between them is either 0 or 180 degrees,
- result of their `cross` product is a zero vector.

Calling `normalized()` on a zero vector won't change it anyhow (zero vector can't be normalized, this info needs to be added to [the docs of `normalized()`](https://docs.godotengine.org/en/3.4/classes/class_vector3.html#class-vector3-method-normalized)). Passing a zero vector as `axis` parameter to `rotated()` will indeed produce an error.

So you need to handle the cases when your vectors are collinear:
- when angle is zero there's no need to rotate,
- when angle is 180 degrees you can rotate around any arbitrary choosen axis perpendicular to these vectors (there are infinitely many such axes, for example: `Vector3.RIGHT`, `Vector3.LEFT`, `Vector3.FORWARD`, `Vector3.BACK`).

So try something like this:
```
func rotate_vector_to_floor_normal(vector):
	if not is_on_floor():
		return vector

	var angle_to = Vector3.UP.angle_to(get_floor_normal())
	var axis = Vector3.UP.cross(get_floor_normal()).normalized()
	if not axis:
		if is_zero_approx(angle_to):
			return vector
		axis = Vector3.RIGHT
	return vector.rotated(axis, angle_to)
```

**Comment by rubixkyoob** [comment] 2021-09-05 21:27
@kleonc Your explanation makes sense, and that modification does, indeed, fix my issue.  Thank you very much for your help!

**Comment by akien-mga** [comment] 2021-09-17 12:23
Closing then as it seems caused by issues in the user scripts, not the engine.

**Closed by akien-mga** 2021-09-17 12:23 UTC
Labels: topic:core, needs testing
