### ISSUE TITLE
[3.x] Duplicated Button focus_mode always set to FOCUS_ALL

### ISSUE THREAD

**Issue by baldie-degenerate** [godotengine/godot#72968] opened 2023-02-09 13:13 UTC
### Godot version

3.5.2 rc2

### System information

Arch Linux

### Issue description

focus_mode value does not carry over to a duplicated button.

### Steps to reproduce

1. Set a button's `focus_mode` to `FOCUS_NONE`
2. Duplicate button 
3. Duplicated button's `focus_mode` is `FOCUS_ALL`

Also happens in editor.

### Minimal reproduction project

[Duplicated_button_FOCUS_ALL.zip](https://github.com/godotengine/godot/files/9995572/Duplicated_button_FOCUS_ALL.zip)

**Comment by Calinou** [comment] 2023-02-09 14:26
Duplicate of https://github.com/godotengine/godot/issues/57009.

**Closed by Calinou** 2023-02-09 14:26 UTC
Labels: bug, topic:editor
