### ISSUE TITLE
Click AltasTexture in theme Inspector will not unfold it

### ISSUE THREAD

**Issue by univeous** [godotengine/godot#45385] opened 2021-01-23 09:12 UTC
**Godot version:** 3.2.3 stable

**OS/device including version:** Windows 10 20H2

**Issue description:** If using AltasTexture in StyleboxTexture in theme, click the AltasTexture in the inspector will not unfold it. Check the Minimal reproduction project.

click AtlasTexture:
![image](https://user-images.githubusercontent.com/40604180/105574101-3e376b00-5d9d-11eb-9d24-6dcf8361842f.png)
then StyleboxTexture will fold and can't change AltasTexture's property:
![image](https://user-images.githubusercontent.com/40604180/105574109-4becf080-5d9d-11eb-8722-2d2b201738b0.png)

**Steps to reproduce:** Open new_theme.tres, and click AltasTexture in StyleboxTexture in the inspector. The StyleBoxTexture will fold.

**Minimal reproduction project:**

[AtlasTexture.zip](https://github.com/godotengine/godot/files/5859965/AtlasTexture.zip)

**Comment by KoBeWi** [comment] 2021-01-23 19:01
Duplicate of #28341 (same underlying issue)

As a workaround, you can right-click the stylebox and select Edit.

**Closed by KoBeWi** 2021-01-23 19:01 UTC
Labels: bug, topic:editor
