### ISSUE TITLE
Stretch aspect keep & keep_width rendering issue on Android

### ISSUE THREAD

**Issue by UgisBrekis** [godotengine/godot#17060] opened 2018-02-26 20:53 UTC
**Godot version:**

3.0 stable official

**OS/device including version:**

Google Nexus 4, Android 5.1.1

**Issue description:**

Please see screenshots attached from Nexus 4.
I noticed rendering issues while testing project on Google Nexus 4 when screen stretching aspect is set either to keep or keep_width(it doesn't matter whether the mode is 2d or viewport). When screen stretching aspect is set to expand, keep_height or ignore, everything seems to be working(at least rendering looks normal).

![screenshot_1970-04-09-22-03-45](https://user-images.githubusercontent.com/9309589/36694006-d8e95f5e-1b34-11e8-8f95-972312b59409.png)

**Steps to reproduce:**
Set screen stretching aspect to either "keep" or "keep_width"

**Minimal reproduction project:**

**Comment by SkaceKamen** [comment] 2018-03-20 11:17
Can confirm

**Godot version:**

3.0.2 stable official

**OS/device including version:**

Oneplus X (E1003), Android 5.1.1

**Screenshot 1:** viewport/keep

![screenshot_2018-03-20-12-11-46](https://user-images.githubusercontent.com/2076742/37651449-7536e980-2c38-11e8-842a-1355f7fec0c8.png)

**Screenshot 2:** viewport/expand

![screenshot_2018-03-20-12-12-25](https://user-images.githubusercontent.com/2076742/37651465-7eaddcda-2c38-11e8-8dc2-c815852d3632.png)

**Comment by nightblade9** [comment] 2018-09-06 23:40
Is there a work-around for this, such as setting the aspect ratio option to something else?

**Comment by ravisharma1987** [comment] 2019-03-02 19:13
I am having the same issue on my OnePlus One but the exported apk works fine on Nexus 7 (2013).
Don't know what is the difference between these two devices other than the obvious difference of OS.

This is how it looks..
![image](https://user-images.githubusercontent.com/1917561/53686442-4d374f00-3d27-11e9-9b71-7e64448ee82d.png)


Project having problem
[Test1.zip](https://github.com/godotengine/godot/files/2922427/Test1.zip)

Edit -
Godot Version
![image](https://user-images.githubusercontent.com/1917561/53686449-6809c380-3d27-11e9-9bae-feac2c03e171.png)


Export Template
![image](https://user-images.githubusercontent.com/1917561/53686451-6c35e100-3d27-11e9-906c-64acf9de5a37.png)


Nexus 7 (2013) Android Version 6.0.1
OnePlus One Android Version Cyanogen Android Version 6.0.1

I found out more details now as follows -

The issue happens even when I don't have any node in my scene.

On Nexus 7 (2013), issue happens when the stretch settings are as follows:
![image](https://user-images.githubusercontent.com/1917561/53686449-6809c380-3d27-11e9-9bae-feac2c03e171.png)


On OnePlus One the issue happens when the stretch settings are as follows:
![image](https://user-images.githubusercontent.com/1917561/53686451-6c35e100-3d27-11e9-906c-64acf9de5a37.png)


Please help..

**Comment by nightblade9** [comment] 2019-03-03 17:25
@ravisharma1987 are you able to easily test against Godot 3.1 to see if this is fixed there?

**Comment by ravisharma1987** [comment] 2019-03-03 17:48
Hello, 
I tested with 3.1 Beta 9, and I can see the problem still existing. I tried also on Linux build and Windows build and the problem is existing still. 

Please let me know if you need any more details about my environment. 
Thanks.

**Comment by volzhs** [comment] 2019-03-03 18:10
![screenshot_20190304_030930](https://user-images.githubusercontent.com/8281454/53699373-f3b84880-3e2a-11e9-9a0c-34de96f09e90.png)

tested with c00429c33 on Kubuntu 19.04 / gtx 1070ti

**Comment by ravisharma1987** [comment] 2019-03-03 18:46
@volzhs Sorry for not being clear. My screenshot is on the device Nexus 7 (2013) but in the editor everything looks perfectly fine.

**Comment by volzhs** [comment] 2019-03-03 18:54
oh i misunderstood by the linux and windows part that you mentioned. sorry.

**Comment by akien-mga** [comment] 2019-12-13 23:48
Is this still reproducible in the latest 3.2 builds?

**Comment by akien-mga** [comment] 2020-01-05 10:16
No answer, so closing. Please comment if you can still reproduce the issue.

**Closed by akien-mga** 2020-01-05 10:16 UTC
Labels: bug, confirmed, platform:android, topic:rendering
