### ISSUE TITLE
Node and Inspector tab goes missing(Godot 3.0 Stable)

### ISSUE THREAD

**Issue by AFWSI** [godotengine/godot#16242] opened 2018-01-31 16:10 UTC
I tried Godot version 2 and didn't like it very much , since version 3 got release I thought I'd give it another go. There seems to be an issue with the Node and Inspector tab going missing. I tried different layouts and it seems to happen on the first column to the right of viewport. One thing I did notice, if you close the project and reopen it, it would be visible again.

Here both are visible.
![godot_tab_issues](https://user-images.githubusercontent.com/24877571/35633361-a462b2f6-066e-11e8-8ef0-a846d232288e.jpg)

These next few pics Inspector disappears ,but also happens with node.
![godot_tab_issues1](https://user-images.githubusercontent.com/24877571/35633379-b1886548-066e-11e8-8edf-236ab51748ab.jpg)

![godot_tab_issues2](https://user-images.githubusercontent.com/24877571/35633407-c01a5616-066e-11e8-83a2-6dda29b0c8cf.jpg)

![godot_tab_issues3](https://user-images.githubusercontent.com/24877571/35633433-d0f6a610-066e-11e8-9684-ba26952f2860.jpg)

Here is a error if it helps any.
![godot_tab_error](https://user-images.githubusercontent.com/24877571/35633458-e55a96e8-066e-11e8-92e9-e48db46ad77c.jpg)

**Comment by vnen** [comment] 2018-01-31 16:23
Thanks for the report, but this is a duplicate of #15992.

**Closed by vnen** 2018-01-31 16:23 UTC
