### ISSUE TITLE
Error with text and animationPlayer

### ISSUE THREAD

**Issue by Torguen** [godotengine/godot#50036] opened 2021-06-30 19:53 UTC
### Godot version

3.3.2 stable official

### System information

w10 64

### Issue description

The animation player does not execute the animation correctly, I don't know how to explain it, there is a desynchronization or something like that.
The text appears visible at some point where it shouldn't.
Previously I could see that that moment occurs near the end of the 1,499X animation but now I can't play it back for the video.

In the video you can see that during the execution of the program the text "WELL DONE" appears and disappears and at some point it is erroneously displayed, this does not coincide with the animation player configuration.

https://user-images.githubusercontent.com/19652075/124022702-72b6ef00-d9ed-11eb-95eb-4acbe9d8f0a3.mp4

### Steps to reproduce

run the project

### Minimal reproduction project

[testAnimation.zip](https://github.com/godotengine/godot/files/6743636/testAnimation.zip)

**Comment by Torguen** [comment] 2021-06-30 19:57
This is what I meant, observe how I can reproduce the moment in which the desynchronization occurs

https://user-images.githubusercontent.com/19652075/124023368-23bd8980-d9ee-11eb-99fd-66bccfd12531.mp4

**Comment by Torguen** [comment] 2021-06-30 20:56
It seems something related to "visible / invisible" of the controls.

**Comment by kleonc** [comment] 2021-07-01 09:47
The cause is you're animating rect properties (`rect_scale`) of a `Control` (`VBoxContainer`) which is a child of a `Container` (`MarginContainer`). `Container` can reposition, scale, etc. its child `Control`s however it wants and that's what your `MarginContainer` does when it's trigerred to sort its children (changing visibility of a child triggers sorting in the parent `Container`).
You can't really assume that changes to positional properties of a `Control` being a child of a `Container` will persist. The problem is that you can change these properties at all. It's being partially addressed by godotengine/godot-proposals/issues/2841 (this proposal still won't prevent changing such properties from the script).

**Comment by Calinou** [comment] 2021-07-01 10:16
Closing per @kleonc's comment.

**Closed by Calinou** 2021-07-01 10:16 UTC
Labels: bug, needs testing, topic:animation

**Comment by Torguen** [comment] 2021-07-01 10:32
Thanks for the information guys and I was able to do it correctly.
Godot is I N C R E D I B L E
