### ISSUE TITLE
Nightly Build - Opening error

### ISSUE THREAD

**Issue by nonunknown** [godotengine/godot#39180] opened 2020-05-30 22:49 UTC
**Godot version:**
Godot Engine v4.0.dev.calinou.4d50f747d

**OS/device including version:**
Ubuntu 20.04
Intel Graphics

**Issue description:**
Tried to opening nightly build but got an error

**Steps to reproduce:**
Download nightly build from here: https://hugo.pro/projects/godot-builds/
When downloaded right-click and in permissions tab click: allow execute as program
Open terminal and type: ./godot-linux-nightly-x86_64.AppImage 

ERROR: Cant find layer: VK_LAYER_KHRONOS_validation
   at: _check_layers (drivers/vulkan/vulkan_context.cpp:158)
ERROR: Cant find layer: VK_LAYER_LUNARG_standard_validation
   at: _check_layers (drivers/vulkan/vulkan_context.cpp:158)
ERROR: Cant find layer: VK_LAYER_GOOGLE_threading
   at: _check_layers (drivers/vulkan/vulkan_context.cpp:158)
ERROR: Condition "err" is true. returned: ERR_CANT_CREATE
   at: _create_physical_device (drivers/vulkan/vulkan_context.cpp:353)
handle_crash: Program crashed with signal 11
Dumping the backtrace.

[1] /lib/x86_64-linux-gnu/libc.so.6(+0x46210) [0x7f7a6ec3c210] (??:0)
[2] ./godot-linux-nightly-x86_64.AppImage() [0x1338cf0] (??:?)
[3] ./godot-linux-nightly-x86_64.AppImage() [0x133687c] (??:?)
[4] ./godot-linux-nightly-x86_64.AppImage() [0x7b9e51] (??:?)
[5] ./godot-linux-nightly-x86_64.AppImage() [0x7b9fd8] (??:?)
[6] ./godot-linux-nightly-x86_64.AppImage() [0x7c2f7b] (??:?)
[7] ./godot-linux-nightly-x86_64.AppImage() [0x7c7c79] (??:?)
[8] ./godot-linux-nightly-x86_64.AppImage(main+0x7d) [0x7a0d7d] (??:?)
[9] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf3) [0x7f7a6ec1d0b3] (??:0)
[10] ./godot-linux-nightly-x86_64.AppImage() [0x7a3cb9] (??:?)
-- END OF BACKTRACE --
Aborted (core dumped)

**Minimal reproduction project:**
N/A

**Comment by Calinou** [comment] 2020-05-30 22:50
The AppImage I provide is currently quite old, because the AppImage .desktop file linter doesn't like a [newly added property](https://github.com/godotengine/godot/pull/38519).

I'll replace AppImage builds with non-AppImage builds in the future to solve this. Either way, this is probably not a bug within the engine, so I'll close this. (Also, double-check that you have Vulkan development libraries installed and that your GPU is recent enough to support Vulkan.)

**Closed by Calinou** 2020-05-30 22:50 UTC
