### ISSUE TITLE
Unsaved script changes are lost after window focus loss on Windows

### ISSUE THREAD

**Issue by ret80** [godotengine/godot#3764] opened 2016-02-18 20:40 UTC
[en]
Often there is a situation when, after revisions in the script, the script file is not overwritten. The disc appears next to the script file highlighted with the extension TMP. It contains all the latest changes. Fail And the script does not change. In this situation, when you run the project performed original Fail without new changes.

[ru]
Часто возникает ситуация когда после правок в скрипте, файл скрипта не перезаписывается. На диске рядом с скриптом появляется фаил с расширением tmp. Он содержит все последний правки. А сам фаил скрипта не меняется. В такой ситуации при запуске проекта выполняется оригинальный фаил без новых изменений.

commit: b28fc0a3d826165cbc4f49ffdb1419a477d7cdb0
os: win 10 64

**Comment by ealataur** [comment] 2016-02-19 12:07
[en]And I have this problem too.. But I catch this bug.
If I open script and change it but not open the scene included this script then after save my changes is not applied

[ru]
Если вдруг дебагер остановит скрипт и откроет его на редактирование, а сцена содержащая скрипт в этот момент не открыта, то после попытки сохранения правок они не сохраняются в файле и продолжает работать старая версия скрипта..

**Comment by reduz** [comment] 2016-02-23 16:08
can you describe in more detail how to reproduce this?

**Comment by ret80** [comment] 2016-02-23 16:20
Tomorrow will try to learn how to play it

**Comment by ealataur** [comment] 2016-02-23 16:31
1. Create two scenes
2. make the script in one of scenes and make error in script
3. close nab with scenes included script with error
4. run project
5. debugger will open script with error
6. correct error and save script
7. script not saved and error is present in scene

It is scenario for me when I catch this bug

**Comment by ret80** [comment] 2016-02-24 14:26
Here that found (2.0):
1 Open any script
2 Make changes
3 Not save the changes.
4 Minimize window editor.
5 Maximize window the editor.
6 Our change anymore.

**Comment by akien-mga** [comment] 2016-02-26 19:56
Description of this same bug from #3840:

> I'm running into a major bug with scripts on 64-bit Windows in the Steam version of Godot.
>
> If you make a change in a script and change focus to another window without saving the script, upon regaining focus the editor seems to reload the script from disc and you lose any changes you've made.
> 
> I have my scenes saves in .scn format and my scripts are external .gd files.

**Comment by ret80** [comment] 2016-02-29 11:49
Strange! Now it is impossible to reproduce.
Close yet I will not.

**Comment by Scipi** [comment] 2016-03-08 02:30
I had the same thing as @ret80 where the bug disappeared for about a week. It just resurfaced again for me when I updated to 2.0.1. Here's a video I managed to record: https://www.youtube.com/watch?v=PNo32_Bhtu0

**Comment by stillinthe90s** [comment] 2016-03-09 15:35
A few of us are having similar problems with 2.0 stable ([http://www.godotengine.org/qa/537/2-0-stable-sometimes-fails-to-update-scripts-why](url)) where script changes sometimes are ignored when testing and lost when restarting Godot.
I'm on a win 64 system and did not have this problem with the 1.1 buld.

**Comment by Zylann** [comment] 2016-03-25 17:16
I noticed the same problem on Godot 2.0.1 Windows 7, while editing a script of my game.
Basically write something, don't save, focus another window, then refocus Godot: changes are lost.

**Comment by akien-mga** [comment] 2016-04-29 12:30
Closing as duplicate of #4444 (which has a cooler ID ;)), apparently the bug affects OSX and Linux too.

**Closed by akien-mga** 2016-04-29 12:30 UTC
Labels: bug, platform:windows, topic:editor
