### ISSUE TITLE
One-way Collision will not work rotated 

### ISSUE THREAD

**Issue by orosmatthew** [godotengine/godot#20204] opened 2018-07-17 03:53 UTC
Godot 3.0.5 Stable (Steam)

Windows 10 GTX 1060 6600K

I tried to rotate a one way Collision shape but it will not collide with my Kinematic Body character. It works when it is one way acting as a floor but not as a wall. Here is a gif of the situation. [https://i.imgur.com/91mCPT9.gif](https://i.imgur.com/91mCPT9.gif)

To reproduce, make a simple Kinematic 2d character and add a static body with a collision shape that is set to one-way and rotate either the shape or the static body by 90* and instance it in a scene.

Here is an example with the default kinematic body demo and a one way collision on the bottom left. [https://drive.google.com/uc?export=download&id=12vdhIBwVvgQxeUDijPU8HvGW-tXpLhq7](https://drive.google.com/uc?export=download&id=12vdhIBwVvgQxeUDijPU8HvGW-tXpLhq7)

**Comment by akien-mga** [comment] 2018-07-17 07:18
That's indeed a duplicate of #18493 and #12791 (will keep only the latter open).

**Closed by akien-mga** 2018-07-17 07:18 UTC
