### ISSUE TITLE
Project freezes importing obj file

### ISSUE THREAD

**Issue by rogerdv** [godotengine/godot#52847] opened 2021-09-19 13:14 UTC
### Godot version

4.0.dev

### System information

Windows 10, Nvidia GTC 980, Vulkan

### Issue description

About 3 months ago one test project stopped worlking when I updated and created my custom build for Linux. The importer freezes at xx percent, when importing some obj files that previously were working perfectly. Today I tried with an unofficial build downloaded from https://downloads.tuxfamily.org/godotengine/testing/4.0/ and the problem persists.

### Steps to reproduce

Open the attached project.

### Minimal reproduction project

[abnility-test-g4.zip](https://github.com/godotengine/godot/files/7192139/abnility-test-g4.zip)

**Comment by Calinou** [comment] 2021-09-19 18:19
Duplicate of https://github.com/godotengine/godot/issues/48265.

**Closed by Calinou** 2021-09-19 18:19 UTC
