### ISSUE TITLE
Editor crash on sync scenes

### ISSUE THREAD

**Issue by marcosbitetti** [godotengine/godot#3430] opened 2016-01-24 12:06 UTC
I insert one scene into other, and when update the scene I expect that it appears when running. But it not show! And when I change tables in Editor to see the inserted node the editor crash.
I was doing a video when it occurs.

https://www.youtube.com/watch?v=BRRKzuGVTjw

**Comment by zoiba** [comment] 2016-01-26 17:26
I confirm, the same happens to me

**Comment by reduz** [comment] 2016-01-26 17:58
please make a small example scene that shows how to reproduce this

**Comment by reduz** [comment] 2016-01-31 23:37
again, I can't reproduce it so please make a small scene where it happens so I can test

**Comment by marcosbitetti** [comment] 2018-01-29 18:28
I not see this bug in latest releases

**Comment by akien-mga** [comment] 2018-01-29 18:30
Great, closing then.

**Closed by akien-mga** 2018-01-29 18:30 UTC
Labels: bug, topic:editor
