### ISSUE TITLE
Cyclic dependency error with custom data types creating more of themselves

### ISSUE THREAD

**Issue by TimCoraxAudio** [godotengine/godot#49181] opened 2021-05-29 07:45 UTC
Godot version: 3.3.2
OS/device including version: Xubuntu 20.10

Issue description: If using a custom class and that class needs to create more of itself, a cyclic dependency error ensues

Steps to reproduce:
```gdscript
extends Node
class_name Item

var count: int
var item_id: int

func split_item(amount: int) -> Item:
    var item = Item.new(item_id, amount)
    count -= amount
    return item
```

I know this  can be prevented by doing:
```gdscript
func split_stack(amount: int) -> Item:
	var item = self.duplicate()
	item.count = amount
	count -= amount
	return item
```
But this is doing essentially the same thing. It also took me a long time to find this problem because the error came up in other classes at the end of the file

**Comment by nonunknown** [comment] 2021-05-29 10:42
Duplicate of #43529 & #21461

**Comment by Calinou** [comment] 2021-05-29 12:23
Closing per @nonunknown's comment.

**Closed by Calinou** 2021-05-29 12:23 UTC
