### ISSUE TITLE
await with time < 0.25 in while erase variant or crash

### ISSUE THREAD

**Issue by Noiros** [godotengine/godot#56644] opened 2022-01-09 09:34 UTC
### Godot version

v4.0.dev.20220105.official [8f6cba3a4]

### System information

Windows 11, GLES3, Rx 5700 XT, Ryzen 7 3600x

### Issue description

if you get an variable in while true with a await timer set below 0.25 sec the variable is erase ...

### Steps to reproduce

put this code in any script

`extends Node

var inv = [["FI", 0, 30]]

func _ready():
	while true:
		print(inv[0][0])
		await get_tree().create_timer(0.1).timeout`

### Minimal reproduction project

[bug.zip](https://github.com/godotengine/godot/files/7834769/bug.zip)

**Comment by ccuntd** [comment] 2022-01-09 10:47
![image](https://user-images.githubusercontent.com/85245131/148678983-e11a263d-351c-412e-a6c7-74e34e716a9f.png)
wym

**Comment by ccuntd** [comment] 2022-01-09 10:49
sometimes it says this and crashes
`Unicode parsing error: Invalid unicode codepoint 3f800000.`

the title is pretty shiddy and doesn't explain what's goin on, the problem is different, it crashes.

**Comment by jmb462** [comment] 2022-01-09 11:47
Cannot reproduce this issue (no variable lost, no crash) with very last v4.0.dev.custom_build [5a61822d7]
But I get this warning once at launch.
```
W 0:00:01:0382   "await" keyword not needed in this case, because the expression isn't a coroutine nor a signal.
  <C++ Error>    REDUNDANT_AWAIT
  <Source>       test.gd:8```

**Comment by ccuntd** [comment] 2022-01-09 14:16
for me it says this on latest build:
```
 
FI
FI
FI
FI
FI
  Unicode parsing error: Invalid unicode codepoint 706e7968.
  Unicode parsing error: Invalid unicode codepoint 706e7968.
  Unicode parsing error: Invalid unicode codepoint 594a5356.
  Unicode parsing error: Invalid unicode codepoint 454b6331.
  Unicode parsing error: Invalid unicode codepoint 50515759.
```

and so on..., the wait stacks, more and more it tries to print, until it does it like 10000 times a second

**Comment by ccuntd** [comment] 2022-01-09 14:18
> and so on..., the wait stacks, more and more it tries to print, until it does it like 10000 times a second

doesn't happen when i'm printing 1 instead of inv

**Comment by ccuntd** [comment] 2022-01-09 14:19
here, i fixed your code:
```
extends Node

var inv = ["FI", 0, 30]

func _ready():
	while true:
		await get_tree().create_timer(.1).timeout
		print(inv)
```

**Comment by KoBeWi** [comment] 2022-01-09 16:37
Also can't reproduce. Maybe it's some system-specific issue? Tested on Windows 10.

**Comment by gokiburikin** [comment] 2022-01-09 20:33
This looks very similar to the issue I posted recently https://github.com/godotengine/godot/issues/56587 that only occurs on release builds.

Opening this MRP in debug builds (tested in v4.0.dev.calinou [e885de050]) has no issue, but opening it in release builds (tested in v4.0.dev.20211210.official [21b81998b]) only prints FI ~5 times before FI fails to print on my machine. Not as severe as a crash, but still not correct.

**Comment by ccuntd** [comment] 2022-01-09 21:03
for me doesn't crash at all

**Comment by cdemirer** [comment] 2022-01-26 21:48
I can't reproduce either (tested on Linux, with both `debug` and `release_debug`).

**Comment by akien-mga** [comment] 2022-01-27 09:24
I'll close this one as duplicate of #57126 which is clearer about how to reproduce the bug.

**Closed by akien-mga** 2022-01-27 09:24 UTC
Labels: bug, topic:core, needs testing
