### ISSUE TITLE
System crash when opening (by mistake) the same project in 2 instances

### ISSUE THREAD

**Issue by juddrgledhill** [godotengine/godot#35622] opened 2020-01-27 14:40 UTC
**Godot version:**
3.2.1

**OS/device including version:**
Windows 10 Enterprise
16GB RAM
i7 6600

**Issue description:**
I hard crashed my PC when I mistakenly opened the same project in 2 instances of the editor.

**Steps to reproduce:**
Open a project in Godot.
Go back to the OS/explorer, open Godot editor again
Choose the same project in the editor window
Machine turns off.

No error message, no blue screen, nothing. Just crashed me to nothing. I thought that I had a power outage in the building.

I know it is a bad idea to open the same stuff twice in 2 different instances, but I am guessing that the hard crash was not intentional and some sort of error messaging would be preferable.

**Minimal reproduction project:**

**Comment by eon-s** [comment] 2020-01-27 14:45
Look at the system logs and try to find more information about the crash, if it was so bad it may be a OS thing (probably video driver), I think that there is no way for Godot to handle that kind of OS problems.

**Comment by juddrgledhill** [comment] 2020-01-27 16:01
I will check them. The confusing thing is that I can certainly run the editor twice, and have many times, but when it is the same project, it explodes.

Here are 2 that look like candidates:

1) The system has rebooted without cleanly shutting down first. This error could be caused if the system stopped responding, crashed, or lost power unexpectedly.

2) The previous system shutdown at 5:10:25 PM on ‎1/‎24/‎2020 was unexpected.

**Comment by Calinou** [comment] 2020-02-02 18:04
@juddrgledhill Can you upload a minimal reproduction project or find a way to get a full system trace? Without this, it's impossible to solve the issue at hand.

**Comment by juddrgledhill** [comment] 2020-02-02 20:35
I will, yes. Global Game Jam today, will try and do that ASAP.

**Comment by KoBeWi** [comment] 2020-03-05 21:24
I can't reproduce it no matter how many times I open the same project. It's either project specific or system specific. You can try with another project to rule out either option.

**Comment by Calinou** [comment] 2020-04-05 20:47
@juddrgledhill Have you been able to reproduce this? If not, I'm afraid we'll have to close this issue as it's difficult to troubleshoot.

**Comment by juddrgledhill** [comment] 2020-04-05 20:48
No, I haven't.

I did try a couple of times, but since it occurred on my work computer, I
am thinking that it might be something about that machine. I have a similar
machine at home and it has not had the issue.

Judd

**Comment by KoBeWi** [comment] 2020-04-05 21:01
So closing this. You could have posted the status update earlier...

**Closed by KoBeWi** 2020-04-05 21:01 UTC

**Comment by Calinou** [comment] 2020-04-05 21:36
Thanks anyway for replying :slightly_smiling_face:

**Comment by juddrgledhill** [comment] 2020-04-05 21:38
No worries. 3 kids makes it tough to remember to post to github ;-)
