### ISSUE TITLE
Accessing a freed node causes inconsistent error reporting (3.0.6)

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#25939] opened 2019-02-16 13:36 UTC
Godot 3.0.6
Windows 10

Following https://godotengine.org/qa/40767/released-game-crash-but-runs-flawlessly-in-editor, I'm writing this issue for the record (which exists in 2.1 as #20302 but could not find a 3.0.6 equivalent).

The following code causes inconsistent behavior:

```gdscript
extends Node

# The scene is just a node with a child Sprite
func _ready():
	yield(get_tree(), "idle_frame")
	var sprite = get_node("Sprite")
	sprite.queue_free()
	
	yield(get_tree(), "idle_frame")
	yield(get_tree(), "idle_frame")

	print(sprite.position)
```

In Godot 3.0.6, sometimes the error is `Invalid get index 'position' (on base: 'GDScriptFunctionState').`. But other times, no error is reported and the game just freezes. In the context of a larger game like the Q&A thread, it can apparently be silent and only show up after export.

That said, I also found that if you try to debug a project with 3.1 *while the 3.0.6 debugger is hanging*, the 3.1 debugger will also hang, even though they are separate projects.

**Comment by akien-mga** [comment] 2020-01-13 14:33
I'll close this as duplicate of #32383.

**Closed by akien-mga** 2020-01-13 14:33 UTC
Labels: bug, topic:editor
