### ISSUE TITLE
Godot taking lots of CPU and being unresponsive after suspend on X11 Ubuntu 22.04

### ISSUE THREAD

**Issue by perry-blueberry** [godotengine/godot#85956] opened 2023-12-09 10:32 UTC
### Tested versions

Reproducible in 4.2.0.stable, 4.1.2.stable (and probably all versions since Godot 4.0.stable, including mono versions).

### System information

Godot v4.2.stable.mono - Ubuntu 22.04.3 LTS 22.04 - X11 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3070 (nvidia; 535.129.03) - AMD Ryzen 7 3700X 8-Core Processor (16 Threads)

### Issue description

After I resume my Ubuntu system from a suspend with Godot previously opened, the Godot editor is unresponsive (if I resize the window for example nothing inside the editor window is redrawn, but the window itself changes size) and it's taking up lots of CPU. Happens every time. Only way to deal with it is to forcibly close the Godot editor.

It seems to have something to with Vulkan as I'm getting these errors thrown continuously:
> ERROR: Vulkan: Cannot submit graphics queue. Error code: VK_ERROR_DEVICE_LOST
   at: swap_buffers (drivers/vulkan/vulkan_context.cpp:2536)
ERROR: Vulkan: Did not create swapchain successfully. Error code: VK_NOT_READY
   at: prepare_buffers (drivers/vulkan/vulkan_context.cpp:2459)

### Steps to reproduce

1. Create a new project in the editor
2. Suspend Ubuntu without closing editor and project
3. Awaken Ubuntu to find the error

### Minimal reproduction project (MRP)

N/A

**Comment by Zireael07** [comment] 2023-12-09 12:43
dupe of #82247

**Comment by Calinou** [comment] 2023-12-09 13:29
Thanks for the report! Consolidating in https://github.com/godotengine/godot/issues/71929.

**Closed by Calinou** 2023-12-09 13:29 UTC
