### ISSUE TITLE
segfault in "Reparent Node" dialog

### ISSUE THREAD

**Issue by dherring** [godotengine/godot#14538] opened 2017-12-11 02:42 UTC
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Debian 9.3, Godot_v3.0-beta1_x11.64

**Issue description:**
"Reparent Node" dialog segfaults on invalid parent selection.

**Steps to reproduce:**
In the following steps, the specific node type and tree depth is not important.
You just need two or more nodes and an invalid parent selection.

1. Create an empty project.
3. Under "Scene", click "+" and add a Node2D.
4. Click "+" and add another Node2D. (It appears as a child of the first node.)
5. Right click on second Node2D, and select Reparent.
6. In the dialog, double-click in the empty tree view space below the second Node2D.

The editor will segfault.

    handle_crash: Program crashed with signal 11

**Comment by akien-mga** [comment] 2017-12-11 06:53
Godot 3.0 beta1 came with debug symbols in the `Godot_v3.0-beta1_x11.64.debug`, which will be loaded automatically to get a backtrace if kept next to your binary. Didn't it happen here?

If not, can you run it trough `gdb` (note that to debug the actual editor and not the project manager, you should `cd` to your project directory, and in `gdb` run `run -e`) and get a backtrace when it crashes? (`bt`)

**Comment by volzhs** [comment] 2017-12-11 07:03
I can reproduce with `Godot_v3.0-beta1_x11.64` from official beta1.
but can't reproduce it with current master head c05c66ee01bcf285d5b4d952fb24c15af281803d 
probably it's fixed between official beta1 and now.

**Comment by volzhs** [comment] 2017-12-11 07:27
probably by https://github.com/godotengine/godot/commit/b8b5bb657767698b5864356fb2549ee9681f1bd6#diff-5d8a6d4c5fbd4ef652a74f16a0ccda4f

**Comment by akien-mga** [comment] 2017-12-11 07:31
Closing as fixed then.

**Closed by akien-mga** 2017-12-11 07:31 UTC
Labels: bug, topic:core

**Comment by dherring** [comment] 2017-12-12 00:27
@akien-mga The Godot_v3.0-beta1_x11.64.debug in Godot_v3.0-beta1_x11.64.zip does not actually contain debug symbols.

I can confirm that this bug has been fixed.  Tested on build c05c66e

**Comment by akien-mga** [comment] 2017-12-12 06:55
> The Godot_v3.0-beta1_x11.64.debug in Godot_v3.0-beta1_x11.64.zip does not actually contain debug symbols.

Hm, that's right.. @hpvb It looks like LTO is breaking symbol extraction?
