### ISSUE TITLE
FileDialog is blurry when `content_scale_factor>1.0` and `gui_embed_subwindows=true`

### ISSUE THREAD

**Issue by PDeveloper** [godotengine/godot#77371] opened 2023-05-22 19:43 UTC
### Godot version

4.0.2

### System information

Windows 10 Vulkan API 1.2.175 - Forward+ - NVIDIA GeForce GTX 860M

### Issue description

When creating a FileDialog in a HDPI window, with `content_scaling_factor=2.0` (for example), the FileDialog is properly scaled, but its rendering is noticably blurry in contrast to the rest of the content which is crispy on a HDPI display.

### Steps to reproduce

1. Create a FileDialog
2. Set Project `content_scaling_factor=2.0`
3. Run project and `popup()` the FileDialog
4. Notice it is blurry while the rest of the GUI isn't

If trying to manually apply `content_scaling_factor` to the `FileDialog`, no matter if it's embedded or not, results in the FileDialog GUI being scaled past the FileDialog window boundaries, and this cannot be undone.

### Minimal reproduction project

Run the project, the FileDialog will be blurry

[FileDialogTest.zip](https://github.com/godotengine/godot/files/11536381/FileDialogTest.zip)

**Comment by Calinou** [comment] 2023-05-22 21:41
- Duplicate of https://github.com/godotengine/godot/issues/70791 (same cause).

**Closed by Calinou** 2023-05-22 21:41 UTC
