### ISSUE TITLE
Editor crash moving files

### ISSUE THREAD

**Issue by grevius5** [godotengine/godot#32025] opened 2019-09-07 09:17 UTC
Godot 3.1 stable

Linux Manjaro

If you move scene file and associated script at the same time in another directory by FileSystem Godot crash

Create a project with a scene and attach a script to it. Create a folder in the project and drag in the scene and the script together.

**Comment by Calinou** [comment] 2019-09-07 13:11
Duplicate of #29266.

**Closed by Calinou** 2019-09-07 13:11 UTC
