### ISSUE TITLE
Constant expressions not allowed in export var ranges

### ISSUE THREAD

**Issue by caryoscelus** [godotengine/godot#6391] opened 2016-09-04 12:29 UTC
Neither referencing previously defined consts nor using numeric-only expressions (e.g. 1.0/64) can be used in export var range hints.

```
export(float, 1.0/64, 64) # SCRIPT ERROR: GDScript::reload: Parse Error: Expected ',' or ')' in numeric range hint.
const a = 4
export(float, a, 5) # SCRIPT ERROR: GDScript::reload: Parse Error: Expected a range in numeric hint
```

**Comment by reduz** [comment] 2016-09-07 03:29
Will change how this works in 3.0

**Comment by rosshadden** [comment] 2017-07-22 19:56
This seems to be true for using any constant in another constant's definition.

```gdscript
const cellSize = 32
const cellDim = Vector2(cellSize, cellSize)
```

**Comment by reduz** [comment] 2017-08-05 13:20
will leave this open to remind me to fix it before 3.0 is out

**Comment by akien-mga** [comment] 2018-01-09 17:41
Still reproducible in the current master branch.

> will leave this open to remind me to fix it before 3.0 is out

@reduz Time is running out if you still want to do this.

**Comment by akien-mga** [comment] 2018-01-15 08:36
Too late for 3.0, it will have to be implemented in a way that doesn't break compatibility for 3.x.

**Comment by akien-mga** [comment] 2018-09-15 10:48
This is still valid in the current master branch. Not critical for the 3.1 milestone though, moving to 3.2 where various GDScript improvements are expected.

**Comment by mentos1386** [comment] 2018-11-18 16:02
Issue also course with using `enum` values as `const` values definition. Really annoying

**Comment by akien-mga** [comment] 2020-05-26 10:57
@vnen If you plan to implement this for 4.0, feel free to reopen a short GIP to keep track of it.

---

Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!

**Closed by akien-mga** 2020-05-26 10:57 UTC
Labels: confirmed, feature proposal, topic:gdscript
