### ISSUE TITLE
Godot freeze computer, when shadow contact set to 1

### ISSUE THREAD

**Issue by djrm** [godotengine/godot#9740] opened 2017-07-20 23:30 UTC
**Operating system or device - Godot version:**
Fedora NVidia GTX 900 series, Driver 381.22 Godot version: 2a0c0db028c84c75f4a927d0fd400449f3236952

**Issue description:**
Godots starts using a LOT of CPU, causing the entire OS to freeze, sometimes im even unable to close godot.

**Steps to reproduce:**
Open the attached project and move the camera towards the walls until you start to touch them (i was using the freelook mode). !WARNING DOING THIS MIGHT FREEZE YOUR COMPUTER, SO TRY TO CLOSE GODOT AS SOON AS POSSIBLE IF IT STARTS TO SLOW DOWN.

As far as i can tell this only happens when the Directional Light shadow contact is set to 1 (dont really know if lower values also work) but with contact set to 0 it does not happen, on 1 this will always happen.

**Link to minimal example project:**

[computer_freeze_test.zip](https://github.com/godotengine/godot/files/1163959/computer_freeze_test.zip)

**Comment by Calinou** [comment] 2017-07-21 00:03
I've been able to reproduce this once, with the NVIDIA driver on Linux. This can be caused if you progressively increase/decrease the value, especially (for example, if you drag the mouse cursor after selecting the Contact property).

**Comment by Zylann** [comment] 2017-07-21 00:04
Last time I tested contact shadows a month ago they did something similar, Godot froze and it was difficult for me to close it due to general slowdown.

**Comment by reduz** [comment] 2017-07-25 12:30
this kinda sounds like a driver bug, but i will give it a check... and add some tests to avoid too high values

**Comment by reduz** [comment] 2017-07-26 18:21
AMD on linux cant reproduce :\

**Comment by djrm** [comment] 2017-07-26 22:10
reduz: you are right, it could be a driver issue, since on intel does not happen, there is a slow down when doing the reported action (moving through the ground), but it does not freeze the computer.

**Comment by reduz** [comment] 2017-08-07 02:03
i did some changes to the shaders to avoid a potential freeze, is it fixed for anyone with nvidia?

**Comment by djrm** [comment] 2017-08-07 02:20
it is fixed for me.

**Comment by vnen** [comment] 2017-08-07 05:15
Closing as fixed then.

**Closed by vnen** 2017-08-07 05:15 UTC
Labels: bug, topic:rendering
