### ISSUE TITLE
PoolStringArray.find() throws segmentation fault in Release, but no errors or warnings in Debug

### ISSUE THREAD

**Issue by Streq** [godotengine/godot#56017] opened 2021-12-17 12:34 UTC
### Godot version

v3.4.stable.official [206ba70f4]

### System information

Ubuntu 20.4, GLES2, HTML5 and Linux builds

### Issue description

Overriding a PoolStringArray export var with any value will make it throw segmentation fault in release exports for linux and html5, without errors or warnings in debug.

### Steps to reproduce

Create a Node2D main scene with the following script
```
extends Node2D

export (PoolStringArray) var array := ["val"]

func _ready():
	array.find("val")

```
override array property value in editor like so 
![image](https://user-images.githubusercontent.com/8540266/146545157-e6eca479-dddb-4843-b41e-284858593b0f.png)

export project in release mode and run from terminal, a segmentation fault will happen, this, however, will not happen in debug mode.

### Current Workaround
Specifying the array property to be of type Array
`export (PoolStringArray) var array : Array = ["val"]`

### Minimal reproduction project

[test bug poolstringarray.zip](https://github.com/godotengine/godot/files/7735087/test.bug.poolstringarray.zip)

**Comment by akien-mga** [comment] 2021-12-17 12:45
I can confirm the crash on 3.4-stable with a `target=release` build.

`PoolStringArray` doesn't have a `find()` method, so this should in theory also fail and raise an error in debug builds, but for some reason it's not working.

Note that the code is invalid, as the export hint uses `PoolStringArray`, but the actual type defined in the script is `Array` (`:= ["val"]` will infer the type as `Array`). The type then changes when modified through the inspector to follow the export hint, and this mismatch between type hint and export hint doesn't seem to be handled consistently in debug and release.

**Comment by Streq** [comment] 2021-12-17 12:55
So essentially: overriding the export (PoolStringArray) var array := ["val"] in editor in debug would make the variable be of type Array (since the find method works in debug) and overriding the export in editor in release would make the variable be of type PoolStringArray, is that correct?

**Comment by akien-mga** [comment] 2021-12-17 13:01
Yeah that seems to be the issue.

**Comment by akien-mga** [comment] 2021-12-29 16:11
Duplicate of #48090

**Closed by akien-mga** 2021-12-29 16:11 UTC
Labels: bug, topic:gdscript, confirmed, crash
