### ISSUE TITLE
Resetting properties of instanced scene

### ISSUE THREAD

**Issue by magpie514** [godotengine/godot#17277] opened 2018-03-05 10:01 UTC
**Godot version:**
e619727

**OS/device including version:**
Ubuntu Linux 17.10 64bit

**Issue description:**
I have a scene (let's call it A) with a Panel node and a few buttons with signals and whatnot.
That scene is instanced in another scene, (let's call it B), but when I make changes to the base Panel node in scene A, specifically its rect size, the changes not only don't fully reflect in B, but the reset button won't let me get the size of A as set in its scene file. Changing child element sizes in A seems to reflect fine in B, though. 
Other Control-inheriting nodes seem to display the same behavior as well.

While this is just a papercut UX kinda sort of bug, and it's not too bad when it's just a few elements changing in size, or elements aligning to a grid, but can be a bit annoying when doing those changes often or during more complete overhauls. So it'd be nice if the reset button could work in those situations to help expediting the process.

**Steps to reproduce:**
1) Create a scene with a Panel node and some childs like buttons or something for scene A.
2) Create a second scene and instance scene A for scene B.
3) In scene A, alter the size rect of the buttons and the base Panel. Save.
4) When switching to scene B, the changes in rect for the buttons are present, but the panel size won't change, and pressing the reset button does nothing.

**Comment by Zylann** [comment] 2018-03-05 13:47
I can't reproduce this in 3.0 stable.

**Comment by hetdegon** [comment] 2018-03-05 15:50
Oh, panel size is overriden if instanced as a child node? Well, my mistake, that could explain it.
Still, the reset button not working is the important issue here.

**Comment by Zylann** [comment] 2018-03-05 17:18
> Oh, panel size is overriden if instanced as a child node?
Only if you put it as child of a `Container` node, like `VBoxContainer` or `GridContainer` ;)

**Comment by hetdegon** [comment] 2018-03-05 19:36
Oh, that's not the case, then
![out5](https://user-images.githubusercontent.com/323651/36995609-d57eead4-20b4-11e8-93c7-4ca4bb63fec6.png)

**Comment by groud** [comment] 2018-03-06 09:18
The Rect value in not really a property of the node, it's a value dependant on both the node's anchors and margin values, and the parent's size. 
Could you check if the margins and anchors values are kept correctly ?

**Comment by hetdegon** [comment] 2018-03-06 14:28
I never really modify those, I prefer manual placement where available.

**Comment by groud** [comment] 2018-03-06 14:36
Well maybe, but that's how control works. If the margin and anchors values stay the same when inheriting this is an intended behavior. The rect is not guaranteed to stay the same since it depends on the parent's size.

**Comment by hetdegon** [comment] 2018-03-06 18:11
That's a tiny bit annoying, but should be all fine if the reset button is made to simply take the "original" size rect. 
Maybe I wrote the issue wrong (I struggle a bit with English at times, it's not my main language, sorry for that), but the reset button for size is the actual thing here. It'd be kinda ideal if it'd reflect automatically, but pressing one button and repositioning is sure faster than manually resizing and repositioning, specially as the number of elements grows.

As for the margin and anchor values, as I said I never used them, unless... are they being set automatically "behind the scenes" when you instance a control as a child of another control? That'd explain it. Note that none of the custom UI I use make use of the scale property, in case that'd affect things.

**Comment by groud** [comment] 2018-03-06 18:38
When you modify the Control's Rect, position or size, it in facts modifies the values of the anchors and margins. Only the anchors and margins values are actually recorded when saving the scene.

The rect/position/size properties are in fact helpers to set the anchors and margins, but they depend on the parent. Thus when you instance the scene, the rect changes since the parent is not the same anymore. Thus the rect changing is not a problem.

That being said, the fact that the button is displayed next to the Rect property is misleading, I agree that it should be removed, but it might need to wait the rework of the inspector before.

**Comment by hetdegon** [comment] 2018-03-06 19:47
Hm, I see... strange I didn't see mention of it anywhere else. Specially since using the pos and size rects via code seems to work as expected.
That said, I'd *really* prefer if it could get the instance's "default" size since it'd be a nice time-saver. 
I'd like to emphasize the "as the number of elements grows" in my previous reply. To have a control be the size you want in the final scene after you change it, you must go to the scene, open the rects sections in the inspector, check the size, go back to the final scene, put the size in, then reposition. With the button working, it's just press reset and reposition.
On a single control it's a few seconds, when it's several similar ones, it's enough time and tedium to get your mind away from whatever you were doing. Please consider that before removing it entirely.

**Comment by groud** [comment] 2018-03-06 19:52
If you need the size and position kept when you instance a Control scene, just set all the anchors to 0. This will remove the impact of the parent's rect on the node's when you instance it.

**Comment by hetdegon** [comment] 2018-03-06 19:57
That's the thing, as I said I never touch them. To test it out, I made a quick menu and instanced it elsewhere, then raised its height by 10 pixels by the grid.
![out5](https://user-images.githubusercontent.com/323651/37054905-8a33cfc8-2180-11e8-946a-8a067a5fcae2.png)
Now the instance is still the same size it was when going back to the other scene. Anchors are still 0.
![out5](https://user-images.githubusercontent.com/323651/37054925-9cd5b204-2180-11e8-9027-be069fd40777.png)

**Comment by groud** [comment] 2018-03-06 20:00
What's the instanced scene parent's in the tree ?

**Comment by hetdegon** [comment] 2018-03-06 20:01
Ah, I edited my reply but was too slow :grin: 
Yeah every single control I have has all anchors set to zero. As said I never touch them.

**Comment by groud** [comment] 2018-03-06 20:01
Can you provide the full screenshot with both the anchor + margin values and the scene tree in both scenes ?

**Comment by hetdegon** [comment] 2018-03-06 20:12
Please don't laugh at the crappiness of this test scene.
![out5](https://user-images.githubusercontent.com/323651/37055499-2c7d0726-2182-11e8-9db1-f8014919613e.png)
![out5](https://user-images.githubusercontent.com/323651/37055505-318de802-2182-11e8-9c22-91517d18c7d6.png)
The second has a few margin values, although I didn't set them manually.

![out5](https://user-images.githubusercontent.com/323651/37055651-855d7dd0-2182-11e8-85c5-093ed667d335.png)
The change in size doesn't reflect when running the scene either. Menu slides in and out, so its position changes at runtime, still keeps the old size in the test scene instead of the new.

Resetting margin values in the test scene results in this
![out5](https://user-images.githubusercontent.com/323651/37055788-edfb5c72-2182-11e8-94ca-b8aa90abbaf5.png)

**Comment by Zireael07** [comment] 2018-03-06 20:14
When you instance the scene, what is the parent node that you child it to?

**Comment by hetdegon** [comment] 2018-03-06 20:16
Oh my bad. But the Panel that is the direct parent of battlecontrols is still having anchors at 0.
![out5](https://user-images.githubusercontent.com/323651/37056070-9fdeae80-2183-11e8-86f9-da916d977d41.png)

**Comment by groud** [comment] 2018-03-06 20:18
Ok I think understood wrongly the problem, the only unexpected behaviour here is the reset's button one. The size is not change when you instance the scene am I right ?

**Comment by hetdegon** [comment] 2018-03-06 20:19
Nope, when freshly instanced it's an 1:1 copy.

**Comment by groud** [comment] 2018-03-06 20:34
Oh, ok thank. The issue is perfectly valid then, sorry I was a little bit confused by what you described.

**Comment by hetdegon** [comment] 2018-03-06 21:03
I apologize, and thanks for the explanation of how controls actually work. Coming from hacking UI elements in libsdl and C by throwing math and pointers at the text editor, concepts such as anchors and margins are a little bit alien to me. I kinda just eyeball everything up until it stops looking ugly eventually...which is perhaps the worst approach possible, but humans are creatures of habit.

**Comment by Calinou** [comment] 2020-06-07 19:32
@magpie514 Can you (or anyone else) still reproduce this bug in Godot 3.2.1 or [3.2.2beta4](https://godotengine.org/article/dev-snapshot-godot-3-2-2-beta-4)?

**Comment by magpie514** [comment] 2020-06-09 13:19
I cannot try 3.2.2b4 at the moment, but in 3.2.1 it requires a weird dance of resetting the sizes, then the margins, then the size again until it kind of works.

**Comment by KoBeWi** [comment] 2024-04-24 15:04
Can't reproduce this in 4.3, closing.
Please comment if you can still reproduce and provide a minimal reproduction project.

**Closed by KoBeWi** 2024-04-24 15:04 UTC
Labels: bug, topic:gui
