### ISSUE TITLE
Issue with rigdibody2d with scale x set to -1

### ISSUE THREAD

**Issue by Vrzasq** [godotengine/godot#31622] opened 2019-08-24 08:00 UTC
**Godot version:**
official 3.1.1

**OS/device including version:**
* GPU gtx1080 drivers GeForce Game Ready Driver v431.36
* CPU i5-750
* Windows 10

**Issue description:**
I have an issue with rigibody2d when transform scale x is set to -1. It flip my sprite upside down.

The demo scene is setup as show on the picture below:
![picture](https://imgur.com/1zdbFF4.jpg)

Basically left unicorn is duplicated version of right unicorn with rigidbody2d scale x set to -1. When I play the scene the left unicorn is flipped.
![picture](https://imgur.com/VpvB8LM.jpg)

That happens also when I wrap rigidbody2d with node2d and change x scale on that.

**Steps to reproduce:**
* Create Scene
* add rigidbody2d with sprite and collision shape attached to it
* duplicate rigibody2d and chnage its x scale to -1
* play the scene

**Minimal reproduction project:**

[unicorn_wars.zip](https://github.com/godotengine/godot/files/3536983/unicorn_wars.zip)

**Comment by KoBeWi** [comment] 2019-08-24 12:10
Duplicate of #12335

**Closed by KoBeWi** 2019-08-24 12:10 UTC
