### ISSUE TITLE
queue_free() still shows the node exists in relesed game

### ISSUE THREAD

**Issue by Scubadoo2** [godotengine/godot#41554] opened 2020-08-27 01:35 UTC
**Godot version:**
Godot 3.2.2 GLES3

**Issue description:**
When using queue.free() on an node, I expect it to become null when checking
if it exists (node == null). So a script that has it stored as a variable
can check if it still exists by doing that test.

This works fine in the editor and debug game, but the official release
doesn't seem to recognize that it's gone. So it will say that it exists and then
trying to access anything in it results in a crash.

**Steps to reproduce:**
1. Have one node store another node in a variable
2. Have the stored node use queue_free() on itself.
3. Have the first node test if the stored node is null and show it in game (NOT just print()).
4. Test in editor, it should say that it is gone when it is gone.
5. Export it in debug mode and run. It should show when it is gone.
6. Export without debug. It will say that it is still there when it is actually gone.

**Minimal reproduction project:**
[QueueFreeTest.zip](https://github.com/godotengine/godot/files/5133470/QueueFreeTest.zip)

**Comment by Zireael07** [comment] 2020-08-27 07:21
I believe this is a known issue, but I can't remember the number of the open issue.

**Comment by Calinou** [comment] 2020-08-27 12:23
Duplicate of https://github.com/godotengine/godot/issues/35534. This can only be resolved in `master` due to the performance cost it would have in `3.2` in release builds.

**Closed by Calinou** 2020-08-27 12:23 UTC

**Comment by naithar** [comment] 2020-08-27 12:25
@Scubadoo2 you can use `is_instance_valid(target)` to check if instance is valid. Once `target` is freed `is_instance_valid` should return `false`.

**Comment by Zireael07** [comment] 2020-08-27 12:37
@naithar: There are open issues related to is_instance_valid(), though.

**Comment by Scubadoo2** [comment] 2020-08-28 17:37
The problem is not that `queue_free()` isn't returning null, the problem is that it IS returning null in the editor and debugger but ISN'T in the released build.

What needs to be fixed is making them consistent, either by having it return `null` or by having a crash in the editor saying that the Node has been freed.
