### ISSUE TITLE
[3.2.2 beta1 mono] Break project compatibility

### ISSUE THREAD

**Issue by git2013vb** [godotengine/godot#38153] opened 2020-04-23 18:20 UTC
**Godot version:**
3.2.1 stable mono
**OS/device including version:**
Debian 10
**Issue description:**
I opened the project with 3.2.2 beta1 mono and when I come back to stable I have this error:
```
Project "desert_edge_sharp.sln" (Build target(s)):
	/home/vale/godot/desert_edge_sharp/desert_edge_sharp.sln.metaproj(0,0): error MSB4126: The specified solution configuration "Tools|Any CPU" is invalid. Please specify a valid solution configuration using the Configuration and Platform properties (e.g. MSBuild.exe Solution.sln /p:Configuration=Debug /p:Platform="Any CPU") or leave those properties blank to use the default solution configuration. [/home/vale/godot/desert_edge_sharp/desert_edge_sharp.sln]
Done building project "desert_edge_sharp.sln" -- FAILED.
```

Edit: the 3.2.2 modify the sln file in "Global" section renaming "Release" and Tools". I had to revert back manually to let project to compile again :) - Same thing in csproj file
**Steps to reproduce:**
See before
**Minimal reproduction project:**
NA

**Comment by neikeq** [comment] 2020-04-25 14:36
We changed the configuration names as it improves experience with external editors/IDEs. Such tools tend to assume `Debug` is the default configuration, but in Godot the default was `Tools`. The changes were:

```
Debug -> ExportDebug
Release -> ExportRelease
Tools -> Debug
```

We decided to include the change in 3.2.2 even though it breaks compatibility, as the benefits are considerable, and considering how far we still are from a 4.0 release.

In the next 3.2.2 build (not sure if beta2, rc or stable) Godot will save a copy of the old sln and csproj files.
Maybe there's more we can do to improve compatibility. We could re-add a `Tools` configuration that would be mapped to `Debug`. That would make it work for running games from older versions of the Godot editor. We can't do the same for export configurations though, as we can't map `Debug` to `ExportDebug`.

**Comment by git2013vb** [comment] 2020-04-26 20:59
Thank you,
Personally I notice this issue because I had to come back to stable version cause this [#38129](https://github.com/godotengine/godot/issues/38129#issuecomment-618524079)

To me having a backup copy of sln and csprj will be enough - not worth to make more effort for this - so just in case someone need. I think when a release is working/stable people usually don't go back.

**Comment by neikeq** [comment] 2020-04-26 22:48
We can re-add `Tools` and `Release` as aliases for `Debug` and `ExportRelease` respectively. But we cannot re-add `Debug` as alias for `ExportDebug` because `Debug` is already taken.

I think this would still be better than completely breaking compatibility though. It means everything would work as expected for the editor/player and when exporting in release mode.
Not sure about exporting in debug mode. I think it would "work", but it would include editor code (code in `#if TOOLS`) if the project has any.

**Comment by git2013vb** [comment] 2020-05-22 16:46
I'm guessing right if I say this isn't yet in beta3?

**Comment by nobuyukinyuu** [comment] 2020-06-29 21:08
The problem seems to stem from the default build task in vscode not being updated to the new configuration.  Go into `tasks.json` and find this section:

```
            "label": "build",
            "type": "shell",
            "command": "C:/Program Files (x86)/Microsoft Visual Studio/2019/BuildTools/MSBuild/Current/Bin/amd64/MSBuild.exe",
            "args": [
                "/p:Configuration=Tools;Platform=Any CPU;GenerateFullPaths=true",
                "/t:Build;"
            ],
```

and change the part where it says `/p:Configuration=Tools;` to say `/p:Configuration=Debug` instead.

**Comment by mmarramarco** [comment] 2020-08-07 21:18
Hi,

I'm having the exact same problem but one Win10, using Visual Studio.

I thought that changing either the solution or the .csproj's configuration so that it matches "Debug / Any CPU" would suffice, but I'm still getting the error. Any ideas as to what I could change next?

![image](https://user-images.githubusercontent.com/27198388/89689038-c6b37380-d903-11ea-8400-85a246966184.png)

![image](https://user-images.githubusercontent.com/27198388/89689225-3cb7da80-d904-11ea-97f5-6544d02bc595.png)

note : on the second picture changing the conditional compilation symbol had no effects. I tried to replace it by DEBUG and nothinhg.

**Comment by neikeq** [comment] 2020-08-08 17:20
@mmarramarco What's the error you get? Is it from Godot or VS?

**Comment by mmarramarco** [comment] 2020-08-10 19:07
sorry @neikeq , I only know saw your message... The error is from the Godot. It's exactly the same as described by git2013vb : "	
```error MSB4126: The specified solution configuration "Tools|Any CPU" is invalid. Please specify a valid solution configuration using the Configuration and Platform properties (e.g. MSBuild.exe Solution.sln /p:Configuration=Debug /p:Platform="Any CPU") or leave those properties blank to use the default solution configuration.```

I ended up just switching over to VSCode, and wait and see if you can fix it by 3.2.3 stable. The configurations was simplier to tackle over there.

**Comment by neikeq** [comment] 2020-08-11 14:50
Are you getting this error in Godot 3.2.2/3.2.3? Or is this Godot 3.2.1 trying to open a project created by one of those newer versions?

**Comment by mmarramarco** [comment] 2020-08-11 16:40
nope, It's in godot 3.2.2, trying to open a project created in 3.2.1.

**Comment by neikeq** [comment] 2020-08-11 19:45
Hmm, that is weird. I would expect it to be the other way around. Can you upload that project for me to test?

**Comment by mmarramarco** [comment] 2020-08-12 18:58
[Olympiad-master.zip](https://github.com/godotengine/godot/files/5065066/Olympiad-master.zip)

Here it is. Although, this one is working... I didn't kept a copy of the "broken" one. As I said, switching to VSCode and using your add-on fixed the configuration issue.

**Comment by akien-mga** [comment] 2020-12-10 15:43
Closing as there's no reproduction project to debug with. If anyone still experiences this issue, please upload the project so that we can investigate what might be missing compatibility-wise.

**Closed by akien-mga** 2020-12-10 15:43 UTC
Labels: topic:mono
