### ISSUE TITLE
[3.2.1] Mouse clicks not registering if click happened outside button

### ISSUE THREAD

**Issue by DoctorWhoof** [godotengine/godot#38126] opened 2020-04-23 04:33 UTC
**Godot version:**
3.2.1.stable.oficial

**OS/device including version:**
MacOS 10.15.4 and Windows 10

**Issue description:**
I'm trying to create an UI where the user can click on a button, then DRAG the mouse over the neighbor buttons, without releasing the left button, to toggle their state.

However, it only works for me on Windows and MacOS if I drag the mouse OUT of the window, then back into it. A user on Linux has reported that it works as expected.

My minimal repro script stores the state of mouse clicks, then uses an "_on_mouse_entered" signal to print a message, but only if the user has already clicked and is dragging.

**Steps to reproduce:**
Run the minimal project attached. CLICK on a button, and without releasing the left mouse button, DRAG over the neighbor buttons. You should see the "button is drag-pressed!" message printed for each button.

**Minimal reproduction project:**
[Drag-Click Test.zip](https://github.com/godotengine/godot/files/4520233/Drag-Click.Test.zip)

**Comment by swenner** [comment] 2020-04-24 16:13
I can confirm that it is also broken on Debian GNU/Linux (Gnome) with Godot 3.2.2beta. You have to move the mouse outside of the window to get the mouse entered event. Could be related to https://github.com/godotengine/godot/issues/20881

**Comment by DoctorWhoof** [comment] 2020-04-24 22:22
It definitely seems related to #20881. I did some more testing, and the individual buttons can register the "click" just fine when it happens outside their rect (I added a "print"statement to verify it). It's the mouse_enter event that seems to not be working as expected, as far as I can tell. Thanks!

And just in case someone is wondering why this is useful, you can use buttons that behave like that to:
- Mass toggle the state multiple items, like the Layers in Photoshop, without RSI inducing click-click-clicking on each one
- Play a sound for each key on a piano roll without releasing the mouse button
- Make "toddler friendly" UI's (click dragging can be easier than multiple clicks in some situations) in apps for kids, etc.

Thanks!

**Comment by Calinou** [comment] 2021-03-28 14:04
Duplicate of https://github.com/godotengine/godot/issues/20881 (same cause).

**Closed by Calinou** 2021-03-28 14:04 UTC
Labels: bug, topic:gui
