### ISSUE TITLE
MultiMesh InstanceCount 1 not working

### ISSUE THREAD

**Issue by DarioDaF** [godotengine/godot#75833] opened 2023-04-08 17:38 UTC
### Godot version

4.0.2.stable

### System information

Windows 11

### Issue description

MultiMeshInstance2D MultiMesh does not work in the editor and in game with InstanceCount 1
Doesn't work well in the editor, but works fine in game if InstanceCount is > 1

### Steps to reproduce

1) Put a MultiMeshInstance2D in the scene, set godot icon texture and mesh to be default quad with 64x64 size.
2) Increase instance count to 1 and try putting the data in buffer (since buffer it's not documented an alternative in the next step)
3) Add to the object this ready script
```gdscript
func _ready():
	multimesh.instance_count = 1
	for i in range(multimesh.instance_count):
		self.multimesh.set_instance_transform_2d(i, Transform2D(0, Vector2(i * 64, 0)))
```

![image](https://user-images.githubusercontent.com/10617344/230735323-d9ee0d7d-e904-4918-badd-6328344a4f8a.png)
Result with identity matrix

### Minimal reproduction project

N/A

**Comment by Calinou** [comment] 2023-04-08 17:44
- Related to https://github.com/godotengine/godot/issues/75485 and https://github.com/godotengine/godot/issues/56357.

**Comment by clayjohn** [comment] 2023-04-11 18:39
I can't reproduce. When I run the scene the single instance is drawn at (0,0). I tested with 4.0.2-stable and on PopOS 22.04. 

![Screenshot from 2023-04-11 11-36-01](https://user-images.githubusercontent.com/16521339/231257794-22034654-ebe3-4050-9d00-cbc57145436a.png)

Are you sure that you are using an appropriately sized quad? You could be getting this sort of issue if you use a quad shaped mesh that isn't intended for 2D, or one that is otherwise malformed. 

By the way, an MRP would be helpful here so that other contributors can see exactly what your scene setup is that is leading to this wrong result

**Comment by DarioDaF** [comment] 2023-04-11 22:02
Will provide a MRP soon, in the meantime testing seems like it happens only with compatibility renderer

**Comment by DarioDaF** [comment] 2023-04-11 22:09
[MRP_MultiMeshBug.zip](https://github.com/godotengine/godot/files/11205328/MRP_MultiMeshBug.zip)

Here the MRP, also one thing seems off to me seeing the output on PopOS you posted:
Is the mesh reversed? Because with the working renderers (or multiple instances) the default quad (gerenated by simply pressing new quad) is oriented upside down (as expected being a Z 3D mesh aka positive X and positive Y); I expect the same to be true for linux...

**Comment by clayjohn** [comment] 2023-04-11 23:42
> Will provide a MRP soon, in the meantime testing seems like it happens only with compatibility renderer

In that case, this is likely a duplicate of https://github.com/godotengine/godot/issues/75747

**Closed** 2023-04-12 07:08 UTC
Labels: bug, topic:rendering, confirmed, needs testing, topic:2d
