### ISSUE TITLE
[4.0 RC1 & RC2] TouchScreenButton BUG

### ISSUE THREAD

**Issue by MASoftware-es** [godotengine/godot#73520] opened 2023-02-17 19:56 UTC
### Godot version

4.0 RC1 & RC2

### System information

Linux Ubuntu

### Issue description

TouchScreenButtons have stopped working in version RC1 and RC2.
The same single project working in Beta 17, fails in RC1 and RC2.

### Steps to reproduce

We just run the project and clicking on the TouchScreenButton doesn't work.

### Minimal reproduction project

Attached very simple project where the failure occurs.

[touch-test.zip](https://github.com/godotengine/godot/files/10771159/touch-test.zip)

**Comment by YuriSizov** [comment] 2023-02-17 20:19
Duplicate of https://github.com/godotengine/godot/issues/73457, fixed by https://github.com/godotengine/godot/pull/73470.

**Closed by YuriSizov** 2023-02-17 20:19 UTC
