### ISSUE TITLE
Glitchy/unresponsive UI when resizing the window

### ISSUE THREAD

**Issue by hiulit** [godotengine/godot#59746] opened 2022-03-31 15:30 UTC
### Godot version

v3.5.beta.3.official

### System information

macOS BigSur (11.16.2) - OpenGL ES 2.0 Renderer: Intel Iris Pro OpenGL Engine 

### Issue description

When resizing the window, everything gets glitchy/unresponsive.

Here's a video showing first 3.5.beta3 and then 3.4.4 (which works fine).

If it may be relevant, I was using @Wcubed's [HFlowContainer](https://github.com/Wcubed/horizontal_flow_container), but now I've switched to the official HFlowContainer on 3.5. The issue is present using any of them.

https://user-images.githubusercontent.com/481475/161091200-8bfa772e-fbc4-4b19-8526-c10ba5faa2c2.mp4

### Steps to reproduce

Open the project, run it and resize the window.

### Minimal reproduction project

You can use the [Lospec Palette List](https://github.com/hiulit/Lospec-Palette-List) (`develop` branch to test 3.5.beta.3 and `1.x` branch to test 3.4.4) as reference, which is what I show in the video.

**Comment by hiulit** [comment] 2022-03-31 16:04
I'll try to test it on my Ubuntu and Windows machines, but it seems likely that it could be related to the HiDPI resolution.

**Comment by theraot** [comment] 2022-03-31 16:12
In Windows 10, they both look the same to me. I don't see the shaking behavior I observe in the OP video.

*I'll mention that on Windows 10 black bars appear momentarily while resizing (in other words it takes a frame to draw the new areas). This is what Windows 10 does for both version, and for my projects too, even 3D.*

**Comment by hiulit** [comment] 2022-03-31 19:46
I've tested on Windows 10 and it seems to work fine. It must a macOS thing :)

**Comment by hiulit** [comment] 2022-03-31 20:48
> I'll mention that on Windows 10 black bars appear momentarily while resizing (in other words it takes a frame to draw the new areas). This is what Windows 10 does for both version, and for my projects too, even 3D.

It happens to me, too.

**Comment by hiulit** [comment] 2022-04-01 09:13
It seems like the issue is only present on macOs.

I've tried to reset to the defaults the only values I changed for this project, which are:

- `run/low_processor_mode=true` (default `false`)
- `window/dpi/allow_hidpi=true` (default `false`)
- `quality/driver/driver_name="GLES2"` (default `GLES3`)

And the issue persists.

**Comment by akien-mga** [comment] 2022-04-01 09:18
Do you get the issue on a 1080p monitor / if you switch your Retina display to 1080p (if that's possible)?

**Comment by hiulit** [comment] 2022-04-01 09:33
Yes, I've scaled my Retina display to 1920x1200

```
print(OS.get_screen_dpi())
# 295
print(OS.get_screen_scale())
# 1
print(OS.get_screen_size())
# (1920, 1200)
```

and the 1080p external monitor:

```
print(OS.get_screen_dpi())
# 83
print(OS.get_screen_scale())
# 1
print(OS.get_screen_size())
# (1920, 1080)
```

and I've enabled and disabled `allow_hidpi` and it stills happens.

**Comment by hiulit** [comment] 2022-04-01 11:23
I've removed my own Theme and the Container with the HFlowContainers and it still happens

https://user-images.githubusercontent.com/481475/161253301-5558ee63-3479-4196-a169-6a732b840d85.mp4

**Comment by theraot** [comment] 2022-04-01 11:33
I think that what mac is doing is scaling the image. That is, when the window resized but the new area is not yet drawn, mac draws the old image but scaled. If it didn't scale it, it would be similar to Windows 10 black bars.

**Comment by Calinou** [comment] 2022-04-01 17:51
> I think that what mac is doing is scaling the image. That is, when the window resized but the new area is not yet drawn, mac draws the old image but scaled. If it didn't scale it, it would be similar to Windows 10 black bars.

This is probably what it's doing. I don't think we can do anything about it.

**Comment by hiulit** [comment] 2022-04-01 17:52
@Calinou but this is something new in 3.5, it doesn't happened in 3.4

**Comment by hiulit** [comment] 2022-04-01 18:52
For the record, the issue is present on the 3 betas.

**Comment by hiulit** [comment] 2022-04-01 19:54
Just to discard everything, I've created a new project [test godot.zip](https://github.com/godotengine/godot/files/8400569/test.godot.zip)
 
## 3.3.4

https://user-images.githubusercontent.com/481475/161332498-32ee505a-90fb-4043-83f4-05878179d35e.mp4

## 3.5.beta.3

https://user-images.githubusercontent.com/481475/161332530-7d7e0530-45bc-4315-be03-f02356e67a35.mp4

**Comment by theraot** [comment] 2022-04-01 20:16
@bruvzg

**Comment by theraot** [comment] 2022-04-01 20:21
@hiulit Does it happen to the Godot window itself?

**Comment by hiulit** [comment] 2022-04-01 22:50
@theraot I didn't thought about that! And yeah, it happens to the Godot editor as well.

https://user-images.githubusercontent.com/481475/161351729-42843d01-cac7-42a0-840c-53e3d11a5f0f.mp4

**Comment by bruvzg** [comment] 2022-04-04 05:14
While I can reproduce it, when resizing window fast, the same happens in 3.4.4 and any older version I have tested (at least up to 3.0). I can't see any difference.

It probably will need implementing a custom backing layer, and changing the way main loop works to fix it (it's a lot of changes, so probably unfeasible for 3.x).

**Comment by hiulit** [comment] 2022-04-04 08:19
This is definitely not happening on 3.4.4. You can see in my first video that even when resizing slowly it gets weird on 3.5.beta.3 and it doesn't happen on 3.4.4.

Here's more videos showing the differences:

## Showly

### 3.4.4

https://user-images.githubusercontent.com/481475/161502803-32f7e96e-7b97-4ed6-823e-869d7583ae20.mp4

### 3.5.beta.3

https://user-images.githubusercontent.com/481475/161502816-0aca68f1-4b87-4c31-b307-4610e1bcedfb.mp4

## Quickly

### 3.4.4

https://user-images.githubusercontent.com/481475/161502826-006beb08-7156-46dc-be53-3c4c0d1de0fc.mp4

### 3.5.beta.3

https://user-images.githubusercontent.com/481475/161502836-9c0be470-7655-42c2-90ff-1f0b7a261768.mp4

**Comment by hiulit** [comment] 2022-04-04 11:23
Ok, so I've compiled Godot `3.x` branch reverting this particulpar commit https://github.com/godotengine/godot/commit/f997a5f8f6e51db47ca6ecfc11923847ed464094 and it seems like this is what is causing the issue.

## Custom compile (3.x without the commit)

https://user-images.githubusercontent.com/481475/161532688-e891caba-49b0-4092-aaf1-3d935ccf7831.mp4

## 3.5.beta.3

https://user-images.githubusercontent.com/481475/161532716-52421a1b-a30d-4096-b466-1afd70f50b5d.mp4

I think we can safely say there's a big different between the two, right?
I admit that sometimes there are slightly rendering issues on 3.4.4, but they are negligible. I actually never noticed them until now, with all these tests, hehe!

**Comment by filipworksdev** [comment] 2022-06-03 19:32
I tested this on Windows 10 I don't see the issue. It has to be a mac specific issue. Very likely not the issue but just to be thorough does this still happen without any text at all? Text has always been buggy for me especially when using font oversampling true as it scales fonts at specific sizes pushing controls around.

**Comment by hiulit** [comment] 2022-06-07 12:53
I don't have the technical knowledge, but from an end-user point of view, it looks way worse now than before.

At some point, this was introduced https://github.com/godotengine/godot/commit/f997a5f8f6e51db47ca6ecfc11923847ed464094 (which seems to be the "issue"), so I'm guessing something can be done to, at least, find a middle ground.

In 3.4.4, for me, it was working ok. A little bit of lag when resizing the window? Sure, but it was minimal, never noticed before. But at least the content of the window wasn't going bonkers, hehe! Now we have a more responsive window when resizing but the content looks terrible. I don't think the content should be stretching when resizing. Does it look good to you?

**Comment by akien-mga** [comment] 2022-06-10 09:09
@hiulit What are your Mac and GPU models exactly?

**Comment by hiulit** [comment] 2022-06-10 09:31
@akien-mga MacBook Pro (Retina, 15-inch, Mid 2015)- Intel Iris Pro 1536 MB running on  macOS BigSur (11.16.2)  and I'm using OpenGL ES 2.0 Renderer

**Comment by bruvzg** [comment] 2022-06-10 10:54
For me, it's hard to reproduce, but I think I have found what's wrong, will try to fix it in a moment.

**Comment by akien-mga** [comment] 2022-06-10 12:26
Fixed by #61895.

I assume the fix needs to be forward ported to `master` too?

**Closed by akien-mga** 2022-06-10 12:26 UTC
Labels: bug, regression, topic:gui

**Comment by Osirisa** [comment] 2024-12-06 16:20
why is this closed? it still happens

on both of my windows machines
Laptop with RTX2000 and RTX4090
Godot 4.2.2 / Godot 4.3

when resizing, the UI wobbles back and forth

Windows 10 / Windows 11

**Comment by theraot** [comment] 2024-12-06 17:54
Why was this closed? Because this issue was for Godot 3.x, and as far as I can tell it is solved there.

With that said, now that you bring attention to it, I've compared Godot 3.x and Godot 4.x resize side by side, Godot 3.x is much more smooth. I don't think it is as pronounced as it was in Godot 3.x, at least it didn't bother me.

It seems the counterpart of the fix for the master branch didn't happen. Or at least I can't find it.

*I notices something else while testing: If Godot 3 is in the background I can click on the border (which gives it focus) and start resizing right away. That works in 4.2.2 but not in 4.3. Godot 4.3 gets focus but I have to release and click again to resize. That seems to be a change on handling out of focus mouse input.*

**Comment by Calinou** [comment] 2024-12-10 17:34
Please continue the discussion in https://github.com/godotengine/godot/issues/84972.

**Comment by theraot** [comment] 2024-12-10 17:46
That does not seem right. Under the assumption that you linked the wrong issue, I searched for one, and this seem to be it:

- https://github.com/godotengine/godot/issues/99072

**Comment by Osirisa** [comment] 2024-12-10 17:52
This doesn't seem like it's the same, as the problem im facing

The videos above are exactly what I'm experiencing

**Comment by theraot** [comment] 2024-12-10 17:54
@Osirisa I think we get out of this if you open a new issue.

**Comment by Osirisa** [comment] 2024-12-10 17:55
Yeah ill do it later

**Comment by Calinou** [comment] 2024-12-11 09:02
I meant to link to https://github.com/godotengine/godot/issues/39222. Sorry for KDE's clipboard being this unreliable (it's been the case for years) 🙁
