### ISSUE TITLE
issues and suggestions for the editor

### ISSUE THREAD

**Issue by draxdeveloper** [godotengine/godot#2152] opened 2015-06-22 20:28 UTC
There some issues and suggestions with the most recent changes into the editor, since the update between scenes was talked in another issue, i will focus here in the docking.

urgent stuff(so i think):
* If i try to dock 3 or more elements in the same docking area(like putting scenes,resources and filesystem) i cant acess all 3 because the arrows that change the tabs are not working.

* Not related to the editor, but the article in the wiki about gdscript have text issues, like this one:
https://github.com/okamstudio/godot/wiki/gdscript
"Any string that restricts itself to alphabetic characters (â€™aâ€™ to â€™zâ€™ and â€™Aâ€™ to â€™Zâ€™), digits (â€™0â€™ to â€™9â€™) and â€™_â€™ qualifies as an identifier. Additionally, identifiers must not begin with a digit. Identifiers are case-sensitive (â€™fooâ€™ is different to â€™FOOâ€™)."

not so urgent stuff(so i think):
* Its seems that you have created 4 docking areas in each side of the main area, it would be good if there was more docking areas (in the top and bottom parts), also, it would be nice if we could move the main area directly.
* Would be nice if we could undock the tabs of 2d,3d,Script and help, also we could undock (and dock in other docking are) the output.
* Speaking of it, it would be nice if we could just close all those dockable elements (so if i think i will not use the 3d in a project, i could just close it and reopen it later)
* Since now editor is becoming more configurable, we could have editor profiles. So i could use a profile more suited to using the script while i am caring the code area and another more suited to edit the nodes when i am caring about the more visual area.
* Also, some elements (not all of then) could be undocked to a external window. (for example, the Script that is kind of independent of the rest). So we can see the two at same time if we have two screens or simple use alt+tab. (another good example to this would be the output, that would work greatly in two screens... man i need two screens :( )

**Comment by mamarilmanson** [comment] 2015-06-23 01:06
:+1

**Comment by akien-mga** [comment] 2015-11-11 13:15
The first point is no longer relevant I think (also a duplicate of #2404), and the second point has been fixed. For the rest, please open a dedicated issue for each point that is still relevant (check for existing issues first).

Such a "list of points" issue is not so practical to work with, each ticket should refer to only one problem.

**Closed by akien-mga** 2015-11-11 13:15 UTC
Labels: archived
