### ISSUE TITLE
Tileset sorting wrong after 9th tile

### ISSUE THREAD

**Issue by keremcaliskan7** [godotengine/godot#34783] opened 2020-01-03 14:32 UTC
**Godot version:** 3.2.beta4
**Godot version:** 3.2.rc4.official

**OS/device including version:** (Probably Any) (Found On: GNU\Linux\Manjaro KDE x86_64)

**Issue description:** Godot sorts tiles correct to the 9th tile. After you add 10th tile Godot puts it after 1st tile. For example: 1, 10, 11, 12, 2, 3, 4, 5, 6, 7, 8, 9.

**Steps to reproduce:** Create a TileMap node. From Inspector menu, select "New TileSet" as Tile Set. Then select an image that includes at least 10 tiles. Add at least 10 tiles using "New Single Tile" button.

**Minimal reproduction project:**
[Sorting.zip](https://github.com/godotengine/godot/files/4019413/Sorting.zip)

**Screenshot.**
![Screenshot_20200103_171242](https://user-images.githubusercontent.com/22561566/71728371-f53d0d80-2e4d-11ea-87ae-fcdec1bcd1df.png)

**Comment by qarmin** [comment] 2020-01-03 17:07
Probably here
https://github.com/godotengine/godot/blob/a7f49ac9a107820a62677ee3fb49d38982a25165/scene/gui/item_list.cpp#L1316-L1322
`items.sort()` should be changed `items.sort_custom<NaturalNoCaseComparator>();`, but I don't have machine to check if it work

**Comment by Janglee123** [comment] 2020-01-03 17:09
I think its not a bug, its how it works.
You can use leading zero to solve it. i.e. 01, 02, 03, 04, 05, 06, 07, 08, 09, 10, 11, 12

**Comment by name-here** [comment] 2020-01-03 22:26
Is there any reason that items.sort() wouldn't sort these in the right order?  Wouldn't you usually want, for example "A" to come before "AB" when sorted?

**Comment by Pleto** [comment] 2020-01-03 22:51
1 comes before 10, so it sorts in the right order (lexicographically).

This seems to be an easy fix (suited for a junior). Can I be assigned to work on it?

**Comment by name-here** [comment] 2020-01-05 00:54
Sorry.  What I meant to say was that something like "B" should come before "AA", as in (most?) alphabetical sorting, where items are sorted first by length of the name, and then by the content of it.  So 1 should come before 10 (as it does), but 2 should come before 10 too (as it doesn't).  Would that be too complicated/slow for the standard sort function?

**Comment by ntovas** [comment] 2020-01-25 16:49
Is this issue still open? I could work on that.

**Comment by Pleto** [comment] 2020-01-25 21:42
I had to learn for a hard exam for the past days and did not find time to solve this issue. I will start working on it tomorrow

**Comment by keremcaliskan7** [comment] 2020-01-27 15:47
Yes. It's open. Tested again on: 3.2.rc4

**Comment by namedtoaster** [comment] 2020-02-24 16:51
I am using the master branch and don't seem to have this bug (see screenshot).

<img width="765" alt="Screen Shot 2020-02-24 at 9 46 44 AM" src="https://user-images.githubusercontent.com/13757806/75172857-2b2e9d80-56eb-11ea-80b0-56fed6492029.png">

 I know it's obviously a different source but based on @qarmin's response, it should maybe have the same behavior? I am new to open-source contributing so I'd like to look into this, but do I need to clone the 3.2 branch to be able to test this?

**Comment by namtran166** [comment] 2020-03-02 18:15
Based on how Array.sort() works in Godot, I believe strings are sorted in alphabetical order, not in natural order. Therefore, when we attempt to sort ["Tile1", "Tile2", "Tile10", "Tile11"], the result would be ["Tile1", "Tile10", "Tile11", "Tile2"], thus leading to this unexpected behavior. I am not sure if this change is necessary, but if you can take a look at here:
https://github.com/godotengine/godot/blob/0c22f5a4476d80b43017b2032f60039ce75e49a9/core/sort_array.h#L318-L321
@Calinou Can you confirm this, since I believe you mentioned this on https://github.com/godotengine/godot/pull/35801?

**Comment by Calinou** [comment] 2020-03-02 20:11
@namtran166 Indeed, this is expected behavior. Someone opened a pull request to fix the TileSet sorting in https://github.com/godotengine/godot/pull/35943.

**Comment by harshbawari** [comment] 2020-03-05 06:54
I would like to work on this issue if others haven't already solved it.

**Comment by Calinou** [comment] 2020-03-05 10:49
@harshbawari Thanks for your interest in contributing :slightly_smiling_face: 

Someone already opened a pull request to solve it: #35943

**Comment by abhinav4987** [comment] 2020-07-03 14:34
is this issue open?
And if not, can you suggest some other junior job issues/ or any, cause I am completely new and clueless.
its cool otherwise too.

**Comment by Calinou** [comment] 2020-07-03 14:38
@abhinav4987 There's already an open pull request to fix this: https://github.com/godotengine/godot/pull/36025

**Comment by abhinav4987** [comment] 2020-07-03 14:48
@Calinou okay

**Closed** 2020-10-26 07:10 UTC
Labels: enhancement, hacktoberfest, topic:editor
