### ISSUE TITLE
Bootsplash appears twice.

### ISSUE THREAD

**Issue by NightBreather** [godotengine/godot#43726] opened 2020-11-20 15:28 UTC
**Godot version:**

3.2.4 Beta 2

**OS/device including version:**

Android 7.0 

**Issue description:**

Hello guys

I am having a problem using the bootsplash feature. İt appears twice while the application is running that png file I was added.The splash that first appears looks quite normal but it appears strangely that second splash

I don't have this problem constantly. It just happens sometimes

**Steps to reproduce:**

**Minimal reproduction project:**

The source code I used to try 👍

https://s4.dosya.tc/server12/nwqmh5/circle_jump-master.rar.html

I'm using a png logo in here

**Comment by NightBreather** [comment] 2020-11-20 15:30
I forgot to add . I don't have this problem constantly. It just happens sometimes.

**Comment by nathanfranke** [comment] 2020-11-20 19:10
For Minimal Reproduction Projects, please use GitHub's built-in file uploading system. For files larger than 10MB, please use a reliable, English website. Also, while `rar` is fine for most intents and purposes, it is customary to use `zip` files due to their widespread support.

Here is the MRP re-uploaded to GitHub in case the site OP used is unavailable.
[circle_jump-master.zip](https://github.com/godotengine/godot/files/5575575/circle_jump-master.zip)

**Comment by NightBreather** [comment] 2020-11-20 20:23
> For Minimal Reproduction Projects, please use GitHub's built-in file uploading system. For files larger than 10MB, please use a reliable, English website. Also, while `rar` is fine for most intents and purposes, it is customary to use `zip` files due to their widespread support.
> 
> Here is the MRP re-uploaded to GitHub in case the site OP used is unavailable.
> [circle_jump-master.zip](https://github.com/godotengine/godot/files/5575575/circle_jump-master.zip)
> 

i am new in github.Sorry for that

**Comment by ozzr** [comment] 2020-11-25 00:08
I am getting the same issue. But the first bootsplash appears bigger than the second one, the time they stay on screen varies, 
![Screenshot_20201124-190704_Light Terrain](https://user-images.githubusercontent.com/36895302/100165510-6e8b8780-2e88-11eb-9511-579268c7f58f.jpg)
![Screenshot_20201124-190740_Light Terrain](https://user-images.githubusercontent.com/36895302/100165531-79deb300-2e88-11eb-8970-48ed140a2f2c.jpg)

**Comment by Calinou** [comment] 2020-11-25 00:20
@ozzr Which device and OS version did you test this on?

**Comment by ozzr** [comment] 2020-11-25 00:49
The device: Samsung Note 10, android 10. But, sorry, it only happens with the default splash image. I used a custom splash screen and it doesn't do it anymore.

**Comment by NightBreather** [comment] 2020-11-27 05:17
> The device: Samsung Note 10, android 10. But, sorry, it only happens with the default splash image. I used a custom splash screen and it doesn't do it anymore. 

I used special splash too but it still happens

**Comment by wombatwingdings** [comment] 2020-12-03 19:37
I get exactly the same issue after recent pull & build. Boot splash appears big then small. Doesn't always happen. Using default "Godot" splash screen. Phone is Motorola G6 Play.

**Comment by alexzheng** [comment] 2020-12-24 03:32
I use a custom splash, the image is also scaled to very big.

**Comment by mbrlabs** [comment] 2020-12-24 22:34
Same here with default splash screen on Android 10. It also happens in `beta1`. Probably a regression from #42389. cc @m4gr3d

**Comment by mbrlabs** [comment] 2020-12-24 23:24
I managed to capture this on an emulator running Android 10:

![splash_bug](https://user-images.githubusercontent.com/8750135/103109359-5786b380-4647-11eb-8a0f-b11e724c6915.gif)

**Comment by bluebarnacles** [comment] 2021-01-11 09:29
I was able to reproduce this on Android (Pixel 4a) with v3.2.4 beta5:

https://user-images.githubusercontent.com/5144579/104164180-6641ca00-53ac-11eb-8354-8c6c8e39c841.mp4

**Comment by floppyhammer** [comment] 2021-01-31 05:53
This issue still exists with 3.2.4 rc1. The splash first appears scaled up then appears again with normal size.

**Comment by Calinou** [comment] 2021-01-31 17:20
@floppyhammer Can you (or anyone else) reproduce this on 3.2.3 or earlier versions?

**Comment by bluebarnacles** [comment] 2021-02-01 02:20
@Calinou This issue didn't occur in 3.2.3 or earlier versions, on Android exports in those versions the screen was blank for several seconds while the engine and resources were loading, then the boot splash was displayed for a split second before changing to the main scene.
91a1e4c9ee (PR #42389, first released in 3.2.4-beta1) introduced earlier display of the boot splash, but it's shown with a different resolution at that point than the version shown after the engine loads.

**Comment by Calinou** [comment] 2021-02-01 15:23
cc @m4gr3d

**Comment by m4gr3d** [comment] 2021-02-18 06:56
Sorry for the delay in responding, I can provide an update about the current behavior and the available options to address the feedback in this issue.

PR #42389 was added to resolve #21824 which was causing the splash image to not show reliably.

As mentioned in the description, this is done by leveraging the Android theme api. This is different from the previous logic which used the engine itself, and it guarantees the splash image will always show on the first frame of the app starting.
Because of the difference however, the splash image is not treated the same way resulting in the difference in scale you're seeing. In addition, the previous logic was not disabled in PR #42389 causing it to attempt to render the splash image once the engine is initialized, but as observed in #21824 and here as well, this second splash render is inconsistent.

Based on the feedback in this thread, two additional tasks are necessary to fully resolve splash handling on Android:

1. Disable the previous logic (based on the engine) on Android - Only the new Android theme logic will then be active which would prevent the splash from showing up twice.
2. Update the logic which handles the splash images for Android so as to allow them to keep the same scale as with the previous logic - This may be tricky to do as the Android theme api is limited, but this would allow end users to use the same splash images across multiple platforms and expect the same result.

**Comment by m4gr3d** [comment] 2021-02-18 11:40
I've addressed task **1** and **2** described in the above comment in PR #46169 and PR #46168.

One limitation of the new api however is that enabling `fullsize` on the splash screen in the project settings doesn't respect the splash screen aspect ratio on Android (e.g: the image is stretched out both horizontally and vertically to fill its container).
Feel free to provide feedback on the PRs.

**Closed** 2021-02-18 12:37 UTC
Labels: bug, confirmed, platform:android, topic:porting
