### ISSUE TITLE
macOS - "Shake mouse pointer to locate" cannot be disabled

### ISSUE THREAD

**Issue by drmar** [godotengine/godot#27955] opened 2019-04-12 12:49 UTC
**Godot version: Godot 3.1**

**OS/device including version: macOS Mojave 10.14.4 / MacBookPro11,1; GPU: Intel Iris 5100**

**Issue description: Since macOS 10.11, Apple introduced a functionality called "Shake mouse pointer to locate". Basically, whenever you move the mouse cursor quickly, it gets really large, so you can see where it is. The problem is that this functionality kicks in inside games developed with Godot. So, in my case, I am developing a point and click game and I have custom cursors, but I inevitably move the mouse around the screen quickly enough every now and again and the functionality kicks in, turning my custom cursor into the standard macOS on and it makes it very big for a second or two. I am not sure if this qualifies as a bug, technically, but it sure does kills the mood in the game and it is quite frankly annoying. Also, there are probably some game genres which might not be playable at all because of this functionality, games that rely on the cursor to be a very precise input method. The solution that I am interested in? Either disable this functionality in macOS as a Godot standard feature, or make it possible to disable it from Godot, from code or from Settings. **

**Steps to reproduce: There are no steps to reproduce, as far as I know. The bug is already in Godot as standard. Also, I have attached the whole project so it can be tested. **

**Minimal reproduction project: 
[The Party_Godot 3.1_macOS_v2.zip](https://github.com/godotengine/godot/files/3073290/The.Party_Godot.3.1_macOS_v2.zip)
**

**Comment by ConnorBP** [comment] 2019-04-12 13:15
I can't seem to find anything on disabling that feature of macos in code, but I assume the method of "fixing" this is to hide the cursor entirely and only draw the custom cursor. I am surprised that this happens with your custom cursors. I wonder if anyone could clarify if  Godot applies custom cursors into the system mouse somehow?

**Comment by bruvzg** [comment] 2019-04-12 15:20
Godot sets custom cursor image to the system cursor (this way is more responsive than drawing cursor manually, cursor and mouse position is always perfectly in sync), and catches `cursorUpdate` and `mouseEntered` events to reset it back to custom after system or other app changes cursor. AFAIK "Shake mouse pointer to locate" feature is not sending `cursorUpdate` events (or any other) and there's no way to detect when it triggers.

**Comment by drmar** [comment] 2019-04-12 16:05
I wish I could help, guys, but this problem is way beyond my technical knowledge.
All I know is that, as small as this problem seems, it can really make an already indie game look even more indie and unpolished. Having that gigantic standard system arrow pop up (possibly) every few seconds when playing a game, like a point and click, does not necessarily make the game unplayable, per se, but it sure nothing to keep the player immersed in the atmosphere of the game.

Also, and this is just my personal opinion, being a beginner and a newcomer to Godot (played around with Unity a bit before this), I really think that small problems like this can decide a developer to explore other options on the market, as far as game engine goes. I personally love Godot and I am trying to support it any way I can, hence this bug report.

Anyway, until someone fixes the problem properly in a future version of Godot, can anybody think of a solution to this problem suitable for a point and click game?

Thanks!

**Comment by Calinou** [comment] 2019-04-12 16:12
@drmar Have other engines solved this problem without resorting to software cursors (which suffer from higher latency)?

**Comment by drmar** [comment] 2019-04-12 16:19
@Calinou Again, I really a beginner programmer and I just recently started working with Godot. The engine got my attention when it reached version 3.1. 

I wish I could have a deeper understanding of this problem so maybe I can help solve it, but truth be told, all that I am capable of right is just reporting bugs when I see them.

I don't mean to question the design decisions behind Godot engine, first and foremost because I don't understand them technically, so I hope no one gets offended for sharing my opinions and making suggestions, to the extent that I am able to.

All I am really interested right now is finding out if there is a viable workaround for this particular problem, suitable for a point and click game. I am sure that in the future this problem will be properly addressed in Godot, especially since I cannot be the only one in the world that is facing this issue.

**Comment by bruvzg** [comment] 2019-04-12 16:28
This is not a bug, cursor is restored back to custom one after shake is finished (if in some cases it's not, this is a bug), so it won't break games that rely on the custom cursor image.

Personally I don't understand what's the problem is, "shake mouse pointer to locate" is accessibility option, if users have enabled it they probably want it for some reason and your app should not interfere with it.

**Comment by drmar** [comment] 2019-04-12 16:33
@bruvzg Please note that I only reported this bug here because @Calinou asked me to, on Godot Facebook group.

I already explained what the problem is, several times in fact, and people seem to keep being hostile about it, for some reason.

If this is the general attitude of the Godot community, them I am sorry for offending you feelings by reporting a genuine problem that can be very easily reproducible by anyone with a recent macOS.

But I understand the general idea. Reporting bugs, problems, whatever you want to call them seems to be a mistake in this engine's community. My bad! It won't happen again. Good luck!

**Comment by nazgulsenpai** [comment] 2019-04-12 17:48
No one is suggesting that you shouldn't have reported this, they're simply stating that isn't a bug and, in my opinion, doing it quite politely. While the community is directly involved in this forum, it's primary purpose is for finding, understanding and eliminating bugs. The mistake here is taking anything posted in an issue report personally.

**Comment by drmar** [comment] 2019-04-12 18:02
@nazgulsenpai Thank you for your answer! 

Firstly, please let me state it again. I wouldn't have reported this problem as a bug on Github if it wouldn't have been suggested to me by @Calinou, on Godot's Facebook group.

I actually understand that it is not a bug, in the classic sense of the word, but it is, in my own opinion, which I am trying to make it as objectively as possible, a real-world problem for some type of games.

What really put me off is that I have explained several times, both on Facebook and on Github what the issue is and some people keep asking me again and again "what is the problem?". I am not sure how many more ways I can explain the problem.

Bottom line, whenever you are playing a game, be it indie or triple A, you simply don't want the player to have to stare at a big black arrow on the screen every few seconds. Am I being absurd here? Because I really think I'm not.

Moreover, back on Facebook, some people in the Godot community seem to be really condescending and even aggressive with their responses as well. What did I do wrong? I am honestly, honestly just trying to help Godot become a better game engine by bringing to the developers attention the problems that I personally discover.

I don't know, maybe some sort of confrontation or hostility is to be expected in any online community, but when you are genuinely trying to help and people tell you that they are "disturbed" (as someone put it on Facebook) by my bug report, well... how would that make you feel? 

Anyway, I hope this bug report is of some help to the engine and the community as a whole.

**Comment by bruvzg** [comment] 2019-04-12 18:32
@drmar As a workaround you can use "software cursor", hide system cursor by using `Input.set_mouse_mode(Input.MOUSE_MODE_HIDDEN)` and draw your own cursor sprite, this method should not be affected by "shake to locate", but it increases input lag a bit (many games use software cursor, so it's a viable option).

No one intended to be hostile, my points were:

1. If you do not need or like "shake to locate" feature, why do you have it enabled? You can always disable it in macOS `System Preferences`->`Accessibility`.

2. If someone keeps it enabled, it probably is for the reason, some people may have vision problems that makes it hard to see mouse cursor, and they actually want big contrast arrow to appear. Windows have similar feature as well (blinking inverted colour circle appearing around the cursor). Accessibility is more importation than game aesthetics. In general, it's [considered good idea](http://gameaccessibilityguidelines.com/provide-a-choice-of-cursor-crosshair-colours-designs/) to allow uses to use system cursor if they want to, instead of forcing them to play your game in the way you designed it.

3. To the extent of my knowledge it is not possible to change "shake to locate" behaviour for a specific app anyway.

**Comment by drmar** [comment] 2019-04-12 19:02
@bruvzg Thank you very much for your solution! This is exactly what I was looking for.

Regarding the larger issue, I do understand the importance of Accessibility features for those people who need it. However, Apple seems to have implemented this feature in the OS by default. While I certainly want all people to play my (potential) games, including people who need accessibility features, I would prefer them to be included in my games as an option, not as standard. Is this immoral? I don't know, it's to anyone to judge, but all the games that I ever played never had the cursor become a giant black arrow in the middle of the screen ever time I moved the mouse too quickly. I guess it is just a matter of personal preference. I would like my game resemble, more or less, the point and click games that I am used to and grew up with. Also, having options in the engine itself is never a bad thing, in my opinion. Some people may chose to leave the accessibility feature son by default, some people don't, but having a choice can only make the Godot engine so much better and feature rich, in my opinion.

Again, thank you everyone for your responses and I am sorry if I overreacted, but I was already in a bad mood by the vibe of Godot Facebook group.

Cheers!

**Comment by akien-mga** [comment] 2019-04-15 08:33
Closing as it was established that it's a macOS feature that we have no control over, so it's not a Godot issue.

**Closed by akien-mga** 2019-04-15 08:33 UTC
Labels: discussion, platform:osx, usability

**Comment by natbro** [comment] 2021-04-24 01:47
a little bit late the question, but the `NSApplicationPresentationOptions` flag can be adjusted with `NSApplicationPresentationOptionDisableCursorLocationAssistance` to disable the cursor location. See https://developer.apple.com/documentation/appkit/nsapplicationpresentationoptions/nsapplicationpresentationdisablecursorlocationassistance?language=objc
