### ISSUE TITLE
Editor crashed when try to fix the script errors during running

### ISSUE THREAD

**Issue by SmallKi** [godotengine/godot#77881] opened 2023-06-05 13:11 UTC
### Godot version

v4.1.dev4.official [5c2295ff5]

### System information

Windows11, GLES3

### Issue description

Editor crashed when try to correct the script during running

### Steps to reproduce

1. try to make a mistake in a script, and add this script into a scene 
2. run this scene 
3. editor will report errors, do not close the running program, and try to fix the error in that script 
4. press 'ctrl + s' to save the script, and there will pop up an error panel saying that can not write to this file due to file locked or insufficient permissions
6. close the popup, the editor will crash, and console shows: "Safe save failed. This may be a permissions problem, but also may happen because you are running a paranoid anti"

### Minimal reproduction project

N/A

**Comment by RedworkDE** [comment] 2023-06-05 13:34
Duplicate of https://github.com/godotengine/godot/issues/77752

**Closed** 2023-06-05 16:23 UTC
