### ISSUE TITLE
[4.0a9] Godot crashes when making and then switching back to an empty scene.

### ISSUE THREAD

**Issue by JerswinMendiola** [godotengine/godot#61723] opened 2022-06-05 16:02 UTC
### Godot version

v4.0.alpha9.official (fc18891)

### System information

Windows 10, GLES3, Intel Core i3 7100

### Issue description

I started a project in Godot 4 Alpha 9, 
![image](https://user-images.githubusercontent.com/95561544/172059325-12acf901-aa3a-4996-a3da-d881dcce3913.png)

made another untitled scene, 
![image](https://user-images.githubusercontent.com/95561544/172059331-ce22e118-e32c-4198-a956-417053af60c2.png)

went back to the first one, 
it freezes a bit, 
then it crashes.

### Steps to reproduce

1.  Make a new project.
2.  Create a new empty scene.
3.  Open the previous scene.

**Comment by Calinou** [comment] 2022-06-05 21:02
Duplicate of https://github.com/godotengine/godot/issues/61654 (fixed in the latest `master` branch).

**Closed by Calinou** 2022-06-05 21:02 UTC
