### ISSUE TITLE
OBJ importer does not read vertex colors

### ISSUE THREAD

**Issue by fracteed** [godotengine/godot#70982] opened 2023-01-06 05:18 UTC
### Godot version

4.0 beta 10

### System information

Windows 10 960m

### Issue description

While the gltf and dae importers both support vertex colors, the obj importer does not. Blender has supported this feature for the last 3 versions, so it would be good to have this working with Godot 4.

While not strictly part of the obj spec, vertex colors are supported in several applications by having the rgb value after the vertex position as shown by this snippet:

```
# Blender 3.4.1
# www.blender.org
mtllib vertex_colored_sphere.mtl
o Sphere
v 0.000000 0.831470 -0.555570 0.0000 1.0000 0.0000
v 0.000000 0.555570 -0.831470 1.0000 0.0000 0.0000
v 0.000000 0.195090 -0.980785 1.0000 0.0000 0.0000
v 0.000000 0.000000 -1.000000 1.0000 0.0000 0.0000
v 0.000000 -0.195090 -0.980785 0.4980 0.0000 0.4980
v 0.000000 -0.555570 -0.831470 0.0000 0.0000 1.0000
```
This is a screenshot of what it should like in blender vs godot currently:

![obj_vertex_color](https://user-images.githubusercontent.com/7741669/210934940-033e64bc-464a-47d3-951b-4a4dfcdef4c5.jpg)

Obj files are still very useful to use for static meshes in Godot since they can be used directly in a mesh instance, so it would be great to have vertex color support.

### Steps to reproduce

- import an obj with vertex colors
-  add a material and turn on the vertex color option

### Minimal reproduction project

The blend file as well as the godot file with obj export example:

[obj_vertex_color.zip](https://github.com/godotengine/godot/files/10357479/obj_vertex_color.zip)

**Comment by fire** [comment] 2023-01-07 06:10
This is a feature proposal as it is not part of the obj spec but is commonly found to be useful. Are you interested in fixing it via a pull request?

**Comment by fracteed** [comment] 2023-01-07 06:29
@fire I am not a c++ coder so I couldn't code it myself. Should I be moving this to the feature requests section instead?

**Comment by Calinou** [comment] 2023-01-07 19:13
Duplicate of https://github.com/godotengine/godot-proposals/issues/5973.

**Closed by Calinou** 2023-01-07 19:13 UTC
Labels: feature proposal, archived, topic:import, topic:3d
