### ISSUE TITLE
Animation Tree Breaks Animations

### ISSUE THREAD

**Issue by HeadMonitor** [godotengine/godot#78158] opened 2023-06-12 21:24 UTC
### Godot version

4.0.3

### System information

Windows 11

### Issue description

When playing my animations through the **Animation Player** everything works as intended, the animation plays smoothly. When trying to use the **Animation Tree** the animations break. It is like certain tracks are not being played at all.

### Steps to reproduce

Open the reproduction project I have attached, and try to play the "Test" animation with **Animation Tree** enabled and with animation tree from animation player. 

### Minimal reproduction project

[Test.zip](https://github.com/godotengine/godot/files/11728475/Test.zip)

**Comment by HeadMonitor** [comment] 2023-06-12 22:06
After further investigation it seems that if I rename the animation to something random (eg. "Dwdadawdwadawdwdadfeesf") it starts to work. Interesting issue here.

**Comment by HeadMonitor** [comment] 2023-06-12 22:35
The animation I renamed to something random decided to break again.

**Comment by felaugmar** [comment] 2023-06-13 04:30
The `AnimationTree` plays well if you delete the **wsdwdwd** animation, but I couldn't investigate further why.

**Comment by TokageItLab** [comment] 2023-06-17 14:43
I guess the cause is due to a mixture of bezier and value tracks. Related by https://github.com/godotengine/godot/issues/49431. Hmm, it may be worth salvaging https://github.com/godotengine/godot/pull/49411.

**Comment by TokageItLab** [comment] 2023-06-23 12:45
Duplicate of #49431

**Closed by TokageItLab** 2023-06-23 12:45 UTC
Labels: bug, topic:editor, topic:animation
