### ISSUE TITLE
Inconsistency between Color RGBA8 and Image RGBA8

### ISSUE THREAD

**Issue by rob1gat** [godotengine/godot#89661] opened 2024-03-18 21:34 UTC
### Tested versions

- Reproducible in v4.3.dev5.official [c9c17d6ca]

### System information

Godot v4.3.dev5 - Linux Mint 21.1 (Vera) - X11 - Vulkan (Forward+) - dedicated AMD Radeon RX 6700 XT (RADV NAVI22) () - 12th Gen Intel(R) Core(TM) i5-12400 (12 Threads)

### Issue description

If I run this piece of code : 
```gdscript
var color:Color = Color(0.505,0.505,0.505)
var img:Image = Image.create(32,32,false, Image.FORMAT_RGBA8)
img.fill(color)
prints(img.get_pixel(0,0).r8, color.r8)
```
I get the ouput : `128 129`

Since I filled `img` with `color`, I would expect `img.get_pixel(0,0).r8` and `color.r8` to be identical.

Looking at the code, it seems that : 
- Colors RGBA8 components are rounded ints : 
```cpp
int32_t get_r8() const { return int32_t(CLAMP(Math::round(r * 255.0f), 0.0f, 255.0f)); } // color.h line 209
```
- Images store RGBA8 components as truncated ints : 
```cpp
ptr[ofs * 4 + 0] = uint8_t(CLAMP(p_color.r * 255.0, 0, 255)); // image.cpp line 3206
```

### Steps to reproduce

N/A

### Minimal reproduction project (MRP)

N/A

**Comment by rsubtil** [comment] 2024-03-20 12:49
The `Color` used to use truncated values, but was explicitly changed to rounded values with https://github.com/godotengine/godot/pull/47726. So in that vein I'd say images should follow the same behavior.

(cc @dalexeev for their input)

**Comment by rob1gat** [comment] 2024-03-20 13:03
I'd say Image should use Color's rgba8 getters to ensure consistency even if the implementation of these getters changes in the future.

**Comment by dalexeev** [comment] 2024-03-21 08:34
* Duplicate of #59983.
* See also #60135.

Thanks for reporting the bug nonetheless!

**Closed by dalexeev** 2024-03-21 08:34 UTC
Labels: discussion, topic:core
