### ISSUE TITLE
Godot load screen Android 

### ISSUE THREAD

**Issue by KatlingZer0** [godotengine/godot#70079] opened 2022-12-14 22:21 UTC
### Godot version

4.0 beta 8

### System information

Android Google pixel 

### Issue description

Open asset library or cancel button does not respond to any input except for highlighting. 

### Steps to reproduce

Load Godot on android phone 

### Minimal reproduction project

No project started

**Comment by Calinou** [comment] 2022-12-15 01:36
Duplicate of https://github.com/godotengine/godot/issues/69854 (same cause).

**Closed by Calinou** 2022-12-15 01:36 UTC
