### ISSUE TITLE
Issue at Build for Playing Store with n

### ISSUE THREAD

**Issue by cutydina** [godotengine/godot#83020] opened 2023-10-08 23:54 UTC
### Godot version

4.1

### System information

Windows 11

### Issue description

When Build AAB to Android, it doesn't build with debug symbols or R8 and Play Store always gives the warning.

### Steps to reproduce

Build on Android and upload bundle to Play Store.

### Minimal reproduction project

![Captura de pantalla 2023-10-08 113740](https://github.com/godotengine/godot/assets/103970174/e804594c-c496-4be3-9430-65756fca16bc)

This but my play store is in Spanish. :(

**Comment by akien-mga** [comment] 2023-10-11 08:43
That's expected, official export templates don't include debug symbols for size reasons.

You can compile custom export templates with debug symbols to upload to Google Play if wanted.

- Duplicate of https://github.com/godotengine/godot-proposals/issues/1342

**Closed by akien-mga** 2023-10-11 08:43 UTC
Labels: platform:android, needs testing, topic:export
