### ISSUE TITLE
Fragment Shader not displaying correctly with low resolutions mode

### ISSUE THREAD

**Issue by brunosxs** [godotengine/godot#15700] opened 2018-01-14 12:11 UTC
**Godot version:**
3.0b2

**OS/device including version:**
Intel® HD Graphics 4000

**Issue description:**

Under the commonly used low resolutions for pixel art focused games, like 320x180, the displaying of a simple mirror shader gets messed up... if I bump the resolution to double its size, or if I just use 240 of height instead of 180, the shader behaves as intended.

With a resolution of 320x180:
![captura de tela_2018-01-14_10-10-22](https://user-images.githubusercontent.com/1557903/34915796-304c2248-f913-11e7-92d4-f9c02df77937.png)

With a resolution of 640x360:
![captura de tela_2018-01-14_10-08-00](https://user-images.githubusercontent.com/1557903/34915785-ed35662c-f912-11e7-8f67-3925b4908b8b.png)

**Steps to reproduce:**

Add this simple shader to a texture inside a 180 height resolution project

```
shader_type canvas_item;


void fragment() {
	vec2 uv = vec2(SCREEN_UV.x, (SCREEN_UV.y) + UV.y);
	COLOR = texture(SCREEN_TEXTURE, uv);	
	
}
```

**Minimal reproduction project:**
[src.zip](https://github.com/godotengine/godot/files/1629299/src.zip)

**Comment by akien-mga** [comment] 2018-01-18 09:51
Not critical for the upcoming 3.0 release, so moving to the next milestone. A fix can still be cherry-picked for 3.0.x maintenance releases once available in the master branch.

**Comment by robfram** [comment] 2018-03-03 19:54
I was playing with your demo project and found that the wrong render is not screen size dependent, as I show with this captures at differente sizes:

320x180, 320x240, 320x320 at the initial position, 320x320 moving the blocks, 320x480
![initial](https://user-images.githubusercontent.com/35065795/36938457-1afbec86-1f22-11e8-8bf1-d34a6efdabc3.png)

I think it is more a bug in your shader code than in Godot per se. I changed the shader to another one not using `UV.y` but an fixed offset dependent of resolution size, and changing colour to see clearly the shader effect. Same resolutions than before:

320x180, 320x240, 320x320, 320x480
![my_initial](https://user-images.githubusercontent.com/35065795/36938469-4aadf000-1f22-11e8-9a91-b5fc4e989624.png)


As I said, not sure if there is a bug underneath this, but it must be take in consideration than the scale of pixels per UV is not the same for the screen than for the sprite where you are applying the shader. For both the whole size, the UV range goes from 0 to 1. If you are using a 320x180 screen resolution and have a sprite of 800x90 to simulate the water reflection, the screen texels will have twice the vertical size in pixels than the sprite one (i.e., screen has 1/180 texel per pixel and sprite has 1/90 texel per pixel).

**Comment by reduz** [comment] 2018-09-06 17:05
if you want to ensure that your screen is scaled per pixel, use viewport scaling and this will work in all resolutions. This is not a bug.

**Closed by reduz** 2018-09-06 17:05 UTC
Labels: bug, topic:rendering
