### ISSUE TITLE
Tilemap bug causing corrupted maps, crashing of Godot

### ISSUE THREAD

**Issue by chucklepie** [godotengine/godot#29312] opened 2019-05-30 13:05 UTC
**Godot version:**
Godot 3.1 

**OS/device including version:**
Windows 10

**Issue description:**
I have attached projects/files to try but basically after creating a 32x32 pixel tileset and creating a tilemap, then drawing the map, on reloading Godot crashes and/or displays the map wrong. Please see images.

I have found the error and it is (possibly byte size related, I do not know what the entry does but seems like this). At the start of the scene file it is adding this:

[gd_scene load_steps=3 format=2]

At the bottom where your map is, you get this:
[node name="TileMap" type="TileMap"]
tile_set = SubResource( 1 )
cell_size = Vector2( 32, 32 )
tile_data = PoolIntArray()

When you save, reload and see it corrupted, then fix the map the header remains the same but the node, just before the tile_data adds a new entry:

[node name="TileMap" type="TileMap"]
********** format=1 ***********
tile_set = SubResource( 1 )
cell_size = Vector2( 32, 32 )
tile_data = PoolIntArray()

i.e. it has added 'format=1'. If I go back to my original corrupted map, add this line in, then it loads ok and is not corrupted.

Find attached two projects, the first (01) is where I drew it all within godot and it is corrupted after reloading, then the second (03) is after I fix it up after reloading. You can see the only difference is this format=1.

Could you also comment to tell me what this means because I am creating 8, 16, 32 sized tilemaps and would like to know the fault.

[FaultyMap03.zip](https://github.com/godotengine/godot/files/3237095/FaultyMap03.zip)
[FaultyMap01.zip](https://github.com/godotengine/godot/files/3237096/FaultyMap01.zip)

![image1](https://user-images.githubusercontent.com/12863685/58634283-d76d6000-82e2-11e9-8e37-6415cd06e790.png)
![image2](https://user-images.githubusercontent.com/12863685/58634282-d76d6000-82e2-11e9-86de-fb6bc777d68d.png)

**Comment by menip** [comment] 2019-05-30 14:05
It's unclear how to replicate, the projects provided don't show a bug in action. Could you attach gif showcasing issue?

**Comment by chucklepie** [comment] 2019-05-30 17:52
I have checked the code (https://github.com/godotengine/godot/blob/master/scene/2d/tile_map.cpp)

Format version 2 is current. What I can see in the code is FORMAT_2 changes data offset, byte size, endian values throughout.

Given it doesn't work, then on re-saving it adds 'format=1', then I'm guessing it's a combination of a bug in tilemap/tileset storing the map as old format 1 but labelling it as 2 when it should be saving as 2, and then somehow managing to add format=1 on a second load somehow.

I imagine even though format=1 is making it work, that's a bug and should be in 2. I can't be much more help I'm afraid.

**Comment by chucklepie** [comment] 2019-05-30 18:02
Why can't you recreate, simply take the first project, load it and it fails. Load the second and it works? 

My steps were:
1. Create a blank project
2. Add Tilemap as a root node
3. Change cell size to 32x32
4. Create new tileset and import the mario bmp file
5. Create about 5 or 10 tiles from this
6. Draw a pretty picture on the screen
7. Save then reload.
8. It fails.

**Comment by chucklepie** [comment] 2019-05-30 18:12
Additionally, in TileMap constructor I can see this:

format = FORMAT_1; //Always initialize with the lowest format

and I'm not entirely sure why, but in _set_tile_data() it's adding 
format = FORMAT_2; 

at the very end, which to me seems like it's writing in format=1 as it's the default, then writing the data, then setting the format to 2?

**Comment by chucklepie** [comment] 2019-05-30 18:56
Here is a short video of the whole fault. I recreated the 'fix' in the video by manually updating the scene file rather than faff on with re-opening, fixing, saving. You should see the entire fault. I believe this to be as per my comment above regarding format being set incorrectly in code.

https://youtu.be/m_3M8ylUMBI

**Comment by DavidSichma** [comment] 2019-05-30 22:37
So this is what I found out:

If a new TileMap is saved for the very first time to disc it won't have any `format` tag. If it is saved again (doesn't matter if for the second or n-th time) it will always have `format = 1`.
If you load a TileMap without the format tag, either by reopening the scene or instancing the scene in another, the TileMap will get loaded incorrectly. Saving a scene with a corrupt TileMap will add `format = 1`
making the damage permament. Maybe it is possible to revert this but I did not investigate.

Simpler reproduction steps:
1. Add a new TileMap to any scene.
2. If you want to visually see the corruption assign a TileSet and start drawing. This is optional.
3. Save the scene with the TileMap for the **very first** time. The bug won't show up if the scene was saved more than once when containing the TileMap. Don't close this scene.
4. \<scene-name>.tscn will not have a format tag for the TileMap.
5. If you reload this scene (preferable by instancing in another scene) you will see a corrupt TileMap if you drew one in step 2.
6. Go back to the scene with the original TileMap. If it hasn't been closed it will still show as intended.
7. Save again. Now \<scene-name>.tscn will have a `format = 1 line. The file shouldn't have changed otherwise. If you try to load the TileMap it won't show up corrupted. As the TileMap won't corrupt anymore it is now safe to close the scene.

For now, the workaround seems to be to save the scene at least two times every time you add a TileMap node.

**Comment by chucklepie** [comment] 2019-05-31 08:02
Thanks for checking and confirming.

I guess the simple question is if format 2 is the current level, why are new tilemaps constructed with a format of 1?

But Is this related to the code I mentioned: Tilemap is constructed with a format of 1, the header of the scene is saved with format 2, in the method _set_tile_data() it allocates the tiles in format 1, but then at the very end it switches format with the last line being  format = FORMAT_2;

So it is writing in format 1, thinking it is 2?

**Comment by fossegutten** [comment] 2019-06-02 09:43
Same happened to me. This bug is pretty bad in the case you make a detailed map that gets corrupted. Had to draw mine over again and it worked the second time.

**Closed** 2019-08-08 09:20 UTC
Labels: bug, needs testing, topic:editor
