### ISSUE TITLE
Collision detection between moving KinematicBody nodes is broken

### ISSUE THREAD

**Issue by e344fde6bf** [godotengine/godot#46601] opened 2021-03-02 20:07 UTC
**Godot version:**
3.2.3.stable

**OS/device including version:**
Arch Linux

**Issue description:**

When KinematicBody nodes test for collisions, they test against the positions objects had at the start of the physics frame.  This causes problems when they are both moving as they can end up overlapping without detecting any collisions. [Here is a proposal](https://github.com/godotengine/godot-proposals/issues/2332)  that discusses this issue in more detail.

**Steps to reproduce:**

Place two cubes next to each other and use `move_and_collide()` towards the same position on the same physics frame. This is what happens:

![test-collision](https://user-images.githubusercontent.com/79001820/109640415-2e7d2480-7b9c-11eb-8bcd-a6584f7e9b7d.png)

**Minimal reproduction project:**

[test-collision.zip](https://github.com/godotengine/godot-proposals/files/6068154/test-collision.zip)

**Comment by madmiraal** [comment] 2021-03-06 09:12
Duplicate of #30481.

**Closed by madmiraal** 2021-03-06 09:12 UTC
Labels: bug, topic:physics
