### ISSUE TITLE
Stretch mode 'viewport' breaks completely when scaling/stretching

### ISSUE THREAD

**Issue by Demiu** [godotengine/godot#32573] opened 2019-10-05 19:22 UTC
**Godot version:**
3.1.1

**OS/device including version:**
Windows 10 Pro N 1803
OpenGL ES 3.0 Renderer: GeForce GTX 1060 6GB/PCIe/SSE2
Nvidia drivers 399.24

**Issue description:**
Setting the stretch mode to 'viewport' makes the engine render nothing (all black) anytime it would have to scale/stretch the world, if the viewport is expanded everything works as expected. This is just a more detailed version of #23054, as the problem persists in 3.1 

**Steps to reproduce:**
Go to project settings, set the stretch mode to viewport.
From here, it breaks in different ways depending on the stretch aspect. Testing done in a window.
_Ignore_ always stretches the contents of the viewport, so any resize of the window breaks it, with the exception of returning to the original size.
_Keep_ stretches/scales only if both the window height and width have been changed, so you can make the window wider or higher and the black bars appear as expected, if you do both then you get nothing (all black).
_Keep\_width_ will expand the viewport when the height is changed, so that works. If you change the width of the window it's black.
_Keep\_height_ is the opposite of keep_width.
_Expand_ is a mix of keep_x modes. As long as you restrict yourself to resizing in only axis it works as expected, by resizing the viewport and everything rendering nicely. If you change both axes it's black.
Making the window smaller than the initial size in any axis always causes a black screen as it always scales down the frame.
Setting the window height in project settings above the display's height will make Windows resize that window to fit vertically. This also triggers the 'no downsizing' case above, but in a unique way. The frame is scaled from the beginning and the boot splash has no issues rendering, but (I presume) further frames are not pushed into framebuffer at all, since the boot image will just stay there instead of immediately going to black screen. Certain actions will still result in expected 'all black' bugged state, like resizing the window in any way; presumably because it makes Windows forcefully flush the window's framebuffer.

**Minimal reproduction project:**
[Test.zip](https://github.com/godotengine/godot/files/3693625/Test.zip)
A white color rect covers the entire viewport. This means white = original, godot's default grey = expanded, black = either the vertical bars of keep_* aspects or the bug, if it's the entire window.

**Comment by Calinou** [comment] 2019-10-07 15:23
Duplicate of #23054. Please continue the discussion there – feel free to copy the issue description and test project as a comment on that issue.

**Closed by Calinou** 2019-10-07 15:23 UTC
