### ISSUE TITLE
Signal reciever method is added out of class body (C#)

### ISSUE THREAD

**Issue by KrizCologne** [godotengine/godot#84689] opened 2023-11-10 03:41 UTC
### Godot version

4.1.2

### System information

Windows 10

### Issue description

When using the "Connecting a signal to a method" window and create a new connection, the method is created out of the class body.
It should be created within the class body.

### Steps to reproduce

1. Select a signal in the "Node"-Tab
2. Right click an select "Connect..." or "Edit"
3. Select any scrpt
4. Tap on "Connect"
5. The newly created method appears out of the class body

### Minimal reproduction project

no project neede

**Comment by akien-mga** [comment] 2023-11-10 09:23
- Duplicate of #18721

**Closed by akien-mga** 2023-11-10 09:23 UTC
