### ISSUE TITLE
Error on build server platform

### ISSUE THREAD

**Issue by AlexHolly** [godotengine/godot#12167] opened 2017-10-17 00:44 UTC
Godot Master
x11
`scons p=server`

```
platform/server/godot_server.cpp: In function 'int main(int, char**)':
platform/server/godot_server.cpp:35:12: error: cannot declare variable 'os' to be of abstract type 'OS_Server'
  OS_Server os;
            ^~
In file included from platform/server/godot_server.cpp:31:0:
platform/server/os_server.h:49:7: note:   because the following virtual functions are pure within 'OS_Server':
 class OS_Server : public OS_Unix {
       ^~~~~~~~~
In file included from platform/server/../x11/power_x11.h:36:0,
                 from platform/server/os_server.h:33,
                 from platform/server/godot_server.cpp:31:
core/os/os.h:130:15: note:      virtual bool OS::_check_internal_feature_support(const String&)
  virtual bool _check_internal_feature_support(const String &p_feature) = 0;
               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by akien-mga** [comment] 2017-10-17 05:53
Duplicate of #8361.

**Closed by akien-mga** 2017-10-17 05:53 UTC
