### ISSUE TITLE
Godot 4 crashes when opening project on ubuntu

### ISSUE THREAD

**Issue by FiveEight58** [godotengine/godot#75096] opened 2023-03-19 11:19 UTC
### Godot version

4.0

### System information

Ubuntu linux

### Issue description

when i open the godot 4.0 executable in ubuntu it opens up fine but when i click on a project and try to open it a window pops up like its supposed to with godot splash screen and then it just crashes, so does the original executable window, and yes i have tried creating a fresh new project

Debugging suggests program crashed with signal 11 

[

https://user-images.githubusercontent.com/61921574/226171712-b8d592b8-acae-44e8-9003-227d877f6135.mp4
![Screenshot_20230319_161639](https://user-images.githubusercontent.com/61921574/226171750-4ce27312-4cc0-4931-8983-0ce04eaf5b65.png)

](url)

### Steps to reproduce

open godot 4.0 linux executable and then click a project

### Minimal reproduction project

N/A

**Comment by Calinou** [comment] 2023-03-21 17:43
- Duplicate of https://github.com/godotengine/godot/issues/58927 (i3-2120 integrated graphics lack Vulkan support).

**Closed by Calinou** 2023-03-21 17:43 UTC
