### ISSUE TITLE
body_entered and body_exited not reporting collision with StaticBody node

### ISSUE THREAD

**Issue by N8n5h** [godotengine/godot#21013] opened 2018-08-14 17:29 UTC
**Godot version:**
v3.0.6.stable.official.8314054

**OS/device including version:**
Windows 7-64Bit

**Issue description:**
body_entered and body_exited signals from Area class appear to not be reporting collision with the StaticBody node.

**Minimal reproduction steps:**
Create a MeshInstance select cube for shape, use the Mesh > Create Trimesh Static Body.
Create an Area, Add a CollisionShape to the area.
Create a script for the Area, connect the body_entered and body_exited signals to that script.
Translate the Area through the MeshInstance, I used an animation.

**Minimal reproduction project:**
[test.zip](https://github.com/godotengine/godot/files/2287910/test.zip)

**Comment by vnen** [comment] 2018-08-15 04:18
This is expected. Static bodies are passive and do not report contacts.

**Comment by N8n5h** [comment] 2018-08-15 13:39
Ok, then I think the Area documentation should be updated to reflect that
and the Physics Introduction as well.

**Comment by bojidar-bg** [comment] 2018-08-15 13:47
> This is expected. Static bodies are passive and do not report contacts.

This issue is about the Area not receiving the signals, not the StaticBody.
That being said, I can't confirm in either 2D or 3D using rectangle/cube and circle/sphere meshes.

This issue seems to be a duplicate of #16392.

**Comment by vnen** [comment] 2018-08-15 14:58
@bojidar-bg that's what I understood from the table in the docs: http://docs.godotengine.org/en/2.1/learning/features/physics/physics_introduction.html#in-case-of-overlap-who-receives-collision-information (which for some reason was removed in 3.0). In there it says that in Static/Area collision none receive this information. Did this change or the table was wrong?

**Comment by bojidar-bg** [comment] 2018-08-15 16:12
Probably changed between versions, Area gets the signal in 3.0.6.

**Comment by N8n5h** [comment] 2018-08-23 14:05
> Probably changed between versions, Area gets the signal in 3.0.6
@bojidar-bg , so it's a bug? or there is something I'm not doing right to get the signal?
I opened an issue for feature request #21043 , but I guess it may not be needed.

**Comment by bojidar-bg** [comment] 2018-08-24 12:38
Note that I was replying to @vnen in my previous comment.

@N8n5h Check #16392 for the bug.
This issue is a bit in limbo right now -- if you confirm that it is a duplicate, we will close it.

**Comment by N8n5h** [comment] 2018-08-24 13:12
> This issue is a bit in limbo right now -- if you confirm that it is a duplicate, we will close it.

I did not import any models and instead used primitive shapes inside of Godot and the "Create Trimesh Static Body" functionality. So if it's a duplicate, the error may be replicable without imported models.
But I'm not sure if it's the same error.

I added minimal reproduction steps in my original post.

**Comment by bojidar-bg** [comment] 2018-08-24 13:34
"Create Trimesh Static Body" creates a concave shape, and is actually used by the importer. Closing as it is the same issue :)

**Closed by bojidar-bg** 2018-08-24 13:34 UTC
