### ISSUE TITLE
Godot4: Set Environment Background mode to Canvas can cause improper editor display

### ISSUE THREAD

**Issue by Argphts** [godotengine/godot#58487] opened 2022-02-24 06:49 UTC
### Godot version

Godot4 alpha2 & 3

### System information

Windows 10 

### Issue description

When adding a WorldEnvironment node in the current scene and set the Environment property Background Mode to "Canvas", all the secondary menus will display as a pure grey box instead of a list of components.
![image](https://user-images.githubusercontent.com/42088114/155472190-1e81757c-f673-43df-bceb-14b567e15442.png)
improper displayed menus:
![image](https://user-images.githubusercontent.com/42088114/155472384-c4558e3d-8d7d-4cc6-8909-517e952b9f0e.png)
![image](https://user-images.githubusercontent.com/42088114/155472458-d16a923b-e8b9-4b1d-8eb0-99bc91861425.png)
![image](https://user-images.githubusercontent.com/42088114/155472514-08fa8c30-6171-4c9c-a58b-2d06aee5ee0d.png)

### Steps to reproduce

![image](https://user-images.githubusercontent.com/42088114/155472570-1cb1964d-af33-42da-88d3-73bdfe756907.png)

**Comment by Chaosus** [comment] 2022-02-24 07:34
Duplicate of https://github.com/godotengine/godot/issues/52467

**Closed by Chaosus** 2022-02-24 07:34 UTC
Labels: bug, archived, topic:rendering, regression, topic:gui, topic:2d
