### ISSUE TITLE
Single GDScript syntax mistake causes multiple errors

### ISSUE THREAD

**Issue by Jayman2000** [godotengine/godot#27702] opened 2019-04-05 15:51 UTC
**Godot version:**
v3.1.stable.official

**OS/device including version:**
Kubuntu 18.10 x86-64

**Issue description:**
Many languages use the following syntax for declaring variables:

`Type variable_name`

GDScript is not one of these languages. Trying to declare a variable in GDScript using that syntax produces the following errors:
1. `modules/gdscript/gdscript_tokenizer.cpp:1103 - Condition ' tk_rb[ofs].type != TK_IDENTIFIER ' is true. returned: StringName()`
2. ` res://example.gd:3 - Parse Error: Unexpected token: Built-In Type:`
3. ` modules/gdscript/gdscript.cpp:580 - Method/Function Failed, returning: ERR_PARSE_ERROR`

with error 1 being printed multiple times. There does not appear to be any lasting effects after the syntax error is corrected.

While I would expect an error to be produced, I would not expect multiple errors to be produced for a single syntax mistake. I would not expect errors 1 and 3 as they reference code in Godot itself, and not the GDScript code being edited by the user. I would also expect any error that is produced to only be produced once, and not multiple times like error 1 is.

**Steps to reproduce:**
1. In the script editor, open a GDScript file that contains this syntax mistake (e.g., "example.gd" in the minimal reproduction project).
2. Open the output tab in the bottom panel. It will contain errors 1, 2, and 3, followed by error 1 twice more.

**Minimal reproduction project:**
[Tokenizer Bug.zip](https://github.com/godotengine/godot/files/3048684/Tokenizer.Bug.zip)

**Comment by abogilovic** [comment] 2019-08-06 02:45
![errors](https://user-images.githubusercontent.com/47434277/62507490-e4d42880-b804-11e9-9dcd-a0f219162b53.png)
Same type1 error, can't find a way to fix :/

**Comment by Calinou** [comment] 2019-08-06 10:20
@abogilovic Can you post a full copy of the script that causes the error?

**Comment by abogilovic** [comment] 2019-08-06 11:59
> 
> 
> @abogilovic Can you post a full copy of the script that causes the error, please?

Oh I found why it started acting like this.
I somehow had this true in fun parameters, don't know why I wrote it.
func _on_exit_button_pressed(true):
	pass
So people, check your scripts if encountering this.
After all it would be great if it pointed me on this line of error source.

**Comment by akien-mga** [comment] 2022-09-30 11:59
Confirmed that this is still a problem with 3.5.1 in https://github.com/godotengine/godot/issues/66648#issuecomment-1263445576.

There might be multiple ways to trigger this error which need to be differentiated and better handled. But the case found in #66648 and described by @abogilovic above is particularly nasty as it doesn't highlight where the error happened. You have to guess by finding which script outputs these errors when you load/save it, and comment lines one by one to find the culprit.

**Comment by bojidar-bg** [comment] 2022-09-30 20:22
Wild guess, culprit for `tk_rb[ofs].type != TK_IDENTIFIER` error is here:

https://github.com/godotengine/godot/blob/0fd48f02f550bb4c51797472958dfde8b267e91a/modules/gdscript/gdscript_parser.cpp#L3942-L3947

Looks like a leftover from #8217. It should call `get_token_literal` instead of `get_token_identifier`; like the code for `var` does here:

https://github.com/godotengine/godot/blob/0fd48f02f550bb4c51797472958dfde8b267e91a/modules/gdscript/gdscript_parser.cpp#L4878

**Comment by coelhucas** [comment] 2023-02-06 20:07
It also happens if you use the `remote` keyword as a signal name, without giving any further information, I had to remove parts of the code until I found it.

E.g.:
```gdscript
signal something(remote) # -> error
```

**Comment by KoBeWi** [comment] 2024-11-19 23:01
Seems fixed in GDScript 2.0.

**Closed by KoBeWi** 2024-11-19 23:01 UTC
Labels: enhancement, discussion, topic:gdscript
