### ISSUE TITLE
Turning off Vsync seems to have no effect

### ISSUE THREAD

**Issue by Geometror** [godotengine/godot#41102] opened 2020-08-07 12:44 UTC
**Godot version:**

241e709462cd90d3daade3c6a05ff130fe85b4c0

**OS/device including version:**

OS: Windows 10 2004
CPU: AMD Ryzen 7 3700X
GPU: AMD Radeon RX 580 (driver version: 20.20.01.09-200711a-357168E-RadeonSoftwareAdrenalin2020)
backend: Vulkan

**Issue description:**

After disabling Vsync under  (and restarting the editor) my test project still runs on 60FPS, which is equal to my monitors refresh rate. I know, Vsync should always be turned on to avoid screen tearing, but as the option to disable it is available, turning it off should have an effect.

**Steps to reproduce:**
1. Create a new project
2. Disable Vsync under Project Settings>General>Display>Window>Vsync
3. Enable "Print Fps" under Project Settings>General>Debug>Settings
4. (Not necessary)Adding a Camera3D, MeshInstance3D and WorldEnvironment to the scene
5. Run the scene

**Minimal reproduction project:**
[vsync_test_project.zip](https://github.com/godotengine/godot/files/5041405/vsync_test_project.zip)

**Comment by Calinou** [comment] 2020-08-07 12:56
Duplicate of #36467.

**Closed by Calinou** 2020-08-07 12:56 UTC
