### ISSUE TITLE
Changing color on the editor theme sometimes crashes

### ISSUE THREAD

**Issue by xfrazz** [godotengine/godot#66976] opened 2022-10-06 09:22 UTC
### Godot version

v4.0.beta2

### System information

Linux

### Issue description

I change one of the color options on the current editor theme which is the stock theme, works sometimes, sometimes produces a crash

```
================================================================
handle_crash: Program crashed with signal 11
Engine version: Godot Engine v4.0.beta2.official (f8745f2f71c79972df66f17a3da75f6e328bc55d)
Dumping the backtrace. Please include this when reporting the bug to the project developer.
[1] /lib/x86_64-linux-gnu/libc.so.6(+0x43090) [0x7f49916d0090] (??:0)
-- END OF BACKTRACE --
================================================================
```

```
================================================================
handle_crash: Program crashed with signal 11
Engine version: Godot Engine v4.0.beta2.official (f8745f2f71c79972df66f17a3da75f6e328bc55d)
Dumping the backtrace. Please include this when reporting the bug to the project developer.
[1] /lib/x86_64-linux-gnu/libc.so.6(+0x43090) [0x7ff3853dc090] (??:0)
[2] /lib/x86_64-linux-gnu/libpthread.so.0(pthread_mutex_lock+0x4) [0x7ff3856eafc4] (??:0)
[3] /home/efrfred/Desktop/Godot_v4.0-beta2_linux.x86_64() [0x28d1e4c] (??:0)
[4] /home/efrfred/Desktop/Godot_v4.0-beta2_linux.x86_64() [0x291a531] (??:0)
[5] /home/efrfred/Desktop/Godot_v4.0-beta2_linux.x86_64() [0x295a47b] (??:0)
[6] /home/efrfred/Desktop/Godot_v4.0-beta2_linux.x86_64() [0x295dd6c] (??:0)
[7] /home/efrfred/Desktop/Godot_v4.0-beta2_linux.x86_64() [0x295e423] (??:0)
[8] /home/efrfred/Desktop/Godot_v4.0-beta2_linux.x86_64() [0x29412c7] (??:0)
[9] /home/efrfred/Desktop/Godot_v4.0-beta2_linux.x86_64() [0xe08004] (??:0)
[10] /home/efrfred/Desktop/Godot_v4.0-beta2_linux.x86_64() [0x3ff844e] (??:0)
[11] /home/efrfred/Desktop/Godot_v4.0-beta2_linux.x86_64() [0x3ff92c5] (??:0)
[12] /home/efrfred/Desktop/Godot_v4.0-beta2_linux.x86_64() [0xe09fa9] (??:0)
[13] /home/efrfred/Desktop/Godot_v4.0-beta2_linux.x86_64() [0xd8b2e8] (??:0)
[14] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf3) [0x7ff3853bd083] (??:0)
[15] /home/efrfred/Desktop/Godot_v4.0-beta2_linux.x86_64() [0xdac6ee] (??:0)
-- END OF BACKTRACE --
================================================================

```

### Steps to reproduce

Don't know how to reproduce, sometimes is fails sometimes it works
Seems to happen more often if the project is bigger or if I have multiple instances but I am not sure.

```
Running Ubuntu with this kernel:
 5.15.0-48-generic
libc:
libc6:amd64            2.31-0ubuntu9.9   # GNU C Library: Shared libraries
linux-libc-dev:amd64   5.4.0-126.142     # Linux Kernel Headers for development
```

**Comment by akien-mga** [comment] 2022-10-06 09:24
Duplicate of #59798. This should be fixed in 4.0 beta 3 :)

**Closed by akien-mga** 2022-10-06 09:24 UTC
