### ISSUE TITLE
Material duplicate does not generate new uid

### ISSUE THREAD

**Issue by D2klaas** [godotengine/godot#57756] opened 2022-02-07 13:21 UTC
### Godot version

v4.0.alpha1.official [31a7ddbf8]

### System information

Windows 10, RTX 2070

### Issue description

When saving a material in the editor, then duplicate the material in the ressource panel results in both materials share the same uid.
This messes up all references in saved and imported scenes. Editor uses random material with the same uid.

original material
```
[gd_resource type="StandardMaterial3D" format=3 uid="uid://cor2a0pcje5qm"]

[resource]
albedo_color = Color(0.996078, 0.027451, 0, 1)
```
duplicated material
```
[gd_resource type="StandardMaterial3D" format=3 uid="uid://cor2a0pcje5qm"]

[resource]
albedo_color = Color(0, 0.996078, 0.0627451, 1)
```

### Steps to reproduce

Create material
Save material as file
Duplicate material in resource panel
Check files for uid's

**Comment by Calinou** [comment] 2022-02-07 13:23
Duplicate of https://github.com/godotengine/godot/issues/54774.

**Closed by Calinou** 2022-02-07 13:23 UTC
