### ISSUE TITLE
Allowing comments for nodes.

### ISSUE THREAD

**Issue by Sslaxx** [godotengine/godot#5992] opened 2016-07-31 22:42 UTC
**Issue description** (what happened, and what was expected):
Having comments on a node might be useful for projects (perhaps larger ones in particular?) where you may not necessarily remember what a node is for, why it's there etc. So if nodes have comments that you can set in the Inspector (and then see by hovering over their entries in the Scene panel), that might be of use?

Please excuse the awful editing, but hopefully these help get my point across?

![node_comment_2 png](https://cloud.githubusercontent.com/assets/324679/17279872/77243b12-5778-11e6-9617-08dc29a15ea5.png)
 ![node_comment_1 png](https://cloud.githubusercontent.com/assets/324679/17279871/771299c0-5778-11e6-8964-8f59d2c2b3b2.png)

**Comment by vnen** [comment] 2016-07-31 22:53
Duplicate of #2082. Can you copy/paste your suggestion there?

**Closed by vnen** 2016-07-31 22:53 UTC

**Comment by Sslaxx** [comment] 2016-07-31 22:57
Done.

**Comment by vnen** [comment] 2016-07-31 23:03
Thanks!
