### ISSUE TITLE
Disabling filter in Project settings crashes Godot

### ISSUE THREAD

**Issue by TeddyDD** [godotengine/godot#8335] opened 2017-04-09 14:14 UTC
**Operating system or device - Godot version:**
Godot 2.1.2 Linux 64 bit (from Steam)

**Issue description:**
Disabling filter option in project settings crashes Godot when checkbox on left side is disabled

**Steps to reproduce:**
- go to Projects Settings > General > Image Loader
- click on checkbox on right side of `filter`

**Workaround**
- turn on left checkbox

**Comment by akien-mga** [comment] 2017-04-09 14:23
Duplicate of #7696, fixed in 2.1.3.

**Closed by akien-mga** 2017-04-09 14:23 UTC
Labels: bug, topic:editor
