### ISSUE TITLE
Impossible to "one-click expand" items in the editor's main menu

### ISSUE THREAD

**Issue by MattUV** [godotengine/godot#16531] opened 2018-02-10 09:12 UTC
**Godot version:** 3.0 stable

**OS/device including version:** Any

**Issue description:**
In the editor's main menu, when an item is expanded and you click on another one, it will close the first one without expanding the second. You have to click twice to expand another menu.
![after](https://user-images.githubusercontent.com/13215043/36060406-5d34440c-0e49-11e8-8b11-a0fc1eafb1a4.gif)

This issue appeared for he first time with this PR: #13351
Before it was working correctly:
![before](https://user-images.githubusercontent.com/13215043/36060416-a6de8a54-0e49-11e8-981a-9d8070174fd5.gif)

**Steps to reproduce:**
Open any project, and play with the main menu.
Do the same with an oder version of godot to compare (I think 3.0 RC1 was released before the regression)

**Note:**
This is a volunteer duplicate of #15974, written for the sake of clarity.

**Comment by letheed** [comment] 2018-02-10 11:59
Solving #11692 is the proper way to solve this.

**Comment by mhilbrunner** [comment] 2018-02-10 15:33
Closing, duplicate of https://github.com/godotengine/godot/issues/15974 and https://github.com/godotengine/godot/issues/11692.

**Closed by mhilbrunner** 2018-02-10 15:33 UTC
