### ISSUE TITLE
Vulkan: Glow not working in 2D due to 2D rendering being in LDR

### ISSUE THREAD

**Issue by MyStarrySpace** [godotengine/godot#62110] opened 2022-06-16 14:00 UTC
### Godot version

4.0.dev (alpha 10)

### System information

Windows 11 Pro version 10.0.22000 Build 22000, NVIDIA GeForce RTX 2060, Game Ready Driver v511.79, Vulkan

### Issue description

The glow feature of WorldEnvironment doesn't work properly in 2D in Godot 4.0. The object itself does get brighter, but it does not emit any bloom

### Steps to reproduce

1. Create a Worldenvironment node
2. Create a Sprite2D with any texture
3. Modulate the sprite with RAW values above 1

### Minimal reproduction project

[2d_hdr_demo.zip](https://github.com/godotengine/godot/files/8919450/2d_hdr_demo.zip)

**Comment by Calinou** [comment] 2022-06-16 14:58
2D rendering in 4.0 is always done in LDR space to improve performance (when HDR isn't needed), so you need to set Bloom above 0.0 to see any effect.

**Comment by MyStarrySpace** [comment] 2022-06-17 00:33
Huh, that's pretty interesting. It seems like bumping up the bloom level isn't doing anything, though. Did you get the glow to work by bumping the bloom value up?

**Comment by Norrox** [comment] 2022-12-22 01:12
> Huh, that's pretty interesting. It seems like bumping up the bloom level isn't doing anything, though. Did you get the glow to work by bumping the bloom value up?

Does not work for me, but i saw @Calinou mentioning rendering 2d in hdr is not available yet
![Skärmbild 2022-12-22 020312](https://user-images.githubusercontent.com/13393087/209033055-12d8150b-28ca-418f-bf2d-b8e69db747eb.png)
![Skärmbild 2022-12-22 020301](https://user-images.githubusercontent.com/13393087/209033062-19bd1e09-7a92-4e0c-ae71-585fdfedc9db.png)

**Comment by Calinou** [comment] 2022-12-22 18:31
> Does not work for me, but i saw @Calinou mentioning rendering 2d in hdr is not available yet

It works if you decrease HDR Threshold below 0.0 (try 0.1) or increase Bloom abvoe 1.0.

**Comment by golddotasksquestions** [comment] 2022-12-22 22:03
I can confirm the issue is still present in Beta9.

@Calinou This is a very severe feature regression compared to Godot3.

Neither is raising Bloom above 0.0 nor lowing the Threshold below 1.0 a solution. Both of these affect the whole viewport.
Using Glow in 2D in Godot is very often (if not by far the most cases) used deliberately on particular objects in the scene. To deliberately make a 2D object glow, the user would modulate that particular object above the 1.0 threshold.

Keeping the Threshold at 1.0 makes a lot of sense if you want to use glow deliberately, because any graphic by be in the 0.0-1.0 range. By modulating only this one graphic ([or only a particular part within that graphic using a shader](https://www.reddit.com/r/godot/comments/zoup7m/comment/j0pw3w8/?utm_source=share&utm_medium=web2x&context=3)) above the LDR threshold, creates a controlled environment. Solving this at the asset level by making sure not to bring in assets which cross a lower than 1.0 threshold is pretty backwards crazy. You would also cut down dynamic range of your assets this way. 

Glow is a modern feature almost no modern game can do without in some form or another, be it 2D or 3D. It would be a shame if using Glow in Godot4 would be even more cumbersome and harder to use than it is in Godot3.

**Comment by Norrox** [comment] 2022-12-24 01:41
> > Does not work for me, but i saw @Calinou mentioning rendering 2d in hdr is not available yet
> 
> It works if you decrease **Glow > HDR Threshold** below 0.0 (try 0.1) or increase Bloom above 1.0. The WorldEnvironment's background mode must also be set to **Canvas**. [godotengine/godot-demo-projects#782](https://github.com/godotengine/godot-demo-projects/pull/782) features two demos with working glow in 2D (Glow in 2D and 2D GPUParticles).

When i do that, the whole color picker glows up like a christmas tree, running beta 10 in linux, have not checked in windows yet, maybe this should be a new bug?
![Screenshot_20221224_023637](https://user-images.githubusercontent.com/13393087/209417071-a8a47f82-b8df-434c-a10a-a56b05e10bb1.png)

**Comment by Calinou** [comment] 2022-12-24 15:32
> When i do that, the whole color picker glows up like a christmas tree, running beta 10 in linux, have not checked in windows yet, maybe this should be a new bug? ![Screenshot_20221224_023637](https://user-images.githubusercontent.com/13393087/209417071-a8a47f82-b8df-434c-a10a-a56b05e10bb1.png)

This is a known issue: https://github.com/godotengine/godot/issues/69122

**Comment by reduz** [comment] 2022-12-25 09:13
This probably deserves a better explanation. What we have as 2D HDR in Godot 3 is not really HDR, as it still mixes color in sRGB space. 
Given HDR displays (and displays with higher contrast) are becoming common place, the idea in Godot 4 is that 2D HDR is actual, true HDR that can be perceived as such. This feature makes it possible to have things such as user interfaces combined with 3D rendering while doing HDR output (which is not possible using the method we use in Godot 3).

Of course, this requires a bit more work and it means that, if HDR is enabled, hint_albedo needs to do the proper conversion of textures from sRGB as well as sRGB happening later. Its a good amount of work and we did not make it to 4.0 because there are so many other things that need to be worked on, so it will happen after its released.

**Comment by golddotasksquestions** [comment] 2023-05-04 14:43
I don't really think it's useful to cover the whole viewport with bloom, but for a [reddit thread](https://www.reddit.com/r/godot/comments/137gruu/how_do_i_implement_2d_glow_in_godot_4/) I just tested WorldEnvironment 2D bloom again in Godot 4.0.2 and apparently not even this is working anymore. Lowering the Threshold will also do exactly nothing.

**Comment by golddotasksquestions** [comment] 2023-05-04 15:33
My bad, bloom still works! (I forgot to change the background mode to Canvas). Also thanks for sharing this workaround!

**Comment by mmMarzban** [comment] 2023-07-07 21:15
I use Compatibility rendering and I don't seem being able to use glow effect any more. (It used to work quite correctly in Godot 3)
Is it because of not having Vulkan? Or is it a bug?

**Comment by Calinou** [comment] 2023-07-07 22:56
> I use Compatibility rendering and I don't seem being able to use glow effect any more. (It used to work quite correctly in Godot 3) Is it because of not having Vulkan? Or is it a bug?

This is a separate issue: https://github.com/godotengine/godot/issues/66455

**Comment by jacob-winkler** [comment] 2023-07-08 16:05
@Calinou in the workaround you posted, when you say something like `the red sprite on the left is not overbright, but the ones on the right are (to varying degrees)` what do you mean by overbright? The modulate values are >1?

**Comment by Calinou** [comment] 2023-07-09 13:20
> what do you mean by overbright? The modulate values are >1?

Yes, "overbright" refers to a pixel where any of the modulate is greater than 1.0 (exclusive).

**Comment by PrecisionRender** [comment] 2023-07-10 03:44
Is there any update on when this will be implemented? Or when it's expected to be? 🤔

**Comment by 3booodpro** [comment] 2023-07-18 07:41
@Calinou @reduz I am so sorry for this mention but its been more than a year and this issue isn't fixed yet, juan did say its going to be fixed after the 4.0 release but and now 4.1.1 got released and still the issue isn't fixed.

Can you guys give us a rough guess when it will be fixed?

**Comment by PrecisionRender** [comment] 2023-07-18 16:41
@3booodpro I pinged them in the development chat.

**Comment by simonschreibt-code** [comment] 2023-08-03 21:35
Just a tiny note: 

The workarounds do work on my PC when:

- I use Forward+ or Mobile Renderer

They do NOT work:

- when I export the game to HTML5/Web
- when I test the game on Android (in Browser via HTML5)
- when I use compatibility renderer (also doesn't work on my PC in this case)

**Comment by Calinou** [comment] 2023-08-03 22:55
> when I test the game in my browser (firefox/chrome) on my PC via HTML5
> when I test the game on Android (in Browser via HTML5)

The web export always uses the Compatibility rendering method, as Vulkan can't run in web browsers.

**Comment by simonschreibt-code** [comment] 2023-08-03 22:56
> The reason this doesn't work when using Compatibility is that there's no glow implementation there.
> 
> > * when I test the game in my browser (firefox/chrome) on my PC via HTML5
> > * when I test the game on Android (in Browser via HTML5)
> 
> The web export always uses the Compatibility rendering method, as Vulkan can't run in web browsers.

Ah! Thank you for the clarification! 
Just for me to know: Is there a plan to add glow to compatibility at some point, or isn't that planned for any future update?

**Comment by Calinou** [comment] 2023-08-03 22:57
> Just for me to know: Is there a plan to add glow to compatibility at some point, or isn't that planned for any future update?

It is planned for a future release, but keep in mind that Compatibility will always render in SDR for performance reasons (also because support for some sRGB/linear formats is spotty on WebGL). This means that when glow is implemented there, it will require you to decrease HDR Threshold below 1.0 to be visible (like you currently need to do with Forward+/Mobile in 2D).

**Closed** 2023-08-08 15:05 UTC
Labels: bug, topic:rendering, confirmed, regression, topic:2d

**Comment by Mupli** [comment] 2023-10-05 16:26
is this fixed? Or no .. This doesn't work in  4.1.1

**Comment by Calinou** [comment] 2023-10-05 16:34
> is this fixed? Or no .. This doesn't work in 4.1.1

As mentioned above, this is only present in 4.2.dev, not 4.1.1.
