### ISSUE TITLE
The font looks bad

### ISSUE THREAD

**Issue by Torguen** [godotengine/godot#46908] opened 2021-03-11 20:37 UTC
**Godot version:**

3.2.4 rc4 mono

**OS/device including version:**

win10 64

**Issue description:**

The font looks flawed (dynamic font).
The project is displaying at half its original resolution.

![Captura2](https://user-images.githubusercontent.com/19652075/110851860-e784e280-82b1-11eb-8114-8aec71a8278c.PNG)

![Captura3](https://user-images.githubusercontent.com/19652075/110851870-ea7fd300-82b1-11eb-831b-ecab854780e2.PNG)

**Steps to reproduce:**

**Minimal reproduction project:**

[juego.zip](https://github.com/godotengine/godot/files/6125837/juego.zip)

**Comment by Calinou** [comment] 2021-03-11 20:43
Duplicate of https://github.com/godotengine/godot/issues/46850 (will be fixed in 3.2.4rc5).

**Closed by Calinou** 2021-03-11 20:43 UTC
