### ISSUE TITLE
MultiMeshInstance3D not showing in play

### ISSUE THREAD

**Issue by Wiggan** [godotengine/godot#73048] opened 2023-02-10 17:10 UTC
### Godot version

4.0 RC1

### System information

Windows10, AMD Ryzen 9 5900X, NVIDIA GeForce RTX 3060 Ti, driver version 30.0.15.1179, forward+.

### Issue description

One of 4 MultiMeshInstance3D instance I had in my scene did not show anything in play. It shows fine in editor and camera preview. I tried changing what mesh to instance, no difference. 
As far as I can tell, there is nothing that is different from this instance compared to the others.

### Steps to reproduce

Load up the project and press play.

### Minimal reproduction project

[MultiMeshInstanceREPEX.zip](https://github.com/godotengine/godot/files/10709665/MultiMeshInstanceREPEX.zip)

**Comment by RedMser** [comment] 2023-02-10 17:34
Can reproduce, very weird bug... Some things I tried (nothing helped understand it though):

- Rename node.
- Create new multimesh node and copy buffer / mesh info across (it renders fine).
- Change which mesh is instanced (it still does not render).
- Copy another multimesh's buffer to the broken multimesh (still doesn't render).
- Delete `.godot` folder.

Maybe needs deeper debugging, but I don't see any reason why this particular node does not work, even if copying / changing all of its properties... 🤯

**Comment by clayjohn** [comment] 2023-02-10 19:32
Funny enough, this is a bug with TAA. Turning off TAA in the test project fixes the issue

**Comment by clayjohn** [comment] 2023-02-10 19:33
Duplicate of https://github.com/godotengine/godot/issues/67287

**Closed by clayjohn** 2023-02-10 19:33 UTC
Labels: bug, topic:rendering, topic:3d
