### ISSUE TITLE
call_deffered("add_node",node) stopped working in Godot 3.2 Stable

### ISSUE THREAD

**Issue by pfagurel** [godotengine/godot#35825] opened 2020-02-01 14:23 UTC
call_deffered("add_node",node) was working in Godot 3.1 Stable. Today i have oppened the project in Godot 3.2 Stable, when executing the game and when it arrives at the call_deffered("add_node",node) code it laggs for +- 2 secs then it stops . Not getting any messages of error : "** Debug Process Stopped **"
Thanks

**Comment by Calinou** [comment] 2020-02-01 17:12
@pfagurel Please upload a minimal reproduction project to make this easier to troubleshoot.

**Comment by pfagurel** [comment] 2020-02-02 13:30
@Calinou Hi, thank you for the reply ! :) I found the problem. When oppening the scene (on which i want to call_deffered("add_n
ode",scene.instance()) ) some the CollisionShape2D get corrupted (?) . 
![godot 3 2](https://user-images.githubusercontent.com/44465840/73608884-6e07c480-45c8-11ea-9e93-97a6f0ff83be.JPG) result in Godot 3.2
![изображение](https://user-images.githubusercontent.com/44465840/73608899-81b32b00-45c8-11ea-8d51-114743b55c53.png) result in Godot 3.1

**Comment by Calinou** [comment] 2020-02-02 16:18
@pfagurel Does this mean you can't reproduce this in any other project?

**Comment by pfagurel** [comment] 2020-02-02 17:32
I've created a new empty Godot 3.2 project, then added a CollisionShape2D with a ConvexPolygonShape2D (shape). I'm getting the same error : " servers/visual/visual_server_canvas.cpp:762 - Condition "pointcount < 3" is true.". So it's not an import/compatibility issue, I think it's a Godot 3.2 issue. Try yourself to do the same and see if you have the same issue.

**Comment by KoBeWi** [comment] 2020-12-21 23:58
Can anyone still reproduce this bug in Godot 3.2.3 or any later release?

If yes, please ensure that an up-to-date Minimal Reproduction Project (MRP) is included in this report (a MRP is a zipped Godot project with the minimal elements necessary to reliably trigger the bug). You can upload ZIP files in an issue comment with a drag and drop.

**Comment by Xrayez** [comment] 2021-02-12 18:04
Without Minimal Reproduction Project, it's difficult to understand the problem, so I don't know how to reproduce the issue.

`servers/visual/visual_server_canvas.cpp:762 - Condition "pointcount < 3" is true` come from attempting to render polygons decomposed from collision shapes in the editor.

**Comment by KoBeWi** [comment] 2021-02-12 18:44
Closing due to lack of update. Please comment if you can still reproduce this issue in the latest stable version of Godot.

**Closed by KoBeWi** 2021-02-12 18:44 UTC
Labels: bug, crash, topic:core
