### ISSUE TITLE
Godot is not building

### ISSUE THREAD

**Issue by Mintormo** [godotengine/godot#24668] opened 2018-12-30 16:09 UTC
**Godot version:**
3.1.custom_build 
commit fb9085a

**OS/device including version:**
Win 7x64, Ubuntu

**Issue description:**
Godot is crashed on building with MSVC++ 2017 (Win 7x64).
With Linux the same.

**Steps to reproduce:**
1. Build godot

![crash](https://user-images.githubusercontent.com/2286710/50548963-3bbdc200-0c66-11e9-835c-399acc83335a.png)

**Comment by volzhs** [comment] 2018-12-30 16:35
duplicate of #24507
you need to delete *.gen.cpp files.

from https://github.com/godotengine/godot/issues/24507#issuecomment-449315336
this `git clean -x -f -q` will help too.

**Closed** 2018-12-30 16:35 UTC
