### ISSUE TITLE
AnimationPlayer should be able to interpolate vec4 shader parameters and plane

### ISSUE THREAD

**Issue by mrcdk** [godotengine/godot#11426] opened 2017-09-19 21:49 UTC
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Master 67aa409f596515894fa855492a31976a3044381c

**Issue description:**

AnimationPlayer can't interpolate between two vec4 values because they are a `Variant` `PLANE` type and this type doesn't have an interpolate function here:

https://github.com/godotengine/godot/blob/master/core/variant_op.cpp#L3103-L3105

**Steps to reproduce:**
See attached example.

**Link to minimal example project:**

[animplayer_shader_vec4.zip](https://github.com/godotengine/godot/files/1315965/animplayer_shader_vec4.zip)

**Comment by hpvb** [comment] 2017-09-19 22:47
This would be easy to add but I don't know if the problem is that the animplayer lets you try or if the problem is that Plane doesn't have an interpolate.

Or perhaps if Plane needs some kind of alias which has an interpolate function.

@reduz @akien-mga @karroffel @bojidar-bg any ideas on what is the 'right thing' here?

**Comment by reduz** [comment] 2017-09-19 22:49
If you export vec4 as color it should..

**Comment by mrcdk** [comment] 2017-09-19 22:56
@reduz this is the shader code from that sample:

```glsl
shader_type canvas_item;

uniform vec4 color:color;

void fragment() {
	COLOR = vec4(color.rgb, texture(TEXTURE, UV).a * color.a);
}
```

Not sure if that's how you export the vec4 as a color or not. I saw an example here https://godotengine.org/article/making-shaders-more-accessible

Still, I think vec4 values should be able to be animated via the AnimationPlayer. I tested vec2 and vec3 and they were being animated.

**Comment by bojidar-bg** [comment] 2017-09-20 10:07
@hpvb IMO, Plane should be interpolateable as well.

**Comment by akien-mga** [comment] 2020-09-04 12:33
The proper hint is `hint_color`, not `color`:
```
uniform vec4 color : hint_color;
```

This then works just fine in 3.2:
![Screenshot_20200904_142850](https://user-images.githubusercontent.com/4701338/92239244-f5008080-eeba-11ea-9171-c5fe360c8e43.png)

`Plane` interpolation could be implemented, but it's completely tangential to what was requested here as a Plane is not a `vec4`, and interpolating between two planes is not the same as a linear interpolation of all four components (as was needed here and is done for `Color`).

See https://stackoverflow.com/questions/57790232/precise-linear-interpolation-between-two-3d-planes

I'll close this as the original use case is handled by the hint.

Plane interpolation could be implemented if there's a use case for it. It should likely be requested through https://github.com/godotengine/godot-proposals (note that there are various other types in `Variant::interpolate` for which no interpolation is performed.

**Closed by akien-mga** 2020-09-04 12:33 UTC
Labels: enhancement, topic:core
