### ISSUE TITLE
Incorrect Color output for visual server

### ISSUE THREAD

**Issue by Variable-ind** [godotengine/godot#56248] opened 2021-12-26 12:24 UTC
### Godot version

3.4.2 stable

### System information

Linux Mint 20.2 Cinnamon, Opengl used: GLES2, Graphics: Intel Corporation 2nd Generation Core Processor Family Integrated Graphics Controller

### Issue description

There seems to be a bug regarding VisualServer that if the input texture has alpha value less than 255 by a given percentage (say 50%) then even if nothing's being done, the (RGB) values of the texture obtained by `VisualServer.texture_get_data()` would also get decreased by the same percentage (in this case 50%) of their original values

The example project tests the outputs of given colored input images

[Youtube Link](https://youtu.be/IuHUq7J0sDA) cause for some reason it wasn't uploading here

### Steps to reproduce

Given in example project

### Minimal reproduction project

[VisualServer bug.zip](https://github.com/godotengine/godot/files/7776962/VisualServer.bug.zip)

**Comment by Calinou** [comment] 2021-12-26 15:55
Duplicate of https://github.com/godotengine/godot/issues/17574.

**Closed by Calinou** 2021-12-26 15:55 UTC
Labels: topic:rendering
