### ISSUE TITLE
RichTextLabel wrapping is not working if set the Visible Characters property

### ISSUE THREAD

**Issue by ippan** [godotengine/godot#16821] opened 2018-02-19 14:16 UTC
**Godot version:**
d5eba83fd57005c110ef594f90c84016b758a0d5

**OS/device including version:**
macOS 10.13.3

**Issue description:**
RichTextLabel wrapping is not working if set the Visible Characters property

**Steps to reproduce:**

1. Create a RichTextLabel
2. Set RichTextLabel's Text to "Test, Test, Test, Test, Test, Test, Test, Test, Test"
3. Wrapping is working now.
4. Set RichTextLabel's Visible Characters to 40
5. Wrapping is not working now.

**Minimal reproduction project:**

**Comment by ret80** [comment] 2018-02-21 19:48
Godot version:
612ab4b
OS/device including version:
win 10

I couldn't reproduce it. Everything works as it should. Please check again.

**Comment by ippan** [comment] 2018-02-22 04:34
# Godot version:
24cd4fe (2 commits after 612ab4b)

# OS/device including version:
macOS 10.13.3

# Issue description:
stilling not working

![Visible Character = -1](https://user-images.githubusercontent.com/2070604/36520562-a6b26ad2-17cc-11e8-881d-30593db66a87.png)
![Visible Character = 40](https://user-images.githubusercontent.com/2070604/36520566-a9485ed2-17cc-11e8-91a3-6975dd80e144.png)

# Minimal reproduction project:
[TestRichText.zip](https://github.com/godotengine/godot/files/1746637/TestRichText.zip)

**Comment by afftor** [comment] 2018-03-03 01:56
Can confirm it. Problem appeared exactly in 3.0.1.

**Comment by hpvb** [comment] 2018-03-03 02:17
This was fixed in 0e1e95c41f02acd5ed5c347ff63d0e38185525ad (will be in 3.0.2)
![screenshot from 2018-03-03 03-17-28](https://user-images.githubusercontent.com/2591099/36929483-69af4742-1e91-11e8-9e90-85f1bc9fe032.png)

**Closed by hpvb** 2018-03-03 02:17 UTC
Labels: bug, topic:core
