### ISSUE TITLE
TileMap 2D renders error around the y-axis

### ISSUE THREAD

**Issue by clapik** [godotengine/godot#69818] opened 2022-12-09 18:03 UTC
### Godot version

4.0 beta 7

### System information

Windows 11, Ubuntu

### Issue description

When using 2D TileMap, the edges are rendered incorrectly around the y-axis.
![image](https://user-images.githubusercontent.com/3974885/206764817-619552f2-af78-45b5-b6da-9b9c5f5bf681.png)

### Steps to reproduce

Create a 2D TileMap with according TileSet

Paint the tile.

### Minimal reproduction project

[TileMapBug.zip](https://github.com/godotengine/godot/files/10197057/TileMapBug.zip)

**Comment by groud** [comment] 2022-12-09 19:00
Duplicate of https://github.com/godotengine/godot/issues/69818. See my answer there.

**Closed by groud** 2022-12-09 19:00 UTC
Labels: bug, topic:rendering, topic:2d

**Comment by clapik** [comment] 2022-12-10 14:52
@groud May you re-link the issue? I think #69818 is _this_ issue. Thanks!

**Comment by groud** [comment] 2022-12-10 15:06
Ah sorry, I edited the link.
