### ISSUE TITLE
Control Left-Click

### ISSUE THREAD

**Issue by SoapSpangledGames** [godotengine/godot#100796] opened 2024-12-25 02:51 UTC
### Tested versions

4.4-dev7

### System information

Godot v4.4.dev7 - Ubuntu 20.04.6 LTS (Focal Fossa) on X11 - X11 display driver, Single-window, 3 monitors - OpenGL 3 (Compatibility) - NVIDIA GeForce GTX 1660 (nvidia; 470.256.02) - AMD FX(tm)-8350 Eight-Core Processor (8 threads)

### Issue description

When holding down the left control key and left-clicking the mouse on a called function, sometimes it takes me to the function, and sometimes it takes me to the documentation for the function. I haven't found the rhyme or reason. This should behave consistently.

In previous versions, this always takes me to the function definition.

### Steps to reproduce

Hold down the left control key while the cursor is hovering over a function to be called, and left-click the mouse. Then do the same for different called functions. The behavior is erratic.

### Minimal reproduction project (MRP)

N/A

**Comment by tetrapod00** [comment] 2024-12-25 03:00
Thanks for reporting! This is a duplicate of https://github.com/godotengine/godot/issues/100680, which is already fixed by https://github.com/godotengine/godot/pull/100707

**Closed by tetrapod00** 2024-12-25 03:00 UTC
