### ISSUE TITLE
Add tool internal variables in gdscript

### ISSUE THREAD

**Issue by credman0** [godotengine/godot#29090] opened 2019-05-21 21:54 UTC
It would be useful to have a variable that tools can use to track state that can change from within the editor. For example:

```var counter = 0
func _enter_tree():
    counter+=1
```

_enter_tree will be called once by the editor, and then once by the game. But counter will be reset to 0 when the game is run. A flawed workaround does exist using export, ie

```
export var counter = 0
func _enter_tree():
    counter+=1
```

but this causes the variable to be editable from within the editor's Inspector, which is not ideal for a variable meant to track the internal state of the node. I request something like maybe this:

```
export (null) var counter = 0
func _enter_tree():
    counter+=1
```

which prevents the variable from appearing in the Inspector.

**Comment by 2shady4u** [comment] 2019-05-24 16:37
How about using `Engine.is_editor_hint()` to distinguish between counter updates?
I think it is really unintuitive to have an export variable that is NOT appearing in the editor sidebar....

This is a duplicate of this btw:
https://github.com/godotengine/godot/issues/5988

**Comment by KoBeWi** [comment] 2019-05-24 16:50
Closing as duplicate of #5988

**Closed by KoBeWi** 2019-05-24 16:50 UTC
