### ISSUE TITLE
Renaming a folder in the editor that contains an scene that its being instanced by another scene can cause the parent scene to corrupt and not open

### ISSUE THREAD

**Issue by wokeraccoon** [godotengine/godot#70272] opened 2022-12-18 20:08 UTC
### Godot version

v4.0.beta8.official [45cac42c0]

### System information

Fedora Linux 37, Windows 11

### Issue description

When renaming a folder inside the editor (not in the OS File Manager) than contains a scene that it's currently being instanced by another scene, the parent scene will be unable to be opened. The editor currently shows this alert when trying to open the scene:

![image](https://user-images.githubusercontent.com/13603525/208316599-96f22a04-2637-4d0a-8703-6d879aba0597.png)

While the console will show this:
`scene/resources/resource_format_text.cpp:514 - res://main.tscn:4 - Parse Error:`
`Failed loading resource: res://main.tscn. Make sure resources have been imported by opening the project in the editor at least once.`

This error appeared while running Godot 4 under Fedora Linux and Windows 11

Attempted steps to fix the broken scene:

- Renaming the folder in the editor back to its original name won't fix it
- Renaming the folder in the OS File Manager won't fix it
- Using the `Edit Dependencies` option while right clicking the parent scene and reselecting the instanced scene won't fix it
- Deleting the `.godot` folder won't fix it

### Steps to reproduce

1. Create a scene anywhere on the project tree (Let's call it `parent.tscn`)
2. Create a folder and create another scene inside of it (for example, `child.tscn`)
3. Open `parent.tscn` and instanciate `child.tscn` to it. Save the scene.
4. Rename the folder where `child.tscn` is located. `parent.tscn` will close and show an error about being unable to open it.
5. Try to open `parent.tscn` through the FileSystem tab, it will show the same error
6. Rename the folder where `child.tscn` is located back to it's original name and try to reopen `parent.tscn`, it will show the same error again

### Minimal reproduction project

[test-bug.zip](https://github.com/godotengine/godot/files/10254543/test-bug.zip)

This project has the corrupted `parent.tscn` scene. It has been tested on different OS in different machines showing the same issues.

**Comment by rcjsuen** [comment] 2022-12-18 20:25
Is this the same issue as #69794?

**Comment by akien-mga** [comment] 2022-12-18 20:34
Indeed, duplicate of #69794

**Closed by akien-mga** 2022-12-18 20:34 UTC
