### ISSUE TITLE
Show in FileSystem no longer works

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#33748] opened 2019-11-19 20:11 UTC
**Godot version:**
cc3b7d2ee

**Steps to reproduce:**
1. Open a scene
2. Right-click its tab
3. Show in FileSystem
4. It doesn't show

Path is filled with filename and everything folds.
![image](https://user-images.githubusercontent.com/2223172/69182307-038ad080-0b11-11ea-944c-44f62b41fd9f.png)

**Comment by KoBeWi** [comment] 2019-11-19 20:13
When you cancel search while file is selected, the directory isn't kept unfolded like it used to. It might be the cause.
![RoAWgJ2So8](https://user-images.githubusercontent.com/2223172/69182462-59f80f00-0b11-11ea-8e87-94093c27da4a.gif)

**Comment by akien-mga** [comment] 2019-11-19 21:54
It's a duplicate of a recent issue (on phone, can't check right now).

**Comment by Calinou** [comment] 2019-11-19 23:11
Duplicate of #33590.

**Closed by Calinou** 2019-11-19 23:11 UTC
Labels: bug, regression, topic:editor
