### ISSUE TITLE
Vulkan: Occlusion/Shadows on 2D Tilemap not working after change_scene(...) (Godot 4.0-alpha15)

### ISSUE THREAD

**Issue by stats** [godotengine/godot#65572] opened 2022-09-09 12:55 UTC
### Godot version

4.0-alpha15

### System information

Windows 10

### Issue description

Occlusion and shadows work when viewing a scene directly using the play scene (F6) option. Or when the scene is set as the main scene.

<img width="264" alt="image" src="https://user-images.githubusercontent.com/786312/189337510-f49cb4aa-eec2-4707-86bc-63d43c5ba0ed.png">

When change to the scene using get_tree().change_tree(...) occlusion and shadows do not work.

<img width="257" alt="image" src="https://user-images.githubusercontent.com/786312/189350162-e486ef6c-bc73-40e0-8ef1-b716e0700683.png">

I confirmed that this does work correctly in 3.5-stable using a similar test project with a Light2D instead of the PointLight2D which is used in 4.0.

### Steps to reproduce

Use the attached project. 

1. Play the project.
2. Press the "Change to Occlusion Scene" button

### Minimal reproduction project

https://github.com/stats/occlusion-test-godot-4/

[OcclusionTest.zip](https://github.com/godotengine/godot/files/9534895/OcclusionTest.zip)

**Comment by Trashtalk217** [comment] 2022-09-09 21:50
I've been able to reproduce this problem on Linux and I'm going to investigate it further.

**Comment by stats** [comment] 2022-09-13 17:14
Confirmed that this is still not working as expected on windows10 in alpha17.

**Comment by Trashtalk217** [comment] 2022-09-13 22:33
I've done some exploration, and while I haven't figured it out, this might help the next person looking at it.
I've got two projects to contrast and compare, when it works and when it doesn't, see attached.

When the occlusion works, `call_deferred(SNAME("_update_dirty_quadrants"));` is called twice in `tile_map.cpp` and when it doesn't work, `call_deferred(SNAME("_update_dirty_quadrants"));` is only called once.

[OcclusionTest_works.zip](https://github.com/godotengine/godot/files/9561208/OcclusionTest_works.zip)
[OcclusionTest_fails.zip](https://github.com/godotengine/godot/files/9561207/OcclusionTest_fails.zip)

**Comment by Trashtalk217** [comment] 2022-09-23 21:37
I've attempted to fix this issue, but I must admit that I couldn't. So I invite others to take a further look at it.

**Comment by Trashtalk217** [comment] 2022-09-23 23:46
I've tested the latest commit f74491fde and the issue still persists. With the new tile system it did take on a new interesting form:

![image](https://user-images.githubusercontent.com/24552941/192069759-2bed7da9-d11e-4cd0-bb02-84ebd893b09c.png)

The shadows are slightly too far to the left. It's supposed to look like this:

![image](https://user-images.githubusercontent.com/24552941/192069973-615d5605-6e38-4690-8fab-9bbad7cdc9ad.png)

Here's an example project:
[OcclusionTest_fails.zip](https://github.com/godotengine/godot/files/9637517/OcclusionTest_fails.zip)

**Comment by MewPurPur** [comment] 2022-09-30 17:37
Confirmed in beta 2. I believe the issue existed as far back as the pre-alphas, though I've not bisected it. Might have just been there since the new tilemaps were merged.

**Comment by MewPurPur** [comment] 2022-10-02 22:19
Workaround (and a hint at what might be wrong): Setting `quadrant_size` to 1 fixes this.

**Closed** 2022-10-06 15:10 UTC
Labels: bug, topic:rendering, confirmed, topic:2d
