### ISSUE TITLE
Nonexistent signal: changed when saving/instancing StaticBody2D

### ISSUE THREAD

**Issue by Araken** [godotengine/godot#20574] opened 2018-07-29 15:31 UTC
**Godot version:**
Master, 07129deaeb767528e550344e1134f2739c89bdd0

**OS/device including version:**
Windows 10 64bit

**Issue description:**
Godot prints "Nonexistent signal: changed" each time a scene with StaticBody2D is saved in editor or instanced in game.

**Steps to reproduce:**
Create a new scene, add StaticBody2D, save the scene.

**Comment by Ace-Dragon** [comment] 2018-07-29 17:36
This happens a lot with games using the 3D nodes as well. The same prints also occur with nearly all of the Godot demo projects.

**Comment by mysticfall** [comment] 2018-08-04 01:47
This looks to be a duplicate of #20521.

**Comment by akien-mga** [comment] 2018-08-13 11:05
Assuming fixed by #20381.

**Closed by akien-mga** 2018-08-13 11:05 UTC
Labels: bug, topic:physics
