### ISSUE TITLE
turn scene crash.

### ISSUE THREAD

**Issue by zszen** [godotengine/godot#30094] opened 2019-06-26 17:06 UTC
**Godot version:**
3.1.1

**OS/device including version:**
mac 10.14.4

**Issue description:**
turn another scene crash.

**Steps to reproduce:**
1. reactive from background.
2. click the deactive scene.
3. show a scene loading panel.
4. crash when two seconds. (immediately disapear. not stack at there.)

[turn scene crash.log](https://github.com/godotengine/godot/files/3331165/turn.scene.crash.log)

**Comment by KoBeWi** [comment] 2019-06-27 16:53
This sounds similar to #28228, but has different log.

**Comment by zszen** [comment] 2019-06-27 19:58
@KoBeWi maybe cause by memory lack.

**Comment by Calinou** [comment] 2020-07-19 19:54
@zszen Can you (or anyone else) still reproduce this bug in Godot 3.2.2 or any later release?

If yes, please ensure that an up-to-date Minimal Reproduction Project (MRP) is included in this report (a MRP is a zipped Godot project with the minimal elements necessary to reliably trigger the bug). You can upload ZIP files in an issue comment with a drag and drop.

**Comment by KoBeWi** [comment] 2020-09-28 16:40
Closing due to lack of update. Please comment if you can still reproduce this issue in the latest stable version of Godot.

**Closed by KoBeWi** 2020-09-28 16:40 UTC
Labels: bug, crash
