### ISSUE TITLE
Menus need a click to close before being able to open the next one

### ISSUE THREAD

**Issue by mhilbrunner** [godotengine/godot#15939] opened 2018-01-21 12:02 UTC
**Godot version:**
Current master (https://github.com/godotengine/godot/commit/fa569210f5ef316177724169a42d2b82f4ab03d9)

**OS/device including version:**
Windows 7 x64

**Issue description:**
Currently, Menus function the following way:
- Click on menu (e.g. "Scene")
- Click somewhere else to close
- Click on next menu (e.g. "Project")

If you click on "Project" directly while another menu is open, only the current menu is closed, the "Project" menu isn't opened. This feels very clunky and alien, as most native menus behave in the following way:

- Click on menu (e.g. "Scene")
- Move cursor to next menu or click on next menu, current menu closes, next one is opened

E.g. in Explorer, Firefox, really most any app I could find works the above way, not the way Godot's menus work.

**Comment by stephdin** [comment] 2018-01-21 17:38
This issue was already reported in #11692

**Comment by vnen** [comment] 2018-01-21 17:41
Closing as duplicate of #11692.

This is not a "bug" per se, it was designed this way (but can be changed).

**Closed by vnen** 2018-01-21 17:41 UTC
Labels: bug, topic:editor, usability
