### ISSUE TITLE
bottom pannel can disapear 

### ISSUE THREAD

**Issue by mieldepoche** [godotengine/godot#80746] opened 2023-08-18 06:34 UTC
### Godot version

4.1

### System information

linux

### Issue description

I can't reproduce this, but it happened a few times already.
Sometimes the bottom pannel disapears.

Closing the scene dock window fixed it in this particular case.

![image](https://github.com/godotengine/godot/assets/71937306/243a61d8-d26b-4ad4-bf10-b7bfc4abc45d)

### Steps to reproduce

idk

### Minimal reproduction project

none

**Comment by kitbdev** [comment] 2024-02-02 03:38
This was probably caused by loading layouts in distraction free mode. 
It was fixed in https://github.com/godotengine/godot/pull/84122

**Closed** 2024-02-02 10:41 UTC
Labels: bug, topic:editor, needs testing
