### ISSUE TITLE
Annoying space between objects and floor

### ISSUE THREAD

**Issue by siamak-s** [godotengine/godot#30861] opened 2019-07-27 07:29 UTC
**Godot version:**
Godot Engine v3.1.1.stable.offical

**OS/device including version:**
Windows 10/NVidia Geforce GTX 950M

**Issue description:**
An annoying space between objects and floor. It seems that objects are floating on the air.

**Steps to reproduce:**

- Create a cube mesh as ground and convert it to a Static Body with ConvexPolygonShape
- Create a cube mesh as object and convert it to RigidBody with ConvexPolygonShape
- Move cube mesh upper than ground and let it fall
- After falling you should see an annoying space between object and ground

**Minimal reproduction project:**
[https://drive.google.com/open?id=1c1iP_rovpRpzOm9Nne89iPk3YdABZgBQ](url)

**Comment by homer666** [comment] 2019-07-27 08:08
If you set a shape's margin to something really low (say, 0.001), the space should be eliminated.

![image](https://user-images.githubusercontent.com/27100585/61991830-162c5600-b099-11e9-8301-c6ce0d590028.png)

![image](https://user-images.githubusercontent.com/27100585/61991814-f5fc9700-b098-11e9-82c3-51b34a2bd81b.png)

You'll have to do this for every shape of every body; I don't think there's a way to change them globally. There was some reason for why the default margin value is what it is, but I can't remember it.

**Comment by TheDuriel** [comment] 2019-07-27 13:47
The core principles behind Godot physics prohibit colliders from ending a frame in a colliding state. This is the minimum seperation distance. If you make it too low, it will break things.

**Comment by siamak-s** [comment] 2019-07-27 15:05
I confirm that changing margin property eliminate space, but it effects on bouncing of objects (specially bouncing behavior of cone completely change), I don't know which bounce effect is more real and how margin effect on this behavior. Is that correct to change the margin property with this situations?

**Comment by siamak-s** [comment] 2019-07-27 15:09
> 
> 
> The core principles behind Godot physics prohibit colliders from ending a frame in a colliding state. This is the minimum seperation distance. If you make it too low, it will break things.
What's your meaning of the minimum seperation distance? 0.04 default value or 0.001 minimum value?
So what's your idea about this space between objects and floor?

**Comment by TheDuriel** [comment] 2019-07-27 18:03
0.04, leave it there. The space should be small enough to not be noticeable in nearly all cases. Worst case scenario you make the colliders slightly smaller than the mesh.

**Comment by madmiraal** [comment] 2020-07-05 18:25
This is actually a duplicate of #27427.

**Closed by madmiraal** 2020-07-05 18:25 UTC
Labels: discussion, topic:physics
