### ISSUE TITLE
Ctrl shortcuts no longer work in editor after an error is raised

### ISSUE THREAD

**Issue by grevius5** [godotengine/godot#17830] opened 2018-03-28 19:47 UTC
**Godot version:**
3.0 >

**OS/device including version:**
Windows 10 64 bit

**Issue description:**
After some work the editor doesn't recognise key combination with ctrl. (ctrl+c, ctrl+v, ctrl+s etc)

**Steps to reproduce:**
I don't know how to reproducing, it's like casual problem after any of this key combination.
After closing and reopening godot work for some time and then the problem reappear.
EDIT: it seems to fail recognising ctrl after the ide show you an error (red background on line with error)

**Comment by girng** [comment] 2018-03-29 01:18
> EDIT: it seems to fail recognising ctrl after the ide show you an error (red background on line with error)

what's the error   it gives before it the ctrl shortcuts stop?

**Comment by justinluk** [comment] 2018-03-29 03:52
I've experienced this as well. I'm also not sure what causes it. If it happens again, I'll check the engine output for an error.

**Comment by grevius5** [comment] 2018-03-29 17:43
@girng i have no erro in the console

**Comment by erjseals** [comment] 2019-11-23 00:43
Has this issue been resolved?

**Comment by KoBeWi** [comment] 2020-11-04 23:41
Closing due to lack of update. Please comment if you can still reproduce this issue in the latest stable version of Godot.

**Closed by KoBeWi** 2020-11-04 23:41 UTC
Labels: bug, topic:editor
