### ISSUE TITLE
Spurious warning on array with implicit empty initialization `The variable "my_array" was used but never assigned a value.`

### ISSUE THREAD

**Issue by hsandt** [godotengine/godot#80818] opened 2023-08-20 13:16 UTC
### Godot version

v4.1.1.stable.official [bd6af8e0e]

### System information

Godot v4.1.1.stable - Ubuntu 22.04.3 LTS 22.04 - Vulkan (Compatibility) - Mesa Intel(R) HD Graphics 4600 (HSW GT2) () - Intel(R) Core(TM) i7-4710HQ CPU @ 2.50GHz (8 Threads)

### Issue description

I often declare arrays (generic of strongly typed) with no explicit initialization value, counting on the default empty array initialization.

Then I fill the array, e.g. calling `push_back` with some value in a loop, and use/return the array.

This causes a spurious warning:

> The variable "my_array" was used but never assigned a value.   <GDScript Error>UNASSIGNED_VARIABLE

Either we shouldn't rely on array empty initialization and explicitly write `var my_array: Array[Type] = []` each time, but then the warning/error messages should go this way; or the empty initialization is reliable and there should not be a warning.

### Steps to reproduce

1. Insert this code in some script:

```gd
func create_array() -> Array[Vector2i]:
	var my_array: Array[Vector2i]

	# optional
	for i in range(5):
		my_array.push_back(i)

	return my_array
```

2. Observe code editor warnings

### Minimal reproduction project

N/A

**Comment by AThousandShips** [comment] 2023-08-20 13:26
Duplicate of #79488

**Closed by AThousandShips** 2023-08-20 13:26 UTC
