### ISSUE TITLE
4.1-dev4 crashes before showing project list

### ISSUE THREAD

**Issue by Damnae** [godotengine/godot#77805] opened 2023-06-03 13:11 UTC
### Godot version

4.1.dev4.mono.official.5c2295ff5

### System information

Windows 10, amd cpu, vulkan

### Issue description

Editor opens to a blank window and crashes before it even shows its project list.

I have no problem running Godot 4.0.3. 
I tried deleting the Godot folder in AppData; 4.1 dev 4 remade some folders with nothing in it before crashing.
I cannot find any crash log, this is all I managed to get:

![2023060357847093](https://github.com/godotengine/godot/assets/1622683/50707371-7cba-44d5-832e-5568244dd032)

### Steps to reproduce

Open Godot_v4.1-dev4_mono_win64.exe or Godot_v4.1-dev4_mono_win64_console.exe in any way.

### Minimal reproduction project

---

**Comment by Zireael07** [comment] 2023-06-03 13:12
Try using --vulkan switch or drag and dropping project file onto Godot icon. (If it helps ,it's a dupe of another issue)

**Comment by clayjohn** [comment] 2023-06-03 13:16
Duplicate of https://github.com/godotengine/godot/issues/77760

**Closed by clayjohn** 2023-06-03 13:16 UTC
