### ISSUE TITLE
Opening project in macOS (Apple Silicon)  will change all texture .import files if project was last opened in Windows or vice versa.

### ISSUE THREAD

**Issue by WindyDarian** [godotengine/godot#74967] opened 2023-03-16 01:07 UTC
### Godot version

4.0 stable

### System information

Windows 11, macOS 16

### Issue description

When collaborating between Windows and macOS, all .import will be changed due to texture import format is different across systems. This makes version control with the team using different operating system hard with these unnecessary changes.

Enabling import of both `ETC2_ASTC` and `S3TC_BPTC`  doesn't help much. Because different platforms have different editor defaults, causing the `project.godot` to change - one line gets removed each time when opening in different OS due to it being default value on that OS. I have a workaround in https://github.com/WindyDarian/godot/commit/87cce4cacfe79dde6c30a82d4d597e1c21f30205  , with setting both to true in project file, but that still means importing both formats for both OS, that's not great.

Ideally, I think .import file shouldn't be changed when project is opened in in different operating system. (macOS should still use ETC2_ASTC while on Windows `S3TC_BPTC`, of course, but all relevant information should only be in .godot folder that is not version controlled)

### Steps to reproduce

1. extract the repro project, keep a copy of `white.png.import`
2. open the project on macOS with Apple Silicon with Godot 4.0
3. note that `white.png.import` changed

### Minimal reproduction project

[godot_project_with_a_texture.zip](https://github.com/godotengine/godot/files/10985705/godot_project_with_a_texture.zip)

**Comment by clayjohn** [comment] 2023-03-16 03:26
Duplicate of https://github.com/godotengine/godot/issues/74609 Please continue the discussion there

**Closed by clayjohn** 2023-03-16 03:26 UTC
Labels: bug, topic:editor, topic:import
