### ISSUE TITLE
Enet disconnects when android app is put into background.

### ISSUE THREAD

**Issue by derac** [godotengine/godot#36583] opened 2020-02-26 23:06 UTC
**Godot version:**
3.2 / all

**OS/device including version:**
OnePlus 6 running Android 10 / OxygenOS 10.3.1

**Issue description:**
When a player on an Android device unfocuses the app, they will disconnect from the server after a short period of time, ruining the game for all other players. This seems to be an issue that would come up commonly for games which take a long time or involve many players. The game I'm working on is for 4+ players, so if any android player changes focus or puts their phone to sleep, the whole game is ruined.

This appears to be a limitation of Android and probably iOS as well. I'm wondering if there is any way to work around the issue besides implementing a server logic to pause for all players when the player loses focus, then checking to see if they are still connecting after regaining focus, then reconnecting and resyncing data if they are not connected to the server. This is much worse and potentially unrecoverable if the player is the server.

**Steps to reproduce:**
Create an Enet server and connect to it on Android. Put the app in the background on the Android device, and it will disconnect from the server after ~30 seconds.

**Minimal reproduction project:**
Any networked project
https://github.com/der-ac/Art-Party

**Comment by Calinou** [comment] 2020-02-27 09:52
How do other game engines work around this?

**Comment by henriquelalves** [comment] 2020-03-10 17:37
I'm currently using the (now deprecated) Unity UNET wrapper library for my daily job, which I believe is very similar to ENET; this issue seems to be the default behaviour of the library caused by the system OS, and I don't think it's solvable engine-wise. Our game runs on a remote game room, so all the server logic runs on it and we had to implement the disconnect/reconnect behaviour, since UNET is pretty much only a middleware to the network layer.

Since Godot abstracts ENET to a high level multiplayer framework, it maybe could fall in a default behaviour of trying to reconnect whenever the connection is lost, but my experience with this is that sometimes even Android and iOS solutions must be different thanks to how sockets are allocated/deallocated in the device (in some cases we had to "destroy" a connection and create a new one, because UNET would keep a hostId of an unreachable connection).

**Comment by pederbacher** [comment] 2020-04-19 19:35
I have now the same issue. Developing a game as a hobby and learn while doing it. There are a lot of permissions to set when exporting the .apk for Android. Could some permission actually enable the app to keep the connection?

Otherwise I guess the only possibility is to lock the game for all if any peer disconnect, and implement a reconnect, I haven't yet tried. Further, if the server stops, then it must be able to restart and all peers reconnect again... actually, if the server stops and cannot start again (maybe battery is out), then another player should be able to restart as server and continue the game...

Args, hope there is a simple way to make this robust...

**Comment by derac** [comment] 2020-04-19 22:09
Yeah, you'll have to implement reconnect logic.

**Comment by jonbonazza** [comment] 2020-10-15 04:23
So currently, enet network polling happens on the main godot thread in _process. When an android app is put in the bg, this process thread stops running (which makes sense. Godot is an application not a service so it is paused when put in the bg like all other non-service apps). The problem is that if the server does not hear from the client within the configured timeout (currently 30s, but mostly irrelevant in this particular case), the server will assume the client is dead and it will be disconnected. 

In the case of android, there isn't a truly good way around this. We currently have two options that I can think of:

1. Make the network polling happen in a separare Service comoonent that the game Applicatiom talks to. This complicates the Android app design significantly and is quite hacky imo. 
2. Handle reconnections when the app is unpaused ("paused" is what android refers to apps that are in the bg but still fullly loaded in memory, ready to become active again when needed. Technically it can also be in the bg but mostly shutdown and unloaded from memory, but to get to this state it still needs to go through the paused atatw first and likewise, will still be "unpaused" before being moced to the foreground as the active app). Ideally this would be handled automatically by the android godot platform implementation, but I believe there does exist a way to hook into this unpaused even from script, so it _could_ be implemented by the user as a workaroynd in the interim.

**Comment by golddotasksquestions** [comment] 2021-03-01 21:15
I have the same problem. 
I made an cross platform multiplayer app (with the pong demo as basis), connecting a desktop export of the app to the android client. Both clients are identical, exported from the same Godot project, besides minor Input differences I solve using OS.has_feature().

When the android app is in the background, after a while (10 to 50 seconds) the desktop app crashes. I then have to restart _both_ the desktop and the android client. Calling this an annoyance is an understatement.

**Comment by Calinou** [comment] 2021-03-01 23:01
@golddotasksquestions Customizing the timeout was added in https://github.com/godotengine/godot/pull/46470, which will be available in the next 3.2.4 RC or release.

**Comment by mhilbrunner** [comment] 2022-01-14 03:01
Closing as partly addressed by https://github.com/godotengine/godot/pull/46470 and in favor of https://github.com/godotengine/godot-proposals/issues/3347 - discussion would likely be best in that proposal, and as long as there is not enough support and it's not implemented, there is not much we can do here.

Increasing the timeout may help, as will considering alternative networking approaches (depending on your game, something more akin to Firebase or even using separate HTTP calls instead of an ongoing connection).

**Closed by mhilbrunner** 2022-01-14 03:01 UTC
Labels: discussion, platform:android, documentation, topic:network
