### ISSUE TITLE
TextureRect's position in editor correct while wrong in game

### ISSUE THREAD

**Issue by iwoithe** [godotengine/godot#70189] opened 2022-12-17 10:50 UTC
### Godot version

4.0 Beta.6

### System information

Windows 10

### Issue description

*Edit: after exporting [Escape](https://github.com/iwoithe/Escape.git) (same Godot version as listed), I have found that this issue occurs with Windows 10 build but does **not** occur in the HTML5 and Linux builds*

*Another edit: it appears this may be a Windows related issue, however I am not able to check this*

The position of the `TextureRects`s are correct inside of the editor, however, the position is wrong in the running game.

https://user-images.githubusercontent.com/73422868/208237779-cc00555f-b3dd-451d-9999-84b61dbff643.mp4

The remote node tree view does not show anything that appears wrong.

https://user-images.githubusercontent.com/73422868/208237817-d37b1359-8db7-40b0-bff6-e242451c3a88.mp4

Also note that this applies to any `TextureRect`, including ones not inside of a layout.

https://user-images.githubusercontent.com/73422868/208238017-01ea9022-b034-4480-8646-bf438bffc754.mp4

### Steps to reproduce

To use the minimal reproduction project:
1. Import the project into Godot 4
2. In the `Game` scene, note the three hearts in a row all in the correct position
3. Run the project
4. Observe the differences

### Minimal reproduction project

[Minimal reproduction project](https://github.com/godotengine/godot/files/10251346/TextureRect_Error_Reproduced_Project.zip)

*Additional Note: This does not occur in an identical project in Godot 3.5*

**Comment by mastermarkus** [comment] 2022-12-31 23:10
Tried this on Windows11 (4.0  Beta.6) and all three hearts appear in upper-right corner as expected both in Editor + Running Game.

**Comment by iwoithe** [comment] 2023-01-28 04:02
Still occurring in 4.0 Beta.14 (Windows 10)

**Comment by kleonc** [comment] 2024-06-03 14:54
Based on the MRP/video it happens for mobile renderer on Intel HD Graphics 615. Hence I'm assuming it's a duplicate of #58314, closing it as such (using compatibility renderer should do as a workaround).

**Closed by kleonc** 2024-06-03 14:54 UTC
Labels: bug, needs testing, regression, topic:gui
