### ISSUE TITLE
GPUParticles3D scale isnt affect particle if it's a billboard mode

### ISSUE THREAD

**Issue by krupitskas** [godotengine/godot#74897] opened 2023-03-14 05:51 UTC
### Godot version

v4.0.stable.official [92bee43ad]

### System information

Windows 11, Vulkan, Nvidia 3070TI

### Issue description

While working on a simple fire effect with GPUParticle3D Im not able to change any scale of produced particles, see video attached
https://user-images.githubusercontent.com/5683877/224907221-3a6ac10b-3890-4acc-959e-4d6ad029b43b.mov

### Steps to reproduce

Create GPUParticle3D
Set DrawPasses Pass 1 -> QuadMesh
Create scale variation from 1 to 3 (it works)
Change QuadMesh material to billboard -> scale isnt affecting QuadMesh anymore

### Minimal reproduction project

N/A

**Comment by AThousandShips** [comment] 2023-03-14 09:24
Duplicate of #74249, solution explained there

**Comment by and-rad** [comment] 2023-03-14 09:58
Yup, `Keep Scale` in the material is probably not enabled here. @krupitskas can you see if the problem goes away when you enable it? 
![scale](https://user-images.githubusercontent.com/8700280/224964952-8d38ff96-af2e-49a3-b78f-f83ad9bdfaad.PNG)

**Comment by krupitskas** [comment] 2023-03-14 10:54
Yes, now it works. Oof, super not obvious 💀💀
Thank you for help @and-rad !

**Comment by Calinou** [comment] 2023-03-14 16:13
Duplicate of https://github.com/godotengine/godot/issues/74249 (this isn't a bug).

See https://github.com/godotengine/godot/pull/18365 for original rationale as to why a opt-in Keep Scale property is needed.

**Comment by adamscott** [comment] 2023-04-30 11:18
Closing as it is a duplicate.

**Closed by adamscott** 2023-04-30 11:18 UTC
Labels: archived, topic:rendering, topic:3d, topic:particles

**Comment by clayjohn** [comment] 2023-05-02 21:29
For future reference, duplicate of https://github.com/godotengine/godot/issues/76328

We recently added ``keep_scale`` to particle billboards in https://github.com/godotengine/godot/pull/65353. Before that it was not needed when particle billboards were used.
