### ISSUE TITLE
VP9 Videos crash VideoPlayer on Windows

### ISSUE THREAD

**Issue by mgschwan** [godotengine/godot#39602] opened 2020-06-16 16:58 UTC
**Godot version:**
Tested on 3.2.1 and 3.2.2 rc1

**OS/device including version:**
Windows 10

**Issue description:**
When a VP9 webm video is played the program crashes after about 0.1-0.2 seconds without showing any video.
A VP8 encoded file works and the VP9 encoded files works on the Linux and Android version without crashing

**Steps to reproduce:**

Scene Tree
---------------------
```
Root
  Viewport
    Control
      Videoplayer
  MeshInstance (with Viewport Texture)
```

Code
----------------------
```
var stream = VideoStreamWebm.new()
stream.set_file("res://assets/crunch_sample.webm")
get_node("Viewport/Control/Videoplayer").stream = stream
get_node("Viewport/Control/Videoplayer").play()
```

**Minimal reproduction project:**
[videotest.zip](https://github.com/godotengine/godot/files/4787993/videotest.zip)

**Comment by Calinou** [comment] 2020-06-18 07:48
Duplicate of #37648.

**Closed by Calinou** 2020-06-18 07:48 UTC
Labels: bug, crash, topic:core
