### ISSUE TITLE
Projects slow to start when external DAC is plugged in

### ISSUE THREAD

**Issue by valeriehalla** [godotengine/godot#13099] opened 2017-11-20 15:38 UTC
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Windows 10, Godot v2.1.4

**Issue description:**
When running a project via the play button / hitting F5 / etc, it takes between 10 and 20 seconds to start up. (The game window appears, then remains as an uninteractable white box for some time.) This seems universal, and not related to the specific project I'm trying to play. Once they *do* start, there don't seem to be any other problems, aside from occasional Audio Underflow errors. 

But here's the wild part: *when my external (USB) digital audio converter is disconnected, projects start up almost instantly!*

It's difficult to say how to reproduce this precisely, since there's a lot of possible factors. I'm using the RtAudio-DirectSound driver. As for hardware, in no particular order:
- Creative SoundCore3D
- ODAC-revB USB DAC
- GA-Z170X-Gaming 7 motherboard
- GTX 1070

I'll try to provide more information if you can think of anything relevant!

**Comment by akien-mga** [comment] 2017-11-20 15:49
CC @marcelofg55 for potential clues about the audio drivers, and @Faless @Geequlim in case this would be related to the debugger somehow.

If you are able to build from source, it would be interesting to see how it behaves in the current 2.1 branch, since it uses a new WASAPI audio driver instead of RtAudio, and has fixes regarding connecting/disconnecting devices: https://github.com/godotengine/godot/commits/2.1

**Comment by vnen** [comment] 2017-11-20 16:18
Might be related to OS audio settings (surround, sample rate, and bit depth).

**Comment by opcon** [comment] 2017-11-21 01:03
I ran into this problem as well (with the same DAC). It's not related to the audio drivers, but rather the input device setup (specifically the DirectInput `EnumDevices` call).

Full details are available at this stackoverflow answer I found when searching for a solution: https://stackoverflow.com/a/40449680

Essentially the (Massdrop) ODAC seems to be misbehaving and adds two devices under `Human Interface Devices`: `USB Input Device` and `HID-compliant consumer control device`. Disabling the `USB Input Device` fixes the problem, without impacting the regular function of the DAC. Check the `Bus reported device description` property of the device to get the right one.

I imagine that this `USB Input Device` is malformed, and so the `EnumDevices` function gets stuck iterating over it and waits for a timeout or something.

(As a bonus, this same bug also cropped up in Dark Souls, and prevented the game from ever reaching the main menu if the ODAC was enabled).

**Comment by vnen** [comment] 2017-11-21 02:45
@opcon thanks a lot for the info. Sadly, this means there's nothing we can do to solve it.

**Comment by akien-mga** [comment] 2018-09-18 08:50
Is this still reproducible in Godot 3.0.6 and/or 3.1-alpha?

**Comment by opcon** [comment] 2018-10-12 16:13
I won't be in a position to test this until the end of the year sorry

**Comment by akien-mga** [comment] 2019-02-20 12:41
Closing for now. If anyone can reproduce it in the current master branch (3.1 builds), please comment here with details and we'll reopen it.

**Closed by akien-mga** 2019-02-20 12:41 UTC
Labels: bug, topic:audio, topic:editor
