### ISSUE TITLE
Won't be able to initialize a class in another one

### ISSUE THREAD

**Issue by pokon548** [godotengine/godot#41119] opened 2020-08-08 09:30 UTC
**Godot version:**

6a9fbaf

**OS/device including version:**

OS: Arch Linux
GPU: Intel Core Processor
Backend: GLES2

**Issue description:**

## What happened
When Godot initializing a class within a Godot script which also inherit a class, Godot throw an GDScriptComplier bug.
```
E 0:00:00.487   _get_variant: GDScriptCompiler bug.
  <C ++错误>      Method failed. Returning: __null
  <C++源程序>      modules/gdscript/gdscript_function.cpp:89 @ _get_variant()
  <栈追踪>         :5 @ _init()
                Control.gd:6 @ _ready()
```

![2020-08-08 17-26-53 的屏幕截图](https://user-images.githubusercontent.com/65808665/89706935-9696bf80-d959-11ea-8f18-a67f30207506.png)

## What was expected
Running without issues.

**Steps to reproduce:**
1. Download and import reproduction project below.
2. Run this project.
3. You will see Godot throw an internal error.

**Minimal reproduction project:**

[Fail to load.zip](https://github.com/godotengine/godot/files/5045014/Fail.to.load.zip)

**Comment by pouleyKetchoupp** [comment] 2020-08-09 12:54
Reproduced in 3.2.3.rc3.

It also crashes when loading the project on master 241e709462cd90d3daade3c6a05ff130fe85b4c0 with this callstack (`p_class` is null):
```
        godot.windows.tools.64.exe!GDScriptParser::DataType::is_set() Line 134	C++
 	godot.windows.tools.64.exe!GDScriptAnalyzer::resolve_inheritance(GDScriptParser::ClassNode * p_class, bool p_recursive) Line 135	C++
 	godot.windows.tools.64.exe!GDScriptAnalyzer::resolve_inheritance() Line 3092	C++
 	godot.windows.tools.64.exe!GDScriptParserRef::raise_status(GDScriptParserRef::Status p_new_status) Line 64	C++
 	godot.windows.tools.64.exe!GDScriptAnalyzer::type_from_variant(const Variant & p_value) Line 2579	C++
 	godot.windows.tools.64.exe!GDScriptAnalyzer::reduce_subscript(GDScriptParser::SubscriptNode * p_subscript) Line 2276	C++
 	godot.windows.tools.64.exe!GDScriptAnalyzer::reduce_expression(GDScriptParser::ExpressionNode * p_expression) Line 1296	C++
 	godot.windows.tools.64.exe!GDScriptAnalyzer::resolve_class_interface(GDScriptParser::ClassNode * p_class) Line 548	C++
 	godot.windows.tools.64.exe!GDScriptAnalyzer::resolve_program() Line 3106	C++
 	godot.windows.tools.64.exe!GDScriptAnalyzer::analyze() Line 3124	C++
 	godot.windows.tools.64.exe!GDScript::reload(bool p_keep_state) Line 612	C++
 	godot.windows.tools.64.exe!GDScriptCache::get_full_script(const String & p_path, Error & r_error, const String & p_owner) Line 200	C++
 	godot.windows.tools.64.exe!ResourceFormatLoaderGDScript::load(const String & p_path, const String & p_original_path, Error * r_error, bool p_use_sub_threads, float * r_progress, bool p_no_cache) Line 2054	C++
 	godot.windows.tools.64.exe!ResourceLoader::_load(const String & p_path, const String & p_original_path, const String & p_type_hint, bool p_no_cache, Error * r_error, bool p_use_sub_threads, float * r_progress) Line 190	C++
 	godot.windows.tools.64.exe!ResourceLoader::_thread_load_function(void * p_userdata) Line 216	C++
 	godot.windows.tools.64.exe!ResourceLoader::load(const String & p_path, const String & p_type_hint, bool p_no_cache, Error * r_error) Line 580	C++
 	godot.windows.tools.64.exe!GDScriptParser::parse_preload(GDScriptParser::ExpressionNode * p_previous_operand, bool p_can_assign) Line 2527	C++
 	godot.windows.tools.64.exe!GDScriptParser::parse_precedence(GDScriptParser::Precedence p_precedence, bool p_can_assign, bool p_stop_on_assign) Line 1840	C++
 	godot.windows.tools.64.exe!GDScriptParser::parse_expression(bool p_can_assign, bool p_stop_on_assign) Line 1866	C++
 	godot.windows.tools.64.exe!GDScriptParser::parse_constant() Line 940	C++
 	godot.windows.tools.64.exe!GDScriptParser::parse_class_member<GDScriptParser::ConstantNode>(GDScriptParser::ConstantNode *(GDScriptParser::*)() p_parse_function, GDScriptParser::AnnotationInfo::TargetKind p_target, const String & p_member_kind) Line 658	C++
 	godot.windows.tools.64.exe!GDScriptParser::parse_class_body() Line 694	C++
 	godot.windows.tools.64.exe!GDScriptParser::parse_program() Line 559	C++
 	godot.windows.tools.64.exe!GDScriptParser::parse(const String & p_source_code, const String & p_script_path, bool p_for_completion) Line 356	C++
 	godot.windows.tools.64.exe!GDScript::reload(bool p_keep_state) Line 601	C++
 	godot.windows.tools.64.exe!GDScriptCache::get_full_script(const String & p_path, Error & r_error, const String & p_owner) Line 200	C++
 	godot.windows.tools.64.exe!ResourceFormatLoaderGDScript::load(const String & p_path, const String & p_original_path, Error * r_error, bool p_use_sub_threads, float * r_progress, bool p_no_cache) Line 2054	C++
 	godot.windows.tools.64.exe!ResourceLoader::_load(const String & p_path, const String & p_original_path, const String & p_type_hint, bool p_no_cache, Error * r_error, bool p_use_sub_threads, float * r_progress) Line 190	C++
 	godot.windows.tools.64.exe!ResourceLoader::_thread_load_function(void * p_userdata) Line 216	C++
 	godot.windows.tools.64.exe!ResourceLoader::load(const String & p_path, const String & p_type_hint, bool p_no_cache, Error * r_error) Line 580	C++
 	godot.windows.tools.64.exe!ScriptEditor::set_window_layout(Ref<ConfigFile> p_layout) Line 2764	C++
 	godot.windows.tools.64.exe!ScriptEditorPlugin::set_window_layout(Ref<ConfigFile> p_layout) Line 3563	C++
 	godot.windows.tools.64.exe!EditorData::set_plugin_window_layout(Ref<ConfigFile> p_layout) Line 828	C++
 	godot.windows.tools.64.exe!EditorNode::_load_docks() Line 4266	C++
 	godot.windows.tools.64.exe!EditorNode::_sources_changed(bool p_exist) Line 836	C++
 	godot.windows.tools.64.exe!call_with_variant_args_helper<EditorNode,bool,0>(EditorNode * p_instance, void(EditorNode::*)(bool) p_method, const Variant * * p_args, Callable::CallError & r_error, IndexSequence<0> __formal) Line 136	C++
 	godot.windows.tools.64.exe!call_with_variant_args<EditorNode,bool>(EditorNode * p_instance, void(EditorNode::*)(bool) p_method, const Variant * * p_args, int p_argcount, Callable::CallError & r_error) Line 158	C++
 	godot.windows.tools.64.exe!CallableCustomMethodPointer<EditorNode,bool>::call(const Variant * * p_arguments, int p_argcount, Variant & r_return_value, Callable::CallError & r_call_error) Line 185	C++
 	godot.windows.tools.64.exe!Callable::call(const Variant * * p_arguments, int p_argcount, Variant & r_return_value, Callable::CallError & r_call_error) Line 50	C++
 	godot.windows.tools.64.exe!Object::emit_signal(const StringName & p_name, const Variant * * p_args, int p_argcount) Line 1077	C++
 	godot.windows.tools.64.exe!Object::emit_signal(const StringName & p_name, const Variant & p_arg1, const Variant & p_arg2, const Variant & p_arg3, const Variant & p_arg4, const Variant & p_arg5) Line 1132	C++
 	godot.windows.tools.64.exe!EditorFileSystem::_notification(int p_what) Line 1124	C++
 	godot.windows.tools.64.exe!EditorFileSystem::_notificationv(int p_notification, bool p_reversed) Line 106	C++
 	godot.windows.tools.64.exe!Object::notification(int p_notification, bool p_reversed) Line 808	C++
 	godot.windows.tools.64.exe!SceneTree::_notify_group_pause(const StringName & p_group, int p_notification) Line 820	C++
 	godot.windows.tools.64.exe!SceneTree::idle(float p_time) Line 447	C++
 	godot.windows.tools.64.exe!Main::iteration() Line 2333	C++
```

**Comment by vnen** [comment] 2020-08-11 22:16
This is a duplicate of #5843

**Closed** 2020-08-11 22:57 UTC
Labels: bug, confirmed, topic:gdscript
