### ISSUE TITLE
C#: Exporting a Generic Type Argument with Variant-Compatible type restrictions triggers `GD0102`

### ISSUE THREAD

**Issue by Delsin-Yu** [godotengine/godot#91746] opened 2024-05-09 06:53 UTC
### Tested versions

Godot v4.3.dev5.mono

### System information

Godot v4.3.dev5.mono - Windows 10.0.17763 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 4060 Ti (NVIDIA; 31.0.15.5222) - AMD Ryzen 9 5900X 12-Core Processor (24 Threads)

### Issue description

Generic Abstract classes encapsulate operations that are not specific to a particular data type and can be used as a `template` to reduce the amount of repetitive code needed. 

Under such a use case, it's natural for a Godot C# developer to use a generic abstract class as the base class when creating a large number of scripts that share exported properties.

However, even if I annotated the Generaic Argument with `where` constraints to restrict it to Godot-compatible export types, the Godot Script Analyser still throws [GD0102](https://docs.godotengine.org/en/latest/tutorials/scripting/c_sharp/diagnostics/GD0102.html) when compiling.

### Steps to reproduce

The following scripts won't compile, even though we have restricted the `TContentType` to `Control`, which is a Variant-Compatible, Godot type. 
```csharp
public abstract partial class BasePropertyInspector<TContentType> : Control where TContentType : Control
{
    [Export] private Label _propertyName;
    [Export] private TContentType _contentControl;
    
    public string DisplayName
    {
        set => _propertyName.Text = value;
    }

    protected TContentType ContentControl => _contentControl;
}
```

For context, the aforementioned type is inherited by the following types:
```csharp
// StringInspector.cs
public partial class StringInspector : BasePropertyInspector<LineEdit>;

// NumberInspector.cs
public partial class NumberInspector : BasePropertyInspector<SpinBox>;

// EnumInspector.cs
public partial class EnumInspector : BasePropertyInspector<OptionButton>;

// BooleanInspector.cs
public partial class BooleanInspector : BasePropertyInspector<CheckBox>;

// ObjectInspector.cs
public partial class ObjectInspector : BasePropertyInspector<Control>
{
    [Export] private CheckButton _foldout;

    public Control Container => ContentControl;

    public override void _Ready() => _foldout.Toggled += on => ContentControl.Visible = on;
}
```

### Minimal reproduction project (MRP)

Compile this in any Godot C# project.
```csharp
using Godot;

public abstract partial class BasePropertyInspector<TContentType> : Control where TContentType : Control
{
    [Export] private Label _propertyName;
    [Export] private TContentType _contentControl;
    
    public string DisplayName
    {
        set => _propertyName.Text = value;
    }

    protected TContentType ContentControl => _contentControl;
}
```

Should fix by https://github.com/godotengine/godot/pull/83432

**Comment by raulsntos** [comment] 2024-05-10 01:26
Duplicate of https://github.com/godotengine/godot/issues/74960

**Closed by raulsntos** 2024-05-10 01:26 UTC
Labels: topic:dotnet
