### ISSUE TITLE
Is there a way to see mesh collider's shape?

### ISSUE THREAD

**Issue by marsmoon** [godotengine/godot#13938] opened 2017-12-03 22:49 UTC
I imported a model with a collider, but my object keeps going through other colliders. It does it often, but not always. I would like to view the shape of my mesh collider to check if there is something wrong with it.

**Comment by eon-s** [comment] 2017-12-04 00:42
Is this a question or you cannot see CollisionShape's concave/convex shapes when these are enabled with the debugger option?

**Comment by marsmoon** [comment] 2017-12-04 01:26
I can only see the default shapes like cube, plane, sphere etc. I cannot see shapes that were generated from a model. What do you mean by debugger option? I'm using the newest master.

**Comment by eon-s** [comment] 2017-12-04 02:34
Ok, I do not know what is the problem with the collision itself but for the shapes, seems that concave collision shapes are not being drawn at all at least on this system (linux, nvidia proprietary drivers 384.90).

![captura de pantalla de 2017-12-03 23-24-58](https://user-images.githubusercontent.com/10215987/33533835-65a874fc-d882-11e7-9294-512c9da9b939.png)
_Convex and concave shapes created with the mesh button_

**Comment by marsmoon** [comment] 2017-12-04 02:40
I'm on GNU/Linux as well with free AMD drivers.

**Comment by Calinou** [comment] 2020-06-19 07:46
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!

**Closed by Calinou** 2020-06-19 07:46 UTC
Labels: enhancement, topic:editor

**Comment by eon-s** [comment] 2020-06-19 20:38
Just to clarify, this was not a request but a bug report, and I could not reproduce it on 3.2.2rc so I guess it can stay closed.
