### ISSUE TITLE
Retrieving argument from a function using .get_method_list() doesnt return type, value and argument name

### ISSUE THREAD

**Issue by KStormStudio** [godotengine/godot#73215] opened 2023-02-13 10:57 UTC
### Godot version

4.0 beta 14

### System information

Win 11

### Issue description

I have a node with 2 or more declared functions. Each function has different argument type and name.
`
func public_setPositionX(x : float):
..
func public_setCaption(caption : String):
..
(node is the node with the script with those functions)
for p in node.get_method_list():
    print(p["args"])
    print(p["args"][0]["type"])
`

I got the same output:
[{ "name": "arg0", "class_name": &"", "type": 0, "hint": 0, "hint_string": "", "usage": 6 }]

So no way to get the argument name as "x" for instance, type and value, how can i do that please?
Thank you very much

### Steps to reproduce

func public_setPositionX(x : float):
..
func public_setCaption(caption : String):
..
(node is the node with the script with those functions)
for p in node.get_method_list():
    print(p["args"])
    print(p["args"][0]["type"])

**Comment by KStormStudio** [comment] 2023-02-14 11:18
Especially in case of functions with more than a argument that would be essential. Anyone please?

**Comment by KoBeWi** [comment] 2023-03-10 18:36
Looks like duplicate of #33624
The last comment includes a potential workaround.

**Closed by KoBeWi** 2023-03-10 18:36 UTC
