### ISSUE TITLE
On Android, Project Setting `application/boot_splash/fullsize` is opposite of other platforms

### ISSUE THREAD

**Issue by JapanYoshi** [godotengine/godot#77544] opened 2023-05-27 08:05 UTC
### Godot version

4.0.3.stable.official [5222a99f5]

### System information

Windows 10, Forward+ renderer, NVIDIA GeForce GTX 1060 with Max-Q Design

### Issue description

On most platforms, when Project Settings `application/boot_splash/fullsize` is true, it will scale the boot splash, and when it is false, it won't. On Android, it's the opposite.

### Steps to reproduce

1. Create project with boot splash.
2. Configure Android export.
3. Observe the effects of turning `application/boot_splash/fullsize` on and off.

### Minimal reproduction project

Any project with a boot splash.

**Comment by JapanYoshi** [comment] 2023-05-27 08:10
With the option set to false:
![image](https://github.com/godotengine/godot/assets/8707990/c93b7768-59c6-445d-975b-1a9b5bfcbd0b)
![image](https://github.com/godotengine/godot/assets/8707990/0a612bfb-cdbe-4345-b9af-f9cb77128381)

**Comment by JapanYoshi** [comment] 2023-05-27 08:13
And with the option set to true:
![image](https://github.com/godotengine/godot/assets/8707990/ba43a2c0-32d6-4fb8-bff5-a90910131757)
![image](https://github.com/godotengine/godot/assets/8707990/fe7cb428-6b2a-426a-bc55-cad7285f2b55)

**Comment by Calinou** [comment] 2023-05-27 23:19
- Duplicate of https://github.com/godotengine/godot/issues/69317 and https://github.com/godotengine/godot/issues/49816.

**Closed by Calinou** 2023-05-27 23:19 UTC
