### ISSUE TITLE
Children of viewport nodes cannot be dragged.

### ISSUE THREAD

**Issue by avencherus** [godotengine/godot#45389] opened 2021-01-23 12:26 UTC
**Godot version:**

3.2.4

**OS/device including version:**

Win 10

**Issue description:**

Children of Viewport nodes from as far as I can tell can't be repositioned with dragging in the editor.  The transform properties have to be manually updated in the inspector panel.

![ezgif com-gif-maker](https://user-images.githubusercontent.com/13004169/105578089-71bacb00-5d86-11eb-93d9-98a73797c638.gif)

**Steps to reproduce:**
1. Setup a 2D viewport.
2. Create sprites as children.
3. Try to drag and move them.

**Minimal reproduction project:**

[Viewport Children Undraggable.zip](https://github.com/godotengine/godot/files/5860177/Viewport.Children.Undraggable.zip)

**Comment by pycbouh** [comment] 2021-01-23 12:56
Duplicate of #20619.

Note that the root of the issue is that to the editor this is just a rendered texture, same as in the actual running project. You can work around this limitation by putting the contents of your `Viewport` into a separate scene.

**Closed by pycbouh** 2021-01-23 12:56 UTC

**Comment by avencherus** [comment] 2021-01-23 20:17
Wouldn't then also editor viewport and the root scene viewport prevent usage of controls the same?
