### ISSUE TITLE
Module linking error for iOS 

### ISSUE THREAD

**Issue by lzubiaur** [godotengine/godot#25796] opened 2019-02-11 12:38 UTC
**Godot version:**
3.0.6-stable

**OS/device including version:**
osx 10.14

**Issue description:**

Compiling custom module and linking against third-party library (Admob cpp) fails with the following error when targeting iOS. Please note that it works fine when compiling for osx.

```
[ 74%] scons: *** [bin/libgodot.iphone.opt.arm64.a] Source `platform/iphone/firebase_admob' not found, needed by target `bin/libgodot.iphone.opt.arm64.a'.
scons: building terminated because of errors.
```

**Steps to reproduce:**
Unzip this [module example](https://github.com/godotengine/godot/files/2850990/admob.zip) in godot_src\modules
Download firebase cpp (direct download [here](https://firebase.google.com/download/cpp)) 
and unzip it in godot_src\modules\admob

Build the module as below:
```
scons p=iphone tools=no bits=64 target=release arch=arm64
```

**Comment by akien-mga** [comment] 2019-02-11 12:47
It's hard to debug something that requires downloading 600 MB worth of binaries, but I suspect that the issue is in your `SCsub` file and not with Godot itself. Is this your module, or a thirdparty one?

```python
# SCsub
Import('env')

sources = [
    "register_types.cpp",
    "admob.cpp"
]

module_env = env.Clone()
module_env.Append(CXXFLAGS=['-O2', '-std=c++11'])

module_env.Append(CPPPATH=['firebase_cpp_sdk/include'])

env.Append(LIBS=['firebase_admob', 'firebase_app']);

if env['platform'] == 'iphone':
    env.Append(LIBPATH='firebase_cpp_sdk/libs/ios/universal')
elif env['platform'] == 'osx':
    env.Append(LIBPATH='firebase_cpp_sdk/libs/darwin/universal')

module_env.add_source_files(env.modules_sources, sources)
```
The `LIBS` should be appended to `module_env`, not `env`. See http://docs.godotengine.org/en/latest/development/cpp/binding_to_external_libraries.html

**Comment by lzubiaur** [comment] 2019-02-11 23:09
mmm, I can compile the iphone module if `LIBS`and `LIBPATH` are defined in the module env but then the editor build fails (linking errors). I guess this is somewhat because the first is building a static library and the other an executable. 

Anyway the doc mentioned above, adds to the "module env" without actually cloning it (`env.Clone()`) which is confusing.

**Comment by Calinou** [comment] 2019-12-30 10:46
@lzubiaur Can you still reproduce this on [Godot 3.2 beta4](https://godotengine.org/article/dev-snapshot-godot-3-2-beta-4)?

**Comment by akien-mga** [comment] 2020-07-26 13:10
No answer, closing.

**Closed by akien-mga** 2020-07-26 13:10 UTC
Labels: bug, platform:ios, topic:thirdparty
