### ISSUE TITLE
Placing CharacterBody2d's position in AnimationPlayer's RESET animation causes position to be lost everywhere that scene is used

### ISSUE THREAD

**Issue by Koden02** [godotengine/godot#78635] opened 2023-06-24 03:53 UTC
### Godot version

4.0.3

### System information

Windows 10

### Issue description

I'm pretty sure this isn't an expected result.  I found this error when I was trying to do an animation that would move the entire CharacterBody2D.  If you place its position in the animationPlayer's RESET animation and save it, if you save any scene with that scene inside of it, it will lose its position data.

### Steps to reproduce

Create a new CharacterBody2D scene.
Place a sprite in the scene so you can see it.
Create an AnimationPlayer as a child of the scene.
In the RESET animation, add in the CharacterBody2D's position as a key.
Save.

Place this scene in another scene, like a map, and drag it to anywhere that isn't the origin.
Save.
Close the scene and reopen it.
Find that the scene you placed returned to origin.

### Minimal reproduction project

[Error Project.zip](https://github.com/godotengine/godot/files/11854404/Error.Project.zip)

**Comment by AThousandShips** [comment] 2023-06-24 08:17
So is it the `CharacterBody2D` scene that resets it's position? Or the scene it is in?

If it's the first then that sounds like it's how it's supposed to be, the position is reset by the animation, as expected?

**Comment by Koden02** [comment] 2023-06-24 15:47
It's the scene it's in that returns to the origin point.

I see what you mean, I turned off that behavior and it stopped removing it, but I wasn't sure if it was the intentional functionality for it to cause the location when placed somewhere else to get deleted.  If that's how it's supposed to work then good to know, just wanted to make sure if this was a bug that it was known so someone else doesn't get thrown off by it.

Good to know though, thanks.

**Comment by AThousandShips** [comment] 2023-06-25 08:10
Closing as not a bug, as the behaviour is documented, thank you for reporting

**Closed by AThousandShips** 2023-06-25 08:10 UTC
Labels: topic:animation
