### ISSUE TITLE
Editor gizmos blur with DOF enabled.

### ISSUE THREAD

**Issue by EMBYRDEV** [godotengine/godot#77366] opened 2023-05-22 19:20 UTC
### Godot version

4.0.3.stable

### System information

Windows 11, Vulkan, RTX2070 Super

### Issue description

With DOF enabled editor gizmos blur in a strange mannor based upion what's behind them.

Gizmos are not part of the visual look of a game and should remain clear and visible regardless of graphics options.

Using `depth_draw_always` in the gizmos shader may solve this problem.

### Steps to reproduce

![image](https://github.com/godotengine/godot/assets/20043270/fd66cc9c-e22a-478e-b241-78b279905179)

### Minimal reproduction project

N/A

**Comment by clayjohn** [comment] 2023-05-23 17:48
This happens because gizmos are rendered the same as other objects. In this case they are transparent objects, so they do not contribute to the depth prepass, so the DoF blur is not aware of them. 

There is a proposal to render Gizmos in a seperate pass so they are not affected by post processing effects https://github.com/godotengine/godot-proposals/issues/2138

**Comment by EMBYRDEV** [comment] 2023-05-23 18:02
Is there any downside to just using "depth_draw_always" on editor gizmos?

**Comment by clayjohn** [comment] 2023-05-23 18:23
> Is there any downside to just using "depth_draw_always" on editor gizmos?

Probably not. It might lead to some awkward depth sorting situations when a scene contains other transparent objects and it could look bad. That being said, it would only help with depth-based effects like DoF. Glow, exposure and adjustments would still apply to Gizmos

**Comment by Calinou** [comment] 2023-05-23 21:43
- Duplicate of https://github.com/godotengine/godot-proposals/issues/2138.

**Closed by Calinou** 2023-05-23 21:43 UTC
Labels: feature proposal, topic:editor, topic:3d

**Comment by Zireael07** [comment] 2023-05-24 06:45
@Calinou This suggestion is worth documenting in Godot docs themselves

**Comment by Calinou** [comment] 2023-05-24 09:43
> @Calinou This suggestion is worth documenting in Godot docs themselves

This is already documented in the [Camera attributes](https://docs.godotengine.org/en/latest/tutorials/3d/environment_and_post_processing.html#camera-attributes) section of the Environment and post-processing documentation.
