### ISSUE TITLE
4.4dev6 crashes when loading csgshape

### ISSUE THREAD

**Issue by morganholly** [godotengine/godot#100131] opened 2024-12-07 00:41 UTC
### Tested versions

happens in 4.4dev6
does not happen in 4.3
crash call stack references manifold, which was added in 4.4dev6

### System information

macos 12.7.6 i9/radeon

### Issue description

loading https://github.com/majikayogames/SimpleFPSController (made in 4.2 according to godot) in 4.4dev6, it crashes with this call stack when loading the editor. it's something with manifold, but i don't know what does it past that.

```
Thread 0 Crashed::  Dispatch queue: com.apple.main-thread
0   libsystem_kernel.dylib        	    0x7ff80351cfce __pthread_kill + 10
1   libsystem_pthread.dylib       	    0x7ff8035531ff pthread_kill + 263
2   libsystem_c.dylib             	    0x7ff80349ed14 abort + 123
3   Godot                         	       0x1062e35fa 0x1059fc000 + 9336314
4   libsystem_platform.dylib      	    0x7ff803568dfd _sigtramp + 29
5   ???                           	    0x6000070e3ec0 ???
6   Godot                         	       0x1064debaa manifold::Manifold::Impl::CreateFaces() + 586
7   Godot                         	       0x1064f3c3b 0x1059fc000 + 11500603
8   Godot                         	       0x1064e8086 manifold::Manifold::Manifold(manifold::MeshGLP<double, unsigned long long> const&) + 70
9   Godot                         	       0x1065299fc 0x1059fc000 + 11721212
10  Godot                         	       0x106527d9b CSGShape3D::_get_brush() + 219
11  Godot                         	       0x10652688b CSGShape3D::_update_shape() + 203
12  Godot                         	       0x10a7f2434 CallQueue::_call_function(Callable const&, Variant const*, int, bool) + 484
13  Godot                         	       0x10a7f26ce CallQueue::flush() + 334
14  Godot                         	       0x1086eb132 SceneTree::process(double) + 258
15  Godot                         	       0x106358203 Main::iteration() + 1155
16  Godot                         	       0x1062de19a OS_MacOS::run() + 154
17  Godot                         	       0x10630ee73 main + 387
18  dyld                          	       0x1168c752e start + 462
```

### Steps to reproduce

download https://github.com/majikayogames/SimpleFPSController/files/15273600/StarterProject.zip, load it in 4.4dev6, crashes before finishes loading editor

### Minimal reproduction project (MRP)

unmodified  https://github.com/majikayogames/SimpleFPSController

**Comment by clayjohn** [comment] 2024-12-07 00:47
Cc @fire

**Comment by fire** [comment] 2024-12-07 01:01
Looking into it.

**Comment by fire** [comment] 2024-12-07 01:09
I cannot reproduce the crash on Master.

![Image](https://github.com/user-attachments/assets/9c52a590-f96f-4bc0-8451-866278928088)

https://github.com/godotengine/godot/commit/aa8d9b83f66488dbb2c9c918e9016ef80f821fb4

**Comment by morganholly** [comment] 2024-12-07 01:13
that certainly looks like the same behavior, with the other related bugs not happening on master

**Comment by fire** [comment] 2024-12-07 13:32
Closing because the crssh may be fixed in godot engine master

**Closed by fire** 2024-12-07 13:32 UTC
Labels: bug, topic:core, crash, regression
