### ISSUE TITLE
2D Viewport does not display child nodes.

### ISSUE THREAD

**Issue by JustYourAverageJosh** [godotengine/godot#49782] opened 2021-06-21 00:58 UTC
### Godot version

3.3.stable

### System information

Windows 10, GLES2, GTX 1060

### Issue description

It also happens in official godot templates (such as the 2D in 3D Demo, and the GUI in 3D demo)

If the root scene is 3D, when you click on one of the viewport's nodes it will go to 2D mode but will be blank (no matter what is in that viewport scene)
If the root scene is 2D, when you click on one of the viewport's nodes, the inspector will show the node's properties, but will not change to that viewport's view

FURTHERMORE:
If you have a control in the 2d viewport, the green Layout and Anchor buttons doesn't show up on the top of the 2D toolbar when you click it.
HOWEVER, there are a few nodes that WILL show the extra options on the toolbar, and will also show things such as Vector2 points!
I tried most of the 2d Nodes, and these are the only ones that show anything when click on them in a 2d Viewport:
Polygon2D
CollisinShape2D
CollisionPolygon2D
Line2D
Bone2D

So this definitely seems like it's unintentional!

Here's a video of what I'm talking about:

https://user-images.githubusercontent.com/47060866/122693909-b77ea100-d209-11eb-9fb5-6c5850e4bc16.mp4

### Steps to reproduce

Create a scene, add a viewport, add a 2d node to the viewport. Then click on the 2d node, it will not be visible, but it's properties will show in the inspector.

### Minimal reproduction project

[2DViewport.zip](https://github.com/godotengine/godot/files/6683402/2DViewport.zip)

**Comment by Calinou** [comment] 2021-06-21 07:17
Duplicate of https://github.com/godotengine/godot/issues/40441 or https://github.com/godotengine/godot/issues/19638?

**Comment by Calinou** [comment] 2021-08-23 16:39
Duplicate of https://github.com/godotengine/godot/issues/39387.

**Closed by Calinou** 2021-08-23 16:39 UTC
Labels: bug, topic:editor, topic:2d
