### ISSUE TITLE
Distortion of audio through SamplePlayer2D

### ISSUE THREAD

**Issue by toby3d** [godotengine/godot#7069] opened 2016-11-08 13:12 UTC
Godot Engine v.2.2.alpha.custom_build by [cdc4664](https://github.com/godotengine/godot/commit/cdc4664226cdc397d054b7390d0f75028d40412c) commit on Linux Mint 18 Mate x86-64

If you add a node SamplePlayer2D, add the sample and play it through a script or autostart node parameter, the sound is heard distorted (sounds faster and higher than the original). To the sound of the game could be heard as same as in the editor, you must set the pitch parameter by **0.9**.

**Comment by Zylann** [comment] 2016-11-08 19:41
Duplicate of https://github.com/godotengine/godot/issues/2026
Apparently scheduled for 2.2, so 3.0 I guess?

**Comment by akien-mga** [comment] 2016-11-11 10:14
Closing as duplicate.

**Closed by akien-mga** 2016-11-11 10:14 UTC
