### ISSUE TITLE
Tutorial Shortcut for Button isn't working, Editor Broken

### ISSUE THREAD

**Issue by mykael22000** [godotengine/godot#76580] opened 2023-04-29 13:44 UTC
### Godot version

v4.0.2.stable.official [7a0977ce2]

### System information

Windows 10, Intel i7, 32GB

### Issue description

The end of the 2D Game Tutorial (admittedly for Godot 3.x) instructs me to set up a keyboard shortcut for the Start button.

It doesn't work, but this may be a known 4.x issue.

The tutorial says to construct it as an InputEventAction, and it's meant to automagically link the Enter key the button.  Except that it doesn't work.

Something needs fixing, either the Tutorial or the engine.

Hmmm. Trying to get the properties up to put them in the tutorial, I seem to have a related issue in the editor.

The little buton with the three bars next tot he shortcut isn't working - clicks are just ignored.

![image](https://user-images.githubusercontent.com/6858095/235305795-7ae1d937-5eba-4432-81aa-d8cf18753196.png)

I've tried closing Godot and restarting and reloading my project, and the problem persists.

### Steps to reproduce

Follow the bit int he 2D game tutorial about adding a Shortcut.

https://docs.godotengine.org/en/stable/getting_started/first_2d_game/07.finishing-up.html

Not sure how to go from Enter shortcut not working to properties button for shortcut being ignored and I can't get back to experiment.  Might be related to create and then deleting a couple of new scenes in Script Edit mode.

### Minimal reproduction project

[DodgeCreep.zip](https://github.com/godotengine/godot/files/11359286/DodgeCreep.zip)

This is the complete 2D Game Tutorial and reliably reproduces the problem whenever I open it.  

Open it with caution.  I closed Godot, relaunched it, opened a different project and the bug was still there (unable to expand the properties for the shortcut).  Not tried rebooting my system, yet.

**Comment by KoBeWi** [comment] 2023-04-29 15:59
Can't reproduce

https://user-images.githubusercontent.com/2223172/235311910-8f2c414c-f1f4-45e4-8d8f-52dbb8113376.mp4

**Comment by KoBeWi** [comment] 2023-05-12 11:20
No reply, closing.
Comment with more info if you can still reproduce.

**Closed by KoBeWi** 2023-05-12 11:20 UTC
