### ISSUE TITLE
Scene instance property changes are not revertible in inspector

### ISSUE THREAD

**Issue by Flavelius** [godotengine/godot#42240] opened 2020-09-22 05:48 UTC
**Godot version:**
3.2.3.stable.mono.official

**OS/device including version:**
Windows 10

**Issue description:**
Usually, for example for scripts when changes of properties differ to their declared value, a revert button is displayed that allows the user to reset the value to the default.
But for instances of scenes this doesn't work. One can for example clear node paths on that instance and no revert button is shown.
It's expected to be able to revert changes to the state saved on disk.

**Steps to reproduce**
Create a scene, add a node with a script declaring a nodepath (c# in my case). Assign another node to that path. Save scene to file. Create another scene, instantiate the previous scene into it and clear the nodepath value on that instance. No revert button is shown.

This is probably also indirectly requesting another improvement for managing those overrides (as it's conveniently possible in unity; apply [to parent], revert etc)

**Comment by Calinou** [comment] 2020-09-22 09:54
Duplicate of https://github.com/godotengine/godot/issues/33611.

**Closed by Calinou** 2020-09-22 09:54 UTC
