### ISSUE TITLE
OpenGL isn't initializing in 3.2.1!

### ISSUE THREAD

**Issue by sukhchainn** [godotengine/godot#37569] opened 2020-04-04 02:02 UTC
**Godot version: 3.2.1**

**OS/device including version: Windows 7 service pack 1**

**Issue description: Nothing initializes**

**Steps to reproduce: run Godot executable**

**Minimal reproduction project: ----**

```

$ ./godot.exe --verbose
Godot Engine v3.2.1.stable.official - https://godotengine.org
Using GLES3 video driver
OpenGL debugging not supported!
OpenGL ES 3.0 Renderer: Intel(R) HD Graphics 4000
ERROR: initialize: Condition "status != 0x8CD5" is true. Continuing.
   At: drivers/gles3/rasterizer_scene_gles3.cpp:5095
ERROR: initialize: Condition "status != 0x8CD5" is true. Continuing.
   At: drivers/gles3/rasterizer_scene_gles3.cpp:5095
ERROR: initialize: Condition "status != 0x8CD5" is true. Continuing.
   At: drivers/gles3/rasterizer_scene_gles3.cpp:5095
ERROR: initialize: Condition "status != 0x8CD5" is true. Continuing.
   At: drivers/gles3/rasterizer_scene_gles3.cpp:5095
ERROR: initialize: Condition "status != 0x8CD5" is true. Continuing.
   At: drivers/gles3/rasterizer_scene_gles3.cpp:5095
ERROR: initialize: Condition "status != 0x8CD5" is true. Continuing.
   At: drivers/gles3/rasterizer_scene_gles3.cpp:5095
ERROR: initialize: Condition "status != 0x8CD5" is true. Continuing.
   At: drivers/gles3/rasterizer_scene_gles3.cpp:5095
ERROR: initialize: Condition "status != 0x8CD5" is true. Continuing.
   At: drivers/gles3/rasterizer_scene_gles3.cpp:5095
ERROR: initialize: Condition "status != 0x8CD5" is true. Continuing.
   At: drivers/gles3/rasterizer_scene_gles3.cpp:5095
ERROR: initialize: Condition "status != 0x8CD5" is true. Continuing.
   At: drivers/gles3/rasterizer_scene_gles3.cpp:5095
ERROR: initialize: Condition "status != 0x8CD5" is true. Continuing.
   At: drivers/gles3/rasterizer_scene_gles3.cpp:5095
ERROR: initialize: Condition "status != 0x8CD5" is true. Continuing.
   At: drivers/gles3/rasterizer_scene_gles3.cpp:5095
ERROR: initialize: Condition "status != 0x8CD5" is true. Continuing.
   At: drivers/gles3/rasterizer_scene_gles3.cpp:5095
ERROR: initialize: Condition "status != 0x8CD5" is true. Continuing.
   At: drivers/gles3/rasterizer_scene_gles3.cpp:5095
ERROR: initialize: Condition "status != 0x8CD5" is true. Continuing.
   At: drivers/gles3/rasterizer_scene_gles3.cpp:5095
ERROR: initialize: Condition "status != 0x8CD5" is true. Continuing.
   At: drivers/gles3/rasterizer_scene_gles3.cpp:5095
ERROR: initialize: Condition "status != 0x8CD5" is true. Continuing.
   At: drivers/gles3/rasterizer_scene_gles3.cpp:5095
ERROR: initialize: Condition "status != 0x8CD5" is true. Continuing.
   At: drivers/gles3/rasterizer_scene_gles3.cpp:5095
ERROR: initialize: Condition "status != 0x8CD5" is true. Continuing.
   At: drivers/gles3/rasterizer_scene_gles3.cpp:5095
ERROR: initialize: Condition "status != 0x8CD5" is true. Continuing.
   At: drivers/gles3/rasterizer_scene_gles3.cpp:5095
ERROR: initialize: Condition "status != 0x8CD5" is true. Continuing.
   At: drivers/gles3/rasterizer_scene_gles3.cpp:5095
ERROR: initialize: Condition "status != 0x8CD5" is true. Continuing.
   At: drivers/gles3/rasterizer_scene_gles3.cpp:5095
ERROR: initialize: Condition "status != 0x8CD5" is true. Continuing.
   At: drivers/gles3/rasterizer_scene_gles3.cpp:5095
ERROR: initialize: Condition "status != 0x8CD5" is true. Continuing.
   At: drivers/gles3/rasterizer_scene_gles3.cpp:5095
ERROR: initialize: Condition "status != 0x8CD5" is true. Continuing.
   At: drivers/gles3/rasterizer_scene_gles3.cpp:5095
ERROR: initialize: Condition "status != 0x8CD5" is true. Continuing.
   At: drivers/gles3/rasterizer_scene_gles3.cpp:5095
ERROR: initialize: Condition "status != 0x8CD5" is true. Continuing.
   At: drivers/gles3/rasterizer_scene_gles3.cpp:5095
ERROR: initialize: Condition "status != 0x8CD5" is true. Continuing.
   At: drivers/gles3/rasterizer_scene_gles3.cpp:5095
ERROR: initialize: Condition "status != 0x8CD5" is true. Continuing.
   At: drivers/gles3/rasterizer_scene_gles3.cpp:5095
ERROR: initialize: Condition "status != 0x8CD5" is true. Continuing.
   At: drivers/gles3/rasterizer_scene_gles3.cpp:5095
ERROR: initialize: Directional shadow framebuffer status invalid
   At: drivers/gles3/rasterizer_scene_gles3.cpp:5120
WASAPI: wFormatTag = 65534
WASAPI: nChannels = 2
WASAPI: nSamplesPerSec = 48000
WASAPI: nAvgBytesPerSec = 384000
WASAPI: nBlockAlign = 8
WASAPI: wBitsPerSample = 32
WASAPI: cbSize = 22
WASAPI: detected 2 channels
WASAPI: audio buffer frames: 933 calculated latency: 21ms

CORE API HASH: 10822102301860774635
EDITOR API HASH: 14982495073158502407
Loading resource: C:\Users/Dell/AppData/Roaming/Godot/editor_settings-3.tres
EditorSettings: Load OK!
EditorSettings: Save OK!
Loaded builtin certs

```

**Comment by clayjohn** [comment] 2020-04-04 02:31
Can you try updating your GPU drivers? 

Can you also provide information about your hardware including CPU model and GPU model. I can see you have Intel HD 4000, but more information would be helpful.

**Comment by sukhchainn** [comment] 2020-04-04 11:31
@clayjohn Godot 2 versions were working fine, were they using OpenGL 2?

I tried --video-driver GLES2 as parameter, it started Godot engine but UI was flickering and there were debugging messages like "linking failed" and so on. It started printed program of some file. I couldn't copy the error messages because I couldn't select them with my mouse.

Anyway, thanks for the help, but I think I'll stick with Godot 2.1.3

**Comment by Calinou** [comment] 2020-04-04 12:02
> @clayjohn Godot 2 versions were working fine, were they using OpenGL 2?

Yes, they used OpenGL ES 2.0 which maps to OpenGL 2.1 on desktop platforms.

**Comment by Calinou** [comment] 2020-08-26 12:36
Closing as nobody else has been able to reproduce this recently. Please comment if you can still reproduce this.

**Closed by Calinou** 2020-08-26 12:36 UTC
Labels: bug, topic:rendering

**Comment by zbhatti-dev** [comment] 2020-09-04 19:57
Hi I am encountering exactly the same error

**Comment by Calinou** [comment] 2020-09-04 20:10
@zbhatti-dev Which operating system, Godot version and graphics card model are you using?

**Comment by clayjohn** [comment] 2020-09-04 21:26
@zbhatti-dev which operating system and version of Godot are you using?

**Comment by zbhatti-dev** [comment] 2020-09-04 21:32
Windows 10; 64 bit
have tried following Godot 3.2.1, 3.2.2, 3.2.3

________________________________

**Comment by clayjohn** [comment] 2020-09-04 21:43
@zbhatti-dev can you please try updating your graphics card drivers?

If that doesn't work, please paste the output you see when attempting to run the engine.

**Comment by zbhatti-dev** [comment] 2020-09-05 11:47
Godot Engine v3.2.2.stable.official - https://godotengine.org
OpenGL ES 3.0 Renderer: Intel(R) UHD Graphics 630
ERROR: initialize: Condition "status != 0x8CD5" is true. Continuing.
   At: drivers/gles3/rasterizer_scene_gles3.cpp:5095
ERROR: initialize: Condition "status != 0x8CD5" is true. Continuing.
   At: drivers/gles3/rasterizer_scene_gles3.cpp:5095
ERROR: initialize: Condition "status != 0x8CD5" is true. Continuing.
   At: drivers/gles3/rasterizer_scene_gles3.cpp:5095
ERROR: initialize: Condition "status != 0x8CD5" is true. Continuing.
   At: drivers/gles3/rasterizer_scene_gles3.cpp:5095
ERROR: initialize: Condition "status != 0x8CD5" is true. Continuing.
   At: drivers/gles3/rasterizer_scene_gles3.cpp:5095
ERROR: initialize: Condition "status != 0x8CD5" is true. Continuing.
   At: drivers/gles3/rasterizer_scene_gles3.cpp:5095
ERROR: initialize: Condition "status != 0x8CD5" is true. Continuing.
   At: drivers/gles3/rasterizer_scene_gles3.cpp:5095
ERROR: initialize: Condition "status != 0x8CD5" is true. Continuing.
   At: drivers/gles3/rasterizer_scene_gles3.cpp:5095
ERROR: initialize: Condition "status != 0x8CD5" is true. Continuing.
   At: drivers/gles3/rasterizer_scene_gles3.cpp:5095
ERROR: initialize: Condition "status != 0x8CD5" is true. Continuing.
   At: drivers/gles3/rasterizer_scene_gles3.cpp:5095
ERROR: initialize: Condition "status != 0x8CD5" is true. Continuing.
   At: drivers/gles3/rasterizer_scene_gles3.cpp:5095
ERROR: initialize: Condition "status != 0x8CD5" is true. Continuing.
   At: drivers/gles3/rasterizer_scene_gles3.cpp:5095
ERROR: initialize: Condition "status != 0x8CD5" is true. Continuing.
   At: drivers/gles3/rasterizer_scene_gles3.cpp:5095
ERROR: initialize: Condition "status != 0x8CD5" is true. Continuing.
   At: drivers/gles3/rasterizer_scene_gles3.cpp:5095
ERROR: initialize: Condition "status != 0x8CD5" is true. Continuing.
   At: drivers/gles3/rasterizer_scene_gles3.cpp:5095
ERROR: initialize: Condition "status != 0x8CD5" is true. Continuing.
   At: drivers/gles3/rasterizer_scene_gles3.cpp:5095
ERROR: initialize: Condition "status != 0x8CD5" is true. Continuing.
   At: drivers/gles3/rasterizer_scene_gles3.cpp:5095
ERROR: initialize: Condition "status != 0x8CD5" is true. Continuing.
   At: drivers/gles3/rasterizer_scene_gles3.cpp:5095
ERROR: initialize: Condition "status != 0x8CD5" is true. Continuing.
   At: drivers/gles3/rasterizer_scene_gles3.cpp:5095
ERROR: initialize: Condition "status != 0x8CD5" is true. Continuing.
   At: drivers/gles3/rasterizer_scene_gles3.cpp:5095
ERROR: initialize: Condition "status != 0x8CD5" is true. Continuing.
   At: drivers/gles3/rasterizer_scene_gles3.cpp:5095
ERROR: initialize: Condition "status != 0x8CD5" is true. Continuing.
   At: drivers/gles3/rasterizer_scene_gles3.cpp:5095
ERROR: initialize: Condition "status != 0x8CD5" is true. Continuing.
   At: drivers/gles3/rasterizer_scene_gles3.cpp:5095
ERROR: initialize: Condition "status != 0x8CD5" is true. Continuing.
   At: drivers/gles3/rasterizer_scene_gles3.cpp:5095
ERROR: initialize: Condition "status != 0x8CD5" is true. Continuing.
   At: drivers/gles3/rasterizer_scene_gles3.cpp:5095
ERROR: initialize: Condition "status != 0x8CD5" is true. Continuing.
   At: drivers/gles3/rasterizer_scene_gles3.cpp:5095
ERROR: initialize: Condition "status != 0x8CD5" is true. Continuing.
   At: drivers/gles3/rasterizer_scene_gles3.cpp:5095
ERROR: initialize: Condition "status != 0x8CD5" is true. Continuing.
   At: drivers/gles3/rasterizer_scene_gles3.cpp:5095
ERROR: initialize: Condition "status != 0x8CD5" is true. Continuing.
   At: drivers/gles3/rasterizer_scene_gles3.cpp:5095
ERROR: initialize: Condition "status != 0x8CD5" is true. Continuing.
   At: drivers/gles3/rasterizer_scene_gles3.cpp:5095
ERROR: initialize: Directional shadow framebuffer status invalid
   At: drivers/gles3/rasterizer_scene_gles3.cpp:5120
ERROR: initialize: Condition "status != 0x8CD5" is true. Continuing.
   At: drivers/gles3/rasterizer_scene_gles3.cpp:5223
ERROR: initialize: Condition "status != 0x8CD5" is true. Continuing.
   At: drivers/gles3/rasterizer_scene_gles3.cpp:5223
ERROR: initialize: Condition "status != 0x8CD5" is true. Continuing.
   At: drivers/gles3/rasterizer_scene_gles3.cpp:5223
ERROR: initialize: Condition "status != 0x8CD5" is true. Continuing.
   At: drivers/gles3/rasterizer_scene_gles3.cpp:5223
ERROR: initialize: Condition "status != 0x8CD5" is true. Continuing.
   At: drivers/gles3/rasterizer_scene_gles3.cpp:5223
ERROR: initialize: Condition "status != 0x8CD5" is true. Continuing.
   At: drivers/gles3/rasterizer_scene_gles3.cpp:5223
ERROR: initialize: Condition "status != 0x8CD5" is true. Continuing.
   At: drivers/gles3/rasterizer_scene_gles3.cpp:5223
ERROR: initialize: Condition "status != 0x8CD5" is true. Continuing.
   At: drivers/gles3/rasterizer_scene_gles3.cpp:5223
ERROR: initialize: Condition "status != 0x8CD5" is true. Continuing.
   At: drivers/gles3/rasterizer_scene_gles3.cpp:5223
ERROR: initialize: Condition "status != 0x8CD5" is true. Continuing.
   At: drivers/gles3/rasterizer_scene_gles3.cpp:5223
ERROR: initialize: Condition "status != 0x8CD5" is true. Continuing.
   At: drivers/gles3/rasterizer_scene_gles3.cpp:5223
ERROR: initialize: Condition "status != 0x8CD5" is true. Continuing.
   At: drivers/gles3/rasterizer_scene_gles3.cpp:5223
ERROR: initialize: Condition "status != 0x8CD5" is true. Continuing.
   At: drivers/gles3/rasterizer_scene_gles3.cpp:5223
ERROR: initialize: Condition "status != 0x8CD5" is true. Continuing.
   At: drivers/gles3/rasterizer_scene_gles3.cpp:5223
ERROR: initialize: Condition "status != 0x8CD5" is true. Continuing.
   At: drivers/gles3/rasterizer_scene_gles3.cpp:5223
ERROR: initialize: Condition "status != 0x8CD5" is true. Continuing.
   At: drivers/gles3/rasterizer_scene_gles3.cpp:5223
ERROR: initialize: Condition "status != 0x8CD5" is true. Continuing.
   At: drivers/gles3/rasterizer_scene_gles3.cpp:5223
ERROR: initialize: Condition "status != 0x8CD5" is true. Continuing.
   At: drivers/gles3/rasterizer_scene_gles3.cpp:5223
ERROR: initialize: Condition "status != 0x8CD5" is true. Continuing.
   At: drivers/gles3/rasterizer_scene_gles3.cpp:5223
ERROR: initialize: Condition "status != 0x8CD5" is true. Continuing.
   At: drivers/gles3/rasterizer_scene_gles3.cpp:5223
ERROR: initialize: Condition "status != 0x8CD5" is true. Continuing.
   At: drivers/gles3/rasterizer_scene_gles3.cpp:5223
ERROR: initialize: Condition "status != 0x8CD5" is true. Continuing.
   At: drivers/gles3/rasterizer_scene_gles3.cpp:5223
ERROR: initialize: Condition "status != 0x8CD5" is true. Continuing.
   At: drivers/gles3/rasterizer_scene_gles3.cpp:5223
ERROR: initialize: Condition "status != 0x8CD5" is true. Continuing.
   At: drivers/gles3/rasterizer_scene_gles3.cpp:5223
ERROR: initialize: Condition "status != 0x8CD5" is true. Continuing.
   At: drivers/gles3/rasterizer_scene_gles3.cpp:5223
ERROR: initialize: Condition "status != 0x8CD5" is true. Continuing.
   At: drivers/gles3/rasterizer_scene_gles3.cpp:5223
ERROR: initialize: Condition "status != 0x8CD5" is true. Continuing.
   At: drivers/gles3/rasterizer_scene_gles3.cpp:5223
ERROR: initialize: Condition "status != 0x8CD5" is true. Continuing.
   At: drivers/gles3/rasterizer_scene_gles3.cpp:5223
ERROR: initialize: Condition "status != 0x8CD5" is true. Continuing.
   At: drivers/gles3/rasterizer_scene_gles3.cpp:5223
ERROR: initialize: Condition "status != 0x8CD5" is true. Continuing.
   At: drivers/gles3/rasterizer_scene_gles3.cpp:5223
ERROR: initialize: Condition "status != 0x8CD5" is true. Continuing.
   At: drivers/gles3/rasterizer_scene_gles3.cpp:5303
ERROR: initialize: Condition "status != 0x8CD5" is true. Continuing.
   At: drivers/gles3/rasterizer_scene_gles3.cpp:5303
ERROR: initialize: Condition "status != 0x8CD5" is true. Continuing.
   At: drivers/gles3/rasterizer_scene_gles3.cpp:5303
ERROR: initialize: Condition "status != 0x8CD5" is true. Continuing.
   At: drivers/gles3/rasterizer_scene_gles3.cpp:5303
ERROR: initialize: Condition "status != 0x8CD5" is true. Continuing.
   At: drivers/gles3/rasterizer_scene_gles3.cpp:5303
ERROR: initialize: Condition "status != 0x8CD5" is true. Continuing.
   At: drivers/gles3/rasterizer_scene_gles3.cpp:5303

ERROR: reflection_atlas_set_size: Condition "status != 0x8CD5" is true. Continuing.
   At: drivers/gles3/rasterizer_scene_gles3.cpp:526
ERROR: reflection_atlas_set_size: Condition "status != 0x8CD5" is true. Continuing.
   At: drivers/gles3/rasterizer_scene_gles3.cpp:526
ERROR: reflection_atlas_set_size: Condition "status != 0x8CD5" is true. Continuing.
   At: drivers/gles3/rasterizer_scene_gles3.cpp:526
ERROR: reflection_atlas_set_size: Condition "status != 0x8CD5" is true. Continuing.
   At: drivers/gles3/rasterizer_scene_gles3.cpp:526
ERROR: reflection_atlas_set_size: Condition "status != 0x8CD5" is true. Continuing.
   At: drivers/gles3/rasterizer_scene_gles3.cpp:526
ERROR: reflection_atlas_set_size: Condition "status != 0x8CD5" is true. Continuing.
   At: drivers/gles3/rasterizer_scene_gles3.cpp:526
framebuffer fail, status: 8cd6
ERROR: _render_target_allocate: Condition "status != 0x8CD5" is true.
   At: drivers/gles3/rasterizer_storage_gles3.cpp:7180

**Comment by zbhatti-dev** [comment] 2020-09-05 11:47
Please see error log above, I have reinstalled all the drivers

**Comment by Calinou** [comment] 2020-09-05 12:14
@zbhatti-dev It seems you're using a dual-GPU setup. Try forcing Godot to start on your dedicated GPU by right-clicking the executable and choosing the NVIDIA GPU in the "Run with graphics processor" menu.

**Comment by zbhatti-dev** [comment] 2020-09-05 12:34
thanks, i cant see that option on the menu - is it possible to run from the cmd prompt?

**Comment by Calinou** [comment] 2020-09-05 12:35
@zbhatti-dev Are you using a laptop with NVIDIA Optimus graphics in the first place?

**Comment by zbhatti-dev** [comment] 2020-09-05 12:50
Were using a desktop...but youve put us on the righttrack; basically the desktop was accessing the Intel GPU; this is because the cable at the back of the desktop to the monitor was connected to the intel gpu port...we changed it and connected it to the NVIDIA port...and hey presto is working!  thanks for your help...son can now carry on with his A-level Computer Studies project!

**Comment by akien-mga** [comment] 2020-09-05 13:20
Note that Godot should work fine with Intel UHD 630 too, but there too a driver update might be needed to solve this driver bug. But if you have it running on NVIDIA, it's likely going to be a better experience anyway :)
