### ISSUE TITLE
not all the InputEventScreenTouch events is triggered in _gui_input

### ISSUE THREAD

**Issue by alexzheng** [godotengine/godot#31822] opened 2019-08-31 06:13 UTC
**Godot version:3.1

**OS/device including version:**

**Issue description:**

Touch two or more fingers on the screen, two InputEventScreenTouch events is triggered with event.pressed = true, However, when release the fingers, only the last finger triggered a event with event.index =0 , event.pressed = false, all other InputEventScreenTouch events is lost.

In _input function, all these events can get.

**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by PonasKovas** [comment] 2020-07-07 14:07
Can reproduce.

**Comment by PonasKovas** [comment] 2020-07-07 14:21
minimal reproducible example:
[inputeventscreentouch.zip](https://github.com/godotengine/godot/files/4885383/inputeventscreentouch.zip)

**Comment by madmiraal** [comment] 2021-05-26 16:09
Closing as it's a duplicate of #29525.

**Closed by madmiraal** 2021-05-26 16:09 UTC
Labels: bug, topic:input
