### ISSUE TITLE
TEXTURE_PIXEL_SIZE always returns (0.0, 0.0)

### ISSUE THREAD

**Issue by markdibarry** [godotengine/godot#43148] opened 2020-10-28 00:19 UTC
**Godot version:**
3.2.3 Stable mono GLES3

**OS/device including version:**
Windows 10

**Issue description:**
When "Use Nvidia Rect Flicker Workaround" setting is active, `TEXTURE_PIXEL_SIZE` always returns `(0.0, 0.0)`.

**Steps to reproduce:**
1. Open a new project.
2. Add a sprite with a texture.
3. In project settings, under Rendering/Quality, check the "Use Nvidia Rect Flicker Workaround" box.
4. Close and reopen project for the setting to take effect.
5. Add a shader to the canvas item with the following code:
```
shader_type canvas_item;

void fragment() {
	vec4 newColor = texture(TEXTURE, UV);
	if (TEXTURE_PIXEL_SIZE.x == 0.0) newColor = vec4(0,0,0,1);
	COLOR = newColor;
}
```

**Minimal reproduction project:**
[NvidiaFlickerBug.zip](https://github.com/godotengine/godot/files/5448765/NvidiaFlickerBug.zip)

**Comment by lawnjelly** [comment] 2020-10-28 08:02
Ah, my mistake, TEXTURE_PIXEL_SIZE is calculated but not sent as a uniform, it didn't occur to me that it might be used as a builtin in custom shaders. It just needs sending, it should be quite simple (although I'll be away till sat so may have to do it then).

**Comment by akien-mga** [comment] 2021-01-05 13:40
I can't seem to reproduce the issue in 3.2.4 beta 4, was this fixed? @lawnjelly

**Comment by lawnjelly** [comment] 2021-01-05 15:15
Just taking a look, it looks like this is fixed, I must have forgot to update this issue.

In RasterizerCanvasGLES3::_batch_render_generic and GLES2:
```
	Vector2 tps;
	tex.tex_pixel_size.to(tps);
	state.canvas_shader.set_uniform(CanvasShaderGLES3::COLOR_TEXPIXEL_SIZE, tps);
```


 Not sure which PR it was that fixed, it was probably included in a bigger PR.

**Comment by akien-mga** [comment] 2021-01-05 15:21
Thanks, closing then.

**Closed by akien-mga** 2021-01-05 15:21 UTC
Labels: bug, regression, topic:shaders
