### ISSUE TITLE
Error import project

### ISSUE THREAD

**Issue by lunariusis** [godotengine/godot#3248] opened 2016-01-05 20:42 UTC
![image](https://cloud.githubusercontent.com/assets/2583605/12126971/12e098b8-b3fd-11e5-8977-92a46de3bd8a.png)

LOG

```
EXEC PATHP??: D:\develop\GODOT_SRC\godot_trunk\bin\godot.windows.opt.tools.exe
running cmdline: "D:\develop\GODOT_SRC\godot_trunk\bin\godot.windows.opt.tools.exe" "-path" "D:\develop\GODOT_SRC\godot_trunk\bin"
EXEC PATHP??: D:\develop\GODOT_SRC\godot_trunk\bin\godot.windows.opt.tools.exe
EXEC PATHP??: D:\develop\GODOT_SRC\godot_trunk\bin\godot.windows.opt.tools.exe
EXEC PATHP??: D:\develop\GODOT_SRC\godot_trunk\bin\godot.windows.opt.tools.exe
DETECTED MONITEORRRSO:R :2
ispose: Invalid call. Nonexistent function 'disconnect' in base 'Nil'.
   At: <built-in>:104
ERROR: Node::queue_delete: Condition ' !is_inside_tree() ' is true.
   At: scene\main\node.cpp:1926
ERROR: Nonexistent signal: confirmed
   At: core\object.cpp:1452
ERROR: Nonexistent signal: on_file_selected
   At: core\object.cpp:1452
ERROR: dispose: Invalid call. Nonexistent function 'is_connected' in base 'Nil'.
   At: <built-in>:41
ERROR: Node::queue_delete: Condition ' !is_inside_tree() ' is true.
   At: scene\main\node.cpp:1926


ERROR: ConfigFile::load: ConfgFile::load - D:/develop/GODOT/Ninja-Training-master/engine.cfg:15 error: Expected Identifier
   At: core\io\config_file.cpp:180


ERROR: ProjectManager::_load_recent_projects: Condition ' err!=OK ' is true. Continuing..:
   At: tools\editor\project_manager.cpp:536
ERROR OPENING FILE: icon.png
ERROR: Octree<struct VisualServerRaster::Instance,1,class DefaultAllocator>::create: Condition ' Math::is_nan(p_aabb.size.x) ' is true. returned: 0
   At: core\math\octree.h:827
ERROR: Octree<struct VisualServerRaster::Instance,1,class DefaultAllocator>::create: Condition ' Math::is_nan(p_aabb.size.x) ' is true. returned: 0
   At: core\math\octree.h:827
ERROR: Octree<struct VisualServerRaster::Instance,1,class DefaultAllocator>::create: Condition ' Math::is_nan(p_aabb.size.x) ' is true. returned: 0
   At: core\math\octree.h:827
ERROR: Octree<struct VisualServerRaster::Instance,1,class DefaultAllocator>::create: Condition ' Math::is_nan(p_aabb.size.x) ' is true. returned: 0
   At: core\math\octree.h:827
ERROR: Octree<struct VisualServerRaster::Instance,1,class DefaultAllocator>::create: Condition ' Math::is_nan(p_aabb.size.x) ' is true. returned: 0
   At: core\math\octree.h:827
ERROR: Octree<struct VisualServerRaster::Instance,1,class DefaultAllocator>::create: Condition ' Math::is_nan(p_aabb.size.x) ' is true. returned: 0
   At: core\math\octree.h:827
ERROR: Object::emit_signal: Error calling method from signal 'exit_viewport': 'KinematicBody2D(ninja.gd)::_on_VisibilityNotifier2D_exit_viewport': Method not found.
   At: core\object.cpp:1210
ERROR: PacketPeerStream::set_stream_peer: Condition ' p_peer.is_null() ' is true.
   At: core\io\packet_peer.cpp:246
WARNING: ObjectDB::cleanup: ObjectDB Instances still exist!
     At: core\object.cpp:1904
ERROR: ResourceCache::clear: Resources Still in use at Exit!
   At: core\resource.cpp:357
```

engine.cfg

```
[application]

name="Ninja Training"
main_scene="res://scenes/main.xml"
icon="icon.png"
target_fps=0

[display]

width=1280
height=720
stretch_mode="2d"
driver="GLES2"
stretch_aspect="keep_height"

[display.Android]

driver="GLES2"

[image_loader]

filter=true

[rasterizer]

use_fragment_lighting=true
fp16_framebuffer=true

[render]

default_clear_color=#ff4ca8ff
thread_model=2
```

![image](https://cloud.githubusercontent.com/assets/2583605/12127043/8b9635d8-b3fd-11e5-9606-499160a97b91.png)

**Comment by akien-mga** [comment] 2016-01-06 09:17
I think it's a duplicate of #3207, though your error log shows potentially other issues. But some of them might be specific to the game you're trying to load (ping @alketii).

**Comment by alketii** [comment] 2016-01-06 10:06
Its the default_clear_color=#ff4ca8ff (notice the number of chars), which was fixed.

**Comment by lunariusis** [comment] 2016-01-06 22:30
akien-mga
Thank you. You're probably right.

**Closed** 2016-01-07 12:07 UTC
Labels: bug, topic:core
