### ISSUE TITLE
TextureButton not working on certain parenting

### ISSUE THREAD

**Issue by AkatDeen** [godotengine/godot#14556] opened 2017-12-11 14:40 UTC
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Windows 10 64 bit, Godot 3.0 Beta 1

**Issue description:**
TextureButton not working when it parented to other nodes rather than Control node.

**Steps to reproduce:**
just try parent TextureButton to any other node than control. it won't work. (Maybe, just maybe it is how it supposed to react in 3.0 instead?)

**Comment by volzhs** [comment] 2017-12-12 08:26
![image](https://user-images.githubusercontent.com/8281454/33874251-7a3e9424-df61-11e7-9967-6aabfdd0ed26.png)

it works as expected.
can you provide a reproducible sample project?

**Comment by AkatDeen** [comment] 2017-12-12 13:28
Sorry for the mistake. end up i try to reproduce them and found out that it only happens when the button parented to the MeshInstance instead like this:

![tbnotwork](https://user-images.githubusercontent.com/34402800/33887022-5d094260-df83-11e7-9a60-7cb3e7d6532b.PNG)

**Comment by DualMatrix** [comment] 2018-09-19 21:35
Could not reproduce in master

**Comment by akien-mga** [comment] 2018-09-20 06:28
Thanks, presuming fixed in 3.1.

**Closed by akien-mga** 2018-09-20 06:28 UTC
Labels: bug, topic:core
