### ISSUE TITLE
[4.0 Beta 11] Anchors presets don't change

### ISSUE THREAD

**Issue by vmikhav** [godotengine/godot#71256] opened 2023-01-12 01:41 UTC
### Godot version

4.0 Beta 11

### System information

Windows 10, Vulkan, Radeon RX 560

### Issue description

Since Beta 11 `anchors preset` property of Control node cannot be changed from both the node inspector and the toolbar. Property value is always `Top Left`. Container Sizing values can be changed, but they have no effect.

### Steps to reproduce

Change `Anchors Preset` of `Control` node.

### Minimal reproduction project

[anchors.zip](https://github.com/godotengine/godot/files/10397370/anchors.zip)

**Comment by Calinou** [comment] 2023-01-12 02:56
Assuming it works correctly on 4.0.beta10 (is that the case? Please state so explicitly :slightly_smiling_face:):

If you can [compile the engine from source](https://docs.godotengine.org/en/stable/development/compiling/index.html), you could look into [bisecting the regression](https://docs.godotengine.org/en/stable/community/contributing/bisecting_regressions.html) to greatly speed up troubleshooting.

- 4.0.beta10's commit hash (`good`) is `d0398f62f08ce0cfba80990b21c6af4181f93fe9`.
- 4.0.beta11's commit hash (`bad`) is `91713ced81792b10fdc9367b7f355738e5d52777`.

**Comment by vmikhav** [comment] 2023-01-12 03:00
@Calinou yes, beta10 works as supposed

**Comment by justofisker** [comment] 2023-01-12 05:12
Bisected to `00b5222f66105d20817a7e25976c254114a22e60`

**Comment by akien-mga** [comment] 2023-01-12 07:56
Possible duplicate of https://github.com/godotengine/godot/issues/71178. CC @YuriSizov

**Comment by Sslaxx** [comment] 2023-01-12 10:30
If it is, it may be fixed by  #71183?

**Comment by YuriSizov** [comment] 2023-01-12 10:33
Yes, to both. It's a duplicate. And it is fixed in master.

**Closed** 2023-01-12 10:33 UTC
Labels: bug, topic:editor, regression, topic:gui

**Comment by nongvantinh** [comment] 2023-01-12 13:24
Couldn't reproduce the bug from current commit: 9802914f97
