### ISSUE TITLE
Particles aren't emiting when scale_curve begins from zero 

### ISSUE THREAD

**Issue by sash-rc** [godotengine/godot#80863] opened 2023-08-21 21:22 UTC
### Godot version

v3.6.beta3.official [21ab700f2]

### System information

Linux Ubuntu 22.04, GeForce 1060

### Issue description

`Particles` stops emitting when the first point of `Scale Curve` in `Process Material`  is zero, like with "Linear preset".
Another fact is that setting `flag_disable_z` or `flag_disable_z` cancels this effect (emitting works).

The same setup in Godot_v3.5.2-stable works without problems.

### Steps to reproduce

Just any `Particles` set up as described in Issue description

### Minimal reproduction project

N/A

**Comment by Calinou** [comment] 2023-08-21 21:33
This occurred in 4.x at some point and was resolved by https://github.com/godotengine/godot/pull/78021.

**Comment by lawnjelly** [comment] 2023-08-22 05:29
Needs MRP. Please always include MRP, no matter how simple to you, it may take time to reproduce / not reproduce on another machine etc.

I don't think I did any changes directly to `Particles` for 3.6 (or 3.5 actually, there were no changes to `GPUParticles` if I remember right, only `CPUParticles`). 3.6 has changes to `CPUParticles2D` only.

There were some general changes for interpolation but I don't think this would be likely to cause this.

On the other hand, this could be a regression due to hierarchical culling. This can fail if there is no update to the `Particles` AABB, try switching it off using `project_settings/rendering/2d/options/culling_mode` set to `Item` instead of `Node`. If this fixes it, please still include MRP so we can fix properly.

**Comment by lawnjelly** [comment] 2023-08-22 07:01
Bisected to #53852 . @Calinou buck passed. :grinning:

**Comment by sash-rc** [comment] 2023-08-22 09:11
> Needs MRP. Please always include MRP

Sorry, I just thought reproduction steps are very basic and don't require dedicated project.
But ok, will do my best next time.

**Comment by akien-mga** [comment] 2023-09-14 11:07
We should solve this before the next beta. What approach do we want to take? Revert #53852 or is there a way to keep both cases working?

**Comment by akien-mga** [comment] 2023-09-19 07:49
Fixed by #81902.

**Closed by akien-mga** 2023-09-19 07:49 UTC
Labels: bug, topic:rendering, regression, topic:particles

**Comment by lawnjelly** [comment] 2023-09-19 11:24
Strangely I couldn't seem to get this bug to reproduce in master (despite having the same code here), so I've shelved master PR for now.
