### ISSUE TITLE
Root motion fails with rotation

### ISSUE THREAD

**Issue by LasseSchnepel** [godotengine/godot#66510] opened 2022-09-27 18:36 UTC
### Godot version

3.5.stable.mono

### System information

Win 10, GLES 2/3

### Issue description

If an animation contains translation and rotation, the root motion does not match this animation and the translation is not applied correctly, even if following the TPS tutorial closely. Same behaviour also in the current Godot4 beta.

### Steps to reproduce

Create a simple rigged model in blender (one bone is enough). Add an animation with rotation and translation (it's called "Left" in the MRP). Use the exported GLB in Godot inside a KineticBody and add an AnimationTree. Use root motion to control the position of the KineticBody.
Both ingame and in the RootMotionView, the rotate+translate animation looks broken.
Inside the AnimationPlayer (with disabled AnimationTree), the animation looks fine.

### Minimal reproduction project

[rootmotion.zip](https://github.com/godotengine/godot/files/9658748/rootmotion.zip)

**Comment by Calinou** [comment] 2022-09-28 06:21
Duplicate of https://github.com/godotengine/godot/issues/58061.

**Closed by Calinou** 2022-09-28 06:21 UTC
