### ISSUE TITLE
Cmd + R to play the game opens the game window almost outside of the screen

### ISSUE THREAD

**Issue by eduardonunesp** [godotengine/godot#17979] opened 2018-04-04 19:13 UTC
![image](https://user-images.githubusercontent.com/582516/38328344-06d30f9c-3821-11e8-9ead-bd4accaa777b.png)

macOS 10.31.3

Window to preview the game is almost invisible appearing far away on the right down corner of the screen

- Open GODOT
- Download the template "Frog Path" (I think)
- Cmd + R to play the game
- Windows almost can't be seem

![image](https://user-images.githubusercontent.com/582516/38328950-a0f4e932-3822-11e8-8374-31de64740d7d.png)

> I'm using two screens the main screen is the bigger monitor although the resolution isn't greater than the macbook

**Comment by bruvzg** [comment] 2018-04-05 14:15
I can't reproduce it with my display configuration.

Could you add screenshot of `System Preferences` -> `Displays` -> `Arrangement` tab and output of `system_profiler SPDisplaysDataType` command?

**Comment by vnen** [comment] 2018-04-05 19:48
Duplicate of #16570.

**Closed by vnen** 2018-04-05 19:48 UTC
Labels: bug, topic:core
