### ISSUE TITLE
GDScript editor freeze when pressing ^ on azerty/bépo layout (dead key)

### ISSUE THREAD

**Issue by khantzen** [godotengine/godot#95257] opened 2024-08-07 19:12 UTC
### Tested versions

Godot Engine v4.2.2 stable official 15073afe3

### System information

Ubuntu 24.04 LTS

### Issue description

When being in the GDScript editor on Godot Engine, pressing `^` character freeze the software my keyboard input are not detected anymore.

The only solution I've found is to restart Godot (fortunately I can save my progress doing it)

### Steps to reproduce

Open gd file in godot editor and write `^` in it

### Minimal reproduction project (MRP)

[BugReport.zip](https://github.com/user-attachments/files/16533066/BugReport.zip)

**Comment by akien-mga** [comment] 2024-08-07 19:54
What's your keyboard layout?

**Comment by khantzen** [comment] 2024-08-07 20:09
> What's your keyboard layout?

typematrix + bépo :)

**Comment by akien-mga** [comment] 2024-08-07 20:18
Since it's bépo I assume `^` acts as a dead key?

**Comment by khantzen** [comment] 2024-08-07 20:22
> Since it's bépo I assume `^` acts as a dead key?

Kind of yeah, you press it once then the letter key and you have the letter with a `^` over it like `â`.

I'm not using this kind of character in the editor, me pressing this key just happen by accident, it's just an annoying bug.

**Comment by khantzen** [comment] 2024-08-07 20:41
@akien-mga  same issue happen with azerty layout :)

**Comment by khantzen** [comment] 2024-08-07 20:43
You won't have this issue on qwerty because the ^ happen doing "Shift + 6" and its behaviour is different there.

**Comment by HolonProduction** [comment] 2024-08-08 07:44
Ubuntu 24.04 LTS ships with a broken IBus version. Either update IBus to 1.5.30 if available or downgrade to 1.5.29-1.

Duplicate of #85664

**Closed** 2024-08-08 07:48 UTC
Labels: bug, topic:gdscript, topic:editor, needs testing
