### ISSUE TITLE
Adding a Scale Texture to a GPUParticles3D system will cause the particles to disapear in certain cases

### ISSUE THREAD

**Issue by xxSeys1** [godotengine/godot#75748] opened 2023-04-06 12:03 UTC
### Godot version

v4.0.2.stable.official [7a0977ce2]

### System information

Windows 11, Vulkan, Ryzen 9 5900X, rx 6700xt

### Issue description

When adding a CurveTexture to a GPUParticles3D's ParticleProcessingMaterial and modifying the curve, sometimes the particles will disappear/ stop drawing. This is not due to the CurveTexture's curve being at 0 all the time. Sometimes the particles will disappear instantly while other times they will go trough one emission cycle and then stop emitting.

### Steps to reproduce

**This is reproducible by but not only by**
**1.** Set up a _GPUParticles3D_ system in your scene (Add a _ParticleProcessingMaterial_, set a _mesh_ as a _draw pass_)
**2.** Go to the _Scale_ parameter in your _ProcessingMaterial_ and add a _CurveTexture_ to where it says _Scale Curve_
**3.** Expand the Curve by clicking on it
**4.** Drag the most left handle of the created curve down to 0 on the y axis and drag it a bit to the right on the x axis. Depending on how far you drag to the right, the amount of emitted particles will either decrease or emission will stop completely.

Sometimes this happens regardless where the most left handle is at. So the described method of reproducing is only one, but the rest of occasions this happens in is seemingly random.

**Using the minimal resproduction project**
In the minimal reproduction project there are 3 _CurveTextures_ (_Works_, _DecreasedEmissionCount_, _DoesNotWork_) in the _CurveTextures_ folder.

Drag the textures into the _Scale Curve_ property in the _ProcessingMaterial_. They should do what their name suggests.

I'm sorry if this is how the _Scale Curve_ is intended to work, but it does not seem so.

### Minimal reproduction project

[GPUPart Scale Curve min rep project.zip](https://github.com/godotengine/godot/files/11170354/GPUPart.Scale.Curve.min.rep.project.zip)

**Comment by Zireael07** [comment] 2023-04-06 15:40
IIRC something similar was reported recently, and this was due to bad interpolation or something?

**Comment by clayjohn** [comment] 2023-04-06 16:40
I think this may be the same as https://github.com/godotengine/godot/issues/68809

**Comment by Calinou** [comment] 2023-04-06 16:54
- Duplicate of https://github.com/godotengine/godot/issues/68809 (moving the start point's above `0.01` fixes the issue).

**Closed by Calinou** 2023-04-06 16:54 UTC
Labels: bug, topic:3d, topic:particles

**Comment by Zireael07** [comment] 2023-04-06 17:28
Thanks for finding what I half-remembered (no keywords I put in the issue tracker would show the thing I was looking for)

**Comment by DimaKiva** [comment] 2023-04-21 20:52
I confirm. GPUParticles3D are not usable after version 4.0RC1
