### ISSUE TITLE
Tilemap edition has slower framerate than usual

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#12391] opened 2017-10-24 23:07 UTC
Godot 3.0 Windows 10 64 bits
nVidia 940M

I noticed a very slow framerate when editing tilemaps (just panning or moving the tile cursor is enough to notice).
Here is a video where  I try to show it (watch til the end):

https://www.youtube.com/watch?v=trGway9DoqU

You can clearly see that the 3D editor runs smoother, and the 2D editor also runs smoother if the tilemap isn't selected. Checking "update always" improves framerate a bit (cc #11030) but in this case it isn't the only factor.

Repro:
Create a tilemap with a simple tileset and select it to bring up the editor, notice slowdown even before drawing tiles. It looks like it happens when the tile cursor moves, but I'm not sure.

**Comment by Zylann** [comment] 2018-01-01 18:18
Tried again tilemaps on latest master, noticed the same slowness.

**Comment by akien-mga** [comment] 2018-01-06 23:01
We have now entered release freeze for Godot 3.0 and want to focus only on release critical issues for that milestone. Therefore, we're moving this issue to the 3.1 milestone, though a fix may be made available for a 3.0.x maintenance release after it has been tested in the master branch during 3.1 development. If you consider that this issue is critical enough to warrant blocking the 3.0 release until fixed, please comment so that we can assess it more in-depth.

**Comment by bojidar-bg** [comment] 2018-01-28 19:44
Could confirm on 2-5 days old master (showing version rc3), as I'm on a lower-perfomance machine right now.

I was able to workaround it by setting a smaller quadrant size.

**Comment by Zylann** [comment] 2018-01-28 19:47
@bojidar-bg that's weird, I have the slowdown even without modifying the tilemap, by just moving the cursor around.

**Comment by bojidar-bg** [comment] 2018-01-29 12:42
Ok, then I guess I confirmed something else, not this :smile:

**Comment by ByTheQuietLake** [comment] 2018-06-01 05:26
@Zylann Do you still have this issue? because when i saw this issue a while back I did have see it too but now in the master build I cant seem to notice much difference in tile map editor and out of it(Win 7 RX480).

**Closed** 2018-07-01 13:14 UTC
Labels: bug, topic:editor, usability
