### ISSUE TITLE
bbcode [img] is visible when visible_characters is 0 and visible_characters_behavior is not set to Characters Before Shaping

### ISSUE THREAD

**Issue by salianifo** [godotengine/godot#86697] opened 2024-01-02 01:11 UTC
### Tested versions

- Reproducible in 4.0.stable and 4.2.1.stable

### System information

Godot v4.2.1.stable - Linux Mint 21.1 (Vera) - X11 - Vulkan (Forward+) - dedicated NVIDIA GeForce GT 730 (nvidia; 470.223.02) - AMD Ryzen 5 2600X Six-Core Processor (12 Threads)

### Issue description

When using the `[img]` tag in a RichTextLabel, the image will be shown even when `visible_characters`/`visible_ratio` is at 0, unless the `visible_characters_behavior` is set to `Characters Before Shaping`.

Expected behavior:
The image should only show up when `visible_characters`/`visible_ratio` has reached that point in the text.

### Steps to reproduce

1. Create a RichTextLabel node
2. Set the text to `This text has an image [img]res://icon.svg[/img]`
3. Set `visible_characters` to 0
4. Set `visible_characters_behavior` to anything other than `Characters Before Shaping`

### Minimal reproduction project (MRP)

N/A

**Comment by klaritan** [comment] 2024-01-07 02:13
Can confirm this issue on Android and Windows.

**Comment by estroBiologist** [comment] 2024-01-25 12:46
Having this issue as well. Looks pretty jarring when trying to embed controller icons into dialogue!

![image](https://github.com/godotengine/godot/assets/26508550/5b2cfdaf-afcd-4fdb-ab3d-4b8adb6b9a54)

**Comment by coppolaemilio** [comment] 2024-04-08 18:18
We are having this issue with Dialogic and there was a need to make a workaround. I think it should be fixed in the RichTextLabel itself rather than at a plugin level.

**Comment by bruvzg** [comment] 2024-04-08 18:23
This should be already fixed by https://github.com/godotengine/godot/pull/89395

**Comment by coppolaemilio** [comment] 2024-04-08 19:05
Yes, I can confirm that the issue is fixed in `master`. I'll close the issue, but it would be nice if you could confirm as well @salianifo 

Thanks!

**Closed by coppolaemilio** 2024-04-08 19:05 UTC
Labels: bug, topic:gui

**Comment by salianifo** [comment] 2024-04-08 20:35
Yes, I can also confirm the issue has been resolved in `master`, thanks for your work @bruvzg!
