### ISSUE TITLE
Errors when attempting to set a imagetexture for a meshinstance in godot 4.0

### ISSUE THREAD

**Issue by rayanmargham** [godotengine/godot#52040] opened 2021-08-23 23:09 UTC
### Godot version

4.0 dev(3041becc6)

### System information

Ubuntu 21.10, Vulkan,Vega 6 Graphics

### Issue description

![image](https://user-images.githubusercontent.com/69608259/130530442-d6421092-8e7c-40e9-8d5d-24c1708968b1.png)
So the issue is that it spams the Uniforms were never supplied for set (3) at the time of drawing, which are required by the pipeline error when i attempt to set a image texture to the material to a MeshInstance3D.

### Steps to reproduce

Add a meshinstance node
create a material for the node
set the "Albedo" texture to an imagetexture
watch the errors flood in

**Comment by Calinou** [comment] 2021-08-23 23:36
Duplicate of https://github.com/godotengine/godot/issues/51361.

**Closed by Calinou** 2021-08-23 23:36 UTC
