### ISSUE TITLE
External Editor doesn't work (Under certain conditions)

### ISSUE THREAD

**Issue by iseos** [godotengine/godot#77071] opened 2023-05-14 15:56 UTC
### Godot version

4.0.2

### System information

Windows 10

### Issue description

If you disable the built-in code editor in the "Editor Feature", the scripts stop opening in the external editor.
Just nothing happens when you click on the script.
This behavior is also present on version 3 of the engine as well as in version 4.

### Steps to reproduce

Go to Editor->Manage Editor Features...
And disable Script Editor
![1](https://github.com/godotengine/godot/assets/16374845/334f776f-33a5-4b29-a3ae-c939375dbc94)

Not forgetting to set up an external editor at the same time:
![2](https://github.com/godotengine/godot/assets/16374845/2156778f-9afc-47ce-8aa2-9609fa19c8f2)
![3](https://github.com/godotengine/godot/assets/16374845/6c91df10-8246-4ac6-9faf-4363d9312124)

Try to open a double shout or other script way.
![4](https://github.com/godotengine/godot/assets/16374845/9ea8319f-09dc-4230-860d-d2101ccf33e8)
And nothing will happen.

If you turn the built-in Script Editor back on, everything works fine and scripts open in an external editor.

To be fair, tested only with vscode, but I think this behavior will be with all editors.

### Minimal reproduction project

N/A

**Comment by AThousandShips** [comment] 2023-05-14 15:59
Duplicate of #74652?

**Comment by iseos** [comment] 2023-05-14 16:07
Yes, a duplicate. Strange that I could not find this issue. But in any case, a reminder of the problem.

**Comment by AThousandShips** [comment] 2023-05-14 16:09
Comment on the previous issue and go ahead and close this

**Comment by iseos** [comment] 2023-05-14 16:11
Done.

**Closed** 2023-05-14 16:11 UTC
