### ISSUE TITLE
Can't open MonoDevelop from editor

### ISSUE THREAD

**Issue by somnivore** [godotengine/godot#25590] opened 2019-02-03 20:51 UTC
**Godot version:**

919fa75803177d0dc8f03c16b6be1360140145e1 Mono

**OS/device including version:**

Ubuntu 18.10

**Issue description:**

```
ERROR: execute: Method/Function Failed.
   At: modules/mono/editor/monodevelop_instance.cpp:51.
```

When MonoDevelop is set as the IDE and a script is opened.

**Comment by neikeq** [comment] 2019-02-03 23:48
I'm closing this assuming it's a duplicate of #25592

**Closed by neikeq** 2019-02-03 23:48 UTC
