### ISSUE TITLE
Get strange black shadow on gltf2 mesh when change camera location and rotation (fixed in GLES3)

### ISSUE THREAD

**Issue by D3ZAX** [godotengine/godot#58789] opened 2022-03-05 16:28 UTC
### Godot version

3.4.3 mono

### System information

Windows10  GLES 3.0  GTX 1060 6G

### Issue description

Get strange black shadow on gltf2 mesh when change camera location and rotation, both in editor and game running. It worked fine in 3.4.2 mono version.

Correct view:
![image](https://user-images.githubusercontent.com/15343372/156891766-ad96b09e-a845-4d9e-996f-c81905d494b1.png)

Wrong view:
![image](https://user-images.githubusercontent.com/15343372/156891798-da8e1714-cb62-401a-b956-521ad7a49d67.png)

### Steps to reproduce

Open the project uploaded, in editor, move or rotator view, the stange shadow will appear and disappear.

### Minimal reproduction project

[Test.zip](https://github.com/godotengine/godot/files/8191038/Test.zip)

**Comment by tinmanjuggernaut** [comment] 2022-03-05 18:06
This is likely a duplicate of #58592

**Comment by Calinou** [comment] 2022-03-05 18:21
I can confirm this on cf970aab2, even if the `.import/` folder is removed while the editor is closed. Therefore, I'm not sure if this is a duplicate of #58592 (although it may also be related to octahedral compression).

https://user-images.githubusercontent.com/180032/156895545-fd8fc820-af61-431b-9bb2-febc29207d39.mp4

**Comment by tinmanjuggernaut** [comment] 2022-03-05 18:45
Does the face mesh have blendshapes? If so, try removing the face, saving the scene, reloading and see if it goes away. If so, it most likely is a duplicate of the other bug. If none of the meshes have blendshapes, then it would be a unique issue.

**Comment by The-O-King** [comment] 2022-03-05 21:56
The face mesh does have blendshapes, and I was able to test and see that on GLES3 things are fixed with https://github.com/godotengine/godot/pull/58808, however the GLES2 issue seen here is new, and probably related to octahedral compression/blend shapes, although I'm not sure how blend shapes are implemented in GLES2, I can look into it though

**Comment by Calinou** [comment] 2022-03-05 22:07
It might be worth checking if the GLES2 part is a regression from https://github.com/godotengine/godot/pull/48480.

**Comment by The-O-King** [comment] 2022-03-06 16:05
Thank you for pointing me to the GLES2 CPU blend shapes implementation that helped me find the issue (which was not caused by the original implementation but rather the addition of octahedral compression broke some assumptions made in that original implementation haha)

I just submitted a fix for GLES2 here: https://github.com/godotengine/godot/pull/58838

**Comment by Calinou** [comment] 2022-03-06 16:24
The GLES3 part of the issue was fixed by https://github.com/godotengine/godot/pull/58808, which is now merged. I'll keep this open to track the GLES2 issue for now.

**Comment by akien-mga** [comment] 2022-03-06 21:35
Fixed by #58808 and #58838.

**Closed by akien-mga** 2022-03-06 21:35 UTC
Labels: bug, topic:rendering, confirmed, topic:import, regression, topic:3d
