### ISSUE TITLE
Shadow mapping ignores backfaces

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#10404] opened 2017-08-17 21:10 UTC
Godot 2.1.3
Godot 3.0 alpha1
Windows 10 64 bits nVidia 940 M
Feedback from this thread: https://godotengine.org/qa/17123/render-back-faces-to-shadow-map?show=17346#c17346

Directional lights don't produce any shadow when used on backfaces. This is a must have for any optimized interior scene, or even some exterior scenes. 

Lights currently project shadow only from front faces. To be honest, I think they should project shadows from backfaces instead, it makes more sense when you think about it (or there should at least be an option if projecting shadows from front faces is required).

Edit: in fact this should be an option per mesh or per material, like: "Shadow mode: none, front, back, two-sided"

Repro:
![image](https://user-images.githubusercontent.com/1311555/29433718-a00fa16a-83a0-11e7-876a-5f9fddb13694.png)

On a game level, in 3.0:
![image](https://user-images.githubusercontent.com/1311555/29433863-32b8d8e2-83a1-11e7-9a1b-73e67f93d694.png)

In the platformer demo:
![image](https://user-images.githubusercontent.com/1311555/29435926-6f4b0a7a-83a9-11e7-955b-75a519f83f36.png)

**Comment by vnen** [comment] 2017-08-28 01:03
Isn't this solved by 7e5890d?

**Comment by Zylann** [comment] 2017-08-28 01:46
I am unable to test it, everything is black or grey since I got latest:
![image](https://user-images.githubusercontent.com/1311555/29756346-5787f00e-8ba3-11e7-8bc1-27da3d438a25.png)

**Comment by reduz** [comment] 2017-09-04 18:40
This is not a bug, this is a feature. It saves shadow mapping from having to draw extra,
Nowadays, you can select front/back facing on lights for shadow mapping, or even if you want single/double sided on objects, so it should be enough. Closing this one!

**Closed by reduz** 2017-09-04 18:40 UTC
Labels: enhancement, topic:rendering

**Comment by Zylann** [comment] 2017-09-04 18:44
> Nowadays, you can select front/back facing on lights for shadow mapping, or even if you want single/double sided on objects, so it should be enough

Well... that's basically what I wanted, but where can I select this?
Also selecting double-sided on my level is a big no-no, I tried that and performance decreased noticeably (in adition to make the level harder to edit)

**Comment by reduz** [comment] 2017-09-04 19:59
Check the light options. You can select double sided for shadows only

On Sep 4, 2017 3:44 PM, "Marc" <notifications@github.com> wrote:

Nowadays, you can select front/back facing on lights for shadow mapping, or
even if you want single/double sided on objects, so it should be enough

Well... that's basically what I wanted, but where can I select this?
Also selecting double-sided on my level is a big no-no, I tried that and
performance decreased noticeably (in adition to make the level harder to
edit)

—
You are receiving this because you modified the open/close state.

Reply to this email directly, view it on GitHub
<https://github.com/godotengine/godot/issues/10404#issuecomment-327014048>,
or mute the thread

**Comment by Zylann** [comment] 2017-09-04 20:04
Is this new? I don't see it in alpha1. Also, why is there no backface mode only? Is this a particular gl limitation?

**Comment by reduz** [comment] 2017-09-04 20:35
![image](https://user-images.githubusercontent.com/6265307/30038062-6aec258a-9197-11e7-878a-a7a286fdd8c3.png)
No, It's not in Alpha 1

**Comment by Zylann** [comment] 2017-09-04 20:45
Ok, I misunderstood your answer, it was just added and I missed it^^
