### ISSUE TITLE
ResourceSaver adds empty script line to saved file even if there's no script attached

### ISSUE THREAD

**Issue by codespren** [godotengine/godot#17689] opened 2018-03-22 09:22 UTC
**Godot version:**

Godot engine v3.0.2.stable.mono.official

**OS/device including version:**

Mac OS 10.13.3 

**Issue description:**

ResourceSaver adds empty script line to saved file when saving PackedScene even if there's no script attached.

**Steps to reproduce:**

Save a node with no script attached to it with ResourceSaver:

`string path = OS.GetUserDataDir() + "/test.res";`
`GridMap gridMap = (GridMap)FindNode("gridMap");`
`PackedScene blueprint = new PackedScene();`
`blueprint.Pack(gridMap);`
`ResourceSaver.Save(path, blueprint);`

Try to load the node with ResourceLoader. Loading seems to be successful but Godot prints following error:

0:00:15:0577 - Cannot find class test for script /Users/xxxx/Library/Application Support/Godot/app_userdata/project/test.res::1
----------
Type:Error
Description: 
Time: 0:00:15:0577
C Error: Cannot find class test for script /Users/xxxx/Library/Application Support/Godot/app_userdata/project/blueprints/test.res::1
C Source: modules/mono/csharp_script.cpp:2025
C Function: reload

Created resource file will contain the following line
`script/source = ""`
If this line is removed manually then the loading works without errors.

**Comment by codespren** [comment] 2018-06-15 08:19
I cannot reproduce this anymore in Godot 3.0.3. Whatever it was, it seems to gone away.

**Comment by akien-mga** [comment] 2018-06-15 08:29
Thanks for the update :)

**Comment by Bauxitedev** [comment] 2018-07-20 14:46
This bug is actually still valid (Godot 3.0.4 Mono), but only if you are saving the PackedScene from a C# script.
E.g. I have this C# script that should save an empty Node with nothing else in it:
```
using Godot;
using System;

public class Node : Godot.Node
{
	public override void _Ready()
	{
		var node = new Node();

		var pack = new PackedScene();
		pack.Pack(node);

		ResourceSaver.Save("res://output.tscn", pack);
	}
}
```

However, it outputs the following file:
```
[gd_scene load_steps=3 format=2]

[sub_resource type="CSharpScript" id=1]

script/source = ""

[sub_resource type="CSharpScript" id=2]

script/source = ""

[node name="" type="Node"]

script = SubResource( 1 )
```

As you can see, there are spurious included CSharpScript resources that should not be there, and the Node has a script attached, even though it shouldn't.

**Reproduction project:**
[mono_resourcesaver_bug.zip](https://github.com/godotengine/godot/files/2214344/mono_resourcesaver_bug.zip)
After the project runs it produces `output.tscn`. Check that file and you'll see the same output as above.

**Comment by Calinou** [comment] 2020-06-07 20:40
The C# part seems to be a duplicate of #27095, so I'll close this.

**Closed by Calinou** 2020-06-07 20:40 UTC
Labels: bug, topic:core
