### ISSUE TITLE
File overwriting

### ISSUE THREAD

**Issue by BBric** [godotengine/godot#2405] opened 2015-08-30 17:03 UTC
File system : 

**A.gd**:
```GDScript
# A.gd
func _init():
    pass
```
**B.gd**:
```GDScript
# B.gd
func _init():
    pass
```
- Open A.gd and B.gd in Godot and close them
- Rename B.gd with C.gd and A.gd with B.gd in the file system
- Reopen the files in Godot
- Here C and B have the same content, A is only available with the file system
- Close Godot, the scripts are saved and A is lost

An additional reason for don't save the unmodified scripts.

**Comment by akien-mga** [comment] 2015-11-09 14:38
I can confirm that messing around with the file system does not work too well with Godot right now, I've hard weird experiences with it.

**Comment by reduz** [comment] 2015-12-31 18:25
Several things changed since this issue was opened:
1) Godot will just reload what changed and ignore what was erased. 
2) There are now tools built-into godot for renaming/deleting files properly

so I guess it no longer applies, correct me if i'm wrong, but will be closing it for now

**Closed by reduz** 2015-12-31 18:25 UTC
Labels: bug, topic:editor
