### ISSUE TITLE
Export files of unsupported import types

### ISSUE THREAD

**Issue by 2dogtwo** [godotengine/godot#60747] opened 2022-05-04 06:56 UTC
### Godot version

3.4.4

### System information

windows10

### Issue description

Is there any way to export any kind of files in the project folder. Let some file types that cannot be imported in the editor can also be put into the pck file. For example, the exe file, I know that it may not be used directly after export, but it can also be copied to other locations and used again, and now I can only package it again with other tools. Does the pck resource file really need to be so demanding?
This is the content translated from the Internet, please forgive me if there is any incomprehension.

### Steps to reproduce

I don't know where I should go to report this. I don't know if it is a problem or a functional requirement, so someone can solve it.

**Comment by Listwon** [comment] 2022-05-04 11:30
Resources tab in export settings?
![obraz](https://user-images.githubusercontent.com/1554127/166672830-b9cdaa76-4d42-4bf8-9076-7cc7ace5a781.png)

**Comment by Calinou** [comment] 2022-05-04 14:08
Duplicate of https://github.com/godotengine/godot-proposals/issues/4492.

**Closed by Calinou** 2022-05-04 14:08 UTC

**Comment by 2dogtwo** [comment] 2022-05-04 20:21
> 导出设置中的资源选项卡？ ![奥布拉兹](https://user-images.githubusercontent.com/1554127/166672830-b9cdaa76-4d42-4bf8-9076-7cc7ace5a781.png)

Thanks, I misunderstood the meaning of my language, the problem is solved. It turns out that the second option is.
