### ISSUE TITLE
When writing `Color.tan` in the script editor, `tan` is highlighted as a keyword instead of a class constant

### ISSUE THREAD

**Issue by ShatReal** [godotengine/godot#45338] opened 2021-01-20 20:06 UTC
**Godot version:**

3.2.3.stable

**OS/device including version:**

Windows 10

**Issue description:**

Typed "Color.tan". "tan" was red instead of blue. I guess the editor thinks it's the "tan" function. Yes, I know that this issue is incredibly minor. :| The code works just fine.
![Annotation 2021-01-20 120617](https://user-images.githubusercontent.com/69117768/105228851-eb994d00-5b17-11eb-8473-6ed47855e0b3.png)

**Steps to reproduce:**
Type "Color.tan".

**Minimal reproduction project:**

**Comment by aaronfranke** [comment] 2021-01-21 07:45
This will be fixed with #45144 because the constant will be `Color.TAN` instead of `Color.tan`. I doubt this will be fixed in 3.2.

**Comment by KoBeWi** [comment] 2021-01-21 14:39
This is actually duplicate of #28866

**Comment by akien-mga** [comment] 2021-01-26 14:56
Fixed by #45479.

**Closed by akien-mga** 2021-01-26 14:56 UTC
Labels: bug, topic:editor
