### ISSUE TITLE
Some GDScript math functions lose precision

### ISSUE THREAD

**Issue by jonri** [godotengine/godot#27665] opened 2019-04-04 02:52 UTC
**Godot version:** master

**OS/device including version:** all

**Issue description:** Helping a Discord user with some unexpected floating point behavior, we realized that the min() function in GDScript was truncating the internal double value to a float.

**Steps to reproduce:**
This GDScript displays False:
```
var t = min(1, 0.1)
print(t == 0.1)
```

This GDScript displays True:
```
var t = min(1, 0.25)
print(t == 0.25)
```
A repeating binary decimal gets truncated so the equality fails.  An exact binary decimal with low enough precision works as expected.  Regardless of the pitfalls of comparing floating point equality, the bigger issue is that this function causes the value to needlessly lose precision.

**Source code explanation:**

- Variant always stores floating point numbers as a double: https://github.com/godotengine/godot/blob/master/core/variant.h#L144
- The implementation of the GDScript min function casts its arguments to a real_t: https://github.com/godotengine/godot/blob/master/modules/gdscript/gdscript_functions.cpp#L489
- The real_t type can be a double or a float, it appears to be a float by default: https://github.com/godotengine/godot/blob/master/core/math/math_defs.h#L112

The sign(), max(), and clamp() GDScript functions also use real_t and may be susceptible to the same problem.  Other GDScript functions such as abs() already cast the Variant to a double, which I think would fix the problem.

**Comment by jonri** [comment] 2019-04-04 11:52
Having slept on this, I hadn't considered everything outside the basic math functions either.  Something like
```
	var v = Vector2(0.1, 0.1)
	print(v.x == 0.1)
```
will exhibit the same problem.  

Looking through the code as a whole, most objects seem to make use of real_t, but there are also chunks of code that only use double.  Maybe the intent is to keep intermediate precision high for math functions?    At any rate, the solution seems less clear-cut now.  Here are some possibilities that I see:

- Do nothing, and officially state that floating point values in GDScript may NEVER be assumed equal.  Throw a GDScript warning when it can be determined that == is being used with two floats.  Maybe give GDScript developers convenience functions similar to is_equal_approx() which is used elsewhere in the engine.
- Use double for the min(), max(), and clamp() functions so that numbers that don't get mathematically manipulated can be assumed not to change.  Make sure any other mathematic functions don't drop to float and ruin the intermediate precision.
- Use real_t everywhere.  I don't know what kind of side-effects this would have on overall precision or on existing code.

**Comment by avencherus** [comment] 2019-04-04 15:04
I will add that I've noticed this at least in the `delta` of processing.  Was finding it not to be equal to 1/60.0 at 60 FPS.  Then saw it wasn't the same precision.

**Comment by aaronfranke** [comment] 2019-06-05 03:56
You should not expect floating-point numbers to have exact quality, as tiny errors happen all the time.

When Godot 3.2 comes out, you will be able to compare floats using `is_equal_approx()`. Additionally, comparing Vectors with `==` will compare with approximate equality. See https://github.com/godotengine/godot/pull/18992

When it comes to the inconsistent level of precision in Godot, the solution is for Godot to use 64-bit floats everywhere, which is already being tracked by #288

**Comment by Pr0methean** [comment] 2020-04-01 02:41
Close as duplicate of #288.

**Closed** 2020-04-01 03:50 UTC
Labels: discussion, enhancement, topic:core, topic:gdscript
