### ISSUE TITLE
Freelook and Zoom conflict

### ISSUE THREAD

**Issue by novemberist** [godotengine/godot#10516] opened 2017-08-21 20:37 UTC
**Operating system or device - Godot version:**
Arch Linux, Godot 3 master

**Issue description:**
                                                                                                                                                 
There seems to be a strange conflict between Freelook and
Zooming. Normally, scrolling with the Mouse wheel zooms in and
out (the indicator on the left moves up and down) within a certain range.

Zooming in and out (note the range):
![zoom](https://user-images.githubusercontent.com/7927471/29537143-e0531dce-86c0-11e7-9919-45f166d9b755.gif)

when Freelook is active, the mouse wheel controls the freelook
speed (the same indicator is used, but strangely in reverse) also within a range:

Setting Freelook speed to minimum:
![speed](https://user-images.githubusercontent.com/7927471/29537189-1e5d1b92-86c1-11e7-8069-64fb7050a0e2.gif)

However, both zooming and freelook speed seem to share the same "range", so
when leaving freelook mode, the zoom indicator is now where you left off in
freelook mode and thus has totally different minimum and maximum points for the
zoom, leading to strange results. (e.g. you can now zoom much more/less than before)

Attempt to zoom in closer (not possible anymore because of freelook speed):
![zoom_attempt](https://user-images.githubusercontent.com/7927471/29537233-4863f83e-86c1-11e7-907c-d3d70c4eabf6.gif)

**Comment by homer666** [comment] 2017-08-21 20:44
I think this is a duplicate of #8961. I don't quite understand the logic behind it though, but it could be worth keeping in mind.

**Comment by novemberist** [comment] 2017-08-21 20:55
My bad, sorry. But I also don't quite get the logic behind it. I suppose if you master the viewport controls at some point, this will be less of an issue or even make sense, but I can also see this causing a lot of confusion (especially when not properly explained to new users), since it is ulinke any other freelook implementation I have ever seen. and it can lead to you being stuck at very strange zoom levels.

I'd love to have freelook and normal mode to be two very seperate things, but I suppose this is just the way it was implemented.

**Comment by homer666** [comment] 2017-08-21 20:57
WHOOPS, didn't mean to delete that post. (For others reading, it was referring to #8961 as a possible dupe.)

**Comment by novemberist** [comment] 2017-08-21 21:13
This basically forces the user to "never forget to reset your freelook speed to some sane value, before leaving freelook mode, or you won't be able to use zoom in a normal way" . This makes sense if you use both modes interchangeably a lot and if you're not set on one preferred freelook speed, but instead keep changing the speed value dynamically all the time. however, this doesn't strike me as a very common use-case so this correlation should definitely be adressed in the documentation.

**Comment by Zylann** [comment] 2017-08-21 23:44
I use both modes a lot, and initially implemented them this way because the meaning of the left bar is the same: it's the zoom factor, or the size of your reference frame.
Zoom increases when you zoom (and then get slower), and decreases when you zoom out (and subsequently becoming faster to handle that large reference frame). Maximum is set to be your near plane (beyond which you can't see closer), minimum is set to be far plane (beyond which you can't see further away). It's consistent with panning as well, which is faster when zoomed out, and slower when zoomed in. And yes, the expected result is that when alternating both, you are left with consistent orbit targets and movement speeds.

It's all good and all but I made myself the same thinking as yours, it can be confusing to some users depending on usage, so I was thinking about leaving an option to make both modes work on separate variables.

**Comment by hubbyist** [comment] 2017-08-22 06:58
What about making left side indicator directly adjustable? This way logic and link between them can be understood by direct experimentation. Adjusting it directly will make things clear for every one and make it a feature I think.

**Comment by hubbyist** [comment] 2017-08-22 07:04
Besides as left side bar is the size of reference frame, may be it can have a human figure above it to represent this.

**Comment by Einlander** [comment] 2017-08-24 12:10
What messes people up is that it doesn't work the same as ANY other 3d game editor. Unity, Unreal, Atomic, Torque, Leadwerks, Hammer, 3d world studio and others use the same control scheme. And Godot is the odd man out. People don't actually expect scrolling the mouse wheel to zoom like an actual camera, the expect it to work as if the pressed the w or a key. Holding shift is the speed modifier. 
As it is people who do not use Godot as their first engine will always be confused. Imo Godot should have the same control scheme as other game engines and not a 3d modeler simply because it's not a 3d modeler.

**Comment by Zylann** [comment] 2017-08-24 12:53
I used Unity, Blender, UDK and Sketchup, and these already don't have the exact same freelook controls (game engine or not). For some it's also the default, for others it's not. Also, mouse wheel zoom isn't part of the freelook implementation but the orbit implementation.
Sure, mouse wheel can be changed to be moving forward, but doing that also implies other things, here is a discussion before it was implemented: https://github.com/godotengine/godot/issues/8260#issuecomment-291669628

**Comment by akien-mga** [comment] 2018-01-15 09:57
What's the status here? Was a consensus reached on how things should work in the current master branch?

**Comment by novemberist** [comment] 2018-01-15 10:00
To be honest, personally I've gotten used to and am  fine with the way it works now.

**Comment by akien-mga** [comment] 2018-01-15 10:02
Alright, let's close then. If there are still things to improve, they'd be better discussed in new issues based on the current 3.0 RC1 behaviour.

**Closed by akien-mga** 2018-01-15 10:02 UTC
Labels: discussion, topic:editor, usability
