### ISSUE TITLE
Renaming folder in file system throws error

### ISSUE THREAD

**Issue by addmix** [godotengine/godot#44096] opened 2020-12-04 21:49 UTC
**Godot version:**

3.2.3

**OS/device including version:**

Windows 10 64 bit AMD

**Issue description:**
Renaming a folder and only changing letter's case throws error (i.e. renaming "name" -> "Name", or vice versa)

**Steps to reproduce:**
create folder, rename, keep same letters but change the case of at least one letter.

**Minimal reproduction project:**
[Rename bug.zip](https://github.com/godotengine/godot/files/5645672/Rename.bug.zip)

**Comment by Calinou** [comment] 2020-12-04 23:13
Duplicate of https://github.com/godotengine/godot/issues/19592.

**Closed by Calinou** 2020-12-04 23:13 UTC
