### ISSUE TITLE
Every time I open a project, I will be prompted "the following files are newer on disk."

### ISSUE THREAD

**Issue by 1419427247** [godotengine/godot#65205] opened 2022-09-01 16:03 UTC
### Godot version

v4.0.alpha15.official [106b68050]

### System information

Windows10,Vulkan

### Issue description

![image](https://user-images.githubusercontent.com/33598732/187952632-f9165f10-e8df-4d1e-8003-7689d9569f04.png)
![image](https://user-images.githubusercontent.com/33598732/187953976-6596fa56-f83e-42ba-bf22-622b4139dbdd.png)
Sometimes it happens when I open a file,I'm worried that my code will be lost because of this information😥😥

### Steps to reproduce

I don't know

**Comment by Calinou** [comment] 2022-09-01 16:10
Do you have a lingering instance of the editor open in the Task Manager?

Do you have the project stored on a network drive?

**Comment by 1419427247** [comment] 2022-09-01 16:28
> 您是否在任务管理器中打开了编辑器的延迟实例？
> 
> 您是否将项目存储在网络驱动器上？

My editor settings are the default, because I tried to create an empty project and then import the existing project file into it, but it was useless

**Comment by 1419427247** [comment] 2022-09-01 16:28
> Do you have a lingering instance of the editor open in the Task Manager?
> 
> Do you have the project stored on a network drive?

My editor settings are the default, because I tried to create an empty project and then import the existing project file into it, but it was useless

**Comment by 1419427247** [comment] 2022-09-01 16:40
> Do you have a lingering instance of the editor open in the Task Manager?
> 
> Do you have the project stored on a network drive?
I found that when I click gdscript in the common folder,I found that when I click gdscript in the common folder, a prompt will pop up

https://user-images.githubusercontent.com/33598732/187967189-b57b4b84-88ab-426d-84c8-8c7288c019eb.mp4

**Comment by Ajrarn777** [comment] 2022-09-01 17:38
Confirm, same problem on my side.

**Comment by alazifk** [comment] 2022-09-01 19:04
I got this after a crash. Erasing the `.godot` folder (close Godot first) forces Godot to reimport everything and the error should disappear (as well as import settings). There probably is a less invasive way to fix this, maybe the modification date is stored in the .md5 file.

**Comment by alazifk** [comment] 2022-09-01 21:25
Deleting `.godot/editor/editor_layout.cfg` or `.godot/editor/filesystem_cache[NUMBER]` fixes the issue. The Editor should be fully closed when doing this, at least doing `Reload Current Project` will cause the corrupt data to get resaved.

Notice that only `.gd` files are affected. `editor_layout.cfg` has a variable `open_scripts=["res://...",...]`. I assume these open scripts get compared using the corrupted cache, triggering the message.

The message is the one you are supposed to get when you have a script open but it has changed on disk. Checking this when you load the project probably does not make sense, since it should just be loaded from disk. Maybe the cache file should be deleted when loading, because the deletion may have failed due to a crash earlier.

**Comment by Calinou** [comment] 2022-09-01 23:18
@Ajrarn777 Which Godot version did you reproduce this on, and which operating system are you using? If you can reproduce this on 4.0.alpha, can you reproduce this on 3.5 too (or vice versa)?

**Comment by Ajrarn777** [comment] 2022-09-02 14:27
@alazifk Yes, deleting the /.godot and /.import folder fixed the issue.
Thanks for your help.

I was using Godot 4.0.14, under windows 10.

**Comment by alazifk** [comment] 2022-09-04 09:03
In `bool ScriptEditor::_test_script_times_on_disk(Ref<Resource> p_for_script)` 
the `last_date` gets incorrectly loaded as 0.

`uint64_t last_date = edited_res->get_last_modified_time();`
The time stamp from the file "`filesystem_cache7`" it is supposed to get is correct, not sure at the moment where things go wrong.

**Comment by MrBBBaiXue** [comment] 2022-09-05 00:03
Same issue here, I placed poject under a git folder, Every time I open it, the dialog popups.

**Comment by vfreitas-** [comment] 2022-09-06 14:24
Same issue here for every gdscript file I try to open it shows this dialog. In my case I'm using Windows 11 + WSL, so my files are stored inside the linux subsystem (//wsl.localhost/Ubuntu/...). I'm using it in the same way with another project but with Godot 3.5 and everything is fine.

Deleting the .godot folder does not work for me. Followed these steps:
Closed godot -> delete .godot folder -> open godot and the project -> try to open any scene or gdscript file -> the dialog appears twice asking for confirmation

And if I do close godot and open it again in sequence it will show the dialog again (twice) with a list of every file that was left open before closing.

Works normally with a project not in WSL.

(In case anyone is wondering why my project is inside the WSL, is because I keep all my software development stuff in there - non godot projects as well)

**Comment by KieranCarden** [comment] 2022-09-20 18:26
I was getting this issue constantly throughout most of the Alpha releases, but with Beta it seems to have gone away (for me). Anyone else seeing the same, or still encountering?

**Comment by vfreitas-** [comment] 2022-09-20 18:28
It seems to have been fixed in beta here as well.

**Comment by 01010100010100100100100101000111** [comment] 2022-09-20 18:38
Same here, had the issue since Alpha 12, not had it once with Beta 1

**Comment by akien-mga** [comment] 2022-09-20 20:22
Great, closing as fixed then.

**Closed by akien-mga** 2022-09-20 20:22 UTC
Labels: bug, platform:windows, topic:editor, needs testing
