### ISSUE TITLE
Wrong editor code highlighting with verbatim token ("@")

### ISSUE THREAD

**Issue by zaevi** [godotengine/godot#34984] opened 2020-01-10 10:28 UTC
**Godot version:**
3.2.beta5.mono (official)

**OS/device including version:**
Windows 10

**Issue description:**
When using verbatim token with string(@""), editor shows wrong code highlighting as below:
![image](https://user-images.githubusercontent.com/12966814/72145856-50cf4400-33d6-11ea-8286-2885266f6890.png)

**Steps to reproduce:**
Just type @ before your string

**Comment by akien-mga** [comment] 2020-01-10 10:30
Duplicate of #32336.

**Closed by akien-mga** 2020-01-10 10:30 UTC
