### ISSUE TITLE
OpenGL: GPUParticles2D not showing after first launch on Android

### ISSUE THREAD

**Issue by kagenay** [godotengine/godot#84352] opened 2023-11-02 10:09 UTC
### Godot version

4.2.beta4

### System information

Godot v4.2.beta4 - Windows 11 22H2 - Vulkan (Mobile) - integrated Intel(R) UHD Graphics 600 (Intel Corporation; 30.0.101.1994) - Intel(R) Celeron(R) N4120 CPU @ 1.10GHz (4 Threads)

### Issue description

Godot GPUParticles2D not showing on android after running the game with remote debug/opening the game after the first remote debug so it only works if i uninstall the game and install with remote debug again, also another bug i found is, the colors of the particles are different on android and windows 

### Steps to reproduce

1. Download and open the project below.
2. Install the apk to your android device via remote debug.
3. You'll see the particles work fine for the first launch but the colors are different for both platforms.
4. Now send the apk with remote debug again or open the app after closing it and you'll see there is no particles being spawned anymore.

### Minimal reproduction project

[ParticleBugAndroid.zip](https://github.com/godotengine/godot/files/13237430/ParticleBugAndroid.zip)

**Comment by Calinou** [comment] 2023-11-02 10:13
- Related to https://github.com/godotengine/godot/issues/80331.

Given it works on the first try but not the second try, this may be related to https://github.com/godotengine/godot/issues/79955 in some way.

**Comment by kagenay** [comment] 2023-11-02 10:22
>Which Android device model and Android version are you using?

Im using a Samsung Galaxy Note 8 Exynos (SM-N950) on android 8

windows:
![image](https://github.com/godotengine/godot/assets/134976618/63a66d31-c458-4b66-87c4-1f3ac74cc3f7)

**Comment by bitsawer** [comment] 2023-11-02 13:59
Possibly a duplicate of https://github.com/godotengine/godot/issues/82419

The possible workaround is to disable Godot shader cache, see https://github.com/godotengine/godot/issues/82419#issuecomment-1736617963

**Comment by clayjohn** [comment] 2024-05-16 20:32
Seems to be a duplicate of https://github.com/godotengine/godot/issues/82419 which was fixed by https://github.com/godotengine/godot/pull/88573

**Closed by clayjohn** 2024-05-16 20:32 UTC
Labels: bug, topic:rendering, needs testing, topic:2d, topic:particles
