### ISSUE TITLE
Bezier Curve animations don't work in AnimationTree

### ISSUE THREAD

**Issue by TheHyper-Dev** [godotengine/godot#85231] opened 2023-11-22 17:43 UTC
### Godot version

4.1.3 stable

### System information

Windows 10 Compatibility Renderer

### Issue description

The bezier curve animation **seems** to be playing judging by that grey bar in the AnimationTree, but nothing moves an inch.

### Steps to reproduce

Make an animation using the bezier curve tracks.
Try using it in an AnimationTree.

### Minimal reproduction project

Nope

**Comment by AThousandShips** [comment] 2023-11-22 17:46
Please provide more details on what you are setting up and how, please attach a minimum project with the animation you've set up to make it easier to confirm this is a bug and not configuration error

**Comment by TheHyper-Dev** [comment] 2023-11-22 17:52
UPDATE:

If the RESET animation contains both bezier and normal key tracks on the same properties, it won't work with the AnimationTree. Otherwise it works.

**Comment by AThousandShips** [comment] 2023-11-22 17:54
Duplicate of https://github.com/godotengine/godot/issues/49431

**Closed by AThousandShips** 2023-11-22 17:54 UTC
Labels: topic:editor, needs testing, topic:animation
