### ISSUE TITLE
Crash when typing during autocomplete of `max()` within `match` statement

### ISSUE THREAD

**Issue by vfig** [godotengine/godot#67225] opened 2022-10-10 22:46 UTC
### Godot version

4.0 beta 2; also in v4.0.beta.custom_build.28f642097 (latest master windows build from github actions)

### System information

Windows 10

### Issue description

in the following script, when i type the `... max(0,` statement as noted in the comment block below, the editor immedately crashes.

### The script

```
extends Node3D

var actor_ap_attack:Array = [0]

func vm_execute(program:Array):
	for cmd in program:
		var actor_id:int = cmd[0]
		var opcode:String = cmd[1]
		match opcode:
			'ADD_AP_ATTACK':
				var delta_ap:int = cmd[2]
				actor_ap_attack[actor_id] = max(0, actor_ap_attack[actor_id]+delta_ap)
				# THE CRASH: insert a blank line following this comment block, immediately before
				#            the next match clause, and type the following:
				#
				#            actor_ap_attack[actor_id] = max(0,
			'ADD_AP_MOVE':
				pass 
```

### Console output and backtrace

```
Godot Engine v4.0.beta.custom_build.28f642097 - https://godotengine.org
Vulkan API 1.2.0 - Using Vulkan Device #0: NVIDIA - NVIDIA GeForce GTX 1060 6GB

Project is missing: e:/dev/godot/bug_gpuparticles3d_error_spam_not_multimesh/project.godot
Editing project: e:/dev/godot/bug_autocomplete_max_crash

Godot Engine v4.0.beta.custom_build.28f642097 - https://godotengine.org
ERROR: Condition "!windows.has(p_window)" is true.
   at: VulkanContext::window_resize (drivers\vulkan\vulkan_context.cpp:1496)
Vulkan API 1.2.0 - Using Vulkan Device #0: NVIDIA - NVIDIA GeForce GTX 1060 6GB

ERROR: Condition "font.is_null()" is true.
   at: LineEdit::_shape (scene\gui\line_edit.cpp:2202)
ERROR: Condition "font.is_null()" is true.
   at: LineEdit::_shape (scene\gui\line_edit.cpp:2202)
ERROR: Condition "font.is_null()" is true.
   at: LineEdit::_shape (scene\gui\line_edit.cpp:2202)
ERROR: Condition "font.is_null()" is true.
   at: LineEdit::_shape (scene\gui\line_edit.cpp:2202)
WARNING: FBX file import is enabled in the project settings, but no FBX2glTF path is configured in the editor settings. FBX files will not be imported.
     at: _editor_init (modules\gltf\register_types.cpp:100)
ERROR: Condition "ret.type != BOOL" is true. Returning: false
   at: Variant::in (core\variant\variant_op.cpp:1107)
ERROR: Condition "ret.type != BOOL" is true. Returning: false
   at: Variant::in (core\variant\variant_op.cpp:1107)
ERROR: Condition "ret.type != BOOL" is true. Returning: false
   at: Variant::in (core\variant\variant_op.cpp:1107)
ERROR: Condition "ret.type != BOOL" is true. Returning: false
   at: Variant::in (core\variant\variant_op.cpp:1107)
ERROR: Condition "ret.type != BOOL" is true. Returning: false
   at: Variant::in (core\variant\variant_op.cpp:1107)
ERROR: Index p_index = 1 is out of bounds (size() = 0).
   at: List<struct PropertyInfo,class DefaultAllocator>::operator [] (.\core/templates/list.h:521)

================================================================
CrashHandlerException: Program crashed
Engine version: Godot Engine v4.0.beta.custom_build (28f642097a7986867e4fb7d697764efb4db753bf)
Dumping the backtrace. Please include this when reporting the bug to the project developer.
[0] oidnUnmapBuffer
[1] oidnUnmapBuffer
[2] oidnUnmapBuffer
[3] oidnUnmapBuffer
[4] oidnUnmapBuffer
[5] oidnUnmapBuffer
[6] oidnUnmapBuffer
[7] oidnUnmapBuffer
[8] oidnUnmapBuffer
[9] oidnUnmapBuffer
[10] oidnUnmapBuffer
[11] oidnUnmapBuffer
[12] oidnUnmapBuffer
[13] oidnUnmapBuffer
[14] oidnUnmapBuffer
[15] oidnUnmapBuffer
[16] oidnUnmapBuffer
[17] oidnUnmapBuffer
[18] embree::TaskScheduler::wait
[19] embree::TaskScheduler::wait
[20] embree::TaskScheduler::wait
[21] embree::TaskScheduler::wait
[22] embree::TaskScheduler::wait
[23] embree::TaskScheduler::wait
[24] embree::TaskScheduler::wait
[25] oidnUnmapBuffer
[26] embree::TaskScheduler::wait
[27] embree::TaskScheduler::wait
[28] embree::TaskScheduler::wait
[29] embree::TaskScheduler::wait
[30] <couldn't map PC to fn name>
[31] <couldn't map PC to fn name>
[32] <couldn't map PC to fn name>
[33] <couldn't map PC to fn name>
[34] <couldn't map PC to fn name>
[35] embree::TaskScheduler::wait
[36] BaseThreadInitThunk
-- END OF BACKTRACE --
================================================================
```

### Steps to reproduce

1. open the MRP in the editor.
2. open Node3D.gd
3. type in the line of code as noted in the comment block.

### Minimal reproduction project

[bug_autocomplete_max_crash.zip](https://github.com/godotengine/godot/files/9749654/bug_autocomplete_max_crash.zip)

**Comment by Aur36** [comment] 2022-10-25 16:40
I can't reproduce it, seems like [#67389](https://github.com/godotengine/godot/pull/67389) fixed it.

**Comment by clayjohn** [comment] 2023-01-26 18:40
I can confirm this is fixed now. I tested in Beta 2 and Beta 14 and I could not reproduce in Beta 14

Closing as fixed by https://github.com/godotengine/godot/pull/67389

**Closed by clayjohn** 2023-01-26 18:40 UTC
Labels: bug, topic:gdscript, crash
