### ISSUE TITLE
No "Edit Filters" button in "Blend3" node in AnimationTree

### ISSUE THREAD

**Issue by nagasawamaki** [godotengine/godot#22923] opened 2018-10-11 03:44 UTC
**Godot version:**
Master branch

**OS/device including version:**
Windows 7

**Issue description:**
There is no "Edit Filters" button in "Blend3" node in AnimationTree

![default](https://user-images.githubusercontent.com/24987226/46779562-f8307780-cd4a-11e8-8a3b-0d6de98e7509.png)

**Comment by rcorre** [comment] 2019-03-31 22:23
Same for `Add3`.

**Comment by akien-mga** [comment] 2019-05-29 06:40
As discussed in #27571, it seems to be by design and it's not clear what the use case for filter on Blend3 would be, so closing.

**Closed by akien-mga** 2019-05-29 06:40 UTC
Labels: enhancement, topic:core

**Comment by Dankakes** [comment] 2024-11-05 00:03
Chances we can revisit?
