### ISSUE TITLE
`await signal` produces false warning

### ISSUE THREAD

**Issue by lufog** [godotengine/godot#57915] opened 2022-02-10 14:03 UTC
### Godot version

4.0.alpha.custom_build (f21a62b62)

### System information

Windows 11, Vulkan Clustered

### Issue description

Following line:
```gdscript
await $Timer.timeout
```

Throws out a warning:
```
W 0:00:01:0420   "await" keyword not needed in this case, because the expression isn't a coroutine nor a signal.
  <C++ Error>    REDUNDANT_AWAIT
  <Source>       player.gd:77
```

The game logic works fine, so I think this is a false warning.

### Steps to reproduce

-create timer
-use `await` with `timeout` signal

**Comment by akien-mga** [comment] 2022-02-10 14:14
Duplicate of #56265

**Closed by akien-mga** 2022-02-10 14:14 UTC
