### ISSUE TITLE
Crash without debugger message when using loop inside _physics_process()

### ISSUE THREAD

**Issue by KiwwiPity** [godotengine/godot#51137] opened 2021-08-01 08:39 UTC
### Godot version

3.3.2-stable Mono

### System information

Linux Debian 10, GLES3

### Issue description

**Case:**
Using a `while` loop inside a `func` called from `_physics_process()` causes a crash without any message in the debugger output.

**What Does the Code:**
Check if a raycast its at the same height as another raycast. If it isn't, move down a certain amount and repeat.

_(I know it's not the best way to do it, just an experiment)_

The main concern here is that if it crashes, then is expected to show an error message like "overflow"/"infinite_loop" or something.

### Steps to reproduce

place it inside _physics_process()

```
func check_raycast() -> void:
	while not raycast_2.is_colliding():
		if raycast_2.translate.y > raycast_1.translation.y: 
			raycast_2.translate.y = -UNIT
```

**Comment by akien-mga** [comment] 2021-08-01 08:50
Duplicate of https://github.com/godotengine/godot-proposals/issues/701.

**Closed by akien-mga** 2021-08-01 08:50 UTC
