### ISSUE TITLE
GridContainer Text Runs Under Spinbox

### ISSUE THREAD

**Issue by pixelinkmedia** [godotengine/godot#29724] opened 2019-06-12 17:24 UTC
**Godot version:**
3.1.1

**OS/device including version:**
Windows 7
Desktop

**Issue description:**
When creating a theme and adding a default font, changing the font size to 18, the GridContainer's -/+/# text goes under the Spin Box control. There is also no setting for the theme to move the Spin box right or anything. So, I looks bad, can't use for good quality looking GUI.

**Steps to reproduce:**
Add new theme, add a default font and make text 18 points or higher

![griscontainer1](https://user-images.githubusercontent.com/51757955/59372370-5d42cf80-8d15-11e9-8ef1-1f6870bd554b.jpg)

**Comment by KoBeWi** [comment] 2020-07-24 23:18
Can anyone still reproduce this bug in [Godot 3.2.3 rc1](https://godotengine.org/article/release-candidate-godot-3-2-3-rc-1) or any later release?

If yes, please ensure that an up-to-date Minimal Reproduction Project (MRP) is included in this report (a MRP is a zipped Godot project with the minimal elements necessary to reliably trigger the bug). You can upload ZIP files in an issue comment with a drag and drop.

**Comment by KoBeWi** [comment] 2020-09-28 22:18
Closing due to lack of update. Please comment if you can still reproduce this issue in the latest stable version of Godot.

**Closed by KoBeWi** 2020-09-28 22:18 UTC
Labels: bug, topic:editor
