### ISSUE TITLE
Crash on creating sky, materials etc

### ISSUE THREAD

**Issue by hackerManik3** [godotengine/godot#56436] opened 2022-01-02 16:06 UTC
### Godot version

v4.0.dev.20211210.official [21b81998b]

### System information

Device Inspiron 15-3565 ,Windows 10, CPU: AMD A6-9225 2.6Gh ,GPU:RADEON R4(Built in),Ram: 4 GB

### Issue description

ERROR: vmaMapMemory failed with error -5.
at: (drivers/vulkan/rendering_device_vulkan.cpp:1605)

in drivers/vulkan/rendering_device_vulkan.cpp line 1605, i found this code:

  

//map staging buffer (It's CPU and coherent)
  void *data_ptr = nullptr;
  {
	  VkResult vkerr = vmaMapMemory(allocator, staging_buffer_blocks[staging_buffer_current].allocation, &data_ptr);
	  ERR_FAIL_COND_V_MSG(vkerr, ERR_CANT_CREATE, "vmaMapMemory failed with error " + itos(vkerr) + ".");
  }

### Steps to reproduce

creating sky resource or material;

**Comment by Calinou** [comment] 2022-01-02 16:30
Related to https://github.com/godotengine/godot/issues/56436. My guess is that your integrated graphics are too old to support Vulkan well, in which case you should use OpenGL instead by starting the editor with the `--rendering-driver opengl3 --single-window` [command line](https://docs.godotengine.org/en/stable/getting_started/editor/command_line_tutorial.html) arguments. However, only basic 2D rendering is currently supported with the OpenGL renderer in `master`.

**Comment by Calinou** [comment] 2022-05-14 17:59
Duplicate of https://github.com/godotengine/godot/issues/56076.

**Closed by Calinou** 2022-05-14 17:59 UTC
Labels: bug, platform:windows, topic:rendering, topic:thirdparty
