### ISSUE TITLE
JSON Improperly Escaped -- Can't Read What it Wrote

### ISSUE THREAD

**Issue by Gastronok** [godotengine/godot#3334] opened 2016-01-13 00:28 UTC
Question marks ('?') in string values of dicts do not get escaped properly. Or rather, they get escaped when internet validators say they shouldn't be.

Converting a dict with a string with a question mark into a JSON string then trying to convert it back again will fail with a return value of 42. Here's code which demonstrates this:

    var json_dict = {}
    json_dict["Key"] = "Will it parse?"
    var json_string = json_dict.to_json()
    json_dict.clear()
    # Parsing the string we just created will fail.
    var return_code = json_dict.parse_json(json_string)
    print("Parsing returns error code ", return_code)

**Comment by reduz** [comment] 2016-01-13 02:54
This was fixed some days ago I think

**Comment by akien-mga** [comment] 2016-01-13 06:24
Duplicate of #3283.

**Closed by akien-mga** 2016-01-13 06:24 UTC
Labels: archived

**Comment by Gastronok** [comment] 2016-01-13 17:37
Oops, sorry! My 2.0 build is a little out of date (and I don't like re-importing all of my projects when going back to 1.1), and my Github search skills are clearly not up to par. Apologies.

**Comment by akien-mga** [comment] 2016-01-13 17:47
No problem, that's why we have a bug triage team ;) It's better to have a bug reported twice than never reported :)
