### ISSUE TITLE
Duplicating an Omnilight3D Crashes Godot

### ISSUE THREAD

**Issue by zoford** [godotengine/godot#40543] opened 2020-07-20 13:41 UTC
**Godot version:**
v4.0.dev.custom_build.9e34ba485

**OS/device including version:**
Windows 10

**Issue description:**
When you try and duplicate an Omnilight3D Godot crashes without any error messages instead of duplicating it.

**Steps to reproduce:**
Try duplicating an Omnilight3D with the right click menu or with "Ctrl+D".

**Minimal reproduction project:**
[Omnilight3D Crash.zip](https://github.com/godotengine/godot/files/4947997/Omnilight3D.Crash.zip)

**Comment by asmaloney** [comment] 2020-07-22 18:26
This crashes on macOS 10.14.6 as well (Godot Engine v4.0.dev.custom_build.0cd98ec7e @ 0cd98ec7e13038d09a77cf821e930be79026f943). Right-clicked and selected "Duplicate" from the context menu.

```
1   LocalVector<RID, unsigned int, false>::push_back(RID)                                                                                                                                          local_vector.h              57   0x103917a34 
2   RenderingServerScene::_update_instance(RenderingServerScene::Instance *)                                                                                                                       rendering_server_scene.cpp  996  0x10391622a 
3   RenderingServerScene::_update_dirty_instance(RenderingServerScene::Instance *)                                                                                                                 rendering_server_scene.cpp  2917 0x103902725 
4   RenderingServerScene::update_dirty_instances()                                                                                                                                                 rendering_server_scene.cpp  2927 0x1039035fc 
5   RenderingServerScene::free(RID)                                                                                                                                                                rendering_server_scene.cpp  2952 0x103911b08 
6   RenderingServerRaster::free(RID)                                                                                                                                                               rendering_server_raster.cpp 77   0x1038f0e41 
7   RenderingServerWrapMT::free(RID)                                                                                                                                                               rendering_server_wrap_mt.h  663  0x10394ab77 
8   Node3DEditorSelectedItem::~Node3DEditorSelectedItem()                                                                                                                                          node_3d_editor_plugin.cpp   4384 0x1023de58b 
9   Node3DEditorSelectedItem::~Node3DEditorSelectedItem()                                                                                                                                          node_3d_editor_plugin.cpp   4382 0x1023de605 
10  void memdelete<Object>(Object *)                                                                                                                                                               memory.h                    115  0x103d429a2 
11  EditorSelection::remove_node(Node *)                                                                                                                                                           editor_data.cpp             1015 0x101af845f 
12  EditorSelection::clear()                                                                                                                                                                       editor_data.cpp             1126 0x101af5b7b 
13  MethodBind0<EditorSelection>::call(Object *, Variant const * *, int, Callable::CallError&)                                                                                                     method_bind.gen.inc         147  0x101b01821 
14  Object::call(StringName const&, Variant const * *, int, Callable::CallError&)                                                                                                                  object.cpp                  890  0x103d43ede 
15  UndoRedo::_process_operation_list(List<UndoRedo::Operation, DefaultAllocator>::Element *)                                                                                                      undo_redo.cpp               289  0x103de0a53 
16  UndoRedo::redo()                                                                                                                                                                               undo_redo.cpp               333  0x103de0478 
17  UndoRedo::commit_action()                                                                                                                                                                      undo_redo.cpp               257  0x103de02d9 
18  SceneTreeDock::_tool_selected(int, bool)                                                                                                                                                       scene_tree_dock.cpp         612  0x101fc20b3 
19  void call_with_variant_args_helper<SceneTreeDock, int, bool, 0ul, 1ul>(SceneTreeDock *, void (SceneTreeDock:: *)(int, bool), Variant const * *, Callable::CallError&, IndexSequence<0ul, 1ul>) callable_method_pointer.h   132  0x101ff54fa 
20  void call_with_variant_args<SceneTreeDock, int, bool>(SceneTreeDock *, void (SceneTreeDock:: *)(int, bool), Variant const * *, int, Callable::CallError&)                                      callable_method_pointer.h   157  0x101ff5424 
...                                                                                                                                                                                                     
```

I don't understand the code well enough, but **p_instance->scenario** is _null_ at this point (in **RenderingServerScene::_update_instance()**):

```cpp
if (RSG::storage->light_get_type(p_instance->base) != RS::LIGHT_DIRECTIONAL && bake_mode != light->bake_mode) {
   if (light->bake_mode == RS::LIGHT_BAKE_DYNAMIC) {
      p_instance->scenario->dynamic_lights.erase(light->instance);
   }

   light->bake_mode = bake_mode;

   if (light->bake_mode == RS::LIGHT_BAKE_DYNAMIC) {
      p_instance->scenario->dynamic_lights.push_back(light->instance);
   }
}
```

And it's the second use that's crashing.

Does adding a check for _nullptr_ in the outermost `if` make sense? Or is there something else going on?

**Comment by akien-mga** [comment] 2020-07-23 07:57
Duplicate of #39951 according to https://github.com/godotengine/godot/issues/40543#issuecomment-662612990.

**Closed by akien-mga** 2020-07-23 07:57 UTC
Labels: bug, crash, topic:editor

**Comment by ElfWitch** [comment] 2024-12-21 10:23
This is happening again in Godot_v4.4-dev7_linux
