### ISSUE TITLE
DEPTH_TEXTURE in Spatial Fragment Shader

### ISSUE THREAD

**Issue by TheDuriel** [godotengine/godot#27029] opened 2019-03-13 22:22 UTC
**Godot version:**

3.1-stable

**OS/device including version:**

windows 7, mac os, various hardware.

**Issue description:**

The DEPTH_TEXTURE Shader uniform does not receive data unless a light in the scene has contacts set to a non 0 value. It does not need to have shadows enabled, or actually light any of the geometry.

**Steps to reproduce:**
`void fragment() {
	float depth = textureLod(DEPTH_TEXTURE, SCREEN_UV, 0.0).r;``

**Minimal reproduction project:**

**Comment by clayjohn** [comment] 2019-03-13 23:43
Duplicate of https://github.com/godotengine/godot/issues/25535

**Closed** 2019-03-14 08:04 UTC
