### ISSUE TITLE
4.2b1-mono on macOS crashes when hiding app using Command-H

### ISSUE THREAD

**Issue by hawkwood** [godotengine/godot#83579] opened 2023-10-18 19:56 UTC
### Godot version

v4.2.beta1.mono.official [b1371806a]

### System information

macOS 13.4.1 M1 MacBook Pro

### Issue description

If I have the app open to either the project list or a project open for editing, and press Command-H to hide it, the app crashes. If I use either the menu (Godot > Hide Godot) or the OS Dock "Hide" function, the app hides properly.

### Steps to reproduce

Open Godot 4.2b1 on macOS, press Command-H, see it crash.

### Minimal reproduction project

None needed.

**Comment by astillich** [comment] 2023-10-19 15:27
I can reproduce this on a 4.2.beta1 non-mono build and it's not there in 4.1.2. FWIW I have the same Mac and macOS the reporter has.

**Comment by Calinou** [comment] 2023-10-19 15:51
Can you try reproducing the issue the same steps on previous 4.2 dev builds to determine when the regression started? You can download them [here](https://downloads.tuxfamily.org/godotengine/4.2/).

cc @bruvzg

**Comment by bruvzg** [comment] 2023-10-19 15:56
Can't reproduce with current master, likely fixed by https://github.com/godotengine/godot/pull/83243

**Comment by akien-mga** [comment] 2023-10-19 15:58
Please try 4.2 beta 2.

**Comment by astillich** [comment] 2023-10-19 17:20
I can confirm that #83243 fixes the issue, the revision before the PR crashes, the one after doesn't.

**Comment by Calinou** [comment] 2023-10-19 17:27
Closing per @astillich's comment. Thanks for testing :slightly_smiling_face:

**Closed by Calinou** 2023-10-19 17:27 UTC
Labels: bug, topic:porting, confirmed, crash, regression
