### ISSUE TITLE
Lock icon not showing up next to node in Scene docker unless scene is closed and re-opened

### ISSUE THREAD

**Issue by ShatReal** [godotengine/godot#46042] opened 2021-02-15 07:03 UTC
**Godot version:**

3.2.4.rc2.official

**OS/device including version:**

Windows 10

**Issue description:**

The lock icon doesn't show up next to the node name in the Scene docker unless the scene is close and then re-opened. This doesn't happen in 3.2.3 or 3.2.4.rc1.

**Steps to reproduce:**
1. Open 3.2.4.rc2
2. Make a node that can be locked
3. Lock node
4. Observe

**Minimal reproduction project:**

**Comment by KoBeWi** [comment] 2021-02-15 11:12
Duplicate of #45964

**Closed by KoBeWi** 2021-02-15 11:12 UTC
