### ISSUE TITLE
slow processing of input events

### ISSUE THREAD

**Issue by Hinsbart** [godotengine/godot#2219] opened 2015-06-30 14:58 UTC
I'm currently working on improving joystick handling, and noticed that going wild on the analog sticks dramatically reduces performance due to parsing a large number of input events.
On low end devices (2006 laptop and xperia z2) this can drop fps down to zero with even just a single gamepad.
In my code, I'm filtering out events below a user set threshold from the hardware stream. But still, having multiple devices sending out axis events can impact performance quite a bit.

According to callgrind most of the work comes from `call_group()` in `SceneTree::input_event()`

**Comment by okamstudio** [comment] 2015-06-30 15:02
this was brought in recently, seems accumulation of input events must be
performed to improve performance

On Tue, Jun 30, 2015 at 11:58 AM, Hondres <notifications@github.com> wrote:

> I'm currently working on improving joystick handling, and noticed that
> going wild on the analog sticks dramatically reduces performance due to
> parsing a large number of input events.
> On low end devices (2006 laptop and xperia z2) this can drop fps down to
> zero with even just a single gamepad.
> In my code, I'm filtering out events below a user set threshold from the
> hardware stream. But still, having multiple devices sending out axis events
> can impact performance quite a bit.
>
> According to callgrind most of the work comes from call_group() in
> SceneTree::input_event()
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/okamstudio/godot/issues/2219>.
>



-- 

*OkamStudio*

**Comment by akien-mga** [comment] 2015-11-11 10:57
Did the sitatuation change in the current master branch, or is it still the same?

**Comment by akien-mga** [comment] 2015-11-11 11:49
More or less of duplicate of #2209.

**Closed by akien-mga** 2015-11-11 11:49 UTC
Labels: enhancement, topic:core
