### ISSUE TITLE
Local Coords Ignoring parent rotation on 3D Particles system  (4.2.2 double build)

### ISSUE THREAD

**Issue by EmanuelOR127** [godotengine/godot#90775] opened 2024-04-17 00:37 UTC
### Tested versions

- Reproducible in 4.2.2 double

### System information

Godot v4.2.2.rc unknown - Windows 10.0.22631 - Vulkan (Forward+) - integrated AMD Radeon(TM) Vega 8 Graphics (Advanced Micro Devices, Inc.; 31.0.14057.5006) - AMD Ryzen 5 3500U with Radeon Vega Mobile Gfx (8 Threads)

### Issue description

On the double version, in 3D, if a particle system has the property "Local Coords" enabled, the emmision direction will completley ignore the particles system transformation, while the particles get emitted in the right rotation.
This only happens on Vulkan, switching to GL Compatibility fixes the issue. (It still happens on Mobile renderer)

### Steps to reproduce

-Select the Forward+/Mobile renderer
-Add a 3D particles system to any scene
-Enable local coords on the particles system 
-Try to transform the particles system

### Minimal reproduction project (MRP)

N/A

**Comment by Shadetheartist** [comment] 2024-08-28 09:53
I might have come across something similar. I could not get the local coords to play nice with a custom curl noise function. I'm using a custom double precision build of the engine on 4.3 + some small cherry picked things and vulkan. 

What i discovered was that the `EMISSION_TRANSFORM ` particle process shader input constant is being sent as an identity matrix when using local coords. This blocked me from computing the local coordinates of some point after the emitter was rotated/scaled etc. I eventually rebuilt the engine with a small change to send the emission transform regardless of whether or not the `use_local_coords` flag was checked. I'm not sure what else that may effect so try it out if you're comfortable with that sort of thing. I may open my own issue/PR with more detail later.

`godot/servers/rendering/renderer_rd/storage_rd/particles_storage.cpp` line ~820

```
if (p_particles->use_local_coords) {
		// CHANGED HERE
		//RendererRD::MaterialStorage::store_transform(Transform3D(), frame_params.emission_transform);
		RendererRD::MaterialStorage::store_transform(p_particles->emission_transform, frame_params.emission_transform);
	} else {
		RendererRD::MaterialStorage::store_transform(p_particles->emission_transform, frame_params.emission_transform);
	}
```

**Comment by Shadetheartist** [comment] 2024-08-28 09:58
@BastiaanOlij `git blame` says you originally committed the above code. Do you have any insights on what the issue is, or if it's safe to store the `emission_transform` when using local coords? I'm not sure if this was just an optimization or something.

**Comment by BastiaanOlij** [comment] 2024-08-28 15:13
> @BastiaanOlij `git blame` says you originally committed the above code. Do you have any insights on what the issue is, or if it's safe to store the `emission_transform` when using local coords? I'm not sure if this was just an optimization or something.

My name probably only came up because I did a bunch of reorganisation work, I don't remember working on the particle system itself.

Whether this is safe depends on how the `emission_transform` is populated, hard to say without diving deeper into the source code

**Comment by Shadetheartist** [comment] 2024-09-20 00:01
Same issue as https://github.com/godotengine/godot/issues/73383

**Comment by akien-mga** [comment] 2024-09-20 09:37
Consolidating in #73383.

**Closed by akien-mga** 2024-09-20 09:37 UTC
Labels: bug, topic:3d, topic:particles

**Comment by EmanuelOR127** [comment] 2024-09-20 17:20
Chupa polla
