### ISSUE TITLE
Godot 4.0beta17 when stretch mode != disabled and aspect = keep/keep width/keep height Visual bugs appear when resizing the window

### ISSUE THREAD

**Issue by Toisoi** [godotengine/godot#72750] opened 2023-02-05 10:21 UTC
### Godot version

4.0beta17

### System information

Windows 11, 11th Gen Intel(R) Core(TM) i5-11320H, Intel(R) Iris(R) Xe Graphics

### Issue description

When stretch mode = canvas_item or viewport and aspect = keep or keep_width or keep_height and user resizes the window, there are visual bugs where black bars should be

### Steps to reproduce

change stretch_mode to canvas_item or viewport and aspect to keep or keep_width or keep_height, add any object to the scene and try to resize the window

### Minimal reproduction project

[text_rpg.zip](https://github.com/godotengine/godot/files/10610675/text_rpg.zip)

https://user-images.githubusercontent.com/63291809/216813520-2d759224-6d4d-405b-a30d-f1eddb716852.mp4

**Comment by pkdawson** [comment] 2023-02-05 22:23
Probably related to Intel graphics, can't reproduce on Windows 11 with an NVIDIA card.

**Comment by clayjohn** [comment] 2023-02-05 22:45
Duplicate of https://github.com/godotengine/godot/issues/71799

**Closed by clayjohn** 2023-02-05 22:45 UTC
