### ISSUE TITLE
Instant crash Win10 x64 1709 "Illegal instruction"

### ISSUE THREAD

**Issue by Jimmio92** [godotengine/godot#26243] opened 2019-02-24 16:42 UTC
**Godot version:**
Godot_v3.1-beta7_win64.exe

**OS/device including version:**
Windows 10 Pro x64 1709
Intel Core i7 920 (Nehalem) 4 core 8 thread @ 2.67GHz
SAPPHIRE AMD Radeon R9 270X
12GB DDR3 @ 1066MHz (CPU limited)

**Issue description:**
I launched the program. It crashed instantly. No output was shown.

I ran it again in my terminal of choice on Windows (msys2), and all I get is "Illegal instruction" and a crash.

I then tried to run the 32 bit version and much to my surprise, it launches as it should. This means **something somewhere is broken on the 64 bit Windows public beta build**.

**Steps to reproduce:**
Launch the program.

**Minimal reproduction project:**

Any. Didn't make it to the project chooser even.

**Comment by clayjohn** [comment] 2019-02-24 17:46
I get the same issue on ubuntu 16.04. Beta 7 will not open at all.

**Comment by hpvb** [comment] 2019-02-24 18:18
Sounds like an issue with the webm assembly then. It works on all my hardware.

**Comment by clayjohn** [comment] 2019-02-24 18:24
Is there something we can do about this? Cause right now it's a pretty big showstopper.

**Comment by hpvb** [comment] 2019-02-24 18:33
I guess we need to disable the webm optimizations again or drop support for processors older than the lakes :P

**Comment by clayjohn** [comment] 2019-02-24 18:51
Well, that's a shame. Those are not ideal options.

**Comment by hpvb** [comment] 2019-02-24 18:55
@clayjohn can you please paste the full output of `lscpu` for your box?

**Comment by clayjohn** [comment] 2019-02-24 18:56
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                2
On-line CPU(s) list:   0,1
Thread(s) per core:    1
Core(s) per socket:    2
Socket(s):             1
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 55
Model name:            Intel(R) Celeron(R) CPU  N2840  @ 2.16GHz
Stepping:              8
CPU MHz:               821.481
CPU max MHz:           2582.3000
CPU min MHz:           499.8000
BogoMIPS:              4326.40
L1d cache:             24K
L1i cache:             32K
L2 cache:              1024K
Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf pni pclmulqdq dtes64 monitor ds_cpl est tm2 ssse3 cx16 xtpr pdcm sse4_1 sse4_2 movbe popcnt tsc_deadline_timer rdrand lahf_lm 3dnowprefetch epb kaiser tsc_adjust smep erms dtherm ida arat

**Comment by hpvb** [comment] 2019-02-24 18:57
OK, the problem is almost certainly AVX1. I'll do a linux64 build for you to test with some but not all enhancements enabled. Would you mind testing it when it's done?

**Comment by clayjohn** [comment] 2019-02-24 19:00
I would be happy to. I'll be away from my laptop for the next hour or two, but I will test as soon as I am back.

**Comment by marcosdon** [comment] 2019-02-24 19:58
It happens to me too. My lscpu output:

Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              2
On-line CPU(s) list: 0,1
Thread(s) per core:  1
Core(s) per socket:  2
Socket(s):           1
NUMA node(s):        1
Vendor ID:           AuthenticAMD
CPU family:          16
Model:               6
Model name:          AMD Athlon(tm) II X2 250 Processor
Stepping:            3
CPU MHz:             800.000
CPU max MHz:         3000.0000
CPU min MHz:         800.0000
BogoMIPS:            6027.13
Virtualization:      AMD-V
L1d cache:           64K
L1i cache:           64K
L2 cache:            1024K
NUMA node0 CPU(s):   0,1
Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm 3dnowext 3dnow constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid pni monitor cx16 popcnt lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt nodeid_msr hw_pstate vmmcall npt lbrv svm_lock nrip_save

**Comment by hpvb** [comment] 2019-02-24 20:20
Can you please try this binary? https://tmm.cx/nextcloud/s/NBGBXZSkpAcWBaA (Linux x64 only)

**Comment by hpvb** [comment] 2019-02-24 21:12
Ignore the previous download, I think I found the actual issue.

**Comment by clayjohn** [comment] 2019-02-24 21:14
I actually just ran it. It worked perfectly!

**Comment by hpvb** [comment] 2019-02-24 21:19
yeah, but it's probably not the correct solution to the issue :)

**Comment by clayjohn** [comment] 2019-02-24 21:22
That makes sense. Let me know if you need me to test anything else!

**Comment by hpvb** [comment] 2019-02-24 21:48
OK, actually doing things properly may be too much of a pita for 3.1.0 at this point. Could you please try the above binary as well @marcosdon to see if this works for you? I'm going to have to redo the vpx stuff entirely but this may be enough for now.

**Comment by marcosdon** [comment] 2019-02-24 22:06
It worked!

**Comment by marcosdon** [comment] 2019-02-24 22:06
(thanks for the fast work!)

**Comment by hpvb** [comment] 2019-02-24 22:32
OK, this will be fixed in b8

**Closed** 2019-02-24 22:32 UTC

**Comment by clayjohn** [comment] 2019-02-24 22:39
@hpvb Thanks! Amazing work!

**Comment by br-n518** [comment] 2019-02-25 00:33
$ lscpu
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                2
On-line CPU(s) list:   0,1
Thread(s) per core:    1
Core(s) per socket:    2
Socket(s):             1
NUMA node(s):          1
Vendor ID:             AuthenticAMD
CPU family:            20
Model:                 2
Model name:            AMD E1-1500 APU with Radeon(tm) HD Graphics
Stepping:              0
CPU MHz:               822.000
CPU max MHz:           1480.0000
CPU min MHz:           822.0000
BogoMIPS:              2954.76
Virtualization:        AMD-V
L1d cache:             32K
L1i cache:             32K
L2 cache:              512K
NUMA node0 CPU(s):     0,1
Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc extd_apicid aperfmperf pni monitor ssse3 cx16 popcnt lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch ibs skinit wdt hw_pstate vmmcall arat npt lbrv svm_lock nrip_save pausefilter

**Comment by jimmyjonezz** [comment] 2019-02-25 10:10
If i use Godot 3.1 Beta 7_x32 - it's work, but for Godot 3.1 Beta 7_x64 - crashes.
