### ISSUE TITLE
Editor crash when accessing incorrect node

### ISSUE THREAD

**Issue by unbu** [godotengine/godot#12090] opened 2017-10-14 10:52 UTC
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Linux Fedora 26 Godot version 2.1.4 (stable)

**Issue description:**

When variable for node access is set up like this:
onready var node = get_node(node_path)
WITHOUT it being string. Entire editor crashes as soon as you try to access it.

**Steps to reproduce:**
In minimal project open the built-in script in the root node and on _ready replace pass with:
test.

For me this crashes entire editor.

**Link to minimal example project:**

[crash_bug.zip](https://github.com/godotengine/godot/files/1384601/crash_bug.zip)

**Comment by bojidar-bg** [comment] 2017-12-11 16:39
Can't reproduce on master/3.0 with the supplied test project (after conversion).
Potentially related to #10972.

Closing as likely fixed.

**Closed by bojidar-bg** 2017-12-11 16:39 UTC
Labels: bug, topic:editor, topic:gdscript
