### ISSUE TITLE
Weird auto indent issue - android

### ISSUE THREAD

**Issue by Trev57** [godotengine/godot#85341] opened 2023-11-25 07:57 UTC
### Godot version

4.1 

### System information

Android

### Issue description

When writing a script, the editor suddenly indented every line, and kept doing so until it stopped responding. Then the project would not open. Happens if a line is incomplete and it attempts to format.

### Steps to reproduce

Edit script
close script
Edit script

### Minimal reproduction project

N\A

**Comment by francocurotto** [comment] 2024-04-07 13:25
Can confirm I have the same behavior in 4.2.1 [b09f793f5]

**Comment by Mohammad9760** [comment] 2024-06-09 17:37
this might help.
from Editor settings > Text editor > Behavior turn off auto indent.
![IMG_20240609_210417_810](https://github.com/godotengine/godot/assets/79392031/79195d4a-191d-40c5-94dc-b477c9481737)
and from the Text editor itself convert tabs into spaces so that you can type 4 spaces instead of tabs.
hope this helps.

**Comment by m4gr3d** [comment] 2024-06-23 22:28
Duplicate of https://github.com/godotengine/godot/issues/70751

**Closed by m4gr3d** 2024-06-23 22:28 UTC
Labels: platform:android, topic:editor, needs testing
