### ISSUE TITLE
VARIANT_ENUM_CAST Error

### ISSUE THREAD

**Issue by primesoftware** [godotengine/godot#3630] opened 2016-02-08 20:17 UTC
I have an enum defined in a C++ class in the header file. When I go to bind it in _bind_methods as per the example in core_object, I get the following:

```
In file included from core/variant.h:46:0,
                 from modules/NewHTTPClient/include/NewHTTPClient/NewHTTPClient.h:7,
                 from modules/NewHTTPClient/NewHTTPClients.cpp:29:
modules/NewHTTPClient/NewHTTPClient.cpp: In static member function 'static void NewHTTPClient::_bind_methods()':
core/simple_type.h:97:1: error: a template declaration cannot appear at block scope
 template<>\
 ^
core/method_bind.h:89:1: note: in expansion of macro 'SIMPLE_NUMERIC_TYPE'
 SIMPLE_NUMERIC_TYPE( m_enum );\
 ^
modules/NewHTTPClient/NewHTTPClient.cpp:318:2: note: in expansion of macro 'VARIANT_ENUM_CAST'
  VARIANT_ENUM_CAST(NewHTTPClient::HTTPRequestType);
  ^
core/simple_type.h:102:1: error: a template declaration cannot appear at block scope
 template<>\
 ^
core/method_bind.h:89:1: note: in expansion of macro 'SIMPLE_NUMERIC_TYPE'
 SIMPLE_NUMERIC_TYPE( m_enum );\
 ^
modules/NewHTTPClient/NewHTTPClient.cpp:318:2: note: in expansion of macro 'VARIANT_ENUM_CAST'
  VARIANT_ENUM_CAST(NewHTTPClient::HTTPRequestType);
  ^
core/simple_type.h:107:1: error: a template declaration cannot appear at block scope
 template<>\
 ^
core/method_bind.h:89:1: note: in expansion of macro 'SIMPLE_NUMERIC_TYPE'
 SIMPLE_NUMERIC_TYPE( m_enum );\
 ^
modules/NewHTTPClient/NewHTTPClient.cpp:318:2: note: in expansion of macro 'VARIANT_ENUM_CAST'
  VARIANT_ENUM_CAST(NewHTTPClient::HTTPRequestType);
  ^
core/simple_type.h:112:1: error: a template declaration cannot appear at block scope
 template<>\
 ^
core/method_bind.h:89:1: note: in expansion of macro 'SIMPLE_NUMERIC_TYPE'
 SIMPLE_NUMERIC_TYPE( m_enum );\
 ^
modules/NewHTTPClient/NewHTTPClient.cpp:318:2: note: in expansion of macro 'VARIANT_ENUM_CAST'
  VARIANT_ENUM_CAST(NewHTTPClient::HTTPRequestType);
  ^
In file included from core/object_type_db.h:33:0,
                 from core/object.h:684,
                 from core/reference.h:32,
                 from modules/NewHTTPClient/include/NewHTTPClient/NewHTTPClient.h:8,
                 from modules/NewHTTPClient/NewHTTPClient.cpp:29:
core/method_bind.h:90:1: error: a template declaration cannot appear at block scope
 template<> \
 ^
modules/NewHTTPClient/NewHTTPClient.cpp:318:2: note: in expansion of macro 'VARIANT_ENUM_CAST'
  VARIANT_ENUM_CAST(NewHTTPClient::HTTPRequestType);
```
Here is _bind_methods:
```
void NewHTTPClient::_bind_methods() 
{
	VARIANT_ENUM_CAST(NewHTTPClient::HTTPRequestType);
	BIND_CONSTANT(GET);
	BIND_CONSTANT(PUT);
	BIND_CONSTANT(HEAD);
	BIND_CONSTANT(POST);
	BIND_CONSTANT(DELETE);
	
........
omitted for brvity
}
```
If I just use BIND_CONSTANT it works fine. If I use VARIANT_ENUM_CAST without BIND_CONSTANT the compiler spits out errors.

And the enum in NewHTTPClient.h under public:
```
enum HTTPRequestType {GET, PUT, HEAD, POST, DELETE};
```

**Comment by reduz** [comment] 2016-02-08 21:45
VARIANT_ENUM_CAST goes outside, in the .h

**Comment by primesoftware** [comment] 2016-02-09 00:32
@reduz OK, got that working now. Two more questions...

1) Do I still need to use BIND_CONSTANT if VARIANT_ENUM_CAST is called?

2) I noticed if try to access the constant in GDScript by typing NewHTTPClient.GET for instance, the code completion does not show the constant. If I type the variable name (i.e. myNewHTTPInst.GET) then I do see the constant. Why does it show when typing the variable, but not the class name?

**Comment by akien-mga** [comment] 2016-02-10 09:43
Closing as it's not a bug, but feel free to continue discussing.

**Closed by akien-mga** 2016-02-10 09:43 UTC
Labels: archived
