### ISSUE TITLE
RectangleShape2D shape slightly broken

### ISSUE THREAD

**Issue by Shadowblitz16** [godotengine/godot#66084] opened 2022-09-19 00:57 UTC
### Godot version

4.0.beta1 mono

### System information

KDE Neon 5.25

### Issue description

The polygon for RectangleShape2D is slightly broken
![image](https://user-images.githubusercontent.com/2453707/190935532-5cef7d89-e743-47a2-814d-4ba63a3e3ea7.png)

I saw this was a issue on the non mono versions in alpha also.

### Steps to reproduce

Create a CollisionShape2D with a RectangleShape2D

### Minimal reproduction project

Doesn't need it I only changed these settings in my project
![image](https://user-images.githubusercontent.com/2453707/190935628-6263f7d9-c8d2-427c-9dca-4d36c84dc7bc.png)

**Comment by kleonc** [comment] 2022-09-19 02:55
Duplicate of #56320.

**Closed by kleonc** 2022-09-19 02:55 UTC
