### ISSUE TITLE
android hangs when editor click + nodes

### ISSUE THREAD

**Issue by thunderstorms-plus** [godotengine/godot#65100] opened 2022-08-30 17:49 UTC
### Godot version

3.5 stable

### System information

Android

### Issue description

it happens that the nodes dialog opens, the choice is normal, and sometimes when you press + it freezes

### Steps to reproduce

Node +

### Minimal reproduction project

![Screenshot_20220830-204654_Godot Editor](https://user-images.githubusercontent.com/30003442/187507767-93c6376f-999b-4225-9d0d-d50993cf2f2f.jpg)
![Screenshot_20220830-204751_Godot Editor](https://user-images.githubusercontent.com/30003442/187507776-7ae8c9b4-084c-42f8-b0bf-5e6f85eabffa.jpg)

**Comment by Zireael07** [comment] 2022-08-30 17:50
Already reported but I can't find the issue, fixed by #64420

**Comment by thunderstorms-plus** [comment] 2022-08-30 17:54
> Уже сообщалось, но я не могу найти проблему, исправлено [# 64420](https://github.com/godotengine/godot/pull/64420)

Ok:)

**Comment by Calinou** [comment] 2022-08-30 18:05
Duplicate of https://github.com/godotengine/godot/issues/64166.

**Closed by Calinou** 2022-08-30 18:05 UTC
