### ISSUE TITLE
"(Unsaved changes will be lost)" is too frightening 

### ISSUE THREAD

**Issue by SuperUserNameMan** [godotengine/godot#4731] opened 2016-05-20 20:04 UTC
**Operating system or device - Godot version:**
Any version of Godot since at least 1.0betaxx on any platform

**Issue description** (what happened, and what was expected):
When you quit the editor to project list, there is this nightmarish dialog box asking you to confirm :

```
Please Confirm...x
Open Project Manager ?
(Unsaved changes will be lost)
[QUIT (and do nightmares)] [Cancel (if you're too afraid to quit)]
```

It would be cool if instead of terrorizing us, the editor was kind enough to tell us what file are not save when files are not saved.

On the other hand, when you just Quit, there is no such warning.

**Steps to reproduce:**
Quit to the project list.

**Link to minimal example project** (optional but very welcome):

**Comment by Marqin** [comment] 2016-05-21 13:20
It looks like https://github.com/godotengine/godot/blob/master/tools/editor/editor_node.cpp#L2686 doesn't have any check if there are not saved files/scenes:

```c++
case RUN_PROJECT_MANAGER: {

	if (!p_confirmed) {
		confirmation->get_ok()->set_text(TTR("Yes"));
		confirmation->set_text("Open Project Manager? \n(Unsaved changes will be lost)");
		confirmation->popup_centered_minsize();
		break;
	}
```

(or maybe it's set in that `p_confirmed`)

**Comment by bojidar-bg** [comment] 2016-07-23 09:09
The Scene close function does it this way:
````c++
if (!p_confirmed && unsaved_cache) {
	confirmation->get_ok()->set_text(TTR("Yes"));
	//confirmation->get_cancel()->show();
	confirmation->set_text(TTR("Close scene? (Unsaved changes will be lost)"));
	confirmation->popup_centered_minsize();
	break;
}

_remove_edited_scene();
````

**Comment by balloonpopper** [comment] 2017-01-29 10:47
Ideally I'd like to see the exit dialog aware of whether there's outstanding changes, but if this isn't feasible, how about a 3 option window with 
Open project manager?
1) Yes (Saves all scenes)
2) Yes (Lose any changes)
3) Cancel

**Comment by bojidar-bg** [comment] 2017-01-29 18:05
@balloonpopper Sounds cool, though it might be better named as:
1. Save changes (the changes part can be dropped)
2. Discard changes
3. Cancel
Since, having two "Yes" buttons is terrible in general.

**Comment by Noshyaar** [comment] 2017-07-24 08:30
Fixed by #9304?

**Closed** 2017-07-24 08:31 UTC
Labels: enhancement, junior job, topic:editor, usability

**Comment by b-hayes** [comment] 2020-05-11 01:01
I had this issue too where my system failed to update because Godot blocked a shutdown because it was open with no changes to be saved at all.

It should just allow the OS to close it if there are no changes.

**Comment by bojidar-bg** [comment] 2020-05-11 07:35
@b-hayes This issue has been considered fixed for the better part of the last 3 years. I would suggest opening a new issue describing the problem you are having instead of bumping this one :smiley:

**Comment by Calinou** [comment] 2020-05-11 08:02
@b-hayes #32321 will address this if it's merged.
