### ISSUE TITLE
Better steam version (64 bit and examples DLC)

### ISSUE THREAD

**Issue by Bonfi96** [godotengine/godot#4809] opened 2016-05-25 18:07 UTC
I started using godot as I discovered it on steam, though I noticed only today that the steam version is the 32 bit one, even on a 64bit os.

Also it would be cool if the examples and demos that come with the steam version would be an optional dlc

**Comment by Tetane** [comment] 2016-06-12 21:21
I just noticed that too ! I've downloaded it from steam because it's easy to have automatic updates through Steam but it installed the 32 bit version even if I have windows 10 64bit.

The Steam client is also 32bit and so are most of the games, I don't know if it is possible for the developers to put 32 and 64bit versions on steam and let it decide which one to install. 

The optional DLC for the demos is also a good idea :+1:

**Comment by ajacobsen** [comment] 2016-06-12 22:12
>  I don't know if it is possible for the developers to put 32 and 64bit versions on steam and let it decide which one to install.

At least it is possible to install both and let the user choose which one to run. I've seen some games doing this.

**Comment by nunodonato** [comment] 2016-06-13 08:07
@punto- :)

**Comment by Calinou** [comment] 2018-04-04 21:55
First of all thank you for your report and sorry for the delay.

We released Godot 3.0 in January 2018 after 18 months of work, fixing many old issues either directly, or by obsoleting/replacing the features they were referring to.

We still have hundreds of issues whose relevance/reproducibility needs to be checked against the [current stable version](https://godotengine.org/download), and that's where you can help us.
**Could you check if the issue that you described initially is still relevant/reproducible in Godot 3.0 or any newer version, and comment about it here?**

For bug reports, please also make sure that the issue contains detailed steps to reproduce the bug and, if possible, a zipped project that can be used to reproduce it right away. This greatly speeds up debugging and bugfixing tasks for our contributors.

Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

Thanks in advance.

*Note: This message is being copy-pasted to many "stale" issues (90+ days without activity). It might happen that it is not meaningful for this specific issue or appears oblivious of the issue's context, if so please comment to notify the Bugsquad about it.*

**Comment by Bonfi96** [comment] 2018-04-05 16:47
As reported on [steamdb](https://steamdb.info/app/404790/depots/) the correct version of godot should be installed on the system automatically. The demos should also now be an optional dlc which is installed by default but can be opted out. 
I'm pretty sure what I said is right but if someone can check it quickly on steam it would be great (currently traveling 😢)

**Comment by Calinou** [comment] 2018-04-05 18:07
It looks like 64-bit Windows binaries are now available in the Steam version, but export templates and demos are still included in the base installation (Steam reports Godot as using 1029 MB of disk space once installed). Thus, this issue is not fully resolved yet.

**Comment by akien-mga** [comment] 2018-11-22 09:57
I have no plans to split things as DLCs for now. Might reconsider in the future but I don't need it tracked in this issue tracker, so closing.

**Closed by akien-mga** 2018-11-22 09:57 UTC
Labels: enhancement
