### ISSUE TITLE
Dictionary variables not showing value on debug screen

### ISSUE THREAD

**Issue by arthurferrai** [godotengine/godot#9133] opened 2017-06-12 17:09 UTC
**Operating system or device - Godot version:**
MacOS 10.11.6 - Godot v2.1.3.stable.official

**Issue description:**
When current code has a `Dictionary` property, debugger doesn't show its contents. Other data types works as expected. Attached image:
<img width="780" alt="screen shot 2017-06-12 at 14 05 39" src="https://user-images.githubusercontent.com/5352649/27045815-8d855cee-4f78-11e7-9fda-0475dd86fa73.png">

**Steps to reproduce:**
Just run the attached project and take a look to debugger window.

**Link to minimal example project:**
[bug_project.zip](https://github.com/godotengine/godot/files/1068923/bug_project.zip)

**Comment by Hinsbart** [comment] 2017-06-12 21:23
Will be fixed by #8979

**Comment by bojidar-bg** [comment] 2017-06-13 10:23
Actually a duplicate of the closed #4103, which was fixed by #8612/#8613.
#8979 would make it possible to preview them the way Arrays are seen.

**Closed by bojidar-bg** 2017-06-13 10:23 UTC
