### ISSUE TITLE
 softbody mesh got stucked ?

### ISSUE THREAD

**Issue by aztecsensei** [godotengine/godot#22160] opened 2018-09-16 16:41 UTC
hello! i never done this before so im guessing please excuse my ignorance,i tried this softbody thing some months ago and it was unplayable, i couldnt use it ,then i just tried it again yesterday and i was finally able to use it but i got this problem where the mesh got stuck in the middle of the air. :(
i dont know if its a bug or my potato cant handle this feature.
any help is welcome.
thanks.

here some video:
https://streamable.com/4sjcl

**Godot version:**

alpha.calinou.561a777

**OS/device including version:**

windows 7 32 bits/gt 710 /driver : 391.35 - WHQL

**Issue description:**

the hat(softbody)get stuck in an object collision.

 

**Steps to reproduce:**
just the normal use.nothing rare.

**Minimal reproduction project:**

[Nature_Scene.zip](https://github.com/godotengine/godot/files/2402793/Nature_Scene.zip)

**Comment by AndreaCatania** [comment] 2018-09-19 16:53
I need a sample project to check it. But I think that the problem is that you didn't attached the point correctly.

After selecting it, (when the point become blue) you need to go in the inspector and set the spatial that the point should follow.

**Comment by aztecsensei** [comment] 2018-09-20 19:45
> I need a sample project to check it. But I think that the problem is that you didn't attached the point correctly.
> 
> After selecting it, (when the point become blue) you need to go in the inspector and set the spatial that the point should follow.

hello, thanks for answer , i think i followed the right settings. but the HAT  is still getting stuck in the tree. :(

here its the scene:  
[Nature_Scene.zip](https://github.com/godotengine/godot/files/2402813/Nature_Scene.zip)

**Comment by AndreaCatania** [comment] 2018-09-22 07:54
I can't reproduce it: https://www.youtube.com/watch?v=DrdyMnLoCdE can you please give me a better idea on how can I reproduce it?
thanks you in advance

**Comment by aztecsensei** [comment] 2018-09-22 15:26
hello, the error happends when you touch the tree in the front ,like this pic:
![error](https://user-images.githubusercontent.com/33324484/45918782-a4b8c100-be51-11e8-9938-d1bc9f97011f.jpg)

thanks for helping.

**Comment by akien-mga** [comment] 2020-01-08 12:02
I tried the project, the carpet doesn't seem to get stuck in the tree, but it lags *a lot* when colliding with the tree.

**Comment by KoBeWi** [comment] 2020-12-09 23:42
Can anyone still reproduce this bug in Godot 3.2.3 or any later release?

**Comment by JosephHalter** [comment] 2021-03-10 08:39
I couldn't reproduce it with with Godot 3.2.4.rc2 on Mac.

**Comment by akien-mga** [comment] 2021-03-10 08:49
Thanks, closing then.

**Closed by akien-mga** 2021-03-10 08:49 UTC
Labels: bug, topic:physics
