### ISSUE TITLE
Grid shortcut from azerty keyboard

### ISSUE THREAD

**Issue by Hazlar** [godotengine/godot#65837] opened 2022-09-15 17:18 UTC
### Godot version

3.5

### System information

Windows 10

### Issue description

Hello,
Nothing really bad, the shortcut key to display the grid in French language on godot is Control + apostrophe ( ' or key 4 of the accents zone, parentheses, etc ).
However it doesn't work.

### Steps to reproduce

I modified the shortcut in order to know which key was considered as an apostrophe for godot and it is therefore the ² key. For godot the apostrophe key as well as all accents, parentheses etc. keys are considered in the form 1 2 3 4 5 6 7 8 9 0 . (I checked that I was not caps locked).

That's nothing bad :)

**Comment by Calinou** [comment] 2022-09-15 19:35
Duplicate of https://github.com/godotengine/godot/issues/65275 (same cause).

**Closed by Calinou** 2022-09-15 19:35 UTC
