### ISSUE TITLE
Label + [autowrap] in VBoxContainer changes its size at startup (like line_spacing)

### ISSUE THREAD

**Issue by FlankeR-46** [godotengine/godot#74052] opened 2023-02-27 14:19 UTC
### Godot version

v4 RC3 - RC6

### System information

Windows 10

### Issue description

If a Label with any autowrap enabled is in the VBoxContainer, then depending on the type of autowrap, the Label size changes along the Y axis when it is first displayed (or the project is launched). As if at this moment the line_spacing parameter increases. If you change line_spacing through the code after the program is launched (the project file is attached), then everything immediately falls into place, and in all the Labels of this container.
I understand that this is not a great problem and it can be circumvented with one line of code, however, I spent several hours trying to figure out why my Popup window does not take the correct size at the time of the first call, and why everything falls into place after the second call. It turns out I had a VBoxContainer with Labels there, which behaved like this.
PS: changing the size of the main window, apparently, leads to a forced redrawing of the Labels, and also everything falls into place.
![label_test](https://user-images.githubusercontent.com/126438573/221585966-e7820fbe-d725-4934-9a36-302213514173.png)

### Steps to reproduce

![image](https://user-images.githubusercontent.com/126438573/221586385-8876c807-8d16-44a7-ad5e-f8249cfb8612.png)
The autowrap parameter for Labels should be different from OFF

### Minimal reproduction project

The project is attached. By clicking on the buttons or changing the screen size, you can see this issue.
[_labels_test.zip](https://github.com/godotengine/godot/files/10840488/_labels_test.zip)

**Comment by FlankeR-46** [comment] 2023-02-27 14:29
PPS: After downloading the project, you will see that the Y-dimensions of the VBoxContainers have changed in the same way as when you first started it. But if you change the size with your hands, they immediately take the right size.
![image](https://user-images.githubusercontent.com/126438573/221590489-b3683572-78f5-4e94-944c-bb1574f92119.png)

**Comment by Rindbee** [comment] 2023-04-24 11:53
https://github.com/godotengine/godot/blob/f178cad04a39bc40e759ef50675606b12bb07fff/scene/gui/label.cpp#L618-L620

https://github.com/godotengine/godot/blob/f178cad04a39bc40e759ef50675606b12bb07fff/scene/gui/label.cpp#L91

https://github.com/godotengine/godot/blob/f178cad04a39bc40e759ef50675606b12bb07fff/scene/gui/label.cpp#L155-L158

https://github.com/godotengine/godot/blob/f178cad04a39bc40e759ef50675606b12bb07fff/scene/gui/label.cpp#L627


These **auto**/**smart** options will cause issues when calculating `get_minimum_size()`, `height` and `width` are dependent.

**Comment by hsandt** [comment] 2023-05-02 16:59
Confirmed with other containers such as the Panel Container, which makes the extra size obvious thanks to the background:

Hierarchy:
![image](https://user-images.githubusercontent.com/1067772/235731776-3fa7013f-6338-4ce3-8a83-f17bc1c5f873.png)

Appearance in editor with any number of words, no wrap, shows expected result:
![image](https://user-images.githubusercontent.com/1067772/235731855-a3881e07-b71b-4d31-971e-39cd5d642656.png)

Runtime is same. Closing and reopening the scene gives same result.

2 words, Arbitrary wrap gives the same result in editor, but at runtime, box is bigger vertically:
![image](https://user-images.githubusercontent.com/1067772/235732265-f21ce026-ee89-4d0f-acab-b0a0ba6e9e68.png)

Closing and reopening the scene shows a panel even bigger:
![image](https://user-images.githubusercontent.com/1067772/235732470-d89e5883-fd95-4904-8eb0-8224dfd1a43f.png)

If you play from here, the runtime will still be as before, not as big.

2 words, Word wrap shows expected result (note I closed and reopened scene to refresh the buggy view from Arbitrary autowrap)

3 words, Word wrap surprisingly triggers the bug again:
![image](https://user-images.githubusercontent.com/1067772/235732938-02460db1-40ee-48b9-adcd-2db29282c924.png)

(the length of each word doesn't matter, only the count; as if each word was adding a ghost line)

Closing and reopening the scene will also show a bigger box, although not as big as arbitrary:
![image](https://user-images.githubusercontent.com/1067772/235733204-ce93d3ae-77d9-45d0-b239-287a2377e198.png)

From here, every extra word will increase the box size after closing and reopening scene, as if adding a ghost line. However, runtime box won't get bigger.

Word (Smart) wrap is similar, but it triggers the bug at runtime even for 1 word, and after reopen scene, the box tends to be bigger.

**Comment by Rindbee** [comment] 2023-05-27 12:31
After `Control::_update_minimum_size()` is called, `data.last_minimum_size` should be the latest `get_combined_minimum_size()`, but not for the cases here.

https://github.com/godotengine/godot/blob/2210111eb5e8bac6a476227c01205ac44745e21e/scene/gui/control.cpp#L1585-L1592

After the `minimum_size_changed` signal is emitted, the `BoxContainer` resort child nodes will cause the `get_combined_minimum_size()` of `Lable` to change. That is, `data.last_minimum_size` is out of date at this time.

**Comment by Rindbee** [comment] 2023-06-01 13:24
If you observe the changes of various values, it is easier to find the cause of this issue. 

https://github.com/godotengine/godot/blob/2210111eb5e8bac6a476227c01205ac44745e21e/scene/gui/control.cpp#L1588-L1592

https://github.com/godotengine/godot/blob/2210111eb5e8bac6a476227c01205ac44745e21e/scene/gui/control.cpp#L1737


Add print code before and after comparison and before notification. 
```c++
print_line(data.last_minimum_size, data.minimum_size_cache, data.minimum_size_valid, data.size_cache, this, "before/after comparison", minsize);
```

Compile, then use the compiled build to run the following test project via the command line.
```shell
godot  --path path/to/project
```

[label-test.zip](https://github.com/godotengine/godot/files/11625510/label-test.zip) (please import the project in advance)


Output:

```shell
(0, 0) (0, 0) true (0, 0) Control:<Control#26541556875> before comparison (0, 0)
(0, 0) (0, 0) true (0, 0) Control:<Control#26541556875> after comparison (0, 0)
(0, 0) (0, 0) true (956, 1033) Control:<Control#26541556875> before NOTIFICATION_RESIZED
(0, 0) (1, 26) false (116, 26) VBoxContainer:<VBoxContainer#26575111309> before comparison (1, 26)
(1, 26) (1, 26) true (116, 26) VBoxContainer:<VBoxContainer#26575111309> after comparison (1, 26)
(0, 0) (1, 26) true (0, 0) Label:<Label#26608665747> before comparison (1, 26)
(1, 26) (1, 26) true (1, 26) Label:<Label#26608665747> before NOTIFICATION_RESIZED
[_on_minimum_size_changed] get_combined_minimum_size(): (1, 26) size: (1, 26)
(1, 26) (1, 26) true (1, 26) Label:<Label#26608665747> after comparison (1, 26)
(1, 26) (1, 52) false (1, 52) Label:<Label#26608665747> before NOTIFICATION_RESIZED
(1, 26) (1, 78) false (116, 78) VBoxContainer:<VBoxContainer#26575111309> before NOTIFICATION_RESIZED
(1, 26) (1, 78) true (1, 78) Label:<Label#26608665747> before NOTIFICATION_RESIZED
(0, 0) (0, 0) true (956, 1033) Control:<Control#26541556875> before comparison (0, 0)
(0, 0) (0, 0) true (956, 1033) Control:<Control#26541556875> after comparison (0, 0)
(1, 26) (1, 78) true (116, 78) VBoxContainer:<VBoxContainer#26575111309> before comparison (1, 78)
(1, 78) (1, 78) true (116, 78) VBoxContainer:<VBoxContainer#26575111309> after comparison (1, 78)
(1, 26) (1, 78) true (116, 78) Label:<Label#26608665747> before NOTIFICATION_RESIZED
(1, 78) (1, 78) true (116, 78) VBoxContainer:<VBoxContainer#26575111309> before comparison (1, 78)
(1, 78) (1, 78) true (116, 78) VBoxContainer:<VBoxContainer#26575111309> after comparison (1, 78)
(1, 26) (1, 26) false (116, 78) Label:<Label#26608665747> before comparison (1, 26)
(1, 26) (1, 26) false (116, 78) Label:<Label#26608665747> after comparison (1, 26)
```

**Closed** 2023-06-02 12:02 UTC
Labels: bug, confirmed, topic:gui

**Comment by Rindbee** [comment] 2023-06-12 13:43
If the value changes are described in the order of time, the changes are shown in the following table, this is the value change during two consecutive `_update_minimum_size()` calls of the child control:

| time | data.last_minimum_size | data.minimum_size_cache | explanation |
| :----: | :---------: | :--------: | :-----: |
| Ti | V0 => Vi (changed) | Vi | in `_update_minimum_size()` (**child**)|
| ... | Vi | ... | ... |
| Tj | Vi | Vj | ... |
| ... | Vi | ... | ... |
| Tk | Vi | Vk | in `_update_minimum_size()` (**parent**) |
| ... | Vi | ... | ... |
| Tm | Vi | Vm |...|
| ... | Vi | ... | ... |
| Tn | Vi => Vi (no changed) | Vm => Vi | in `_update_minimum_size()` (**child**) |

There are two key points:
1. Not sure which value is used when the parent container updates the minimum size;
2. At Tn, the `minimum_size_changed` signal is not emitted because the values are equal (`data.last_minimum_size == data.minimum_size_cache`). So the parent container is not updating its minimum size with the correct child minimum size again.


This issue  happened earlier, #78009 ensured the correct size early by `_size_changed()`.

My suggestion is to emit the `minimum_size_changed` signal at time Tn since `data.minimum_size_cache` ever changed.

I'm worried about something that might be similar, but that happens at other times, since `_size_changed()` isn't a public method after all, or maybe I'm overly worried.

**Comment by YuriSizov** [comment] 2023-06-12 15:05
> since `_size_changed()` isn't a public method after all

I considered making it accessible publicly, so other classes could request a check on the actual size when they expect there might be one. But I couldn't really come up with a case where some control would cause chances in its actual size but not its minimum size.
