### ISSUE TITLE
MeshLibrary Item name field entering text in reverse

### ISSUE THREAD

**Issue by FreeThings** [godotengine/godot#69244] opened 2022-11-27 06:00 UTC
### Godot version

v4.0-beta6

### System information

Windows 10

### Issue description

When trying to edit the name field of an item in the MeshLibrary, the text is entered in reverse.

https://user-images.githubusercontent.com/48502134/204121390-853175e8-2bb7-4435-808b-4f5722ba7129.mp4

### Steps to reproduce

1. Create a MeshLibrary
2. Add an Item to the mesh library
3. Attempt to edit the name of said Item

### Minimal reproduction project

[mesh_library_error_project.zip](https://github.com/godotengine/godot/files/10097628/mesh_library_error_project.zip)

**Comment by Zireael07** [comment] 2022-11-27 10:13
Related to several already reported issues. Something something debugger focus

**Comment by RumblingTurtle** [comment] 2022-11-29 06:54
Duplicate of #63549. Same issue was found in SkeletonModification3DLookAt #62876. Both have solutions

**Closed** 2022-11-29 07:29 UTC
Labels: bug, topic:core
