### ISSUE TITLE
Editor crashes when trying to enable Physics in .blend import settings on this specific model

### ISSUE THREAD

**Issue by matjlars** [godotengine/godot#87729] opened 2024-01-30 05:36 UTC
### Tested versions

I am using v4.2.stable.official [46dc27791]

### System information

Godot v4.2.stable - Windows 10.0.22621 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1660 Ti (NVIDIA; 31.0.15.3118) - Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 Threads)

### Issue description

I am trying to enable Physics in the .blend import settings with this specific .blend file. When I check the "Physics" check box, it freezes for a few seconds and then crashes.

I am not sure, but I suspect that this model is breaking the "decompose convex" algorithm because it tries to execute that algorithm normally when you select the "Physics" check box. I am unable to test if another shape-creation algorithm would work because it crashes before I am allowed to select a different one.

I tested this on a brand new project without setting any other import settings so I am confident it's narrowed down as far as I can before it crashes.

Another odd thing I noticed is even after Godot is closed, Windows does not let me move the project directory. When I try, I get a dialog that says "The action can't be completed because the folder or a file in it is open in another program" and there is a Try Again button that does not work.  I know that this isn't the root cause because the bug still happens when I copy the .blend file over to a brand new project and try again.

### Steps to reproduce

1. Double click "rock.blend" to open the importer settings dialog
2. Select "rock" right underneath "Scene" in the "Scene" tab.
3. Select the "Physics" check box in the "Generate" section.
4. If it successfully builds the shape, un-check Physics and check it again.

### Minimal reproduction project (MRP)

[rock_test.zip](https://github.com/godotengine/godot/files/14093268/rock_test.zip)

**Comment by Awarets** [comment] 2024-02-18 10:02
Seems to be fixed in v4.2.1.stable.mono.official [b09f793f5]

**Comment by akien-mga** [comment] 2024-02-18 11:25
Tested on Linux, I couldn't reproduce the bug on 4.2.stable either, so it might be OS/system specific.

**Comment by akien-mga** [comment] 2024-08-08 08:59
Closing as not reproducible.

**Closed by akien-mga** 2024-08-08 08:59 UTC
Labels: bug, topic:physics, needs testing, topic:import, crash
