### ISSUE TITLE
TextureButton Still can't drag image to Click Mask

### ISSUE THREAD

**Issue by ondesic** [godotengine/godot#17723] opened 2018-03-23 17:41 UTC
**Godot version:**
3.02 stable

**OS/device including version:**
Windows 10 pro

**Issue description:**
I can't drag a black and white PNG to the Click Mask property of a TextureButton.  I searched the problem but the only work around was to use code.  Is this being worked on?

**Comment by Noshyaar** [comment] 2018-03-23 17:45
Reimport the PNG as BitMap http://docs.godotengine.org/en/latest/classes/class_bitmap.html.

**Comment by ondesic** [comment] 2018-03-23 17:57
I know you can reimport, but it isn't intuitive.  It took me a long time to figure this out.  It would be nice to simply drag a black and white PNG to the spot and have godot do the conversions.  Wouldn't this be easier for users?

**Comment by Noshyaar** [comment] 2018-03-23 18:12
Agreed. The problem is that one file can only be imported as one resource type. I've discussed with @akien-mga months ago.

```
[10:47:23] <Noshyaar[m]> I can't use one resource as several type? E.g. a png as both texture and bitmap?
[11:08:35] <Akien> The import maps one source file to one imported resource, so I guess that you can't indeed
[11:09:12] <Akien> Working is to duplicate the source file. We'll see if there's a real use case for having multiple resources from one source file apart from trying to reproduce a bug :P
[11:10:24] <Noshyaar[m]> Umm, one use case is from that issue. If I can import png as both BitMap and texture, I can use it as button and click mask.
[11:10:51] <Noshyaar[m]> without another b&w mask.
```

**Comment by Zylann** [comment] 2018-03-23 18:17
How about having an option for the button to use the transparency of the current texture instead of the bitmask, if the bitmask is not set?

**Comment by Calinou** [comment] 2020-06-18 12:20
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!

**Closed by Calinou** 2020-06-18 12:20 UTC
Labels: enhancement, topic:editor, usability
