### ISSUE TITLE
_get_property_list() property values get wiped after script error

### ISSUE THREAD

**Issue by Razoric480** [godotengine/godot#52959] opened 2021-09-23 03:26 UTC
### Godot version

3.3.stable

### System information

Windows 10

### Issue description

If you have a script that exports properties with `export` and a script error occurs, after fixing the error the value it used to hold will be right back in its place as if nothing changed.

On the other hand, if you have a tool script and use `_get_property_list()` and a script error occurs, after fixing the error the default value will be put in its place, requiring re-inputting every property value.

It's also possible to wipe those properties when making changes to child scenes, though I haven't been able to reproduce it consistently.

### Steps to reproduce

1. Create new `Node` with script:
```gdscript
tool
extends Node

var some_prop := ""

func _get_property_list() -> Array:
	return [{"name": "some_prop", "type": TYPE_STRING}]
```
2. Set _some_prop_ to a value.
3. Save scene
4. Cause a script error (invalid characters anywhere)
5. File -> Save script
6. Fix error
7. File -> Save script
8. _some_prop_ is now blank

**Comment by akien-mga** [comment] 2021-09-23 08:38
Duplicate of #45337.

**Closed by akien-mga** 2021-09-23 08:38 UTC
