### ISSUE TITLE
mouse will disappear in demo "2d in 3d"

### ISSUE THREAD

**Issue by vipsbpig** [godotengine/godot#6241] opened 2016-08-22 15:26 UTC
**Operating system or device - Godot version:**
windows 7 64bit - godot 2.1 statble 64bit

**Issue description** (what happened, and what was expected):
when drag Spinbox item with arrow in demo "GUI in 3d", mouse will disappear after release.

**Comment by vnen** [comment] 2016-08-22 19:15
Duplicate of #5814.

**Closed by vnen** 2016-08-22 19:15 UTC
