### ISSUE TITLE
Tooltip does not disappear after a hover

### ISSUE THREAD

**Issue by Thed13** [godotengine/godot#73986] opened 2023-02-26 15:07 UTC
### Godot version

Godot 4 RC 5

### System information

Windows 10, GLES3, Nvidia GTX 1070 (31.0.15.2849)

### Issue description

I was on the latest docs doing the Dodge The Creeps game on the HUD page, when i tried to do the anchor presets i noticed that after hovering a preset, the tooltip doesn't disappear after hovering another one.

https://user-images.githubusercontent.com/94700814/221418512-55359af4-b08f-4299-b711-b092d2ad3625.mp4

### Steps to reproduce

1. Create a Control node
2. Go to Anchor preset
3. Hover a preset

### Minimal reproduction project

N/A

**Comment by YuriSizov** [comment] 2023-02-26 15:12
Duplicate of https://github.com/godotengine/godot/issues/73926

**Closed by YuriSizov** 2023-02-26 15:12 UTC
