### ISSUE TITLE
Unable to compile. unresolved externals error

### ISSUE THREAD

**Issue by ragas** [godotengine/godot#5276] opened 2016-06-18 18:42 UTC
**Operating system or device - Godot version:**
Windows 10, Using latest master (last commit 9b9580f5682fc5876a546eaf3062d5a3d29fc0f9)

**Issue description** (what happened, and what was expected):
Unable to compile 64 bit. Did worked few days back. 

Here is log:
```
tools\editor\editor_icons.windows.opt.tools.64.obj : warning LNK4042: object specified more than once; extras ignored
inspector_dock.windows.opt.tools.64.obj : warning LNK4221: This object file does not define any previously undefined public symbols, so it will not be used by any link operation that consumes this library
link /nologo /SUBSYSTEM:CONSOLE winmm.lib opengl32.lib dsound.lib kernel32.lib ole32.lib oleaut32.lib user32.lib gdi32.lib IPHLPAPI.lib Shlwapi.lib wsock32.lib shell32.lib advapi32.lib dinput8.lib dxguid.lib /OUT:bin\godot.windows.opt.tools.64.exe /LIBPATH:platform\windows\lib "/LIBPATH:C:\Program Files (x86)\Windows Kits\8.1\Lib" "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\LIB\amd64" "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\LIB\amd64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.10240.0\ucrt\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\lib\um\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\8.1\Lib\winv6.3\um\x64" "/LIBPATH:C:\Program Files\Microsoft DirectX SDK (March 2009)\Lib\x86" main\main.windows.opt.tools.64.lib modules\modules.windows.opt.tools.64.lib drivers\drivers.windows.opt.tools.64.lib tools\tool.windows.opt.tools.64.lib scene\scene.windows.opt.tools.64.lib servers\servers.windows.opt.tools.64.lib core\core.windows.opt.tools.64.lib drivers\freetype\freetype_builtin1.windows.opt.tools.64.lib drivers\freetype\freetype_builtin2.windows.opt.tools.64.lib platform\windows\godot_win.windows.opt.tools.64.obj platform\windows\context_gl_win.windows.opt.tools.64.obj platform\windows\os_windows.windows.opt.tools.64.obj platform\windows\ctxgl_procaddr.windows.opt.tools.64.obj platform\windows\key_mapping_win.windows.opt.tools.64.obj platform\windows\tcp_server_winsock.windows.opt.tools.64.obj platform\windows\packet_peer_udp_winsock.windows.opt.tools.64.obj platform\windows\stream_peer_winsock.windows.opt.tools.64.obj platform\windows\joystick.windows.opt.tools.64.obj platform\windows\godot_res.windows.opt.tools.64.obj
   Creating library bin\godot.windows.opt.tools.64.lib and object bin\godot.windows.opt.tools.64.exp
main.windows.opt.tools.64.lib(main.windows.opt.tools.64.obj) : error LNK2019: unresolved external symbol "char const * * __cdecl tests_get_names(void)" (?tests_get_names@@YAPEAPEBDXZ) referenced in function "private: static void __cdecl Main::print_help(char const *)" (?print_help@Main@@CAXPEBD@Z)
main.windows.opt.tools.64.lib(main.windows.opt.tools.64.obj) : error LNK2019: unresolved external symbol "class MainLoop * __cdecl test_main(class String,class List<class String,class DefaultAllocator> const &)" (?test_main@@YAPEAVMainLoop@@VString@@AEBV?$List@VString@@VDefaultAllocator@@@@@Z) referenced in function "public: static bool __cdecl Main::start(void)" (?start@Main@@SA_NXZ)
bin\godot.windows.opt.tools.64.exe : fatal error LNK1120: 2 unresolved externals
scons: *** [bin\godot.windows.opt.tools.64.exe] Error 1120
scons: building terminated because of errors.
```
**Steps to reproduce:**
scons platform=windows target=release_debug  -j2

**Link to minimal example project** (optional but very welcome):

**Comment by vnen** [comment] 2016-06-18 19:18
Duplicate of #5182. If you're using SCons 2.5.0, try to downgrade to 2.4.1 which is still working.

**Closed by vnen** 2016-06-18 19:18 UTC
Labels: bug, platform:windows, topic:buildsystem

**Comment by vnen** [comment] 2016-06-19 01:58
BTW, this seems not related to SCons version. Check the discussion at #5182.
