### ISSUE TITLE
Godot doesn't let me move a font or rename its folder due to Windows file locking limitations

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#23773] opened 2018-11-17 19:13 UTC
Godot 3.0.6
Godot 3.1 alpha2
Windows 10 64 bits

I am trying to move a `.ttf` font to another folder, but Godot keeps erroring and doesn't do it. Curiously, this does not print anything in the console other than the usual `Call rescan!` when moving things:

![image](https://user-images.githubusercontent.com/1311555/48664788-ff5e4a00-ea9b-11e8-89a3-fdfffbaaba94.png)

I tried reproducing it in a simple project, but it worked only once, and never reproduced again so far even if I delete `.import` and cache etc. Unfortunely it keeps happening in my full project and I'll be forced to move it by hand and update every reference to it. I don't know why it happens sometimes and not other times, but reproducing from scratch seems to always succeed.

Here are the reproduction steps, if you can repro. Sorry I didn't upload a project for the reason above.

1) Create a new project
2) Create the following folder structure:
```
fonts/
menus/
    fonts/
```
3) Put this font into `fonts/` (unzip it first): [upheavtt.zip](https://github.com/godotengine/godot/files/2592154/upheavtt.zip)
4) Create two dynamic fonts using it, one with size 16 and another with size 22, and save them under `fonts/upheaval16.tres` and `fonts/upheaval22.tres`.
5) Now, pick one of the `.tres` and move it under `menus/fonts/`.
6) Move the second `.tres` under `menu/fonts/` as well.
7) Finally, try to move `upheavtt.ttf` under `menu/fonts/`: the error happens and the font is not moved.
8) Try to rename the `fonts` folder: the error happens again and the folder is not renamed.

**Comment by qarmin** [comment] 2019-02-09 12:36
This seems to be a windows limitation, reduz in #4522 explain why this happens.

**Comment by KoBeWi** [comment] 2019-04-09 16:55
Very similar to #23781

**Comment by mbarbre1** [comment] 2019-09-29 17:50
Kind of a deal breaker if you can't organize resources.  I shut down godot and organized the font files, and this resulted in completely breaking the project fonts.

**Comment by Zylann** [comment] 2019-10-10 19:59
Still happens in Godot 3.2 alpha1

**Comment by Hendrix63** [comment] 2019-11-03 13:38
Found out that I cannot move a fonts folder or fonts as long as I have a scene open in the editor that uses the font. If I close the scene then I am able to move the fonts folder or fonts.
Using Godot 3.1.1 on Windows.

**Comment by KoBeWi** [comment] 2020-10-24 23:06
Still valid in 6c173e2

**Comment by Flavelius** [comment] 2020-12-05 08:39
Still valid in 3.2.3, any currently open scene needs to be closed, then it works.

**Comment by avencherus** [comment] 2020-12-05 09:06
> This seems to be a windows limitation, reduz in #4522 explain why this happens.

I read it as Freetype is the cause.  It holds the file open.  This is a platform specific issue, and the solution would probably involve finding a clean way of closing the files before doing these directory operations.

**Comment by Flavelius** [comment] 2020-12-05 09:21
If closing a scene can release the lock, it can't see why it shouldn't be possible to use the same method that does this unrelated to scene closing and just reopen it immediately afterwards.

**Closed** 2020-12-07 09:43 UTC
Labels: bug, confirmed, platform:windows, topic:editor
