### ISSUE TITLE
Editor property tooltips are truncated (4.0 alpha 14)

### ISSUE THREAD

**Issue by snoopdouglas** [godotengine/godot#64316] opened 2022-08-12 12:34 UTC
### Godot version

4.0.alpha14

### System information

Fedora 36, GNOME on Wayland

### Issue description

Editor property tooltips are all chopped off at around the same point:

![Screenshot from 2022-08-12 13-30-35](https://user-images.githubusercontent.com/4892574/184354802-97b7628d-f837-416a-8ecd-3d39c3c2f5f8.png)
![Screenshot from 2022-08-12 13-30-53](https://user-images.githubusercontent.com/4892574/184354806-78939d76-22bf-448f-8367-6bf40ad7caa2.png)
![Screenshot from 2022-08-12 13-31-39](https://user-images.githubusercontent.com/4892574/184354808-0e1f8d5d-43d2-4091-9e5a-ec99143bdd16.png)

### Steps to reproduce

Hover over a property in the editor.

### Minimal reproduction project

Seems to be the case on all projects.

**Comment by Zireael07** [comment] 2022-08-12 12:47
KDE on X11 seeing the same, just no black bar - simply truncated to one row

**Comment by Calinou** [comment] 2022-08-12 13:37
Duplicate of https://github.com/godotengine/godot/issues/61712.

**Closed by Calinou** 2022-08-12 13:37 UTC
