### ISSUE TITLE
No Code Completion For Script Instanced Nodes

### ISSUE THREAD

**Issue by toliaferrode** [godotengine/godot#4849] opened 2016-05-27 21:56 UTC
**Operating system or device - Godot version:**
Linux, Godot 2.0.3

**Issue description** (what happened, and what was expected):
I followed the instancing tutorial for scripting. I expected code completion for the node/instance, but there was none.

**Steps to reproduce:**
Instance a node in code and type the node on a new line and try putting a period after it.

**Link to minimal example project** (optional but very welcome):

**Comment by vnen** [comment] 2016-05-27 23:42
@toliaferrode I closed your other issue as duplicate and you opened another one? Please do not do that. You can discuss your problem in the still open issue about the subject, no need not make new tickets for the same thing. It won't make be solved faster nor better. If you don't think it's a duplicate, then explain why not in the same issue (it's just closed, not locked) and I'll reopen it.

So I'll also close this as duplicate of #1039 & #4835.

**Closed by vnen** 2016-05-27 23:42 UTC

**Comment by toliaferrode** [comment] 2016-05-28 03:17
Hey, sorry about that truly. I honestly thought I didn't post the original
issue. I apologize.

**Comment by vnen** [comment] 2016-05-28 13:19
@toliaferrode ok, I can understand that. BTW, you can see the issues you created if you click the "Issues" link on the top bar of GitHub. So next you can be sure you didn't make one yet 😉

**Comment by toliaferrode** [comment] 2016-06-01 21:05
Thanks a lot. :)
