### ISSUE TITLE
Visible Custom Shapes not updating when doing custom extents

### ISSUE THREAD

**Issue by alketii** [godotengine/godot#23046] opened 2018-10-16 10:42 UTC
**Godot version:**
39bdffa57c667f575520b59e84199d0e46a4f1c0

**OS/device including version:**
Linux

**Issue description:**
Debugging Visible Custom Shapes not showing correctly when doing custom extents from code.
I tested the same with 2D counterparts, and it works.

**Steps to reproduce:**
Add a KinematicBody with a CollisionShape, trought code change extents and Enable Visible Custom Shapes

**Minimal reproduction project:**
[collision_bug.zip](https://github.com/godotengine/godot/files/2482609/collision_bug.zip)

**Comment by KoBeWi** [comment] 2019-11-29 12:36
Duplicate of #17300

**Closed by KoBeWi** 2019-11-29 12:36 UTC
Labels: bug, topic:core
