### ISSUE TITLE
Shift+R shortcut in the TileSet collision tab is not working properly

### ISSUE THREAD

**Issue by RACECAR69** [godotengine/godot#58728] opened 2022-03-04 05:20 UTC
### Godot version

3.4.3 stable

### System information

OS - Windows 11, Laptop - HP Omen, GPU- Nvidia Geforce GTX 1650, Processor- Intel i7 9th gen 

### Issue description

while setting the collisions for the tileset I encounter the problem that the New Rectangle hotkey (shift + r) does not do what is intended
****Expected Result**** of pressing shift + r
![image](https://user-images.githubusercontent.com/71834151/156702291-c4b0fd71-4632-4d14-8956-68316c7a04c4.png)
any tool you selected earlier should be deselected and the New Rectangle tool should be selected

****what actually happens**** after pressing shift + r
![image](https://user-images.githubusercontent.com/71834151/156702423-35141910-7a59-41d7-92a7-6e25cccfc28d.png)
it selects both the selection tool and the new rectangle 
this doesn't allow me to create a new rectangle and instead i would have to manually move the cursor to press it

### Steps to reproduce

after creating a tileset

- click on the tileset resource
![image](https://user-images.githubusercontent.com/71834151/156704043-e52a72a2-f07b-4f81-ac80-78f319b73d00.png)
- new autotile
![image](https://user-images.githubusercontent.com/71834151/156704094-0df63955-e6fa-46d2-a02e-09538b87373d.png)
- collision tab
![image](https://user-images.githubusercontent.com/71834151/156704114-52ee9b5c-f56f-425c-ad9d-d4a276c6c85e.png)
- make sure you have the cursor option selected
![image](https://user-images.githubusercontent.com/71834151/156704162-a1ee3e2f-32b1-4622-87f4-b5ff5e0513bf.png)
- press shift r
![image](https://user-images.githubusercontent.com/71834151/156704226-d4608b1b-340c-4c82-9a83-65241f23a1a7.png)

**Comment by coffe789** [comment] 2022-04-19 10:38
I believe this is a duplicate of #54481

**Comment by Calinou** [comment] 2022-04-19 12:42
Duplicate of https://github.com/godotengine/godot/issues/54481.

**Closed by Calinou** 2022-04-19 12:42 UTC
Labels: bug, topic:editor, usability, topic:2d
