### ISSUE TITLE
AnimatedTexture doesn't work anymore

### ISSUE THREAD

**Issue by Banduck** [godotengine/godot#23088] opened 2018-10-17 14:28 UTC
**Godot version:**
3.1 0dbe014

**OS/device including version:**
Windows 10

**Issue description:**
The AnimatedTexture doesn't work anymore. 
If you try to add new frames, no new frames will be added.

**Steps to reproduce:**
![animatedtexture](https://user-images.githubusercontent.com/42905358/47093387-61235e00-d229-11e8-9a32-0bbd6183a4c0.gif)

**Comment by ByTheQuietLake** [comment] 2018-10-17 15:18
I think this is a duplicate of  #22442, you can find some more details there.

**Comment by akien-mga** [comment] 2018-10-17 18:56
Duplicate of #22442.

**Closed by akien-mga** 2018-10-17 18:56 UTC
Labels: bug, topic:editor
