### ISSUE TITLE
Arabic language is corrupted.

### ISSUE THREAD

**Issue by StarlkYT** [godotengine/godot#30255] opened 2019-07-02 14:58 UTC
Arabic language in Godot 3 is corrupted.
Godot 3 have problem with an Arabic writing system because in the Arabic language all words, sentences and etc must be written from right to left, so that's why it looks corrupted and the words aren't connected with each other.

Examples:
In Godot 3 if you typed something it will "almost" look like this:
" ا ه ل ا  و س ه ل ا ب ك م  ف ي  ب ر ن ا م ج  ج و د و ت 3".
And it must look like this:
"اهلا وسهلا بكم في برنامج جودوت 3".

**Comment by Zireael07** [comment] 2019-07-02 15:32
I am 100% sure that it was already reported, but unfortunately proper RTL support is not easy.

Someone with better github-fu will be able to find the issue AND the PR that was supposed to fix it but stalled.

**Comment by Calinou** [comment] 2019-07-02 15:46
Duplicate of https://github.com/godotengine/godot/issues/982.

**Closed by Calinou** 2019-07-02 15:46 UTC
