### ISSUE TITLE
OSX: Mouse cursor position wrong after click-dragging numeric input

### ISSUE THREAD

**Issue by jscheel** [godotengine/godot#10081] opened 2017-08-04 13:44 UTC
**Operating system or device - Godot version:**
MacOS 10.12.5
Godot 2.1.3.stable.official

**Issue description:**
After click-dragging on a numeric entry to change the value, the cursor position is set to the bottom right of my entire screen. I would expect the cursor position to be reset to its position when the gesture began.

**Steps to reproduce:**
Click-drag numeric input.

**Comment by kubecz3k** [comment] 2017-08-04 17:13
Can't reproduce on linux on 7ac50b523b8cb313245e2fbdd16b5561c88b3aeb so it's probably OSX related issue

**Comment by kubecz3k** [comment] 2017-08-04 17:15
@jscheel can you check if the issue is present in 3.0 alpha?

**Comment by jscheel** [comment] 2017-08-04 17:21
@kubecz3k yes, can confirm that it is still present in 3.0 alpha

**Comment by jscheel** [comment] 2017-08-04 17:23
Here is a recording of what is happening. First, I use the slider to change the value. Second, I drag directly on the number. After I let go, the cursor jumps to the bottom right, which I then bring back into the view.

![cursor](https://user-images.githubusercontent.com/211478/28979455-8a8abd3e-790f-11e7-9b98-c25471307f3f.gif)

**Comment by toger5** [comment] 2017-08-04 18:34
also have this issue. (macOS)

**Comment by bruvzg** [comment] 2017-08-04 20:17
Same issue (macOS 12.12.5), looks like `OS_OSX::warp_mouse_pos` is broken.

**Comment by jscheel** [comment] 2017-08-04 20:20
@bruvzg is it possible that this is only broken on retina displays? I don't recall this happening on my external monitor. Can't test until next week though :(

**Comment by bruvzg** [comment] 2017-08-04 20:23
@jscheel No I am using non retina display.

**Comment by jscheel** [comment] 2017-08-04 20:48
Haha, sorry, had to post this here: https://github.com/godotengine/godot/blob/263452ee91c7d76f3a2b1503ce8fbd0d35bbb6e4/platform/osx/os_osx.mm#L1084

**Comment by kubecz3k** [comment] 2017-08-04 21:28
sorry for tag jugglery, `junior job` usually raises a chance for external pr, and in the issue here has enough info for less experienced contributors to try his bugfixing powers, haven't noticed the proper pr is already waiting to be merged :)

**Closed** 2017-08-07 12:47 UTC
Labels: bug, confirmed, platform:osx, topic:editor
