### ISSUE TITLE
Graphical glitches when using screen space reflections

### ISSUE THREAD

**Issue by JamesC01** [godotengine/godot#48392] opened 2021-05-02 18:24 UTC
**Godot version:**
4.0 master (Hugo's build)

**OS/device including version:**
Vulkan
gtx 1050 ti
Windows 10

**Issue description:**
I've been testing @Calinou 's unofficial builds for over a month now, and the screen space reflections always creates graphical glitches [video link](https://twitter.com/JamesC01_/status/1388868068466741249) among other general slowness. These problems only show in the editor, and resizing the bottom tabs affects the graphical glitches.

![glitchy](https://user-images.githubusercontent.com/31216671/116823410-48c38680-ab7c-11eb-8739-d808c55d42fa.png)

This error keeps repeating in the output:

  Attempted to use an unused shader variant (shader is null),
  This render pipeline requires (0) bytes of push constant data, supplied: (16)
  No render pipeline was set before attempting to draw.
  Uniforms supplied for set (3):
Set: 1 Binding: 0 Type: CombinedSampler Length: 1
Set: 1 Binding: 1 Type: CombinedSampler Length: 1
are not the same format as required by the pipeline shader. Pipeline shader requires the following bindings:
Set: 0 Binding: 0 Type: Image Length: 1
Set: 0 Binding: 1 Type: Image Length: 1
Set: 1 Binding: 0 Type: Image Length: 1
Set: 1 Binding: 1 Type: Image Length: 1
Set: 2 Binding: 0 Type: Image Length: 1
Set: 3 Binding: 0 Type: CombinedSampler Length: 1

**Steps to reproduce:**
Create a new node3D and add a world environment. Turn ss reflections on.

**Minimal reproduction project:**
[minimal_project.zip](https://github.com/godotengine/godot/files/6412014/minimal_project.zip)

**Comment by Calinou** [comment] 2021-05-02 19:22
Duplicate of https://github.com/godotengine/godot/issues/44539.

**Closed by Calinou** 2021-05-02 19:22 UTC
