### ISSUE TITLE
.TSCN corrupted when scaling GIProbe in orthographic view

### ISSUE THREAD

**Issue by JamesC01** [godotengine/godot#52449] opened 2021-09-06 21:05 UTC
### Godot version

3.3.3.stable

### System information

Windows 10

### Issue description

if I try to scale a GIProbe on the Y axis when looking from a top-down orthographic view, I get the error " servers/visual/visual_server_scene.cpp:723 - Condition "Math::is_nan(v.x)" is true." If I save the file, and try to load it, it can't parse it. I can solve it by removing the GIProbe from the tscn manually in a text editor.

### Steps to reproduce

Create a new scene, add a GIProbe, press numpad 7 to go into top-down ortho view, and try to scale using the middle scale handle.

**Comment by qarmin** [comment] 2021-09-07 08:56
Duplicate of https://github.com/godotengine/godot/issues/40589

**Closed by qarmin** 2021-09-07 08:56 UTC
