### ISSUE TITLE
ERROR: _load: Failed loading resource

### ISSUE THREAD

**Issue by git2013vb** [godotengine/godot#34777] opened 2020-01-03 09:36 UTC
**Godot version:**
3.2beta4
**OS/device including version:**
Debian 10
**Issue description:**
```
ERROR: _load: Failed loading resource: res://addons/file-editor/file.samples/sample.csv.
   At: core/io/resource_loader.cpp:278.
ERROR: _load: Failed loading resource: res://addons/file-editor/file.samples/sample.csv.
   At: core/io/resource_loader.cpp:278.
ERROR: _load: Failed loading resource: res://addons/file-editor/file.samples/sample.csv.
   At: core/io/resource_loader.cpp:278.
ERROR: _load: Failed loading resource: res://addons/file-editor/file.samples/sample.csv.
   At: core/io/resource_loader.cpp:278.
ERROR: _load: Failed loading resource: res://addons/file-editor/file.samples/sample.csv.
   At: core/io/resource_loader.cpp:278.
ERROR: _load: Failed loading resource: res://addons/file-editor/file.samples/sample.csv.
   At: core/io/resource_loader.cpp:278.
```

**Steps to reproduce:**
It happen with any csv file in any folder
**Minimal reproduction project:**

**Comment by Calinou** [comment] 2020-01-03 11:06
Can you upload a minimal reproduction project, please?

**Comment by FeralBytes** [comment] 2020-01-03 22:30
@git2013vb that error seems to be produced by your add on 
file-editor", not godot.

**Comment by git2013vb** [comment] 2020-01-04 14:39
> @git2013vb that error seems to be produced by your add on
> "file-editor", not godot.

file-editor is a plugin from AssetLib. However I have same problem if I have a CSV file in project , Can be the translate one or another one (even an empty one) as you can see.:

```
ERROR: _load: Failed loading resource: res://datatable/test.csv.
   At: core/io/resource_loader.cpp:278.

```



> Can you upload a minimal reproduction project, please?

No need : Just add a csv file in any project and you'll see the error.

**Comment by Calinou** [comment] 2020-01-13 22:38
@git2013vb The `.csv` file included in that ZIP is empty – its size is 0 bytes.

**Comment by git2013vb** [comment] 2020-01-14 11:45
> @git2013vb The `.csv` file included in that ZIP is empty – its size is 0 bytes.
> 
> Also, when you save a CSV file, make sure it uses UTF-8 encoding _without BOM_.

The same happen with normal csv file (translation). 
I will try to set UTF-8.. Maybe is this the problem.

**Comment by henriquelalves** [comment] 2020-04-27 02:03
It's still happenning; apparently Godot can't load CSV's in its current build.

**Comment by Calinou** [comment] 2020-04-27 07:09
@henriquelalves Are you loading a translation CSV or a generic (non-translation CSV)? You can select the import type by selecting the CSV in the FileSystem dock, going to the Import dock, choosing the type then clicking **Reimport**.

**Comment by henriquelalves** [comment] 2020-04-27 21:23
I'm using a normal CSV file (I reimported it via Editor). I created another issue about it with a minimal example: https://github.com/godotengine/godot/issues/38245

willnationsdev clarified to me that CSV files can't be loaded as "TextFile resources", but they don't seem to be exportable as normal Resources too.

**Comment by akien-mga** [comment] 2020-12-10 15:41
Closing as duplicate of #38245.

**Closed by akien-mga** 2020-12-10 15:41 UTC
Labels: bug, topic:import
