### ISSUE TITLE
Collision shapes attached to physical bones don't transform with their bones when animated

### ISSUE THREAD

**Issue by Two-Tone** [godotengine/godot#24359] opened 2018-12-14 22:23 UTC
**Godot version:**
3.1 Alpha 3 and Alpha 2

**OS/device including version:**
Win 7 x64

**Issue description:**
If the skeleton the bones are tied to is animated the bones will transform, but the shapes do not move from their original position.

**Minimal reproduction project:**
[Here is a test scene with an animated hand model I made.](https://www.dropbox.com/s/xoss7quvlilbr7e/hand%20ok.tscn?dl=0) All you have to do is generate a set of physical bones from the skeleton, set the scene as the root scene, and hit F5. It's already set up to loop the animation.

**Comment by Two-Tone** [comment] 2019-01-08 12:44
Hopefully this gets fixed before the stable build is released since this *completely* breaks the tool.

**Comment by akien-mga** [comment] 2019-01-26 00:01
Ping @AndreaCatania

**Comment by Two-Tone** [comment] 2019-01-28 13:52
@AndreaCatania I'm not sure if I understand your comment as it's a bit of a mess.  But I'm going to assume I'm doing something wrong.

So what extra should I do so that the collision shapes *do* animate?

**Comment by Two-Tone** [comment] 2019-03-02 21:10
It's been a month, anything?

They ARE suppose to animate, right?  [Because in the last gif in the article describing the bones you can clearly see them animate with the bones](https://godotengine.org/article/godot-ragdoll-system)

**Comment by phryk** [comment] 2019-03-25 01:52
I have the same issue with IK. Bone constraints also seem to either get lost on export (even with better collada export) or be plainly ignored by the physical bone generation feature.

This makes usage extremely cumbersome at best and impossible at worst. :(

![ikbonefail](https://user-images.githubusercontent.com/1021513/54889507-42468900-4ea5-11e9-908b-83145d91089e.png)

**Comment by akien-mga** [comment] 2020-01-09 09:41
Still reproducible in the current master branch.

**Comment by AndreaCatania** [comment] 2020-01-11 10:41
The Physical Bones are not supposed to be animated currently since they are thought for ragdoll only. I should add the support for this feature, in the meanwhile is advised to use bone attachment.

**Comment by AndreaCatania** [comment] 2020-02-08 18:59
Fixed by this: #36008

**Closed** 2020-02-09 10:15 UTC
Labels: bug, topic:physics

**Comment by Two-Tone** [comment] 2020-02-11 02:32
Any chance it'll be backported to a 3.2.x update?  It's not a major change
but would be nice to have before 4.0 drops.
