### ISSUE TITLE
Godot crashes on circular dependencies with resources

### ISSUE THREAD

**Issue by Mojko** [godotengine/godot#47463] opened 2021-03-29 16:53 UTC
**Godot version:**
Godot Engine v3.1.2.stable.official

**OS/device including version:**
NVIDIA GeForce RTX 2060 SUPER

**Issue description:**
What happened:
The program crashed when cyclic dependencies occur by exporting resources and dragging and dropping them in the inspector

What was expected:
Some sort of error message warning about cyclic dependencies, maybe some dialog box that you have to press "ok" of?

**Steps to reproduce:**
1. I have a script that extends Resource. The script exports a Resource field
2. Create a resource based off this script -> Resource1
3. Create another resource based off this script -> Resource2
4. In Resource1, drag and drop Resource2 into the exported resource field in the inspector
5. In Resource2, drag and drop Resource1 into the exported resource field in the inspector
6. Crash

**Minimal reproduction project:**
[IssueBugReport#1.zip](https://github.com/godotengine/godot/files/6223262/IssueBugReport.1.zip)

**Comment by Calinou** [comment] 2021-03-29 16:58
Duplicate of https://github.com/godotengine/godot/issues/41111.

**Closed by Calinou** 2021-03-29 16:58 UTC
Labels: bug, crash, topic:editor
