### ISSUE TITLE
set/get doesn't trigger when setting dictionary/array by index

### ISSUE THREAD

**Issue by Mohammed-Anwar** [godotengine/godot#79499] opened 2023-07-15 13:12 UTC
### Godot version

Godot 4.1

### System information

Godot v4.1.stable - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce 930MX (NVIDIA; 31.0.15.2233) - Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz (4 Threads)

### Issue description

the set function of dictionary/array doesn't trigger when trying to set specific key or index
in godot 3.x you can do it fine with `setget`, but in godot 4.x it's looks like an old bug come again #37737

### Steps to reproduce

in any script, write any dictionary/array with "set" and it's function with print line
then try to set key/index anywhere in your code (like _ready function) 

example :
```Gdscript
var data : Dictionary = {
	"money":300,
	"items":1,
	"slots":1
} : set = _new_data

func _new_data(value):
	data = value
	print("function triggered")

func _ready():
	data["money"] = 200
```

run the script to find no output

### Minimal reproduction project

N/A

**Comment by AThousandShips** [comment] 2023-07-15 13:19
This is as expected and intended and not a bug IMO, it doesn't assign to the dictionary, it assigns to an index in it, it's an optimisation

**Comment by Mohammed-Anwar** [comment] 2023-07-15 13:21
is so, then every time i need to set one key, i need to re-set the whole dictionary?
in every line >->?

**Comment by AThousandShips** [comment] 2023-07-15 13:22
If you want this behaviour yes, and there you see what performance issue having that by default would be arguably

**Comment by Mohammed-Anwar** [comment] 2023-07-15 13:26
what about thing like `set("dictionary:key", value)` to trigger the setter?
`set("data:money", 100)`
if there is no way like this, then you can close the issue

**Comment by AThousandShips** [comment] 2023-07-15 13:28
Does it trigger it, I can't test at the moment

But to be clear, making it assign a dictionary or array each time it's modified would be bad for performance

It would also be confusing, as you could do:
```gdscript
var arr_copy = my_array
arr_copy[1] = y
```
And it wouldn't fire, even if it would when doing `my_array[1] = y`

**Comment by Mohammed-Anwar** [comment] 2023-07-15 13:36
nice to know it's intended and not but.
but right now what is the best way to do (asking for a good line of code)

**Comment by AThousandShips** [comment] 2023-07-15 13:39
For the future note that this isn't for support questions, please use the other [community channels](https://godotengine.org/community) for that.

You will probably just have to set it manually, also see the other issues for suggestions, as people have already answered that there

**Closed** 2023-07-15 13:41 UTC
Labels: discussion, topic:gdscript, documentation
