### ISSUE TITLE
[4.0] Looping tween with two property tweeners stops after first step.

### ISSUE THREAD

**Issue by FluffyBunniesTasteTheBest** [godotengine/godot#59585] opened 2022-03-27 15:57 UTC
### Godot version

v4.0.alpha.mono.custom_build [3990152f6]

### System information

Ubuntu 2021.10 Vulkan API 1.2.162 - Using Vulkan Device #0: NVIDIA - NVIDIA GeForce GTX 1070

### Issue description

Dear Godot team,
the following code snippet is moving a particle effect between two positions using a tween:

```
public void AddParticleEffect(Vector2 srcPos, Vector2 dstPos)
{
	GPUParticles2D newParticleEffect = particleEffectScene.Instantiate() as GPUParticles2D;
	newParticleEffect.Position = srcPos;
	AddChild(newParticleEffect);
	activeParticleEffects.Add(newParticleEffect);

	Tween moveParticlesTween = newParticleEffect.CreateTween();
	moveParticlesTween.SetTrans(Tween.TransitionType.Sine);
	moveParticlesTween.SetEase(Tween.EaseType.In);
	moveParticlesTween.TweenProperty(newParticleEffect, "position", dstPos, 2);
	moveParticlesTween.TweenProperty(newParticleEffect, "position", srcPos, 2);
	moveParticlesTween.SetLoops();
}
```

The first time `AddParticleEffect()` is called, it is working as expected - i.e. the particle effect is moving infinitely. 
Calling the same method a second time causes the particle effect to stop after the first step (i.e. after the line `moveParticlesTween.TweenProperty(newParticleEffect, "position", dstPos, 2);` is done).

### Steps to reproduce

The easiest way to reproduce the issue is to run the attached minimal reproduction project and:
1. Push the start button - you'll see an animation moving left/right infinitely.
2. Push either the stop or remove button.
3. Push the start button again. The animation starts to move to the right and then stops. At the time the animation stops, the following error message is logged:
```
E 0:00:11:0073   step: Infinite loop detected. Check set_loops() description for more info.
  <C++ Error>    Method/function failed. Returning: false
  <C++ Source>   scene/animation/tween.cpp:322 @ step()
```
Please note that the above calls of `TweenProperty()` use a two seconds duration, which, according to the [docs](https://docs.godotengine.org/en/latest/classes/class_tween.html#class-tween-method-set-loops), should be all right.

### Minimal reproduction project

Upload failed, please [see here](https://github.com/godotengine/godot/issues/59585#issuecomment-1080299161).

**Comment by Calinou** [comment] 2022-03-27 17:08
@FluffyBunniesTasteTheBest The minimal reproduction project didn't upload (likely because you clicked away from the text field while it was still uploading). Try editing your post and upload it again.

Also, please create a minimal reproduction project in GDScript instead of C# for two reasons:

- Non-Mono builds of Godot are easier to set up and have less moving parts.
- This rules out C# being the cause of the bug.

**Comment by FluffyBunniesTasteTheBest** [comment] 2022-03-28 07:33
[TweenTest.zip](https://github.com/godotengine/godot/files/8360567/TweenTest.zip)

**Comment by GeorgeS2019** [comment] 2022-04-04 21:24
@Calinou I tried **two weeks** ago and the Godot4 mono is not able to dotnet build project compared to an older version of Godot4 mono **2 months ago**.  I suspect the [reason here](https://github.com/godotengine/godot/issues/59871#issuecomment-1088022342).

**Comment by GeorgeS2019** [comment] 2022-04-17 05:43
Confirmed

## Godot version

v4.0.alpha.mono.custom_build [3ce843c](https://github.com/godotengine/godot/commit/3ce843c128c7c06d9841433c399e261609f44892)

Windows 11

<img src="https://user-images.githubusercontent.com/49812372/163701990-4483ba0e-a7fe-4d96-9055-d209057aa08b.gif" alt="alt text" title="Tween Test" width="500"/>



```
E 0:00:27:0085   Tween::step: Infinite loop detected. Check set_loops() description for more info.
  <C++ Error>    Method/function failed. Returning: false
  <C++ Source>   scene\animation\tween.cpp:325 @ Tween::step()
```

**Comment by KoBeWi** [comment] 2022-08-16 12:25
Can't reproduce in d5d22ab
@FluffyBunniesTasteTheBest Can you confirm? Judging from the error message you posted, a similar bug was fixed, so it should be working now.

GDScript repro btw
[TweenTest.zip](https://github.com/godotengine/godot/files/9350843/TweenTest.zip)

**Comment by YuriSizov** [comment] 2023-02-27 10:35
Closing per comment above. Please provide more details and an MRP so we can investigate the issue better, if it still occurs.

**Closed by YuriSizov** 2023-02-27 10:35 UTC
Labels: bug, topic:core, needs testing
