### ISSUE TITLE
Directional Shadows disappear with large Camera Z Far values at some angles

### ISSUE THREAD

**Issue by ashlanderr** [godotengine/godot#89560] opened 2024-03-16 08:16 UTC
### Tested versions

- Reproducible in: v4.3.dev5.official [89f70e98d]
- Not Reproducible in: v4.3.dev2.official [352434668], v4.2.1.stable.mono.official [b09f793f5]

### System information

Godot v4.3.dev5 - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3060 Ti (NVIDIA; 31.0.15.3623) - AMD Ryzen 7 2700 Eight-Core Processor (16 Threads)

### Issue description

When I set the camera's Z Near to 10m and Z Far to 1,000,000m, shadows from a directional light begin to disappear at certain angles. Reducing the Z Far value to 100,000m resolves the issue. The ratio between the near and far planes is not significantly different from the default values (4000 / 0.05 = 80,000, compared to 1,000,000 / 10 = 100,000), so I think that the problem is unlikely to be related to Z fighting or similar issues.

Small Z Far value:
![image](https://github.com/godotengine/godot/assets/25693223/633d70dc-1ab8-42c8-bfa7-e6d664273286)

Large Z Far value:
![image](https://github.com/godotengine/godot/assets/25693223/6e9f8fb1-27ca-4279-8f50-54df16747b25)

### Steps to reproduce

In the MRP, toggle the preview between Camera3D_Ok and Camera3D_Error to observe the disappearance of shadows. Additionally, you can adjust the editor camera settings to match those of Camera3D_Error and rotate it to identify angles at which the shadows fail.

### Minimal reproduction project (MRP)

[ShadowTest1.zip](https://github.com/godotengine/godot/files/14622846/ShadowTest1.zip)

**Comment by matheusmdx** [comment] 2024-05-09 21:41
Bisecting points to #84745 as the culprit

![image](https://github.com/godotengine/godot/assets/44306054/bb716f90-a954-405f-81c9-2f8d3f9d948d)

**Comment by clayjohn** [comment] 2024-05-09 23:14
Cc @lawnjelly

**Comment by lawnjelly** [comment] 2024-05-10 06:52
I just checked and it doesn't seem fixed by https://github.com/godotengine/godot/pull/90417 which was merged after 4.3 dev 5.

It's probably again down to numerical precision at large values, I'll investigate, it could be it needs an epsilon for this case.

Until then just switch off tighter culling in `project_settings/rendering/lights_and_shadows/tighter_shadow_caster_culling` if you wish to use extreme frustum sizes.

**Comment by lawnjelly** [comment] 2024-05-10 07:18
Also occurs in 3.6 beta 5 (as the tighter culling code is shared). Here's MRP for 3.6:
[tighter_culling_large_frustum_bug.zip](https://github.com/godotengine/godot/files/15271563/tighter_culling_large_frustum_bug.zip)

This should be easier to debug in 3.6 and port fix to 4.x.

**Comment by lawnjelly** [comment] 2024-05-10 08:03
Got it, it's the same bug as #89714 , but I forgot to fix it for directional lights.
Should be able to do PR quickly before I go, as I am away this weekend.

**Comment by lawnjelly** [comment] 2024-05-12 13:28
Re-opening this temporarily (maybe until the next build) to try and prevent duplicate issues being reported.

The issue is fixed, but bug reporters may not see closed issues in their searches.

**Closed** 2024-05-21 11:07 UTC
Labels: bug, topic:rendering, regression, topic:3d
