### ISSUE TITLE
Editor: Tabbing does not automatically select the next selectable field in Inspector

### ISSUE THREAD

**Issue by WolfgangSenff** [godotengine/godot#66393] opened 2022-09-25 11:16 UTC
### Godot version

4.0.beta1

### System information

Windows 11

### Issue description

If you're editing a property in the inspector that has more than one value (think Transforms) and you hit tab, it doesn't correctly move to the next editable property and put it into editing mode. I didn't see this elsewhere in the bug list, but it's a bit hard to search for it. This used to work in 3.x of course. It's unclear to me if this is only happening when you edit something away from the default value, or if it happens at other times as well, but I'm definitely able to consistently reproduce this. It's also the case that sometimes it moves to the next field but doesn't put it into editing mode, just selects it. This has been happening in Godot 4 since the beginning as far back as I can remember. This is also true for shift-tabbing to go backward.

### Steps to reproduce

1. Create a new project
2. Create a new scene with a Node2D as the base
3. Open Transform in the inspector
4. Tap on the x value for position
5. Enter a number and press the tab button
6. Enter another number
7. If the exact bug above doesn't happen, select back on the x value, type in another number and hit tab again.

### Minimal reproduction project

[Dummy.zip](https://github.com/godotengine/godot/files/9640611/Dummy.zip)

**Comment by Calinou** [comment] 2022-09-25 18:04
Duplicate of https://github.com/godotengine/godot/issues/37723.

**Closed by Calinou** 2022-09-25 18:04 UTC
