### ISSUE TITLE
If autoscript list appears, the property dialog will behind the script editor

### ISSUE THREAD

**Issue by zhagsenkk** [godotengine/godot#22987] opened 2018-10-13 15:51 UTC
**Godot version:**
3.1 alpha

**OS/device including version:**
win10 ,gtx760

**Issue description:**
![-2](https://user-images.githubusercontent.com/10054853/46907276-bc600280-cf42-11e8-99bf-a38dda72ec0a.png)

**Steps to reproduce:**
1.script
2.move the mouse to one property.

**Minimal reproduction project:**
null

**Comment by akien-mga** [comment] 2018-10-16 11:21
Duplicate of #22504.

**Closed by akien-mga** 2018-10-16 11:21 UTC
