### ISSUE TITLE
Godot 2.0 Feb 23 2016 stable version: How to rotate/pan scene (Macbook Pro)?

### ISSUE THREAD

**Issue by VansonLeung** [godotengine/godot#3971] opened 2016-03-07 09:16 UTC
Operation System:
Macbook Pro Late 2014 , Yosemite 10.10.5

I could rotate the object, and pan the object
and I could also set perspective (which are preset angles)
but I do not know how to pan/rotate the viewport

I tried all possible control combinations with my Macbook trackpad.
I wonder if the pan/rotate controls are only available now for Mouse.

**Comment by VansonLeung** [comment] 2016-03-07 09:38
Tested:

Navigation Scheme: Godot => Shift / Ctrl / Alt modifiers do nothing
Navigation Scheme: Maya => Shift / Ctrl modifiers do nothing, Alt does Orbit
Navigation Scheme: Modo => Shift / Ctrl modifiers do nothing, Alt does Orbit

Setting Orbit Modifier, Pan Modifier or Zoom Modifier to anything => modifiers still do nothing special.

**Comment by neikeq** [comment] 2016-03-07 10:09
I think the Pan topic is a duplicate of #53

**Comment by VansonLeung** [comment] 2016-03-07 10:55
By the way, today is my first day trying out Godot 
and I just donated $5 USD.

I hope this engine would eventually replace Unity3D as my current only option.

**Comment by akien-mga** [comment] 2016-04-12 06:54
Closing as duplicate of #53, which has just been fixed by adding modifiers navigation for people without middle mouse button.

**Closed by akien-mga** 2016-04-12 06:54 UTC
Labels: enhancement, platform:osx, topic:editor, usability

**Comment by Download** [comment] 2024-07-11 13:47
> #53

If something was 'fixed' in issue #53, but people are still reporting issues on it 3918 issues later, maybe the 'fix' wasn't great. I am here because I have the same issue as OP.

First time Godot user. Have been (trying) to work with it for a few days now. Have spent multiple hours trying to figure out how to pan the viewport using my trackpad on my Mac M1 and have still not found a single working solution. I will check issue #53 next, but somehow I don't expect it to contain a fix for my situation...  

I tried one-finger drag, two-finger drag, Alt + one-finger drag, Alt + two-finger drag, Ctrl + one-finger drag etc etc and nothing works. I can zoom in/out and rotate around the selected object just fine, but not being able to pan the viewport is a show-stopper.

**Comment by Calinou** [comment] 2024-07-11 19:05
Please continue the discussion in https://github.com/godotengine/godot-proposals/issues/2295.
