### ISSUE TITLE
Tile map editor oversizes the GUI width

### ISSUE THREAD

**Issue by alexfacciorusso** [godotengine/godot#7461] opened 2017-01-07 15:45 UTC
macOS Sierra on MacBook Pro Retina 13" - Godot 2.1.1

When I select a TileMap node, the TileMap editor opens, making the right part of the Godot GUI disappear out of the window.

If I enlarge the window, making it larger than my screen width, the rightest part of the GUI is shown.

The only way to make it return to a normal state is to de-select the TileMap node and to resize manually the Godot window, forcing the UI to refresh.

![bug_recording](https://cloud.githubusercontent.com/assets/4479527/21742898/7cc6625e-d4f8-11e6-9f8a-2142f8e165a2.gif)

**Comment by bojidar-bg** [comment] 2017-01-07 15:56
Duplicate of #6461

**Closed by bojidar-bg** 2017-01-07 15:56 UTC
