### ISSUE TITLE
Changing the tooltip delay in project settings affects the editor

### ISSUE THREAD

**Issue by CowThing** [godotengine/godot#9030] opened 2017-06-03 00:26 UTC
**Operating system or device - Godot version:**
Windows 10 64bit - Godot 2.1.3 and Godot 3.0

**Issue description:**
Changing the tooltip delay in project settings will affect the editor's tooltips (after closing the project and reopening it). It should only affect the tooltips in-game.

**Steps to reproduce:**
Open any project, go to project settings and set tooltip delay to 0, then close the project and reopen it. Now all tooltips in the editor appear instantly.

**Comment by kubecz3k** [comment] 2018-04-04 15:59
First of all thank you for your report and sorry for the delay.

We released Godot 3.0 in January 2018 after 18 months of work, fixing many old issues either directly, or by obsoleting/replacing the features they were referring to.

We still have hundreds of issues whose relevance/reproducibility needs to be checked against the [current stable version](https://godotengine.org/download), and that's where you can help us.
**Could you check if the issue that you described initially is still relevant/reproducible in Godot 3.0 or any newer version, and comment about its current status here?**

For bug reports, please also make sure that the issue contains detailed steps to reproduce the bug and, if possible, a zipped project that can be used to reproduce it right away. This greatly speeds up debugging and bugfixing tasks for our contributors.

Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

Thanks in advance.

*Note: This message is being copy-pasted to many "stale" issues (90+ days without activity). It might happen that it is not meaningful for this specific issue or appears oblivious of the issue's context, if so please comment to notify the Bugsquad about it.*

**Comment by CowThing** [comment] 2018-04-04 23:02
Yes this issue still happens in Godot 3.0.2

**Comment by akien-mga** [comment] 2018-11-22 09:50
This seems to be fixed in the master branch (631cf676c).

**Comment by CowThing** [comment] 2018-11-23 13:58
I just tested this again with 1c16941 (from Calinou's nightly builds) and it's still happening.

**Comment by CowThing** [comment] 2018-12-12 15:16
@akien-mga Can this be reopened? It's still present in 3.1 alpha 3.

**Comment by moonlumen** [comment] 2024-02-12 01:16
This doesn't happen anymore

**Comment by Calinou** [comment] 2024-02-12 21:39
I can still reproduce this on v4.3.dev.custom_build [cbd43ce9b]:

https://github.com/godotengine/godot/assets/180032/4bfafbd1-7243-4b59-8fb3-97558061cdfc

Remember that tooltip delay project setting changes only affect the editor after you restart it.

**Comment by KoBeWi** [comment] 2024-03-20 23:14
This could be resolved with #85678 by adding a separate delay for editor.

**Closed** 2024-04-26 13:22 UTC
Labels: bug, topic:editor, confirmed, usability, topic:gui
