### ISSUE TITLE
Editor "Connect" button does weird stuff with C#

### ISSUE THREAD

**Issue by albinaask** [godotengine/godot#55221] opened 2021-11-22 09:33 UTC
### Godot version

3.4 stable

### System information

Windows 10

### Issue description

When I try to connect a button press to an already existing C# method, as a response Godot inserts a GDScript method stub into my script which isn't very appropriate. The expected behaviour would instead be to insert nothing since the method already exist. It does not seem to matter whether the project is just built or the script is asynced from the built version. 

Godot seem to insert the GDScript version of the stub even when the method specified does not exist

### Steps to reproduce

1. Open a mono project 
2. Add button to new scene
3. Add C# script, 
4. Press "Node" in the right panel
5. Press "Connect" on the "pressed" signal. 
6. Watch GDSCript stub in C# script.

**Comment by raulsntos** [comment] 2021-11-22 13:34
Maybe a duplicate of #39566. For me it works as described in https://github.com/godotengine/godot/issues/39566#issuecomment-898534782.

**Comment by albinaask** [comment] 2021-11-22 19:46
My external editor option is set to "Visual studio code" (which is the external tool I'm using) and it still inserts this:

```
func LoadWorld():
	pass # Replace with function body.
```

**Comment by ondesic** [comment] 2021-12-03 16:04
Same problem in 3.4.1.  It gets frustrating because of course this throws an error in the C# code.

**Comment by Calinou** [comment] 2021-12-03 16:06
@ondesic @albinaask Can anyone reproduce this on Godot 3.3, or is this just in 3.4?

**Comment by ondesic** [comment] 2021-12-04 02:55
I just tested this in 3.3.3
In 3.3.3 Godot doesn't even insert code in to Visual Studio Code.
This must be a new feature in 3.4 (to add the code snippet to VS Code)?

**Comment by Calinou** [comment] 2021-12-04 15:17
cc @Razoric480 

The LSP Make Function integration should be modified to insert C# code in C# scripts, or it should at least be disabled in C#.

**Comment by Razoric480** [comment] 2021-12-04 15:55
Given it's meant to be a GDScript LSP, I've gone ahead and just skipped over any non-GDScript languages when adding signals.

Doing mono LSP stuff should the job of the mono module.

**Comment by ondesic** [comment] 2021-12-04 16:26
I was excited that Godot was even inserting any code at all in VS Code.  Just needs one more step to insert C# code.

**Comment by Razoric480** [comment] 2021-12-04 16:33
> I was excited that Godot was even inserting any code at all in VS Code. Just needs one more step to insert C# code.

While I could add some C# parsing in theory, adding C# code to the GDScript module isn't really in spirit.

I suppose the ideal would be to split the LSP from the GDScript module and make it language agnostic, I.E. put it in its own module, then add overridable handlers in languages so that any scripting language could, in theory, use the LSP, just by passing which language to use.

**Comment by raulsntos** [comment] 2021-12-04 16:47
I'm confused about something here, I thought it was `ScriptTextEditor` that adds the signal to the script in:

https://github.com/godotengine/godot/blob/2a9dd654bc0197dd864df61b5b37e302022c2871/editor/plugins/script_text_editor.cpp#L274

Anyway, there is this issue https://github.com/godotengine/godot/issues/12908 that clarifies why it's not that simple to make this work with C# (and any other similar languages).

**Comment by Razoric480** [comment] 2021-12-04 16:50
> I'm confused about something here, I thought it was `ScriptTextEditor` that adds the signal to the script in:
> 
> https://github.com/godotengine/godot/blob/2a9dd654bc0197dd864df61b5b37e302022c2871/editor/plugins/script_text_editor.cpp#L274
> 
> Anyway, there is this issue #12908 that clarifies why it's not that simple to make this work with C# (and any other similar languages).

When the editor is not set to external, yes, it is. In which case that should go into the mono module.

When the editor is set to external, it does not add anything, but still emits the signal that one should be added. The LSP connects to that signal and then adds a function in those cases.

**Closed** 2021-12-06 16:46 UTC
Labels: bug, topic:editor, confirmed, topic:mono
