### ISSUE TITLE
Allow using import tools from command line

### ISSUE THREAD

**Issue by arypbatista** [godotengine/godot#9053] opened 2017-06-05 02:14 UTC
**Operating system or device - Godot version:**
Godot 2.1.3+

**Issue description:**
Allow using import tools from command line so Godot users can create scripts and automatize assets import.

For example:

- I could develop some scripts to help me refresh a group of fonts given a JSON configuration file, instead of manually re-importing one by one.
- I could batch import multiple images as textures, from multiple directories, and use the same script over and over as I update the source images.
- Have an script to monitor original images and watch for changes, automatically importing the assets as textures.

**Steps to reproduce:**
n/a

**Link to minimal example project:**

**Comment by bojidar-bg** [comment] 2017-06-05 09:26
Related/dupe of #533, I guess.

**Comment by akien-mga** [comment] 2017-06-28 13:05
Indeed.

**Closed by akien-mga** 2017-06-28 13:05 UTC
Labels: discussion, enhancement, topic:editor
