### ISSUE TITLE
global_mouse_position always return (0,0) on edited_scene_root

### ISSUE THREAD

**Issue by ajreckof** [godotengine/godot#63453] opened 2022-07-25 18:10 UTC
### Godot version

4.0.alpha12

### System information

MacOS Monterey 12.4 MacbookPro with M1 chip

### Issue description

When you try to get the global mouse position on the edited scene root to know where the mouse is on your scene it always return 0. On Godot 3.4 getting the mouse position on the edited root scene works perfectly.

### Steps to reproduce

Create an editor plugin and then use `get_tree().edited_scene_root.get_global_mouse_position()`

### Minimal reproduction project

`master`(broken) : [test_Godot_4.0.zip](https://github.com/godotengine/godot/files/9183784/test_Godot_4.0.zip)
`Godot 3.x` (working) : [test_Godot_3.4.zip](https://github.com/godotengine/godot/files/9183782/test_Godot_3.4.zip)

**Comment by KoBeWi** [comment] 2022-07-25 18:11
Duplicate of #60390

**Closed by KoBeWi** 2022-07-25 18:11 UTC
