### ISSUE TITLE
RichTextLabel's scroll_following setting does not work

### ISSUE THREAD

**Issue by scgm0** [godotengine/godot#78557] opened 2023-06-22 12:03 UTC
### Godot version

v4.1.beta3.official [ada712e06]

### System information

Godot v4.1.beta3 - Manjaro Linux #1 SMP PREEMPT_DYNAMIC Sun Jun  4 18:26:12 UTC 2023 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1650 (nvidia; 530.41.03) - Intel(R) Core(TM) i5-9300H CPU @ 2.40GHz (8 Threads)

### Issue description

scrolling_following is true, RichTextLabel also does not scroll its content automatically when adding_text.

### Steps to reproduce

1.Add a RichTextLabel node
2. 
```
func _ready() -> void:
	while true:
		add_text("abcd\n")
		await get_tree().create_timer(0.1).timeout
	pass
```

### Minimal reproduction project

None

**Comment by bitsawer** [comment] 2023-06-22 13:30
Probably a duplicate of https://github.com/godotengine/godot/issues/78434

**Comment by akien-mga** [comment] 2023-06-22 14:20
Thanks for the report, consolidating in #78434.

**Closed by akien-mga** 2023-06-22 14:20 UTC
Labels: bug, regression, topic:gui
