### ISSUE TITLE
Node names truncated in Inspector

### ISSUE THREAD

**Issue by miv391** [godotengine/godot#73644] opened 2023-02-20 18:58 UTC
### Godot version

v4.0.rc2.official [d2699dc7a]

### System information

Windows 10

### Issue description

Node names are truncated in Inspector view. Sometimes 1 character is missing, sometimes 2. Examples:
```
Node2D -> Node2 
Node3D -> Node3
Timer -> Tim
Foobar -> Foob
```
![kuva](https://user-images.githubusercontent.com/49998025/220181444-2b5f9806-9365-4cfd-88ba-904ee888b0e1.png)

### Steps to reproduce

Create a new project and add some nodes.

### Minimal reproduction project

N/A

**Comment by Zireael07** [comment] 2023-02-20 19:34
Duplicate of #73600, already fixed in master per that issue

**Closed** 2023-02-20 19:49 UTC
