### ISSUE TITLE
Godot editor suddenly highlights part of the code and deletes it

### ISSUE THREAD

**Issue by titonova** [godotengine/godot#34584] opened 2019-12-24 13:51 UTC
I've recently experienced a problem whereby as i type code in the godot editor, the cursor moves to another location on the same line, and/or highlights my code thus I write  the code in the wrong places.

I've tried restarting my computer several times, it doesn't seem to work.

I think it has to do with the bugs in my editor code but I am not sure

OS : Win64
Version: Godot 3.1

**Comment by Calinou** [comment] 2019-12-24 15:59
Could this be related to #25548 somehow?

**Comment by Calinou** [comment] 2020-03-08 13:34
Duplicate of #25548.

**Closed by Calinou** 2020-03-08 13:34 UTC
Labels: bug, topic:editor
