### ISSUE TITLE
Godot 4.0 beta 10 .NET 6 / mono crash loading project (seems unrelated to other similar issues)

### ISSUE THREAD

**Issue by AmyGilhespy** [godotengine/godot#71106] opened 2023-01-09 12:23 UTC
### Godot version

Godot_v4.0-beta10_mono_win64

### System information

Windows 10

### Issue description

I can't share my project because it uses assets that I'm not legally able to share, and it's also pretty big and therefore rather unhelpful for debugging an editor crash, but I will try to make a minimal reproduction project soon over the next few days.

There are a lot of issues with titles with similar wording, but I tried to look at all of them and none of them seem to be my issue.

I have been closely following the progression of Godot 4.0 with this project.  I started it in an early beta (I think beta 2?) and have updated it with every beta update that has come out.  Beta 8 worked fine, I missed beta 9, and beta 10 crashed, so I tried beta 9 and beta 9 worked fine also.  Therefore, the issue I am facing seems to have been introduced in beta 10.

I have never built Godot from source and historically I have had extreme difficulty building C++ projects on this computer.  I plan to try because I know I will be able to find the bug if I can just figure out how to compile Godot myself, as there were only 90 commits between betas 9 and 10 and I am perfectly willing to isolate them one-by-one until I find it.

I forgot where Godot stores its logs so I just ran the version that spawns a console instead so I could see what was causing the crash, and this is the last bit of output (posted at the end of this report).  I know this is not very helpful but I plan to add more information over the next day or two as I try to debug it myself.  Like I said, hopefully I can figure out how to build Godot myself because then I can be very helpful.

It looks like at least part of the error was due to the recent merge that added a default parameter to ProjectSettings.GetSetting (which I very much appreciate having that new default parameter, so thank you!)... I will try updating my code right after I submit this report and see if the crash error changes at all.

```
ERROR: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.TypeInitializationException: The type initializer for 'Amy.AmysGameCollection.Character2DSV' threw an exception.
 ---> System.MissingMethodException: Method not found: 'Godot.Variant Godot.ProjectSettings.GetSetting(System.String)'.
   at Amy.AmyUtil.InitLayers(String category, Int32 layerCount)
   at Amy.AmyUtil.Init2DPhysicsLayers() in D:\Godot\Projects\AmysGameCollection\Scripts\Amy\AmyUtil.cs:line 2015
   at Amy.AmyUtil.GetPhysics2DLayerNumberByName(String name, Boolean ignoreNonexistent) in D:\Godot\Projects\AmysGameCollection\Scripts\Amy\AmyUtil.cs:line 1212
   at Amy.AmysGameCollection.Character2DSV..cctor() in D:\Godot\Projects\AmysGameCollection\Scenes\Characters\Character2DSV.cs:line 210
   --- End of inner exception stack trace ---
   at Amy.AmysGameCollection.Character2DSV.GetGodotMethodList() in D:\Godot\Projects\AmysGameCollection\Godot.SourceGenerators\Godot.SourceGenerators.ScriptMethodsGenerator\Amy.AmysGameCollection.Character2DSV_ScriptMethods.generated.cs:line 15
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at Godot.Bridge.ScriptManagerBridge.GetMethodListForType(Type type) in /root/godot/modules/mono/glue/GodotSharp/GodotSharp/Core/Bridge/ScriptManagerBridge.cs:line 761
   at Godot.Bridge.ScriptManagerBridge.UpdateScriptClassInfo(IntPtr scriptPtr, godot_bool* outTool, godot_array* outMethodsDest, godot_dictionary* outRpcFunctionsDest, godot_dictionary* outEventSignalsDest, godot_ref* outBaseScript) in /root/godot/modules/mono/glue/GodotSharp/GodotSharp/Core/Bridge/ScriptManagerBridge.cs:line 593
   at: godotsharp_pusherror (modules/mono/glue/runtime_interop.cpp:1223)
Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at Godot.NativeInterop.NativeFuncs.godotsharp_internal_reload_registered_script(IntPtr)
   at Godot.Bridge.ScriptManagerBridge.CreateScriptBridgeForType(System.Type, Godot.NativeInterop.godot_ref*)
   at Godot.Bridge.ScriptManagerBridge.GetOrCreateScriptBridgeForType(System.Type, Godot.NativeInterop.godot_ref*)
   at Godot.Bridge.ScriptManagerBridge.GetOrCreateScriptBridgeForPath(Godot.NativeInterop.godot_string*, Godot.NativeInterop.godot_ref*)
```

### Steps to reproduce

Open my project in Godot 4.0 beta 10.

### Minimal reproduction project

(Coming soon, please give me a few days to try to make one)

**Comment by akien-mga** [comment] 2023-01-09 12:46
Given the error message, the likely culprit is 5aa243f9da1c8ae425ae5b6706fe889f6e301959, which added an optional `default_value` argument to `ProjectSettings.get_setting()`.

I'm not so familiar with .NET but I assume you have existing assemblies compiled with a previous version of Godot where the signature was `GetSetting(System.String)`, when in beta 10 it should be `GetSetting(System.String, Variant)`.
Since it crashes on start, I assume `AmyUtil.cs` is a `[Tool]` script, and since it's now invalid it raises an exception.

Deleting the `.mono` folder in the project folder should let you open it in beta 10, and compile with the new version of `GetSetting`.

@godotengine/dotnet It would be better if the editor could still be opened when a tool script is raising an exception, so that users can recompile with the new version without having to delete assemblies manually.

**Comment by AmyGilhespy** [comment] 2023-01-09 13:37
Thank you for your quick response!  Deleting .godot/mono (which used to be .mono) allows me to load my project in the new beta and rebuild it successfully!

I have been trying to make a minimal reproduction project anyway in order to prove the cause of the crash.  I don't want to abandon this issue just because it no longer affects me personally.  However, I have not yet been able to cause a crash intentionally in a new project.  AmyUtil is not actually a [Tool] script, but the static method from AmyUtil that calls ProjectSettings.GetSetting using the old signature is itself called from the constructor (actual C# class constructor, not _Ready) of another scene which was opened in another scene editor tab in Godot at the time I saved and built previously.  I think it being in the constructor of a scene opened in the editor is why Godot is running that code when it opens the project despite it not being a [Tool] script (to construct the open scene tree to display in the editor).

However, I have made a repro project using this information and it still won't crash... I am still trying, I just wanted to update.

**Comment by AmyGilhespy** [comment] 2023-01-09 13:58
You're right, I didn't notice it was a static constructor!  The offending code was this:

```cs
static Character2DSV()
{
    // ...
    LayerNumberGround = AmyUtil.GetPhysics2DLayerNumberByName("Ground");
    // ...
}
```

And `AmyUtil.GetPhysics2DLayerNumberByName` is a static method that used the old signature of `ProjectSettings.GetSetting`.  I will wrap static constructors in try...catch as you suggest in order to prevent future crashes as the API evolves.

Thank you both!

Would a minimal reproduction project still be helpful?

**Comment by raulsntos** [comment] 2023-01-10 00:49
Duplicate of https://github.com/godotengine/godot/issues/45723?

**Comment by akien-mga** [comment] 2023-01-10 07:32
Seems so.

> Would a minimal reproduction project still be helpful?

I believe with what was established so far, making a reproduction project shouldn't be too hard, but as neikeq mentions this might not be solvable, it may not be needed. I do hope we can find a workaround though.

Closing to consolidate in #45723.

**Closed by akien-mga** 2023-01-10 07:32 UTC
Labels: bug, topic:dotnet, crash, regression
