### ISSUE TITLE
holding the mouse button down blocks the "_on_mouse_entered" and other signals

### ISSUE THREAD

**Issue by RichardEllicott** [godotengine/godot#69668] opened 2022-12-06 15:04 UTC
### Godot version

3.5.1

### System information

Windows 10, issue present on all OS's

### Issue description

I am not entirely sure if it is a bug or a feature exactly but when you hold the mouse down and drag it, it will block any further on _on_mouse_entered signals

i am trying to make a card game where i need to drag one card to another card, which creates a contextual action like say for example one card attacks another card, it would also prevent making a typical drag drop windows style interface where you might say drag an item to a folder

a workaround would be appreciated... if for exampe some people rely on this unexpected behaviour for the sake of their program design... is their any way of querying godots internals, for example running a command that will query the screen at a particular position... for example, what controls are there etc.... i don't have the ability or knowhow to modify Godot's source to gain access to this internal information and none of the low level servers seem to deal with the UI controls

### Steps to reproduce

set up a color rectangles with a simple script to report the "_on_mouse_entered" signal to show the issue

move the mouse into the color rect to see the signal.... then try holding the mouse down while performing the same action, the signal will not trigger

### Minimal reproduction project

[ShowDragDropIssue.zip](https://github.com/godotengine/godot/files/10167603/ShowDragDropIssue.zip)

**Comment by Calinou** [comment] 2022-12-06 15:35
Duplicate of https://github.com/godotengine/godot/issues/20881.

**Closed by Calinou** 2022-12-06 15:35 UTC
