### ISSUE TITLE
Having an engine.cfg file in ~ (as in /home/username) stops the project list from running

### ISSUE THREAD

**Issue by dejaime** [godotengine/godot#7764] opened 2017-02-09 01:43 UTC
My system information: http://pasted.co/ca4970b9

How to reproduce:

1.  Copy a valid engine.cfg from any Godot project to your home folder
2.  Open Godot executable via shortcut or double click.

What happens is that Godot does not open the project list while the cfg file is there, instead it tries to run the project (not in the editor, but actually run it).

**Comment by volzhs** [comment] 2017-02-09 04:14
I can reproduce it with 2.x by putting `engine.cfg` and with master putting `godot.cfg` on `~/`

**Comment by volzhs** [comment] 2017-02-09 05:37
https://github.com/godotengine/godot/blob/master/drivers/unix/dir_access_unix.cpp#L244

this `getcwd(real_current_dir_name,2048);` makes real_current_dir_name pointing to `~` directory.

**Comment by hpvb** [comment] 2017-02-09 23:13
After doing some looking into this it appears that godot tries to start from pwd and move down each directory and checks for an engine.cfg. This seems to me to be entirely undesirable on unix systems at least, but I can't imagine it being particularly great on Windows and MacOS either.

Would someone object if I change this behavior to just look for engine.cfg in the current workdir rather than try each path all the way to the root?

**Comment by bojidar-bg** [comment] 2017-02-10 08:56
Well, I guess the idea is similar to how `git` works -- it starts in the current directory and moves up until it reaches `.git` (or filesystem end). If we do this, it would make it impossible to start godot from somewhere deep within the project tree, but only from the project's root (not that I object personally, but maybe it is useful in some cases).

For an exercise, try putting a `.git/` folder in `~` :wink:

**Comment by hpvb** [comment] 2017-02-10 08:58
Actually probably the following paths should be checked:
* Current workdir
* The directory of the binary itself

This way launching a godot game from a different directory will still work (for e.g launchers) and running godot in your project directory will still open it. Maybe for a tools build we should default to the editor rather than running the project though. 

Thoughs?

**Comment by bojidar-bg** [comment] 2017-02-10 08:59
BTW, duplicate problem of the _closed_ #7234 (but this one shouldn't be closed anyway, since it is more complete)

**Comment by hpvb** [comment] 2017-02-10 09:00
@bojidar-bg I understand the idea behind it but I think for godot it's less expected than for git. (I hadn't seen your comment before typing my previous one)

I'm not sure if people will actually expect it to pick up an engine.cfg from anywhere below. Going past the user's homedirectory 'down' (which it does now) seems a little strange also. There *really* shouldn't be a godot.cfg in / :)

**Comment by bojidar-bg** [comment] 2017-02-10 09:00
@hpvb Sounds cool, yeap, just make sure running the game with #7470 applied still works.

**Comment by hpvb** [comment] 2017-02-10 09:02
@bojidar-bg very, very bad indeed :P What were you agreeing to exactly? :D

**Comment by bojidar-bg** [comment] 2017-02-10 09:04
@hpvb I was agreeing to:

> Actually probably the following paths should be checked:
>
> * Current workdir
> * The directory of the binary itself

**Comment by hpvb** [comment] 2017-02-10 09:05
@bojidar-bg Any thoughts on opening the editor by default rather than running the project with a 'tools' build? I'd rather see a '-r <run the project>' rather than make '-e <run the editor>' the exceptional case.

**Comment by bojidar-bg** [comment] 2017-02-10 12:13
@hpvb Maybe we don't need to change this behaviour, but if it need changing, then `-r` to force-run makes some sense.

**Comment by akien-mga** [comment] 2017-02-10 12:21
I'm fine with the above proposal, just not with:

> Any thoughts on opening the editor by default rather than running the project with a 'tools' build? I'd rather see a '-r ' rather than make '-e ' the exceptional case.

So far there hasn't been many requests to change that, so it's probably not that important. Also, I prefer having a game start in a couple seconds, close it, and append `-e` to the command line to open the editor instead, than having the editor start in 15 s, close it, and append `-r` because I actually wanted to play the game. And having `-e` as an additional option for the tools build makes more sense than changing the default behaviour compared to non-tools build and having instead another `-r` argument to force the non-tools behaviour.

**Comment by hpvb** [comment] 2017-02-10 12:26
OK, I'll limit myself to the path changes then.

**Comment by reduz** [comment] 2017-08-05 19:39
this no longer needs fixing, given the access to datapacks changed.
Godot will try to run the project by default if a project.godot is found at that directory, this is not a bug but a feature. It also allows you to use the editor binary for testing deploys.

**Comment by akien-mga** [comment] 2017-09-25 21:22
Actually still needs fixing, but #11539 fixes it.

**Closed** 2017-10-11 21:37 UTC
Labels: discussion, enhancement, platform:linux, topic:core, topic:editor

**Comment by dejaime** [comment] 2018-10-10 02:53
Thanks for the fix! Really appreciate it.
