### ISSUE TITLE
Node paths to editable children in custom resources do not save

### ISSUE THREAD

**Issue by SomeSortOfSam** [godotengine/godot#82320] opened 2023-09-25 18:40 UTC
### Godot version

v4.1.1.stable.official [bd6af8e0e]

### System information

Godot v4.1.1.stable - Windows 10.0.19045 - Vulkan (Compatibility) - AMD Radeon(TM) R7 Graphics () - AMD A10-7800 Radeon R7, 12 Compute Cores 4C+8G (4 Threads)

### Issue description

I was attempting to bundle a bunch of information into the same array element by making a custom resource, and was then frustrated when the nodes in said array never got saved. Doing some testing, I've found out that it only affected editable children. Every time I try to save the scene with a resource with a node path to an editable child, the console spits out this error
![image](https://github.com/godotengine/godot/assets/57550537/519c358a-01d7-4f13-ab74-bc7e6627c23b)

For my particular problem, this can be worked around with multiple arrays, as when not in a resource the nodes do save

### Steps to reproduce

1. Create a custom resource with an exported node
2. Create a scene with a child, where one of the nodes has a script that that exports the custom resource
3. Create a scene with the previous scene instanced inside it. Set child to editable children
4. Create the resource inside the child, and assign the node field to an editable child
5. Save (the editor may crash at this point)
6. Reopen the project - the node path inside the resource will now be blank

### Minimal reproduction project

[ResourceNodePathBug.zip](https://github.com/godotengine/godot/files/12718110/ResourceNodePathBug.zip)

**Comment by SaNeOr** [comment] 2023-09-26 19:26
Looking at the result of the serialization, if your field is a Node, then it actually holds an Object instance (since Nodes also inherit from Object), but the Node is not instantiated during deserialization (which makes sense to me, otherwise you'd be reloading the scene again with an additional Node, but it might take some hints?)

However, for your needs.  If you want to refer to an object in the scene, you can use **NodePath**

**Comment by YuriSizov** [comment] 2023-09-26 19:58
Thanks for your report. This is a duplicate of https://github.com/godotengine/godot/issues/80538. This is also not a bug.

Resources cannot export nodes. Exporting nodes only makes sense for other nodes, because both the exporter and exportee need to exist in the scene tree. Resources are not a part of the scene tree, they cannot resolve node paths because of that. Plus the same resource can be shared between multiple nodes or non-node objects, like other resources. This makes any kind of resolution of node paths impossible.

As suggested, you can export and store the node path as is in your resource, and resolve the node as fits your game logic yourself.

**Closed** 2023-09-26 19:58 UTC
