### ISSUE TITLE
CSG missing UV2

### ISSUE THREAD

**Issue by SuperDIMMaX** [godotengine/godot#39974] opened 2020-06-30 05:12 UTC
**Godot version:**
Any?

**OS/device including version:**
Any?

**Issue description:**
CSG not have UV2. and no have Vertex Color

**Steps to reproduce:**
Example minimal code:
```
var mdt = MeshDataTool.new()
mdt.create_from_surface(mesh, 0)
for i in range(mdt.get_vertex_count()):
	mdt.set_vertex_uv2(i,Vector2(1,1))
mdt.commit_to_surface(mesh)
```

`mdt.set_vertex_uv(i,Vector2(1,1))` - is working

And can be add Vertex color? (interpolation resolver)

For logical and perfomance reason, this need additional check boxes to editor and parametr in code func (if problem with capability - add last parametr - bitflags, with default value).

**Comment by akien-mga** [comment] 2020-06-30 05:52
Duplicate of #39972.

**Closed by akien-mga** 2020-06-30 05:52 UTC
