### ISSUE TITLE
WorldEnvironment is affecting editor's windows

### ISSUE THREAD

**Issue by qwe3121** [godotengine/godot#72465] opened 2023-01-31 19:25 UTC
### Godot version

godot 4 beta 16

### System information

Windows 11, Vulcan, GTX 1050 TI (driver geforce game ready 528.24)

### Issue description

WorldEnvironment is affecting editor's windows:
for example, if glow is enabled and blend mode set to replace, all windows of editor became black
![image](https://user-images.githubusercontent.com/95754732/215859176-61e54c69-f5bb-454d-8feb-9ced4d34d30c.png)
glow is enabled, blend mode set to additive, and strength set to 2
![image](https://user-images.githubusercontent.com/95754732/215859503-d3033008-269d-42bd-9b44-b890f30afc93.png)
also if you move to other scene all became normal
![image](https://user-images.githubusercontent.com/95754732/215859678-6f7e3049-9592-47f9-9933-c8418b2e3094.png)
so the scene with world evn node should be open to see this bug
(back to node_2d from node_2d_2 and there is bug again)
![image](https://user-images.githubusercontent.com/95754732/215859921-07280b03-1176-481d-a452-690231dd59a5.png)

### Steps to reproduce

1) create project (Forward+)
2) create Node2D
3) add WorldEnvironment
4) create New Environment resource
5) set background mode to canvas
![image](https://user-images.githubusercontent.com/95754732/215860341-8359caed-536a-4a7e-b7c6-134ac3e59b85.png)
6) enable glow
7) for example, change your blend mode to replace 
8) for example, open project settings
![image](https://user-images.githubusercontent.com/95754732/215860526-94f11bf9-e1a8-4e3f-baf5-949b370bda62.png)

### Minimal reproduction project

[Bug.zip](https://github.com/godotengine/godot/files/10549994/Bug.zip)

**Comment by clayjohn** [comment] 2023-01-31 19:38
Duplicate of https://github.com/godotengine/godot/issues/69122

Fixed by https://github.com/godotengine/godot/pull/72343

The fix will be in Beta 17

**Closed by clayjohn** 2023-01-31 19:38 UTC
