### ISSUE TITLE
Using ViewportTexture in TextureButton shows flipped content

### ISSUE THREAD

**Issue by BeayemX** [godotengine/godot#21353] opened 2018-08-24 08:29 UTC
**Godot version:**

The bug occurs in 3.0.6 stable and in the latest build from master (34e58fd831172bad1eebb748c97238c28864423a)

**OS/device including version:**

Linux Mint 19

**Issue description:**

When using a viewport as the content for a ViewportContainer everything is working fine.
When using the same viewport as a ViewportTexture for a TextureButton the image is shown upside down.

![image](https://user-images.githubusercontent.com/3453076/44573887-2b617c00-a788-11e8-908b-6fba55169a0b.png)

**Minimal reproduction project:**
[ViewportAsTextureButtonBug.zip](https://github.com/godotengine/godot/files/2317604/ViewportAsTextureButtonBug.zip)

**Comment by Noshyaar** [comment] 2018-08-24 09:01
Due to the math behind the rendering of viewport, the Y axis flips. That's why Viewport comes with Flip_V property. TextureButton actually renders it correctly. Since ViewportContainer is used to show viewport content, it conveniently compensates for this by drawing it upside-down:

https://github.com/godotengine/godot/blob/34e58fd831172bad1eebb748c97238c28864423a/scene/gui/viewport_container.cpp#L135-L138

**Comment by reduz** [comment] 2018-09-07 23:02
This will probably be solved the right way in 3.2

**Comment by akien-mga** [comment] 2020-01-08 09:34
Still reproducible in the current master branch (ed22a4c4542). The "3.2" reference in the above comment was about the Vulkan renderer, so actually 4.0.

**Comment by KoBeWi** [comment] 2020-12-10 00:23
Fixed in 4.0-dev.

**Closed by KoBeWi** 2020-12-10 00:23 UTC
Labels: bug, topic:core, topic:gui
