### ISSUE TITLE
The editor window sometimes doesn't gain focus when an error occurs while debugging

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#19531] opened 2018-06-12 18:51 UTC
Godot 3.0.2
Windows 10 64 bits

I noticed this quite often:
When I launch a game and an error happens, the debugger will issue a breakpoint. The game will then freeze on top of the editor. And sometimes, the game just stays on top.

1) Shouldn't Godot just take focus when that happens?

So given that situation, I usually try to click anywhere in the editor to give it focus and bring the window forward, however it often has no effect (if not always?). I have to click the window decoration (top bar) in order for Godot to be brought forward.

2) Shouldn't Godot go to foreground when clicking inside?

**Comment by vnen** [comment] 2018-06-12 21:41
> I have to click the window decoration (top bar) in order for Godot to be brought forward.

Maybe this happens because of the failed focus grab?

**Comment by Calinou** [comment] 2020-06-07 20:21
@Zylann Can you (or anyone else) still reproduce this bug in Godot 3.2.1 or [3.2.2beta4](https://godotengine.org/article/dev-snapshot-godot-3-2-2-beta-4)?

**Comment by Zylann** [comment] 2020-06-07 20:22
I don't have a clear repro for this, but it's been a while since it happened to me.

**Comment by Calinou** [comment] 2020-06-07 20:41
@Zylann Alright, I'll close this for now.

If someone can reproduce this bug, please comment so this issue can be reopened.

**Closed by Calinou** 2020-06-07 20:41 UTC
Labels: bug, topic:editor
