### ISSUE TITLE
Double clicking a snake case variable does not select the whole variable

### ISSUE THREAD

**Issue by QbieShay** [godotengine/godot#49769] opened 2021-06-20 18:02 UTC
### Godot version

v4.0.dev.custom_build [1acc76fec]

### System information

Linux

### Issue description

Previously in Godot, when double clicking on a `snake_case` piece of text, the whole `snake_case` text was higlighted. Now it will trea the `_` as a whitespace and higlight only the half where you double clicked. Liikely a regression?

### Steps to reproduce

- Create a script
- Create a variable called `snake_case`
- Double click on `snake`
- Observe that only `snake` is selected and not the whole `snake_case` word

**Comment by Chaosus** [comment] 2021-06-21 05:43
Duplicate of https://github.com/godotengine/godot/issues/46380, (I've created a similar issue but it was closed as a duplicate too: https://github.com/godotengine/godot/issues/49673)

**Closed by Chaosus** 2021-06-21 05:43 UTC
