### ISSUE TITLE
Color Picker Hex Tooltip prevents key events

### ISSUE THREAD

**Issue by LauraWebdev** [godotengine/godot#84877] opened 2023-11-14 09:56 UTC
### Godot version

4.1.2-stable

### System information

Windows 11, macOS 14.0

### Issue description

<img width="532" alt="image" src="https://github.com/godotengine/godot/assets/7365286/f8ea1d38-4185-4eef-a6e3-39326ffd25c7">

This tooltip that shows up when hovering over the hex input field in a color picker prevents any key events.

It has been a small annoyance in workflow for months, since I tend to click on the color property and want to start typing my hex code. This problem can be mitigated by moving the mouse after clicking in that area.

### Steps to reproduce

- Open a color picker in the properties panel
- Click into the hex input, the tooltip will show up
- Try entering a hex code while the tooltip is shown

What I would expect as a user:
- Open a color picker in the properties panel
- Click into the hex input, the tooltip will show up
- You can enter a hex code, the tooltip either stays or dismisses, but you are not prevented entering something

### Minimal reproduction project

Any empty project will do, as this is a problem with the color picker editor UI.

**Comment by AThousandShips** [comment] 2023-11-14 10:00
Duplicate of https://github.com/godotengine/godot/issues/79500

**Closed by AThousandShips** 2023-11-14 10:00 UTC
