### ISSUE TITLE
Godot freezes at start up in general when running on Windows 11

### ISSUE THREAD

**Issue by LeCloutPanda** [godotengine/godot#90893] opened 2024-04-19 09:15 UTC
### Tested versions

Godot Engine v4.2.2.stable.official.15073afe3

### System information

Windows 11 - Vulkan API 1.3.277 - Forward+ also Compatability

### Issue description

When booting Godot, loading projects and running the project Godot hangs for a minute or two then eventually loads, this didn't happen when I was on Windows 10 but started since upgrading to 11. It loads and runs instantly if ran through a powershell set to headless.

### Steps to reproduce

Open Godot both the normal and mono builds on Windows 11

### Minimal reproduction project (MRP)

Not Needed.

**Comment by m4rr5** [comment] 2024-04-19 18:20
I've just downloaded the 4.2.2 release and tried it on my Windows 11 system, but it does not hang for me. Not when I start Godot, not when I open a project. If I had to take a blind guess, I'd say there is either some shell extension or a network drive mapped on your system that no longer exists and hangs until it finally times out. Could you try this on a different computer (if you have more than one)? Also, try looking at your network neighborhood to see if there's anything there that could cause it. Maybe as a test try running Godot while completely offline (disconnected from the local network, with the network interface down).

**Comment by Zireael07** [comment] 2024-04-19 19:01
... or a misbehaving USB device driver (people have had similar issues)

**Comment by LeCloutPanda** [comment] 2024-04-20 03:50
> I've just downloaded the 4.2.2 release and tried it on my Windows 11 system, but it does not hang for me. Not when I start Godot, not when I open a project. If I had to take a blind guess, I'd say there is either some shell extension or a network drive mapped on your system that no longer exists and hangs until it finally times out. Could you try this on a different computer (if you have more than one)? Also, try looking at your network neighborhood to see if there's anything there that could cause it. Maybe as a test try running Godot while completely offline (disconnected from the local network, with the network interface down).

When trying this I still have the issue, I disabled all known networks and there aren't any network storage devices attached.

> ... or a misbehaving USB device driver (people have had similar issues)
As for this one none of my drivers have updated and I've tried unpluggin all my usbs and just using my keyboard and I still have the issue.

Again when I run it in headless mode it is fine, it loads the project and prints a test string out but if I try to to launch the Project Selector, Editor and Game it hangs trying to what I believe is initialize some graphic stuff.

**Comment by LeCloutPanda** [comment] 2024-04-20 07:55
Running Godot 4.0+ through powershell with `--verbose` it hangs just before `Using "winink" pen tablet driver...` leading me to uninstalling my tablet drivers but it still hangs on this line then it loads the rest of the program.

If I run it with `--verbose` and `--headless` it still loads near instantly and doesn't hang. I am still actively testing stuff.

**Comment by LeCloutPanda** [comment] 2024-04-20 08:44
With even more testing I did a benchmark test running godot normally and in headless mode.
[Normal Boot.txt](https://github.com/godotengine/godot/files/15047482/Normal.Boot.txt)
[Headless Boot.txt](https://github.com/godotengine/godot/files/15047483/Headless.Boot.txt)

**Comment by akien-mga** [comment] 2024-04-20 09:31
What is your GPU and GPU drivers version?

**Comment by LeCloutPanda** [comment] 2024-04-20 09:47
GPU: RTX 4060 Ti 
Tested driver versions: 551.76

Edit: Before even posting this I checked to see if I had a driver update and I did so I updated and it just now works... so it was something wrong between 551.76 - 552.22, Nvidia did not let me know there was a driver update. But the odd thing is I had updated my drivers since it stopped working correctly so Nvidia must have broken something.

**Comment by akien-mga** [comment] 2024-04-20 09:52
Thanks for testing! Closing then as it's a Nvidia driver regression which they fixed already.

**Closed by akien-mga** 2024-04-20 09:52 UTC
Labels: bug, platform:windows, needs testing

**Comment by LeCloutPanda** [comment] 2024-04-21 14:28
I am re-opening this as I booted my pc back up and it has started to die once again going back to the original issue of hanging when loading normally and still boots quickly when using headless.

**Comment by sayoun** [comment] 2024-05-03 22:14
I have exactly the same issue as @LeCloutPanda , I have a RTX 4070 Super TI and it goes black everytime it starts, I tried with Nvidia driver 552.22 and 552.31 and it the same effect,

**Comment by cacklinglaughing** [comment] 2024-10-29 05:20
same problem, Windows 11 RTX 4070 and GRD 565.90. opening godot editor freezes for a minute, and then it loads. opening the game freezes for a minute, then that loads. both times, right before that freeze ends my nvidia hint that says i can use it with highlight clips pops up.

**Comment by cacklinglaughing** [comment] 2024-10-29 05:34
it also loads instantly with --headless, but the winink line is the first line that shows up *after* the freeze happens, and since this is a brand new computer i've never installed a tablet driver. i just updated my driver and it still freezes but i did not reboot after doing it.

**Comment by xrabohrok** [comment] 2025-03-22 20:02
Google has a high chance of dropping people here so I'll put this here:

My laptop (Win11/ core-i9 / rtx4070) after opening a project in Godot (4.2-4.4)  would grand-mal seize on an issue that looks a lot like this.  I would get a few seconds of good performance, but the moment I would interact with the the node editor it would freeze completely.  

Someone on issue #103087 suggested  turning the editor setting "Single Window mode" on and restarting (Editor ->Editor Settings... -> Interface/Editor -> Single Window Mode. _This worked for me._  YMMV.
