### ISSUE TITLE
trying to overwrite a non empty folder in trash with another one of the same name by deleting it gives error

### ISSUE THREAD

**Issue by josuraki** [godotengine/godot#46226] opened 2021-02-19 16:31 UTC
**Godot version:**
3.2.3 stable

**OS/device including version:**
xubuntu 20.04

**Issue description:**
as stated in title, if you have a non empty folder in your trash and try to delete another folder of the same name inside godot's file system dock, it just replies with an unspecific error instead of telling you that it cant be overwritten because its not empty.
this means you would have to manually empty your trash to delete another folder of the same name.

i am aware that this probably relates to the missing trashinfo issue discussed in #44021 as it only happens when deleting files through godot and not through normal filemanagers, meaning godot just creates weird trash files

godot error is:
`Cannot remove: res://folder_name`

the terminal gives you this:
`mv: cannot move '/home/user/project_name/folder_name/' to '/home/user/.local/share/Trash/files/folder_name': Directory not empty`

**Steps to reproduce:**
1. create folder in file system dock and put anything (folder, script, etc.) into it
2. delete it through file system dock
3. create new folder of the same name as first folder
4. delete it through file system dock
5. enjoy error message

**Comment by Calinou** [comment] 2022-05-28 20:46
I can't reproduce this on 3.5.rc 20c72e827 (Fedora 36 KDE). This was likely fixed by https://github.com/godotengine/godot/pull/44021.

This is what I get in the system trash after following the reproduction steps – no error messages are printed by Godot in the process.

![image](https://user-images.githubusercontent.com/180032/170842292-eaf25725-f087-49b8-b144-ec017cd3b01d.png)

**Closed by Calinou** 2022-05-28 20:46 UTC
Labels: bug, platform:linuxbsd, topic:editor, topic:porting
