### ISSUE TITLE
Weird boxes in some ItemList dialogs

### ISSUE THREAD

**Issue by MewPurPur** [godotengine/godot#85028] opened 2023-11-17 19:21 UTC
### Godot version

Godot v4.2.rc1 - Pop!_OS 22.04 LTS - X11 - GLES3 (Compatibility) - Mesa Intel(R) Graphics (ADL GT2) () - 12th Gen Intel(R) Core(TM) i5-1235U (12 Threads)

### System information

Godot v4.2.rc1 - Pop!_OS 22.04 LTS - X11 - GLES3 (Compatibility) - Mesa Intel(R) Graphics (ADL GT2) () - 12th Gen Intel(R) Core(TM) i5-1235U (12 Threads)

### Issue description

I get random boxes in the UI of multiple dialogs.

![image](https://github.com/godotengine/godot/assets/85438892/1878b1a5-06dc-4c31-9d85-3233f8c44f0c)

![image](https://github.com/godotengine/godot/assets/85438892/cb7e246e-bbb3-44e7-9c83-8c6a0c7db9eb)

### Steps to reproduce

Go to these dialogs - connections dialog and quick open dialog

### Minimal reproduction project

N/A

**Comment by MewPurPur** [comment] 2023-11-17 19:26
There's no change in behavior from them, for clarity, it's just a visual glitch.

**Comment by Sauermann** [comment] 2023-11-17 19:35
I believe, that this is tracked in #74115

**Comment by MewPurPur** [comment] 2023-11-17 19:46
Cool, this is an issue I started getting very recently for these dialogs.

**Comment by AThousandShips** [comment] 2023-11-17 19:50
Not the same, that issue is for the compatibility renderer, seems to have spread to the Vulkan renderer as well

**Comment by MewPurPur** [comment] 2023-11-17 19:53
WAIT no, it's on the Compatibility renderer. I'll fix this.

**Comment by AThousandShips** [comment] 2023-11-17 19:54
Duplicate of https://github.com/godotengine/godot/issues/74115

**Closed by AThousandShips** 2023-11-17 19:54 UTC
Labels: bug, topic:editor, topic:gui
