### ISSUE TITLE
Changing Custom Font's Dynamic Font's Font Data's Font Path doesn't refresh font on GUI node

### ISSUE THREAD

**Issue by kuhnchris** [godotengine/godot#47234] opened 2021-03-21 15:31 UTC
**Godot version:**
3.3-rc6 (custom, Godot Engine v3.3.rc.custom_build.9a5776cd1 - https://godotengine.org )

**OS/device including version:**
ArchLinux
OpenGL ES 3.0 Renderer: AMD RENOIR (DRM 3.40.0, 5.11.6-arch1-1, LLVM 11.1.0)
OpenGL ES Batching: ON

**Issue description:**
Changing the font path (i.e. changing the font) in a RichTextLabel doesn't refresh the display

**Steps to reproduce:**
- Add RichTextLabel
- Enter some text
- Add a Custom Fonts > Normal Fonts (New DynamicFont) > Font > Font Data (New DynamicFontData) > Font Path Object, i.e. select a custom font
- Text gets properly refresh with new font
![image](https://user-images.githubusercontent.com/761911/111910647-8bb11b00-8a62-11eb-9783-b041db2a11f3.png)
- Go to the Font Data and change Font Path, i.e. change to a different font:
![image](https://user-images.githubusercontent.com/761911/111910666-9ff51800-8a62-11eb-967b-d72f5bf8ac9f.png)
- The font is not changed!
![image](https://user-images.githubusercontent.com/761911/111910678-af746100-8a62-11eb-8576-f16efe1c55fe.png)
- Changing font size or other parameters does not load the proper font in, so it is "cached"
![image](https://user-images.githubusercontent.com/761911/111910708-c450f480-8a62-11eb-88bb-8e8214a966e9.png)
- Closing and reopening the scene fixes it, but it should be like this directly after changing the font!
![image](https://user-images.githubusercontent.com/761911/111910723-d6cb2e00-8a62-11eb-96d9-4824376fb2bf.png)

**Minimal reproduction project:**
[godot-33rc6-dynfontpath.zip](https://github.com/godotengine/godot/files/6177753/godot-33rc6-dynfontpath.zip)

**Comment by Calinou** [comment] 2021-03-21 17:57
Duplicate of https://github.com/godotengine/godot/issues/27106 (same cause).

**Closed by Calinou** 2021-03-21 17:57 UTC
