### ISSUE TITLE
When I click on physic button, nothing happens MAC

### ISSUE THREAD

**Issue by ehsanxt** [godotengine/godot#82990] opened 2023-10-08 09:12 UTC
### Godot version

4.1.2

### System information

Mac OS Big Sur - 11.7.10

### Issue description

When I click on physic button to add collision, nothing happens. Am I doing anything wrong or is this a bug?
![Bug](https://github.com/godotengine/godot/assets/1328670/bb2c538d-cb3c-4d94-bd39-100c7d342be1)

### Steps to reproduce

Select a tilemap, click paint, Paint properties. click Physic button.

### Minimal reproduction project

[2d.zip](https://github.com/godotengine/godot/files/12840248/2d.zip)

**Comment by AThousandShips** [comment] 2023-10-08 09:15
Duplicate of https://github.com/godotengine/godot/issues/75592

**Closed by AThousandShips** 2023-10-08 09:15 UTC

**Comment by ehsanxt** [comment] 2023-10-08 09:40
so maybe message box should appear and says something about lack of physic layer, when we click on it a disable box appears like it has problem.

**Comment by AThousandShips** [comment] 2023-10-08 09:44
There is:
* #79676

Available in 4.2
