### ISSUE TITLE
TileMap errors after shrinking atlas image

### ISSUE THREAD

**Issue by Lemonymous** [godotengine/godot#79199] opened 2023-07-08 12:06 UTC
### Godot version

4.1.rc3.mono

### System information

Windows 10, Forward+, NVIDIA GeForce GTX 1050 Ti (31.0.15.3179)

### Issue description

Replacing a TileMap's TileSet's image with a smaller one outside of the Godot editor introduces errors when running the application.
It appears that the TileSet continues to hold some information about the old image, and errors because that data refers to tiles outside of the current texture size.

I have not found a good in-editor way to fix these errors without recreating the whole TileSet again from scratch.

I was however able to remove the errors by manually editing the TileMap tscn file and remove every line starting with a coordinate (x:y) outside of the current texture's extents.

### Steps to reproduce

- Create a new project
- Create a two pngs of different sizes (e.g. 32x16 and 48x16) and only move the large image to your project folder
- Create a `TileMap` node
- `Inspector` -> `Tile Set` -> `New TileSet`
- Drag the large image into `Tiles` in the bottom window
- "The atlas's texture was modified. Would you like to automatically create tiles in the atlas?" -> Yes
- Outside of the Godot editor, replace the large image with the small image you created earlier.
- Go back to the Godot editor. Save, and launch the project.
- Observe 3 errors per tile that the large image had, that the small does not.
```
E 0:00:00:0910   create_tile: Cannot create tile. The tile is outside the texture or tiles are already present in the space the tile would cover.
  <C++ Error>    Condition "!room_for_tile" is true.
  <C++ Source>   scene/resources/tile_set.cpp:4138 @ create_tile()
E 0:00:00:0910   has_alternative_tile: The TileSetAtlasSource atlas has no tile at (2, 0).
  <C++ Error>    Condition "!tiles.has(p_atlas_coords)" is true. Returning: false
  <C++ Source>   scene/resources/tile_set.cpp:4518 @ has_alternative_tile()
E 0:00:00:0910   create_alternative_tile: TileSetAtlasSource has no tile at (2, 0).
  <C++ Error>    Condition "!tiles.has(p_atlas_coords)" is true. Returning: TileSetSource::INVALID_TILE_ALTERNATIVE
  <C++ Source>   scene/resources/tile_set.cpp:4468 @ create_alternative_tile()
```

### Minimal reproduction project

This project has gone through the exact same steps as in the outlined in `Steps to reproduce`, and will throw errors when running it.
[tileset_errors.zip](https://github.com/godotengine/godot/files/11990566/tileset_errors.zip)

**Comment by Calinou** [comment] 2023-07-08 14:36
- Related to https://github.com/godotengine/godot/issues/74946 (possible duplicate?).

**Comment by KoBeWi** [comment] 2023-07-08 15:36
Duplicate of #61296

> I have not found a good in-editor way to fix these errors without recreating the whole TileSet again from scratch.

You can restore the big texture, remove tiles that would end up outside and go back to smaller texture.

**Closed by KoBeWi** 2023-07-08 15:36 UTC
Labels: bug, topic:import, topic:2d

**Comment by qalmurri** [comment] 2023-12-14 07:07
If you have a 32x32.png spritesheet for Isometric. In Tilemap, use Isometric 32x32 first, then import spritesheet 32x32.png. If so, set the Tilemap to 32x16. It's like a reversal method. You have to try it.....
