### ISSUE TITLE
GDScript: Getting error with extending by script path and class_name

### ISSUE THREAD

**Issue by DarkMessiah** [godotengine/godot#42222] opened 2020-09-21 08:17 UTC
**Godot version:**
Reproduced in: **Godot_v3.2.2-stable_win64** and **Godot_v3.2.3-stable_win64**
Works in: **Godot_v3.2.1-stable_win64**

**OS/device including version:**
Windows 10 64bit

**Issue description:**
Getting error when open "Create New Node" dialog:
`core/script_language.cpp:244 - Condition "!global_classes.has(p_class)" is true. Returned: String()`

**Steps to reproduce:**
1) Create 2 scripts

```gdscript
#BaseNode.gd
extends Node
```

```gdscript
#NewNode.gd
class_name NewNode
extends "res://BaseNode.gd"
```
2) Open "Create New Node" by "+" in Editor

**Minimal reproduction project:**
[godot_issue.zip](https://github.com/godotengine/godot/files/5254127/godot_issue.zip)

**P.S.:** If add class_name BaseNode and extends from it, all works fine. I think, godot can't recognize base class when you try extends by script path.

**Comment by DarkMessiah** [comment] 2020-09-21 08:17
Maybe same issue https://github.com/godotengine/godot/issues/41486?

**Comment by Calinou** [comment] 2020-09-21 12:42
Duplicate of #41486.

**Closed by Calinou** 2020-09-21 12:42 UTC
