### ISSUE TITLE
Strange behavior with the tree nodes dock

### ISSUE THREAD

**Issue by Torguen** [godotengine/godot#46753] opened 2021-03-07 11:55 UTC
**Godot version:**

3.2.4 rc3 mono

**OS/device including version:**

win10 64

**Issue description:**

In the gif you can see that when a node is selected and the "up" and "down" cursors are pressed the placeholders fail to point to the currently selected node.

This happens when, for example, you have a main node and you add the node "AnimationTreePlayer", it seems that the too long name has something to do with this.

look at the tree of nodes in the following gifs

Behavior 1
The gray line goes up and down but the highlight box doesn't move.
![behavior1](https://user-images.githubusercontent.com/19652075/110238880-43630a80-7f44-11eb-8fd1-3a85158f1a78.gif)

Behavior 2
The highlight box moves, but once it reaches the top, it no longer moves down.
![behavior2](https://user-images.githubusercontent.com/19652075/110238886-4827be80-7f44-11eb-99d1-aa4c64b722c7.gif)

In both cases the "dock" inspector shows the correct information.

**Steps to reproduce:**
Create a 2D scene
Add a node principal node and add a node like "AnimationTreePlayer" (I know the node is out of date but the problem seems to be with long names)
Select the node "AnimationTreePlayer" press the cursor up to select the main node.

**Minimal reproduction project:**

[Test.zip](https://github.com/godotengine/godot/files/6097031/Test.zip)

**Comment by KoBeWi** [comment] 2021-03-09 00:14
Looks similar to either of these
#36291 #22397 #12544

**Comment by follower** [comment] 2021-09-03 18:02
Yeah, this is almost certainly a bug which is the result of the changes made to keyboard navigation of tree controls in https://github.com/godotengine/godot/pull/16947 which is discussed further in #36291.

I've added a suggestion in a comment in that for how someone could help move this issue forward, if someone would like to do so: https://github.com/godotengine/godot/issues/36291#issuecomment-912712659

**Comment by KoBeWi** [comment] 2022-01-03 11:25
Closing as duplicate of #12544

**Closed by KoBeWi** 2022-01-03 11:25 UTC
Labels: bug, topic:editor
