### ISSUE TITLE
Debug stepping becomes really slow when the scene contains a shader material wich uses the TIME uniform.

### ISSUE THREAD

**Issue by Gnumaru** [godotengine/godot#68232] opened 2022-11-03 20:14 UTC
### Godot version

4.0beta15

### System information

windows 10 x64, vulkan and opengl

### Issue description

While trying to step trough lines in the debugger in a scene that contains a shader material that uses the TIME built-in uniform, the debug steps become really slow.

### Steps to reproduce

Open attached project, play "main.tscn" and try to step through the breakpoints with F10 or F12

### Minimal reproduction project

[NewGameProjectG4B.zip](https://github.com/godotengine/godot/files/9932630/NewGameProjectG4B.zip)

**Comment by Gnumaru** [comment] 2022-11-03 20:15
Another slow debug stepping related bug was reported here:
https://github.com/godotengine/godot/issues/67696

**Comment by Zireael07** [comment] 2022-11-04 07:59
Same on Linux (my sky shader uses TIME)

**Comment by flotos** [comment] 2022-11-09 08:49
Same, it was slow to the point I thougt it was freezing. Removing my shader from the label I used totally fixed it.

**Comment by Gnumaru** [comment] 2022-11-17 14:29
still reproducible on beta 5

**Comment by clayjohn** [comment] 2023-01-26 19:00
Closing as duplicate of https://github.com/godotengine/godot/issues/68232

**Closed by clayjohn** 2023-01-26 19:00 UTC
Labels: bug, topic:editor, confirmed, topic:shaders, performance

**Comment by Zireael07** [comment] 2023-01-26 19:12
Yy, you closed this as duplicate of... itself?

**Comment by clayjohn** [comment] 2023-01-26 19:58
Whoops, I had both issues open at once. Should be https://github.com/godotengine/godot/issues/67696
