### ISSUE TITLE
AnimationTree editor crashes on change of AnimationTree node to edit

### ISSUE THREAD

**Issue by dpalais** [godotengine/godot#68042] opened 2022-10-30 01:32 UTC
### Godot version

4.0-git (11e1bac768349ae821647a582282458e83b8d72b)

### System information

Fedora 36

### Issue description

The editor crashes when the AnimationTree editor edits a new AnimationTree node after editing a different AnimationTree that has already been disposed.

### Steps to reproduce

1. Create or open a scene with an AnimationTree in it
2. Click on the AnimationTree to have the editor show the AnimationTree editor
3. Close the scene
4. Reopen the scene
5. If it hasn't crashed by this point, click on the AnimationTree node once again

[Backtrace.txt](https://github.com/godotengine/godot/files/9894896/Backtrace.txt)

### Minimal reproduction project

[AnimationTree editor crash.zip](https://github.com/godotengine/godot/files/9894897/AnimationTree.editor.crash.zip)

**Comment by TokageItLab** [comment] 2022-11-20 01:34
This is caused by #65196 and the problem areas are as follows:

**animation_tree_editor_plugin.cpp:**
```cpp
void AnimationTreeEditor::edit(AnimationTree *p_tree) {
	if (p_tree && !p_tree->is_connected("animation_player_changed", callable_mp(this, &AnimationTreeEditor::_animation_list_changed))) {
		p_tree->connect("animation_player_changed", callable_mp(this, &AnimationTreeEditor::_animation_list_changed));
	}

	if (tree == p_tree) {
		return;
	}

	if (tree && tree->is_connected("animation_player_changed", callable_mp(this, &AnimationTreeEditor::_animation_list_changed))) {
		tree->disconnect("animation_player_changed", callable_mp(this, &AnimationTreeEditor::_animation_list_changed));
	}

```

This method disconnects the old tree signal when a new tree is assigned to avoid unnecessary updates.

```cpp
tree->is_connected("animation_player_changed", callable_mp(this, &AnimationTreeEditor::_animation_list_changed))
```

But this line seems that the retrieval of signals from ClassDB is failing. Sometimes we get an error `Nonexistent signal: animation_player_changed.`, else it crashes.

I am not sure why this is happening. Can someone please give me some wisdom on this?

**Comment by TokageItLab** [comment] 2022-11-20 03:10
@fire says it is probably a cyclic references problem. We will visit this again later. We must solve this problem at least by RC.

**Closed** 2022-11-20 16:49 UTC
Labels: bug, topic:editor, crash, regression, topic:animation
