### ISSUE TITLE
AudioStreamPlayer2D and WAV with internal loop info

### ISSUE THREAD

**Issue by wagnerfs** [godotengine/godot#26566] opened 2019-03-04 06:29 UTC
**Godot version:**
3.1 beta 10

**OS/device including version:**
Windows 10 x64

**Issue description:**
Repeatedly playing AudioStreamPlayer2Ds with a WAV file that has loop info either causes weird noises or plays as if it started at the end before actually play from the beginning.
Using AudioStreamPlayer2D.seek before playing makes the sound play from start, quickly stopping and quickly restarting like it was a small audio hickup.

**Steps to reproduce:**
Any AudioStreamPlayer2D with this WAV file imported with loop on
![image](https://user-images.githubusercontent.com/106078/53714233-54945080-3e2c-11e9-9225-9316247e66b4.png)

The audio file:
[Charging.zip](https://github.com/godotengine/godot/files/2924527/Charging.zip)

**Minimal reproduction project:**
[Bug.zip](https://github.com/godotengine/godot/files/2924543/Bug.zip)
Press Enter, wait for the sound to enter loop stage, press Enter again to stop and repeat, sometimes it happens sometimes it doesn't.

**Comment by girng** [comment] 2019-03-04 06:30
I've heard of this before, and that disabling trim can help. Does it?

**Comment by wagnerfs** [comment] 2019-03-04 06:55
> 
> 
> I've heard that disabling trim can help. But still, I don't think it should be doing that

Nope, reimported with Trim disabled, Normalize disabled, same isue.

**Comment by wagnerfs** [comment] 2019-03-04 16:33
Okay, I found a workaround for this incase someone else comes into the same issue.

Before playing the audio, seek it to 0.0 and then play it starting from -1.0
`$AudioStreamPlayer2D.seek(0.0)
$AudioStreamPlayer2D.play(-1.0)`

Interally as far as I got it by reading the source code, when you play it from a value bellow 0.0, it'll skip some stuff on _mix_audio method, so seeking before playing it at -1 will make sure things are alright internally so it can skip that small code block and play normally.
Playing at -1 before seeking won't actually play the audio at all.

**Comment by tom-jk** [comment] 2020-07-20 14:55
Can reproduce on 3.2.2.stable on linux mint 18.3, kernel 4.15.0-55-generic.
The effect occurs randomly but on average about one in every two/three repeats.
Can confirm suggested workaround does mitigate issue.
Disabling trim does not make a difference.

For convenience here is a sample of the output audio, alternating between correct and incorrect:
**(potential loudness warning)** [26566_ogg.zip](https://github.com/godotengine/godot/files/4948424/26566_ogg.zip)

**Comment by Calinou** [comment] 2020-07-25 12:24
Duplicate of #22016.

**Closed by Calinou** 2020-07-25 12:24 UTC
Labels: bug, confirmed, topic:audio
