### ISSUE TITLE
Running a gdscript in command line a window opens and closes in milliseconds.

### ISSUE THREAD

**Issue by icnikerazah** [godotengine/godot#13366] opened 2017-11-28 13:44 UTC
MacOs Sierra, Custom Build

**Issue description:**
When i run a script in terminal (godot -s sayhello.gd) a pop up window appears with godot logo.

**Steps to reproduce:**
Same Prodecure in command line tutorial in docs.
<img width="348" alt="ekran resmi 2017-11-28 16 38 01" src="https://user-images.githubusercontent.com/33985414/33322517-9fd6814a-d45a-11e7-8525-3dceb2538c8a.png">

**Comment by akien-mga** [comment] 2017-11-28 13:52
That's normal, all Godot commands will spawn a Godot window, unless you use the server/headless binary.

**Comment by icnikerazah** [comment] 2017-11-28 14:01
That's is not normal, it's annoying and useless.

**Comment by akien-mga** [comment] 2017-11-28 14:12
Well "normal" means "that's the way it's designed". You are free to think that it's a bad design, but that doesn't make it anormal :)

Anyway, duplicate of #2081.

**Closed by akien-mga** 2017-11-28 14:12 UTC
