### ISSUE TITLE
Namespace in singleton give "Script does not inherit a Node"

### ISSUE THREAD

**Issue by git2013vb** [godotengine/godot#48266] opened 2021-04-28 12:30 UTC
**Godot version:**

3.3  mono stable

**OS/device including version:**

Debian 10

**Issue description:**

If I add a namespace in my singleton CS script I have this error when i run the scene

**Steps to reproduce:**
Run a scene with a script attached using a namespace into script

**Minimal reproduction project:**

NA I think is easy to check - any mono project you have is good to reproduce it - but if you need I can prepare one from  scratch

**Comment by Calinou** [comment] 2021-04-28 13:21
Duplicate of https://github.com/godotengine/godot/issues/36787.

**Closed by Calinou** 2021-04-28 13:21 UTC
