### ISSUE TITLE
Editor crashes when selecting AnimatedSprite while on collision shape layer

### ISSUE THREAD

**Issue by denvermullets** [godotengine/godot#72836] opened 2023-02-07 14:20 UTC
### Godot version

v4.0.beta17.official [c40020513]

### System information

MacOS Ventura 13.2, 2.4ghz intel i9, amd radeon 5500m 8gb

### Issue description

i was following along the tutorial 'your first 2d game' and after adding sprites to the AnimationSprite2d layer i clicked on the CollisionShape2d layer and Godot hard crashed. 

### Steps to reproduce

have animation panel up from the AnimatedSprite2d layer and then click on CollisionShape2d layer in the scene list. then click on one of the animations and godot will crash.

### Minimal reproduction project

here's a branch of the project as is: https://github.com/denvermullets/demo-gd-redux/tree/bug/crash-branch

includes screenshot of app right before crash and the crash log and a video

**Comment by YuriSizov** [comment] 2023-03-09 18:26
Thanks for the report! This was a duplicate of https://github.com/godotengine/godot/issues/72763, fixed by https://github.com/godotengine/godot/pull/72783.

**Closed by YuriSizov** 2023-03-09 18:26 UTC
Labels: bug, topic:editor, crash, topic:animation
