### ISSUE TITLE
godot osx font too small [字体太小了]

### ISSUE THREAD

**Issue by LingJiJian** [godotengine/godot#2337] opened 2015-08-05 15:17 UTC
i create godot with my macbook retina , but the font too small ,how can i setting up?

**Comment by FEDE0D** [comment] 2015-08-06 01:28
This is for issues and bugs only.
You should check the Facebook group https://www.facebook.com/groups/godotengine/
or the forum http://www.godotengine.org/forum/.
But I think what you want is in the wiki: https://github.com/okamstudio/godot/wiki/editor_font

**Comment by Zeta-Balam** [comment] 2015-08-13 17:51
I have the same issue, also the icons are so small, and when I change the font size, som elements from the ui does not fit well

**Comment by reduz** [comment] 2015-08-13 17:57
it is actually an issue, I don't understand why for some people this
happens.

I wish i had a retina display so Godot could support HiDPI but i don't.
Things that happen when some users have more purchasing possibilities than
the developer :)

Will eventually ask for donations so I can purchase the relevant hardware
and support it.

Cheers!

Juan

**Comment by reduz** [comment] 2015-09-04 14:50
osx is different because it supports specifying compatibility. when you run
the editor inside the package it should work though

**Comment by franciscotufro** [comment] 2015-10-13 05:38
@reduz I can help with this since my macbook is Retina. Let me know where should I look and I can test and send a patch.

**Comment by akien-mga** [comment] 2015-11-10 14:55
Duplicate of #20 I guess.

**Closed by akien-mga** 2015-11-10 14:55 UTC
Labels: archived
