### ISSUE TITLE
Godot 4 windows switching

### ISSUE THREAD

**Issue by GorEldeen** [godotengine/godot#72366] opened 2023-01-30 10:07 UTC
### Godot version

4.0

### System information

Linux mint, GLES3, Nvidia quadro 2000m

### Issue description

so sometimes (Randomly) Godot 4 starts switching between windows inside the engine itself, Some simple tasks like "Create script" as you can see here, It keeps doing that and i have to end the process from my task manager

Sometimes it happens when i add node child

### Steps to reproduce

1. Go to script tab
2. Make a new script

### Minimal reproduction project

https://user-images.githubusercontent.com/112822849/215447764-364a5ee3-304f-49b8-b36c-83e0d8e82f75.mp4

**Comment by ilovespicynoodles** [comment] 2023-01-30 11:06
Same issue here. Using the new Beta 15. Same happens with Editor Settings. Project Settings works fine though.
When it happens, i can't even switch to my browser or anything else and use for example the url bar. Can't use my terminal either to kill the process. it won't stop switching back to the flickering godot window.

I tried running godot with the --verbose flag but there are no logs of when it does this.

**Comment by Calinou** [comment] 2023-01-30 13:03
Duplicate of https://github.com/godotengine/godot/issues/72187.

**Closed by Calinou** 2023-01-30 13:03 UTC
Labels: bug, topic:editor
