### ISSUE TITLE
NVIDIA OpenGL driver - Godot crash

### ISSUE THREAD

**Issue by jgodfrey** [godotengine/godot#35285] opened 2020-01-18 15:21 UTC
**Godot version:**
3.2 rc1

**OS/device including version:**
WIndows 10 Pro 1909

**Issue description:**
I've been working on a Godot project using 3.1.2 stable for quite some time now. I just grabbed the 3.2 rc1 build and attempted to open a copy of my project. The project manager opens fine, but when I attempt to open my 3.1.2 project, I get the following NVIDIA driver error:

![image](https://user-images.githubusercontent.com/1459347/72665955-0bf96d80-39d3-11ea-912e-89157dec403a.png)

Once the error dialog is closed, neither the editor or the project manager are left open.

My system details are as follows:

Sony VAIO laptop
NVIDIA GeForce GT 330M
Driver Version 21.21.13.4201

As far as I know, this is the most up-to-date driver available for this (dated) system.

**Steps to reproduce:**
Open working Godot 3.1.2 project in Godot 3.2 rc1

**Minimal reproduction project:**

**Comment by NieznanywInternetach** [comment] 2020-01-18 15:45
It may be related with #35242 
Can you try this version? It's compiled by @akien-mga 
https://downloads.tuxfamily.org/godotengine/3.2/tmp-test/godot.3.2.rc1.796d35d-reverted.exe.zip

**Comment by jgodfrey** [comment] 2020-01-18 15:57
Thanks for the input and the link. I can confirm that the above-linked version works on my system. Though, reading through the associated ticket, it doesn't sound like there's an official fix available - at least not yet...

**Comment by Zireael07** [comment] 2020-01-18 16:10
Not yet, but they know where the problem is, hopefully a fix will come soon(ish)

**Comment by Calinou** [comment] 2020-01-18 16:11
Duplicate of #35285. (Your system has a different graphics card, but the underlying cause is the same.)

**Closed by Calinou** 2020-01-18 16:11 UTC
