### ISSUE TITLE
Unhelpful Error Exporting From Commandline Without Build Templates

### ISSUE THREAD

**Issue by AsherGlick** [godotengine/godot#34882] opened 2020-01-07 05:55 UTC
**Godot version:**
3.1.2 stable

**OS/device including version:**
Ubuntu Linux 18.04

**Issue description:**
When exporting from the command line without proper build templates downloaded a generic os file error is displayed without any indication that it is related to the build templates.

**Steps to reproduce:**
Download a version of godot onto a machine that does not have the build templates for that version, or delete the build templates for that version.
Then attempt to run a command line export such as:
`./Godot_v3.1.2-stable_x11.64 --export "Linux/X11" output.x86_64`

see the printout of:
```
Godot Engine v3.1.2.stable.official - https://godotengine.org
OpenGL ES 3.0 Renderer: GeForce GTX 1070 with Max-Q Design/PCIe/SSE2
ERROR: copy: Failed to open 
   At: core/os/dir_access.cpp:300.
ERROR: _fs_changed: Project export failed with error code 12.
   At: editor/editor_node.cpp:495.
```

**Minimal reproduction project:**

**Comment by akien-mga** [comment] 2020-01-07 10:06
Duplicate of #18470.

**Closed by akien-mga** 2020-01-07 10:06 UTC
