### ISSUE TITLE
Clicking below the last line (if not empty) in the code editor logs an error

### ISSUE THREAD

**Issue by adamscoble** [godotengine/godot#69313] opened 2022-11-28 21:27 UTC
### Godot version

4.0.beta6

### System information

Windows 10

### Issue description

If you have some code in a script and the last line is **not** an empty line, clicking below that line will log this error on each click:

> GDScript parser bug: Trying to advance past the end of stream.
> scene/gui/text_edit.cpp:4911 - Index p_column = 18 is out of bounds (text[carets[p_caret].selection.selecting_line].length() + 1 = 18).

### Steps to reproduce

1. Create or open a script.
2. Remove any empty (just new line characters) trailing lines.
3. Click below the last line.

### Minimal reproduction project

N/A

**Comment by Rindbee** [comment] 2022-11-29 10:33
A duplicate of #69011 fixed by #69054.

**Closed** 2022-11-29 10:48 UTC
