### ISSUE TITLE
Godot RC 3 crashes when trying to clear a Curve in a Path2D

### ISSUE THREAD

**Issue by unichat** [godotengine/godot#16130] opened 2018-01-28 12:29 UTC
**Godot version:** Godot 3 RC3

**OS/device including version:** Manjaro Linux XFCE 12.1.2

**Issue description:**

When clearing a curve in a Path2D, Godot crashes with the message:
`handle_crash: Program crashed with signal 11
Dumping the backtrace. Please include this when reporting the bug on https://github.com/godotengine/godot/issues
[1] /usr/lib/libc.so.6(+0x348e0) [0x7f7dab64e8e0] (??:0)
[2] /home/linus/Downloads/Godot_v3.0-rc3_x11.64() [0x14ca710] (??:?)
[3] /home/linus/Downloads/Godot_v3.0-rc3_x11.64() [0x12d07dc] (??:?)
[4] /home/linus/Downloads/Godot_v3.0-rc3_x11.64() [0xd31a20] (??:?)
[5] /home/linus/Downloads/Godot_v3.0-rc3_x11.64() [0x19971c4] (??:?)
[6] /home/linus/Downloads/Godot_v3.0-rc3_x11.64() [0xe70459] (??:?)
[7] /home/linus/Downloads/Godot_v3.0-rc3_x11.64() [0xe76016] (??:?)
[8] /home/linus/Downloads/Godot_v3.0-rc3_x11.64() [0x4c39af] (??:0)
[9] /home/linus/Downloads/Godot_v3.0-rc3_x11.64() [0x452dad] (??:0)
[10] /usr/lib/libc.so.6(__libc_start_main+0xea) [0x7f7dab63af4a] (??:0)
[11] /home/linus/Downloads/Godot_v3.0-rc3_x11.64() [0x45e5ff] (??:0)
-- END OF BACKTRACE --
`
The expected behaviour would be to not crash, and clear the path :)

**Steps to reproduce:**
In the example project, click on CarPath -> Curve -> Clear

**Minimal reproduction project:**

[test.zip](https://github.com/godotengine/godot/files/1671056/test.zip)

**Comment by Noshyaar** [comment] 2018-01-28 12:41
Already fixed by #15994 (Duplicate of #15989). Thanks for testing & reporting.

**Closed by Noshyaar** 2018-01-28 12:41 UTC
