### ISSUE TITLE
Types/keywords are highlighted in $ operator node path

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#22836] opened 2018-10-07 17:59 UTC
This never really bothered me, but I thought that it's not unreasonable issue, so well, reporting it.
![image](https://user-images.githubusercontent.com/2223172/46584961-887c6d00-ca6a-11e8-8a09-15344542db89.png)
![image](https://user-images.githubusercontent.com/2223172/46584967-95995c00-ca6a-11e8-800f-28c964b1222b.png)
Perfectly, anything that is after $ operator should be considered a constant string and highlighted with appropriate color, preferably the same as $ operator or standard text color. Right now the node paths are needlessly colorful and it might be confusing for some people.

Here's a mockup for above code fix, with both color variants:
![image](https://user-images.githubusercontent.com/2223172/46585022-5fa8a780-ca6b-11e8-90ea-50409840410b.png)
![image](https://user-images.githubusercontent.com/2223172/46585024-66cfb580-ca6b-11e8-9fa3-850ddfa6bc7d.png)

**Comment by CowThing** [comment] 2018-10-07 18:31
I had an issue for this before #11554 and it was supposed to be fixed with #18183

I thought it was fixed for a bit, but now testing on 8068d02 it seems to be broken.

**Comment by akien-mga** [comment] 2018-10-07 18:33
CC @Paulb23

**Comment by Paulb23** [comment] 2018-10-13 12:17
I'm not quite too sure what you are asking here, as it currently looks like your last screenshot. 

What syntax highlighter do you have selected? As it will only work with the `GDScript` syntax highlighter, not the `Standard` one. You can change it under `edit --> Syntax Highlighter`

What Godot version / commit are you running?

**Comment by CowThing** [comment] 2018-10-13 15:10
Just checked, the syntax highlighter was set to Standard even though I was editing a GDScript file. And everything else was being highlighted exactly the same as a GDScript file is so I didn't realize it wasn't on the GDScript syntax.

So I guess the issue is that Standard syntax highlighting is being selected by default for GDScript files. And that Standard highlighting has the same highlighting as GDScript except for the $NodePath, in which case what is the reason for Standard highlighting?

**Comment by Paulb23** [comment] 2018-10-13 16:00
At the moment the `GDScript` highlighter also has function declaration and types when using typed GDScript. 

There's now a separation between highlighter and script, so when more highlighters are added you can change the highlighting to match the file you are editing. As the script editor no longer restricts what can be opened (So long as its `utf_8`).

On a new instance of Godot the `Standard` highlighter is currently used by `TextFiles` and the GDScript highlighter is selected for `GDScript`, however see #22268.

**Closed** 2019-04-21 11:01 UTC
Labels: bug, topic:editor, usability
