### ISSUE TITLE
Cannot see collision shapes of areas/bodies instanced in other scenes in the editor 

### ISSUE THREAD

**Issue by Bauxitedev** [godotengine/godot#20059] opened 2018-07-09 09:47 UTC
**Godot version:**
3.0.4 Mono

**OS/device including version:**

**Issue description:**
If you have a scene containing an area, rigid body, static body or kinematic body as the root containing a collision shape, instancing this scene into another scene will no longer show the collision shape of the body.
(A workaround is to turn "editable children" on, but I think this should work out of the box, and that brings other issues with it)

**Steps to reproduce:**
1. Create a StaticBody scene, add a capsule shape and Sprite3D with the Godot icon (for clarity). You'll get something like this.
![1](https://user-images.githubusercontent.com/31383123/42443416-b498ce04-836d-11e8-85bb-fd9cf0036d71.png)
Notice how the capsule shape is clearly visible.
2. Now instance this scene into another scene. Notice how the capsule shape is now gone.
![2](https://user-images.githubusercontent.com/31383123/42443456-cda36f9e-836d-11e8-9ba4-2e84471c00fe.png)

**Comment by Calinou** [comment] 2020-06-07 20:45
I can't reproduce this in 3.2.2beta4, closing. (The shape will appear in gray instead of blue when it's from an instanced scene, but it's still visible.)

**Closed by Calinou** 2020-06-07 20:45 UTC
Labels: bug, topic:editor
