### ISSUE TITLE
Screen Space Reflections disappear from any moving object in 4.3

### ISSUE THREAD

**Issue by jamesdkay** [godotengine/godot#97998] opened 2024-10-09 02:19 UTC
### Tested versions

- Reproducible in v4.3.stable.mono.official [77dcf97d8]
- Not reproducible v4.2.stable.mono.official [46dc27791]

### System information

Godot v4.3.stable.mono - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1660 Ti (NVIDIA; 31.0.15.1640) - AMD Ryzen 7 4800H with Radeon Graphics (16 Threads)

### Issue description

Any time an object is moving it loses its screen space reflections until it stops moving. This is new in 4.3 and did not happen in 4.2. Issue occurs both in the editor and in game.

Compare a moving object in 4.2:

https://github.com/user-attachments/assets/043bdf42-2276-4982-ac15-0c5caede0936

...with the same scene in 4.3:

https://github.com/user-attachments/assets/9800e685-4ab4-4472-adee-4d007214afae

This happens both in the editor and in game.

### Steps to reproduce

Create a scene, add a few objects, add a WorldEnvironment and enable SSR. Move on object and the reflection effect disappears from the object when it is moving.

### Minimal reproduction project (MRP)

Simply move any object that you can see screen space reflections on and watch them disappear.

[ssr.disappears.zip](https://github.com/user-attachments/files/17301180/ssr.disappears.zip)

**Comment by tetrapod00** [comment] 2024-10-09 02:25
Probably a duplicate of https://github.com/godotengine/godot/issues/95814, which was fixed in https://github.com/godotengine/godot/pull/95438.

Try one of the 4.4dev versions and see if you can reproduce the problem?

**Comment by jamesdkay** [comment] 2024-10-09 04:14
Oops, sorry for the duplicate. Somehow I missed the other one.

**Closed** 2024-10-09 04:14 UTC

**Comment by tetrapod00** [comment] 2024-10-09 04:50
It's easy to miss when the issue was already closed. Thank you for reporting, anyway!
