### ISSUE TITLE
Shadows and environment not working in glcompactible renderer

### ISSUE THREAD

**Issue by TomerconDevelopers** [godotengine/godot#72358] opened 2023-01-30 06:02 UTC
### Godot version

4.0 beta 16

### System information

system: windows 10, ryzen 6 3600, rx 590, 16gb RAM, android device: OPPO A57, CPH2387, android version 12

### Issue description

Shadow and world environment settings are not working properly in glCompactible renderer both in editer and exported game.
Actual scene in modile renderer:
![image](https://user-images.githubusercontent.com/62302722/215398724-8b8d5896-d45d-44a9-9e2e-5762ab0fba75.png)
Scene in glcompactible mode:
![image](https://user-images.githubusercontent.com/62302722/215398838-2971deb5-6e17-4a0f-afff-6278d530182a.png)
I also tested by creating fresh project as in glcompact mode, still same result

### Steps to reproduce

create new project -> choose glcompact renderer-> add meshinstance plane and a cube, add directional light

### Minimal reproduction project

create new project -> choose glcompact renderer-> add meshinstance plane and a cube, add directional light

**Comment by clayjohn** [comment] 2023-01-30 06:08
Duplicate of https://github.com/godotengine/godot/issues/67866

Shadows haven't been reimplemented in the gl_compatibility renderer yet

**Closed by clayjohn** 2023-01-30 06:08 UTC
