### ISSUE TITLE
Possible Android Performance Problems

### ISSUE THREAD

**Issue by hjegor** [godotengine/godot#19822] opened 2018-06-28 11:40 UTC
**Godot version:**

used 2.1.5-rc1 (but overall 2.1)

**OS/device including version:**

iOS (iPhone SE)
Android (OnePlus One, Samsung Galaxy S7) 

**Issue description:**

As I was developing my mobile game, I experienced some performance differences between my Android and iOS Release build. So, I cloned this bunnymark repo (https://github.com/curly-brace/godot-bunnies) and played around a bit with the low level **VisualServer** benchmark which resulted in the following:

Android (OnePlus One) could handle **1.000** bunnies @ 12 - 15fps.
Android (Galaxy S7) could handle **5.000** bunnies @ 13-15fps.

For comparison:
iOS (iPhone SE) could handle **10.000** bunnies @ 13 - 14fps.

However, I never realized bad performance on my OnePlus One while playing other games, so I tried another bunnymark using Unity this time (https://github.com/eray-z/Game-Engine-Benchmarks) and it could handle **1.000** bunnies easily @ 60fps (even **7.000** bunnies @ 13-15fps).

**Steps to reproduce:**

Downloading Godot 2.1.5-RC1 and the corresponding Templates, cloning https://github.com/curly-brace/godot-bunnies and exporting release builds for Android and iOS.

**Minimal reproduction project:**

**Comment by RKelln** [comment] 2018-07-15 19:38
I'm seeing Android performance problems as well on Godot 3.0.5. My app runs at 60+ fps (often 100+) on Linux but 1-3 fps on Android.  After disabling various items I discovered the culprit seems to be `draw_circle()` (I was using about 40 of these). Disabling it entirely or using `draw_rect()` instead helped keep fps at 60 (seems to be locked there). Multiple `draw_line()` also reduced performance to about 20 fps while `draw_polyline()` was fine at 60 fps. Perhaps all the draw functions need testing or there is something inherit on Android that should be avoided?

**Comment by Calinou** [comment] 2020-04-16 20:48
Duplicate of #24671.

**Closed by Calinou** 2020-04-16 20:48 UTC
Labels: topic:porting, topic:rendering
