### ISSUE TITLE
CanvasLayer not remaining static

### ISSUE THREAD

**Issue by Ackspyre** [godotengine/godot#59802] opened 2022-04-01 19:40 UTC
### Godot version

v4.0.alpha4.official [f47097973]

### System information

Windows 10, Microsoft Surface 6

### Issue description

CanvasLayer does not stay with the screen. I first thought I was doing something wrong, but I tried it in Godot3 and it didn't reproduce. While reproducing it I found that the label node follows the screen while the panel moves off the screen as the camera/rigidbody falls.

More System info:
![image](https://user-images.githubusercontent.com/68719420/161330645-5d7a9973-20b0-44c8-920b-3e917b6c9658.png)

### Steps to reproduce

1)Open new project
2)Add a Canvas Layer and both a Panel and Label as a children
3)Add a RigidDynamicBody2D 
4)Add a Sprite and Camera(set as current) as children of the RigidDynamicBody2D
5)Run the program

The text stays with the screen, but the Panel does not when the RigidDynamicBody2D begins to fall with the camera.

![image](https://user-images.githubusercontent.com/68719420/161330372-7c48b959-ad44-41d3-afcf-ffd9b2c69941.png)

### Minimal reproduction project

[IssueReport.zip](https://github.com/godotengine/godot/files/8400477/IssueReport.zip)

**Comment by Sauermann** [comment] 2022-04-01 20:27
I am unable to replicate this issue. The MRP works for me as expected.

**Comment by arkology** [comment] 2022-04-01 20:46
Finally, someone faced the same bug!
Related/duplicate – https://github.com/godotengine/godot/issues/58314

Actually I think the problem is with Intel (or maybe any) iGPU - I reproduced it in 2 PC with iGPU.

**Comment by Ackspyre** [comment] 2022-04-01 21:33
Verified this happens in both Vulcan Clustered and Vulcan Mobile.
I've added a .gif showing what happens. The framerate wasn't great so its only a few frames but hopefully it shows what happens.
![Animation](https://user-images.githubusercontent.com/68719420/161343417-8704025c-1cb4-4a19-9d1c-0b57b47051cd.gif)

Glad I provide more info to @arkology 's issue. One thing to note that is different with my case is that the canvasLayer is not a child of the camera, but rather of the main scene's node.

**Comment by Ackspyre** [comment] 2022-04-03 04:12
Another thing to note: My surface auto-updated to windows 11. The issue no longer persists, even when opening the exact same godot project.

**Comment by akien-mga** [comment] 2022-04-03 07:49
@arkology are you able to reproduce @Ackspyre's issue too on your Intel iGPUs with the project in the OP? If so I guess we could close this one as duplicate of #58314 to consolidate things there.

**Comment by arkology** [comment] 2022-04-03 09:29
@akien-mga yes, I see the same behaviour with the project in the OP. This is actually the same bug.

**Comment by Ackspyre** [comment] 2022-04-03 09:53
> @arkology are you able to reproduce @Ackspyre's issue too on your Intel iGPUs with the project in the OP? If so I guess we could close this one as duplicate of #58314 to consolidate things there.

Yes I saw the same issues as Arkology. I can't reproduce now that my Surface decided (on its own mind you) to update to windows 11 last night. Not sure if my driver version changed or just the OS, but the issue is fixed for me. One other thing we could document if we haven't is Arkology's display driver version and see if running windows updates fixes the symptoms.

**Comment by akien-mga** [comment] 2022-04-03 10:28
Duplicate of #58314

**Closed by akien-mga** 2022-04-03 10:28 UTC
Labels: bug, topic:core, regression, topic:2d
