### ISSUE TITLE
Cannot change type of a node with a custom script to a different custom script

### ISSUE THREAD

**Issue by derkork** [godotengine/godot#86701] opened 2024-01-02 06:29 UTC
### Tested versions

v4.2.stable.mono.official [46dc27791]

### System information

Godot v4.2.stable.mono - Windows 10.0.22621 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 4080 (NVIDIA; 31.0.15.3758) - AMD Ryzen 9 7950X3D 16-Core Processor (32 Threads)

### Issue description

I have two custom node scripts that extend Node2D. 

```gdscript
class_name MyCustomNode2D
extends Node2D
```

```gdscript
class_name MyOtherCustomNode2D
extends Node2D
```

If I create a new Node2D of `MyCustomNode2D` and then try to change its type to `MyOtherCustomNode2D` through the _Change type..._ operation, the node keeps its old type (`MyCustomNode2D`) attached.

### Steps to reproduce

- Open the `example.tscn` in the attached project.
- Right-click on the `MyCustomNode2D` node in the scene.
- Select _Change Type..._ 
- In the opening popup select `MyOtherCustomNode2D`
- Press _Change_

After this I would expect the attached script of the node to change to `my_other_custom_node2d.gd` but it stays as `my_custom_node2d.gd`, so the _Change Type..._ operation essentially did nothing.

### Minimal reproduction project (MRP)

[change_type_reproducer.zip](https://github.com/godotengine/godot/files/13807602/change_type_reproducer.zip)

**Comment by AThousandShips** [comment] 2024-01-02 10:51
Duplicate of https://github.com/godotengine/godot/issues/77444

**Closed by AThousandShips** 2024-01-02 10:51 UTC
Labels: discussion, topic:editor
