### ISSUE TITLE
GLES2: BakedLightmap hides non-baked meshes on Android

### ISSUE THREAD

**Issue by Janders1800** [godotengine/godot#32535] opened 2019-10-03 23:05 UTC
**Godot version:**
3.1 stable

**OS/device including version:**
Android 8.1

**Issue description:**
Wen using bakedlightmap on a scene the non-baked meshes disappear wen running on Android

**Steps to reproduce:**
Add a bakedlightmap node
Bake lights
Add a meshinstance
Run on Android

**Minimal reproduction project:**
[LightMaps.zip](https://github.com/godotengine/godot/files/3688377/LightMaps.zip)

Posible related: #24550

**Comment by clayjohn** [comment] 2019-10-03 23:08
Duplicate of #24550. We should track the issue there. Thanks for the minimal reproduction project though!! :)

**Closed by clayjohn** 2019-10-03 23:08 UTC
