### ISSUE TITLE
AnimationPlayer problem with dock.

### ISSUE THREAD

**Issue by Torguen** [godotengine/godot#47820] opened 2021-04-12 07:54 UTC
**Godot version:**

v3.3.rc8.mono.official

**OS/device including version:**

win10 64

**Issue description:**

Observe the gif and the animationPlayer panel with the animation, the panel is shown, after you run, the animation panel is hidden, stop the execution then you select the animationPlayer node but the animation panel is not shown.
Presumably this happens with all nodes displaying information on that panel.

![behavior1](https://user-images.githubusercontent.com/19652075/114360061-e840bb00-9b74-11eb-80a6-936fe995c391.gif)

**Steps to reproduce:**
Look at the gif

**Minimal reproduction project:**

**Comment by akien-mga** [comment] 2021-04-12 08:06
Judging by the GIF this might be specific to the Editable Children feature which changed in 3.3. CC @hilfazer @KoBeWi

**Comment by KoBeWi** [comment] 2021-04-12 15:14
To me it looks more like #46935 (which is weird, because it should've been fixed)
It's not related to editable children.

**Comment by AtomaFajrovulpo** [comment] 2021-07-10 17:26
Duplicate of #33528

**Comment by Calinou** [comment] 2021-07-10 17:45
Closing per @AtomaFajrovulpo's comment.

**Closed by Calinou** 2021-07-10 17:45 UTC
Labels: bug, regression, topic:editor
