### ISSUE TITLE
Global uniforms - sampler2D entries lost on restart...

### ISSUE THREAD

**Issue by vitawrap** [godotengine/godot#77146] opened 2023-05-17 00:36 UTC
### Godot version

4.0.2.stable

### System information

Windows 10, Intel Core i7-4790, Mobile renderer, NVIDIA GeForce GTX 980

### Issue description

Values like floats work and are "remembered" on startup in `Project Settings -> Shader Globals`. However, it seems any kind of sampler2D is not. Next startup will show that the list is shy of whatever sampler2D was added.

### Steps to reproduce

- Create a new Godot project with the `Mobile` renderer.
- Go to Project Settings and Shader Globals
- Add a new entry of type sampler2D
    - The texture type does not seem to matter, that and whether it's saved or not.
- Close the project and reopen
- *The entry is gone*

### Minimal reproduction project

N/A

**Comment by vitawrap** [comment] 2023-05-17 00:48
Previous search for similar issues yielded nothing, and now I manually find #77021 ...😅

**Comment by akien-mga** [comment] 2023-05-17 09:40
Seems like a duplicate of #77021 indeed.

**Closed by akien-mga** 2023-05-17 09:40 UTC
