### ISSUE TITLE
Control Anchors Preset aren't inherited well from child scenes

### ISSUE THREAD

**Issue by guyguy2001** [godotengine/godot#74360] opened 2023-03-04 14:35 UTC
### Godot version

v4.0.stable.official [92bee43ad]

### System information

Windows 10

### Issue description

I have 2 very similar issues, that I believe are the same

### 1.
default value for anchor preset is revertable to a different value
**Actual**
When creating a new Control scene, the default value from the Anchors Preset is `Full Rect`, but the editor allows me to revert it:
![image](https://user-images.githubusercontent.com/6932278/222907963-c370f488-e690-4b92-a70f-7c3d8a89e45c.png)

**Expected**
The default value shouldn't be revertable

### 2.
when putting a child scene in a parent scene, and defining the Anchors Preset in the child scene, you can revert it in the parent scene to a different value
Child:
![image](https://user-images.githubusercontent.com/6932278/222908040-3fd12776-3611-42fa-b319-e8eec29c4b77.png)
Parent:
![image](https://user-images.githubusercontent.com/6932278/222908067-4e524101-0c8d-4e51-b238-216ea1d4910e.png)

This seems to affect the "Layout Mode" option as well

### Steps to reproduce

1.
Create a UI scene called "child" with just a control
in the "Layout" panel, the "Anchors Preset" option will be revertable.

2.
Create a UI scene called "main" and put `child` inside of it.
Change the value of the "Anchors Preset" of `child` inside of `child.tscn`.
Go to the instance of `child` in `main.tsn`, and try to revert the 'Anchors Preset' value.

### Minimal reproduction project

https://github.com/guyguy2001/godot-4-ui-repro

**Comment by guyguy2001** [comment] 2023-03-04 14:43
### Before reverting `child` in the parent scene:
![image](https://user-images.githubusercontent.com/6932278/222909144-9df68c69-542d-479f-a99b-549e25daf2bc.png)

```tscn
[gd_scene load_steps=2 format=3 uid="uid://c8vc2d3gfoyyg"]

[ext_resource type="PackedScene" uid="uid://dbi30w6hxoy0n" path="res://child.tscn" id="1_sa3w7"]

[node name="Main" type="Control"]
layout_mode = 3
anchors_preset = 0

[node name="Child" parent="." instance=ExtResource("1_sa3w7")]
layout_mode = 1
```

### After reverting:
![image](https://user-images.githubusercontent.com/6932278/222909247-7b9a3f8e-ec74-433f-9b3f-1e2561dd5a8f.png)
```tscn
[gd_scene load_steps=2 format=3 uid="uid://c8vc2d3gfoyyg"]

[ext_resource type="PackedScene" uid="uid://dbi30w6hxoy0n" path="res://child.tscn" id="1_sa3w7"]

[node name="Main" type="Control"]
layout_mode = 3
anchors_preset = 0

[node name="Child" parent="." instance=ExtResource("1_sa3w7")]
layout_mode = 1
anchors_preset = 0
anchor_left = 0.0
anchor_right = 0.0
grow_horizontal = 1
```

**Comment by YuriSizov** [comment] 2023-03-04 19:29
Duplicate of https://github.com/godotengine/godot/issues/69226

**Closed by YuriSizov** 2023-03-04 19:29 UTC
