### ISSUE TITLE
Android Vibrate is used without checking VIBRATE permission

### ISSUE THREAD

**Issue by zero2000** [godotengine/godot#31670] opened 2019-08-25 23:58 UTC
**Godot version:**
v3.1.2.devel.custom_build

**OS/device including version:**
OS: Linux mint 19.2
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              4
On-line CPU(s) list: 0-3
Thread(s) per core:  2
Core(s) per socket:  2
Socket(s):           1
NUMA node(s):        1
Vendor ID:           AuthenticAMD
CPU family:          21
Model:               101
Model name:          AMD A12-9720P RADEON R7, 12 COMPUTE CORES 4C+8G
Stepping:            1
CPU MHz:             1675.579
CPU max MHz:         2700,0000
CPU min MHz:         1400,0000
BogoMIPS:            5389.28
Virtualization:      AMD-V
L1d cache:           32K
L1i cache:           96K
L2 cache:            1024K
NUMA node0 CPU(s):   0-3

**Issue description:**
Hello, I want to report this error since before I could create my tamplate both release and debug for Android, but after adding a new module, I failed, then I removed it and recompiled it and then it no longer generates, apart. also when I solve that, I generate the release and I wanted to upload it to the app store and now tell me that it is not compatible with 64bits which compiles for arm64v8 and nothing, I get that no. then update godot del git and now when I pass the ./gradlew build and I get this,

<?xml version="1.0" encoding="UTF-8"?>
<issues format="4" by="lint 3.2.1">

    <issue
        id="MissingPermission"
        severity="Error"
        message="Missing permissions required by Vibrator.vibrate: android.permission.VIBRATE"
        category="Correctness"
        priority="9"
        summary="Missing Permissions"
        explanation="This check scans through your code and libraries and looks at the APIs being used, and checks this against the set of permissions required to access those APIs. If the code using those APIs is called at runtime, then the program will crash.&#xA;&#xA;Furthermore, for permissions that are revocable (with targetSdkVersion 23), client code must also be prepared to handle the calls throwing an exception if the user rejects the request for permission at runtime."
        errorLine1="    v.vibrate(p_duration_ms);"
        errorLine2="    ~~~~~~~~~~~~~~~~~~~~~~~~"
        quickfix="studio">
        <location
            file="/home/ppbg/game_engine/godot/platform/android/java/src/org/godotengine/godot/Godot.java"
            line="337"
            column="5"/>
    </issue>

    <issue
        id="GradleDependency"
        severity="Warning"
        message="A newer version of com.android.tools.build:gradle than 3.2.1 is available: 3.5.0"
        category="Correctness"
        priority="4"
        summary="Obsolete Gradle Dependency"
        explanation="This detector looks for usages of libraries where the version you are using is not the current stable release. Using older versions is fine, and there are cases where you deliberately want to stick with an older version. However, you may simply not be aware that a more recent version is available, and that is what this lint check helps find."
        errorLine1="  classpath &apos;com.android.tools.build:gradle:3.2.1&apos;"
        errorLine2="  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
        quickfix="studio">
        <location
            file="/home/ppbg/game_engine/godot/platform/android/java/build.gradle"
            line="8"
            column="3"/>
    </issue>

    <issue
        id="TrulyRandom"
        severity="Warning"
        message="Potentially insecure random numbers on Android 4.3 and older. Read https://android-developers.blogspot.com/2013/08/some-securerandom-thoughts.html for more info."
        category="Security"
        priority="9"
        summary="Weak RNG"
        explanation="Key generation, signing, encryption, and random number generation may not receive cryptographically strong values due to improper initialization of the underlying PRNG on Android 4.3 and below.&#xA;&#xA;If your application relies on cryptographically secure random number generation you should apply the workaround described in https://android-developers.blogspot.com/2013/08/some-securerandom-thoughts.html .&#xA;&#xA;This lint rule is mostly informational; it does not accurately detect whether cryptographically secure RNG is required, or whether the workaround has already been applied. After reading the blog entry and updating your code if necessary, you can disable this lint issue."
        url="https://android-developers.blogspot.com/2013/08/some-securerandom-thoughts.html"
        urls="https://android-developers.blogspot.com/2013/08/some-securerandom-thoughts.html"
        errorLine1=" private static final SecureRandom RANDOM = new SecureRandom();"
        errorLine2="                      ~~~~~~~~~~~~">
        <location
            file="/home/ppbg/game_engine/godot/platform/android/java/src/com/google/android/vending/licensing/LicenseChecker.java"
            line="68"
            column="23"/>
    </issue>

    <issue
        id="HardwareIds"
        severity="Warning"
        message="Using `getString` to get device identifiers is not recommended."
        category="Security"
        priority="6"
        summary="Hardware Id Usage"
        explanation="Using these device identifiers is not recommended other than for high value fraud prevention and advanced telephony use-cases. For advertising use-cases, use `AdvertisingIdClient$Info#getId` and for analytics, use `InstanceId#getId`."
        url="https://developer.android.com/training/articles/user-data-ids.html"
        urls="https://developer.android.com/training/articles/user-data-ids.html"
        errorLine1="  io.unique_id = Secure.getString(getContentResolver(), Secure.ANDROID_ID);"
        errorLine2="                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~">
        <location
            file="/home/ppbg/game_engine/godot/platform/android/java/src/org/godotengine/godot/Godot.java"
            line="444"
            column="18"/>
    </issue>

</issues>

I want to know why it is and if it is my mistake, some guide to solve it.

**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by akien-mga** [comment] 2019-08-26 07:19
The first issue is indeed an error, and caused by #31438. CC @volzhs

**Comment by volzhs** [comment] 2019-08-27 12:07
it actually checks its permission.

https://github.com/godotengine/godot/blob/2c63c27ef1e83089fccbbfd2e8ec2781196b19e8/platform/android/java/src/org/godotengine/godot/Godot.java#L333-L340

https://github.com/godotengine/godot/blob/2c63c27ef1e83089fccbbfd2e8ec2781196b19e8/platform/android/java/src/org/godotengine/godot/Godot.java#L959-L986

for now, I'm not sure why lint says it.

**Comment by volzhs** [comment] 2019-08-27 12:09
64 bit issue is not related to this.
there should be release/debug apk even though lint says about the mission permissions.

**Comment by volzhs** [comment] 2019-08-27 12:40
AFAIK, to fix this issue, we need to put `<uses-permission android:name="android.permission.VIBRATE" />` line in the default `AndroidManifest.xml`

or adding `@SuppressLint("MissingPermission")` line for the `vibrate()` method in `Godot.java`

**Comment by akien-mga** [comment] 2019-08-27 15:42
Fixed by #31712.

**Closed by akien-mga** 2019-08-27 15:42 UTC
Labels: bug, platform:android, topic:porting
