### ISSUE TITLE
Scene dock glitches when minimum width

### ISSUE THREAD

**Issue by char0xff** [godotengine/godot#31306] opened 2019-08-11 22:36 UTC
**Godot version:**
v3.1.1.stable.official x64, Ubuntu

**Issue description:**
Minor editor issue.
The scene dock glitched when it's resized to a small width.

![glitch](https://user-images.githubusercontent.com/10872697/62840330-2f3c2600-bc99-11e9-85b7-2c4a55888bcb.png)

**Comment by KoBeWi** [comment] 2019-08-11 22:51
Duplicate of #28823

**Closed by KoBeWi** 2019-08-11 22:51 UTC
Labels: bug, topic:editor
