### ISSUE TITLE
ConvexPolygonShape2D problems with Auto Tiles

### ISSUE THREAD

**Issue by MinecraftPlaye** [godotengine/godot#18398] opened 2018-04-24 15:11 UTC
**Godot version:**
3.0.2-stable

**OS/device including version:**
Windows 10 (1709, x64)

**Issue description:**
My character can run into some walls while this should not be possible
with my collision setup (as far as I know).
![game](https://user-images.githubusercontent.com/9168045/39196017-684abf3e-47e1-11e8-8b18-51803b29a828.png)
I'm quite new to Godot 3, thus following [this tutorial](https://www.youtube.com/watch?v=uV5WKocIycY&index=5&list=PL9FzW-m48fn2jlBu_0DRh7PvAt-GULEmd).
As I still have the problem when all tiles within the tile map have a collision box I think this might be a problem with the engine.

**Minimal reproduction project:**

[Game.zip](https://github.com/godotengine/godot/files/1943349/Game.zip)

**Comment by vnen** [comment] 2018-04-24 16:51
Did you try turning on the Visibile Collision Shapes in the Debug menu? It'll show where the collision boxes are so it's easier to see whether there's a problem with your setup or with Godot.

**Comment by guilhermefelipecgs** [comment] 2018-04-24 21:39
Duplicate of #18197

This happens because you create a Concave shape.
In your case, you just need to recreate the collision that I'm showing in this gif below:
![output](https://user-images.githubusercontent.com/1387165/39215422-20ef435a-47ee-11e8-9dd5-1accbd80568b.gif)

**Comment by MinecraftPlaye** [comment] 2018-04-24 22:40
@guilhermefelipecgs How can I accidentally create a concave shape when I clearly selected convex polygon as the shape?
No matter how often I re-create the collision in the gif, the problem still occurs (while it is extremly hard to just select the red dot without selecting another collision...).

**Comment by guilhermefelipecgs** [comment] 2018-04-25 00:12
> How can I accidentally create a concave shape when I clearly selected convex polygon as the shape?

Maybe you clicked twice in the same spot. You can enable grid snap to try to avoid this.

This dock need some UX improvements, especially in the red dots. 

> No matter how often I re-create the collision in the gif, the problem still occurs

Try this way:
![output](https://user-images.githubusercontent.com/1387165/39219648-3fca44aa-4802-11e8-9aaa-2e166e7bd46c.gif)

Fixed project here: [Game.zip](https://github.com/godotengine/godot/files/1944997/Game.zip)

**Comment by MinecraftPlaye** [comment] 2018-04-25 20:33
@guilhermefelipecgs Thx, now it is working while also learning some new things about the Editor. :)

**Comment by akien-mga** [comment] 2018-05-01 09:42
Closing as duplicate of #18197.

**Closed by akien-mga** 2018-05-01 09:42 UTC
Labels: topic:physics
