### ISSUE TITLE
PackedScene.Pack() ignores changed properties of target nodes

### ISSUE THREAD

**Issue by mysticfall** [godotengine/godot#18293] opened 2018-04-19 11:44 UTC
**Godot version:**
`master` / 9ce8d8ddda35cda781364e9b648325a2953d3f63

**OS/device including version:**
_Manjaro Linux 17.1_

**Issue description:**
When saving a scene with `PackedScene.Pack()`, all nodes get saved with their exported properties reset to their default values.

It's reproducible in a C# project, and it's not clear if it happens in GDScript too.

**Comment by neikeq** [comment] 2018-08-10 08:43
Can you share an example project?

**Comment by PrinceMerluza** [comment] 2018-08-13 04:13
Hi, this is a sample project. The parents scene has export vars and will also instance another scene(with export vars) as a child. it would change the values in code and saved it to a packedscene file.

There are two versions of script for GD and C#. 

The GD one will correctly save the export vars value but the C# will have default values.

https://drive.google.com/open?id=1aqZrzk5-onOLm2xMSUHYy-02rKlBZtms

**Comment by akien-mga** [comment] 2019-02-23 13:19
Still reproducible in 3.1 beta 6.

**Comment by bitstopper** [comment] 2019-10-02 06:42
Still reproducible in https://github.com/godotengine/godot/commit/7e3dcf54ea209affff0855c080686a59a2ccc70f

**Comment by akien-mga** [comment] 2020-01-05 10:23
Still seems reproducible with the project in https://github.com/godotengine/godot/issues/18293#issuecomment-412404176 on 3.2 beta 5.

**Comment by neikeq** [comment] 2020-01-22 18:21
Damn, this is a regression from #27014.

One possible option is to revert that issue and add a custom callback like (e.g.: `_Init`) that is not called for temporary instances. This way people can use that instead of the constructor when needed.

Another option is to make the editor save the exports info before running the game (and when exporting the project), so the game can re-use it instead of having to re-calculating them.

In any case, I'm not sure if there's time to do this for 3.2.0.

**Comment by neikeq** [comment] 2020-01-23 14:35
Moving to the next milestone as there's no time to get a proper fix for 3.2.0.

**Comment by MightyPrinny** [comment] 2020-05-01 03:19
I get this in gd script scripts as well

**Comment by neikeq** [comment] 2020-05-10 12:54
@MightyPrinny Are you sure? That may be a different issue.

**Comment by MightyPrinny** [comment] 2020-05-10 16:36
@neikeq yes, the script's properties get reset when I save a scene with pack, however there's a workaroud that might not work with c# scripts, I can instance a gdscript node using new() at runtime and then the properties save properly.

**Comment by neikeq** [comment] 2020-05-10 19:29
> Another option is to make the editor save the exports info before running the game (and when exporting the project), so the game can re-use it instead of having to re-calculating them.

This is probably going to be the best idea in the meantime. It should fix this issue without needing to change the way things work for now.

**Closed** 2020-05-11 08:19 UTC
Labels: bug, confirmed, topic:mono

**Comment by neikeq** [comment] 2020-05-11 13:54
Can someone test if this is actually fixed by #38638? As far as I knew, to fix this we need games to know about the default values, but maybe I was mistaken about the cause.
