### ISSUE TITLE
Spatial editor gizmos are affected by their parent node's scale

### ISSUE THREAD

**Issue by DerRidda** [godotengine/godot#2792] opened 2015-11-15 16:55 UTC
As the title suggests. Icons for 3D light nodes appear at a fixed, huge size.

Build is latest from git.

![huge_light_icon](https://cloud.githubusercontent.com/assets/3391055/11169791/098d83ba-8bc2-11e5-83e2-415650ebf4f6.png)

**Comment by akien-mga** [comment] 2015-11-15 17:04
Thanks for the report. It's more or less the same issue as in #1638 so I'll close this one and add your screenshot there.

**Comment by akien-mga** [comment] 2015-11-15 17:09
Reopening, I misinterpreted the issue. It's not a zooming issue, the icon is *always* this big for @DerRidda.

**Comment by akien-mga** [comment] 2015-11-15 17:11
For the reference I can't reproduce the issue on Linxu X11 64bit by e.g. loading the Platform 3D demo in the editor and checking out the dimensional light icon.

**Comment by DerRidda** [comment] 2015-11-15 17:22
I tried a clean rebuild and it is not fixed. Trying again from a fresh clone.

**Comment by DerRidda** [comment] 2015-11-15 17:53
Still no change, this isa  genuine issue for me.

**Comment by DerRidda** [comment] 2015-11-15 18:38
Apparently my rebuilding has fixed it it is fixed in new scenes but the one affected is not recovering. As that scenes is absolutely not important I consider the issue resolved.

**Comment by eska014** [comment] 2015-11-15 18:42
Was this caused by the DirectionalLight node's scale?
If so, it should probably be changed so the sprite doesn't scale.

**Comment by DerRidda** [comment] 2015-11-15 18:51
No it wasn't, this happened with any light I added at any scale.

**Comment by bojidar-bg** [comment] 2015-11-23 12:57
@DerRidda does it happen when you rebuild that very scene again?

**Comment by DerRidda** [comment] 2015-11-23 20:12
I deleted that scene and therefore can not test this issue anymore.

**Comment by akien-mga** [comment] 2015-11-23 20:31
Actually the first screenshot shows it all: the DirectionalLight is a child of Spatial, and Spatial is upscaled by at least 8 on the x axis.

Just tried the same in a new project and could reproduce the issue:

Spatial, scale (8, 8, 8)
  -> DirectionalLight

![gd](https://cloud.githubusercontent.com/assets/4701338/11348895/65e1a386-9229-11e5-856c-354cfbb29390.png)

So the light icon just needs to be made non-scalable in the viewport (likely the same for #1638).

**Comment by akien-mga** [comment] 2015-11-23 21:05
So after a first look at https://github.com/godotengine/godot/blob/master/tools/editor/spatial_editor_gizmos.cpp#L3057 I've found that there are several other gizmos affected by this issue:
- GizmoLight (OmniLight, SpotLight)
- GizmoDirectionalLight (DirectionalLight)
- GizmoSpatialSamplePlayer (SpatialSamplePlayer)
- GizmoSpatialStreamPlayer (SpatialStreamPlayer)
- Visible (VisibilityNotifier)

We'd need to find a way to make those gizmos unscalable, so that they are not affected by their parent's scale. I don't know if FixedMaterial has a feature for that already.

**Comment by tonymtbird** [comment] 2015-12-12 03:26
i have a fix to #1638 i will look into this as well before a pull request..

**Comment by tonymtbird** [comment] 2015-12-12 06:17
hum seems like a bigger issue is at play here, when I scale a spatial node, EVERY child of it seems to scale in the view port--somehow that seems the way it should be, but it should not be.  A spatial is just a kind of placeholder for the universe--its more of an ancient ancestor then a parent, and should be coded that way?

**Comment by akien-mga** [comment] 2016-03-23 12:32
Suggestion from #748:

> Some nodes like lights use sprites to display their position, but often when zooming out they become so big, compared to rest of the scene, that they are more in the way than help.

> They need editable maximum size settings, and ON/OFF switching.

**Comment by DualMatrix** [comment] 2018-09-19 19:15
Tested in master. Seems fixed.

**Comment by akien-mga** [comment] 2018-09-19 21:03
Thanks, closing.

**Closed by akien-mga** 2018-09-19 21:03 UTC
Labels: bug, confirmed, topic:editor
