### ISSUE TITLE
"(Re)importing Assets" dialog blocks screen making it difficult to do other things while waiting...

### ISSUE THREAD

**Issue by maiself** [godotengine/godot#72155] opened 2023-01-27 05:47 UTC
### Godot version

Godot 4, d1e5903c67956707948b1de370b807e3aad395b7

### System information

Arch Linux, Gnome Shell, Wayland

### Issue description

The "(Re)importing Assets" dialog blocks all other windows while importing is in progress. This window is always on top, immovable, and unhideable. For long import operations it makes using other applications on the system difficult.

![Screenshot from 2023-01-27 00-39-51](https://user-images.githubusercontent.com/6334580/215018181-41c17f90-140b-4b86-8d62-3515accdf3a7.png)

![Screenshot from 2023-01-27 00-40-26](https://user-images.githubusercontent.com/6334580/215018190-e2f26c78-1260-4499-8ca7-9146c260a6d0.png)

![Screenshot from 2023-01-27 00-44-18](https://user-images.githubusercontent.com/6334580/215018197-850ab0c3-f5e4-47b6-babf-771851d5a876.png)

### Steps to reproduce

Cause files to import, try to use other applications while import is in progress.

### Minimal reproduction project

N/A

**Comment by akien-mga** [comment] 2023-01-27 08:28
Probable duplicate of other fixes issues, but you don't specify which Godot version you're using precisely. "4.0" spans 3 years...

**Comment by maiself** [comment] 2023-01-27 10:32
Build from today, d1e5903c67956707948b1de370b807e3aad395b7. Don't have a start date, or even sure if there is one.

**Comment by akien-mga** [comment] 2023-01-27 10:35
Seems like I misread the issue originally, I thought it was freezing but it's just staying on top of non-Godot windows. I've seen that too, probably ever since multi window support was implemented.

**Comment by Calinou** [comment] 2023-01-27 10:35
Enabling **Single Window Mode** in the Editor Settings most likely works around the issue.

**Comment by AThousandShips** [comment] 2023-01-27 11:34
Since the editor is unusable while reimporting embedding it sounds good

**Comment by akien-mga** [comment] 2023-01-31 10:34
Fixed by #72439.

**Closed by akien-mga** 2023-01-31 10:34 UTC
Labels: bug, topic:editor, usability, topic:import
