### ISSUE TITLE
Support for Windows Alt codes for extended ASCII input

### ISSUE THREAD

**Issue by SHARKvince** [godotengine/godot#2689] opened 2015-10-27 23:27 UTC
When trying to insert a character with an alt code in Godot, in any text field, it will not be picked up.

For this purpose, I tried to enter the curly apostrophe: ’ (Alt + 0146)

Example 1:
1. Open a new scene
2. Add a Label node
3. When writing text in the text field, enter Alt + 0146

Example 2:
1. Open a new scene
2. Add a TextEdit field
3. Save scene
4. Play scene
5. In the text field, try to enter Alt + 0146

Neither of these approaches will work.

**Comment by vnen** [comment] 2015-11-09 21:22
At first I thought this was related to Unicode, but it does not work even with standard ASCII characters (like Alt+65 for "A").

**Comment by reduz** [comment] 2015-12-28 01:01
this is very windows specific.. i have no idea how to fix it.. godot just gets unicode characters, so maybe this is a behavior of Window's line edit control, which godot does not use?

**Comment by akien-mga** [comment] 2018-05-15 09:04
Retagging as a feature proposal, as it's not a bug per se, it's just a feature of Windows input controls that we don't have in Godot's cross-platform controls.

I've had a quick look for examples of how this could be implemented, but couldn't find anything relevant (the name of the "feature" doesn't help search engines though).

If someone wants to look into, it might be worth checking how cross-platform toolkits like Qt or GTK+ handle it. If it's possible to implement it at all, then it might be interesting to also look into supporting <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>U</kbd> + hex which is used (at least by GTK+ apps) to input any Unicode character.

**Comment by jluini** [comment] 2020-05-16 18:32
I have the same problem, my keyboard doesn't have keys for angle brackets < >.
I usually get them with Alt+60 and Alt+62 (using numeric keyboard) but that doesn't work in godot, so I'm copypasting them from another application. The right bracket is specially useful to statically type the function return values (`func xxx() -> int:`).

I imagine two possible solutions:

1. add a specific command for inserting a > so we can bind a shortcut to it
2. change the autocompleter so when a hyphen is added after a funcion signature it autocompletes with the bracket, maybe the semicolon, and the cursor gets in the place of the type

Before autocompletion:

`func get_some_integer() -`

After autocompletion:

`func get_some_integer() -> :`

**Comment by akien-mga** [comment] 2020-05-25 19:07
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!

**Closed by akien-mga** 2020-05-25 19:07 UTC
Labels: confirmed, feature proposal, platform:windows, topic:editor

**Comment by akien-mga** [comment] 2022-05-13 08:17
Implemented by #55441.
