### ISSUE TITLE
Export with release keystore but fail with error:"'jarsigner' returned with error #1"

### ISSUE THREAD

**Issue by KenHuang0917** [godotengine/godot#7377] opened 2016-12-27 16:16 UTC
**Operating system or device - Godot version:**
macOS Sierra 10.12.1, Godot 2.1 stable
**Issue description** (what happened, and what was expected):
Export with release keystore but fail with error:"'jarsigner' returned with error #1"
I tried adding -sigalg MD5withRSA -keyalg RSA to generate keystore as #1957 but didn't help.

**Steps to reproduce:**
Godot export to Android .apk, unchecking "Debugging enabled"
But signed with debugkey is OK

**Link to minimal example project** (optional but very welcome):

**Comment by KenHuang0917** [comment] 2016-12-28 03:49
It could be my fault and I found the reason why it failed. At the export dialog, "Options-Keystore-Release User" should be the "alias". More specifically , if the keystore is generated by:

keytool -keyalg RSA -genkeypair -alias androiddebugkey -keypass android -keystore debug.keystore -storepass android -dname "CN=Android Debug,O=Android,C=US" -validity 9999 -sigalg MD5withRSA -keyalg RSA

then the "Release User" should be "androiddebugkey" rather than the user ("Android Debug").
Sorry for my misunderstanding and thank you for your help!

**Comment by KenHuang0917** [comment] 2016-12-31 13:51
Another question: Is it possible to sign Godot's apk with .jks file which is generated by Android Studio? Godot's export only accept .keystore type file. I tried to rename .jks file to .keystore file to cheat Godot, but still failed and get the same 'jarsigner' returned with error #1. I made a mistake so that I have to use this .jks file to sign project. :(

**Comment by Noshyaar** [comment] 2018-04-10 16:03
First of all thank you for your report and sorry for the delay.

We released Godot 3.0 in January 2018 after 18 months of work, fixing many old issues either directly, or by obsoleting/replacing the features they were referring to.

We still have hundreds of issues whose relevance/reproducibility needs to be checked against the [current stable version](https://godotengine.org/download), and that's where you can help us.
**Could you check if the issue that you described initially is still relevant/reproducible in Godot 3.0 or any newer version, and comment about it here?**

For bug reports, please also make sure that the issue contains detailed steps to reproduce the bug and, if possible, a zipped project that can be used to reproduce it right away. This greatly speeds up debugging and bugfixing tasks for our contributors.

Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

Thanks in advance.

*Note: This message is being copy-pasted to many "stale" issues (90+ days without activity). It might happen that it is not meaningful for this specific issue or appears oblivious of the issue's context, if so please comment to notify the Bugsquad about it.*

**Comment by akien-mga** [comment] 2019-04-15 14:15
> Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

As there was no update since the previous post, we close this issue.

If it is still relevant in the way it was described and discussed above, please comment to ask for it to be reevaluated. If it is only partly relevant, or if the original issue has changed, it would be better to open a new issue (potentially referring to this one) focused on the current state.

**Closed by akien-mga** 2019-04-15 14:15 UTC
Labels: documentation, platform:android, topic:editor
