### ISSUE TITLE
References to class not resolved when exported

### ISSUE THREAD

**Issue by FrankAlbella** [godotengine/godot#41215] opened 2020-08-13 05:53 UTC
**Godot version:**

3.2.3rc3

**OS/device including version:**

Pop!_OS 20.04, GTX 1080, proprietary driver 440.100

**Issue description:**

Attempting to reference a `class_name` causes a parse error when exported. This issue is not present when the project is ran from the editor, the scene must be exported and ran from the produced executable. The project was exported from a Linux machine, but the error and crash occur with both the Windows and Linux exported executable file. Other operating systems were not tested. 

The inheritance issue can be worked around by using the script path instead of the class_name. For example: use `extends "base.gd"` instead of `extends base`

**Steps to reproduce:**
1. Declare a `class_name [class name]` in a script
2. In another script reference the class, this includes: 
   a. `extends [class name]`
   b. `if x is [class name]`
3. Download and install export templates from the Manage Export Templates menu
4. Export the project
5. Run the executable file
6. Run the project until the script is run, the game will crash and have this error printed to the terminal: `SCRIPT ERROR: GDScript::load_byte_code: Parse Error: The identifier "[class name]" isn't declared in the current scope.`

**Minimal reproduction project:**

[godot_inheritance_issue.zip](https://github.com/godotengine/godot/files/5067324/godot_inheritance_issue.zip)

**Comment by Calinou** [comment] 2020-08-13 12:18
Duplicate of https://github.com/godotengine/godot/issues/40991.

**Closed by Calinou** 2020-08-13 12:18 UTC
