### ISSUE TITLE
[Godot 4.0] Exporting Typed Nested Arrays not Supported, Although Docs Say They Are

### ISSUE THREAD

**Issue by TicklesTheBrain** [godotengine/godot#65329] opened 2022-09-04 15:30 UTC
### Godot version

4.0 alpha 15

### System information

Windows 10, Radeon 5500 XT

### Issue description

I am trying to export a nested Array into the editor, I'm using the exact code snippet from the docs:
![image](https://user-images.githubusercontent.com/21967696/188321292-235eb9c8-c052-449e-819d-de7cfa375280.png)

Can be found here: https://docs.godotengine.org/en/latest/tutorials/scripting/gdscript/gdscript_exports.html

This gives an error message, and doesn't work:

![image](https://user-images.githubusercontent.com/21967696/188321326-9ab67e19-01c5-4eef-aa7f-b6215b1392d3.png)
![image](https://user-images.githubusercontent.com/21967696/188321335-667867b6-d3f7-4422-a5d5-8dc4d4f0199e.png)

### Steps to reproduce

1. Start new project.
2. Try exporting nested array as shown in docs
3. Observe the error

**Comment by Calinou** [comment] 2022-09-04 17:35
Duplicate of https://github.com/godotengine/godot/issues/61923.

**Closed by Calinou** 2022-09-04 17:35 UTC
