### ISSUE TITLE
[FIXED in master] [Godot 4 RC2] Directional shadow twitches when the camera moves

### ISSUE THREAD

**Issue by unfa** [godotengine/godot#73572] opened 2023-02-18 23:56 UTC
### Godot version

4.0 RC2

### System information

Arch Linux + X11+ KDE Plasma + Radeon RX6800XT

### Issue description

I've tested and it does not happen in RC1 - this is clearly a regression in RC2.

Demonstration in RC2:
https://youtu.be/7RK0D4woyMI

In RC1 there is no such issue:
https://youtu.be/Jl5q6M_i2Ao

### Steps to reproduce

Probably just use a directional light I guess?

### Minimal reproduction project
[Twitching Shadows.zip](https://github.com/godotengine/godot/files/10788214/Twitching.Shadows.zip)

**Comment by akien-mga** [comment] 2023-02-19 00:02
What do you mean by "FIXED in master"?

**Comment by Calinou** [comment] 2023-02-19 00:44
@unfa Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

Also, check if this only occurs when the light's angular distance is greater than 0 (PCSS-style shadows).

**Comment by unfa** [comment] 2023-02-19 00:49
@akien-mga That means me building Godot from git after the RC2 release doesn't show this problem. I assume it was a mistake that was noticed and promptly fixed after the RC2 release. I decided to still post the issue in case it's not that simple.

@Calinou Ok, I'll try to do that.

**Comment by unfa** [comment] 2023-02-20 22:49
Here's an MRP:
[Twitching Shadows.zip](https://github.com/godotengine/godot/files/10788214/Twitching.Shadows.zip)

**Comment by Calinou** [comment] 2023-02-20 22:51
Duplicate of https://github.com/godotengine/godot/issues/59232.

**Closed by Calinou** 2023-02-20 22:51 UTC
Labels: bug, topic:rendering, needs testing, topic:3d

**Comment by unfa** [comment] 2023-02-20 22:53
Thanks!

**Comment by akien-mga** [comment] 2023-02-21 07:24
What about the comment that it's fixed in master? Is #59232 too?

**Comment by unfa** [comment] 2023-02-21 13:29
I didn't test that one.

**Comment by akien-mga** [comment] 2023-02-21 15:29
I tested and the MRP from https://github.com/godotengine/godot/issues/73572#issuecomment-1437643757 does reproduce the bug, so it doesn't appear to be fixed (and thus can indeed be a duplicate of #59232).
