### ISSUE TITLE
4.0: Editor crashing when opening dialog box. No logs reported.

### ISSUE THREAD

**Issue by castroclucas** [godotengine/godot#45381] opened 2021-01-23 06:54 UTC
**Godot version:**

Godot 4 d39f638

**OS/device including version:**

Manjaro Linux 5.9.16-1-MANJARO KDE
GTX 1660 Super
All drivers are updated, including nvidia-vulkan drivers. Lib32 drivers are also installed.
Vulkan backend.

**Issue description:**

Everytime I open a project, or create a new one, the window glitches but opens fine.
I can interact with the 3D view, change to 2D view, Script View, etc. Everything visible works fine. 

But when I click on anything that opens a dialog box/new window (like Scene-> New Scene or Project -> Project Settings) or hit the play button, the editor simple freezes my entire computer, even the mouse.

After some seconds I can move the mouse again and have to sudo pkill the editor.

I rebuilt the package many times, with `release_debug` and `debug` tags, mono and without mono. I experienced this issue with all builds.

I also ran Godot with `--debug` and `--verbose` parameters but the freezes produces no helpful logs:

```
Godot Engine v4.0.dev.custom_build.d39f6386c - https://godotengine.org
Using ICU / HarfBuzz / Graphite text server...
EditorSettings: Save OK!
XInput: Refreshing devices.
XInput: No touch devices found.
DisplayServer::_create_window 0 want rect: 448, 240, 1024, 600 got rect 448, 240, 1024, 600
PulseAudio: detected 2 channels
PulseAudio: audio buffer frames: 512 calculated latency: 11ms

Class 'BulletPhysicsDirectBodyState3D' is not exposed, skipping.                                                                                                                       
Class 'BulletPhysicsDirectSpaceState' is not exposed, skipping.
Class 'BulletPhysicsServer3D' is not exposed, skipping.
Class 'GDScriptEditorTranslationParserPlugin' is not exposed, skipping.
Class 'GDScriptNativeClass' is not exposed, skipping.
Class 'IP_Unix' is not exposed, skipping.
Class 'PhysicsDirectBodyState2DSW' is not exposed, skipping.
Class 'PhysicsDirectSpaceState2DSW' is not exposed, skipping.
Class 'PhysicsServer2DSW' is not exposed, skipping.
Class 'ResourceImporterMP3' is not exposed, skipping.
Class 'ResourceImporterOGGVorbis' is not exposed, skipping.
Class 'TextServerAdvanced' is not exposed, skipping.
Construct gdnative interface

Destruct gdnative interface

EditorSettings: Load OK!
Loaded builtin certs
EditorSettings: Save OK!
DisplayServer::_window_changed: 0 rect: 0, 29, 1024, 600
DisplayServer::_window_changed: 0 rect: 0, 29, 2560, 1006
DisplayServer::_create_window 1 want rect: 1024, 503, 512, 77 got rect 1024, 503, 512, 77
out of date
out of date
DisplayServer::_window_changed: 0 rect: 1216, 96, 1024, 600
DisplayServer::_window_changed: 0 rect: 3456, 29, 1024, 600
out of date
DisplayServer::_window_changed: 0 rect: 2560, 29, 1920, 1051
out of date
DisplayServer::_window_changed: 0 rect: 2805, 99, 1024, 600
DisplayServer::_window_changed: 0 rect: 2946, 29, 1024, 600
DisplayServer::_window_changed: 0 rect: 2560, 29, 1920, 1051
DisplayServer::_create_window 2 want rect: 2999, 129, 255, 136 got rect 2999, 129, 255, 136
````

Godot 3.2 Stable works fine.

**Steps to reproduce:**

- `git clone https://github.com/godotengine/godot.git`
- `cd godot`
- `scons -j8 platform=x11 target=debug` or `release_debug`. I tested with both.
- `bin/godot.linuxbsd.tools.64 -d -v`
- open or create new project. The project selection screen works fine. I can even open dialog boxes.
- the editor also opens fine
- try to play the scene or open any dialog boxes and the screen freezes

**Minimal reproduction project:**

Happens with any project, even with new ones.

**Comment by qarmin** [comment] 2021-01-23 08:26
This may be Nvidia 450+ drivers issue.
Try to use this workaround from this comment https://github.com/godotengine/godot/issues/41614#issuecomment-699430991

**Comment by Calinou** [comment] 2021-01-23 15:39
Duplicate of https://github.com/godotengine/godot/issues/41614.

**Closed by Calinou** 2021-01-23 15:39 UTC

**Comment by castroclucas** [comment] 2021-01-23 22:09
Woah, I searched a lot for "GUI Crashes", "GUI Freezes", "Editor Crashes", but not for "GUI unresponsive".

It solved the problem. Thank you!

**Comment by Calinou** [comment] 2021-01-23 22:34
> Woah, I searched a lot for "GUI Crashes", "GUI Freezes", "Editor Crashes", but not for "GUI unresponsive".

I added keywords to the issue so it can be found more easily.
