### ISSUE TITLE
Collision shape gizmo isn't updated upon changing the shape

### ISSUE THREAD

**Issue by tagcup** [godotengine/godot#8910] opened 2017-05-25 15:23 UTC
In the editor, changes made to a collision shape aren't immediately reflected in the 3D editor.
The only way I can get it updated is to select a different node and then reselect the collision shape node.

**Comment by tagcup** [comment] 2017-05-26 15:11
It's actually not updated at all until I reselect the collision shape again.

Here's a different example: if you move the parent object (test cube) a little below in the y-axis using the property editor, the child collision shape gizmo doesn't follow it

![screenshot_20170526_100956](https://cloud.githubusercontent.com/assets/16531565/26500490/bea1fc4a-41fb-11e7-9509-f1fb1e70f50e.png)

**Comment by Yazir** [comment] 2017-05-29 19:07
Can confirm.

**Comment by Qu-inn** [comment] 2017-06-08 14:37
Same for me, changing the transform (either directly or by any parent) of the CollisionShape is not immediately represented by the gizmo.

The gizmo updates if I mouse over one of the handles to edit the shape (where it should be drawn). Or if I deselect/select another node as reported above.

Some quick debugging shows that update_gizmo() is not getting called when the transform is changed, but seems to work fine when it does get called (selecting the node or mousing over the handles).

**Comment by kubecz3k** [comment] 2017-08-03 18:45
In duplicate #10049 @ApachOC posted gif together with a note:
![28886574-46a1fd72-77ba-11e7-8f9c-c005a3498fec](https://user-images.githubusercontent.com/6129594/28937899-a3ece924-788c-11e7-84f2-6374e6daf6ae.gif)
_Please note, that the perceived movement of the gizmo is caused by moving cursor over shape handles, which causes the gizmo to update its transform._

**Comment by reduz** [comment] 2017-08-07 00:33
duplicate of #7837

**Closed by reduz** 2017-08-07 00:33 UTC
Labels: bug, confirmed, topic:editor
