### ISSUE TITLE
"Input.JoyConnectionChanged" is passing a "long" type device id rather than "int"

### ISSUE THREAD

**Issue by MrYang259** [godotengine/godot#80007] opened 2023-07-29 10:03 UTC
### Godot version

4.1.1 stable mono

### System information

Windows10-Godot 4.1.1-stable-mono-Forward+

### Issue description

Trying to get controller connection signals, I declared a function to print connecting controller name, the function's first parameter has to be "long" type to work, but most of the build in functions are using "int"

### Steps to reproduce

declare function with "long" parameter and cast to "int" after(won't get bigger number than "int" I guess)

### Minimal reproduction project

[Bug Report.zip](https://github.com/godotengine/godot/files/12206816/Bug.Report.zip)

**Comment by RedworkDE** [comment] 2023-07-29 13:27
Duplicate of https://github.com/godotengine/godot/issues/65749

**Closed by RedworkDE** 2023-07-29 13:27 UTC
