### ISSUE TITLE
Piles of KinematicBody2D nodes glitch when on a vertically moving platform

### ISSUE THREAD

**Issue by carllacan** [godotengine/godot#52061] opened 2021-08-24 11:02 UTC
### Godot version

3.3.3 stable, also 3.4 beta4

### System information

Manjaro with Plasma KDE, Atx Radeon 580 GLES3

### Issue description

Piles of KinematicBody2D nodes on top of a vertically moving platform have glitchy movement, partially overlapping one another and getting separated by a few pixels form the platform they are supposed to stand on.  The sync_to_physics option solves the problem when it's a single object on top of the platform, but not when there are more than two, like a box and the character player.

### Steps to reproduce

Create a KinematicBody2D with a Sprite and a corresponding CollisionShape, and animate it so that its position changes up and down.

Create various KinematicBody2D and use move_and_slide to have them fall fown on the vertically moving platform.

### Minimal reproduction project

[godot_kinematic.zip](https://github.com/godotengine/godot/files/7038629/godot_kinematic.zip)

**Comment by pouleyKetchoupp** [comment] 2021-08-24 22:54
Probably similar cause as #49497, but with a different use case so I'm keeping both open for testing purpose.

**Comment by pouleyKetchoupp** [comment] 2021-10-01 17:53
Closing as duplicate of https://github.com/godotengine/godot/issues/49497, but I've added a note there to check this use case for test.

**Closed by pouleyKetchoupp** 2021-10-01 17:53 UTC
Labels: bug, confirmed, topic:physics, topic:2d
