### ISSUE TITLE
I don't even know anymore. Editor not representing the game or something.

### ISSUE THREAD

**Issue by ligazetom** [godotengine/godot#35577] opened 2020-01-26 08:47 UTC
**Godot version:**
3.2.beta.custom_build.24281cd9c

**OS/device including version:**
Windows 10 Pro (Version: 1903, Build 18362.535)

**Issue description:**
Objects are in different positions once started the game than in editor.
Here it is how it looks in editor:
![image](https://user-images.githubusercontent.com/11858829/73132827-696b6b00-4020-11ea-8ea6-a4e01b2c54cb.png)
Closer:
![image](https://user-images.githubusercontent.com/11858829/73132833-7ab47780-4020-11ea-846f-e48c02ab5950.png)

After hitting F5:
![image](https://user-images.githubusercontent.com/11858829/73132875-41303c00-4021-11ea-8168-5649b49d8beb.png)

**Steps to reproduce:**
Do anything, and godot makes it broken somehow.

**Minimal reproduction project:**
[TestGame.zip](https://github.com/godotengine/godot/files/4113266/TestGame.zip)

I uploaded my whole test project I've been playing with since 2 months ago. However I'm done. This engine has so many basic functionalities broken. I hope it helps somehow.

**Comment by ligazetom** [comment] 2020-01-26 08:51
I mean, I scaled the cubes to make the walls, but this is so out of touch.

**Comment by Jummit** [comment] 2020-01-26 08:59
All scenes are corrupted. They all seem to randomly end in the middle.

**Comment by aaronfranke** [comment] 2020-01-26 22:39
IIRC, Godot currently doesn't support scaled RigidBodies, they behave weirdly. Perhaps there should be a warning about this, or perhaps support for them should be improved?

**Comment by nathanwfranke** [comment] 2020-01-27 08:23
Duplicate(?) or related to #5734. Scaling 3D physics bodies leads to undefined behaviour. I think reduz plans to make scaling work by 4.0, but for 3.2 it should at least be prevented. (#26890)

**Comment by akien-mga** [comment] 2020-01-27 08:33
Indeed, duplicate of #5734 for the bug (physics body can't be scaled) and #26890 for the usability issue in the meantime.

**Closed by akien-mga** 2020-01-27 08:33 UTC
Labels: bug, discussion, topic:physics

**Comment by akien-mga** [comment] 2020-01-27 08:50
See #35614.
