### ISSUE TITLE
Z fighting issue between 3D Animated Sprites even with opaque pre-pass custom material.

### ISSUE THREAD

**Issue by ca3games** [godotengine/godot#25297] opened 2019-01-24 20:44 UTC
https://www.youtube.com/watch?v=a1KosDF0ZlQ

As you can see in the video, there's a wrong Z ordering between two animated sprites and their rigidbodies on a 3D scene.

There's already monitoring collision turn on and set to 1.
I even set a custom material to the animated sprite and set the Depth Draw to Opaque Pre-Pass mode on both the red wolf sprite and the other character.

[Project.zip](https://github.com/godotengine/godot/files/2793532/Project.zip)

Here are the project files.

**Comment by reduz** [comment] 2019-02-12 10:01
I can't reproduce this, even with GLES2. @CowThing can you post that example project?

**Comment by CowThing** [comment] 2019-02-12 13:44
Looks like that was fixed sometime between beta 2 and beta 3, because I can only reproduce it in beta 2. And it works in a more recent build as well.

**Comment by akien-mga** [comment] 2019-02-12 14:02
Thanks, closing as fixed.

**Closed by akien-mga** 2019-02-12 14:02 UTC
Labels: bug, topic:rendering
