### ISSUE TITLE
Certain chacters in Label text do not display correctly

### ISSUE THREAD

**Issue by jfcg** [godotengine/godot#42829] opened 2020-10-15 16:24 UTC
**Godot version:**
v3.2.3

**OS/device including version:**
Latest Manjaro Linux, XFCE desktop, en_US.UTF-8 locale, turkish keyboard

**Issue description:**
certain chacters in Label text do not display correctly

**Steps to reproduce:**
- create empty project
- add Label
- set Label's text to `Hello ç ş ı ğ ü`
- observe in 2d viewport that Label text does not display correctly
- run the scene
- observe that certain characters do not display correctly

**Screenshot**
![godot bug](https://user-images.githubusercontent.com/1410597/96158076-c9da6980-0f1b-11eb-9573-7726c71431e5.jpg)

**Minimal reproduction project:**
[Tutor1.zip](https://github.com/godotengine/godot/files/5386370/Tutor1.zip)

**Comment by Calinou** [comment] 2020-10-15 16:35
Duplicate of https://github.com/godotengine/godot-proposals/issues/1079.

To solve this, assign a custom DynamicFont to your label (or in your theme resource).

**Closed by Calinou** 2020-10-15 16:35 UTC
