### ISSUE TITLE
Importing .wav files causes crash + "read-only" mode

### ISSUE THREAD

**Issue by korncob** [godotengine/godot#69983] opened 2022-12-12 20:25 UTC
### Godot version

v4.0.beta8.official

### System information

Windows 10, Intel i7-8700 3.2ghz, Geforce RTX 2070

### Issue description

On a completely new/blank project, and on a project I'm attempting to manually convert over, importing a .wav file that's large in size seems to hard crash the editor. If I import more than one .wav at a time, the project crashes on open until I remove them.
Now assuming I import one .wav file, take the crash and successfully reload the project, the .wav file seems unusable and states "this object is read-only". Upon clicking said text, it brings up a popup telling me to change the importation settings to make it usable again. There are barely any options and they all seem related to common compression/normalize/etc. type options. Nothing related to the object being read-only, even so I tried flipping options off and on randomly and reimporting the .wav file with no change in it being usable.
On the flip side, the 1 .mp3 that I wanted to convert over seems to work perfectly fine on importation and usability. For reference I have a few hundred .wav files and I've tried tens of them so far individually with all of them behaving the same both in my project and on a blank project.

### Steps to reproduce

Open blank project, import any .wav file longer than a few seconds by either drag and drop into the editor or pasting into the file system.

### Minimal reproduction project

This issue is replicatable with a blank project however just in case I uploaded a blank project with an example .wav (just ambient noise) just so it's easier to open it and see the read-only issue.

[audio_issues.zip](https://github.com/godotengine/godot/files/10211735/audio_issues.zip)

**Comment by korncob** [comment] 2022-12-13 07:31
Small update, I tried importing my entire project with the .wav's using beta 7 instead of 8 and it seems to be letting me import it without crashing, but it's still ready-only. I do feel like I'm maybe missing a setting somewhere, but everywhere I searched/asked had no answers.

**Comment by akien-mga** [comment] 2022-12-13 09:57
The fact that it's read only is expected. As the dialog tells you, it's an imported resource, and imported resource can't be modified - they should be reimported with different settings if you want to change some of their imported state. 

The import settings do match the properties of the imported file, though I agree the relationships may not be obvious. That's a UX problem that could be improved:

- Force 8 Bit --> Format 8-bit/16-bit
- Force Mono --> Stereo On/Off
- Force Max Rate + Max Rate Hz --> Mix Rate
- Loop Mode --> Loop Mode, Begin, and End

**Comment by korncob** [comment] 2022-12-14 03:42
Thanks for your reply!
I see where I got confused, so in 3.4 which is the version I'm used to
using when you import a .wav is allows you to preview the audio file. In
beta 8 when I didn't see the option to playback the audio file and I saw
"read-only" at the top, combined with mp3's having a completely different
menu popup, I got confused and thought the .wav's were being disabled in
some way. What I meant with the properties of the imported file is that
there wasn't an option to turn off "read-only", which I'm now realizing
doesn't matter because I'm not needing to actually edit the file in engine.
Sorry for the confusion, I do agree your wording is way better though for
the inspector portion of the imported files though.

**Comment by akien-mga** [comment] 2022-12-14 08:21
Indeed I was also surprised by the lack of preview/playback option. It seems to be a regression that should be fixed before the 4.0 release: https://github.com/godotengine/godot/issues/63683

**Comment by realkotob** [comment] 2022-12-24 19:48
https://github.com/godotengine/godot/issues/63683 was closed, is this also fixed?

**Comment by akien-mga** [comment] 2023-01-19 21:21
I'd say yes, at least I can't reproduce the mentioned crash.

The slightly confusing differences between the Import options and the properties of the imported stream would have been good to streamline, but it's too late for Godot 4.0 and changing it afterwards would break compatibility.

**Closed by akien-mga** 2023-01-19 21:21 UTC
Labels: bug, topic:import, crash
