### ISSUE TITLE
[4.2dev4] GPUParticles2D fully opaque in runtime

### ISSUE THREAD

**Issue by fredlim** [godotengine/godot#81273] opened 2023-09-03 14:33 UTC
### Godot version

v4.2.dev4.official [549fcce5f]

### System information

Windows 11 22H2

### Issue description

There is no alpha effect on GPUParticle2D
![Screenshot 2023-09-03 221759](https://github.com/godotengine/godot/assets/8569368/e98b17e9-f063-4bac-9c43-7e7a543c416b)
![Screenshot 2023-09-03 221815](https://github.com/godotengine/godot/assets/8569368/8294c59a-f113-42b5-8603-3ac2b17c053a)

Working fine with v4.1.1.stable.official [bd6af8e0e] and v4.2.dev3.official [013e8e3af]

### Steps to reproduce

Open the project main.tscn, drag the player node to see the particles are fading correctly. Run the game, moving the player, the particle is fully opaque.

### Minimal reproduction project

[Dodge the Creeps!.zip](https://github.com/godotengine/godot/files/12506294/Dodge.the.Creeps.zip)

**Comment by clayjohn** [comment] 2023-09-05 15:26
Seems to be a duplicate of https://github.com/godotengine/godot/issues/81166 which was fixed by https://github.com/godotengine/godot/pull/81198

Testing in master and I can confirm that this is fixed. We will release Dev5 soon with the fix!

**Closed by clayjohn** 2023-09-05 15:26 UTC
Labels: bug, topic:rendering, confirmed, topic:2d, topic:particles
