### ISSUE TITLE
Godot random freeze

### ISSUE THREAD

**Issue by ryugold777** [godotengine/godot#70082] opened 2022-12-14 23:39 UTC
### Godot version

3.5.1

### System information

Linux/Arch Linux

### Issue description

I was developing my game and suddenly godot freeze. This is happening often every time I need to open the terminal e use the command "pkill" e restart the engine. I don't know what is the reason of this bug, but is annoying me. Thanks in advance for the answers.

### Steps to reproduce

I don't know what is the reason.

### Minimal reproduction project

[Project.zip](https://github.com/godotengine/godot/files/10232457/Project.zip)

**Comment by Rubonnek** [comment] 2022-12-15 03:35
The MRP has missing dependencies and it's not possible to run the project as-is. It's hard to find the cause of the issue without being able to reproduce it.

**Comment by timothyqiu** [comment] 2022-12-15 07:22
Possible duplicate of #69942

**Comment by lawnjelly** [comment] 2022-12-15 10:26
List of candidates if it is recent, and if linux specific:
(neither of which is confirmed, but a lot of recent reports, and all linux so far)
https://github.com/godotengine/godot/commits/3.x/platform/x11

**Comment by ryugold777** [comment] 2022-12-15 15:01
> Possible duplicate of #69942

yes it's the same bug.

**Comment by Rubonnek** [comment] 2022-12-15 15:05
Closing as duplicate of #69942.

**Closed by Rubonnek** 2022-12-15 15:05 UTC
