### ISSUE TITLE
color choosing dialog does not respond to clicks when clicking on the right side bar

### ISSUE THREAD

**Issue by lordadamson** [godotengine/godot#3593] opened 2016-02-05 11:07 UTC
![screenshot from 2016-02-05 10-44-43](https://cloud.githubusercontent.com/assets/6195060/12844590/f72ef532-cc08-11e5-8037-c9060f73f820.png)

the right side chooses the color from that rainbow spectrum and then you choose the shade in the middle right? well when I click/drag anywhere on that right side rainbow it doesn't respond. I had to drag the RGB sliders to get the color I wanted.

**Comment by akien-mga** [comment] 2016-02-05 11:14
Looks like it could be a duplicate of #3492, can you check if it's this behaviour that you're having?

**Comment by lordadamson** [comment] 2016-02-05 12:41
yes sir, that's exactly my issue.

**Comment by akien-mga** [comment] 2016-02-05 12:45
Thanks, closing as duplicate then.

**Closed by akien-mga** 2016-02-05 12:45 UTC
Labels: bug, topic:core

**Comment by akien-mga** [comment] 2016-02-09 11:11
Actually this specific part of the broader issue was not fixed, so this one is now a duplicate of #3633.
