### ISSUE TITLE
Hitting enter in Rename Project dialog should rename project (but instead launches project)

### ISSUE THREAD

**Issue by Oranjoose** [godotengine/godot#24391] opened 2018-12-16 05:55 UTC
Godot 3.1 Alpha 3
Windows 10 x64 

![image](https://user-images.githubusercontent.com/15862731/50050518-7c94d300-00cb-11e9-9063-ea707ee7a9c9.png)

In the Project Manager, after typing in a new name while in the Rename Project dialog Project Name field, hitting enter does not accept the new name, but instead goes straight to launching the project without the changed name.

The desirable effect is that the Rename Project dialog is closed, accepting the new project name.

**Comment by akien-mga** [comment] 2018-12-16 12:39
Duplicate of #17620.

**Closed by akien-mga** 2018-12-16 12:39 UTC
Labels: bug, junior job, topic:editor, usability
