### ISSUE TITLE
Cannot Add Tileset Physics Layer (4.0)

### ISSUE THREAD

**Issue by RandomWalrus13** [godotengine/godot#78848] opened 2023-06-29 18:43 UTC
### Godot version

4.0.3

### System information

Windows 10

### Issue description

As I try to add a physics layer to my tileset for collision properties, I am not able to select physics as shown in the picture attached below.
![Screenshot 2023-06-29 134119](https://github.com/godotengine/godot/assets/111152655/545718a9-cb5d-41aa-a86a-9ebe7e717925)

### Steps to reproduce

I have a reproduction product below.

### Minimal reproduction project

[reproduction-product.zip](https://github.com/godotengine/godot/files/11909430/reproduction-product.zip)

**Comment by AThousandShips** [comment] 2023-06-29 18:51
Duplicate of: #75592

You need to add a layer before you can paint with them, this is done in the tileset resource in the inspector

**Closed** 2023-06-29 18:52 UTC
