### ISSUE TITLE
Bluetooth keyboard events not handling echo properly on Android

### ISSUE THREAD

**Issue by GioeleVasile** [godotengine/godot#79051] opened 2023-07-05 08:06 UTC
### Godot version

4

### System information

Android 13

### Issue description

If I go in my game, godot seem to not see the keyboard. I saw my script for errors, but it seem correct. I used a script for move the characters as people show in the tutorials, so it should be correct and I saw it many times. there aren't sinctasys errors.
Godot don't move the characters with bluetooth keyboard.
I went to settings of the projects - imputs for add the buttons to "up, down, left, right". Godot took my buttons, but as physics button. And even in this way the character doesn't move.

### Steps to reproduce

Connect a keyboard.

Create the basic script.

Start the game.

### Minimal reproduction project

This was the script

```gdscript
extends CharacterBody2D
@export var speed: int = 35
func handleInput():
	var moveDirection = Input.get_vector("ui_left", "ui_right", "ui_up", "ui_down")
	velocity = moveDirection*speed
	
func _physics_process(delta):
		handleInput()
		move_and_slide()
```

**Comment by Calinou** [comment] 2023-07-05 11:39
@GioeleVasile Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot. (That is, please upload an entire ZIP file, not just the script.)

**Comment by AThousandShips** [comment] 2023-07-05 12:42
Drag and drop a ZIP archive to upload it. **Do not select another field until the project is done uploading.**

**Comment by GioeleVasile** [comment] 2023-07-05 12:48
> Drag and drop a ZIP archive to upload it. **Do not select another field until the project is done uploading.**
> 
> I'd you're on android you click the area below the text
With "browse" it say "Impossible to find an app for complete the operation". It don't see my app where there are files, the archive, the other options are for photos. I can't attack the files, however if you open a project and copy the script in Bodycharacter2d with a sprite as son you obtained my project for now

**Comment by AThousandShips** [comment] 2023-07-05 12:50
We need more than just the script, the input map, the project settings, etc.

**Comment by GioeleVasile** [comment] 2023-07-05 13:00
[projectgodot 1.zip](https://github.com/godotengine/godot/files/11958099/projectgodot.1.zip)

**Comment by GioeleVasile** [comment] 2023-07-05 13:01
> We need more than just the script, the input map, the project settings, etc.

Try that, in the previouse message. Is it sufficient?

**Comment by bruvzg** [comment] 2023-07-05 18:21
I can reproduce it on Android. `InputEventKey`s from the BT keyboard are received, and are the same as events on desktop, so it's something wrong with action handling (it works on desktop).

**Comment by GioeleVasile** [comment] 2023-07-05 18:37
> 


And what this mean? My character doesn't move, even if I did what the tutorial did.

**Comment by AThousandShips** [comment] 2023-07-05 18:38
It means they can confirm the bug, but that it's unclear what is causing it

**Comment by AThousandShips** [comment] 2023-07-05 18:41
I was talking about the comment by bruvzg above, we are the people who investigate and try to solve bugs, and they or someone else will hopefully find a solution to this

**Comment by bruvzg** [comment] 2023-07-05 19:29
Seems like actions are actually triggering as well, but for example, holding Left produce alternating `(0, -1)` and `(0,0)` vectors instead of constant `(0, -1)`. Probably caused by missing `echo` parameter in Android key events.

**Comment by GioeleVasile** [comment] 2023-07-06 04:44
> Seems like actions are actually triggering as well, but for example, holding Left produce alternating `(0, -1)` and `(0,0)` vectors instead of constant `(0, -1)`. Probably caused by missing `echo` parameter in Android key events.

Howeverc, do you know how to put in a game virtual arrows or pad? For a momentaney solution

**Comment by GioeleVasile** [comment] 2023-07-06 10:02
> Seems like actions are actually triggering as well, but for example, holding Left produce alternating `(0, -1)` and `(0,0)` vectors instead of constant `(0, -1)`. Probably caused by missing `echo` parameter in Android key events.

How can I know when the bug is fixed?

**Comment by GioeleVasile** [comment] 2023-07-06 10:20
> > Seems like actions are actually triggering as well, but for example, holding Left produce alternating `(0, -1)` and `(0,0)` vectors instead of constant `(0, -1)`. Probably caused by missing `echo` parameter in Android key events.
> 
> However, do you know how to put in a game virtual arrows or pad? For a momentaney solution

However there are even other problems. Godot say "Error in 9-5, the slide and moves not found in base self". It said before I fixed it that in 7-1 there was an error. When I click on the start the game button many times it have a veery long load or an infinite loading (now, before the segnalation of the previouse problem no). I need to force to close the program. If it load the sprite normally, and I click on back for return in the screen of the script, it crash.

**Comment by Calinou** [comment] 2023-07-06 12:29
> How can I know when the bug is fixed?

From your perspective, the bug will only be fixed when https://github.com/godotengine/godot/pull/79089 is merged and lands in a stable release.

**Comment by GioeleVasile** [comment] 2023-07-06 12:52
> > How can I know when the bug is fixed?
> 
> From your perspective, the bug will only be fixed when #79089 is merged and lands in a stable release (and you update to the release in question).

How can I implement virtual pad in game while I wait?

**Comment by Zireael07** [comment] 2023-07-06 15:43
@GioeleVasile Lots of tutorials around on how to make a virtual pad. This is not a support forum, this is an issue tracker though.

**Closed** 2023-07-12 12:28 UTC
Labels: bug, platform:android, confirmed, topic:input

**Comment by GioeleVasile** [comment] 2023-07-12 14:43
I noticed someone closed this but for now my character still down't move

**Comment by YuriSizov** [comment] 2023-07-12 15:42
@GioeleVasile Issues are closed when pull requests addressing them are merged. There is no public release that fixes the issue yet.

How did you test? Did you compile from source with the fix applied?

**Comment by GioeleVasile** [comment] 2023-07-12 18:19
> @GioeleVasile Issues are closed when pull requests addressing them are merged. There is no public release that fixes the issue yet.
> 
> How did you test? Did you compile from source with the fix applied?

I simple searched if there was an upgrade and then I tried to move my character, if there was an upgrade

**Comment by YuriSizov** [comment] 2023-07-12 18:40
Then you have to wait, the fix will be available in the upcoming 4.2 dev1 build.

**Comment by GioeleVasile** [comment] 2023-07-16 16:01
But

> Then you have to wait, the fix will be available in the upcoming 4.2 dev1 build.

But how long until the upgrade?

**Comment by GioeleVasile** [comment] 2023-07-29 07:54
> Then you have to wait, the fix will be available in the upcoming 4.2 dev1 build.

It's passed two weeks, how long untill the update?

**Comment by YuriSizov** [comment] 2023-07-31 13:11
@GioeleVasile 4.2 dev1 has been released [2 weeks ago](https://godotengine.org/article/dev-snapshot-godot-4-2-dev-1/), followed up by 4.2 dev2 [late last week](https://godotengine.org/article/dev-snapshot-godot-4-2-dev-2/). You can download a build from [here](https://github.com/godotengine/godot-builds/releases/tag/4.2-dev2) to give it a test.

**Comment by YuriSizov** [comment] 2023-07-31 13:26
> I usually upgrade godot from play store.

This is a dev snapshot, not a stable release. It is only available in Play Store if you join our beta testers group [here](https://groups.google.com/g/godot-testers).

> For Android, what download I need to do in the links you posted?

The one with "android_editor" in the name, whether the APK or the AAB, as you prefer.

**Comment by GioeleVasile** [comment] 2023-08-02 17:14
> I was talking about the comment by bruvzg above, we are the people who investigate and try to solve bugs, and they or someone else will hopefully find a solution to this
> 
> The bug is registered simply by posting here, and we are the people who investigate them :)

Hello,

I downloaded the 4.2 but the character still don't move with my bluetooth keyboard. Have I done something wrong?

**Comment by GioeleVasile** [comment] 2023-08-06 08:43
> > I usually upgrade godot from play store.
> 
> This is a dev snapshot, not a stable release. It is only available in Play Store if you join our beta testers group [here](https://groups.google.com/g/godot-testers).
> 
> > For Android, what download I need to do in the links you posted?
> 
> The one with "android_editor" in the name, whether the APK or the AAB, as you prefer.

Hello,

Have someone red? Because I did as you said but the problem is not resolved.

**Comment by YuriSizov** [comment] 2023-08-07 11:10
@GioeleVasile There is no need to bump the issue. Whenever someone who can guide you through the problem can help you, they will. In the meantime, have you tried asking about this on one of our [community platforms](https://godotengine.org/community/)?

**Comment by GioeleVasile** [comment] 2023-08-14 09:23
> @GioeleVasile There is no need to bump the issue. Whenever someone who can guide you through the problem can help you, they will. In the meantime, have you tried asking about this on one of our [community platforms](https://godotengine.org/community/)?

I asked here because someone said to me this is the place for report bugs. I will search even in other community platforms.

**Comment by Zireael07** [comment] 2023-08-14 09:46
@GioeleVasile This bug was already reported, there is no need to bump further

**Comment by GioeleVasile** [comment] 2023-12-22 07:44
> @GioeleVasile This bug was already reported, there is no need to bump further

Hello, noone answered to me, even in the community. The bug maybe is fixed, but not the problem
