### ISSUE TITLE
Can't set transparent background.

### ISSUE THREAD

**Issue by LSDogX** [godotengine/godot#75425] opened 2023-03-28 14:40 UTC
### Godot version

4.0.1

### System information

Windows10

### Issue description

I've tried every settings about "transparent" to make the main window have a transparent background, but it didn't work.
![1ec2b16e65ff7d2b224c844a33154b0](https://user-images.githubusercontent.com/61925478/228270495-2227671f-e05f-4b5a-b8fa-0f55a94ca2da.png)

Ps: After that I turned back to Godot3, and it just simply worked:
![6e9a6ccddc7e64b63798fc31f28ad15](https://user-images.githubusercontent.com/61925478/228271372-06776f91-6e8e-4114-8083-4911e9fcb10d.png)

### Steps to reproduce

write following code in main scene and run the game
⚠ I forgot to say that **these settings are also set in the Project Settings dialog**
```
func _ready():
	print(DisplayServer.has_feature(DisplayServer.FEATURE_WINDOW_TRANSPARENCY))
	
	DisplayServer.window_set_flag(DisplayServer.WINDOW_FLAG_BORDERLESS, true);
	DisplayServer.window_set_flag(DisplayServer.WINDOW_FLAG_TRANSPARENT, true);
	
	ProjectSettings.set_setting("application/boot_splash/bg_color", Color.TRANSPARENT);
	ProjectSettings.set_setting("display/window/size/transparent", true);
	ProjectSettings.set_setting("rendering/viewport/transparent_background", true);
	ProjectSettings.set_setting("display/window/per_pixel_transparency/enabled", true);
	ProjectSettings.set_setting("display/window/per_pixel_transparency/allowed", true);
	
	get_tree().root.transparent = true;
	get_tree().root.transparent_bg = true;
	
	get_viewport().transparent = true;
	get_viewport().transparent_bg = true;
```
The background will still not be transparent

### Minimal reproduction project

[godot_test.zip](https://github.com/godotengine/godot/files/11090676/godot_test.zip)

**Comment by Calinou** [comment] 2023-03-28 15:10
Project settings are only read when the project starts. You need to set them in the Project Settings dialog, not set their values in `_ready()`.

**Comment by LSDogX** [comment] 2023-03-28 16:22
I changed to the compatibility mode, then all the sprites and texture rects are "invisible"(They are not rendered in the editor), but this time the background is transparent when I run it.
I believe it's my own problem because I asked some friends and their godot is doing it really well, I will try something else and hope to fix it..

**Comment by MegadronA03** [comment] 2023-03-29 18:46
Can't reproduce (4.0.1.stable Windows 10, Nvidia GT 740 473.81)
Same goes for script detach.
![Screenshot (136)](https://user-images.githubusercontent.com/56801003/228637738-3267ce36-9707-403e-bd3b-dcb9fce3616f.png)

**Comment by LSDogX** [comment] 2023-03-29 23:20
> Some old GPUs/drivers which have Vulkan support (2014-2016 GPUs, like AMD Pitcairn) do not have window transparency support for Vulkan, so results might vary. With OpenGL renderer, transparent should work on any supported GPU.

That makes sense, my laptop is pretty old. Thanks for your explanation!

**Comment by Calinou** [comment] 2023-03-30 00:17
Reopening, as this should be documented.

**Comment by Calinou** [comment] 2023-09-13 21:47
Closing in favor of https://github.com/godotengine/godot/issues/76167, as this is due to the same cause. This is not due to the GPU generation, but due to using NVIDIA Optimus (hybrid graphics).

**Closed by Calinou** 2023-09-13 21:47 UTC
Labels: topic:rendering, topic:porting, documentation

**Comment by LSDogX** [comment] 2023-12-10 03:49
![nice try](https://github.com/godotengine/godot/assets/61925478/4fc4dbf4-392a-4987-98d0-4999331b734d)
Surprisingly it's working in Godot 4.2 now! i love u godot😙

**Comment by AThousandShips** [comment] 2023-12-10 13:07
This is likely a different issue then as the other issue is not solved (please see the other issue report for details)

**Comment by LSDogX** [comment] 2023-12-10 13:39
> This is likely a different issue then as the other issue is not solved (please see the other issue report for details)

![image](https://github.com/godotengine/godot/assets/61925478/56249b6f-e379-4945-b50e-7d2a38e2ca5a)
Turns out it was solved by something else, I remember I just updated the nvidia driver recently, for reference the version is 546.17
