### ISSUE TITLE
IPv6 support

### ISSUE THREAD

**Issue by Kermer** [godotengine/godot#4651] opened 2016-05-13 15:42 UTC
It would be nice for Godot Networking to finally support IPv6, especially that most of ISPs begin to use v6 instead of v4 as a base.

With my new modem(router) I can't get the networking to work, since [Godot can't resolve the hostname](https://github.com/godotengine/godot/blob/a895e2e372c9df2a9972f38134ae0ea9c8bf45a8/drivers/unix/ip_unix.cpp#L69) for IPv6 and my supposed IPv4 (which I don't even know how is obtained) doesn't respond to anything.

**Comment by reduz** [comment] 2016-05-13 15:50
I don't live in a country where ipv6 is widespread, so any contributions
welcome

**Comment by Calinou** [comment] 2016-05-13 20:54
My ISP supports IPv6 since a few years now (SFR, France), but I don't have network programming knowledge.

**Comment by punto-** [comment] 2016-05-13 22:45
Does the current API work for an ipv6 implementation at least? Maybe we
need a bigger container for the addresses :p

**Comment by Kermer** [comment] 2016-05-15 15:04
[IP_Address](https://github.com/godotengine/godot/blob/a895e2e372c9df2a9972f38134ae0ea9c8bf45a8/core/io/ip_address.h) is the current address holder, which is 32b union, so expanding this to 128 will be required. The question is how this action alone will affect other functions...
Maybe with some hints I could try to start some work on it.

Following the error from entering IPv6 string in StreamPeerTCP.connect(), we should start in resolving hostname - [`gethostbyname(p_hostname.utf8().get_data())`](https://github.com/godotengine/godot/blob/a895e2e372c9df2a9972f38134ae0ea9c8bf45a8/drivers/unix/ip_unix.cpp#L68) returns NULL for v6 and I'm not sure where this function is defined (is it system or external library?)

Second thing - expanding IP_Address and changing the return value from gethostbyname to correct (size) one.

**Comment by reduz** [comment] 2016-05-15 15:18
I am unaware of how IPV6 works, is it enough with just supporting 128bit
addresses, or is there anything else we must add support for?

**Comment by Kermer** [comment] 2016-05-15 16:24
Probably not. They have shorter header and few other things... But hey, one problem at a time :shipit:

**Comment by punto-** [comment] 2016-05-15 16:40
When does the divergence happen tho? If you have a hostname, you resolve it
and might get an ipv4 address, or ipv6, at that point you decide to connect
using the StreamPeer for that protocol? Or is there a separate resolver for
each protocol? The questions is not about adapting the existing
implementations I think, it's about if the StreamPeer API provides
everything needed to implement one for ipv6, which will be separate from
the current ipv4 one.

**Comment by vnen** [comment] 2016-05-15 16:55
`gethostbyname()` is deprecated in Windows. From [MS Docs](https://msdn.microsoft.com/pt-br/library/windows/desktop/ms738524(v=vs.85).aspx):

> The gethostbyname function can only return IPv4 addresses for the name parameter. The getaddrinfo function and associated addrinfo structure should be used if IPv6 addresses for the host are required or if both IPv4 and IPv6 addresses for the host are required.

So at least for Windows `gethostbyname()` has to be replaced with `addrinfo()`.

**Comment by Kermer** [comment] 2016-05-18 13:04
I peeked into current networking a bit and I think rewriting those files isn't for me. As punto mentioned, creating a separate StreamPeer for v6 would be a start. Rewriting it from scratch, using the old one only as helper, might be even quicker than trying to modify the v4 version. Maybe after that you could try to merge them.

Maybe I'll try my luck with creating some module later on. Using [asio c++ lib](http://think-async.com/) or something like that.

Either way keep in mind that IPv4 might hold on long for intranet, but for internet there might be more traffic through v6 than v4 in a couple of years, so it's worth to support it.

P.S. [Mind that 6to4 exists, but 4to6 doesn't](https://en.wikipedia.org/wiki/6to4)

**Comment by lukaskotik** [comment] 2016-10-09 19:42
https://developer.apple.com/news/?id=05042016a
So for almost all of the mobile games developers support of IPv6 can be quite handy ;)

**Comment by reduz** [comment] 2016-10-09 19:49
@punto- is looking at implementing ipv6 this week

**Comment by Kermer** [comment] 2016-10-09 19:51
Nice! Keep us updated :+1:

**Comment by Disputer** [comment] 2016-10-15 16:41
Here is an official answer from Apple about our application: "Performance - 2.1
We discovered one or more bugs in your app when reviewed on iPad and iPhone running iOS 10.0.2 on Wi-Fi connected to an IPv6 network. We were unable to log in. 

Next Steps:
Please run your app on a device while connected to an IPv6 network (all apps must support IPv6) to identify the issue(s), then revise and resubmit your app for review. 
Resources:
For information about supporting IPv6 Networks, please refer to Supporting IPv6 DNS64/NAT64 Networks and About Networking" :(

**Comment by bojidar-bg** [comment] 2016-10-28 15:27
Done (but a bit broken) on master, so maybe we should close this?

**Closed** 2016-10-31 07:00 UTC
Labels: feature proposal, topic:core

**Comment by vnen** [comment] 2016-10-31 10:06
I think we need another issue about IPv6 on ENet.

**Comment by Kermer** [comment] 2016-10-31 12:36
@vnen - akien just did: #6992

**Comment by FabiGjuzi** [comment] 2016-11-30 09:32
I had the same issue. I dont have any log in form on my game but the only moment when access user internet is the moment when he want to buy something from the store and I am using godot in app purchase. Any idea what should I do for this issue??

Thanks!!!

**Comment by punto-** [comment] 2016-11-30 09:36
What is the issue you have exactly? app store rejecting your game for the
ipv6 reasons? Can you open a separate issue with the exact error message?

**Comment by FabiGjuzi** [comment] 2016-11-30 09:37
yes.......Here is the apple response

Performance - 2.1


We discovered one or more bugs in your app when reviewed on iPad and iPhone running iOS 10.1.1 on Wi-Fi connected to an IPv6 network.

- We were unable to purchase your In App Purchase products because of the error message.

We've attached screenshot(s) for your reference.

Next Steps

Please run your app on a device while connected to an IPv6 network (all apps must support IPv6) to identify the issue(s), then revise and resubmit your app for review.

If we misunderstood the intended behavior of your app, please reply to this message in Resolution Center to provide information on how these features were intended to work.

For new apps, uninstall all previous versions of your app from a device, then install and follow the steps to reproduce the issue(s). For updates, install the new version as an update to the previous version, then follow the steps to reproduce the issue(s).

**Comment by punto-** [comment] 2016-11-30 09:47
Open a new issue with this and attach those screenshots with the actually
error message, I don't think this is related to the IPV6 code
