### ISSUE TITLE
Can't change material of a sprite using script

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#52420] opened 2021-09-05 17:42 UTC
### Godot version

c6f6c05

### System information

W10

### Issue description

```
func _ready():
	var sprite = Sprite2D.new()
	sprite.material = CanvasItemMaterial.new()
```
![image](https://user-images.githubusercontent.com/2223172/132136264-8dbc5c43-c02f-441a-b883-cd0650bbe71c.png)

### Steps to reproduce

Just the script above.

**Comment by EricEzaM** [comment] 2021-09-21 02:57
This appears to happen anywhere a `PROPERTY_HINT_RESOURCE_TYPE` is used with a comma-delimited list of Resource Type options.

![image](https://user-images.githubusercontent.com/41730826/134104870-3889f810-2039-481c-bf80-7ad1e336fb25.png)

**Comment by akien-mga** [comment] 2021-09-21 07:58
Duplicate of #42280.

**Closed by akien-mga** 2021-09-21 07:58 UTC
Labels: bug, topic:gdscript, regression
