### ISSUE TITLE
Game crashes upon mouse enters the window

### ISSUE THREAD

**Issue by Ninjihaku** [godotengine/godot#2093] opened 2015-06-15 11:31 UTC
I'm using godot version 1.1 stable, and installed the latest export scripts. When I export my game with the debug flag enabled (for Windows), it works fine. But when I export the game in release mode, when the mouse cursor enters the game window, the game crashes.

I gave the game to two more people and the two of them experienced the same problem, which is a big problem.

Hovering the mouse cursor during debug mode doesn't display anything relevant about it. But when I am in the editor and I run the game, I get the following error:

**ERROR: set_Stream_peer: Condition ' p_peer.is_null() ' is true.
At: core/io/packet_peer.cpp:288**

I also get another one:

**ERROR: free_static: Condition ' !MemoryPoolStatic::get_singleton() ' is true.
At: core/os/memory.cpp:58**

My system is a Core 2 Duo with 2GB of RAM, the OS is Windows 8.1 x86 (32 bit).

**Comment by akien-mga** [comment] 2015-11-11 10:26
Potentially a duplicate of #1868.

Haven't heard about Windows issues for a while, is this still valid in the current master branch/with nightly builds?

**Comment by akien-mga** [comment] 2015-12-04 15:14
Closing as duplicate of #1868.

**Closed by akien-mga** 2015-12-04 15:14 UTC
Labels: archived, bug, platform:windows, topic:porting
