### ISSUE TITLE
Strange interactions with duplicated child node on instanced node

### ISSUE THREAD

**Issue by literalcitrus** [godotengine/godot#14680] opened 2017-12-14 23:57 UTC
Windows 10, Godot 2.1.4

**Issue description:**
Strange UI/interaction glitches when a child node is added to a instanced node, and then a node with the same name is added to the scene of the instanced node itself.

**Steps to reproduce:**

1. Instance a scene onto a node.
2. Enable editable children
3. Add child node to the instanced node in the scene it was just added to
4. Open the scene of the instanced node and add a node with the same name, save scene
5. Return to original scene, both nodes will be present. Clicking one will "select" both.

This works with regular nodes, instanced scenes, as well as nodes of different types (the inspector shows the details of the child node that is in the instanced scene in the case where nodes are different).

**Link to minimal example project:**
[ChildNodeBug.zip](https://github.com/godotengine/godot/files/1561151/ChildNodeBug.zip)

**Comment by akien-mga** [comment] 2018-09-18 08:58
Still reproducible in the current master branch (f148e8eede).

**Comment by akien-mga** [comment] 2020-06-20 21:35
Closing as duplicate of #26390.

**Closed by akien-mga** 2020-06-20 21:35 UTC
Labels: bug, topic:editor
