### ISSUE TITLE
[Suggestion] Ability to detach the code editor from the main window

### ISSUE THREAD

**Issue by mthreis** [godotengine/godot#20172] opened 2018-07-15 09:33 UTC
**Issue description:**
It's a limitation of regular text editors (like VS Code or Atom): they can't reproduce Godot editor's functionality when it comes to auto-completion and/or syntax checking (for identation, for example). There doesn't seem to be a replacement for the code editor but, unfortunately, it's a chore to work with it since it takes too much screen space on the IDE, especially considering that there's a bar at the left corner that can't be minimized and a script list that can't be turned into tabs. Result: not too much room for what really matters, the code!

A possible solution would be adding a button next to the "distraction free mode" one that would detach the code editor from the main window, giving it one for itself. When the code editor is in a different window, the "Script" could or be removed or lead to that other window when clicked. The result would look somewhat like this:

![sda](https://user-images.githubusercontent.com/31781227/42732482-d0b9e84a-87f8-11e8-82dc-4a18e58860fc.png)

**Comment by swarnimarun** [comment] 2018-07-15 09:45
There is already a few threads on the matter, https://github.com/godotengine/godot/issues/19197

**Comment by vnen** [comment] 2018-07-15 17:31
It is a duplicate of #9059

**Closed by vnen** 2018-07-15 17:31 UTC

**Comment by CyberGh0st-droid** [comment] 2023-03-17 18:38
was this ever implemented?
