### ISSUE TITLE
Editor Crash on png drag and drop

### ISSUE THREAD

**Issue by dubajj** [godotengine/godot#73235] opened 2023-02-13 17:54 UTC
### Godot version

 4.0 RC1

### System information

Windows 10, NVIDIA GeForce GTX 1660 Ti (27.21.14.5751), AMD Ryzen 9 3900XT 12-Core Processor  3.79 GHz, 48GB RAM

### Issue description

Dragging any png asset into the *FileSystem* tab immediately crashes the editor. I can reproduce this with new empty projects and large existing projects.
![godot_crash_import_png_empty_project](https://user-images.githubusercontent.com/223864/218534284-48bfc2e7-d4f1-407a-82e1-4c8cfc8a738f.gif)

### Steps to reproduce

1) Create a new project (with any renderer) with Godot 4.0 RC1 with no settings changed
2) Drag a png into the "FileSystem" tab under "res://"
3) Godot has now hung and if you click anywhere in the UI it crashes out to the OS crash handler.

### Minimal reproduction project

N/A (use an empty new project)

**Comment by YuriSizov** [comment] 2023-02-13 18:10
Duplicate of https://github.com/godotengine/godot/issues/53871.

**Closed by YuriSizov** 2023-02-13 18:10 UTC
