### ISSUE TITLE
`hint_normal` in a shader destroys the alpha channel on re-import

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#19223] opened 2018-05-28 15:30 UTC
Godot 3.0.2

I am packing bump into my normal map. So I have RGB used for normals, and A for bump, this way I save one texture fetch in the fragment shader, for each texture.
Then, I figured I would use `hint_normal` because that's what the texture mostly contains.
Then Godot re-imported my texture, and by doing so, got rid of the alpha channel.

Given the fact I had no problem initially by NOT using `hint_normal`, I'm not sure if that's can be considered a bug. But is there any problem I would not be aware of by not using the hint?
(also that might be a problem with SpatialMaterials if using the same packing trick, unless the user disables auto-conversion)

**Comment by reduz** [comment] 2018-09-07 15:17
Not a bug, if the texture is used for normal mapping, then you don't want the alpha channel.
If you don' t want this behavior, then change the import settings for the texture.
Closing.

**Closed by reduz** 2018-09-07 15:17 UTC
Labels: bug, topic:rendering
