### ISSUE TITLE
Importing project with HDR texture taking too long

### ISSUE THREAD

**Issue by telmotrooper** [godotengine/godot#73627] opened 2023-02-20 14:47 UTC
### Godot version

4.0.rc2.official [d2699dc]

### System information

OS: Arch Linux, CPU: i7-3770, GPU: Radeon RX 570

### Issue description

In Godot 3, importing a project with an HDR texture of size 4096x2048 was pretty much instantaneous, while in Godot 4.0 RC 2 it takes (in my computer) **almost 6 minutes**.

For reference, I've prepared two equivalent projects, both have only a 3D scene with a WorldEnvironment, loading the texture as a panorama sky:

![image](https://user-images.githubusercontent.com/9438853/220136663-fd3c3d52-db14-48f0-9e2d-b9758cae960b.png)

I'm not sure if this is a bug or if the default settings for importing textures are way too demanding now. My CD pipeline is timing out when trying to export a Godot 4 project and it's likely that it has to do with this issue.

If this is intended behavior, feel free to close the issue, though I'd appreciate if someone could tell me whether there's something I can do to reduce this import time.

### Steps to reproduce

Just load the projects attached.

### Minimal reproduction project

[godot_projects.zip](https://github.com/godotengine/godot/files/10785340/godot_projects.zip)

**Comment by akien-mga** [comment] 2023-02-20 14:59
Duplicate of #72666. This is fixed in RC2 already, but you have to remove the corresponding `.import` files, or change the import setting manually.

**Comment by akien-mga** [comment] 2023-02-20 15:12
Are you sure that you didn't use RC 1?

In the MRP, I can reproduce the issue because the `casual_day_4k.hdr.import` file uses VRAM compression which seems to be very slow to compress, as outlined in #72666.

If I delete that file (and the `.godot` folder for good measure) and open in 4.0 RC 2, the import is instantaneous, since no compression is done.

**Comment by telmotrooper** [comment] 2023-02-20 15:13
@akien-mga Yup, been using RC 2 since it was out and just created the project on it:
![image](https://user-images.githubusercontent.com/9438853/220143321-d9ea79da-3f94-46c0-b062-1ece16d4c9a6.png)

**Comment by telmotrooper** [comment] 2023-02-20 15:18
@akien-mga Any chance this is related to the Linux build of 4.0 RC 2?

**Comment by akien-mga** [comment] 2023-02-20 15:31
I'm using the Linux build of 4.0 RC 2 too.

I can reproduce the issue too when copying `main.tscn` and `casual_day_4k.hdr` in a new project. The initial import is fast, but opening `main.tscn` triggers a new slow import. Somehow the WorldEnvironment must be forcing some import settings.

**Comment by Calinou** [comment] 2023-02-20 16:06
>  Somehow the WorldEnvironment must be forcing some import settings.

This is likely **Detect 3D** logic, which should be modified to use Lossless compression for HDR textures until the HDR VRAM compressor performance issue is fixed.

**Comment by clayjohn** [comment] 2023-02-20 18:45
Duplicate of https://github.com/godotengine/godot/issues/61948

**Closed by clayjohn** 2023-02-20 18:45 UTC
Labels: bug, topic:editor, confirmed, topic:import, topic:3d, performance
