### ISSUE TITLE
Bad mixing of animations and missing bones from some imported .glb files

### ISSUE THREAD

**Issue by jcarlosrc** [godotengine/godot#59176] opened 2022-03-15 20:20 UTC
### Godot version

4.0 alpha 4

### System information

Windows 10

### Issue description

I have imported a model from Blender in .glb format. In Godot, I have artifacts when mixing animations using an AnimationTree node. Also, there is a bone missing. Both problems can be seen when comparing with Godot 3.4. Below a comparison: Godot 3.4 (first), Godot 4Alpha 4 (second). We can see the armature strangely going down when mixing idle and walking animations. Also, ArmPole.R missing in the armature.

![Godot3 4-correct](https://user-images.githubusercontent.com/8985409/158463036-d7046169-bfca-4933-9ad6-c2f1925838cc.gif)
![Godot4Alpha4-mix_animation_bug](https://user-images.githubusercontent.com/8985409/158463158-35b73e94-ea82-4506-ab08-aac2ccadcae7.gif)

![Godot3 4](https://user-images.githubusercontent.com/8985409/158463271-943fa7e7-7830-4bd1-aef5-693712cd6512.png)
![Godot4Alpha4](https://user-images.githubusercontent.com/8985409/158463267-af74c272-dccf-45c8-ba06-25adca86fe2d.png)

### Steps to reproduce

Import an armature from Blender and use an Animation Tree node to mix animations. However, it does not occur with all imported armatures. The minimal project contains the armature which shows the bug.

### Minimal reproduction project
[BugReportAlpha4_animations.zip](https://github.com/godotengine/godot/files/8257056/BugReportAlpha4_animations.zip)

**Comment by Calinou** [comment] 2022-03-15 20:24
@jcarlosrc Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

**Comment by jcarlosrc** [comment] 2022-03-15 21:00
> @jcarlosrc Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

Done.

**Comment by TokageItLab** [comment] 2022-03-16 01:07
Blend issue is Dupe of #55838, and the behavior of bone lacking is not a bug, it is Blender's exporter issue #32393.

**Closed by TokageItLab** 2022-03-16 01:07 UTC
Labels: bug, needs testing, topic:import, regression, topic:animation, topic:3d

**Comment by TokageItLab** [comment] 2022-03-16 01:23
@jcarlosrc If you have a reproducible process that is definitely missing bones for the importer, please open a new Issue. At that time, please attach the version you imported, the OS, and if possible, the project for each version.

**Comment by TokageItLab** [comment] 2022-03-16 01:28
@jcarlosrc Looking back at your screenshot, you said the bones are missing, is that the AniamtionTree filter?
Maybe it's just that the animation optimizer deleted the track during the import process, so it doesn't show up in the list of filters. Try disabling the optimizer.

**Comment by jcarlosrc** [comment] 2022-03-16 02:24
It is indeed the optimizer, my fault. The bad mixing is there though. If it is duped of #55838 I cannot see it clearly but it is ok. Thanks.

**Comment by TokageItLab** [comment] 2022-03-16 08:09
> If it is duped of https://github.com/godotengine/godot/issues/55838 I cannot see it clearly but it is ok.
Sorry, more appropriate is #54407, and I think it will be fixed #57675. Thank you for replying.
