### ISSUE TITLE
ScrollBar theming is broken

### ISSUE THREAD

**Issue by ykoc** [godotengine/godot#22252] opened 2018-09-19 15:22 UTC
Godot version: 3.1 Alpha 1 (and any other versions of 3.1 up to that of 18.09)
MS Windows 7 x64

In a theme editor attached theme for a ScrollBar looks absolutely correct, but not in running project.
1) Running non-themed  project 
result of 
SomeScrollContainer.get_v_scrollbar().rect_size.x
is 12
the same container with theme set returns 32 - what is the reason and background of that change?
2) ScrollBar within ScrollContainer seems to ignore Expand Margin property (in case of VScrollBar it fits fully in the height of non-themed bar but this is not correct behavior having Expand Margin at both top and bottom at 14)
[scroll theme.zip](https://github.com/godotengine/godot/files/2397670/scroll.theme.zip)

**Comment by ykoc** [comment] 2018-09-19 23:41
Update (made some experiments)
1) all of mentioned above is happening if i set theme as a default theme for a project
2) if i set theme to a root node of scene something different happens: 
-  get_v_scrollbar().rect_size.x returns 14 (this is the size of scroll style item texture )
- Expand margin is not ignored - but areas outside ScrollContainer bounding box are simply clipped

**Comment by akien-mga** [comment] 2019-01-23 19:33
Is this still reproducible in the current master branch?

**Comment by ykoc** [comment] 2019-01-23 22:03
> Is this still reproducible in the current master branch?

Still the same behavior. 
![image](https://user-images.githubusercontent.com/35262366/51639668-8df6b800-1f72-11e9-850f-e51645352247.png)
this is what I have in theme editor frame
![image](https://user-images.githubusercontent.com/35262366/51639760-c1394700-1f72-11e9-955c-642eb9e9e277.png)
this is what I have in-game if I set theme to some node (textures scales normally but are clipped)
![image](https://user-images.githubusercontent.com/35262366/51639896-1aa17600-1f73-11e9-8d50-2a2adf271d8b.png)
and now I set the same theme as custom theme for full project (textures scales... strangely but now full scrollbar is resized to fit into box taking most of Expand Margins into account - still one or two rightmost pixels of the grabber are clipped)

**Comment by georgwacker** [comment] 2019-11-20 17:12
To expand on the theming issues, `ScrollBar `seems to be very picky about the allowed style combinations. The `Grabber`s can be set with `StyleBoxFlat`, but then when you try to remove the `Scroll `property with a `StyleBoxEmpty`, the `Grabber `does not render anymore. The Editor still shows it, unless you reload the scene. Running the scene does not show it, however.
What you have to do right now is set them to `StyleBoxTexture `and actually assign an empty texture image. The code that creates the Editor Theme currently does the same and has an empty texture file for `Scroll`. It would be great to just support `StyleBoxEmpty `for it.

For pixel art games with super low resolutions (320x180) there currently does not seem to be a way to change the width of the scrollbars in a `ScrollContainer`. Even when you set the `Grabber `to a `StyleBoxTexture `with 2x2px, it just gets stretched to the default size.
To get 1-2px wide scrollbars in my project, I am currently using a `StyleBoxFlat `with `Draw Center` disabled and a Left Border Width set to 1. Doing it that way, the border is always either on the left or right of the actual scrollbar position.
It would be nice to just have a width property in the theming options for `ScrollBar`.

**Comment by Calinou** [comment] 2019-12-06 00:12
I can confirm this on commit https://github.com/godotengine/godot/commit/e9eea4f3ce5447fca68d60e520f925f2af94217c.

**Comment by KoBeWi** [comment] 2019-12-30 21:01
Any complete reproduction project for this? The attached theme doesn't load.

**Comment by KoBeWi** [comment] 2020-12-09 00:24
Closing due to lack of update. Please comment if you can still reproduce this issue in the latest stable version of Godot.

**Closed by KoBeWi** 2020-12-09 00:24 UTC
Labels: bug, confirmed, topic:gui

**Comment by HGCollier** [comment] 2021-07-12 20:47
I'm having a similar issue where the content margin is working for top and bottom but not left and right, has this been resolved/has is it ever planned to be?
![image](https://user-images.githubusercontent.com/25365699/125353732-d086f780-e35a-11eb-930e-1d8bc022f7b4.png)

**Comment by KoBeWi** [comment] 2021-07-12 20:56
@HGCollier Can you attach some theme affected by this bug?

**Comment by HGCollier** [comment] 2021-07-12 21:09
> @HGCollier Can you attach some theme affected by this bug?

Just found a solution, although its not amazing. Ended up just adding some whitespace around my grabber texture. Tried attaching my `.tres` theme file but it's not supported. What would be the best way to go about attaching it?

**Comment by KoBeWi** [comment] 2021-07-12 21:42
> What would be the best way to go about attaching it?

Put it into a zip or change extension to `.txt`.
