### ISSUE TITLE
GDScript subresources do not save correctly when owner is custom resource

### ISSUE THREAD

**Issue by Benpaste** [godotengine/godot#88894] opened 2024-02-27 04:59 UTC
### Tested versions

- Reproducible in 4.2.1.stable

### System information

Godot v4.2.1.stable - Windows 10.0.19045 - Vulkan (Forward+) - dedicated AMD Radeon RX 5700 (Advanced Micro Devices, Inc.; 31.0.24002.92) - AMD Ryzen 5 3600 6-Core Processor (12 Threads)

### Issue description

When a custom Resource contains an exported GDScript, many of the ordinary methods for saving edits to that script file stop working.

WHAT DOES NOT WORK:
- Ctrl + S
- Ctrl + Alt + S (save script)
- Shift + Alt + S (save all)
- right-clicking on the script in the Scripts Panel and clicking "Save"
- clicking "Save" on the dropdown for the exported GDScript, in the parent resource's Inspector window.
- ***Running the project***
- Quitting the project - this results in a "Save changes before quitting?" dialogue that reappears every time you press "Save & Quit"

WHAT DOES WORK:
- Closing the script from the Scripts Panel (prompts a "Close and save changes?" dialogue). Works ONCE and will not save further edits.
- Clicking "Save" on the parent resource in the Inspector.

### Steps to reproduce

1. Create a new GDScript file, `resource_class.gd`.

`extends Resource`
`class_name CustomResource`
`@export var custom_script: GDScript`

2. Create a new instance of this resource, `resource_instance.tres`.
3. Navigate to `resource_instance.tres`'s Inspector tab, click on Custom Script and click New GDScript.
4. Type "Hello World" in the new Custom Script. Press Ctrl+S to save.
5. Observe that the exported script's name in the Scripts Panel changes from `[unsaved](*)` to `new_resource.tres::GDScript_xxxxx(*)`.
6. Observe that pressing Ctrl+S does not save any changes to the Custom Script. Opening `resource_instance.tres` in a text editor will confirm that no changes are being saved.

### Minimal reproduction project (MRP)

[Export Script Saving MRP.zip](https://github.com/godotengine/godot/files/14414536/Export.Script.Saving.MRP.zip)

**Comment by KoBeWi** [comment] 2024-02-27 12:17
Looks like duplicate of #86696?

**Comment by Benpaste** [comment] 2024-02-27 21:18
It is, thank you. Wasn't able to find it via search but that describes my problem exactly

**Comment by akien-mga** [comment] 2024-02-27 23:02
Consolidating in #86696.

**Closed by akien-mga** 2024-02-27 23:02 UTC
Labels: bug, topic:editor
