### ISSUE TITLE
Marking animation as loop in Editor does not work. We have to set loop = true in code.

### ISSUE THREAD

**Issue by jcarlosrc** [godotengine/godot#39526] opened 2020-06-14 00:11 UTC
**Godot version:**

Beta 3.2.2-beta4 for Windows.

**OS/device including version:**

Windows 10

**Issue description:**

I marked animations as loop in Editor. They play as expected in the Editor. However, they stop in the game. I have to set them to loop in code to work.

**Steps to reproduce:**
In the included code, check Cube scene *check_loop_bug* boolean to *true* and play the game. We can see animations not looping. When this boolean is *false* game works as expected because loop is set in code.

**Minimal reproduction project:**
Here it is:
[Bug-Report-Loop.zip](https://github.com/godotengine/godot/files/4775681/Bug-Report-Loop.zip)

**Comment by Sl3dge78** [comment] 2020-06-17 14:40
I was able to reproduce on 3.2 branch 7f67674 but doesn't seem to happen anymore on master 84e7552 Windows 10

**Comment by Sl3dge78** [comment] 2020-06-17 15:09
This is the same issue as #20467
The animation Player in the given scene is imported from the .glb file.

**Comment by Kayomn** [comment] 2021-01-14 01:29
Can confirm this problem is still present in 3.2.3 with both GLB and FBX.

**Comment by Kayomn** [comment] 2021-01-14 18:42
Temporary workaround for anyone who encounters this issue.

Export your animations with a `-loop` suffix on the respective animation clip for your model and Godot will automatically import it as a looping clip.

**Comment by akien-mga** [comment] 2022-04-06 22:25
Duplicate of #34394

**Closed by akien-mga** 2022-04-06 22:25 UTC
Labels: bug, topic:editor, confirmed

**Comment by doublesob** [comment] 2022-10-16 19:06
> **Godot version:**
> 
> Beta 3.2.2-beta4 for Windows.
> 
> **OS/device including version:**
> 
> Windows 10
> 
> **Issue description:**
> 
> I marked animations as loop in Editor. They play as expected in the Editor. However, they stop in the game. I have to set them to loop in code to work.
> 
> **Steps to reproduce:** In the included code, check Cube scene _check_loop_bug_ boolean to _true_ and play the game. We can see animations not looping. When this boolean is _false_ game works as expected because loop is set in code.
> 
> **Minimal reproduction project:** Here it is: [Bug-Report-Loop.zip](https://github.com/godotengine/godot/files/4775681/Bug-Report-Loop.zip)

Same issue. How to loop it in code?
