### ISSUE TITLE
CSG missing UV2

### ISSUE THREAD

**Issue by SuperDIMMaX** [godotengine/godot#39972] opened 2020-06-30 05:06 UTC
**Godot version:**
Any?

**OS/device including version:**
Any?

**Issue description:**
CSG not have UV2. and no have Vertex Color

**Steps to reproduce:**
Example minimal code:
```
var mdt = MeshDataTool.new()
mdt.create_from_surface(mesh, 0)
for i in range(mdt.get_vertex_count()):
	mdt.set_vertex_uv2(i,Vector2(1,1))
mdt.commit_to_surface(mesh)
```

`mdt.set_vertex_uv(i,Vector2(1,1))` - is working

And can be add Vertex color? (interpolation resolver)

For logical and perfomance reason, this need additional check boxes to editor and parametr in code.

**Comment by akien-mga** [comment] 2020-06-30 05:51
Godot version:
Any?

So you don't know what Godot version(s) you tested...?

**Comment by SuperDIMMaX** [comment] 2020-06-30 06:21
> > Godot version:
> > Any?
> 
> So you don't know what Godot version(s) you tested...?
_Any?_ - this is any version 3 and 4 (v2 - not have CSG)
3.2 lastest costom build with CSG fix https://github.com/godotengine/godot/pull/39956
And i not see in 3.x and master branch in sources of CSG - UV2.

**Comment by akien-mga** [comment] 2020-06-30 09:53
CC @madmiraal

**Comment by SuperDIMMaX** [comment] 2020-06-30 10:16
This issue is independed on this issue https://github.com/godotengine/godot/issues/39919

Probality you can direct copy data as `surface_get_arrays()` .

**Comment by madmiraal** [comment] 2020-06-30 10:59
> CSG not have UV2. and no have Vertex Color

This is true. However, this is not a bug. If this is desired, please create a new feature proposal in the dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker, where it can be discussed and reviewed and the community can assess the validity of the proposal for the engine. This issue log is now solely dedicated to bug reports and Pull Requests.

> probality need "cleanup" functions - delete dublicate vertex(not sure, but...) blender delete 916 dublicated vertex in test project

Blender is a far better tool for creating 3D assets. The CSG tool is provided to enable rapid prototyping. That been said, the way it works at the moment is to use the current faces to calculate the new faces. This helps when you only want to update the faces of the objects you're changing, but it does result in the excess faces you see. However, closing and reopening the scene will recreate only the faces required. Furthermore, it keeps all the individual objects separate, so faces that can be merged between objects are not. Again this is to facilitate moving individual objects without recalculating the entire scene.

Again, if you want to see these features in Godot, please create an issue in the ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker.

**Closed by madmiraal** 2020-06-30 10:59 UTC
Labels: bug, topic:core
