### ISSUE TITLE
Y axis flickers when orbiting center of node3d scene

### ISSUE THREAD

**Issue by andersmmg** [godotengine/godot#55847] opened 2021-12-12 06:25 UTC
### Godot version

4.0-dev.20211210

### System information

Windows 10, GTX 1650

### Issue description

The green y-axis line flickers while orbiting the center of a scene with a Node3D as the root. 
I didn't notice flickering orbiting anywhere but dead center, so moving around makes it go away until camera is moved to center again (for example pressing F)

### Steps to reproduce

Create a new scene
Orbit the center, there should be no flickering
Create a root Node3D
Orbit center, flickering ensues

**Comment by Chaosus** [comment] 2021-12-12 06:41
Duplicate of https://github.com/godotengine/godot/issues/37016

**Closed by Chaosus** 2021-12-12 06:41 UTC
