### ISSUE TITLE
Godot need OpenGL 3.1 to open

### ISSUE THREAD

**Issue by nikhilCad** [godotengine/godot#26822] opened 2019-03-09 06:34 UTC
**Godot version:**

godot 3.1 rc1

**OS/device including version:**

Windows 7 64  bit
OpenGL 2.1

**Issue description:**

This version necessarily needs opengl 3.1 to open. Previous versions atleast opened and I was getting an option to choose GLES2 or GLES3 for my project. But now I get this:
![image](https://user-images.githubusercontent.com/47214394/54067209-7bef8100-4263-11e9-8ce4-a589aa4c471c.png)

**Steps to reproduce:**
Open Godot rc1 on old hardware.

**Minimal reproduction project:**

**Comment by nikhilCad** [comment] 2019-03-09 06:40
![image](https://user-images.githubusercontent.com/47214394/54067276-37b0b080-4264-11e9-8683-40d40c8ada9a.png)
This is from godot 3.1 beta 11. Opening without any issues. But not anymore!

**Comment by jimmyjonezz** [comment] 2019-03-09 06:57
Yes, me too. It's so bad. I have Intel G45 (support shader 2.1). I know, it's graphic card very old, but i love Godot...

**Comment by nikhilCad** [comment] 2019-03-09 07:29
Does this mean that the editor will open with OpenGL 3.1 only?

**Comment by JFonS** [comment] 2019-03-09 07:33
Closing as duplicate of #26806.

@nikhilCad it's just a bug and it will be fixed in the next release candidate.

**Closed** 2019-03-09 07:33 UTC
