### ISSUE TITLE
Project Manager Crash when Templates tab Selected

### ISSUE THREAD

**Issue by Bat-Computer** [godotengine/godot#19598] opened 2018-06-16 11:59 UTC
Godot version: 3.03

OS/device including version: Windows 10 64bit Home Build 1803**
Nvidia GeForce GTX 750 Ti (2GB)

Issue description:
Project Manager Crash when Templates tab Selected

How to Reproduce:
Select Project Manager when Godot starts, then click Templates Tab. Several errors are generated in the console regarding a .png file.

Error in Console:
ERROR: _png_error_function: Not a PNG file
At: drivers/png/image_loader_png.cpp:62
libpng error: Not a PNG file...

**Comment by TailyFair** [comment] 2018-06-16 12:14
duplicate of https://github.com/godotengine/godot/issues/19336

**Comment by vnen** [comment] 2018-06-16 18:01
Closing as duplicate.

**Closed by vnen** 2018-06-16 18:01 UTC
