### ISSUE TITLE
(Re)importing Assets (jpegs and png) very slow on linux

### ISSUE THREAD

**Issue by dodgyville** [godotengine/godot#18990] opened 2018-05-18 00:55 UTC
**Godot version:**
3.x (master)

**OS/device including version:**
Ubuntu 17.10, 18.04

**Issue description:**
When add a new model to the project by copying the files into the directory structure, the auto-import starts to (re)import the texture images (stored in PNG or JPG). This can take several minutes per image. 
In the terminal the following lines get outputted per image:

begin encoding, format: ETC2_RGB8
time encoding: 45386

Is there some way to speed this up? Perhaps by pre-encoding the image files before importing into godot?

**Comment by Zireael07** [comment] 2018-05-18 07:43
This is not limited to Linux and I believe it's simply the way ETC2 format works. Untick ETC2 in project settings to see a speedup.

**Comment by bojidar-bg** [comment] 2018-06-03 12:20
Marking as duplicate of #10583, similar to how #10880 was. It would be less of a hassle when reimporting goes in the background.

**Closed by bojidar-bg** 2018-06-03 12:20 UTC
