### ISSUE TITLE
Shader code: Declaring a uniform array after a uniform bool causes the array to not function.

### ISSUE THREAD

**Issue by InfuriatedBrute** [godotengine/godot#54680] opened 2021-11-06 19:03 UTC
### Godot version

[v4.0.dev.20211015.official.f113dc986](https://downloads.tuxfamily.org/godotengine/testing/4.0/4.0-dev.20211015/)

### System information

Windows 11, Vulkan, Nvidia Geforce RTX 3050

### Issue description

In a .gdshader file, declaring a uniform array at any point after declaring a uniform boolean causes the uniform array to not function. Specifically, you can set and get the uniform array from a script as normal, but inside the shader code it will function as though it is filled with zeroes.

### Steps to reproduce

Create a TextureRect with a Shader and a Script. In the shader code, declare a uniform array, and discard a fragment if the first item in the array is >= 0.1. In the script, set that array so that its first element is 1. Note that when you run the program, the TextureRect will now not render. Now declare a uniform bool above the uniform array, and it will render.

### Minimal reproduction project

[minimal-uniform-arrays.zip](https://github.com/godotengine/godot/files/7491092/minimal-uniform-arrays.zip)

**Comment by Calinou** [comment] 2021-11-06 19:12
Duplicate of https://github.com/godotengine/godot/issues/54657.

**Closed by Calinou** 2021-11-06 19:12 UTC
