### ISSUE TITLE
TextEdit current line has highlighting artifacts when word wrap is enabled

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#32610] opened 2019-10-06 23:58 UTC
Godot 3.1.1

When word wrapping is enabled, text edit's current line has highlighting artifacts when the line is within a wrapped row:

![image](https://user-images.githubusercontent.com/1311555/66278037-757ac380-e89d-11e9-963d-ec422052a532.png)

Notice the `get_nod` getting a brighter highlight. This happens in the script editor and regular text edits in game. There is no selection here.
Note: my current line highlighting color is `r=255, g=255, b=255, a=18`

**Comment by Anutrix** [comment] 2020-01-09 17:46
Can you tell me a way to reproduce this? Couldn't reproduce it.

**Comment by Zylann** [comment] 2020-01-09 18:25
Looks like it's not reproducing in Godot 3.2 beta5.

**Comment by Anutrix** [comment] 2020-01-09 19:55
I can reproduce in 3.1.1 but not nearly latest master 8ece49bf04c8d12683db717c3419d90ff88c0b57.

**Comment by akien-mga** [comment] 2020-01-09 20:12
Closing as fixed then.

**Closed by akien-mga** 2020-01-09 20:12 UTC
Labels: bug, topic:gui
