### ISSUE TITLE
Android editor does not switch to the editor view when the project encounters a script error

### ISSUE THREAD

**Issue by Booklight12** [godotengine/godot#77272] opened 2023-05-20 08:02 UTC
### Godot version

4.1 dev

### System information

Android

### Issue description

I understand that the development team wants to solve the problem that breakpoints and other functions cannot be used properly on Android, but you seem to have forgotten to switch Windows. When the program has problems, the computer end will jump to the editing page of the engine, while the mobile end is directly stuck in the execution page of the program, and you can only exit by crossing out the background.

### Steps to reproduce

Create a new project on the mobile side, prepare a faulty gdscript ready function, and see what happens

### Minimal reproduction project

null

**Comment by Booklight12** [comment] 2023-05-20 08:23
I think the normal logic would be something like this: There is a problem -> Go back to the engine edit page and display the error message and memory information. Just like on the computer side

**Comment by Booklight12** [comment] 2023-07-12 04:41
This issue is still not fixed in the latest release

**Comment by Booklight12** [comment] 2023-07-30 17:12
I hope the authorities haven't forgotten the problem

**Comment by m4gr3d** [comment] 2023-11-15 15:39
Duplicate of https://github.com/godotengine/godot/issues/77966

**Closed** 2023-11-15 15:40 UTC
Labels: bug, platform:android, topic:editor, confirmed
