### ISSUE TITLE
VS Code permanently loses the connection to the GDScript language Server

### ISSUE THREAD

**Issue by okapii** [godotengine/godot#34147] opened 2019-12-06 15:21 UTC
**Godot version:**
v3.2.beta3.official

**OS/device including version:**
Mac OS 10.15.1

**Issue description:**
VS Code loses the connection to the language server multiple times per hour. After some time intellisense stops working which can be fixed by restarting Godot and manually reestablishing the connection. Curiously not all features stop working at once. Oftentimes the tooltips disappear first, then ctrl-space stops working and eventually the symbols overview is gone. Godot can't be just quit in these situations, instead one has to _kill_ the process. This seems to me to indicate that the issue might not be caused by the VS Code extension but by Godot. I however [reported this for the VS Code extension](https://github.com/godotengine/godot-vscode-plugin/issues/111) already, too.

An interesting side effect maybe worth knowing is the fact that the status in the bottom right corner of VS Code never stops saying "Initializing". That's the case even if everything seems to work as intended. Clicking the status opens the flyout where it in turn says "Connected to GDScript language Server" – but it still keeps saying that once things stopped working.

**Steps to reproduce:**
Sadly I haven't figured out a way to reliably reproduce this, yet. The only thing I noticed so far is the fact that one can shorten the time until the issue appears by triggering many actions like showing the tooltips using `<cmd>-<k> <cmd>-<i>` or `<ctrl>-<shift>`.

**Minimal reproduction project:**
–

**Comment by akien-mga** [comment] 2019-12-06 17:28
CC @Geequlim

**Comment by Geequlim** [comment] 2019-12-07 02:32
Sorry I can't reproduce this.

**Comment by Geequlim** [comment] 2019-12-07 03:33
@okapii Can you get any console error message from the godot editor ?

**Comment by Geequlim** [comment] 2019-12-07 04:42
> An interesting side effect maybe worth knowing is the fact that the status in the bottom right corner of VS Code never stops saying "Initializing". 
This is a bug of the new version of VSCode I have reported to the VSCode repo https://github.com/microsoft/vscode/issues/86508

**Comment by okapii** [comment] 2019-12-14 10:20
@Geequlim Sorry for the late reply. It was a busy week. Just installed the new beta, which fixes the connection status-display for me.

Sadly there don't appear any console error messages in Godot's editor when the connection gradually gets lost.

**Comment by npretto** [comment] 2019-12-24 14:08
Another Catalina user here, same problem but worse: i tried with multiple versions/betas of godot but i can't get the autocompletion on vscode to work for more than a minute or two.

No errors in the console i opened godot editor with.

If there's anything I can do to help debug this I'm here

**Comment by Geequlim** [comment] 2019-12-25 01:42
So this problem is only happen on macOS ?

**Comment by okapii** [comment] 2019-12-25 18:50
I have no way to confirm that it isn't happening on non MacOS systems but obviously the two exiting reports are for MacOS.

**Comment by TicklesTheBrain** [comment] 2020-01-09 08:18
I am experiencing the same problem on Windows 10. In addition to that, when the connection between VSCode and Editor dies, the Godot Editor will crash on exit.

I have not found a reliable way to reproduce this, but I could try to look for error messages if I knew where :) The Editor Console doesn't seem to have anything useful, though :(

**Comment by obsoke** [comment] 2020-01-10 03:03
I'm also experiencing this issue on Godot 3.2 beta 5 & VS Code plugin beta 2. My OS is Arch Linux. I'm seeing similar symptoms to others in this thread: VS Code loses connection & autocomplete stops working, hovering over variable names or functions shows `Loading...` instead of the function docs or variable information, trying to exit Godot crashes it.

It seems to happen randomly while editing code, and always within 10 minutes of trying to do something. I think it may be related to the linting errors VS Code shows but that's based on the fact that linting information in the editor seems to change nearly right before the connection is lost.

**Comment by Geequlim** [comment] 2020-01-10 05:11
@obsoke  What is the connection status showing with this error ?
`Initializing` or  `Connecting` or `Disconnected` ?

**Comment by Geequlim** [comment] 2020-01-10 05:34
I can reproduce this with godot 3.2 beta5.
The client cannot connect to the Languge server before restart godot editor.
The editor cannot exit when closing the window.

Here is the output of the godot editor
```
ERROR: Another resource is loaded from path 'res://MeshInstance.gd' (possible cyclic resource inclusion).
   At: core/resource.cpp:78
SCRIPT ERROR: GDScript::reload: Parse Error: Expected identifier as member
          At: res://MeshInstance.gd:28
ERROR: reload: Method/Function Failed, returning: ERR_PARSE_ERROR
   At: modules/gdscript/gdscript.cpp:576
SCRIPT ERROR: GDScript::reload: Parse Error: Expected identifier as member
          At: res://MeshInstance.gd:28
ERROR: reload: Method/Function Failed, returning: ERR_PARSE_ERROR
   At: modules/gdscript/gdscript.cpp:576
ERROR: Another resource is loaded from path 'res://MeshInstance.gd' (possible cyclic resource inclusion).
   At: core/resource.cpp:78
```

Sseems the LSP thread is locked when parsing scripts
@vnen Do you have any idea about this?

**Comment by TicklesTheBrain** [comment] 2020-01-10 09:09
Sorry, I was getting the same kind of errors as @Geequlim in the previous post, just didn't think they were relevant to this problem. Thought they were some of my own oopsies in gdscript :worried:

**Comment by vnen** [comment] 2020-01-10 11:13
@Geequlim maybe the LSP is trying to load a file at the same time as editor, which is not allowed (that is, loading the same file at the same time). Though this should just fail parsing and keep going, wouldn't really lock the thread.

Maybe it's related to the mutex on reload: https://github.com/godotengine/godot/blob/abefd42e846a04d2256da9d27b6d5757d431cec0/modules/gdscript/gdscript.cpp#L544-L551

**Comment by Geequlim** [comment] 2020-01-11 05:28
@TicklesTheBrain Could you try this reproduce after disable threading of lsp server? You can disable it the editor settings.

**Comment by TicklesTheBrain** [comment] 2020-01-11 12:22
> @TicklesTheBrain Could you try this reproduce after disable threading of lsp server? You can disable it in the editor settings.
I will try but I can't find the option you're taking about. The only "thread" related thing I see in the editor settings is the asset library > "Use threads". LSP has: port, enable smart resolve and show native symbols options.
How do I disable threading of lsp?

**Comment by Geequlim** [comment] 2020-01-11 14:40
> How do I disable threading of lsp?
Disable `Use threads` and restart the editor

**Comment by Geequlim** [comment] 2020-01-11 16:04
@TicklesTheBrain  Oh sorry. You have to try disable the threading after #35015 is merged.
You may need to try that in next release.

**Comment by TicklesTheBrain** [comment] 2020-01-12 09:50
@Geequlim Tried it out in Calinou's nightly builds https://hugo.pro/projects/godot-builds/ In fact, I didn't even have to disable it, threading is disabled by default on that build, it seems.

After some initial testing it seems to work fine without threading, haven't gotten LSP to crash yet. After enabling LSP again, I had the same problem within 30 seconds.

So it seems to be multi-threading related after all. I will test more and write back if I see the crash again.

**Comment by Geequlim** [comment] 2020-01-12 10:19
@TicklesTheBrain Thank you very much !
Does it always reproduce after threading enabled ? If so it would be easier to get a minimal test project to find out the problem.
Thanks for your testing !

**Comment by TicklesTheBrain** [comment] 2020-01-12 14:00
There isn't a minimal project that crashes just after being opened. Just after everything is loaded - it will work fine. The lsp connection crashes only when editing the script file.
The simplest I've gotten it to crash consistently is making a parse error when writing strings with an apostrophe, which gets understood like the end of the string. It doesn't always crash at the EXACT same moment, but you can see that by the time I'm writing that last if, there are no more suggestions, etc. - the connection has crashed. Have a look at this gif I made:
![lsp_parse_crash](https://user-images.githubusercontent.com/21967696/72219950-42a73200-3554-11ea-84e9-0aacf1967e1a.gif)

Here is that project (nothing in it really, single node with a script attached). And as I said it will not crash after loading, only when editing.
[godot_lsp_crash.zip](https://github.com/godotengine/godot/files/4050705/godot_lsp_crash.zip)

Also that last crash didn't output any errors to the console.

**Comment by Geequlim** [comment] 2020-01-13 11:28
@TicklesTheBrain Thank you again for your testing.

**Closed** 2020-01-13 12:05 UTC
Labels: bug, topic:gdscript
