### ISSUE TITLE
CSGBox or shapes making .obj completely black

### ISSUE THREAD

**Issue by coppolaemilio** [godotengine/godot#58529] opened 2022-02-25 13:14 UTC
### Godot version

4.0.alpha3

### System information

macOS Monterey - 12.2.1 - M1 - Vulkan

### Issue description

While testing using custom made objects I created a floor using a csg shape and then added a 3D model on top. The main issue is that when the obj is close to the csg shape it goes black for no reason. The gifs will be easier to understand:
![csg-bug-1](https://user-images.githubusercontent.com/2206700/155720962-914d31c5-3699-49b9-bf7f-805290e9c36c.gif)

Update: it is also happening with a regular mesh instance:
![csg-bug-2](https://user-images.githubusercontent.com/2206700/155721713-91b2f397-0a88-4927-951d-832880c98dec.gif)
When moving the mesh instance further away it shows the house properly

### Steps to reproduce

1 - Create a 3D scene
2 - Add an environment and a DirectionalLight3D
3 - Add a CSG shape 
4 - Import an .obj
5 - Toggle the CSG shape to see the issue

### Minimal reproduction project

[testing-alpha.zip](https://github.com/godotengine/godot/files/8141390/testing-alpha.zip)

**Comment by Calinou** [comment] 2022-02-25 13:47
Duplicate of https://github.com/godotengine/godot/issues/57161.

**Closed by Calinou** 2022-02-25 13:47 UTC
Labels: bug, topic:rendering, topic:import, topic:3d
