### ISSUE TITLE
[4.0] NavigationAgent3D.get_next_location call causes Godot to hang

### ISSUE THREAD

**Issue by shmolyneaux** [godotengine/godot#57780] opened 2022-02-08 00:48 UTC
### Godot version

v4.0.alpha1.official [31a7ddbf8]

### System information

Windows 10, Vulkan

### Issue description

When you run the attached project, Godot hangs and crashes due to an out of memory error. Here is the output on the console when this happens:
```
ERROR: Condition "!_ptrnew" is true. Returning: ERR_OUT_OF_MEMORY
   at: resize (./core/templates/cowdata.h:301)
ERROR: Condition "err" is true. Returning: true
   at: push_back (./core/templates/vector.h:305)
```
In the script `TestNavigationUnit3D.gd`, if you comment out the line `$NavigationAgent3D.get_next_location()` it no longer hangs.

Thanks for all the work on Godot! I really appreciate the project!

### Steps to reproduce

- Run the main scene in the attached project
- It should start hanging immediately
- For me, it runs out of memory after about 8 seconds.

### Minimal reproduction project

[godot_navigation_hang.zip](https://github.com/godotengine/godot/files/8019738/godot_navigation_hang.zip)

**Comment by smix8** [comment] 2022-05-13 17:11
@ shmolyneaux
I cannot reproduce the issue. The scene runs fine without any issues for me. If possible please test again with recent Godot 4.0 if the issue persists on your end.

**Comment by smix8** [comment] 2022-05-19 23:16
@Calinou 
I think this can be closed, there is nothing special in the MRP that could cause such an error in current Godot 4.0. All kind of MRP from other navigation issues had the same code and added complexity on top and no one reported crashes like this.

Memory issues with vector or variants were so common in the very unstable alpha 1 versions.
A navigation path query may have triggered it but it was usually never the source of the problem.

**Comment by Calinou** [comment] 2022-05-19 23:22
Closing per @smix8's comment. Please comment if you can still reproduce this on the latest `master` branch.

**Closed by Calinou** 2022-05-19 23:22 UTC
Labels: bug, needs testing, topic:navigation
