### ISSUE TITLE
Editor becomes unresponsive during CLI export

### ISSUE THREAD

**Issue by vrcsix** [godotengine/godot#7893] opened 2017-02-26 15:38 UTC
**Operating system or device - Godot version:**
```
$ uname -a
Linux ubuntu-vm 4.8.0-39-generic #42~16.04.1-Ubuntu SMP Mon Feb 20 15:06:07 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

Godot 2.1.2-stable. Also tested: 2.1/HEAD

**Issue description:**
When exporting via the command line, the editor becomes unresponsive and doesn't exit. It does seem to produce a functioning binary, however.

GUI export works fine.

![out](https://cloud.githubusercontent.com/assets/1703924/23340171/0d348fae-fc32-11e6-9531-90cc6d044815.gif)

GDB: [gdb.txt](https://github.com/godotengine/godot/files/802056/gdb.txt). The main thread waits for thread 6, which is stuck waiting on a semaphore.

Expected behavior: Godot exports the project and exits cleanly.

**Steps to reproduce:**
```
$ rm -rf ~/.godot && mkdir ~/.godot && unzip -d ~/.godot Godot_v2.1.2-stable_export_templates.tpz
$ sudo unzip -d /usr/local/bin Godot_v2.1.2-stable_x11.64.zip
$ git clone https://github.com/godotengine/godot-demo-projects.git demos && cd demos/2d/pong
$ Godot_v2.1.2-stable_x11.64 -export "Windows Desktop" /tmp/pong.exe
```

**Comment by akien-mga** [comment] 2017-02-27 08:29
```
$ git clone https://github.com/godotengine/godot-demo-projects.git demos && cd demos/2d/pong
$ Godot_v2.1.2-stable_x11.64 -export "Windows Desktop" /tmp/pong.exe
```
Note that the master branch of the demos repo is for use with the master branch of the engine. Do you still reproduce the issue if you checkout the 2.1 branch?

**Comment by protomouse** [comment] 2017-02-27 11:58
I've been able to reproduce it with a newly created 2.1 project also. Have not tried the 2.1 demos.

**Comment by marcelofg55** [comment] 2017-09-24 02:57
I tried this but couldn't reproduce with latest 2.1.

**Comment by vnen** [comment] 2017-11-12 16:35
I can reproduce consistently with latest 2.1 (55c010aa6).

**Comment by Calinou** [comment] 2018-04-10 19:34
I can't reproduce this issue as of commit https://github.com/godotengine/godot/commit/53b51f68bf9b6dd38014b5ac022209b8433d7340, so I'm closing this. Feel free to comment if you can still reproduce this bug on Godot 3.0.2 or newer.

**Closed by Calinou** 2018-04-10 19:34 UTC
Labels: bug, confirmed, topic:editor
