### ISSUE TITLE
Godot closing itself while saving a scene after canceling its termination

### ISSUE THREAD

**Issue by LeoClose** [godotengine/godot#80053] opened 2023-07-30 11:13 UTC
### Godot version

4.1.1.stable

### System information

Godot v4.1.1.stable - Windows 10.0.22000 - Vulkan (Compatibility) - NVIDIA GeForce GTX 1050 Ti (NVIDIA; 31.0.15.3640) - AMD Ryzen 5 1600 Six-Core Processor (12 Threads)

### Issue description

https://github.com/godotengine/godot/assets/72339524/eccffb5b-d5e0-4f98-9626-391ee0d08a3f

Godot simply closes itself when trying to save a scene after canceling app termination

### Steps to reproduce

Load a project, change something in the scene, try to close the engine but click on cancel, then try to save a scene and the engine will close itself

### Minimal reproduction project

N/A

**Comment by saierXP** [comment] 2023-07-30 11:57
It can be reproduced in 4.1.dev1, possibly due to the introduction of #67466 (Scene tab closing refactor).

**Comment by TheSofox** [comment] 2023-12-14 11:20
PR fix submitted.

**Comment by KoBeWi** [comment] 2024-07-25 20:32
Can't reproduce in 4.3.
I think there was a duplicate issue that got fixed independently.

**Closed** 2024-07-25 20:32 UTC
Labels: bug, topic:editor
