### ISSUE TITLE
Run in Fullscreen

### ISSUE THREAD

**Issue by LastSize** [godotengine/godot#32642] opened 2019-10-08 10:02 UTC
**Godot version: 3.1.1.stable.official**

**OS/device including version: windows 10**

**Issue description:**
There are 2 monitors in my system
First      1920x1080 
Second 1280x1024
When I run a project in Fullscreen, it runs on the first monitor with the resolution of the second.
with a gray line at the bottom
Stretch settings "viewport"or "2d" do not affect the result.

![screen-2](https://user-images.githubusercontent.com/40803227/66386652-618da980-e9e4-11e9-8f7b-04e38f6ddea2.jpg)
![screen-1](https://user-images.githubusercontent.com/40803227/66386654-62264000-e9e4-11e9-8332-8abb1fe4f862.jpg)

**Comment by KoBeWi** [comment] 2019-10-08 10:51
Probably related to #20618

**Comment by LastSize** [comment] 2019-10-08 13:37
Probably need for a new feature in Godot.
To prevent this, a compiled application must be able to determine which monitor it is running on and its parameters.

**Comment by Calinou** [comment] 2019-10-08 13:40
Duplicate of #21746.

> To prevent this, a compiled application must be able to determine which monitor it is running on and its parameters.

This is already possible, see `OS.current_screen` and the associated `OS.get_screen_*` methods.

**Closed by Calinou** 2019-10-08 13:40 UTC
Labels: bug, topic:editor, topic:rendering

**Comment by LastSize** [comment] 2019-10-08 16:38
> Duplicate of #21746.
> 
> > To prevent this, a compiled application must be able to determine which monitor it is running on and its parameters.
> 
> This is already possible, see `OS.current_screen` and the associated `OS.get_screen_*` methods.

This is configurable in the project settings. The compiled program does not run with values from the project settings. I think this is a mistake, but you can have your own opinion.
