### ISSUE TITLE
Error when changing theme.tres properties not attached to any Control node.

### ISSUE THREAD

**Issue by jaekit** [godotengine/godot#73193] opened 2023-02-13 02:41 UTC
### Godot version

4.0.rc1.mono

### System information

Windows 11

### Issue description

When adding/removing any custom properties inside a theme.tres file, the Theme tab in the editor will close and will result in `Condition "edited_theme.is_null()" is true.`

However, when opening the .tres file again, the properties will be added/removed properly.

There is no error when the .tres file is attached to a Control node. One may want to change the tres file with no Control node if it is a default theme.
The workaround is to attach the tres file to any Control node and modify it from there.

### Steps to reproduce

Create a new theme.tres file and open it to bring up the Theme inspector.
Add any item type and try to add/remove any property.
Observe the Theme tab minimizing and resulting in an error.
When opening the theme.tres file again, the property is set correctly however.

### Minimal reproduction project

N/A

**Comment by jaekit** [comment] 2023-02-13 02:45
Not reproducible in 3.5.1.stable

**Comment by YuriSizov** [comment] 2023-02-13 11:18
Duplicate of https://github.com/godotengine/godot/issues/72799. Fixed by https://github.com/godotengine/godot/pull/73098.

**Closed by YuriSizov** 2023-02-13 11:18 UTC
