### ISSUE TITLE
GI probe indirect lighting on gridmaps

### ISSUE THREAD

**Issue by DevMagicLord** [godotengine/godot#18836] opened 2018-05-13 12:34 UTC
Godot 3.0.2
Win 7 64 bits GeForce 960

Hi there,

I made a scene with an emissive material and Global Illumination, but lighting only throw  on floor, but walls don't receive any bounces lighting.

https://github.com/DevMagicLord/Godot3/blob/master/bugs/Giprobeissue.jpg

While materials without normal map and roughness map receives all indirect lighting.

https://github.com/DevMagicLord/Godot3/blob/master/bugs/giprobeissue2.jpg

Materials with normal map and roughness, metallic maps, needs to receive lighting bounces.

**Comment by Calinou** [comment] 2018-05-14 09:45
Does your scene use procedural meshes (such as CubeMesh inside a MeshInstance)? From my testing, GIProbe bakes won't affect them.

**Comment by groud** [comment] 2018-05-14 12:11
Probably related to #18056

**Comment by DevMagicLord** [comment] 2018-05-14 20:48
I found GiProbe baking works well on standard objects, and emissive objects must also have the flag "used in baked lighting" to true.

But i imported 3D tiles and put "used in baked lighting" to true before saving a meshlib, and baking the Giprobe doesn't bake well on Gridmaps, it's very dark.

On center this is gridmap while others are objects.
https://github.com/DevMagicLord/Godot3/blob/master/bugs/giprobeGridmapsbaking.jpg?raw=true



The issue is about gridmaps.

**Comment by EzraT** [comment] 2018-08-28 15:07
This happens to me too with Godot 3.0.6 on Linux.
There is a very clear difference to how GIProbe looks on regular MeshInstance nodes, compared to how it looks on a Gridmap.

**Comment by reduz** [comment] 2018-11-16 19:53
Sorry, without a test scene, figuring out what is going on is impossible. Closing.

**Closed by reduz** 2018-11-16 19:53 UTC
Labels: bug, topic:rendering

**Comment by EzraT** [comment] 2018-11-17 12:09
@reduz [Reproduction Project](https://github.com/godotengine/godot/files/2591712/gridmap_gi_issue.zip)

**Comment by EzraT** [comment] 2019-01-08 11:03
Could this one be added to the 3.1 milestone?

**Comment by reduz** [comment] 2019-01-17 19:04
Actually, it seems to be working, but the emission channel is not strong enough. Lights can compensate this because they have a bake energy value but materials don't. I promise to add this after 3.1 is out, as I will be doing some rewriting to the GIProbe code.

**Comment by KoBeWi** [comment] 2020-12-10 23:43
Still valid in 3.2.4 beta3
Can't test on master, because GridMap doesn't work (incompatible meshlib?)

**Comment by SoloCodeNet** [comment] 2021-09-08 05:47
Gi PRobe not working on voxel based model, no texture on the mesh just magica voxel import 
tested with meshinstance directly work fine, add gridmap with same model (left and right) and re-bake
capture : https://ibb.co/pJ8D9Z8

**Comment by Calinou** [comment] 2021-12-17 18:02
This appears to be fixed in `master` according to my tests in https://github.com/godotengine/godot/issues/56030.

**Comment by EzraT** [comment] 2022-04-13 11:27
Issue still present in 3.5.beta3.

**Comment by EzraT** [comment] 2022-04-13 11:56
I did some more testing, and I found something that could hopefully shed some more light on this problem.

To clarify again, this is what the scene in the MRP looks like when using just meshinstances for the hallways:
![image](https://user-images.githubusercontent.com/781121/163173459-528a5da8-1770-4362-a34e-a2eefc239843.png)

Now here's what the same meshes look like in a gridmap, using the exact same settings in the GIProbe:
![image](https://user-images.githubusercontent.com/781121/163173711-718892ec-22a3-411f-8f1d-0e33190193b9.png)

The GIProbe is turned to 16 in both scenes to demonstrate the problem better.

What I discovered is this:
When I turn down the Bias property on the GIProbe node to zero in the scene with only MeshInstances, things start to look very similar to GridMap scene:
![image](https://user-images.githubusercontent.com/781121/163174545-3dccb5ca-2e84-45be-b137-ace103c5b81b.png)

Changing the Bias value in the Gridmap scene also does not result in any different visuals.

Could it be that GIProbe is not applying the Bias value to gridmaps?

**Comment by Calinou** [comment] 2022-04-13 12:29
Can you reproduce this with a MultiMeshInstance? GridMap uses MultiMesh behind the scenes for rendering.

**Comment by EzraT** [comment] 2022-04-13 12:33
@Calinou 
Check #45313
As far as I'm aware MultiMeshInstances in Godot 3 do not affect GIProbe, as the issue says.
