### ISSUE TITLE
Attempting to clear an array that is shadowed before the shadowed array is declared causes crash

### ISSUE THREAD

**Issue by twobitadder** [godotengine/godot#74459] opened 2023-03-06 00:30 UTC
### Godot version

4.0.stable

### System information

Windows 10, also Linux Mint 20 (I think? I don't have my laptop available at the moment lol)

### Issue description

After accidentally shadowing an array within a script's global scope, I noticed that the engine will crash upon attempting to clear an array with that name before the shadowing variable is declared. 

I first noted this with a tool script, so the editor itself will hard crash to desktop, but even if you place the offending code in a scene and run the scene, the scene will crash without fanfare.

Apologies if this has already been reported, a cursory search didn't turn up anything but I don't know if I have the right terminology to search with.

### Steps to reproduce

```
var my_array : Array

func _ready() -> void:
	my_array.clear()
	
	var my_array := []
```
is sufficient code to attach to a node to cause the crash to occur

### Minimal reproduction project

N/A, as it can be reproduced very easily. If others are unable to reproduce it though, I can provide an MRP.

**Comment by twobitadder** [comment] 2023-03-06 00:31
NB: I thought perhaps at first it was because the global scope array was not fully declared but even if you initialize it with a value it will still cause the crash, and it only does not crash when `var my_array := []` is removed from the end.

**Comment by vonagam** [comment] 2023-03-06 08:54
The same issue - #74015.

**Comment by akien-mga** [comment] 2023-03-06 09:06
Indeed, duplicate of #74015. The main difference is the crash, which is caused here by using type hints on the shadowing array, so it uses the fast path with `call_with_validated_variant_args`.

**Closed by akien-mga** 2023-03-06 09:06 UTC
Labels: bug, topic:gdscript, topic:editor, crash

**Comment by twobitadder** [comment] 2023-03-06 17:55
Dang, I knew it was my search ability lacking. Sorry!
