### ISSUE TITLE
Y aixs flickers in empty 3D editor

### ISSUE THREAD

**Issue by floppyhammer** [godotengine/godot#51603] opened 2021-08-13 02:53 UTC
### Godot version

v4.0.dev.custom_build [a98589a44]

### System information

Windows 11, Vulkan

### Issue description

The flickering only happens in the empty 3D editor. It doesn't occur if you add a new 3D node.

![y-axis-flickering](https://user-images.githubusercontent.com/28705694/129297959-62c8b64c-2be1-477d-aca8-4fd03e74107a.gif)

I remember seeing a report about this before but can't find it anymore.

### Steps to reproduce

Create and open a new project, hold and drag the mouse middle button, observe.

### Minimal reproduction project

No need.

**Comment by Chaosus** [comment] 2021-08-13 07:34
Duplicate of https://github.com/godotengine/godot/issues/37016

**Closed by Chaosus** 2021-08-13 07:34 UTC
