### ISSUE TITLE
Debug Performance Monitor Graph is "difficult" to read afterward

### ISSUE THREAD

**Issue by SuperUserNameMan** [godotengine/godot#5066] opened 2016-06-06 12:11 UTC
**Operating system or device - Godot version:**
Official 2.0.3stable win64

**Issue description** (what happened, and what was expected):

Sometimes, the debug performance monitor graph is "difficult" to read because it does not show min/max value, average value, nor a grid/scale, nor a timeline, nor a hint-box showing value under the mouse, etc.

Only the last value is available.

![monitor_scale](https://cloud.githubusercontent.com/assets/9801802/15821428/0fcdad9e-2bf0-11e6-8c9d-085fa3cfa158.png)

**Steps to reproduce:**

**Link to minimal example project** (optional but very welcome):

**Comment by akien-mga** [comment] 2016-06-06 12:15
I agree that it lacks at least a scale for the y-axis. Having the values in a tooltip on hover would be pretty cool too :)

**Comment by SuperUserNameMan** [comment] 2016-06-06 12:32
being able to save graph into a CSV sheet, could be very handy to compare efficiency of undergoing optimizations too.

**Comment by akien-mga** [comment] 2016-07-15 11:19
Not critical for the upcoming 2.1, so moving to the next milestone.

**Comment by lupoDharkael** [comment] 2018-12-29 16:21
Working on this!

**Comment by lupoDharkael** [comment] 2019-01-03 18:07
Here's an update about what I've been doing with the profiler:

- min/max value, average value, (and percentiles maybe): The default area for the profiler is very limited, I don't want to clutter the graphic with information. A possible solution might be adding an extra Control and show it only when you extend the profiler to fit the central area of the editor.

- grid/scale: TODO

- timeline: TODO

- hint-box showing value under the mouse: WIP

- being able to save graph into a CSV sheet: WIP (will export data from the Profiler and the Monitors)

- export/import profiler & monitors status: I've wanted this feature for a while as it is very convenient to share the values of profiling session to other team members when you want to track a bug of performance problem. The problem is this requires a format more flexible than CSV as the profiler has lists of lists and that kind of data structure is hard to represent in CSV if you want to keep the file clean and easy to use for plotting in Libreoffice and similar software. I've implemented an exporter/importer from json because Godot aready has code to serialize Variant to that format.

This will take some time but I'll eventually make the PR so it can be reviewed.

**Comment by lupoDharkael** [comment] 2019-02-18 00:32
Here is the PR for the CSV export (as @SuperUserNameMan suggested): https://github.com/godotengine/godot/pull/25995

**Comment by Calinou** [comment] 2020-06-05 13:29
Closing in favor of https://github.com/godotengine/godot-proposals/issues/1014, as feature proposals are now tracked on the Godot proposals repository.

**Closed by Calinou** 2020-06-05 13:29 UTC
Labels: enhancement, pr welcome, topic:editor, usability
