### ISSUE TITLE
Godot tries to load plugins before importing assets

### ISSUE THREAD

**Issue by andersmmg** [godotengine/godot#51599] opened 2021-08-13 00:09 UTC
### Godot version

Every one I've tested

### System information

Manjaro Linux

### Issue description

Often, when I open a project for the first time that has enabled plugins, I get this error before it starts importing. After it's done, I have to go manually enable the right plugins, which can be annoying since sometimes there are pluugins that shouldn't be enabled right now, and I have to put in notes somewhere to not enable it, or remove it and put a note to install it and set it up later.

### Steps to reproduce

Open a project that has a plugin enabled which uses an asset that needs to be imported.

![Screenshot_20210812_180120](https://user-images.githubusercontent.com/16022203/129285252-375c848e-494b-401b-a50e-05a2445e2218.png)

**Comment by Zylann** [comment] 2021-08-13 09:30
Related https://github.com/godotengine/godot/issues/23937

**Comment by Calinou** [comment] 2021-08-13 16:45
Duplicate of https://github.com/godotengine/godot/issues/23937 (see also https://github.com/godotengine/godot-proposals/issues/1615).

**Closed by Calinou** 2021-08-13 16:45 UTC
