### ISSUE TITLE
Godot 4.1.1 can't export build ios / xcode project - a) [Export Icons]: Invalid icon (icons/iphone_120x120); B) undefined symbols;  Linker command failed with exit code 1 - Apple Silicon

### ISSUE THREAD

**Issue by LeandroHPerez** [godotengine/godot#82551] opened 2023-09-29 20:54 UTC
### Godot version

v4.1.1.stable.official [bd6af8e0e] - (without .net) - MacOs version

### System information

Macbook Apple M2 Pro - MacOs  Sonoma 14.0

### Issue description

Tried to export two diference projects for iOS results in "strange errors" (i tried anothers projects too).
**Bug one:**
_* Project export for platform: ios iOS - & Failed.
•[Export Icons]: Invalid icon (icons/iphone_120x120)_

 **Bug two:**
_a) Undefined symbols:
b) Linker command failed with exit code 1 (use -v to see invocation)_

### Steps to reproduce

**Environment:**
Macbook Pro M2 Pro
Xcode Version 15.0 (15A240d)
Godot 4.1.1  regular (without .net)

1- Open any minimal Godot 4.1.1 project
2- In Godot: Project > Export > Choose "iOS" updated template/preset
3- Type an valid "app store team id", i've used this method to get my free key -> Session Get the team ID in link:  https://medium.com/@phillipdev/exporting-to-ios-using-godot-4-1-for-free-ed99b8f594b7

4- type bundle identifier
5- type an Export path

![image](https://github.com/godotengine/godot/assets/5435476/69b81616-5250-450d-a480-c4915b193472)

6- Now, click in "Export project" > "Save", for me is the first bug found:

**Bug one:**
_* Project export for platform: ios iOS - & Failed.
•[Export Icons]: Invalid icon (icons/iphone_120x120)_

![image](https://github.com/godotengine/godot/assets/5435476/194ad0ce-73a8-43d4-8f9f-55c8303b4e0e)

7- Now, choose an image for every field of icons, because what warning will be ocour for every field....
Do like this:
![image](https://github.com/godotengine/godot/assets/5435476/4edc2cf8-e8f2-468f-bedb-263a92a0b63a)

8 - Now, finally, click in "Export project" > "Save"
![image](https://github.com/godotengine/godot/assets/5435476/fad5e454-b1ed-42ad-8b85-4cac3297d941)

9- Open exported project in Xcode: open file my_file_name.xcodeproj

10- In Xcode try build and see errors like this.

 **Bug two:**
_a) Undefined symbols:
b) Linker command failed with exit code 1 (use -v to see invocation)_

![image](https://github.com/godotengine/godot/assets/5435476/dcdfb005-ab4b-4490-a610-72582528a10d)

Attached:
Zipped Godot Project
Two image files, each one with 1024x1024 size with extensions: .png and .jpg. I tried use this images in bug step 7.

### Minimal reproduction project

[Tappy Plane v6.zip](https://github.com/godotengine/godot/files/12771682/Tappy.Plane.v6.zip)

**Comment by LeandroHPerez** [comment] 2023-09-29 21:17
Thanks for fast reply, like an ninja.
Will this problem be fixed in the next version of Godot?
For me and certainly most peoples this is a big fix that helps a lot.

**Comment by akien-mga** [comment] 2023-09-30 08:22
Duplicate of #82454.

**Closed by akien-mga** 2023-09-30 08:22 UTC
