### ISSUE TITLE
Kinematic move() and move_and_slide() slows down randomly with multiple objects

### ISSUE THREAD

**Issue by sketchyfun** [godotengine/godot#6507] opened 2016-09-15 21:59 UTC
**Operating system or device - Godot version:**
Windows 7 (also tested on Ubuntu)

**Issue description** (what happened, and what was expected):
Multiple kinematic bodies using move_and_slide() cause random slow downs, it seems to happen less if the collision shapes are circles, and is the worst when using a capsule shape.

Originally Juan pointed out that if the velocity returned from using move() wasn't used with slide() or capped manually then the values might increase (like the Y value with gravity) and eventually cause slow down when the values become too large. However, in the example linked below, I'm using move_and_slide() and I'm also manually clamping the velocity values, and this problem still persists.

The problem happens more frequently with more objects, but I've had it happen in my own game project with as little as 5-6 objects, and it will drag the framerate down to single digits when it happens.

If there's enough objects, like in the example, once the problem occurs it doesn't seem to go away. If you have fewer objects (say less than 20), then the problem takes longer to appear but also goes away after a few seconds, as seen in the graph below.  

Here's what the profile graph looks like:

![profile1](https://i.imgur.com/CBDSyXZ.png)

and as you can see, when the usage spikes the fixed process count goes from 33 to 264 (when I had 33 objects)

![profile2](https://i.imgur.com/cUpgfgP.png)

**Steps to reproduce:**
Download the example linked below, run the profiler and then run the scene. The more objects there are, the quicker the problem appears. The example has about 26 objects, so it should happen within a few seconds of starting the scene.

**Link to minimal example project** (optional but very welcome):
[slow_kinematic.zip](https://github.com/godotengine/godot/files/477045/slow_kinematic.zip)
https://dl.dropboxusercontent.com/u/3292249/slow_kinematic.zip

**Comment by eon-s** [comment] 2016-09-16 18:15
Reducing the max_bounces to 1 solves the fps problem in the example, if I double the numbers of nodes, the problem appears again.
Tried forcing velocity x = 0 on the script (with double amount) and slowly drops to < 30fps.

**Comment by sketchyfun** [comment] 2016-09-17 11:11
Where is the max_bounces setting? I can't seem to find it on any of the nodes or in the project settings

**Comment by eon-s** [comment] 2016-09-17 12:48
@sketchyfun is the 4th parameter:
`move_and_slide(linear_velocity, floor_direction=Vector2(0,0), slope_stop_min_velocity=5,max_bounces=4)`

Controls a loop, I guess is a form of precision control for the slide.

**Comment by sketchyfun** [comment] 2016-09-17 13:16
Ah thanks, that at least lets me carrying on working without slow down in the mean time!

**Comment by leiget** [comment] 2016-10-10 17:46
I've fixed this issue with the help of eon-s.

What I did was edit [physics_body_2d.cpp](https://github.com/godotengine/godot/blob/master/scene/2d/physics_body_2d.cpp) so that it uses a bool to check if "body_test_motion()" needs to be done.

In that file, if put
```
//Bool to say if the body_test_motion has already been done.
bool body_test_motion_DONE = false;
```
at the top of the file, on line 32, after the includes.

Then, I replaced
```
colliding = Physics2DServer::get_singleton()->body_test_motion(get_rid(),gt,p_motion,margin,&result);
```
on line 1066, or around there, with
```
	//Only do body_test_motion on the first call of this function.
	if(body_test_motion_DONE == false)
	{
		colliding = Physics2DServer::get_singleton()->body_test_motion(get_rid(),gt,p_motion,margin,&result);
		body_test_motion_DONE = true;
	}
```
in the "Vector2 KinematicBody2D::move(const Vector2& p_motion)" function.

Then, I put 
```
	//Reset the motion test so it can be done next time.
	body_test_motion_DONE = false;
```
on around line 1328, which is after the while loop, "while(p_max_bounces)", so that it will reset the bool so the next call to "move_and_slide" it can be called.

Here is the file itself:
[physics_body_2d_cpp.txt](https://github.com/godotengine/godot/files/520097/physics_body_2d_cpp.txt)

**Comment by leiget** [comment] 2016-10-10 19:18
But now that I've tested it some more, there is some slow down after adding more objects, but it's not the same problem. It seems to be "_fixed_process" that is being slowish (only 0.014 seconds), but it's getting 74 calls.

Anyway, here is the minimal project file:
[slow_kinematic_update_01.zip](https://github.com/godotengine/godot/files/520232/slow_kinematic_update_01.zip)

This will run at 60 FPS on my machine. But, if I add 2 or 3 more kinematic objects, it will go down to 7.5 FPS. And remember that this is with a build with the additions in my previous post.

**Comment by eon-s** [comment] 2016-10-10 20:16
@leiget now with that fix in this demo, it stays around 900 fps with CircleShape2D, which is pretty insane :D , and 1/3-1/2 that value with rectangle.

I was going to blame the capsule but dies at 1fps with CollisionPolygon, the problem may go up to the server and the way it manages the shapes.

**Comment by leiget** [comment] 2016-10-10 20:50
@eon-s What are your PC specs? I have a AMD 860K and a 960 GTX and I get ~3500 FPS with a capsule shape collision.

**Comment by leiget** [comment] 2016-10-10 21:32
I've encountered a problem. On platformers which use move_and_slide(), when you are walking on the ground, the character moves slowly, but when you jump the character moves at the speed that he is supposed to.

**Comment by eon-s** [comment] 2016-10-10 21:42
@leiget I have noticed the jump thing too, in the other issue (not in the demo), and that move_and_slide uses the full velocity vector (then I thought I was doing something wrong).

**Comment by eon-s** [comment] 2016-10-20 19:29
After realizing that collision margin pushes a bit the bodies, tested the project (with no fixes on `move_and_slide`) with minimum collision margin and got an average of 300fps on the monitor (with the label showing over 1000).

The script on this project example has a lot of small movements for all the bodies, maybe the margin is creating a bottleneck on the physics server.

**Comment by reduz** [comment] 2017-08-05 13:26
the algorithm has been considerably optimized in 3.0, so any testing would be appreciated

**Comment by eon-s** [comment] 2017-08-05 14:18
Still the same, here is a version of the examples exported to 3 with 2.1.4b2

[slowkinematic3.zip](https://github.com/godotengine/godot/files/1202412/slowkinematic.zip)

**Comment by reduz** [comment] 2017-08-08 16:51
I ran some callgrind on it. The main reasons why this is slow are:

- First and foremost, KinematicBody motion is a LOT more complex than a RigidBody, they are not supposed to be fast, specially when you have tons of them collising against lots of things
- Demo uses ConvexPolygon+Capsule. This is a pretty complex collision resolution
- That said, the SAT code needs to be changed eventually in 3.1 for simplified version
- But the main reason for the slowness is that 2D math in Godot is not inlined.. this should be done at some point, but is always kicked back. If anyone wants to volunteer, feel welcome.

I'll remove the bug tag and replace by enhancement. Will kick for 3.1

**Comment by Zireael07** [comment] 2021-05-09 10:34
I am seeing something similar in 3.3. but in 3D.

**Comment by Calinou** [comment] 2021-05-09 10:52
@Zireael07 Do you have a minimal reproduction project?

**Comment by eon-s** [comment] 2021-05-09 14:51
@Zireael07 this issue was for 2D which is a very different engine than the (two) used for 3D, and I'm not sure if this already solved or not, it may be better to open a new one and show results with Godot and Bullet physics.

**Comment by eon-s** [comment] 2021-05-12 03:16
Tested this issue with 3.3 using `move_and_collide` and `move_and_slide` and I have not experienced any slowdown using `CircleShape2D`, `CapsuleShape2D` and irregular `CollisionPolygon2D` in solid mode.

**Comment by akien-mga** [comment] 2021-05-12 11:02
I can't reproduce the issue on any 3.x release either with the MRP from https://github.com/godotengine/godot/issues/6507#issuecomment-320446220 (after fixing scripts with `s/_fixed_process/_physics_process/g`).

So closing, please open a new issue with an up to date MRP for 3.3+ if you still reproduce a similar issue.

**Closed by akien-mga** 2021-05-12 11:02 UTC
Labels: enhancement, topic:core, topic:physics
