### ISSUE TITLE
Godot 4.0 Beta 8 macos universal version only opened with a blank grey window on a Intel x86_64 platform. 

### ISSUE THREAD

**Issue by cyberpsyche** [godotengine/godot#69945] opened 2022-12-12 07:51 UTC
### Godot version

Godot 4.0 Beta 8

### System information

MacOS 10.15.7 (19H2) Intel Iris Graphics 6100 1536 MB

### Issue description

The app only opened with a blank grey window on an Intel x86_64 platform. 

### Steps to reproduce

The app only opened with a blank grey window on an Intel x86_64 platform. 

### Minimal reproduction project

The app only opened with a blank grey window on an Intel x86_64 platform.

**Comment by Zireael07** [comment] 2022-12-12 07:56
duplicate of #69046 (just search for 'gray' and it shows up)

**Comment by Calinou** [comment] 2022-12-12 09:10
Duplicate of https://github.com/godotengine/godot/issues/69046.

**Closed by Calinou** 2022-12-12 09:10 UTC
