### ISSUE TITLE
Depending on precision, inconsistent float behavior across STDOUT, debugger, and memory in GDScript.

### ISSUE THREAD

**Issue by crazychenz** [godotengine/godot#37647] opened 2020-04-07 01:55 UTC
**Godot version:** 
Godot 3.2.1 Windows (non-Mono)

**OS/device including version:** 
Windows 10 (x64)
Intel Core i5-8600K

**Issue description:**
BLUF: Floating point number handling is inconsistent with precision greater than three 9s and less than eight 9s.

When using floating point numbers (in GDScript) close to a whole number, the behavior of the rounding that may occur is different across different components of the software at different precisions. For example:

A float with a value of 0.999 is accurate in stdout, debugger, and memory. (OK)
A float with a value of 0.999999 is accurate in stdout. Rounded up in debugger and memory. (BAD)
A float with a value of 0.9999999 is rounded in stdout and debugger. Accurate in memory. (BAD)
A float with a value of 0.99999999 is rounded in stdout, debugger, and memory. (OK)

I found this issue by storing integers in instances of Vector2(float, float). I expected to be able to cast the coordinates with int() when required. At one point I was dropping slightly below 1 because I performed a 180 degree vector rotation. Everything was showing a correct transition from -1 to 1, but when I cast the 1 with int(1), I would get 0. 

I've added some screen captures of each of the different precisions to show the different states of Godot/GDscript, its stdout, its debugger. Memory access is limited in GDScript (without Native), so I deduce the memory state by indirectly invoking whatever hash algorithm is used to de-reference Dictionary entries. **Blue highlighted area indicate expected behavior and orange highlighted areas indicated unexpected behavior.**

<img width="702" alt="3-9s-highlights" src="https://user-images.githubusercontent.com/792769/78621473-a5a51e00-7850-11ea-98a2-480fb6ff48de.png">
<br />
<img width="703" alt="6-9s-highlights" src="https://user-images.githubusercontent.com/792769/78621468-a50c8780-7850-11ea-836c-a4107d69c19b.png">
<br />
<img width="703" alt="7-9s-highlights" src="https://user-images.githubusercontent.com/792769/78621471-a5a51e00-7850-11ea-9acb-76799e4b1b6b.png">
<br />
<img width="703" alt="8-9s-highlights" src="https://user-images.githubusercontent.com/792769/78621548-dc7b3400-7850-11ea-91eb-7d0700ce5597.png">

**Steps to reproduce:**
See the minimal project.

**Minimal reproduction project:**
You can see the behavior in the following project. Add breakpoint to line 11 of the script attached to top Node of Node.tscn.
[MisleadingRound.zip](https://github.com/godotengine/godot/files/4441509/MisleadingRound.zip)

**Comment by aaronfranke** [comment] 2020-04-07 03:43
This is a duplicate of #288, see also #17971 and #27665.

**Closed by aaronfranke** 2020-04-07 03:43 UTC
