### ISSUE TITLE
Clear curves on Path2D

### ISSUE THREAD

**Issue by tiagomsa** [godotengine/godot#16085] opened 2018-01-26 14:06 UTC
Hi there, im using Godot 3 rc3 and it keeps crashing when i try to clear curves on Path2D.

![godot_bug](https://user-images.githubusercontent.com/35841384/35443165-9e66b772-0299-11e8-89e3-dc83fac3c80c.gif)

**Comment by Noshyaar** [comment] 2018-01-26 14:25
Can't reproduce. Would appreciate a stack trace or crash logs.

**Comment by akien-mga** [comment] 2018-01-26 14:28
Or an example project and steps to reproduced as asked for in the issue template.

**Comment by williamd1k0** [comment] 2018-01-26 14:30
I was able to reproduce it in `rc3` but not in `internal stable`.

**Comment by akien-mga** [comment] 2018-01-26 14:32
Ah indeed, it's fixed by #15994 (and this issue is a duplicate of #15989).

**Closed by akien-mga** 2018-01-26 14:32 UTC
Labels: bug, topic:editor

**Comment by tiagomsa** [comment] 2018-01-26 14:41
yep sorry my bad for the duplicate

**Comment by akien-mga** [comment] 2018-01-26 15:01
No worry, it's better to have an issue reported several times than none :)
