### ISSUE TITLE
Godot causes my OS to freeze/restart

### ISSUE THREAD

**Issue by MinaRashad** [godotengine/godot#37471] opened 2020-03-31 18:50 UTC
**Godot version:**
Godot_v3.2-stable
**OS/device including version:**
Ubuntu 18.10 cosmic
**Issue description:**

After opening a project file to edit, after some not long time about 5 minutes,
The program freezes after some time the whole os freezes. If I try to kill the process
through "System monitor" it causes my OS to restart for some reason. if i do not
kill the process, I will be forced to restart it anyway. after restarting and opening godot, somehow
it works without any problems.
I know this looks weird,

**Steps to reproduce:**

*it happens randomly.*

**Minimal reproduction project:**
*No Specific project*

**Comment by clayjohn** [comment] 2020-03-31 19:02
Could you post more information about your hardware? It may be helpful.

Unfortunately, if you can't reproduce reliably and no one else is experiencing this same issue, it is unlikely to get fixed. 

I recommend updating your OS (if not latest) and your GPU drivers to make sure that this isn't an OS/Driver specific issue.

**Comment by Axol3** [comment] 2020-03-31 19:28
The same thing happens to me but only when I've kept my OS running for too long. How regularly does this happen to you?

**Comment by MinaRashad** [comment] 2020-04-01 11:24
@clayjohn 
OS 64 bits
CPU:iIntel(R) Core(TM) i5-7200U CPU @ 2.50GHz
GPU:Radeon
8G ram
anything else?

@Axol3 Well, I use my PC a lot, it happens pretty often.

**Comment by Calinou** [comment] 2020-04-01 12:19
@MinaRashad @Axol3 Can you reproduce this with any other 3D applications or games?

**Comment by MinaRashad** [comment] 2020-04-01 15:11
@Calinou For me it happens randomly, it has no relation with whether the project is 2D or 3D, this problem was since version 3.1 , I ignored it, hoping that it will be solved in 3.2. but unfortunally it did not :'(

**Comment by MinaRashad** [comment] 2020-04-01 15:17
I think it is related with godot, i use blender and it works fine and other, no app i use act like this. I think it is related to godot somehow, maybe it has code that acts differently on different OS, thats at least what i suspect.

**Comment by Rybadour** [comment] 2020-04-01 15:28
I am seeing a similar issue on OSX after a recent update of my OS.
I'm on High Sierra 10.13.6 and the latest version of Godot and using GLES3.

It seems to happen for me while using "Play the Project".

This is the only app I've noticed this problem although some other applications have been behaving a bit erratic. Godot is the only one that can freeze up the OS completely.

**Comment by Zireael07** [comment] 2020-04-01 15:31
IIRC we had similar reports in the past... @Calinou do you remember the other issue #?

**Comment by Rybadour** [comment] 2020-04-01 15:50
Anecdotally GLES2 seems to be working fine I've had no issues after I switched.

**Comment by Calinou** [comment] 2020-04-01 16:39
@Zireael07 Indeed, see #18871. Unfortunately, it's very difficult to reproduce for individual contributors.

**Comment by MinaRashad** [comment] 2020-04-04 13:05
@Calinou 
Hey, I tried to do some researches on some claims that I found on the issue You mentioned.
### **Claim 1: "It has something to do with intel CPUs"**

I gathered data from all people who said they have the same problem, and then plotted the data and found that exactly 80% of them has intel CPU, doing further researches, I found that 80% of computers manufactured have intel CPU, this means that this has nothing to do with the CPU
![Screenshot from 2020-04-04 14-48-24](https://user-images.githubusercontent.com/39602891/78451203-61fdb900-7684-11ea-8617-f5008835f2ac.png)

### **Claim 2:" it is related to something you do from the editor" or " it happens when you close a running project from the editor"**

in the past 2 days, I recorded every time godot crashed on me, one of them godot crashed when I was searching in the templates but I was able to kill the process. but as soon as I ran it again it crashed when I tried to close it normally by the "x" icon the PC restarted. luckily I was filming both crashes, I might try to upload it if it will help.

**Comment by davidpwbrown** [comment] 2020-04-09 22:06
Currently happening to me on a project, Ubuntu 19, it wasnt happening yesterday, now it is.
Every 20 seconds or so, it freezes my entire machine for 20 seconds at a time. Nothing is happening in the editor, nothing is clicked or selected, it just happens when its idling.

Same happens in gles2 or gles3
Cpu spikes in system monitor. Running Godot with --verbose, dosnt detail any particular errors or loading/hanging.

**Comment by Zireael07** [comment] 2020-04-10 07:08
@davidpwbrown: Fancy seeing you here! In the other issue, I remarked that it might be Godot not playing ball with GNOME's compositor - does the problem go away if you fiddle with the compositor settings and/or switch to a different DE?

**Comment by davidpwbrown** [comment] 2020-04-10 13:02
> 
> 
> @davidpwbrown: Fancy seeing you here! In the other issue, I remarked that it might be Godot not playing ball with GNOME's compositor - does the problem go away if you fiddle with the compositor settings and/or switch to a different DE?

Not tried that yet, booting into Windows for the being (ugh!) to run the project, It did *seem* that alt-tabbing to Godot editor in Ubuntu did seem to trigger it more often, so perhaps the compositor is a cause, Ill fiddle with it and report back later.

**Comment by sinistro25** [comment] 2020-04-15 22:13
I'm having a similar problem, after some minutes of utilization the program freezes and refuses to be killed even with a SIGKILL (didn't know that was possible :o ), On further investigation running 'ps' on it return 'STATUS DNsl' indicating that the process is in uninterruptible sleep now (that's why SIGKILL didn't work)!!!

My PC:
OS: Ubuntu 18.04.4 LTS x86_64 
Host: XPS 15 9575 
Kernel: 4.19.0-041900-generic
CPU: Intel i7-8705G (8) @ 3.100GHz

**Comment by Skaruts** [comment] 2020-05-19 13:57
I'm having BSODs again while using 3.2.1. I checked if this had anything to do with my system overheating or something, but at least as far as CPU and GPU are concerned, that's not the case. 

And then Godot 3.1.1 never, ever makes my system crash, so I'm less suspicious that this is a problem on my end. Gonna keep using that one for now.  

---

Windows 7 (64 bits)
ATI Radeon HD 4870
Intel Core Duo 2.13Mhz

**Comment by Calinou** [comment] 2020-05-19 14:03
@Skaruts Which renderer are you using? On such an old AMD graphics card, you should use the GLES2 renderer. (But even then, it might not have ideal OpenGL 2.1 support.)

**Comment by Skaruts** [comment] 2020-05-19 16:05
@Calinou I am on GLES2, yes. 

But I think my card supports 3, at least according to _OpenGL Extensions Viewer_ OpenGL 3.3 and GLES3 are supported. I just never use GLES3 because godot stalls, which may be #20566, but I haven't tested it. Other than that godot runs perfectly fine for me in GLES3, afaict (I don't know if it causes BSODs, though).

**Comment by KoBeWi** [comment] 2020-06-12 14:21
Soo my brother has similar issue. He says that using Godot might freeze his laptop and sometimes it even deletes his scripts (this somewhat reminds me of #25545).

He's using Windows 10 x64 with ATI Radeon, I don't know exact model though and can't check right now.

**Comment by Adz214** [comment] 2022-10-11 15:48
I have the same issue. After opening a project in the editor & idling for 5-10 mins (not touching anything), Godot will hang. On clicking the editor it will freeze, killing Godot via task manager will cause the OS to crash & restart. No error messages are logged.

Sometimes the same issue occurs when the editor is minimized & hasn't been interacted with for 5-10 mins, even though I'm using other programs.

**Godot version:**
Godot_v3.5.1-stable

**OS/device including version:**
Windows 10
Processor	Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz   2.21 GHz
Installed RAM	16.0 GB (15.9 GB usable)
System type	64-bit operating system, x64-based processor

**Comment by Calinou** [comment] 2022-11-04 22:04
Closing in favor of https://github.com/godotengine/godot/issues/18871. Please consolidate reports about random freezing there, but try to include profiler or debugger information if you can. Otherwise, we can't do anything to resolve this issue.

**Closed** 2022-11-04 22:06 UTC
Labels: bug, archived, topic:editor
