### ISSUE TITLE
Shadow glitch

### ISSUE THREAD

**Issue by cutepig49** [godotengine/godot#9829] opened 2017-07-25 01:41 UTC
**Operating system or device - Godot version:**
windows7 x64
https://bintray.com/calinou/godot/editor/2017-07-24.11c14b8

**Issue description:**
Look at the shadow, it looks like be cut at half.
![gif](https://user-images.githubusercontent.com/3340057/28551843-12a367c0-711d-11e7-90ef-bbafffc0a2ad.gif)

**Steps to reproduce:**
Import the project provided below, and open Game.tscn.

**Link to minimal example project:**
[WeirdShadow.zip](https://github.com/godotengine/godot/files/1171692/WeirdShadow.zip)

**Comment by Noshyaar** [comment] 2017-07-25 10:27
Bisection says 9483613, but I'm not really sure since this scene uses MeshInstance with plane mesh, which doesn't exist before that commit, so I tested with TestCube instead. The glitch isn't as bad as shown. So I'm not sure if the issue comes from that commit or before that.

**Comment by djrm** [comment] 2017-07-25 18:12
it might be caused by the lack of contact shadows.
https://twitter.com/reduzio/status/829151000007151616

i have a similar looking scene that can be fixed with contact enabled, except for this #9740
![screenshot from 2017-07-25 13-07-22](https://user-images.githubusercontent.com/1103897/28586888-d6d0fea6-713a-11e7-8115-545aa6991ff2.png)

**Comment by Zylann** [comment] 2017-07-25 19:58
It looks like shadow bias is set too high. If you use a directional light you can tune it down to reduce the gap drastically. Only then, see if you need contact shadows.

**Comment by djrm** [comment] 2017-07-25 20:03
@Zylann thats true, but by default is set to 1, so maybe a better default would be 0.08, it makes shadows look way better.

![screenshot from 2017-07-25 15-03-16](https://user-images.githubusercontent.com/1103897/28591203-6f178a04-714a-11e7-9e8c-100278b14808.png)

**Comment by reduz** [comment] 2017-08-22 12:58
I don't know what the best defaults are, any help regarding testing, checking the value other engines have as default, etc. would help

**Comment by reduz** [comment] 2017-08-30 11:10
closed via a1d7c496b

**Closed by reduz** 2017-08-30 11:10 UTC
Labels: bug, topic:rendering
