### ISSUE TITLE
Godot can't read non ascii characters properly

### ISSUE THREAD

**Issue by Ryptun** [godotengine/godot#4423] opened 2016-04-24 17:54 UTC
I made thread about this long time ago but this bug still exists in 2.0.2
https://github.com/godotengine/godot/issues/2254

While exporting godot is searching for template in:
C:\Users\Rafa\AppData\Roaming\Godot\templates\android_debug.apk
instead of
C:\Users\Rafał\AppData\Roaming\Godot\templates\android_debug.apk

**Comment by akien-mga** [comment] 2016-04-24 17:57
Closing as duplicate of #2254, one report is enough since the initial issue hasn't been fixed and the bug report is still open :)

**Closed by akien-mga** 2016-04-24 17:57 UTC
