### ISSUE TITLE
Inheriting an inherited scene causes error on save: Index p_idx = X out of bounds 

### ISSUE THREAD

**Issue by RafaelVidaurre** [godotengine/godot#88258] opened 2024-02-12 22:23 UTC
### Tested versions

- Reproducible in 4.3-dev3 [d3352813e]
- Reproducible in 4.3-dev2
- Not reproducible in 4.2

### System information

v4.3.dev.custom_build [d3352813e] 

### Issue description

When saving a scene that inherits from another inherited scene containing at least one child node, this error appears.
<img width="1258" alt="Screenshot 2024-02-12 at 10 23 25 PM" src="https://github.com/godotengine/godot/assets/1808674/46509c08-8220-4818-a337-281106e5c182">

### Steps to reproduce

* Create a scene (scene_1)
* Add a child node
* Create an inherited scene from scene_1 (scene_2)
* Add a child node
* Create an inherited scene from scene_2 (scene_3)
* Save scene_3

### Minimal reproduction project (MRP)

[Archive.zip](https://github.com/godotengine/godot/files/14251512/Archive.zip)

**Comment by akien-mga** [comment] 2024-02-20 11:05
Probably duplicate of #87424 ? @Rindbee

**Comment by Rindbee** [comment] 2024-02-20 11:21
Yes, it's a duplicate.

**Closed** 2024-02-20 11:53 UTC
Labels: bug, topic:core, regression
