### ISSUE TITLE
Virtual Scipting: Nodes change size randomly when selected

### ISSUE THREAD

**Issue by novemberist** [godotengine/godot#9154] opened 2017-06-13 15:34 UTC
Arch Linux, Godot 3.0 master

VS scripting nodes often randomly expand when being moved or selected. Example:

![vscript](https://user-images.githubusercontent.com/7927471/27090789-7bd892ea-505e-11e7-8de2-ab6d05687c35.gif)

**Comment by groud** [comment] 2017-06-13 15:48
Isn't that a feature ? ^^
Is this happening with any node or only action ones ?

**Comment by novemberist** [comment] 2017-06-13 15:52
Happens with other Nodes too and not only with those that are actively selected, but randomly. The way nodes expand (and reset) size is unpredictable and annoying - i doubt this is a feature.

**Comment by groud** [comment] 2017-06-13 15:56
(the feature part was a joke... :) )

I believe the problem may come from the drawing function, as it happens even when you are just moving the selection rectangle. Should be investigated.

**Comment by vnen** [comment] 2017-06-13 16:25
Duplicate of #6381.

**Closed by vnen** 2017-06-13 16:25 UTC
