### ISSUE TITLE
Gl_Compatibility renderer missing 3D shadows

### ISSUE THREAD

**Issue by DSGuy02** [godotengine/godot#67866] opened 2022-10-25 10:30 UTC
### Godot version

4.0 beta 3 mono

### System information

Linux, OpenGL 3, Intel HD Graphics 4000, Mesa 18.3.6

### Issue description

Settiing `rendering/renderer/rendering_method` to gl_compatibility causes the sky and meshes and to not get rendered on runtime, but they look fine in the editor. Sprite3D and Shadows from DirectionLight3D does not get rendered at all.

How it looks in the editor, notice the highlighted nodes are Sprite3D.
![in_editor](https://user-images.githubusercontent.com/17575526/197745395-3585eba2-971b-4bd0-bc71-fa6e1e09fed3.png)

How it looks with DirectionalLight3D and shadows enabled, notice the absence of shadows.
![in_editor_with_lighting](https://user-images.githubusercontent.com/17575526/197748314-02849e85-9b95-4d47-afd0-7e0c55143361.png)

Running the scene, the sky, lighting, and sprite3ds does not get rendered, the meshes comes out as pink.
![running_scene](https://user-images.githubusercontent.com/17575526/197745434-fae072f0-9133-4c48-97fc-59b9eb18bbd8.png)

### Steps to reproduce

- Create new project and set the all rendering to 'gl_compatibility'
- Make a 3D scene
- Add or import any kind of meshes
- Add a Sprite3D node and use godot's icon.svg (or any image) as texture
- Add DirectionalLight3D and enable shadow
- Add a camera
- Run the scene

### Minimal reproduction project

[OpenGl_Render_Test.zip](https://github.com/godotengine/godot/files/9859469/OpenGl_Render_Test.zip)

**Comment by mohammedzero43** [comment] 2022-10-25 11:39
Tried it on Nvidia MX450 , Got Green / White  artifacts sometimes , and rendered well at other times ..

I attached new environment to the camera and it fixed it

**Comment by DSGuy02** [comment] 2022-10-25 11:44
> I attached new environment to the camera and it fixed it

That fixed it for me as well, at least there's a workaround

**Comment by DSGuy02** [comment] 2022-10-25 12:07
> I attached new environment to the camera and it fixed it

Adding a WorldEnvironment to the scene seems to make the meshes render now, however setting the Background mode to 'sky' yields nothing, and the Sprite3D and shadows still don't get rendered
![running_scene_with_custom_environment](https://user-images.githubusercontent.com/17575526/197768378-3f3d1b63-20a6-4bb4-a192-546501145b36.png)

**Comment by kleonc** [comment] 2022-10-25 12:38
`Sprite3D` not rendering is a duplicate of #67700 (already fixed), not sure about the other issues.

**Comment by mrjustaguy** [comment] 2022-10-25 14:07
shadow rendering hasn't been reimplemented yet.

**Comment by Calinou** [comment] 2022-10-25 14:58
> Adding a WorldEnvironment to the scene seems to make the meshes render now, however setting the Background mode to 'sky' yields nothing, and the Sprite3D and shadows still don't get rendered

Did you add a sky material? You can copy the current preview sun and sky using the "three vertical dots" button at the top of the 3D editor viewport. To do so, you need to remove the existing WorldEnvironment and/or DirectionalLight3D node from your scene first (if you added one).

**Comment by DSGuy02** [comment] 2022-10-25 16:26
> Did you add a sky material? You can copy the current preview sun and sky using the "three vertical dots" button at the top of the 3D editor viewport. To do so, you need to remove the existing WorldEnvironment and/or DirectionalLight3D node from your scene first (if you added one).

I just followed your steps and was able to successfully recreate the default environment, thank you. I think this workaround should suffice until a proper fix had been made.

**Comment by Calinou** [comment] 2023-05-14 02:32
- Duplicate of https://github.com/godotengine/godot/issues/66596.

**Closed by Calinou** 2023-05-14 02:32 UTC
Labels: bug, topic:rendering, topic:3d

**Comment by sygi** [comment] 2023-05-14 11:21
Is there some context I can read about the decision to not implement shadows? It does seem like a significant limitation until (if!) vulkan for web lands

**Comment by Zireael07** [comment] 2023-05-14 11:50
@sygi: There is no such decision. Shadows are planned, just didn't happen yet. Features in Godot in general happen on a best case basis, with few dedicated contributors...
