### ISSUE TITLE
ResourceLoader don't load resource with parameters in the _init constructor

### ISSUE THREAD

**Issue by peterhoglund** [godotengine/godot#53447] opened 2021-10-05 20:45 UTC
### Godot version

3.3.4 stable

### System information

MacOS Big Sur 11.6

### Issue description

When saving and loading using ResourceSaver and ResourceLoader resources don't get loaded back properly if they are instantiated with parameters in the constructor. The resource that is loaded is an empty resource without the script.

### Steps to reproduce

Create a resource from script that takes a parameter in the constructor and load it with ResourceLoader.

```
extends Resource
class_name Item

var item_name : String
func _init(_name : String):
    item_name = _name
```

```
item = Item.new("Item Name")

ResourceSaver.save("user://resource_save_data.tres", item)

var load_game = ResourceLoader.load("user://resource_save_data.tres")
print (load_game.item_name)
```

This will throw an error `Invalid get index 'item_name' (on base 'Resource')`. There is also an error in the debugger for the ResourceLoader.load():
```
E 0:00:00.668   _create_instance: Condition "r_error.error != Variant::CallError::CALL_OK" is true. Returned: __null
  <C++ Source>  modules/gdscript/gdscript.cpp:121 @ _create_instance()
  <Stack Trace> LoadTest.gd:7 @ _ready()
```

### Minimal reproduction project
[LoadTestProject.zip](https://github.com/godotengine/godot/files/7291299/LoadTestProject.zip)

Edit: fixed code typos and uploaded a test project

**Comment by peterhoglund** [comment] 2021-10-07 12:52
Thank you for clearing this out. After further testing, I think the key problem here was that I had forgotten about the `export` keyword and the warning or errors did not explain that well. It had worked before so the behavior isn't fully consistent.

This will not work, and not give any hints about why
```
var item_name : String
func _init(_name := ""):
    item_name = _name
```

However, this will work, even without the `export` keyword
```
var item_name : String
func _init():
    item_name = "Item Name"
```

This will not work even with the `export` keyword and will throw the errors I got
```
export var item_name : String
func _init(_name : String):
    item_name = _name
```

But this will work and is the way it is supposed to be done I guess.
```
export var item_name : String
func _init(_name : String = ""):
    item_name = _name
```

It would be nice to have more descriptive errors. I couldn't understand the `E 0:00:00.668   _create_instance`-error or what to make out of it.

**Comment by alexdevteam** [comment] 2021-10-31 19:38
Ideally the error should be output in the editor itself too, instead of only at runtime.

**Comment by AnidemDex** [comment] 2021-10-31 19:52
Happens in 3.4 RC2
```
E 0:00:01.317   _create_instance: Condition "r_error.error != Variant::CallError::CALL_OK" is true. Returned: nullptr
  <C++ Source>  modules/gdscript/gdscript.cpp:115 @ _create_instance()
```
> Indeed, the errors should be given more explicit messages with the _MSG variant of the error macros.

Here's the related line where the error is triggered, if someone can make a PR to add a description to this error (I don't know how)
https://github.com/godotengine/godot/blob/23955fc282b95bcd318034b5de536d42f2a08359/modules/gdscript/gdscript.cpp#L115

**Comment by Calinou** [comment] 2022-02-19 18:03
Duplicate of https://github.com/godotengine/godot/issues/15866 (same cause).

**Closed by Calinou** 2022-02-19 18:03 UTC
Labels: enhancement, topic:core, needs testing
