### ISSUE TITLE
4.3beta3 NavigationRegion2D bake_navigation_polygon

### ISSUE THREAD

**Issue by 1823988919** [godotengine/godot#94484] opened 2024-07-17 20:01 UTC
### Tested versions

4.3beta3

### System information

4.3beta3

### Issue description

NavigationRegion2D: when use  bake_navigation_polygon() in code, i can see NavigationRegion changed in debug,but the NavigationAgent2D cant find the new path to target, only happened in beta3.  

### Steps to reproduce

11111111111111111111111111111

### Minimal reproduction project (MRP)

N/A

**Comment by AThousandShips** [comment] 2024-07-17 20:12
Please upload an MRP to make this easier to test, or add more details on how you set things up
- A small Godot project which reproduces the issue, with no unnecessary files included. Be sure to not include the `.godot` folder in the archive (but keep `project.godot`).
- Having an MRP is very important for contributors to be able to reproduce the bug in the same way that you are experiencing it. When testing a potential fix for the issue, contributors will use the MRP to validate that the fix is working as intended.
- Drag and drop a ZIP archive to upload it (max 10 MB). **Do not select another field until the project is done uploading.**
- **Note for C# users:** If your issue is *not* C#-specific, please upload a minimal reproduction project written in GDScript. This will make it easier for contributors to reproduce the issue locally as not everyone has a .NET setup available.

**Comment by smix8** [comment] 2024-07-17 20:27
Thanks for reporting.  Duplicate of https://github.com/godotengine/godot/issues/94358 that was very recently fixed with PR https://github.com/godotengine/godot/pull/94362 that will be part of the next beta release so closing.

**Closed by smix8** 2024-07-17 20:27 UTC
Labels: needs testing, topic:navigation, topic:2d
