### ISSUE TITLE
Slow startup time on games due to async(?) audio devices

### ISSUE THREAD

**Issue by dandevs** [godotengine/godot#30894] opened 2019-07-28 17:07 UTC
**Godot version:**
3.1.1

**OS/device including version:**
Windows 10

**Issue description:**
I have an issue where my audio device, a PnP USB DAC that is a **discrete asynchronous USB audio receiver** (nuforce udac 3) causes things like executable games from godot (empty project) and launching the game via F5 in the editor to launch around 5-10 seconds later. I have the same issue with love2d but nowhere else. Using a different audio device, it all launches instantly. I'm not entirely sure if its the device itself, but I feel like the main culprit is the aforementioned async nature of the device. 

In OpenAL/love2d I get this error: **AL lib: (EE) alc_cleanup: 1 device not closed**
I know Godot doesn't use OpenAL, but this is the only clue I have. If you could point me to where I can get logs for this particular issue I'd be happy to copy and paste them for you.

From wikipedia on asynchronous circuits: `An asynchronous circuit, or self-timed circuit, is a sequential digital logic circuit which is not governed by a clock circuit or global clock signal. Instead it often uses signals that indicate completion of instructions and operations, specified by simple data transfer protocols. `

**Comment by Calinou** [comment] 2019-07-28 17:41
This could be caused by Godot scanning for USB devices on startup. See https://github.com/godotengine/godot/issues/20566.

**Comment by Calinou** [comment] 2020-02-17 15:01
I'll close this as a duplicate of #20566, now that the original issue has been renamed.

**Closed by Calinou** 2020-02-17 15:01 UTC
Labels: bug, platform:windows, topic:audio, topic:editor
