### ISSUE TITLE
'Error' texture on focused MenuButton

### ISSUE THREAD

**Issue by GalanCM** [godotengine/godot#729] opened 2014-09-25 14:44 UTC
If I add a MenuButton to a scene and run it, whenever it has keyboard focus a texture with the word 'Error' is overlayed on the button. This occurs this both the default theme and custom themes.

**Comment by alxcyl** [comment] 2015-02-05 09:23
Currently experiencing this, too, on v1.0 stable. It appears when you click on a `MenuButton` object and click somewhere else to dismiss the menu, the text "ERROR" appears on top of the object.

**Comment by akien-mga** [comment] 2015-10-31 09:27
Is this issue still valid in the current master branch?

**Comment by vnen** [comment] 2015-10-31 15:48
I'm not able to reproduce this in current master (bd736e5). I'll close it and if someone experiences the issue it can be reopened.

**Comment by eska014** [comment] 2015-11-01 09:20
This can be reproduced with the "Tracks" button in the animation edtior:
![menubutton](https://cloud.githubusercontent.com/assets/6996191/10868058/f52b3fe8-8081-11e5-860b-9e41f5b76a46.gif)
For this demonstration, I set an exaggerated minimum size.
This is in current master (281d6fac1edd4a5b06692b850c00db6a5a9bbb46).

**Closed** 2015-11-18 22:43 UTC
Labels: bug, confirmed, topic:core
