### ISSUE TITLE
_init function not invoke correctly

### ISSUE THREAD

**Issue by CsloudX** [godotengine/godot#50174] opened 2021-07-05 08:59 UTC
### Godot version

4.0dev.calinou[9b8095ad0]

### System information

Window 10

### Issue description

Code like this:
```
class ValBase:
    func _init(val):
        prints("valbase init",val)

class ValA extends ValBase:
    var nn

class ValB extends ValBase:
    var nn

func _ready():
    var a = ValA.new("a")  # no print
    var b = ValB.new("b") # no print
```
I think it should print something(should invoke ValBase._init), but it not

sorry i can't upload a reproduction project, because my computer no network and i report this use my phone.

### Steps to reproduce

1. create a project
2. create a scene and copy this code
3. run

**Comment by KoBeWi** [comment] 2021-07-05 10:26
Duplicate of #42506

As a workaround you can do
```
class ValA extends ValBase:
	func _init(val):
		super._init(val)
```

**Closed by KoBeWi** 2021-07-05 10:26 UTC
