### ISSUE TITLE
get_method_list() returns wrong information about methods in GDScript

### ISSUE THREAD

**Issue by sian2005** [godotengine/godot#50415] opened 2021-07-13 11:01 UTC
### Godot version

v3.2.4.rc1.official

### System information

Windows 10

### Issue description

As a quick declaration before further investigation, `get_method_list()` returns everything correctly on engine declared methods, but it does not on GDScript's. There, properties of arguments revert to defaults, like the name property gets arg0, arg1, ..., same as the types, hints, ...

To further clarify, here's a screenshot from a function I created in GDScript explicitly mentioning the type and the default value:
![image](https://user-images.githubusercontent.com/62208362/125438934-fc078e0f-0d35-446e-988d-715b670ff4c2.png)

On a breakpoint after declaration of the variable "`method`", (= "`test`" from `get_method_list()`)
You can first see that the variable with type int (= 2) just gets 0, same as the hint, hint_string, and the usage, which is always 7. This too applies on the second and third argument. (They are exactly thesame exept for the `name`: arg1 and arg2)
![image](https://user-images.githubusercontent.com/62208362/125437309-e231c5be-f229-4a57-8c47-47b4cc930cb5.png)

The default arguments, (the second and third argument on the method "`test`"), also do not appear.
![image](https://user-images.githubusercontent.com/62208362/125438298-4c622874-6af5-4a83-bfbf-fb662c4d2284.png)

And as you might've guessed, the "`return`" specifications also does not represent the one in the method.
![image](https://user-images.githubusercontent.com/62208362/125439516-2442af55-648c-410b-ba33-6cfa4721ed07.png)

Here: #33624 is another issue describing thesame problem.

### Steps to reproduce

Create a method which you call in de ready function that
- firstly iterates upon the get_method_list() in a for loop and stores the specific function, in my case "test", in a variable:
![image](https://user-images.githubusercontent.com/62208362/125440139-1b1fcc84-cc59-4813-b76b-2edb6351c0d9.png)

- Then, create a breakpoint, or type `breakpoint` after the for loop:
![image](https://user-images.githubusercontent.com/62208362/125440392-3e1f159e-9b6a-4fc2-9291-7e150237c75b.png)

- Finally, run the project and examine the results in the debugger.

### Minimal reproduction project

Here: [Minimal Reproduction Project of get_method_list() bug.zip](https://github.com/godotengine/godot/files/6808278/Minimal.Reproduction.Project.of.get_method_list.bug.zip) you can find the minimal reproduction project.

There are comments in the Script.gd:
> Check for the Dictionary "method" in Locals in the debugger when you run the project.
> There, you can open "args", "default_args" and the "return" specifications.

**Comment by timothyqiu** [comment] 2021-07-13 11:37
Duplicate of #33624.

**Closed by timothyqiu** 2021-07-13 11:37 UTC
Labels: bug, topic:gdscript

**Comment by sian2005** [comment] 2021-07-13 12:50
> Duplicate of #33624.

The other issue is similar, but its not a duplicate. My confusion came from it being tagged topic:core, and mine is topic:gdscript, so I thought I could make a new one, and make it a bit more tidy than the previous xD

**Comment by timothyqiu** [comment] 2021-07-13 13:01
I added the "topic:gdscript" because it's the GDScript implementation of that method that has the bug. Other modules like VisualScript implemented the method but seems work fine.

It's fine to open an issue if you're not sure whether it's a duplicate :)
