### ISSUE TITLE
Rename physics layers and name dialog box

### ISSUE THREAD

**Issue by rayosdev** [godotengine/godot#14367] opened 2017-12-07 06:55 UTC
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Windows 10, Godot 3.0

**Issue description:**
Clicking the Collision Layer or Collision Mask in the Inspector opens a dialog box named "Physics Layers" in both instances and should probably be called layers when clicking the layers filed and masks when clicking mask field to not confuse the user

**Steps to reproduce:**
Click the Collision Layer or Collision Mask in the Inspector

**Link to minimal example project:**
https://filebin.ca/3jqBcPyctHdN/masksandlayersrename.gif

**Comment by akien-mga** [comment] 2017-12-07 07:04
Duplicate of #14363 filed a couple hours before :)

**Closed by akien-mga** 2017-12-07 07:04 UTC
