### ISSUE TITLE
On startup shows the "Please confirm..." No projects dialog and then gets unresponsive, regardless of choice.

### ISSUE THREAD

**Issue by Overload86** [godotengine/godot#58060] opened 2022-02-13 19:31 UTC
### Godot version

v4.0.alpha2.official.79077e6c1

### System information

Windows 11 64 Bit, Geforce 2060 Super, latest drivers

### Issue description

The confirmation dialog is literally the only thing working. After clicking Cancel (or the option to open the Asset Library) the whole Project Manager is static. Cannot change language, on mouse-over nothing gets highlighted and upon clicking anywhere in the window, Windows hangs a bit and shows the "Not responding" dialog.

Console says:

```
Godot Engine v4.0.alpha2.official.79077e6c1 - https://godotengine.org
Vulkan API 1.2.189 - Using Vulkan Device #0: NVIDIA - NVIDIA GeForce RTX 2060 SUPER

ERROR: Condition "err" is true. Returning: ERR_CANT_CREATE
   at: swap_buffers (drivers/vulkan/vulkan_context.cpp:1956)
ERROR: Condition "err" is true. Returning: ERR_CANT_CREATE
   at: swap_buffers (drivers/vulkan/vulkan_context.cpp:1956)
ERROR: Vulkan: Did not create swapchain successfully.
   at: (drivers/vulkan/vulkan_context.cpp:1880)
ERROR: Condition "err" is true. Returning: ERR_CANT_CREATE
   at: swap_buffers (drivers/vulkan/vulkan_context.cpp:1956)
```

### Steps to reproduce

This happens as soon as I cancel the first dialog. Tried the compiled binaries, as well as cloning master and compiling myself.

**Comment by Calinou** [comment] 2022-02-13 20:30
Duplicate of https://github.com/godotengine/godot/issues/57937 (same cause).

**Closed by Calinou** 2022-02-13 20:30 UTC
