### ISSUE TITLE
[4a9] @onready does not work with script extension

### ISSUE THREAD

**Issue by DatBrute** [godotengine/godot#61708] opened 2022-06-05 01:42 UTC
### Godot version

4.0 alpha 9 d9daf38

### System information

Windows 11, GLES3, NVIDIA GeForce RTX 3050

### Issue description

@onready does not do anything when used in a script that is extended by another script (a superclass).

Neither does ready(), but that seems intentional.

### Steps to reproduce

Provided is a working (non-bugged) minimal reproduction in v3.4.4, and a non-working (bugged) minimal reproduction in v4.0.

v3.4.4 correctly outputs "hey1 ho1"
v4.0a9 incorrectly outputs "honull"

### Minimal reproduction project

[onready_test_3.4.4.zip](https://github.com/godotengine/godot/files/8839178/onready_test_3.4.4.zip)
[onready_test_4.0a9.zip](https://github.com/godotengine/godot/files/8839179/onready_test_4.0a9.zip)

**Comment by KoBeWi** [comment] 2022-06-05 01:49
Duplicate of #52223

**Closed by KoBeWi** 2022-06-05 01:49 UTC
