### ISSUE TITLE
CollisionShape2D looks weird in editor

### ISSUE THREAD

**Issue by OlliO6** [godotengine/godot#68895] opened 2022-11-19 19:22 UTC
### Godot version

4.0.beta5.mono

### System information

Windows 11, NVIDIA GeForce GTX 1650 Ti, Vulkan(I think)

### Issue description

![image](https://user-images.githubusercontent.com/104021024/202867616-aacd0ba9-1c6f-426b-924d-d8dae87a4023.png)

The CollisionPolygon2D looks like it should be but as you can see the Collision shapes are looking weird.
All have a second border that goes further than the collision detection actually is wich is kinda misleading.
And I think you can see what else is looking weird.

### Steps to reproduce

Just add a CollisionShape2D to your scene.

### Minimal reproduction project

N/A

**Comment by Calinou** [comment] 2022-11-19 19:29
Duplicate of https://github.com/godotengine/godot/issues/56320.

**Closed by Calinou** 2022-11-19 19:29 UTC
