### ISSUE TITLE
Editor/Project mouse offset Win10

### ISSUE THREAD

**Issue by shiMusa** [godotengine/godot#37302] opened 2020-03-25 17:22 UTC
**Godot version:**
3.2.1 stable

**OS/device including version:**
Win 10 1909

**Issue description:**
[video_2020-03-25_13-14-00.zip](https://github.com/godotengine/godot/files/4382384/video_2020-03-25_13-14-00.zip)

This issue occurs even with keyboard. It seems like the highlight on the button is wrong?
Other menus work just fine.

**Steps to reproduce:**
(Fresh project), go to "Project", hover with mouse over buttons.

**Minimal reproduction project:**
Simple blank project.

**Comment by Calinou** [comment] 2020-03-25 17:30
Duplicate of #23069. Try updating your graphics driver to the latest version *provided by Intel*. Alternatively, start the Godot editor with the `--verbose` command-line argument, which can also mitigate the issue.

**Closed by Calinou** 2020-03-25 17:30 UTC
