### ISSUE TITLE
Property Editor String Input - Text Select and Ctrl+Z bug.

### ISSUE THREAD

**Issue by WatIsDeze** [godotengine/godot#5642] opened 2016-07-11 11:41 UTC
**Windows 10, 64 bit - Godot 2.0.4.1 x64 exe:**

**Issue description** (what happened, and what was expected):
I had expected that when selecting text from right to left, in the string property text input field, it'd scroll along. Also, ctrl+z seems to fail. However I feel there is no need to make a separate issue here, since the text input field seems quite broken this way.

**Steps to reproduce:**
Well, in my case, I created a scene, Node2D, added on to that a WindowDialog, and wanted to edit its title. Thus, after entering a long string and trying to select a part of it, I ran into these issues.

**Link to minimal example project** (optional but very welcome):
No example project but an image explaining what it DOES do when I try to select it....

![ex](https://cloud.githubusercontent.com/assets/10252874/16729495/18ce5518-476d-11e6-8c4e-3cd0be4f1d9d.png)

**Comment by neikeq** [comment] 2016-07-12 22:24
I will have a look at the scroll bug tomorrow.
About Ctrl+Z, LineEdit only has a single level undo, which means you can only undo once... I am not sure if there is a reason not to add proper undo/redo to LineEdit or if it just was never done. In any case, I would consider that a duplicate of #5545

**Closed** 2016-07-18 22:29 UTC
Labels: bug, confirmed, topic:core
