### ISSUE TITLE
Editor GUI Text Controls Hide the Last Character

### ISSUE THREAD

**Issue by Faustabov** [godotengine/godot#3643] opened 2016-02-10 01:10 UTC
Using Windows 10 and the rc1 version of 2.0

When using any of the editor controls that work with text the last character is hidden when the control is too small to show the last character, for instance, in the below image, you can see that the Path field is missing the final character in the path 'x', you also can't see my caret at this point, if I move the caret back a space it shows up properly in the field.

You should be able to reproduce this by clicking any text field and attempting to move the caret to the location following the final character.

![godottextboxlastcharactermissing](https://cloud.githubusercontent.com/assets/17059062/12936104/13fd6f32-cf69-11e5-967b-3deb63d1b995.png)

**Comment by zhagsenkk** [comment] 2016-02-10 03:41
I can reproduce  it.

**Comment by nopeson** [comment] 2016-02-10 06:19
Same, when using LineEdit in project.

**Comment by akien-mga** [comment] 2016-02-17 16:56
@MarianoGnu @neikeq @TheHX Any clue?

**Comment by akien-mga** [comment] 2016-06-03 07:33
Closing as duplicate of #4992 which is a bit broader.

**Closed by akien-mga** 2016-06-03 07:33 UTC
Labels: bug, topic:core, usability
