### ISSUE TITLE
Copy/Cut on X11 not working in the editor

### ISSUE THREAD

**Issue by hpvb** [godotengine/godot#10431] opened 2017-08-18 23:51 UTC
Fedora 26 / Godot master (fc89cf90b268dfb25e039ae248e3305bb593be41)

**Issue description:**
On my box I cannot copy any content from the Godot editor at all. Primary selection does not work and neither does explicitly pressing 'ctrl-c', or even right-clicking on the selected text and selecting 'copy' or 'cut'

When selecting 'cut' the text does disappear, but does not appear on the clipboard.

**Steps to reproduce:**

* Copy some text from a different X11 program
* Paste it in godot editor (this works)
* Select different text in the editor
* Press ctrl-c, ctrl-x, or select the option from the context menu
* Press ctrl-v

Notice that the text previously on the clipboard gets pasted.

**Comment by eon-s** [comment] 2017-08-19 16:13
On Ubuntu+Gnome, Godot master bacfe7a55.

I can copy and cut with ctrl-c, ctrl-x, and right click options, but then I can just use the shortcut (ctrl+v) to paste, the right click menu does not give the paste option outside Godot.

**Comment by hpvb** [comment] 2017-08-27 12:32
This seems to be related to Godot's use of the PRIMARY clipboard. I'll think about how to fix this properly

**Comment by reduz** [comment] 2017-09-29 19:33
@hpvb any ideas? :P

**Comment by AlexHolly** [comment] 2017-10-22 00:03
I can't reproduce any of those issues using kubuntu 17.04

Maybe related to #4209

**Comment by Applemann** [comment] 2018-01-06 21:25
@hpvb any news with this?? I am testing Godot Engine v3.0.beta.build2 on Ubuntu 16.04
and it is very frustrating
I thing that this is very important to fix
```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.3 LTS
Release:        16.04
Codename:       xenial
```

[bad-copy.zip](https://github.com/godotengine/godot/files/1609232/bad-copy.zip)

**Comment by bfloch** [comment] 2018-01-09 07:31
FYI: I am on the latest master - Fedora 26 but can not reproduce this.

**Comment by Applemann** [comment] 2018-01-10 20:14
@bfloch try it on Ubuntu 16.04
```
>>> lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.3 LTS
Release:	16.04
Codename:	xenial
```

how reproduce is here:
[bad-copy.zip](https://github.com/godotengine/godot/files/1620317/bad-copy.zip)

**Comment by hpvb** [comment] 2018-01-10 20:53
I think the problem is related to having a clipboard manager but I haven't spend any further time on this. I'll try to get a PR out for this soon.

**Comment by akien-mga** [comment] 2018-01-16 10:24
Not critical for the upcoming 3.0 release, so moving to the next milestone. A fix can still be cherry-picked for 3.0.x maintenance releases once available in the master branch.

**Comment by hpvb** [comment] 2018-01-28 23:42
@eon-s @AlexHolly @Applemann @bfloch I've tested #16156  this on some configurations on my local machine but I don't have i3 or unity to test with. Would you mind testing the mentioned PR and report on it please?

**Comment by eon-s** [comment] 2018-01-29 09:57
@hpvb Unity may not need to be a concern anymore because it was officially abandoned and won't be on the next LTS.

**Comment by Applemann** [comment] 2018-01-29 11:03
@hpvb I tested it on my computer (Ubuntu 16.04.3 LTS, with i3wm) and now it is working.. thanks ;)

**Comment by AlexHolly** [comment] 2018-01-29 13:27
I am not able to reproduce this issue on Ubuntu 17.10-GNOME Shell 3.26.2 with or without the fix so :+1:

**Comment by hpvb** [comment] 2018-01-29 15:06
It probably just means that the Java app doesn't understand text/plain?charset=utf8 atom. Do you see the same problem when you try to copy/paste from a GTK3 app?

**Comment by AlexHolly** [comment] 2018-01-29 15:49
No it only happens with Godot. Any other app works fine.

**Comment by hpvb** [comment] 2018-01-29 16:41
I'll check DBVisualizer then if I can find it. It appears to all work fine trying to paste into Eclipse and some other Java programs I have laying about.

**Comment by hpvb** [comment] 2018-01-29 17:00
I've found other reports of Java programs with this issue. I've found a way to make the Java program at least not error, but pasting still isn't working.

**Comment by hpvb** [comment] 2018-01-29 17:21
@AlexHolly can you please test the PR again? I believe I've fixed the Java compatibility issue. There was actually still a bug in the clipboard handling code. Thanks for testing!

**Comment by hpvb** [comment] 2018-01-29 17:39
@AlexHolly if you had tried before my last push please try again. I tried to 'tidy something up' and completely broke everything

**Comment by AlexHolly** [comment] 2018-01-29 19:25
I think it works now #4209 is also solved :+1:

**Closed** 2018-01-30 12:39 UTC
Labels: bug, platform:linux
