### ISSUE TITLE
C# and Visual Studio Code: Connecting Signals from the GUI doesn't add a method.

### ISSUE THREAD

**Issue by DarylGraves** [godotengine/godot#41152] opened 2020-08-09 20:24 UTC
**Godot version: v3.2.2stable.mono.official**

**OS/device including version:Windows 10  (Build 18363)**

**Issue description:**
When connecting a signal via the GUI, the new signal method is not being added to the script.

**Steps to reproduce:**
Under Editor Settings -> Mono I have the External Editor set as "Visual Studio Code". Tried this on multiple projects (going through the tutorial series)

**Minimal reproduction project:**
N/A

Apologies if this isn't a bug or has been reported. I couldn't find it but the tutorials are implying it should append the method template. I am wondering if it's because it's C# and/or an external editor? I've tried completely closing the file in VSC and connecting signal but it just never appears in the file regardless of text editor I open it in.

**Comment by Calinou** [comment] 2020-08-09 20:31
Duplicate of https://github.com/godotengine/godot/issues/23208.

**Closed by Calinou** 2020-08-09 20:31 UTC
