### ISSUE TITLE
Audio Limiter Effect Introduces Clipping Instead of Preventing It

### ISSUE THREAD

**Issue by jitspoe** [godotengine/godot#36631] opened 2020-02-28 06:12 UTC
**Godot version:** 3.2, 3.1

**OS/device including version:** Windows 8.1

**Issue description:** Audio Limiter effect does not reduce volume to avoid clipping.  Instead, it increases volume, and introduces clipping where there was none.

Example of sound after going through Limiter:
![image](https://user-images.githubusercontent.com/7751182/75515000-eba3d200-59c6-11ea-8f46-a30178136b23.png)
Note how the waves spike up after exceeding certain values.

Sine wave example.
Before:
![image](https://user-images.githubusercontent.com/7751182/75515070-168e2600-59c7-11ea-822f-2fbc018a782b.png)
After:
![image](https://user-images.githubusercontent.com/7751182/75515119-345b8b00-59c7-11ea-9ea1-8eafd6831881.png)

**Steps to reproduce:** Add Limiter effect to master bus with default settings.  Play a sound that exceeds the soft clip threshold.

**Minimal reproduction project:**
[test_audio_limiter.zip](https://github.com/godotengine/godot/files/4265455/test_audio_limiter.zip)
WARNING: TURN YOUR VOLUME DOWN BEFORE PLAYING!

**Comment by Calinou** [comment] 2020-02-28 08:15
cc @reduz, as he implemented the various audio effects.

**Comment by jitspoe** [comment] 2020-02-29 09:01
Looking at the code, it seems like it's not fully implemented.  There's a property, soft_clip_ratio, which is not used.  Also, the logic seems to be operating on a purely per-sample basis.  I've never implement a limiter before, but it seems like they typically have some sort of attack and decay when sound crosses some threshold, so it should scale the volume down for a bit, then back up again over time using a curve, which would require some sort of persistent data to track that volume change.

**Comment by Calinou** [comment] 2020-02-29 13:47
> I've never implement a limiter before, but it seems like they typically have some sort of attack and decay when sound crosses some threshold,

Isn't that the job of a compressor audio effect?

**Comment by jitspoe** [comment] 2020-03-01 16:50
Compressors and limiters are very similar.  To be honest, I've never fully understood the difference between them.

**Comment by Calinou** [comment] 2020-04-12 19:52
@jitspoe [This page](https://www.musicianonamission.com/limiter-vs-compressor/) explains the difference between a compressor and limiter.

**Comment by freemanfromgodotengine** [comment] 2020-05-04 21:54
I can confirm this bug. In my experiments parts of the amplitude selected by Celling Db and Treshold Db are being distorted, so basically limiter does not work at all in my Godot 3.2.1.

Like @jitspoe nicely presented, limiter clearly does not attenuate the high amplitude part of the sound wave. Actually it sounds like it does contrary and distorts those fragments even more by increasing their level.

**Comment by morphiser** [comment] 2020-08-25 14:40
It's questionable what the limiter in godot is trying to achieve. Usually a limiter uses a little bit of lookahead to calculate the signal energy and then regulates the gain accordingly (with an adjustable attack/release time). The current implementation rather seems to aim at a soft clipping function. Clipping does not have any time dependencies but generally leads to some signal distortion (introducing harmonics and aliasing), which may or may not be desired.
An actual limiter is usually used on the master bus to prevent digital clipping of the mix.

**Comment by Calinou** [comment] 2020-08-25 15:52
It will probably take a while before this is fixed, as reduz implemented all the audio effects but is currently busy working on the Vulkan renderer for 4.0. That is, unless someone contributes a pull request :slightly_smiling_face:

**Comment by Tony-Goat** [comment] 2020-08-26 22:23
I implemented a temporary solution for this to work for now. I'm no audio engineer, so my solution may fall apart under certain circumstances.

**Comment by morphiser** [comment] 2020-08-29 21:51
@Tony-Goat I couldn't really reproduce your result with this patch. Which parameters did you use for this screenshot?

**Comment by Tony-Goat** [comment] 2020-08-30 00:01
> @Tony-Goat I couldn't really reproduce your result with this patch. Which limiter parameters did you use for this screenshot?

The results I posted are from the default settings. I used the test project provided here.

**Comment by akien-mga** [comment] 2023-02-22 14:21
Is this still reproducible in 4.0 RC 3 or later?

**Comment by freemanfromgodotengine** [comment] 2023-03-02 22:34
> Is this still reproducible in 4.0 RC 3 or later?

Yes. Problem remains in 4.0-stable released yesterday.

**Comment by wareya** [comment] 2023-11-03 20:43
Limiters should never have any kind of soft clipping or hard clipping configuration. If they have it, they're not limiters, they're waveshapers.

Proper limiters are very similar to peak compressors with an infinite compression ratio, but they have a different type of attack curve. Compressors have a type of attack curve that allows part of the audio signal to temporarily be louder than the limit. Limiters have an attack curve that does lookahead to prevent this from happening, or just zero attack if lookahead is too hard to implement. (Compressors also usually use RMS instead of peak amplitude, and limiters always use peak amplitude, but there isn't a significant conceptual difference between the two.)

Here's an example:

![image](https://github.com/godotengine/godot/assets/585488/f9a7a480-eaee-4309-9ee7-7627d419e088)

Allowing the compressor effect to go down to zero attack would allow people to use it as a limiter. However, "good" limiters have lookahead, adding a small amount of latency (usually 1ms or 2ms) to allow for an attack curve without causing the initial transient spike to go above the limit. This is necessary because otherwise the upswing part of loud signals gets clipped as the limiter's compression value goes down every sample to meet the new peak.

Robust attack curves for limiters are basically blurs applied to the envelope. If you implement attack this way, you also need to implement "sustain", or else the envelope won't fully envelope the signal during transients. You can implement sustain by basically doing `max(sample[t], sample[t-1], sample [t-2], ...)`. For long attack/sustain values, this is expensive unless you use a bucketing circular buffer, where every N samples gets bucketed into its own max bucket and you only recalculate the buckets that have had a sample changed.

If you don't want to deal with the complexity of a lookahead/sustain system, you can "over-limit" signals when they cross the limiting threshold, by setting the compression value to like, `0.9 * limit_amplitude / actual_amplitude` instead of `limit_amplitude / actual_amplitude`, when the actual amplitude is greater than the limit amplitude.

**Comment by wareya** [comment] 2023-11-04 00:55
I just implemented a correct limiter in gdscript and uploaded it under a public domain license (CC0) here:

https://github.com/wareya/LimiterTest

Main.gd contains a limiter that implements release, sustain, *and* attack. The core logic of it is around 50 lines long (90 lines total including declarations and initialization etc). As examples of why it has to be 50 lines long, MainNoAttack.gd and MainSimple.gd implement limiters that lack sustain and/or attack; they produce distorted output.

In case I never get around to it, I give permission to anyone to port this to C++ (or do absolutely anything with it in general; it's CC0).

Here's what the output sounds like for three sine waves added together, faded out, and multiplied by 4.0 before being limited:

(make sure to unmute)

https://github.com/godotengine/godot/assets/585488/5cbc3be6-af85-4d67-a7f9-769a14707e08

**Comment by lander-vr** [comment] 2024-02-27 18:23
I tried to implement the GDScript example limiter @wareya made in C++ through GDExtension. It limits, however there is an issue where it seems to miss the first few samples that are above the ceiling threshold, and it doesn't limit those.

Here is my repo: https://github.com/lander-vr/GDExtension_sandbox

I admittedly don't fully grasp how those buckets and memory arrays work, as well as why the box_blur variables are multiplied by 32767.0, to then later at output be divided again. @wareya (or someone else who knows) if you have some time, it would be great if you could give some further explanations on these, if you wouldn't mind taking a peek at this.

Either way thanks for sharing that GDScript example project, I'm learning a bunch!

This screenshot shows a constant very quiet white-noise, and a single loud sine beep played over top. The ceiling is set to -24dB, which is why there's such an extreme difference between those first loud samples that you can see, and the actually limited samples.
![image](https://github.com/godotengine/godot/assets/31851431/c8567ecc-f734-4222-97c9-b01cffb578d6)

> However, "good" limiters have lookahead, adding a small amount of latency (usually 1ms or 2ms) to allow for an attack curve without causing the initial transient spike to go above the limit.

It seems like this is the issue I'm experiencing, but I'm not sure what the best way would be to go about adding that latency.

**Comment by wareya** [comment] 2024-02-28 07:21
I'll try to take a look at some point within the next couple days.

The bucketing system is a fast way to calculate the max() of a large series of numbers without having to recalculate the whole thing each time. Instead, it only has to recalculate a small fraction of it.

The `32767.0` stuff is part of a way to implement a moving-window box blur with only two additions/subtractions per timestep instead of having to recalculate the whole thing from scratch every timestep. Doing this with floats is numerically unstable, so it has to do them with integers instead. Multiplying by `32767` allows it to convert to the equivalent of signed 16-bit PCM instead of everything getting rounded to -1, 0, or 1. (Float audio data is normally in the range -1.0 to 1.0.)

**Comment by akien-mga** [comment] 2024-03-25 14:26
Should be fixed by the new AudioEffectHardLimiter added in #89088.

**Closed by akien-mga** 2024-03-25 14:26 UTC
Labels: bug, confirmed, topic:audio
