### ISSUE TITLE
print function doesn't print any output even I restarted Godot

### ISSUE THREAD

**Issue by GittyGrubHub85** [godotengine/godot#42717] opened 2020-10-11 12:33 UTC
**Godot version: 3.2**

**OS/device including version: Windows 10**

**Issue description:**

I was having troubles from my script of code that my print function did NOT print any output of my Godot Editor console. The script is already attached on a node, it used to print an output at runtime but it suddenly stopped printing any output later in runtime. Even I closed the editor and open it back, there's still no output even I've code it in my ready() function. I was also opening another Godot editor that I hadn't closed off yet so I'm using 2 Godot Editors for my 2 projects. I closed both of them, opened Godot back, and the problem has been fixed now I can see the printed texts on my output Godot Editor from the print("text") function. Even I've fixed the problem but it was an unimaginable problem I didn't find it common. I hope the developers have read this problem and can do to fix about this sneaky problem**

**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by sonic2kk** [comment] 2020-10-11 12:35
Can you please provide a minimal reproduction project? Then we can run your exact project and see what the issue is 🙂

**Comment by Calinou** [comment] 2020-10-11 12:38
Duplicate of https://github.com/godotengine/godot/issues/22723.

**Closed by Calinou** 2020-10-11 12:38 UTC

**Comment by GittyGrubHub85** [comment] 2020-10-11 12:42
> Can you please provide a minimal reproduction project? Then we can run your exact project and see what the issue is 🙂

It's my first time adding an issue and I may mess up time by time. I'm not familiar with minimal reproduction project

**Comment by sonic2kk** [comment] 2020-10-11 12:51
@GittyGrubHub85 A minimal reproduction project is the smallest, most stripped down project you can zip up.

Say for example you're working on a game. You don't want to send us your entire game! So you just make a project that only has the bug in question.
