### ISSUE TITLE
Metadata entires are case sensitive, but it changes displaying entry names

### ISSUE THREAD

**Issue by 3da** [godotengine/godot#88438] opened 2024-02-17 13:28 UTC
### Tested versions

v4.2.1.stable.mono.official [b09f793f5]

### System information

Windows 10

### Issue description

Wrong metadata entry names are displaying

### Steps to reproduce

Add 2 entry names with same text but only different letter case.
For example:
To
to

### Minimal reproduction project (MRP)

No need project to reproduce.
![image](https://github.com/godotengine/godot/assets/437616/91a0a59e-87b1-4c9a-8dbb-7ba4e9f722c6)

**Comment by Mickeon** [comment] 2024-02-17 16:27
Duplicate of https://github.com/godotengine/godot/issues/82938 I believe, and an extremely strong reason to change the current behavior.

**Comment by Calinou** [comment] 2024-02-17 21:40
Thanks for the report! Consolidating in https://github.com/godotengine/godot/issues/82938.

**Closed by Calinou** 2024-02-17 21:40 UTC
