### ISSUE TITLE
Syntax errors fail silently in headless mode

### ISSUE THREAD

**Issue by radlotus** [godotengine/godot#79041] opened 2023-07-04 20:28 UTC
### Godot version

4.0 - 4.1.rc3
### Issue description

syntax errors fail silently in headless mode.

```gdscript
extends MainLoop

const foo

func _initialize():
    print(foo)
```

```gdscript
extends MainLoop

xfunc _initialize():
    print(100)
```

```gdscript
extends MainLoop

func _initialize():
    const arr = [1,2,3,4
    print(arr)
```

**Comment by radlotus** [comment] 2023-07-04 20:40
This also seems to fail silently.
```gdscript
extends MainLoop

func _initialize():
asfads
```

**Comment by radlotus** [comment] 2023-07-04 20:57
seems like syntax errors fail silently in headless mode.

**Comment by dalexeev** [comment] 2023-07-05 06:38
* Probably related: #75545.

**Comment by dalexeev** [comment] 2023-07-05 08:36
* Duplicate of #75545.

**Closed by dalexeev** 2023-07-05 08:36 UTC
Labels: bug, topic:gdscript, needs testing
