### ISSUE TITLE
[C#] csproj conditionals break export fields. 

### ISSUE THREAD

**Issue by MaxIsJoe** [godotengine/godot#79839] opened 2023-07-23 22:08 UTC
### Godot version

4.1.1 Stable Mono

### System information

Godot v4.1.1.stable.mono - Windows 10.0.19045 - Vulkan (Compatibility) - NVIDIA GeForce GTX 1650 (NVIDIA; 31.0.15.3179) - AMD Ryzen 5 5600G with Radeon Graphics (12 Threads)

### Issue description

Attempting to use conditionals in the .csproj seems to break the godot project, which makes exported variables impossible as everything is set to `null` in the .tres files and they cannot be edited in the inspector at all.

### Steps to reproduce

1. Do something like this in your .csproj:
```
<Project Sdk="Godot.NET.Sdk/4.1.1">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <EnableDynamicLoading>true</EnableDynamicLoading>
  </PropertyGroup>

  <PropertyGroup Condition="'$(OS)' == 'Windows_NT'">
    <DefineConstants>WINDOWS</DefineConstants>
    <SteamworksDllPath>./Steamworks/Facepunch.Steamworks.Win64.dll</SteamworksDllPath>
  </PropertyGroup>
  <PropertyGroup Condition="'$(OS)' != 'Windows_NT'">
    <DefineConstants>LINUX</DefineConstants>
    <SteamworksDllPath>./Steamworks/Facepunch.Steamworks.Posix.dll</SteamworksDllPath>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="Facepunch.Steamworks">
      <HintPath>$(SteamworksDllPath)</HintPath>
    </Reference>
  </ItemGroup>
</Project>
```

2. Go into Godot
3. Create and attach a script with any exported field like this:
`[Export] private string something;`
4. Compile
5. Attempt to edit any of the variables exported in the editor.

![](https://cdn.discordapp.com/attachments/717024221183868949/1132778549816873030/wea.gif)
![](https://media.discordapp.net/attachments/717024221183868949/1132784625094242324/image.png)

### Minimal reproduction project

use this to replicate project:
```
<Project Sdk="Godot.NET.Sdk/4.1.1">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <EnableDynamicLoading>true</EnableDynamicLoading>
  </PropertyGroup>

  <PropertyGroup Condition="'$(OS)' == 'Windows_NT'">
    <DefineConstants>WINDOWS</DefineConstants>
    <SteamworksDllPath>./Steamworks/Facepunch.Steamworks.Win64.dll</SteamworksDllPath>
  </PropertyGroup>
  <PropertyGroup Condition="'$(OS)' != 'Windows_NT'">
    <DefineConstants>LINUX</DefineConstants>
    <SteamworksDllPath>./Steamworks/Facepunch.Steamworks.Posix.dll</SteamworksDllPath>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="Facepunch.Steamworks">
      <HintPath>$(SteamworksDllPath)</HintPath>
    </Reference>
  </ItemGroup>
</Project>
```

**Comment by raulsntos** [comment] 2023-07-24 09:52
The problem is the usage of `<DefineConstants>` since you are replacing the constants defined by Godot.NET.Sdk.
- So this is a duplicate of https://github.com/godotengine/godot/issues/79605.

You shouldn't need to add `WINDOWS` and `LINUX` constants, Godot already defines constants for each supported platform (these constants are documented in the [_C# features_](https://docs.godotengine.org/en/stable/tutorials/scripting/c_sharp/c_sharp_features.html#full-list-of-defines) page). In this case you'll want to use `GODOT_WINDOWS` and `GODOT_LINUXBSD`.

If you meant to add to the existing constants you should be using `<DefineConstants>$(DefineConstants);WINDOWS</DefineConstants>` instead.

**Closed by raulsntos** 2023-07-24 09:52 UTC
Labels: bug, topic:editor, topic:dotnet
