### ISSUE TITLE
Can not open c# script by editor

### ISSUE THREAD

**Issue by Ling2121** [godotengine/godot#36046] opened 2020-02-09 11:10 UTC
**Godot version:** 3.2
**OS/device including version:** Windows10

**Issue description:** can not open c# script by editor

**Steps to reproduce:** 
 modules\mono\mono_gd\gd_mono_utils.cpp:357 - System.ArgumentException: Illegal characters in path.

**Minimal reproduction project:**

**Comment by Calinou** [comment] 2020-02-09 13:39
@Ling2121 What does the *full path* to the C# script look like?

**Comment by Ling2121** [comment] 2020-02-09 15:22
> @ Ling2121 C＃脚本的_完整路径_是什么样的？

Previous version no problem

**Comment by akien-mga** [comment] 2020-03-02 15:39
There isn't much to go on, but I assume it's a duplicate of #35810.

**Closed by akien-mga** 2020-03-02 15:39 UTC
Labels: bug, regression, topic:editor, topic:mono
