### ISSUE TITLE
draw_line and Sprite3D don't work in HTML5

### ISSUE THREAD

**Issue by bozydar** [godotengine/godot#7176] opened 2016-11-23 10:10 UTC
**Operating system or device - Godot version:**
Fedora 23, x86_64, Godot Engine  v2.1.stable.official

**Issue description** (what happened, and what was expected):
Using `draw_line` on a `TextureButton` works improperly when exported to HTML5.

**Steps to reproduce:**
Drawing on `TextureButton` with a script.

    func _draw():
        draw_line(Vector2(3, 3), Vector2(47, 47), Color(0.5, 0, 0, 0.6), 30)
        draw_line(Vector2(3, 47), Vector2(47, 3), Color(0.5, 0, 0, 0.6), 30)

Running the application (good):
![native](https://cloud.githubusercontent.com/assets/225232/20556675/75459152-b168-11e6-91a2-dd0fe0f6b0a8.png)

Running the application in Firefox 50.0 after exporting it to HTML5 (bad)
![firefox](https://cloud.githubusercontent.com/assets/225232/20556674/75422148-b168-11e6-9cec-9cea194f1347.png)

*Note:* There is no problem with drawing with `draw_primitive()` function.

**Link to minimal example project** (optional but very welcome):

**Comment by GodotIsAMess** [comment] 2016-11-25 02:49
There are so many things wrong with the HTML 5 export it's laughable that anyone would think that people would use Godot solely for HTML 5 games.  Developers are wasting their time by working on fixing kinks and bugs in HTML 5 when there are far bigger issues to fry. (200ms+ sound lag, no OS mouse cursor support, etc).

**Comment by bojidar-bg** [comment] 2016-11-25 08:52
@GodotIsAMess I hope you didn't register a new user just to comment here...

Responding to your comment, I haven't seen any dev recently taking html5 issues anyway (and if they do, it's for the best!).
Also, devs might be wasting there time reading (and responding to) comments like yours, like I just did.
Finally, in case you didn't check news recently, [Godot has been awarded some money to actually fix HTML (using webassembly, websockets and webgl 2.0)](https://godotengine.org/article/mozilla-awards-godot-engine-part-moss-mission-partners-program).

**Comment by GodotIsAMess** [comment] 2016-11-25 15:55
@bojidar-bg Nice logic you got there. Claiming to waste developer time by responding to my comment, but continue to waste time on the HTML 5 export which will never be bug free. There are so many issues evident with it, anyone who would even think about using the HTML 5 export in production would be out of their minds. Godot's other export options are fine though, and the grant is irrelevant as there is still bugs existing in Godot (200ms lag, no mouse cursor OS support = lag when moving around), but let's continue to work on C# integration and fix HTML 5 bugs. What a joke.

**Comment by vnen** [comment] 2016-11-25 16:29
@GodotIsAMess 
> [...] waste time on the HTML 5 export which will never be bug free

First that nothing ever is bug free. Second that issues are unrelated and people working in one part of the engine not always has the knowledge to work on another part, so improving the web export not necessarily hinders progress on the audio engine. Finally, we do not have the resources to hire a bunch of developers to work on "core issues" (which requires knowledge on the respective areas) and everyone here is contributing with free time. If you prefer another engine which is "bug free", you are not forced to use Godot.

**Comment by GodotIsAMess** [comment] 2016-11-25 16:46
@vnen So by your logic, since the audio issue on the native imports isn't there for the HTML 5 exports it's fine? That doesn't even make sense. The issues are still there though, and a lot of developers come to Godot and then later find out about these nasty bugs that completely RUIN their game and immersion levels.  

What I am saying is the people who are in charge (mostly looking at @reduz, @vnen, @bojidar-bg, @akien-mga, and others) -- need to realize what's going on here.  There are two bugs off the top of my head that are **extremely** detrimental and no indie game dev or production company would use Godot for this very reason.

- 200+ms sound delay for playing sound effects
- NO os mouse cursor support

Which every other single game engine I've used don't have these issues. Even Atomic Engine for crying out loud.

However, these have been reported as issues here for months. And if you look at the recent Godot update:

https://github.com/godotengine/godot/compare/2.1.1-stable...master

Over **810 commits** have been committed and NOT one has been for the cursor support, or to the fix audio lag. Why even make a game that has sound effects when it kills the immersion? Why even make a game that uses a custom cursor icon that lags when moved? Do you developers realize that production ready games actually rely on the ability for custom mouse cursor support? Not a sprite that is layered on the screen and has a noticeable delay (which is what Godot does).

Developers that come to Godot use it for months because it's an awesome engine and then later find out about these stupid issues and are heart struck. That's none of my business though,

**Comment by vnen** [comment] 2016-11-25 17:06
@GodotIsAMess try to read again what I wrote and understand "my logic" this time. If you have an issue that is not reported yet, do it or else nobody will ever know. But if you have nothing else to add, refrain to post further comments.

**Comment by GodotIsAMess** [comment] 2016-11-25 17:12
@vnen And your attitude is exactly why Godot is where its at today. Dodge the points raised, and not fixed the essential issues that are required for any game engine to operate. It's really sad to be honest.

- Sound delay lag: https://github.com/godotengine/godot/issues/6965

- Mouse Cursor lag issues https://github.com/godotengine/godot/issues/6929 and https://github.com/godotengine/godot/issues/3086 and [a full list](https://github.com/godotengine/godot/search?p=1&q=mouse+cursor&type=Issues&utf8=%E2%9C%93)

> If you have an issue that is not reported yet, do it or else nobody will ever know

Maybe you should re-read my post. I've already told you, these issues have been REPORTED for months.

**Comment by vnen** [comment] 2016-11-25 17:19
@GodotIsAMess and I have already responded that we do not have the resources to hire knowledgeable developers to fix the bugs so we rely in kind people in the community to do the work for free. Not everyone is willing to do this and we (including you) can't force them to do so.

**Comment by akien-mga** [comment] 2016-11-25 17:35
Don't feed the troll guys, nothing worth commenting on.

**Comment by reduz** [comment] 2016-11-25 17:36
Dear @GodotIsAMess, most game engines written in C++ such as Unity or Unreal have similar limitations when exporting to HTML5, as we use something called "asm.js". It is not an ideal solution and it has several drawbacks that are beyond our ability to fix.

Due to that kind of issues, the [WebAssembly ](http://webassembly.org/)standard is being developed and it will be supported by all the major web browsers next year (Chrome, Firefox, IE and Safari). We have work in progress towards supporting it, but currently it is not stable. Likewise, HTML5 support never left beta status. Until then, I hope you are comprehensive and understanding.

**Comment by reduz** [comment] 2016-11-25 17:41
Here are also some hints for your consideration:

1) Audio lag cannot be fixed because asm.js does not allow threads, so audio must be processed in the main thread, which introduces lag in exchange for reducing sound artifacts. Using SamplePlayer instead of StreamPlayer can reduce lag.
2) Tick lines (with width >1) are unsupported by WebGL, so it's up to you to use something else, such as polygons.
3)  Regarding mouse cursor support, you are the first that complained.

Thanks for your patience!

**Comment by GodotIsAMess** [comment] 2016-11-25 17:47
@akien-mga Yeah, I'm really a troll when the 200ms sound delay bug does exist and ruins immersion for games. As I said, this type of attitude of blaming the reporter and not tackling on the actual issue is what really infuriates me to no end.  

@reduz The audio issues are on **native export**s man, not WebGL / HTML 5. I was just responding to @vnen about his silly argument.

Look:
- Sound delay lag: https://github.com/godotengine/godot/issues/6965

- Mouse Cursor lag issues https://github.com/godotengine/godot/issues/6929 and https://github.com/godotengine/godot/issues/3086 and [a full list](https://github.com/godotengine/godot/search?p=1&q=mouse+cursor&type=Issues&utf8=%E2%9C%93)


Sound delay lag issue above is on native exports. Windows, Linux,etc.  There is a 200+ms delay. And @vnen is telling me that @reduz which can re-write a 3.0 renderer natively cannot isolate / fix a sound audio bug? I highly doubt that.

Reduz most likely can fix these bugs without any problem, it's just the community here @vnen, @akien-mga, and @bojidar-bg  (so far) try to put me off as a troll and not care about the REAL issues. That's why those bugs probably exist because the main person who can fix them **isn't aware**.

**Comment by reduz** [comment] 2016-11-25 17:53
The audio lag issues are in part due to the audio server design. It can't be fixed without rewriting a large part of it (otherwise it will affect  performance negatively). This will happen when Godot 3.0 or 3.1 is out (depending on the timing), so please be patient.

**Comment by akien-mga** [comment] 2016-11-25 18:17
Nobody is saying that the issues you mentioned are not valid. But you are coming out of nowhere with a provocative nickname, hijacking a fully unrelated issue with some weird assumption that we are focusing on the HTML5 export (where did you see that?) to whine about an engine developed by volunteers on their free time in a non-profit manner. Hence my calling you a troll, who is just wasting our time and not at all helping the engine get better.

**Comment by GodotIsAMess** [comment] 2016-11-25 18:18
@reduz Okay, well I appreciate your honesty. 

 I spent MONTHS developing a awesome game on Godot. I think over 10k+ lines of code in GDScript and everything. Hundreds of hours googling for answers, posting on Reddit, Q&A site, etc. 

Then, while finishing up the game I started to notice the mouse cursor lag and audio delay. For example, a player opening a door and the door triggers a "open door sound". Which is then hindered by the 200ms lag. This ultimately ruins the entire game.

I've spent so much time and energy and cannot even publish my fucking game with Godot because of silly issues like that. It's not even fair to Godot either as the engine is SO good, unique and extremely fast with an amazing editor. It's actually depressing those little bugs can ruin the entire game-play experience.

Then, **it infuriates me by trying to get the developers like you aware of this** through **official means of communication** (github), of which I get called a troll and that these issues are not even prevalent. Which couldn't be more wrong. I have a feeling that is part of the reason why those bugs were not fixed in the first place. Soley because you as the main developer were not aware of them by the community correctly.  

As I said, the community relations here is an absolute joke. We have a main developer here (@reduz) who is responding professionally to the real issues I raised, and then we have community support members who don't give a fucking damn about the issues I am raising and think I'm a troll and it's a joke. There's obviously a disconnect somewhere between developer / community communication and that is detrimental towards the development with Godot.

**Comment by GodotIsAMess** [comment] 2016-11-25 18:20
> But you are coming out of nowhere with a provocative nickname

Yeah, because my **provacative** nickname is so insulting! Does my nickname effect your ability to analyze issues? Because I sure as hell hope not.

**Comment by vnen** [comment] 2016-11-25 18:26
@GodotIsAMess had you been part of the many community channels so we actually knew who you are and had not created a GitHub account with an obvious provocative name and had just posted your problems in the in a polite manner we would be more willing to respond. You *are* being a troll, whether the issues are legitimate or not.

You could have just as much created a GitHub account with a regular nickname, posted "Hey guys, I'm having this problem too, do you have a estimate of when it'll be fixed?" We would be happy to respond. We have new issues posted everyday, you are not special just because you *think* your issues are more important than the other.

**Comment by GodotIsAMess** [comment] 2016-11-25 18:27
> @GodotIsAMess had you been part of the many community channels so we actually knew who you are and had not created a GitHub account with an obvious provocative name and had just posted your problems in the in a polite manner we would be more willing to respond. You are being a troll, whether the issues are legitimate or not.

That's the point though. If I were to do it under my main account you guys probably wouldn't even have this conversation in thread and probably just brush it off as "oh an issue that will get fixed later, it's not important".

**Comment by reduz** [comment] 2016-11-25 18:27
@GodotIsAMess There is nothing much that can be done about it, we don't have a dozen of full time developers, so priority usually goes towards what the majority needs or wants. Godot is infinitely better now than it was when released almost 3 years ago. 

We first made it stable, then made the 2D engine really good, and finally we spent a year fixing usability issues everyone complained about, then we implemented multiplayer and visual scripting.  Now we are focusing in the most lagged area, which is 3D, and afterwards the plan is to fix physics, animation and sound. We will eventually reach to a point where everything is more or less there, so we can focus on the smaller stuff (like implementing proper hardware cursor, which is laggy now due to it being software). 

Countless times, the developer decides to work him/herself on fixing what is broken and submit a PR, thanks to Godot being fully open source.  If this is not your case, apologies, but there is nothing more we can do about it.

**Comment by akien-mga** [comment] 2016-11-25 18:30
There are (unpaid) humans reading bug reports. And guess what, it's also humans who fix bugs. And yeah, this might be an epiphany, but humans have feelings. Personally I don't want to write code for you if you can't be courteous and collaborative, and just come bitching about what we're doing for free.

**Comment by GodotIsAMess** [comment] 2016-11-25 18:32
> Personally I don't want to write code for you if you can't be courteous and collaborative, and just come bitching about what we're doing for free.

It's not about me (that's why I made this account) -- It's about the other hundreds of game developers that will spend their time developing a game in Godot and then in the end, find out their fucking sound effects have a 200ms delay that ruin the entire game.  And also that they cannot use a custom mouse cursor. Well, they can, but it will lag since it's just a drawn sprite being updated.

**Comment by vnen** [comment] 2016-11-25 18:32
@GodotIsAMess 
> probably just brush it off as "oh an issue that will get fixed later, it's not important".

Well, the result wasn't any different. You cited known issues planned to be fixed later. You didn't make them be fixed any time sooner.

**Comment by reduz** [comment] 2016-11-25 18:44
@GodotIsAMess but you are welcome to attempt fixing the hardware mouse cursor issue yourself if you need, and we can gladly help

**Comment by SuperUserNameMan** [comment] 2016-11-26 14:05
> It's about the other hundreds of game developers that will spend their time developing a game in Godot and then in the end, find out their fucking sound effects have a 200ms delay that ruin the entire game and end up being a total waste of time.

IMO, someone who is seriously willing to spend lot of time and energy into a serious project, would seriously test and evaluate every aspects of the engine before deciding to use it or not.

**Comment by kubecz3k** [comment] 2016-11-26 15:29
Not a single post here is in the subject, I would like to ask you guys to stop this offtopic here as I will need to clean this issue from irrelevant comments soon.

**Comment by GodotIsAMess** [comment] 2016-11-26 17:07
> IMO, someone who is seriously willing to spend lot of time and energy into a serious project, would seriously test and evaluate every aspects of the engine before deciding to use it or not.

Yeah, that's good to know now after spending  6+ months on Godot isn't it. Thanks for your consideration. 

> Not a single post here is in the subject, I would like to ask you guys to stop this offtopic here as I will need to clean this issue from irrelevant comments soon.

And continue to work on a HTML 5 export which is pointless but not work on fixing the main, essential core bugs that are detrimental towards the entire game engine. The logic this community has is so strong, I might really pass out.

**Comment by bojidar-bg** [comment] 2016-11-26 17:27
@GodotIsAMess Please, if you really, really, think that this discussion about discouraging html5 should continue, open a __new__ issue -- this discussion is _off-topic_ and __unconstructive__ here, and would be deleted as such whenever possible.

Also, I recommend you using your real account, and deleting this fake account of yours (assuming you have a real account) -- not doing so is violation of GitHub's Terms and Conditions.

Finally, you are paying nearly _no_ attention to what is being said here, so I would spend some time to assemble some nice quotes for you:
> @reduz - The audio lag issues are in part due to the audio server design. It can't be fixed without rewriting a large part of it (otherwise it will affect performance negatively). This will happen when Godot 3.0 or 3.1 is out (depending on the timing), so please be patient.
> @reduz - but you are welcome to attempt fixing the hardware mouse cursor issue yourself if you need, and we can gladly help
> @vnen - We have new issues posted everyday, you are not special just because you think your issues are more important than the other.
> @akien-mga - There are (unpaid) humans reading bug reports. And guess what, it's also humans who fix bugs
> @vnen - Second that issues are unrelated and people working in one part of the engine not always has the knowledge to work on another part, so improving the web export not necessarily hinders progress on the audio engine.

Please, consider reading them again, then thinking them over, and __only then__ deciding what and where to post.

(and yes, I really spent 10-15 minutes of my life to respond to a troll... so much for Godot programming today)

**Comment by GodotIsAMess** [comment] 2016-11-26 17:40
@bojidar-bg There it is. I'm a troll because I'm raising completely valid points in regards to the game engine. I know what @reduz has said, and quite frankly I don't care about what the others have said (@vnen, @akien-mga , etc) because @reduz IIRC is the lead developer here.

If I were to make a new issue regarding the sound bug you will close it / delete it too. Don't play games.

**Comment by vnen** [comment] 2016-11-26 17:58
@GodotIsAMess you don't care about what I say and yet expect me to cater to your needs...

FYI reduz is not even working on the web export, if you didn't understand that yet. You don't even know what we are doing. You can just look at the commit log and count how many of them are about HTML5.

**Comment by GodotIsAMess** [comment] 2016-11-26 18:01
> @GodotIsAMess you don't care about what I say and yet expect me to cater to your needs...

FYI reduz is not even working on the web export, if you didn't understand that yet. You don't even know what we are doing. You can just look at the commit log and count how many of them are about HTML5.

Where have I said I expect you to cater to my needs? I'm asking you (and everything) to acknowledge that the sound delay problem is a core, essential issue that will be fixed. It literally is a production stopper bug and is HIGHLY detrimental towards any game developer who wishes to publish games with Godot.. Why can't you guys understand this?

**Comment by punto-** [comment] 2016-11-26 18:07
I agree that the sound issue is a big deal, we shouldn't dismiss it,
instead figure out how to fix it or work around it (possibly by seriously
breaking the audio server on a case-by-case basis). The cursor thing is not
that serious, you should be able to fix it and send a pull request.
The argument that we should stop everything else to fix those issues is
flawed of course, but that's not good enough reason to dismiss the audio
problem.

**Comment by vnen** [comment] 2016-11-26 18:13
The sound issue is very problematic, I think we all agree on that. However, reduz is a single person and he'll eventually get to the audio issue. If there's anyone else who can fix it, great, but until someone like that show up I doubt this can be solved.

**Comment by GodotIsAMess** [comment] 2016-11-26 18:14
@punto- I agree wholeheartedly. 

However, just for the record:

> I agree that the sound issue is a big deal, we shouldn't dismiss it,

But @reduz has said:

> The audio lag issues are in part due to the audio server design. It can't be fixed without rewriting a large part of it (otherwise it will affect performance negatively). This will happen when Godot 3.0 or 3.1 is out (depending on the timing), so please be patient.

If the sound bug is a **big issue**, why wait until 3.0/3.1? Which is possible Q1-Q2 of next year... That's not fair to the game developers who have been working religiously on their projects to end up being hindered by the AudioServer ruining their games immersion levels.

It's not fair to the Godot community here because Godot is a great engine and the possibility of a viral type, AAA game being published under it is GREATLY diminished. And Godot is a unique engine and deserves to be in the limelight for it's awesome features.

And then (my most vehemently point) it's not fair towards game developers who have worked for half a year and then find out about this Audio bug and then cannot publish their game.. That's  just not fair and that's the position I'm in and others will share that same fate if it's not resolved.

**Comment by vnen** [comment] 2016-11-26 18:44
Forget about @GodotIsAMess. All I see is a broken record who just repeats that we *have* to fix the issue *for free* and *right now*, no matter how hard it is to fix or if there's anyone available to dot that. No intention at all to understand what other people are saying. Not a troll because there's a bug, but yes a troll for the wording and behavior and the unwillingness to understand.

@kubecz3k if you please, delete all off-topic comments and lock the issue.

**Comment by GodotIsAMess** [comment] 2016-11-26 18:54
> Forget about @GodotIsAMess. All I see is a broken record who just repeats that we have to fix the issue for free and right now, no matter how hard it is to fix or if there's anyone available to dot that. No intention at all to understand what other people are saying. Not a troll because there's a bug, but yes a troll for the wording and behavior and the unwillingness to understand.

Deleting my posts doesn't change the fact that there is an audio issue that is detrimental towards any game that is published. Silence the truth all you want, it's only hindering and disrespectful towards future game developers that come to Godot and later found out they cannot publish their game after xxx months of work.

**Comment by kubecz3k** [comment] 2016-11-26 21:00
Conversation have been cleaned and locked because of massive offtopic discussion regarding https://github.com/godotengine/godot/issues/6965 and https://github.com/godotengine/godot/issues/4261

**Comment by akien-mga** [comment] 2016-11-27 20:27
Unlocking the issue as it's still valid and should be available for **on-topic** comments. Sorry @bozydar for the mess (pun intended) that happened here.

Note: Any further off-topic discussion may be deleted without notice.

**Comment by eska014** [comment] 2017-01-31 20:01
`draw_line` uses [`_draw_primitive`](https://github.com/godotengine/godot/blob/cdb0be8eed381b6cf28df6bc1eba26bb79eac576/drivers/gles2/rasterizer_gles2.cpp#L165) in the OpenGL ES 2 rasterizer. That function is missing an alternative implementation for WebGL which doesn't use client side arrays (web platform defines `GLES_NO_CLIENT_ARRAYS` for that purpose), causing this error, independent of line width.

Not looking further into this myself with the ES3 rasterizer in the works

**Comment by bojidar-bg** [comment] 2017-03-24 19:59
Is this still valid on master/3.0 (as I heard we now have a ewb platform sort-of working)?

**Comment by eska014** [comment] 2017-04-06 17:40
Tested this, fixed in 3.0

**Comment by Noshyaar** [comment] 2018-04-08 03:25
First of all thank you for your report and sorry for the delay.

We released Godot 3.0 in January 2018 after 18 months of work, fixing many old issues either directly, or by obsoleting/replacing the features they were referring to.

We still have hundreds of issues whose relevance/reproducibility needs to be checked against the [current stable version](https://godotengine.org/download), and that's where you can help us.
**Could you check if the issue that you described initially is still relevant/reproducible and comment about it here?**

For bug reports, please also make sure that the issue contains detailed steps to reproduce the bug and, if possible, a zipped project that can be used to reproduce it right away. This greatly speeds up debugging and bugfixing tasks for our contributors.

Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

Thanks in advance.

*Note: This message is being copy-pasted to many "stale" issues (90+ days without activity). It might happen that it is not meaningful for this specific issue or appears oblivious of the issue's context, if so please comment to notify the Bugsquad about it.*

**Comment by Zireael07** [comment] 2018-08-10 09:40
Why is this still open? Eska said it's fixed in 3.0.

**Comment by Noshyaar** [comment] 2018-08-10 09:44
I'll close it then.

**Closed by Noshyaar** 2018-08-10 09:44 UTC
Labels: bug, platform:html5, topic:rendering

**Comment by HummusSamurai** [comment] 2018-09-24 14:48
@eska014 Do you remember the commit that fixed this in 3.0 ? I'm using draw_line() in 2.1 and would like to try backporting it if it's possible.

**Comment by akien-mga** [comment] 2018-09-24 17:40
The renderer was changed between 2.1 and 3.0, and likely fixed this issue. That can't be backported :)
