### ISSUE TITLE
Dragging a skeleton bone root to be the immedate bone under it crashes

### ISSUE THREAD

**Issue by fire** [godotengine/godot#52533] opened 2021-09-10 13:13 UTC
### Godot version

1234c2b

### System information

popos 21.04 Linux

### Issue description

Dragging a skeleton bone root to be the immedate bone under it crashes.

### Steps to reproduce

1. Import a glb with a skeleton.
2. Click on the skeleton3d node
3. Drag the root node on the inspector on the right to the node just underneath it

### Minimal reproduction project

See instructions.

**Comment by Calinou** [comment] 2021-09-10 13:31
cc @TwistedTwigleg

**Comment by TwistedTwigleg** [comment] 2021-09-11 00:52
I can confirm the bug. I’m not sure what is causing it (nor if my changes caused it) but I will try to take a look at it and see what I can find out.

**Comment by TokageItLab** [comment] 2023-01-15 18:30
@fire I can't reproduce, already fixed by something? Also I think #52575 is the wrong way for a fix, since bone editor trees are not allowed to be dragged in the first place.

**Closed** 2023-01-15 18:40 UTC
Labels: bug, topic:editor, confirmed, crash, topic:3d
