### ISSUE TITLE
Import mesh with missing material file softlocks/crashes Godot

### ISSUE THREAD

**Issue by DarioDaF** [godotengine/godot#49177] opened 2021-05-28 20:22 UTC
**Godot version:** 364ea7f280a3f074795e542b16b1d0ec76cf6ce2

**OS/device including version:** Windows 10

**Issue description:**

Dragging any obj file without its corresponding mtl file will freeze the ide at 100% reimporting assets and create errors in the console.
It's expected to fail gracefully or not process the resource without soft locking the IDE (imho).

![image](https://user-images.githubusercontent.com/10617344/120037787-775d4180-c002-11eb-9fdb-6cfcfa7a2192.png)
Main window

![image](https://user-images.githubusercontent.com/10617344/120037830-8a701180-c002-11eb-879a-979ccb7492df.png)
Console

```
ERROR: Task 'reimport' already exists.
   at: (editor\progress_dialog.cpp:159)
ERROR:ERROR: Couldn't open MTL file 'untitled.mtl', it may not exist or not be readable.
 Couldn't open MTL file 'untitled.mtl', it may not exist or not be readable.
   at:    at: (editor\import\resource_importer_obj.cpp:48)
(editor\import\resource_importer_obj.cpp:48)
ERROR:ERROR: Couldn't open MTL file 'res://untitled.mtl', it may not exist or not be readable.
 Couldn't open MTL file 'res://untitled.mtl', it may not exist or not be readable.
   at:    at: (editor\import\resource_importer_obj.cpp:48)
(editor\import\resource_importer_obj.cpp:48)
ERROR: Cannot create file 'res://.godot/imported/untitled.obj-ca5f032a2b78f72fc26fcfb202d29dda.mesh'.
   at: (core\io\resource_format_binary.cpp:1776)
ERROR: Cannot save Mesh to file 'res://.godot/imported/untitled.obj-ca5f032a2b78f72fc26fcfb202d29dda.mesh'.
   at: (editor\import\resource_importer_obj.cpp:531)
ERROR: Error importing 'res://untitled.obj'.
   at: EditorFileSystem::_reimport_file (editor\editor_file_system.cpp:1788)
```

**Steps to reproduce:**
Create any obj wavefront file with material.
Drag the obj file in the project tree and wait.

**Minimal reproduction project:** Godot empty 3D project

**Extra notes:**
I'm not sure if this is an exporter problem or what, but given the trace it seems sensible to suppose it can happen with any multifile resource to be imported.

**Comment by Calinou** [comment] 2021-05-29 00:36
Duplicate of https://github.com/godotengine/godot/issues/48265.

**Closed by Calinou** 2021-05-29 00:36 UTC
Labels: bug, topic:3d, topic:editor, topic:import
