### ISSUE TITLE
Connecting using wss works with html5 export but not on any other platform

### ISSUE THREAD

**Issue by meruiden** [godotengine/godot#34083] opened 2019-12-03 13:55 UTC
**Godot version: Godot_v3.2-beta1_win64**

**OS/device including version: Windows 10 and android 9**

**Issue description:**
When I try to connect over wss to my server from the html5 export of the game, it works without issue. but whenever using any other platform it throws

```
thirdparty/mbedtls/library/ssl_tls.c:5757: x509_verify_cert() returned -9984 (-0x2700)
ERROR: _do_handshake: TLS handshake error: -9984
   At: modules/mbedtls/stream_peer_mbedtls.cpp:91
mbedtls error: returned -0x2700
```

I added the crt to trusted certificates and also to the project settings certificate.

(my crt is from LetsEncrypt and im connecting to an url, not an ip)
**Steps to reproduce:**
Connect to a wss server using WebSocketClient.connect_to_url

**Comment by meruiden** [comment] 2019-12-03 13:57
@Faless  any thoughts?

**Comment by Faless** [comment] 2019-12-03 15:09
Trying on latest master on Linux, it appears to work with my LetEncrypt cert.
Can you provide a minimum reproduction project?

**Comment by meruiden** [comment] 2019-12-03 15:14
I am hosting my project privately on gitlab, i dont mind giving you access to it.

my connection script looks like this

``` python

func initClient():
	print("starting client...")

	if(client == null):
		client = WebSocketClient.new()
		
		client.set_verify_ssl_enabled(ssl)

		if(ssl && (OS.get_name() == "Windows" || OS.get_name() == "Android")):
			print("trusting crt...")
			var cert = X509Certificate.new()
			cert.load("res://SpaceIOServer/certificate.crt")
			#client.set_trusted_ssl_certificate(cert)
			
				
		client.connect("connection_established", self, "_connected_ok")
		client.connect("connection_error", self, "_connection_error")
		client.connect("connection_closed", self, "_connection_closed")

	if(ssl):
		client.connect_to_url("wss://" + sslUrl + ":" + String(port), PoolStringArray(), false)
	else:
		client.connect_to_url("ws://" + url + ":" + String(port), PoolStringArray(), false)

	pass
```


the server runs on https://ws-rs.org/

**Comment by meruiden** [comment] 2019-12-03 15:19
I can also wetransfer the source if that helps

**Comment by Faless** [comment] 2019-12-03 15:30
Well, I guess I'll have to check against the actual SSL server. Can you send me the address? In IRC pm if you prefer privacy (`fales` on freenode)

**Comment by Faless** [comment] 2019-12-03 15:33
Ah, btw, in your code `#client.set_trusted_ssl_certificate(cert)` is commented out so you are not actually setting it (but I guess that was just one of your tests). Also, you shouldn't need one if you are not building with `builtin_certs=no`.

**Comment by meruiden** [comment] 2019-12-03 15:52
I used the latest 3.2 build from the official godot repo. does that have builtin_certs enabled? yes right?

**Comment by meruiden** [comment] 2019-12-03 15:54
After removing that line and the path from the settings i still get

```
thirdparty/mbedtls/library/ssl_tls.c:5757: x509_verify_cert() returned -9984 (-0x2700)
ERROR: _do_handshake: TLS handshake error: -9984
   At: modules/mbedtls/stream_peer_mbedtls.cpp:91
mbedtls error: returned -0x2700

```

**Comment by meruiden** [comment] 2019-12-05 13:42
okay so after investigating with @Faless  it became clear that my server did not pass the CA certificate. I managed to fix that by adding the root and intermediate certificate in my rust webserver like so:

```rust

        let acceptor = Rc::new({
            let mut builder = SslAcceptor::mozilla_intermediate(SslMethod::tls()).unwrap();
            builder.set_private_key(&pkey).unwrap();
            builder.set_certificate(&cert).unwrap();
            builder.add_extra_chain_cert(inter).unwrap();
            builder.add_extra_chain_cert(ca).unwrap();
            builder.check_private_key().unwrap();
            builder.build()
        });
``` 
the ssl checker https://www.sslshopper.com/ssl-checker.html#hostname=spaceio.csteenhuis.com:3012

now also tells me that that works. but i still get the same error

```
thirdparty/mbedtls/library/ssl_tls.c:5757: x509_verify_cert() returned -9984 (-0x2700)
ERROR: _do_handshake: TLS handshake error: -9984
   At: modules/mbedtls/stream_peer_mbedtls.cpp:91
mbedtls error: returned -0x2700
```

@Faless can you see what goes wrong with this setup? you still have my source right?

**Comment by Faless** [comment] 2019-12-06 08:53
If you are specifying the ssl certificate file in Godot (via project settings, or `trusted_ssl_certificate` property), make sure that file also include the full chain.
I can now connect to that server without specifying a custom SSL certificate. The connection though, seems to be immediately reset by the server.
This seems to be an issue with the server, `openssl s_client` exits right after handshake, `ncat` shows input/output error. In general, the server seems to close the TCP connection immediately after the handshake.

I'm also getting `PR_CONNECT_RESET_ERROR` with Firefox when loading the website.

**Comment by meruiden** [comment] 2019-12-06 13:32
My website was down for some reason. its up again. i tried to do the trusted_ssl_certificate and indeed it connects without errors but disconnects immediately because the server throws

```
TRACE 2019-12-06T13:29:45Z: ws::connection: Ready to read handshake from 143.176.185.153:61069.
TRACE 2019-12-06T13:29:45Z: ws::stream: Attempting to read ssl handshake.
TRACE 2019-12-06T13:29:45Z: mio::sys::windows::selector: set readiness to Readable
TRACE 2019-12-06T13:29:45Z: mio::sys::windows::tcp: scheduling a write of 4095 bytes
TRACE 2019-12-06T13:29:45Z: mio::sys::windows::tcp: done immediately with 4095 bytes
TRACE 2019-12-06T13:29:45Z: mio::sys::windows::selector: set readiness to Readable | Writable
TRACE 2019-12-06T13:29:45Z: ws::io: Encountered error while reading: unexpected EOF
ERROR 2019-12-06T13:29:45Z: ws::handler: WS Error <Io(Custom { kind: Other, error: "unexpected EOF" })>
DEBUG 2019-12-06T13:29:45Z: ws::io: WebSocket connection to 143.176.185.153:61069 disconnected.
```

which is still weird because html5 has no problem connecting to the server

**Comment by meruiden** [comment] 2019-12-06 14:10
I fixed the PR_CONNECT_RESET_ERROR.

adding the certificate with trusted_ssl_certificate seems to work. the only issue is that godot seems to disconnect too quickly

```
TRACE 2019-12-06T14:05:04Z: ws::connection: Ready to write handshake to 143.176.185.153:65369.
TRACE 2019-12-06T14:05:04Z: ws::connection: Finished writing handshake response to 143.176.185.153:65369
DEBUG 2019-12-06T14:05:04Z: ws::io: WebSocket connection to 143.176.185.153:65369 disconnected.
```

this is the server output

**Comment by meruiden** [comment] 2019-12-06 14:49
The webserver seems to fail at parsing the headers because its empty. does godot send headers by default?

**Comment by Faless** [comment] 2019-12-06 17:23
> The server seems to fail at parsing the http request because its empty. does godot send this by default?

No, Godot sends a valid WebSocket handshake request:
```
GET / HTTP/1.1
Host: spaceio.csteenhuis.com:3012
Upgrade: websocket
Connection: Upgrade
Sec-WebSocket-Key: 8q83uWLiAGtXPf0aSqlpug==
Sec-WebSocket-Version: 13


```

**Comment by Faless** [comment] 2020-01-14 17:03
This seems to have been due to server certificate misconfiguration. Closing as non-godot related.

**Closed by Faless** 2020-01-14 17:03 UTC
Labels: needs testing, topic:network

**Comment by spaghiajoeojo** [comment] 2020-06-03 19:28
I have the same problem on 3.2.1.stable.official (downloaded from steam).
I have a NodeJS server using ws packet from npm and a self-signed certificate. HTTPS works great and if I use a client for test (I tried 2-3 browser extensions) wss:// URL works as expected. But, in Godot, using the script provided in the docs, I get the op's error and the connection can't be established.
