### ISSUE TITLE
Error when I change from OpenGL3 to OpenGL2 in Godot 3.1

### ISSUE THREAD

**Issue by JA-Developer** [godotengine/godot#21643] opened 2018-09-01 03:58 UTC
Hello, How are you?
Recently, I downloaded Godot 3.1 Alpha, and well, All run well when I use OpenGL3, but when I change to OpenGL2 the screen freezes up, and the graphical driver stop working.
![image](https://user-images.githubusercontent.com/40817962/44942147-b3d3b400-ad68-11e8-9a1b-336e5d60e7d0.png)
![image](https://user-images.githubusercontent.com/40817962/44942156-ed0c2400-ad68-11e8-923d-e5c92fb4435b.png)
![image](https://user-images.githubusercontent.com/40817962/44942154-debe0800-ad68-11e8-8f82-0c755f45828b.png)

**Comment by JA-Developer** [comment] 2018-09-01 03:59
Thanks for your attention!!

**Comment by usbhell** [comment] 2018-09-01 14:11
I have the same issue although I don't know if its the same cause. I simply create a new project and select GLES2. After a restart the system freezes (OSX El Capitan 10.11.6 Geforce 9400). If im very lucky I can force quit the application but usually the screen goes a bit garbled and the whole system hangs. Well after multiple restarts and fiddling about I found if I commented out the following lines in default_env.tres I could open the project and carry on.

[resource]

;background_mode = 2
;background_sky = SubResource( 1 )

**Comment by JA-Developer** [comment] 2018-09-01 16:44
No, every time that I try to load the project, the result is the same. It's like if my graphical driver had an trouble. Even if I reboot my computer.

**Comment by williamd1k0** [comment] 2018-09-01 16:52
Maybe related to #20588 and #21551

**Comment by reduz** [comment] 2018-09-08 00:01
Please submit a project that causes this

**Comment by Zireael07** [comment] 2018-09-08 07:07
I believe it's a dupe of #21551

**Comment by akien-mga** [comment] 2018-09-10 16:39
Indeed, duplicate of #21551.

**Closed by akien-mga** 2018-09-10 16:39 UTC
Labels: bug, topic:rendering
