### ISSUE TITLE
New Scene doesn't create a new scene

### ISSUE THREAD

**Issue by Eko450-eng** [godotengine/godot#62452] opened 2022-06-27 11:02 UTC
### Godot version

v3.4.4.stable.arch_linux

### System information

Arch Linux

### Issue description

When creating a new scene by going to file system tab > Right click > New Scene > Enter Name > Save.
It opens a new tab with the scene but won't create the actual scene until you save it in the tab that has been opened which caused some confusion and also feels just wrong since the scene will not take over the name that you have passed into the popup, instead it will just be called [empty].

### Steps to reproduce

Open a Project
Right click anywhere in the FileSystem tab
Hit “New Scene”
Enter a name
Save

**Comment by Calinou** [comment] 2022-06-27 12:36
A scene can't be saved to disk unless you add at least one node to it, so I suppose the dialog should also ask you a root node type to add at the same time.

**Comment by akien-mga** [comment] 2022-06-27 12:57
Duplicate of #34524.

**Closed by akien-mga** 2022-06-27 12:57 UTC
Labels: enhancement, topic:editor, usability
