### ISSUE TITLE
arm64 .NET missing from macOS export 4.3

### ISSUE THREAD

**Issue by roonskipp** [godotengine/godot#94631] opened 2024-07-22 16:55 UTC
### Tested versions

- reproducible in 4.3-beta3

- tested in 4.2.2 mono where it works with export templates for 4.2.2

### System information

MacBook Pro M3 Pro  Sonoma 14.3

### Issue description

When exporting godot .NET project to macOS the arm dylibs are missing for .NET. Showing package contents, resources folder only contains: x86_64. macos_arm64 is missing. 

This gives the following error: 
<img width="968" alt="Screenshot 2024-07-22 at 18 51 15" src="https://github.com/user-attachments/assets/95186b9b-0638-4bde-bd12-8a6e964e3c56">

### Steps to reproduce

Create a new project in godot 4.3 beta 3 with .NET and attempt to export for macOS. Open the exported .dmg file and run the application. 

### Minimal reproduction project (MRP)

[mrp.zip](https://github.com/user-attachments/files/16337242/mrp.zip)

**Comment by raulsntos** [comment] 2024-07-23 01:41
Your MRP doesn't contain a C# project or the export preset used to export the project. Also, it may be useful to know the information of your .NET installation (run `dotnet --info` in a terminal).

For macOS we should be building the C# project for 2 architectures:

https://github.com/godotengine/godot/blob/4e5ed0bbfb56f0a71eb61c868f965476652c23df/modules/mono/editor/GodotTools/GodotTools/Export/ExportPlugin.cs#L188-L192

Can you share the contents of the `.dmg` file?

**Comment by bruvzg** [comment] 2024-07-23 05:45
Most likely caused by signing issue (try switching to ad-hoc signature) and already fixed by https://github.com/godotengine/godot/pull/94518

**Comment by roonskipp** [comment] 2024-07-23 08:12
> Most likely caused by signing issue (try switching to ad-hoc signature) and already fixed by #94518

I attempted to change the Codesign to Built in (Ad-Hoc only), and it successfully built for arm64. 

I could launch the MRP project. 

However on my actual project, the built app cannot run, with the following output errors: 

```Godot Engine v4.3.beta3.mono.official.82cedc83c - https://godotengine.org
Vulkan 1.2.283 - Forward Mobile - Using Device #0: Apple - Apple M3 Pro

2024-07-23 10:09:42.646 TypeOne[35331:11847404] WARNING: AVCaptureDeviceTypeExternal is deprecated for Continuity Cameras. Please use AVCaptureDeviceTypeContinuityCamera and add NSCameraUseContinuityCameraDeviceType to your Info.plist.
Failed to create CoreCLR, HRESULT: 0x80070008
ERROR: hostfxr_get_runtime_delegate failed with code: -2147450743
   at: initialize_hostfxr_self_contained (modules/mono/mono_gd/gd_mono.cpp:237)
ERROR: Parameter "load_assembly_and_get_function_pointer" is null.
   at: initialize_hostfxr_and_godot_plugins (modules/mono/mono_gd/gd_mono.cpp:296)
ERROR: Parameter "godot_plugins_initialize" is null.
   at: initialize (modules/mono/mono_gd/gd_mono.cpp:405)

================================================================
handle_crash: Program crashed with signal 11
Engine version: Godot Engine v4.3.beta3.mono.official (82cedc83c9069125207c128f9a07ce3d82c317cc)
Dumping the backtrace. Please include this when reporting the bug to the project developer.
[1] invoke_previous_action(sigaction*, int, __siginfo*, void*, bool)
[2] 2   libsystem_platform.dylib            0x0000000181b05a24 _sigtramp + 56
[3] Object* ClassDB::creator<MobileVRInterface>()
[4] Object* ClassDB::creator<MobileVRInterface>()
[5] JSON::get_data() const
[6] JSON::get_data() const
[7] JSON::get_data() const
[8] JSON::get_data() const
[9] RendererCompositorRD::_create_current()
[10] RendererCompositorRD::_create_current()
[11] 11  dyld                                0x00000001817550e0 start + 2360
-- END OF BACKTRACE --
================================================================
```

**Comment by roonskipp** [comment] 2024-07-23 08:24
> Your MRP doesn't contain a C# project or the export preset used to export the project. Also, it may be useful to know the information of your .NET installation (run `dotnet --info` in a terminal).
> 
> For macOS we should be building the C# project for 2 architectures:
> 
> https://github.com/godotengine/godot/blob/4e5ed0bbfb56f0a71eb61c868f965476652c23df/modules/mono/editor/GodotTools/GodotTools/Export/ExportPlugin.cs#L188-L192
> 
> Can you share the contents of the `.dmg` file?

Here is a zip with the c# project

[TestFolderGodot copy.zip](https://github.com/user-attachments/files/16345811/TestFolderGodot.copy.zip)


Since my game crashes and the MRP does not after building with the Built in ad-hoc only Codesign, perhaps the three errors are not critical?

**Comment by roonskipp** [comment] 2024-07-23 08:27
The DMG Contents when zipped is 111MB, cannot upload it. Let me know if there are other details that are useful. 

I will try to make a backup of my actual project, and convert it to godot 4.2.2 where it exported successfully previously and see if it runs without the errors I posted above.

**Comment by raulsntos** [comment] 2024-07-23 12:44
The hostfxr errors mean the .NET runtime could not be initialized, so the project won't be able to use C#. That's why in a project with C# scripts it crashes. These errors can't be ignored.

Specifically, the error code [`-2147450743`](https://github.com/dotnet/runtime/blob/main/docs/design/features/host-error-codes.md) means a failure initializing CoreCLR. You shared 2 outputs with different CoreCLR errors:

- `HRESULT: 0x80004005` is `E_FAIL`, an unspecified failure, so I don't know what went wrong. Try setting the environment variable `COREHOST_TRACE` to 1. This enables some verbose logging that may give more information about what went wrong when initializing CoreCLR.

- `HRESULT: 0x80070008` is undocumented, but it seems to be constructed from a WIN32 error which maps to `ERROR_NOT_ENOUGH_MEMORY`. So I guess make sure you have enough memory to initialize the .NET runtime. I don't know if macOS limits the available memory to the Godot process, in which case there may be a way to allow the process to use more memory.

> It all works on iOS exports though

Godot exports to the iOS platform use NativeAOT which is a completely different .NET runtime, the issue you are having seems specific to the CoreCLR runtime.

**Comment by bruvzg** [comment] 2024-07-23 20:20
The error seems to be caused by missing `com.apple.security.cs.allow-jit` entitlement (which should be auto set for .NET version, but seems like it's not detected correctly).

<img width="647" alt="Screenshot 2024-07-23 at 23 18 49" src="https://github.com/user-attachments/assets/4de917f7-6863-4fb0-8e2a-c30b81c644bd">

It should not even show it in the list, but I guess `if (Engine::get_singleton()->has_singleton("GodotSharp")) {` checks stop working for some reason.

**Comment by bruvzg** [comment] 2024-07-23 20:32
So it is regression from https://github.com/godotengine/godot/pull/91557, `has_singleton("GodotSharp")` is still used in multiple places in the engine (not only export code).

**Closed** 2024-07-24 08:04 UTC
Labels: bug, platform:macos, topic:dotnet, regression, topic:export
