### ISSUE TITLE
Floaty ConvexPolygonShapes in Bullet physics

### ISSUE THREAD

**Issue by hoontee** [godotengine/godot#40710] opened 2020-07-25 21:28 UTC
**Godot version:**
3.1 - 3.2.3.rc1 - master (Not present in 3.0.6 and earlier)

**OS/device including version:**
Windows 10 2004

**Issue description:**
When using a `ConvexPolygonShape` (or a `CollisionPolygon` which decomposes into many `ConvexPolygonShapes`) with the Bullet physics engine, all of its contacts will be offset by the collision `margin` (0.04 units.)
Does not occur with GodotPhysics.

Left is `BoxShape`, right is `ConvexPolygonShape` (or `CollisionPolygon`)
Bullet: ![image](https://user-images.githubusercontent.com/5272529/88466446-f9845300-ce91-11ea-92e5-d17efada0ea2.png)
GodotPhysics: ![image](https://user-images.githubusercontent.com/5272529/88466473-33edf000-ce92-11ea-9970-861a3b2877fe.png)

**Steps to reproduce:**
Use a `ConvexPolygonShape` or `CollisionPolygon` with the Bullet physics engine.

**Minimal reproduction project:**
[Physics.zip](https://github.com/godotengine/godot/files/4976521/Physics.zip)

**Comment by Sonoracpp** [comment] 2020-07-25 21:37
I think it has something to do with collision margins

**Comment by madmiraal** [comment] 2020-07-27 12:05
Duplicate of #27427.

**Closed by madmiraal** 2020-07-27 12:05 UTC
Labels: bug, topic:physics
