### ISSUE TITLE
C#: Missing Equals,  on Variant

### ISSUE THREAD

**Issue by MikeSchulze** [godotengine/godot#78076] opened 2023-06-10 07:14 UTC
### Godot version

v4.1.dev4.mono.official [5c2295ff5]

### System information

Windows 10, MacOS

### Issue description

Hi i run into this issue by migrating my C# test framework to v4.1.xx.

The Varaint breaks my implementation because I used `Equals` to compare things (not only GodotObject's).

In C# `object.Equals`, the operator `==` is defined to compare by members and by reference with `object.ReferenceEquals()`.

This is currently not possible with Godot Varints.

From my perspective the Variant should implement:

methods: `Equals`, `ReferenceEquals`
operators: '==', `!=`

Otherwise you are forced to implement your own unbox method to compare Godot.Variant on C# standard.

I now Variant is Godot specific but ist should folow the c# standards.

### Steps to reproduce

```csharp
    partial class ExampleNode : Godot.Node
    {
        private readonly int value;
        private readonly string msg;

        public ExampleNode(string msg, int value)
        {
            this.msg = msg;
            this.value = value;
        }

        public override bool Equals(object? obj)
        {
            return obj is ExampleNode example &&
                   value == example.value &&
                   msg == example.msg;
        }

        public override int GetHashCode() => HashCode.Combine(value, msg);
    }
```

```csharp
        private void CompareThings<T>(T? left, T? right)
        {
            System.Console.WriteLine();
            System.Console.WriteLine($"Compare {left.GetType()}");
            object? a1 = left;
            object? b1 = right;
            System.Console.WriteLine("As System : {0} {1} Equals: {2,-5}, reference Equals: {3,-5}, operator Equals {4,-5}", a1, b1, object.Equals(a1, b1), object.ReferenceEquals(a1, b1), a1 == b1);

            Godot.Variant a2 = Godot.Variant.From(left);
            Godot.Variant b2 = Godot.Variant.From(right);
            System.Console.WriteLine("As Variant: {0} {1} Equals: {2,-5}, reference Equals: {3,-5}, unboxed Equals: {4,-5}", a2, b2, object.Equals(a2, b2), object.ReferenceEquals(a2, b2), a2.Obj.Equals(b2.Obj));
        }

        public test() {
            CompareThings(10, 10);
            CompareThings("a1", "a1");
            CompareThings(new Godot.Node(), new Godot.Node());
            CompareThings(new Example("a1", 1), new Example("a1", 1));
        }
```

```console
Compare System.Int32
As System : 10 10 Equals: True , reference Equals: False, operator Equals False
As Variant: 10 10 Equals: True , reference Equals: False, unboxed Equals: True 

Compare System.String
As System : a1 a1 Equals: True , reference Equals: True , operator Equals True
As Variant: a1 a1 Equals: False, reference Equals: False, unboxed Equals: True

Compare Godot.Node
As System : <Node#29779559636> <Node#29796336857> Equals: False, reference Equals: False, operator Equals False
As Variant: <Node#29779559636> <Node#29796336857> Equals: False, reference Equals: False, unboxed Equals: False

Compare GdUnit4.Asserts.ExampleNode
As System : <Node#29813114072> <Node#29846668506> Equals: True , reference Equals: False, operator Equals False
As Variant: <Node#29813114072> <Node#29846668506> Equals: False, reference Equals: False, unboxed Equals: True
```

### Minimal reproduction project

N/A

**Comment by raulsntos** [comment] 2023-06-10 08:10
Duplicate of https://github.com/godotengine/godot-proposals/issues/5758

**Closed by raulsntos** 2023-06-10 08:10 UTC
