### ISSUE TITLE
Some elements of the editor overlap with others

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#20837] opened 2018-08-09 09:37 UTC
**Godot version:**
3.1 9bd5315

**OS/device including version:**
Windows 10 Intel HD 4600

**Screen Resolution**
Around 1920x540px

**Issue description:**
When height of editor is small, some elements from right panel  overlap others, part around Node and Inspector tab are transparent and that do not look good.

I checked this and this seems to be caused by Profiler, other tabs, like Errors and Debugger looks good until I click to Profiler

https://streamable.com/mc97n

**Comment by qarmin** [comment] 2018-10-08 11:20
The same problem is with Tile Set 
https://streamable.com/twfat

**Comment by akien-mga** [comment] 2019-01-23 13:58
Is this still reproducible in the current master branch?

**Comment by qarmin** [comment] 2019-01-23 14:02
Only with Profiler. 
Tileset and Video Mem seems to be repaired

**Comment by akien-mga** [comment] 2019-10-04 10:22
This seems to have been fixed in the master branch.

**Comment by qarmin** [comment] 2019-10-04 10:44
059a53ee1 still has problem with Profiler, Network Profiler and Video mem
![jfile](https://user-images.githubusercontent.com/41945903/66201892-b8257b80-e6a4-11e9-8453-ee4ab288f2ba.gif)

**Comment by akien-mga** [comment] 2019-10-04 11:39
Hm indeed, I couldn't reproduce it when I tried earlier, but now I can.

CC @YeldhamDev @groud you're good with boxes :o)

**Comment by YeldhamDev** [comment] 2019-10-04 19:48
I took a good look at this, and honestly, I have no clue.

`ScriptEditorDebugger` currently inherits `Control`, so my first action was to change it to a `MarginContainer`, so it actually acknowledges the minimal size of its children, but it still refused to take the sizes into account.

The cause may be how the editor is placed (note that the tabs in the debugger go outside the bottom panel area), but I couldn't find where it tells the editor to do that. If anyone else is more lucky, let me know.

**Comment by golddotasksquestions** [comment] 2019-10-12 17:58
Has this already been fixed as well?
![overlapp01](https://user-images.githubusercontent.com/47016402/66705715-98d4c100-ed2a-11e9-8df8-76dfd64d4370.gif)

**Comment by pouleyKetchoupp** [comment] 2019-11-18 08:48
@YeldhamDev You got very close :) The only remaining issue after switching to MarginContainer is that ScriptEditorDebugger was overriding `get_minimum_size()` and directly calling `Control::get_minimum_size()` so any Container logic was skipped.

**Closed** 2019-11-18 09:06 UTC
Labels: bug, topic:editor
