### ISSUE TITLE
Messed up Layout after loading a project

### ISSUE THREAD

**Issue by Daniel-da-Silva** [godotengine/godot#43235] opened 2020-10-31 09:51 UTC
**Godot version:**
3.2.2
(3.2.3 - I tried it with 3.2.3 version there was the same happening)

**OS/device including version:**
MX Linux - always updated
Intel i5-2520M

**Issue description:**

Today my project broke. When I started it, I couldn't use the editor normally - couldn't scroll to zoom in in the 2D view, the layout was weird, when I clicked on stuff it didn't work everytime (like there were no nodes shown, when I tried it).

When I opened other projects everything worked flawlessly.

I could fix it though with just copying the folder of the project to another place and/or renaming the folder (Decide to Decide4) in which the project is located and reimported. When I renamed the folder back and put it in the previous location it stopped working again.

Restarting didn't change anything.

![Bildschirmfoto_2020-10-31_10-50-07](https://user-images.githubusercontent.com/73739524/97776268-01295700-1b67-11eb-926b-ea3d7835a4ae.png)

Terminal:

Error
[ErrorMessage.txt](https://github.com/godotengine/godot/files/5468998/ErrorMessage.txt)

When everything is fine
[NormalMessage.txt](https://github.com/godotengine/godot/files/5468999/NormalMessage.txt)

**Comment by Calinou** [comment] 2020-10-31 11:24
Unfortunately, without a minimal reproduction project, this will most likely be impossible to troubleshoot.

**Comment by Daniel-da-Silva** [comment] 2020-10-31 11:29
I would really love to do that, but since the project works when I put it in another folder this is hard to replicate. Is there anything else I could do?

**Comment by Calinou** [comment] 2020-10-31 11:36
@Daniel-da-Silva :shrug: 

We may close this issue if nobody manages to reproduce it in a few weeks' time. In the meantime, I suggest setting up version control like Git to avoid losing your project data due to mistakes or bugs.

**Comment by Daniel-da-Silva** [comment] 2020-10-31 11:47
I started it with the Terminal - maybe this is useful in any way (it's fucking long). When I start another project this doesn't happen

Error

[ErrorMessage.txt](https://github.com/godotengine/godot/files/5468984/ErrorMessage.txt)

Normal

[NormalMessage.txt](https://github.com/godotengine/godot/files/5468990/NormalMessage.txt)

**Comment by Daniel-da-Silva** [comment] 2020-10-31 11:49
And thanks for the advice! - I always put my projects on USB stick but I should use git or something.

**Comment by mrjustaguy** [comment] 2020-11-01 20:15
Backup your Cache, Kill it, see if that fixes it, then put back the Cache if it does to see if it'll break it.

**Comment by Anutrix** [comment] 2020-11-03 08:01
> I could fix it though with just copying the folder of the project to another place and/or renaming the folder (Decide to Decide4) in which the project is located and reimported. When I renamed the folder back and put it in the previous location it stopped working again.

Based on this, I'm 99% sure it's just the config(aka cache like mrjustaguy said) for the project is messed up.			
On Linux, this is `~/.local/share/godot/app_userdata/[project_name]`, or `~/.local/share/[custom_name]` if `use_custom_user_dir` is set.
Try deleting or renaming that folder.

**Comment by Daniel-da-Silva** [comment] 2020-11-04 08:54
Unfortunately this didn't change anything :/ I cut and pasted it on a USB stick and removed it. The problem is still there. Removing didn't help and putting it back also didn't. Thanks for posting the path, I use Linux for a short amount of time as my main machine.

**Comment by akien-mga** [comment] 2020-11-04 08:57
>  On Linux, this is `~/.local/share/godot/app_userdata/[project_name]`, or `~/.local/share/[custom_name]` if `use_custom_user_dir` is set.

Those are the paths for the `user://` filesystem, not the project metadata. Project metadata on Linux is in `~/.config/godot/projects/<name>-<hash>/`.

**Comment by Daniel-da-Silva** [comment] 2020-11-16 01:28
I will test this in a couple of days! Thanks!

**Comment by Daniel-da-Silva** [comment] 2020-11-20 17:45
Hey guys, I just tested it and cut the folder completely and put it in the download section. Didn't change anything, the problem still was there (and is still fixed by the same method).

**Comment by Anutrix** [comment] 2020-11-21 08:29
Was the project or editor open when you moved/deleted the .config folder? You need to have it closed.

**Comment by Daniel-da-Silva** [comment] 2020-11-23 01:32
It was closed

**Comment by Calinou** [comment] 2022-11-05 00:02
@Daniel-da-Silva Can you (or anyone else) still reproduce this bug in [Godot 3.5.1](https://godotengine.org/article/maintenance-release-godot-3-5-1) or any later release?

If yes, please ensure that an up-to-date Minimal Reproduction Project (MRP) is included in this report (a MRP is a zipped Godot project with the minimal elements necessary to reliably trigger the bug). You can upload ZIP files in an issue comment with a drag and drop.

**Comment by Daniel-da-Silva** [comment] 2022-11-05 12:00
I don't have the files in the old location, I think, to reproduce it. All I can say it didn't happen since quite a while!

**Comment by Calinou** [comment] 2022-11-25 19:26
Alright, closing for now. Please comment if you (or anyone else) can still reproduce this bug on the latest Godot version.

**Closed by Calinou** 2022-11-25 19:26 UTC
Labels: bug, topic:editor, needs testing
