### ISSUE TITLE
Can't erase action or input when built-in actions are hidden

### ISSUE THREAD

**Issue by foxydevloper** [godotengine/godot#50657] opened 2021-07-20 18:26 UTC
### Godot version

v4.0.dev.custom_build [bb037de95]

### System information

Windows 10

### Issue description

When "Show Built-in Actions" is disabled, the delete button is not clickable because it's clipped to the right.

https://user-images.githubusercontent.com/12120644/126375414-b3905ebc-d2a3-4691-805c-1cc790beebbb.mp4

There's also a really weird 6 pixel column, that shows up differently depending on "Show Built-in Actions":
![image](https://user-images.githubusercontent.com/12120644/126375843-0a0dd461-f554-47e4-8586-3fea9aa5d4b0.png)
![image](https://user-images.githubusercontent.com/12120644/126375794-cf4eb4b4-c04f-4a23-8598-04db697d19e7.png)
I don't know whether it's related to delete being too far to the right, but it shouldn't be there

### Steps to reproduce

- Open Input Map
- Have Show Built-in Actions off
- Can't press delete on actions or events

**Comment by EricEzaM** [comment] 2021-07-20 23:51
This is a regression after f4379cbc82cfe915e97a8e879567b820a10198f4(#50146) CC @reduz 

Bisect:
`f4379cbc82cfe915e97a8e879567b820a10198f4 is the first bad commit`

**Comment by EricEzaM** [comment] 2021-08-05 01:52
Appears to be fixed in latest master?

**Comment by akien-mga** [comment] 2021-09-21 14:25
Duplicate of #52891.

**Closed by akien-mga** 2021-09-21 14:25 UTC
Labels: bug, topic:editor, usability
