### ISSUE TITLE
Can't assign a Node3D to an @export Array[Node3D]

### ISSUE THREAD

**Issue by prominentdetail** [godotengine/godot#72564] opened 2023-02-02 03:58 UTC
### Godot version

v4.0.beta.custom_build [1b131ac49]

### System information

Windows 10

### Issue description

Can't assign node3d to an array via the inspector.

### Steps to reproduce

Click the node with the script, go to the inspector and click the Assign.. button in one of the array slots and then choose a node.
It won't assign it.

### Minimal reproduction project

[arrayNodeBug.zip](https://github.com/godotengine/godot/files/10564597/arrayNodeBug.zip)

**Comment by dalexeev** [comment] 2023-02-02 11:44
Duplicate of #62916.

**Closed** 2023-02-02 11:50 UTC
Labels: bug, topic:gdscript
