### ISSUE TITLE
Laptop touchpads are seen as gamepads

### ISSUE THREAD

**Issue by thomaslenzi** [godotengine/godot#59250] opened 2022-03-17 21:25 UTC
### Godot version

4.0-alpha4

### System information

Linux - Manjaro 21.2.5

### Issue description

In Godot 4.0-alpha4, my laptop's touchpads are seen as gamepads. When no actual controllers are attached to my laptop, functions and signals such as `Input.get_connected_joypads()` and `Input.joy_connection_changed.connect` see two existing devices. When I add real controllers, they are assigned device ids from 2 and up. In contrast, this is not the case in Godot 3.4.3.

**Godot 3 output at start**
`[blank]`
**Godot 3 output when I connect a Xbox 360**
`0 Xbox 360 Controller`

**Godot 4 output at start**
`0 SYNA8008:00 06CB:CE58 Touchpad`
`1 ELAN901C:00 04F3:2C29`
**Godot 4 output when I connect a Xbox 360**
`2 Xbox 360 Controller`

Note that if the Xbox controller is connected when I launch the "game", it is seen with device id = 0.

A tool such as gamepad-tool yields the same results as Godot 3 (no additional devices detected). 

### Steps to reproduce

Create an empty project with a single Node2D and the following script attached
```
extends Node2D

func _ready():
	Input.joy_connection_changed.connect(self._on_joy_connection_changed)
	for device in Input.get_connected_joypads():
		print(device, " ", Input.get_joy_name(device))

func _on_joy_connection_changed(device, connected):
	print(device, " ", Input.get_joy_name(device))
```

**Comment by thomaslenzi** [comment] 2022-03-22 07:35
For completeness, I also tested on v3.4.4-rc2  and v3.5-beta2 and both behave as expected.

**Comment by akien-mga** [comment] 2022-03-22 07:52
I didn't bisect, but I have a hunch that #57612 might be the culprit. It hasn't been cherry-picked for `3.x` and `3.4` yet.
CC @maiself @madmiraal

**Comment by madmiraal** [comment] 2022-03-22 11:37
I've created PR #59412 to increase the restriction on devices that are detected as gamepads that should fix this issue.

**Comment by thomaslenzi** [comment] 2022-03-22 13:27
Solved by #59412. Thank you for your help. 
Should I close the issue or wait for the PR to be merged?

**Comment by Calinou** [comment] 2022-03-22 13:36
> Solved by #59412. Thank you for your help. Should I close the issue or wait for the PR to be merged?

The issue won't be fixed in `master` until the PR is merged. Therefore, we need to wait for the PR to be merged to close the issue.

**Comment by vysker** [comment] 2022-10-11 08:42
For anyone else running into this issue, you can work around the issue by including this in any `_ready()` function:

```
if Input.get_connected_joypads().is_empty():
    for action in InputMap.get_actions():
        for event in InputMap.action_get_events(action):
            if event is InputEventJoypadMotion:
                InputMap.action_erase_event(action, event)
```

This obviously shouldn't be in production code. And it's also not cognizant of the fact that you might have both a joypad _and_ a touchpad connected.

**Comment by MegaKeegMan** [comment] 2022-11-01 23:57
Looking forward to the merge! I see the suggested workaround above, and I don't quite understand it. I am in the process of figuring out how to get local multiplayer to work, and am adding a player instance to the scene for each connected gamepad. So my current workaround looks something like this:
```
var input_devices = Input.get_connected_joypads()

func _ready() -> void:
  for device in input_devices:
          if not Input.get_joy_name(device).contains("Touchpad"):
	    var new_player = player_scene.instantiate().setup(device)
	    add_child(new_player)
```

At least that's the relevant bit. Hope this helps someone, or that someone comments on why not to do this. Though ultimately, I don't intend to leave the number of players to be determined by how many devices are connected.

**Comment by Drejzer** [comment] 2023-01-22 14:25
This can be seen in Input Map in project settings in beta14
(godot4-bin beta14-1 AUR package installed on Manjaro 22.0.0)

Since "Listening for input" is focused when adding new key to an action, it will immediately detect moving the mouse as Joypad Axis 0,1 or 2

**Comment by Calinou** [comment] 2023-01-31 13:49
I can confirm this on 4.0.beta16 while I was working on https://github.com/godotengine/godot-demo-projects/pull/830, but with a different kind of device. This is not limited to laptop touchpads; here, it was occurring with a motherboard LED controller:

![image](https://user-images.githubusercontent.com/180032/215778045-8459a36c-6048-4665-a6a6-7cf19a29907b.png)

**Comment by Zireael07** [comment] 2023-01-31 14:25
https://github.com/godotengine/godot/pull/59412 is one of the proposed fixes and has been waiting nearly a year

**Comment by bend-n** [comment] 2023-02-25 12:05
As making the touchpad not usable as a input device is difficult and would make using certain gamepads impossible, can we not have a simple workaround: a way to stop the input system from registering a certain device name?

**Comment by Calinou** [comment] 2023-02-25 17:04
> As making the touchpad not usable as a input device is difficult and would make using certain controllers impossible, can we not simply have a way to stop the input system from registering a certain device?

We could have a project setting with a list of device IDs that shouldn't be registered as controllers (plus an environment variable to append to this list), but this will require manual maintenance.

**Comment by bend-n** [comment] 2023-02-26 01:46
Yeah,  and have the list changeable.

**Comment by waynepiekarski** [comment] 2023-09-24 05:17
I'm running into this problem with Godot 4.1.1 and none of the existing solutions worked to filtering out the joystick events being generated by the trackpad on my Framework laptop with Ubuntu 22.04.

However, I've noticed that Input.is_joy_known() returns false for these trackpads and not real joysticks, and so a workaround in my _input event handler that seems to be working for me is this:
```
func _input(event):
    if not Input.is_joy_known(event.get_device()):
        # Skip trackpad and only support real USB joysticks
        return
    # print("ID=" + str(event.get_device()) + " NAME=" + Input.get_joy_name(event.get_device()) + " KNOWN=" + str(Input.is_joy_known(event.get_device())))
    # Handle the rest of your InputEventJoypadMotion events here
```

**Comment by bend-n** [comment] 2023-09-24 05:19
Have you tried using my [builds](https://github.com/bend-n/godot-builds/releases/latest)? Ive patched a fix into them.

**Comment by malucard** [comment] 2023-10-22 13:29
This is a major issue for any usage of the engine on my laptop. Why is this waiting for so long?

**Comment by Calinou** [comment] 2023-10-22 22:15
> This is a major issue for any usage of the engine on my laptop. Why is this waiting for so long?

See https://github.com/godotengine/godot/pull/59412#issuecomment-1759087924. The PR needs to be revised significantly (or even remade from scratch) before it can be merged.

**Comment by geekley** [comment] 2023-10-30 23:22
You can use this script I made before the PR is ready.
I believe it's the best workaround to fix this issue according to the proposed solution:
> For the time being, we'd suggest addressing the root issue in a simpler, yet more focused, way: blacklist devices that contain "touchpad" in their name (case-insentive, just in case).

It works on my "SynPS/2 Synaptics TouchPad" device. Tested on Godot v4.1.2.stable.mono only.
Not sure if you should use this in production. But it can at least help you for now, if you use a laptop for development. It's very simple and self-explanatory. Free to tweak the regex if needed. You can also remove the logging line.

Just add this script as an auto-load in your project settings. The node will just run the code at startup, then self-delete.
`TouchpadIsNotJoypad.gd`
```gdscript
# Public domain, as per The Unlicense. NO WARRANTY. See https://unlicense.org

extends Node
## Solves a [url=https://github.com/godotengine/godot/issues/59250]bug[/url] where touchpad devices
## can be detected as a joypad.
##
## This script should be autoloaded in the project settings.
## This is merely a workaround, not for use in production code.

func _ready() -> void:
	var pattern := RegEx.create_from_string('(?i)\\b(?:touch|track|click)pad\\b')
	for device_id in Input.get_connected_joypads():
		var device_name := Input.get_joy_name(device_id)
		if not pattern.search(device_name):
			continue
		# Device name contains "touchpad", "trackpad" or "clickpad" word, ignoring case.
		var guid := Input.get_joy_guid(device_id)
		var mapping := guid + ',' + device_name.replace(',', '') # not mapping any axes or buttons
		prints('Ignoring joypad device:', mapping) # you can comment out or remove this line
		# Replace with empty mapping on this guid. Should ignore all joypad input from this device.
		Input.add_joy_mapping(mapping, true)
	queue_free()
```

**Comment by geekley** [comment] 2023-11-11 02:37
I've updated the code above to fix an issue.
Please update it if you're using it, and tell me if you get any issues.

The change is because even the touchpad device may take a few frames to appear (e.g. on Flatpak version of Godot), so now the check will run for every device connection instead of assuming the list of devices is ready at startup. Also, devices like drawing tablets can be connected at any time.

I've also updated the regex to match "mouse" and "pen" words as well. Note that this isn't exhaustive. I don't know if words like "pencil", "tablet", "stylus", etc. should be included. Tweak as needed.

**Comment by geekley** [comment] 2023-12-12 05:43
I've updated the code in the gist again to fix another issue.
I'm now sending input events once to reset all of the device's SDL axes and buttons to zero upon disabling it.
This ensures it won't be stuck in motion, in case you were moving the touchpad during startup.

Please update if you're using the code (it's for v4.2 now, but should be trivial to port back by removing `for` type hints).

**Comment by mak448a** [comment] 2024-02-11 20:55
Any updates on this?

**Comment by AThousandShips** [comment] 2024-02-11 20:58
See the linked PR, but otherwise please don't bump things without information, if someone has an update they would have added it here :)

**Comment by Chris-Frendo** [comment] 2024-06-15 22:37
Any updates on this? Been holding off using godot because of this bug which makes working on a laptop a headache.

**Comment by bend-n** [comment] 2024-06-16 02:09
you can use [my patches of godot](https://github.com/bend-n/godot-builds/releases/tag/4.2.2) which have this fixed.

**Comment by Chris-Frendo** [comment] 2024-06-17 20:53
I'm using pacman to install godot, is there an easy-ish way to use that patch without having to build from source? I'd want to keep getting updates for godot.


Or even better, are there plans to fix this on the actual godot project?

**Comment by geekley** [comment] 2024-06-17 20:54
@Chris-Frendo Use my script from the gist above: https://github.com/godotengine/godot/issues/59250#issuecomment-1786196830

**Comment by Chris-Frendo** [comment] 2024-06-17 21:04
Yeah that helps for the project itself, but godot itself registers the touchpad as a joystick input when mapping something in the input map. Unfortunately I haven't found a way around that issue yet.

**Comment by geekley** [comment] 2024-06-17 21:12
@Chris-Frendo I can't remember if merely making it a tool script (just adding `@tool` annotation on top of the code) would be enough to solve that, but maybe you can try it and see how it goes?

**Comment by Chris-Frendo** [comment] 2024-06-17 21:19
I'm quite a noob with godot so I can't saay for certain, but the annotation didn't really seem to fix the problem, however it did end up crashing godot when opening the project settings window, so something must be happened with the annotation.

**Comment by bend-n** [comment] 2024-06-17 23:41
> I'm using pacman to install godot, is there an easy-ish way to use that patch without having to build from source? I'd want to keep getting updates for godot.

Unfortunately i only have an AUR package for the 2d version.

**Closed** 2024-07-09 14:53 UTC
Labels: bug, platform:linuxbsd, topic:porting, confirmed, topic:input, regression

**Comment by TheBoctor** [comment] 2024-12-23 23:21
Has anyone still been having this happen with specific models of Synaptics touchpads? I notice several of these devices omit all of the current filtered words/patterns (e.g. 'touchpad', 'trackpad') from their device names, just being called "Synaptics." As a result, they will still make the inputs go crazy, whenever I playtest on some common ThinkPad laptops (P50, T480).

Reusing [this](https://gist.github.com/geekley/5e6daf62d2e86b566c4886f20b604d21) previous workaround and adding 'synaptics' to the list of banned words/names completely alleviates the problem. Would denylisting 'synaptics' upstream interfere with any known joypads?

**Comment by geekley** [comment] 2024-12-24 00:10
@TheBoctor Are you using Linux? A recent (kernel?) update changed the name on the touchpad device in my laptop. I know because I had to update settings and a script I was using to remap buttons with xinput.

For me, the device name was `SynPS/2 Synaptics TouchPad`, but became `Synaptics TM2768-001`.
So this issue should be reopened @Calinou, as the current solution will not work anymore.

I suppose the ideal would be to see if Synaptics has any sort of pattern regarding model names, and use that. For example, suppose all touchpad model numbers start with "TM" or with "T", then we could reasonably use this heuristic I think?
Unless there's a better way to use underlying low-level system calls to see if the device is being interpreted as a pointer, of course.

**Comment by TheBoctor** [comment] 2024-12-24 00:21
> For me, the device name was `SynPS/2 Synaptics TouchPad`, but became `Synaptics TM2768-001`.
Yes, that's exactly the same format as the names my T480/P50 touchpads now show, with the "TM" initials and four digits. It must have either been a libinput or a kernel change. Either way, I would never have noticed the names changing between releases, good catch.

**Comment by scurest** [comment] 2025-01-10 17:22
If you encounter this issue as a _player_, here's a workaround that worked for me. You need to install [Bubblewrap](https://wiki.archlinux.org/title/Bubblewrap) from your package manager first. We're going to sandbox the game so it can't access the touchpad's device file.

(Works for non-Godot games too.)

**If you want to play with mouse & keyboard:**

Run this from the shell

    bwrap --dev-bind /{,} --bind /dev/input{,} ./YourGame

This prevents the sandbox from accessing all device files in /dev/input, including the touchpad.

**If you want to play with a controller:**

First plug the controller in and find the `/dev/input/eventX` for it (try looking in `ls -l /dev/input/by-id`), then run

    bwrap --dev-bind /{,} --bind /dev/input{,} --dev-bind /dev/input/eventX{,} ./YourGame

This lets just that one device file into the sandbox.
