### ISSUE TITLE
AnimationTree - AnimationNodeBlendTree - Blend2 node blending issue

### ISSUE THREAD

**Issue by MatejsBalodis** [godotengine/godot#27484] opened 2019-03-28 10:05 UTC
**Godot version:**

v3.1.stable.official

**OS/device including version:**

Windows 10
Ubuntu 17.04.

**Issue description:**

I made animations using skeleton2D and bone nodes. I used animationTree node with Tree Root set to AnimationNodeBlendTree. I made 2 animations and tried to blend them with Blend2 node. Animations and blending works fine, until you make changes in the animation key frames, for example, delete key frames. Then if you blend between animations, around 0.5, the state is messed up, it "remembers" the original key frames and blends it in together.

**Steps to reproduce:**
- Create skeleton2D with bones;
- Create animationPlayer node;
- Create 2 animations, for example, rotation for 1 bone with at least 2 key frames with different values per track;
- Create animationTree node;
- Set Tree Root to AnimationNodeBlendTree;
- Add 2 nodes and set them to the 2 animations created before;
- Add Blend2 node and connect all nodes;
- Check blending to make sure it works, change values around;
- Go back to AnimationPlayer node and delete one of the 2 key frames;
- Check Blend2 node in animationTree and set blending to 0.5 to see the issue.

As I was doing this on a stream, you can see footage of what actions I took and what the result looked like here: https://www.twitch.tv/videos/402399553

**Minimal reproduction project:**

[AnimationTree-test.zip](https://github.com/godotengine/godot/files/3017270/AnimationTree-test.zip)

**Comment by asheraryam** [comment] 2019-03-28 11:13
Can you point out at what time in the stream this happened? 46 minutes is a bit long to go through just to see a bug 😅

**Comment by MatejsBalodis** [comment] 2019-03-28 11:18
Try going to 26:00.

**Comment by asheraryam** [comment] 2019-03-28 11:29
I watched until 31 and yeah definitely the AnimationTree seems to be not updating the blended animation when keyframes are deleted. That seems to be the bug explanation.

But note that the bug you mentioned at 29:30 is likely not a bug, that might be how blending works. The middle values between two animations can be messed up if the animation is changing the same exact values in opposite directions.

**Comment by akien-mga** [comment] 2019-03-28 12:00
CC @YeldhamDev @guilhermefelipecgs

**Comment by guilhermefelipecgs** [comment] 2019-03-28 18:08
> Animations and blending works fine, until you make changes in the animation key frames, for example, delete key frames.

This is not a bug, this happens because of `Blend2`, the problem is that `Blend2` doesn't interpolates `Property Track` like `position` and `rotation` very well, causing this weird movement. As far as I know, only `3D Transform Track` will works.
![Captura de tela de 2019-03-28 14-48-32](https://user-images.githubusercontent.com/1387165/55180590-a2208680-5168-11e9-98c4-03d32589454c.png)
Maybe we should add `2D Transform Track` for this? :thinking: 

@MatejsBalodis In your case, replacing `Blend2` to `Add2` should works, you will have a more natural movement this way.

**Comment by MatejsBalodis** [comment] 2019-03-28 18:14
@guilhermefelipecgs But it does work correctly, until you make changes like delete keyframes. With the old **AnimationTreePlayer** node doing the same doesn't result in an error. I can use Blend2, change keyframes, delete keyframes and there will be no unintended result in blending.

**Comment by guilhermefelipecgs** [comment] 2019-03-28 18:39
To clarify, here is the difference from `Blend2`and `Add2` when animating `position`:
![Peek 28-03-2019 15-26](https://user-images.githubusercontent.com/1387165/55183155-042fba80-516e-11e9-88fa-8871dfe2c517.gif)
This also happens in 3D if using `Property Track`, but not with `3D Transform Track`

**Comment by guilhermefelipecgs** [comment] 2019-03-28 18:58
> @guilhermefelipecgs But it does work correctly, until you make changes like delete keyframes. With the old **AnimationTreePlayer** node doing the same doesn't result in an error. I can use Blend2, change keyframes, delete keyframes and there will be no unintended result in blending.

@MatejsBalodis If you want the old `Blend2` behaviour you can just use `Add2` because I think they have the same behaviour now. See here:
![Peek 28-03-2019 15-48](https://user-images.githubusercontent.com/1387165/55184658-7ce44600-5171-11e9-8784-c9c021028c5a.gif)
I don't know why it has changed and if this is really intentional, I think only @reduz can tell us.

**Comment by MatejsBalodis** [comment] 2019-03-28 19:02
@guilhermefelipecgs Ok, I can use add, that's good. But I tried to do what you did with Blend2 and it works.
![AnimationTree](https://user-images.githubusercontent.com/6319635/55185278-a6ff2d80-519c-11e9-9eb2-5dcf51d29740.gif)

So I don't understand why is it not a bug?

**Comment by guilhermefelipecgs** [comment] 2019-03-28 19:26
> @guilhermefelipecgs Ok, I can use add, that's good. But I tried to do what you did with Blend2 and it works.

This is a little dificult to explain, but your idle animation is setted to `Vector2(0, 0)` and this cause the impressions that it's working, but if you use another position, the `Vector2::linear_interpolation` will not works.

Demo here: [AnimationTree-test_v2.zip](https://github.com/godotengine/godot/files/3019797/AnimationTree-test_v2.zip)

Gif: 
![Peek 28-03-2019 16-17](https://user-images.githubusercontent.com/1387165/55186306-faf61c00-5174-11e9-8aae-e94d485ef082.gif)

> So I don't understand why is it not a bug?

Maybe this is a bug, I dunno, we need an opinion from @reduz about this because I don't know what the default behavior should be.

**Comment by guilhermefelipecgs** [comment] 2019-03-30 14:21
ok, I've tested other software and I think `Blend2` behavior is definitely not correct. I'll work on a proper fix for this.

**Closed** 2019-04-01 14:38 UTC
Labels: bug, topic:core
