### ISSUE TITLE
[4.2.2] selecting multiple lines of code and "CMD + SHIFT + DOWN_ARROW" behaviour is wrong

### ISSUE THREAD

**Issue by madhupprasad** [godotengine/godot#95006] opened 2024-08-01 05:26 UTC
### Tested versions

Reproducible in 4.2.2

### System information

Godot v4.2.2.stable - macOS 14.1.1 - Vulkan (Forward+) - integrated Apple M1 - Apple M1 (8 Threads)

### Issue description

EXPECTED BEHAVIOUR : After selecting two lines of code, pressing CMD + SHIFT + DOWN_ARROW should duplicate them together after the last selected line.

CURRENT BEHAVIOUR :   After selecting two lines of code, pressing CMD + SHIFT + DOWN_ARROW duplicates each line separately. (Attached screen shot for reference)

![Screenshot 2024-08-01 at 10 48 49 AM](https://github.com/user-attachments/assets/dc5b2002-22e9-4350-98a5-869dc3a6ba12)
![Screenshot 2024-08-01 at 10 48 59 AM](https://github.com/user-attachments/assets/22cd95c6-3160-420b-95b0-7c7f03992ae3)

### Steps to reproduce

Select 2 lines of code and press CMD + SHIFT + DOWN_ARROW

### Minimal reproduction project (MRP)

N/A - It is there in the latest version (4.2.2)

**Comment by Giganzo** [comment] 2024-08-01 09:39
Cant reproduce this in 4.3rc1 with CTRL + ALT + DOWN

**Comment by madhupprasad** [comment] 2024-08-01 12:35
I tested in 4.3 version and it works fine. Then I built 4.2.2 and tested and it was producing the issue. 

I went through the code and I believe the issue is in ```void CodeEdit::duplicate_lines()```

**Comment by madhupprasad** [comment] 2024-08-01 13:13
Ok I understood the problem, If select the text from top to bottom (where the caret is at the bottom) this logic works perfectly. 

![Screenshot 2024-08-01 at 6 42 08 PM](https://github.com/user-attachments/assets/0a889b2e-d943-4869-8823-acc10d2e3a24)

But if I select the text from bottom to top, where the caret is in the start of the selection, only in this case, it wont work as expected. 

![Screenshot 2024-08-01 at 6 42 41 PM](https://github.com/user-attachments/assets/8f7d7520-a704-4dae-b5fe-5ddd7f6cd6f4)

**Comment by kitbdev** [comment] 2024-08-01 13:35
- duplicate of https://github.com/godotengine/godot/issues/83589
- fixed in https://github.com/godotengine/godot/pull/86978

**Closed** 2024-08-01 14:33 UTC
Labels: bug, topic:editor, needs testing
