### ISSUE TITLE
calling surface_get_arrays on a quad throws error but also returns arrays

### ISSUE THREAD

**Issue by Miziziziz** [godotengine/godot#31224] opened 2019-08-09 02:44 UTC
**Godot version:** 3.1

**OS/device including version:** Ubuntu 19.04

gpu: GP108M [GeForce MX150]
driver: nvidia 430

**Issue description:**
If I call surface_get_arrays on a quad mesh I get this error:
E 0:00:00:0351   Condition ' surface->index_array_len == 0 ' is true. returned: PoolVector<uint8_t>()
  <C Source>     drivers/gles3/rasterizer_storage_gles3.cpp:3774 @ mesh_surface_get_index_array()
  <Stack Trace>  test.gd:4 @ _ready()

Doesn't happen on any other primitive meshes.
I also get this error message when I set the mesh as a quad:
 drivers/gles3/rasterizer_storage_gles3.cpp:3774 - Condition ' surface->index_array_len == 0 ' is true. returned: PoolVector<uint8_t>()

**Steps to reproduce:**
Make a scene, add a MeshInstance with a quad as the mesh.
Put this script on the MeshInstance:
```
extends MeshInstance

func _ready():
	mesh.surface_get_arrays(0)
```
Run the project

**Comment by clayjohn** [comment] 2019-09-17 15:30
Can't reproduce in current master. 

I actually starting preparing a PR doing something that I thought would fix this but then I realized the error was already fixed in master! :)

**Closed by clayjohn** 2019-09-17 15:30 UTC
Labels: bug, topic:rendering
