### ISSUE TITLE
Text selection for sub-sequences works differently rather than in 3.x version.

### ISSUE THREAD

**Issue by Chaosus** [godotengine/godot#49673] opened 2021-06-17 07:09 UTC
### Godot version

bb4c464fecae268a419a91db8eec8f525e904b45

### System information

Windows 10

### Issue description

I noticed that text selection of word sub-sequences (divided by '_') are different between versions:

Godot 4.0:
 ![text_selection_4 0](https://user-images.githubusercontent.com/3036176/122347736-051db400-cf53-11eb-8188-177118089f85.gif)

Godot 3.3:
![text_selection_3 3](https://user-images.githubusercontent.com/3036176/122348046-62b20080-cf53-11eb-9ca4-827f051306b3.gif)

If it's not a bug but an intended enhancement - I think the 4.0 version is harder for common usage than the old - the user needs to perform more actions to select a function, etc.

### Steps to reproduce

^^

### Minimal reproduction project

Too easy to reproduce

**Comment by Calinou** [comment] 2021-06-17 07:12
Duplicate of https://github.com/godotengine/godot/issues/46380.

**Closed by Calinou** 2021-06-17 07:12 UTC
