### ISSUE TITLE
Engine crashes when the second parameter of a posmod is 0

### ISSUE THREAD

**Issue by PolRecasensSarra** [godotengine/godot#69440] opened 2022-12-01 09:37 UTC
### Godot version

3.5.1.stABLE

### System information

Debian10

### Issue description

When using posmod and the second parameter is 0, the engine crashes.

### Steps to reproduce

1. Create a script and attach it to a node.
2. In the _ready function, write `posmod(1, 0)` and save the script.
3. When saving the script, the engine will crash automatically. (if it doesn't crash when saving, press "play" to make sure that the line is executed)

### Minimal reproduction project

"N/A"

**Comment by timothyqiu** [comment] 2022-12-01 09:44
Duplicate of #43932

**Closed by timothyqiu** 2022-12-01 09:44 UTC
