### ISSUE TITLE
Vulkan: GPUParticles3D reappear for a single frame after being deleted when a new instance of the effect is created

### ISSUE THREAD

**Issue by LennDG** [godotengine/godot#66921] opened 2022-10-05 10:31 UTC
### Godot version

4.0 beta 2

### System information

Windows 10, Vulkan, NVIDIA RTX2070 Super with latest drivers (517.48)

### Issue description

I have a particle effect consisting of 2 GPUParticles3D nodes. After hitting an object or a timer running out the parent node of the GPUParticles is deleted.
When a new instance of the particle effect is created, one of the GPUParticles3D (the one not using local coords if that matters) reappears for a single frame in the state it was when the parent node was deleted.
The video shows this happening.

https://user-images.githubusercontent.com/5593865/194039499-5dd3cd05-7006-4c7a-b9af-f046efcaf73b.mp4

### Steps to reproduce

1. Open the attached project
2. Run the main scene
3. Click to shoot a projectile. if you alternate between sides it becomes easy to see the glitch

There are other glitchy effects if you spam click the same location, but I have not been able yet to determine their nature. This issue is specifically the reappearing.

### Minimal reproduction project

[GPUParticlesBug.zip](https://github.com/godotengine/godot/files/9714867/GPUParticlesBug.zip)

**Comment by Chaosus** [comment] 2022-10-05 11:36
Duplicate of https://github.com/godotengine/godot/issues/65443

**Closed by Chaosus** 2022-10-05 11:36 UTC
