### ISSUE TITLE
smoothstep() bug in shader when argument accesses member of a matrix

### ISSUE THREAD

**Issue by loganjk** [godotengine/godot#24110] opened 2018-12-01 21:02 UTC
**Godot version:**
v3.1.alpha.official

**OS/device including version:**
Windows 10 Pro, Intel i7-4790K, using only integrated GPU (Intel HD Graphics 4600)

**Issue description:**
In a fragment shader, smoothstep does not behave as expected when third argument accesses a scalar member of a matrix with [][] syntax, like test[0][0].  Instead, smoothstep seems to return time-dependent spatial noise, even when all arguments are constant in time and space.

**Steps to reproduce:**
Start a new project.  Create a Node2D with a ColorRect child node with a ShaderMaterial with the following shader:

shader_type canvas_item;

void fragment() {
	mat2 test=mat2(vec2(0.0), vec2(0.0));
	COLOR=vec4(1.0, 0.0, 0.0, smoothstep(0.0, 1.0, test[0][0])); //does not behave as expected
}

Similar problem for mat3 and mat4.

I am working around this by not passing test[0][0] directly, but instead first setting a float equal to this and then passing it, like:

mat2 test=mat2(vec2(0.0), vec2(0.0));
float t=test[0][0];
COLOR=vec4(1.0, 0.0, 0.0, smoothstep(0.0, 1.0, t)); //behaves as expected

step() does not seem to have a similar problem -- step(0.0, test[0][0]) behaves as expected.  I have not encountered any other functions besides smoothstep with this problem, but I have not searched extensively.

**Minimal reproduction project:**

[Godot Bug Report.zip](https://github.com/godotengine/godot/files/2636308/Godot.Bug.Report.zip)

**Comment by clayjohn** [comment] 2018-12-01 22:18
I can't reproduce this error on Ubuntu 16.04 using intel integrated graphics (Mesa 18.05). I tested it in my own test scene and in the scene you uploaded. 

Have you tried updating your drivers?

**Comment by loganjk** [comment] 2018-12-01 22:47
I just updated to the newest driver version, 20.19.15.5058, and I am still seeing the problem.

**Comment by clayjohn** [comment] 2018-12-01 23:19
That's unsettling. My bet is still on driver issues unfortunately. We will have to wait and see if other users are also experiencing the same problems, maybe someone else will be able to reproduce the bug.

**Comment by clayjohn** [comment] 2019-12-15 19:55
Removing milestone as this has yet to be reproduced, so we can't really do anything. But leaving open in case someone else can reproduce.

**Comment by akien-mga** [comment] 2019-12-16 07:18
I think it's probably better to close the issue for now as there's nothing we can do to solve it, apart from advising to try newer drivers. Intel doesn't seem to provide new driver branches for 4th gen: https://www.intel.com/content/www/us/en/support/products/81496/graphics-drivers/graphics-for-4th-generation-intel-processors/intel-hd-graphics-4600.html

You might want to try the current latest which appears to be 15.40.42.5063 - which is confusing as you had 20.19.15.5058, but that seems to be a rebranded 15.40.41.5058 as per https://www.station-drivers.com/index.php?option=com_kunena&view=topic&catid=17&id=63&Itemid=858&lang=en

**Closed by akien-mga** 2019-12-16 07:18 UTC
Labels: bug, topic:shaders
