### ISSUE TITLE
"Temporary" Inspector elements don't move when the Inspector is scrolled (DisplayServer regression)

### ISSUE THREAD

**Issue by snailrhymer** [godotengine/godot#57363] opened 2022-01-28 16:42 UTC
### Godot version

v4.0.alpha1.official [31a7ddbf8]

### System information

Windows 10

### Issue description

Some property displays in the Inspector create a temporary UI element when the user edits that property. If the inspector is scrolled while one of these is present, it fails to move with the scrolling. This happens with dropdown menus, the color picker and any LineEdit that modifies numbers (floats, ints, including vector components).

https://user-images.githubusercontent.com/61291296/151585414-e00603f0-7269-4914-9a97-e7c82e23c2e6.mp4

***

In 3.4.2, the inspector can't be scrolled while one of these elements has focus, so the bug is not reproducible there.

### Steps to reproduce

For example:

1. Create a `Control` node and view it in the Inspector.
2. Open enough sections for the Inspector to become scrollable.
3. Edit `anchor_left`.
4. While that field still has focus, scroll the inspector with the mouse's scrollwheel. The active field will stay in place.

**Comment by KoBeWi** [comment] 2022-10-07 21:58
The problem is that the LineEdit appears in a Popup, which appears over the main window. Even if we make it follow the source node, it won't clip properly. The best solution might be disabling the scroll. Or evaluating whether the LineEdit really needs to be in a separate popup 🤔

**Comment by reduz** [comment] 2023-01-13 10:02
@KoBeWi This should have been fixed by #67397 if I am not mistaken?

**Comment by reduz** [comment] 2023-01-13 19:19
Closing as confirmed fixed.

**Closed by reduz** 2023-01-13 19:19 UTC
Labels: bug, topic:editor, regression
