### ISSUE TITLE
Scandal with a node slider and zoom

### ISSUE THREAD

**Issue by Torguen** [godotengine/godot#46632] opened 2021-03-03 20:51 UTC
**Godot version:**

3.2.4 rc3 mono

**OS/device including version:**

win10 64

**Issue description:**

A node's slider appears to drift out of its lane and becomes unselectable when applied zoom out. When you go to select it then it disappears and teases you.
To solve this, click on the micro-small area that indicates the length and drag it until the slider enters a safe area where it can be selected.

Obviously the slider should always be selectable and this is a clear problem that will have to be solved.
I just think the best thing is that it always remains visible

![GIF](https://user-images.githubusercontent.com/19652075/109875286-913ff000-7c70-11eb-86c5-3516ce4f7315.gif)

**Steps to reproduce:**
Necesary?

**Minimal reproduction project:**

[testSlider.zip](https://github.com/godotengine/godot/files/6079326/testSlider.zip)

**Comment by progammer** [comment] 2021-03-05 03:47
Hello, as a disclaimer, I'm fairly new and would like to contribute but I'm not entirely sure where to start
I've managed to locate the icon @ ./editor/icons/GuiSliderGrabber.svg but was unable to find where the resource may have been declared for usage, I've also taken a peek into ./editor/animation_track_editor.cpp but I'm not sure if I'm looking in the right place.. I'd appreciate it if anyone could guide me to where I should be looking

**Comment by jmb462** [comment] 2021-03-05 14:31
@progammer Sorry, I've started investivating on this issue yesterday and I've juste submit a PR (#46693) .

I think the problem was in editor_spin_slider.cpp
The scale of the GraphEdit wasn't applied when calculating the grabber position.

**Comment by progammer** [comment] 2021-03-05 16:04
@jmb462 Not sure why you're apologizing! It's great that you found it :)

**Comment by Torguen** [comment] 2021-03-12 16:01
This is not fixed in RC4 right?

It keeps happening in RC4

**Comment by jmb462** [comment] 2021-03-12 16:28
@Torguen My PR is still in discussion and has not been merged.
(And this PR is for 4.0 so IF it is merged, it will need to be cherrypicked to 3.2 later IF it's possible).

**Comment by akien-mga** [comment] 2021-03-13 21:19
For the reference, I checked and this doesn't seem to be a regression (reproducible in 3.2-stable and 3.2.3-stable too).

**Closed** 2021-03-14 10:35 UTC
Labels: bug, topic:gui, usability
