### ISSUE TITLE
Allow Godot 2D to render Vector images

### ISSUE THREAD

**Issue by Raj2032** [godotengine/godot#16883] opened 2018-02-21 11:41 UTC
Traditionally game engines only use Bitmap images. Can we get Godot to support Vector images, like SVG formats?

**Comment by akien-mga** [comment] 2018-02-21 12:28
Duplicate of #4826.

**Closed by akien-mga** 2018-02-21 12:28 UTC

**Comment by poke1024** [comment] 2018-03-18 21:33
See https://github.com/poke1024/godot_svg_plus
