### ISSUE TITLE
Godot 3D Atlas Texture not cropping

### ISSUE THREAD

**Issue by SenhorPatolino** [godotengine/godot#71012] opened 2023-01-07 02:52 UTC
### Godot version

4.0 beta 10

### System information

Windows 10, Vulkan, NVIDIA Driver V.528.02

### Issue description

 AtlasTexture gets applied to the plane, however the crop region does not function properly :
![image](https://user-images.githubusercontent.com/61413244/211128040-fb66354c-940d-4f91-8295-21cab53ec28a.png)

### Steps to reproduce

1. Apply an .atlastex file into a plane mesh
2. Crop using "Edit Region" at the texture settings

### Minimal reproduction project

[Debug.zip](https://github.com/godotengine/godot/files/10365382/Debug.zip)

**Comment by Calinou** [comment] 2023-01-07 18:52
Duplicate of https://github.com/godotengine/godot/issues/33855 (AtlasTexture is only supported in 2D).

**Closed by Calinou** 2023-01-07 18:52 UTC
Labels: bug, topic:editor, topic:3d
