### ISSUE TITLE
Audio Input issue

### ISSUE THREAD

**Issue by CystalCore** [godotengine/godot#51195] opened 2021-08-02 17:34 UTC
### Godot version

3.3.2 Stable

### System information

Windows 10

### Issue description

I'm trying to make a PNGtuber program for my friends but after about an hour of running the audio input starts having a double effect and after a second hour it has a full 1 second delay. 

### Steps to reproduce

to reproducer this take the recording demo,
add a spectrum analyzer and remove record,
setup a way to see the spectrum,
run the program for an hour then say something into the mic.
 

### Minimal reproduction project

https://github.com/CystalCore/Godot-audio-error

**Comment by fire** [comment] 2021-08-02 17:44
@ellenhp Could take look if she wants.

**Comment by ellenhp** [comment] 2021-08-02 18:42
When you say it has a double effect, do you mean that you can hear two voices (one second apart) in your stream whenever you say anything, or do you mean that you can say something and then you hear your own voice a full second after you'd expect to? I assume it's the latter, but I want to confirm.

My plate is pretty full right now but I'll try and take a look sometime.

**Comment by CystalCore** [comment] 2021-08-02 18:56
the visual effect from the audio happens twice
I will run an unmuted test to see if it is feed back or the audio double playing

**Comment by CystalCore** [comment] 2021-08-02 19:40
so at 37 minutes i started to get feedback

**Comment by Calinou** [comment] 2021-08-02 20:18
The link to your minimal reproduction project doesn't work, as you posted the issue while the project was still uploading. Can you edit your original post and try to upload the project again?

**Comment by CystalCore** [comment] 2021-08-02 20:38
here is a video of the issue after about an hour of using the program with audio on
https://youtu.be/8PXOiIqEP1g
I will make a repo of the project and link that

**Comment by CystalCore** [comment] 2021-08-02 20:44
https://github.com/CystalCore/Godot-audio-error
here is a link to the project on git

**Comment by CystalCore** [comment] 2021-08-05 22:54
also this could be part of the issue but i use a custom built PC that doesn't have a sound card so i don't have an audio mixer. I don't see how it could be an issue but if it works fine for you and not for me then that is probably the issue.

**Comment by Calinou** [comment] 2021-08-05 22:55
> also this could be part of the issue, I use a custom built PC that doesn't have a sound card so I don't have an audio mixer. I don't see how it could be an issue but if it works fine for you and not for me then that is probably the issue.

Dedicated sound cards are uncommon nowadays, so I don't think that's the source of the issue.

**Comment by CystalCore** [comment] 2021-08-17 19:44
is there any way to turn off and on the Enable Audio Input option of the project and would that somehow reset the audio so that it doesn't get feed back? also my mic goes to Voicemod and that goes to Godot could that be causing the issue?

**Comment by CystalCore** [comment] 2021-08-19 22:05
Godot 3.3.3 has this in the update notes "Audio: Fix cubic resampling algorithm (GH-51082)." I will see if this somehow fixes the issue and I will follow up with results.

**Comment by CystalCore** [comment] 2021-08-19 22:59
update 3.3.3 audio changes did not change the outcome of the project

**Comment by Calinou** [comment] 2021-08-19 23:49
> Godot 3.3.3 has this in the update notes "Audio: Fix cubic resampling algorithm ([GH-51082](https://github.com/godotengine/godot/pull/51082))." I will see if this somehow fixes the issue and I will follow up with results.

This pull request only affected audio *output*, not input.

**Comment by Calinou** [comment] 2021-11-06 00:41
> Is there any way to reset the Audio Stream after a amount of time has elapsed

Godot doesn't have a way to reset the sound engine without restarting the rest of the engine.

PS: Are you using an USB microphone? If so, this issue's cause could be the same as https://github.com/godotengine/godot/issues/54544.

**Comment by CystalCore** [comment] 2021-11-06 17:00
I am i will check this out

**Comment by airisun** [comment] 2021-11-06 17:00
@CystalCore  Can you try this project file? Try it with voicemod and without voicemod. And are u using usb microphone?
[Mic Testing.zip](https://github.com/godotengine/godot/files/7468757/Mic.Testing.zip)

**Comment by CystalCore** [comment] 2021-11-07 21:52
It is a USB mic plugged into a USB 3.0

**Comment by CystalCore** [comment] 2021-11-07 23:00
im using godot 3.4 and so far the test project it hasn't broke yet, i have yet to try it with my project which uses Spectrum and not Volume Peak to see if that causes a difference.

**Comment by airisun** [comment] 2021-11-08 02:40
With my project file, It works just fine for analog microphone with audio jack. For usb mic or microphone with audio interface, it will face a latency issue. Either right from the beginning or after about 30 minutes of usage.

**Comment by CystalCore** [comment] 2021-11-08 02:46
yeah I updated to godot 3.4 and it hasn't happened yet with your setup or mine so 3.4 might have fixed it

**Comment by airisun** [comment] 2021-11-08 02:49
Well you can try run the test for awhile and see if the issue is still there

**Comment by CystalCore** [comment] 2021-11-08 16:08
I ran both yours and mine for 2 to 3 hours and didn't get any feedback what so ever.

**Comment by CystalCore** [comment] 2021-11-08 16:09
however there is a chance where exporting and running in the engine cause a difference but that wasn't making a difference before 3.4

**Comment by CystalCore** [comment] 2021-11-08 16:15
The Godot 3.4 change log has "Fix cubic resampling algorithm (GH-51082)" which appears to have issues I had but with proper terminology, I was experience audio artifacts after an amount of time. This does appear to be fixed.

**Comment by Calinou** [comment] 2021-11-08 17:39
Closing as resolved in 3.4.

**Closed by Calinou** 2021-11-08 17:39 UTC
Labels: bug, needs testing, topic:audio
