### ISSUE TITLE
glTF export sets vertex color mode to a setting that will break in re-import

### ISSUE THREAD

**Issue by RPicster** [godotengine/godot#85383] opened 2023-11-26 13:58 UTC
### Godot version

4.2RC2

### System information

Windows 10

### Issue description

In my example I exported a scene where I combined different 3D plants to an arrangement.
My plan was to join meshes in Blender and reimport the gltf to save draw calls.

After joining and exporting back to glTF from Blender, vertex colors were broken and on the wrong vertices.

Investigation brought up that the type of vertex colors is changed after exporting from Godot:
![image](https://github.com/godotengine/godot/assets/9423774/b889e670-d96e-490c-80f5-5cf61209b673)
These are the default Blender settings.

These are the settings after exporting from Godot:
![image](https://github.com/godotengine/godot/assets/9423774/2c3b3336-e26f-4e19-8482-a4b5a2f7827c)

Converting back to the default setting inside Blender solved the broken vertex colors.

### Steps to reproduce

- Export 3D mesh with vertex colors from Godot.
- Open in Blender, export.
- Reimport in Godot.

### Minimal reproduction project

-

**Comment by fire** [comment] 2023-11-26 17:57
What version of blender are you using? I suspect this is a new Blender 4 feature.

**Comment by RPicster** [comment] 2023-11-26 18:12
> What version of blender are you using? I suspect this is a new Blender 4 feature.

I tried it in Blender 3.6LTS and Blender 4.
The problem seems to be how the data is exported from Godot, not in Blender.

**Comment by lyuma** [comment] 2023-12-24 05:14
This is not a Godot issue: it is a limitation of the glTF format. You will notice the same occurs when exporting and re-importing a mesh with vertex colors back into Blender.
![example showing vertex colors before and after export](https://github.com/godotengine/godot/assets/39946030/5701ea6d-d1b5-49dc-b8e0-f02d1a8cc998)

The one surprising thing is that Blender does not support exporting float colors, given that the comments in this issue https://projects.blender.org/blender/blender-addons/issues/99005 appear to indicate that non-byte color and non-face-corner vertex colors.

As an example, shown in the screenshot above, I used the Python Console to make one vertex color have a red component of 10.0, a value which is only representable as Color and not Byte Color. As you can see, after export and import, this vertex now has a red component of 1.0, as this is the highest possible Byte Color.

I have attached the blend and exported glb files here for testing:
[blender_color_cube_test.zip](https://github.com/godotengine/godot/files/13760911/blender_color_cube_test.zip)

See also this comment: https://github.com/KhronosGroup/glTF-Blender-IO/issues/542#issuecomment-1360419098 indicating that the Color vs Byte Color has to do with sRGB to linear conversion.

All this said, given that this is a Blender issue and a glTF format issue, we cannot solve this in Godot itself, so I will close this issue. Thanks for testing vertex colors and this is all good information to be aware of in the future.

**Closed by lyuma** 2023-12-24 05:14 UTC
Labels: bug, topic:import, topic:3d, topic:export

**Comment by lyuma** [comment] 2023-12-24 05:18
OK, hold on, I may have fixated on the wrong part of this bug.

You also noted that "After joining and exporting back to glTF from Blender, vertex colors were broken and on the wrong vertices." This sounds like a serious issue and unrelated to the other problem of "Vertex" vs "Face Corner.

That said, this will require a reproduction project and test model, There are a lot of steps you implied take place in terms of re-importing and merging meshes, to guess exactly how you were doing this.

I would also guess tat this may be a Blender issue rather than a Godot issue. So we definitely need a reproduction project.
If you do make a reproduction case for vertex colors being mixed up and are sure it's not a bug in Blender itself, please attach it here and we can re-open the issue, or you can file a new issue about just that problem.
