### ISSUE TITLE
Weird collision between a cylinder and a cube

### ISSUE THREAD

**Issue by svprdga** [godotengine/godot#79196] opened 2023-07-08 10:16 UTC
### Godot version

4.1.stable.flathub

### System information

Godot v4.1.stable (970459615) - Freedesktop SDK 22.08 (Flatpak runtime) - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1070 (nvidia) - Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 Threads)

### Issue description

In my game I have a player that has a cylinder as a collision shape. There are also boxes around.

The issue is when I try to collide with the boxes in a particular angle.

It's better to watch it:

https://github.com/godotengine/godot/assets/43069276/5bbd3606-95a3-475d-a47c-fbfc7f2465e4

I don't know if this is the expected behavior, but as the shape is a cylinder I thought that the player should slide along the face of the box .

### Steps to reproduce

1. Create a moving object 
2. Collide against a Box like I do in the video

### Minimal reproduction project

N/A

**Comment by kleonc** [comment] 2023-07-08 12:27
Looks like a duplicate of #72198, closing as such then. Thanks for the report though! :slightly_smiling_face:

**Closed by kleonc** 2023-07-08 12:27 UTC
