### ISSUE TITLE
bug in setting the global rotation degrees value

### ISSUE THREAD

**Issue by KridaCreations** [godotengine/godot#94807] opened 2024-07-26 16:54 UTC
### Tested versions

4.1, 4.2.2

### System information

Windows 11

### Issue description

I am developing a multiplayer game and faced a weird scenario
the structure of my player character is like this
mainnode
->bodymesh(child node of main node)
->headnode(child node of main node)
->->head mesh(child node of head node)

i am using the body to rotate around the y axis(left right) and head to rotate around the x axis(up and down)

i am setting the rotation of character first by setting the rotation degrees vector of mainnode and then setting the rotation degrees value of the head node(which is a descendant of the main node)

but setting the rotation of head node is resetting the main rode rotation have any of you also faced the issue

### Steps to reproduce

[TransformIssue.zip](https://github.com/user-attachments/files/16394610/TransformIssue.zip)
run the world scene in the project i have attached

### Minimal reproduction project (MRP)

[TransformIssue.zip](https://github.com/user-attachments/files/16394613/TransformIssue.zip)

**Comment by AThousandShips** [comment] 2024-07-26 16:56
Please try with a supported version, like 4.1.4, or better 4.2.2, 4.1 is no longer supported

**Comment by KridaCreations** [comment] 2024-07-26 16:57
i found a way around it by setting the x,y,z components individually
instead of this 
<img width="437" alt="image" src="https://github.com/user-attachments/assets/56e73e8e-2a05-4879-8046-41289d0cecfe">
do this
<img width="449" alt="image" src="https://github.com/user-attachments/assets/074fe178-1b08-454e-9579-f82545033f22">

**Comment by KridaCreations** [comment] 2024-07-26 17:00
> Please try with a supported version, like 4.1.4, or better 4.2.2, 4.1 is no longer supported

i tested the same issue in 4.2.2 stable it is their

**Comment by KridaCreations** [comment] 2024-07-26 17:01
i moved back to 4.1 from 4.2 because i was facing some issue in remote debugger of 4.2 which was making the editor slow (atleast that what i think)

**Comment by 4X3L82** [comment] 2024-07-27 15:42
> i found a way around it by setting the x,y,z components individually instead of this <img alt="image" width="437" src="https://private-user-images.githubusercontent.com/77878199/352607902-56e73e8e-2a05-4879-8046-41289d0cecfe.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIwOTQ3NzMsIm5iZiI6MTcyMjA5NDQ3MywicGF0aCI6Ii83Nzg3ODE5OS8zNTI2MDc5MDItNTZlNzNlOGUtMmEwNS00ODc5LTgwNDYtNDEyODlkMGNlY2ZlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI3VDE1MzQzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE5Zjg0MGE0ZWI2ZjU4M2NjYmM2MjVmOGI5NTYyNzQyMTc4Mjc5NDU1YjNjY2IxOTQ1OTM0NmM4YWUxNDRkOTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.HWFuJQE-cKvVdFOuPu_Tj6IenfPSJT0I-_yDzgvdpDM"> do this <img alt="image" width="449" src="https://private-user-images.githubusercontent.com/77878199/352608111-074fe178-1b08-454e-9579-f82545033f22.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIwOTQ3NzMsIm5iZiI6MTcyMjA5NDQ3MywicGF0aCI6Ii83Nzg3ODE5OS8zNTI2MDgxMTEtMDc0ZmUxNzgtMWIwOC00NTRlLTk1NzktZjgyNTQ1MDMzZjIyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI3VDE1MzQzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZlODY0ZDEzZTQzYWE4MWI3M2FmYWNjOWUwZDM0NDlmYWNkNDE5ODg0ZDgwZmYyZDY0NDk0ZGM3NDMwMGZkZGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.66vV3-0V-qjeeXFC4cv-dSnWEZ3YvmtugGahS4Z3l1w">

It's because you are using `global_rotation_degrees`. Global means not local, meaning the rotation (or position, etc) of itself/the parent (in this case  your "Main") is ignored. Try using `.rotation_degrees` instead.

**Comment by kleonc** [comment] 2024-07-27 23:20
> but setting the rotation of head node is resetting the main rode rotation have any of you also faced the issue

It doesn't, the `headNode.global_rotation_degrees = (headGlobalRotationDegrees)` line in the MRP doesn't change/affect the `PlayerNode.global_rotation_degrees` anyhow.

Changing `headNode.global_rotation_degrees` affects only the `transform` of `headNode`, and given that `headNode` is a child of `PlayerNode` it doesn't affect `PlayerNode.global_transform` (from which `global_rotation_degrees` is calculated).

In the MRP you can't observe the `mainNode` to rotate around Y just fine because it has only a vertical cylinder mesh child. Adding e.g. a leg shows it rotates just fine:

![Godot_v4 2 2-stable_win64_TCMok2vKrd](https://github.com/user-attachments/assets/08ac2ba7-a36a-4a6e-b52b-41b7eb0b631e)|![Ww0xbfNKGi](https://github.com/user-attachments/assets/56cc788f-6338-4326-862c-53a11c679fc2)
-|-



---

Changing the global rotation of the parent changes the global rotation of the child, thus if you'd want to account for the parent's global rotation change when changing the global rotation of the child, then the child global rotation should be read after actually modifying the parent's global rotation.

So instead of:
```gdscript
var parent_global_rotation = parent.global_rotation_degrees
var child_global_rotation = child.global_rotation_degrees # Reading before changing the parent global transform, thus not taking such change into account.

... # Modify `parent_global_rotation`.
... # Modify `child_global_rotation`.

parent.global_rotation_degrees = parent_global_rotation
child.global_rotation_degrees = child_global_rotation
```
doing something like:
```gdscript
var parent_global_rotation = parent.global_rotation_degrees
... # Modify `parent_global_rotation`.
parent.global_rotation_degrees = parent_global_rotation

var child_global_rotation = child.global_rotation_degrees # Reading after changing the parent global transform, thus taking such change into account.
... # Modify `child_global_rotation`.
child.global_rotation_degrees = child_global_rotation
```
would make it work like you'd expect it to @KridaCreations.

---

So AFAICT everything works correctly in here, unexpected behavior is caused by a faulty user logic. Closing as not a bug.

**Closed by kleonc** 2024-07-27 23:20 UTC
Labels: needs testing, topic:3d

**Comment by KridaCreations** [comment] 2024-07-28 01:32
> > but setting the rotation of head node is resetting the main rode rotation have any of you also faced the issue
> 
> It doesn't, the `headNode.global_rotation_degrees = (headGlobalRotationDegrees)` line in the MRP doesn't change/affect the `PlayerNode.global_rotation_degrees` anyhow.
> 
> Changing `headNode.global_rotation_degrees` affects only the `transform` of `headNode`, and given that `headNode` is a child of `PlayerNode` it doesn't affect `PlayerNode.global_transform` (from which `global_rotation_degrees` is calculated).
> 
> In the MRP you can't observe the `mainNode` to rotate around Y just fine because it has only a vertical cylinder mesh child. Adding e.g. a leg shows it rotates just fine:
> 
> ![Godot_v4 2 2-stable_win64_TCMok2vKrd](https://github.com/user-attachments/assets/08ac2ba7-a36a-4a6e-b52b-41b7eb0b631e)	![Ww0xbfNKGi](https://github.com/user-attachments/assets/56cc788f-6338-4326-862c-53a11c679fc2)
> Changing the global rotation of the parent changes the global rotation of the child, thus if you'd want to account for the parent's global rotation change when changing the global rotation of the child, then the child global rotation should be read after actually modifying the parent's global rotation.
> 
> So instead of:
> 
> ```gdscript
> var parent_global_rotation = parent.global_rotation_degrees
> var child_global_rotation = child.global_rotation_degrees # Reading before changing the parent global transform, thus not taking such change into account.
> 
> ... # Modify `parent_global_rotation`.
> ... # Modify `child_global_rotation`.
> 
> parent.global_rotation_degrees = parent_global_rotation
> child.global_rotation_degrees = child_global_rotation
> ```
> 
> doing something like:
> 
> ```gdscript
> var parent_global_rotation = parent.global_rotation_degrees
> ... # Modify `parent_global_rotation`.
> parent.global_rotation_degrees = parent_global_rotation
> 
> var child_global_rotation = child.global_rotation_degrees # Reading after changing the parent global transform, thus taking such change into account.
> ... # Modify `child_global_rotation`.
> child.global_rotation_degrees = child_global_rotation
> ```
> 
> would make it work like you'd expect it to @KridaCreations.
> 
> So AFAICT everything works correctly in here, unexpected behavior is caused by a faulty user logic. Closing as not a bug.

oh sorry i realized my mistake, thanks for clarification
