### ISSUE TITLE
Godot editor usability- ability to remember scenes that were last opened when closing the project

### ISSUE THREAD

**Issue by blurymind** [godotengine/godot#12556] opened 2017-11-01 09:35 UTC
Right now if you open multiple scenes in the editor, save the project and close it, when you reopen it - godot will only open the main scene. You will need to re-open the other project scenes again.

It would be a nice usability bonus if the editor remember which scenes were last opened in previous session- and open them when the project is opened again

**Comment by akien-mga** [comment] 2017-11-01 10:08
Duplicate of #2385.

**Closed by akien-mga** 2017-11-01 10:08 UTC
