### ISSUE TITLE
GDScript bug "constant already exists" in 3.1 (prob related to optional typing changes)

### ISSUE THREAD

**Issue by nazgum** [godotengine/godot#23599] opened 2018-11-08 19:02 UTC
**Godot version:**
3.1 Alpha 2

**OS/device including version:**
Ubuntu Linux

**Issue description:**
With the changes to gdscript to add optional typing, it is throwing an error for constant already exists, even when scoped within another variable such as an enum.

**Steps to reproduce:**
The following code triggers the error:

```
enum Forest {
  PATH1 = 5
}

enum Dungeon {
  PATH1 = 5
}
```

But Forest.PATH1 and Dungeon.PATH1 should be allowed here, as they are scoped within their own enums.

I use this with TileSets in my game, where I use enums to map the tile ids.

**Minimal reproduction project:**
Attached is a picture showing the bug, as its simple to see in a single file.

![godot-alpha2-bug](https://user-images.githubusercontent.com/13953/48220531-8c4b2a00-e35d-11e8-9808-50d39c8beed2.png)

**Comment by bojidar-bg** [comment] 2018-11-08 19:06
Duplicate of #22293 (to be fixed when #19650 is).

**Closed by bojidar-bg** 2018-11-08 19:06 UTC
