### ISSUE TITLE
Godot does not repeat sound playback correctly.

### ISSUE THREAD

**Issue by Torguen** [godotengine/godot#43935] opened 2020-11-28 16:09 UTC
**Godot version:**

3.2.4 beta 3 mono

**OS/device including version:**

win10 64

**Issue description:**

I need to play a sound (my project is at 24 fps) in a loop but I should not use the import option "loop" for X reasons.
But Godot cannot do this, Godot does not do a perfect repetition because there are always small silences between one playback and the next, even if you use signals!
...
Don't ask the question "Why don't you use the loop option when import? This will fix it."
...
Why do I need this?
I am trying to play music imitating the NES console, I have the patterns in separate audio files.
After one pattern, another is played, there cannot be a silence after a pattern because it will break the rhythm of the song.
Some songs have an intro that is never repeated in the song, after the intro the song starts but Godot doesn't make a perfect playback when a playback ends, so the result is not satisfactory.

**Steps to reproduce:**
Import a sound and try to loop it without using the "loop" option when importing the file ... you won't be able to.
Looping correctly can only be achieved if you use the "loop" option when importing the sound.

**Minimal reproduction project:**

[testFamiStudio.zip](https://github.com/godotengine/godot/files/5610867/testFamiStudio.zip)
![Captura2](https://user-images.githubusercontent.com/19652075/100520164-a9e5c900-319c-11eb-8813-9078d1d5b236.PNG)

**Comment by Calinou** [comment] 2020-11-28 16:22
Duplicate of https://github.com/godotengine/godot/issues/32382.

> Why do I need this?
> I am trying to play music imitating the NES console, I have the patterns in separate audio files.
> After one pattern, another is played, there cannot be a silence after a pattern because it will break the rhythm of the song.
> Some songs have an intro that is never repeated in the song, after the intro the song starts but Godot doesn't make a perfect playback when a playback ends, so the result is not satisfactory.

I think you'll need a C++ module to replicate some kind of tracker music/soundfont functionality…

**Closed by Calinou** 2020-11-28 16:22 UTC

**Comment by Torguen** [comment] 2020-11-28 16:25
Well if you have closed it then you should be safe and not make an assumption.
So if you are sure that there is no way to get this done without "digging deeper" then ok.
