### ISSUE TITLE
Flatpak/Snap export

### ISSUE THREAD

**Issue by Sandvich** [godotengine/godot#25376] opened 2019-01-27 12:38 UTC
Hi!
I think it'd be really useful to have a flatpak or snap export for Godot games, instead of/in addition to the current Linux export. It should make distribution much simpler.

**Comment by volzhs** [comment] 2019-01-27 12:47
duplicate of #5597 ?

**Comment by Sandvich** [comment] 2019-01-27 12:50
No, my understanding is that that one is for Godot itself to be available as a flatpak. This is for the games. Unless I'm misunderstanding that issue.

**Comment by fire** [comment] 2019-01-27 20:15
@Sandvich Do you know if the flatpack tools is usable from Windows / Mac? What dependencies do they have?

**Comment by Sandvich** [comment] 2019-01-29 01:05
I don't know a great deal about making flatpaks, sorry. I expect that they'd run on WSL, as it has some limited support for running flatpaks themselves, but I can't find any documentation on the matter. Same for OS X.

**Comment by clayjohn** [comment] 2020-05-27 05:34
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!

**Closed by clayjohn** 2020-05-27 05:34 UTC
Labels: feature proposal, topic:porting
