### ISSUE TITLE
Two scenes loading eachother (using export) causes Crash

### ISSUE THREAD

**Issue by ivanskodje** [godotengine/godot#7268] opened 2016-12-08 13:16 UTC
**Operating system or device - Godot version:**
2.1.1 stable (on Steam)

**Issue description** (what happened, and what was expected):
When I hit play, the game freezes and will not start.
 I have no idea what causes this, but I suspect it has something with using **export (PackedScene),** and having the scenes reference each-other. What is supposed to happen, is that scene_1 is supposed to change to scene_2 when pressing space (ui_select) - and scene_2 to change back to 1 when pressing space again. I would understand why this would happen if they would automatically load eachother (thus causing a loop), but neither scene is instancing the other at startup, so it is odd.

**_Edit 1:_** I can confirm that it still crashes, even if I do not run any code. It is definitely because of the e**xport (PackedScene)** that refer each-other.

**_Edit 2:_** If you change the next_scene inside scene_2.tscn
  `export (PackedScene) var next_scene`
into 
  `onready var next_scene = preload("res://scene_1/scene_1.tscn")`
It works perfectly. It has something to do with export. 

**Steps to reproduce:**
1. Download project files:
[Scene Transitioning - Bug.zip](https://github.com/godotengine/godot/files/639481/Scene.Transitioning.-.Bug.zip)

2. Hit play.

**Comment by eon-s** [comment] 2016-12-08 16:44
The example shows a "broken dependency error", after fixing it and when trying to run, on the console, you get the error (among others):
`ERROR: Another resource is loaded from path: res://scene_1/scene_1.tscn`

Is not taking the resource as the same one and seems to be trying to use the same path.

Also, the dependency error appears when re-loading the project.

**Comment by Tybobobo** [comment] 2016-12-09 23:33
Renamed to be a bit more descriptive, since I now know what is causing this

**Comment by williamd1k0** [comment] 2016-12-09 23:56
I believe that it happened with me too.
I created a scene manager to change scenes. I exported the next scene value like this:

```gdscript
export(String, FILE, "*.tscn") var next_scene
```
This works ok.

***
Yesterday I tried to change this system to export the actual `PackedScene` and it crashes for no apparent reason.
Tons of `Parse Error: [ext_resource] referenced nonexistent resource at:` in the console.

**Comment by williamd1k0** [comment] 2016-12-10 00:20
**Update**: Actually it really crashes if 2 scenes are "loading" each other.

I tested it on my game:
1. Load Main TitleScreen.
2. If you wait x seconds it changes to an "Attract Mode" scene (a "preview" of the game).
3. When "Attract Mode" ends, back to the Main TitleScreen.

If I remove the "Attract Mode" or the "back to TitleScreen when attract ends" from exported var it runs ok.

**Comment by arthurferrai** [comment] 2017-06-14 20:10
Happened with me too. But in my case, neither "Output" nor "Debugger" windows show any message about the problem (version 2.1.3 on Mac OS 10.11.6)

**Comment by bojidar-bg** [comment] 2017-06-14 20:29
Potentially related to #5958.

**Comment by arthurferrai** [comment] 2017-06-15 16:52
The problem looks the same when running project. But, in this case, the scenes are still editable.

**Comment by Noshyaar** [comment] 2018-04-08 03:53
First of all thank you for your report and sorry for the delay.

We released Godot 3.0 in January 2018 after 18 months of work, fixing many old issues either directly, or by obsoleting/replacing the features they were referring to.

We still have hundreds of issues whose relevance/reproducibility needs to be checked against the [current stable version](https://godotengine.org/download), and that's where you can help us.
**Could you check if the issue that you described initially is still relevant/reproducible in Godot 3.0 or any newer version, and comment about it here?**

For bug reports, please also make sure that the issue contains detailed steps to reproduce the bug and, if possible, a zipped project that can be used to reproduce it right away. This greatly speeds up debugging and bugfixing tasks for our contributors.

Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

Thanks in advance.

*Note: This message is being copy-pasted to many "stale" issues (90+ days without activity). It might happen that it is not meaningful for this specific issue or appears oblivious of the issue's context, if so please comment to notify the Bugsquad about it.*

**Comment by arthurferrai** [comment] 2018-04-08 18:49
It still happens on godot 3.0.2

**Comment by reduz** [comment] 2018-11-08 17:36
#9686 is the same (I mean, symptom may be different but the bug is the same), so closing this one.

**Closed by reduz** 2018-11-08 17:36 UTC
Labels: bug, topic:gdscript

**Comment by Shadowblitz16** [comment] 2023-04-21 02:14
Still happens in godot 4.0.2
