### ISSUE TITLE
Editor's "blue box" is two times smaller than "play" window

### ISSUE THREAD

**Issue by starrepo** [godotengine/godot#27172] opened 2019-03-17 17:58 UTC
**Godot version:**
3.1

**OS/device including version:**
*Hardware Overview:*
  Model Name:	MacBook Pro
  Processor Name:	Intel Core i5
  Processor Speed:	2.3 GHz
  Number of Processors:	1
  Total Number of Cores:	2
  L2 Cache (per Core):	256 KB
  L3 Cache:	4 MB
  Memory:	8 GB

*Intel Iris Plus Graphics 640:*
  Chipset Model:	Intel Iris Plus Graphics 640
  Type:	GPU
  Bus:	Built-In
  VRAM (Dynamic, Max):	1536 MB
  Vendor:	Intel
  Device ID:	0x5926
  Revision ID:	0x0006
  Metal:	Supported, feature set macOS GPUFamily2 v1
  Displays:
Color LCD:
  Display Type:	Built-In Retina LCD
  Resolution:	2560 x 1600 Retina
  Framebuffer Depth:	24-Bit Color (ARGB8888)
  Main Display:	Yes
  Mirror:	Off
  Online:	Yes
  Rotation:	Supported
  Automatically Adjust Brightness:	No

**Issue description:**
Blue box (design size) does not match to run-time window when you play selected scene. In fact, that blue box is two times smaller than the "play" window. This can be seen on macbook pro 13, however, I don't see the issue on Windows computer.

<img width="1164" alt="godotbluebox" src="https://user-images.githubusercontent.com/42064505/54495653-5eb75400-48ee-11e9-810b-79d3c446e55a.png">

**Steps to reproduce:**
1. Create new project
2. Create and save scene
3. Play the scene

**Comment by Calinou** [comment] 2019-03-17 21:12
This is because you're on a Retina display, so the window will automatically be resized to be twice as large as the initial size. To fix this, set the stretch mode to `2d` in the Project Settings (and the stretch aspect to `expand`).

See [Multiple resolutions](https://docs.godotengine.org/en/latest/tutorials/viewports/multiple_resolutions.html) in the documentation.

**Comment by abstractr** [comment] 2019-03-17 21:47
Changed stretch mode to 2d and aspect to expand

> This is because you're using an hiDPI display on macOS, which means the window will automatically be resized to be twice as large as the initial size. To fix this (by upscaling the viewport based on the window size), set the stretch mode to `2d` and the stretch aspect to `expand` in the Project Settings.
> 

I changed stretch mode to `2d` and the stretch aspect to `expand` and the issue is still there. Do you have other ideas? Is it possible to have the blue rectangle of the same size as play window on the mac?

**Comment by KoBeWi** [comment] 2019-03-29 14:26
Isn't it what Allow HiDPI option is for?

**Comment by toger5** [comment] 2019-03-30 00:32
yea I also think that Is what Allow HiDPI is for. It should be renamed to use `OS based dpi scale by sizing the window` or similar.

**Comment by Calinou** [comment] 2019-03-30 12:57
@toger5 Automatic window resizing based on DPI is currently only implemented on macOS. Also, we need to keep option names short when possible :slightly_smiling_face:

**Comment by toger5** [comment] 2019-03-30 18:01
What about 'use OS dpi scaling'

**Comment by Calinou** [comment] 2019-03-30 18:08
@toger5 The scaling factor is defined by the **Editor Scale** editor setting (which defaults to "Auto", including in running projects) but it could be customized by the user.

Also, renaming it would break existing projects that rely on it, so I don't think it's a good idea.

**Comment by toger5** [comment] 2019-03-31 16:44
@Calinou I am not sure that is correct. there is one option, `use hidpi theme` and that is doing what you mean. changing the theme to something more reasonable on higher dpi screens. most importantly changing font size.
But allow hidpi does something different. It tells the os to NOT updscale the frame buffer and draw it twice the size.

If you activate `allow hidpi` it draws everything as you would expect. deactivating it asks the os to upscale the buffer before drawing it to a window. And for that behaviour the name is really bad.. imo

**Comment by Calinou** [comment] 2019-03-31 18:26
@toger5 I guess it could be renamed to `enable_dpi_awareness` then. Mind creating a separate issue for that? :slightly_smiling_face:

**Comment by timothyqiu** [comment] 2020-01-08 07:34
I think this is resolved by #34824

The "blue box" at 100% scale is now the same size as the "play" window on a HiDPI monitor.

**Comment by akien-mga** [comment] 2020-01-08 07:38
Thanks, closing.

**Closed by akien-mga** 2020-01-08 07:38 UTC
Labels: enhancement, topic:editor
