### ISSUE TITLE
[beta 3] GPU Particle 2D damping works incorrectly

### ISSUE THREAD

**Issue by SanctusAnimus** [godotengine/godot#84053] opened 2023-10-27 13:03 UTC
### Godot version

v4.2.beta3.official [e8d57afae]

### System information

Godot v4.2.beta3 - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3080 (NVIDIA; 31.0.15.4592) - AMD Ryzen 9 5900X 12-Core Processor (24 Threads)

### Issue description

After upgrading to beta 3, some of my particles which have fixed velocity no longer move at all - they just spawn and stay, with damping set to 150-200 (min-max) and initial velocity of 160-160.
According to description (and to how it works in beta 2), those settings should mean that my particles are moving but will be slowed to 0 within 0.6-1s approx.

In beta 3, setting damping to just 10 is enough for my particle to not move at all. Does not happen in beta 2.
If behaviour / meaning of damping value was changed, this needs to be reflected in the documentation as well, otherwise it's a bug?

How it now works in beta 3:

https://github.com/godotengine/godot/assets/43399078/9ab05d4d-9cbb-4cbf-8a07-bb2b67e304fd

How it's supposed to work (and was working in beta 2):

https://github.com/godotengine/godot/assets/43399078/cc614804-9a5f-4054-bd4a-bec252e95058

FPS is low due to ShareX recording being considered as alt-tabbed, but should still be fairly obvious what's wrong.
Particle with material etc attached.

### Steps to reproduce

- Create GPUParticle2D
- Add ParticleProcessMaterial
- Remove gravity, set Initial velocity min/max to something high (1000 will do)
- Set damping under Acceleration to 15 / 15 (min / max) - emitted particles no longer moves.

### Minimal reproduction project

Attaching just the particle scene, as it's self-contained
[thruster_1.zip](https://github.com/godotengine/godot/files/13189187/thruster_1.zip)

**Comment by QbieShay** [comment] 2023-10-27 15:32
Should be addressed by https://github.com/godotengine/godot/pull/84028

**Comment by akien-mga** [comment] 2023-10-27 15:38
- Duplicate of #84009.

**Closed by akien-mga** 2023-10-27 15:38 UTC
Labels: bug, regression, topic:particles
