### ISSUE TITLE
AudioStreamPlayer: Remaps not always switch to the right language

### ISSUE THREAD

**Issue by VP-GAMES** [godotengine/godot#44633] opened 2020-12-23 22:09 UTC
**Godot version:**
v3.2.3

**OS/device including version:**
NAME="Ubuntu"
VERSION="20.04.1 LTS (Focal Fossa)"
OpenGL ES 3.0 Renderer: GeForce RTX 2080 SUPER/PCIe/SSE2

**Issue description:**
Audio (resources) configured in remaps not always switch to the right language

**Steps to reproduce:**
Create AudioStreamPlayer add Resource, create Remaps and change Languages, then push the play button, language change has effect, but not always sometimes the AudioStreamPlayer has old resource and play old language file(You have to play around with language change and push play button).

**Minimal reproduction project:**
[AudioRemaps.zip](https://github.com/godotengine/godot/files/5737296/AudioRemaps.zip)

**Comment by Gamemap** [comment] 2021-01-05 09:03
https://github.com/godotengine/godot/issues/42847

I think this is the same problem.

**Comment by Calinou** [comment] 2022-11-04 23:47
Duplicate of https://github.com/godotengine/godot/issues/42847.

**Closed by Calinou** 2022-11-04 23:47 UTC
Labels: bug, topic:core, needs testing, topic:audio
