### ISSUE TITLE
Confusing Editor Focus/Focus on multiple editor panels at the same time

### ISSUE THREAD

**Issue by Dante3085** [godotengine/godot#61158] opened 2022-05-18 16:08 UTC
### Godot version

3.4.4.stable.mono

### System information

Windows 11

### Issue description

**High-Level description**
When working in the Godot Editor I expect my focus to be in a specific editor panel, because I just clicked in it or an item in that panel was just selected etc.  For some panels like "FileSystem", "Scene" or the central viewport this is indicated by a gray outline. 
Sometimes the focus seems to be in multiple panels at once. When one action is performed in the presumed to be focused panel, but something happens in another panel, that is very confusing.

**Concrete Examples**
1. The script editor is open in the central viewport and one line is selected. Now I click inside the FileSystem panel and try to cut a file with CTRL+X. Not the file is cut, but the previously selected line in the code editor. It's completely fine if cutting files in the FileSystem panel is not implemented yet, but something happening in the code editor instead is very confusing.

2. Again, the script editor is opened and one line of code has just been added. Now I click inside the FileSystem panel and move a file from one folder to another. Then I press CTRL+Z to undo moving the file. Not the moving of the file is undone, but the code line in the script editor.

3. A working example with undo is when undoing, adding a new node as a child in the Scene panel.

### Steps to reproduce

Like the concrete examples say.

### Minimal reproduction project

I presume that this problem is independant of a specific project. Just to test that I downloaded and opened the "Escosia Game Template" from the Asset Library Projects and everything is as described.

**Comment by Calinou** [comment] 2022-05-18 17:48
Duplicate of https://github.com/godotengine/godot/issues/52861.

**Closed by Calinou** 2022-05-18 17:48 UTC
Labels: bug, topic:editor
