### ISSUE TITLE
Exported `PackedStringArray` loses focus after each character is typed

### ISSUE THREAD

**Issue by QueenOfSquiggles** [godotengine/godot#78712] opened 2023-06-26 14:56 UTC
### Godot version

4.1.beta3.mono [ada712e06]

### System information

Godot v4.1.beta3.mono - Manjaro Linux #1 SMP PREEMPT_DYNAMIC Sun Jun  4 12:31:46 UTC 2023 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1070 (nvidia; 530.41.03) - AMD Athlon(tm) X4 880K Quad Core Processor (4 Threads)

### Issue description

For any script (GDScript and C# tested) that is exporting a `PackedStringArray`, the inspector behaves strangely. When adding an element in the editor, the `LineEdit` loses focus after each character is typed. So between typing each character I have to click on the element again.

![image](https://github.com/godotengine/godot/assets/8940604/5f25e584-c6ab-405f-a6b6-81b2170666dc)

For example, after typing the "a", the element lost focus and my further typing goes nowhere.

### Steps to reproduce

Create a script that exports a `PackedStringArray`
Try to add an element with more than one character.

### Minimal reproduction project

Can be recreated very quickly. Any script exporting a `PackedStringArray` (GDScript and C# tested).
[Minimal example project can be found here: https://github.com/QueenOfSquiggles/PackedStringArray-Bug-Example](https://github.com/QueenOfSquiggles/PackedStringArray-Bug-Example)

**Comment by Sauermann** [comment] 2023-06-26 15:16
Can confirm in v4.1.beta3.official [ada712e06]
This is no longer reproducible in v4.1.beta.custom_build [afc5fa14a].

My guess is, that it got fixed by #78643.

**Comment by akien-mga** [comment] 2023-06-26 15:24
Thanks for testing!

- Duplicate of #78628

**Closed by akien-mga** 2023-06-26 15:24 UTC
Labels: bug, topic:editor
