### ISSUE TITLE
Transform Widget Flickering in 3D

### ISSUE THREAD

**Issue by hodgej** [godotengine/godot#35391] opened 2020-01-21 01:18 UTC
**Godot version:**
3.1, 3.2 RC1 and RC2
**OS/device including version:**
Windows 10, Lenovo Yoga
**Issue description:**
The Transform Widget disappears unless you angle the camera to a specific position/angle. This is a huge nuisance.

[As you can see, the Widget is there:](https://pasteboard.co/IQV4QrM.png)

[And then it's not, when I move the camera by a bit:](https://pasteboard.co/IQV4ZWi.png)

**Steps to reproduce:**
Open a 3D scene, use the Transform Widget.

**Comment by Calinou** [comment] 2020-01-21 01:21
I don't remember ever seeing this. Which graphics card do you have? Also, can you reproduce this in an empty project?

**Comment by hodgej** [comment] 2020-01-21 12:37
I use a Integrated Intel HD Graphics 620. When I get home I will be able to provide a project.

**Comment by Animatical** [comment] 2020-06-27 16:51
> I use a Integrated Intel HD Graphics 620. When I get home I will be able to provide a project.

I'm having this exact same issue. We have the same integrated graphics, so it's definitely an issue with that.

**Comment by Calinou** [comment] 2020-06-27 17:17
This is actually a duplicate of https://github.com/godotengine/godot/issues/30330, closing.

**Closed by Calinou** 2020-06-27 17:17 UTC
Labels: bug, confirmed, topic:editor, topic:rendering
