### ISSUE TITLE
Visualscript output can be connected to the same node's input

### ISSUE THREAD

**Issue by mrcdk** [godotengine/godot#11640] opened 2017-09-27 23:13 UTC
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Godot 3.0 master https://github.com/godotengine/godot/commit/da144fed4c49133a93b3b83cfc665352c0af351a

**Issue description:**

I don't think this should be allowed:

![https://i.imgur.com/8AU3l3x.png](https://i.imgur.com/8AU3l3x.png)

**Steps to reproduce:**
1. Add a node with inputs and outputs
2. Connect output to input

**Comment by djrm** [comment] 2017-09-27 23:22
duplicate of #6307

**Comment by groud** [comment] 2017-09-28 06:50
> duplicate of #6307

Closing then :)

**Closed by groud** 2017-09-28 06:50 UTC
