### ISSUE TITLE
Godot can't find PCK file when 'embed pck' on export is enabled

### ISSUE THREAD

**Issue by Wolfyxon** [godotengine/godot#45345] opened 2021-01-21 07:56 UTC
**Godot version:**
3.2.3 Stable.official

**OS/device including version:**
Windows 10

**Issue description:**
When I was exporting my game i enabled option 'embed pck' and after export i found just exe file no pck so i was glad there is option to export just 1 file instead of 2. Exe had an icon so i was very suprised. But when i launched it in console error popped up:
Error: Couldn't load project data at path ".". Is the .pck file missing?
If you've renamed the executable, the associated .pck file should also be renamed to match the executable's name (without the extension).

**Steps to reproduce:**
?

**Minimal reproduction project:**

I dont want to someone get my project. And i think project is not needed in this issue

**Comment by mrjustaguy** [comment] 2021-01-21 10:00
Unable to Reproduce what I think you're trying to explain.
Steps I took:
Export Embeded pck Enabled
Exported Test.exe
Ran Test.exe (worked just fine)
Renamed Test.exe to Tst.exe
Ran Tst.exe (worked just fine)

I Did Get the message when I didn't tick Embed Pck (so with it disabled) and renamed the Exe, however this is expected behavior as the error clearly states, the exe and pck names have to be identical as the exe is trying to load this like this example:
Get self name -> "Example.exe" -> remove .exe -> "Example" -> add .pck -> "Example.pck" -> Load "Example.pck"

**Comment by aaronfranke** [comment] 2021-01-21 10:31
> I dont want to someone get my project.

That's why it's called a **Minimal** reproduction project. We as Godot developers want the minimum required to reproduce the issue, because this greatly helps with narrowing things down.

I can't reproduce this bug. When I export [Dodge the Creeps](https://godotengine.org/asset-library/asset/515) with "Embed Pck" for Windows, I get a perfectly working build, with an EXE that works in any folder. Tested both with/without debug, both Windows and Linux. I also tested with the TPS demo and the executable is over 500 MB (so it's for sure embedding the resources).

This means that you will need to provide a minimal reproduction project, since others can't reproduce the bug you describe.

**Comment by Calinou** [comment] 2021-01-21 16:01
Did you export a 32-bit or 64-bit executable? 32-bit doesn't support PCK embedding: https://github.com/godotengine/godot/issues/35830

**Comment by ignasKavaliauskas** [comment] 2021-01-31 19:16
I've the same issue. 

> > I dont want to someone get my project.
> 
> That's why it's called a **Minimal** reproduction project. We as Godot developers want the minimum required to reproduce the issue, because this greatly helps with narrowing things down. We don't want you to send us your big project.
> 
> I can't reproduce this bug. When I export [Dodge the Creeps](https://godotengine.org/asset-library/asset/515) with "Embed Pck" for Windows, I get a perfectly working build, with an EXE that works in any folder. Tested both with/without debug, both Windows and Linux. I also tested with the TPS demo and the executable is over 500 MB (so it's for sure embedding the resources).
> 
> This means that you will need to provide a minimal reproduction project, since others can't reproduce the bug you describe.

Did you also set a custom icon inside the export template? 

I'm also having this issue, but only when trying to set a custom icon for the .exe. I'd to recompile the windows export template with my custom icon as default in order to make it work.

**Comment by furroy** [comment] 2021-03-09 15:32
I too am struggling with this. Once I added an ico with rcedit, unbeknownst to me it stopped working.  I was just building the Windows EXE in my project folder, and it runs fine there. But when I give it to someone else to run, they get missing pck error, even though I chose to embed it.  If I turn off the icon option and re-export it runs for other people again, but ofc no icon.  But maybe the fact that the same EXE runs in my local project folder with no errors is a clue to what's wrong. And no I don't have an external .pck file anywhere for it to find.

[https://i.gyazo.com/50762603c327e30d8f1ed64d15f3dedb.png](https://i.gyazo.com/50762603c327e30d8f1ed64d15f3dedb.png)

**Comment by furroy** [comment] 2021-03-13 19:29
For anyone else who needs a work around... Don't use rcedit, bad juju.  There's a tool "Resource Hacker" Use that on the original exe's in your godot/templates and don't give Godot the ico. Also not all ico's are made equal, since there can be multiple resolutions, multiple types, optional transparency, etc.  Use IcoFX to make your ico.

**Comment by nathanfranke** [comment] 2021-11-03 10:08
I'm getting this error when using `install` in a `PKGBUILD`.

```
[nathan@arch test]$ ls -l
total 34548
-rw-r--r-- 1 nathan users      133 Nov  3 04:52 PKGBUILD
-rwxr-xr-x 1 nathan users 35370880 Nov  3 04:51 Test.x86_64

[nathan@arch test]$ ./Test.x86_64 
Godot Engine v3.3.4.stable.official.faf3f883d - https://godotengine.org
OpenGL ES 3.0 Renderer: NVIDIA GeForce GTX 960/PCIe/SSE2
OpenGL ES Batching: ON

[nathan@arch test]$ cat PKGBUILD
pkgname=asd
pkgver=1
pkgrel=1
pkgdesc="Test"
arch=('x86_64')

package() {
        install -Dm755 '../Test.x86_64' "${pkgdir}/usr/bin/asd"
}

[nathan@arch test]$ makepkg
==> Making package: asd 1-1 (Wed 03 Nov 2021 04:52:27 AM CDT)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
==> Extracting sources...
==> Entering fakeroot environment...
==> Starting package()...
==> Tidying install...
  -> Removing libtool files...
  -> Purging unwanted files...
  -> Removing static library files...
  -> Stripping unneeded symbols from binaries and libraries...
  -> Compressing man and info pages...
==> Checking for packaging issues...
==> Creating package "asd"...
  -> Generating .PKGINFO file...
  -> Generating .BUILDINFO file...
  -> Generating .MTREE file...
  -> Compressing package...
==> Leaving fakeroot environment.
==> Finished making: asd 1-1 (Wed 03 Nov 2021 04:52:29 AM CDT)

[nathan@arch test]$ ls -l pkg/asd/usr/bin
total 34544
-rwxr-xr-x 1 nathan users 35370880 Nov  3 04:52 asd

[nathan@arch test]$ pkg/asd/usr/bin/asd
Error: Couldn't load project data at path ".". Is the .pck file missing?
If you've renamed the executable, the associated .pck file should also be renamed to match the executable's name (without the extension).
```

I tried the same PKGBUILD with 4M random bytes and glxgears, and those worked fine.

Project is zip exported on 3.3.4:
[Test9_1.zip](https://github.com/godotengine/godot/files/7466654/Test9_1.zip)

**Comment by Calinou** [comment] 2021-11-03 14:14
Duplicate of https://github.com/godotengine/godot/issues/33466.

**Closed by Calinou** 2021-11-03 14:14 UTC
Labels: bug, platform:windows, topic:porting, confirmed

**Comment by Tiberius92692** [comment] 2021-11-18 16:27
My project is randomly doing this if exported to secondary SSD. Works perfect exported to a folder on my desktop though. 

Hope this helps.
