### ISSUE TITLE
Textures do not appear in debug when assigned at runtime

### ISSUE THREAD

**Issue by chucklepie** [godotengine/godot#57696] opened 2022-02-06 09:32 UTC
### Godot version

3.4.2

### System information

PopOS

### Issue description

Have a texture assigned, in this case a TextureRect

![image](https://user-images.githubusercontent.com/12863685/152674881-754afef5-e18a-41ea-9c2d-92872c4a9c16.png)

Assign it in code, in this case it's an ImageTexture, but given to the texture, and you cannot view the texture, so you have no idea at all what is there for debugging.

![image](https://user-images.githubusercontent.com/12863685/152674923-134a07a9-2787-4651-a642-d776df3c92c1.png)

I'm guessing this is because in this case it is an ImageTexture, but it's being given to the texture so you would expect the IDE to be able to render it given the runtime can...

### Steps to reproduce

Create a texture at runtime, assign it to a texture.

**Comment by Zireael07** [comment] 2022-02-06 09:34
Duplicate of another issue I can't find atm - it is the case for some time that Resources created at runtime do not show in debugger.

**Comment by chucklepie** [comment] 2022-02-06 09:44
Ok, shall I close this?

**Comment by Chaosus** [comment] 2022-02-06 09:47
> Ok, shall I close this?

Until we find a duplicated issue - not.

**Comment by Calinou** [comment] 2022-02-06 11:08
Duplicate of https://github.com/godotengine/godot/issues/47237 (same cause).

**Closed by Calinou** 2022-02-06 11:08 UTC
Labels: bug, topic:editor
