### ISSUE TITLE
When more than 1 viewport is open, fly mode may incorrectly trigger selection mode change

### ISSUE THREAD

**Issue by bitinn** [godotengine/godot#81475] opened 2023-09-09 04:33 UTC
### Godot version

v4.1.1.stable.official [bd6af8e0e]

### System information

Godot v4.1.1.stable - macOS 13.5.0 - Vulkan (Forward+) - integrated Apple M2 Max - Apple M2 Max (12 Threads)

### Issue description

When 2 viewports are open, using fly mode (hold right mouse button, then press QWE keys) in the second viewport will cause all Godot viewports to switch mode. See attached videos.

https://streamable.com/izeh07

### Steps to reproduce

Open any 3D scene and navigate it as described.

### Minimal reproduction project

N/A as it is pretty trivial to repro, but note sometimes it is only reproduced in the second / third viewport; so my presumption is somehow input are not captured correctly and it triggered both fly mode and selection mode change.

**Comment by bitinn** [comment] 2023-09-09 04:35
Note: I did try to repro this on a brand new project and it is semi-consistently reproduced on the 2nd / 3rd viewport, the 1st viewport seems less affected.

**Comment by timothyqiu** [comment] 2023-09-09 05:57
I can confirm this.

It seems that capturing the mouse still sends movement events. So whichever viewport covering center point of the screen grabs focus.

**Comment by Calinou** [comment] 2023-09-09 15:40
cc @Sauermann

**Comment by Sauermann** [comment] 2023-09-09 16:29
Conceptually it looks like the QWE-keys are intended to be use for navigating the camera, but fail to set the input event as handled, so they are additionally interpreted for changing the mode.

**Comment by ryevdokimov** [comment] 2024-05-19 20:44
Duplicate of: https://github.com/godotengine/godot/issues/87639

Which was solved by: https://github.com/godotengine/godot/pull/88275

**Closed** 2024-05-20 06:30 UTC
Labels: bug, topic:editor, confirmed, usability, topic:input, topic:3d
