### ISSUE TITLE
SkeletonModification2DTwoBoneIK throws errors and warnings when used

### ISSUE THREAD

**Issue by IvanIG3** [godotengine/godot#75022] opened 2023-03-17 11:41 UTC
### Godot version

4.0.stable

### System information

Windows 10, Vulkan, NVIDIA GeForce GTX 1070

### Issue description

When using a SkeletonModification2DTwoBoneIK in a modification stack for a Skeleton2D, some errors and warnings are thrown to the console.

![console](https://user-images.githubusercontent.com/54667250/225893871-9bd5fee2-3f28-4db3-9b20-f99bdf9baf50.png)

### Steps to reproduce

Just execute the project below to see errors and warnings.

### Minimal reproduction project

[skeleton_ik_test.zip](https://github.com/godotengine/godot/files/11000896/skeleton_ik_test.zip)

**Comment by Calinou** [comment] 2023-05-08 17:38
- Duplicate of https://github.com/godotengine/godot/issues/73247 (same cause).

**Closed by Calinou** 2023-05-08 17:38 UTC
Labels: bug, topic:animation
