### ISSUE TITLE
glTF importer tries to use base64 text as file path

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#33796] opened 2019-11-21 16:45 UTC
**Godot version:**
3.2.beta.custom_build. 083d088de

**OS/device including version:**
Ubuntu  19.10
**Issue description:**
After importing minimal project there is a lot of errors but I saw that Godot try to use encoded base64 text as path to files.
```
ERROR: get_file_as_array: Can't open file from path 'res://2.0/SimpleMorph/glTF-Embedded/data:application/gltf-buffer;base64,AAABAAIAAAAAAAAAAAAAAAAAAAAAAIA/AAAAAAAAAAAAAAA/AAAAPwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIC/AACAPwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIA/AACAPwAAAAA='.
   At: core/os/file_access.cpp:602.
ERROR: get_file_as_array: Can't open file from path 'res://2.0/SimpleMorph/glTF-Embedded/data:application/gltf-buffer;base64,AAAAAAAAgD8AAABAAABAQAAAgEAAAAAAAAAAAAAAAAAAAIA/AACAPwAAgD8AAIA/AAAAAAAAAAAAAAAA'.
   At: core/os/file_access.cpp:602.
```
or very long(> 50000 characters)
```
ERROR: _load: No loader found for resource: res://2.0/AlphaBlendModeTest/glTF-Embedded/data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAABAAAAAQACAYAAAB/HSuDAAAABmJLR0QAAAAAAAD5Q7t/AAAACXBIWXMAAA3XAAAN1wFCKJt4AAAAB3RJTUUH4gMQFzc3sTKNqAAAIABJREFUeNrs3Xl0VPXB/HPnS0zkwBZIAExLCKCtipHXFAQq6WAVCygsqq1WvVU1Kp9cO1Pq61a1Frbx2oVbRUkiqCIFgEFVKgKCFZFLYLKElCSkIQlmZksc7+/P56nPA4TkkAWvhPer3PmnM7NnZlv3kPHud/cxREAAAAAWMQYY6gAND8PCQAAAAAAYAIAAAAAAAAwAQAAAAAAAJgAAAAAAAAATAAAAAAAAAAmAAAAAAAAABMAAAAAAACACQAAAAAAAMAEAAAAAAAATAAAAAAAAAAmAAAAAAAAABMAAAAAAACACQAAAAAAAMAEAAAAAAAAYAIAAAAAAAAwAQAAAAAAAJgAAAAAAACACQAAAAAAAMAEAAAAAAAAYAIAAAAAAAAwAQAAAAAAAJgAAAAAAAAATAAAAAAAAAAmAAAAAAAAABMAAAAAAAAwAQAAAAAAAJgAAAAAAAAATAAAAAAAAAAmAAAAAAAAABMAAAAAAACACQAAAAAAAMAEAAAAAAAAYAIAAAAAAAAwAQAAAAAAABMAAAAAAACACQAAAAAAAMAEAAAAAAAAYAIAAAAAAAAwAQAAAAAAAJgAAAAAAAAATAAAAAAAAAAmAAAAAAAAYAIAAAAAAAAwAQAAAAAAAFKUjwQAAAAAYKfKykrNnj1bCxcu1IcffqiSkhJFo1F16tRJRx11lIYOHaoJEyboqKOOIhYa5JAAAAAAgE2MMYYK0pNPPqk777xTRUVF9a7n9/t11VVX6YEHHlA4HCYcmAAAAAAAwARAKqipqdHVV1+tv/97wf0uP79+2v+/PnKy8vjHxGYAAAAAADABIDtrrrqKk2bNu2gHnv66afrnXfekd/v5x8SknASQAAAAACwxKxZs+rc+B84cKAWLFig8vJyVVZW6r333tOYMWOS1nv/fd1zz33EBIAAAAAYD9zmIrH46Z3795GUsJt3LhxJh6P1/mYG264IWn9du3ambKyMgPsi08XAAAAAEwAWGDevHlJG/Ndu3Y1e/bs2e9jqqurzTHHHJP0uMcee2zfDb+EmzHGrFq1yowdO9Z07tzZBAIBc+SRR5rLL7/cbNy4cb+vV1tba9544w1z4403mkGDBplOnToZv99v2rdvb0488URz0003ma+/rrB3/WLL74wv/jFL8zRRx9tQqGQycjIMCeddJJ54IEHTDQarXO8Df0++9ngbdR6u3fvNlOnTjVnnHGGyc7ONoFAwHTp0sWcf/75Zvbs2cZ1XSYAAAAAAIAJgOYxefLkpA3We+65p8HHPfTQQ0mPu+iii+rdEH7qqaeM1+tNWi7JtG/f3qxatarO1+revXudj/nuLRwOm5dffnm/4/3LX/5i/H7/fh9/xhlntOoEwNKlS01ubm69v9OwYcPM7t27mQAAAAAAACYAmq5fv35JG54rV65s8HEffPBB0uN69+5d74awx+Opd4O3Z8+eJhKJNLhBvb9bKBQyX331VdLjp0+f3ujnaI0JgLfeeqveyYjv3kaPHs0EAAAAAAAwAdB0eXl5SRud5eXlDT6uvLw86XGZmZn1bgg7jmN++9vfmh07dpjdu3ebadOmmbS0tKS9BOraoG7Xrp256aabzLJly0xpaamJRCJm1apVZsCAAQmP/+Uvf5nw2LKyMtO+ffuEdc466yyzatUqE4vFzJYtW8yUKVNabQKgoqIiqfkNN9xgNm3aZHbt2mXmz59v8vPzE36+ePFiJgAAAAAAgAmApqnrL9G1tbUNPq6mpibpcX6/v94N4auuuirpee66666Edc4777ykdcaNG2d27NhR5zjWrVuX8Pjvf/7CT9/8MEHk/ZSiMVijToUoiUmAB555JGEn02ePLnB8zJMmjSJCQAAAAAAYAKgadq1a5e0wbpr164GH7dr166kx+Xm5ta7Ifz5558nPc9nn32WsE5+fn69r1tbW2u++uors3jxYjNt2jRz2223JV2N4LuGDBmS8POnn366zufdtm1bq0wA7Dueuk5+WFpamrBOr169mAAAAAAAACYAmuaoo45K2mBds2ZNg4/7+OOPkx53/PHH73dD2Ofz1blnwb5n3w+FQknrxONxM336dHP22WebUCh0QMfu77u7/bp16/b7O2VmZrb4BEBdh1yoESc4TGU+Pl4AAAAA4NA74YQT9PXXXycsW7JkiU466aR6H/f2228nLTv99NP3u36HDh3k9XqTlu+7LB6PJ9yvrq7W+eefr0WLFh3U71deXp5wv1u3bvtdNy0trcV7l5WVHfBjIpFISv8b8/B/MwAAAAA49H70ox8lLXv88ccVi8X2+5iamhr99a9/TVo+ZMiQ/T6mqqqqzuUlJSUJ97OyshLu33fffUkb/z169NCoUaN07bXX6ve/718vv3/jXnfn+3cuXO/v1NpaWmTeza0x3soFDrs/o2xBwD253RJR5LhsBeT9BoZAAAAWt748eN16623as+ePXuXbdy4Uddee62mTZsmx3GSHjNlyhT9+9/TliWn5+vUaNG7fd1KioqtGPHDnXs2DFh+apVqxLuH3vssQn3Z86cmXD/z3/+s6677rqEiYXbb799v6+bl5enjRs37r2/du1adenSJWm9tWvXqra2tt5WwWAwYWKkqKhIeXl5Cets3ry53ufo1q2bPv300733v/zyS/Xq1Yt/iDgsvaiDuD4ntzZ3+5b/KwAAgNZmDmN33nlnnd/LhgwZYt566y2zZ88es2fPHrNs2TIzcuTIOtet6+R6+64zderUpHV+9KMfJazzm9/8pt6rFOzevTvh56+88kq9x9yPHz8+6RKAdRkxYkSDx/j36NEj4eczZ85MWufee++t93muv/76hJ9df/31bf7fF58uYAKAGxMAAACACQBLVFdXm0GDBh3097eJEyc26mR44XDYPPfccyYSiZitW7eaq6++OulEgZs2bUp4jpycnIR1brrpJrNjxw5TVlZmZs6caTp27FjvBvdrr72W9PMJEyaYL774wlRXV5t169aZiy++uMGTCRpjzNixYxN+npeXZ+bOnWt27txptm7dah588EGTlpZW7/OsW7fOeL3epH7Lli0zRUVFpqqqymzZssWsWLHC3HfffUmXNWQCAEwAcGMCAAAAgAmAJikpKTFnnHHGAX93u/DCC00kEmnUBEBDt9tuuy3pOSZMmFDvY9LT0+vd4HZdN+nSe4297WvhwoUNPsbn8zX4PHXtJXAg42ACAEwAcGMCAAAAgAmAJonFYmbKlCkmGAw2+J0tKyvL/OEPfzCu6zb6cninnXbafp9vwoQJdV4m8OuvvzadOnWq8zGBQMDMmzevwQ3mHTt2mNNPP73e3+c3v/lNoza8991rQftcwnDu3LmNep6pU6fWOVnABACYAODGBAAAAAATAK1m69at
```
**Minimal reproduction project:**
https://github.com/KhronosGroup/glTF-Sample-Models/archive/master.zip

**Comment by akien-mga** [comment] 2020-10-01 10:18
> Minimal reproduction project:
https://github.com/KhronosGroup/glTF-Sample-Models/archive/master.zip

Welp... Here's a **minimal** reproduction project which doesn't weigh 850 MB ;)
[glTF-import-bug.zip](https://github.com/godotengine/godot/files/5311164/glTF-import-bug.zip)

(Includes the two assets referenced in the OP.)

**Comment by akien-mga** [comment] 2020-10-02 10:49
For the reference, if you try to import https://github.com/KhronosGroup/glTF-Sample-Models after the fix, you'll now get a crash \o/ but it's unrelated to this glTF issue. There are actually some DAE files in the repo which trigger a crash in the Collada importer. I'll open an issue for that.

**Comment by akien-mga** [comment] 2020-10-02 10:55
I merged a bit too fast, after removing the Collada files there are still some glTF files which can fail. I'll make a follow up PR.

**Comment by akien-mga** [comment] 2020-10-02 12:36
Alright, #42504 fixes the base64-related issues.

There's issues more among the ~250 glTF files of that Khronos repo, notably:

- Some errors with the `bufferView` handling:

```
ERROR: Condition "buffer_end > bv.byte_length" is true. Returning: ERR_PARSE_ERROR
   at: _decode_buffer_view (editor/import/editor_scene_importer_gltf.cpp:597)
ERROR: Condition "buffer_end > bv.byte_length" is true. Returning: ERR_PARSE_ERROR
   at: _decode_buffer_view (editor/import/editor_scene_importer_gltf.cpp:597)
ERROR: Condition "buffer_end > bv.byte_length" is true. Returning: ERR_PARSE_ERROR
   at: _decode_buffer_view (editor/import/editor_scene_importer_gltf.cpp:597)
ERROR: Condition "array_len == 0" is true. Returning: ERR_INVALID_DATA
   at: mesh_create_surface_data_from_arrays (servers/rendering_server.cpp:803)
ERROR: Condition "err != OK" is true.
   at: add_surface_from_arrays (scene/resources/mesh.cpp:1118)
ERROR: Index p_idx = -1 is out of bounds (surfaces.size() = 0).
   at: surface_set_material (scene/resources/mesh.cpp:1214)
```

- A segfault in the `_parse_meshes` function:

```
ERROR: FATAL: Index p_index = 2 is out of bounds (((Vector<T> *)(this))->_cowdata.size() = 2).
   at: operator[] (./core/vector.h:50)
handle_crash: Program crashed with signal 4
Dumping the backtrace. Please include this when reporting the bug on https://github.com/godotengine/godot/issues
[1] /lib64/libc.so.6(+0x3a4e0) [0x7f871a68f4e0] (??:0)
[2] VectorWriteProxy<AABB>::operator[](int) (/home/akien/Projects/godot/godot.git/./core/vector.h:50 (discriminator 7))
[3] RasterizerStorageRD::mesh_add_surface(RID, RenderingServer::SurfaceData const&) (/home/akien/Projects/godot/godot.git/servers/rendering/rasterizer_rd/rasterizer_storage_rd.cpp:2348 (discriminator 2))
[4] RenderingServerRaster::mesh_add_surface(RID, RenderingServer::SurfaceData const&) (/home/akien/Projects/godot/godot.git/servers/rendering/rendering_server_raster.h:245)
[5] RenderingServerWrapMT::mesh_add_surface(RID, RenderingServer::SurfaceData const&) (/home/akien/Projects/godot/godot.git/servers/rendering/rendering_server_wrap_mt.h:152 (discriminator 2))
[6] ArrayMesh::add_surface(unsigned int, Mesh::PrimitiveType, Vector<unsigned char> const&, int, Vector<unsigned char> const&, int, AABB const&, Vector<Vector<unsigned char> > const&, Vector<AABB> const&, Vector<RenderingServer::SurfaceData::LOD> const&) (/home/akien/Projects/godot/godot.git/scene/resources/mesh.cpp:1107)
[7] ArrayMesh::add_surface_from_arrays(Mesh::PrimitiveType, Array const&, Array const&, Dictionary const&, unsigned int) (/home/akien/Projects/godot/godot.git/scene/resources/mesh.cpp:1128)
[8] EditorSceneImporterGLTF::_parse_meshes(EditorSceneImporterGLTF::GLTFState&) (/home/akien/Projects/godot/godot.git/editor/import/editor_scene_importer_gltf.cpp:1232 (discriminator 3))
[9] EditorSceneImporterGLTF::import_scene(String const&, unsigned int, int, List<String, DefaultAllocator>*, Error*) (/home/akien/Projects/godot/godot.git/editor/import/editor_scene_importer_gltf.cpp:3209)
[10] ResourceImporterScene::import(String const&, String const&, Map<StringName, Variant, Comparator<StringName>, DefaultAllocator> const&, List<String, DefaultAllocator>*, List<String, DefaultAllocator>*, Variant*) (/home/akien/Projects/godot/godot.git/editor/import/resource_importer_scene.cpp:1274)
[11] EditorFileSystem::_reimport_file(String const&) (/home/akien/Projects/godot/godot.git/editor/editor_file_system.cpp:1729)
[12] EditorFileSystem::reimport_files(Vector<String> const&) (/home/akien/Projects/godot/godot.git/editor/editor_file_system.cpp:1916 (discriminator 3))
[13] EditorFileSystem::_update_scan_actions() (/home/akien/Projects/godot/godot.git/editor/editor_file_system.cpp:561)
[14] EditorFileSystem::_notification(int) (/home/akien/Projects/godot/godot.git/editor/editor_file_system.cpp:1123)
[15] EditorFileSystem::_notificationv(int, bool) (/home/akien/Projects/godot/godot.git/editor/editor_file_system.h:106 (discriminator 14))
[16] Object::notification(int, bool) (/home/akien/Projects/godot/godot.git/core/object.cpp:808)
[17] SceneTree::_notify_group_pause(StringName const&, int) (/home/akien/Projects/godot/godot.git/scene/main/scene_tree.cpp:818)
[18] SceneTree::idle(float) (/home/akien/Projects/godot/godot.git/scene/main/scene_tree.cpp:447 (discriminator 2))
[19] Main::iteration() (/home/akien/Projects/godot/godot.git/main/main.cpp:2426)
[20] OS_LinuxBSD::run() (/home/akien/Projects/godot/godot.git/platform/linuxbsd/os_linuxbsd.cpp:240)
[21] godot-git(main+0x135) [0x1a9dd47] (/home/akien/Projects/godot/godot.git/platform/linuxbsd/godot_linuxbsd.cpp:60)
[22] /lib64/libc.so.6(__libc_start_main+0xea) [0x7f871a67bcda] (??:0)
[23] godot-git(_start+0x2a) [0x1a9db6a] (??:?)
```

I'll open separate issues for those (+ the Collada crash).

That's a crazily huge repo but it's a good testing resource for the glTF importer :)

**Comment by akien-mga** [comment] 2020-10-02 13:01
> That's a crazily huge repo but it's a good testing resource for the glTF importer :)

Note: This repo also contains glTF 1.0 scenes that we don't support, so they raise errors too and fail importing. I'll see if we can gracefully recognize such files and ignore them.

**Comment by akien-mga** [comment] 2020-10-05 12:02
> Some errors with the `bufferView` handling:

Welp, can't reproduce those today after reimporting everything from scratch.

> A segfault in the `_parse_meshes` function. It doesn't happen on the `3.2` branch, and I checked and it also happens before my changes in `master`, so it's not a regression from my fixes.

I opened #42569 for this.

**Closed** 2020-10-05 13:02 UTC
Labels: bug, confirmed, topic:core, topic:import
