### ISSUE TITLE
Vector3 don't store the right value

### ISSUE THREAD

**Issue by CristianoSimao** [godotengine/godot#61606] opened 2022-06-01 15:03 UTC
### Godot version

v3.4.3.stable.official -242c05d12-

### System information

Linux Fedora 35 - CPU AMD Ryzen 3 2200 G - GLES2

### Issue description

Try store a float number in a Vector3 and the result will be various imprecise numbers.
I discovered this after observating various collisions imprecisions in my game because I use movements of objects in a very small scale. Then I created a function to cut low number cases in float numbers. Exemple: if the number is 32.05687 after cut the value will be 32.05
The function work ok, but after storing the values in a Vector3 the numbers change.

### Steps to reproduce

The result change after various interation using random numbers with diferent sizes. But with a simple test you can see the problem.

Run this code:
```
extends Spatial

var px
var py
var pz
var vector

# Called when the node enters the scene tree for the first time.
func _ready():
	pass # Replace with function body.


# Called every frame. 'delta' is the elapsed time since the previous frame.
func _process(delta):
	
	px = 2.32
	py = 3.58
	pz = 42.85
	
	vector = Vector3(px,py,pz)
	print("Px:" + str(px) + " Py:" + str(py) + " Pz:" + str(pz))
	print("Vector:"+ str(vector))
```

In my computer vector show the wrong value in "Pz" :  42.849998

### Minimal reproduction project

[testvector.zip](https://github.com/godotengine/godot/files/8815355/testvector.zip)

**Comment by Zireael07** [comment] 2022-06-01 15:10
Vector3 stores floating point numbers. The imprecision is their key feature.

If you need to compare floats, use is_equal_approx()

**Comment by clayjohn** [comment] 2022-06-01 15:34
Duplicate of https://github.com/godotengine/godot/issues/43476

A very helpful resource when reasoning about why floating point numbers lose precision is the [floating point guide](https://floating-point-gui.de/). 

As a note, this issue is an inherent limitation when using 32 bit floating point numbers. Using 64 bit floating bit numbers will give you so much precision that this is no longer a problem (which you can do if you compile Godot with 64 bit precision enabled)

**Closed by clayjohn** 2022-06-01 15:34 UTC
Labels: archived, topic:core
