### ISSUE TITLE
Editor doesn't update when changing a StyleBox's color 

### ISSUE THREAD

**Issue by Windfisch** [godotengine/godot#23569] opened 2018-11-07 13:32 UTC
**Godot version:** 955a913a1fcc7551a3e03017eb2ac8edc4ee7043

**OS/device including version:** Linux/X11

**Issue description:**
When changing a Label's associated StyleBox's background color, then the editor does not update immediately. Instead, you need to resize/move/change the Label in some other way for the change to become visible.

**Steps to reproduce:**
1. Create new scene, choose "2D scene"
2. Add a Label, give it some text
3. in the Label's settings under "Custom Styles", assign a "normal" style using a new `StyleBoxFlat`.
4. The Label's background color will visibly change to a lighter gray
5. In the StyleBoxFlat's settings, change its background color to red
6. The "preview" field in the inspector will update immediately. The Label in the editor will not.
7. Move/Resize the label by some pixels
8. The label will update its background color to red.

**Comment by pawilon** [comment] 2018-11-16 14:30
I think this might be the same bug as in https://github.com/godotengine/godot/issues/22895

**Comment by Windfisch** [comment] 2018-11-16 17:19
Yes, the attached GIF in #22895 looks identical to what I've experienced, just with a Button instead of a label.

**Comment by akien-mga** [comment] 2018-11-16 17:21
Closing as duplicate of #22895 then.

**Closed by akien-mga** 2018-11-16 17:21 UTC
Labels: bug, topic:editor
