### ISSUE TITLE
Tool script doesn't call _ready or _enter_tree on reload

### ISSUE THREAD

**Issue by Eymux** [godotengine/godot#16974] opened 2018-02-24 11:21 UTC
**Godot version:**
3.0 stable
3.0.1 Build 689dfcd

**OS/device including version:**
Windows 7 Home

**Issue description:**
I have written a tool script, that draws connections between nodes. For that I have an onready variable, that loads the nodes. In the _draw function I get the position of the nodes and draw lines between them.
The lines are only drawn once after I reload the editor. When I change the script, nothing is drawn.
The problem is, that the onready variable is undefined after reloading the script. _ready and _enter_tree aren't called either. I have tried notifications, too. But no notifications for ready or enter_tree are received.

**Steps to reproduce:**
* create a new scene
* add two Node2D
* add a tool script to one node

```
tool
extends Node2D

var node

func _ready():
	node = get_node("../Node2D2")
	
func _process(delta):
	update()
	
func _draw():
	draw_circle(node.position, 30, Color(1, 0, 0))
```

* when you reload the editor, the circle is drawn
* change the radius of the circle and save the script
* the circle is not redrawn

**Minimal reproduction project:**
[Test2.zip](https://github.com/godotengine/godot/files/1754312/Test2.zip)

**Comment by RabbitB** [comment] 2018-02-24 12:07
Tool scripts are _'isolated'_ so to speak. While running within the editor, they cannot reference or access any other nodes in the scene, as those nodes don't really exist yet. Same goes for singletons--they aren't yet instantiated inside the editor, so they don't exist until you run the game.

**Comment by Eymux** [comment] 2018-02-24 12:55
The script is able to reference the the other nodes for the first time. And it can reference other nodes in the _process function.
So I don't think that's correct.

**Comment by Ranoller** [comment] 2018-02-24 13:23
This is the behavior of an editor plugin. I don't like too. Every time a script is changed you have to reload entire editor to make plugin works. Make plugins is this way is a bit annoying, but there is for now other system. It will be fine to have option to reload editor without close and open (or automatic reload on editorplugin script change, but this is more difficult)

**Comment by Zylann** [comment] 2018-02-25 15:01
I had this problem too with tool scripts. The problem is, script reloading RESETS variables. If it didnt do that, the script could be able to still function normally, provided that your changes are not too big. Recalling ready() would mean reloading the scene anyways (which you need to do manually at the moment, no need to restart the entire editor)

**Comment by Eymux** [comment] 2018-02-25 15:07
How about simulating removing and readding the node?

**Comment by Zylann** [comment] 2018-02-25 15:18
When I was doing my terrain plugin, that would mean freezing Godot for 3 seconds everytime I hit Ctrl+S xD

**Comment by Eymux** [comment] 2018-02-25 15:24
3 seconds is faster, than restarting the whole editor and restoring everything I had opened. I could live with that.

**Comment by Zylann** [comment] 2018-02-25 15:37
And 0 seconds are faster if my node didn't get readded^^ (i.e if variables didnt get reset). Note that this could also be non-viable for ingame reloading.

**Comment by Eymux** [comment] 2018-02-25 15:42
But if I don't reload or readd, then my changes aren't applied. Which brings us to the start of the problem.
I'm writing code in iterations. I'll write something, then I test it immediately. When I write an editor tool, I want to see my changes, when I save the script.

**Comment by Zylann** [comment] 2018-02-25 16:12
There are multiple solutions to reloading, some more suited than others, but there is no ultimate solution. There will always be a best case where only function reloading is needed, and there will always be a worst case where restarting the editor or the game is needed.

**Comment by Zylann** [comment] 2018-02-25 16:14
I mean, I can't think of a way that contents everyone, unless having choice of how reloading is performed (which also means Ctrl+S can't really default to a single reloading method)

**Comment by Eymux** [comment] 2018-02-25 16:17
Currently the **only** way is to restart the whole editor. And I don't think, that's necessary, when just reloading a script. Honestly I don't see where the problem is.

**Comment by Eymux** [comment] 2018-02-25 16:27
Avoiding side effects in my own code is my business. I don't believe Godot needs to worry about that.
One way is to use Engine.editor_hint.

**Comment by Zylann** [comment] 2018-02-25 16:30
That hint can't tell you `_ready()` was called because of instancing the node in editor or the script being reloaded.

**Comment by Eymux** [comment] 2018-02-25 16:34
And? I still don't see our problem. I'm not trying to be obtuse. I just don't understand, why Godot has to bother with side effects in my code.
Do you have an example, where this would matter?

**Comment by volzhs** [comment] 2018-02-25 16:43
probably #6005?

**Comment by Zylann** [comment] 2018-02-25 16:44
The problem I see is that `_ready` and `_enter_tree` would loose their semantic. Who knows what people put in these functions, but it's to deal with when these events actually happen. Having them happen exceptionally on script reloading breaks that semantic, which might come unexpected, hence the possible side-effects, and why reloading the scene would not have these side-effects (for everyone, not just you). Also, what about the `_init()` constructor function? Same story here, would it be called again?

Another example of the problem I had with my plugin:
https://github.com/Zylann/godot_terrain_plugin/blob/master/addons/zylann.terrain/terrain.gd#L54
The nodes created by the terrain would be created a second time, over the existing ones which my script forgets about because of getting reset by reloading. Having `_ready()` called again wouldn't solve anything.

**Comment by Eymux** [comment] 2018-02-25 16:51
It shouldn't be the job of Godot to worry about the users code. If a programmer is writing bad code, it's his/her own fault.
And in a tool script, I want the reload to reset everything to default and call _enter_tree and _ready. There is no second time here.

**Comment by Zylann** [comment] 2018-02-25 16:56
@Eymux if you want this to happen, there is a need for the script to cleanup its state. Calling `_ready` again because of reloading would become ambiguous, and here is why:
You might think you can test if your objects exist before `_ready` to be called and clean them up if `editor_hint`. But that would make your node do that too when you reparent it, because that's also what the definition of `_enter_tree` and `_ready` are... and you don't necessarily want that to happen.
But tbh even that is impossible currently because as I said, the script gets reset quite blindly, leaking every object it might have created during its lifetime...

**Comment by Eymux** [comment] 2018-02-25 17:04
I believe, we're getting into a different discussion here. My tool doesn't need to know, when it is reset. It doesn't instantiate anything. I just want to draw something to the screen.
Maybe Godot script needs a destructor.

I can't wait for full C# support.

**Comment by Zylann** [comment] 2018-02-25 17:10
Why C#?

**Comment by Eymux** [comment] 2018-02-25 17:12
Because it's a decent language with a garbage collector.

**Comment by volzhs** [comment] 2018-02-25 17:20
> I just want to draw something to the screen.

is that all you want?

```gdscript
tool
extends Node2D

export var radius = 30
var node

func _ready():
	node = get_node("../Node2D2")
	
func _process(delta):
	update()
	
func _draw():
	draw_circle(node.position, radius, Color(1, 0, 0))
```

this will solve your problem then.
you don't need to reload or something.
just change the radius value in the inpector panel.

**Comment by Eymux** [comment] 2018-02-25 17:25
This is just the minimal example, I've created for the issue.
My script is more complicated than that.

**Comment by TheBoJaN** [comment] 2018-04-14 21:42
@volzhs That example points out the exact issue here, if you wanted to change it to draw a polygon you would change the code, Ctrl+S and node would be lost causing errors until you reload the scene.

I see no issues with the proposal of calling _ready() on script reload, if it causes side-effects it should be my job to deal with them by not blindly adding new nodes without checking to make sure they don't already exist. If I save a script, it should behave exactly as it would if I just attached it to a node, not in a way that is unique to the action of saving.

**Comment by willnationsdev** [comment] 2018-06-15 22:47
@Zylann 
> All of these have pros and cons. I can think of breaking cases for every one of them.

If that's the case, why not make them all available and make it configurable in the EditorSettings? That way users can change it whenever their use-case is appropriate?

**Comment by Zylann** [comment] 2018-06-15 23:35
@willnationsdev it's not possible because that would affect all plugins you have in your project, which may have been developped with the option or without it... would be a mess.

**Comment by willnationsdev** [comment] 2018-06-20 17:39
What if we created a specific method for the use-case of "re-initializing a tool script after it has been saved"? You could define a `_tool_reload()` method and then just have that method and the `_ready()` method both execute a separate initialization method. That way the same logic gets executed in-game when the script is included, in-editor when you set it up as a dock/panel/etc. as the editor opens, and when you save the script within the editor. Could even implement custom logic for each specific case (since the `_ready()` could use the `is_editor_hint()` to differentiate between the first two cases).

**Comment by Zylann** [comment] 2018-06-20 18:00
@willnationsdev as far as hot-reload of scripts is concerned, I don't see why such a callback would be tool only, though.

**Comment by neikeq** [comment] 2018-10-24 19:43
Scripts should two callbacks: `about_to_reload` and `reloaded` (Just an example, I don't like these names). In Unity you have `OnEnable` and `OnDisable` which are called on reload (they are also called in other situations that would not apply to Godot).

**Comment by Takanu** [comment] 2019-05-13 18:26
I'm so happy I found the issue where people were talking about this, it has driven me **_insane_** today figuring out why the state of my custom node suddenly drops on script reloads and it makes testing pretty tedious.

I currently don't have a preference so long as I can deal with the dropped properties once the script has been reloaded, having separate functions be called when this occurs seems to make the most sense with the least potential collisions.

**Comment by Favorlock** [comment] 2019-10-03 17:48
It would be great if they could fix this soon. As has been mentioned, resetting variables to default state on hot reload isn't very effective. I've been working on a plugin the last few days and this issue has been a plague. Often this will lead to orphaned nodes, which is bad.

**Comment by BenjaminNavarro** [comment] 2020-02-02 08:26
I'm also quite bothered with this reloading issue. My solution for now is to not rely on `onready` or `_ready` to be called but to use getter functions to give me the references to the nodes I need.

**Comment by Shadowblitz16** [comment] 2020-04-29 03:23
please fix this its a pain in the butt and I would consider it a bug.
literally reloading the script in the editor is the same as closing and reopening it.
it should be treated as so.

**Comment by tliron** [comment] 2020-07-21 13:57
This is a painful issue! I spent a day trying to understand what was going on. The problem is not only that `_ready` would not be called again (and this includes `onready` variable initializations), but also that `setget` setters for exported properties *would* be called again. 

(Moreover, the editor will always call the setters *before* `_ready` if the property was given a non-default custom value. This, at least, makes sense, because you would likely want `_ready` to take the "real" values into account. But of course if `_ready` isn't called at all, you are stuck in an in-between state.)

Example:
```
tool
extends Node

export(int) var selection = 0 setget set_selection
onready var children = get_children()

func set_selection(v):
  # "children" will sometimes be null!
  print(children)
  selection = v
```
There were a few suggestions here on how to solve this problem. I'll add my two cents: it would be nice if there was a `_reload` built-in callback function exactly for handling these situations. The logic for reloading is simply different from the logic for adding to the tree (readying). It wouldn't be trivial, but at least it would be *clear* where you should put code to handle this situation.

Furthermore, I don't think such a callback should be reserved just for tool scripts! After all, any runtime node in the game could be reloaded dynamically, too.

**Comment by cgbeutler** [comment] 2020-11-25 00:10
> That's why I think there are in fact multiple hot-reload ways:
> 
> * Soft-reload, which reloads functions only and has zero cost as far as the script is concerned. It keeps the current state of the script which is good because we get minimal amount of state loss, getting closer to true hot-reloading ;
> * The current reload, which also resets members for some reason, which defeats hot-reloading in several cases. Maybe it could do better by saving previous vars and re-assigning them beforehands unless their default value changed? (which is what Unity assembly-reload does AFAIK) ;
> * Hard-reload, which reloads the scene (or the node where the script is), which users end up doing by restarting the editor (which is overkill because you could just reopen your scene) ;
> * Your proposal for recalling life-cycle functions is yet another in-between

If I could add my two cents...
I think it would be nice if game-scripts and tool-scripts worked in similar ways. In other words, it would be nice to add buttons to reload a scene/plugin when working on tool scripts.

Currently, when editing a game script, it can soft-reload while the scene is running, but you can click the replay button to do a hard-reload of the scene. So if I am editing a game script and get in a bad state, I can click one button to clear that bad state and get a fresh reload.

If I am editing my tool script and accidentally introduce an error that puts me in a bad stat, then there is no "reset all" button. Copying over the state completely would perpetuate the bad state into subsequent hot-reloads. I would need a reload button somewhere, similar to what the game has.

What would this look like? I don't know for sure, but it seems like a simple start would be something like this?
![image](https://user-images.githubusercontent.com/9751923/100164799-dedcdd80-2e75-11eb-86af-a4a12418b731.png)
A little scene reload that shows up if a tool script exists in the scene?

If you edit a tool script used in a plugin, maybe a button shows up to reload the plugin? (There are already several assetlib projects for a quick reload of plugins.)

Something like this would make tools behave closer to games.

I could also see it maybe being a button in the editor window itself or in the context menu for a script. A button there could kick off a reload of whatever scenes/plugins use the script:
![image](https://user-images.githubusercontent.com/9751923/100165429-77c02880-2e77-11eb-84da-82db29ba992c.png)


Anyway, food for thought

**Comment by cgbeutler** [comment] 2020-11-25 00:17
All that said, if no button is added, I would think that hard-reload should be the default, because if you are editing a script, chances are you will be in a bad state until your last edit... you know, cuz you're fixing it.

**Comment by me2beats** [comment] 2020-12-01 02:20
Faced this behavior too.
how bad such a work-round would be:
```gdscript
func _init():
	#... here some _init code, and then

	if is_inside_tree():
		_enter_tree()
		_ready()
```
for editor-only tools I think this should be ok.

**Comment by cgbeutler** [comment] 2020-12-01 09:27
@me2beats that would not call all the `onready` variable initialization. There's a lot more that happens in the ready process than just `_ready`

**Comment by WinterSnake** [comment] 2021-07-13 07:15
Still facing this issue while trying to get a child node.
```gdscript
tool
class_name OrbitalCamera extends Spatial

onready var camera: Camera = self.get_node("camera")


func _get(property):
	if property == "Camera/Offset":
		return self.camera.transform.origin

func _set(property, value):
	if property == "Camera/Offset":
		self.camera.transform.origin = value

func _get_property_list():
	var properties = []
	properties.append({
		name = "Camera/Offset",
		type = TYPE_VECTOR3,
		usage = PROPERTY_USAGE_EDITOR
	})
	return properties
```
When saving the scene I get the error: ` Invalid get index 'transform' (on base: 'Nil')`
I'm unsure why saving reloads the scene without calling `_ready` but switching scenes in the tabs seems to keep the reference/not reload. I had to manually reload the scene in order to get the reference to the child node back.
In the mean time, however - this seems to work to keep the child node even when saving:
```gdscript

func _process(delta):
	if Engine.editor_hint:
		# -Reparent Child Node
		if self.camera == null:
			self.camera = self.get_node("camera")```

**Comment by Zylann** [comment] 2021-07-13 09:24
I think your code does not have the same problem as this issue states. Instead, your code has a design issue, which will also happen when you close and reopen the scene: it tries to access a child node inside a setter of an exported variable. However setters are called when objects of a scene are *created*, even before its children are. And that happens before it is added to the tree. `_ready` is called *after* it is added to the tree. Usually to implement this you should check if the node is inside the tree, and assign variables or child nodes in `_ready` in addition to the setters.

**Comment by WinterSnake** [comment] 2021-07-13 09:28
> I think your code does not have the same problem as this issue states. Instead, your code has a design issue, which will also happen when you close and reopen the scene: it tries to access a child node inside a setter of an exported variable. However setters are called when objects of a scene are _created_, even before its children are. And that happens before it is added to the tree. `_ready` is called _after_ it is added to the tree. Usually to implement this you should check if the node is inside the tree, and assign variables or child nodes in `_ready` in addition to the setters.

Except it doesn't. The code works perfectly fine on closing/re-opening the scene as well as the first time the scene is loaded. It's only when the scene is saved does the reference to the child node go to nil. This is with the latter of the part of code commented out, of course. It seems like saving the file refreshes the scene without calling the necessary `_enter_tree` and `_ready` functions.

**Comment by Zylann** [comment] 2021-07-13 09:35
I edited my answer, it's possible that your problem also highlight other issues.

**Comment by WinterSnake** [comment] 2021-07-13 09:46
I stand corrected, actually.
I suppose I forgot to OR them in this instance in testing (did so for other variables thought I tried it for this one but I guess not), but that seems to be working as intended now without the latter part of the code in `_process`.

**Comment by Zylann** [comment] 2021-07-13 10:06
> I suppose I forgot to OR them in this instance in testing

I thought your code was actually correct though, with just the editor hint. Because Godot will save the transform of the camera anyways, there is no reason to also save the variable your script exposes, because it has the same source, and your goal was only to have a shortcut in the editor. Hence why I was surprised Godot even calls your property on load because the editor hint is supposed to get called only when using the inspector (so way after the scene is loaded). There should not have been any error anytime with the script you posted, unless *the script* gets reloaded (like, as if you had modified it while it runs).

> properties don't update dynamically

That's something Godot 4 aims to fix by polling I believe

**Comment by WinterSnake** [comment] 2021-07-13 10:15
> Because Godot will save the transform of the camera anyways, there is no reason to also save the variable your script exposes, because it has the same source, and your goal was only to have a shortcut in the editor.
> There should not have been any error anytime with the script you posted, unless the script gets reloaded (like, as if you had modified it while it runs).

Well, maybe a future thing to resolve otherwise, but I'll keep it here under this issue rather than creating a new one since I think it somewhat applies to the same concept.

> That's something Godot 4 aims to fix by polling I believe
I built the master branch, but had other issues unrelated that I'm still trying to figure out through source before I submit an issue. But I have seen some nice things in the master thus far, and if this is one of them, that's amazing.

**Comment by superhawk610** [comment] 2021-08-28 02:01
As @tliron noted, `_ready()` and `_enter_tree()` aren't called when reloading a tool, but `setget` setters for `exports` _are_ run. Using this, I was able to add a functional `_reload()` callback like so:

```godot
extends Node2D
tool

export(bool) var _reload = false setget _reload

func _reload(x):
    # perform reload logic here
```

This definitely feels hacky, and will add a `Reload` checkbox to the scene editor for your tool, but otherwise seems to work alright.

**Comment by KoBeWi** [comment] 2022-09-17 15:46
I didn't read the whole discussion, but the "issue" mentioned in title is intended behavior. `_ready()` or `_enter_tree()` are only called when node enters tree. So if you have a tool script and want to call these methods again, just reload the scene (or switch scene tabs in case of `_enter_tree()`. For editor plugins you can disable and enable the plugin. There is no need to restart the editor in any case.

Also in 4.0 the variables are no longer cleared on script update (#55134).

If there is anything left here, it should go to a proposal.

**Closed by KoBeWi** 2022-09-17 15:46 UTC
Labels: enhancement, topic:editor, confirmed, topic:plugin
