### ISSUE TITLE
AnimatedSprite with normal_map only works in the editor not when executed

### ISSUE THREAD

**Issue by aykut4** [godotengine/godot#48968] opened 2021-05-22 13:33 UTC
When an AnimatedSprite has two SpriteFrames and one of them has the suffix "_normal" to be able to make use of the normal map it only works in the editor.

When the project is ran the normal_map effect disappears.
![Editor](https://user-images.githubusercontent.com/26779522/119228373-06ee8600-bb13-11eb-9fda-fda29403fd65.PNG)
![Running](https://user-images.githubusercontent.com/26779522/119228377-0b1aa380-bb13-11eb-9564-3a736c4e9a8e.PNG)

**Comment by madmiraal** [comment] 2021-05-24 12:26
@aykut4, please complete the entire issue template; don't delete it. It's there for a reason:
```
<!-- Please search existing issues for potential duplicates before filing yours:
https://github.com/godotengine/godot/issues?q=is%3Aissue
-->

**Godot version:**
<!-- Specify commit hash if using non-official build. -->


**OS/device including version:**
<!-- Specify GPU model, drivers, and the backend (GLES2, GLES3, Vulkan) if graphics-related. -->


**Issue description:**
<!-- What happened, and what was expected. -->


**Steps to reproduce:**


**Minimal reproduction project:**
<!-- A small Godot project which reproduces the issue. Drag and drop a zip archive to upload it. -->
```

**Comment by Calinou** [comment] 2021-05-24 15:29
Duplicate of https://github.com/godotengine/godot/issues/43435.

**Closed by Calinou** 2021-05-24 15:29 UTC
