### ISSUE TITLE
A strange shadow forms

### ISSUE THREAD

**Issue by DimaKiva** [godotengine/godot#7051] opened 2016-11-06 09:29 UTC
**Operating system or device - Godot version:**
Godot 2.1

**Steps to reproduce:**
Add a light above the cube, activate the shadow.

**Link to minimal example project** (optional but very welcome):
![2016-11-06 09-47-45](https://cloud.githubusercontent.com/assets/11325733/20036243/1001ad3a-a43e-11e6-922c-c76605677442.png)

**Comment by bojidar-bg** [comment] 2016-11-06 10:06
Would be likely fixed with the new gles-3 shadowmapper and renderer

**Comment by algorev** [comment] 2017-03-16 07:11
Is caused by dual paraboloid shadow mapping.

**Comment by volzhs** [comment] 2017-03-16 07:30
"GODOT'S NEW RENDERER, PROGRESS REPORT 2" mentioned about it.

https://godotengine.org/article/godots-new-renderer-progress-report-2

**Comment by Calinou** [comment] 2017-03-16 09:00
Cubemap shadow mapping is available in the new renderer (which will be in Godot 3.0), but it isn't the default option right now.

**Closed** 2017-07-17 22:15 UTC
Labels: bug, topic:rendering
