### ISSUE TITLE
Beta 2.0 fails to run on Fedora (libssl.so.1.0.0 error)

### ISSUE THREAD

**Issue by techtonik** [godotengine/godot#3557] opened 2016-02-02 17:58 UTC
```
$ ./Godot_v2.0_beta_20160126_x11.64 
./Godot_v2.0_beta_20160126_x11.64: error while loading shared libraries: libssl.so.1.0.0: cannot open shared object file: No such file or directory
```
Can it be fixed without making Fedora specific build?

**Comment by akien-mga** [comment] 2016-02-02 18:09
Duplicate of #1391, the other issue was not that hard to spot with a small search before filing an issue...

**Closed by akien-mga** 2016-02-02 18:09 UTC

**Comment by techtonik** [comment] 2016-02-02 19:15
@akien-mga yea, sorry - GitHub doesn't propose similar tickets like other trackers do. I actually found some Linux bugs, but didn't think there was something so specific for Fedora.
