### ISSUE TITLE
Pathfinder and 2D isometric tilemaps dont find path between side cells

### ISSUE THREAD

**Issue by schweigert** [godotengine/godot#43079] opened 2020-10-25 17:45 UTC
**Godot version:** 3.2.2.stable

**OS/device including version:** Manjaro / Nvidia Rtx 3090 / Core I9 / 64GB

**Issue description:**

I am configuring the Navigation2D node in my project, which is using a TileMap node configured for isometric visualization. When debugging, I realized that it only generates its way on the tile where it is already positioned, never to other places.

I've tried to increase the size of the navigation borders in the tilemaps editor, but it just doesn't work.
I tried to make the mesh match perfectly, and it didn't work.

**Steps to reproduce:**

Create a Navigation2D node and add a TileMap as a child.
Configure the tilemap through the TileMap editor.
Debug with a Line2D the path generated by Navigation2D

![Peek 25-10-2020 14-25](https://user-images.githubusercontent.com/13274722/97114606-487b9780-16d0-11eb-8732-1eb76e8f9f03.gif)

![image](https://user-images.githubusercontent.com/13274722/97114630-69dc8380-16d0-11eb-9ede-f73f435b0546.png)

![image](https://user-images.githubusercontent.com/13274722/97114601-44e81080-16d0-11eb-97ad-e67609f484b4.png)

```gdscript
extends Line2D

onready var nav : Navigation2D = get_parent() as Navigation2D
onready var player : Node2D = get_parent().get_node("Player") as Node2D
func _ready():
	InputBehavior.connect("clicked", self, "_input_clicked")

func _input_clicked(position : Vector2) -> void:
	points = nav.get_simple_path(nav.get_closest_point(player.get_global_transform().get_origin()), nav.get_closest_point(position))

```

```gdscript
extends Camera2D


func _input(event):
	if event is InputEventMouseButton and not event.pressed:
		InputBehavior.clicked(get_global_mouse_position())
```

**Comment by erictuvesson** [comment] 2020-10-27 22:09
@schweigert Do you have any custom properties on the tiles?

It seems like you have the navigation debug on in the screenshot, hard to see when it's so green.

I tested navigation with a isometric tilemap and I had no issues.

**Comment by schweigert** [comment] 2020-10-28 11:29
No, I didn't add any attributes to the tile @erictuvesson .

![image](https://user-images.githubusercontent.com/13274722/97430230-565f3180-18f7-11eb-99f0-56709562c34c.png)

I found it strange because in other examples I saw, navigation appears united in debugging. In my case, it displays several separate blocks, and I cannot understand why it is not merging the navigations.

**Comment by erictuvesson** [comment] 2020-10-28 11:45
Can you share the project? I am not sure how you are making the tiles offset as there are multiple ways.

**Comment by schweigert** [comment] 2020-10-28 12:15
Unfortunately not because it is a commercial project.

I managed to make it work, but it really needs to be pixel perfect between the tiles' polygons, which when we have several tiles in separate sprites is difficult to test.


![Peek 28-10-2020 09-04](https://user-images.githubusercontent.com/13274722/97434393-b527a980-18fd-11eb-9eee-70bed2c48fea.gif)

I found it strange that if two mesh polygons are overlapping, it does not mix both to create a unique navmesh. Perhaps it is a possible improvement in this system. What do you think?

**Comment by Zireael07** [comment] 2020-10-28 12:30
If it's an issue of polygons having to be pixel perfect, it's an already reported issue that applies to both 2D and 3D navmesh/navpoly.

Yes, merging overlapping polys would be an obvious improvement, but no one did it in at least a year that passed since I last saw the issue reported.

**Comment by Zireael07** [comment] 2020-10-28 12:41
I found the issues: https://github.com/godotengine/godot/issues/12275, https://github.com/godotengine/godot/issues/17118 and a duplicate was closed as fixed with the 4.0 navigation server feature (but it's still an issue in 3.x)

**Comment by CyberFoxar** [comment] 2020-12-30 00:23
I had the same issue with hexagonal tiles. Overlapping the meshes does _not_ work on 3.x .

**Comment by Calinou** [comment] 2020-12-30 00:26
@CyberFoxar Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

**Comment by CyberFoxar** [comment] 2020-12-30 16:42
Sure, here's the simplest example I have. Recommended to tick debug>"View Navigation" to see overlapping tiles.
The line shows the plotted path (or lack thereof). You can see that the path can be plotted from one tile to the next (x axis) because there's no overlap between polygons. However, when trying to got down (y axis) `get_simple_path` just does not work.

[MinimalBroken.zip](https://github.com/godotengine/godot/files/5754938/MinimalBroken.zip)

**Closed** 2021-01-05 22:22 UTC
Labels: topic:navigation

**Comment by Calinou** [comment] 2021-01-05 22:28
@schweigert Did you find a solution to this issue?

**Comment by CyberFoxar** [comment] 2021-01-05 22:49
Either that, or I'll repost mine on its own issue.
