### ISSUE TITLE
(Engine Dev, C++) Using PROPERTY_HINT_RANGE with a step of 1.0 hides slider

### ISSUE THREAD

**Issue by M-O-Marmalade** [godotengine/godot#69279] opened 2022-11-28 03:35 UTC
### Godot version

tested on 3.x and master branches

### System information

Windows 11, I9-12900H, RTX 3070Ti Laptop GPU

### Issue description

When adding a new property to the editor while working on engine code, you can use `PROPERTY_HINT_RANGE` to specify a `"min"`, `"max'`, and `"step"` value. When `"step"` is set to anything other than 1.0, the slider is shown under the property. When `"step"` is set to 1.0, the slider disappears. I would like to set the step to 1.0, but still have the slider show up. The option to hide the slider using `"hide_slider"` now exists, so the slider should be shown by default when `"step"` is set to 1.0.

### Steps to reproduce

`ADD_PROPERTY(PropertyInfo(Variant::FLOAT, "keep_hf_hz", PROPERTY_HINT_RANGE, "1,20500,1,suffix:Hz"), "set_keep_hf_hz", "get_keep_hf_hz");`

This will not show any slider, even though `"hide_slider"` was not used. For big ranges like audio Hz values, it can take a lot of mouse dragging to smoothly transition from one value to another. Being able to smoothly change a value is important when auditioning/designing audio. The Shift key can be used to increase precision when dragging, but the Control key only snaps to integers, so in this case, it doesn't speed up the dragging (I may have to open up a separate issue on this as well).

### Minimal reproduction project

The Distortion AudioEffect has a `Keep Hf Hz` property which is a good example of this issue. There are plenty other examples as well.

**Comment by Calinou** [comment] 2022-12-01 22:22
Duplicate of https://github.com/godotengine/godot/issues/42809.

**Closed by Calinou** 2022-12-01 22:22 UTC
