### ISSUE TITLE
Input.set_custom_mouse_cursor glitch with big (e.g. 64x64) cursors when using hotspot

### ISSUE THREAD

**Issue by Jeto143** [godotengine/godot#28743] opened 2019-05-07 19:42 UTC
**Godot version:**

3.1

**OS/device including version:**

Windows 10 (up-to-date)

**Issue description:**

When switching to another cursor using a hotspot vector, a split-second visual glitch will appear when the destination cursor is more than 32x32 (though it starts being visible mostly from 40x40 upward).

In other words, the target cursor will appear at the wrong position (hotspot of `(0, 0)`) for like one frame before appearing at the requested one.

This doesn't seem to be happening when the cursor is 32x32 or less. I'm aware the 32x32 dimensions was a restriction in previous versions, but I don't think there should be any issues on 3.1, unless I missed something?

I also am aware this might not happen on every setup, since this is somewhat of a hardware thing behind the scenes (again, if I understood correctly).

**Video demo:**

https://streamable.com/3a0yu (sorry for poor quality, had to take it with phone, see comment below)

**Minimal reproduction project:**

[cursorbug.zip](https://github.com/godotengine/godot/files/3154233/cursorbug.zip)

Corresponding code (both cursors being 64x64, alt one has its hotspot centered):

```gdscript
extends Node2D

const DEFAULT_CURSOR = preload('res://default_cursor.png')
const ALT_CURSOR = preload('res://alt_cursor.png')

func _process(delta: float):
	if Input.is_mouse_button_pressed(BUTTON_LEFT):
		Input.set_custom_mouse_cursor(ALT_CURSOR, Input.CURSOR_ARROW, Vector2(32, 32))
	else:
		Input.set_custom_mouse_cursor(DEFAULT_CURSOR)
```

(Simply run project and click anywhere to switch cursor, release to switch back.)

**Comment by akien-mga** [comment] 2019-05-07 22:29
CC @guilhermefelipecgs

**Comment by guilhermefelipecgs** [comment] 2019-05-08 00:55
@Jeto143 What's your GPU and driver version?

**Comment by Jeto143** [comment] 2019-05-08 01:13
@guilhermefelipecgs Intel(R) HD Graphics 620 v. 25.20.100.6576 (07/02/2019, up to date)

So, just a somewhat basic laptop's integrated graphic chipset. Note that I can play most indie / 2D games without any issues on it (and where I can't it's usually because the FPS drops too much / game requires more graphic power). I haven't encountered any "glitch" of the sorts as far as I can remember.

**Comment by Jeto143** [comment] 2019-05-08 01:36
Here's a video of it. I had to take it with my phone because taking it directly from my computer was not showcasing the bug (it must have been skipping frames so it was actually like nothing was wrong).

Sorry for the horrible quality, I zoomed quite a bit:
https://streamable.com/3a0yu

**Comment by qarmin** [comment] 2019-05-08 10:20
I can reproduce this on Ubuntu 19.04 Nvidia 970 430

**Comment by guilhermefelipecgs** [comment] 2019-05-08 17:15
@qarmin I also managed to reproduce the error on archlinux with same gpu. Unfortunately I can't reproduce on Windows.

@Jeto143  Try this code below on Windows and see if flickering decreases:
```gdscript
extends Node2D

const DEFAULT_CURSOR = preload('res://default_cursor.png')
const ALT_CURSOR = preload('res://alt_cursor.png')


func _input(event):
	if not event is InputEventMouseButton:
		return

	if Input.is_mouse_button_pressed(BUTTON_LEFT):
		Input.set_custom_mouse_cursor(ALT_CURSOR, Input.CURSOR_ARROW, Vector2(64, 64))
		Input.set_custom_mouse_cursor(ALT_CURSOR, Input.CURSOR_ARROW, Vector2(64, 64))
	else:
		Input.set_custom_mouse_cursor(DEFAULT_CURSOR)
		Input.set_custom_mouse_cursor(DEFAULT_CURSOR)
```

**Comment by Jeto143** [comment] 2019-05-08 18:29
@guilhermefelipecgs Your second solution actually removes the glitch completely, but instead produces another unwanted behavior: when releasing the mouse, the default cursor doesn't appear again unless I move. In other words, if I click and release without moving the mouse at all, there will be no cursor visible on the screen until I move the mouse again.

If I change your `else` part to this, that fixes that part too and everything looks good:

```
else:
		Input.set_mouse_mode(Input.MOUSE_MODE_HIDDEN)
		Input.set_custom_mouse_cursor(DEFAULT_CURSOR)
		Input.set_mouse_mode(Input.MOUSE_MODE_VISIBLE)
                Input.set_custom_mouse_cursor(DEFAULT_CURSOR)
```

Obviously this doesn't seem to be very normal to have to do all this, but that should help in the meantime, so thanks. :)

**Comment by guilhermefelipecgs** [comment] 2019-05-08 19:27
> when releasing the mouse, the default cursor doesn't appear again unless I move.

okay, I was not expecting for that 😄, Linux behave differently.

Hopefully, this patchwill fix flickering:
```diff
diff --git a/platform/windows/os_windows.cpp b/platform/windows/os_windows.cpp
index 0b61770d8..57eca9db7 100644
--- a/platform/windows/os_windows.cpp
+++ b/platform/windows/os_windows.cpp
@@ -2392,6 +2392,7 @@ void OS_Windows::set_custom_mouse_cursor(const RES &p_cursor, CursorShape p_shap

                if (p_shape == cursor_shape) {
                        if (mouse_mode == MOUSE_MODE_VISIBLE || mouse_mode == MOUSE_MODE_CONFINED) {
+                               SetCursor(NULL);
                                SetCursor(cursors[p_shape]);
                        }
                }
```
Can you compile godot with the patch above to see if solves your problem?

**Comment by Jeto143** [comment] 2019-05-08 19:57
I've never done that yet so this might take me a little time (according to https://docs.godotengine.org/en/3.1/development/compiling/compiling_for_windows.html) but I'll get to it asap and let you know. Thanks again.

**Comment by guilhermefelipecgs** [comment] 2019-05-08 20:12
I compiled a 64 bits version, if you prefer: https://drive.google.com/file/d/1rcLlzKC2i2emmdzm--bqfJRg1F1FwfkL/view?usp=sharing

**Comment by Jeto143** [comment] 2019-05-08 20:29
Doesn't seem to make any difference at all, unfortunately :/ (workaround still works too)

**Comment by guilhermefelipecgs** [comment] 2019-05-08 22:03
Please try again with this one: https://drive.google.com/file/d/1bSzxcsyMLHrADxSomDFNeS77FvcaOWlA/view?usp=sharing

**Comment by Jeto143** [comment] 2019-05-08 22:14
Still the same, sorry. Feel free to keep them coming though, it's really easy to test.

**Comment by Jeto143** [comment] 2019-05-09 11:05
@guilhermefelipecgs Just tried it at work, where my computer has both a Intel HD Graphics 630 and a "normal" (though low-end) AMD graphic card: the flickering only occurs with the former.

So it probably occurs on any Windows 10 machine running an Intel HD Graphics chipset, if you can get your hand on one.

**Comment by guilhermefelipecgs** [comment] 2019-05-09 16:16
Technically, we can't fix the flickering cursor because this is an OS problem, this affect Windows, Mac, and Linux. I can clearly see flicker with native cursor on Linux using other programs (with my GTX 970), especially when it uses hotspot. The larger the image, more visible the flicker. That's why I've put a 32x32 limit in the past, but many users have asked to increase.

I was trying to get around the problem by hiding the cursor during the swap to smooth the flicker, 
but still godot can't guarantee that it would always work. So I don't think it's worth trying to fix it.

@Jeto143 One thing you can try is to center all the cursors to remove the need for the hotspot, the flicker should be less frequent this way.

**Comment by Jeto143** [comment] 2019-05-09 17:37
@guilhermefelipecgs How/why would that earlier hack/workaround completely fix it though? I don't see any flickering at all, even using 256x256 cursors, if I use it. See this updated minimal project (with giant cursors): [cursorbug_workaround.zip](https://github.com/godotengine/godot/files/3163266/cursorbug_workaround.zip)

If we can "fix" it like that, shouldn't Godot's implementation itself be able to do the same? Or is this too unoptimal/prone to side effects?

> @Jeto143 One thing you can try is to center all the cursors to remove the need for the hotspot, the > flicker should be less frequent this way (and if it works, you will not need that hack #28743 (comment)).

If I center the cursors (so that their hotspot is at the middle) I'll rather have to use a hotspot for all cursors, rather than none of them, right? Because I don't see how I can use a "target" cursor without a hotspot, unless I missed something.

I've just tried using a hotspot for *all* cursors and it actually removes the flickering as well, so I might just do that :)

**Comment by guilhermefelipecgs** [comment] 2019-05-09 20:43
> How/why would that earlier hack/workaround completely fix it though?

That workaround works because the cursor became invisible during the exchange and these extra calls create a slight delay (enough delay to hide the flicker). And creating a deliberate delay in function to hide an OS problem doesn't seem very good to me.


> If I center the cursors (so that their hotspot is at the middle) I'll rather have to use a hotspot for all cursors, rather than none of them, right?

You need to set the same hotspot for all cursors. I forgot to mention that.

> I've just tried that (using the same hotspot for _all_ cursors) and it actually removes the flickering as well, so I might just do that :)

It's good to know that it works, I'll try to document that on docs or class reference to let users know that using hotspot with larger textures may have this side effect.

**Comment by Jeto143** [comment] 2019-05-09 21:10
> That workaround works because the cursor became invisible during the exchange and these extra calls create a slight delay (enough delay to hide the flicker). And creating a deliberate delay in function to hide an OS problem doesn't seem very good to me.

Oh, of course then. I thought this was more of a "force some flags to update while they would normally be updated one frame too late" kind of thing. But if it's only a lucky delay, then obviously not the best idea!

Adding some docs on the matter sounds good in any case.

Anyway, feel free to close the issue then, and thanks again for your help/time.

**Comment by guilhermefelipecgs** [comment] 2019-05-09 22:28
You're welcome. I'll leave it open until I document it.

**Comment by KoBeWi** [comment] 2020-08-18 18:51
I checked the repro in [Godot 3.2.3 rc3](https://godotengine.org/article/release-candidate-3-2-3-rc-3) and I can't reproduce the issue (although not sure what to look at, because the video is dead).
@Jeto143 Can you confirm if it's fixed in the mentioned version?

**Comment by akien-mga** [comment] 2020-12-10 15:52
I'm pretty sure this was fixed by @guilhermefelipecgs.

**Closed by akien-mga** 2020-12-10 15:52 UTC
Labels: bug, confirmed, topic:input
