### ISSUE TITLE
Editor nodes fail initialisation on custom class with a _init function requiring parameter, results in unclear error

### ISSUE THREAD

**Issue by D2klaas** [godotengine/godot#64476] opened 2022-08-16 00:16 UTC
### Godot version

3.5

### System information

windows 10

### Issue description

When a node in the editor get a script assigned that requires a paramter for a _init function it fires a non fatal hard to decipher error. The nodes falls back on its super class. The error then is:
```
E 0:00:00.574   _create_instance: Condition "r_error.error != Variant::CallError::CALL_OK" is true. Returned: nullptr
  <C++-Quellcode>modules/gdscript/gdscript.cpp:126 @ _create_instance()
```
This isn't a major problem but could be better handled. Since this isn't caused by gdscript (would immediately raise an parse error) there is no obvious clou that points to the issue. 

### Steps to reproduce

Write a custom class with _init function requiering a paramter. Assign the script to a node in the editor. Try to call a custom function in the custom class. The debugger then showas that no script is actually assigned to the node.

### Minimal reproduction project

basenode:
```
extends Node

func _ready():
	for child in get_children():
		child.test()
```

childnode
```
extends Node

func _init( wannaFail ):
	print("you inited")

func test():
	print("test")
```

**Comment by Calinou** [comment] 2022-08-16 13:20
Duplicate of https://github.com/godotengine/godot/issues/15866.

**Closed by Calinou** 2022-08-16 13:20 UTC
