### ISSUE TITLE
Using dictionary keys direcly in function call crashes the game

### ISSUE THREAD

**Issue by ScyDev** [godotengine/godot#1040] opened 2014-12-23 17:01 UTC
The function findNearestTargetZombie() returns a dictionary that is properly filled with two non-null values.

When accessing the key directly in the function call to sendProjectile(), as in this example below, the game crashes without an error message (except Debug Process Stopped).

If I assign these two dictionary valus to two separate vars before using them, everything works fine.

```
			var targetZombieIntel = findNearestTargetZombie()
			
			if (targetZombieIntel["targetZombie"] != null):
				sendProjectile(currentWeapon, targetZombieIntel["shortestDistance"])
```

The function returns a dictionary:

```
func findNearestTargetZombie():
	var heroPos = self.get_translation() + self.get_parent_spatial().get_translation()
	
	var targetZombie = null
	var shortestDistance = null

        # code for finding zombies
	
	var found = {"targetZombie": targetZombie, "shortestDistance": shortestDistance}
	return found
```

**Comment by akien-mga** [comment] 2015-11-05 09:49
Can you still reproduce this issue in the current master @ScyDev? And still only in your own project, or could you manage to reproduce it in a simple project?

**Comment by akien-mga** [comment] 2016-03-24 10:08
Closing as there as not been activity since Dec 2014, and it will be hard to debug if it's project specific. The bug might still be there, but there's not much that can be done to isolate it without further input from the OP.

**Closed by akien-mga** 2016-03-24 10:08 UTC
Labels: bug, topic:gdscript
