### ISSUE TITLE
Will there be maintenance releases in the 2.0.x branch?

### ISSUE THREAD

**Issue by ret80** [godotengine/godot#3807] opened 2016-02-23 15:41 UTC
[en]
Very surprised at the emergence of a stable version 2.0! Recently I created a couple of bugs that have not yet been closed. And if you look at the current list of errors found it very huge. And all this is already a stable version!
The problem is that version 2.0 is not supported. Found it to correct errors will not be none. They will be corrected in the next version 2.1 already. And when it does not appear clear. And people have to live with supposedly stable version is not known how many. Updated between stable versions of bad practice. And how to live?

[ru]
Очень удивился появлению стабильной версии 2.0! Совсем недавно создал пару багов которые до сих пор не закрыты. И если посмотреть на существующий список найденных ошибок то он очень огромен. И при всем этом уже есть стабильная версия!
Проблема в том что версия 2.0 уже не поддерживается. Найденные в ней ошибки исправлять не кто не будет. Они будут исправляться в уже следующей версии 2.1. А когда она появится не ясно. И людям придется жить с якобы стабильной версией неизвестно сколько. Обновляться между стабильными версиями плохая практика. И как жить дальше?

**Comment by reduz** [comment] 2016-02-23 15:50
Stable means that none of the bugs is really serious, there will always be
bugs. They will be eventually fixed though.


2016-02-23 12:42 GMT-03:00 ret80 <notifications@github.com>:

**Comment by ret80** [comment] 2016-02-23 16:00
Let's say at the moment serious mistakes were found (although bug # 3764 considered serious). But if an error is found tomorrow, the problem will remain. Since version 2.0.1 will not be

**Comment by reduz** [comment] 2016-02-23 16:09
if we find more serious bugs, we make a 2.0.1 version, don't worry

**Comment by Ace-Dragon** [comment] 2016-02-23 17:06
The fact is with all software though, if the developers waited until there were no more bug reports of any kind before release, then the release would _never_ see the light of day.

The best you can do is ensure there's no showstoppers or notable regressions present (ie. making sure the software is not going backwards in terms of stability and quality).

**Comment by ret80** [comment] 2016-02-23 17:34
I agree. Provided that the developer will maintain the latest stable version. For example, developers Unity released fixes to the stable version is developing a new version. Between the stable versions of many events can occur. For example there is a new iOS or hkod renew or something. And we need that to version 2.0 to receive updates. But as the practice with Godot does not happen.

**Comment by reduz** [comment] 2016-02-23 17:38
Unity has more money and more developers to properly maintain a stable
version, but on the other side Godot HEAD is always generally stable

**Comment by akien-mga** [comment] 2016-02-23 17:41
> Provided that the developer will maintain the latest stable version. [...] And we need that to version 2.0 to receive updates. But as the practice with Godot does not happen.

That is true, up to now previous releases have not been supported much, but there had been only two releases so far (1.0 and 1.1, and 1.1 arrived relatively fast).

For 2.0, at one point the changes were so enormous compared to 1.1, and the master branch so stable, that it made no sense to create a 1.1.1 with fixes. We were already advising everyone to use Godot from git or nightly builds in production, as it was already very good.

The name "stable" in the tagged release does not mean that everything outside this tag is "unstable". Though I agree using just "2.0" for the final release would be better IMO - but now there's kind of a pattern :)

As for whether there will be a 2.0.1, it depends on the bugs we find, and what we plan as the next milestone. If we plan to have a new 2.1 release in a few months as many suggested (i.e. not the "big" 2.1 with tons of changes we've considered so far, but split this milestone into two or three smaller releases), the need for normal "maintenance" releases is not so important. If we plan to work on 2.1 for a very long time before it's "stable", then yeah, we'll consider a 2.0.1 to fix bugs.

**Comment by akien-mga** [comment] 2016-02-23 17:54
Also 1.1 did not appear as needing a maintenance release. How can I say that? Once 2.0 was well into its development, we got *few* bug reports done from 1.1 users, and even fewer duplicated bug reports about bugs in 1.1 that had been fixed in 2.0 but not backported to a stable 1.1.1 version.

So all in all, I don't think we've let our users down :) So I see no reason to think we'll let them down this time.

**Comment by Ace-Dragon** [comment] 2016-02-23 20:10
Ret; I wouldn't exactly refer to Unity as the way development should be done.

Sure, they release patches, but it's not preventing the fact that a sizable chunk of their community are sticking with older versions because they see the newer releases as unstable and containing game breaking regressions (even after the patch releases).

The way I see it going on there, they make releases based on deadlines and not whether the issue count has gone down to an acceptable level (you notice the Blender and Godot devs. in contrast choosing to hold off releasing if needed). You also need to take the condition of the codebase into account (the better quality the code, the less likely a fix breaks something else, and right now it seems the largest priority for the Unity devs. is adding features as fast as they can even if it means older ones breaking down).

**Comment by reduz** [comment] 2016-02-23 20:16
In Godot most devs keep using HEAD. 
To be honest, fixed releases are mostly for new developers, who will gradually move to HEAD too.

The advantage of our approach is that so far most issues get fixed very quickly. because there is a lot of developers testing them, so as a result HEAD is generally stable already.

**Comment by reduz** [comment] 2016-02-23 20:17
And of course the obvious advantage is less time needed to maintain old releases.

**Comment by philiplb** [comment] 2016-02-23 20:26
A nightly build system would be awesome then maybe? Or weekly?

**Comment by reduz** [comment] 2016-02-23 20:28
yeah we are working on nightlies, in fact I think there should be nothing
preventing them.. have to talk to punto and alket...

**Comment by philiplb** [comment] 2016-02-23 20:31
Great. :) I could offer an hosted MacMini if you like for the OS X and iOS templates.

**Comment by reduz** [comment] 2016-02-23 20:41
stable in Godot is more like "we fixed as much as we could for this release
and we tested it well".. so releases are a good starting point for someone
new to godot. There is not much of a concept of LTS for old releases though.

**Comment by reduz** [comment] 2016-02-23 20:41
Thanks! Though we ended up using OSXCross for this, it worked wonders

**Comment by ret80** [comment] 2016-02-23 21:19
All this is great but unfortunately your approach with constant updating of the head does not work. Example:
You have updated the system modules and system assembly androyd templates. Documentation for this security update was not followed. I needed to build the project with advertising. And because of the lack of proper documentation, I could not do it. Then I decided to go back to version 1.1 and there to build the project. But unfortunately, and here I was waiting for the failure because the new xcode refused to collect engine version 1.1. It tore me all the terms of the assignment. And I had to look for other solutions. What I mean is that the policy updates and versioning is not bad Godot promotes the use for commercial purposes. All too unreliable. I believe that it is time to change something like that.
PS
To refer that we can not do something because they have more money and people is not an option. It should be like an old remedy the situation for the better. Not immediately but at least gradually.

**Comment by ret80** [comment] 2016-02-23 21:43
Incidentally I noticed in the features of the platform haiku. But, unfortunately, how to build Godot under this OS is not where it is not written. This is not a normal situation. If something is stated to be described.

**Comment by reduz** [comment] 2016-02-23 22:06
This had to be done because Google deprecated Ant, even if we had kept an
LTS with Ant, Google erased all the documentation about Ant from their
website. It was not our fault, we had to forcibily upgrade to Gradle.

**Comment by punto-** [comment] 2016-02-23 23:18
The main obstacle for nightilies is that if we turn them on, we'll run out
of credit in the machine that builds them after like 10 days. We need a
better host for that..

**Comment by akien-mga** [comment] 2016-02-23 23:34
What about weekly builds? :p

**Comment by trollworkout** [comment] 2016-02-24 08:03
i have used godot for a month now and been compiling my own godot engine from source almost every day and every compile has been a stable one

**Comment by ret80** [comment] 2016-02-24 09:32
The fact that we had to go to the Gradle is no problem. The problem is that the process for Godot members was poorly described. Rather generally it has not been described. Moved all. That this is sad!

**Comment by ret80** [comment] 2016-02-24 14:48
I worked one hour the new version. This is supplemented by bugs #3764, #3766.
I suggest to all the same release version 2.0.1

**Comment by trollworkout** [comment] 2016-02-25 07:57
i suggest 3 branches:
very stable USE FIRST  this one is awesome 1111
unstable sucks is like OKish 
maybe u wanna throw this in the garbage

aka this post is waste of time you don't need a stable branch pls close this. I , however, like the idea of nightlies. I don't know how you guys wanna do the nightlies but I can help. I am on OSX so i can cross compile.

**Comment by DriNeo** [comment] 2016-02-26 18:15
Why not just have more frequent stable releases ? With a less ambitious roadmap for every release it could be possible.
And it could be good for Godot popularity because the software seems more alive.

**Closed** 2016-03-13 11:57 UTC
Labels: discussion

**Comment by akien-mga** [comment] 2016-03-13 12:01
For the reference, as it's related to this discussion: http://godotengine.org/article/updates-on-the-release-cycle-and-godot-2-0-1
