### ISSUE TITLE
EditorPlugin "add autoload" changes the active scene

### ISSUE THREAD

**Issue by CodeDarigan** [godotengine/godot#29000] opened 2019-05-19 11:41 UTC
3.1 Stable, Windows 10.

When adding any autoload (tool or otherwise) via EditorPlugin's "add_autoload_plugin", it changes the active scene in the editor. If you have two scene tabs, the selected tabbed scene will be the one changed. If no scene is selected, nothing will change. 

I'm not sure if this is a bug or intended behaviour but it does seem to conflict with the idea of adding autoloads in the EditorPlugin especially if they're tooled (as one would except from an EditorPlugin)

On a slightly related note too, remove_autoload in plugins exit_tree hangs the editor for a bit when exiting the editor.

[Example Repo](https://github.com/CodeDarigan/AutoloadExample)

**Comment by KoBeWi** [comment] 2020-08-10 21:46
Can anyone still reproduce this bug in [Godot 3.2.3 rc3](https://godotengine.org/article/release-candidate-3-2-3-rc-3) or any later release?

If yes, please ensure that an up-to-date Minimal Reproduction Project (MRP) is included in this report (a MRP is a zipped Godot project with the minimal elements necessary to reliably trigger the bug). You can upload ZIP files in an issue comment with a drag and drop.
(the linked project is dead)

**Comment by KoBeWi** [comment] 2020-09-28 16:40
Closing due to lack of update. Please comment if you can still reproduce this issue in the latest stable version of Godot.

**Closed by KoBeWi** 2020-09-28 16:40 UTC
Labels: bug, topic:plugin
