### ISSUE TITLE
No ability to flip parallax background

### ISSUE THREAD

**Issue by ghost** [godotengine/godot#5198] opened 2016-06-13 20:16 UTC
There's no ability to flip parallax background. Maybe add an option?

**Comment by reduz** [comment] 2016-06-13 21:17
just flip the nodes children of ParallaxLayer.. you can scale them by -1 at
some axis

**Comment by zerornull** [comment] 2016-06-13 21:20
@reduz It's not centered so it needs to get parallax background's size and add it as an offset.

**Comment by trollworkout** [comment] 2016-06-14 04:50
Have you tried to set scaling negative on ParallaxLayer say -1, 1. It should flip it and preserve any offsets.

**Comment by zerornull** [comment] 2016-06-14 06:15
@trollworkout Since it's not centered, it won't be on screen. And it would require to get background's size, which I can't get. Simply scaling it doesn't work, it's not centered.

**Comment by zerornull** [comment] 2016-06-14 06:18
@reduz It doesn't work, tried that. They're in wrong position.

**Comment by zerornull** [comment] 2016-06-14 06:22
@trollworkout No, wouldn't work, since parallax layers aren't centered too.

**Comment by zerornull** [comment] 2016-06-15 17:51
@reduz Also what about adding to canvas layer not only ignoring camera zoom option, but ignoring it's rotation and scale, which could be unchecked? Or simpy making parallax background not rotating with camera?

**Comment by Chaosus** [comment] 2018-08-23 16:19
Its probably fixed(and I dont see other complains about same problem), the issue is also bad formed and does not contain subheaders, version or screenshots. Closed by bugsquad.

**Closed by Chaosus** 2018-08-23 16:19 UTC
Labels: feature proposal, topic:core
