### ISSUE TITLE
Nonexistent function `get-parameter-list` in (base) AnimationNode

### ISSUE THREAD

**Issue by michael-nischt** [godotengine/godot#64539] opened 2022-08-17 16:37 UTC
### Godot version

v3.5.stable.official [991bb6ac7]

### System information

Ubuntu 22.04, NVIDIA GeForce GTX 765M

### Issue description

The `AnmationNode` function [get-parameter-list](https://docs.godotengine.org/en/stable/classes/class_animationnode.html#class-animationnode-method-get-parameter-list) is nonexistent in sub-classes.

E.g.:
![image](https://user-images.githubusercontent.com/500820/185191554-081bd393-6e0c-4914-b32e-26ff0cdcca59.png)

Consequently, [get-parameter](https://docs.godotengine.org/en/stable/classes/class_animationnode.html#class-animationnode-method-get-parameter) always returns `null`.

### Steps to reproduce

1. Run the attached minimal reproduction project.
2. Note the errors in `player_anim.gd` attached to the `AnimationTree` node.
3. Optional: set the `WORKAROUND` constant to `false` for am idea why we want that

Note:  we don't want to iterate all parameters via the `AnimationTree` node and filter the nodes. This would be a error prone since the `AnimationNodeBlendSpace1D` sub-nodes are not sorted by their position! (they are in that example but we want to turn the script into a general plug-in).

### Minimal reproduction project

[AnimtionNodeBug-MissingMethods.zip](https://github.com/godotengine/godot/files/9364594/AnimtionNodeBug-MissingMethods.zip)

The purpose is to blend movement animations based on a single `speed` value.
The animations on;y require matching animation cycles but can each have different duration.

A feature Unity's Mecanim `BlendTree1D` has built-in but Godots `AnimationNodeBlendSpace1D` can't since there's no way to query an `AnimationNode`s duration.

**Comment by Calinou** [comment] 2022-08-17 21:06
Duplicate of https://github.com/godotengine/godot/issues/35272.

**Closed by Calinou** 2022-08-17 21:06 UTC

**Comment by michael-nischt** [comment] 2022-08-17 21:23
@Calinou Can we please discuss this?

I understand that it originally wasn't intended to call based on the discussions in the duplicated report.

However, I hope the this report makes a good point why there is a lot of benefit to actually having them callable. 
I would at least expect a suggestion how to solve the problem I shared without those.

To be more precise. Querying the global parameter list doesn't help since `AnimationNodeBlendSpace1D` points are not named explicitly. They are numbers based on the node creation and not sorted. Understandably since there is not valid sorting for the 2D case, so explicit naming is the only option I can think of. 
This means there is not way to deterministically query the parameters matching a node. At least not in a generic way required (required for a plugin).

Or what am I missing?

**Comment by Calinou** [comment] 2022-08-17 21:47
> Can we please discuss this?

Use the https://github.com/godotengine/godot-proposals repository for that :slightly_smiling_face:
