### ISSUE TITLE
[C#] Type safe return types for PhysicsDirectSpaceState API

### ISSUE THREAD

**Issue by mysticfall** [godotengine/godot#19362] opened 2018-06-04 15:54 UTC
**Godot version:**
`master` / 2ff31badaff

**OS/device including version:**
_Manjaro Linux 17.1_

**Issue description:**
Currently, all methods of `PhysicsDirectSpaceState` API have generic return type like `object` or `Dictionary<object, object>` in C#, which better be changed to something more specific to prevent potential mistakes.

**Comment by akien-mga** [comment] 2022-01-24 23:22
Is this fixed in current Godot versions? The 3.4 docs seem to indicate that return types for these methods are either `Array` or `Dictionary`, which matches the GDScript API / information from ClassDB.

**Comment by raulsntos** [comment] 2022-01-25 02:43
This sounds like a duplicate of #19342

**Closed** 2022-01-25 06:55 UTC
Labels: enhancement, usability, topic:mono
