### ISSUE TITLE
Find in Files/Replace in Files

### ISSUE THREAD

**Issue by vonflyhighace2** [godotengine/godot#16336] opened 2018-02-02 23:48 UTC
**Godot version:**
Any

**OS/device including version:**
Any/Engine Level

**Issue description:**
there is a find/replace in file but this should be expanded to files throughout the project to include more search capabilities. Also can we have button Icons not be fixed sizes, I seen no reason for this. there is no way to adjust the rect of a button fitted with a texture in the Icon property.

**Steps to reproduce:**
This would be a tremendous feature since a lot of people use external code editors solely for mass refactoring, plus just a nice feature in general.

**Minimal reproduction project:**

**Comment by vnen** [comment] 2018-02-03 03:24
Related to #2592.

**Comment by vonflyhighace2** [comment] 2018-02-03 05:37
Wow from 2 years ago talk about being buried.

**Comment by vnen** [comment] 2018-02-03 13:58
It's not much about being buried, it's more about no one caring enough to actually make it happen.

**Comment by NathanWarden** [comment] 2018-02-03 14:09
You might as well comment on it if you're interested in it... or if you know how to it would be awesome if you could go ahead and implement it :)

**Comment by Ranoller** [comment] 2018-02-04 02:58
I have a modification of TODO plugin that do that (only search, not replace) but godot 2 do not expose to gdscript enought methods to scroll to any line in the script, so you only see where are the search result and the line, and you need to scroll to that manually. TODO plugin it's not ported to godot 3... I suscribe this feature request with all my hearth. Perfect example of this feature is the way that is implemented in notepad++(find in open files, replace in open files, with a contextual window with the search results that allow to jump to file and line).... But i'm realist about that, this is not trivial, i'm happy with code folding and function list, this is "the third" of the trinity of the text-editor features in my opinion...

**Comment by Zylann** [comment] 2018-02-08 02:15
Duplicate of #2592 ?
I started such a tool this evening :p

**Comment by alforium** [comment] 2018-02-08 08:45
I was going to post the same suggestion! I'd really like being able to mass-search and mass-replace across all project scripts. 

Another example of a program that does this well is Bluefish, which is the one I've been using. But it would be much better to be able to do all script-related stuff directly inside of Godot.

Here's an idea to polish it further: being able to choose between searching in all files in the project, searching in open files or just in files in a particular folder.  But just a basic option that includes all files would be really nice already.

Btw, thanks for your work, guys! :) This engine is awesome. I hope I can contribute some day.

**Closed** 2018-04-08 20:24 UTC
Labels: feature proposal, topic:editor, usability
