### ISSUE TITLE
Checks for Nodes (Bodies?) in group pulls another node from scenetree that isn't part of group

### ISSUE THREAD

**Issue by HPCR-SD** [godotengine/godot#79180] opened 2023-07-07 23:28 UTC
### Godot version

v4.1.rc3.official [cdd2313ba]

### System information

Godot v4.1.rc3 - Windows 10.0.19045 - Vulkan (Compatibility) - Intel(R) UHD Graphics 630 (Intel Corporation; 31.0.101.2114) - Intel(R) Core(TM) i5-10500T CPU @ 2.30GHz (12 Threads)

### Issue description

I came across this while making a mistake in my code and forgot about it til just now while realizing that this behavior still doesn't make sense.

When I do a check like if `_on_body_entered(body: Node2D) -> void: get_tree().get_nodes_in_group("plane"): body.die()` which is connected to body_entered signal body.die() gets triggered by any body that collides with my Area2D, even if it's not part of the group. What's funny is if I tell before the detection to check if that node is part of that group, it comes back false, but if I run code to remove it from the group, suddenly body.died doesn't get called anymore, because the check suddenly becomes false...As it should have been in the first place. 

Now I understand there maybe some confusion why I'm checking the tree for nodes in the group, I can't over state how accidental it was that I came across this. It was a late night and I was following a tutorial and I kept missing this one detail cause I wasn't thinking clearly. 

My apologies if I'm still missing something here, but my understanding from reading documentation is that the object which was in the scene should have been the only thing returned or if for some reason it hadn't it should have returned an empty array, or since the same deal happens with get_first_node_in_group it should have return null.

Also hence my Bodies? comment in the title I'm unsure how wide spread this is. This is likely bigger then when checking bodies, but it's strange that what it returned was a body not assoiated with the group and not just any other node...so this could be bodies only, or when using this to pull nodes in a group in a tree for any reason

I'm hoping I've provided enough detail and been clear enough. If not I'll try to come back to this Sunday with a clearer mind.

### Steps to reproduce

Assuming this is Body only related to keep to what I have experienced you just need 2 bodies (I used area2d and static body, but found character body would trigger it as well) to collide, do a check for a node being part of a certain group using either get_first_node_in_group or get_nodes_in_group and in my case it fails to pull the only node in the scene tree in that group and pulls a node (body) not in the that group from the scene tree.

### Minimal reproduction project

[Test.zip](https://github.com/godotengine/godot/files/11986870/Test.zip)

**Comment by Zireael07** [comment] 2023-07-08 08:28
user error

body is the body that triggered the signal

get_tree().get_nodes_in_group gets... nodes in group, but you don't do anything with those (you don't assign the list to a variable)

You're effectively doing NO check whether the body is in a group

the proper way to do it is
_on_body_entered(body: Node2D) ->
  if body.is_in_group("plane"):
      body.die()

**Comment by kleonc** [comment] 2023-07-08 11:59
User error, as explained in the previous comment. Evrything works as intended. Closing as not a bug.

Further explanation:
- `get_tree().get_nodes_in_group("plane")` returns an `Array` containing nodes belonging to the `"plane"` group,
- an `Array` evaluates to `true` only if it's non-empty.

Hence `if get_tree().get_nodes_in_group("plane"):` checks whether there are any nodes in the `"plane"` group.

---

@HPCR-SD For the future, please use [other community channels](https://godotengine.org/community/) (Discord/Reddit/Q&A/etc.) to ask for help when you're not sure about something. This is a bugtracker, not a help desk.

**Closed by kleonc** 2023-07-08 11:59 UTC
