### ISSUE TITLE
@export values from parent class do not get updated in child class within the editor

### ISSUE THREAD

**Issue by Go-Ba** [godotengine/godot#84038] opened 2023-10-27 05:59 UTC
### Godot version

v4.1.2.stable.official [399c9dc39]

### System information

Godot v4.1.2.stable - Windows 10.0.19045 - Vulkan (Compatibility) - NVIDIA GeForce GTX 1060 6GB (NVIDIA; 31.0.15.3623) - AMD Ryzen 5 2600X Six-Core Processor (12 Threads)

### Issue description

Parent class has a variable with @export
child inherits from that class

when a change is made to the variable i.e changing default value, changing export_range limits, or even deleting the variable all together, these changes do not get reflected in any node with a class that inherits from that parent class

![image](https://github.com/godotengine/godot/assets/64071930/892623bb-06a3-496f-a5ca-95dc73ce4aa6)
![image](https://github.com/godotengine/godot/assets/64071930/984277ee-1237-45e0-9603-97c42fef44e8)

### Steps to reproduce

- make a parent class
- give it a class_name
- make a child class which inherits from it
- add an @export variable to the parent class
- create a node for both the parent and child class
- observe that they both have that variable being exported
- modify or delete the variable from the parent class
- it will be updated for the parent class but still display for the child class

### Minimal reproduction project

[Inheritance_Bug_MRP.zip](https://github.com/godotengine/godot/files/13185367/Inheritance_Bug_MRP.zip)

**Comment by dalexeev** [comment] 2023-10-27 12:14
* Duplicate of #82998.
* Fixed by #83123 for 4.2.

Thanks for reporting the bug nonetheless!

**Closed by dalexeev** 2023-10-27 12:14 UTC
