### ISSUE TITLE
CollisionShape2D does not exist at run-time after reparent/duplication

### ISSUE THREAD

**Issue by not-surt** [godotengine/godot#1183] opened 2015-01-11 09:17 UTC
When reparenting a CollisionShape2D to a StaticBody2D or duplicating a CollisionShape2D in a StaticBody2D the new shape will not exist at run-time until it is moved on the editor canvas.

Demo project: https://docs.google.com/uc?export=download&id=0B7Mva4UEh5kxRk5BOFlLazBLekk
Run the demo project.
The StaticBody2D reports as having 0 shapes.
Move a CollisionShape2D on the canvas.
Run the demo project.
The StaticBody2D now correctly reports as having 2 shapes.

**Comment by reduz** [comment] 2015-01-11 14:42
collisionshape2D never exists at runtime because it's a helper for the
editor.
This will change soon though, since it seems there is a lot of use for it
being accessible. Might be enabled with a flag.

**Comment by not-surt** [comment] 2015-01-11 19:18
Yes but it is supposed to be turned into a Shape2D that does exist at runtime.
That Shape2D will not exist after reparent/duplication until the corresponding CollisionShape2D is moved on the editor canvas.

**Comment by okamstudio** [comment] 2015-01-11 19:26
oh the Shape2D is in the CollisionObject2D API during runtime

On Sun, Jan 11, 2015 at 4:18 PM, surt <notifications@github.com> wrote:

> Yes but it is supposed to be turned into a Shape2D that does exist at
> runtime.
> That Shape2D will not exist after reparent/duplication until the
> corresponding CollisionShape2D is moved on the editor canvas.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/okamstudio/godot/issues/1183#issuecomment-69506882>.
>



-- 

*OkamStudio*

**Comment by not-surt** [comment] 2015-01-16 12:33
I just discovered that the reverse is also true.
I had deleted some CollisionShape2Ds from previously duplicated StaticBody2Ds in the editor but the Shape2Ds corresponding to the deleted CollisionShape2Ds were still appearing when the game was run.
It does appear to be some kind of caching issue.
If I move one of the remaining CollisionShape2Ds in the editor it seems to update properly and all deleted Shape2Ds no longer show up at run-time.

**Comment by akien-mga** [comment] 2015-11-06 10:13
I believe this has been fixed in the current master branch.

**Comment by eska014** [comment] 2015-11-06 23:37
I can still reproduce this issue in master.

**Comment by bojidar-bg** [comment] 2017-06-29 10:49
I assume this was fixed in the 3.0 collision shape refactor (currently just 2D)?

**Comment by reduz** [comment] 2017-08-04 15:57
This is finally fixed now, both in 3D and 2D, let's celebrate!!

**Closed by reduz** 2017-08-04 15:57 UTC
Labels: bug, confirmed, topic:core, topic:physics
