### ISSUE TITLE
WorldEnvironment with stretch_mode = viewport and mode = keep bugs

### ISSUE THREAD

**Issue by razcore-art** [godotengine/godot#3656] opened 2016-02-10 19:48 UTC
### Steps to replicate
1. open to "HDR for 2D" in edit mode
2. go to `Project Settings`, set `stretch_mode` to `viewport` set `width` and `height` to some values greater than your screen resolution (I set mine to 1920x1080)
3. run "game"

I get [this image](https://dl.dropboxusercontent.com/u/40341257/godot/godot_environ_bug01.png) which is a bug, those stretchy things on the right side shouldn't exist.

![godot_environ_bug01](https://cloud.githubusercontent.com/assets/4701338/12959903/de0cbc4a-d038-11e5-8e29-a119eaef06e8.png)

Also, if `mode` is set to `Keep` in the `Environment` resource, the editor goes crazy [like so](https://dl.dropboxusercontent.com/u/40341257/godot/godot_environ_bug02.png)... By the way, I have no idea what this `mode` property does... I was just fulling around.

![godot_environ_bug02](https://cloud.githubusercontent.com/assets/4701338/12959907/e136d81a-d038-11e5-954b-90d726309aac.png)

**Comment by akien-mga** [comment] 2016-02-10 19:58
Note: please upload the images directly on the bug report with drag&drop, this way we still have the info even if you cleanup your dropbox ;) (I've imported them already for this bug).

**Comment by akien-mga** [comment] 2016-02-10 20:01
Potentially a duplicate of #1571.

**Comment by razvanc87** [comment] 2016-02-10 20:02
I forgot you can upload the images...

**Comment by razcore-art** [comment] 2018-06-23 06:59
@akien-mga yea, I checked, it seems that #1571 refers to the same stretch_mode issue, that part seems to be fixed by cc3777d, the environment mode = keep is still a problem in the editor, but since this is for v2.1 and everything is focused on v3 I'm wondering if I should close this issue. What you think?

**Comment by akien-mga** [comment] 2018-06-25 13:05
Yeah issues that are specific to 2.1 are unlikely to get fixed nowadays, unless they're really blockers for some games currently being developed with 2.1. I'll leave it to you to see if you think it can be closed, or if it should stay around "just in case" someone wants to work on it or be closed when 2.1 goes EOL.

**Comment by akien-mga** [comment] 2018-09-17 13:31
The 2.1 branch is no longer actively worked by engine developers, unless critical fixes are needed for current games in production. As such we are now closing non-critical bug reports affecting only the 2.1 branch.

Please comment if this was incorrectly triaged and is still relevant in 3.x versions.

**Closed by akien-mga** 2018-09-17 13:31 UTC
Labels: bug, topic:core, topic:rendering
