### ISSUE TITLE
C#/Mono: Rect2::GrowMargin does not return modified Rect2

### ISSUE THREAD

**Issue by KamiGrave** [godotengine/godot#38217] opened 2020-04-26 09:42 UTC
**Godot version:**
3.2 C#/Mono
**Issue description:**
The method Rect2::GrowMargin(Margin margin, float by) calls Rect2::GrowIndividual but does not assign the return value of the call, therefore just returns an unmodified copy of 'this' (i.e. the current Rect2).
**Steps to reproduce:**
1. Create Rect2 with some size and position
2. Call GrowMargin on the Rect2 to increase the size
3. Notice that the returned Rect2 matches the initial Rect2's size and position

**Work around:**
Call GrowIndividual instead, as internally that's what the call is doing anyway.

**Comment by Nannaquin** [comment] 2020-04-26 18:54
Hey, I'm trying to go after this but GrowMargin isn't returning the initial size and position when following the reproduction steps (in other words its working on my end). Is there any more detail you can provide?

**Comment by KamiGrave** [comment] 2020-04-26 20:05
I'm not sure how that's possible. The code I'm seeing:
` public Rect2 GrowMargin(Margin margin, real_t by)
        {
            var g = this;

            g.GrowIndividual(Margin.Left == margin ? by : 0,
                    Margin.Top == margin ? by : 0,
                    Margin.Right == margin ? by : 0,
                    Margin.Bottom == margin ? by : 0);

            return g;
        }`

It never assigns 'g'. I've just double checked and Rect2i is the same. Which means what is returned will always be equal to 'this', not the modified Rect2. I would expect it to behave the same as GrowIndividual, which modifies 'g' correctly before returning. In this case, the return value of GrowIndividual is not being used.

That code is from the Master branch, but looks the same on the others I checked.

**Comment by Nannaquin** [comment] 2020-04-26 20:15
Ah, I built from 3.2 since you specified that.  I took a look at that code and GrowIndividual and at first thought the same thing, but it seems that both GrowMargin and GrowIndividual return their changes in the same way.  Additionally I checked to make sure GrowIndividual was working first (it did), so I'm not sure why I'm not able to replicate the issue (or let alone how GrowMargin works under these conditions).

**Comment by Nannaquin** [comment] 2020-04-26 20:39
Can I ask what kind of values you're providing to GrowMargin?

**Comment by KamiGrave** [comment] 2020-04-26 20:58
I was calling it using Margin.Top and something like 64 (It was calculated in the code). My original position was 0, 48 and size 32, 128.

**Comment by KamiGrave** [comment] 2020-04-26 21:15
[Rect2Test.zip](https://github.com/godotengine/godot/files/4536480/Rect2Test.zip)

Here's a minimum project showing 3 cubes. Red is the original, green is GrowMargin and blue is GrowIndividual.

It's using v3.2.1.stable.mono.official, and targetting framework version 4.8 (I don't have 4.7 installed).

**Comment by Nannaquin** [comment] 2020-04-26 21:16
Try using MARGIN_TOP instead of Margin.Top

**Comment by KamiGrave** [comment] 2020-04-27 17:37
According to what I can see, Margin.Top has the value 1. Left is 0, Right = 2, Bottom = 3.

I can find any define for MARGIN_TOP in Mono at all. There's only a define for GDScript from the GlobalScope. Are you sure you're running the Mono version and not GDScript?
As far as I can see, the GDScript version (i.e. C++ version) is correct. It is the Mono version that appears to be wrong.

I'll modified the original description to mention Mono in case it isn't clear from the issue title.

**Comment by pycbouh** [comment] 2020-04-28 10:16
The same issue was fixed in the native implementation a couple of years ago: #14919. Mono has its own code for this that needs to be updated as well.

@Nannaquin for your reference.

**Comment by Nannaquin** [comment] 2020-04-28 19:03
Should I be making this change in the 3.2 branch or the master branch? This whole time I've been working with the 3.2 files (where there is an absence of the Rect2i.cs file in the same folder as Rect2.cs)

**Comment by pycbouh** [comment] 2020-04-28 19:16
@Nannaquin You should always make PRs against the master branch.

**Closed** 2020-04-30 01:39 UTC
Labels: bug, cherrypick:3.2, junior job, topic:mono
