### ISSUE TITLE
Node2D.global_rotation affected by scale

### ISSUE THREAD

**Issue by greenfox1505** [godotengine/godot#31980] opened 2019-09-05 00:03 UTC
**Godot version:** 3.1

**OS/device including version:** seen on web and Ubuntu 18.04.3 LTS

**Issue description:** Node2D

**Steps to reproduce:** Reading and write back to Node2D.global_rotation when a parent node is not evenly scaled (scale.x != scale.y)

**Minimal reproduction project:** https://gitlab.com/greenfox/global-rotation-vs-scale

**Comment by greenfox1505** [comment] 2019-09-05 00:09
https://greenfox.gitlab.io/global-rotation-vs-scale
This link should have a usable demo in about 30minutes

**Comment by Zylann** [comment] 2019-09-05 12:40
But what difference do you actually get?
I think it's because when using a matrix to do conversions, scale and rotation are overlapping the same cells. So rotation WILL affect cells that relate to scale, but the reason you obtain different scale is probably because of float precision error.

**Comment by greenfox1505** [comment] 2019-09-06 18:26
> But what difference do you actually get?

The answer to that is in demo I posted.

It probably is a floating point error.

**Comment by svendixon** [comment] 2019-11-08 12:14
Yeah pretty annoying.

I use scale.x to flip my objects and sprites in my platform game. And I have to check if my rotation save data is round(abs(data["rotation"])) is 180, then hard set it to 0. Then set my scale to Vector2(-1, 1). 

Otherwise it would set some crazy rotation and the scale.y to -1... It's gross.

**Comment by MightyPrinny** [comment] 2020-03-17 00:00
This is a duplicate of  #17405

**Comment by akien-mga** [comment] 2020-03-17 06:40
Closing as duplicate of #17405. I copied the reproduction project there.

**Closed by akien-mga** 2020-03-17 06:40 UTC
Labels: bug, archived, topic:core
