### ISSUE TITLE
GDScript - The dictionary from get_signal_connection_list() doesn't parse .signal

### ISSUE THREAD

**Issue by avencherus** [godotengine/godot#7321] opened 2016-12-17 16:28 UTC
This is on Windows version 2.1.1

When you try to access the dictionary result of this method, you can't use the dot notation for signal.  The editor can't see to parse it.

```
func _ready():
	connect("exit_tree", self, "test")
	for s in get_signal_connection_list("exit_tree"):
		print(s.signal)

```
![godot_2016-12-17_18-27-20](https://cloud.githubusercontent.com/assets/13004169/21288249/8349e498-c486-11e6-8a93-d2ab0d8bf105.png)

**Comment by bojidar-bg** [comment] 2016-12-17 18:16
Note that you can workaround this with `s["signal"]` -- (I do not think this issue is a minor one).

**Comment by avencherus** [comment] 2016-12-17 18:19
Thanks bojidar.  That's what I ended up having to do to use it.  Thought it was worth reporting.  It seems to be something with the signal keyword, so it might be present in some other areas that I'm less familiar with.

**Comment by bojidar-bg** [comment] 2016-12-17 19:33
It is also present if you do `object.log()` --> it would fail because `log` is a builtin function in gdscript.

**Comment by bojidar-bg** [comment] 2017-04-14 09:18
Closing in favour of #8085, since even though the latter is actually duplicate of that one, it is more active that this one.

**Closed by bojidar-bg** 2017-04-14 09:18 UTC
Labels: bug, discussion, topic:gdscript
