### ISSUE TITLE
The basis matrix of the character is changing, but the character does not generate rotation

### ISSUE THREAD

**Issue by ypp666666** [godotengine/godot#76732] opened 2023-05-04 17:49 UTC
### Godot version

godot4.03 rc1

### System information

windows 11 5600g

### Issue description

I have been using quaternion interpolation to smooth the rotation of my rigid body character before, and they have been reliably validated in versions such as godot3 and godot4beta. However, when I ported the project to the latest version of Godot4, the character was unable to generate rotation. I have tried some possible reasons.

1. The character's rigid body can still control rotation by changing its angle

2. The character's rigid body can still generate rotation or deformation by multiplying it by a certain value in the basis matrix

3. Character rigid bodies cannot be set to global anymore_ Transform coordinates to generate rotation, although running

### Steps to reproduce

	if nav_agent.is_target_reachable() and not nav_agent.is_target_reached():
		next_location = nav_agent.get_next_path_position()
		direction = next_location- $".".global_transform.origin
		direction = direction.normalized()
		$".".global_transform.origin += direction*delta*speed

		look_at = lerp(look_at,-$".".global_transform.origin-direction*10,0.16)
		look_at = look_at.normalized()
		print(look_at)

		var wtransform = $".".global_transform.looking_at(look_at,Vector3(0,1,0))
		var wrotation = Quaternion($".".global_transform.basis).slerp(Quaternion(wtransform.basis),0.09)  
		$".".global_transform = Transform3D(Basis(wrotation), $".".global_transform.origin)

### Minimal reproduction project

if nav_agent.is_target_reachable() and not nav_agent.is_target_reached():
	next_location = nav_agent.get_next_path_position()
	direction = next_location- $".".global_transform.origin
	direction = direction.normalized()
	$".".global_transform.origin += direction*delta*speed

	look_at = lerp(look_at,-$".".global_transform.origin-direction*10,0.16)
	look_at = look_at.normalized()
	print(look_at)

	var wtransform = $".".global_transform.looking_at(look_at,Vector3(0,1,0))
	var wrotation = Quaternion($".".global_transform.basis).slerp(Quaternion(wtransform.basis),0.09)  
	$".".global_transform = Transform3D(Basis(wrotation), $".".global_transform.origin)

**Comment by ypp666666** [comment] 2023-05-04 17:52
I have printed out the basis matrix, and I can see on the console that the basis matrix is changing as expected. On the remote panel, the basis matrix of the character's rigid body is also changing, but the character just doesn't rotate, even a little bit.

**Comment by AThousandShips** [comment] 2023-05-04 17:55
Please upload an MRP:

> To speed up our work, please upload a minimal project that isolates and reproduces the issue. This is always the best way for us to fix it. We recommend attaching a ZIP file with the minimal project directly to the bug report, by drag and dropping the file in the GitHub edition field. This ensures the file can remain available for a long period of time. Only use third-party file hosts if your ZIP file isn't accepted by GitHub because it's too large.
>
> We recommend always attaching a minimal reproduction project, even if the issue may seem simple to reproduce manually.

**Comment by AThousandShips** [comment] 2023-05-04 17:56
Also using $"." Is unnecessary, it just means the node itself

**Comment by AThousandShips** [comment] 2023-05-04 18:04
Also you can't control a `RigidBody3D` directly except by forces, I think you need to use a `CharacterBody3D`

**Comment by AThousandShips** [comment] 2023-05-04 18:09
See [here](https://docs.godotengine.org/en/stable/tutorials/physics/rigid_body.html#doc-rigid-body)

**Comment by ypp666666** [comment] 2023-05-04 18:41
Thank you. I use rigidbody,and I resolved this issue while creating MRP, and the rotation is working properly again. I think it may be due to other code in my project updating the character's position information, which resulted in the character not rotating as expected. Overall, this is a mistake caused by my low-quality code, However, there is indeed a mismatch between the transformation parameters and the actual situation in  godot (even in certain code conflicts, I think it should still be in line with practical intuition)

**Comment by fire** [comment] 2023-05-06 01:47
Is this resolved? How can we resolve?

**Comment by Calinou** [comment] 2023-06-09 18:32
- Related to https://github.com/godotengine/godot/issues/74162.

@ypp666666 Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot. Otherwise, we'll have to close this as we have no way to reproduce the issue locally (and find a way to resolve it).

**Comment by Calinou** [comment] 2023-07-03 23:26
Closing due to lack of response. Please comment if you can still reproduce this bug on the latest Godot version.

Since no [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) was included in the original bug report, please upload one as well to ease troubleshooting.

**Closed by Calinou** 2023-07-03 23:26 UTC
Labels: bug, topic:core, needs testing
