### ISSUE TITLE
Godot freezes when show popup window

### ISSUE THREAD

**Issue by o01eg** [godotengine/godot#44033] opened 2020-12-02 08:34 UTC
**Godot version:**

ba51af7904819b3739173d24567e79ee5d3600f9

**OS/device including version:**

Gentoo Linux AMD64, GeForce GTX 750 Ti, nvidia-drivers, Vulkan

**Issue description:**

Godot editor freezes after show any popup windows.

```
Godot Engine v4.0.dev.custom_build.ba51af790 - https://godotengine.org
Using ICU / HarfBuzz / Graphite text server...
DisplayServer::_create_window 0 want rect: 448, 300, 1024, 600 got rect 448, 300, 1024, 600
DisplayServer::_window_changed: 0 rect: 454, 327, 1024, 600
 
ERROR: Condition "p_size < 0" is true. Returning: ERR_INVALID_PARAMETER
   at: resize (./core/templates/cowdata.h:252)
DisplayServer::_window_changed: 0 rect: 0, 58, 1920, 1142
DisplayServer::_create_window 1 want rect: 203, 94, 408, 227 got rect 203, 94, 408, 227
```

**Steps to reproduce:**
1. Create initial empty project.
2. Right click on file system or open main menu.
3. Godot Editor freezes.
4. When switch to other window, popup window remains up.

**Comment by Zireael07** [comment] 2020-12-02 09:12
Which version of NVIDIA drivers?

**Comment by o01eg** [comment] 2020-12-02 09:21
@Zireael07 x11-drivers/nvidia-drivers-455.28-r1

**Comment by Zireael07** [comment] 2020-12-02 09:29
455, eh? Duplicate of https://github.com/godotengine/godot/issues/41574 then - head there to see what you can do (Roll back to some older version or pass --single_window IIRC)

**Closed** 2020-12-02 09:46 UTC
