### ISSUE TITLE
"Object was deleted while awaiting a callback" when loading a complex resource or asset.

### ISSUE THREAD

**Issue by sabudum** [godotengine/godot#37009] opened 2020-03-12 17:09 UTC
**Godot version 3.2 stable or 3.2.1 stable**

**OS/Device including version: Windows 7 Pro SP1**

**Issue Description:**
When importing and selecting a complex resource, such as a skeleton with many bones, the debugger is flooded with the message:
"Object was deleted while awaiting a callback"

**Steps to reproduce:**
1 - Download example project and source
2 - Open said project
3 - Load any of the three files named ExportedSkeleton (escn, dae or fbx)
4 - Select the skeleton

**Reproduction Project:**

[Complex Asset Bug Example.zip](https://github.com/godotengine/godot/files/4325530/Complex.Asset.Bug.Example.zip)

**Comment by Calinou** [comment] 2020-03-12 20:28
Duplicate of #33355 (and possibly #35652).

**Closed by Calinou** 2020-03-12 20:28 UTC

**Comment by Xekkel** [comment] 2020-03-23 22:19
I'm very new to programming and learning Godot. I understand this issue will be addressed in 4.0 hopefully, but for now, is there a work around for this problem somewhere?

**Comment by Calinou** [comment] 2020-03-23 22:44
@Xekkel Not that I know of, sorry :slightly_frowning_face:
