### ISSUE TITLE
C#/Mono [Export] custom type variable

### ISSUE THREAD

**Issue by brmassa** [godotengine/godot#20388] opened 2018-07-23 20:11 UTC
Currently using [Export] with a custom Class produces nothing on the inspector.

```
[System.Serializable]
Class CustomData
{
 [Export]
 string valueString = "";
 [Export]
 int valueInt = 0;
}

Class CustomNode : Node
{
 [Export]
 CustomData valueData;
}
```

**Comment by neikeq** [comment] 2018-07-23 22:04
Only fields and properties from the script's class can be exported. This is the way Godot works by design.

**Comment by brmassa** [comment] 2018-07-24 13:46
:/ so there is not even an interest on implementing such useful feature?

**Comment by neikeq** [comment] 2018-07-25 00:50
I will see what can be done, but as I said this is the way Godot works by design, so I can't promise anything.

**Comment by NathanWarden** [comment] 2018-07-25 03:50
@neikeq I just think this issue should be re-opened for discussion in case someone else wants to tackle it, or for a time when you are able to look into it :)

I know you have a lot of other higher priority things on your plate regarding C#, so I wouldn't burden yourself with this right now. While I think this would be a *very* useful feature to have, there are still higher priority C# issues. I just don't think it's worth closing just yet.

**Comment by brmassa** [comment] 2018-07-25 04:59
I opened as a C#/Mono issue, but it would be useful for C++ and other
GDNative languages as well. Even GDScript maybe.

**Comment by aaronfranke** [comment] 2018-08-08 03:12
@vnen Do you think this is feasible to do with GDScript? It would be a useful feature.

**Comment by vnen** [comment] 2018-08-08 13:58
@aaronfranke you can already do, to a certain extent, since you can make scripts derived of Resource. But for non-resource it's harder to serialize. I'm not convinced Godot should care about those things, why not use Godot Resources?

**Comment by mysticfall** [comment] 2018-08-08 16:46
I don't think all custom type properties can be represented as resources. Sometimes, you may just want to group relevant values together and treat it as a single property.

For example, imagine you need to define rotational limitations for x, y, z axes in Euler angles. It'd be convenient if we can define a structure that contains minimum and maximum allowed angle and define such a limitation for each axis using that data type, like:

```csharp
public struct RotationalLimit {

    public float Min { get; }

    public float Max { get; }
    ...
}

[Export]
public RotationalLimit X { get; set; }

[Export]
public RotationalLimit Y { get; set; }

[Export]
public RotationalLimit Z { get; set; }
```
Using resource is not really an option for such an use case, and implementing a similar feature without a custom type would be more cumbersome and verbose.

Currently, Godot has a limited support for grouping properties (which doesn't work in C# at the moment) and such properties cannot be nested. In comparison, it's much more convenient in Unity, since you don't have to write any custom code to use a simple struct as a property type and you can easily nest them, so I hope we can also have a similar feature in future.

**Comment by neikeq** [comment] 2018-08-09 00:34
I misunderstood the issue for not reading carefully. So this is about making custom types from exported variables editable in the inspector. I wonder if this is possible with the new inspector. IIRC, the idea was that we could make custom controls for properties.

Can anyone confirm this? cc @reduz

**Comment by neikeq** [comment] 2018-08-09 01:00
Actually, this could be made to work with categories.

**Comment by brmassa** [comment] 2019-01-18 17:38
@neikeq so is it already possible? I would love to write some more complex structures and edit them in the editor. 

@vnen, as @mysticfall  pointed, It is not a static resource, but a living data holder. class Player, Enemy, etc, just containing data. It is important to separate pure data and presentation (Node)

**Comment by Trayani** [comment] 2019-11-24 20:25
It has been a while since the last comment. Has a final decision been made on it? I'm not asking "when", but rather "if at all" :).
This feature would be extremely useful, especially if applicable to any language.

**Comment by clayjohn** [comment] 2020-05-27 18:57
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!

**Closed by clayjohn** 2020-05-27 18:57 UTC
Labels: feature proposal, topic:core

**Comment by wmigor** [comment] 2021-03-27 10:27
Use Resource and this addon https://github.com/wmigor/godot-mono-custom-resource-register
