### ISSUE TITLE
blend shapes min/max always -1 to 1

### ISSUE THREAD

**Issue by lukostello** [godotengine/godot#49249] opened 2021-06-02 03:56 UTC
**Godot version:**
3.3 stable official

**OS/device including version:**
Windows 10

**Issue description:**
Blend shapes always have a min of -1 and max of 1 even when they didn't originally

**Steps to reproduce:**
Import mesh with various min/max I've included a blend file for your convenience:
[cube.zip](https://github.com/godotengine/godot/files/6581857/cube.zip)
After opening it notice how each blend shape has different min/maxes. Then after importing it notice how it is now all -1 min and 1 max. I don't think its related to how it imports though because I'm pretty sure it didn't use to do this and a mesh I had with a blend shape range of 0 to 1 worked fine and now that same mesh has a range of -1 to 1. 

**Minimal reproduction project:**
[blendshaperange_bug.zip](https://github.com/godotengine/godot/files/6581891/blendshaperange_bug.zip)

**Comment by lukostello** [comment] 2021-06-02 03:58
@fire this is probably related to work you're doing

**Comment by lukostello** [comment] 2021-06-02 13:32
Also just tried importing this: 
[outercorners.zip](https://github.com/godotengine/godot/files/6584857/outercorners.zip)
and none of the blendshapes imported accurately and a space appeared before all the numbers in the blend shape names i.e. "In0" became "In 0" the order changed too, that doesn't matter too much to me though

**Comment by fire** [comment] 2021-06-02 13:51
Investigating.

**Comment by fire** [comment] 2021-06-02 13:53
Are you aware of https://github.com/godotengine/godot/pull/45837 ?

**Comment by lukostello** [comment] 2021-06-02 15:30
So my 2nd comment is an unrelated issue that is probably from blender not godot. As per the original issue, it seems the gltf2 format doesn't import the range of the blendshape so I'd either have to take it up with the gltf2 source code or we could increase the min to -infinity to positive infinity, which seems like overkill to me. I'd recommend people just adjust their shape keys such that they work from 0 to 1... or apparently -1 to 1 in this case. 

Other than that the names being changed to "In0" to "In 0" might be a godot thing, as well as the ordering. But it doesn't matter much to me and is pretty low priority

**Comment by fire** [comment] 2021-06-02 18:48
@lyuma was looking into this.

**Comment by lyuma** [comment] 2021-06-02 19:36
I did some testing with this concept. TL;DR: it just led to more questions: what is expected of morphs outside -1 to 1?
I am using this patch:
```diff
diff --git a/scene/3d/mesh_instance_3d.cpp b/scene/3d/mesh_instance_3d.cpp
index c495f68890..1055028711 100644
--- a/scene/3d/mesh_instance_3d.cpp
+++ b/scene/3d/mesh_instance_3d.cpp
@@ -95,7 +95,7 @@ void MeshInstance3D::_get_property_list(List<PropertyInfo> *p_list) const {
 	ls.sort();
 
 	for (List<String>::Element *E = ls.front(); E; E = E->next()) {
-		p_list->push_back(PropertyInfo(Variant::FLOAT, E->get(), PROPERTY_HINT_RANGE, "-1,1,0.00001"));
+		p_list->push_back(PropertyInfo(Variant::FLOAT, E->get(), PROPERTY_HINT_RANGE, "-1,1,0.00001,or_lesser,or_greater"));
 	}
 
 	if (mesh.is_valid()) {

```
which would allow picking values in the inspector outside the range of -1 to 1. However, I ran into some rendering issues that lead me to believe blend shape extrapolation is ill-defined in general, especially regarding normals and tangents.

The real problem leading to the rendering issues is that the glTF importer is importing blend weights in NORMALIZED mode instead of RELATIVE:
```cpp
//ideally BLEND_SHAPE_MODE_RELATIVE since gltf2 stores in displacement
//but it could require a larger refactor?
import_mesh->set_blend_shape_mode(Mesh::BLEND_SHAPE_MODE_NORMALIZED);
...
for (int l = 0; l < size; l++) {
    if (l < max_idx) {
        w_varr[l] = r_varr[l] + r_src_varr[l];
    ...
```
The above comment was added in this commit from 2018: d9d6119b6efa09187c5a8f580d41c028987058c4

(Note related issue: https://github.com/godotengine/godot/issues/49005 - default blend weights in the gltf document are ignored in master branch. I used the test project from 49005 to test with because I already had it)

Most notably, blend values of 2.0 or higher seem to have weird lighting artifacts, possibly due to blend shape tangents. If the weight is exactly 2.0, it even appears that lighting is entirely ignored: perhaps the normals become 0. (I put a light of 1000 energy and saw this:
![light intensity 1000, blend weight=2 had no effect](https://user-images.githubusercontent.com/39946030/120538050-dd4b1f80-c39a-11eb-8b66-786ea85548b0.png)
at blend values below 1.99, it is really bright and blend values above 2.01 are just weird, like it's glossy but not bright.

In `servers/rendering/renderer_rd/shaders/skeleton.glsl` I found the following code which I believe to be the culprit... but again it just leads back to the rendering issues being caused by NORMALIZED mode instead of RELATIVE:
```glsl
		if (params.normalized_blend_shapes) {
			vertex = (1.0 - blend_total) * vertex;
			normal = (1.0 - blend_total) * normal;
			tangent.rgb = (1.0 - blend_total) * tangent.rgb;
		}
```

but it raises some interesting questions: what *should* be the behavior with blend shape normals when the value is very positive? how about very negative?

If I change the mesh to blend mode relative, the normals actually act as I expect for large values. However, blend weights below -1 lead to flipped normals in relative mode. It's clear even in relative mode, there remain unanswered questions.

Due to this discovery, I think this needs to be punted and possibly reviewed by the rendering team if it's interesting.

I'd honestly like to know what the glTF spec (or other implementations) say on this matter, if anything: blend shape extrapolation seems like a complex subject. I know that Unity doesn't support blend shape extrapolation at all (they do allow keyframe interpolation outside 0..1 but none of the importers support it)

**Comment by lukostello** [comment] 2021-06-04 02:17
interestingly while it displays "In 0" it is still "In0" in the code. Very peculiar.

**Comment by akien-mga** [comment] 2021-06-04 08:50
> interestingly while it displays "In 0" it is still "In0" in the code. Very peculiar.

Property names in the inspector are converted from `snake_case` to (an approximation of) natural language. `my_variable` becomes "My Variable", etc.

You can disable the "Capitalize Properties" if that's an annoyance (applies to all properties):
![Screenshot_20210604_105009](https://user-images.githubusercontent.com/4701338/120774546-abfd5b80-c522-11eb-806c-94dd15cc8943.png)

**Comment by fire** [comment] 2021-07-20 13:03
Thinking about this more, I think this is really a feature request since the system is working as designed. Thus the issue of being -1 to 1 can be closed.

**Comment by fire** [comment] 2021-07-27 05:27
Closing. Please create a feature proposal to explain your needs.

**Closed by fire** 2021-07-27 05:27 UTC
Labels: discussion, topic:3d, topic:import
