### ISSUE TITLE
PhysicalBone3D missing apply functions

### ISSUE THREAD

**Issue by CrezyDud** [godotengine/godot#58364] opened 2022-02-20 17:54 UTC
### Godot version

v4.0.alpha.custom_build [0217d44df]

### System information

Linux, Vulkan

### Issue description

![image](https://user-images.githubusercontent.com/84625713/154856607-a9734e00-c400-4114-8d81-54c18f8754b8.png)
the physicalbone3d is missing apply function to push it,
this could be fixed by making the physicalbone3d inherit rigid body 3d
or adding those functions manually.

### Steps to reproduce

a

**Comment by Calinou** [comment] 2022-02-20 21:18
Duplicate of https://github.com/godotengine/godot-proposals/issues/1951.

**Closed by Calinou** 2022-02-20 21:18 UTC

**Comment by CrezyDud** [comment] 2022-02-20 21:47
this isnt like proposal, its a bug that it is missing these features they should be added before 4.0, by addding them to physicalbone3d or by making physicalbone3d inherit rigidbody3d

**Comment by CrezyDud** [comment] 2022-02-20 22:59
@Calinou (sorry, i dont know if github pings when edeting messages)

**Comment by Calinou** [comment] 2022-02-20 23:07
> @Calinou (sorry, i dont know if github pings when edeting messages)

This isn't a bug, it's a missing feature :slightly_smiling_face:
