### ISSUE TITLE
Touching the screen should trigger mouseover event too

### ISSUE THREAD

**Issue by rraallvv** [godotengine/godot#1212] opened 2015-01-13 21:27 UTC
This is an issue I've fond in other engines too, for desktop platforms, the mouse position is constantly updated, therefore the mouseover event works right away.

For mobile devices the mouse position should be updated on touch events too, not only on touch dragged events. So that the UI behaves in a consistent way across desktop and mobile platforms.

To see this problem run the demo **_mousepick_test**_ on a mobile device, then touch the screen, the objects being touched change its color, now drag the touch, and the object is highlighted.

**Comment by akien-mga** [comment] 2016-03-24 13:06
A test project from #3590:

> Here is the example I'm using: https://www.dropbox.com/s/bngu083qctasmal/example.tar.gz?dl=0

> When a mouse button is pressed and held on desktop the viewport.get_mouse_pos() function returns the correct position. On mobile, touching and holding does not update get_mouse_position until the touch is over. I feel this is slightly inconsistent.

**Comment by DenisComtesse** [comment] 2016-08-23 16:31
I can confirm this. It's quite annoying, considering that otherwise it's very nice and easy to implement controls in Godot that work both with mouse and touch screens. But this inconsistency has given me a few headaches trying to work around it, so it would be fantastic if this could get fixed.

**Comment by vinod8990** [comment] 2016-08-28 12:49
I can confirm this.
We can test this by printing get_viewport().get_mouse_pos() inside the _update() 
Test on an android with debug enabled. We can see the print value changing drastically on the 4th or 5th so lines..

**Comment by DenisComtesse** [comment] 2017-01-09 22:28
Any ideas how to fix this, or any workarounds? I have a game where I need to get the mouse position when the mouse button is pressed, to determine where exactly the player has clicked. But I can't find a way to get this to work on touch screens (using Android), because most of the time the mouse position remains the same when I touch the screen. It is only updated while dragging. The weird thing is that buttons work perfectly. So obviously Godot knows where the touch event takes place, because otherwise Buttons wouldn't work.



I've attached a minimal test project: [TouchTest.zip](https://github.com/godotengine/godot/files/694797/TouchTest.zip) 
A Godot icon follows the mouse, and you can toggle a CheckButton. On Android, the icon follows only when you drag. But if you just toggle the button, the icon remains in place, but the the button is still toggled. There are exceptions, sometimes it does work - I guess this is when you accidentally drag a little bit while touching the screen.

This bug is driving me crazy ;-) I would be really thankful if anyone could look into that. I have no experience in engine development, but if there's anything else I can do to help solve it, or if you need more info, just ask.

**Comment by bojidar-bg** [comment] 2017-03-24 19:31
Can someone confirm that this issue is still present on ios?

**Comment by akien-mga** [comment] 2018-05-09 09:04
Is this still valid in the current master branch or Godot 3.0.x?

CC @RandomShaper

**Comment by AlexHolly** [comment] 2018-08-28 18:04
Is this related?
"entered" will only show when dragged
A simple touch will not count as entered.
tested on Android with https://github.com/godotengine/godot/commit/a651dbfe7e583267418a504597eaefb2d0da0ada
```
extends ColorRect

func _ready():
	connect("mouse_entered", self, "entered")
	connect("mouse_exited", self, "exited")
	

func exited():
	print("exited")

func entered():
	print("entered")
```

**Comment by Calinou** [comment] 2020-06-19 08:28
Can anyone reproduce this on Godot 3.2.1 or later?

**Comment by KoBeWi** [comment] 2020-12-10 23:55
Closing due to lack of update. Please comment if you can still reproduce this issue in the latest stable version of Godot.

**Closed by KoBeWi** 2020-12-10 23:55 UTC
Labels: enhancement, needs testing, platform:ios, topic:core
