### ISSUE TITLE
Scene dock receives input when it shouldn't

### ISSUE THREAD

**Issue by rgrams** [godotengine/godot#5374] opened 2016-06-23 12:14 UTC
**Operating system or device - Godot version:**
Windows 7. Recent 64-bit builds from https://archive.hugo.pro/godot/ and http://fixnum.org/godot/.

**Issue description & repro steps:**
The scene dock now seems to _always_ take input no matter what. In many contexts, Ctrl-A is "select all", but it's also "add node" for the scene dock. Previously, if you were in the script editor or editing a property in the inspector, Ctrl-A would only select all, now it selects all _and_ brings up the add node dialog box, which is obviously undesirable. I don't have a specific date when this started happening, the last build I used was from the 8th and it worked correctly, recent builds from the last few days have the issue. 

There are some contexts in which this happened before, but they weren't as much of a pain. If you open the "project settings" or the "editor settings" menu the scene dock will receive input while that is open, even if you're in the script editor. I'm sure there are other situations that I haven't tried.

**Comment by akien-mga** [comment] 2016-06-23 12:30
I believe this might be the same issue as #5174.

**Comment by Paulb23** [comment] 2016-06-23 12:58
See #5175 and #5304

**Comment by reduz** [comment] 2016-06-23 13:08
ctrl-a should add a node no matter where you are, but if the text editor
uses this, it should accept the event so the shortcut does not get it

**Comment by djrm** [comment] 2016-06-25 02:22
This has a weird behavior, it only happens the the first time CTRL+A is pressed after switching to Script mode, or after the godot window regains focus.

**Comment by akien-mga** [comment] 2016-06-28 05:38
Closing as duplicate of #5175 (which might be fixed now).

**Comment by akien-mga** [comment] 2016-06-28 05:51
Reopening as it doesn't seem fixed yet, while I think #5174 itself might be solved.

**Comment by neikeq** [comment] 2016-06-28 12:34
This bug is the same as #4856. That issue refers to MenuButton's menu and not ToolButton, but the cause is the same.

**Comment by neikeq** [comment] 2016-06-28 13:45
Ok, the cause of this bug is that the shortcut for the "New Node" button is being added to the button [here](https://github.com/godotengine/godot/blob/ba5bc57816999804e3c392e9d1f94b528baa8c18/tools/editor/scene_tree_dock.cpp#L1853) while being manually handled [here](https://github.com/godotengine/godot/blob/ba5bc57816999804e3c392e9d1f94b528baa8c18/tools/editor/scene_tree_dock.cpp#L56-L58) too. The reason to handle it manually is to ensure the event is `pressed` and not `echo`, since `BaseButton` doesn't check that. The reason the shortcut is still added to the button is probably to display the hotkey in its tooltip, but that makes handling it manually completely useless since the button will also handle the event even if it's `echo` or not `pressed`. 

This is the same issue I am facing in #5200 and the following are the possible solutions I proposed:

- Extending ShortCut to check if the event is pressed and/or echo.
- Add a flag to BaseButton to disable the event handling while still keeping the ShortCut.

@reduz We were discussing this on irc a week ago and you seemed in favour of adding the flag to BaseButton. Should I make a PR?

**Comment by reduz** [comment] 2016-07-01 15:03
Ah I just fixed this via ec94dd7eeebb218c51baedb1e63c02e77f8a2c9a , but it was failing due to BaseButton also using the button release event to exec the shortcut, not sure if everything else is related but closing this as it's now fixed.

**Closed by reduz** 2016-07-01 15:03 UTC
Labels: bug, topic:editor
