### ISSUE TITLE
Mixamo animation without skin not converted into skeleton3d in Godot 4

### ISSUE THREAD

**Issue by ooo-mmm** [godotengine/godot#62275] opened 2022-06-21 11:47 UTC
### Godot version

4.0 alpha 10

### System information

Windows 11, Vulkan mobile, GPU: nvidia 1050ti

### Issue description

When we import animations from mixamo without skin feature selected, then Godot 4 is not converting the fbx into a skeleton3d instead all the bones appear as node3d in the hierarchy. The import of same model is working fine in Godot 3.4.4
 
4.0alpha10
![image](https://user-images.githubusercontent.com/31175327/174791711-e4e45a13-a5ca-46da-80ce-e52fef5425b4.png)

3.4.4mono
![image](https://user-images.githubusercontent.com/31175327/174791825-c613ac94-ffe8-44b3-9bc2-5bb6f8281603.png)

### Steps to reproduce

Import any model from mixamo.com without skin.

**Comment by and-rad** [comment] 2022-06-21 12:15
Related to and likely a duplicate of #60854 .

It's a limitation of the FBX2gltf tool that you're using when importing FBX into Godot. If there is no mesh, there are no skins and without skin information Godot is not able to build a skeleton from the nodes in the GLTF file.

**Comment by ooo-mmm** [comment] 2022-06-21 13:15
Importing from blender works, also Collade without skins works but with skin collade skeleton is not deforming the mesh
![image](https://user-images.githubusercontent.com/31175327/174808277-9d267851-c37e-46b2-841c-7275ac675822.png)

**Comment by lyuma** [comment] 2022-06-21 23:36
> Related to and likely a duplicate of #60854 .
> 
> It's a limitation of the FBX2gltf tool that you're using when importing FBX into Godot. If there is no mesh, there are no skins and without skin information Godot is not able to build a skeleton from the nodes in the GLTF file.

I believe this is a missing feature in FBX2glTF.

FBX knows that the nodes are part of a skeleton because they have an FbxSkeleton attached. Hence, FBX2glTF should detect this case and create a dummy glTF skin like discussed in this blender gltf io issue here:
https://github.com/KhronosGroup/glTF-Blender-IO/issues/822

(This functionality that allows you to convert in Blender is therefore actually quite new, in Blender 3.2 )

Regarding Collada, please file as separate issue about this. It's hard to interpret this given only one sentence. In the new issue, please explain what you did to produce the collada file, and the file or a reproduction project, and explain what is wrong.

**Comment by ooo-mmm** [comment] 2022-06-22 03:21
I think there is some issue with my .dae file, also I overcame the issues by using .blend integration directly in Godot 4

**Comment by akien-mga** [comment] 2022-07-17 13:51
If this is specific to Collada, can you attach files which are problematic so we can test?

**Comment by ooo-mmm** [comment] 2022-07-17 13:59
Hi I dont have that exact file. But it was just a character animation default export from mixamo directly into Godot

**Comment by fire** [comment] 2023-08-29 21:09
@lyuma did we add this feature to Godot Engine 4?

**Closed** 2024-02-27 09:28 UTC
Labels: bug, topic:import, topic:animation, topic:3d
