### ISSUE TITLE
PoolByteArray function request.

### ISSUE THREAD

**Issue by OlexiyKravchuk** [godotengine/godot#28692] opened 2019-05-05 01:23 UTC
In PoolByteArray, there are not enough functions, recently I have been working a lot with this, and I constantly need to pack different types of data in PoolByteArray, so that after that I can remove them in parts, for this, I first wrote my functions. But it is cumbersome and not very convenient. Therefore, to improve this, I began to create the File object, and use it as an intermediary, because it has almost all the functions I need, like get / store_8 (), _ 16, _32, _64, _line (), etc. ...
But in the way to use the file as an intermediary there is a big drawback, it is much slower because of the need to save and load data on the disk and back.
 At the same time, I noticed that the File itself ultimately converts everything created into PoolByteArray, for saving. Therefore, it seems to me that it would be much more convenient if PoolByteArray itself had all the necessary functions for faster work with data and was independent of the disk speed delays.

**Comment by Zylann** [comment] 2019-05-06 03:45
If what you need is read and write various primitives from a byte array, I think a stream object would be more appropriate than putting it all in `PoolByteArray` (especially since the latter has no concept of current read position). `StreamPeerBuffer` is very close to what you seek and has all functions you need, however it relates to networking so I'm not sure it exactly does what you expect.

**Comment by OlexiyKravchuk** [comment] 2019-05-07 21:58
I know about this option, it is practically not applicable in my tasks, the ego is intended to send embedded data over the network in a specific order, while the file is much more convenient and expedient.
But still, it’s not the same thing as using PoolByteArray instead of circumventing obstacles, and this request is about adding non-enough functions in PoolByteArray, and not looking for workarounds that I’ve already trodden on and reinventing the wheels with crutches.

**Comment by Zylann** [comment] 2019-05-08 00:08
That's why I was suggesting to add a new pure data `Stream` object which would allow to read and write to `PoolByteArrays`, just like you described (it's done that way too in C#). It can't directly be `PoolByteArray` because for `get / store_8 (), _ 16, _32, _64, _line ()` etc functions to exist, there is need for a current read position and write positions, which a `PoolByteArray` doesn't have (and doesn't need to have, it's not its job, it would be considered bloat).

**Comment by Faless** [comment] 2019-06-24 07:18
> That's why I was suggesting to add a new pure data `Stream` object which would allow to read and write to `PoolByteArrays`

Isn't that what `StreamPeerBuffer` already does? I don't get what the problem is with `StreamPeerBuffer`. It has all the needed functions. What am I missing?

> But still, it’s not the same thing as using PoolByteArray

What is the difference? I don't get it. You use `StreamPeerBuffer` to write to `PoolByteArray`. Then read the `data_array` property.

**Comment by Zylann** [comment] 2019-06-24 12:52
> Isn't that what StreamPeerBuffer already does?

Yeah, I think it does that. But, maybe people don't find `StreamPeerBuffer` because:
1) It's named after a network use case
2) The functions mentionned before are not shown on it but are actually in the base class
3) Due to being network-related it also processes the data a little bit which might not be wanted

**Comment by Calinou** [comment] 2021-08-08 16:51
This was implemented by https://github.com/godotengine/godot/pull/47761, closing.

**Closed by Calinou** 2021-08-08 16:51 UTC
Labels: enhancement, topic:core
