### ISSUE TITLE
Attempting to drag unfocused game window only focuses window, not drag

### ISSUE THREAD

**Issue by Goldenlion5648** [godotengine/godot#99937] opened 2024-12-02 18:57 UTC
### Tested versions

Godot v4.3.stable.official [77dcf97d8]

### System information

Godot v4.3.stable - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1050 Ti (NVIDIA; 31.0.15.5123) - Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 Threads)

### Issue description

When starting a game, then un-focusing the game window, and attempting to reposition the window while it is unfocused, the window does not get dragged. It only refocuses, and requires clicking again to start dragging. This is not the case for other windows programs (i.e. file explorer)

### Steps to reproduce

1. Start the engine (or a game)
2. Click outside the engine or game window so that it is not focused
3. Attempt to reposition the window by dragging the window's titlebar
4. (Notice the window does not get dragged only focused)
5. Upon clicking and dragging again, the window will be able to be repositioned (this step is not wanted, but is the current behavior)

### Minimal reproduction project (MRP)

N/A

**Comment by tetrapod00** [comment] 2024-12-03 08:23
Very likely a duplicate of https://github.com/godotengine/godot/issues/95577, which has an open PR to fix https://github.com/godotengine/godot/pull/95606.

Can you try to reproduce this in 4.2.2 (with a fresh project)?

There were also several other issues related to focus on Windows that have been fixed during 4.4. Can you test the last 4.4 dev version and see if this still happens?

**Comment by Goldenlion5648** [comment] 2024-12-03 14:58
It does not happen in 4.2.2. In 4.4dev5, the issue still occurs

**Comment by tetrapod00** [comment] 2024-12-03 19:35
Seems like a duplicate, then. Consolidating into https://github.com/godotengine/godot/issues/95577. Thanks for reporting!

**Closed by tetrapod00** 2024-12-03 19:35 UTC
Labels: bug, needs testing
