### ISSUE TITLE
Black Box when mouse over on non-open tab in Editor

### ISSUE THREAD

**Issue by charro** [godotengine/godot#70044] opened 2022-12-14 04:50 UTC
### Godot version

v4.0.beta8.official [45cac42c0]

### System information

Ubuntu  20.04.5 LTS  - Nvidia GeForce GTX 960M - Vulkan

### Issue description

When mouse over a tab in the Game Editor, looks like instead of showing a hint something is broken and it shows a black box instead:

![Screenshot from 2022-12-13 23-26-01](https://user-images.githubusercontent.com/2556531/207506763-28fbb282-9e5a-4a23-a4c1-f80e6c85c58f.png)

![Screenshot from 2022-12-13 23-26-13](https://user-images.githubusercontent.com/2556531/207506792-8e8eca24-869c-4ea7-9b9e-d5d5daeb109d.png)

### Steps to reproduce

* Create new project
* Save scene, give it any name, this is important, only happens when is saved
* Click in new scene (plus + sign on tabs), it will create a new tab
* Once on the new scene opened, mouse over the previous tab with the first created and just saved scene
* You'll see the black box

### Minimal reproduction project

N/A

**Comment by Chaosus** [comment] 2022-12-14 10:56
> You'll see the black box

I think it's called scene preview. Sometimes it's showed incorrectly.

**Comment by gb-aviation** [comment] 2022-12-15 11:40
这个应该是场景预览，被预览的场景中有可见的东西时鼠标悬浮上去就可以在小窗口中看到，如果原场景的节点不是可显示的就是个小黑框。

**Comment by Calinou** [comment] 2022-12-15 18:40
Duplicate of https://github.com/godotengine/godot/issues/30439 (same cause).

**Closed by Calinou** 2022-12-15 18:40 UTC
Labels: bug, topic:editor
