### ISSUE TITLE
Non-Exported C# script properties are sometimes serialized to scenes

### ISSUE THREAD

**Issue by alexdlm** [godotengine/godot#77303] opened 2023-05-21 11:00 UTC
### Godot version

4.1.0-dev2 (and dev1)

### System information

Windows 11 / Dotnet 7.0.202

### Issue description

There is some scenario where scenes save, and within them non-exported C# properties are getting serialized. These are often objects, and so I end up with a line like the below against a Node, which looks like some serialized Object model. This also survives deserialization which is problematic because most of the time these are expected to be null (because they are not exported!).

eg saved under a Node with a `private VBoxContainer ItemContainer {get; set;}` property, no `[Export]` attribute.
```
ItemContainer = Object(VBoxContainer,"_import_path":NodePath(""),"unique_name_in_owner":true,"process_mode":0,"process_priority":0,"editor_description":"","visible":true,"modulate":Color(1, 1, 1, 1),"self_modulate":Color(1, 1, 1, 1),"show_behind_parent":false,"top_level":false,"clip_children":0,"light_mask":1,"visibility_layer":1,"z_index":0,"z_as_relative":true,"y_sort_enabled":false,"texture_filter":0,"texture_repeat":0,"material":null,"use_parent_material":false,"clip_contents":false,"custom_minimum_size":Vector2(0, 0),"layout_direction":0,"layout_mode":2,"size_flags_horizontal":3,"size_flags_vertical":3,"size_flags_stretch_ratio":1.0,"auto_translate":true,"localize_numeral_system":true,"tooltip_text":"","focus_neighbor_left":NodePath(""),"focus_neighbor_top":NodePath(""),"focus_neighbor_right":NodePath(""),"focus_neighbor_bottom":NodePath(""),"focus_next":NodePath(""),"focus_previous":NodePath(""),"focus_mode":0,"mouse_filter":1,"mouse_force_pass_scroll_events":true,"mouse_default_cursor_shape":0,"shortcut_context":null,"theme":null,"theme_type_variation":&"","alignment":0,"script":null)
```

### Steps to reproduce

I have not been able to reproduce on a simple project yet, so it may be a unique combination on my more complex project, however I have not managed to narrow it down yet either by disabling things. It doesn't happen when I want it to 😆 It is definitely not every save!

Some possible factors:
1. It seems to happen more often when hitting 'Save All Scenes', but again, that is not reliable.
2. It _might_ be limited to Child scenes, with [Tool] scripts on their root, but that's mostly what I'm working on at the moment so I can't say for sure. I get the feeling it might be when I have a number of these inter-dependent scenes open.
3. I never had this on 4.0.x builds, with no obvious project difference since upgrading

### Minimal reproduction project

If I can actually get a repro I will post one.

**Comment by alexdlm** [comment] 2023-05-21 11:00
If there's not something obvious, I'm happy to keep debugging with some assistance:
* Where is the relevant serialization code in C++, there were a few candidates but I didn't narrow it down. With some locations to check I can set some breakpoints and catch it in the act.
* Why are these properties also in the ScriptSerialization generated C# code? This looks to only be called by [CSharpLanguage::reload_assemblies](https://github.com/godotengine/godot/blob/809a98216267f3066b9fec2f02b2042bdc9d3e0d/modules/mono/csharp_script.cpp#L839) but looks immediately interesting. I assume reload_assemblies is attempting to maintain editor state.
* Why does the C# ScriptProperties generator enumerate private fields & properties, particularly if they are not exported. I see they do list with the exported flag to false, but why does anything need to know about them?

**Comment by Faradax** [comment] 2023-11-19 22:23
I ran into this issue and was able to create a reliable reproduction setup:

---

[Bug_Serialization.zip](https://github.com/godotengine/godot/files/13404752/Bug_Serialization.zip)

Reproduction steps:
- Build the project once
- Open SceneWithTool in the editor
- Change anything in the Code - Adding a whitespace somethere is enough
- Build the project in the editor (ALT+B)

Notice how on any subsequent builds, these two lines show up in the output:
> Get - This should not happen in Editor
> Set - This should not happen in Editor
They are logged when the getter and setter of `NonExportedBool` are called.

Notice how when the SceneWithTool is closed, nothing is logged on build.
You can also create and open other scenes that contain instances of SceneWithTool - in that case, for each instance in any of the open scenes, the log lines are written.

---
In my real project, this poses a real issue. There, Godot tried to serialize a Property that relies on state that is not initialized in the editor, and consequently throws a NullReferenceException. As a result, the scene instances are not serialized properly and lose their state, breaking big parts of all opened levels.

**Comment by tomsep** [comment] 2024-01-25 20:27
If restoring of non-exported properties is required then would it make sense to only do this on properties that are explicitly marked to be restored? For example:
```
[RestoreOnRebuild]
public float Power { get; set; }
```
Now it is quite problematic that all properties are forcefully get and set on rebuild. Any side effects the properties have is also forced on rebuild.

**Comment by raulsntos** [comment] 2024-01-26 03:53
> Why does the C# ScriptProperties generator enumerate private fields & properties, particularly if they are not exported. I see they do list with the exported flag to false, but why does anything need to know about them?

@alexdlm Script members have to be "exposed" somehow so they can be used from interop (e.g.: GDScript). The exported flag only means that the `[Export]` attribute is used in the field/property and that applies the default [usage flags](https://docs.godotengine.org/en/stable/classes/class_@globalscope.html#enum-globalscope-propertyusageflags) to it:

- `PROPERTY_USAGE_STORAGE` means the property will be serialized in the scene file.
- `PROPERTY_USAGE_EDITOR` means the property will be shown in the inspector.

But even when a field/property is not exported, it still needs to be exposed, this is also what GDScript does. These properties don't have the usage flags previously mentioned, but still have the `PROPERTY_USAGE_SCRIPT_VARIABLE` flag.

However, your original report says that properties without the `[Export]` attribute are being serialized and that's a bug because those properties should not have the `PROPERTY_USAGE_STORAGE` flag:

https://github.com/godotengine/godot/blob/5034478611697358f4e135c69f364ef6d8cd54dc/modules/mono/editor/Godot.NET.Sdk/Godot.SourceGenerators/ScriptPropertiesGenerator.cs#L463-L467

Please, upload a MRP if you are able to reproduce this behavior.

> Where is the relevant serialization code in C++, there were a few candidates but I didn't narrow it down. With some locations to check I can set some breakpoints and catch it in the act.

I believe that would be in `packed_scene.cpp`, but as you can see it's ignoring all the properties that don't have the `PROPERTY_USAGE_STORAGE` flag.

https://github.com/godotengine/godot/blob/5034478611697358f4e135c69f364ef6d8cd54dc/scene/resources/packed_scene.cpp#L663-L666

---

@Faradax In your MRP you are using a `[Tool]` script. Tool scripts are run in the editor as documented in the [_Running code in the editor_](https://docs.godotengine.org/en/stable/tutorials/plugins/running_code_in_the_editor.html) documentation page. This obviously means that you can break stuff when this code executes but that's expected.

If you don't want the script to run in the editor at all, don't use the `[Tool]` attribute. If you only want to stop parts of your script from executing use the `Engine.IsEditorHint()` method as suggested in the documentation.

```csharp
public bool NonExportedBool
{
    get
    {
        if (!Engine.IsEditorHint())
            GD.Print("Get - This should not happen in Editor");
        return _nonExportedBool;
    }
    set
    {
        if (!Engine.IsEditorHint())
            GD.Print("Set - This should not happen in Editor");
        _nonExportedBool = value;
    }
}
```

**Comment by raulsntos** [comment] 2024-07-28 01:58
Closing as per the above comment. If anyone is still able to reproduce this issue, please open a new issue and make sure to upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/4c1f11944ebfe1204f21c6ac488c7a2294e1d520/CONTRIBUTING.md#provide-a-simple-example-project) to make it easier to troubleshoot.

**Closed by raulsntos** 2024-07-28 01:58 UTC
Labels: bug, topic:dotnet, regression
