### ISSUE TITLE
RichTextLabel does not fit content height

### ISSUE THREAD

**Issue by DozyBird** [godotengine/godot#57245] opened 2022-01-26 08:58 UTC
### Godot version

v4.0.alpha.calinou [b25c7fef0]

### System information

Ubuntu 21.10, Windows 11

### Issue description

RichTextLabel has no min_rect_size, even when it contains text and fit_content_height is enabled.

![image2](https://user-images.githubusercontent.com/66665185/151132774-e6ccf85d-53e8-435f-8d1e-39cc311f3848.png)

### Steps to reproduce

1. Create a RichTextLabel
2. Write text into it
3. Enable fit_content_height

### Minimal reproduction project

[test.zip](https://github.com/godotengine/godot/files/7940225/test.zip)

**Comment by akien-mga** [comment] 2022-01-26 09:52
This sounds like a duplicate of #18260, and I don't see how it could be platform specific. Are you sure that you tested the same scene on Windows, i.e. with a RichTextLabel in a VBoxContainer?

**Comment by DozyBird** [comment] 2022-01-26 17:38
My mistake, this appears to affect Windows as well. I updated my Windows build to b25c7fef0

**Closed** 2022-01-27 11:49 UTC
Labels: bug, topic:gui

**Comment by DozyBird** [comment] 2022-01-27 22:33
So this bug still occurs with default settings. I figured out that it's because a change in behavior that may not be a bug. But it's certainly not obvious.

https://github.com/bruvzg/godot/blob/0014f0233a8932dda1c47bcad7d3e79112332e38/scene/gui/rich_text_label.cpp#L4069
`total_height = main->lines[main->lines.size() - 1].offset.y + main->lines[main->lines.size() - 1].text_buf->get_size().y * main->lines[main->lines.size() - 1].text_buf->get_line_count() * get_theme_constant(SNAME("line_separation"));`

Commit 268bab0 now multiplies the content height by the theme's "line_separation". But "line_separation" is by default 0. So unless the user modifies their theme or adds a theme_override, fit_content_height will never work.

**Comment by bruvzg** [comment] 2022-01-27 22:45
This is a typo, should be `offset + get_size + count * lsep` not `offset + get_size * count * lsep` (same as the other places it's done).
