### ISSUE TITLE
Godot blend/GLTF import is not compatible with Blender 4.2

### ISSUE THREAD

**Issue by demolke** [godotengine/godot#93997] opened 2024-07-06 12:12 UTC
### Tested versions

- reproducible on any version talking to Blender 4.2

### System information

not relevant

### Issue description

Blender commit https://projects.blender.org/blender/blender/commit/0f0a8df8a922cdb0796c0b3fdbdc5c669efb3059 which is landing in 4.2 deprecated `vertex_colors` GLTF property, thus breaking all Godot Blender integration. All `.blend` imports silently fail with no indication why - nothing printed to the console/stderr/...

The underlying error is

```
Python: Traceback (most recent call last):
  File "blender-4.2.0-beta+v42.c94bed9afa0d-windows.amd64-release\4.2\scripts\modules\bpy\ops.py", line 109, in __call__
    ret = _op_call(self.idname_py(), kw)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Converting py args to operator properties:: keyword "export_colors" unrecognized
```

### Steps to reproduce

1. get blender 4.2
2. point godot to it
3. observe all .blend imports fail

### Minimal reproduction project (MRP)

For example this one https://github.com/godotengine/godot/files/12903509/vertexcolorexample.zip from https://github.com/godotengine/godot/issues/83310

**Comment by passivestar** [comment] 2024-07-06 18:43
possibly a duplicate of https://github.com/godotengine/godot/issues/92365

**Comment by akien-mga** [comment] 2024-07-07 08:36
Indeed, duplicate of #92365.

**Closed by akien-mga** 2024-07-07 08:36 UTC
Labels: enhancement, topic:import, topic:3d
