### ISSUE TITLE
Editor freezes when closing on Mac (M1 Max) - Godot v4.2.beta6 mono

### ISSUE THREAD

**Issue by dnllowe** [godotengine/godot#84918] opened 2023-11-14 23:49 UTC
### Godot version

Godot v4.2.beta6.mono

### System information

macOS 13.4.0 - Vulkan (Forward+) - integrated Apple M1 Max - Apple M1 Max (10 Threads)

### Issue description

Whether closing from the menu (Godot -> Quit Godot), the shortcut (CMD + Q), or closing the window using the standard red "X", the editor will freeze indefinitely instead of closing. In order to close the Editor, you must right click on the icon from the Dock and choose "Force Quit".

I can provide my system logs if it would help, but I'm not sure if there's much insight to glean from them.

### Steps to reproduce

This will happen even from a new / blank project. Simply open the Godot 4.2 beta6 editor, create a new project or load an existing one, and attempt to close it.

https://github.com/godotengine/godot/assets/18432482/c391d0c7-0a59-4312-8bf2-a6e94cf3cf41

### Minimal reproduction project

N/A

**Comment by dogboydog** [comment] 2023-11-15 00:44
Duplicate of https://github.com/godotengine/godot/issues/84728 ?

**Comment by dnllowe** [comment] 2023-11-15 00:55
Definitely looks related, but maybe not resolved specifically for MacOS?

**Comment by dogboydog** [comment] 2023-11-15 00:59
The issue was closed after beta 6 was already released, so that's probably while you're still seeing the issue.

**Comment by dnllowe** [comment] 2023-11-15 01:02
Ah, got it -- that makes sense

**Closed** 2023-11-15 01:02 UTC
