### ISSUE TITLE
Kinematic body move_and_slide_with_snap doesn't stop on slopes with stop_on_slope

### ISSUE THREAD

**Issue by nezvers** [godotengine/godot#37208] opened 2020-03-21 13:32 UTC
**Godot version:**
3.2

**OS/device including version:**
win 10

**Issue description:**
No matter on the setup player is still sliding down even with ZERO velocity. I tried to use only returned Y value and applied gravity only in the air, that doesn't help.
Enabling stop_on_slope only reduces sliding speed. And reacts to slopes the same way as when move_and_slide returns all 3 axis.
Meanwhile, move_and_slide stops on slopes.

**Steps to reproduce:**
Gravity only when not on the floor.
Snap length only when on the floor.

**Minimal reproduction project:**
FPS controller with exported values for debugging needed parameters and configuration.
[3D_FPS_controller.zip](https://github.com/godotengine/godot/files/4362956/3D_FPS_controller.zip)

**Comment by mss1451** [comment] 2020-03-22 01:44
I was having the same issue. I think the problem is here in `physics_body.cpp`:
```
if (p_stop_on_slope) {
	// move and collide may stray the object a bit because of pre un-stucking,
	// so only ensure that motion happens on floor direction in this case.
	col.travel = col.travel.project(p_up_direction);
}
```
Calculated motion still results in stuck object so the next time the function is called, the object will stray. I have my solution but it is multi-level and a bit dirty. I modify the collision result in `move_and_collide`. Just added one more parameter `prevent_stray`.
```
...
if (colliding) {
	if (p_motion != Vector3() && prevent_stray) {
		Vector3 unstuck_vector = result.motion - p_motion;
		real_t inner_angle = acos(-p_motion.normalized().dot(unstuck_vector.normalized()));
		real_t trimmed_length = unstuck_vector.length() / cos(inner_angle);
		result.motion = p_motion * (1.0 - trimmed_length / p_motion.length());
        }
...
}
```
This way object will never go in a direction other than `p_motion`. For `move_and_slide`, `prevent_stray` should be false otherwise the object won't slide. I have observed that the sliding behavior relies on un-stucking. Not on `motion = motion.slide(collision.normal);`

**Comment by akien-mga** [comment] 2020-03-22 08:27
CC @madmiraal - I'm fairly sure this has been discussed in other issues, you might know which.

**Comment by madmiraal** [comment] 2020-03-22 10:18
This is a duplicate of #34117.

As elaborated on [here](https://github.com/godotengine/godot/issues/34117#issuecomment-562841402), `stop_on_slope` only works when the `x` and `z` components of the `velocity` vector passed to `move_and_slide()` or `move_and_slide_with_snap()` functions are zero. In the example project provided, `x` and `z` never reach zero, because the amount they are reduced in the linear_interpolation step:
```velocity = velocity.linear_interpolate(direction * speed, acceleration * delta)```
is less than the amount they are increased by the slide down the slope.

The solution is to either use a `RayShape` `CollisionShape`, or snap the `x` and `z` values to zero when they drop below a minimum level.

**Closed** 2020-03-22 10:21 UTC
Labels: topic:physics
