### ISSUE TITLE
KinematicBody2D in platformer demo slides down when standing on slopes when facing one direction, not the other

### ISSUE THREAD

**Issue by louisVottero** [godotengine/godot#10983] opened 2017-09-04 22:40 UTC
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
latest godot built today

**Issue description:**
Open the platformer demo.  Stand facing right on a platform that slopes down towards the right.  The character will keep walking down the slope instead of just standing on the slope.

**Link to minimal example project:**

**Comment by HummusSamurai** [comment] 2017-09-05 09:26
This is due to the move_and_slide() function.

The gravity force is being continuously applied when you're on the ground, but since you can't go directly downwards it makes you slide along the ramp.

This is an implementation issue and not an engine issue, and can go under https://github.com/godotengine/godot-demo-projects instead. The correct way to solve this would be to set gravity to 0 when the kinematic body is on the floor (which is checked through the is_onfloor() function that is already used in the script).

Please file and issue in the demo repository and I will do a PR tonight to fix it.

**Comment by louisVottero** [comment] 2017-09-05 10:50
This could be. However the character won't slide down the slope if he's facing up the slope.  However if he's facing down the slope he will slide down.    This feels like a bug with the kinematic solver?

**Comment by akien-mga** [comment] 2017-09-05 10:58
It's not clear in the initial post, is this about the 2D or 3D platformer?

**Comment by HummusSamurai** [comment] 2017-09-05 10:59
Regardless of whether it's in 2D or 3D, it is possibly because move_and_slide() attempts to slide forward, so if you're looking towards an upwards slope it would dissipate the force, but not vice versa.

It's not necessarily a bug but more of how kinematic bodies should behav;, if you want more accurate newtonian physics then the RigidBody (set to Character mode) would behave like you want it to.

If the kinematic body were to slide both upwards and downwards, it's movement might lose the essence of what "KinematicBody" is supposed to be: a body to controlled by the player or through script.

Again, I honestly don't think this should be changed in the engine, or else Kinematic Body and Rigid Body in Character mode would be indifferentiable.

**Comment by louisVottero** [comment] 2017-09-05 11:02
Kinematic Body 2D.  If its not a bug I apologize.  But it feels like something is off. Gravity should pull down the same on a body facing forward or backwards on a slope.

**Comment by HummusSamurai** [comment] 2017-09-05 11:04
@louisVottero This is true for Rigid Body but not for Kinematic Body, where you are expected to do physics yourself.

**Comment by reduz** [comment] 2017-09-05 11:10
I'm sorry but nothing can be done without a demo project

**Comment by louisVottero** [comment] 2017-09-05 12:57
This would be the demo project. 
https://github.com/godotengine/godot-demo-projects/tree/master/2d/platformer

**Comment by eon-s** [comment] 2017-09-06 01:00
I think the OP refers to configuration problem specific to the platformer.
The min slope velocity does not have a drag so it will keep sliding down (gravity+initial motion) until the base of the slope and that is the expected behaviour.

---------------

There is another issue, though, if the min slope velocity is increased to stop the body from sliding down slopes, it can't walk on normal floor.
A way to solve this could be not applying the min slope velocity if collision normal is the close to the floor normal (parameter).

---------------

I agree with @HummusSamurai that the auto-sliding down slopes should be removed but keeping a way that prevents jumping when going down slopes.

_And I insist in that this complex character controller behaviour should be in its own class (maybe even derived from RigidBody2D in kinematic mode instead)._

**Comment by reduz** [comment] 2017-09-06 11:47
Ah I see, the problem is not so much the min slope velocity as the deacceleration setting of the character script, should be adjusted

**Comment by reduz** [comment] 2017-11-06 15:33
If anyone wants to try tweaking the script to avoid this situation, feel welcome

**Comment by dherring** [comment] 2017-12-10 17:49
Having played through the demo, I don't think this is a bug.  It appears to be an intentional feature with a slightly surprising behavior.  Best test location is the bit hill on the bottom-right.

The feature is that your character is slower when walking up slopes and faster when walking down slopes.  The surprising behavior is that when you are "sliding" down a slope, the motion continues until you turn around or reach the bottom.  Turning isn't instant, but rather takes some "effort" (time and distance).  If you are stopped while facing uphill, a quick tap can turn you downhill without starting to slide.

Overall, I think this is a good game mechanic and should be kept.


If you do want to suppress the sliding, the task is a bit complicated by the interaction between move_and_slide and the lerp on linear_vel.x.  The return value from move_and_slide is needed for inertia in jumps.  The lerp slowly increases the velocity, and increasing SLOPE_SLIDE_STOP will clamp the first movement lerp to zero unless jumping.  Playing with GRAVITY_VEC or FLOOR_NORMAL makes things floaty or super-heavy before fixing the problem.

The best option I found was to simulate a little sliding friction as follows.

```
diff --git a/2d/platformer/player.gd b/2d/platformer/player.gd
index 5919e72..f73241f 100644
--- a/2d/platformer/player.gd
+++ b/2d/platformer/player.gd
@@ -50,6 +50,12 @@ func _physics_process(delta):
        target_speed *= WALK_SPEED
        linear_vel.x = lerp(linear_vel.x, target_speed, 0.1)
 
+ # add some sliding friction
+ if on_floor and target_speed == 0:
+         # 0.6 and lower quickly stops the sliding.
+         # 0.7 and higher slows it but does not stop.
+         linear_vel.x=0.6*linear_vel.x
+
        # Jumping
        if on_floor and Input.is_action_just_pressed("jump"):
                linear_vel.y = -JUMP_SPEED
```

**Comment by podpathos** [comment] 2017-12-18 09:38
It's not a bug it's design.
But I disagree with dherring that difference in sliding speed is mechanic that should be kept, becouse custom physics of KinematicBody should not by default aproximate "real" physics (different speeds of climbing and decending slopes), it should be custom, if not, it defeats the purpose of custom physics, we already have Rigid body for "real" physics.
I have noticed that many people have same isue (plus jumping when change occurs from climbing slope to decending slope) making old school platformer and no solution. In old school platformers character should be stick to ground level no mater of change from one slope angle to antother, and without "real" physics sliding by default. It would be nice if someone from community would share working example of oldschool platformer that works as it should work, if it is possible to make one with KinematicBody and not with completely custom code/collision detection algorithms (raycast etc.).
At least it would be nice to know is KinematicBody way to go in making oldschool platoformers wich dont have all this issues, or to go with completely custom physics/collision detection.
Thanks!

**Comment by eon-s** [comment] 2017-12-18 11:38
@podpathos the old way of controlling collisions using `move_and_collide` is still available.

**Comment by akien-mga** [comment] 2018-01-08 12:08
We have now entered release freeze for Godot 3.0 and want to focus only on release critical issues for that milestone. Therefore, we're moving this issue to the 3.1 milestone, though a fix may be made available for a 3.0.x maintenance release after it has been tested in the master branch during 3.1 development. If you consider that this issue is critical enough to warrant blocking the 3.0 release until fixed, please comment so that we can assess it more in-depth.

**Comment by KoBeWi** [comment] 2019-06-19 11:58
So, since the issue was created, physics of kinematic bodies changed and demo changed too (I remembered it differently than it is now) and the original issue might be fixed now.

But if it's about removing the sliding effect, the new KinematicBody features in 3.1 would be helpful to achieve that (i.e. `move_and_slide_with_snap` and ray colliders).

**Comment by madmiraal** [comment] 2020-06-04 12:51
Fixed with https://github.com/godotengine/godot-demo-projects/pull/405.

**Closed** 2020-06-04 12:52 UTC
Labels: discussion, enhancement, hero wanted!, topic:physics
