### ISSUE TITLE
Item_list_ensure_current_is_visible scrolls the scrolling but the icons does not move

### ISSUE THREAD

**Issue by DadangoGodotNoob** [godotengine/godot#7816] opened 2017-02-15 19:26 UTC
**Operating system or device - Godot version:**
Windows 10
Godot V 2.1

**Issue description:**

Item_list_ensure_current_is_visible scrolls the scrolling but the icons does not move. This might be intentional? I wouldn't know 🔢 first bug report

**Steps to reproduce:**
my code looks like this for the itemlist : ("inventory" being the itemlist)
```gdscript
if inventory.is_selected(i) and inventory.get_item_metadata(i).size() == 10: #
    inventory.ensure_current_is_visible()
    highest_value_dice = inventory.get_item_metadata(i)[2]
    lowest_value_dice = inventory.get_item_metadata(i)[1]
    attack_range = inventory.get_item_metadata(i)[9]
    now_wielding = inventory.get_item_text(i)
```
This is under the "on_ItemLis_item_activated" func and everything works great.
Here is the issue:
![first screen](http://image.prntscr.com/image/0d494d7346a041a6a7546ea3881a5b5b.png) - once items have been picked up the scroll appears as it should
![second screen](http://image.prntscr.com/image/f2423ccb158145b29095ce0aaa14ca3f.png) - doubble tapping then "activates" the item and inventory.ensure_current_is_visible() runs. The scroll also moves but the items stand still.
![third screen](http://image.prntscr.com/image/134aea31b30f4ec19f16cdeca5e253ea.png) - clicking once more on the item will give the result I was looking for, where the full item name and icon are revealed and the scroll appears to work.

Hope this makes sense, It seems like a bug or something of the like, so I probably won't need this to work "better", but thought I'd show it anyway in case it is a bug :)

Have a nice day

**Link to minimal example project:**
:

*Bugsquad edit*: make images be images, not links

**Comment by bojidar-bg** [comment] 2017-02-15 19:49
@DadangoGodotNoob Can you embed the images directly into Github, as currently I can see only the second one?

**Comment by bojidar-bg** [comment] 2017-02-15 19:53
To me it looks like the itemlist does call `update` therefore not redrawing properly, hm..

**Comment by DadangoGodotNoob** [comment] 2017-02-16 00:22
Thank you for embedding! I copied it from the QA section, when Zylann guided me here instead, so made no formatting.

**Comment by kubecz3k** [comment] 2018-04-10 17:40
First of all thank you for your report and sorry for the delay.

We released Godot 3.0 in January 2018 after 18 months of work, fixing many old issues either directly, or by obsoleting/replacing the features they were referring to.

We still have hundreds of issues whose relevance/reproducibility needs to be checked against the [current stable version](https://godotengine.org/download), and that's where you can help us.
**Could you check if the issue that you described initially is still relevant/reproducible in Godot 3.0 or any newer version, and comment about its current status here?**

For bug reports, please also make sure that the issue contains detailed steps to reproduce the bug and, if possible, a zipped project that can be used to reproduce it right away. This greatly speeds up debugging and bugfixing tasks for our contributors.

Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

Thanks in advance.

*Note: This message is being copy-pasted to many "stale" issues (90+ days without activity). It might happen that it is not meaningful for this specific issue or appears oblivious of the issue's context, if so please comment to notify the Bugsquad about it.*

**Comment by YeldhamDev** [comment] 2018-11-22 04:38
I can't reproduce this in as of 631cf67.

**Comment by akien-mga** [comment] 2018-11-22 08:09
Thanks, closing.

**Closed by akien-mga** 2018-11-22 08:09 UTC
Labels: bug, topic:core
