### ISSUE TITLE
Broken 3D joints when exported.

### ISSUE THREAD

**Issue by LeonardMeagher2** [godotengine/godot#2432] opened 2015-09-05 22:52 UTC
The gif on top was run inside the editor, and the gif on bottom is when exported.

I have no real way to  test, because no errors are thrown for these different behaviors, something to note, is that very rarely, even running from the editor this happens, but every time I test the exported version this happens.

![sumo_bug1](https://cloud.githubusercontent.com/assets/1546044/9701604/d97e3110-53e5-11e5-8394-3be987cbec17.gif)
![sumo_bug2](https://cloud.githubusercontent.com/assets/1546044/9701605/dcc3865e-53e5-11e5-9218-c15359ab6ad1.gif)

**Comment by slapin** [comment] 2015-09-06 02:29
Could you please link minimal project demonstrating the issue?

**Comment by LeonardMeagher2** [comment] 2015-09-06 02:54
https://dl.dropboxusercontent.com/u/106710024/physics_bug.zip

You need to export it, I export linux 64bit, both debug and release do the same thing for me (I built my own templates) 

You press space to reload the current scene, and occasionally the joints will not work.

Please let me know what you experience. @slapin

**Comment by crr0004** [comment] 2015-09-10 02:27
Linux, Fedora 22 exported with build commit b0aa49accbd7e45dae38f1bd43b0fbdd11714211.

I didn't experience the bug you're describing.

**Comment by okamstudio** [comment] 2015-09-10 02:31
Maybe a release bug? I will check

**Comment by LeonardMeagher2** [comment] 2015-09-11 02:59
@reduz, If you need a debug copy of the game to check I can do that also. It'd be sweet if this is easy to fix.

**Comment by reduz** [comment] 2015-09-11 03:20
sorry, just finished fixing the new build system and I'm exhausted.. will
give it a check tomorrow hopefully

**Comment by LeonardMeagher2** [comment] 2015-09-22 23:42
@reduz any time to test, I'd really like to see if you experience what I am, my game is unplayable this way, and everyone's computer I've tested it on similar results happen.

**Comment by bojidar-bg** [comment] 2016-05-24 18:54
@reduz ~ Did you actually get to checking this? :smile:

**Comment by akien-mga** [comment] 2016-07-21 11:40
Is this bug still reproducible?

**Comment by vnen** [comment] 2016-07-21 13:44
This might be related to #1860, which also seems to be a problem with joints.

**Comment by LeonardMeagher2** [comment] 2017-05-19 23:40
This is still an issue for me, creating anything with many joints (and I'm not sure why) breaks, this does happen for me in the editor also now.

It's pretty much the reason I am looking for a new engine, anything with stable physics.

**Comment by reduz** [comment] 2017-08-04 16:57
This is in suspense now given the possibility of moving to Bullet, let's wait a bit more to see if it's possible

**Comment by reduz** [comment] 2017-11-03 23:09
OK Given the Bullet PR is almost done, this should probably be closed soon.

**Comment by kubecz3k** [comment] 2017-11-05 10:11
Bullet is merged now. Would be nice if someone could recheck (#12641)

**Comment by rminderhoud** [comment] 2017-11-20 10:23
I tested with 6 pin joints in-editor with latest commit and no breakage:

![peek 2017-11-20 04-20](https://user-images.githubusercontent.com/1752584/33013631-51aa2bcc-cdaa-11e7-8699-723b11cecfd7.gif)

**Comment by akien-mga** [comment] 2017-11-20 10:52
Nice! Marked as closed then; it likely still affects the Godot custom physics engine, but it will be deprecated so we likely won't spend time trying to fix it unless the fixes are trivial.

**Closed by akien-mga** 2017-11-20 10:52 UTC
Labels: bug, confirmed, needs testing, topic:physics
