### ISSUE TITLE
Improvement: Developer/Designer Notes in Godot Editor

### ISSUE THREAD

**Issue by Skyfish1** [godotengine/godot#24762] opened 2019-01-04 11:34 UTC
**Godot version:**
3.*

**Improvement description:**
I think it would be very helpful while developing/designing your game in the Godot Editor, if you could attach developer notes/infos to nodes in the scene tab that appear as tooltips when you hover over them and with a small icon (like the script icon) - maybe a lightbulp - to show that here is a note attached.

One step further would be invisible note/info nodes that could be placed in the viewport window (game world), that are only visible in Editor and not exported or rendered when the game is running.

![image](https://user-images.githubusercontent.com/25827515/50686281-00801200-101d-11e9-9ca9-47c3f3eb79e9.png)

I often have ideas or improvements, that I want to explore later. Or if you are collaborating with other developers you could leave some notes to explain things.

Yes you could attach scripts with comments, but it's not the same and as practical.

**Comment by bojidar-bg** [comment] 2019-01-04 11:57
Duplicate of #2082. See also #7361.

**Closed by bojidar-bg** 2019-01-04 11:57 UTC

**Comment by captainwasabi** [comment] 2019-01-06 15:06
hmm, I do not believe this is a duplicate of #2082.  This looks like it's putting a note into the environment itself as a separate node, which really I think you can do already using a label.  You'd probably want to add a little functionality so that it's only shown in the editor (and Im not sure how this'd work in 3d.) but again, I don't think it's a duplicate of #2082.

**Comment by bojidar-bg** [comment] 2019-01-06 15:09
@captainwasabi That's the second suggestion. The first suggestion is one-to-one duplicate though.

**Comment by captainwasabi** [comment] 2019-01-06 15:16
Oh, true dat.  It's causing some confusion over in #2082 because of the screenshots.
