### ISSUE TITLE
AnimationPlayer instances share the same Animation object

### ISSUE THREAD

**Issue by MaurizioMacri** [godotengine/godot#30503] opened 2019-07-10 22:28 UTC
**Godot version:**
3.1.1 Stable

**OS/device including version:**
Windows 10

**Issue description:**
I have a scene with an AnimationPlayer containing an Animation. I create multiple instances of the scene and dinamically i call a function to modify some Animation parameters. I expect that if I call the function on just one of the AnimationPlayer instances it modify just that one instance. Instead it happens that all instances are modified because all AnimationPlayer instaces share the same Animation object.

**Steps to reproduce:**
- Create a scene with an AnimationPlayer and create a simple Animation
- Add a script and a function to modify the animation (i tried it with track keys value)
- Create another scene with multiple instances of the previous scene
- Call the function on one AnimationPlayer
- You will see it modify all the instances

**Comment by KoBeWi** [comment] 2019-07-10 22:36
Probably a duplicate of #30197

**Comment by Calinou** [comment] 2019-07-10 23:33
Duplicate of #30197.

**Closed by Calinou** 2019-07-10 23:33 UTC
