### ISSUE TITLE
Tiny font when creating new editor theme

### ISSUE THREAD

**Issue by meneerbanaan** [godotengine/godot#48743] opened 2021-05-15 19:19 UTC
**Godot version:**
3.3

**OS:**
macOS Big Sur

**Issue description:**

Sorry if this question has already been asked, but I didn’t find any related topics.

So my problem has to do with creating a new editor theme. The issue is whenever I create a new theme and apply this as custom theme for the editor. The font size defaults to something unreadable tiny. I’m using an iMac Pro so I assume it has to do with the hdpi display. Just my guess, so please don’t shoot me if it’s completely wrong. 😅

I tried increasing the font size in settings, but that seems to have no effect. 
I hope someone can help me, as I would like to change the theme to my liking.

**Comment by Calinou** [comment] 2021-05-15 19:26
Duplicate of https://github.com/godotengine/godot/issues/25585 (same cause).

**Closed by Calinou** 2021-05-15 19:26 UTC
