### ISSUE TITLE
Setting a negative scale on a Spatial causes its rotation and scale to change

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#26173] opened 2019-02-22 23:42 UTC
Godot 3.0.6
Godot 3.1 alpha1

Repro in Godot 3.0.6:
1) Create a Spatial
2) Set its scale to (-1, 1, 1)
3) Save the scene, close it
4) Reopen the scene, select the Spatial: now it has a scale of (1, 1, 1) and a rotation of (180, 0, 0)

Repro in Godot 3.1 alpha1:
Same steps, except the final result produces a scale of (-1, -1, -1) and a rotation of (180, 0, 0).

I noticed this because my character has two wings, one of which is the same mirrorred. I animate this wing's rotation, but due to the scale being fudged the result ended up wrong, then I found the rest by doing the repro.

**Comment by akien-mga** [comment] 2019-02-23 10:12
>  Godot 3.1 alpha1

What about beta 6?

**Comment by Zylann** [comment] 2019-02-23 11:49
@akien-mga Godot 3.1 beta 6 does the same as alpha1.

**Comment by reduz** [comment] 2019-02-23 12:28
This is not a bug. Godot only saves the transforms to disk, not the individual rotation/translation/scale. Those are only for reference in the editor.

Maybe we could add some code that if you only edited the object via loc/rot/scale, it will save and bring those back instead. The problem is that this won't work well with instancing and inheritance as if a scene saves transform but then you modify loc/rot/scale in the instance, it wont recognize that it was overriden.

Maybe just saving loc/rot/scale could be enough, like in 2D and I was thinking of adding an "order" enum, so you can actually chose the order of axis composition/decomposition. This would break compatibility though, so it's definitely 4.0 material.. will kick there.

**Comment by Zylann** [comment] 2019-02-23 12:34
@reduz yeah I expected that, because it looks like those two unwrapped transform states I seen in the inspector have the same matrix representation. It's just quite inconvenient because the API exposes those properties as if they would work fine, but they don't and it's unintuitive. Also, for comparison this doesn't happen anymore in Unity (its API uses Quaternion though). I'm not sure if adding an order enum would make things easier.

**Comment by aaronfranke** [comment] 2020-06-22 18:11
Rather than changing the code, I think this should simply be documented as a known limitation. It is Godot's convention that negative scales in 3D only work if all of the scale numbers are negative, due to how Godot decomposes transforms.

A similar limitation exists in 2D, but in that case only a negative Y scale is allowed, and a negative X scale results in a rotation. If https://github.com/godotengine/godot/issues/38868#issuecomment-647388442 is implemented, this would also have to be documented for 2D.

The Godot 3.0.6 behavior reported in the OP is wrong, but the behavior in 3.2.2 and reported behavior in 3.1 alpha 1 is correct.

**Comment by akien-mga** [comment] 2022-03-26 23:38
This seems fixed in 4.0 alpha 5.

**Closed by akien-mga** 2022-03-26 23:38 UTC
Labels: bug, topic:core
