### ISSUE TITLE
Very long loading of an empty program Godot 4.0 beta 1

### ISSUE THREAD

**Issue by Ghashy** [godotengine/godot#65908] opened 2022-09-16 15:25 UTC
### Godot version

4.0 beta 1

### System information

iMac (27-inch, Late 2012), macOS Catalina 10.15.7, i7, NVIDIA GeForce GTX 675MX 1 GB

### Issue description

I created a program from scratch on MacBook Pro M1. Then exported it (with debug disabled) and run it on my iMac with intel core i7. The loading was enormously long, about 1 minute. The same project rendered from Godot 3.5 run for one second. It seems like a bug.

### Steps to reproduce

Render an empty project

Run it on intel processor

**Comment by Calinou** [comment] 2022-09-16 16:07
Duplicate of https://github.com/godotengine/godot/issues/62322.

**Closed by Calinou** 2022-09-16 16:07 UTC
Labels: bug, platform:macos, topic:export, performance
