### ISSUE TITLE
Godot 4 Crash when editing a ScriptExtension on something that does not have a script. 

### ISSUE THREAD

**Issue by AlexanderLife** [godotengine/godot#68036] opened 2022-10-29 22:07 UTC
### Godot version

Godot_v4.0-beta3_linux.x86_64

### System information

Ubuntu 20.04 

### Issue description

When you make a script extention on something that does not have a script it and try to edit that script extension it will crash godot 4.

Why it may seem like why would someone do this? a user seeing what things will do can get to this crash in only 11 clicks deep from a new project. curiosity on what's a Script Extension got me to this I was lucklly not working on anything, but I could have been working on something and had that same curiosity and clicked with out thinking. 

if you have the output open you see this before crash

``` 
Godot Engine v4.0.beta3.official (c) 2007-2022 Juan Linietsky, Ariel Manzur & Godot Contributors.
  modules/gltf/register_types.cpp:76 - Blend file import is enabled in the project settings, but no Blender path is configured in the editor settings. Blend files will not be imported.
  modules/gltf/register_types.cpp:100 - FBX file import is enabled in the project settings, but no FBX2glTF path is configured in the editor settings. FBX files will not be imported.
--- Debug adapter server started ---
--- GDScript language server started ---
New Scene Root
Create Node
Set tile_set
  ./core/object/script_language_extension.h:54 - Required virtual method ScriptExtension::_can_instantiate must be overridden before calling.
  ./core/object/script_language_extension.h:65 - Required virtual method ScriptExtension::_placeholder_instance_create must be overridden before calling.
Set script
  ./core/object/script_language_extension.h:118 - Required virtual method ScriptExtension::_has_property_default_value must be overridden before calling.
  ./core/object/script_language_extension.h:57 - Required virtual method ScriptExtension::_get_instance_base_type must be overridden before calling.
  ./core/object/script_language_extension.h:55 - Required virtual method ScriptExtension::_get_base_script must be overridden before calling.
```

Godot is working up to this point but if you try to edit the ScriptExtension it will crash. with this

```
ERROR: Required virtual method ScriptExtension::_can_instantiate must be overridden before calling.
   at: _gdvirtual__can_instantiate_call (./core/object/script_language_extension.h:54)
ERROR: Required virtual method ScriptExtension::_placeholder_instance_create must be overridden before calling.
   at: _gdvirtual__placeholder_instance_create_call (./core/object/script_language_extension.h:65)
ERROR: Required virtual method ScriptExtension::_has_property_default_value must be overridden before calling.
   at: _gdvirtual__has_property_default_value_call (./core/object/script_language_extension.h:118)
ERROR: Required virtual method ScriptExtension::_get_instance_base_type must be overridden before calling.
   at: _gdvirtual__get_instance_base_type_call (./core/object/script_language_extension.h:57)
ERROR: Required virtual method ScriptExtension::_get_base_script must be overridden before calling.
   at: _gdvirtual__get_base_script_call (./core/object/script_language_extension.h:55)
ERROR: Required virtual method ScriptExtension::_get_source_code must be overridden before calling.
   at: _gdvirtual__get_source_code_call (./core/object/script_language_extension.h:74)
ERROR: Required virtual method ScriptExtension::_get_language must be overridden before calling.
   at: _gdvirtual__get_language_call (./core/object/script_language_extension.h:105)

================================================================
handle_crash: Program crashed with signal 11
Engine version: Godot Engine v4.0.beta3.official (01ae26d31befb6679ecd92cd3c73aa5a76162e95)
Dumping the backtrace. Please include this when reporting the bug to the project developer.
[1] /lib/x86_64-linux-gnu/libc.so.6(+0x46210) [0x7fc1227ae210] (??:0)
[2] /home/alexander/Downloads/Compressed/Godot_v4.0-beta3_linux.x86_64() [0x2258f09] (??:0)
[3] /home/alexander/Downloads/Compressed/Godot_v4.0-beta3_linux.x86_64() [0x225de66] (??:0)
[4] /home/alexander/Downloads/Compressed/Godot_v4.0-beta3_linux.x86_64() [0x1b61f05] (??:0)
[5] /home/alexander/Downloads/Compressed/Godot_v4.0-beta3_linux.x86_64() [0x1d18911] (??:0)
[6] /home/alexander/Downloads/Compressed/Godot_v4.0-beta3_linux.x86_64() [0x1d2554d] (??:0)
[7] /home/alexander/Downloads/Compressed/Godot_v4.0-beta3_linux.x86_64() [0x42befaa] (??:0)
[8] /home/alexander/Downloads/Compressed/Godot_v4.0-beta3_linux.x86_64() [0x1b1cdc1] (??:0)
[9] /home/alexander/Downloads/Compressed/Godot_v4.0-beta3_linux.x86_64() [0x1b0d251] (??:0)
[10] /home/alexander/Downloads/Compressed/Godot_v4.0-beta3_linux.x86_64() [0x4803aa5] (??:0)
[11] /home/alexander/Downloads/Compressed/Godot_v4.0-beta3_linux.x86_64() [0x42c0f77] (??:0)
[12] /home/alexander/Downloads/Compressed/Godot_v4.0-beta3_linux.x86_64() [0x294c8d5] (??:0)
[13] /home/alexander/Downloads/Compressed/Godot_v4.0-beta3_linux.x86_64() [0xe57eb5] (??:0)
[14] /home/alexander/Downloads/Compressed/Godot_v4.0-beta3_linux.x86_64() [0xd928ac] (??:0)
[15] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf3) [0x7fc12278f0b3] (??:0)
[16] /home/alexander/Downloads/Compressed/Godot_v4.0-beta3_linux.x86_64() [0xdb3e3e] (??:0)
-- END OF BACKTRACE --
================================================================
```

### Steps to reproduce

on a linux system
run the app image with ./Godot_v4.0-beta3_linux.x86_64
make a new project pick mobile
make a new 2D Scene
Add a TileMap (do not add a script)
Add a New TileSet
edit that TileSet
at the bottem of the inspector on the right under RefCounted
Script click "NewScriptExtenstion" 
(after clicking for me it has the box icon of the script extenstion but no text like it does not exist)
edit that ScriptExtenstion
for me crash happens now
ctrl-C  to exit the BackTrace

run again with ./Godot_v4.0-beta3_linux.x86_64
Make a new project pick Forward+
make a new 3D Scene
Add a Camera3D (do NOT add a script)
Add a NewEnvironment
edit that Environment
at the bottem of the inspector on the right under RefCounted
Script click "NewScriptExtenstion" 
edit that ScriptExtenstion
crash happens
ctrl-C  to exit the BackTrace

run again 
open one of the projects that should be fresh because nothing get saved :(
make a new User Interface
add a Label (do NOT add a script)
add New LabelSettings
edit that LabelSettings
at the bottem of the inspector on the right under RefCounted
Script click "NewScriptExtenstion" 
Script click on the blank space where text should be next to the ScriptExtenstion box icon that is the same as clicking the edit
crash happens

**Comment by Calinou** [comment] 2022-11-04 19:48
@AlexanderLife  Please surround large blocks of text with triple backticks like this:

\`\`\`
text here
\`\`\`

This prevents them from taking too much space and also makes sure issue references aren't accidentally created. I edited your comment, but remember to do this next time :slightly_smiling_face:

**Comment by Paulb23** [comment] 2022-11-06 14:51
Duplicate of #67267

**Closed by Paulb23** 2022-11-06 14:51 UTC
Labels: bug, needs testing, topic:gdextension, crash
