### ISSUE TITLE
Blend shapes error spam

### ISSUE THREAD

**Issue by DwanaG** [godotengine/godot#24226] opened 2018-12-08 05:15 UTC
**Godot version:**
Godot 3.1 21dea10

**OS/device including version:**
Windows 10 64 -bits

**Issue description:**
Whenever there is a mesh with blend shapes in a scene, the following error is printed for each of the blend shapes

> ERROR: VisualServerScene::instance_set_blend_shape_weight: Index p_shape=0 out of size 
>(instance->blend_values.size()=0)
   At: servers\visual\visual_server_scene.cpp:595

This happens when the scene is opened in the editor and when running the scene.

**Steps to reproduce:**
- Add a mesh with blend shapes to a scene

**Minimal reproduction project:**

[ShapeKeys.zip](https://github.com/godotengine/godot/files/2659425/ShapeKeys.zip)

**Comment by KoBeWi** [comment] 2020-06-29 22:40
Can anyone still reproduce this bug in [Godot 3.2.2](https://godotengine.org/article/maintenance-release-godot-3-2-2) or any later release?

**Comment by KoBeWi** [comment] 2020-09-28 22:33
Closing due to lack of update. Please comment if you can still reproduce this issue in the latest stable version of Godot.

**Closed by KoBeWi** 2020-09-28 22:33 UTC
Labels: bug, topic:core, topic:rendering
