### ISSUE TITLE
Wrong alpha rendering in ViewportTexture

### ISSUE THREAD

**Issue by Faless** [godotengine/godot#15402] opened 2018-01-06 14:00 UTC
**Godot version:**
3.0 master branch: 51854d61b0695e9487c7c624dfeb8c75718bd01b

**OS/device including version:**
Ubuntu 17.10
Nvidia GTX 980 (drivers 384.90)

**Issue description:**
When using `ViewportContainer` color modulation alpha is wrong

**Steps to reproduce:**
Create the following scene:

```
- Control
  - Viewport
    - Sprite (set modulate to use 50% alpha)
  - ViewportContainer
    - Viewport (set this viewport to use the same World2D of the first one)
       - Camera2D
```

The resulting blend is wrong. You can compare with the one you get when moving the `Sprite` outside of the `Viewport`.

![viewport_bug](https://user-images.githubusercontent.com/1687918/34640402-5144f370-f2f2-11e7-9b50-3dd1559e414d.png)

Check the attached demo for an easy test

**Minimal reproduction project:**
[double_alpha.zip](https://github.com/godotengine/godot/files/1608835/double_alpha.zip)

**Comment by Faless** [comment] 2018-01-07 11:28
Update:
I did some further testing, no need to use modulate, any PNG with alpha will be rendered differently between when inside the main viewport and when shown through render texture.

See the updated demo which no longer uses colour modulation:

[alpha_bug.zip](https://github.com/godotengine/godot/files/1609712/alpha_bug.zip)

![alpha_bug](https://user-images.githubusercontent.com/1687918/34649000-121d70d2-f3a6-11e7-8507-992780ef20cc.png)

**Comment by LeonardMeagher2** [comment] 2018-01-16 04:06
I believe this happens when you put the viewport texture in a mesh''s materiel also.
it really makes everything washed out.

**Comment by Calinou** [comment] 2020-06-07 16:50
Related to #17574. Note that this will probably be fixed in 4.0 thanks to bindless textures in Vulkan. These make it possible to use the same texture in sRGB and non-sRGB without having to import it twice. (Godot's 2D renderer expects non-sRGB textures, whereas the 3D renderer expects sRGB texture.)

**Comment by Zylann** [comment] 2021-06-08 17:08
Is this caused by premultiplied alpha? I had this issue in the past when making an image editor based on viewports.

**Comment by Calinou** [comment] 2022-07-10 18:29
Duplicate of https://github.com/godotengine/godot/issues/17574.

@LeonardMeagher2 This particular issue can be fixed by enabling **Albedo Tex Force Srgb** in the SpatialMaterial. See https://github.com/godotengine/godot/issues/18208#issuecomment-1175534138.

**Closed by Calinou** 2022-07-10 18:29 UTC
Labels: bug, topic:rendering
