### ISSUE TITLE
Animation editor timeline playhead does not advance when adding a key if the confirmation dialog appears

### ISSUE THREAD

**Issue by Torguen** [godotengine/godot#33681] opened 2019-11-17 18:41 UTC
**Godot version:**
3.2 beta 1 mono

**OS/device including version:**
Win10 Home 64

**Issue description:**
It can be seen that when you enter the first frame by clicking on the key icon to add a keyframe, the frame is entered in the animation editor but the timeline did not move, then when you click on the key icon again , the second frame overlaps the first frame.
The first frame disappears, it cannot be selected.
Although you double clicked on the key icon, only the second frame was added.
The first frame was overwritten.

**_The problem was that the timeline did not shift when the first frame was introduced._**

I would like to add something, add a new animation by pressing the "Animation" -> "New" button should bring the timeline to 0.

**Steps to reproduce:**
Add the initial keyframe in the animation editor and then a new keyframe.

The first frame will be overwritten by the second frame, then even though you pressed the keyframe add button twice, only the second frame was added to the animation editor.

![GIF](https://user-images.githubusercontent.com/19652075/69012103-45314500-0972-11ea-9689-dc2fe8c9dfa1.gif)

**Minimal reproduction project:**
[animationEditorBug.zip](https://github.com/godotengine/godot/files/3855960/animationEditorBug.zip)

**Comment by Torguen** [comment] 2019-11-20 02:54
The solution to this problem is to apply the rule that every time a frame is added to the timeline, the time bar must move automatically.
Currently that is not happening when the create framekey icon is pressed for the first time.

**Comment by avencherus** [comment] 2019-11-20 19:24
I believe this issue has existed since at least 2.1, probably even always.  Might even be an issue somewhere for it...

The work around we've used is to click the keyframe and then scrub the timeline forward then backward, re-keyframe over top the first, and then it will advance.

Seems it doesn't want to advance a step if there is no existing keyframes.

**Comment by Torguen** [comment] 2019-11-20 20:38
There really are two possible and valid paths.

On the initial press of the "Add keyframe" button the timeline of the animation is created, then two things can happen afterwards:

A - If you insert a new frame (I mean automatically by the editor), then the line should move automatically.

B - If you do not insert a new frame, then the line should not be moved, leaving 0.0 ready to add the first animation frame.

**Comment by rathren** [comment] 2020-01-07 11:00
uhf that's awkward. Note to self: "don't include issue id when trying to something in git you haven't done before" :D

**Comment by KoBeWi** [comment] 2020-11-28 22:39
Seems fixed in 3.2

**Comment by KoBeWi** [comment] 2020-11-30 23:02
Ok it's not fixed if you have confirmation enabled. It's only correct when you insert without confirmation.

**Comment by golddotasksquestions** [comment] 2021-04-12 17:43
I think this bug exist since 3.1 at least.

If the user presses the key sympol on a property without an existing track, after the first key is set, the timestamp is not advanced, therefore the first key is overwritten by the second key:

https://user-images.githubusercontent.com/47016402/114317464-7fbbf480-9b08-11eb-9f70-b07f2baa308a.mp4

See simple steps to reproduce here:
https://github.com/godotengine/godot/issues/47808

**Comment by Torguen** [comment] 2022-02-17 09:47
Stay present at v3.5.beta1.official [b9b23d222]
When the first key is added, the animationplayer's timebar doesn't advance, however it does advance with any other keys added after the first one.

**Closed** 2022-07-28 08:14 UTC
Labels: bug, topic:editor, confirmed
