### ISSUE TITLE
2D Flickering 

### ISSUE THREAD

**Issue by nshusa** [godotengine/godot#16277] opened 2018-02-01 10:37 UTC
**Godot version:**
3.0 stable

**OS/device including version:**
OS: Windows 10
GPU: Nvidia GTX 1070

**Issue description:**
In 2D there seems to be some flickering with the tiles in this scene.

Here's what it looks like
![https://i.imgur.com/XRl5qi0.gif](https://i.imgur.com/XRl5qi0.gif)

**Steps to reproduce:**
Run the project below. The flickering should start within a few seconds.

**Minimal reproduction project:**
[Zombie Game.zip](https://github.com/godotengine/godot/files/1685134/Zombie.Game.zip)

**Comment by akien-mga** [comment] 2018-02-01 10:57
Thanks for the detailed report. It's a duplicate of #9913, but we're having a hard time debugging it as it seems hard to reproduce.

**Closed by akien-mga** 2018-02-01 10:57 UTC
