### ISSUE TITLE
[CSharp] Properties that can be null should use 'nullable'

### ISSUE THREAD

**Issue by x1shi** [godotengine/godot#75772] opened 2023-04-07 05:18 UTC
### Godot version

4.0.1

### System information

pass

### Issue description

```csharp
public void Test(){
     var node = new Godot.Control();
     /*
     * public Theme Theme { get; set; }
     * in class Control
     */
     GD.Print(node.Theme); //but get null here
}
```

### Steps to reproduce

pass

### Minimal reproduction project

pass

**Comment by x1shi** [comment] 2023-04-07 05:22
need make `Control.Theme`'s type like this: `public Theme? Theme { get; set; }`

**Comment by raulsntos** [comment] 2023-04-07 19:28
Duplicate of https://github.com/godotengine/godot-proposals/issues/2241

**Closed by raulsntos** 2023-04-07 19:28 UTC
Labels: archived, topic:dotnet
