### ISSUE TITLE
Blend shapes have incorrect size on HTML5 platform (GLES3)

### ISSUE THREAD

**Issue by Atem1995** [godotengine/godot#60525] opened 2022-04-26 09:38 UTC
### Godot version

3.x and 3.4.

### System information

window10, html5

### Issue description

Blend shapes behave inconsistently in html5 and window10, in html5, it is obviously enlarged by more than 2 times

on Android，it works normal, just not right on html5.
![1650965553(1)](https://user-images.githubusercontent.com/52338846/165270891-697191d7-dd16-41eb-b9d4-627d1e4f3e76.png)
![1650965675(1)](https://user-images.githubusercontent.com/52338846/165270907-a726c254-b538-4b56-b17d-287ad408d21e.png)
.

### Steps to reproduce

#

### Minimal reproducti
[blend_shapes_test.zip](https://github.com/godotengine/godot/files/8562156/blend_shapes_test.zip)
This minimal project is on version 3.4.4 stable. But the same problem is on the 3.x version. I had tested it.

#

**Comment by Zireael07** [comment] 2022-04-26 09:39
Please give the issue a descriptiive title and include a minimal project

**Comment by Atem1995** [comment] 2022-04-26 10:15
> Please give the issue a descriptiive title and include a minimal project

Sorry,hah...

**Comment by Calinou** [comment] 2022-04-26 12:19
Can you reproduce this after switching to the GLES2 rendering backend and exporting to HTML5 again?

**Comment by Atem1995** [comment] 2022-05-06 05:48
> Can you reproduce this after switching to the GLES2 rendering backend and exporting to HTML5 again?

@Calinou When switching to gles2, objects with Blend shape disappeared. There should be no rendering. I tested it in depth and found that under gles3, if the shadow of the direct light is turned off, it can be animated normally.

**Comment by Calinou** [comment] 2022-05-06 16:12
@Atem1995 Does it work outside of HTML5 (i.e. when running the project natively)?

**Comment by Atem1995** [comment] 2022-05-06 16:16
Yes,it does. Only on HTML5 it make some mistakes……



---Original---
From: "Hugo ***@***.***&gt;
Date: Sat, May 7, 2022 00:13 AM
To: ***@***.***&gt;;
Cc: "吾也君( Atem ***@***.******@***.***&gt;;
Subject: Re: [godotengine/godot] Blend shapes have incorrect size on HTML5platform (GLES3) (Issue #60525)




 
@Atem1995 Does it work outside of HTML5 (i.e. when running the project natively)?

**Comment by clayjohn** [comment] 2022-05-06 16:29
It looks like this is where the error is coming from. 
https://github.com/godotengine/godot/blob/4ea6707ea3b2c093be3c05503f4f7fc5a682e499/drivers/gles2/rasterizer_storage_gles2.cpp#L2508-L2510
It is saying that one of the blend shapes supplied has a different amount of data than the base mesh. On the face of it, it is unclear why this would trigger on HTML5 builds but not others.

**Comment by Atem1995** [comment] 2022-05-06 16:37
Can it be fixed?I am trying to make a web3.0 game with Godot.If it could not work, maybe babylon.js is another choice... :/



---Original---
From: "Clay ***@***.***&gt;
Date: Sat, May 7, 2022 00:30 AM
To: ***@***.***&gt;;
Cc: "吾也君( Atem ***@***.******@***.***&gt;;
Subject: Re: [godotengine/godot] Blend shapes have incorrect size on HTML5 platform (GLES3) (Issue #60525)




 
It looks like this is where the error is coming from.
 https://github.com/godotengine/godot/blob/4ea6707ea3b2c093be3c05503f4f7fc5a682e499/drivers/gles2/rasterizer_storage_gles2.cpp#L2508-L2510
 It is saying that one of the blend shapes supplied has a different amount of data than the base mesh. On the face of it, it is unclear why this would trigger on HTML5 builds but not others.

**Comment by clayjohn** [comment] 2022-05-06 16:41
> Can it be fixed?I am trying to make a web3.0 game with Godot.If it could not work, maybe babylon.js is another choice... :/

I just dug into the GLES2 issue a little bit, I think the error comes from here:
https://github.com/godotengine/godot/blob/4ea6707ea3b2c093be3c05503f4f7fc5a682e499/drivers/gles2/rasterizer_storage_gles2.cpp#L2492-L2498

The rasterizer has to decompress the vertex attributes because it doesn't support half_floats, but it doesn't decompress the blend shapes! So the blend shapes end up not aligning with the original mesh and the function emits an error. The fix on our end is to make sure that the blend shapes get decompressed. On your end, you can fix things now by importing your mesh with all the compress options unchecked (right now most attributes are compressed in the MRP).

**Comment by clayjohn** [comment] 2022-05-06 17:38
I've made a pull request fixing the GLES2 issue, I'm trying to reproduce the GLES3 issue now.

**Comment by clayjohn** [comment] 2022-05-06 19:28
Okay, fixes are in for both the GLES3 issue and the GLES2 issue. Once those get merged this should be totally fixed.

**Comment by Atem1995** [comment] 2022-05-07 02:41
> Okay, fixes are in for both the GLES3 issue and the GLES2 issue. Once those get merged this should be totally fixed.

Thanks！Good job！Man! 👍

**Comment by clayjohn** [comment] 2022-05-07 07:29
Closing as fixed by #60832

**Closed by clayjohn** 2022-05-07 07:29 UTC
Labels: bug, platform:html5, topic:rendering, topic:3d
