### ISSUE TITLE
Cannot open Dictionary contents of 2D arrays in the debugger

### ISSUE THREAD

**Issue by smks** [godotengine/godot#56493] opened 2022-01-04 20:40 UTC
### Godot version

3.4.2.stable

### System information

macOS Catalina v10.15.7

### Issue description

2.3 GHz Quad-Core Intel Core i7

When trying to inspect a dictionary inside an array of an array, it is quite stubborn to open. In fact it decides not to open so I cannot inspect it at all.

<img width="516" alt="Screenshot 2022-01-04 at 20 37 32" src="https://user-images.githubusercontent.com/4087157/148120848-c11f0d62-91f4-4433-b907-2c4e9ef55d06.png">

GIF:

![DebuggerBug-Godot](https://user-images.githubusercontent.com/4087157/148121082-9ffa5622-d8be-47d0-954e-4e94de05633c.gif)

### Steps to reproduce

Create a 2D array, and give each element a dictionary of say... 12 items of scalar values.

Try and open In the debugger and click to open the array and then try and open the dictionary.

**Comment by Calinou** [comment] 2022-01-04 20:43
Duplicate of https://github.com/godotengine/godot/issues/25375.

**Closed by Calinou** 2022-01-04 20:43 UTC
