### ISSUE TITLE
Mono C# 'Condition !valid is true.', 'Method/Function Failed.' Errors

### ISSUE THREAD

**Issue by SRugina** [godotengine/godot#19971] opened 2018-07-04 19:31 UTC
**Godot version:** 3.0.4 Mono Edition

**OS/device including version:** Linux on a Laptop

**Issue description:** Writing a C# script, but I get this in the output, which prevents me from using my C# script. Also crashes when pressing F6 ` modules/mono/editor/csharp_project.cpp:118 - Method/Function Failed.
 modules/mono/csharp_script.cpp:1957 - Condition ' !valid ' is true. returned: __nul`

**Steps to reproduce:** Install Mono complete from command line, then download Godot 3.0.4 onto a fresh ubuntu install, then make a new 2d project and do the "Your First Game" script from documentation for the player. Check output of script, see the errors. Press F6. Will crash.

**Minimal reproduction project:** 
[DodgeCreeps.zip](https://github.com/godotengine/godot/files/2164197/DodgeCreeps.zip)

**Comment by neikeq** [comment] 2018-07-05 01:34
I can't reproduce it on master as of e3c8ac43, I will try tomorrow with 3.0.4.

**Comment by reduz** [comment] 2018-09-07 19:14
news on this?

**Comment by akien-mga** [comment] 2019-02-23 13:36
Assuming fixed in the master branch as per @neikeq's comment.

**Closed by akien-mga** 2019-02-23 13:36 UTC
Labels: bug, topic:mono
