### ISSUE TITLE
Using viewport texture in a TextureRect shows errors

### ISSUE THREAD

**Issue by sszigeti** [godotengine/godot#59161] opened 2022-03-15 10:59 UTC
### Godot version

v3.4.3.stable.official [242c05d12] (but I believe I saw this issue several versions earlier)

### System information

Windows 10

### Issue description

I need to create a single texture of several others so that I can apply visual effects to the composite layer.

I believe this requires a Viewport whose texture can be attached to a TextureRect.

This seems to be working, however I'm getting the following errors logged:

```
E 0:00:00.434   get_path: Cannot get path of node as it is not in a scene tree.
<C++ Error>   Condition "!is_inside_tree()" is true. Returned: NodePath()
<C++ Source>  scene/main/node.cpp:1587 @ get_path()
E 0:00:00.439   get_node: (Node not found: "TextureRect/Viewport" (relative to "").)
<C++ Error>   Condition "!node" is true. Returned: nullptr
<C++ Source>  scene/main/node.cpp:1325 @ get_node()
E 0:00:00.443   setup_local_to_scene: ViewportTexture: Path to node is invalid.
<C++ Error>   Condition "!vpn" is true.
<C++ Source>  scene/main/viewport.cpp:69 @ setup_local_to_scene()
```

![screenshot](https://raw.githubusercontent.com/sszigeti/godot-viewport-texture-bugs/main/screenshot.png)

The exported application works properly, except in debug mode the errors are shown in the console. A non-debug build seems to be working fine as well, so these errors are just false.

I'm not 100% confident but I believe that several versions ago (maybe around 3.3) I was able to use a TextureRect with a Viewport without this issue.

I have also tried to use ViewportContainer instead of a TextureRect. In this case no errors were shown. I still need to use the TextureRect, as the generated viewport texture doesn't have filtering (that I need), and I have found no way to access the texture of a ViewportContainer.

### Steps to reproduce

Start the attached project, also available as [a public GitHub repo](https://github.com/sszigeti/godot-viewport-texture-bugs).

### Minimal reproduction project

https://github.com/sszigeti/godot-viewport-texture-bugs

https://github.com/sszigeti/godot-viewport-texture-bugs/archive/refs/tags/v1.zip

**Comment by Calinou** [comment] 2022-03-15 17:33
Duplicate of https://github.com/godotengine/godot/issues/16067.

**Closed by Calinou** 2022-03-15 17:33 UTC
