### ISSUE TITLE
Bug in breakpoints: "!id_map.has(p_rid.get_data())" is true

### ISSUE THREAD

**Issue by kzerot** [godotengine/godot#38229] opened 2020-04-26 14:03 UTC
**Godot version:** 3.2.2.rc

**OS/device including version:** Linux Manjaro

**Issue description:**
![error](https://user-images.githubusercontent.com/4415061/80309703-5e6ed500-87df-11ea-8bab-e5097d284931.png)
It's floating bug, I have it only on more or less big project (on video - around 100 *.gd scripts)
When I'm trying to use breakpoints on certain places in a code debug console starting to spam error messages:
```
E 0:00:14.820   getornull: Condition "!id_map.has(p_rid.get_data())" is true. Returned: __null
  <C++ Source>  ./core/rid.h:160 @ getornull()
```
It can happen in different places of code. Also it happens not always. 
https://youtu.be/QFScfQA6wNU

**Steps to reproduce:** 
Really don't know. Make an big project
**Minimal reproduction project:**
Nothing

**Comment by SuperMeip** [comment] 2020-07-08 20:36
This happens to me with some code without debugging as well :(

**Comment by Reneator** [comment] 2021-06-28 12:54
Still getting this Error in 3.3.2 windows 10 with my big project. But this doesnt happen always, but when it does, it repeatedly spams those Errors and slows down the editor drastically:
![image](https://user-images.githubusercontent.com/24807557/123639622-abee3400-d820-11eb-8ae3-83608dd8dd97.png)

**Comment by tinmanjuggernaut** [comment] 2021-11-06 00:08
RIDs that have already been freed are being sent to free again. You might be doing it in your code. The editor does it by itself due to a bug introduced as of Nov 2020.
You can read about it in #53374 and the fix is coming in PR #54650.

**Comment by akien-mga** [comment] 2021-12-09 21:05
This may have been fixed by #54650 (included in 3.4.1 and 3.5). Please comment if you can still reproduce it.

**Closed by akien-mga** 2021-12-09 21:05 UTC
Labels: bug, topic:core

**Comment by Torguen** [comment] 2023-04-20 15:18
![Captura](https://user-images.githubusercontent.com/19652075/233411465-6ec8a32c-a5d8-44fc-acee-6bfd4039507b.PNG)

Still in 3.6 beta 1

**Comment by bspear8** [comment] 2023-04-30 23:45
Observed in 3.5.1 stable
![image](https://user-images.githubusercontent.com/11604157/235381606-f80018a2-4e74-4106-bb2b-58110f9b5252.png)

**Comment by hero2002** [comment] 2023-12-06 20:11
It still exists in 3.5.3 stable
