### ISSUE TITLE
SSAO Regression, also related to a SSIL Bug

### ISSUE THREAD

**Issue by mrjustaguy** [godotengine/godot#51564] opened 2021-08-12 11:49 UTC
### Godot version

v4.0.dev.custom_build [b76b45b42]

### System information

Windows 10, Vulkan, Nvidia Quadro K2000 461.92

### Issue description

some time between v4.0.dev.custom_build [0537e3d61] and v4.0.dev.custom_build [b76b45b42] SSAO Broke (25th to 29th July).

Expected in 0537e3d61:
![SSAO Expected](https://user-images.githubusercontent.com/50302479/129191428-a58a62fd-bbe9-43e9-b9b6-5c580a2b4dd6.PNG)

Broken in b76b45b42:
![SSAO Regression](https://user-images.githubusercontent.com/50302479/129191447-5b124a27-6b07-4e96-82f8-c9fd0b03a331.PNG)

### Steps to reproduce

1. Create a Simple Scene With a Pair of Objects
2. Turn on SSAO (Very Low Has the most visible issue, but others do too)

### Minimal reproduction project

[SSAO Reg.zip](https://github.com/godotengine/godot/files/6975210/SSAO.Reg.zip)

**Comment by clayjohn** [comment] 2021-08-12 14:17
Ive noticed this too, it happens sporadically I find that about half the time restarting the editor makes it go away. 

I think I have a fix in my SSIL PR https://github.com/godotengine/godot/pull/51206

**Comment by clayjohn** [comment] 2021-08-12 15:58
I have a feeling it is caused by https://github.com/godotengine/godot/commit/cf3f404d312146cf46ae27fd8d220852eac27eb9 which was merged on July 26. If that's the case then the "fix" I did in #51206 is totally unrelated :P

**Comment by mrjustaguy** [comment] 2022-01-14 21:24
This is Still Present in v4.0.dev.custom_build [172223e9b] and Similar effect takes Place not only in SSAO but in SSIL too, and is especially clear when using Half Resolution on Lower Quality.

**Comment by BastiaanOlij** [comment] 2023-02-09 05:23
Please test with #72838

**Comment by mrjustaguy** [comment] 2023-02-09 09:39
it had no effects on this issue, though that is because in RC1 it seems to have been resolved already (aside from the half res issue and the depth inaccurate occlusions due to depth, both of which were issues for a long time and seem separate to this)

**Comment by akien-mga** [comment] 2023-02-09 10:10
Closing then.

**Closed by akien-mga** 2023-02-09 10:10 UTC
Labels: bug, topic:rendering, confirmed, regression, topic:3d
