### ISSUE TITLE
[feature request] Explicitly named arguments in method call

### ISSUE THREAD

**Issue by fisheye36** [godotengine/godot#27563] opened 2019-03-31 20:21 UTC
Since GDScript is inspired by Python, it might as well copy one syntactic element from it. When calling a method and supplying arguments, you can explicitly name that parameter in method call to make it more readable:

```
func do_something(first_arg, second_arg):
    pass

func _ready():
    do_something(1.0, second_arg=5.0)
```

I personally believe every programming language should support this syntax since it only aids in readability of the code written. It is especially handy when a function/method expects a boolean:

```
func _ready():
    _spawn_player(Vector2(100.0, 200.0), is_hidden=false)
```

What are your opinions and what would be the cost of implementing that feature (easy / hard)?

**Comment by Calinou** [comment] 2019-03-31 20:47
Duplicate of https://github.com/godotengine/godot/issues/6866.

**Closed by Calinou** 2019-03-31 20:47 UTC
