### ISSUE TITLE
Engine not reading gamepad input correctly

### ISSUE THREAD

**Issue by Ns816235** [godotengine/godot#52602] opened 2021-09-12 15:20 UTC
### Godot version

3.3.3 stable

### System information

Linux mint

### Issue description

Right stick is not reading any horizontal movement when stick is moving. This is using an xbox360 rock candy gamepad. [video](https://www.reddit.com/r/godot/comments/pmbcch/gamepad_not_reading_leftright_on_right_stick/)

### Steps to reproduce

Plug in gamepad.  Print var Input.get_joy_axis(0, JOY_AXIS_2).  Notice no output

### Minimal reproduction project

[gamepadError.zip](https://github.com/godotengine/godot/files/7149812/gamepadError.zip)

**Comment by Calinou** [comment] 2021-09-12 16:01
Duplicate of https://github.com/godotengine/godot/issues/48067.

**Closed by Calinou** 2021-09-12 16:01 UTC
Labels: bug, topic:input

**Comment by Rubonnek** [comment] 2021-09-12 16:50
@Ns816235 Have you attempted to [map the keys and joysticks](https://docs.godotengine.org/en/stable/tutorials/inputs/controllers_gamepads_joysticks.html#my-controller-has-incorrectly-mapped-buttons-or-axes/) for your controller like @Calinou implied?

I personally use the [SDL2 GamePad tool](https://www.generalarcade.com/gamepadtool/) for that.

You can install the joypad configuration string the tool provides at runtime in an [Autoload](https://docs.godotengine.org/en/stable/getting_started/step_by_step/singletons_autoload.html).

```gdscript
extends Node
func _ready():
    var joypad_configuration_string : String = "gamepadtool, or controllermap configuration string goes here"
    var overwrite_existing_entry : bool = true
    Input.add_joy_mapping(joypad_configuration_string, overwrite_existing_entry)
```

Then test again.

@Ns816235 Your test works in my end but I have a different controller. If you want the engine to have built-in support for your controller, you'll have to make a pull request to [SDL_GameControllerDB](https://github.com/gabomdq/SDL_GameControllerDB). Updates to that repository will eventually make their way to Godot when we synchronize those.

**Comment by Ns816235** [comment] 2021-09-13 14:22
Apologies for the late response, rock candy is more so a 'no-name' model as Calinou called it.  I have tried remapping, but with failure.  I have submitted a request over on SDL_GameControllerDB (thank you for that tip), so hopefully it'll start on the next possible update.  Thank you all for you help.
