### ISSUE TITLE
With current master variant type is broken

### ISSUE THREAD

**Issue by slapin** [godotengine/godot#31841] opened 2019-08-31 22:27 UTC
I see the error when I try to use Array constructor over anything.

Invalid call. Nonexistent 'Array' constructor.

Code example:

```gdscript
	var pd1: PoolVector2Array = base_array[ArrayMesh.ARRAY_TEX_UV2]
	var pd2: PoolVector2Array = gender_array[ArrayMesh.ARRAY_TEX_UV2]
	var pa1 = Array(pd1)
	var pa2 = Array(pd2)
```

In addition, it is not possible to modify PoolXArray typed arrays from gdscript using a[x] = b
push_back() and append_array do not work also.
```gdscript
	var buckets = [
		{
			"dir": [Vector3(-1, 0, 0), Vector3(0, 0, 1)],
			"triangles": PoolIntArray()
		},
		{
			"dir": [Vector3(-1, 0, 0), Vector3(0, 0, -1)],
			"triangles": PoolIntArray()
		},
		{
			"dir": [Vector3(1, 0, 0), Vector3(0, 0, 1)],
			"triangles": PoolIntArray()
		},
		{
			"dir": [Vector3(1, 0, 0), Vector3(0, 0, -1)],
			"triangles": PoolIntArray()
		}
	]
```

In the above example, any chagnes to buckets[x].triangles like buckets[x].triangles.push_back(20) are ignored, however buckets[x].triangles = PoolIntArray(Array(buckets[x].triangles) + [20, 21, 22]) work fine.

This is master branch
ba854bbc7bb0eae230299de4da8dfcb7caf74b69 is my current HEAD.

**Comment by slapin** [comment] 2019-08-31 23:46
as I understand, the reason is that sometimes gender_array[ArrayMesh.ARRAY_TEX_UV2] is Variant::NIL which leads to series of checks and in can_convert() routine the check for object leads to can_convert() returning false. I think this case is frequent enough and deserver either sane error or allow creation of empty array in this case. As for second issue I'm still don't know what to think of.

**Comment by KoBeWi** [comment] 2020-09-01 23:36
Can anyone still reproduce this bug in [Godot 3.2.3 rc4](https://godotengine.org/article/release-candidate-godot-3-2-3-rc-4) or any later release?

If yes, please ensure that an up-to-date Minimal Reproduction Project (MRP) is included in this report (a MRP is a zipped Godot project with the minimal elements necessary to reliably trigger the bug). You can upload ZIP files in an issue comment with a drag and drop.

**Comment by slapin** [comment] 2020-10-26 10:25
Minimal repro script (run with godot -s script.gd).
To demo second case, comment-out execution of case1()
case1 produces meaningful error now so I think it has valid solution, but not second case.
```gdscript
extends SceneTree
var ba: = []
var ga: = []
func case1():
        ba.resize(ArrayMesh.ARRAY_MAX)
        ga.resize(ArrayMesh.ARRAY_MAX)
        var pd1: PoolVector2Array = ba[ArrayMesh.ARRAY_TEX_UV2]
        var pd2: PoolVector2Array = ga[ArrayMesh.ARRAY_TEX_UV2]
        var pa1 = Array(pd1)
        var pa2 = Array(pd2)
func case2():
        var buckets = [
                {
                        "dir": [Vector3(-1, 0, 0), Vector3(0, 0, 1)],
                        "triangles": PoolIntArray()
                },
                {
                        "dir": [Vector3(-1, 0, 0), Vector3(0, 0, -1)],
                        "triangles": PoolIntArray()
                },
                {
                        "dir": [Vector3(1, 0, 0), Vector3(0, 0, 1)],
                        "triangles": PoolIntArray()
                },
                {
                        "dir": [Vector3(1, 0, 0), Vector3(0, 0, -1)],
                        "triangles": PoolIntArray()
                }
        ]
        buckets[1].triangles.push_back(20)
        print(buckets)
func _init():
        case1()
        case2()

```

**Comment by KoBeWi** [comment] 2020-10-26 15:07
> var pd1: PoolVector2Array = ba[ArrayMesh.ARRAY_TEX_UV2]

This line is wrong. It tries to assign null to `PoolVector2Array`. The `ba` array is empty. When you create a correct PoolArray, the Array constructor works correctly.

The second case is duplicate of #15265

**Closed by KoBeWi** 2020-10-26 15:07 UTC
Labels: bug, topic:core
