### ISSUE TITLE
Vector support?

### ISSUE THREAD

**Issue by toby3d** [godotengine/godot#9188] opened 2017-06-15 01:59 UTC
As far as I know, Godot supports ONLY static images of the `png`/`jpg`/`jpeg` format. How about implementing support for vector formats? This would eliminate the blurring and pixel problems. In this way, the vector will always look good at all screen resolutions at any zoom level.

I'm not talking about replacing one format with another. I'm talking about additional implementation for those who need it.

**Comment by vnen** [comment] 2017-06-15 02:28
Duplicate of #4826.

**Closed by vnen** 2017-06-15 02:28 UTC

**Comment by toger5** [comment] 2017-06-15 02:32
vector formats are beasts. It's not as easy as just adding a vector format to the accepted image formats.
But you have a good point it would be cool. there are a couple of other issues about the same topic. (named: `svg + something`). check them out to see what the current process is.
Vector graphics just take a lot of power to get rendered. Analysing the curves converting them into polygon shapes send them to the gnu and render them.. harder than just buffering pixels to a specific location of the screen...
Probably the support for them also would work by importing svgs as bitmaps. Otherwise they just would take a lot of power.
Reduz is planning (at leas mentioned) to support 2d meshes in some future release. This is the closest to an actual vector graphic. Than it might be possible to import svgs as pngs(redered) or as 2d meshes...
But again: thats a lot of work
