### ISSUE TITLE
Hardware interference bug making loading scenes slowly

### ISSUE THREAD

**Issue by Kyle-Truebird** [godotengine/godot#38179] opened 2020-04-24 15:51 UTC
I read that someone was having problems loading a scene demo because of a piece of hardware that was plugged in so I started unplugging my peripherals. It turns out my FiiO K1 dac was the culprit. The scenes load instantly now. I'm using a Dell XPS with windows 10 Home and Godot 3.2.1 stable.

Link to steam form where I saw the problem.
https://steamcommunity.com/app/404790/discussions/0/1734333281937236159/

processor: Intel i7-8705G cpu
ram: 16GB
system type: 64bit
graphics: Intel HD Graphics 630

To reproduce the problem, plug Fiio k1 dac back in.

**Comment by akien-mga** [comment] 2020-04-24 15:55
Duplicate of #20566.

Upgrading the firmware of the peripheral might help, it's a driver bug.

**Closed by akien-mga** 2020-04-24 15:55 UTC
