### ISSUE TITLE
Crash cause when being dumb and forgetting to rename after deleting default name of a node.

### ISSUE THREAD

**Issue by Poyo64** [godotengine/godot#27785] opened 2019-04-07 21:05 UTC
Hopefully no else has said anything about this.
I deleted a collisionnode2d's name, forgot to type in new name, and then tried to change the collision shaped but it broke godot :'^(.

![uh oh](https://user-images.githubusercontent.com/49376516/55689793-fa206f80-5956-11e9-8e5f-7f4b519af6e4.gif)

**Comment by qarmin** [comment] 2019-04-08 06:20
Confirm on Ubuntu 18.04.2
Next time please fill template about Godot version etc.

This happens because Godot never exit loop in _gui_input_event (line 1742) 
![Zrzut ekranu z 2019-04-08 08-17-28](https://user-images.githubusercontent.com/41945903/55702477-fa604f80-59d6-11e9-8575-b97b20a908a9.png)

**Comment by YeldhamDev** [comment] 2019-04-20 14:20
Manjaro GNU/Linux
It doesn't alright crashes for me, but it gets stuck and the process needs to be killed manually.

**Comment by Anutrix** [comment] 2019-08-12 14:19
I think we should do the same thing that other software like Windows Explorer do i.e, when there's no name and that item/window looses focus, it uses the previous name.

**Comment by KoBeWi** [comment] 2019-11-19 15:30
I can't reproduce it in 3.1 nor 3.2.

**Comment by KoBeWi** [comment] 2019-12-02 13:42
@qarmin Could you confirm that it's no longer reproducible? >_>
The window just closes when you click outside.

**Comment by YeldhamDev** [comment] 2019-12-02 14:01
@KoBeWi Can't reproduce it anymore in Manjaro GNU/Linux.

**Comment by qarmin** [comment] 2019-12-02 17:46
I also can't reproduce this anymore

**Comment by KoBeWi** [comment] 2019-12-02 17:50
Ok, closing ¯\\\_(ツ)_/¯

**Closed by KoBeWi** 2019-12-02 17:50 UTC
Labels: bug, confirmed, crash, topic:editor
