### ISSUE TITLE
Godot steam rolls the entire project when saving if your hard drive is full

### ISSUE THREAD

**Issue by JayTheCoderX** [godotengine/godot#99312] opened 2024-11-16 10:36 UTC
### Tested versions

Reproductible in 4.3.stable and I'm assuming at least every other version of Godot 4. Probably 3 as well.

### System information

Godot v4.3.stable (77dcf97d8) - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 2070 (NVIDIA; 32.0.15.6603) - Intel(R) Core(TM) i5-9400 CPU @ 2.90GHz (6 Threads)

### Issue description

Occurred in version 4.3.stable. I'm assuming this is also the case for all other Godot versions but I haven't tested. So I don't know exactly what caused this, but the drive my Godot folder of the project I have been working on for almost a year was full (Steam was downloading an update for a game), but then godot tried to save the project while the drive was full- it then proceeded to crash. When I reopened it, I noticed that every single tscn and gdshader file had a file size of zero. Godot somehow erased all the contents of all gdshader and tscn files.

Side note: I feel like this could be fixed by when attempting to save a file, first make a copy, verify that the copy saved correctly, if it did then override the original, if that saves correctly then you can remove a copy. This would make it impossible for any file to become corrupt while attempting to save. Sorry if this isn't very coherent, I just lost almost a year of work, mostly my fault for not making a backup, but still.

### Steps to reproduce

1. Install satisfactory update with 4 gigabytes of free space
2. When your drive has 0 bytes free, press f5
3. Cry

### Minimal reproduction project (MRP)

Any project

**Comment by AThousandShips** [comment] 2024-11-16 10:47
See also:
* https://github.com/godotengine/godot/issues/45354

**Comment by JayTheCoderX** [comment] 2024-11-16 11:24
Notably, even files that shouldn't have been saved, like the shaders which weren't even open at the time, were wiped

**Comment by KoBeWi** [comment] 2024-11-23 11:05
> Side note: I feel like this could be fixed by when attempting to save a file, first make a copy, verify that the copy saved correctly, if it did then override the original, if that saves correctly then you can remove a copy.

This should be already happening and it's called "safe save". Sometimes it can fail when file is read-only and you are left with tmp files in your project; the original file is untouched.

**Comment by AThousandShips** [comment] 2024-11-23 11:07
The problem is that the safe save won't help if the engine doesn't detect that the file system is full, unless it does correctly detect failure and stops writing back

**Comment by KoBeWi** [comment] 2024-11-23 11:17
Shouldn't it fail at OS level though? In that case Godot would be able to handle it. Do apps normally account for full disk space?

**Comment by AThousandShips** [comment] 2024-11-23 11:19
I don't expect that would or should fail, it renames one file onto another I think, that should *reduce* the amount of data on the drive

**Comment by KoBeWi** [comment] 2024-11-23 11:23
No, but the safe save first writes a file and if writing fails, stops the operation; otherwise it renames it over old file. If that doesn't prevent errors, it means you can write the file with no enough space, in which case I assume it overwrites any files randomly.

**Comment by AThousandShips** [comment] 2024-11-23 11:26
That is the assumption yes, but unsure exactly how the detection works, and when things go wrong

It's possible that the OS causes issues due to temporary storage in memory before writing back etc.

Haven't dug into the small details here, and could be due to various issues with the detection and writing multiple files

Theoretically one part of the operation could fail because space ran out at a critical point etc.

Also depends on how the rename itself works, it might be the OS doesn't recover gracefully etc.

**Comment by AThousandShips** [comment] 2024-11-23 11:32
Not sure how the detection would work but the closing operation of `FileAccess` on windows doesn't check if any errors occured, so I'm not sure how this would recover assuming the file creation succeeded and then writing to the temporary file failed

So as long as the temporary file was created, any error writing to it meanwhile doesn't seem to matter, and the empty temporary file just overwrites the original 

I might be missing something in the code but I don't see anything that would prevent this scenario

**Comment by huwpascoe** [comment] 2024-11-23 11:51
Windows can create mountable vhd from the partition manager and Linux can do anything with ramdrives etc, so there's no reason why we can't test this problem.

**Comment by AThousandShips** [comment] 2024-11-23 11:57
Who said we couldn't test it? This discussion is relevant to pinpointing what the issue is specifically and the point of failure, and specifically that the safe save system isn't necessarily guaranteed to avoid this *depending* on what the low level operations are doing, which is something to test

**Comment by Calinou** [comment] 2024-11-23 13:34
Thanks for the report! Consolidating in https://github.com/godotengine/godot/issues/45354, as this is due to the same cause.

> Notably, even files that shouldn't have been saved, like the shaders which weren't even open at the time, were wiped

Godot likely attempted to save these files anyway, even if it's only to change their modification date. This will happen especially if you had shaders opened in the shader editor bottom panel, even if the bottom panel is currently collapsed.

There's an issue tracking this for `project.godot` in particular, but I can't find it right now.

**Closed by Calinou** 2024-11-23 13:34 UTC
Labels: bug, topic:core, topic:editor
