### ISSUE TITLE
Godot Freeze while clicking on "scene" menu.

### ISSUE THREAD

**Issue by DenisSalem** [godotengine/godot#44575] opened 2020-12-21 18:36 UTC
**Godot version :**
- Godot Engine v4.0.dev.custom_build.fe93f6292
- Using ICU / HarfBuzz / Graphite text server...

**OS/device including version :** Gentoo

- **Kernel** : 5.4.72
- **RAM** : 12Go
- **CPU** : Intel(R) Core(TM) i7-2600 CPU @ 3.40GHz
- **Graphic Card** : NVIDIA GTX 1060 3Gb
- **Graphic Driver** : x11-drivers/nvidia-drivers-455.28-r1
- **Window Manager** : i3 (feh is running in background updating wallpaper every 5s)

**Issue description:**
Launching Godot and creating / loading a fresh new project looks good. But when I try to interact with UI, like the main basic menu in the top-left corner, Not only it freezes for a couples of long seconds, but the entire system doesn't respond anymore. After a moment I can get back my hands on a tty and kill the process which is still frozen.

The curious thing is that, on the other hand, the 3D viewport is very smooth and effective.

There is no errors output displayed, when launched from a tty.

**Steps to reproduce:**
Clicking, let's say, on the "scene" top-left menu trigger the freeze.

**Minimal reproduction project:**
None required

**Comment by Zireael07** [comment] 2020-12-21 19:15
NVIDIA driver 455? Did you run a search? I think that is a duplicate of already reported NVIDIA driver issue...

**Comment by Calinou** [comment] 2020-12-21 22:03
Duplicate of https://github.com/godotengine/godot/issues/41614.

**Closed by Calinou** 2020-12-21 22:03 UTC

**Comment by DenisSalem** [comment] 2020-12-21 22:27
Well I did a research. But not with those keywords. My bad

I assume you refer to this : https://github.com/NixOS/nixpkgs/pull/107345

**Comment by fabianhjr** [comment] 2020-12-21 22:36
Hi @DenisSalem, the PR you mention bumps the Nvidia Vulkan Beta drivers on NixOS; however this issue report mentions nvidia-drivers-455.28-r1 which isn't listed on https://developer.nvidia.com/vulkan-driver but rather on the stable/mainline releases: https://www.nvidia.com/Download/driverResults.aspx/165689/en-us.

**Comment by DenisSalem** [comment] 2020-12-21 22:40
Ok... Sorry.

Anyway, thank you for the tips about the single window mode :)
