### ISSUE TITLE
FileDialog: Having 10000+ elements makes the game unresponsive

### ISSUE THREAD

**Issue by PerikiyoXD** [godotengine/godot#80336] opened 2023-08-06 13:56 UTC
### Godot version

v4.1.1.stable.mono.official [bd6af8e0e]

### System information

Godot v4.1.1.stable.mono - Windows 10.0.19044 - Vulkan (Compatibility) - NVIDIA GeForce GTX 1050 Ti (NVIDIA; 31.0.15.3203) - 11th Gen Intel(R) Core(TM) i5-11400 @ 2.60GHz (12 Threads)

### Issue description

I'm making an Import/Export tool, and I need to select files.

Actually, I have folders with up to 10000 files, and when I open the folder, the game window will freeze.

![imagen](https://github.com/godotengine/godot/assets/3116368/8dfe9056-bd82-4be7-8808-c0c78ef14770)

Another folder with 3000 files works fine.

This is unusable and probably is caused by instancing so many "TreeItem" elements in the "FileDialog".

Please, don't hesitate to ask for more context or details, and/or performance profiling information (I don't know how to run those efficiently)

### Steps to reproduce

Start with a fresh project
- Create a folder with 10000+ files in your filesystem (All files must use the same extension)
- Create a scene and add a FileDialog
- Adjust the FileDialog to filter by extension of choice
- Run the app, and navigate to the folder. Start scrolling down and it'll freeze the app window.

### Minimal reproduction project

Use steps to reproduce.

**Comment by PerikiyoXD** [comment] 2023-08-06 14:05
Tried to profile the 3000 file folder. I keep scrolling till the end and this spike happens. Frames drop to ~15fps
![imagen](https://github.com/godotengine/godot/assets/3116368/ac4d8ca1-31cf-4856-85bf-159313dd647f)

**Comment by PerikiyoXD** [comment] 2023-08-06 14:15
More insight, It's spiking the Physics Process.
![imagen](https://github.com/godotengine/godot/assets/3116368/a9676695-2dcf-4c1c-b6e6-a9f0b4a72b09)
First "red section" is slow scrolling, last part is where I just scroll all the time nonstop, and killed the app directly.

It's caused by Physics Processing.

**Comment by dalexeev** [comment] 2023-08-06 15:14
* See #79325.

**Comment by PerikiyoXD** [comment] 2023-08-06 15:36
Just built godot on 4.2.0-dev (master/main) and works flawlessly.

**Comment by dalexeev** [comment] 2023-08-06 16:20
Duplicate of #79292 and/or #79927, fixed by #79325.

**Closed by dalexeev** 2023-08-06 16:20 UTC
Labels: enhancement, topic:gui, performance
