### ISSUE TITLE
System crash when printing null returned from another method

### ISSUE THREAD

**Issue by codespren** [godotengine/godot#37407] opened 2020-03-29 12:24 UTC
**Godot version:**
3.2.1

**OS/device including version:**
Mac OS Catalina 10.15.3

**Issue description:**
When printing a variable in C# code with GD.Print() the operating system crashes if variable to be printed is null and was returned from another method.
Godot editor doesn't print any error message but just hangs.
If Godot was started from the console then there's following error:

`=================================================================
	Native Crash Reporting
=================================================================
Got a SIGSEGV while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries 
used by your application.
=================================================================

=================================================================
	Native stacktrace:
=================================================================
	0x104ad2388 - /Applications/Godot_mono.app/Contents/MacOS/Godot : mono_dump_native_crash_info
	0x104ac5bf5 - /Applications/Godot_mono.app/Contents/MacOS/Godot : mono_handle_native_crash
	0x104ad97ef - /Applications/Godot_mono.app/Contents/MacOS/Godot : mono_sigsegv_signal_handler_debug
	0x7fff696c542d - /usr/lib/system/libsystem_platform.dylib : _sigtramp
	0x7fbc3b5e5960 - Unknown
	0x10530a7dc - /Applications/Godot_mono.app/Contents/MacOS/Godot : _ZN13GDMonoMarshal29mono_object_to_variant_stringEP11_MonoObjectPP14_MonoException
	0x105287b97 - /Applications/Godot_mono.app/Contents/MacOS/Godot : _Z20godot_icall_GD_printP10_MonoArray
	0x121d0b569 - Unknown

=================================================================
	Telemetry Dumper:
=================================================================
Pkilling 0x700009b8c000 from 0x10ef47dc0
Pkilling 0x700009d8f000 from 0x10ef47dc0
* Assertion: should not be reached at threads.c:6254
Entering thread summarizer pause from 0x10ef47dc0
Finished thread summarizer pause from 0x10ef47dc0.
debugger-agent: Unable to listen on 41

Waiting for dumping threads to resume

=================================================================
	External Debugger Dump:
=================================================================
(lldb) command source -s 0 '/tmp/mono-gdb-commands.737'
Executing commands in '/tmp/mono-gdb-commands.737'.
(lldb) process attach --pid 737
`

After crash, Mac OS's Activity monitor doesn't display any processes and whole system becomes more or less unresponsive and only way to recover is to force hard reset by physical power button.

**Steps to reproduce:**
1. Start minimal project included
2. Crash

**Minimal reproduction project:**

[nullCrashProject.zip](https://github.com/godotengine/godot/files/4398851/nullCrashProject.zip)

**Workaround:""

Print variables with GD.Print("" + object); instead of GD.Print(object);

**Comment by Jiaming00** [comment] 2020-03-30 08:12
I tried, anyway, the console outputs an error, the list of objects in the String.ConvertAll parameter cannot have null.

**Comment by asmaloney** [comment] 2020-07-21 18:40
As another data point, I tried with the attached project and it runs properly for me. It outputs "null" in the console.

Godot Engine v3.2.3.beta.mono.custom_build.af35d0d3c

macOS 10.14.6

(Aside: I'm not sure how to find the mono version being used... is that accessible somewhere? The logs are referencing `/Library/Frameworks/Mono.framework/Versions/Current/lib/mono/4.5/`, but no actual version is output anywhere I can find.)

**Comment by akien-mga** [comment] 2020-07-21 19:12
Duplicate of #37309, fixed by #40078. It's fixed in the `3.2` branch for 3.2.3 as tested by @asmaloney.

**Closed by akien-mga** 2020-07-21 19:12 UTC
Labels: bug, crash, needs testing, platform:macos, topic:editor, topic:mono
