### ISSUE TITLE
Play Edited Scene overwrites scene in first tab

### ISSUE THREAD

**Issue by zinkkrysty** [godotengine/godot#10698] opened 2017-08-27 20:17 UTC
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Godot 3 bd282ff43f23fe845f29a3e25c8efc01bd65ffb0
MacOS 10.12.6

**Issue description:**
I wanted to play the current edited scene, but the editor saved the current scene over my previous scene.

**Steps to reproduce:**
1. Create a project with multiple scenes
2. Open a scene, press the Play Edited Scene button
3. Open another scene while leaving the first one opened as well in a tab
4. With the 2nd scene active in the tabs, press the "Play Edited Scene" button again.
5. After the scene plays, Godot has replaced my 1st scene with the 2nd one. (seems like this happens only for the first tab, also notice the error in the Output panel when closing the last tab)

**GIF of the whole process**
![godot3_weird_scene_mixup_2](https://user-images.githubusercontent.com/570771/29753580-7aab7b7a-8b74-11e7-823e-e03bb10511e0.gif)

**Link to minimal example project:**

[Godot3FirstGame.zip](https://github.com/godotengine/godot/files/1254696/Godot3FirstGame.zip)

**Comment by Zylann** [comment] 2017-08-27 20:43
Duplicate of #10675

**Closed** 2017-08-27 20:44 UTC
Labels: archived
