### ISSUE TITLE
Meshes that have gone through the 4.0 project converter have broken lighting and other issues.

### ISSUE THREAD

**Issue by KnightNine** [godotengine/godot#75119] opened 2023-03-19 21:17 UTC
### Godot version

4.0

### System information

Windows 10

### Issue description

Shadows seem to be inverted on meshes which have gone through the project converter. (as opposed to the ones I have re-imported from blender)
![broken lighting](https://user-images.githubusercontent.com/34152090/226209074-4930f700-9766-4aa4-acc7-f7f6cc572048.PNG)

Also the `grow` property of materials attached to these converted meshes results in this mess:

 
![4 0](https://user-images.githubusercontent.com/34152090/226209242-f24669cd-09b7-44d4-9531-09a8f3a3773b.PNG)

when it should look like this:

![3 5](https://user-images.githubusercontent.com/34152090/226209406-9b186fbc-e0ee-4ec6-8fb3-8fb8cff935ec.PNG)

This makes the converted meshes useless for most models in my project.

### Steps to reproduce

Convert a project containing mesh files to 4.0 using the project converter.

### Minimal reproduction project

here's a mesh for 3.5 that you can test this with:
[Mesh-Path Point.zip](https://github.com/godotengine/godot/files/11012316/Mesh-Path.Point.zip)

**Comment by Calinou** [comment] 2023-03-19 21:49
- Duplicate of https://github.com/godotengine/godot/issues/63550 (same cause).

**Closed by Calinou** 2023-03-19 21:49 UTC
