### ISSUE TITLE
Expose ENet peer timeout settings

### ISSUE THREAD

**Issue by supagu** [godotengine/godot#20056] opened 2018-07-09 04:50 UTC
*Bugsquad edit:* This issue is about exposing http://enet.bespin.org/group__peer.html#gac48f35cdd39a89318a7b4fc19920b21b

----

So using the latest godot master branch. I'm working on a multiplayer game. Now sometimes I get about half an hour in to the game and there is a lag spike then I get a disconnect as a result.

It seems as if some packet exceeds its timeout, which causes a disconnect by the server. The client then locks up in PacketPeerUDPPosix::_poll while it waits for recvfrom (which is meant to be non-blocking? so how it can block there is beyond me). After about 30 seconds the client will continue and detect the disconnect. During this time, the game is totally locked up. I can't even get a signal to be emitted that the client is waiting for the server. This should be fixed.

More importantly, there should be a way to change the timeout settings for ENET. It seems a packet has about 1.6 seconds to be acknowledged as being received from the client, so that means its got about 0.8seconds to get tot he client, then 0.8seconds back at most. Any longer and then server will drop them.

Exposing a timeout would allow me to better handle low frame rates, playing over the internet. It would also allow me to easier to debug the network code - I would be able to set a break point and examine code and resume a multiplayer game without the fear of hitting a break point followed by a sudden disconnect.

**Comment by alex9099** [comment] 2018-07-10 20:49
Would you mind creating a test project were this happens?

**Comment by supagu** [comment] 2018-07-11 01:33
[NetworkTest.zip](https://github.com/godotengine/godot/files/2182660/NetworkTest.zip)

You will need to edit the IP your connecting to in the script on the CanvasLayer.
I emulate a low frame rate, combined with a method taking a different amount of time on the client vs the server - which really seems to be the killer.

Once the client is disconnected, the whole app becomes unresponsive.

**Comment by alex9099** [comment] 2018-07-11 22:57
I can reproduce the disconnect part, but for me it is not freezing after disconnecting,

I'm still trying to figure it out (i can't fully understand the implementation), but @Faless might be able to help :)

**Comment by Faless** [comment] 2018-07-12 01:19
@supagu 
In the example provided:
- There is delay in `_process`.
- Then there is delay in `do_it_everywhere`.
- In `do_it_everywhere` one of the two peers (the server in this case) has less delay than the client.
- Which means it generate more calls to `do_it_everywhere` overall for the client.
- Which in turns generate even more delay in the client.
- Up to a point, when there are, say, 40 calls executed in a single `_process` in the client.
- Which generates > 30 secs delay in a single `_process` (we are talking 0.025 FPS).

And THEN the clients disconnect.
This is normal behaviour, your client shouldn't freeze for such a long time.
And in any case, the example generate a strictly increasing amount of delay. So no matter what you do, given enough time, it will timeout.

> The client then locks up in PacketPeerUDPPosix::_poll while it waits for recvfrom

It shouldn't lock there, how do you know that is actually the function where it locks? Did you get a stack trace?
Do you have any `OS.delay_usec` or `OS.delay_msec` in your project? At least in the example, that where it "locks" (as explained above, and tested with a debugger)

**Comment by Faless** [comment] 2018-07-12 13:54
Recvfrom is not specific to Linux, it's in basically every network stack
(both Linux/OSX and Windows).
But my question was, how do you know that: "the lockup seems to be coming
from recvfrom"?

**Comment by supagu** [comment] 2018-07-12 22:51
Every time it is locked up, when i break with my IDE (qt) that is where the call stack points me.

**Comment by OvermindDL1** [comment] 2018-07-12 22:58
> Every time it is locked up, when i break with my IDE (qt) that is where the call stack points me.

You sure it is just not grabbing the wrong thread or so?

**Comment by supagu** [comment] 2018-07-12 23:01
Im pretty sure it is the primary thread. I think recvfrom is only called by the primary thread.

**Comment by Faless** [comment] 2018-09-02 15:31
@supagu you are right, after further investigation I found out that when the client disconnected, it would try to reopen the connection, but without setting the non-block option on the socket, causing the **locking**. The is fixed in #21692 .


I suggest we move the discussion on the ENet Timeout setting to #21121 where they propose to set the timeout to `0`. Keep in mind that the MultiplayerAPI is polled once each frame and flushes all pending packets.

**Comment by Wavesonics** [comment] 2020-04-24 03:19
Is this planned for 4.0?

**Comment by Calinou** [comment] 2020-04-24 07:55
@Wavesonics There's an open [pull request](https://github.com/godotengine/godot/pull/35349) that implements this, it just needs to be merged.

**Comment by goatchurchprime** [comment] 2020-11-18 18:43
It would really help if there was a logged error or message when the server decides to kick a client off for the reason of timeouts so that I would more quickly be able to identify the problem and know what to look for.  Otherwise the source of these drop-outs is mysterious.  

Maybe also a message on the client in debug mode when the polling interval between two frames is dangerously high or spiked up so we can learn about problems and risks long before we get too deep into a project when debugging becomes harder.  

I think I'm getting large delays from a call to ` ResourceLoader.load()` on a 7Mb image file.  Time to learn about the `ResourceInteractiveLoader` I guess to see if it makes a difference.  It's frustrating that I am not even certain that this has anything to do with my problem.  For example, if I make a busy wait loop in GDscript does polling continue between the script commands?  I don't know what the best way to temporarily stall my program on a key-press to simulate the this delay in networking traffic.

**Comment by Calinou** [comment] 2020-11-18 21:53
> Edit: My problem is actually an Image.load() on a downloaded file. ResourceLoader doesn't seem to work on it.

Use the `Image.load_*_from_buffer()` methods to load images from a network resource.

**Comment by goatchurchprime** [comment] 2020-11-19 09:27
I experimented with that as well.  The decoding the jpg file into an image using that function takes 450ms in my example, while the loading of the PoolByteArray from the file is instantaneous.  I'm going to see if threading deals with it.

**Comment by Calinou** [comment] 2020-11-19 18:32
I ran a profiler over a project that loads a 600 KB JPEG image 20 times, here are the functions using the most CPU time:

![image](https://user-images.githubusercontent.com/180032/99708315-f85cde80-2a9d-11eb-907d-f8bfbc2526b7.png)

**Comment by goatchurchprime** [comment] 2020-11-19 19:03
The exact file I was having trouble with was this one:
 http://cave-registry.org.uk/svn/NorthernEngland/ThreeCountiesArea/rawscans/leckfellaerial.jpg

**Closed** 2021-02-27 15:45 UTC
Labels: enhancement, topic:network
