### ISSUE TITLE
"Clear Script" doesn't show up anymore

### ISSUE THREAD

**Issue by YeldhamDev** [godotengine/godot#20590] opened 2018-07-30 03:06 UTC
**Godot version:**
 5a5614e

**Issue description:**
When selecting a node that has a script the "Attach Script" icon switched to "Clear Script", now it doesn't:
![screenshot at 2018-07-30 00-05-21](https://user-images.githubusercontent.com/30739239/43375569-50130e8e-938c-11e8-9e6c-0330bbf8b17c.png)
How it's supposed to look:
![screenshot at 2018-07-30 00-07-25](https://user-images.githubusercontent.com/30739239/43375632-a2e2b7a4-938c-11e8-802b-fc72db20f464.png)

**Comment by bojidar-bg** [comment] 2018-07-30 06:14
Byproduct of #20233, now the add-script button would automatically populate the "extends" field to the path of the script.

**Comment by willnationsdev** [comment] 2018-08-13 12:04
Yes, I specifically brought this up with reduz, and he said that he would rather the clear script button go away entirely instead of showing both it AND the add script button. You still have access to clearing a script from the right-click context menu and from the Inspector's "script" property and it was an infrequent-enough operation that he thought that would be acceptable.

I guess the question remains: is there enough public outcry over this change that people want to show both of the icons at once?

**Comment by akien-mga** [comment] 2018-08-13 12:07
Why is the "Add script" shown when there's already a script though?

**Comment by willnationsdev** [comment] 2018-08-13 12:41
Because clicking the add script button on a node that already has a script now auto-fills the inherits field of the ScriptCreateDialog, for easier creation of derived scripts. This is especially useful for deriving g from script classes, which can be inherited from by name.

**Comment by akien-mga** [comment] 2018-08-13 12:44
So if a node has script A attached, you click the "Add script" again, it will propose to create a new script B to replace the attached A, which inherits from A?

That seems a bit weird usability wise to me, I'm not sure it's a good design. At least it's not the workflow I would expect when I want to attach a script to a node that should inherit a base script.

**Comment by willnationsdev** [comment] 2018-08-13 12:49
That's the functionality I would have expected. Would you expect there to be a separate button created with a new icon, that conditionally shows up instead of the add script button, but does the same thing? So basically just change the icon?

**Comment by akien-mga** [comment] 2018-08-13 12:52
I don't know, I just came back from holidays and maybe need to test the feature before criticizing ;)

As is I don't really see why the "common" use case for scripts inheriting another script would be to have the base script assigned first, and then replace that, instead of adding the new script directly without having to assign this base script before.

I understand the potential workflow if you have e.g. a base enemy.tscn with enemy.gd, and you create an inherited scene bat.tscn where you want to attach bat.gd that inherits enemy.gd - but is that really the main workflow for this feature?

**Comment by YeldhamDev** [comment] 2018-08-13 21:58
I think the icon and tooltip should change when in "inherit" mode.

Also, when I try to use it, it just says that the inherited parent name/path is invalid.

**Comment by willnationsdev** [comment] 2018-08-13 22:14
Oh, well that since a bug. XD

**Comment by PLyczkowski** [comment] 2018-09-11 20:28
Inherit script icon could use something like this instead of a +
![images](https://user-images.githubusercontent.com/7307968/45385782-01c2a480-b612-11e8-8056-98596ab380e8.png)

**Comment by willnationsdev** [comment] 2018-09-11 20:40
Yeah, I know akien proposed changing the icon when deriving. I'm not sure who "approves" visual designs like that though.

**Comment by bojidar-bg** [comment] 2018-09-12 06:32
CC @djrm

**Comment by Chaosus** [comment] 2018-09-13 18:38
IMO it had more intuitive behavior in 3.0.6 than now in 3.1...

**Comment by willnationsdev** [comment] 2018-09-13 19:56
@Chaosus Yeah, I would've just kept them both personally, but it's not my call.

**Comment by williamd1k0** [comment] 2018-09-13 20:07
I prefer the old behavior (and I remember cherry-picking this feature for the 2.1 branch), but the new workflow also looks interesting so I would opt for the second option:

>Keep the "add script"/"clear script" toggle, and add an additional button when selecting a node with an existing script with this "inherit script" icon.

**Comment by willnationsdev** [comment] 2018-09-28 13:41
@JustusPan I agree. I'm not sure what the workflow is to add new icons to the editor though. Has something to do with creating an SVG, optimizing it with a utility, and then adding it to /editor/icons. But then there's also the `godot-design` repository and idk how that's involved.

**Comment by willnationsdev** [comment] 2018-10-16 16:51
@akien-mga Speaking of which, @PLyczkowski created an icon and forwarded it to me. I have added an optimized copy of the .svg file to a [godot-design branch of mine](https://github.com/willnationsdev/godot-design/tree/script-extend), but I'm not sure how I'm supposed to integrate that with the editor. Am I supposed to just submit a separate PR to update the `/editor/icons` directory with the same .svg file?

**Comment by groud** [comment] 2018-10-19 09:45
I prefer the old behavior too. Inheriting a script is not common at all. The add script button here to "create a script that inherits the previous one and then replace it" has quite an unexpected behavior.

I would probably make this a RMB menu entry and either remove the button when the node has a script or bring back the delete script button.

**Comment by willnationsdev** [comment] 2018-10-19 12:42
Perhaps some people use it more than others then, cause I know it's an important feature for my use-cases. But a lot of people have been confused by the change, so either having both buttons or switching to a RMB option sounds pretty good.

**Comment by PLyczkowski** [comment] 2018-10-19 12:57
It is very common for me. @groud Are you testing with the new icon? It should be pretty obvious then when you are adding a new script and when you are extending. But I'm ok with it being an RMB menu entry if it's confusing even with a separate icon.

**Comment by willnationsdev** [comment] 2018-10-19 13:01
@PLyczkowski The new icon isn't actually present yet. I have a branch on my godot-design repo with it, but I haven't heard back from anyone about what I'm actually *supposed* to do with the icon. The documentation on "adding icons to the editor" isn't really consolidated/clear.

**Comment by PLyczkowski** [comment] 2018-10-19 13:11
I understand the confusion about the functionality then.

**Comment by willnationsdev** [comment] 2018-10-19 13:17
@PLyczkowski I'm going to submit a PR soon that adds the icon. We'll see what people think about it then. Don't even know if I'm doing it "right". <_< Just copy/pasting the optimized SVG to the editor/icons folder and hoping that does the trick...

**Comment by akien-mga** [comment] 2018-10-19 13:45
The README seems understandable to me: https://github.com/godotengine/godot/blob/master/editor/icons/README.md
Make PR on the godot-design repo with the sources, optimize the SVG and put the optimized SVG in `editor/icons`.

**Comment by akien-mga** [comment] 2018-10-19 13:46
The README seems understandable to me: https://github.com/godotengine/godot/blob/master/editor/icons/README.md
Make PR on the godot-design repo with the sources, optimize the SVG and put the optimized SVG in `editor/icons`.
(`git log editor/icons` can also give you some hints :))

**Comment by willnationsdev** [comment] 2018-10-19 13:51
@akien-mga Oh, a README in `/editor/icons`, of course! I checked around godot-design, but didn't understand how any of the stuff was so supposed to tie back into the main godot repo. *Feels stupid now*

Sounds like my guess turned out to be right then, lol.

**Comment by willnationsdev** [comment] 2018-10-19 17:38
@akien-mga It doesn't actually close the issue though. It just adds an extends icon so that we can test whether people are satisfied with that or if they still want the old button setup.

**Comment by akien-mga** [comment] 2018-10-19 18:43
Well, you did that :)
![screenshot_20181019_204319](https://user-images.githubusercontent.com/4701338/47237508-9d98ba80-d3df-11e8-836c-9a309848dee8.png)

**Comment by willnationsdev** [comment] 2018-10-19 18:53
Oh, does putting "close" in it *automatically* close it?? TIL...whoops. I'll keep that in mind.

I'll have to google if there's a list of keywords like that and be more mindful in the future. Thanks for the heads-up.

**Comment by akien-mga** [comment] 2018-10-19 19:08
Yep: https://help.github.com/articles/closing-issues-using-keywords/

**Comment by QbieShay** [comment] 2018-10-25 07:57
@willnationsdev I agree with @groud . I am using Godot extensively and refactoring is way slower without a fast way to clear a script.

**Closed** 2018-10-29 11:16 UTC
Labels: discussion, enhancement, usability
