### ISSUE TITLE
The toggle button add/remove script DOESN'T remove

### ISSUE THREAD

**Issue by xDGameStudios** [godotengine/godot#22998] opened 2018-10-14 00:55 UTC
**Godot version:**
3.1.alpha.calinou.4c1a5d9

**OS/device including version:**
MacOSX 

**Issue description:**
The button that adds/remove (toggles) scripts from a node doesn't change icon or behavior. It adds the script but it doesn't remove it. The script can be removed scrolling to script under node properties and using "Clear" though..

**Images:**
<img width="224" alt="captura de ecra 2018-10-14 as 01 54 24" src="https://user-images.githubusercontent.com/10358443/46911447-1ddc9d00-cf54-11e8-9736-37770e9827ac.png">

the icon doesn't change to the remove icon nor does it remove the script.

**Comment by dejaime** [comment] 2018-10-14 01:02
I can reproduce this on Linux and version 3.0.6 stable. If you click the add script it does add, but if you click it _right away_ to remove the script, it simply doesn't. If you re-select the node on the scene hierarchy it works as expected.

**Comment by xDGameStudios** [comment] 2018-10-14 01:34
well in version 3.1.apha and in MacOSX as I described, it doesn't work! Even if I re-select the node!

**Comment by akien-mga** [comment] 2018-10-16 12:38
Duplicate of #20590.

**Closed by akien-mga** 2018-10-16 12:38 UTC
