### ISSUE TITLE
Play the project (F5) sometimes invokes the project list

### ISSUE THREAD

**Issue by Waasha** [godotengine/godot#14598] opened 2017-12-12 17:11 UTC
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Windows 7 64bit, Godo 3.0 Beta

**Issue description:**

When the "Play the project" button, or F5 is pressed, it sometimes invokes the project list window, even though the Main scene is selected in preferences.
Expected Behavior: The Main scene should always be played.

**Steps to reproduce:**
Create any Scene, save it, set it as Main scene and try to Play the project few times.

**Comment by Zireael07** [comment] 2017-12-12 17:12
Duplicate of issue #11391, fixed in master

**Closed** 2017-12-12 17:41 UTC
