### ISSUE TITLE
Unable to connect two blendSpace2D in animationTree

### ISSUE THREAD

**Issue by NervousTic** [godotengine/godot#66204] opened 2022-09-21 10:04 UTC
### Godot version

4.0 beta 1

### System information

Windows 10

### Issue description

I'm following this tutorial (https://www.youtube.com/watch?v=Luf2Kr5s3BM&t=490s) and I can not connect the two blendSpace2D as shown in this video ( 30min 30 seconds)

### Steps to reproduce

Add animation in animationPlayer
Create a animationTree
Add two blend2DSpace
try to connect them

**Comment by TokageItLab** [comment] 2022-09-21 11:04
Dupe of #65988.

**Closed by TokageItLab** 2022-09-21 11:04 UTC
