### ISSUE TITLE
Global content stretch mode setting not respected in popups

### ISSUE THREAD

**Issue by tianer2820** [godotengine/godot#78892] opened 2023-07-01 01:33 UTC
### Godot version

v4.0.3.stable.mono.official [5222a99f5]

### System information

Linux (Fedora KDE)

### Issue description

Global content stretch mode setting not respected in popups. When the global content stretch mode is set to canvas item, the popup menu still scales using the canvas mode, resulting in blurry texts in popup menus

### Steps to reproduce

1. Start a new project, set the default window size to something small, like 300x200, then set content stretch mode to canvas item in project settings
2. Add an option button to the main scene, add some text items in the option button
3. Lunch the scene, scale up the window
4. Click on the option button. Every text in the main viewport is clear and sharp, but the option menu is blurry.

### Minimal reproduction project

[test.zip](https://github.com/godotengine/godot/files/11923921/test.zip)

**Comment by Sauermann** [comment] 2023-07-01 05:54
I believe, that this is a duplicate of #54030

**Closed** 2023-07-01 08:49 UTC
