### ISSUE TITLE
script horizontal scrolling broken

### ISSUE THREAD

**Issue by romulox-x** [godotengine/godot#2100] opened 2015-06-15 22:30 UTC
This seems to be related to the new dock layout, with docks on the left side of the window.  The script editor won't scroll all the way to the right unless you move the cursor there.  It's missing about the same distance as the width of the left dock, which makes me think the dock area is not being taken into account.

**Comment by Suitecake** [comment] 2015-07-17 17:00
This is a duplicate of #1663

**Comment by romulox-x** [comment] 2015-08-03 01:29
It's noteworthy that my issue only appeared after the dock rearranging changes were pushed, which happened after that issue was submitted.  I never had any problems scolling to see all of my text before this push.  So it sounds to me like similar issues with different causes.

**Comment by akien-mga** [comment] 2015-11-22 13:51
I can't reproduce this issue in the current master branch (on Linux X11), so I'll assume it is fixed. Feel free to reopen or ask me to reopen if you can still reproduce it (it might be platform-dependent).

**Closed by akien-mga** 2015-11-22 13:51 UTC
Labels: bug, topic:editor, usability
