### ISSUE TITLE
Using constructor in a class extended from Resource causes an error

### ISSUE THREAD

**Issue by Skyofflad** [godotengine/godot#64902] opened 2022-08-25 18:51 UTC
### Godot version

4.0 alpha 14

### System information

Kubuntu 20.04

### Issue description

I can't summarize this problem, so I will list steps to reproduce it
1. Create a class, extended from Resource and override it's _init() function
```gdscript
extends Resource

class_name ResTestOne

@export var string: String
@export var num: int

func _init(s, n):
	string = s
	num = n
```
2. Create an instance of it
```gdscript
var resOne: ResTestOne = ResTestOne.new('a', 1)
```
3. Assign it to a variable in another resource and save it on disk
```gdcript
var file := SaveFile.new()
	file.resOne = resOne
	ResourceSaver.save(file, "res://save.tres")
```
When I try to load it
```gdcript
var loaded_file := load("res://save.tres")
```
game crashes and shows this error:
```
E 0:00:00:0780   _ready: Error constructing a GDScriptInstance.
  <Ошибка C++>   Method/function failed. Returning: nullptr
  <Исходный код C++>modules/gdscript/gdscript.cpp:183 @ _create_instance()
  <Трассировка стека>main.gd:14 @ _ready()
```
But if I do not override it's _init() function, everything works fine:
```gdcript
var resTwo: ResTestTwo = ResTestTwo.new()
	resTwo.string = 'a'
	resTwo.num = 1
	var file := SaveFile.new()
	file.resTwo = resTwo
	ResourceSaver.save(file, "res://save.tres")
	var loaded := load("res://save.tres")
```
But the contents of the Save file look exactly the same for both resources:
```
[gd_resource type="Resource" load_steps=6 format=3]

[ext_resource type="Script" path="res://ResTestOne.gd" id="1_8gc2v"]
[ext_resource type="Script" path="res://ResTestTwo.gd" id="2_mydiv"]
[ext_resource type="Script" path="res://Savefile.gd" id="3_qma2a"]

[sub_resource type="Resource" id="Resource_g0ply"]
script = ExtResource("1_8gc2v")
string = "a"
num = 1

[sub_resource type="Resource" id="Resource_7co2k"]
script = ExtResource("2_mydiv")
string = "a"
num = 1

[resource]
script = ExtResource("3_qma2a")
resOne = SubResource("Resource_g0ply")
resTwo = SubResource("Resource_7co2k")
```

### Steps to reproduce

above

### Minimal reproduction project

[ResourceConstructorTest.zip](https://github.com/godotengine/godot/files/9427494/ResourceConsructorTest.zip)

**Comment by Calinou** [comment] 2022-08-25 20:23
It might be worth checking for duplicates in this list: https://github.com/godotengine/godot/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+resourcesaver+label%3Abug

**Comment by jtnicholl** [comment] 2022-08-25 23:52
When loading resources from disk ResourceLoader calls the constructor with no arguments. It won't work if you add any parameters to `_init` without default values.
You can still have arguments, but they need default values. So this won't work:
```gdscript
func _init(s, n):
```
But this should:
```gdscript
func _init(s = "", n = 0):
```

**Comment by Skyofflad** [comment] 2022-08-26 07:09
Oh, it makes sense now
So it's not a bug then?

**Comment by jtnicholl** [comment] 2022-08-27 15:30
I don't think it is, it's even mentioned in the docs.
https://docs.godotengine.org/en/stable/classes/class_object.html#class-object-method-init
Could definitely use a more helpful error message.

**Comment by Calinou** [comment] 2022-08-27 15:49
Duplicate of https://github.com/godotengine/godot/issues/15866 (same cause).

**Closed by Calinou** 2022-08-27 15:49 UTC
Labels: bug, topic:gdscript
