### ISSUE TITLE
Collision solver issue with some ConvexPolygonShape2D?

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot#5745] opened 2016-07-16 23:43 UTC
**Operating system or device - Godot version:**
Mageia 6 x64, Godot 2.0.4.1 and master HEAD.

**Issue description** (what happened, and what was expected):
Characters seem to get stuck in ConvexPolygonShape2Ds with a shape like that:
![cku5noj80](https://cloud.githubusercontent.com/assets/4701338/16897840/747e95b6-4bbf-11e6-96c1-8d91d151de3f.png)
or that:
![spectacle m21132](https://cloud.githubusercontent.com/assets/4701338/16897847/b5b6c5f8-4bbf-11e6-9260-82785e727e81.png)

Note that the same outline drawn as a _Concave_PolygonShape2D works just fine.

**Steps to reproduce:**
- Open attached project in the editor
- Toggle visible collision shapes
- Go to the bottom with the arrow keys, then run left or right in one of the tiles with the problematic collision shape
- See that you get stuck

**Link to minimal example project** (optional but very welcome):
[convexpolygon_bug.zip](https://github.com/godotengine/godot/files/367597/convexpolygon_bug.zip)

**Comment by Zylann** [comment] 2016-07-17 01:46
The shapes are concave. Isn't ConvexPolygonShape2D not supposed to handle these?

**Comment by TheoXD** [comment] 2016-07-17 10:50
You've discovered a black hole xD It is sucking in the object literally.

**Comment by akien-mga** [comment] 2016-07-17 11:08
> The shapes are concave. Isn't ConvexPolygonShape2D not supposed to handle these?

I also wondered about this, but I showed the screenshot to @reduz and he agreed it looks weird, so I preferred opening an issue to get to the bottom of this. I'm not sure how the convex/concave notions should be understood for the collision shapes. Here clearly this specific curve is concave, but does it make the whole shape a "concave shape"? What about a shape with a concave curve followed by a convex curve?

**Comment by TheoXD** [comment] 2016-07-17 11:17
I just changed the indices order and it works as intended, only collision is not visible on debug (probably because of the order change and faces being one sided)

**Comment by bojidar-bg** [comment] 2016-07-17 11:22
Well, the definition of "convex region" is to be unable to find any segment that has its both ends inside the region, but is not a subset of the region (i.e. doesn't cross to the other side of the boundary).

In this sense, @akien-mga's idea of having a concave curve and then a convex curve fails, since you are still able to draw such a segment.

**Comment by akien-mga** [comment] 2016-07-17 11:32
So I guess this shape would have undefined behaviour:
![spectacle hv4572](https://cloud.githubusercontent.com/assets/4701338/16900346/eb1cafa6-4c22-11e6-9b6f-0781f22452ff.png)

**Comment by TheoXD** [comment] 2016-07-17 12:02
@akien-mga, it's still the same invalid convex as in the test project, since angle between two edges is too extreme (in this case over 180 degrees). Flipping normal only those edges should fix the problem.

**Comment by Zylann** [comment] 2016-07-17 12:38
Just curious, is there a reason Concave and Convex are separated? If we had only one, there shouldn't be wrong cases when drawing it if the engine can detect it's concave or convex.

**Comment by eon-s** [comment] 2017-11-19 20:14
This affects master too, OP example ported to 3:
[convexpolygon_bug_v3.zip](https://github.com/godotengine/godot/files/1485934/convexpolygon_bug_v3.zip)

**Comment by samdze** [comment] 2018-03-05 20:46
The bug appears with `move_and_slide` too. It's really annoying, at this point concave shapes can't be used in tilemaps.

**Comment by Calinou** [comment] 2020-06-07 19:31
@akien-mga Can you (or anyone else) still reproduce this bug in Godot 3.2.1 or [3.2.2beta4](https://godotengine.org/article/dev-snapshot-godot-3-2-2-beta-4)?

**Comment by eon-s** [comment] 2020-06-08 05:09
I could not reproduce it on latest beta with `move_and_collide` nor `move_and_slide`, using the ported example.

**Comment by Calinou** [comment] 2020-06-08 07:33
@eon-s Alright, closing then.

**Closed by Calinou** 2020-06-08 07:33 UTC
Labels: bug, topic:physics
