### ISSUE TITLE
Input.get_action_strength autocompletion adds too many quotes at the end

### ISSUE THREAD

**Issue by titusio** [godotengine/godot#71030] opened 2023-01-07 17:24 UTC
### Godot version

4.0-beta10_mono_win64

### System information

Windows 11

### Issue description

When letting the autocompletion fill in the name of the input action it adds a one single or double quote too much at the end.

https://user-images.githubusercontent.com/80385479/211162726-6f8658f2-1451-4069-92de-f71057eaf962.mp4

It does't happen if the autocompletion fills out existing single or double quotes.

### Steps to reproduce

- Create a project and add a input action.
- Create a script and let the name of the input action be filled in without adding any form of quotations inside the brackets of the function call before.

### Minimal reproduction project

N/A

**Comment by akien-mga** [comment] 2023-01-07 18:21
Duplicate of https://github.com/godotengine/godot/issues/70535

**Closed by akien-mga** 2023-01-07 18:21 UTC
