### ISSUE TITLE
Godot crash when click on Sprite -> Convert to 2D Mesh

### ISSUE THREAD

**Issue by allkhor** [godotengine/godot#17991] opened 2018-04-05 08:00 UTC
**Godot version:**

Godot master: a1f835df771

**OS/device including version:**

Xubuntu 16.04.4 x86_64

**Issue description:**

In 2d tab, when clicking on **Sprite** -> **Convert to 2D Mesh**, Godot crash.
Also crash happens when clicks: 
**Skeleton2d** -> **Make Rest Pose (From Bones)**
**Skeleton2d** -> **Set Bones to Rest Pose**
```
user@user-PC:~$ handle_crash: Program crashed with signal 11
Dumping the backtrace. Please include this when reporting the bug on https://github.com/godotengine/godot/issues
[1] /lib/x86_64-linux-gnu/libc.so.6(+0x354b0) [0x7f36a5a084b0] (??:0)
[2] Ref<Texture>::ref(Ref<Texture> const&) (/home/user/source/godot_3/core/reference.h:70)
[3] Ref<Texture>::Ref(Ref<Texture> const&) (/home/user/source/godot_3/core/reference.h:197)
[4] Sprite::get_texture() const (/home/user/source/godot_3/scene/2d/sprite.cpp:153)
[5] SpriteEditor::_update_mesh_data() (/home/user/source/godot_3/editor/plugins/sprite_editor_plugin.cpp:97)
[6] SpriteEditor::_menu_option(int) (/home/user/source/godot_3/editor/plugins/sprite_editor_plugin.cpp:87)
[7] MethodBind1<int>::call(Object*, Variant const**, int, Variant::CallError&) (/home/user/source/godot_3/./core/method_bind.gen.inc:729 (discriminator 12))
[8] Object::call(StringName const&, Variant const**, int, Variant::CallError&) (/home/user/source/godot_3/core/object.cpp:914 (discriminator 1))
[9] Object::emit_signal(StringName const&, Variant const**, int) (/home/user/source/godot_3/core/object.cpp:1195 (discriminator 1))
[10] Object::emit_signal(StringName const&, Variant const&, Variant const&, Variant const&, Variant const&, Variant const&) (/home/user/source/godot_3/core/object.cpp:1241)
[11] PopupMenu::activate_item(int) (/home/user/source/godot_3/scene/gui/popup_menu.cpp:934 (discriminator 4))
[12] PopupMenu::_gui_input(Ref<InputEvent> const&) (/home/user/source/godot_3/scene/gui/popup_menu.cpp:324)
[13] MethodBind1<Ref<InputEvent> const&>::call(Object*, Variant const**, int, Variant::CallError&) (/home/user/source/godot_3/core/method_bind.gen.inc:729 (discriminator 12))
[14] Object::call_multilevel(StringName const&, Variant const**, int) (/home/user/source/godot_3/core/object.cpp:748 (discriminator 1))
[15] Object::call_multilevel(StringName const&, Variant const&, Variant const&, Variant const&, Variant const&, Variant const&) (/home/user/source/godot_3/core/object.cpp:855)
[16] Viewport::_gui_call_input(Control*, Ref<InputEvent> const&) (/home/user/source/godot_3/scene/main/viewport.cpp:1369 (discriminator 2))
[17] Viewport::_gui_input_event(Ref<InputEvent>) (/home/user/source/godot_3/scene/main/viewport.cpp:1719 (discriminator 3))
[18] Viewport::input(Ref<InputEvent> const&) (/home/user/source/godot_3/scene/main/viewport.cpp:2339 (discriminator 2))
[19] Viewport::_vp_input(Ref<InputEvent> const&) (/home/user/source/godot_3/scene/main/viewport.cpp:1213)
[20] MethodBind1<Ref<InputEvent> const&>::call(Object*, Variant const**, int, Variant::CallError&) (/home/user/source/godot_3/core/method_bind.gen.inc:729 (discriminator 12))
[21] Object::call(StringName const&, Variant const**, int, Variant::CallError&) (/home/user/source/godot_3/core/object.cpp:914 (discriminator 1))
[22] Object::call(StringName const&, Variant const&, Variant const&, Variant const&, Variant const&, Variant const&) (/home/user/source/godot_3/core/object.cpp:839)
[23] SceneTree::call_group_flags(unsigned int, StringName const&, StringName const&, Variant const&, Variant const&, Variant const&, Variant const&, Variant const&) (/home/user/source/godot_3/scene/main/scene_tree.cpp:250)
[24] SceneTree::input_event(Ref<InputEvent> const&) (/home/user/source/godot_3/scene/main/scene_tree.cpp:406 (discriminator 6))
[25] InputDefault::parse_input_event(Ref<InputEvent> const&) (/home/user/source/godot_3/main/input_default.cpp:324)
[26] OS_X11::process_xevents() (/home/user/source/godot_3/platform/x11/os_x11.cpp:1857 (discriminator 3))
[27] OS_X11::run() (/home/user/source/godot_3/platform/x11/os_x11.cpp:2503)
[28] /home/user/source/godot_3/bin/godot.x11.tools.64(main+0xd3) [0xee5869] (/home/user/source/godot_3/platform/x11/godot_x11.cpp:56)
[29] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf0) [0x7f36a59f3830] (??:0)
[30] /home/user/source/godot_3/bin/godot.x11.tools.64(_start+0x29) [0xee56c9] (??:?)
-- END OF BACKTRACE --
```
**Steps to reproduce:**
1) Create new project.
2) Click on **Sprite** -> **Convert to 2D Mesh**
3) Crash

**Comment by akien-mga** [comment] 2018-04-05 11:34
Duplicate of #16891. I'll paste the stacktrace there though.

**Closed by akien-mga** 2018-04-05 11:34 UTC
Labels: bug, topic:editor
