### ISSUE TITLE
Bad behaviour of OSX export from command line

### ISSUE THREAD

**Issue by frankiezafe** [godotengine/godot#34990] opened 2020-01-10 13:41 UTC
**Godot version:**
Godot version 3.1.1

**OS/device including version:**
Linux Mint 19 Cinnamon

**Issue description:**

When setting the export path extension to **.zip**, the platform is not taken into account and the behaviour is the same as if `--export "pck"` is specified.

Same behaviour for all platforms ( `--export "Linux/X11"`, `--export "Mac OSX"` or `--export "Windows Desktop"` ), but error appears more often with Mac OSX, as the export generates an archive containing the .app.

**Steps to reproduce:**

```bash
Godot_v3.1.1-stable_x11.64 -v --export "Mac OSX" ../test.zip
```

**Comment by akien-mga** [comment] 2020-01-10 13:46
Duplicate of #23073 (fixed in 3.2).

**Closed by akien-mga** 2020-01-10 13:46 UTC
