### ISSUE TITLE
In the c# version, after adding conditional compilation custom constants in the project name.csproj file, the fields exported by [Export] cannot be assigned values in the editor, and the existing assignments will disappear after restarting the editor.

### ISSUE THREAD

**Issue by quietofheart** [godotengine/godot#83870] opened 2023-10-24 00:52 UTC
### Godot version

4.1.2,4.2.beta.2

### System information

wiindos11,macos14

### Issue description

![image](https://github.com/godotengine/godot/assets/107016779/64ea4180-00d9-4a08-b12c-1b72489d0cb7)
![image](https://github.com/godotengine/godot/assets/107016779/7732c024-e97b-44aa-be42-391b12a8b61d)

### Steps to reproduce

1,Add conditional compilation custom constants in the project name.csproj file
2,[Export]Exported fields cannot be assigned values in the editor

### Minimal reproduction project

N/A

**Comment by timothyqiu** [comment] 2023-10-24 02:03
Please post issues and comments in English, we don't all speak Chinese. In case you don't think you can clearly express yourself in English, you can always use something like a online translation service.

发布 Issue 和评论的时候请使用英文，并不是所有人都懂中文。如果你觉得自己无法用英文表达清楚，也可以发机翻后的内容。

**Comment by atirut-w** [comment] 2023-10-24 03:01
Rough TL until the original is edited:
```
In the C# version, after adding a condition to compile a custom constant in the project name.csproj file, fields exported through [Export] cannot be assigned a value in the editor, and the value disappears after restarting the editor.
```
```
1,Add custom constants for conditional compilation in the project name.csproj file.
2, [Export] fields can not be assigned values in the editor.
```

**Comment by raulsntos** [comment] 2023-10-24 03:55
From the screenshot, it looks like this is a duplicate of https://github.com/godotengine/godot/issues/79839.

You are replacing the constants defined by Godot.NET.Sdk. You need to use `<DefineConstants>$(DefineConstants);$(OS);Test</DefineConstants>` instead.

**Closed** 2023-10-24 06:04 UTC
