### ISSUE TITLE
set from window modw to borderless mode OS.window_size will add forever

### ISSUE THREAD

**Issue by chenjie199234** [godotengine/godot#18877] opened 2018-05-15 01:32 UTC
at first  OS.window_size is 1600x900.OS.get_real_window_size is 1616x939 window mode.
then set borderless,and OS.window_size is 1616x939 and will not change anymore.even set from borderless back to window mode.the OS.window_size is still 1616x939.

**Comment by chenjie199234** [comment] 2018-05-18 03:11
this will cause ui problem!just like the picture below:
first is borderless ui is ok
second is no borderless.ui is lack on right and buttom of the window
![09cwd i1_piwdlj 2x y2 k](https://user-images.githubusercontent.com/29348971/40214163-d5cb869e-5a8b-11e8-8d15-e5387b5a7fd1.png)
![q xgoq45sw3s4e qj4p 3uy](https://user-images.githubusercontent.com/29348971/40214164-d6154810-5a8b-11e8-94d9-6adff9e15486.png)

**Comment by mhilbrunner** [comment] 2018-05-21 16:34
Reopening, as this is still a valid issue.

**Comment by codeoftherings** [comment] 2018-05-21 20:51
I'm new here and this looks good as a first issue. Any guidance on how to approach this?

**Comment by guilhermefelipecgs** [comment] 2018-05-22 00:12
Duplicate of #19033.

**Comment by mhilbrunner** [comment] 2018-05-22 13:26
Closing as duplicate of #19033. Should be fixed by https://github.com/guilhermefelipecgs/godot/commit/28d24c4f6689a622f4451b354797038fc00543e9

**Closed by mhilbrunner** 2018-05-22 13:26 UTC
Labels: bug, junior job, topic:core
