### ISSUE TITLE
Serial IO type module for GDscript

### ISSUE THREAD

**Issue by orosmatthew** [godotengine/godot#21428] opened 2018-08-26 02:49 UTC
Hello,

I propose that Godot have a way to communicate with the outside world with hardware such as the Arduino. Mono has System.IO.Ports to be able to send data and receive data from things such as Arduinos. I was just proposing it because I had a pretty cool idea for a project but could not find a better way or communicating with outside hardware.

**Comment by groud** [comment] 2018-08-26 05:38
Duplicate of #21244

**Closed** 2018-08-26 05:39 UTC
Labels: archived
