### ISSUE TITLE
Can't export a boolean array (`bool[]`) in C# (and passing it to an RPC doesn't work either)

### ISSUE THREAD

**Issue by Steveplays28** [godotengine/godot#70931] opened 2023-01-04 22:55 UTC
### Godot version

v4.0.beta10.mono.official [d0398f62f]

### System information

Windows 10

### Issue description

I can't export a boolean array in C#.
The compiler output says the type is unsupported for export.

```log
D:\Repos\first-person-shooter\common\scripts\Weapon.cs(8,25): The type of the exported field is not supported: 'FirstPersonShooter.Weapon.BooleanArray'
```

On top of that, I'm also unable pass a boolean array through the RPC system (using `Rpc()` or `RpcId()` functions):

```log
Argument 2: cannot convert from 'bool[]' to 'Godot.Variant'
```

### Steps to reproduce

1. Export any `bool[]`:

```cs
[Export] public bool[] BooleanArray;
```

2. Try to build the project, which fails with the error in the description ("The type of the exported field is not supported").

### Minimal reproduction project

N/A

**Comment by Steveplays28** [comment] 2023-01-04 23:05
I suppose this is related to #70298 ([relevant comment](https://github.com/godotengine/godot/issues/70298#issuecomment-1358683697))

**Comment by hawkerm** [comment] 2023-10-02 06:39
Yeah, I was trying to have an array of `AnimatedSprite2D` as a field or property and it's just never initialized, the array is empty in C#.

**Comment by ultrasuperpingu** [comment] 2024-03-20 18:35
Enums array export is not working neither :)

**Comment by raulsntos** [comment] 2024-04-05 01:38
- Closing as a duplicate of https://github.com/godotengine/godot/issues/70298

The only collections currently supported are the ones that are Variant-compatible as documented in the [_C# collections_](https://docs.godotengine.org/en/stable/tutorials/scripting/c_sharp/c_sharp_collections.html) documentation. I want to re-add support for `T[]`, `List<T>`, and `Dictionary<TKey, TValue>` where `T` is a Variant-compatible type. Follow the linked issue to track this.

**Closed by raulsntos** 2024-04-05 01:38 UTC
Labels: topic:dotnet

**Comment by ultrasuperpingu** [comment] 2024-04-05 18:15
> The only collections currently supported are the ones that are Variant-compatible as documented in the [_C# collections_](https://docs.godotengine.org/en/stable/tutorials/scripting/c_sharp/c_sharp_collections.html) documentation.

In fact, basic types array are supported except bool (indeed, as said in the documentation). But isn't bool Variant type ?
