### ISSUE TITLE
Are there iterators on Vector?

### ISSUE THREAD

**Issue by RayKoopa** [godotengine/godot#8354] opened 2017-04-11 10:35 UTC
I'm rewriting `tabs` and `tab_container` to finally get rid of old bugs and crappy behavior, and use unified logic as far as possible in the new `base_tabs`, and ran into a performance problem when implementing stuff like `get_tab_count()`, let's say for `tab_container`:

There's a private helper method `Vector<Control *> _get_tabs()` which returns all child controls which come into question for tabs (toplevel controls will not create a tab):
```cpp
Vector<Control *> TabContainer::_get_tabs() const {

	Vector<Control *> tabs;
	for (int i = 0; i < get_child_count(); i++) {
		// Top level controls do not count as tabs.
		Control *control = get_child(i)->cast_to<Control>();
		if (!control || control->is_toplevel_control())
			continue;
		tabs.push_back(control);
	}
	return tabs;
}
```

Now there's another (public) method `get_tab_count()`, which basically has the following choices of implementation:
- `return _get_tabs().size()`: Waste of work since the vector itself isn't needed, only the size.
- Reimplementing the control iteration and just counting an index: Not much better since the requirements of controls to have a tab might change, and then multiple code places have to be changed to implement that correctly, if they are not forgotten anyway (this was actually the case in some old implementation where toplevel controls were sometimes not ignored).

      int TabContainer::get_tab_count() const {
      
      	int count = 0;
      	for (int i = 0; i < get_child_count(); i++) {
      		// Top level controls do not count as tabs.
      		Control *control = get_child(i)->cast_to<Control>();
      		if (!control || control->is_toplevel_control())
      			continue;
      		count++;
      	}
      	return count;
      }

Then, there's another (public) method `get_tab_control()`, which also has to iterate through the controls the same way, just to pick out _one_ control in the end:
```cpp
Control *TabContainer::get_tab_control(int p_idx) const {

	Vector<Control *> tabs = _get_tabs();
	ERR_FAIL_INDEX(p_idx, tabs.size());

	return tabs[p_idx];
}
```

I'm probably a C# whore, but can't this be optimized with some custom iterator over the controls? I heard this could be implemented in C++ with something like a `Vector::iterator`, **but I can't find any on Godot's custom Vector class**.

Am I blind and not seeing it? Or is this not implemented yet? How should I proceed?

**Comment by Zylann** [comment] 2017-04-11 11:44
I never saw any iterator in the C++ classes of Godot, so as a result iterating on stuff is different everytime. I didn't run into a design problem yet due to this lack, but I believe it would be a great way to improve code maintainance (especially if we can implement it with minimal/zero overhead).

**Comment by RayKoopa** [comment] 2017-04-11 13:19
I see, so no iterators at the moment for me? :(
The only optimization potential I can see then is writing a private `_filter` method which checks if the control should have a tab (basically the toplevel checking part). But it still itches me, it feels hacky...

**Comment by Zylann** [comment] 2017-04-11 17:53
It looks like the problem is getting the actual tabs. Can't they be referenced for god in a list instead of re-fetching them all the time?
Otherwise, if it's about doing something on the set of tabs, you could use a lambda so you won't need to reimplement the filtering iteratiion... but because we aren't in C++11 yet you would need some C trickery with a function pointer and a void*.

**Comment by RayKoopa** [comment] 2017-04-11 17:56
I tried implementing it like that, however, `TabContainer` does not manage tabs itself, it uses its child nodes and stores stuff like icon & disabled state in meta data, while `Tabs` indeed has a custom list. Keeping a copy of the list for `TabContainer` didn't work out well, especially when you resort the children, you'd have to mirror the changes, get notifications when controls go toplevel (which I didn't even find) to remove them, etc....
They're not refetched "all the time", only when measuring or drawing.
(I'm really hating these two controls btw).

**Comment by Calinou** [comment] 2019-12-24 09:28
I'll close this, as the original question has been answered.

**Closed by Calinou** 2019-12-24 09:28 UTC
Labels: discussion, documentation
