### ISSUE TITLE
Exceptions thrown by Nuget package when executed with Godot.NET.Sdk/4.1.0 but not when executed with Microsoft.NET.Sdk

### ISSUE THREAD

**Issue by pappapisshu** [godotengine/godot#79418] opened 2023-07-13 11:19 UTC
### Godot version

4.1.stable.mono.stable.official

### System information

Windows 10 Pro N (x64) - Godot 4.1.stable.mono - .NET SDK 6.0.411

### Issue description

Using the [Kubernetes C# Client](https://github.com/kubernetes-client/csharp) within `Godot.NET.Sdk` throws exceptions that are not thrown when the client is executed within the `Microsoft.NET.Sdk` framework. 

In its basic use, the library loads a configuration file from the file system (by default located in the path `%USERPROFILE%\.kube\config` on Windows or `~/.kube/config` on Linux and Mac), extracts some information such as the address of an HTTP server and its certificates, and send HTTP requests to that server.

In particular, using the library as reported in the [library documentation itself](https://github.com/kubernetes-client/csharp#sample-code), in a `Microsoft.NET.Sdk` context, you get a result like this:
```
C:\Users\Guybrush Threepwood\Simple>dotnet run
Starting Request!
coredns-787d4945fb-jv2p6
etcd-minikube
kube-apiserver-minikube
kube-controller-manager-minikube
kube-proxy-6br9v
kube-scheduler-minikube
storage-provisioner
```

Here is the snippet of source code that allows you to obtain the above output:
```
private static void Main(string[] args)
{
    var config = KubernetesClientConfiguration.BuildDefaultConfig();
    IKubernetes client = new Kubernetes(config);
    Console.WriteLine("Starting Request!");

    var list = client.CoreV1.ListNamespacedPod("kube-system");
    foreach (var item in list.Items)
    {
        Console.WriteLine(item.Metadata.Name);
    }

    if (list.Items.Count == 0)
    {
        Console.WriteLine("Empty!");
    }
}
```

However, if the analogous code snippet is used in a `Godot.NET.Sdk` context, for example within the `_Ready()` method of a class that extends `Node`:
```
public override void _Ready()
{
	var config = KubernetesClientConfiguration.BuildDefaultConfig();
	IKubernetes client = new Kubernetes(config);
	GD.Print("Starting Request!");
	
	var list = client.CoreV1.ListNamespacedPod("kube-system");
	foreach (var item in list.Items)
	{
		GD.Print(item.Metadata.Name);
	}
	
	if (list.Items.Count == 0)
	{
		GD.Print("Empty!");
	}
}
```

You get different output and it seems that the execution of the `_Ready()` method does not complete:
```
Godot Engine v4.1.stable.mono.official.970459615 - https://godotengine.org
Vulkan API 1.1.95 - Forward+ - Using Vulkan Device #0: NVIDIA - GeForce GT 750M
 
Starting Request!
```

Looking at the debug output via Visual Studio Code gives you some more information:
```
-------------------------------------------------------------------
You may only use the Microsoft .NET Core Debugger (vsdbg) with
Visual Studio Code, Visual Studio or Visual Studio for Mac software
to help you develop and test your applications.
-------------------------------------------------------------------
Godot Engine v4.1.stable.mono.official.970459615 - https://godotengine.org
Vulkan API 1.1.95 - Forward+ - Using Vulkan Device #0: NVIDIA - GeForce GT 750M

Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\6.0.19\System.Private.CoreLib.dll'. I simboli sono stati caricati.
Loaded 'C:\Godot\Godot_v4.1-stable_mono_win64\GodotSharp\Api\Debug\GodotPlugins.dll'. I simboli sono stati caricati.
AVVISO: Non è stato possibile caricare i simboli per 'System.Runtime.dll'. 'C:\Users\GUYBRU~1\AppData\Local\Temp\SymbolCache\system.runtime.pdb/59f37fcc47724ecaab82b88431d75e1dFFFFFFFF/system.runtime.pdb' non corrisponde al modulo di cui è in corso il debug.
Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\6.0.19\System.Runtime.dll'. Impossibile trovare o aprire il file PDB.
AVVISO: Non è stato possibile caricare i simboli per 'System.Runtime.InteropServices.dll'. 'C:\Users\GUYBRU~1\AppData\Local\Temp\SymbolCache\system.runtime.interopservices.pdb/650217b6f9064038a6aff7b06785c5f7FFFFFFFF/system.runtime.interopservices.pdb' non corrisponde al modulo di cui è in corso il debug.
Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\6.0.19\System.Runtime.InteropServices.dll'. Impossibile trovare o aprire il file PDB.
Loaded 'C:\Godot\Godot_v4.1-stable_mono_win64\GodotSharp\Api\Debug\GodotSharp.dll'. I simboli sono stati caricati.
AVVISO: Non è stato possibile caricare i simboli per 'System.Collections.dll'. 'C:\Users\GUYBRU~1\AppData\Local\Temp\SymbolCache\system.collections.pdb/f387b0b37b8d487b89f5848832855b1fFFFFFFFF/system.collections.pdb' non corrisponde al modulo di cui è in corso il debug.
Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\6.0.19\System.Collections.dll'. Impossibile trovare o aprire il file PDB.
Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\6.0.19\System.Console.dll'. I simboli sono stati caricati.
AVVISO: Non è stato possibile caricare i simboli per 'System.Runtime.Loader.dll'. 'C:\Users\GUYBRU~1\AppData\Local\Temp\SymbolCache\system.runtime.loader.pdb/4cec053fc9fc4aa4af8e1dbd0e2ea1beFFFFFFFF/system.runtime.loader.pdb' non corrisponde al modulo di cui è in corso il debug.
Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\6.0.19\System.Runtime.Loader.dll'. Impossibile trovare o aprire il file PDB.
AVVISO: Non è stato possibile caricare i simboli per 'System.Runtime.CompilerServices.Unsafe.dll'. 'C:\Users\GUYBRU~1\AppData\Local\Temp\SymbolCache\system.runtime.compilerservices.unsafe.pdb/a1dc35cf8ef8493284e48b990cdb5eb2FFFFFFFF/system.runtime.compilerservices.unsafe.pdb' non corrisponde al modulo di cui è in corso il debug.
Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\6.0.19\System.Runtime.CompilerServices.Unsafe.dll'. Impossibile trovare o aprire il file PDB.
AVVISO: Non è stato possibile caricare i simboli per 'System.Threading.dll'. 'C:\Users\GUYBRU~1\AppData\Local\Temp\SymbolCache\system.threading.pdb/8ee51d0fad6c4fd89d5b5a50cfc0510bFFFFFFFF/system.threading.pdb' non corrisponde al modulo di cui è in corso il debug.
Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\6.0.19\System.Threading.dll'. Impossibile trovare o aprire il file PDB.
AVVISO: Non è stato possibile caricare i simboli per 'System.Collections.Concurrent.dll'. 'C:\Users\GUYBRU~1\AppData\Local\Temp\SymbolCache\system.collections.concurrent.pdb/221fa177b46742fdb83a8fce357cb98eFFFFFFFF/system.collections.concurrent.pdb' non corrisponde al modulo di cui è in corso il debug.
Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\6.0.19\System.Collections.Concurrent.dll'. Impossibile trovare o aprire il file PDB.
AVVISO: Non è stato possibile caricare i simboli per 'System.Diagnostics.TraceSource.dll'. 'C:\Users\GUYBRU~1\AppData\Local\Temp\SymbolCache\system.diagnostics.tracesource.pdb/a6c91600e10248cc953cfd77dad497ffFFFFFFFF/system.diagnostics.tracesource.pdb' non corrisponde al modulo di cui è in corso il debug.
Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\6.0.19\System.Diagnostics.TraceSource.dll'. Impossibile trovare o aprire il file PDB.
Loaded 'Kubernetes-client'. I simboli sono stati caricati.
Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\6.0.19\System.Linq.dll'. I simboli sono stati caricati.
AVVISO: Non è stato possibile caricare i simboli per 'System.Runtime.Serialization.Formatters.dll'. 'C:\Users\GUYBRU~1\AppData\Local\Temp\SymbolCache\system.runtime.serialization.formatters.pdb/3291fc4f69c3461d95a4e5c94cd7e295FFFFFFFF/system.runtime.serialization.formatters.pdb' non corrisponde al modulo di cui è in corso il debug.
Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\6.0.19\System.Runtime.Serialization.Formatters.dll'. Impossibile trovare o aprire il file PDB.
* Ricerca di 'KubernetesClient.pdb' nei server dei simboli configurati...........
Loaded 'KubernetesClient'. Impossibile trovare o aprire il file PDB.
Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\6.0.19\System.Security.Cryptography.X509Certificates.dll'. I simboli sono stati caricati.
* Ricerca di 'KubernetesClient.Basic.pdb' nei server dei simboli configurati........
Loaded 'KubernetesClient.Basic'. Impossibile trovare o aprire il file PDB.
* Ricerca di 'KubernetesClient.Models.pdb' nei server dei simboli configurati.........
Loaded 'KubernetesClient.Models'. Impossibile trovare o aprire il file PDB.
Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\6.0.19\System.Net.Http.dll'. I simboli sono stati caricati.
Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\6.0.19\System.Runtime.InteropServices.RuntimeInformation.dll'. I simboli sono stati caricati.
* Ricerca di 'YamlDotNet.pdb' nei server dei simboli configurati.........
Loaded 'YamlDotNet'. Impossibile trovare o aprire il file PDB.
AVVISO: Non è stato possibile caricare i simboli per 'System.Private.Uri.dll'. 'C:\Users\GUYBRU~1\AppData\Local\Temp\SymbolCache\system.private.uri.pdb/8cfc7b3711d0410bbe8d008b80f0a0e3FFFFFFFF/system.private.uri.pdb' non corrisponde al modulo di cui è in corso il debug.
Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\6.0.19\System.Private.Uri.dll'. Impossibile trovare o aprire il file PDB.
Loaded 'System.Text.Json'. I simboli sono stati caricati.
Loaded 'Fractions'. I simboli sono stati caricati.
Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\6.0.19\netstandard.dll'. I simboli sono stati caricati.
Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\6.0.19\System.Runtime.Numerics.dll'. I simboli sono stati caricati.
Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\6.0.19\System.Text.RegularExpressions.dll'. I simboli sono stati caricati.
AVVISO: Non è stato possibile caricare i simboli per 'System.Reflection.Emit.ILGeneration.dll'. 'C:\Users\GUYBRU~1\AppData\Local\Temp\SymbolCache\system.reflection.emit.ilgeneration.pdb/bfcb376b4cc749d780fcc93e1bdb544eFFFFFFFF/system.reflection.emit.ilgeneration.pdb' non corrisponde al modulo di cui è in corso il debug.
Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\6.0.19\System.Reflection.Emit.ILGeneration.dll'. Impossibile trovare o aprire il file PDB.
AVVISO: Non è stato possibile caricare i simboli per 'System.Reflection.Emit.Lightweight.dll'. 'C:\Users\GUYBRU~1\AppData\Local\Temp\SymbolCache\system.reflection.emit.lightweight.pdb/37dcd5840b914cecb4a50f5aa4b526d1FFFFFFFF/system.reflection.emit.lightweight.pdb' non corrisponde al modulo di cui è in corso il debug.
Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\6.0.19\System.Reflection.Emit.Lightweight.dll'. Impossibile trovare o aprire il file PDB.
AVVISO: Non è stato possibile caricare i simboli per 'System.Memory.dll'. 'C:\Users\GUYBRU~1\AppData\Local\Temp\SymbolCache\system.memory.pdb/3112f513148846479cb55b02327129c4FFFFFFFF/system.memory.pdb' non corrisponde al modulo di cui è in corso il debug.
Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\6.0.19\System.Memory.dll'. Impossibile trovare o aprire il file PDB.
AVVISO: Non è stato possibile caricare i simboli per 'System.Reflection.Primitives.dll'. 'C:\Users\GUYBRU~1\AppData\Local\Temp\SymbolCache\system.reflection.primitives.pdb/8e4aee69196b402ea9a4ae92b072aa4cFFFFFFFF/system.reflection.primitives.pdb' non corrisponde al modulo di cui è in corso il debug.
Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\6.0.19\System.Reflection.Primitives.dll'. Impossibile trovare o aprire il file PDB.
Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\6.0.19\System.ObjectModel.dll'. I simboli sono stati caricati.
Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\6.0.19\System.ComponentModel.TypeConverter.dll'. I simboli sono stati caricati.
Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\6.0.19\System.Linq.Expressions.dll'. I simboli sono stati caricati.
Exception thrown: 'System.FormatException' in System.Private.CoreLib.dll
Exception thrown: 'System.FormatException' in System.Private.CoreLib.dll
Exception thrown: 'System.FormatException' in System.Private.CoreLib.dll
Exception thrown: 'System.FormatException' in System.Private.CoreLib.dll
Exception thrown: 'System.FormatException' in System.Private.CoreLib.dll
Exception thrown: 'System.FormatException' in System.Private.CoreLib.dll
Exception thrown: 'System.FormatException' in System.Private.CoreLib.dll
Exception thrown: 'System.FormatException' in System.Private.CoreLib.dll
Exception thrown: 'System.FormatException' in System.Private.CoreLib.dll
Exception thrown: 'System.FormatException' in System.Private.CoreLib.dll
Exception thrown: 'System.FormatException' in System.Private.CoreLib.dll
Exception thrown: 'System.FormatException' in System.Private.CoreLib.dll
Exception thrown: 'System.FormatException' in System.Private.CoreLib.dll
Exception thrown: 'System.FormatException' in System.Private.CoreLib.dll
Exception thrown: 'System.FormatException' in System.Private.CoreLib.dll
Exception thrown: 'System.FormatException' in System.Private.CoreLib.dll
Exception thrown: 'System.FormatException' in System.Private.CoreLib.dll
Exception thrown: 'System.FormatException' in System.Private.CoreLib.dll
Exception thrown: 'System.FormatException' in System.Private.CoreLib.dll
Exception thrown: 'System.FormatException' in System.Private.CoreLib.dll
Exception thrown: 'System.FormatException' in System.Private.CoreLib.dll
Exception thrown: 'System.FormatException' in System.Private.CoreLib.dll
Exception thrown: 'System.FormatException' in System.Private.CoreLib.dll
Exception thrown: 'System.FormatException' in System.Private.CoreLib.dll
Exception thrown: 'System.FormatException' in System.Private.CoreLib.dll
Exception thrown: 'System.FormatException' in System.Private.CoreLib.dll
Exception thrown: 'System.FormatException' in System.Private.CoreLib.dll
Exception thrown: 'System.FormatException' in System.Private.CoreLib.dll
Exception thrown: 'System.FormatException' in System.Private.CoreLib.dll
Exception thrown: 'System.FormatException' in System.Private.CoreLib.dll
Exception thrown: 'System.FormatException' in System.Private.CoreLib.dll
Exception thrown: 'System.FormatException' in System.Private.CoreLib.dll
Exception thrown: 'System.FormatException' in System.Private.CoreLib.dll
Exception thrown: 'System.FormatException' in System.Private.CoreLib.dll
Exception thrown: 'System.FormatException' in System.Private.CoreLib.dll
Exception thrown: 'System.FormatException' in System.Private.CoreLib.dll
Exception thrown: 'System.FormatException' in System.Private.CoreLib.dll
Exception thrown: 'System.FormatException' in System.Private.CoreLib.dll
Exception thrown: 'System.FormatException' in System.Private.CoreLib.dll
Exception thrown: 'System.FormatException' in System.Private.CoreLib.dll
Exception thrown: 'System.FormatException' in System.Private.CoreLib.dll
Exception thrown: 'System.FormatException' in System.Private.CoreLib.dll
Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\6.0.19\System.Net.Primitives.dll'. I simboli sono stati caricati.
Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\6.0.19\System.Security.Cryptography.Primitives.dll'. I simboli sono stati caricati.
Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\6.0.19\System.Collections.NonGeneric.dll'. I simboli sono stati caricati.
Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\6.0.19\Microsoft.Win32.Primitives.dll'. I simboli sono stati caricati.
Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\6.0.19\System.Net.Security.dll'. I simboli sono stati caricati.
Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\6.0.19\System.Diagnostics.DiagnosticSource.dll'. I simboli sono stati caricati.
AVVISO: Non è stato possibile caricare i simboli per 'System.Diagnostics.Tracing.dll'. 'C:\Users\GUYBRU~1\AppData\Local\Temp\SymbolCache\system.diagnostics.tracing.pdb/1c6ec02d723f4fe4bbf8f083e51deb9cFFFFFFFF/system.diagnostics.tracing.pdb' non corrisponde al modulo di cui è in corso il debug.
Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\6.0.19\System.Diagnostics.Tracing.dll'. Impossibile trovare o aprire il file PDB.
Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\6.0.19\System.Security.Cryptography.Algorithms.dll'. I simboli sono stati caricati.
Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\6.0.19\System.Security.Cryptography.Encoding.dll'. I simboli sono stati caricati.
Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\6.0.19\System.Formats.Asn1.dll'. I simboli sono stati caricati.
Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\6.0.19\System.Security.Cryptography.Csp.dll'. I simboli sono stati caricati.
Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\6.0.19\System.Security.Cryptography.Cng.dll'. I simboli sono stati caricati.
Exception thrown: 'System.Security.Cryptography.CryptographicException' in System.Security.Cryptography.Algorithms.dll
Loaded 'System.Text.Encodings.Web'. I simboli sono stati caricati.
Starting Request!
Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\6.0.19\System.Net.Sockets.dll'. I simboli sono stati caricati.
AVVISO: Non è stato possibile caricare i simboli per 'System.Threading.Overlapped.dll'. 'C:\Users\GUYBRU~1\AppData\Local\Temp\SymbolCache\system.threading.overlapped.pdb/57aa0a5407f840b2935c5d72c509bd5fFFFFFFFF/system.threading.overlapped.pdb' non corrisponde al modulo di cui è in corso il debug.
Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\6.0.19\System.Threading.Overlapped.dll'. Impossibile trovare o aprire il file PDB.
Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\6.0.19\System.Net.NameResolution.dll'. I simboli sono stati caricati.
AVVISO: Non è stato possibile caricare i simboli per 'System.Threading.ThreadPool.dll'. 'C:\Users\GUYBRU~1\AppData\Local\Temp\SymbolCache\system.threading.threadpool.pdb/9e8ad02649af4ac48bcf9775c06ce355FFFFFFFF/system.threading.threadpool.pdb' non corrisponde al modulo di cui è in corso il debug.
Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\6.0.19\System.Threading.ThreadPool.dll'. Impossibile trovare o aprire il file PDB.
Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\6.0.19\System.Security.Principal.Windows.dll'. I simboli sono stati caricati.
Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\6.0.19\System.Security.Claims.dll'. I simboli sono stati caricati.
Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\6.0.19\System.Threading.Channels.dll'. I simboli sono stati caricati.
Exception thrown: 'System.IO.IOException' in System.Net.Sockets.dll
Exception thrown: 'System.IO.IOException' in System.Private.CoreLib.dll
Exception thrown: 'System.IO.IOException' in System.Net.Security.dll
Exception thrown: 'System.IO.IOException' in System.Private.CoreLib.dll
```

In both `Godot.NET.Sdk` and `Microsoft.NET.Sdk` scenarios, the library has been imported as a NuGet package, as shown by the C# project files:
```
<Project Sdk="Godot.NET.Sdk/4.1.0">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <EnableDynamicLoading>true</EnableDynamicLoading>
    <RootNamespace>Kubernetesclient</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="KubernetesClient" Version="11.0.36" />
  </ItemGroup>
</Project>
```

```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="KubernetesClient" Version="11.0.36" />
  </ItemGroup>
</Project>
```

You can find both the project in the `Godot.NET.Sdk` context and the one in the `Microsoft.NET.Sdk` context among the attachments.

### Steps to reproduce

First of all it is necessary to have an appropriate configuration file that the library can use to retrieve the connection information to the HTTP server. If you have your own `KubeConfig` file you can use that, otherwise you can use the one I have attached, saving it in the path `%USERPROFILE%\.kube\config` on Windows or `~/.kube/config` on Linux and Mac.

NOTE: Please, note that if you use the attached config file, the HTTP connection will fail because locally you will not have any HTTP server to answer the requests. For the purposes of library usage testing, however, this is not important. If you want to do a complete test with a working HTTP server you could install `minikube` as described on the [official site](https://minikube.sigs.k8s.io/docs/start/).

Once the config file is present, to test the library in the `Microsoft.NET.Sdk` context it is sufficient to launch `dotnet run` inside the `Simple` folder that you find attached to this issue.

Instead, to test the library in the `Godot.NET.Sdk` context, it is sufficient to import into Godot the `kubernetes-client` folder that you find attached to the issue and then launch the project. 
Note that the project is configured to view the source code on Visual Studio Code, as described in the [official documentation](https://docs.godotengine.org/en/stable/tutorials/scripting/c_sharp/c_sharp_basics.html).

### Minimal reproduction project

- [Simple.zip](https://github.com/godotengine/godot/files/12038712/Simple.zip) -> It is a simple project that demonstrates the basic functioning of the library in a `Microsoft.NET.Sdk` context.
- [kubernetes-client.zip](https://github.com/godotengine/godot/files/12038711/kubernetes-client.zip) -> It is a simple Godot project that throws exceptions using the library in a `Godot.NET.Sdk` context.
- [config.zip](https://github.com/godotengine/godot/files/12038709/config.zip) -> It contains a `KubeConfig`, i.e. a configuration file that allows you to test the library once it is saved in the path `%USERPROFILE%\.kube\config` on Windows or `~/.kube/config` on Linux and Mac.

**Comment by raulsntos** [comment] 2023-07-13 18:14
The MRP doesn't throw exceptions for me, it just freezes on the `ListNamespacedPod` method. It's likely an async method that blocks the main thread. Try using `Task.Run` or `ListNamespacedPodWithHttpMessagesAsync`.

**Comment by RedworkDE** [comment] 2023-07-14 08:25
As pointed out, you need use the `async` versions of these methods or because of a quirk of how async works it godot, the sync wrapper will deadlock when called from the main thread.

MRP: `(new Func<Task>(async () => await Task.Run(() => {}))()).GetAwaiter().GetResult();` deadlocks when called in in `_Ready`

**Comment by RedworkDE** [comment] 2023-07-14 08:27
Duplicate of https://github.com/godotengine/godot-docs/issues/6790

**Closed by RedworkDE** 2023-07-14 08:27 UTC
Labels: bug, topic:dotnet
