### ISSUE TITLE
Setting WorldEnvironment's Mode "Canvas" in 2D makes every pulldown menu invisible

### ISSUE THREAD

**Issue by azul372** [godotengine/godot#62728] opened 2022-07-05 05:51 UTC
### Godot version

4.0alpha11

### System information

Windows 10, GLES3,  NVIDIA Quadro P2000

### Issue description

Setting WorldEnvironment's Background Mode "Canvas" makes almost all pulldown parameters unreadable, filled with Default Clear Color of the project. In 4.0alpha10, this will not happen(since it crashes to begin with https://github.com/godotengine/godot/issues/62079)

![image](https://user-images.githubusercontent.com/80684394/177256910-b1d4ce2d-a279-4ca4-9086-6e3124a2c00b.png)
![image](https://user-images.githubusercontent.com/80684394/177257181-d470c8fe-6edc-4df0-b822-33cde94d7148.png)

This also affects Scene, Project, Debug, Editor, Help menus at the top of the engine. It seems they just become invisible and still responses when clicked.

### Steps to reproduce

1. Set WorldEnvironment node in the tree
2. Open the Environment in the inspector
3. Switch background_mode to Canvas
4. Try to select some drop-down lists of the engine

**Comment by Calinou** [comment] 2022-07-05 15:36
Duplicate of https://github.com/godotengine/godot/issues/52467.

**Closed by Calinou** 2022-07-05 15:36 UTC
Labels: bug, topic:rendering, topic:editor
