### ISSUE TITLE
LightmapGI: lightmap doesn't work in godot 4.0 beta 2.

### ISSUE THREAD

**Issue by Lasuch69** [godotengine/godot#66629] opened 2022-09-29 22:14 UTC
### Godot version

4.0 beta 2 linux 64bit

### System information

Fedora 36, RX 550, Vulkan 1.2.0

### Issue description

Originally this project was made in godot 4 beta 1. Here is a screenshot of how it should look like:
![Screenshot from 2022-09-30 00-05-25](https://user-images.githubusercontent.com/71460040/193150501-d2353a1d-0523-455f-934c-bd6f17874384.png)

But after opening it in beta 2 it looks like this:
![Screenshot from 2022-09-30 00-05-03](https://user-images.githubusercontent.com/71460040/193150742-ca761cf7-a300-4cc6-b5bd-a9780daa1922.png)

Similar thing happen on my other project all tho i am using reflection probe on top with a lightmap.

Beta 1:
![Screenshot from 2022-09-29 23-27-09](https://user-images.githubusercontent.com/71460040/193147019-a6582cdc-1269-4952-bd13-fd0e8646af06.png)

Beta 2:
![Screenshot from 2022-09-29 23-26-17](https://user-images.githubusercontent.com/71460040/193147013-141dff93-d418-4ec1-9422-10dde3c7ffa0.png)

Note that i haven't changed a single setting when changing versions.

### Steps to reproduce

Change version from beta 1 to beta 2

### Minimal reproduction project

Project from the 2 first shots, the other one is too big.
[bug.zip](https://github.com/godotengine/godot/files/9679347/bug.zip)

**Comment by Calinou** [comment] 2022-09-29 22:34
Duplicate of https://github.com/godotengine/godot/issues/66618.

**Closed by Calinou** 2022-09-29 22:34 UTC
