### ISSUE TITLE
A strange problem with KinematicBody2D's colliding body.

### ISSUE THREAD

**Issue by dbsGen** [godotengine/godot#3092] opened 2015-12-17 06:27 UTC
I write a little demo to show this problem.
https://github.com/dbsGen/CollidingTest
In the demo, I make a mark at the colliding position, and some time the KinematicBody2D's colliding position is different with others.

**Comment by akien-mga** [comment] 2015-12-17 06:34
Maybe related to #2097.

**Comment by reduz** [comment] 2016-01-11 02:06
I don't understand this much.. but it seems related to tree processing order to me.. nothing out of the ordinary

**Comment by dbsGen** [comment] 2016-01-26 04:10
![194aacff-2841-4a1a-83a1-8d3e29be5df3](https://cloud.githubusercontent.com/assets/1573606/12572235/721af6fc-c424-11e5-9521-384facdd97db.png)
The KinematicBody2D and Area2D using same CollisionShape. But some time they can not be detecteded at same time.

**Comment by akien-mga** [comment] 2016-07-21 08:41
Is this still reproducible in the current master branch?

**Comment by MarianoGnu** [comment] 2016-07-21 10:01
Kinematic body has a skin parameter, this means it's collision shape is a little bugger and not detected by other bodies. I had problems because of this to make a falling platform because i could'n detect collision with player. I had to test a movement on every frame to workaround this

**Comment by eon-s** [comment] 2017-11-19 21:23
Still happens in 2.1.4 and master.

Project for 3:
[CollidingTestv3.zip](https://github.com/godotengine/godot/files/1485986/CollidingTestv3.zip)

Sounds pretty much similar to #11879.

**Comment by Anutrix** [comment] 2019-10-04 21:23
Can you tell us how to understand the test project?
Are black crosses collision position?

**Comment by eon-s** [comment] 2019-10-06 17:45
Setting `sync to physics` option on the animated Kinematic bodies seem to fix the problem on latest stable.

**Comment by tavurth** [comment] 2020-05-07 14:56
In the first GIF we can see the latest state in Godot version:
<img width="653" alt="Screenshot 2020-05-07 at 20 38 05" src="https://user-images.githubusercontent.com/100964/81309471-b12f7300-90a2-11ea-8664-8074609c8c10.png">


In the first video we can see an occasional black cross, representing a mismatched collision with the sibling KinematicBodies.
**Gif**
![2020-05-07 20-36-02](https://user-images.githubusercontent.com/100964/81309368-965cfe80-90a2-11ea-9f94-2002b1781c45.gif)
**Imgur**
https://i.imgur.com/oIqLbkx.mp4

After enabling `sync-to-physics` on the bodies the black crosses disappear, representing the fact that each KB is now in sync with it's siblings.
**Gif**
![2020-05-07 20-34-27](https://user-images.githubusercontent.com/100964/81309373-978e2b80-90a2-11ea-8b3e-83d2eafdc44d.gif)
**Imgur**
https://i.imgur.com/xYLGcSR.mp4

**Comment by tavurth** [comment] 2020-05-07 14:56
Hope that's helpful, I'm glad this at least has a fix now

**Comment by tavurth** [comment] 2020-05-13 12:51
@akien-mga I'm not sure of the status of this now, can this be marked as completed?

**Comment by madmiraal** [comment] 2020-06-01 11:03
Closing as fixed.

**Closed by madmiraal** 2020-06-01 11:03 UTC
Labels: bug, topic:physics
