### ISSUE TITLE
More options for use_pixel_snap project setting.

### ISSUE THREAD

**Issue by ElfEars** [godotengine/godot#27522] opened 2019-03-29 23:26 UTC
**NOTE: This jitter is unrelated to the other common jitter problem. (That one is related to the physics engine)**

We've all been there. Having to floor node positions when not in motion to stop sprites from jittering when the camera moves due to float rounding.

I'd suggest splitting 2d_pixel_snap into int options for determining which pixel a visual object's position should be rendered as:

- none (off. No pixel snap. Default value)
- Nearest (Uses current method of rounding visual positions to their nearest whole value.) (Via a strange floor +0.5 approach. I assume shader code does not support rounding)
- Floor (Floors visual positions thus causing less jittering)
- Ceiling (Ceilings visual positions. Again causing less jittering)

**Comment by CptPotato** [comment] 2019-03-30 07:27
I think the problem is that the sprites aren't snapped to integer positions in the world but integer positions in the screen.

If I think about it correctly, rounding the camera's position should eliminate this problem, but you'll have to compensate for that in the camera movement code (so that the change in position in removed again in the next `_process`.

**Comment by Calinou** [comment] 2020-10-29 13:21
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!

**Closed by Calinou** 2020-10-29 13:21 UTC
Labels: discussion, enhancement, topic:rendering
