### ISSUE TITLE
Script editor: View jumps to the last line on opening

### ISSUE THREAD

**Issue by isaacremnant** [godotengine/godot#30896] opened 2019-07-28 18:31 UTC
**Godot version:** 331a703f5

**Issue description:** Open a script, the caret and view go to the very last line. Scripts should open at the top.

**Comment by KoBeWi** [comment] 2019-07-28 21:48
Looks like duplicate of #29858

**Closed by KoBeWi** 2019-07-28 21:48 UTC

**Comment by isaacremnant** [comment] 2019-07-29 02:53
@KoBeWi How did you fix this? I still get the same behavior when changing "Scroll Past End Of File".
