### ISSUE TITLE
InputMap - Action Strength Inconsistency With Key And Analog Stick Mapped

### ISSUE THREAD

**Issue by Lukas-Fletcher** [godotengine/godot#39287] opened 2020-06-04 13:54 UTC
**Godot version:** 3.2.1.stable.official

**OS/device including version:** Microsoft Windows 10 Pro Version	10.0.18363 Build 18363

**Controller:** PS4 Dualshock4

**Issue description:**
![Screenshot (6)](https://user-images.githubusercontent.com/66425672/83764271-077bdb80-a67a-11ea-9576-da6ba130a1bc.png)

When having controller connected, an input event action mapped to a keyboard key (up in project) and a controller analog stick (left stick up in project) will not give a constant strength when the keyboard key is held down.

**Steps to reproduce:**
Open project.
Connect controller.
Press "Up Arrow" Key

**Minimal reproduction project:**

[ControllerStickBug.zip](https://github.com/godotengine/godot/files/4730456/ControllerStickBug.zip)

**Comment by madmiraal** [comment] 2021-04-04 09:42
@Sakull284 I've created a PR (#47599) that should fix this problem. However, I don't have a PS4 controller to test it with. Please test is for us.

**Comment by Calinou** [comment] 2023-01-25 14:44
Duplicate of https://github.com/godotengine/godot/issues/45628.

**Closed by Calinou** 2023-01-25 14:44 UTC
Labels: bug, confirmed, topic:input
