### ISSUE TITLE
Godot crashes when I add a file from file explorer to the Godot file system

### ISSUE THREAD

**Issue by P1gZ** [godotengine/godot#73125] opened 2023-02-11 20:43 UTC
### Godot version

4.0 RC 1 and Beta 17

### System information

Windows 11

### Issue description

When I try to move a file to the Godot file system, it says "(Re)importing assets", a dark window opens, and after a while I get a message to close the program. After re-opening the project the file has loaded in but I don't understand why it crashes. It also happens to me in 4.0 Beta 17 but not the versions before. It doesn't look like it has happened to anyone else though.

### Steps to reproduce

I opened the project, dragged the file in, and it broke.

### Minimal reproduction project

N/A

**Comment by akien-mga** [comment] 2023-02-11 20:52
Duplicate of #73107

**Closed by akien-mga** 2023-02-11 20:52 UTC
