### ISSUE TITLE
Difficult to return to tileset editor from shader editor

### ISSUE THREAD

**Issue by paulguy** [godotengine/godot#71383] opened 2023-01-14 07:01 UTC
### Godot version

4.0 beta12

### System information

Linux (Arch Linux)

### Issue description

There doesn't seem to be a clear/consistent way to return to the tileset editor after editing a tile's shader.

### Steps to reproduce

* Select a tilemap node.
* Go to the tileset editor.
* Pick a tile.
* Add or edit a shader material to the tile. -> the shader editor comes up
* Returning to the tileset editor requires selecting another node then selecting the tilemap node again, which is pretty unintuitive.
* Go to the tileset editor.
* Picking the same tile will seem to have some chance of opening the shader editor again without having to click anything else but the tile, even if different tiles were selected first.  Doesn't seem to matter if it's an alternate tile or not.

### Minimal reproduction project

N/A

**Comment by Calinou** [comment] 2023-01-14 09:22
Duplicate of https://github.com/godotengine/godot/issues/32002.

**Closed by Calinou** 2023-01-14 09:22 UTC
Labels: enhancement, topic:editor
