### ISSUE TITLE
Running a game with a RigidBody using the "_integrate_forces(state)" function on a built-in script lags my PC

### ISSUE THREAD

**Issue by 19PHOBOSS98** [godotengine/godot#38455] opened 2020-05-04 12:58 UTC
**Godot version:**
Godot 3.2.1
**OS/device including version:**
Macbook pro OS: Catalina 10.15.4
**Issue description:**
https://youtu.be/JnHyyacYnOA
**Steps to reproduce:**
-prepare a RigidBody
-attach a built-in script
-add the function: "func _integrate_forces(state)"
-run, at least try... 
**Minimal reproduction project:**
[testing.zip](https://github.com/godotengine/godot/files/4574755/testing.zip)

**Comment by akien-mga** [comment] 2020-05-04 13:34
Duplicate of #38454.

**Closed by akien-mga** 2020-05-04 13:34 UTC

**Comment by 19PHOBOSS98** [comment] 2020-05-04 21:54
shouldn't this be it's own thing since it happens for another reason?

**Comment by 19PHOBOSS98** [comment] 2020-05-04 22:00
> Duplicate of #38454.
It lags whenever I enter my password, using `_integrate_forces` on a built-in script when running triggers the prompt to do so. The other post talks about it just lagging whenever the prompt gets my password.

**Comment by akien-mga** [comment] 2020-05-05 06:10
From the description of both issues it sounded like the same thing.

**Comment by 19PHOBOSS98** [comment] 2020-05-05 06:17
> From the description of both issues it sounded like the same thing.

the other one's the real problem I agree, but wouldn't it be safe to point out that this specific function triggers a prompt that requires a password? I mean, I imagine that this doesn't really happen in other systems...

**Comment by 19PHOBOSS98** [comment] 2020-05-09 00:19
I think I solved it... It's stupid but, I just forgot to set `contact reported` and turn on `custom integrator` and `contact monitor`.
