### ISSUE TITLE
Saving after setting an exported PackedScene variable in the inspector resets the value

### ISSUE THREAD

**Issue by emoulsdale** [godotengine/godot#41509] opened 2020-08-25 14:47 UTC
**Godot version:**

Godot master branch, commit hash _dd58f4da66_, compiled using clang/llvm and lld for the linuxbsd platform.

**OS/device including version:**

- HP Envy Laptop 13-ah1xxx (this is the output on Ubuntu)
    - 7.5 GiB memory
    - Intel® Core™ i5-8265U CPU @ 1.60GHz × 8
    - Nvidia GeForce MX150 2GB (GDDR5)
- Ubuntu 20.04.1 LTS (64-bit)
- Vulkan backend

**Issue description:**

When exporting a _PackedScene_ variable and loading a _.tscn_ file into it using the inspector: _saving_ causes the value to be reset.

This is unexpected because the value should not be reset AFAIK, though I may be mistaken.

**Steps to reproduce:**
Create two scenes, one of which contains a node to which a script is attached, containing an exported variable of type _PackedScene_. In the inspector, load the other scene into this variable, and save. This should case the value to be reset.

In the uploaded minimal reproduction project, this reference is in the only node of _Main.tscn_. 

**Minimal reproduction project:**

[emoulsdale.zip](https://github.com/godotengine/godot/files/5124300/emoulsdale.zip)

**Comment by pouleyKetchoupp** [comment] 2020-08-26 21:06
Confirmed on master, can't reproduce on 3.2.2. No error message.

**Comment by akien-mga** [comment] 2020-09-02 07:36
Might actually be a GDScript issue, see #41690.

**Comment by Calinou** [comment] 2021-03-31 09:39
Duplicate of https://github.com/godotengine/godot/issues/45697, which has more information about the bug causing this
.

**Closed by Calinou** 2021-03-31 09:39 UTC
Labels: bug, confirmed, topic:core, topic:editor
