### ISSUE TITLE
Undo does not reset size on TextureRects which were automatically resized by being put into a CenterContainer

### ISSUE THREAD

**Issue by Proggle** [godotengine/godot#66092] opened 2022-09-19 08:04 UTC
### Godot version

v3.5.stable.official [991bb6ac7]

### System information

Windows 10

### Issue description

Let's say you have a texturerect and a centercontainer.
![image](https://user-images.githubusercontent.com/89282845/190974105-fadd8b53-a7d1-4125-ab48-faf0be236c64.png)
You drag the texturerect onto the centercontainer, so it's now a child of the centercontainer.  The centercontainer automatically resizes it.
![image](https://user-images.githubusercontent.com/89282845/190974241-1ba0ffec-2987-446c-9942-b6fcdc1d9f1d.png)
You decide you didn't want to do that, and press control+Z to undo.  The tree heirarchy is undone, but the change in size to the texturerect is not undone.
![image](https://user-images.githubusercontent.com/89282845/190974347-c768a31a-101b-4355-accf-7bc547cb36a5.png)

Expectation: Undo should restore the editor entirely to the state before the drag-and-drop operation, not partially.

### Steps to reproduce

1) drag and drop a texturerect onto a center container.
2) press control + Z

### Minimal reproduction project

[CenterContainerBug.zip](https://github.com/godotengine/godot/files/9597106/CenterContainerBug.zip)

**Comment by KoBeWi** [comment] 2022-09-19 11:35
The undo action uses generic `add_child()` method from Node and it has no information about the side-effects of this action. Resolving this would be tricky and require some special handing for specific nodes. I don't think it's worth it.

**Comment by SirQuartz** [comment] 2022-09-19 22:35
> The undo action uses generic `add_child()` method from Node and it has no information about the side-effects of this action. Resolving this would be tricky and require some special handing for specific nodes. I don't think it's worth it.

You could probably do this by storing the size of the node within its previous parent with the undo action, then simply check if the current size is different and set the size of the node accordingly. Of course, that's just a hypothesis.

**Comment by KoBeWi** [comment] 2022-09-19 22:39
Yeah the problem is that Node has no size, so you first need to check if it's a Control and do this conditionally. Doable, but sounds hacky. Also you can reparent a node in multiple ways, so this should be done with a specialized method to avoid duplicating this code.

This is minor bug that rarely has a real impact. In worst case you can just revert your scene if it was saved recently enough.

**Comment by lostminds** [comment] 2022-11-27 16:52
I was just planning on reporting this bug for 4.0.beta6 and the issue is more general (perhaps it should be renamed?) affecting all Control nodes being placed in any of the layout Container nodes that resize them, and working with control nodes I think it's not that rare. Basically it means that undo doesn't undo layout changes caused by containers. This is annoying and I think it can decrease the willingness of users to try using these container nodes, since you can't undo the changes they cause. Which is a pity since they're powerful and useful once you get them set up correctly.

Having implemented undo-systems in other applications I think a workable more general approach would be to record any changes that the layout container applies when the new control node child is being added as part of the same undo action group if one is active. This way these or any other changes changes would also be undone if the user then undoes the change in parent, but you won't need to save anything in some undo state for all nodes where it's not relevant.

**Comment by TheSofox** [comment] 2023-11-24 12:30
Duplicate of https://github.com/godotengine/godot/issues/44629

I've made pull request that fixes this issue and has been approved for 4.3 : https://github.com/godotengine/godot/pull/85181

**Comment by lostminds** [comment] 2023-11-24 12:45
> I've made pull request that fixes this issue and has been approved for 4.3

Great work @TheSofox! Looks like it's been cherrypicked for 4.2 so hopefully it should be included in 4.2.1 even if it didn't make it into the first 4.2 release

**Closed** 2023-11-24 12:54 UTC
Labels: bug, topic:editor, usability
