### ISSUE TITLE
Import a downloaded image from Android

### ISSUE THREAD

**Issue by Cosciad** [godotengine/godot#36305] opened 2020-02-17 15:16 UTC
**Godot version:**
3.2

**OS/device including version:**
Android 7.1.2 / OnePlus 3

**Issue description:**
I'm trying to open an image file with this path: /storage/emulated/0/Download/XXX.jpg
To do it, I'm using this code:
`var img = Image.new()`
`var itex = ImageTexture.new()`
`img.load("Path/to/my/image/file")`
`itex.create_from_image(img)`
`find_node("Image").texture = itex`

The result of this code is that I have the frame of the image but filled up with black and that's it..

Could you tell me if this is a bug or do I do it wrong ?

**Comment by Calinou** [comment] 2020-02-17 15:28
Does it work if you load the image file's contents into a PoolByteArray and pass it to [`Image.create_jpg_from_buffer()`](https://docs.godotengine.org/en/latest/classes/class_image.html#class-image-method-load-jpg-from-buffer)?

**Comment by Cosciad** [comment] 2020-02-17 15:42
I didn't try but the previous code works on PC.
How can I load the jpg content in a PoolByteArray ?

**Comment by volzhs** [comment] 2020-02-17 16:45
Did you enable `Read External Storage` permission?

**Comment by Cosciad** [comment] 2020-02-17 17:03
Yes I enabled it, still not working )=

**Comment by Cosciad** [comment] 2020-02-18 09:14
So, I tried the load_jpg_buffer, the read external.
It works on PC but not on android.
Maybe it has something to do with the import files ?

**Comment by Cosciad** [comment] 2020-02-18 09:45
Nailed it ! Switching to GLES2 does the thing !
So I think there is a problem with GLES3. =)

**Comment by Calinou** [comment] 2020-02-18 12:56
Duplicate of #35459.

**Closed by Calinou** 2020-02-18 12:56 UTC
