### ISSUE TITLE
Multiline declarations with mixed tabs and spaces can't be commented out easily

### ISSUE THREAD

**Issue by L4Vo5** [godotengine/godot#80360] opened 2023-08-07 04:16 UTC
### Godot version

v4.2.dev2.official [da81ca62a]

### System information

N/A

### Issue description

After https://github.com/godotengine/godot/pull/44557, commenting a multiline declaration (like an array, dictionary, string, maybe others) with mixed tabs and spaces with the "Toggle Comment" shortcut causes the error `Mixed use of tabs and spaces for indentation`

### Steps to reproduce

Have a multiline declaration with mixed tabs and spaces, highlight it, and press Ctrl+K (the toggle comment shortcut)
```gdscript
var test := [
	 2
]
```
```gdscript
#var test := [
	 #2
#]
```
![image](https://github.com/godotengine/godot/assets/37083802/f447476f-9538-4ef9-8765-06876dce53ec)
```gdscript
var test = """
	 a
"""
```
```gdscript
#var test = """
	 #a
#"""
```
![image](https://github.com/godotengine/godot/assets/37083802/3e192d6b-31cc-4800-b495-35635ada6bbe)

### Minimal reproduction project

N/A

**Comment by dalexeev** [comment] 2023-08-07 06:33
* Duplicate of #52834.

Thanks for the report nonetheless!

**Closed by dalexeev** 2023-08-07 06:33 UTC
Labels: bug, topic:gdscript, topic:editor

**Comment by L4Vo5** [comment] 2023-08-07 08:07
> * Duplicate of [Error when mixing tabs and spaces in comment line #52834](https://github.com/godotengine/godot/issues/52834).

Hmm, while the error itself is the same, that issue would only be "fixed" by allowing the mixed indentation before comments. My issue could be alternatively fixed by changing the Ctrl+K behaviour again.
For example, the shortcut could put the # after the tabs but before the space:
```
#var test := [
	# 2
#]
```
(that causes no errors)
Of course, technically the old behaviour of Ctrl+K could be reverted to fix this issue as well, but I think the above compromise would work better.
```
#var test := [
#	 2
#]
```
My issue is relevant when trying to comment out huge swathes of code automatically - I don't actually care if the `#` is before or after or in the middle of the tabs and spaces, I just want it to not cause errors by default.
