### ISSUE TITLE
GDScript 2.0: Arguments sent over Callable is of type ExampleClass, but cannot be cast into ExampleClass

### ISSUE THREAD

**Issue by Scraphead** [godotengine/godot#63795] opened 2022-08-01 20:44 UTC
### Godot version

v4.0.alpha13.official

### System information

Windows 11

### Issue description

Unable to cast argument into a custom class when it is invoked by callable from a different gdscript.

The custom class variables are still accessible in receiving function, and it says it is of type custom class, but it fails the cast operation.

Expected outcome is a successful cast into custom class

### Steps to reproduce

1:
Create script my_callable.gd

```gdscript
class_name MyCallable

static func trigger_callable(method : Callable):
	var package = ExampleClass.new()
	package.message = "Howdy"
	method.call(package)

class ExampleClass:
	var message : String
```

2:
Create script callable_cast_null.gd
```gdscript
extends Node

func _ready() -> void:
	MyCallable.trigger_callable(_on_my_callable)

func _on_my_callable(arg):
	print("MyCallable.ExampleClass message in arg: " + arg.message)
	print("Arg is MyCallable.ExampleClass: " + str(arg is MyCallable.ExampleClass))
	print("Casting arg to MyCallable.ExampleClass: " + str(arg as MyCallable.ExampleClass))
```

3:
Create a new scene, attach callable_cast_null.gd to a node and run game

4:
_on_my_callable prints true when checking if argument type is ExampleClass, but it gets null when casting argument into ExampleClass

```gdscript
# _on_my_callable print output:
#  MyCallable.ExampleClass message in arg: Howdy  <-- There is a ExampleClass message value in arg
#  Arg is MyCallable.ExampleClass: true           <-- Argument is of type ExampleClass
#  Casting arg to MyCallable.ExampleClass: null   <-- But still fails to be casted into ExampleClass
```

_**Other:**_
If _on_my_callable has a typed argument, it is not invoked at all
```gdscript
func _on_my_callable(arg : MyCallable.ExampleClass):
```

### Minimal reproduction project

[CallableCastNull.zip](https://github.com/godotengine/godot/files/9237267/CallableCastNull.zip)

**Comment by Scraphead** [comment] 2022-08-03 18:15
On further testing, this does not relate to Callable, but seems to be an issue when using an inner class of another gdscript.

Reduced example:

example_class.gd
```gdscript
class_name ExampleClass

#Cannot cast to this inner class in another gdscript
class InnerClass:
	var message : String
```
inner_class_cast_null.gd
```gdscript
extends Node

func _ready() -> void:
	var example := ExampleClass.InnerClass.new()
	example.message = "howdy"
	print("ExampleClass.InnerClass message in arg: " + example.message)
	print("Arg is ExampleClass.InnerClass: " + str(example is ExampleClass.InnerClass))
	print("Casting arg to ExampleClass.InnerClass: " + str(example as ExampleClass.InnerClass))

	# Output:
	#  ExampleClass.InnerClass message in arg: Howdy  <-- There is a InnerClass message value in arg
	#  Arg is ExampleClass.InnerClass: true           <-- Argument is of type InnerClass
	#  Casting arg to ExampleClass.InnerClass: null   <-- But still fails to be casted into InnerClass
```

Example project:
[InnerClassNullCast.zip](https://github.com/godotengine/godot/files/9254043/InnerClassNullCast.zip)


I think this is a duplicate of #62982

**Comment by Calinou** [comment] 2022-08-03 22:55
Duplicate of https://github.com/godotengine/godot/issues/62982.

**Closed by Calinou** 2022-08-03 22:55 UTC
Labels: bug, topic:gdscript
