### ISSUE TITLE
Bug in release Android export templates. 11/07/16

### ISSUE THREAD

**Issue by alexolin** [godotengine/godot#5645] opened 2016-07-11 13:55 UTC
Operating system or device - Windows10-64  Godot version: 2.1alfa  11/07/16 01:17

Android Export templates builds , but release export template builds without Godot libs.
Debug template is full and work sucessfull.

Compile with:
scons platform=android target=release_debug
gradlew build

in bin folder:
11.07.2016  10:39         9 657 862 android_debug.apk
11.07.2016  10:39         1 543 280 android_release.apk

Release templates is without Godot libs.

**Comment by akien-mga** [comment] 2016-07-11 14:52
Might be related to the recently merged #5077; CC @RandomShaper and @volzhs.

**Comment by RandomShaper** [comment] 2016-07-11 19:32
Could you list what you have in your `platform/android/java/libs` directory, recursively?

**Comment by alexolin** [comment] 2016-07-12 06:13
D:\1107\PLATFORM\ANDROID\JAVA\LIBS
└───debug
    └───armeabi-v7a
            libgodot_android.so

**Comment by RandomShaper** [comment] 2016-07-15 02:22
Yeah, that's wrong.

Please tell me the complete command you used for building so I can check
whether I missed some case.

Anyway, I'm on my honeymoon so I won't be able to do it before a few days.

El 12/7/2016 1:14 a. m., "alexolin" <notifications@github.com> escribió:

>

> D:\1107\PLATFORM\ANDROID\JAVA\LIBS
> └───debug
> └───armeabi-v7a
> libgodot_android.so
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
<https://github.com/godotengine/godot/issues/5645#issuecomment-231946732>,
or mute the thread
<https://github.com/notifications/unsubscribe/ALQCtpX6Y8uyhElYLm-oB1Mw2x4FHvjWks5qUzCsgaJpZM4JJY2T>
.

**Comment by alexolin** [comment] 2016-07-18 11:54
Compile with:
scons platform=android target=release_debug
gradlew build

If copy (before gradlew build) libgodot_android.so to platform\android\armeabi-v7a\ template build full.
![piv15](https://cloud.githubusercontent.com/assets/15943158/16913977/48888262-4cf7-11e6-8731-c2a854c93f82.JPG)

**Comment by volzhs** [comment] 2016-07-18 16:23
I guess this is because of https://github.com/godotengine/godot/blob/d279d060e18fba43c83c77b0f91dcf2f6bfb3fd2/platform/android/SCsub#L123-L130

according to this codes,
we should take only ``android_debug.apk`` if ``scons platform=android target=release_debug`` or ``target=debug``,
and only ``android_release.apk`` if ``scons platform=android target=release``

**Comment by reduz** [comment] 2016-07-18 22:30
Happy honeymoon man! take your time!

**Comment by akien-mga** [comment] 2016-07-27 12:22
So far when building from a *clean* environment (I've seen that build artifacts from before this PR can cause issues, especially if you have an old lib in `armeabi/` and the new one in `armeabi-v7a`) it works just fine for me. Do we still have used who can't build for android properly, or was this just a transition issue?

**Comment by volzhs** [comment] 2016-07-27 14:00
I have same issue if I build for release and release_debug.
I temporarily solved it as describe above, clean ``platform/android/java/libs`` before building each template.

**Comment by RandomShaper** [comment] 2016-07-27 15:35
I can't see why the cleanup is needed after having built before the PR because libs copied inside ´libs/<arch>´ but outside ´libs/debug´ and ´libs/release´ should get just ignored.

Even more confusing is that after the initial cleanup you have to do an additional one between debug/release variants.

So, @volzhs, will you follow the procedure one again listing what you have in `android/java/lbs`?:

1) Do the initial cleanup.
2) Run `scons platform=android target=release` and list contents.
3) **Don't perform the additional cleanup here.**
3) Run `scons platform=android target=release_debug` and list again.

**Comment by RandomShaper** [comment] 2016-07-27 15:40
Just in case it's not clear, `gradle build` should be run only once after you have built the library for both release and debug/release_debug. It takes care of packaging both APKs taking the libraries from the appropiate directories.

**Comment by volzhs** [comment] 2016-07-27 16:47
I will try it again, but what I have experienced as #5850.
It seems to OK but, I got wrong android template in ``bin`` if I don't clean ``libs``

**Comment by volzhs** [comment] 2016-07-27 17:50
@RandomShaper did you try to make a release template after making release_debug or vise versa without cleaning libs directory?
try to make android templates with 370ae3512deda40b2659a1192f302298e269305f commit and then make it again with current head.
then test with these templates by one click deploy.
This is what I had done and I got crash.
I don't have any ``armeabi`` directory under ``platform/android/java``

**Comment by volzhs** [comment] 2016-07-28 15:49
@RandomShaper This is what I did with fresh clone current head.

```
scons -j 4 platform=android colored=yes tools=no theora=no speex=no dds=no pvr=no openssl=no musepack=no disable_tooltip=yes target=release

tree platform/android/java/libs
D:\DEVELOPMENT\GODOT-MASTER\PLATFORM\ANDROID\JAVA\LIBS
└─release
    └─armeabi-v7a

platform/android/java/gradlew.bat build
```

in bin folder,

android_debug.apk - **629,441**
android_release.apk - **7,538,967**

android_debug.apk does not have ``lib/armeabi-v7a``

**Comment by RandomShaper** [comment] 2016-07-28 17:05
I think I've spotted the problem: the build fails at link time for release_debug due to some undefined symbols. That's why the debug APK has no libraries inside and thus the crash at runtime.

I'm doing further research on why that happens.

**Comment by RandomShaper** [comment] 2016-07-28 17:08
Anyway, here a the link errors in case someone has an explanation of why these appear for release_debug and not for release:
```
platform\android\java_class_wrapper.os:java_class_wrapper.cpp:function JavaClassWrapper::_bind_methods(): error: undefined reference to '_MD(char const*, char const*)'
platform\android\java_class_wrapper.os:java_class_wrapper.cpp:function JavaClassWrapper::_bind_methods(): error: undefined reference to 'MethodBind::_generate_argument_types(int)'
platform\android\java_class_wrapper.os:java_class_wrapper.cpp:function JavaClassWrapper::_bind_methods(): error: undefined reference to 'ObjectTypeDB::bind_methodfi(unsigned int, MethodBind*, MethodDefinition const&, Variant const**, int)'
```

**Comment by RandomShaper** [comment] 2016-07-28 17:13
It seems it's not up to a particular release/release_debug variant but it's up to the order in which you perform both builds (as someone pointed out or some other circumstance).

So in principle no code is to blame.

**Comment by reduz** [comment] 2016-07-28 17:21
feel free to disable javaclass wrapper, it's not currently in use

**Comment by RandomShaper** [comment] 2016-07-28 17:32
I'm starting to think this is related to the multicore builds (`scons -j`) on Windows.

@volzhs, you are building on Windows, aren't you? Have you PyWin32 installed? I myself have it not installed as I read somewhere that on current versions of Python it's not needed anymore.

In such scenario, SCons might be getting confused when building with #5077 after having built previously without it and that would explain the somewhat random and difficult to reproduce problem.

**Comment by volzhs** [comment] 2016-07-28 18:02
@RandomShaper I don't have a problem making ``libgodot_android.so`` for release_debug on Windows.
It builds successfully.
In my case, it's fine if clear ``platform/android/java/libs``

**Comment by RandomShaper** [comment] 2016-07-28 20:48
We could conclude this is a transition issue, right?

When the docs get updated a note about this could be put.

By the way, I'm ready to update the docs with the new build procedure as
soon as it's considered functional.

**Comment by akien-mga** [comment] 2016-07-31 20:33
> By the way, I'm ready to update the docs with the new build procedure as soon as it's considered functional.

The release is imminent, so feel free to give it a go :) There's actually a pending PR for that but I'm not fully happy with the more subjective changes made (https://github.com/godotengine/godot-docs/pull/214).

**Comment by KelinciFX** [comment] 2016-08-03 05:48
> I'm not fully happy with the more subjective changes made (godotengine/godot-docs#214).

"More subjective changes made". That's a nice sentence. Thanks...

To be honest and clear. Seriously, I never encounter this kind of error.

About packaging the .apk(s) : 

I prefer Android Studio (v2.1.2) way when building the .apk(s). It used assemble{Release|Debug} command, instead of "build" one. So, I usually do (Win OS):

A.] android_release.apk
1) scons -j 4 p=android tools=no target=release
2) cd platform\android\java
3) gradlew assembleRelease

B.] android_debug.apk
1) scons -j 4 p=android tools=no target=release_debug
2) cd platform\android\java
3) gradlew assembleDebug

![compiling_android_done_right_godot_2 1rc1](https://cloud.githubusercontent.com/assets/12244526/17355050/8d80a85c-596f-11e6-8960-7118e562c23f.png)

assembleRelease &/ assembleDebug run faster than build. I think it's mainly because build will do many tasks, including "unused" ones.

Note:
"gradlew build" doesn't always work as it should. Sometimes Gradle want us to hit "gradlew clean" first before doing second or next "gradlew build" command when a change had been done.

I also made a note about this on my "more subjective changes made" PR.

:-)

**Comment by RandomShaper** [comment] 2016-08-03 11:10
`build` runs the tests (as long as they are present), which AFAIK it's currently not the case. If in some future some Android-specific tests were added, it would have to be changed back. Not a big concern, I think.

Also note that after building all the variants of the .so via multiple SCons commands, a single `gradle build` will package both release and debug export templates.

**Comment by KelinciFX** [comment] 2016-08-03 16:21
Agree... build is not the case. Luckily, I didn't say that build is the case. Yes, gradle build will do fat packaging, it made me thinking why build is slightly slower than assembleR|D. The case (IME) was "gradle clean" need to be fired up before doing second or next "gradle build". It's probably "just" my though. So, it's quite ok to not deal with that.

Please, bear in mind that I'm not an advanced Godot user nor an expert programmer. I'm very happy there are some expert contributor (RandomShaper, Volzhs, Jay3d, and others) improving Godot for Android. I see Godot is great, it deserves more and more users. As we know, Android is by far the most popular mobile platform. I think if Android support in Godot is amazing, Android developers who tries Godot will be happy and probably spend more time on Godot, even better stick with it for developing their Android app/game.

:-)

**Comment by volzhs** [comment] 2016-08-08 16:17
Someone suffers same issue.
https://godotengine.org/qa/6771/android-release-template-too-small-and-not-working

**Comment by plucian** [comment] 2016-08-08 19:45
I cleared the libs as suggested.  libgodot_android.so is in the correct folder 20.6M. No luck, the release template is still small ~1.5M and not working.

**Comment by volzhs** [comment] 2016-08-08 20:19
@plucian what about doing ``gradlew clean`` before ``gradlew build``?

**Comment by reduz** [comment] 2016-08-08 20:25
you might have to create some directories manualy because git does not
store empty directories?

**Comment by plucian** [comment] 2016-08-08 20:40
@volzhs I've already tried it before my first post, since was already mentioned here
@reduz I think I have all the directories needed, I did not git clone anyway, I downloaded the zip file. But in any case if I should manually create some directories which directories should I create ?

**Comment by RandomShaper** [comment] 2016-08-08 21:44
With the current status of this, no directories should be needed to be
created by hand.

Has the release .so file at least been created for you under /bin?

If that was the case, perhaps the culprit of these issues is the line of
the SCons script where it copies it to its final destination inside the
android dir.

I am new to SCons and probably I misunderstood how that works. Maybe some
SCons expert could have a look there.

**Comment by volzhs** [comment] 2016-08-08 21:51
@RandomShaper in my case, ``.so`` file is moved to expected location ``platform/android/java/libs/release[debug]``, but still happens.

**Comment by plucian** [comment] 2016-08-08 23:36
I thought I'd start from scratch, downloaded latest version, this time the compilation gave lots of errors and doesn't finish building because of errors...
printing the last part:
core\variant_call.cpp: In static member function 'static Variant::Type Variant::
get_method_return_type(Variant::Type, const StringName&, bool*)':
core\variant_call.cpp:1209:26: error: 'const struct _VariantCall::FuncData' has
no member named 'return_type'
   *r_has_return=E->get().return_type;
                          ^
core\variant_call.cpp:1211:18: error: 'const struct _VariantCall::FuncData' has
no member named 'return_type'
  return E->get().return_type;
                  ^

**Comment by volzhs** [comment] 2016-08-08 23:58
@plucian There is a issue for it #6022.
It has been about a week.

**Comment by akien-mga** [comment] 2016-08-09 05:45
@plucian @volzhs That does not seem related to #6022, but more an issue linked with #6055 (cc @eska014). You're trying to build 2.2-alpha though, better switch to the 2.1 branch to test the latest stable code.

**Comment by volzhs** [comment] 2016-08-09 06:22
@akien-mga @plucian Oh, my mistake :)

**Comment by plucian** [comment] 2016-08-09 09:43
ok guys, I downloaded an older version, followed the instructions and this time it worked. What I did different from the first time:
- I built first the release template which took a very long time and have yet to build for the debug version, the debug version was also created by gradlew build but since it did not have an libgodot_android.so in the lib folder, came out small as expected and not working, as expected.
- I used a different commit but I cannot say for sure which one, initially I used the RC01.
I'm sure is not enough information to track down the problem but every bit counts, I think..

**Comment by RandomShaper** [comment] 2016-08-09 10:16
Users who still suffer/can reproduce the issue, please merge [this](https://github.com/RandomShaper/godot/tree/fix-android-build) and try again.

I'll open a PR if it works.

**Comment by volzhs** [comment] 2016-08-12 16:25
@RandomShaper I don't think https://github.com/RandomShaper/godot/commit/1775381e50de21abfff3e77ff8000340f0899ba2 would not fix it.
Because, I don't have problem with locating ``.so`` files under ``platform/android/java/libs/release[debug]/armeabi-v7a``

``libgodot_android.so`` is under ``libs/release/armeabi-v7a`` if build with target=release,
and ``libgodot_android.so`` is under ``libs/debug/armeabi-v7a`` if build with target=release_debug.
No problem with that.

The problem is, when do ``gradlew build``, final apk file does not contain ``.so`` file in latter case.
if build debug after release, then debug apk does not have it.
if build release after debug, then release apk does not have it.
if clean in ``libs`` before ``scons && gradlew build``, then works.

I didn't test ``scons`` > ``clean libs`` > ``gradlew build`` sequence.

**Comment by akien-mga** [comment] 2016-10-03 19:43
Was this effectively fixed by e906563?

**Comment by plucian** [comment] 2017-02-24 19:59
I haven't have any problem since. Maybe this should be closed now?

**Comment by bojidar-bg** [comment] 2017-02-24 20:22
Well, would be nice, yeah :smiley: We can reopen if needed.

**Closed by bojidar-bg** 2017-02-24 20:22 UTC
Labels: bug, platform:android, topic:buildsystem
