### ISSUE TITLE
Crash in Connecting Signal Window when clicking in empty space inside the Connect To Node area 

### ISSUE THREAD

**Issue by biglari** [godotengine/godot#14922] opened 2017-12-21 23:18 UTC
**Godot version:**
Godot 3.0 Beta 1 mono win64

**OS/device including version:**
Windows 7 Professional SP1 64 bit

**Issue description:**
When connecting Signals the Window which opens leads to a crash when clicking anywhere in the empty area in the "Connect To Node" area. 

**Steps to reproduce:**
1. Create new Project
2. Create Area2D Node
3. Select Node, and under Node tab add any Signal
4. In "Connecting Signal" window, click in "Connect To Node" area anywhere other than the Area2D item

**Comment by hpvb** [comment] 2017-12-22 00:51
I can't reproduce this on 3068ccc8e69aad68c860ce8688bdc6d41107be1b on Linux/x86_64 would it be possible for you to create a video or gif of exactly what you're doing?

Could you also try with the freshly released beta 2?

Thanks!

**Comment by biglari** [comment] 2017-12-22 01:35
Problem is solved in Beta 2

**Comment by vnen** [comment] 2017-12-22 01:37
Closing as solved then.

**Closed by vnen** 2017-12-22 01:37 UTC
Labels: bug, topic:editor
