### ISSUE TITLE
Random visual Artifacts with Vulkan Renderer in Godot 4 using GpuParticles2d

### ISSUE THREAD

**Issue by codingvessel** [godotengine/godot#66471] opened 2022-09-26 21:19 UTC
### Godot version

4.0.dev

### System information

Windows 10

### Issue description

When creating GpuParticles2d and removing them i encounter lots of random visual artifact lines across the screen.

I remove each particle system with a timer set to queue_free() after 1 second.

The artifacts only appear when combined with the removal.

### Steps to reproduce

Just start the Main scene in MRP.

### Minimal reproduction project

[RenderingBug.zip](https://github.com/godotengine/godot/files/9649737/RenderingBug.zip)

**Comment by Calinou** [comment] 2022-09-26 22:14
Duplicate of https://github.com/godotengine/godot/issues/56691.

**Closed by Calinou** 2022-09-26 22:14 UTC
Labels: bug, topic:rendering

**Comment by Wiggan** [comment] 2023-07-06 10:54
This issue and both duplicates are closed. The issue is very much present in 4.0.3 though. 
Is there no other way of working around this than just having the world far away from [0, 0, 0]?

**Comment by clayjohn** [comment] 2023-07-06 11:21
@Wiggan I think you may be running into https://github.com/godotengine/godot/issues/71935 As this issue is related to GPUParticles2D. https://github.com/godotengine/godot/issues/71935 already has a PR that should be merged soon for 4.2/4.1.1
