### ISSUE TITLE
Ability of selecting sub-scenes from the main 3D view

### ISSUE THREAD

**Issue by zoiba** [godotengine/godot#6867] opened 2016-10-19 08:56 UTC
complex 3D levels may be a pain to edit, if you can't select each elements from the 3d view, you have to find each scene element by browsing the hierarchy tree and, if you have hundred of elements made by sub-scenes, it's very frustrating finding a specific one.

**Comment by Zylann** [comment] 2016-10-19 12:33
I find it hard to select stuff in the 3D screen in general too. Sometimes it works, sometimes it doesn't at all.

**Comment by zoiba** [comment] 2016-10-19 14:37
it doesn't work when you try to select instantiated  sub-scenes, otherwise it works. In simple scenes you can always select stuff from the scene tree but on complex scenes is a pain.

**Comment by Zylann** [comment] 2016-10-19 17:38
Right, I can reproduce your issue, even with "editable children" enabled. Should not make a difference, but I note it just in case.

**Comment by Noshyaar** [comment] 2018-04-07 07:14
First of all thank you for your report and sorry for the delay.

We released Godot 3.0 in January 2018 after 18 months of work, fixing many old issues either directly, or by obsoleting/replacing the features they were referring to.

We still have hundreds of issues whose relevance/reproducibility needs to be checked against the [current stable version](https://godotengine.org/download), and that's where you can help us.
**Could you check if the issue that you described initially is still relevant/reproducible in Godot 3.0 or any newer version, and comment about it here?**

For bug reports, please also make sure that the issue contains detailed steps to reproduce the bug and, if possible, a zipped project that can be used to reproduce it right away. This greatly speeds up debugging and bugfixing tasks for our contributors.

Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

Thanks in advance.

*Note: This message is being copy-pasted to many "stale" issues (90+ days without activity). It might happen that it is not meaningful for this specific issue or appears oblivious of the issue's context, if so please comment to notify the Bugsquad about it.*

**Comment by Zylann** [comment] 2018-04-07 16:15
I tried to instance a scene into a main 3D scene, clicking on it makes the root node of the instance selected, so I can't reproduce sub-scene selection bug.

Related issue about selection in 3D: https://github.com/godotengine/godot/issues/10979
I still find 3D selection is not always working good in some cases.

**Comment by akien-mga** [comment] 2018-11-22 10:55
There were lots of improvements to selecting scenes in the 3D viewport, as the original problem seems to be fixed, so closing. Remaining issues with scene selection should be tracked in new bug reports against the current master branch.

**Closed by akien-mga** 2018-11-22 10:55 UTC
Labels: discussion, feature proposal, topic:editor
