### ISSUE TITLE
GDScript: or-expression evaluation

### ISSUE THREAD

**Issue by koalefant** [godotengine/godot#3023] opened 2015-12-09 00:16 UTC
Following code would invoke call_node function even if first part of or-expression (condition == null) succeeds:
```gdscript
if condition == null or call_node( condition ):
     # whatever
```
This is different from how Python or C++ would evaluate such expression. Is this an intended behavior?

**Comment by akien-mga** [comment] 2015-12-09 06:37
Confirmed in the current master branch.

**Comment by bojidar-bg** [comment] 2015-12-09 10:12
I'm not sure that this is a bug, BTW. It might as well be intended behaviour.

**Comment by Ovnuniarchos** [comment] 2015-12-09 17:04
It'd be useful to test if `and` uses short-circuit eval or not. If their behavior differs, one of the two would have to give.

**Comment by 29jm** [comment] 2015-12-09 17:15
@Ovnuniarchos `and` uses short-circuit. IMHO `or` should do the same.

**Comment by punto-** [comment] 2015-12-09 18:37
Does it do the same if you use || ?

**Comment by Ovnuniarchos** [comment] 2015-12-10 14:29
Does it still happen in  current master (8a94297105e0c67055dcfeaa9643ca6fb734ef04)? Can't reproduce.

**Comment by vnen** [comment] 2015-12-10 15:54
I can't reproduce this with a recent build (2d84943).

For me it has the following behavior:

```GDScript
if true or test() # Does not run "test"
if false and test() # Does not run "test"
```

It doesn'

And I believe that this is the most intuitive way as most programming languages do the same. It also has a little better performance, as it won't be calling unneeded functions that wouldn't make the condition change anyway.

**Comment by akien-mga** [comment] 2015-12-10 15:58
I tried it a couple of days ago and *could* reproduce the issue, with something like:
```
var i = 0

func test():
    i += 1

func _ready():
    var testbool = true
    if testbool or test():
        pass
    print(i)
```
IIRC the print gave me "1". I'll try again in the evening.

**Comment by koalefant** [comment] 2015-12-11 12:11
Unfortunately I can't reproduce it myself anymore. I will try again with older versions.

**Comment by vnen** [comment] 2015-12-11 14:19
It seems the original issue does not happen anymore. If it happened in an earlier version, then it's now fixed, so no reason to keep this open. May reopen if there's any news on this subject.

**Closed by vnen** 2015-12-11 14:19 UTC
Labels: bug, confirmed, topic:gdscript
