### ISSUE TITLE
Final letter in a text button sometimes clips (Godot 4.1.3, iPhone 6/7/8)

### ISSUE THREAD

**Issue by scripturial** [godotengine/godot#85449] opened 2023-11-28 00:05 UTC
### Godot version

4.1.3

### System information

Sonoma 14.0, Xcode 15.0.1, iPhone (see below) 

### Issue description

Rendering text inside a text button clips the final letter, but leaves a space where the letter should be:

![](https://scripturial.com/files/button-text-clip.png)

I am trying to narrow down which devices this is a problem for. Based on user feedback it appears that the problem might be limited to iOS 15, or specific older models of iPhone with a 750 wide screen resolution.

### Steps to reproduce

It is difficult to reproduce. The problem occurs on:

 - iPhone 7 / iOS 15.8

The problem does not occur on:

 - iPhone XS Max / iOS 17.1.1
 - iPhone 14 / iOS 17.1.1
 - iPhone SE 3rd gen / 16.6
 - iPad Air 5th gen / 16.5

The app runs with the older "compatibility engine". And the buttons are using a google font embedded into the app for cross phone/os consistency and for support for characters in other languages, if it matters, the font is NotoSans.

### Minimal reproduction project

Unfortunately I have not yet been able to reproduce the problem, I am still investigating.

**Comment by scripturial** [comment] 2023-11-28 00:16
In case it's helpful to note, clipping and overrun behavior is disabled. So it is strange that any letter would disappear like this.

<img width="322" alt="image" src="https://github.com/godotengine/godot/assets/138373494/ba41b03b-0166-4fd1-85e6-4fe170b73686">

**Comment by scripturial** [comment] 2023-11-28 03:03
It doesn't seem likely, but I can't help but wonder if this issue with determining the text width needed for the button is connected somehow to https://github.com/godotengine/godot/issues/80907

**Comment by Rindbee** [comment] 2024-01-18 08:01
Possibly a duplicate of #81624.

**Comment by Calinou** [comment] 2024-01-18 15:32
Thanks for the report! Consolidating in https://github.com/godotengine/godot/issues/81624, as this is likely due to the same cause.

**Closed by Calinou** 2024-01-18 15:32 UTC
Labels: bug, topic:gui
