### ISSUE TITLE
Transparency issues on 4.3.dev

### ISSUE THREAD

**Issue by NotRabug50** [godotengine/godot#91459] opened 2024-05-02 14:11 UTC
### Tested versions

-4.3.dev6
-4.2.2.stable
-3.5.3.stable

### System information

Godot v4.3.dev6 - Windows 10.0.22631 - Vulkan (Forward+) - dedicated NVIDIA GeForce GT 1030 (NVIDIA; 31.0.15.5161) - AMD Ryzen 3 1300X Quad-Core Processor (4 Threads)

### Issue description

![image](https://github.com/godotengine/godot/assets/78092286/5383ef4f-27b0-4312-85b4-b9f64074e378)
Godot 4.3 fixed splash screen transparency issues but there is also weird issues in transparency as you can see on the image above when you have a transparent splash screen it has a weird semi-transparent flashing. also has a flashing on scaling on transparent
![image](https://github.com/godotengine/godot/assets/78092286/eed5bdc3-de1c-4f8b-9f6e-1b2917f39111)
also godot 3 does not have this issue

### Steps to reproduce

-Open Godot 4
-Turn on transparency and make splash screen background color transparent
-Or scale window fast

### Minimal reproduction project (MRP)

N/A

**Comment by ChristopheClaustre** [comment] 2024-06-29 09:04
I tried to reproduce the bug but I don't understand it what it is exactly.

> -Open Godot 4
> -Turn on transparency and make splash screen background color transparent
> -Or scale window fast

What do you mean by `Turn on transparency` ?
After my tests, alpha of splashscreen background colour seems to be ignored.
But what is the meaning of having a transparent background on splashscreen, what is behind the splashscreen/window that you want to see ?

Can you produce a MRP with the project settings that reproduce your bug ?
Since the problem appears when scaling window, can you produce a video maybe ?

**Comment by Calinou** [comment] 2024-06-29 23:11
This is due to the same cause as https://github.com/godotengine/godot/issues/92712 and https://github.com/godotengine/godot/issues/83939. You're seeing the scaled area as temporarily white as scaled areas are white until Godot assigns them a color, and white with premultiplied alpha is visible even if alpha is 0.0.

Closing in favor of the above linked issues (there may be even more open issues about this out there).

**Closed by Calinou** 2024-06-29 23:11 UTC
Labels: bug, platform:windows, topic:core, topic:rendering, needs testing
