### ISSUE TITLE
Godot does some weird stuff when deleting folders

### ISSUE THREAD

**Issue by Shadowblitz16** [godotengine/godot#38160] opened 2020-04-23 21:27 UTC
**Godot version:**
3.2.1

**OS/device including version:**
Windows 10 Pro Education 64 bit

**Issue description:**
I just deleted a folder and now its still there and it thinks its the root
![image](https://user-images.githubusercontent.com/2453707/80151297-a6d38c00-856e-11ea-82c8-5524c0ae53db.png)

**Steps to reproduce:**
- Delete a folder in a folder.

**Minimal reproduction project:**
can't give one because it corrects on reload.

**Comment by KoBeWi** [comment] 2020-04-23 21:37
Duplicate of #27526

**Closed by KoBeWi** 2020-04-23 21:37 UTC
