### ISSUE TITLE
Raster section values in monitors always 0

### ISSUE THREAD

**Issue by UgisBrekis** [godotengine/godot#17302] opened 2018-03-06 12:55 UTC
**Godot version:**

Godot v3.0 stable official

**OS/device including version:**

Windows 10, Nvidia GeForce GTX 970

**Issue description:**

All the raster monitor values(draw calls, surface changes, shader changes, mat changes, vertices drawn, objects drawn) are always 0 and they do not represent the actual state. 

I am using only 2D mode and I haven't tested this in 3D. 

**Steps to reproduce:**

1. Run the game
2. Go to "Monitors"
3. Observe "Raster" section

**Minimal reproduction project:**

**Comment by ttencate** [comment] 2018-04-10 08:35
Confirmed in Godot 3.0.2, Arch Linux, GeForce GTX 960/PCIe/SSE2.

**Comment by volzhs** [comment] 2018-04-10 09:01
I think it's same issue with #9080

**Comment by Calinou** [comment] 2020-04-11 21:54
Duplicate of #8373.

**Closed by Calinou** 2020-04-11 21:54 UTC
Labels: bug, topic:editor
