### ISSUE TITLE
Ambient occlusion gets darker (until black) the closer the camera

### ISSUE THREAD

**Issue by Flavelius** [godotengine/godot#48503] opened 2021-05-06 12:59 UTC
**Godot version:**

3.3.stable.mono.official

**OS/device including version:**

Win10
nvidia gtx1060

**Issue description:**

https://user-images.githubusercontent.com/8841352/117301650-1fa43e00-ae7b-11eb-9816-5b1aa54eac3f.mp4

The closer the camera is to creases, the darker the AO post effect gets (i.e. zoomed in over-the-shoulder view on characters creates black neck, armpits etc).

**Steps to reproduce:**
Enable AO post effect, zoom into geometric crevices/creases.

**Comment by Calinou** [comment] 2021-05-06 13:37
@Flavelius Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

**Comment by Flavelius** [comment] 2021-05-06 15:22
[BugProject.zip](https://github.com/godotengine/godot/files/6435718/BugProject.zip)
It's a little less pronounced here, probably because of different angles etc., but it still shows that at some point it just gets stronger. There, activate preview mode for the camera and play the attahed animation that moves the camera. Additionally it even seems to flicker at some points (more pronounced when manually moving around and zooming in in the sceneview).

**Comment by Calinou** [comment] 2021-05-06 15:25
> as inversely it even gets a lot weaker the further away.

This is expected, as SSAO cannot represent ambient occlusion on far away details accurately. You need to use baked ambient occlusion (lightmaps, GIProbe in 4.0, …) for that.

**Comment by Flavelius** [comment] 2021-05-06 15:30
Ok, but then atleast it doesn't work correctly for those close small details too (as visible in the entry-video). I, personally would be fine with a simple (customizable if necessary) clamp.

**Comment by josefkaragoli** [comment] 2021-05-14 09:39
@Flavelius the current SSAO implementation was discontinued in favour of the ASSAO implementation for 4.0. I dont think it can be backported to 3.x since it uses compute shaders which are not present on openGL. Inplementing a distance clamping system is a good temporary solution until 4.0 comes.

**Comment by Calinou** [comment] 2021-12-26 15:31
Closing in favor of https://github.com/godotengine/godot-proposals/issues/3720, as the current behavior is technically not a bug.

**Closed by Calinou** 2021-12-26 15:31 UTC
Labels: bug, topic:rendering, confirmed, topic:3d
