### ISSUE TITLE
AStar weird behavior 

### ISSUE THREAD

**Issue by ElefanteNoi** [godotengine/godot#31284] opened 2019-08-11 07:56 UTC
**Godot version:**
Godot 3.1.1

**OS/device including version:**
Windows 10

**Issue description:**
AStar give different path each time it run.

**Steps to reproduce:**
https://media.giphy.com/media/Ll3RkMB5uI7km8BTsq/giphy.gif
each time project is run AStar give different path.

**Minimal reproduction project:**
[AStar.zip](https://github.com/godotengine/godot/files/3489636/AStar.zip)

if i run on different PC (Windows 7) it give the same path every time unlike the GIF above.
~~https://imgur.com/QDlhH0e~~
https://media.giphy.com/media/L0TtgVNE7IM4YFwB6K/giphy.gif

**Comment by KoBeWi** [comment] 2019-08-11 10:46
Isn't this intended though? Each path has the same length.

**Comment by KoBeWi** [comment] 2019-11-08 01:32
Looks like duplicate of #25617, except the Windows 7 part.

**Comment by tom-jk** [comment] 2020-07-20 13:27
On linux mint 18.3:
Can reproduce in 3.1.2.stable.
Can no longer reproduce in 3.2.2.stable.

Video comparison (length: 0m18s): https://youtu.be/tIZscFRTl9Q

**Comment by Calinou** [comment] 2020-07-20 13:33
@tom-jk Thanks for testing this :slightly_smiling_face: I'll assume this was resolved between 3.1.2 and 3.2.2.

**Closed by Calinou** 2020-07-20 13:33 UTC
Labels: bug, topic:navigation
