### ISSUE TITLE
Editor crashes when changing a node's type to StatusIndicator

### ISSUE THREAD

**Issue by Skystr1ke** [godotengine/godot#89613] opened 2024-03-17 16:23 UTC
### Tested versions

- Reproducible in: v4.3.dev5.official [89f70e98d], v4.3.dev4.official [df78c0636]
- Not reproducible in: all previous Godot versions

### System information

Godot v4.3.dev5 - Windows 11 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 4070 Laptop GPU (NVIDIA; 31.0.15.5161) - 13th Gen Intel(R) Core(TM) i9-13900H (20 Threads)

### Issue description

Adding a node to the tree and changing its type to StatusIndicator crashes the editor.

### Steps to reproduce

1. Add a node to the scene tree.
2. Right-click it and select "Change Type..."
3. Select StatusIndicator from the menu and click "Change".

### Minimal reproduction project (MRP)

N/A

**Comment by AThousandShips** [comment] 2024-03-17 17:18
Sounds similar to:
* https://github.com/godotengine/godot/issues/89425

**Comment by ajreckof** [comment] 2024-04-03 11:44
I was unable to reproduce the crash on 4.3dev5 by following the reproduction steps. I agree with AThousandShips that it looks like a duplicate of #89425. If so it is already fixed.

**Comment by AThousandShips** [comment] 2024-05-18 11:03
Closing as fixed, if this is a different bug please comment and this can be reopened

**Closed by AThousandShips** 2024-05-18 11:03 UTC
Labels: bug, topic:editor, needs testing, crash
