### ISSUE TITLE
Auto re-import of .gltf file failed with  BUG: File queued for import, but can't be imported!

### ISSUE THREAD

**Issue by idchlife** [godotengine/godot#47737] opened 2021-04-08 22:03 UTC
**Godot version:**

3.2.3 stable

**OS/device including version:**

macos catalina

**Issue description:**

Reimport of .gltf file failed. Need to open file without inherited scene to refresh it into the project.
In output:
 editor/editor_file_system.cpp:1766 - BUG: File queued for import, but can't be imported!
 editor/editor_file_system.cpp:1767 - Method failed.

**Steps to reproduce:**
1) Create model in Blender.
2) Save if into the project files.
3) Create inherited scene with it.
4) Save the scene.
5) Open .blend file. Edit. Re-export with the same name as .gltf
6) See error in output.
7) Open model manually to refresh it in the project. (model will also be refreshed in the saved inherited scene)

**Minimal reproduction project:**

**Comment by Calinou** [comment] 2021-04-08 22:52
Duplicate of https://github.com/godotengine/godot/issues/45524.

**Closed by Calinou** 2021-04-08 22:52 UTC
