### ISSUE TITLE
Tabbed Container's children's Y position should account for TabHeight.

### ISSUE THREAD

**Issue by Brickcaster** [godotengine/godot#10633] opened 2017-08-25 13:20 UTC
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Godot 2.1.3

**Issue description:**
I created a Tabbed Container and then created a panel child node.  Setting the panel's position to x,0 causes it to overlap the tab display.

**Expected behavior:**
Tabbed containers' children account for the offset of the tabs, similar to how children of Window Dialog use x,0 as the bottom of the title bar rather than cover it.

**Comment by akien-mga** [comment] 2018-01-15 10:14
Is this still reproducible in Godot 3.0 RC1?

**Comment by bojidar-bg** [comment] 2019-04-24 11:14
Duplicate of #20750, thus fixed.
Fox the record, the problem was that the Y position could be changed, not that the TabsContainer didn't take it into account.

**Closed by bojidar-bg** 2019-04-24 11:14 UTC
Labels: bug, confirmed, topic:core
