### ISSUE TITLE
Problem with event.is_action() 

### ISSUE THREAD

**Issue by mathpeseg** [godotengine/godot#22126] opened 2018-09-15 20:53 UTC
**Godot version:**
3.0.6.stable.oficcial.8314054  (Steam Version)

**OS/device including version:**
Windows 10

**Issue:**

So, when i use this line of code using GDscript : 
` right_vel = int(event.is_action("ui_right"))`

The code dosen't work like i expected it to work, but when used
```
if event.is_action_pressed("ui_right"):
	right_vel = 1
elif event.is_action_released("ui_right"):
	right_vel = 0
```
it works as expected. 
In the first code it only returns false when another key is pressed. In the secound, it returns false when a key is released, and not when a new one is pressed.

Is this a problem with the "event.is_action()"?
if not, could there be made an "event.is_action_pressed_and_released()" or something like that?

Project with both exemples in two diferent objects:
[Exemple1.zip](https://github.com/godotengine/godot/files/2386096/Exemple1.zip)

**Comment by mathpeseg** [comment] 2018-09-15 22:28
May be related to: #6388 and #6612

**Comment by mathpeseg** [comment] 2018-09-16 17:04
So, it is not suposed to return true when pressed and false when released? i tought it would be way easier to use a function that does that. Not that it is really needed, i can allways use ifs and elses like i used there. but it dosen't look as clean as it would look in the first exemple. Thanks anyways. ^^

**Comment by vnen** [comment] 2018-09-16 17:43
> So, it is not suposed to return true when pressed and false when released? i tought it would be way easier to use a function that does that.

It's what `is_action_pressed()` does. Of course returning `false` doesn't really mean the action was released, it could be another action that was triggered, but `is_action()` returning `false` on release would mean the same thing.

In any case, it's not a bug so I'll close this.

**Closed by vnen** 2018-09-16 17:43 UTC
