### ISSUE TITLE
Android low FPS and GPU timer not updating after 73eff10

### ISSUE THREAD

**Issue by roalyr** [godotengine/godot#88355] opened 2024-02-15 04:15 UTC
### Tested versions

Bug appears in 4.x 73eff10c76c201a083193c044de1836217b4d72b

Previous commit f317cc713aa4dbcee2efa10db764473a56680be7 doesn't have the bug

(builds are here: https://github.com/roalyr/godot-for-3d-open-worlds/releases/tag/Test2 )

### System information

Lenovo TB350FU, ARM Mali-G57 MC2 and Motorola moto g(60), Adreno 618, all in Vulkan mobile mode.

### Issue description

1. GPU timer freezes and rarely updates.
2. FPS is lower than expected in 3D scenes (bug-free editor has 2 - 2.5 more FPS, both in editor itself and when launching the scene).
3. Occasionally prints out error: 
```
drivers/vulkan/rendering_device_driver_vulkan.cpp:2538 - Condition "err != VK_SUCCESS" is true. Returning: ERR_CANT_CREATE
```

### Steps to reproduce

Compile Android editor of both version (see commit numbers above) and test 3D scenes that are expected to render at less FPS than screen refresh rate (moderately demanding renders). This way on the same scenes the difference in FPS will be clearly visible.

### Minimal reproduction project (MRP)

Any (I noticed on this scene (just launch it after cloning the repo): https://github.com/roalyr/GD4Lancer/blob/main/Scenes/Stellar/Nebulas/Nebula.tscn the FPS difference was 17-18 vs 38-42 less or more).

**Comment by roalyr** [comment] 2024-02-15 04:29
Builds: https://github.com/roalyr/godot-for-3d-open-worlds/releases/tag/Test2

**Comment by DarioSamo** [comment] 2024-02-15 12:08
A few things to confirm that come to mind:

- [ ] If this behavior actually happens in upstream Godot or only in the fork you linked.
- [ ] Testing with and without V-Sync to see if behavior is any different.
- [ ] Adding some printing to swap chain resizing to see if for some reason it's not constantly being triggered.

There's not many much behavior changes I can think of yet that could trigger such an issue. I'll try to test myself on Android but I don't recall other people noticing any such behavior when testing the PR on the platform, so I'm a bit lost on what it could possibly be at the moment.

**Comment by DarioSamo** [comment] 2024-02-15 12:22
> Adding some printing to swap chain resizing to see if for some reason it's not constantly being triggered.

This is what's constantly happening for some reason apparently!

**Comment by DarioSamo** [comment] 2024-02-15 12:44
It seems we're stuck in a loop where VK_SUBOPTIMAL_KHR is returned during present no matter what we do in Android.

I'm not sure how we can retrieve why it does this, but whatever we're doing to recreate the swap chain. It could be easily explained why the previous version didn't trigger this bug: [it just ignored suboptimal](https://github.com/godotengine/godot/blob/474589eb838623f4a59628c0316d0d27f83ed3d1/drivers/vulkan/vulkan_context.cpp#L2678).

I'll try to confirm whether the previous version was running into this as well and simply ignored it or if the swap chain recreation we're doing right now is missing something from doing it as optimal.

**Comment by DarioSamo** [comment] 2024-02-15 12:54
It seems indeed the previous version has always triggered VK_SUBOPTIMAL_KHR in android, it just chose to ignore it during presentation and it never led to resizing. I'll investigate as to why it never achieves the optimal presentation but I suspect it might be due to something...

**Comment by DarioSamo** [comment] 2024-02-15 13:13
So my suspicion was right.

Godot does not handle screen rotation natively, as it always creates the swap chain with VK_SURFACE_TRANSFORM_IDENTITY_BIT_KHR despite the current transform being different (for example VK_SURFACE_TRANSFORM_ROTATE_90_BIT_KHR on my landscape mode during testing).

The error goes away if I use the transform that is marked as the current transform, but the screen looks distorted and incorrect.

![image](https://github.com/godotengine/godot/assets/538504/86acd39e-3605-481e-85eb-1afe600fe902)

But the constant resizing error goes away.

Since it's unlikely Godot will get modified to support screen rotations natively, I guess our only choice is to handle Suboptimal as a valid result. I'll do a PR and we can verify if it fixes the error.

**Comment by roalyr** [comment] 2024-02-15 13:40
A reminder to self to to open (or link to existing) an issue related to mouse handling on Android when dragging sliders and rotation gizmo in 3D view (left-right mouse motion is perceived as up-down and vice versa). Might also be related to poor orientation handling.

**Comment by m4gr3d** [comment] 2024-02-15 15:51
> So my suspicion was right.
> 
> Godot does not handle screen rotation natively, as it always creates the swap chain with VK_SURFACE_TRANSFORM_IDENTITY_BIT_KHR despite the current transform being different (for example VK_SURFACE_TRANSFORM_ROTATE_90_BIT_KHR on my landscape mode during testing).
> 
> The error goes away if I use the transform that is marked as the current transform, but the screen looks distorted and incorrect.
> 
> ![image](https://private-user-images.githubusercontent.com/538504/305083980-86acd39e-3605-481e-85eb-1afe600fe902.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgwMTIxODQsIm5iZiI6MTcwODAxMTg4NCwicGF0aCI6Ii81Mzg1MDQvMzA1MDgzOTgwLTg2YWNkMzllLTM2MDUtNDgxZS04NWViLTFhZmU2MDBmZTkwMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxNVQxNTQ0NDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jOThiODdhZDVhZmRlZjkwYWYxZDIxNjhjMmVhYjI0NGIyNDZjNmYwMTA5OGFhZDk0YzVhODg0MDgxNGZiMGQ5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.jpzeAnQCk93ME5uN9Ie8pkVTckCmy1vTx7eeoAb9O5Q)
> 
> But the constant resizing error goes away.
> 
> Since it's unlikely Godot will get modified to support screen rotations natively, I guess our only choice is to handle Suboptimal as a valid result. I'll do a PR and we can verify if it fixes the error. It's not the best solution but at least it'll bring it back to the behavior previous to the commit: it just basically exposed an underlying error that was being suppressed before. Therefore it should be clearly documented in code as well that the behavior is intentional.

@DarioSamo Are we applying this [vulkan Android optimization tip](https://developer.android.com/ndk/guides/graphics/design-notes#apply), I wonder if that's the cause of the issue you're seeing when applying the current transform.

**Closed** 2024-02-16 23:28 UTC
Labels: bug, platform:android, topic:rendering, regression
