### ISSUE TITLE
executable created by godot executes the scene of another project

### ISSUE THREAD

**Issue by argento2** [godotengine/godot#39006] opened 2020-05-24 09:28 UTC
**Godot version:**
Godot_v3.2.2-beta3_x11.64

**OS/device including version:**
Fedora linux 31

**Issue description:**
I created a small Godot project that opens and shows the content in the UI of a godot .pck file.

I exported this project in a single .exe file (eg: package_viewer.exe) and I put this .exe file in another Godot project.

My intention was to use the package_viewer.exe to see the contents of the packages of the other project.

But, when I execute package_viewer.exe from the command line, a scene from the other project is executed instead (I know it cause I see some errors from the other project in the shell and the title of the window that is opened is from the other project too).

package_viewer.exe does NOT use ProjectSettings.load_resource_pack(path_to_pack) to load the .pck file but it uses file.open(path_to_pack) and then reads it as a binary file.

**Steps to reproduce:**
1- Create 2 godot projects: project_1 and project_2
2- export the project_1 to project_1.exe
3- put project_1.exe in the project_2 folder
4- execute project_1.exe and a scene of project_2 will be partly executed.

**Minimal reproduction project:**

**Comment by argento2** [comment] 2020-05-24 09:37
If I remove or rename the file project.godot from the project_2 folder then project_1.exe executes normally

**Comment by Zireael07** [comment] 2020-05-24 10:15
This is a duplicate of at least one existing issue.
Basically the way Godot built projects work is by having a Godot executable, which then opens the scene in the folder it is in, or the built-in pck. (That's why, if you put a project in a folder with other projects, it'll likely open project manager window instead of the project you wanted it to, or some other scene)
There is an open PR to make it prefer built-in pck, IIRC? But that's not done yet.

**Comment by Calinou** [comment] 2020-05-24 11:53
Duplicate of #37568, which has since been resolved (the fix is in 3.2.2 betas).

**Closed by Calinou** 2020-05-24 11:53 UTC
