### ISSUE TITLE
Vulkan: Projector property in SpotLight3D does not work properly

### ISSUE THREAD

**Issue by golddotasksquestions** [godotengine/godot#57695] opened 2022-02-06 05:28 UTC
### Godot version

v4.0.alpha1.official [31a7ddbf8]

### System information

Win64 bit, Nvidea765M, Vulkan

### Issue description

![image](https://user-images.githubusercontent.com/47016402/152668781-309fa4f9-2121-4074-a958-1678fceb947d.png)

With a Projector Texture assigned, the Lights Energy property needs to be cranked up to crazy amounts to even make the texture show up at all. When the texture does finally show up, it is not resized to fit the light angle (beam on the surface). Instead the texture is distorted and only a small, seemingly arbitrary region is shown. (see below test texture for the arrow marked region)

### Steps to reproduce

Add a SpotLight3D, enable shadow and add a Projection texture.
Use this texture to easily find the cropped area of the texture:
![flashlight_beam_test](https://user-images.githubusercontent.com/47016402/152668843-7740cfe5-7cd7-4dbe-8560-5f28ea98ba40.png)

**Comment by Calinou** [comment] 2022-02-06 11:45
I can confirm the part about the incorrect texture mapping for SpotLight3D projectors. The OmniLight3D projector mapping looks fine to me, as it expects a 360° panorama texture (similar to sky HDRIs).

> With a Projector Texture assigned, the Lights Energy property needs to be cranked up to crazy amounts to even make the texture show up at all.

I can't reproduce this on `master` 9d1626b4d. The projector texture acts as a *multiplier*, which means it will always darken the actual light unless the projectore texture has overbright colors (with the EXR or HDR image formats).

**Minimal reproduction project:** [test_projector.zip](https://github.com/godotengine/godot/files/8010079/test_projector.zip)

PS: Please upload a minimal reproduction project directly in the future to rule out any potential import setting issues :slightly_smiling_face: 

### OmniLight3D

### Projector disabled

![2022-02-06_12 41 47](https://user-images.githubusercontent.com/180032/152679214-7325a508-3bd8-4a7e-b536-e8ccd89cfb85.png)

### Projector enabled

![2022-02-06_12 41 58](https://user-images.githubusercontent.com/180032/152679218-bde18aee-3e10-4bf4-b5c7-0a8b962062bb.png)

### SpotLight3D

### Projector disabled

![2022-02-06_12 42 39](https://user-images.githubusercontent.com/180032/152679272-1fda6223-6195-4fd4-9b0e-c5b5e1cd79c5.png)

### Projector enabled

*The mapping is incorrect, but if you look at the bright pixels, they have roughly the same brightness as when a projector texture is not used.*

![2022-02-06_12 43 02](https://user-images.githubusercontent.com/180032/152679277-0d34dfbf-a648-4074-b149-530db33d09d7.png)

**Comment by dusakus** [comment] 2022-02-09 15:07
Isn't this the same exact problem I described and "kinda solved" in #50445 ?
I checked, and the same source modification still works.

**Comment by akien-mga** [comment] 2022-02-09 15:23
@dusakus The easier workflow for us would be for you to make a Pull Request with your proposed change, so that it can be reviewed and eventually merged.

**Comment by Calinou** [comment] 2022-02-10 00:23
Duplicate of https://github.com/godotengine/godot/issues/50445.

**Closed by Calinou** 2022-02-10 00:23 UTC
Labels: bug, topic:rendering, confirmed, topic:3d
