### ISSUE TITLE
Circle and Capsule CollisionShape2D aren't drawn in 3.0

### ISSUE THREAD

**Issue by NoGodDamnName** [godotengine/godot#9025] opened 2017-06-02 17:42 UTC
Currently, in 3.0 the bounding boxes for CollisionShape2D's Circle and Capsule aren't drawn anymore, but the handles are still there. Thought i could drop this minor issue.
![s01](https://cloud.githubusercontent.com/assets/28677151/26737592/bc5dfda6-4798-11e7-965f-880382020f6c.jpg)

I'm running Manjaro Linux if it helps.

**Comment by bojidar-bg** [comment] 2017-06-02 19:26
Duplicate of #8033.

**Closed by bojidar-bg** 2017-06-02 19:26 UTC
