### ISSUE TITLE
Collision detection hangs with 4.0

### ISSUE THREAD

**Issue by peastman** [godotengine/godot#62689] opened 2022-07-03 22:51 UTC
### Godot version

e16242b73ba723f58db01fe48dafecf994a27f33

### System information

MacOS 12.4, AMD Radeon R9 M370X, Vulkan

### Issue description

The attached project demonstrates a problem using the latest 4.0 code.  It contains a simple room consisting of a plane for the floor and four boxes for walls.  A few objects (some spheres and a capsule) are supposed to fall into it from above and bounce.  At first they fall normally, but when they reach the floor the process hangs and needs to be force quit.

### Steps to reproduce

Play the attached scene.

### Minimal reproduction project

[gd4test.zip](https://github.com/godotengine/godot/files/9035610/gd4test.zip)

**Comment by squidink7** [comment] 2022-07-16 02:37
This is because you generated collision shapes for the spheres and capsule rather than using the inbuilt sphere shape and capsule shape. This caused the engine to generate many many polygons per sphere to create the round shape rather than the technique used when it's manually assigned a sphere shape. It would be good if the engine could detect these spherical shapes and assign them the proper collision shape rather than creating very detailed convex polygons as it does now, however I imagine this would be complicated to detect on models that consist of more than basic shapes, and its usefulness may be limited.

**Comment by Zireael07** [comment] 2022-07-16 08:53
duplicate of #48587 then

**Comment by Calinou** [comment] 2022-07-16 15:57
Duplicate of https://github.com/godotengine/godot/issues/48587.

**Closed by Calinou** 2022-07-16 15:57 UTC
Labels: bug, topic:physics, topic:3d

**Comment by peastman** [comment] 2022-07-17 20:30
Thanks!  That makes sense.  It would be great if it could automatically select appropriate shapes.  I naively assumed that since I created the mesh with "New SphereMesh", I would automatically get an efficient collision shape from "Create Single Convex Collision Sibling".  But if it internally represents all meshes with the same class, I can see why that would be hard to implement.
