### ISSUE TITLE
AnimationPlayer: Add animation name to "finished" signal

### ISSUE THREAD

**Issue by williamd1k0** [godotengine/godot#7444] opened 2017-01-06 04:14 UTC
**Operating system or device - Godot version:**
Godot c798ff1

**Issue description** (what happened, and what was expected):

The `finished` signal needs the current animation name as argument like `animation_started(String name)`.

Now:
```gdscript
func _on_AnimationPlayer_finished():
	if get_node("path/to/AnimationPlayer").get_current_animation() == 'explode':
		emit_signal('explode')
```

With animation name:
```gdscript
func _on_AnimationPlayer_finished(current_animation):
	if current_animation == 'explode':
		emit_signal('explode')
```

**Comment by akien-mga** [comment] 2017-01-06 07:49
I think this was done a few months ago, then reverted as it broke compatibility. @reduz Maybe something to reconsider for 3.0?

**Comment by bebae** [comment] 2017-01-06 10:24
An additional signal would probably be better, because `finished` indicates that the animation player finished playing any animation.

`signal animation_finished(String name)` which gets emitted every time an animation finished.

And the documentation for `finished` is also wrong, it says "Notifies when an animation finished playing", but as said it only notifies if the animation player finished a non loop animation and no other animation is queued.

And if we want to break compatibility we could set the current_animation to "", when finished gets emitted, shouldn't have any use with the new signal animation_finished and would allow to use:
```
if anim_player.get_current_animation() != "jump":
	anim_player.play("jump")
```
instead of:
```
if anim_player.get_current_animation() != "jump" AND anim_player.is_playing():
	anim_player.play("jump")
```

**Comment by williamd1k0** [comment] 2017-01-07 00:56
@akien-mga Oh, I see! I think implementing it in 3.0 is a good one.

**Comment by razvanc-r** [comment] 2017-01-30 16:40
I'm here just because this issue was referenced from my other one :).

@bebae why would you have to `finished` signals? It doesn't make any sense. You can only play/finish one animation at a time.

**Comment by bebae** [comment] 2017-01-30 17:10
@razvanc-r Currently as it is `finished` gets emitted when the animation player finish an animation and no other animation is queued. So currently it is a signal that indicates that the AnimationPlayer is finished and has nothing to do with a specific animation. At least that is how it behaves, the documentation is different.

But if we want a signal that also returns the animation name it should be named `signal animation_finished(String name)`, because all other signals which return the animation are named `animation...`

I don't really care about the `finished`signal but it probably could still be useful if you have some oneshots with randomized animations and you only care about when the animation player is finished, but this could also be done with `animation_finished` i guess.

**Comment by dodgyville** [comment] 2017-11-23 06:17
The method in animation_finished signal is called with 1 argument but it doesn't appear to contain the name of the finished animation, theAnimPlayer.get_current_animation() is also empty at this point. This is in the current tip of godot 3.

**Comment by dodgyville** [comment] 2018-03-30 03:54
Ah, this still happens! `anim_name` is empty for `animation_finished` signals

**Comment by bojidar-bg** [comment] 2018-03-31 06:48
Try using assigned_animation instead of current_animation. In 3.0, current_animation becomes `""` when the animation player is no longer playing.

**Comment by akien-mga** [comment] 2018-04-03 09:20
This issue is fixed in 3.0, the `animation_finished` signal comes with the animation name as argument, and it works fine in this example: 
[anim_finished.zip](https://github.com/godotengine/godot/files/1870894/anim_finished.zip)

If you found a situation where it doesn't work as intended, please open a new issue with detailed steps to reproduce and an example project.

**Closed by akien-mga** 2018-04-03 09:20 UTC
Labels: enhancement, topic:core

**Comment by jordanlis** [comment] 2020-09-06 09:38
Hello, this still seems to not work properly... I connected an animation_finished to a function, but this function is never called.. when I print current_animation, I get nothing...

**Comment by Calinou** [comment] 2020-09-06 13:00
@jordanlis Please open a new issue with a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) attached.
