### ISSUE TITLE
Memory Leak from Toggling MeshInstance Visibility

### ISSUE THREAD

**Issue by qdeanc** [godotengine/godot#57555] opened 2022-02-02 17:31 UTC
### Godot version

3.4.2.stable

### System information

Windows 10, GLES3, Intel Core i7, RTX 2070 Super

### Issue description

Toggling the visibility of a MeshInstance causes a permanent increase in Static Memory usage:

+Removing the MeshInstace from memory does not lower the Static Memory usage.
+Toggling the MeshInstance scale between (0,0,0) and (1,1,1) causes same issue.
+Translating the MeshInstance in and out of the camera view frustum causes same issue.
+Toggling MeshInstance visibility every 200ms instead of every frame causes same issue.

![image](https://user-images.githubusercontent.com/80287313/152204062-cfa538fa-d681-43c5-b250-1db36dbcad6c.png)

### Steps to reproduce

I've added a minimal reproduction project
Here is the script that toggles the visibility of each MeshInstance (called chunk):
![image](https://user-images.githubusercontent.com/80287313/152205676-ea129348-7323-4fa0-ad84-e6949ed9d54e.png)

### Minimal reproduction project

[Mesh_Instance_Memory_Leak.zip](https://github.com/godotengine/godot/files/7988658/Mesh_Instance_Memory_Leak.zip)

**Comment by Calinou** [comment] 2022-02-02 17:36
@qdeanc Can you reproduce this if you disable the BVH in the Project Settings?

cc @lawnjelly

**Comment by qdeanc** [comment] 2022-02-02 17:41
Disabling "Use Bvh" in the project's Rendering settings fixes the issue!
Changing to GLES2 has no effect.

**Comment by AnidemDex** [comment] 2022-02-02 18:03
Played with the reproduction project, the error is the same as the issue. The issue is gone if I didn't apply mesh to the node, or use an empty/not generated by code mesh.

**Comment by lawnjelly** [comment] 2022-02-02 18:48
Ah that doesn't sound good.
I'm just having a look now. :+1:

**Comment by qdeanc** [comment] 2022-02-02 19:50
Thank you!! :D

**Comment by akien-mga** [comment] 2022-02-03 08:57
Fixed by #57561.

**Closed by akien-mga** 2022-02-03 08:57 UTC
Labels: bug, topic:rendering, topic:3d
