### ISSUE TITLE
Static typing doesn't doesn't recognise class_type properly for purpose of Auto-completion

### ISSUE THREAD

**Issue by MaciejGorczycaGD** [godotengine/godot#27349] opened 2019-03-23 15:16 UTC
**Godot version:**
3.1 Steam

**OS/device including version:**
Windows 10

**Issue description:**
When I use class_name to create a class for Enemy engine doesn't recognised build in functions of it's parent for purpose of auto-completion 

My Enemy is:

extends KinematicBody2D
class_name Enemy

However when I later try to do 

func update(host: Enemy, delta):
	var collision = host.move_and_collide(host.velocity * delta)

auto completion is not working as intended. I can type 

host.

and any function I have created will be completed 

but if I type host.move_and it will not auto-complete to move_and_slide when typed by hand it will work fine but auto-completion is not recognising it. 

**Steps to reproduce:**

Call a class from other script and try to type any of parent class functions

**Minimal reproduction project:**

Go open scene enemy "res://Characters/Enemies/Enemy.tscn" container open script "res://Characters/Enemies/States/Calm.gd"  and under function func update(host: Enemy, delta): try to type host. and then any of KinematicBody2d methods and you will see autocomplition not working. 

Then try typing host. and any of enemy.gd methods and you will see all of them working. 

[First Game - Copy.zip](https://github.com/godotengine/godot/files/2999502/First.Game.-.Copy.zip)

**Comment by NetroScript** [comment] 2019-03-23 23:36
Probably the same issue as https://github.com/godotengine/godot/issues/27152

**Comment by Calinou** [comment] 2019-03-29 17:11
Duplicate of #27152.

**Closed by Calinou** 2019-03-29 17:11 UTC
