### ISSUE TITLE
Appending array to itself causes crash without any errors

### ISSUE THREAD

**Issue by aomimezura** [godotengine/godot#28089] opened 2019-04-16 17:41 UTC
**Godot version:**

3.1

**OS/device including version:**

Ubuntu 14.04

**Issue description:**

If you append an array to itself, the game crashes without showing any errors or printing any text before the append is done making debugging the crash extremely difficult.

**Steps to reproduce:**
Create array. Next, print something. Then append the array to itself. Run. You will see the game crash WITHOUT the print working and you get no error messages.
[SelfReferenceBug.zip](https://github.com/godotengine/godot/files/3086176/SelfReferenceBug.zip)

**Minimal reproduction project:**

**Comment by Zireael07** [comment] 2019-04-16 17:56
I believe it's a dupe of an existing issue, but I can't find it atm.

**Comment by qarmin** [comment] 2019-04-16 18:05
This happens because Variant::operator String call self recursively.
![Zrzut ekranu z 2019-04-16 20-03-16](https://user-images.githubusercontent.com/41945903/56233184-d958c800-6082-11e9-87c3-d58519dd6de6.png)

**Comment by aomimezura** [comment] 2019-04-16 19:39
I understand WHY it happens, just not why it doesn't tell you it's an error. It was a difficult bug to track down in my code because of it.

**Comment by groud** [comment] 2019-04-17 07:17
> I understand WHY it happens, just not why it doesn't tell you it's an error.

I think @qarmin's message was not addressed to you specifically, but to anyone who wanted to work on this issue.

But yeah, the engine should raise an error.

**Comment by akien-mga** [comment] 2019-04-17 08:15
Related to #1289.

**Closed** 2019-04-20 21:46 UTC
Labels: bug, topic:gdscript
