### ISSUE TITLE
Positioning issues with 2D lighting on ParallaxBackground

### ISSUE THREAD

**Issue by NewDefectus** [godotengine/godot#73138] opened 2023-02-12 01:15 UTC
### Godot version

4.0.rc1

### System information

Windows 10, Vulkan, Nvidia GeForce GTX 1050

### Issue description

When placing a PointLight2D in front of a ParallaxBackground node and setting the light's minimum layer to be -100 (so that it also lights the background), the apparent position of the light on the background is sometimes extremely off. For instance, in the attached project, this is how the light "should" look (this is how it appears in the editor):
![image](https://user-images.githubusercontent.com/36775845/218287741-76c5514c-473a-44b2-bcc6-de53d438f78e.png)
And this is how it appears when running the project (note this only occurs when a Camera2D object is added):
![image](https://user-images.githubusercontent.com/36775845/218287757-c4bb9523-71f8-4d71-8b88-46146422d98c.png)
The large Godot icon in the background is a sprite in a ParallaxLayer, whereas the smaller icon in the foreground is simply a sprite. Notice that the lighting appears correctly positioned for the sprite, but misplaced for the background.

### Steps to reproduce

Run the minimal reproduction project.

### Minimal reproduction project

[ParallaxLightTest.zip](https://github.com/godotengine/godot/files/10715051/ParallaxLightTest.zip)

**Comment by kleonc** [comment] 2023-02-12 13:22
Duplicate of #63101.

**Closed by kleonc** 2023-02-12 13:22 UTC
