### ISSUE TITLE
Useless warnings in AnimationMixer about Value Track Interpolation Type

### ISSUE THREAD

**Issue by madokadev** [godotengine/godot#85781] opened 2023-12-05 13:00 UTC
### Tested versions

Reproducible in 4.2.stable, not reproducible in 4.1.stable. Renderer type doesn't matter.

### System information

Godot v4.2.stable - Windows 10.0.22621 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3070 (NVIDIA; 31.0.15.3758) - AMD Ryzen 7 5800 8-Core Processor (16 Threads)

### Issue description

When the interpolation type ofa track in the RESET animation is a non-angle version, and that same track in any other animation is an angle interpolation, the engine will show the warning: 
W <TIMESTAMP>   _update_caches: AnimationMixer: 'new_animation', Value Track: 'Track:Subtrack' has different interpolation types for rotation between some animations which may be blended together. Blending prioritizes angle interpolation, so the blending result uses the shortest path referenced to the initial (RESET animation) value.
  <C++ Source>   scene/animation/animation_mixer.cpp:892 @ _update_caches()

This will only show for the first animation track where this happens, even across multiple scenes. The thing that the engine warns about is not a problem whatsoever. This warning will happen very often since the reset tracks always have the interpolation type 'linear' when created. So changing any track to 'linear angle' will trigger this warning.

I assume that there's something more going on, with the warning only showing once, though I just want it gone.

### Steps to reproduce

Create an AnimationPlayer.
Create a Sprite2D.
Animate the Sprite2D, including a rotation, ensuring that you make a RESET track.
Turn the interpolation type into 'linear angle'.

### Minimal reproduction project (MRP)

[AnimationMixerWarning.zip](https://github.com/godotengine/godot/files/13560273/AnimationMixerWarning.zip)

**Comment by TokageItLab** [comment] 2023-12-05 17:36
Dupe of https://github.com/godotengine/godot/issues/83545

**Closed by TokageItLab** 2023-12-05 17:36 UTC

**Comment by hsandt** [comment] 2024-01-11 20:07
Sounds like two different issues to me.

This is about the RESET track using a different Interpolation type, but we don't care (in general we just have a unique value to reset to, and interpolation doesn't matter - maybe the new Animation Tree can do smooth transitions between animations, but I suspect that in the case of RESET it's just instantaneous anyway).

Whereas #83545 is about an incorrect warning (on the screenshot I see the Discord interpolation icon, so it's not using UpdateMode.UPDATE_CONTINUOUS).

In addition, if we really want RESET interpolation to match the mode of other tracks, I'd recommend that when auto-creating a RESET track (using right-click menu or when adding a new track and prompted to add matching RESET track), we copy the same Interpolation mode to the RESET track (but when just adding a new track, dev had no time to set said mode, so it may not be very relevant...). I could open a proposal for this, but if it doesn't matter and the warnings are removed, it won't be that much useful. So I need to know if this issue will be recognised as a valid unique issue.

If this issue is recognised as its own issue specifically for RESET, then we can also rename it to include "RESET" to make it easier for other devs to find in the list.

**Comment by jinyangcruise** [comment] 2025-06-25 10:17
Encounter this too for a long time. Reproducible in v4.5.beta1, v4.5.dev1,2,3,4,5.
The values are all float so I don't know why they are recognized as different types.

![Image](https://github.com/user-attachments/assets/aadd891f-0d18-4baa-8bf5-9dc5d0761913)

![Image](https://github.com/user-attachments/assets/0bd0f3ca-2f66-4723-b171-7a90b2b4bb2e)
