### ISSUE TITLE
AnimationTree crashing beta 15

### ISSUE THREAD

**Issue by oxixxixo** [godotengine/godot#72076] opened 2023-01-25 21:21 UTC
### Godot version

Godot 4.0 beta 15

### System information

Windows 10

### Issue description

The engine crashes as a result of various interactions with the animationtree node.

### Steps to reproduce

Start a new project, make animationplayer and animationtree children of root node, set the animationtree's 'anim player' to be the animationplayer without touching the 'tree root' property. Can also be achieved by setting the 'tree root' and then removing it while keeping the 'anim player'. It also seems that adding the animationtree before an animationplayer also produces a crash.

### Minimal reproduction project

n/a

**Comment by Calinou** [comment] 2023-01-25 21:24
Can you reproduce this in 4.0.beta14 or older betas?

**Comment by oxixxixo** [comment] 2023-01-25 21:32
just tested in beta 14 with no issues

**Comment by robertomorrison0** [comment] 2023-01-25 22:23
Reproduced the problem on Arch Linux (6.1.7-arch1-1) (glibc version 2.36-7 ) 

```
handle_crash: Program crashed with signal 11
Engine version: Godot Engine v4.0.beta15.official (4fa6edc888cfacd5346bf08afa14b5f5a9bd6d0c)
Dumping the backtrace. Please include this when reporting the bug to the project developer.
[1] /usr/lib/libc.so.6(+0x389e0) [0x7f0e59b419e0] (??:0)
[2] /home/simon/Downloads/GodotEngine/Godot_v4.0-beta15_linux.x86_64() [0x212887d] (??:0)
[3] /home/simon/Downloads/GodotEngine/Godot_v4.0-beta15_linux.x86_64() [0x2129685] (??:0)
[4] /home/simon/Downloads/GodotEngine/Godot_v4.0-beta15_linux.x86_64() [0x1c7159e] (??:0)
[5] /home/simon/Downloads/GodotEngine/Godot_v4.0-beta15_linux.x86_64() [0x1c7b612] (??:0)
[6] /home/simon/Downloads/GodotEngine/Godot_v4.0-beta15_linux.x86_64() [0x1f2890f] (??:0)
[7] /home/simon/Downloads/GodotEngine/Godot_v4.0-beta15_linux.x86_64() [0x1f28a63] (??:0)
[8] /home/simon/Downloads/GodotEngine/Godot_v4.0-beta15_linux.x86_64() [0x2b15ccd] (??:0)
[9] /home/simon/Downloads/GodotEngine/Godot_v4.0-beta15_linux.x86_64() [0x2b74102] (??:0)
[10] /home/simon/Downloads/GodotEngine/Godot_v4.0-beta15_linux.x86_64() [0x2b749fa] (??:0)
[11] /home/simon/Downloads/GodotEngine/Godot_v4.0-beta15_linux.x86_64() [0x2b909a5] (??:0)
[12] /home/simon/Downloads/GodotEngine/Godot_v4.0-beta15_linux.x86_64() [0xe62934] (??:0)
[13] /home/simon/Downloads/GodotEngine/Godot_v4.0-beta15_linux.x86_64() [0x42ba644] (??:0)
[14] /home/simon/Downloads/GodotEngine/Godot_v4.0-beta15_linux.x86_64() [0x42bb4c5] (??:0)
[15] /home/simon/Downloads/GodotEngine/Godot_v4.0-beta15_linux.x86_64() [0xe6434d] (??:0)
[16] /home/simon/Downloads/GodotEngine/Godot_v4.0-beta15_linux.x86_64() [0xdd74e2] (??:0)
[17] /usr/lib/libc.so.6(+0x23290) [0x7f0e59b2c290] (??:0)
[18] /usr/lib/libc.so.6(__libc_start_main+0x8a) [0x7f0e59b2c34a] (??:0)
[19] /home/simon/Downloads/GodotEngine/Godot_v4.0-beta15_linux.x86_64() [0xdf757e] (??:0)
```

**Comment by akien-mga** [comment] 2023-01-26 00:15
CC @godotengine/animation

**Comment by akien-mga** [comment] 2023-01-26 00:24
Possibly a duplicate of #72044?

**Comment by TokageItLab** [comment] 2023-01-26 06:19
I think so.

**Comment by Flynsarmy** [comment] 2023-01-26 06:50
I had this same issue. Compiled from source and no more crashing. I believe this is a dup.

**Closed** 2023-01-26 07:40 UTC
Labels: bug, topic:editor, needs testing, crash, regression, topic:animation
