### ISSUE TITLE
Godot freezes whole computer if i set the MSAA level to 16x

### ISSUE THREAD

**Issue by mbrlabs** [godotengine/godot#44426] opened 2020-12-16 13:51 UTC
**Godot version:**
92d4deedaa542e9458845fdf2b2a44fedd19fde8 master

**OS/device including version:**
Windows 10, GeForce RTX 2060/PCIe/SSE2

**Issue description:**
If i set the MSAA level to 16x in the projects settings, my computer becomes immediately unresponsive. I have to force reboot. If i reopen the project after the reboot it immediately does the same thing after selecting the project. I have to manually remove the setting in the `project.godot`. All other MSAA levels work fine.

Unfortunally i can't provide error messages, because of the immediate freeze.

**Comment by Calinou** [comment] 2020-12-16 13:54
Duplicate of https://github.com/godotengine/godot/issues/37917.

**Closed by Calinou** 2020-12-16 13:54 UTC
