### ISSUE TITLE
Different shader file name or node name lengths resize the editor dock/viewport

### ISSUE THREAD

**Issue by capnm** [godotengine/godot#34535] opened 2019-12-22 06:45 UTC
**Godot version:**
Known broken 3.2.beta4, current tip,
worked in 3.1.1

**OS/device including version:**
Linux, Ubuntu 18.04.3 LTS
**Issue description:**
![Screenshot from 2019-12-22 07-34-25](https://user-images.githubusercontent.com/4047289/71318161-a37ba700-248d-11ea-9cff-0e18acc2d2fd.png)

![Screenshot from 2019-12-22 07-34-28](https://user-images.githubusercontent.com/4047289/71318163-a8d8f180-248d-11ea-8098-4c733d7a4980.png)

![Screenshot from 2019-12-22 08-04-59](https://user-images.githubusercontent.com/4047289/71318526-4b936f00-2492-11ea-9923-be38c481ac5f.png)

![Screenshot from 2019-12-22 08-05-01](https://user-images.githubusercontent.com/4047289/71318529-50582300-2492-11ea-8869-edbedf4aee26.png)

**Steps to reproduce:**
Double-click the shaders file name in the fs dock or select a node name in the tree dock.
Who ever implemented this feature, thanks, but I don't like it :-1: 

**Minimal reproduction project:**
[test.zip](https://github.com/godotengine/godot/files/3992196/test.zip)

**Comment by capnm** [comment] 2019-12-22 15:03
It is also annoying by editing gdscript files with the external language server https://github.com/godotengine/godot-vscode-plugin .

**Comment by tom-jk** [comment] 2020-07-24 20:15
Testing on linux mint 18.3

Can reproduce in 3.2.beta4.
Can't reproduce in 3.2.stable, 3.2.2.stable, 3.2.3.beta1.

Appears to be resolved.

**Comment by Calinou** [comment] 2020-07-24 20:21
Closing as resolved per @tom-jk's comment.

**Closed by Calinou** 2020-07-24 20:21 UTC
Labels: bug, regression, topic:editor
