### ISSUE TITLE
Allow export nodes

### ISSUE THREAD

**Issue by Geequlim** [godotengine/godot#17525] opened 2018-03-15 09:48 UTC
Currently if we want to export a node for designer from code. We have to export a NodePath then call `get_node` after `_ready`.

```gdscript
export(NodePath) var path_the_node
onready var node = get_node(path_the_node)
```

Is it possible in the future to export nodes directly like this
```gdscript
export(Label) var level
export(Button) var exit
````

Then we can select the  nodes like we did today with NodePath. Then the exported node should be avaliable before `_ready` just like other `onready` variables.

**Comment by bojidar-bg** [comment] 2018-03-15 11:24
Exact duplicate of #7821

**Closed by bojidar-bg** 2018-03-15 11:24 UTC
Labels: enhancement, topic:gdscript
