### ISSUE TITLE
[4.0] Edited values started to appear in the left bottom corner if you attach or detach the monitor

### ISSUE THREAD

**Issue by Rinocrosser** [godotengine/godot#57279] opened 2022-01-26 23:03 UTC
### Godot version

4.0 Alpha 1

### System information

Windows 10 (dual monitor setup)

### Issue description

Edited values started to appear in the left bottom corner.
Menu items are appearing in wrong places, etc.

The issue appears after I attached the second monitor or detach it while Godot is running.

![image](https://user-images.githubusercontent.com/19660324/151260433-cdde3c1b-31c3-4926-ab0b-9755db8444d3.png)

### Steps to reproduce

1. Make any node that has numeric values
2. Attach or detach the second monitor
3. Try to edit numeric values in the inspector
4. Try to open top menu items of Godot Engine

**Comment by Calinou** [comment] 2022-01-26 23:05
Duplicate of https://github.com/godotengine/godot/issues/45740.

**Closed by Calinou** 2022-01-26 23:05 UTC

**Comment by Rinocrosser** [comment] 2022-01-26 23:22
> Duplicate of #45740.

I've tried to search for it, sorry, haven't seen

**Comment by akien-mga** [comment] 2022-01-26 23:36
No need to apologize, searching through 6000 issues is difficult and it's easy to miss related issues - we find them because we remember seeing them in the past :) It's never wrong to report a bug even if it ends up being a duplicate report.
