### ISSUE TITLE
Vulkan: CSG Geometry are not rendered in editor after restarting with Restore Scenes On Load enabled

### ISSUE THREAD

**Issue by Leakbang** [godotengine/godot#56003] opened 2021-12-16 22:12 UTC
### Godot version

v4.0.dev.calinou [e31138958]

### System information

Linux Kubuntu, Vulkan, NVIDIA GeForce GTX 1050 Ti, Driver Version: 470.63.01

### Issue description

CSG Geometry are not rendered. The outlines are drawn, however, the shapes themselves are not rendered. Running the scene, the CSG geometry would be visible.

![image](https://user-images.githubusercontent.com/51197897/146455725-0bd93715-dd40-4629-8b41-06ae0d7864ce.png)

Switching (not reloading) scenes would also fix the issue.

### Steps to reproduce

- Create scene1 with CSG Geometry. 
- Create scene2. _(Content not important)_
- Instance scene2 into scene 1 _(Not sure if this step is required)_
- With both scenes open, focus on scene2
- Save and exit editor
- Relaunch the editor. _Now both scenes load but scene 2 is open on the screen. Switching to scene 1 via the scene tabs will result in the bug._

**Comment by Calinou** [comment] 2021-12-16 22:45
@Leakbang Can you reproduce this in 3.4?

**Comment by Leakbang** [comment] 2021-12-16 22:50
> @Leakbang Can you reproduce this in 3.4?

In 3.4, only the default scene is opened when opening the editor. Is there a setting to change this setting?

**Comment by Calinou** [comment] 2021-12-16 22:52
> In 3.4, only the default scene is opened when opening the editor. Is there a setting to change this setting?

Yes, enable **Restore Scenes On Load** in the Editor Settings (it's now enabled by default in `master`).

**Comment by Leakbang** [comment] 2021-12-16 22:57
Yes, I encounter the exact same issue in 3.4.

**Comment by Calinou** [comment] 2021-12-16 23:09
Duplicate of https://github.com/godotengine/godot/issues/54445.

**Closed by Calinou** 2021-12-16 23:09 UTC
Labels: bug, topic:core, topic:editor, topic:3d
