### ISSUE TITLE
"make floating" option not work in godot4.1.1

### ISSUE THREAD

**Issue by lowpolyegg** [godotengine/godot#81588] opened 2023-09-12 20:10 UTC
### Godot version

v4.1.1.stable.official [bd6af8e0e]

### System information

windows10

### Issue description

when i clicked "make floating" option in panel tab,userinterface bloken like this.
i want restore this.
it this bug?
![ui_bug2](https://github.com/godotengine/godot/assets/52220817/84e43bb3-bba6-4aea-b061-0ee3bf1ca970)
![ui_bug](https://github.com/godotengine/godot/assets/52220817/3bf82abc-d941-4434-92a0-e63cb86628d7)

### Steps to reproduce

1:making "new project"
2:i clicked "make floating" option in inspecter tab

### Minimal reproduction project

[test.zip](https://github.com/godotengine/godot/files/12590459/test.zip)

**Comment by YuriSizov** [comment] 2023-09-12 20:20
Thanks for the report! This is a duplicate of https://github.com/godotengine/godot/issues/79673 which is fixed already and will be available in future Godot releases. In the meantime, you can disable the single window mode.

**Closed** 2023-09-12 20:20 UTC

**Comment by lowpolyegg** [comment] 2023-09-12 20:46
i understand it. thank you very much for support.
