### ISSUE TITLE
Memory leak when working with audio

### ISSUE THREAD

**Issue by TimurKhan** [godotengine/godot#44527] opened 2020-12-19 18:04 UTC
**OS/device including version:**
Windows 10
OpenGL ES 3.0 Renderer: Intel(R) HD Graphics 5500
Realtek High Definition Audio
Intel Core i7-5500U CPU 2.4GHz
RAM 8 Gb

**Issue description:**
Errors messages after exit:
WARNING: cleanup: ObjectDB instances leaked at exit (run with --verbose for details).
At: core/object.cpp:2135
ERROR: clear: Resources still in use at exit (run with --verbose for details).
At: core/resource.cpp:477

**Steps to reproduce:**
Opening an empty project. 
Add Control Node
Add a bus. 
Add the "Record" effect.
Run project.
Exit.

**Minimal reproduction project:**

[Error.zip](https://github.com/godotengine/godot/files/5719944/Error.zip)

**Comment by Calinou** [comment] 2020-12-19 20:45
Duplicate of https://github.com/godotengine/godot/issues/34495.

**Closed by Calinou** 2020-12-19 20:45 UTC
Labels: bug, topic:audio, topic:editor
