### ISSUE TITLE
NodePath export var value gets reset upon playing scene

### ISSUE THREAD

**Issue by yllennods** [godotengine/godot#43321] opened 2020-11-05 01:24 UTC
**Godot version:**

master (c35517f)

**OS/device including version:**

Windows 10 version 20H2

**Issue description:**

I set up a node with NodePath as an export var, assigned it in the inspector, pressed play, and the NodePath export var value was reset.

**Steps to reproduce:**
Open attached godot project, open Node2D.tscn, and press Play Scene, or:
Create new project.
New scene, make it a 2D scene.
Create/attach a new script to the Node2D in the new scene.
Add line `@export var nodepath : NodePath`.
Set `nodepath` export var in inspector (can be set to itself or add a new Node2D as child and use that instead).
Press Play Scene.

**Minimal reproduction project:**

[test2.zip](https://github.com/godotengine/godot/files/5491305/test2.zip)

**Comment by yllennods** [comment] 2020-11-05 02:00
It works if I use `@export_node_path` instead of `@export`, but I would think it should still work correctly with just `@export`?

**Comment by KoBeWi** [comment] 2020-11-05 10:11
Duplicate of #41690

**Closed by KoBeWi** 2020-11-05 10:11 UTC
