### ISSUE TITLE
Godot Mono External editor setting is broken

### ISSUE THREAD

**Issue by MagnetBoi** [godotengine/godot#72933] opened 2023-02-09 00:37 UTC
### Godot version

4.0

### System information

Windows 11

### Issue description

(4.0 rc1) I opened godot 4 rc1 and when selecting external editor I get a text box with the number 4. Changing the numbers has no impact and putting text reverts to numbers. (I opened a beta 17 project, not sure if it is important)

### Steps to reproduce

-Open godot mono rc1
-Select external editor

### Minimal reproduction project

None

**Comment by raulsntos** [comment] 2023-02-09 00:58
The editor settings were renamed in https://github.com/godotengine/godot/pull/72061.

The setting is still showing up because it is set in `editor_settings-4.tres` (see https://docs.godotengine.org/en/latest/tutorials/io/data_paths.html#editor-data-paths for the path to that file).

There's a proposal about removing obsolete/undefined settings: https://github.com/godotengine/godot-proposals/issues/3526.

**Comment by Calinou** [comment] 2023-02-09 01:08
Duplicate of https://github.com/godotengine/godot-proposals/issues/3526.

**Closed by Calinou** 2023-02-09 01:08 UTC
