### ISSUE TITLE
web FTBFS

### ISSUE THREAD

**Issue by slapin** [godotengine/godot#32868] opened 2019-10-16 13:01 UTC
master branch of yesterday,

```
In file included from modules/websocket/emws_client.cpp:33:
modules/websocket/emws_client.h:53:8: warning: 'EMWSClient::connect_to_host' hides overloaded virtual function [-Woverloaded-virtual]
        Error connect_to_host(String p_host, String p_path, uint16_t p_port, bool p_ssl, const PoolVector<String> p_protocol = PoolVector<String>(), const Dictionary p_custom_headers = Dictionary());
              ^
modules/websocket/websocket_client.h:60:16: note: hidden overloaded virtual function 'WebSocketClient::connect_to_host' declared here: type mismatch at 5th parameter ('const Vector<String>' vs 'const PoolVector<String>')
        virtual Error connect_to_host(String p_host, String p_path, uint16_t p_port, bool p_ssl, const Vector<String> p_protocol = Vector<String>(), const Vector<String> p_custom_headers = Vector<String>()) = 0;
                      ^
In file included from modules/websocket/emws_client.cpp:33:
modules/websocket/emws_client.h:42:11: error: allocating an object of abstract class type 'EMWSClient'
        GDCIIMPL(EMWSClient, WebSocketClient);
                 ^
modules/websocket/websocket_client.h:60:16: note: unimplemented pure virtual method 'connect_to_host' in 'EMWSClient'
        virtual Error connect_to_host(String p_host, String p_path, uint16_t p_port, bool p_ssl, const Vector<String> p_protocol = Vector<String>(), const Vector<String> p_custom_headers = Vector<String>()) = 0;
                      ^
In file included from modules/websocket/emws_server.cpp:33:
modules/websocket/emws_server.h:46:8: warning: 'EMWSServer::listen' hides overloaded virtual function [-Woverloaded-virtual]
        Error listen(int p_port, PoolVector<String> p_protocols = PoolVector<String>(), bool gd_mp_api = false);
              ^
modules/websocket/websocket_server.h:53:16: note: hidden overloaded virtual function 'WebSocketServer::listen' declared here: type mismatch at 2nd parameter ('const Vector<String>' vs 'PoolVector<String>')
        virtual Error listen(int p_port, const Vector<String> p_protocols = Vector<String>(), bool gd_mp_api = false) = 0;
                      ^
In file included from modules/websocket/emws_server.cpp:33:
modules/websocket/emws_server.h:42:11: error: allocating an object of abstract class type 'EMWSServer'
        GDCIIMPL(EMWSServer, WebSocketServer);
                 ^
modules/websocket/websocket_server.h:53:16: note: unimplemented pure virtual method 'listen' in 'EMWSServer'
        virtual Error listen(int p_port, const Vector<String> p_protocols = Vector<String>(), bool gd_mp_api = false) = 0;
```

Emscripten build fails.

**Comment by bojidar-bg** [comment] 2019-10-16 13:07
CC @Faless

**Comment by Calinou** [comment] 2019-10-16 16:17
Duplicate of #32860.

**Closed by Calinou** 2019-10-16 16:17 UTC
Labels: bug, platform:html5, topic:network
