### ISSUE TITLE
Array returning functions return an empty array

### ISSUE THREAD

**Issue by markjoshwel** [godotengine/godot#62451] opened 2022-06-27 10:34 UTC
### Godot version

4.0.alpha10.official (4bbe7f0b9)

### System information

Windows 10

### Issue description

In-editor and debug exports return the correct value, whereas release exports return a empty array.

I have messed around with the minimal reproduction project, and found the following:

- typing the array as `Array[int]` or `Array` will cause the function to return `[]`
- not typing the array will cause the function to return `null` 

---

GDScript:
```gdscript
func array_test() -> Array:
    var a: Array = []
    a.append(2)
    a.append(8)
    a.append(2)
    print("returning a=",a)
    return a


func _ready() -> void:
    print("ready")
    print(array_test())
```

Expected:
```text
ready
returning a=[2, 8, 2]
[2, 8, 2]
```

Output (Editor):
![emptyarray-editor](https://user-images.githubusercontent.com/89562141/175921619-f504de83-301e-450a-8785-f403c932e458.png)

Output (Debug):
![emptyarray-debug](https://user-images.githubusercontent.com/89562141/175921660-89a1a6c4-a9d3-4c6e-82c3-792633051247.png)

Output (Release):
![emptyarray-release](https://user-images.githubusercontent.com/89562141/175921750-faa2c5fd-2094-4f83-8c41-ee4ac78772a8.png)

export_presets.cfg:
```
[preset.0]

name="Windows Desktop"
platform="Windows Desktop"
runnable=true
custom_features=""
export_filter="all_resources"
include_filter=""
exclude_filter=""
export_path="./emptyarray.exe"
encryption_include_filters=""
encryption_exclude_filters=""
encrypt_pck=false
encrypt_directory=false
script_export_mode=1
script_encryption_key=""

[preset.0.options]

custom_template/debug=""
custom_template/release=""
debug/export_console_script=2
binary_format/64_bits=true
binary_format/embed_pck=false
texture_format/bptc=false
texture_format/s3tc=true
texture_format/etc=false
texture_format/etc2=false
texture_format/no_bptc_fallbacks=true
codesign/enable=false
codesign/identity_type=0
codesign/identity=""
codesign/password=""
codesign/timestamp=true
codesign/timestamp_server_url=""
codesign/digest_algorithm=1
codesign/description=""
codesign/custom_options=PackedStringArray()
application/modify_resources=true
application/icon=""
application/file_version=""
application/product_version=""
application/company_name=""
application/product_name=""
application/file_description=""
application/copyright=""
application/trademarks=""
```

### Steps to reproduce

1. Open project
2. Export debug project
3. Run debug project

   See following in console (expected):
   ```text
   ready
   returning a=[2, 8, 2]
   [2, 8, 2]
   ```
4. Export release project
5. Run release project

   See following in console (unexpected):
   ```
   ready
   returning a=[2, 8, 2]
   []
   ```

### Minimal reproduction project

[EmptyArrayMRP.zip](https://github.com/godotengine/godot/files/8991117/EmptyArrayMRP.zip)

**Comment by akien-mga** [comment] 2022-06-27 11:37
Duplicate of #59239.

**Closed by akien-mga** 2022-06-27 11:37 UTC
