### ISSUE TITLE
Oren Nayar causes Visual Artifacts

### ISSUE THREAD

**Issue by Cygon** [godotengine/godot#16440] opened 2018-02-06 08:18 UTC
**Godot version:** 3.0-stable, custom build from 9bd402698cfa299b79b9144f8d7744c308a4e085
**OS/device including version:** Gentoo Linux 4.9.72, KDE Plasma 5.10.5
**GPU model and drivers:** NVidia GTX 1080 w/proprietary drivers 387.22

**Issue description:**
The `Oren Nayar` diffuse mode negatively interacts with several other rendering techniques and causes heavy visual artifacts.

Having a Subsurface material (example: rug) near an Oren Nayar material (example: stone floor) results in black vertical bars:
![Vertical Bars on Subsurface Materials](https://user-images.githubusercontent.com/3613175/35848126-3a5cfae8-0b1d-11e8-9413-a3ec07537443.jpg)

Using the *Glow* post-processing effect when an Oren Nayar material is present in the scene will result in flickering squares appearing on it:
![Flickering Blocks on Oren Nayar Material](https://user-images.githubusercontent.com/3613175/35848260-c30bc90a-0b1d-11e8-89d6-4d2115548323.jpg)

Reflection probes appear to be working fine initially, but if a reflection probe's origin is moved out-of-center, it generates black noise:
![Black Noise from Off-Center Reflection Probe](https://user-images.githubusercontent.com/3613175/35848376-3ce4173c-0b1e-11e8-9e56-025a4338b7a7.jpg)

This gets way worse when two off-center reflection probes overlap. In this case, the entire covered volume can turn pitch black:
![Black Walls from Reflection Probe](https://user-images.githubusercontent.com/3613175/35848360-2c15b262-0b1e-11e8-862c-dfc479714062.jpg)

**Steps to reproduce:**
1. Create a material using the `Oren Nayar` diffuse mode (mine has Albedo, Roughness 0.75, Normals)
2. Put it on a room or other mesh
3. Recreate the situations described above (place an object using a subsurface scattering material near it, enable the *Glow* effect or use reflection probes in its vicinity)

**Comment by Chaosus** [comment] 2018-02-15 15:11
@Cygon Could you upload a demo project ?

**Comment by Cygon** [comment] 2018-02-16 20:49
I can reproduce these issues with a small room of Oren Nayar materials + a subsurface material box in it, but the strongest I've seen them so far are in a for-fun project where I tried to see what the Bethesda game "Skyrim" would look like if rendered with PBR materials in Godot (also used in the screenshots above).

I'll provide the project, trimmed down to a single room, for debugging purposes, but do note that the assets are copyrighted :-)

[OrenNayarArtifactsReproduction.7z](http://blog.nuclex-games.com/OrenNayarArtifactsReproduction.7z) (71.5 MiB)

Upon opening the project (and waiting for the `.import` directory to be rebuilt), one half of the room should immediately turn pitch black, reproducing the effect seen in the lastmost screenshot. Disabling the reflection probes will remove the black noise. Moving the camera near the carpets will show the noise pattern happening on subsurface materials. Enabling the 'Glow' effect in the `WorldEnvironment` will reveal the flickering squares.

**Comment by Chaosus** [comment] 2018-02-17 07:40
I found the source of this problem
https://github.com/godotengine/godot/blob/6dba6bb40a90666e379d0bc17f9f105af072d633/drivers/gles3/shaders/scene.glsl#L982

if I set sigma2 to zero the problem is dissappear, 

![image](https://user-images.githubusercontent.com/3036176/36339084-c0d4ec02-13ce-11e8-80ce-88ec74ac8c91.png)

But I guess the roughness should be taken to account, need to be checked by @reduz

**Comment by reduz** [comment] 2018-11-15 00:43
This seems to have been fixed at some point because I can't reproduce the problem. Closing.

**Closed by reduz** 2018-11-15 00:43 UTC
Labels: bug, topic:rendering
