### ISSUE TITLE
AnimationPlayer Sprite:frame weird behavior

### ISSUE THREAD

**Issue by Dillybob92** [godotengine/godot#6697] opened 2016-10-04 07:29 UTC
**Operating system or device - Godot version:**
2.1 stable

**Issue description** (what happened, and what was expected):
Animating spritesheets is becoming a real pain in the ass. I have no idea what is going with the AnimationPlayer anymore :(

Take this spritesheet for example:

![normal-punch](https://cloud.githubusercontent.com/assets/10387670/19065318/bbfc23d6-89c7-11e6-82ce-aad34f40ad9f.png)

5 frames.

Steps to reproduce:
- Add a Sprite and AnimationPlayer node 
- Change Sprites texture to the above sprite
- Create a new animation, name it "puncher"
- Set the animation length to 0.3
- Set the Sprite's `VFrames` to `1`, and `HFrames` to `5`
- Insert a keyframe at 0 seconds for the first `frame` (`0`)
- Now, go to the last time in the timeline (0.3seconds) and insert a new keyframe for `frame`. The last fame is index `4` (0,1,2,3,4) = 5 frames. 
- It will show the punching sprite with the label "5"
- Now on the animation track, set the animation mode to `Continuous`. So it looks something like this:

![image](https://cloud.githubusercontent.com/assets/10387670/19065508/d16db544-89c8-11e6-98d3-9eabede519c1.png)

Now, start to drag the line in the animation player from left to right (Beginning to End), **it stops on frame 4? Why?**

![image](https://cloud.githubusercontent.com/assets/10387670/19065585/3137cbb8-89c9-11e6-9cd9-d356845636a5.png)

But, you can actually fix this, buy clicking on the last keyframe, and changing the value to `5`:
![image](https://cloud.githubusercontent.com/assets/10387670/19065608/49d50a78-89c9-11e6-9a92-fb8705405545.png)

Then, when you click enter, it will still show 4 (since there is only 4 frames in the spritesheet, counting index) so that's correct. But, now drag the animation timeline from left to right again... It now stops on frame 5 which is correct..

![image](https://cloud.githubusercontent.com/assets/10387670/19065636/6e65b02c-89c9-11e6-844f-56aa683ab1c8.png)

**Comment by akien-mga** [comment] 2016-10-04 07:33
Duplicate of your own #6173?

**Comment by akien-mga** [comment] 2016-10-04 07:35
Potential duplicate of #959 too.

**Comment by Dillybob92** [comment] 2016-10-04 07:47
Not sure about this one this is really strange

If you click on the **last** keyframe in the **timeline editor** and change the value to your `HFrames` value, it will obviously show 4 (as it's counting the index -- 5 frames)

![](https://i.gyazo.com/9e46fd84b56977cef769cc0970655464.gif)


It fixes everything and now makes this issue and my other 1 obsolete, what in the heck? O_O

Something is happening when you click the insert key. Trying to isolate this more..

**Comment by Dillybob92** [comment] 2016-10-04 07:50
This issue is a mess I apologize. I will try to make a video about this

**Comment by Zylann** [comment] 2016-10-04 09:18
You are trying to interpolate an integer, I guess there is some rounding at play.

**Comment by eon-s** [comment] 2016-10-04 10:44
In the captures I see step "0" (is that possible?), a project could be helpful to see if the issue is somewhere else.

**Comment by Dillybob92** [comment] 2016-10-04 12:41
Here guys, made a video to better showcase bug:

https://streamable.com/j505

**Comment by bojidar-bg** [comment] 2016-10-04 13:16
@Dillybob92  Are you sure this isn't a duplicate of #6173 and (maybe) #959?

**Comment by Dillybob92** [comment] 2016-10-04 14:42
I have no idea anymore @bojidar-bg I am sorry.

I want to say it's a duplicate of my old 6173 issue, but if we change the keyframe value in the timeline editor manually to n+1 it works fine. Thus voids the entire 6173 issue..

It works as intended if we don't use they insert keyframe button, but change the keyframe manually so I don't think rounding is at play here?

**Comment by brunoferreira94** [comment] 2017-02-21 04:00
On the last key, click on the pen to edit the transition, so click on the straight line and play again. Remember that you have to add a extra step after the final key.

**Closed** 2017-11-09 08:18 UTC
Labels: bug, topic:core

**Comment by akien-mga** [comment] 2017-11-09 09:16
*Bug triage note:* The original issue reporter closed all their issues before deleting their account. If you are affected by a similar issue/want a similar feature, please file a new ticket (referencing this one if it contains useful information) so that it can be further looked at and eventually resolved.
