### ISSUE TITLE
CTRL+TAB should cycle tabs in Script Editor

### ISSUE THREAD

**Issue by aegarpyke** [godotengine/godot#1093] opened 2015-01-03 03:35 UTC
Pretty much what the title says. If a custom keyboard shortcut can be set, even better!

**Comment by akien-mga** [comment] 2015-11-05 13:24
I'd have to check, but if Ctrl+Tab is not already implemented for something, it should probably be used for switching between scene tabs now that multiscene editing is implemented.
In the script editor, it could also be used to switch between scripts I guess, though that might be somewhat confusing as the script editor and the scene tabs are not well separated.

**Comment by vjrossi** [comment] 2016-04-02 11:10
This is a must-have, especially as Ctrl-W doesn't take you back to the previous tab and it's necessary to resort to the mouse. Very sad this hasn't been implemented in 15 months since Jan 2015.

**Comment by djrm** [comment] 2016-06-25 02:38
this has been fixed by #5304

**Comment by neikeq** [comment] 2016-06-25 09:18
I don't think this was fixed. This issue ask for such shortcut in the Script Editor, and IINW #5304 only adds it to the scene tabs.
However, I am not sure if it's right to add this to the Script Editor, since it would cause confusion with the Scene tabs.

**Comment by vnen** [comment] 2016-06-25 18:17
I think it makes sense to make it work with the script editor too if you use the option "Open dominant script on Scene change". I believe this would already work, but the problem is that the editor capture <kbd>TAB</kbd> and <kbd>Shift</kbd>+<kbd>TAB</kbd>, whether or not <kbd>Ctrl</kbd> is pressed.

**Comment by djrm** [comment] 2016-06-25 20:13
oh that's true, this haven't been fixed

**Comment by djrm** [comment] 2016-06-25 21:45
will be working on this one, but i dont know, should it switch scripts instead of tabs when the user is in script mode (this actually makes sense, since changing scenes keeps the editor in script mode)

**Comment by rgrams** [comment] 2016-06-26 01:41
You can already switch between next and previous scripts with Ctrl-Alt-Left and -Right, thought it's kind of confusing since it uses your history, rather than just going up and down the list. 

Using Ctrl-Tab and Ctrl-Shift-Tab for switching both scene tabs and scripts seems like a bad idea to me. I haven't tried your commit, is there a way to escape the script editor to switch scene tabs again? 

Of course once the kinks get worked out of customizing editor shortcuts, this won't be much of an issue, but I think making the same shortcut do different things at different times by default is a good way to confuse new users. Personally I would change the defaults so Ctrl-Alt-Left and Ctrl-Alt-Right switch scripts up and down the list rather than using the history, but that's just my opinion.

**Comment by djrm** [comment] 2016-06-26 02:30
@rgrams yeah maybe another shortcut would be a better idea

**Closed** 2016-06-30 06:04 UTC
Labels: enhancement, topic:editor, usability
