### ISSUE TITLE
Vulkan: Godot4 Alpha10 crashing when WorldEnvironment set to Background: Canvas

### ISSUE THREAD

**Issue by golddotasksquestions** [godotengine/godot#62455] opened 2022-06-27 11:55 UTC
### Godot version

v4.0.alpha10.official [4bbe7f0b9]

### System information

Win, Vulkan, Nvidea 765M

### Issue description

As the tile says, as soon as "Canvas" is selected, Godot crashes.
[Other users on Reddit reported a grey screen.
](https://www.reddit.com/r/godot/comments/vljpg0/need_help_with_glow_in_godot4/)
### Steps to reproduce

Add a WorldEnvironment Node,
add an Environment
set Background to "Canvas"

**Comment by akien-mga** [comment] 2022-06-27 12:09
Crashing on Linux too (AMD Radeon RX Vega M):
```
================================================================
handle_crash: Program crashed with signal 11
Engine version: Godot Engine v4.0.alpha.custom_build (c4f0062f15408988e743d65cb98dbb7347c29cf3)
Dumping the backtrace. Please include this when reporting the bug to the project developer.
[1] /lib64/libc.so.6(+0x3c3a0) [0x7f21d87823a0] (??:0)
[2] RendererSceneRenderRD::render_scene(RID, RendererSceneRender::CameraData const*, RendererSceneRender::CameraData const*, PagedArray<RendererSceneRender::GeometryInstance*> const&, PagedArray<RID> const&, PagedArray<RID> const&, PagedArray<RID> const&, PagedArray<RID> const&, PagedArray<RID> const&, PagedArray<RID> const&, RID, RID, RID, RID, RID, RID, int, float, RendererSceneRender::RenderShadowData const*, int, RendererSceneRender::RenderSDFGIData const*, int, RendererSceneRender::RenderSDFGIUpdateData const*, RendererScene::RenderInfo*) (/home/akien/Projects/godot/godot.git/servers/rendering/renderer_rd/renderer_scene_render_rd.cpp:5120)
[3] RendererSceneCull::render_empty_scene(RID, RID, RID) (/home/akien/Projects/godot/godot.git/servers/rendering/renderer_scene_cull.cpp:3285 (discriminator 4))
[4] RendererViewport::_draw_viewport(RendererViewport::Viewport*) (/home/akien/Projects/godot/godot.git/servers/rendering/renderer_viewport.cpp:499)
[5] RendererViewport::draw_viewports() (/home/akien/Projects/godot/godot.git/servers/rendering/renderer_viewport.cpp:662)
[6] RenderingServerDefault::_draw(bool, double) (/home/akien/Projects/godot/godot.git/servers/rendering/rendering_server_default.cpp:92)
[7] RenderingServerDefault::draw(bool, double) (/home/akien/Projects/godot/godot.git/servers/rendering/rendering_server_default.cpp:382)
[8] Main::iteration() (/home/akien/Projects/godot/godot.git/main/main.cpp:2824)
[9] OS_LinuxBSD::run() (/home/akien/Projects/godot/godot.git/platform/linuxbsd/os_linuxbsd.cpp:441)
[10] /home/akien/Projects/godot/godot.git/bin/godot.linuxbsd.tools.64(main+0x136) [0x2284f5c] (/home/akien/Projects/godot/godot.git/platform/linuxbsd/godot_linuxbsd.cpp:70)
[11] /lib64/libc.so.6(+0x29177) [0x7f21d876f177] (??:0)
[12] /lib64/libc.so.6(__libc_start_main+0x85) [0x7f21d876f235] (??:0)
[13] /home/akien/Projects/godot/godot.git/bin/godot.linuxbsd.tools.64(_start+0x21) [0x2284d61] (??:?)
-- END OF BACKTRACE --
================================================================
```

**Comment by Calinou** [comment] 2022-06-27 12:26
Duplicate of https://github.com/godotengine/godot/issues/62079.

**Closed by Calinou** 2022-06-27 12:26 UTC
Labels: bug, topic:rendering, confirmed, crash
