### ISSUE TITLE
Tile Map keyboard shortcuts doesn't work. it coincides with other keys.

### ISSUE THREAD

**Issue by icnikerazah** [godotengine/godot#15325] opened 2018-01-04 14:42 UTC
**Godot version:**
https://github.com/godotengine/godot/commit/e315c94900be47e61152a2958011e14b7e635a3e

**OS/device including version:**
macOs Sierra 10.12.6

**Issue description:**

Tile Map keyboard shortcuts doesn't work. it coincides with other keys.
these keys;
<img width="328" alt="ekran resmi 2018-01-04 17 29 57" src="https://user-images.githubusercontent.com/33985414/34568245-3faa506a-f176-11e7-9f55-67dfb4cae1a3.png">
<img width="195" alt="ekran resmi 2018-01-04 17 32 35" src="https://user-images.githubusercontent.com/33985414/34568251-435aed6e-f176-11e7-80d1-fb5cd43cec53.png">

**Steps to reproduce:**
for example "command+b" runs project not tilemap select.
"S" is not mirror tilemap cell , "S" is Snap
- [ ] I searched the existing [GitHub issues](https://github.com/godotengine/godot/issues?utf8=%E2%9C%93&q=is%3Aissue+) for potential duplicates.

**Comment by bojidar-bg** [comment] 2018-01-04 14:59
> - [ ] I searched the existing [GitHub issues](https://github.com/godotengine/godot/issues?utf8=%E2%9C%93&q=is%3Aissue+) for potential duplicates.

Duplicate of #15145.

**Closed by bojidar-bg** 2018-01-04 14:59 UTC
