### ISSUE TITLE
C# '@' special character for multi-lines strings is not displayed correctly like in visual studio editor

### ISSUE THREAD

**Issue by Delectus98** [godotengine/godot#40021] opened 2020-07-01 14:20 UTC
**Godot version:**

3.2.1 Mono

**OS/device including version:**

Windows 10

**Issue description:**

Using '@', the verbatim identifier, for multi-lines strings the godot editor is not able to know when the strings ends.

Exemple in godot editor:

``` C
//displayed as code (normal)
class Foo
{

    public void foo()
    {
           string str = 
// displayed as string content (normal)
           @" line 1
           line 2
           line 3
           ...."
// displayed as string content (bad)
           ;
     }
}
```

Visual studio editor knows when strings ends when started with '@'.

Exemple in vs editor:

``` C
//displayed as code (normal)
class Foo
{

    public void foo()
    {
           string str = 
// displayed as string content (normal)
           @" line 1
           line 2
           line 3
           ...."
//displayed as code (normal)
           ;
     }
}
```

**Comment by Calinou** [comment] 2020-07-01 14:24
Duplicate of #32336 (fixed in 3.2.2 by #37484).

**Closed by Calinou** 2020-07-01 14:24 UTC
