### ISSUE TITLE
Input.action_just_pressed and Input.action_just_released doesnt work in _physics_process on Android

### ISSUE THREAD

**Issue by ShadowwDev** [godotengine/godot#66318] opened 2022-09-23 20:21 UTC
### Godot version

4.0.beta1

### System information

Vulkan Android

### Issue description

on Android with TouchScreenButton node, input_action_just_pressed and Input.action_just_released doesnt work in _physics_process function but it does work with _process function however.

This works on godot 3.5 so im guessing its a bug on godot 4 beta 1

### Steps to reproduce

heres an example project with the details:
https://github.com/ShadowwDev/Godot4Beta1-InputBugTest

### Minimal reproduction project

Project download 
[InputBugAndroid.zip](https://github.com/godotengine/godot/files/9636878/InputBugAndroid.zip)

**Comment by aea0ccf9** [comment] 2022-10-09 14:53
I can confirm this on 4.0.beta2.

**Comment by dannygaray60** [comment] 2022-12-29 17:47
I was developing a project with Godot4 beta10 and ran into that same problem. When calling Input.is_action_just_pressed... on android it does not work if it is inside physics_process, it only works inside _process.

**Comment by erniel** [comment] 2023-02-05 07:52
same issue with godot 4 beta 16. Input.is_action_just_pressed doesnt work on android

**Comment by visionm45** [comment] 2023-03-02 04:59
Confirmed bug in Godot 4.0

**Comment by ivandortulov** [comment] 2023-05-03 22:48
This is still happening. Wish that it is fixed soon. The `_process(delta)` workaround does work.

**Comment by Calinou** [comment] 2023-05-03 22:58
On 4.0.2, this works on desktop when enabling **Emulate Touch From Mouse** in the advanced Project Settings, so the issue is Android-specific (or Android/iOS).

**Comment by ehsanonline** [comment] 2023-05-11 18:36
I'm using `v4.0.1.stable.official [cacf49999]` and `Input.is_action_just_pressed` and `Input.is_action_just_released` aren't working on android. I use them for jumping.

**Comment by visionm45** [comment] 2023-05-11 20:54
try 4.0.2

**Comment by erniel** [comment] 2023-05-12 15:09
> try 4.0.2

Still not working on android

**Comment by erniel** [comment] 2023-07-08 22:16
Confirmed bug in Godot 4.1

**Comment by idbrii** [comment] 2023-10-01 17:51
Is this issue because is_action_just_pressed checks if the input was pressed on *this frame* where each frame is a call to `_process` and not `_physics_process`? Maybe on Android, the framerate you're getting means that `_physics_process` isn't called frequently enough to hit the right frames when the input was changed (but on PC the framerate works out)?

**Comment by Alex2782** [comment] 2023-10-15 13:59
> On 4.0.2, this works on desktop when enabling **Emulate Touch From Mouse** in the advanced Project Settings, so the issue is Android-specific (or Android/iOS).

Is the emulation started here? [input.cpp#L502](https://github.com/godotengine/godot/blob/51f81e1c88499f04d2ebdcc0be0b34e73f5e90eb/core/input/input.cpp#L502)
TouchScreenButton events on Android here [input.cpp#L858](https://github.com/godotengine/godot/blob/a574c0296b38d5f786f249b12e6251e562c528cc/core/input/input.cpp#L858)


I think because `TouchScreenButton` is a graphical element, the functions are only triggered after `_physics_process`.
Workaround: #83301 ` = get_physics_frames() + 1`

I was going to compare it to a normal `Button`, but there is no `action` property. [Docs](https://docs.godotengine.org/en/latest/classes/class_button.html#properties)
If it should be solved like with the `TouchScreenButton`, then you could probably reproduce the problem in the desktop version.

**Comment by lawnjelly** [comment] 2023-10-16 08:56
Sorry I must have missed this bug report.

It may be a regression from my PR #77055 .

I have a fair idea of what may be happening, and why it occurs on Android (because it has separate input thread).

Previously both a press AND release updated the physics tick on the action, so it may have been reporting the `action_just_pressed` on the next physics tick when released (because it occurred too late for the current user code to intercept it). It would have still been likely buggy.

There's a PR (#83301) to just increase the physics tick registered for the press. This would likely "fix" the issue, but isn't ideal because it introduces a tick of delay to input, I'll put a note on that PR.

The actual problem makes total logical sense if you think about it. Every physics tick you have an opportunity to process presses that come in that tick. If the press comes in _after_ the `_physics_process`, then it can be missed. This isn't occurring on most platforms as they process input synchronously before a tick, but on Android it can occur after (by random chance).

I think this should be pretty easy to fix properly, I'll do a PR. :+1:

**Comment by synalice** [comment] 2023-10-18 22:18
Indeed, moving some of the `Input` code into the `_process` function fixed this issue for me. Thx ❤️
It really needs to be more clear what is going wrong. Something like debug warnings, idk.

**Comment by lawnjelly** [comment] 2023-10-19 06:51
> Indeed, moving some of the `Input` code into the `_process` function fixed this issue for me. Thx ❤️
> It really needs to be more clear what is going wrong. Something like debug warnings, idk.

The fault is not your side, it's an engine bug. There is PR to fix it, it just needs to be reviewed and merged. There's no point making a PR for warnings, as it is just as simple to fix it.

In some cases putting input code in the `_process()` can be used to mostly workaround it in the meantime (although even that appears to be susceptible, to a lesser extent).

**Comment by synalice** [comment] 2023-10-19 07:31
Then what's the point of using `_process` at all? Isn't everything better
off being inside of a `_physics_process`?

**Comment by Alex2782** [comment] 2023-10-19 13:38
@synalice 
https://github.com/godotengine/godot/pull/83438#issuecomment-1765333406
You could try this demo and check the input latencies and experiment with engine settings.

Normally you should also process all inputs under `_physics_process` (at 60 FPS, because '_physics_process' is executed before '_process), but on Android that doesn't work so well yet. There is a bugfix for the `is_action_just` functions, but this increases the input latency (at 60 FPS it is at least 16.7ms).

**Closed** 2023-10-24 08:55 UTC
Labels: bug, platform:android, topic:porting, confirmed, topic:input, regression
