### ISSUE TITLE
Instantiating scenes that contain CPUParticles2D node causes spikes in the profiler (not just the first time)

### ISSUE THREAD

**Issue by pixel-boy** [godotengine/godot#73494] opened 2023-02-17 11:58 UTC
### Godot version

3.5.2.rc2.official

### System information

Windows10 / GLES3

### Issue description

Instantiating scenes containing nodes of type CPUparticles2D causes spikes in the profiler:

![godot_particle_profileur_spike](https://user-images.githubusercontent.com/16109919/219645849-f9b00d1c-daae-4a04-89ca-ac409f2b67f6.png)

Oddly the profiler only shows 0.05ms for script functions, while shoot projectile took 16.06ms, maybe this is just normal behavior, but it seems to cause stutter issues.

### Steps to reproduce

Instantiated scenes containing CPUParticles2D

### Minimal reproduction project

[ParticleTest.zip](https://github.com/godotengine/godot/files/10766388/ParticleTest.zip)

**Comment by Zireael07** [comment] 2023-02-17 13:43
Shader compiling most likely?

**Comment by clayjohn** [comment] 2023-02-17 18:13
@pixel-boy Are you freeing the scenes before instantiating again? Freeing the scene would clean up and free the shaders in the scene as well.

**Comment by pixel-boy** [comment] 2023-02-17 18:24
@clayjohn In the example I put above it was deleted after 3 seconds, but I just tried without deleting them and the problem is also there, a gif to illustrate the situation: 

![bug_particle](https://user-images.githubusercontent.com/16109919/219749848-ee219bd6-3f4d-4178-9ad3-894cbf9ea827.gif)

**Comment by clayjohn** [comment] 2023-02-17 18:43
I can't reproduce the issue on PopOS 22.04 with 3.5.2 rc2 or with 3.5.1 with intel integrated graphics. When I run there is no frame spike from instantiating the scene. 

Since the spike occurs even when the previous scene wasn't freed, it is unlikely to be shader compilation stutter. 

One possibility here is that the spike is caused from allocating the required memory for the CPUParticles effect (both on CPU and GPU). To confirm it would be helpful to get more testing on Windows where OpenGL drivers tend to be quite slow. 

Another possibility is some sort of frame synching going on. In the original image it looks like the amount of time is pretty consistently around 16ms which makes it look like it is waiting for Vsync or something. It would be useful to see if the same spike occurs when Vsync is disabled (I tested on my device with Vsync enabled and disabled and saw no spike in either case)

**Comment by Calinou** [comment] 2023-02-17 21:19
- Related to https://github.com/godotengine/godot/issues/48978.

**Comment by pixel-boy** [comment] 2023-02-17 21:25
I confirm that the problem is no longer there without vsync.

**Comment by clayjohn** [comment] 2023-02-17 21:25
Thanks for checking! That means this is the same as https://github.com/godotengine/godot/issues/66365. So I will be closing this issue so we can track everything in one place.

**Closed by clayjohn** 2023-02-17 21:25 UTC
Labels: bug, needs testing
