### ISSUE TITLE
SpotLight (and other lights*) stops affecting Volumetric Fog if shadows are turned on

### ISSUE THREAD

**Issue by Jamsers** [godotengine/godot#69611] opened 2022-12-05 15:25 UTC
### Godot version

4.0.beta7.official

### System information

Windows 11 22H2, GTX 1650 Mobile, NVIDIA Driver 527.37, Vulkan

### Issue description

Lights seem to stop affecting volumetric fog if their shadows are turned on, save for a small flickery sliver near the light source itself.

![shadowVolumetric](https://user-images.githubusercontent.com/39361911/205672197-6ce74a8c-fc26-4d8c-9d83-b9cafaf86c7d.png)

*The issue presents itself with DirectionalLight and OmniLight, but if you enable shadows for DirectionalLight/OmniLight and then reload the project, the issue seems to get fixed. But not so for SpotLight.

### Steps to reproduce

Turn on Volumetric Fog in your WorldEnvironment.
Place a SpotLight (or another light*) in your scene.
(Try to setup the scene in a way that makes Volumetric Fog's effect obvious, i.e. placing a cube in front of the light)
Turn on the SpotLight's shadows.
Notice that the light stops affecting Volumetric Fog.

### Minimal reproduction project

[VolumetricFogIssue.zip](https://github.com/godotengine/godot/files/10155327/VolumetricFogIssue.zip)

**Comment by Calinou** [comment] 2022-12-05 17:26
Duplicate of https://github.com/godotengine/godot/issues/57722.

**Closed by Calinou** 2022-12-05 17:26 UTC
Labels: bug, topic:rendering
