### ISSUE TITLE
Tree signal "item_custom_button_pressed" doesn't work

### ISSUE THREAD

**Issue by eskandrej** [godotengine/godot#71928] opened 2023-01-23 18:23 UTC
### Godot version

v4.0.beta.custom_build [7b1747d36]

### System information

Windows 10, NVIDIA GeForce GTX 760

### Issue description

Signal is never emitted. I've searched in the code and it seems that the signal is only defined but not emitted anywhere.

### Steps to reproduce

N/A

### Minimal reproduction project

N/A

**Comment by Calinou** [comment] 2023-01-23 18:25
See https://github.com/godotengine/godot/issues/37604.

**Comment by akien-mga** [comment] 2023-01-23 19:39
Duplicate of #37604

**Closed by akien-mga** 2023-01-23 19:39 UTC
Labels: discussion, topic:gui
