### ISSUE TITLE
Delete folders for nonexistent projects in %appdata%/godot

### ISSUE THREAD

**Issue by rogeriodec** [godotengine/godot#26894] opened 2019-03-11 02:52 UTC
**Godot version:**
3.1 RC1

**OS/device including version:**
Windows 10 x64

**Issue description:**
While I do a "Scan" in "Project List", the old projects whose folders have been deleted still remain in `%appdata%/godot/projects` and `%appdata%/godot/app_userdata` folders.

- The `app_userdata` folder keeps the names of the folders of nonexistent projects, but they are empty.
- The `projects` folder maintains a series of configuration files that should no longer exist.

**Steps to reproduce:**

1. Create any project and exit Godot
2. Delete its folder (via Windows Explorer)
3. Run Godot and click "Scan" on "Project List" window
4. Check the `%appdata%/godot` sub-folders.

**Comment by Zireael07** [comment] 2019-03-11 07:41
Some people run projects from USB, so when the USB is not in, the project is "deleted" (inaccessible) but its cache etc. folders should not be deleted, for obvious reasons... That is a problem with all similar suggestions.

**Comment by rogeriodec** [comment] 2019-03-11 12:52
> Some people run projects from USB, so when the USB is not in, the project is "deleted" (inaccessible) but its cache etc. folders should not be deleted, for obvious reasons... That is a problem with all similar suggestions.

https://docs.godotengine.org/en/3.0/development/compiling/packaging_godot.html

_"The self contained mode can be used to package Godot for distribution systems where it doesn’t live at a fixed location. If the editor finds a .`_sc_` file in the directory the executable is located in, Godot will continue in “self contained mode”. On Windows, the file name to use is _sc_ (without the preceding dot)."_

**Comment by eon-s** [comment] 2019-03-11 21:12
Self contained mode is about the editor, not the projects.

An option to clean the cache may be useful in the project manager.

Duplicate of #22467.

Related PR #25882.

**Comment by clayjohn** [comment] 2019-04-21 06:28
Closing as duplicate of #22467.

**Closed by clayjohn** 2019-04-21 06:28 UTC
