### ISSUE TITLE
Using wrong type on variable setter silently fails, "set" method sets to default value

### ISSUE THREAD

**Issue by nathanfranke** [godotengine/godot#48865] opened 2021-05-19 22:00 UTC
**Godot version:**
3.3.1 :tada: 

**OS/device including version:**
Ubuntu 20.10

**Issue description:**
Script:
```swift
extends Node

var my_var1 setget _set_my_var1
func _set_my_var1(value: int) -> void:
	my_var1 = value

var my_var2: int

func _ready():
	self.my_var1 = 5
	self.my_var2 = 5
	
	self.my_var1 = "This should throw an error"
	var untyped = "This should throw an error"
	self.my_var2 = untyped
	
	print(self.my_var1) # Silently failed
	print(self.my_var2) # Sets to zero
```

Result:

```py
5 # Silently failed
0 # Set to zero
```

Expected: Both setters should have an error. The first one can be checked at compile time, and the second one can only be checked at runtime.

**Steps to reproduce:**
1) Create variable with no type hint, but a setter with a type hint.
2) Set the variable using normal syntax to an invalid value.

1) Create variable with type hint.
2) Set the variable using `set` method _or_ a typeless expression to an invalid value.

**Minimal reproduction project:**
[GodotSetterBug.zip](https://github.com/godotengine/godot/files/6511751/GodotSetterBug.zip)

**Comment by Calinou** [comment] 2021-05-19 23:35
Duplicate of https://github.com/godotengine/godot/issues/48765.

**Closed by Calinou** 2021-05-19 23:35 UTC
