### ISSUE TITLE
(BUG) Engine UI Offset for input fields, tab buttons and popups.

### ISSUE THREAD

**Issue by HappyWood** [godotengine/godot#57071] opened 2022-01-22 20:49 UTC
### Godot version

4.0.dev

### System information

Windows 10, Vulkan, AMD Ryzen 7 3600, Nvidia 1060 6gb

### Issue description

When clicking on the tab button the sub-button panel has a weird offset, it also happens with the input field and also with every popups.

![image](https://user-images.githubusercontent.com/60289655/150654960-2245a0c8-35d2-42c0-9407-2618e14e143f.png)
![image](https://user-images.githubusercontent.com/60289655/150654969-806fc83d-94c0-4215-bff4-7396f736f4a6.png)

### Steps to reproduce

Click on a number , text ect... or tab button to have this offset and the input box or the button pannel will have an offset.

**Comment by Calinou** [comment] 2022-01-22 21:19
Duplicate of https://github.com/godotengine/godot/issues/45740.

**Closed by Calinou** 2022-01-22 21:19 UTC
