### ISSUE TITLE
The material effect in the preview is different from runtime view

### ISSUE THREAD

**Issue by lee12321** [godotengine/godot#27323] opened 2019-03-22 14:00 UTC
**Godot version:**

3.1 stable

**OS/device including version:**

NVIDIA GeForce GTX 660

**Issue description:**

the water material is from this [repo](https://github.com/Maujoe/godot-basic-water-material.git)
the effect in the preview is different from runtime view
![N)B({A%B13~58VV6BCPH)F](https://user-images.githubusercontent.com/39612837/54826565-04056a00-4ceb-11e9-8b08-e8a3a36a56c6.png)

![1LNR(UGF@)N0SJUKMG%(K65](https://user-images.githubusercontent.com/39612837/54826772-7f671b80-4ceb-11e9-8e84-cd54569638f0.png)

Water shader on this [repo ](https://github.com/faculezcano/godot-water-shader.git)seems have similar problem 
**Steps to reproduce:**
import the project and run it

**Minimal reproduction project:**

**Comment by LinuxUserGD** [comment] 2019-03-24 10:46
For me it works on my project. I only have the issue that it's only rendering the water material with gles2.

**Comment by lee12321** [comment] 2019-03-24 11:47
> For me it works on my project. I only have the issue that it's only rendering the water material with gles2.

I have issue using gles3 but with gles2 I can see water material

**Comment by tjysdsg** [comment] 2019-03-24 12:04
```
uname -a
Linux tjysdsg 4.19.30-1-lts #1 SMP Tue Mar 19 17:47:54 CET 2019 x86_64 GNU/Linux
```
Confirm that using `gles3` driver the issue can reproduce, but using `gles2` driver the scene run normally.
Using `Lenovo T480`, graphics card `Geforce MX150`

**Comment by Maujoe** [comment] 2019-03-25 20:44
This is a problem with Proximity Fade: #25387 

A temporary workaround is to disable the Proximity Fade option until it got fixed ;)

**Comment by Calinou** [comment] 2019-03-25 20:56
I'll close this issue as a duplicate of #25387. Thanks for confirming it :slightly_smiling_face:

**Closed by Calinou** 2019-03-25 20:56 UTC

**Comment by LinuxUserGD** [comment] 2019-03-28 07:15
I have another issue with GLES2: On HTML5 there is no water and on Android the water looks strange (distorted and low quality).

**Comment by LinuxUserGD** [comment] 2019-04-09 20:01
> I have another issue with GLES2: On HTML5 there is no water and on Android the water looks strange (distorted and low quality).

Here are images where you can see the low-res water material on Android (GLES2):


![bug](https://user-images.githubusercontent.com/34406967/55831147-bd997300-5b12-11e9-85a0-177a594398af.png)
![bug2](https://user-images.githubusercontent.com/34406967/55831156-c0946380-5b12-11e9-8e1d-5901acec84db.png)


Should I open another issue?
