### ISSUE TITLE
Godot editor 4.0 freezes on any sort of interaction

### ISSUE THREAD

**Issue by Shadowblitz16** [godotengine/godot#43808] opened 2020-11-24 00:40 UTC
**Godot version:**
4.0

**OS/device including version:**
Zorin OS 15.3 nvidia GTX 650

**Issue description:**
when opening up 4.0 the editor freezes and lags my os 

**Steps to reproduce:**
- Open Godot 4.0
- Click anywhere
- Editor does not respond and os partially freezes

**Minimal reproduction project:**
Its just a new project

**Comment by qarmin** [comment] 2020-11-24 07:08
Are you using Nvidia proprietary drivers 450 or 455?

**Comment by Shadowblitz16** [comment] 2020-11-24 20:38
@qarmin 
![image](https://user-images.githubusercontent.com/2453707/100148658-e4283100-2e51-11eb-87ba-3dff83d3b143.png)
yep looks like it

**Comment by Calinou** [comment] 2020-11-24 20:42
Duplicate of https://github.com/godotengine/godot/issues/41614.

**Closed by Calinou** 2020-11-24 20:42 UTC
