### ISSUE TITLE
Shader parameters not set correct when exporting via self contained server version

### ISSUE THREAD

**Issue by Keetz** [godotengine/godot#12923] opened 2017-11-14 14:22 UTC
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Godot 2.1.4-stable

**Issue description:**

When exporting a project using godot 2.1.4-stable compiled with "platform=server" (or using the server version from the website) and in self contained mode, shader parameters set in the inspector is reset to the original values in the shader script.

**Steps to reproduce:**
1. Download the project included, it already includes a godot server version and export templates for linux.

2. Verify the project and check the wanted end result. Run the game and note the size of the shader, and note the values printed to the console, they are the same as the shader parameters set in the inspector.

3. Now export the project using the godot server version in the godot folder in the project.
Run following from inside the godot folder:
`./godot_2.1.4_server -export "Linux X11" /home/*your_user*/Documents/test`
Last part is the desired location of the export, edit it to match your desired location.

4. Run the game that you just exported and notice how the shader is considerable smaller now, and even check the output in the terminal to see that the values are not what is set in the inspector.

**More info:**
I have tested this in self contained mode with the server version and the normal editor version.
I have tested this with the server version and editor version **NOT** in self contained mode.
I have tested this by exporting from the exporter in the editor.
I have tested this by downloading the server version from the website, and compiled my own server version at the tag '2.1.4-stable'.

It **only** happens with the server version in self contained mode.

**Images:**
A look at the shader if the game is run from within the editor:
![selection_063](https://user-images.githubusercontent.com/6707330/32784366-ee933254-c94e-11e7-92ac-8d15999a16c3.jpg)

A look at the shader if the game is run from the exported binary:
![selection_062](https://user-images.githubusercontent.com/6707330/32784420-18980264-c94f-11e7-8733-50aacf19cc78.jpg)

Notice the size difference of the white ring.

These are the original parameters:
![selection_065](https://user-images.githubusercontent.com/6707330/32784593-8dec4d18-c94f-11e7-8959-954a9432bf78.jpg)

These are the parameters set in the inspector. These are the values we want to see in the output of the exported game!
![selection_064](https://user-images.githubusercontent.com/6707330/32784551-702bb548-c94f-11e7-9c07-05f9eddd8f48.jpg)

**Link to minimal example project:**
https://github.com/Keetz/GodotShaderBugProject
or direct download:
https://github.com/Keetz/GodotShaderBugProject/archive/master.zip

If you don't want to run the binaries i included for trust issues or whatever :ok_hand:
Just replace the 'godot_2.1.4_server' with the official Linux Server 64 bit from here https://godotengine.org/download
And replace the templates with the ones found in the Export Templates from the same link

**Comment by akien-mga** [comment] 2017-11-14 14:30
Tagging as 2.1 as it needs to be fixed there where the server binary is available (it's not currently in 3.0), but once the cause of the bug is found, it should be made sure that it's fixed in master too.

**Comment by Keetz** [comment] 2018-06-07 08:31
Wanted to test this on current master, but I can't before #16949 is fixed.

**Comment by KoBeWi** [comment] 2020-06-12 23:45
Can anyone still reproduce this bug in Godot 3.2.1 or any later release (e.g. [3.2.2-beta4](https://godotengine.org/article/dev-snapshot-godot-3-2-2-beta-4))?

If yes, please ensure that an up-to-date Minimal Reproduction Project (MRP) is included in this report (a MRP is a zipped Godot project with the minimal elements necessary to reliably trigger the bug). You can upload ZIP files in an issue comment with a drag and drop.

**Comment by KoBeWi** [comment] 2020-09-28 00:22
Closing due to no reply. Please comment if you can still reproduce in 3.2.3+.

**Closed by KoBeWi** 2020-09-28 00:22 UTC
Labels: bug, topic:editor
