### ISSUE TITLE
Can't intercept InputEvents sent  to pickable CollisionObjects

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#16042] opened 2018-01-24 20:58 UTC
Godot 3.0 RC2

I had this problem long before, but I was not sure if the feature was hidden somewhere or just inexistent:
basically, I couldn't find a way to mark an InputEvent as handled in the `input_event` signal of a pickable `CollisionObject[2D]`.
This would be especially useful with overlapping objects. It seems the front-most already receives the input first, but it gets forwarded to every next object regardless.

**Comment by volzhs** [comment] 2018-01-24 22:16
i have same issue.

**Comment by henriquelalves** [comment] 2018-02-21 17:48
I can confirm this problem, "_input_event" is not working the same as in Godot 2.1.4.

**Comment by mhilbrunner** [comment] 2018-04-04 19:13
What about SceneTree.set_input_as_handled()?
http://docs.godotengine.org/en/3.0/classes/class_scenetree.html#class-scenetree-set-input-as-handled?

**Comment by KoBeWi** [comment] 2019-09-06 22:49
> What about SceneTree.set_input_as_handled()?

It doesn't seem to work with `input_event()`.

**Comment by akien-mga** [comment] 2023-06-07 16:43
Duplicate of #29825 which is more detailed.

**Closed by akien-mga** 2023-06-07 16:43 UTC
Labels: enhancement, topic:physics, topic:input
