### ISSUE TITLE
Input.parse_input_event does not work in version 4.2.1

### ISSUE THREAD

**Issue by devmark404** [godotengine/godot#87692] opened 2024-01-29 01:17 UTC
### Tested versions

It worked in version 4.1.1, but in version 4.2.1 it does not work

### System information

Window 10 - Godot v4.2.1 - Mobile

### Issue description

Input.parse_input_event does not work in version 4.2.1, but it does work in version 4.1.1

Here I have a godot project that when pressing the button should execute the action 'ui_left'

It works perfectly in godot 4.1.1 but when I try to use it in godot 4.2.1 it doesn't work

Try to use Input.action_press() but it doesn't give the desired results as this method keeps running infinitely

Code

```
extends Node2D

@export var input_pressed:String = ''

func _process(delta: float) -> void:
	if Input.is_action_pressed("ui_left", true):
		print('The button left is being pressed')
	pass

func _on_button_button_down() -> void:
	# This way works correctly in godot 4.1.1, but in godot 4.2.1 it doesn't work
	input_parse_input_event(true)
	
	# If I use this way, is_action_pressed is still executed even if I change the value of 'pressed' to false
	#input_action_press(true)
	pass
	
func _on_button_button_up() -> void:
	# This way works correctly in godot 4.1.1, but in godot 4.2.1 it doesn't work
	input_parse_input_event(false)
	
	# If I use this way, is_action_pressed is still executed even if I change the value of 'pressed' to false
	#input_action_press(false)
	pass

func input_parse_input_event(is_pressed=true):
	var e = InputEventAction.new() 
	e.action = input_pressed
	e.pressed = is_pressed
	Input.parse_input_event(e) 
	print(e)
	pass

func input_action_press(is_pressed=true):
	var e = InputEventAction.new() 
	e.action = input_pressed
	e.pressed = is_pressed
	Input.action_press(e.action) 
	print(e)
	pass
```

Don't forget to add ui_left in the editor variable if you use this code

### Steps to reproduce

Use godot 4.1.1 to see correct operation
Run the current scene
Press the button that appears
You will see a message displayed while the button is being pressed

Then use godot 4.2.1
Run the current scene
Press the button that appears
The message indicating that the button has been pressed will not appear.

### Minimal reproduction project (MRP)

[Godot Error Input Button 4.1.1.zip](https://github.com/godotengine/godot/files/14078617/Godot.Error.Input.Button.4.1.1.zip)

Example

Use godot 4.1.1 to see correct operation
Run the current scene
Press the button that appears
You will see a message displayed while the button is being pressed
'The button left is being pressed'

Then use godot 4.2.1
Run the current scene
Press the button that appears
The message indicating that the button has been pressed will not appear.
'The button left is being pressed'

**Comment by Rubonnek** [comment] 2024-01-29 12:18
I'm able to reproduce this issue with a custom build from `master` at 17e7f85c06366b427e5068c5b3e2940e27ff5f1d as well.

**Comment by rsubtil** [comment] 2024-01-29 12:31
Possibly a duplicate of #85984, and https://github.com/godotengine/godot/pull/86010 might fix this, could you give it a try?

**Comment by Rubonnek** [comment] 2024-01-29 12:55
> Possibly a duplicate of #85984, and #86010 might fix this, could you give it a try?

#86010 fixes this issue as well, and the issue presented in #85984 is virtually the same.

Closing as duplicate of #85984.

**Closed by Rubonnek** 2024-01-29 12:55 UTC
Labels: bug, topic:input, regression
