### ISSUE TITLE
Having a variable named `value` causes a source generator error 4.0 beta5

### ISSUE THREAD

**Issue by cphillips83** [godotengine/godot#68746] opened 2022-11-16 20:05 UTC
### Godot version

4.0.beta5

### System information

Windows 11

### Issue description

```
Godot.SourceGenerators\Godot.SourceGenerators.ScriptPropertiesGenerator\XYZ_ScriptProperties.generated.cs(36,13): error CS8331: Cannot assign to variable 'in godot_variant' b
ecause it is a readonly variable [PROJECT.csproj]
```

### Steps to reproduce

1. Create a new project
2. Create a C# script deriving from Node (or in my test case it was `HBoxContainer`)
3. Create a variable `private int value;`
4. Build with `dotnet build`

You will be greeted with a total of 3 errors, all appear to be due to a conflict with the name `value` which looks to be used internally in Godot

**Comment by pihdastudios** [comment] 2022-11-18 03:09
this also occurs when the variable name is `name`
`public String name`

**Comment by raulsntos** [comment] 2022-11-24 02:38
Duplicate of https://github.com/godotengine/godot/issues/66819

**Closed by raulsntos** 2022-11-24 02:38 UTC
Labels: bug, topic:dotnet
