### ISSUE TITLE
Debug -> Visible Collision Shapes and get_tree().debug_collisions_hint ambiguity and not working correctly.

### ISSUE THREAD

**Issue by blipk** [godotengine/godot#64353] opened 2022-08-13 09:47 UTC
### Godot version

4.0.alpha13

### System information

Arch AMD64

### Issue description

Checking the editor menu option `Debug -> Visible Collision Shapes` seems to conflict with `get_tree().debug_collisions_hint` which also doesn't behave correctly.

Some strange behaviour between combinations and usage of those settings:
1. I have a `TileMap` node if I set `collision_visibility_mode` either as `VISIBILITY_MODE_FORCE_HIDE` or `VISIBILITY_MODE_FORCE_SHOW` this will override whatever option is set from the editor menu. This I can understand and makes some sense, but may be confusing to some.

2. I have `TileMap` and `RayCast2D` nodes with default properties (no `TileMap.collision_visibility_mode`) and the following debug function on a node:
```
func _process(_delta):
	if Input.is_action_just_pressed("toggle_colliders"):
		print(get_tree().is_debugging_collisions_hint())
		get_tree().debug_collisions_hint = not get_tree().debug_collisions_hint
		print(get_tree().is_debugging_collisions_hint())
```
If editor option _Visible Collision Shapes_ is turned off:
The above action doesn't change the TileMap visibility, however after a delay it will make the raycast visible, which is actually the `visible` property which has no mention of collisions.

If editor option _Visible Collision Shapes_ is turned on:
The `TileMap` physics layers will show as well as the `RayCast`, however using the above action doesn't disable any of them, except strangely maybe occasionally the raycast.

The following function has the desired effect of toggling the collision visibility on or off and without delay:
```
if Input.is_action_just_pressed("toggle_colliders"):
	print(get_tree().is_debugging_collisions_hint())
	get_tree().debug_collisions_hint = not get_tree().debug_collisions_hint
	tilemap.collision_visibility_mode = tilemap.VISIBILITY_MODE_FORCE_SHOW if get_tree().is_debugging_collisions_hint() else tilemap.VISIBILITY_MODE_FORCE_HIDE
	raycast.visible = get_tree().debug_collisions_hint
	print(get_tree().is_debugging_collisions_hint())
```

Overall it seems very confusing and inconsistent behaviour between the editor `Visible Collision Shapes` option and `get_tree().debug_collisions_hint` and when and how they will affect `collision_visibility_mode` or `visibility` on which or what nodes.

### Steps to reproduce

See above.

**Comment by Calinou** [comment] 2022-08-13 10:19
@blipk Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

**Comment by blipk** [comment] 2022-08-13 11:16
Thanks Calinou, I'll see what I can do, but really the first snippet I shared is enough to see that debug_collisions_hint seems to only set the visibility of collision shapes once or not at all, it won't toggle.

The behaviour was also similar (or worse) in 3.4stable with debug_collisions_hint having no effect at all.

It's also a a matter of ambiguity between the editor feature, the SceneTree.debug_collisions_hint and how and what they effect on nodes. 

Perhaps this is more of a note to further detail documentation on the editor feature, the SceneTree property, and to describe what they effect.

**Comment by smix8** [comment] 2022-08-13 12:46
The SceneTree debug_hints are not designed to be toggleable at runtime.

The Editor stuff that manages the usual debug visuals is not available at runtime so those debug_hints are set by the main iteration at the game start to let nodes know that they are now responsible for creating debug visuals when they are first created.

Most nodes will not react to changing the debug_hints afterwards except for those few nodes that rebuild everything all the time.

I don't think the SceneTree should have to do with anything debug related at all. Navigation recently moved nearly all debug to the Editor gizmo and NavigationServer (still uses debug_hint but only due to compatibility) ti cleanup the SceneTree. Maybe physics should do the same at some point and move everything to the PhysicsServer and make collision debug toggleable.

**Comment by blipk** [comment] 2022-08-14 01:46
Thanks for the info @smix8.

The description for debug_collision_hints says
```
If true, collision shapes will be visible when running the game from the editor for debugging purposes.
```

Which really isn't true, like you said it has no real effect being changed at runtime. Would be nice to have the docs explain this so people aren't scratching their heads.

Your suggestions to move it to the PhysicsServer make sense though and the feature use isn't too urgent so I'm happy to wait for these things to be implemented in well thought out way.

**Comment by mhilbrunner** [comment] 2022-08-17 12:54
As per the above PRs, this is now documented. @Calinou Should we close this issue then?

**Comment by Calinou** [comment] 2022-08-17 14:08
> As per the above PRs, this is now documented. @Calinou Should we close this issue then?

Yes – I think run-time toggleability of those properties should be discussed in a [proposal](https://github.com/godotengine/godot-proposals), with a technical implementation mentioned.

**Closed by Calinou** 2022-08-17 14:08 UTC
Labels: documentation, topic:physics
