### ISSUE TITLE
Adding an AtlasTexture to MenuButton's item, locks you in texture region editing mode (w/ workaround)

### ISSUE THREAD

**Issue by Skaruts** [godotengine/godot#43405] opened 2020-11-09 08:35 UTC
Found this in `Godot 3.2.3.stable`.

As seen in the image below, when you add an `AtlasTexture` to an item of a `MenuButton` and then click it, all the items disappear and you get locked in texture region editing mode. The `Items` drop down menu for that `MenuButton` also disappears.

![mbtn01](https://user-images.githubusercontent.com/6277234/98517064-46cfd900-2265-11eb-9ad0-b3688e644626.gif)

--- 
#### Workaround
A simple workaround (image below) is to use a second `MenuButton`, add an item and set another type of texture to it. You may notice this time the texture properties panel is open by default. Click to close it, and that will close the `AtlasTexture` properties on the first button as well, which will take you out of texture region mode. Now when you select the first button, you have access to the items again and can remove the `AtlasTexture`.

![mbtn01_workaround](https://user-images.githubusercontent.com/6277234/98517076-4a636000-2265-11eb-9aef-ffae0423aa23.gif)

If all else fails, you can also edit the scene file and remove the resource from the scene and from the button's item.

**Comment by KoBeWi** [comment] 2020-11-09 11:27
Related to #28211

**Comment by KoBeWi** [comment] 2021-01-11 00:33
Actually can be closed as duplicate of above (same bug basically).

**Closed by KoBeWi** 2021-01-11 00:33 UTC
Labels: bug, topic:editor
