### ISSUE TITLE
Area2D doesn't detect bodies when "Monitorable" property is set to false

### ISSUE THREAD

**Issue by Paar86** [godotengine/godot#86327] opened 2023-12-19 12:38 UTC
### Tested versions

Release 4.2.1

### System information

Godot v4.2.1.stable - Windows 10.0.22621 - Vulkan (Forward+) - integrated AMD Radeon (TM) Graphics (Advanced Micro Devices, Inc.; 31.0.12034.4) - AMD Ryzen 5 5625U with Radeon Graphics (12 Threads)

### Issue description

When Area2D has the property "Monitorable" set to false, it stops detecting PhysicsBody2D objects, even though this property should only make the area invisible to other areas, at least according to documentation.

### Steps to reproduce

In the attached project, hold the "right" key to move Area2D object until it collides with StaticBody2D object (make sure collision shapes are visible). In the output window there should be a log entry "Overlapping: true".
Set "Monitorable" property on the Area2D object to "false" and do the same. Body entered signal no longer triggers.

### Minimal reproduction project (MRP)

[Area_Monitorable_Bug.zip](https://github.com/godotengine/godot/files/13715622/Area_Monitorable_Bug.zip)

**Comment by AThousandShips** [comment] 2023-12-19 12:55
Duplicate of https://github.com/godotengine/godot/issues/17238

**Closed by AThousandShips** 2023-12-19 12:55 UTC
Labels: bug, confirmed, topic:physics, topic:2d
