### ISSUE TITLE
Lightmap crash when baking with high texel density 

### ISSUE THREAD

**Issue by jcostello** [godotengine/godot#64401] opened 2022-08-14 19:59 UTC
### Godot version

v4.0.alpha.custom_build [9a3940bc6]

### System information

Ubuntu 21.04. RTX 2060

### Issue description

When baking the lightmap with high texel density, the engine crash. 

```
Engine version: Godot Engine v4.0.alpha.custom_build (9a3940bc609cac8e6c0bc6f3d1f4fbd84940caa6)
Dumping the backtrace. Please include this when reporting the bug to the project developer.
[1] /lib/x86_64-linux-gnu/libc.so.6(+0x41040) [0x7fbd905ed040] (??:0)
[2] /lib/x86_64-linux-gnu/libc.so.6(+0x1833b1) [0x7fbd9072f3b1] (??:0)
[3] Image::create(int, int, bool, Image::Format) (??:0)
[4] LightmapperRD::_blit_meshes_into_atlas(int, Vector<Ref<Image> >&, Vector<Ref<Image> >&, AABB&, Vector2i&, int&, bool (*)(float, String const&, void*, bool), void*) (??:0)
[5] LightmapperRD::bake(Lightmapper::BakeQuality, bool, int, float, int, bool, Lightmapper::GenerateProbes, Ref<Image> const&, Basis const&, bool (*)(float, String const&, void*, bool), void*) (??:0)
[6] LightmapGI::bake(Node*, String, bool (*)(float, String const&, void*, bool), void*) (??:0)
[7] LightmapGIEditorPlugin::_bake_select_file(String const&) (??:0)
[8] void call_with_variant_args_helper<LightmapGIEditorPlugin, String const&, 0ul>(LightmapGIEditorPlugin*, void (LightmapGIEditorPlugin::*)(String const&), Variant const**, Callable::CallError&, IndexSequence<0ul>) (??:0)
[9] void call_with_variant_args<LightmapGIEditorPlugin, String const&>(LightmapGIEditorPlugin*, void (LightmapGIEditorPlugin::*)(String const&), Variant const**, int, Callable::CallError&) (??:0)
[10] CallableCustomMethodPointer<LightmapGIEditorPlugin, String const&>::call(Variant const**, int, Variant&, Callable::CallError&) const (??:0)
[11] Callable::callp(Variant const**, int, Variant&, Callable::CallError&) const (??:0)
[12] Object::emit_signalp(StringName const&, Variant const**, int) (??:0)
[13] Error Object::emit_signal<String>(StringName const&, String) (??:0)
[14] EditorFileDialog::_action_pressed() (??:0)
[15] void call_with_variant_args_helper<EditorFileDialog>(EditorFileDialog*, void (EditorFileDialog::*)(), Variant const**, Callable::CallError&, IndexSequence<>) (??:0)
[16] void call_with_variant_args<EditorFileDialog>(EditorFileDialog*, void (EditorFileDialog::*)(), Variant const**, int, Callable::CallError&) (??:0)
[17] CallableCustomMethodPointer<EditorFileDialog>::call(Variant const**, int, Variant&, Callable::CallError&) const (??:0)
[18] Callable::callp(Variant const**, int, Variant&, Callable::CallError&) const (??:0)
[19] Object::emit_signalp(StringName const&, Variant const**, int) (??:0)
[20] Error Object::emit_signal<>(StringName const&) (??:0)
[21] AcceptDialog::_ok_pressed() (??:0)
[22] void call_with_variant_args_helper<AcceptDialog>(AcceptDialog*, void (AcceptDialog::*)(), Variant const**, Callable::CallError&, IndexSequence<>) (??:0)
[23] void call_with_variant_args<AcceptDialog>(AcceptDialog*, void (AcceptDialog::*)(), Variant const**, int, Callable::CallError&) (??:0)
[24] CallableCustomMethodPointer<AcceptDialog>::call(Variant const**, int, Variant&, Callable::CallError&) const (??:0)
[25] Callable::callp(Variant const**, int, Variant&, Callable::CallError&) const (??:0)
[26] Object::emit_signalp(StringName const&, Variant const**, int) (??:0)
[27] Error Object::emit_signal<>(StringName const&) (??:0)
[28] BaseButton::_pressed() (??:0)
[29] BaseButton::on_action_event(Ref<InputEvent>) (??:0)
[30] BaseButton::gui_input(Ref<InputEvent> const&) (??:0)
[31] Control::_call_gui_input(Ref<InputEvent> const&) (??:0)
[32] Viewport::_gui_call_input(Control*, Ref<InputEvent> const&) (??:0)
[33] Viewport::_gui_input_event(Ref<InputEvent>) (??:0)
[34] Viewport::push_input(Ref<InputEvent> const&, bool) (??:0)
[35] Window::_window_input(Ref<InputEvent> const&) (??:0)
[36] void call_with_variant_args_helper<Window, Ref<InputEvent> const&, 0ul>(Window*, void (Window::*)(Ref<InputEvent> const&), Variant const**, Callable::CallError&, IndexSequence<0ul>) (??:0)
[37] void call_with_variant_args<Window, Ref<InputEvent> const&>(Window*, void (Window::*)(Ref<InputEvent> const&), Variant const**, int, Callable::CallError&) (??:0)
[38] CallableCustomMethodPointer<Window, Ref<InputEvent> const&>::call(Variant const**, int, Variant&, Callable::CallError&) const (??:0)
[39] Callable::callp(Variant const**, int, Variant&, Callable::CallError&) const (??:0)
[40] DisplayServerX11::_dispatch_input_event(Ref<InputEvent> const&) (??:0)
[41] DisplayServerX11::_dispatch_input_events(Ref<InputEvent> const&) (??:0)
[42] Input::_parse_input_event_impl(Ref<InputEvent> const&, bool) (??:0)
[43] Input::flush_buffered_events() (??:0)
[44] DisplayServerX11::process_events() (??:0)
[45] OS_LinuxBSD::run() (??:0)
[46] /home/juan/dev/godot/bin/godot.linuxbsd.tools.64(main+0x17f) [0x563c990bd5b8] (??:0)
[47] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xd5) [0x7fbd905d4565] (??:0)
[48] /home/juan/dev/godot/bin/godot.linuxbsd.tools.64(_start+0x2e) [0x563c990bd37e] (??:0)
-- END OF BACKTRACE --
```

### Steps to reproduce

Bake Test scene from MRP

### Minimal reproduction project

[Lightmap.zip](https://github.com/godotengine/godot/files/9334019/Lightmap.zip)

**Comment by Calinou** [comment] 2022-08-14 21:40
Duplicate of https://github.com/godotengine/godot/issues/54679.

**Closed by Calinou** 2022-08-14 21:40 UTC
