### ISSUE TITLE
Vulkan: Error spam while running project `VulkanContext::swap_buffers: Condition "err" is true. Returning: ERR_CANT_CREATE`

### ISSUE THREAD

**Issue by INdIEDeV016** [godotengine/godot#59699] opened 2022-03-30 17:13 UTC
### Godot version

v4.0.alpha.custom_build [118f29694]

### System information

Windows 10, Vulkan Clustered, NVIDIA GeForce GT 1030

### Issue description

This error occurs randomly while running my game. And freezes project just like other issues out there, but in my case I am not sure what causes it. No overlay software is used. It doesn't crash on startup, but while running the project. Not sure what causes it! Best guess: CPU intensive tasks such as adding many `CanvasItem` nodes (`Node2D` or `Control` Nodes) to `SceneTree` at once and it generally happens for relatively complex and big projects. So, can't make a reproduction project for now.

![image](https://user-images.githubusercontent.com/80198819/160892457-7b38dfa9-a914-45e8-909a-48be75356e63.png)
 
And it has been occurring for me even before alpha releases.

### Steps to reproduce

Not sure. Quite random. Or mostly when some CPU intensive tasks such as adding many `CanvasItem` nodes (`Node2D` or `Control` Nodes) to `SceneTree` at once.

### Minimal reproduction project

N/A

**Comment by Calinou** [comment] 2022-03-30 20:33
Related to https://github.com/godotengine/godot/issues/45725.

As per https://github.com/godotengine/godot/issues/45725#issuecomment-1016252446, did you update your NVIDIA driver to 511.23 or newer?

**Comment by INdIEDeV016** [comment] 2022-03-31 06:51
Yes it seems!
![image](https://user-images.githubusercontent.com/80198819/160994039-3ec29b21-274c-4fbf-9733-8ed3dcbd5264.png)

**Comment by AndersonDeMatos** [comment] 2022-04-17 22:55
this also happened to me, in two different situations. But I can't reproduce this error intentionally.
The first time it happened while I was minimizing the debug window of my running project by double clicking on border of the OS window.
The second time when I was scrolling the mouse wheel over a HSlider on the debug window of my project while it was running. 
In both situations the "game" window froze and I had to stop its execution by clicking the stop button on the editor.  
I'm using Pop!_OS 21.10.
![Screenshot from 2022-04-17 19-38-51](https://user-images.githubusercontent.com/72280012/163735200-7c838af5-3f3d-44a2-8915-82d5a13872f3.png)

**Comment by INdIEDeV016** [comment] 2022-04-18 07:32
@AndersonDeMatos Yes, after further testing and close observation, your problems have happened in my project. It seems, there is some unidentified Vulkan 2D rendering.

**Comment by JosephCatrambone** [comment] 2022-08-06 19:05
I seem to be running into this issue, too, on Alpha 13 with hotfix (Godot Engine v4.0.alpha13.official.82811367c).  For me, it happens on nVidia graphics when coming out of system suspension.

```
ERROR: Vulkan: Did not create swapchain successfully.
   at: prepare_buffers (drivers/vulkan/vulkan_context.cpp:2048)
ERROR: Condition "err" is true. Returning: ERR_CANT_CREATE
   at: swap_buffers (drivers/vulkan/vulkan_context.cpp:2125)
```

Startup logs:
```
Godot Engine v4.0.alpha13.official.82811367c - https://godotengine.org                                                                         
MESA-INTEL: warning: Performance support disabled, consider sysctl dev.i915.perf_stream_paranoid=0                                      
                                                                                                                                               Vulkan API 1.2.131 - Using Vulkan Device #1: NVIDIA - NVIDIA GeForce GTX 1050 Ti with Max-Q Design
```

**Comment by Calinou** [comment] 2022-08-07 05:59
@JosephCatrambone Can you reproduce this with other games or applications using Vulkan? Suspend on Linux is notoriously buggy with graphics drivers, especially with the proprietary NVIDIA driver.

**Comment by codespren** [comment] 2022-09-30 14:17
I received this same error in Godot 4 Beta 1 when I zoomed close to meshInstance ingame. The meshInstance had a shader material with many if-clauses. I changed the shader logic so that there were less ifs and the error went away.

Now I updated to Godot 4 Beta 2 and error occurs immediately when I run the project even if I disable the problematic shader. I tried to start a new, empty project and it seems to work fine.

macOs Monterey 12.6, AMD Radeon Pro 5500M

![image](https://user-images.githubusercontent.com/17741903/193287772-6fd4e73a-a9cc-4057-9260-c7a1b3ecb95a.png)

**Comment by darksylinc** [comment] 2023-08-19 18:03
Hi!

Could you test [this version](https://github.com/godotengine/godot/pull/80566#issuecomment-1685026683) to see if you can still repro the problem? Thanks.

**Comment by JosephCatrambone** [comment] 2023-08-21 19:54
It's been a year or so and my machine's drivers have likely updated since then, but I think I can try some night this week.

**Comment by INdIEDeV016** [comment] 2023-08-23 21:09
I don't know which commit might have resolved the issue, but there are no more random swapchain errors and crashes anymore.

**Comment by Calinou** [comment] 2023-08-23 21:25
Closing in favor of https://github.com/godotengine/godot/issues/71929.

**Closed by Calinou** 2023-08-23 21:25 UTC
Labels: bug, platform:windows, topic:rendering, needs testing
