### ISSUE TITLE
pass string as parameter? C ++ module

### ISSUE THREAD

**Issue by PerduGames** [godotengine/godot#9806] opened 2017-07-24 05:20 UTC
If I can not have "const char *" parameters in the functions, how would I do if I need to pass a string as a parameter?

Example:

#In my.h

`myFunction(const char *s, int i=0);`

#In my.cpp

```
MyClass::myFunction(const char *s, int i)
{
//Here you would use the parameters
}
```

#Calling myFunction with gd script:

`myFunction("I exist?", 2)
`

**Comment by Noshyaar** [comment] 2017-07-24 05:27
Have you tried `myFunction(String s, ...)`?

**Comment by PerduGames** [comment] 2017-07-24 05:29
yes, Also does not work

**Comment by Noshyaar** [comment] 2017-07-24 05:32
Try adapting from label set_text
`void Label::set_text(const String &p_string) {`

```
void Label::_bind_methods() {
    ClassDB::bind_method(D_METHOD("set_text", "text"), &Label::set_text);
    ClassDB::bind_method(D_METHOD("get_text"), &Label::get_text);

    ADD_PROPERTYNZ(PropertyInfo(Variant::STRING, "text", PROPERTY_HINT_MULTILINE_TEXT, "", PROPERTY_USAGE_DEFAULT_INTL), "set_text", "get_text");
```

**Comment by PerduGames** [comment] 2017-07-24 05:38
I will try here

But what have you done in this line?

`ADD_PROPERTYNZ(PropertyInfo(Variant::STRING, "text", PROPERTY_HINT_MULTILINE_TEXT, "", PROPERTY_USAGE_DEFAULT_INTL), "set_text", "get_text");
`

**Comment by Noshyaar** [comment] 2017-07-24 05:39
It's for property. If your method isn't setter or getter, just ignore it.

**Comment by PerduGames** [comment] 2017-07-24 05:43
But I still can not understand why I can not pass a "const char *", what happens?

**Comment by Noshyaar** [comment] 2017-07-24 05:49
This is where String is defined https://github.com/godotengine/godot/blob/master/core/ustring.h
If I understand correctly, it has more features, like unicode support etc. GDScript uses String (Variant). You can convert char * to String, but not the other way around.

**Comment by PerduGames** [comment] 2017-07-24 05:56
But I can convert string to char *:

```
string s = "my string";
char *my_char = new char[s.length()+1];
memcpy(my_char, s.c_str(), s.length() + 1);
```

**Comment by Noshyaar** [comment] 2017-07-24 05:57
Godot String != string

**Comment by PerduGames** [comment] 2017-07-24 06:00
I understand, I thought I was talking about c ++ XD I'll sleep, tomorrow I'll try with string, and more, thanks for the help

**Comment by marcelofg55** [comment] 2017-07-24 13:18
Use String, I've used it on a module and it works fine, you can check it here for reference: [oamlGodotModule](https://github.com/oamldev/oamlGodotModule)

**Comment by PerduGames** [comment] 2017-07-24 16:07
I do not understand how you're using string without including any godot file for this, or do you just need the "reference"?

**Comment by marcelofg55** [comment] 2017-07-24 17:54
Yeah, just include "reference.h" and then you can use String, and to convert to const char * use .ascii()

**Comment by PerduGames** [comment] 2017-07-24 18:04
That's what I needed. Compiling here now. I thank you.

**Comment by PerduGames** [comment] 2017-07-24 18:44
I am getting "undefined reference to" for Enet functions, am I doing it correctly on my SCsub?

```
# SCsub
Import('env')

module_env = env.Clone()
module_env.add_source_files(env.modules_sources,"*.cpp")
module_env.Append(CXXFLAGS='-lenet')
```

**Comment by akien-mga** [comment] 2017-07-24 18:47
The last line hould be `module_env.Append(LIBS=['enet'])`

**Comment by PerduGames** [comment] 2017-07-24 18:51
I have changed and I continue to receive the same.

**Comment by marcelofg55** [comment] 2017-07-24 19:42
Try this patch, it compiled fine for me now.
[compile.patch.zip](https://github.com/godotengine/godot/files/1170993/compile.patch.zip)

**Comment by PerduGames** [comment] 2017-07-24 20:18
Thank you, compiled, but this is not necessary:

```
-void unregister_simplep2p_types () {
+ Void unregister_SimpleP2P_types () {
```

Because the name of my folder is in tiny anyway.

**Comment by PerduGames** [comment] 2017-07-24 20:48
I try to do this:

`var simple = SimpleP2P.new()
`
But I get this error:

```
SCRIPT ERROR: GDScript::reload: Compile Error: Identifier not found: SimpleP2P
   At: built-in:6.
ERROR: reload: Method/Function Failed, returning: ERR_COMPILATION_FAILED
   At: modules/gdscript/gd_script.cpp:522.
```

By clicking the button:

```
ERROR: emit_signal: Error calling method from signal 'pressed': 'Button::_on_Button_pressed': Method not found.
   At: core/object.cpp:1162.
```

If it says "var simple = SimpleP2P.new ()" the button works, when otherwise I get this error. This is happening when I try to compile into other modules as well.

But the error only appears when I export, when text in the editor works normally.

**Comment by marcelofg55** [comment] 2017-07-24 20:55
That's because you have to compile the export templates with the custom module. The default godot export templates don't have the module you're trying to use.

**Comment by PerduGames** [comment] 2017-07-24 20:58
I do not understand, but if I compiled godot, I thought it included my module. That's at least what I understood in the documentation.

**Comment by marcelofg55** [comment] 2017-07-24 21:02
You compiled the godot editor not the godot export templates, you have manually compile the export templates you need to use and then replace the default ones. This is always needed when you add a custom c++ module. If you're using Windows read this: http://docs.godotengine.org/en/stable/development/compiling/compiling_for_windows.html#creating-windows-export-templates

**Comment by PerduGames** [comment] 2017-07-24 21:03
I'm debian, I'll see here.

**Comment by marcelofg55** [comment] 2017-07-24 21:08
This link then: http://docs.godotengine.org/en/stable/development/compiling/compiling_for_x11.html#building-export-templates

**Comment by PerduGames** [comment] 2017-07-24 21:20
I think I understood, I have to compile the editor, compile the export models, open the editor and put the models in the "custom binary", but I'm still a bit confused of what is done, Godot takes all the c ++ and Create a template? Why do I already think and have more than one module?

**Comment by PerduGames** [comment] 2017-07-25 03:45
I saw it here and I'm getting "ERR_ALREADY_IN_USE" when trying to create the client to connect to the server.

**Comment by akien-mga** [comment] 2017-07-25 12:41
Closing as it's not a bug but more a support thread, but feel free to continue discussing :)

**Closed by akien-mga** 2017-07-25 12:41 UTC
