### ISSUE TITLE
[4.0] Inspector shows Node2D.`rotation` in degrees, but hovering on the property says it's in radians.

### ISSUE THREAD

**Issue by Mickeon** [godotengine/godot#64464] opened 2022-08-15 18:14 UTC
### Godot version

v4.0.alpha.custom_build [112721ce9]

### System information

Windows 10

### Issue description

Hovering on the `rotation` of a **Node2D** displays the original property's name and description, which is in **radians**, but the slider in the editor is clearly expressed in **degrees**.

![image](https://user-images.githubusercontent.com/66727710/184691849-363474bd-c739-49d4-96f4-b68476b8dc5b.png)

This doesn't occur in Godot 3.x because `rotation_degrees` is the property exposed to the Inspector.

Not the worst thing in the world, and it's easy to see why this happens. But... it does happen, and it may be confusing for beginners, who may not know what the difference between radians and degrees even is.

### Steps to reproduce

Open any project, look for any Node2D or inheriting class, then hover on its `rotation` property in the Inspector.

### Minimal reproduction project

No need.

**Comment by kleonc** [comment] 2022-08-15 18:33
Duplicate of #58316.

**Closed** 2022-08-15 18:35 UTC
Labels: archived, topic:editor, documentation, topic:2d
