### ISSUE TITLE
Animation scrubbing broken in rc1

### ISSUE THREAD

**Issue by noidexe** [godotengine/godot#15753] opened 2018-01-15 18:53 UTC
**Godot version:** 3.0-rc1, 702e28f

**OS/device including version:** 
Win 7 64

**Issue description:**
Expected: Scrubbing the timeline in the editor should update the animation
Actual: Nothing happens

**Steps to reproduce:**
- scrub back and forth in any AnimationPlayer node

**Comment by akien-mga** [comment] 2018-01-15 18:56
Duplicate of #15646, fixed in the master branch.

**Closed by akien-mga** 2018-01-15 18:56 UTC
