### ISSUE TITLE
Crash on MacOS after compilation from source.

### ISSUE THREAD

**Issue by Zaphodious** [godotengine/godot#8029] opened 2017-03-14 23:02 UTC
**Operating system or device - Godot version:**
MacOS 10.12.3 - commit 52ddd9ac9cf4074e6461a236808313002b0d83c4

**Issue description:**

After compiling from source, the editor crashed when going to edit a newly created project. The window remains, and the process cannot be force stopped from the Activity Monitor. Expected, would be that the editor loaded the project and shut down properly when closed.

**Steps to reproduce:**
Compile using "scons platform=osx" on a mac running 10.12.3, and run the resulting binary (either 64 or 32 bit). Create a new project, then edit it after its creation.

**Link to gist containing error information:**

https://gist.github.com/Zaphodious/a698002d7a9d37bd75521ca0e73c921b

**Comment by ViktorEvil** [comment] 2017-03-28 18:53
I have exactly the same issue on a 2015 MacBook Air, macOS 10.12.3

**Comment by ViktorEvil** [comment] 2017-03-28 20:25
looks like its related to this issue

[https://github.com/godotengine/godot/issues/7865](url)

resizing the screen sorted the problem

**Comment by Zaphodious** [comment] 2017-03-29 02:09
For the 64 bit version, resizing the window did work! Horray! Getting that binary requires "bits=64", as just running "scons p=osx" spits out the 32-bit version by default... and resizing *that* one doesn't do anything for the hangup.

**Comment by ViktorEvil** [comment] 2017-03-29 08:45
I still get error messages when the project loader closes and when Godot closes but it is just about usable

**Comment by kubecz3k** [comment] 2018-04-10 16:35
First of all thank you for your report and sorry for the delay.

We released Godot 3.0 in January 2018 after 18 months of work, fixing many old issues either directly, or by obsoleting/replacing the features they were referring to.

We still have hundreds of issues whose relevance/reproducibility needs to be checked against the [current stable version](https://godotengine.org/download), and that's where you can help us.
**Could you check if the issue that you described initially is still relevant/reproducible in Godot 3.0 or any newer version, and comment about its current status here?**

For bug reports, please also make sure that the issue contains detailed steps to reproduce the bug and, if possible, a zipped project that can be used to reproduce it right away. This greatly speeds up debugging and bugfixing tasks for our contributors.

Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

Thanks in advance.

*Note: This message is being copy-pasted to many "stale" issues (90+ days without activity). It might happen that it is not meaningful for this specific issue or appears oblivious of the issue's context, if so please comment to notify the Bugsquad about it.*

**Comment by akien-mga** [comment] 2019-04-15 14:23
> Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

As there was no update since the previous post, we close this issue.

If it is still relevant in the way it was described and discussed above, please comment to ask for it to be reevaluated. If it is only partly relevant, or if the original issue has changed, it would be better to open a new issue (potentially referring to this one) focused on the current state.

**Closed by akien-mga** 2019-04-15 14:23 UTC
Labels: bug, platform:osx, topic:porting
