### ISSUE TITLE
Pause Mode set in Inspector Ignored by Autoloaded Scene

### ISSUE THREAD

**Issue by AllenKll** [godotengine/godot#52363] opened 2021-09-02 23:23 UTC
### Godot version

v3.3.3.stable

### System information

Windows 10

### Issue description

Setting the Pause Mode to Process in the inspector for an autoloaded scene is not respected when the application is run.   In the example project, I have set the Globals class to be auto loaded and set the Pause Mode to "Process".  When I run the project, I can look in the remote inspector and see that for the Globals class, the Pause mode is "Inherited" I also have a print out to the Output that verifies this.

Changing the scene from auto load, to instanced in the tree beneath another node, does allow the pause mode to be set via the inspector.

I would expect that setting the pause mode for the autoloaded scene, would cause the pause mode to be the same when the project is run. 

### Steps to reproduce

Open example project.
Verify that the Globals scene's Pause Mode is set to "Process" in the Inspector
Run the example project.
Observe that the output indicates "Node.PAUSE_MODE_INHERIT"  

### Minimal reproduction project

[AutoLoadProcessBug.zip](https://github.com/godotengine/godot/files/7102297/AutoLoadProcessBug.zip)

**Comment by kleonc** [comment] 2021-09-02 23:36
No bug in here, you've added `Globals.gd` script as an AutoLoad, not `Globals.tscn` scene. The Pause Mode you're setting in the inspector is saved in the scene file:
```
[gd_scene load_steps=2 format=2]

[ext_resource path="res://Globals.gd" type="Script" id=1]

[node name="Globals" type="Node"]
pause_mode = 2
script = ExtResource( 1 )
```
Adding the scene as an AutoLoad instead of script makes it work as intended.

From [the docs](https://docs.godotengine.org/en/3.4/getting_started/step_by_step/singletons_autoload.html#autoload):
> When autoloading a script, a Node will be created and the script will be attached to it. This node will be added to the root viewport before any other scenes are loaded.

**Comment by Calinou** [comment] 2021-09-02 23:48
Closing per @kleonc's comment.

**Closed by Calinou** 2021-09-02 23:48 UTC
Labels: bug, topic:core
