### ISSUE TITLE
Autotile ATLAS_TILE shape offset only applies to first tile

### ISSUE THREAD

**Issue by Lodugh** [godotengine/godot#25610] opened 2019-02-04 15:16 UTC
**Godot version:** Godot 3.1-beta11(64bit,Linux)
**OS/device including version:** Linux Mint 19.1(Ubuntu 18.04)
**Issue description:**
The shape_offset is only applied to the first Tile of an AUTO_TILE/ATLAS_TILE and none of the following tiles.

**Steps to reproduce:**
Create a TileMap with a TileSet in it that has an ATLAS_TILE with a shape_offset and multiple tiles(each with collision). Then place the different tiles and look at it with visible collisions.

**Minimal reproduction project:**
[autotile_shape_offset_bug.zip](https://github.com/godotengine/godot/files/2828980/autotile_shape_offset_bug.zip)

EDITED: I looked a bit deeper into it and my first assumption wasn't right. Corrected the issue above.

**Comment by akien-mga** [comment] 2019-02-27 10:20
Ping @MarianoGnu

**Comment by Lodugh** [comment] 2019-03-11 21:35
Was the milestone changed because it is too hard to fix? Because I think priority wise it is a pretty big bug.. At the moment it breaks my game and makes it hardly possible to work on it. 
Just a thought of mine, you probably had your reason.

**Comment by akien-mga** [comment] 2019-03-11 21:52
Not too hard, but too late. It will be fixed after 3.1 and the fix will be included in a 3.1.x release (hopefully 3.1.1 in a couple of weeks).

**Comment by Ranoller** [comment] 2019-05-12 12:07
I test that with my attempt of modifications of tilemap... but i see that the problem is not the tilemap, nor the tileset. Problem is the editor only able to edit first shape, if you edit that manually it works:
![TileSetBug](https://user-images.githubusercontent.com/11712737/57581936-19af3880-74bf-11e9-8b82-0a977afe98a5.png)
So it´s not bug of tilemap or tileset, is only not implemented functionality in tileset editor.

**Comment by Lodugh** [comment] 2019-05-15 21:45
Then I guess it is a quite simple fix?
@MarianoGnu I would be super thankful if it would happen soon! I think its a pretty fatal bug..

**Closed** 2019-08-07 12:27 UTC
Labels: bug, topic:core

**Comment by markopolojorgensen** [comment] 2020-09-29 19:44
I don't think it's worth reopening this, but fyi this still happens in 3.2.3-stable if you create additional tile shapes after setting the shape offset.
Easy workaround is to
1. finish adding all collision shapes
2. set the offset to something else (like 0,0)
3. set it back to what you actually want
I guess this is expected behavior, since the offset is only added to tiles with shapes when the value of the offset is changed, so naturally adding more shapes later means they don't get the offset. It threw me for a loop, though, so I thought I'd document it somewhere.
