### ISSUE TITLE
Using connect_to_url() on a WebSocketClient hangs

### ISSUE THREAD

**Issue by jedStevens** [godotengine/godot#16955] opened 2018-02-23 17:31 UTC
master
b6bf572e021f59ca9f6e95fca2e1cd08bd3fe0f2

Manjaro

Using a WebSocketClient to connect to an `express-ws` Socket hangs the running application.

Trying to connect to a global players list so I can connect clients over P2P to play 1v1.

```
extends Node

var ws = null

var connected_msg = "CON:game"

func _ready():
	ws = WebSocketClient.new()
	ws.connect_to_url("ws://localhost:3000/socket")
	set_process(true)
```

**Steps to reproduce:**
Use this script to create a WebSocketClient and attempt to connect to some socket on port 3000 at path "/socket"

Not sure why this is... do I have to thread this? I'm not advanced enough to fix this if its actually a problem, but would like to see a documented example, there isn't any info on it yet that I could find.

EDIT -------
This client websocket works to connect to my current one, but is written for an `index.html` file and written in JavaScript. Its just accepting messages and building a list of players.

```
var online_count =  0;
var total_count = 0;
var ws = new WebSocket('ws://localhost:3000/socket');

ws.onopen = function(e) {
        ws.send("CON:webpage");
};

ws.onmessage = function(e){
        var type = e.data.substring(0,3);
        if (type == "SPC"){
                total_count = e.data.substring(4);
                setTotalCount();
        }
        else if (type == "SOC"){
                online_count = e.data.substring(4);
                setOnlineCount();
        }
        else if (type == "ADD"){
                var data = e.data.substring(4);
                var args = data.split(" ");
                console.log("ADD PLAYER: ", args[0], parseInt(args[1]));
                var status = parseInt(args[1]) == 1 ? "In Game" : "Online";
                addTableRow(args[0], status);
        }
};


function setTotalCount(){
        document.getElementById('player-count').innerHTML = total_count;
};
function setOnlineCount(){
        document.getElementById('in-game-count').innerHTML = online_count;
};

function addTableRow(username, status){
        var table = document.getElementById("player-list");

        var row = table.insertRow(-1);

        var username_cell = row.insertCell(0);
        var status_cell   = row.insertCell(1);

        username_cell.innerHTML = username;
        status_cell.innerHTML = status;
};

```

**Comment by girng** [comment] 2018-02-24 22:51
cc @Faless can take a look

**Comment by Faless** [comment] 2018-02-27 10:30
@jedStevens sounds strange, what you are doing seems correct, in fact, testing with an echo server works fine.

e.g.:
```
extends Node

var ws = null

func _ready():
	ws = WebSocketClient.new()
	ws.connect_to_url("ws://echo.websocket.org")

```

What do you mean exactly by "hangs"? Does the game freezes completely? Do you have some server log? Does it tries to connect at all?

**Comment by jedStevens** [comment] 2018-02-27 11:33
Since its in the ready function, the game window freezes on the splash screen. It hangs and never boots to the real game. It freezes no matter where I put it

**Comment by Faless** [comment] 2018-03-29 22:26
> var ws = new WebSocket('ws://localhost:3000/socket');

I'm unable to reproduce the bug.

It seems to work fine for me with `express-ws` using the following test.
[ws_test.zip](https://github.com/godotengine/godot/files/1862129/ws_test.zip)

Can you provide the full code (both client and server) to reproduce the issue?

**Comment by jedStevens** [comment] 2018-03-29 22:28
I can attempt again in a few hours

**Comment by Faless** [comment] 2018-03-29 22:29
> I can attempt again in a few hours

Also check out the demo in the zip I sent and let me know

**Comment by mhilbrunner** [comment] 2018-04-04 18:24
@jedStevens Did you fix it/find the issue or is this still an issue?

**Comment by joaopedrosgs** [comment] 2018-08-10 00:54
same here, but instead of hanging, it just crashes after connection
backtrace:
[backtrace.log](https://github.com/godotengine/godot/files/2276256/backtrace.log)

**Comment by joaopedrosgs** [comment] 2018-08-10 01:00
i tried the demo in the zip and it crashes here
[backtrace.log](https://github.com/godotengine/godot/files/2276265/backtrace.log)

**Comment by Faless** [comment] 2018-08-30 19:14
I'm still unable to reproduce.
I'm closing this as it seems fixed, but feel free to comment/reopen if you are still experiencing this issue.

**Closed by Faless** 2018-08-30 19:14 UTC
Labels: bug, topic:network
