### ISSUE TITLE
Pick tile shortcut on macOS

### ISSUE THREAD

**Issue by k7771911** [godotengine/godot#19496] opened 2018-06-10 19:27 UTC
**Godot version:** 3.0.3.RC3

**OS/device including version:** macOS High Sierra

**Issue description:**

The "Pick Tile" shortcut is Control-Click which on macOS registers as a right click and deletes the tile instead of picking it. The Shortcuts configuration does not seem to include any option to change the key.

**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by k7771911** [comment] 2018-06-10 22:20
@vnen that should be the behavior indeed but it looks like the macOS shortcuts are not configured correctly.

**Comment by akien-mga** [comment] 2018-06-11 05:27
Duplicate of #10761.

**Closed by akien-mga** 2018-06-11 05:27 UTC
Labels: bug, platform:osx, topic:editor
