### ISSUE TITLE
iOS Magenta color on startup

### ISSUE THREAD

**Issue by canvasbushi** [godotengine/godot#28247] opened 2019-04-20 21:21 UTC
**Godot version:**
3.1

**OS/device including version:**
iOS 10+

**Issue description:**
I'm seeing a magenta colored screen(instead of black which is my clear color) on startup.
I started seeing this problem after changing from GLES3 to GLES2.

**Steps to reproduce:**
Gles2 Godot 3.1 iOS export.

**Minimal reproduction project:**

**Comment by andy-noisyduck** [comment] 2020-07-13 23:28
This is still an issue (a year later) on 3.2.2. Big pink screen whilst app is loading on iOS (GLES2).

**Comment by canvasbushi** [comment] 2020-07-14 00:36
> This is still an issue (a year later) on 3.2.2. Big pink screen whilst app is loading on iOS (GLES2).

I only came back to check if randy savage really replied to my topic...
Think the fix had something to do with rendering > environment > default_env.tres - you had to delete it?

however the lesson here is godot doesn't care much about integration or support like other game engines like unity/unreal engine.
PS: if you think that this is bad, wait til you get to creating modules for monetization and analytics, you think it would be build in or easy to use.
PS PS: next youll see weird messages like some people creating ad modules that take some of your revenue. O.O!!!

**Comment by andy-noisyduck** [comment] 2020-07-14 00:52
> Think the fix had something to do with rendering > environment > default_env.tres - you had to delete it?

Alas, I do not have a default environment to delete.

> however the lesson here is godot doesn't care much about integration or support like other game engines like unity/unreal engine.

My experience is that new features and platform support are slowly being added, but that bug reports sit there for years and never get fixed. I have a number open myself. Still, let's try keep the info here relative to the issue.

**Comment by akien-mga** [comment] 2020-07-14 06:11
@canvasbushi Only a small fraction of Godot contributors have access to Apple hardware, especially devices running iOS, and an even smaller fraction of those has any knowledge of mobile rendering (actually, it's near 0). So yes, some bugs can take a long time to be addressed if there's nobody that can debug or fix them.

**Comment by andy-noisyduck** [comment] 2020-07-14 11:52
> @canvasbushi Only a small fraction of Godot contributors have access to Apple hardware

If it helps, the bug is present when using the Simulator too.

**Comment by volzhs** [comment] 2020-07-14 12:40
I also have a project that runs on GLES2 but could not reproduce and don't have feedback about it.
is your project for 3D?

**Comment by canvasbushi** [comment] 2020-07-14 20:17
the fastest way to fix this, would be for you to upload your project/project settings.
alot of issues are often caused due to bad configuration like multi-threaded rendering/physics, default_env.tres causing a magenta screen on ios, etc. check your rendering tab.

![image](https://user-images.githubusercontent.com/49125185/87471866-a6ceaf80-c5e4-11ea-916c-7b063908077a.png)

also, you might need export to xcode again to see changes in the project settings.

**Comment by andy-noisyduck** [comment] 2020-07-16 16:10
> I also have a project that runs on iOS with GLES2 but could not reproduce and don't have feedback about it.
> is your project for 3D?

2D, but I can replicate this with a new empty project in 3.2.2 (so long as GLES2 is set). The splash never shows (including the Godot default splash), and where the splash should be is a bright pink/magenta screen. The issue is not present when using GLES3.

I'm testing against iOS 13.6 via the Xcode Simulator (though 13.5 also had the same issue). I was able to replicate the issue both with and without Mono. I do not have a modern physical device to check against.

Removing the default environment has no effect on the bug for me.

**Comment by Calinou** [comment] 2022-08-06 03:25
@canvasbushi Can you (or anyone else) still reproduce this bug in [Godot 3.4.4](https://godotengine.org/article/maintenance-release-godot-3-4-4) or any later release?

If yes, please ensure that an up-to-date Minimal Reproduction Project (MRP) is included in this report (a MRP is a zipped Godot project with the minimal elements necessary to reliably trigger the bug). You can upload ZIP files in an issue comment with a drag and drop.

**Comment by andy-noisyduck** [comment] 2022-08-08 14:02
@Calinou I tried repeating these steps in 3.5 but I could no longer reproduce the issue.

**Comment by Calinou** [comment] 2022-08-08 17:21
Thanks for replying :slightly_smiling_face: Closing then.

**Closed by Calinou** 2022-08-08 17:21 UTC
Labels: bug, platform:ios, topic:rendering, confirmed
