### ISSUE TITLE
Default shadow bias is too low for SpotLights

### ISSUE THREAD

**Issue by ghost** [godotengine/godot#16787] opened 2018-02-17 23:11 UTC
Same problem as #12028 but gonna post this since that thread(?) seems to be quite dead.
**Godot version:**
3.0 stable

**OS/device including version:**
Windows 7 x64 Professional with 16GB of RAM
Intel HD 4000 with newest drivers (Version: 15.33.46.4885 Date: 1/3/2018)

**Issue description:**
1. Any spotlight with shadows enabled causes stripes to appear on the lighting.
Both spotlights in the image above are at default settings, except for the one with shadows on.
![image](https://user-images.githubusercontent.com/35950962/36346336-0b7bfffa-1480-11e8-86d6-ed6e6105ea29.png)
Zoomed up:
![image](https://user-images.githubusercontent.com/35950962/36346355-5a6a378a-1480-11e8-9795-cbe8c3af2de4.png)

2. Directional light with "Max Distance" of over 500 starts to show same issues as spotlights
Max Distance set at 500. Stripes are barely visible but are there.
![image](https://user-images.githubusercontent.com/35950962/36346427-cd9a79b2-1481-11e8-94e1-166c4bb668c6.png)
This effect maxes out at around 1000 which doesn't change no matter high you set the Max Distance at.
![image](https://user-images.githubusercontent.com/35950962/36346457-4aa6c7ee-1482-11e8-85a7-62d7a9b3689d.png)

**Minimal reproduction project:**

Two scenes are included; one with spotlights and one with a directional light.
[shadowbug.zip](https://github.com/godotengine/godot/files/1734245/shadowbug.zip)

**Comment by Anutrix** [comment] 2018-02-18 13:23
Young's double slit experiment

**Comment by eon-s** [comment] 2018-02-19 00:57
In spotlight, this is the limit of shadow bias, if light is parallel to the surface there is no way to get rid of the strips (increase the bias to 1 and rotate it -0.5 degree on X and stripes start to disappear), not sure if is a bias bug, need a hack to work in this setup or what.

The directional light issue may be a different one, related to intel gpu because I do not see it with nvidia proprietary on linux (search issues mentioning intel graphics).

**Comment by reduz** [comment] 2018-02-19 10:58
I still think someone with a bit more experience should take a look at the
shadow code.. I have the feeling I am missing something else to avoid these

**Comment by DEF7** [comment] 2018-04-14 03:38
This is a normal part of shadowmapping called "shadow acne", it's caused the same way as z-fighting. This is what the bias values are for: so devs can tweak individual lights in their projects to minimize it. Reduce your shadow distance to the absolute lowest possible value you can get away with in your scene, and tweak the bias/contact values. Another tip is to enable reverse culling, which shadows using backfaces instead of front-faces.

The tricky part is making sure your shadows are properly casting (as well as one can manage) from objects/surfaces that are extremely close to shadowed surfaces - because increasing bias to differentiate between a surface and its own shadow also causes objects near that surface to lose their shadow if they're closer than the bias value (aka 'peter-panning').

**Comment by reduz** [comment] 2018-09-06 20:00
I don't think this is a bug, but will see how it remains in 3.2

**Comment by Toshiwoz** [comment] 2019-03-13 23:23
In just releaser Godot 3.1 stable version I noticed that too, strange thing is that I didn't notice that in the first alphas. Has some default value changed?

**Comment by akien-mga** [comment] 2019-12-13 23:40
I could reproduce the issue with spotlights in the MRP in the current master branch, but not with directional lights.

**Comment by eon-s** [comment] 2019-12-15 18:30
With directional lights, I can see the strips when the camera is far from the surface (almost max zoom out on the editor).
With the spotlights, the strips disappear when I enable the "reverse cull face" option on shadow section (I have no idea of what it does because there is no description).

Using Godot 3.2b, AMD R5.

**Comment by Calinou** [comment] 2019-12-15 19:35
> With directional lights, I can see the strips when the camera is far from the surface (almost max zoom out on the editor).

This is due to shadow bias. You can increase Normal Bias or Bias Split Scale (the latter will only impact far-away splits, not the closest split).

**Comment by Calinou** [comment] 2021-07-02 17:36
Duplicate of https://github.com/godotengine/godot/issues/12028.

**Closed by Calinou** 2021-07-02 17:36 UTC
Labels: bug, topic:3d, topic:rendering
