### ISSUE TITLE
Editor freezes when changing tileset's Texture Region Size

### ISSUE THREAD

**Issue by fishclaws** [godotengine/godot#68135] opened 2022-11-01 18:39 UTC
### Godot version

v4.0.beta3

### System information

Windows 10

### Issue description

When opening a tileset and increasing the Texture Region Size the UI freezes and the logs loop forever saying: 
ERROR: UndoRedo history mismatch: expected 0, got 2.

### Steps to reproduce

Open an existing tileset and try increasing the texture region size

**Comment by melek** [comment] 2023-02-02 06:21
I got this error today. If I don't generate tiles when changing the texture I can change it, otherwise the error occurs and Godot crashes:

```
ERROR: UndoRedo history mismatch: expected 0, got 6.
   at: (editor/editor_undo_redo_manager.cpp:108)
```

Godot 4.0b16
Windows 10 Pro 19044.2486

**Comment by silenuz** [comment] 2023-02-23 15:41
This happens in RC 3 as well on both Linux and Windows systems for me (Mono Version)

if when I add the spritesheet to the tileset I choose to automatically create tiles in the atlas it results in the Godot editor becoming locked and unusable if I change the region.x or region.y by any large amount.

![spritesheet-test-one](https://user-images.githubusercontent.com/13521146/220948073-74cbf1c7-c8f7-4008-bc63-cb0a41a21c41.gif)

If i choose not to automatically create the tiles, I can change the region size without crashing the editor however it still results in the same error messages, only this time just once for each change:

![spritesheet-test-two](https://user-images.githubusercontent.com/13521146/220951358-d369296e-9fe1-402d-a308-2e1aa8aa0c20.gif)

At first I thought it might be a message per pixel step in size, however sometimes a single step results in a multitude of error messages.

![spritesheet-test-three](https://user-images.githubusercontent.com/13521146/220956024-6b4c223d-fdfa-4a97-b6ff-7d7b3482435b.gif)

**Comment by KoBeWi** [comment] 2023-02-25 00:48
Related to #73603
Likely same issue, but this one seems to apply to multiple tiles at once, hence greater spam and potential freezes.

**Comment by YuriSizov** [comment] 2023-06-26 12:26
While this report came before, I'm going to close it as a duplicate of https://github.com/godotengine/godot/issues/74594, which has seen activity recently. Thanks for your contribution nonetheless, this is just consolidating things.

**Closed by YuriSizov** 2023-06-26 12:26 UTC
Labels: bug, topic:editor, topic:2d
