### ISSUE TITLE
Cross-Compile Linking Error w/ Threads

### ISSUE THREAD

**Issue by WinterSnake** [godotengine/godot#54731] opened 2021-11-07 17:37 UTC
### Godot version

4.0.dev

### System information

Arch Linux, Ryzen 9 3950x

### Issue description

Compiling master branch for Windows from Linux results in linking errors.
Compiled with: `x86_64-w64-mingw32-gcc (GCC) 11.2.0`
Command being ran: `scons jobs=32 arch=x86_64 bits=64 platform=windows tools=no target=release`
```
scons: Reading SConscript files ...
Configuring for Windows: target=release, bits=64
Using MinGW
Checking for C header file mntent.h... no
scons: done reading SConscript files.
scons: Building targets ...
Linking Program        ==> bin/godot.windows.opt.x86_64.exe
main/libmain.windows.opt.x86_64.a(main.windows.opt.x86_64.o): in function `Thread::get_caller_id()':
~/development/cpp/assets/engines/Godot/./core/os/thread.h:96:(.text+0x1358): relocation truncated to fit: IMAGE_REL_AMD64_REL32 against undefined symbol `TLS init function for Thread::caller_id'
~/development/cpp/assets/engines/Godot/./core/os/thread.h:96:(.text+0x1362): relocation truncated to fit: IMAGE_REL_AMD64_REL32 against undefined symbol `TLS init function for Thread::caller_id'
~/development/cpp/assets/engines/Godot/./core/os/thread.h:96:(.text$_ZN22RenderingServerDefault22global_variables_clearEv[_ZN22RenderingServerDefault22global_variables_clearEv]+0x19): relocation truncated to fit: IMAGE_REL_AMD64_REL32 against undefined symbol `TLS init function for Thread::caller_id'
~/development/cpp/assets/engines/Godot/./core/os/thread.h:96:(.text$_ZN22RenderingServerDefault22global_variables_clearEv[_ZN22RenderingServerDefault22global_variables_clearEv]+0x26): relocation truncated to fit: IMAGE_REL_AMD64_REL32 against undefined symbol `TLS init function for Thread::caller_id'
modules/libmodule_visual_script.windows.opt.x86_64.a(visual_script.windows.opt.x86_64.o): in function `Thread::get_caller_id()':
~/development/cpp/assets/engines/Godot/./core/os/thread.h:96:(.text+0xbef5): relocation truncated to fit: IMAGE_REL_AMD64_REL32 against undefined symbol `TLS init function for Thread::caller_id'
~/development/cpp/assets/engines/Godot/./core/os/thread.h:96:(.text+0xbeff): relocation truncated to fit: IMAGE_REL_AMD64_REL32 against undefined symbol `TLS init function for Thread::caller_id'
~/development/cpp/assets/engines/Godot/./core/os/thread.h:96:(.text+0xbfa0): relocation truncated to fit: IMAGE_REL_AMD64_REL32 against undefined symbol `TLS init function for Thread::caller_id'
~/development/cpp/assets/engines/Godot/./core/os/thread.h:96:(.text+0xbfaa): relocation truncated to fit: IMAGE_REL_AMD64_REL32 against undefined symbol `TLS init function for Thread::caller_id'
modules/libmodule_gdscript.windows.opt.x86_64.a(gdscript.windows.opt.x86_64.o): in function `Thread::get_caller_id()':
~/development/cpp/assets/engines/Godot/./core/os/thread.h:96:(.text$_ZN16GDScriptLanguage28debug_get_current_stack_infoEv[_ZN16GDScriptLanguage28debug_get_current_stack_infoEv]+0x20): relocation truncated to fit: IMAGE_REL_AMD64_REL32 against undefined symbol `TLS init function for Thread::caller_id'
~/development/cpp/assets/engines/Godot/./core/os/thread.h:96:(.text$_ZN16GDScriptLanguage28debug_get_current_stack_infoEv[_ZN16GDScriptLanguage28debug_get_current_stack_infoEv]+0x30): relocation truncated to fit: IMAGE_REL_AMD64_REL32 against undefined symbol `TLS init function for Thread::caller_id'
modules/libmodule_gdscript.windows.opt.x86_64.a(gdscript_editor.windows.opt.x86_64.o): in function `Thread::get_caller_id()':
~/development/cpp/assets/engines/Godot/./core/os/thread.h:96:(.text+0xb65): additional relocation overflows omitted from the output
collect2: error: ld returned 1 exit status
scons: *** [bin/godot.windows.opt.x86_64.exe] Error 1
scons: building terminated because of errors.
[Time elapsed: 00:00:49.097]
```

Fails somewhere around 75%, can upload full log of compile

### Steps to reproduce

Cross-compile the master branch as per the [docs](https://docs.godotengine.org/en/latest/development/compiling/compiling_for_windows.html#cross-compiling-for-windows-from-other-operating-systems) on Arch Linux.

### Minimal reproduction project

N/A

**Comment by Calinou** [comment] 2021-11-07 18:17
Is your MinGW setup configured to use pthreads? When compiled using MinGW, Godot expects pthreads to be used rather than Win32 threads.

**Comment by WinterSnake** [comment] 2021-11-07 19:28
> Is your MinGW setup configured to use pthreads? When compiled using MinGW, Godot expects pthreads to be used rather than Win32 threads.

It does indeed seem like [MinGW](https://github.com/godotengine/godot/files/7492872/mingw.txt) is setup with pthreads.
```
Target: x86_64-w64-mingw32
Configured with: /build/mingw-w64-gcc/src/gcc/configure --prefix=/usr --libexecdir=/usr/lib --target=x86_64-w64-mingw32 --with-bugurl=https://bugs.archlinux.org/ --enable-languages=c,lto,c++,ada,objc,obj-c++,fortran --enable-shared --enable-static --enable-threads=posix --enable-fully-dynamic-string --enable-libstdcxx-time=yes --enable-libstdcxx-filesystem-ts=yes --with-system-zlib --enable-cloog-backend=isl --enable-lto --enable-libgomp --disable-multilib --enable-checking=release --disable-sjlj-exceptions --with-dwarf2
Thread model: posix
```
> Also, does this occur when compiling the `3.x` branch?

Compiled with `scons jobs=32 bits=64 platform=windows tools=no target=release verbose=yes warnings=no`
[`3.x` branch](https://github.com/godotengine/godot/files/7492943/log.txt) compiles just fine and I can export against it.

In reference, here is the [log](https://github.com/godotengine/godot/files/7492947/log.txt) for the master branch where it errors.
Same command.

**Comment by Ethergeist** [comment] 2021-12-12 06:52
I'm using Arch Linux on a Ryzen 9 3900x, and I got a similar error (although the build went to 100% and it looks like the error happened during linking): "undefined symbol `TLS init function for Thread::caller_id'" - I'm re-running the compile now and capturing the log.

**Comment by Ethergeist** [comment] 2021-12-12 08:16
Here is the log:
[build.log](https://github.com/godotengine/godot/files/7698344/build.log)

**Comment by akien-mga** [comment] 2021-12-12 10:02
Do you have `mingw-w64-winpthreads` installed?

**Comment by Ethergeist** [comment] 2021-12-12 19:25
> Do you have `mingw-w64-winpthreads` installed?

Yes, I have the version from the community repo installed. (There is a -git version on the AUR, but I've not tried that)

**Comment by Ethergeist** [comment] 2021-12-28 23:42
Just some additional info on the error (I just pulled the latest from the repo and did a successful linuxbsd build, then tried the windows build again - both target=release_debug):
` 99%] progress_finish(["progress_finish"], [])
[100%] core/core_constants.cpp: In function 'void register_global_constants()':
core/core_constants.cpp:128:6: note: variable tracking size limit exceeded with '-fvar-tracking-assignments', retrying without
  128 | void register_global_constants() {
      |      ^~~~~~~~~~~~~~~~~~~~~~~~~
core/variant/variant_call.cpp: In function 'void _register_variant_builtin_methods()':
core/variant/variant_call.cpp:1361:13: note: variable tracking size limit exceeded with '-fvar-tracking-assignments', retrying without
 1361 | static void _register_variant_builtin_methods() {
      |             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[100%] Linking Static Library ==> core/libcore.windows.opt.tools.64.a
Ranlib Library         ==> core/libcore.windows.opt.tools.64.a
[100%] Linking Program        ==> bin/godot.windows.opt.tools.64.exe
modules/libmodule_visual_script.windows.opt.tools.64.a(visual_script.windows.opt.tools.64.o): in function `Thread::get_caller_id()':
/home/steve/Projects/godot/./core/os/thread.h:96:(.text+0x91f5): relocation truncated to fit: IMAGE_REL_AMD64_REL32 against undefined symbol `TLS init function for Thread::caller_id'
/home/steve/Projects/godot/./core/os/thread.h:96:(.text+0x91ff): relocation truncated to fit: IMAGE_REL_AMD64_REL32 against undefined symbol `TLS init function for Thread::caller_id'
/home/steve/Projects/godot/./core/os/thread.h:96:(.text+0x92a0): relocation truncated to fit: IMAGE_REL_AMD64_REL32 against undefined symbol `TLS init function for Thread::caller_id'
/home/steve/Projects/godot/./core/os/thread.h:96:(.text+0x92aa): relocation truncated to fit: IMAGE_REL_AMD64_REL32 against undefined symbol `TLS init function for Thread::caller_id'
/home/steve/Projects/godot/./core/os/thread.h:96:(.text+0x1e4ec): relocation truncated to fit: IMAGE_REL_AMD64_REL32 against undefined symbol `TLS init function for Thread::caller_id'
/home/steve/Projects/godot/./core/os/thread.h:96:(.text+0x1e50f): relocation truncated to fit: IMAGE_REL_AMD64_REL32 against undefined symbol `TLS init function for Thread::caller_id'
/home/steve/Projects/godot/./core/os/thread.h:96:(.text+0x1e838): relocation truncated to fit: IMAGE_REL_AMD64_REL32 against undefined symbol `TLS init function for Thread::caller_id'
/home/steve/Projects/godot/./core/os/thread.h:96:(.text+0x1e84e): relocation truncated to fit: IMAGE_REL_AMD64_REL32 against undefined symbol `TLS init function for Thread::caller_id'
/home/steve/Projects/godot/./core/os/thread.h:96:(.text+0x1fc33): relocation truncated to fit: IMAGE_REL_AMD64_REL32 against undefined symbol `TLS init function for Thread::caller_id'
/home/steve/Projects/godot/./core/os/thread.h:96:(.text+0x1fc3d): relocation truncated to fit: IMAGE_REL_AMD64_REL32 against undefined symbol `TLS init function for Thread::caller_id'
modules/libmodule_gdscript.windows.opt.tools.64.a(gdscript.windows.opt.tools.64.o): in function `Thread::get_caller_id()':
/home/steve/Projects/godot/./core/os/thread.h:96:(.text$_ZN16GDScriptLanguage28debug_get_current_stack_infoEv[_ZN16GDScriptLanguage28debug_get_current_stack_infoEv]+0x20): additional relocation overflows omitted from the output
collect2: error: ld returned 1 exit status
scons: *** [bin/godot.windows.opt.tools.64.exe] Error 1
scons: building terminated because of errors.
[Time elapsed: 00:07:10.457]`

I checked my mingw-w64-winpthreads version and it is: 9.0.0-1 (Arch Linux X64)

**Comment by akien-mga** [comment] 2022-02-22 08:45
Duplicate of #52190

**Closed by akien-mga** 2022-02-22 08:45 UTC
Labels: platform:windows, platform:linuxbsd, topic:buildsystem
