### ISSUE TITLE
Glitchy mess when using viewport scaling and gl_compatibility renderer

### ISSUE THREAD

**Issue by ChildishGiant** [godotengine/godot#73294] opened 2023-02-14 15:34 UTC
### Godot version

4.0.rc1

### System information

Linux, gl_compatibility

### Issue description

![image](https://user-images.githubusercontent.com/13716824/218782784-6ee03736-a54a-44fc-86e6-3a737b25b0d9.png)
The outside of the viewport is not cleared or black like with other renders

### Steps to reproduce

Make a new project with the gl_compatiblity renderer and turn `display/window/stretch/mode` to `viewport` or `canvas_items`

### Minimal reproduction project

[Minimum Repro.godot.zip](https://github.com/godotengine/godot/files/10734068/Minimum.Repro.godot.zip)

**Comment by clayjohn** [comment] 2023-02-14 15:38
Duplicate of https://github.com/godotengine/godot/issues/71799

**Closed by clayjohn** 2023-02-14 15:38 UTC
