### ISSUE TITLE
Crash when starting the game on Android 12+

### ISSUE THREAD

**Issue by SkanerSoft** [godotengine/godot#64384] opened 2022-08-14 09:21 UTC
### Godot version

3.5 Stable

### System information

Android 12+

### Issue description

The error occurs when running the game on Android 12 and above.

Players who have reported this cannot conduct full-fledged tests using ADB, that's why I'm attaching reports from Google Play.

I think this is a problem that can be solved. I will try to do it myself by modifying Gradle settings, and if I succeed, I will write a solution here.

The error is related to this:
`android.app.PendingIntent.checkFlags`

Unfortunately, I don't have a device running version 12 of Android, so I'm also asking for help in testing this problem.

Full Stack
```
Exception java.lang.IllegalArgumentException:
  at android.app.PendingIntent.checkFlags (PendingIntent.java:378)
  at android.app.PendingIntent.getBroadcastAsUser (PendingIntent.java:648)
  at android.app.PendingIntent.getBroadcast (PendingIntent.java:635)
  at androidx.work.impl.utils.ForceStopRunnable.getPendingIntent (ForceStopRunnable.java:174)
  at androidx.work.impl.utils.ForceStopRunnable.isForceStopped (ForceStopRunnable.java:108)
  at androidx.work.impl.utils.ForceStopRunnable.run (ForceStopRunnable.java:86)
  at androidx.work.impl.utils.SerialExecutor$Task.run (SerialExecutor.java:75)
  at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1167)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:641)
  at java.lang.Thread.run (Thread.java:920)
```

### Steps to reproduce

Run any game built in Godot 3.5 on Android 12.

There is a theory that this will also be relevant for lower versions of Godot.

**Comment by m4gr3d** [comment] 2022-08-15 03:59
@SkanerSoft Unfortunately the information provided is not enough to allow us to reproduce and identify the issue. 

> Run any game built in Godot 3.5 on Android 12.

Can you provide a test project that consistently crashes when built on Godot 3.5 on Android 12, but doesn't when using prior versions of Godot?

**Comment by SkanerSoft** [comment] 2022-08-15 09:01
I don't have an Android 12 phone, so I'm not sure I can build exactly the minimal project. Someone else who has such a device is needed to make sure that the problem is really happening.

**Comment by m4gr3d** [comment] 2022-08-15 09:34
@SkanerSoft You may be able to use the Android emulator on a PC to test your project on Android 12: https://developer.android.com/studio/run/emulator

**Comment by SkanerSoft** [comment] 2022-08-18 08:03
In general, I was able to test the problem. I can't say exactly why it appeared, but I was able to solve it by adding the following line to the Gradle settings:

`implementation 'androidx.work:work-runtime-ktx:2.7.1'`

After that, the project on Android 12 began to run without problems.
The device on which the tests were carried out is Realme 9Pro 5G.
As for the minimum project, this is literally any project.

**Comment by m4gr3d** [comment] 2022-08-26 16:01
@SkanerSoft I tested two sample projects using the Godot 3.5 stable build and stable build templates on a device running Android 13, and I was not able to reproduce the issue you're describing.

So it's likely the issue originates with your project configuration.
If you can share the project that's crashing, or provide a repro project, we can investigate further, otherwise there's not much we can do.

> implementation 'androidx.work:work-runtime-ktx:2.7.1'

For reference, the stock Godot Android template doesn't make use of this library, so this may originate from one of the plugin your project is using.

**Comment by m4gr3d** [comment] 2022-08-26 16:03
I'll close the issue for now as not-reproducible. Feel free to re-open if you're able to provide a repro project.

**Closed by m4gr3d** 2022-08-26 16:04 UTC
Labels: bug, platform:android, topic:porting, needs testing, crash
