### ISSUE TITLE
Theme files still generating pointless diffs

### ISSUE THREAD

**Issue by TheDuriel** [godotengine/godot#28755] opened 2019-05-08 08:48 UTC
**Godot version:**

3.1.1 - Mono

**OS/device including version:**

Any

**Issue description:**

Theme Files change their resource ID upon saving. without any other changes made to the file.

https://twitter.com/reduzio/status/1116402005675786242

(i would link the commit, but i can't find it. should be around april 11th)

**Steps to reproduce:**
Make a theme. Add some internal resources. Save. Restart Godot. Open the theme, do not make any changes. Save it again. Depending on your number of resources you will see their IDs changed.

**Minimal reproduction project:**

**Comment by TheDuriel** [comment] 2019-05-08 08:48
![image](https://user-images.githubusercontent.com/44248915/57362318-d41d0380-717e-11e9-902b-d93ee41cbc4d.png)

**Comment by bojidar-bg** [comment] 2019-05-08 10:53
I think I've seen something similar with scene files, seems to happen when I have two scenes open, one instancing the other, and I run the game while having the inner scene active.

**Comment by TheDuriel** [comment] 2019-05-08 17:39
I had assumed it mad it into 3.1.x as i did not see the problem occur for a while. I'm using mono, so testing master is a bit troublesome atm for my project. Would love it if someone else took at look.

**Comment by KoBeWi** [comment] 2020-01-12 13:15
This is probably the same as #33411 and #28346
It might happen to any sub-resource.

**Comment by akien-mga** [comment] 2020-01-15 14:03
Duplicate of #22226.

**Closed by akien-mga** 2020-01-15 14:03 UTC
Labels: bug, topic:core, topic:editor
