### ISSUE TITLE
Bug with highlighting of fields in about window.

### ISSUE THREAD

**Issue by DmitriySalnikov** [godotengine/godot#12222] opened 2017-10-18 23:04 UTC
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Win 10, Godot 3.0

**Issue description:**
![2017-10-19_01-51-09](https://user-images.githubusercontent.com/7782218/31746492-76ea8c7c-b470-11e7-9e19-f2b85e8fc5a9.gif)

**Steps to reproduce:**
Open about window, select field in first or second tab, scroll

**Comment by Noshyaar** [comment] 2017-10-19 11:04
Duplicate of #9612

**Closed by Noshyaar** 2017-10-19 11:04 UTC
