### ISSUE TITLE
Make TouchScreenButton handle events

### ISSUE THREAD

**Issue by romulox-x** [godotengine/godot#583] opened 2014-07-11 05:07 UTC
When a touch is processed by a TouchScreenButton, the touch is still processed by a node that's set to process unhandled input.  The TouchScreenButton should prevent the event from being seen as unhandled.

**Comment by kubecz3k** [comment] 2015-10-30 13:19
@romulox-x do you know current status for this bug maybe? It's little troublesome for me to check in a moment. Also let us know (just in case) if it was Android or iOS.

**Comment by akien-mga** [comment] 2016-03-23 11:00
Closing as old as there has been no feedback from the OP or other testers since 2014. Feel free to reopen or opening a new issue if the problem is still current in 2.0 or git HEAD.

**Closed by akien-mga** 2016-03-23 11:00 UTC
Labels: bug, topic:core
