### ISSUE TITLE
Incorrect operation of the dictionary in the loop

### ISSUE THREAD

**Issue by Timofffee** [godotengine/godot#28730] opened 2019-05-07 00:34 UTC
**Godot version:**
3.1.1 Stable

**Issue description:**
The dictionary in the loop is not cleared when the type is assigned.

**Steps to reproduce:**
Wrong
```GDScript
for i in 5:
    var dict: Dictionary
    dict[i] = i
    print(dict)
```
> <details><summary>Output:</summary>
> <p>
> 
> ```GDScript
> {0:0}
> {0:0, 1:1}
> {0:0, 1:1, 2:2}
> {0:0, 1:1, 2:2, 3:3}
> {0:0, 1:1, 2:2, 3:3, 4:4}
> ```
> </p>
> </details>
Correct
```GDScript
for i in 5:
    var dict: Dictionary = {} 
    # or just
    # var dict = {}
    dict[i] = i
    print(dict)
```
> <details><summary>Output:</summary>
> <p>
> 
> ```GDScript
> {0:0}
> {1:1}
> {2:2}
> {3:3}
> {4:4}
> ```
> </p>
> </details>

**Minimal reproduction project:**
Just use the code written above

**Comment by akien-mga** [comment] 2019-05-07 06:18
Duplicate of  #24134.

**Closed by akien-mga** 2019-05-07 06:18 UTC
