### ISSUE TITLE
The way KinematicBody pushes itself back after multiple collisions is flawed

### ISSUE THREAD

**Issue by ThePixelGuy** [godotengine/godot#41289] opened 2020-08-15 17:58 UTC
**Godot version:**
3.2.2.stable

**Issue description:**
The KinematicBody node does not correctly push itself back when it is colliding with multiple that push it in an axis.
In the source code, at the 995th line, you can see that it pushes itself back by each collider according to said collider.

```
if (collided) {
	found_collision = true;

	colliders.push_back(collision);
	...
}
```
Although this works with multiple colliders that push the KinematicBody in a single axis by itself, if there are multiple colliders that push in a single axis, that will cause the KinematicBody to land on a wrong position after the collisions.

![image](https://user-images.githubusercontent.com/57534680/90318468-4dd29e00-df39-11ea-8d86-b0f0d7edf7f7.png)

**Steps to reproduce:**

1. Create a KinematicBody.
2. Create multiple StaticBodys on the same position, preferably a lot.
3. Attach a script to the KinematicBody that will allow you to move the KinematicBody to the stacked StaticBodys.
4. Notice how the KinematicBody is repositioned too far away from the StaticBodys, since each of the StaticBodys push the KinematicBody the same amount that would position the KinematicBody correctly by itself.

**Minimal reproduction project:**

[KinematicBody Collision Flaw.zip](https://github.com/godotengine/godot/files/5079205/KinematicBody.Collision.Flaw.zip)
(Move with left & right arrow keys.)

PS: This is my first time "posting" anything on GitHub, please let me know if something about the post is off.

**Comment by madmiraal** [comment] 2020-08-16 07:25
Duplicate of #35780, fixed with #35945.

**Closed by madmiraal** 2020-08-16 07:25 UTC
