### ISSUE TITLE
The theme editor is seriously error

### ISSUE THREAD

**Issue by L2750558108** [godotengine/godot#73080] opened 2023-02-11 07:00 UTC
### Godot version

4.0(rc 1) mono

### System information

windows10

### Issue description

This is not exactly the same of https://github.com/godotengine/godot/issues/73076

The Theme Editor closes automatically when you
1.drag a file to the right column in the Theme Editor
2.add or remove theme types from the Theme Manage Topic Items window
3.add or remove theme items in the Theme Editor right column or Theme Manage Topic Items window

And the theme editor closing caused when the Manage Theme Project window is open will not close the Manage Theme Project window, and adding or removing types or projects at this time will cause the Godot Editor to crash

### Steps to reproduce

See "Issue description" for detail

1.Create a theme
2.Double click it to open theme editor
3.Do anyone of this
    a.drag a file to the right column in the Theme Editor
    b.add or remove theme types from the Theme Manage Topic Items window
    c.add or remove theme items in the Theme Editor right column or Theme Manage Topic Items window
4.See the theme editor is closed
5.If you do b or c in step 2, you can see the Theme Manage Topic Items window is still exists. Adding or removing types or projects.
6.See godot editor is crash

### Minimal reproduction project

An empty project

**Comment by Zireael07** [comment] 2023-02-11 09:43
duplicate/related to #72271

**Comment by L2750558108** [comment] 2023-02-11 09:53
They are not exactly the same, and I summarize the situation more comprehensively than it

**Comment by akien-mga** [comment] 2023-02-11 10:10
Duplicate of #72271 (theme editor closing) and https://github.com/godotengine/godot/issues/72799 (crash).

**Closed by akien-mga** 2023-02-11 10:10 UTC
