### ISSUE TITLE
Animation Tree Player improvements (mostly GUI)

### ISSUE THREAD

**Issue by slapin** [godotengine/godot#4438] opened 2016-04-25 09:38 UTC
We need to have the following improvements to ATP:
1. There is a feature called filters. If you don't know, you can't avoid using it if you blend
   several animations or using oneshot node for things like blinking, as it limits scope of your animations.
   We need to have separate filters "node" from blend/oneshot nodes in GUI.
   This node will allow us eventually implement general animation filtering, which will make
   animation composition hardships go away. Basically all important functionality
   is already implemented, this is small readjustment.
   Nedd to mention we don't want to attach this "node" to Animation node.
2. Animation node needs to have multiple output in GUI. This
   can be generated into multiple animation "nodes" for each output, or some other things,
   but this have to be done, as lots of nodes with the same animation really clutters scene output.

Imagine you have "blink" animation and "breathe" animation.
First one goes to oneshot node, second is looped, they blend to all animations like, walk, stand.
sit, lay down, idle13, whatever. If you have hundred main animations ,only these 2 detail animations will
make your setup into 300 nodes hard to navigate and manage.
Internally this can be the same as now, but for GUI something needs to change.
1.  The filter editor for animations with many tracks (like skeletal animations) looks like mess.
   It is very hard to navigate. Probably it should be replaced by something useful, but probably
   if possible the existing one can be improved by a few simple things:
   - Add search for simple substring with immediate display (like quick search in some apps)
     not requiring press Enter after each result, just reducing output with additional character entered.
2. Add "invert selection", "select all", "unselect all" buttons
3. Disable treeish view (probably a checkbox with immediate reaction), replacing it with plain table), that would really help with bones,

**Comment by slapin** [comment] 2016-04-25 12:06
@bojidar-bg what do you think?

**Comment by bojidar-bg** [comment] 2016-04-25 13:02
@slapin Well, I haven't used AnimationTreePlayer yet, but I will try it and see if those changes are reasonable :)

**Comment by slapin** [comment] 2016-04-25 13:05
I think it is just start, I have some other ideas, but these are most simple ones and are most annoying issues.

**Comment by slapin** [comment] 2016-04-25 13:12
Well, this is core node needed to implement character animation in 3D and
keep sanity,
so going 3D you will have to use it eventually

**Comment by JoshuaGrams** [comment] 2016-04-26 01:55
The AnimationTree GUI code is a __mess__: I'm guessing it was written before the GUI nodes existed because it's mostly hard-coded. So changing the GUI isn't easy.

The core functionality for filtering is **not** all implemented: you can have **one** filter on any given path through the tree, so it's quite limited. The filters don't combine at all; they just overwrite each other.  The easiest thing would be to add filtering directly to leaf nodes (Animation nodes) to work around this limitation.  But even there, adding it to the GUI is a nuisance (I did this the other day for personal use and ended up adding a "Edit Filters" entry in the animation popup menu because that was the only way to do it without rewriting the whole AnimTree GUI). I could push that code to github if you're interested.

Multiple output: it sounds to me like you're doing it backwards. Why can't you select between walk, stand, sit, lay down, idle, etc., and then blend your breathe/blink oneshot on top of that at the very end?  Then you would only need one copy. The code is **not** set up to have multiple outputs: each connection makes time pass by recursing up from the `out` node, so if you added N outputs the animation would play N times as fast. And what if you want it to play at a different speed from one output as from another output?

Filter editor: again, look at the code. It's not set up so it's simple to make those kinds of modifications. If you want to take it on, good for you.

**Comment by Keyaku** [comment] 2016-08-10 01:12
As of 2016, AnimationTreePlayer is still severely lacking. Lacks signals, plays Animations in a heavily erratic manner whereas AnimationPlayer can play them correctly, causes errors all over the place.

It's really a shame because I was trying to use it for simple cutscenes (by "Transitioning" to the next input index), but it breaks everywhere (and I'm almost sure I'm doing things right).

I hope someone can take a thorough look into this one!

**Comment by reduz** [comment] 2016-08-10 01:21
It will be completely rewritten for Godot 3.0

**Comment by slapin** [comment] 2016-08-10 13:45
For now you can write your own blender in GDScript using Animation
resource, it is quite easy.
ATP also can be used with a few hacks.
The main problem with 3D animations with ATP is that they consume too much
CPU
if you have complex tree (about 20-30 nodes is noticeable), I really don't
know why.
To overcome this you can write your own game-specific animation blender
looking at ATP code, strangely, you don't need it in C++ - GDScript version
works fine.
But the code will be really hairy, so I hope that this eventually be fixed
in some way.

**Comment by Keyaku** [comment] 2016-08-10 14:51
@Slapin Actually, it's a 2D game; I was trying to get from one animation to another with just a transition node in the cutscene, and drawing a more complex tree for a "Move Set" specific to a character.

Sadly, this causes errors all over the place,

**Comment by slapin** [comment] 2016-08-10 17:09
As I said, you better write your own game-specific animation blender.
The Animation resource is easy to work with and you can make quite
powerful animation system with GDScript without much effort.
Especially for 2D. For 3D the set of workarounds can do a trick too,
but it is much harder work, and as all things made of sticks, not very
reusable, which is sad.

**Comment by JuanDidNothingWrong4** [comment] 2017-12-02 03:43
Voting to close this, not a priority at all. Juan told me on reddit.

**Comment by akien-mga** [comment] 2018-09-10 13:55
`AnimationTreePlayer` is deprecated in Godot 3.1 and will be removed in Godot 3.2. It is replaced by `AnimationTree`, which was written from scratch and likely fixes/deprecates this issue.

If the issue is still relevant in some form with `AnimationTree` in Godot 3.1, please open a new issue about it (potentially linking this one if there is relevant discussion to keep track of).

**Closed by akien-mga** 2018-09-10 13:55 UTC
Labels: enhancement, topic:editor
