### ISSUE TITLE
Projects take considerably longer to start if another instance exists (editor or another game) (possibly shader caching bug)

### ISSUE THREAD

**Issue by nathanfranke** [godotengine/godot#63419] opened 2022-07-25 01:53 UTC
### Godot version

3f39625399d8a5ef118341e47500f31f21b11581
Can't to reproduce in 3.x (tested 3.4.4.stable and 3.5.rc7)

### System information

Arch on 5.18.12-arch1-1

### Issue description

See https://github.com/godotengine/godot/issues/43351#issuecomment-1179631929

```sh
$ time ./bin/godot.linuxbsd.opt.tools.64.llvm --path ~/workspace/empty --quit

...

real    0m1.804s
user    0m2.805s
sys     0m0.386s
```

Again, in another terminal right after:
```sh
$ time ./bin/godot.linuxbsd.opt.tools.64.llvm --path ~/workspace/empty --quit

...

real    0m7.352s
user    0m6.795s
sys     0m0.394s
```

### Steps to reproduce

1) Run a godot project with `--path`
2) Run a godot project with `--path`
the second instance will take considerably longer to start

### Minimal reproduction project

[empty.zip](https://github.com/godotengine/godot/files/9177227/empty.zip)

**Comment by Calinou** [comment] 2022-07-25 13:05
Can you reproduce this in 3.4.4 to confirm whether this is due to 4.0's shader cache?

**Comment by Zylann** [comment] 2022-07-25 22:05
I experience really slow startups as well. It's nowhere near startup times in Godot 3.

**Comment by nathanfranke** [comment] 2022-07-25 22:11
> Can you reproduce this in 3.x to confirm whether this is due to 4.0's shader cache?

Cannot reproduce at all in 3.4.4.stable or 3.5.rc7. However I did discover a similar bug https://github.com/godotengine/godot/issues/63460

> I experience really slow startups as well. When starting a game from the editor, it shows a white window for about 5 seconds before it starts showing the splash. It's nowhere near startup times in Godot 3.

Issue https://github.com/godotengine/godot/issues/43351 may be more related to your issue, this issue is only about starting multiple instances simultaneously.

**Comment by KoBeWi** [comment] 2023-02-23 00:33
Can't reproduce, both instances take the same time to launch.
@nathanfranke Can you confirm that this is fixed?

**Comment by KoBeWi** [comment] 2023-02-25 01:36
Closing. You can deconfirm it.

**Closed by KoBeWi** 2023-02-25 01:36 UTC
Labels: bug, topic:editor, performance

**Comment by Zireael07** [comment] 2023-02-25 08:23
Is "deconfirm"  a typo for "reconfirm"?

**Comment by nathanfranke** [comment] 2023-02-25 08:29
I will check it soon

**Comment by KoBeWi** [comment] 2023-02-25 15:28
> Is "deconfirm" a typo for "reconfirm"?

No, it refers to

> Can you confirm that this is fixed?

I just closed the issue assuming it's fixed. So if it's not, it would "deconfirm" it.

**Comment by nathanfranke** [comment] 2023-03-03 19:34
I don't see this issue on 4.0.stable, probably fixed.
