### ISSUE TITLE
Sync to physics doesn't work!

### ISSUE THREAD

**Issue by shmellyorc** [godotengine/godot#37508] opened 2020-04-01 20:03 UTC
Godot version:
v3.2.1.stable.offcal

OS/device including version:
Windows 10 (latest)

Issue description:
sync to physics doesn't work with platforms. the collision (visually) moves with the path follow 2d but the actual collision doesn't.

contained a sample project here: https://ufile.io/bvc0vd9t + as an attachment

[sync_to_physics.zip](https://github.com/godotengine/godot/files/4417326/sync_to_physics.zip)

**Comment by Calinou** [comment] 2020-04-01 20:40
Duplicate of #25291.

**Closed by Calinou** 2020-04-01 20:40 UTC
