### ISSUE TITLE
Shader Materials don´t respect configured shader parameters if they are duplicated - Godot 4

### ISSUE THREAD

**Issue by rena-souza** [godotengine/godot#68178] opened 2022-11-02 19:03 UTC
### Godot version

4.0 beta 4

### System information

PopOs 22.04 LTS, RTX 2060, intel i7 9th gen, 16gb ram

### Issue description

After duplicate a shader material, and modifying the shader parameters. The new parameters will be applied in the original material to. Reload the scene, or the engine won´t fix the issue.

In editor
![In editor](https://user-images.githubusercontent.com/8316202/199576233-2322f3a3-1d04-4f72-a366-0f12a6446ede.png)
Running the game
![Running](https://user-images.githubusercontent.com/8316202/199576770-5d486207-afef-48c4-b244-b4bdf0f13bb0.png)

Editor after reloading the scene
![Editor after close and opening the scene again](https://user-images.githubusercontent.com/8316202/199576889-48d89678-6b82-45c5-ada1-5e94991d1f53.png)

### Steps to reproduce

* Create a new shader material A.
* Add a new Shader to material A, and save it as a resource. The shader should have parameters to visualize the problem.
* Apply the material A to a mesh, it should work as expected
* Now duplicate the material, and change the shader parameters. When applying to a new mesh, It will appear to have worked as expected in editor
* Running the game will show both meshes with the shadder behaving as if they have the same parameters.
* After you reload the scene. The editor will have the same behavior as when running the game

### Minimal reproduction project

[godot-4-materials-test.zip](https://github.com/godotengine/godot/files/9923316/godot-4-materials-test.zip)

**Comment by Zireael07** [comment] 2022-11-02 19:33
duplicate of https://github.com/godotengine/godot/issues/67206?

**Comment by rena-souza** [comment] 2022-11-02 19:38
Yes! It looks like the same thing.

**Comment by Calinou** [comment] 2022-11-02 20:05
Can you try [building the latest `master` branch](https://docs.godotengine.org/en/latest/development/compiling/index.html), which includes a fix for https://github.com/godotengine/godot/issues/54774?

**Comment by rena-souza** [comment] 2022-11-03 01:30
Tested with a build from the master branch and it is working as expected!

**Comment by akien-mga** [comment] 2022-11-03 08:16
Duplicate of #54774

**Closed by akien-mga** 2022-11-03 08:16 UTC
Labels: bug, archived, topic:editor
