### ISSUE TITLE
HashingContext example produces different hash values each time it is run

### ISSUE THREAD

**Issue by graydwarf** [godotengine/godot#51959] opened 2021-08-21 19:16 UTC
### Godot version

3.2.3.stable

### System information

Windows 10

### Issue description

Running the example found on the HashingContext help page produces seemingly random hash values. Sometimes it produces the same hash value and sometimes it's just random. 

https://docs.godotengine.org/en/stable/classes/class_hashingcontext.html

### Steps to reproduce

- Launch repro project
- Specify path to file you want to hash
- Click the 'Hash Using Example Code' button a few times.

The repro project also contains a workaround function ('Hash Using Workaround') that @Nisovin provided in Discord while helping to troubleshoot the issue.

### Minimal reproduction project

[RandomHashValueIssue.zip](https://github.com/godotengine/godot/files/7026076/RandomHashValueIssue.zip)

**Comment by Calinou** [comment] 2021-08-21 19:54
cc @Faless @jonbonazza

**Comment by Faless** [comment] 2021-08-22 11:46
Yep, that's actually a bug in `File.get_buffer`, fixed in #47811, but reverted due to #47971 . I'll have to look into #47975 which seems to be the proper fix for the get_var issue.

**Comment by chimeforest** [comment] 2022-11-02 07:40
I ran into this also in Godot 3.5.1.stable

I worked around it by just doing the whole file at once.
replace
```
while not file.eof_reached():
        ctx.update(file.get_buffer(CHUNK_SIZE))
```
with
```
ctx.update(file.get_buffer(file.get_len()))
```
and it will work.
I'm not sure how well it will work on large files.. luckily for me all my files are small (under 40MB) so it's not a problem.

Also... something I didn't know... it's possible to use this functionality on a PoolByteArray.
Since I'm loading my entire file at once anyway, I thought I might be able to save a little computing power by only reading the file once. Turns out I was right, it makes sense since file.get_buffer() returns a PoolByteArray.

Anyway, here is the code I wrote for that:

```
static func GetMD5HexFromPool(pool:PoolByteArray):
	var ctx = HashingContext.new()
	ctx.start(HashingContext.HASH_MD5)
	ctx.update(pool)
	var res = ctx.finish()
	return res.hex_encode()
```

**Comment by SteveSmith16384** [comment] 2023-11-15 11:02
I can't help feeling this is such a big bug, HashingContext should be removed/disabled until it's fixed?  In it's current state it can only cause problems and confusion, and I can't see any use for it.

**Comment by AThousandShips** [comment] 2023-11-15 11:09
Can someone confirm this still applies? The `get_var` issue seems to have been fixed?

**Comment by SteveSmith16384** [comment] 2023-11-15 11:21
I've also just discovered that File has getMd5() and get_sha256() methods.  Is there any reason not to use these?

**Comment by Faless** [comment] 2023-11-15 11:38
> I can't help feeling this is such a big bug, HashingContext should be removed/disabled until it's fixed?

As described above, the bug is (was?) not in `HashingContext` but in `File.get_buffer()`.

**Comment by Faless** [comment] 2023-11-15 11:57
I confirmed the bug in `File(Access).get_buffer()` was fixed in 4.x but present in 3.x .
I've opened #84934 which should fix it

**Closed** 2023-12-08 14:45 UTC
Labels: bug, topic:core, confirmed
