### ISSUE TITLE
Custom tooltips for GDS exports are ineffective unless the script is saved again

### ISSUE THREAD

**Issue by magian1127** [godotengine/godot#97422] opened 2024-09-24 18:36 UTC
### Tested versions

master

### System information

win11

### Issue description

![image](https://github.com/user-attachments/assets/7e41fe18-f5b2-41b8-8c01-2ba87485e9ee)

It shouldn't wait for `update_script_paths_documentation` to update the default opened TSCN.
I suggest triggering documentation writing when the TSCN is first opened, and then continue using `update_script_paths_documentation` afterward.

### Steps to reproduce

1. Create a Node and attach a GDScript to it.
2. Custom `##` exports tooltips.
3. Reopen the Godot editor and load the project.
4. At this point, the class tooltips are ineffective.(unless the GDScript is saved again)

### Minimal reproduction project (MRP)

[Gdstip.zip](https://github.com/user-attachments/files/17119265/Gdstip.zip)

**Comment by dalexeev** [comment] 2024-09-25 17:37
Most likely a duplicate of #72406 / #86577. Please test if #95821 fixes this.

Thanks for reporting the bug nonetheless!

**Closed by dalexeev** 2024-09-25 17:37 UTC
