### ISSUE TITLE
When entering specific values into a polygon collision shape in a tilemap, Godot crashes.

### ISSUE THREAD

**Issue by zeroxoneafour** [godotengine/godot#52302] opened 2021-09-01 03:51 UTC
### Godot version

4.0.dev (036b7a0)

### System information

Arch Linux, Vulkan, Official NVIDIA

### Issue description

I'm having a very strange issue. I'm experimenting with tilemaps, and trying to set collision shapes for specific tiles. After figuring out how to add collisions (the master documentation on tilemaps needs to be updated), I tried to create a 4-vertex collision polygon with vertices at { (0,0), (0,3), (3,3), (3,0) } relative to the selected area. Now, all of these happened from the same commit.

When I built Godot without builtin Bullet, Opus, LibPNG, FreeType, and a few others, I got a segmentation fault and the program became broken. I used ThinLTO and Clang/LLD.

When I rebuilt Godot with the same options, but without ThinLTO, the build broke with errors on the final linking.

When I rebuilt Godot with the same compiler, but without builtin options or ThinLTO, the same thing happened as when I used the builtin options without ThinLTO.

When I deleted the build directory and recloned/rebuilt using Clang/LLD, no builtin library options, and no ThinLTO, the build was successful. Note that this was the same scenario and commit as the third scenario, down to the build script used. When I tried to change those specific values I was talking about, Godot crashed with a large memory dump (but no segfault message).

Note that each time I used dynamic C++ linking, because Clang is broken without it (something to do with libatomic).

### Steps to reproduce

This is probably a non-reproducible bug, but here is exactly what I did on the last attempt.

1. Built Godot 4.0.dev `036b7a0` with `use_llvm`, `use_lld`, `target=release_debug`, `-j12` and `use_static_cpp=false`
2. Opened a previous project where the tilemap I created already had the physics shape, but the vertexes were off.
3. Tried to change the vertexes of the polygon physics shape for the square ground tile
4. Once I got to the third vertex, it invariably crashed.

### Minimal reproduction project

[tilemaps.zip](https://github.com/godotengine/godot/files/7088106/tilemaps.zip)

**Comment by Calinou** [comment] 2021-09-01 13:18
Duplicate of https://github.com/godotengine/godot/issues/42037 (same cause).

**Closed by Calinou** 2021-09-01 13:18 UTC
