### ISSUE TITLE
export to ios: core/os/file_access.cpp:577 - Condition ' !f ' is true. returned: Vector<uint8_t>()

### ISSUE THREAD

**Issue by njt1982** [godotengine/godot#30052] opened 2019-06-24 22:39 UTC
EDIT

I found this was caused by a space in the ios project name (for anyone else thats stumbles upon this)

---

https://github.com/godotengine/godot/blob/66baa3b633fe904ea0d90a9688d602d9f3a0b3bd/core/os/file_access.cpp#L577

```
 core/os/file_access.cpp:577 - Condition ' !f ' is true. returned: Vector<uint8_t>()
 core/os/file_access.cpp:577 - Condition ' !f ' is true. returned: Vector<uint8_t>()
 core/os/file_access.cpp:577 - Condition ' !f ' is true. returned: Vector<uint8_t>()
 core/os/file_access.cpp:577 - Condition ' !f ' is true. returned: Vector<uint8_t>()
 core/os/file_access.cpp:577 - Condition ' !f ' is true. returned: Vector<uint8_t>()
 core/os/file_access.cpp:577 - Condition ' !f ' is true. returned: Vector<uint8_t>()
 core/os/file_access.cpp:577 - Condition ' !f ' is true. returned: Vector<uint8_t>()
 core/os/file_access.cpp:577 - Condition ' !f ' is true. returned: Vector<uint8_t>()
 core/os/file_access.cpp:577 - Condition ' !f ' is true. returned: Vector<uint8_t>()
 core/os/file_access.cpp:577 - Condition ' !f ' is true. returned: Vector<uint8_t>()
 core/os/file_access.cpp:577 - Condition ' !f ' is true. returned: Vector<uint8_t>()
 core/os/file_access.cpp:577 - Condition ' !f ' is true. returned: Vector<uint8_t>()
 core/os/file_access.cpp:577 - Condition ' !f ' is true. returned: Vector<uint8_t>()
 core/os/file_access.cpp:577 - Condition ' !f ' is true. returned: Vector<uint8_t>()
Static library: libgodot.iphone.debug.fat.a
Unzipping...
READ: data.pck
READ: godot_ios/
READ: godot_ios/dummy.cpp
ADDING: My Game Name/dummy.cpp size: 2207
READ: godot_ios/en.lproj/
READ: godot_ios/en.lproj/InfoPlist.strings
ADDING: My Game Name/en.lproj/InfoPlist.strings size: 45
Creating /Users/nthompson/Documents/GoDot/MyGameName/ios-export/My Game Name/en.lproj
READ: godot_ios/export_options.plist
ADDING: My Game Name/export_options.plist size: 462
READ: godot_ios/godot_ios-Info.plist
ADDING: My Game Name/My Game Name-Info.plist size: 1397
READ: godot_ios/godot_ios.entitlements
ADDING: My Game Name/My Game Name.entitlements size: 246
READ: godot_ios/Images.xcassets/
READ: godot_ios/Images.xcassets/LaunchImage.launchimage/
READ: godot_ios/Images.xcassets/LaunchImage.launchimage/Contents.json
ADDING: My Game Name/Images.xcassets/LaunchImage.launchimage/Contents.json size: 2566
Creating /Users/nthompson/Documents/GoDot/MyGameName/ios-export/My Game Name/Images.xcassets/LaunchImage.launchimage
READ: godot_ios/Images.xcassets/LaunchImage.launchimage/Default-480h@2x.png
ADDING: My Game Name/Images.xcassets/LaunchImage.launchimage/Default-480h@2x.png size: 1641
READ: godot_ios/Images.xcassets/LaunchImage.launchimage/Default-568h@2x.png
ADDING: My Game Name/Images.xcassets/LaunchImage.launchimage/Default-568h@2x.png size: 1919
READ: godot_ios/Images.xcassets/LaunchImage.launchimage/Default-667h@2x.png
ADDING: My Game Name/Images.xcassets/LaunchImage.launchimage/Default-667h@2x.png size: 2392
READ: godot_ios/Images.xcassets/LaunchImage.launchimage/Default-Landscape-736h@3x.png
ADDING: My Game Name/Images.xcassets/LaunchImage.launchimage/Default-Landscape-736h@3x.png size: 4360
READ: godot_ios/Images.xcassets/LaunchImage.launchimage/Default-Landscape-X.png
ADDING: My Game Name/Images.xcassets/LaunchImage.launchimage/Default-Landscape-X.png size: 4192
READ: godot_ios/Images.xcassets/LaunchImage.launchimage/Default-Landscape.png
ADDING: My Game Name/Images.xcassets/LaunchImage.launchimage/Default-Landscape.png size: 1722
READ: godot_ios/Images.xcassets/LaunchImage.launchimage/Default-Landscape@2x.png
ADDING: My Game Name/Images.xcassets/LaunchImage.launchimage/Default-Landscape@2x.png size: 5097
READ: godot_ios/Images.xcassets/LaunchImage.launchimage/Default-Portrait-736h@3x.png
ADDING: My Game Name/Images.xcassets/LaunchImage.launchimage/Default-Portrait-736h@3x.png size: 5274
READ: godot_ios/Images.xcassets/LaunchImage.launchimage/Default-Portrait-X.png
ADDING: My Game Name/Images.xcassets/LaunchImage.launchimage/Default-Portrait-X.png size: 5513
READ: godot_ios/Images.xcassets/LaunchImage.launchimage/Default-Portrait.png
ADDING: My Game Name/Images.xcassets/LaunchImage.launchimage/Default-Portrait.png size: 1881
READ: godot_ios/Images.xcassets/LaunchImage.launchimage/Default-Portrait@2x.png
ADDING: My Game Name/Images.xcassets/LaunchImage.launchimage/Default-Portrait@2x.png size: 5491
READ: godot_ios/dylibs/
READ: godot_ios/dylibs/empty
ADDING: My Game Name/dylibs/empty size: 41
Creating /Users/nthompson/Documents/GoDot/MyGameName/ios-export/My Game Name/dylibs
READ: godot_ios.xcodeproj/
READ: godot_ios.xcodeproj/project.pbxproj
ADDING: My Game Name.xcodeproj/project.pbxproj size: 23563
READ: godot_ios.xcodeproj/project.xcworkspace/
READ: godot_ios.xcodeproj/project.xcworkspace/contents.xcworkspacedata
ADDING: My Game Name.xcodeproj/project.xcworkspace/contents.xcworkspacedata size: 158
Creating /Users/nthompson/Documents/GoDot/MyGameName/ios-export/My Game Name.xcodeproj/project.xcworkspace
READ: godot_ios.xcodeproj/xcshareddata/
READ: godot_ios.xcodeproj/xcshareddata/xcschemes/
READ: godot_ios.xcodeproj/xcshareddata/xcschemes/godot_ios.xcscheme
ADDING: My Game Name.xcodeproj/xcshareddata/xcschemes/My Game Name.xcscheme size: 3482
Creating /Users/nthompson/Documents/GoDot/MyGameName/ios-export/My Game Name.xcodeproj/xcshareddata/xcschemes
READ: libgodot.iphone.debug.fat.a
ADDING: My Game Name.a size: 243411032
READ: libgodot.iphone.release.fat.a
Exporting additional assets
```

When I try to open the project, I get this:
![image](https://user-images.githubusercontent.com/384976/60056523-166fb500-96d9-11e9-972d-43d46855889f.png)

I believe I have followed fully:
https://docs.godotengine.org/en/3.1/getting_started/workflow/export/exporting_for_ios.html

I have created the required icons and the portrait/landscape launch screens. I have set the Team ID and bundle (after remaking my App ID due to the hyphen bug (#30050)).

Am I missing something? It looks like its failing to find some files to copy?

**Comment by njt1982** [comment] 2019-06-24 22:54
Ahhh foudn the problem! I had a space in the project filename. 

I used `$ xcodeproj config-dump` and got this error:
`Dictionary missing ';' after key-value pair for "path", found "T"`

aroudn this bit:
```
{isa = PBXFileReference; lastKnownFileType = text.plist.entitlements; path = My Game Name.entitlements; sourceTree = "<group>"; };
```

**Comment by KoBeWi** [comment] 2019-06-25 13:12
So shall this be closed or maybe docs should be improved to avoid this?

**Comment by njt1982** [comment] 2019-06-25 21:15
Hi @KoBeWi I think the minimum is a note in the documentation to avoid a space in the IPA filename. In a perfect world, the space shouldn't have been a problem (I've made loads of XCode projects with spaces in the name 😉). But a simple sentence in the documentation could have saved me ~1hour of debugging ;)

**Comment by njt1982** [comment] 2019-06-25 21:50
@KoBeWi / @YeldhamDev I've opened a PR to add a note: https://github.com/godotengine/godot-docs/pull/2569

I guess this should be closed in favour of any other disussion over on that PR?

**Comment by Calinou** [comment] 2020-01-28 22:34
Duplicate of #25128.

**Closed by Calinou** 2020-01-28 22:34 UTC
Labels: documentation, enhancement
