### ISSUE TITLE
Cannot construct temporary MonoObject

### ISSUE THREAD

**Issue by git2013vb** [godotengine/godot#37703] opened 2020-04-08 21:05 UTC
**Godot version:**
3.2.1 stable mono
**OS/device including version:**
Debian 10
**Issue description:**
I tried to use these examples here: https://docs.godotengine.org/en/latest/getting_started/step_by_step/resources.html#creating-your-own-resources
`BotStats.cs` and `Bot.cs` but I have this error:

` Cannot construct temporary MonoObject because the class does not define a parameterless constructor: 'res://assets/resources/BotStats.cs'.`

I'm missing something? How I can use them? 
**Steps to reproduce:**
I saved both as script resources:
![image](https://user-images.githubusercontent.com/13235119/78833388-b2f31180-79e4-11ea-9863-3c5422bcdf39.png)
 Then I loaded as script:
```
 private Script _myBotStats = ResourceLoader.Load("res://assets/resources/BotStats.cs") as Script;
 private Script _myBot = ResourceLoader.Load("res://assets/resources/Bot.cs") as Script;

```
**Minimal reproduction project:**
C# project.

Edit:
I think was missing this from documentation:
```
 public BotStats()
        {
        }
```
I'm wrong? btw.. How I can use them in C#?

**Comment by neikeq** [comment] 2020-04-08 21:41
Yes, if you define a constructor with parameters, C# won't generate the parameterless constructor, so you have to declare it yourself as in your last example:

``` C#
public BotStats()
{
}
```

The example you linked is wrong then, as it should declare this constructor.

Maybe this can be improved in the future.

**Comment by git2013vb** [comment] 2020-04-08 22:12
Still I have no idea how to use these examples. 
I tied to make a node with Bot.cs as script then set the resource Stats with the BotStats but obviously it is a "script"  so it not work. How I can set BotStat as "BotStat" class?

**Comment by git2013vb** [comment] 2020-04-08 22:53
Finally I understood how to make it work - I hope, who never know if there are multiple way. Yeah the documentation barely scratch the surface.
Its a trend :) Every step I have to write questions/ ask help/ open issue that aren't :).

**Comment by Keelar** [comment] 2021-07-09 00:42
Why am I getting these errors on classes that I only reference in code? I thought the whole point of requiring a parameterless constructor was for things like nodes and scenes that can be instanced by the editor? Do I need to provide a parameterless constructor for any class that extends Godot.Object and if so why? Everything works fine if I just ignore them but I really don't like just ignoring errors and a lot of these classes *require* parameters and putting in a bunch of useless constructors just to get rid of the errors is annoying.

**Comment by neikeq** [comment] 2021-07-09 19:22
@Keelar Yes, for all classes extending `Godot.Object`. This is needed to get the default value of exported fields, for the inspector. I'm thinking of changing the way this works in Godot 4.0 or 4.1 though.

**Comment by Keelar** [comment] 2021-07-09 22:11
I would definitely like to see this change. Couldn't you just make them initialize to null if a parameterless constructor doesn't exist? Or throw the error from the node that exports a property of a type without a parameterless constructor?

**Comment by git2013vb** [comment] 2023-04-03 08:04
> Is this still relevant in Godot 4.0?

I cannot confirm it. Currently I don't use C#

**Comment by dashdotdashdot** [comment] 2023-10-25 10:50
> Is this still relevant in Godot 4.0?

The error message is now `ERROR: System.MissingMemberException: Cannot create script instance. The class '<MyClassNameWouldBeHere>' does not define a parameterless constructor.` but the issue is otherwise the same.

**Comment by raulsntos** [comment] 2024-07-28 04:27
- Fixed by https://github.com/godotengine/godot-docs/pull/6525

**Closed by raulsntos** 2024-07-28 04:27 UTC
Labels: topic:dotnet
