### ISSUE TITLE
Clicking on Control nodes in the scene editor marks a scene as having unsaved changes

### ISSUE THREAD

**Issue by ibrahn** [godotengine/godot#18937] opened 2018-05-16 17:45 UTC
**Godot version:**
045451e58d847201017042b052b54198688bb288

**Issue description:**
Clicking on Control nodes in the scene editor marks the scene as having changed.
(diff of  the saved scene before and after shows no changes)
Looks like it might be something to do with text properties, as each click prints `Set hint_tooltip` to the output. Control nodes with additional text properties will print a line for each of those too. For example, a Label node prints `Set text` and `Set hint_tooltip` with each click.

**Steps to reproduce:**
Add a Control node to an empty scene and save it.
Click on the Control in the scene view.
Scene is now marked changed (the asterisk appears on the scene tab and closing the scene will prompt you to save).

**Comment by groud** [comment] 2018-05-17 08:38
I though it was my fault (from the 2D editor rework), but as @akien-mga says it looks like a really recent regression. I tagged it as a bug.

**Comment by hetdegon** [comment] 2018-05-18 14:41
I was going to open an issue about scenes being marked as changed all the time, even immediately after saving, but I guess it's because of this?

**Closed** 2018-05-19 22:07 UTC
Labels: bug, topic:editor
