### ISSUE TITLE
AnimationPlayer Node can't see custom methods in InBuilt Scripts

### ISSUE THREAD

**Issue by peaposto** [godotengine/godot#55135] opened 2021-11-19 17:02 UTC
### Godot version

3.4 Stable

### System information

Windows 10

### Issue description

It's impossible to call functions defined in an In Built Script from the animationPlayer Node

### Steps to reproduce

1)Add an in built script to any node and define a new method
2)Add an animationPlayer node
3)Your method will not be available in the call method track

### Minimal reproduction project

[AnimatioPlayerBug.zip](https://github.com/godotengine/godot/files/7571754/AnimatioPlayerBug.zip)

**Comment by Calinou** [comment] 2021-11-19 17:51
Duplicate of https://github.com/godotengine/godot/issues/27351.

**Closed by Calinou** 2021-11-19 17:51 UTC
