### ISSUE TITLE
Cannot assign to constant variables using inherited constants/enums

### ISSUE THREAD

**Issue by TGRCdev** [godotengine/godot#21415] opened 2018-08-25 18:16 UTC
**Godot version:**
``master`` branch
Commit 2db494267b2924989900e968bdb898d8ab50c8f5

**OS/device including version:**
Ubuntu 18.04

**Issue description:**
When a script inherits another script that contains a ``constant`` or set of ``enums``, they cannot be assigned to new ``constants``, else it will throw ``Parse Error: Expected constant expression``.

Attempting to assign to the inherited ``constant`` also throws ``Parse Error: cannot assign a new value to a constant``, so they're still treated as constants for assignments TO them, but not constant assignments FROM them.

**Steps to reproduce:**
1. Write a ``.gd`` file that has a ``const`` value, or a set of ``enum`` values in it.
2. Extend that original ``.gd`` file and declare a new ``const`` using one of the base script's constant values
3. The editor will show a parse error stating that the ``const`` assignment expected a constant expression.

**Minimal reproduction project:**
[IssueProject.zip](https://github.com/godotengine/godot/files/2321104/IssueProject.zip)

**Comment by allkhor** [comment] 2018-08-26 12:47
Also reproduced on **2.1** branch.

**Comment by akien-mga** [comment] 2018-08-27 07:14
CC @vnen

**Comment by vnen** [comment] 2018-08-27 15:40
I think there was an older issue about this.

**Comment by Chaosus** [comment] 2018-09-13 19:56
This issue is simular to #19818 and #20008 but im not sure is it a duplicate or not. I leave this message just for linking these issues together.

**Comment by vnen** [comment] 2018-09-16 00:55
This is a duplicate of #20008.

**Closed by vnen** 2018-09-16 00:55 UTC
Labels: bug, topic:gdscript
