### ISSUE TITLE
Godot enters an infinite loop while manipulating themes

### ISSUE THREAD

**Issue by Max-Hollywood** [godotengine/godot#39138] opened 2020-05-29 03:37 UTC
**Godot version:** 3.2.1

**OS/device including version:** Windows 10

**Issue description:** After creating a custom theme based on the editor theme, it is actually changing the editors theme.  When selecting a theme or closing the window in the theme section in the editor options menu, it causes an infinite loop.

**Steps to reproduce:**
1. Select a Control Node and create a new Theme
2. Click "Edit Theme" in the bottom panel
3. Click "Create from Current Editor Theme"
4. Change something that's noticeable, like a Button Style colour
5. Click "Editor" then "Editor Settings" then "Theme"
6. This is where it hangs.  I had a few things happen here:
  - Clicking the "revert to default" button and then selecting the "Default" Preset caused the infinite loop
  - Just selecting the "Default" Preset caused the loop
  - I just clicked "Theme" and went to close the window and caused the loop

The only message in the log is this (ignore the load_image error, that happens when I load the project).
The `Failed method` line is where the infinite loop starts.
![godotissue_infinite_theme](https://user-images.githubusercontent.com/29140168/83218171-d6e6fe00-a1b0-11ea-8a68-256695173a56.png)

**Minimal reproduction project:**

**Comment by Max-Hollywood** [comment] 2020-05-29 03:55
On a side note, while editing a theme and creating a gradient texture, the default width is 2048, so Godot UI resizes to compensate for this inside the current window:
![godotissue_slider_icon_gradient_texture_window_size](https://user-images.githubusercontent.com/29140168/83219477-c421f880-a1b3-11ea-95f4-b53ac9c2bfc0.png)

```
ERROR: texture_get_data: Condition "!texture->active" is true. Returned: Ref<Image>()
   At: drivers/gles3/rasterizer_storage_gles3.cpp:1070
ERROR: texture_get_data: Condition "!texture->active" is true. Returned: Ref<Image>()
   At: drivers/gles3/rasterizer_storage_gles3.cpp:1070
```

**Comment by FeralBytes** [comment] 2020-06-06 07:14
On Linux the infinite loop causes the editor to consume Ram out of control. This randomly happens when editing a theme.

**Comment by FeralBytes** [comment] 2020-06-07 17:33
Of Note: Godot Version 3.2.2.-beta4 has yet to crash while manipulating themes. 
Even if it did I am on Linux and used a temporary work around of setting 
``
ulimit -v 2000000
``
in the terminal that i launched Godot from.

**Comment by pycbouh** [comment] 2021-08-02 18:52
Can you reproduce this still in the `3.4-beta` releases? This UI was heavily remade as well as the logic behind it.

**Comment by FeralBytes** [comment] 2021-08-19 04:08
@pycbouh I will have to re-check when 3.4 hits release.

**Comment by YuriSizov** [comment] 2023-08-29 14:16
I'm going to close this due to the lack of updates. The theme editor itself was changed in both 4.x and 3.x since this had been reported.

**Closed by YuriSizov** 2023-08-29 14:16 UTC
Labels: bug, confirmed, topic:gui
