### ISSUE TITLE
Can't render particles in editor

### ISSUE THREAD

**Issue by ctwobosius** [godotengine/godot#71439] opened 2023-01-14 22:26 UTC
### Godot version

4.0 beta 11

### System information

EndeavourOS KDE edition, Vulkan (Mobile), RTX 2060

### Issue description

Tried making sphere particles in a GPUParticles3D, it shows up in game but not in the editor, for the Mobile renderer option.

Editor error message is not helpful for end user: ```Vertex amount (4) must be a multiple of the amount of vertices required by the render primitive (3).```

Edit: it appears to happen with any sort of particle, not just sphere ones.

Workaround is to first set the Pass 1 then set the Process Material.

### Steps to reproduce

1) Add a GPUParticles3D.

2) Set its process_material to a new ParticleProcessMaterial

3) Set its Pass 1 to a sphere mesh and decrease the radius or height from the default (eg: 0.25m)

### Minimal reproduction project

[bug.zip](https://github.com/godotengine/godot/files/10418997/bug.zip)

**Comment by clayjohn** [comment] 2023-01-16 19:20
This seems related to https://github.com/godotengine/godot/issues/69156

**Comment by clayjohn** [comment] 2023-01-18 05:49
Ah, actually this is a duplicate of https://github.com/godotengine/godot/issues/71439

**Closed by clayjohn** 2023-01-18 05:49 UTC
Labels: bug, topic:rendering, topic:3d

**Comment by akien-mga** [comment] 2023-01-18 07:55
> Ah, actually this is a duplicate of #71439

You referenced this very issue :)

**Comment by clayjohn** [comment] 2023-01-18 16:20
> > Ah, actually this is a duplicate of #71439
> 
> You referenced this very issue :)

Whoops, should be https://github.com/godotengine/godot/issues/69454

Duplicate of https://github.com/godotengine/godot/issues/69454
