### ISSUE TITLE
Cannot set mipmaps/filter defaults on texture imports from gltf files

### ISSUE THREAD

**Issue by elvisish** [godotengine/godot#52948] opened 2021-09-22 20:22 UTC
### Godot version

3.3 stable

### System information

Windows 7 64-bit

### Issue description

I've set the texture imports in both Project Settings and the node import tab, but textures still come in with filter and mipmaps on:
![image](https://user-images.githubusercontent.com/16231628/134415925-e2bdbb02-bead-4f0d-b9bc-1ed036777938.png)
![image](https://user-images.githubusercontent.com/16231628/134415943-27624baa-3229-48c4-b953-97e440e0a7b2.png)

A gltf file exported from blender always imports like this:
![image](https://user-images.githubusercontent.com/16231628/134416119-a5b141c4-600d-48db-a149-1ecb3627519d.png)

This happens with both built-in materials and unpacked files:
![image](https://user-images.githubusercontent.com/16231628/134416032-17bfcb00-7560-4af2-ab41-c132c027384e.png)
![image](https://user-images.githubusercontent.com/16231628/134416059-26bf6794-53ec-4278-909a-1843d9fe94c8.png)

### Steps to reproduce

Export a gltf in blender, watch as Godot does not import with the texture defaults it's been given.

**Comment by Calinou** [comment] 2021-09-22 21:09
Duplicate of https://github.com/godotengine/godot/issues/45206.

**Closed by Calinou** 2021-09-22 21:09 UTC
Labels: bug, needs testing, topic:import, topic:3d

**Comment by elvisish** [comment] 2021-09-22 21:33
> Duplicate of #45206.

The other issue doesn't mention mipmaps?

**Comment by Calinou** [comment] 2021-09-22 22:39
> The other issue doesn't mention mipmaps?

It's still the same underlying cause :slightly_smiling_face:

**Comment by elvisish** [comment] 2021-09-22 23:56
> > The other issue doesn't mention mipmaps?
> 
> It's still the same underlying cause 🙂 I edited the other issue's title accordingly.

Just for reference of anyone coming across this, is the present solution to use a) built-in materials or separate files and b) to manually change the mipmap and filter settings on each material?

**Comment by Calinou** [comment] 2021-09-23 00:27
> Just for reference of anyone coming across this, is the present solution to use a) built-in materials or separate files and b) to manually change the mipmap and filter settings on each material?

You can use non-embedded textures and change the flags on the textures in the Import dock.

**Comment by elvisish** [comment] 2021-09-23 07:21
> > Just for reference of anyone coming across this, is the present solution to use a) built-in materials or separate files and b) to manually change the mipmap and filter settings on each material?
> 
> You can use non-embedded textures and change the flags on the textures in the Import dock. If you still want to use embedded textures, you'll have to use a script on the MeshInstance to toggle filter/mipmaps on its textures at run-time.

Does non-embedable mean this?

![](https://user-images.githubusercontent.com/16231628/134416059-26bf6794-53ec-4278-909a-1843d9fe94c8.png)

And change flags manually on each one like this?

![](https://user-images.githubusercontent.com/16231628/134416119-a5b141c4-600d-48db-a149-1ecb3627519d.png)

**Comment by Calinou** [comment] 2021-09-23 15:23
> Does non-embedable mean this?

Yes, but make sure the individual texture files are separate as well (i.e. not embedded within the `.material`) file. Also, consider using the **Files (.tres)** option to use a more VCS-friendly text format instead of a binary format.

> And change flags manually on each one like this?

Yes, but you need to do it from a script or your changes will be lost upon running the project or reimporting the glTF (depending on whether you've set materials to be kept on reimport).

**Comment by elvisish** [comment] 2021-09-24 22:38
> > Does non-embedable mean this?
> 
> Yes, but make sure the individual texture files are separate as well (i.e. not embedded within the `.material`) file. Also, consider using the **Files (.tres)** option to use a more VCS-friendly text format instead of a binary format.
> 
> > And change flags manually on each one like this?
> 
> Yes, but you need to do it from a script or your changes will be lost upon running the project or reimporting the glTF (depending on whether you've set materials to be kept on reimport).

In my experience:

- glTF cannot be made into insrtanced scene easily, so useless if I want to add a script or collider.
- glb + seperate materials take up glb size * 2 due to the materials having the images embedded in them
- glb + tres takes up 10x space as tres is awful for storing texture images
- all the above are useless at following the project import settings (filter, mipmaps) and just totally ignore that part, leaving you to manually fix each and every texture import setting
- gltf + serperate material or tres takes up about 1/4 as much space (tres slightly less) as glb built-in and respects import settings but no isntanced scenes (and the folder looks terrible with 20 files instead of 1)

So far, I've found no good solution for importing an object, having it respect my texture import settings and being able to turn it into an instanced scene to add scripts or colliders or whatever to.
