### ISSUE TITLE
LightOccluder2D warning isn't disappearing

### ISSUE THREAD

**Issue by Muller-Castro** [godotengine/godot#35722] opened 2020-01-29 23:58 UTC
**Godot version:**
3.2 stable

**OS/device including version:**
Windows 10

**Issue description:**
The warning about the occluder polygon isn't disappearing after the polygon is set

**Steps to reproduce:**
![LightOccluder2D](https://user-images.githubusercontent.com/37383316/73408047-b29a1400-42d9-11ea-8641-3ae837759818.gif)

**Minimal reproduction project:**

**Comment by Calinou** [comment] 2020-01-30 00:10
Duplicate of #21225.

**Closed by Calinou** 2020-01-30 00:10 UTC
