### ISSUE TITLE
[FBX] Maya to Mixamo Animation is Broken

### ISSUE THREAD

**Issue by likeich** [godotengine/godot#45930] opened 2021-02-12 19:18 UTC
**Godot version:**
3.3 RC 6

**OS/device including version:**
Windows 10 20H2, RTX 2060

**Issue description:**
Character assets from Synty Studios (who use Maya) that are uploaded to Mixamo for animations and then imported into Godot break when the Mixamo animation is played.

**Steps to reproduce:**
Upload the FBX asset to Mixamo and choose an animation. This issue has shown up with every animation I have tried, so the one chosen shouldn't matter (I chose the male Breathing Idle animation though).

Download the animation with the following settings. I've tried others and those haven't worked either.

![Screenshot 2021-02-12 140647](https://user-images.githubusercontent.com/57882701/107811043-91b52d00-6d3b-11eb-9c96-9afb2695eb0f.png)

Then import the model into Godot. I applied the texture here but the same outcome happens either way.

![Screenshot 2021-02-12 141304](https://user-images.githubusercontent.com/57882701/107811713-99c19c80-6d3c-11eb-8879-2dd0e57c0ee3.png)

Play the Mixamo animation in the AnimationPlayer for an instant Cronenberg Monster.

![Screenshot 2021-02-12 141516](https://user-images.githubusercontent.com/57882701/107811802-c1186980-6d3c-11eb-9407-910a6ad32081.png)

**Minimal reproduction project:**
I'm using a paid-for asset so I will not post it publicly. I can send it to an individual upon request.

**Comment by Calinou** [comment] 2021-02-12 20:35
cc @RevoluPowered

**Comment by likeich** [comment] 2021-03-23 23:43
Confirmed still an issue as of 3.3 RC 6

**Comment by likeich** [comment] 2021-05-29 15:31
Confirmed still an issue as of 3.3.2


https://user-images.githubusercontent.com/57882701/120075950-5ed84000-c071-11eb-8e5a-ac199598be8f.mp4

**Comment by AgentSmith0** [comment] 2021-08-07 08:42
I have the same problem with Godot 3.3.2. But Godot is not the only one having problems with the characters of Synty Studios. Blender has also problems when you import them.

**Comment by AgentSmith0** [comment] 2021-08-07 09:05
Here is a program that can import FBX correctly: https://github.com/Adjam93/threejs-model-viewer It uses three.js.

**Comment by Calinou** [comment] 2021-08-07 11:47
> I have the same problem with Godot 3.3.2. But Godot is not the only one having problems with the characters of Synty Studios (even when imported with other format than FBX, like GLB).

Unfortunately, without access to the specific models, there's nothing we can do about this issue.

**Comment by AgentSmith0** [comment] 2021-08-07 12:28
Here are some links: https://www.youtube.com/watch?v=9H0aJhKSlEQ
A reproduction should be possible with the following files: https://www.dropbox.com/s/unnye4cpmdlqhzs/Mixamo_SyntyStudios.zip, use Mixamo_Simple_Guy.fbx

**Comment by AgentSmith0** [comment] 2021-08-07 12:37
I attached an animated fbx that is exported from Mixamo, which is not working in Godot and not in Blender. Then I attached the same model with animation exported from Mixamo as dae, which is working in Godot and Blender.

**Comment by AgentSmith0** [comment] 2021-08-07 13:49
It looks like even Blender has these problems: https://blenderartists.org/t/maya-to-blender-fbx-import-for-rig-issue/1154371

**Comment by AgentSmith0** [comment] 2021-08-18 06:55
Is there a any fix or workaround, because this problem makes it unable for me to finish my work?

**Comment by Calinou** [comment] 2021-08-18 13:43
> Is there a any fix or workaround, because this problem makes it unable for me to finish my work?

I don't know of any such workaround, other than finding a 3D program which can import the FBX correctly then export to another format supported by Godot such as glTF or Collada.

**Comment by AgentSmith0** [comment] 2021-09-11 15:22
There's an open source 3d library in javascript called Three.js (https://github.com/mrdoob/three.js). They are able to import animations of Maya FBX files correctly. Maybe that helps.

**Comment by akien-mga** [comment] 2022-04-06 22:19
This is probably fixed with the new FBX importer using [FBX2glTF](https://github.com/V-Sekai/FBX2glTF/releases).
You can test it in Godot 4.0 alpha 6: https://godotengine.org/article/dev-snapshot-godot-4-0-alpha-6
This new importer might also be backported for the `3.x` branch eventually.

If you still find issues with these models using the new importer, we suggest opening a new issue with details about the problems in Godot 4.0 alpha 6 or later.

**Closed by akien-mga** 2022-04-06 22:19 UTC
Labels: bug, topic:import, topic:3d
