### ISSUE TITLE
[BUG] Color hint in shaders causes a shader compilation error

### ISSUE THREAD

**Issue by Monniasza** [godotengine/godot#83728] opened 2023-10-21 13:27 UTC
### Godot version

v4.1.2.stable.mono.official [399c9dc39]

### System information

v4.1.2.stable.mono.official [399c9dc39]

### Issue description

I'm unable to use color hints to make an atmosphere shader
Log:
```
Godot Engine v4.1.2.stable.mono.official (c) 2007-present Juan Linietsky, Ariel Manzur & Godot Contributors.
  modules/gltf/register_types.cpp:73 - Blend file import is enabled in the project settings, but no Blender path is configured in the editor settings. Blend files will not be imported.
--- Debug adapter server started ---
--- GDScript language server started ---
  :3 - Oczekiwana prawidłowa podpowiedź typu po znaku ':'.
  Shader compilation failed.
  res://atmosphere.gdshader:3 - Oczekiwana prawidłowa podpowiedź typu po znaku ':'.
  Shader compilation failed.
--Main Shader--
    1 | shader_type canvas_item;
    2 | 
E   3-> uniform vec3 atmosphere_color : hint_color = vec3(0.5, 0.5, 1.0);
    4 | uniform float atmosphere_radius : hint_range(0.001, 2.0) = 1.2;
    5 | uniform float atmosphere_density : hint_range(0.001, 0.1) = 0.05;
    6 | 
    7 | void fragment() {
    8 |  vec3 ray_dir = normalize(-frag_coord);
    9 |  float distance = length(ray_dir);
   10 |  float atmosphere_scale = atmosphere_density * distance;
   11 |  COLOR = mix(atmosphere_color, COLOR, exp(-atmosphere_scale));
   12 | }
   13 | 
--res://atmosphere.gdshader--
    1 | shader_type canvas_item;
    2 | 
E   3-> uniform vec3 atmosphere_color : hint_color = vec3(0.5, 0.5, 1.0);
    4 | uniform float atmosphere_radius : hint_range(0.001, 2.0) = 1.2;
    5 | uniform float atmosphere_density : hint_range(0.001, 0.1) = 0.05;
    6 | 
    7 | void fragment() {
    8 |  vec3 ray_dir = normalize(-frag_coord);
    9 |  float distance = length(ray_dir);
   10 |  float atmosphere_scale = atmosphere_density * distance;
   11 |  COLOR = mix(atmosphere_color, COLOR, exp(-atmosphere_scale));
   12 | }
   13 | 
```

### Steps to reproduce

1. Open the attached project in Godot
2. Use the given shader in a new shader material

### Minimal reproduction project

[shaderbug.zip](https://github.com/godotengine/godot/files/13060783/shaderbug.zip)

**Comment by bitsawer** [comment] 2023-10-21 13:35
Thanks for the report. `hint_color` has been renamed to `source_color` in Godot 4, so closing as this is not a bug. However, there is a PR that would give a more helpful error message in this case: https://github.com/godotengine/godot/pull/82548

**Closed by bitsawer** 2023-10-21 13:35 UTC
