### ISSUE TITLE
Blocking DNS resolves stalling game

### ISSUE THREAD

**Issue by LoneDespair** [godotengine/godot#56159] opened 2021-12-22 12:41 UTC
### Godot version

3.3.3.stable

### System information

Windows 10

### Issue description

Connecting to a server
while connected to a wifi without internet
have a 50% chance of stalling the client for 12 seconds on all platforms

and returns an error of "_resolve_hostname: getaddrinfo failed! Cannot resolve hostname."

### Steps to reproduce

1. Connect to a network without internet
2. Connect to a server on either WebSocketClient or NetworkedMultiplayerENet
3. 50% chance of stalling

**Comment by Calinou** [comment] 2021-12-22 17:19
This may be resolved by https://github.com/godotengine/godot/pull/53243 when using WebSocketClient.

**Comment by mhilbrunner** [comment] 2022-01-14 00:07
Closing as duplicate of https://github.com/godotengine/godot/issues/56159

**Closed by mhilbrunner** 2022-01-14 00:07 UTC
Labels: bug, topic:network
