### ISSUE TITLE
Groups of spaces in scripts automatically changing into tabs/indentation

### ISSUE THREAD

**Issue by PIZZA-ALERT** [godotengine/godot#78657] opened 2023-06-25 00:03 UTC
### Godot version

4.0.3.stable

### System information

Windows 11, ask for more info if needed, I'm not sure what else would be needed here.

### Issue description

Issue also asked about on Godot Q&A (currently unresolved): https://ask.godotengine.org/155740/godot-automatically-creating-tabs-script-template-how-that

I have a script template that I use for all my scripts. In this template, I have an instance of a long line of spaces leading to a comment (this is my commenting method of choice, putting all comments on the right). Looks like (without underscores, would be spaces):
my code  _    _    _    _    _    _    _    _    _    _    _    # my comment

It worked perfectly in prior versions, though after switching to Godot 4 it has started converting my groups of spaces into tabs. It now looks like this (with the indent carrots), despite me only including spaces there in my .gd file:
my code  >    >    >    >    >    >    >    >    >       # my comment

I cannot find a way to disable this "feature" and believe it to truly be a bug. Mr. J. Godfrey (a Godot contributor/Q&A admin I think?) believes so as well. I have taken a look at the indentation section of the editor settings but this is a different feature. I like tabs for indents, and am not trying to change that. I just don't want Godot to auto-change my spaces into indents when it sees a group of them. I understand others may, so I'm proposing there is an option created for that (or please inform me of which one it is if it exists). When I create/edit this template in Notepad, I'm able to verify that it is indeed just normal spaces.

### Steps to reproduce

1) Go to this link and download the script template I created (this program won't let me attach a .gd for some reason):
https://drive.google.com/file/d/1oXPKAn_3DulkF2oIFNYTFV3QKuNKdGz-/view?usp=sharing

2) Load it into a folder called "Objects" within your script templates folder (you may need to create this folder, found at *Godot master folder location*...Godot Engine\editor_data\script_templates\

3) Create a new script in Godot 4.0.3.stable and select this file as the template. You may need to create it on a node, type shouldn't matter.

4) Open the new script and see that the "extends" line has a bunch of tab indents when it should just be spaces.

### Minimal reproduction project

N/A, this is trivial

**Comment by capnm** [comment] 2023-06-25 10:54
Have you tried to adjust the indentation you love in your editor?
![image](https://github.com/godotengine/godot/assets/4047289/21b4ec66-6101-420b-9d09-2f594ae50aab)

**Comment by AThousandShips** [comment] 2023-06-25 11:00
This is handled by settings indeed, and desired feature, not a bug, and follows the [code style](https://docs.godotengine.org/en/stable/tutorials/scripting/gdscript/gdscript_styleguide.html)

**Comment by capnm** [comment] 2023-06-25 11:18
[default-behaviour-and-overriding-it](https://docs.godotengine.org/en/latest/tutorials/scripting/creating_script_templates.html#default-behaviour-and-overriding-it) could mention the default WS and how to change it.

**Comment by jgodfrey** [comment] 2023-06-25 14:49
I don't have a horse in this race (since I don't use script templates, as mentioned in the linked Q&A thread), but this feels strange to me.

In my view, an _indent_ refers to some amount of space added ahead of a line (or block) of text to move it away from the margin. I don't see how (or why) indent settings should make automatic adjustments to spacing _within_ a line of text - which is what's happening here.

So, to me, it's perfectly valid for indent settings to make adjustments to this, for example:

`       if $var == 10:`

However, to convert between spaces and tabs within the line seems a bit over-zealous...
`var my_var = 10            # some comment`

So, while automated modifications to leading and trailing text seems perfectly valid (and even expected when using most programmer's editors), I don't think I've ever seen an editor mess with _inner line_ spacing. 

Is this really intentional?

**Comment by AThousandShips** [comment] 2023-06-25 14:51
My bad, OP didn't add any description to show this behaviour in any screenshots I saw

That is a bit more complex yes

**Comment by capnm** [comment] 2023-06-25 14:59
> However, to convert between spaces and tabs within the line seems a bit over-zealous...
> `var my_var = 10 # some comment`

Yes, this is clearly a bug.

**Comment by AThousandShips** [comment] 2023-06-25 15:08
Note that this does *not* happen when just converting spaces normally, but must be somehow related to the templates, will look into

**Comment by AThousandShips** [comment] 2023-06-25 15:30
This is due to this part:
https://github.com/godotengine/godot/blob/3710f069293f2fde8afe33fea898c4b36fa5e943/editor/script_create_dialog.cpp#L863-L910

Will investigate a fix

**Comment by capnm** [comment] 2023-06-25 15:53
I think the `auto indent` should IMO use the default editor conversion. Here it instead of conversion to tab deletes the 4 spaces.
![image](https://github.com/godotengine/godot/assets/4047289/35995151-7fd4-4188-8735-be16350b93a7)

**Comment by AThousandShips** [comment] 2023-06-25 15:54
Please open a separate issue if one doesn't exist, this is a separate area of the code

**Comment by jgodfrey** [comment] 2023-06-25 15:56
> This is due to this part:

> Will investigate a fix

Yeah, those two `line.replace()` calls starting with the logic at line `907` seem problematic. Without looking at the implementation, I assume those replace every occurrence in the line. Seems like it'll have to be a bit smarter than that...

**Comment by AThousandShips** [comment] 2023-06-25 15:59
Working on a new fix based on the convert indent code, will update if I solve it

**Comment by capnm** [comment] 2023-06-25 16:00
> Please open a separate issue if one doesn't exist, this is a separate area of the code

Could we somehow have same code for both cases?

**Comment by AThousandShips** [comment] 2023-06-25 16:01
Not really they're in completely different part of the engine, this is handled in `CodeEdit` which operates on its own content, much more complicated and not really applicable for the conversion for a template, which doesn't even use tabs but `_TS_`.

**Comment by capnm** [comment] 2023-06-25 16:18
WDYT is the automatic Indentation meant here. Should it just call the default conversion function?

**Comment by AThousandShips** [comment] 2023-06-25 16:20
There isn't a default conversion function to call, `CodeEdit` operates on its own text

The template code converts tabs and spaces to `_TS_` that *then* gets converted to indentation on applying the template, so the code isn't compatible unfortunately

**Comment by AThousandShips** [comment] 2023-06-25 16:22
Fix for this specific bug open, if there's an issue in "Auto Indent" please open a dedicated issue to track it

**Comment by PIZZA-ALERT** [comment] 2023-06-25 17:12
Hey everyone, I just woke up to all your messages! Thank you so much for hopping on this so quickly.

I apologize for not including a visual in my post of what happens, I figured my little issue description and the steps to reproduce explained that but I can see that I should have had both. I've updated it to be more clear (hopefully)!

I am a bit confused as the conversation has gone up and down a bit, with some saying it's a bug, others saying it's something else, and others saying to open a new issue for this for some reason...can I please just get a single explanation of what the next steps are and what is truly happening with my code here? Why it's just now doing this when Godot 3.X never had the issue?

Thanks again!!

**Comment by AThousandShips** [comment] 2023-06-25 17:14
No nee issue for a different bug, and the code has massively changed since 3.x

**Comment by PIZZA-ALERT** [comment] 2023-06-25 17:21
Hmm ok, sorry if you feel like you've explained but I'm still confused - is my "issue" going to be "fixed" somehow? Should I expect to be able to use my template as intended in later releases?

**Comment by AThousandShips** [comment] 2023-06-25 17:25
It is, there's a PR open for it right now that will close it, what I was talking as a different issue is the "Auto Indent" issue that I mentioned above was a different issue, I'm sorry for causing confusion

**Comment by PIZZA-ALERT** [comment] 2023-06-25 17:29
Thanks a lot! You all rock.

I've never submitted an issue here before, Q&A has always met my needs. Should I expect a message here when the fix is released or something? Or should I just manually check when the next few patches roll out?

**Comment by AThousandShips** [comment] 2023-06-25 17:31
This will close when this is solved, will hopefully be in 4.1

**Closed** 2023-08-02 10:48 UTC
Labels: bug, topic:gdscript, topic:editor, confirmed
