### ISSUE TITLE
Rotated tiles missing collision layer on transitioning between scenes

### ISSUE THREAD

**Issue by dehboxturtle** [godotengine/godot#83849] opened 2023-10-23 15:35 UTC
### Godot version

4.2 Beta 2

### System information

Windows 11

### Issue description

I noticed that when using rotated tiles it doesn't seem to create their collision layer if you leave the scene and then come back.

Here is a video of it happening in my scene, even godot recognizes the collision layer is gone and doesn't paint it in with the debug feature for seeing collisions enabled.

[link to video because file is too big](https://www.dropbox.com/scl/fi/wiqxb4wfupea5if00bm55/Recording-2023-10-23-100805.mp4?rlkey=llf09jjxb8w4xqlz61xf5h4yx&dl=0)

### Steps to reproduce

(Turn on Visible Collisions debug option prior to reproducing)

1. Create any tileset in a tilemap. Add some collision to the tiles. 
2. Add rotated or flipped tiles using the new buttons added in this beta to Scene 1
3. Start game on Scene 1
4. From a script in Scene 1 switch to Scene 2 using the global scene switcher pattern described in [godot docs](https://docs.godotengine.org/en/stable/tutorials/scripting/singletons_autoload.html#custom-scene-switcher) 
5. Switch back to Scene 1 from Scene 2 and observe collision boxes missing from rotated/flipped tiles.

### Minimal reproduction project

[missing collisions.zip](https://github.com/godotengine/godot/files/13072832/missing.collisions.zip)

Repro project with some simple scenes and tilemap set up already so you can just walk on the scene switch triggers to observe the issue.

**Comment by AThousandShips** [comment] 2023-10-23 16:35
Duplicate of https://github.com/godotengine/godot/issues/83825

**Closed by AThousandShips** 2023-10-23 16:35 UTC
