### ISSUE TITLE
Sprite.set_region_rect not work as expected on iOS

### ISSUE THREAD

**Issue by alexzheng** [godotengine/godot#11656] opened 2017-09-28 11:38 UTC
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
godot 2.1
iOS

**Issue description:**

use Sprite.set_region_rect to simulate a rolling road
It can work well on Mac OS and Android, but when run a iOS device, the animation will become oddly when run for a long time
see the demo project.

**Steps to reproduce:**

**Link to minimal example project:**

[road.zip](https://github.com/godotengine/godot/files/1340663/road.zip)

**Comment by KoBeWi** [comment] 2020-06-13 15:07
Closing, because there was no reply. The issue can be reopened if someone manages to reproduce it in Godot 3.2.1 or newer.

**Closed by KoBeWi** 2020-06-13 15:07 UTC
Labels: bug, platform:ios, topic:rendering
