### ISSUE TITLE
Adding new track to `Inherited` `AnimationPlayer` does not show an error

### ISSUE THREAD

**Issue by tavurth** [godotengine/godot#58689] opened 2022-03-02 17:05 UTC
### Godot version

v3.4.3.official

### System information

Mac OSX (Intel 2019)

### Issue description

When opening an inherited scene that contains an `AnimationPlayer` such as a `.fbx` file or a `.gltf`, the animation player can be edited and new tracks can be added.

These tracks however do not actually function in the real game. Example:

1. I wanted to call a function at `0.5 seconds` into one animation
2. I add a method track and specify the function
3. The function is never called

This seems to be because even though I can add tracks in the inspector, they are not added to the final AnimatinPlayer because it's an inherited one?

### Steps to reproduce

1. Import a `.gltf` with animations
2. Add an animation track
3. See if the animation track plays when running the game

I would expect that this should show an error while adding, as it's quite easy to waste some time on this because it seems like everything is working 😞

**Comment by Calinou** [comment] 2022-03-02 17:29
Duplicate of https://github.com/godotengine/godot/issues/34394 (same cause).

**Closed by Calinou** 2022-03-02 17:29 UTC
Labels: bug, topic:editor, usability, topic:animation

**Comment by tavurth** [comment] 2022-03-02 17:32
Thanks!
