### ISSUE TITLE
EmitSignal and string argument causes silent crash

### ISSUE THREAD

**Issue by fouf** [godotengine/godot#69321] opened 2022-11-29 00:50 UTC
### Godot version

4.0 beta 5 and beta 6

### System information

Windows 10 x64 Vulkan

### Issue description

Emitting lots of signals with a string parameter causes a crash. I'm using the new C# signal delegates. The editor keeps on running but the game will crash with no error. I was running into this problem during development when emitting 30-40 signals a second.  I've tried a parameter-less signal and it seemed to not crash, so it may have something to do with the StringNames that are generated with each click.

### Steps to reproduce

I've made a demo project that emits 10000~ signals when you push the button. If you push it a bunch it will eventually crash with no error, editor should keep running. The test scene name is 'aaa'.

Just set up any signal with a string parameter and emit the signal a lot. It seems less signal calls can cause it to crash if the game is under load doing other things. It should crash like the demo project.

### Minimal reproduction project

[signal_crash_2.zip](https://github.com/godotengine/godot/files/10108740/signal_crash_2.zip)

**Comment by raulsntos** [comment] 2022-11-29 01:48
Duplicate of https://github.com/godotengine/godot/issues/67563

**Closed by raulsntos** 2022-11-29 01:48 UTC
