### ISSUE TITLE
GridContainer autodetects wrong Nodes as focus neighbors

### ISSUE THREAD

**Issue by JapanYoshi** [godotengine/godot#46812] opened 2021-03-09 06:58 UTC
**Godot version:**
3.2.3.stable.mono.latest

**OS/device including version:**
Windown 10

**Issue description:**
Whenever I use a GridContainer, neighbor detection does not work.

`focus_neighbor_bottom` selects the node to the bottom left.
`focus_neighbor_top` and `focus_neighbor_left` select the node to the top left.
`focus_neighbor_right` selects the node to the top right.

Visually, this is what Godot does:
    - - - - - # C - center node, currently focused
    - * - R - # R - focused by ui_right
    - - C - - # B - focused by ui_down
    - B - - - # * - focused by ui_up and ui_left

**Steps to reproduce:**
1. Set up a `GridContainer` with lots of `Node`s as children (for example, `Button`s).
2. Click on one of them  to give it focus
3. Press arrow keys to change focus

**Minimal reproduction project:**

[Test.zip](https://github.com/godotengine/godot/files/6106442/Test.zip)
This also demonstrates my use case for `GridContainer`: to create an on-screen keyboard for signing your high score.

**Comment by retrotails** [comment] 2021-06-26 00:31
can confirm on v3.3.2.stable.arch_linux, also this appears to be a dupe of https://github.com/godotengine/godot/issues/42965 as we all have Hseparation/Vseparation to zero. my annoying workaround is 1px undersized buttons and 1px V/H separation.

**Comment by Calinou** [comment] 2021-06-26 00:35
Duplicate of https://github.com/godotengine/godot/issues/42965.

**Closed by Calinou** 2021-06-26 00:35 UTC
Labels: bug, topic:gui
