### ISSUE TITLE
tres files failing to open

### ISSUE THREAD

**Issue by wrac4242** [godotengine/godot#49929] opened 2021-06-26 20:35 UTC
### Godot version

v3.3.2.stable

### System information

Fedora 33

### Issue description

Error opening .tres file which was created in the editor 

On a double click of the file with the .tres ending it fails to open and has the below error
```
scene/resources/resource_format_text.cpp:1195 - res://plan.tres:1 - Parse Error: Expected '['
 scene/resources/resource_format_text.cpp:848 - res://plan.tres:1 - Parse Error: Expected '['
 Failed to load resource 'res://plan.tres'.
 Failed loading resource: res://plan.tres. Make sure resources have been imported by opening the project in the editor at least once.
 editor/editor_node.cpp:947 - Condition "!res.is_valid()" is true. Returned: ERR_CANT_OPEN
```

### Steps to reproduce

Take the below file and try to open the `plan.tres` file inside godot with a double click
The file will not open and the console will have the error listed above

method 2:
create a new resource of type TextFile
save it in the project
close the tab in the editor 
try to reopen it

### Minimal reproduction project

[bug_minimal.zip](https://github.com/godotengine/godot/files/6720664/bug_minimal.zip)

### edits
added another method for reproduction

**Comment by Calinou** [comment] 2021-06-26 21:30
`test.tres` contains just "test case". How did you save the file in question? The script editor's TextFile functionality shouldn't be used to edit `.tres` files directly.

**Comment by wrac4242** [comment] 2021-06-26 21:36
the tres file was created inside godot itself by making a new resource, then selecting TextFile as the type, and then opening it up in the editor. On this it successfully opens and allows me to edit it. but after closing the file it has issues reopening it

the reason why I am editing a tres file is because its stated as a TextFile in the New Resource menu and it does not allow me to open txt files inside the editor itself

**Comment by Calinou** [comment] 2021-06-26 22:07
Duplicate of https://github.com/godotengine/godot/issues/21787.

**Closed by Calinou** 2021-06-26 22:07 UTC
Labels: topic:editor
