### ISSUE TITLE
UNUSED_CLASS_VARIABLE when used in ternary if

### ISSUE THREAD

**Issue by Drauthius** [godotengine/godot#31268] opened 2019-08-10 13:02 UTC
**Godot version:** 3c7327da332c6bf56f8c2a8e601a13fa718ede05

**OS/device including version:** Gentoo Linux

**Issue description:** When a class variable is only used in the condition part of a ternary if, a warning in the editor is produced.

**Steps to reproduce:**
```gdscript
export var s = "monkey"

func _ready():
    print("a" if s == "monkey" else "b")
```

Results in the error:
`LINE 3 (UNUSED_CLASS_VARIABLE): The class variable 's' is declared but never used in the script.`

**Comment by YeldhamDev** [comment] 2019-08-10 13:17
Duplicate of #29131.

**Closed by YeldhamDev** 2019-08-10 13:17 UTC
