### ISSUE TITLE
Cannot represent string as int64 in compare

### ISSUE THREAD

**Issue by fire** [godotengine/godot#33800] opened 2019-11-21 18:25 UTC
**Godot version:**
https://github.com/godotengine/godot/commit/37b230fe3af3c7e20a6f938d03b61a79b117d354

**OS/device including version:**
Fedora 31

**Issue description:**

```
ERROR: to_int: Cannot represent 12501374198249454378.jpg as integer, provided value is too big.
   At: core/ustring.cpp:2166.
```

![Screenshot from 2019-11-21 10-24-00](https://user-images.githubusercontent.com/32321/69365374-11dc0800-0c49-11ea-92bc-6fb2f548f428.png)

https://github.com/godotengine/godot/blob/083d088de3fe7cd5d825cebebc46ce32fc87b4b0/core/ustring.cpp#L537-L557

Convert a string to in64 fails. Maybe try comparing digit by digit?

**Steps to reproduce:**
Load https://github.com/KhronosGroup/glTF-Sample-Models/archive/master.zip in a Godot project.

**Minimal reproduction project:**
None.

**Comment by Bakainkorp** [comment] 2019-11-21 19:13
I might be misunderstanding, but I think it's as simple as the string, in Int64, overflows. The value you're trying to convert is 12.501.374.198.249.454.378. On the other hand, MAX_INT64 is 9.223.372.036.854.775.807.

If the string were to be compared in Int64, with it being larger than Int64, then there are a couple of ways to do the comparison, although I don't think it should be done if the strings themselves are already larger than Int64.

1. You can count the number of numerical characters in the string, so if it's one string has more characters than the other, the comparison can be done.
2. The two strings can be compared starting from the leftmost digit, if they have the same number of numerical characters, going right until there is a discrepancy. 
3. Barring all else, a secondary string can be used to represent the values above the MAX_INT64 threshold. However, I think that if any of the solutions were to be implemented, it would need to be the first two.

**Comment by aaronfranke** [comment] 2019-11-21 23:49
Duplicate of #33713

**Closed** 2019-11-22 00:05 UTC
