### ISSUE TITLE
Loading 1MiB+ image with Image.load_from_file shows var as null on debugger

### ISSUE THREAD

**Issue by estebanfer** [godotengine/godot#73016] opened 2023-02-10 02:25 UTC
### Godot version

v4.0.rc1.official.8843d9ad3

### System information

Windows 10, Lubuntu 20.04

### Issue description

Loading a large image (1024KiB of memory or more it seems) using `Image.load_image_from_file()` shows the variable as `<null>` on the debugger, though it shows correctly when using `print()`.
Also, creating a ImageTexture from an image that shows as null on the debugger also makes the ImageTexture to show as null
This bug doesn't seem to be on Godot 3.5.1

### Steps to reproduce

1. Create a `Node2D`, attach a script
2. Paste this code:
```gdscript
extends Node2D
func _ready():
	var image := Image.load_from_file(path_to_image)
	print(image)
```
3. Change `path_to_image` to a path of an image that would use 1024 KiB of memory or more (Double click an image on `res://` to see how much memory it would use)
4. Add a breakpoint to confirm if the `image` variable shows as `<null>` on the debugger

### Minimal reproduction project

[image_null_project.zip](https://github.com/godotengine/godot/files/10702967/image_null_project.zip)
Add breakpoints on the script to see the `<null>` on the variables
Note: I know that images from the project shouldn't be loaded with `Image.load_from_file()`, but I used it there just to make this easier to reproduce. (Same bug happens when loading images from an absolute path)

**Comment by Calinou** [comment] 2023-02-10 02:51
Duplicate of https://github.com/godotengine/godot/issues/70493.

**Closed by Calinou** 2023-02-10 02:51 UTC
