### ISSUE TITLE
[feature request] Godot Editor - Android port

### ISSUE THREAD

**Issue by blurymind** [godotengine/godot#6482] opened 2016-09-14 08:57 UTC
From a correspondence on twitter:

> todor imreorov ‏@blurymind  16h16 hours ago
> @reduzio can godot editor run on #android to develop games on mobile like #love2d  can? Would love to have it on my galaxy tab :D 
> 
> Juan Linietsky ‏@reduzio  14h14 hours ago
> @blurymind would not be difficult to do, but not a priority for the main devs. If anyone wants to contribute this work be welcome.

Basically Godot can compile games to android, but the actual editor doesnt have a port yet.
With the rise of android based tablets, I see more and more people use their tablet with a keyboard for work.
As an owner of an android galaxy note 10.1 and someone who spends 4 hours travelling on the train every work day, I started contemplating using that time to do some coding.

Unfortunately there are not many options at the moment, because most game engines have a huge footprint. The only I found that works well is Love2d, but to develop for it you dont have nice things such as code autocompletion on android.
https://love2d.org/

I think that having the editor also work on mobile devices would be a great way to take advantage of it's small footprint and bring to those platforms something that is currently not very available for them.

@reduz  says it's not difficult to do, and work would be welcome.

So who is interested in doing a port, what would the possible technical issues of such port be?

**Comment by akien-mga** [comment] 2016-09-14 09:07
Duplicate of #267.

**Comment by blurymind** [comment] 2016-09-14 09:22
here is love2d on the android store btw
https://play.google.com/store/apps/details?id=org.love2d.android

having Godot at the playstore will give it more exposure, as there is currently no competition - apart of love2d.

There is seriously no other game engine editor on there atm

**Comment by akien-mga** [comment] 2016-09-14 09:23
Let's continue the discussion in the original issue (#267) please.

**Closed by akien-mga** 2016-09-14 09:23 UTC
