### ISSUE TITLE
AcceptDialog theme is outdated + font is blurry

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#9780] opened 2017-07-22 20:41 UTC
Godot 3.0:
Just needed an AcceptDialog in my module, which I added as child of my EditorPlugin, but I noticed it doesn't look like the rest of the editor:
![image](https://user-images.githubusercontent.com/1311555/28494434-db6dd3a2-6f2e-11e7-9f25-f949ebc6a1d6.png)

**Comment by reduz** [comment] 2017-08-22 12:38
This is not a bug, you are not placing the dialog as child of EditorPlugin::get_base_control().
As this _is_ documented in EditorPlugin, will close the issue.

**Closed by reduz** 2017-08-22 12:38 UTC
Labels: bug, topic:editor, topic:plugin

**Comment by Zylann** [comment] 2017-08-22 12:55
Oh... I think I would never have found that without casually reading all functions docs one by one xD

**Comment by reduz** [comment] 2017-08-22 13:17
yeah, I figured, but I have no idea how to document it better. Maybe in a
tutorial?

**Comment by Zylann** [comment] 2017-08-22 13:40
What the editor's tree look like is also a mystery to me, if I were to add such a dialog in a scene for a game I would probably have guessed immediately to put it under a main control that has the theme setup, otherwise that would mean setting up the theme manually as it doesn't have a parent control up in the hierarchy
