### ISSUE TITLE
[Godot 4.0] Create Version Control Metadata window has really small font

### ISSUE THREAD

**Issue by hilias** [godotengine/godot#74437] opened 2023-03-05 13:54 UTC
### Godot version

4.0

### System information

Macbook Pro, Apple M2, Screen 2560 × 1600

### Issue description

The font and UI elements on the window created are really small.
<img width="655" alt="image" src="https://user-images.githubusercontent.com/4306301/222964323-ee72e4f0-653d-44fa-9b4c-b8d0d113b851.png">

Other windows: 
<img width="690" alt="image" src="https://user-images.githubusercontent.com/4306301/222964657-f62ae04f-62c6-4601-ada1-b9b80156b8f5.png">

### Steps to reproduce

Click on Project > Version Control > Create Version Control Metadata

### Minimal reproduction project

N/A

**Comment by hilias** [comment] 2023-03-05 13:55
The theme on the window looks like the old Godot editor theme, maybe it's hardcoded?

**Comment by YuriSizov** [comment] 2023-03-05 14:01
It's the current default project theme. It's a common issue with windows added in a wrong place in the editor tree.

**Comment by akien-mga** [comment] 2023-03-06 10:37
Duplicate of #73154

**Closed by akien-mga** 2023-03-06 10:37 UTC
Labels: bug, topic:editor, topic:gui
