### ISSUE TITLE
Reduced performance Godot 4.3

### ISSUE THREAD

**Issue by ghost** [godotengine/godot#95765] opened 2024-08-18 19:34 UTC
### Tested versions

Godot 4.3 stable, Godot 4.2.2 stable

### System information

Android 11, Samsung A20 - Godot 4.3 (Forward_mobile); Android, Samsung A20 - Godot 4.2 (Forward_mobile), Windows 10 - Godot 4.3 (

### Issue description

I have an arrangement that is very sensitive to performance requirements and I noticed some changes in performance after switching from 4.2.2 to 4.3 initially, I did not fix it maybe because of the GodotJolt plugin, but no, I did not find any difference when I turned it off, but I noticed that if you look with a larger camera not at the floor textures, the fps increases in the editor itself 40-70 in the game 19-24, I found out that this probably comes from the texture, in my project there was a floor and a player and no more, even the sky was just nonsense because of the unselected texture, the po was a material with a 512 by 512 texture, I thought that maybe after exposing some standard render parameters changed to overestimated from those that were in 4.2.2, I'm just starting to develop something or I'm very poorly versed in GDScript concepts, etc., for this I'm sitting in the Godot community where another person also noticed that with the exposure, his performance dropped, he was able to sort through all the settings at least on milestones renderers and as he states his normal 60 fps changed to 40, it seems to be in 4.3 Many performance updates have been implemented.

### Steps to reproduce

I guess if you create any project in 4.3, just create a scene with a camera floor from csgmesh plane, roll material from albedo and UV Triplinear onto it and increase the size of the plane, for example, to for example 20 by 20 meters, it will be the same, I note that I had the textures and materials in the katologs folders if it is so important.

### Minimal reproduction project (MRP)

Unfortunately, I can't imagine it.

**Comment by Calinou** [comment] 2024-08-18 19:45
Please upload a minimal reproduction project[^1] to make this easier to troubleshoot.

[^1]: A small Godot project which reproduces the issue, with no unnecessary files included. Be sure to not include the `.godot` folder in the archive (but keep `project.godot`).<br><br>Drag and drop a ZIP archive to upload it. **Do not select another field until the project is done uploading.**<br><br>**Note for C# users:** If your issue is *not* Mono-specific, please upload a minimal reproduction project written in GDScript or VisualScript. This will make it easier for contributors to reproduce the issue locally as not everyone has a Mono setup available.

**Comment by Aramur230** [comment] 2024-08-18 22:13
[Desktop.zip](https://github.com/user-attachments/files/16652578/Desktop.zip)
this is test project my colleague, у него Intel i3-10110U
Intel UHD Graphics

**Comment by Aramur230** [comment] 2024-08-18 22:16
![image](https://github.com/user-attachments/assets/fe445c2a-e4cf-41b5-aa16-f55342d1c9cb)
![image](https://github.com/user-attachments/assets/3f436445-5f80-40df-9519-940b66be6b18)
my colleague has an Intel i3-10110U
Intel UHD Graphics FPS is higher by 4.2.2, however, on my Samsung A20, both projects have 47 fps

**Comment by Aramur230** [comment] 2024-08-18 22:17
tomorrow I will send the same example as a colleague, I exactly met with the fact that FPS was falling on my phone, and in the editor it was higher than in the project at launch

**Comment by Aramur230** [comment] 2024-08-18 22:20
![image](https://github.com/user-attachments/assets/d2401a57-7e80-41e5-b4b2-3b52602fa992)
![image](https://github.com/user-attachments/assets/765621df-d79c-40cc-9b25-86c4b917220d)
my colleague also noted that: FPS is 15 lower if I use forward + And on the 4.2 engine with forward + it is almost as much as 100 lower

**Comment by brcontainer** [comment] 2024-10-08 18:04
> ... my colleague has an Intel i3-10110U Intel UHD Graphics FPS is higher by 4.2.2, however, on my Samsung A20, both projects have 47 fps

On my hardware, both versions maintained a constant average of ~880fps, see:

![image](https://github.com/user-attachments/assets/d3853f2c-036c-47aa-990c-b000b00e71dc)

> Godot 4.2 on the left and 4.3 on the right.

The problem may be related to the way your hardware and drivers handle rendering. If it is old hardware, it may try to compensate for certain features, which ends up taking more time and affecting performance.

Note: don't send the `.godot` folder when reporting a issue.

Hope this helps 👍

**Comment by clayjohn** [comment] 2024-10-08 20:06
I'll go ahead and close this issue since it can't be reproduced and the OP has since deleted their GitHub account so they can't be reached for follow up questions.

**Closed by clayjohn** 2024-10-08 20:06 UTC
Labels: topic:rendering, needs testing, regression, topic:3d, performance

**Comment by dangquochuyne2024** [comment] 2024-12-20 05:51
godot 4.3 always not responding
