### ISSUE TITLE
AudioStreamPlayer (And AudioStreamPlayer2D) do not obey Volume settings when called from an AnimationPlayer being controlled by an AnimationTree

### ISSUE THREAD

**Issue by mrbaggins** [godotengine/godot#69746] opened 2022-12-08 03:49 UTC
### Godot version

4.0 beta 7 official

### System information

Win 10

### Issue description

Volume settings in inspector are not used, and the audio plays at full volume if the animation with an audio playback is managed by an AnimationTree with a StateMachine root node. The preview in the Animation Player is affected correctly, but in game audio is not.

AudioStreams on autoplay seem fine as well, as does ticking the "Playing" check box in the inspector.

### Steps to reproduce

Add an AudioStreamPlayer or AudioStreamPlayer2D
Adjust volume or pitch to -20dB or so for notable difference
Create Animation Player, Add an animation, add an audio playback track, insert a key and pick a sound the sound file.
Test the animation in the animation player to hear the reduced volume.
Code the animation to run using $AnimationPlayer.play("Animation Name") in script, hear the reduced volume in game

Add an animation Tree, set the Animation Player from before as its player. 
Add a statemachine root node
Add the animation in the statemachine.
Test the animation in the player to hear the reduced volume
Remove the $AnimationPlayer.play() code
Call "$AnimationTree.travel("Animation Name") in script instead, hear NON reduced volume.

### Minimal reproduction project

Two projects, only change is whether used .play or .travel in AnimationPlayer or AnimationTree respectively. Both set to -15dB. Both should be same volume, but are not. Headphone warning, original sound is kind of loud.
[Audio Animation Bug PLAYER.zip](https://github.com/godotengine/godot/files/10181857/Audio.Animation.Bug.PLAYER.zip)
[Audio Animation Bug TREE.zip](https://github.com/godotengine/godot/files/10181858/Audio.Animation.Bug.TREE.zip)

**Comment by TokageItLab** [comment] 2022-12-08 04:59
Duplicate of #65750

**Closed by TokageItLab** 2022-12-08 04:59 UTC
Labels: bug, archived, topic:audio, topic:animation

**Comment by TokageItLab** [comment] 2022-12-08 05:57
The workaround is to use the Method track. Well, I too would like to see this fixed as soon as possible. Maybe later 4.1? @reduz

**Comment by mrbaggins** [comment] 2022-12-08 07:21
I've already hit a separate bug in that one, call method doesn't always get hit when spammed if under 0.4 seconds~ long

**Comment by TokageItLab** [comment] 2022-12-08 07:38
Ah I remember that your issue #69382. And I still think that is probably a StateMachine issue and not a MethodTrack issue!
