### ISSUE TITLE
is_on_floor() detection is buggy

### ISSUE THREAD

**Issue by vickylance** [godotengine/godot#38566] opened 2020-05-08 11:52 UTC
**Godot version:**
v3.2.1

**OS/device including version:**
MacBook Pro - Catalina

**Issue description:**
`is_on_floor()` is returning true one frame and false another frame
<img width="206" alt="Screenshot 2020-05-08 at 3 49 07 PM" src="https://user-images.githubusercontent.com/5861833/81403168-708e3300-9150-11ea-8a0a-a5c90023039d.png">

**Steps to reproduce:**
1) Add a simple kinematic body and apply gravity only when not on floor this bug happens.

I have attached a below project with minimal reproduction

**Minimal reproduction project:**
[MinimalProject](https://drive.google.com/file/d/1VAw9Y5c5zoopi_CChoewkDVkzgjaIYb5/view?usp=sharing)

**Comment by Calinou** [comment] 2020-05-08 12:17
Duplicate of #35780.

**Closed by Calinou** 2020-05-08 12:17 UTC

**Comment by vickylance** [comment] 2020-05-08 12:37
But the KinematicBody is not in a GridMap or any edge. Its on a plain flat solid ground

**Comment by Calinou** [comment] 2020-05-08 12:57
@vickylance I think it's still the same underlying issue :slightly_smiling_face:

**Comment by madmiraal** [comment] 2020-05-08 15:26
@vickylance For `is_on_floor()` to return true, the previous call to `move_and_slide()` must result in a collision with the floor. If you update the velocity with the post collision velocity, after colliding with the floor the velocity in the `y` direction will be 0. However, if you also then choose not to apply gravity, the velocity passed to the next call to `move and slide()` in the `y` direction will be 0. Therefore, the next call to `move_and_slide()` won't result in a collision with the floor, and `is_on_floor()` correctly returns `false`.

**Comment by jcarlosrc** [comment] 2020-07-27 01:18
This is not "correct". If the body is already colliding with the floor the physics engine should return true. This is, is_on_floor should return true if the body is already touching the floor even if vel.y is 0.
