### ISSUE TITLE
Insufficient processing of RigidBody in the physics engine

### ISSUE THREAD

**Issue by DimitriyPS** [godotengine/godot#44664] opened 2020-12-24 18:27 UTC
**Godot version:**
2.Х / 3.Х / 4.Х (?)

**OS/device including version:**
All

**Issue description:**
How it manifests itself: RigidBody Objects that have a small size and, accordingly, a small form of collisions-in free fall fly through the forms of collisions of other physical bodies. RigidBody objects that have a relatively large size and a corresponding large collision grid fall through the collision grids of other bodies when additional effort is applied (for example, a player stepped on or pushed an object).

**Minimal reproduction project:**
My project is complex and highlighting a simple example is labor-intensive. Yes, and there were more than once these examples on github. This is not the first time I have written about this problem. And I'm not the only one who writes about it. But for many years, the situation has only changed for the worse. So I only attach videos:

https://vimple.co/0644d6538b02478a9478e872bb187dca

**More detailed:**
I will write a lot of text. Because this is a big problem. Because the Godot development team has been ignoring it for years.

Today I read the news: https://godotengine.org/article/camille-mohr-daurat-hired-work-physics

She evokes mixed feelings. I dealt with "Bullet Physics" - it is a good physics engine, good functionality, good performance, reliable work. He was very poorly and unprofessionally integrated into Godot, so only bugs worked, but in all the other products I've met him he was great. I am very regret that it will not be brought to mind. But the fact that for the first time they paid attention to the physical engine and for this a person was allocated - this gives hope. Personally for me the last hope, to continue using Godot.

Game development is my hobby. I have been using since Godot 2.x version. The problem of insufficient processing of RigidBody by the physical engine has always been. This was both in Godot Physics and in Bullet Physics. There was a noticeable improvement in Godot 3.1.1, but there it was too. Now the situation has changed for the worse.

Previously, it was possible to increase the number of frames of the physics engine - this worked. It's bad for performance, but at least it worked. In the last few versions of Godot 3.2.X, changing the number of physics frames does not give any effect.

As for the CCD, as much as I have not tested on small and large forms, it has never worked in Godot. Didn't work for NEVER.

Camille, aka PouleyKetchoupp, I really ask You not to pass by this problem, please pay attention to it. This problem alone makes the Godot from unsuitable for any project that needs simple but full-fledged physics. I am very sorry for the effort spent on the part of the project that I have already completed for a Godot Engine from, but in the meantime I am forced to plan to transfer my project to Unity 3D.

**Comment by Calinou** [comment] 2020-12-24 19:53
Duplicate of https://github.com/godotengine/godot/issues/9071.

Please don't create issues to pressure contributors. It only makes things go slower, not faster.

**Closed by Calinou** 2020-12-24 19:53 UTC
