### ISSUE TITLE
Player KinematicBody2D (using Rayshape2D and move_and_slide) make moving platform(using move_and_collide) drop down slowly together.

### ISSUE THREAD

**Issue by RonTang** [godotengine/godot#36500] opened 2020-02-24 06:11 UTC
**Godot version:** 
3.2 stable

**Bug Gif:**
![20200224_135959-10-20](https://user-images.githubusercontent.com/4351322/75131549-8aea7000-570e-11ea-8cef-06b9eaf5ebf4.gif)

**OS/device including version:** 
develop and learn using win10 

**Issue description:** 
Player(KinematicBody2D) using rayshape2D and move_and_slidenot work with moving platform(KinematicBody2D) using move_and_collide. When player standing on this moving platform, they will drop down slowly together.

**Steps to reproduce:**
100% reproduce.  Just use player jump on the moving platform.

**Minimal reproduction project:**
Please open level1 scene in the project. In the right of scene has a moving platform.
[github.zip](https://github.com/godotengine/godot/files/4243247/github.zip)

I am a newbie to godot . I believe godot is greate engine. Thanks everyone.

**Comment by RonTang** [comment] 2020-02-28 04:34
I tested a lot of situations. Only when players use **rectangleshap2d** and use the **move_and_slide** function in the script can work with the moving platform using the **move_and_collide** function.
So at current I think best way to create moving platform is using AnimationPlayer or Path2D and check the **sync with physics** of motion in KinematicBody2D.

**Comment by Janglee123** [comment] 2020-02-28 05:50
@RonTang I cant open your demo project make sure it contains project.godot file.

**Comment by RonTang** [comment] 2020-02-29 02:55
@Janglee123 Thanks your reply. I will upload again.Wait a moment

**Comment by RonTang** [comment] 2020-02-29 03:18
![20200229_111133-0-15](https://user-images.githubusercontent.com/4351322/75599976-efc61180-5ae4-11ea-8afb-2c50172b1a02.gif)

And this is mini project
[Jungle Jump.zip](https://github.com/godotengine/godot/files/4269863/Jungle.Jump.zip)
Without rayshape2d the moving platform is ok. Thanks for your help.

**Comment by fabriceci** [comment] 2021-07-04 21:20
I can't reproduce the issue in 3.2.2 stable. Note that the platform bounce on the collision normal, and the player can collide with the platform... 

```python
velocity = velocity.bounce(collision.normal)
```

**Comment by pouleyKetchoupp** [comment] 2021-07-05 17:35
Closing as the specific issue shown in the video doesn't occur anymore.

As already pointed out, using `move_and_collide` for the moving platform currently doesn't work very well though, because it will still collide and bounce on the player, so using animation should be the preferred way if possible.

Right now, it's hard to work around the limitation that collision layers are setup in a symmetrical way, so if the player collides with the platform, the platform also collides with the player. The only way I can think about would be to change collision layers before the platform calls `move_and_collide` and change it back after.

In 4.0, you will be able to setup collision layers in a way that the platform will be able to ignore the player and only collide with the environment:
https://github.com/godotengine/godot-proposals/issues/2775

**Closed by pouleyKetchoupp** 2021-07-05 17:35 UTC
Labels: bug, topic:physics
