### ISSUE TITLE
Allow access to external libraries

### ISSUE THREAD

**Issue by rogeriodec** [godotengine/godot#26896] opened 2019-03-11 03:35 UTC
**Godot version:**
3.1 RC1

**OS/device including version:**
Windows 10 x64

**Issue description:**
I want to have a unique Materials library folder for all projects. 
How can I point this external library to be used inside my project?
Currently, everything is restricted to the structure `res://`
Do I have to duplicate a giant library of materials for each project?

**Comment by vnen** [comment] 2019-03-11 04:15
Duplicate of #26617

**Closed by vnen** 2019-03-11 04:15 UTC
