### ISSUE TITLE
Editor Crash when using VS code

### ISSUE THREAD

**Issue by acedogblast** [godotengine/godot#51961] opened 2021-08-21 20:48 UTC
### Godot version

v3.3.3-stable_x11.64

### System information

Linux, GLES 2.0, AMD RX 5600XT, mesa 21.0.3

### Issue description

When opening vs code to edit a script, vs code complains that it can not connect to the godot language server due to the editor crashing. I ran the editor on the console to get this error message:
```
handle_crash: Program crashed with signal 11
Dumping the backtrace. Please include this when reporting the bug on https://github.com/godotengine/godot/issues
[1] /lib/x86_64-linux-gnu/libc.so.6(+0x46210) [0x7f2b4bd8b210] (??:0)
[2] /home/charles/Godot/Godot_v3.3.3-stable_x11.64() [0xe15f97] (??:0)
[3] /home/charles/Godot/Godot_v3.3.3-stable_x11.64() [0x2f78a1a] (??:?)
[4] /home/charles/Godot/Godot_v3.3.3-stable_x11.64() [0x2f288f5] (??:?)
[5] /home/charles/Godot/Godot_v3.3.3-stable_x11.64() [0xe50446] (??:0)
[6] /home/charles/Godot/Godot_v3.3.3-stable_x11.64() [0xe447b5] (??:0)
[7] /home/charles/Godot/Godot_v3.3.3-stable_x11.64() [0x2f2cec1] (??:?)
[8] /home/charles/Godot/Godot_v3.3.3-stable_x11.64() [0x2f2d90c] (??:?)
[9] /home/charles/Godot/Godot_v3.3.3-stable_x11.64() [0x2f64a28] (??:?)
[10] /home/charles/Godot/Godot_v3.3.3-stable_x11.64() [0x2f7fd1b] (??:?)
[11] /home/charles/Godot/Godot_v3.3.3-stable_x11.64() [0xe142e4] (??:0)
[12] /home/charles/Godot/Godot_v3.3.3-stable_x11.64() [0x1cda1ae] (??:0)
[13] /home/charles/Godot/Godot_v3.3.3-stable_x11.64() [0x1ceb9c8] (??:0)
[14] /home/charles/Godot/Godot_v3.3.3-stable_x11.64() [0x3119a3d] (??:?)
[15] /home/charles/Godot/Godot_v3.3.3-stable_x11.64() [0x990dcd] (??:0)
[16] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf3) [0x7f2b4bd6c0b3] (??:0)
[17] /home/charles/Godot/Godot_v3.3.3-stable_x11.64() [0x99f5ae] (??:0)
-- END OF BACKTRACE --
```

### Steps to reproduce

Open a script in the editor.

**Comment by acedogblast** [comment] 2021-08-21 20:53
This did not occur using v3.3.2 stable.

**Comment by Calinou** [comment] 2021-08-21 21:28
Duplicate of https://github.com/godotengine/godot/issues/51923.

**Closed by Calinou** 2021-08-21 21:28 UTC
