### ISSUE TITLE
Error awaiting on a method called via Object.Call in C#

### ISSUE THREAD

**Issue by jjmontesl** [godotengine/godot#41358] opened 2020-08-18 19:40 UTC
**Godot version:**

Godot Engine v3.2.2.stable.mono.official - https://godotengine.org
OpenGL ES 2.0 Renderer: GeForce GTX 1660/PCIe/SSE2
OpenGL ES 2.0 Batching: ON

**OS/device including version:**

Running on Ubuntu 18.04.

**Issue description:**

When calling an asynchronous method via Object.Call(), I cannot await on the result. The debugger output shows an error when marshalling the resulting `Task` object:

E 0:00:06.473   mono_object_to_variant_impl: Attempted to convert an unmarshallable managed type to Variant. Name: 'Task`1' Encoding: 21.
  <C++ Error>   Method failed. Returning: Variant()
  <C++ Source>  modules/mono/mono_gd/gd_mono_marshal.cpp:887 @ mono_object_to_variant_impl()
  <Stack Trace> :0 @ System.Object Godot.NativeCalls.godot_icall_2_582(IntPtr , IntPtr , System.String , System.Object[] )()
                Object.cs:370 @ System.Object Godot.Object.Call(System.String , System.Object[] )()
                ScriptManager.cs:116 @ void ScriptRunner+<RunStep>d__8.MoveNext()()
                :0 @ void System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start<ScriptRunner+<RunStep>d__8 >(ScriptRunner+<RunStep>d__8& )()
                :0 @ System.Threading.Tasks.Task ScriptRunner.RunStep(ScriptStep )()
                ScriptManager.cs:54 @ void ScriptRunner+<RunLoop>d__7.MoveNext()()
                :0 @ void System.Runtime.CompilerServices.AsyncVoidMethodBuilder.Start<ScriptRunner+<RunLoop>d__7 >(ScriptRunner+<RunLoop>d__7& )()
                :0 @ void ScriptRunner.RunLoop()()
                ScriptManager.cs:40 @ void ScriptRunner.Start()()
                ScriptManager.cs:211 @ void ScriptManager.Start(System.String )()
                GameMain.cs:300 @ void GameMain.SceneSewerCavernEnterClose()()
                GameMain.cs:196 @ void GameMain.Trigger(Godot.Node , Godot.Vector2 )()
                GameAreaTrigger.cs:38 @ void GameAreaTrigger._OnBodyEntered(System.Object )()

**Steps to reproduce:**

Define an async Task method:

```
public async Task RunStepText(string textStr) { 
  GD.Print(textStr);
  await ToSignal(GetTree().CreateTimer(5.0f), "timeout");
}
```

Call it via Object.Call:

```
	GDScriptFunctionState result = (GDScriptFunctionState) target.Call("RunStepText", "Test");
	await target.ToSignal(result, "completed");
	GD.Print("Call completed.");
```

The method executes, but the  "completed" signal is never received, and the error above is shown in the debugger.

**Comment by jjmontesl** [comment] 2020-08-18 19:42
Ideally, I'd furthermore suggest having CallDeferred return an Awaitable (currently returns void) or some alternative that simplifies code that waits for an async call, but I leave this considerations to the experts.

**Comment by neikeq** [comment] 2020-08-18 21:29
>Ideally, I'd furthermore suggest having versions of Call and CallDeferred return an Awaitable or some alternative that simplifies code that waits for an async call

We can make `GDScriptFunctionState` awaitable.

**Comment by neikeq** [comment] 2020-08-18 21:43
There are two things wrong here.

```cs
GDScriptFunctionState result = (GDScriptFunctionState) target.Call("RunStepText", "Test");
await target.ToSignal(result, "completed");
```

`RunStepText` returns `Task`, not `GDScriptFunctionState`. However because of the error you're getting, `Call` actually returns `null` so the cast works. If `Call` didn't fail and returned the task, then you would get an `InvalidCastException`.

The correct code would be:

```cs
await (Task) target.Call("RunStepText", "Test");
```

However, that doesn't work right now because of the error you're reporting. This error happens because right now `Call`/`Set`/`Get`/`EmitSignal` and such only support parameter and return types that can be marshalled as Variant. As such `Task` is not supported.
Sine this is the source of the issue, I'm closing it as a duplicate of #38188.

**Closed by neikeq** 2020-08-18 21:43 UTC
Labels: bug, topic:mono
