### ISSUE TITLE
GDScript some local static type declarations persist

### ISSUE THREAD

**Issue by kroppt** [godotengine/godot#27997] opened 2019-04-13 20:48 UTC
**Godot version:**
v3.1.stable.official

**OS/device including version:**
Windows 10 Education version 1809 build 17763.437

**Issue description:**
I declared a static variable in a function.
When I ran the function again, the variable was not re-instantiated.
I expect a local variable to be re-instantiated with a zero-value.
This does not happen for every type, though, and I have no idea which types one must re-instantiate.
`Vector2` outputs:
```
(1, 1)
(0, 0)
...
```
whereas `Array` outputs:
```
[1]
[1]
...
```
**Steps to reproduce:**
Declare a static variable in a function and change it. Check next time you run the function whether its value is default or still changed.

**Minimal reproduction project:**
[static_type_check.zip](https://github.com/godotengine/godot/files/3076727/static_type_check.zip)

**Comment by akien-mga** [comment] 2019-04-15 10:24
Duplicate of #24134.

**Closed by akien-mga** 2019-04-15 10:24 UTC
