### ISSUE TITLE
CanvasItem's "Clip Children" only clips children of the same Z-index

### ISSUE THREAD

**Issue by ChrisMoore0186** [godotengine/godot#75503] opened 2023-03-30 18:24 UTC
### Godot version

v4.0.stable.official

### System information

Windows 10 Home, Intel UH Graphics 630

### Issue description

Clip Children feature only works on child nodes that have the same Z-index as the parent. At _worst_ it should clip anything on the same Z-index or lower while any child on a higher Z-index is not clipped, but instead all child objects must be on the same index as the parent, limiting the ability to sort the drawing order of masked objects.

### Steps to reproduce

- Create any node that can clip children (Sprite2D is fine)
- Add a texture for the clipping mask
- Create a child node that supports clipping (another Sprite2D with a texture)
- Change the z-value of the child to be different from the parent

### Minimal reproduction project

N/A

**Comment by AThousandShips** [comment] 2023-03-30 18:27
Duplicate of #69306, please search for similar issues before opening

**Comment by Calinou** [comment] 2023-03-30 19:48
- Duplicate of https://github.com/godotengine/godot/issues/69306.

**Closed by Calinou** 2023-03-30 19:48 UTC
Labels: bug, archived, topic:rendering, topic:gui, topic:2d
