### ISSUE TITLE
Regression: Draw String and bbcode_text modulate color stopped working in 3.5!

### ISSUE THREAD

**Issue by VanDeiMin** [godotengine/godot#64709] opened 2022-08-21 22:38 UTC
### Godot version

3.5 mono

### System information

Windows 10, Gles3, nVidiaM1000M

### Issue description

after change from 3.4.2 to 3.5 I've noticed that color modulate and bbtext_color don't work anymore.

### Steps to reproduce

draw_string(font, Vector2(_x + 4.0, 26.0), str(_sec), Color("8bff66"));
label.bbcode_text += "[color=#%s] text [/color]"%Color("8bff66").to_html(true);

**Comment by KoBeWi** [comment] 2022-08-21 23:51
Can't reproduce
![image](https://user-images.githubusercontent.com/2223172/185816332-0c305a35-7cd9-46f1-8a62-0b355ea07188.png)
Please attach a minimal project.

**Comment by quentincaffeino** [comment] 2022-08-22 14:24
My project can be used as repro for bbcode issue, see https://github.com/quentincaffeino/godot-console/tree/develop/demo

Beeing affected by this, for tracking: https://github.com/quentincaffeino/godot-console/issues/88

**Comment by KoBeWi** [comment] 2022-08-22 14:52
I can't open the project, because it depends on some symbolic links.

**Comment by quentincaffeino** [comment] 2022-08-22 15:07
I guess if you run windows git doesn't automatically resolve links. Please see where `addons` folder goes in github web ui and manually replace it with a real link.

**Comment by quentincaffeino** [comment] 2022-08-22 15:08
For me it shows error in gut plugin but it doesn't matter and if you see same error just ignore it.

**Comment by KoBeWi** [comment] 2022-08-22 17:00
OK reproduced it finally
![image](https://user-images.githubusercontent.com/2223172/185975993-b3400ace-f0ed-475c-8303-2c53965d0d75.png)

Here's a minimal project:
[FontBug.zip](https://github.com/godotengine/godot/files/9396192/FontBug.zip)

It's caused by the font.

Same issue appears in 4.0. I can confirm that it does not happen in 3.4.5. Looking at the changelog, there was some FreeType update that could be the culprit.
CC @bruvzg probably.

**Comment by bruvzg** [comment] 2022-08-22 17:10
Strange, seems like an issue with the specific font.

**Comment by bruvzg** [comment] 2022-08-22 17:21
Seems like `FT_HAS_COLOR` for this font return true (usually it's true for color emoji fonts), that's why coloring is disabled. Might be caused by `freetype` update.

**Comment by bruvzg** [comment] 2022-08-22 17:29
For some reason, this font contains `SVG` table (but I do not see any SVG glyphs in it, so it's probably a bug in a font), older FreeType did not support it at all.

**Comment by VanDeiMin** [comment] 2022-08-22 17:42
Is there any chance for this issue to be resolved at Godot part and I could use SourceCodePro like in older versions,
 or should I check for another one?

**Comment by KoBeWi** [comment] 2022-08-22 17:44
Another option is editing the font file. Judging from the comments, you just need to remove a flag.

But the issue is technically a regression, so it will be fixed in some form (e.g. by making this font feature optional).

**Comment by bruvzg** [comment] 2022-08-22 17:45
> Is there any chance for this issue to be resolved at Godot 

Yes, instead of `FT_HAS_COLOR` we can check for the image format of the rendered glyph to see if it's colored. I'll make PR to fix it in a moment.

**Comment by akien-mga** [comment] 2022-08-22 17:48
You can also download a new version of SourceCodePro fonts from https://github.com/adobe-fonts/source-code-pro, that seems to solve the issue in @KoBeWi's MRP (testing with a newer version of `SourceCodePro-Regular.otf`).

**Closed** 2022-08-23 05:45 UTC
Labels: bug, confirmed, regression, topic:gui
