### ISSUE TITLE
Inspector UI bug. Can't handle nested dictionary

### ISSUE THREAD

**Issue by tanjunior** [godotengine/godot#38842] opened 2020-05-18 19:33 UTC
**Godot version:**
3.2.1
**OS/device including version:**
win10home 1909
**Issue description:**
UI bug at Inspector in remote scene view
**Steps to reproduce:**
create a new project
add a node
attach script
add a nested dictionary
`var myDict : Dictionary = {
	"layer1" : {
		"layer2" : {
			"layer3" : {
				"key" : "value"
			}
		}
	}
}`
run the game/scene
select the remote tab under Scene
choose the node that you have created
open up myDict in Inspector

[video](https://drive.google.com/file/d/1rmTJwK5wZVMMB2lQkHpYFoXZRA_2UbYt/view?usp=sharing)

**Comment by Calinou** [comment] 2020-05-18 19:43
Duplicate of #25375.

**Closed by Calinou** 2020-05-18 19:43 UTC
