### ISSUE TITLE
Pop-out menus, pop-up dialogue boxes, and right-click context menus fully grey when OpenGL3 renderer selected (only happens when 2D screen is active)

### ISSUE THREAD

**Issue by belal-sweileh** [godotengine/godot#65678] opened 2022-09-12 01:15 UTC
### Godot version

4.0.alpha16

### System information

Windows 10, RTX 2060 Super, OpenGL3

### Issue description

If the OpenGL3 renderer is selected from the project settings, and if the currently selected screen is the 2D screen, then all pop-out menus, pop-up dialogue boxes, and right-click context menus appear fully grey when nothing appears to be drawn in the 2D screen. 

In particular, this problem seems to occur only  (1) if the 2D screen is showing the empty scene, or (2) if the 2D screen is showing a scene where nothing is really being drawn to the screen, or (3) if there are nodes that draw something to the screen but can't be seen due to zooming and panning away from that content. 

Furthermore, when closing a 2D scene, whatever was shown last in the 2D screen remains visible afterwards.

However, if the screen is switched to the 3D screen, Script screen, or AssetLib screen, the mentioned menus and dialogue boxes are no longer fully grey and selections can be made as normal. Also, when the renderer is switched to Vulkan, the issue resolves itself. Below are some screenshots and a screencast that depict the issue.

Some images depicting the issue:
![2022-09-11_18-19-15](https://user-images.githubusercontent.com/95645075/189555620-db372ee0-1848-4c83-b55d-2fee592e92db.jpg)

![2022-09-11_18-18-04](https://user-images.githubusercontent.com/95645075/189555626-25768462-2056-4982-ae8f-98274dd8c889.jpg)

Screencast showing how to reproduce the issue:
https://user-images.githubusercontent.com/95645075/189557967-97fcd0d3-ca31-4013-8c81-9490fabbb36b.mp4

### Steps to reproduce

1) Create a new project
2) From "Project -> Project Settings", turn on "Advanced Settings".
3) Go to "General -> Rendering -> Driver" and select "opengl3" from the "driver name" dropdown
4) Save and restart the Godot Editor
5) Open the project again
6) Click on 2D screen
7) It should show the "[empty]" scene
8) Try performing any action that results in opening a pop-up menu or dialogue box (e.g. click on "Scene" or "Project" menus, right-click within the 2D scene, clicking on any button/tool within the Godot interface that results in opening a pop-up menu such as the "+" sign for  "Adding nodes" or the "hyperlink" button "Instantiating a child scene", or the "three dots" for managing the dock position, etc.), and this will result in a fully grey pop-out menu or dialogue box.
9) Click on the 3D screen, or the Script screen, or the AssetLib screen
10) Repeating actions described in Step 8 will not display the issue.
11) Create a new 2D scene
12) Click on the 2D screen
13) Repeating actions described in Step 8 will display the issue.
14) Try adding a Sprite2D node and you will see that it isn't possible since the "Add node" dialogue box will be fully grey
15) Click on 3D screen
16) Add a Sprite2D node as a child node
17) Click on the 2D screen
18) Repeating actions described in Step 8 will display the issue. For example, try assigning a texture to the sprite2D node and you will see that it isn't possible since the pop-out menu will be fully grey
19) Click on 3D screen
20) Click on the Sprite2D node and assign any texture to the Sprite2D (such as  a new Texture2D or simply drag the Godot logo "icon.svg" onto the Texture property field)
21) Click on the 2D screen
22) Repeating actions described in Step 8 will not display the issue.
23) Resize the sprite2D node if needed then zoom in and pan away from the Sprite2D so that it is no longer visible within the 2D screen.
24) Repeating actions described in Step 8 will display the issue.
25) Close the unsaved "2D" scene without saving.
26) You will notice that the Sprite2D node is still visible in the 2D screen even after the 2D scene was closed.  Switching between the other screens and the 2D screen will not make the previous scene disappear.
27) Click on the 2D screen
28) Repeating actions described in Step 8 will display the issue.
29) Create a new User Interface scene
30) Click on the 2D screen
31) Repeating actions described in Step 8 will display the issue. For example, try adding a RichTextLabel node as a child and you will see that it isn't possible the "Add node" dialogue box will be fully grey
32) Click on 3D screen
33) Add a RichTextLabel node as a child node
34) Click on the 2D screen
35) Repeating actions described in Step 8 will display the issue. For example, try changing the autowrap mode and you will see that it isn't possible since the pop-out menu will be fully grey
36) Click on the RichTextLabel node and assign type in any text into the "Text" property field. Add any system font to the Theme overrides section in the inspector and resize the text and RichTextLabel so that the text is visible on screen.
37) Repeating actions described in Step 8 will not display the issue.
38) Zoom in and pan away from the RichTextLabel within the 2D screen so that it is no longer visible
39) Repeating actions described in Step 8 will not display the issue.
40) Close the unsaved "User Interface" scene without saving
41) You will notice that the RichTextLabel node is still visible in the 2D screen even after the "User Interface" scene was closed.  Switching between the other screens and the 2D screen will not make the previous scene disappear.
42) Switch rendering driver back to "Vulkan" from project settings as shown in Steps 2-4
43) Repeating actions described in Step 8 will not display the issue.

### Minimal reproduction project

All that is needed is to create blank project and follow the steps above.

**Comment by Calinou** [comment] 2022-09-12 01:27
Multi-window support is known to be broken with the OpenGL renderer. Try enabling **Single Window Mode** in the editor settings then restart the editor.

**Comment by belal-sweileh** [comment] 2022-09-12 02:04
Hi. I just tried enabling "Single Window Mode" in the editor settings and restarted the editor, but it didn't resolver the issue. I followed the same steps above to reproduce the issue and I saw the same issues.

**Comment by clayjohn** [comment] 2022-09-13 00:23
Duplicate of https://github.com/godotengine/godot/issues/65510

**Closed by clayjohn** 2022-09-13 00:23 UTC
Labels: bug, topic:rendering, topic:editor, regression
