### ISSUE TITLE
Vulkan: Glow with background mode Canvas affects editor UI

### ISSUE THREAD

**Issue by crazyStewie** [godotengine/godot#70243] opened 2022-12-18 04:08 UTC
### Godot version

4.0.beta8

### System information

Manjaro Linux, gtx 1060

### Issue description

When enabling glow on a 2D scene, by setting the background mode to canvas, the effect starts affecting all editor UI elements not on the main window (drop down menus, tooltips, settings windows, etc).
<details>
  <summary>Screenshot of the Glow affecting the Editor Settings window</summary>
  
![GodotEditorGlow](https://user-images.githubusercontent.com/30158085/208280675-8d6481f9-d166-457f-8452-34daee543151.png)
  
</details>

This seems to also apply to other post processing effects

### Steps to reproduce

- Add WorldEnvironment node to 2d scene
- Create a new Environment Resource
- Set Background Mode to Canvas
- Set Tonemap exposure to 10
- Enable glow
- Set Glow Blend Mode to Additive to maximize the effect
- Glow should now appear on all editor UI besides the main windows (popups, dropdowns, tooltips, settings, etc)

### Minimal reproduction project

N/A

**Comment by clayjohn** [comment] 2022-12-18 04:21
Duplicate of https://github.com/godotengine/godot/issues/69122

Closing this so we can track it in one place

**Closed by clayjohn** 2022-12-18 04:21 UTC
