### ISSUE TITLE
TileMap editor expands to accommodate long tile name, pushing neighboring panels offscreen

### ISSUE THREAD

**Issue by TypesLogicsCats** [godotengine/godot#12329] opened 2017-10-22 21:44 UTC
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
GNU/Linux Debian (Crouton), Godot v2.1.4.stable.official

**Issue description:**
When the mouse hovers over a tile with a long name, the TileMap editor resizes to accommodate the longer tool bar, pushing the panels to the right of it off-screen.

**Steps to reproduce:**
1. Create a TileSet resource.
2. Give a tile a long name such that the menu bar of the TileMap editor needs to resize.
3. Create or open a TileMap. The mouse must be hovering over an empty tile so that [none] is displayed in the tool bar.
4. Hover over a tile with a long name. The TileMap editor will expand to fit the name in the place of [none] in the tool bar, pushing the panels to the left partially off-screen.

**Link to minimal example project:** [tilemap_editor_bug.tar.gz](https://github.com/godotengine/godot/files/1405369/tilemap_editor_bug.tar.gz)

**Comment by akien-mga** [comment] 2018-09-17 15:56
Is this still reproducible in 3.0.6 or the current master branch?

**Comment by TheAspiringHacker** [comment] 2018-10-10 23:45
It's been a long time, so I don't remember how the bug looked like, but it seems to still exist in 3.0.6 except that I may have meant "right" when I wrote "left," because it's the panel on the right that goes outside the window.

![godot-before](https://user-images.githubusercontent.com/30581223/46772211-d2608f80-ccc4-11e8-8858-82c7d9101454.png)
![godot-after](https://user-images.githubusercontent.com/30581223/46772213-d42a5300-ccc4-11e8-9069-95d1bda3c910.png)

**Comment by bojidar-bg** [comment] 2020-01-21 10:49
Duplicate of #28135 (or vice-versa), fixed by #33829.

**Closed by bojidar-bg** 2020-01-21 10:49 UTC
Labels: bug, topic:editor
