### ISSUE TITLE
[Feature request] A "Make Resources Uniques" that applies to children nodes ; make it clearer when resources are linked

### ISSUE THREAD

**Issue by vichug** [godotengine/godot#2270] opened 2015-07-16 13:00 UTC
right now, if there is a node with children nodes that you duplicate, you have to go in each node and click each time "Make Resources Uniques" in order for every resources everywhere to become unique. It can be bothersome and long process if you want to create several elements that are nearly the same but just change a little thing each time. It would be beneficient to have like an option like "Make Resources Uniques (Also in Subnodes)".
Also, it can become very unclear with time which resources are shared across which nodes. It could be cool if there was somehow a more convenient approach to know that.

**Comment by vichug** [comment] 2015-07-18 11:23
hm. i just realized there is a quite similar request already : https://github.com/okamstudio/godot/issues/1213

**Comment by akien-mga** [comment] 2015-11-06 11:58
Closing as duplicate of #1213 then.

**Closed by akien-mga** 2015-11-06 11:58 UTC
Labels: archived, feature request, topic:editor
