### ISSUE TITLE
Godot 3.1.1 Fails to Launch (Linux, Debian Buster with kernel 4.19 and non-working Nvidia/nouveau PRIME setup)

### ISSUE THREAD

**Issue by sunnystormy** [godotengine/godot#29576] opened 2019-06-07 14:24 UTC
**Godot version:**
3.1.1

**OS/device including version:**
Debian Buster

**Issue description:**
I'm having an issue where I run the godot binary on my Linux machine and nothing happens. When I open "top" it shows the process consuming 100 percent of the cpu. I did not have this issue prior to the current stable release (3.1.1). I switched to different desktop environments (between KDE and LXDE) but the problem persists. Any ideas?

**Steps to reproduce:**
Try to run both the 64-bit Linux builds (Mono and non-Mono), or compile from source.

**Minimal reproduction project:**
N/A

**Comment by sunnystormy** [comment] 2019-06-07 14:29
---Update---

It's the damn kernel! For some reason, kernel 4.19.* is causing processes to stall while running. I just got things working on a 4.9.* kernel. *facepalm*

**Comment by duckinator** [comment] 2019-06-11 01:35
Reproduced with a fresh Debian Buster install in a VirtualBox VM.

Games exported from Godot will use 100% CPU on all cores.

I was unable to find a Buster package for the 4.9 kernel, so was unable to test if that fixed it for me as well.

**Comment by Calinou** [comment] 2019-06-11 07:05
@duckinator Does Godot print anything to standard output/error when you start it from a terminal?

Maybe you could try running it with `strace` and look at the lines that appear before Godot gets stuck.

**Comment by akien-mga** [comment] 2019-06-11 09:03
What kind of graphics hardware do you have? Are those by any chance laptops with Intel IGP and Nvidia or AMD discrete GPU, running open source drivers?

**Comment by akien-mga** [comment] 2019-06-11 09:04
Also, are you running Xorg or Wayland?

**Comment by sunnystormy** [comment] 2019-06-11 12:52
@akien-mga I'm using a laptop with both Intel IGP and an Nvidia discrete GPU. I'm using open-source drivers for both (though only Intel works...), as well as Xorg for my windowing environment.

**Comment by akien-mga** [comment] 2019-06-11 13:56
Does it run with `DRI_PRIME=0`? If so can you post the output of `godot --verbose`?

**Comment by duckinator** [comment] 2019-06-11 14:34
Testcase: [testcase.zip](https://github.com/godotengine/godot/files/3276987/testcase.zip)

Strace logs: 
[strace.log](https://github.com/godotengine/godot/files/3276989/strace.log)

The only thing that stands out to me is the frequent `clock_gettime()` calls. I'm reading up on Godot's architecture atm, since I figure that'll help me get a better idea of where to start poking around.


As a note, the testcase was created by just creating a new project and adding a new 'User Interface' scene. (That's literally it.)

**Comment by duckinator** [comment] 2019-06-11 14:42
Output of `godot --verbose`, when running it in my VM:

```
pup@debian:~/29576$ ~/Godot_v3.1.1-stable_x11.64 --verbose
XInput: Refreshing devices.
XInput: Absolute pointing device: Virtual core pointer
XInput: No touch devices found.
Detecting GPUs, set DRI_PRIME in the environment to override GPU detection logic.
Only one GPU found, using default.
Using GLES3 video driver
OpenGL ES 3.0 Renderer: llvmpipe (LLVM 7.0, 128 bits)
PulseAudio: detected 2 channels
PulseAudio: audio buffer frames: 512 calculated latency: 11ms
CORE API HASH: -7323055289690356460
EDITOR API HASH: 4311324559216891413
Loading resource: res://default_env.tres
Loaded builtin certs
Loading resource: res://MainScene.tscn
```

@Calinou I believe this + my last comment contain everything you asked for.

@akien-mga see above for `godot --verbose` output. The only difference with `DRI_PRIME=0` is that these two lines don't get printed:

```
Detecting GPUs, set DRI_PRIME in the environment to override GPU detection logic.
Only one GPU found, using default.
```

**Comment by sunnystormy** [comment] 2019-06-11 14:57
@duckinator All I did was try to run the Godot Engine binary for Linux 64 downloaded from the downloads page (both vanilla and Mono versions). I also compiled the engine from source and ran the resulting binary with the same problem.

I don't have time to run the tests you've shared atm, but I will look into it later this evening. Hope this helps, and thank you very much!

**Comment by duckinator** [comment] 2019-06-11 15:12
Ah, okay! That's really interesting.

The Godot Engine binary itself runs in my VM, but performance is garbage: it's technically usable, but I get 80%+ CPU usage and visible delays in it updating the screen, just from moving the text cursor in the text editor.

**Comment by Calinou** [comment] 2019-06-11 15:40
@duckinator 3D acceleration in VirtualBox is pretty bad (and limited to OpenGL 2.1), there's not much we can do about it :slightly_frowning_face:

**Comment by duckinator** [comment] 2019-06-11 16:29
@Calinou yeah, I majorly misunderstood the issue originally & am now unsure if I actually reproduced it.

But if my testcase produces the original problem, that may still simplify debugging (just because it's a less-complex program).

**Comment by sunnystormy** [comment] 2019-06-11 22:15
@akien-mga Got things working by setting the environment variable "**DRI_PRIME**" to **zero**. Still... I don't like having to tinker with my environment to get Godot Engine up and running. >_>

**Comment by duckinator** [comment] 2019-06-12 13:36
@sunnystormy `DRI_PRIME=0` is telling it to _not_ use the Nvidia GPU. Since you said [only the Intel GPU works](https://github.com/godotengine/godot/issues/29576#issuecomment-500827150), it makes sense that this would be necessary. (See [this part of the nouveau website](https://nouveau.freedesktop.org/wiki/Optimus/#offloading3d) for more details.)

If you got the Nvidia driver working, it should (in theory) function as expected. This seems like a problem with specific kernel + driver combinations moreso than Godot.

**Comment by sunnystormy** [comment] 2019-06-12 14:03
@duckinator Then it is as I suspected: a kernel issue. Well, that bites! This actually gives me yet another reason to switch over to FreeBSD. Unfortunately, I doubt that I am the only one with an IntelGPU/Nvidia laptop where only the Intel GPU is properly recognized by the system. So... this kernel issue may potentially affect a *lot* of users.

**Comment by akien-mga** [comment] 2019-06-12 14:58
@sunnystormy You can put `export DRI_PRIME=0` in your `~/.bashrc` to prevent any application from using the Nvidia GPU via `nouveau`. Or you can blacklist `nouveau` on boot, but I guess even if it's not working properly for graphical applications, it might still provide relevant power management features.

**Comment by sunnystormy** [comment] 2019-06-12 15:47
@akien-mga I know I can modify my system, as you've suggested, but the problem is that I want things to work "right out of the box", and it does with the 4.9.* kernel series. Now that I know that the issue seems to be on the "Linux" side of things (which is a huge bummer), I'm beginning to wonder if I should inform Debian about these problems?

**Comment by santouits** [comment] 2019-06-12 17:50
I wonder if there is anything we can do in godot's side for this issue. Can you run the 2.1 version? https://downloads.tuxfamily.org/godotengine/2.1.5/

**Comment by akien-mga** [comment] 2019-06-12 19:07
2.1 would work fine as it doesn't attempt to detect discrete GPUs. Since Godot 3.1, we try to detect the GPUs and if a discrete GPU is found (normally it's more powerful than the integrated one), we use it by setting `DRI_PRIME=1`.

In @sunnystormy's case the `nouveau` setup seems non working, so Godot opts in for a dead end. It's not a Godot-related issue per se, other applications should also have issues if ran with `DRI_PRIME=1`. You could try `DRI_PRIME=1 supertuxkart` and `DRI_PRIME=1 glxinfo`, and if those don't work, file a bug report with Debian against the Mesa component.

**Comment by akien-mga** [comment] 2019-06-12 19:08
Note that `nouveau` is sadly not renowned for its performance, and we should probably change Godot's auto-detection logic to ignore discrete Nvidia GPUs if running `nouveau`, and thus basically keep `DRI_PRIME=1` only for Intel+AMD setups (where it works well).

That being said, even badly performing `nouveau` should not prevent Godot from launching, it should just have sub-par performance compared to the proprietary `nvidia` driver.

**Comment by sunnystormy** [comment] 2019-06-12 21:48
@akien-mga Since my nouveau setup leads to a dead end, is there no error being reported internally when you try to detect the discrete GPU? The fact that a soft-lock is occurring must mean there's an error somewhere that we can reference... Or is this beyond the scope of the GPU detection logic?

**Comment by duckinator** [comment] 2019-06-14 13:28
I'm not sure if the error would occur somewhere Godot can access it &mdash; and if it is, I'm not sure it'd provide many details.

However, one approach would be adding a page to the docs about how DRI_PRIME works and a line after the existing DRI_PRIME-related message along the lines of:

> If Godot never launches, or it performs poorly, see &lt;link to aforementioned new docs page&gt;.

@akien-mga @sunnystormy do you think that^ approach is reasonable? If so, I can go ahead and submit PRs to both this repo + the docs.

(I'm also open to suggestions on the exact message, btw.)

**Comment by sunnystormy** [comment] 2019-06-14 18:18
@duckinator It is absolutely reasonable. It's just unfortunate that the hardware aspect of this is what's causing the problem. I'm probably gonna buy a System76 laptop sometime in the future so that I *know* I'll have proper graphics support from the OS.

**Comment by akien-mga** [comment] 2020-01-14 09:59
@sunnystormy Can you still reproduce this issue?

If so, please provide:
- Output of `glxinfo`.
- Output of `godot --verbose` (if you set `DRI_PRIME=0`, you need to unset it first otherwise it won't print the relevant GPU vendor details).

**Comment by sunnystormy** [comment] 2020-01-15 02:56
@akien-mga I will try reproducing this over the weekend. Unfortunately, school just started again, so my weekdays are quite busy. Thank you!

**Comment by sunnystormy** [comment] 2020-01-19 04:25
@akien-mga I haven't had the time to work on this, I'm pretty busy. The issue is my GPU setup (Intel Integrated Graphics + NVIDIA). Newer versions of the Linux kernel may be more amenable now that we're getting into the 5.* series.

**Comment by sunnystormy** [comment] 2020-01-20 18:57
@akien-mga Just got around to looking at this today. The latest Debian buster kernel (5.4.0-2) works with DRI_PRIME set to "0".

**Comment by akien-mga** [comment] 2020-07-26 20:29
> Just got around to looking at this today. The latest Debian buster kernel (5.4.0-2) works with DRI_PRIME set to "0".

Thanks, but is it still failing by default without setting `DRI_PRIME=0` manually?

Normally Godot should favor Intel over `nouveau` when detecting available outputs, so it shouldn't attempt using nouveau at all. But maybe it's failing in the detection code.

To debug further I would still need the output requested above though, otherwise I can only make guesses:
https://github.com/godotengine/godot/issues/29576#issuecomment-574096001

**Comment by gdesecrate** [comment] 2020-09-26 11:11
I got Nvidia ION and latest Ubuntu Mate. Godot 64bit binary is loaded from site.

With nouveau launching godot 3.2.3 hangs up the system right at loading window
If I do "--video-driver GLES2" it shows working project selector dialog, but if I load any project the godot get stuck at loading screen (with sponsors)
Same stuck situation if I "-e -path MYPATH --video-driver GLES2"

Here comes the weird part! **If I install proprietary nvidia drivers while editor is stuck at loading project - it gets unstuck and working!** But if I close it and try launch it again (even after system reset) it tells me that my videocard does not support GLES2.

If I switch to nouveau driver (through additional drivers dialog in Ubuntu) the godot editor launches just fine (even with no --video-driver GLES2). If I restart system - I am back to step 1 where I can only see project manager by forcing GLES2.

**Exported games launches fine with nouveau**, but tell "your hardware bad" if proprietary driver is installed.

So I think there is something with editor loading or/and drivers in debian-derived distros.

Same PC had Godot Editor working on Ubuntu Mate (summer 2019) and month ago on Manjaro.

**Comment by Zireael07** [comment] 2020-09-26 11:42
@gdesecrate: The symptoms you mention seem to suggest it's a problem on your end (broken drivers install, broken environment). Additionally, there was a report of a NVIDIA driver regression recently, it might be that too.

**Comment by gdesecrate** [comment] 2020-09-27 22:30
@Zireael07: Thanks, downgrading the nvidia videodriver helped somehow

**Comment by akien-mga** [comment] 2020-12-10 23:04
I'll close as the OP's issue is unfixable as is, their nouveau PRIME setup is bogus. I would suggest to set `DRI_PRIME=0` in `/.bashrc`, or disable `nouveau`.

**Closed by akien-mga** 2020-12-10 23:04 UTC
Labels: bug, platform:linuxbsd, topic:editor, topic:porting
