### ISSUE TITLE
Billboarded particles are rotated incorrectly with double-precision builds

### ISSUE THREAD

**Issue by TCROC** [godotengine/godot#89020] opened 2024-02-29 20:38 UTC
### Tested versions

Godot Engine v4.3.dev.mono.custom_build.a47830c66

### System information

Pop OS 22.04

### Issue description

When rotating an instance of ParticlesGPU3D, the particles become distorted.  They continue to distort worse and worse until a threshold is passed and they become invisible.

Here is a particle effect that isn't rotated:

![image](https://github.com/godotengine/godot/assets/24307049/a25a61cb-5ac4-495d-8a3d-a8fe6729b2fd)

![image](https://github.com/godotengine/godot/assets/24307049/b0e93271-4b27-4ebf-be8a-0bcf5a0d6248)

And here is one that is rotated 85.5 degrees along the x axis:

![image](https://github.com/godotengine/godot/assets/24307049/218343af-1a75-46f7-9345-a15fc1e8ad73)

![image](https://github.com/godotengine/godot/assets/24307049/1fb2eaa0-3aa4-497b-8fd6-7ca800cb1aef)

And if you continue to rotate it, it eventually becomes invisible:

![image](https://github.com/godotengine/godot/assets/24307049/a86e8c5f-db51-4109-86af-91d1be51fb45)

This poses a problem for wanting to do things like simulate a rocket emitting fire out of a thruster.  Or pretty much any dynamic moving and rotating 3d object.

### Steps to reproduce

1. Open the example project.  
2. See that everything is behaving as expected in "ParticlesGpu.tscn".
3. See that things are distorted in "ParticlesGpuRotated.tscn"

### Minimal reproduction project (MRP)

[GodotGpuParticlesBug.zip](https://github.com/godotengine/godot/files/14453288/GodotGpuParticlesBug.zip)

**Comment by TCROC** [comment] 2024-02-29 20:55
Ok I found a solution.  Maybe its not a bug.  I would love some clarification tho and maybe whether or not we should consider enabling this by default.  Anyways:

![image](https://github.com/godotengine/godot/assets/24307049/28ec4915-ebe8-44da-86cc-b090e2dca505)

Enabling "Rotate Y" seems to fix it.  So my new questions are:

1. What does this boolean do?
2. Why do I get the weird distorted behavior without it?
3. Why isn't it enabled by default?
4. Is there a performance impact?  (This might be answered by 3).

Thanks again everyone! :)

**Comment by clayjohn** [comment] 2024-02-29 21:30
Running your MRP it both the regular parties and the rotated particles look fine

_Rotated particles_
![image](https://github.com/godotengine/godot/assets/16521339/8157e5f9-970d-4441-aeb3-a31a7051b059)

However, I noticed that the project is flagged as using "double precision" and you are using a custom build of Godot. 

Can you test the project with your custom build with double precision disabled? This issue might be specific to double precision builds

**Comment by TCROC** [comment] 2024-02-29 21:32
Yep I'll give that a shot

**Comment by clayjohn** [comment] 2024-02-29 21:34
Also to be clear, I don't think Rotate Y is the proper fix here, it more likely just avoids the actual problem for some reason. Its a good data point to help find the actual solution though

**Comment by TCROC** [comment] 2024-02-29 21:41
While godot is building on my machine, I tested it with the CPU particles as well.  I noticed that the CPU particles don't seem to change the direction they emit from / towards when rotating in 3D space.  Would this be another bug?  Is there a config that needs to be checked for CPU particles to emit relative to its current rotation?

**Comment by TCROC** [comment] 2024-02-29 21:56
I can confirm that both CPU and GPU particles are working as expected without double precision enabled.  So there are currently 2 known issues with particles and double precision builds:

1. GPU Particles get distorted when rotating.
2. CPU particles do not emit in the correct direction when rotating.

So I guess the issue should probably be renamed to something more in line with: 

"Particles rotating incorrectly on double precision builds" or something along those lines.

**Comment by TCROC** [comment] 2024-02-29 21:59
And just tested "Rotate Y" with CPU particles.  That does not fix the CPU particles like it does the GPU particles.

**Comment by cridenour** [comment] 2024-03-01 19:41
Dupe of #76388 but great find on the Rotate Y workaround.

**Comment by TCROC** [comment] 2024-03-01 19:45
Thanks @cridenour ! :)  So I guess we can probably close this issue as a duplicate then?  Unless you guys still want to keep it open for reference.  I opened up a separate issue for what I found with the cpu particles that I mentioned in this issue: https://github.com/godotengine/godot/issues/89061 so we won't lose that if we close this.

**Comment by clayjohn** [comment] 2024-03-01 19:46
> Thanks @cridenour ! :) So I guess we can probably close this issue as a duplicate then? Unless you guys still want to keep it open for reference. I opened up a separate issue for what I found with the cpu particles that I mentioned in this issue: #89061 so we won't lose that if we close this.

I'll go ahead and close this as we like to only keep one issue open. The discussion was fruitful though and this will remain linked to  https://github.com/godotengine/godot/issues/76388

**Closed by clayjohn** 2024-03-01 19:46 UTC
Labels: bug, needs testing, topic:3d, topic:particles
