### ISSUE TITLE
Shaders do not render the modulate color

### ISSUE THREAD

**Issue by noxhy** [godotengine/godot#64996] opened 2022-08-28 16:53 UTC
### Godot version

4.0.alpha14

### System information

Windows 10

### Issue description

Shaders wont render modulate color.
I expected the ascii textures to change to the pink I put for the modulate. It stayed white unlike in Godot 3.

Workspace:
![image_2022-08-28_125155181](https://user-images.githubusercontent.com/58011428/187085472-8b83b697-1b16-4f5a-9c60-6cc68490e7d4.png)

Ascii Shader Code:

![image_2022-08-28_125017456](https://user-images.githubusercontent.com/58011428/187085401-f6d6f1e2-d041-4de1-b7e3-e10d95b1ac80.png)

### Steps to reproduce

1. Use a shader on a ColorRect
2. Modulate the ColorRect

**Comment by Calinou** [comment] 2022-08-28 17:02
@noxhy Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot. (The shader code itself isn't enough, and code posted in an image can't be copied easily.)

**Comment by Zylann** [comment] 2022-08-28 17:03
### In Godot 3

`COLOR` used to behave as being just the modulate color in `fragment`.
The following was showing a uniformly colored rectangle with the modulate color:
```glsl
void fragment() {
	COLOR = COLOR;
}
```
You could however write only this, and have modulation applied on top, even if you didn't write it explicitely:
```glsl
void fragment() {
	COLOR = texture(TEXTURE, UV);
}
```
This variant did the same thing, somehow Godot didn't apply modulation twice:
```glsl
shader_type canvas_item;

void fragment() {
	COLOR = COLOR * texture(TEXTURE, UV);
}
```

### In Godot 4

The behavior seems to have changed, in ways the doc isn't explaining.

The following now outputs *the texture with color modulation baked in*:
```glsl
void fragment() {
	COLOR = COLOR;
}
```
The following outputs *the texture without color modulation*:
```glsl
void fragment() {
	COLOR = texture(TEXTURE, UV);
}
```
The following outputs the texture with color modulation applied twice, appearing darker:
```glsl
void fragment() {
	COLOR = texture(TEXTURE, UV);
}
```

**Comment by KoBeWi** [comment] 2022-08-28 17:43
Duplicate of #49781

**Closed by KoBeWi** 2022-08-28 17:43 UTC
Labels: archived, needs testing, topic:shaders
