### ISSUE TITLE
Array type mismatch fails silently

### ISSUE THREAD

**Issue by jjanella** [godotengine/godot#94490] opened 2024-07-18 02:22 UTC
### Tested versions

4.2.2.stable

### System information

Arch Linux - Godot 4.2.2.stable

### Issue description

When passing a PackedVector2Array into a function that modifies input marked as an Array, a PackedVector2Array will not be modified, and will not leave any type of warning. 

### Steps to reproduce

Run the code below. Notice only the regular array is modified, while the packed array does nothing, then creates an errpr. Note an error is expected for this code, however the issue is that it doesn't create errors where it should.

### Minimal reproduction project (MRP)

``` swift
extends Node

func modify_silent_fail(arr: Array) -> void:
	arr.pop_at(0)

func modify_with_error(arr) -> void:
	arr.pop_at(0)

func _ready():
	var v_arr: Array = [Vector2(0,1), Vector2(1,2), Vector2(2,3)]
	var pv_arr: PackedVector2Array = PackedVector2Array([Vector2(1,0), Vector2(2,1), Vector2(3,2)])

	# Works as expected
	modify_silent_fail(v_arr)
	print(v_arr)

	# Does nothing, not as expected. Should either create an error or modify the array.
	modify_silent_fail(pv_arr)
	print(pv_arr)

	# Works as expected
	modify_with_error(v_arr)
	print(v_arr)

	# Creates an error as expected
	modify_with_error(pv_arr)
	print(pv_arr)
```

**Comment by dalexeev** [comment] 2024-07-18 14:33
I can't reproduce the crash. A crash is an unrecoverable engine error that leads to its immediate shutdown. A crash is not a freeze, not an error in the Output Log or the Debugger.

> ```swift
> # Does nothing, not as expected. Should either crash or modify the array.
> ```

This is not a bug, but non-obvious behavior. See:

* #89829
* #89853

**Comment by jjanella** [comment] 2024-07-19 02:01
For clarity you are correct it does not crash the engine.

**Comment by dalexeev** [comment] 2024-07-19 06:05
Implicit casting `PackedVector2Array` to `Array` causes copying. You modify the copy, the original remains unchanged.

```gdscript
extends Node

func modify_silent_fail(arr: Array) -> void:
    arr.pop_at(0)
    print(arr) # [(2, 1), (3, 2)]

func _ready():
    var pv_arr: PackedVector2Array = PackedVector2Array([Vector2(1,0), Vector2(2,1), Vector2(3,2)])
    modify_silent_fail(pv_arr)
    print(pv_arr) # [(1, 0), (2, 1), (3, 2)]
```

* Duplicate of #89829.

Thanks for the contribution nonetheless!

**Closed by dalexeev** 2024-07-19 06:05 UTC
Labels: topic:gdscript
