### ISSUE TITLE
Unable to Scale Radial Progress Bars

### ISSUE THREAD

**Issue by LordBozo** [godotengine/godot#31506] opened 2019-08-20 17:11 UTC
**Godot version:** 
3.1.1 Stable

**OS/device including version:**
OpenGL ES 3.0 Renderer: GeForce GTX 660 Ti/PCIe/SSE2

**Issue description:**
Selecting nine patch stretch on a TextureProgress node allows it to shrink or grow the graphic inside, unless one of the radial or bilinear fill modes are selected

**Steps to reproduce:**
Place down a TextureProgress node
Select Nine Patch Stretch
Put a large picture in as one of the textures
it allows you to now scale the picture
Change fill mode to Clockwise/Counter Clockwise/Clockwise and Counter Clockwise/ Bilinear
Image will revert to default size and prevents scaling

**Minimal reproduction project:**
[BugReport.zip](https://github.com/godotengine/godot/files/3521763/BugReport.zip)

**Comment by LATRio** [comment] 2019-08-21 12:34
You can scale it by modifying rect_scale (Control -> Rect -> Scale).

**Comment by bojidar-bg** [comment] 2019-08-21 12:44
This is hardly a solution, due to #3925 -- Containers will reset child nodes' scale to (1, 1).

**Comment by Calinou** [comment] 2020-03-10 21:43
Duplicate of #33222.

**Closed by Calinou** 2020-03-10 21:43 UTC
Labels: bug, topic:gui
