### ISSUE TITLE
ViewportTextures do not work at runtime when applied to a material override of an instanced mesh

### ISSUE THREAD

**Issue by depressedtimbit** [godotengine/godot#78597] opened 2023-06-23 03:23 UTC
### Godot version

4.0.3.stable

### System information

Windows 11 - Vulkan Forward+ - GeForce GTX 1650 SUPER

### Issue description

when applying material overrides/overlays to a mesh that is an instanced scene, ViewportTextures will function while in editor 
![godot windows opt tools 64_b4Sgw6AZmV](https://github.com/godotengine/godot/assets/84045706/d06bd060-70d1-4dcb-98cc-d926a9e4d68c)
but not when ran
![godot windows opt tools 64_LzVzYV9vmK](https://github.com/godotengine/godot/assets/84045706/c9d34a54-4c8c-4d90-96bd-a0a2e501bc46)

### Steps to reproduce

- start with a basic scene containing a Camera3D, SubViewport, and control nodes as children of the SubViewport
- Create a MeshInstance3D, add a mesh, Save branch as new scene 
- add new material in any available slot, mesh/material, material_override, material_overlay surface_material_override
- make local to scene, add ViewportTexture assigned to the SubViewport
- at this point the material will appear as normal
- play the scene

### Minimal reproduction project

N/A

**Comment by arkology** [comment] 2023-06-23 03:37
@clayjohn this is related to what I wrote yesterday https://github.com/godotengine/godot/issues/78285#issuecomment-1602473790 (but my case is 2d). Please take a look

**Comment by Rindbee** [comment] 2023-06-23 06:33
A duplicate of #77678.

**Closed** 2023-06-23 06:50 UTC
