### ISSUE TITLE
create ViewportTexture failed

### ISSUE THREAD

**Issue by lyh1091106900** [godotengine/godot#72457] opened 2023-01-31 15:24 UTC
### Godot version

3.2.3

### System information

Windows10 , GLES3 ， GTX1650super

### Issue description

Can't create a ViewportTexture on resources saved as a file.
Resource needs to belong to a scene.

### Steps to reproduce

![3UVK1CAVL95PK$X9WLA)FTC](https://user-images.githubusercontent.com/4587022/215801572-1f2303b0-d041-42e7-a969-65fad94933a7.png)

### Minimal reproduction project

[Godot-2D-Reflections-master.zip](https://github.com/godotengine/godot/files/10547960/Godot-2D-Reflections-master.zip)

**Comment by KoBeWi** [comment] 2023-01-31 16:16
This is not a bug. ViewportTexture requires a path to node, so it can only be created inside a scene.

**Comment by lyh1091106900** [comment] 2023-01-31 16:28
so ，what is the right way to bound ViewportTexture define in shader

**Comment by KoBeWi** [comment] 2023-01-31 16:30
You can set it using script
```GDScript
material.set_shader_param("texture_uniform", $Viewport.get_texture())
```

**Comment by lyh1091106900** [comment] 2023-01-31 16:39
thanks，it works 。Its a old way to create ViewportTexture now be abandoned

**Comment by KoBeWi** [comment] 2023-01-31 16:56
You can also make the material built-in and local to scene. But from my experience, setting from code is more reliable.

That said, closing as it's not a bug.

**Closed by KoBeWi** 2023-01-31 16:56 UTC
