### ISSUE TITLE
PhysicalBone3D's don't follow SkeletonIK3D in running project

### ISSUE THREAD

**Issue by NykolaR** [godotengine/godot#77704] opened 2023-05-31 18:04 UTC
### Godot version

4.0.3 stable

### System information

Linux, AMD

### Issue description

In engine, when running SkeletonIK3D with a physical skeleton, the physical bones follow and match the IK. When a project is ran, the SkeletonIK3D visually functions, but physical bones will no longer follow the IK. It's possible I'm just overlooking something but have been stumped on it for ~3 hours now. Don't necessarily expect a fix since SkeletonIK3D is deprecated, but may also be relevant for whatever it's replacement ends up being/if the IK modification stack returns.

https://github.com/godotengine/godot/assets/15218653/a0cf883c-ad67-401d-816b-ac2eaea7d888

https://github.com/godotengine/godot/assets/15218653/9866702c-54cb-4f5a-8832-166fb0a3c2bd

### Steps to reproduce

Create physical skeleton, add SkeletonIK3D, use IK. In the minimal reproduction, turn on visible collision shapes and run game, or play animation in editor and then start the IK.

### Minimal reproduction project

[IKTest.zip](https://github.com/godotengine/godot/files/11617487/IKTest.zip)

**Comment by Chaosus** [comment] 2023-06-01 08:33
Duplicate of https://github.com/godotengine/godot/issues/75894

**Closed by Chaosus** 2023-06-01 08:33 UTC
Labels: bug, topic:physics, topic:3d
