### ISSUE TITLE
Missing 'Direction' parameter in Particles Material

### ISSUE THREAD

**Issue by PullTheStrings** [godotengine/godot#16319] opened 2018-02-02 12:10 UTC
**Godot version:**

3.0

**OS/device including version:**

**Issue description:**

 The 'Direction' parameter in Particles Material mentioned in your online documentation is missing.

![missingdirectiongodot](https://user-images.githubusercontent.com/15687516/35732399-866481f6-0819-11e8-9fae-9f8c625dd974.png)
![missingdirectiongodot2](https://user-images.githubusercontent.com/15687516/35732404-89d6df14-0819-11e8-9a5d-90a11daa2941.png)

**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by vnen** [comment] 2018-02-02 13:33
Duplicate of #13492.

**Closed by vnen** 2018-02-02 13:33 UTC
Labels: documentation, topic:core
