### ISSUE TITLE
editing Node's metadata from inside the Inspector

### ISSUE THREAD

**Issue by SuperUserNameMan** [godotengine/godot#5433] opened 2016-06-26 17:12 UTC
**Operating system or device - Godot version:**
2.0.3stable win64

**Issue description** (what happened, and what was expected):

It could be handy to be able to set the metadata of a node directly from the inspector without being forced to attach a custom script to it.

**Steps to reproduce:**

**Link to minimal example project** (optional but very welcome):

**Comment by bojidar-bg** [comment] 2016-06-27 08:14
Strange... I'm absolutely sure there was another issue once about this, but I can't seem to find it...

**Comment by kubecz3k** [comment] 2016-07-05 16:08
closing as a duplicate of https://github.com/godotengine/godot/issues/2082

**Comment by SuperUserNameMan** [comment] 2016-07-05 16:18
not a duplicate. the other is about attaching a note to a node.

mine is about editing meta from inside the inspector.

**Comment by SuperUserNameMan** [comment] 2016-07-05 16:19
@kubecz3k :
not a duplicate. the other is about attaching a note to a node.

mine is about editing meta from inside the inspector.

**Comment by kubecz3k** [comment] 2016-07-05 17:35
@SuperUserNameMan oh ok, sorry about that!

**Comment by bojidar-bg** [comment] 2016-07-06 08:36
@kubecz3k Oopsie, sorry for not fully explaining the case; I though saying that is is for another problem would suffice `XD`

**Comment by bojidar-bg** [comment] 2016-07-06 08:37
On a side note, maybe this would look good inside the `Node` tab (plus a corresponding icon in the scene tree)?

**Comment by vnen** [comment] 2016-07-06 15:25
Another scene tree icon? I already need to make the dock wider to see the node name in some cases...

**Comment by vnen** [comment] 2016-11-17 01:49
This could be useful. I might tackle this but I haven't an idea for how the GUI should look like.

**Comment by bojidar-bg** [comment] 2016-11-17 10:38
@vnen Here are a few GUI suggestions I could come up with.. (md-fu)

Property | Value
--- | ---
my_prop (editable name, somehow) | <kbd>type dropdown</kbd>
my_prop_value | ...

Or  (ArrayPropertyEdit-alike):

Property | Value
--- | ---
length | 1
items |
├&nbsp;1_name | "my_prop"
├&nbsp;1_type | <kbd>type dropdown</kbd>
└&nbsp;1 | ...

Or  (custom tree of Control nodes):

Property | Value | &nbsp;
--- | --- | ---
my_prop (LineEdit) | Type: <kbd>String</kbd> (type dropdown)<br><kbd>2</kbd> (some type-specific editor, somehow) | <kbd>Remove</kbd>
&nbsp; | <kbd>Add</kbd> | &nbsp;

**Comment by vnen** [comment] 2016-11-17 15:09
@bojidar-bg thanks for the suggestions. I think I'll try to make it as a plugin first, like a new dock.

**Comment by bojidar-bg** [comment] 2016-11-17 15:35
@vnen To be fair, you might be able to get the group dock with some black magic, then insert a new tab into it... :wink:

**Comment by vnen** [comment] 2016-11-17 16:12
I don't think the Node dock is the best place since Resources also have metadata.

**Comment by leoddd** [comment] 2017-11-29 00:52
From what I can tell, Godot can now edit dictionaries from within the Inspector, meaning that you could probably just use that implementation (and its eventual upgrades) for the metadata editing, since metadata is essentially a dictionary?

As for where to put it, maybe just make it a property exposed to the Inspector for the Object class, since that is where metadata is handled (and both resources and Nodes obviously inherit this).

**Comment by bojidar-bg** [comment] 2017-11-29 16:32
Yes, it just lacks an expose.

**Comment by aaronfranke** [comment] 2018-10-22 03:11
This issue should probably be tracked via https://github.com/godotengine/godot/issues/18591 

(Yes I know this issue is older, but the one I linked is more active and was opened by reduz)

**Comment by YeldhamDev** [comment] 2019-07-23 14:53
As #22642 was reverted and is being tried again in #30765, reopening it.

**Comment by akien-mga** [comment] 2019-10-28 14:04
See https://github.com/godotengine/godot/pull/32416#issuecomment-546954593 for further discussion on what changes might be relevant for metadata in 4.0.

**Comment by akien-mga** [comment] 2020-05-26 09:40
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!

**Closed by akien-mga** 2020-05-26 09:40 UTC
Labels: feature proposal, topic:editor, usability

**Comment by akien-mga** [comment] 2022-03-25 11:32
Object metadata is now exposed in the Inspector in Godot 4.0: #59452.
