### ISSUE TITLE
"Frame #:" goes outside the Debugger's Profiler tab

### ISSUE THREAD

**Issue by YeldhamDev** [godotengine/godot#10526] opened 2017-08-22 00:35 UTC
**Ubuntu 17.04 - Build: fc8abf7**

**Issue description:**
Self-explanatory:

![screenshot at 2017-08-21 21-23-09](https://user-images.githubusercontent.com/30739239/29543570-77863478-86b8-11e7-8abb-4e57f7d1e606.png)

**Comment by akien-mga** [comment] 2017-08-22 05:43
@groud

**Comment by groud** [comment] 2017-08-22 06:39
This was is fixed by yesterday's #10514. (I can't reproduce :) )

**Closed** 2017-08-22 06:43 UTC
Labels: bug, topic:editor
