### ISSUE TITLE
Tree focus border disappears when Border Size is set to 0 in the Editor Settings

### ISSUE THREAD

**Issue by rainlizard** [godotengine/godot#46502] opened 2021-02-28 04:35 UTC
**Godot version:** v3.2.4.rc3
**OS/device including version:** Windows 8.1, GTX 970
**Issue description:**
When you click on the FileSystem to give focus to it, the UI controls work as expected; up and down move to the next file, left and right open and collapse subdirectories, enter opens a file. However the selection graphic isn't updating, as you press the arrow keys you are moving an invisible selection around.

**Steps to reproduce:**
-Create a few subdirectories with some files in them
-Give focus to the FileSystem by clicking with the mouse
-Use arrow keys to move your invisible selection to a subdirectory then open and collapse it, or press enter

**Comment by Calinou** [comment] 2021-02-28 14:05
I can confirm this on `3.2` Git ecf432abc. *However*, it's not so much about not displaying the focused item, but rather that the "mouse selected" and "currently focused" item are at different places.

This occurs in any Tree such as the Scene Tree dock:

![image](https://user-images.githubusercontent.com/180032/109421100-368b6780-79d6-11eb-9b6a-254659f45b3b.png)

**Comment by akien-mga** [comment] 2021-02-28 20:40
If I understand correctly, what you describe is a feature. What moves around is not invisible but is indeed a selection cursor, and not changing the selection itself. That enables you to navigate the tree, and then validate your selection with Enter or Space (`ui_accept`).

Changing the selection will impact the editor (selecting a script will open the script editor, selecting an image will open it in the Import and Inspector docks, etc.), so it's expected that it doesn't happen at each time while you navigate the tree.

**Comment by rainlizard** [comment] 2021-03-01 00:29
Wow that's funny, having "Border Size" set to 0 in Editor Settings is making the cursor invisible. That's probably intentional by design and I'm changing settings I'm not familiar with. That's my bad.
(with only a brief glance I changed it because I thought it made the editor more compact)

Thanks for your time.

**Comment by Calinou** [comment] 2021-03-01 01:28
> Wow that's funny, having "Border Size" set to 0 in Editor Settings is making the cursor invisible. That's probably intentional by design and I'm changing settings I'm not familiar with. That's my bad.
(with only a brief glance I changed it because I thought it made the editor more compact)

Actually, that part should be fixed. I already made it so that focus outlines never disappear when Border Size is set to 0, but this should also apply to Tree selection outlines.

**Closed** 2021-03-12 12:42 UTC
Labels: bug, confirmed, topic:editor, topic:gui, usability
