### ISSUE TITLE
Embedded .pck export on Windows can't have a custom executable icon

### ISSUE THREAD

**Issue by CarlBeniz** [godotengine/godot#35752] opened 2020-01-30 18:37 UTC
**Godot version:**
3.2.stable.official

**OS/device including version:**
Windows 10 64-bit

**Issue description:**
Issue #33466 mentions that custom metadata with rcedit in general doesn't work with embedded .pck, but with 3.2.stable, all text-related fields seem to export properly, except for Icon. Setting a custom icon will trigger the "missing .pck file" error when you try to run the exe.

**Steps to reproduce:**
-Make a project that can be exported to run on Windows Desktop.
-Under Options in Export, enable "Embed Pck".
-Set a custom icon under the Application group.
-Make sure Rcedit is referenced in the Editor Settings, and then Export the project. Debug/Release mode have the same result.

**Minimal reproduction project:**
Any buildable project will do.

**Comment by Calinou** [comment] 2020-01-30 21:03
Duplicate of #33466. (Please write a comment there instead of opening a new issue.)

**Closed by Calinou** 2020-01-30 21:03 UTC
