### ISSUE TITLE
Export to iOS doesn't enable available localizations

### ISSUE THREAD

**Issue by DrMoriarty** [godotengine/godot#27951] opened 2019-04-12 05:29 UTC
**Godot version:**

Godot 3.1.1.dev (commit fd3845cda)

**OS/device including version:**

MacOSX 10.13.6

**Issue description:**

I have two localization files in my project:
![Снимок экрана 2019-04-12 в 8 23 09](https://user-images.githubusercontent.com/1177068/56014119-88e90f80-5cfc-11e9-8c5f-cd73aa519351.png)

When I export it for iOS I see only English - Development language in Xcode:
![Снимок экрана 2019-04-12 в 8 23 25](https://user-images.githubusercontent.com/1177068/56014143-a322ed80-5cfc-11e9-8643-792e2dd106b5.png)

The game don't use Russian localization resource until I add Russian localization manually in Xcode project.
When I update my iOS export the editor rewrite whole project and all my changes have lost.

**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by Calinou** [comment] 2020-08-18 14:21
cc @bruvzg - Was this ever implemented?

**Comment by bruvzg** [comment] 2020-08-18 14:30
> Was this ever implemented?

No, `TranslationServer` should load localization file according to current system locale, but it won't show in the Xcode project. Locale detection should be fixed in #41172.

**Comment by naithar** [comment] 2021-03-01 01:07
This one actually seems to be fixed by https://github.com/godotengine/godot/pull/41173 as `OS::get_singleton()->get_locale` now returns correct value.

**Comment by Calinou** [comment] 2021-03-01 01:26
Closing per @naithar's comment. Please open a new issue if you can still reproduce this.

**Closed by Calinou** 2021-03-01 01:26 UTC
Labels: bug, platform:ios, topic:porting

**Comment by zarmath** [comment] 2021-03-13 20:36
I have the same problem I understand that these will be solved in the next version, is that so?

**Comment by Calinou** [comment] 2021-03-13 20:43
@zarmath Which Godot version are you using? This should be fixed in 3.2.4rc4 but the bug will remain present in 3.2.3.

**Comment by zarmath** [comment] 2021-03-14 10:40
Yes I'm using version 3.2.3
