### ISSUE TITLE
"Snap Relative" crashes the editor when moving a node

### ISSUE THREAD

**Issue by AWKgamedev** [godotengine/godot#13957] opened 2017-12-04 13:15 UTC
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Windows 10, Godot 3.0 beta1, GTX 1060

**Issue description:**
Editor crashes and throws up the following error when moving a node and Toggle Snapping and Snap Relative are enabled:

> CrashHandlerException: Program crashed
> [0] <couldn't map PC to fn name>
> [1] <couldn't map PC to fn name>
> [2] <couldn't map PC to fn name>
> [3] <couldn't map PC to fn name>
> [4] <couldn't map PC to fn name>
> [5] <couldn't map PC to fn name>
> [6] <couldn't map PC to fn name>
> [7] <couldn't map PC to fn name>
> [8] <couldn't map PC to fn name>
> [9] <couldn't map PC to fn name>
> [10] <couldn't map PC to fn name>
> [11] <couldn't map PC to fn name>
> [12] <couldn't map PC to fn name>
> [13] <couldn't map PC to fn name>
> [14] <couldn't map PC to fn name>
> [15] <couldn't map PC to fn name>
> [16] <couldn't map PC to fn name>
> [17] <couldn't map PC to fn name>
> [18] CallWindowProcW
> [19] CallWindowProcW
> [20] glDebugEntry
> [21] CallWindowProcW
> [22] DispatchMessageW
> [23] <couldn't map PC to fn name>
> [24] <couldn't map PC to fn name>
> [25] <couldn't map PC to fn name>
> [26] <couldn't map PC to fn name>
> [27] <couldn't map PC to fn name>
> [28] BaseThreadInitThunk
> -- END OF BACKTRACE --

**Steps to reproduce:**
1.  Add Node2D to scene
2.  Enable Toggle Snapping and Snap Relative
3.  Move the node around

**Comment by Noshyaar** [comment] 2017-12-04 13:20
I cannot reproduce in Antergos x86_64 - 055c560
cc: @groud

**Comment by volzhs** [comment] 2017-12-04 14:09
I can't either on Ubuntu 16.04 abdcf2c

**Comment by groud** [comment] 2017-12-04 14:13
Weird, can't reproduce either.

**Comment by CowThing** [comment] 2017-12-04 23:03
I can reproduce it. But only sometimes. I have a Node as the root of the scene and a Node2D as the child. It crashes more consistently if I select the Node, turn Snap Relative off and then back on. Then select the Node2D and try to move it.

**Comment by TheAspiringHacker** [comment] 2017-12-06 02:50
Searching the error message, it appears to be only for Windows: https://github.com/godotengine/godot/search?utf8=%E2%9C%93&q=couldn%27t+map+pc+to+fn+name&type= . Thus, the bug occurs on @AWKgamedev's Windows machine but not @Noshyaar's Antergos machine or @volzh's Ubuntu machine. @CowThing, when you could and could not reproduce the bug, did you use different operating systems?

**Comment by CowThing** [comment] 2017-12-06 03:01
Yeah I'm using Windows 10. So it seems the crash is windows related.

**Comment by akien-mga** [comment] 2017-12-06 06:56
> Searching the error message, it appears to be only for Windows: https://github.com/godotengine/godot/search?utf8=%E2%9C%93&q=couldn%27t+map+pc+to+fn+name&type= 

No, that error just means "man, there are no debug symbols in your binary so I'm writing a useless stacktrace, sorry about that". It's not related to the actual issue :)

**Comment by akien-mga** [comment] 2017-12-11 09:53
> I have a Node as the root of the scene and a Node2D as the child. It crashes more consistently if I select the Node, turn Snap Relative off and then back on. Then select the Node2D and try to move it.

I haven't managed to reproduce it on Mageia (Linux) using those steps, though I don't think it would be system-specific (could be compiler-specific though if it's an optimisation bug).

On the other hand I've noticed this weird behaviour, cc @groud:
- Select Node parent:
![spectacle z20007](https://user-images.githubusercontent.com/4701338/33825248-5c5fc0dc-de61-11e7-8f59-ab61fd84a7b7.png)
- Toggle snapping:
![spectacle b20007](https://user-images.githubusercontent.com/4701338/33825262-6621af5e-de61-11e7-8b5d-fc99d2383e64.png)
Notice how the lock and selectability have changed? Clicking the buttons have no effect.
- Select Node2D child:
![spectacle q20007](https://user-images.githubusercontent.com/4701338/33825294-7e4b5922-de61-11e7-9981-ffc2526cee35.png)
Back to normal.

**Comment by groud** [comment] 2017-12-11 09:57
I have to solve all those issues. But the canvas item editor is now a pain to work with. I'm cleaning a lot of code by now, reviewing functionalities one after the other. Once I'm done, all those issue should be relatively easy to fix :)

**Comment by coppolaemilio** [comment] 2017-12-26 01:53
I can reproduce this on my personal project using Windows 10. Funny thing is that the error is not happening if I copy and paste that project to a new dir and import the copy from the welcome screen. There is no way for me to send you a project where you can reproduce it 👎 .

I have snap to grid activated, Toggle snapping (the magnet icon thing) and I'm in a 2D scene moving Sprite nodes inside a simple Node.


Error message:
```
GLES3: max ubo light: 409
GLES3: max ubo reflections: 455, ubo size: 144
ARVR: Registered interface: Native mobile
CrashHandlerException: Program crashed
Dumping the backtrace. Please include this when reporting the bug on https://github.com/godotengine/godot/issues
[0] <couldn't map PC to fn name>
[1] <couldn't map PC to fn name>
[2] <couldn't map PC to fn name>
[3] <couldn't map PC to fn name>
[4] <couldn't map PC to fn name>
[5] <couldn't map PC to fn name>
[6] <couldn't map PC to fn name>
[7] <couldn't map PC to fn name>
[8] <couldn't map PC to fn name>
[9] <couldn't map PC to fn name>
[10] <couldn't map PC to fn name>
[11] <couldn't map PC to fn name>
[12] <couldn't map PC to fn name>
[13] <couldn't map PC to fn name>
[14] <couldn't map PC to fn name>
[15] <couldn't map PC to fn name>
[16] <couldn't map PC to fn name>
[17] <couldn't map PC to fn name>
[18] <couldn't map PC to fn name>
[19] <couldn't map PC to fn name>
-- END OF BACKTRACE --
```

Hope it helps :/

**Comment by volzhs** [comment] 2018-01-05 21:54
@coppolaemilio I tested you sample with bb2341e81
can't reproduce it on ubuntu 17.10

* select 1 or 2 or 3 sprites
* moving around other sprites

I did this with these conditions

* use snap
* grid on / relative off
* grid off / relative on
* grid on / relative on

can you still reproduce it?

**Comment by coppolaemilio** [comment] 2018-01-06 03:22
I'm not sure about bb2341e since I can't build on my own. I downloaded the most recen build from http://godot3builds.digitecnology.com/ (a8a3d5c83) and it is still happening. Sorry I can't do more for now.

**Comment by poke1024** [comment] 2018-01-07 01:02
Cannot reproduce this. We need a proper stacktrace.

**Comment by vnen** [comment] 2018-01-07 01:27
I can reproduce this, but it doesn't happen all the time.

**Comment by vnen** [comment] 2018-01-07 01:51
Not really sure what's causing it, but managed to get a decent stack trace:

```
Unhandled exception thrown: read access violation.
List<Node * __ptr64,DefaultAllocator>::Element::get(...) returned 0xFFFFFFFFFFFFFFFF.
```

```
[0] CanvasItemEditor::_gui_input_viewport (godot\editor\plugins\canvas_item_editor_plugin.cpp:1911)
[1] CanvasItemEditor::_gui_input_viewport (godot\editor\plugins\canvas_item_editor_plugin.cpp:1911)
[2] MethodBind1<CanvasItemEditor,Ref<InputEvent> const & __ptr64>::call (godot\core\method_bind.gen.inc:815)
[3] Object::call (godot\core\object.cpp:914)
[4] Object::emit_signal (godot\core\object.cpp:1195)
[5] Object::emit_signal (godot\core\object.cpp:1241)
[6] Viewport::_gui_call_input (godot\scene\main\viewport.cpp:1485)
[7] Viewport::_gui_input_event (godot\scene\main\viewport.cpp:1982)
[8] Viewport::input (godot\scene\main\viewport.cpp:2448)
[9] Viewport::_vp_input (godot\scene\main\viewport.cpp:1325)
[10] MethodBind1<Viewport,Ref<InputEvent> const & __ptr64>::call (godot\core\method_bind.gen.inc:815)
[11] Object::call (godot\core\object.cpp:914)
[12] Object::call (godot\core\object.cpp:838)
[13] SceneTree::call_group_flags (godot\scene\main\scene_tree.cpp:248)
[14] SceneTree::input_event (godot\scene\main\scene_tree.cpp:404)
[15] InputDefault::parse_input_event (godot\main\input_default.cpp:346)
[16] OS_Windows::WndProc (godot\platform\windows\os_windows.cpp:453)
[17] WndProc (godot\platform\windows\os_windows.cpp:793)
[18] CallWindowProcW
[19] CallWindowProcW
[20] glDebugEntry
[21] CallWindowProcW
[22] DispatchMessageW
[23] OS_Windows::process_events (godot\platform\windows\os_windows.cpp:1825)
[24] OS_Windows::run (godot\platform\windows\os_windows.cpp:2303)
[25] widechar_main (godot\platform\windows\godot_win.cpp:150)
[26] _main (godot\platform\windows\godot_win.cpp:172)
[27] main (godot\platform\windows\godot_win.cpp:184)
[28] __scrt_common_main_seh (f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:283)
[29] BaseThreadInitThunk
-- END OF BACKTRACE --
```

**Comment by vnen** [comment] 2018-01-07 16:57
Fixed by #15433.

**Closed by vnen** 2018-01-07 16:57 UTC
Labels: bug, platform:windows, topic:editor

**Comment by Ron5s** [comment] 2018-03-29 03:48
Im getting this same error and crash on Windows 10. running v3.0.2 mono stable.  It seems like the same thing as this error.

CrashHandlerException: Program crashed
Dumping the backtrace. Please include this when reporting the bug on https://github.com/godotengine/godot/issues
[0] <couldn't map PC to fn name>
[1] <couldn't map PC to fn name>
[2] <couldn't map PC to fn name>
[3] <couldn't map PC to fn name>
[4] <couldn't map PC to fn name>
[5] <couldn't map PC to fn name>
[6] <couldn't map PC to fn name>
[7] <couldn't map PC to fn name>
[8] <couldn't map PC to fn name>
[9] <couldn't map PC to fn name>
[10] <couldn't map PC to fn name>
[11] <couldn't map PC to fn name>
[12] <couldn't map PC to fn name>
[13] BaseThreadInitThunk
-- END OF BACKTRACE --
Nothing read: No such file or directory
ERROR: StreamPeerTCPWinsock::read: Server disconnected!

   At: drivers\windows\stream_peer_tcp_winsock.cpp:203

**Comment by Noshyaar** [comment] 2018-03-29 04:52
The stack trace `<couldn't map PC to fn name>` isn't specific to any issues (i.e. useless). So you have to tell us what you were doing just before it crashed, or make a minimal project.

**Comment by Ron5s** [comment] 2018-03-29 13:15
@Noshyaar Thank you for the reply.  The code is written in C# and it occurs when I either draw a mesh with mesh instance or use queue_free() to delete the mesh instance nodes.  I haven't determined which one it is exactly.  But it doesn't happen every time.  Sometimes it takes a few tries to reproduce.

**Comment by plucian** [comment] 2018-08-23 08:03
I get the same error in 2.1.5 stable branch. I suspect to be an autoload/dictionary problem, seems totally unrelated to problems described above.
