### ISSUE TITLE
Null pointer at custom parameter setget export events

### ISSUE THREAD

**Issue by wagfeliz** [godotengine/godot#76386] opened 2023-04-24 01:46 UTC
### Godot version

4.02.stable

### System information

Linux Ubunto 22.04

### Issue description

Null pointer at custom parameter setget export events:

```gdscript
@export_group("This Component")
@export var someproperty: bool = false :
	set(value):
		get_parent()  # ..... -> null pointer
		$Camera/Camera3D.current  # ... -> accessing anything get null pointer
```

It happens when you load the node at the first time, just reseting any property that has set values...
What it suppose to do would be to be able to get the saved content and correctly load the object, it not only dont do that but gives null pointers errors.

### Steps to reproduce

Just create an export on any node or component :

```gdscript
@tool
class_name Bug  extends Node3D
@export_group("This Component")
@export var someproperty: bool = false :
	set(value):
		get_parent()
```

Set some value in editor on this property, close the node and try to load it again, in my env its getting null pointer and reseting the content of this property

### Minimal reproduction project
```gdscript
@tool
class_name Bug  extends Node3D
@export_group("This Component")
@export var someproperty: bool = false :
	set(value):
		get_parent()
```

**Comment by ajreckof** [comment] 2023-06-13 21:55
I think this is expected if you wish to call `get_node` or any of the related function you shoul always make sure that your node is inside the tree. This applies everywhere but is more visible inside setter as they are effectively called often outside tree. 

You should change your code to 
```gdscript
@export var some_property : int :
	set(value):
		if !is_inside_tree():
			await ready
		some_property = value
```

it won't complain and it will be properly set.

**Comment by adamscott** [comment] 2023-06-14 11:23
It's expected indeed. The same issue arises when trying to call `get_parent()` in `_init()`.

1. Parent node is loaded
2. Child nodes are loaded
3. Child nodes are ready
4. Parent node is ready

So you could use something like this:
```gdscript
@tool
class_name Bug  extends Node3D
@export_group("This Component")
@export var someproperty: bool = false :
	set(value):
		if not is_inside_tree():
			return
		$Camera/Camera3D.current = value

func _ready() -> void:
	someproperty = true
```

I'm closing as this is intended behavior.

**Closed by adamscott** 2023-06-14 11:23 UTC
Labels: bug, topic:gdscript
