### ISSUE TITLE
Unable to re-import HDRi maps

### ISSUE THREAD

**Issue by HK-SHAO** [godotengine/godot#69051] opened 2022-11-23 13:25 UTC
### Godot version

v4.0.beta5.official [89a33d28f]

### System information

Windows 11, Vulkan API 1.2.0 - Using Vulkan Device #0: AMD - AMD Radeon(TM) Graphics

### Issue description

Cannot reimport HDRi maps.

1. Every time godot gets stuck and unresponsive. When I killed the process and reopened godot, the hdr file was probably imported successfully
2. `.hdr` or `.exr` files imported as shaders `uniform sampler2D` do not work correctly in the browser
3. `cubemap` does not seem to work properly, and cannot set a texture for this resource
   - https://github.com/godotengine/godot/issues/65665

![](https://user-images.githubusercontent.com/24982550/203556673-f9d59d42-3484-430c-b562-751027701e0a.png)
![](https://user-images.githubusercontent.com/24982550/203556530-7667f51c-9dd9-46a8-b41c-1810d38b2d34.png)
![](https://user-images.githubusercontent.com/24982550/203556688-9ae1a1ea-c4a2-4938-a6c4-e94d67bd5dd7.png)

### Steps to reproduce

Every time you re-import as `sampler2D`

### Minimal reproduction project

https://github.com/HK-SHAO/Godot-RayTracing-Demo

**Comment by Calinou** [comment] 2022-11-23 14:04
Duplicate of https://github.com/godotengine/godot/issues/61948.

**Closed by Calinou** 2022-11-23 14:04 UTC

**Comment by HK-SHAO** [comment] 2022-11-23 16:01
> Duplicate of #61948.
> 
> > .hdr or .exr files imported as shaders uniform sampler2D do not work correctly in the browser
> 
> This is likely a WebGL 2.0 limitation with regards to HDR texture support.

but `three.js` is able to use HDR texture
