### ISSUE TITLE
Reimport do a automatic Reimport with old settings

### ISSUE THREAD

**Issue by fkrick** [godotengine/godot#27092] opened 2019-03-15 13:46 UTC
**Godot version:**
3.1 stable x64 X11

**OS/device including version:**
Fedora 28
OpenGL ES 3.0 Renderer: Mesa DRI Intel(R) UHD Graphics 620 (Kabylake GT2)

**Issue description:**
I try to reimport some textures used in 3D scene, after i hit the reimport button, godot editor start a Reimport after finish  the "custom settings reimport" and overwrite the .import file with old settings

**Steps to reproduce:**
1. Select a texture
2. open the import panel
3. do some custom settings
4. hit reimport
5. Wait until the first reimport progressbar finished
6. wait until the second progressbar ist finished
7. De-select the texture
8. select the texture and all old stings come up.

[simplescreenrecorder-2019-03-15_14.38.22.mp4.zip](https://github.com/godotengine/godot/files/2971317/simplescreenrecorder-2019-03-15_14.38.22.mp4.zip)

**Comment by fkrick** [comment] 2019-03-16 13:56
anyone ?

**Comment by akien-mga** [comment] 2020-01-15 10:11
Duplicate of #24220.

**Closed by akien-mga** 2020-01-15 10:11 UTC
Labels: bug, topic:import
