### ISSUE TITLE
Engine is null

### ISSUE THREAD

**Issue by wagfeliz** [godotengine/godot#76698] opened 2023-05-03 12:43 UTC
### Godot version

4.02.stable

### System information

Linux Ubunto 22.04

### Issue description

If you put in code something like this:
@export_group("Engine")

You will get error with godot engine for some reason :

if( Engine.is_editor_hint()): return
     -> Nonexistent function is_editor_hint in base Nil ...

### Steps to reproduce

extends Node
@export_group("Engine")
func _process(delta):
    if( Engine.is_editor_hint()): return

### Minimal reproduction project

extends Node
@export_group("Engine")
func _process(delta):
    if( Engine.is_editor_hint()): return

**Comment by AThousandShips** [comment] 2023-05-03 12:46
Duplicate of #73843 or related to it

**Comment by kleonc** [comment] 2023-05-03 16:51
Duplicate of #73843.

**Closed by kleonc** 2023-05-03 16:51 UTC
