### ISSUE TITLE
KinematicBody2D.move result in weird movement between KinematicBody2D

### ISSUE THREAD

**Issue by alexzheng** [godotengine/godot#8757] opened 2017-05-14 08:59 UTC
_bugsquad edit: reproduction project for 3.0 is here https://github.com/godotengine/godot/issues/8757#issuecomment-379476799_

-----------

**Operating system or device - Godot version:**
Mac OS godot version 2.1.3

**Issue description:**

when KinematicBody overlapped(for example they are spawned at the same position), call move, even the argument is vector2d(0,0),  the bodies will move to some uncertain positions, far away from its original position, it seems a force  is add to the bodies, and it can even move through  static collide bodies.

**Steps to reproduce:**
create some Kinematic Bodies at the the same position
add some static bodies with rectangular shape  to  create walls surround them
call move on each body
the Kinematic Bodies will move through the static bodies to the outside of the walls

please check the demo project, and click to  make the KinematicBody move
**Link to minimal example project:**

[kenimatic.zip](https://github.com/godotengine/godot/files/999211/kenimatic.zip)

**Comment by eon-s** [comment] 2017-05-14 12:24
I have noticed this behaviour in many (if not all) engines, what method should be used for separation if the first attempts fail? stop trying and leave the body as "stuck"?

**Comment by alexzheng** [comment] 2017-05-14 14:10
This bug makes a game using Kinematic Bodies to move unplayable,  some bodies will just move out of the screen and become unreachable, even if I have a wall at each side of the edge, the bodies will still move through the walls.

**Comment by eon-s** [comment] 2017-05-14 15:41
@alexzheng yes, I understand the problem, even if I see it as a bad design problem (two colliding bodies should never be forced into full overlap situation and expect a good separation) I would like to see a reasonable reaction from the Physics server (like ignoring them).

**Comment by alexzheng** [comment] 2017-05-15 08:37
Could the developers of Godot take Attention to this issue, It's really very serious, I have made a prototype for a game, but this issue prevent me from developing further for publish. Kinematic bodies will out of control for some situations.

**Comment by RebelliousX** [comment] 2017-05-16 09:09
Don't use KinematicBody then, there are plenty of closed issues about the same problem, reduz will tell you it is not a bug and can't be fixed.

A workaround is to move using set_pos() and check for collisions using direct space state for World2D, using intersection functions, it is your responsibility to stop the object from moving when colliding then.

For me I ditched the whole Physics for 2D. I admit they have their uses and produce awesome mechanics, but for specific issues like in platform games, you will be dealing with physics issues not related to your code more than when you are coding your game. And that is for all engines.

**Comment by kubecz3k** [comment] 2018-04-07 10:36
First of all thank you for your report and sorry for the delay.

We released Godot 3.0 in January 2018 after 18 months of work, fixing many old issues either directly, or by obsoleting/replacing the features they were referring to.

We still have hundreds of issues whose relevance/reproducibility needs to be checked against the [current stable version](https://godotengine.org/download), and that's where you can help us.
**Could you check if the issue that you described initially is still relevant/reproducible in Godot 3.0 or any newer version, and comment about its current status here?**

For bug reports, please also make sure that the issue contains detailed steps to reproduce the bug and, if possible, a zipped project that can be used to reproduce it right away. This greatly speeds up debugging and bugfixing tasks for our contributors.

Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

Thanks in advance.

*Note: This message is being copy-pasted to many "stale" issues (90+ days without activity). It might happen that it is not meaningful for this specific issue or appears oblivious of the issue's context, if so please comment to notify the Bugsquad about it.*

**Comment by akien-mga** [comment] 2018-11-22 11:37
Still reproducible with the above project in the current master branch (631cf676).

**Comment by KoBeWi** [comment] 2020-06-11 22:55
Still happens in 46e0e13
Although it's not as big problem as it sounds, because you rarely get two kinematic bodies inside each other. And even if they do, it's usually very slightly, so the push is not that big. So just don't put kinematic bodies on top of each other (why would you even need that).

**Comment by alexzheng** [comment] 2020-06-11 23:25
Overlapping happens when spawn a kinematic body.

**Comment by KoBeWi** [comment] 2020-06-11 23:28
Then prevent spawning them at the same position. E.g. put Area2D on the spawner and don't spawn if it's occupied. Or add some offset. You can't just put two physic objects at the exact position and expect them to behave predictably.

**Comment by alexzheng** [comment] 2020-06-11 23:35
The issue is it would pass through static bodys,that’s weird.

**Comment by KoBeWi** [comment] 2020-06-11 23:51
Yeah, that should definitely be fixed.

**Comment by madmiraal** [comment] 2020-07-27 08:24
#35945 will all but solve this issue, by ensuring that `KinematicBodies` are only moved the required distance to not overlap before attempting the move. However:
1. When both bodies are moved in the same physics frame, as in the [example project above](https://github.com/godotengine/godot/issues/8757#issuecomment-379476799), they are both moved from each other; so they look like they're being moved too far, but they're really only being moved away from the original position of the other body.
2. If the pre-move to stop them from overlapping results in a new collision, as in the wall in the [example project above](https://github.com/godotengine/godot/files/1886483/overlappingkinematics.zip), this will only be resolved in the next movement call. Note: if the body is stuck i.e. the pre-move cannot resolve all the collisions, the body is deemed stuck and no move is attempted.

I'm not sure whether these two minor points are enough to keep this issue open if #35945 is merged.

**Comment by akien-mga** [comment] 2021-04-28 13:41
This seems to be fixed in 3.3 (at least the MRP).

**Closed by akien-mga** 2021-04-28 13:41 UTC
Labels: bug, confirmed, discussion, topic:physics
