### ISSUE TITLE
Editor: Show Line Length Guideline(s) option shows up twice

### ISSUE THREAD

**Issue by eltharionx** [godotengine/godot#55554] opened 2021-12-02 18:10 UTC
### Godot version

3.4.stable

### System information

Windows 10

### Issue description

Two options in Editor Settings appear to do the same thing:

"Show Line Length Guideline(s)"

![linelength](https://user-images.githubusercontent.com/4984444/144478773-202a5929-975c-4b3e-be20-5e801d25bf91.png)

### Steps to reproduce

Open up Editor Settings:
General Tab > Text Editor > Appearance

You'll see two lines for Show Line Length Guideline(s)

**Comment by raulsntos** [comment] 2021-12-02 19:28
Most likely a consequence of renaming the setting in #49640, and therefore this would be a duplicate of godotengine/godot-proposals#3526.

**Closed** 2021-12-02 21:34 UTC
Labels: bug, topic:editor
