### ISSUE TITLE
Pressing "Shift" causes "W" and "S" key to not work correctly while running current scene (F6) - edit: It's ghosting...

### ISSUE THREAD

**Issue by KimeriX** [godotengine/godot#92046] opened 2024-05-17 09:46 UTC
### Tested versions

v4.2.2.stable.official [15073afe3]

### System information

Logitech Keyboard K120, Windows 10.0.22631 - Vulkan (Forward+) - dedicated AMD Radeon RX 6800 (Advanced Micro Devices, Inc.; 31.0.24027.1012) - 12th Gen Intel(R) Core(TM) i5-12400F (12 Threads)

### Issue description

If I am pressing W and S key to move a character up and down, if both  are pressed the character should not move as get_axis("Forward","Backward") results with 0.

Pressing Shift (to enable a movement state maybe) while or before pressing a key makes the other "opposite" key not register.
This only (at least from what I checked) with keys "W" and "S". 

If keys "Up" and "Down" are used, shift works correctly and when both are pressed get_axis result is 0.

If keys "A" and "D" are used with get_axis("Left","Right"), shift works correctly and when both are pressed get_axis result is 0.

If "Alt" is connected to the same action as "Shift" and it's pressed instead, "W" and "S" interact correctly.

If "W" and "S" are being pressed, shift is not even responding, as soon as one is released, shift works.

### Steps to reproduce

1. Map keys ("W" ,"Up")/ ("S" ,"Down") as move_forward / _backward
2. Map keys "Shift" / "Alt" as Sprint
3. Use get_axis("move_forward", "move_backward") and set it so that if != 0 print("walking") and if sprint is pressed print("Sprinting").
4. Set that if get_axis(...) is = 0 "idle" is printed instead.
5. Press W and then S, check if idle is being printed.
6. Then lift one (W or S) and check if walking is printed. 
7. Then press shift and check if sprinting is being printed.
8. Then press the other button ( W or S) and check if idle is NOT being printed. - If so, the bug is occurring, the intended behaviour should be that idle is being printed.

### Minimal reproduction project (MRP)

[Shift_Bug_Test.zip](https://github.com/godotengine/godot/files/15347039/Shift_Bug_Test.zip)

**Comment by AThousandShips** [comment] 2024-05-17 09:49
Can you confirm this isn't a result if ghosting? See [here](https://gamedev.stackexchange.com/a/109002)

**Comment by KimeriX** [comment] 2024-05-17 09:53
If it was ghosting, shouldn't this happen with any multiple combination of keys? (A + D, Up + Down, Left + Right) + Shift work indeed correctly. W + S + Alt also works.

**Comment by AThousandShips** [comment] 2024-05-17 09:55
Because ghosting is specific to certain keys due to groupings, so you should test with a detection program or page to show it registered all the keys, just to eliminate that possibility

**Comment by KimeriX** [comment] 2024-05-17 09:55
https://www.microsoft.com/applied-sciences/projects/anti-ghosting-demo

It seems it's ghosting... dang...

**Comment by KimeriX** [comment] 2024-05-17 09:58
My ghosting keys seem to be 1, 2, X and S in combination with shift.

**Comment by AThousandShips** [comment] 2024-05-17 10:01
Then this is unfortunately not something we can solve, if you find the same issue without ghosting that's something to investigate though, but closing this as it's not a bug in the engine

**Closed by AThousandShips** 2024-05-17 10:01 UTC
Labels: needs testing, topic:input
