### ISSUE TITLE
Godot allow to exist folders with the same name - e.g. AAA and aaa on windows

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#22475] opened 2018-09-27 12:30 UTC
**Godot version:**
3.1 8fc92ae

**OS/device including version:**
Windows 10

**Issue description and Steps to reproduce:**
When I have folder with name AAA I can't create folder with aaa, but when I create script and put it in new folder which have name aaa, godot create it and shouldn't do this.

https://streamable.com/kcjrz

**Comment by DualMatrix** [comment] 2018-09-27 23:08
Wouldn't allowing this break things on other OS's that don't distinguish between capitalization of folders?

**Comment by ni-code** [comment] 2018-09-28 01:02
@DualMatrix I believe that windows is the only OS around that thinks 'file_or_folder_name' and 'FiLe_Or_FoLdEr_NaMe' are the same.

Although NTFS can be configured to be case sensitive, it is turned off by default.

**Comment by akien-mga** [comment] 2018-09-28 07:19
I think that the Script Create Dialog should probably not be allowed to create folders on its own like this based on a manually typed path. There might be other ways to create such folder names with different case on Windows though that need to be handled at the Dir/FileAccess level probably.

**Comment by KellyThomas** [comment] 2018-09-28 09:03
Some of the macOS file systems default to a case insensitive mode.

**Comment by elasota** [comment] 2018-09-28 16:04
@akien-mga It actually can't create folders on its own.  If the destination directory doesn't exist, then the create script dialog will display an "Invalid path" error.  Even if that wasn't the case, partial paths where directories exist should be resolving to FS directories.

**Comment by dualtagh** [comment] 2018-10-03 15:29
Looks like a UI issue, not a directory creation issue. `AAA` & `aaa` are the pointing to the same folder. If you alt-tab away and back again, `AAA` is gone from FileSystem

**Comment by Anutrix** [comment] 2019-07-12 18:09
**Just Random Info:** Case sensitivity on Windows 10 is an NTFS system feature that can be enabled on a per-directory basis. This means that it wouldn't apply to your entire file system. That said, you can only add the feature to specific folders for development purposes. Case sensitivity on Windows 10 was included in the April 2018 Update.

**Comment by Zylann** [comment] 2021-06-25 18:25
The link to the video seems dead so basically I can still reproduce this in Godot 3.3.2 by doing this:
1) In the project, create a folder named `aaa`
2) In the script editor, create a new script
3) Use `Save As...`. The dialog starts in `res://` on the adress bar. Append `AAA` so it becomes `res://AAA`. Observe all files displayed by the dialog disappear.
4) Click Save: observe the directory was created with the script in it.

Other attempts at explicitely creating the folder are met with a `could not create folder` popup.

**Closed** 2024-04-06 11:07 UTC
Labels: bug, platform:windows, topic:editor, confirmed
