### ISSUE TITLE
Expose Object metadata to Editor

### ISSUE THREAD

**Issue by mhilbrunner** [godotengine/godot#29081] opened 2019-05-21 17:21 UTC
Based on the discussion in https://github.com/godotengine/godot/issues/18591, it may make sense to expose object metadata to be editable in the Editor.

**Comment by ArdaE** [comment] 2019-05-21 17:36
Does this mean metadata will also be available in the Inspector during debugging (when a "Remote" object is selected)? If not, please consider making it available, so values set by code at runtime can be viewed.

**Comment by KoBeWi** [comment] 2019-05-21 17:42
Duplicate of #5433 probably.

**Comment by YeldhamDev** [comment] 2019-05-21 20:52
There's already a pull for that: #22642
The problem is the internal metas used for the editor, a solution could be hiding any metas starting with "_".

**Closed** 2019-05-21 20:53 UTC
Labels: enhancement, topic:editor, usability
