### ISSUE TITLE
CollisionShape2D Rectangle does not render the top-left corner properly in editor

### ISSUE THREAD

**Issue by Shadetheartist** [godotengine/godot#71001] opened 2023-01-06 15:56 UTC
### Godot version

4.0 dev 95ce236b7d

### System information

Linux, Vulkan, Quatro T1000

### Issue description

Close inspection of the CollisionShape2D rectangle shows that the outline for the top left corner is not scaled the same as the rest of the lines around the rectangle. 

![image](https://user-images.githubusercontent.com/8973930/211047958-25b998eb-2239-4d31-8efc-54801ee79321.png)

![image](https://user-images.githubusercontent.com/8973930/211047988-bd5c5978-28b8-41f1-b671-67f7f01548f1.png)

### Steps to reproduce

Create a CollisionShape2D using the Rectangle shape and observe the top left corner. 

### Minimal reproduction project

[bug_report.zip](https://github.com/godotengine/godot/files/10361346/bug_report.zip)

**Comment by markdibarry** [comment] 2023-01-06 16:44
Duplicate of #56320

**Closed** 2023-01-06 16:49 UTC
