### ISSUE TITLE
Godot CSV/TXT File Export Don't Work On Build

### ISSUE THREAD

**Issue by CodeEasyYT** [godotengine/godot#41042] opened 2020-08-05 08:19 UTC
**Godot version:**
3.2.2.stable.mono

**Issue description:**
Hi, I am developing an android game. I'm using Godot Mono C#. Since there is no way to create custom resources on C#,
I wrote a file reading system which works perfectly when reading CSV files. Here is the example picture and code:
![Example](https://user-images.githubusercontent.com/59538669/89388359-935ac400-d70c-11ea-9a20-97199dab54b6.png)
```
using Godot;
using System.Collections.Generic;

public class CSVReader
{
    public readonly string Path;
    public string Text { get; private set; }

    List<string> Columns;
    List<List<string>> Values;

    public readonly CSVReaderFor ReadingFor;

    public CSVReader(string _CSVPath, CSVReaderFor _readingFor, bool _doNotCreateIfSameTypeExists = true)
    {
        if (_doNotCreateIfSameTypeExists && characterReader != null)
            return;

        Path = _CSVPath;

        Columns = new List<string>();
        Values = new List<List<string>>();
        ReadingFor = _readingFor;

        Read();

        if (ReadingFor == CSVReaderFor.CharacterReading)
            characterReader = this;
    }

    public string[] GetColumns()
    {
        return Columns.ToArray();
    }

    public string[] GetTheValueAt(int _index)
    {
        return Values[_index].ToArray();
    }

    public int GetTheIntValueAt(int _index, int _neededValue)
    {
        try
        {
            return int.Parse(Values[_index][_neededValue]);
        }
        catch
        {
            throw new System.Exception($"The needed value does not exist/wrong type ({_index}:{_neededValue}). (UnhandledException) From: CSVReader:{ReadingFor}");
        }
    }

    public string GetTheStringValueAt(int _index, int _neededValue)
    {
        return Values[_index][_neededValue];
    }

    public void Read()
    {
        File _f = new File();
        _f.Open(Path, File.ModeFlags.Read);

        DebugText.instance.Print("Reading CSV file at: " + Path);

        int _currentLine = -1;
        while(!_f.EofReached())
        {
            _currentLine++;

            string _line = _f.GetLine();
            string _goingToPrint = "";

            if(_line == "")
            {
                DebugText.instance.Print($"Unneeded line at Characters.csv:{_currentLine}. Skipping...", "CSVReader:" + ReadingFor);
                continue;
            }

            if (_currentLine == 0)
            {
                _goingToPrint = "Columns: ";

                for(int i = 0; i <_line.Split(';').Length; i++)
                {
                    Columns.Add(_line.Split(';')[i]);

                    if (i != _line.Split(';').Length - 1)
                        _goingToPrint += _line.Split(';')[i] + ", ";
                    else
                        _goingToPrint += _line.Split(';')[i];
                }

                DebugText.instance.Print(_goingToPrint, "CSVReader:" + ReadingFor);

                _currentLine++;
                continue;
            }

            _goingToPrint = "New Value: ";

            for (int i = 0; i < _line.Split(';').Length; i++)
            {
                string _goingToAdd = _line.Split(';')[i];

                if(_goingToAdd == "*")
                {
                    _goingToAdd = Values[_currentLine - 3][i];
                }

                Values.Add(new List<string>());
                Values[_currentLine - 2]
                    .Add(_goingToAdd);

                _goingToPrint += _goingToAdd;

                if (i != _line.Split(';').Length - 1)
                    _goingToPrint += ", ";
            }

            DebugText.instance.Print(_goingToPrint, "CSVReader:" + ReadingFor);
        }
    }

    //Static
    public static CSVReader characterReader = null;
}

public enum CSVReaderFor
{
    CharacterReading
}
```

**Main Problem:**
When I build the project (I build for android and pc for testing purposes), when I run the build file it says:
```
ERROR: File must be opened before use.
   At: core/bind/core_bind.cpp:2107
ERROR: File must be opened before use.
   At: core/bind/core_bind.cpp:2107
ERROR: File must be opened before use.
   At: core/bind/core_bind.cpp:2107
...
```
![What Happens](https://user-images.githubusercontent.com/59538669/89388015-10d20480-d70c-11ea-94cf-d1020e050321.png)
Is there a solution to fix this problem?

**Minimal Reproduction Project:**
This project includes:
 - `Montserrat-ExtraBold.ttf` font
 - 1 example scene
 - CSVReader class
 - A DebugText script (inherited from Label Node and already attached)
 - A script that results this issue.
 - A build.

[CSVFileReadError.zip](https://github.com/godotengine/godot/files/5027775/CSVFileReadError.zip)

**Comment by Calinou** [comment] 2020-08-05 10:05
@CodeEasyYT Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

**Comment by CodeEasyYT** [comment] 2020-08-05 10:39
@Calinou I uploaded a Minimal Reproduction Project to my post at the end of my post. Thanks for responding so fast.

**Comment by neqs20** [comment] 2020-08-05 14:18
Isn't it relates to the fact that Godot only exports 'Resource' type files ? 

Try adding `*.csv` to the export process.
It located in: Project -> Export... -> Resources -> Filters to export non-resource files/folders

**Comment by CodeEasyYT** [comment] 2020-08-05 15:21
@neqs20,
Firstly thanks for responding. But when I add to that part, error still continues.
Maybe another setting resulting this issue?

![image](https://user-images.githubusercontent.com/59538669/89431345-7a700400-d748-11ea-9a69-a931727eb003.png)

**Comment by nisovin** [comment] 2020-08-05 23:48
CSV files are imported as translation files by default. Try changing the import type of the CSV file.

**Comment by CodeEasyYT** [comment] 2020-08-06 06:17
@nisovin 
Before, with CSV Translation the file had a red "X" icon. Then I reimported it with CSV, and icon turned into a TXT File icon. None of tüm fixed the issue.

**Comment by Paulb23** [comment] 2020-08-06 08:16
Seems like a duplicate of #38957 / #38733 / #31749

**Comment by CodeEasyYT** [comment] 2020-08-06 08:47
Yeah, seems like it. But I didn't understand how Translation works. Can you explain it?

**Comment by Calinou** [comment] 2020-09-06 23:51
Duplicate of #39957.

**Closed by Calinou** 2020-09-06 23:51 UTC
