### ISSUE TITLE
Build warnings with Emscripten latest-upstream (LLVM 9)

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot#30247] opened 2019-07-02 11:08 UTC
**Godot version:**
3.2 master (266dc732)

**OS/device including version:**
Mageia 7 x86_64
Emscripten 1.38.30, using LLVM 9 upstream backend (`latest-upstream`)

**Issue description:**
Trying the `latest-upstream` branch of Emscripten which is about to become the new default backend. Doing a `release` build.

It generates some warnings that the current default `latest-fastcomp` branch doesn't raise:
```
platform/javascript/javascript_eval.cpp:55:57: warning: template argument uses local type '(anonymous union at platform/javascript/javascript_eval.cpp:45:2)' [-Wlocal-type-template-args]
        Variant::Type return_type = static_cast<Variant::Type>(EM_ASM_INT({
                                                               ^~~~~~~~~~~~
/home/akien/Projects/godot/emscripten/emsdk/upstream/emscripten/system/include/emscripten/em_asm.h:179:62: note: expanded from macro 'EM_ASM_INT'
#define EM_ASM_INT(code, ...) emscripten_asm_const_int(#code _EM_ASM_PREP_ARGS(__VA_ARGS__))
                                                             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/akien/Projects/godot/emscripten/emsdk/upstream/emscripten/system/include/emscripten/em_asm.h:122:7: note: expanded from macro '_EM_ASM_PREP_ARGS'
    , __em_asm_sig_builder::__em_asm_sig(__VA_ARGS__).buffer, ##__VA_ARGS__
      ^~~~~~~~~~~~~~~~~~~~
1 warning generated.
```
```
platform/javascript/os_javascript.cpp:993:2: warning: template argument uses unnamed type [-Wunnamed-type-template-args]
        EM_ASM_ARGS({
        ^~~~~~~~~~~~~
/home/akien/Projects/godot/emscripten/emsdk/upstream/emscripten/system/include/emscripten/em_asm.h:214:63: note: expanded from macro 'EM_ASM_ARGS'
#define EM_ASM_ARGS(code, ...) emscripten_asm_const_int(#code _EM_ASM_PREP_ARGS(__VA_ARGS__))
                                                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/akien/Projects/godot/emscripten/emsdk/upstream/emscripten/system/include/emscripten/em_asm.h:122:7: note: expanded from macro '_EM_ASM_PREP_ARGS'
    , __em_asm_sig_builder::__em_asm_sig(__VA_ARGS__).buffer, ##__VA_ARGS__
      ^~~~~~~~~~~~~~~~~~~~
./core/os/main_loop.h:53:2: note: unnamed type used in template argument was declared here
        enum {
        ^
platform/javascript/os_javascript.cpp:993:2: warning: template argument uses unnamed type [-Wunnamed-type-template-args]
        EM_ASM_ARGS({
        ^~~~~~~~~~~~~
/home/akien/Projects/godot/emscripten/emsdk/upstream/emscripten/system/include/emscripten/em_asm.h:214:63: note: expanded from macro 'EM_ASM_ARGS'
#define EM_ASM_ARGS(code, ...) emscripten_asm_const_int(#code _EM_ASM_PREP_ARGS(__VA_ARGS__))
                                                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/akien/Projects/godot/emscripten/emsdk/upstream/emscripten/system/include/emscripten/em_asm.h:122:7: note: expanded from macro '_EM_ASM_PREP_ARGS'
    , __em_asm_sig_builder::__em_asm_sig(__VA_ARGS__).buffer, ##__VA_ARGS__
      ^~~~~~~~~~~~~~~~~~~~
./core/os/main_loop.h:53:2: note: unnamed type used in template argument was declared here
        enum {
        ^
platform/javascript/os_javascript.cpp:993:2: warning: template argument uses unnamed type [-Wunnamed-type-template-args]
        EM_ASM_ARGS({
        ^~~~~~~~~~~~~
/home/akien/Projects/godot/emscripten/emsdk/upstream/emscripten/system/include/emscripten/em_asm.h:214:63: note: expanded from macro 'EM_ASM_ARGS'
#define EM_ASM_ARGS(code, ...) emscripten_asm_const_int(#code _EM_ASM_PREP_ARGS(__VA_ARGS__))
                                                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/akien/Projects/godot/emscripten/emsdk/upstream/emscripten/system/include/emscripten/em_asm.h:122:7: note: expanded from macro '_EM_ASM_PREP_ARGS'
    , __em_asm_sig_builder::__em_asm_sig(__VA_ARGS__).buffer, ##__VA_ARGS__
      ^~~~~~~~~~~~~~~~~~~~
./core/os/main_loop.h:53:2: note: unnamed type used in template argument was declared here
        enum {
        ^
platform/javascript/os_javascript.cpp:993:2: warning: template argument uses unnamed type [-Wunnamed-type-template-args]
        EM_ASM_ARGS({
        ^~~~~~~~~~~~~
/home/akien/Projects/godot/emscripten/emsdk/upstream/emscripten/system/include/emscripten/em_asm.h:214:63: note: expanded from macro 'EM_ASM_ARGS'
#define EM_ASM_ARGS(code, ...) emscripten_asm_const_int(#code _EM_ASM_PREP_ARGS(__VA_ARGS__))
                                                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/akien/Projects/godot/emscripten/emsdk/upstream/emscripten/system/include/emscripten/em_asm.h:122:7: note: expanded from macro '_EM_ASM_PREP_ARGS'
    , __em_asm_sig_builder::__em_asm_sig(__VA_ARGS__).buffer, ##__VA_ARGS__
      ^~~~~~~~~~~~~~~~~~~~
./core/os/main_loop.h:53:2: note: unnamed type used in template argument was declared here
        enum {
        ^
4 warnings generated.
```

Then I get an actual error, but that's for another issue (*Edit:* #30248).

**Steps to reproduce:**
- `./emsdk install latest-upstream`
- `./emsdk activate latest-upstream`
- `source emsdk_env.sh`
- `scons p=javascript target=release`

**Comment by Faless** [comment] 2020-02-21 07:37
This seems fixed in latest versions of emscripten please reopen if you still encounter it, I can't reproduce this any more.

**Closed by Faless** 2020-02-21 07:37 UTC
Labels: bug, platform:html5, topic:buildsystem
