### ISSUE TITLE
Export value shown twice.

### ISSUE THREAD

**Issue by mageowl** [godotengine/godot#63928] opened 2022-08-04 22:53 UTC
### Godot version

4.0.alpha13

### System information

MacOS 12.5

### Issue description

I am exporting a NoiseTexture using `@export`. It shows up twice in the inspector and removing the `@export` makes both disappear.

```gdscript
extends Node2D

@export var noise: NoiseTexture = null;

func _ready():
	pass # Replace with function body.


func _process(delta):
	pass
```
<img width="1440" alt="Screen Shot 2022-08-04 at 3 43 28 PM" src="https://user-images.githubusercontent.com/32573897/182967354-fe635dad-e694-4730-a5a0-b2e32b2df53c.png">

### Steps to reproduce

1. Create a new node with a script.
2. Add a `@export`ed NoiseTexture
3. Two values appear in the inspector.
4. Change the type to a String
5. Only one input changes type.

### Minimal reproduction project

My Project:
[Archive.zip](https://github.com/godotengine/godot/files/9263841/Archive.zip)

**Comment by kleonc** [comment] 2022-08-05 00:15
Duplicate of #63668.

**Closed by kleonc** 2022-08-05 00:15 UTC
