### ISSUE TITLE
Not coherent content in tscn file 

### ISSUE THREAD

**Issue by git2013vb** [godotengine/godot#15067] opened 2017-12-26 13:46 UTC
**Godot version:**
3.0 beta
**OS/device including version:**
Windows 7-64 

**Issue description:**
Snip code from tscn file:
-------------start snip code---------------
[sub_resource type="ViewportTexture" id=11]

resource_local_to_scene = true
viewport_path = NodePath("Node2D/ViewportContainer/Viewport")

[sub_resource type="Shader" id=12]

code = "shader_type canvas_item;

render_mode blend_add;

"

[sub_resource type="ShaderMaterial" id=13]

render_priority = 0
shader = SubResource( 12 )
----------end snip code--------------

the weird content is right after `code = "shader_type canvas_item;`

is is highly possible this situation bring at this error I have:

![image](https://user-images.githubusercontent.com/13235119/34357921-124ad87c-ea43-11e7-9f97-5d3b233ad5c7.png)

**Steps to reproduce:**
Is unknown at this moment. I will try to reproduce it.

**Minimal reproduction project:**

- [ ] I searched the existing [GitHub issues](https://github.com/godotengine/godot/issues?utf8=%E2%9C%93&q=is%3Aissue+) for potential duplicates.

**Comment by vnen** [comment] 2017-12-26 13:55
I fail to see anything weird. The error message is caused by a node not found: your ViewportTexture is pointing to a node that's not on the scene.

**Comment by git2013vb** [comment] 2017-12-26 14:04
This is a "pattern" that i don't recognize :
------------------------------------
code = "shader_type canvas_item;

render_mode blend_add;

"
----------------------------------

I checked all tsnc files I this snip code seems to me out of place.

**Comment by reduz** [comment] 2017-12-26 14:07
it's coherent, it matches this:
```
code = --> " <-- shader_type canvas_item;
```

the error is because you used a viewport texture and you most likely forgot to set local to scene in the material you assigned it to.

**Comment by reduz** [comment] 2017-12-26 14:08
This should probably be automatic (detecting it's set to a material and set that local to scene)

**Comment by reduz** [comment] 2017-12-26 14:08
still, not a bug so closing

**Closed by reduz** 2017-12-26 14:08 UTC

**Comment by git2013vb** [comment] 2017-12-26 14:18
Thank you for your explanation.  :)

There is a way to me to understand where is the origin of this problem if I check the tscn file? 
Because in scene I don't see any problems

Thank you

**Comment by git2013vb** [comment] 2017-12-26 14:24
I checked now and I see the whole sub section:
-------------------------------------------------------------
[sub_resource type="ViewportTexture" id=11]

resource_local_to_scene = true
viewport_path = NodePath("Node2D/ViewportContainer/Viewport")

[sub_resource type="Shader" id=12]

code = "shader_type canvas_item;

render_mode blend_add;

"
------------------------------------------------------

I see that is set to true in resource_local_to_scene.  Is this property that you mentioned before?

Any way how I can find this none in my scene? 

Thank you :)

**Comment by reduz** [comment] 2017-12-26 14:29
the problem is that a resource set to local to scene (in this case the viewport, which is set to that by default), can't be used inside another resource unless it's also set to local to scene.

**Comment by git2013vb** [comment] 2017-12-26 14:37
I found where my problem was - I followed the ID trail :) 
I have an attempt to add some shader code in a label .

![image](https://user-images.githubusercontent.com/13235119/34358701-ff38909c-ea49-11e7-854c-f62131909b34.png)


As you can see the content match :)

Thank you for your help .
