### ISSUE TITLE
The 2D skeleton deformation in 4.0 is broken

### ISSUE THREAD

**Issue by anunknowperson** [godotengine/godot#72515] opened 2023-02-01 14:34 UTC
### Godot version

4.0.beta15.official [4fa6edc88]

### System information

Windows 10, Forward+

### Issue description

The deformation of the polygons does not correspond to the position of the skeleton in the simple image.

![image](https://user-images.githubusercontent.com/54563399/216071443-ecfb0c90-d84f-4b16-ae39-37171c328ac6.png)

### Steps to reproduce

Download a test project
or
create a skeleton for a simple picture yourself and try to deform it.

### Minimal reproduction project

[2d_animation_bug_test.zip](https://github.com/godotengine/godot/files/10558022/2d_animation_bug_test.zip)

**Comment by Calinou** [comment] 2023-02-01 14:40
Related to https://github.com/godotengine/godot/issues/71962 and https://github.com/godotengine/godot/issues/71108.

**Comment by anunknowperson** [comment] 2023-02-01 14:57
![image](https://user-images.githubusercontent.com/54563399/216077791-9d5d02f6-72a0-43e9-b373-46f16f7e0788.png)
Also, in the bone weights editing menu, the position of the image does not correspond to the positions of the bones, which is very inconvenient.

**Comment by clayjohn** [comment] 2023-02-01 15:12
Duplicate of: https://github.com/godotengine/godot/issues/71108

Fixed by: https://github.com/godotengine/godot/pull/72214

**Closed by clayjohn** 2023-02-01 15:12 UTC
Labels: bug, topic:rendering, topic:2d

**Comment by anunknowperson** [comment] 2023-02-01 15:14
> Did this solve the problem with the bone weight editor (screenshot above)?

**Comment by anunknowperson** [comment] 2023-02-01 15:14
> Duplicate of: #71108
> 
> Fixed by: #72214

Did this solve the problem with the bone weight editor (screenshot above)?
