### ISSUE TITLE
Shader language doesn't allow assigning constants with certain values, i.e. pow(x,y)

### ISSUE THREAD

**Issue by stryker313** [godotengine/godot#81391] opened 2023-09-06 20:16 UTC
### Godot version

3.6 beta 2

### System information

Windows 10 gtx 1060 6gb intel i5 4690k

### Issue description

In the shading language, when attempting to assign a constant with pow, an error is thrown.

### Steps to reproduce

1. Open a new shader, and try to assign a constant float to the value of pow(2,1), or similar value
Sample code
```

shader_type spatial;

uniform float lod : hint_range(0.0, 1.0) = 1.0;
const float QUARTER_COLOR = lod/2.0;
const float QUARTER_COLOR1 = pow(2,lod);
```

the error "Expected constant expression after '=' is thrown

related #33840

### Minimal reproduction project

[Bug.zip](https://github.com/godotengine/godot/files/12542102/Bug.zip)

**Comment by bitsawer** [comment] 2023-09-07 12:50
Thanks for the report. Looks like a duplicate of https://github.com/godotengine/godot/issues/48525, so closing to keep discussion in one place. Currently, this is an intentional Godot 3 (and currently also Godot 4) restriction to maximize portability, see the discussion in the linked issue.

**Closed by bitsawer** 2023-09-07 12:50 UTC
Labels: bug, topic:shaders

**Comment by Xynonners** [comment] 2023-09-13 09:13
@bitsawer if I'm not mistaken #48525 is talking about uniform expressions, while this report is for constant expressions. 

In that godot 3.3 issue, the following is fine:
```
// ok
const float c = 1.0 / sqrt(2.0);
```
However on godot 4.1, doing so throws the error:
```
error(3): Expected constant expression.
```

**Comment by bitsawer** [comment] 2023-09-13 13:37
The title does mention constant expression, but the code example in the first post uses an uniform expression and then tries to use that uniform in a constant, which is not going to work (and is direct duplicate of https://github.com/godotengine/godot/issues/48525):

``` glsl
uniform float lod : hint_range(0.0, 1.0) = 1.0;
const float QUARTER_COLOR = lod/2.0;
```

Looks some of these issues were supposed to be fixed by the PR linked to https://github.com/godotengine/godot/issues/33840  but maybe the linked PR didn't fix them fully or the problem has come back at some point. So this issue seems to be kind of semi-duplicate which has two different problems where the uniform constant part is already tracked elsewhere and the other problem has been marked as solved, but doesn't seem to be fully.
