### ISSUE TITLE
2D / render glitches with "Pixel Snap", Camera2D node, rotated shapes, and certain window and camera position values

### ISSUE THREAD

**Issue by wingedadventurer** [godotengine/godot#29677] opened 2019-06-11 12:46 UTC
**Godot version:**
3.1.1

**OS/device including version:**
Win10

**Issue description:**
Polygon2D node doesn't get affected by "Use Pixel Snap" project setting. It gets certain glitches when the setting is on (though it looks fine when that setting is off).

The reason I need "Use Pixel Snap" is that I'm also using a TileMap. Having both TileMap and Polygon2D, they don't get along.

This is how my level looks like, consisting of TileMap walls and Polygon2D door object (seen from editor):

![level](https://user-images.githubusercontent.com/26509794/59272601-a5e78380-8c56-11e9-8c2a-c75d2bae757d.png)

This is what it looks like in-game with "Use Pixel Snap" turned OFF:
(tiles are messed up as expected, but polygon is fine)

![no-snap](https://user-images.githubusercontent.com/26509794/59272459-5ef98e00-8c56-11e9-9042-0b013f2e1f8a.png)

This is what it looks like in-game with "Use Pixel Snap" turned ON:
(tiles are fixed, but now polygon is glitchy)

![snap](https://user-images.githubusercontent.com/26509794/59272643-bd267100-8c56-11e9-9e3c-409e30005895.png)

My Door object looks like this when it's opened, all vertices aligned to pixel grid:

![door](https://user-images.githubusercontent.com/26509794/59272675-cca5ba00-8c56-11e9-8fa7-45a007671e67.png)

**Comment by clayjohn** [comment] 2019-06-11 15:00
It looks like your door is rotated by a small amount. Take a look at its transformation and the transformation of all its parents and make sure none are off.

**Comment by wingedadventurer** [comment] 2019-06-11 15:17
@clayjohn I double-checked, everything is perfectly positioned, rotated, and scaled. All vertices have integer coordinates.

It's not just the door object that has this problem. Few other examples:

![e1](https://user-images.githubusercontent.com/26509794/59284499-a4c15100-8c6c-11e9-9bbc-7b80fb54c967.png)
![e2](https://user-images.githubusercontent.com/26509794/59284506-a68b1480-8c6c-11e9-8bc0-888a8feb681f.png)

This only happens on certain camera zoom levels.

**Comment by clayjohn** [comment] 2019-06-11 16:15
Is the camera rotated then? Similar issues have come up in the past and it has almost always been the transform of the camera or node.

**Comment by wingedadventurer** [comment] 2019-06-11 16:20
@clayjohn The Camera2D node has normal transforms as well. Although the way I implemented the camera is that its zoom property is dynamic - constantly changes over time. Some parts of my game the camera is "pulsing" (zooming in and out), and you can see the glitches on very few frames (but still visible). Other times the zoom is static, but again on certain positioning of the player (which is followed by camera) you can spot the glitches.

**Comment by clayjohn** [comment] 2019-06-11 16:28
That sounds sufficiently different from prior issues. Can you upload a minimal reproducible project so that others can confirm and fix this issue?

**Comment by wingedadventurer** [comment] 2019-06-14 08:35
Right, after some fiddling I found the cause. Basically the glitch happens if these conditions are met:

1. Pixel Snap project setting is on;
2. Camera2D node is used;
3. the glitching object's rotation is 90° (tested on Sprite and on Polygon2D);
4. certain combination of (display_window_width, camera.position.x) or (display_window_height, camera.position.y) is achieved.

Little more explanation on 4.:

- If window size values are EVEN, and camera's coords are set to .5 values, you will get the glitch on rotated object.
- If window size values are ODD, and camera's coords are set to .0 values, you will get the glitch on rotated object.

Below are some examples (red nodes are glitchy ones):

![06-14-2019 10-19-06 AM](https://user-images.githubusercontent.com/26509794/59495402-7bccd600-8e8f-11e9-8abf-6277d9a0264f.png)
![06-14-2019 10-19-10 AM](https://user-images.githubusercontent.com/26509794/59495416-7ff8f380-8e8f-11e9-9883-63c6783f013f.png)
![06-14-2019 10-19-21 AM](https://user-images.githubusercontent.com/26509794/59495421-825b4d80-8e8f-11e9-8ab3-2af66c34cdae.png)
![06-14-2019 10-19-25 AM](https://user-images.githubusercontent.com/26509794/59495428-84251100-8e8f-11e9-8c90-c6c11bef9137.png)
![06-14-2019 10-19-40 AM](https://user-images.githubusercontent.com/26509794/59495432-86876b00-8e8f-11e9-82de-1c8bc250a745.png)
![06-14-2019 10-19-53 AM](https://user-images.githubusercontent.com/26509794/59495435-87b89800-8e8f-11e9-8a03-4bc5c672dd8c.png)

I'm also providing this "minimal" reproduction project with instructions:
[Pixel Snap Bug.zip](https://github.com/godotengine/godot/files/3289754/Pixel.Snap.Bug.zip)

**Comment by Zireael07** [comment] 2019-06-14 08:48
As usual, you can't avoid pixels moving around when there are non-integer positions/scales involved.

**Comment by wingedadventurer** [comment] 2019-06-14 08:56
Yes, but why would that happen only when the object is rotated 90°, and not when it's not rotated?

And why would it happen if camera's position has integer values, but the window has an ODD value, ex. (1025, 600)?

**Comment by clayjohn** [comment] 2019-06-19 01:49
Experimenting with this and #29882 it seems that the issue only comes up when setting rotation in editor. 

If you set ``rotation_degrees`` to ``90`` in ``ready()`` then the problem goes away.

**Comment by wingedadventurer** [comment] 2019-06-29 21:01
Calling `rotation_degrees = round(rotation_degrees)` in `_ready` indeed does fix this temporarily, thanks. 🙂

**Comment by KoBeWi** [comment] 2020-08-13 18:21
Looks fixed in 9413446b2 (the rectangles from MRP are no longer deformed). Still valid in 3.2.3 rc3, but since a workaround exists, it should be fine to close this.

**Closed by KoBeWi** 2020-08-13 18:21 UTC
Labels: bug, topic:core, topic:editor, topic:rendering
