### ISSUE TITLE
Daylight Savings Time triggers an unnecessary File Update Prompt in Windows

### ISSUE THREAD

**Issue by chooper-git** [godotengine/godot#84543] opened 2023-11-06 17:51 UTC
### Godot version

v4.1.2.stable.official [399c9dc39]

### System information

Godot v4.1.2.stable - Windows 10.0.19045 - Vulkan (Compatibility) - AMD Radeon(TM) RX Vega 11 Graphics (Advanced Micro Devices, Inc.; 26.20.13028.13) - AMD Ryzen 5 2400G with Radeon Vega Graphics (8 Threads)

### Issue description

Project was open with all files saved on my Windows machine the night before Daylight Savings Time (Location: California).  The next day with a starting working in my project I was greeted by a Pop-Up dialogue warning me of "Newer scripts on disk" and it presented several options like "Revert", "Save Over" & "Scan".  (note: I didn't take pics, so titles and text may not be totally accurate in my description).   All my files were "saved" in the project so I closed the window without selecting any of the provided buttons.  It soon prompted again, so I decided to "Save Over" and move on as I don't edit my files outside the Godot program, so there was no way the Files On Disk could be newer.  Then it dawned on me that perhaps the Window OS was updated at 2am automatically when Daylight Savings switched and caused the files in Godot to be out of temporal sync with the ones on Disk.  Had I been working in my Project and selected "Revert" I could have lost data.  I posted this to Reddit and the community feels his is indeed a bug limited to Windows and can only occur twice a year with Daylight Savings time adjustments.

### Steps to reproduce

Live in a location that obeys Daylight Savings time adjustments
Open a Godot project on a Windows computer with at least one script saved on disk
Leave your project loaded when a Daylight Savings Time adjustment occurs (or maybe this can be simulated)
See the file warning popup daig

### Minimal reproduction project

"N/A"

**Comment by AThousandShips** [comment] 2023-11-06 17:51
Duplicate of https://github.com/godotengine/godot/issues/74816

**Closed by AThousandShips** 2023-11-06 17:51 UTC
