### ISSUE TITLE
Incorrect Top, Right, Left and Bottom neighbour calculations when in BoxContainer that has negative seperation

### ISSUE THREAD

**Issue by sydist** [godotengine/godot#86523] opened 2023-12-26 12:31 UTC
### Tested versions

Godot v4.2.1.stable

### System information

Godot v4.2.1.stable - Windows 10.0.19044 - Vulkan (Mobile) - dedicated NVIDIA GeForce GTX 1660 Ti (NVIDIA; 31.0.15.4584) - Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz (12 Threads)

### Issue description

When focusable nodes are inside a BoxContainer that has a negative Seperation value, the neigbour calculations break.
It seems to skip some nodes.

### Steps to reproduce

1. Open the MRP
2. Start the program
3. Use the up and down arrows

### Minimal reproduction project (MRP)

[focus_bug.zip](https://github.com/godotengine/godot/files/13771477/focus_bug.zip)

**Comment by rsubtil** [comment] 2023-12-28 14:26
Duplicate of https://github.com/godotengine/godot/issues/82796

**Comment by AThousandShips** [comment] 2023-12-28 14:33
Closing as a duplicate of:
* #82796

Thank you for reporting

**Closed by AThousandShips** 2023-12-28 14:33 UTC
Labels: bug, needs testing, topic:gui
