### ISSUE TITLE
Physics operations go unaccounted for in the Profiler

### ISSUE THREAD

**Issue by Reousa** [godotengine/godot#39326] opened 2020-06-05 17:49 UTC
Possibly related issues: #37455, #23715

**Godot version:**
3.2.1

**OS/device including version:**
Windows 10

**Issue description:**
In our project, we've had two intersecting areas centered on the player that serve to detect certain far static bodies entering them, for LOD purposes.
Upon increasing the values of these areas, performance started to exponentially decrease.

This is displayed in the profiler as follow:
![image](https://user-images.githubusercontent.com/18017673/83909278-c9a9b080-a768-11ea-89f3-973da64e6583.png)

which doesn't quite add up.

**Steps to reproduce:**
Theoretically speaking, create two intersecting areas, on a movable object & give them access to interact with static bodies at relatively long ranges.

**Minimal reproduction project:**
Sadly I wasn't able to replicate this in a smaller sized project, so here are some git references:
[Broken commit](https://github.com/moonwards1/Moonwards-Virtual-Moon/commit/df3db5cb0cad839873901af53c83d7bd9f9cc635)
[Working commit](https://github.com/moonwards1/Moonwards-Virtual-Moon/commit/e27629080bfa0cbb1840609675ed5a74ee6f4388)

**Comment by Reousa** [comment] 2020-06-05 18:27
A little unrelated but I didn't feel creating a new issue without confirmation is a good idea - is that kind of performance loss normal for this use-case?

Areas were being set to scales of 300 & 500 respectively, but also 100 & 200 caused a huge performance hit - in relation to the default 20 & 40 (so about 5x the range)

**Comment by Calinou** [comment] 2020-06-05 20:32
Duplicate of https://github.com/godotengine/godot/issues/23715.

**Closed by Calinou** 2020-06-05 20:32 UTC
