### ISSUE TITLE
Atlas texture do not work whit particles and texture progress

### ISSUE THREAD

**Issue by CHIESOFTWARE** [godotengine/godot#35231] opened 2020-01-17 10:44 UTC
**Godot version:**
3.1.2
**OS/device including version:**
linux, ubuntu studio 19
**Issue description:**
i try to assign a texture for a particle node , i use an atlas texture but is not visible,  if i separate that texture an i use it as a single file it work fine. i think is inefficient to have single files for particles.

Also if i try to assign a texture atlas to a texture progress node the texture progress node glitch 
**Steps to reproduce:**
To reproduce the issue whit particles just create a particle node, them assign an atlas texture to it an select a region from the atlas.

To reproduce the glitch whit the texture progress just assign an atlas texture to a texture progress and select the region from the atlas texture.  
**Minimal reproduction project:**

**Comment by arkology** [comment] 2020-01-17 11:40
About TextureProgress is better described in https://github.com/godotengine/godot/issues/34837

**Comment by Calinou** [comment] 2020-01-17 13:11
Duplicate of #33855 and #34837.

**Closed by Calinou** 2020-01-17 13:11 UTC

**Comment by CHIESOFTWARE** [comment] 2020-01-17 14:00
> Duplicate of #33855 and #34837 , It said closed,  but is fixed ? I'm using godot 3.1.2 and the error still there

**Comment by akien-mga** [comment] 2020-01-17 14:03
> It said closed, but is fixed ? I'm using godot 3.1.2 and the error still there

It's closed because it's a duplicate of pre-existing issues. These issues are still open, so no, the bug is still not fixed.
