### ISSUE TITLE
class reference or use of class constant disables scene on android [v3.2.3]

### ISSUE THREAD

**Issue by duane-r** [godotengine/godot#40987] opened 2020-08-03 08:47 UTC
**Godot version:**
v3.2.3.rc3.official

**OS/device including version:**
Moto G cell phone, android 7.1.2
archlinux, amd ryzen integral graphics

**Issue description:**
A reference to a scene class in an unused method in a child scene causes that scene to vanish when running on android.

**Steps to reproduce:**
I started a scene, programmatically creating a large colorbox and attaching another scene containing a colorbox. The daughter scene has an unused function with an argument of the class type of the parent. The two scenes should appear as an orange background with a gray square on it. This works on linux, but the daughter scene disappears when exported to android, leaving just an orange background.

If I remove the argument from the unused function in the daughter scene, the android export works as expected. The sample works with or without the argument in stable Godot 3.2.

The attached project is probably a better explanation. See the comment in the Map.gd file.

**Minimal reproduction project:**
[class-ref-bug.zip](https://github.com/godotengine/godot/files/5014824/class-ref-bug.zip)

**Comment by duane-r** [comment] 2020-08-18 14:18
Any use of a class constant will cause the same problem with android builds. Again, this works on stable godot 3.2.2, but fails on 3.2.3rc3. See this slightly modified example.

In a project I'm currently working on, the problem is so severe that the android build simply crashes. Removing all references to class constants fixes the issue, but it's a serious pain.

[tn-bug.zip](https://github.com/godotengine/godot/files/5090891/tn-bug.zip)

**Comment by Calinou** [comment] 2020-08-18 14:29
Duplicate of https://github.com/godotengine/godot/issues/40991.

**Closed by Calinou** 2020-08-18 14:29 UTC
Labels: bug, topic:core
