### ISSUE TITLE
iOS input delay on exports from 3.2.3

### ISSUE THREAD

**Issue by mtk4000** [godotengine/godot#42164] opened 2020-09-18 11:28 UTC
**Godot version:**

3.2.3.stable.official

**OS/device including version:**

Issue is present on two devices I've tested:
- iPhone X, iOS 14.0
- iPad 6th generation, iPadOS 13.6.1

**Issue description:**

There is a noticeable delay (~250ms) between the time the screen is tapped and the time _input(event) fires.

**Steps to reproduce:**
1. Download Multitouch View Demo from Asset Library
2. Export to iOS using 3.2.3.stable export template
3. Install and run on iOS device

**Comment by Calinou** [comment] 2020-09-18 19:54
See also https://github.com/godotengine/godot/issues/41452. Can you reproduce this on Godot 3.2.2?

**Comment by mtk4000** [comment] 2020-09-18 21:39
No; I just exported the same Multitouch View Demo project using 3.2.2 and it ran perfectly on both devices. I'll try 3.2.3-rc4 to see if it's related to #41452.

**Comment by naithar** [comment] 2020-09-27 12:17
The delay is 150ms same as iOS's delay for some native views.
It will also fire immediately on touch movement or touch being released.

Related code is in: https://github.com/godotengine/godot/blob/3.2/platform/iphone/gl_view_gesture_recognizer.m

The issue linked above (#41452) also has the discussion on why it's working this way now and why the problem from that issue occurred.

The delay could probably be lowered a little, but this would require testing with project from initial issue.

**Comment by mtk4000** [comment] 2020-09-27 14:09
Thanks for your response. I'm not sure I understand though. Is there really no way to detect an iOS tap before 150ms have passed? It seems like this would break the responsiveness of a lot of games. It's very noticeable. Is there any workaround to get iOS input faster?

**Comment by naithar** [comment] 2020-09-27 15:42
As I previously said, if you release the touch before 150ms delay, touch events would fire immediately, so 150ms delay basically has no effect on input. 
And tap, which is essentially a press and fast release, should be working correctly as before. 
Also in PR and issue that was fixed with it I've mentioned why this fixed was introduced. Basically on newest phones iOS fires `moved` events even if no movement happened.

I haven't found any issue with my iOS project with this implementation. With 3.2.2 I had to make a workarounds so game would correctly handle taps. 
And the problem from #41452 was happening only because iOS queues input events instead of firing them when they happen, like Android does.

**Comment by mtk4000** [comment] 2020-09-27 15:53
Sorry, maybe "tap" was the wrong word. I have a project where you press and hold to move. There's no gesture or release to trigger further input, so I relied on the initial event. Worked great in 3.2.2, but now with the delay I need to find a workaround.

**Comment by naithar** [comment] 2020-09-27 16:04
Moving delay value into project settings should probably give more control over the input for cases like yours.

**Comment by naithar** [comment] 2020-09-27 17:34
@mtk4000 I've made some modifications in this branch - https://github.com/naithar/godot/tree/feature/ios-delay-in-settings 
You can change default delay in ProjectSettings at `Input Devices -> Pointing`.

**Comment by mtk4000** [comment] 2020-09-28 16:32
Works great. Thank you very much for your help.

**Comment by naithar** [comment] 2020-09-28 18:44
That's great. I'll try to make PR soon, so this would make into 3.2.4.

**Closed** 2020-10-01 10:16 UTC
Labels: discussion, platform:ios, topic:input

**Comment by Joseaay** [comment] 2020-10-05 09:32
Having the same issue here since I moved to 3.2.3, how can I solve that without needing to re-compile the engine?
Is there any way I can modify that delay parameter without needing to touch Godot's internals?

**Comment by naithar** [comment] 2020-10-05 09:34
No, you can't, for now you have to rebuild the engine. You can wait for Godot 3.2.4 beta or RC1 and migrate to it once it's out.

**Comment by Joseaay** [comment] 2020-10-05 09:54
Will do, thanks!

**Comment by fadexmusic** [comment] 2020-10-24 20:10
I get this problem as well, also don't have the experience to rebuild the engine. Any idea when the RC is gonna be released? I get an error when exporting to iOS from the 3.2.4 beta (AOT Compilation exited with code 134), but I need this issue fixed asap.

**Comment by naithar** [comment] 2020-10-24 20:12
> I get this problem as well, also don't have the experience to rebuild the engine. Any idea when the RC is gonna be released? I get an error when exporting to iOS from the 3.2.4 beta (AOT Compilation exited with code 134), but I need this issue fixed asap.

Are you using Mono build with C#?

**Comment by fadexmusic** [comment] 2020-10-24 20:43
Yes @naithar

**Comment by naithar** [comment] 2020-10-24 21:47
Well, the fix for this issue is merged and should be in beta, but I can't help you with Mono build.
I think you should make another issue for your case or find the one already addressing it. As far as I know Godot Mono for iOS sometimes have issues, so making a correct bug report could help contributors find and fix the problem.

**Comment by akien-mga** [comment] 2020-10-24 22:40
> Any idea when the RC is gonna be released? I get an error when exporting to iOS from the 3.2.4 beta (AOT Compilation exited with code 134), but I need this issue fixed asap.

A RC can't be released right after a beta which apparently doesn't work ;)

Please open an issue about this AOT compilation failure.

**Comment by yokai-shogun** [comment] 2021-02-26 20:24
I'm having this issue on 3.2.3-stable-release. I can't use v3.2.4 rc3 because I'm using a few plugins that may not be compatible with it. Game crashes if I use prebuilt versions of the plugins and some are not compiling for v3.2.4 rc3. I was trying to find the "ios-delay-in-settings" branch, but it's missing. Is there any way I can have access to it or at least the changes I need to make to add this feature? Thanks.

**Comment by naithar** [comment] 2021-02-26 21:59
The PR that's linked to this issue https://github.com/godotengine/godot/pull/42457 has the changes you need.

**Comment by BimDav** [comment] 2022-10-28 15:05
The problem is still present in 3.5.1, at least for systems that use InputDefault, such as TouchScreenButton. If I understand the current solution correctly, for short taps it will fire the presses at the same time (just before) the releases. So for something using InputDefault, action_press() will be called just before action_release(), and then Input.is_action_pressed() will always return false for presses shorter than 0.15s, which is very long.

**Comment by elinfame** [comment] 2024-08-25 19:50
Also confirming that this is still in issue in 3.5.3. Is there any path forward here or is this a hard platform limitation?

**Comment by elinfame** [comment] 2024-08-26 07:01
Nevermind, I set the input_devices/pointing/ios/touch_delay project setting to 0, and all works well! Out of curiosity, why have this setting at all, or at least, why not set it to 0 by default? Even using NSTimer to delay it by 0 seconds causes it to not be dispatched immediately, but rather, schedule it for the next run of the event queue (which is still in practice fast enough for the user not to notice, but still).

**Comment by Calinou** [comment] 2024-08-26 07:10
> Out of curiosity, why have this setting at all, or at least, why not set it to 0 by default

To my knowledge, the touch delay is in place so that double-taps can be recognized. Setting it to 0 by default would prevent double-taps from registering. Also, changing a default project setting's value would break compatibility with existing projects, so the change would have to be applied to newly created projects only by modifying the `project.godot` file written by the project manager.
