### ISSUE TITLE
screen drag and get global mouse position lag on android..other objects, collisions working really good.. no frame dropping... just case with screen drag or get global mouse position..

### ISSUE THREAD

**Issue by dahiyabunty1** [godotengine/godot#34503] opened 2019-12-21 06:19 UTC
**Godot version:**

**OS/device including version:**

**Issue description:**

**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by Calinou** [comment] 2019-12-21 22:56
Duplicate of #34480.

**Closed by Calinou** 2019-12-21 22:56 UTC
