### ISSUE TITLE
Google Play strict mode policy violation with Mono module using non-SDK ActivityThread

### ISSUE THREAD

**Issue by ksvslk** [godotengine/godot#42076] opened 2020-09-15 07:13 UTC
Google Play pre-launch report generates warnings about Android compatibility due to Android new updates:
https://developer.android.com/about/versions/11/non-sdk-11

Stack traces:

[stacktrace_gp1.txt](https://github.com/godotengine/godot/files/5223038/stacktrace_gp1.txt)
[stacktrace_gp2.txt](https://github.com/godotengine/godot/files/5223039/stacktrace_gp2.txt)
[stacktrace_gp3.txt](https://github.com/godotengine/godot/files/5223040/stacktrace_gp3.txt)

I had similar warnings about my IronSource Ads plugin but that might not be Godot related (hints to solve this still welcome).
[stacktrace_gp5.txt](https://github.com/godotengine/godot/files/5223044/stacktrace_gp5.txt)
[stacktrace_gp4.txt](https://github.com/godotengine/godot/files/5223045/stacktrace_gp4.txt)
[stacktrace_gp6.txt](https://github.com/godotengine/godot/files/5223043/stacktrace_gp6.txt)

Testing tools recommended by Google:
https://developer.android.com/distribute/best-practices/develop/restrictions-non-sdk-interfaces#test-for-non-sdk

**Godot version:**
3.2.3 RC5

**OS/device including version:**
Using Godot GLES2 mode.

**Steps to reproduce:**
Upload app to Google Play

**Comment by akien-mga** [comment] 2020-09-15 07:18
CC @godotengine/android

**Comment by m4gr3d** [comment] 2020-09-15 08:42
@akien-mga Looks like the issue is originating from the [mono codebase's use of the `ActivityThread` class](https://github.com/godotengine/godot/blob/3.2/modules/mono/mono_gd/support/android_support.cpp#L114).

**Comment by m4gr3d** [comment] 2020-09-15 08:42
cc @godotengine/mono

**Comment by akien-mga** [comment] 2021-11-08 09:03
Fixed by #54746.

**Closed by akien-mga** 2021-11-08 09:03 UTC
Labels: bug, platform:android, topic:porting, topic:mono
