### ISSUE TITLE
[3.4.2] editor_description overwrite is not being saved on Imported Scenes

### ISSUE THREAD

**Issue by kuhnchris** [godotengine/godot#57700] opened 2022-02-06 11:25 UTC
### Godot version

3.4.2.stable (arch)

### System information

Linux, Arch

### Issue description

The content of "editor_description" will not be saved after being overwritten. 
I.e. you split an object into a separate scene, import this scene as a child, overwrite the editor_description and other properties. The other properties are overwritten perfectly well and working as intended, but the editor_description will be reset as soon as you reopen the scene.

### Steps to reproduce

- Download the example.zip
- Open `RichTextLabel.tscn`
- See the `editor_description` and `text`t
- Open `Inner.tscn`
- Edit `editor_descrption` and `text`
- Save
- Close `Inner.tscn`
- Open `Inner.tscn`
- See that `text` stays overwritten but `editor_description` is reset to `RichTextLabel.tscn'`s content

https://user-images.githubusercontent.com/761911/152678554-329f638d-b7f0-4eb0-9b6e-78d5f63569f8.mp4

### Minimal reproduction project

[issue-editor_description.zip](https://github.com/godotengine/godot/files/8010033/issue-editor_description.zip)

**Comment by kuhnchris** [comment] 2022-02-06 11:27
Possibly a regression of #49708 ?

**Comment by Calinou** [comment] 2022-02-06 11:38
> Possibly a regression of https://github.com/godotengine/godot/pull/49708 ?

That PR was only merged in `master` and wasn't cherry-picked. Therefore, this can't be the reason for a regression in `3.x`.

**Comment by kuhnchris** [comment] 2022-02-06 11:51
Then maybe it's just possible that this "fix" is missing in 3.x? I do see lots of references to get_meta and set_meta in 3.x in node.cpp, so this probabbly seems possible. Any reason it wasn
t cherry-picked?

**Comment by KoBeWi** [comment] 2022-02-06 11:56
This has the same cause as #12838
Editor description is stored in meta, so it doesn't work for instanced scenes. It was changed to a property in 4.0, but it can't be backported, because it breaks compatibility.

**Closed by KoBeWi** 2022-02-06 11:56 UTC
Labels: bug, topic:editor

**Comment by kuhnchris** [comment] 2022-02-06 13:50
Okay. I'll leave a workaround here for the future, in case someone (like me) needs this for their project: (basically I just use normal properties and set the editor_description when ready. yes i could have also solved that differently or by using a custom property or tag everywhere, but I'm lazy like that.)

``` 
export var windowTitle: String = "<Replace me please>" setget _sg_windowTitle
export var target: String = "bg_boxOverlay"
export var targetProperty: String = "editor_description"

func _sg_windowTitle(newVal: String) -> void:
	windowTitle = newVal
	_findTarget(self)

func _findTarget(node: Node) -> void:
	if node.name == target:
		if targetProperty in node:
			print("property '",targetProperty,"' in node '",node.name,"'")
			node[targetProperty] = windowTitle
	else:
		for n in node.get_children():
			_findTarget(n)

func _ready() -> void:
	_findTarget(self)
```
