### ISSUE TITLE
2DRigidbody weird physics on sliding

### ISSUE THREAD

**Issue by NullNeska** [godotengine/godot#12496] opened 2017-10-29 23:27 UTC
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Windows 10, Godot 3.0 custom build 0c043bc

**Issue description:**
RigidBody2D got stuck where it shouldn't 

**Steps to reproduce:**
create a tile map, make a line of colliable tiles, create a rigidbody2D, slide it across the tiles

**Link to minimal example project:**
![fixedregularharborporpoise-size_restricted](https://user-images.githubusercontent.com/6185415/32149714-1f3f7e02-bcdf-11e7-81dc-f3218c255cea.gif)

**Comment by reduz** [comment] 2017-10-29 23:38
I have no idea what you are trying to do, but it's probably not how a rigid
body is intended to be used.
Can you post source code?

**Comment by NullNeska** [comment] 2017-10-29 23:40
```extends RigidBody2D



func _ready():
	pass

func _physics_process(delta):
	if Input.is_key_pressed(KEY_D):
		linear_velocity.x += 500 * delta
	if Input.is_key_pressed(KEY_A):
		linear_velocity.x -= 500 * delta
	```

**Comment by Dillybob92** [comment] 2017-10-29 23:47
Can you post your project example? Your collision shape bodies are not scaled, are they?

**Comment by NullNeska** [comment] 2017-10-29 23:48
[CaveExplorer.zip](https://github.com/godotengine/godot/files/1425607/CaveExplorer.zip)

**Comment by reduz** [comment] 2017-10-29 23:52
try using the _integrate_forces callback to manipulate velocity

**Comment by NullNeska** [comment] 2017-10-29 23:54
still getting stuck with
```
func _integrate_forces(state):
	if Input.is_key_pressed(KEY_D):
		linear_velocity.x += 5
	if Input.is_key_pressed(KEY_A):
		linear_velocity.x -= 5

**Comment by reduz** [comment] 2017-10-29 23:59
use state argument to change linear velocity

**Comment by NullNeska** [comment] 2017-10-30 00:02
It is getting stuck less with this, but still happens.
```func _integrate_forces(state):
	var lin = state.get_linear_velocity()
	if Input.is_key_pressed(KEY_D):
		lin.x += 5
	if Input.is_key_pressed(KEY_A):
		lin.x -= 5
	linear_velocity = lin

**Comment by NullNeska** [comment] 2017-10-30 00:04
could it be because the tiles are all separate collision shapes? i had a issue earlier with a kinematic2D not fitting in a hole even though the collisions shapes were just sliding and not actually colliding.

**Comment by NullNeska** [comment] 2017-10-30 09:40
![workaround](https://user-images.githubusercontent.com/6185415/32164083-c773dd66-bd34-11e7-9854-116c91d425f8.png)
this is a workaround i got working. instead of having the box slide across, i put some raycasts under 1 pixel to use instead.

**Comment by Dillybob92** [comment] 2017-10-30 10:02
@NullNeska 

If you used 1 long collision rectangle shape, this doesn't happen right?

**Comment by eon-s** [comment] 2017-11-01 00:52
Is normal to get stuck in the impossible gap between tiles using rigid bodies (in some engines even happens with capsule shapes).

If you want to use rigid bodies that way, you can try with a polygon with rounded corners (may fail too) or a circle/capsule like the platformer demo, leave the rectangle in a children-body for other purposes (like hitbox).

**Comment by mhilbrunner** [comment] 2018-04-10 16:02
First of all thank you for your report and sorry for the delay.

We released Godot 3.0 in January 2018 after 18 months of work, fixing many old issues either directly, or by obsoleting/replacing the features they were referring to.

We still have hundreds of issues whose relevance/reproducibility needs to be checked against the [current stable version](https://godotengine.org/download), and that's where you can help us.
**Could you check if the issue that you described initially is still relevant/reproducible in Godot 3.0 or any newer version, and comment about it here?**

For bug reports, please also make sure that the issue contains detailed steps to reproduce the bug and, if possible, a zipped project that can be used to reproduce it right away. This greatly speeds up debugging and bugfixing tasks for our contributors.

Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

Thanks in advance.

*Note: This message is being copy-pasted to many "stale" issues (90+ days without activity). It might happen that it is not meaningful for this specific issue or appears oblivious of the issue's context, if so please comment to notify the Bugsquad about it.*

**Comment by akien-mga** [comment] 2018-05-29 08:36
> Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

As there was no update since the previous post, we close this issue.

If it is still relevant in the way it was described and discussed above, please comment to ask for it to be reevaluated. If it is only partly relevant/the original issue has changed, it would be better to open a new issue (potentially referring to this one) focused on the current state.

**Closed by akien-mga** 2018-05-29 08:36 UTC
Labels: enhancement, topic:physics, usability

**Comment by mcardellg** [comment] 2019-07-05 13:13
Found this when looking for a solution to an identical problem.
I created my own work around which is to join up the collision shapes for tilemaps where they are adjacent, I posted about it [here](https://godotforums.org/discussion/20853/small-code-snippet-for-optimising-tilemap-collisions#latest).
Hope this helps anyone else who lands here looking for a solution.
