### ISSUE TITLE
Artifacting when blurring a SCREEN_TEXTURE with textureLod on the mobile renderer.

### ISSUE THREAD

**Issue by Felipe-Sena** [godotengine/godot#91474] opened 2024-05-02 18:35 UTC
### Tested versions

- Reproducible in: 4.3.dev6 [89850d553], 4.2.2-stable and 4.2.stable

### System information

Godot v4.2.2.stable - Windows 10.0.22631 - Vulkan (Mobile) - dedicated NVIDIA GeForce RTX 4070 (NVIDIA; 31.0.15.5222) - AMD Ryzen 9 7900X 12-Core Processor (24 Threads)

### Issue description

Whenever a shader that reads from `hint_screen_texture` is blurred with a `textureLod` in the Vulkan Mobile renderer an artifact appears in the upper part of the image. Using `SCREEN_UV` or `UV` does not affect the outcome. This does **not** happen with regular textures blurred with `textureLod` that use any of the two `UV` methods described above.

On the mobile renderer you can clearly see the artifact:
![artifact](https://github.com/godotengine/godot/assets/93457186/60a9f629-d042-481b-8a8b-72030ecbe298)

This issue disappears once I switch to the Forward+ renderer:
![no_artifact](https://github.com/godotengine/godot/assets/93457186/87523fe7-0136-4fc2-9d04-018e4db1a3d8)

### Steps to reproduce

Create a new project with the Mobile renderer and then create a spatial shader that contains the following lines:
```gdscript
shader_type spatial;

uniform sampler2D screen_texture : hint_screen_texture, filter_linear_mipmap;


void fragment() {
	ALBEDO = textureLod(screen_texture, SCREEN_UV, 1).rgb;
}
```

And then apply it to a `ShaderMaterial`.

### Minimal reproduction project (MRP)

[MRP.zip](https://github.com/godotengine/godot/files/15192542/MRP.zip)

**Comment by clayjohn** [comment] 2024-05-02 19:18
This appears to be a duplicate of https://github.com/godotengine/godot/issues/88786. 

We like to reduce duplicate bug reports and track the bug in one place. So I am going to close this report in favour of https://github.com/godotengine/godot/issues/88786

**Closed by clayjohn** 2024-05-02 19:18 UTC
