### ISSUE TITLE
4.0.2: GLTF import, bones doubled

### ISSUE THREAD

**Issue by MikeFrom** [godotengine/godot#76039] opened 2023-04-13 18:56 UTC
### Godot version

4.0.2

### System information

Windows 10

### Issue description

When I import my gltf file, bones get doubled:
<img width="1253" alt="Godot_4_0_2_gltf_import_bones_doubled" src="https://user-images.githubusercontent.com/50963378/231855955-ec7ba5f2-bb86-4dbf-b690-0bd4d0f3e8bf.png">

In Godot 3.5.1 this works, as expected:
<img width="1306" alt="Godot_3_5_1_gltf_import_bones_only_once_OK" src="https://user-images.githubusercontent.com/50963378/231856134-e3f85ed2-3830-432b-95f4-0900828ce3d8.png">

Is there a setting to prevent doubled bones? Thanks

### Steps to reproduce

Import this GLTF file:
[bumper_rotate.zip](https://github.com/godotengine/godot/files/11225618/bumper_rotate.zip)

### Minimal reproduction project

-

**Comment by clayjohn** [comment] 2023-04-13 19:04
CC @lyuma @TokageItLab

**Comment by smix8** [comment] 2023-04-13 19:48
Godot 4 compared to Godot 3 creates redundant bones for every parented object in Blender.
Since you seem to have 3 parented meshes you end up with 3 new bones all named after your mesh objects.

Related to https://github.com/godotengine/godot/issues/75917.

**Comment by MikeFrom** [comment] 2023-07-08 18:46
Tested today in Godot 4.1.0, I still get double bones. Or have I missed something to avoid doubles? Thanks

**Comment by akien-mga** [comment] 2023-07-08 19:23
- Duplicate of #75917

**Closed by akien-mga** 2023-07-08 19:23 UTC
Labels: bug, topic:import, topic:animation
