### ISSUE TITLE
Godot 4 Beta AnimatedTexture Tilemap does not working 

### ISSUE THREAD

**Issue by HamidKazemzadeh** [godotengine/godot#66563] opened 2022-09-28 18:37 UTC
### Godot version

4 Beta

### System information

Windows 11

### Issue description

I have created Tilemap by animated texture and create a small map but animated tilemap does not working

### Steps to reproduce

No code

### Minimal reproduction project

Need password to upload

**Comment by KoBeWi** [comment] 2022-09-28 20:54
Tile animations are done differently in Godot 4, you can see here for details: #52539
Not sure if any tutorial exists yet.

**Comment by HamidKazemzadeh** [comment] 2022-09-29 06:16
Thank you for your answer, I have tried to achieve that by sprite sheet and animation texture but could not do that. do you know what kind of object should be use to drag and drop into tileset ?!

**Comment by KoBeWi** [comment] 2022-09-29 10:44
Animations are created with spritesheets. You specify number of columns, separation and then add frames and it happens automatically. Here's a short video guide:

https://user-images.githubusercontent.com/2223172/193011163-7faf7964-fcf4-4573-9d48-f8ac95389b54.mp4

**Comment by HamidKazemzadeh** [comment] 2022-09-29 12:16
Thanks a lot it works perfect :))

**Comment by HamidKazemzadeh** [comment] 2022-09-29 12:22
Btw when creating a res as animated texture dosn't work anymore ?! if not what is the use case of it? Im new to Godot thats why I am asking this question

**Comment by KoBeWi** [comment] 2022-09-29 12:33
Yes, AnimatedTexture is no longer supported in TileMaps. The old workflow was that you'd assign an AnimatedTexture for each tile separately, so it required lots of setup to get your TileMap animated. The new workflow is much easier, because you can add animation for all tiles at once.

Closing, as this is intended behavior.

**Closed by KoBeWi** 2022-09-29 12:33 UTC
Labels: archived
