### ISSUE TITLE
Cannot Load Saved Materials

### ISSUE THREAD

**Issue by cybereality** [godotengine/godot#66700] opened 2022-10-01 11:27 UTC
### Godot version

v4.0.beta2.official [f8745f2f7]

### System information

Ubuntu 22.04, AMD RX 6800 XT

### Issue description

I can create a material (either standard or ORM) on a mesh. However, if I save this, I cannot load it anywhere else, even on the same mesh. It gives an error: "The selected resource (StandardMaterial3D) does not match any type expected for this property (BaseMaterial3D, ShaderMaterial)". This is a new project, with nothing else but a cube.

![Godot_Beta_2_Material_Error](https://user-images.githubusercontent.com/3398643/193407281-d39d8e49-4e46-49dc-be84-ee5641f19c49.jpg)

### Steps to reproduce

Create a MeshInsance. 
Give it a material (standard or orm). It can be on the mesh or the override.
Save the material.
Click on the material drop-down and choose load or quick load.
Choose the same material.
Watch the error.

### Minimal reproduction project

[MaterialBug.zip](https://github.com/godotengine/godot/files/9690147/MaterialBug.zip)

**Comment by manueldun** [comment] 2022-10-01 14:12
Does this count for hacktoberfest? If it does i am going to give this a try

**Comment by Calinou** [comment] 2022-10-01 15:53
> Does this count for hacktoberfest? If it does i am going to give this a try

Yes, any issue counts.

**Comment by Zylann** [comment] 2022-10-01 16:12
I had an existing scene containing various mesh instances with a `StandardMaterial3D` assigned to them. Some of them inexplicably lost that material, and I can't assign it back because of this error. Despite that, some mesh instances still has the material assigned just fine.

**Comment by Calinou** [comment] 2022-10-01 22:13
If you can [compile the engine from source](https://docs.godotengine.org/en/stable/development/compiling/index.html), you could look into [bisecting the regression](https://docs.godotengine.org/en/stable/community/contributing/bisecting_regressions.html) to greatly speed up troubleshooting.

**Comment by manueldun** [comment] 2022-10-02 01:09
> If you can [compile the engine from source](https://docs.godotengine.org/en/stable/development/compiling/index.html), you could look into [bisecting the regression](https://docs.godotengine.org/en/stable/community/contributing/bisecting_regressions.html) to greatly speed up troubleshooting.
> 
> Assuming this issue doesn't occur in 4.0.beta1:
> 
> * 4.0.beta1's commit hash (`good`) is [4ba934b](https://github.com/godotengine/godot/commit/4ba934bf3d1e697d8f332b5e8cfd694cdf49a7ba).
> * 4.0.beta2's commit hash (`bad`) is [f8745f2](https://github.com/godotengine/godot/commit/f8745f2f71c79972df66f17a3da75f6e328bc55d).

I will start bisecting tomorrow morning to get an idea of how it should be fixed. I just found the code where it shows the warning. Thanks.

**Comment by fracteed** [comment] 2022-10-02 04:35
Just wanted to confirm that I also have this issue in beta2, that didn't exist in beta1. Meshes that already had materials are fine and the material can be edited, but another material can no longer be applied.

**Comment by clayjohn** [comment] 2022-10-03 01:39
For posterity, this bug was introduced by https://github.com/godotengine/godot/pull/62413 and will be closed by #66795

**Closed** 2022-10-03 07:33 UTC
Labels: bug, topic:editor, confirmed, regression, topic:3d
