### ISSUE TITLE
Project List (bug)

### ISSUE THREAD

**Issue by ret80** [godotengine/godot#4552] opened 2016-05-05 10:30 UTC
**Operating system or device:**
godot 2.0.2 windows

**Issue description** (what happened, and what was expected):

**Steps to reproduce:**
1 Open any project.
2 Run it.
3 Return the menu to the list of projects.
The window will be the way was a window running the project. And if it was small, and the project list window is too small.

**Link to minimal example project** (optional but very welcome):

**Comment by neikeq** [comment] 2016-05-05 10:47
Duplicate of #4045

**Closed by neikeq** 2016-05-05 10:47 UTC
