### ISSUE TITLE
Scene window not visible when playing project

### ISSUE THREAD

**Issue by srodrigo** [godotengine/godot#25909] opened 2019-02-15 15:55 UTC
**Godot version:**
3.0.6

**OS/device including version:**
Windows 10

Nvidia GeForce GTX 1050 Ti, latest drivers installed (418.91), although I just updated them, same problem with the previous ones.

**Issue description:**
When playing the scene, the new window is not visible.

The only way to see it is go to the taskbar, click on Godot, right click on the scene window, and select Maximise (which BTW appears really small).

**Steps to reproduce:**
This problem only happens when Godot is on an external screen 1920x1200. This is the output when playing the scene:
`running cmdline: "C:\Path_to_godot\Godot_v3.0.6-stable_win64.exe\Godot_v3.0.6-stable_win64.exe" "--path" "Path_to_project" "--remote-debug" "127.0.0.1:6007" "--allow_focus_steal_pid" "5760" "--position" "-3360,1570"`

Notice the -3360, which I imagine is the problem.

The main screen is 3840x2160, if playing the screen from there, the behaviour is correct.

**Minimal reproduction project:**
Just a new project with a Node object and a material.

**Comment by akien-mga** [comment] 2019-02-15 17:14
Doesn't the window show on your main screen then?

**Comment by srodrigo** [comment] 2019-02-15 17:57
@akien-mga No, it doesn't. As I explained above, it doesn't show at all when Godot is on the external screen.

> The only way to see it is go to the taskbar, click on Godot, right click on the scene window, and select Maximise

Everything is fine when Godot is on the main screen.

**Comment by akien-mga** [comment] 2020-06-22 12:59
Can you still reproduce this bug in Godot 3.2.1 or any later release (e.g. [3.2.2-rc2](https://godotengine.org/article/release-candidate-godot-3-2-2-rc-2))?

**Comment by vailton720** [comment] 2020-10-13 22:16
how did you solve the problem?
i have the same problem.

**Comment by Calinou** [comment] 2020-10-14 12:23
Duplicate of https://github.com/godotengine/godot/issues/40733 and possibly others. Try enabling **Allow Hidpi** in the Project Settings.

**Closed by Calinou** 2020-10-14 12:23 UTC
Labels: bug, platform:windows, topic:editor
