### ISSUE TITLE
Delay in movement controls

### ISSUE THREAD

**Issue by ck-linuxx** [godotengine/godot#49256] opened 2021-06-02 14:59 UTC
First sorry if something's wrong, it's the translation's fault.

In version 3.3.2 of godot, it has a delay in the controls, when I press right it takes a few milliseconds to obey my command. I have a backup of version 3.2.2 of godot, this version doesn't have this delay.

**Comment by Calinou** [comment] 2021-06-02 16:29
@ck-linuxx Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

**Comment by CritCorsac** [comment] 2021-07-24 10:14
I am also having this issue. There's always been some input delay when using V-Sync, as would be expected, but the amount of delay seems to have increased sometime around 3.3. Disabling V-Sync noticeably decreases the amount of input lag.

I think this might be related to #48369 as there's an ongoing discussion about input delay there.

**Comment by Calinou** [comment] 2021-07-24 10:34
> I think this might be related to #48369 as there's an ongoing discussion about input delay there.

Which operating system are you using?

**Comment by CritCorsac** [comment] 2021-07-27 00:05
> > I think this might be related to #48369 as there's an ongoing discussion about input delay there.
> 
> Which operating system are you using?

I'm running Linux at the moment. Sorry for the late reply.

**Comment by Calinou** [comment] 2021-07-27 11:47
Duplicate of https://github.com/godotengine/godot/issues/48369#.

**Closed by Calinou** 2021-07-27 11:47 UTC
Labels: bug, confirmed, needs testing, topic:input
