### ISSUE TITLE
CTRL+CLICK to jump to documentation is not working under certain conditions

### ISSUE THREAD

**Issue by azul372** [godotengine/godot#57473] opened 2022-01-31 02:57 UTC
### Godot version

3.4.2 stable

### System information

Windows 10, GLES3,  NVIDIA Quadro P2000

### Issue description

Ctrl + click on a built-in method name should display its script documentation, right? But I found that for some methods and under certain conditions, it doesn't show up. For example:
```
if OS.get_ticks_msec() % 5 == 0:
	print_debug("test")
```
In this code, if you Ctrl + Click OS.get_ticks_msec(), it doesn't display the documentation. But if you write like
```var foo = OS.get_ticks_msec()```
and do the same action, it does work. The former code itself completely works and doesn't show any error, so basically the only problem is the inexplicable missing link to documentation. The same issue also occurs in some other codes, such as:
```
if OS.get_audio_driver_count() > 1:
	pass
```
At first I thought the if block is the cause, but then I found out that some methods in if-statement have no problems with showing documentation by ctrl+click. For instance, the code below jumps to SceneTree documentation with ease.
```
if get_tree().get_node_count() > 5:
	print("test")
```

I haven't tried on many codes, so maybe it only happens with `OS.`, or maybe not. In any case, I think it would be good to fix.

### Steps to reproduce

The fastest way I guess is to write a script like this
```
extends Node

# Called when the node enters the scene tree for the first time.
func _ready() -> void:
	if get_tree().get_node_count() > 0:
		print("code works, link to documentation works")
	if OS.get_audio_driver_count() > 0:
		print("code works, link to documentation doesn't work")
	pass
```
And try to Ctrl + Click on `get_node_count()` and `get_audio_driver_count()` to check if it jumps to documentation.

**Comment by KoBeWi** [comment] 2022-01-31 03:00
Duplicate of #26114
This is resolved in 4.0

**Closed by KoBeWi** 2022-01-31 03:00 UTC
