### ISSUE TITLE
Trying to drag the edge of the FileDialog while it is not focused will lock the input ingame

### ISSUE THREAD

**Issue by marzecdawid** [godotengine/godot#68606] opened 2022-11-13 12:47 UTC
### Godot version

4.0.beta4

### System information

Windows 10 21H2, Vulkan, AMD Radeon RX 6750 XT (31.0.12029.1042)

### Issue description

If the FileDialog is not 'focused' and you try to drag its edge to resize it then it will lock the input for your game with errors spam:

https://user-images.githubusercontent.com/23726629/201522123-ca9e29be-00b0-45eb-96a0-566ff09497a9.mp4

### Steps to reproduce

1. Open reproduction project
2. Run the scene
3. Click outside of the FileDialog window
4. Try to drag the edge of the FileDialog when it is not focused

### Minimal reproduction project

[FreezeTest.zip](https://github.com/godotengine/godot/files/9997203/FreezeTest.zip)

**Comment by Rindbee** [comment] 2022-11-14 12:25
Related to #62194.

**Comment by Sauermann** [comment] 2022-11-14 13:45
I would consider this issue a duplicate of #62194.

**Comment by Sauermann** [comment] 2022-11-14 15:56
Can be closed as fixed by #68272

**Closed** 2022-11-14 16:05 UTC
