### ISSUE TITLE
Collision Layer Mask does't work the right way.

### ISSUE THREAD

**Issue by andykenobi** [godotengine/godot#47399] opened 2021-03-26 20:23 UTC
**Godot version:**
3.2

**OS/device including version:**
Windows 10

**Issue description:**
What is happening, I want to make object A collide with B, but just Object A receive the signal.

I set this:
> Object A
 > Layer0
 > Maks1

> Object B
 > Layer 1
 (no mask)

But when Object A collide with Object B, the signal "area_entered" is emited for the two objects. I think it's not correct.

I think the correct way to execute is:
If Object A collide with B, just trigger the signal "area_entered" on Object A, becouse B has no mask or has no Object A Layer in mask.

**Steps to reproduce:**
Just create 2 Objects and put layers and mask like above, put any script, but connect "area_entered" on both. Then make one object move in direction to the other. Bang... will emit signal on two objects.

**Minimal reproduction project:**
[collision_mask_test.zip](https://github.com/godotengine/godot/files/6214192/collision_mask_test.zip)

**Comment by Calinou** [comment] 2021-03-26 21:13
> What is happening, I want to make object A collide with B, but B not collide with A.

How is that supposed to work in practice? If one object collides with another, then the other object must collide with it by design. I don't see how else it could work.

**Comment by andykenobi** [comment] 2021-03-27 00:20
I say, about the script... Real World Example:
If i walk and hit someone, i say: sorry, but the other guy don't say nothing.
If someone hit me, i say nothing, but he says: sorry.

Got it?

**Comment by andykenobi** [comment] 2021-03-27 00:49
One example in game:
> Player
> Layer 0
> (no Mask)

> Bullet
> Layer 1
> Mask 0

When bullet hit player, just emit signal for "Bullet" not "Player" becouse player does't set mask. Got it?

**Comment by floppyhammer** [comment] 2021-03-27 01:31
@andykenobi Your real world example would more fit into a detection scenario instead of a collision one. For a collision one, it doesn't matter who bumps into who as the result is always some interaction forces generated between them that makes the moving side stop. Collision is always mutual just like interaction forces in real world. When deciding which side should apologize, detection nodes like `Area` might come in handy.

**Comment by madmiraal** [comment] 2021-03-27 11:49
Duplicate of #7644, which is fixed with #42268 and it's 3.x version #42269.

**Closed by madmiraal** 2021-03-27 11:49 UTC
Labels: topic:physics
