### ISSUE TITLE
Error when saving inherited scene from GLB asset

### ISSUE THREAD

**Issue by wkirby** [godotengine/godot#72059] opened 2023-01-25 17:09 UTC
### Godot version

v4.0.beta15.mono.official [4fa6edc88]

### System information

macOS 13.1 (22C65), M1 Max

### Issue description

Creating a new inherited scene from a GLB file results in error message "Requested file format unknown: glb". This error did not occur on Beta 14.

### Steps to reproduce

1. Start a new project
2. Add `tile_tree.glb` (attached as a `.zip` below) to the file system
3. Right click and click "New Inherited Scene"
4. Attempt to save
5. Observe error message

* GLB Asset (sourced from Kenney assets): [tile_tree.glb.zip](https://github.com/godotengine/godot/files/10501687/tile_tree.glb.zip)
* Screen recording: https://user-images.githubusercontent.com/579688/214631733-9e63116d-5e84-4417-89c8-12f7cb2978a5.mov

### Minimal reproduction project

[GLBTest.zip](https://github.com/godotengine/godot/files/10501703/GLBTest.zip)

**Comment by Zireael07** [comment] 2023-01-25 18:11
I suppose this is a dupe of already fixed #72003

**Closed** 2023-01-25 18:23 UTC
