### ISSUE TITLE
Dynamic lighting missing/broken on some meshes

### ISSUE THREAD

**Issue by jamie-pate** [godotengine/godot#21587] opened 2018-08-30 01:12 UTC
**Godot version:**

3.0.6.stable.custom_build (compiled from "https://github.com/godotengine/godot/archive/3.0.6-stable.tar.gz")

**OS/device including version:**

OpenGL ES 3.0 Renderer: Radeon RX 560 Series (POLARIS11, DRM 3.26.0, 4.18.5-arch1-1-ARCH, LLVM 6.0.1)
(confirmed on other machines)

**Issue description:**

Lighting does not work for certain meshes.
Adding a UV2 map allows baked lightmaps but not dynamic.

Disabling the normal map OR enabling Triplanar UV2 both seem to fix the problem.

![dynamic_light_mesh_problem](https://user-images.githubusercontent.com/682658/44823708-dc1bb100-abb6-11e8-8996-023a1c78aad7.png)

I also noticed the widgets won't draw over the affected objects
![widget_lost](https://user-images.githubusercontent.com/682658/44823709-dc1bb100-abb6-11e8-8448-68504ed7c703.png)

**Steps to reproduce:**
Run attached scene. Meshes are baked into the scene, exported from Maya dae

**Minimal reproduction project:**

[couchbug.zip](https://github.com/godotengine/godot/files/2334266/couchbug.zip)

**Comment by Ace-Dragon** [comment] 2018-08-30 18:06
A few things to check 

-When exporting, make sure the _generate tangents_ checkbox is ticked, I would also make sure the _triangulate_ checkbox is also ticked.
-Normal maps don't work if they are in imported as Srgb, if that is the case then you need to change the color space and re-import them.

**Comment by jamie-pate** [comment] 2018-09-07 21:46
Srgb was 'detect' but disabling it did not change the outcome.

Exporting from maya as `obj` instead of `dae` seems to fix the problem also. (not sure what settings the artist is using)

**Comment by glaforte** [comment] 2018-11-23 13:08
I reproduced the problem in Godot 3.0.6.
I also reproduced the problem identically in Godot 3.1 alpha 2 / master.
As noted by the reporter, this seems to be an incompatibility between Baked Light-maps, Normal Maps and the UV2 channel.

**Comment by glaforte** [comment] 2018-11-23 15:04
There are two issues with the 'LongSofa' meshes:
1) Their UV2 has not been exported nor generated. The Godot Editor can generate one for you (screenshot below) or your 3D artist can generate it a DCC Tool.
![image](https://user-images.githubusercontent.com/2227491/48949356-b2e49580-ef05-11e8-836a-712b74e6c3ef.png)

2) The Tangent and Binormal vertex streams were not imported nor generated, during the COLLADA import in the Godot Editor. This is definitely an issue that I would like to investigate, since it seems to work fine in other cases. @jamie-pate Could you please provide me with the original COLLADA file and/or the Blender file for the 'LongSofa' mesh? Thanks :)

**Comment by KoBeWi** [comment] 2020-06-25 20:24
Still reproducible in 3.2.2 rc2
Although the above comment remains unanswered...

Also here's this scene in 23f7f86 heh
![image](https://user-images.githubusercontent.com/2223172/85791702-8ffa1300-b732-11ea-9704-19893f345b74.png)

**Comment by akien-mga** [comment] 2021-04-28 11:28
Fixed by #44628.

**Closed by akien-mga** 2021-04-28 11:28 UTC
Labels: bug, confirmed, topic:import
