### ISSUE TITLE
The whole editor quits if you double click a dialog window's close button

### ISSUE THREAD

**Issue by cdemirer** [godotengine/godot#55862] opened 2021-12-12 12:50 UTC
### Godot version

4.0.dev (092a28612)

### System information

5.15.2-2-MANJARO (KDE if that matters for this issue)

### Issue description

If you double click on a dialog window's close button (the one offered by the WM), the editor quits.

This is only easily reproduced via the Editor Settings dialog, since it takes a while to close after clicking the window manager's close ("X") button (but not if you click the button named "Close" at the bottom of the Editor Settings dialog), giving enough time for double clicking.

I have confirmed that this line is executed as a result: 
https://github.com/godotengine/godot/blob/bdf8340e5993ec3f86e4bf1d5ede48df7d023a12/editor/editor_node.cpp#L677-L678

So the second request to close the dialog somehow makes its way into the editor node, closing the whole editor.

**Note:** This is not related to any alignment with the main editor window's close button. It happens regardless of the positioning of the dialog window.

### Steps to reproduce

Double click instead of single clicking on the *window manager's* close button ("X") for the Editor Settings dialog.

### Minimal reproduction project

Happens with any project

**Comment by KoBeWi** [comment] 2021-12-12 14:12
Can't reproduce it on Windows 10.

**Comment by Rubonnek** [comment] 2021-12-12 14:43
I'm able reproduce it in Arch Linux somewhat consistently. It crashes sometimes with a segmentation fault.

Here's the backtrace:

```
#0  0x00007ffff7d12424 in pthread_mutex_lock () from /usr/lib/libpthread.so.0
#1  0x000055555592c69b in __gthread_mutex_lock (__mutex=0x190) at /usr/include/c++/11.1.0/x86_64-pc-linux-gnu/bits/gthr-default.h:749
#2  0x000055555592c71a in __gthread_recursive_mutex_lock (__mutex=0x190) at /usr/include/c++/11.1.0/x86_64-pc-linux-gnu/bits/gthr-default.h:811
#3  0x000055555592c856 in std::recursive_mutex::lock (this=0x190) at /usr/include/c++/11.1.0/mutex:108
#4  0x000055555951112c in MutexImpl<std::recursive_mutex>::lock (this=0x190) at ./core/os/mutex.h:47
#5  MutexLock<MutexImpl<std::recursive_mutex> >::MutexLock (p_mutex=..., this=<optimized out>) at ./core/os/mutex.h:66
#6  SceneTree::queue_delete (this=0x40, p_object=0x55557128b840) at scene/main/scene_tree.cpp:1037
#7  0x00005555594cf67b in Node::queue_delete (this=0x55557128b840) at scene/main/node.cpp:2549
#8  0x000055555954709f in Viewport::_gui_cancel_tooltip (this=0x555564cabe00) at scene/main/viewport.cpp:1131
#9  0x0000555559541d35 in Viewport::_notification (this=0x555564cabe00, p_what=11) at scene/main/viewport.cpp:442
#10 0x000055555610bed7 in Viewport::_notificationv (this=0x555564cabe00, p_notification=11, p_reversed=true) at ./scene/main/viewport.h:89
#11 0x000055555610c810 in Window::_notificationv (this=0x555564cabe00, p_notification=11, p_reversed=true) at ./scene/main/window.h:42
#12 0x000055555610d180 in AcceptDialog::_notificationv (this=0x555564cabe00, p_notification=11, p_reversed=true) at ./scene/gui/dialogs.h:45
#13 0x00005555581f94f9 in EditorSettingsDialog::_notificationv (this=0x555564cabe00, p_notification=11, p_reversed=true) at editor/settings_config_dialog.h:44
#14 0x000055555ca16351 in Object::notification (this=0x555564cabe00, p_notification=11, p_reversed=true) at core/object/object.cpp:846
#15 0x00005555594b6331 in Node::_propagate_exit_tree (this=0x555564cabe00) at scene/main/node.cpp:266
#16 0x00005555594b5d13 in Node::_propagate_exit_tree (this=0x555564db6a60) at scene/main/node.cpp:257
#17 0x00005555594b5d13 in Node::_propagate_exit_tree (this=0x555564ac42d0) at scene/main/node.cpp:257
#18 0x00005555594b5d13 in Node::_propagate_exit_tree (this=0x5555632542c0) at scene/main/node.cpp:257
#19 0x00005555594b5d13 in Node::_propagate_exit_tree (this=0x5555630a6460) at scene/main/node.cpp:257
#20 0x00005555594cec0c in Node::_set_tree (this=0x5555630a6460, p_tree=0x0) at scene/main/node.cpp:2487
#21 0x000055555950d546 in SceneTree::finalize (this=0x555562f42950) at scene/main/scene_tree.cpp:567
#22 0x0000555555925b37 in OS_LinuxBSD::run (this=0x7fffffffdb80) at platform/linuxbsd/os_linuxbsd.cpp:347
#23 0x000055555592184d in main (argc=2, argv=0x7fffffffe088) at platform/linuxbsd/godot_linuxbsd.cpp:58
```


Here's [full backtrace](https://github.com/godotengine/godot/files/7698922/full_backtrace.txt).

**Comment by cdemirer** [comment] 2021-12-12 14:53
Interesting. I just noticed "crash" label was added after my initial comment (which apparently can happen per @Rubonnek's comment). To clarify my case: It never crashes for me, and always does what the actual close ("X") button of the main editor window would do. For example, it asks to save if I have unsaved changes in a scene etc.

**Comment by Calinou** [comment] 2021-12-12 15:06
I remember seeing this issue reported already, but I can't find it right now.

**Comment by cdemirer** [comment] 2021-12-12 15:17
Oh, found it #49977

**Comment by Rubonnek** [comment] 2021-12-12 15:26
Closing as duplicate of #49977.

**Closed by Rubonnek** 2021-12-12 15:26 UTC
Labels: bug, platform:linuxbsd, topic:porting, confirmed, crash
