### ISSUE TITLE
Input not handling joystick axis

### ISSUE THREAD

**Issue by henriiquecampos** [godotengine/godot#11465] opened 2017-09-21 18:12 UTC
Windows 10, Godot pre-alpha 3.0

**Issue description:**
Input singleton not handling axis related events, at least not on my Xbox360 controller

**Steps to reproduce:**
Create a simple Input Handler
Add any axis related event
Try
```GDScript
func _fixed_process(delta):
	if Input.is_action_pressed("game_up"):
		print("up")
```

**Comment by Hinsbart** [comment] 2017-09-24 11:12
Mhh, probably a duplicate of #10391 which has been fixed already. What does `pre-alpha 3.0` mean exactly? I can reproduce this with alpha1 but not with the latest master (on Linux).
I currently don't have access to a windows machine to test this, so if you're using an older version, could you try it again with an up-to-date version please?

**Comment by Hinsbart** [comment] 2017-09-27 15:40
This has just been tested by @AndreaCatania on windows and it's working apparently, so closing for now.

**Closed by Hinsbart** 2017-09-27 15:40 UTC
Labels: archived
