### ISSUE TITLE
Sky shaders do not correctly respect 'use in sky only' property

### ISSUE THREAD

**Issue by Ophiolith** [godotengine/godot#58206] opened 2022-02-16 21:05 UTC
### Godot version

4.0 alpha 2

### System information

WIndows 10, Nvidia GTX 1070, Vulkan renderer

### Issue description

When using a sky shader that only uses light0, If there is more than one DirectionalLight3D node in a scene, and one has the 'use in sky only' property enabled, the shader will disinherit that light, and assign the next light in the scene that does _not_ have that property enabled as light0. This would seem like correct behaviour, as typically sky and scene lighting should be matched, but as I've detailed [here](https://github.com/godotengine/godot-proposals/discussions/3984), this can cause issues when the shader modifies lightx values.

To allow greater artistic flexibility with regards to scene lighting, and combat lighting discontinuity described in the discussion above, sky shaders should instead retain inheritance from lights with the 'use in sky only' toggle enabled.

### Steps to reproduce

1. Add WorldEnvironment and two or more DirectionalLight3D nodes to a scene, these can be separate or parented
2. Add geometry nodes to test lighting
3. Add sky shader to WorldEnvironment
4. Toggle 'use in sky only' on in properties of first DirectionalLight3D

### Minimal reproduction project

Minimal reproduction exceeds Github's file size restrictions, upload is here: https://www.dropbox.com/s/ltlqhjn4yesflqk/4.0_test_lighting.zip?dl=0

**Comment by clayjohn** [comment] 2022-02-16 21:19
I'm not totally certain what the issue is here. There was a bug with "use in sky only" that was fixes earlier today (https://github.com/godotengine/godot/pull/58175), could that be the root cause?

Are you suggesting that if there are two lights in the scene, the sky shader should prioritize lights that are marked as "use in sky only" instead of taking the first light in the scene tree?

**Comment by Ophiolith** [comment] 2022-02-19 19:05
> I am having trouble reproducing this exact issue in a clean project. I will try again with your MRP and see if I can reproduce.

Please let me know if you're still having trouble reproducing - I can try recording a video displaying the issue on the MRP if this would help.

**Comment by clayjohn** [comment] 2022-02-20 05:57
On closer inspection, I can reproduce using Alpha 2, but it is already fixed in master (499eec13a3660f6f05a6212be97ea164fd98b519). 

It was probably fixed by either https://github.com/godotengine/godot/pull/58175 or https://github.com/godotengine/godot/pull/57104

Closing as it is already fixed. It should be working fine for alpha 3 :)

**Closed by clayjohn** 2022-02-20 05:57 UTC
Labels: bug, topic:rendering
