### ISSUE TITLE
Adding an alpha channel to a GPUParticle3D crashes the editor

### ISSUE THREAD

**Issue by FlashDaggerX** [godotengine/godot#71866] opened 2023-01-22 16:40 UTC
### Godot version

v4.0.beta.custom_build [56fdef281]

### System information

Arch Linux 6.1.7-arch1-1 (Vulkan API 1.3.224 - NVIDIA - NVIDIA GeForce RTX 3060)

### Issue description

I was just messing around with the editor doing nothing in particular. The editor crashed after I tried to make a `BoxMesh` transparent. I am not experienced with the ins-and-outs of Godot, so apologies if this isn't the way to do it. I figured I should report the crash none-the-less.

Might be related to #69156?

<details><summary>Backtrace</summary><pre>
================================================================
handle_crash: Program crashed with signal 11
Engine version: Godot Engine v4.0.beta.custom_build (56fdef281ecc40e8ce10d4e17aa1357b150aca18)
Dumping the backtrace. Please include this when reporting the bug to the project developer.
[1] /usr/lib/libc.so.6(+0x389e0) [0x7f9a022539e0] (??:0)
[2] /tmp/godot/bin/godot.linuxbsd.editor.x86_64(+0x3fdf719) [0x55d0c7259719] (??:0)
[3] /tmp/godot/bin/godot.linuxbsd.editor.x86_64(+0x3f6792f) [0x55d0c71e192f] (??:0)
[4] /tmp/godot/bin/godot.linuxbsd.editor.x86_64(+0x3f6e62b) [0x55d0c71e862b] (??:0)
[5] /tmp/godot/bin/godot.linuxbsd.editor.x86_64(+0x3f8748a) [0x55d0c720148a] (??:0)
[6] /tmp/godot/bin/godot.linuxbsd.editor.x86_64(+0x3ee6f3f) [0x55d0c7160f3f] (??:0)
[7] /tmp/godot/bin/godot.linuxbsd.editor.x86_64(+0x4464b54) [0x55d0c76deb54] (??:0)
[8] /tmp/godot/bin/godot.linuxbsd.editor.x86_64(+0x446933b) [0x55d0c76e333b] (??:0)
[9] /tmp/godot/bin/godot.linuxbsd.editor.x86_64(+0x3da496a) [0x55d0c701e96a] (??:0)
[10] /tmp/godot/bin/godot.linuxbsd.editor.x86_64(+0x3da6a75) [0x55d0c7020a75] (??:0)
[11] /tmp/godot/bin/godot.linuxbsd.editor.x86_64(+0x3da9410) [0x55d0c7023410] (??:0)
[12] /tmp/godot/bin/godot.linuxbsd.editor.x86_64(+0x3e0699c) [0x55d0c708099c] (??:0)
[13] /tmp/godot/bin/godot.linuxbsd.editor.x86_64(+0xb0d147) [0x55d0c3d87147] (??:0)
[14] /tmp/godot/bin/godot.linuxbsd.editor.x86_64(+0xab4031) [0x55d0c3d2e031] (??:0)
[15] /tmp/godot/bin/godot.linuxbsd.editor.x86_64(+0xaa6379) [0x55d0c3d20379] (??:0)
[16] /usr/lib/libc.so.6(+0x23290) [0x7f9a0223e290] (??:0)
[17] /usr/lib/libc.so.6(__libc_start_main+0x8a) [0x7f9a0223e34a] (??:0)
[18] /tmp/godot/bin/godot.linuxbsd.editor.x86_64(+0xab21c5) [0x55d0c3d2c1c5] (??:0)
-- END OF BACKTRACE --
================================================================</pre>
</details>

Compiling the editor build should've included debug symbols... Oops. Let me know if there's a way I can fix that.

### Steps to reproduce

* Create a new 3D scene with a `Node3D` as its base
* Add a `GPUParticles3D`
* Set the first `Draw Pass` to a new `BoxMesh`
* Set `Transparency/Transparency` to `Alpha`
* Be humbled with a backtrace.

### Minimal reproduction project

[MRP.zip](https://github.com/godotengine/godot/files/10474931/MRP.zip)

**Comment by clayjohn** [comment] 2023-01-22 17:48
Sounds like a duplicate of https://github.com/godotengine/godot/issues/69156 which will be fixed by  https://github.com/godotengine/godot/pull/71581

Could you confirm whether https://github.com/godotengine/godot/pull/71581 fixes this issue as well?

**Comment by FlashDaggerX** [comment] 2023-01-22 18:59
> Sounds like a duplicate of #69156 which will be fixed by #71581
> 
> Could you confirm whether #71581 fixes this issue as well?

It does!

**Comment by clayjohn** [comment] 2023-01-22 19:34
Wonderful! 

Closing as a duplicate of #69156 

Will be fixed by #71581

**Closed by clayjohn** 2023-01-22 19:34 UTC
Labels: bug, topic:rendering, topic:editor, crash
