### ISSUE TITLE
Feature request: NodeRef (node reference)

### ISSUE THREAD

**Issue by indiemaatheus** [godotengine/godot#7846] opened 2017-02-19 15:14 UTC
From times to times I crash a whole scene while moving (reparenting) a node, and it takes a lot of time to fix (and test) things if you have many scripts. While NodePath's make things cleanear, they won't keep track of the node if you reparent it. So, that's my suggestion: adding a NodeRef property type so one can easily reference another node in its code.

**Comment by bojidar-bg** [comment] 2017-02-19 15:16
I prefer to close this as duplicate of #7821, since it is about the same core issue.

**Closed by bojidar-bg** 2017-02-19 15:16 UTC
