### ISSUE TITLE
The mesh normal map generated by ArrayMesh does not display correctly

### ISSUE THREAD

**Issue by 1419427247** [godotengine/godot#69445] opened 2022-12-01 14:03 UTC
### Godot version

v4.0.beta6.official [7f8ecffa5]

### System information

Win10

### Issue description

When I tried to use GDExtension to make square mesh generation, I found that when I added normal mapping to the material, the face whose normal vector should be (0,0, - 1) would display incorrectly

![image](https://user-images.githubusercontent.com/33598732/205068188-c2fb243b-01c6-48d9-9544-8980ff414702.png)

normals.push_back(Vector3i(0,0,-1))
This should not happen. When I change the normal vector to (0,0,1), it will display correctly

And this problem only occurs when normal mapping is enabled
![image](https://user-images.githubusercontent.com/33598732/205068954-29fc7c03-c34e-487f-a237-82f1887a6aba.png)
When I turn off, the grid display is normal

![image](https://user-images.githubusercontent.com/33598732/205069806-6679e72b-3930-455c-ae59-8763eb4b59e5.png)

### Steps to reproduce

```
@tool
extends MeshInstance3D

var material = preload("res://material.tres")
func _process(delta):
	var basics_uvs = [
		Vector2(0, 0),
		Vector2(1, 0),
		Vector2(1, 1),
	];
	var vertexs = [
	[
		Vector3(0.5, 0.5, 0),
		Vector3(-0.5, 0.5, 0),
		Vector3(-0.5, -0.5, 0),
	]];
	
	var vertices = PackedVector3Array()
	var normals = PackedVector3Array()
	var uvs = PackedVector2Array()
	
	for i in range(3):
		vertices.push_back(vertexs[0][i])
		normals.push_back(Vector3i(0,0,-1))
		uvs.push_back(basics_uvs[i])

	var arr_mesh = ArrayMesh.new()
	var arrays = []
	arrays.resize(Mesh.ARRAY_MAX)
	arrays[Mesh.ARRAY_VERTEX] = vertices
	arrays[Mesh.ARRAY_NORMAL] = normals
	arrays[Mesh.ARRAY_TEX_UV] = uvs

	arr_mesh.add_surface_from_arrays(Mesh.PRIMITIVE_TRIANGLES, arrays)
	arr_mesh.surface_set_material(0,material)
	mesh = arr_mesh
```

### Minimal reproduction project

[Report.zip](https://github.com/godotengine/godot/files/10132946/Report.zip)

**Comment by Calinou** [comment] 2022-12-01 15:48
You need to generate tangents for the normal map to display correctly.

**Comment by clayjohn** [comment] 2022-12-01 17:57
Duplicate of https://github.com/godotengine/godot/issues/65564

**Closed by clayjohn** 2022-12-01 17:57 UTC
Labels: archived, discussion, topic:core, topic:rendering, topic:3d
