### ISSUE TITLE
godot 4.x : The parameter type of the OptionButton.ItemSelected has not changed, the complier needs long instead of integer.  

### ISSUE THREAD

**Issue by 1641585051** [godotengine/godot#86157] opened 2023-12-14 13:48 UTC
### Tested versions

godot 4.x

### System information

windows 10

### Issue description

I notice this issue of  The parameter type of the OptionButton.ItemSelected has not changed, the complier needs long instead of integer.  At least that's the case with C# in the documentation. and if there's no problem with the doc on GDScript, can you add a C#-relater type description

### Steps to reproduce

OptionButton opButton = GetNode<T>("...");
opButton.ItemSelected += OnItemSelected;

......

private void OnItemSelected(long Index)
{
  // ......
}

### Minimal reproduction project (MRP)

this may be an imperfection of the doc,and there should be no need for minimal replication projects.

**Comment by AThousandShips** [comment] 2023-12-14 13:56
Duplicate of https://github.com/godotengine/godot/issues/65311

**Closed by AThousandShips** 2023-12-14 13:56 UTC
