### ISSUE TITLE
UndoRedo doesn't undo in the reverse order

### ISSUE THREAD

**Issue by Macksaur** [godotengine/godot#60836] opened 2022-05-06 20:35 UTC
### Godot version

3.4.4.stable

### System information

Windows 10, GLES3

### Issue description

When using `UndoRedo` to record and commit actions they are executed in the order that they are added (good, correct) but they are not undone in the reverse order (problematic).

This is a problem if you persist an `UndoRedo` while you accumulate actions as part of a single gesture (stroking a line). If the line self-intersects the undo corrupts the data and does not restore it to the state that it was in previously.

`UndoRedo.undo()` should execute everything in reverse because it's not always possible to guarantee the ordering of the code that adds methods/data to be undone.

### Steps to reproduce

```gdscript
tool
extends EditorPlugin

func _echo(what:String, n:int) -> void:
	prints(what, n)

func somewhere() -> void:
	var test := get_undo_redo()
	test.create_action("test")

	for n in 3:
		test.add_do_method(self, "_echo", "do", n)
		test.add_undo_method(self, "_echo", "undo", n)

	test.commit_action()
	test.undo()
```
```
do 0
do 1
do 2
test
undo 0
undo 1
undo 2
```

**Comment by Calinou** [comment] 2022-05-06 20:53
cc @KoBeWi 

This change would almost certainly break compatibility with existing projects, so I don't think it can be done for 3.x.

**Comment by KoBeWi** [comment] 2022-05-06 21:06
Why not just
```GDScript
for n in 3:
	test.add_do_method(self, "_echo", "do", n)
	test.add_undo_method(self, "_echo", "undo", 2 - n)
```
?

The way UndoRedo works right now is more intuitive, there is not reason to change it just because of a single corner case.

**Comment by Macksaur** [comment] 2022-05-06 23:23
I doubt fixing this breaks any compatibility because you can't actually rely on it and use it in a meaningful fashion for complex operations. If anyone relies on the order of `undo()` right now... 🤷

---

Anyway, for a real example of why it's busted: look at the implementation of Godot's `TileMapEditor` and the messy lengths it goes to ensure drawing tiles don't self-intersect and corrupt data. It doesn't even use `UndoRedo` until the very last minute because it simply *can't do anything else*. `UndoRedo` doesn't support undo as a time reversible operation => `TileMapEditor` must track it's own undo data and redundantly ensure correctness on its own.

As for the sample code I gave, I actually tried to rewrite it to avoid making it easy to gloss over the issue... but you're suggesting changes that just don't work. `2-n` doesn't "exist" in any real sense, that just shrugs away the actual problem. These are events separated in time, one after the other in sequence. i.e. set this cell to that tile and record what data was clobbered then repeat for the next cell, and the next. It must be reversible. Which it currently is not. Not without recording extra information.

In the case of the `TileMapEditor` it manually tracks this extra information, `undo_data`, and avoids recording self-intersections /at all/ because there's no support for undoing them. This isn't a corner case. Every user of `UndoRedo` will have to do something extraneous like this if any of their operations are further divisible, order-sensitive or have the potential to be self-intersecting.

---

IMO this is why `UndoRedo.undo()` is fundamentally broken. I don't understand how it possibly can be more intuitive to perform the undo operation in the forward-order that overwrites data?

If this is fixed it allows for the simple code to be correct rather than requiring every user of `UndoRedo` to track the time-reversibility of their operations themselves. It was very surprising to find that `undo()` worked this way.

**Comment by timothyqiu** [comment] 2022-05-07 03:36
IMHO, the way you structure your code assumes undo methods will be called in reverse order.

```gdscript
for n in 3:
    test.add_do_method(self, "_echo", "do", n)
    test.add_undo_method(self, "_echo", "undo", n)
```

The `add_*()` methods just add the command to the corresponding action.

```gdscript
# execute these for DO
test.add_do_method(self, "_create_that_object")
test.add_do_method(self, "_add_that_object_to_system")
test.add_do_method(self, "_update_viewport")

# execute these for UNDO
test.add_undo_method(self, "_remove_that_object_from_system")
test.add_undo_method(self, "_destroy_that_object")
test.add_undo_method(self, "_update_viewport")
```

It's strange to write something like:

```gdscript
# you have to read this in reverse order (?)
test.add_undo_method(self, "_update_viewport")
test.add_undo_method(self, "_destroy_that_object")
test.add_undo_method(self, "_remove_that_object_from_system")
```

**Comment by Macksaur** [comment] 2022-05-07 10:41
You don't write that... that's why. Especially when it's generated from event based code that adds things automatically to `UndoRedo` that you have no control over what's added next.

Please stop picking on the over-simplified and trivial example... 😄

```gdscript
test.add_undo_method(self, "_update_viewport")

test.add_do_method(self, "_create_that_object")
test.add_undo_method(self, "_destroy_that_object")

test.add_do_method(self, "_add_that_object_to_system")
test.add_undo_method(self, "_remove_that_object_from_system")

test.add_do_method(self, "_update_viewport")
```

Related commands should be grouped together so that they undo in the correct order. This only occurs in the manner you speak of from "human readable" undo code made to look ordered for whomever wrote it when it is in fact not.

Have you looked at `TileMapEditor`? You shouldn't have to track extraneous data to perform an undo.

---

This reverse order has already been rationalized in other places in the engine (https://github.com/godotengine/godot/pull/55512). I don't see why it is so easy to refute here?

If this is honestly such a sticking point, can we add a flag that makes undo execute in the correct order? I would be happy with that because it would both preserve backwards compatibility and make both ways to write possible in the simplest manner.

`UndoRedo.set_undo_in_reverse_order_for_current_action(true)`

**Comment by KoBeWi** [comment] 2022-05-07 11:57
> Have you looked at TileMapEditor? You shouldn't have to track extraneous data to perform an undo.

Which part are you referring to exactly and how reverse undo would improve it?

> UndoRedo.set_undo_in_reverse_order_for_current_action(true)

That could be added, but sounds like something for a proposal.

**Comment by timothyqiu** [comment] 2022-05-07 12:03
> You don't write that... that's why. Especially when it's generated from event based code that adds things automatically to `UndoRedo` that you have no control over what's added next.

I mean, judging from OP, you're stating that it's a bug that undo does not call methods in reverse order. But this is expected behavior and your code can be adjusted in a way to work with the current design.

What you suggest could be seen as a feature proposal. You can post it here: https://github.com/godotengine/godot-proposals/issues

**Comment by Macksaur** [comment] 2022-05-07 13:08
> But this is expected behavior...

So was the execution of `tree_exited` happening in the wrong order until it was fixed.

> Which part are you referring to exactly and how reverse undo would improve it?

I am specifically referring to self-intersection in `TileMapEditor`'s tile painting code. If it did the exact reverse of every operation it added to the `UndoRedo` it would not need to track custom data in `TileMapEditor.undo_data`.

---

This affects all users of `UndoRedo` of any complex operation and is why I believe it's fundamentally wrong and an unnecessary burden on users to manually track and get right. It's all a workaround to a "bug" in `UndoRedo`.

If the reverse order is used then none of this is necessary and operations are simply subtracted in the exact order they were last added (i.e. reverse).

I am not opening any proposals given the friction here. I feel unable to explain myself or the issue further such that it would be a worthwhile use of time.

**Comment by timothyqiu** [comment] 2022-05-07 13:18
> So was the execution of `tree_exited` happening in the wrong order until it was fixed.

The order of `tree_exit` has nothing to do with `UndoRedo` I believe.

> I am not opening any proposals given the friction here. I feel unable to explain myself or the issue further such that it would be a worthwhile use of time.

I think it's just the "friction" for labeling current behavior as bug/wrong. I see no reason to reject adding a reverse toggle for it :P

In the end, there is no solution that fits every scenario. Things will go smoother if done in a suitable way.

**Comment by L4Vo5** [comment] 2023-04-30 19:32
I'm surprised to learn this is how it works. This ruins many use cases where you don't center your logic entirely around the UndoRedo system - for example, you can't safely start recording an action, then call some functions that set off a chain of events which unpredictably call many different functions and objects, each of which contributes to the action by registering their do and undo methods. This would break if these independently-made changes depended on the other objects' data and expected said data before `undoing` to be in the same state it was after `doing` (which is a reasonable expectation)

Even registering different actions and merging them with `UndoRedo.MERGE_ALL` will still make the undos execute in the forward order. Since each action has to register their own dos and undos and can happen at entirely different points in time, at that point it makes absolutely no sense that the merged version would still start with the undos for the first action, then for the second, etc.

The "reverse" order that people commenting here seem so baffled by is how I initially expected things to work. Grouping a "do" action with its corresponding "undo" action, I think, is more intuitive than registering a bunch of "do" actions first and all the "undo" ones later (which again can't even be done if they happen over different methods that you don't exactly know a priori). Even [the docs' example code](https://docs.godotengine.org/en/4.0/classes/class_undoredo.html) groups them:
```gdscript
    var node = get_node("MyNode2D")
    undo_redo.create_action("Move the node")
    undo_redo.add_do_method(self, "do_something")
    undo_redo.add_undo_method(self, "undo_something")
    undo_redo.add_do_property(node, "position", Vector2(100,100))
    undo_redo.add_undo_property(node, "position", node.position)
    undo_redo.commit_action()
```
And if you group them together like that, it follows that order-dependent actions like creating and destroying things would have to happen in reverse order when undoing.
The only notable exception would be things that you specifically want to happen at the start or end of undoing actions, like updating a viewport. But I think that's exceptional enough to force you to work around it, instead of forcing you to work around everything else.

I'm definitely in favor of _at least_ having a toggle for this, and wouldn't even mind if it's made into the default behaviour in a future compat-breaking update.

**Comment by KoBeWi** [comment] 2023-04-30 19:47
This is issue was recently brought up on chat. Reverse order could be an optional argument of `create_action()` method.

**Comment by L4Vo5** [comment] 2023-04-30 20:09
> This is issue was recently brought up on chat. Reverse order could be an optional argument of `create_action()` method.

what about the behaviour of merging actions?

**Comment by KoBeWi** [comment] 2023-04-30 20:11
It would be the same, no? Action merging works by removing duplicate actions (based on name) from the action chain. Each action is still self-contained, so order of undo does not matter.

**Comment by L4Vo5** [comment] 2023-04-30 21:18
> It would be the same, no? Action merging works by removing duplicate actions (based on name) from the action chain. Each action is still self-contained, so order of undo does not matter.

Currently, undoing merged actions still executes the first merged action's undos, then the second, etc.
With the logic of "whatever gets done last is undone first", allowing *that* order to be reversed is also desirable, which is different from allowing each of the merged actions to themselves have a reversed undo order (or not) for their inner method calls.

**Comment by KoBeWi** [comment] 2023-04-30 21:35
> Currently, undoing merged actions still executes the first merged action's undos, then the second, etc.

I checked the code and actions are cleared when they are merged (they "execute" as no-op).

In any case, merged actions work the same whether they are merged or not, it's just an optimization. Not sure how their order matters.

**Comment by L4Vo5** [comment] 2023-04-30 22:59
Well, order is the entire issue here.
The way I see merging actions, they're useful to have a "broader action" that's still broken down into parts, for example if it takes place over a few seconds instead of instantly, that way you can record UndoRedo actions as you go and the user can undo them before the last step is done with no issue. This might not be so useful in the editor, but it might be when implemeting undos in a game. But maybe I'm misunderstanding what the purpose of the feature is.

Regardless, merged actions currently work the same as if you only made one action in the first place, which is _different_ from taking several, separate actions and putting them together. If you take merged actions as meaning the latter, then not only would you probably expect them to undo in opposite order (equivalent to a bunch of actions that you were undo()-ing in sequence - which will obviously make them run backwards -, which were simply optimized into a single action that you undo() once while still producing the same effect), you'd also want each inner action to independently function how you'd expect from looking at their individual code. That means that if the first action registers the undo steps 1, 2 and 3, and expects them to run in reverse order (`3 2 1`), but then the second action, made somewhere else in the code, registers the undo steps 5 and 4 expecting them to run in forward order (`5 4`), then merging them with backwards order should produce exactly `5 4 3 2 1`.

Implementation-wise, I see two options. Either reverse-order actions register their steps with push_front or an equivalent, or every action keeps track of a flag that dictates if it'll run in forward or reverse order.
For the first option, merging them will still be easy: you either concatenate the first array with the second, then the third, etc. or if merging backwards, the last array with the previous to last etc. However, using push_front for every added undo step could be a performance hit (one solution for that may be to build the vector normally and only reverse it when the action is comitted).
For the second option, vector performance is the same as usual, but merging them will get messy if the different actions have their reverse flag set to different values. You can't just append all the arrays, in the previous example that'd give you the undo array `1 2 3 5 4` which will never undo as `5 4 3 2 1` whether you run it forwards or backwards. You'd have to, when merging, selectively reverse or not each action's undos depending on that action's flag.

Furthermore, if reverse merging isn't even implemented, then option 1 will produce `3 2 1 5 4` and option 2 will have to arbitrarily decide which of the two actions' flags to keep, and if it keeps the first one's (reverse order), it'll end up undoing as `4 5 1 2 3`, which contains `4 5`, which is the opposite of what you locally expected when making the second action with the undo-forwards flag.

**Comment by KoBeWi** [comment] 2023-04-30 23:09
Merging only works for actions that have the same name. If your `3 2 1` and `5 4` actions are different then they should have different name and never be merged.

UndoRedo was designed specifically for editor, not for games. If you have a complex use-case where you have multiple different actions merged together and their order matters and all, it's just out-of-scope for this class.

The main use of merging is actually in the editor. Often when changing something in the editor you might see message spam about setting some property (e.g. when using ColorPicker). These 30+ actions are merged into 1, otherwise it would make undo unusable.

**Closed** 2023-06-14 07:28 UTC
Labels: discussion, topic:core
