### ISSUE TITLE
GDScript issue with re-initializaing of a variable when script used both as autoload and bound to a Node

### ISSUE THREAD

**Issue by Krakean** [godotengine/godot#14531] opened 2017-12-10 22:44 UTC
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Windows 10, Godot 3.0 master at 10 dec 2017

**Issue description:**
GDScript variable state is resetted from time to time.
Main reason that cause this issue: adding a script to Project's AutoLoad section.
If you remove from autoload, then bug disappear. OR if you remove this script from Node's script section in Inspector.
So I guess, if the same script is allowed to be in Autoload _and_ attached to node - then we have a bug. Otherwise - we should popup an error messagebox to user saying like he cannot have same script in autoload & attach to node.

**Steps to reproduce:**
Open project in Godot, run it and see output tab.
You will see log like this:
res: 0, val: False
res: 3, val: False
res: 0, val: False
SETTING TRUE!
res: 1, val: True
res: 3, val: False <-- bug
SETTING TRUE!
res: 1, val: True
res: 0, val: False <-- bug
SETTING TRUE!
res: 1, val: True
SETTING TRUE!
res: 1, val: True
res: 0, val: True
res: 0, val: True
res: 3, val: True
res: 3, val: True
res: 0, val: True
SETTING TRUE!
res: 1, val: True
SETTING FALSE!
res: 2, val: False
res: 0, val: True <-- bug
res: 0, val: False

**Link to minimal example project:**
https://nofile.io/f/pSpjwosTrMm/qwe2.zip

**Comment by eska014** [comment] 2018-01-03 19:33
Sample project is down, can you upload the zip file directly to Github? Drag and drop into the text field

**Comment by akien-mga** [comment] 2018-01-05 13:41
We have now entered release freeze for Godot 3.0 and want to focus only on release critical issues for that milestone. Therefore, we're moving this issue to the 3.1 milestone, though a fix may be made available for a 3.0.x maintenance release after it has been tested in the master branch during 3.1 development. If you consider that this issue is critical enough to warrant blocking the 3.0 release until fixed, please comment so that we can assess it more in-depth.

**Comment by vnen** [comment] 2018-09-16 20:44
No clear way to reproduce the bug and the link to the project is long dead. Can anyone confirm this?

**Comment by akien-mga** [comment] 2018-09-17 09:53
Closing for now as there's not enough information to work with. Can be reopened if the issue is still relevant and someone can provided additional info.

**Closed by akien-mga** 2018-09-17 09:53 UTC
Labels: bug, topic:gdscript
