### ISSUE TITLE
editor change all id of resource in scene(tscn) after deleting a top resource

### ISSUE THREAD

**Issue by puppetmaster-** [godotengine/godot#8566] opened 2017-04-28 08:23 UTC
**Operating system or device - Godot version:**
Operating system: Windows 7
Godot version: 2.1.3

**Issue description:**
What happened:
Godot change all id of resource in scene after deleting a top resource.
![image](https://cloud.githubusercontent.com/assets/10463138/25520243/8ec75972-2bfb-11e7-9468-f16f75c061af.png)
What was expected:
Not changing resource id or change only the last resource to id = 1
 ([ ext_resource path="res://resources/player/player_small_23.png" type="Texture" id=~~34~~ 1 ] )

**Steps to reproduce:**
1. create a scene (tscn) with many resources
2. save the scene
3. check in repo
4. delete first added resource

**Comment by reduz** [comment] 2017-04-28 08:42
This is expected, they are indices to external resources. Internal resource
IDs are kept

**Comment by Zylann** [comment] 2017-04-28 10:31
Same as here: https://github.com/godotengine/godot/issues/6527

**Comment by reduz** [comment] 2017-04-28 12:47
Its kind of a logical thing.. its easy to store an id for a built in
resource because it's built in.. but for a resource that is shared between
many scenes, there is just nowhere to store an id..

**Comment by bojidar-bg** [comment] 2017-04-28 13:06
Marking as duplicate of #6527.. Would be nice if you can migrate the discussion there

**Closed by bojidar-bg** 2017-04-28 13:06 UTC
Labels: discussion, topic:core

**Comment by Zylann** [comment] 2017-04-28 13:47
@reduz you could store the mapping in the scene resource, maybe?
