### ISSUE TITLE
Changing a visual shader varying type on creation closes the varying creation window

### ISSUE THREAD

**Issue by mudu0912** [godotengine/godot#79554] opened 2023-07-16 17:32 UTC
### Godot version

4.1.stable

### System information

Godot v4.1.stable - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3060 Laptop GPU (NVIDIA; 31.0.15.3623) - 11th Gen Intel(R) Core(TM) i5-11300H @ 3.10GHz (8 Threads)

### Issue description

When creating a varying in a visual shader, trying to change one of the two drop-down settings closes the varying creation window, making it impossible to create a varying that isn't the default float.

### Steps to reproduce

1 - Create a blank Godot 4.1 stable project
2 - Create a visual shader
3 - Go to vertex panel
4 - Click on manage varying > add varying
5 - Click on either of the drop-down options

### Minimal reproduction project

[ChangingVaryingTypeClosesPopUpWindow.zip](https://github.com/godotengine/godot/files/12064681/ChangingVaryingTypeClosesPopUpWindow.zip)

**Comment by QbieShay** [comment] 2023-07-16 23:15
Bug still present in `a7583881af5477cd73110cc859fecf7ceaf39bd7`

**Comment by QbieShay** [comment] 2023-07-16 23:16
I imagine either @Chaosus or @Geometror may have an idea of what is happening there..? Or maybe this is a change in control nodes

**Comment by Chaosus** [comment] 2023-07-17 06:18
Duplicate of https://github.com/godotengine/godot/issues/79109

**Closed by Chaosus** 2023-07-17 06:18 UTC
Labels: bug, topic:editor, confirmed, topic:shaders

**Comment by Chaosus** [comment] 2023-07-17 06:20
(Have no idea why this happening, probably some GUI bug.)
