### ISSUE TITLE
Feature request for Visual Scripting: Copy, Cut and Paste nodes between the scripts

### ISSUE THREAD

**Issue by procedural** [godotengine/godot#6117] opened 2016-08-11 16:28 UTC
I tried to select the nodes and press Ctrl + C for copy or Ctrl + X for cut and in another script Ctrl + V for paste: nothing happens...

It's an important feature because text-based GDScript allows you refactor code easily by copy and pasting code around, so :)

So far I'm having a blast with Visual Scripting, thank you for making it happen!

**Comment by procedural** [comment] 2016-08-11 16:55
Also, copy-pasting functions, variables and signals between the scripts...

**Comment by vnen** [comment] 2016-08-11 17:00
Duplicate of #6073.

**Closed by vnen** 2016-08-11 17:00 UTC

**Comment by procedural** [comment] 2016-08-11 17:04
@vnen oh, thanks, didn't noticed that one!
