### ISSUE TITLE
Yellow text (Debugger with Warnings) is unreadable when using light themes until restarting the editor

### ISSUE THREAD

**Issue by Yagich** [godotengine/godot#72955] opened 2023-02-09 10:32 UTC
### Godot version

4.0rc1

### System information

Linux/Manjaro

### Issue description

When using light themes, the warnings in the debugger are almost indistinguishable from the light background.

![image](https://user-images.githubusercontent.com/24468819/217785303-363d54a6-c4e9-4325-b778-e0fcd477156e.png)
![image](https://user-images.githubusercontent.com/24468819/217786098-9de25277-b31e-4e77-b313-03f7aa080de8.png)

### Steps to reproduce

Use a light theme and run a project with warnings

### Minimal reproduction project

N/A

**Comment by dusky1ight** [comment] 2023-02-10 15:51
Hey @Yagich !
Hope you're doing well 
I would like to work on the issue.
Can you please assign this to me?

**Comment by Zireael07** [comment] 2023-02-10 15:53
Godot engine doesn't practice assigning issues. Just make a PR

**Comment by TheShed412** [comment] 2023-02-23 04:08
If this is still an issue, it could be a desktop environment issue. I am on a pretty vanilla Ubuntu 20 system and I am not able to reproduce this.
![godot_yellow](https://user-images.githubusercontent.com/9973218/220819330-05e543ea-ec71-49fc-8a69-3ec4f47b9b11.png)

**Comment by moraguma** [comment] 2023-03-01 23:47
I'm on Windows and it's pretty hard to read

![image](https://user-images.githubusercontent.com/63124011/222292847-09b367db-e488-41db-a282-271fcf8f0dad.png)

**Comment by akien-mga** [comment] 2023-03-02 08:27
You might need to restart the editor after changing the theme for the change to fully take effect.
Can you confirm that it works fine after a restart @Yagich?

**Comment by Yagich** [comment] 2023-03-02 17:40
Ah yes, after restart it looks fine!

**Closed** 2023-03-10 21:51 UTC
Labels: bug, topic:editor, usability
