### ISSUE TITLE
Function `raise` sometimes doesn't change render order of controls

### ISSUE THREAD

**Issue by MednauN** [godotengine/godot#14364] opened 2017-12-07 06:05 UTC
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Windows 10
Godot 3.0 7b02f5591d2a4c4d2d7da723b1303a99b6c4f168

**Issue description:**
Sometimes `raise` doesn't work as expected - the order of child nodes is changed, but the render order of Control nodes isn't.
I made a minimal example to reproduce this bug - running a scene with following script (where "Layer1" and "Layer2" are controls):
```
extends Node

var initialized = false

func _process(delta):
	if not initialized:
		initialized = true
		var l1 = load("res://Layer1.tscn").instance()
		get_parent().add_child(l1)
		var l2 = load("res://Layer2.tscn").instance()
		add_child(l2)
	else:
		raise()
```
Results in situation where "Layer2" is below "Layer1", but according to scene tree it should be above:

![invalid_tree](https://user-images.githubusercontent.com/20835548/33700102-b1de983c-db49-11e7-9af6-e81fb080cac5.png)

And some more cases I tried:
- Bug doesn't appear if call `raise` immediately after creating children. But appears if call it via `call_deferred`
- Change type of "Main" node to a Control fixes the bug too
- Re-parenting this scene from root to another scene does nothing
- And this code also produces the bug:
```
func initialize():
	var l1 = load("res://Layer1.tscn").instance()
	get_parent().add_child(l1)
	var l2 = load("res://Layer2.tscn").instance()
	add_child(l2)
		
func _ready():
	call_deferred("initialize")
	
func _process(delta):
	raise() # or call_deferred("raise")
```

**Link to minimal example project:**
[sample.zip](https://github.com/godotengine/godot/files/1537956/sample.zip)

**Comment by DleanJeans** [comment] 2018-01-13 16:28
Godot 3 Beta 2 reporting!

This works pretty well for me:
```
func _ready():
    call_deferred("raise")
```
The child order seems to be locked when everything is getting ready (`_ready` is called). As I get this when I call `raise()` without `call_deferred()`:
```
Condition ' data.blocked > 0 ' is true.
```

I guess the problem is poor documentation.
I think it's better if `raise()` is deferred by default, like `queue_free()`, at least in this case.

**Comment by MednauN** [comment] 2018-01-13 16:39
@DleanJeans well, I guess this issue needs re-checking since it's quite old. I will check if the sample works when I have some free time (like tomorrow or so). If you would like, you can do it yourself, there is a sample project attached to the issue.

And my original complain was that the order of objects in scene tree _was_ changed, but the render order wasn't (as you can see in screenshot: Layer2 is at the top according to the scene tree, but it's rendered at the bottom).

**Comment by DleanJeans** [comment] 2018-01-13 17:39
Oops!
I was messing around with `raise()` when I found this.
I guess I'm pretty burned out after a long day to miss those.
And sorry, I just checked it and it's still not fixed.

**Comment by Calinou** [comment] 2020-06-07 16:42
Can anyone still reproduce this bug in Godot 3.2.1 or [3.2.2beta4](https://godotengine.org/article/dev-snapshot-godot-3-2-2-beta-4)?

**Comment by Calinou** [comment] 2020-06-21 13:48
Closing due to lack of response. Please comment if you can still reproduce this bug.

PS: If no [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) was included in the original bug report, please upload one as well to ease troubleshooting.

**Comment by Poobslag** [comment] 2020-06-24 18:13
I'm still encountering this in 3.2.1 -- I have a scene with about 400 nodes being added/removed rapidly, and it occasionally (but not very consistently) results in nodes flickering as they jump forward or backwards in the scene tree.

**Comment by Poobslag** [comment] 2020-06-27 18:14
I've fixed my issue by getting rid of the `remove_child` calls. I was implementing an object pool unnecessarily, which required a lot of `remove_child` calls which affected the renderer in unpredictable ways.

Getting rid of the `remove_child()` calls allows the renderer to work as it's designed to. While I'm unsure why removing invisible children affected the draw order, I recommend closing the issue until someone can reproduce the bug in a more concise way than I'm able to.

**Comment by Calinou** [comment] 2020-06-27 18:44
Closing per @Poobslag's comment.

**Closed by Calinou** 2020-06-27 18:44 UTC
Labels: bug, topic:rendering

**Comment by Emaleth** [comment] 2021-11-07 23:20
3.4
CanvasLayer with PanelContainer children. Clicking on any children call raise() on that node. Index is correct, but node doesn't move in the tree nor moves to top visually.

**Comment by Calinou** [comment] 2021-11-07 23:52
@Emaleth Please open a new issue with a minimal reproduction project attached.
