### ISSUE TITLE
Converting project from Godot 3 to 4 causes some nodes properties to revert to their defaults

### ISSUE THREAD

**Issue by Marigem** [godotengine/godot#65999] opened 2022-09-17 18:30 UTC
### Godot version

v4.0.beta1.official.20d667284

### System information

Windows 10, Arch Linux

### Issue description

Timer node and animation tree process callback mode reverts from physics to idle.

Raycast2D cast_to property reverts to the default (0, 50).

These are the ones I noticed.

### Steps to reproduce

Convert MRP to godot 4 beta

### Minimal reproduction project

[convert-mrp.zip](https://github.com/godotengine/godot/files/9592394/convert-mrp.zip)

**Comment by KoBeWi** [comment] 2022-09-17 18:42
I think a conversion for these properties is just missing, so they are not renamed to the new ones and get reset.

**Comment by Calinou** [comment] 2022-09-17 20:00
RayCast's `cast_to` was renamed to `target_position` in 4.0.

**Comment by gotnospirit** [comment] 2022-09-18 00:12
https://github.com/godotengine/godot/blob/24115beb3c69e648b1d48f969785b9b0729e1be8/editor/project_converter_3_to_4.cpp#L1015-L1031

**Comment by Mickeon** [comment] 2022-09-29 08:12
Oook, the converter reeally needs some refactoring. It's really difficult to work with how repetitive the code is.

**Comment by TheSofox** [comment] 2024-09-24 11:39
`editor\renames_map_3_to_4.cpp` has been updated at some stage to allow `cast_to` to be renamed to `target_position`. Confirmed it works on v4.4.dev.custom_build [4254946de]

So that leaves `process_mode` to `process_callback` for `Timer` (and incidentally `Camera2D`); and to `callback_mode_process` for AnimationTree. Unfortunately, this is gonna be hard to fix because in 4.x, the `Node` type attribute `pause_mode` got renamed to `process_mode`.

I think you can see how that's a big conflict. Remember all the above nodes (`Timer`, `Camera2D`, etc) inherit from `Node` so if a Godot 4.x opens the scene file, and reads `process_mode` for `AnimationTree`, how does it know whether it was the result of someone setting a pause mode in Godot 4.x, or someone setting the callback mode in Godot 3.x? This stops me from using the `_set()` method solution, which I've used to solve a similar problem like this in the past. If someone tries to set `process_mode`, the `Node` class intercepts it before it ever reaches the `AnimationTree::_set()`

**Comment by akien-mga** [comment] 2024-09-24 13:27
Thanks for checking. Indeed these remaining conflicts are complex and so far I think the consensus is to not try to implement the complexity required to deal with them. So I would close the remaining issue with `process_mode` as a "wontfix".

**Closed by akien-mga** 2024-09-24 13:27 UTC
Labels: enhancement, topic:editor
