### ISSUE TITLE
Godot 4.0 beta - custom C# template not available

### ISSUE THREAD

**Issue by toddgibson** [godotengine/godot#66519] opened 2022-09-28 00:30 UTC
### Godot version

4.0.beta1.mono

### System information

Windows 11, RTX 3050

### Issue description

In Godot 3.5 when adding a new script to a node, templates from %APPDATA%\Godot\script_templates\ are available.  In 4.0 they are not.

<img width="229" alt="image" src="https://user-images.githubusercontent.com/3081793/192660667-f0b8dc12-8afb-4802-a6d2-4d359ec5a71f.png">

In 3.5, my Basic template is available to use:
<img width="269" alt="image" src="https://user-images.githubusercontent.com/3081793/192660861-5b7b8dd0-f42c-4283-affe-8f9e292c6b8b.png">

In 4.0 my Basic template is not available:
<img width="342" alt="image" src="https://user-images.githubusercontent.com/3081793/192660774-2b83a4e5-e9d2-4103-898d-4ba35541d3e8.png">

### Steps to reproduce

Add a script template to the default path (above)

When adding a script to a node it is not available.

**Comment by raulsntos** [comment] 2022-09-28 09:37
Duplicate of https://github.com/godotengine/godot/issues/61614

In 4.0 the templates now need to be in a folder with the name of the target class (e.g.: `script_templates/Node/basic.cs`).

**Closed by raulsntos** 2022-09-28 09:37 UTC
Labels: bug, topic:editor, topic:dotnet, regression
