### ISSUE TITLE
Remote peer state isn't synchronized

### ISSUE THREAD

**Issue by Enhex** [godotengine/godot#17324] opened 2018-03-07 03:37 UTC
**Godot version:**
3.0.2

**OS/device including version:**
Window 10 64-bit

**Issue description:**
I tried out the "Multiplayer Bomber Demo" with another person.
I had my port forwarded, the other person successfully joined, but when I started the game he was still stuck at the lobby while the game started on my side.

I also made a simple multiplayer test project without a lobby, having a server (without a player), me connected locally, and the other player connected remotely. The other player could see me move, but I couldn't see the other player move.

We later tested using another multiplayer test I made in another game engine and it worked fine, indicating the problem is caused by Godot's networking.

**Steps to reproduce:**
You could try playing "Multiplayer Bomber Demo" with remote people. I'm not sure what's the cause so I don't know if this issue will reproduce.

**Minimal reproduction project:**
Multiplayer Bomber Demo: https://godotengine.org/asset-library/asset/139

You can also use my test project, which is much simpler: [multiplayer.zip](https://github.com/godotengine/godot/files/1787678/multiplayer.zip)

**Comment by Faless** [comment] 2018-09-13 02:41
I'm unable to reproduce the issue.
Tested both your project and the bomber on both Linux and Windows, with both `3.0.2` and current `master`.
Remember you CAN'T join a started game in the Bomber demo, so all players MUST join before the server press start game. If someone joins when the game has started he'll be stuck at the lobby.

@Enhex are you still experiencing this issue? Can you try with the latest [Godot 3.0.6](https://godotengine.org/download)

**Comment by Faless** [comment] 2018-09-22 13:41
Just tried a match between a `4G` connected device and a `optic fiber -> WiFI`. On both `3.0.6` and current `master`.
Everything seem to work. Tried both Linux and Windows 10.
Make sure you allow Godot through your firewall if any (e.g. windows firewall) on both client and server and that your port forwarding works.
Closing.

**Closed by Faless** 2018-09-22 13:41 UTC
Labels: bug, topic:network
