### ISSUE TITLE
Foreign nodes are no longer highlighted

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#81055] opened 2023-08-27 20:08 UTC
### Godot version

4.2 6da4ad1

### System information

Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1060 (NVIDIA; 30.0.15.1403) - Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 Threads)

### Issue description

![image](https://github.com/godotengine/godot/assets/2223172/d65ab202-93dd-4d83-bcef-c2b34bfa23f3)

In 4.2 dev3:
![image](https://github.com/godotengine/godot/assets/2223172/8621ec24-65d4-490d-bfc1-7e6e8aa3606a)

### Steps to reproduce

1. Create a scene with some children
2. Instantiate it in another scene
3. Enable editable children

### Minimal reproduction project

N/A

**Comment by Calinou** [comment] 2023-08-27 20:11
I can't get the color to show up in 4.2.dev3 (*Test* has editable children enabled)
![image](https://github.com/godotengine/godot/assets/180032/e6074909-af75-43c7-a35a-53b01341fcda)

It shows up if I add another node as child while editable children is enabled. It's gone once I restart the editor though.

**Comment by bitsawer** [comment] 2023-08-27 20:46
Duplicate of https://github.com/godotengine/godot/issues/78577 and https://github.com/godotengine/godot/issues/78648

Bisected regression to https://github.com/godotengine/godot/pull/72277 by capnm: https://github.com/godotengine/godot/issues/78648#issuecomment-1609761363

**Comment by KoBeWi** [comment] 2023-08-27 21:01
Is it really? I can consistently reproduce it on master and it consistently works in dev3.

**Comment by bitsawer** [comment] 2023-08-27 21:05
I'm not actually sure if we talk about the same thing, by highlight do you mean the color highlight is missing (like Calinou mentioned they yellow color) or something else? Might need some more testing.

**Comment by KoBeWi** [comment] 2023-08-27 23:53
Ok it's not related to inherited nodes. It's some Tree bug. TreeItem text can't be colored.

**Comment by KoBeWi** [comment] 2023-08-28 00:20
Caused by this line
https://github.com/godotengine/godot/blob/6da4ad16624484398331f393b503f8b5e2888c51/editor/gui/scene_tree_editor.cpp#L664
It has existed since 2 months, so something recently might've made it execute more often (aka always).

**Closed** 2023-08-28 10:15 UTC
Labels: bug, topic:editor, usability, regression
