### ISSUE TITLE
DrawRect (Color?) alpha bit not processing correctly

### ISSUE THREAD

**Issue by bferguson3** [godotengine/godot#14607] opened 2017-12-12 23:09 UTC
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
MacOS High Sierra, Macbook Air
Godot 3.0b1 Mono

**Issue description:**
I am using a custom _Draw to draw a simple, transparent green grid around the player.
Using DrawRect, I was unable to get the rect to be transparent except for when I lower the alpha bit extremely close to zero. My estimate is that 0.01 is actually processed by the engine as an alpha of "1", since 0.005 appears to give roughly 50% transparency.

**Steps to reproduce:**
This code:
`Vector2 rPos = p.GetPosition();
            Vector2 rSize = new Vector2(32, 32);
            Rect2 newR = new Rect2(p.GetPosition(), rSize);
            DrawRect(newR, new Color(0, 127, 0, 0.005f));`

Provides the following graphics:
![2017-12-12 3 00 57](https://user-images.githubusercontent.com/32964659/33913381-6b0ba108-df4e-11e7-831f-6c88cfd8df07.png)

**Comment by leoddd** [comment] 2017-12-12 23:14
Color arguments go from 0 to 1, not from 0 to 255. You're basically drawing a green rectangle with a color intensity of 127 times the norm, meaning you'll need a much lower alpha.

It's strange behavior and Color should probably clamp values or throw a warning if you use values above 1, but the issue here isn't the alpha.

**Comment by bferguson3** [comment] 2017-12-12 23:17
Understood, thanks. 
Can I presume that the Color documentation for 3.0 will not support int, as the current docs state?

http://docs.godotengine.org/en/stable/classes/class_color.html
float a - Alpha (0 to 1)
int a8 - Alpha (0 to 255)

**Comment by eon-s** [comment] 2017-12-12 23:59
The one with int argument takes only one, not four.

Docs are fine, also check the latest for current version http://docs.godotengine.org/en/latest/classes/class_color.html

> Constructs a color from a 32-bit integer (each byte represents a component of the RGBA profile).

**Comment by vnen** [comment] 2017-12-13 02:52
Closing since it's not a bug.

**Closed by vnen** 2017-12-13 02:52 UTC
