### ISSUE TITLE
AnimationPlayer does not play the last index in spritesheet

### ISSUE THREAD

**Issue by Dillybob92** [godotengine/godot#6173] opened 2016-08-16 15:23 UTC
**Operating system or device - Godot version:** 2.1 stable

![torch2](https://cloud.githubusercontent.com/assets/10387670/17704401/d2c17620-6389-11e6-9b46-6a761381ee90.png)

1) Add a sprite  and animation player node

2) Set the sprite to `8 vFrames`, and `2 HFrames`

3) Key frame the sprite's frame from 0 to 15

4) Set animation to `continuous mode`

As you see, once you start to animate with this sprite sheet is never shows the last frame index with the purple `L` written on it. 

Also, if you change the steps to zero it doesn't even go to frame `15` that you keyframed.. it goes back to `14` and then it goes to `0` before looping.  

https://i.gyazo.com/04a85fe532082738278270f473ead24a.gif

**Comment by Dillybob92** [comment] 2016-08-16 16:40
Isolated this down a bit more. Seems like the last frame doesn't get shown only **when you have the looping checkbox enabled**.  Tested it without the looping button checked, and it works perfect

**Comment by eska014** [comment] 2016-08-16 18:16
In your animation, the last frame is "visible" for 0 msec, then the animation repeats, immediately switching back to the first frame, before the last frame can really be seen.
You need to give the last frame some time to be visible, i.e. the last frame can't be exactly on the end the animation, but some time before instead (mathematically, on `1 - 1/16 = 0.9375 ≈ 0.94`).

But I would recommend you just insert a keyframe for every frame, that way is much less confusing

**Comment by Dillybob92** [comment] 2016-08-16 18:28
@eska014 Continuous mode AFAIK is supposed to interpolate through those frames and do the math automatically I think. It does for 2.0 (just tested on it now)

**Comment by bojidar-bg** [comment] 2016-08-16 19:27
The thing is that in recent versions it would interpolate tracks from their last value to the start value when loop is on. So, you get something like:

| frame/time | 0.00 | 0.25 | 0.50 | 0.75 | 1.00 | (loop) |
|:---:|:---:|:---:|:---:|:---:|:---:|:---:|
| 4 | | | | | k | |
| 3 | | | | / | \\ |
| 2 | | | / | | \\ | \\ |
| 1 | | / | | | | \\ |
| 0 | k | | | | | (k) |

You can easily see that the problem lies in the fact that it doesn't really have where to interpolate back to start, and since integers are _probably_ **floored**, it might show the frame for a nanosecond or so, and it would then go down to 0 in no time.

**Comment by akien-mga** [comment] 2016-10-04 07:35
Potential duplicate of #959.

**Comment by bojidar-bg** [comment] 2016-10-04 08:20
Note that this might be solvable if we round integers instead of flooring them. IDK if that would break something else though..

**Comment by Zylann** [comment] 2016-10-04 09:24
I think you can round the integer instead. Flooring will prevent you from seeing the last frame, and ceiling will prevent the first.
What about floor(frame_f + 0.5) ?

**Comment by akien-mga** [comment] 2016-10-04 09:28
@Zylann That would mean seeing the first and last sprites only half a unit time :)

**Comment by bojidar-bg** [comment] 2016-10-04 10:34
@Zylann You realise `floor(x+0.5) == round(x)`? :laughing:

**Comment by bojidar-bg** [comment] 2017-04-07 14:27
Actually, have you tried switching the frame property's transition to "nearest"? That way it worked for me on a project I was/am doing.
![image](https://cloud.githubusercontent.com/assets/5276727/24804554/77ce021a-1bb7-11e7-9c0c-9557448ae62a.png)

**Comment by bojidar-bg** [comment] 2017-04-07 14:28
Also, as @brunoferreira94 suggested on https://github.com/godotengine/godot/issues/6697#issuecomment-281239285, 
> On the last key, click on the pen to edit the transition, so click on the straight line and play again. Remember that you have to add a extra step after the final key.

**Closed** 2017-11-09 08:18 UTC
Labels: bug, topic:core

**Comment by akien-mga** [comment] 2017-11-09 09:16
*Bug triage note:* The original issue reporter closed all their issues before deleting their account. If you are affected by a similar issue/want a similar feature, please file a new ticket (referencing this one if it contains useful information) so that it can be further looked at and eventually resolved.
