### ISSUE TITLE
Compiled EXE project cannot read some directories

### ISSUE THREAD

**Issue by KhappaMJ** [godotengine/godot#44273] opened 2020-12-10 19:11 UTC
Dear company please have a look at this code:

```    var path = "res://world/"
    var levels = []
    var dir = Directory.new()

    dir.open(path)
    dir.list_dir_begin()
    while true:
        var file_name = dir.get_next()
        if file_name == "":
            break
        elif not file_name.begins_with("."):
            levels.append(file_name)
            get_node("PanelContainer").get_node("LabelOutput").set_text(file_name)
```

It work properly under dev pressing play. Then once the project has been compiled as an EXE file, it doesn't read the directories into the directory "world"

but if I change directory well, it does work. But only for some directories
Please tell me how to fix it or what to do because we are in a rush

Thank you very much in advance
Kind Regards
Khappa MJ
K-Storm-Studio Ltd

**Comment by Calinou** [comment] 2020-12-10 19:18
What's the file type of the files under `res://world`? Did you add the files under `res://world` to the [non-resource export filter](https://docs.godotengine.org/en/latest/tutorials/export/exporting_projects.html#export-mode)?

> Dear company

There's no company behind Godot :slightly_smiling_face:

**Comment by bruvzg** [comment] 2020-12-10 19:19
What's in the `world` directory? Resource files (images, sound files) are imported to the `res://.import`, and originals are not preserved (and if there's nothing left in the directory in won't be included as well).

**Comment by KhappaMJ** [comment] 2020-12-10 19:23
> 
> 
> What's the file type of the files under `res://world`? Did you add the files under `res://world` to the [non-resource export filter](https://docs.godotengine.org/en/latest/tutorials/export/exporting_projects.html#export-mode)?
> 
> > Dear company
> 
> There's no company behind Godot 🙂

res://world contains other 2 directories like "res://characters" for instance , it's similar but this one can be read

**Comment by KhappaMJ** [comment] 2020-12-10 19:23
> 
> 
> What's in the `world` directory? Resource files (images, sound files) are imported to the `res://.import`, and originals are not preserved (and if there's nothing left in the directory in won't be included as well).

other 2 dirs like other directories in the same project

**Comment by KhappaMJ** [comment] 2020-12-11 09:28
ok so is there a way to fix it by myself? Or do you have to fix it? And how long does this take please?

**Comment by bruvzg** [comment] 2020-12-11 09:31
> other 2 dirs like other directories in the same project

And what's inside these folders? Without seeing full file tree and export options it's impossible to say what's wrong.

**Comment by KhappaMJ** [comment] 2020-12-11 09:35
> 
> 
> > other 2 dirs like other directories in the same project
> 
> And what's inside these folders? Without seeing full file tree and export options it's impossible to say what's wrong.

The folder contains other folders with levels or even empty but the system cant read them.
Just sitting the files from the built program it is able to read some folders and not others.... but why?

**Comment by bruvzg** [comment] 2020-12-11 09:41
PCK do not store folder names at all, only file names.

Empty folders won't be exported (include folder that become empty since all files are non-resource and were skipped).

Add "filter to include non resource files" in the export config to include custom files to the export, see https://docs.godotengine.org/en/latest/tutorials/export/exporting_projects.html.

**Comment by KhappaMJ** [comment] 2020-12-11 09:57
there are not empty folders. What is that? "filter to include non resource files", let me have a look, thanks

**Comment by Calinou** [comment] 2021-01-02 23:27
@KhappaMJ Did you find a solution to this problem?

**Comment by Calinou** [comment] 2021-09-22 00:40
I'll close this as nobody else has been able to reproduce this recently. Please comment (with the [issue template](https://github.com/godotengine/godot/blob/master/.github/ISSUE_TEMPLATE/bug_report.md) filled) if you can still reproduce this.

**Closed by Calinou** 2021-09-22 00:40 UTC
Labels: topic:core, needs testing
