### ISSUE TITLE
Setting default argument value to null makes variable permanently recognized as null

### ISSUE THREAD

**Issue by CsloudX** [godotengine/godot#49183] opened 2021-05-29 08:51 UTC
**Godot version:**

v4.0.dev.calinou.364ea7f28

**OS/device including version:**

Windows10

**Issue description:**

```
func show_dlg(text,parent=null):
    if parent==null:
        parent = Engine.get_main_loop().root
    var dlg = AcceptDialog.new()
    dlg.dialog_text = text
    parent.add_child(dlg)    # Invalid get index "add_child" on base Nil
    dlg.popup_centered()
```
I think the code was correct and could run, but parse error and I can't run the code
**Steps to reproduce:**

**Minimal reproduction project:**

[ParseTest.zip](https://github.com/godotengine/godot/files/6564766/ParseTest.zip)

**Comment by nonunknown** [comment] 2021-05-29 10:38
First some things to point:

Godot Version, should be provided the commit hash, since theres not a official build yet, you can simply go here and copy it:
![image](https://user-images.githubusercontent.com/58845030/120067163-91257580-c050-11eb-823c-78f12224060e.png)

Second: You did not provide a Minimal Reproduction project, for some cases its not necessary, but for yours its needed.

Third: I think if you change this line:
`parent = Engine.get_main_loop().root`
to this:
`parent = get_tree().current_scene`

this will solve your problem!

**Comment by CsloudX** [comment] 2021-05-29 13:28
Maybe I want code like this:
```
static func show_dlg(text,parent=null):
    if parent==null:
        parent = Engine.get_main_loop().root
    var dlg = AcceptDialog.new()
    dlg.dialog_text = text
    parent.add_child(dlg)    # Invalid get index "add_child" on base Nil
    dlg.popup_centered()
```
In a static function, I can call it anywhere, 4.0 have this issue, I download Godot4.0 from unoffcial(https://hugo.pro/projects/godot-builds/), So I don't know the commit hash.
It a parse problem, So I don't upload the reproduction project

**Comment by Calinou** [comment] 2021-05-29 13:31
> So I don't know the commit hash.

The commit hash is written in the top-right corner of the project manager, but also in the editor's About dialog (**Help > About** at the top of the editor). You can click it to copy the full version text.

**Comment by CsloudX** [comment] 2021-05-29 13:48
Sorry, The commit hash and Minimal reproduction project added.

**Comment by Vignesh1-art** [comment] 2021-05-29 14:15
I don't think this issue might be with parsing.

**Comment by KoBeWi** [comment] 2021-05-29 14:21
The culprit seems to be `parent=null` part. It makes variable recognized as null, even though you might pass something in the argument or assign it later. Not to mention that the variable is untyped, so this check shouldn't even happen.
![LufzzW5Txm](https://user-images.githubusercontent.com/2223172/120073730-e9349a00-c099-11eb-97bc-e377cd1151cf.gif)

**Comment by Vignesh1-art** [comment] 2021-05-29 14:25
> The culprit seems to be `parent=null` part. It makes variable recognized as null, even though you might pass something in the argument or assign it later. Not to mention that the variable is untyped, so this check shouldn't even happen.
> ![LufzzW5Txm](https://user-images.githubusercontent.com/2223172/120073730-e9349a00-c099-11eb-97bc-e377cd1151cf.gif)

Yeah I have noticed that removing null works. But I think this should work with null also.

**Comment by Vignesh1-art** [comment] 2021-05-29 14:30
This error is comming from `gdscript _analyzer`

**Comment by CsloudX** [comment] 2021-05-31 06:55
I found can coding like this:
```
static func show_dlg(text,parent:Node=null):
    if parent==null:
        parent = Engine.get_main_loop().root
    var dlg = AcceptDialog.new()
    dlg.dialog_text = text
    parent.add_child(dlg)    
    dlg.popup_centered()
```
And I also this this was logical, So should I close this comment? @Calinou

**Comment by akien-mga** [comment] 2021-05-31 12:25
> And I also this this was logical, So should I close this comment?

The issue is still a bug that needs to be fixed, it should work even without the type hint.

**Closed** 2021-09-17 15:20 UTC
Labels: bug, topic:gdscript, regression
