### ISSUE TITLE
position and global_position give weird values when parent node isn't added to the scene tree

### ISSUE THREAD

**Issue by johnfn** [godotengine/godot#49122] opened 2021-05-27 00:13 UTC
**Godot version:**
3.3

**OS/device including version:**
MacOS Catalina

**Issue description:**
Got weird results from position and global_position

**Steps to reproduce:**

1. Make a new scene with the structure One (Root) > Two
2. Run this code:

```
  var parent: Node2D = load("res://Test.tscn").instance()
  var child = parent.get_child(0)
  
  print(parent.global_position)
  print(child.position)
  print(child.global_position)
```

I get the following results:

```
(143.953995, 114.738998)
(77.738701, 59.867802)
(77.738701, 59.867802)
```

To me, this makes no sense. If `child` is verifiably a child of `parent` - which it is, because it's returned from get_child(0) - then I expect `child.global_position = parent.global_position + child.position`. In this case, that isn't true.

Once I do `add_child(parent)` then this works. 

**Minimal reproduction project:**

[TestProj.zip](https://github.com/godotengine/godot/files/6550269/TestProj.zip)

**Comment by timothyqiu** [comment] 2021-05-27 01:45
I think it's intended behavior.

"global" means relative to the scene tree's coordinate, not the node's parent's. There is no "global" if the node is not inside the tree, so local position is returned instead of the non-existent global position, and an error is generated:

```
get_global_transform: Condition "!is_inside_tree()" is true. Returned: get_transform()
```

**Comment by johnfn** [comment] 2021-05-27 04:52
I'll say that I definitely missed the error message and I think that clears up half my issue...

But I think there's still a problem here. `child` is part of the tree rooted at `parent`, even if that's not attached to anything. So `child.global_position` should be `child.position + parent.global_position`. Go ahead and print an error, but at least return a *reasonable* value for `child.global_position`. Defaulting it to `child.position` doesn't seem to make sense to me - it would make much more sense to be the sum of the positions of its ancestors.

**Comment by kleonc** [comment] 2021-05-27 11:31
First of all this issue is about `CanvasItem.get_global transform()`, it's not specific to the `Node2D.global_position`, `Node2D.global_rotation` etc.

---

> "global" means relative to the scene tree's coordinate, not the node's parent's. There is no "global" if the node is not inside the tree, so local position is returned instead of the non-existent global position,

@timothyqiu Not sure what do you mean by "relative to the scene tree's coordinate" but when a CanvasItem is in the scene tree then its global coordinate space refers to the local coordinate space of the CanvasLayer it belongs to. And CanvasItem's global transform is indeed just a composition of its own transform and consequtive CanvasItems' transforms up in the tree.

For example if you have such tree outside of the scene tree:
```
A (Node2D)
┖- B (Node)
   ┖- C (Node2D)
      ┖- D (Node2D)
```
then after adding `A` to the scene tree `D.global_transform` will be equal to `C.transform * D.transform` no matter where in the scene tree `A` was added to. So it's indeed reasonable to expect `D.global_transform` return the same transform even before adding that tree to the scene tree.
On the other hand `A.global_transform` might change after adding it to the scene tree.

>  and an error is generated

This is a debug only error so `CanvasItem.get_global_transform()` will work as expected by @johnfn in the release builds anyway:
https://github.com/godotengine/godot/blob/364ea7f280a3f074795e542b16b1d0ec76cf6ce2/scene/main/canvas_item.cpp#L464-L480


I'd say the question is: why this check/error was added at all? It was added in 83ae9a5e2859a1dc2393aebeb9f9efdf12c53e73. Is it still needed?
For sure it can potentially spot some unintentional user mistakes e.g.:
```
# doing:
var node: Node2D = some_scene.instance()
node.global_position = ...
some_other_node.add_child(node)

# instead of:
var node: Node2D = some_scene.instance()
some_other_node.add_child(node)
node.global_position = ...
```

All in all, I agree with @johnfn and I think `CanvasItem.get_global_transform()` should return a composition of self+parents' transforms whether in the scene tree or not. Changing that error into a warning might be a viable solution.

**Comment by akien-mga** [comment] 2023-03-09 06:55
Duplicate of #30445

**Closed by akien-mga** 2023-03-09 06:55 UTC
Labels: topic:core, topic:2d
