### ISSUE TITLE
Incorrect key binding detection for Editor Shortcuts on Windows Japanese keyboard

### ISSUE THREAD

**Issue by hsandt** [godotengine/godot#35853] opened 2020-02-02 15:30 UTC
**Godot version:**
3.2

**OS/device including version:**
Windows 10 with Japanese keyboard hardware

**Issue description:**
On a Japanese keyboard, and only when using the corresponding input mapping in the language input settings (e.g. English for Japanese keyboard to input latin characters, or Japanese with Microsoft IME to input kana):

key bindings do not match the symbols written on my keys/the actual input if I type on those keys, for certain symbols:
`;` is read as Equal (note: upper is +)
`:` is read a SemiColon (note: upper is *)
`@` is read as QuoteLeft (note: upper is backtick)
`[` is read as BraceLeft (note: upper is `{` indeed)
`]` is read as BraceRight (note: upper is `}` indeed)
`\` from the bottom is read as Unknown (note: but the Yen key at the top is correctly read as BackSlash, and this is a common issue with JP keyboard with those 2 backslashes so not a big deal)

Since both the Binding assignment in Editor Settings > Shortcuts > Pen Icon > press shortcut and the Binding usage while working in the editor use the same incorrect detection, ultimately it's possible to assign and use the shortcuts you want.

The problem is more with default shortcuts: those use the original binding names, and therefore do not match what the user sees on their keyboard.

Ex: Canvas Item Editor "Zoom In" is mapped by default to Control+Equal, which is physically `Ctrl+;` on my Japanese keyboard. If I want to use `Ctrl+;` for something else, it will conflict with Zoom In, which I will have to manually remap to `Ctrl+Keypad +` or so.

Discussion: On JP keyboard, `=` is not located on the lower part of a key so you could argue by that fixing this, we won't be able to access Zoom In anymore. But this would match the behavior on Linux and actually detect keys as shown on hardware, so I think this would be the intended behavior.

**Steps to reproduce:**
1. Hard: get a JP keyboard in your hands. Maybe find a way to simulate it, maybe French keyboards have the same issue and you'll find one more easily... Or just ask me to test your PR.
2. Go to Editor Settings > Shortcuts > Pen Icon to edit one > press `Ctrl + ;` (or some other key in that area)
3. Observe detected binding: `Control+Equal` (or some other incorrect keycode)

**Comment by Calinou** [comment] 2020-02-02 17:28
I'll close this as a duplicate of #2915, #11777, #20527, #28156, #28157 as this issue was reported numerous times already. Those reports were made with different keyboard layouts, but the underlying issue is the same.

**Closed by Calinou** 2020-02-02 17:28 UTC
Labels: bug, platform:windows, topic:input
