### ISSUE TITLE
Inspector Tooltips Load Without Descriptions on Custom Classes And Properties

### ISSUE THREAD

**Issue by jake-abed** [godotengine/godot#94234] opened 2024-07-11 21:01 UTC
### Tested versions

- Reproducible in v4.3.beta3.official [82cedc83c], v4.3.beta2, and v4.3.beta1.
- Not reproducible in 4.2.2 stable and earlier [EDIT: Inaccurate - present in earlier versions]

### System information

Godot v4.3.beta3 - macOS 14.5.0 - Vulkan (Forward+) - integrated Apple M1 Pro - Apple M1 Pro (8 Threads) (Also tested on Windows 10 and Linux Ubuntu 24.04)

### Issue description

Upon initially loading a project, custom descriptions in user created classes do not appear in the Inspector menu. Instead the text 'No description available.' appears in the tool up.

Saving the file with changes does not fix the problem. However, making any changes/edits to the script and saving it will cause the tooltips to load with the descriptions in place as expected. Closing and reloading Godot will revert the behavior back to the initial unintended behavior.

Expected behavior is that the description, as written in documentation in GDScript, will appear in the tooltip.

Example:

Snippet:
```gdscript
## A test node to demonstrate this bug!
class_name TestNode extends Node2D

## The name of the node!
@export var node_name: String

## The scaling factor for the node size.
@export var scaling: float
```

Appears as the following initially:
<img width="664" alt="Screenshot 2024-07-11 at 1 51 41 PM" src="https://github.com/godotengine/godot/assets/66989570/e6868a5d-341d-4828-a77d-2edf97ce73c1">

It should appear as such:
<img width="692" alt="Screenshot 2024-07-11 at 1 52 33 PM" src="https://github.com/godotengine/godot/assets/66989570/e9e9329d-7b16-4449-a85b-e63d96eac5c0">

Appears to be a regression, though I could be mistaken. I am very curious as to the root cause/solution to the issue, but I am not very familiar with C++ nor the engine's internals.

### Steps to reproduce

1) Load the Minimal Reproduction Project below in a Godot 4.3 beta release.
2) If not open already, open the test_node.tscn scene.
3) Open the associated test_node.gd script in the Script Editor.
4) With TestNode selected in the Scene Dock, try hovering over the custom class `TestNode` or its properties.
5) The tooltip should render with the placeholder text: 'No description available'.
6) Make any non-breaking edits to the test_node.gd script.
7) Repeat step 5 and the documentation will load as intended.
8) Close Godot and reload the project. You should be able to reproduce steps 1-5 again.

### Minimal reproduction project (MRP)

[tooltip_test_mrp.zip](https://github.com/user-attachments/files/16183424/tooltip_test_mrp.zip)

**Comment by akien-mga** [comment] 2024-07-11 21:08
CC @dalexeev

**Comment by dalexeev** [comment] 2024-07-12 06:47
* Duplicate of #72406.

This is not a recent regression, the bug is quite long-lived. The worst part is that documentation is not always available even for loaded scripts, so tooltips may be missing in the Inspector.

Also, there is a more global problem that scripts are loaded/compiled on demand. So, documentation may be missing in Editor Help Search, and doc links to unloaded scripts will not work. We probably need a cache.

**Comment by jake-abed** [comment] 2024-07-12 14:22
Apologies, in testing I could have sworn it was not a problem in 4.2.x; it very clearly is. Maybe there was some behavior that I was doing that was causing scripts to compile/load without the saving? I have to head into work, but I'll take a look and try to recreate the expected behavior really quickly.

I'll keep putzing around and see what I can find.

**Comment by dalexeev** [comment] 2024-07-12 15:19
The following code works well when you run Godot with the `--gdscript-docs` flag. But I'm not sure that using something like this every editor run would be good for performance.

https://github.com/godotengine/godot/blob/97b8ad1af0f2b4a216f6f1263bef4fbc69e56c7b/main/main.cpp#L3703-L3732

**Comment by akien-mga** [comment] 2024-07-18 10:01
Consolidating in #72406 / #86577.

**Closed by akien-mga** 2024-07-18 10:01 UTC
Labels: bug, topic:editor, regression
