### ISSUE TITLE
HTML export with strange color profile on Firefox

### ISSUE THREAD

**Issue by henriiquecampos** [godotengine/godot#13985] opened 2017-12-04 23:56 UTC
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Windows x64 Godot 3.0 beta (https mirror available @ [godotengine.org/](https://godotengine.org/article/dev-snapshot-godot-3-0-beta-1). GeForce GTX 660

**Issue description:**
For some reason, the HTML release changes the color profile for all `*.png`. It also doesn't overwrite some custom colors for `Labels`. This only occurs within Firefox (Firefox Quantum 58.0b8 (64-bit)), when playing it within Google Chrome (62.0.3202.94 (Official Build) (64-bit)) the graphics are fixed but the sound effects have a small, but perceptible delay.

Here the Firefox version:
![image](https://user-images.githubusercontent.com/10171059/33582672-7b8ef2da-d93d-11e7-93da-0bc30715bd34.png)

And Chrome:
![image](https://user-images.githubusercontent.com/10171059/33582702-9b22f1d2-d93d-11e7-8296-0156808993f0.png)

**Steps to reproduce:**
1. Make a game with .png images
2. Test an HTML export using Firefox

**Link to minimal example project:**
**Not promoting myself** but you can check it at the very [itch.io game page](https://pigdev.itch.io/tillagefever) :P

**Comment by CowThing** [comment] 2017-12-05 00:28
I'm using Firefox 57.0.1 (64-bit) and the colors are correct.

**Comment by henriiquecampos** [comment] 2017-12-05 00:40
That's weird, I tested @NathanLovato entry and seems like it has the same color profile in both Firefox and Chrome, but for some reason mine is...like if I didn't fit the cartridge correctly into SNES 🤔

**Comment by Superwaitsum** [comment] 2017-12-05 02:08
Can confirm color changing and flickering in Firefox 59 Nightly, in Chromium 61 there are no errors. (In the itch.io page)

**Comment by akien-mga** [comment] 2017-12-05 08:07
The colors are correct for me on Firefox Nightly (59.0a1 (2017-12-04) (64-bit)).

**Comment by bruvzg** [comment] 2017-12-05 08:35
macOS FF 57.0.1 (64-bit), Chrome 62.0.3202.94 (64-bit); Android FF 58.0b colours are correct, no flickering.

**Comment by Superwaitsum** [comment] 2017-12-05 13:25
After disabling ANGLE for webgl, it looks good but only for a second before it becomes all black (due to driver problems?), also this only happens the first time opening the game or after cleaning history, afterwards it's black always. So it may be an ANGLE problem in Firefox. (forgot to add I use Windows x64, AMD 7660d)

**Comment by akien-mga** [comment] 2017-12-11 09:37
Any idea what could cause this to be system and browser-specific @eska014 ?

**Comment by Vorion86** [comment] 2017-12-11 19:15
If it's related to ANGLE, maybe it's this bug? https://bugs.chromium.org/p/chromium/issues/detail?id=792966
It only seems to appear on Firefox 57+ and Chrome 63+, and only on Windows as far as I know. I currently don't have the time to test it with Godot though, so I could be wrong.

**Comment by henriiquecampos** [comment] 2017-12-11 20:11
@Vorion86 I can confirm the bug you linked happen in my firefox, but doesn't happen in my chrome seems like there's something to do with this and the bug matches the bug described by the user who reported this bug

**Comment by Superwaitsum** [comment] 2017-12-12 04:45
The bug @Vorion86 mentioned is related, but demo is ok (gray) in Firefox Nightly (2017-12-11) for me.
Thanks to this bug i found a bug marked as duplicated that is the same bug as this (has a duplicated at https://bugzilla.mozilla.org/show_bug.cgi?id=1424258)
The test project of this bug is a rectangle formed by 2 colored triangles, this fails with ANGLE but works ok without it.
After bisecting Firefox (Testing both the rectangle example and Tillage Fever), I found that Tillage Fever is affected by the same bug. 
Also found the corresponding pushlog that mentions several ANGLE changes:
https://hg.mozilla.org/integration/mozilla-inbound/pushloghtml?fromchange=fd1fe0931730ae57be8aee0969183be0121e2857&tochange=07f89c0d5e17fa3ca705af27da878fd3211d52f4

So it's ANGLE confirmed (at least on Windows, since #13998 was on Ubuntu, but it consists of artifacts).

**Comment by akien-mga** [comment] 2018-01-05 14:02
So I guess we'll just have to wait for ANGLE/browsers bug fixes?

**Comment by akien-mga** [comment] 2018-01-08 15:34
Can't block 3.0 if it's a browser vendor bug, so kicking to 3.1.

**Comment by Superwaitsum** [comment] 2018-01-09 23:35
Tested it today on Firefox Nightly 59.0a1 (2018-01-09) (64-bits) (Windows), and the color profile is fixed. Not sure if the fix will be added to Firefox 58 tought. I think it can be safely removed from milestone 3.1

**Comment by henriiquecampos** [comment] 2018-01-10 00:58
Yep, it seems like it is fixed on firefox 58.0b14 (64-bit)! I think that +1 confirmation would be enough to close the issue
![image](https://user-images.githubusercontent.com/10171059/34750846-7ef610ba-f590-11e7-90f8-ffb3754dd50e.png)

**Comment by akien-mga** [comment] 2018-01-10 06:50
Awesome :)

**Closed by akien-mga** 2018-01-10 06:50 UTC
Labels: bug, confirmed, platform:html5, topic:rendering
