### ISSUE TITLE
iOS `sensor_landscape` orientation only allows landscape left orientation

### ISSUE THREAD

**Issue by narunsa** [godotengine/godot#28848] opened 2019-05-13 10:38 UTC
**Godot version:**
3.1

**OS/device including version:**
Ipad ios 11.3.1

**Issue description:**
In project setting > handheld > orientation = landscape
In Export > IOS > orientation > check on landscape left and landscape right

Issue 1. After build my game ipad, it can't rotate. it stuck in landscape left.
Issue 2. So i try to build my game with only landscape right so i check only landscape right. image below

![IMG_0092](https://user-images.githubusercontent.com/6898374/57615415-d2e83e00-75a5-11e9-997f-a45f9a8e58c2.PNG)

**Comment by Benoit9** [comment] 2019-06-19 06:48
I have the same issue. Changing the orientation in Xcode directly gives the same results (stuck in landscape left, or portrait with black bar).

**Comment by Benoit9** [comment] 2019-06-19 07:17
In Project Settings > Handheld > Orientation : sensor 
worked for me.

**Comment by narunsa** [comment] 2019-06-19 10:05
@Benoit9 I change to sensor_landscape, It worked too

**Comment by BastiaanOlij** [comment] 2019-06-24 12:06
One of these days these things should be unified, when the settings in xcode do not line up with the setting in projects things get wonky. I've run into this a few times with ARCore and ARKit (yes the same issue exists on Android)

Easier said then done though :)

**Comment by levis501** [comment] 2020-06-13 05:02
Suggestion: add a tooltip in the export settings pointing to the project settings.  e.g. "See also: Project Settings > Display > Window > Handheld > Orientation"

**Comment by Calinou** [comment] 2020-06-13 11:30
@levis501 Unfortunately, export preset settings can't have tooltips yet, so we'd have to implement that feature to display a tooltip.

**Comment by NanitesNanites** [comment] 2022-03-28 14:25
I run into the same thing, Orientation in Project Settings is set to sensor_landscape, the Orientation setting in Export seems to not exist anymore in 3.4.4, and the game ist stuck on landscape left on IOS (on Android, it rotates between landscape left and right as intended). Is it still possible to fix it by changing any other setting?

**Comment by Calinou** [comment] 2022-03-28 14:30
> the Orientation setting in Export seems to not exist anymore in 3.4.4,

See https://github.com/godotengine/godot/pull/48943.

**Comment by NanitesNanites** [comment] 2022-03-28 16:53
@Calinou 
MRP attached:
[OrientationTest.zip](https://github.com/godotengine/godot/files/8364752/OrientationTest.zip)

just a simple scene with an arrow to indicate orientation. Orientation in Project Settings is set to sensor_landscape. I also checked in XCode that both Landscape Left and Right are checked when importing the project, and they are, but the screen always stay at Landscape Left.

**Comment by Calinou** [comment] 2022-04-28 15:30
I wonder if the issue is here: https://github.com/godotengine/godot/blob/59e84be9b5137877b415d1c57349f4fa5a67897a/platform/iphone/view_controller.mm#L201-L202

Unlike `SCREEN_SENSOR_PORTRAIT`, there is no bitwise `OR` performed to combine LandscapeLeft and LandscapeRight.

**Comment by naithar** [comment] 2022-04-29 17:21
> I wonder if the issue is here:
> 
> https://github.com/godotengine/godot/blob/59e84be9b5137877b415d1c57349f4fa5a67897a/platform/iphone/view_controller.mm#L201-L202
> 
> Unlike `SCREEN_SENSOR_PORTRAIT`, there is no bitwise `OR` performed to combine LandscapeLeft and LandscapeRight.
> 
> In contrast, you can see that the Xcode generator adds both options:
> 
> https://github.com/godotengine/godot/blob/59e84be9b5137877b415d1c57349f4fa5a67897a/platform/iphone/export/export.cpp#L576-L580
> 
> This quirk is present in both `master` and `3.x` (but I linked to `3.x` code here).
> 
> cc @naithar @bruvzg

`UIInterfaceOrientationMaskLandscape` is basically a shorthand for `UIInterfaceOrientationMaskLandscapeLeft | UIInterfaceOrientationMaskLandscapeRight` [link](https://developer.apple.com/documentation/uikit/uiinterfaceorientationmask/uiinterfaceorientationmasklandscape/), so it should be working correctly.

It also seems like the problem can be reproduced in `Debug` mode only. When running compiled app directly on device orientation changes correctly.

**Comment by naithar** [comment] 2022-04-29 19:22
Adding `[[UIDevice currentDevice] beginGeneratingDeviceOrientationNotifications];` at the start of `- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions` in `AppDelegate` fixes orientation change in `Debug` build.

**Comment by akien-mga** [comment] 2023-02-22 10:58
Is this still reproducible in 4.0 RC 3 or later? CC @bruvzg

**Comment by bruvzg** [comment] 2023-02-22 11:43
> Is this still reproducible in 4.0 RC 3 or later? CC @bruvzg

`sensor_landscape` seems to be working fine and rotate between both landscape orientations (tested on 10th gen iPad).

**Closed** 2023-02-22 12:15 UTC
Labels: bug, platform:ios, topic:porting, confirmed
