### ISSUE TITLE
Video playback freezes when using Webm

### ISSUE THREAD

**Issue by Takuyax** [godotengine/godot#19198] opened 2018-05-27 09:38 UTC
**Godot version:**
3.0.2 stable

**OS/device including version:**
ubuntu 16.04 LTS

**Issue description:**
What happened:
When playing back some VP9 encoded Webm videos in a VideoPlayer node, video playback freezes. This happens with videos that are CPU intense, in my case 60 fps videos at 1280x720* pixel resolution. At first video playback runs perfectly smooth, then just freezes. This makes it seem like the decoder crashed due to a skipped frame. Trying to restart playback with $VideoPlayer.stop() and $VideoPlayer.play() doesn't work.

* Since this issue seems to depend on CPU speed, I encoded the video in the attached scene in 1080p resolution, to make the issue easier to reproduce.

What was expected:
When video decoding lags behind, the decoder should skip frames and re-synchronize with the audio.

**Steps to reproduce:**
a)
1. Load the provided test scene and run it.
2. Notice that Video playback freezes after a short time. (If not reproducible, try a slower CPU. In my case it was 100% reproducible on an i7-4930K running at 3.4 GHz.)
3. Notice that the Play/Stop button can't restart the video playback.

b)
1. Prepare a high fps, high resolution video. (E.g. 1080p, 60 fps)
2. Encode it to VP9 in a Webm container. (E.g. with ffmpeg: ffmpeg -i test.mov -pix_fmt yuv420p -c:v libvpx-vp9 -crf 30 -b:v 0 -deadline good -c:a libvorbis -b:a 128k test.webm)
3. Create a new project in Godot.
4. Import the webm file.
5. Add a VideoPlayer node.
6. Set the VideoPlayer to play the webm file.
7. Enable Autoplay for the VideoPlayer.
8. Run the scene.
8. Notice that Video playback freezes after a short time.

**Minimal reproduction project:**
Uploaded externally, due to big size (26.7 MB): https://drive.google.com/open?id=1dcYsdgCLLRkb1YR0x9QyNGtDX0jTbyvu

**Comment by Calinou** [comment] 2018-05-27 10:10
While this is a bug, do note that you could use the older VP8 codec to decrease CPU usage.

**Comment by madadam** [comment] 2018-06-20 11:35
I can confirm this bug. My workaround for now is to use Theora (ogv) videos, which don't seem to suffer from this issue.

**Comment by qarmin** [comment] 2019-12-26 09:57
I have only black screen.
It stuck in swap_buffers like in #33472

**Comment by Takuyax** [comment] 2020-02-02 00:15
I can confirm the black screen with 3.2 stable on Kubuntu 18.04. Sound plays, the stream_position value increases as expected, and I can control the playback, but the video output always stays black.

**Comment by YounesThabet** [comment] 2020-05-05 23:17
@qarmin @Takuyax still no fix for black screen with 3.2 stable!!
did you guys find any workaround for this issue?

**Comment by Takuyax** [comment] 2020-05-08 16:15
> @qarmin @Takuyax still no fix for black screen with 3.2 stable!!
> did you guys find any workaround for this issue?
Silent video playback works for me since version 3.2.1, after this fix: https://github.com/godotengine/godot/pull/35993
However the problem still occurs for me in 3.2.1 if the video has an audio track. I haven't tried the 3.2.2. beta yet.

**Comment by marcusmmmz** [comment] 2021-02-16 19:43
Why hasn't this been fixed yet...
Kubuntu 20.4: works as expected in dev, but in build only the audio plays
Windows 10: build crashes, didn't test it in dev
Yes, using OGV is a plausible workaround but webm files are way smaller so there's still reason to fix this
Maybe 3.2.5 or even 3.2.4?

**Comment by Calinou** [comment] 2021-02-16 20:16
Duplicate of https://github.com/godotengine/godot/issues/33472.

**Closed by Calinou** 2021-02-16 20:16 UTC
Labels: bug, confirmed, topic:core

**Comment by Lawrenceku** [comment] 2023-06-02 02:55
The error is still persistent in godot 3.4.4 stable version...using webm seems to be the only solution, however the .ogv format uses compression algorithms to reduce the file size of the video leaving the video compromized, in simple terms it LAGS...
