### ISSUE TITLE
Error selecting Stretch mode=2d

### ISSUE THREAD

**Issue by GrandFunkR** [godotengine/godot#8221] opened 2017-04-01 14:21 UTC
**Operating system or device - Godot version:**
Linux
Godot 3.0 master

**Issue description:**

selecting 
Stretch mode = 2d
aspect=keep

window remains black and have this error:

ERROR: _gl_debug_print: GL ERROR: Source: OpenGL Type: Error     ID: 11  Severity: High  Message: GL_INVALID_VALUE in glViewport(0, 0, 720, -2147483648)
                                                                                                                                                                                          At: drivers/gles3/rasterizer_gles3.cpp:122.

**Steps to reproduce:**
create new project
set 

Stretch mode = 2d
aspect=keep

**Link to minimal example project:**

**Comment by Zylann** [comment] 2017-04-01 15:50
Duplicate of #8138?

**Comment by Hinsbart** [comment] 2017-04-02 08:15
closing as dupe of #8138.

**Closed by Hinsbart** 2017-04-02 08:15 UTC
Labels: bug, topic:rendering
