### ISSUE TITLE
3D Physics: Continuous Collision Detection fails regularly

### ISSUE THREAD

**Issue by michael-nischt** [godotengine/godot#69676] opened 2022-12-06 17:18 UTC
### Godot version

v4.0.beta7.official [0bb1e89fb]

### System information

Arch Linux, GeForce 3080

### Issue description

3D Physics: Continuous Collision Detection fails regularly when enabled on a rigid body.

https://user-images.githubusercontent.com/500820/205977754-3e2e6baa-3b09-4919-8d4f-5495d6fbe8c2.mp4

### Steps to reproduce

Launch and play the attached project.

Hold SPACE to apply a force to the ball until it tunnels through a mesh collider and two adjacent box colliders.

The `ball.gd` script has a 
```gdscript
const TUNNEL : bool = true
```

with that set to false the static bodies are positions slightly different the ball collides as expected.

### Minimal reproduction project

[TunnelBug3D.zip](https://github.com/godotengine/godot/files/10168693/TunnelBug3D.zip)

**Comment by rick551a** [comment] 2022-12-06 19:17
To solve:
Make the collision shape convex on your ball.

How:
1) Delete the collision shape you have now for the ball

2) Click the mesh in the node tree, click the 'mesh' button and on the dropdown click 'Create simplified convex collision sibling'
, or append -convcol to object name in blender to get a convex shape on import

Observe, it works!


Note: 
Had this 'issue' in 3.x too, maybe a note in the help files is required, about convex collisions etc.

**Comment by michael-nischt** [comment] 2022-12-06 21:29
> To solve: Make the collision shape convex on your ball.
> 
> How:
> 
>     1. Delete the collision shape you have now for the ball
> 
>     2. Click the mesh in the node tree, click the 'mesh' button and on the dropdown click 'Create simplified convex collision sibling'
>        , or append -convcol to object name in blender to get a convex shape on import
> 
> 
> Observe, it works!
> 
> Note: Had this 'issue' in 3.x too, maybe a note in the help files is required, about convex collisions etc.

Thanks for sharing a possible the workaround! :pray: 

I'm not sure though it will have other issues in our main project. Like having the ball not roll smoothly on the ground. Maybe having two collisions shapes, the simplified convex shape and the sphere (slightly bigger) will work. I will try tomorrow.

Anyway, it is only a workaround. I mean there's no good reason why the sphere, a simpler shape and pure geometric convex shape, should not be equally or even more precise (and performant), right?

**Comment by Calinou** [comment] 2022-12-06 22:15
Duplicate of https://github.com/godotengine/godot/issues/9071.

**Closed by Calinou** 2022-12-06 22:15 UTC

**Comment by michael-nischt** [comment] 2022-12-07 11:11
Sadly the workaround doesn't work in the actually project. It believe decreased the likelihood a bit but still going through walls despite lower forces/speeds than the mini project. :disappointed:

**Comment by Calinou** [comment] 2022-12-07 16:17
Increasing physics FPS is usually the best way to combat tunneling, but don't pick a value that's too high (and prefer values that are multiples of 60 when not using physics interpolation, such as 120, 180 or 240).

**Comment by michael-nischt** [comment] 2022-12-07 16:54
Well, I tried 240 and it didn't happen often but still every now and then. Sadly any tunneling would be game breaking for us.

My new approach is to write my own physics simulation on top of Godot's `move_and collide` (which always prevents tunneling) by moving one object at a time.
So far already works flawlessly with static colliders / objects and handles [bouncing.](https://github.com/godotengine/godot/issues/69667) too. 
Hope I can add support for interacting with rigid body like objects with energy transfer and all later this week. :crossed_fingers:
