### ISSUE TITLE
Exported project fails to start when UID is saved in project settings

### ISSUE THREAD

**Issue by BastiaanOlij** [godotengine/godot#100354] opened 2024-12-13 11:43 UTC
### Tested versions

- Reproducible in Godot master (c2e4ae782a399adf42c664d3d21d8defe49ba8e5)

### System information

Windows 10

### Issue description

If you set the main scene through the project manager dialog Godot now saves the UID in the project file:
```
config_version=5

[application]

config/name="test-export"
run/main_scene="uid://dg450amr7gaby"
config/features=PackedStringArray("4.4", "GL Compatibility")
config/icon="res://icon.svg"
```

This works fine in the editor but after exporting your project, Godot can no longer run the project:
```
PS C:\projects\export> Godot Engine v4.4.dev.custom_build.c2e4ae782 (2024-12-11 17:48:18 UTC) - https://godotengine.org
OpenGL API 3.3.0 NVIDIA 566.03 - Compatibility - Using Device: NVIDIA - NVIDIA GeForce RTX 4070 Ti

ERROR: No loader found for resource: res://uid:/dg450amr7gaby (expected type: )
   at: (core\io\resource_loader.cpp:327)
ERROR: Failed loading scene: res://uid:/dg450amr7gaby.
   at: (main\main.cpp:4214)
```

The fault is caused by this line of code:
```
editor_node.cpp:3973 if (!p_force_open_imported && FileAccess::exists(p_scene + ".import")) {
```
It attempts to load the file `res://uid:/dg450amr7gaby.import` which does not exist.

### Steps to reproduce

- Create a new project
- Create a scene, add some stuff to it
- Save the scene
- Select the scene as your main scene in the project manager (IMPORTANT, If you run your scene and select "use current scene" it will save the proper file path and work)
- Export your project

### Minimal reproduction project (MRP)

[test-export.zip](https://github.com/user-attachments/files/18125819/test-export.zip)

**Comment by KoBeWi** [comment] 2024-12-13 14:12
> The fault is caused by this line of code:
editor_node.cpp:3973 if (!p_force_open_imported && FileAccess::exists(p_scene + ".import")) {

How can it cause the bug if it's editor code?

**Comment by KoBeWi** [comment] 2024-12-13 14:53
Then the error would appear during export, but it's not the case.
There are two issues here and the description is mixed up. The quoted line causes error on editor startup, if no scene was restored (so it tries to open main scene)

**Comment by BastiaanOlij** [comment] 2024-12-14 06:49
Owh that last bit might be a fluke of testing on my end, I might have run it with a dev/editor build to try and trap the error as with a runtime build it just quits silently.

**Comment by BastiaanOlij** [comment] 2024-12-14 06:50
The bottom line is:
- exporting the project with the UIDs in the `project.godot` file -> exported project fails to load and just quits
- editing the `project.godot` to add proper paths (or select "use current scene" when running a project) -> exported project works

**Comment by BastiaanOlij** [comment] 2024-12-14 07:03
Just to rule out there is an issue with my custom build. Just reproduced this with Godot 4.4 dev 6 with the following steps:

1. Download Godot 4.4 dev 6 and run
2. Create a new project
3. Download export templats
4. Create a new scene, add `DirectionalLight3D`, `WorldEnvironment`, `Camera3D` and `MeshInstance3D` with a `BoxMesh` to create the most basic scene possible
5. Save this scene
6. Open project manager, select Run, set the main scene to the scene you just saved
7. Press run button in toolbar to test, project works
8. Open export window
9. Add `Windows Desktop` export preset
10. Press Export Project and save the project in a new folder
11. Run the exported project, project fails to load.

**Comment by matheusmdx** [comment] 2024-12-14 14:57
Just a detail, this seems to be a duplicate of #100084 but this one has more detail, maybe is good consolidate everything here or at least keep an eye to close both when the fix is done.

**Comment by markushaslinger** [comment] 2024-12-15 14:23
I ran into this issue today as well.

Not sure if related at all, but I had a similar problem with the splash screen: when set via the project dialogue it entered the uid which then failed to resolve at start in the exported version. Changed it manually in the `project.godot` file to the path and it works now.
Thought I'd mention it here, because it looks similar in cause & behaviour for someone unfamiliar with the code, but might be totally unrelated or even simple user error.

**Comment by KoBeWi** [comment] 2024-12-15 14:46
The splash screen was fixed recently.

**Comment by Wolve-3DTech** [comment] 2024-12-15 20:26
Hi everyone ! I've just encountered the same issue as @BastiaanOlij. Glad to see that this issue is being addressed !

**Comment by Wolve-3DTech** [comment] 2024-12-15 20:27
And this issue does occur in Godot 4.4dev6

**Closed** 2024-12-17 15:23 UTC
Labels: bug, regression, topic:export
