### ISSUE TITLE
getting random OS freezes while using godot

### ISSUE THREAD

**Issue by Miziziziz** [godotengine/godot#37928] opened 2020-04-16 08:24 UTC
**Godot version:** both 3.2 and 3.2.1

**OS/device including version:** Ubuntu 19.10, kernel 5.3.0-46 generic, does not happen on 5.3.0-45

Happens with both nouveau drivers and proprietary version 430

**Issue description:** occasional OS freezes while using godot, lasts a few seconds, audio works fine, sometimes mouse cursor freezes.
Good description of issue here: https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1872001

kern.log shows this when it happens:
[ 3586.874215] i915 0000:00:02.0: GPU HANG: ecode 9:0:0x00000000, hang on rcs0
[ 3586.875240] i915 0000:00:02.0: Resetting rcs0 for hang on rcs0

happens randomly, sometimes doesn't happen for an hour, others happens every couple of minutes

**Steps to reproduce:**
make a project and work in it for a while

**Comment by Calinou** [comment] 2020-04-16 08:33
This is likely a kernel/driver regression. Does it occur with other 3D applications and games?

**Comment by Miziziziz** [comment] 2020-04-16 08:44
Only other 3d application I've tried is blender and it works fine

**Comment by Ev1lbl0w** [comment] 2020-04-16 15:37
I've seen this exact issue on my setup: you'll have to update to a newer kernel *(at least 5.5)*, but I don't think that's an option in Ubuntu.

If you can go back to 5.3.0-45, stay there until there's an Ubuntu version with kernel 5.5.

**Comment by jhonnystene** [comment] 2020-04-18 21:57
Having the same issue with Godot 3.1, 3.2, and 3.2.1 on Ubuntu 19.10, Arch, and ElementaryOS.

**Comment by Calinou** [comment] 2020-04-18 22:39
@jhonnystene Can you reproduce this in other 3D applications and games?

**Comment by jhonnystene** [comment] 2020-04-18 23:12
@Calinou I've tried in OpenSCAD, Blender, and Minecraft. The problem only happens in Godot. It can happen for me in all views the editor, as well as in the project list sometimes.

**Comment by Ev1lbl0w** [comment] 2020-04-19 10:44
@jhonnystene are you getting errors on your `journalctl` for the `i915` driver? Something on the lines of:

```
Dez 08 00:18:20 cynecx kernel: i915 0000:00:02.0: GPU HANG: ecode 9:1:0x00000000, hang on rcs0
Dez 08 00:18:20 cynecx kernel: GPU hangs can indicate a bug anywhere in the entire gfx stack, including userspace.
Dez 08 00:18:20 cynecx kernel: Please file a _new_ bug report on bugs.freedesktop.org against DRI -> DRM/Intel
Dez 08 00:18:20 cynecx kernel: drm/i915 developers can then reassign to the right component if it's not a kernel issue.
Dez 08 00:18:20 xxx kernel: The GPU crash dump is required to analyze GPU hangs, so please always attach it.
Dez 08 00:18:20 xxx kernel: GPU crash dump saved to /sys/class/drm/card0/error
Dez 08 00:18:20 xxx kernel: i915 0000:00:02.0: Resetting rcs0 for hang on rcs0
Dez 08 00:18:20 xxx kernel: [drm:gen8_reset_engines [i915]] *ERROR* rcs0 reset request timed out: {request: 00000001, RESET_CTL: 00000001}
Dez 08 00:18:20 xxx kernel: i915 0000:00:02.0: Resetting chip for hang on rcs0
```

(If you can't do anything when your computer freezes, reboot and do `journalctl -b -1` to access the last journal)

**Comment by jhonnystene** [comment] 2020-04-19 22:02
@Ev1lbl0w Usually, I only get this line repeated a couple of times when it freezes:
`[21736.872688] i915 0000:00:02.0: Resetting rcs0 for hang on rcs0`

Once in a blue moon, it will also show this at the start:
`[ 3034.766150] i915 0000:00:02.0: GPU HANG: ecode 9:0:0x00000000, hang on rcs0`

**Comment by Ev1lbl0w** [comment] 2020-04-20 11:43
That looks like the issue I've mentioned. You've mentioned you tried this on Arch: were you on the latest kernel *(or at least >=5.5)*?

**Comment by jhonnystene** [comment] 2020-04-20 15:18
I think i was above 5.5, I'll update to the latest kernel and report back.

**Comment by Calinou** [comment] 2020-04-20 16:57
I think we should close this issue as it's not related to Godot.

**Closed** 2020-04-20 16:58 UTC
Labels: bug, platform:linuxbsd, topic:core
