### ISSUE TITLE
Build Does Not Detect C# Extensions (or any .cs files that do not contain nodes)

### ISSUE THREAD

**Issue by 11clock** [godotengine/godot#14932] opened 2017-12-22 07:02 UTC
**Godot version:**
3.0 beta 2

**OS/device including version:**
Windows

**Issue description:**
When you make an extension method in another .cs class, build fails because it cannot find the extension you are attempting to reference.

**Steps to reproduce:**
1. Create a .cs file with an extension to any node or whatever.
2. In a node script, reference the extension. Note that VS Code sees this as valid.
3. In the editor, play the game.

EDIT: I did more research and it looks like that Godot neglects to include .cs files in the solution that do not contain nodes. This is undesirable.

**Comment by neikeq** [comment] 2017-12-22 17:10
I assume you created it from VS Code, which does not update the csproj. Godot cannot assume the file is part of the game csproj (you could have other C# projects). Godot only makes this assumption when creating the script from the Godot editor, when the script is attached to a node and when the script is used as an AutoLoad (this last one is pending :smile:).

You must either create the script from Godot or use an IDE like MonoDevelop or Visual Studio.

BTW, I plan to add a panel to view and edit includes and references in the game project, in order to make it friendlier than editing the project file. This will happen after 3.0 though.

**Comment by akien-mga** [comment] 2018-01-05 11:37
We have now entered release freeze for Godot 3.0 and want to focus only on release critical issues for that milestone. Therefore, we're moving this issue to the 3.1 milestone, though a fix may be made available for a 3.0.x maintenance release after it has been tested in the master branch during 3.1 development. If you consider that this issue is critical enough to warrant blocking the 3.0 release until fixed, please comment so that we can assess it more in-depth.

**Comment by 11clock** [comment] 2018-01-06 06:18
The VS code extension is a decent workaround until then, although not perfect. I can wait.

**Comment by 11clock** [comment] 2018-06-27 20:21
Are there any updates on this issue?

**Comment by exts** [comment] 2018-06-27 21:59
@neikeq can you update the title of this issue to reflect the actual issue since c# extensions actually work fine with godot. This is a file being included in the csproj file issue w/ vscode/godot editor. Which is a non issue in most IDE's.

**Comment by PJB3005** [comment] 2018-07-02 16:32
I can't say I've tested this, but a workaround for this, although kinda hacky, is to add the following line before the `</Project>` in your `.csproj` file:
```xml
<ItemGroup>
  <Compile="**\*.cs" />
</ItemGroup>
```

This should make msbuild automatically compile all `.cs` files without having to manually add them to the `.csproj`, so kinda like a .NET Core project.

You can also Make it only do specific directories by making `<Compile>` entries for specific folders, probably: `<Compile="src\**\*.cs" />`

**Comment by neikeq** [comment] 2018-07-03 02:51
I guess the best will be to watch the project directory for source files added or removed outside the Godot editor and show a dialog asking for confirmation from the user to apply these actions to the project.

**Comment by akien-mga** [comment] 2019-01-19 13:37
Related to #12917.

**Comment by nuke-makes-games** [comment] 2019-02-27 14:28
Might be worth adding some sort of Godot option to generate the csproj with the wildcard to grab all C# files. I know i've been struggling with my csproj sometimes missing files, i'd have certainly opted for something more automated if given the option.

**Comment by phelioz** [comment] 2019-11-17 08:08
> I can't say I've tested this, but a workaround for this, although kinda hacky, is to add the following line before the `</Project>` in your `.csproj` file:
> 
> ```
> <ItemGroup>
>   <Compile="**\*.cs" />
> </ItemGroup>
> ```
> 
> This should make msbuild automatically compile all `.cs` files without having to manually add them to the `.csproj`, so kinda like a .NET Core project.
> 
> You can also Make it only do specific directories by making `<Compile>` entries for specific folders, probably: `<Compile="src\**\*.cs" />`

Worked great for me :) But had to change it to following to get the project to compile.

```
<ItemGroup>
    <Compile Include="**\*.cs" />
</ItemGroup>
```

**Comment by aaronfranke** [comment] 2020-10-06 20:43
Please re-test with Godot 3.2.3 and/or the master branch. Both of these use the new C# project format, so issues related to the `csproj` file might just not exist anymore. Also, check if you have the latest Mono and .NET Core.

As of Godot 3.2.3, using this as your `csproj` should automatically include every C# file:

```csproj
<Project Sdk="Godot.NET.Sdk/3.2.3">
  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
  </PropertyGroup>
</Project>
```

If this issue does still exist for you, then you will need to include a minimal reproduction project.

**Comment by Tobi-Mob** [comment] 2021-09-10 17:59
> Please re-test with Godot 3.2.3 and/or the master branch. Both of these use the new C# project format, so issues related to the `csproj` file might just not exist anymore. Also, check if you have the latest Mono and .NET Core.
> 
> As of Godot 3.2.3, using this as your `csproj` should automatically include every C# file:

Works for me in Godot 3.3.3 as you said.
A new Godot project uses the new csproj format which does not has this issue.

**Comment by Calinou** [comment] 2021-09-10 18:34
Closing as resolved per @Tobi-Mob's comment. Thanks for testing 🙂

**Closed by Calinou** 2021-09-10 18:34 UTC
Labels: bug, topic:mono
