### ISSUE TITLE
PoolVector[23]Array method to get distance between vertices (for A*)

### ISSUE THREAD

**Issue by Timofffee** [godotengine/godot#12615] opened 2017-11-03 19:17 UTC
It's easy to add, but it is strange that these functions no. 
I understand that it is easily implemented in GDscript, but sometimes I just don't want to clutter up the scripts short functions.

- Find the sum of distances of all vectors in PoolVector2Array / PoolVector3Array. 
```
# GDScript 3.0
func _ready():
	var pv3a = PoolVector3Array ()
	
	pv3a.append(Vector3(13,7,3))
	pv3a.append(Vector3(32,3,1))
	pv3a.append(Vector3(44,3,7))
	pv3a.append(Vector3(89,6,4))
	
	print (get_distance(pv3a)) # 78.135186

func get_distance(arr): # This function
	var arr_dist = 0
	for i in arr.size() - 1:
		arr_dist += arr[i].distance_to(arr[i + 1])
	return arr_dist
```
- Vector3 to Vector2 and vice versa.  *Bugsquad edit:* Duplicate of #6861.
```
# GDScript 3.0
func _ready():
	print (to_vector2(Vector3(30, 10, 0))) # Vector2(30, 10)
	print (to_vector3(Vector2(24, 3))) # Vector3(24, 3, 0)

func to_vector2(vec):
	return (Vector2(vec.x, vec.y))

func to_vector3(vec):
	return (Vector3(vec.x, vec.y, 0))
```
(Yes it's not ideal, but probably there is an option to add a selection of axes.)

**Comment by Zireael07** [comment] 2017-11-03 20:08
+1 to vector3 to vector2 and back.

**Comment by raymoo** [comment] 2017-11-04 06:49
Or support swizzling

**Comment by Adinimys** [comment] 2017-11-04 07:51
Isn't to_vector almost as long to type as what it does ? 
I don't know what is the policy of the engine on such "ease-of-use" functions. I could try implementing them if it was decided to be necessary, that will teach me how binding functions to GDScript works :)

**Comment by hubbyist** [comment] 2017-11-07 07:40
possible duplicate of #6861

**Comment by akien-mga** [comment] 2017-11-09 17:32
The Vector3 to Vector2 part is a duplicate of #6861 indeed. Rewording the title to focus on the first proposal (please make separate issues for each proposal next time).

**Closed** 2019-05-06 23:11 UTC
Labels: discussion, enhancement, topic:core
