### ISSUE TITLE
Add texture atlas support for SpriteFrames

### ISSUE THREAD

**Issue by alexzheng** [godotengine/godot#9340] opened 2017-06-24 05:34 UTC
**Operating system or device - Godot version:**
ALL

**Issue description:**

AnimationSprite is an easy way to create frame animations, but we can not put all the frame images in a single file.

**Steps to reproduce:**

**Link to minimal example project:**

**Comment by alexzheng** [comment] 2017-06-25 02:20
it would be better to support multiple animations in one sprite sheet.
For example, we can put walking, running and jumping frames in one sprite sheet, and set the "start frame" and "end frame" for each animation.
Thanks!

**Comment by bojidar-bg** [comment] 2017-06-25 11:30
@alexzheng Don't worry, we would probably go as far as to support texture atlases (unaligned frames) and using the frames in any order that one might want (which would imply being able to use only some of the frames of an animation).

**Comment by alexzheng** [comment] 2017-06-25 12:12
amazing

**Comment by timoschwarzer** [comment] 2017-07-02 06:00
Can't you just import all your frames into a single AtlasTexture and load the single .atex files into your SpriteFrames? This is what I'm doing and it works just fine.
Or do you mean something else?

**Comment by bojidar-bg** [comment] 2017-07-02 12:13
@timoschwarzer you can, but it isn't intuitive enough.

**Comment by timoschwarzer** [comment] 2017-07-02 12:20
What is your suggested way of doing it?
For me this way works just fine and is intuitive enough due to its flexibility.

**Comment by kubecz3k** [comment] 2018-04-03 11:28
First of all thank you for your report and sorry for the delay.

We released Godot 3.0 in January 2018 after 18 months of work, fixing many old issues either directly, or by obsoleting/replacing the features they were referring to.

We still have hundreds of issues whose relevance/reproducibility needs to be checked against the [current stable version](https://godotengine.org/download), and that's where you can help us.
**Could you check if the issue that you described initially is still relevant/reproducible in Godot 3.0 or any newer version, and comment about its current status here?**

For bug reports, please also make sure that the issue contains detailed steps to reproduce the bug and, if possible, a zipped project that can be used to reproduce it right away. This greatly speeds up debugging and bugfixing tasks for our contributors.

Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

Thanks in advance.

*Note: This message is being copy-pasted to many "stale" issues (90+ days without activity). It might happen that it is not meaningful for this specific issue or appears oblivious of the issue's context, if so please comment to notify the Bugsquad about it.*

**Comment by alexzheng** [comment] 2018-04-03 23:15
This new feature is still NOT provide in 3.0!

**Comment by dalexeev** [comment] 2019-02-16 20:19
The SpiteFrames editor would be even more convenient if you could open image, specify the number of rows and columns, and the frames would be automatically imported.

**Comment by piratesephiroth** [comment] 2019-03-03 18:21
Maybe not the exactly the solution you guys wanted but [I made a script](https://github.com/piratesephiroth/sprite-sheet-packer/blob/master/SpriteSheetPacker/defaultFormats/godot.js) for [Spritesheet Packer](https://github.com/amakaseev/sprite-sheet-packer) that allows publishing a spritesheet directly as an AnimatedSprite.

**Comment by KoBeWi** [comment] 2019-05-13 11:38
Fixed in 3f76d2c2

**Closed** 2019-05-13 11:42 UTC
Labels: confirmed, feature proposal, topic:core, topic:editor
