### ISSUE TITLE
Godot 3 do not import PBM files (no .import file) for Click Masks

### ISSUE THREAD

**Issue by nylnook** [godotengine/godot#14830] opened 2017-12-19 15:36 UTC
**Godot version:**
Archlinux 64b, Godot 3b1

**Issue description:**
TextureButtons Click Masks seem to be badly imported in Godot 3, and do not generate .import files in the project folder
This might  be the cause of #14828
See also #14700 for a sum-up in and a minimal project example

**Comment by reduz** [comment] 2017-12-26 15:08
This is not a bug, and seems to be a duplicate of #14700, so closing

**Comment by nylnook** [comment] 2017-12-26 16:42
As explained in #14828, we are speaking about PBM... @akien-mga asked me to separate feature proposal and bugs, which is why it is separated from #14700 ... please reopen !

**Comment by nylnook** [comment] 2018-01-03 09:38
thanks @akien-mga ;)

**Comment by reduz** [comment] 2018-01-06 19:39
PBM format is now gone, you can import an image as bitmap

**Closed by reduz** 2018-01-06 19:39 UTC
Labels: bug, topic:editor
