### ISSUE TITLE
LineEdit scroll offset does not update properly when changing text

### ISSUE THREAD

**Issue by lightbulbmeow** [godotengine/godot#82342] opened 2023-09-26 00:53 UTC
### Godot version

4.1.1.stable

### System information

Godot v4.1.1.stable - Ubuntu 22.04.2 LTS 22.04 - Vulkan (Forward+) - integrated AMD Unknown (RADV RENOIR) () - AMD Ryzen 5 4600H with Radeon Graphics (12 Threads)

### Issue description

When typing some long text into LineEdit, the text will scroll to the right, as expected. But once the user tries to replace the entire text with a shorter one, the new text will appear as if it isn't there.

The issue appears to be because the `scroll_offset` of the LineEdit doesn't get updated properly whenever text is edited.
The bug only happens with LineEdit, not with TextEdit.

### Steps to reproduce

1. Insert a new LineEdit.
2. In test play mode, type in a really long text into the textbox such as "WWWWWWWWWWWWWWWWWW"
3. Press Ctrl+A then Delete. (Using the Clear function will *not* produce the bug)
4. Type in some text. The first character won't appear.

### Minimal reproduction project

N/A

**Comment by jsjtxietian** [comment] 2023-09-28 11:06
Duplicate of #81411

**Comment by TheSofox** [comment] 2024-01-01 14:41
Confirmed that this bug is fixed in Godot v4.3.dev (13a0d6e9b). Most likely fixed by PR https://github.com/godotengine/godot/pull/81443 which was fixing duplicate bug #81411. Recommend this issue be closed.

**Closed** 2024-01-01 14:56 UTC
Labels: bug, topic:gui
