### ISSUE TITLE
Control mouse_filter "pass" option triggers mouse_entered and mouse_exited signals when entering/exiting a node on top  

### ISSUE THREAD

**Issue by fullmontis** [godotengine/godot#58998] opened 2022-03-10 20:47 UTC
### Godot version

3.4.3

### System information

Xubuntu 20.04

### Issue description

Let's take a Control node (called bottom) that has on top another smaller Control node with mouse_filter set to pass (called top). 

Whenever the mouse enters or exits top but and remains inside bottom, the mouse_entered and mouse_exited signals are both triggered for bottom.

Ideally, the mouse_entered and mouse_exited signals should only trigger when the mouse enters or exits bottom, and not when the mouse exits or enters top. 

### Steps to reproduce

1. Create Control node
2. Create new Control node over and inside the first one and set mouse_filter to "pass"
3. Move mouse in and out of the top Control node and check the mouse_entered and mouse_exited signals for the underlying Control node

### Minimal reproduction project

[bug-control-mouse.zip](https://github.com/godotengine/godot/files/8227038/bug-control-mouse.zip)

**Comment by Calinou** [comment] 2022-03-10 21:01
This may be a duplicate of https://github.com/godotengine/godot/issues/16854, which was considered intended behavior and is now documented. cc @KoBeWi

**Comment by KoBeWi** [comment] 2022-03-10 21:14
Yes, duplicate of #16854
`mouse_filter` is irrelevant, it only affects input events.

**Closed by KoBeWi** 2022-03-10 21:14 UTC
Labels: topic:gui
