### ISSUE TITLE
GraphEdit. Bad key name in get_connection_list() dictionary

### ISSUE THREAD

**Issue by Lexpartizan** [godotengine/godot#40322] opened 2020-07-12 18:55 UTC
This is a small problem that can hardly be called a error. More like inattention. When we use the connect_node(from, **from_slot**, to,**to_slot**) or disconnect_node(from,**from_slot** to,**to_slot**) functions in such graphedit, we use from_slot and to_slot .  get_connection_list () return array structure of the form {**from_port**: 0, from: "graphnode name 0", **to_port**: 1, to: "graphnode name 1" }. 
In one case, we refer to ports, and in the other to slots, although they are the same entity.

I suggest changing the key names in the get_connection_list () function to from_slot and to_slot to avoid confusion. 
I think that with the transition to the new major version 4.0, you can fix this and break compatibility.
Or duplicate this keys to from_slot and to_slot to maintain compatibility.

It might have been worth adding to the proposal, but I don't think it's a suggestion, it's a correction of an error that was made inattentively. So I write about it here.

**Comment by Calinou** [comment] 2020-07-12 20:27
Renaming parameters can be done without breaking backwards compatibility :slightly_smiling_face:

**Comment by mrushyendra** [comment] 2020-07-15 08:17
Related to #40043

**Comment by Lexpartizan** [comment] 2020-07-15 19:47
@mrushyendra
Thank you, I didn't expect that these are really different concepts. This can lead to confusion.
https://github.com/godotengine/godot/issues/37227

**Comment by akien-mga** [comment] 2020-09-29 07:57
Closing as duplicate of #37227 then.

**Closed by akien-mga** 2020-09-29 07:57 UTC
Labels: breaks compat, enhancement, topic:gui
