### ISSUE TITLE
Particles2D jitter / stutter on M1 mac

### ISSUE THREAD

**Issue by mattchala** [godotengine/godot#56060] opened 2021-12-18 20:13 UTC
### Godot version

3.4.1

### System information

OS Big Sur, M1 Macbook Air

### Issue description

I'm getting stuttery, jittery particle performance with particles2d that doesn't happen in 3.4.  I've created a minimal project reproduction that is just some particles emitting and it is still jittery when running the project, but not in editor.  it seems to be the more particles there are, the more jittery and bugged they become, because in my main project the particles seem almost frozen and flashing in and out of existence.   im wondering if this is a bug or maybe if nobody else is experiencing this maybe the way a certain value functions on particle2d emitters has been changed that i had set to some weird value.

### Steps to reproduce

created a a particle2d with a sprite sheet that has multiple h-frames and set to emitting

### Minimal reproduction project

[particlejitterstutter.zip](https://github.com/godotengine/godot/files/7739895/particlejitterstutter.zip)

**Comment by clayjohn** [comment] 2021-12-18 20:21
Are yuo saying that in 3.4, running on you M1 Mac Particles2D was fine, but in upgrading to 3.4.1 they suddenly got worse? Or did you upgrade to an M1 Mac at the same time that you upgraded to 3.4.1?

I ask because M1 Macs have problems with GPU Particles to begin with see: https://github.com/godotengine/godot/issues/54052

**Comment by bruvzg** [comment] 2021-12-18 20:47
Seems like another issue caused by #54526. Try your project with the artifact from the #56059 to confirm.

**Comment by mattchala** [comment] 2021-12-18 21:08
> Are yuo saying that in 3.4, running on you M1 Mac Particles2D was fine, but in upgrading to 3.4.1 they suddenly got worse? Or did you upgrade to an M1 Mac at the same time that you upgraded to 3.4.1?
> 
> I ask because M1 Macs have problems with GPU Particles to begin with see: #54052

ah, running on same machine.  3.4 on the same m1 mac seems to work fine with the particles and i only notice the issues when i load the same projects in 3.4.1.  i wasn't aware of other issues with particles on m1 but i personally hadn't experienced any issue on the later 3.3 builds and prior 3.4 builds on my m1 air until this version

**Comment by akien-mga** [comment] 2021-12-21 08:19
Closing as duplicate of #56055 (same root cause).

**Closed by akien-mga** 2021-12-21 08:19 UTC
Labels: bug, platform:macos, topic:rendering, regression
