### ISSUE TITLE
High CPU usage due to continuous editor redrawing when working with AnimationTree, even when no animation is active

### ISSUE THREAD

**Issue by OBKF** [godotengine/godot#24705] opened 2019-01-02 03:02 UTC
___

***Bugsquad note:** This issue has been confirmed several times already. No need to confirm it further.*

___

**Godot version:** 3.1 build 9ba6849cf4191e1c037e7416d21f28b19e0e5f43

![image](https://user-images.githubusercontent.com/12987951/50579180-133eef00-0e43-11e9-8c93-12d56c8178ca.png)

**OS/device including version:** Xubuntu 18.04LTS

**Issue description:**

I am experiencing a high CPU usage when working with AnimationTree, just by opening it up not even setting it active.

**Steps to reproduce:**

1. Add AnimationTree node to the scene.
2. Open AnimationTree editor.
3. Check CPU usage (before and after).

**Edit:**
You need to add some animations first (see my CPU stats on the UP-RIGHT corner of the image bellow).
![00](https://user-images.githubusercontent.com/12987951/50591697-2e385000-0e91-11e9-8a94-b6aa765c480f.png)

I added an example project:
[AnimationTreeBug.zip](https://github.com/godotengine/godot/files/2720700/AnimationTreeBug.zip)

**Comment by OBKF** [comment] 2019-01-02 11:52
i5-4310M, I didn't test this on windows.
O have high CPU usage only when using the Animation tree, Idle it's 0%.

**Comment by girng** [comment] 2019-01-02 12:03
@OBKF it does seem you have a word in the background generated as well? what if you open a new blank scene and go to the animationtree editor, is the cpu still at 16%?

**Comment by OBKF** [comment] 2019-01-02 12:36
@girng  It may be an OS specific :thinking: !?
I will try it on windows later and see what happens.

**Comment by Calinou** [comment] 2019-01-02 17:21
I can't notice a significant CPU usage difference here on an i7-6700K + GTX 1080 on Linux.

**Comment by OBKF** [comment] 2019-01-15 06:52
I am experiencing similar behavior with shader editor (I think everything in that bottom panel too), and sometimes with editing lights, the games always runs fine it's only the editor.

**Comment by akien-mga** [comment] 2020-06-20 21:21
Can anyone still reproduce this bug in Godot 3.2.1 or any later release (e.g. [3.2.2-rc2](https://godotengine.org/article/release-candidate-godot-3-2-2-rc-2))?

If yes, please ensure that an up-to-date Minimal Reproduction Project (MRP) is included in this report (a MRP is a zipped Godot project with the minimal elements necessary to reliably trigger the bug). You can upload ZIP files in an issue comment with a drag and drop.

**Comment by justdaft** [comment] 2020-11-03 06:56
Hi can reproduce this issue with Godot 3.2.3 stable, running on my 
MacBook Pro (Retina, 13-inch, Mid 2014)
2.6 GHz Dual-Core Intel Core i5
8 GB 1600 MHz DDR3

When using the animation tree in the editor it causes my cpu to spike to around 90% and cause my fan to max out.
this happens all the time im my current project a 2d platformer game, but I was able to reproduce 
it in the Minimal Reproduction Project in the attached zip file.

Does anyone have any guidance on how to prevent this.

[Godot_AnimationTree_Example.zip](https://github.com/godotengine/godot/files/5479641/Godot_AnimationTree_Example.zip)

**Comment by Calinou** [comment] 2020-11-03 12:51
> Does anyone have any guidance on how to prevent this.

As far as I know, there are no workarounds for this. You could try increasing **Low Processor Mode Sleep Usec** in the Editor Settings to a value like 30000, but I'm not sure if this will decrease CPU usage meaningfully.

**Comment by c7borg** [comment] 2020-11-21 21:18
I have the same issue with Animation Tree, it is fine until I open the node with the animation tree then the fan goes to full speed I found closing the node then re-opening it does reduce it to 15%..

**Comment by markusneg** [comment] 2022-01-28 09:27
Same here: full CPU load upon selecting (inactive) AnimationTree. I am on a modern Debian based Linux system and Intel CPU.

**Comment by Calinou** [comment] 2022-01-28 16:17
This seems to be caused by the AnimationTree editor causing continous redrawing, even if the animation is inactive.

**Comment by tavurth** [comment] 2022-02-20 21:09
### Workaround

Disable the `AnimationTree` in the editor but add a script to enable it when the game starts.

**Comment by KoBeWi** [comment] 2022-05-26 12:36
Doesn't seem to be happening in 2e88628

**Comment by TokageItLab** [comment] 2022-11-21 20:16
Does this problem still occur?

**Comment by c7borg** [comment] 2022-11-21 20:20
I've moved to godot 4 and a newer macbook, I do hear the fan kick in if I leave the animation playing for an extended period of time but I no longer consider this a problem as such

**Comment by TokageItLab** [comment] 2022-11-21 20:25
@Calinou Is it possible to close this issue once? If it occurs again later, we would like to look into the issue again.

**Closed** 2022-11-22 10:27 UTC
Labels: bug, topic:editor, confirmed, topic:animation, performance
