### ISSUE TITLE
Save hotkey should save according to context

### ISSUE THREAD

**Issue by QbieShay** [godotengine/godot#11801] opened 2017-10-03 13:21 UTC
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Godot Editor

**Issue description:**

*Expected* : when hitting ctrl+s, something is saved according to the current view: if in script view the script is saved, if in scene view the scene is saved
*Happened*: Editor saves the open scene instead of the script

**Comment by Zylann** [comment] 2017-10-03 13:51
Related to https://github.com/godotengine/godot/issues/5289

**Comment by ScottMakesGames** [comment] 2017-10-03 14:13
same goes for editing resources, if i'm editing a resource over in one of the panels and i hit ctrl+s, it should save the resource.

**Comment by akien-mga** [comment] 2019-04-15 15:49
This is actually a duplicate of the even older #9069.

**Closed by akien-mga** 2019-04-15 15:49 UTC
Labels: bug, topic:editor, usability
