### ISSUE TITLE
"Terminating due to blacklisting by kernel driver" error on iOS export.

### ISSUE THREAD

**Issue by dunyakilavuz** [godotengine/godot#39884] opened 2020-06-27 14:43 UTC
**Godot version:**
3.2.2 Stable Mono Official Version
**Issue description:**
I was experimenting on exporting an existing android project of mine to iOS thanks to C# support for iOS. Xcode builds and installs the project without an error. However  on the running phase i get the following error from the debugger.

```
*********** main.m
running app main
Path: /var/containers/Bundle/Application/A19C0B5B-C1AA-47D7-9B97-36925C9F9820/SolarX_iOS.app
godot_iphone /var/containers/Bundle/Application/A19C0B5B-C1AA-47D7-9B97-36925C9F9820/SolarX_iOS.app/SolarX_iOS
cwd /private/var/containers/Bundle/Application/A19C0B5B-C1AA-47D7-9B97-36925C9F9820/SolarX_iOS.app
os created
setting data dir to /var/mobile/Containers/Data/Application/CF66FEC1-E5F7-458B-8F85-75241E83BD05/Documents from /var/mobile/Containers/Data/Application/CF66FEC1-E5F7-458B-8F85-75241E83BD05/Documents
setup 0
after init super 0x15de0c9b0
2020-06-27 17:25:41.848429+0300 SolarX_iOS[1875:424835] Metal GPU Frame Capture Enabled
2020-06-27 17:25:41.848949+0300 SolarX_iOS[1875:424835] Metal API Validation Enabled
2020-06-27 17:25:41.961603+0300 SolarX_iOS[1875:424835] Setting up an OpenGL ES 3.0 context. Based on Project Settings "rendering/quality/driver/driver_name"
******** screen size 1125, 2436
after init gles 0x15de0c9b0
******** adding observer for sound routing changes
******** adding observer for keyboard show/hide
cadisaplylink: 1start animation!
******** screen size 1125, 2436
2020-06-27 17:25:42.085162+0300 SolarX_iOS[1875:424835] Godot Engine v3.2.2.stable.mono.official - https://godotengine.org
Godot Engine v3.2.2.stable.mono.official - https://godotengine.org
2020-06-27 17:25:42.091924+0300 SolarX_iOS[1875:424835] OpenGL ES 3.0 Renderer: Apple A12 GPU
OpenGL ES 3.0 Renderer: Apple A12 GPU
2020-06-27 17:25:42.463409+0300 SolarX_iOS[1875:424835] 
 
2020-06-27 17:25:42.629682+0300 SolarX_iOS[1875:424835] **ERROR**: Mono: Core API hash mismatch.
2020-06-27 17:25:42.629739+0300 SolarX_iOS[1875:424835]    At: modules/mono/mono_gd/gd_mono.cpp:494:_init_godot_api_hashes() - Mono: Core API hash mismatch.
**ERROR**: Mono: Core API hash mismatch.
   At: modules/mono/mono_gd/gd_mono.cpp:494:_init_godot_api_hashes() - Mono: Core API hash mismatch.
2020-06-27 17:25:42.631002+0300 SolarX_iOS[1875:424835] Mono: Config attempting to parse: '/private/var/containers/Bundle/Application/A19C0B5B-C1AA-47D7-9B97-36925C9F9820/SolarX_iOS.app/data_Godot/Mono/etc/mono/config'.
2020-06-27 17:25:42.631338+0300 SolarX_iOS[1875:424835] Mono: Config attempting to parse: '/private/var/mobile/Containers/Data/Application/CF66FEC1-E5F7-458B-8F85-75241E83BD05/.mono/config'.
2020-06-27 17:25:42.661236+0300 SolarX_iOS[1875:424835] Mono: Image addref mscorlib[0x28133ae80] (asmctx DEFAULT) -> .mono/assemblies/Debug/mscorlib.dll[0x15e0bbc00]: 2
2020-06-27 17:25:42.661672+0300 SolarX_iOS[1875:424835] Mono: Prepared to set up assembly 'mscorlib' (.mono/assemblies/Debug/mscorlib.dll)
2020-06-27 17:25:42.661943+0300 SolarX_iOS[1875:424835] Mono: Found statically linked AOT module 'mscorlib'.
2020-06-27 17:25:42.667463+0300 SolarX_iOS[1875:424835] Mono: Unloading image .mono/assemblies/Debug/mscorlib.dll [0x15e8b2800].
2020-06-27 17:25:42.667630+0300 SolarX_iOS[1875:424835] Mono: Image addref mscorlib[0x28128ad00] (asmctx DEFAULT) -> .mono/assemblies/Debug/mscorlib.dll[0x15e0bbc00]: 4
2020-06-27 17:25:42.667790+0300 SolarX_iOS[1875:424835] Mono: AOT: image 'mscorlib' found.
2020-06-27 17:25:42.682172+0300 SolarX_iOS[1875:424835] Mono: Assembly mscorlib[0x28133ae80] added to domain GodotEngine.RootDomain, ref_count=1
2020-06-27 17:25:42.689710+0300 SolarX_iOS[1875:424835] Mono: Image addref GodotSharp[0x28133b380] (asmctx DEFAULT) -> .mono/assemblies/Debug/GodotSharp.dll[0x15e0dd400]: 2
2020-06-27 17:25:42.689743+0300 SolarX_iOS[1875:424835] Mono: Prepared to set up assembly 'GodotSharp' (.mono/assemblies/Debug/GodotSharp.dll)
2020-06-27 17:25:42.689756+0300 SolarX_iOS[1875:424835] Mono: Assembly GodotSharp[0x28133b380] added to domain GodotEngine.RootDomain, ref_count=1
2020-06-27 17:25:42.689770+0300 SolarX_iOS[1875:424835] Mono: Found statically linked AOT module 'GodotSharp'.
2020-06-27 17:25:42.701416+0300 SolarX_iOS[1875:424835] Mono: Image addref System[0x28133b580] (asmctx DEFAULT) -> .mono/assemblies/Debug/System.dll[0x15e0d9e00]: 2
2020-06-27 17:25:42.701435+0300 SolarX_iOS[1875:424835] Mono: Prepared to set up assembly 'System' (.mono/assemblies/Debug/System.dll)
2020-06-27 17:25:42.701446+0300 SolarX_iOS[1875:424835] Mono: Assembly System[0x28133b580] added to domain GodotEngine.RootDomain, ref_count=1
2020-06-27 17:25:42.701455+0300 SolarX_iOS[1875:424835] Mono: Found statically linked AOT module 'System'.
2020-06-27 17:25:42.707300+0300 SolarX_iOS[1875:424835] Mono: Image addref Mono.Security[0x28128b100] (asmctx DEFAULT) -> .mono/assemblies/Debug/Mono.Security.dll[0x15e8ad400]: 2
2020-06-27 17:25:42.707315+0300 SolarX_iOS[1875:424835] Mono: Prepared to set up assembly 'Mono.Security' (.mono/assemblies/Debug/Mono.Security.dll)
2020-06-27 17:25:42.707323+0300 SolarX_iOS[1875:424835] Mono: Assembly Mono.Security[0x28128b100] added to domain GodotEngine.RootDomain, ref_count=1
2020-06-27 17:25:42.707332+0300 SolarX_iOS[1875:424835] Mono: Found statically linked AOT module 'Mono.Security'.
2020-06-27 17:25:42.709594+0300 SolarX_iOS[1875:424835] Mono: AOT: image 'Mono.Security' found.
2020-06-27 17:25:42.714288+0300 SolarX_iOS[1875:424835] Mono: Image addref System.Core[0x28133b780] (asmctx DEFAULT) -> .mono/assemblies/Debug/System.Core.dll[0x15e0dac00]: 2
2020-06-27 17:25:42.714312+0300 SolarX_iOS[1875:424835] Mono: Prepared to set up assembly 'System.Core' (.mono/assemblies/Debug/System.Core.dll)
2020-06-27 17:25:42.714321+0300 SolarX_iOS[1875:424835] Mono: Assembly System.Core[0x28133b780] added to domain GodotEngine.RootDomain, ref_count=1
2020-06-27 17:25:42.714330+0300 SolarX_iOS[1875:424835] Mono: Found statically linked AOT module 'System.Core'.
2020-06-27 17:25:42.716627+0300 SolarX_iOS[1875:424835] Mono: AOT: image 'System.Core' found.
2020-06-27 17:25:42.717736+0300 SolarX_iOS[1875:424835] Mono: Image addref System.Numerics[0x28133b980] (asmctx DEFAULT) -> .mono/assemblies/Debug/System.Numerics.dll[0x15e0df200]: 2
2020-06-27 17:25:42.717750+0300 SolarX_iOS[1875:424835] Mono: Prepared to set up assembly 'System.Numerics' (.mono/assemblies/Debug/System.Numerics.dll)
2020-06-27 17:25:42.717758+0300 SolarX_iOS[1875:424835] Mono: Assembly System.Numerics[0x28133b980] added to domain GodotEngine.RootDomain, ref_count=1
2020-06-27 17:25:42.717767+0300 SolarX_iOS[1875:424835] Mono: Found statically linked AOT module 'System.Numerics'.
2020-06-27 17:25:42.718231+0300 SolarX_iOS[1875:424835] Mono: AOT: image 'System.Numerics' found.
2020-06-27 17:25:42.718248+0300 SolarX_iOS[1875:424835] Mono: AOT: image 'System' found.
2020-06-27 17:25:42.718333+0300 SolarX_iOS[1875:424835] Mono: AOT: image 'GodotSharp' found.
2020-06-27 17:25:42.719218+0300 SolarX_iOS[1875:424835] Mono: Loading reference 0 of .mono/assemblies/Debug/GodotSharp.dll asmctx DEFAULT, looking for mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
2020-06-27 17:25:42.719234+0300 SolarX_iOS[1875:424835] Mono: Assembly Ref addref GodotSharp[0x28133b380] -> mscorlib[0x28133ae80]: 2
2020-06-27 17:25:42.720530+0300 SolarX_iOS[1875:424835] Mono: Loading reference 2 of .mono/assemblies/Debug/GodotSharp.dll asmctx DEFAULT, looking for System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
2020-06-27 17:25:42.720546+0300 SolarX_iOS[1875:424835] Mono: Assembly Ref addref GodotSharp[0x28133b380] -> System[0x28133b580]: 2
2020-06-27 17:25:42.720791+0300 SolarX_iOS[1875:424835] Mono: Loading reference 0 of .mono/assemblies/Debug/System.dll asmctx DEFAULT, looking for mscorlib, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e
2020-06-27 17:25:42.720804+0300 SolarX_iOS[1875:424835] Mono: Assembly Ref addref System[0x28133b580] -> mscorlib[0x28133ae80]: 3
2020-06-27 17:25:42.730807+0300 SolarX_iOS[1875:424835] Mono: Loading reference 0 of .mono/assemblies/Debug/Mono.Security.dll asmctx DEFAULT, looking for mscorlib, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e
2020-06-27 17:25:42.730826+0300 SolarX_iOS[1875:424835] Mono: Assembly Ref addref Mono.Security[0x28128b100] -> mscorlib[0x28133ae80]: 4
2020-06-27 17:25:42.740059+0300 SolarX_iOS[1875:424835] Mono: Loading reference 0 of .mono/assemblies/Debug/System.Core.dll asmctx DEFAULT, looking for mscorlib, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e
2020-06-27 17:25:42.740079+0300 SolarX_iOS[1875:424835] Mono: Assembly Ref addref System.Core[0x28133b780] -> mscorlib[0x28133ae80]: 5
2020-06-27 17:25:42.766497+0300 SolarX_iOS[1875:424835] Mono: Image addref SolarX[0x28128b200] (asmctx DEFAULT) -> .mono/assemblies/Debug/SolarX.dll[0x15e923000]: 2
2020-06-27 17:25:42.766529+0300 SolarX_iOS[1875:424835] Mono: Prepared to set up assembly 'SolarX' (.mono/assemblies/Debug/SolarX.dll)
2020-06-27 17:25:42.766541+0300 SolarX_iOS[1875:424835] Mono: Assembly SolarX[0x28128b200] added to domain GodotEngine.RootDomain, ref_count=1
2020-06-27 17:25:42.766554+0300 SolarX_iOS[1875:424835] Mono: Found statically linked AOT module 'SolarX'.
2020-06-27 17:25:42.767390+0300 SolarX_iOS[1875:424835] Mono: AOT: image 'SolarX' found.
2020-06-27 17:25:42.911467+0300 SolarX_iOS[1875:424835] Mono: Loading reference 1 of .mono/assemblies/Debug/SolarX.dll asmctx DEFAULT, looking for GodotSharp, Version=1.0.7482.13981, Culture=neutral, PublicKeyToken=null
2020-06-27 17:25:42.911495+0300 SolarX_iOS[1875:424835] Mono: Assembly Ref addref SolarX[0x28128b200] -> GodotSharp[0x28133b380]: 2
2020-06-27 17:25:43.087074+0300 SolarX_iOS[1875:425106] Execution of the command buffer was aborted due to an error during execution. Caused GPU Hang Error (IOAF code 3)
2020-06-27 17:25:43.087137+0300 SolarX_iOS[1875:425106] Execution of the command buffer was aborted due to an error during execution. Caused GPU Hang Error (IOAF code 3)
2020-06-27 17:25:43.087262+0300 SolarX_iOS[1875:425106] GLDRendererMetal command buffer completion error: Error Domain=MTLCommandBufferErrorDomain Code=2 "Caused GPU Hang Error (IOAF code 3)" UserInfo={NSLocalizedDescription=Caused GPU Hang Error (IOAF code 3)}
2020-06-27 17:25:43.102903+0300 SolarX_iOS[1875:424835] Loading Scene thread start.
Loading Scene thread start.
2020-06-27 17:25:43.103299+0300 SolarX_iOS[1875:425175] Mono: Loading reference 0 of .mono/assemblies/Debug/SolarX.dll asmctx DEFAULT, looking for mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
2020-06-27 17:25:43.103408+0300 SolarX_iOS[1875:425175] Mono: Assembly Ref addref SolarX[0x28128b200] -> mscorlib[0x28133ae80]: 6
2020-06-27 17:25:43.107525+0300 SolarX_iOS[1875:424835] Mono: Loading reference 1 of .mono/assemblies/Debug/GodotSharp.dll asmctx DEFAULT, looking for System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
2020-06-27 17:25:43.107553+0300 SolarX_iOS[1875:424835] Mono: Assembly Ref addref GodotSharp[0x28133b380] -> System.Core[0x28133b780]: 2
2020-06-27 17:25:44.193241+0300 SolarX_iOS[1875:424835] [Error] _authenticateUsingAlert:Failed to authenticate player with existing credentials.Error: Error Domain=GKErrorDomain Code=15 "The requested operation could not be completed because this application is not recognized by Game Center." UserInfo={GKServerStatusCode=5019, NSLocalizedDescription=The requested operation could not be completed because this application is not recognized by Game Center., NSUnderlyingError=0x283260870 {Error Domain=GKServerErrorDomain Code=5019 "status = 5019, no game matching descriptor: ios:com.dunyakilavuz.SolarX:1.0:1.0+-1" UserInfo={GKServerStatusCode=5019, NSLocalizedFailureReason=status = 5019, no game matching descriptor: ios:com.dunyakilavuz.SolarX:1.0:1.0+-1}}}
2020-06-27 17:25:44.321089+0300 SolarX_iOS[1875:424835] [Account Error] startAuthenticationForExistingPrimaryPlayer:Failed to Authenticate player.Error: Error Domain=GKErrorDomain Code=15 "The requested operation could not be completed because this application is not recognized by Game Center." UserInfo={NSLocalizedDescription=The requested operation could not be completed because this application is not recognized by Game Center.}
2020-06-27 17:25:44.321348+0300 SolarX_iOS[1875:424835] [Account Error] authenticationDidCompleteWithError: Authentication failed for player with error: Error Domain=GKErrorDomain Code=15 "The requested operation could not be completed because this application is not recognized by Game Center." UserInfo={NSLocalizedDescription=The requested operation could not be completed because this application is not recognized by Game Center.}
2020-06-27 17:25:45.043479+0300 SolarX_iOS[1875:424835] [TraitCollection] Class CKBrowserSwitcherViewController overrides the -traitCollection getter, which is not supported. If you're trying to override traits, you must use the appropriate API.
2020-06-27 17:25:46.701050+0300 SolarX_iOS[1875:425107] Execution of the command buffer was aborted due to an error during execution. Caused GPU Hang Error (IOAF code 3)
2020-06-27 17:25:46.701127+0300 SolarX_iOS[1875:425107] Execution of the command buffer was aborted due to an error during execution. Caused GPU Hang Error (IOAF code 3)
2020-06-27 17:25:46.701201+0300 SolarX_iOS[1875:425107] GLDRendererMetal command buffer completion error: Error Domain=MTLCommandBufferErrorDomain Code=2 "Caused GPU Hang Error (IOAF code 3)" UserInfo={NSLocalizedDescription=Caused GPU Hang Error (IOAF code 3)}
2020-06-27 17:25:46.702249+0300 SolarX_iOS[1875:425107] Execution of the command buffer was aborted due to an error during execution. Ignored (for causing prior/excessive GPU errors) (IOAF code 4)
2020-06-27 17:25:46.702290+0300 SolarX_iOS[1875:425107] Execution of the command buffer was aborted due to an error during execution. Ignored (for causing prior/excessive GPU errors) (IOAF code 4)
2020-06-27 17:25:46.702325+0300 SolarX_iOS[1875:425107] Execution of the command buffer was aborted due to an error during execution. Ignored (for causing prior/excessive GPU errors) (IOAF code 4)
2020-06-27 17:25:46.702352+0300 SolarX_iOS[1875:425107] Execution of the command buffer was aborted due to an error during execution. Ignored (for causing prior/excessive GPU errors) (IOAF code 4)
2020-06-27 17:25:46.702395+0300 SolarX_iOS[1875:425107] GLDRendererMetal command buffer completion error: Error Domain=MTLCommandBufferErrorDomain Code=4 "Ignored (for causing prior/excessive GPU errors) (IOAF code 4)" UserInfo={NSLocalizedDescription=Ignored (for causing prior/excessive GPU errors) (IOAF code 4)}
2020-06-27 17:25:46.702435+0300 SolarX_iOS[1875:424835] Terminating due to blacklisting by kernel driver

```

Regardless the error, the app opens up and runs without any problems after trying to launch the app several times. The app crashes on the loading screen. The loading is handled on a background thread. Also should mention the app launches and operates normally on the android side, making me think maybe there is a bug in the iOS side. 

Maybe I am doing something wrong here. Does anyone experience this, or know how to tackle the problem?

**Comment by Calinou** [comment] 2020-06-27 14:47
cc @neikeq

**Comment by akien-mga** [comment] 2020-06-27 14:48
CC @neikeq for the "Core API mismatch" error, but I think it's a false positive.

The problem seems to be that your app triggers issues in the graphics driver.

Can you reproduce it with a minimal project? Does it work if you don't load everything in a thread when it starts, but delay loading of some of the biggest resources?

**Comment by dunyakilavuz** [comment] 2020-09-28 15:58
Problem resolved on the stable 3.2.3 release.

**Comment by DrMoriarty** [comment] 2020-10-13 20:01
I have this issue in godot 3.2.4.beta (0a2a93b165)

```
2020-10-13 22:59:16.612150+0300 trawler-io[82157:5634227] GLDRendererMetal command buffer completion error: Error Domain=MTLCommandBufferErrorDomain Code=2 "Caused GPU Hang Error (IOAF code 3)" UserInfo={NSLocalizedDescription=Caused GPU Hang Error (IOAF code 3)}
2020-10-13 22:59:16.628465+0300 trawler-io[82157:5633994] DrawView: 500 error
2020-10-13 22:59:16.632447+0300 trawler-io[82157:5634262] Execution of the command buffer was aborted due to an error during execution. Caused GPU Hang Error (IOAF code 3)
2020-10-13 22:59:16.633007+0300 trawler-io[82157:5634262] Execution of the command buffer was aborted due to an error during execution. Caused GPU Hang Error (IOAF code 3)
2020-10-13 22:59:16.633124+0300 trawler-io[82157:5634262] GLDRendererMetal command buffer completion error: Error Domain=MTLCommandBufferErrorDomain Code=2 "Caused GPU Hang Error (IOAF code 3)" UserInfo={NSLocalizedDescription=Caused GPU Hang Error (IOAF code 3)}
2020-10-13 22:59:16.634949+0300 trawler-io[82157:5634262] Execution of the command buffer was aborted due to an error during execution. Ignored (for causing prior/excessive GPU errors) (IOAF code 4)
2020-10-13 22:59:16.635036+0300 trawler-io[82157:5634262] Execution of the command buffer was aborted due to an error during execution. Ignored (for causing prior/excessive GPU errors) (IOAF code 4)
2020-10-13 22:59:16.635095+0300 trawler-io[82157:5634262] Execution of the command buffer was aborted due to an error during execution. Ignored (for causing prior/excessive GPU errors) (IOAF code 4)
2020-10-13 22:59:16.635425+0300 trawler-io[82157:5634262] Execution of the command buffer was aborted due to an error during execution. Ignored (for causing prior/excessive GPU errors) (IOAF code 4)
2020-10-13 22:59:16.635618+0300 trawler-io[82157:5634262] GLDRendererMetal command buffer completion error: Error Domain=MTLCommandBufferErrorDomain Code=4 "Ignored (for causing prior/excessive GPU errors) (IOAF code 4)" UserInfo={NSLocalizedDescription=Ignored (for causing prior/excessive GPU errors) (IOAF code 4)}
2020-10-13 22:59:16.636152+0300 trawler-io[82157:5633994] Terminating due to blacklisting by kernel driver
```

**Comment by dunyakilavuz** [comment] 2021-02-06 11:27
So after a debugging session, I found out what caused this error. (At least for my project.) 

In my project I use a custom `WorldEnvironment` node for my 3D game scene. Initially, I managed to run the project on iOS side without including this custom node. So to find out whats wrong with the node, I started with the basic `Environment` object and add functionality to it bit by bit to see when it crashes the game.

The crash occurred after setting the `Background` mode to `Sky` and `Sky` was set to a `Panorama` which uses a custom .png file. So using a custom panorama skybox caused this problem for me. 

Now when I don't specify a panorama sky the project runs without problems. However I can still use the same skybox for pc and android without any crash occurring, so this has to be a bug for iOS platform only.

**Comment by akien-mga** [comment] 2021-02-06 12:17
Thanks, that confirms that it's a rendering issue and not related to Mono.

There are similar issues on lower end Android devices when using `ProceduralSky` which requires a lot of video memory and can crash the driver. I guess some iOS devices have similar limitations, though it's `PanoramaSky` here. Might be worth checking if it happens with any kind of panorama texture or only some big ones. (E.g. does it work with `icon.png`?)

What kind of iOS device(s) is it crashing on?

**Comment by naithar** [comment] 2021-02-06 13:37
@dunyakilavuz any chance that you can provide a reproduction project for us to test? 
It might be a `.png` file size that causes the issue, due to the iOS limits, but I am not sure.

**Comment by dunyakilavuz** [comment] 2021-02-06 16:44
Guess I was fast to conclude that the issue was produced by the `PanoramaSky` property alone. It probably has to do with the total size of other textures we include in our projects as well.

I use an iPhone XS to run these projects. I tried using icon.png (3 KB in size) as PanoramaSky but interestingly it still crashes the game whereas the original skybox is 2.9 MB in size. Not setting a property runs the project however. 

The original project has .png files with various sizes (from 50 KB button textures to 6-7 MB albedo, normal map textures). 
I think @naithar's suggestion is accurate in this case. Maybe adding the skybox texture to all the assets I already use was the last straw that made the crash.

I wrapped up a new sample project with some of the assets I use in the original. So far, I kept on adding textures to it but failed to crash the game with the same `Environment` setup. Instead, I will try to reduce the sizes of the large textures I use in the original. I hope to see If smaller textures in size prevent the crash even with a skybox property.

**Comment by Calinou** [comment] 2021-12-14 10:31
I'll close this as nobody else has been able to reproduce this recently. Please comment (with the [issue template](https://github.com/godotengine/godot/blob/master/.github/ISSUE_TEMPLATE/bug_report.md) filled) if you can still reproduce this.

**Closed by Calinou** 2021-12-14 10:31 UTC
Labels: bug, platform:ios, topic:rendering

**Comment by Mikerhinos** [comment] 2022-10-12 14:24
Having this problem too with a colleague that has an iPhone.
App was crashing when going from a 2D menu scene to a 3D scene with the "excessive gpu errors" message.
I deleted the environments nodes, desactivated Glow, textures etc. and now it doesn't crash anymore EXCEPT if we go from the 2D menu to 3D scene to 2D menu too fast.
It runs smooth as butter on my Xiaomi Note 8 Pro even with all the effects activated :( 

(Godot 3.5 Stable, he tried to export on 3.5.1 but same problem)
