### ISSUE TITLE
Skybox leaks through ReflectionProbe reflections

### ISSUE THREAD

**Issue by Jamsers** [godotengine/godot#69100] opened 2022-11-24 06:29 UTC
### Godot version

3.5.1.stable.official

### System information

Windows 11 22H2, GTX 1650 Mobile, NVIDIA Driver 526.98, GLES3

### Issue description

The skybox seems to leak through the reflection applied by ReflectionProbe on objects. I'd expect that a roof would completely block out the sun and the sky for example, instead of the reflection being a kind of "blend" between the two.

![Reflection1_Godot](https://user-images.githubusercontent.com/39361911/203708826-50564936-3062-43d3-a834-279b4f7bc413.png)
![Reflection1_Unity](https://user-images.githubusercontent.com/39361911/203708837-ec1cafab-30bd-47d9-b21b-53f8acfd32a4.png)

(The projects pictured above can be found at [GodotLightingTest](https://github.com/Jamsers/GodotLightingTest) and [UnityLightingTest](https://github.com/Jamsers/UnityLightingTest).)

### Steps to reproduce

Set up a scene with a bright skybox.
Create a reflective surface facing up.
Put a "roof" on top of this reflective surface, to block the light and reflections from up top.
Add a ReflectionProbe affecting the reflective surface.
Move the ReflectionProbe's origin to somewhere between the surface and its "roof".
Check the reflections and notice that the skybox color seems to bleed through the reflection. At certain angles, you can even see the sun poking through the reflections.

### Minimal reproduction project

[GodotReflectionIssue.zip](https://github.com/godotengine/godot/files/10081343/GodotReflectionIssue.zip)

**Comment by BraqueDown** [comment] 2022-11-24 10:31
See https://github.com/godotengine/godot-proposals/issues/3013,
and https://github.com/godotengine/godot/pull/61416.

**Comment by Calinou** [comment] 2022-11-24 14:56
Duplicate of https://github.com/godotengine/godot-proposals/issues/3013.

**Closed by Calinou** 2022-11-24 14:56 UTC
Labels: archived, topic:rendering, topic:3d
