### ISSUE TITLE
PinJoint2D causing node to move unexpectedly when attached via code

### ISSUE THREAD

**Issue by MrNoobGuy** [godotengine/godot#30191] opened 2019-06-29 15:04 UTC
**Godot version:**
3.1.1 and 3.1 64-bit

**OS/device including version:**
Windows 10 64-bit

**Issue description:**
When constructing an pendulum object with a joint at either end with a circle at the bottom, the circle object moves as soon as it is set as the joint's node_a/b. It occurs even when the collision shapes are disabled.
Everything works when it I build it in the editor, but when I try to code it together the unexpected movement occurs.

**Steps to reproduce:**
Static body with child PinJoint2D connected to it and to 'arm'.
'Arm' RigidBody with segment shape, child PinJoint2D connected at other end and to circle.
Circle RigidBody

![pinjoint2d_example](https://user-images.githubusercontent.com/52352965/60385846-f9930300-9a85-11e9-91c4-9caac05f7513.png)

No Number = Constructed in the editor.
1 = Objects placed in the editor, disabled and without gravity. The local positions are exact copies of the editor-built nodes.
2 = Gravity applied, first joint attached, but arm-to-circle joint not attached (The circle has fallen slightly in the screenshot).
3 = Circle connected to arm, which causes it to move to a new position.
4 = Collision shapes enabled, the circle and arm spin out of control.

**Minimal reproduction project:**
[PinJoint2D_Unexpected_Movement.zip](https://github.com/godotengine/godot/files/3341990/PinJoint2D_Unexpected_Movement.zip)

**Comment by pwab** [comment] 2020-06-16 21:22
Hey @MrNoobGuy this issue can be easily solved:
You are adding bodies as a child to the scene and after that you're trying to change their position. This will get in conflict with the physics engine because as soon as bodies have been added to the scene their position is calculated in the physics frame. (If someone is reading this with more knowledge of the physics server please correct me if I'm wrong here)

### For example:
**Don't**
```
add_child(_arm)
_arm.rotation = _prebuilt_arm.rotation
```

**Do**
```
_arm.rotation = _prebuilt_arm.rotation
add_child(_arm)
```

I updated your code for mode 3 (the last one where everything is created at runtime) so that it moves as expected:
[PinJoint2D_Unexpected_Movement.zip](https://github.com/godotengine/godot/files/4789142/PinJoint2D_Unexpected_Movement.zip)

**Comment by pouleyKetchoupp** [comment] 2020-12-23 19:44
Confirmed on 3.2.3 stable.

The workaround by @pwab in https://github.com/godotengine/godot/issues/30191#issuecomment-645018813 makes sense, but here's a more accurate description of the issue.

In general, it should be fine to set the position after adding a body to the scene, except in this case the position in physics is updated only on the next step. When a joint is created right after the bodies are created, it uses the previous positions from the physics side, which is not correct.

This needs to be fixed by making sure the joint is setup using the updated body transforms when created.

**Closed** 2020-12-25 13:59 UTC
Labels: bug, confirmed, topic:physics
