### ISSUE TITLE
Crypto module missing in HTML5 export

### ISSUE THREAD

**Issue by lloesche** [godotengine/godot#55695] opened 2021-12-07 16:39 UTC
### Godot version

3.4.stable

### System information

Webassembly export

### Issue description

When exporting HTML5/webasm the Crypto module seems disabled via:
https://github.com/godotengine/godot/blob/46fdba5f8b09e2c52247ab28047f578e32414f1a/platform/javascript/detect.py#L55

throwing
```
ERROR: Crypto is not available when the mbedtls module is disabled.
```

The argument of saving 200kb in output size because the Crypto feature is "not used often on the web platform" is outdated ever since Godot 3.4.

Crypto now contains `hmac_digest` necessary to generate and validate JSON Web Tokens (JWTs) which is an integral part of any Oauth2/OpenID connect authentication flow on the web.

Meaning while it's true that the browser handles all the transport layer security, any sort of OAuth2 authenticated requests on the web rely on the Crypto module hence it's an error not to include it if the argument for not including is "it's not needed on the web".

### Steps to reproduce

- Build an app that does JWT generation/verification either standalone or as part of OAuth authentication flow.
- Export the app to HTML5
- App will fail to load with default export templates.

Edit: I just found https://github.com/godotengine/godot-proposals/issues/3574 which is the same issue. To me it is a bug as this should have been a default when the new Godot 3.4 Crypto functions were shipped. But feel free to close in favour of the proposal.

**Comment by Calinou** [comment] 2021-12-07 17:18
Duplicate of https://github.com/godotengine/godot-proposals/issues/3574.

**Closed by Calinou** 2021-12-07 17:18 UTC
