### ISSUE TITLE
Large Tilemaps cause lag when placing or erasing tiles

### ISSUE THREAD

**Issue by whaleywoo** [godotengine/godot#74505] opened 2023-03-06 18:40 UTC
### Godot version

4.0.stable

### System information

Windows 10, AMD Ryzen 7 5800H with Radeon Graphics 3.20 GHz

### Issue description

When a Tilemap has a somewhat large number of tiles, placing or erasing tiles causes noticeable lag about half the time. I would expect there to be much less lag for this number of tiles because it is not insanely large (see image). Additionally, this still happens even if you split the large Tilemap into multiple smaller Tilemaps.
![tilemap](https://user-images.githubusercontent.com/46167261/223200880-931a4f94-e8b9-4753-8b76-49a725f305b3.PNG)

### Steps to reproduce

Simply create a Tilemap, give it a Tileset, and add a large number of tiles. Then try placing or erasing tiles multiple times in succession.

### Minimal reproduction project

[Tilemap Size Test.zip](https://github.com/godotengine/godot/files/10901783/Tilemap.Size.Test.zip)

**Comment by AThousandShips** [comment] 2023-03-07 14:15
That's a pretty huge `TileMap` though? Does this happen when zoomed in as well?

**Comment by AThousandShips** [comment] 2023-03-07 14:35
Also, look at #6415, #68960

**Comment by AThousandShips** [comment] 2023-03-07 14:37
Duplicate of #72405

**Closed** 2023-03-07 14:59 UTC
