### ISSUE TITLE
rect_scale of node can't be set to (0,0) anymore.

### ISSUE THREAD

**Issue by ondesic** [godotengine/godot#36748] opened 2020-03-03 05:10 UTC
**Godot version:**
3.2 stable

**OS/device including version:**
Win 10

The issue that is breaking my code is:  If you assign a Container node to a rect_scale of (0,0), it now is setting the rect_scale to (0.00001, 0.00001).
This is breaking a large section of conditional checking of code I already have in place

Reproduce:
Create a new project with a Node2D.
Add a Container Node as a child.
Create a script for the Node2D an place in the "_ready()" function the code:

var wewe = Vector2(0, 0)
var tete = str(wewe)
var Test = $Container.rect_scale
var uu = str(Test)
wewe = 100

Step though the code and you should find that tete equals "(0,0)" like expected.
However uu == "(0.00001, 0.00001)"

I don't know when this was introduced, but I just updated to 3.2 stable, and this bug is present.

**Comment by aaronfranke** [comment] 2020-03-03 06:20
If the only concern is with checking if the scale is zero, you could always just adjust that code.

    rect_scale.x < 0.0001 && rect_scale.y < 0.0001

Or maybe:

    Vector2.ZERO.is_equal_approx(rect_scale / 10) # Must divide to land below the tolerance.

**Comment by ondesic** [comment] 2020-03-03 15:50
This isn't my only concern.  
The inspector still says (0,0) even though it is 0.00001,  
I set the property to (0,0) and it should become (0,0).  The tween code asks for the pro to be set to (0,0).

From 3.1 and before, we have been able to set this to a solid (0,0).  As well, the docs do not mention that you cannot set the property to (0,0).  Hopefully what ever changed can to switched back

**Comment by bojidar-bg** [comment] 2020-03-03 16:52
Duplicate of #35081?

**Comment by Calinou** [comment] 2020-03-16 10:06
Duplicate of #35081.

**Closed by Calinou** 2020-03-16 10:06 UTC
Labels: bug, topic:core
