### ISSUE TITLE
Linux compilation error: no 'String OS_Unix::get_global_settings_path() const' member function declared in class 'OS_Unix'

### ISSUE THREAD

**Issue by kubecz3k** [godotengine/godot#13088] opened 2017-11-20 11:43 UTC
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Ubuntu 17.04, d413f372be9dac1bdd9ae6a709de910d8691b58f

**Issue description:**
I have this error during linux compilation:
```
drivers/unix/os_unix_global_settings_path.gen.cpp:3:44: error: no 'String OS_Unix::get_global_settings_path() const' member function declared in class 'OS_Unix'
 String OS_Unix::get_global_settings_path() const {
```
I'm using `scons platform=x11 CC=gcc-5 CXX=g++-5 -j 4 target=release_debug` to compile

**Steps to reproduce:**

**Comment by Sslaxx** [comment] 2017-11-20 11:47
Did you do `git clean -ffdx` first? I had that error, cleaning the repo fixed it.

**Comment by nimenko** [comment] 2017-11-20 11:59
Duplicate of #13076.

**Comment by akien-mga** [comment] 2017-11-20 12:00
You should know better @kubecz3k as a hardcore *master* user; the answer to a build issue with a `*.gen.*` file is always "delete it". ;)

**Closed** 2017-11-20 11:59 UTC
Labels: bug, platform:linux, topic:buildsystem

**Comment by kubecz3k** [comment] 2017-11-20 12:02
@akien-mga huh sorry! I will do better next time :)
