### ISSUE TITLE
С# scripts do not run during the start of the scene

### ISSUE THREAD

**Issue by zrckr** [godotengine/godot#50689] opened 2021-07-21 10:00 UTC
### Godot version

v4.0.dev.mono.custom_build [8cc599db6]

### System information

Windows 10

### Issue description

At the time of writing this issue, it is not possible to run C# scripts. If you create a script, the engine will not create `*.sln` and `*.csproj` for the project, thus, not allowing to build a library and load scripts during the run of the scene. Also the "Build" and "MSBuild" buttons are missing in the editor.

Error output during playing the scene:
```
ERROR: Mono: Core API hash mismatch.
   at: GDMono::_init_godot_api_hashes (modules\mono\mono_gd\gd_mono.cpp:495)
ERROR: Mono: Editor API hash mismatch.
   at: GDMono::_init_godot_api_hashes (modules\mono\mono_gd\gd_mono.cpp:500)
ERROR: Cannot instance script because the project assembly is not loaded. Script: 'res://Node3D.cs'.
   at: (modules\mono\csharp_script.cpp:3073)
```

### Steps to reproduce

1. Create a new C# script
2. Create a scene (Node3D.tscn) with Node3D as the root
3. Attach a script for a Node3D.tscn
4. Save a scene to a file
5. Run a it via "Play Scene" mode
6. Mono will not be loaded, and errors will occur

### Minimal reproduction project

[csharp_mono_bug.zip](https://github.com/godotengine/godot/files/6854638/csharp_mono_bug.zip)

**Comment by akien-mga** [comment] 2021-07-21 10:16
That's probably expected, there have been a lot of changes to the core in the `master` branch and the Mono bindings haven't been updated to match them yet.

**Comment by Chaosus** [comment] 2021-07-21 10:17
Duplicate of https://github.com/godotengine/godot/issues/44532?

**Comment by akien-mga** [comment] 2021-07-21 10:23
I'm not sure, that one seems to be specific to Nuget, while I think the core API mismatch here is just that Mono can't match the core API at all right now.

**Comment by Zerocker** [comment] 2021-07-21 14:36
> Duplicate of #44532?
The last time I checked it was somewhere in early July (I don't remember the exact commit or PR). Then Mono worked fine.

**Comment by neikeq** [comment] 2021-07-21 20:37
C# is expected to be broken on latest master after recent internal changes to Godot's core. I'll be fixing it this week.

**Comment by willnationsdev** [comment] 2021-08-01 22:59
I may have also encountered this issue. When attempting to create a C# script, the Editor crashes. Going to share the backtrace and mono log here, in case it is helpful.

```
[0] Object::call (C:\Users\Will\source\repos\godot\core\object\object.cpp:773)
[1] Object::call (C:\Users\Will\source\repos\godot\core\object\object.cpp:773)
[2] CSharpLanguage::reload_tool_script (C:\Users\Will\source\repos\godot\modules\mono\csharp_script.cpp:764)
[3] ResourceFormatSaverCSharpScript::save (C:\Users\Will\source\repos\godot\modules\mono\csharp_script.cpp:3603)
[4] ResourceSaver::save (C:\Users\Will\source\repos\godot\core\io\resource_saver.cpp:117)
[5] ScriptCreateDialog::_create_new (C:\Users\Will\source\repos\godot\editor\script_create_dialog.cpp:321)
[6] ScriptCreateDialog::ok_pressed (C:\Users\Will\source\repos\godot\editor\script_create_dialog.cpp:286)
[7] AcceptDialog::_ok_pressed (C:\Users\Will\source\repos\godot\scene\gui\dialogs.cpp:106)
[8] call_with_variant_args_helper<AcceptDialog> (C:\Users\Will\source\repos\godot\core\variant\binder_common.h:223)
[9] call_with_variant_args<AcceptDialog> (C:\Users\Will\source\repos\godot\core\variant\binder_common.h:333)
[10] CallableCustomMethodPointer<AcceptDialog>::call (C:\Users\Will\source\repos\godot\core\object\callable_method_pointer.h:97)
[11] Callable::call (C:\Users\Will\source\repos\godot\core\variant\callable.cpp:51)
[12] Object::emit_signal (C:\Users\Will\source\repos\godot\core\object\object.cpp:1100)
[13] Object::emit_signal (C:\Users\Will\source\repos\godot\core\object\object.cpp:1155)
[14] BaseButton::_pressed (C:\Users\Will\source\repos\godot\scene\gui\base_button.cpp:128)
[15] BaseButton::on_action_event (C:\Users\Will\source\repos\godot\scene\gui\base_button.cpp:168)
[16] BaseButton::_gui_input (C:\Users\Will\source\repos\godot\scene\gui\base_button.cpp:67)
[17] call_with_variant_args_helper<BaseButton,Ref<InputEvent>,0> (C:\Users\Will\source\repos\godot\core\variant\binder_common.h:223)
[18] call_with_variant_args_dv<BaseButton,Ref<InputEvent> > (C:\Users\Will\source\repos\godot\core\variant\binder_common.h:366)
[19] MethodBindT<BaseButton,Ref<InputEvent> >::call (C:\Users\Will\source\repos\godot\core\object\method_bind.h:287)
[20] Viewport::_gui_call_input (C:\Users\Will\source\repos\godot\scene\main\viewport.cpp:1646)
[21] Viewport::_gui_input_event (C:\Users\Will\source\repos\godot\scene\main\viewport.cpp:1968)
[22] Viewport::input (C:\Users\Will\source\repos\godot\scene\main\viewport.cpp:3095)
[23] Window::_window_input (C:\Users\Will\source\repos\godot\scene\main\window.cpp:922)
[24] call_with_variant_args_helper<Window,Ref<InputEvent> const &,0> (C:\Users\Will\source\repos\godot\core\variant\binder_common.h:218)
[25] call_with_variant_args<Window,Ref<InputEvent> const &> (C:\Users\Will\source\repos\godot\core\variant\binder_common.h:333)
[26] CallableCustomMethodPointer<Window,Ref<InputEvent> const &>::call (C:\Users\Will\source\repos\godot\core\object\callable_method_pointer.h:97)
[27] Callable::call (C:\Users\Will\source\repos\godot\core\variant\callable.cpp:51)
[28] DisplayServerWindows::_dispatch_input_event (C:\Users\Will\source\repos\godot\platform\windows\display_server_windows.cpp:1803)
[29] DisplayServerWindows::_dispatch_input_events (C:\Users\Will\source\repos\godot\platform\windows\display_server_windows.cpp:1777)
[30] Input::_parse_input_event_impl (C:\Users\Will\source\repos\godot\core\input\input.cpp:642)
[31] Input::parse_input_event (C:\Users\Will\source\repos\godot\core\input\input.cpp:465)
[32] Input::flush_accumulated_events (C:\Users\Will\source\repos\godot\core\input\input.cpp:858)
[33] DisplayServerWindows::process_events (C:\Users\Will\source\repos\godot\platform\windows\display_server_windows.cpp:1530)
[34] OS_Windows::run (C:\Users\Will\source\repos\godot\platform\windows\os_windows.cpp:626)
[35] widechar_main (C:\Users\Will\source\repos\godot\platform\windows\godot_windows.cpp:163)
[36] _main (C:\Users\Will\source\repos\godot\platform\windows\godot_windows.cpp:185)
[37] main (C:\Users\Will\source\repos\godot\platform\windows\godot_windows.cpp:199)
[38] __scrt_common_main_seh (D:\agent\_work\9\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288)
[39] BaseThreadInitThunk
-- END OF BACKTRACE --
```

Mono log:
[2021-08-01_16.33.35_13048.log](https://github.com/godotengine/godot/files/6913561/2021-08-01_16.33.35_13048.log)

**Comment by neikeq** [comment] 2021-10-02 12:56
Can you check if #52293 fixes this issue?

**Comment by raulsntos** [comment] 2022-08-26 16:37
Closing per @zrckr's comment.

**Closed by raulsntos** 2022-08-26 16:37 UTC
Labels: bug, topic:dotnet, regression
