### ISSUE TITLE
Web export is not working properly for Godot 4.0

### ISSUE THREAD

**Issue by ahmutkadim** [godotengine/godot#74882] opened 2023-03-13 21:12 UTC
### Godot version

4.0

### System information

MacOS arm64 

### Issue description

I do not know whether this is an engine problem or my own mistake but it looks like godots web export does not work. When I run it on a local apache server, it says that some features are missing for the server and even it does not run in itch.io servers. When I tried to run it from godots built in webgl tester, it did not open up in safari (stuck at loading) and took time to load in firefox and google chromee. Also in google chrome and firefox some of the colors of the ui elements were wrong and hovering did not work as expected for some ui elements.

### Steps to reproduce

I do not know whether this is an engine problem or my own mistake but it looks like godots web export does not work. When I run it on a local apache server, it says that some features are missing for the server and even it does not run in itch.io servers. When I tried to run it from godots built in webgl tester, it did not open up in safari (stuck at loading) and took time to load in firefox and google chromee. Also in google chrome and firefox some of the colors of the ui elements were wrong and hovering did not work as expected for some ui elements.

### Minimal reproduction project

Reproduction is not necessary since it would occur with any web export on Godot 4

**Comment by clayjohn** [comment] 2023-03-13 21:16
You need to enable sharedArrayBuffer support in order to host Godot apps on Itch.io. Itch.io has a setting for you to enable this. 

The game not loading on safari is actually a very slow load time which comes from a bug in safari that is apparently fixed in an update that should be coming soon https://github.com/godotengine/godot/issues/70691

**Comment by ahmutkadim** [comment] 2023-03-13 21:21
There is also problem with rendering ui items, for which some of their colors are not displayed properly and hovering over buttons leads to unexpected results. I created game with mobile rendering but according to my experimentation it looks even though ı changed web exporting rendering from gl compatible to mobile, it exports with gl compatible regardless. What may I do.

**Comment by Calinou** [comment] 2023-03-13 21:25
> What may I do.

We recommend sticking to Godot 3.x (and using its GLES2 renderer) if you want reliable exporting to HTML5.

**Comment by ahmutkadim** [comment] 2023-03-13 21:29
It does occur in macOS when run natively.

**Comment by Calinou** [comment] 2023-03-13 21:51
> It does occur in macOS when run natively.

Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

**Comment by ahmutkadim** [comment] 2023-03-13 22:19
[troubleshoot demonstration.zip](https://github.com/godotengine/godot/files/10962312/troubleshoot.demonstration.zip)

Here is the minimal demonstration as zip. I configured renderer to be gl compatible but you can change to mobile to see the difference and issue. I advice to not click on any intractable parts since I did not edited the scripts so I do not know how it will behave for missing files.

**Comment by chadrbanks** [comment] 2023-03-16 13:12
Yeah, I can confirm that if you try to run my game on Mac or iOS then it does not work. Android and Windows run fine. Link below. This game ran fine on iOS and Mac before I updated from v3.5.x to v4.x recently. Would love a workaround or fix asap. Where do I report in the community to help replicate, investigate, and repair this?

https://chadrbanks.itch.io/one-click-toast

**Comment by Calinou** [comment] 2023-03-17 00:06
- Duplicate of https://github.com/godotengine/godot/issues/70691 (same cause).

**Closed by Calinou** 2023-03-17 00:06 UTC
Labels: platform:web, topic:porting

**Comment by ahmutkadim** [comment] 2023-03-20 16:54
It seems like starting a project with compatibility mode fixes my issue from start to an extend but does anyone knows when Godot 4.0 web export will be fixed? It does not work for any iOS device, in any browser and it does not work on safari and it boots slow on other browsers.

**Comment by ahmutkadim** [comment] 2023-03-20 21:55
When is Godot 4.1 is planned to come out?

**Comment by Calinou** [comment] 2023-03-20 22:04
> When is Godot 4.1 is planned to come out?

[There is no ETA provided](https://docs.godotengine.org/en/latest/about/release_policy.html#when-is-the-next-release-out) as usual. We recommend sticking to Godot 3.5 when targeting HTML5 for now.
