### ISSUE TITLE
Tooltip Theme doesn's work

### ISSUE THREAD

**Issue by chenjie199234** [godotengine/godot#18478] opened 2018-04-28 06:25 UTC
V3.0.2 stable
I create a Button and add a tooltip.
add a theme contains TooltipLabel to the button.
set a red color
but nothing happened!
![4sc7d_r j10q 4 2e52hk r](https://user-images.githubusercontent.com/29348971/39392844-0676bd3c-4af0-11e8-92a8-1609517a9b75.png)
![zc s dj1 gto0t w v gc](https://user-images.githubusercontent.com/29348971/39392845-06c7394c-4af0-11e8-88c8-bf81ef210505.png)
![2zd4bj g2s0qe 5menj30vn](https://user-images.githubusercontent.com/29348971/39392846-070f18fc-4af0-11e8-913e-f36329d72697.png)

**Comment by merumelu** [comment] 2018-10-29 16:18
Can't reproduce this in master.
![0542](https://user-images.githubusercontent.com/17676847/47663999-6a53e980-db9e-11e8-92ef-0f4044bca9b4.png)

**Comment by mastermarkus** [comment] 2019-01-17 00:52
Having same problem on Godot 3.0.6 64bit, Windows10 and I'm not able to reproduce issue also

**Comment by KoBeWi** [comment] 2019-04-25 19:35
This is fixed in 3.1.

**Comment by groud** [comment] 2019-04-25 19:37
Closing as fixed on 3.1 then.

**Closed by groud** 2019-04-25 19:37 UTC
Labels: bug, topic:core
