### ISSUE TITLE
Reparenting nodes with drag & drop

### ISSUE THREAD

**Issue by unfa** [godotengine/godot#2084] opened 2015-06-13 19:24 UTC
I think this could speed the workflow a lot.
Drag a node, drop it on it's new parent, and done!

What do you think?

**Comment by reduz** [comment] 2015-06-13 19:50
eventually

**Comment by kubecz3k** [comment] 2015-10-30 12:37
Closing since it's a duplicate of https://github.com/godotengine/godot/issues/570

**Closed by kubecz3k** 2015-10-30 12:37 UTC
Labels: feature request, topic:editor
