### ISSUE TITLE
When saving a scene for the first time in the editor, the FileDialog does not autofill the name of the scene root name anymore

### ISSUE THREAD

**Issue by golddotasksquestions** [godotengine/godot#81484] opened 2023-09-09 11:27 UTC
### Godot version

4.2 Dev4

### System information

Win10 Nvidea

### Issue description

This is a regression from 4.2 dev3 to 4.2 dev4.

In all previous versions before Godot 4.2 dev4, when you created a new scene, named the root node "anything", hit Ctrl+S, the FileDialog would open and "anything.tscn" would have been proposed as name. You would only have to hit Enter or click "Save" and that's it.

Now in Godot 4.2 dev4 I manually have to rewrite the scene name before I can save the scene. This feels like a regression and huge loss in usability.

### Steps to reproduce

1. Create a new scene
2. Name Root node (or not)
3. Save scene
4. Observe the "File:" LineEdit in the FileDialog being empty.

### Minimal reproduction project

N/A

**Comment by AThousandShips** [comment] 2023-09-09 11:31
Duplicate of #81225

**Closed by AThousandShips** 2023-09-09 11:31 UTC
