### ISSUE TITLE
Rendering Glitches/Sprites Flickering on Chrome and Vivaldi

### ISSUE THREAD

**Issue by henriiquecampos** [godotengine/godot#18013] opened 2018-04-06 02:54 UTC
**Godot version: 3.0.2**

**OS/device including version: Windows 10, GeForce GTX 660, Google Chrome 65.0.3325.181 64-bit and Vivaldi 1.14.1077.60 32-bit**

**Issue description:**

For some reason the game flicks A LOT, like...is unplayable when running on these browsers, game works like a charm on Firefox 59.0.2 (64-bit)

**Steps to reproduce:**
You guys know I try to give the most information as possible, but I don't have any idea what's happening this time

**Minimal reproduction project:**

[web.zip](https://github.com/godotengine/godot/files/1882531/web.zip)

Also the source code:
https://github.com/pigdevstudio/one_game_a_month/tree/master/permanence

I think this can be related to either Joystick Vibration or [Camera Shaking](https://github.com/pigdevstudio/one_game_a_month/blob/master/permanence/levels/level_01/level_01.tscn#L21-L41) as the flickering occurs every time these behaviors happen, but it also happens randomly when Labels are animated (which happens simultaneously with screen shake some times, so I think it is a better clue)

**Comment by puppetmaster-** [comment] 2018-04-06 07:00
maybe it has something to do with https://github.com/godotengine/godot/issues/16918

**Comment by akien-mga** [comment] 2018-04-06 07:03
CC @eska014

**Comment by eska014** [comment] 2018-04-06 10:56
This is a duplicate of #16281, caused by 2D particles.

**Closed by eska014** 2018-04-06 10:56 UTC
Labels: bug, platform:html5, topic:rendering
