### ISSUE TITLE
_draw is not visible with Control Node

### ISSUE THREAD

**Issue by AlexHolly** [godotengine/godot#18842] opened 2018-05-13 17:51 UTC
Godot Master
x11

It works with a Node2D but not with a Control

This shows the rect
```
extends Node2D

func _ready():
	set_position(Vector2(0,0)) # Draw visible

func _draw():
	draw_rect(Rect2(0,0,10,10), Color(1,0,0,1), true)
```

No rect visible
```
extends Control

func _ready():
	set_position(Vector2(0,0)) # Draw not visible
	#set_position(Vector2(1,1)) # Draw visible

func _draw():
	draw_rect(Rect2(0,0,10,10), Color(1,0,0,1), true)
```

**Comment by groud** [comment] 2018-05-15 17:30
Duplicate of #17917

**Closed by groud** 2018-05-15 17:30 UTC
