### ISSUE TITLE
Vector2 values < 0.0005 are shown as integer 0 in Debug panel

### ISSUE THREAD

**Issue by trollusk** [godotengine/godot#76930] opened 2023-05-10 22:50 UTC
### Godot version

4.0.2

### System information

Windows 11

### Issue description

If a Vector2 value has "small" x or y values (< 0.0005), then in the Stack Variables part of the Debug panel, the values will be shown as "0". Hovering with the mouse also shows 0. Only by hovering over the variable name in the script window, can you see the actual value.

This can lead to annoying bugs where values are not close enough to zero for `is_zero_approx` to be true, yet are presented as being zero in the Debugger.

I suggest only rounding to zero if `is_zero_approx` is true for the value. Also, hovering over the value in the Stack Variables list should display the unrounded value in the tooltip.

![image](https://github.com/godotengine/godot/assets/220468/76197876-f0ef-4503-b71a-76f6d37c7950)
![image](https://github.com/godotengine/godot/assets/220468/ce525699-ac7a-4098-ad30-bf646813c19f)

### Steps to reproduce

Set a Vector2 variable to small x and y values.
Set a breakpoint.
Inspect the variable's value in the debugger.

### Minimal reproduction project

N/A

**Comment by Calinou** [comment] 2023-05-10 23:01
Thanks for the report! Consolidating in https://github.com/godotengine/godot/issues/18251- Duplicate of https://github.com/godotengine/godot/issues/18251, as the inspector and debugger rely on the same code.

**Closed by Calinou** 2023-05-10 23:01 UTC
