### ISSUE TITLE
UDP Network latency problem

### ISSUE THREAD

**Issue by yatebyaeby** [godotengine/godot#86740] opened 2024-01-03 09:22 UTC
### Tested versions

v4.2.1.stable.official [b09f793f5]

### System information

Godot v4.2.1.stable - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3060 (NVIDIA; 31.0.15.3742) - Intel(R) Core(TM) i5-6400 CPU @ 2.70GHz (4 Threads)

### Issue description

Duplicate https://github.com/godotengine/godot/issues/81915

UDPServer or PacketPeerUDP gets big latency on LAN network
Its 27msec for only PING command between Server and 1 Client
But its about 50msec for only PING command between Server and 3 Clients

### Steps to reproduce

1. Start Project below
2. Run 2 or More Instances
![image](https://github.com/godotengine/godot/assets/129945583/35a0ee1a-2916-4df2-acf6-1b8bd2dd56e6)
3. Choose one windows press F2 to create Server
4. Choose other and press F1 to create Client
5. Get ping 27-50msec on LAN

### Minimal reproduction project (MRP)

[ServerUDP.zip](https://github.com/godotengine/godot/files/13817352/ServerUDP.zip)

**Comment by AThousandShips** [comment] 2024-01-03 10:36
Why is this open as a separate issue?

**Comment by yatebyaeby** [comment] 2024-01-03 15:31
> Why is this open as a separate issue?

the previous example is more complex, its more easy to understand and testing

**Comment by AThousandShips** [comment] 2024-01-03 15:32
If it's the same issue only one report should exist, update the other one instead 🙂

Closing as a duplicate of that one

**Closed by AThousandShips** 2024-01-03 15:32 UTC
