### ISSUE TITLE
Raycast2D.add_exception() not working with TileMap node

### ISSUE THREAD

**Issue by wingedadventurer** [godotengine/godot#22891] opened 2018-10-09 18:29 UTC
**Godot version:**
Latest stable (3.0.6)
2018-10-09 daily build

**Issue description:**
Like the title says, it seems that Raycast2D (and probably Raycast 3D) doesn't add a properly setup TileMap with collisions to its exceptions when using `add_exception()` to the detected TileMap.

I made a TileMap consisting of walls with collisions. Tileset was set up correctly as intented. I spread a RayCast across some placed tiles, and I made a code where if the ray detects any node, it adds it as an exception. The code works perfectly for any type of collision object, except for TileSet which is never added to its exceptions.

Check the minimal reproduction project for more info.

**Minimal reproduction project:**
[Raycast TileMap bug.zip](https://github.com/godotengine/godot/files/2461693/Raycast.TileMap.bug.zip) (made with Godot stable 3.0.6)

Edit: **Turn on visible collision shapes to actually see your raycast.**

**Comment by groud** [comment] 2018-10-10 09:42
Can you try with 3.1 alpha ?

**Comment by wingedadventurer** [comment] 2018-10-10 10:43
@groud I've just tried with 3.1 alpha, and add_exception() still fails with TileMap.

**Comment by Razzlegames** [comment] 2019-09-23 00:13
This is too bad, since I was doing things like this, but now I get an infinite loop if tilemaps with collision are present :( :

I can prob get away with just grabbing the first colliding body any not looping for now.

```gdscript

func _physics_process(delta):
	
	var collision_obj_to_add_back = []
	while is_colliding():
		var col = get_collider()

		if  col is PhysicsBody2D :
			col.propagate_call("setOneWayCollision", [disable_collisions, physics_object], true)
		if !(col is Area2D):
			collision_obj_to_add_back.append(col)
		add_exception(col)
		force_raycast_update()

	for col in collision_obj_to_add_back:
		remove_exception(col)
```

**Comment by akien-mga** [comment] 2020-01-09 08:25
Related to #24739 and #27282. The TileMap and GridMap collision logic needs to be reworked to properly solve these issues.

**Comment by KoBeWi** [comment] 2020-12-10 13:21
Still valid in 3.2.4 beta3

This is weird though. The `add_exception()` has this condition:
https://github.com/godotengine/godot/blob/2ac8c3b6dc211ed7cf62b9971a3c8eaadad7a3b2/scene/2d/ray_cast_2d.cpp#L239-L242
It's expected that TileMaps are omitted, buuut there's also `add_exception_rid()`, which doesn't have this check. However `add_exception_rid(RID(collider))` doesn't work either, while theoretically it should 🤔

**Comment by groud** [comment] 2021-05-24 14:31
Related to/duplicate of: https://github.com/godotengine/godot/issues/17090

**Comment by KoBeWi** [comment] 2021-05-24 15:37
Closing as duplicate of #17090

**Closed by KoBeWi** 2021-05-24 15:37 UTC
Labels: bug, confirmed, topic:core, topic:physics
