### ISSUE TITLE
Analogue input mappings cause digital ones for the same action to be eaten

### ISSUE THREAD

**Issue by JustMog** [godotengine/godot#74202] opened 2023-03-02 02:12 UTC
### Godot version

v4.0.stable.official

### System information

Windows 11

### Issue description

When an action in the input map has both key (or button) events and analogue stick events, the key and button events are sometimes dropped, acting as if the button was released when it wasn't.
This happens only when a controller is plugged in (tested with ps4 & xbox 360).
Affects both Input.is_action_pressed and Input.get_axis, unsure about other functions/events.

### Steps to reproduce

run the repro project with a controller plugged in and use left & right arrow keys & left & right on the dpad to move the sprite.
it should stop unexpectedly, sometimes starting again after a moment and other times requiring the button to be released & repressed.
seems to happen fairly frequently but may take a few seconds. may be more noticeable with the dpad than keyboard.
i have also noticed the same issue in the official platformer demo project.

### Minimal reproduction project

[project.zip](https://github.com/godotengine/godot/files/10866912/project.zip)

**Comment by JustMog** [comment] 2023-03-02 02:19
oh, this may be #45628. apologies for the duplicate if so, didnt show up in my initial search.

**Comment by akien-mga** [comment] 2023-03-02 09:21
Duplicate of https://github.com/godotengine/godot/issues/45628 indeed. No worry, we prefer duplicate reports to not knowing about bugs ;)

**Closed by akien-mga** 2023-03-02 09:21 UTC
