### ISSUE TITLE
Cannot use `is` with variables on right

### ISSUE THREAD

**Issue by bitwes** [godotengine/godot#73906] opened 2023-02-25 04:40 UTC
### Godot version

v4.0.rc5.official.6296b4600

### System information

MacOS Ventura 13.0

### Issue description

Using `is` with a variable on the right side of the expression causes parser errors.

I assume there is something in the release notes or documentation as this seems it breaks a lot of code,  but it's difficult finding good results for "is".  I didn't see anything in the documentation or any other issues with these errors.  This appears to have started in RC4.  

## Scenario 1
Using a loaded script on the right side of `is` causes "<script var> is a variable but does not contain a type."
``` gdscript
# res://scratch/simple_script.gd
var foo = 'bar'
```
``` gdscript
# res://demo1.gd
extends SceneTree
var SimpleScript = load('res://scratch/simple_script.gd')

func _init():
    var foo = SimpleScript.new()
    if(foo is SimpleScript):
        print('it is')
    else:
        print('it is not')

```
```
SCRIPT ERROR: Parse Error: "SimpleScript" is a variable but does not contain a type.
```

## Scenario 2
Using `is` with a passed in value generates a "Could not find type <param name> in the current scope" parser error.
```gdscript
# res://demo2.gd
extends SceneTree

func check_is(thing, the_class):
    if(thing is the_class):
        print('it is')
    else:
        print('it is not')

func _init():
    quit()
```
```
SCRIPT ERROR: Parse Error: Could not find type "the_class" in the current scope.
```

### Steps to reproduce

See description

### Minimal reproduction project

See description

**Comment by AThousandShips** [comment] 2023-02-25 05:49
Duplicate of #73722

**Closed** 2023-02-25 08:43 UTC
Labels: archived

**Comment by Zireael07** [comment] 2023-03-04 08:20
This or the other should be pinned and/or documented better.
