### ISSUE TITLE
BaseButton.is_hovered() returning true while LMB is pressed and mouse has left the button

### ISSUE THREAD

**Issue by Muller-Castro** [godotengine/godot#32727] opened 2019-10-10 19:52 UTC
**Godot version:** 3.1.1.stable

**OS/device including version:** Windows 10 18362

**Issue description:** The function should return false after the mouse leaves the button, even with the LMB pressed

**Steps to reproduce:**

![IsHovered](https://user-images.githubusercontent.com/37383316/66601348-10b1b880-eb7e-11e9-9337-e46185aa188b.gif)

**Minimal reproduction project:**

**Comment by groud** [comment] 2019-10-10 20:24
Closing as a duplicate of #20881.

**Closed** 2019-10-10 20:24 UTC
Labels: bug, topic:core
