### ISSUE TITLE
Duplicated resources share UID

### ISSUE THREAD

**Issue by mrjustaguy** [godotengine/godot#55732] opened 2021-12-08 14:53 UTC
### Godot version

v4.0.dev.20211117.official [175690957]

### System information

Windows 11, Vulkan, Nvidia Quadro K2000 461.92

### Issue description

I created a Standard Material, made changes, and made several duplicates from within Godot's File System (not from Windows) and  assigned different textures to each of the duplicates. When restarting the editor, I noticed all the materials suddenly used the same textures, when I looked up the Material .tres files, I've noticed that they all share the same UID

### Steps to reproduce

Create a Resource
Create Duplicate of that resource from within Godot
Check UIDs of both

**Comment by akien-mga** [comment] 2021-12-08 15:18
Duplicate of #54774

**Closed by akien-mga** 2021-12-08 15:18 UTC
