### ISSUE TITLE
Parser bug: Mismatch in extents tracking stack.

### ISSUE THREAD

**Issue by riazey** [godotengine/godot#76564] opened 2023-04-28 22:47 UTC
### Godot version

4.0.2

### System information

Windows 10

### Issue description

EDIT: this was fixed by removing the offending files listed with the MRP and then dragging them back in from my desktop after opening the project~

I was developing my game then suddenly this started happening. I can no longer playtest my game.
I am not 100% sure what caused this but I believe at the time I was making a new inherited scene, saved it, then moved some scenes in the FileSystem tab?

![image](https://user-images.githubusercontent.com/75141902/235264827-62419c7d-963b-4002-9452-a6493a9bfe25.png)

### Steps to reproduce

No idea aaa- x-x

### Minimal reproduction project

Since I have no idea what caused it here's my early project :'D
https://drive.google.com/file/d/14JFZ420AelUNjBIth78msHY29rNjB55_/view?usp=share_link

I was working on these when the error occurred:
- Slot_0.tcsn
- Slot_Clickable.tscn
- Slot_Orphan.tscn
- Slot_Orphan.gd

**Comment by Calinou** [comment] 2023-04-29 01:59
> EDIT: this was fixed by removing the offending files listed with the MRP and then dragging them back in from my desktop after opening the project~

Can you reproduce this in a new project?

**Comment by riazey** [comment] 2023-04-29 07:02
I was unable to reproduce this in a new project but I remember this happening in an alpha version as well, at the time I had no idea why it happened and chalked it up to "alpha stuff". I'm not sure specifically what is triggering it tbh but thought I'd get the issue out there in case other people see it!

**Comment by dalexeev** [comment] 2023-07-11 13:16
* Duplicate of #76054.
* Will be fixed by #79301.

This happens when you edit a script and leave the lines unfinished for a couple of seconds:

```gdscript
const
```

```gdscript
func _ready():
    match 1:
        .
```

**Closed by dalexeev** 2023-07-11 13:16 UTC
Labels: bug, topic:gdscript
