### ISSUE TITLE
Output error when select a `TileMap` node in the editor

### ISSUE THREAD

**Issue by pinellos** [godotengine/godot#83185] opened 2023-10-12 08:39 UTC
### Godot version

4.x

### System information

Windows, WebEditor

### Issue description

The output print this error everytime a TileMap node is selected in editor:

`editor/editor_node.cpp:8223 - Condition "plugins_list.has(p_plugin)" is true.`

### Steps to reproduce

Add a TileMap node and add a tileset to it, then select the TileMap node in tree.

### Minimal reproduction project

N/A

**Comment by AThousandShips** [comment] 2023-10-12 08:40
What version are you on? 4.x could be any of 7 different stable versions

**Comment by pinellos** [comment] 2023-10-12 08:41
This happens on every 4.x version i've tried, 4.1.2 / 4.2 / WebEditor from Godot website...

**Comment by jakemeinershagen** [comment] 2023-12-09 15:48
Same here
Environment:
Linux Mint 21.1 Cinnamon

Godot:
v4.1.3.stable.official [f06b6836a]

Reproduce:
In my normal project it happens when I click on the tilemap.

I was able to reproduce it a blank project by following steps:

1. New project
2. Create Node2d
3. Add tilemap
4. Click on `<empty>` in the inspector to add new tileset.
5. Click on node2d
6. click on tilemap

I did notice some weird behaviors that change when the error pops up:
- If I create the tilemap and add the tileset, but make sure that I don't click on the tileset, I can click back and forth between the node 2d and tilemap without the error appearing. I can even close godot and reopen and still not get the error. However, as soon as I have clicked the tileset once I get the error every time I click the tilemap afterward.
- The above is only true in the case that the tilemap is new and the tileset on that map has not been clicked. If I create the tilemap, add a tileset, click the tileset (which gives error), remove the tileset, add new tileset (just the act of adding the tileset now creates the error)

Looks like there is a previous issue that was marked as closed for something just like this #74543 (closed by #74717).

**Comment by AThousandShips** [comment] 2023-12-09 15:49
Can you please try this in 4.2? It has been most likely resolved there

**Comment by jakemeinershagen** [comment] 2023-12-09 15:56
Yep, looks like it is resolved in 4.2. Should have checked that. Thanks

**Comment by AThousandShips** [comment] 2023-12-09 16:11
Closing as per the above, a cherry picked fix might be added to 4.1

**Closed by AThousandShips** 2023-12-09 16:11 UTC
Labels: bug, topic:editor, topic:2d
