### ISSUE TITLE
Crash on resizing Godot window diagonally

### ISSUE THREAD

**Issue by ssoher** [godotengine/godot#34520] opened 2019-12-21 17:27 UTC
**Godot version:**
3.1.2 stable

**OS/device including version:**
Windows 10 x64 1903

**Issue description:**
Resize the Godot window diagonally with fast motion and it will crash. This happens on any Godot window, including the project manager. Sometimes it takes a little effort, sometimes it's instant so if you can't reproduce it immediately, try some more. Is there a log file to see what's causing the crash?

![godot_crash](https://user-images.githubusercontent.com/4283979/71311402-cc6d4f00-242f-11ea-9d71-cf185c40ce76.gif)

**Comment by KoBeWi** [comment] 2019-12-21 18:11
> Is there a log file to see what's causing the crash?

You need to compile Godot from source and run from the console to get some useful backtrace.

**Comment by Calinou** [comment] 2019-12-21 21:28
Duplicate of #24702.

**Closed by Calinou** 2019-12-21 21:28 UTC
