### ISSUE TITLE
godot window completely dissapears, but process still runs when moving godot window to another workspace on a window manager

### ISSUE THREAD

**Issue by ana-rchy** [godotengine/godot#74317] opened 2023-03-03 19:59 UTC
### Godot version

4.0.stable

### System information

arch linux, kernel 6.2.1-arch1-1-vfio

### Issue description

the window completely dissapears if i try moving it to another workspace in bspwm, indicated by opening a terminal window and seeing it takes up the whole space so theres only one window in that workspace
the process is still alive and seems to not be frozen or anything tho

### Steps to reproduce

1. use bspwm
2. open godot
3. move the godot window to another workspace
4. 
![image](https://user-images.githubusercontent.com/85036427/222814896-f7f3a249-a595-4213-8e05-dda950280346.png)

### Minimal reproduction project

N/A

**Comment by rsubtil** [comment] 2023-03-03 23:47
Duplicate of #68471

**Comment by Calinou** [comment] 2023-03-04 00:01
- Duplicate of https://github.com/godotengine/godot/issues/68471.

**Closed by Calinou** 2023-03-04 00:01 UTC

**Comment by ana-rchy** [comment] 2023-04-02 20:06
> * Duplicate of [Godot 4 editor window disappears on BSPWM tilling manager when changing the workspace #68471](https://github.com/godotengine/godot/issues/68471).

the new 4.0.1 update fixes the random chance of window dissapearing when changing workspace, but the issue i described here, of *moving* windows, still isnt fixed
