### ISSUE TITLE
Export Project for android.

### ISSUE THREAD

**Issue by catafest** [godotengine/godot#20735] opened 2018-08-05 11:31 UTC
None
**Godot version:**

 Godot 3.0.6.stable.mono.official.8314054 with mono download and tpz templates

**OS/device including version:**

Windows 8.1

**Issue description:**

I try to use Export Project with Andoid , the button is inactive (
mono template is install but tell me is missing).

**Steps to reproduce:**
I download Godot 3.0.6.stable.mono.official.8314054
I used a minimal project from youtube tutorial
I used java settings paths:
C:/Program Files/Java/jdk1.8.0_172/bin/jarsigner.exe
C:/Program Files/Java/jdk1.8.0_172/bin/debug.keystore
my username for Android Studio path , see C:/Users/username/AppData/Local/Android/Sdk/platform-tools/adb.exe

I used this tutorial for settings : https://www.youtube.com/watch?v=QPI8JsKF2j4&t=186s

**Minimal reproduction project:**

I used a minimal project from youtube tutorial and export for windows os working well. 

This tutorial for project https://www.youtube.com/watch?v=-D-IcbsdT04

**Comment by catafest** [comment] 2018-08-05 11:34
Will be great if the team of Godot game engine will come with one tool/infos  to repair compatibility and integrity issues with export output (Android OS). I can debug this ?

**Comment by Zireael07** [comment] 2018-08-05 11:42
I believe there is no Mono export for android yet.

**Comment by dunyakilavuz** [comment] 2018-08-05 11:58
You can check #20267 to follow that issue like I do.

**Comment by vnen** [comment] 2018-08-06 15:40
Duplicate of #20267

**Closed by vnen** 2018-08-06 15:40 UTC
Labels: platform:android, topic:porting
