### ISSUE TITLE
Editor stuck in re-import loop when it can't import textures

### ISSUE THREAD

**Issue by passivestar** [godotengine/godot#90980] opened 2024-04-21 12:20 UTC
### Tested versions

v4.3.dev.custom_build [4a0160241]

### System information

Godot v4.3.dev (4a0160241) - macOS 14.4.0 - Vulkan (Forward+) - integrated Apple M1 Max - Apple M1 Max (10 Threads)

### Issue description

More aftermath of https://github.com/godotengine/godot/pull/76991. Stops when the "Import Resources When Unfocused" is disabled

https://github.com/godotengine/godot/assets/60579014/151d9493-81e2-4fd7-9915-3c6bf2db4e76

P.S I'm also wondering why those textures fail to load in the first place, they are perfectly fine jpegs

### Steps to reproduce

MRP

### Minimal reproduction project (MRP)

[MRP_reimport_loop.zip](https://github.com/godotengine/godot/files/15051864/MRP_reimport_loop.zip)

**Comment by passivestar** [comment] 2024-05-05 19:18
> P.S I'm also wondering why those textures fail to load in the first place, they are perfectly fine jpegs

Opened an issue for that: https://github.com/godotengine/godot/issues/91600

**Comment by ttencate** [comment] 2024-05-23 07:34
It's not specific to textures: the same thing also happens if Godot fails to import Blender files (#80049, #82888) and FBX files (#85402). And I don't think it's a new problem either.

As far as I can tell, this happens because the editor re-tries the import as soon as the progress dialog closes and the main editor window gains focus again.

**Comment by DanielKinsman** [comment] 2024-07-19 23:09
Easy step to reproduce, remove write permisson to  the `.godot` directory, open the editor, watch the chaos. I did this accidentally while doing docker things and it became owned by the root user.

**Comment by vnen** [comment] 2024-07-24 19:35
I have a problem like this on a project with 4.2.2, but it only happens on macOS.

**Comment by akien-mga** [comment] 2024-07-26 10:25
Duplicate of #62271, fixed in 4.3.

**Closed by akien-mga** 2024-07-26 10:25 UTC
Labels: bug, topic:editor, topic:import
