### ISSUE TITLE
Project Manager forgets all projects between runs.

### ISSUE THREAD

**Issue by murphy-slaw** [godotengine/godot#21942] opened 2018-09-10 15:59 UTC
**Godot version:**

3.1.alpha.calinou.af290f7

**OS/device including version:**

OS X Sierra 10.13.6
MacBook (Retina, 12-inch, 2017)

**Issue description:**

In the latest builds of 3.1, the project manager loads with an empty project list, even though I have previously scanned or manually added projects to it.

**Steps to reproduce:**

- Run Godot.
- Project manager opens with empty project list. <img width="1020" alt="screen shot 2018-09-10 at 8 56 01 am" src="https://user-images.githubusercontent.com/757734/45308930-7218db00-b4d7-11e8-8aa1-457e0b6c7599.png">
- Scan a directory with Godot projects in it.
- Projects appear in Project Manager <img width="1026" alt="screen shot 2018-09-10 at 8 57 16 am" src="https://user-images.githubusercontent.com/757734/45309034-ac827800-b4d7-11e8-8b72-ea91361ee25d.png">
- Load a project.
- From the project, select, Quit To Project List
- You are returned to the Project List, which is completely empty again.

**Minimal reproduction project:**

Issue is not project-dependent.

**Comment by Noshyaar** [comment] 2018-09-10 16:21
Duplicate of https://github.com/godotengine/godot/issues/21823

**Closed by Noshyaar** 2018-09-10 16:21 UTC
