### ISSUE TITLE
Updated script paths

### ISSUE THREAD

**Issue by Remixful** [godotengine/godot#53359] opened 2021-10-03 16:39 UTC
### Godot version

3.3.4 stable

### System information

Windows 10

### Issue description

After I move a few files around (in the file explorer or the FileSystem tab in Godot), the script begins to throw an error that class_name already exists at the scripts new location. If I right click the script I currently have open that is throwing this error, and then copy script path, the path is the new location, so the script editor has the right file open. The only way to fix this is to restart Godot.

### Steps to reproduce

1. Make a script, set a class_name
2. Move this script to a different folder
3. Wait for error to pop up (or soft-reload, CTRL+SHIFT+R)

**Comment by Calinou** [comment] 2021-10-03 17:42
Duplicate of https://github.com/godotengine/godot/issues/47867.

**Closed by Calinou** 2021-10-03 17:42 UTC
Labels: bug, topic:editor
