### ISSUE TITLE
@export_category breaks export var tooltips

### ISSUE THREAD

**Issue by aaandreeew** [godotengine/godot#68520] opened 2022-11-11 13:18 UTC
### Godot version

4.0 beta 4

### System information

Windows 10 (x86_64), Vulkan, Intel Core i5-8265U with UHD Graphics 620 (31.0.101.2111)

### Issue description

Edit: Clarified some language

Export variables can have editor tooltips set by preceeding their declaration with `## This is a tooltip`. This doesn't work when the export variable is contained within a custom category like `@export_category('Category')`
 
(My screenshots don't have a visible cursor, sorry)

Works fine here, out of categories:

![image](https://user-images.githubusercontent.com/114206308/201347354-72d2be13-827d-4e84-9453-c5bdaa277e30.png)
![image](https://user-images.githubusercontent.com/114206308/201347500-32d60e98-e8ea-4c7f-8aa7-3eb550db6cc6.png)

Doesn't work for export variables in categories. Tooltips still work for export variables outside of a category:

![image](https://user-images.githubusercontent.com/114206308/201347522-0fe828ae-b8ae-49c6-aaa1-b6d1f1d2781a.png)

### Steps to reproduce

 1. Create a new project and attach a script to the scene tree root (this is the quickest, but this bug applied to any other nodes I had)
 2. Create some export variables and annotate them like `## <annotation here>` on the line before each. Note how tooltips appear properly.
 3. Create an export category with `@export_category('<category name>')` on a line before. Note how tooltips won't appear for export variables in the export category.

### Minimal reproduction project

[Editor Tooltips Bug.zip](https://github.com/godotengine/godot/files/9990462/Editor.Tooltips.Bug.zip)

Created in Godot 4.0 beta 4

**Comment by YuriSizov** [comment] 2022-11-17 11:59
Duplicate of https://github.com/godotengine/godot/issues/64432.

**Closed by YuriSizov** 2022-11-17 11:59 UTC
Labels: bug, topic:gdscript, topic:editor
