### ISSUE TITLE
[Godot4] Editor UI locks up and must be killed when attempting to open scene with Window/AcceptDialog class

### ISSUE THREAD

**Issue by solorvox** [godotengine/godot#59252] opened 2022-03-17 21:53 UTC
### Godot version

v4.0.alpha4.official [f47097973]

### System information

Linux Mint 20.3, Vulkan, RTX2070

### Issue description

Godot 4.0 alpha 4 UI/editor freezes up and must be killed when attempting to open a GD 3.x project that used AcceptDialog.

### Steps to reproduce

Open project, goto res://globals and open "options (freeze).tscn".

Editor will stop reacting to all input.  Console reports spammed with:
ERROR: Attempting to use an uninitialized RID
   at: get_or_null (./core/templates/rid_owner.h:199)

### Minimal reproduction project

[gd4-a4-freeze.zip](https://github.com/godotengine/godot/files/8292804/gd4-a4-freeze.zip)

**Comment by Calinou** [comment] 2022-03-17 22:05
Duplicate of https://github.com/godotengine/godot/issues/59088 (will be fixed by https://github.com/godotengine/godot/pull/59124).

**Closed by Calinou** 2022-03-17 22:05 UTC
