### ISSUE TITLE
Data lost when wrong datatype passed to static typed function with a custom class

### ISSUE THREAD

**Issue by CitrusWire** [godotengine/godot#45049] opened 2021-01-09 19:44 UTC
**Godot version:**
3.2.3

**OS/device including version:**

Win7

**Issue description:**
Godot is invisibly losing data and changing passed values to "Null" when static typing and you pass in the wrong type.
The correct option is that it should raise an error in such cases

**Steps to reproduce:**
A script that defines a custom class:
```
class_name Pop

... whatever you want...

```

And a second script that (ab)uses it:
```
func test_func():
	var a = Rect2()
	print(a)
	second(a)

func second(b: Pop):
	print(b)
```

You'll get this back:

> (0, 0, 0, 0)
    Null

What it should be doing is raising an exception.

If you remove the static typing from `second` it will correctly print b.

**Minimal reproduction project:**

Above

**Comment by KoBeWi** [comment] 2021-01-09 23:13
Duplicate of #37312
Fixed in 4.0, backporting the fix would break compatibility.

**Closed by KoBeWi** 2021-01-09 23:13 UTC
Labels: topic:gdscript
