### ISSUE TITLE
Editor sidebar resizes when switching between Inspector and Node tabs

### ISSUE THREAD

**Issue by Vultraz** [godotengine/godot#28317] opened 2019-04-22 23:37 UTC
**Godot version:**
3.1 official, 150% scaling

**OS/device including version:**
Windows 10 64 bit

**Issue description:**
When toggling between the Inspector and Node tabs the entire right sidebar (in the default layout) will expand (when switching to Inspector) or shrink (when switching to Node) a little. Minor but a bit annoying.

**Comment by YeldhamDev** [comment] 2019-04-23 00:04
Duplicate of #25317.

**Closed by YeldhamDev** 2019-04-23 00:04 UTC
