### ISSUE TITLE
Can't lock Node3D under SubViewport (in editor)

### ISSUE THREAD

**Issue by AndHalfAFish** [godotengine/godot#80083] opened 2023-07-31 10:47 UTC
### Godot version

4.1.1

### System information

Godot v4.1.1.stable - TUXEDO OS 2 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3070 Laptop GPU () - AMD Ryzen 9 5900HX with Radeon Graphics (16 Threads)

### Issue description

3D nodes in the scene tree can be locked in the editor, to prevent accidental selection in the viewport.
3D nodes that are children of a SubViewport node cannot be locked in the same way.

### Steps to reproduce

see project file

### Minimal reproduction project

[test_node_lock.zip](https://github.com/godotengine/godot/files/12214160/test_node_lock.zip)

**Comment by KoBeWi** [comment] 2023-07-31 11:37
Duplicate of #30910

**Closed by KoBeWi** 2023-07-31 11:37 UTC

**Comment by AndHalfAFish** [comment] 2023-07-31 13:07
@KoBeWi : you wrote "Seeing how this is intended and the locking would be useless (you can't move/select nodes inside Viewport anyways...) ..." in https://github.com/godotengine/godot/issues/30910

Could you explain please what you mean ? I -can- select 3d meshes in the viewport when those meshes are under a SubViewport node.

Thanks.

**Comment by KoBeWi** [comment] 2023-07-31 13:19
Maybe it has changed since I made that comment, but seems like viewport behavior in 3D is different than in 2D. In 2D the nodes under sub-viewport are not displayed unless you display the content of the viewport somehow. I wonder if it's intended.

**Comment by AndHalfAFish** [comment] 2023-07-31 14:30
Seems like a bug to me. =)
But the issue is closed, so, it won't be fixed ...

**Comment by KoBeWi** [comment] 2023-07-31 14:37
The original issue about locks not working is still opened.
The viewport bug is a separate issue; if it turns out intended then the locks can be changed to work in viewports (I think it's a one line change).

btw you can see and edit nodes inside viewports, because they share World3D by default. They become invisible once you make the world unique, but can still be edited. This part is definitely not intended.

**Comment by AndHalfAFish** [comment] 2023-07-31 19:09
Thanks for the explanation !
