### ISSUE TITLE
Regression: Editor settings constantly getting lost

### ISSUE THREAD

**Issue by lyuma** [godotengine/godot#90895] opened 2024-04-19 11:17 UTC
### Tested versions

- Reproducible in 2efbc6b
- Not reproducible in 655e93d

### System information

Godot v4.3.dev (2efbc6bfb) - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3090 (NVIDIA; 31.0.15.3713) - Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz (16 Threads)

### Issue description

There seems to be a format incompatibility which not only prevents older Godot versions from using new editor settings, but causes editor settings to be lost any time an older version of the engine is started.

And older build of Godot, such as 4.2.1, will print the following:
```
ERROR: C:/Users/Admin/AppData/Roaming/Godot/editor_settings-4.tres:1 - Parse Error: Saved with newer format version
   at: open (scene/resources/resource_format_text.cpp:1052)
ERROR: Failed loading resource: C:/Users/Admin/AppData/Roaming/Godot/editor_settings-4.tres. Make sure resources have been imported by opening the project in the editor at least once.
   at: (core/io/resource_loader.cpp:273)
ERROR: Could not load editor settings from path: C:/Users/Admin/AppData/Roaming/Godot/editor_settings-4.tres
   at: create (editor/editor_settings.cpp:919)
```

### Steps to reproduce

1. Load the latest master version of Godot
2. Change some editor setting, such as Theme to grey
3. Open an older build of Godot, such as 4.3 from two weeks ago, or 4.2.1.
4. The older build will fail to read editor settings, so it will be on factory defaults
5. Open a new build of Godot. The older build overwrote or corrupted the settings, so even the new build will be on factory defaults.

### Minimal reproduction project (MRP)

Editor settings apply to all projects.

**Comment by akien-mga** [comment] 2024-04-19 11:25
Duplicate of 90846.

**Closed by akien-mga** 2024-04-19 11:25 UTC
