### ISSUE TITLE
InputEventScreenTouch `pressed` property isn't properly updated when lifting finger (regression in 3.5.2 RC 1)

### ISSUE THREAD

**Issue by Torguen** [godotengine/godot#70119] opened 2022-12-15 19:45 UTC
### Godot version

v3.5.2.rc1.official [f5f0543ae]

### System information

w10 64

### Issue description

When the finger is lifted, "elif !event.pressed:" is not executed,

![Captura2](https://user-images.githubusercontent.com/19652075/207952895-27987aab-5385-4110-adeb-c8015c28841c.PNG)

In 3.5.1 stable it worked correctly.

### Steps to reproduce

Run the scene.
Press click in mouse.
"pressed" is writed but "!pressed" is not written when releasing the mouse click.

### Minimal reproduction project

[inputEvent.zip](https://github.com/godotengine/godot/files/10240146/inputEvent.zip)

**Comment by akien-mga** [comment] 2022-12-15 21:39
I can confirm the regression. Likely caused by 26012ed6b62dbf7b0bf411ee55db0843c1ca45d5. CC @m4gr3d 

It is also reproducible in the `3.x` branch.

**Comment by m4gr3d** [comment] 2022-12-15 21:46
> I can confirm the regression. Likely caused by 26012ed6b62dbf7b0bf411ee55db0843c1ca45d5. CC @m4gr3d 
> 
> It is also reproducible in the `3.x` branch.

That change should only affect drag events, so it's likely to be something else. I'll take a look.

**Comment by akien-mga** [comment] 2022-12-15 22:13
> > I can confirm the regression. Likely caused by [26012ed](https://github.com/godotengine/godot/commit/26012ed6b62dbf7b0bf411ee55db0843c1ca45d5). CC @m4gr3d
> > It is also reproducible in the `3.x` branch.
> 
> That change should only affect drag events, so it's likely to be something else. I'll take a look.

I just checked on the `3.x` branch where I could reproduce the bug (as of 4d8b9be48d90a64db4027c0b5ad55b381f865f28).
Reverting b28bcb4cfc09267ebfc36a0d59289bacdaf131ce / #68630 does fix the regression.

I'm testing on Linux on a laptop with a touchscreen monitor. The bug is reproducible both with mouse clicks (emulating touch from mouse) and with the touchscreen.

**Comment by m4gr3d** [comment] 2022-12-15 22:33
> > > I can confirm the regression. Likely caused by [26012ed](https://github.com/godotengine/godot/commit/26012ed6b62dbf7b0bf411ee55db0843c1ca45d5). CC @m4gr3d
> > > It is also reproducible in the `3.x` branch.
> > 
> > That change should only affect drag events, so it's likely to be something else. I'll take a look.
> 
> I just checked on the `3.x` branch where I could reproduce the bug (as of 4d8b9be48d90a64db4027c0b5ad55b381f865f28).
> Reverting b28bcb4cfc09267ebfc36a0d59289bacdaf131ce / #68630 does fix the regression.
> 
> I'm testing on Linux on a laptop with a touchscreen monitor. The bug is reproducible both with mouse clicks (emulating touch from mouse) and with the touchscreen.

Interesting 🤔

Thanks for reproducing, I'll take a look

**Comment by akien-mga** [comment] 2022-12-22 14:23
I've reverted the `3.5` cherry-pick for now, so that it doesn't block releasing 3.5.2. (It was a fairly risky cherry-pick in the first place to make in the stable branch before it got some testing in 3.6 betas.)

I haven't reverted #68630 in the `3.x` branch though, so it's still reproducible and in need of a fix.

Should also be tested on `master` which had #68632 merged.

**Comment by HEAVYPOLY** [comment] 2023-01-04 18:37
Can confirm that reverting #68630  fixes touch release on 3.x

**Comment by m4gr3d** [comment] 2023-01-04 18:57
@HEAVYPOLY The fix for this issue is included in https://github.com/godotengine/godot/pull/70583.

**Comment by HEAVYPOLY** [comment] 2023-01-04 20:12
ok, thanks!

**Comment by akien-mga** [comment] 2023-01-09 08:26
Fixed by #70583.

**Closed by akien-mga** 2023-01-09 08:26 UTC
Labels: bug, confirmed, topic:input, regression
