### ISSUE TITLE
ImmediateGeometry set_color only works with GLES2

### ISSUE THREAD

**Issue by dbrookman** [godotengine/godot#41054] opened 2020-08-05 18:43 UTC
**Godot version:**

3.2.2.stable.official

**OS/device including version:**

macOS 10.14.6
Intel Iris 1536 MB graphics
GLES3

**Issue description:**

Geometry is rendered as black using GLES3, even if `set_color()` is called with a specified color before. A VisualShader with the Unshaded flag set in the ImmediateGeometry's Material Override will change the color, but not to the color specified in `set_color()`.
`set_color()` works as intended using GLES2.

**Steps to reproduce:**
```
clear()
begin(Mesh.PRIMITIVE_LINES, null)
set_color(Color.white)
add_vertex(Vector3.ZERO)
add_vertex(Vector3.FORWARD)
end()
```

**Minimal reproduction project:**

[set_color_bug.zip](https://github.com/godotengine/godot/files/5030459/set_color_bug.zip)

**Comment by clayjohn** [comment] 2020-08-05 18:54
I could not reproduce on Windows 10.

A few additional notes. ``set_color()`` is only used for the mesh's ``albedo`` if the SpatialMaterial has the ``use_vertex_color_as_albedo`` flag set. The reason it appears to work in GLES2 is that ``albedo`` is white by default.

I have a feeling the line appearing dark in GLES3 is an unrelated bug, probably #40170

**Comment by dbrookman** [comment] 2020-08-05 19:03
I'm also able to set arbitrary colors via `set_color()` on GLES2.
<img width="536" alt="Screen Shot 2020-08-05 at 3 01 56 PM" src="https://user-images.githubusercontent.com/53625739/89453052-42ef6080-d724-11ea-97a7-97634cd29695.png">

**Comment by clayjohn** [comment] 2020-08-05 19:13
> I'm also able to set arbitrary colors via set_color() on GLES2.

Is that using your example project or using a VisualShader?

In the example project you posted ``set_color()`` has not effect in GLES2 or GLES3 for me, unless I add a SpatialMaterial and set ``use_vertex_as_albedo``. If you are setting ``ALBEDO`` to ``COLOR`` in your own shader, it will have the same effect.

**Comment by dbrookman** [comment] 2020-08-05 19:34
Whoops, I thought I had sent the project with a material on.
I can select arbitrary colors (that only show in GLES2) when ImmediateGeometry's material override is a Spatial Material with Vertex Colors > Use As Albedo set on.

GLES2
<img width="1136" alt="Screen Shot 2020-08-05 at 3 31 53 PM" src="https://user-images.githubusercontent.com/53625739/89455827-8946be80-d728-11ea-85f0-f72d2e64553d.png">
GLES3
<img width="1136" alt="Screen Shot 2020-08-05 at 3 32 06 PM" src="https://user-images.githubusercontent.com/53625739/89455847-919ef980-d728-11ea-9362-eaa6838a9c8c.png">


[set_color_bug2.zip](https://github.com/godotengine/godot/files/5030782/set_color_bug2.zip)

**Comment by clayjohn** [comment] 2020-08-05 20:22
Can you confirm whether you are experiencing the bug in #40170

**Comment by dbrookman** [comment] 2020-08-05 20:25
Yes, it occurs exactly like [this](https://github.com/godotengine/godot/issues/40170#issuecomment-654818352).

**Comment by clayjohn** [comment] 2020-08-05 20:46
Thanks for confirming! This is a duplicate of #40170. So I'll close this issue in favour of #40170.

**Closed by clayjohn** 2020-08-05 20:46 UTC
Labels: needs testing, topic:rendering
