### ISSUE TITLE
Project Menu Bug

### ISSUE THREAD

**Issue by MrTeeXD** [godotengine/godot#28935] opened 2019-05-16 16:50 UTC
**Godot version:**

3.1.1

**OS/device including version:**

Windows 10 64bit
Intel Graphics HD 530 128MB

**Issue description:**

When opening the Project Menu in Godot, the Project Menu is so slow that you have to click a button twice for it to respond. 

**Steps to reproduce:**
1. Double Click the .exe
2. Try to click once on a project
3. You should be able to click twice to open a project

**Minimal reproduction project:**

There are no projects to reproduce this issue

**GIF of the issue**
![xT7J6QbZ3s](https://user-images.githubusercontent.com/37266538/57872187-6ec6b380-780b-11e9-8a47-1313f00a3e32.gif)

**Comment by qarmin** [comment] 2019-05-16 17:47
Have you installed the latest graphics drivers from Intel site?
I recommend Intel DSA from this site https://www.intel.com/content/www/us/en/support/detect.html

**Comment by MrTeeXD** [comment] 2019-05-16 18:42
Ah, thank you, tell me, where can i go for Godot questions because i want to ask one related to scripting?

**Comment by Calinou** [comment] 2019-05-16 20:47
Duplicate of https://github.com/godotengine/godot/issues/23069.

@MrTeeXD See [this page](https://godotengine.org/community) for a list of support channels. I recommend trying the Discord server or the Godot subreddit (/r/godot).

**Closed by Calinou** 2019-05-16 20:47 UTC
