### ISSUE TITLE
Deleting a C# Script Does Not Remove It From Solution

### ISSUE THREAD

**Issue by 11clock** [godotengine/godot#14934] opened 2017-12-22 07:44 UTC
**Godot version:**
3.0 beta 2

**OS/device including version:**
Windows

**Issue description:**
Deleting a .cs script does not remove it from the solution.

**Steps to reproduce:**
Create a .cs script, then delete it with the file explorer. Then try to play.

**Comment by Hinsbart** [comment] 2017-12-22 07:53
Duplicate of #12415

**Closed by Hinsbart** 2017-12-22 07:53 UTC
