### ISSUE TITLE
Undefined math constants breaks windows build

### ISSUE THREAD

**Issue by hammeron-art** [godotengine/godot#7627] opened 2017-01-24 16:53 UTC
Windows 10, VS2015 x64 Native Tools
scons platform=windows

I get errors about math constants (like M_PI, M_SQRT2) in many files in servers\audio\effects.
The build works if I manually define these constants in core\typedefs.h

I supposed it's a compiler specific issue.
https://msdn.microsoft.com/en-us/library/4hwaceh6.aspx 

> Math Constants are not defined in Standard C/C++. To use them, you must first define _USE_MATH_DEFINES and then include cmath or math.h.

**Comment by bojidar-bg** [comment] 2017-01-24 17:03
Duplicate of #7608

**Closed by bojidar-bg** 2017-01-24 17:03 UTC
