### ISSUE TITLE
ShaderMaterial3D Emission stops working if a second Material is rendered

### ISSUE THREAD

**Issue by Marco-MP88** [godotengine/godot#59093] opened 2022-03-13 08:57 UTC
### Godot version

4.0 alpha 4

### System information

M1 Pro Apple Silicon, Monterey 12.2.1

### Issue description

ShaderMaterial3D Emission turns black if any other Materials are being rendered.

### Steps to reproduce

- Create a 3D Scene
- Add a Meshinstance Node
- Add a Mesh
- Add a Shadermaterial to the Meshinstance Mesh
- Enable Emission
- Add another Meshinstance to another Node

If using Minimal reproduction project:
- Toggle "ToggleVisibility"-Node visibility on and off

### Minimal reproduction project

[EmissionBugM1.zip](https://github.com/godotengine/godot/files/8239219/EmissionBugM1.zip)

**Comment by Marco-MP88** [comment] 2022-03-13 14:06
Materials in general seem to not work properly on M1 Platform and it feels like Operations are not being processed at all or in the right order. This doesn't seem to just apply to Emission but to albedo too. If SDFGI, SFAO, SSIL is enabled, nested Scenes or Objects with Materials, which are already blacked out, disappear completely. Can be reproduced within a scene with 3 Models with and without a WorldEnvironment:

Model 1: No Material
Model 2: Material A
Model 3: Material B

**Comment by Calinou** [comment] 2022-03-13 16:01
Duplicate of https://github.com/godotengine/godot/issues/51898 (same cause).

**Closed by Calinou** 2022-03-13 16:01 UTC
Labels: bug, topic:rendering, topic:3d
