### ISSUE TITLE
Locked nodes are still selectable

### ISSUE THREAD

**Issue by NullNeska** [godotengine/godot#15221] opened 2017-12-31 15:09 UTC
**Godot version:**
Godot 3.0 beta 2

**OS/device including version:**
Windows 10

**Issue description:**
Everytime i try to move a node, a large locked node is selected

**Steps to reproduce:**
make a large node, lock it, make a smaller node in the same position, struggle to select the node

**Minimal reproduction project:**
![unlawfulrequiredhuman-size_restricted](https://user-images.githubusercontent.com/6185415/34462452-997feec2-ee12-11e7-83d8-d0a541b0ad48.gif)

- [x] I searched the existing [GitHub issues](https://github.com/godotengine/godot/issues?utf8=%E2%9C%93&q=is%3Aissue+) for potential duplicates.

**Comment by volzhs** [comment] 2017-12-31 18:40
it looks like you added a small size child node at big parent node.
and locked big parent node and make child node unselectable.
is that right?

**Comment by NullNeska** [comment] 2017-12-31 21:03
both nodes are not related.

**Comment by groud** [comment] 2018-09-06 16:57
This looks fixed on master branch.

**Comment by groud** [comment] 2018-09-09 19:42
Closing as likely solved, please tell if someone can reproduce the bug.

**Closed by groud** 2018-09-09 19:42 UTC
Labels: bug, topic:editor

**Comment by CarlGustavAlbertDwarfsteinYung** [comment] 2019-01-19 03:09
This is still present in 3.1 Beta 1.

**Comment by akien-mga** [comment] 2019-01-19 09:13
Can't reproduce, please provide an example project and steps to reproduce.
