### ISSUE TITLE
False Negatives on is_colliding() When Colliding with Floor

### ISSUE THREAD

**Issue by earthcrafterman** [godotengine/godot#5346] opened 2016-06-21 17:50 UTC
**Operating system or device - Godot version:**
Windows and 2.0.3

**Issue description** (what happened, and what was expected):
I was using a is_colliding() call, but for some reason while the object is indeed colliding and staying still with the terrain, the call is returning false. Even stranger is that the call returns true if it collides with a wall or the crease where the slope starts.

**Steps to reproduce:**

Download this:
https://drive.google.com/open?id=0B8GPmOdcLf_fYm5YdUQzekJzUUk

Open it and run the scene. You should notice in the output that it says "Colliding" when you press against a wall, but not when you are idling or moving along the floor.

**Link to minimal example project** (optional but very welcome):

https://drive.google.com/open?id=0B8GPmOdcLf_fYm5YdUQzekJzUUk0111222

**Comment by henkz1** [comment] 2016-06-22 15:11
I think the bug is in your code. The collision happens after you check if it's colliding with ground, then the collision is resolved in "HandleCollision". It looks like it's working when colliding with the wall because the slide move in "HandleCollision" results in a new collision with the floor.
You can ask the community for help http://godotengine.org/community.

**Comment by earthcrafterman** [comment] 2016-06-23 00:39
Thank you, I was able to fix it by moving it all under HandleCollisions

**Comment by vnen** [comment] 2016-06-23 00:56
Good that you solved it. Closing as it is not a bug.

**Closed by vnen** 2016-06-23 00:56 UTC
