### ISSUE TITLE
Script editor text clipping through UI

### ISSUE THREAD

**Issue by Keetz** [godotengine/godot#12395] opened 2017-10-25 09:09 UTC
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
2.1.4 (This didn't happen in 2.1.3)
Ubuntu 16.04

**Issue description:**
Text clips through the bottom of the script editor

**Steps to reproduce:**
Write some code and open the Output beneath the script editor and try to resize it to see how the text clips through.

In the second picture i just grabbed the border and started resizing till the text started clipping through.

![selection_051](https://user-images.githubusercontent.com/6707330/31990115-74f05e70-b974-11e7-9cbd-969771722061.jpg)
![selection_052](https://user-images.githubusercontent.com/6707330/31990106-709547b4-b974-11e7-8d55-34490a2d194b.jpg)

**Comment by akien-mga** [comment] 2017-10-25 09:41
Duplicate of #10738, fixed in 2.1 branch already.

**Closed by akien-mga** 2017-10-25 09:41 UTC
