### ISSUE TITLE
LightmapGI: Pixellated Shadows

### ISSUE THREAD

**Issue by WickedInsignia** [godotengine/godot#63435] opened 2022-07-25 12:16 UTC
### Godot version

4.0 Alpha 12

### System information

Windows 10, GTX1080, i7 6700

### Issue description

Godot 4's LightmapGI exhibits pixelated shadows. This is a regression from the improved CPU lightmapper in 3.x.

### Godot 4's lightmap shadows with a directional light:
![Godot4LightmapGIShadows](https://user-images.githubusercontent.com/70243134/180775025-9888c6c5-13ef-44b9-9df2-a79c6032921e.JPG)

### Godot 3's lightmap shadows with identical scene settings:
![Godot3LightmapGIShadows](https://user-images.githubusercontent.com/70243134/180775152-c03af37f-f93e-49d9-84b0-f6d2d8da69b1.JPG)

### Steps to reproduce

- Open MPR
- Optionally, bake any light in Godot 4 with shadows active

### Minimal reproduction project

Godot 4:
[LightmapQualityExampleG4.zip](https://github.com/godotengine/godot/files/9181015/LightmapQualityExampleG4.zip)

Godot 3.4.4:
[LightmapQualityExampleG3.zip](https://github.com/godotengine/godot/files/9181020/LightmapQualityExampleG3.zip)

**Comment by Calinou** [comment] 2022-07-25 12:16
Duplicate of https://github.com/godotengine/godot/issues/49935.

**Closed by Calinou** 2022-07-25 12:16 UTC

**Comment by WickedInsignia** [comment] 2022-07-25 12:19
@Calinou I noticed light bleeding in G4 vs G3.
Could this be due to the lack of bicubic sampling or possibly another issue?

Godot 4:
![LightmapBleed01_Godot4](https://user-images.githubusercontent.com/70243134/180775894-94d7e386-2a2f-4bfe-84a2-162a4eeda43c.JPG)
![LightmapBleed02_Godot4](https://user-images.githubusercontent.com/70243134/180775918-6a9cf958-b00a-488a-9c1b-40f765a3bff3.JPG)

Godot 3:
![LightmapBleed01_Godot3](https://user-images.githubusercontent.com/70243134/180775951-106da761-469c-4638-befb-28f9abff6e8b.JPG)
![LightmapBleed02_Godot3](https://user-images.githubusercontent.com/70243134/180775975-835ccba1-3133-4674-a165-f7396c0b3359.JPG)

**Comment by Calinou** [comment] 2022-07-25 12:38
> @Calinou I noticed light bleeding in G4 vs G3.
> Could this be due to the lack of bicubic sampling or possibly another issue?
> Just gauging whether to bother with a report to keep track of it.

Please create a separate issue with a minimal reproduction project attached. I could notice increased lightmap bleeding when [updating the global illumination demo to readd lightmaps](https://github.com/godotengine/godot-demo-projects/pull/759), but haven't found any combination of settings that resolves it.
