### ISSUE TITLE
Labels/text UV's behave oddly with CanvasItem shaders

### ISSUE THREAD

**Issue by RitzyMage** [godotengine/godot#50503] opened 2021-07-15 23:04 UTC
### Godot version

3.3.stable

### System information

Windows 10, GLES 3

### Issue description

For buttons or labels when using a canvas shader, I expect the text UV's to match their location on the screen. However, they do not. Instead, each letter uses UV's from some other point (I'm not sure where it is determined actually).

![image](https://user-images.githubusercontent.com/35404417/125868378-fff9705c-fb12-4947-b66e-a29d297b1c5d.png)

In the image above, I am using the example gradient shader [here](https://docs.godotengine.org/en/stable/tutorials/shading/your_first_shader/your_first_canvasitem_shader.html#your-first-fragment-function). I expect that the text would blend in with the background, but instead each letter is a solid color that corresponds to which letter it is rather than the position in the button.

### Steps to reproduce

Create a label or button and give it a custom shader like the following:

`shader_type canvas_item;

void fragment() {
  COLOR = vec4(UV, 0.5, 1.0);
}`

(although any fragment or vertex shader that reads from the UV's will probably not behave as expected; this is just a simple example)

### Minimal reproduction project

[buttonShader.zip](https://github.com/godotengine/godot/files/6826645/buttonShader.zip)

**Comment by Calinou** [comment] 2021-07-15 23:22
Duplicate of https://github.com/godotengine/godot/issues/23210.

**Closed by Calinou** 2021-07-15 23:22 UTC
