### ISSUE TITLE
DisplayServer: Unresponsive UI on Windows, any project

### ISSUE THREAD

**Issue by TibRib** [godotengine/godot#45609] opened 2021-01-31 19:23 UTC
**Godot version:**
Godot Engine v4.0.dev.custom_build.02eb11450
_Using ICU / HarfBuzz / Graphite text server_

**OS/device including version:**
Vulkan graphics API, GTX 1080 with latest Nvidia drivers, Windows 10 Pro (Insider Preview 21301)

**Issue description:**
```
ERROR: Condition "!windows.has(event_from_window->get_window_id())" is true.
   at: DisplayServerWindows::_dispatch_input_event (platform\windows\display_server_windows.cpp:1787)
```
After a minute or less, the Godot UI does not listen anymore to user interactions. It is not frozen, as the editor window still shows the scene in movement : Good frametimes, objects moving (@tool)... Even the "Save & Close / Don't Save" window that appears as I hit the windows exit button is not listening to clicks.

Also the editor takes up to 10 seconds to display itself when loading a blank project - I am not sure if this is related.

As I wanted to port my current work on Godot 4.0 beta, this issue is quite a hassle.

**Steps to reproduce:**
- Create/load a new project with latest godot 4.0
- Create a Node3D
- Put a WorldEnvironment inside of the Node3D
- Play with its settings.
I am not sure whether or not the usage of the WorldEnvironment node is in cause but I am sure to make this UI issue happen when reproducing these steps.

**Minimal reproduction project:**

[VulkanTest.zip](https://github.com/godotengine/godot/files/5900479/VulkanTest.zip)

Thank you for your time, and for your lovely work on the engine 😃

**Comment by Calinou** [comment] 2021-01-31 19:27
> As I wanted to port my current work on Godot 4.0 beta, this issue is quite a hassle.

It's not even an *alpha* yet :slightly_smiling_face:

**Comment by TibRib** [comment] 2021-01-31 21:58
Thank you for your reactivity !

The `--single-window` workaround seems to work with my small project configuration, 

By the way, you are right, it is not an alpha yet, my apologies...

**Comment by Calinou** [comment] 2021-01-31 22:06
Duplicate of https://github.com/godotengine/godot/issues/45325.

**Closed by Calinou** 2021-01-31 22:06 UTC
Labels: bug, platform:windows, regression, topic:editor
