### ISSUE TITLE
Scaling characters with multiple RigidBody2Ds (Workaround?)

### ISSUE THREAD

**Issue by footurist** [godotengine/godot#16727] opened 2018-02-15 20:31 UTC
I have a character with multiple `RigidBody2Ds`, that also has a bone skeleton for animation over them. Now, the problem is, that the physics engine handles the transforms of the bodies, so they won't scale properly. If you scale the children (`CollisionShape2Ds` and `Sprites`) the positions will be off, although I tried changing them. Is anybody aware of a proper way to work around this? Being able to scale these kind of characters would be awesome.

Thanks for all your answers.
Greetings, Footurist

**Comment by eon-s** [comment] 2018-02-15 22:52
I assume this is a feature request for allowing scaled bodies (if is a question better try the Q&A).

Not sure why the physics engine can't handle scale (states have a transform), if that is for performance reasons, enabling scale can be optional on project settings.

Related https://github.com/godotengine/godot/issues/5734 (try the state scale option mentioned on that issue)

**Comment by Footurist** [comment] 2018-02-15 23:29
@eon-s I guess it is. Well I remember @reduz saying, that this is because the physics engine overrides the transforms if you try to scale the body (at least for RigidBody2D). I also remember him saying, that he was considering to implement axis flipping for physics bodies. How can I make this a feature request?

**Comment by eon-s** [comment] 2018-02-15 23:55
@Footurist just redact it as a feature request, or be clear that scaling can help in that use case.

**Comment by akien-mga** [comment] 2020-01-27 09:08
Duplicate of #5734.

**Closed by akien-mga** 2020-01-27 09:08 UTC
Labels: feature proposal, topic:physics
