### ISSUE TITLE
Editor crashes when working with VSCode if the language server is running

### ISSUE THREAD

**Issue by git2013vb** [godotengine/godot#73146] opened 2023-02-12 07:18 UTC
### Godot version

v4.0.rc1.official [8843d9ad3]

### System information

Debian 11

### Issue description

I have several projects that I'm used to open at same time (mostly two at same time - [client/server], [client/castle], ...)

And usually I have to set the language server into different ports because I use vscode as editor.

The crash happen when I do some changes in vscode like: 
- copy paste code form script to another script in the same project or in another project
- copy paste in the same script 

in both case the pastes script will be indented to the last row of. An it seems the crash happen just after the end of paste action
To me seems the language server shut down the editor for whatever reason. I'm not sure 100% but it can be related to many vscode editors opened at same time. 
As long I recall it never happen when I use just one vscode instance.

So godot close itself without any warnings/errors so I suppose its a crash.

Because it is a random issue I cannot give any MRP at this time. Sorry.

It happen in beta version too. I didn't report it before because I thought is was a problem related to beta stage.

Thanks

### Steps to reproduce

My use case is:
Two project opened using vscode as editor (client/server)
- server running
- working on client
we suppose I run the client and it break to an error
If i do not stop the client and I go to vscode to change anything the godot editor close itself (often happen even if I stop the running client and then go in vscode to modify the code)

### Minimal reproduction project

na

**Comment by YuriSizov** [comment] 2023-02-12 10:23
Not much can be said from your logged error, it's just the end of the trace, not the root of the problem. Only live debugging would help there, or more specific steps to reproduce.

> It happen in beta version too. I didn't report it before because I thought is was a problem related to beta stage.

Problems related to the beta stage are only going to be resolved during beta if they are reported. Otherwise they will simply remain problems, unsolved and still present.

**Comment by git2013vb** [comment] 2023-02-15 07:57
>Problems related to the beta stage are only going to be resolved during beta if they are reported. Otherwise they will simply remain problems, unsolved and still present.

Well its depends. 
If the issue can be fixed during that stage it will be, otherwise it will be postponed to the next. It happen often.

Sure the early the issue will be reported the better is.. But this one is so weird that I was hoping to be related to other issues in beta stage.  Its not that I could give more details two months ago - also at that time I was not in the mood :)

It is still possible that is related because there are several issues in beta stage that are not yet fixed. So I think we can wait.

**Comment by YuriSizov** [comment] 2023-03-10 11:43
Seems like this is a duplicate of your own previous report: https://github.com/godotengine/godot/issues/71016. Since this other issue has some details about your crash, I'm going to close this one in favor of the other.

**Closed by YuriSizov** 2023-03-10 11:43 UTC
Labels: bug, topic:editor, needs testing, crash
