### ISSUE TITLE
`Godot.Collections.Dictionary` shares reference when used in inherited scene

### ISSUE THREAD

**Issue by markdibarry** [godotengine/godot#65589] opened 2022-09-09 20:37 UTC
### Godot version

4.0.dev (d2a6a187f4)

### System information

Windows 10

### Issue description

Can't think of a better title as this is a confusing bug.
When a scene has a `Godot.Collection.Dictionary`, and is inherited once, it works as expected. When inherited a second time, the `Dictionary` seems to share the same reference for all instances of the scene.

Example:
![image](https://user-images.githubusercontent.com/21325943/189438624-055d6213-3ccc-4386-887c-0682068700ad.png)
Produces the following output:
![image](https://user-images.githubusercontent.com/21325943/189438677-c44816b4-c966-4752-84d0-91da1d43d37c.png)

However, changing the scene to a twice inherited scene:
![image](https://user-images.githubusercontent.com/21325943/189438530-8225627a-a1b5-4fad-97c2-81f94c594eb4.png)
Produces the following output:
![image](https://user-images.githubusercontent.com/21325943/189438584-b5408e99-982b-4092-95c7-45c0279516fd.png)

### Steps to reproduce

See MRP.

### Minimal reproduction project

[DictionaryBug.zip](https://github.com/godotengine/godot/files/9538521/DictionaryBug.zip)

**Comment by raulsntos** [comment] 2022-09-09 23:54
If you take a look at the scene files, the `OptionDisplayInheritedTwice.tscn` contains an instantiated dictionary while `OptionDisplayInherited.tscn` has the dictionary set to null. I think that's what causes the issue and it doesn't have anything to do with inheritance.

I've also been able to reproduce this with GDScript so it doesn't seem related to .NET and sounds to me like it may be a duplicate of https://github.com/godotengine/godot/issues/16478 or https://github.com/godotengine/godot/issues/48038.

**Comment by markdibarry** [comment] 2022-09-10 00:36
Thanks for the insight, @raulsntos! You're definitely on to something. After some more testing I have a few findings:
1. I notice setting a `Dictionary<string, Variant>` with a property initializer results in some console error spam:
![image](https://user-images.githubusercontent.com/21325943/189461229-b52d84fd-1ff1-47d5-8f2b-69175a7a0862.png)
2. The picture begins to complete itself with why `Dictionary` is initialized in the scene file: If any script in the pipeline is a tool script, the collection will be initialized in the constructor or `_Ready` or wherever you normally initialize it, so any changes to the scene will result in saving the initialized `Dictionary`, and in turn corrupting the `.tscn` file.

So it seems to make sense, though I don't think initialized fields should cause `Dictionary`s to be shared. As you said, this doesn't seem to be a C# specific issue, though it is a long-standing bug, so in the meantime it'd be good to caution users to not use collections in tool scripts, or to manually fix them on save until this can be resolve.

**Comment by markdibarry** [comment] 2022-09-10 14:18
I'm going to close this since it looks like this is a long-known bug and isn't planned to be fixed. However the property initializer error spam may be worth looking into.

**Closed** 2022-09-10 14:19 UTC
Labels: bug, topic:dotnet
