### ISSUE TITLE
Unstable, glitchy RigidBody3D simulation for small objects

### ISSUE THREAD

**Issue by vinrato** [godotengine/godot#75026] opened 2023-03-17 13:12 UTC
### Godot version

v4.0.stable.official [92bee43ad]

### System information

Windows 11, Vulkan, RTX 2060 (driver version 31.0.15.3118)

### Issue description

Small RigidBody3D objects are glitchy as they often went through objects and get stuck in them while twitching.
I have messed with the physics parameters and they don't do much, I even enabled continuous collision detection and the issue still persists.

https://user-images.githubusercontent.com/72286622/225913026-8f8fa9a2-f7b4-4ab9-9319-daa5ff1b3988.mp4

### Steps to reproduce

1. Create a RigidBody3D with CollisionShape3D of a box with its 'y' axis size reduced
2. Run the game

### Minimal reproduction project

N/A

**Comment by Calinou** [comment] 2023-03-17 22:07
- Duplicate of https://github.com/godotengine/godot/issues/61827.

**Closed by Calinou** 2023-03-17 22:07 UTC
