### ISSUE TITLE
Godot 4 class Window don't display anything in editor.

### ISSUE THREAD

**Issue by filantus** [godotengine/godot#62376] opened 2022-06-24 12:54 UTC
### Godot version

v4.0.alpha10.official [4bbe7f0b9]

### System information

Windows 10, GLES3

### Issue description

Don't know it's a bug or not. Sorry if i'm not understood something. But it's definitely looks wrong and inconvenient to me.

Problem: In Godot 4 class Window don't display anything in editor. Just black screen.

<img width="1280" alt="2022-06-24_15-46-14" src="https://user-images.githubusercontent.com/13046849/175539356-c9cbf905-f7fb-43d8-92a7-4c1ea86ffc9b.png">

In runtime content of Window is displayed normally.

<img width="1280" alt="2022-06-24_15-59-12" src="https://user-images.githubusercontent.com/13046849/175540923-72ce3828-71ee-4a9c-bcd4-348fb11dcd5b.png">

### Steps to reproduce

See screenshot above. Add a Window and any UI inside.

**Comment by Calinou** [comment] 2022-06-24 16:17
Duplicate of https://github.com/godotengine/godot/issues/61034.

**Closed by Calinou** 2022-06-24 16:17 UTC
Labels: bug, topic:gui
