### ISSUE TITLE
Editor crashs when modifying material preoperties of draw passes mesh (pass 1) in GPUParticles3D (Godot 4.0.beta15)

### ISSUE THREAD

**Issue by remicombelles** [godotengine/godot#72146] opened 2023-01-26 23:00 UTC
### Godot version

4.0.beta15

### System information

Windows 10 64bits, Vulkan, NVidia GPU, Intel CPU (no integrated graphics)

### Issue description

Editor crashs when modifying material preoperties of draw passes mesh (pass 1) in GPUParticles3D.
It is not happening every time. (I would say 3 times / 10)

### Steps to reproduce

1. Add a GPUParticles3D node
2. Add a ParticleProcessMaterial to the Process Material field of the node
3. Add a mesh (a sphere in my case) in the Pass1 field of Draw Passes
4. Add a StandardMaterial3D to the mesh
5. Modify parameters in the material created (Billboard > particle billboard make it crashs for me)

### Minimal reproduction project

N/A

**Comment by Zireael07** [comment] 2023-01-27 16:58
Duplicate of https://github.com/godotengine/godot/issues/69454 ?

**Comment by akien-mga** [comment] 2023-01-27 17:11
Would be good if you could test in beta 16 which fixed similar issues indeed.

**Comment by remicombelles** [comment] 2023-01-27 17:16
> Duplicate of #69454 ?

I don't think so because #69454 is not about the material parameters but about mesh parameters (that seems to work fine for me)

**Comment by remicombelles** [comment] 2023-01-27 17:28
> Would be good if you could test in beta 16 which fixed similar issues indeed.

It seems to work on beta 16 ! (Tried on a new project and the one that caused crash before)
Should I close this issue ?

**Closed** 2023-02-02 13:24 UTC
Labels: bug, topic:rendering, topic:editor, crash
