### ISSUE TITLE
Tilemap Atlas Name - Entering name prints backwards in textbox

### ISSUE THREAD

**Issue by devEyesgood** [godotengine/godot#73539] opened 2023-02-18 00:22 UTC
### Godot version

v4.0.rc2.official [d2699dc7a]

### System information

Windows 11 Pro, AMD Ryzen 7, 32GB, GTX 1660 Ti

### Issue description

When entering text into the Atlas Name field, the text displays backwards.
![image](https://user-images.githubusercontent.com/16976618/219820244-2a0b5a91-0704-4415-a2d6-7764fe5e4c8d.png)

### Steps to reproduce

Create Tilemap.  Drag an image to create an Atlas.  Give the Atlas a name.  Name prints backwards as you type.

### Minimal reproduction project

see above.

**Comment by gotnospirit** [comment] 2023-02-18 01:28
Duplicate of #72289

**Comment by YuriSizov** [comment] 2023-02-18 01:37
Indeed, it is.

**Closed by YuriSizov** 2023-02-18 01:37 UTC

**Comment by devEyesgood** [comment] 2023-02-18 01:45
Oops.  I didn't see #72289.  Apologies.
