### ISSUE TITLE
Asset production pipeline with blender issues: Scenes' animations not properly updated upon reimport

### ISSUE THREAD

**Issue by Maveyyl** [godotengine/godot#51123] opened 2021-07-31 21:24 UTC
### Godot version

3.3.2-stable-mono

### System information

Windows 10, blender 2.92.0

### Issue description

I export an asset in glTF format from blender 2.92.0, it contains a mesh, a material, a skeleton, and animations.

I import that glTF file in godot and can use it as a scene and it has everything I wanted in it.

Problems arise when I update the animations en blender and reimport the glTF. If I instantiate a new scene from it it has the update, but all the instantiated scenes from it do not get updated.

Scenes inheriting from it get updated only if I try to create a new inherited scene from the updated and reimported glTF. But not the scenes instantiated from the inherited scene.

I was expecting that inheriting scenes would be updated automatically.

### Steps to reproduce

Create any 3D object with an animation.

Export in glTF. Import in godot, instantiate it, create an instantiated scene of it as well.

Update the animation in blender.

Export in glTF again and replace to former file. Reimport the asset in godot. Nothing should have changed.

**Comment by fire** [comment] 2021-07-31 21:39
I think the current behaviour requires a Godot Engine restart in some cases.

This is not good. Maybe we should document those cases so it's less frustrating.

**Comment by Calinou** [comment] 2021-07-31 23:03
Duplicate of https://github.com/godotengine/godot/issues/38853.

**Closed by Calinou** 2021-07-31 23:03 UTC
