### ISSUE TITLE
Floating Point Exports only display 3 digits of the Mantissa

### ISSUE THREAD

**Issue by Skullfurious** [godotengine/godot#38100] opened 2020-04-22 01:33 UTC
**Godot version:**
3.2.stable.official

**OS/device including version:**
Windows 10 
**Issue description:**
Editor Exports only displays 3 digits of the Mantissa. Not sure why.
**Steps to reproduce:**
Export any fraction with more than 3 digits in the mantissa side and you will see what I mean when you view its parameters in the node inspector.

![PxUf3Ww 1](https://user-images.githubusercontent.com/34455502/79930904-0f602300-8420-11ea-8090-7abcb7d505c4.png)

**Minimal reproduction project:**

**Comment by Skullfurious** [comment] 2020-04-22 01:53
![Screen_Shot_2020-04-21_at_6 49 08_PM 1](https://user-images.githubusercontent.com/34455502/79931951-a5954880-8422-11ea-9d47-c77c432491f9.png)

Apologies.

**Comment by Skullfurious** [comment] 2020-04-22 01:54
I will comment that it may be useful to display more digits of the mantissa even if the float step is smaller than the currently set one.

**Comment by Skullfurious** [comment] 2020-05-06 13:24
I realize that this was archived but there is some ambiguity with the UI due to the nature of this issue.

Essentially, if I export a more precise value from my project it will never appear in the editor unless my step value is as precise as the exported value.

The issue here is that it's called "Step Value" and as far as I can tell, rather than stepping, it also appears to **round* the value to the editors step value which might not be ideal for all types of precision.

This would also not be as bad of a problem if stepping through these values wasn't so slow for higher precision values. Perhaps allow us to have a step value property exported with the exported variable?
![2wJh5g6 1](https://user-images.githubusercontent.com/34455502/81182087-bfd33880-8f83-11ea-9ff6-4a4dea4f2c2e.png)

**Comment by Calinou** [comment] 2020-05-06 13:52
Duplicate of #18251.

**Closed** 2020-05-11 09:06 UTC
Labels: archived

**Comment by Zireael07** [comment] 2020-05-13 16:48
I just got bit by a similar issue, but not in exported variable, I was looking at the debugger and it said the value was 0, while it was 0.000000028 IRC. This is a serious problem for debugging, as it leads people to think the function/variable doesn't work, while it does!

**Comment by Calinou** [comment] 2020-05-14 07:21
@Zireael07 I'm fairly sure the debugger uses EditorSpinSlider, except properties are set to be read-only.

**Comment by Zireael07** [comment] 2020-05-14 07:25
Hm, should I make an issue about changing the debugger to using some other control in order to avoid the problem here or on godot-proposals, then? Changing to some other control node is a proposal, but it's in order to fix a bug...

**Comment by Calinou** [comment] 2020-05-14 07:56
@Zireael07 I think we should try to fix the rounding bug in EditorSpinSlider instead.

**Comment by Zireael07** [comment] 2020-05-14 07:59
Which of the two duplicates should I leave a note in, then?

**Comment by Calinou** [comment] 2020-05-14 08:05
@Zireael07 Probably #18251.
