### ISSUE TITLE
3.2.2rc1 sometimes opens project list instead of playing project

### ISSUE THREAD

**Issue by hmans** [godotengine/godot#39564] opened 2020-06-15 12:43 UTC
**Godot version:**
3.2.2.rc1.official

**OS/device including version:**
Windows 10 (19041.329), nVidia GTX 1060, GLES3

**Issue description:**
Sometimes, when I hit F5 to play the project (start its main scene), instead of doing that, Godot will open the project list (the one that typically appears when starting up the editor.) 

**Steps to reproduce:**
This appears to happen randomly, and I have not been able to find a way to reliable reproduce it. To make things worse, I haven't been able to provoke the issue at all with a blank (except for an empty 2D scene) project. My guess is that this is somehow related to scene loading, and the bigger your project gets, the more likely you are to encounter this issue. (Unfortunately, I can't attach my current game project here.)

I will try some other projects to see if I can find a way to reliably reproduce the issue.

**Edit:** I haven't done any significant work with the 3.2.2 betas, so I can't say if this is a regression new to RC1. But I did work with 3.2.1 for a while and never encountered the issue there.

**Comment by akien-mga** [comment] 2020-06-15 12:58
Duplicate of #28036.

**Closed by akien-mga** 2020-06-15 12:58 UTC

**Comment by hmans** [comment] 2020-06-15 13:04
Oof, I really tried finding an existing issue, but apparently I didn't try hard enough. ;-) Thanks and sorry for the trouble!

**Comment by akien-mga** [comment] 2020-06-15 13:11
No worry, it was not easy to find unless you knew that it's there :)
