### ISSUE TITLE
Various errors are printed to the console when closing editor

### ISSUE THREAD

**Issue by enxas** [godotengine/godot#78031] opened 2023-06-09 07:41 UTC
### Godot version

v4.1.beta1.mono.official [828ec2c5d]

### System information

Godot v4.1.beta1.mono - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1660 Ti with Max-Q Design (NVIDIA; 31.0.15.3179) - Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 Threads)

### Issue description
When closing editor various errors are printed to the console. Could be related to this #69614
```
WARNING: Scan thread aborted...
     at: _notification (editor/editor_file_system.cpp:1224)
ERROR: Attempt to disconnect a nonexistent connection from '@ConfirmationDialog@16960:<ConfirmationDialog#1160312314556>'. Signal: 'confirmed', callable: 'Delegate::Invoke'.
   at: (core/object/object.cpp:1353)
ERROR: Attempt to disconnect a nonexistent connection from '<VBoxContainer#1160714967762>'. Signal: 'ready', callable: 'Delegate::Invoke'.
   at: (core/object/object.cpp:1353)
ERROR: Attempt to disconnect a nonexistent connection from '@Button@16969:<Button#1161352501997>'. Signal: 'pressed', callable: 'Delegate::Invoke'.
   at: (core/object/object.cpp:1353)
ERROR: Attempt to disconnect a nonexistent connection from '@PopupMenu@16968:<PopupMenu#1160983403226>'. Signal: 'id_pressed', callable: 'Delegate::Invoke'.
   at: (core/object/object.cpp:1353)
ERROR: Attempt to disconnect a nonexistent connection from '<EditorSettings#-9223372008903932759>'. Signal: 'settings_changed', callable: 'Delegate::Invoke'.
   at: (core/object/object.cpp:1353)
ERROR: Condition "!EditorSettings::get_singleton() || !EditorSettings::get_singleton()->has_setting(p_setting)" is true. Returning: Variant()
   at: _EDITOR_GET (editor/editor_settings.cpp:1117)
WARNING: ObjectDB instances leaked at exit (run with --verbose for details).
     at: cleanup (core/object/object.cpp:2021)
ERROR: Resources still in use at exit (run with --verbose for details).
   at: clear (core/io/resource.cpp:489)
ERROR: Pages in use exist at exit in PagedAllocator: N7Variant5Pools11BucketSmallE
   at: ~PagedAllocator (./core/templates/paged_allocator.h:170)
```

### Steps to reproduce

Run project couple of times.
Close editor.
Errors will be printed to the console.

### Minimal reproduction project

[MRP.zip](https://github.com/godotengine/godot/files/11703643/MRP.zip)

**Comment by AThousandShips** [comment] 2023-06-09 07:57
In the future I'd suggest updating your original report unless the new issue differs significantly, or add to the report in #78002 which has the same error in part

Also these are separate issues and should be reported separately, please search for other issues before doing so as they might already be reported

**Comment by AThousandShips** [comment] 2023-06-09 07:58
* Problem 2 is probably duplicate of #69614

**Comment by AThousandShips** [comment] 2023-06-09 08:08
You need to do that now, the "next time" was just for the first comment, as per the rules cited

**Comment by enxas** [comment] 2023-06-09 08:16
What should I do with this issue now? Should I rename it and delete additional info?

**Comment by AThousandShips** [comment] 2023-06-09 08:17
Yes, though number one is already tracked as well, so focus on 3 or 4, if they do not already exist

**Comment by AThousandShips** [comment] 2023-06-09 08:38
* The signal ones are probably the same as #34752

**Closed** 2023-06-09 19:31 UTC
Labels: bug, archived, topic:editor
