### ISSUE TITLE
Shader visually differs from playing scene and in-editor

### ISSUE THREAD

**Issue by Mikeysax** [godotengine/godot#67807] opened 2022-10-23 15:27 UTC
### Godot version

4.0beta3

### System information

PopOS 22.04, 5.19.0-76051900-generic kernel, Ryzen 6800h, Radeon 6700m, amdgpu, Vulkan

### Issue description

In editor:

![image](https://user-images.githubusercontent.com/15805689/197404425-85f6f7ed-1b9a-4082-a1f6-ff5feaffbb34.png)

![image](https://user-images.githubusercontent.com/15805689/197405689-da787f06-0134-4194-9937-f6727c728db3.png)

When playing scene:

![image](https://user-images.githubusercontent.com/15805689/197404410-6dbcf103-902d-400d-8328-90e52071f6c6.png)

### Steps to reproduce

Modifying shaders update in editor but don't show the same in game. It's not clear which is visually correct. Far and near of camera are set to the same as in editor.

### Minimal reproduction project

Reproduction Repo: https://github.com/Mikeysax/example-project-for-godot-bug-67807

It appears like the noise being used for the foam is never applied:

![image](https://user-images.githubusercontent.com/15805689/197404139-eb3c2f36-bc0a-4fd2-a856-3e7a92e90978.png)

Shader Code: https://gist.github.com/Mikeysax/a97f14e8f1d00a53c3ba83d964eeb350

**Comment by Calinou** [comment] 2022-10-23 15:30
@Mikeysax Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

From a look at the screenshots, this is likely a duplicate of https://github.com/godotengine/godot/issues/60360. Your Camera3D node may be using a Far property that's lower than the editor camera, causing the directional shadow to appear sharper when running the project. You can confirm this by enabling Camera3D preview in the editor.

**Comment by Mikeysax** [comment] 2022-10-23 16:42
@Calinou I've updated the main response with more detail and the shader code

**Comment by Calinou** [comment] 2022-10-23 17:01
What are your Camera3D' node Near and Far properties? I get a feeling the depth fade calculation is not working as intended in your shader because the depth texture's values differ from the editor camera.

**Comment by Mikeysax** [comment] 2022-10-23 17:06
> What are your Camera3D' node Near and Far properties? I get a feeling the depth fade calculation is not working as intended in your shader because the depth texture's values differ from the editor camera.

![image](https://user-images.githubusercontent.com/15805689/197405470-e55f9cfb-fe9e-4b44-8c83-d4f5c663bd39.png)

The far and near are the same as the editor (near is 0.05, far is 4000)

Here is the camera script as well: https://gist.github.com/Mikeysax/7b8b6b3c4f7de5660c3e396190d43210

**Comment by Calinou** [comment] 2022-10-23 17:40
Can you isolate the parts necessary to create a minimal reproduction project? It's impossible to say anything more about this otherwise.

**Comment by Mikeysax** [comment] 2022-10-23 18:06
> Can you isolate the parts necessary to create a minimal reproduction project? It's impossible to say anything more about this otherwise.

I've just added the repo to the original issue.

Here it is as well: https://github.com/Mikeysax/example-project-for-godot-bug-67807

**Comment by Mikeysax** [comment] 2022-10-23 18:08
@Calinou I'm noticing in the reproduction that it's no longer doing the same thing. I'm confused now. Any idea why if it's literally the same settings?

**Comment by clayjohn** [comment] 2022-10-24 23:41
To me this looks like the textures aren't being used at runtime.

**Comment by Mikeysax** [comment] 2022-10-25 01:49
> To me this looks like the textures aren't being used at runtime.

Yeah potentially. Although the lighter discoloration on the water is also a noise texture and the water also has a UV texture applied which is visible. It's the foam that different the most for some reason. I think it's potentially related to the TIME (because it's most responsible for the movement of the noise on the foam) but I'm not 100% sure.

**Comment by clayjohn** [comment] 2022-10-25 17:18
I took a look at the project and ran it through a frame debugger. All the uniforms/textures appear to be set correctly and the shader is using them. 

I noticed if you restart the editor, you get the same flat foam effect you get on running the scene, but the foam effect gets stronger with time. So I ran the scene and let it run and sure enough eventually the foam effect gets as strong as it looks in the editor. 

The problem seems to be with how you calculate ``foam_time`` Increasing the ``foam_speed`` uniform makes the foam look normal faster. Adding an offset to ``foam_time`` makes it looks good right away, but then results in it fairly quickly getting too noisy. 

You will need to refactor your foam calculations so that it is consistently at the same amount of strength. I suggest using a periodic function like ``sin()`` in your calculation of ``foam_time``

**Closed by clayjohn** 2022-10-25 17:18 UTC
Labels: topic:rendering, needs testing, topic:3d

**Comment by Mikeysax** [comment] 2022-10-25 20:42
> I took a look at the project and ran it through a frame debugger. All the uniforms/textures appear to be set correctly and the shader is using them.
> 
> I noticed if you restart the editor, you get the same flat foam effect you get on running the scene, but the foam effect gets stronger with time. So I ran the scene and let it run and sure enough eventually the foam effect gets as strong as it looks in the editor.
> 
> The problem seems to be with how you calculate `foam_time` Increasing the `foam_speed` uniform makes the foam look normal faster. Adding an offset to `foam_time` makes it looks good right away, but then results in it fairly quickly getting too noisy.
> 
> You will need to refactor your foam calculations so that it is consistently at the same amount of strength. I suggest using a periodic function like `sin()` in your calculation of `foam_time`

Thank you for this! Much appreciated for finding the bug; Glad it's not the engine itself
