### ISSUE TITLE
No anisotropic filtering with GLES2 backend

### ISSUE THREAD

**Issue by furrykef** [godotengine/godot#45641] opened 2021-02-01 18:43 UTC
**Godot version:**

3.2.4.rc1

**OS/device including version:**

Linux Mint 20.1, Radeon HD 7850, amdgpu driver

**Issue description:**

I get no anisotropic filtering at all in GLES2, at least from what I can tell. It works fine in the same project with GLES3.

Also, there is no option to change the anisotropic filtering level in the Project Settings when GLES2 is active. This setting can still be adjusted by switching to GLES3, changing the setting, and switching back, but it has no visible effect in GLES2.

I'm told anisotropic filtering used to work with the GLES2 backend, which is why I'm reporting this as a bug rather than a feature request.

**Steps to reproduce:**
Just run the attached project. Notice how much blurrier the ground is as it approaches the horizon in GLES2 mode, but not in GLES3 mode.

**Minimal reproduction project:**

[anisotropy.zip](https://github.com/godotengine/godot/files/5905955/anisotropy.zip)

**Comment by Calinou** [comment] 2021-02-01 18:46
For the record, anisotropic filtering (including configuring the anisotropic filtering level) worked back in Godot 2.x. Therefore, it should be possible to have this working in 3.2's GLES2 too.

**Comment by clayjohn** [comment] 2021-02-01 19:15
I would resist calling this a bug. Anisotropic filtering is an optional extension that hardware manufacturers can provide. AFAIK it should be supported on all hardware, but even GLES3 has to enable it with an extension check. Also, while it is available on pretty much all desktop devices, support on android (and I assume WebGL) is still not good.

It looks like is was never added to the GLES2 renderer. It is unclear whether this is by design or just because karrofel didn't have enough time. 

At any rate, it can likely be added using a similar system as in GLES3 without too much work.  

This would be a great task for someone who wants to learn a bit more about working with graphics APIs

**Comment by akien-mga** [comment] 2021-02-02 17:13
Fixed by #45654.

**Closed by akien-mga** 2021-02-02 17:13 UTC
Labels: feature proposal, topic:rendering
