### ISSUE TITLE
Match does not work when entering to set save data.

### ISSUE THREAD

**Issue by MasTho0128** [godotengine/godot#44902] opened 2021-01-03 22:54 UTC
**Godot version:**
3.2.2 Stable

**OS/device including version:**
OpenGL ES 2.0 Renderer: Intel(R) HD Graphics 4600
OpenGL ES 2.0 Batching: ON

**Issue description:**

when loading data from a dictionary and setting it to a variable then using that variable to use it in a match never enters the match (the number is within the range of the match) I solve it temporarily using an "if" like this: if value = = 1: but I had to do this for each value which is resource expenditure.

**Steps to reproduce:**

1: I used this link to save my game data. https://docs.godotengine.org/es/latest/tutorials/io/saving_games.html
2: I add it inside a singleton and send it to be called every time my game starts.
3: when reloading the data of that scene in the part of locating the nodes, I command to call the function to the object that contains the match (new_object.data()).
func data():
match value:
0:
event_1
1:
event_2
....
"event is replaced by the functions that I apply to my object"

4: It never enters the match, I had to do the check with "if".

**Minimal reproduction project:**

**Comment by Calinou** [comment] 2021-01-03 23:22
It's likely that you're trying to match a floating-point value against an integer. Use `match int(value)` instead of `match value`.

(Remember that `print` doesn't display non-significant decimals for floating-point numbers, which may make them look like integers. Use `typeof()` to be sure of that.)

**Comment by KoBeWi** [comment] 2021-01-04 11:23
Might be duplicate of #42224

**Comment by Calinou** [comment] 2021-01-04 12:10
Closing per @KoBeWi's comment.

**Closed by Calinou** 2021-01-04 12:10 UTC
