### ISSUE TITLE
Win10 compiling error when not including tools (tools=no)

### ISSUE THREAD

**Issue by thisismike97** [godotengine/godot#6334] opened 2016-08-30 20:57 UTC
**Operating system or device - Godot version:**
windows 10 insider build 14905.rs_prerelease.160811-1739
latest godot version from the master branch

**Issue description** 

Compiling error, logs below.

```
F:\Gamedev\godot>scons p=windows tools=no target=release
scons: Reading SConscript files ...
Detected MSVC compiler: amd64
Compiled program architecture will be a 64 bit executable (forcing bits=64).
scons: done reading SConscript files.
scons: Building targets ...
cl /Fomodules\visual_script\visual_script_nodes.windows.opt.64.obj /c modules\visual_script\visual_script_nodes.cpp /TP /TP /nologo /O2 /MT /Gd /GR /nologo "/IC:\Program Files (x86)\Windows Kits\10\/Include" /DWINDOWS_ENABLED /DRTAUDIO_ENABLED /DWIN32 /DTYPED_METHOD_BIND /DGLES2_ENABLED "/IF:\Programs\Visual Studio\VC\INCLUDE" "/IF:\Programs\Visual Studio\VC\ATLMFC\INCLUDE" "/IC:\Program Files (x86)\Windows Kits\10\include\10.0.14393.0\ucrt" "/IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" "/IC:\Program Files (x86)\Windows Kits\10\include\10.0.14393.0\shared" "/IC:\Program Files (x86)\Windows Kits\10\include\10.0.14393.0\um" "/IC:\Program Files (x86)\Windows Kits\10\include\10.0.14393.0\winrt" /I "/IC:/Program Files/Microsoft DirectX SDK (March 2009)/Include" /D_WIN64 -DFREETYPE_ENABLED -DENABLE_DEPRECATED /DMSVC /GR -DMUSEPACK_ENABLED -DSQUISH_ENABLED -DVORBIS_ENABLED -DOPUS_ENABLED -DTHEORA_ENABLED -DTHEORALIB_ENABLED -DPNG_ENABLED -DDDS_ENABLED -DPVR_ENABLED -DJPG_ENABLED -DWEBP_ENABLED -DSPEEX_ENABLED -DGDSCRIPT_ENABLED -DMINIZIP_ENABLED -DXML_ENABLED -DETC1_ENABLED -DGLEW_ENABLED -DGLEW_STATIC /Icore /Icore\math /Itools /Idrivers /I. /Iplatform\windows /Iplatform\windows\include /Idrivers\freetype /Idrivers\freetype\freetype\include /Imodules\godotsteam\sdk\public /Idrivers\builtin_zlib\zlib /Imodules\visual_script /Idrivers\freetype\include /Imodules\enet
visual_script_nodes.cpp
modules\visual_script\visual_script_nodes.cpp(2407): error C3254: 'VisualScriptNodeInstanceCustomNode': class contains explicit override 'instance' but does not derive from an interface that contains the function declaration
modules\visual_script\visual_script_nodes.cpp(2407): error C2838: 'instance': illegal qualified name in member declaration
modules\visual_script\visual_script_nodes.cpp(2407): error C2365: 'VisualScriptNodeInstanceCustomNode::instance': redefinition; previous definition was 'data member'
modules\visual_script\visual_script_nodes.cpp(2308): note: see declaration of 'VisualScriptNodeInstanceCustomNode::instance'
modules\visual_script\visual_script_nodes.cpp(2409): error C2371: 'VisualScriptNodeInstanceCustomNode::instance': redefinition; different basic types
modules\visual_script\visual_script_nodes.cpp(2308): note: see declaration of 'VisualScriptNodeInstanceCustomNode::instance'
modules\visual_script\visual_script_nodes.cpp(2410): error C3927: '->': trailing return type is not allowed after a non-function declarator
modules\visual_script\visual_script_nodes.cpp(2410): error C3613: missing return type after '->' ('int' assumed)
modules\visual_script\visual_script_nodes.cpp(2410): error C3646: 'instance': unknown override specifier
modules\visual_script\visual_script_nodes.cpp(2410): error C2059: syntax error: '='
modules\visual_script\visual_script_nodes.cpp(2410): error C2238: unexpected token(s) preceding ';'
modules\visual_script\visual_script_nodes.cpp(2411): error C3927: '->': trailing return type is not allowed after a non-function declarator
modules\visual_script\visual_script_nodes.cpp(2411): error C3613: missing return type after '->' ('int' assumed)
modules\visual_script\visual_script_nodes.cpp(2411): error C3646: 'in_count': unknown override specifier
modules\visual_script\visual_script_nodes.cpp(2411): error C2059: syntax error: '='
modules\visual_script\visual_script_nodes.cpp(2411): error C2238: unexpected token(s) preceding ';'
modules\visual_script\visual_script_nodes.cpp(2412): error C3927: '->': trailing return type is not allowed after a non-function declarator
modules\visual_script\visual_script_nodes.cpp(2412): error C3613: missing return type after '->' ('int' assumed)
modules\visual_script\visual_script_nodes.cpp(2412): error C3646: 'out_count': unknown override specifier
modules\visual_script\visual_script_nodes.cpp(2412): error C2059: syntax error: '='
modules\visual_script\visual_script_nodes.cpp(2412): error C2238: unexpected token(s) preceding ';'
modules\visual_script\visual_script_nodes.cpp(2414): error C2059: syntax error: 'for'
modules\visual_script\visual_script_nodes.cpp(2414): error C2143: syntax error: missing ')' before ';'
modules\visual_script\visual_script_nodes.cpp(2414): error C2238: unexpected token(s) preceding ';'
modules\visual_script\visual_script_nodes.cpp(2414): error C2143: syntax error: missing ';' before '<'
modules\visual_script\visual_script_nodes.cpp(2414): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
modules\visual_script\visual_script_nodes.cpp(2414): error C2143: syntax error: missing ';' before '++'
modules\visual_script\visual_script_nodes.cpp(2414): error C2059: syntax error: ')'
modules\visual_script\visual_script_nodes.cpp(2414): error C2334: unexpected token(s) preceding '{'; skipping apparent function body
modules\visual_script\visual_script_nodes.cpp(2419): error C2059: syntax error: 'if'
modules\visual_script\visual_script_nodes.cpp(2419): error C2334: unexpected token(s) preceding '{'; skipping apparent function body
modules\visual_script\visual_script_nodes.cpp(2421): error C2059: syntax error: 'else'
modules\visual_script\visual_script_nodes.cpp(2421): error C2334: unexpected token(s) preceding '{'; skipping apparent function body
modules\visual_script\visual_script_nodes.cpp(2425): error C2059: syntax error: 'return'
modules\visual_script\visual_script_nodes.cpp(2425): error C2238: unexpected token(s) preceding ';'
modules\visual_script\visual_script_nodes.cpp(2430): error C2628: 'VisualScriptNodeInstanceCustomNode' followed by 'void' is illegal (did you forget a ';'?)
modules\visual_script\visual_script_nodes.cpp(2430): error C2259: 'VisualScriptNodeInstanceCustomNode': cannot instantiate abstract class
modules\visual_script\visual_script_nodes.cpp(2430): note: due to following members:
modules\visual_script\visual_script_nodes.cpp(2430): note: 'int VisualScriptNodeInstance::step(const Variant **,Variant **,VisualScriptNodeInstance::StartMode,Variant *,Variant::CallError &,String &)': is abstract
f:\gamedev\godot\modules\visual_script\visual_script.h(124): note: see declaration of 'VisualScriptNodeInstance::step'
modules\visual_script\visual_script_nodes.cpp(2430): error C2556: 'VisualScriptNodeInstanceCustomNode VisualScriptCustomNode::_bind_methods(void)': overloaded function differs only by return type from 'void VisualScriptCustomNode::_bind_methods(void)'
f:\gamedev\godot\modules\visual_script\visual_script_nodes.h(619): note: see declaration of 'VisualScriptCustomNode::_bind_methods'
modules\visual_script\visual_script_nodes.cpp(2342): error C2575: 'step': only member functions and bases can be virtual
modules\visual_script\visual_script_nodes.cpp(2342): error C2601: 'step': local function definitions are illegal
modules\visual_script\visual_script_nodes.cpp(2344): error C2065: 'node': undeclared identifier
modules\visual_script\visual_script_nodes.cpp(2344): error C2227: left of '->get_script_instance' must point to class/struct/union/generic type
modules\visual_script\visual_script_nodes.cpp(2344): note: type is 'unknown-type'
modules\visual_script\visual_script_nodes.cpp(2356): error C2065: 'in_count': undeclared identifier
modules\visual_script\visual_script_nodes.cpp(2358): error C2065: 'in_count': undeclared identifier
modules\visual_script\visual_script_nodes.cpp(2362): error C2065: 'in_count': undeclared identifier
modules\visual_script\visual_script_nodes.cpp(2364): error C2065: 'work_mem_size': undeclared identifier
modules\visual_script\visual_script_nodes.cpp(2366): error C2065: 'work_mem_size': undeclared identifier
modules\visual_script\visual_script_nodes.cpp(2372): error C2065: 'node': undeclared identifier
modules\visual_script\visual_script_nodes.cpp(2372): error C2227: left of '->get_script_instance' must point to class/struct/union/generic type
modules\visual_script\visual_script_nodes.cpp(2372): note: type is 'unknown-type'
modules\visual_script\visual_script_nodes.cpp(2372): error C2227: left of '->call' must point to class/struct/union/generic type
modules\visual_script\visual_script_nodes.cpp(2385): error C2065: 'out_count': undeclared identifier
modules\visual_script\visual_script_nodes.cpp(2391): error C2065: 'work_mem_size': undeclared identifier
scons: *** [modules\visual_script\visual_script_nodes.windows.opt.64.obj] Error 2
scons: building terminated because of errors.
```

**Steps to reproduce:**
VS2015 x64 Native Tools Command Prompt
scons p=windows tools=no target=release

**Comment by vnen** [comment] 2016-08-31 00:18
Duplicate of #6291.

**Closed by vnen** 2016-08-31 00:18 UTC
