### ISSUE TITLE
Only one CanvasGroup can be used per layer

### ISSUE THREAD

**Issue by markdibarry** [godotengine/godot#60301] opened 2022-04-16 14:36 UTC
### Godot version

4.0 dev (d27f60f)

### System information

Windows 10, Vulkan

### Issue description

`CanvasGroup`s solve the problem of having many displayed nodes that make up a unit but not being able to apply a shader to them as a unit. This also solves the alpha issue with normal node groups in the example below:
![labelex](https://user-images.githubusercontent.com/21325943/163677891-82739592-a47b-4e15-ab3b-fe8e897484eb.png)

The most common use case for `CanvasGroup` is for multi-part sprites, for example:
* A character that can "hold" different weapons/armor.
* A character that has customizable appearance.

The second example can be achieved by using the `use parent material` flag if there is a shallow hierarchy, but requires some heavy and fragile `Viewport` manipulation if not.

`CanvasGroup`s currently have a few bugs associated with them, though some visual glitches will be fixed by #59989. However, even with this fix, `CanvasGroup` currently cannot be used more than once in a `CanvasLayer`, or the higher-priority group will override the display of any other groups near it. `CharacterBody2D`s shouldn't be placed in their own `CanvasLayer` (or anything to do with collision due to unexpected results, and would be ridiculous to maintain even if it did work), which unfortunately makes the `CanvasGroup` node unable to be used for its main purpose.

Here is an example of the issue:
![cg0](https://user-images.githubusercontent.com/21325943/163679018-db6d10fa-df10-428f-9c07-d073d0152d46.png)
![cg1](https://user-images.githubusercontent.com/21325943/163679019-8464b9e4-8b93-4eb1-a475-4bbe9926e735.png)
![cg2](https://user-images.githubusercontent.com/21325943/163679021-5a310577-6e64-4db7-a7d6-acbe6370c99c.png)

### Steps to reproduce

N/A

### Minimal reproduction project

[CanvasGroupBug.zip](https://github.com/godotengine/godot/files/8500095/CanvasGroupBug.zip)

**Comment by insomniacUNDERSCORElemon** [comment] 2022-04-19 20:18
MRP seems to work as-expected (in admittedly-outdated alpha5). If I change it so the *parent* is a canvasgroup instead (even if I change 1 of 2 canvasgroups into node2d) then the selfmodulate alpha is *inverted* and a backbuffer issue (similar-but-opposite of the one you show) can happen.

Similarly (especially clipping also using backbuffer just like canvasgroup), as I've mentioned on https://github.com/godotengine/godot/issues/49198, clipping (`clip children` visibility option of canvasitems) cannot be stacked (parent that clips a child that clips), which limits some effects or character options (especially in the context of engine-created art).

Pulling it back to canvasgroup this version of the issue is still bad, for instance if you had something like an ethereal/glass sword/shield (or maybe even something like a user-set-transparency paint-job on a car) and you needed to make the entire character fade then it wouldn't work right.

Side note: any canvasitem with clipping enabled is a functional equivalent to a canvasgroup. So while you can't really mix them together, it isn't really needed.

**Comment by golddotasksquestions** [comment] 2022-04-28 17:07
I was just trying to duplicate a CanvasGroup (with 4 icon Sprite2Ds as children), and Godot immediately crashed and closed itself.

Godot Alpha 7 ( v4.0.alpha7.official [3e9ead05f] )
Win 64, Nvidea 765M

**Comment by that-richard** [comment] 2022-09-18 12:14
Can confirm it's still happening in Godot 4.0 Beta 1

![image](https://user-images.githubusercontent.com/11839880/190901560-eb15be18-3bc3-436f-ad3f-9a430fce6396.png)

**Comment by insomniacUNDERSCORElemon** [comment] 2022-09-18 19:26
So I can confirm with beta 1 now as well, so alpha 4 that I was using must have different behavior. 

Though the behavior of a canvasgroup nested in another canvasgroup (the child CG having inverted selfmodulation) still occurs.

**Comment by clayjohn** [comment] 2022-10-07 19:22
I'm changing the label from "bug" to "enhancement". Currently CanvasGroup's piggyback on the BackBuffer system we currently have in place, meaning that they rely on the background ``SCREEN_TEXTURE``. As such they can only nest one layer deep i.e. you cannot have a CanvasGroup inside another CanvasGroup. 

While this is a major limitation, it is not a bug _per se_. I believe it may be possible to remove this limitation, but the only options I can think of would add significant performance cost and would dramatically increase the complexity of the implementation. We will have to put some thought into how this can be done and if it would be worth the extra cost/complexity.

**Comment by markdibarry** [comment] 2022-10-07 19:38
@clayjohn There may be a misunderstanding. I would suggest that this specific ticket (not being able to use more than one `CanvasGroup` per layer) is still very much a bug, because otherwise `CanvasGroup` is not being able to be used for original advertised purpose, is extremely limited in use and would be better suited as an addon.

However, I agree that the separate issue you mention of nesting `CanvasGroup` nodes, is a limitation and worth exploring as an enhancement. Though, it would make it more versatile.

**Comment by clayjohn** [comment] 2022-10-07 20:58
> @clayjohn There may be a misunderstanding. I would suggest that this specific ticket (not being able to use more than one `CanvasGroup` per layer) is still very much a bug, because otherwise `CanvasGroup` is not able to be used for its original advertised purpose, is extremely limited in use, and would be better suited as an addon. If the problem the node is intended to solve can't be achieved in our current system (described in this [blog post](https://godotengine.org/article/godots-2d-engine-gets-several-improvements-upcoming-40)), it may be better to remove the feature before 4.0 is released until the system is improved to be able to support it.
> 
> However, I agree that the separate issue you mention of nesting `CanvasGroup` nodes, is a limitation and worth exploring as an enhancement. Though, it would make it more versatile.

Yes, you are right. I was confusing this with the nesting CanvasGroup issue. The issue reported here is indeed a bug and I believe I know how to solve it! :)

**Closed** 2022-10-08 11:56 UTC
Labels: bug, topic:rendering, topic:2d
