### ISSUE TITLE
World Grid Glitch

### ISSUE THREAD

**Issue by Elsarques** [godotengine/godot#93405] opened 2024-06-20 17:35 UTC
### Tested versions

- Reproducible in: 4.2.2 Stable

### System information

Android 14 Godot 4.2.2 Stable Mali GPU

### Issue description

The world grid is glitchy
![Screenshot_20240620_143102_Godot Editor 4](https://github.com/godotengine/godot/assets/168835907/9d10c2ac-410b-4784-ab74-1958968b8314)

### Steps to reproduce

Open Godot

### Minimal reproduction project (MRP)

[VendedorAuto.zip](https://github.com/user-attachments/files/15917754/VendedorAuto.zip)

**Comment by Chaosus** [comment] 2024-06-20 18:39
Duplicate of https://github.com/godotengine/godot/issues/37016, and was fixed at master.

**Comment by Calinou** [comment] 2024-06-20 23:02
Thanks for the report! Consolidating in https://github.com/godotengine/godot/issues/73763.

**Closed by Calinou** 2024-06-20 23:02 UTC
Labels: bug, topic:editor, topic:3d
