### ISSUE TITLE
Navigation does not always work with gluing (3.0)

### ISSUE THREAD

**Issue by DimaKiva** [godotengine/godot#12275] opened 2017-10-21 06:24 UTC
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
3.0 custom_build

**Issue description:**
The navigation grid does not always work with gluing.
Navmesh consists of several parts, with different positions and different orientations. But it's not always working.

To test the path in the example, Immediate draw the line.

![11](https://user-images.githubusercontent.com/11325733/31848777-4214f990-b66b-11e7-9400-918e3045fa98.png)
![22](https://user-images.githubusercontent.com/11325733/31848783-55467728-b66b-11e7-95a9-2417aef62bb7.png)

**Link to minimal example project:**
[Bug navmesh.zip](https://github.com/godotengine/godot/files/1403849/Bug.navmesh.zip)

**Comment by Zireael07** [comment] 2017-10-21 07:49
Did you check that the vertices match *exactly*? Even 0.000001 of overlap will stop your navmesh from working...

**Comment by DimaKiva** [comment] 2017-10-21 08:18
> Did you check that the vertices match exactly?
It's impossible. A floating point number cannot be leveled.
It would be nice if the navigator thought recognize close points (if dist vertex to vertex < 0.1) as one.

**Comment by reduz** [comment] 2017-11-07 14:36
navigation has a parameter where you can specify the tolerance for gluing

**Comment by Zireael07** [comment] 2017-11-07 14:54
What, where? is that one of the new things that came with recast?

**Comment by akien-mga** [comment] 2018-01-06 23:02
We have now entered release freeze for Godot 3.0 and want to focus only on release critical issues for that milestone. Therefore, we're moving this issue to the 3.1 milestone, though a fix may be made available for a 3.0.x maintenance release after it has been tested in the master branch during 3.1 development. If you consider that this issue is critical enough to warrant blocking the 3.0 release until fixed, please comment so that we can assess it more in-depth.

**Comment by DimaKiva** [comment] 2018-01-07 07:47
Not scary. Up to 3.1 will be tolerated.

**Comment by akien-mga** [comment] 2018-01-09 17:39
Maybe this is a duplicate of #7246 ?

**Comment by Zireael07** [comment] 2018-05-18 15:41
Very possibly.

**Comment by reduz** [comment] 2018-09-05 21:31
We will probably be rewriting how navigation works in 3.2/4.0, including improving how gluing works (this does not work in this issue because gluing only happens when edges are 100% matched including both points), so kicking it to 3.2

**Comment by KoBeWi** [comment] 2020-11-13 00:38
Seems to work in 3.2.3

**Closed by KoBeWi** 2020-11-13 00:38 UTC
Labels: bug, topic:navigation
