### ISSUE TITLE
Godot crashes when using "Continuous" update mode on PackedVector2Array Animation tracks

### ISSUE THREAD

**Issue by henriiquecampos** [godotengine/godot#68562] opened 2022-11-12 14:00 UTC
### Godot version

4.0.beta4.official[e6751549c]

### System information

SolusOS

### Issue description

When you change the track update type from discrete to continuous on tracks that has a PackedVector2Array type, Godot crashes.

This looks like a regression since 4.0.beta2 I was making this type of animation just fine.

### Steps to reproduce

1. Create a new scene
2. Add a Polygon2D node
3. Add an AnimationPlayer as its child
4. Create an animation using the "Polygon" property 
5. Change the animation's update mode from "discrete" to "continuous"

Godot will probably crash immediately. And will crash every time you try to even open the animation.

**Comment by adamscott** [comment] 2022-11-12 16:54
Please create a Minimal reproduction project. Even if the steps are quite simple, it would be so much easier to test if the issue is still there if a project exists where you just have to apply step 5 to see if it's fixed or not. It helps a lot debugging.

https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#reporting-bugs

**Comment by adamscott** [comment] 2022-11-12 17:01
Could reproduce on Godot 4.0 beta 4, but couldn't reproduce on master (c17f17e). Seems that the issue is fixed.

**Comment by akien-mga** [comment] 2022-11-12 19:11
Indeed, duplicate of https://github.com/godotengine/godot/issues/68377

**Closed by akien-mga** 2022-11-12 19:11 UTC
Labels: bug, crash, topic:animation
