### ISSUE TITLE
GDScript 2.0: In a inheritance + @onready the variable is created, but it is not initialized

### ISSUE THREAD

**Issue by AttackButton** [godotengine/godot#54588] opened 2021-11-04 11:05 UTC
### Godot version

v4.0.dev.calinou.795cd2eb3

### System information

Windows 10

### Issue description

In an inheritance, the @onready creates the variable, but it is not initialized. This doesn't happen, for example, with the export annotation or creating variables with no annotations.

### Steps to reproduce

Just create a script using the class_name for the Parent, create a variable using the @onready, initialize it with some data and try to use this Parent variable in a extended Child.

### Minimal reproduction project

[inheritance_annotation_bug.zip](https://github.com/godotengine/godot/files/7474279/inheritance_annotation_bug.zip)

**Comment by KoBeWi** [comment] 2021-11-04 11:52
Duplicate of #52223

Your child has `@onready` variable, which is treated like `_ready()` and prevents parent from initializing. You'd need to add
```
func _ready():
    super._ready()
```
to your child.

**Closed by KoBeWi** 2021-11-04 11:52 UTC
Labels: bug, topic:gdscript, regression
