### ISSUE TITLE
Importing multiple FBXs results in models sharing the same mesh

### ISSUE THREAD

**Issue by JotaFaD** [godotengine/godot#44042] opened 2020-12-02 16:54 UTC
**Godot version:**
v3.2.4 beta 3

**OS/device including version:**
RTX 2060, Nvidia driver 457.30, GLES 3.0

**Issue description:**
Importing multiple FBXs (by drag and drop inside project's folder and focusing on the engine) results in a ".mesh" Array Mesh file being created alongside the scenes for each model and every model having the same mesh as this file.
The console also print the message:
`Another resource is loaded from path 'res://Assets/Mesh/.mesh' (possible cyclic resource inclusion).`

**Steps to reproduce:**
Drag and Drop multiple FBXs inside project folder.

**Minimal reproduction project:**
The models I'm using were extracted from a unity prefab. If necessary, I can test the bug with other models which can be freely shared.

**Comment by Calinou** [comment] 2020-12-02 17:06
Can you reproduce this in Godot 3.2.3?

> The models I'm using were extracted from a unity prefab. If necessary, I can test the bug with other models which can be freely shared.

Yes, please upload a minimal reproduction project.

**Comment by Jose-Paulo-FaD** [comment] 2020-12-02 18:13
@Calinou I'm having a lot of trouble getting a minimum project due to #43949, here's what I gathered:

Opening this same project on 3.2.3 also manifests this bug.
Creating an empty project in either 3.2.3 or 3.2.4 beta 3 and importing in 3.2.3 works as intended.
Creating an empty project in either 3.2.3 or 3.2.4 beta 3 and importing in 3.2.4 beta 3 causes #43949

I tried the original models, 2 of Kenney's models and 2 of Assimp's test models and the results were the same for each case described above.

**Comment by RevoluPowered** [comment] 2020-12-15 17:51
> **Godot version:**
> v3.2.4 beta 3
> 
> **OS/device including version:**
> RTX 2060, Nvidia driver 457.30, GLES 3.0
> 
> **Issue description:**
> Importing multiple FBXs (by drag and drop inside project's folder and focusing on the engine) results in a ".mesh" Array Mesh file being created alongside the scenes for each model and every model having the same mesh as this file.
> The console also print the message:
> `Another resource is loaded from path 'res://Assets/Mesh/.mesh' (possible cyclic resource inclusion).`
> 
> **Steps to reproduce:**
> Drag and Drop multiple FBXs inside project folder.
> 
> **Minimal reproduction project:**
> The models I'm using were extracted from a unity prefab. If necessary, I can test the bug with other models which can be freely shared.

Importing multiple FBXs (by drag and drop inside project's folder and focusing on the engine) results in a ".mesh" Array Mesh file being created alongside the scenes for each model and every model having the same mesh as this file.

How are you creating these mesh files, did you change the importer options? if so what to?

**Comment by Jose-Paulo-FaD** [comment] 2020-12-18 19:20
> How are you creating these mesh files, did you change the importer options? if so what to?

@RevoluPowered I'm not very experienced in 3D, so it took me some time to find what was triggering the bug. The template I was using had the import setting `Meshes > Storage` set to `Files (.mesh)` by default. When this is the case, godot automatically creates a single .mesh file after importing the models and all models share this single mesh file, like I described in the original post.

If you change the setting to `Built-In`, which I believe is the default, everything works fine. Although I first found this bug in 3.2.4 beta3, it also happens in v3.2.3 stable.

**Comment by akien-mga** [comment] 2022-04-06 22:28
This is probably fixed with the new FBX importer using [FBX2glTF](https://github.com/V-Sekai/FBX2glTF/releases).
You can test it in Godot 4.0 alpha 6: https://godotengine.org/article/dev-snapshot-godot-4-0-alpha-6
This new importer might also be backported for the `3.x` branch eventually.

If you still find issues with these models using the new importer, we suggest opening a new issue with details about the problems in Godot 4.0 alpha 6 or later.

**Closed by akien-mga** 2022-04-06 22:28 UTC
Labels: bug, topic:import
