### ISSUE TITLE
Automated Testing: Proposal/Query. 

### ISSUE THREAD

**Issue by PaulHMason** [godotengine/godot#28638] opened 2019-05-03 07:21 UTC
I'm particularly interested in using Godot for cross-platform application development using the Control nodes but I can't find any information on automated testing. Is there any support for driver type applications for automated UI testing? I know that it doesn't make sense for games, but it's invaluable for normal types of application (could probably be useful for testing the Godot editor as well).

The basic idea is to expose some kind of interface that an external driver process can attach to and a way to find individual UI elements and invoke properties/events on them and then get the application state afterwards.

**Comment by groud** [comment] 2019-05-03 09:20
Related to / duplicate of #2641

**Comment by PaulHMason** [comment] 2019-05-11 10:28
> Related to / duplicate of #2641

This isn't the same as unit testing (although being able to unit test scripts would also be very useful).

**Comment by KoBeWi** [comment] 2020-05-27 22:42
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!

**Closed by KoBeWi** 2020-05-27 22:42 UTC
Labels: discussion, feature proposal, topic:core
