### ISSUE TITLE
Anchor Preset Scaling Issues

### ISSUE THREAD

**Issue by XCRunnerS** [godotengine/godot#76353] opened 2023-04-23 00:52 UTC
### Godot version

4.0.2.stable (steam)

### System information

Windows 10

### Issue description

Anchor Points seem to misbehave when the scale of an object is not 1

### Steps to reproduce

Specify steps to reproduce:
1. Open Demo Project
2. Use the Anchor Presets to adjust the location of the UI Element (in this demo, a panel container)
3. Notice Anchor Presets go to the same locations without considering the resize of the elements

### Minimal reproduction project

[UI_Scale_Anchor_Demo_Issue.zip](https://github.com/godotengine/godot/files/11302598/UI_Scale_Anchor_Demo_Issue.zip)

**Comment by KoBeWi** [comment] 2023-06-06 10:36
Duplicate of #19068

**Closed by KoBeWi** 2023-06-06 10:36 UTC
