### ISSUE TITLE
Creating a theme from current editor theme doesn't make a deep copy and allows you to break editor visuals

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#44331] opened 2020-12-13 00:21 UTC
**Godot version:**

3.2.4 beta4

**Issue description:**

See title.

**Steps to reproduce:**
1. Create a new Theme resource
2. Press Edit theme -> Create from current editor theme
![image](https://user-images.githubusercontent.com/2223172/101999867-6b462780-3ce1-11eb-904f-978b321e1973.png)
3. In the inspector, open some stylebox (e.g. in Button)
4. Edit it
5. Editor changes too, because your resource is sharing its stylebox

**Comment by Calinou** [comment] 2020-12-13 00:37
Duplicate of https://github.com/godotengine/godot/issues/27192.

**Closed by Calinou** 2020-12-13 00:37 UTC
Labels: bug, topic:editor, topic:gui
