### ISSUE TITLE
Godot should warn that changes are lost on editing an .obj mesh (perhaps on other imported resources too)

### ISSUE THREAD

**Issue by lucbf** [godotengine/godot#20659] opened 2018-08-01 21:57 UTC
**Godot version:**
3.0.x, 3.1

I suspect Material_OV was added because of this, nevertheless there's no workaround for other nodes such as gridmap and multimesh and even if there was it would be impossible to set a .obj file as local to scene for example.

**Comment by M4gma** [comment] 2018-08-01 22:12
I have to say that I tried to fix this bug by making godot save the changes on the .import folder but I gave up when I saw that (at least aparently) godot just wants to save .tscn and .tres files.

**Comment by eon-s** [comment] 2018-08-02 12:37
You mean that changes get lost on the inherited scene when editing the source model?

**Comment by M4gma** [comment] 2018-08-02 12:44
No, when you create a MeshInstance node and load a  obj mesh

**Comment by eon-s** [comment] 2018-12-04 17:19
Editing resources in place can be useful for testing, but maybe can be partially locked and force you to open a "preview mode" with a button or something.

**Comment by elizaho** [comment] 2020-03-31 01:05
I would like to work on this.

**Comment by Calinou** [comment] 2020-03-31 08:10
@elizaho Go ahead :slightly_smiling_face:

**Comment by ChristopheLY** [comment] 2020-06-16 06:42
I have a solution but it's not cover everery  possibilities where current_node have a mesh

Another thing, the button warning was not update when I add or delete a mesh .obj

editor/editor_node.cpp
![image](https://user-images.githubusercontent.com/45402513/84680964-c6b27b00-af33-11ea-8b1b-4f7fa66f8ccb.png)

**Comment by ChristopheLY** [comment] 2020-06-17 06:57
I would like to add a commit but i have a PR open (#39141) , what can I do?

**Comment by akien-mga** [comment] 2020-06-17 11:30
@ChristopheLY You can use separate branches to make several PRs. See https://docs.godotengine.org/en/latest/community/contributing/pr_workflow.html#branching
In general you should avoid making PRs from your fork's `master` branch, but since you already have one, it's not a problem, you just need to create a new branch and then reset it to the upstream `master` branch's state.

**Comment by akien-mga** [comment] 2022-03-26 19:11
It took me a while to understand what the issue is exactly so I'll rephrase it.

When editing the .obj directly, as Bojidar pointed out, it does show "changes may be lost".

When editing the Mesh resource assigned to a MeshInstance3D, whether it's saved as a custom .tres or builtin in its parent node, you *can* change things. You can assign a material, etc.

The part which is problematic is that if you didn't save this modified Mesh resource as a `.tres`, and you then reimport the `.obj` file, any changes made on top of it in the scene will be lost.

I'll close this as duplicate of #42128 which is a bit clearer.

**Closed by akien-mga** 2022-03-26 19:11 UTC
Labels: enhancement, topic:editor, usability
