### ISSUE TITLE
When in Pan Mode, cannot come out of it unless restarting the editor

### ISSUE THREAD

**Issue by knadoor** [godotengine/godot#79026] opened 2023-07-04 14:07 UTC
### Godot version

Godot 4.1 RC2

### System information

MacOS Ventura 13.4.1

### Issue description

When in the 2D view and pressing "G" (or user defined shortcut) to switch to Pan Mode, pressing "G" again does not exit the mode, it stays in pan.

Pressing "G" when in pan mode again should exit it.

### Steps to reproduce

As above.

### Minimal reproduction project

N/A

**Comment by KoBeWi** [comment] 2023-07-04 14:14
G just selects tool on the toolbar.
![image](https://github.com/godotengine/godot/assets/2223172/6d9874ce-ec6f-4307-9c4a-584ad83fe2f5)
Press Q to "exit" it.

**Comment by knadoor** [comment] 2023-07-04 14:53
Nice one, thanks :)

**Comment by KoBeWi** [comment] 2023-07-04 14:58
Closing, as it's not a bug.

**Closed by KoBeWi** 2023-07-04 14:58 UTC
