### ISSUE TITLE
Can't use backspace, enter, del, can't even copy and paste but can use normal alphabet keys

### ISSUE THREAD

**Issue by TilokSaha** [godotengine/godot#75593] opened 2023-04-02 12:25 UTC
### Godot version

v4.0.1.stable.official [cacf49999]

### System information

Windows 10 

### Issue description

I needed a reference so I can follow my work on the current project, so I opened another Godot editor in a new desktop 
(by win+tab >  +new desktop) and open Godot again but with a different project, so I have two Godot running at the same time. I used to do this back in 3.5 also, but it worked flawlessly until now in 4.0. 
So when I switch the window from one project to another using alt-tab, the editor bugs out and I can't use backspace, enter, but can use alphabet keys.
I think this kinda issue was raised a few days ago by another dude but it was closed due to a misunderstanding, so I am not alone. 

### Steps to reproduce

1. Open any script from your first Godot Editor
2. Win + Tab > +New Desktop > Open Godot again > choose different project > open any script from there (on win 10)
3. now try switching back and forth with win + tab and try typing in the script and use backspace or enter key, it will not work

### Minimal reproduction project

any two blank projects, having 1 script each. You just have to type to test it out.

Thank you.

**Comment by KoBeWi** [comment] 2023-04-02 12:35
Duplicate of #74957
This should be fixed in [4.0.2 rc1](https://godotengine.org/article/release-candidate-godot-4-0-2-rc-1/)

**Closed by KoBeWi** 2023-04-02 12:35 UTC
