### ISSUE TITLE
Control nodes are not ready before _ready() is called when alignment is set to fill

### ISSUE THREAD

**Issue by tokengamedev** [godotengine/godot#88099] opened 2024-02-08 13:11 UTC
### Tested versions

4.2.2.rc1
3.5.3 (Working fine)

### System information

Windows 11

### Issue description

When you have a control with alignment setup as fill for either horizontal and/or vertical. The rendering or calculations are not complete before `_ready()` is called.
My assumptions are when the scene is loaded and `_ready()` called all the rendering and calculations are completed. When you ask for size on controls it should be correct. 
It is not the case. 
To get the correct value you have to wait for next frame using `await get_tree().process_frame`

This is not reproducible in 3.5.3.

### Steps to reproduce

MRP attached

here is the code and output in comments
```gdscript
extends Control

@onready var panel: PanelContainer = $Panel
@onready var texture_rect: TextureRect = $Panel/TextureRect

func _ready() -> void:
	print("Panel Size:", panel.size)
	print("Texture Size:", texture_rect.size)
	await get_tree().process_frame
	print("Panel Size:", panel.size)
	print("Texture Size:", texture_rect.size)

# Output:
#Panel Size:(1152, 648)
#Texture Size:(128, 128)
#Panel Size:(1152, 648)
#Texture Size:(1152, 648)

```

### Minimal reproduction project (MRP)

[ReadyNotReadyMRP.zip](https://github.com/godotengine/godot/files/14209600/ReadyNotReadyMRP.zip)

**Comment by AThousandShips** [comment] 2024-02-08 13:21
This is expected, and should be documented better IMO, it's just not possible to know this by `_ready` as the parent and siblings are not ready yet

**Comment by AThousandShips** [comment] 2024-02-08 13:23
Duplicate of https://github.com/godotengine/godot/issues/72024

**Closed by AThousandShips** 2024-02-08 13:23 UTC
Labels: discussion, documentation, topic:gui

**Comment by tokengamedev** [comment] 2024-02-08 14:18
This is not a limitation or designed feature in Godot which should be expected. It is a serious bug, which was not reproducible in 3.x. Even if you want to document as a limitation, you cannot, as you do not know when it produces correct result and when not.

It is safe to assume that the core functionality of Godot is broken. This bug or #72024 redefines the usability of _ready() function.

**Comment by MewPurPur** [comment] 2024-02-09 08:41
You say this isn't a bug, but the points the core contributors brought up seem very valid to me. How do you argue against those?

**Comment by tokengamedev** [comment] 2024-02-13 07:46
@MewPurPur, even if I found a workaround, I still think it is a bug for _ready() function. The reason being the purpose of ready function. This has changed.

Now when I say you cannot document it because, the developer don't know what is ready at the time ready is called. So what to document, may be only thing you can say a gray statement like "not all things are ready when _ready is called",

I understand what the contributors have done to optimize the launching of the game. (This is also explained by reduz in X/Twitter also) but what I don't understand is how the engine developer missed the implications of optimizations.

Finally, regarding the point, you said _"How do you argue against those?"_. 
When I or anybody (Game developer mostly) raise an issue in Godot. **_Most of us_** verify that is reproduced consistently, create project if required to, write a lengthy documentation of issue if required to. This involves a lot of effort and time, which we take out from our game development time. 

The _purpose is to find a workaround or solution_ so that we can proceed with our development work, and not to argue with anybody.

**Comment by MewPurPur** [comment] 2024-02-13 09:19
Ignoring the discussion about whether this should be expected, the workaround is to use the `resized` signal. But anyway, this is a development platform about Godot, so the main purpose is actually to work out whether this is a bug in Godot that needs fixing.
