### ISSUE TITLE
StringName comparisons give wrong and inconsistent results

### ISSUE THREAD

**Issue by lilizoey** [godotengine/godot#76218] opened 2023-04-18 18:02 UTC
### Godot version

4.0.2

### System information

Linux 5.10.167-2-MANJARO

### Issue description

Comparing StringNames will give wrong and inconsistent results, running the provided code will give the results:
```
a < b false
a > b false
a <= b true
a >= b true
a == b false
```

The documentation for `<` on `StringName` says:

> Returns true if the left String comes before right in Unicode order, which roughly matches the alphabetical order. Useful for sorting.

However then "a < b" should be true, not false.

In addition `a <= b` and `b <= a` is true, yet `a == b` is false. Which is inconsistent.

### Steps to reproduce

run
```gdscript
func _ready():
	var a = &"a"
	var b = &"b"
	print("a < b ", a < b)
	print("a > b ", a > b)
	print("a <= b ", a <= b)
	print("a >= b ", a >= b)
	print("a == b ", a == b)
```

### Minimal reproduction project

N/A

**Comment by AThousandShips** [comment] 2023-04-18 18:10
The documentation is apparently wrong from the implementation, should be updated

**Comment by KoBeWi** [comment] 2023-04-18 18:53
The operator is implemented like this
https://github.com/godotengine/godot/blob/06f5b09ca493d1de5dd4bec97bdb6b9ad4fb1d29/core/string/string_name.h#L117-L119
`_data` is a pointer. It's wrongly implemented (unless there is a reason why it's like that).

**Comment by KoBeWi** [comment] 2023-04-18 18:54
Yeah but does it use `<` operator? It's basically sorting pointers.

**Comment by AThousandShips** [comment] 2023-04-18 18:56
I assume `StringName` was/are used in `RBMap` etc, sorting the pointers should give uniqueness and is faster than comparing by the content, seems to be overlooked

**Comment by AThousandShips** [comment] 2023-04-18 18:58
In fact the wording for `String` and `StringName` are equal for the ordering operators, including calling it `String` in `StringName`, however the equality operator differs, *and* makes a note about how it is faster:

> Returns true if the StringName and right refer to the same name. Comparisons between StringNames are much faster than regular [String](https://docs.godotengine.org/en/stable/classes/class_string.html#class-string) comparisons.

**Comment by AThousandShips** [comment] 2023-04-18 19:01
The implementation is weird though as it doesn't give correct results, also there isn't any other comparison operators for `StringName` than `<=` so might be doing conversion under the hood somewhere

**Comment by AThousandShips** [comment] 2023-04-18 19:16
For now if you want the alphabetic ordering a workaround should be to cast them to `String`

I suspect there's some conversion going on as there's no errors caused by the fact that `StringName` doesn't have any of the remaining operators, and a decision would have to be made on what ordering to use, alphabetical or pointer based

**Comment by AThousandShips** [comment] 2023-05-18 11:22
Working on a fix for this

**Closed** 2023-05-18 16:42 UTC
Labels: bug, topic:core
