### ISSUE TITLE
Shortcut taken (OS X) : Quit to project list

### ISSUE THREAD

**Issue by MangelMaxime** [godotengine/godot#1600] opened 2015-04-02 12:18 UTC
The shortcut (Meta + Shift + Q) used for the action "Quit to project list" is already taken by OSX.

It's a shortcut to exit the current session. We should find another shortcut. like : Meta + Shift + L.
L like List ?

**Comment by akien-mga** [comment] 2016-04-29 08:51
Should be easy to workaround.

**Comment by djrm** [comment] 2016-06-25 02:48
Now its possible to rebind the shortcut

**Comment by akien-mga** [comment] 2016-07-20 13:43
Would <kbd>Alt + Shift + Q</kbd> work?

**Comment by bojidar-bg** [comment] 2016-11-06 10:10
Pretty ping :smiley:

**Comment by cxong** [comment] 2017-10-08 06:30
Looks like this is already fixed. https://github.com/godotengine/godot/blob/3d87b70f7a8cadaab581c481fcc51622e8043ee0/editor/editor_node.cpp#L5012-L5016

**Comment by bojidar-bg** [comment] 2017-10-09 13:35
Duplicate of #2398, fixed by 9c38ad00936f89c4c6ddacfdbf0332e9f1623bca.

**Closed by bojidar-bg** 2017-10-09 13:35 UTC
Labels: enhancement, hacktoberfest, platform:osx, topic:editor, usability
