### ISSUE TITLE
Scene UID Not being updated when duplicating folders

### ISSUE THREAD

**Issue by stats** [godotengine/godot#68456] opened 2022-11-09 16:58 UTC
### Godot version

v4.0.beta4.official [e6751549c]

### System information

Window 10

### Issue description

When duplicating a folder and scenes inside the folder that are duplicated will have the same uid for for the scene in the [gd_scene] line.

OriginalFolder\OriginalScene.tscn: `[gd_scene format=3 uid="uid://66b48vs4wrdd"]`
DuplicateFolder\DuplicateScene.tscn: `[gd_scene load_steps=2 format=3 uid="uid://66b48vs4wrdd"]`

This conflict in UID results will result in the incorrect resource being loaded when referencing the duplicate as a PackedScene from an export variable and then trying to instantiate it.

**Proposed Fix:** When duplicating folders all copied sub-resources will need new uid created during the copying process.

### Steps to reproduce

1. Extract DuplicateFolderBug.zip and import and run the project
2. Open TestScene.gd
3. Notice that OriginalScene.tscn is the Packed Scene loaded as a export var
4. Player the scene
5. Notice that the godot sprite is displayed
6. Open OriginalFolder/OriginalScene.tscn and find that the sprite is not part of this scene
7. The sprite is part of DuplicateFolder/DuplicateScene.tscn

If you check the Remote you will see that DuplicateScene.tscn is being loaded and not the OriginalScene.tscn that is referenced from the export var.

### Minimal reproduction project

[DuplicateFolderBug.zip](https://github.com/godotengine/godot/files/9973355/DuplicateFolderBug.zip)

**Comment by KoBeWi** [comment] 2022-11-09 23:24
Can't reproduce. When I duplicate the OriginalFolder, the scene correctly gets a new UID.
Tested in [dca5cb8](https://github.com/godotengine/godot/commit/dca5cb8e40fd2a348a59ea73c597eb742c14c980)

**Comment by KoBeWi** [comment] 2022-11-09 23:30
Ok I got the dates wrong. This was fixed after beta 4 commit.
The issue will be resolved in beta5.

**Closed by KoBeWi** 2022-11-09 23:30 UTC
