### ISSUE TITLE
"Visibility changed" event always sends error strings to log

### ISSUE THREAD

**Issue by Chaosus** [godotengine/godot#19286] opened 2018-05-31 07:13 UTC
**Godot version:**
43b7ebf

**OS/device including version:**
no matter

**Issue description:**
If you implement visibility changed event function it will spam these error strings every time you load scene in the editor.

![image](https://user-images.githubusercontent.com/3036176/40767244-a0381ebe-64ba-11e8-9867-41c3e0a2471d.png)

**Steps to reproduce:**
Create a scene with simple Node with script and attach visibility changed event to it, every time scene is loaded or switched it will spam error string to log, which is not good !

**Minimal reproduction project:**
[VisibilityChangedBug.zip](https://github.com/godotengine/godot/files/2057164/VisibilityChangedBug.zip)

**Comment by akien-mga** [comment] 2018-05-31 10:20
Might be related to #18172? I already checked that it was not *caused* by #18172, but it may be linked to this `first_draw` stuff.

The issue is likely that the notification is propagated in the editor when the Node2D enters the SceneTree, but since the editor doesn't run non-tool scripts, it can't find the method bound to it. Such notifications should ideally not be propagated to the editor, but not sure how to change it and what would be the impact.

**Comment by Chaosus** [comment] 2018-05-31 11:00
https://github.com/godotengine/godot/blob/43b7ebf0a0478d7b04620b03920fd82041afb588/scene/2d/canvas_item.cpp#L511

If you comment this line or mark it editor hint, the problem will dissappear, but editor will not work correctly always

**Comment by DualMatrix** [comment] 2018-09-24 20:09
Could not reproduce in master 2c79087

**Comment by akien-mga** [comment] 2018-09-24 20:30
I can still reproduce it on aaef640b8 myself. Note that it happens when the scene is opened in the editor, not when running the game.

It's the same issue as #13070 though and should get fixed by #22297.

**Closed by akien-mga** 2018-09-24 20:30 UTC
Labels: bug, topic:editor
