### ISSUE TITLE
Merge TouchScreenButton to Control?

### ISSUE THREAD

**Issue by wojtasss** [godotengine/godot#28814] opened 2019-05-10 19:38 UTC
I am creating mobile game. First I was using TextureButton, but quick realized that Control buttons doesn't handle detecting simultaneously touches, so I found TouchScreenButton but it not inherit from Control so it doesn't fit to creating responsive game interface. It would be possible to do that TouchScreenButton would be inherit from Control node?

**Comment by Calinou** [comment] 2019-05-10 19:53
> so I found TouchScreenButton but it not inherit from Control so it doesn't fit to creating responsive game interface. It would be possible to do that TouchScreenButton would be inherit from Control node?

As a workaround, you can add TouchScreenButtons as a child of a Control node, which can then be anchored. See https://github.com/godotengine/godot-demo-projects/pull/323 for an example.

**Comment by KoBeWi** [comment] 2019-12-20 10:31
Duplicate of #15039 actually

**Closed by KoBeWi** 2019-12-20 10:31 UTC
Labels: discussion, enhancement, topic:core, topic:input
