### ISSUE TITLE
Godot randomly fails to find class members

### ISSUE THREAD

**Issue by slapin** [godotengine/godot#4477] opened 2016-04-29 05:52 UTC
we have several sets of
```gdscript
const NORMAL = 0
const GRABBED = 1

var state = NORMAL setget switch_state, get_state

func leave_state(st):
    pass
func enter_state(st):
    if st == NORMAL:
        anim.state = anim.STANDING
    elif st == GRABBED:
        anim.state = anim.GRABBED

func switch_state(st):
   if st != state:
       leave_state(state)
       enter_state(st)
   state = st

func get_state():
    return state
```
Some are attached to RigidBody, some are attached to AnimationTreePlayer.

in some instances anim.STANDING, and anim.GRABBED access fails with
Invalid get index 'GRABBED' (on base: 'AnimationTreePlayer (housewife-anim.gd)').
setting these to intended numbers makes things work. Looks like GDScript is very buggy about
constants, it is not first time I meet such behavior, it is not a new thing, it happend with 1.0 too.

No inheritance is used this time, so it fails with just plain GDScript.

Node structure is
RigidBody1 -> script1
+AnimationTreePlayer1 => script3
RigidBody2 => script2
+AnimationTreePlayer2 => script3
The 2nd ATP with script fails to find GRABBED which is directly const, but finds NORMAL.
first ATP have no problems.

**Comment by slapin** [comment] 2016-04-29 06:00
Looks like memory corruption with multiple scenes loaded, as when I restart Godot and load just one scene which contains RigidBodies, the problem do not occur. However this starts occuring again as I
edit scenes and leave them open.

**Comment by slapin** [comment] 2016-04-29 06:01
Yes, it executes diffrent script when this error happens.

**Comment by reduz** [comment] 2016-06-20 01:27
please make a test project, or your issue didn't happen

**Comment by slapin** [comment] 2016-06-20 16:50
This issue happens when you have several scenes with the same name in the
project.
This is minimal condition. For others, I don't know. It is not really
100%-reproducible.

My sole purpose for submitting bugs is improvement of Godot quality.
If you don't care, feel free to close all of them.

**Comment by vnen** [comment] 2016-06-20 17:12
If we can't reproduce the bug we can't fix it. In your code example you use `anim.GRABBED`, but `anim` is not defined in the excerpt, so I can't tell what it is and whether it does have a `GRABBED` constant in it or not.

**Comment by reduz** [comment] 2016-06-20 17:23
@slapin come on dude, we work hard for you to have something that works, at least take the effort of making a test project to save us time

**Comment by slapin** [comment] 2016-06-20 18:00
Sorry guys, I can't spend any time on this at the moment. So if you have to
close this now I
have no problem.
The problem was that it took constants from wrong script.
I had 2 scenes, one in project root, another one with the same name in
project subdir.
Both use scripts (dfferent). When used from third scene, the constants
defined
in script were not seen and functions did not work, but both scripts were
running OK.
By experimentation I found it picked constants from different script.
I solved this problem by renaming scene in root directory to a different
name.
Filed a bug ant totally forgot about it.
I can live with problems I can work around, so I generally don't submit
bugs for these, this one was intended just for probably serious problem deep
under. As nobody encountered anything like this now, it was probably fixed
on
the go, or is not in the area where people poke things. Anyway, if anybody
encounter
something like this again they will file a new bug.

**Comment by reduz** [comment] 2016-06-20 18:06
ok, for now closing it, if someone submits again we can contrast it

**Closed by reduz** 2016-06-20 18:06 UTC
Labels: bug, topic:core
