### ISSUE TITLE
"ui_accept" InputMap defaults cannot be deleted

### ISSUE THREAD

**Issue by SirNarpa** [godotengine/godot#20728] opened 2018-08-05 00:13 UTC
**Godot version:** 3.0.5

**OS/device including version:** Windows 10

**Issue description:** "ui_accept" InputMap defaults cannot be deleted

**Steps to reproduce:**
1. Create a new Project
2. Delete the 4 default key bindings for "ui_accept". Alternatively, add a fifth acceptable keybind and then clear the default 4.
3. Run this: `print(InputMap.get_action_list("ui_accept"))`
4. Notice that all of the default keybindings are still present, even though they were removed.
5. Even if a valid key is added, or one of the options remains (like leaving 'enter'), the deleted values will return.
6. Close and re-open the project, observe that all four defaults have returned.

**Minimal reproduction project:**

[ui_accept.zip](https://github.com/godotengine/godot/files/2259924/ui_accept.zip)

**Workaround:** Re-map the key you need to some irrelevant set of keys.

This makes TextEdit impossible to use with ui_accept, as every space is seen as accepting the line. Having _one_ keyboard key bound to this (Enter) makes sense, but the way this is behaving there must always be three keyboard keys bound to ui_accept, even if two of them are just re-assigned to some irrelevant set of keys so that "Space" and "Kp Enter" can be used elsewhere.

**Comment by AlexHolly** [comment] 2018-08-05 01:50
duplicate? https://github.com/godotengine/godot/issues/3793

**Comment by reduz** [comment] 2018-08-05 02:25
This is fixed in master

**Comment by akien-mga** [comment] 2018-08-14 15:11
Duplicate of #3793.

**Closed by akien-mga** 2018-08-14 15:11 UTC
Labels: archived

**Comment by akien-mga** [comment] 2018-08-14 16:28
It's actually a "bug" that this got fixed, see #3793. Keeping closed as it's a duplicate of #3793 though.
