### ISSUE TITLE
Predefined C# format for mono version

### ISSUE THREAD

**Issue by Torguen** [godotengine/godot#42619] opened 2020-10-07 14:19 UTC
**Godot version:**

3.2.3 mono stable

**OS/device including version:**

win10 64

**Issue description:**

In the mono version, the GDScript format is predefined when creating a script.
The GDScript format is not supposed to be used in this version and the main format for scripts is C #.

**Steps to reproduce:**
Create a new script in the mono version and note that the default format initially is GDScript
![Captura](https://user-images.githubusercontent.com/19652075/95343542-f3aae500-08b8-11eb-9445-4966a3cfbe66.PNG)

**Minimal reproduction project:**

**Comment by Calinou** [comment] 2020-10-07 14:46
> The GDScript format is not supposed to be used in this version and the main format for scripts is C #.

Nothing says you're not *supposed* to use GDScript in a Mono-enabled build.

That said, it makes sense to use C# as the default option in the script creation dialog.

**Comment by neikeq** [comment] 2020-10-18 13:24
>That said, it makes sense to use C# as the default option in the script creation dialog.

Keep in mind that I plan to unify the classic and C#-enabled versions of the editor into one. I have yet to write a GIP about this but the idea is that all the C# bulky dependencies are not included by default and downloaded when C# is actually used.
If this happens then it doesn't make sense to make these version-specific changes.

**Comment by aaronfranke** [comment] 2020-10-23 05:19
Godot actually remembers what language you selected last time, so if you only use C# scripts, then you should only ever have to click through that dropdown menu once. Godot also remembers this if you close and re-open Godot.

**Comment by Tobi-Mob** [comment] 2021-09-12 18:24
> Godot actually remembers what language you selected last time, so if you only use C# scripts, then you should only ever have to click through that dropdown menu once. Godot also remembers this if you close and re-open Godot.

I can confirm this is the current behaviour in Godot 3.3.3

> Nothing says you're not _supposed_ to use GDScript in a Mono-enabled build.

> Keep in mind that I plan to unify the classic and C#-enabled versions of the editor into one. [...]
> If this happens then it doesn't make sense to make these version-specific changes.

Since 
* GDScript and C# are valid choices
* The editor remembers your preference
* classic and mono edition of the editor will be merged into one version some day

The current behaviour seems pretty good to me.
I would not change anything.

**Comment by aaronfranke** [comment] 2021-09-12 18:26
As per the above discussion, nothing should be changed here. Using GDScript in the Mono version of Godot is perfectly valid, and the editor remembers what you choose, so there is no need to change what the default in this dropdown is. Closing.

**Closed by aaronfranke** 2021-09-12 18:26 UTC
Labels: enhancement, topic:editor, usability, topic:mono
