### ISSUE TITLE
[Android Editor] Text box content duplication/scrambling in editor

### ISSUE THREAD

**Issue by ashifolfi** [godotengine/godot#83022] opened 2023-10-09 02:19 UTC
### Godot version

4.1.2.stable

### System information

Godot v4.1.2.stable - Android - Vulkan (Mobile) - integrated Mali-G72 - (8 Threads)
Samsung Galaxy Tab S6 Lite - Android 13 (One UI 5.1.1)

### Issue description

When editing any kind of text in the android editor using any kind of keyboard, the text field will blink it's entire contents momentarily, mash lines together, delete random characters or sections of text, duplicate characters or sections of text, insert random characters, and just overall progressively destroy any kind of content you had in the file by scrambling everything up.

This makes editing scripts completely impossible on the android editor, making it useless for anything more than simple scene rearrangement.

Furthermore, the effects seem to get worse and worse the more you type without interruption.

https://github.com/godotengine/godot/assets/29577987/60e75831-2603-4f68-a838-737a8fe9adcf

### Steps to reproduce

1. Open the android editor
2. Open any project (new or existing)
3. Open any kind of text file that uses the built in script editor
4. try and type at all (the longer you try the more the effects should worsen)

### Minimal reproduction project

N/A

**Comment by m4gr3d** [comment] 2024-06-23 22:33
Duplicate of https://github.com/godotengine/godot/issues/70751

**Closed by m4gr3d** 2024-06-23 22:33 UTC
Labels: bug, platform:android, topic:editor, topic:gui
