### ISSUE TITLE
Rename or Reimport OGG audio file causes crash on editor.

### ISSUE THREAD

**Issue by vitorbalbio** [godotengine/godot#43576] opened 2020-11-15 20:57 UTC
**Godot version:**
Latest 3.2.3 stable

**OS/device including version:**
Windows 10

**Issue description:**
Rename or Reimport OGG audio file causes crash on editor.

**Steps to reproduce:**
Create a project. Add the OGG Audio to the scene (Any Resource exported variable or Audio Stream Player). Rename it in File System or reimport the file. Editor crashes.

**Minimal reproduction project:**
[BugAudioReimport.zip](https://github.com/godotengine/godot/files/5543094/BugAudioReimport.zip)

**Comment by akien-mga** [comment] 2020-11-15 21:05
I can't reproduce the issue. Can you detail the steps to reproduce more precisely, or make a video of the steps you're taking to trigger the crash?

**Comment by vitorbalbio** [comment] 2020-11-15 21:58
> I can't reproduce the issue. Can you detail the steps to reproduce more precisely, or make a video of the steps you're taking to trigger the crash?

For me just opening this project that i send and renaming the file already crash the editor. it happens in any project in any ogg file. I'm using Windows 10 and latest stable version of Godot 3.2.3
Check this video: https://imgur.com/a/vsScie1

**Comment by KoBeWi** [comment] 2020-12-01 00:26
Duplicate of either #27800

**Closed by KoBeWi** 2020-12-01 00:26 UTC
Labels: bug, crash, topic:audio
