### ISSUE TITLE
RichTextLabel does not support wrapping for Chinese font

### ISSUE THREAD

**Issue by cjmxp** [godotengine/godot#1848] opened 2015-05-07 09:07 UTC
RichTextLabel
Chinese font does not support Wrap

**Comment by reduz** [comment] 2015-05-07 17:04
someone contributed a fix for label so it wraps correctly, do you know how
to fix this?

**Comment by akien-mga** [comment] 2016-05-20 10:33
Is this issue still valid in the current master branch?

**Comment by akien-mga** [comment] 2016-05-29 18:20
@Geequlim Could you check if this issue is fixed in master?

**Comment by Geequlim** [comment] 2016-05-30 04:55
@akien-mga It seems the wrapping doesn't work for Chinese  :(

![](http://ac-vx10w61r.clouddn.com/f04bab267fe79fd3.png)

**Comment by Geequlim** [comment] 2016-05-30 04:58
By the way, Both RichTextLabel and TextEdit have to set custom font to display Chinese characters even the editor can display that.

**Comment by neikeq** [comment] 2016-05-30 09:24
@Geequlim Do you mean `TextEditor::set_wrap(bool)`? Wrap is not implemented at all in `TextEdit`, there is an issue: #3985

**Comment by Geequlim** [comment] 2016-05-30 09:27
@neikeq  Yes, `TextEditor::set_wrap(bool)` dosn't work yet.

**Comment by neikeq** [comment] 2016-06-03 15:18
@Geequlim But this issue is about RichTextLabel. It seems to work fine in your screenshot, IINW.

**Comment by Geequlim** [comment] 2016-06-03 15:24
@neikeq Nope.
Take a look at last word in the last line in the screenshot.

Only half of the word `最` is shown and some words behind it was cliped.

**Comment by volzhs** [comment] 2016-06-03 15:41
I think this is caused by no space with Chinese.
There is similar issue #4735 even though it's Latin character.

**Comment by reduz** [comment] 2016-06-14 11:18
this is fixed now, Chinese font should now wrap

**Closed by reduz** 2016-06-14 11:18 UTC
Labels: bug, topic:core
