### ISSUE TITLE
Subcategorize "Script Variables"

### ISSUE THREAD

**Issue by 11clock** [godotengine/godot#22173] opened 2018-09-17 00:23 UTC
When you have a lot of variables in a script, it can get quite unwieldy to manage them in the inspector.

![b2c361957a7df8a81235377e64db2d78](https://user-images.githubusercontent.com/21234930/45602543-123d9b00-b9d5-11e8-9e51-d9f5436b3245.png)

I would like to be able to subcategorize script variables, just like native nodes can.

![6c4b3f79f966c0154c1f32ddb35eab87](https://user-images.githubusercontent.com/21234930/45602547-27b2c500-b9d5-11e8-8761-1e829a245cad.png)

**Comment by Ace-Dragon** [comment] 2018-09-17 00:52
I'm in full agreement, that could be quite a handy feature to have if you use a lot of exported properties in a script.

The only obstacle I can think of right is how a script with categorized properties would look (then there's allowing existing games to make use of it without causing all of the objects to reset).

**Comment by vnen** [comment] 2018-09-17 01:07
Duplicate of #4378

**Closed by vnen** 2018-09-17 01:07 UTC
