### ISSUE TITLE
GLES2 Light bugs when baking light

### ISSUE THREAD

**Issue by Janders1800** [godotengine/godot#43204] opened 2020-10-30 08:32 UTC
**Godot version:**

3.2.4 beta-1

**OS/device including version:**

Zorin OS 15

**Issue description:**

Lights flicker wen moving the camera (Only if there is a BakedLightmap node).
"Bake mode all" lights illuminate baked objects, but if I hide it and show it again then it works ok, but it screws other lights.

![LightBug](https://user-images.githubusercontent.com/27329423/97677375-724b0a80-1a92-11eb-8ab1-0abb713bbd73.gif)

Possible related: https://github.com/godotengine/godot/pull/41629

**Steps to reproduce:**
Make a similar setup as the gif

**Minimal reproduction project:**

[LightMaps.zip](https://github.com/godotengine/godot/files/5469768/LightMaps.zip)

**Comment by mrjustaguy** [comment] 2020-10-30 08:48
You forgot to add an MRP

**Comment by Janders1800** [comment] 2020-10-30 19:28
I'm unable to reproduce this bug in a minimal project.

**Comment by Janders1800** [comment] 2020-10-30 22:14
Maybe related? https://github.com/godotengine/godot/issues/33110

**Comment by mrjustaguy** [comment] 2020-10-31 16:57
Reprocuded:
[Light.zip](https://github.com/godotengine/godot/files/5469442/Light.zip)

Reason: Too many lights affecting the mesh --> Renderer Limit --> Flickering due to Choice of lights rendered affected by what the camera sees (I guess? - to the flickering part that is)

Solutions: Reduce number of lights affecting the mesh or wait for Godot 4 and use Vulkan

**Comment by Janders1800** [comment] 2020-10-31 20:31
Sorry but that's not the same setup as wen the bug happens.
- I'm using GLES2 (sorry, forgot to mention it).
- Generated meshinstances can't be lightmapped (No UV2).
- And lights aren't set to "bake mode all".

I've managed to reproduce the bug on a minimal project:
[LightMaps.zip](https://github.com/godotengine/godot/files/5469768/LightMaps.zip)

**Comment by mrjustaguy** [comment] 2020-11-01 09:19
I don't think I was successful with reproducing it on your MRP on a Quadro K2000 (driver 452.06).. Gif of the MRP would help in searching, as it's possible I'm looking at the wrong thing and thus not noticing the bug.. Only thing I'm noticing is that I can turn off all lights and still have a lit setup even with the baked lighting node hidden.. which only ends when I kill it.

**Comment by Janders1800** [comment] 2020-11-01 11:03
Yeah in stable works OK

**Comment by clayjohn** [comment] 2020-11-01 19:13
Cc: @JFonS

**Comment by JFonS** [comment] 2020-11-01 19:25
Definitely sounds like a regression from the baked lights PR. I will take a look at it :)

**Comment by Janders1800** [comment] 2020-11-19 13:25
Still happens on 3.2.4 beta-2

**Comment by JFonS** [comment] 2020-11-25 17:17
Sorry for the delay on this issue.

@Janders1800 I opened  #43858 which I think fixes the issue. I tested on your MRP and everything seems to work fine, but it would be great if you could test it on your project as well.

**Comment by akien-mga** [comment] 2020-11-25 22:11
Fixed by #43858.

**Closed by akien-mga** 2020-11-25 22:11 UTC
Labels: bug, confirmed, regression, topic:rendering

**Comment by Janders1800** [comment] 2020-11-29 14:11
Works OK
