### ISSUE TITLE
[Godot 3.2-stable] 3D Particles Node not work

### ISSUE THREAD

**Issue by D3ZAX** [godotengine/godot#35942] opened 2020-02-06 07:32 UTC
**Godot version:** 3.2

**OS/device including version:** windows 7

**Issue description:** Godot 3.2 3D Particles Node shows nothing, and log is: "ERROR: Image height must be greater than 0." It works well after convert to CPUParticles

**Steps to reproduce:** In the editor, create new scene, set as 3d scene, add Particles node, set Process Material to New ParticlesMaterial, set Pass 1 in Draw Passes to New QuadMesh, then nothing shows.

**Comment by Zireael07** [comment] 2020-02-06 07:41
Does it work if you check "disable z"? If yes, then it's a duplicate of #35492

**Comment by D3ZAX** [comment] 2020-02-06 10:04
Yes! It will work fine if I check "disable z"!

**Comment by akien-mga** [comment] 2020-02-06 10:39
Duplicate of #35492

**Closed by akien-mga** 2020-02-06 10:39 UTC
