### ISSUE TITLE
Godot 2.0 Beta will popup an exception window when closing  editor on MAC OSX

### ISSUE THREAD

**Issue by lizistorm** [godotengine/godot#3542] opened 2016-02-01 16:32 UTC
Also popup the error after open a project by project manager and close played game window.

Here is the pop up error:
![image](https://cloud.githubusercontent.com/assets/2263255/12723352/fec5a4fc-c943-11e5-82f1-3bc74c130205.png)

**Comment by akien-mga** [comment] 2016-02-01 16:48
Thanks, that seems to be a duplicate of #3498 and was fixed recently in the master branch, so it should work in the next beta/RC.

**Closed by akien-mga** 2016-02-01 16:48 UTC
Labels: platform:osx

**Comment by punto-** [comment] 2016-02-01 17:14
Is this from the latest on github? I think it's fixed.

**Comment by lizistorm** [comment] 2016-02-02 03:41
Oh sorry! I should checkout fixed issues first.
