### ISSUE TITLE
Internal Script Error! - opcode #38 when trying to instantiate a class in a script that uses a const value

### ISSUE THREAD

**Issue by nialna** [godotengine/godot#35857] opened 2020-02-02 18:00 UTC
**Godot version:**
3.2

**OS/device including version:**
windows 10

**Issue description:**
Just got this error in a class being instantiated from another script. It's trying to use the value of a const to assign to a field in the class.

file `PlayerMeta.gd`
```
const PLAYER_START_HP = 25

class PlayerMeta extends Reference:

	var inventory = []
	var max_hp = PLAYER_START_HP
	var xp = 0
	var level = 0

	func _init():
		inventory = []

	func add_item(item):
		inventory.append(item)

# Declare member variables here. Examples:
# var a = 2
# var b = "text"


# Called when the node enters the scene tree for the first time.
func _ready():
	pass # Replace with function body.


# Called every frame. 'delta' is the elapsed time since the previous frame.
#func _process(delta):
#	pass
```

The line `var max_hp = PLAYER_START_HP` causes the error:

`Internal Script Error! - opcode #38 (report please).`

**Steps to reproduce:**
Create the script above, and try instantiating it from a node:

```
extends Node2D

const PlayerMeta = preload("res://scripts/PlayerMeta.gd").PlayerMeta

var player_meta = PlayerMeta.new()
```

**Comment by imekon** [comment] 2020-04-06 16:23
I'm getting the same issue with enums (in Godot 3.2.1.stable.official)

I found a workaround is to use values like 0, 1, 2 etc.

**Comment by vnen** [comment] 2020-05-17 01:47
Duplicate of #5843

**Closed by vnen** 2020-05-17 01:47 UTC
Labels: bug, topic:gdscript
