### ISSUE TITLE
iPhone HTML5 export never loading

### ISSUE THREAD

**Issue by Tinkersedge** [godotengine/godot#27019] opened 2019-03-13 18:08 UTC
I have looked for similar issues, but the question wasnt' the same, doesn't seem to be answered, or the issues were either closed or changed to discussion. 

**Godot version:**
I am using the 3.1 stable version released today.

**OS/device including version:**
desktop mac, android mobile device, and iphone

**Issue description:**
When exporting my game with the HTML5 template using GLES2, I can view and play my game on all the desktop browsers I have as well as on my Android phone default browser. However, it never completes loading on my iphone or ipad. 

[HelloWorld3.1.zip](https://github.com/godotengine/godot/files/2962969/HelloWorld3.1.zip)

**Comment by eon-s** [comment] 2019-03-14 00:17
iPhone and iPad models and iOS versions?
Also try the demo on https://webassembly.org/

**Comment by Tinkersedge** [comment] 2019-03-14 02:05
iPhone X - ios 12.1.4
iPad 3rd generation - ios 10.3.3

iPad - the webassembly.org demo shows up on the ipad in Safari. 
iPhone - the webassembly.org demo never loads in Safari or in Chrome.

**Comment by awindahl** [comment] 2019-08-09 13:08
there is a custom version of the engine that takes acare of ios safari support for html5. It works without major hiccups. https://github.com/dotdigitalgroup/godot/tree/asmjs-support

This issue is the same as https://github.com/godotengine/godot/issues/26554

**Comment by Tinkersedge** [comment] 2019-08-09 13:41
Great. Can't wait to check it out. But, what is it exactly that is at that link? I don't see a way to start the engine. Is it a build for export?

**Comment by awindahl** [comment] 2019-08-12 09:04
I don't understand your comment, I linked the repository for the custom build of Godot. Download the source code and follow the guide in the docs for compiling the engine and export templates from source. All the best.

**Comment by tadaaagames** [comment] 2019-08-12 15:59
@awindahl is this making its way into official Godot?

**Comment by awindahl** [comment] 2019-08-12 16:33
This is just a custom version, I have no idea what the plans are.

**Comment by tadaaagames** [comment] 2019-08-12 16:39
Ok Thanks a lot.

**Comment by scottkunkel** [comment] 2019-09-07 17:17
Manually merged into my code, confirming it works great with mp3 sounds.
However, for some reason the html template on export is empty

**Comment by Calinou** [comment] 2020-04-18 13:01
Duplicate of #26554.

**Closed by Calinou** 2020-04-18 13:01 UTC
Labels: bug, platform:html5, platform:ios, topic:porting
