### ISSUE TITLE
Copy-pasting Unicode characters from some programs doesn't work under linux

### ISSUE THREAD

**Issue by ShivanshAnand** [godotengine/godot#8477] opened 2017-04-21 06:32 UTC
I'm using Ubuntu 12.0 and godot 2.1.2

Looks like I can't type Chinese and Hindi characters in godot. When I try to paste some non - latin text ( eg. some text in hindi ) in a label node , it instead of pasting the test pasting the text , pastes some unicode escape characters like /u9390/u8920......

https://cloud.githubusercontent.com/assets/871079/5474205/a39a8276-8620-11e4-8e78-56bf06bd9774.png

**Steps to reproduce:**

**Link to minimal example project:**

**Comment by bojidar-bg** [comment] 2017-04-21 12:42
I can confirm that copying text from chrome/chromium into godot ~2.1.3 works, so, seems like that part was fixed.
Actually, it didn't really work when copying from KCharSelect (I'm on KDE), but when copying KChar -> Chrome -> Godot, it works fine. Something fishy is going on here (probably related to Godot not being a QT app?)...

The "typing" part is a duplicate of #29

Not closing yet, since some parts of the issue remain (copy-pasting). For being able to type out those character using an IME, check the linked issue.

**Comment by kubecz3k** [comment] 2018-04-10 17:02
I was able to copy some Polish signs from Firefox as well as some Chinese (with Google translate). @ShivanshAnand can you please confirm that the issue still exists in current main or 3.0.2?

**Comment by bojidar-bg** [comment] 2018-04-10 20:17
I am able to copy from KCharSelect directly on 3.0.2.

**Comment by akien-mga** [comment] 2018-04-11 06:35
Assuming fixed in 3.0 (at least there were many changes regarding inputting and pasting Unicode characters, and above two tests confirm it). Please comment if you can still reproduce the issue.

**Closed by akien-mga** 2018-04-11 06:35 UTC
Labels: bug, confirmed, platform:linuxbsd, topic:porting, usability
