### ISSUE TITLE
Box Selection doesn't work properly

### ISSUE THREAD

**Issue by samvila** [godotengine/godot#12545] opened 2017-10-31 21:39 UTC
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Godot 3.0 Alpha 2, Windows 10 64 bit

Box Selection doesn't work properly, please see this video as a reference:
https://youtu.be/lRbefcsYDi4?t=55

When trying to select object using the box selection functionality on Godot I get some objects selected in the best case, usually I get no objects selected whatsoever.

**Comment by Zylann** [comment] 2017-10-31 21:46
Related #10979

**Comment by akien-mga** [comment] 2017-11-01 09:08
Let's close as duplicate of #10979 then, I'll add a link to the video there.

**Closed by akien-mga** 2017-11-01 09:08 UTC
