### ISSUE TITLE
Editor displaying export properties for Resource script on Node with Node script (script have the same name)

### ISSUE THREAD

**Issue by AhNesh** [godotengine/godot#51026] opened 2021-07-29 16:52 UTC
### Godot version

3.3.stable.mono

### System information

Windows 10

### Issue description

Two C# scripts with the same name, but different namespace and in different folders, one extending Node, the other extending Resource. If you add the script extending Node to a node in a scene, the editor will display the exported properties from the script that extends Resource, and those properties will be saved to the .tscn file. The path in the Script field is the path to the script that extends Node.

Happened in 3.3.stable.mono and also in 3.4.beta2.mono.

### Steps to reproduce

1. Create new project
2. Create folder Namespace1
3. Create script Class1.cs - extends Node, surround class with `namespace Namespace1 {}`
4. Create folder Namespace2
5. Create script Class1.cs - extends Resource, surround class with `namespace Namespace2 {}`, add an Export property
6. Build .csproj
7. Create Scene
8. Add Namespace1.Class1.cs script to node in scene
9. Export property from Namespace2.Class1.cs shows up in inspector on node in editor

![confusion](https://user-images.githubusercontent.com/33862238/127532842-059c2843-2592-4761-bfb2-5144c04064a2.png)

Namespace1.Class1.cs

```C#
using Godot;
using System;

namespace Namespace1
{
    public class Class1 : Node
    {

    }
}
```
Namespace2.Class1.cs
```C#
using Godot;
using System;

namespace Namespace2
{
    public class Class1 : Resource
    {
        [Export]
        public int MyProperty { get; set; }
    }
}
```

### Minimal reproduction project

[ClassNameConfusion.zip](https://github.com/godotengine/godot/files/6902176/ClassNameConfusion.zip)

**Comment by paulloz** [comment] 2021-09-18 16:49
I tried the provided project on `v3.3` and `v3.4.beta.mono.custom_build [95162ca39]` but I can't reproduce the described behaviour.

**Comment by AhNesh** [comment] 2021-09-20 16:24
I am not able to reproduce this with `v3.3` anymore either. Weird...

**Comment by Calinou** [comment] 2021-09-20 16:44
Closing, as nobody has been able to reproduce this recently. Please comment if you can still reproduce this on Godot 3.3.3 or later.

**Closed by Calinou** 2021-09-20 16:44 UTC
Labels: bug, topic:editor, needs testing, topic:mono
