### ISSUE TITLE
plane collider never response to is_on_floor()

### ISSUE THREAD

**Issue by dotquixote** [godotengine/godot#25868] opened 2019-02-14 05:47 UTC
**Godot version:**
master

**Issue description:**
kinematic vs static plane
same condition, other collision mesh type has no problem.

**Steps to reproduce:**

extends KinematicBody

func _ready():
	pass

func _physics_process(delta):
	move_and_slide(Vector3(0,-1,0),Vector3(0,1,0))
	if is_on_floor():
		print("I am on Ground")

**Comment by akien-mga** [comment] 2019-02-14 13:50
Duplicate of #5910.

**Closed by akien-mga** 2019-02-14 13:50 UTC
Labels: topic:physics
