### ISSUE TITLE
Godot crashes when deleting a child UI element in a callback

### ISSUE THREAD

**Issue by nuke-makes-games** [godotengine/godot#26751] opened 2019-03-07 13:43 UTC
**Godot version:** 3.1 beta 5

**OS/device including version:** Win 10

**Issue description:**

I created a very simple tooltip UI element with simple logic. If the user's mouse enters the parent element, it creates a tooltip next to the element. If the mouse exits the parent, the tooltip is deleted.

If the user moves their mouse on and off the parent element without mousing over the tooltip, it is fine. If the user moves their mouse from the parent element to the tooltip, Godot crashes.

I worked around this crash by not deleting the tooltip in the mouse_exited callback for the parent element and instead deleting it on the next _Process call.

**Steps to reproduce:**

I attached a project with a test scene (Scenes/test.tscn), open that and hover your mouse over the UI element then move it to the right to cause a crash.

Relevant code that causes the crash is in Src/Godot/UI/AttributeItem.cs

**Minimal reproduction project:**

[Game.zip](https://github.com/godotengine/godot/files/2941455/Game.zip)

**Comment by Zylann** [comment] 2019-03-07 13:48
So here is the problematic code:
AttributeItem.cs
```cs
    private void MouseExit() // this is called by mouse_exited signal
    {
        if (m_tooltip != null)
        {
            m_del = true;

            // this code results in the crash
            RemoveChild(m_tooltip);
            m_tooltip.Free();
            m_tooltip = null;
        }
    }
```
You are using `Free`, which *immediately* destroys the node. In some cases that means dangling pointers may cause a crash like here. You can try using `queue_free()` instead of remove and free.
Maybe you can also try `CallDeferred("free")`.

**Comment by nuke-makes-games** [comment] 2019-03-07 14:04
I tried QueueFree and CallDeferred("free") instead, and while it does not crash, it still causes errors:

`E 0:00:08:0622   Condition ' !is_inside_tree() ' is true. returned: get_transform()
  <C Source>     scene/2d/canvas_item.cpp:478 @ get_global_transform()
`

For now i'm happy with my workaround where i just delete the element the next time _Process is called.

**Comment by Zylann** [comment] 2019-03-07 14:07
@nuke-makes-games one of my two workarounds (queue free) still expects the node to be in the tree, are they both causing errors?

**Comment by nuke-makes-games** [comment] 2019-03-07 14:14
Both gave the same result, though I was calling RemoveChild in both tests so maybe that tainted the results.

**Comment by Chaosus** [comment] 2019-03-07 15:17
Assigned @reduz, maybe he knows how to properly fix it and safely apply to 3.1

**Comment by akien-mga** [comment] 2019-03-07 16:50
It would be good to have a GDScript-based MRP, to rule out a potential issue with the Mono module.

**Comment by KoBeWi** [comment] 2020-07-18 18:53
an anyone still reproduce this bug in [Godot 3.2.2](https://godotengine.org/article/maintenance-release-godot-3-2-2) or any later release?

If yes, please ensure that an up-to-date Minimal Reproduction Project (MRP) is included in this report (a MRP is a zipped Godot project with the minimal elements necessary to reliably trigger the bug). You can upload ZIP files in an issue comment with a drag and drop.
(the attached project doesn't run in 3.2.2 due to errors; also a GDScript project would be useful, as noted comment above)

**Comment by KoBeWi** [comment] 2020-09-28 22:36
Closing due to lack of update. Please comment if you can still reproduce this issue in the latest stable version of Godot.

**Closed by KoBeWi** 2020-09-28 22:36 UTC
Labels: bug, topic:core
