### ISSUE TITLE
New windows close immediately when opened from a popup menu (DisplayServer regression)

### ISSUE THREAD

**Issue by neikeq** [godotengine/godot#38931] opened 2020-05-21 17:44 UTC
**Godot version:**
4.0 dev (9239412027b6c25009efab69dc39650e0d76c56d)

**OS/device including version:**
Ubuntu 20.04 64-bit

**Issue description:**

New windows close immediately after being opened if they where opened from a popup menu.
This includes windows opened from:
- The main menu, e.g.: `Editor Settings`, `Project Settings`, `Export`, `Manage Export Templates...`.
- The context menu of the FileSystem, e.g.: "New Folder/Scene/Script/Resource...`, `Rename...`, `Move To...`.
- The context menu of the Scene dock, e.g.: `Add Child Node`, `Instance Child Scene`, `Attach Script`.

In some weird cases I've managed to open `Editor Settings` without it closing immediately, but this seems too random.

Windows that are not opened from a popup menu on the other hand stay open as expected.
This includes windows opened from:
- The Scene dock toolbar, e.g.: `Add Child Node`, `Instance Child Scene`, `Attach Script` (these are the same I mentioned before which don't work when opened from the context menu).
- The Inspector dock toolbar, e.g.: `Create New Resource`, `Open A File`.
- The `Make Floating` button when changing a dock's position. Notice how this one works even though it's open from the `Dock Position` popup, so this seems to be specific to popup menus.

**Steps to reproduce:**

Open the editor and try to open the `Editor Settings` from the main menu. It should close immediately.

**Comment by neikeq** [comment] 2020-05-21 17:45
I wonder if I'm the only one experiencing this bug as I couldn't find any other issue about it and it's not listed in #37734.

**Comment by Anutrix** [comment] 2020-05-21 19:12
It seems to be Linux specific issue. I even suspect it to be Ubuntu 20 specific issue.

**Comment by neikeq** [comment] 2020-05-21 23:10
Oops, yes. Forgot to say that. I cannot reproduce on Windows 10 either.

**Comment by mrushyendra** [comment] 2020-05-23 02:42
I wasn't able to reproduce on Ubuntu 16.04 LTS 64-bit. Windows that were opened from the popup window seemed fine and persisted, as seen from this [video](https://github.com/godotengine/godot/files/4671017/godot_4_window_recording.mp4.zip). 

However, they did automatically close when they went out of focus when I clicked on something else (not sure if that is a feature or a bug).

**Comment by rileylyman** [comment] 2020-05-29 04:46
I also experience this issue on Ubuntu 18.04. It seems that when my mouse leaves the popup it closes.

**Comment by swarminglogic** [comment] 2020-06-12 13:21
I also experience this on two separate `Ubuntu 19.04` systems with different hardware. It's more or less everywhere making it clunky to use.

I suspect it's the same issue when creating new projects, where the popups there for choosing directories close the parent window (the "New Project/Create New Project" view)

As for the particular details mentioned in the original post are a bit different for me (Currently running a fresh `84abf5a97`). For instance `Project Settings` and `Editor Settings` work without issue, but for example deleting a node using <right-click> -> `Delete Node(s)` causes the deletion-confirmation-popup to auto-close as soon as it shows up. I've tried this many times now, and occasionally it does stay open. Something like 1/20 stay open.

Getting the same popup using `<del>` never has this issue.

Also, the relative path from the mouse to the popup is off. The context menu does not appear from the cursor position but rather at some fixed position on the left side of screen (coordinates `132,148`). This is regardless of mouse position and window position. Though, if the godot editor is on the right monitor, the popup location is touching the left edge. New windows also pop up on the left monitor even if the window is on the right. Which monitor the initial start was on has no effect on this.

The reason why I mention all of these things in this issue is that could all be related to the display server.

**Comment by swarminglogic** [comment] 2020-06-12 15:32
Running some bisecting to narrow it a bit down. The faulty behavior in question seems to emerge between `09ba290364a` (newer) and `543fb1c4dadd7` (older by 3 commits) . In the latter, the popups appear in the right position and do not disappear immediately after creation. There are however other issues though, like the inability to register clicks within some windows. Hopefully this is of some help.

**Comment by abueide** [comment] 2020-06-15 06:43
is my bug possibly related? https://github.com/godotengine/godot/issues/39555

**Comment by Anutrix** [comment] 2020-06-15 06:45
> 
> 
> is my bug possibly related? #39555

No. That issue is present in Windows too is related to another issue.

**Comment by neikeq** [comment] 2020-07-05 11:39
Seems fixed on latest master. cc @reduz Any idea what commit could have fixed it?

**Comment by akien-mga** [comment] 2020-07-06 06:47
Likely fixed by #39993.

**Closed by akien-mga** 2020-07-06 06:47 UTC
Labels: bug, confirmed, platform:linuxbsd, regression, topic:core, topic:editor

**Comment by russinet** [comment] 2023-08-26 16:35
Still not fixed in 4.1.1. My symptoms align with those outlined here (i.e. Project Settings are fine, but something like Add Node closes). Sometimes it works as expected, but most of the time it just doesn't work. Just for the sake of adding extra data points, my Godot is from Flathub and I'm running a Wayland session.

**Comment by russinet** [comment] 2023-08-26 16:40
As a workaround, enabling "Single Window Mode" in Editor Settings seems to fix the issue since it's not using Linux's window manager.

**Comment by jcrd** [comment] 2023-10-18 19:13
I am having a similar issue. This is the mostly closely related existing issue I could find and enabling "single window mode" as suggested above fixes my issue too, so I will share details here:

Godot v4.1.2.stable.flathub [399c9dc39]
Gnome 44.4 with Wayland on Fedora 38

To reproduce:
1. Attach a new script to a node - the "Add Node Script" dialogue works as expected
2. Open the "Choose Location" dialogue - this works as expected
3. Change the path and click Open

The updated "Add Node Script" dialogue should now be visible, but instead it is sent to the background (it is visible in the Activities overview of Gnome) and is unable to be brought to the foreground to use, but it can still be closed.
