### ISSUE TITLE
Confusing things in physics

### ISSUE THREAD

**Issue by 2plus2makes5** [godotengine/godot#18394] opened 2018-04-24 11:38 UTC
While reading Godot's documentation isn't rare to read something like: "it can be confusing" or similar because yes some things may actually be confusing. One of the most confusing part is the physics one, let's start with layers:

collision_layer
collision_mask

in the collision_mask description is written:
"...If an object isn’t in one of the mask **layers**..."

so even the collision_mask is a layer, but then why there's a collision_**layer** and a collision_mask if both are layers? In my opinion their names should specify that they are layers and their function, i would suggest something more clear like:

collision_presence_layer
collision_scan_layer 

or something similar, or at least to rename collision_mask to collision_mask_layer

Another issue is physic bodies names, i know that they are physics terms that correctly describe them, but not everyone remember or have studied those terms, so in my opinions more "mainstream" names could help, but the real problem is Rigid_Body.

From the documentation:
"StaticBody2D
A static body is one that is not moved by the physics engine. It participates in collision detection, but does not move in response to the collision. They are most often used for objects that are part of the environment or that do not need to have any dynamic behavior.

RigidBody2D
This is the node that implements simulated 2D physics. You do not control a RigidBody2D directly, but instead you apply forces to it (gravity, impulses, etc.) and the physics engine calculates the resulting movement. Read more about using rigid bodies.

KinematicBody2D
A body that provides collision detection, but no physics. All movement and collision response must be implemented in code."

but then you go on and read that Rigid_body has various modes included:

"Static - The body behaves like a StaticBody2D and does not move.
...
Kinematic - The body behaves like a KinematicBody2D and must be moved by code."

So what's the difference between Rigid and Kinematic and Static? What's the point of Kinematic and Static if Rigid can do what they can do? Why calling it "Rigid" if it can also be not rigid?

In my opinion it would be less confusing if the Rigid_body was limited to the Rigid mode(like Kinematic and Static that have no other modes) and what is now called Rigid_Body was renamed to something like Generic_Body, and even better if instead of modes it had flags that we can choose from and mix to make our own modes to make the node to behave like we want.

Sorry if i wrote a lot and/or this isn't helpful.

**Comment by 2plus2makes5** [comment] 2018-04-24 16:06
Other names, probably better, that came in my mind later are:

object_layer(s)
collision_detection_layer(s)

and

Custom_Body or Custom_Physics_Body for what i previously called Generic_Body.

**Comment by AndreaCatania** [comment] 2018-05-01 16:36
A RigidBody can be Static, Kinematic or Rigid.. And there's no difference with the StaticBody or KinematicBody. So it is a bit confusing. 

Remove the possibility to make it kinematic and static from the editor could help, but we have to leave the possibility to change it trought scripting because is useful control the mode of RigidBody.

Instead for the layer and mask names, the naming can be improved I suggest these: `collision_type` and `collide_with`

**Comment by Calinou** [comment] 2020-04-27 07:32
Right now, the property hint for the PhysicsBody nodes is: `"Rigid,Static,Character,Kinematic"`

We could hide the values at the end by removing them from the property hint, but the issue is that we want to hide **Static**, which is in between **Rigid** and **Character**. Therefore, we'd have to reorder the enum first, which breaks compatibility.

**Comment by AndreaCatania** [comment] 2020-04-27 07:50
@Calinou yes. Re reading this issue I'm wondering why we should hide it. Even if each mode, code wise, is really similar; conceptually these are different from each other.

Each one has its own reason to exist, and I don't agree that see those is confusing. Of course, choose one of those mode require to know what each one does, but this is not a reason to hide it.

However, I still think this is an advanced property, and probably would be better move that as one of the last property of the inspector so to not give such importance as it has now.

**Comment by MrSuit** [comment] 2020-05-08 17:05
Hi, can I join discussion?

I don't wanna create new issue for this when I found already similar one.
Is not it confusing for you that in project settings are layers [1,2,3,4]  and so on. You can actually name them. But actually in source code you are getting collision_layer or collision_mask from PhysicsBody2D, which is actually some value represented as integer. I did not found anything useful to this topic in documentation. Of course you can finally call function get_collision_layer_bit or get_collision_mask_bit.

For me it is a little bit confusing that same name in project settings and for property of this class actually represents 2 different things.

And next one, in same code for PhysicsBody2D class in property description is written that you can use all 32 layers, so what the hack. I absolutely do not get it
Maybe it would be nice to fix this as well.

What do you think about this?

**Comment by MrSuit** [comment] 2020-05-08 17:23
Ok so collision_mask or layer are in real the summaries of PhysicsBody2D collision [mask, layer] bits :/

**Comment by madmiraal** [comment] 2020-06-24 11:55
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!

**Closed by madmiraal** 2020-06-24 11:55 UTC
Labels: discussion, documentation, topic:physics
