### ISSUE TITLE
GLES3 gltf Intel Black Model Bug

### ISSUE THREAD

**Issue by Echua36** [godotengine/godot#43149] opened 2020-10-28 01:36 UTC
**Godot version:**

Godot_v3.2.3-stable_win64

**OS/device including version:**

i5-9300h, GTX 1650(laptop version), intel uhd 630, GLES3

**Issue description:**

export tree form blender 2.90.1 with gltf option, import to godot then showing black color when viewing on certain fixed angle and grid disappearing

**Steps to reproduce:**
place the Bill's Tree.gltf on 0 transfrom (or anywhere), add meshinstance with non-flat mesh (capsule,cube,cylinder,prism and sphere) with intel uhd 630 and GLES3 as renderer then deselect everything (or not selecting a node) try find fixed angle to reproduce the black look on my screenshot 
it does not happen on GLES2
it less likely to happen with GTX 1650 (not tested with GLES2) or many copies with the tree
**Minimal reproduction project:**

[Render Bug Report.zip](https://github.com/godotengine/godot/files/5448930/Render.Bug.Report.zip)

**Comment by Echua36** [comment] 2020-10-28 01:49
it happens in Play (F5) too

**Comment by Flavelius** [comment] 2020-10-29 13:46
I noticed that your source model has non-uniform scale. godot (as opposed to other engines) treats this as a special case where it doesn't ensure the model looks correct by default; i had a similar problem where checking the 'Ensure correct normals' in the spatial material solved it, maybe that fixes your problem too.

**Comment by Echua36** [comment] 2020-10-29 14:11
Still black even turn on ensure correct normals on uhd 630, the only way to fix this is downgrade to GLES2 or use gtx 1650 or place batch of them reduce it
![Godot_v3 2 3-stable_win64_nhmF09mXf8](https://user-images.githubusercontent.com/45130922/97584482-0d13fc80-1a33-11eb-9408-4b89318cc059.png)
![Godot_v3 2 3-stable_win64_2ra7wStDHz](https://user-images.githubusercontent.com/45130922/97584498-11401a00-1a33-11eb-9f10-67e3c71dca21.png)
![Godot_v3 2 3-stable_win64_MzVMrCtxv2](https://user-images.githubusercontent.com/45130922/97584508-1309dd80-1a33-11eb-93b2-386a8ba120f4.png)

**Comment by Zireael07** [comment] 2020-10-29 14:33
If it's black only on the Intel, it's a dupe of an already reported issue (search for "black" and "Intel")

**Comment by Echua36** [comment] 2020-10-29 15:36
yes i'm sure it's dupe of https://github.com/godotengine/godot/issues/30330

**Comment by Calinou** [comment] 2020-10-29 17:44
Duplicate of https://github.com/godotengine/godot/issues/30330.

**Closed by Calinou** 2020-10-29 17:44 UTC
