### ISSUE TITLE
Godot Engine v4.0.beta6 don't open with Vulkan API 1.1.0 - Using Vulkan Device #0: Intel - Intel(R) HD Graphics 520

### ISSUE THREAD

**Issue by papatv** [godotengine/godot#69158] opened 2022-11-25 06:40 UTC
### Godot version

Godot Engine v4.0.beta6.official.7f8ecffa5

### System information

Windows 10, Intel(R) HD Graphics 520 Vulkan API 1.1.0

### Issue description

Godot Engine v4.0.beta6 don't open with Vulkan API 1.1.0 - Using Vulkan Device #0: Intel - Intel(R) HD Graphics 520 in windows 10, I tried but never open, godot show the projects and  then when I click in edit, the window is black.
![2022-11-25 (8)](https://user-images.githubusercontent.com/16613720/203916031-70b3960c-9116-4495-a1fc-1d8c090377fc.png)
![2022-11-25 (10)](https://user-images.githubusercontent.com/16613720/203916115-ca38cf9e-b11e-47fb-bd78-0fc5d5e5388f.png)
![2022-11-25 (9)](https://user-images.githubusercontent.com/16613720/203916140-00c2bc81-52f6-4b1d-8a19-add549977b00.png)
![2022-11-25 (11)](https://user-images.githubusercontent.com/16613720/203916145-d667d0f4-5b37-45e1-b0b9-5f884a847277.png)

### Steps to reproduce

Godot Engine v4.0.beta6 don't open with Vulkan API 1.1.0 - Using Vulkan Device #0: Intel - Intel(R) HD Graphics 520 in windows 10, I tried but never open, godot show the projects and then when I click in edit, the window is black.

### Minimal reproduction project

Godot Engine v4.0.beta6 don't open with Vulkan API 1.1.0 - Using Vulkan Device #0: Intel - Intel(R) HD Graphics 520 in windows 10, I tried but never open, godot show the projects and then when I click in edit, the window is black.

**Comment by clayjohn** [comment] 2022-11-25 06:46
Duplicate of https://github.com/godotengine/godot/issues/69046

**Closed by clayjohn** 2022-11-25 06:46 UTC
