### ISSUE TITLE
Crash while closing editor: Resources still in use at exit / ObjectDB instances still exist

### ISSUE THREAD

**Issue by jahd2602** [godotengine/godot#5801] opened 2016-07-19 03:55 UTC
**Operating system or device - Godot version:**
Windows 8.1
Godot 2.1

**Issue description** (what happened, and what was expected):
After closing the editor, windows reports a program crash, and the console shows various error messages.

![breakout godot](https://cloud.githubusercontent.com/assets/2841740/16938091/55dad206-4d3a-11e6-82b3-399061e8623a.png)

**Steps to reproduce:**
1. Open project
2. Close editor
3. Crash

**Link to minimal example project** (optional but very welcome):
http://www.mediafire.com/download/g08l7saby12b5q7/Breakout.zip

**Comment by akien-mga** [comment] 2016-07-19 05:17
Thanks, it's a duplicate of #5664 and is fixed in git already.

**Closed by akien-mga** 2016-07-19 05:17 UTC

**Comment by Osimedias** [comment] 2018-05-09 18:49
I have the same error, i use godot 3.0.2
it started to happen to me when I was testing my project

**Comment by vnen** [comment] 2018-05-09 18:56
@Osimedias the error message itself is not a problem, it usually means something about your project. The problem was the crash. But this is an old issue that was fixed a long time ago, if you are getting crashes please open a new issue.

**Comment by jahd2602** [comment] 2018-08-19 22:07
@Osimedias is it happening on Windows or iOS?

It started happening to me in iOS, and I fixed it with https://github.com/jahd2602/godot/commit/1250c176068b45727448bcb9d9a0b52f9a392a85
