### ISSUE TITLE
Editor Script Reload Error when class that is defined in autoload singleton script references the autoload singleton

### ISSUE THREAD

**Issue by chanon** [godotengine/godot#19596] opened 2018-06-16 09:13 UTC
**Godot version:**
master branch

**Issue description:**
When a class that is defined in an autoload singleton script references the autoload singleton, the editor will display a parse error to the output log, even though when actually run it runs fine.

**Steps to reproduce:**
Example autoload script `Global.gd`:
```
extends Node

class TestClass:
	func sayHello():
		Global.hello("someone")  # parse error here, Global is null or undefined

func _ready():
	var test = TestClass.new()
	test.sayHello()

func hello(name):
	print("hello " + name)
```

Output:
![image](https://user-images.githubusercontent.com/357737/41497556-70c93400-7181-11e8-99e3-531b6fa3c355.png)

Then when running the project:
![image](https://user-images.githubusercontent.com/357737/41497561-895584d8-7181-11e8-8969-0f63482617f8.png)
(The editor autoload failed, but it works when running the game.)

(This used to work fine without errors before the "autoloads in editor" commit.)

**Minimal reproduction project:**
[ClassCantAccessSingleton.zip](https://github.com/godotengine/godot/files/2107989/ClassCantAccessSingleton.zip)

**Error when used with Typed GDScript pull request**
If this project is opened in https://github.com/godotengine/godot/pull/19264 it will not allow the code to run, even though it is valid.

This is output when used with Typed GDScript:
![image](https://user-images.githubusercontent.com/357737/41497513-fed9bba8-7180-11e8-8a06-c9251a107575.png)

**Comment by akien-mga** [comment] 2018-06-16 09:18
CC @vnen

**Comment by vnen** [comment] 2018-06-16 18:21
The problem is that those scripts are being parser/compiled before the autoloads are in place. I was thinking about this, because after I removed the autoloads from the tree in-editor, I couldn't initialize them so soon anymore.

The only solution I can think of is to add an autoload manager singleton in the editor to handle this before the editor node is created.

**Comment by chanon** [comment] 2018-06-17 11:49
Here is another similar case:
[ClassCantAccessSingleton2.zip](https://github.com/godotengine/godot/files/2108914/ClassCantAccessSingleton2.zip)

In this case, if an autoload singleton preloads another script which references the autoload singleton, an error will result. Again, the Typed GDScript build will not allow the game to continue running.

`Global.gd`:
```
extends Node

const MyNode = preload("res://MyNode.gd")

func test(instance):
	if instance is MyNode:
		print("We got a MyNode")
	else:
		print("Not a MyNode")
```

`MyNode.gd`
```
extends Node

func _ready():
	Global.test(self) # error says Global is null
```

**Comment by vnen** [comment] 2018-06-18 18:55
Actually, I got a simple fix for this. It seems I forgot to register the autoloads in the proper order. I still need to test how this works with typing, but it shouldn't be a problem.

**Closed** 2018-06-18 21:52 UTC
Labels: bug, topic:gdscript
