### ISSUE TITLE
Cursor doesn't skip to the end of input box when all is selected and left arrow clicked.

### ISSUE THREAD

**Issue by DavidHusicka** [godotengine/godot#32801] opened 2019-10-13 16:43 UTC
**Godot version:**
3.2 alpha build 2

**OS/device including version:**
Windows 10 64 bit

**Issue description:**
When you click on any input box, all is selected. When all is selected and arrow key is pressed, it deselects (which is correct behaviour) but the cursor doesn't jump to end of input box.
Example of correct behaviour in Firefox: https://www.youtube.com/watch?v=8Si9YmlCUsM&feature=youtu.be
Exapmle of incorrect behaviour in Godot: https://youtu.be/lzOm7-Uu0j8

**Steps to reproduce:**
Make the cursor skip to the end when all is selected

**Comment by silvanocerza** [comment] 2019-10-24 20:53
To do what you want you must press Control + Left or Right, on Mac it's probably Command instead of Control.

It might make sense to change the behaviour but I think this is not the only thing that needs to be changed. 
For example on Firefox if you select the whole text with Control+A and then press Shift+Right nothing happens, but if you press Shift+Left, you deselect the rightmost selected character, the same happens if you select by dragging over the text from left to right.
But this changes if you select by draggin from right to left, in this case Shift+Left does nothing, but Shift+Right deselect the leftmost selected character.

This probably needs to be discussed before being implemented.

**Comment by EricEzaM** [comment] 2020-09-22 13:42
Can't reproduce in current master - solved?

**Comment by akien-mga** [comment] 2020-09-22 13:56
It's reproducible in 3.2.3-stable, but seems fixed in `master` indeed, so closing.

**Closed by akien-mga** 2020-09-22 13:56 UTC
Labels: enhancement, topic:editor, usability
