### ISSUE TITLE
It seems the screen size on some Android device is not correct.

### ISSUE THREAD

**Issue by alexzheng** [godotengine/godot#12123] opened 2017-10-15 13:35 UTC
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
godot 2.1
Android 7.1.1

**Issue description:**

Device XiaoMi Mix2, its screen size is 1080*2160
Project Settings:
Stretch Mode: 2d
Stretch Aspect: keep width
Width:1242
Heigh:2208

I try all these api
       OS.alert(str(get_tree().get_root().get_rect()))
	OS.alert(str(get_viewport().get_rect()))
	OS.alert(str(OS.get_video_mode_size()))
	OS.alert(str(OS.get_window_size()))

The result is 1080*2030

Only part of the screen is rendered.
And if I add a banner to the bottom,the banner is cropped.

**Steps to reproduce:**

**Link to minimal example project:**

**Comment by alexzheng** [comment] 2017-10-15 13:41
Here is the normal screen and the screen rendered by Godot.

![img_3233](https://user-images.githubusercontent.com/1130047/31585257-7e8a8152-b1f1-11e7-9fc4-163ef02c0b0e.JPG)
![img_3234](https://user-images.githubusercontent.com/1130047/31585258-7fe336b6-b1f1-11e7-8577-48637ab0a5e9.JPG)

**Comment by volzhs** [comment] 2017-10-15 16:50
what about changing Stretch Aspect to ignore or expand?

**Comment by volzhs** [comment] 2017-10-15 17:01
this "only part of screen rendered" problem(?) happens with almost games now which, based on 16:9 ratio.
I'm using galaxy s8+ 1440 x 2960 pixels / 18.5:9 ratio.
and I think, you should take care of the admob position correctly.

**Comment by alexzheng** [comment] 2017-10-16 00:47
change the Stretch Aspect will not effect the size.

**Comment by alexzheng** [comment] 2017-10-16 01:00
I just use adParams.gravity = Gravity.BOTTOM to align the banner.
If I align the banner to top use Gravity.TOP, the banner will not be cropped.

**Comment by alexzheng** [comment] 2017-10-16 01:07
Here is the render screen of my game made by some other engine, it rendered the full screen.
![img_3236](https://user-images.githubusercontent.com/1130047/31591337-59313f26-b251-11e7-8a46-d4b11c80bd49.JPG)

**Comment by mhilbrunner** [comment] 2018-04-10 16:40
First of all thank you for your report and sorry for the delay.

We released Godot 3.0 in January 2018 after 18 months of work, fixing many old issues either directly, or by obsoleting/replacing the features they were referring to.

We still have hundreds of issues whose relevance/reproducibility needs to be checked against the [current stable version](https://godotengine.org/download), and that's where you can help us.
**Could you check if the issue that you described initially is still relevant/reproducible in Godot 3.0 or any newer version, and comment about it here?**

For bug reports, please also make sure that the issue contains detailed steps to reproduce the bug and, if possible, a zipped project that can be used to reproduce it right away. This greatly speeds up debugging and bugfixing tasks for our contributors.

Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

Thanks in advance.

*Note: This message is being copy-pasted to many "stale" issues (90+ days without activity). It might happen that it is not meaningful for this specific issue or appears oblivious of the issue's context, if so please comment to notify the Bugsquad about it.*

**Comment by akien-mga** [comment] 2019-04-15 14:23
> Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

As there was no update since the previous post, we close this issue.

If it is still relevant in the way it was described and discussed above, please comment to ask for it to be reevaluated. If it is only partly relevant, or if the original issue has changed, it would be better to open a new issue (potentially referring to this one) focused on the current state.

**Comment by leakim34** [comment] 2019-08-10 20:14
Hi ,
I noticed same issue with Huawei P20 Pro which has 18.7:9 ratio 2240x1080 resolution.
In expand or 2d mode it returns me (OS.get_window_size() or even viewport size .. ) a resolution of 2159x1080. 

I tested many other android devices and all of them were correct except this Huawei p20 pro. 

Thanks

**Comment by AlexHCC** [comment] 2020-04-06 16:32
Any update on this? I am facing the same issue with the Xiaomi Mi A3 in Godot 3.2.

Basically OS.get_screen_size() returns the same screen resolutions as OS.get_window_safe_area() witch is 1490x720 but the device has a notch and a screen resolution of 1560x720. As a result I get black bars outside the safe area.

Seems like Godot confuses the full screen size of some mobile devices with the safe area.

**Comment by azmrv** [comment] 2020-07-04 14:47
Xiaomi Redmi Note 6 the same bug with screen size

**Comment by AlexHCC** [comment] 2021-04-22 13:00
This has been fixed for me, Godot 3.3 adds notch support.

**Comment by akien-mga** [comment] 2021-04-22 13:54
Indeed, thanks for the update!

**Closed by akien-mga** 2021-04-22 13:54 UTC
Labels: bug, platform:android, topic:porting
