### ISSUE TITLE
non-selectable children icon glitch on new scene

### ISSUE THREAD

**Issue by KellyThomas** [godotengine/godot#15942] opened 2018-01-21 13:30 UTC
**Godot version:**
Godot_v3.0-rc2_mono_win64

**OS/device including version:**
Windows 7

**Issue description:**
If I have a 2D scene containing nodes with the non-selectable children option set and then create a new scene the icons are still drawn.

These icons disappear if I toggle scene tabs, resize the panel or window, change 2d/3d modes... pretty much anything that causes a redraw.

Existing Scene:
![image](https://user-images.githubusercontent.com/1151394/35194544-48cfd458-fef0-11e7-9b0f-8d2fee31d29f.png)

New Scene:
![image](https://user-images.githubusercontent.com/1151394/35194691-332daf38-fef2-11e7-986f-cbde99ee01da.png)

**Steps to reproduce:**

  1. New project
  2. Add child node, pick Node2D
  3. Click the "Make sure the object's children are not selectable" button.
  4. Create a new scene

**Minimal reproduction project:**
[test project.zip](https://github.com/godotengine/godot/files/1649774/test.project.zip)

**Comment by vnen** [comment] 2018-01-21 18:22
Duplicate of #14500.

**Closed by vnen** 2018-01-21 18:22 UTC
