### ISSUE TITLE
Unexpected RigidBody child behaviour in Bullet 

### ISSUE THREAD

**Issue by VercingetorixChief** [godotengine/godot#41003] opened 2020-08-03 17:50 UTC
**Godot version: 3.2.3 RC3**

**OS/device including version:**
Windows 10 64-bit

**Issue description:**

There seems to be a bug with regards to physics of RigidBody childs of RigidBodies.

- Seems to be only happening in Bullet.
- I did not have this issue with the 3.2.3 beta. (I forgot which specific commit I was building from)
- RigidBody children connected by a HingeJoints seem to be completly unaffected by physics. 

Behaviour in Bullet:
![test2](https://user-images.githubusercontent.com/10586460/89210972-0d653e80-d58f-11ea-8d1a-3feb704dda6e.gif)

Behaviour in GodotPhysics:
![test3](https://user-images.githubusercontent.com/10586460/89211028-27068600-d58f-11ea-8872-6dcc2fae9492.gif)

**Steps to reproduce:**
Have any RigidBody child to a RigidBody node.

**Minimal reproduction project:**
[test.zip](https://github.com/godotengine/godot/files/5017442/test.zip)

**Comment by VercingetorixChief** [comment] 2020-08-03 18:15
I also had the following error stack when starting the project. This does not get thrown every time though and I cant reliably reproduce it. So I dont know if it is related.

ERROR: shape_get_data: Condition "!shape->is_configured()" is true. Returned: Variant()
   At: servers/physics/physics_server_sw.cpp:125
ERROR: CylinderShape is not supported in GodotPhysics. Please switch to Bullet in the Project Settings.
   At: servers/physics/physics_server_sw.cpp:73
ERROR: get: Condition "!p_rid.is_valid()" is true. Returned: __null
   At: ./core/rid.h:149
ERROR: shape_set_data: Condition "!shape" is true.
   At: servers/physics/physics_server_sw.cpp:103
ERROR: Invalid ID.
   At: servers/physics/physics_server_sw.cpp:1400
ERROR: set_data: Condition "!d.has("cell_size")" is true.
   At: servers/physics/shape_sw.cpp:1640
ERROR: get: Condition "!p_rid.is_valid()" is true. Returned: __null
   At: ./core/rid.h:149
ERROR: body_attach_object_instance_id: Condition "!body" is true.
   At: servers/physics/physics_server_sw.cpp:671
ERROR: Invalid ID.
   At: servers/physics/physics_server_sw.cpp:1400

**Comment by VercingetorixChief** [comment] 2020-08-03 22:24
I looked at into it a bit more. And the 3.2.2 stable build also gives me the same issue. I have been building Godot from source for the last year or so. And none of those builds were giving me this issue. 

I am planning on doing a clean build of the 3.2 branch when I have time to do so. 

So I am really not sure what's going on. It might just be my system specific. But I cant imagine what it could be.

**Comment by madmiraal** [comment] 2020-08-04 07:16
This issue exists in 3.1-stable too. The issue is not present in 3.0.6.

**Comment by madmiraal** [comment] 2020-08-04 11:12
Fixed on `master` with #40184 i.e. it will be fixed in 3.2 with #40788.

**Closed by madmiraal** 2020-08-04 11:12 UTC
Labels: bug, topic:physics
