### ISSUE TITLE
Save and restart does not prompt to save unsaved changes

### ISSUE THREAD

**Issue by GimmickNG** [godotengine/godot#63787] opened 2022-08-01 16:35 UTC
### Godot version

4.0.alpha13.official (59dcddc45)

### System information

Windows 10

### Issue description

When making changes requiring a restart, unsaved changes are not prompted to be saved. The editor closes and restarts, and all unsaved changes are lost.

### Steps to reproduce

- Make some changes in a project
- Editor > Editor Settings > Interface > Editor
- Change the display scale from 75% to 100% (or to any other value)
- Click "Save and Restart"
- Editor restarts, all unsaved changes are lost

**Comment by Calinou** [comment] 2022-08-01 17:09
Duplicate of https://github.com/godotengine/godot/issues/43302.

**Closed by Calinou** 2022-08-01 17:09 UTC
