### ISSUE TITLE
Anti-alias in 2D

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#12840] opened 2017-11-11 17:21 UTC
After looking at those issues: https://github.com/godotengine/godot/issues/10241, https://github.com/godotengine/godot/issues/7242#issuecomment-343637952

I saw that Godot supports anti-aliasing using MSAA, but I was surprised that this is only active in 3D. I tried to set it to 2x, 4x, and I saw a neat difference in 3D viewport, but none in 2D (using Line2D or Polygon2D to test it).
![image](https://user-images.githubusercontent.com/1311555/32691799-7ab47764-c70d-11e7-879b-9815d3417d0f.png)

Could it be made optionally available in 2D too?

Note: not sure if I should have posted in the first old issue rather than creating a new broader one

**Comment by reduz** [comment] 2017-11-11 17:37
It should be possible to enable it in 2d eventually...

**Comment by starry-abyss** [comment] 2017-12-22 14:47
May be added for 3.1? A bone-animator friend can't start using Godot because of this

**Comment by reduz** [comment] 2017-12-22 14:55
Yeah, should be tagges for 3.1

**Comment by icnikerazah** [comment] 2018-01-04 22:02
i can't start my 2d snooker game project because, there is no way to draw anti-aliased line. it's a shame for a game engine.

**Comment by reduz** [comment] 2018-01-04 22:04
@icnikerazah we had to cut the feature addition at some point :( you will have to wait some weeks.

**Comment by Zylann** [comment] 2018-01-04 22:05
I also realized that some other games (like Terraria I think?) support anti-alias on pixels themselves, so pixel-art with uneven zooming levels can also benefit from it.

**Comment by reduz** [comment] 2018-01-04 22:07
well, you can always supersample yourself by allocating a twice as big
viewport and scale it back, might still work fine for 2D

**Comment by Zylann** [comment] 2018-01-04 22:08
@reduz isn't it what AA is doing in 3D currently?

**Comment by icnikerazah** [comment] 2018-01-04 22:16
i have tried everything. no way in 2d.

**Comment by reduz** [comment] 2018-01-04 22:29
@Zylann No, not really, if your scaling is done properly, you should need to touch zero game code.

**Comment by Zylann** [comment] 2018-01-04 22:33
@reduz from what I've tried so far, GUI doesn't scale. By that, I mean it does RESIZE, but doesn't scale with resolution unless you find some magical code to do so... or maybe I miss something?

**Comment by Calinou** [comment] 2018-01-05 00:07
> @reduz isn't it what AA is doing in 3D currently?

No, Godot just tells the OpenGL driver to enable MSAA for the viewport (which can be done without restarting the engine). Rendering everything at an higher resolution then scaling it down is called SSAA (super-sampling), and is a much slower method of anti-aliasing (but it's technically the nicest-looking).

**Comment by tuxalin** [comment] 2018-01-05 10:38
There's a cheaper way to provide AA for lines by using distance fields, it's also more flexible as you can control the AA radius and can add more features like outline, configurable line caps or dashed patterns.
If someone can guide me where I can find the current implementation(geometry generation, shaders, testing) I can start working on it, as it will require some new attributes for the geometry and new shaders.

**Comment by Zylann** [comment] 2018-01-05 12:31
@tuxalin The Line2D drawing code is in https://github.com/godotengine/godot/blob/master/scene/2d/line_2d.cpp#L226, but it's far from being the only thing that needs AA. You might open another issue for this because although it could provide AA too, it's a different feature.

**Comment by reduz** [comment] 2018-01-05 12:59
The problem with AA in the line code is that NVidia has decided to not
support Line AA, even though it's dictated by specification. I still have
to try other approaches to do  AA, but there is no more time for this for
3.0. If anyone wants to propose soemthing in the meanwhile, feel free.

**Comment by tuxalin** [comment] 2018-01-06 23:45
@Zylann , thanks for the info!
I've looked over the code and it's a bit more work than I expected, so yes it wont make for 3.0.

The whole line generation needs to be rewritten as I see it use a basic shader(with position, color and uv attributes) and optional textures. The distance field approach is purely vectorial and no textures will be required(except if you want custom patterns) and will require different attributes(position and tangents, 3 floats).

@reduz , regarding AA, if you mean line primitives, then yes, those are legacy and some vendors chose not to offer AA support(GL_LINE_SMOOTH) for them, especially that you can write your own line shaders designed for your use case.

If wanted I can make another issue for this, however without distance fields you're left few approaches(tried them before) that wont achieve the same AA quality or flexibility, and MSAA will be expensive until the quality is good enough(guessing 8x).
If you're interested on the approach I propose check out this paper: https://hal.inria.fr/hal-00907326/file/paper.pdf

**Comment by Qws** [comment] 2018-04-30 09:40
I guess I can't expect anti-aliasing for 2.1 ever? (Sorry for late comment/bump)

I've been making a 2D game with high resolution for year in 2D, almost done. But this issue has always kinda disturbed me but I wanted to find solution later. Looks like there is no solution yet to avoid this sharp razor points on 2d like Anti-aliasing?

What can I do best to have anti-aliasing effect on 2D sprites?

**Comment by insomniacUNDERSCORElemon** [comment] 2018-07-02 09:45
Polygon2d's AA setting works for me, and with some help from another user (see [this reddit thread](https://www.reddit.com/r/godot/comments/8v90z9), I offered a test project and so did they) here are my findings:

- in certain cases, AA works on nVidia hardware (with proprietary drivers at least)
- if HDR is enabled (as it is by default), framebuffer needs to be set to 2D for AA
- AA does NOT work with the HTML export (in Firefox... Chrome/Chromium does not play the export at all)

The other user has said polygon2d AA does not work when using an Intel iGPU (they confirmed my findings with nVidia GPUs) but I cannot confirm that. Additionally, AMD GPUs+APUs (including Intel w/Vega M) will need to be tested (especially newer stuff) as well as Android/Mac/iOS.

**Comment by reduz** [comment] 2018-09-06 12:17
This is difficult to do in GLES3, so will implement in GLES2 and Vulkan in 3.2, kicking there

**Comment by insomniacUNDERSCORElemon** [comment] 2018-12-30 22:51
It seems that all of the existing previous implementation of this (HDR off, polygon2d only) is broken (AA just doesn't show up at all on 2D polygons) in 3.1 alpha 4. Even with GLES2 (and the new partial transparency options if those happen to be even slightly related). At least for me w/nvidia.

Fonts use AA just fine so it IS working... but then again it doesn't seem possible to turn that OFF either (yes, with a ttf font... and yeah likely unrelated).

**Comment by Calinou** [comment] 2018-12-30 23:55
> Fonts use AA just fine so it IS working... but then again it doesn't seem possible to turn that OFF either (yes, with a ttf font... and yeah likely unrelated).

Fonts are rasterized by FreeType, they are not seen as polygons by Godot (in other words, they're just textures).

Also, it's possible to [disable antialiasing in DynamicFonts](https://github.com/godotengine/godot/pull/23645) since recently :slightly_smiling_face:

**Comment by insomniacUNDERSCORElemon** [comment] 2019-01-01 16:36
@Calinou ok, I guess it's unrelated then. But I was referring to in-game (at least with a dynamic font on a button) and anti-aliasing still being present when the checkbox in the font settings is unchecked.

So is 2D AA intentionally broken in alpha 4 (as reduz hinted at above)? If it can be fixed for 3.1 w/GLES2, maybe karroffel can weigh in? Or is this is pushed back until it can be done in one effort for the GLES2 _and_ Vulkan renderers?

**Comment by pgruenbacher** [comment] 2019-03-02 23:27
commenting cause this I think this will help with polygon2d holes in zylann's heightmap mask when it's eventually realized.
https://github.com/Zylann/godot_heightmap_plugin

**Comment by fab918** [comment] 2019-11-25 10:50
Is-there something plans on this for 4.0/Vulkan (or a workaround in 3.2)? I'm faced the same issue, a non-pixel art game (using high res sprites) with ugly pixel edge.

(@Qws have you find a workaround?)

**Comment by Calinou** [comment] 2019-11-25 13:17
@fab918 Depending your needs, you could use a Line2D node with a pre-made texture whose top and bottom edges are transparent, like the one below (streteched to 256×16 for demonstration purposes):

![image](https://user-images.githubusercontent.com/180032/69543615-44aa3700-0f8e-11ea-85f2-1d2ceb97c0dc.png)

**Comment by fab918** [comment] 2019-11-25 14:20
@Calinou Thanks for your answer, maybe I misunderstood the topic of the thread (sorry if it's the case).

I don't use Polygon2D, I just want to apply the anti-aliasing filter in the 2D viewport because I have sprites with "staircase effect" (which I don't have in my photo editor, [see here](https://ibb.co/NVFgzxz)).

I tried to increase the resolution of sprites (and tried import presets) but that not solve the issue, I assumed that could be the 2D antialiasing.

**Comment by akien-mga** [comment] 2019-11-26 13:09
@fab918 Seems like your texture was imported with `Filter` disabled, as @Calinou mentioned. That's not related to anti-aliasing.

**Comment by akien-mga** [comment] 2019-11-26 13:09
Duplicate of #10241.

**Comment by starry-abyss** [comment] 2019-11-26 23:44
No, the other issue is only about lines and polygons. Take "screen-space shaders" example, rotate the picture, and there is aliasing at edges:

![aa_broken_2d_godot](https://user-images.githubusercontent.com/11571820/69681590-96061380-10bf-11ea-8b59-593aa61275c8.jpg)

**Comment by Calinou** [comment] 2020-05-27 07:34
Note that this feature is planned in some way for Godot 4.0.

___

Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!

**Closed by Calinou** 2020-05-27 07:34 UTC
Labels: feature proposal, topic:rendering

**Comment by nathanfranke** [comment] 2020-08-03 01:46
Superseded by https://github.com/godotengine/godot-proposals/issues/1297
