### ISSUE TITLE
Hex demo tiles are offsets

### ISSUE THREAD

**Issue by vsiles** [godotengine/godot#21213] opened 2018-08-20 07:30 UTC
**Godot version:**

from github: faa49c182978b3fe74e7aad65fb761c2881f009c

**OS/device including version:**

linux/ubuntu

**Issue description:**

As discussed [here](https://github.com/godotengine/godot-demo-projects/issues/248) and [here](https://godotengine.org/qa/31715/detect-tile-under-mouse-cursor?show=31791#c31791), when dealing with hexagonal tiles in godot, there seems to have two main issues:
- the underlying grid is still based on square/rectangle, so `get_cell` is buggy, and when adding tiles to a tilemap, the tile is located at some offset on the lower right part of the actual tile.

**Steps to reproduce:**
Select the tilemap in the [hexmap demo](https://github.com/godotengine/godot-demo-projects/tree/master/2d/hexagonal_map) and try to add more tiles, the tile will be displayed at some offset of the current tile grid cell.

**Minimal reproduction project:**

Witnessed on the official site release and recent github compilation

**Comment by OvermindDL1** [comment] 2018-08-20 15:01
I though I was going crazy, I couldn't figure out what was happening there with the offsets, glad I was just not doing something wrong.  But yes, I confirm the same issue.

**Comment by reduz** [comment] 2018-09-07 22:41
After 3.1 is out, I advocate for a simplification of TileMap, given how unnecesarily complex it got.

**Comment by Zireael07** [comment] 2018-09-09 12:08
Is this a reoccurrence of #4206?

**Comment by MarianoGnu** [comment] 2018-09-09 14:05
For 3.2/4.0 it could even be worth having sepparate nodes and resources for hexagonal and isometric tiles, even if it's possible to have them all toghether like now, having them splitten up would much more straightforward for a final user imho, and since you will never have topdown+isometric+hexagonal tiles on the same tileset anyway there's no need for this anyway

**Comment by Mochnant** [comment] 2018-11-07 17:01
I'd like to see improved hexagon support, as well.  Unity supports both square and hexagon tilemaps, so perhaps that could provide guidance.

**Comment by akien-mga** [comment] 2019-01-23 14:11
Is this still reproducible in the current master branch?

**Comment by ThisIsNoZaku** [comment] 2019-02-17 22:53
@akien-mga I downloaded 3.0.6 last week and am seeing this issue.

**Comment by CurlyBraceTT** [comment] 2019-04-07 10:31
The only *workaround* I have found is custom hex grid implementations
https://github.com/romlok/godot-gdhexgrid
Also even custom module (Not sure if its compatible with 3.1)
https://github.com/cefleet/HexModule

**Comment by StStep** [comment] 2019-07-30 01:52
Couldn't this be solved by having a custom offset for the 'Tile Origin' style property for the TileSet node?
Hex sprites have unusable space on the top left corner; setting 'Tile Origin' to center, you can see the offset clearly. Wouldn't a centered 'Tile Origin' with (-64, -64) offset (since demo pngs are 128x128px) perfectly center it for the sprites in the demo?

**Comment by akien-mga** [comment] 2020-01-08 08:44
Fixed by #30231, you should enable "Centered Textures" on the TileMap.

**Closed by akien-mga** 2020-01-08 08:44 UTC
Labels: bug, topic:core
