### ISSUE TITLE
Show C# syntax in docs

### ISSUE THREAD

**Issue by TZubiri** [godotengine/godot#36204] opened 2020-02-14 03:00 UTC
**Godot version:** 3.2

**Issue description:**

The methods TileMap.Clear and TileMap.SetCell are defined in the documentation as clear and set_cell

https://docs.godotengine.org/en/3.2/classes/class_tilemap.html

**Comment by YeldhamDev** [comment] 2020-02-14 03:12
The documentation uses GDScript's snake_case syntax.

**Comment by TZubiri** [comment] 2020-02-14 03:14
Perhaps I forgot  to mention I am using C#, this syntax does not correspond to the actual method names in C#

**Comment by Calinou** [comment] 2020-02-14 08:18
I'm not sure if we can do anything about the online documentation. As for the editor help, this could be still misleading as inline code examples will always use GDScript.

**Comment by TZubiri** [comment] 2020-02-14 09:55
Changing casing to comply with language conventions was a very bad idea. Can godot catch errors for undefined methods and try to suggest the appropriate casing?

**Comment by TZubiri** [comment] 2020-02-17 00:34
> Changing casing to comply with language conventions was a very bad idea. Can godot catch errors for undefined methods and try to suggest the appropriate casing?

There's a precedent for this aliasing behaviour.

using the function name _ready instead of _Ready works fine, but emits the following warning:

` modules/mono/mono_gd/gd_mono_class.cpp:189 - Method 'void _ready()' should be 'void _Ready()'. In class '.MapGenerator'.`

**Comment by Calinou** [comment] 2020-04-17 20:08
Duplicate of #19655.

**Closed by Calinou** 2020-04-17 20:08 UTC
Labels: documentation, enhancement, topic:editor, topic:mono
