### ISSUE TITLE
Input Map Actions unfold upon adding a new Action. (In the Project Settings)

### ISSUE THREAD

**Issue by expat1999** [godotengine/godot#18212] opened 2018-04-15 08:24 UTC
**Godot version:**

- 3.0.2 (Windows 64-bit Mono)

**Issue description:**

- This isn't a very major issue, but when you go to the Input Map and collapse all the actions, then add a new action, all of the other actions unfold...  since all of the default actions are at the top of the list, it gets a little annoying.  I wonder if there should be a different category under the Input Map for the default actions.  But at the very least they should stay collapsed, seeing as that just makes sense.

**Steps to reproduce:**

1. Create a new project (or presumably open any project).
2. Navigate to the Input Map in Project Settings.
3. Collapse all or some of the Actions in the list.
4. Add a new action to the list.
5. Notice how all other actions unfold.

**Comment by vnen** [comment] 2018-04-17 04:10
Duplicate of #8728

**Closed by vnen** 2018-04-17 04:10 UTC
