### ISSUE TITLE
Request: Code window and game editor window side by side

### ISSUE THREAD

**Issue by Norrox** [godotengine/godot#23500] opened 2018-11-04 12:14 UTC
Code window and game editor window side by side, would been nice to have it when your using a 4k ultrawide monitor. i have been trying external code editors from time to time but i prefer godots built in one.

example on how it can look.
![974a720d96d897685e09c138ef8377e2](https://user-images.githubusercontent.com/13393087/47963967-97d3e380-e033-11e8-8920-ca63af2ed4d8.png)

**Comment by bojidar-bg** [comment] 2018-11-04 12:45
Duplicate of #9059 and/or #8250?

**Comment by Calinou** [comment] 2018-11-08 13:32
Closing as a duplicate of https://github.com/godotengine/godot/issues/9059.

**Closed by Calinou** 2018-11-08 13:32 UTC
