### ISSUE TITLE
[visual script] After creating variable of type array, often it has fixed type of PoolVector2Array, not respecting type hint selected

### ISSUE THREAD

**Issue by idchlife** [godotengine/godot#48698] opened 2021-05-13 19:58 UTC
**Godot version:**

3.3

**OS/device including version:**

macOS

**Issue description:**

Kind of elusive bug, but it's more common than I thought. My colleague ran into it 4 times already. Can be hard to reproduce.

**Steps to reproduce:**
1) Create variable
2) Choose type array
3) Change size to 1
4) Choose hint String
5) See it's turned into PoolVector2Array
6) See hint is still String but under the hoods it's PoolVector2Array and to fill elements of an array in "edit variable" window you need to provide x and y as in Vector2 and not String values

**Minimal reproduction project:**

[poolvector2arrayrepro.zip](https://github.com/godotengine/godot/files/6474773/poolvector2arrayrepro.zip)

**Comment by akien-mga** [comment] 2021-05-13 20:34
I can confirm the bug, it's caused by #45096 which is a backport of #44918 but in the wrong section, it should be for `type` and not `hint`. I'll fix it.

**Comment by akien-mga** [comment] 2021-05-13 21:02
Fixed by #48702.

**Closed by akien-mga** 2021-05-13 21:02 UTC
Labels: bug, confirmed, regression, topic:visualscript
