### ISSUE TITLE
Uncropped Viewport node in 2D editor overlaps editor UI

### ISSUE THREAD

**Issue by RandomShaper** [godotengine/godot#4975] opened 2016-06-01 12:25 UTC
Godot v. 2.0.3 stable, Win x64

**What happened:**
In a simple setup like the one the figure shows (2D: `Control` -> `Viewport` -> Instanced 3D `Scene`) the root `Control` (and thus the `Viewport`) can be dragged as to overlap some of the editor UI elements.

![bug](https://cloud.githubusercontent.com/assets/11797174/15709212/ccc8c488-2803-11e6-9035-653816135175.png)

**Steps to reproduce:**
Create a scene like the one in the figure or the attached files and drag the root `Control` outside the visible area.

**Link to minimal example project**
[A sample project which shows the bug.](https://drive.google.com/file/d/0B-WnZEtQk02PSlFzQnAzdTlyNXM/view?usp=sharing)

_By the way, GitHub has rejected to upload the same .zip file to this post. I think it would be better to embed the test project than linking to it. Strange enough, it tells me to "Try agagin with a PNG, GIF, [..], or ZIP." (!)_

**Comment by neikeq** [comment] 2016-06-03 15:14
Duplicate of #1840

**Closed** 2016-06-03 15:15 UTC
