### ISSUE TITLE
Godot crashes opening a PluginScript on the inspector

### ISSUE THREAD

**Issue by vetu11** [godotengine/godot#35861] opened 2020-02-02 22:31 UTC
**Godot version:**
Godot3.2-stable

**OS/device including version:**
Debian 10

**Issue description:**
Godot crashes when trying to see the details of a PluginScript in the inspector.

**Steps to reproduce:**
Create a MeshInstance with an ArrayMesh. Edit the ArrayMesh in the inspector and add a PluginScrip to it. Click the PluginScript (or right click and press edit). Godot crashes.
![Inspector](https://user-images.githubusercontent.com/26150190/73616399-1a6e9880-4613-11ea-84b6-54d2d4007755.png)

**Minimal reproduction project:**
[PluginScriptCrash.zip](https://github.com/godotengine/godot/files/4145575/PluginScriptCrash.zip)

**Comment by timothyqiu** [comment] 2020-02-03 04:42
I think this is a duplicate of #31769

**Comment by akien-mga** [comment] 2020-02-06 09:20
Duplicate of #31769

**Closed by akien-mga** 2020-02-06 09:20 UTC
Labels: bug, crash, topic:editor, topic:plugin
