### ISSUE TITLE
Wrong Rigidbody collision behaviour (3.0.3 rc1)

### ISSUE THREAD

**Issue by ProbDenis** [godotengine/godot#18812] opened 2018-05-12 13:15 UTC
**Godot version:**
3.0.3 rc1

**OS/device including version:**
Various Windows versions - the bug doesn't happen on Linux.

**Issue description:**
3.0.3 rc1 on Windows breaks the Rigibody collisions in my game. Instead of bouncing off a StaticBody, they "slide" along them, sometimes disappearing in or passing through other bodies:

![rigidbodies](https://user-images.githubusercontent.com/15891496/39957652-b30b9c64-55f6-11e8-8e56-16ed7d8cec00.gif)

This never happened in 3.0.2. And probably the weirdest thing: The issues seems to be Windows-specific, because it works just fine on Linux (same Godot version, same PC)

**Comment by QbieShay** [comment] 2018-05-12 14:04
@AndreaCatania

**Comment by hpvb** [comment] 2018-05-13 21:34
Does this happen with the 32bit Windows build?

**Comment by ProbDenis** [comment] 2018-05-14 08:41
I've just checked, and it doesn't happen. The issue is limited to the 64 bit Windows build.

**Comment by hpvb** [comment] 2018-05-14 21:18
3.0.3-rc2 is out. Could you please try with this release? I can't reproduce it here on wine with this build nor on Windows with mesa software renderer.

**Comment by ProbDenis** [comment] 2018-05-14 22:31
I did a quick test with Wine and I'm getting the same with rc2. The 32 bit version is fine, but the 64 bit Windows build has this strange bug.

**Comment by hpvb** [comment] 2018-05-15 01:03
This is indeed very strange. I can't reproduce it at all. This is a video of the 32bit and 64bit windows versions on wine and the native 64bit linux version:

![bugs](https://user-images.githubusercontent.com/2591099/40030710-6fe0606c-57ec-11e8-8891-6f7e6d9ef3ff.gif)

Could this be some Nvidia driver issue perhaps?

**Comment by hpvb** [comment] 2018-05-15 01:26
I have one more idea, could you please try this binary? https://tmm.cx/nextcloud/s/SgT2ymq2NqYCw6J/download?path=%2F&files=Godot_v3.0.3-rc2_win64.exe.zip

**Comment by hpvb** [comment] 2018-05-15 01:39
I was able to reproduce it actually, I must have done something wrong previously. Here you see the bug with the released binary but not with the above binary:

![win10-bug](https://user-images.githubusercontent.com/2591099/40031776-723f5354-57f1-11e8-837f-58f5f430f76a.gif)

This means the problem is caused by the Microsoft compiler in LTO mode. For 3.0.3 I'll disable LTO for the Windows builds again and do a proper benchmark between a non-LTO MSVC build vs an LTO Ming-w64 build for 3.0.4.

Can you please verify that with the above binary the problem is gone for you also?

**Comment by ProbDenis** [comment] 2018-05-15 07:40
Yes, I can confirm that the non-LTO build works fine.

**Comment by AndreaCatania** [comment] 2018-05-15 09:34
I've tried it in a LTO build with windows 64 and it works fine.
@ProbDenis Can you please send me the command that are you using to build it? (The one where you have the error)
Thanks you

**Comment by ProbDenis** [comment] 2018-05-15 12:50
I haven't built it. We got the bug with the official 3.0.3 builds (rc1 and rc2).

**Comment by hpvb** [comment] 2018-05-16 00:17
@AndreaCatania 
```
call "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Auxiliary\Build\vcvarsall.bat" amd64 10.0.16299.0
call scons -j8 verbose=no warnings=no progress=no platform=windows builtin_libpng=yes builtin_openssl=yes builtin_zlib=yes gdnative_wrapper=yes debug_symbols=no tools=yes target=release_debug use_lto=yes
```

**Comment by hpvb** [comment] 2018-06-13 10:08
Fixed by switching to mingw + lto on 3.0 at least.

**Comment by AndreaCatania** [comment] 2018-08-26 07:29
What's the state of this issue?

**Comment by hpvb** [comment] 2018-08-27 00:35
Switching to mingw seems to have fixed the issue. We need to go this anyway for the mono builds. I'm closing this.

**Closed by hpvb** 2018-08-27 00:35 UTC
Labels: bug, platform:windows, topic:physics
