### ISSUE TITLE
Export Variable Lost After Using PackedScene.Pack to Save Node and Reinstantiate

### ISSUE THREAD

**Issue by L2750558108** [godotengine/godot#75816] opened 2023-04-08 10:15 UTC
### Godot version

4.0.1

### System information

windows10

### Issue description

See "Step to Reduce"

### Steps to reproduce

1.Prepare these file
Test.cs
using Godot;
using System;

class Test : Node
{
 [Export]public Node test = null;
 int count = 100;
 public override void _Process(double delta)
 {
  if(test != null)
  {
   GD.Print(test.GetPath());
  }
  else
  {
   GD.Print("NULL");
  }
  if(count <= 0)
  {
   Test1();
  }
  count--;

 }
 public void Test1()
 {
  var temp = new PackedScene();
  temp.Pack(this);
  GetNode("/root").AddChild(temp.Instantiate());
  QueueFree();
 }
}

test.tscn
testScene <- Test.cs
testScene/testNode

And assign the "testScene/testNode" node to the exported property "test" of the "testScene"

It can be seen that the "TestScene" node will always output the path of the node referenced by the "test" property and the function "Test1" will be called after 100 frames.This function will packed the node, free it and reinstantiate it

2.Run from test.tscn
3.The output will be "/root/testScene/testNode" at first
4.After 100 times, the output will be NULL. It show the value of the export property "test" is lost

### Minimal reproduction project

[新建游戏项目.zip](https://github.com/godotengine/godot/files/11182979/default.zip)

**Comment by KoBeWi** [comment] 2023-04-08 10:23
Duplicate of #73315

**Closed by KoBeWi** 2023-04-08 10:23 UTC
