### ISSUE TITLE
Extra Cull Margin triggers worst LOD

### ISSUE THREAD

**Issue by lyuma** [godotengine/godot#67890] opened 2022-10-26 01:15 UTC
### Godot version

4.0.beta3 (not in 4.0.beta2)

**Unlike #67772, this is not a double-precision build**

### System information

Windows 10, Nvidia

### Issue description

Since 4.0 beta3, using high values for Extra Cull Margin will cause the LODs to break. This bug was not present on 4.0 beta2

Screenshot of Extra Cull Margin=16384 on beta3
![broken LODs](https://user-images.githubusercontent.com/39946030/197911500-9c2560e3-96cc-48fb-a0f1-c722b729ae0b.png)

Screenshot on beta2:
![good LODs](https://user-images.githubusercontent.com/39946030/197911569-e3ea5710-2ecb-436c-b0a3-900c6173333e.png)

CC @Zylann Unrelated to previous bug with import and double precision builds. This is not affected by importer, and the same binary scene will look different on beta2 and beta3; or depending on extra cull margin.

CC @TechnoPorg the regression *may* be your PR #67307 - I haven't done a full bisect yet but it is between beta2 and beta3

### Steps to reproduce

1. Open the attached project.
2. Check if the mesh looks broken (LODs)
3. Set Extra Cull Margin to 0, and then 16384, on the Body mesh to see how it affects rendering.

### Minimal reproduction project

[ExtraCullLODTest.zip](https://github.com/godotengine/godot/files/9865119/ExtraCullLODTest.zip)

**Comment by lyuma** [comment] 2022-10-26 01:26
Possibly also some relation to #67479
it's curious that both rendering issues related to LODs showed up in beta3

**Comment by clayjohn** [comment] 2022-10-26 18:28
Indeed this is caused by https://github.com/godotengine/godot/pull/67307 Distance is now calculated as an absolute value rather than a directional value so the LODing code fails to detect when the camera is inside the AABB and instead gives an LOD distance for how far to the edge of the AABB. 

It seems though that the "correct" behaviour may not be much better for your use-case. The "correct" behaviour would means that your model would never use any LOD except for the highest resolution as the camera will always be inside the model's AABB.

**Comment by fire** [comment] 2022-10-26 18:44
@clayjohn Perhaps a boolean for lod disable would be the "expected" option.

**Comment by TechnoPorg** [comment] 2022-10-29 15:48
Should LOD calculations factor in Extra Cull Margin? I don't think it affects the visible level of detail, so maybe only the base mesh AABB could be used.
That still doesn't solve the issue of when the camera is in the AABB, though

**Comment by Calinou** [comment] 2022-10-29 19:50
> Should LOD calculations factor in Extra Cull Margin? 

I'd say Extra Cull Margin shouldn't affect LOD. Extra Cull Margin is typically only used to workaround rendering issues with objects being culled too early, so it shouldn't change how things look in practice.

**Comment by lyuma** [comment] 2023-05-17 21:49
This LOD bug can also be triggered by setting a large `w`, `h` and `d` in the mesh renderer Custom AABB box.
![large custom AABB bug](https://github.com/godotengine/godot/assets/39946030/b550137d-a070-42e6-acf4-8f8bb4c2ad9d)

Reproduction steps:
1. Use reproduction project from #76892 ( https://github.com/godotengine/godot/files/11437148/BoneMap_non_skinned.zip )
2. Enable editable children on the _rotated or _original versions
3. Find Body mesh
4. Set Custom AABB to have x=0,y=0,z=0 and w=1000,h=1000,d=1000
5. The model will get a distorted LOD as in the above screenshot.

Any reason not to check for `inst->transformed_aabb.has_point(p_render_data->scene_data->cam_transform.origin)` ? that seems like a pretty safe fix for now

**Comment by lyuma** [comment] 2023-05-22 17:21
This bug has multiple causes so it is not fuly fixed yet. It seems to depend on the camera direction but being inside a mesh with large AABB (either using extra cull margin or using custom AABB or simply having a huge mesh) godot still seeems to use thewromg lod. Using a non equal size helps repro, like 100,100,5

**Comment by briansemrau** [comment] 2023-07-07 16:16
The distance LOD selection appears to be much better with this change. Not sure it's 100% correct and I haven't tested it much.

```diff --git a/servers/rendering/renderer_rd/forward_clustered/render_forward_clustered.cpp b/servers/rendering/renderer_rd/forward_clustered/render_forward_clustered.cpp
index 069b43203f..38b803d67c 100644
--- a/servers/rendering/renderer_rd/forward_clustered/render_forward_clustered.cpp
+++ b/servers/rendering/renderer_rd/forward_clustered/render_forward_clustered.cpp
@@ -944,23 +944,14 @@ void RenderForwardClustered::_fill_render_list(RenderListType p_render_list, con
                        // LOD

                        if (p_render_data->scene_data->screen_mesh_lod_threshold > 0.0 && mesh_storage->mesh_surface_has_lod(surf->surface)) {
-                               // Get the LOD support points on the mesh AABB.
-                               Vector3 lod_support_min = inst->transformed_aabb.get_support(p_render_data->scene_data->cam_transform.basis.get_column(Vector3::AXIS_Z));
-                               Vector3 lod_support_max = inst->transformed_aabb.get_support(-p_render_data->scene_data->cam_transform.basis.get_column(Vector3::AXIS_Z));
+                               Vector3 forward = p_render_data->scene_data->cam_transform.basis.get_column(Vector3::AXIS_Z);
+                               Vector3 center = inst->transformed_aabb.get_center();
+                               Vector3 support = inst->transformed_aabb.get_support(-forward);
+                               real_t radius = (support - center).length();
+                               float distance = p_render_data->scene_data->cam_transform.origin.distance_to(center) - radius;

-                               // Get the distances to those points on the AABB from the camera origin.
-                               float distance_min = (float)p_render_data->scene_data->cam_transform.origin.distance_to(lod_support_min);
-                               float distance_max = (float)p_render_data->scene_data->cam_transform.origin.distance_to(lod_support_max);
-
-                               float distance = 0.0;
-
-                               if (distance_min * distance_max < 0.0) {
-                                       //crossing plane
+                               if (distance < 0.0) {
                                        distance = 0.0;
-                               } else if (distance_min >= 0.0) {
-                                       distance = distance_min;
-                               } else if (distance_max <= 0.0) {
-                                       distance = -distance_max;
                                }

                                if (p_render_data->scene_data->cam_orthogonal) {
```

anyone feel free to PR it if I don't find the time

**Comment by fire** [comment] 2023-07-08 07:14
I tested @briansemrau 's test on the original model and it seem to in error. Looking into it.

**Comment by lyuma** [comment] 2023-07-08 08:36
@briansemrau Would it be possible to explain a little intuition of how your proposed changes work?

Another thing. Fire was asking me a question. Do we want:
1. if inside aabb pick the best quality
2. scale quality by aabb origin

Intuitively speaking, I can't think of a reason why a mesh would ever use any LOD other than best quality, if within the AABB. but perhaps we could assert this and ignore the AABB. If the logic of meshopt is correct, it should never choose a lower quality within the AABB, because you may be staring at one specific polygon in the mesh.

Without doing a per-polygon check, there's no way to to know if you are looking at an important polygon, so no matter what logic is used, it must never use a lower quality if within the AABB

**Comment by briansemrau** [comment] 2023-07-08 16:07
The previous code (and the version before) seemed to be checking multiple aabb supports, which intuitively doesn't make much sense to me. We want the signed distance to the AABB surface, and I'm not sure what the intent of the current code is.

I simplified that logic so that the distance to the AABB is measured by the distance to the origin, minus the "radius" of the AABB towards the camera.
By calculating this way, when the camera is inside the AABB the distance is negative, showing the highest quality mesh.

My use case for this is to show a multimesh spanning a large area. It makes no sense for a tree to suddenly look lower quality while you're walking right by one just because you're in the AABB. Once inside the AABB we can't make any assumptions about the model because it's just an approximation.

**Comment by fire** [comment] 2023-07-08 19:32
I'll post the text test cashes:

## Grass multimesh
Use case is one grass multi mesh that covers the entire map. Being in the AABB should not fail

## Culling extent to the maxmium extent

1. Current case is picks the most decimate lod
2. Proposals here say once the camera is inside of the AABB it should pick the LOD with the most indices
3. My proposal is to avoid disabling lods on avatar globally. The rendering system will still attempt to lod the avatar and not pick the highest index count lod.

## Conclusions

We have a test case for avatars culling extent to the maxmium extent. @briansemrau can you provide a grass multi-mesh test case?

**Comment by YuriSizov** [comment] 2023-07-24 17:50
Fixed by https://github.com/godotengine/godot/pull/79590.

**Closed by YuriSizov** 2023-07-24 17:50 UTC
Labels: bug, topic:rendering, confirmed, topic:3d
