### ISSUE TITLE
"WorldEnvironment is Ignored" warning

### ISSUE THREAD

**Issue by TailyFair** [godotengine/godot#18724] opened 2018-05-08 21:00 UTC
**Godot version:**
a79f4ac382686ec1e10484d4cf2351090d28ce2f

**OS/device including version:**
Windows 10 x64

**Issue description:**
![image](https://user-images.githubusercontent.com/27275873/39782600-4838ab30-531b-11e8-82d7-3b1ad2fa315e.png)

I'm not quite sure why `WorldEnvironment` is ignored, since scene obviously has `Camera` added.
Might be related to 29d305599dcb095e6586ebecf6e595f85d2cfcaf.

If indeed `WorldEnvironment` is ignored, maybe warning should be more specific.

If I'm using Environment mode incorrectly, I would appreciate guidance.

------
For 2D scene, setting Environment's background to `Canvas`, warning icon persist, but doesn't prompt warning pop-up when clicked.

**Steps to reproduce:**
Create new project
Add WorldEnvironment and Camera to Root node.

**Minimal reproduction project:**

**Comment by akien-mga** [comment] 2018-05-08 21:25
CC @poke1024.

**Comment by capnm** [comment] 2018-05-08 22:03
Duplicate of #17943

**Closed** 2018-05-09 06:15 UTC
Labels: bug, confirmed, topic:editor
