### ISSUE TITLE
GPU Particles not rendered on iOS when using GLES3

### ISSUE THREAD

**Issue by Tobi-La** [godotengine/godot#35849] opened 2020-02-02 12:16 UTC
**Godot version:**
3.2 stable
**OS/device including version:**
iPhone 6s , iOS 13.3.1
**Issue description:**
Particle nodes are not rendered GLES 3 at all. CPUParticles work, but they have a very very high battery consumption (my battery lasts only 10 minutes rendering them), so I really need the gpu particles.

This is how it should look like (windows):
![windowsGLES3](https://user-images.githubusercontent.com/25849067/73608025-ff256e00-45bd-11ea-8deb-f3de26716378.PNG)

And this how it looks on iOS:
![iOSGLES3](https://user-images.githubusercontent.com/25849067/73608030-06e51280-45be-11ea-87d5-0eea72818b8c.PNG)

**Steps to reproduce:**
Create a scene with a particle node in it
**Minimal reproduction project:**
[ParticleIOS.zip](https://github.com/godotengine/godot/files/4144133/ParticleIOS.zip)

**Comment by mrjustaguy** [comment] 2020-02-02 13:36
Too old a GPU on iOS, that's the issue, they changed sth from 3.1 to 3.2 that some older GPUs no longer render particles properly, had the issue on my PC back when i had an antique GPU in, replaced it with a tad more modern GPU and worked just fine.

**Comment by Calinou** [comment] 2020-02-02 17:32
We don't support using the GLES3 renderer on mobile anymore; please use GLES2 instead. This means you can't use GPU particles anymore, so I guess you'll have to find another way to make your game look pretty :slightly_smiling_face:

**Comment by aaronfranke** [comment] 2020-02-02 22:59
@Calinou Shouldn't there be a warning about this in the engine, then?

**Comment by zxcvdev** [comment] 2020-02-05 17:07
I get the GPU Particles to work on iOS with GLES3 (using Godot 3.2 stable) by setting the `Disable Z` flag. Seems to be the same problem as #35492 .

**Comment by clayjohn** [comment] 2020-02-05 17:30
@Tobi-La Can you confirm @zxcvdev's workaround? If so, I will close this in favour of #35492.

**Comment by akien-mga** [comment] 2020-02-06 10:39
Closing as duplicate of #35492 (please comment if setting `Disable Z` actually doesn't solve the issue for you and we'll reopen).

**Closed by akien-mga** 2020-02-06 10:39 UTC
Labels: bug, platform:ios, topic:rendering

**Comment by Tobi-La** [comment] 2020-02-06 15:02
@akien-mga  @clayjohn This workaround sadly doesn't work for me, as I am using emission points and now they all get alligned on the z-axis instead using the z value of my points

**Comment by clayjohn** [comment] 2020-02-06 15:04
@Tobi-La

But the particles appear right? Which means you are experiencing the same bug as in #35492

**Comment by Tekuzo** [comment] 2022-05-18 19:33
@clayjohn When I tried to use the Disable-Z Flag it still displays nothing.

**Comment by clayjohn** [comment] 2022-05-18 21:21
@Tekuzo What version of the engine are you using? And do you get any error messages or anything when you run the scene?

**Comment by Tekuzo** [comment] 2022-05-18 22:00
3.4.4 and no errors

**Comment by ZenRepublic** [comment] 2025-01-02 11:09
iOS particles not showing up using godot 4.3 in compatibility mode webgl

pc works, android works
