### ISSUE TITLE
GLES2 huge wait time and error (Directional shadow framebuffer status invalid)

### ISSUE THREAD

**Issue by OlexiyKravchuk** [godotengine/godot#27584] opened 2019-04-01 23:32 UTC
**Godot version:**
Godot_v3.1-stable_win64.exe

**OS/device including version:**
ОС: Windows 7 x64 
Radeon HD 3650

**Issue description:**
When creating and running a new empty project in the editor, even if there is not a single scene with nodes, an error occurs - (Directional shadow framebuffer status invalid), and in order for it to simply open in the editor, you need to wait 30 seconds in GLES2 mode , after that, all editors work acceptable.
But when I start working with the project and debugging scripts, then each time the project is launched for debugging, this wait is repeated again and again, together with an error (Directional shadow framebuffer status invalid).
P.S. Even the operating system runs faster than the empty project in Godot 3.1stable in GLES2 mode, while in version 2.1.5stable even the heaviest project was launched in just 6 seconds.

![image](https://user-images.githubusercontent.com/10380658/55365819-a3e2a500-54ee-11e9-871f-6a60f0b91449.png)

**Comment by Calinou** [comment] 2019-04-03 09:28
Duplicate of https://github.com/godotengine/godot/issues/27572 (which has more information). It might not be possible to fix this (and the long startup times) on such old graphics drivers, which haven't been maintained by AMD for a long time now.

**Closed by Calinou** 2019-04-03 09:28 UTC

**Comment by OlexiyKravchuk** [comment] 2019-04-03 14:20
No, this is another case, because the project manager initially runs from GLES3 and starts a few seconds, and the projects themselves open GLES2 for a very long time, I believe that there is another problem inside, pay attention to the different * .cpp files that are caused in these processes.
