### ISSUE TITLE
GDScript: Cannot use the `class_name` to call `new()` in the same file

### ISSUE THREAD

**Issue by lmbarros** [godotengine/godot#38947] opened 2020-05-22 01:52 UTC
**Godot version:** 3.2.1

**OS/device including version:** Linux

**Issue description:** If I define a `class_name`, I cannot use this name to instantiate the class from within the class from itself: fails with `Identifier not found: Foo`.

**Steps to reproduce:** Please see below.

**Minimal reproduction project:**
I have this "driver" code that I run using a headless build with `godot-headless --script main.gd`:

```gdscript
# main.gd
extends SceneTree

var Foo = preload("res://foo.gd")

func _init():
    var f = Foo.make_a_foo()
    quit()
```

And here's `foo.gd`, where the problem happens:

```gdscript
# foo.gd
extends Reference
class_name Foo

static func make_a_foo() -> Foo: # <--- no problem here
    return Foo.new() # <--- error here
```

When I run this project I get this error: `SCRIPT ERROR: GDScript::reload: Compile Error: Identifier not found: Foo`.

**Comment by aaronfranke** [comment] 2020-05-22 04:26
Duplicate of #21461.

**Closed by aaronfranke** 2020-05-22 04:26 UTC
