### ISSUE TITLE
Regression in 3d custom shaders not showing

### ISSUE THREAD

**Issue by lawnjelly** [godotengine/godot#42764] opened 2020-10-13 11:13 UTC
**Godot version:**
3.2 current branch 0a2a93b (13 oct 2020)
(It works in 3.2.3 stable, so has been introduced since then)

**OS/device including version:**
Linux Mint 18.3
GLES2 and GLES3

**Issue description:**
Sometime in the last 2 or 3 weeks a regression seems to have come in which is affecting custom shaders. I had been working on 2d so not noticed this. When I attempted to load an old 3d project the other day none of the textures were showing, but when I went back to a previous build they did show. I didn't test it thoroughly.

Today I opened some more 3d projects with custom shaders and again they are either black or showing as plain color, as if the custom shader is not working.

**Steps to reproduce:**
To test this I:
1) created a new project
2) added a MeshInstance
3) made it a box
4) Added a shader material
5) Wrote a basic unshaded shader
6) Assigned a texture

It shows correctly. However, after saving and closing the scene and reloading the project, the custom shader is no longer working. This even happens within the same project. When I created another box in an identical fashion and repeated the steps, the texture shows on the new box but not the old. I suspect after saving it will not show on either:

![Screenshot from 2020-10-13 12-04-05](https://user-images.githubusercontent.com/21999379/95853424-508d1c00-0d4d-11eb-93f1-b29d625b8e0f.png)

I've not pinned down what is causing this yet, I think it is a new regression so should be easy to bisect.

**Minimal reproduction project:**
[Unshaded_regression.zip](https://github.com/godotengine/godot/files/5370949/Unshaded_regression.zip)

**Comment by akien-mga** [comment] 2020-10-13 11:56
No issue in 4040cd350db9be99c46fbe9376367eb2cb58b2fd but I can reproduce in 0a2a93b165fa714e23e93e6d5c95ca37937c8f12, so the most likely culprit is #40313 (@pouleyKetchoupp).

**Comment by lawnjelly** [comment] 2020-10-13 11:58
Yes I can confirm it appears for me in #40313. 

I'll have a look through the PR and see if I can work out what is causing it.

**Comment by akien-mga** [comment] 2020-10-13 12:22
Duplicate of #42675.

**Closed by akien-mga** 2020-10-13 12:22 UTC
Labels: bug, regression, topic:shaders
