### ISSUE TITLE
In the project manager, favorites are not remembered after quitting

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot#5469] opened 2016-06-28 18:12 UTC
**Operating system or device - Godot version:** Arch Linux 64-bit - Git commit https://github.com/godotengine/godot/commit/5065e46381814746eeddb4c44b5eb1540b0331f8, compiled with Clang 3.8.0

**Issue description** (what happened, and what was expected): In the project manager, favorites are not remembered after quitting.

**Steps to reproduce:** Mark one or several projects as favorite in the project manager, open the editor, quit it and restart the project manager. The favorites are gone.

**Comment by djrm** [comment] 2016-06-28 22:02
mm, unable to reproduce on 5065e46381814746eeddb4c44b5eb1540b0331f8
Fedora Linux 64bit with gcc 6.1.1 20160510

**Comment by djrm** [comment] 2016-07-03 23:05
this might be solved as well by 1e095cf39760d0469e7a5a0749b1541a0790cb77

**Comment by vnen** [comment] 2016-07-03 23:29
I'll assume this is fixed. If the bug is still present the issue can be reopened.

**Comment by BraindeadBZH** [comment] 2016-08-14 09:15
I'm on Windows 10 with Godot installed through Steam and I have this issue.
Another way to reproduce is to open Godot, mark some projects as favorite, open a project in Edit mode, Quit to project list and then the favorites are lost.

**Comment by mefihl** [comment] 2016-08-14 09:44
Godot 2.1, Windows 10 issue is not fixeed.

**Comment by bojidar-bg** [comment] 2016-08-14 16:33
Reopening as per @vnen's comment above.

**Comment by volzhs** [comment] 2017-04-03 16:51
I think this is fixed by #6998

**Comment by akien-mga** [comment] 2017-04-03 17:02
Closing. Please comment if you can still reproduce the issue.

**Closed by akien-mga** 2017-04-03 17:02 UTC
Labels: bug, confirmed, topic:editor
