### ISSUE TITLE
Geometry2D.offset_polygon() returns too many points

### ISSUE THREAD

**Issue by ImamuraCross** [godotengine/godot#99070] opened 2024-11-11 13:42 UTC
### Tested versions

-Reproducible in:
- v4.3.stable.mono.official [77dcf97d8]
- v4.3.stable.official [77dcf97d8]
- v4.3.rc1.official [e343dbbcc]
- v4.3.beta3.official [82cedc83c]
- **v4.3.dev6.official [89850d553]**

Not reproducible in:
- v4.3.dev5.official [89f70e98d]
- v4.3.dev4.official [df78c0636]
- v4.3.dev3.official [36e943b6b]
- v4.2.2.stable.official [15073afe3]

### System information

Godot v4.3.stable.mono - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 2060 (NVIDIA; 32.0.15.6603) - AMD Ryzen 7 5800X 8-Core Processor (16 Threads)

### Issue description

Normally, using `Geometry2D.offset_polygon()` w/ `JOIN_ROUND` on, say, a square polygon produces the following; you can see the number of total points is **48**:
![image](https://github.com/user-attachments/assets/d501fabe-0c2a-4ef1-adc0-41eb34dffcc6)

However, as of v4.3.dev6.official [89850d553], it produces the following; a point count of **5316**:
![image](https://github.com/user-attachments/assets/92938de5-d5f7-4bbd-b4fa-c8f16dccbf21)

I am using the same code for both examples:
```gdscript
func _ready() -> void:
	var poly : PackedVector2Array = [Vector2(0, 0), Vector2(500, 0), Vector2(500, 500), Vector2(0, 500)]
	polygon = Geometry2D.offset_polygon(poly, 100, Geometry2D.JOIN_ROUND)[0]
```

----

I assume that before, it had some way of determining the optimal, minimum point count for performance reasons; now, it seems to cram in as many as it can, which certainly looks nice, but has MASSIVELY affected performance in several areas of my project.

I'm unsure if this is a bug, or intentional; I can see in the [changelog](https://godotengine.github.io/godot-interactive-changelog/#4.3-dev6), a mention of, "Add `closest_points_between_segments()` basis path tests for Geometry2D ([GH-48652](https://github.com/godotengine/godot/pull/48652))," but reading the thread, I can't say for sure if its relevant.

If it is intentional, a way to indicate to Godot that I'd like it to decide the optimal, minimum number of points to be used, would be appreciated.
I believe `draw_arc()` has something to that effect, for instance.

### Steps to reproduce

Simply open the MRP; the **Geometry2D.offset_polygon()** script on the Polygon2D node will run automatically in the editor.

### Minimal reproduction project (MRP)

[polygon_test.zip](https://github.com/user-attachments/files/17702981/polygon_test.zip)

**Comment by kleonc** [comment] 2024-11-11 18:34
Duplicate of #97964, already fixed by #98017. Hence closing.

The change was not intentional, it is a regression from #90153. The fix is included in v4.4.dev4.official [36e6207bb], and marked to be cherry-picked into 4.3 (so should be included in the next 4.3.x release as well).

Note that the result for the provided example is slightly different now, in v4.4.dev4.official [36e6207bb] it produces 52 points instead of the previous 48 (basically different results from Clipper2 and Clipper1).

**Closed by kleonc** 2024-11-11 18:34 UTC
