### ISSUE TITLE
RPCs don't work with generic typed arrays

### ISSUE THREAD

**Issue by jonbonazza** [godotengine/godot#87321] opened 2024-01-18 02:40 UTC
### Tested versions

Godot 4.2.1

### System information

Windows 11 Pro - Godot 4.2.1

### Issue description

If you have an rpc method that accepts a generic typed array (e.g. `Array[String]`, The method will work locally, but when called on a remote peer, it will complain that "Array cannot be cast to type Array".

### Steps to reproduce

Open the attached MRP and launch the default scene. Then, inspect the debugger for errors.

### Minimal reproduction project (MRP)

[ArrayTests.zip](https://github.com/godotengine/godot/files/13971456/ArrayTests.zip)

**Comment by dalexeev** [comment] 2024-01-18 05:17
* Duplicate of #69215.
* May be fixed by #78219.
 
Thanks for reporting the bug nonetheless!

**Closed by dalexeev** 2024-01-18 05:17 UTC

**Comment by jonbonazza** [comment] 2024-01-18 05:53
Damn i searched for this too since i figured it should have already been reported. Oh well. Thanks!
