### ISSUE TITLE
Godot 4.2.beta6 just closes with no error or indication of what is wrong when opening some projects

### ISSUE THREAD

**Issue by Damnae** [godotengine/godot#84853] opened 2023-11-13 17:29 UTC
### Godot version

Godot Engine v4.2.beta6.mono.official.64150060f

### System information

Windows 10, amd cpu, vulkan

### Issue description

Even when using -v in console, nothing seems wrong and Godot closes after printing its version number for the second time.
Another project opens fine ~~and then godot freezes trying to upgrade meshes.~~

If there is already a report of this that I missed, consider this one to be more about the lack of indication of what is wrong that the problem of some projects not opening?

### Steps to reproduce

- Open a project
- Something is wrong but you won't know why
- Godot closes
- No error or log to be found

### Minimal reproduction project
[testproject.zip](https://github.com/godotengine/godot/files/13339563/testproject.zip)

**Comment by AThousandShips** [comment] 2023-11-13 17:30
Unfortunately there's not enough information here to help you, please provide a project that this happens with

**Comment by Damnae** [comment] 2023-11-13 17:33
I can't provide my whole project and I have no idea what's wrong with it because godot doesn't seem to provide anything when it crashes. < For me this is the real issue.

**Comment by AThousandShips** [comment] 2023-11-13 17:34
I understand that, but you said it happens on different projects, but not all

You understand we can't do anything unless we know something about what's going wrong?

**Comment by AThousandShips** [comment] 2023-11-13 17:42
Okay, but you're not following

I'm not demanding you prove that something is wrong, the MRP is to help identify *what* is wrong, and if you don't provide anything like that we can't do anything, do you understand how it's impossible to do something if we don't know anything?

**Comment by akien-mga** [comment] 2023-11-13 17:45
Even if you can't provide a reproduction project, there are other tests you could make to help identify what the issue is.

Could you test earlier 4.1.x-stable and 4.2-beta/dev snapshots and let us know which versions work and don't work? Specifically, assuming that your project works in 4.1.3, it would be useful to know what's the first 4.2 build that fails.

If you're able to compile Godot from source, you could also possibly get more information when the engine crashes by connecting it to a debugger (the official builds we provide don't include debug symbols, so a debugger wouldn't give much info).

**Comment by Damnae** [comment] 2023-11-13 17:50
From my point of view what is wrong is that Godot doesn't provide anything when it crashes like this.

I'll check other versions.

**Comment by AThousandShips** [comment] 2023-11-13 17:50
Agreed, that's part of the bug 🙂

**Comment by Damnae** [comment] 2023-11-13 18:02
4.1.3 works. 
None of the 4.2 beta manage to open the project.
dev1 works, dev4 works, dev6 doesn't, dev5 doesn't.

So somewhere between dev4 and dev5.

**Comment by Damnae** [comment] 2023-11-13 18:20
Removing godot-jolt from the project allowed godot 4.2.beta6 to open it.

**Comment by akien-mga** [comment] 2023-11-13 18:33
Thanks for testing, that should be solved in Godot-Jolt already by https://github.com/godot-jolt/godot-jolt/pull/640.

Regarding not getting any information, that's sadly often the case on a crash, as it's by nature unpredictable.
Windows makes it further tricky as it tends not to print error messages in the console unless it's compiled as a console app.

We've been discussing the possibility to add a safe mode that could help debug such issues, so I'll close this as duplicate of https://github.com/godotengine/godot-proposals/issues/2628.

**Closed by akien-mga** 2023-11-13 18:33 UTC
Labels: bug, topic:editor, needs testing, crash

**Comment by Calinou** [comment] 2023-11-13 22:06
> Regarding not getting any information, that's sadly often the case on a crash, as it's by nature unpredictable.
Windows makes it further tricky as it tends not to print error messages in the console unless it's compiled as a console app.

https://github.com/godotengine/godot/pull/61906 addresses this, but it needs several more things to be fully operational:

- https://github.com/godotengine/godot/pull/61006 so that it *could* work with official builds.
- Official builds should have debug symbols available.
- [Crash backtraces that are not useful should warn and tell you to download debug symbols to make the backtrace understandable.](https://github.com/godotengine/godot/pull/55565) We can also provide a tool to reverse existing backtraces that were produced without debug symbols using the debug symbols file.
