### ISSUE TITLE
Make changing game file icon easier

### ISSUE THREAD

**Issue by nikhilCad** [godotengine/godot#26679] opened 2019-03-06 04:32 UTC
**Godot version:**

Godot 3.1 beta 10

**OS/device including version:**

Windows

**Issue description:**

Currently we have to download rcedit to change the file icon. This just seems..well, uncomfortable. I mean every other engine allows to change file icon internally. The only other place I have seen rcedit being used is game frameworks, and well, Godot is not that low level.
Please developers, isn't there a workaround for it? A common user speaking.

**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by girng** [comment] 2019-03-06 04:59
Windows only issue I believe

**Comment by groud** [comment] 2019-03-06 10:24
Related, if not duplicate, to #21347

**Comment by akien-mga** [comment] 2019-03-06 10:48
Duplicate of #21347 indeed.

**Closed by akien-mga** 2019-03-06 10:48 UTC

**Comment by nikhilCad** [comment] 2019-03-06 11:36
Its not a duplicate. I am asking if the icon can be directpy changed im godot, without the (direct) use of rcedit by the user

**Comment by akien-mga** [comment] 2019-03-06 11:38
Well this issue is a duplicate of #21347, or #21347 is a duplicate of this issue. Both relate to simplifying the workflow to edit PE data for Windows binaries, without having to rely on rcedit.

**Comment by nikhilCad** [comment] 2019-03-06 11:39
Okay, you are the boss. Will anyone be working on it?

**Comment by nikhilCad** [comment] 2019-03-06 13:23
I think that's a no.

**Comment by groud** [comment] 2019-03-06 13:28
For now, nobody volunteered to do so, and it's not a priority.
But if you want to give it a try feel free to make a PR.

**Comment by nikhilCad** [comment] 2019-03-06 14:38
No promises though :)
