### ISSUE TITLE
AnimationPlayer transition not fully working with rotations

### ISSUE THREAD

**Issue by TIBI4** [godotengine/godot#27062] opened 2019-03-14 19:43 UTC
**Godot version:**
3.1 stable

**OS/device including version:**
OpenGL ES 2.0 Renderer in a GeForce GTX 960M/PCIe/SSE2

**Issue description:**
- AnimationPlayer is not making transitions when specific rotations are made.
- Not working on imported meshes (as https://github.com/godotengine/godot/issues/19027).
- Not working on not imported MeshInstances done inside Godot.
- The problem appears when this bar is modified.
![image](https://user-images.githubusercontent.com/25259582/54386185-2b1ec480-4677-11e9-866a-8b339d132ba8.png)
_(I don't know what is the **W**, but errors appear with **X**, **Y**, **Z** and **W** modifications)_

**Steps to reproduce:**
- Create a Spatial scene.
- Add a new MeshInstance Node inside it.
- Add an AnimationPlayer Node inside the Spatial scene, and play with it the same way I did in the GIFs.

**Imported Mesh from Blender with BetterCollada for Godot**
![o3aMsgto8x](https://user-images.githubusercontent.com/25259582/54386555-ff500e80-4677-11e9-97a6-00f3cd4420ea.gif)

**Made inside Godot**
![iuafGVCpTU](https://user-images.githubusercontent.com/25259582/54386567-07a84980-4678-11e9-98a3-6b143fbbbf93.gif)

**Modifying W**
![tPns095UlH](https://user-images.githubusercontent.com/25259582/54386572-0aa33a00-4678-11e9-97f1-803f4caccfef.gif)

**Comment by Calinou** [comment] 2019-03-14 20:32
I suppose rotation animation keys use X/Y/Z/W coordinates because they use quaternions, which are better-suited to animations as they are immune to gimbal lock. See [Using 3D transforms](https://docs.godotengine.org/en/latest/tutorials/3d/using_transforms.html) in the documentation.

**Comment by akien-mga** [comment] 2020-06-22 09:54
Can anyone still reproduce this bug in Godot 3.2.1 or any later release (e.g. [3.2.2-rc2](https://godotengine.org/article/release-candidate-godot-3-2-2-rc-2))?

If yes, please ensure that an up-to-date Minimal Reproduction Project (MRP) is included in this report (a MRP is a zipped Godot project with the minimal elements necessary to reliably trigger the bug). You can upload ZIP files in an issue comment with a drag and drop.

**Comment by akien-mga** [comment] 2021-04-28 11:25
No answer, so closing. Please comment if you can still reproduce the issue in Godot 3.3 or later.

**Closed by akien-mga** 2021-04-28 11:25 UTC
Labels: bug, discussion, topic:core
