### ISSUE TITLE
Can't import project in Android Editor

### ISSUE THREAD

**Issue by shahriarlabib000** [godotengine/godot#95011] opened 2024-08-01 08:44 UTC
### Tested versions

- Reproducible in: 4.3.rc1

### System information

Android 11 -Godot 4.3.rc.1

### Issue description

Can't seem to access older existing projects.

### Steps to reproduce

Uninstall your other version of godot app if you have any . Install 4.3.rc1 and give it storage permission as usual. Try importing existing projects

### Minimal reproduction project (MRP)

N/A

**Comment by shahriarlabib000** [comment] 2024-08-01 16:00
So first i have to tap the create new project button then back out and then press import project. It seems to work this way

**Comment by Hilderin** [comment] 2024-08-01 21:33
I think this is a duplicate of #94570

**Closed** 2024-08-01 21:50 UTC
Labels: bug, platform:android, topic:editor, topic:porting, needs testing
