### ISSUE TITLE
Light doesn't look right with floors when looking straight ahead

### ISSUE THREAD

**Issue by YeldhamDev** [godotengine/godot#10188] opened 2017-08-09 00:17 UTC
**Ubuntu 17.04 - Godot version: 3.0.alpha1**

**Issue description:**
When a light has shadows enabled, looking straight ahead, hits a plane mesh facing upwards, it looks really awkward. The bias has to be set really high for it to look decent.

![screenshot_at_2017-08-08_19-34-31](https://user-images.githubusercontent.com/30739239/29099960-d5fb2610-7c7e-11e7-97aa-b62576b09e9a.png)

**Comment by groud** [comment] 2017-08-09 14:54
Maybe a duplicate of #8708 ?

**Closed** 2017-12-07 14:19 UTC
