### ISSUE TITLE
4.0 beta 7 Vulkan failing on modern laptop

### ISSUE THREAD

**Issue by Clonkex** [godotengine/godot#69696] opened 2022-12-07 02:43 UTC
### Godot version

v4.0.beta7.mono.official [0bb1e89fb]

### System information

Windows 11, HP Omen 15 Ryzen 15-en0016ax Laptop w/ GTX 1660 Ti

### Issue description

I've been trying to get 4.0 going on my laptop so I can work in my lunch break. I found that beta 3 didn't open at all, it just gave the generic error about being unable to find any suitable Vulkan or OpenGL drivers. With beta 6 and 7, the project list opens.

After trying to open a project on beta 7, Nvidia driver 525.something:

```
c:\Program Files\Godot\Godot_v4.0-beta7_mono_win64>Godot_v4.0-beta7_mono_win64_console.exe
Godot Engine v4.0.beta7.mono.official.0bb1e89fb - https://godotengine.org
OpenGL Renderer: NVIDIA GeForce GTX 1660 Ti/PCIe/SSE2

Editing project: C:/Code Repos/Godot/GdBepuPhysics
Godot Engine v4.0.beta7.mono.official.0bb1e89fb - https://godotengine.org
ERROR: vkEnumeratePhysicalDevices reported zero accessible devices.

Do you have a compatible Vulkan installable client driver (ICD) installed?
vkEnumeratePhysicalDevices Failure
   at: (drivers/vulkan/vulkan_context.cpp:1097)
ERROR: Condition "err != OK" is true. Returning: ERR_CANT_CREATE
   at: _window_create (drivers/vulkan/vulkan_context.cpp:1626)
ERROR: Failed to create Vulkan Window.
   at: (platform/windows/display_server_windows.cpp:3603)
ERROR: Failed to create main window.
   at: (platform/windows/display_server_windows.cpp:3920)
```

After trying to open the same project on beta 7, Nvidia driver 527.37 (latest at time of writing):

```
c:\Program Files\Godot\Godot_v4.0-beta7_mono_win64>Godot_v4.0-beta7_mono_win64_console.exe
Godot Engine v4.0.beta7.mono.official.0bb1e89fb - https://godotengine.org
OpenGL Renderer: NVIDIA GeForce GTX 1660 Ti/PCIe/SSE2

Editing project: C:/Code Repos/Godot/GdBepuPhysics
Godot Engine v4.0.beta7.mono.official.0bb1e89fb - https://godotengine.org
ERROR: Condition "err" is true. Returning: ERR_CANT_CREATE
   at: _create_physical_device (drivers/vulkan/vulkan_context.cpp:1096)
ERROR: Condition "err != OK" is true. Returning: ERR_CANT_CREATE
   at: _window_create (drivers/vulkan/vulkan_context.cpp:1626)
ERROR: Failed to create Vulkan Window.
   at: (platform/windows/display_server_windows.cpp:3603)
ERROR: Failed to create main window.
   at: (platform/windows/display_server_windows.cpp:3920)
```

I can't see any reason it shouldn't be working. [Supposedly](https://vulkan.gpuinfo.org/listreports.php?devicename=NVIDIA+GeForce+GTX+1660+Ti&platform=windows) my GPU has supported Vulkan 1.3 since the start of the year.

The integrated CPU is an AMD Ryzen 5 4600H with an integrated "Radeon Graphics" GPU, so I wonder if it's trying to use that? But how would I know? I tried setting the Godot editor exe to High Performance in the Windows 11 settings menu under System > Display > Graphics but it seems to have no effect. However I noticed that setting it to Power Saving also had no effect and I got the same logs as above (including where it says GTX 1660), so perhaps it's not working.

### Steps to reproduce

- Have my laptop
- Try to start Godot 4.0 beta 7 on it

### Minimal reproduction project

N/A

**Comment by clayjohn** [comment] 2022-12-07 03:40
It sounds like Godot is trying to use your CPU which may not have updated drivers. 

If you run Godot with the ``--verbose`` command line argument, it should print out a list of available GPUs. 

The full command on windows is: 
```
./Godot_v4.0-beta7_win64.exe --verbose --rendering-driver vulkan
```
This will open the project settings with the vulkan renderer and should print out available GPUs, which one it selects, and information about the selected GPU

**Comment by Calinou** [comment] 2022-12-07 16:46
Duplicate of https://github.com/godotengine/godot/issues/57708.

**Closed by Calinou** 2022-12-07 16:46 UTC
