### ISSUE TITLE
Often drop frame 1 to 2 second on mac.

### ISSUE THREAD

**Issue by Angluca** [godotengine/godot#1745] opened 2015-04-27 08:35 UTC
I git pull and compile 1.1beta new version everyday.
I found the occasional drop frame from 1 to 2 seconds when (maybe)I use collosionobject(kine or rigid body), Every once in a while there will be.

And I run platformer example has it too,  Need to carefully look at character has been movement.
I play other 2d games hasn't it so have no problem with my machine.

**Comment by freemanfromgodotengine** [comment] 2015-04-27 21:14
Can it be related, or even the same as https://github.com/okamstudio/godot/issues/1659 ?

**Comment by Angluca** [comment] 2015-04-28 07:16
Well, I think the same as it.

**Comment by akien-mga** [comment] 2015-11-17 09:41
Closing as duplicate of #1659 then.

**Closed by akien-mga** 2015-11-17 09:41 UTC
Labels: archived
