### ISSUE TITLE
Exported variables don't get saved until they are modified

### ISSUE THREAD

**Issue by mrcdk** [godotengine/godot#11665] opened 2017-09-28 18:52 UTC
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Godot 3.0 master https://github.com/godotengine/godot/commit/4f39ce32b9195405f934445b20059e86632b47f9

**Issue description:**

I have this script that exports a bool to the inspector.:
```
tool
extends ParallaxLayer

export (bool) var centered = false setget set_centered, get_centered

var _centered = false

func set_centered(v):
	if v == null:
		print("Somehow the value is null")
	_centered = v
	if Engine.is_editor_hint() && has_node("sprite"):
		$sprite.centered = _centered
func get_centered():
	return _centered
	
func _ready():
		
	print("new layer")
	print(centered)
	print(_centered)
	
	$sprite.centered = _centered
```
When I add an instance of the scene the checkbox in the inspector is unchecked and also shows the button to go back to the default value which shouldn't do it because I haven't modified the value:
![https://i.imgur.com/57Qf1zO.png](https://i.imgur.com/57Qf1zO.png)

Because I haven't modified the value it won't get saved to the `*.tscn`:
```
...
[ext_resource path="res://unlimited_parallax_layer.tscn" type="PackedScene" id=2]
[ext_resource path="res://sprites/bg1.png" type="Texture" id=3]
...
[node name="layer4" parent="bg" instance=ExtResource( 2 )]

texture = ExtResource( 3 )
...
```

Which, when running the game, creates the following issue:
Output:
```
Somehow the value is null
new layer
False
Null
```

And the debugger stops with `Invalid set index 'centered' (on base: 'Sprite')` and points to the last line `$sprite.centered = _centered`

If I check and uncheck the checkbox in the inspector the value will be saved to t he `*.tscn` and the problem will go away. The return to default icon will also be gone.

I'm not sure if this is a generic issue or a boolean only one because I haven't tested it with other types.

**Comment by reduz** [comment] 2017-11-07 01:50
This is intended and the way it's expected to work. 

Before this functionality, users complained that, if a variable was modified in code, not updating to the rest of the places where it was used if not set. We got quite a lot of complaining about that.

Because of this, variables that are not modified will not be saved, which causes your problem.  You will have to write your code with this in mind.

**Comment by akien-mga** [comment] 2017-11-07 09:40
It doesn't look to me like what you're describing @reduz. Looks more like a bug affecting tool scripts.

**Comment by rtroncoso** [comment] 2017-11-11 15:44
@akien-mga @reduz can confirm this is happening to me as well. I'm currently tring to import game files of another project (graphics, in this case) to use with Godot TileMaps.

To load the data into the engine I'm using customized Sprite nodes with additional (exported) data about the specific graphic. This data can be seen in the game engine, with it's respective animations and loaded exported variables:

![skol-11_11_2017-12_38_24-pm-_3_](https://user-images.githubusercontent.com/1449912/32690899-a7923c60-c6dd-11e7-8fd2-dc74b38c7113.gif)

Exporting the scene containing all the assets to a file `Graphics.tscn` using a `PackedScene` instance works correctly. Opening the file in a text editor shows the correct values for everything:

![2017-11-11 11_53_29-graphics tscn - visual studio code](https://user-images.githubusercontent.com/1449912/32690537-04b1f054-c6d7-11e7-9893-f7b6d27d9478.png)

But, when opening the scene in the editor, all the values get lost and if you save/play the scene this changes will be commited and saved to the file, removing all exported variables from the node:

![2017-11-11 11_54_28-godot engine - skol - graphics tscn](https://user-images.githubusercontent.com/1449912/32690624-470898bc-c6d8-11e7-938e-dabc2337df6e.png)
![2017-11-11 12_01_46-graphics tscn - visual studio code](https://user-images.githubusercontent.com/1449912/32690618-389ac6a6-c6d8-11e7-8e14-62add1960c88.png)

**Other Observations:**

I believe this is only happening with child nodes of the exported scene's root, I tried exporting a `bool` and a `Dictionary` (containing all the graphics) variable from the root of this `Generator` and they seem to maintain themselves when opening the scene in the editor:

![2017-11-11 11_55_19-godot engine - skol - graphics tscn](https://user-images.githubusercontent.com/1449912/32690646-9e8459dc-c6d8-11e7-8216-09c94ee7e5c7.png)

Probably the error is somewhere around instancing child nodes for exported scenes and loading their saved values. This could also not be working for normally exported `PackedScene` scenes (if someone is trying to save the complete state of their game and loading it afterwise), but I can't confirm that. I'll try and look into the code where this is happening and see if there's something wrong, but I'm not very familiriazed with Godot's codebase so I can't promise anything.

Sorry for the long post, but I tried to gather as much information and data as possible just to leave this documented. Thanks!

**Comment by akien-mga** [comment] 2018-01-07 00:05
We have now entered release freeze for Godot 3.0 and want to focus only on release critical issues for that milestone. Therefore, we're moving this issue to the 3.1 milestone, though a fix may be made available for a 3.0.x maintenance release after it has been tested in the master branch during 3.1 development. If you consider that this issue is critical enough to warrant blocking the 3.0 release until fixed, please comment so that we can assess it more in-depth.

**Comment by DualMatrix** [comment] 2018-09-13 23:05
I can't reproduce this, does anyone have an example project I could use?

**Comment by vnen** [comment] 2018-09-16 20:38
I can't reproduce either in a recent dev version. There were some changes in exported variables between 3.0 and 3.1 so it might have been fixed.

If someone can reproduce, please attach a sample project.

**Closed by vnen** 2018-09-16 20:38 UTC
Labels: bug, topic:gdscript
