### ISSUE TITLE
Wobbling/Jittering of tiles in Godot 3.3 but not Godot 3.2.3 on Linux with 75 hz display

### ISSUE THREAD

**Issue by Daniel-da-Silva** [godotengine/godot#48200] opened 2021-04-26 00:18 UTC
Couldn't find one that had this problem only when changed to 3.3

**Godot version:**
3.3

**OS/device including version:**
ThinkPad X220, Mx Linux always updated,, i5-2520m

**Issue description:**
When I opened the same game with Godot 3.3 there is sometimes a small but noticeable jitter/wobble on the Tilemap when not moving while playing.
This only happened on my 75 hz monitor, not on 60 hz monitor and it only happened on Linux on this monitor (tested it on Windows with the same monitor). This doesn't happen with Godot 3.2.3.

**Minimal reproduction project:**
I wanted to upload my game but it was too big and since it seems oddly specific I don't know how much of use it is. Still wanted to mention it. Maybe there's a setting I can try? GPU Pixel Snap seems to improve the problem but not solving it and the character movement looks awful with it - so it won't be of much use.

**Comment by Daniel-da-Silva** [comment] 2021-04-26 00:27
Also wanted to add - this only affects my 2D Platformer - my 3D project is totally fine after upgrading.

**Comment by lawnjelly** [comment] 2021-04-26 06:40
Maybe making a video would help?

**Comment by Calinou** [comment] 2021-04-26 13:16
Try installing, enabling and configuring the [smoothing-addon](https://github.com/lawnjelly/smoothing-addon) to add physics interpolation to your project. See [Fixing jitter and stutter in the documentation](https://docs.godotengine.org/en/stable/tutorials/misc/jitter_stutter.html).

**Comment by Daniel-da-Silva** [comment] 2021-04-26 17:58
@lawnjelly The ThinkPad I use isn't very strong, I don't think I could really show it since the framerate would be so choppy. I don't have a capture card and you don't really see it when I captured it with my smartphone :/

@Calinou I used the addon but it didn't change anything. I'm confused because of two things: It wobbles, jitters when nothing moves - the tilemap - and secondly it wasn't the case with 3.2.3

Anyways - I deleted the import folder and now my game is small enough

Instructions: Walk to a language door. Press space.
Walk to the start door. Press space
Fall down. Stand still. And see the wobble (or don't see it) especially in the area in the picture but also on other parts on the tilemap.

[BBTS_Godot_Github.zip](https://github.com/godotengine/godot/files/6379134/BBTS_Godot_Github.zip)
![wobble](https://user-images.githubusercontent.com/73739524/116128723-89795680-a6c9-11eb-826b-daefbc1ac54c.png)

**Comment by lawnjelly** [comment] 2021-04-26 18:36
I couldn't see any wobbling / jittering of tiles (Linux Mint 20, Intel HD graphics 630), so it's really hard to give much feedback, there can be lots of source of wobble / jitter.

Vibrations can sometimes happen as a result of physics, I would try having the camera / player not use physics and see if that cures it.

**Comment by Daniel-da-Silva** [comment] 2021-04-26 18:58
@lawnjelly Do you have a monitor with above 60 hz? Because on 60 hz I also see no wobbling. I'm just wondering if it has to do with the changes from 3.2.3 because it works without any wobble in 3.2.3 and if I could change something there but turning Batching off didn't change anything. The only way if someone has a 60 hz monitor would maybe be overclocking it to 65-70 hz, sometimes this possible but I don't think the effort is worth it.

Do you mean putting the code instead of physics process into process? This didn't change anything. And camera is on idle. Sorry, I'm not sure, what you mean with not using physics. Thanks for putting the time in!

I don't even know if this would be a dealbreaker for upgrading to 3.3 because it could be very well only my machine making something weird and who uses 75 hz?

**Comment by lawnjelly** [comment] 2021-04-26 19:22
My monitor seems to be 60hz on looking it up. But in godot you can change the physics tick rate from 60. At odd tick rates I can see some nasty jitter, but that is what fixed timestep interpolation is used to correct for, if you see the link Calinou posted.

What I mean by not using physics, is to not move your player / camera with the physics engine. In godot you can move something either by applying a force to e.g. a rigidbody in the physics engine, and letting that move your object, or you can move the object position directly, and not use a physics object.

Maybe you aren't using physics already, but your project is rather large and it is hard to work out. Basically if you press left you can move the player position directly in process or physics_process, and use the delta to decide how far to move. Probably in process if you want to remove the possibility of aliasing between physics ticks and frames. If that removes the wobble then you know it is something physics related.

In 3.3 I can think of two things which may have changed and could be affecting you:
* The 2d camera no longer has a frame delay
* Physics may have changed

Other than that without seeing what is happening for you, it is pretty difficult to diagnose. Maybe another contributor will see this wobble.

**Comment by Daniel-da-Silva** [comment] 2021-04-26 21:50
Hey, thanks again for putting time into an oddly specific issue that's unlikely to be common.
I tested 75 fps as physics in Godot 3.3 and the wobble still was there (and the game runs at 200-300 fps without vsync in windowed so it should handle this). With 100 fps in Godot 3.2.3 it didn't happen. So it seems unrelated to this and rewriting it seems a relatively big task for an issue that likely is specific to this configuration (since it isn't on Windows, although my Windows PC is stronger)

The delay would seem an odd reason since I stand a longer time on one place.

Maybe jitter or wobble is the wrong word - a slight constant shivering on the tilemap? And also text it seems - I saw that in the options. 

But! Good news - it's really bad quality but I could catch it on camera!

https://user-images.githubusercontent.com/73739524/116155233-1df3b100-a6ea-11eb-98f9-6d53af64058a.mp4

**Comment by Calinou** [comment] 2021-04-26 23:01
> Maybe jitter or wobble is the wrong word - a slight constant shivering on the tilemap? And also text it seems - I saw that in the options.

In this case, this issue seems to be very close to https://github.com/godotengine/godot/issues/48130.

**Comment by Daniel-da-Silva** [comment] 2021-04-26 23:42
@Calinou I saw that issue but I thought this was a problem which was also in Godot 3.2.3 or before since in my case it's only in Godot 3.3. 3.2.3 (and 3.2.2 for that matter) are totally fine.

**Comment by lawnjelly** [comment] 2021-04-27 06:24
This kind of thing is usually due to a small vibration in the camera position, which can cause a relatively large change in the image because of sampling error (to pixels). If you programmatically set your camera position to a fixed value, and still get it, then it would be very odd, so I would suggest you test this.

As I say this is most likely to be caused by your physics.

It is also possible that some filtering mode / offset has changed between 3.2.3 and 3.3 and accentuated the effect, but you need to use a process of elimination to find the cause, you have to act as a detective.

**Comment by Daniel-da-Silva** [comment] 2021-04-27 11:53
@lawnjelly You were right! Thanks! It's the physics - at least as far as my understanding goes. I put in a piece of code to teleport the character to the level where the wobble was. In one test I had move_and_slide commented out and there was no shiver. When I commented it back in it shivered again. Even with no movement (maybe the player falls half a pixel after getting into the level when move and slide is processed? The camera is btw just attached to the player it doesn't have an extra script)
It just is so strange that it yields different results on different machines.

But how can I fix that?

**Comment by lawnjelly** [comment] 2021-04-27 12:16
> But how can I fix that?

You will have to get creative. This is similar to the problems involved with 2d snapping and jitter, and there has been a considerable amount written in various issues trying to solve it.

**Comment by Daniel-da-Silva** [comment] 2021-04-27 12:35
That's a bummer ... I can't really justify investing the time to solve this issue since I don't really need any of the features of 3.3 for that game (the learning would be awesome but I need to work on my 3D game which had no problems after upgrading but doesn't use any physics). Staying on 3.2.3 and trying out 3.3.1 etc. is likely the best option for me at the moment.

**Comment by non-nattawut** [comment] 2023-10-08 10:41
I have an workaround update to this issue , DISCLAIMER : I am not sure is this same to mine because author does not include video.

*SOLUTION*
1. My 75Hz Monitor have tiles wobbling when player moving, When is alter value of
`physics/common/physics_ticks_per_second` from 60 to 75 its looking fixed (sometimes still wobbling)

2. use _ process(delta) instead of _physics_process(delta) with update position instead of use move_and_slide() seem fixed too
`

First half of video is `physics_ticks_per_second`  = 60
second half is 75
Actually in video see no different, I dont know why. But in my screen its fixed
https://github.com/godotengine/godot/assets/67323548/6aecfdc9-648a-4eb2-9b9f-08aeee32a4f5

my reproduce project (This issue I met on both 3.x and 4.x version of GODOT)
[test-for-tilemap-wobbing-3.X.zip](https://github.com/godotengine/godot/files/12840409/test-for-tilemap-wobbing-3.X.zip) )(this only have solution 1 and 2)


PS. on your screen maybe not met with any issue. I asked my friend that test on GODOT 3.x with 60,90 and 144 Hz, result in He's not met any issues

**Comment by non-nattawut** [comment] 2023-10-08 11:29
I have an workaround update to this issue , DISCLAIMER : I am not sure is this same to mine because author does not include video.

**THE ISSUE**
white pillar tile (in video) is wobbling/shaking when player moving on 75Hz monitor refresh rate, on 60Hz refresh rate look fine

**SOLUTION in reproduce project**

1. My 75Hz Monitor have tiles wobbling when player moving, When is alter value of `physics/common/physics_ticks_per_second` from 60 to 75 its looking fixed (sometimes still wobbling but not much)

2. use `_ process(delta)` instead of `_physics_process(delta)` with `update position` instead of use `move_and_slide()` seem fixed too. and alter value of `physics/common/physics_ticks_per_second` take no effect, still work perfectly

**SOLUTION in my main project**
for solution number 1 is working but if focus a bit. it still have little tile shaking/wobbling
for solution number 2 is not working still need to adjust `physics/common/physics_ticks_per_second` to 75

**VIDEO**
First half of video is `physics_ticks_per_second` = 60
second half is 75
Actually in video see no different, I dont know why. But in my screen its fixed
https://github.com/godotengine/godot/assets/67323548/6aecfdc9-648a-4eb2-9b9f-08aeee32a4f5

**REPRODUCE PROJECT** (This issue I met on both 3.x and 4.x version of GODOT)
[test-for-tilemap-wobbing-4.X.zip](https://github.com/godotengine/godot/files/12840446/test-for-tilemap-wobbing-4.X.zip)
[test-for-tilemap-wobbing-3.X.zip](https://github.com/godotengine/godot/files/12840413/test-for-tilemap-wobbing-3.X.zip)

PS. on your hardware maybe not met with any issue. I asked my friend that test on GODOT 3.x with 90 and 144 Hz, result in He's not met any issues

**My PC**

Monitor1 : Acer VG240Y (50 and 75Hz tested and met issue)
Monitor2 : SM2333T (50 tested and met issue)
***Both monitor tested on 60Hz and see no any problem with tile shaking/wobbling

OS : Windows 10 64 bit
GODOT : 3.5.3.stable , 4.1.2.stable (tested on my PC)
GPU : NVIDIA RTX 3060TI
CPU : Ryzen 5 3600

**Comment by Calinou** [comment] 2023-10-08 16:58
Closing in favor of https://github.com/godotengine/godot-proposals/issues/2753, as this issue is dependent on the lack of built-in physics interpolation.

Note that even once physics interpolation is implemented, you will need to make sure your camera movement is a multiple (or divider) of the monitor refresh rate for it to look perfectly smooth without any stuttering. This is not specific to Godot – it's mathematics :slightly_smiling_face:

**Closed by Calinou** 2023-10-08 16:58 UTC
Labels: topic:core, needs testing
