### ISSUE TITLE
Drag'n drop nodes into script broken

### ISSUE THREAD

**Issue by albinaask** [godotengine/godot#58446] opened 2022-02-22 19:57 UTC
### Godot version

v3.4.2.stable.mono.official [45eaa2daf]

### System information

Windows 10, AMD, Nvidia

### Issue description

When grabbing a node associated with an editor (e.g Spatial or CanvasItem) and dragging it into an open GDScript in the editor "script tab" the editor first time switches back to the scene view, then going back into the "scripting tab" dragging the node into the GDScript now correctly inserts the quoted relative node path. 

While fixing this I've also realised that I use the `$path/to/node.do_something()` instead of `get_node("path/to/node").do_something()` so inserting the dollar-sign version would make the experience smoother, however not technically a bug per say, the enhancement is likely (without actually have looked at the source code) extremely tightly packed with the bug and could be ironed out like two birds with one stone. If you'd rather have this over at the feature suggestion rep let me know and I'll post it there instead.

(video): 
https://user-images.githubusercontent.com/11806563/155209021-44e5821d-d49e-4fa5-870e-14d0856578f7.mp4

### Steps to reproduce

1. Open project
2. new scene
3. new node 
4. new child node
5. new GDScript connected to node
5. drag child node into script file. 

### Minimal reproduction project

N/a

**Comment by KoBeWi** [comment] 2022-02-22 21:48
The first part is duplicate of #33704 (in 3.5 you can mitigate it by holding Alt)
As for the second part, dollar operator supports quoted strings just fine, so you can do `$"path/to/node"`. I once suggested that the quotes should be only inserted when needed: #33317

**Closed by KoBeWi** 2022-02-22 21:48 UTC
Labels: enhancement, topic:gdscript, topic:editor
