### ISSUE TITLE
Can't build the editor for mingw on linux

### ISSUE THREAD

**Issue by fire** [godotengine/godot#23157] opened 2018-10-19 18:58 UTC
**Godot version:**
cf7a66195fadd078bb5d6fafebf54e250f5163e7

**OS**
fedora-28

**Issue description:**
Can't build the editor.

@Faless

**Steps to reproduce:**

```
[go] Start to build godot-sandbox/0.68.cf7a6619/defaultStage/1/defaultJob on gocd-agent-fedora-28-0 [/go]
[go] Task: /bin/bash -c "scons platform=windows target=release_debug -j`nproc` use_lto=no gdnative_wrapper=yes deprecated=no"took: 31.677sexited: 2
scons: Reading SConscript files ...
Configuring for Windows: target=release_debug, bits=default
Using Mingw
YASM is necessary for WebM SIMD optimizations.
WebM SIMD optimizations are disabled. Check if your CPU architecture, CPU bits or platform are supported!
Checking for C header file mntent.h... (cached) no
scons: done reading SConscript files.
scons: Building targets ...
Compiling ==> main/main.cpp
Compiling ==> modules/websocket/lws_client.cpp
modules/websocket/lws_client.cpp: In member function 'virtual Error LWSClient::connect_to_host(String, String, uint16_t, bool, PoolVector<String>)':
modules/websocket/lws_client.cpp:87:41: error: invalid conversion from 'const char*' to 'size_t {aka long long unsigned int}' [-fpermissive]
  strncpy(abuf, addr_str.ascii().get_data(), 1023);
                ~~~~~~~~~~~~~~~~~~~~~~~~~^~
modules/websocket/lws_client.cpp:87:49: error: invalid conversion from 'int' to 'const char*' [-fpermissive]
  strncpy(abuf, addr_str.ascii().get_data(), 1023);
                                                 ^
modules/websocket/lws_client.cpp:87:49: error: too few arguments to function 'errno_t strncpy_s(char*, size_t, const char*, size_t)'
In file included from /usr/x86_64-w64-mingw32/sys-root/mingw/include/string.h:190:0,
                 from ./core/os/copymem.h:42,
                 from ./core/dvector.h:34,
                 from ./core/variant.h:41,
                 from ./core/method_ptrcall.h:36,
                 from ./core/method_bind.h:35,
                 from ./core/class_db.h:34,
                 from ./core/reference.h:34,
                 from ./core/io/stream_peer.h:34,
                 from modules/websocket/lws_helper.h:36,
                 from modules/websocket/lws_client.h:36,
                 from modules/websocket/lws_client.cpp:32:
/usr/x86_64-w64-mingw32/sys-root/mingw/include/sec_api/string_s.h:39:27: note: declared here
   _CRTIMP errno_t __cdecl strncpy_s(char *_Dst,size_t _DstSizeInChars,const char *_Src,size_t _MaxCount);
                           ^~~~~~~~~
modules/websocket/lws_client.cpp:89:38: error: invalid conversion from 'const char*' to 'size_t {aka long long unsigned int}' [-fpermissive]
  strncpy(hbuf, p_host.utf8().get_data(), 1023);
                ~~~~~~~~~~~~~~~~~~~~~~^~
modules/websocket/lws_client.cpp:89:46: error: invalid conversion from 'int' to 'const char*' [-fpermissive]
  strncpy(hbuf, p_host.utf8().get_data(), 1023);
                                              ^
modules/websocket/lws_client.cpp:89:46: error: too few arguments to function 'errno_t strncpy_s(char*, size_t, const char*, size_t)'
In file included from /usr/x86_64-w64-mingw32/sys-root/mingw/include/string.h:190:0,
                 from ./core/os/copymem.h:42,
                 from ./core/dvector.h:34,
                 from ./core/variant.h:41,
                 from ./core/method_ptrcall.h:36,
                 from ./core/method_bind.h:35,
                 from ./core/class_db.h:34,
                 from ./core/reference.h:34,
                 from ./core/io/stream_peer.h:34,
                 from modules/websocket/lws_helper.h:36,
                 from modules/websocket/lws_client.h:36,
                 from modules/websocket/lws_client.cpp:32:
/usr/x86_64-w64-mingw32/sys-root/mingw/include/sec_api/string_s.h:39:27: note: declared here
   _CRTIMP errno_t __cdecl strncpy_s(char *_Dst,size_t _DstSizeInChars,const char *_Src,size_t _MaxCount);
                           ^~~~~~~~~
modules/websocket/lws_client.cpp:91:38: error: invalid conversion from 'const char*' to 'size_t {aka long long unsigned int}' [-fpermissive]
  strncpy(pbuf, p_path.utf8().get_data(), 2047);
                ~~~~~~~~~~~~~~~~~~~~~~^~
modules/websocket/lws_client.cpp:91:46: error: invalid conversion from 'int' to 'const char*' [-fpermissive]
  strncpy(pbuf, p_path.utf8().get_data(), 2047);
                                              ^
modules/websocket/lws_client.cpp:91:46: error: too few arguments to function 'errno_t strncpy_s(char*, size_t, const char*, size_t)'
In file included from /usr/x86_64-w64-mingw32/sys-root/mingw/include/string.h:190:0,
                 from ./core/os/copymem.h:42,
                 from ./core/dvector.h:34,
                 from ./core/variant.h:41,
                 from ./core/method_ptrcall.h:36,
                 from ./core/method_bind.h:35,
                 from ./core/class_db.h:34,
                 from ./core/reference.h:34,
                 from ./core/io/stream_peer.h:34,
                 from modules/websocket/lws_helper.h:36,
                 from modules/websocket/lws_client.h:36,
                 from modules/websocket/lws_client.cpp:32:
/usr/x86_64-w64-mingw32/sys-root/mingw/include/sec_api/string_s.h:39:27: note: declared here
   _CRTIMP errno_t __cdecl strncpy_s(char *_Dst,size_t _DstSizeInChars,const char *_Src,size_t _MaxCount);
                           ^~~~~~~~~
scons: *** [modules/websocket/lws_client.windows.opt.tools.64.o] Error 1
scons: building terminated because of errors.
[go] Task status: failed, took: 31.677s, exited: 2
```

**Comment by fire** [comment] 2018-10-19 18:59
First seen with these changes:

Dualtagh Murray <dualtagh.murray@gonitro.com> | Fixing warnings generated by MSVCFixes #22684. | b902a2f2a7438810cdcb053568ed5c27089b1e8a
-- | -- | --
Max Hilbrunner <mhilbrunner@users.noreply.github.com> | Merge pull request #23035 from voithos/missingpckShow an alert when a project is not found in release mode | a3072aa35e3bfd69d826fa33328b3ce1862f472a
Zaven Muradyan <voithos@google.com> | Show an alert when a project is not found in release modePreviously, an error message would get printed to the console, but thisis problematic in e.g. Windows where a console is not displayed. In thecase of a missing .pck file, the binary would just silently fail. Now,it shows an alert.Fixes #21994. | 552c518b80fb14d8e35bcf

**Comment by fire** [comment] 2018-10-19 19:00
Broken by https://github.com/godotengine/godot/commit/b902a2f2a7438810cdcb053568ed5c27089b1e8a

**Comment by akien-mga** [comment] 2018-10-19 19:10
Duplicate of #23141.

**Closed by akien-mga** 2018-10-19 19:10 UTC
