### ISSUE TITLE
Godot Doesn't Import Blender File Correctly If Blender File Has Whitespace In File Name

### ISSUE THREAD

**Issue by yosimba2000** [godotengine/godot#76813] opened 2023-05-07 18:58 UTC
### Godot version

4.0.2

### System information

Blender Version 3.5
Windows 10 Pro 64-Bit, 22H2

### Issue description

Godot imports absolutely nothing if the .blend file name has a whitespace in it. 
For example, 'MyFile.blend' imports correctly into Godot.
But 'My File.blend' imports nothing into Godot.

### Steps to reproduce

Minimal reproduction:
1) Create new Blender file. It should come with the default cube.
2) Save this Blender file using any name, as long as the name does not have a whitespace. For example, 'MyFile.blend'
3) Save As this Blender file again, but use a different name that has a whitespace. For example, 'My File.blend'

4) Import both Blender files into Godot.
5) For Blender file that DOES NOT have whitespace in its name, drag it into Godot scene. The cube shows correctly.
6) For Blender file that DOES have whitespace in its name, drag it into Godot scene. Nothing shows.
7) Done.

### Minimal reproduction project

N/A

**Comment by yosimba2000** [comment] 2023-05-07 18:59
Forgot to mention I am on Windows 10 Pro 64-Bit, 22H2

**Comment by brno32** [comment] 2023-05-08 21:48
Would this be a good first issue?

**Comment by yosimba2000** [comment] 2023-05-08 23:16
> Would this be a good first issue?

Hi, not sure what you mean. Do you mean as a simple bugfix? It sounds like it would be. Somewhere in Godot's Blender import function probably isn't parsing whitespaces properly.

**Comment by Zireael07** [comment] 2023-05-09 06:42
@yosimba2000 They are wondering whether this should get a "good first issue" or equivalent tag.

**Comment by AThousandShips** [comment] 2023-05-09 06:46
From a quick glance at the import code I can't find any use of whitespace in there so I'm not so sure this is a simple issue

**Comment by AThousandShips** [comment] 2023-05-09 08:49
Then it might be sufficient to change `sink_global` to use `uri_encode` instead of `c_escape` but I'm not sure

**Comment by AThousandShips** [comment] 2023-05-09 11:13
Then it might be due to this line:
https://github.com/godotengine/godot/blob/668cf3c66f42989949399f36e9faa29426e37416/modules/gltf/editor/editor_import_blend_runner.cpp#L138

**Comment by AThousandShips** [comment] 2023-05-09 11:14
I don't see any places that do make this change in the code

**Comment by akien-mga** [comment] 2023-05-09 11:26
Actually it is a Blender exporter bug.

I initially tried to reproduce the bug and couldn't, using Blender 3.3.6 from my distro.

Then I downloaded and set up Blender 3.5.1 and the bug happens.

Loading `b c.blend` in Blender 3.5.1 and exporting it as glTF Separate with default config:
```
$ ls b*
 b%20c.bin  'b c.blend'  'b c.gltf'
```

CC @julienduroure

**Comment by AThousandShips** [comment] 2023-05-09 11:38
Then for recent versions `uri_encode` should work as a fix but it'd seemingly need to consider both options as blender uses different names on different versions

**Comment by akien-mga** [comment] 2023-05-09 11:40
It's tricky, because users could have a file named `b%20c.blend` already, which should export as `b%20c.gltf` and `b%20c.bin`. In this case we probably don't want to override the name choice made by the user. Hopefully the issue can be patched in Blender 3.5.2 and we won't need to work it around.

**Comment by julienduroure** [comment] 2023-05-09 11:59
@akien-mga There is no Blender 3.5.2 planned.

The next release 3.6 (currently in alpha) will include this fix: https://projects.blender.org/blender/blender-addons/commit/8c77651799
Can you please test with 3.6?

**Comment by akien-mga** [comment] 2023-05-09 12:13
Thanks, I confirm it's fixed in 3.6 alpha from today.

I think we can close this as wontfix from our end then, it's just Blender 3.5/3.5.1 which are known problematic for this specific use case and this will be soon fixed by 3.6.

**Closed by akien-mga** 2023-05-09 12:13 UTC
Labels: bug, confirmed, topic:thirdparty, topic:import
