### ISSUE TITLE
[GDScript] export enum gives error

### ISSUE THREAD

**Issue by supagu** [godotengine/godot#44784] opened 2020-12-29 08:08 UTC
**Godot version:**
master Commit #187be733

**Issue description:**
Exporting custom enum results in error: "Export type can only be built-in or a resource."

**Steps to reproduce:**

```gdscript
enum enum_viewport_type {UI, CAMERA}
@export var viewport_type: enum_viewport_type;
```

** Extra info **

The current "latest" documentation claims it should work: https://docs.godotengine.org/en/latest/tutorials/scripting/gdscript/gdscript_exports.html?highlight=export

**Comment by Calinou** [comment] 2020-12-29 08:12
Duplicate of https://github.com/godotengine/godot/issues/42894.

**Closed by Calinou** 2020-12-29 08:12 UTC
