### ISSUE TITLE
Setting the project theme affects the code hint for the code editor.

### ISSUE THREAD

**Issue by wetiontop** [godotengine/godot#16303] opened 2018-02-02 03:49 UTC
**Godot version:**
3.0 release

**OS/device including version:**
MacOS 10.3.1

**Issue description:**
When I set a global theme in the project settings, then restarting Godot would cause the code editor's code hint to not work, which is an easy problem to reproduce.

**Steps to reproduce:**
1、open project setting set the theme
2、restart godot
3、new GDScript
4、input api, look code hint

**Comment by Clocktown** [comment] 2018-03-20 15:46
I can confirm this error for 3.0.2 on Windows 10.  
Additionally, Message Windows that pop up in the editor (e.g. when closing the editor) are also affected (they lack an outer margin). There might be many more hidden bugs caused by this.

**Comment by amcolash** [comment] 2018-07-22 20:50
I was running into this issue as well. I thought it had something to do with using the editor theme as a template. Guess it is good to know that everything just needs to have that theme set at a more local level for now.

**Comment by KoBeWi** [comment] 2020-06-14 22:43
Closing in favor of #31834, because it's a duplicate with better title.

**Closed by KoBeWi** 2020-06-14 22:43 UTC
Labels: bug, topic:editor
