### ISSUE TITLE
EditorFileSystem duplicating root folder if deleting a folder from a not-indexed unit

### ISSUE THREAD

**Issue by Ranoller** [godotengine/godot#16685] opened 2018-02-14 09:30 UTC
Same issue that what fixed here #9225 to new folder. But with deleted folders (only in not indexed drives)

**Godot version:**

Godot 2.1 and Godot 3

**OS/device including version:**

Win7

**Issue description:**

Deleting folder in filesystem editor dock causes that editor shows a duplicated of res:// inside the deleted folder (editor only, filesystem is right). Reopen editor rescans and problem is fixed.
If you delete recursivelly the new ghost folders you can freeze editor in a "re-importing" non existing files loop.

Edit:( This behavior only happend when the godot project is in a drive with not indexed content (EJ: usb pendrive))

**Comment by vnen** [comment] 2018-02-14 14:26
Can't reproduce this with Godot 3.

**Comment by akien-mga** [comment] 2018-02-14 14:35
Detailed steps to reproduce are missing from the OP, but I guess it might be related to deleting folders from outside Godot, while being in those folders in the Godot FileSystem dock. So I'd try something like:
- create `res://test`, enter it the FileSystem dock
- in explorer.exe, delete that `test` folder
- see what happens or not in Godot

**Comment by vnen** [comment] 2018-02-14 14:43
I tried that, even with recursive folders, and a few other variations.

More detailed steps to reproduce would be appreciated.

**Comment by Ranoller** [comment] 2018-02-14 14:45
Mmmm... ok, it´s all releated to the non importing issue in  not indexed unit. I try to reproduce in a indexed unit and works as expected. So, i don´t know well what to do with this issue. I edit title for now and if not-indexed units issue is considered a bug i detail all the problems that godot have working from one of this units.

**Comment by KoBeWi** [comment] 2020-05-21 13:07
This looks very much like #27526

**Comment by Calinou** [comment] 2020-05-21 13:21
Duplicate of #27526.

**Closed by Calinou** 2020-05-21 13:21 UTC
Labels: bug, topic:editor
