### ISSUE TITLE
Engine.is_editor_hint() doesnt work on func _draw()

### ISSUE THREAD

**Issue by jonSP12** [godotengine/godot#90346] opened 2024-04-07 14:05 UTC
### Tested versions

4.2.1

### System information

windows 10 vulkan foward+

### Issue description

Engine.is_editor_hint() doesnt work on func _draw()

### Steps to reproduce

```
@tool
extends Node2D


func _process(delta):
	
	queue_redraw();
	
	if Engine.is_editor_hint():
		queue_redraw();
	else:
		queue_redraw();

func _draw():
	
	if not Engine.is_editor_hint():
		draw_circle(Vector2(100, 100), 200, Color.ALICE_BLUE )
	
	
	if Engine.is_editor_hint():
		$sprite2D.rotation += 0.2
	else:
		$sprite2D.rotation -= 0.1
```

### Minimal reproduction project (MRP)

NA

**Comment by KoBeWi** [comment] 2024-04-07 14:42
What do you mean by it doesn't work? What is the expected behavior vs what it does?

**Comment by jonSP12** [comment] 2024-04-07 15:13
the $sprite2D doesnt rotate also nothing gets drawn when you run the scene.
the expected behavior of Engine.is_editor_hint() is to have code running in the editor or in the game ( run the scene )
Engine.is_editor_hint() only works in process function, ( from what i tried )...

**Comment by KoBeWi** [comment] 2024-04-07 17:07
Can't reproduce

https://github.com/godotengine/godot/assets/2223172/11e7627a-4dcd-42fd-a6d7-4d53d685572c

Does `sprite2D` exist in your scene?

**Comment by jonSP12** [comment] 2024-04-07 18:09
Its working
I just notice i had this null return on top the func... I just didnt though it would trigger on running the scene, i though those 2 ( if's ) would only run in the editor


```

func _draw():
	
	if (drawText == null): ####################################
		return;
	if ( drawText.get_size() < Vector2(32, 32)  ):#####################
		return;
	
		
	for i in canvasTex: 
		draw_texture( canvasTex[i], i );
	
	if ( drawText != null ):
		draw_texture(drawText, mGpos );
	
	
	if not Engine.is_editor_hint():
		draw_circle(Vector2(100, 100), 200, Color.ALICE_BLUE )
		draw_circle(Vector2(200, 200), 200, Color.ALICE_BLUE )
	
	
	
	if Engine.is_editor_hint():
		$sprite2D.rotation += 0.2
	else:
		$sprite2D.rotation -= 0.1
	

```

**Comment by KoBeWi** [comment] 2024-04-07 18:26
Well the ifs are not guarded by `Engine.is_editor_hint()`, so they will run outside editor too.
Closing as it's working as expected.

**Closed by KoBeWi** 2024-04-07 18:26 UTC
