### ISSUE TITLE
Weird texture resize

### ISSUE THREAD

**Issue by jh62** [godotengine/godot#47376] opened 2021-03-26 07:30 UTC
**Godot version:** v3.2.4.rc5.official (b169a16cb51b7203a171245acb5b4193c9d4bca4.)

**OS/device:** Windows10/Intel HD5500/GLES2

**Issue description:**

TextureRect has an odd behaviour when using the mouse to resize it.

**Steps to reproduce:**

1. Create TextureRect
2. Assign a texture
3. Resize using mouse dragging side points.

**Minimal reproduction project:**

![vhyIdb8RpV](https://user-images.githubusercontent.com/22467336/112597388-d5479000-8deb-11eb-876d-a1fe941ab9b6.gif)

**Comment by akien-mga** [comment] 2021-03-26 08:25
Duplicate of #46979. 3.3 RC 6 is already out fixing this.

**Closed by akien-mga** 2021-03-26 08:25 UTC
