### ISSUE TITLE
Error building android on xubuntu with strange encoding problem.

### ISSUE THREAD

**Issue by alikifah** [godotengine/godot#5724] opened 2016-07-15 15:05 UTC
System information:
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04 LTS"
NAME="Ubuntu"
VERSION="16.04 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian

I'm trying to compile for android with the latest master branch
I managed to compile the engine for X11 using scons with no issues, this problem occurs only when I build for android.
I installed all the requirements and set ANDROID_HOME  and ANDROID_NDK_ROOT  as was mentioned in the wiki, but on building with scons:          

I get this strange error with scons searching for files with invalid encoding characters:

```
$ scons -j 10 p=android target=release_debug
----------------
----------------
---------------- 
/home/ali/android/android-ndk-r12b/toolchains/arm-linux-androideabi-4.9/prebuilt//linux-x86/bin/arm-linux-androideabi-g++: 6: /home/ali/android/android-ndk-r12b/toolchains/arm-linux-androideabi-4.9/prebuilt//linux-x86/bin/arm-linux-androideabi-g++: �
          h������%�
                     h�p����%��
                               �����%r�
                                       h�P����%j�
                                                  h�@����%b�
                                                             h�0����%Z�
                                                                        h�: not found
/home/ali/android/android-ndk-r12b/toolchains/arm-linux-androideabi-4.9/prebuilt//linux-x86/bin/arm-linux-androideabi-g++: 7: /home/ali/android/android-ndk-r12b/toolchains/arm-linux-androideabi-4.9/prebuilt//linux-x86/bin/arm-linux-androideabi-g++: �
          h: not found
/home/ali/android/android-ndk-r12b/toolchains/arm-linux-androideabi-4.9/prebuilt//linux-x86/bin/arm-linux-androideabi-g++: 9: /home/ali/android/android-ndk-r12b/toolchains/arm-linux-androideabi-4.9/prebuilt//linux-x86/bin/arm-linux-androideabi-g++: ������%�
                  h�p����%��
                            h(�`����%��
                                       h)�P����%��
                                                  h*�@����%��
                                                             h+�0����%ڻ
                                                                       h,� ����%һ
 h-�����%ʻ
           h.�����%»
                    h/������%��
                               h0������%��
                                          h1������%��
                                                     h2������%��
                                                                h3������%��
                                                                           h4������%��
      h5������%��
                 h6������%��
                            h7�p����%z�
                                       h8�`����%r�
                                                  h9�P����%j�
                                                             h:�@����%b�
                                                                        h;�0����%Z�
   h<� ����%R�
              h=�����%J�
                         h>�����%B�
                                   h?������%:�
                                              h@������%2�
                                                         hA������%*�
                                                                    hB������%"�
                                                                               hC������%�
          hD������%�
                     hE������%
�
 hF������%�
            hG�p����%��
                       hH�`����%��
                                  hI�P����%��
                                             hJ�@����%��
                                                        hK�0����%ں
                                                                  hL� ����%Һ
                                                                            hM�����%ʺ
      hN�����%º
               hO������%��
                          hP������%��
                                     hQ������%��
                                                hR������%��
                                                           hS������%��
                                                                      hT������%��
 hU������%��
            hV������%��
                       hW�p����%z�
                                  hX�`����%r�
                                             hY�P����%j�
                                                        hZ�@����%b�
                                                                   h[�0����%Z�
                                                                              h\� ����%R�
         h]�����%J�
                    h^�����%B�
                              h_������%:�
                                         h`������%2�
                                                    ha������%*�
                                                               hb������%"�
                                                                          hc������%�
     hd������%�
                he������%
�
 hf������%�
            hg�p����%��
                       hh�`����%��
                                  hi�P����%��
                                             hj�@����%��
                                                        hk�0����%ڹ
                                                                  hl� ����%ҹ
                                                                            hm�����%ʹ
      hn�����%¹
               ho������%��
                          hp������%��
                                     hq������%��
                                                hr������%��
                                                           hs������%��
                                                                      ht������%��
 hu������%��
            hv������%��
                       hw�p����%z�
                                  hx�`����%r�
                                             hy�P����w1�9���sHk�H��H�y&u��V�����UH��AWAVAUATI��SH��(H�����H���
                                     ���H���a���H�<H9�u�fDH��H9�t��/u�H�=Z�
  �?H�����H��
             ����BL9����t�z�
                             �����ݾ�L�L��H�������
                                                    ���L�����H������TH�=��
                                                                             1��a��p�7�������P���H��t����: not found
/home/ali/android/android-ndk-r12b/toolchains/arm-linux-androideabi-4.9/prebuilt//linux-x86/bin/arm-linux-androideabi-g++: 9: /home/ali/android/android-ndk-r12b/toolchains/arm-linux-androideabi-4.9/prebuilt//linux-x86/bin/arm-linux-androide�����1��A�0�F������AGH�==�X1�H�+������H��t����������
                                   ��: not found
/home/ali/android/android-ndk-r12b/toolchains/arm-linux-androideabi-4.9/prebuilt//linux-x86/bin/arm-linux-androideabi-g++: 10: /home/ali/android/android-ndk-r12b/toolchains/arm-linux-androideabi-4.9/prebuilt//linux-x86/bin/arm-linux-androideabi-g++: Syntax error: ")" unexpected
scons: *** [platform/android/os_android.os] Error 2
/home/ali/android/android-ndk-r12b/toolchains/arm-linux-androideabi-4.9/prebuilt//linux-x86/bin/arm-linux-androideabi-g++ -o platform/android/ifaddrs_android.os -c -DNO_STATVFS -fpic -ffunction-sections -funwind-tables -fstack-protector -fvisibility=hidden -D__ARM_ARCH_7__ -D__ARM_ARCH_7A__ -D__GLIBC__ -Wno-psabi -march=armv7-a -mfloat-abi=softfp -ftree-vectorize -funsafe-math-optimizations -fno-strict-aliasing -DANDROID -Wa,--noexecstack -DGLES2_ENABLED -mfpu=neon -D__ARM_NEON__ -D_DEBUG -g1 -Wall -O0 -DDEBUG_ENABLED -fno-exceptions -DNO_SAFE_CAST -DFREETYPE_ENABLED -fPIC -DDEBUG_MEMORY_ALLOC -DSCI_NAMESPACE -DENABLE_DEPRECATED -DDEBUG_MEMORY_ALLOC -DANDROID_ENABLED -DUNIX_ENABLED -DNO_FCNTL -DMPC_FIXED_POINT -DMUSEPACK_ENABLED -DSQUISH_ENABLED -DVORBIS_ENABLED -DOPUS_ENABLED -DTHEORA_ENABLED -DTHEORALIB_ENABLED -DPNG_ENABLED -DDDS_ENABLED -DPVR_ENABLED -DJPG_ENABLED -DWEBP_ENABLED -DSPEEX_ENABLED -DGDSCRIPT_ENABLED -DMINIZIP_ENABLED -DXML_ENABLED -DETC1_ENABLED -Icore -Icore/math -Itools -Idrivers -I. -Iplatform/android -I/home/ali/android/android-ndk-r12b/platforms/android-14/arch-arm/usr/include -I/home/ali/android/android-ndk-r12b/sources/cxx-stl/gnu-libstdc++/4.9/include -I/home/ali/android/android-ndk-r12b/sources/cpufeatures -Idrivers/freetype -Idrivers/freetype/freetype/include platform/android/ifaddrs_android.cpp
scons: *** [platform/android/godot_android.os] Error 2
scons: *** [platform/android/file_access_android.os] Error 2
scons: *** [platform/android/dir_access_android.os] Error 2
scons: *** [platform/android/audio_driver_opensl.os] Error 2
scons: *** [platform/android/file_access_jandroid.os] Error 2
scons: *** [platform/android/dir_access_jandroid.os] Error 2
scons: *** [platform/android/thread_jandroid.os] Error 2
scons: *** [platform/android/audio_driver_jandroid.os] Error 2
/home/ali/android/android-ndk-r12b/toolchains/arm-linux-androideabi-4.9/prebuilt//linux-x86/bin/arm-linux-androideabi-g++: 1: /home/ali/android/android-ndk-r12b/toolchains/arm-linux-androideabi-4.9/prebuilt//linux-x86/bin/arm-linux-androideabi-g++: �4}~{Wv.VZ: not found
/home/ali/android/android-ndk-r12b/toolchains/arm-linux-androideabi-4.9/prebuilt//linux-x86/bin/arm-linux-androideabi-g++: 1: /home/ali/android/android-ndk-r12b/toolchains/arm-linux-androideabi-4.9/prebuilt//linux-x86/bin/arm-linux-androideabi-g++: �K: not found
/home/ali/android/android-ndk-r12b/toolchains/arm-linux-androideabi-4.9/prebuilt//linux-x86/bin/arm-linux-androideabi-g++: 1: /home/ali/android/android-ndk-r12b/toolchains/arm-linux-androideabi-4.9/prebuilt//linux-x86/bin/arm-linux-androideabi-g++: h�KAp�KBx�KC��KE��KF��KQ��KR��KS��KU��KV��KW��KX��KY��Ka��Kn��Ko��Kq��KT��KL�K�KJ�KP�KO: not found
/home/ali/android/android-ndk-r12b/toolchains/arm-linux-androideabi-4.9/prebuilt//linux-x86/bin/arm-linux-androideabi-g++: 1: /home/ali/android/android-ndk-r12b/toolchains/arm-linux-androideabi-4.9/prebuilt//linux-x86/bin/arm-linux-androideabi-g++: P�K_X�K]: not found
/home/ali/android/android-ndk-r12b/toolchains/arm-linux-androideabi-4.9/prebuilt//linux-x86/bin/arm-linux-androideabi-g++: 1: /home/ali/android/android-ndk-r12b/toolchains/arm-linux-androideabi-4.9/prebuilt//linux-x86/bin/arm-linux-androideabi-g++: ELF: not found
/home/ali/android/android-ndk-r12b/toolchains/arm-linux-androideabi-4.9/prebuilt//linux-x86/bin/arm-linux-androideabi-g++: 1: /home/ali/android/android-ndk-r12b/toolchains/arm-linux-androideabi-4.9/prebuilt//linux-x86/bin/arm-linux-androideabi-g++: ����%��
                h: not found
/home/ali/android/android-ndk-r12b/toolchains/arm-linux-androideabi-4.9/prebuilt//linux-x86/bin/arm-linux-androideabi-g++: 2: /home/ali/android/android-ndk-r12b/toolchains/arm-linux-androideabi-4.9/prebuilt//linux-x86/bin/arm-linux-androideabi-g++: �@����%��
                  h
                   �0����%ڼ
                           h
                            �: not found
/home/ali/android/android-ndk-r12b/toolchains/arm-linux-androideabi-4.9/prebuilt//linux-x86/bin/arm-linux-androideabi-g++: 6: /home/ali/android/android-ndk-r12b/toolchains/arm-linux-androideabi-4.9/prebuilt//linux-x86/bin/arm-linux-androideabi-g++: �
          h������%�
                     h�p����%��
                               �����%r�
                                       h�P����%j�
                                                  h�@����%b�
                                                             h�0����%Z�
                                                                        h�: not found
/home/ali/android/android-ndk-r12b/toolchains/arm-linux-androideabi-4.9/prebuilt//linux-x86/bin/arm-linux-androideabi-g++: 7: /home/ali/android/android-ndk-r12b/toolchains/arm-linux-androideabi-4.9/prebuilt//linux-x86/bin/arm-linux-androideabi-g++: �
          h: not found
/home/ali/android/android-ndk-r12b/toolchains/arm-linux-androideabi-4.9/prebuilt//linux-x86/bin/arm-linux-androideabi-g++: 9: /home/ali/android/android-ndk-r12b/toolchains/arm-linux-androideabi-4.9/prebuilt//linux-x86/bin/arm-linux-androideabi-g++: ������%�
                  h�p����%��
                            h(�`����%��
                                       h)�P����%��
                                                  h*�@����%��
                                                             h+�0����%ڻ
                                                                       h,� ����%һ
 h-�����%ʻ
           h.�����%»
                    h/������%��
                               h0������%��
                                          h1������%��
                                                     h2������%��
                                                                h3������%��
                                                                           h4������%��
      h5������%��
                 h6������%��
                            h7�p����%z�
                                       h8�`����%r�
                                                  h9�P����%j�
                                                             h:�@����%b�
                                                                        h;�0����%Z�
   h<� ����%R�
              h=�����%J�
                         h>�����%B�
                                   h?������%:�
                                              h@������%2�
                                                         hA������%*�
                                                                    hB������%"�
                                                                               hC������%�
          hD������%�
                     hE������%
�
 hF������%�
            hG�p����%��
                       hH�`����%��
                                  hI�P����%��
                                             hJ�@����%��
                                                        hK�0����%ں
                                                                  hL� ����%Һ
                                                                            hM�����%ʺ
      hN�����%º
               hO������%��
                          hP������%��
                                     hQ������%��
                                                hR������%��
                                                           hS������%��
                                                                      hT������%��
 hU������%��
            hV������%��
                       hW�p����%z�
                                  hX�`����%r�
                                             hY�P����%j�
                                                        hZ�@����%b�
                                                                   h[�0����%Z�
                                                                              h\� ����%R�
         h]�����%J�
                    h^�����%B�
                              h_������%:�
                                         h`������%2�
                                                    ha������%*�
                                                               hb������%"�
                                                                          hc������%�
     hd������%�
                he������%
�
 hf������%�
            hg�p����%��
                       hh�`����%��
                                  hi�P����%��
                                             hj�@����%��
                                                        hk�0����%ڹ
                                                                  hl� ����%ҹ
                                                                            hm�����%ʹ
      hn�����%¹
               ho������%��
                          hp������%��
                                     hq������%��
                                                hr������%��
                                                           hs������%��
                                                                      ht������%��
 hu������%��
            hv������%��
                       hw�p����%z�
                                  hx�`����%r�
                                             hy�P����w1�9���sHk�H��H�y&u��V�����UH��AWAVAUATI��SH��(H�����H���
                                     ���H���a���H�<H9�u�fDH��H9�t��/u�H�=Z�
  �?H�����H��
             ����BL9����t�z�
                             �����ݾ�L�L��H�������
                                                    ���L�����H������TH�=��
                                                                             1��a��p�7�������P���H��t����: not found
/home/ali/android/android-ndk-r12b/toolchains/arm-linux-androideabi-4.9/prebuilt//linux-x86/bin/arm-linux-androideabi-g++: 9: /home/ali/android/android-ndk-r12b/toolchains/arm-linux-androideabi-4.9/prebuilt//linux-x86/bin/arm-linux-androide�����1��A�0�F������AGH�==�X1�H�+������H��t����������
                                   ��: not found
/home/ali/android/android-ndk-r12b/toolchains/arm-linux-androideabi-4.9/prebuilt//linux-x86/bin/arm-linux-androideabi-g++: 10: /home/ali/android/android-ndk-r12b/toolchains/arm-linux-androideabi-4.9/prebuilt//linux-x86/bin/arm-linux-androideabi-g++: Syntax error: ")" unexpected
scons: *** [platform/android/ifaddrs_android.os] Error 2
scons: building terminated because of errors
```

after that I found these files with the same encoding issue created in the main folder of godot.
![screenshot_2016-07-15_16-41-29](https://cloud.githubusercontent.com/assets/20050723/16878675/be1d1b42-4aad-11e6-973f-ea5c4d3ae61e.png)

My system is using the default UTF-8 encoding
help me please I don't know how to solve this error is it a file system problem or something else?
Thanks in advance.

**Comment by vnen** [comment] 2016-07-15 15:54
This is weird. I see the path for NDK is `linux-x86` which means you have the NDK for 32bits. And it seems that the NDK site mixed up the links, so I recommend you to download the NDK once again and check if it's the right architecture. (I assume you have a 64bit platform, otherwise running 10 jobs wouldn't make much sense).

**Comment by alikifah** [comment] 2016-07-17 22:31
It seems like this problem occurs only in the 32bit system I switched to 64bit ubuntu and it was gone. but I'm surprised that no one else had this problem since I couldn't find it in the search.

**Comment by Calinou** [comment] 2018-04-05 09:14
I'll close this, since OP resolved their issue with compiling for Android a long time ago and nobody else confirmed having the same issue. If you can still reproduce this, please comment on this issue.

**Closed by Calinou** 2018-04-05 09:14 UTC
Labels: bug, platform:android, topic:buildsystem
