### ISSUE TITLE
Generate functions in external editors

### ISSUE THREAD

**Issue by rcorre** [godotengine/godot#20024] opened 2018-07-07 20:08 UTC
**Godot version:**

```
3.0.4.stable.custom_build
```

**OS/device including version:**

Linux desktop-arch 4.17.2-1-ARCH #1 SMP PREEMPT Sat Jun 16 11:08:59 UTC 2018 x86_64 GNU/Linux

**Feature Request:**

It would be nice if the "Create Function" option from the signal connection dialog worked with external editors.
I use neovim, and when I wire a new connect with "Create Function" enabled, it opens the script with neovim but there is no new function definition.

One flexible solution I could think of is adding a `{generated_text}` external editor param.
If there are concerns about passing multiline text as a cli flag, then `{generated_text}` could be the path to a temp file containing the generated function, or the text could be passed on STDIN.

Another is to append and save the generated text to the file before opening the editor. This could be optional as it is not the current behavior.

**Comment by Calinou** [comment] 2020-11-06 18:42
Duplicate of https://github.com/godotengine/godot/issues/41283.

**Closed by Calinou** 2020-11-06 18:42 UTC
Labels: enhancement, topic:editor, usability
