### ISSUE TITLE
Scaling physics body to 0 causes issues with raycasting

### ISSUE THREAD

**Issue by skemps** [godotengine/godot#43478] opened 2020-11-12 13:43 UTC
**Godot version:**
3.2.3 Official stable

**OS/device including version:**
linux, nvidia 970, GLES3

**Issue description:**
When one of physics bodies in scene is scaled to 0, other can not be detected with raycasting properly. Sometimes they're detected and sometimes they're not

**Steps to reproduce:**
Add two bodies to scene. Scale one to 0 and use space_state.intersect_ray on other.

**Minimal reproduction project:**
https://github.com/skemps/GodotPhysicsBodyScaleIssue

**Comment by Zireael07** [comment] 2020-11-12 14:31
1) Scaling physics body to 0 is a no-no generally.
2) Duplicate of an existing issue which IIRC is already fixed (by showing you a warning if you scale stuff to 0)

**Comment by skemps** [comment] 2020-11-12 15:26
I noticed now that if I scale it in the editor I get det == 0 warning, but I was scaling it in code and there was no warnings.

**Comment by madmiraal** [comment] 2020-11-13 10:55
Duplicate of #41031 and #40952, which was fixed with #41426, which has been cherry-picked for 3.2.4.

**Closed by madmiraal** 2020-11-13 10:55 UTC
Labels: topic:physics
