### ISSUE TITLE
2D Occluders with cull mode enabled show light before the shadow

### ISSUE THREAD

**Issue by eon-s** [godotengine/godot#10095] opened 2017-08-04 18:47 UTC
**Ubuntu 17.04 - Godot 3 alpha**

**Issue description:**
Enabling the cull mode on LightOccluder2D shows some light where the shadow should start

![lightoccluderbug](https://user-images.githubusercontent.com/10215987/28982197-55860cee-792b-11e7-94d8-98670d0f647b.png)
_The right one is counter clockwise and light penetrates a bit the occluder_

**Steps to reproduce:**
Enable a culling mode on a LightOccluder2D.
Can be tested with "light and shadows" demo, using culling mode in clockwise.

**Comment by reduz** [comment] 2017-09-01 19:47
This is not a bug, it's a feature... you can adjust the bias to correct this.

**Comment by eon-s** [comment] 2017-09-01 22:31
There is no shadow bias property anywhere (at least up to d1308d5c5 ) on 2D lights nor occluders.

There is a gradient length but cannot be less than 1 (still, gradient seem to start far from the occluder).

**Comment by reduz** [comment] 2017-09-01 22:51
Ok.. i guess we need shadow bias..

**Comment by reduz** [comment] 2017-11-13 21:03
kicking to 3.1, too much stuff to do

**Comment by akien-mga** [comment] 2019-11-26 12:31
Is this still reproducible in the current master branch? If so, could you provide a minimal reproduction project?

**Comment by eon-s** [comment] 2019-11-26 12:37
Is still there on 3.1 at least, I'll check on 3.2 and add a project if needed, I think that there were no changes on 2D occluders.

**Comment by eon-s** [comment] 2019-11-28 01:32
Here is a modified demo to show the problem with occluders with cull mode enabled, just check the border of the red one, try different cull modes on the occluder to see the effects.
[unbiased_shadows.zip](https://github.com/godotengine/godot/files/3899415/unbiased_shadows.zip)

**Comment by KoBeWi** [comment] 2020-11-05 10:14
Looks fixed in 494bf38

**Closed by KoBeWi** 2020-11-05 10:14 UTC
Labels: bug, topic:rendering
