### ISSUE TITLE
Multiple instances of ViewportContainer scene share state

### ISSUE THREAD

**Issue by rainerdeyke** [godotengine/godot#27326] opened 2019-03-22 15:39 UTC
**Godot version:**
3.1

**OS/device including version:**
Lubuntu 18.04 LTS, amd64, Nvidia GeForce GTX 1060, nvidia-driver-390

**Issue description:**
I create two instances of a scene containing a ViewportContainer->Viewport->Spatial chain.  I modify the 3D scene of one of these two viewports.  The change appears in both viewports.

**Steps to reproduce:**
Create a scene ViewportContainer->Viewport->Spatial chain.  Create a second scene that creates two instances of the first scene.  Modify one of the 3D scenes.

**Minimal reproduction project:**
[test00.zip](https://github.com/godotengine/godot/files/2997189/test00.zip)

**Comment by KoBeWi** [comment] 2019-03-28 21:20
Not sure if this is a bug. You probably need to toggle something to disable Viewport sharing. Sharing a same resource between instances sometimes happen.

**Comment by rainerdeyke** [comment] 2019-03-29 07:29
Low-level optimizations should not break high-level functionality unless the high-level functionality itself is clearly marked as undefined behaviour.  I haven't seen anything in the documentation that says I can't use viewports like that, so this looks like a bug to me.

That said, if there is a workaround, I'd very much like to know what it is!

**Comment by mrcdk** [comment] 2019-03-29 08:36
The issue is that both viewport share the same  [`World`](https://docs.godotengine.org/en/3.1/classes/class_world.html) which is the default one so spatial will be added to the same scenario, physics space,... You need to specify a new `World` in your `Viewport` and make that resource `Local to Scene` so it won't be shared between the different instances

![https://i.imgur.com/GsPkVPL.png](https://i.imgur.com/GsPkVPL.png)

**Comment by KoBeWi** [comment] 2024-11-19 23:20
Yes, assign a separate World3D, or enable `own_world_3d`. This is mentioned in the Viewport's description, so closing.

**Closed by KoBeWi** 2024-11-19 23:20 UTC
Labels: discussion, documentation
