### ISSUE TITLE
Attached to node script is not available at runtime

### ISSUE THREAD

**Issue by p10tr3k** [godotengine/godot#69140] opened 2022-11-24 22:31 UTC
### Godot version

v3.5.1.stable.official [6fed1ffa3]

### System information

Mac OS Ventura

### Issue description

I have Player scene that has child node MoveCommandAffector with custom script
![image](https://user-images.githubusercontent.com/11059246/203869916-58dd7d22-b487-4cb0-9772-18f85bc2e8be.png)

At runtime I list all children (affectors) from node CommandAffectors:
```
var affectors = $Player.get_command_affectors()
affectors[0].affect_command(MoveCommand.new($Player, Vector2.UP, $Board))
```
When I try to run method on attached script to the first element I get this error:
![image](https://user-images.githubusercontent.com/11059246/203870192-1432abd1-470d-4cbf-be03-751f9b231880.png)

The first element contains expected element but it doesn't have any script attached to it:

![image](https://user-images.githubusercontent.com/11059246/203870314-35380d9b-8a36-4208-aafa-357f35f98dd6.png)

### Steps to reproduce

Just run attached project

### Minimal reproduction project

[GodotBug_missingScript.zip](https://github.com/godotengine/godot/files/10087566/GodotBug_missingScript.zip)

**Comment by p10tr3k** [comment] 2022-11-24 22:50
Ok, I have found the problem. I have used constructor with parameters. When I removed parameters from constructor it worked.
I think that there should be specific error message for such case.

**Comment by KoBeWi** [comment] 2022-11-25 16:45
Duplicate of #15866

**Closed by KoBeWi** 2022-11-25 16:45 UTC
