### ISSUE TITLE
Editor settings. User can go into "Interface" section which contains bad parameters

### ISSUE THREAD

**Issue by breakmt** [godotengine/godot#26199] opened 2019-02-23 16:51 UTC
**Godot version:**
3.1 beta 6

**OS/device including version:**
Windows 7 x64

**Issue description:**
1. Start Godot - Open project,
2. Editor - Editor settings

**Result:**
1. You are in "Interface" section,
2. You can see strange parameters. For example "Editor language" is an edit box, not a list. If you try to change parameter it is not actually changing. For example, uncheck "Quit Confirmation" (no "rollback" icon btw) and go to "Editor" section - you will see that "Quit Confirmation" is still checked. 

**Expected:**
1. You are in "Editor" section (by default),
2. When you click on "Interface" section it just expands/collapses, you can't go into it

![bug](https://user-images.githubusercontent.com/1552169/53289190-fae4b400-37a3-11e9-8e9a-962c1986b481.gif)

**Comment by meld-cp** [comment] 2019-02-24 00:34
Can't reproduce the issue on Win 10 Pro x64, (NVIDIA GeForce GTX 660)

![2019-02-24_13-28-07](https://user-images.githubusercontent.com/18450687/53293426-5b253580-3838-11e9-9ed3-69d3fbbb164a.gif)

**Comment by breakmt** [comment] 2019-02-24 06:31
Hm, really strange. I tried on Win 10 x64 too and yes, it is not reproduced there. But it is still an issue for my PC with Win7 x64 GeForce GTX 650 Ti

**Comment by breakmt** [comment] 2019-02-26 18:27
I managed to look at C:\Users\breakmt\AppData\Roaming\Godot\editor_settings-3.tres and I found there lines like:
```
interface/editor_language = ";kjlj;"
interface/hidpi_mode = 0
interface/show_script_in_scene_tabs = false
interface/font_size = 14
interface/source_font_size = 14
interface/custom_font = ""
interface/dim_editor_on_dialog_popup = true
interface/dim_amount = 0.6
interface/dim_transition_time = 0.08
interface/separate_distraction_mode = false
interface/save_each_scene_on_quit = true
interface/quit_confirmation = false
```
I'm not sure how they were created there, I can only guess that it could happen when I switched between Godot versions? Anyway, I deleted all that strange lines and error is gone.

**Comment by akien-mga** [comment] 2019-02-27 08:05
That's weird, I don't find those strings in Godot 2.1, Godot 3.0 nor current master branch. They might have been from 3.0 alpha time before the `editor` category was added in `interface`.

At any rate, closing as this should not happen on new configs.

**Closed by akien-mga** 2019-02-27 08:05 UTC
Labels: bug, topic:editor
