### ISSUE TITLE
Beta 15: Can't use "quick open scene" while editing scripts, The editor gets stuck

### ISSUE THREAD

**Issue by ababen1** [godotengine/godot#72035] opened 2023-01-25 13:01 UTC
### Godot version

v4.0.beta15.official [4fa6edc88]

### System information

linux

### Issue description

When I use Control+Shift+O to quick open scene, the editor gets stuck and I have to kill the process in order to get out of it.
However, this bug only seems to happen when I'm viewing the script tab.

### Steps to reproduce

I have attached a video of the bug, I think it explains it

### Minimal reproduction project

https://user-images.githubusercontent.com/80917990/214569805-a69ece5e-1803-464c-9025-ed1bfa66bf38.mp4

**Comment by akien-mga** [comment] 2023-01-25 13:23
Duplicate of #72012

**Closed by akien-mga** 2023-01-25 13:23 UTC
