### ISSUE TITLE
Windows 10 - Blender Path does not contain a Blender installation

### ISSUE THREAD

**Issue by kuligs2** [godotengine/godot#94560] opened 2024-07-20 14:04 UTC
### Tested versions

Godot Engine v4.3.beta2.official.b75f0485b
And i think beta3

### System information

Godot v4.3.beta2 - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA RTX A2000 (NVIDIA; 31.0.15.5186) - Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz (8 Threads)

### Issue description

Trying to select blender installation when the prompt is shown, and it says path is not valid.

![image](https://github.com/user-attachments/assets/2f6e9001-dae1-46fd-9428-2cb5feac6fd9)

I tried to add and remove last "/". It didnt make any difference

Tried
![image](https://github.com/user-attachments/assets/36ef4545-fdd9-4eaf-83fc-2d5b26a26c74)

This should be valid right?
![image](https://github.com/user-attachments/assets/79e6d767-d573-4cb2-8e4d-a8549e2d83b4)

### Steps to reproduce

Crete new project, 
copy .blend file to the project folder, 
it shows the blend path prompt, 
try to set it, it does not allow

### Minimal reproduction project (MRP)

-

**Comment by AThousandShips** [comment] 2024-07-20 14:07
Try pointing to the executable, not the folder

**Comment by kuligs2** [comment] 2024-07-20 14:08
> Try pointing to the executable, not the folder

This works only if you do it in the Editor settings but not when it promts, there you can only select forlder.

**Comment by kuligs2** [comment] 2024-07-20 14:09
Here, no file selection, only folder.
![image](https://github.com/user-attachments/assets/2351c068-0ba2-43e3-8631-52bfcca27aae)

**Comment by AThousandShips** [comment] 2024-07-20 14:12
This is a duplicate of:
* https://github.com/godotengine/godot/issues/93235

Thank you for reporting

**Closed by AThousandShips** 2024-07-20 14:12 UTC
