### ISSUE TITLE
Script-Icon in the Scene-Dock not updateing

### ISSUE THREAD

**Issue by whiteshampoo** [godotengine/godot#60295] opened 2022-04-16 07:40 UTC
### Godot version

3.x.x + 4 alpha 6

### System information

not OS-specific

### Issue description

When i add/remove a script in the Inspector, the Scene-Dock is not updating the add-/remove-script icon.

![icon1](https://user-images.githubusercontent.com/2029198/163666463-16da4532-6d9d-48ff-ac4f-7f3c523b1845.PNG)
![icon2](https://user-images.githubusercontent.com/2029198/163666466-84d08a6c-a913-432b-9479-7569fda1aed0.PNG)

### Steps to reproduce

1. Click on a Node
2. Add/Remove the attached script in the inspector
-> Icon in the Scene-Dock is not updated

### What i've found

Looks like the function `SceneTreeDock::_update_script_button()` in [scene_tree_dock.cpp](https://github.com/godotengine/godot/blob/master/editor/scene_tree_dock.cpp) needs to be called again. But i dont know from where.

**Comment by kleonc** [comment] 2022-04-16 13:10
Duplicate of #55237.

**Comment by Calinou** [comment] 2022-04-16 14:13
Duplicate of https://github.com/godotengine/godot/issues/55237.

**Closed by Calinou** 2022-04-16 14:13 UTC
Labels: bug, topic:editor
