### ISSUE TITLE
`Tween` crashes game if used in `_*process` `_*input` callbacks

### ISSUE THREAD

**Issue by lufog** [godotengine/godot#59997] opened 2022-04-07 21:02 UTC
### Godot version

v4.0.alpha.custom_build [0f9231ca0]

### System information

Windows 11, Geforce 1660, Vulkan Clustered

### Issue description

Tween crashed the game if used in `_*process` or `_*input` callbacks, it doesn't even have to be called.

https://user-images.githubusercontent.com/10379487/162301692-c3bfdd64-c79f-4003-81f0-6c5651ca412a.mp4

I don't press any buttons, i.e. the `run_animation()` method is not even called.

backtrace:
```
================================================================
CrashHandlerException: Program crashed
Engine version: Godot Engine v4.0.alpha.custom_build (0f9231ca0f49a26f868dbc91521b02b966de50ef)
Dumping the backtrace. Please include this when reporting the bug on https://github.com/godotengine/godot/issues
[0] oidnUnmapBuffer
[1] oidnUnmapBuffer
[2] oidnUnmapBuffer
[3] embree::TaskScheduler::wait
[4] embree::TaskScheduler::wait
[5] oidnUnmapBuffer
[6] oidnUnmapBuffer
[7] oidnUnmapBuffer
[8] oidnUnmapBuffer
[9] <couldn't map PC to fn name>
[10] <couldn't map PC to fn name>
[11] <couldn't map PC to fn name>
[12] <couldn't map PC to fn name>
[13] <couldn't map PC to fn name>
[14] oidnUnmapBuffer
[15] BaseThreadInitThunk
-- END OF BACKTRACE --
================================================================
```

### Steps to reproduce

Uncomment `_process()` and press play button.

### Minimal reproduction project

[TweenTest_G4.zip](https://github.com/godotengine/godot/files/8446431/TweenTest_G4.zip)

**Comment by lufog** [comment] 2022-04-07 21:37
If run with connected debugger, I get:
![image](https://user-images.githubusercontent.com/10379487/162324051-7d1e4e06-2f14-4321-a827-5dd91071f6cb.png)

**Comment by KoBeWi** [comment] 2022-04-08 00:52
Proper stack trace:
```
CrashHandlerException: Program crashed
Engine version: Godot Engine v4.0.alpha.custom_build (ae2d53cdcdb55417bd3094efa53324295c035333)
Dumping the backtrace. Please include this when reporting the bug on https://github.com/godotengine/godot/issues
[0] Map<StringName,Input::Action,Comparator<StringName>,DefaultAllocator>::find (C:\godot_source\core\templates\map.h:585)
[1] Input::is_action_just_pressed (C:\godot_source\core\input\input.cpp:275)
[2] call_with_variant_args_retc_helper<Input,bool,StringName const &,bool,0,1> (C:\godot_source\core\variant\binder_common.h:705)
[3] call_with_variant_args_retc_dv<Input,bool,StringName const &,bool> (C:\godot_source\core\variant\binder_common.h:501)
[4] MethodBindTRC<Input,bool,StringName const &,bool>::call (C:\godot_source\core\object\method_bind.h:584)
[5] GDScriptFunction::call (C:\godot_source\modules\gdscript\gdscript_vm.cpp:1742)
[6] GDScriptInstance::callp (C:\godot_source\modules\gdscript\gdscript.cpp:1539)
[7] Node::_gdvirtual__process_call<0> (C:\godot_source\scene\main\node.h:229)
[8] Node::_notification (C:\godot_source\scene\main\node.cpp:57)
[9] Node::_notificationv (C:\godot_source\scene\main\node.h:45)
[10] Object::notification (C:\godot_source\core\object\object.cpp:850)
[11] SceneTree::_notify_group_pause (C:\godot_source\scene\main\scene_tree.cpp:853)
[12] SceneTree::process (C:\godot_source\scene\main\scene_tree.cpp:452)
[13] Main::iteration (C:\godot_source\main\main.cpp:2722)
[14] OS_Windows::run (C:\godot_source\platform\windows\os_windows.cpp:677)
[15] widechar_main (C:\godot_source\platform\windows\godot_windows.cpp:169)
[16] _main (C:\godot_source\platform\windows\godot_windows.cpp:191)
[17] main (C:\godot_source\platform\windows\godot_windows.cpp:205)
[18] WinMain (C:\godot_source\platform\windows\godot_windows.cpp:219)
[19] __scrt_common_main_seh (D:\a01\_work\26\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288)
[20] BaseThreadInitThunk
-- END OF BACKTRACE --
```
Does not happen in alpha 6 and it's not related to Tweens. This code will crash too:
```GDScript
func _process(_delta: float) -> void:
	if Input.is_action_just_pressed("ui_accept"):
		pass
```

**Comment by KoBeWi** [comment] 2022-04-08 00:53
And it's actually a duplicate of #59971

**Closed by KoBeWi** 2022-04-08 00:53 UTC
Labels: bug, topic:core, crash

**Comment by lufog** [comment] 2022-04-08 08:21
I apologize for misleading you. I experimented with `Tween`, late at night. Somehow I did not even think that the problem was not related to them. Perhaps I was sleepy. :)

As I understand it, attaching a backtrace from GitHub actions binaries makes little sense?  In order for it to contain useful information, do you need to build it yourself with debug symbols, or do something else?

**Comment by KoBeWi** [comment] 2022-04-08 09:06
Yes, official releases don't have debug symbols, so you need a custom build. I think nightly builds come with debug symbols too.
