### ISSUE TITLE
Make the Node search also work in the Remote View of the Scene Tree dock

### ISSUE THREAD

**Issue by PLyczkowski** [godotengine/godot#31073] opened 2019-08-04 11:14 UTC
Use case: If you want to inspect a single node, that you know the name of, while the game is running, this would add a quick way to do find it.

**Comment by KoBeWi** [comment] 2019-08-04 12:43
Duplicate of #22949
Already implemented in 3.2-dev

**Closed by KoBeWi** 2019-08-04 12:43 UTC
