### ISSUE TITLE
Linux Intel GPU cannot allocate memory

### ISSUE THREAD

**Issue by MrMinimal** [godotengine/godot#29388] opened 2019-06-01 18:45 UTC
**Godot version:**
Godot_v3.1.1-stable_x11.64

**OS/device including version:**
Xubuntu 19.04
```
00:02.0 VGA compatible controller [0300]: Intel Corporation HD Graphics 615 [8086:591e] (rev 02) (prog-if 00 [VGA controller])
	Subsystem: Xiaomi HD Graphics 615 [1d72:1607]
	Flags: bus master, fast devsel, latency 0, IRQ 134
	Memory at b0000000 (64-bit, non-prefetchable) [size=16M]
	Memory at a0000000 (64-bit, prefetchable) [size=256M]
	I/O ports at 3000 [size=64]
	[virtual] Expansion ROM at 000c0000 [disabled] [size=128K]
	Capabilities: <access denied>
	Kernel driver in use: i915
	Kernel modules: i915
```

**Issue description:**
I try to start a simple 3D scene with a camera and a capsule mesh and get in the terminal:
`i965: Failed to submit batchbuffer: Cannot allocate memory`

Also under `/var/log/syslog`I get:
```
Jun  1 20:30:35 tom-laptop kernel: [  701.298286] Godot_v3.1.1-st: page allocation failure: order:0, mode:0x40d0(__GFP_IO|__GFP_FS|__GFP_COMP|__GFP_RECLAIMABLE), nodemask=(null),cpuset=/,mems_allowed=0
Jun  1 20:30:36 tom-laptop kernel: [  701.298293] CPU: 1 PID: 2310 Comm: Godot_v3.1.1-st Not tainted 5.0.0-15-generic #16-Ubuntu
Jun  1 20:30:36 tom-laptop kernel: [  701.298293] Hardware name: Timi TM1607/TM1607, BIOS XMAKB200P0100 05/07/2017
Jun  1 20:30:36 tom-laptop kernel: [  701.298294] Call Trace:
Jun  1 20:30:36 tom-laptop kernel: [  701.298301]  dump_stack+0x63/0x8a
Jun  1 20:30:36 tom-laptop kernel: [  701.298304]  warn_alloc.cold.119+0x7b/0xfb
Jun  1 20:30:36 tom-laptop kernel: [  701.298306]  __alloc_pages_slowpath+0xe63/0xea0
Jun  1 20:30:37 tom-laptop kernel: [  701.298308]  ? __alloc_pages_nodemask+0x2c4/0x2e0
Jun  1 20:30:37 tom-laptop kernel: [  701.298311]  __alloc_pages_nodemask+0x2c4/0x2e0
Jun  1 20:30:37 tom-laptop kernel: [  701.298314]  alloc_pages_current+0x81/0xe0
Jun  1 20:30:37 tom-laptop kernel: [  701.298316]  new_slab+0x378/0x740
Jun  1 20:30:37 tom-laptop kernel: [  701.298318]  ? xas_alloc+0x99/0xb0
Jun  1 20:30:37 tom-laptop kernel: [  701.298321]  ___slab_alloc+0x373/0x4f0
Jun  1 20:30:37 tom-laptop kernel: [  701.298322]  ? xas_nomem+0x3d/0x60
Jun  1 20:30:37 tom-laptop kernel: [  701.298324]  ? xas_alloc+0x99/0xb0
Jun  1 20:30:37 tom-laptop kernel: [  701.298326]  __slab_alloc+0x20/0x40
Jun  1 20:30:37 tom-laptop kernel: [  701.298328]  kmem_cache_alloc+0x197/0x1d0
Jun  1 20:30:37 tom-laptop kernel: [  701.298329]  ? xas_nomem+0x3d/0x60
Jun  1 20:30:37 tom-laptop kernel: [  701.298331]  xas_nomem+0x3d/0x60
Jun  1 20:30:37 tom-laptop kernel: [  701.298333]  add_to_swap_cache+0x253/0x300
Jun  1 20:30:37 tom-laptop kernel: [  701.298336]  __read_swap_cache_async+0xfc/0x210
Jun  1 20:30:37 tom-laptop kernel: [  701.298338]  swap_cluster_readahead+0x174/0x2f0
Jun  1 20:30:37 tom-laptop kernel: [  701.298340]  ? __switch_to_asm+0x34/0x70
Jun  1 20:30:37 tom-laptop kernel: [  701.298343]  ? i2cdev_ioctl_smbus+0x60/0x2d0
Jun  1 20:30:37 tom-laptop kernel: [  701.298345]  shmem_swapin+0x63/0xb0
Jun  1 20:30:37 tom-laptop kernel: [  701.298348]  ? sched_clock+0x9/0x10
Jun  1 20:30:37 tom-laptop kernel: [  701.298349]  ? radix_tree_node_ctor+0x40/0x40
Jun  1 20:30:37 tom-laptop kernel: [  701.298352]  ? call_rcu+0x10/0x20
Jun  1 20:30:37 tom-laptop kernel: [  701.298354]  ? xas_store+0x332/0x540
Jun  1 20:30:37 tom-laptop kernel: [  701.298357]  shmem_getpage_gfp+0x71f/0xca0
Jun  1 20:30:37 tom-laptop kernel: [  701.298359]  shmem_read_mapping_page_gfp+0x44/0x80
Jun  1 20:30:37 tom-laptop kernel: [  701.298395]  i915_gem_object_get_pages_gtt+0x24d/0x660 [i915]
Jun  1 20:30:37 tom-laptop kernel: [  701.298425]  ____i915_gem_object_get_pages+0x22/0x40 [i915]
Jun  1 20:30:37 tom-laptop kernel: [  701.298453]  __i915_gem_object_get_pages+0x5b/0x70 [i915]
Jun  1 20:30:37 tom-laptop kernel: [  701.298482]  __i915_vma_do_pin+0x2d0/0x4b0 [i915]
Jun  1 20:30:37 tom-laptop kernel: [  701.298509]  eb_lookup_vmas+0x8b5/0xb90 [i915]
Jun  1 20:30:37 tom-laptop kernel: [  701.298511]  ? __mutex_lock_interruptible_slowpath+0x13/0x20
Jun  1 20:30:37 tom-laptop kernel: [  701.298539]  eb_relocate_slow+0xd0/0x2c0 [i915]
Jun  1 20:30:37 tom-laptop kernel: [  701.298566]  i915_gem_do_execbuffer+0x3cf/0x1030 [i915]
Jun  1 20:30:37 tom-laptop kernel: [  701.298568]  ? xas_load+0xc/0x80
Jun  1 20:30:37 tom-laptop kernel: [  701.298571]  ? find_get_entry+0x50/0x160
Jun  1 20:30:37 tom-laptop kernel: [  701.298573]  ? __kmalloc_node+0x1e1/0x2b0
Jun  1 20:30:37 tom-laptop kernel: [  701.298600]  i915_gem_execbuffer2_ioctl+0x1c9/0x360 [i915]
Jun  1 20:30:37 tom-laptop kernel: [  701.298627]  ? i915_gem_madvise_ioctl+0x10e/0x1e0 [i915]
Jun  1 20:30:37 tom-laptop kernel: [  701.298653]  ? i915_gem_execbuffer_ioctl+0x2b0/0x2b0 [i915]
Jun  1 20:30:37 tom-laptop kernel: [  701.298668]  drm_ioctl_kernel+0xad/0xf0 [drm]
Jun  1 20:30:37 tom-laptop kernel: [  701.298680]  drm_ioctl+0x233/0x410 [drm]
Jun  1 20:30:37 tom-laptop kernel: [  701.298706]  ? i915_gem_execbuffer_ioctl+0x2b0/0x2b0 [i915]
Jun  1 20:30:37 tom-laptop kernel: [  701.298710]  do_vfs_ioctl+0xa9/0x640
Jun  1 20:30:37 tom-laptop kernel: [  701.298713]  ? handle_mm_fault+0xe1/0x210
Jun  1 20:30:37 tom-laptop kernel: [  701.298715]  ksys_ioctl+0x67/0x90
Jun  1 20:30:37 tom-laptop kernel: [  701.298717]  __x64_sys_ioctl+0x1a/0x20
Jun  1 20:30:37 tom-laptop kernel: [  701.298719]  do_syscall_64+0x5a/0x110
Jun  1 20:30:37 tom-laptop kernel: [  701.298721]  entry_SYSCALL_64_after_hwframe+0x44/0xa9
Jun  1 20:30:37 tom-laptop kernel: [  701.298722] RIP: 0033:0x7f4cd2908417
Jun  1 20:30:37 tom-laptop kernel: [  701.298724] Code: 00 00 90 48 8b 05 79 0a 0d 00 64 c7 00 26 00 00 00 48 c7 c0 ff ff ff ff c3 66 2e 0f 1f 84 00 00 00 00 00 b8 10 00 00 00 0f 05 <48> 3d 01 f0 ff ff 73 01 c3 48 8b 0d 49 0a 0d 00 f7 d8 64 89 01 48
Jun  1 20:30:37 tom-laptop kernel: [  701.298725] RSP: 002b:00007ffce7bda9e8 EFLAGS: 00000246 ORIG_RAX: 0000000000000010
Jun  1 20:30:37 tom-laptop kernel: [  701.298727] RAX: ffffffffffffffda RBX: 00000000041e3e70 RCX: 00007f4cd2908417
Jun  1 20:30:37 tom-laptop kernel: [  701.298728] RDX: 00007ffce7bdaa30 RSI: 0000000040406469 RDI: 0000000000000004
Jun  1 20:30:37 tom-laptop kernel: [  701.298729] RBP: 00007ffce7bdaa30 R08: 000000000421e000 R09: 000000000000000c
Jun  1 20:30:37 tom-laptop kernel: [  701.298729] R10: 00007ffce7bdaad0 R11: 0000000000000246 R12: 0000000040406469
Jun  1 20:30:37 tom-laptop kernel: [  701.298730] R13: 0000000000000004 R14: ffffffffffffffff R15: 0000000000000000
Jun  1 20:30:37 tom-laptop kernel: [  701.298733] warn_alloc_show_mem: 4 callbacks suppressed
Jun  1 20:30:37 tom-laptop kernel: [  701.298733] Mem-Info:
Jun  1 20:30:37 tom-laptop kernel: [  701.298737] active_anon:154 inactive_anon:398 isolated_anon:0
Jun  1 20:30:37 tom-laptop kernel: [  701.298737]  active_file:1419 inactive_file:1319 isolated_file:0
Jun  1 20:30:37 tom-laptop kernel: [  701.298737]  unevictable:904846 dirty:0 writeback:0 unstable:0
Jun  1 20:30:37 tom-laptop kernel: [  701.298737]  slab_reclaimable:11657 slab_unreclaimable:17392
Jun  1 20:30:37 tom-laptop kernel: [  701.298737]  mapped:2513 shmem:905083 pagetables:2443 bounce:0
Jun  1 20:30:37 tom-laptop kernel: [  701.298737]  free:22137 free_pcp:224 free_cma:0
Jun  1 20:30:37 tom-laptop kernel: [  701.298740] Node 0 active_anon:616kB inactive_anon:1592kB active_file:5676kB inactive_file:5276kB unevictable:3619384kB isolated(anon):0kB isolated(file):0kB mapped:10052kB dirty:0kB writeback:0kB shmem:3620332kB shmem_thp: 0kB shmem_pmdmapped: 0kB anon_thp: 0kB writeback_tmp:0kB unstable:0kB all_unreclaimable? no
Jun  1 20:30:37 tom-laptop kernel: [  701.298741] Node 0 DMA free:15312kB min:276kB low:344kB high:412kB active_anon:0kB inactive_anon:0kB active_file:0kB inactive_file:0kB unevictable:592kB writepending:0kB present:15988kB managed:15904kB mlocked:0kB kernel_stack:0kB pagetables:0kB bounce:0kB free_pcp:0kB local_pcp:0kB free_cma:0kB
Jun  1 20:30:37 tom-laptop kernel: [  701.298745] lowmem_reserve[]: 0 2084 3762 3762 3762
Jun  1 20:30:37 tom-laptop kernel: [  701.298747] Node 0 DMA32 free:43504kB min:37280kB low:46600kB high:55920kB active_anon:756kB inactive_anon:684kB active_file:2988kB inactive_file:2332kB unevictable:2113348kB writepending:40kB present:2239988kB managed:2174452kB mlocked:0kB kernel_stack:64kB pagetables:236kB bounce:0kB free_pcp:572kB local_pcp:332kB free_cma:0kB
Jun  1 20:30:37 tom-laptop kernel: [  701.298750] lowmem_reserve[]: 0 0 1678 1678 1678
Jun  1 20:30:37 tom-laptop kernel: [  701.298751] Node 0 Normal free:29732kB min:30024kB low:37528kB high:45032kB active_anon:868kB inactive_anon:548kB active_file:2764kB inactive_file:3116kB unevictable:1504232kB writepending:228kB present:1818624kB managed:1727244kB mlocked:32kB kernel_stack:5360kB pagetables:9536kB bounce:0kB free_pcp:324kB local_pcp:312kB free_cma:0kB
Jun  1 20:30:37 tom-laptop kernel: [  701.298754] lowmem_reserve[]: 0 0 0 0 0
Jun  1 20:30:37 tom-laptop kernel: [  701.298756] Node 0 DMA: 0*4kB 0*8kB 1*16kB (E) 2*32kB (UE) 2*64kB (U) 2*128kB (UE) 2*256kB (UE) 0*512kB 2*1024kB (UE) 2*2048kB (ME) 2*4096kB (M) = 15312kB
Jun  1 20:30:37 tom-laptop kernel: [  701.298763] Node 0 DMA32: 6*4kB (UE) 119*8kB (UME) 108*16kB (UM) 70*32kB (UME) 36*64kB (UM) 24*128kB (UME) 11*256kB (UME) 8*512kB (UME) 4*1024kB (UME) 5*2048kB (ME) 3*4096kB (UM) = 43856kB
Jun  1 20:30:37 tom-laptop kernel: [  701.298770] Node 0 Normal: 543*4kB (UM) 435*8kB (UME) 191*16kB (UME) 110*32kB (UM) 36*64kB (UM) 11*128kB (UME) 2*256kB (UE) 19*512kB (UME) 4*1024kB (E) 0*2048kB 0*4096kB = 30276kB
Jun  1 20:30:37 tom-laptop kernel: [  701.298778] Node 0 hugepages_total=0 hugepages_free=0 hugepages_surp=0 hugepages_size=1048576kB
Jun  1 20:30:37 tom-laptop kernel: [  701.298779] Node 0 hugepages_total=0 hugepages_free=0 hugepages_surp=0 hugepages_size=2048kB
Jun  1 20:30:37 tom-laptop kernel: [  701.298779] 908012 total pagecache pages
Jun  1 20:30:37 tom-laptop kernel: [  701.298782] 213 pages in swap cache
Jun  1 20:30:37 tom-laptop kernel: [  701.298783] Swap cache stats: add 7883738, delete 7882708, find 2719854/3248471
Jun  1 20:30:37 tom-laptop kernel: [  701.298784] Free swap  = 14905852kB
Jun  1 20:30:37 tom-laptop kernel: [  701.298784] Total swap = 15998972kB
Jun  1 20:30:37 tom-laptop kernel: [  701.298785] 1018650 pages RAM
Jun  1 20:30:37 tom-laptop kernel: [  701.298785] 0 pages HighMem/MovableOnly
Jun  1 20:30:37 tom-laptop kernel: [  701.298786] 39250 pages reserved
Jun  1 20:30:37 tom-laptop kernel: [  701.298786] 0 pages cma reserved
Jun  1 20:30:37 tom-laptop kernel: [  701.298787] 0 pages hwpoisoned
Jun  1 20:30:37 tom-laptop kernel: [  701.298789] SLUB: Unable to allocate memory on node -1, gfp=0xc0(__GFP_IO|__GFP_FS)
Jun  1 20:30:37 tom-laptop kernel: [  701.298790]   cache: radix_tree_node, object size: 576, buffer size: 584, default order: 2, min order: 0
Jun  1 20:30:37 tom-laptop kernel: [  701.298791]   node 0: slabs: 735, objs: 20475, free: 0

```

**Steps to reproduce:**
Open scene linked below and start only that scene in the editor.

**Minimal reproduction project:**
Running only this very simple scene seems to produce it.
https://gitlab.com/ScrambleSim/Scramble/blob/feature/asset-import/Scramble-client/assets/entities/characters/pilot/pilot.tscn

**Comment by MrMinimal** [comment] 2019-06-01 19:02
I suspect there not to be enough VRAM but I lack the skills to tell how much usage I have by my application.

**Comment by MrMinimal** [comment] 2019-06-04 20:30
After a long freeze I got the following dump in the terminal:
```bash
OpenGL ES 3.0 Renderer: Mesa DRI Intel(R) HD Graphics 615 (Kaby Lake GT2) 
handle_crash: Program crashed with signal 11
Dumping the backtrace. Please include this when reporting the bug on https://github.com/godotengine/godot/issues
[1] /lib/x86_64-linux-gnu/libc.so.6(+0x43f60) [0x7f6582afef60] (??:0)
[2] /usr/lib/x86_64-linux-gnu/dri/i965_dri.so(+0x19a747) [0x7f657e769747] (??:0)
[3] /usr/lib/x86_64-linux-gnu/dri/i965_dri.so(+0x19cbc8) [0x7f657e76bbc8] (??:0)
[4] /usr/lib/x86_64-linux-gnu/dri/i965_dri.so(+0x1a01c6) [0x7f657e76f1c6] (??:0)
[5] /usr/share/godot/3.1.1/Godot_v3.1.1-stable_x11.64() [0xbde3a2] (<artificial>:?)
[6] /usr/share/godot/3.1.1/Godot_v3.1.1-stable_x11.64() [0x231eb57] (<artificial>:?)
[7] /usr/share/godot/3.1.1/Godot_v3.1.1-stable_x11.64() [0x1708388] (??:?)
[8] /usr/share/godot/3.1.1/Godot_v3.1.1-stable_x11.64() [0x17091a6] (<artificial>:?)
[9] /usr/share/godot/3.1.1/Godot_v3.1.1-stable_x11.64() [0x21c2170] (??:?)
[10] /usr/share/godot/3.1.1/Godot_v3.1.1-stable_x11.64() [0xe35d33] (<artificial>:?)
[11] /usr/share/godot/3.1.1/Godot_v3.1.1-stable_x11.64() [0x7c53d4] (??:?)
[12] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xeb) [0x7f6582ae1b6b] (??:0)
[13] /usr/share/godot/3.1.1/Godot_v3.1.1-stable_x11.64() [0x7d2c1e] (??:?)
-- END OF BACKTRACE --
Aborted (core dumped)

```

**Comment by MrMinimal** [comment] 2019-06-04 20:41
This only happens on GLES 3.0, GLES 2.0 works fine. The project used to work before on GLES 3.0 though.

**Comment by KoBeWi** [comment] 2020-07-30 23:45
Can anyone still reproduce this bug in [Godot 3.2.3 rc2](https://godotengine.org/article/release-candidate-godot-3-2-3-rc-2) or any later release?

**Comment by KoBeWi** [comment] 2020-09-28 22:27
Closing due to lack of update. Please comment if you can still reproduce this issue in the latest stable version of Godot.

**Closed by KoBeWi** 2020-09-28 22:27 UTC
Labels: bug, platform:linuxbsd
