### ISSUE TITLE
Vulkan: Adding a mesh without material causes other meshes to be rendered improperly (disappear)

### ISSUE THREAD

**Issue by chosia** [godotengine/godot#59870] opened 2022-04-04 12:37 UTC
### Godot version

4.0.alpha5

### System information

MacOS 10.15.7

### Issue description

A mesh without a  material added to the scene can cause other meshes to 'disappear'. Possibly a duplicate of #51898, but I can't judge it.

### Steps to reproduce

Remove material and material override from the 'pill' in the attached project. Also see the README.txt in the attached project.

### Minimal reproduction project

[material_not_set_bug.zip](https://github.com/godotengine/godot/files/8409719/material_not_set_bug.zip)

**Comment by Calinou** [comment] 2022-04-04 12:39
Which hardware (and GPU) are you using? Can you post a video recording?

**Comment by chosia** [comment] 2022-04-04 12:40
<img width="587" alt="Screenshot 2022-04-04 at 14 40 23" src="https://user-images.githubusercontent.com/29225521/161545577-5a334314-5b93-403b-9a45-b9ce478e9ffe.png">

Here are my hardware specs. Will upload a screencast in a moment.

**Comment by chosia** [comment] 2022-04-04 12:52
https://user-images.githubusercontent.com/29225521/161547502-e75581b7-7f65-4262-860f-cf9fed866e70.mp4

Removing the material from the 'pill' causes the 'column' to be rendered black in editor.

**Comment by chosia** [comment] 2022-04-04 12:55
Running with a pill with material:

https://user-images.githubusercontent.com/29225521/161548268-a9c63ff0-5085-441f-a0ad-4a2d85d50179.mp4

Running with a pill without material:

https://user-images.githubusercontent.com/29225521/161548275-7b9e0fb1-8935-4ca2-b57d-52185a333647.mp4

**Comment by snougo** [comment] 2022-04-09 10:00
this issue already apperas before alpha5 and I got this issue before alpha1

![Screen Shot 2022-04-09 at 5 57 18 PM](https://user-images.githubusercontent.com/64188282/162566962-4e743f40-52f4-4937-b5be-3d5594bca67c.png)

**Comment by Marco-MP88** [comment] 2022-04-15 07:12
got the same issue on M1 Pro but your post makes me believe this is not a GPU architecture but a MoltonVK/Metal related issue.

**Comment by Marco-MP88** [comment] 2022-04-15 07:14
Haven't tested it but I think the issue should be able to be replicated using a Mac OS VM if no apple hardware is available to developers.

**Comment by Calinou** [comment] 2022-04-15 13:19
Duplicate of https://github.com/godotengine/godot/issues/51898.

**Closed by Calinou** 2022-04-15 13:19 UTC
Labels: bug, platform:macos, topic:rendering, needs testing, regression, topic:3d
