### ISSUE TITLE
Project manager reset occasionally 

### ISSUE THREAD

**Issue by ZX-WT** [godotengine/godot#10058] opened 2017-08-03 04:10 UTC
**Operating system or device - Godot version:**
mint 17.2 / 2.14 beta 

**Issue description:**

The project manager will reset suddenly, when I start godot and the project list will become empty, all the previous projects are not shown. The language may also reset. I experience this issue in previous version as well.

**Steps to reproduce:**
start godot and it may happen suddenly.

**Link to minimal example project:**

**Comment by Noshyaar** [comment] 2017-08-03 05:40
This might happen if the config folder (~/.godot) is deleted, or shared between versions. (like switching branch and rebuild, and the config file is  uncompatible)

You sure you didn't do anything like that?

**Comment by RandomShaper** [comment] 2017-08-03 07:52
Are you running some always-watching backup software? It happened to me with one from a certain vendor. I switched to another and since then I haven't been bitten by this issue anymore.

Well, it may be caused also by a paranoid antivirus.

**Comment by MarianoGnu** [comment] 2017-08-04 10:43
You probably have your projects in a different partition than your system, if this partition is not mounted then the projects aren't found and godot removes them from the list

**Comment by golddotasksquestions** [comment] 2019-05-19 12:04
I have this issue too. (Win7) My Project list resets (empty list) and I have to reimport all projects. 
It seems impossible to replicate reliably, but I have noticed it happening when "Quit to Project List".

Note none of the above proposed causes seem to apply:

- Config folder was not deleted, branches were not switched or rebuild.
- I'm not running a backup software.
- My projects are on the same partition like my system.

**Comment by Zireael07** [comment] 2019-05-19 12:45
Looks like my issue #27124 is duplicate of this one.

I haven't deleted config folder and I'm not building from source nor using a backup software.

**Comment by akien-mga** [comment] 2019-05-20 11:19
Closing as superseded by #27124, since this issue is quite old and the bug back then might be different from the current issue.

**Closed by akien-mga** 2019-05-20 11:19 UTC
Labels: discussion
