### ISSUE TITLE
optrirun crash

### ISSUE THREAD

**Issue by skarmiglione** [godotengine/godot#10802] opened 2017-08-31 04:52 UTC
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
optimus nvidia/intel.
Linux Mint 18.2

**Issue description:**

it just crash with a empty project what i am starting

**Steps to reproduce:**
 optirun ./Godot_v2.1.3-stable_x11.64
WARNING: initialize: Could not find cursor theme
   At: platform/x11/os_x11.cpp:346.
ERROR: load_image: Error opening file: /home/cmkat/cosmogatokat/Herramientas/creacion_de_juegos/godot/juegos godot 2.1/projectleek-master/icon.png
   At: core/io/image_loader.cpp:53.
ERROR: load_image: Error opening file: /home/cmkat/cosmogatokat/Herramientas/creacion_de_juegos/godot/juegos hecho con godot 2.0/marine_treasure_hunter-master/icon.png
   At: core/io/image_loader.cpp:53.
WARNING: _png_warn_function: iCCP: known incorrect sRGB profile
   At: drivers/png/image_loader_png.cpp:66.
WARNING: _png_warn_function: iCCP: known incorrect sRGB profile
   At: drivers/png/image_loader_png.cpp:66.
WARNING: _png_warn_function: iCCP: known incorrect sRGB profile
   At: drivers/png/image_loader_png.cpp:66.
WARNING: _png_warn_function: iCCP: known incorrect sRGB profile
   At: drivers/png/image_loader_png.cpp:66.
WARNING: _png_warn_function: iCCP: known incorrect sRGB profile
   At: drivers/png/image_loader_png.cpp:66.
OPENING: /home/cmkat/cosmogatokat/2d/balloon fight (::home::cmkat::cosmogatokat::2d::balloon fight)
WARNING: initialize: Could not find cursor theme
   At: platform/x11/os_x11.cpp:346.
cmkat@saturnikx ~/cosmogatokat/Herramientas/creacion_de_juegos/godot $ XIO:  fatal IO error 2 (No such file or directory) on X server ":8"
      after 53 requests (53 known processed) with 0 events remaining

**Link to minimal example project:**

**Comment by akien-mga** [comment] 2017-08-31 05:33
Duplicate of #67.

**Closed by akien-mga** 2017-08-31 05:33 UTC
