### ISSUE TITLE
TAA + SSAA and/or MSAA 3D distorts/corrupts editor and yield black screen on run

### ISSUE THREAD

**Issue by CoreTaxxe** [godotengine/godot#65479] opened 2022-09-07 14:57 UTC
### Godot version

4.0-alpha16

### System information

Windows 11, Vulkan, RTX 3070 V. 516.94

### Issue description

Enabling TAA with either (or both) MSAA 3D or SSAA cause the editor to completely distort/corrupt the 3D space and yield in a black screen on scene run. Effect is less pronounced with lower settings for MSAA 3d or SSAA. 

Edit : Cannot reliably reproduce the issue with SSAA + TAA but every time with MSAA 3D + TAA

![image](https://user-images.githubusercontent.com/47256718/188908630-3c6cb005-777f-4c3b-848b-09a34b85151c.png)

After restarting the editor the 3D space remains black until you change the tabs/open a new tab.

![image](https://user-images.githubusercontent.com/47256718/188910271-1ef4b7bb-6b65-4bf3-a6ba-4e699fefe96d.png)

Console constantly repeats these errors  :
```
  Immediate draw list is already inactive.
  Invalid framebuffer format attachment(2), in pass (0), if an attachment is marked as multisample, all of them should be multisample and use the same number of samples.
  ./servers/rendering/renderer_rd/framebuffer_cache_rd.h:170 - Condition "rid.is_null()" is true. Returning: rid
  drivers/vulkan/rendering_device_vulkan.cpp:4204 - Condition "!framebuffer" is true. Returning: INVALID_ID
  drivers/vulkan/rendering_device_vulkan.cpp:7318 - Condition "!framebuffer" is true. Returning: INVALID_ID
  drivers/vulkan/rendering_device_vulkan.cpp:7640 - Condition "!dl" is true.
  drivers/vulkan/rendering_device_vulkan.cpp:7640 - Condition "!dl" is true.
  drivers/vulkan/rendering_device_vulkan.cpp:7640 - Condition "!dl" is true.
  drivers/vulkan/rendering_device_vulkan.cpp:7689 - Condition "!dl" is true.
  drivers/vulkan/rendering_device_vulkan.cpp:7713 - Condition "!dl" is true.
  drivers/vulkan/rendering_device_vulkan.cpp:4081 - Condition "!E" is true. Returning: TEXTURE_SAMPLES_1
  Mismatch fragment shader output mask (5) and framebuffer color output mask (0) when binding both in render pipeline.
  servers/rendering/renderer_rd/pipeline_cache_rd.cpp:60 - Condition "pipeline.is_null()" is true. Returning: RID()
  drivers/vulkan/rendering_device_vulkan.cpp:7640 - Condition "!dl" is true.
  drivers/vulkan/rendering_device_vulkan.cpp:7747 - Condition "!dl" is true.
  drivers/vulkan/rendering_device_vulkan.cpp:7765 - Condition "!dl" is true.
  drivers/vulkan/rendering_device_vulkan.cpp:7689 - Condition "!dl" is true.
  drivers/vulkan/rendering_device_vulkan.cpp:4081 - Condition "!E" is true. Returning: TEXTURE_SAMPLES_1
  Mismatch fragment shader output mask (5) and framebuffer color output mask (0) when binding both in render pipeline.
  servers/rendering/renderer_rd/pipeline_cache_rd.cpp:60 - Condition "pipeline.is_null()" is true. Returning: RID()
  drivers/vulkan/rendering_device_vulkan.cpp:7640 - Condition "!dl" is true.
  drivers/vulkan/rendering_device_vulkan.cpp:7747 - Condition "!dl" is true.
  drivers/vulkan/rendering_device_vulkan.cpp:7765 - Condition "!dl" is true.
  drivers/vulkan/rendering_device_vulkan.cpp:7689 - Condition "!dl" is true.
  drivers/vulkan/rendering_device_vulkan.cpp:4081 - Condition "!E" is true. Returning: TEXTURE_SAMPLES_1
  Mismatch fragment shader output mask (5) and framebuffer color output mask (0) when binding both in render pipeline.
  servers/rendering/renderer_rd/pipeline_cache_rd.cpp:60 - Condition "pipeline.is_null()" is true. Returning: RID()
  drivers/vulkan/rendering_device_vulkan.cpp:7640 - Condition "!dl" is true.
  drivers/vulkan/rendering_device_vulkan.cpp:7747 - Condition "!dl" is true.
  drivers/vulkan/rendering_device_vulkan.cpp:7765 - Condition "!dl" is true.
  drivers/vulkan/rendering_device_vulkan.cpp:7689 - Condition "!dl" is true.
  drivers/vulkan/rendering_device_vulkan.cpp:4081 - Condition "!E" is true. Returning: TEXTURE_SAMPLES_1
  Mismatch fragment shader output mask (5) and framebuffer color output mask (0) when binding both in render pipeline.
  servers/rendering/renderer_rd/pipeline_cache_rd.cpp:60 - Condition "pipeline.is_null()" is true. Returning: RID()
  drivers/vulkan/rendering_device_vulkan.cpp:7640 - Condition "!dl" is true.
  drivers/vulkan/rendering_device_vulkan.cpp:7747 - Condition "!dl" is true.
  drivers/vulkan/rendering_device_vulkan.cpp:7765 - Condition "!dl" is true.
  drivers/vulkan/rendering_device_vulkan.cpp:7689 - Condition "!dl" is true.
  drivers/vulkan/rendering_device_vulkan.cpp:4081 - Condition "!E" is true. Returning: TEXTURE_SAMPLES_1
  Mismatch fragment shader output mask (5) and framebuffer color output mask (0) when binding both in render pipeline.
  servers/rendering/renderer_rd/pipeline_cache_rd.cpp:60 - Condition "pipeline.is_null()" is true. Returning: RID()
  drivers/vulkan/rendering_device_vulkan.cpp:7640 - Condition "!dl" is true.
  drivers/vulkan/rendering_device_vulkan.cpp:7747 - Condition "!dl" is true.
  drivers/vulkan/rendering_device_vulkan.cpp:7765 - Condition "!dl" is true.
  Immediate draw list is already inactive.

```

### Steps to reproduce

1. Create new or use an existing project (empty project is sufficient to reproduce.)
2. Enable TAA with MSAA 3d and or SSAA

**Comment by Calinou** [comment] 2022-09-07 16:45
Can you reproduce this on previous 4.0 alphas (starting from alpha10 or so)? You can download them [here](https://downloads.tuxfamily.org/godotengine/4.0/).

**Comment by CoreTaxxe** [comment] 2022-09-07 17:48
❌  can **NOT** be reproduced
✅ can be reproduced

1. alpha 10 ❌ 
2. alpha 11 ❌ 
3. alpha 12 ❌ 
4. alpha 13 ❌ 
5. alpha 14 ❌ 
6. alpha 15 ❌ 

7. alpha 16 ✅ 


looks like regression

**Comment by akien-mga** [comment] 2022-09-07 20:01
CC @Geometror @clayjohn @BastiaanOlij

**Comment by Geometror** [comment] 2022-09-08 02:18
That's strange, this was the exact issue I found when testing #63901, but I can confirm @BastiaanOlij fixed that before it was merged.

**Comment by BastiaanOlij** [comment] 2022-09-08 23:21
Is it still broken in master? I'm not sure if #63901 made it into alpha 16?

**Comment by CoreTaxxe** [comment] 2022-09-09 15:39
Still broken in master.

**Comment by JoanPotatoes2021** [comment] 2022-09-11 16:36
Found a lead, the bug is reproducible only on MSAA levels > than 2x, I can only reproduce the bug on MSAA 4x and 8x, but on 2x it works just fine, using `v4.0.alpha16.official` [86dd3f312]
![msaaxtaa](https://user-images.githubusercontent.com/88800565/189538870-d1927f11-c939-4415-b30a-e2ab8ec294e1.gif)

**Comment by JoanPotatoes2021** [comment] 2022-09-11 17:30
Also can't reproduce the issue if the Rendering Back End is changed to `Forward Mobile` in the project settings, TAA works with MSAA levels 2x,4x and 8x,

![msaaxtaa1](https://user-images.githubusercontent.com/88800565/189540887-a259702e-5ef8-4767-a075-ea32301148e7.gif)

I don't write c++ though :neckbeard: , but could it be the `texture_samples = RD : :TEXTURE_SAMPLES_1;`? https://github.com/godotengine/godot/pull/63901/files#diff-c4cb62e4cc7c7024ba2b72b07ae7c7c849f63b0c0fa0acbed94c45e378e27b29

In the mobile cluster https://github.com/godotengine/godot/pull/63901/files#diff-fb99395dba48cfb81f7e21da2a4f1e99fda0391e279402bf910ccee6a54eca11 it is assigned like:

```
i target_size = RD::get_singleton()->texture_size(p_target_buffer);
		const RD::TextureSamples ts[RS::VIEWPORT_MSAA_MAX] = {
			RD::TEXTURE_SAMPLES_1,
			RD::TEXTURE_SAMPLES_2,
			RD::TEXTURE_SAMPLES_4,
			RD::TEXTURE_SAMPLES_8,
		};
```

**Comment by BastiaanOlij** [comment] 2022-09-11 23:35
The mobile renderer doesn't have TAA support so it won't be effected :)

The `texture_samples = RD : :TEXTURE_SAMPLES_1;` just sets a default, the actual value is assigned here: 
https://github.com/godotengine/godot/blob/master/servers/rendering/renderer_rd/forward_clustered/render_forward_clustered.cpp#L140

That configure method should be called when the MSAA setting changes but I've got something to go on now so let me see if I can reproduce the same behavior over here.

**Comment by BastiaanOlij** [comment] 2022-09-12 01:09
Really really dumb typo. Thanks for your testing @JoanPotatoes2021 , pointed me in the right direction :)

**Closed** 2022-09-12 05:22 UTC
Labels: bug, topic:rendering, regression, topic:3d
