### ISSUE TITLE
Type casting in array .map doesn't work

### ISSUE THREAD

**Issue by Ughuuu** [godotengine/godot#73309] opened 2023-02-14 21:21 UTC
### Godot version

4.0 R 3

### System information

Macos M1

### Issue description

I'm trying to return an array of nodes of certain types from a function. Initially they are of `Array[Node]` type, and I want to cast them to `Array[Polygon2D]` type.
When I do this in `.map` function, it doesn't work as expected. It gives just `Array` type.
The function return shows:
`Trying to return an array of type "Array" where expected return type is "Array[Polygon2D]"`
If I do it in a for loop, it works.

Expected Behaviour

Not to give error when using map and have same effect as when using for loop as map should change the initial array.

I also tried using `arr as Array[Polygon2D]` on mapped array, but still nothing.

### Steps to reproduce

```

func bug() -> Array[Polygon2D]:
	var arr := get_children() \
		.filter(func(node): return node is Polygon2D) \
		.map(func(node): return node as Polygon2D)
	return arr

func works() -> Array[Polygon2D]:
	var arr := get_children() \
		.filter(func(node): return node is Polygon2D)

	var polygons: Array[Polygon2D] = []
	for node in arr:
		polygons.append(node as Polygon2D)
	return polygons

# Called when the node enters the scene tree for the first time.
func _ready():
	works()
	bug()
```

### Minimal reproduction project

[bug-map-type.zip](https://github.com/godotengine/godot/files/10736944/bug-map-type.zip)

**Comment by KoBeWi** [comment] 2023-02-14 21:36
Duplicate of #72566
> var polygons: Array[Polygon2D] = []
	for node in arr:
		polygons.append(node as Polygon2D)
	return polygons

Can be changed to
```GDSript
var polygons: Array[Polygon2D] = []
polygons.assign(arr)
return polygons
```

**Closed by KoBeWi** 2023-02-14 21:36 UTC
