### ISSUE TITLE
area_entered signal not triggered when toggling monitorable

### ISSUE THREAD

**Issue by eimlav** [godotengine/godot#79464] opened 2023-07-14 14:05 UTC
### Godot version

4.1.stable

### System information

Godot v4.1.stable - macOS 12.6.5 - Vulkan (Forward+) - integrated Intel(R) Iris(TM) Graphics 6100 - Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz (4 Threads)

### Issue description

When toggling the `monitorable` state of an Area2D that is overlapping another Area2D that has `monitoring` enabled (with collisions layers/masks setup correctly), the area entered event is not fired for the second Area2D. The only way to re-trigger the event is to move the first Area2D so it is no longer overlapping and to then re-collide the edges of the areas.

My expectation here is that when I re-enable the `monitorable` property of the first Area2D it should trigger the `area_entered` signal of the second Area2D when they are overlapping.

It's possible that this could be completely intentional behaviour but I was not able to find any documentation to state whether this is the case or not.

### Steps to reproduce

1. Setup Area2D (area 1) with collision layer 1 and no collision mask
2. Setup another Area2D (area 2) with no collision layer and collision mask 1
3. Connect area 2 `area_entered` signal to any kind of debug function
4. Overlap the two Area2Ds
5. Toggle the `monitorable` state of area 1
6. The `area_entered` signal is never triggered.

### Note

I also decided to do a test with a flipped scenario where instead of toggling area 1's `monitorable` state, I toggled area 2's `monitoring` state. This produced unusual results in that on a rare occasion, the `area_entered` event would get triggered.

### Minimal reproduction project

N/A

**Comment by AThousandShips** [comment] 2023-07-14 14:10
Well the documentation says:
> Emitted when the received area enters this area

And 
> If `true`, the area detects bodies or areas entering and exiting it.

So the expectation isn't based on anything in the documentation

Could possibly add a clarification if it's considered unclear or unexpected

**Comment by KoBeWi** [comment] 2023-07-14 14:28
Duplicate of #71489

**Closed by KoBeWi** 2023-07-14 14:28 UTC
Labels: discussion, topic:physics
