### ISSUE TITLE
ERROR: Vulkan: Cannot submit graphics queue. Error code: VK_ERROR_DEVICE_LOST

### ISSUE THREAD

**Issue by BlagoPenev** [godotengine/godot#74876] opened 2023-03-13 19:49 UTC
### Godot version

Godot Engine v4.0.stable.official

### System information

Windows 11 , AMD Radeon RX 5700 XT

### Issue description

For me it happens on a specific project, big one. It is random crash. I can work for a day without a problem, the next day can crash every 1-5 minutes. It crashes the GPU drivers. Only on Forward+

### Steps to reproduce

Open a project with Forward+ , for me only on big projects, it is not necessary to play the game, just leave it on the editor, so it is not gdscript related, at some point starts crashing

### Minimal reproduction project

Open a project with Forward+ , for me only on big projects, it is not necessary to play the game, just leave it on the editor, so it is not gdscript related, at some point starts crashing

**Comment by clayjohn** [comment] 2023-03-13 20:01
Duplicate of https://github.com/godotengine/godot/issues/71929

This issue has been reported a number of times as it appears in a number of different ways. Since in your case you can't provide an MRP or many details (as it only happens in a large project) I will close this issue and continue tracking the issue in the open issues with more details. 

Keep an eye on https://github.com/godotengine/godot/issues/71929 if you want to follow the progress towards fixing this issue.

**Closed by clayjohn** 2023-03-13 20:01 UTC
