### ISSUE TITLE
Group list in project manager

### ISSUE THREAD

**Issue by eon-s** [godotengine/godot#18861] opened 2018-05-14 10:52 UTC
**Godot version:**
Any

**Issue description:**
Groups are a great tool, but is easy to misspell them, or forget the correct name, this makes them need an external tool for keeping the group list, in particular in mid/big projects.

Would be interesting if groups can be managed in a central way on the project manager, like physics layers, and the node dock let you pick one or more of these in the list, it can be also used for autocomplete group names when writing `get_nodes_in_group`, `is_in_group` and similar functions.

This won't stop people from adding things to their own groups by code but may improve a lot the editor UX and completion in this subject.

**Comment by Zylann** [comment] 2018-05-14 12:46
Duplicate of https://github.com/godotengine/godot/issues/5744

**Closed** 2018-05-14 12:53 UTC
