### ISSUE TITLE
InputEventAction shortcuts have weird tooltips

### ISSUE THREAD

**Issue by Jummit** [godotengine/godot#28914] opened 2019-05-15 14:18 UTC
**Godot version:**
3.1.1

**Issue description:**
InputEventAction shortcuts don't have good tooltips.
![action#](https://user-images.githubusercontent.com/28286961/57782676-03a6af80-772d-11e9-93ba-20f8d611eb71.png)

**Steps to reproduce:**
Create a new button with an InputEventAction shortcut, launch the game and hover over it.

**Comment by CowThing** [comment] 2019-05-15 16:17
Somewhat related to #23617 and my comment https://github.com/godotengine/godot/pull/23731#issuecomment-439400016

Shortcut tooltips use the `as_text()` function on the input to convert it to text for the tooltip to display. The issue is that `InputEventAction`'s `as_text()` function does not create a useful description of what inputs trigger the event. But other inputs like `InputEventKey` do create nice readable strings.

Is it even possible to make `InputEventAction` create a readable string describing what inputs trigger it? Since it can have many different inputs assigned to it.

**Comment by KoBeWi** [comment] 2019-05-20 10:31
Maybe it could display the first assigned key (or joypad button if connected).

**Comment by sszigeti** [comment] 2019-07-20 10:30
I think it should be possible to disable these tooltips in case they're supposed to be replaced by a custom tooltip feature (with animation, etc.).

**Comment by akien-mga** [comment] 2019-07-20 10:47
It *is* possible to disable these tooltips as per #23617 linked above.

**Comment by madmiraal** [comment] 2021-05-23 09:18
Fixed on master with #43660.

**Closed by madmiraal** 2021-05-23 09:18 UTC
Labels: enhancement, topic:core, topic:input
