### ISSUE TITLE
Reflection setup crash

### ISSUE THREAD

**Issue by AndreaCatania** [godotengine/godot#45555] opened 2021-01-29 08:58 UTC
**Godot version:**
fbb4742377326c25a6f804fb497186b4d461aa1c

**OS/device including version:**
Fedora 33

**Issue description:**
When I open the game, after few frames the game crashes: 
```
handle_crash: Program crashed with signal 11
Dumping the backtrace. Please include this when reporting the bug on https://github.com/godotengine/godot/issues
[1] /lib64/libc.so.6(+0x3da60) [0x7ffff7730a60] (??:0)
[2] RendererSceneRenderRD::_setup_reflections(PagedArray<RID> const&, Transform const&, RID) (/home/andrea/Workspace/momento/wander/source/engine/godot/servers/rendering/renderer_rd/renderer_scene_render_rd.cpp:6127)
[3] RendererSceneRenderRD::render_scene(RID, Transform const&, CameraMatrix const&, bool, PagedArray<RendererSceneRender::GeometryInstance*> const&, PagedArray<RID> const&, PagedArray<RID> const&, PagedArray<RID> const&, PagedArray<RID> const&, PagedArray<RID> const&, RID, RID, RID, RID, RID, int, float) (/home/andrea/Workspace/momento/wander/source/engine/godot/servers/rendering/renderer_rd/renderer_scene_render_rd.cpp:7392)
[4] RendererSceneCull::_render_scene(RID, Transform, CameraMatrix const&, bool, RID, RID, RID, RID, RID, int, float) (/home/andrea/Workspace/momento/wander/source/engine/godot/servers/rendering/renderer_scene_cull.cpp:2789 (discriminator 4))
[5] RendererSceneCull::render_camera(RID, RID, RID, Vector2, float, RID) (/home/andrea/Workspace/momento/wander/source/engine/godot/servers/rendering/renderer_scene_cull.cpp:2151 (discriminator 2))
[6] RendererViewport::_draw_3d(RendererViewport::Viewport*, XRInterface::Eyes) (/home/andrea/Workspace/momento/wander/source/engine/godot/servers/rendering/renderer_viewport.cpp:88)
[7] RendererViewport::_draw_viewport(RendererViewport::Viewport*, XRInterface::Eyes) (/home/andrea/Workspace/momento/wander/source/engine/godot/servers/rendering/renderer_viewport.cpp:136)
[8] RendererViewport::draw_viewports() (/home/andrea/Workspace/momento/wander/source/engine/godot/servers/rendering/renderer_viewport.cpp:567)
[9] RenderingServerDefault::draw(bool, double) (/home/andrea/Workspace/momento/wander/source/engine/godot/servers/rendering/rendering_server_default.cpp:115)
[10] RenderingServerWrapMT::draw(bool, double) (/home/andrea/Workspace/momento/wander/source/engine/godot/servers/rendering/rendering_server_wrap_mt.cpp:93)
[11] Main::iteration() (/home/andrea/Workspace/momento/wander/source/engine/godot/main/main.cpp:2508)
[12] OS_LinuxBSD::run() (/home/andrea/Workspace/momento/wander/source/engine/godot/platform/linuxbsd/os_linuxbsd.cpp:261)
[13] /home/andrea/Workspace/momento/wander/source/engine/godot/bin/godot.linuxbsd.tools.64(main+0x135) [0x1f189bb] (/home/andrea/Workspace/momento/wander/source/engine/godot/platform/linuxbsd/godot_linuxbsd.cpp:60)
[14] /lib64/libc.so.6(__libc_start_main+0xf2) [0x7ffff771b1e2] (??:0)
[15] /home/andrea/Workspace/momento/wander/source/engine/godot/bin/godot.linuxbsd.tools.64(_start+0x2e) [0x1f187ce] (??:?)
-- END OF BACKTRACE --
```

This issue seems a regression of this commit 099dee35f47db3e293cb8e60287ffe6a44f3d5d4. I've noticed that if I move the spawn point elsewhere the crash doesn't occurs. This seems, somehow, related to the frame rate. Probably some race condition?

**Comment by clayjohn** [comment] 2021-01-29 15:05
Duplicate of https://github.com/godotengine/godot/issues/45384

**Closed by clayjohn** 2021-01-29 15:05 UTC
Labels: bug, regression, topic:rendering
