### ISSUE TITLE
[3.0] Mouse cursor stuck in "resizing" icon when the mouse exits window border

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#8043] opened 2017-03-16 01:48 UTC
Tested on Godot master 3ceefab232604b09d3fff843c24a13e99f50912b
Windows 10 64 bits

Repro steps:
1) Open Editor Settings (or any other resizeable editor window)
2) Move the mouse to a border, see it changes to a resizing icon
3) Move the mouse away from the window: notice the cursor stays a resizing icon (wrong behaviour).
4) Click outside of the window: notice the cursor becomes normal again

When doing 3), I expected the mouse to go back to a normal pointer.

**Comment by akien-mga** [comment] 2017-03-16 06:24
Duplicate of #7622.

**Closed by akien-mga** 2017-03-16 06:24 UTC
