### ISSUE TITLE
C# script Export variables don't appear in inspector until the engine is restarted

### ISSUE THREAD

**Issue by realManix** [godotengine/godot#15831] opened 2018-01-18 02:40 UTC
**Godot version:**

Godot 3.0 RC 1

**OS/device including version:**

Windows 10

**Issue description:**

When you add a C# script with "Export variables" to a node, the variables will not show in the inspector even after you build the project. The only way to fix this right now seems to be to restart the engine.

**Steps to reproduce:**
Create a project, add a node, add a C# script to that node, add an [Export] variable to the node and try building the project. Check the inspector.

**Minimal reproduction project:**

**Comment by akien-mga** [comment] 2018-01-18 08:48
Duplicate of #12518.

**Closed by akien-mga** 2018-01-18 08:48 UTC
