### ISSUE TITLE
Parser Error: Expected ')' in expression Input GODOT 3.0

### ISSUE THREAD

**Issue by yuyoDev** [godotengine/godot#9373] opened 2017-06-25 20:47 UTC
**Operating system or device - Godot version:**
Archlinx 64

**Issue description:**

Apparently the new input syntax does not work in linux.

**Steps to reproduce:**
This code dont work
func _input(event):
	if (event extends InputEventMouseMotion):
		print("this dont work!")

**Link to minimal example project:**

**Comment by karroffel** [comment] 2017-06-25 20:52
@yuyoDev For checking the type of a value you now need to use `is` instead of `extends`.

`extends` is still used for defining classes, just not for *checking* them. Duplicate of #9220

**Closed by karroffel** 2017-06-25 20:52 UTC

**Comment by yuyoDev** [comment] 2017-06-25 20:57
Thank you very much, apologies if it was something very silly, please
instruct me if it is necessary to answer these emails every time. Thanks
again.

2017-06-25 15:52 GMT-05:00 Thomas Herzog <notifications@github.com>:
