### ISSUE TITLE
Vulkan: SoftDynamicBody has artifacts due to incorrectly generated normals

### ISSUE THREAD

**Issue by gitscher** [godotengine/godot#57162] opened 2022-01-24 22:40 UTC
### Godot version

Godot 4.0 alpha 1

### System information

Windows 10 64bit Vulkan GeForce RTX 3080 Treiberversion 511.23

### Issue description

![SoftDynamicBody](https://user-images.githubusercontent.com/94169968/150876549-7fdc77de-53bc-4166-85d9-e45eddd693b6.png)
there are no artifacts in the editor.
When you start the scene then I have artifacts

### Steps to reproduce

start project and then play the project

### Minimal reproduction project

[SoftDynamicBody.zip](https://github.com/godotengine/godot/files/7929330/SoftDynamicBody.zip)

**Comment by Calinou** [comment] 2022-01-24 22:53
I can confirm this on commit fc09d783f (Linux, NVIDIA 495.46).

***Epilepsy warning:** The video below contains flashing.*

https://user-images.githubusercontent.com/180032/150878302-3f4aea43-99cc-4d01-8f32-1a01f628a85d.mp4

The artifacts are caused by incorrectly generated normals for the soft body, as the artifacts go away when you hide the DirectionalLight3D and set the Environment sky mode to **Clear Color** (so that lighting is uniform across all directions).

https://user-images.githubusercontent.com/180032/150878308-52278ca3-577c-4964-8477-214e02d05ada.mp4

**Comment by James103** [comment] 2022-02-09 21:21
I can reproduce both this and #56142 on Godot 4.0 alpha 2.

Are you able to bisect to find the first commit that broke normal generation (and therefore lighting) for SoftBody objects? If so, what commit introduced these artifacts?

**Comment by rburing** [comment] 2022-08-05 07:25
Duplicate of https://github.com/godotengine/godot/issues/56541, fixed by https://github.com/godotengine/godot/pull/63922.

**Closed by rburing** 2022-08-05 07:25 UTC
Labels: bug, topic:rendering, confirmed, regression, topic:3d
