### ISSUE TITLE
Editor treats custom repository host zips differently.

### ISSUE THREAD

**Issue by Gramps** [godotengine/godot#75712] opened 2023-04-05 19:49 UTC
I noticed that some plug-ins that have their repository host set as custom seem to have their zips treated differently.  For example, some plug-ins I have downloaded, the editor seems to ignore the base folders and just dump the contents into the project's root.  However, ones that have, say, Github listed as the repository host with a commit hash to get the zips, those unzip correctly.

In both cases, the editor seems to see the folders.  It just doesn't install correctly for some reason.  Not sure if this is intended, a bug, or what.

**Comment by Trey2k** [comment] 2023-04-05 20:05
My asset is having this issue, it uses a nightly.link: https://nightly.link/WeaselGames/godot_luaAPI/workflows/gdextension/main/godot_luaAPI.zip
ZIP:
![zip](https://user-images.githubusercontent.com/7241029/230196509-59d21506-d6a5-493d-903d-f79064f001ca.png)
In Editor:
![editor](https://user-images.githubusercontent.com/7241029/230196562-01384cb0-3a57-4c49-85d6-2600da3d2ab3.png)

**Comment by Gramps** [comment] 2023-04-05 20:12
So here are two screens; one using a custom repo host zip and mine using a Github commit hash zip:
![screenie1](https://user-images.githubusercontent.com/1097098/230198372-af63c067-0d57-499e-b8fb-30e650356c11.png)
![screenie2](https://user-images.githubusercontent.com/1097098/230198379-38e65062-77ab-4bc9-9ef0-3d25da53e159.png)

Upon making these screens, I find that the Github commit hash zips have the first folder as the commit hash-named folder which the editor ignore then installs those contents; which is the correct behavior for these kinds of zips.

However, the custom repo host zips do not have these hash-named folders and just directly store the files needed.  The editor treats them the same way and skips the first folder and installs the contents inside.  So it seems to be treating both the same way actually, though this is not really ideal for most custom repo zips I have seen.

**Comment by Gramps** [comment] 2023-04-05 20:14
It may be a good idea to make this behavior known to people posting custom repo plug-ins so they can package accordingly.  Or if this is a flag the editor understands, to treat the zips differently.

**Comment by Trey2k** [comment] 2023-04-05 21:19
To add to this, adding the a container folder manually also semi breaks manual imports, as it is included in this case.
![image](https://user-images.githubusercontent.com/7241029/230213828-691505a3-d387-4430-8fa6-14a4f6d1c8c2.png)

**Comment by ashtonmeuser** [comment] 2023-05-23 00:18
@Calinou Will this be fixed on the Godot side? It seems to me to be an issue firmly on the side of the Asset Library and not asset creators.

In short, the issue is that a ZIP file imported manually via Asset Library → Import is treated differently than _the exact same ZIP file_ specified in the Asset Library "Download Commit/URL" field. The asset is using the Custom repository host option.

Here's an affected asset: https://godotengine.org/asset-library/asset/1798. And here's the ZIP file it's downloading that can be manually imported: https://github.com/ashtonmeuser/godot-wasm/releases/download/v0.1.8-godot-3/godot-wasm.zip.

Attached are screenshots of (1) manually imported ZIP file via Asset Library → Import, (2) [asset](https://godotengine.org/asset-library/asset/1798) imported via Asset Library GUI, (3) download field in Asset Library "My Assets".

Note that the same ZIP file is used and results in different directory structures. It seems unfair and overly complicated to expect asset creators to build separate artifacts for the Asset Library GUI and for manual importing and for asset users to differentiate the two.

As for solutions, you've put yourself in a sticky situation as some asset creators may be accounting for this idiosyncrasy and you can't break their assets. The simplest solution, in my mind, is to add a new field in the Asset Store settings along the lines of "Include ZIP top-level directory" that defaults to false. Godot will have to read this setting and extract the asset accordingly.

<img width="680" alt="Screenshot 2023-05-22 at 4 50 55 PM" src="https://github.com/godotengine/godot/assets/7253863/34b90def-b690-4c77-920b-287ccf44420c">
<img width="680" alt="Screenshot 2023-05-22 at 4 51 42 PM" src="https://github.com/godotengine/godot/assets/7253863/f335ddcb-722d-4245-bcba-34d4040168fb">
<img width="689" alt="Screenshot 2023-05-22 at 4 53 27 PM" src="https://github.com/godotengine/godot/assets/7253863/c52c048b-b153-4684-a12d-c73757964419">

**Comment by Calinou** [comment] 2023-05-23 10:30
> It seems to me to be an issue firmly on the side of the Asset Library and not asset creators.

This means it's an issue with the editor code handling the ZIPs, not the asset library backend (which doesn't host any ZIP archives, let alone manipulate them).

**Comment by ashtonmeuser** [comment] 2023-05-23 16:07
Agreed that the root cause of this is not the Asset Library but rather the editor.

> In the interim, the easiest way to avoid this is having people submitting zips not from Github commits to add a new top-level folders that gets ignored.

This breaks manually importing a zip file. The problem with this issue is that the trivial fix for the Asset Library ZIP breaks that same ZIP for manual imports. The inconsistency in editor treatment of assets is the issue.

Perhaps the simplest solution is for the editor to do the same trimming of top-level directory for manually imported asset ZIPs. Then the solution is, as Gramps mentioned, adding a vestigial dir to the top of the ZIP that will be ignored. This means that editors prior to the fix will work with the Asset Library but not with manual imports which is the least impactful in my opinion.

**Comment by Trey2k** [comment] 2023-05-23 16:33
> Perhaps the simplest solution is for the editor to do the same trimming of top-level directory for manually imported asset ZIPs. Then the solution is, as Gramps mentioned, adding a vestigial dir to the top of the ZIP that will be ignored. This means that editors prior to the fix will work with the Asset Library but not with manual imports which is the least impactful in my opinion.

The issue is that would break downloading the repo as a zip and importing for people not using custom download links.

**Comment by ashtonmeuser** [comment] 2023-05-24 01:08
The difference in treatment of ZIP assets seems intentional and was added by @reduz in https://github.com/godotengine/godot/commit/8b1dcbfe4d92f9d7273bbd2f1eb805e5c508961a. Opening an Asset Library archive ([addon_editor_plugin.cpp#L392](https://github.com/godotengine/godot/blob/8b1dcbfe4d92f9d7273bbd2f1eb805e5c508961a/tools/editor/addon_editor_plugin.cpp#L392)) uses a depth of `1` while opening a manually downloaded archive ([addon_editor_plugin.cpp#L1032](https://github.com/godotengine/godot/blob/8b1dcbfe4d92f9d7273bbd2f1eb805e5c508961a/tools/editor/addon_editor_plugin.cpp#L1032)) uses the default depth of `0`.

The solution without a change to Godot is to package the Asset Library archive with an extra top-level directory. The caveat is that users can not download _asset_library.zip_ (or whatever you've named it) from the releases page and install it manually. They can, however, download the repo ZIP and install that manually (thus, a `.gitattributes` file is a good idea).

**Comment by YuriSizov** [comment] 2023-09-05 22:16
I've opened a PR that attempts to address this situation in a simple but graceful way: https://github.com/godotengine/godot/pull/81358

Let me know what you think!

**Comment by Gramps** [comment] 2023-09-05 22:18
Very cool.  I will dig into this tonight!  Thanks!

**Closed** 2023-09-08 22:00 UTC
Labels: discussion, topic:editor, confirmed, topic:assetlib, breaks compat
