### ISSUE TITLE
Android game stuck at boot splash after remaining few hours in background

### ISSUE THREAD

**Issue by shahediqbal13** [godotengine/godot#51021] opened 2021-07-29 15:10 UTC
### Godot version

3.3.2.stable.mono.official

### System information

Device Model: Redmi 7, Android 10, Ram: 3GB, CPU: Octa-core Max 1.8GHz

### Issue description

A simple game made in Godot 3.3.2 mono version get stuck at splash screen if I move this game to background and open few heavy resource intensive game and the again try to open my game from background task.

My Observation:
I am suspecting that while I open some other game it releases some variable of my Godot game from memory.
The issue is 100% reproducible in my device.

Here are few error highlight I am suspecting:
SensorManager(6330): sensor or listener is null
ActivityManager(2127): Process org.godotengine.androidtest (pid 6330) has died: fore TOP 
Perf(6608): Fail to get file list org.godotengine.androidtest
E/Perf(6608): getFolderSize() : Exception_1 = java.lang.NullPointerException: Attempt to get length of null array

Video Demonstration: 
https://user-images.githubusercontent.com/28184239/127512266-3d5fb1a1-b376-4168-b691-8f34cb33e03d.mp4

Log: 
[stuck_at_boot_splashlog.txt](https://github.com/godotengine/godot/files/6901386/stuck_at_boot_splashlog.txt)

### Steps to reproduce

1. Open the game made with Godot in an android device
2. Move the game to background by pressing home button
3. Now open few resource intensive games or keep your game in background for few hours
4. Then after sometime open your game
5. Now your game will stuck in splash screen
6. If you press the home button and then again try to open your game, the game will open as usual without any issue

### Minimal reproduction project

[AndroidTest.zip](https://github.com/godotengine/godot/files/6901417/AndroidTest.zip)

**Comment by Calinou** [comment] 2021-07-29 15:21
Can you reproduce this in a project that uses a non-Mono build (and only GDScript)?

**Comment by shahediqbal13** [comment] 2021-07-29 15:29
Please give me some time. I have to download the standard version of Godot. I will let you know.

**Comment by shahediqbal13** [comment] 2021-07-29 16:04
I created similar sample project (OpenGL ES2 based) in Godot v3.3.2.stable.official and tested in my device. Getting the same issue. I think if you check closely in pause and resume life cycle of Godot's android template then you can determine what is causing the issue.

Note: In both project I didn't use any script (C# or gdscript).

[AndroidTestGodotStandardVersion.zip](https://github.com/godotengine/godot/files/6901906/AndroidTestGodotStandardVersion.zip)

**Comment by mbrlabs** [comment] 2021-07-30 09:16
I can confirm this. I didn't bother to report it since it happend only a couple of times on an old test phone a while ago and i couldn't really reproduce it (execpt wait for hours leaving it open in the background). Anyways, i also recently noticed it on a Galaxy S10 running Android 11 on basically an empty project. Tested with v3.3.2.stable.official.

**Comment by akien-mga** [comment] 2021-07-30 09:21
CC @godotengine/android

**Comment by shahediqbal13** [comment] 2021-08-08 16:52
I made custom android build template by adding some logs on android lifecycle events. I found that when this issue happens following android methods are called again and again which leads the the game start in deadlock.

**onAttach(): called
onCreate(): called
UiChangeListener(): called
initializeGodot(): called
onVideoInit(): called
onAttach(): called
onCreate(): called
UiChangeListener(): called
initializeGodot(): called
onVideoInit(): called
onDestroy(): called
forceQuit(): called**

[log.txt](https://github.com/godotengine/godot/files/6951149/log.txt)

**Comment by shahediqbal13** [comment] 2021-08-08 19:19
I think the issue is happening due to the native resources/allocated memory are not getting cleaned properly.
When android system destroys an app from memory due to other app's resource allocation the **onDestroy()** method is not called, in where Godot actually cleanup its resources.  If I call "forceQuit()" on "onPause()" method this issue doesn't happen, but it breaks the user experience - instead of resuming the game, it starts the game again.

**Comment by mbrlabs** [comment] 2021-08-09 18:21
@shahediqbal13 yes, i think you are right. I found a way to reproduce this now instantly without waiting. In the developer settings there is an option called "Don't keep activities" - which calls `onDestroy` if the user leaves the app:

![settings](https://user-images.githubusercontent.com/8750135/128754486-18188e54-c018-4e07-bd66-0a8638ddb95e.jpg)

If you enable it all Godot apps will get stuck the next time you open them. If you open and close them again it works again...and so on.

**Comment by shahediqbal13** [comment] 2021-08-09 18:38
Thanks for sharing this USB debugging feature. Actually one of my Android games now has more than 70k+ downloads. But the problem is I am getting ANR and crash report more that 100 daily. I was trying to find out possible reasons and tested in many devices, but couldn't reproduce it. Then I found this issue. I think this is causing the ANR in production. I will try to investigate more on this.

**Comment by mbrlabs** [comment] 2021-08-09 19:02
Yes, pretty sure that's it. I can reproduce this on a 10 year old Galaxy S4 and a new S10 with an empty project.

@Calinou this issue probably deserves a "High Priority" label. Basically every user is gonna run into this since no one completly closes an app.

Maybe @m4gr3d can help as well? :)

**Comment by Calinou** [comment] 2021-08-09 19:57
Can anyone check if this occurs with Godot 3.2.x (such as Godot 3.2.3)?

**Comment by shahediqbal13** [comment] 2021-08-09 20:20
@Calinou I was actually doing this. Tested in Godot 3.2.3.stable.mono.official. The issue doesn't happen in that version. And also checked in Godot 3.3.3-rc-mono - the issue persists in this version.

**Comment by mbrlabs** [comment] 2021-08-09 20:23
Yes, same with the standard build. 
First bad version is 3.3. I still have some 3.2.4 builds. I'm trying those now.

**Comment by mbrlabs** [comment] 2021-08-10 23:07
So, i suspected #42186 (commit e99dc65b64bbc88fd05434508e985115f1fb11d0 in 3.x) to be the cause, so compiled Godot for that and the previous commit (59da1db188baa778e29fc484e90197da2a9e1049) and i found that indeed since that Subview PR got merged there is a problem with re-opening Godot apps when they have been destroyed by the system. They don't hang like right now in the current `3.x` branch or `3.3.2` but just crash like in `beta1` (see my comment above).

Since `3.2.4 rc4` however it starts to hang - not crash. Not sure what changed since...i can try to guess what changed since then based on the Git history and then biscect from there, but i think we should first look at what went wrong in #42186. 

The whole Android build process is pretty time consuming, so if anyone want's to try it here is a python script i use, which automates the process (currently just builds debug templates): [build_android.zip](https://github.com/godotengine/godot/files/6964900/build_android.zip).

@akien-mga Please don't release 3.3.3 before this is fixed. This bug is actually quite serious.

**Comment by mbrlabs** [comment] 2021-08-12 14:11
@shahediqbal13 I found a fix: https://github.com/godotengine/godot/pull/51571. Can you check if this fixes the hangs with your project as well?

**Comment by shahediqbal13** [comment] 2021-08-12 14:58
@mbrlabs I have tested your fix. But it is not working as expected. It works fine with you shared USB debug setting. But If I test in my way, like opening the app and press home button then open other apps then reopen the godot app, the game exits on the start.

**Comment by mbrlabs** [comment] 2021-08-12 15:11
Hmm, yes i can reproduce that. Weird. I thought that debug setting is emulating exactly that, but apparently it behaves differently. I will investigate further.

**Comment by m4gr3d** [comment] 2021-08-12 18:20
@mbrlabs @shahediqbal13 Thanks for the detailed breakdown of the issue!
I think I have a fix that'll address the issue; I'm finishing testing it, and will push a PR shortly once that's done.

**Comment by shahediqbal13** [comment] 2021-08-12 21:00
@m4gr3d Seems like issue is fixed. I can't reproduce it. Thanks for the PR :)

**Closed** 2021-08-13 06:44 UTC
Labels: bug, platform:android, topic:porting, confirmed, high priority, regression
