### ISSUE TITLE
After I create about 50 named class. In"Create New Node" dialog, the class tree refresh very slowly,

### ISSUE THREAD

**Issue by miblooming** [godotengine/godot#31039] opened 2019-08-02 16:34 UTC
Godot version:
3.1.1

OS/device including version:
Windows10.0.17763.379

**Issue description:**

**Steps to reproduce:**
After I create about 60 named class.
In"Create New Node" dialog, the class tree refresh very slowly,
Especially when I input to search. 

**Minimal reproduction project:**

[AddNewNodeBug.zip](https://github.com/godotengine/godot/files/3462167/AddNewNodeBug.zip)

**Comment by Calinou** [comment] 2019-08-02 16:43
Duplicate of #27333.

**Closed by Calinou** 2019-08-02 16:43 UTC
