### ISSUE TITLE
Html5 export not working: Could not load game data

### ISSUE THREAD

**Issue by Jummit** [godotengine/godot#32584] opened 2019-10-06 09:51 UTC
**Godot version:**
5a23ab61f

**OS/device including version:**
Ubuntu 18.04.3 LTS / Thinkpad T420

**Issue description:**
When exporting to html5, it gives me the error `Error: Could not load game data at path '.'. Is the .pck file missing?`

**Steps to reproduce:**
Create a new project with a main scene and export it to html5. Put it on a server or in localhost and open it in the browser.

**Minimal reproduction project:**
[HtmlTest.zip](https://github.com/godotengine/godot/files/3694195/HtmlTest.zip)

**Comment by akien-mga** [comment] 2019-10-06 10:35
A priori duplicate of #32422.

Did you build the HTML5 export templates matching your editor version? This bug was fixed a 5 days ago.

**Comment by Jummit** [comment] 2019-10-06 11:18
It could be possible that I am still using the old export templates.

**Closed** 2019-10-06 11:22 UTC
