### ISSUE TITLE
In some cases, the invisible area of the child control can still be seen when `clip_contents` is enabled

### ISSUE THREAD

**Issue by Rindbee** [godotengine/godot#63707] opened 2022-07-31 02:54 UTC
### Godot version

v4.0.alpha.custom_build [7281f0f23]

### System information

Linux Mint 20.3

### Issue description

When the visible area of the parent control is `0`, the invisible area of the child control can still be seen when `clip_contents` is enabled:
1. One of the dimensions of size is `0`. 
2. The rect of the parent control is not within the visible area of the 2D main screen.

https://user-images.githubusercontent.com/30386067/182007794-bea8fa75-9359-4b93-903f-a7667243fd13.mp4

### Steps to reproduce

1. Add a control `A`, give it a size `(100, 100)`.
2. Add a `ColorRect` as a child of `A`, give it a size `(500,500)`;
3. Enable clip_contents of A.
4. Resize the size of A, make one dimension to `0`.

**Comment by KoBeWi** [comment] 2022-07-31 08:46
Duplicate of #56579

**Closed by KoBeWi** 2022-07-31 08:46 UTC
