### ISSUE TITLE
Select Method displays duplicates

### ISSUE THREAD

**Issue by mitchcurtis** [godotengine/godot#28940] opened 2019-05-16 18:42 UTC
**Godot version:**
3.1

**OS/device including version:**
MacBook Pro
macOS 10.14.4

**Issue description:**

I have the following script, Item.gd:

```
extends Node2D

class_name Item

onready var animation_player = get_node("AnimationPlayer")
onready var state_manager = get_node("StateManager")
onready var collision_node = get_node("CollisionNode")
var item_data = null
# Shared data. Shouldn't be modified after being set.
var item_name = "" setget set_item_name
# Instance data.
var equipper = null

func set_item_name(new_item_name):
    assert(item_name.length() == 0)
    
    item_name = new_item_name
    item_data = ItemDatabase.item_at(item_name)

func get_shared_data():
    return item_data
    
func _ready():
    if (animation_player):
        animation_player.connect("animation_finished", state_manager, "_on_animation_finished")
        animation_player.connect("animation_finished", self, "_on_AnimationPlayer_finished")
    if (state_manager):
        state_manager.connect("state_changed", self, "_on_state_changed")

func _on_AnimationPlayer_finished(animation_name):
    return
    
func _on_state_changed():
    return
    
func _destroy():
    print("destroying "+name)
    collision_node.contact_monitor = false
    queue_free()
```

I have Maggot.gd, which extends it:

```
extends "../Item.gd"

var shooter = null

func _init():
    set_item_name("Maggot")

func _ready():
    assert(collision_node.connect("body_entered", self, "_on_body_entered") == OK)
    animation_player.play("fly")

func _on_body_entered(body):
    Audio.play("res://assets/audio/melee-wood-plastic.wav", get_tree().current_scene)
    if (body.has_method("hit")):
        body.hit(shooter, self)
    _destroy()
    
func _destroy():
    animation_player.connect("animation_finished", self, "_on_animation_finished")
    animation_player.play("splat")
    
#func _on_animation_finished(animation_name):
#    ._destroy()
```

The scene for Maggot.tscn:

<img width="268" alt="Screen Shot 2019-05-16 at 8 40 32 PM" src="https://user-images.githubusercontent.com/6002340/57878700-e3551e80-781a-11e9-8c75-3e57d3ba0137.png">

If I want to call a method in an animation, the Select Method dialog gives me these choices:

<img width="1009" alt="Screen Shot 2019-05-16 at 8 34 50 PM" src="https://user-images.githubusercontent.com/6002340/57878618-b274e980-781a-11e9-9a86-b99688bd8aed.png">

You can see that the methods declared in Maggot.gd are duplicated there.

**Comment by Anutrix** [comment] 2019-07-04 21:28
What is the expected behavior though? Should it display both functions from both base and super script or just the super script? Because despite being overridden, both the functions perform different actions so displaying both is, in a way, might be the right behavior.

**Comment by mitchcurtis** [comment] 2019-07-05 07:34
At the very least, I would expect that each script type has its own section of properties in order to distinguish them from base types. That is, have sub-sections within "Script Methods", where each section's title is the name of the type. The point is to make it clear which function is being referred to, since it's currently impossible to know.

**Comment by KoBeWi** [comment] 2020-08-25 23:19
Can anyone still reproduce this bug in [Godot 3.2.3 rc4](https://godotengine.org/article/release-candidate-godot-3-2-3-rc-4) or any later release?

If yes, please ensure that an up-to-date Minimal Reproduction Project (MRP) is included in this report (a MRP is a zipped Godot project with the minimal elements necessary to reliably trigger the bug). You can upload ZIP files in an issue comment with a drag and drop.

**Comment by akien-mga** [comment] 2020-12-10 16:14
No answer, so closing. Please comment if you can still reproduce it, and make sure that an up-to-date reproduction project is included.

**Closed by akien-mga** 2020-12-10 16:14 UTC
Labels: bug, topic:core, topic:editor, topic:gdscript
