### ISSUE TITLE
Scrolling in output window does not work when Display Scale is set to Custom

### ISSUE THREAD

**Issue by Nova840** [godotengine/godot#85164] opened 2023-11-21 05:55 UTC
### Godot version

v4.1.3.stable.official [f06b6836a]

### System information

Godot v4.1.3.stable - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 960 (NVIDIA; 31.0.15.4617) - AMD FX(tm)-6300 Six-Core Processor (6 Threads)

### Issue description

When the display scale is set to certain custom values, the scroll bar will not scroll down to the most recent message when printing something from _process(). It looks to be similar to #78434 and #79975, but only happens for custom display scales.

https://github.com/godotengine/godot/assets/17053434/c6bef5a7-a511-4040-9572-3898321a0be1

### Steps to reproduce

1. Start a new project
2. In Editor Settings, change "Display Scale" to "Custom"
3. Change "Custom Display Scale" to 0.8
4. Create a script that prints a message from _process()
5. Run the project, notice how the scroll bar doesn't move down to follow the most recent message

### Minimal reproduction project

[Output Test.zip](https://github.com/godotengine/godot/files/13422226/Output.Test.zip)

(This is just a project that calls print() from _process(), as I can't include the editor settings in the project)

**Comment by bruvzg** [comment] 2023-11-21 07:46
Probably duplicate of https://github.com/godotengine/godot/issues/82041 should be fixed by https://github.com/godotengine/godot/pull/82079.

**Closed** 2023-11-21 09:00 UTC
