### ISSUE TITLE
Area2D has stange position of colliders

### ISSUE THREAD

**Issue by sergeykorablin** [godotengine/godot#76327] opened 2023-04-21 21:45 UTC
### Godot version

4.0.2

### System information

Fedora Linux 38

### Issue description

In the script I use instantiate/add_child to create an object with Area2D that should detect collisions, but it doesn't.
But when I put tscn with this object on scene, it interacts normally.

After some testing and investigation, I found that the colliders are not where they are displayed, they are outside the top of the window and I can interact with them if the second area2d has a negative Y coordinate. Or i can resize window and these invisible area2d (or collision shapes?) will be lit lower than the top side of the window.

p.s. sorry for my English))

### Steps to reproduce

![Screenshot](https://user-images.githubusercontent.com/37698016/233737986-df5d301e-2a29-432e-989d-05235c496007.png)

### Minimal reproduction project

[test.zip](https://github.com/godotengine/godot/files/11300664/test.zip)

**Comment by Zireael07** [comment] 2023-04-22 07:26
Without a minimal project, there is NOTHING the team can do.

Attach a project or this will get closed.

**Comment by AThousandShips** [comment] 2023-04-22 07:46
I would recommend going to the [other community channels](https://godotengine.org/community) this looks like a configuration error or a misunderstanding of the functionality

Without a project this can't be investigated, but I suspect this is not a bug but user error

**Comment by sergeykorablin** [comment] 2023-04-22 08:28
@Zireael07 @AThousandShips 
i added a simple project to my first message

**Comment by kleonc** [comment] 2023-04-22 11:52
Fixed by #75509 (should be included in 4.0.3).

**Closed by kleonc** 2023-04-22 11:52 UTC
