### ISSUE TITLE
Using a setget set function on multiple values - without value = newvalue inside the function

### ISSUE THREAD

**Issue by blurymind** [godotengine/godot#11631] opened 2017-09-27 11:42 UTC
Basically I am trying to implement an undo system in my application. At first I thought that using setget on all values that I want to revert upon undo would be ideal, but I quickly found out that there is a flaw in this logic- I cant use a single function to do it.

I want to do something like this:
```
var layerVisible = true setget storeUndoStep
var layerPosition = Vector2(0,0) setget storeUndoStep

```
Using setget to call a function that stores the old value to an array, every time a value is changed.
The problem is:

Setget's function needs to assign the new value, you cant just grab the old value before it's changed. You have to also assign it in the function - this makes it impossible to reuse the same function on multiple variables. You have to create a separate storeUndo function for every single variable that changes. Is it possible to use setget only to trigger a function, but let godot write the new value without doing
`value = newvalue `
inside the setget function?

my plan for the undo system is:
undosteps = [[all values undo step 1],[all values undo step 2],[all values undo step 3]...]

So on each undoable value change, use set get to append all current values array to the undosteps array

Perhaps I should use the get function?

**Comment by blurymind** [comment] 2017-09-27 11:54
It seems that the value is null if I use only a get function like this
var layerPosition = Vector2(0,0) setget ,storeUndoStep

So it seems that I can not use a universal set get function on multiple values

**Comment by blurymind** [comment] 2017-09-27 12:05
Using only the get makes the value be nill for some reason and breaks other parts of the code,
So I have make a whole bunch of setget functions now I guess, like this:

```
func storeUndoStep1(new):
	storeUndoStep()
	layerPosOffset=new
var layerCurFrame = 0
func storeUndoStep2(new):
	storeUndoStep()
	layerCurFrame=new
.... A whole bunch more ....

func storeUndoStep():
<do the value recording here>
```

**Comment by groud** [comment] 2017-09-27 12:08
Godot already provides an undo / redo impementation called UndoRedo, why not use this one ?

**Comment by blurymind** [comment] 2017-09-27 12:10
@groud ah sorry, I totally missed it ! 
Are there any tutorials/examples on it? How does one integrate it

**Comment by blurymind** [comment] 2017-09-27 12:13
@groud Please note that I am integrating an undo/redo system for a custom application, not an editor plugin. Can the undo/redo class be used outside godot's editor?

**Comment by groud** [comment] 2017-09-27 12:15
Here: http://docs.godotengine.org/en/stable/classes/class_undoredo.html

> @groud Please note that I am integrating an undo/redo system for a custom application, not an editor plugin. Can the undo/redo class be used outside godot's editor?

Normally yes, you just have to create a new UndoRedo object. 
For example the spatial editor uses `SpatialEditor::get_singleton()->get_undo_redo();`

**Comment by blurymind** [comment] 2017-09-27 12:19
@groud is there example code snippet anywhere ? 
This is seems less simple than my array plan :(
Is there no way to do it with setgets?

**Comment by groud** [comment] 2017-09-27 12:27
Here is a cpp code, I let you translate in GDscript.
```
undo_redo->create_action("Change margin");
Control *c = Object::cast_to<Control>(E->get());
undo_redo->add_do_method(c, "set_margin", MARGIN_RIGHT, 0);
undo_redo->add_undo_method(c, "set_margin", MARGIN_RIGHT, c->get_margin(MARGIN_BOTTOM));
undo_redo->commit_action();
```
then to undo:

`undo_redo->undo()`

Have a look to the /core/undo_redo.h file for the API.

**Comment by blurymind** [comment] 2017-09-27 12:28
one suggestion to improve setget set from me is to have both the old and the new value as a parameter to the function.
It will allow for a function to be reused on multiple values like this:

```
var layerSize = Vector2() setget storeUndoStep
var layerPosOffset = Vector2() setget storeUndoStep

func storeUndoStep(old,new):
	triggerMyStuff()
	new = old
```

**Comment by groud** [comment] 2017-09-27 12:30
This wont happen, this is not what setters/getters are meant to be.

**Comment by blurymind** [comment] 2017-09-27 12:31
Is there a way to trigger an event whenever a variable is changed, without actually doing anything to the variable?

**Comment by groud** [comment] 2017-09-27 12:33
You define a setter, and send a signal before updating the variable.

**Comment by bojidar-bg** [comment] 2017-09-27 12:33
Slightly off topic, but still...

Would be nice if we can pass additional custom parameters to setgets -- similar to signals.

Maybe something like:
```gdscript
export var width setget _set_size("width")
export var height setget _set_size("height")

func _set_size(property, new_value):
  if property == "width": width = new_value
  elif property == "height": height = new_value
  update()
```
Or, if `set` could be used without triggering the setter somehow:
```gdscript
export var width setget _set_size("width")
export var height setget _set_size("height")

func _set_size(property, new_value):
  set(property, new_value)
  update()
```
Or, if returning `true` from the `setter` would make it save the value: (this happens to not require custom paramters passed to the setter)
```gdscript
export var width setget _set_size
export var height setget _set_size

func _set_size(new_value):
  update()
  return true
```

For comparison, here is the current solution: (which quickly becomes bloaty)
```gdscript
export var width setget _set_width
export var height setget _set_height

func _set_width(new_value):
  width = new_value
  update()
func _set_height(new_value):
  height = new_value
  update()
```

This would help writing plugins/addons, or other types of reusable code, without falling into [lots of repetitive lines](https://github.com/KOBUGE-Incubator/planetoidee/blob/master/game/render.gd#L4-L10).

**Comment by bojidar-bg** [comment] 2017-09-27 12:34
Some of the proposed solutions are slightly related to #6491.

**Comment by blurymind** [comment] 2017-09-27 12:36
It is exactly what I need right now. @bojidar-bg  is right - it will come in handy for many other situations.

In my case it looks like I have to actually do a lot of refactoring to go with the undo-redo api or use lots of repetitive setget function lines

**Comment by groud** [comment] 2017-09-27 12:38
@bojidar-bg, I don't agree with that, a function that set a variable but needs other arguments is not a setter. setget is just used to reroute calls to `myobject.myvariable = val` to `myobject.setmyvariable(val)`.
Adding parameter to the setget syntax would be a bad idea IMHO.

**Comment by blurymind** [comment] 2017-09-27 12:42
@groud  setget set already has a parameter

Perhaps instead of setget we could have something like this?

```
export var width onupdate _set_size
export var width onupdate _set_size

func _set_size():
   print("set size was triggered")
```

**Comment by groud** [comment] 2017-09-27 12:47
I'd better like to have either a notification / signal when a property changes.

**Comment by blurymind** [comment] 2017-09-27 12:50
I like the idea! Emit a signal whenever a variable was changed. Perhaps it would be useful of the emited signal emits both the before and after values?

**Comment by groud** [comment] 2017-09-27 12:56
So I guess I can mark this issue as a duplicate of #6491, which is clearer than this one I guess.

Anyway, if you need more help on the UndoRedo class, that should fix the initial problem, please ask on the forum/facebook/IRC/Q&A. :)

**Comment by blurymind** [comment] 2017-09-27 13:01
@groud  thank you :) 
I will try. It is poorly documented atm - no examples out there

**Comment by groud** [comment] 2017-09-27 13:03
Ok closing this issue as a duplicate of #6491 then.

> I will try. It is poorly documented atm
Sure, a lot of things are :)

**Closed by groud** 2017-09-27 13:03 UTC
Labels: discussion, enhancement, topic:gdscript
