### ISSUE TITLE
Excesive space in inspector for property name

### ISSUE THREAD

**Issue by Ranoller** [godotengine/godot#17332] opened 2018-03-07 13:17 UTC
**Godot version:**

Godot 3

**OS/device including version:**

All systems

**Issue description:**

Doing large sessions of work with godot i notice some incomodity in changing values in inspector. I see excesive space to name properties and few space to enter numbers and text. I think "values" of properties are more important that the "name"... I explain myself:
![inspector1](https://user-images.githubusercontent.com/11712737/37094110-034fa9d6-2212-11e8-87f5-3dfa0a7f4be4.png)
![inspector2](https://user-images.githubusercontent.com/11712737/37094120-08e70bc8-2212-11e8-95b0-93b5ff871bc7.png)
![inspector3](https://user-images.githubusercontent.com/11712737/37094122-0ae2f734-2212-11e8-8ecd-5662dc84cf67.png)

**Comment by vnen** [comment] 2018-03-07 16:29
Duplicate of #7133.

**Closed by vnen** 2018-03-07 16:29 UTC
