### ISSUE TITLE
Crash on launching Project Manager

### ISSUE THREAD

**Issue by hilfazer** [godotengine/godot#43125] opened 2020-10-27 08:45 UTC
**Godot version:**

b370aa75dd95ec6b7921f0e95be428a550a0edcc

**OS/device including version:**

Windows 7 x64 SP1

**Issue description:**

> E:\Programming\Godot\sources\godot-fork-4.0\bin>godot.windows.opt.tools.64.exe
Godot Engine v4.0.dev.custom_build.b370aa75d - https://godotengine.org
CrashHandlerException: Program crashed
Dumping the backtrace. Please include this when reporting the bug on https://git
hub.com/godotengine/godot/issues
[0] RtlDeNormalizeProcessParams
[1] RtlDeNormalizeProcessParams
[2] RtlDeNormalizeProcessParams
[3] loaderScanForImplicitLayers (e:\programming\godot\sources\godot-fork-4.0\thi
rdparty\vulkan\loader\loader.c:4876)
[4] vkEnumerateInstanceLayerProperties (e:\programming\godot\sources\godot-fork-
4.0\thirdparty\vulkan\loader\trampoline.c:218)
[5] VulkanContext::_create_physical_device (e:\programming\godot\sources\godot-f
ork-4.0\drivers\vulkan\vulkan_context.cpp:277)
[6] VulkanContext::initialize (e:\programming\godot\sources\godot-fork-4.0\drive
rs\vulkan\vulkan_context.cpp:1134)
[7] DisplayServerWindows::DisplayServerWindows (e:\programming\godot\sources\god
ot-fork-4.0\platform\windows\display_server_windows.cpp:3120)
[8] DisplayServerWindows::create_func (e:\programming\godot\sources\godot-fork-4
.0\platform\windows\display_server_windows.cpp:3219)
[9] Main::setup2 (e:\programming\godot\sources\godot-fork-4.0\main\main.cpp:1457
)
[10] Main::setup (e:\programming\godot\sources\godot-fork-4.0\main\main.cpp:1379
)
[11] widechar_main (e:\programming\godot\sources\godot-fork-4.0\platform\windows
\godot_windows.cpp:153)
[12] _main (e:\programming\godot\sources\godot-fork-4.0\platform\windows\godot_w
indows.cpp:187)
[13] main (e:\programming\godot\sources\godot-fork-4.0\platform\windows\godot_wi
ndows.cpp:199)
[14] __scrt_common_main_seh (d:\agent\_work\2\s\src\vctools\crt\vcstartup\src\st
artup\exe_common.inl:288)
[15] BaseThreadInitThunk
-- END OF BACKTRACE --

I expected the Project Manager to launch.

**Steps to reproduce:**
Compile the project and run godot.windows.*.64.exe

So far i've checked 64 bit builds. Crash appeared for debug, release_debug and release builds. There was no backtrace for release build.

**Minimal reproduction project:**

N/A

**Comment by bruvzg** [comment] 2020-10-27 08:55
Duplicate of #43105, fixed by #43112.

**Closed by bruvzg** 2020-10-27 08:55 UTC
