### ISSUE TITLE
Unable to write to file error on Windows 10, Godot 3.1

### ISSUE THREAD

**Issue by DeybisMelendez** [godotengine/godot#27862] opened 2019-04-09 17:10 UTC
**Godot version:**
Godot 3.1 Estable

**OS/device including version:**
Windows 10 64 bits

**Issue description:**
In a random way Godot sends a message of "loading error", I do not know how to reproduce the problem, it appears suddenly. As you can see in the screenshot, I was not running the game, I had not paused it, nor had any changes without saving. In this case, I had minimized Godot and when I maximized the window, the message appeared. The project did not get corrupted and it seems that there is no error in reality.

I apologize for my bad English, I speak Spanish, I used the google translator.

--------------

De manera aleatoria Godot manda un mensaje de "error de carga", no sé como reproducir el problema, aparece de repente. Como podrán ver en el screenshot, no estaba ejecutando el juego, ni lo tenía en pausa, ni tenía cambios sin guardar. En este caso, yo tenía minimizado Godot y al maximizar la ventana me apareció el mensaje. El proyecto no se me corrompió y parece que no hay error en realidad.

Pido disculpas por mi mal inglés, hablo español, usé el traductor de google.

![Screenshot (110)](https://user-images.githubusercontent.com/40205683/55820221-d88ac980-5ab7-11e9-9a56-d81ccae03913.png)

**Comment by DeybisMelendez** [comment] 2019-04-09 17:18
I would like to add that in the Godot console this appears:
```ERROR: close: Condition ' rename_error ' is true.
   At: drivers/windows/file_access_windows.cpp:176```

----
me gustaría añadir que en la consola de Godot aparece esto:
```ERROR: close: Condition ' rename_error ' is true.
   At: drivers/windows/file_access_windows.cpp:176```

**Comment by rogeriodec** [comment] 2019-04-09 17:47
Have you tried to restart your Windows? It seems the file is locked for another process...

**Comment by qarmin** [comment] 2019-04-09 18:17
I see that you have opened two instances of Godot and this is probably the cause.
Probably this is Windows limitation about non access to opened files, which this seems doesn't happens on macOS and Linux

**Comment by nazgulsenpai** [comment] 2019-04-10 02:37
I had a similar issue in the past because OneDrive was synchronizing my Users folder while I was editing my project. Certain resources at random were unable to save. So if you're using any backup program that works on the entire User folder, try saving your project elsewhere i.e. drag it to your root C:\ and see if you have the same issue there.

If not that, you can always try running as Administrator.

**Comment by DeybisMelendez** [comment] 2019-04-10 18:34
@nazgulsenpai @qarmin @rogeriodec 
I have Google Drive on my PC but the project does not have it there, but if I use Git, I have my projects in Documents. I do not have open godot 2 times, the other window is the console or terminal, if I close that also closes godot.

This error is not the first time that it appears to me, it has already appeared to me many times and in unexpected moments.

-----------

Tengo Google Drive en mi PC pero el proyecto no lo tengo ahí, pero si uso Git, mis proyectos los tengo en Documents. Yo no tengo abierto godot 2 veces, la otra ventana es la consola o terminal, si yo cierro eso también se cierra godot.

Este error no es la primera vez que me aparece, me ha aparecido ya muchas veces y en momentos inesperados.

**Comment by Anutrix** [comment] 2019-07-04 22:32
Typically happens if auto-sync is on. Make sure OneDrive, GoogleDrive, MegaSync or any other auto-sync software doesn't include your project folder.

**Comment by KoBeWi** [comment] 2020-09-27 21:11
Can anyone still reproduce this bug in Godot 3.2.3 or any later release?

I remember it used to be quite common, but since 3.2 I get it once in a few months (it usually appears under heavy load of CPU).

**Comment by akien-mga** [comment] 2020-12-10 23:01
No answer, so closing.

**Closed by akien-mga** 2020-12-10 23:01 UTC
Labels: bug, topic:editor
