### ISSUE TITLE
Text inside in-editor docs view is too close to the edge when opened

### ISSUE THREAD

**Issue by dogyx** [godotengine/godot#70144] opened 2022-12-16 10:23 UTC
### Godot version

v4.0.beta8.official [45cac42c0]

### System information

EndeavourOS, AMD RX 6600

### Issue description

When opening a new page in in-editor documentation viewer, the text inside of it is too close to the edge of the view.
![bug](https://user-images.githubusercontent.com/85757201/208075487-ffc52e18-c705-4528-8869-129215c0033e.png)

How it looks after slightly resizing 'open files' / 'file outline' panel and 'documentation' view: (This is how I expect it should always look)
![expected](https://user-images.githubusercontent.com/85757201/208075644-696ecccc-8012-402d-b575-80529be3335b.png)

### Steps to reproduce

1. Open in-editor docs, for example, by clicking on "Search Help" and choosing an entry there. Though, the bug seems to appear regardless of how a page is opened.
2. See the bug.

### Minimal reproduction project

N/A

**Comment by Calinou** [comment] 2022-12-16 16:19
Duplicate of https://github.com/godotengine/godot/issues/69773 (will be fixed in the next beta).

**Closed by Calinou** 2022-12-16 16:19 UTC
