### ISSUE TITLE
Script Editor clears unsaved changes when changing application

### ISSUE THREAD

**Issue by n-pigeon** [godotengine/godot#4444] opened 2016-04-25 21:36 UTC
**Operating system or device:**
Linux (Ubuntu)
Godot 2.0.2

**Issue description** (what happened, and what was expected):
If I edit a script and don't save it, then change for sec to other application window like web browser, unsaved text disappears.

**Steps to reproduce:**
Create script.
Write something.
Change application.
Go back to Godot.

**Comment by akien-mga** [comment] 2016-04-26 07:19
Hm that's interesting, as up to now we only got report about this happening on Windows. I never experienced this myself on Linux, but I guess I'm a compulsive Ctrl+S spammer :D

**Comment by akien-mga** [comment] 2016-04-26 07:20
Might be a duplicate of #3764, but let's keep it open until it can be confirmed that it's the same bug on both Windows and Linux.

**Comment by nsrosenqvist** [comment] 2016-04-26 21:47
I noticed something similar the other day. I was using Godot 2.0.2 on OSX and noticed that sometimes the code I've just entered had disappeared but I didn't find a pattern to when it was happening.

**Comment by slapin** [comment] 2016-04-29 11:25
Yes, confirm it, IIRC it is since 2.0 or so, Linux too.

**Comment by akien-mga** [comment] 2016-04-29 12:29
Ok so it seems to be platform-independent in the end, thanks for the feedback :)

**Comment by vnen** [comment] 2016-05-14 19:45
Two new reports for 2.0.3 in #4656.

**Comment by akien-mga** [comment] 2016-05-17 07:31
We really need this one fixed for 2.1, and I wouldn't be against a fix to backport for 2.0.4 either ;)

**Comment by akien-mga** [comment] 2016-06-03 07:43
@reduz Could you have a look at this one? It seems to affect quite a few users in both stable and 2.1-dev.

**Comment by vnen** [comment] 2016-06-21 17:34
Another report on Linux: #5343.

**Comment by bojidar-bg** [comment] 2016-07-03 15:44
Can reproduce (and the steps are easy) on Arch linux, details:

I have an `res://editor/editor.tscn` scene, which depends on `res://editor/editor_world.gd`. The latter extends `res://world/base_world.gd`.

Then, I rename `res://editor/editor_world.gd` to `res://world/editor_world.gd`, and proceed to edit  `res://world/base_world.gd`. I Ctrl-Alt-Up to change desktops for a second, and.... the changes are gone! :smile: 

Restarting the editor helps. The console is constantly spammed with messages of the sort of:
````
ERROR: set_path: Another resource is loaded from path: res://world/base_world.gd
   At: core/resource.cpp:178.
````
\- for every open script in the editor.

Renaming the resource back to the original name (`res://world/editor_world.gd` to `res://editor/editor_world.gd`) clears the issue as well.

**Comment by vnen** [comment] 2016-07-03 20:01
So I can make the steps even easier:

1. Create 2 scripts (say `script1.gd` and `script2.gd`)
2. Leave both scripts open in editor.
3. Make some changes in `script1.gd` and **do not** save.
4. Go to a terminal and `touch script2.gd`.
5. Go back to Godot, the changes on `script1.gd` will vanish.

What is happening is that when any script is changed on disk, the script editor is reloading **all** of them, even the scripts that are not saved yet.

I believe this should be changed to reload only the modified files and show the Resave/Reload popup for unsaved files that changed on disk.

Also, there's the problem of the Script Editor keeping references to moved/deleted scripts, which is causing the error spamming, but that's another issue.

**Closed** 2016-07-09 15:12 UTC
Labels: bug, topic:editor

**Comment by bojidar-bg** [comment] 2017-02-22 07:50
Hm, was the fix reverted in the end, or is github trying to confuse us?

**Comment by akien-mga** [comment] 2017-02-22 08:04
It was reverted in 6923b1c, but maybe another fix was done afterwards. Can the bug still be reproduced in 2.1.2?
