### ISSUE TITLE
Lists of Enums that are assigned values through the editor have incorrect values at runtime

### ISSUE THREAD

**Issue by 491625** [godotengine/godot#52175] opened 2021-08-28 02:11 UTC
### Godot version

3.3.3

### System information

Windows 10

### Issue description

I have a list of enum values that is exposed through the editor via the [Export] attribute. At runtime, the first entry in that list has an incorrect value that doesn't correspond to any member of the enum.

I've repro'd the problem in a stripped down project that only contains the following script assigned to a single Node2D.
```
using Godot;
using System;
using System.Collections.Generic;

public class NodeWithEnumList : Node2D
{
	
	[Export]
	public List<TestEnum> EnumVals {get; set;}
	
	// Called when the node enters the scene tree for the first time.
	public override void _Ready()
	{
		foreach(var enumVal in EnumVals)
		{
			Console.WriteLine($"You have an enumVal of {enumVal}");
		}
	}

	public enum TestEnum
	{
		firstVal,
		secondVal
	}

}
```

Here's what's configured for that Node2D in the editor.
![image](https://user-images.githubusercontent.com/13492529/131202759-00ae2d8d-b7d2-4c7a-8aed-3b55cccdd777.png)

And here's what gets printed out in the console.
![image](https://user-images.githubusercontent.com/13492529/131202778-d7a6efe0-78a4-45e3-b285-1a21edabe481.png)

### Steps to reproduce

Repro steps are included in the 'Issue Description' above, but here's a quick summary of how to repro with the project attached.

1. Start up the project and make sure that the 'Enum Vals'  property on the Node2D has at least 1 entry assigned to it.
2. Play the project (you may want to have a debugger attached and a breakpoint in the _Ready() function in NodeWithEnumList.cs)
3. Look at the console output, or use the debugger to inspect the value of the EnumVals variable.

### Minimal reproduction project

[EnumBugTest.zip](https://github.com/godotengine/godot/files/7070008/EnumBugTest.zip)

**Comment by Calinou** [comment] 2021-08-28 14:29
Duplicate of https://github.com/godotengine/godot/issues/42926.

**Closed by Calinou** 2021-08-28 14:29 UTC
