### ISSUE TITLE
Failure of mathematical analysis in 3D scene

### ISSUE THREAD

**Issue by artems37rus** [godotengine/godot#32604] opened 2019-10-06 19:54 UTC
**Godot version:**
v3.2.alpha.custom_build.1d9233c38
**OS/device including version:**
Windows 10 x64
**Issue description:**
![2019-10-06_22-36-10](https://user-images.githubusercontent.com/50069281/66274886-d4cfd800-e88b-11e9-8559-1122447c12c7.gif)
**Steps to reproduce:**
Create a new project and put a large number on any coordinate
**Minimal reproduction project:**
N/A

**Comment by Zylann** [comment] 2019-10-06 20:29
That sounds like float imprecision, but I'm skeptical because the inspector doesnt have any problem representing all the decimals.

**Comment by qarmin** [comment] 2019-10-07 04:08
Look at #21922 and #12299

**Comment by aaronfranke** [comment] 2019-11-05 06:23
This imprecision is larger than would be caused by floats. It's actually my fault, regression from #18992.

There's some interesting logic in [spatial_editor_plugin.cpp line 2185](https://github.com/godotengine/godot/blob/master/editor/plugins/spatial_editor_plugin.cpp#L2185) that checks if the transform is unchanged (equal to the old one) before updating in the editor. I didn't anticipate equality checks being used to decide when *not* to do something when I made #18992.

It's being partially reverted anyway, so this issue will be fixed when #32477 is merged.

**Closed** 2019-11-07 13:54 UTC
Labels: bug, topic:core
