### ISSUE TITLE
Bring back the default light in Godot 3 3D.

### ISSUE THREAD

**Issue by kakoeimon** [godotengine/godot#12399] opened 2017-10-25 10:49 UTC
**Issue description:**

In Godot 2 we had a default light in the editor. This way we had the ability to edit the scenes without any light. 
In Godot 3 there is no default light and this creates the problem that we cannot edit the scenes cause always everything is very dark or the sky from the enviroment is blended.
The problem becomes more clear when by trying to edit particles of an object, cause this type of object is always made inside Godot.
Unless I am missing something I believe that the default light must come back in the edit frop down as it was in Godot 2.

**Comment by akien-mga** [comment] 2017-10-25 10:55
Duplicate of #10451. Feel free to comment there if you don't agree with its resolution, as it's apparently not intuitive enough yet.

**Closed by akien-mga** 2017-10-25 10:55 UTC
