### ISSUE TITLE
Offset when determining the size and alignment of bitmap fonts (valign == center)

### ISSUE THREAD

**Issue by DimitriyPS** [godotengine/godot#5945] opened 2016-07-28 06:57 UTC
**Godot 2.1**

I started using Godot 2.1 and quickly noticed that the interface of the project looks a bit wrong. Upon closer inspection, it turned out it was fonts:
![0000](https://cloud.githubusercontent.com/assets/11189223/17203725/bba4fd3e-54a9-11e6-9284-98f1596a1872.png)

**Comment by akien-mga** [comment] 2016-07-28 07:05
I can confirm that when using the default font too:
![spectacle wy6992](https://cloud.githubusercontent.com/assets/4701338/17203851/169f7514-54a2-11e6-954a-161e5769631c.png)

This should be fixed before 2.1, as it's a regression(\*) and might mess up the GUIs of 2.0 users.

(\*) How it looks like in 2.0:
![spectacle qb6992](https://cloud.githubusercontent.com/assets/4701338/17203884/5d7207ea-54a2-11e6-93d4-d2af10cff78d.png)

**Comment by akien-mga** [comment] 2017-08-08 11:33
Is this still valid in the current master branch?

**Comment by reduz** [comment] 2017-08-08 11:41
bitmap fonts are no longer supported for importing, so i guess not

**Comment by reduz** [comment] 2017-08-08 11:48
just closing, then

**Closed by reduz** 2017-08-08 11:48 UTC
Labels: bug, confirmed, topic:core
