### ISSUE TITLE
Code line overlaps the bottom of the script editor

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#15079] opened 2017-12-26 20:37 UTC
Godot 2.1.4
Windows 10 64 bits

I started a debug session and had an error, and I noticed the last line of the script editor overlaps with the bottom:

![image](https://user-images.githubusercontent.com/1311555/34364324-f42d1a20-ea84-11e7-8a12-d5ab7c4c3e35.png)

It also does that when using Ctrl+F.

**Comment by Dillybob1992** [comment] 2017-12-26 21:02
Was fixed in 3.0 IIRC

**Comment by eon-s** [comment] 2017-12-26 23:03
Duplicate of #10738 and already fixed on 2.1 branch.

**Closed** 2017-12-26 23:05 UTC
