### ISSUE TITLE
Split OS.execute into blocking and non-blocking method

### ISSUE THREAD

**Issue by mhilbrunner** [godotengine/godot#19302] opened 2018-06-01 09:20 UTC
See https://github.com/godotengine/godot/issues/19056

**Comment by akien-mga** [comment] 2018-06-01 09:36
Duplicate of #18919.

**Comment by romeojulietthotel** [comment] 2018-06-05 23:27
I see mention of  _breaking compatibility_ but why would fixing this break compatibility?

**Comment by akien-mga** [comment] 2018-06-06 06:18
Because unless we write two new methods and keep the old `OS.execute()` unmodified (and thus still broken as it is now), we would need to modify the `OS.execute()` API (remove it or change its behaviour), and thus break the compatibility.

**Comment by romeojulietthotel** [comment] 2018-07-02 01:17
But why do you think `OS.execute` would need to be modified in a way that would make it incompatible? Your assertions are unclear.

Using `posix_spawn` should provide a suitable fix for this. I played with it and it would even provide some extra functionality if we wanted.

**Comment by neikeq** [comment] 2018-07-04 19:08
@romeojulietthotel This is the method signature for `OS.execute`: http://docs.godotengine.org/en/3.0/classes/class_os.html#class-os-execute
The `bool blocking` argument would need to be removed, which breaks compatibility.

**Comment by SubSage** [comment] 2019-04-18 12:19
I have a pr that could be helpful with all of this, if anyone wants to double check the pr and make sure it works, feel free : https://github.com/godotengine/godot/pull/26462

**Closed** 2021-01-12 15:17 UTC
Labels: breaks compat, enhancement, topic:core
