### ISSUE TITLE
CSG collision not updated when moved 

### ISSUE THREAD

**Issue by FrankAlbella** [godotengine/godot#40683] opened 2020-07-24 21:47 UTC
**Godot version:**
3.2.2

**OS/device including version:**
Pop!_OS 20.04, GTX 1080, proprietary driver 440.100

**Issue description:**
A CSG mesh node with collision enabled will not update it's collision location when the node is moved. You can force the collision to update by disabling the collision then re-enabling it.

**Steps to reproduce:**
1. Add a CSG Mesh to the scene 
2. Enable collisions 
3. Translate it through a GDScript
4. The collision of the object and the mesh are now in two different places

**Minimal reproduction project:**
[csg_collision.zip](https://github.com/godotengine/godot/files/4974359/csg_collision.zip)

**Comment by aaronfranke** [comment] 2020-07-25 00:44
Confirmed with 3.2.3 beta 1.

**Comment by hoontee** [comment] 2020-08-11 05:16
Duplicate of #27364?

**Closed** 2020-08-11 09:58 UTC
Labels: bug, confirmed, topic:core
