### ISSUE TITLE
Don't let me make the "con" folder!

### ISSUE THREAD

**Issue by Pacomatic1** [godotengine/godot#70196] opened 2022-12-17 14:57 UTC
### Godot version

v3.5.1.stable.official [6fed1ffa3]

### System information

Windows 10 (although this likely affect all systems)

### Issue description

Although it's less a bug and moreso an oversight, this still needs attention.
In Godot, you're able to make folders.
But one time, I was trying to make a folder called 'coin' but had a typo and called it 'con'.
con is a reserved system variable.
Windows don't let you make this folder by normal means, and deletion cannot happen by normal means, because _you're not supposed to be able to create it!_

So, be it Windows, Mac, or Linux, **don't let me make the folder 'con'!**

### Steps to reproduce

Go into any project.
Go to your folder tree.
Make a new folder.
Call it 'con'.

If you want to delete it afterward and you're on Windows 10 then go to cmd.exe with Admin privileges and paste:
rd /s \\?\"filepath goes here"

### Minimal reproduction project

n/a

**Comment by Calinou** [comment] 2022-12-17 16:57
Duplicate of https://github.com/godotengine/godot/issues/38198.

**Closed by Calinou** 2022-12-17 16:57 UTC
