### ISSUE TITLE
Exported int gets initialised with invalid value (C#)

### ISSUE THREAD

**Issue by Cat-Lips** [godotengine/godot#47590] opened 2021-04-03 09:26 UTC
**Godot version:**
current master (8f7f58463)

**OS/device including version:**
Windows 10

**Issue description:**
If a C# script is decorated with the Tool attribute and Exports an int to the editor, the corresponding numeric up/down editor control gets stuck on a very high number when ticked.  ~~Works as expected if the Tool attribute is removed.~~
If the tool attribute is removed, the same issue occurs at runtime (see follow-up comment).

**Steps to reproduce:**
Using the attached project, open MyTest.tscn and tick the 'Test Value' field up or down in the property inspector.

**Minimal reproduction project:**
[New Game Project.zip](https://github.com/godotengine/godot/files/6252208/New.Game.Project.zip)

**Comment by Cat-Lips** [comment] 2021-04-03 10:47
Apologies, Tool/Editor control is a red-herring.  Without the Tool attribute, the same issue occurs at runtime:

```
//[Tool]
public partial class MyTest : Control
{
    private int _testValue;

    [Export]
    public int TestValue
    {
        get => _testValue;
        set
        {
            GD.Print($"TestValue: {_testValue} => {value}");
            _testValue = value;
        }
    }

    public MyTest() => GD.Print("MyTest()");

    public override void _EnterTree() => GD.Print("EnterTree()");
}
```

With `TestValue = 3` via tscn, console output is:
```
MyTest()
TestValue: 0 => 1739526920
EnterTree()
```

New repro attached...
[New Game Project.zip](https://github.com/godotengine/godot/files/6252385/New.Game.Project.zip)

**Comment by Calinou** [comment] 2021-04-03 14:16
Can you reproduce this in 3.2.3 or 3.3rc7?

**Comment by Cat-Lips** [comment] 2021-04-04 02:49
> @Cat-Lips Can you reproduce this in 3.2.3 or 3.3rc7?

Unfortunately, I could not open or create a new project with either of these packages.
Always seemed to hang just before opening the editor.
(Also tried installing Mono SDK and VS Build Tools.)
Verbose godot/mono log attached (for 3.2.3): [logs.zip](https://github.com/godotengine/godot/files/6253930/logs.zip)

I could try building from tag if that helps?

**Comment by Cat-Lips** [comment] 2021-04-08 01:56
> @Cat-Lips Can you reproduce this in 3.2.3 or 3.3rc7?

I can confirm that this issue is not present in 3.2.3 or 3.3rc7.

**Comment by raulsntos** [comment] 2022-08-26 15:08
Can you reproduce this in the latest master? I was unable to reproduce so it likely got fixed in the move to .NET 6.0.

**Comment by Cat-Lips** [comment] 2022-09-08 11:34
Apologies.  I no longer use master.  I am happy for the issue to be resolved if it can no longer be reproduced.

**Comment by raulsntos** [comment] 2022-09-09 18:44
I'll close as fixed since I can't reproduce it.

![image](https://user-images.githubusercontent.com/3903059/189421760-b9ee586e-d3e2-4688-a4f4-3e0304a93f54.png)

**Closed by raulsntos** 2022-09-09 18:44 UTC
Labels: bug, topic:dotnet, regression
