### ISSUE TITLE
Unable to remove a stream from an AudioStreamPlayer

### ISSUE THREAD

**Issue by YeldhamDev** [godotengine/godot#18012] opened 2018-04-06 01:05 UTC
**Godot version:**
eaa5dfb

**Issue description:**
Any attempt results in this error:
`scene/2d/audio_stream_player_2d.cpp:245 - Condition ' !p_stream.is_valid() ' is true.`

**Comment by chanon** [comment] 2018-06-19 11:48
Probably related, or the same thing as #16846

**Comment by bojidar-bg** [comment] 2018-06-19 14:57
Yes, duplicate of #16846, thanks for noticing.

**Closed by bojidar-bg** 2018-06-19 14:57 UTC
Labels: bug, topic:audio
