### ISSUE TITLE
 No loader found for SVG resource  on a activated Plugin

### ISSUE THREAD

**Issue by MikeSchulze** [godotengine/godot#44940] opened 2021-01-05 15:31 UTC
**Godot version:**
Godot Engine v3.2.3.stable.mono.official (c) 2007-2020 Juan Linietsky, Ariel Manzur & Godot Contributors.
Godot Engine v3.2.3.stable

**OS/device including version:**
Windows 10 64bit
MacOs

**Issue description:**
I run into this issue after i cleaned up all *.import files.
I try a "fresh" plugin install by by having a project without any *.import files. After opening the project i got a lot of errors.
Here the example plugin error report.
```
Godot Engine v3.2.3.stable.mono.official (c) 2007-2020 Juan Linietsky, Ariel Manzur & Godot Contributors.
--- GDScript language server started ---
 No loader found for resource: res://addons/test-plugin/assets/Progress4.svg.
 No loader found for resource: res://addons/test-plugin/assets/Progress2.svg.
 No loader found for resource: res://addons/test-plugin/assets/Progress7.svg.
 No loader found for resource: res://addons/test-plugin/assets/Progress8.svg.
 No loader found for resource: res://addons/test-plugin/assets/Progress5.svg.
 No loader found for resource: res://addons/test-plugin/assets/Progress6.svg.
 No loader found for resource: res://addons/test-plugin/assets/Progress3.svg.
 No loader found for resource: res://addons/test-plugin/assets/Progress1.svg.
 No loader found for resource: res://addons/test-plugin/assets/Progress1.svg.
 scene/resources/resource_format_text.cpp:175 - Couldn't load external resource: res://addons/test-plugin/assets/Progress1.svg
 No loader found for resource: res://addons/test-plugin/assets/Progress2.svg.
 scene/resources/resource_format_text.cpp:175 - Couldn't load external resource: res://addons/test-plugin/assets/Progress2.svg
 No loader found for resource: res://addons/test-plugin/assets/Progress3.svg.
 scene/resources/resource_format_text.cpp:175 - Couldn't load external resource: res://addons/test-plugin/assets/Progress3.svg
 No loader found for resource: res://addons/test-plugin/assets/Progress4.svg.
 scene/resources/resource_format_text.cpp:175 - Couldn't load external resource: res://addons/test-plugin/assets/Progress4.svg
 No loader found for resource: res://addons/test-plugin/assets/Progress5.svg.
 scene/resources/resource_format_text.cpp:175 - Couldn't load external resource: res://addons/test-plugin/assets/Progress5.svg
 No loader found for resource: res://addons/test-plugin/assets/Progress6.svg.
 scene/resources/resource_format_text.cpp:175 - Couldn't load external resource: res://addons/test-plugin/assets/Progress6.svg
 No loader found for resource: res://addons/test-plugin/assets/Progress7.svg.
 scene/resources/resource_format_text.cpp:175 - Couldn't load external resource: res://addons/test-plugin/assets/Progress7.svg
 No loader found for resource: res://addons/test-plugin/assets/Progress8.svg.
 scene/resources/resource_format_text.cpp:175 - Couldn't load external resource: res://addons/test-plugin/assets/Progress8.svg
Loading Plugin success
``` 
**Steps to reproduce:**
* install the attached example plugin
* activate it
* close the project
* remove manually all *.import and .import folder
* reopen the project
See errors on console

**Minimal reproduction project:**

[svg_import.zip](https://github.com/godotengine/godot/files/5771071/svg_import.zip)

**Comment by KoBeWi** [comment] 2021-01-05 20:26
Duplicate of #23937

**Closed by KoBeWi** 2021-01-05 20:26 UTC
Labels: bug, topic:editor, topic:import, topic:plugin
