### ISSUE TITLE
Godot fails to build Mono glue with the latest update

### ISSUE THREAD

**Issue by mysticfall** [godotengine/godot#36442] opened 2020-02-22 04:32 UTC
**Godot version:**
`master` / 7c1415b99

**OS/device including version:**
Manjaro Linux (Testing/KDE)

**Issue description:**
After checking out the current master branch and run scons to build the Mono glue, it fails with the following output:
```
Generating _ClassDB...
ERROR: Type not found. Creating placeholder: 'StringName'.
   at: _get_type_or_placeholder (modules/mono/editor/bindings_generator.cpp:2137)
...
Generating AnimatedSprite.cs...
ERROR: Parameter "prop_itype" is null.
   at: _generate_cs_property (modules/mono/editor/bindings_generator.cpp:1433)
ERROR: Failed to generate property 'animation' for class 'AnimatedSprite'.
   at: _generate_cs_type (modules/mono/editor/bindings_generator.cpp:1297)
ERROR: Generation of the Core API C# project failed.
   at: generate_cs_api (modules/mono/editor/bindings_generator.cpp:1115)
ERROR: --generate-mono-glue: Failed to generate the C# API.
   at: handle_cmdline_args (modules/mono/editor/bindings_generator.cpp:3181)
...
(similar logs repeated many times)
...
Project "/home/fender/workspace/godot/modules/mono/glue/GodotSharp/GodotSharp.sln" (1) is building "/home/fender/workspace/godot/modules/mono/glue/GodotSharp/GodotSharp/GodotSharp.csproj" (2) on node 1 (default targets).                                                                                                                                                            
/home/fender/workspace/godot/modules/mono/glue/GodotSharp/GodotSharp/GodotSharp.csproj(83,3): error MSB4019: The imported project "/home/fender/workspace/godot/modules/mono/glue/GodotSharp/GodotSharp/Generated/GeneratedIncludes.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.
Done Building Project "/home/fender/workspace/godot/modules/mono/glue/GodotSharp/GodotSharp/GodotSharp.csproj" (default targets) -- FAILED.
Project "/home/fender/workspace/godot/modules/mono/glue/GodotSharp/GodotSharp.sln" (1) is building "/home/fender/workspace/godot/modules/mono/glue/GodotSharp/GodotSharpEditor/GodotSharpEditor.csproj" (3) on node 1 (default targets).
/home/fender/workspace/godot/modules/mono/glue/GodotSharp/GodotSharpEditor/GodotSharpEditor.csproj(38,3): error MSB4019: The imported project "/home/fender/workspace/godot/modules/mono/glue/GodotSharp/GodotSharpEditor/Generated/GeneratedIncludes.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.
Done Building Project "/home/fender/workspace/godot/modules/mono/glue/GodotSharp/GodotSharpEditor/GodotSharpEditor.csproj" (default targets) -- FAILED.
Done Building Project "/home/fender/workspace/godot/modules/mono/glue/GodotSharp/GodotSharp.sln" (default targets) -- FAILED.

Build FAILED.

"/home/fender/workspace/godot/modules/mono/glue/GodotSharp/GodotSharp.sln" (default target) (1) ->
"/home/fender/workspace/godot/modules/mono/glue/GodotSharp/GodotSharp/GodotSharp.csproj" (default target) (2) ->
  /home/fender/workspace/godot/modules/mono/glue/GodotSharp/GodotSharp/GodotSharp.csproj(83,3): error MSB4019: The imported project "/home/fender/workspace/godot/modules/mono/glue/GodotSharp/GodotSharp/Generated/GeneratedIncludes.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.


"/home/fender/workspace/godot/modules/mono/glue/GodotSharp/GodotSharp.sln" (default target) (1) ->
"/home/fender/workspace/godot/modules/mono/glue/GodotSharp/GodotSharpEditor/GodotSharpEditor.csproj" (default target) (3) ->
  /home/fender/workspace/godot/modules/mono/glue/GodotSharp/GodotSharpEditor/GodotSharpEditor.csproj(38,3): error MSB4019: The imported project "/home/fender/workspace/godot/modules/mono/glue/GodotSharp/GodotSharpEditor/Generated/GeneratedIncludes.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.

    0 Warning(s)
    2 Error(s)
```
I haven't been able to build Godot since the Vulkan update, but I'm not sure if it's the same problem with #36111 or not.

**Comment by KiransHub** [comment] 2020-02-22 10:51
I'm having the same issue

**Comment by DenisBelmondo** [comment] 2020-02-27 01:44
I can confirm this issue also occurs on Windows 10.

**Comment by LinuxUserGD** [comment] 2020-02-28 13:31
It was fixed for a small time but after some new commits I also get this on Arch Linux:
```Swift
ERROR: Type not found. Creating placeholder: 'StringName'.
   at: _get_type_or_placeholder (modules/mono/editor/bindings_generator.cpp:2137)
ERROR: Type not found. Creating placeholder: 'StringName'.
   at: _get_type_or_placeholder (modules/mono/editor/bindings_generator.cpp:2137)
ERROR: Type not found. Creating placeholder: 'StringName'.
   at: _get_type_or_placeholder (modules/mono/editor/bindings_generator.cpp:2137)
ERROR: Type not found. Creating placeholder: 'StringName'.
   at: _get_type_or_placeholder (modules/mono/editor/bindings_generator.cpp:2137)
ERROR: Type not found. Creating placeholder: 'StringName'.
   at: _get_type_or_placeholder (modules/mono/editor/bindings_generator.cpp:2137)
ERROR: Type not found. Creating placeholder: 'StringName'.
   at: _get_type_or_placeholder (modules/mono/editor/bindings_generator.cpp:2137)
ERROR: Type not found. Creating placeholder: 'StringName'.
   at: _get_type_or_placeholder (modules/mono/editor/bindings_generator.cpp:2137)
ERROR: Type not found. Creating placeholder: 'StringName'.
   at: _get_type_or_placeholder (modules/mono/editor/bindings_generator.cpp:2137)
ERROR: Type not found. Creating placeholder: 'StringName'.
   at: _get_type_or_placeholder (modules/mono/editor/bindings_generator.cpp:2137)
ERROR: Type not found. Creating placeholder: 'StringName'.
   at: _get_type_or_placeholder (modules/mono/editor/bindings_generator.cpp:2137)
ERROR: Type not found. Creating placeholder: 'StringName'.
   at: _get_type_or_placeholder (modules/mono/editor/bindings_generator.cpp:2137)
ERROR: Type not found. Creating placeholder: 'StringName'.
   at: _get_type_or_placeholder (modules/mono/editor/bindings_generator.cpp:2137)
ERROR: Type not found. Creating placeholder: 'StringName'.
   at: _get_type_or_placeholder (modules/mono/editor/bindings_generator.cpp:2137)
ERROR: Type not found. Creating placeholder: 'StringName'.
   at: _get_type_or_placeholder (modules/mono/editor/bindings_generator.cpp:2137)
ERROR: Type not found. Creating placeholder: 'StringName'.
   at: _get_type_or_placeholder (modules/mono/editor/bindings_generator.cpp:2137)
ERROR: Type not found. Creating placeholder: 'StringName'.
   at: _get_type_or_placeholder (modules/mono/editor/bindings_generator.cpp:2137)
ERROR: Type not found. Creating placeholder: 'StringName'.
   at: _get_type_or_placeholder (modules/mono/editor/bindings_generator.cpp:2137)
ERROR: Type not found. Creating placeholder: 'StringName'.
   at: _get_type_or_placeholder (modules/mono/editor/bindings_generator.cpp:2137)
ERROR: Type not found. Creating placeholder: 'StringName'.
   at: _get_type_or_placeholder (modules/mono/editor/bindings_generator.cpp:2137)
ERROR: Type not found. Creating placeholder: 'StringName'.
   at: _get_type_or_placeholder (modules/mono/editor/bindings_generator.cpp:2137)
ERROR: Type not found. Creating placeholder: 'StringName'.
   at: _get_type_or_placeholder (modules/mono/editor/bindings_generator.cpp:2137)
ERROR: Type not found. Creating placeholder: 'StringName'.
   at: _get_type_or_placeholder (modules/mono/editor/bindings_generator.cpp:2137)
ERROR: Type not found. Creating placeholder: 'StringName'.
   at: _get_type_or_placeholder (modules/mono/editor/bindings_generator.cpp:2137)
ERROR: Type not found. Creating placeholder: 'StringName'.
   at: _get_type_or_placeholder (modules/mono/editor/bindings_generator.cpp:2137)
ERROR: Type not found. Creating placeholder: 'StringName'.
   at: _get_type_or_placeholder (modules/mono/editor/bindings_generator.cpp:2137)
ERROR: Type not found. Creating placeholder: 'StringName'.
   at: _get_type_or_placeholder (modules/mono/editor/bindings_generator.cpp:2137)
ERROR: Type not found. Creating placeholder: 'StringName'.
   at: _get_type_or_placeholder (modules/mono/editor/bindings_generator.cpp:2137)
Generating _Directory...
Generating _Engine...
Generating _File...
Generating _Geometry...
Generating _GodotSharp...
Generating _JSON...
Generating _Marshalls...
Generating _Mutex...
Generating _OS...
Generating _ResourceLoader...
Generating _ResourceSaver...
Generating _Semaphore...
Generating _Thread...
ERROR: Type not found. Creating placeholder: 'StringName'.
   at: _get_type_or_placeholder (modules/mono/editor/bindings_generator.cpp:2137)
Generating _VisualScriptEditor...
Mono glue generated successfully
Declaring global enum 'Type' inside static class 'Variant'
ERROR: Cannot resolve type reference in documentation: 'Vector2i'.
   at: bbcode_to_xml (modules/mono/editor/bindings_generator.cpp:536)
ERROR: Cannot resolve type reference in documentation: 'Rect2i'.
   at: bbcode_to_xml (modules/mono/editor/bindings_generator.cpp:536)
ERROR: Cannot resolve type reference in documentation: 'Vector3i'.
   at: bbcode_to_xml (modules/mono/editor/bindings_generator.cpp:536)
ERROR: Cannot resolve type reference in documentation: 'StringName'.
   at: bbcode_to_xml (modules/mono/editor/bindings_generator.cpp:536)
ERROR: Cannot resolve type reference in documentation: 'Callable'.
   at: bbcode_to_xml (modules/mono/editor/bindings_generator.cpp:536)
ERROR: Cannot resolve type reference in documentation: 'Signal'.
   at: bbcode_to_xml (modules/mono/editor/bindings_generator.cpp:536)
ERROR: Cannot resolve type reference in documentation: 'PackedInt64Array'.
   at: bbcode_to_xml (modules/mono/editor/bindings_generator.cpp:536)
ERROR: Cannot resolve type reference in documentation: 'PackedFloat64Array'.
   at: bbcode_to_xml (modules/mono/editor/bindings_generator.cpp:536)
Declaring global enum 'Operator' inside static class 'Variant'
Generating ARVRAnchor.cs...
Generating ARVRCamera.cs...
Generating ARVRController.cs...
Generating ARVRInterface.cs...
ERROR: Type not found. Creating placeholder: 'StringName'.
   at: _get_type_or_placeholder (modules/mono/editor/bindings_generator.cpp:2137)
Generating ARVRInterfaceGDNative.cs...
Generating ARVROrigin.cs...
Generating ARVRPositionalTracker.cs...
ERROR: Type not found. Creating placeholder: 'StringName'.
   at: _get_type_or_placeholder (modules/mono/editor/bindings_generator.cpp:2137)
Generating ARVRServer.cs...
Generating AStar.cs...
Generating AStar2D.cs...
Generating AcceptDialog.cs...
Generating AnimatedSprite.cs...
ERROR: Parameter "prop_itype" is null.
   at: _generate_cs_property (modules/mono/editor/bindings_generator.cpp:1433)
ERROR: Failed to generate property 'animation' for class 'AnimatedSprite'.
   at: _generate_cs_type (modules/mono/editor/bindings_generator.cpp:1297)
ERROR: Generation of the Core API C# project failed.
   at: generate_cs_api (modules/mono/editor/bindings_generator.cpp:1115)
ERROR: --generate-mono-glue: Failed to generate the C# API.
   at: handle_cmdline_args (modules/mono/editor/bindings_generator.cpp:3183)
```
and
```Swift
[5%] clang ++ -o main / tests / test_math.x11.opt.tools.64.llvm.o -c -std = gnu ++ 17 -g1 -O2 -flto = thin -pipe -fpie -pthread -Wall - -Werror = return-type -DDEBUG_ENABLED -DTYPED_METHOD_BIND -DTOUCH_ENABLED -DALSA_ENABLED -DALSAMIDI_ENABLED -DPULSEAUDIO_ENABLED -D_REENTRANT -DJOYDEV_ENABLED -DX11_ENABLED -DUNIX_ENABLED -DVULKAN_ENABLED -DPTRCALL_ENABLED -DTOOLS_ENABLED -DMINIZIP_ENABLED -DZSTD_STATIC_LINKING_ONLY -DGLAD_ENABLED -DGLES_OVER_GL -DHAVE_MNTENT -Ithirdparty / freetype / include -Ithirdparty / libpng -Ithirdparty / glad -Ithirdparty / vulkan -Ithirdparty / vulkan / include -Ithirdparty / vulkan / loader -Ithirdparty / zstd -Ithirdparty / zlib -Iplatform / x11 -I. main / tests / test_math.cpp
platform / x11 / os_x11.cpp: 244: 2: warning: Forcing vulkan video driver because OpenGL not implemented yet [-W # warnings]
#warning Forcing vulkan video driver because OpenGL not implemented yet
 ^
[5%] clang ++ -o main / tests / test_oa_hash_map.x11.opt.tools.64.llvm.o -c -std = gnu ++ 17 -g1 -O2 -flto = thin -pipe -fpie -pthread -Wall - -Werror = return-type -DDEBUG_ENABLED -DTYPED_METHOD_BIND -DTOUCH_ENABLED -DALSA_ENABLED -DALSAMIDI_ENABLED -DPULSEAUDIO_ENABLED -D_REENTRANT -DJOYDEV_ENABLED -DX11_ENABLED -DUNIX_ENABLED -DVULKAN_ENABLED -DPTRCALL_ENABLED -DTOOLS_ENABLED -DMINIZIP_ENABLED -DZSTD_STATIC_LINKING_ONLY -DGLAD_ENABLED -DGLES_OVER_GL -DHAVE_MNTENT -Ithirdparty / freetype / include -Ithirdparty / libpng -Ithirdparty / glad -Ithirdparty / vulkan -Ithirdparty / vulkan / include -Ithirdparty / vulkan / loader -Ithirdparty / zstd -Ithirdparty / zlib -Iplatform / x11 -I. main / tests / test_oa_hash_map.cpp
Generated / GodotObjects / PathFollow2D.cs (94,21): warning CS0108: 'PathFollow2D.Rotate' hides inherited member 'Node2D.Rotate (float)'. Use the new keyword if hiding was intended. [/Run/media/user/user/git/godot/modules/mono/glue/GodotSharp/GodotSharp/GodotSharp.csproj]
Generated / NativeCalls.cs (3220,94): error CS0246: The type or namespace name 'Callable' could not be found (are you missing a using directive or an assembly reference?) [/ Run / media / user / user / git /godot/modules/mono/glue/GodotSharp/GodotSharp/GodotSharp.csproj]
Generated / NativeCalls.cs (3223.95): error CS0246: The type or namespace name 'Callable' could not be found (are you missing a using directive or an assembly reference?) [/ Run / media / user / user / git /godot/modules/mono/glue/GodotSharp/GodotSharp/GodotSharp.csproj]
Generated / NativeCalls.cs (3226.95): error CS0246: The type or namespace name 'Callable' could not be found (are you missing a using directive or an assembly reference?) [/ Run / media / user / user / git /godot/modules/mono/glue/GodotSharp/GodotSharp/GodotSharp.csproj]
Generated / GodotObjects / ARVRInterface.cs (149,16): error CS0246: The type or namespace name 'StringName' could not be found (are you missing a using directive or an assembly reference?) [/ Run / media / user / user /git/godot/modules/mono/glue/GodotSharp/GodotSharp/GodotSharp.csproj]
Generated / GodotObjects / Object.cs (471,45): error CS0246: The type or namespace name 'Callable' could not be found (are you missing a using directive or an assembly reference?) [/ Run / media / user / user /git/godot/modules/mono/glue/GodotSharp/GodotSharp/GodotSharp.csproj]
Generated / GodotObjects / Object.cs (481,47): error CS0246: The type or namespace name 'Callable' could not be found (are you missing a using directive or an assembly reference?) [/ Run / media / user / user /git/godot/modules/mono/glue/GodotSharp/GodotSharp/GodotSharp.csproj]
Generated / GodotObjects / Object.cs (490.48): error CS0246: The type or namespace name 'Callable' could not be found (are you missing a using directive or an assembly reference?) [/ Run / media / user / user /git/godot/modules/mono/glue/GodotSharp/GodotSharp/GodotSharp.csproj]
Generated / GodotObjects / ARVRPositionalTracker.cs (80,16): error CS0246: The type or namespace name 'StringName' could not be found (are you missing a using directive or an assembly reference?) [/ Run / media / user / user /git/godot/modules/mono/glue/GodotSharp/GodotSharp/GodotSharp.csproj]
Generated / GodotObjects / ARVRPositionalTracker.cs (68,39): warning CS0108: 'ARVRPositionalTracker.GetType ()' hides inherited member 'object.GetType ()'. Use the new keyword if hiding was intended. [/Run/media/user/user/git/godot/modules/mono/glue/GodotSharp/GodotSharp/GodotSharp.csproj]
Generated / GodotObjects / ArrayMesh.cs (144,36): warning CS0108: 'ArrayMesh.BlendShapeMode' hides inherited member 'Mesh.BlendShapeMode'. Use the new keyword if hiding was intended. [/Run/media/user/user/git/godot/modules/mono/glue/GodotSharp/GodotSharp/GodotSharp.csproj]
Generated / GodotObjects / ArrayMesh.cs (40,21): warning CS0108: 'ArrayMesh.ArrayFormat' hides inherited member 'Mesh.ArrayFormat'. Use the new keyword if hiding was intended. [/Run/media/user/user/git/godot/modules/mono/glue/GodotSharp/GodotSharp/GodotSharp.csproj]
Generated / GodotObjects / ArrayMesh.cs (80,21): warning CS0108: 'ArrayMesh.ArrayType' hides inherited member 'Mesh.ArrayType'. Use the new keyword if hiding was intended. [/Run/media/user/user/git/godot/modules/mono/glue/GodotSharp/GodotSharp/GodotSharp.csproj]
Generated / GodotObjects / LightOccluder2D.cs (36.20): warning CS0108: 'LightOccluder2D.LightMask' hides inherited member 'CanvasItem.LightMask'. Use the new keyword if hiding was intended. [/Run/media/user/user/git/godot/modules/mono/glue/GodotSharp/GodotSharp/GodotSharp.csproj]
Generated / GodotObjects / CPUParticles.cs (15,21): warning CS0108: 'CPUParticles.Flags' hides inherited member 'GeometryInstance.Flags'. Use the new keyword if hiding was intended. [/Run/media/user/user/git/godot/modules/mono/glue/GodotSharp/GodotSharp/GodotSharp.csproj]
The creation of the project "/run/media/user/user/git/godot/modules/mono/glue/GodotSharp/GodotSharp/GodotSharp.csproj" has been completed (default goals) - ERROR.
The creation of the project "/run/media/user/user/git/godot/modules/mono/glue/GodotSharp/GodotSharp.sln" has been completed (standard goals) - ERROR.

Build process failed.

"/run/media/user/user/git/godot/modules/mono/glue/GodotSharp/GodotSharp.sln" (default target) (1) ->
"/run/media/user/user/git/godot/modules/mono/glue/GodotSharp/GodotSharp/GodotSharp.csproj" (default target) (2) ->
(CoreCompile target) ->
  Generated / GodotObjects / PathFollow2D.cs (94,21): warning CS0108: 'PathFollow2D.Rotate' hides inherited member 'Node2D.Rotate (float)'. Use the new keyword if hiding was intended. [/Run/media/user/user/git/godot/modules/mono/glue/GodotSharp/GodotSharp/GodotSharp.csproj]
  Generated / GodotObjects / ARVRPositionalTracker.cs (68,39): warning CS0108: 'ARVRPositionalTracker.GetType ()' hides inherited member 'object.GetType ()'. Use the new keyword if hiding was intended. [/Run/media/user/user/git/godot/modules/mono/glue/GodotSharp/GodotSharp/GodotSharp.csproj]
  Generated / GodotObjects / ArrayMesh.cs (144,36): warning CS0108: 'ArrayMesh.BlendShapeMode' hides inherited member 'Mesh.BlendShapeMode'. Use the new keyword if hiding was intended. [/Run/media/user/user/git/godot/modules/mono/glue/GodotSharp/GodotSharp/GodotSharp.csproj]
  Generated / GodotObjects / ArrayMesh.cs (40,21): warning CS0108: 'ArrayMesh.ArrayFormat' hides inherited member 'Mesh.ArrayFormat'. Use the new keyword if hiding was intended. [/Run/media/user/user/git/godot/modules/mono/glue/GodotSharp/GodotSharp/GodotSharp.csproj]
  Generated / GodotObjects / ArrayMesh.cs (80,21): warning CS0108: 'ArrayMesh.ArrayType' hides inherited member 'Mesh.ArrayType'. Use the new keyword if hiding was intended. [/Run/media/user/user/git/godot/modules/mono/glue/GodotSharp/GodotSharp/GodotSharp.csproj]
  Generated / GodotObjects / LightOccluder2D.cs (36.20): warning CS0108: 'LightOccluder2D.LightMask' hides inherited member 'CanvasItem.LightMask'. Use the new keyword if hiding was intended. [/Run/media/user/user/git/godot/modules/mono/glue/GodotSharp/GodotSharp/GodotSharp.csproj]
  Generated / GodotObjects / CPUParticles.cs (15,21): warning CS0108: 'CPUParticles.Flags' hides inherited member 'GeometryInstance.Flags'. Use the new keyword if hiding was intended. [/Run/media/user/user/git/godot/modules/mono/glue/GodotSharp/GodotSharp/GodotSharp.csproj]


"/run/media/user/user/git/godot/modules/mono/glue/GodotSharp/GodotSharp.sln" (default target) (1) ->
"/run/media/user/user/git/godot/modules/mono/glue/GodotSharp/GodotSharp/GodotSharp.csproj" (default target) (2) ->
(CoreCompile target) ->
  Generated / NativeCalls.cs (3220,94): error CS0246: The type or namespace name 'Callable' could not be found (are you missing a using directive or an assembly reference?) [/ Run / media / user / user / git /godot/modules/mono/glue/GodotSharp/GodotSharp/GodotSharp.csproj]
  Generated / NativeCalls.cs (3223.95): error CS0246: The type or namespace name 'Callable' could not be found (are you missing a using directive or an assembly reference?) [/ Run / media / user / user / git /godot/modules/mono/glue/GodotSharp/GodotSharp/GodotSharp.csproj]
  Generated / NativeCalls.cs (3226.95): error CS0246: The type or namespace name 'Callable' could not be found (are you missing a using directive or an assembly reference?) [/ Run / media / user / user / git /godot/modules/mono/glue/GodotSharp/GodotSharp/GodotSharp.csproj]
  Generated / GodotObjects / ARVRInterface.cs (149,16): error CS0246: The type or namespace name 'StringName' could not be found (are you missing a using directive or an assembly reference?) [/ Run / media / user / user /git/godot/modules/mono/glue/GodotSharp/GodotSharp/GodotSharp.csproj]
  Generated / GodotObjects / Object.cs (471,45): error CS0246: The type or namespace name 'Callable' could not be found (are you missing a using directive or an assembly reference?) [/ Run / media / user / user /git/godot/modules/mono/glue/GodotSharp/GodotSharp/GodotSharp.csproj]
  Generated / GodotObjects / Object.cs (481,47): error CS0246: The type or namespace name 'Callable' could not be found (are you missing a using directive or an assembly reference?) [/ Run / media / user / user /git/godot/modules/mono/glue/GodotSharp/GodotSharp/GodotSharp.csproj]
  Generated / GodotObjects / Object.cs (490.48): error CS0246: The type or namespace name 'Callable' could not be found (are you missing a using directive or an assembly reference?) [/ Run / media / user / user /git/godot/modules/mono/glue/GodotSharp/GodotSharp/GodotSharp.csproj]
  Generated / GodotObjects / ARVRPositionalTracker.cs (80,16): error CS0246: The type or namespace name 'StringName' could not be found (are you missing a using directive or an assembly reference?) [/ Run / media / user / user /git/godot/modules/mono/glue/GodotSharp/GodotSharp/GodotSharp.csproj]

    7 Warning (s)
    8 errors

Elapsed time 00: 00: 25.10
scons: *** [bin / GodotSharp / Api / Debug / GodotSharp.dll] RuntimeError: 'msbuild' exited with error code: 1
Traceback (most recent call last):
  File "/run/media/user/user/git/godot/modules/mono/build_scripts/solution_builder.py", line 150, in run_command
    subprocess.check_call (args, env = env_override)
  File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError (retcode, cmd)
subprocess.CalledProcessError: Command '[' / usr / bin / msbuild ',' /run/media/user/user/git/godot/modules/mono/glue/GodotSharp/GodotSharp.sln ',' / p: Configuration = Debug ',' / p: NoWarn = 1591 ']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/SCons/Action.py", line 1209, in execute
    result = self.execfunction (target = target, source = rsources, env = env)
  File "/run/media/user/user/git/godot/modules/mono/build_scripts/api_solution_build.py", line 20, in build_api_solution
    build_solution (env, solution_path, build_config, extra_msbuild_args = extra_msbuild_args)
  File "/run/media/user/user/git/godot/modules/mono/build_scripts/solution_builder.py", line 214, in build_solution
    run_command (msbuild_path, msbuild_args, env_override = msbuild_env, name = 'msbuild')
  File "/run/media/user/user/git/godot/modules/mono/build_scripts/solution_builder.py", line 152, in run_command
    raise RuntimeError ("'% s' exited with error code:% s"% (name, e.returncode))
RuntimeError: 'msbuild' exited with error code: 1
1 warning generated.
scons: building terminated because of errors.
```

**Comment by oisincar** [comment] 2020-02-29 21:45
Confirming this (original issue), with near-identical logs on Ubuntu 19.04/ msbuild 16.3.0/ Mono 6.6.0.

**Comment by cat-kitten** [comment] 2020-02-29 21:49
Confirming this. I'm on Windows 10.

**Comment by akien-mga** [comment] 2020-02-29 22:30
Thanks for the report. We don't need more confirmations, we're well aware that the Mono bindings need fixes to account for recent changes in the master branch. This is expected.

**Comment by LinuxUserGD** [comment] 2020-03-18 13:54
Seems to be fixed now.

**Comment by neikeq** [comment] 2020-03-18 13:56
Oops, fixed by #37050

**Closed by neikeq** 2020-03-18 13:56 UTC
Labels: bug, topic:buildsystem, topic:mono

**Comment by darrylryan** [comment] 2020-03-28 08:42
This seems to be back again...

**Comment by LinuxUserGD** [comment] 2020-03-28 11:16
@darrylryan
But should be a new issue as those errors are different.

**Comment by akien-mga** [comment] 2020-03-28 11:43
There's no need to report Mono build issues at this stage, the master branch is changing a lot with compat breakage, and of course it means that the Mono bindings need to be updated.
