### ISSUE TITLE
Sprite and TextureFrame don't resize properly if their texture is resized

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#24463] opened 2018-12-18 21:59 UTC
Godot 3.0.6
Godot 3.1 alpha3

In my project, an `ImageTexture` can be resized, but another unrelated component referencing that texture gets bugs because the sprite it uses for offscreen rendering gets the texture drawn wrongly...
The bug happens with `Sprite` and `TextureRect`, and behaves slightly differently between 3.1 and 3.0.6, but it still occurs.

Reproduction steps:
1) Create an empty Godot project with an empty scene
2) Create a sprite, assign it a texture (the default icon will do)
3) Open the texture in an image editor, resize it bigger, and save it
4) Go back to Godot, notice it does not resize properly:
![image](https://user-images.githubusercontent.com/1311555/50185480-ca018200-030f-11e9-98e3-61acc85c2eb2.png)
5) Move the sprite around with the mouse, notice it goes back to normal. In 3.0.6, just clicking is enough, but you still have to interact with it. Changing its transform in the inspector does not fix it, but changing visibility does.
6) If you resize smaller, this happens:
![image](https://user-images.githubusercontent.com/1311555/50185534-ffa66b00-030f-11e9-8e97-c49aa55f78b9.png)

Workaround: you have to call `update()` on the node, so I dragged a spaghetti from the resizing code to every code depending on that texture.

**Comment by JFonS** [comment] 2018-12-18 22:18
This can also be easily reproduced by changing the size of a noise texture in the editor itself.

**Comment by KoBeWi** [comment] 2019-04-05 16:38
Isn't it the same as #20614?

**Comment by akien-mga** [comment] 2019-04-08 10:14
Seems like a duplicate of #20614 indeed.

**Closed by akien-mga** 2019-04-08 10:14 UTC
Labels: bug, topic:core
