### ISSUE TITLE
ERROR: affine_invert: Condition "det == 0" is true.

### ISSUE THREAD

**Issue by arasgonul** [godotengine/godot#47371] opened 2021-03-25 22:09 UTC
Please help I can't find a solution in google I am using godot 3.2.3

**Comment by Calinou** [comment] 2021-03-25 22:16
Duplicate of https://github.com/godotengine/godot/issues/41756.

PS: In the future, please fill in the [issue template](https://github.com/godotengine/godot/blob/master/.github/ISSUE_TEMPLATE/bug_report.md) instead of replacing it.

**Closed by Calinou** 2021-03-25 22:16 UTC
