### ISSUE TITLE
Exporting to Android errors, flickering, glitching.

### ISSUE THREAD

**Issue by zacharytyhacz** [godotengine/godot#20165] opened 2018-07-15 04:52 UTC
godot 3.0.5.stable 
* Edit - Tested on 3.0.6 stable - still persists.

**FIXED / WORKS ON GODOT 3.1 BETA 9 ON GLES2** 

windows 7 64 bit intel duo

exporting android apk to samsung galaxy s5 

with the correct export template with this version, when i export an android apk via one click deploy to my galaxy s5, it installs fine, though once I open the app the godot logo starts to flicker, turn black, and then my game project appears in glitchy colors and that's as far as it go.

I made my godot project, scripts and scenes 

set up export settings as so in picture.

added Android to my export options and left options as default

have my phone correctly hooked up via USB with developer mode on to allow one-click-deploy

select one click deploy and allow installation onto device.

app successfully installs, when i run the app on my phone it shows godot logo, flickers and may or may not turn black, then shows ' the game ' in glitchy, picture included.

I know that my phone is compatible with the OpenGL version, I'm just really not sure what is causing the issue. I managed to export to my device a 2D platformer template, with very much the same settings so I am dumbfounded to know what is causing this with my project.

Thank you anyone for any help or assistance you may have

I cherry picked lines in my log cat that had resemblance to godot. 
some lines that i see come up are....

W ResourcesManager: getTopLevelResources: /data/app/org.godotengine.srcmy_project-1/base.apk / 1.0 running in org.godotengine.srcmy_project rsrc of package null

07-15 00:10:51.350 15891 15891 D GODOT   : command_line is null? yes

07-15 00:10:51.350   818  2016 W ServiceManager: Permission failure: com.samsung.permission.SSENSOR from uid=10264 pid=15891

07-15 00:10:51.350   818  2016 D PermissionCache: checking com.samsung.permission.SSENSOR for uid=10264 => denied (103 us)

[logcat.txt](https://github.com/godotengine/godot/files/2195460/logcat.txt)

Attached is my android export settings.
![show](https://user-images.githubusercontent.com/38140593/42730649-8480b264-87c7-11e8-86c5-c01273d1752e.png)

![show2](https://user-images.githubusercontent.com/38140593/42730694-fe59e730-87c8-11e8-859d-fa7dfec52e92.png)

issue still persists 4 days later, still haven't cracked.
logcat when opening the app:
07-18 19:28:05.228  1738  1738 E ActivityThread: 	at android.app.LoadedApk$ServiceDispatcher.<init>(LoadedApk.java:1204)
07-18 19:28:05.228  1738  1738 E ActivityThread: 	at android.app.LoadedApk.getServiceDispatcher(LoadedApk.java:1098)
07-18 19:28:05.228  1738  1738 E ActivityThread: 	at android.app.ContextImpl.bindServiceCommon(ContextImpl.java:1416)
07-18 19:28:05.228  1738  1738 E ActivityThread: 	at android.app.ContextImpl.bindService(ContextImpl.java:1399)
07-18 19:28:05.228  1738  1738 E ActivityThread: 	at android.content.ContextWrapper.bindService(ContextWrapper.java:632)
07-18 19:28:05.228  1738  1738 E ActivityThread: 	at com.google.android.hotword.client.HotwordServiceClient.internalBind(HotwordServiceClient.java:117)
07-18 19:28:05.228  1738  1738 E ActivityThread: 	at com.google.android.hotword.client.HotwordServiceClient.onAttachedToWindow(HotwordServiceClient.java:65)
07-18 19:28:05.228  1738  1738 E ActivityThread: 	at com.android.launcher2.Launcher.onAttachedToWindow(Launcher.java:2272)
07-18 19:28:05.228  1738  1738 E ActivityThread: 	at com.android.internal.policy.PhoneWindow$DecorView.onAttachedToWindow(PhoneWindow.java:3784)
07-18 19:28:05.228  1738  1738 E ActivityThread: 	at android.view.View.dispatchAttachedToWindow(View.java:15805)
07-18 19:28:05.228  1738  1738 E ActivityThread: 	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3139)
07-18 19:28:05.228  1738  1738 E ActivityThread: 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1731)
07-18 19:28:05.228  1738  1738 E ActivityThread: 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1437)
07-18 19:28:05.228  1738  1738 E ActivityThread: 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7397)
07-18 19:28:05.228  1738  1738 E ActivityThread: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:920)
07-18 19:28:05.228  1738  1738 E ActivityThread: 	at android.view.Choreographer.doCallbacks(Choreographer.java:695)
07-18 19:28:05.228  1738  1738 E ActivityThread: 	at android.view.Choreographer.doFrame(Choreographer.java:631)
07-18 19:28:05.228  1738  1738 E ActivityThread: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:906)
07-18 19:28:05.228  1738  1738 E ActivityThread: 	at android.os.Handler.handleCallback(Handler.java:739)
07-18 19:28:05.228  1738  1738 E ActivityThread: 	at android.os.Handler.dispatchMessage(Handler.java:95)
07-18 19:28:05.228  1738  1738 E ActivityThread: 	at android.os.Looper.loop(Looper.java:158)
07-18 19:28:05.228  1738  1738 E ActivityThread: 	at android.app.ActivityThread.main(ActivityThread.java:7224)
07-18 19:28:05.228  1738  1738 E ActivityThread: 	at java.lang.reflect.Method.invoke(Native Method)
07-18 19:28:05.228  1738  1738 E ActivityThread: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
07-18 19:28:05.228  1738  1738 E ActivityThread: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
07-18 19:28:06.218  6266  6266 E Zygote  : v2
07-18 19:28:06.218  6266  6266 E Zygote  : accessInfo : 0
07-18 19:28:12.268   803  1630 E Watchdog: !@Sync 3193 [07-18 19:28:12.273]

**Comment by zacharytyhacz** [comment] 2018-07-17 22:47
Bumping, attempted exporting from other operating systems and devices, issue still portrays as so and I have run out of ideas on what to do next to try and fix this issue or where to look.

**Comment by AlexHolly** [comment] 2018-08-28 15:15
Do you use any Stretch mode settings? Display->Window->Stretch->Mode->Viewport?

**Comment by Toshiwoz** [comment] 2019-01-31 23:01
I'm having the same issue with 3.1 Beta3, and I realized that it flickers only if I export for GLES2, GLES3 is ok, even if it's super slow on my device (as expected).
I was testing a 3D scene, not sure if with only 2D elements gives this problem anyways.

**Comment by zacharytyhacz** [comment] 2019-02-12 03:56
> I'm having the same issue with 3.1 Beta3, and I realized that it flickers only if I export for GLES2, GLES3 is ok, even if it's super slow on my device (as expected).
> I was testing a 3D scene, not sure if with only 2D elements gives this problem anyways.

Hello, I gave up on trying to fix this bug. My theory is that it is just some Android compatibility issues with either the hardware or OS version on the device. I was testing on a **Samsung Galaxy S5, Android versoin 6.0.1**

**Comment by Toshiwoz** [comment] 2019-02-12 04:25
Hey, by any chance did you first created the project with gles3 and then switched to 2?
I did with mine, and I had a similar problem, I solved it by creatign a gles 2.0 from the beginning, then I copied all the wcenws and scripts to the new one, just don't copy project files. It worked for me.

**Comment by JohnCWakley** [comment] 2019-02-24 17:14
I followed @Toshiwoz's advice and created a new project as gles2, then moved all but the project files over and the exported android build worked as expected.

ty @Toshiwoz !

**Comment by Toshiwoz** [comment] 2019-02-25 00:06
@johncwakley, I'm glad it was helpful.
Most likely the problem is easy to fix.

**Comment by zacharytyhacz** [comment] 2019-02-25 18:25
Haven't had the chance to export my project yet again to a mobile device, will update godot to 3.1 and test again. Also, @Toshiwoz , what are your mobile device's specs that was having similar problems? Are they the same or similar as mine? I have a hunch that with this issue, it could very be well be a device hardware issue. If your specs are different, it could be something else. 

Also, have you looked into your android logcat logs for errors or anything like I posted? There could be important details

**Comment by ravisharma1987** [comment] 2019-02-25 22:36
I am having the same issue on my OnePlus One but the exported apk works fine on Nexus 7 (2013). 
Don't know is the difference between these two devices other than the obvious difference of OS.

**Comment by akien-mga** [comment] 2019-02-26 08:13
Could you attach a project that reproduces the bug?

**Comment by Toshiwoz** [comment] 2019-02-26 13:49
@zacharytyhacz I have a Huawei, for what I can see from phone info it's a MYA-L11.
I did not checked error logs, but there is a slight difference with my problem, the flickering was only at the beginning, when you see the spalsh image of Godot, then it closes (crashes?).
And as I mentioned it was fixed by creating from scratch a GLES2 project, as my problem arised when I converted a gles3 to gles2 and exported to Android. 3.0.6 does not have this option.
As s conclusion I believe it's a different root problem, even if it manifests with similar simptoms.

**Comment by akien-mga** [comment] 2019-02-26 14:25
I've seen that too, and @reduz is working on fixing it. The flicker during the splash screen seems to be while it attempts to load ETC2 textures when it's supposed to use ETC, and eventually crashes.

**Comment by akien-mga** [comment] 2019-02-27 10:11
Please test with the current master or beta 9 when it's released, it might have been fixed by recent changes.

**Comment by zacharytyhacz** [comment] 2019-02-27 21:55
@akien-mga  Ok will do.

**Comment by zacharytyhacz** [comment] 2019-03-02 05:41
Update - Tested again on same device in original post with 3.0.6, same original error and related to @ravisharma1987 's post images. Will try beta 9 when its released.

**Comment by akien-mga** [comment] 2019-03-02 09:02
@zacharytyhacz Beta 9 is released already: https://godotengine.org/article/dev-snapshot-godot-3-1-beta-9

**Comment by zacharytyhacz** [comment] 2019-03-02 19:02
Ok just tested with 3.1 beta 9 on same hardware and project....

Results with beta 9

### GLES3 - The original bug persists, no difference from 3.0.6

**### GLES2 - Works flawlessly and as intended, bug error is no longer present.**

**Closed** 2019-03-02 19:04 UTC
Labels: bug, high priority, platform:android, topic:rendering
