### ISSUE TITLE
Viewport render_target_update_mode doesn't switch to UPDATE_DISABLED when set to UPDATE_ONCE.

### ISSUE THREAD

**Issue by CedNaru** [godotengine/godot#48729] opened 2021-05-15 08:35 UTC
**Godot version:**
3.3-stable

**OS/device including version:**
Windows 10

**Issue description:**
When setting a Viewport update mode to UPDATE_ONCE, the property is never set to UPDATE_DISABLED afterward. 
That update is only made in the internal implementation of the Visual Server but the Node property stays unaffected.

This doesn't follow what the doc is actually stating:
**UPDATE_ONCE = 1 --- Update the render target once, then switch to UPDATE_DISABLED.**

The Node behavior must be fixed or the documentation updated to match it.

**Steps to reproduce:**

- Create a Viewport with the render_target_update_mode property set to UPDATE_ONCE.
- Wait for the next frame so the rendering is done.
- Check the render_target_update_mode property, it should be still set to UPDATE_ONCE.

**Minimal reproduction project:**
Just use the 3D in 2D demo in the official Godot demo projects.

**Comment by lawnjelly** [comment] 2021-05-15 12:39
This seems like an unclear documentation issue.

Given the one way flow of information from the client to the visual server, it isn't easy to backwards update information in the UI. And it doesn't seem required, just a mismatch of expectations. The client could attempt to 'guess' when an update had occurred, but that seems bug prone and overkill.

**Comment by clayjohn** [comment] 2021-05-15 16:09
Duplicate of https://github.com/godotengine/godot/issues/33351

**Closed by clayjohn** 2021-05-15 16:09 UTC
Labels: documentation, junior job, topic:rendering
