### ISSUE TITLE
Confusing size behaviour when controls are in a HBoxContainer

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#12824] opened 2017-11-10 22:14 UTC
Godot 3.0
Windows 10 64 bits

I'm trying to make it so a control expands vertically within an horizontal container while keeping their width, but I'm failing so far... Everything I put inside ends up with a width of zero.
There is either a bug, or *something implicit to know* for this to work...

Repro steps:

1) Create a HBoxControl

![image](https://user-images.githubusercontent.com/1311555/32680815-cfb904ba-c66c-11e7-9222-89682230b831.png)

2) Create a ColorRect inside, notice it spawns with zero width

![image](https://user-images.githubusercontent.com/1311555/32680820-d465004a-c66c-11e7-8816-004cdce831cb.png)

3) Give the ColorRect some width by dragging the right handle in the viewport

![image](https://user-images.githubusercontent.com/1311555/32680828-d89d7764-c66c-11e7-9de6-011a1e3afb79.png)

4) Resize the container, notice the ColorRect disappears as its size goes back to zero

Edit: apparently the only thing that worked was to set a minimum size. Is there a reason why it works that way? It's not very intuitive... and also not documented

**Comment by groud** [comment] 2017-11-11 17:33
Within a container, the size of the node does not matter, it is overriden by the container.
Thus this is a normal behaviour.

**Comment by Zylann** [comment] 2017-11-11 17:38
@groud this is where things get interesting: in a HBoxContainer, only the height and X position are relevant to change. I don't see any reason why the container would set the width to zero.

**Comment by groud** [comment] 2017-11-11 17:44
Yeah, the way control nodes work is a little bit inconsistent in some situations, but that's not a bug.
A container modifes the size of its children, and uses the minimum size to avoid shrinking it too much. Some nodes, like ColorRect, do not have a minimum size. Thus, if you want it to have one, you have to use the custom minimum size.

**Comment by Zylann** [comment] 2017-11-11 17:45
@groud that should be documented at least :)

**Comment by groud** [comment] 2017-11-11 17:51
See [here](http://docs.godotengine.org/en/latest/learning/features/gui/custom_gui_controls.html#sizing).

Still I understand that it can be confusing, But I'm not sure what we can do about it. Maybe edit the minimum size instead of the normal one if we edit a child of a container ?

**Comment by Zylann** [comment] 2017-11-11 18:01
Could it be added to BoxContainer class documentation too? Because as a developer, that's where I ended up first when coding (and there was no link to the tutorial page either).

**Comment by groud** [comment] 2017-11-11 18:07
It's common behaviour of the whole container/control nodes system. I guess it could be added to the Container doc. :)

**Comment by Linicks** [comment] 2018-04-17 18:25
I would say, that the container system has been a stumbling block for me, and is why I'm reading all the issues trying to get a better understanding of how it works ("Yes, I've already read the current docs :)" ).  Based on these threads, it's clear that I'm not the only one struggling with this.  I know the system makes sense once you understand it, but it isn't consistent with most other UI tools.  Not saying that it needs to be necessarily, but better documentation, and tutorials are needed to reduce the frustration of trying to learn something that doesn't conform to typical behavior and nomenclature in some instances.

**Comment by groud** [comment] 2018-09-19 16:48
I'll close this issue as superseded by #20750

**Closed by groud** 2018-09-19 16:48 UTC
Labels: bug, topic:editor, usability
