### ISSUE TITLE
"Uniforms were never supplied for set (3) at the time of drawing, which are required by the pipeline" after freeing a GPUParticle2D

### ISSUE THREAD

**Issue by malaVydra** [godotengine/godot#82489] opened 2023-09-28 16:32 UTC
### Godot version

4.1.1.stable.mono

### System information

Godot v4.1.1.stable.mono - macOS 13.6.0 - Vulkan (Forward+) - integrated Apple M1 - Apple M1 (8 Threads)

### Issue description

I have a Node2D which is responsible for emitting 2 children (GPUParticles2D).

I also added the timer to the parent node and connected its Timeout signal to free the parent.

The error I get is:

```
E 0:00:07:0555   compute_list_dispatch: Uniforms were never supplied for set (3) at the time of drawing, which are required by the pipeline
  <C++ Error>    Method/function failed.
  <C++ Source>   drivers/vulkan/rendering_device_vulkan.cpp:8026 @ compute_list_dispatch()
```

I remember having this problem around 6 months ago and don't remember finding an adequate solution. What fixed it back then was changing the GPUParticle2D node type to CPUParticle2D.

### Steps to reproduce

- Create a scene and add Node2D to it
- Add a few GPUParticle2D children (duplicate one a few times favorably)
- Add a timer child

- Add a script to the parent node
- Set the timer WaitTime to the particles' LifeTime
- In the _Ready() method, add the listener to the Timeout signal of a timer, which frees the node
- In the _Ready() method, emit the particles

### Minimal reproduction project

N/A

**Comment by jsjtxietian** [comment] 2023-09-28 17:06
Maybe related #82257

**Comment by bitsawer** [comment] 2023-09-29 05:35
I can't seem to reproduce this, but the instructions seem a bit vague.

Could you attach a MRP test project? It will give a common base to all testers to see if this only happens on specific systems for example. And yes, there is a good chanche that this is a duplicate of https://github.com/godotengine/godot/issues/82257, but testing this to make sure would still be useful.

**Closed** 2023-10-11 22:22 UTC
Labels: bug, topic:rendering, needs testing
