### ISSUE TITLE
Stylebox appears differently in the editor and when running the project

### ISSUE THREAD

**Issue by Elesh-Norn** [godotengine/godot#96779] opened 2024-09-10 07:55 UTC
### Tested versions

- Godot_v4.3-stable

### System information

Godot v4.3.stable - Windows 10.0.22631 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3070 (NVIDIA; 32.0.15.5612) - AMD Ryzen 9 5900X 12-Core Processor (24 Threads)

### Issue description

I have a Button Node with a theme, that points to a Stylebox. It appears correctly in the editor. When Running in Game, or via F6. It displays the style of another Stylebox.

If I remove the style of the button, it is displayed the same way in a correct manner.

Here is the setup:
![image](https://github.com/user-attachments/assets/c80abfc1-14b6-43d2-adc8-3a617297c83b)
I have a theme, applied to a button, named Cancel. The normal button style is being filled by the Stylebox Resource marqued as 1. It is displayed correctly in the editor preview.

![image](https://github.com/user-attachments/assets/6758b963-a04e-4bc2-b050-39caecb48050)
When ran with F6 or in Game, it displays style from Stylebox Resource marqued as 2.

Interestingly, if I remove any style:
![image](https://github.com/user-attachments/assets/b0f0846c-8361-49e2-a92d-a440c1ff3c78)

It gets displayed correctly:
![image](https://github.com/user-attachments/assets/7726596e-f770-4ff0-9a20-4ed4f173be35)

I tried removing .godot and it did not fix the problem.
The .tres file points to correct resources.
 

### Steps to reproduce

Interestingly the MRP I came through with copy pasting files is a bit cursed:

- Open General_theme.tres with the theme editor
- In the Button Normal Style, replace "NewInventoryBagButton.tres" with "InventoryBagButton.tres"
- The Editor view should show a different looking button.
- Launch the Button Scene with F6
- First Stylebox is shown

### Minimal reproduction project (MRP)

[bugstyleboxtheme.zip](https://github.com/user-attachments/files/16941326/bugstyleboxtheme.zip)

**Comment by kleonc** [comment] 2024-09-10 10:08
The issue seems to be that within MRP different resources share the same UID.

Both `res://UI/InventoryBagButton.tres` and `res://UI/NewInventoryBagButton.tres` start with:
```tres
[gd_resource type="StyleBoxFlat" format=3 uid="uid://bg6853reyfo3a"]
```
Both `res://UI/InventoryBagButtonFocus.tres` and `res://UI/NewInventoryBagButtonFocus.tres` start with:
```tres
[gd_resource type="StyleBoxFlat" format=3 uid="uid://bw8sax77qyv4"]
```
Both `res://UI/InventoryBagButtonHovered.tres` and `res://UI/NewInventoryBagButtonHovered.tres` start with:
```tres
[gd_resource type="StyleBoxFlat" format=3 uid="uid://cdgfd5h85x5w5"]
```

Same duplicated UIDs referenced by `res://UI/General_theme.tres`:
```tres
[gd_resource type="Theme" load_steps=7 format=3 uid="uid://ba0ow554cjlyn"]

[ext_resource type="StyleBox" uid="uid://cdgfd5h85x5w5" path="res://UI/InventoryBagButtonHovered.tres" id="2_ixufh"]
[ext_resource type="StyleBox" uid="uid://bw8sax77qyv4" path="res://UI/NewInventoryBagButtonFocus.tres" id="2_kes41"]
[ext_resource type="StyleBox" uid="uid://cdgfd5h85x5w5" path="res://UI/NewInventoryBagButtonHovered.tres" id="3_2fhj0"]
[ext_resource type="StyleBox" uid="uid://bg6853reyfo3a" path="res://UI/InventoryBagButton.tres" id="3_87ayk"]
[ext_resource type="StyleBox" uid="uid://bg6853reyfo3a" path="res://UI/NewInventoryBagButton.tres" id="4_m0b3y"]
[ext_resource type="StyleBox" uid="uid://b32upgu2lswx3" path="res://Combat/CombatUI/ButtonFocused.tres" id="5_gbmfm"]
```

---

So the question is how it ended up like that. I suspect copy-paste through the OS file manager?

Tested (v4.3.stable.official [77dcf97d8]) and when duplicating via Godot's file system dock new UIDs are assigned, as expected.

Probably resources with duplicated UIDs should be somehow detected? And if so, then it should prompt the user to resolve the conflicts (determine which resource-with-duplicated-UID other resources should actually reference)? :thinking:

Seems like duplicate of / same cause as #96313.

**Comment by Elesh-Norn** [comment] 2024-09-10 10:42
I had a weird flow where, where I modified in place InventoryBag which was already created.
Once I was happy with the change, I duplicated via the interface and called it NewInventoryBag.
Restored InventoryBag with git.

Here it gets blurry, I think I observed the theme was pointed to NewInventoryBag, drag InventoryBag in place of the new one and saved.

I tried replicating this flow in a MRP, but did not manage, the updates of references were done correctly.

**Comment by kleonc** [comment] 2024-09-10 13:56
> I had a weird flow where, where I modified in place InventoryBag which was already created.
> Once I was happy with the change, I duplicated via the editor interface and called it NewInventoryBag.
> Restored InventoryBag with git.

Are you sure that's exactly what you did? I'm not sure why such steps would result in duplicated UIDs.

If you'd instead:
1. Modify in place InventoryBag which was already created.
2. Duplicate it.
3. Rename the original InventoryBag to NewInventoryBag.
4. Rename the duplicate to InventoryBag.
5. Restore InventoryBag from git.

Or:

1. Modify in place InventoryBag which was already created.
2. Rename it to NewInventoryBag.
3. Restore InventoryBag from git.

Then it would make sense to end up with both having the same UID. Otherwise that's a mystery to me why it would happen.

> Here it gets blurry, I think I observed the theme was pointed to NewInventoryBag

This would mean that at this point NewInventoryBag had the same UID as the original InventoryBag.

**Comment by Elesh-Norn** [comment] 2024-09-11 15:55
Well I was sure enough to post about it and try to MRP. Now it's been two days.

Scenario 1 seems most likely but it seems insane I would do that 3 times in a row.

**Comment by WhalesState** [comment] 2024-09-18 02:50
I've already duplicated the resources, and Godot generates a unique UID each time. However, when I duplicate them via Windows file manager (copy-paste), the issue occurs.

Godot should detect duplicated UIDs when the `FileSystem` changes. Renaming the issue to 'Resources uses the same UID when duplicated from the file manager' would make it clearer and easier to pick up.

**Comment by Zireael07** [comment] 2024-09-18 07:18
@WhalesState In that case, it is a duplicate of another existing issue

**Comment by Elesh-Norn** [comment] 2024-09-18 09:33
Knowing where it stemmed from, enabled me to take care of that issue. If Godot could detect and warn me that two different resources have the same UUID, I wouldn't have lost dev time.

**Comment by Calinou** [comment] 2024-09-18 13:02
Thanks for the report! Consolidating with https://github.com/godotengine/godot/issues/96313, as this is due to the same cause.

**Closed by Calinou** 2024-09-18 13:02 UTC
Labels: bug, topic:core, topic:gui
