### ISSUE TITLE
The difference between an angular damp of 0.999 and 1 is massive.

### ISSUE THREAD

**Issue by SimonCadge** [godotengine/godot#40131] opened 2020-07-05 11:04 UTC
**Godot version:**
3.2.2 Stable

**OS/device including version:**
GLES3 Windows 10 RTX 2070 Super

**Issue description:**
I'm creating a tank game. The wheel tread things are separate rigid bodies which are moved forwards and backwards, and they are connected to the body by Generic6DOFJoints. If I don't apply angular damping then the tank can achieve the same angular velocity as it can achieve linear velocity, which is unwieldy, but applying an angular damping of 0.999 is too little damping and 1 is too much.

![Sound-Effights-Research-DEBUG-20](https://user-images.githubusercontent.com/11338764/86531172-f3184200-beb6-11ea-9416-c0869040cd9b.gif)

That gif is with the angular damping set to 0.999. I achieve a top angular velocity of around 5.
![Sound-Effights-Research-DEBUG-20 (1)](https://user-images.githubusercontent.com/11338764/86531205-2a86ee80-beb7-11ea-88f1-9fef907a1f21.gif)

That gif is with the angular damping set to 1. I achieve a top angular velocity of around 0.5.

Ideally I'd like somewhere in the middle but I can't select a value between 0.999 and 1.

**Minimal reproduction project:**
https://github.com/SimonCadge/sound-effights-godot
Clone that repo and run the default scene. Then, go into the Tank.tscn scene and modify the angular damp of the body node to 0.999.

**Comment by Calinou** [comment] 2020-07-05 11:54
> Ideally I'd like somewhere in the middle but I can't select a value between 0.999 and 1.

You can set it manually in a script to work around the precision limit defined in the property hint.

**Comment by SimonCadge** [comment] 2020-07-05 12:32
Ah, ok thanks. I set the damp to 0.9999999 in a script, which works as I want it to.
I'd still say that this is an issue. Values above 1 didn't make any difference, a value of 1 functioned the same as a value of 100. And values below 1 barely seemed to change anything, since most of the values that actually change things are between 0.999 and 1. For a long time I thought that angular damp was actually just a toggle.

**Comment by madmiraal** [comment] 2020-07-05 17:27
Duplicate of #19182, fixed in 4.0 with  #37314 and in 3.2.3 with #39084.

**Closed by madmiraal** 2020-07-05 17:27 UTC
Labels: topic:physics
