### ISSUE TITLE
[C#] Godot fails to export project including EditorPlugin

### ISSUE THREAD

**Issue by pikol93** [godotengine/godot#41196] opened 2020-08-12 06:14 UTC
**Godot version:**
Godot_v3.2.2-stable_mono_win64

**OS/device including version:**
Windows 10
GLES3
Nvidia GTX 1050Ti

**Issue description:**
Godot fails to export a project when it contains a class that inherits from `EditorPlugin`.
```
Project "CSharpExportBug.sln" (Build target(s)):
	Message: Building solution configuration "ExportDebug|Any CPU".
	Project "CSharpExportBug.csproj" (default targets):
		Skipping target "GenerateTargetFrameworkMonikerAttribute" because all output files are up-to-date with respect to the input files.
		Csc: C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\Roslyn\csc.exe /noconfig /nowarn:1701,1702 /nostdlib+ /errorreport:prompt /warn:4 /define:GODOT_PC;GODOT_S3TC;GODOT_WINDOWS;GODOT_S3TC;GODOT_64;GODOT;DEBUG /highentropyva+ /reference:D:\Godot\CSharpExportBug\.mono\assemblies\Debug\GodotSharp.dll /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.7\mscorlib.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.7\System.Core.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.7\System.dll" /debug+ /debug:portable /optimize- /out:.mono\temp\obj\ExportDebug\CSharpExportBug.dll /ruleset:"C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Team Tools\Static Analysis Tools\\Rule Sets\MinimumRecommendedRules.ruleset" /subsystemversion:6.00 /target:library /utf8output /langversion:7.3 Properties\AssemblyInfo.cs SomeEditorPlugin.cs ".mono\temp\obj\ExportDebug\.NETFramework,Version=v4.7.AssemblyAttributes.cs"
		Csc: Using shared compilation with compiler from directory: C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\Roslyn
		SomeEditorPlugin.cs(3,33): error CS0246: The type or namespace name 'EditorPlugin' could not be found (are you missing a using directive or an assembly reference?) [D:\Godot\CSharpExportBug\CSharpExportBug.csproj]
	Done building project "CSharpExportBug.csproj" -- FAILED.
Done building project "CSharpExportBug.sln" -- FAILED.

```

**Steps to reproduce:**
1. Create a new project
2. Add a new class that inherits from `EditorPlugin` to solution
3. Try to export the project

**Minimal reproduction project:**
[CSharpExportBug.zip](https://github.com/godotengine/godot/files/5060892/CSharpExportBug.zip)

**Comment by van800** [comment] 2020-08-12 19:53
I expect it to be not a bug.
It can be fixed by adding condition to corresponding Compile Include, like in this example: 
https://github.com/van800/GodotSample2/commit/5180014eb7e17f035dd6da337cf6bed119b18d51#diff-58b3e37226e0d4200e1fdf4ddf52abd6R63-R64

**Comment by raulsntos** [comment] 2020-08-12 20:46
You have to use the define constant `TOOLS` like so:
```cs
#if TOOLS
using Godot;

public class SomeEditorPlugin : EditorPlugin
{
	// Code here...
}
#endif
```
The code inside the if won't be compiled when exporting, which makes sense in this case since `EditorPlugin` is not available when the game is exported. It's like `UNITY_EDITOR` in Unity.

The use of the define constant `TOOLS` can be seen in the [documentation for making plugins](https://docs.godotengine.org/en/stable/tutorials/plugins/editor/making_plugins.html#the-script-file) (in the C# code example) although it's never actually explained.

So I don't think this is a bug but maybe an issue with lack of documentation about this.

---

Of course, @van800 solution works too, but I prefer not to edit the `.csproj` manually.

**Comment by neikeq** [comment] 2020-08-12 21:48
Yup, access to the editor API (from the `GodotSharpEditor` assembly) must be surrounded with `#if TOOLS` or else it will result in build issues when exporting the game.
This is likely to change in the future. Most likely there will be a separate C# project for working with the editor API.

**Closed by neikeq** 2020-08-12 21:48 UTC
