### ISSUE TITLE
iOS GLES2 3D Rendering is Broken

### ISSUE THREAD

**Issue by semirix** [godotengine/godot#27191] opened 2019-03-18 02:22 UTC
**Godot version:** 3.1
**OS/device including version:**
iOS SDK Version: 10
iOS Version: 12

**Issue description:**
There seems to be some major rendering issues present in iOS GLES2 3D renderer. Whatever is rendering the controls seems to be fine though.

**What it currently looks like:**
![image](https://user-images.githubusercontent.com/7454145/54502817-a686bb80-4980-11e9-9bdd-aa3efb6fbead.png)

**What it should look like:**
![image](https://user-images.githubusercontent.com/7454145/54517212-2464ba00-49b5-11e9-8172-d6e8e37f4423.png)

**Steps to reproduce:**
Try making a new iOS project in GLES2 mode and adding a couple of meshes with textures.

**Minimal Reproduction project:**
[iOS GLES2 Bug.zip](https://github.com/godotengine/godot/files/3052227/iOS.GLES2.Bug.zip)

**Comment by clayjohn** [comment] 2019-03-18 03:32
What is this supposed to look like? Could you post a picture of what it looks like with the GLES3 backend? Currently you haven't given enough information for someone to try and fix the issue.

**Comment by semirix** [comment] 2019-03-18 08:35
@clayjohn I have added a second reference picture.

**Comment by akien-mga** [comment] 2019-04-02 10:24
Might have been improved by @samgreen's #27071 (for a different bug, but it might have caused rendering issues). This fix will be included in 3.1.1.

Would you be able to provide a minimal reproduction project to make it easier to debug and fix?

**Comment by semirix** [comment] 2019-04-02 10:34
@akien-mga I'll try to, this occurred in a semi-large private project so I don't know how involved creating a reproduction will be.

**Comment by semirix** [comment] 2019-04-08 00:38
@akien-mga I have included a minimal reproduction project. I am building it on an iPhone XR with iOS 12.1.

Also, considering that this is a pretty severe rendering issue, resolving it 3.2 seems quite far away in my opinion. I understand the team has it's priorities but we're trying to release and this is a showstopper for us and likely would be for anyone else experiencing this. Is there any chance at all of resolving this in a sooner release?

**Comment by akien-mga** [comment] 2019-04-08 07:02
> Also, considering that this is a pretty severe rendering issue, resolving it 3.2 seems quite far away in my opinion. I understand the team has it's priorities but we're trying to release and this is a showstopper for us and likely would be for anyone else experiencing this. Is there any chance at all of resolving this in a sooner release?

3.2 is the current milestone, as it's our next main release. The 3.1 milestone is closed, as 3.1 was released. We still use it for bugs that impact *only* 3.1, but this one is likely reproducible in the master branch and 3.2 too.

Once it's fixed in the master branch, it can be backported to the stable 3.1 maintenance releases.

**Comment by semirix** [comment] 2019-04-08 08:24
@akien-mga Ahh okay, I was unclear on what the process was. Thank you!

**Comment by akien-mga** [comment] 2019-04-15 19:39
@samgreen Please mention the reason for closing. Did you confirm that #27071 fixed it?

**Comment by samgreen** [comment] 2019-04-15 23:42
@akien-mga Was a misclick, thanks for the ping!

**Comment by semirix** [comment] 2019-04-29 02:28
Just tested on 3.1.1, #27071 did not fix the issue.

**Comment by ssemakin** [comment] 2019-06-06 10:02
guys, any follow up on this? I'm on latest master 197b65f32ac811f79bc5599fbfe8cf83914b6873 and looks like hitting exactly this issue with iOS build on GLES2. I can provide a simple project to try.

**Comment by semirix** [comment] 2019-08-30 04:05
Any news or progress on this issue?

**Comment by clayjohn** [comment] 2019-08-30 05:48
Nothing has changed. Sorry. Currently not many contributors own iPhones to test on, so progress is slow.

**Comment by aaqib7** [comment] 2019-12-01 19:17
Opengles 2 is not rendering 3d objects/materials/textures on iPhone X either. I have tested using the 'Minimal Reproduction Project'. I am usig Opengles 2 since '3' does not given an optimal FPS and it will be poor on lower end devices if it's already poor on an iPhone X.

This is how it's meant to look like:
![Screenshot 2019-12-01 at 19 14 27](https://user-images.githubusercontent.com/4943715/69918879-e0481580-146e-11ea-9e83-b24eaaa6a20e.png)

However, it looks like this on an iPhone X:
![iphone_x_opengles2](https://user-images.githubusercontent.com/4943715/69918912-269d7480-146f-11ea-886e-eb7a1358f9d9.JPG)

Does Open GLES 2.0 render 3D objects on any iOS devices?

**Comment by aaqib7** [comment] 2019-12-01 19:32
Also, if i switch to Open GLES 3.0 then the texture renders fine (128x128).

I am getting console errors in Open GLES 2 (iPhone X):

----------------------------------------------------------------------
2019-12-01 19:31:40.536483+0000 test[48437:11480397] [DYMTLInitPlatform] platform initialization successful
*********** main.m
running app main
Path: /var/containers/Bundle/Application/CA00FA79-E4AC-4D5B-AA84-4AA9887ABFAD/test.app
godot_iphone /var/containers/Bundle/Application/CA00FA79-E4AC-4D5B-AA84-4AA9887ABFAD/test.app/test
cwd /private/var/containers/Bundle/Application/CA00FA79-E4AC-4D5B-AA84-4AA9887ABFAD/test.app
os created
setting data dir to /var/mobile/Containers/Data/Application/2FF695C3-572C-46EE-BDC4-85E2F603268A/Documents from /var/mobile/Containers/Data/Application/2FF695C3-572C-46EE-BDC4-85E2F603268A/Documents
setup 0
after init super 0x157e26060
2019-12-01 19:31:40.696139+0000 test[48437:11480359] Metal GPU Frame Capture Enabled
2019-12-01 19:31:40.696650+0000 test[48437:11480359] Metal API Validation Enabled
2019-12-01 19:31:40.759354+0000 test[48437:11480359] Setting up an OpenGL ES 2 context. Based on Project Settings "rendering/quality/driver/driver_name"
******** screen size 1125, 2436
after init gles 0x157e26060
******** adding observer for sound routing changes
******** adding observer for keyboard show/hide
cadisaplylink: 1start animation!
******** screen size 1125, 2436
2019-12-01 19:31:40.832881+0000 test[48437:11480359] +[CATransaction synchronize] called within transaction
2019-12-01 19:31:40.878099+0000 test[48437:11480359] +[CATransaction synchronize] called within transaction
2019-12-01 19:31:40.887049+0000 test[48437:11480359] +[CATransaction synchronize] called within transaction
2019-12-01 19:31:40.896281+0000 test[48437:11480359] OpenGL ES 2.0 Renderer: Apple A11 GPU
OpenGL ES 2.0 Renderer: Apple A11 GPU
2019-12-01 19:31:40.969134+0000 test[48437:11480359] [MC] System group container for systemgroup.com.apple.configurationprofiles path is /private/var/containers/Shared/SystemGroup/systemgroup.com.apple.configurationprofiles
2019-12-01 19:31:40.970509+0000 test[48437:11480359] [MC] Reading from public effective user settings.
2019-12-01 19:31:41.439588+0000 test[48437:11480359] 500 error
2019-12-01 19:31:41.439678+0000 test[48437:11480359] [Error] setCurrentGameFromInternal: ignoring -- nil bundleIdentifier :(null)
2019-12-01 19:31:41.444501+0000 test[48437:11480359] 500 error
2019-12-01 19:31:41.452383+0000 test[48437:11480359] 500 error
2019-12-01 19:31:41.485791+0000 test[48437:11480359] 500 error
2019-12-01 19:31:41.486735+0000 test[48437:11480359] [Error] _authenticateUsingAlert:Faied to authenticate player with existing credentials.Error: Error Domain=GKErrorDomain Code=15 "The requested operation could not be completed because this application is not recognised by Game Center." UserInfo={GKServerStatusCode=5019, NSLocalizedDescription=The requested operation could not be completed because this application is not recognised by Game Center., NSUnderlyingError=0x280125f20 {Error Domain=GKServerErrorDomain Code=5019 "status = 5019, no game matching descriptor: ios:com.aaqib.hafeez.testgles:1.0:1.0+-1" UserInfo={GKServerStatusCode=5019, NSLocalizedFailureReason=status = 5019, no game matching descriptor: ios:com.aaqib.hafeez.testgles:1.0:1.0+-1}}}
2019-12-01 19:31:41.498563+0000 test[48437:11480359] [Error] startAuthenticationForExistingPrimaryPlayer:Failed to Authenticate player.Error: Error Domain=GKErrorDomain Code=15 "The requested operation could not be completed because this application is not recognised by Game Center." UserInfo={NSLocalizedDescription=The requested operation could not be completed because this application is not recognised by Game Center.}
2019-12-01 19:31:41.502485+0000 test[48437:11480359] 500 error

------------------------------------------------------------------------------------

**Comment by Calinou** [comment] 2019-12-01 20:40
@aaqib7 Which Godot version are you using? There have been many fixes to rendering on iOS since 3.1.1 was released. Try 3.1.2 or [3.2 beta 2](https://godotengine.org/article/dev-snapshot-godot-3-2-beta-2).

**Comment by aaqib7** [comment] 2019-12-01 22:59
@Calinou I was using Godot 3.1.1. I have just tried it on 3.2 Beta and it's still the same (as shown above).

I am getting the following error in the console: _DrawView: 500 error_

I have tried it on iPhone X and iPhone 6 and doesn't work on both which suggest OpenGL ES 2 is totally broken on iOS for 3D.

I am using XCode 10.2.1

**Comment by jahd2602** [comment] 2019-12-19 22:55
@aaqib7 The 500 error is apparently harmless. Issue that describes it: #31907 

The lines that print that are:

https://github.com/godotengine/godot/blob/2a4c528d067826dd1af865c93c3dc945c9a0e196/platform/iphone/gl_view.mm#L494-L495

The `DrawView:` part was added recently, that's why it was impossible to locate it before.

As a temporary fix, just comment those two lines while debugging.

**Comment by clayjohn** [comment] 2020-01-13 03:27
Unfortunately, contributions to IOS specific bugs are few and far between. Accordingly, I am bumping this back to 3.2.1/4.0.

**Comment by clayjohn** [comment] 2020-05-03 18:12
@lawnjelly and I have been exploring some problems with iOS in the 2D renderer and we may have struck on something that could be causing problems in both the 2D and 3D renderer. If so, there may be a potential fix for this in the works if someone is willing to build and test changes (neither of us have an iOS device to test on, so this has been very difficult)

**Comment by akien-mga** [comment] 2020-10-21 18:03
Can anyone check if this is still reproducible in 3.2.3-stable or 3.2.4-beta1? There have been fixed in this area (notably #38453).

**Comment by Calinou** [comment] 2021-01-14 13:57
Closing due to lack of response. Please open a new issue with a minimal reproduction project attached if you can still reproduce this.

**Closed by Calinou** 2021-01-14 13:57 UTC
Labels: bug, platform:ios, topic:rendering
