### ISSUE TITLE
Floating precision

### ISSUE THREAD

**Issue by wf192** [godotengine/godot#6900] opened 2016-10-22 16:56 UTC
Antergos Linux - Godot v2.2 alpha_build

When adding a 0.0000001 to any number, the resulting print, will be the same number.

```
func _ready():
    var a = Vector3(0,0,0)
    var b = Vector3(0,0,0)
    a += Vector3(0.0000001, 0.0000001, 0.0000001)
    printt(a, b, a != b)
    printt(1 + 0.0000001)
```

**Comment by akien-mga** [comment] 2016-10-22 17:49
That is pretty common when using single precision floats :)

**Comment by Zylann** [comment] 2016-10-23 13:07
Godot is built with reals being `float`, if you want that much precision you should build it with `double`, or change the approach to your problem by changing the scale or introducing relative coordinates.

**Comment by tagcup** [comment] 2016-10-25 17:32
@wf192 You need to compile Godot with `REAL_T_IS_DOUBLE` defined.
BTW, shouldn't other defs in math_defs.h (such as `CMP_EPSILON`) be different when using 32-bit and 64-bit floats?

**Comment by bojidar-bg** [comment] 2017-04-21 07:45
Marking as duplicate of #288, plus, I think it got mostly done in 3.0 already.

**AFAIR** (but some of it might still be missing), GDScript was ported to use doubles internally, though I can't find the commit. Variant was also made to use them, and `REAL_T_IS_DOUBLE` was made default.

**Closed by bojidar-bg** 2017-04-21 07:45 UTC
Labels: discussion, topic:core

**Comment by tagcup** [comment] 2017-04-21 15:07
There's actually still a bit of work for enabling `REAL_T_IS_DOUBLE`, I need to get confirmation from @reduz on a few points once he's back.

**Comment by tagcup** [comment] 2017-04-21 17:47
Just to clarify, `REAL_T_IS_DOUBLE` isn't enabled just yet (it actually doesn't even compile with it at the moment), but will hopefully get around it before 3.0.

**Comment by reduz** [comment] 2017-04-21 17:52
I dont think enabling doubles works.. we are much closer, but likely have
to test it to see if something breaks. Also variant serializer does not
support doubles, we should add the flag for that in the format.

**Comment by Zylann** [comment] 2017-04-21 19:50
Will it affect GDNative as well?

**Comment by karroffel** [comment] 2017-04-21 20:04
@Zylann the C API would need to be adapted when signatures of the originals change. Also then method signatures of "raw" methods change, so the generated bindings would use `double` instead of `float`

**Comment by tagcup** [comment] 2017-04-21 22:20
You wouldn't need to change anything if you're using `real_t` (rather than `float` or `double`) for stuff defined as `real_t`. Is it not the case with GDNative?

**Comment by Zylann** [comment] 2017-04-22 08:39
If someone compiles the engine with `float` it won't work with GDNative modules, unless they are also recompiled. Otherwise I guess they would crash.

**Comment by tagcup** [comment] 2017-04-22 15:44
It can be documented I guess.
Current official is float BTW.

**Comment by RicardRC** [comment] 2020-01-06 14:22
Using the #define REAL_T_IS_DOUBLE gave me a hell of a weekend with crashes on octree insert. My fault, for using things without looking here if they were ready.

**Comment by jamie-pate** [comment] 2024-07-22 18:35
For posterity, REAL_T_IS_DOUBLE will absolutely not work with embree occlusion culling (as of godot 4.3-beta3)
Godot passes `RTC_FORMAT_FLOAT3` without checking if `REAL_T_IS_DOUBLE` is defined

**Comment by Calinou** [comment] 2024-07-22 19:40
> For posterity, REAL_T_IS_DOUBLE will absolutely not work with embree occlusion culling (as of godot 4.3-beta3) Godot passes `RTC_FORMAT_FLOAT3` without checking if `REAL_T_IS_DOUBLE` is defined

Can you open a dedidcated issue for this?

**Comment by jamie-pate** [comment] 2024-07-22 21:43
Dedicated issue,
https://github.com/godotengine/godot/issues/94638
There doesn't seem to be a `RTC_FORMAT_DOUBLE3` so we'd have to convert Vector3 to floats for this to work (should be ok because occlusion culling probably shouldn't be high precision even if the rest of your project is.
