### ISSUE TITLE
Cant use a PoolRealArray Variable as a Global Variable

### ISSUE THREAD

**Issue by meisamsafavi** [godotengine/godot#60162] opened 2022-04-12 03:21 UTC
### Godot version

3.4.4 stable

### System information

Windows 10 , GTX 1050ti , GLES3

### Issue description

After Creating a Script within a PoolRealArray variable and adding the script to autoload to use the defined variable as a global buffer, unfortunately it's not possible to read or write on it on other scripts.

### Steps to reproduce

1.Make a Scripts and call it Globals and define a variable of type PoolRealArray to use it as a buffer
2.Add the created script to Autoload to have access on other scripts
3.Try to append some data and print length of buffer
there you can see the 0 length

**Comment by timothyqiu** [comment] 2022-04-12 04:49
Duplicate of #56473

**Closed by timothyqiu** 2022-04-12 04:49 UTC
