### ISSUE TITLE
Viewport: "set_attach_to_screen_rect" function is not respected by _gui_input events.

### ISSUE THREAD

**Issue by API-Beast** [godotengine/godot#21147] opened 2018-08-18 13:17 UTC
There are several places where _gui_input transforms mouse or touch coordinates. They all use get_global_transform_with_canvas ([canvas_item.cpp:350](https://github.com/godotengine/godot/blob/62f2a8aadb28572f6d6a1fd382312e788fada3bc/scene/2d/canvas_item.cpp#L350)) which does not take into account the to_screen_rect, only the canvas transform.

_input on the other hand is transformed using the function "_make_input_local" ([viewport.cpp:1188](https://github.com/godotengine/godot/blob/master/scene/main/viewport.cpp#L1188)) which in addition to the canvas transform also takes into account the "_get_input_pre_xform", which calculates a transformation based on the to_screen_rect.

This causes Godot to fail to detect GUI clicks in setups where Viewports are used as a texture and the render resolution doesn't match the screen size, while _input based click detection works fine.

```cpp
Ref<InputEvent> Viewport::_make_input_local(const Ref<InputEvent> &ev) {

	Vector2 vp_ofs = _get_window_offset();
	Transform2D ai = get_final_transform().affine_inverse() * _get_input_pre_xform();

	return ev->xformed_by(ai, -vp_ofs);
}

Transform2D Viewport::_get_input_pre_xform() const {
	Transform2D pre_xf;

	if (to_screen_rect != Rect2()) {
		pre_xf.elements[2] = -to_screen_rect.position;
		pre_xf.scale(size / to_screen_rect.size);
	}

	return pre_xf;
}
```

**Comment by KoBeWi** [comment] 2020-07-29 16:38
Can anyone still reproduce this bug in [Godot 3.2.3 rc2](https://godotengine.org/article/release-candidate-godot-3-2-3-rc-2) or any later release?

If yes, please ensure that an up-to-date Minimal Reproduction Project (MRP) is included in this report (a MRP is a zipped Godot project with the minimal elements necessary to reliably trigger the bug). You can upload ZIP files in an issue comment with a drag and drop.

(testing this on master would be useful)

**Comment by KoBeWi** [comment] 2020-09-28 16:25
Closing due to lack of update. Please comment if you can still reproduce this issue in the latest stable version of Godot.

**Closed by KoBeWi** 2020-09-28 16:25 UTC
Labels: bug, topic:core, topic:import
