### ISSUE TITLE
Object.get_signal_connection_list() only returns signals connected with the Signals GUI.

### ISSUE THREAD

**Issue by eatallyourdarlings** [godotengine/godot#94791] opened 2024-07-26 11:02 UTC
### Tested versions

4.3 RC

### System information

Godot v4.3.rc1 - macOS 14.5.0 - GLES3 (Compatibility) - Apple M1 Pro - Apple M1 Pro (8 Threads)

### Issue description

expected behaviour of Object.get_signal_connection_list() is to return a list of nodes a signal is connected to, regardless of if it was connected with the Signals GUI or with code (it doesn't say otherwise in the class reference).

### Steps to reproduce

running the attached project should print the button to the console. If you disconnect the button's 'pressed' signal using the GUI and uncomment the code in the button's script, it should print an empty array (`[]`). 

the single main scene is a button with the following script: 
```
extends Button

func _ready() -> void:
	#pressed.connect(_button_pressed)
	#self.pressed.connect(self._button_pressed)
	pass

func _button_pressed() -> void:
	print("hello!")
```

and a child Node with this script:
```
extends Node

func _ready() -> void:
	print(get_parent().get_signal_connection_list("pressed"))
```

### Minimal reproduction project (MRP)

[signals.zip](https://github.com/user-attachments/files/16390697/signals.zip)

**Comment by AThousandShips** [comment] 2024-07-26 11:37
The `_ready` of the child node is called before that of the parent, see the [documentation](https://docs.godotengine.org/en/stable/classes/class_node.html#class-node-private-method-ready), so this is expected 

Can you confirm it works when you call it *after* having connected the signal?

**Comment by eatallyourdarlings** [comment] 2024-07-27 02:35
@AThousandShips it works if I move the above code from respective `_ready()` functions to `_enter_tree()`. Was the issue that I wasn't using best practice for referencing nodes when they're initialised?

**Comment by AThousandShips** [comment] 2024-07-27 08:31
Read the link I sent, `_ready` in a child is called *before* that of a parent

Closing as there's no bug here, but an issue of order of execution

**Closed by AThousandShips** 2024-07-27 08:31 UTC

**Comment by eatallyourdarlings** [comment] 2024-07-27 11:49
Hi I did read the link you sent I was just asking for clarification so I could investigate it myself and better understand the order of execution. Not very helpful :[

**Comment by AThousandShips** [comment] 2024-07-27 11:53
The order is described there, I didn't intend any dismissal, but this isn't a bug, please turn to the [other community channels](https://godotengine.org/community/) for more support! But in this particular case the issue is that `_ready` is called in all children, and then in the parent, and `_enter_tree` is called in the opposite order

**Comment by eatallyourdarlings** [comment] 2024-07-27 11:55
Okay thanks I understand. Appreciate it!
