### ISSUE TITLE
Vulkan: SubWindows exhibit rendering artifacts while in the editor (black window)

### ISSUE THREAD

**Issue by PixelGamer6632** [godotengine/godot#61034] opened 2022-05-14 17:11 UTC
### Godot version

4.0 Alpha 8

### System information

Windows 11 64 Biy Intel Iris Xe Graphics, display/graphics driver version 30.0.100.9864, Vulkan rendering engine

### Issue description

![image](https://user-images.githubusercontent.com/105533700/168441490-57e0a45c-1aa5-4b5b-ba91-86857368f3ad.png)
![Screenshot 2022-05-13 220752](https://user-images.githubusercontent.com/105533700/168441493-8b52a10e-17e1-41f0-9d18-0398125bc9b1.png)

The window panel nodes are being really weird. Both images were on different days so relaunching does nothing. I don't exactly know how to explain this so here are pics.

### Steps to reproduce

Add a window panel node
Increase size (x:600, y:400 recommended)

### Minimal reproduction project

[Run! 3.zip](https://github.com/godotengine/godot/files/8693586/Run.3.zip)

**Comment by Calinou** [comment] 2022-05-14 17:59
This is a duplicate of another issue, but I can't find it right now.

**Comment by PixelGamer6632** [comment] 2022-05-15 18:31
**Single Window Mode** wasn't even on when I made the post.

Also when I relaunched Godot 4 the next day the window was just black, changed back to glitched when I changed the size though.

**Comment by filantus** [comment] 2022-06-24 16:49
I'm confirm having that issue too. See https://github.com/godotengine/godot/issues/62376
v4.0.alpha10.official [4bbe7f0b9]
Windows 10, GLES3

**Comment by Rindbee** [comment] 2022-07-12 05:57
In the editor, the Window is embedded. So the problem seems to be caused by the following code.

https://github.com/godotengine/godot/blob/9b3972ad48393559f772151646304e28f938a6fa/scene/main/window.cpp#L424-L427

The update mode will be set to `RS::VIEWPORT_UPDATE_WHEN_PARENT_VISIBLE`. 

https://github.com/godotengine/godot/blob/9b3972ad48393559f772151646304e28f938a6fa/servers/rendering/renderer_viewport.cpp#L602-L607

The window's `visible` is determined by the above code. When embedded, the child is drawn before the parent. The equality condition does not hold. So, the `visible` will never be `true`.

**Comment by MinusKube** [comment] 2022-08-30 20:20
I believe this has been fixed by #63091

**Closed** 2022-08-30 20:29 UTC
Labels: bug, topic:rendering, confirmed, regression
