### ISSUE TITLE
Godot crashes when attempting to add a new node on Android 12

### ISSUE THREAD

**Issue by Shidoengie** [godotengine/godot#64440] opened 2022-08-15 14:35 UTC
### Godot version

3.5

### System information

The device used was a Samsung a12 with a Exynox cpu installed with android 12 

### Issue description

Appon Creating a new file and attempting to add a new node Godot will simply crash. This issue also happens when opening the node menu and After further experimentation not only did it crash Godot it also crashed my phone causing it to reboot.

### Steps to reproduce

Open Godot, create a new file, touch the add new node button and it should crash or attempt to open the node menu.

**Comment by Calinou** [comment] 2022-08-15 16:02
Duplicate of https://github.com/godotengine/godot/issues/64166.

**Closed by Calinou** 2022-08-15 16:02 UTC
