### ISSUE TITLE
GDScript 2.0: Typed arrays don't work with setters

### ISSUE THREAD

**Issue by mphe** [godotengine/godot#58285] opened 2022-02-18 17:45 UTC
### Godot version

4.0 Alpha 2

### System information

Arch Linux

### Issue description

Typed arrays with setters don't load their values upon running. This applies to all typed arrays, no matter which type they have.
Untyped arrays work fine.

I first thought this was related to https://github.com/godotengine/godot/issues/53771, as mentioned in my comment there, but it turns out it is a different bug.

It works in the editor, also in tool scripts, but upon running the game, such arrays remain empty. The scene file contains the correct values but they don't seem to get loaded.

There are no errors or warnings.

If anyone could give me a hint on where to start debugging this, I can try to investigate this myself.

### Steps to reproduce

See also the reproduction project.

1. Declare a typed array with a setter
```gdscript
@export var array: Array[int]:
    set(value):
        array = value
```
2. Assign some values to the array using the inspector
3. Run the game
4. Notice how the array is empty

### Minimal reproduction project

[typed_array_setters.zip](https://github.com/godotengine/godot/files/8099244/typed_array_setters.zip)

Contains a scene with 3 nodes. One node declares untyped arrays, one declares a typed array, and the last one is a tool script with a typed array.
Each node exports 4 arrays, one without setters/getters, one with a setter, one with a getter, and one with both.
In `_ready` they print the array contents.
Notice how arrays with setters are empty.

**Comment by mphe** [comment] 2022-03-05 17:47
Alright, I debugged this and found the problem and a workaround.

### The problem
Typed arrays lose their type when being written to a `tscn` file. Upon loading the respective `PackedScene`, it's just a normal, untyped array.
When instantiating the scene, the stored array is assigned to the property, which in turn calls the setter function. Before executing the function, its arguments are type checked. It expects an `Array[int]` but gets an untyped `Array`. This is considered as incompatible type and the function fails silently.

### The workaround
Don't specify types in the setter. However, it only works when using dedicated setter functions instead of the inline syntax.

```gdscript
# Works
@export var array: Array[int]: set = setter

func setter(value):
    array = value


# Does not work
@export var array: Array[int]: set = setter

func setter(value: Array[int]):
    array = value


# Does not work
@export var array: Array[int]:
    set(value):
        array = value
```


### Detailed process

Starting from `PackedScene::instantiate` and following to `SceneState::instantiate`, nodes are created and their properties assigned.
https://github.com/godotengine/godot/blob/cdd63fa8722da2cce75d3d9db65ce06548a5fa31/scene/resources/packed_scene.cpp#L274

`node->set` eventually leads us to `GDScriptInstance::set`.
https://github.com/godotengine/godot/blob/cdd63fa8722da2cce75d3d9db65ce06548a5fa31/modules/gdscript/gdscript.cpp#L1267

If the property has a setter, it will call the setter.
https://github.com/godotengine/godot/blob/cdd63fa8722da2cce75d3d9db65ce06548a5fa31/modules/gdscript/gdscript.cpp#L1276

This will eventually lead us to `GDScriptFunction::call`
https://github.com/godotengine/godot/blob/cdd63fa8722da2cce75d3d9db65ce06548a5fa31/modules/gdscript/gdscript_vm.cpp#L455

The loop starting from line 514 checks for argument types.
https://github.com/godotengine/godot/blob/cdd63fa8722da2cce75d3d9db65ce06548a5fa31/modules/gdscript/gdscript_vm.cpp#L514-L538

The relevant condition block is in line 525. This condition will evaluate true, meaning the provided argument type (`Array`) is not implicitly convertable to the expected type (`Array[int]`).
https://github.com/godotengine/godot/blob/cdd63fa8722da2cce75d3d9db65ce06548a5fa31/modules/gdscript/gdscript_vm.cpp#L525-L530

This happens due to `GDScriptDataType::is_type` reporting a type mismatch when trying to assign an untyped array to a typed array.
https://github.com/godotengine/godot/blob/cdd63fa8722da2cce75d3d9db65ce06548a5fa31/modules/gdscript/gdscript_function.h#L78-L94

Hence, the function call fails, sets a corresponding error code and returns a default constructed value.
Additionally, the error is also silently ignored, because the calling code only checks if the result is valid without printing an error if it isn't.


Otherwise, back in `GDScriptInstance::set`, when there is no setter defined, the new array will be assigned using `Array::typed_assign`, which in turn leads us to `Array::_assign`.

https://github.com/godotengine/godot/blob/cdd63fa8722da2cce75d3d9db65ce06548a5fa31/modules/gdscript/gdscript.cpp#L1287
https://github.com/godotengine/godot/blob/ff65d33e8c278bfbbbad18f9db959b2bbe04f919/core/variant/array.cpp#L180

If the other array has no type, it will check each element's type to match and if everything evaluates positive, the new value will be assigned.

https://github.com/godotengine/godot/blob/ff65d33e8c278bfbbbad18f9db959b2bbe04f919/core/variant/array.cpp#L186-L217

Hence, everything works fine when not using a setter, because unlike `GDScriptDataType::is_type`, `Array::_assign` also checks types element-wise.

### Conclusion
- There should be an error if there is a function argument mismatch, maybe directly in `GDScriptFunction::call`?
- `GDScriptDataType::is_type` with `p_allow_implicit_conversion = true` should take individual element types into account when dealing with untyped arrays.

**Comment by Calinou** [comment] 2022-05-12 15:50
According to https://github.com/godotengine/godot/issues/60968, using separate functions should work as a workaround even if you keep the typed array hint.

**Comment by mphe** [comment] 2022-05-12 18:27
It works in tool script, but not when running the game.

**Comment by takaturre** [comment] 2022-11-19 15:36
Just found that this is still an issue in 4.0.beta5.

![image](https://user-images.githubusercontent.com/16601926/202858254-08048587-3457-4d42-ba8b-546407a5c555.png)

It seems the data is stored in the `tscn` file, but the problem is that the setter is not called on startup - or rather the call doesn't execute (there's no error nor warning).

![image](https://user-images.githubusercontent.com/16601926/202858759-f6170a55-5dae-4dde-b18c-c12bb5cb96b6.png)

MRP:
[TypedArraySetter.zip](https://github.com/godotengine/godot/files/10047330/TypedArraySetter.zip)

**Comment by DmitriySalnikov** [comment] 2023-01-05 01:08
v4.0.beta10.official [d0398f62f] still does not call a setter or a method with a typed argument.

At least this method still works
```gdscript
@export var cfg : Array[StringName]:
	set = _set_cfg

func _set_cfg(val):
	cfg = val
```

**Comment by L4Vo5** [comment] 2023-01-06 10:02
An error can be triggered explicitly if you try to assign to the array from another script:
`my_obj.gd`:
```gdscript
class_name MyObj

var a: Array[int]:
	set(val):
		pass # anything can go here
```
some node in a scene:
```gdscript
extends Node

func _ready() -> void:
	var obj = MyObj.new()
	obj.a = [0, 1]
```
Error: `Invalid set index 'a' (on base: Resource (MyRes) with value of type 'Array'.`
It won't produce an error if you use static typing on either obj (`var obj := MyObj.new()`) or the value assigned to `a` (via an intermediate variable declared explicitly as `Array[int]`).
`obj.a = [0, 1] as Array[int]` still produces the error. Not sure if Arrays can be cast and it's failing or they can't be cast and this silently does nothing different.

**Closed** 2023-01-31 10:20 UTC
Labels: bug, topic:gdscript, confirmed

**Comment by FabriceCastel** [comment] 2025-04-29 20:51
This seems to be an issue in 4.5.dev2 - attempting to use `set` on a basic `Array[int]`, and then attempt to assign the custom resource containing that field to an array of resources of its type, it fails with:

```
ERROR: Attempted to set an object into a TypedArray, that does not inherit from 'GDScript'.
ERROR: core/variant/array.cpp:490 - Condition "!_p->typed.validate(value, "set")" is true.
```

For clarity what I'm doing is like,

```
class_name ChildResource extends Resource

var numbers: Array[int]:
  set(arr):
    numbers = arr
```

```
class_name ParentResource extends Resource

var children: Array[ChildResource]
```

If I create a `ParentResource` and then try to create a separate `ChildResource` and assign it to its `children` array, the errors above go boom.
