### ISSUE TITLE
Creating a new editor plugin doesn't work

### ISSUE THREAD

**Issue by xDGameStudios** [godotengine/godot#23708] opened 2018-11-14 14:45 UTC
**Godot version:**
calinou.8849d3b

**OS/device including version:**
Windows 10

**Issue description:**
If you create a plugin from the editor, going into "Project"... "Project Setting"... "Plugins"... "Create"..
will not create the plugin and output an error.

![capture1](https://user-images.githubusercontent.com/10358443/48489816-cdd74b80-e81b-11e8-8230-a635511e5ae0.PNG)

note: my project is in another drive (don't know if that can be the issue).

**Comment by CowThing** [comment] 2018-11-14 17:35
Just tried it with 3.1 Alpha 2, and it works. I'm using Win10, and my project is on the same drive as the Godot executable.

**Comment by KoBeWi** [comment] 2020-06-08 14:26
@xDGameStudios Can you still reproduce this in Godot 3.2.1 or 3.2.2beta4?
(I can't reproduce)

**Comment by akien-mga** [comment] 2021-04-28 09:24
No answer, so closing. It's unlikely to be reproducible today, users have been developing hundreds of editor plugins since 2018.

**Closed by akien-mga** 2021-04-28 09:24 UTC
Labels: bug, platform:windows, topic:editor, topic:porting
