### ISSUE TITLE
High CPU usage during download on linux

### ISSUE THREAD

**Issue by bmarzins** [godotengine/godot#37399] opened 2020-03-29 03:31 UTC
**Godot version:**
3.2.1

**OS/device including version:**
Lenovo P53, running Ubuntu 18.04

Here's what godot prints when I start up a test project:
Godot Engine v3.2.1.stable.official - https://godotengine.org
OpenGL ES 3.0 Renderer: Mesa DRI Intel(R) UHD Graphics 630 (Coffeelake 3x8 GT2) 
 
Editing project: /home/ben/projects/godot/godot_3.2/test (::home::ben::projects::godot::godot_3.2::test)
Godot Engine v3.2.1.stable.official - https://godotengine.org
OpenGL ES 3.0 Renderer: Mesa DRI Intel(R) UHD Graphics 630 (Coffeelake 3x8 GT2) 

**Issue description:**
When I try to download an export template with Editor -> Manage Export Templates, after I select the "Official 3.2.1" mirror, and begin the download, godot's CPU usage spikes from under 10% to over 100%. It remained there during the whole download.

**Steps to reproduce:**
Download an export template

**Minimal reproduction project:**
A new project will work.

**Comment by Ev1lbl0w** [comment] 2020-03-29 10:28
I have noticed this too. Could it be some kind of "busy" wait?

**Comment by Calinou** [comment] 2020-03-29 12:06
The export template manager's progress bar only updates twice a second, so it shouldn't be due to the editor re-rendering continuously.

**Comment by Calinou** [comment] 2020-03-29 18:25
Duplicate of #35868.

**Closed by Calinou** 2020-03-29 18:25 UTC
Labels: bug, topic:editor, topic:network
