### ISSUE TITLE
Name of properties takes too much space when inspector is wide

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#24342] opened 2018-12-14 08:50 UTC
**Godot version:**
3.1 01fa067

**OS/device including version:**
Windows 10

**Issue description:**
When I resize inspector dock, then name of properties and its values takes both half of inspector space.
When values are very long and we try to resize inspector to see this value, then a lot of space is wasted.

Red pointer show where values ends(with this revert button), yellow show where end the longest name of properties and pink show wasted space

![fffff](https://user-images.githubusercontent.com/41945903/49992787-5402c100-ff85-11e8-8357-647ace2cbc3f.png)

**Comment by akien-mga** [comment] 2018-12-14 09:55
Duplicate of #7133.

**Closed by akien-mga** 2018-12-14 09:55 UTC
