### ISSUE TITLE
Load() built-in function doesn't accept StringName as argument

### ISSUE THREAD

**Issue by berarma** [godotengine/godot#98889] opened 2024-11-06 09:38 UTC
### Tested versions

- Reproducible in 4.3

### System information

Debian GNU/Linux 12.7

### Issue description

Calling `load()` with a StringName argument triggers the error: "Invalid type in GDScript utility function "load()". Cannot convert argument 1 from StringName to String."

### Steps to reproduce

Call `load()` with a StringName as argument.

### Minimal reproduction project (MRP)

It's just one line of code.

`load(StringName("res://script.gd")`

**Comment by berarma** [comment] 2024-11-06 11:08
> `load()` takes in `path: String`
> 
> This can be circumvented with `load("res://script.gd")`, or method `String(from: StringName)` to convert the `StringName`.

Most functions in Godot 4 take a StringName but they don't complain when they get a String instead. I think the same principle of equivalence should be applied to this case for coherence.

**Comment by KoBeWi** [comment] 2024-11-06 11:31
Can't reproduce in 4.4

**Comment by dalexeev** [comment] 2024-11-06 13:42
* Fixed by #84368.

**Closed by dalexeev** 2024-11-06 13:42 UTC
Labels: bug, topic:core, topic:gdscript, needs testing
