### ISSUE TITLE
GI probes don't seem to have an effect

### ISSUE THREAD

**Issue by jmf** [godotengine/godot#8194] opened 2017-03-29 10:54 UTC
**Operating system or device - Godot version:**
Linux 4.10, godot d4740a98537b1e7dcb6fb48176abdebe27eee83c
GPUs tested: GeForce GTX 645 with nouveau driver and Intel Haswell GPU.
**Issue description:**
I placed a GI probe in the scene with two cubes imported from blender, set the material property "emission" up for one of the cubes and pressed the bake button. It doesn't appear to work.
Screenshot after baking: ![Screenshot](https://lut.im/itPzyRnmwv/P0vxggNrUccT3fkH.png)

**Steps to reproduce:**
Import any models, create a GI probe around them, make one have emission and bake.

**Link to minimal example project:**
https://my.mixtape.moe/ignmrd.zip

**Comment by ZX-WT** [comment] 2017-03-29 10:59
Did you enable use in baked light in the geometry section?

**Comment by jmf** [comment] 2017-03-29 11:19
Yes, in both cubes the option "Use In Baked Light" is checked.

**Comment by DenisComtesse** [comment] 2017-04-14 11:27
I can confirm this. Adding a GIProbe and baking doesn't seen to do anything. I've played with material and WorldEnvironment settings too, but without any success. But since there's no documentation for this feature yet, I can't tell if it's a bug or just something I have overlooked. Maybe @reduz could explain how it's supposed to work, so we can verify?

**Comment by toger5** [comment] 2017-04-16 17:35
I also ran into that issue. I have one project where I tried one project where it works.
I think It has something to do with the setup. I also would be interested how to do it properly. But since there will be documentation anyways we just have to wait I think ;)

**Comment by reduz** [comment] 2017-06-02 11:27
This is fixed now, did not realize there was an issue

**Closed by reduz** 2017-06-02 11:27 UTC
Labels: bug, topic:rendering
