### ISSUE TITLE
Font oversampling breaks rendering on Window node when game is resized.

### ISSUE THREAD

**Issue by EMBYRDEV** [godotengine/godot#76450] opened 2023-04-25 19:22 UTC
### Godot version

4.0.2.stable

### System information

Windows 11, Vulkan

### Issue description

![image](https://user-images.githubusercontent.com/20043270/234380534-d481556f-17e2-4f4a-b339-6531d091e659.png)

When font oversampling is enabled and the game is resized, the font rendering inside a window node breaks.

When the subwindow is resized the font rendering fixes itself.

### Steps to reproduce

Download repo project, run test_ui.tscn, resize the main window.

### Minimal reproduction project

[UIScalingTest (2).zip](https://github.com/godotengine/godot/files/11326033/UIScalingTest.2.zip)

**Comment by Calinou** [comment] 2023-10-01 17:55
As a workaround, enable MSDF font rendering (you can do this in the Import dock, or in the Project Settings for the default project font). This will remove the need for font oversampling entirely.

**Comment by EMBYRDEV** [comment] 2023-10-02 06:45
> As a workaround, enable MSDF font rendering (you can do this in the Import dock, or in the Project Settings for the default project font). This will remove the need for font oversampling entirely.

This does somewhat help but MSDF font rendering has some weird kerning issues I asusme are being tracked elsewhere?

Before (correct):
![image](https://github.com/godotengine/godot/assets/20043270/c9836669-c7f8-4311-9924-19c41c019a30)

After (misaligned 2nd 't' in testing among other small issues):
![image](https://github.com/godotengine/godot/assets/20043270/f250c05a-8a8f-43d3-838d-d595e6a4e747)

**Comment by nofuncoding** [comment] 2024-06-22 03:08
same in 4.3.beta2
will this issue be solved?

**Comment by Calinou** [comment] 2024-06-22 18:59
> will this issue be solved?

This requires https://github.com/godotengine/godot/pull/86022 to be merged to be fixed, which is a large PR. Godot 4.3 is in feature freeze, so this can only be merged in 4.4 at the earliest.

**Comment by bruvzg** [comment] 2024-06-22 19:19
This should be fixed by https://github.com/godotengine/godot/pull/92731, but seems like subwindow title is still affected for some reason (text outside and inside subwindow seems to be fine).

**Closed** 2024-06-26 09:13 UTC
Labels: bug, confirmed, topic:gui

**Comment by domdfcoding** [comment] 2024-07-20 21:57
Is there a specific issue for the kerning problem with MSDF @EMBYRDEV mentioned? I'm seeing it too on 4.2.2 and the latest commit, although with my font the results aren't as bad.

**Comment by Calinou** [comment] 2024-07-21 02:49
> Is there a specific issue for the kerning problem with MSDF @EMBYRDEV mentioned? I'm seeing it too on 4.2.2 and the latest commit, although with my font the results aren't as bad.

Please open a separate issue for this kerning issue with a minimal reproduction project attached. This was tangentially discussed in https://github.com/godotengine/godot/issues/90779, but that issue is best kept separate about font *hinting* specifically.
