### ISSUE TITLE
Open FileDialog on Linux make app close without any error

### ISSUE THREAD

**Issue by tlloancy** [godotengine/godot#84629] opened 2023-11-08 19:29 UTC
### Godot version

4.1.3

### System information

Debian Bookworm

### Issue description

i launch godot on linux with option --rendering-driver opengl3

then i compil, launch the app and when i click to open a filedialog the whole appliation crash or close

### Steps to reproduce

try to open a filedialog window on linux bookworm

### Minimal reproduction project

FileDialog.popup()

get these errors at the beginning i don't know if it is relevant

```
ERROR: Condition "!texture_allocs_cache.has(p_id)" is true.
   at: texture_free_data (drivers/gles3/storage/utilities.h:111)
ERROR: Cubemap Arrays are not supported in the GL Compatibility backend.
   at: texture_2d_layered_initialize (drivers/gles3/storage/texture_storage.cpp:763)
ERROR: Attempting to use an uninitialized RID
   at: get_or_null (./core/templates/rid_owner.h:199)
ERROR: Condition "!t" is true.
   at: texture_free (drivers/gles3/storage/texture_storage.cpp:705)
WARNING: Blend file import is enabled in the project settings, but no Blender path is configured in the editor settings. Blend files will not be imported.
     at: _editor_init (modules/gltf/register_types.cpp:73)
```
[edit] My bad, it seems to have logs at crash time:
```

WARNING: res://Client/Game/ChatBox.tscn:6 - ext_resource, invalid UID: uid://0iembcto5jlr - using text path instead: res://Client/Assets/Cave-Story.ttf
     at: load (scene/resources/resource_format_text.cpp:447)

ERROR: Caller thread can't call this function in this node (/root). Use call_deferred() or call_thread_group() instead.
   at: propagate_notification (scene/main/node.cpp:2222)

================================================================
handle_crash: Program crashed with signal 4
Engine version: Godot Engine v4.1.3.stable.official (f06b6836a9ecfd0e6ec96d8bcf0fe9c9bc10dcbf)
Dumping the backtrace. Please include this when reporting the bug to the project developer.
[1] /usr/lib/x86_64-linux-gnu/libc.so.6(+0x3bfd0) [0x7f55c4c3dfd0] (??:0)
[2] llvm::CmpInst::Create(llvm::Instruction::OtherOps, llvm::CmpInst::Predicate, llvm::Value*, llvm::Value*, llvm::Twine const&, llvm::BasicBlock*) (??:0)
-- END OF BACKTRACE --
================================================================
```

[edit2] i can see these errors in the linux terminal from where i launch godot. But i can't see any error in godot itself

**Comment by bruvzg** [comment] 2023-11-08 22:03
> llvm::CmpInst::Create

This looks like Mesa crash. Might be duplicate of https://github.com/godotengine/godot/issues/74172.

**Comment by akien-mga** [comment] 2024-07-04 16:05
Indeed, consolidating in #74172 which seems to be the same issue with both nouveau and llvmpipe crashing on old Debian/Ubuntu distros.

**Closed by akien-mga** 2024-07-04 16:05 UTC
Labels: bug, platform:linuxbsd, topic:rendering, topic:thirdparty, crash
