### ISSUE TITLE
Tooltips don't appear anymore

### ISSUE THREAD

**Issue by DleanJeans** [godotengine/godot#17001] opened 2018-02-25 05:10 UTC
**Godot version:** 3.0, 3.0.1-rc1

**OS/device including version:** Windows 10 64-bit

**Issue description:**
I remember they used to work in Godot 3 Alpha, Beta, Release Candidate Versions and Godot 2.
This includes almost everything: the FileSystem dock, Scene tab, Inspector Tab, Node tab, you name it.

Godot 2:
![tooltip](https://user-images.githubusercontent.com/12462089/36638212-1de89ae4-1a21-11e8-8ef5-48a6535d5464.png)

Godot 3 RC3:
![tooltiprc3](https://user-images.githubusercontent.com/12462089/36638308-1de119ec-1a24-11e8-85e3-9157357b7b2a.png)

**Comment by akien-mga** [comment] 2018-02-25 09:04
I can't reproduce it on Linux x86_64:

- *master* branch (95b8984d5f4)
![image](https://user-images.githubusercontent.com/4701338/36639713-08b89fc4-1a13-11e8-84b9-b2302a4dfcae.png)
- 3.0.1 RC1
![spectacle t27563](https://user-images.githubusercontent.com/4701338/36639720-23064ea8-1a13-11e8-8c2e-ba5e191efa58.png)

**Comment by DleanJeans** [comment] 2018-02-25 14:57
Someone on the Godot Engine Facebook Group is also experiencing this.
Unsure which platform.

![image](https://user-images.githubusercontent.com/12462089/36642771-ca2c3180-1a76-11e8-92fc-dd78a21c9dbf.png)

**Comment by RabbitB** [comment] 2018-02-27 08:25
I'm afraid I can't reproduce this; all tool-tips show as expected. Looks like it may not be a Windows specific issue.

**Godot version:**
3.0.1 Stable win64

**OS/device including version:**
Windows 10 Pro x64 - build 16299.125

**Comment by DleanJeans** [comment] 2018-02-27 11:24
This seems to only affect old projects. The tooltips work again when you create a new one. But no way to fix the tooltips not showing in old projects.

**Comment by akien-mga** [comment] 2018-02-27 11:30
Can you provide a project where tooltips don't work?

**Comment by DleanJeans** [comment] 2018-02-28 11:43
[NoTooltips.zip](https://github.com/godotengine/godot/files/1766912/NoTooltips.zip)
Playing around with `project.godot` randomly makes tooltips appear again.

**Comment by Noshyaar** [comment] 2018-02-28 11:57
Can confirm with the given project. Tooltips appear on other projects.

**Comment by avril-gh** [comment] 2018-02-28 12:47
theres many settings for tooltips here and there.
Obsolete settings file with wrong data maybe ?

**Comment by akien-mga** [comment] 2018-03-01 13:32
The culprit seems to be this parameter:
```
[physics]

common/enable_object_picking=false
```

As a workaround, remove it, and tooltips should work again. I'll try to find why it breaks tooltips though.

**Comment by akien-mga** [comment] 2018-03-01 13:37
The problem is that this option disabled `_physics_process` in the Viewport, and apparently tooltips use that. They should be fixed to use the internal idle process.

**Closed** 2018-03-01 15:59 UTC
Labels: bug, confirmed, topic:core
