### ISSUE TITLE
Store the int_array using separate lines

### ISSUE THREAD

**Issue by rraallvv** [godotengine/godot#12925] opened 2017-11-14 15:10 UTC
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Godot 2.1 (HEAD)

**Issue description:**

I've noticed that, in source control, changes to some values in `int_array` elements need to update the whole array.

	-		<int_array  len="222"> 				-1, -1, 3, 0, -1, 2, 1, 0, 2, 1, 0, 0, 0, 4, 4, -1, 22, 1, 0, 5, 2, 6, 3, 7, 4, 8, 2, 9, 3, 10, 5, 11, 5, 12, 5, 13, 6, 14, 6, 15, 6, 16, 6, 17, 6, 18, 7, 19, 8, 20, 2, 21, 2, 22, 9, 23, 10, 24, 6, 25, 6, 0, 0, 0, 26, 26, -1, 12, 1, 0, 27, 11, 28, 7, 29, 12, 30, 13, 31, 14, 32, 2, 33, 6, 34, 15, 35, 16, 36, 5, 37, 5, 0, 0, 0, 38, 38, -1, 21, 1, 0, 27, 17, 5, 2, 39, 3, 40, 6, 41, 7, 42, 18, 43, 19, 44, 19, 45, 6, 46, 5, 47, 20, 48, 5, 49, 21, 50, 18, 51, 16, 52, 7, 53, 7, 54, 5, 55, 22, 56, 23, 0, 0, 0, 57, 57, -1, 19, 1, 0, 27, 17, 5, 2, 39, 3, 40, 6, 41, 7, 42, 18, 43, 19, 44, 19, 45, 6, 46, 5, 47, 24, 48, 5, 49, 21, 50, 18, 51, 16, 52, 7, 58, 23, 59, 18, 0, 0, 0, 75, 60, -1, 14, 61, 2, 62, 2, 63, 3, 64, 3, 65, 25, 66, 7, 67, 5, 68, 5, 69, 5, 70, 5, 71, 25, 72, 18, 73, 7, 74, 26, 0 </int_array>
	+		<int_array  len="222"> 				-1, -1, 3, 0, -1, 2, 1, 0, 2, 1, 0, 0, 0, 4, 4, -1, 22, 1, 0, 5, 2, 6, 3, 7, 4, 8, 2, 9, 3, 10, 5, 11, 5, 12, 5, 13, 6, 14, 6, 15, 6, 16, 6, 17, 6, 18, 7, 19, 8, 20, 2, 21, 2, 22, 9, 23, 10, 24, 6, 25, 3, 0, 0, 0, 26, 26, -1, 12, 1, 0, 27, 11, 28, 7, 29, 12, 30, 13, 31, 14, 32, 2, 33, 6, 34, 15, 35, 16, 36, 5, 37, 5, 0, 0, 0, 38, 38, -1, 21, 1, 0, 27, 17, 5, 2, 39, 3, 40, 6, 41, 7, 42, 18, 43, 19, 44, 19, 45, 6, 46, 5, 47, 20, 48, 5, 49, 21, 50, 18, 51, 16, 52, 7, 53, 7, 54, 5, 55, 22, 56, 23, 0, 0, 0, 57, 57, -1, 19, 1, 0, 27, 17, 5, 2, 39, 3, 40, 6, 41, 7, 42, 18, 43, 19, 44, 19, 45, 6, 46, 5, 47, 24, 48, 5, 49, 21, 50, 18, 51, 16, 52, 7, 58, 23, 59, 18, 0, 0, 0, 75, 60, -1, 14, 61, 2, 62, 2, 63, 3, 64, 3, 65, 25, 66, 7, 67, 5, 68, 5, 69, 5, 70, 5, 71, 25, 72, 18, 73, 7, 74, 26, 0 </int_array>

It doesn't happen with other type of collections like for instance `string_array`.

Is there chance to make Godot to store `int_array` elements like this instead?

	<int_array  len="222">
		-1, -1, 3, 0, -1, 2, 1, 0, 2, 1,
		0, 0, 0, 4, 4, -1, 22, 1, 0, 5,
		2, 6, 3, 7, 4, 8, 2, 9, 3, 10,
		5, 11, 5, 12, 5, 13, 6, 14, 6,
		15, 6, 16, 6, 17, 6, 18, 7, 19, 8,
		....
		20, 2, 21, 2, 22, 9, 23
	</int_array>

The number of elements in a row could vary from 1 to N, an there is a tradeoff since there are additional characters inserted in each line, but that is also the case with `string_array`.

	<string_array  len="76">
		<string> "world" </string>
		<string> "_import_transform" </string>
		<string> "__meta__" </string>
		<string> "Spatial" </string>
		<string> "ImmediateGeometry" </string>
		...
	</string_array>

Those could be stored like like this:

	<string_array  len="76"><string> "world" </string><string> "_import_transform" </string><string> "__meta__" </string><string> "Spatial" </string><string> "ImmediateGeometry" </string>...</string_array>

The tradeoff is not only for space storage but also for readability, if on argue that the whole purpose of storing in a human-readable format is to make things look nicer, then storing one element per line doesn't look nice either:

	<int_array  len="222">
		-1,
		-1,
		3,
		0,
		-1,
		...
	</int_array>

**Steps to reproduce:**
Save a scene in **xscn** format

**Comment by akien-mga** [comment] 2017-11-14 15:13
`xscn` is deprecated and removed in 3.0, so I doubt we'll be making changes to it.

**Comment by rraallvv** [comment] 2017-11-15 00:47
@akien-mga I see, with xscn changing the value for some exported variable would crate a diff with the whole array working under source control. I switched to tscn and now the exported variables are stored in separate rows each row with the name of the var.

I'm not sure if storing large chunks of data like below would bring some benefit when working under source control using the tscn format, since the data would normally be edited using some third party tool like Tiled or Blender.

This way:

	data = {
	"cells": PoolIntArray(
	3, 0, 1048584, 12, 0, 1441800, 65539, 0, 1048584, 65548,
	0, 1441800, 131075, 0, 1048578, 131084, 0, 1441800, 196611, 0,
	1048578, 196620, 0, 1441800, 262147, 0, 1048578, 262156, 0, 1441800,
	327683, 0, 1048584, 327692, 0, 1441794, 393219, 0, 1048584, 393228,
	-65525, 65535, 2
	)
	}

...or with prepended tabs:

	data = {
		"cells": PoolIntArray(
			3, 0, 1048584, 12, 0, 1441800, 65539, 0, 1048584, 65548,
			0, 1441800, 131075, 0, 1048578, 131084, 0, 1441800, 196611, 0,
			1048578, 196620, 0, 1441800, 262147, 0, 1048578, 262156, 0, 1441800,
			327683, 0, 1048584, 327692, 0, 1441794, 393219, 0, 1048584, 393228,
			-65525, 65535, 2
		)
	}

Nevertheless, I've already made a patch for xml for Godot 2.1 for all array formats and it words fine, I'm submitting the PR (#12937). Something like this can be done for tscn too.

Cheers!

**Comment by akien-mga** [comment] 2018-09-18 08:37
I'll close this issue as it was made specifically for the XML format which is now deprecated. The issue is still partly relevant for TSCN/TRES, but that's covered in #16783 and can be further discussed there.

**Closed by akien-mga** 2018-09-18 08:37 UTC
Labels: enhancement, topic:core
