### ISSUE TITLE
Renaming a mono/C# project from Project Settings causes it to fail to load solution 

### ISSUE THREAD

**Issue by SLGamesCregg** [godotengine/godot#60471] opened 2022-04-23 15:10 UTC
### Godot version

3.4.4 Stable Mono

### System information

Windows 10

### Issue description

If you rename a project via the Godot editor it causes the project to no longer run. Instead, if you try running the project you will get an error like the following one. This causes the entire project to fail to load any C# files.

```
E 0:00:00.751   can_instance: Cannot instance script because the project assembly is not loaded. Script: 'res://Test.cs'.
  <C++ Error>   Method failed. Returning: __null
  <C++ Source>  modules/mono/csharp_script.cpp:2889 @ can_instance()
```

The issue is related to the project .csproj and .sln files, which don't get changed upon a project rename. A workaround for this is going to the files themselves and manually editing them, but you'd expect the project to update the .csproj and .sln file as it did on initial project creation (or at least try to). 

### Steps to reproduce

1. Open minimal reproduction project and press play. You will see a "Hello World" printed to the console.
2. Open project settings and change "Name" in Application Config. 
3. Press "Play" and you will get the error described above, and you will no longer see the "Hello World" output.

### Minimal reproduction project

[ReproTest.zip](https://github.com/godotengine/godot/files/8547460/ReproTest.zip)

**Comment by Calinou** [comment] 2022-04-23 15:16
Duplicate of https://github.com/godotengine/godot/issues/27030.

**Closed by Calinou** 2022-04-23 15:16 UTC
Labels: bug, topic:editor, topic:dotnet
