### ISSUE TITLE
ERROR: get_edited_scene_root

### ISSUE THREAD

**Issue by AlexHolly** [godotengine/godot#2654] opened 2015-10-21 22:22 UTC
ERROR: get_edited_scene_root: Index current_edited_scene out of size (edited_scene.size()).
   At: tools/editor/editor_data.cpp:500.

How about opening the "Scene -> Project Settings -> main_scene" as default if there is one defined and no others are cached in "current_edited" on Project start.

Update: Godot is also not opening my recent used scenes on project start.

godot 2.0 master
OS:ubuntu

**Comment by firefly2442** [comment] 2015-10-22 19:29
See also #2611 for my attempt at examining the issue.

**Comment by akien-mga** [comment] 2015-11-01 13:09
Closing as duplicate of #2611.

**Closed by akien-mga** 2015-11-01 13:09 UTC
Labels: archived, bug, topic:editor

**Comment by akien-mga** [comment] 2015-11-04 21:15
Actually it was not really a duplicate of #2611, but it could now be considered a duplicate of #2731 which has more details and a proposed fix.
