### ISSUE TITLE
Rich text label crash

### ISSUE THREAD

**Issue by bushig** [godotengine/godot#1803] opened 2015-05-04 11:08 UTC
When trying to resize Rich text label demo example all the way down in godot editor, editor crashes every time, and when trying to resize project window all the way down, it crashes too.  Also there some random crashes when typing long text inside [fill][/fill]
Deleting [fill][/fill] part fixed all the problems.

**Comment by bushig** [comment] 2015-11-08 22:12
The editor still crashes when I type something long inside [fill][/fill]. Try press for example 'E' button inside existing [fill] tag to recreate problem. For me minimal number of words inside text in order to get error is 3. Also for me error never occured if I try to type at the end of the text.

**Comment by akien-mga** [comment] 2015-12-16 11:01
Looks like a duplicate of #2688.

**Closed by akien-mga** 2015-12-16 11:01 UTC
Labels: bug, high priority, topic:core
