### ISSUE TITLE
Creating a new project in a new folder actually opens an existing project if a selection was made

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#41775] opened 2020-09-04 23:24 UTC
Godot 3.2.3 rc5
Godot 3.2.3 rc3
Windows 10 64 bits

In the project manager, if you select a project, and then go on to create a new project, Godot will end up opening the initially selected project regardless, instead of creating a new project.

Steps:
1) Open project manager with some projects in the list
2) Click on the first project
3) Click `New Project`
4) Click `Browse`
5) Navigate somewhere and click `Create Folder`
6) Focus the folder name field to edit it
7) Press Enter: observe the project manager closes, and Godot opens the project you selected in 1). On the other hand, the new folder gets created, but will be empty.

This did not happen in Godot 3.2.2 stable.

**Comment by capnm** [comment] 2020-09-05 11:47
I can confirm the same issue with Linux + current 3.2 tip

**Comment by akien-mga** [comment] 2020-09-05 13:25
> This did not happen in Godot 3.2.2 stable.

Are you sure? The same thing seems to happen with 3.2.2.

The problem is that the input event is somehow not handled by the popup and passed to the project manager, which then runs the currently selected project. Good old issue that has been worked around countless times but there are always some UI elements where it fails...

**Comment by capnm** [comment] 2020-09-05 13:50
> Are you sure? The same thing seems to happen with 3.2.2.

My Linux version seems to work ok:
![grafik](https://user-images.githubusercontent.com/4047289/92306370-dd92c780-ef8e-11ea-9431-3f546b2dd218.png)

**Comment by scottmpowell** [comment] 2020-09-07 03:04
This is a regression for me on Linux. It works for 3.2.2 and 4.0, but fails for 3.2.3.rc5

**Comment by Calinou** [comment] 2020-09-07 13:30
I bisected the regression to c0b394572f35498801571ad7176eb357d5de1bf3.

**Comment by pouleyKetchoupp** [comment] 2020-09-07 14:41
Oh, I can't remember why I've added the return there. I'll have to test again.

Links to related PRs:
4.0 - #40487
3.2 - #40469

**Comment by pouleyKetchoupp** [comment] 2020-09-08 08:29
Fixed in #41870. This change in `LineEdit` was not needed for the Android fix, so I must have introduced it by mistake while making some tests.

Sorry and thanks all for investigating!

**Closed** 2020-09-08 09:14 UTC
Labels: bug, confirmed, regression, topic:editor
