### ISSUE TITLE
Tooltip Blinking

### ISSUE THREAD

**Issue by Dillybob92** [godotengine/godot#4667] opened 2016-05-16 04:17 UTC
Every single time I hover over something that has a tooltip, it blinks. The tooltip like magically disappears, this is so odd I have no idea.

https://i.gyazo.com/c57b3c1746e0f490ec78a6f37484bdea.gif

I am using the latest stable build:
Godot_v2.0.3_stable_win64.exe

I also changed the tooltip delay to 3 seconds, 0.7 seconds, to any value.. It doesn't seem to have any effect. Not sure what else to report :P

**Comment by vjrossi** [comment] 2016-05-16 06:59
Funny, I get the same thing but for me the tooltip at least hangs around for maybe 10 seconds before it goes off, then back on for another 10.

**Comment by Dillybob92** [comment] 2016-05-16 07:12
@vjrossi. Haha, I just had it where the tooltips were showing instantly even though I had it set to 0.7. And it started to lag the screen. I just re-started Godot and it went back to the normal blinking. Weird as heck!

**Comment by kubecz3k** [comment] 2016-05-16 07:54
Not sure if this issue is related to windows build, but can't reproduce on Ubuntu 16.04

**Comment by bojidar-bg** [comment] 2016-05-16 08:50
Releated/dupe of #3835?

**Comment by Dillybob92** [comment] 2016-05-16 17:04
@bojidar-bg Yeah, sorry I forgot to  search :( I applied a gif though.

I just restarted my computer and it's NOT happening now. I'm stumped!

**Comment by kubecz3k** [comment] 2016-05-16 17:16
archiving because it's duplicate of https://github.com/godotengine/godot/issues/3835

**Closed by kubecz3k** 2016-05-16 17:16 UTC
Labels: archived, bug, platform:windows, topic:editor
