### ISSUE TITLE
After 401 Errors game crashes

### ISSUE THREAD

**Issue by sanyi12** [godotengine/godot#81049] opened 2023-08-27 16:04 UTC
### Godot version

4.1.1

### System information

Windows 10, Forward+, RTX3070

### Issue description

After 401 Errors game crashes

### Steps to reproduce

After 401 Errors that look like the ones below, game crashes. I wish I could have explained better but I have no idea what those errors do or mean. 
Note: those errors DO NOT appear during gameplay. They do not appear at all. After a while, the game just crashes and there they are. 

E 0:05:29:0397   compute_list_begin: Only one draw/compute list can be active at the same time.
  <C++ Error>    Condition "compute_list != nullptr" is true. Returning: INVALID_ID
  <C++ Source>   drivers/vulkan/rendering_device_vulkan.cpp:7735 @ compute_list_begin()

E 0:05:29:0397   compute_list_bind_compute_pipeline: Condition "p_list != ID_TYPE_COMPUTE_LIST" is true.
  <C++ Source>   drivers/vulkan/rendering_device_vulkan.cpp:7748 @ compute_list_bind_compute_pipeline()

E 0:05:29:0397   compute_list_bind_uniform_set: Condition "p_list != ID_TYPE_COMPUTE_LIST" is true.
  <C++ Source>   drivers/vulkan/rendering_device_vulkan.cpp:7812 @ compute_list_bind_uniform_set()

E 0:05:29:0397   compute_list_end: Condition "!compute_list" is true.
  <C++ Source>   drivers/vulkan/rendering_device_vulkan.cpp:8194 @ compute_list_end()

### Minimal reproduction project

could not reproduce. don't know what is the reason behind them

**Comment by bitsawer** [comment] 2023-08-27 16:16
Most likely fixed by https://github.com/godotengine/godot/pull/79849, the fix will probably be in next releases. Closing as likely duplicate of the issues mentioned in the PR, especially if you use advanced nodes like GPU particles in your project. Still, please comment or reopen the issue if the problems has not been fixed in next release (or you can try Godot custom builds).

**Closed by bitsawer** 2023-08-27 16:16 UTC
