### ISSUE TITLE
Crash on Vulkan in Hybrid GPU Mode

### ISSUE THREAD

**Issue by amosstevens** [godotengine/godot#65144] opened 2022-08-31 11:50 UTC
### Godot version

4.0.alpha15.official.432b25d36 

### System information

Windows 10 21H2 19044.1889, Vulkan, iGPU: AMD Vega 8, dGPU: Nvidia RTX 3080 GA104M, Nvidia Driver: 516.94

### Issue description

I'm on a Lenovo Legion 7, when i put the laptop in hybrid mode (via BIOS) godot crash with the error below, instead when i use the only discrete gpu mode it works flawlessly

```
Godot Engine v4.0.alpha15.official.432b25d36 - https://godotengine.org
ERROR: GENERAL - Message Id Number: 0 | Message Id Name: Loader Message
        setup_loader_tramp_phys_devs:  Failed during dispatch call of 'vkEnumeratePhysicalDevices' to lower layers or loader to get count.
        Objects - 1
                Object[0] - VK_OBJECT_TYPE_INSTANCE, Handle 1902339142752
   at: _debug_messenger_callback (drivers/vulkan/vulkan_context.cpp:171)
ERROR: vkEnumeratePhysicalDevices reported zero accessible devices.

Do you have a compatible Vulkan installable client driver (ICD) installed?
vkEnumeratePhysicalDevices Failure
   at: (drivers/vulkan/vulkan_context.cpp:864)
ERROR: Condition "err != OK" is true. Returning: ERR_CANT_CREATE
   at: _window_create (drivers/vulkan/vulkan_context.cpp:1462)
```

### Steps to reproduce

1. Open Godot 4 in Hybrid GPU Mode
2. Open Godot 4 in Discrete Only GPU Mode

**Comment by Calinou** [comment] 2022-08-31 14:24
Duplicate of https://github.com/godotengine/godot/issues/57708.

**Closed by Calinou** 2022-08-31 14:24 UTC
Labels: bug, platform:windows, topic:rendering
