### ISSUE TITLE
Show image in Project Settings/General/Boot Splash does not work for Android application

### ISSUE THREAD

**Issue by MooSoup** [godotengine/godot#64703] opened 2022-08-21 19:56 UTC
### Godot version

v3.5.stable.official [991bb6ac7]

### System information

Windows 10

### Issue description

Project Settings/General/Boot Splash there is a "show image" boolean, which does not work for android builds. I exported my project for Android (debug) and the image is still showing. It does work for windows desktop application.

### Steps to reproduce

Create a new project, activate "show image" in Project Settings/General/Boot Splash and export for Android.

**Comment by Calinou** [comment] 2022-08-21 20:15
Duplicate of https://github.com/godotengine/godot/issues/63966 and/or https://github.com/godotengine/godot/issues/64491.

**Closed by Calinou** 2022-08-21 20:15 UTC
