### ISSUE TITLE
TileMap children behind TileMap

### ISSUE THREAD

**Issue by beamer159** [godotengine/godot#69687] opened 2022-12-06 22:17 UTC
### Godot version

4.0 beta 7

### System information

Windows 11

### Issue description

In the editor, if I create a Sprite2D child for a parent TileMap, it appears in front of the TileMap. However, when run, the Sprite2D child appears behind the TileMap parent. If I reload the current project, the Sprite2D child appears behind the TileMap parent in the  editor as well. I was not expecting this. I thought children Node2Ds appear in front of their Node2D parents by default.

![image](https://user-images.githubusercontent.com/7436252/206034931-fb206182-083e-4e97-81f8-0c46dc1989c8.png)

### Steps to reproduce

1. Create TileMap
2. Create Sprite2D child of the TileMap
3. Run

### Minimal reproduction project

[project.zip](https://github.com/godotengine/godot/files/10170645/project.zip)

**Comment by KoBeWi** [comment] 2022-12-06 22:43
Duplicate of #53746

**Closed by KoBeWi** 2022-12-06 22:43 UTC
