### ISSUE TITLE
popup menus closing rapidly

### ISSUE THREAD

**Issue by voylin** [godotengine/godot#72215] opened 2023-01-27 23:53 UTC
### Godot version

4.0.beta_16

### System information

Arch linux, i3 wm

### Issue description

In the last beta (15) I experienced this issue with the toolbar popups disappearing right after clicking them, only showing themselves for a milisecond. Now in beta 16, I'm having a very similar issue. When trying to work in the theme editor, everything I click makes the theme editor go away. Same for the color wheel popup, as soon as I click in it, it disappears. I can not drag anything in the color wheel as well as it just closes instantly. This is not an issue in beta_14 (the version I am using for my project now as 15 and 16 are having this issue.)

### Steps to reproduce

Open any project and try to edit some value with a color wheel popup or try to use the theme editor.

### Minimal reproduction project

This issue happens in all projects including new ones. (Not certain if it is specific to Linux or i3)

**Comment by akien-mga** [comment] 2023-01-28 12:20
CC @bruvzg. Might be specific to i3 WM, it's not the first time we're having WM-specific issues.

**Comment by akien-mga** [comment] 2023-01-28 13:02
Probably duplicate of #72189.

**Closed** 2023-02-22 13:41 UTC
Labels: bug, platform:linuxbsd, topic:porting, regression
