### ISSUE TITLE
Re-add atlas packing option

### ISSUE THREAD

**Issue by amkk** [godotengine/godot#13940] opened 2017-12-04 01:25 UTC
**Issue description:**
Godot 2.0 has "image groups tab" and "atlas toggle button" in export settings.
![1](https://user-images.githubusercontent.com/8508498/33532007-a8881dee-d8d8-11e7-9eaf-9fc2d55ecdf9.png)
I can't find it in Godot 3.0.
Is this removed or regret?
It's really useful feature for me.

**Comment by reduz** [comment] 2017-12-04 01:53
It's gone, you can select multiple images and change settings at the same
time on import (using import tab)

**Comment by Zylann** [comment] 2017-12-04 02:31
@reduz but how do we make atlases on export now?

**Comment by amkk** [comment] 2017-12-04 15:22
@reduz  I know that and thanks to new import system.
I like it.
but make atlas on export time is really useful.
It's allows flexible workflow.
so please don't remove it.

**Comment by reduz** [comment] 2017-12-04 15:24
Atlas on export won't come back simply for the reason that Godot does no longer any work of that sort when exporting.

Still, it should be possible to do atlas on import, just no one hasn't voluntereed yet with a proposal.

**Comment by Zylann** [comment] 2017-12-04 16:14
@reduz I think doing extra export steps like that is important to consider because one idea behind atlas baking is that it's part of transforming the assets from an editor-optimized workflow to a player-optimized experience (same idea behind binarizing scenes for example).

**Comment by reduz** [comment] 2017-12-04 16:24
@Zylann Truth is that they are not that useful in this case nowadays, so It's a matter of focusing the effort on priorities, else nothing gets done.

In any case, an import workflow using atlases could work exactly the same, you would select to import the texture as "atlas" and select an atlas name. If it wasn't done it's because there really hasn't been a strong demand for it.

**Comment by Tymonrare** [comment] 2018-01-10 14:34
@reduz i guess it's good to use another tools like texturepacker for optimize resources and workflow, but @Zylann has a point - autobatcher in export pipeline can make great job for beginners who don't know why we have to use atlases and for teams where smooth workflow without constant reimports very important

**Comment by jahd2602** [comment] 2018-05-16 16:15
Please let's re-add the atlas option, for export or for import, this is especially useful when doing tilemaps.

**Comment by mhilbrunner** [comment] 2018-05-16 16:31
Isn't on-import worse than on-export, as you likely want to work on separate images in your art pipeline?

So on each iteration, your workflow needs to be:
*make change > make atlas > import > test*

instead of:
*make change > import> test*

**Comment by xdeadmonkx** [comment] 2018-07-17 14:42
The problem is when you adding atlas on import it's not that easy to replace it to new generated atlas - all rects will be changed and you have to recreate all existing sprites.
But if you generate atlas on export then you just need to add new sprite)

**Comment by timoschwarzer** [comment] 2018-12-25 14:06
> make change > make atlas > import > test

My proposal:

- Put `a.png`, `b.png` and `c.png` into res://assets/
- Select these files in the editor and click "Create atlas" in the import tab
- The editor then:
  - Creates an atlas file in res://.import/ containing the whole atlas
  - Writes this association to the `a.png.import` etc. files
  - Creates `*.png.atex` files next to the original `*.png*` files

Upside:
- When one or more originals change, the editor would simply rebuild the atlas like any other imported file, too.

Downside:
- On export, the probably unused original `*.png` files would be exported, too, I guess.

**Comment by arkology** [comment] 2019-04-19 19:34
If I understand correctly, with this https://github.com/godotengine/godot/commit/04847ef5f98d9a20a72286c44cc26302ec82dec5 commit the option of atlas packing is back!

**Comment by akien-mga** [comment] 2019-04-19 19:51
Indeed, fixed by 04847ef.

**Closed by akien-mga** 2019-04-19 19:51 UTC
Labels: discussion, feature proposal

**Comment by firecloud888** [comment] 2021-11-01 20:36
I really think it need to be reopened. Bunk of assets is hard to reimport. You can only reimport once a time and reboot the engine, if the game has many resources, it's a nightmare. This function is absolute useless before the final release.... If you only use godot for small games ,it's fine. But we need a more powerful engine to develop bigger game

**Comment by Calinou** [comment] 2021-11-01 20:39
@firecloud888 [Atlas support is already available in Godot 3.2 and later](https://godotengine.org/article/atlas-support-returns-godot-3-2). However, as the article says, it's mainly relevant when targeting low-end mobile devices. When targeting desktop platforms or recent/high-end mobile devices, it's not as important.
