### ISSUE TITLE
Kinematic body sinking through Plane collision shape.

### ISSUE THREAD

**Issue by LeonardMeagher2** [godotengine/godot#962] opened 2014-12-11 20:59 UTC
Here is a test case
https://db.tt/dsbVSzUT

@reduz

**Comment by akien-mga** [comment] 2015-11-05 08:27
Hi @LeonardMeagher2 and sorry for the delay. It looks like both test cases are now dead links. Can you still reproduce this issue in the current master branch?

**Comment by akien-mga** [comment] 2016-03-24 09:35
No answer, closing as it's hard to reproduce without test case. Please reopen or open a new issue if the issue is still valid, and provide steps to reproduce and a test case (you can upload a zip archive directly to the issue, to avoid such dead links).

**Closed by akien-mga** 2016-03-24 09:35 UTC
Labels: bug, topic:core
