### ISSUE TITLE
Changing the root of an scene that's instanced somewhere else deletes the whole scene, other than the root

### ISSUE THREAD

**Issue by Gonkee** [godotengine/godot#35305] opened 2020-01-19 06:31 UTC
**Godot version:**

v3.1 Stable

**OS/device including version:**

Windows 10 Pro Version 1903 Build 18362.592

**Issue description:**

If you have scene B that is instanced in scene A, and set one of the children nodes in B to be its root, then open scene A again, then back to scene B, the whole scene disappears other than the new root. Check video recording in the zip file for more details.

**Steps to reproduce:**

1) Create a scene called "instance" with any node as the root, and a few children nodes (such as sprites, etc.).
2) Make another scene called "main" and add the "instance" scene to "main" as a child.
3) Go into the "instance" scene and make one of its children nodes the root of the scene. Save the scene.
4) Go into the "main" scene
5) Go into the "instance" scene again. All the children nodes of the new roots may be deleted/disappeared. In some cases in the past, closing and reopening the scene doesn't bring the lost nodes back, while in others it does.

**Minimal reproduction project:**

[scene deletion bug.zip](https://github.com/godotengine/godot/files/4082326/scene.deletion.bug.zip)

**Comment by KoBeWi** [comment] 2020-01-19 19:19
Duplicate of #24484, already fixed in 3.2

As for
> In some cases in the past, closing and reopening the scene doesn't bring the lost nodes back, while in others it does.

it's possible you just accidentally saved the empty scene.

**Closed by KoBeWi** 2020-01-19 19:19 UTC
