### ISSUE TITLE
Node pointer exports do not work in tool mode

### ISSUE THREAD

**Issue by EIREXE** [godotengine/godot#65387] opened 2022-09-05 23:55 UTC
### Godot version

4.0 4b164b8e4790cfeb597b763123560b59a96458e5

### System information

Arch Linux, RADV

### Issue description

Currently, trying to access an exported node in tool mode results in the variable holding it being empty, this is I believe because the actual data is stored as a meta property, which can be accessed with `get("metadata/_editor_prop_ptr_variable_name")`

### Steps to reproduce

Open the MRP, open test.tscn, observe that the console prints that the node is indeed empty.

### Minimal reproduction project

[nodeptrmrp.zip](https://github.com/godotengine/godot/files/9492374/nodeptrmrp.zip)

**Comment by raulsntos** [comment] 2023-07-01 02:02
- I'm unable to reproduce in v4.1.rc1.mono.official [1f9e540f1].
- It seems this was fixed by https://github.com/godotengine/godot/pull/76389.
- Also, this issue is a duplicate of https://github.com/godotengine/godot/issues/74141.

**Closed by raulsntos** 2023-07-01 02:02 UTC
Labels: bug, topic:gdscript, topic:plugin
