### ISSUE TITLE
Autocompletion fails inside if when the method is defined below cursor

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#35721] opened 2020-01-29 23:52 UTC
**Godot version:**
3.2

**Issue description:**
Might be related to #22121 and similar issues.

Here's code for testing:
```
func test():
	
	
	if 1 < 2:
		pass

func hello_true():
	return true

const HELLO_FALSE = false
```
![image](https://user-images.githubusercontent.com/2223172/73407730-572c4e00-42fa-11ea-86f0-1085161076c9.png)
![image](https://user-images.githubusercontent.com/2223172/73407759-6a3f1e00-42fa-11ea-9e6b-0e6266a01981.png)
What's weird is that it randomly sometimes works in normal ifs, but always fails in nested if statements.

**Comment by Janglee123** [comment] 2020-01-31 11:03
It seems like parser fails to list functions below the if statement.

**Comment by kimjiy9607** [comment] 2020-02-10 22:03
I think it is related to #23264.

**Comment by Calinou** [comment] 2020-02-11 10:01
Duplicate of #23264.

**Closed by Calinou** 2020-02-11 10:01 UTC
Labels: bug, topic:editor, topic:gdscript
