### ISSUE TITLE
Implement some way to save files to real file system in a HTML5 version of a Godot game.

### ISSUE THREAD

**Issue by Ivoch** [godotengine/godot#18947] opened 2018-05-16 22:59 UTC
**Godot version:** 3

**OS/device including version:** HTML5

**Issue description:** There is currently no way to save/download files from within a HTML5 version of a Godot game.

**Steps to reproduce:** Create a small project with one Button and one FileDialog that saves an arbitrary text file. Works as expected in all exported versions, except HTML5. There is currently no way to save a file locally from HTML5, for example save games. FileDialog shows some virtual file system, probably in the browser sandbox mode. The file is only saved there and is inaccessible from the local OS or the server backend.

**Minimal reproduction project:**
[htmlsave.zip](https://github.com/godotengine/godot/files/2010991/htmlsave.zip)

**Comment by vnen** [comment] 2018-05-17 01:08
I think this a browser limitation, it doesn't let JavaScript or WebAssembly mess with the host filesystem.

**Comment by akien-mga** [comment] 2018-05-17 06:33
CC @eska014

**Comment by eska014** [comment] 2018-05-17 09:47
We can open a native file dialog. But if I add a function for that to `OS`, it'll have to implemented on all platforms

**Comment by Geequlim** [comment] 2018-05-17 11:47
@eska014 Here is already implemented for Window, Linux (GTK+), and macOS
https://github.com/GodotExplorer/NativeDialogs

**Comment by Calinou** [comment] 2018-05-17 13:45
Also see [this thread on the Godot subreddit](https://www.reddit.com/r/godot/comments/8jp8tz/savedownload_file_in_html5/) where I suggested @Ivoch to open an issue here.

**Comment by Zylann** [comment] 2018-05-17 17:48
Can't we use local storage?

**Comment by eska014** [comment] 2018-05-17 17:54
Persistent `user://` filesystem already works, using IndexedDB. This issue is about saving data from Godot as a file to the real file system.

The problem is, do we want to maintain functionality to open a native file dialog, e.g. `OS.native_file_save()`/`_open()`, for all platforms? This practically seems to be needed only for the HTML5 platform. On the other hand, I want to keep the number of HTML5-specific APIs as low as possible

**Comment by Zylann** [comment] 2018-05-17 19:39
Or at least, we could use interoperability so that HTML5-specific stuff that we can't put in Godot can be done with JS?

**Comment by eska014** [comment] 2018-05-17 20:36
You can already execute JavaScript in the browser using `JavaScript.eval()`

**Comment by raymoo** [comment] 2018-05-21 21:36
On Android it would mean not having to make `FileDialog` touchscreen-friendly

**Comment by 37TS** [comment] 2018-05-22 02:19
What about an encrypted CSV with a user-selected private key as an option to fill in the export settings?
The key could then be stored somewhere in the "project_name.**pck**" resource file.

**Comment by Calinou** [comment] 2019-10-02 16:39
Can JavaScript even force the browser to open a native file dialog? I don't remember seeing this, unless the browser is configured to ask for download location every time.

We can however force a download using JavaScript, including from a Base64 URL or similar. Just make sure not to initiate several downloads at once, or the browser will prompt the user before doing so (Firefox does this at least).

Maybe this can be implemented using the JavaScript singleton.

**Comment by Calinou** [comment] 2020-05-26 13:45
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!

**Closed by Calinou** 2020-05-26 13:45 UTC
Labels: feature proposal, platform:html5, topic:porting
