### ISSUE TITLE
Dual Screen workflow?

### ISSUE THREAD

**Issue by unfa** [godotengine/godot#20314] opened 2018-07-20 22:19 UTC
I wonder if anyone (like me) works with a dual-screen setup.

I've tried to make Godot 3 occupy both of my screens but I wasn't able to.

Is it possible at all?
Are there any plans for such options?
Any ideas?

I've searched but found nothing.

**Comment by toger5** [comment] 2018-07-20 23:48
there are a bunch of issues about it. currently it is not possible. to closest you can get (and this will not make you happy ;) ) is by using vs code on one screen with `godot tools Addon` and godot on the other...

And there might be OS native multi window support coming. (for popup dialogs at least) but this should allow games/(and the editor) to do anything on multiple windows.

And it also might take some time to reorganise the editor layout. It is very good at being responsive to your current test. so ripping it apart for dual window might be harder than desired... but I could imagine that that it fairly easy to do the filling modes:
 - screen 1: fullscreen centre window (2d 3d script...) screen 2: all the docks
 - pop out 2d, 3d, script, shader editor... to a new window and move it to the other screen.

**Comment by swarnimarun** [comment] 2018-07-21 06:30
As toger5 said there are numerous issues about the topic, this is better you go and discuss your ideas there. And close this one.

And from what I know we won't be seeing this feature in 3.1 for it will require a pretty hefty overhaul. But it is on the roadmap and we can hope to get it sooner rather than later.

**Comment by akien-mga** [comment] 2018-08-16 14:53
Duplicate of #9059, not possible for now as Godot does not support multiple windows.

**Closed by akien-mga** 2018-08-16 14:53 UTC
