### ISSUE TITLE
Area Nodes body_shape_entered signal returns wrong body_shape index

### ISSUE THREAD

**Issue by 19PHOBOSS98** [godotengine/godot#38281] opened 2020-04-28 03:36 UTC
**Godot version:**
3.2.1
**OS/device including version:**
Macbook Pro 10.15.2
**Issue description:**
I had a static body with more than two shapes. The area node moves around with the player. The node detects the static body just fine but it keeps returning a body_shape index of 0 regardless of which collision shape it detects. Is this a bug or am I doing something wrong?
**Steps to reproduce:**
-add a scripted area node with the "entered_body_shape" signal pointed to the script and parent it to an avatar
-create a static body with two or more collision shapes
-collide with said collision shapes using player's area node
-read out returned value of parameter "body_shape"

**Minimal reproduction project:**

[Wrong Body Shape Index.zip](https://github.com/godotengine/godot/files/4543212/Wrong.Body.Shape.Index.zip)

**Comment by Calinou** [comment] 2021-05-15 16:57
Duplicate of https://github.com/godotengine/godot/issues/19290. As a workaround, switch to the GodotPhysics engine instead of Bullet.

**Closed by Calinou** 2021-05-15 16:57 UTC
Labels: bug
