### ISSUE TITLE
Node renaming in tree no longer occurs on double click, and visual of renaming node is not as clean

### ISSUE THREAD

**Issue by EricEzaM** [godotengine/godot#38817] opened 2020-05-18 02:00 UTC
**Godot version:**
Godot Engine v4.0.dev.custom_build.d4599fff6
**OS/device including version:**
Win 10 1903
**Issue description:**
Before (3.2.1 stable): Rename opens on double click, popup is nice and clean
![5P44edRna7](https://user-images.githubusercontent.com/41730826/82167404-0a976d80-98ff-11ea-9bd5-5ba6c441ca89.gif)

After (v4.0.dev.custom_build.d4599fff6): Double click doesnt work, popup has unneeded padding.
![wTTkYAO19Q](https://user-images.githubusercontent.com/41730826/82167432-2864d280-98ff-11ea-96ec-09ef0a53ea04.gif)

**Steps to reproduce:**
Make nodes

**Minimal reproduction project:**
n/a

Related to #37335

Edit: Also...
Pressing escape on text edit to cancel actually commits the edit

**Comment by akien-mga** [comment] 2020-05-18 07:29
What are "before" and "after" here?

**Comment by EricEzaM** [comment] 2020-05-18 08:21
> What are "before" and "after" here?

Sorry, 3.2.1 stable and latest dev build.

**Comment by EricEzaM** [comment] 2020-05-20 13:29
The double click issue might stem from here. 

https://github.com/godotengine/godot/blob/55377aa559a93dab1d479a7e45d4c717306b309e/scene/gui/tree.cpp#L2478

`pressing for editor` is false. If I manually set it to true in the IDE during a breakpoint, the popup shows on double click. Git bisect yielded no solid results as the builds that were narrowed down to would not compile for me at all. No idea why this is happening. Can't find where bug may have appeared based on git blame or the diff history.

The border issue is to do with styling... `PopupPanel` shares the style with `Popup` which seemed to get a new stylebox, which has margins of 8 on all sides. That is an easy fix.

**Comment by EricEzaM** [comment] 2020-05-20 14:39
Traced it back further...

In 3.2, we have
https://github.com/godotengine/godot/blob/b6c551e8646bedde0f81ac3a4f61f9709e82668d/scene/main/scene_tree.cpp#L416-L421

Which has been removed in 4.0. tree.cpp relies on current_event though, as seen here:

https://github.com/godotengine/godot/blob/b6c551e8646bedde0f81ac3a4f61f9709e82668d/scene/gui/tree.cpp#L1882-L1891

Here, the second conditional in the if is always true, since current event never changes... thus the editor never appears. Seeing as input_event was removed from scene_tree, this doesnt seem to be such an easy fix. Thoughts @akien-mga?

**Comment by reduz** [comment] 2020-07-02 14:55
Duplicate of #37335, which was already closed in  #40020

**Closed by reduz** 2020-07-02 14:55 UTC
Labels: bug, regression, topic:editor
