### ISSUE TITLE
Black borders at the bottom of windows form and popups cause frequent small UI displacements

### ISSUE THREAD

**Issue by GenesisAN** [godotengine/godot#92266] opened 2024-05-22 19:49 UTC
### Tested versions

v4.2.2,v4.3-dev6

### System information

Godot v4.2.2.stable.mono - Windows 10.0.22631 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 4060 Laptop GPU (NVIDIA; 32.0.15.5585) - AMD Ryzen 9 7940HX with Radeon Graphics (32 Threads)

### Issue description

https://github.com/godotengine/godot/assets/42198626/aac240a5-1bdc-4a32-bf57-b809c6369c73

This black border cannot be captured by screenshots or screen recording software and can only be seen through the monitor. It slightly affects the user interface layout and causes the UI to shift slightly when it appears.

I noticed it the first time I used Godot on my new laptop.

As the mouse moves over the Godot control, it sometimes appears and sometimes disappears, causing a slight UI jitter.

### Steps to reproduce

N/A

### Minimal reproduction project (MRP)

N/A

**Comment by Calinou** [comment] 2024-05-22 20:26
Do you have any third-party overlays installed (similar to https://github.com/godotengine/godot/issues/13208 or https://github.com/godotengine/godot/issues/32990)?

Vulkan layers shouldn't cause issues in the project manager as it always uses OpenGL, so it's likely a third-party overlay that affects OpenGL as well.

**Comment by GenesisAN** [comment] 2024-05-23 02:42
I tried using `--single-window` and I noticed that the black border no longer appears in the popup window, but the black border is still present throughout the godot windows form. I also noticed the other two issuss you mentioned.

Also I don't have any software installed on my computer that involves overlays, including Fence, and I've turned off overlays for both NVIDIA and AMD, and the problem still occurs.

I tried switching the operating mode of my NVIDIA graphics card, and in `NVIDIA-only` mode, the black border no longer appears in godot, but in both `optimus` and `auto-select` modes, it appears.

**Comment by GenesisAN** [comment] 2024-09-18 00:51
After using the official Windows 11 image on my laptop and reinstalling everything through a USB drive, then reinstalling all the drivers, I found that the issue no longer occurs. I cannot determine which step resolved the problem, but it seems that the issue has indeed disappeared.

**Comment by GenesisAN** [comment] 2024-09-18 00:53
> Can you reproduce this when starting the project manager with the `--single-window` command line argument?
> 
> Do you have any third-party overlays installed (similar to #13208 or #32990)?
> 
> Vulkan layers shouldn't cause issues in the project manager as it always uses OpenGL, so it's likely a third-party overlay that affects OpenGL as well.

After using the official Windows 11 image on my laptop and reinstalling everything through a USB drive, then reinstalling all the drivers, I found that the issue no longer occurs. I cannot determine which step resolved the problem, but it seems that the issue has indeed disappeared.

**Comment by akien-mga** [comment] 2024-09-18 08:30
Thanks for the update. Closing then as we won't be able to investigate further if you can't reproduce the issue anymore, but it was likely caused by a driver bug or similar.

**Closed by akien-mga** 2024-09-18 08:30 UTC
Labels: bug, platform:windows, topic:rendering, topic:porting, needs testing
