### ISSUE TITLE
Android inst2dict() and resource loading errors at start

### ISSUE THREAD

**Issue by Tobi-La** [godotengine/godot#23987] opened 2018-11-26 13:06 UTC
**Godot version:**
3.1.alpha.calinou.815557c

**OS/device including version:**
Oukitel K6000 Pro
Android 6.0

**Issue description:**
When starting my app on android on this device the Godot logo flashes for a few times, afterwards the app crashes. Here are the first errors I found in logcat:

> 
> 11-26 13:44:32.774 19120 19136 E godot   : **SCRIPT ERROR**: Parse Error: Too many arguments for 'inst2dict()' call. Expected at most 1.
> 
> 11-26 13:44:32.774 19120 19136 E godot   :    At: res://scripts/Data/currency.gdc:16:GDScript::load_byte_code() - Parse Error: Too many arguments for 'inst2dict()' call. Expected at most 1.
> 
> 11-26 13:44:32.774 19120 19136 E godot   : **ERROR**: Method/Function Failed, returning: ERR_PARSE_ERROR
> 
> 11-26 13:44:32.774 19120 19136 E godot   :    At: modules/gdscript/gdscript.cpp:768:load_byte_code() - Method/Function Failed, returning: ERR_PARSE_ERROR
> 
> 11-26 13:44:32.774 19120 19136 E godot   : **ERROR**: Condition ' err != OK ' is true. returned: RES()
> 
> 11-26 13:44:32.774 19120 19136 E godot   :    At: modules/gdscript/gdscript.cpp:2119:load() - Condition ' err != OK ' is true. returned: RES()

Afterwards I get errors from my resources in the following format

> 11-26 13:44:32.774 19120 19136 E godot   : **ERROR**: Failed loading resource: res://path/to/script.gdc
> 
> 11-26 13:44:32.775 19120 19136 E godot   :    At: core/io/resource_loader.cpp:192:_load() - Method/Function Failed, returning: RES()
> 
> 11-26 13:44:32.775 19120 19136 E godot   : **SCRIPT ERROR**: Parse Error: Can't preload resource at path: res://path/to/script.gd
> 
> 11-26 13:44:32.775 19120 19136 E godot   :    At: res://path/to/otherScript.gdc:5:GDScript::load_byte_code() - Parse Error: Can't preload resource at path: res://path/to/script.gd
> 
> 11-26 13:44:32.775 19120 19136 E godot   : **ERROR**: Method/Function Failed, returning: ERR_PARSE_ERROR
> 
> 11-26 13:44:32.775 19120 19136 E godot   :    At: modules/gdscript/gdscript.cpp:768:load_byte_code() - Method/Function Failed, returning: ERR_PARSE_ERROR
> 
> 11-26 13:44:32.775 19120 19136 E godot   : **ERROR**: Condition ' err != OK ' is true. returned: RES()
> 
> 11-26 13:44:32.775 19120 19136 E godot   :    At: modules/gdscript/gdscript.cpp:2119:load() - Condition ' err != OK ' is true. returned: RES()

and so on, I guess this has something to do with load() and preload() calls from my code

**Steps to reproduce:**
I can't upload my project here, but if needed I can try to create a minimal reproduction project
Let me know if you need anything

**Comment by bojidar-bg** [comment] 2018-11-27 21:32
Make sure you have export templates **exactly** matching the version of Godot you are using. 
Download them from where you downloaded Godot, or compile some for the same commit.

Likely a duplicate of #21630 and/or #21630. Closing until proven wrong.

**Closed by bojidar-bg** 2018-11-27 21:32 UTC
