### ISSUE TITLE
Feature Request: Bounties

### ISSUE THREAD

**Issue by RUSshy** [godotengine/godot#31928] opened 2019-09-03 13:48 UTC
Hi

I just had this idea, many open source projects offers the ability to pay people for fixing bugs or implementing user requested features

How it could work:

User  post issue X

He has choice:

- Do nothing, and hope someone fix/solve it
- Create a bounty for N$, more people can add to the bounty, then if someone come with a valid PR, he can claim the bounty

**Comment by Calinou** [comment] 2019-09-03 14:10
Duplicate of #3792.

**Closed by Calinou** 2019-09-03 14:10 UTC
