### ISSUE TITLE
Scale doesn't reset when undoing a rotation with non uniform scale bones in Skeleton3D

### ISSUE THREAD

**Issue by marciocjr13** [godotengine/godot#84249] opened 2023-10-31 13:36 UTC
### Godot version

v4.1.1.stable.mono.official [bd6af8e0e]

### System information

Godot v4.1.1.stable.mono - Windows 10.0.19044 - Vulkan (Forward+) - dedicated AMD Radeon RX 580 2048SP (Advanced Micro Devices, Inc.; 31.0.12027.9001) - Intel(R) Core(TM) i5-10400F CPU @ 2.90GHz (12 Threads)

### Issue description

If the parent of a bone is of non uniform scale (anything other than 1), then the bone scale of the child will change when rotating it, this is actually normal behaviour to keep the proportions as far as I am aware, but the issue is when you undo the rotation (in case of a mistake), the editor will revert the rotation but will not revert the scale, which can lead to models eventually looking "distorted" if you don't notice it at first.

Example Screenshots:

- Here is the skeleton with the torax bone having a non uniform scale, look at the scale of the arm and compare it in the following screenshots:
![Screenshot 2023-10-31 102536](https://github.com/godotengine/godot/assets/50471444/8387f54c-d065-4e47-a965-2fae91658b80)

- Now with rotation applied to the arm, the scale has changed. The scale does not change in uniform scale bones but as far as I am aware this is normal behaviour to keep proportions consistent.
![Screenshot 2023-10-31 102557](https://github.com/godotengine/godot/assets/50471444/880f99ec-2ef3-4df4-a5d2-a72364304f28)

- Now here is the issue: if you undo, the rotation will revert back, but the scale will not. Eventually, it will add up and distort the model.
![Screenshot 2023-10-31 102612](https://github.com/godotengine/godot/assets/50471444/ffd06759-1e6e-4cd0-85df-cacd0afc2f32)

In the example project I included both an uniform and non uniform variant of the same skeleton so you can compare the results.

### Steps to reproduce

1. Scale a bone with children to a non uniform (non 1) scale
2. Rotate the children
3. Undo

### Minimal reproduction project

[Skeleton Scale Issue.zip](https://github.com/godotengine/godot/files/13216941/Skeleton.Scale.Issue.zip)

**Comment by AThousandShips** [comment] 2023-10-31 13:37
Can you please try this with a supported version, like 4.1.2 (only the latest patch version is supported, and it might already be fixed)

**Comment by marciocjr13** [comment] 2023-10-31 13:41
> Can you please try this with a supported version, like 4.1.2 (only the latest patch version is supported, and it might already be fixed)

I have tried it now on v4.1.2.stable.mono.official [399c9dc39] and with v4.2.beta4.mono.official [93cdacbb0] and can confirm the issue persists.

**Comment by rsburke4** [comment] 2023-11-11 02:14
As shown in the video below, I think I found a solution to the "undo" issue, but there's something more serious going on here. (Note: I flattened the torso a lot to exaggerate the effect here. The more the scaling, the greater the effect of the propagated error.)

https://github.com/godotengine/godot/assets/37226458/7ae01df3-0f76-4c50-b837-ab48269d8fa9


If the behavior we're trying to achieve is localizing the non-uniform scale to bones higher in the hierarchy without affecting children than I think there's a little extra work to do. I don't mind looking into this further.

**Comment by TokageItLab** [comment] 2023-11-11 16:08
Related https://github.com/godotengine/godot-proposals/issues/4190. I believe the solution to this is https://github.com/godotengine/godot/pull/83903#issuecomment-1780257075. I will put it in a proposal later but I am currently working on another task so please wait a little while.

**Comment by fire** [comment] 2023-11-11 16:51
@bbqbarbhg developed a way to emulate the two modes mentioned in godot engine. Can you describe how they work?

**Comment by bqqbarbhg** [comment] 2023-11-11 17:32
Not sure if it applies here, but the scale compensation by undoing parent scale as in #4190 will break for non-uniform scaling. What I did in ufbx is to add auxiliary in case animated or non-uniform scaling is used. The scale of the parent node is moved into a helper:

```
Parent (scale set to 1)
+ ScaleHelper (scale moved here)
| + (skin reference)
| + ScaledChildren
+ UnscaledChildren
```

To make this work you still need to modify the translation of `UnscaledChildren` by the scaling amount of `ScaleHelper`. This works for animations contained within the file but fails for runtime animations, as either you scale `Parent` which will scale `UnscaledChildren` or `ScaleHelper` which will cause `UnscaledChildren` to not move as intended.

If a native non-scale-inheriting bone mode would be implemented it would benefit the ufbx importer as well, as the workaround has the above caveat and some others caused by using external animation library assets. FBX also contains a mode that propagates the scale without shearing, but it is so rarely used that it's not worth implementing into a generic skeleton in my opinion.

**Comment by fire** [comment] 2023-11-12 22:10
The previous link was https://github.com/godotengine/godot-proposals/issues/4190

**Comment by fire** [comment] 2024-05-15 14:30
@TokageItLab do you think it's related to https://github.com/godotengine/godot/pull/90064 ?

**Comment by fire** [comment] 2024-05-17 17:52
https://github.com/godotengine/godot/pull/92012 was merged to fix this. Can you try?

**Comment by fire** [comment] 2024-05-24 17:31
I tested a build with #92012 and further changes and it seems to be fixed. Did not narrow down the list of changes though.

**Comment by fire** [comment] 2024-05-27 14:58
Thanks for your bug report, as far as I can tell it's fixed, but feel free to comment if it's still broken.

**Closed by fire** 2024-05-27 14:58 UTC
Labels: enhancement, discussion, topic:animation, topic:3d
