### ISSUE TITLE
3.0.x: Comments above shader_type makes shader compiler assume spatial

### ISSUE THREAD

**Issue by nobuyukinyuu** [godotengine/godot#20984] opened 2018-08-13 20:34 UTC
**Godot version:**
3.0.x series (tested on 3.0.6)

**OS/device including version:**
Windows

**Issue description:**
Placing comments in lines before `shader_type` breaks access to non-spatial attributes.
The following code will produce an error "Unknown identifier in expression:  TEXTURE" and will not highlight the attribute.  Attributes such as `ALBEDO` *do* get highlighted and seem to indicate that the compiler is picking up on the shader_type statement at some point but doesn't pass the correct type.

```glsl
//I'm a comment
shader_type canvas_item;


void fragment(){
	
	COLOR.rgba = texture(TEXTURE, UV);
}
```

This issue doesn't seem to affect 3.1 at current.

**Comment by Chaosus** [comment] 2018-08-19 13:06
Fixed by 9423f23

**Closed by Chaosus** 2018-08-19 13:06 UTC
Labels: bug, topic:rendering

**Comment by nobuyukinyuu** [comment] 2018-08-19 14:57
Hi, this commit indicates it's targeted for version 3.1.  This bug is specific to the 3.0 branch.  Is a backport planned, or is the milestone from this issue in error?

**Comment by akien-mga** [comment] 2018-08-19 15:46
That commit was merged 25 days ago and is labelled for cherry-picking to the 3.0 branch (#16052), so it will happen eventually.

This issue is a duplicate of #16032.
