### ISSUE TITLE
Textures don't appear on export with improper capitalisation but do appear in the debugger

### ISSUE THREAD

**Issue by Emarald64** [godotengine/godot#79298] opened 2023-07-10 16:42 UTC
### Godot version

4.1

### System information

Windows 11

### Issue description

When running a project that loads files in code though the debugger the capitulation of file names doesn't matter. However when exporting the project the capitulation does matter. This can lead to issues that only appear when exporting the project but not when developing.

### Steps to reproduce

Create a scene with a textureRect node. create a script that assigns a texture to the node but has improper capitulation of the file name. when the scene is run in the editor the txture appears on the node. However when exported the texture does not appear

### Minimal reproduction project

[Archive.zip](https://github.com/godotengine/godot/files/12004353/Archive.zip)

**Comment by Emarald64** [comment] 2023-07-10 17:07
In the editor and when running it I don't get any errors. I think when I exported to windows and ran the console version I got errors

**Comment by KoBeWi** [comment] 2023-07-10 22:28
There is a warning about it:
![image](https://github.com/godotengine/godot/assets/2223172/c9a2d989-b867-4221-886e-c12c89c9acc9)

**Comment by KoBeWi** [comment] 2023-07-10 22:29
Closing as duplicate of the mentioned issue.

**Closed by KoBeWi** 2023-07-10 22:29 UTC
Labels: topic:editor, needs testing, topic:export
