### ISSUE TITLE
(4.0) Menu dropdown show in wrong position

### ISSUE THREAD

**Issue by seppoday** [godotengine/godot#57397] opened 2022-01-29 12:05 UTC
### Godot version

4.0 alpha 1

### System information

Windows 11

### Issue description

![image](https://user-images.githubusercontent.com/62170071/151660333-539fec13-66f0-49e0-ab0e-030fc4437728.png)

### Steps to reproduce

Dunno. It just happens sometimes and then it just stays that way.

**Comment by timothyqiu** [comment] 2022-01-29 12:13
Duplicate of #45740

**Closed by timothyqiu** 2022-01-29 12:13 UTC
