### ISSUE TITLE
4.2 dev5 - Borderless fullscreen window size is incorrect

### ISSUE THREAD

**Issue by dogboydog** [godotengine/godot#82156] opened 2023-09-22 22:25 UTC
### Godot version

v4.2.dev5.mono.official [e3e2528ba]

### System information

Windows 10, Nvidia RTX 3090

### Issue description

I discovered this when testing the new integer scaling option in Project Settings. 

![image](https://github.com/godotengine/godot/assets/9920963/71f45a18-b477-40b5-ab91-5500db1285a0)

The DisplayServer is reporting a window size that is not the same as the screen size in full screen mode. I wrote a MRP with a script which prints the screen vs window size.

The output for me is this: 

Screen(1920, 1080)
Window: (1918, 1078)

The window is 2 pixels smaller in both dimensions than the screen size, which means even though the the screen size is divisible by the viewport size,   integer scaling leaves black bars around the viewport. Is this a settings problem I have in my project and the repro or a bug? Maybe I'm misunderstanding something. 

I get the same behavior on my Windows 11 laptop as well. 

Thank you

### Steps to reproduce

Run the attached project and observe console output / game appearance

### Minimal reproduction project

[windowsize_fullscreen.zip](https://github.com/godotengine/godot/files/12704916/windowsize_fullscreen.zip)

**Comment by bitsawer** [comment] 2023-09-22 22:37
Thanks for the report. Duplicate of https://github.com/godotengine/godot/issues/63500, see https://github.com/godotengine/godot/issues/63500#issuecomment-1418733855 for more information.

If you are not planning on creating multiple windows, you should probably just use "Exclusive Fullscreen" mode.

**Closed by bitsawer** 2023-09-22 22:37 UTC

**Comment by dogboydog** [comment] 2023-09-22 22:40
I see. Thank you
