### ISSUE TITLE
Godot Wont open and crash.

### ISSUE THREAD

**Issue by Vyntage2557** [godotengine/godot#54902] opened 2021-11-12 05:50 UTC
### Godot version

Godot v3.4-stable_osx.universal

### System information

Macbook Pro, macOS Catalina 10.15.7, mid 2012, GPU Intel HD Graphics 4000 1536 MB, Memory 4 GB 1600 MHz DDR3, Processor 2.5 GHz Dual-Core Intel Core i5

### Issue description

I have used godot for a while now and when i updated it to godot 3.4 it just crashes and shows "Godot quit unexpectedly" and another option shows up which has these options (reopen and don't reopen) and both of them dont work. Please help!

### Steps to reproduce

1. Download Godot
2. Extract Godot
3. Open Godot
4. Godot Crashes
5. "Godot Quit Unexpectedly" Appears
6. Click "Reopen"
7. Another option shows up "Reopen" or "Don't Reopen" (None of them helps)

**Comment by Calinou** [comment] 2021-11-12 10:46
Duplicate of https://github.com/godotengine/godot/issues/54421.

**Closed by Calinou** 2021-11-12 10:46 UTC
Labels: bug, platform:macos, needs testing, crash
