### ISSUE TITLE
Animations are not resetting properly when played in the editor.

### ISSUE THREAD

**Issue by Sslaxx** [godotengine/godot#812] opened 2014-10-23 13:21 UTC
https://www.dropbox.com/s/krusjk4lh0655da/812_Demonstrator.webm?dl=0

I've noticed if I wanted the animation to reset properly in the editor, I had to either play it and VERY quickly stop it, play it and then rewind the animation back to the start, then (and this is the buggy bit) if I wanted the animated item to work properly again I had to first select it.

The keyframes are at 0 and 0.5, by the way. https://mediencenter.t-online.de/auth/guest/shareToken/DDE241350EA1C553A3945179DF687D896509C0DF is the example uploaded by Wendigo on http://www.godotengine.org/forum/viewtopic.php?f=11&t=1024

**Comment by akien-mga** [comment] 2015-10-31 12:23
I must admit I did not understand the bug by watching the video... I played a bit with the test scene attached in the second link, and couple finally manage to understand what you mean by 

>  (and this is the buggy bit) if I wanted the animated item to work properly again I had to first select it

Indeed if you stop the animation e.g. mid-course in the editor, and then run the game, it will not be shown mid-course. On the other, if you select the mid-course animation in the editor, and then play the game, it will be shown mid-course.

**Comment by akien-mga** [comment] 2016-04-23 13:57
After discussing it with @bojidar-bg, it's far from a junior job, as fixing this without a hack likely involves rethinking the way the animation player modifies on the fly the properties of the nodes it acts upon.

**Comment by slapin** [comment] 2016-04-23 15:21
Why not just reset all loaded animation resource positions to 0? Should be simple enough.

**Comment by slapin** [comment] 2016-04-23 15:23
We have a habit of "lets postpone that as this is too complex", that is not really a good habit.
Lets split big problem into simple ones and solve one by one, instead of waiting for something,
which will probably never happen.

**Comment by bojidar-bg** [comment] 2016-04-23 15:31
@slapin Because the 0-frames of different animations might conflict with each other, in which case we get undefined behavior. Don't think we made a quick work of it. We discussed it in depth to the point in which it became obvious that the only "normal" solution would be to rewrite the way animations are played. Not much people know godot code as much as to fix me (I don't either).

Also, if we decide on a solution for the conflicting 0-frame thing, I would be happy to implement it, though it would be behind an editor settings flag.

**Comment by slapin** [comment] 2016-04-23 18:45
Could you please elaborate on 0-frames conflict? I don't see a case where that would conflict
at start/initialization time?

**Comment by akien-mga** [comment] 2016-04-24 12:12
The problem is that you can keyframe properties at position 0 in animations, and the way the AnimationPlayer is built in Godot implies that the state of the animation is directly reflected on the properties of the affected nodes.

So imagine that you have a scene with a Sprite with e.g. 10 frames.
- In animation "idle", you keyframe the frame 0 at position 0.
- In animation "run", you keyframe the frame 5 at position 0, because it's the first frame you want to use in your running animation.
- In animation "fight", you keyframe the frame 8 at position 0, etc.

Now if all animations are reset to position 0 upon saving, the question of what frame should be displayed in the Sprite is undefined. Obviously one would like to use frame 0 in my example, which would typically be e.g. a character facing the player. But that's not something the engine could decide by itself. What if the "default" frame should be frame 4?

Same issue if you have animations starting with a fade in, by resetting to position 0 in this animation you may end up having your Sprite displayed with opacity 0 by default.

**Comment by puppetmaster-** [comment] 2017-05-29 11:18
I ask this question again on the proper issues... #8976

Is it possible to rewind each animation before saving (scene) or playing (scene/project)?

**Comment by bojidar-bg** [comment] 2017-05-29 18:40
@puppetmaster- Check comments above, slapin specifically asked:
> Why not just reset all loaded animation resource positions to 0? Should be simple enough.

The problem is that you might have conflicts between the first frames of different animations, as I and @akien-mga  discussed way back (check the other comments for more info).

We can potentially just rewind them in alphabetical order (or some other well-defined order), with the autoplayed animation last, but I'm not completely sold over that idea yet.

**Comment by puppetmaster-** [comment] 2017-05-29 19:45
@bojidar-bg Sorry, I have read the comments above but for me reset to position 0 and rewind is not the same. 

I found out what the problem in my case is. :smiley: 
There is some intelligence hidden when playing an animation. Godot know that nothing has changed.
But with Editor:Setting Auto Save Before Running = true it saves the sprite position !?!
![scene_got_saved_also_when noting_has_changed](https://cloud.githubusercontent.com/assets/10463138/26560555/da5560b2-44b7-11e7-8bba-eec27183e60a.gif)

Should I open a new issue?

**Comment by Sslaxx** [comment] 2017-06-01 19:11
Is this fixed by #8982? That references #8976.

**Comment by bojidar-bg** [comment] 2017-06-02 08:24
@Sslaxx No, if this was fixed, then #8976 could be termed fixed, since we wouldn't be able to reproduce it, the opposite isn't true.

**Comment by akien-mga** [comment] 2018-05-09 08:30
First of all thank you for your report and sorry for the delay.

We released Godot 3.0 in January 2018 after 18 months of work, fixing many old issues either directly, or by obsoleting/replacing the features they were referring to.

We still have hundreds of issues whose relevance/reproducibility needs to be checked against the [current stable version](https://godotengine.org/download), and that's where you can help us.
**Could you check if the issue that you described initially is still relevant/reproducible in Godot 3.0 or any newer version, and comment about it here?**

For bug reports, please also make sure that the issue contains detailed steps to reproduce the bug and, if possible, a zipped project that can be used to reproduce it right away. This greatly speeds up debugging and bugfixing tasks for our contributors.

Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

Thanks in advance.

*Note: This message is being copy-pasted to many "stale" issues (90+ days without activity). It might happen that it is not meaningful for this specific issue or appears oblivious of the issue's context, if so please comment to notify the Bugsquad about it.*

**Comment by KoBeWi** [comment] 2018-06-07 01:20
So, I'm making a complex cut-scene that involves multiple animations playing after each other and I find the Animator's behavior to be ULTRA annoying. It's counter-productive needing to rewind your current animation each time you want to see how it looks currently in-game, because otherwise everything dependent is randomly displaced over the scene. The suggestion to reset everything upon saving is unnecessary. I'd be happy with a single button that just resets currently selected animation, basically an instant-rewind, to not waste time carefully moving your timeline back.

**Comment by reduz** [comment] 2018-06-07 18:29
I don't think a proper fix to this exists because the animation system does not really understand initial values.

What I propose, is that one could mark an animation as the "default", and Godot may set the state of the animation to whatever is in there before saving. Optionally, we could add a reset button that appears if this animation exists, so you can use it easily from the editor.

**Comment by reduz** [comment] 2018-06-07 18:32
Or maybe when the scene is loaded in the game, the "reset" animation applies its values to everything.

**Comment by KoBeWi** [comment] 2018-06-07 18:40
My problem right now is that whenever I want to play my scene (which is necessary for full test, because I use some stuff outside animator), I have to either rewind the animation by moving timeline manually (absolutely awkward and you need to be careful not to skip some values) or press the rewind button and wait 15 seconds. I need a way to speed-up the process, so a reset button that instantly rewinds the animation and sets all tracks to first value in timeline, would be sufficient.

Unless I'm doing something wrong and there's a better way. I'm using a series of single animations for a cutscene.

**Comment by KoBeWi** [comment] 2018-06-07 20:01
The "default" animation isn't really needed, but could be there as an option. I'd be for resetting everything in alphabetical order, so you can manipulate animation sorting to resolve conflicts yourself. Setting a "default" animation could override this and just reset all values to this particular animation.

As for resetting, a reset button would be obviously useful. Not sure about auto-resetting, unless you'd be able to select when it's happening. Some people might want it when saving and some only when running scene. Also, there could be distinction between "reset all" button, which would have the behavior I described above and "reset current animation" button.

btw, you said animation doesn't understand initial values, but they are just values at first key in respective track.

**Comment by reduz** [comment] 2018-06-08 01:05
@KoBeWi different animations may have different initial values, so there is not really any information for resetting. This is why I think the only practical way is to defining a special animation with the initial values on load

**Comment by KoBeWi** [comment] 2018-06-08 01:19
That's why I said they should all at once be reset in e.g. alphabetical order. This way initial values would be the ones from last animation. But well, if that "special animation" you mention gets special treating (like being played before actual autoplay animation or having a dedicated reset button), it should be fine too. Still better than what we have now.

**Comment by cart** [comment] 2018-06-08 01:58
I dont think using names to create a precedence order is a good idea. Changing an animation name shouldn't affect state like that. And any sort of ordering seems overly complex / hard to reason about.

I like @reduz's "default" approach. Its simpler and more explicit. In my project I frequently use a "default" animation to reset animation state in editor and in code. It would be nice to formalize that.

**Comment by KoBeWi** [comment] 2019-05-19 22:20
Soooo... how about some super-magical UndoRedo action triggered on play and commited on stop that would record all changed properties, so you can easily undo them?

**Comment by Anutrix** [comment] 2019-10-20 06:18
Any updates?

**Comment by rvenson** [comment] 2020-01-19 19:08
> @KoBeWi different animations may have different initial values, so there is not really any information for resetting. This is why I think the only practical way is to defining a special animation with the initial values on load

The values that we set in the editor can't be used as default values for all the animations? I don't know if I understood the problem clearly, but I have an annoying issue related to this:

![ezgif-3-8bda173ce0a7](https://user-images.githubusercontent.com/7561122/72686547-c1601a00-3ad4-11ea-976d-fef66701f3a8.gif)
> An example of unintentional lost of information

Ex.:
* Create a black background (_ColorRect_)
* Create an _AnimationPlayer_ and an animation that change the background to red colour at whatever frame (without defining any first keyframe)
* Play the animation
* Now the default value (black) that I defined in the editor was lost forever!

I know that I should define the first keyframe with the black colour, but then we go back to the rewind issue problem. And sometimes, you just need to change the background colour to red, regardless of the actual colour in-game.

![ezgif-3-d249629b399e](https://user-images.githubusercontent.com/7561122/72686548-c1601a00-3ad4-11ea-806b-24154f00a069.gif)
> Rewind to get default values on animation

Sorry for any missconception and let me know if there is any workaround about this. :)

**Comment by dschoemehl** [comment] 2020-04-13 16:27
Just hit this issue myself. I would put this in the same family of confusion as [#17903](https://github.com/godotengine/godot/issues/17903). Values changing in the inspector are confusing. If I change values in script, they don't maintain those changes. But if I change values with the AnimationPlayer, the changes will remain. I am solving this by setting default values in the _ready(). This has two implications from a usability standpoint:

1) I have to change my thinking as to how to use the inspector window. When using the AnimationPlayer it is important to understand that those values are not defaults, but rather a way to input values for the animation key frames.
2)  I now need to remember to hard code the default values into my _ready() function for every value that I change. I could make a default animation to store these as well, but the same bookkeeping remains. I may try that as well just to see the difference.

Overall I am loving Godot and I have a workaround so I can move forward. No matter what tool you pick you will hit these sorts of things if you use it long enough and I am very appreciative of the hard work the community has put into this!

My suggest would be to consider another button or mode on the Inspector window to specify if you are setting/viewing default or animation values.
![AnimationSettings](https://user-images.githubusercontent.com/4430542/79137948-488df880-7d79-11ea-97ff-f498ae78e0f5.jpg)

**Comment by KoBeWi** [comment] 2020-10-08 13:03
Closing in favor of https://github.com/godotengine/godot-proposals/issues/1597 which would fix this issue.

**Closed by KoBeWi** 2020-10-08 13:03 UTC
Labels: bug, discussion, topic:editor
