### ISSUE TITLE
New inspector does not save material changes

### ISSUE THREAD

**Issue by BastiaanOlij** [godotengine/godot#18997] opened 2018-05-18 09:37 UTC
**Godot version:**
Latest master

**OS/device including version:**
n/a

**Issue description:**
When I open up a material .tres file and edit settings, there is no way to save the changes. When using CTRL-S to save, it reverts my changes back to what it was.

**Steps to reproduce:**
Thats the other thing, when adding a material to a mesh or meshinstance, I don't have a way to save it as a .tres file either, but if you have a .tres material file you can reproduce it by trying to edit it :)

**Comment by BastiaanOlij** [comment] 2018-05-18 12:03
Note, I found the save function, have to edit the resource, then use the save in the dropdown. 
Not very user friendly..

Do have to say the new interface is growing on me

**Comment by reduz** [comment] 2018-09-07 15:04
This is an usability enhancement proposal, will probably not happen for 3.1, so kicking to 3.2

**Comment by KoBeWi** [comment] 2019-04-25 23:31
Looks like using CTRL + S is saving materials properly in 3.1. It actually saves scene, but was changed that also saves all opened resources, or something like that. Anyways, I can't reproduce the issue now.

**Comment by akien-mga** [comment] 2019-04-25 23:32
Closing as fixed.

**Closed by akien-mga** 2019-04-25 23:32 UTC
Labels: enhancement, topic:editor

**Comment by nickritter** [comment] 2020-08-01 22:04
This is happening to me now too. I've got a textline node in an hbox and I keep changing the hbox margin, but when I edit any other property in the inspector, the margin reverts back to normal. I'm in Godot 3.2.2 stable on Windows 10 Pro 64-bit.
