### ISSUE TITLE
Resource type error

### ISSUE THREAD

**Issue by 2821869675** [godotengine/godot#37735] opened 2020-04-10 02:20 UTC
**Godot version:**
3.2.1.stable
**OS/device including version:**
windows 7 Ultimate X64
**Issue description:**
Godot cannot recognize the text file written to the content
**Steps to reproduce:**
In a project, create a text-type resource(TextFile) in the file system
Then write something like this:
`[
	{
		"amount": 1,
	},
	{
		"path": "1/a.tscn",
	}
]`

Save, close the project and reopen it
Godot couldn't edit it and would report errors

**Minimal reproduction project:**
[demo.zip](https://github.com/godotengine/godot/files/4459574/demo.zip)

**Comment by aaronfranke** [comment] 2020-04-10 06:54
This is mostly a duplicate of #21787, though it doesn't specifically mention these exact steps, the bug is still the same. See also #24187.

**Closed by aaronfranke** 2020-04-10 06:54 UTC
Labels: bug, topic:editor
