### ISSUE TITLE
Odd Behavior adding a new Scene in 4.0.2.stable

### ISSUE THREAD

**Issue by mykael22000** [godotengine/godot#76579] opened 2023-04-29 13:22 UTC
### Godot version

v4.0.2.stable.official [7a0977ce2]

### System information

Windows 10, Intel i7, 32GB

### Issue description

I've just worked through the 2D Game Tutorial.

I normally had the big panel in the center set to 'Script' when I was adding new scenes (because this is where the tutorial sort of leaves you).

It seems that if I added a scene (with the '+' button above the main view), I'd get a new script as well - but the script was untitled and wasn't linked to the new scene.  It's contents appeared to be the same as the contents of the last scrip I'd been editing.

I made changes to the script and saved it as HUD.gd.  Only when I tried to connect events from the HUD scene nodes to it, did I get any errors - Scene has no Script linked.  I saved it, the used the node dialog to link the script tot he scene - and it erased my script, replacing it with a blank HUB.gd stub.  I was then able to connect it up ok.

The next bit of oddness was that my Main.gd script seemed to have been overwritten by a part of the Hub.gd script.  I erased that data and had to reenter the Main.gd script from the tutorial.

I think all the problems come from adding a new scene in script editor mode, attempting to create a new script.

### Steps to reproduce

Bring the script editor up with a scene linked script showing and press the + button to add a new scene:

![image](https://user-images.githubusercontent.com/6858095/235304831-0aa891b4-c44e-4b8b-b5c8-e057b9ecffc9.png)

I get a new script called 'empty' which contains the same script as the script I was editing when I hit the +:

![image](https://user-images.githubusercontent.com/6858095/235304875-5592d90b-252e-407d-bffd-0113e6d8ed35.png)

### Minimal reproduction project

Will probably occur with any Godot project, but I can upload my version of the tutorial if you'd like.

**Comment by KoBeWi** [comment] 2023-04-30 00:33
Can't reproduce. Also your screenshot does not show the empty script.
Can you record a short video of the bug?

**Comment by mykael22000** [comment] 2023-04-30 00:44
I can add a recording later today.

If you look at the second screen shot, there is an extra script tag labelled [empty] and it's contents is the same as the Main script that was in focus when I pressed the '+' button.

This is with a first time Godot installation.

**Comment by KoBeWi** [comment] 2023-04-30 00:47
If you refer to the topmost [empty], it's a scene tab, not script. Scripts are listed in the list on the left.
By default Godot will automatically switch to the main script in the scene (`text_editor/behavior/files/open_dominant_script_on_scene_change` in Editor Settings), so if you change scene tabs, it will also change the current script.

**Comment by and-rad** [comment] 2023-04-30 04:56
Expanding on what @KoBeWi said, there is no new script created, just some confusion due to the editor layout. 

The tabs are scene tabs and they always show the name of the active scene. Since the new scene doesn't have a name yet, [empty] is what it's called for now. The list of scripts is shown in the sidebar of the script editor. `Main.gd` was the selected script before the new level was created and it's still the selected script after the new level was created.

There doesn't seem to be a bug here, so I think this can be closed.

**Comment by mykael22000** [comment] 2023-04-30 05:43
Well, this was my first time using Godot and I was following the tutorial and it wasn't clear at all what the problem was.  I'm pretty sure I was able to change the script displayed in the editor by clicking on the scene name above the script edit session.

Please wait for the video before you close it out. If I'm getting confused by it  I'm sure others are - and they my just gibe up on it rather than spend 10mins retyping the scripts from the tutorial.

**Comment by mykael22000** [comment] 2023-04-30 09:12
Well, after reviewing it while making the video after reading what you'd written above, it does seem to work the way you said.  But without knowing that, it seemed to work a very different (and broken) way.  At the least the tutorial needs to explain the way the script editor works when it introduces the user to it.

https://user-images.githubusercontent.com/6858095/235345197-63505fd2-c607-45f1-acf3-f864b72f799a.mp4

**Comment by KoBeWi** [comment] 2023-04-30 14:21
Issues about tutorials should be opened on the doc repository: https://github.com/godotengine/godot-docs

**Comment by adamscott** [comment] 2023-04-30 14:46
Closing as this is not an issue. Good luck with Godot, by the way! I hope you'll like it.

**Closed by adamscott** 2023-04-30 14:46 UTC
Labels: archived, discussion, topic:editor, usability
