### ISSUE TITLE
CPU usage spike for empty project.

### ISSUE THREAD

**Issue by qdwang** [godotengine/godot#38667] opened 2020-05-11 14:46 UTC
**Godot version:**
3.2.1 mono windows x64
**OS/device including version:**
windows 10 x64 build 18363
**Issue description:**
![cpu_spike](https://user-images.githubusercontent.com/403616/81574832-e1e01700-93d8-11ea-8935-4f52569be1cc.png)
FPS drop significantly at random frame.
**Steps to reproduce:**
Create an empty project, run it with the profiler and wait for less then 1 minute. You can also catch the issue by using MSI afterburner.
**Minimal reproduction project:**
It will happen in empty project.

**Comment by Calinou** [comment] 2020-05-11 15:07
Duplicate of #33969.

**Closed by Calinou** 2020-05-11 15:07 UTC
