### ISSUE TITLE
Code Completion hint stays open until I click

### ISSUE THREAD

**Issue by thecodethinker** [godotengine/godot#1674] opened 2015-04-12 04:40 UTC
When a code completion hint shows up it will stay up until I either click or get another hint which then stays on screen.

**Comment by reduz** [comment] 2015-04-12 22:50
moving cursor or pressing ESC will not close it?

**Comment by Ace-Dragon** [comment] 2015-04-13 00:47
Sometimes, you would want to tip to just go away when you continue typing because it blocks the view.

Better yet, just raise the Y value of the tooltip by several pixels so it becomes non-blocking for the line in question.

**Comment by kbdavidson** [comment] 2015-04-13 02:41
I agree it should be dismissed automatically (somehow) as you continue to type, especially after moving to the next line.

**Comment by reduz** [comment] 2015-04-18 23:37
i seriously don't see the problem, could you be more specific :)

**Comment by kbdavidson** [comment] 2015-04-19 01:14
Try this to reproduce:
1. Start a new script
2. In _init start a for loop
3. When the tool tip pops up showing the range() usage, it stays up even after completing the for line
4. Type a few more lines (without clicking the mouse)

The tool tip stays one line above the cursor covering up the previous line:

![image](https://cloud.githubusercontent.com/assets/4614207/7217732/d822e200-e60f-11e4-8de4-c9ba1886269b.png)

**Comment by akien-mga** [comment] 2015-11-22 17:15
I can't reproduce this issue in the current master branch, the tooltip is discarded as soon as the closing parenthesis is added in ```range(100)```. Assuming it has thus been fixed.

**Closed by akien-mga** 2015-11-22 17:15 UTC
Labels: enhancement, topic:editor, usability
