### ISSUE TITLE
Theme with many properties causes inspector to lag

### ISSUE THREAD

**Issue by NHodgesVFX** [godotengine/godot#23163] opened 2018-10-20 00:59 UTC
**Godot version:**
Godot Engine v3.1.alpha.calinou.c1779b1

**OS/device including version:**
Windows 10 64bit
GTX 980

**Issue description:**
When creating a new theme from the editor the node that the theme is directly attached to becomes extremely laggy. In addition trying to open and edit the them in the inspector also creates lag

**Steps to reproduce:**
Create a node2d and a control as a child. Add a new theme to the control. Open the theme editor and select new from current editor. notice there is now lag when selecting the control and editing the theme in the inspector 

**Minimal reproduction project:**
In the example notice that when selecting the control node that has the theme directly applied it lags. However, when selecting the children that inherit the theme there is no lag

[Quiz.zip](https://github.com/godotengine/godot/files/2497698/Quiz.zip)

**Comment by bojidar-bg** [comment] 2018-12-13 16:46
Can confirm with the sample project.

The problem is that the theme has too many items (all of them are enabled actually), and the inspector lags while it loads them.
Probably it can be solved by not creating all the Control nodes (or at least not adding them to the tree) until they are needed.

**Comment by AlexHolly** [comment] 2018-12-14 12:54
https://github.com/godotengine/godot/commit/ab9bbce3114d476bc00bf19aa5eaec6998f29514
x11

Selecting a Node in Scene Tree uses 100% CPU

1. Create a new Theme for a Control
2. Use "Create From Current Editor Theme"
3. Create a new Control and select between first and second Node.

**Comment by akien-mga** [comment] 2020-01-08 13:40
It seems fixed in the current `master` branch (ae216646). There's a ~1 second lag for me when populating the Inspector with all the theme items, but that's to be expected with so many items, and the editor is not laggy afterwards.

**Closed by akien-mga** 2020-01-08 13:40 UTC
Labels: bug, topic:editor
