### ISSUE TITLE
`Open C++ Source on GitHub` throws errors

### ISSUE THREAD

**Issue by zaevi** [godotengine/godot#54658] opened 2021-11-06 10:24 UTC
### Godot version

master, 3.4

### System information

Win10

### Issue description

The function `Open C++ Source on GitHub` on `Debugger->Errors` causes kinds of errors.

Run scene with code:
```gdscript
func _ready():
    add_child(null) #1 error (open page as expected)
    emit_signal("") #2 error
    add_child(self) #3 error
    var unused #4 warning
```
This will throw errors and then click `Open C++ Source on GitHub` they will:

`#1` direct as expected:
`https://github.com/godotengine/godot/blob/7538c052158071e68054b6e6e0d5a2e9df8ee4f2/scene/main/node.cpp#L1109` 

`#2` direct to:
```
https://github.com/godotengine/godot/blob/7538c052158071e68054b6e6e0d5a2e9df8ee4f2/Condition%20%22!signal_is_valid%20&&%20!script.is_null()%20&&%20!Ref%3CScript%3E(script)-%3Ehas_script_signal(p_name)%22%20is%20true.%20Returning#L0
```

`#3` throw internal error: `Incorrect C++ source stack trace file:line format (please report).`

`#4` same as `#3` but this is warning for script, so the function shouldn't be available here.

Stacktrace:
```
E 0:00:01:0226   _ready: Parameter "p_child" is null.
  <C++ Source>   scene\main\node.cpp:1109 @ Node::add_child()
  <Stack Trace>  Node2D.gd:4 @ _ready()
E 0:00:01:0231   _ready: Can't emit non-existing signal "".
  <C++ Error>    Condition "!signal_is_valid && !script.is_null() && !Ref<Script>(script)->has_script_signal(p_name)" is true. Returning: ERR_UNAVAILABLE
  <C++ Source>   core\object\object.cpp:1045 @ Object::emit_signal()
  <Stack Trace>  Node2D.gd:5 @ _ready()
E 0:00:01:0234   _ready: Can't add child 'Node2D' to itself.
  <C++ Error>    Condition "p_child == this" is true.
  <C++ Source>   scene\main\node.cpp:1110 @ Node::add_child()
  <Stack Trace>  Node2D.gd:6 @ _ready()
W 0:00:01:0222   The local variable 'unused' is declared but never used in the block. If this is intended, prefix it with an underscore: '_unused'
  <C++ Error>    UNUSED_VARIABLE
  <Source>       Node2D.gd:7
```

### Steps to reproduce

/

**Comment by akien-mga** [comment] 2021-11-06 10:48
It seems to use the wrong field in the error report, it should use `C++ Source`, and the option should not be shown if `C++ Source` is not present (e.g. for GDScript errors).

**Comment by Altoc** [comment] 2022-04-03 10:14
Received this error today. Attempted to view C++ source in godot editor (v. 3.4 stable windows) for the following error related to tilemaps:

```
E 0:00:08.418   body_set_shape_as_one_way_collision: Can't change this state while flushing queries. Use call_deferred() or set_deferred() to change monitoring state instead.
  <C++ Error>   Condition "body->get_space() && flushing_queries" is true.
  <C++ Source>  servers/physics_2d/physics_2d_server_sw.cpp:660 @ body_set_shape_as_one_way_collision()
  <Stack Trace> Main.gd:19 @ createScene()
                ObjDistressed.gd:30 @ _on_ObjDistressed_body_entered()
```

**Comment by akien-mga** [comment] 2023-01-08 21:52
Duplicate of #66974

**Closed by akien-mga** 2023-01-08 21:52 UTC
Labels: bug, topic:editor, confirmed
