### ISSUE TITLE
Crash when changing string parameter to `get_node` in GDScript editor

### ISSUE THREAD

**Issue by Torguen** [godotengine/godot#96552] opened 2024-09-04 07:49 UTC
### Tested versions

v4.4.dev1.official [28a72fa43]

### System information

w10 64

### Issue description

As you can see in this video, when I enter the letter "L" to change a string containing a node name, it immediately crashes.

https://github.com/user-attachments/assets/a04e089e-faf1-456e-b71b-bfe4f9634ca5

![Captura](https://github.com/user-attachments/assets/3433d160-a359-466d-bef7-3dfe4e3dc21e)

### Steps to reproduce

See the video

### Minimal reproduction project (MRP)

I could send the project privately.
This is a work project.

**Comment by akien-mga** [comment] 2024-09-04 07:52
I suspect an issue with GDScript code completion, CC @HolonProduction.

**Comment by arkology** [comment] 2024-09-04 08:34
I get the same behavior not only with `get_node`, also when changing/typing string as argument in function call, chash with the same error log.

**Comment by arkology** [comment] 2024-09-04 14:12
> Maybe a duplicate of #96442

Perhaps, but this one, I suppose, applies only to strings as argument to a function.

**Comment by HolonProduction** [comment] 2024-09-04 15:25
Probably a duplicate of #96239, should happen with all literals (strings, numbers, true, false, ...) and should only happen on calls which are in some way dependent on loading another script (`get_parent` probably has a script attached?).

#96243 should fix this, can't verify it though since there is no MRP.

**Comment by AThousandShips** [comment] 2024-09-04 15:27
Closing as solved, if this still occurs when dev2 is released (or if an MRP is provided and it still occurs) this can be reopened

**Closed by AThousandShips** 2024-09-04 15:27 UTC
Labels: bug, topic:gdscript, topic:editor, crash, regression

**Comment by Torguen** [comment] 2024-09-05 15:25
> Probably a duplicate of #96239, should happen with all literals (strings, numbers, true, false, ...) and should only happen on calls which are in some way dependent on loading another script (`get_parent` probably has a script attached?).
> 
> #96243 should fix this, can't verify it though since there is no MRP.

The assumption is correct, I have this problem again with an integer and that call is to another script.
