### ISSUE TITLE
Preload fails in exported project

### ISSUE THREAD

**Issue by DoctorAlpaca** [godotengine/godot#16008] opened 2018-01-23 20:30 UTC
**Godot version:**
Godot 3.0rc2

**OS/device including version:**
Arch Linux rolling release

**Issue description:**
Preloading a GDScript file from another one produces an error in exported projects (but works fine when ran from the editor). Using load instead of preload works. Tested only on 64 bit Linux, but running the Windows version using wine gives the same error.

```
./test.x86_64
No touch devices found
OpenGL ES 3.0 Renderer: GeForce GTX 970/PCIe/SSE2
GLES3: max ubo light: 409
GLES3: max ubo reflections: 455, ubo size: 144
ARVR: Registered interface: Native mobile
SCRIPT ERROR: GDScript::load_byte_code: Parse Error: Can't preload resource at path: res://b.gd
   At: res://a.gdc:4.
ERROR: load_byte_code: Method/Function Failed, returning: ERR_PARSE_ERROR
   At: modules/gdscript/gdscript.cpp:764.
ERROR: load: Condition ' err != OK ' is true. returned: RES()
   At: modules/gdscript/gdscript.cpp:1848.
ERROR: _load: Failed loading resource: res://a.gdc
   At: core/io/resource_loader.cpp:186.
ERROR: poll: res://scene.tscn:3 - Parse Error: [ext_resource] referenced nonexistent resource at: res://a.gd
   At: scene/resources/scene_format_text.cpp:439.
ERROR: load: Condition ' err != OK ' is true. returned: RES()
   At: core/io/resource_loader.cpp:149.
ERROR: _load: Failed loading resource: res://scene.tscn
   At: core/io/resource_loader.cpp:186.
ERROR: start: Failed loading scene: res://scene.tscn
   At: main/main.cpp:1613.
WARNING: cleanup: ObjectDB Instances still exist!
   At: core/object.cpp:1989.
ERROR: clear: Resources Still in use at Exit!
   At: core/resource.cpp:418.
```

**Minimal reproduction project:**
[preload_example.zip](https://github.com/godotengine/godot/files/1657500/preload_example.zip)

**Comment by vnen** [comment] 2018-01-23 20:54
I can't reproduce on Windows 10.

**Comment by akien-mga** [comment] 2018-01-23 21:02
Duplicate of #15902, fixed in upcoming RC3.

**Closed by akien-mga** 2018-01-23 21:02 UTC
