### ISSUE TITLE
Upgrade Mesh Surface tool creates flickering black triangles on mesh

### ISSUE THREAD

**Issue by yosimba2000** [godotengine/godot#86638] opened 2023-12-30 12:37 UTC
### Tested versions

Issue occurs in Godot 4.2.1 and 4.3 dev1, both .Net version
Issue does not occur in Godot 4.1 .Net version

### System information

Win10 22H2, Godot 4.2.1 .Net, RTX 3070

### Issue description

When upgrading mesh using Upgrade Mesh Surface tool or importing mesh in Godot 4.2 and onwards, some meshes get black triangles that flicker when moving the camera. The flicker looks like Z-fighting to me.

When mesh is viewed in Godot 4.1 .Net, the black triangles do not appear.

### Steps to reproduce

.GLB file: https://filebin.net/dtarvnlizuworxx8
1) Create project using Godot 4.1 .Net
2) Import and instantiate piece.glb in the 3D game world. You may need to zoom out to see the mesh.
3) The mesh does not have black triangles.
4) Save the project, then open the project using Godot 4.2.
5) From Tools menu, select Upgrade Mesh Surfaces.
6) The mesh now has flickering black triangles.

### Minimal reproduction project (MRP)

![image](https://github.com/godotengine/godot/assets/61702289/4fc4e60d-1c01-4c6f-9800-9ff8c8d85e97)
![image](https://github.com/godotengine/godot/assets/61702289/676bf704-a889-400f-8013-4c7cea0f0b8b)

**Comment by yosimba2000** [comment] 2023-12-30 12:46
i think it's related to https://github.com/godotengine/godot/issues/85406
I disabled mesh compression in import settings as described here:
https://github.com/godotengine/godot/issues/85406#issuecomment-1828357136

**Comment by clayjohn** [comment] 2024-01-06 02:14
Indeed, this is a duplicate of https://github.com/godotengine/godot/issues/85406

**Closed by clayjohn** 2024-01-06 02:14 UTC
