### ISSUE TITLE
Internal Script Error! - opcode #38 (report please)

### ISSUE THREAD

**Issue by hilfazer** [godotengine/godot#24786] opened 2019-01-05 12:57 UTC
**Godot version:**

Godot 3.1 alpha3, alpha4, alpha5

**OS/device including version:**

Windows 7 Pro SP1

**Issue description:**

"Internal Script Error! - opcode #38 (report please)" when trying to instantiate an Object derived from Reference.

**Steps to reproduce:**
1. Run the project
2. Click "New & Create" button

error should be reported in DevButtons.gd, line 63
"var creationData = GameCreatorGd.UnitCreationData.new()"

I've got same line in CharacterCreation.gd and no error there.

**Minimal reproduction project:**

It's not a minimal project as i don't know how to reproduce it
https://github.com/hilfazer/Projects/tree/InternalScriptErrorOpcode38/Godot/DungeonCrawler

**Comment by hilfazer** [comment] 2019-01-05 13:04
Moving "var creationData" from function body to class members gets rid of this error.

**Comment by vnen** [comment] 2019-01-14 12:42
This is a duplicate of #5843. The issue is that the reference goes out of scope and is de-allocated, so GDScript can't find it when it's time to use it.

The workaround is to split in two variables so you don't lose the reference to the base:

```gdscript
var gameCreator = GameCreatorGd
var creationData = gameCreator.UnitCreationData.new()
```

**Closed by vnen** 2019-01-14 12:42 UTC
Labels: bug, topic:gdscript
