### ISSUE TITLE
When adding points in curve editor, they don't appear in the specified y range

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#41083] opened 2020-08-06 17:32 UTC
**Godot version:**

3.2.3 rc3

**Issue description:**

I have a Line2D. I tried to make a curve with high width values. I added a point, but it's nowhere to be seen:
![image](https://user-images.githubusercontent.com/2223172/89563157-516c7380-d81b-11ea-8833-351c299e8d04.png)
I can't scroll nor zoom the curve editor, so it's basically unusable. You can only do something with small values.

EDIT:
Ok, the workaround is to decrease the min value, move the point higher and increase min again.

EDIT2:
Every new point is created below the min value :I

EDIT3:
See comments for more details.

**Comment by Zylann** [comment] 2020-08-07 09:39
This used to be a bottom panel editor, but got moved in the inspector when it was revamped in the past, which limits it a lot. I think @WiggleWizard is working on an improvement for precision work on such curves.

**Comment by WiggleWizard** [comment] 2020-08-07 16:20
Zylann's correct; I am currently working on an improved curve editor. If you have requests could you put them in the proposal please?

**Comment by KoBeWi** [comment] 2020-08-07 16:21
I don't have requests, this is a bug (unless fixing it counts as a request xd).
Also #41084

**Comment by Zylann** [comment] 2020-08-07 17:36
AFAIK "can't be zoomed [vertically]" isn't a bug, it's just not supported by the way the editor currently displays it. Solving zoom specifically would need a vertical resizer in the inspector, although due to other concerns found in the proposal a broader solution might be picked.

**Comment by KoBeWi** [comment] 2020-08-07 17:42
Well, I included a screenshot. Line2D has a width curve property which I edited. You can set min and max y value for curve's points, but this makes the editor _unusable_ if they are bigger than the 0-1 default. If I can't edit the curve properly then it's definitely a bug.

**Comment by Zylann** [comment] 2020-08-07 17:44
> the actual bug I guess, is that you added a point to the curve but the editor did not take the view region into account to position it. New points should appear where you clicked.

**Comment by KoBeWi** [comment] 2020-08-07 17:46
Nice edit xd
I'll update the title.

**Comment by FeralBytes** [comment] 2021-01-21 06:11
I am sorry, but I have to agree, this is a bug and it is broken. Yes there is a workaround. But really I wasted a significant amount of time thinking it was completely broken. So on preparing to report a bug I found this one. The editor putting every point at 0 on the line when you add a point is not useful, when we already established that the minimum number is higher than 0.

**Comment by anvilfolk** [comment] 2022-10-26 02:42
Still confirmed in 3.5.1, but fixed in #67857 :)

**Closed** 2023-05-29 08:32 UTC
Labels: bug, topic:editor, confirmed, usability
