### ISSUE TITLE
You can't move child nodes of a viewport.

### ISSUE THREAD

**Issue by 0nepixel** [godotengine/godot#17739] opened 2018-03-24 14:09 UTC
Godot 2.0/2.1/3.0.
I don't know why but you can't move the child nodes of a viewport (2D) in the editor, you have to take the node out and change the position, then put it back in the viewport, it's anoying and impractical :/.

**Comment by asheraryam** [comment] 2018-11-29 07:46
I'd like to address this but first would need to know, is this desirable behaviour?

**Comment by bojidar-bg** [comment] 2019-07-17 20:01
Closing as duplicate of #20619, as the later has a bit more discussion and details.

**Closed by bojidar-bg** 2019-07-17 20:01 UTC
Labels: discussion, enhancement, topic:editor, usability
