### ISSUE TITLE
Godot default android export template includes permission requests that were not requested

### ISSUE THREAD

**Issue by hasherkeen** [godotengine/godot#19168] opened 2018-05-25 21:14 UTC
**Godot version:**
2.1.4 - 2,1.5

**OS/device including version:**
Android

**Issue description:**
Godot default android export template includes permission requests that were not requested.

A week back my apps were removed from Google Play for requesting sensitive permissions and for not including a Privacy Policy file. After talking to the support staff i was told that my games requested the following permissions:

android.permission.READ_PHONE_STATE 
android.permission.RECORD_AUDIO
android.permission.GET_ACCOUNTS
android.permission.READ_CONTACTS
android.permission.CAMERA

Which i've never toggled during the export process.

And, i believe, purging everything between line 37 to line 202 off the AndroidManifest.xml.template is not enough, as there are still sensitive permissions being requested in the background.

After opening a compiled export template APK in Android Studio and doing a a global tree search, by hitting ctrl+shift+f and entering 'android.permission', there is, oddly, a fair amount of sensitive permissions being requested.

Here's a list of some of those i've found:

**FILE NAME: FingerprintManagerCompat.smali**
value = "android.permission.USE_FINGERPRINT"

**FILE NAME: zzaqo.smali**
const-string v2, "android.permission.ACCESS_COARSE_LOCATION"
const-string v2, "android.permission.ACCESS_FINE_LOCATION"

**FILE NAME: zzaiw.smali**
const-string v2, "android.permission.RECORD_AUDIO"
const-string v2, "android.permission.CAMERA"

**FILE NAME: zzmw.smali**
const-string v1, "android.permission.WRITE_EXTERNAL_STORAGE"

**FILE NAME: WorkSourceUtil.smali**
const-string v2, "android.permission.UPDATE_DEVICE_STATS"

These appear to be generated during the compilation process for no apparent reason.

**Comment by eon-s** [comment] 2018-05-25 21:18
Read here for instructions on how to fix the problems with placeholder permissions https://godotengine.org/article/fixing-godot-games-published-google-play

**Comment by hasherkeen** [comment] 2018-05-25 21:27
The problem of sensitive permissions being unwanted-ly requested continues even after doing that.

**Comment by akien-mga** [comment] 2018-05-25 21:34
That's a duplicate of #18192.

> Here's a list of some of those i've found:
>
> FILE NAME: FingerprintManagerCompat.smali
> value = "android.permission.USE_FINGERPRINT"
> 
> FILE NAME: zzaqo.smali
> const-string v2, "android.permission.ACCESS_COARSE_LOCATION"
> const-string v2, "android.permission.ACCESS_FINE_LOCATION"

I don't know what those are but they're not defined by Godot. (You can grep for those permission names, you'll only find references to the placeholders and the logic that can replace them when asked for by actual permissions).
When you upload a game to Google Play, or try to install it on a device, it doesn't ask for any of the permissions you listed above unless you explicitly requested them.

**Comment by hasherkeen** [comment] 2018-05-25 21:40
Understood, but i'd still like to know why these things are there, because they are.

If you: 
-> open a compiled export template APK in Android Studio
-> do a a global tree search, by hitting ctrl+shift+f
-> enter android.permission in the search box

You will come across them too.

**Comment by kubecz3k** [comment] 2018-06-03 11:35
Closing as duplicate of https://github.com/godotengine/godot/issues/18192

**Closed by kubecz3k** 2018-06-03 11:35 UTC
