### ISSUE TITLE
Command line window appears when running on Windows 10 (again)

### ISSUE THREAD

**Issue by lnktree** [godotengine/godot#30092] opened 2019-06-26 15:31 UTC
Open the Godot 3.1.1 in Windows 10, a command line window will appear and will not disappear until you close Godot. It's weird working in your projects with a minimized command line window.

**Comment by akien-mga** [comment] 2019-06-26 15:59
Why "again"? This has always been Godot's behavior, and this is on purpose, as the console provides important information for developers and users alike whenever there is an error or a crash.

In 3.2, you will however have an option to hide it if you wish so (as per #24448).
Duplicate of #17889

**Closed by akien-mga** 2019-06-26 15:59 UTC

**Comment by lnktree** [comment] 2019-06-26 16:08
It was said that this has been fixed previously..

I think the window should be hidden by default, and this option activates the window instead. A developer wants to work in the project and not see a command line every time the project is opened, one of the proposals of the engine is to be easy to use and not to confuse the user with a black screen. It’s just not elegant.

**Comment by BenMcLean** [comment] 2019-07-29 22:29
It should be off by default, with an option to turn it on yeah. Hopefully fixed in 3.2
