### ISSUE TITLE
Moving KinematicBody2D can recieve physics events

### ISSUE THREAD

**Issue by Allexit** [godotengine/godot#3719] opened 2016-02-15 19:54 UTC
I have a platform and a player, both are KinematicBody2D's. The player is constantly pushed towards the ground (gravity) with `KinematicBody2D.move`. When the player stands onto the platform which is patrolling between two points, it starts to slowly "push" down with the player. 
This does not occour with platforms that are completely still.

To my understanding this shouldn't happen, referring to the documentations at [http://docs.godotengine.org/](http://docs.godotengine.org/en/latest/tutorials/2d/physics_introduction.html#kinematicbody2d)

> "They are not affected by the physics at all (to other types of bodies, such a character or a rigidbody, these are the same as a staticbody) --"

There is a workaround for this, and it is to check weather the player could actually move towards the ground with `KinematicBody2D.test_move` and, not move it unless it could move. This is in some cases preferable, but it should be fixed nevertheless.

**Comment by Allexit** [comment] 2016-02-15 21:34
Additional note; I have (like the example platforming thing in the docs), made it so that the motion of the player is slided with the collision normal, but as physics normally work, it still "twitches" invisibly between outside and inside of the object it's colliding to. So when it goes inside the moving platform, it pushes it out of it's way. I'm not sure if this is intentional or not, but since it doesn't work on **immovable** Kinematic2DBodies, I persume it is not.

**Comment by eska014** [comment] 2016-02-15 22:01
Sounds like a duplicate of #1472

**Comment by Allexit** [comment] 2016-02-16 08:10
it is very likely to be caused from the same bug; More reasons to fix it

**Comment by eska014** [comment] 2016-02-16 14:55
Closing as duplicate of #1472

**Closed by eska014** 2016-02-16 14:55 UTC
Labels: bug, topic:core

**Comment by reduz** [comment] 2016-02-16 15:01
This is not a bug, just don't  move the platform with move() if you don' t
want collisions to affect it. Set the transform normally from code or
animate it with an AnimationPlayer
