### ISSUE TITLE
Rigidbody2D objects appear with wrong coords

### ISSUE THREAD

**Issue by scrappedgear** [godotengine/godot#7301] opened 2016-12-14 14:20 UTC
**Issue description**:
I've been experiencing this issue since Godot 2.1. Rigidbody2D objects sometimes just spawn in a distance of their actual coords. Also I've noticed that the distance depends on physics_fps value. With high physics fps the distance between a Rigidbody2D appearing on a scene and it's actual coords is larger.

**Steps to reproduce:**
I tried to reproduce it myself, but the bug appears rarely. I've usually spotted it only with physics_fps value set to 200 and Rigidbody2Ds' gravity scale set to 10.

**Godot version:** Linux x86_64, Godot 2.1.1 stable

**Comment by bojidar-bg** [comment] 2016-12-14 14:21
Does enabling "Continuous Collision Detection" help? (even if it is a bit buggy with the bounce)

**Comment by scrappedgear** [comment] 2016-12-14 14:26
@bojidar-bg I've played with that option for a while, but the bug didn't disappear.

**Comment by Noshyaar** [comment] 2018-04-10 15:50
First of all thank you for your report and sorry for the delay.

We released Godot 3.0 in January 2018 after 18 months of work, fixing many old issues either directly, or by obsoleting/replacing the features they were referring to.

We still have hundreds of issues whose relevance/reproducibility needs to be checked against the [current stable version](https://godotengine.org/download), and that's where you can help us.
**Could you check if the issue that you described initially is still relevant/reproducible in Godot 3.0 or any newer version, and comment about it here?**

For bug reports, please also make sure that the issue contains detailed steps to reproduce the bug and, if possible, a zipped project that can be used to reproduce it right away. This greatly speeds up debugging and bugfixing tasks for our contributors.

Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

Thanks in advance.

*Note: This message is being copy-pasted to many "stale" issues (90+ days without activity). It might happen that it is not meaningful for this specific issue or appears oblivious of the issue's context, if so please comment to notify the Bugsquad about it.*

**Comment by akien-mga** [comment] 2019-04-15 14:14
> Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

As there was no update since the previous post, we close this issue.

If it is still relevant in the way it was described and discussed above, please comment to ask for it to be reevaluated. If it is only partly relevant, or if the original issue has changed, it would be better to open a new issue (potentially referring to this one) focused on the current state.

**Closed by akien-mga** 2019-04-15 14:14 UTC
Labels: bug, topic:physics
