### ISSUE TITLE
Unchecking Script Editor in Manage Editor Features disables external editor integration.

### ISSUE THREAD

**Issue by BrunoDSL** [godotengine/godot#65235] opened 2022-09-02 07:50 UTC
### Godot version

v3.5.stable.official [991bb6ac7]

### System information

Windows 10 21H2 x64

### Issue description

As per title description, unchecking `Script Editor` from `Manage Editor Features` completely kills any external editor integration on both regular and Mono version of Godot, despite the option stating the feature only applies to the built-in script editor. Once you do that, external editors don't open when you load projects and clicking the script icons in the UI do nothing.

### Steps to reproduce

1 - Set up an external editor in the options
2 - Disable `Script Editor` in `Manage Editor Features`
3 - Attempt to use the external editor or open it through Godot.

### Minimal reproduction project

Non applicable (engine related).

**Comment by Calinou** [comment] 2022-09-02 15:52
Duplicate of https://github.com/godotengine/godot/issues/59758.

**Closed by Calinou** 2022-09-02 15:52 UTC
