### ISSUE TITLE
Post processing Volume like Unreal Engine

### ISSUE THREAD

**Issue by ghost** [godotengine/godot#21048] opened 2018-08-15 16:09 UTC
It's Good thing to have a Post processing volume like Unreal Engine

**Comment by aaronfranke** [comment] 2018-08-15 18:26
Can you please be more descriptive? Explain as if we've never used Unreal before.

**Comment by CCODE05B** [comment] 2018-08-15 18:44
@aaronfranke it's a Box volume contain Post process Parameters , when the Camera ( Any camera ) enter that Volume ( Enter inside the box ) it Change the main Post process parameters in the Scene based on the ones in that Volume
Here is a simple Video Explain it better 

https://youtu.be/i9bnPStLYfk?t=92

**Comment by evandropoa** [comment] 2018-09-29 05:29
Hi, if you need this feature maybe you could emulate it in code with an area collider and modifing the worldenviroment or the camera enviroment on enter and exit of the area collider signals.

**Comment by CCODE05B** [comment] 2018-09-29 11:28
@evandropoa i can do that in game , the problem is i don't know how to do it in Editor , and the second thing is it will be awesome if it implemented officially in the Engine because if i did it , maybe no one or few people will see it

**Comment by reduz** [comment] 2018-09-29 12:01
This is one of the reasons why I wanted to split WorldEnvironment into effects and post processing eventually, so you can animate or switch between post processes and leave other parameters such as SSR/SSAO/etc alone.

**Comment by evandropoa** [comment] 2018-09-29 18:39
Yep, independent post processing it´s the right thing to do, it will open many other possibilities for effects in code and plugins.

**Comment by akien-mga** [comment] 2020-01-08 08:35
Feature proposals should now be filed under https://github.com/godotengine/godot-proposals with details about the use case. Closing this, but if anyone wants this feature and it's not tracked yet on godot-proposals, feel free to open one there.

**Closed by akien-mga** 2020-01-08 08:35 UTC
Labels: feature proposal, topic:rendering
