### ISSUE TITLE
Signal map is not thread save

### ISSUE THREAD

**Issue by fian46** [godotengine/godot#35648] opened 2020-01-28 05:41 UTC
**Godot version:** rc4

**OS/device including version:**  android 9, Linux mint

**Issue description:** when you creating and destroying **scene that has signal on it** from different thread the signal slot_map is throw tons of error because of some signal maybe not exist. i assuming the signal map is not thread save. i am not really understand about Godot core engine but i think this is true because after moving my code to the same thread this problem disappear. sorry if my English is bad or any of my word is wrong .

this is the log from test
```
Godot Engine v3.2.rc4.official - https://godotengine.org
OpenGL ES 3.0 Renderer: AMD KABINI (DRM 2.50.0, 5.3.0-26-generic, LLVM 9.0.0)

**ERROR**: Disconnecting nonexistent signal 'changed', slot: 243201:_shape_changed.
   At: core/object.cpp:1522:_disconnect() - Condition "!s->slot_map.has(target)" is true.
**ERROR**: Disconnecting nonexistent signal 'changed', slot: 243201:_shape_changed.
   At: core/object.cpp:1522:_disconnect() - Condition "!s->slot_map.has(target)" is true.
**ERROR**: Disconnecting nonexistent signal 'changed', slot: 243201:_shape_changed.
   At: core/object.cpp:1522:_disconnect() - Condition "!s->slot_map.has(target)" is true.
**ERROR**: Disconnecting nonexistent signal 'changed', slot: 243201:_shape_changed.
   At: core/object.cpp:1522:_disconnect() - Condition "!s->slot_map.has(target)" is true.
**ERROR**: Disconnecting nonexistent signal 'changed', slot: 243201:_shape_changed.
   At: core/object.cpp:1522:_disconnect() - Condition "!s->slot_map.has(target)" is true.
**ERROR**: Disconnecting nonexistent signal 'changed', slot: 243201:_shape_changed.
   At: core/object.cpp:1522:_disconnect() - Condition "!s->slot_map.has(target)" is true.
**ERROR**: Disconnecting nonexistent signal 'changed', slot: 243201:_shape_changed.
   At: core/object.cpp:1522:_disconnect() - Condition "!s->slot_map.has(target)" is true.
**ERROR**: Disconnecting nonexistent signal 'changed', slot: 243201:_shape_changed.
   At: core/object.cpp:1522:_disconnect() - Condition "!s->slot_map.has(target)" is true.
**ERROR**: Disconnecting nonexistent signal 'changed', slot: 243201:_shape_changed.
   At: core/object.cpp:1522:_disconnect() - Condition "!s->slot_map.has(target)" is true.
**ERROR**: Disconnecting nonexistent signal 'changed', slot: 243201:_shape_changed.
   At: core/object.cpp:1522:_disconnect() - Condition "!s->slot_map.has(target)" is true.
**ERROR**: Disconnecting nonexistent signal 'changed', slot: 243201:_shape_changed.
   At: core/object.cpp:1522:_disconnect() - Condition "!s->slot_map.has(target)" is true.
**ERROR**: Disconnecting nonexistent signal 'changed', slot: 243201:_shape_changed.
   At: core/object.cpp:1522:_disconnect() - Condition "!s->slot_map.has(target)" is true.
**ERROR**: Disconnecting nonexistent signal 'changed', slot: 243201:_shape_changed.
   At: core/object.cpp:1522:_disconnect() - Condition "!s->slot_map.has(target)" is true.
**ERROR**: Disconnecting nonexistent signal 'changed', slot: 243201:_shape_changed.
   At: core/object.cpp:1522:_disconnect() - Condition "!s->slot_map.has(target)" is true.
**ERROR**: Disconnecting nonexistent signal 'changed', slot: 243201:_shape_changed.
   At: core/object.cpp:1522:_disconnect() - Condition "!s->slot_map.has(target)" is true.
**ERROR**: Disconnecting nonexistent signal 'changed', slot: 243201:_shape_changed.
   At: core/object.cpp:1522:_disconnect() - Condition "!s->slot_map.has(target)" is true.
**ERROR**: Disconnecting nonexistent signal 'changed', slot: 243201:_shape_changed.
   At: core/object.cpp:1522:_disconnect() - Condition "!s->slot_map.has(target)" is true.
**ERROR**: Disconnecting nonexistent signal 'changed', slot: 243201:_shape_changed.
   At: core/object.cpp:1522:_disconnect() - Condition "!s->slot_map.has(target)" is true.
**ERROR**: Disconnecting nonexistent signal 'changed', slot: 243201:_shape_changed.
   At: core/object.cpp:1522:_disconnect() - Condition "!s->slot_map.has(target)" is true.
**ERROR**: Disconnecting nonexistent signal 'changed', slot: 243201:_shape_changed.
   At: core/object.cpp:1522:_disconnect() - Condition "!s->slot_map.has(target)" is true.
**ERROR**: Disconnecting nonexistent signal 'changed', slot: 243201:_shape_changed.
   At: core/object.cpp:1522:_disconnect() - Condition "!s->slot_map.has(target)" is true.
**ERROR**: Disconnecting nonexistent signal 'changed', slot: 243201:_shape_changed.
   At: core/object.cpp:1522:_disconnect() - Condition "!s->slot_map.has(target)" is true.
**ERROR**: Disconnecting nonexistent signal 'changed', slot: 243201:_shape_changed.
   At: core/object.cpp:1522:_disconnect() - Condition "!s->slot_map.has(target)" is true.
**ERROR**: Disconnecting nonexistent signal 'changed', slot: 243201:_shape_changed.
   At: core/object.cpp:1522:_disconnect() - Condition "!s->slot_map.has(target)" is true.
```
this thing repeated until the game freezes

**Steps to reproduce:** try to instance and free many scene from thread and sometimes it break

**Minimal reproduction project:** i thing it is really simple to reproduce

**Comment by Calinou** [comment] 2020-01-28 16:09
Duplicate of #34752.

**Closed by Calinou** 2020-01-28 16:09 UTC
