### ISSUE TITLE
ViewportTexture doesn't work in VisualShader

### ISSUE THREAD

**Issue by ilyabelow** [godotengine/godot#84609] opened 2023-11-08 09:41 UTC
### Godot version

4.1.3

### System information

Godot v4.1.3.stable - Manjaro Linux #1 SMP PREEMPT_DYNAMIC Wed Oct 25 13:06:34 UTC 2023 - X11 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3060 Laptop GPU () - 12th Gen Intel(R) Core(TM) i5-12500H (16 Threads)

### Issue description

When I try adding new ViewportTexture to a Texture2D node in visual shader editor, I get this message:

```
Can't create a ViewportTexture on this resource because it's not set as local to scene.
Please switch on the 'local to scene' property on it (and all resources containing it up to a node).
```

When I first found this problem, the shader was attached to a MeshInstance3D, which was set (along with all resources in the hierarchy) as "local to scene". Ordinary shaders, with ViewportTexture as a shader parameter, works as expected with the same setup. And if you create VisualShader just as a resource without attaching it to a mesh and checking "Local to Scene" checkbox, the result is the same message

Googling only gave [this](https://ask.godotengine.org/59479/how-do-you-use-viewporttexture-in-visual-shader) somewhat old report, so it seems that this is an old bug

P. S. Just in case I've tried this on master branch (3e7f638d7b, 08.11.23, same issue)

### Steps to reproduce

1. Create new VisualShader resource
2. Check "Local to Scene" (makes no difference)
3. Add "Texture2D" node to the shader
4. Choose "Texture" type and in source choose "New ViewportTexture"

### Minimal reproduction project

Minimal project contains only new_shader.tres with one node

[visualshader_issue.zip](https://github.com/godotengine/godot/files/13294843/visualshader_issue.zip)

**Comment by clayjohn** [comment] 2023-11-08 11:25
The MRP isn't enough to reproduce the reported issue. 

In your scene have you ensured that you checked local to scene on all resources containing the VisualShader? That means it needs to be checked on the VisualShader, the ShaderMaterial, and the Mesh. It is not enough to just check it on the VisualShader

**Comment by ilyabelow** [comment] 2023-11-08 12:07
> The MRP isn't enough to reproduce the reported issue.

What do you mean? It cannot be reproduced or the use case in MRP is invalid? If latter, than I guess the error message should be clearer I guess... and if the former, that's weird

> In your scene have you ensured that you checked local to scene on all resources containing the VisualShader? That means it needs to be checked on the VisualShader, the ShaderMaterial, and the Mesh. It is not enough to just check it on the VisualShader

Yes, everything is local to scene. As I've said, if you replace VisualShader with just Shader and set ViewportTexture as a shader parameter (with ```uniform sampler2D test;``` in shader file) it works as expected. The issue begins as soon as you try setting a ViewportTexture as a source in Texture node in VisualShader

**Comment by jsjtxietian** [comment] 2023-11-09 02:46
I can confirm this issue. I believe the problem is that this visual shader is set as local_to_scene, but the texture node itself is not.

**Comment by timothyqiu** [comment] 2023-11-09 04:27
I can confirm this too. A `VisualShaderNodeTexture` is itself a Resource inside the VisualShader. But there's no way to turn on local to scene for it.

**Comment by jsjtxietian** [comment] 2023-11-09 06:23
I think there might be two solutions for this:

1. Hack the warning check to exclude this scenario, not recommended of course, but solves the problem
2. Try to make all nodes marked as local_to_scene when the visual shader itself is marked as local_to_scene, it makes sense this way, but it might need more work as there seems no easy way of just doing this.

**Comment by ilyabelow** [comment] 2023-11-09 08:53
I was thinking about trying to fix this problem myself as my first issue, on that note - why exactly it is required for a ViewportTexture resource to have local to scene parents? Theoretically it could be a valid use case to use the same render target as a texture in multiple mesh instances, so the limitation is technical

**Comment by ilyabelow** [comment] 2023-12-03 17:18
Okay, I did some digging and realized that just setting all visual shader nodes as local to scene will not solve the problem. It is not supported at all to make a ViewportTexture in a material that is saved to a file (as an error in `EditorPropertyResource::_resource_changed` suggests), so we need a special error message that prohibits adding ViewportTexture to a Texture2D node AND that tells to use Texture2DParameter instead

Also, I've tried using Texture2DParameter node with ViewportTextures - it works, but it's glitchy (but it's a story for another time)

**Comment by YuriSizov** [comment] 2023-12-08 16:20
Should we consider this issue closed now?

**Closed** 2023-12-08 16:42 UTC
Labels: bug, topic:editor, topic:shaders
