### ISSUE TITLE
Autocompletion for the extends type

### ISSUE THREAD

**Issue by Jummit** [godotengine/godot#36607] opened 2020-02-27 18:17 UTC
**Godot version:**

ed0f1940cbdbe470da85f446f315ee12897038a1

**Issue description:**

There is no autocompletion for the extends type.

**Steps to reproduce:**

Create a blank script and type "extends " and hit ctrl+space.

**Comment by Calinou** [comment] 2020-02-27 20:51
Duplicate of #36431.

**Closed by Calinou** 2020-02-27 20:51 UTC
Labels: enhancement, junior job, topic:editor, topic:gdscript
