### ISSUE TITLE
UndoRedo's "redo" actions do not execute

### ISSUE THREAD

**Issue by willnationsdev** [godotengine/godot#15451] opened 2018-01-07 17:17 UTC
**Godot version:**
Godot 3.0 8e82404

**Issue description:**
While writing a plugin, I attempted to implement actions for `UndoRedo`. While the actions would DO properly and UNDO properly, attempting to REDO the actions would do nothing at all.

**Steps to reproduce:**
Create a plugin with some `add_do_method` and `add_undo_method` calls. Then execute the action, undo it with Ctrl+Z and attempt to redo the action with Ctrl+Shift+Z. I have been seeing no results when I should be.

**Sample project:**
[UndoRedoTest.zip](https://github.com/godotengine/godot/files/1609986/UndoRedoTest.zip)

Open the Project. There is a dock added to the left. Default button text is "Click me!". Do actions set it to "TESTING", and undo actions to "UNDO TESTING". You'll notice that "redo-ing" from the EditorShortcut of Ctrl+Shift+Z does not switch it from "UNDO TESTING" to "TESTING".

**Comment by capnm** [comment] 2018-01-07 20:38
Is the short-cut perhaps interacting with your text-editor?
If I open e.g. the 2D view, then it seems to work here as intended.
(linux, 37ca542d2bfd9aac296e82e30a76117090dea08e)

**Comment by willnationsdev** [comment] 2018-01-07 20:41
Nope, I've been doing this from the 2D view as well. I'm on Windows 10, but idk if that's having an impact here.

**Comment by Hinsbart** [comment] 2018-01-10 18:07
I can't reproduce this either (c037f6339f1, linux).
Redo works fine here in all Editor views.

**Comment by brainsick** [comment] 2018-01-12 21:46
So, here's a thought.  I was messing around with UndoRedo testing, largely inspired by this issue.  I've opened a couple PRs based on that thus far.  I found #15506 rather interesting because it smells like this issue (my undo broke, your redo is broken).

If we do a (admittedly _crude_) analysis of the code base.

```
todd@todd-ab28d3:~/repos/remote/brainsick-godot$ find . \( -name '*.cpp' -o -name '*.h' \) -print0 | xargs -0 egrep create_action | wc -l
304
todd@todd-ab28d3:~/repos/remote/brainsick-godot$ find . \( -name '*.cpp' -o -name '*.h' \) -print0 | xargs -0 egrep commit_action | wc -l 
293
```

We see that the calls are unbalanced.  You could be being bitten by this, just 10 layers removed.

**Comment by reduz** [comment] 2018-09-06 16:36
Can't re-create either, so closing.

**Closed by reduz** 2018-09-06 16:36 UTC
Labels: bug, needs testing, topic:core

**Comment by Valla-Chan** [comment] 2024-01-31 23:18
I'm also having this issue, and have absolutely no idea what to do.
