### ISSUE TITLE
AnimationPlayer emiting signal in the editor

### ISSUE THREAD

**Issue by henriiquecampos** [godotengine/godot#13394] opened 2017-11-29 10:25 UTC
Windows 10, Godot 2.1.4

I think the the `AnimationPlayer` `finished` signal is being emitted within the editor without we set any tool script.

I made a simple scene connecting the `finished` signal to the `queue_free` of the root node of the scene. When I play the animation, both through the **end** and to the **beginning**, Godot **crashes**.

**Steps to reproduce:**
1. Create a scene with a `Label`
2. Add an `AnimationPlayer` as child
3. Create an `animation`
4. Connect `finished` signal to the `queue_free` method using the editor interface
5. Play the animation

**Comment by reduz** [comment] 2017-11-29 13:02
that is expected, there is no reason why it should not do that

**Comment by henriiquecampos** [comment] 2017-11-29 13:26
Nope, tried with a `Sprite` and it also triggers the `queue_free` with its `texture_changed` signal.

So maybe...check for `! is_editor` to `queue_free` nodes?

**Comment by reduz** [comment] 2017-11-29 13:32
maybe we could avoid emitting signals conneted from the editor while
running from the editor, those are marked as persisting anyway

**Comment by henriiquecampos** [comment] 2017-11-29 13:35
Seems like the perfect solution. Would it work for tool scripts?

I mean, if I connect a signal within the editor but call a method in a `tool` script, will this method be called?

**Comment by reduz** [comment] 2017-11-29 13:38
when you connect by code, the persist flag is not set by default, so there
should be no problem

**Comment by henriiquecampos** [comment] 2017-11-29 13:40
But it would be connected through the editor, only the method would be in code. I think I misexpressed myself :P

**Comment by reduz** [comment] 2017-11-29 13:43
the fix is just making connnections with the persist flag not emit in editor mode

**Comment by reduz** [comment] 2017-11-29 13:44
or maybe not, if you make a plugin using the editor itself to edit the UI, that will make it stop working, so i am not very sure.

**Comment by henriiquecampos** [comment] 2017-11-29 13:49
Maybe let users set a flag to tell if the signal shall be executed in the editor?

I think it would be convenient to add just a `CheckButton` while connecting signals using the interface. And use it as an extra argument for `connect` ?

**Comment by akien-mga** [comment] 2018-07-22 15:59
Duplicate of #13070.

**Closed by akien-mga** 2018-07-22 15:59 UTC
Labels: bug, topic:editor
