### ISSUE TITLE
using a varying in the vertex shader and not using it in any other stage yields an error

### ISSUE THREAD

**Issue by QbieShay** [godotengine/godot#50464] opened 2021-07-14 20:14 UTC
### Godot version

v3.4.beta.custom_build [a3310c1da]

### System information

Linux Arch, Radeon RX 590

### Issue description

This shader code does not compile

```
shader_type spatial;
render_mode blend_add, unshaded;

uniform sampler2D shape_texture;
uniform sampler2D color_gradient;
uniform float emission_intensity = 1.0;
uniform sampler2D noise;

varying float lifetime;

void vertex(){
	lifetime = INSTANCE_CUSTOM.y/INSTANCE_CUSTOM.w;
	
}

void fragment(){
	float shape = texture(shape_texture, UV).r;
	//shape += texture(noise, vec2(lifetime, 0.0) + UV).r ;
	shape = clamp(shape, 0.0, 1.0);
	float alpha = shape - (1.0 - COLOR.r);
	vec4 color = texture(color_gradient, vec2(alpha/ COLOR.r));
	ALBEDO = max(vec3(0.0), emission_intensity * color.rgb * alpha);
}
```

![Screenshot_2021-07-14_22-13-28](https://user-images.githubusercontent.com/7917475/125686709-3c8fc4cb-4faa-4138-babf-c8e8f6bf07e2.png)

### Steps to reproduce

see above

**Comment by Calinou** [comment] 2021-07-14 20:54
I can confirm this on `master` Git 8747f2565 while working on https://github.com/godotengine/godot/pull/50442.

**Comment by Chaosus** [comment] 2021-07-15 06:07
I don't think it's a bug since It's proposed by @reduz (https://github.com/godotengine/godot/pull/44698#issuecomment-776056050). If this is undesired I could fix this of course...

**Comment by QbieShay** [comment] 2021-07-15 07:39
Oh sorry @Chaosus, I didn't know. I think it's valid to use a varying only in the vertex shader, because while a finished shader doesn't do this, while you're developing a shader you might have plenty of these instances.
@reduz I think we should accept if a varying is used in the vertex shader only, for the sake of easing development.

If we are against this still, the error message needs to be made more explicit. I wasn't sure what was the issue, and I tried adding more keywords to the varying (fragment, vertex etc.)

**Comment by Chaosus** [comment] 2021-07-15 08:10
>  I think it's valid to use a varying only in the vertex shader

Do you mean assign in the vertex shader? Because varyings are the mechanism of translation variables between functions so there is no point to use it in the vertex shader rather than assign and use it in a fragment + now it's not only limited to the vertex but can be used to fragment->light or vertex->light etc,

**Comment by QbieShay** [comment] 2021-07-15 08:19
In the above example I was developing a shader so I didn't get yet to the part where I was using it, and it's annoying when the shader is incomplete, because it errors in the middle of development. This is the only case where an unused variable causes an error and not a warning

**Comment by Calinou** [comment] 2021-07-15 13:52
We can use the new warning system to emit a warning instead of an error.

**Comment by Chaosus** [comment] 2021-07-15 14:17
I want https://github.com/godotengine/godot/pull/49996 to be merged first since it introduces handling of function name inside, which is required to implement this warning...

**Closed** 2021-07-21 11:05 UTC
Labels: confirmed, enhancement, topic:shaders

**Comment by Infini-Creation** [comment] 2025-02-03 10:12
Don't know for sure if it's related to this but with the latest v4.4.beta2.official [a013481b0], I've got:

![Image](https://github.com/user-attachments/assets/8d64c5ce-49ce-49f6-9d12-16620a3b37a6)

which is also quite a confusing warning.
