### ISSUE TITLE
Nested nodes with "Clip Children" wont render children

### ISSUE THREAD

**Issue by peterhoglund** [godotengine/godot#80494] opened 2023-08-10 20:31 UTC
### Godot version

4.1.1.stable.official

### System information

MacOS 11.7.4

### Issue description

It seems like you can't have several nodes with "Clip Children" as children. I use a Panel node as a clipping mask for a Texture ("ClipMask" in the attached image) with "Clip Only" applied. That node is a child of another Panel node ("Background") with "Clip + Draw" applied. This will result in "Background" turning white and the children nodes invisible. Self modulate is not working on "Background" however Modulate will tint the white color. If I turn off the "ClipMask", Self Modulate does work. So it seems like something is not working as expected with how "Background" is rendered in this state. The clipping works though, "ColorRect" is clipped by "Background".

I would expect the Texture to be clipped by ClipMask and then with the ColorRect ontop of them, and all of them being clipped by "Background". Self Modulate would only tint the background color, and Modulate would tint both "ColorRect" and the Texture.

<img width="321" alt="image" src="https://github.com/godotengine/godot/assets/522470/10309a3d-8fce-4f07-b788-0b8349081827">

### Steps to reproduce

See the image above, and set Background Clip Children to Clip+Draw and ClipMask to Clip Only.

### Minimal reproduction project

-

**Comment by clayjohn** [comment] 2023-08-10 20:38
Duplicate of https://github.com/godotengine/godot/issues/75042 and https://github.com/godotengine/godot/issues/74175

To keep track of everything in the same place. I am closing this, in favour of https://github.com/godotengine/godot/issues/75042 which includes an MRP.

To be clear, this is a well-known limitation of clip_children and the CanvasGroup that is mentioned in the docs, but not in enough places. 

That being said, there is already a PR lifting this limitation. You could help get the PR merged sooner by testing it in your project https://github.com/godotengine/godot/pull/74859

**Closed by clayjohn** 2023-08-10 20:38 UTC

**Comment by peterhoglund** [comment] 2023-08-10 21:21
Ok, thank you for letting me know!
