### ISSUE TITLE
Fallback to embedded font for dynamic font

### ISSUE THREAD

**Issue by volzhs** [godotengine/godot#8998] opened 2017-05-30 17:32 UTC
**Operating system or device - Godot version:**
All OS, All Godot version

**Issue description:**

Letters are not visible if assigned font does not have for it after assigning a TTF.
but we have embedded font for taking care of almost all kinds of languages.
So, it will be great that character is rendered with embedded fonts if assigned custom TTF and its fallback don't have for it.

I hope 2.1 has this too.

**Comment by kubecz3k** [comment] 2018-04-04 16:00
First of all thank you for your report and sorry for the delay.

We released Godot 3.0 in January 2018 after 18 months of work, fixing many old issues either directly, or by obsoleting/replacing the features they were referring to.

We still have hundreds of issues whose relevance/reproducibility needs to be checked against the [current stable version](https://godotengine.org/download), and that's where you can help us.
**Could you check if the issue that you described initially is still relevant/reproducible in Godot 3.0 or any newer version, and comment about its current status here?**

For bug reports, please also make sure that the issue contains detailed steps to reproduce the bug and, if possible, a zipped project that can be used to reproduce it right away. This greatly speeds up debugging and bugfixing tasks for our contributors.

Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

Thanks in advance.

*Note: This message is being copy-pasted to many "stale" issues (90+ days without activity). It might happen that it is not meaningful for this specific issue or appears oblivious of the issue's context, if so please comment to notify the Bugsquad about it.*

**Comment by akien-mga** [comment] 2018-09-14 16:29
@volzhs Is this still relevant?

**Comment by Yukitty** [comment] 2019-01-22 20:53
Yes. Godot Engine still skips rendering text at all if a font is missing the glyphs that are being used.

**Comment by Calinou** [comment] 2019-10-19 19:35
Note that Godot lets you define an arbitrary number of fallback fonts in DynamicFont since 3.0:

![image](https://user-images.githubusercontent.com/180032/67150480-3fcfd480-f2b8-11e9-849d-a7e425665817.png)

Since the default project font currently supports *less* characters than most TTF fonts out there, is this issue worth keeping open?

**Comment by Calinou** [comment] 2021-01-31 20:55
Closing per the above comment.

**Closed by Calinou** 2021-01-31 20:55 UTC
Labels: enhancement, topic:core
