### ISSUE TITLE
Code editor tooltip gets cut off by a panel to the side.

### ISSUE THREAD

**Issue by ShantanuBalse** [godotengine/godot#20534] opened 2018-07-28 05:13 UTC
**Godot version:** 3.0.5 Stable Official

**OS version:** Windows 10

**Issue description:**

If the tooltip is big enough, it will get cut off by the panel to it's side (the inspector panel in attached screenshot).

**Steps to reproduce:**
Write a line long enough for it's tooltip to reach the edge of the neighbouring panel.

![capture](https://user-images.githubusercontent.com/36737173/43353271-89c0803a-9251-11e8-9c49-77ec364a8929.PNG)

**Comment by akien-mga** [comment] 2018-07-28 08:16
I'm pretty sure this is a duplicate, but I can't find the earlier issue(s) about it...

**Comment by romlok** [comment] 2018-07-28 08:52
Looks like #16225 is the same bug.

**Comment by Calinou** [comment] 2019-07-03 23:10
Duplicate of #16225. (While the tooltip is cut at the bottom in the linked issue, the underlying bug is the same.)

**Closed by Calinou** 2019-07-03 23:10 UTC
Labels: bug, topic:editor, usability
