### ISSUE TITLE
Editor Settings/Run/Window Placement/Rect = Force Maximized always ignores Screen setting.

### ISSUE THREAD

**Issue by ajboni** [godotengine/godot#35571] opened 2020-01-26 04:35 UTC
**Godot version:**
3.1.2 and 3.2.rc3

**OS/device including version:**
OS: Linux Mint 19.3 Tricia x86_64 
 Kernel: 5.3.0-26-generic 

**Issue description:**

Editor Settings / Run / Window Placement / **Rect** = Force Maximized always ignores *Screen* setting.

It runs the project on the same monitor, no matter what settings. Other combinations work as expected (eg: Force Fullscreen + Next monitor)

**Steps to reproduce:**
set the editor setting like the image ( Rect=Force Maximized and Screen = Monitor 2 or Next Monitor)

![image](https://user-images.githubusercontent.com/12578313/73130682-ecb69d80-3fdb-11ea-92ef-44e76d92a7ec.png)

**Comment by KoBeWi** [comment] 2020-12-17 00:06
@ajboni Can you still reproduce the issue in [Godot 3.2.4 beta4](https://godotengine.org/article/dev-snapshot-godot-3-2-4-beta-4)?

I can't. Windows 10

**Comment by ajboni** [comment] 2020-12-17 04:04
> @ajboni Can you still reproduce the issue in [Godot 3.2.4 beta4](https://godotengine.org/article/dev-snapshot-godot-3-2-4-beta-4)?
> 
> I can't. Windows 10

Just tried again, still fails. (always open in same monitor)

**Comment by Calinou** [comment] 2022-10-28 21:01
Duplicate of https://github.com/godotengine/godot/issues/36462.

**Closed by Calinou** 2022-10-28 21:01 UTC
Labels: bug, platform:linuxbsd, topic:editor, confirmed
