### ISSUE TITLE
The mouse mode stays the same when an issue happens

### ISSUE THREAD

**Issue by HatisEm** [godotengine/godot#5399] opened 2016-06-25 04:56 UTC
**Operating system or device - Godot version:**
Ubuntu 15.10, Godot 2.0.2

**Issue description** (what happened, and what was expected):
I wrote a little code to capture the mouse like this "Input.set_mouse_mode(Input.MOUSE_MODE_CAPTURED)"
the problem is when I add a new feature i get issues in the code just like every other human and when issues happen the editor pops up which is the problem, the mouse is still captured i can't type anything and can't use the editor's shortcuts to stop debugging or even close the window with "Alt+F4" the Ubuntu shortcut

**My Wish**
Add some feature that returns the mouse mode to un-captured, or saves the system's state before debugging the game and redo it when there are issues because the only solution that I can do is RESTART the computer which is why my development is SLOW

**Comment by akien-mga** [comment] 2016-06-25 08:38
This is indeed a bug and should be fixed. Note that you probably don't need to restart your computer for that though, you just need to find a way to kill the Godot process. Alt+F4, or log in to tty2 and `killall -9 godot.name.of.binary`, etc.

**Comment by Hinsbart** [comment] 2016-06-25 11:27
Correct me if I'm wrong, but isn't this a duplicate of #2232, and has already been fixed by #4295 ?

**Comment by akien-mga** [comment] 2016-06-25 11:36
Indeed, and the fix had been backported for 2.0.3-stable already, so closing.

**Closed by akien-mga** 2016-06-25 11:36 UTC
Labels: bug, topic:editor, usability
