### ISSUE TITLE
cpu-features.h not found

### ISSUE THREAD

**Issue by pranshuthegamer** [godotengine/godot#52351] opened 2021-09-02 19:46 UTC
### Godot version

3.3

### System information

Android 10 Using Termux

### Issue description

Im trying to compile a server build of godot from Android using termux, but a file is missing, called cpu-features.h

![Screenshot_2021-09-03-01-11-38-646_com termux](https://user-images.githubusercontent.com/61378895/131906421-5734ca6f-93c2-4720-9609-0ba393356421.jpg)

### Steps to reproduce

install termux from f-droid (play store version outdated)
install Python3.5+
Install Scons using pip

get 3.3 stable source, extract and cd into it

run  `scons  -j8 platform=server tools=no target=release`

**Comment by Calinou** [comment] 2021-09-02 19:48
Duplicate of https://github.com/godotengine/godot/issues/30914.

**Closed by Calinou** 2021-09-02 19:48 UTC
