### ISSUE TITLE
CSharp Tool scripts cannot have custom resource properties set in the inspector

### ISSUE THREAD

**Issue by Mantissa-23** [godotengine/godot#85825] opened 2023-12-06 07:44 UTC
### Tested versions

- Reproducible In: 4.2.stable.mono

I suspect but have not confirmed that this bug has always been present in the C# build.

### System information

Godot v4.2.stable.mono - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3080 (NVIDIA; 31.0.15.3734) - AMD Ryzen 9 5900X 12-Core Processor (24 Threads)

### Issue description

A C# tool script cannot have a custom resource property set. It will result in the following error:

```
  /root/godot/modules/mono/glue/GodotSharp/GodotSharp/Core/NativeInterop/ExceptionUtils.cs:112 - System.InvalidCastException: Unable to cast object of type 'Godot.Resource' to type 'Prism.ProceduralAnimation.JointConstraintSet'.
     at Prism.ProceduralAnimation.InverseKinematics.RestoreGodotObjectData(GodotSerializationInfo info) in C:\Users\Dylan\Projects\studio-mantissa\Godot.SourceGenerators\Godot.SourceGenerators.ScriptSerializationGenerator\Prism.ProceduralAnimation.InverseKinematics_ScriptSerialization.generated.cs:line 32
     at Prism.ProceduralAnimation.IKOnNode3D.RestoreGodotObjectData(GodotSerializationInfo info) in C:\Users\Dylan\Projects\studio-mantissa\Godot.SourceGenerators\Godot.SourceGenerators.ScriptSerializationGenerator\Prism.ProceduralAnimation.IKOnNode3D_ScriptSerialization.generated.cs:line 22
     at Godot.Bridge.CSharpInstanceBridge.DeserializeState(IntPtr godotObjectGCHandle, godot_dictionary* propertiesState, godot_dictionary* signalEventsState) in /root/godot/modules/mono/glue/GodotSharp/GodotSharp/Core/Bridge/CSharpInstanceBridge.cs:line 255
```

### Steps to reproduce

Assuming MRP:
1. Select any node that has a tool script with a custom resource property
2. Attempt to create a new resource to fill that property, or load a resource from the filesystem
3. Property will remain null, and resource will not be created, and the above error will be thrown.

### Minimal reproduction project (MRP)

[CSharp Tool Script Resource Error MRP.zip](https://github.com/godotengine/godot/files/13578001/CSharp.Tool.Script.Resource.Error.MRP.zip)

**Comment by raulsntos** [comment] 2023-12-07 01:49
Scripts not marked as `[Tool]` can't be instantiated in the editor, instead we create a placeholder to hold the necessary data (that's how you can edit it in the inspector). So you need to add the `[Tool]` attribute to the C# classes that you want to use in the editor (this includes resources that you want to access from other tool scripts because they run in the editor).

Make sure to read the [_Running code in the editor_](https://docs.godotengine.org/en/stable/tutorials/plugins/running_code_in_the_editor.html#doc-running-code-in-the-editor) documentation page for more information.

- Closing as duplicate of https://github.com/godotengine/godot/issues/55596.

**Closed by raulsntos** 2023-12-07 01:49 UTC
