### ISSUE TITLE
GLTF and GLB animation optimization removes too many keyframes

### ISSUE THREAD

**Issue by OlivierVanHoutte** [godotengine/godot#63327] opened 2022-07-22 19:14 UTC
### Godot version

4.0.alpha12

### System information

Windows 10, Vulcan

### Issue description

When importing an glb or gltf file, with animation optimization enabled (default settings), it removes too many keyframes, resulting in a wrong animation. This does not happen in version 3.4.4 stable. 
4.0.alpha12:
![image](https://user-images.githubusercontent.com/33663275/180506415-9aad48f2-d9f0-44da-8996-7d12141cf0e9.png)
3.4.4 stable:
![image](https://user-images.githubusercontent.com/33663275/180506827-20009472-fe6d-4591-87f1-4c5f72564a9b.png)
Notice the difference in keyframes.

Temporary fix would be to disable this optimization (or roll back to whatever was used in 3.4.4). 

### Steps to reproduce

1. Create a new project
2. Make a new 3D scene
3. Add the attached GLB file to the scene (make sure animation optimization is enabled on import, should be enabled by default)
4. Open the "Idle" animation
5. Look at the keyframes
6. Compare the animations with a glb viewer or the same scene in godot version 3.4.4 stable

[GLB file.zip](https://github.com/godotengine/godot/files/9170098/GLB.file.zip)

### Minimal reproduction project

[test.zip](https://github.com/godotengine/godot/files/9170130/test.zip)

**Comment by Calinou** [comment] 2022-07-22 19:40
Duplicate of https://github.com/godotengine/godot/issues/53864, https://github.com/godotengine/godot/issues/58968 and/or https://github.com/godotengine/godot/issues/59150.

**Closed by Calinou** 2022-07-22 19:40 UTC
Labels: bug, topic:animation, topic:3d
