### ISSUE TITLE
Creating gd class file and renaming causes Parse Error

### ISSUE THREAD

**Issue by wyattbiker** [godotengine/godot#49751] opened 2021-06-20 05:08 UTC
### Godot version

3.3.2.stable

### System information

Mac OS X (Catalina) 10.15.7

### Issue description

Create a simple gd class file and save it. Rename the script file, make a change and save. You will get this error:
```
 res://Testing/SpritesTest/new_script.gd:1 - Parse Error: Unique global class "script" already exists at path: res://Testing/SpritesTest/new_script2.gd
 modules/gdscript/gdscript.cpp:583 - Method failed. Returning: ERR_PARSE_ERROR
```

Errors will only stop showing up when you exit Godot Project.

### Steps to reproduce

Put the script below in a .gd script file called **new_script.gd**

```
class_name script
	
var x	
func _init(amt):
	x=amt
	
func incrby(amt):
	x += amt	
```		

- Save the file. 
- Rename it to **new_script1.gd** from the FileSystem panel.
- Edit something like adding a blank line.
- Save
- Error will appear in Output console

### Minimal reproduction project

See above

**Comment by Calinou** [comment] 2021-06-20 09:54
Duplicate of https://github.com/godotengine/godot/issues/49369.

**Closed by Calinou** 2021-06-20 09:54 UTC
