### ISSUE TITLE
Rigged mesh sometimes disappears during an animation

### ISSUE THREAD

**Issue by mysticfall** [godotengine/godot#19281] opened 2018-05-30 23:41 UTC
**Godot version:**
`master` / 2ff31bada

**OS/device including version:**
_Manjaro Linux 17.1_

**Issue description:**
I have a 3D character scene which is composed of a `KinematicBody` under which its skeletons and all relevant meshes resides.

It works correctly for the most part but intermittently, some attached mesh instances disappear when the character plays a certain animation (implemented as `AnimationTreePlayer`'s one shot node):

* https://www.youtube.com/watch?v=-BR9NRxWIHw

My first instinct was to suspect bad weight painting, but as the problem only occurs from time to time so probably the cause could lie elsewhere.

I know that it's neither very informative nor specific enough to be a good issue report, but for now I have little idea where to look at to find additional clues about the cause.

I'd appreciate if anyone could give me some suggestions what debugging steps I could try to investigate the problem further, and I'll try to update the issue with more specific informations if I can find them.

**Comment by CptPotato** [comment] 2018-05-31 15:05
Looks like the different parts of the character are seperate 3d objects. In the video Godot doesn't seem to use the transformed objects' bounding boxes for frustum culling but the original ones. So when they go off-screen the corresponding object is culled.

Also, I want to add that proper culling for animated meshes might be a bit tricky, especially when using GPU accelerated bone animations (not sure if Godot uses this approach).

**Comment by mysticfall** [comment] 2018-06-01 02:49
Yes, the hair and clothe are consisted of different meshes which reside under a single skeleton:
![hierarchy](https://user-images.githubusercontent.com/2367032/40818314-917627fe-6591-11e8-8f74-45debde969dd.png)

Thanks for the insight. I don't have sufficient knowledge to use the information to fix this problem, but I hope it might help engine devs to figure out what really went wrong.

**Comment by Sslaxx** [comment] 2018-06-23 11:09
If the documentation doesn't make mention of it if it isn't a bug, perhaps it should?

**Comment by akien-mga** [comment] 2018-06-25 14:01
Fixed by #19193 according to @karroffel.

**Comment by mysticfall** [comment] 2018-06-25 16:21
@akien-mga I'm not sure if it was the case. I've been using that branch rebased on master for a while, and it was that environment on which I found the fix I mentioned above.

I just tested it with `master`(0954c8f01765) again and I could reproduce the issue as before.

**Comment by mysticfall** [comment] 2018-06-25 17:09
It turned out I was indeed using a stale build for the past couple of weeks (it was asomething has changed regarding `pkg-config`, I suppose), but the problem still persists with the latest build.

I was wondering why I'm not seeing all the greatest things reduz has been working on `AnimationGraphPlayer` on my end, but now I know why :) But I suppose we should consider reopening this issue, if it's not indeed an intended behavior.

**Comment by vnen** [comment] 2018-06-25 21:17
> but the problem still persists with the latest build.

Did you reimport the models with the new build?

**Comment by mysticfall** [comment] 2018-06-26 02:58
No, I didn't. Maybe that could be why I'm still having the problem, then? I'll test it again with reimporting all the relevant models soon and let you know if it resolves the issue for me.

**Comment by karroffel** [comment] 2018-06-26 09:16
I had to re-import too, after that it was fixed.

**Comment by mysticfall** [comment] 2018-06-26 16:14
Just tried it again after reimporting the body, hair, collar meshes and the problem seems to persist. I simply deleted `*,mesh` resources and reimported from `*.dae` files which I exported using Better Collada.

**Comment by tagcup** [comment] 2018-06-26 18:41
@mysticfall Can you upload a dae file which reproduces this?

**Comment by mysticfall** [comment] 2018-06-27 10:15
@tagcup Of course, I just pusehed the reimported meshes as linked above. And you can download the associated Collada(.dae) files from the same location where those mesh resources are located.

**Comment by tagcup** [comment] 2018-06-27 14:46
Do you have a single .dae file containing animation which reproduces this issue? Human.dae has no animations and doesn't reproduce the issue.

**Comment by tagcup** [comment] 2018-06-27 15:01
FYI, in case all you reimported was mesh files, what you actually need to reimport is animations

**Comment by tagcup** [comment] 2018-06-27 19:15
I imported & opened the file Animations - Interactions.dae, and played the animation and I'm not seeing any problems.

Again, can you please upload a **single** self-contained dae which reproduces the issue?

**Comment by tagcup** [comment] 2018-06-27 19:21
I also tried opening Animations - Interactions.dae, exported the pick up animation, open Human Female scene, loaded the pick up animation file into the animation (I don't know if this is your workflow or not, I wish you were descriptive, I have no idea what you're doing), and played it, and everything seems to be working fine here. I don't see any disappearing meshes.

**Comment by mysticfall** [comment] 2018-06-27 23:00
Unlike #19027, it's only reproducible when running a scene, and the symptom is demonstrated in the Youtube video I linked in the description above.

The only way to reproduce it I know of is using the whole project that contains those animation resources. You'll need to change _'Extra Cull Margin'_ property back to '0' on the 'Short Hair' and 'Collar' mesh instances too.

If you have a full project, run it (the default `Test Scene`) and move the character forward to get closer to one of the rag items lying on the ground.

You might need to get a bit closer to be able to interact with it (It'll show "`E` Take" if you do that). Then press `E` to see the character stooping down to pick the item, and you'll probably see either the hair or collar disappear briefly when her head in at the lowest position. If it doesn't reproduce the issue, exist the game play (press `ESC` and select `Quit` from the menu) and try it again. On my end, now it happens about 80% of the times.

Note that you'll need to be in a 3rd person view to see it happens.

Sorry I couldn't find any easier way to reproduce the issue.

**Comment by reduz** [comment] 2018-11-19 11:56
Seems this is because of bones AABBs not being properly updated. This broke at some point during the move to GLES3, I will give it a check.

**Closed** 2018-11-19 13:44 UTC
Labels: bug, hero wanted!, topic:rendering
