### ISSUE TITLE
godot 4.0 beta theme crash

### ISSUE THREAD

**Issue by antigamer101** [godotengine/godot#65994] opened 2022-09-17 17:09 UTC
### Godot version

4.0.beta

### System information

Windows 10, nvidia gtx 1650

### Issue description

trying to change the theme options crashes the engine

### Steps to reproduce

Editor -> Editor settings -> Theme -> Base color/ Accent color

**Comment by KoBeWi** [comment] 2022-09-17 17:27
Duplicate of #59798

**Closed by KoBeWi** 2022-09-17 17:27 UTC
