### ISSUE TITLE
Change node name removes editable children and wipes all unique data

### ISSUE THREAD

**Issue by chucklepie** [godotengine/godot#41351] opened 2020-08-18 13:29 UTC
**Godot version:**
3.2.2 stable

**OS/device including version:**
linux mint

**Issue description:**
I changed the name of some nodes with editable children. Without any prompt or direction, it not only removed the editable children, but on showing editable children every change was lost.

Changing a name should not wipe data.

I found this issue: 20409

But it is closed with no status other than saying it might be fixed by somebody back in 2019...

**Steps to reproduce:**
As above, simply rename a node

**Comment by Calinou** [comment] 2020-08-18 14:05
Duplicate of https://github.com/godotengine/godot/issues/20409 (which is open as of writing).

**Closed by Calinou** 2020-08-18 14:05 UTC
