### ISSUE TITLE
Error message using a sampler2D uniform in a shader code

### ISSUE THREAD

**Issue by LD2Studio** [godotengine/godot#55046] opened 2021-11-17 05:43 UTC
### Godot version

v4.0.dev.custom_build [d01fae9a8]

### System information

Kubuntu 20.04, Intel i5-2500, 16Go, GTX1050Ti

### Issue description

I use a uniform variable of type sampler2D in my shader code, then assign a NoiseTexture resource to this variable. The moment I add the OpenSimplexNoise resource as noise, looping error messages appear.
The problem also occurs if I use a GradientTexture2D resource with a new gradient.

### Steps to reproduce

Create a shader attached to a meshinstance3D with a PlaneMesh for example.
Copy the following shader code:
```
shader_type spatial;

uniform sampler2D noise;
```
Add NoiseTexture and  OpenSimplexNoise like noise.
![2021-11-17_06-32](https://user-images.githubusercontent.com/75833443/142140830-a7493583-a96a-4bf1-abf7-91cdf7a0111d.png)

error messages appear immediately: 
![2021-11-17_06-35](https://user-images.githubusercontent.com/75833443/142141100-13f49720-5b3a-4718-8191-0399aab7e9b3.png)

### Minimal reproduction project

[IssueShaderUniform01.zip](https://github.com/godotengine/godot/files/7552075/IssueShaderUniform01.zip)

**Comment by Chaosus** [comment] 2021-11-17 07:51
Duplicate of https://github.com/godotengine/godot/issues/53089

**Closed by Chaosus** 2021-11-17 07:51 UTC
