### ISSUE TITLE
RichTextLabel: Distance Field font gets rendered blurred

### ISSUE THREAD

**Issue by timoschwarzer** [godotengine/godot#5632] opened 2016-07-10 19:02 UTC
**Operating system or device - Godot version:**
Any, 2.0.4.1

**Issue description** (what happened, and what was expected):
See title

**Comment by vnen** [comment] 2016-07-10 20:01
Related to the discussion on #5514.

And screenshots would be nice.

**Comment by timoschwarzer** [comment] 2016-07-10 22:14
Screenshot:
![image](https://cloud.githubusercontent.com/assets/8849554/16716396/d1173940-46fb-11e6-9b86-f4116c912907.png)

Sample Project: (used Font: https://fonts.google.com/specimen/Itim)
[gd-richtextlabel.tar.gz](https://github.com/godotengine/godot/files/356222/gd-richtextlabel.tar.gz)

**Comment by akien-mga** [comment] 2016-07-10 22:16
That's actually a feature for all fonts that look like Comic Sans MS. :p

**Comment by timoschwarzer** [comment] 2016-07-10 22:18
Ehm, this is not Comic Sans... :laughing: (But well, it looks similar :grin:)

**Comment by akien-mga** [comment] 2016-07-10 22:21
That why I said "that look like" ;)

**Comment by timoschwarzer** [comment] 2016-07-10 22:28
I tried it with other fonts... It happens there, too... 
*surprise* :joy:

**Comment by akien-mga** [comment] 2018-11-23 15:45
Still reproducible in 2.1.5, as well as in the current master branch after converting the project using the WIP exporter. Note that the .fnt files should be saved in 2.1.5 before exporting for them to work in 3.0+ (and they eventually get corrupted on save in the master branch anyway).

The blurry render in RTL is the same as you'd get in Label if you disable the `distance_field` hint, so it sounds like RTL simply doesn't support distance field BitMapFont.

**Comment by KoBeWi** [comment] 2020-11-12 00:16
Can anyone still reproduce this bug in Godot 3.2.3 or any later release?

If yes, please ensure that an up-to-date Minimal Reproduction Project (MRP) is included in this report (a MRP is a zipped Godot project with the minimal elements necessary to reliably trigger the bug). You can upload ZIP files in an issue comment with a drag and drop.
(the provided project is incompatible with Godot 3)

**Comment by Calinou** [comment] 2020-11-12 13:46
Duplicate of https://github.com/godotengine/godot/issues/8022.

**Closed by Calinou** 2020-11-12 13:46 UTC
Labels: bug, topic:gui
