### ISSUE TITLE
Drag and Drop @export is reset when file saves in GD v4.0

### ISSUE THREAD

**Issue by MrJoshBowman** [godotengine/godot#47747] opened 2021-04-09 11:20 UTC
**Godot version:**
4.0 dev build

**OS/device including version:**
MacOS Big Sur, Macbook Pro 2019

**Issue description:**
Whenever I drag a script to use (or anything I set up as a custom export) into its box in the inspector. It goes in but as soon as the file saves, it disappears again and isn't used.

**Steps to reproduce:**
Drag 'test_script.gd' into 'Another Script Input' box in the 'Control' Node.
*appears in the box*
Save the updated Control file
*'test_script.gd' disappears from box*

(I've included a 'preload' of the script in the Control.gd as well, just for comparison)

**Minimal reproduction project:**
[13_exportReset.zip](https://github.com/godotengine/godot/files/6285327/13_exportReset.zip)

**Comment by KoBeWi** [comment] 2021-04-09 12:06
Duplicate of #43542

**Closed by KoBeWi** 2021-04-09 12:06 UTC
