### ISSUE TITLE
`SHADOWED_VARIABLE` false positive within static functions

### ISSUE THREAD

**Issue by khellste** [godotengine/godot#70857] opened 2023-01-03 01:30 UTC
### Godot version

4.0-beta10

### System information

Windows 10, Vulkan

### Issue description

The `SHADOWED_VARIABLE` warning gives a false positive when a variable in a static function scope has the same name as an instance field. This shouldn't be the case since instance fields are not in the same scope as static functions.

Here's a very minimal repro:
```
class_name StaticFuncShadow
extends RefCounted

static func static_func(x: String) -> void:
    print(x)

var x: String = ""
```

![image](https://user-images.githubusercontent.com/3039797/210289357-596fd950-ea52-4b0e-9a89-5f1bad9134c5.png)

### Steps to reproduce

1. Create a class with an instance field named `x`.
2. Give that class a static function with a parameter named `x`.
3. After running the project, the debugger complains that the static function parameter `x` shadows the instance field `x`.

### Minimal reproduction project

[LinterError.zip](https://github.com/godotengine/godot/files/10333945/LinterError.zip)

**Comment by khellste** [comment] 2023-01-03 01:40
It's not exactly the same issue, but I would also advocate for relaxing this warning inside constructor methods. In my experience it's pretty common for instance fields to be assigned directly from constructor parameters, and it's silly to have to change the name just to work around the linter warning.

For example, the following is a very common pattern in other languages (Python, Java, JavaScript, C#, and others) that isn't possible to do in GDScript without getting a warning:
```
var my_field

func _init(my_field):  # <-- SHADOWED_VARIABLE warning
    self.my_field= my_field
```

**Comment by kleonc** [comment] 2023-01-03 11:38
Duplicate of #63120.

@khellste `_init` is not any different in that aspect, the shadowing warning is correct in that case. That's expected behavior, not a bug. So if anything, what you're suggesting for `_init` could be a subject for a discussion in [Godot Improvement Proposals](https://github.com/godotengine/godot-proposals#godot-improvement-proposals).

**Closed by kleonc** 2023-01-03 11:38 UTC
Labels: bug, topic:gdscript
