### ISSUE TITLE
Reflections for StandardMaterial3D show up as pure black when using a PanoramaSkyMaterial in Compatibility Renderer

### ISSUE THREAD

**Issue by Alex786** [godotengine/godot#95882] opened 2024-08-21 03:43 UTC
### Tested versions

First Found in v4.3.stable.official [77dcf97d8]
Reproducible in 4.3-stable, 4.3-rc3, 4.3-rc2, 4.3-rc1
Not Reproducible in v4.3.beta3.official [82cedc83c] and earlier

### System information

Godot v4.3.stable - Windows 10.0.22631 - GLES3 (Compatibility) - Intel(R) UHD Graphics 605 (Intel Corporation; 30.0.101.1660) - Intel(R) Pentium(R) Silver N5030 CPU @ 1.10GHz (4 Threads) \ Driver Version: 10.0.22621.3672

### Issue description

When using the Compatibility Renderer, The sky reflections for StandardMaterial3D using a PanoramaSkyMaterial appear entirely black.

![image](https://github.com/user-attachments/assets/1bd3bb79-1214-4093-b080-61990100781a)

The issue doesn't seem to appear while using a ProceduralSkyMaterial or PhysicalSkyMaterial (Haven't tried ShaderMaterial).
It gets weirder because it will sometimes work correctly if I reload the project (either through the project list or using the "reload current project" button).

### Steps to reproduce

1. Add Root 3D Scene
2. Add MeshInstance3D
3. Add Mesh
4. Add StandardMaterial3D
5. Metallic = 1
6. Roughness = 0
7. Add WorldEnvironment
8. Add New Environment Resource
9. Change Background mode to Sky
10. Add New Sky Resource
11. Add PanoramaSkyMaterial
12. Add EXR file (one is provided in MRP)

### Minimal reproduction project (MRP)

[MRP.zip](https://github.com/user-attachments/files/16685700/MRP.zip)

**Comment by patwork** [comment] 2024-09-21 14:11
Cannot reproduce on nvidia GTX960, but I suspect it is just cubemap update problem (fixed in https://github.com/godotengine/godot/pull/97069)

![cc](https://github.com/user-attachments/assets/e6828cc5-1f32-4e75-a074-591c312b496d)

**Closed** 2024-09-21 14:12 UTC
Labels: bug, topic:rendering, needs testing
