### ISSUE TITLE
Problem with Node doubling after add node to parent scene which already presents in child scene

### ISSUE THREAD

**Issue by breakmt** [godotengine/godot#28133] opened 2019-04-17 18:21 UTC
**Godot version:**
3.1 stable

**OS/device including version:**
Windows 7 x64 

**Steps to reproduce:**
1. Create Scene 1,
2. Create new inherited Scene 2 (as child of Scene 1),
3. Add to Scene 2 some node, for example Sprite - save,
4. Add to Scene 1 node of same type - save

**Result:**
In Scene 2 there are two nodes with same names and if you click on each of them - they both selected.

**Expected:**
Godot should handle this situation in the proper way. How? I'm not sure, but I think there should be a warning message in the moment when you open/switch to Scene 2. In this warning there should be a message like "There are a node %Node name% with the same name as in parent scene. Nodes can't use same name in one tree, thats why is will be renamed to %Node new name%" and button "Fix problem", which just rename Node (not from parent, child one) just the way "Duplicate" function works (so Sprite will be Sprite2).

Maybe more experienced users will show some better way to fix this!

![bug17042019](https://user-images.githubusercontent.com/1552169/56310802-6409f780-6155-11e9-9a99-8660e39fa460.gif)

**Minimal reproduction project:**
[17042019.zip](https://github.com/godotengine/godot/files/3090963/17042019.zip)

**Comment by eon-s** [comment] 2019-04-18 10:09
Try running it and look at the remote tree, to see what happens (maybe one of the nodes is renamed?).

I guess that the derived scene should detect if the base scene has a node with the same name and automatically rename it.

**Comment by bojidar-bg** [comment] 2019-04-18 12:35
Was reported earlier in #6152 for editable children, but not for inherited scenes.

**Comment by akien-mga** [comment] 2020-01-15 12:46
Duplicate of #26390.

**Closed by akien-mga** 2020-01-15 12:46 UTC
Labels: bug, topic:editor
