### ISSUE TITLE
The selection does not work correctly in some windows

### ISSUE THREAD

**Issue by Miskler** [godotengine/godot#77826] opened 2023-06-04 04:39 UTC
### Godot version

4.0.3.stable

### System information

Win 10, i5-11400H, 16GB RAM, RTX3050M

### Issue description

![ScreenRecorderProject139_1](https://github.com/godotengine/godot/assets/69055489/52133d16-fd9d-4aec-9c15-994c702e842a)

### Steps to reproduce

I also noticed this error in the window with plugins

### Minimal reproduction project

.

**Comment by Zentrophy** [comment] 2023-06-04 09:20
I've noticed that strange box appearing too when GL Compatibility mode is enabled.

**Comment by AThousandShips** [comment] 2023-06-04 09:24
* Duplicate of #74115

**Closed** 2023-06-06 03:56 UTC
