### ISSUE TITLE
Tooltips Showing when Godot is not focused.

### ISSUE THREAD

**Issue by Morokiane** [godotengine/godot#74531] opened 2023-03-07 04:44 UTC
### Godot version

4.0 stable

### System information

Windows 11

### Issue description

Tooltips pop up when Godot is not in focus. If a web browser or file explorer is above Godot and you move the mouse over something that has a tooltip the tooltip will pop over the window and will not go away unless you mouse over the element possibly causing another one to come up.

![example 1](https://user-images.githubusercontent.com/4334870/223322441-35196a2c-194b-4917-9041-62297f3f0512.png)
![example 2](https://user-images.githubusercontent.com/4334870/223322449-6a6f0ca7-0b24-4218-89ee-0fba3777b65b.png)

### Steps to reproduce

Have a active window above Godot. Mouse over an element that pops up a tooltip in Godot even though it isn't the active window.

### Minimal reproduction project

N/A

**Comment by RandomCatDude** [comment] 2023-03-07 12:31
Can't replicate on Manjaro Linux, so this might be a Windows-only bug.

**Comment by akien-mga** [comment] 2023-03-07 13:56
CC @bruvzg

**Comment by Morokiane** [comment] 2023-03-07 14:02
> Can't replicate on Manjaro Linux, so this might be a Windows-only bug.

Seems to be. I tried it on MacOS and it does not do it.

**Comment by mnemotic** [comment] 2023-03-07 19:24
Can confirm in Windows 11, 22H2.

**Comment by Anixias** [comment] 2023-03-13 22:37
Confirmed on Windows 10, and have tried Zorin OS (Ubuntu) and it does not occur there. Definitely a Windows-only bug.

**Comment by Calinou** [comment] 2023-03-13 22:49
- Duplicate of https://github.com/godotengine/godot/issues/46737.

**Closed by Calinou** 2023-03-13 22:49 UTC
Labels: bug, platform:windows, topic:porting, topic:gui
