### ISSUE TITLE
[4.0] Game debug window sometimes opens behind the Godot editor (DisplayServer regression)

### ISSUE THREAD

**Issue by PrecisionRender** [godotengine/godot#57831] opened 2022-02-08 23:54 UTC
### Godot version

v4.0.alpha.calinou [9d1626b4d]

### System information

Windows 11, Vulkan, Nvidia GeForce RTX 2060 Max-Q

### Issue description

When testing a game by clicking the play button in the Godot editor, the window will sometimes open behind the Godot editor. I have been unable to find a consistent way to reproduce this, although it does seem to happen more often after the first time a scene is run. It seems to hardly ever happen if the scene's root is just a `Node`. 

I have changed many different window settings, and none seemed to affect this problem, except for `Always on top`.

### Steps to reproduce

Unkown: it seems to happen on its own.

**Comment by Calinou** [comment] 2022-02-09 00:35
@PrecisionRender Can you reproduce this after enabling **Single Window Mode** in the Editor Settings then restarting the editor?

**Comment by PrecisionRender** [comment] 2022-02-09 02:03
@Calinou No. That seems to keep the issue from happening, at least from testing it for 2 minutes.

**Comment by mhilbrunner** [comment] 2022-02-11 15:38
Okay, weirdly enough, the _sometimes_ is perfectly reproducible:

If, after pressing Play, you move the cursor to the general area the game window pops up at, the new game window stays on top correctly.

However, if you leave the cursor in the general are of the editors Play button, the new window gets moved behind the editor.

**Comment by mhilbrunner** [comment] 2022-02-11 17:25
It seems this may have been caused by https://github.com/godotengine/godot/commit/f4ea9cd9f301d3af3a707e330221a4f1e242e7be (merged in PR https://github.com/godotengine/godot/pull/57341).
Thats the earliest commit I can reproduce it with, the one immediately before (https://github.com/godotengine/godot/commit/29c4644890c82f38f54553fa127a9661e7a0c75a) seems unaffected.

**Comment by bruvzg** [comment] 2022-02-11 20:26
> It seems this may have been caused by https://github.com/godotengine/godot/commit/f4ea9cd9f301d3af3a707e330221a4f1e242e7be (merged in PR https://github.com/godotengine/godot/pull/57341).

Is it reproducible after #57961?
Also, is it reproducible with versions before #57341, if you toggle editor full-screen on and off before running the project?

**Comment by bruvzg** [comment] 2022-02-11 21:33
This is caused by `transient` flag added to the tooltips (which is required to make them work in full-screen mode on macOS). But `transient` flag also sets child-parent relationship which is not required for non-exclusive transient windows and which cause the tooltip of the "Run" button to take app focus. Should be fixed by #56953.

**Comment by mhilbrunner** [comment] 2022-02-12 15:33
@bruvzg 
> Is it reproducible after https://github.com/godotengine/godot/pull/57961?

Yes.

> Also, is it reproducible with versions before https://github.com/godotengine/godot/pull/57341, if you toggle editor full-screen on and off before running the project?

Seems not reproducible, but only 90% sure as the Editor fullscreen mode seems pretty buggy for me.

> Should be fixed by https://github.com/godotengine/godot/pull/56953.

Confirmed

**Closed** 2022-02-12 15:46 UTC
Labels: bug, platform:windows, topic:porting, regression
