### ISSUE TITLE
Make time_scale behave similarly to pause

### ISSUE THREAD

**Issue by ArcFutahito** [godotengine/godot#7521] opened 2017-01-13 23:43 UTC
time_scale is really useful for slo-mo in games, but making it global limits use cases severely. What I propose is to handle changing scale similar to pause, where user can select some nodes/branches to be excluded from slo mo goodness.

**Comment by Norrolith** [comment] 2017-01-14 01:09
Seconded.

**Comment by ferhand** [comment] 2017-01-14 01:57
Yes, yes and three times yes. I second this motion too. An ease way to put some objects in slow motion even if they are influenced by the physics motor. 
Any way if there's a way to achieve that I can't find it...

**Comment by bojidar-bg** [comment] 2017-01-14 12:30
Duplicate of #6885?

**Comment by bojidar-bg** [comment] 2017-01-30 13:32
Closing as duplicate, given that nobody responded...

**Closed by bojidar-bg** 2017-01-30 13:32 UTC
