### ISSUE TITLE
ERROR: clear: Resources still in use at exit

### ISSUE THREAD

**Issue by shatilov-diman** [godotengine/godot#45512] opened 2021-01-27 20:37 UTC
At first: thank you all for the amazing engine!

I've found several similar issues, but it looks little different

**Godot version:**. v3.2.3.stable.official

**Issue description:**
```
ERROR: ~List: Condition "_first != __null" is true.
   At: ./core/self_list.h:112.
ERROR: ~List: Condition "_first != __null" is true.
   At: ./core/self_list.h:112.
Leaked instance: GDScript:6304 - Resource path: 
Leaked instance: GDScriptNativeClass:669
Leaked instance: GDScriptNativeClass:802
Leaked instance: GDScript:6303 - Resource path: res://Logger.gd
WARNING: cleanup: ObjectDB instances leaked at exit (run with --verbose for details).
   At: core/object.cpp:2135.
Hint: Leaked instances typically happen when nodes are removed from the scene tree (with `remove_child()`) but not freed (with `free()` or `queue_free()`).
ERROR: clear: Resources still in use at exit (run with --verbose for details).
   At: core/resource.cpp:477.
Resource still in use: res://Logger.gd (GDScript)
```

**Steps to reproduce:**
Please add below code into empty project and add it to AutoLoad.
Add export presses "Linux/X11". 
Export it with next command:

```
godot --verbose --path ${PWD} --export-pack "Linux/X11" test.pck
```

```gdscript
extends Node
class_name LoggerNode

class TaggedLogger:
  var _logger: LoggerNode = null
  var _tags: Dictionary = {}

  func _init(logger: LoggerNode, tags: Dictionary):
    self._logger = logger
    self._tags = tags

func With(tags: Dictionary) -> TaggedLogger:
  """Extend logs with tags"""
  return TaggedLogger.new(self, tags)
```

Removing 'LoggerNode' type hints or removing the script from AutoLoad (of course attach it to any scene) solve the leak.

**Comment by Calinou** [comment] 2021-01-27 20:43
PS: Please surround large blocks of text with triple backticks like this:

```
text here
```

This prevents them from taking too much space and also makes sure issue references aren't accidentally created. I edited your comment, but remember to do this next time :slightly_smiling_face:

**Comment by akien-mga** [comment] 2021-02-03 13:54
Duplicate of #16959.

**Closed by akien-mga** 2021-02-03 13:54 UTC
Labels: needs testing, topic:gdscript
