### ISSUE TITLE
(4.0) Running project (F5) takes forever to load

### ISSUE THREAD

**Issue by seppoday** [godotengine/godot#57342] opened 2022-01-28 09:53 UTC
### Godot version

4.0 alpha 1

### System information

Windows 10 (notebook), also Windows 7 (another notebook)

### Issue description

For some reason when I run a project (F5) I need to wait like 2-3 minutes for it to start. After that, first run it takes like 10-15 seconds to load every next time and there is white screen when loading. I can add GIF but...don't know if it will add anything to that issue. In Godot 3.4.2 it took like 1 sec.

### Steps to reproduce

Dunno it is global or not but I just created simple scene with one sprite. Nothing else.

**Comment by Zireael07** [comment] 2022-01-28 10:37
That's likely the shaders cache compiling the first time. It's a new feature in 4.0.

**Comment by seppoday** [comment] 2022-01-28 10:45
> That's likely the shaders cache compiling the first time. It's a new feature in 4.0.

Maybe. But if it is shader cache then it is very confusing. Because for 2-3 minutes project is not working and there is also 0 feedback from editor.

**Comment by Calinou** [comment] 2022-01-28 16:35
Duplicate of https://github.com/godotengine/godot-proposals/issues/3657.

**Closed by Calinou** 2022-01-28 16:35 UTC
Labels: bug, needs testing, performance

**Comment by nathanfranke** [comment] 2022-07-07 05:35
See also https://github.com/godotengine/godot/issues/43351
