### ISSUE TITLE
(4.0) Shortcuts problem -> TAB don't move cursor to next value in inspector and Ctrl + A (add node) sometimes don't work

### ISSUE THREAD

**Issue by seppoday** [godotengine/godot#57451] opened 2022-01-30 15:59 UTC
### Godot version

4.0 alpha 1.0

### System information

Windows 11

### Issue description

1. Pressing tab don't move cursor to next value in inspector. So if I want to change X and Y values I need to use my mouse. In 3.x it worked.
2. CTRL + A to add node sometimes don't work and I need to press it few times.

### Steps to reproduce

Just check in editor.

**Comment by Calinou** [comment] 2022-01-30 21:14
Duplicate of https://github.com/godotengine/godot/issues/54602 (fixed in `master`).

**Closed by Calinou** 2022-01-30 21:14 UTC
