### ISSUE TITLE
Unusable performance when enabling Per Pixel Transparency and Fullscreen

### ISSUE THREAD

**Issue by Nubilous** [godotengine/godot#35628] opened 2020-01-27 16:17 UTC
**Godot version:** 3.2 RC 4, 64-bit, OpenGL ES 2

**OS/device including version:** Windows 10, 64-bit, Geforce GTX 760

**Issue description:** On an empty project, when enabling Fullscreen and "Allowed" and "Enabled" for Per Pixel Transparency, FPS drops from several thousand to ~23. This does not happen in Godot 3.1.2.

**Steps to reproduce:** Start empty project, add empty 2D main scene, go to Project Settings -> Display -> Window, enable Fullscreen and Per Pixel Transparency "Allowed" and "Enabled". Run the game.

**Minimal reproduction project:**
[performance_bug.zip](https://github.com/godotengine/godot/files/4118039/performance_bug.zip)

**Comment by Calinou** [comment] 2020-01-27 17:19
This needs to be bisected to know which commit caused the regression. Can you test all older Godot 3.2 RCs, betas and alphas?

**Comment by bruvzg** [comment] 2020-01-27 18:55
It's probably related to the "v-sync via compositor" changes (per pixel transparency mode uses `UpdateLayeredWindow` instead of normal swap -  [os_windows.cpp#L2180-L2203](https://github.com/godotengine/godot/blob/master/platform/windows/os_windows.cpp#L2180-L2203)).

**Comment by akien-mga** [comment] 2020-01-27 19:10
I can confirm it on Windows, but it works fine on Linux.

It happens both when `VSync Via Compositor` is enabled or disabled, but it might still be related to the code changes that were done to support the option as mentioned by @bruvzg.

**Comment by bruvzg** [comment] 2020-01-27 19:22
Is it happening with v-sync disabled?

**Comment by akien-mga** [comment] 2020-01-27 20:13
> Is it happening with v-sync disabled?

Yes. (At least VSync off and VSync Via Compositor off.)

**Comment by bruvzg** [comment] 2020-01-28 08:18
I have done some tests and reviewed transparency code:

1. transparency is not compatible with full screen mode at all, and it's switching to borderless window when enabled.
2. v-sync via compositor doesn't work in windowed mode with transparency enabled (missing `DwmFlush` call in the swap code).
3. I'm getting same ~20 fps in 1440p borderless window mode in both 3.1.2 and 3.2.

Are you sure you are getting higher fps with 3.1.2, reproduction project doesn't show whether transparency is actually enabled, maybe it's not enabling it at all.

Here's test project with toggles that's using some transparent stuff to test it:
[_per_pix_tst.zip](https://github.com/godotengine/godot/files/4121265/_per_pix_tst.zip)

**Comment by Nubilous** [comment] 2020-01-28 10:41
I am not able to get low FPS using the onscreen options in the _per_pix_test project, but if I go to project settings and enable Fullscreen and both "Allowed" and "Enabled" for Per Pixel Transparency, I get low FPS in 3.2, but very high FPS (60 with vsync, ~2500 without vsync) in 3.1.2.

I should mention: once I do this in 3.1.2, I get a black (not transparent) fullscreen window, in 3.2 I do get a transparent (fullscreen) window.

Not sure if this is still relevant, but this issue appears as early as alpha1 (not sure how to test versions before that :)

**Comment by Zireael07** [comment] 2020-01-28 11:31
IIRC per pixel transparency wasn't really working in 3.1.2, since you're saying you get a black window, so you're comparing apples to oranges.

**Comment by bruvzg** [comment] 2020-01-28 12:29
Seems like it's just difference it the order in which 3.1 and 3.2 are handling contradictory `Fullscreen` and `Transp. Enabled` options:
- 3.1: full screen mode with transparency disabled
- 3.2: borderless with transparency enabled

BTW, what's the use case for full screen + transparency?

**Comment by Nubilous** [comment] 2020-01-28 12:51
For me there is no use case: I had a project where they were mistakenly enabled at the same time. I didn't notice this in 3.1.2, but took me some time to figure out why the performance for the same project in 3.2 was so abysmal. It would probably be good to not allow those options to be enabled at the same time?

**Comment by KoBeWi** [comment] 2020-12-17 00:39
Can anyone still reproduce this bug in Godot 3.2.3 or any later release?

I can't reproduce it, Windows 10 with GTX 1060

**Comment by bruvzg** [comment] 2021-03-30 09:13
Performance should be fixed by #38629.

**Closed by bruvzg** 2021-03-30 09:13 UTC
Labels: bug, confirmed, platform:windows, topic:rendering

**Comment by sian2005** [comment] 2021-11-10 17:06
With full screen enabled and using per pixel transparency the background is black, is this going to be fixed in later releases of Godot?
I actually need it :3

**Comment by Calinou** [comment] 2021-11-10 17:08
> With full screen enabled and using per pixel transparency the background is black, is this going to be fixed in later releases of Godot? I actually need it :3

This is already reported in https://github.com/godotengine/godot/issues/46958. The workaround is to use a window that's one pixel less tall than the desktop resolution. For example, on a 1920×1080 display, use a 1920×1079 borderless window.

**Comment by sian2005** [comment] 2021-11-10 17:35
Yeah, the one problem with that is that the taskbar (on windows) is above the window, and to keep it short, I don't want that with the thing I'm making. The only way I currently know of to prevent this is by full screening the window...
