### ISSUE TITLE
draw_polyline 

### ISSUE THREAD

**Issue by Spartan322** [godotengine/godot#34073] opened 2019-12-03 06:33 UTC
**Godot version:**
Mono 3.2 Beta 2

**OS/device including version:**
Manjaro Arch Linux "Juhraya" 18.1.2

**Issue description:**
draw_polyline draws the start and end points wider then the rest of the points.
![](https://cdn.discordapp.com/attachments/342056330523049988/651299486462902272/unknown.png)
This is using the draw_polyline_color function but it results in the same shape
![image](https://user-images.githubusercontent.com/4315446/70025690-c5a79680-156b-11ea-8a6e-eb600fb0313e.png)

**Steps to reproduce:**
* Add a `_draw` override to a CanvasItem
* Add `draw_polyline([Vector2(), Vector2(0, 100), Vector2(100, 100), Vector2(100, 0), Vector2(-25, 0)], Color.white, 50, false)`
* Have the node draw either in editor or in game

**Minimal reproduction project:**
[polyline_issue_project.zip](https://github.com/godotengine/godot/files/3914928/polyline_issue_project.zip)

It seems related to #16466, however the focus of this issue relates to an erroneous line shape for what would expectingly be a uniform drawing of lines.

**Comment by clayjohn** [comment] 2019-12-03 06:46
This is indeed a duplicate of https://github.com/godotengine/godot/issues/16466 can you copy your post here as a comment on that thread? It is much better for us to keep bug reports together instead of making multiple issues for the same bug.

**Closed by clayjohn** 2019-12-03 06:46 UTC
