### ISSUE TITLE
VB-style "With" statement for GDScript?

### ISSUE THREAD

**Issue by Sslaxx** [godotengine/godot#6300] opened 2016-08-27 10:40 UTC
**Issue description** (what happened, and what was expected):
As referred to in #6295 - as suggested by @vnen - including a "With" style statement in GDScript for syntactic sugar purposes.

**Link to minimal example project** (optional but very welcome):
https://github.com/godotengine/godot/issues/6295#issuecomment-242887120

**Comment by neikeq** [comment] 2016-08-27 14:51
Is this a duplicate of #1736, or are they two different things?

**Comment by bojidar-bg** [comment] 2016-08-27 16:35
@neikeq This is different, even though the two are somewhat mergable (I think we shouldn't anyway).

This one is about using `with` as a shorthand of `obj.x; obj.y; obj.z` -> `with obj: .x, .y .z` (or similar).
The other is about using `with` as a shorthand of `z = a(); if z != null: z.y` -> `with a() as z: z.y`.

**Comment by Sslaxx** [comment] 2017-12-20 15:15
While the new `$nodename` syntax makes things simpler, there is still a use-case for a `with` type statement.

```with $nodename:
        x ()
        y = z```

**Comment by akien-mga** [comment] 2017-12-20 16:44
That's a good example of why such sugar is bad practice IMO. How do you know if `$othernode.a` will evaluate to `self.get_node("othernode").a` or `self.get_node("nodename").get_node("othernode").a`? Given how `x`, `y` and `z` use the `with` statement, one could expect `$` and `get_node` to do the same.

**Comment by akien-mga** [comment] 2018-03-22 09:00
As per the above, I think this wouldn't be a good construct to add to GDScript. If anything, I'd prefer to keep the `with` keyword for a Python-like `with` as proposed in #1736.

**Closed by akien-mga** 2018-03-22 09:00 UTC
Labels: feature proposal, topic:gdscript, usability
