### ISSUE TITLE
Quick Open should sort search results prioritizing file names over folder names

### ISSUE THREAD

**Issue by hmans** [godotengine/godot#39645] opened 2020-06-18 13:43 UTC
This is vaguely related to #39184, but it's not the same issue.

**Godot version:**
3.2.1.stable

**OS/device including version:**
Currently Linux (Pop_OS), but I'm confident this also happens at least in Windows. (Haven't checked macOS.)

**Issue description:**
When using the filter input in Quick Open, it filters all available files by the phrase I've entered, which is great. But I believe it should also prioritize file name over path here. Example from my current project:

![image](https://user-images.githubusercontent.com/1061/85026728-539a4600-b179-11ea-8773-4339428ff540.png)

What I would have expected is that the scene actually named "Godot" to be prioritized. As it is now, Quick Open will just show an alphabetical list of filenames that have the search phrase anywhere in their path.

To clarify, the set of files listed in Quick Open after searching is correct, I would just expect them to be listed in a different order, with "Game.tscn" at the top.

(My workaround is to search for "game.", which whittles it down to just the Game scene. I still believe there is room for improvement here.)

**Steps to reproduce:**

- Open the attached demo project.
- Start "Quick Open" using Ctrl-Shift-O
- Enter "game" into the search input
- "Player.tscn" will now be the top selected entry, not "Game.tscn"

**Minimal reproduction project:**
[QuickOpenDemo.zip](https://github.com/godotengine/godot/files/4798906/QuickOpenDemo.zip)

**Comment by akien-mga** [comment] 2020-06-18 14:26
You should try 3.2.2 RC 1 ;)
![Screenshot_20200618_162458](https://user-images.githubusercontent.com/4701338/85032576-4896e400-b180-11ea-8b85-6db2b2c26e36.png)

Duplicate of #33504, fixed by #33578.

**Closed by akien-mga** 2020-06-18 14:26 UTC
Labels: enhancement, topic:editor, usability

**Comment by hmans** [comment] 2020-06-18 15:48
> You should try 3.2.2 RC 1 ;)

Haha, that's what I get for sticking with the stable version for the other game I'm working on... duh! :) Also, I'll work on my issue search-fu, I missed this one somehow, too. Once again sorry for the trouble. Thanks!
