### ISSUE TITLE
Project Manager: Intended directory change with enter opens a listed project in Import dialog

### ISSUE THREAD

**Issue by lmjk** [godotengine/godot#15601] opened 2018-01-11 17:50 UTC
**Godot version:**
2.1.4 and 3.0 beta 2

**OS/device including version:**
Fedora 27 (x86_64)

**Issue description:**
An already listed project is opened when you press enter to change directory path in the Import dialog. Pressing enter should result only in directory change.

**Steps to reproduce:**
In the Project Manager, first click on a project on the list. But then select Import, click on Browse (actually optional), write a non-importable path and press enter. Instead of opening the directory you entered and allowing you to proceed exploring the file system, Godot will open the listed project you clicked on earlier.

**Comment by ronroniv** [comment] 2018-05-14 07:58
I think this happens always when using any dialog window in Project Manager. It feels like the focus remains on project list regardless of whatever dialog you are using, so the list always takes away the enter key input.

**Comment by akien-mga** [comment] 2019-10-04 19:19
Duplicate of #17620

**Closed by akien-mga** 2019-10-04 19:19 UTC
Labels: bug, topic:editor
