### ISSUE TITLE
[4.0 beta-1] Can't assign node into exported Array[AnimatedSprite2D] in the inspector

### ISSUE THREAD

**Issue by Galaxyzeta** [godotengine/godot#66399] opened 2022-09-25 13:26 UTC
### Godot version

v4.0 beta-1 win64

### System information

Windows 11, Nvidia GTX1050ti, Vulkan

### Issue description

I have a scene tree like this:
```text
Node2D
L__  AnimatedSprite1
L__  AnimatedSprite2
```

I added a script on Node2D, with an exported typed array variable:
```gdscript
@export var animatedSprites: Array[AnimatedSprite2D] = []
```

Then I tried to make my child node `AnimatedSprite1` and `AnimatedSprite2 ` as items of the exported array, but nothing happened. 

Assigning the same node to an exported, non-array, statically-typed variable works, though.
```gdscript
@export var testAssign: AnimatedSprited2D
```

### Steps to reproduce

1. Create a scene, with Node2D as root node.
2. Add an AnimatedSprite2D  as child node.
3. Create a script, export a variable which type is Array[AnimatedSprite2D], and assign this script to the root node.
4. Reload the scene, in the inspector of the root node, click the newly exported field, and then click `Add Element`.
5. Click `Assign`, and choose AnimatedSprite2D node in the list, or just drag the node to the selection box.
6. Nothing happend.

https://user-images.githubusercontent.com/54425661/192146450-192ed1ac-49d3-422c-893b-51f2c385d9e5.mp4

### Minimal reproduction project

[BugReport.zip](https://github.com/godotengine/godot/files/9640848/BugReport.zip)

**Comment by Calinou** [comment] 2022-09-25 18:17
Duplicate of https://github.com/godotengine/godot/issues/62753.

**Closed by Calinou** 2022-09-25 18:17 UTC
