### ISSUE TITLE
core script built in custom nodes should not be not visible in scene tree

### ISSUE THREAD

**Issue by burstina** [godotengine/godot#28154] opened 2019-04-18 09:17 UTC
that's a proposal.

Let's build a custom node: we do a custom class into a custom script. It is ok.

Let's put this custom node in the tree. Editor add custom node and its custom script. That's ok.
Let's add _**many**_ of this custom nodes in the tree. Editor add all custom nodes in the tree, but associates each node to a single shared script. That _should_ ok.

Let's custom scripts fpr one or two of those custom nodes, now troubles begin because custom script is shared between custom nodes.

After few days, we want to look at custom nodes we have customized: we face new troubles, because usually we look for script icon near node icons, but all custom nodes have one. We have to look inside scripts, one by one, and figure out wich one we have customized. **That's no good**.

I hope I explained what the point is.

ciao
Graziano

**Comment by bojidar-bg** [comment] 2019-04-18 09:27
Duplicate of #6067 (or at least was discussed there).

**Closed by bojidar-bg** 2019-04-18 09:27 UTC
