### ISSUE TITLE
exported binaries don't run

### ISSUE THREAD

**Issue by lordadamson** [godotengine/godot#3212] opened 2016-01-03 02:15 UTC
Hi I compiled godot from source code and I'm trying to export the 2d platformer demo.
I'm using fedora 23.
So I export the binary and when I run it:
```
/home/adam/godot: /lib64/libssl.so.1.0.0: no version information available (required by /home/adam/godot)
/home/adam/godot: /lib64/libcrypto.so.1.0.0: no version information available (required by /home/adam/godot)
BOOT SPLASH:
BOOT SPLASH IS : 
ERROR: set_code_buffer: Condition ' version>5 ' is true. returned: ERR_INVALID_DATA
   At: modules/gdscript/gd_tokenizer.cpp:1061.
ERROR: operator[]: Condition ' p_index<0 || p_index>=size() ' is true. returned: aux
   At: core/vector.h:128.
Segmentation fault (core dumped)
```
you probably shouldn't worry about the first two lines (the ones that require libssl and stuff, I kind of handled it) I believe it's the part that comes after `BOOT SPLASH IS:`

**Comment by lordadamson** [comment] 2016-01-03 02:16
And when exported to windows, and run from the cmd the cmd says: `File too big to fit in memory`

**Comment by lordadamson** [comment] 2016-01-03 02:17
Note: I'm using the Godot Engine 2.0 ALPHA 10/30/2015 export templates on the website, but I'm running a custom build with the latest code on github.

**Comment by mohaalak** [comment] 2016-01-03 03:19
my problem exactly build the export from repo too , it will  solve your problem. 10/30/2015 template have problelms exporting .

**Comment by lordadamson** [comment] 2016-01-03 03:25
how do I build the export from repo @mohaalak ?

**Comment by Hinsbart** [comment] 2016-01-03 04:09
the same way you build the editor, just add `tools=no` and `target=release` to the parameters. You might have to rename the resulting binary to fit the template name.
Actually, I think the name is the only thing that matters to the exporter, so in theory you could also export editor builds (but don't do that :P).

**Comment by mohaalak** [comment] 2016-01-03 13:30
you can read it in wiki there is a detail for compiling for every platform.

**Comment by lordadamson** [comment] 2016-01-03 14:38
okay I guess the missing link for me now is. how do I do the actual export? :D 
I compiled with no tools and I have a godot binary. what should I name the binary? and how do I use it to export my program?

**Comment by akien-mga** [comment] 2016-01-03 14:58
I'm closing the issue as it's not a bug, you can't use a recent build of the engine with old templates, you need templates that match your build (same source code commit). But feel free to continue discussing how to build those templates yourself, I just close so that developers don't think it's a bug that needs fixing :)

**Closed by akien-mga** 2016-01-03 14:58 UTC

**Comment by vnen** [comment] 2016-01-03 15:53
@lordadamson you can replace the templates in `~/.godot/templates` keeping the same name. The names of the binaries are also described in the docs about compilation (e.g. [Compiling for Linux](http://www.godotengine.org/projects/godot-engine/wiki/Compiling_for_Linux)).

Another way is to set a Custom Binary in the Export dialog window. This is also described in the same documentation page about compiling.

**Comment by lordadamson** [comment] 2016-01-03 17:58
Okay so I compiled the template and places it in `~/.godot/templates` and exported my application and when I run that's what I get:
```
Godot Engine v2.0.alpha.custom_build (c) 2008-2015 Juan Linietsky, Ariel Manzur.
Usage: /home/adam/godot [options] [scene]
Options:
	-path [dir] : Path to a game, containing engine.cfg
	-test [test] : Run a test.
		(string, containers, math, render, particles, multimesh, gui, io, shaderlang, physics)
	-r WIDTHxHEIGHT	 : Request Window Resolution
	-p XxY	 : Request Window Position
	-f		 : Request Fullscreen
	-mx		 Request Maximized
	-vd DRIVER	 : Video Driver (GLES2)
	-ad DRIVER	 : Audio Driver (ALSA)
	-rthread <mode>	 : Render Thread Mode ('unsafe', 'safe', 'separate).)
	-s,-script [script] : Run a script.
	-d,-debug : Debug (local stdout debugger).
	-rdebug ADDRESS : Remote debug (<ip>:<port> host address).
	-fdelay [msec]: Simulate high CPU load (delay each frame by [msec]).
	-timescale [msec]: Simulate high CPU load (delay each frame by [msec]).
	-bp : breakpoint list as source::line comma separated pairs, no spaces (%20,%2C,etc instead).
	-v : Verbose stdout mode
	-lang [locale]: Use a specific locale
	-rfs <host/ip>[:<port>] : Remote FileSystem.
	-rfs_pass <password> : Password for Remote FileSystem.
ERROR: cleanup: ObjectDB Instances still exist!
   At: core/object.cpp:1853.
```

**Comment by akien-mga** [comment] 2016-01-03 18:04
That's the output when it does not find any project to load in the current directory (it shows the help output). You need either to place the exported binary next to the data.pck file, or specify a path with the -path switch.

**Comment by lordadamson** [comment] 2016-01-03 18:25
@akien-mga I'm not running the godot engine. I'm running the exported binary of my sample game. it shouldn't do that.

**Comment by lordadamson** [comment] 2016-01-03 18:25
and the data.pck is right besides it

**Comment by lordadamson** [comment] 2016-01-03 18:28
I tried to export with a single binary and that's what I got:
```
BOOT SPLASH IS : 
ERROR: set_code_buffer: Bytecode is too New! Please use a newer engine version.
   At: modules/gdscript/gd_tokenizer.cpp:1061.
ERROR: operator[]: Condition ' p_index<0 || p_index>=size() ' is true. returned: aux
   At: core/vector.h:128.
Segmentation fault (core dumped)
```

**Comment by akien-mga** [comment] 2016-01-03 18:28
>  I'm not running the godot engine. I'm running the exported binary of my sample game. it shouldn't do that.

Yes it should, the exported binary is also Godot engine, just without the editor, but it does have a -help output. My guess is that you are running from a directory that does not contain the data.pck. If you run ```/path/to/godot/executable``` but are not within ```/path/to/godot``` when doing so, it will fail. You need ```cd /path/to/godot && ./executable``` for example.

**Comment by akien-mga** [comment] 2016-01-03 18:29
> I tried to export with a single binary and that's what I got:

Your templates don't match your engine version (it should be the exact same commit).

**Comment by Hinsbart** [comment] 2016-01-03 18:31
Also, did you really build the export from git? I think building export binaries is broken right now(as in won't build at all)

**Comment by lordadamson** [comment] 2016-01-03 18:34
well it did build:
```
scons platform=x11 tools=no target=release bits=64
scons: Reading SConscript files ...
libevdev development libraries not found, disabling gamepad support
Enabling PulseAudio
scons: done reading SConscript files.
scons: Building targets ...
g++ -o bin/godot.x11.opt.64 platform/x11/godot_x11.x11.opt.64.o platform/x11/context_gl_x11.x11.opt.64.o platform/x11/os_x11.x11.opt.64.o platform/x11/key_mapping_x11.x11.opt.64.o platform/x11/joystick_linux.x11.opt.64.o main/libmain.x11.opt.64.a modules/libmodules.x11.opt.64.a bin/tests/libtests.x11.opt.64.a drivers/libdrivers.x11.opt.64.a scene/libscene.x11.opt.64.a servers/libservers.x11.opt.64.a core/libcore.x11.opt.64.a -lX11 -lXinerama -lXcursor -lssl -lcrypto -lfreetype -lasound -lpulse-simple -lpulse -lGL -lGLU -lpthread -lz
scons: done building targets.
```
```
commit 8fb70142e41ab09cd3c6fc3b4545a3be66276be8
Author: Juan Linietsky <reduzio@gmail.com>
Date:   Sat Jan 2 15:57:19 2016 -0300

    Ability to use opacity on distance field textures, fixes #2148
```

and I build both the engine and the export from that commit.

**Comment by Hinsbart** [comment] 2016-01-03 18:39
Alright, that commit is the last one with working exports, the next one broke it. You're lucky then^^
I will give it a try on that version

**Comment by akien-mga** [comment] 2016-01-03 18:39
Looks good yes. And just to make sure: you named the template "linux_x11_64_release" and when you export from within the editor you tick on 64bit and untick debug?

**Comment by lordadamson** [comment] 2016-01-03 18:45
shit I feel dumb. I didn't untick debug :| I'll try quickly and let you know.

**Comment by lordadamson** [comment] 2016-01-03 18:47
it did work now O.O
well thank you all for the awesome support :)) great project and a great community
