### ISSUE TITLE
Editor's Camera Pan didn't work in small scales.

### ISSUE THREAD

**Issue by vitorbalbio** [godotengine/godot#43467] opened 2020-11-11 23:38 UTC
**Godot version:**
Godot 3.2.3 Stable

**OS/device including version:**
Windows 10

**Issue description:**
When working with small scale scenes and zoomed camera the camera Pan did not work as should. Looks like it has a fixed real world threshold for minimum movement which didn't work in small scale scenes.

![wn0daWH4zm](https://user-images.githubusercontent.com/6172013/98876726-a42e7a80-245d-11eb-972e-29ad046f4b09.gif)

**Steps to reproduce:**
Create a scene
Zoom it
Try to pan

**Comment by Calinou** [comment] 2020-11-12 15:48
This is likely due to floating-point precision issues. Clamping the zoom value would help alleviate this.

**Comment by Zylann** [comment] 2020-11-14 01:50
Duplicate of https://github.com/godotengine/godot/issues/37034
I'm skeptical about the floating-point error though, that zoom doesnt seem high enough.

**Closed** 2020-11-14 02:13 UTC
Labels: bug, topic:editor
