### ISSUE TITLE
Incorrect subheading in export dialog when using the "Export all resources except resources checked below" export mode

### ISSUE THREAD

**Issue by yosimba2000** [godotengine/godot#76931] opened 2023-05-10 23:26 UTC
### Godot version

4.0.2

### System information

Windows 10 x64, 22H2

### Issue description

Not sure if this is a bug, but it's confusing

1) In Godot Export, go to Resources Tab.
2) Select dropdown option "Export all resources in the project except resources checked below".
3) Right below that, it says "Resources to Export", which is direct contrast to what is shown in Step 2

I have confirmed that checking the boxes does NOT export the files checked, as expected from Step 2.
So the line "Resources to export" should be changed to something like "Resources to NOT export"

![image](https://github.com/godotengine/godot/assets/61702289/b9ee4224-b53f-4e84-83f6-e01743bb3d21)

### Steps to reproduce

N/A

### Minimal reproduction project

N/A

**Comment by martinboue** [comment] 2023-05-11 12:50
Hi,

I want to contribute to the project and this issue might be a good start.

I think here is the code responsible of setting up the resources tab:
https://github.com/godotengine/godot/blob/fd4a06c51555904104b18494d0224f450d74fe2a/editor/export/project_export.cpp#L1176-L1190

The solution I'm considering is changing the `include_label` text according to the `filter_type` in the `_export_type_changed` method below.
https://github.com/godotengine/godot/blob/fd4a06c51555904104b18494d0224f450d74fe2a/editor/export/project_export.cpp#L686-L709

I can start working on a PR as soon as my local environment is ready 😃

**Comment by martinboue** [comment] 2023-05-11 13:59
This is my understanding of the desired outcome when selecting "Export all resources except resources checked below":
![image](https://github.com/godotengine/godot/assets/28391199/61bbaa3d-1789-4653-bb3d-0df59ebae8af)
I'm ready to work on a PR.

**Comment by eugene87222** [comment] 2023-05-11 15:19
#76705
Seems to be the same issue btw 😄

**Comment by Calinou** [comment] 2023-05-11 15:47
- Duplicate of https://github.com/godotengine/godot/issues/76705.

> I'm ready to work on a PR.

Feel free to open a pull request for this 🙂

**Closed by Calinou** 2023-05-11 15:47 UTC
Labels: bug, topic:editor, good first issue
