### ISSUE TITLE
Crash when trying to view 3D settings

### ISSUE THREAD

**Issue by Zephilinox** [godotengine/godot#8628] opened 2017-05-02 19:58 UTC
Latest (https://github.com/godotengine/godot/commit/5a6ccce97d350011b599e793cea95aa4e7899395), Windows 7 32-bit debug build

Clicking on View->Settings in the 3D tab causes a crash

![image](https://cloud.githubusercontent.com/assets/2060863/25636600/ce79d3ca-2f79-11e7-8ede-9b4a65cf249d.png)

**Comment by Ahmed0425** [comment] 2017-05-02 22:02
duplicated many times #8489 #8148 #8174 #7888 #8302 (black screen is relative to the bug btw)
and is being fixed now #8622 (although just a part of it was fixed for now)

**Comment by vnen** [comment] 2017-05-02 23:37
Closing as duplicate of #8489.

**Closed by vnen** 2017-05-02 23:37 UTC
