### ISSUE TITLE
Javascript as scripting language

### ISSUE THREAD

**Issue by jonorozcoc** [godotengine/godot#19294] opened 2018-05-31 16:30 UTC
I think it could be easier for people developing games on HTML5 to make games on Godot if it can have Javascript as programming language. It's pseudo-class oriented paradigm can help to organize programming workflow instead of learning a new language.

Thanks for you awesome work building this software.

**Comment by akien-mga** [comment] 2018-05-31 16:53
Duplicate of #937.

The consensus hasn't changed since then, and we don't need more languages supported officially, GDScript, VisualScript, C# and C (GDNative) are enough.

We wouldn't stop anyone from implementing JS support as community bindings though, like some are doing for Nim, D, Python, C++, Rust and others.

**Closed by akien-mga** 2018-05-31 16:53 UTC

**Comment by Ads20000** [comment] 2020-03-19 18:35
Sure enough (still in development): https://github.com/Geequlim/ECMAScript
