### ISSUE TITLE
Some icons are misaligned on certain font sizes

### ISSUE THREAD

**Issue by CptPotato** [godotengine/godot#31485] opened 2019-08-19 16:29 UTC
Godot version: 3.2 dev
System: Win 10, AMD graphics card

When I change the editor's font size some icons aren't scaled properly like the revert to default arrow:

![grafik](https://user-images.githubusercontent.com/3957610/63282423-13470e80-c2af-11e9-9379-f49c22eb1e2f.png)

This only happens on some font sizes such as 9, 12 or 16.

**Comment by akien-mga** [comment] 2019-08-20 11:19
CC @Calinou

**Comment by Calinou** [comment] 2019-08-20 11:43
Changing the font size doesn't change the icons' size:

![image](https://user-images.githubusercontent.com/180032/63344256-4e4d4e80-c350-11e9-922f-21649e3c8bf8.png)

Only changing the editor scale will. The issue must be elsewhere (e.g. the editor tries to draw the icons on coordinates not aligned with the display).

**Comment by KoBeWi** [comment] 2020-09-15 22:17
Can anyone still reproduce this bug in [Godot 3.2.3 rc6](https://godotengine.org/article/release-candidate-godot-3-2-3-rc-6) or any later release?
(I couldn't reproduce it)

**Comment by akien-mga** [comment] 2020-12-10 16:46
No answer, so closing. Please comment if you can still reproduce it, and make sure that an up-to-date reproduction project is included.

**Closed by akien-mga** 2020-12-10 16:46 UTC
Labels: bug, topic:editor, topic:rendering
