### ISSUE TITLE
Vulkan Mobile leaks RIDs on exit even in empty project (StorageBuffer, Framebuffer, Texture)

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot#89182] opened 2024-03-05 14:05 UTC
### Tested versions

- Reproducible in 4.3.dev (f9ebd84b5ace8d0e6a9c43c3403ecd9a4bcb132e), 4.3-dev1, 4.2.1-stable (didn't test earlier)

### System information

Fedora Linux 39 (KDE Plasma) - Wayland - Vulkan (Forward+) - dedicated AMD Radeon RX 7600M XT (RADV NAVI33) () - AMD Ryzen 7 7840HS w/ Radeon 780M Graphics (16 Threads)

### Issue description

When exiting the editor after editing a Vulkan Mobile project (empty new project included), the following leaks are reported:
```
WARNING: 1 RID of type "StorageBuffer" was leaked.
     at: _free_rids (./servers/rendering/rendering_device.cpp:5191)
 - RID:624587029086219
WARNING: 1 RID of type "Framebuffer" was leaked.
     at: _free_rids (./servers/rendering/rendering_device.cpp:5191)
 - RID:625025115750887
WARNING: 4 RIDs of type "Texture" were leaked.
     at: finalize (./servers/rendering/rendering_device.cpp:5344)
 - RID:625020820790930
 - RID:625033705692822
 - RID:625046590594712
 - RID:625059475496602
```

Running a 3D scene doesn't seem to trigger that leak, so it seems to be specific to the editor, possibly the default preview environment?

CC @godotengine/rendering 

### Steps to reproduce

- Create new project with Vulkan Mobile rendering method
- Open it from a terminal
- Close and see the leak report

### Minimal reproduction project (MRP)

Empty Vulkan Mobile project

**Comment by clayjohn** [comment] 2024-03-05 20:09
Marking as a good first issue. It might not be the best issue if you are a total beginner at open source and c++. This is more of a good first issue for someone who has a little bit of experience in open source and/or c++ and is looking for a good first task with Godot

What we need to do is identify what resources have been created that aren't freed at the end. Most likely everything will be within https://github.com/godotengine/godot/blob/master/servers/rendering/renderer_rd/forward_mobile/render_forward_mobile.cpp

Resource creation almost always follows the pattern of `***_create()` I.e. `framebuffer_create()` to create framebuffer

When exiting the engine, any resource created by the renderer should be freed in the destructor, You can see a few example there already:
https://github.com/godotengine/godot/blob/39f90600bc553f2273e72708eb2a8d37a8517e86/servers/rendering/renderer_rd/forward_mobile/render_forward_mobile.cpp#L2824

**Comment by sullyscience** [comment] 2024-03-12 02:28
I can take a look at this.

**Comment by sullyscience** [comment] 2024-03-15 18:39
It looks like that code was missed when the instance data was added to the mobile render (in [this](https://github.com/godotengine/godot/commit/51ed3aef63c0fdfc7666c004cc6d94dd15322d81#diff-fb99395dba48cfb81f7e21da2a4f1e99fda0391e279402bf910ccee6a54eca11) commit)

The texture and framebuffer leaks were caused by [RenderSceneBuffersRD::allocate_blur_textures()](https://github.com/godotengine/godot/blob/68ad520da4365c866ceea42e0238b2ea24647289/servers/rendering/renderer_rd/storage_rd/render_scene_buffers_rd.cpp#L504)

**Comment by BalmundSM** [comment] 2024-03-18 14:47
It seems this issue fixed by https://github.com/godotengine/godot/pull/89531. Why not close it?

**Comment by AThousandShips** [comment] 2024-03-18 14:48
Because it's not merged yet, it's not fixed yet :)

**Closed** 2024-03-24 00:28 UTC
Labels: bug, topic:rendering
