### ISSUE TITLE
GDScript 2.0: Reloading scripts works, but gives an error

### ISSUE THREAD

**Issue by neolith** [godotengine/godot#66593] opened 2022-09-29 11:22 UTC
### Godot version

v4.0.beta1.official [20d667284]

### System information

Windows 10

### Issue description

Reloading a script via `.reload()` throws an error:

```
E 0:00:00:0749   _ready: Attempt to open script '' resulted in error 'Can't open file'.
  <C++ Error>    Condition "err" is true. Returning: err
  <C++ Source>   modules/gdscript/gdscript.cpp:1064 @ load_source_code()
  <Stack Trace>  GameLogic.gd:88 @ evaluate()
                 GameLogic.gd:44 @ getPersistentModifiers()
                 GameLogic.gd:11 @ _ready()
```

The script seems to reload nonetheless and my game keeps running. The error code returned by `.reload()` is 0.

A bug report with a similar error is #66105, but I have no idea if the two are related.

### Steps to reproduce

1. Create a new script with `var script = GDScript.new()`
2. Set some content for the script with `script.set_source_code()`
3. Reload the script with `script.reload()`

**Comment by Rindbee** [comment] 2022-10-05 22:43
https://github.com/godotengine/godot/blob/57ffc4d82c773a513c8d122d859f07759c8c7da3/modules/gdscript/gdscript.cpp#L925
This line seems to treat an empty path as a built-in script, in fact built-in scripts also have non-empty paths, it seems that only the generated scripts have empty paths.

**Comment by adamscott** [comment] 2023-01-08 17:36
Could not reproduce on master (fcba87e). @akien-mga I suggest we close this issue.

### Minimal reproduction project
[66593.zip](https://github.com/godotengine/godot/files/10369066/66593.zip)

**Closed** 2023-01-08 20:11 UTC
Labels: bug, topic:gdscript, regression
