### ISSUE TITLE
Editor improvement for using tabs for more than just scenes

### ISSUE THREAD

**Issue by chucklepie** [godotengine/godot#30547] opened 2019-07-12 20:41 UTC
**Godot version:**
3.1.1 stable

**OS/device including version:**
Windows 10

**Issue description:**
Only scenes can belong to a new tab.

In the main IDE you get one tab per scene file, as many scenes as you want. However, all other files (script, help, etc) cannot be open in a new tab and instead sit in another pane as a 'history'. 

When you open a gd script file, or the help,  it opens up but the tab still has the name of currently open scene, even though the page has absolutely nothing to do with the scene.

Because of this, you lose massive screen space on your editor with the 'history', you cannot have two script files open at once, and you cannot have help window open either.

You get as many tabs for scenes as you like, but only one for literally everything else and they have to overwrite each other.

Suggestion: ditch the history (or put it as an optional view) and open every file as a new tab because I believe this is a fallback to a version of godot that possibly only had internal script files.

It would make so much more sense to be able to easily switch between tabs than use a history bar. When you have a larger project with multiple script files, this one tab for everything not a scene makes it impossible to code and does not scale.

Thanks.

**Comment by Zylann** [comment] 2019-07-12 20:45
> you cannot have two script files open at once

You can?

![image](https://user-images.githubusercontent.com/1311555/61157503-3501e880-a4ee-11e9-9592-e281b12e8bb1.png)

> You get as many tabs for scenes, but only one for everything else and they have to overwrite each other.

And for resources, you have this:

![image](https://user-images.githubusercontent.com/1311555/61157556-582c9800-a4ee-11e9-9284-0c083c484262.png)

In these cases, and even for scenes, you can open multiple of them at once, but only view one.

**Comment by rdckgames** [comment] 2019-07-12 20:49
I like this feature!

**Comment by chucklepie** [comment] 2019-07-12 20:49
![image](https://user-images.githubusercontent.com/12863685/61157660-b194c700-a4ee-11e9-9295-ddc018545381.png)


This script file has nothing to do with scene1, but it looks like it's part of scene 1.

Yes, that's exactly what I'm saying. Would you open up Visual Studio Code and only be allowed to have one tab?

Yes, they are vertical, but that's the point, it takes up loads of space when having them as tabs makes so much more sense. After all, if you follow that logic, why allow more than one scene to be open in a tab?

**Comment by Zylann** [comment] 2019-07-12 20:52
I think it's because scenes and scripts are different things. When you work on a script, it may or may not be part of that scene, sure, but having them separated would loose the concept of active scene (and all autocompletion coming from it).

**Comment by chucklepie** [comment] 2019-07-12 20:56
> I think it's because scenes and scripts are different things. When you work on a script, it may or may not be part of that scene, sure, but having them separated would loose the concept of active scene (and all autocompletion coming from it).

What about the help window? that is completely separate again, but resigned to living in the 'history' pane.

However, your comment is more an internal engine fault limiting the choice to the way it is now, rather than anything else?

Regarding your comment on part of a scene, there is another open bug stopping you from saving a script unless you have a scene (any scene, not even related) open.

**Comment by Zylann** [comment] 2019-07-12 21:04
> What about the help window? that is completely separate again, but resigned to living in the 'history' pane.

Help could be separated yes, because it really has no relation with current scene and scene.

> However, your comment is more an internal engine fault limiting the choice to the way it is now, rather than anything else?

It's not an engine fault, it's just the way it was designed. Opening scene1 and editing scene2 code doesnt seem like a problem to me. I don't always want to open scene2 just to edit its script.

> As an aside, you're saying if I have scene1.tscn file open, go to my history and open scene2.gd it takes its auto complete history from scene1? that is just wrong ;-)

It might take completion from scene1 if that script is found in the active scene. If not, that won't be.

> Regarding your comment on part of a scene, there is another open bug stopping you from saving a script unless you have a scene (any scene, not even related) open.

Some of these issues were from me, and there is a subtility: by default, Ctrl+S is NOT saving the current script, it actually saves the current scene (which THEN saves all resources referenced in it, including scripts). It is a GLOBAL shortcut, it's not contextual, so it also runs even if you have the script editor focused. As a result, no scene open prevents you from saving a script. 
For that very reason, I changed my shortcut so that it maps to the `Save Script` action instead. I also suggested that we made such shortcut contextual, so that it would save the resource related to the focused editor.

**Comment by chucklepie** [comment] 2019-07-12 21:10
tbh, I didn't even know ctrl+alt+s was save script and your suggestion of a context save is much better.

If I have a global script file for singleton use, surely that does not have be part of a scene to be edited?

But if autocomplete really does take its objects from the current scene, that's just wrong and liable to fail (my example of opening scene2.gd from history but scene1.tscn is open).

Most other IDE's keep a database of objects (e.g. pdb in visual studio) not just details of the current active form.

**Comment by Zylann** [comment] 2019-07-12 21:16
> If I have a global script file for singleton use, surely that does not have be part of a scene to be edited?

Yes, in fact scripts don't need to be part of a scene to even exist. You can write a script which inherits nothing and contains only helper functions. Or even a script inheriting `Resource` to create a custom one.

> But if autocomplete really does take its objects from the current scene, that's just wrong and liable to fail (my example of opening scene2.gd from history but scene1.tscn is open).

The open scene provides context. The context may change depending on which scene you work on. You can keep a database around so you don't need to have the scene open (i.e look in database if not found in active scene), but you still need to deal with the case where the script is found in more than one scene.

**Comment by kruglinski** [comment] 2019-07-15 02:28
The simple "Brute force" method to achieve this, is to open the engine editor multiple times, work complete separately, and only debugging, testing in the first engine editor instance

**Comment by mhilbrunner** [comment] 2020-05-28 15:25
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!

**Closed by mhilbrunner** 2020-05-28 15:25 UTC
Labels: feature proposal, topic:editor, usability

**Comment by starry-abyss** [comment] 2021-07-22 23:44
Related: https://github.com/godotengine/godot-proposals/issues/1895
