### ISSUE TITLE
Blender importer adds long suffix to root node name

### ISSUE THREAD

**Issue by rcorre** [godotengine/godot#84025] opened 2023-10-26 21:44 UTC
### Godot version

4.2.beta.custom_build.50d17f6b8

### System information

Linux 6.5.8-arch1-1

### Issue description

Root nodes of files imported using the blender importer have a hash after the name, e.g. Character-e1c248ae26fc8808362fd6c8fbab07b3. I don't have the same issue with a .glb import of the same file.

### Steps to reproduce

1. Open the project
2. Open the blend file in Godot
3. Note the root name has a long suffix
4. Open the .glb file
5. Note the root name does not have a long suffix

### Minimal reproduction project

[example.zip](https://github.com/godotengine/godot/files/13183145/example.zip)

**Comment by Shigewara** [comment] 2023-10-28 23:06
Have same issue on 4.2 Beta 3 on Windows 10 x64

**Comment by rcorre** [comment] 2023-11-03 21:46
As a workaround, you can set RootName in the import options.

**Comment by fire** [comment] 2023-11-06 01:34
Looking into it

**Comment by akien-mga** [comment] 2023-11-09 15:49
I wrongly assumed that this would be a regression, I checked in earlier dev snapshots and in 4.0-stable, 4.1-stable and 4.1.3-stable, they all behave the same. So it's not critical for the 4.2 release.

**Comment by akien-mga** [comment] 2023-11-09 15:57
Tested intermediate 4.2 dev/beta snapshots.

The regression was introduced in 4.2-dev5 (dev4 doesn't have the bug).

Didn't bisect further but #80272 sounds possibly related, CC @aaronfranke.

**Comment by aaronfranke** [comment] 2023-11-09 18:48
This was caused by #79774, not #80272. I opened #84678 to fix this, and did a thorough investigation.

**Closed** 2023-11-09 19:11 UTC
Labels: bug, confirmed, topic:import, regression, topic:3d
