### ISSUE TITLE
app crashes when adding a new folder or changing files around the project.

### ISSUE THREAD

**Issue by Merzzyg1** [godotengine/godot#94639] opened 2024-07-22 22:03 UTC
### Tested versions

-reproducible ins v4.3.beta3.official [82cedc83c]. not reproducible in v4.3.beta.2.official 

### System information

Godot v4.3.beta3 - Android - Vulkan (Mobile) - integrated Adreno (TM) 740 -  (8 Threads)

### Issue description

when i try to make a new folder it just crashes on me. i have also tried with swapping files around. (ignore how long it took to press the options)

https://github.com/user-attachments/assets/dfb8bfb1-4e34-4de1-83c1-00056113b6fe

### Steps to reproduce

open app, make a new folder in any directory = crash

### Minimal reproduction project (MRP)

as i was writting this i tried to export and it just keeps crashing when i open the app so yeahhh.
i tried to compress but the file ended up being 75 mb so i uploaded it to mediafire idk if thats ok or not but heres the link: https://www.mediafire.com/file/0h64m0ww464ygay/MRP.zip/file

**Comment by Merzzyg1** [comment] 2024-07-22 22:09
Adding into this.  i just downloaded this version v4.3.beta2.official [b75f0485b] and it seems to work fine. i dare say this version feels faster than the other one i stated. .

**Comment by akien-mga** [comment] 2024-07-23 14:07
Tested on a Google Pixel 7a and I can't reproduce the crash. But I do see that creating a new folder trigger a rescan of all files in the FileSystem dock. That sounds like #94416.

Maybe the crash in your end is because your phone is less powerful and rescanning/reimporting 3D meshes might be too heavy for the GPU?

**Comment by Merzzyg1** [comment] 2024-07-23 14:11
> Tested on a Google Pixel 7a and I can't reproduce the crash. But I do see that creating a new folder trigger a rescan of all files in the FileSystem dock. That sounds like #94416.
> 
> Maybe the crash in your end is because your phone is less powerful and rescanning/reimporting 3D meshes might be too heavy for the GPU?

Might be im going to check if it happens in a new project without 3d characters

**Comment by Merzzyg1** [comment] 2024-07-23 14:59
> Tested on a Google Pixel 7a and I can't reproduce the crash. But I do see that creating a new folder trigger a rescan of all files in the FileSystem dock. That sounds like #94416.
> 
> Maybe the crash in your end is because your phone is less powerful and rescanning/reimporting 3D meshes might be too heavy for the GPU?

following up i have record both versions 4.3.2 and 4.3.3. i also had a recording of version 4.3.3 with a project with no files but that one was too large for github. to sumorise that video it worked flawlessly as expected so nothing interesting. 

Here is the video of version 4.3.2

https://github.com/user-attachments/assets/c83350f3-df96-45e5-914e-96c5731e60b7

in the video you can see how its running smoothly and the new folder was added quickly. 

Here is the video of version 4.3.3

https://github.com/user-attachments/assets/a61b09f7-310f-46a2-827d-133cf6f59453

i wasnt able to screen record the loading process because of file sizes (both videos were the same lenght but this one was 26 mbs... idk how) but it shows the app crashing for no reason. in both videos it was the same project which means its aproblem in 4.3.3 and after reading #94416  it might be connected. I believe my phone is capable to run the app so its a problem built in the newer version.

**Comment by Merzzyg1** [comment] 2024-07-23 19:36
> > Tested on a Google Pixel 7a and I can't reproduce the crash. But I do see that creating a new folder trigger a rescan of all files in the FileSystem dock. That sounds like #94416.
> > 
> > Maybe the crash in your end is because your phone is less powerful and rescanning/reimporting 3D meshes might be too heavy for the GPU?
> 
> following up i have record both versions 4.3.2 and 4.3.3. i also had a recording of version 4.3.3 with a project with no files but that one was too large for github. to sumorise that video it worked flawlessly as expected so nothing interesting. 
> 
> Here is the video of version 4.3.2
> 
> https://github.com/user-attachments/assets/c83350f3-df96-45e5-914e-96c5731e60b7
> 
> in the video you can see how its running smoothly and the new folder was added quickly. 
> 
> Here is the video of version 4.3.3
> 
> https://github.com/user-attachments/assets/a61b09f7-310f-46a2-827d-133cf6f59453
> 
> i wasnt able to screen record the loading process because of file sizes (both videos were the same lenght but this one was 26 mbs... idk how) but it shows the app crashing for no reason. in both videos it was the same project which means its aproblem in 4.3.3 and after reading #94416  it might be connected. I believe my phone is capable to run the app so its a problem built in the newer version.
> 
> 

adding to this in version v4.3.beta2.official [b75f0485b] @export variables are currently not changing the values in the code when changed throught the ui. 
should i make a new issue report on this?

![Screenshot_20240723_203609.jpg](https://github.com/user-attachments/assets/7d373c4e-7c21-4def-993a-41e8df36b39a)

**Comment by akien-mga** [comment] 2024-07-24 10:57
Could you test this build from #94691?
https://github.com/godotengine/godot/actions/runs/10074692377/artifacts/1734400150

This should include an apk of the Android editor which you can sideload on your phone manually.

It should solve the problem of always reimporting files on any filesystem operation, which would be a duplicate of #94416.

What I'm still unsure of is why this reimport triggers a crash in your case. The crash might be a different bug, and might be reproducible in the "fixed" build or 4.3.beta2 if you delete the `.godot` folder to force a full reimport. Could you test that?

**Comment by Merzzyg1** [comment] 2024-07-24 11:20
> Could you test this build from #94691?
> https://github.com/godotengine/godot/actions/runs/10074692377/artifacts/1734400150
> 
> This should include an apk of the Android editor which you can sideload on your phone manually.
> 
> It should solve the problem of always reimporting files on any filesystem operation, which would be a duplicate of #94416.
> 
> What I'm still unsure of is why this reimport triggers a crash in your case. The crash might be a different bug, and might be reproducible in the "fixed" build or 4.3.beta2 if you delete the `.godot` folder to force a full reimport. Could you test that?

i have tried the build you sent me and it works now theres no crashes. it loads smoothly and deletes smoothly. changing folder names reloads without a problem. i also tried what you said about deleting the .godot file to force a reload of the full project and it realoaded with no problems whatsoever. conclusion the new build works.

**Comment by akien-mga** [comment] 2024-07-24 13:51
Thanks for testing! I'll close this as duplicate of #94416 and thus resolved by #94691.

The crash is worked around but the root cause for it might not be fixed yet. We'll have to see when fixing #94416 properly if we understand what could cause a crash on reimport.

**Closed by akien-mga** 2024-07-24 13:51 UTC
Labels: bug, topic:editor, needs testing, crash, regression
