### ISSUE TITLE
missing icons for path/curve editing

### ISSUE THREAD

**Issue by henkz1** [godotengine/godot#5228] opened 2016-06-15 15:05 UTC
**Operating system or device - Godot version:**

Ubuntu 16.04, https://github.com/godotengine/godot/commit/1899f7f28d814193a04b50fe51c5494f0eb14813
**Issue description** (what happened, and what was expected):
When editing paths(Path and Path2D) editor displays the buttons with "error".

Path2D:
![image](https://cloud.githubusercontent.com/assets/17125468/16084565/986bc444-3319-11e6-86e0-b9a4b0cdca67.png)
Path:
![image](https://cloud.githubusercontent.com/assets/17125468/16085058/1a7658e0-331b-11e6-8796-1f0562eb531e.png)

**Comment by akien-mga** [comment] 2016-06-15 15:13
Are you using HiDPI?

**Comment by henkz1** [comment] 2016-06-15 17:01
@akien-mga No using LoDPI, I tried HiDPI as well and icons were missing there too

**Comment by djrm** [comment] 2016-06-15 18:10
This is weird, the icons are there, but not visible, i can confirm the problem

**Comment by akien-mga** [comment] 2016-06-15 18:18
Do they have names that differ from what the editor expect?

**Comment by djrm** [comment] 2016-06-15 18:40
no, everything is the same, this is weird, im bisecting

**Comment by djrm** [comment] 2016-06-15 18:54
the problem is here c1056a9bfb723d053c3bec9d9f8d84ecdc5e93f9

**Comment by djrm** [comment] 2016-06-18 21:24
@akien-mga fixed this one a while ago, mind to check, its a trivial fix

**Comment by akien-mga** [comment] 2016-06-18 21:41
Yeah I just haven't merged it yet because I don't understand it :) So I wanted @reduz to have a look at it to ensure that it's not a broader bug that might affected other editor plugins.

**Closed** 2016-06-18 22:17 UTC
Labels: bug, topic:editor

**Comment by SuperUserNameMan** [comment] 2016-07-13 11:49
okay, so i'm not going to open a new issue.

just to mention that 2.0.4.1 is affected too.

![2 0 4 1_spatial_path_button_icons](https://cloud.githubusercontent.com/assets/9801802/16802356/9cf1bc10-4900-11e6-93fe-f6bde49db2c5.png)
