### ISSUE TITLE
Unusual FileSystem behavior when creating new assets in folders

### ISSUE THREAD

**Issue by Anheurystics** [godotengine/godot#5674] opened 2016-07-13 12:40 UTC
Window 10 64-bit, Godot 2.1 beta

Creating a new asset (ie. scene) and saving it in a new folder makes the FileSystem not synchronize correctly and act weird. For example, creating a scene called Control.tscn and saving it in a new folder called "test" brings this up in the FileSystem:
![godot_2016-07-13_20-36-30](https://cloud.githubusercontent.com/assets/6197645/16803618/fce4135a-4939-11e6-93c9-5ae43940a04e.png)

Re-opening the project in the editor fixes this, however.

**Comment by bojidar-bg** [comment] 2016-07-13 14:24
Duplicate of #3662

**Closed by bojidar-bg** 2016-07-13 14:24 UTC
Labels: archived
