### ISSUE TITLE
godot freezing even some time  godot freez my fulll laptop

### ISSUE THREAD

**Issue by devendra618** [godotengine/godot#39310] opened 2020-06-05 03:24 UTC
ubuntu 18.04.4
ram 8 gb
![Screenshot from 2020-06-05 08-54-26](https://user-images.githubusercontent.com/45286465/83833712-32157500-a70a-11ea-9620-ad1156f1da9f.png)

**Comment by Calinou** [comment] 2020-06-05 07:52
Duplicate of #18871. Unfortunately, we still don't have a "definite" hardware setup or reproduction steps for this bug.

**Closed by Calinou** 2020-06-05 07:52 UTC

**Comment by devendra618** [comment] 2020-06-05 08:14
what can I do to fix that bug

**Comment by Calinou** [comment] 2020-06-05 08:19
@devendra618 Which graphics card model do you have? Try upgrading to a more recent Linux distribution. It might fix bugs in graphics drivers.

**Comment by Zireael07** [comment] 2020-06-05 09:21
@Calinou: Again, an Ubuntu user affected. I'm definitely seeing a trend, and thinking it's less hardware and more software...

**Comment by Calinou** [comment] 2020-06-05 09:39
@Zireael07 Many people have reported the same issue on Windows, so I'm not so sure about that.

**Comment by devendra618** [comment] 2020-06-05 10:28
![Screenshot from 2020-06-05 15-57-01](https://user-images.githubusercontent.com/45286465/83866322-49258880-a745-11ea-8fda-80f7c798b6c0.png)
i have two graphics card
