### ISSUE TITLE
Godot 4 freezes 3/4 times when renaming an audio bus

### ISSUE THREAD

**Issue by nightblade9** [godotengine/godot#74970] opened 2023-03-16 03:21 UTC
### Godot version

4.0.0 official binaries, .NET flavour.

### System information

Manjaro (Arch) with KDE Plasma; GPU = NVIDIA Corporation TU117M [GeForce GTX 1650 Ti Mobile] (rev a1)

### Issue description

When I rename an audio bus (newly created or previously created and saved), the editor freezes.

Appears to be a regression, as I never had this issue with 3.5.1. BUT, it could also be a GPU issue (I noticed a few visual glitches in 4.0.0 compared to 3.5.1)

### Steps to reproduce

- Create a new or open any existing project
- Click on the Audio tab
- Click Add Bus
- Try to rename the new bus by typing "SFX"

Expected: 3/4 times, the editor froze:

- twice after I pressed enter
- once after I typed F, before I typed X

### Minimal reproduction project

Works on any project.

**Comment by stmSi** [comment] 2023-03-16 06:51
I can't reproduce this.. i have almost same setup as you too. Manjaro, KDE, 2060 RTX... but i am testing this in 4.0 with no .NET

**Comment by timothyqiu** [comment] 2023-03-16 07:19
Duplicate of #74374

Should have already been fixed in 4.0.1.rc1.

**Closed by timothyqiu** 2023-03-16 07:19 UTC
Labels: bug, topic:audio, regression
