### ISSUE TITLE
Touch event not being registered on Wacom Cintiq

### ISSUE THREAD

**Issue by UgisBrekis** [godotengine/godot#11586] opened 2017-09-25 21:12 UTC
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Godot v3.0 alpha custom build, Windows 10 PC + Wacom Cintiq tablet

**Issue description:**

Godot doesn't recognize touch events when using Wacom Cintiq, meaning it prints out that the input event is left mouse button or mouse motion.  What makes it weirder is that godot also doesn't fire any event when I press the finger on the screen, I actually have to move it, only then the console prints that the left mouse button was pressed and motion event happened.

So the issue is that the touch event doesn't get recognized as touch event, instead it gets recognized as a left mouse button event, and also "pressed" and "released" states get printed out both only after finger was released from the screen, instead of printing "pressed" when finger was pressed and "released" when finger was released off the screen.

**Steps to reproduce:**
Just to clarify it:
1)I press on the screen -nothing happens
2a)I release the finger off the screen - console prints that the left mouse button was pressed and released
2b)I drag the finger - console prints that the left mouse button was pressed and mouse motion happened

**Link to minimal example project:**

**Comment by vnen** [comment] 2017-11-14 01:31
May be related to #8028.

**Comment by KoBeWi** [comment] 2018-06-15 14:45
Eh, I had similar issue recently, not sure if it fits here.

Godot 3.0.2 worked fine on Wacom tablet (also Win10), but 3.0.3 broke it with this new "universal translation of touch to mouse". The device is recognized as desktop probably, so touch controls are automatically disabled. Going into options to enable touch would fix this, but you know, it's hard to do if I can't click anything :/

**Comment by LikeLakers2** [comment] 2018-06-15 23:03
I get the feeling this might be related to the issue I made, #19586.

**Comment by UgisBrekis** [comment] 2018-06-18 21:19
3.0.3 definitely broke something and it's worse now- none of Wacom Cintiq touch event are registered.

**Comment by akien-mga** [comment] 2018-06-18 21:20
CC @RandomShaper

**Comment by RandomShaper** [comment] 2018-06-19 22:16
This should have an easy fix. I'll look into it tomorrow.

In the meantime, could anyone setup a simple project that dumps input events to check if the engine at least receives touch input from Wacom devices although the editor UI doesn't react to them?

**Comment by RandomShaper** [comment] 2018-06-19 22:18
Maybe when this is sorted out, the original issue will be fixed as well.

**Comment by UgisBrekis** [comment] 2018-06-20 13:21
Thanks @RandomShaper for looking into this. I'm gonna prepare a simple demo later today.

**Comment by UgisBrekis** [comment] 2018-06-20 21:58
Ok, made a small project, however it gets weird: touch events are registered, but the index property is completely off: event.index should indicate which finger triggered the event, however I get the values of what it seems to be event id. After restarting Godot, these values are not started from 0, but continue from where they left off in the previous session. 
[WacomCintiqTouch.zip](https://github.com/godotengine/godot/files/2121251/WacomCintiqTouch.zip)

**Comment by RandomShaper** [comment] 2018-06-21 19:09
Could someone try with #19708?

**Comment by RandomShaper** [comment] 2018-06-23 11:02
Here is [a prebuilt Godot 3.0.4 + #19708 for Windows, x64](https://drive.google.com/open?id=1Bj3XM4jwUzWBDr1vQeGJaTpV0z8GiOlE) so you affected users can test if/how the issue is still present after the intended fix.

**Comment by KoBeWi** [comment] 2018-06-27 19:39
Tested to work on Wacom Mobile Studio Pro 13 (Windows 10).

**Closed** 2018-07-03 13:41 UTC
Labels: bug, topic:core
