### ISSUE TITLE
AnimationPlayer and cubic interpolation

### ISSUE THREAD

**Issue by Torguen** [godotengine/godot#79067] opened 2023-07-05 15:55 UTC
### Godot version

v3.6.beta2.official [68c507f59]

### System information

w10 64

### Issue description

The animation player node keeps changing the size of the node when the timeline is between two keys that are duplicates.
AnimationPlayer should not change the size of the sprite node.

This happens much more pronounced in my project (in the attached test it is less pronounced).
Watch the video... how can I fix this?

https://github.com/godotengine/godot/assets/19652075/c92e7391-4663-4490-9a83-69ddc27f9153

### Steps to reproduce

Just move the timeline between the two duplicate keys and you will see that the node keeps changing its size but the two keys indicate the same size.

### Minimal reproduction project

[testAnimPlayer.zip](https://github.com/godotengine/godot/files/11959817/testAnimPlayer.zip)

**Comment by TokageItLab** [comment] 2023-07-07 05:02
Dupe of https://github.com/godotengine/godot/issues/57952

**Closed by TokageItLab** 2023-07-07 05:02 UTC
Labels: topic:animation
