### ISSUE TITLE
Local To Scene in Resourcecs does not behave as expected.

### ISSUE THREAD

**Issue by wyattbiker** [godotengine/godot#64175] opened 2022-08-09 18:33 UTC
### Godot version

v4.0.alpha13.official [59dcddc45]  and v3.5

### System information

Mac OS X (Catalina) 10.15.7

### Issue description

Local To Scene in Resources chcked flag is ignored when you make a Duplicated node

### Steps to reproduce

Both in 3.5 and 4.0

1. Create a Node2D scene
2. Add a RigidDynamicBody2D  (or RigidBody2D)
3. Add a CollisionShape2D shape with RectangleShape2D.
4. Check the Local To Scene under Resources.
5. Make a duplicate of the RigidDynamicBody2D and move it out of the way.

If you try to resize the collision shape it will resize in both nodes.

### Minimal reproduction project

[LocalToScene3.5.zip](https://github.com/godotengine/godot/files/9293784/LocalToScene3.5.zip)

**Comment by KoBeWi** [comment] 2022-08-09 21:04
Duplicate of #45350
`local_to_scene` takes effect when node is being instanced from PackedScene, not during duplication.

**Closed by KoBeWi** 2022-08-09 21:04 UTC
