### ISSUE TITLE
GLES2 [visual] shader shows pixelated texture on Android

### ISSUE THREAD

**Issue by wombatwingdings** [godotengine/godot#41107] opened 2020-08-07 16:00 UTC
**Godot version:**
Godot 3.2.3.rc custom build as of 6 August 2020
SHA-1: 23b553ba0603161346526e1821bff5002520173c

**OS/device including version:**

GLES2 Android 
Motorola G6 Play - Adreno 505

**Issue description:**

Using Visual Shader to modify uv of Texture to scale the image causes massive pixelation problem on Android. 

Windows
![windows](https://user-images.githubusercontent.com/36036908/89664560-3f4c0d00-d8cf-11ea-96be-72a431dad16f.png)
Android
![android](https://user-images.githubusercontent.com/36036908/89664571-42df9400-d8cf-11ea-9eaa-17f631b35ebb.png)

**Steps to reproduce**
![VisualShader](https://user-images.githubusercontent.com/36036908/89665121-137d5700-d8d0-11ea-9ebd-f894260e137a.PNG)

**Minimal reproduction project:**

[GLES2textureProb.zip](https://github.com/godotengine/godot/files/5042446/GLES2textureProb.zip)

**Comment by clayjohn** [comment] 2020-08-07 17:59
Duplicate of https://github.com/godotengine/godot/issues/32813

Fixed by 
https://github.com/godotengine/godot/pull/33646

In your project settings tick the box next to ``rendering/gles2/compatibility/enable_high_float.android``. that should solve your issue. :)

**Closed by clayjohn** 2020-08-07 17:59 UTC
Labels: bug, platform:android, topic:rendering, topic:shaders

**Comment by wombatwingdings** [comment] 2020-08-07 19:38
@clayjohn You are the man! Thank you so much!
