### ISSUE TITLE
In 4.0 it is not possible to edit nodes such as FileDialog or AcceptDialog in the editor

### ISSUE THREAD

**Issue by marzecdawid** [godotengine/godot#68577] opened 2022-11-12 20:40 UTC
### Godot version

4.0.beta4

### System information

Windows 10 21H2, Vulkan, AMD Radeon RX 6750 XT (31.0.12029.1042)

### Issue description

In Godot 4.0 you can no longer edit nodes in the Viewport category in the editor, it was previosly possible in the 3.5.1

[Video showing the problem](https://www.youtube.com/watch?v=AlUapT1rtpI)

### Steps to reproduce

1. Add any node under Viewport category
2. Change the visibility of the node so it is visible in the editor
3. Try to grap the node or change its size in the editor.

**Comment by adamscott** [comment] 2022-11-12 20:55
Please upload directly your video in the issue itself. (you can drag the video file in the markdown editor of the issue)

**Comment by marzecdawid** [comment] 2022-11-12 21:18
@adamscott The video was to large in size for that.

**Comment by KoBeWi** [comment] 2022-11-12 22:07
Well the "bug" is pretty obvious. These nodes are no longer Controls and they don't have editor implemented. So we either need to write a new editor for Window-based nodes or somehow adapt CanvasItem editor to support them.

Pretty sure this was already reported somewhere, but I can't find it >_>

**Comment by Rindbee** [comment] 2022-11-13 10:51
Duplicate of #56872.

**Closed** 2022-11-13 11:53 UTC
Labels: topic:editor, usability, topic:gui
