### ISSUE TITLE
Sprite 3D node renders behind AnimatedSprite 3D.

### ISSUE THREAD

**Issue by ca3games** [godotengine/godot#30394] opened 2019-07-07 03:51 UTC
![Captura de pantalla de 2019-07-06 22-48-30](https://user-images.githubusercontent.com/19626687/60763740-69822a00-a040-11e9-996a-df8b896e2157.png)

As you can see, even if both the animatedSprite node and the Sprite node are set to opaque pre pass, if Sprite 3D has transparency it usually has issues like rendering behind the animated Sprite 3D.
If the Sprite material is set to transparency off, this issue dissapears, but you lose the transparency on the sprite.

EDIT: Attached Demo: [Demo.zip](https://github.com/godotengine/godot/files/3365703/Demo.zip)

**Comment by clayjohn** [comment] 2019-07-07 05:23
Can you provide more information? What version are you using? Is this GLES2 or GLES3?

**Comment by ca3games** [comment] 2019-07-07 14:03
> Can you provide more information? What version are you using? Is this GLES2 or GLES3?

Attached demo of the issue.

**Comment by clayjohn** [comment] 2019-07-07 15:18
Duplicate of https://github.com/godotengine/godot/issues/27141, fixed by https://github.com/godotengine/godot/pull/28520

This issue is already fixed in master. And will be includes in releases 3.1.2 and 3.2+.

In the future please fill out the bug report template. If I had known you were using 3.1 and GLES2 I could have told you right away that the issue was already resolved.

**Closed** 2019-07-07 15:18 UTC
Labels: archived
