### ISSUE TITLE
Opening a directory should cancel searching in file system dock

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#24073] opened 2018-11-29 23:51 UTC
Let's say your project looks like this:
![image](https://user-images.githubusercontent.com/2223172/49259397-81098c80-f439-11e8-9c34-36b317e55bbd.png)

You now search for a specific file:
![image](https://user-images.githubusercontent.com/2223172/49259418-91216c00-f439-11e8-91e8-931b4171e4c8.png)

It shows in the tree that there are two files that match your search. Now you are interested in the "new folder", where the Spatial.tscn lies. You double-click the new folder and you see this:
![image](https://user-images.githubusercontent.com/2223172/49259451-b4e4b200-f439-11e8-9a0b-2b291d0530fa.png)

I'd rather expect the contents of the directory, not search results in a different view. So the search should be automatically cancelled in this case IMO.

**Comment by akien-mga** [comment] 2018-12-02 15:57
Marking as bug since the folder view should not show `Spatiaal.tscn` since it's not contained in that folder. Whether or not it should keep the filter and only shows files matching the filter *within the selected folder*, or discard the filter, is up for discussion. I guess discarding the search filter may indeed make sense.

**Comment by groud** [comment] 2018-12-02 19:15
This is no more reproducible, opening a folder via double-click it in the tree is now deactivated.

**Comment by akien-mga** [comment] 2018-12-02 20:48
Which shows again why we have an issue template that asks for the Godot version...

**Closed by akien-mga** 2018-12-02 20:48 UTC
Labels: bug, topic:editor, usability
