### ISSUE TITLE
Modifying more than 1 VehicleWheel node at once does not work

### ISSUE THREAD

**Issue by tobiblender** [godotengine/godot#35884] opened 2020-02-03 15:21 UTC
**Godot version:**
3.2 stable
**OS/device including version:**
win8
**Issue description:**
if you select multiple nodes of any kind in the scene and try to change parameters for all of them in the inspector, it doesnt work anymore.
i tryed it with 4 vehiclewheel-nodes 
and with 2 mesh-instance-nodes (make them unique before)
it changes the last selected node... sometime 2 nodes out of 4... but never can i change a parameter for all selected nodes... 
in 3.1.2 stable it worked just fine.
**PS: maybe this bug only affects the vehicle-wheels-node. not sure. i am new to godot ;)**

a related thing on all nodes:
the little round arrow next to an inspector-value (to reset the value to default)
isnt showing up if i select multiple nodes. (of the same type)

in 3.1.2 this was possible and very very handy :) should be brought back imo...

**Steps to reproduce:**
- create 2 or more nodes of same kind (vehicle wheels bugs for sure)
- select them and try to change a parameter/value in the inspector
- check the nodes and see that the change has not effected all of them
**Minimal reproduction project:**
not nessecary here

**Comment by YeldhamDev** [comment] 2020-02-03 17:59
I tested this with a `LineEdit` node and it worked correctly.

By "make them unique", you mean making their sub-resources unique? Because if so, the inspector is likely picking one of the resources from the multiple nodes selected, and editing that, which will not trigger the change for the others because they are completely different.

**Comment by tobiblender** [comment] 2020-02-03 19:19
i had this problem today in 3.2 for vehicle-wheels... changing parameters on multiple wheels was working in 3.1.2

maybe its just the wheels-nodes that broke...  i have no full overview because i am using godot just some weeks now.

**Comment by Zireael07** [comment] 2020-02-03 19:21
I just changed parameters on multiple node2D's (position) and it worked.

What parameters were you trying to change? Were Vehicle Wheels the only node you tried?

**Comment by tobiblender** [comment] 2020-02-03 19:30
it seems not all nodes affected - maybe just the wheel-nodes.

i cant go deeper here, because i am a relativly new user.
made my first game in 3.1.2 in the last weeks ... i am not so deep into the engine/UI yet.
please someone with more experience test this behavior. should be easy.

i was rewritting my game for 3.2 at the weekend... it was a pain, so lot have changed.
and today i took the day to report the bugs i found, and made little test-projects to show them off.
sorry i am pretty exhausted in the moment. :)

**Comment by KoBeWi** [comment] 2020-12-23 00:07
I tried VehicleWheels specifically and they don't exhibit this behavior, so this issue is likely fixed/invalid. Closing.

Comment if you can still reproduce, preferably with a video showing the bug.

**Closed by KoBeWi** 2020-12-23 00:07 UTC
Labels: bug, regression, topic:editor
