### ISSUE TITLE
Raycast result collider value cannot be assigned to a typed variable

### ISSUE THREAD

**Issue by mrzapp** [godotengine/godot#20417] opened 2018-07-24 17:57 UTC
**Godot version:**
v3.1-dev.custom_build.b665809 (godot-git from AUR)

**OS/device including version:**
Manjaro 17.1.11

**Issue description:**
When trying to assign a raycast collider value (said in the docs to be of type `Object`), this error is thrown "Internal Script Error! - opcode #37 (report please)."

**Steps to reproduce:**
1. Create a typed variable
2. Perform a raycast
3. Assign the "collider" value to the typed variable

**Comment by akien-mga** [comment] 2018-07-24 19:38
CC @vnen

**Comment by Zylann** [comment] 2018-07-24 23:50
Isnt' this because the result is a dictionary? Which contains variants, which can only be checked to a limited degree.
With typed GDScript you would need something like:

```gdscript
var collider := hit.collider as Object
```

**Comment by vnen** [comment] 2018-07-25 01:20
> 1. Create a typed variable
> 2. Perform a raycast

Can it be of any type? There are also many ways to do raycasting (both in 2D and 3D)... Would be simpler to provide a code snippet or sample project.

> Isn't this because the result is a dictionary?

If that's the case then the bindings are wrong. GDScript got much more sensitive to binding errors. C# and GDNative are sensitive too, so they might be also broken if the bindings are wrong. That might be the cause of the opcode error.

**Comment by mrzapp** [comment] 2018-07-25 04:18
@vnen My bad, I should have been more specific. Here's a snippet:

```
extends Spatial

var hit_result : Object

func _ready():
    var space_state : PhysicsDirectSpaceState = get_world().direct_space_state
    var result : Dictionary = space_state.intersect_ray(Vector3(0, 0, 0), Vector3(1, 0, 1))
    
    if result.has("collider"):
        hit_result = result["collider"] # <- This fails

    hit_result = $RayCast.get_collider() # <- This fails too
```

This code will execute properly if I remove the ": Object" part of the variable declaration

**Comment by akien-mga** [comment] 2018-07-25 07:00
`get_collider` does return `Object`, but it will always be a more specified class inheriting object, like `KinematicBody` or `Area`.

So here you'd have to cast the result I suppose if you want to assign it to an `Object` variable.

**Comment by mrzapp** [comment] 2018-07-25 07:21
@akien-mga you're right, this works:

```
extends Spatial

var hit_result : Spatial

func _ready():
    var space_state : PhysicsDirectSpaceState = get_world().direct_space_state
    var result : Dictionary = space_state.intersect_ray(Vector3(0, 0, 0), Vector3(1, 0, 1))
    
    if result.has("collider"):
        hit_result = result["collider"] as Spatial # <- This works

    hit_result = $RayCast.get_collider() as Spatial # <- This works too
```
I suppose it's safe to assume that we'll be hitting a `Spatial` type when we're using ray casting in 3D, so maybe that's what it should be returning in the first place instead of `Object`?

**Comment by mrzapp** [comment] 2018-07-25 07:31
@akien-mga Should we just clarify it in the docs for now? I can make a pull request for the PhysicsDirectSpaceState page

**Comment by akien-mga** [comment] 2018-07-25 07:59
The XML is generated from the source code, so it needs to be fixed in the engine if we want to fix the doc (`get_collider()`'s signature does return `Object` for now).

**Closed** 2018-07-26 11:48 UTC
Labels: bug, topic:gdscript
