### ISSUE TITLE
Installing demos from Project Manager is a confusing process

### ISSUE THREAD

**Issue by dejayc** [godotengine/godot#16790] opened 2018-02-18 03:41 UTC
**Godot version:**
3.0

I felt stupid that it took me like 20 minutes to figure out how to install a Godot demo from the Project Manager "Templates" tab.  My brain didn't understand why I had to click two separate "Install" buttons to install a demo project.  In my opinion, one "Install" button should be enough, and if two buttons are really required, they should be named differently.

Thus, I propose renaming either of the "Install" buttons.  The first button could be renamed something like "Download" or "Prepare Install", or the second button could be renamed something like "Create New Project from This Demo" or something.

**Comment by Noshyaar** [comment] 2018-02-18 04:24
Duplicate of #16773

**Closed by Noshyaar** 2018-02-18 04:24 UTC
