### ISSUE TITLE
Script editor tooltips that have a very long string freeze the editor

### ISSUE THREAD

**Issue by gongpha** [godotengine/godot#72335] opened 2023-01-29 20:11 UTC
### Godot version

d01ac9c73

### System information

Windows 11 x64, Vulkan (Mobile), NVIDIA GeForce GTX 1650

### Issue description

When the game was paused (by breakpoints or whatever) and then hovering container variables (i.e. `Array` or `Dictionary`) for the tooltips that show a very LONG string representation of the variable, the editor will freeze after the tooltip shows.

https://user-images.githubusercontent.com/13400398/215352322-3ad13ddb-7b30-4b81-8ec5-69e269113479.mp4

But not for other tooltips :

https://user-images.githubusercontent.com/13400398/215352451-4a81b636-557f-4fa2-9c02-7a12187b3c6e.mp4

(Just a cursed text, Not a renderer issue)

### Steps to reproduce

Place this script in the main scene then run the project :
```gdscript
extends Node
var arr : Array
func _init() :
	for i in 1024 :
		arr.append("55555555555555555555555555555555555555555555555")
	breakpoint
```
Once the breakpoint is reached, try hovering any `arr` text in the script editor until the long tooltip shows. Then the editor freezes

### Minimal reproduction project

N/A

**Comment by Calinou** [comment] 2023-01-29 22:29
Duplicate of https://github.com/godotengine/godot/issues/70493.

**Closed by Calinou** 2023-01-29 22:29 UTC
