### ISSUE TITLE
World Environment Node Affects the UI arrows as well as the axis

### ISSUE THREAD

**Issue by MinaRashad** [godotengine/godot#37560] opened 2020-04-03 20:46 UTC
**Godot version:**
3.2
**Issue description:**
When Using the World Environment and activate Dof far blur , it blurs everything on the screen regardless of whether it is part of the scene, this includes the arrows used to change the position of a node, x,y,z-axis, ..etc
You can see this here
![Screenshot from 2020-04-03 22-34-44](https://user-images.githubusercontent.com/39602891/78403438-a9d8fd80-75fc-11ea-9457-e679e094d49d.png)

This is the scene used
[bug.zip](https://github.com/godotengine/godot/files/4429830/bug.zip)

**Comment by clayjohn** [comment] 2020-04-03 21:24
This is intentional. The rotation gizmos are not UI elements, they are actual meshes in the scene. If you don't want your WorldEnvironment settings to appear in the editor, you can de-select "Environment" in the "Perspective" menu in the upper left corner of the scene view. 

For further information, please see [this issue](https://github.com/godotengine/godot/issues/8485) where a user had the same problem (only with glow instead of DOF)

**Comment by Calinou** [comment] 2020-04-03 22:39
Duplicate of #8140.

**Closed by Calinou** 2020-04-03 22:39 UTC
Labels: discussion, topic:editor, topic:rendering
