### ISSUE TITLE
Updating an Array's String or StringName values via AnimationTree results in corrupted valueus

### ISSUE THREAD

**Issue by TheQuietCroc** [godotengine/godot#100543] opened 2024-12-18 05:41 UTC
### Tested versions

Found in
- v4.3.stable.mono.official [77dcf97d8]
![Image](https://github.com/user-attachments/assets/ca8d2fb0-9564-425f-a97c-f354ebfa9b7f)

Works in
- v4.0.stable.mono.official [92bee43ad]
- v4.1.1.stable.mono.official [bd6af8e0e]
- v4.2.1.stable.mono.official [b09f793f5]
![Image](https://github.com/user-attachments/assets/00db7711-bc6d-4f65-a69f-63d9499c379f)

### System information

Godot v4.3.stable.mono - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1070 (NVIDIA; 32.0.15.6094) - Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz (16 Threads)

### Issue description

Given I have a custom node with an exported array of variants.

When I use an AnimationTree to trigger an AnimationPlayer to play an animation that updates String or StringName values.

Then I expect the String and StringName values to be saved exactly as I set them in the keyframe.

Instead, the values are corrupted and save as unreadable gibberish.

### Steps to reproduce

Custom script setup 
1. Create a custom class that inherits from `Label`
2. Export a `StringName`, `String`, and `Array`
3. Create an `update` function that sets the `Label`'s text to the exported values
4. Call the `update` function in the `ready` function

Test scene setup
1. Create a new scene with a `Control` root node
2. Add a `custom` node child
3. Give the new child node an `AnimationPlayer` child

AnimationPlayer setup
1. Create a new animation
2. Set it to autoplay
3. Set it to loop
4. Make it as long as you want
5. Add as many export field update frames as you want
6. For every field update, make a call to the `custom` node's `update` function at the same time

Custom node 2 setup
1. Duplicate the `custom` node
2. Turn off autoplay from the new `custom` node's `AnimationPlayer`
3. Add an `AnimationTree` child to the new `custom` node
4. Set `Tree Root` to a new `AnimationNodeStateMachine`
5. Set `Anim Player` to the new `custom` node's `AnimationPlayer`
6. Add a new transition from the `AnimationTree`'s state machine Start node to a new animation node

Testing in editor
1. Ensure both nodes' animations are playing
2. Select the second `custom` node in the scene tree
3. Observe that the `Array`'s `StringName` and `String` values are gibberish like `·ÅµÍt§ÈÆ½Â»¢µÁ¹t`
4. Select the first `custom` node in the scene tree
5. Observe that the `Array`'s `StringName' and `String' values are readable

Testing in player
1. Run the scene
2. Observe that the first `custom` node's `Array`'s `StringName' and `String' values are readable
3. Observe that the second `custom` node's `Array`'s `StringName` and `String` values are gibberish like "·ÅµÍt§ÈÆ½Â»¢µÁ¹t"

### Minimal reproduction project (MRP)

[AnimationTreeMRP.zip](https://github.com/user-attachments/files/18175425/AnimationTreeMRP.zip)
This project was made using the steps above. You should be able to run it and observe the issue immediately.

**Comment by TokageItLab** [comment] 2024-12-19 01:18
Can't reproduce issue in MRP. Well, in any case that should be the intended behavior. If you are using AnimationTree you should review the settings for Discrete since String will be interpolated to animate the characters if it is Continuous. Make sure that the UpdateMode of the animation track is set to Discrete, and then set CallbackModeDiscrete to something other than ForceContinuous.

![Image](https://github.com/user-attachments/assets/98fd62ec-0f1a-4748-b0fa-f6148edcfae6)

![Image](https://github.com/user-attachments/assets/48132d76-2e46-4224-8176-592504f835ca)

**Closed by TokageItLab** 2024-12-19 01:18 UTC
Labels: bug, topic:core, topic:animation

**Comment by TheQuietCroc** [comment] 2024-12-19 03:35
Setting Discrete to Recessive is what fixed it. I'm not gonna go back and test this in the old builds to see if that's a new field, but thanks for bringing it up.
