### ISSUE TITLE
Open External Editor from Godot Debugger Panel not working

### ISSUE THREAD

**Issue by Chtau** [godotengine/godot#84294] opened 2023-11-01 08:15 UTC
### Godot version

4.1.2

### System information

Godot v4.1.2.stable - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1080 (NVIDIA; 31.0.15.3713) - AMD Ryzen 7 5800X 8-Core Processor (16 Threads)

### Issue description

When the external Editor is active and you click on an error in the Debugger Panels "Stack Frames" or "Errors" it does not open the 
 external Editor.

### Steps to reproduce

* Configurate to "Use External Editor" in Editor Settings
* Run debugging from within the Godot Engine
* Produce a Runtime Error
* Click on the Error in the "Stack Trace" or "Errors" Panel

### Minimal reproduction project

[test.zip](https://github.com/godotengine/godot/files/13224784/test.zip)

This Test Scene throws a runtime error on "A" press

**Comment by KoBeWi** [comment] 2024-07-30 12:18
Duplicate of #19838

**Closed by KoBeWi** 2024-07-30 12:18 UTC
Labels: bug, topic:editor
