### ISSUE TITLE
DrawView: 500 error on IOS

### ISSUE THREAD

**Issue by DisDoh** [godotengine/godot#43759] opened 2020-11-21 23:17 UTC
**Godot version:**

3.2.3-stable

**OS/device including version:**

IOS 12.4.9 iphone 6 Gles 2

**Issue description:**

The game does work as expected but this error just keep showing in the debugger console.`DrawView: 500 Error`

**Steps to reproduce:**
I'm exporting my game with xcode after having exported with godot for ios.
Steps: I'm using some TextureRect and some ButtonRect I think the problem is coming from that because the debugger doesn't stop showing the error and i have a TextureRect in the middle of the screen, a Poker Table png to be exact.
When opening my game the first think to appear is a video and there is no error but in the next scene there is a TextureRect and the debugger write a  `DrawView: 500 error` in xcode.
**Minimal reproduction project:**

Sorry I'm not willing to share my project.
But I'm kind of sure it's caused from the TextureRect

**Comment by Calinou** [comment] 2020-11-22 00:00
How large is the `Poker Table png` texture? Mobile hardware usually doesn't support textures that are larger than 4096 pixels in either dimension.

**Comment by clayjohn** [comment] 2020-11-22 00:57
Duplicate of: https://github.com/godotengine/godot/issues/31907

**Closed by clayjohn** 2020-11-22 00:57 UTC
Labels: bug, platform:ios, topic:porting
