### ISSUE TITLE
AnimationPlayer freezes when nonzero blend time is used to play same animation as previously played

### ISSUE THREAD

**Issue by jamesdkay** [godotengine/godot#81815] opened 2023-09-17 17:16 UTC
### Godot version

v4.1.stable.mono.official [970459615]

### System information

Godot v4.1.stable.mono - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1660 Ti (NVIDIA; 31.0.15.1640) - AMD Ryzen 7 4800H with Radeon Graphics (16 Threads)

### Issue description

Using AnimationPlayer, when you use play() with custom_blend set to a nonzero value the AnimationPlayer doesn't play if the animation being played is the same as the previous animation played. This is the case even if that previous animation has finished playing. Blending from one animation to a different animation works, as does playing the same animation again with a zero blend time.

Sorry if this is a duplicate. I see some very similar issues reported but nothing that seemed to be this exact issue. Feel free to combine this issue with another one if it necessary.

### Steps to reproduce

Create an animation player and give it an animation track "anim1". Call play("anim1", 0.1)

This will work once, but trying to call it a second time will not work.

If you change 0.1 to 0.0 it will work. If you change "anim1" to a second animation track "anim2" it will work unless "anim2" is the previously played animation.

See minimal reproduction project.

### Minimal reproduction project

[animationplayer bug.zip](https://github.com/godotengine/godot/files/12643317/animationplayer.bug.zip)

Open and run the project. Left click anywhere to run an animation track "move". Rectangle will move from left to right.
Once this animation has finished, click anywhere again. This time the animation will not play. Actually, clicking repeatedly will step backwards through through the animation for some reason and eventually will play again.
Right click anywhere to play a copy of this animation. This will also work once but will not work a second time in a row. Both animations play fine if the previously played animation was not the same one trying to be played.

Also, if you edit the script on the ColorRectangle and change 

anim.play("move_copy", 0.1)

to

anim.play("move_copy", 0.0)

everything works as expected. The problem seems to occur only for nonzero blend times.

**Comment by TokageItLab** [comment] 2023-09-22 09:46
Dupe of #72484

**Closed by TokageItLab** 2023-09-22 09:46 UTC
Labels: bug, topic:animation
