### ISSUE TITLE
Export Keyword seem to reference arrays.

### ISSUE THREAD

**Issue by PerrierB** [godotengine/godot#45721] opened 2021-02-05 01:32 UTC
Godot version: V3.2.3 Stable Official

OS/device including version: Windows, GLES 3.0, Intel(R) HD Graphics

Issue description:
Creating 2 different variables, both using the "export" keyword and being assigned an empty array, links them together. When appending a value to the first variable, it also adds it to the second variable. The issue goes away if instead of assigning an empty array you instead cast the exported variable.

Steps to reproduce:
The following doesn't work : 

```
extends Node2D

export var array_one = []
export var array_two = []

func _ready():
	array_one.append(1)
	
print(array_two.size()) #this statement returns 1

```
While this version does :

```
extends Node2D

export (Array)var array_one
export (Array)var array_two

func _ready():
	array_one.append(1)
	
	print(array_two.size())#This statement returns 0
```

Minimal reproduction project:
[Issue Project.zip](https://github.com/godotengine/godot/files/5929509/Issue.Project.zip)

**Comment by Calinou** [comment] 2021-02-05 01:39
Duplicate of https://github.com/godotengine/godot/issues/16478.

**Closed by Calinou** 2021-02-05 01:39 UTC
