### ISSUE TITLE
opening scene in new tab conflict with tool keyword

### ISSUE THREAD

**Issue by mohaalak** [godotengine/godot#2277] opened 2015-07-17 14:55 UTC
Hi
I build the last version of Godot when I open a scene that has a script and tool , to add object with script and animate it with tween , object have problem , it is like that it is initiated twice .

**Comment by mohaalak** [comment] 2015-07-17 14:56
it will add two object in my scene , and I add it in _ready function just once

**Comment by akien-mga** [comment] 2015-11-10 16:37
Are you still able to reproduce this issue in the current master branch? If so, could you provide an example project that reproduces it?

**Comment by bojidar-bg** [comment] 2015-11-10 16:39
Seems like a duplicate of #2657 (If not, tell me and I'll delete my comment :smile: )

**Comment by akien-mga** [comment] 2015-11-11 10:37
Might actually be a duplicate of #2229, so it's not easy to understand what was meant initially.

**Comment by akien-mga** [comment] 2015-11-11 10:37
Closing for now, feel free to reopen if your issue was different from the two linked above.

**Closed by akien-mga** 2015-11-11 10:37 UTC
Labels: archived, bug, topic:editor
