### ISSUE TITLE
3->4 project conversion from Project Manager fails without Vulkan support even with "--rendering-driver opengl3"

### ISSUE THREAD

**Issue by Foxysen** [godotengine/godot#76303] opened 2023-04-20 21:17 UTC
### Godot version

4.0.2

### System information

Windows 10, GPU with no Vulkan support

### Issue description

My GPU doesn't support Vulkan. I run Godot 4 with "--rendering-driver opengl3" argument.

I have tried to open my Godot 3 project from Godot 4 Project Manager. It asked me whether I want my project to be converted. I pressed "full conversion". Very shortly it gave me a error that it can't run Vulkan app and that I should use "--rendering-driver opengl3", which I already run. After it closed Project Manager for me and I reopened it, I could find the project in the Project Manager list and then open it. There was no error. However the convertion was minimal, just enough to run it in Godot 4. I believe that it didn't run a full auto-convertion.
This always happens when I repeat these steps.

Next I have used command line and launched Godot 4 from it with "--convert-3to4" argument, doing it on second copy of the same Godot 3 project. (Had to increase limits for it to convert everything.) The process went smoothly and final project could be opened without error as well. However it had a more full conversion in comparison. This makes me believe that conversion process fails in Project Manager method by not respecting "--rendering-driver opengl3" argument in the process (I don't know how it actually looks as I can't run it).

P.S. I also run Godot 4 with "--single-window" argument, as it glitches out for me otherwise. I don't know if it has an impact on my experience, but worth mentioning.

Bonus:
I have a suspicion that this issue 
https://github.com/godotengine/godot/issues/74159
is related to this one and is actually a result of a failed conversion.

### Steps to reproduce

Get GPU with no Vulkan support and try to convert any Godot 3 project from Project Manager while running with "--rendering-driver opengl3".

### Minimal reproduction project

Any Godot 3 project, it just has to error on attempt.

**Comment by Calinou** [comment] 2023-04-20 22:04
This sounds like a duplicate of https://github.com/godotengine/godot/issues/74159. The project converter does not set the renderer of the converted project, so it defaults to Forward+ on desktop, Forward Mobile on mobile and Compatibility on web.

**Comment by akien-mga** [comment] 2023-04-20 22:10
It probably doesn't require a fallback, the problem isn't what renderer the project itself is using, but what renderer is used by the project manager when starting a new process with the `--convert-3to4` argument.

Making default to OpenGL3 like the project manager might solve the issue of the files conversion not happening properly.

**Comment by Foxysen** [comment] 2023-04-21 06:47
I think that akien-mga has got the source of my problem right and solution makes sense to me.

I will make sure to confirm if it solves my issue when I see it implemented in a compiled release.

**Closed** 2023-07-08 16:24 UTC
Labels: bug, topic:rendering, topic:editor
