### ISSUE TITLE
BakedLightmap extents don't update in real time 3.2.4 beta 6

### ISSUE THREAD

**Issue by Wavesonics** [godotengine/godot#45430] opened 2021-01-25 00:21 UTC
**Godot version:**
3.2.4 beta 6

**OS/device including version:**
Windows 64 GLES3

**Issue description:**
The new BakedLightmap node:
When changing the extents by grabbing the handles in 3D and dragging them larger or smaller, the extents field in Inspector don't update in real time.

If you click off the node and back on it then they update.

**Steps to reproduce:**
- Create a BakedLightmap node
- Select it
- Grab it's handles in the 3D view and resize it's Extents

Note that the Extents values (X,Y,Z) in Inspector don't update.

**Comment by Calinou** [comment] 2021-01-25 01:06
Duplicate of https://github.com/godotengine/godot/issues/45317.

**Closed by Calinou** 2021-01-25 01:06 UTC
