### ISSUE TITLE
Unable to instance empty scene - Nonexistent function 'instance' error"

### ISSUE THREAD

**Issue by JacobZalewski** [godotengine/godot#88677] opened 2024-02-22 18:25 UTC
### Tested versions

I'm encountering a critical bug in Godot v4.2.1.stable.official

### System information

Windows 10 - Godot Engine v4.2.1.stable.official.b09f793f5 - https://godotengine.org Vulkan API 1.3.271 - Forward+ - Using Vulkan Device #0: NVIDIA - NVIDIA GeForce RTX 3070 Ti

### Issue description

I'm encountering a critical bug in Godot v4.2.1.stable.official which prevents me from instancing even the most basic, empty scenes. This results in a consistent crash with the following error:
"Invalid call. Nonexistent function 'instance' in base 'PackedScene'."

Steps to Reproduce:

Create a new, blank Godot project.
Set up two scenes:
MainMenu.tscn:
Root Node: Node2D
Child Node: TextureButton
Attached Script (GDScript):
```gdscript
GDScript
extends Node2D

func _ready():
  $TextureButton.pressed.connect(self._on_TextureButton_pressed)

func _on_TextureButton_pressed():
  var loaded_scene = preload("res://TestScene.tscn") 
  var next_scene = loaded_scene.instance() 
  queue_free() 
  get_tree().change_scene_to(next_scene) 
```
Use code [with caution.](https://gemini.google.com/faq#coding)
TestScene.tscn:
Root Node: Node2D (empty, no scripts)
Run MainMenu.tscn:
Click the TextureButton.
Expected Result: The game should smoothly switch to the empty TestScene.
Actual Result: The game crashes with the "Nonexistent function 'instance'" error.

Project Files:

[Attach a zipped copy of your Absolute Minimal Test project]
System Information:

Operating System: [Please specify Windows version, macOS version, or Linux distro]
Graphics Card: NVIDIA GeForce RTX 3070 Ti
Other Specs (If Possible): [CPU, RAM]
Additional Notes:

This bug persists even with the most basic code and a completely empty scene.
It significantly hinders the ability to use standard scene switching workflows.
Thank you for investigating this issue!

### Steps to reproduce

Create a new, blank Godot project.
Set up two scenes:
MainMenu.tscn:
Root Node: Node2D
Child Node: TextureButton
Attached Script (GDScript):
```gdscript
GDScript
extends Node2D

func _ready():
  $TextureButton.pressed.connect(self._on_TextureButton_pressed)

func _on_TextureButton_pressed():
  var loaded_scene = preload("res://TestScene.tscn") 
  var next_scene = loaded_scene.instance() 
  queue_free() 
  get_tree().change_scene_to(next_scene) 
```
TestScene.tscn:
Root Node: Node2D (empty, no scripts)
Run MainMenu.tscn:
Click the TextureButton.
Expected Result: The game should smoothly switch to the empty TestScene.
Actual Result: The game crashes with the "Nonexistent function 'instance'" error.

### Minimal reproduction project (MRP)

[SceneSwitchBugTest.zip](https://github.com/godotengine/godot/files/14377979/SceneSwitchBugTest.zip)

**Comment by AThousandShips** [comment] 2024-02-22 18:28
The method is `instantiate`, not `instance`, please see the [documentation](https://docs.godotengine.org/en/stable/classes/class_packedscene.html#class-packedscene-method-instantiate)

Closing as this is not a bug

Thank you for reporting

**Closed by AThousandShips** 2024-02-22 18:28 UTC
