### ISSUE TITLE
Cannot assign Array[A_Extend] to Array[A] in GDScript

### ISSUE THREAD

**Issue by luckyabsoluter** [godotengine/godot#100798] opened 2024-12-25 04:49 UTC
### Tested versions

v4.3.stable.official [77dcf97d8]

### System information

v4.3.stable.official [77dcf97d8]

### Issue description

When attempting to assign an Array of a subclass (Array[A_Extend]) to an Array of its parent class (Array[A]), the GDScript compiler throws the following error:
```
Value of type "Array[A_Extend]" cannot be assigned to a variable of type "Array[A]".
```

This behavior contradicts the expected polymorphism in object-oriented programming where a subclass should be assignable to a parent class reference.

### Expected Behavior:
The array_A_Extend (an array of subclass A_Extend) should be assignable to array_A (an array of parent class A) without any errors.

### Actual Behavior:
An error is thrown, preventing the assignment:
Value of type "Array[A_Extend]" cannot be assigned to a variable of type "Array[A]".

### Steps to reproduce

# Assign
1. Create a new Godot project.
2. Add the following script to a Node:
``` gdscript
extends Node

class A:
    pass

class A_Extend extends A:
    pass

func _ready():
    var array_A: Array[A] = []
    var array_A_Extend: Array[A_Extend] = []

    array_A = array_A_Extend  # Error: Value of type "Array[A_Extend]" cannot be assigned to a variable of type "Array[A]".
    #array_A.assign(array_A_Extend)  # bug workaround
```
3. Check the script for errors.

# Argument
1. Create a new Godot project.
2. Add the following script to a Node:
``` gdscript
extends Node

class A:
    pass

class A_Extend extends A:
    pass

func _ready():
    var array_A: Array[A] = []
    var array_A_Extend: Array[A_Extend] = []

    need_A(array_A_Extend)  # Error: Invalid argument for "need_A()" function: argument 1 should be "Array[A]" but is "Array[A_Extend]".
    #array_A.assign(array_A_Extend)  # bug workaround
    #need_A(array_A)

func need_A(p: Array[A]):
    pass
```
3. Check the script for errors.

# Argument but No error
1. Create a new Godot project.
2. Add the following script to a Node:
``` gdscript
extends Node

class A:
    func _to_string():
        return "A"

class A_Extend extends A:
    func _to_string():
        return "A_Extend"

func _ready():
    need_A([A_Extend.new()])

func need_A(array_A: Array[A]):
    print(array_A)
```
3. No error!

### Minimal reproduction project (MRP)

N/A

**Comment by tetrapod00** [comment] 2024-12-25 05:56
Maybe duplicate of https://github.com/godotengine/godot/issues/95113

**Comment by dalexeev** [comment] 2024-12-25 17:15
Duplicate of:

* #80586
* #83876
* #89959
* #93063
* #93084

See:

* [Wikipedia - Covariance and contravariance (computer science)](https://en.wikipedia.org/wiki/Covariance_and_contravariance_(computer_science))
* [GDScript reference - Typed arrays](https://docs.godotengine.org/en/latest/tutorials/scripting/gdscript/gdscript_basics.html#typed-arrays)
* godotengine/godot-proposals#7364

![](https://github.com/godotengine/godot/assets/47700418/f75cea69-5544-40df-b111-f798cdb32901)

This is not a bug. Arrays are passed by reference; they do not copy the entire content. Otherwise you would get:

```gdscript
var a: Array[Node2D]
var b: Array[Node]
b = a # Now `b` refers to the same array as `a`.
b.append(Label.new()) # Valid, `Label` is a subtype of `Node`.
print(a[0]) # Invalid, `Label` is **not** a subtype of `Node2D`.
```

Probably the only way this would work is if the GDScript supported [`read`/`write` qualifiers](https://github.com/godotengine/godot-proposals/discussions/7364#discussioncomment-6576975). But it's too difficult.

Thanks for the contribution nonetheless!

**Closed by dalexeev** 2024-12-25 17:15 UTC
Labels: bug, topic:gdscript
