### ISSUE TITLE
Building project in Godot Mono leads randomly to .NET: Failed to unload assemblies.

### ISSUE THREAD

**Issue by JonathanPicques** [godotengine/godot#70064] opened 2022-12-14 17:23 UTC
### Godot version

4.0.beta8

### System information

Windows 10 64bits

### Issue description

```
  .NET: Failed to unload assemblies.
  modules/mono/managed_callable.cpp:92 - Condition "delegate_handle.value == nullptr" is true.
  Can't get method on CallableCustom "Delegate::Invoke".
  core/object/object.cpp:1058 - Error calling from signal 'timeout' to callable: 'Node::': Method not found.
```

The last three lines will be repeated in a loop until the editor becomes unusable.

### Steps to reproduce

Sorry can't find a pattern here

### Minimal reproduction project

N/A

**Comment by JonathanPicques** [comment] 2022-12-14 17:24
Seems to be linked to https://github.com/godotengine/godot/issues/70026

**Comment by Chaosus** [comment] 2022-12-16 08:26
Duplicate of #70026

**Closed by Chaosus** 2022-12-16 08:26 UTC
Labels: bug, topic:dotnet
