### ISSUE TITLE
Weird FPS output when running game.

### ISSUE THREAD

**Issue by jonbonazza** [godotengine/godot#15924] opened 2018-01-21 04:38 UTC
**Godot version:**
RC2 official build

**OS/device including version:**
Windows 10 64-bit

**Issue description:**
Maybe I am just misinterpreting the output, but when I configure Godot to print the FPS and run my project, I see an odd looking output:

```
FPS: 114
FPS: 60
FPS: 112
FPS: 60
FPS: 113
FPS: 60
FPS: 112
FPS: 60
FPS: 113
FPS: 60
FPS: 113
```

It seems that every other output is around what I would expect (~113), but then interleaved evenly is always 60. 

Is the 60 perhaps the physics integration and the 113 the rendering FPS?

I noticed that with RC2, things are a bit choppier than with RC1. I am going to see what this looks like in RC1 and report back.

**Comment by jonbonazza** [comment] 2018-01-21 04:44
Looks like the output is the same in RC1, though it's noticeably smoother, but that's a different issue.

**Comment by Noshyaar** [comment] 2018-01-21 13:08
I could be wrong but I think one is for the editor (100+), another is for the running project (60).

**Comment by Zephilinox** [comment] 2018-01-21 13:54
Duplicate of #13452

**Closed** 2018-01-21 14:24 UTC
Labels: bug, topic:editor
