### ISSUE TITLE
Cannot vertically scroll Godot templates without moving mouse

### ISSUE THREAD

**Issue by myDisconnect** [godotengine/godot#19288] opened 2018-05-31 10:27 UTC
**Godot version:**

3.0.2-stable

**OS/device including version:**

OS X El Capitan / MacBook Pro (Retina, 13-inch, Early 2015)

**Issue description:**

Vertical scroll doesn't work correctly in Templates. 
Currently it allows to scroll up/down only once and after that it gets disabled until you move your mouse a bit which gives you an extra one scroll.

**Steps to reproduce:**
1. Launch Godot application
2. Press Templates tab
3. Try scrolling up and down

**Comment by DrMoriarty** [comment] 2018-05-31 19:06
I have the same behaviour in inspector view. But scene view, file system view and files view works as expected.
Also I made a long scroll view in my game and it scrolls the same buggy way.
OS X High Sierra (10.13.4)
Godot from current master 3d9dffdef7d436cda779ee4a659476fa94c62a35

**Comment by bojidar-bg** [comment] 2018-10-23 17:18
Cannot confirm on master (a36a99b846ddc6bb499dca9a7dcdecaada8d08b5), Arch Linux on the Templates tab.

Retagging as OSX-specific. Additionally, unassigning myself, since I don't own a Mac.

**Comment by DrMoriarty** [comment] 2018-10-25 15:28
@bojidar-bg 
I'm sure that this bug does not appear on godot 3.1.alpha1
I only can reproduce it on 3.0.6-official
So somebody can just close it.

**Comment by akien-mga** [comment] 2018-10-25 15:36
Closing as fixed in 3.1 then.

**Closed by akien-mga** 2018-10-25 15:36 UTC
Labels: bug, needs testing, platform:osx, topic:editor, usability
