### ISSUE TITLE
Too many 2D editor menu options push inspector menu off screen

### ISSUE THREAD

**Issue by mandmeier** [godotengine/godot#62264] opened 2022-06-21 03:19 UTC
### Godot version

4.0.dev10

### System information

MacOS Monterey M1

### Issue description

When I select e.g. a control node, all is fine. All panels fit into my window

<img width="1434" alt="image" src="https://user-images.githubusercontent.com/26724996/174708320-849a2311-f689-47c2-97a7-fd5db895142c.png">

The problem is with the extra menu options for some nodes, e.g. the MenuButton node. The extra options Anchor, Horizontal, Vertical etc push the Inspector menu to the right off screen. (probably a similar issue to #60728 but not sure if exactly the same)

<img width="1341" alt="image" src="https://user-images.githubusercontent.com/26724996/174708630-8b36432c-5841-4109-b511-fb8c2fc2f05f.png">

Would it be possible to make the extra options in the 2D menu wrap to a second line? If not I have to extend the window to the right and make it larger than my computer screen, kinda annoying:

<img width="1434" alt="image" src="https://user-images.githubusercontent.com/26724996/174708797-c21d1608-c2d6-44a5-ac34-9f3f141d2571.png">

### Steps to reproduce

Open a new project and make a Node2D and a MenuButton node, then click them in the Scene panel.

**Comment by KoBeWi** [comment] 2022-06-21 10:07
Duplicate of #31133

**Closed by KoBeWi** 2022-06-21 10:07 UTC
Labels: bug, topic:editor, topic:2d
