### ISSUE TITLE
2D usability issues - scaling objects together

### ISSUE THREAD

**Issue by QbieShay** [godotengine/godot#20080] opened 2018-07-10 08:49 UTC
**Godot version:**
3.0.3

**Issue description:**
Currently, I have issues with the 2D workflow. One of the bigger problems I have is that there is no way to scale objects together. It can be worked around if the nodes are put as a child of a node and the parent node is scaled, but that is not possible when inheriting a scene. In the following example, I want to scale together the collision shape of the repeater and the visual representation of it. If i select them singularly, i can resize them, I have the rectangle with the small circles. But if i select them together, it's gone. Since they have different base scale, I can't just set the scale for both of them
![image](https://user-images.githubusercontent.com/7917475/42499033-0fefc5da-842e-11e8-9bc2-e573b17655a5.png)
![image](https://user-images.githubusercontent.com/7917475/42499057-1dacdb9a-842e-11e8-88a8-5d78a900870f.png)

Also, pivot changing doesn't seem to work.

This issue was discussed with @reduz at GodotCon, but hasn't been addressed yet. I believe @groud can do something about it?

**Comment by groud** [comment] 2018-07-10 09:03
I think changing pivot of multiple node does work on master, but not multiple node scaling. This is in fact quite complex, that's why I did not take the time to implement it. 

But yeah, that would definitely be a good improvement.

**Comment by groud** [comment] 2018-07-10 09:05
Ah but BTW, I don't know if it is fixed with bullet, but scaling a collision shape does not work with Godot physics. (I see one is selected on your screenshot)

**Comment by QbieShay** [comment] 2018-07-10 09:22
@groud AFAIK uniform scaling is fine, the problem is non uniform scaling. 

I understand multiple node scaling also involves changing the position etc, but the lack of this feature has been slowing me down considerably. Please consider implementing it :) 

I really miss the ability to scale something relative to its center without having to set the scale manually from the inspector

**Comment by mhilbrunner** [comment] 2018-07-10 12:21
@groud For Bullet, scaling works fine. Juan said he needed to implement a workaround for 2D/Godot physics.

**Comment by fracteed** [comment] 2018-07-11 01:43
This issue was previously raised in #19691

**Comment by akien-mga** [comment] 2019-11-14 12:46
Duplicate of #19691.

**Closed by akien-mga** 2019-11-14 12:46 UTC
Labels: enhancement, topic:editor
