### ISSUE TITLE
Clicking on AnimationPlayer in Editor runs animation

### ISSUE THREAD

**Issue by AtomaFajrovulpo** [godotengine/godot#33530] opened 2019-11-10 22:43 UTC
**Godot version:**

_3.2 beta 1_

**Issue description:**

When you click on an AnimationPlayer the animation being currently edited / last to be editted is played.

**Steps to reproduce:**

Click on an AnimationPlayer.

**Minimal reproduction project:**

[AnimationPlayer run Demo.zip](https://github.com/godotengine/godot/files/3829136/AnimationPlayer.run.Demo.zip)

(In this project open Sprite.tscn, open the AnimationPlayer and go to _show_, click on the Sprite node in the node tree, set its visiblity to false using the eye button in the editor, then click on the AnimationPlayer and watch the Sprite appear / eye button toggle on. This also works the other way around, as in if you used the hide animation to change the Sprite from showing to hiding instead.)

**Comment by KoBeWi** [comment] 2019-11-11 00:48
Duplicate of #33353

**Closed by KoBeWi** 2019-11-11 00:48 UTC
