### ISSUE TITLE
When multiple `AnimationTree`s are active in the same scene only the last `AnimationTree` result is applied

### ISSUE THREAD

**Issue by KnightNine** [godotengine/godot#80951] opened 2023-08-24 05:15 UTC
### Godot version

4.1

### System information

Windows 10

### Issue description

Just noticed that I can no longer use the same `AnimationPlayer` across multiple `AnimationTree`s like I could in 3.X and I thought it was worth mentioning.

Here is a test scene, one AnimationTree handles the colorrect changing color, the other handles the colorrect changing the color's alpha value. note how the next animTree to become active overrides the cycle being run by the last animTree.

![animation lock](https://github.com/godotengine/godot/assets/34152090/61763c67-55a8-489f-b2c3-4919d153f57d)

I've found that priority of which animation tree is allowed to work is based on the order of the nodes in the scene tree (last having a higher priority).

I can fix this by having an animation player for each animation tree though I didn't need to do this in 3.X.

### Steps to reproduce

Set the `anim_player` property of two `AnimationTrees` (using `AnimationNodeStateMachine` as their `tree_root` property ) to the same `AnimationPlayer` and try to run them both at the same time.

What is being animated doesn't seem to matter.

### Minimal reproduction project
[Test.zip](https://github.com/godotengine/godot/files/12433155/Test.zip)

**Comment by TokageItLab** [comment] 2023-08-31 20:08
Probably this is the expected behavior, but I guess you could propose an option like `AnimationTree.priority` for when another AnimationTree is already manipulating the same object.

**Comment by TokageItLab** [comment] 2023-08-31 22:32
If you want to apply both results of the two Trees, then this issue is exact a duplicate of https://github.com/godotengine/godot/issues/80971.

**Closed by TokageItLab** 2023-08-31 22:32 UTC
Labels: usability, topic:animation

**Comment by KnightNine** [comment] 2023-09-01 07:55
> If you want to apply both results of the two Trees, then this issue is exact a duplicate of #80971.

Yeah, just realized that this issue is probably directly caused by #80971 since both animation trees are using the same anim-player and once the second anim-tree tries to run an animation, the unused parameters (across the anim-player being used) of the animation run within the second anim-tree are forced to be reset and this overrides the first anim-tree trying to animate anything.

This is annoying to try to explain concisely.
