### ISSUE TITLE
_input() method on popup nodes is never called (gdscript)

### ISSUE THREAD

**Issue by iahimoh** [godotengine/godot#79909] opened 2023-07-25 23:29 UTC
### Godot version

4.1.1.stable

### System information

Godot v4.1.1.stable unknown - Arch Linux #1 SMP PREEMPT_DYNAMIC Tue, 04 Jul 2023 08:39:40 +0000 - Vulkan (Forward+) - dedicated AMD Radeon RX 470 Graphics (RADV POLARIS10) () - AMD Ryzen 5 1400 Quad-Core Processor (8 Threads)

### Issue description

When I attach a script using gdscript on a popup node, I try using the _input() method, but it's never called ingame, but the same method is called properly when I attach similar script on a generic node.
This used to work on godot 3.

### Steps to reproduce

Create a popup node in a scene, attach a gdscript to it, declare a _input() function in it like so and see that it will never print anything
```
extends Popup

func _input(event):
	print_debug(event)
	
```

### Minimal reproduction project

[PopupTest.zip](https://github.com/godotengine/godot/files/12166332/PopupTest.zip)

**Comment by Sauermann** [comment] 2023-07-26 19:49
In V4 Popups are now based on Windows and differ regarding input events compared to the V3 implementation.
 
Please note, that in your MRP the Popup is hidden, so it doesn't receive any input events, which is the expected behavior in V4.
If you add the following in the _ready-function of your Popup-script, it will receive input events, while shown.

```gdscript
extends Popup


func _ready():
	show.call_deferred()
```

**Comment by Sauermann** [comment] 2023-07-28 20:34
I am going to close this, since this is expected behavior. Please feel free to open new issues, if you come across other problems.

**Closed by Sauermann** 2023-07-28 20:34 UTC
Labels: discussion, topic:input
