### ISSUE TITLE
Problem with importing .glb file (with Morph / Blend keys)

### ISSUE THREAD

**Issue by atari83** [godotengine/godot#36247] opened 2020-02-15 15:25 UTC
Godot version: 3.2
OS version: FreeBSD 12.1

Hello there,
My friend has created a piece of paper and has used Morph/Blend keys for animation and vertex deformation and export it to .glb file.

Importing the the file to Belnder 2.8 is just fine (animation, morph, ..). However when i import it to godot, There is no Morph animation (although the blend keys are exists!). So basically Morph keys are imported but there is no animation.

For reference, here it is the link to .glb file for examination:
https://drive.google.com/open?id=1hqELT1JarzcILomV-6BjHqqS50bpDMoI

Please help!

**Comment by atari83** [comment] 2020-02-15 22:20
I think i found the issue ... obviously Morphs are not working under GLES2, when i change video render er to GLES3 it worked !

However, i dont know if morphs are supposed to not working with GLES2 or not .. is it as planned ?

**Comment by fire** [comment] 2020-05-26 18:18
Morphs are currently not working in GLES2 at this very moment.

Since Godot Engine 3.2 doesn't support GLES2 and morph targets. This is a feature request for GLES2 morph targets.

So it's not a bug.

**Comment by fire** [comment] 2020-10-27 03:54
Closing as a duplicate of https://github.com/godotengine/godot/issues/37804.

**Closed by fire** 2020-10-27 03:54 UTC
Labels: bug, topic:import
