### ISSUE TITLE
Sprites for some tiles are swapped

### ISSUE THREAD

**Issue by plfx** [godotengine/godot#5948] opened 2016-07-28 09:32 UTC
This is really irritating, and I'm not sure what I've done to cause it.

**Operating system or device - Godot version:**
Windows 10 - Godot 2.0.4.1.stable.official

**Issue description** (what happened, and what was expected):
When placing tiles in a tilemap, some tiles in the tile selection menu/palette actually result in totally different tiles being placed on the map. The name and thumbnail is that of one tile, but placing the tile in the map results in a different one.

**Steps to reproduce:**
1. Create a scene and populate it with sprites.
2. Convert the scene to a tileset (any format)
3. Create a new scene and create a tilemap.
4. Load the previously created tileset.
5. Proceed through the list of tiles. Some of them do not look like their thumbnail once placed.

**Link to minimal example project** (optional but very welcome):
I've attached an example project with a single scene demonstrating the issue.
I have attempted to place two tiles, one called `fgSlantL` and the other called `fgSlopeR`. You can see what these tiles are supposed to look like in the thumbnail. However, when I actually place them, `fgSlantL` looks like `fgSlopeR` and vice versa.

[StarsBelow.zip](https://github.com/godotengine/godot/files/388068/StarsBelow.zip)

**Comment by plfx** [comment] 2016-07-28 09:44
I've discovered one cause, and a workaround:
If I save the tiles scene as a `.scn` rather than `.xml`, the tilemap works correctly.

**Comment by bojidar-bg** [comment] 2016-07-28 12:03
@plfx Did you export with "merge with existing" on? If so, can you try doing it without it?

**Comment by plfx** [comment] 2016-07-28 15:02
I have tried both with and without this option to no effect.

**Comment by akien-mga** [comment] 2016-07-31 08:54
I can't reproduce using the above-linked project. When I place `fgSlantL` and `fgSlopeR` in the TileMap, they look just like their preview.

**Comment by plfx** [comment] 2016-08-04 04:49
I can't reproduce it anymore either.

**Comment by akien-mga** [comment] 2016-08-04 05:28
Closing then. If you manage to reproduce it in a reliable way, don't hesitate to comment here so that the issue can be reopened.

**Closed by akien-mga** 2016-08-04 05:28 UTC
Labels: bug, topic:editor
