### ISSUE TITLE
Creating signal callbacks generates invalid C# code

### ISSUE THREAD

**Issue by rzubek** [godotengine/godot#81848] opened 2023-09-18 05:33 UTC
### Godot version

v4.1.1.stable.mono.official [bd6af8e0e]

### System information

Godot v4.1.1.stable.mono - Windows 10.0.22621 - Vulkan (Compatibility) - Intel(R) Iris(R) Xe Graphics (Intel Corporation; 30.0.101.3118) - 12th Gen Intel(R) Core(TM) i7-1255U (12 Threads)

### Issue description

Code generation for signals generates invalid C# code. 

While the generated function stub is fine, it's placed at the very end of the .cs file, outside of the class definition.

### Steps to reproduce

1. I have set up Visual Studio 2022 as the external editor, not sure if that matters.
2. Follow the official "step by step" guide to this step: https://docs.godotengine.org/en/stable/getting_started/step_by_step/signals.html#connecting-a-signal-in-the-editor - however, follow C# instructions instead of GDScript instructions.
3. Create a new receiver method as described in the tutorial:
![image](https://github.com/godotengine/godot/assets/3272252/d455f16e-8e34-489e-9cc2-c797c282e73b)
4. Observe that the generated code is invalid: method definition lives outside of the class definition:
![image](https://github.com/godotengine/godot/assets/3272252/4eebf512-d039-4b98-a857-3fbe90ce482c)

**Expected result:**
Method definition should be generated inside its respective class definition.

### Minimal reproduction project

Follow the official "step by step" guide, the problem is visible in this step: 
https://docs.godotengine.org/en/stable/getting_started/step_by_step/signals.html#connecting-a-signal-in-the-editor

**Comment by Chaosus** [comment] 2023-09-18 06:55
Duplicate of https://github.com/godotengine/godot/issues/18721

**Closed by Chaosus** 2023-09-18 06:55 UTC
Labels: bug, topic:dotnet
