### ISSUE TITLE
draw_rect glitch when using Viewport stretch mode, 1 px lines may not be drawn

### ISSUE THREAD

**Issue by erammos** [godotengine/godot#25565] opened 2019-02-02 02:01 UTC
**Godot version:**

V3.1.beta.custom_build.8698876 

**OS/device including version:**

Ubuntu 18.04.1 LTS - GeForce 1060  390.77 driver

**Issue description:**

When window's stretch mode is viewport, draw_rect method renders an incomplete/glitchy rectangle on preview editor 

**Steps to reproduce:**

- Project Settings->Window->Stretch Mode = viewport
- Attach a gdscript on a Node2D (which is centered on default viewport)
 `func _draw():
 	draw_rect(Rect2(Vector2(0,0),Vector2(100,100)),Color(1,0,0,1),false)`

- Play (F5)

**Minimal reproduction project:**

[draw_rect.zip](https://github.com/godotengine/godot/files/2823931/draw_rect.zip)

**Comment by clayjohn** [comment] 2020-01-13 06:28
Can't reproduce in 3.1.1 stable or on 3.2 beta6.

Windows 10. GTX 1050.

**Comment by akien-mga** [comment] 2020-01-13 08:23
I can reproduce it in the current `master` branch on Linux, both with Intel HD 630 and AMD Radeon RX Vega M (Mesa 19.3.1).

**Comment by Calinou** [comment] 2020-01-13 10:57
It sounds like a driver-specific issue again (related to OpenGL line drawing).

**Comment by KoBeWi** [comment] 2020-12-06 23:20
Fixed in 4.0

**Closed by KoBeWi** 2020-12-06 23:20 UTC
Labels: bug, confirmed, topic:rendering
