### ISSUE TITLE
Cannot find member upon updating enum / class 

### ISSUE THREAD

**Issue by Rustywolf** [godotengine/godot#77329] opened 2023-05-22 04:15 UTC
### Godot version

4.0.2.stable

### System information

Windows 10, Intel CPU, Nvidia GPU

### Issue description

Modifying a class or enum in this specific project does not update the autocomplete until a restart of godot occurs. There are seemingly unnecessary files given in the example zip, but deleting any subsection of the project seems to fix the issue. Notably, deleting the `res://scripts/game/state/` and `res://scripts/game/modifiers/` folders was fixing the issue for me. 

### Steps to reproduce

1. Open `res://scripts/constants/Enums.gd`
2. Add additional entry to ActionType enum
3. Open `res://scripts/game/actions/impl/ActionAddBlock.gd`
4. Attempt to use new enum value within file

### Minimal reproduction project

[rstcg.zip](https://github.com/godotengine/godot/files/11526931/rstcg.zip)

**Comment by Rustywolf** [comment] 2023-05-23 09:14
Issue still occurs on 4.0.3, and 4.1 dev 2

**Comment by KoBeWi** [comment] 2023-05-26 21:31
Duplicate of #76383

**Closed by KoBeWi** 2023-05-26 21:31 UTC
