### ISSUE TITLE
Add icon to Windows exported binary

### ISSUE THREAD

**Issue by pstrejczek** [godotengine/godot#1211] opened 2015-01-13 19:52 UTC
1. Windows Export doesn't have option for adding icon for the exe file
2. It would be great to have some more control over the exported application window (f.ex. disable the close button or possibility to use window without the border or use a tool window instead of normal)

**Comment by blackwc** [comment] 2015-01-25 10:58
A workaround would be [ResHacker](http://www.angusj.com/resourcehacker/). After export, just load the executable in ResHacker where you can add version information and icons.

**Comment by reduz** [comment] 2015-01-25 14:22
I tried to look for some code that allows modification of the resulting
binary without much success.. Only code that works on windows using native
windows apis, so it will only work on windows

**Comment by blackwc** [comment] 2015-01-25 14:29
What do you mean, @reduz ?

@pstrejczek the windows styles can be modified in [platform/os_windows.cpp](https://github.com/okamstudio/godot/blob/master/platform/windows/os_windows.cpp#L1065)

**Comment by okamstudio** [comment] 2015-01-25 14:53
Not the icon, metadata and signature

**Comment by pstrejczek** [comment] 2015-01-25 19:35
Thank you for the replies. I know about the workaround with some kind of resource hacker. 
I also know the close button could be disabled. I just thought it would be cool to be able to set those parameters in the project options. We have option to set the icon for other exports so it would be nice to have it also for windows.

**Comment by reduz** [comment] 2015-01-25 19:37
yeah, i just don't know how to set the icon by modifying the binary in a
portable way

**Comment by reduz** [comment] 2015-01-25 19:40
maybe this: https://code.google.com/p/portable-executable-library/

**Comment by blackwc** [comment] 2015-01-27 06:51
[This](https://gist.github.com/blackwc/e3844c1b87dfe35934ed) seems to do the trick for the icon. There's also some fixes to allow exporting with no templates installed if a custom binary is being used.

**Comment by ScyDev** [comment] 2015-06-20 15:25
I would also like to have an icon for the Windows *.exe files. 

Resource Hacker can't open the files :(
RCEdit works only on the 64bit EXE and truncates the 32bit EXE at about 5 MB (of total 80 MB).

I don't have experience really, but it would seem to me that Windows EXEs do have a standard for including icons as resources? So this should be possible to just export the icon from Godot directly without additional tools?

**Comment by akien-mga** [comment] 2015-11-06 11:53
See #2518.

**Comment by akien-mga** [comment] 2015-11-19 06:35
Fixed by #2518.

**Comment by bojidar-bg** [comment] 2016-04-04 11:14
@akien-mga ~ since that PR was reverted, maybe this should be reopened?

**Comment by akien-mga** [comment] 2016-05-19 09:04
For the reference, this used to be implemented in 1.1 using a library called `pe_bliss`. But this library brought some issues, was a bit too heavy for our small needs, so we removed it and would now prefer a lighter solution.

**Comment by ScyDev** [comment] 2016-05-19 09:16
Maybe this `pe_bliss`could be an optional download for people who want to deploy to Windows?
Like Android SDK Setup.

**Comment by akien-mga** [comment] 2016-05-19 09:17
Nope because it made bad Windows binaries, so it's not a viable solution.

**Comment by akien-mga** [comment] 2016-05-19 09:20
A better solution would be from a Windows dev to grab the relevant functions from pe_bliss and integrate them into Godot after some cleanup of the aging code. Maintaining a whole library (which is dead upstream) just to use one or two of its functions is more than we can/should handle.

**Comment by vnen** [comment] 2016-05-19 13:26
Just found a simple open source tool for this, Windows only, of course: https://github.com/atom/rcedit. This seems simple enough to even be embedded in Godot, but it requires ATL (which is not available in MinGW).

At first we can recommend this rcedit to change the icon and info for Windows exports (apart from recompiling the templates).

I might look further into this but for my brief research editing a PE seems to be more trouble than it's worth.

**Comment by ScyDev** [comment] 2016-05-19 13:30
@vnen I don't remember in detail, but rcedit corrupted by binaries when I tried it.

**Comment by surashu** [comment] 2016-07-01 09:13
@vnen I just tried out rcedit and it worked for my test exported project. Both on the 32-bit and the 64-bit executable. Good find!

**Comment by akien-mga** [comment] 2016-07-01 09:16
It could be nice to document the usage of rcedit in the page about exporting to Windows then.

**Comment by surashu** [comment] 2016-07-01 09:22
@akien-mga I've so far successfully changed the icon and the file version. I'm trying to figure out how to change the other strings too.
![bandicam 2016-07-01 17-20-31-501](https://cloud.githubusercontent.com/assets/12764163/16517505/516a171e-3fb0-11e6-8049-3bbd15f9660e.jpg)

**Comment by bojidar-bg** [comment] 2016-07-01 12:18
Hm, maybe we can reverse-engineer the place those strings are stored in the `.exe`?

**Comment by vnen** [comment] 2016-07-01 14:37
Replacing strings in a binary is always problematic, as you can break the alignment if the string size is different. But for resource strings might be different, since this seems to be what [pefile](https://github.com/erocarrera/pefile) does.

**Comment by LanceJZ** [comment] 2016-08-27 18:21
When you run the game, in the Task Manager, it is listed as Godot Engine, is there anyway to change that?

**Comment by vnen** [comment] 2016-08-28 02:50
@LanceJZ you can edit those in the same way you edit the icon: using a PE editor software or building Godot from source (you can edit the `platform/windows/godot_res.rc` file to your needs).

**Comment by vnen** [comment] 2016-08-28 02:52
As a note, there's a PE format specification provided by Microsoft: https://www.microsoft.com/en-us/download/details.aspx?id=19509

This along with pe_bliss code might be used as a reference to develop a custom solution for Godot.

**Comment by jospic** [comment] 2016-09-07 10:50
@surashu
what version of rcedit have you used?
I was build latest version from github repository but it changes .exe size...
Thanks
-j

**Comment by avril-gh** [comment] 2016-09-07 13:27
@surashu 
http://www.angusj.com/resourcehacker/

**Comment by jospic** [comment] 2016-09-07 13:56
@avril-gh
I've tried it a lot of months ago.... resource hacker not works! It alters the exe file size like rcedit

**Comment by akien-mga** [comment] 2016-09-07 14:00
Well it's normal that it alters the exe file size, since you're changing information bundled in the exe (icon, name, etc.). Of course it should not change dramatically, at most a few kB.

**Comment by surashu** [comment] 2016-09-08 04:48
@jospic Looking at the instances of `rcedit.exe` I can find in my system, apparently, it's version 0.1.0.0.

![bandicam 2016-09-08 12-40-35-649](https://cloud.githubusercontent.com/assets/12764163/18337267/8ded38b4-75c1-11e6-93e0-ed2be19dc264.jpg)

@avril-gh I read somewhere on this thread that Resource Hacker had problems interacting with the end product so I went with rcedit immediately.

**Comment by jospic** [comment] 2016-09-08 10:43
@surashu 
The version that I've compiled reports 0.2.0.0 as version number.
Please where is possible to download what do you have?
Thanks in advance.
-j

**Comment by surashu** [comment] 2016-09-08 23:33
@jospic [This one?](https://github.com/electron/rcedit/releases)

**Comment by jospic** [comment] 2016-09-09 07:41
@surashu 
This version I've tried without success a time ago! How can it works for you? I've been tested with Godot 2.1 but it not works anyway? The size of the .exe project is considerably reduced and the .exe file  can not be executed...
Any suggestions?

**Comment by Pegus1936** [comment] 2017-12-01 06:24
[this is not a high priority issue](https://www.reddit.com/r/gamedev/comments/7gmtxl/godot_30_beta_1_is_there_right_in_time_for_ludum/dqke3es/) (voting to close)

**Comment by ScyDev** [comment] 2017-12-01 11:24
@Pegus1936 It is if you're trying to release a professional looking game. Please don't close.

**Comment by akien-mga** [comment] 2017-12-01 11:25
This is indeed not a high priority issue (there are known workarounds, it's hard to fix properly and we've tried already), but it's definitely one that we want to see fixed one day. You don't get to vote on closing issues. If you think the issue is not needed, feel free to downvote it, but it's our call in the end.

**Comment by vnen** [comment] 2017-12-01 14:19
The problem with this issue is that there's no PE editing library available (at least none that I could find that isn't at least 5 years old) and making one is a daunting task. I looked into it but it's a great effort for little gain. Maybe I'll try if I find some free time for a side project.

The WinAPI can do it to an extent, but it's only available on Windows and only when built with MSVC. Would be the same as rcedit, so people can use that instead as a workaround. The easiest way is to make people download rcedit for themselves and call it with a `shell_open` during export (similar to the Android tools).

**Comment by reduz** [comment] 2017-12-01 14:34
@Pegus1936 I thought you were done with the Godot community. 

@vnen we could ask for a path to rcedit.exe so it's called on export automatically. Just calling it can change icons?

**Comment by sprite-1** [comment] 2017-12-01 15:13
@vnen if it's going to be done via rcedit downloaded separately, might as well add all the other options to the GUI like version number, company name, description, etc.

**Comment by reduz** [comment] 2017-12-01 16:24
on linux/osx i suppose rcedit can be invoked via wine, if installed.

**Comment by vnen** [comment] 2017-12-01 16:36
@reduz yeah, I think it is doable. I never used rcedit myself but people report success with it. We just need to call it with the right arguments. Would also need to ask for a `.ico` file, I think it's the only supported format.

**Comment by akien-mga** [comment] 2017-12-09 09:51
This is now fixed by #14437 by using the external (FOSS) `rcedit` Windows tool. It's not fully "out of the box" as users will still need to download this tool and set its path in their editor settings, but it's already the case for Android and not particularly an issue. It also works from macOS/Linux via WINE, albeit requires a little trick for now (check the PR), but this will be improved soon.

I'll open another issue so that we can continue investigating out of the box and cross-platform PE edition without relying on `rcedit`, but in the meantime the main use case discussed here is addressed. 🎉

**Closed by akien-mga** 2017-12-09 09:51 UTC
Labels: feature proposal, platform:windows, pr welcome, topic:porting

**Comment by nightblade9** [comment] 2019-07-05 01:17
If anyone is looking for this later, the `rcedit` settings are under Editor > Settings > Export > Windows > rcedit.

![image](https://user-images.githubusercontent.com/31222662/60691923-11f98800-9ea1-11e9-8da0-eb0cd5ed8f86.png)
