### ISSUE TITLE
How to use GodotPayments or GodotPaymentV3

### ISSUE THREAD

**Issue by vsrinu26f** [godotengine/godot#4200] opened 2016-04-02 14:03 UTC
**Operating system or device:**
Android

**Issue description** (what happened, and what was expected):
There is no example or information on using GodotPaymentV3

**Steps to reproduce:**

**Link to minimal example project** (optional but very welcome):

**Comment by akien-mga** [comment] 2016-04-02 14:05
Duplicate of #1258 and https://github.com/godotengine/godot-docs/issues/118

**Closed by akien-mga** 2016-04-02 14:05 UTC
