### ISSUE TITLE
Array needs a shuffle() method

### ISSUE THREAD

**Issue by adolson** [godotengine/godot#1027] opened 2014-12-22 06:47 UTC
We should be able to shuffle or randomize an Array by calling Array.shuffle(). 
Would also be good for many uses. Would also be handy to do things like:

for enemy in get_node("enemies").get_children().shuffle():

(get_children() returns an Array, so this should work.)

If such functionality already exists, I couldn't find it, and I also couldn't figure out how to use sort_custom() and couldn't find any documentation on it either.

**Comment by coderMess** [comment] 2015-01-02 22:33
I suggest using pointers to the first and last element of the sub-array to shuffle instead of the position of the first element and length, so it works more similarly to std::shuffle: http://www.cplusplus.com/reference/algorithm/shuffle/

**Comment by akien-mga** [comment] 2015-11-05 09:37
Duplicate of #2576 which has more input from the devs.

**Closed by akien-mga** 2015-11-05 09:37 UTC
Labels: archived, feature request
