### ISSUE TITLE
Godot 4.0 Raycast not detecting TileMap at _ready function

### ISSUE THREAD

**Issue by unlut** [godotengine/godot#75073] opened 2023-03-18 17:11 UTC
### Godot version

Godot 4.0.stable.official

### System information

Ubuntu 18, GLES3

### Issue description

I was working on converting parts of a platformer game from Godot 3 to Godot 4. In one of the scripts I perform some raycasts to detect edges/corners of the tilemap which are used for patrolling enemies etc... It was not working in Godot 4 and later I found out issue was tilemap is not being detected by raycast. This is the code from uploaded sample project:

```
extends Node2D

var counter:int = 0
@export var RAYCAST_ORIGIN:Vector2 = Vector2(0, 0)
@export var RAYCAST_TARGET:Vector2 = Vector2(4000, 4000)


func _ready():
	#await get_tree().create_timer(1.0).timeout
	var result = perform_raycast()
	print("_ready raycast result:", result, "\n")

func _process(delta):
	counter += 1
	if (counter % (32*4) == 0):
		var result = perform_raycast()
		print("_process raycast result:", result, "\n")
	
func perform_raycast():
	var state = get_world_2d().direct_space_state
	var params = PhysicsRayQueryParameters2D.new()
	params.from = RAYCAST_ORIGIN
	params.to = RAYCAST_TARGET
	var result = state.intersect_ray(params)
	return result

```

Print statement in _ready prints empty dictionary but _process one prints correct result. If I uncomment wait line in the _ready function it also works, but considering it was not required in the previous version, and it only happens with TileMap collision (for example characterbody is working fine) I assumed it is a bug?

### Steps to reproduce

Setup a scene with a TileMap and a tile with collision. Perform a raycast in _ready function that passes through TileMap. Also example project is uploaded.

### Minimal reproduction project

[tilemap_raycast_bug.zip](https://github.com/godotengine/godot/files/11009102/tilemap_raycast_bug.zip)

**Comment by AThousandShips** [comment] 2023-03-18 17:38
Is the tilemap present in the scene by that time?

**Comment by unlut** [comment] 2023-03-18 17:48
> Is the tilemap present in the scene by that time?

Yes. Tiles are painted through editor interface.

**Comment by AThousandShips** [comment] 2023-03-18 17:51
No I mean is the `TileMap` initialized yet? When `_ready` is called on a node the tree isn't guaranteed to be fully populated, for example if the `TileMap` is lower down in the tree

**Comment by unlut** [comment] 2023-03-18 17:58
Scene tree is something like this:

MainNode2D
    Node2DA
    TileMap
    Node2DB
    
I tried putting this code to _ready functions of all these nodes. All of them produce the same result, even the tilemap node itself.

**Comment by AThousandShips** [comment] 2023-03-18 18:34
The physics might not be ready by the first frame like that

**Comment by AThousandShips** [comment] 2023-03-18 18:39
Duplicate of #67679

**Closed** 2023-03-19 02:21 UTC
