### ISSUE TITLE
Xbox Series wireless controller detected as two devices

### ISSUE THREAD

**Issue by FarbrorMartin** [godotengine/godot#69257] opened 2022-11-27 14:12 UTC
### Godot version

3.5 RC4

### System information

Windows 10, GLES3, Intel HD 620

### Issue description

Xbox Wireless Controller gets detected as two controllers.

I detect connected controllers with Input, like so:
`var joypads = Input.get_connected_joypads()`
If I connect an Xbox Wireless controller i get two entries. One for an XInput Gamepad, and one for an Xbox Series Controller.
They both give input actions from the physical controller.

In a local multiplayer game this causes problems because one controller gets interpreted as two players, and thus the same physical controller controls two characters.

I have not hade this problem with my wired Xbox clone controller, my wireless 8Bitdo or my wired Xbox 360 clone controller.

### Steps to reproduce

Connect an Xbox Wireless Controller (or maybe a wired, though I have not tested this).
Get a list of connected controllers using `Input.get_connected_joypads()`
See that the list contains two entries, instead of the expected one entry.

### Minimal reproduction project

[Xbox Controller detected twice.zip](https://github.com/godotengine/godot/files/10098477/Xbox.Controller.detected.twice.zip)

**Comment by FarbrorMartin** [comment] 2022-11-27 14:29
I tested the same controller on the Gamepad Tester website, and it does not register as two devices there, but instead as a single "Xbox 360 Controller (XInput STANDARD GAMEPAD)"

**Comment by FarbrorMartin** [comment] 2022-11-27 14:37
Just tested on 4.0 beta 6 and the problem is the same.

**Comment by MicrotonalMatt** [comment] 2023-01-13 11:43
I can confirm I'm having this issue in 4.0 beta 11

**Comment by Calinou** [comment] 2023-01-13 17:00
> If I connect an Xbox Wireless controller i get two entries. 

Are you using an USB adapter or Bluetooth?

**Comment by MicrotonalMatt** [comment] 2023-01-13 22:23
The controller was connected to the computer via USB cable but was sending inputs via bluetooth. I just found that switching the usb port fixed the issue for me but I'm still not sure of the cause.

**Comment by Calinou** [comment] 2023-01-13 22:24
> The controller was connected to the computer via USB cable but was sending inputs via bluetooth. I just found that switching the usb port fixed the issue for me but I'm still not sure of the cause.

This was likely the culprit, and I'm not sure if we can do anything about it.

@FarbrorMartin Can you check whether you were charging the controller while using it via Bluetooth?

**Comment by FarbrorMartin** [comment] 2023-01-13 22:33
I’m sorry but I returned the controller, and I don’t have another one like
it. (It had some  connection issues where it constantly lost BT-connection)
It was a Xbox wireless, so I assume I connected it via Bluetooth.
If I remember correctly it worked as it should when I tested it on that
js-based web page. Can’t remember the name right now. It’s for testing
controllers. I think that one is based off the same libraries as Godot’s
controller code.
SDL?
Maybe you could test that and see if it works?

**Comment by MicrotonalMatt** [comment] 2023-01-13 22:40
I tested the controller with both usb ports on gampad-tester.com and both times it detected the controller as xinput with index 0.

**Comment by PrecisionRender** [comment] 2023-01-20 21:10
I have the same issue, but only when the controller is in Bluetooth mode. Hooking up the controller with a USB-C cable fixes the issue for me.

**Comment by PrecisionRender** [comment] 2023-01-20 22:41
Note: This seems like a duplicate of #41684.

**Comment by Calinou** [comment] 2023-01-20 23:27
Duplicate of https://github.com/godotengine/godot/issues/41684.

**Closed by Calinou** 2023-01-20 23:27 UTC
Labels: bug, platform:windows, archived, confirmed, topic:input
