### ISSUE TITLE
Some Windows show weird behaviour on Fedora 37 + KDE

### ISSUE THREAD

**Issue by leonb033** [godotengine/godot#75744] opened 2023-04-06 11:16 UTC
### Godot version

4.0.2.stable, 4.0.1.stable

### System information

Fedora Linux 37
KDE Plasma 5.27.3
Kernel: 6.2.8-200.fc37.x86_64 (64-bit)
Graphics: Wayland
GPU: AMD Radeon RX 6950 XT

### Issue description

After opening some windows like the "Create New Node" or "Open a Directory"-Window they gradually shrink to minimal height without any user input.
When manually resizing the window, only the window's contents resize but not the actual window.
Sometimes the window does resize but immediately starts shrinking again. 

https://user-images.githubusercontent.com/81116130/230362931-b59b9718-1067-4e72-982a-ca40f889ee83.mp4

### Steps to reproduce

Open "Create New Node"-Window and manually resize.

### Minimal reproduction project

N/A

**Comment by leonb033** [comment] 2023-04-06 11:20
https://user-images.githubusercontent.com/81116130/230362466-ba9d40d8-21bd-4c9e-9e48-1727822b1ed1.mp4

**Comment by Calinou** [comment] 2023-04-06 22:36
- Duplicate of https://github.com/godotengine/godot/issues/75515.

**Closed by Calinou** 2023-04-06 22:36 UTC
