### ISSUE TITLE
Dictionary mixed.

### ISSUE THREAD

**Issue by OlexiyKravchuk** [godotengine/godot#1707] opened 2015-04-18 18:16 UTC
I tried to create a dictionary for this I took turns in the loop "FOR" adds one element of the file for the cycle, and in the file, it was in this order - (0,1,2,3,4,5,6, 7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29).
But when I started to get them one by one, each element of the dictionary, then the entire order is messed up in a strange way, this - (0,1,10,11,12,13,14,15,16,17,18,19,2, 20,21,22,23,24,25,26,27,28,29,3,4,5,6,7,8,9)
  I also applied to the dictionary method keys (), which returns an array of keys, and this back even more confused the order is - (24,16,8,0,25,17,9,1,26,18,10,2, 27,19,11,3,28,20,12,4,29,21,13,5,22,14,6,23,15,7). I applied to the array function sort (), and it streamlined the array of keys, but did not solve my problem because I need is a dictionary with the correct order pairs.
I spent a test for 1.0 stable, and 1.1 beta, the results are identical

**Comment by not-surt** [comment] 2015-04-18 18:27
A dictionary is not a sequence data structure.
I have never seen an implementation on any platform that provided sequenced
retrieval.
If you want that functionality then use a sequence and dictionary in
combination.

**Comment by SuperUserNameMan** [comment] 2015-04-18 18:42
Personaly I don't care about the fact that no-one ever implemented a dictionary that keep items ordered. There is no rules in the universe that prevent to add some coherence to a Dictionnary implementation. 
It could be a useful feature.

and by the way, I already dropped some tears about it here  #1310

**Comment by not-surt** [comment] 2015-04-18 18:56
On 19 April 2015 at 04:42, SuperUserNameMan <notifications@github.com>
wrote:

> Personaly I don't care about the fact that no-one ever implemented a
> dictionary that keep items ordered. There is no rules in the universe that
> prevent to add some coherence to a Dictionnary implementation.
> It could be a useful feature.
>
> and by the way, I already dropped some tears about it here #1310
> <https://github.com/okamstudio/godot/issues/1310>
>

So everyone who only needs a standard dictionary should suffer the
corresponding performance/storage penalty?

**Comment by reduz** [comment] 2015-04-18 18:57
This is impossible to do, because Dictionary uses hashing to be able to mix
different types of keys, and not every kind of key can be compared using
operator<

**Comment by OlexiyKravchuk** [comment] 2015-04-18 19:17
@not-surt
hmm two points ...
1) What do you mean by the word, use the sequence?
2) any structure is of the order, it can not be chaos, and even in these mixed numbers, if you look closely, you will notice there is an order, it's just mixed twice, the first order is alphabetical series, and the second I can not identify the principle but it also has a structure of repeating a cycle in a spiral.
For reference, any "dictionary", "list", "linked list", "stack", "turn", a reference type containers, or other similar structure, in any case, must have serial communication circuit to have interaction and integrity because otherwise it's just not working.
Of course they can be combined in any order, of its elements in the chain, and adding to it new elements to the end or specify the position or the beginning, but the sequence of elements were present and there must be stored somehow somewhere, and I'm interested in the sequence is the order in which I write them down there, and I want to read them in the same order in which I wrote them and there, of course, if I did not make into this order additional changes, and it should be possible.

**Comment by Andi-K** [comment] 2015-08-26 16:05
> 1) What do you mean by the word, use the sequence?

I guess he meant a array, see randyyaj's comment at #1310"
I can live with this workaround.

It is nice to have a combination of dictionary and array out of the box, but the main issue is the sketchy wiki.

I didn't know the term "dictionary" and assumed it is like [PHP's (associative) arrays](http://sandbox.onlinephpfunctions.com/code/ca88775c676ff05362749f003a45f45106e82c67). 
You can add something to a dict by using ``dict["bar"] = "foo"``. That's pretty much like you do in PHP (``$dict["bar"] = "foo"``)
So a dictionary in a for loop behaved unexpected for me too.

Now, I know it is a "hash table". The Wiki should make it more clear.

In addition it's strange that a dictionary has ``erase`` function but no ``add()/append()``.
If you look only at the class description you think you have to do use to_json(), manipulate the string and  parse_json() again... -.-

**Comment by akien-mga** [comment] 2015-11-17 10:04
Duplicate of #1310.

**Closed by akien-mga** 2015-11-17 10:04 UTC
Labels: archived, topic:gdscript
