### ISSUE TITLE
Godot 3.2.1 and Godot 3.2 source code fails to compile

### ISSUE THREAD

**Issue by godotmj** [godotengine/godot#39285] opened 2020-06-04 13:26 UTC
**Godot version:** 

3.2.1 and 3.2 stable

**OS/device including version:** 

Windows

**Issue description:**

- Failed to compile source code of Godot 3.2.1 and Godot 3.2 stable versions.
- In 'crash_handler_windows.cpp' file, 'string' library is missing.

**Steps to reproduce:**
- Download source files from Git.
- Compile and compiling fails

**Minimal reproduction project:**

**Comment by akien-mga** [comment] 2020-06-04 13:48
Please include your compiler version in such reports.

But that's a duplicate of #37986 which is fixed in the current `3.2` branch.

If you want to build `3.2.1-stable` specifically, you can apply the fix manually (https://github.com/akien-mga/godot/commit/aecba58e920a2c777f2a6dc83105fd5bbdfd60c9), downgrade your VS 2019 version if possible, or wait for Microsoft to change their mind about breaking compatibility in a patch update...

**Closed by akien-mga** 2020-06-04 13:48 UTC
