### ISSUE TITLE
Image file imported incorrectly

### ISSUE THREAD

**Issue by blackears** [godotengine/godot#96145] opened 2024-08-27 05:01 UTC
### Tested versions

v4.3.stable.official [77dcf97d8]

### System information

Windows 11

### Issue description

When I try to import this GLB file, the diffuse map of the rock texture is incorrect.  It should be grey, not yellow.

### Steps to reproduce

Import the attached GLB file and add it to a scene.

### Minimal reproduction project (MRP)

https://drive.google.com/file/d/1pwfFcOOVAP-w48dDqpVXYzBAZOsmWBJv/view?usp=sharing

**Comment by yahkr** [comment] 2024-08-27 19:50
After changing the import settings on your diffuse textures to not be imported as Normal Maps the texture looks more correct:

![image](https://github.com/user-attachments/assets/14d49645-de02-4dba-be45-bbd84daa5625)

**Comment by clayjohn** [comment] 2024-09-01 06:44
Thanks for checking yahkr. Closing as the issue is comes from a misconfigured import setting, not a problem with the engine

**Closed by clayjohn** 2024-09-01 06:44 UTC
Labels: archived, topic:import

**Comment by blackears** [comment] 2024-09-01 11:52
Okay.  I never touched that setting, though.  I'm not sure why the importer decided to import that as a normal map - other gltf viewers treat it as diffuse.
