### ISSUE TITLE
Some local variables won't show up in the debugger for certain code

### ISSUE THREAD

**Issue by marcelb** [godotengine/godot#63009] opened 2022-07-14 23:45 UTC
### Godot versions tested on

3.4.4 (Standard 64bit, stable), 3.4.5 (Standard 64bit, stable), 3.5 (Standard 64bit, stable), 3.5.1 (Standard 64bit, stable), 3.5.2 (RC1 64bit, stable)

### System information

Windows 10

### Issue description

Local variables won't show up in the debugger for certain code (see reproduction)

This was seemingly reported before but was closed without a fix: #10703
There is also another issue about the debugger which seem to be unrelated though, because the debugger isn't working at all (which is not the case here): #46112

### Steps to reproduce

I took my complex project and cut it down until I ended up with a VERY simple piece of code which triggers the problem (when run attached to a scene node).

```gdscript
extends Node

func _ready():
	var result = someFunction()

func someFunction():
	var visibleVar1 = 1
	var visibleVar2 = "test"
	if visibleVar1 > 0:
		var invisibleVar1 = 0815
		var invisibleVar2 = "invisibleTest"
		return invisibleVar2 # BREAKPOINT HERE, you won't see invisibleVar1 or invisibleVar2 in locals
	else:
		pass # if you remove the else it doesn't happen
```

### Minimal reproduction project

Heres a demo project with it happening right away. Just one empty scene and one gd file:
[DebuggerBug.zip](https://github.com/godotengine/godot/files/9116646/DebuggerBug.zip)

**Comment by marcelb** [comment] 2022-08-05 19:12
This is also happening with Godot 3.4.5 and Godot 3.5.
It's not happening with Godot 4.0 Alpha 13, so it's a 3.X problem.

**Comment by marcelb** [comment] 2022-12-26 00:10
Also happening with 3.5.1 and 3.5.2 RC 1.

**Comment by Banderi** [comment] 2023-01-08 09:23
I think this is the same as #28151 and #53442. This is a crippling bug that's been around for a long time and sadly it's never been fixed, although there has been at least one PR related to this: https://github.com/godotengine/godot/pull/38608

**Comment by akien-mga** [comment] 2023-01-08 09:31
Duplicate of #53442

**Closed by akien-mga** 2023-01-08 09:31 UTC
Labels: bug, topic:gdscript, topic:editor
