### ISSUE TITLE
Bug with tween property reference in C#

### ISSUE THREAD

**Issue by Torguen** [godotengine/godot#33301] opened 2019-11-03 20:14 UTC
**Godot version:**
3.1.1 stable mono oficial
**OS/device including version:**
Win10 64

**Issue description:**
In the initialization of a tween you need a parameter that refers to the property you want to manipulate.
In the case of Label and its Rect position property, the correct mode with C # should be referenced as "RectPosition" but this does not work, however, the correct reference is "rect_position".

This is likely to happen with more properties of the same object and other objects.
For example, it also occurs with "position: x" of the sprite node (the correct mode in C# would be "Position: x").

**Steps to reproduce:**
With C#.
Initialize a tween to manipulate the position property of a label node.
You will notice that if you reference the property using "RectPosition" it does not work.
You must use the GDScript style "rect_position".

**Minimal reproduction project:**

[test.zip](https://github.com/godotengine/godot/files/3802072/test.zip)

![1](https://user-images.githubusercontent.com/19652075/68091361-0f269800-fe7f-11e9-999c-b0b7901df244.png)

**Comment by WizzardMaker** [comment] 2019-11-04 16:42
It's likely, because the Mono version of the engine is encapsulating every Property, Method, etc. to conform to the C# style of writing. We are still using the godot style of writing internally.
Your experienced behavior is also observable, when using the Call or CallDeferred methods when calling godot methods like `GetCameraPosition`, you have to use the godot style `get_camera_position`.

It's not the cleanest of solutions, but I can't see a proper way of changing this behavior.
We should make sure, that the documentation for the C# guide mentions this though

**Comment by Torguen** [comment] 2019-11-05 08:59
I understand, it would be helpful if this information appears in the documentation, newbies like me could feel very confused.

**Comment by KoBeWi** [comment] 2020-10-11 20:21
Can anyone still reproduce this bug in Godot 3.2.3 or any later release?

**Comment by KoBeWi** [comment] 2022-01-30 21:49
Closing due to lack of update bruh.
If you can still reproduce with the new Tweens in 4.0, open a new issue.

**Closed by KoBeWi** 2022-01-30 21:49 UTC
Labels: bug, topic:mono

**Comment by ptlis** [comment] 2025-02-06 20:20
I've just run into this in Godot 4.3 and so can confirm that it's still reproducible.

A minimal test case look like this:

```cs
var sprite = GetNode<Sprite2D>("Sprite2D");
var targetPosition = Vector2.Down;
var movementTween = CreateTween();

// These work
movementTween.TweenProperty(sprite, "position", targetPosition, 1);
movementTween.TweenProperty(sprite, "global_position", targetPosition, 1);

// These don't
movementTween.TweenProperty(sprite, "Position", targetPosition, 1);
movementTween.TweenProperty(sprite, "GlobalPosition", targetPosition, 1);
```
The error messages in the console from the last two statements are:

> ERROR: The tweened property "Position" does not exist in object "Sprite2D:<Sprite2D#58099500816>".
>    at: (scene/animation/tween.cpp:110)
> ERROR: The tweened property "GlobalPosition" does not exist in object "Sprite2D:<Sprite2D#58099500816>".
>    at: (scene/animation/tween.cpp:110)

**Comment by raulsntos** [comment] 2025-02-06 20:45
@ptlis That is expected behavior. The properties are defined as `position` and `global_position` in Core so that's the name you have to use to reference them by name.

To avoid having to guess what the correct name is, use the `PropertyName` class:

```csharp
movementTween.TweenProperty(sprite, PropertyName.Position.ToString(), targetPosition, 1);
movementTween.TweenProperty(sprite, PropertyName.GlobalPosition.ToString(), targetPosition, 1);
```
