### ISSUE TITLE
Slow game for Vehicle simulation 3d in some start

### ISSUE THREAD

**Issue by gra-frogger** [godotengine/godot#3845] opened 2016-02-27 08:17 UTC
**Operating system or device:**
manjaro linux 64, drivers ati open

**Issue description (what happened, and what was expected):**
In some cases the game go slow if I use the vehicle simulation

**Steps to reproduce:**
create vehicle and terrain and load scene, the bug generate randomly If you play a game, the important is that the bug start from the beginning of played session, the game go incredibly slow.

**Link to minimal example project (optional but very welcome):**

**Comment by kubecz3k** [comment] 2016-02-27 16:04
I'm very sorry but this issue don't seems to be helpful.. In reproduction steps you basically said "create a game with vehicle and expect it to be slow". There are many factors that will determine speed of your program and no-one will be able to guess what you are doing wrong, or what exactly causes your problem if you don't provide some kind of really reproducible steps or at least sample project. 
In fact there are couple of quite complicated projects that are using vehicle simulation and their creators never complain on the performance..

**Comment by ScotFlux** [comment] 2016-02-28 15:32
Dude.. I at some point agree with @kubecz3k .

1.] Performance is slow.
How can we measure if the game is slow? I guess core i7 vs amd E-450 will give a different result. GPU things (AMD Radeon 6320 vs R7)?

2.] Scenes Complexity matter.
When I use Unity. There is a doc for "how to achieve best performance". I believe every game engine has their own way to manage performance. And I'm pretty sure the more complex => more performance tricks should be done in order to achieve best performance.

**Comment by DriNeo** [comment] 2016-02-29 01:06
I encountered the same issue with a GPU Intel HD 4600. 
When the bug happens the scene runs like slow motion. The framerate remains good.

It's weird because I don't know the conditions who make the bug happens.
Just try to restart the scene several times. To save time, put the car a bit in the air, so you can check this immediately.

**Comment by DriNeo** [comment] 2016-02-29 19:05
Two additional findings.

Sometimes any rigid body could be affected by the same issue. Not at the same time than other physics bodies. It seems completely random...

I made a lot of tests in another scene and I can't reproduce the issue anymore.
The scene where the issue happens has a complex collision shape made by the import feature with the  " -col " suffixe. I removed the walls and after that, the issue can't be reproduced.

**Comment by bkeys** [comment] 2016-12-27 23:14
I would like to step in here and say that I have been experiencing the same issue. It seems like there is no concrete way to replicate this bug, it almost happens completely at random.

**Comment by ClikCode** [comment] 2017-02-03 07:52
I'm not dissaggreeing with anyone, but it's also possible that it could be the vehicle setup itself that is wrong. Please provide an example

**Comment by DriNeo** [comment] 2017-02-04 11:46
The problem on my broken scene was fixed by changing the staticbody collision shape, the vehicle settings remains the same. The old project was deleted so I can't share it anymore.
As I said before the issue happens when the terrain collision shape is generated from a complicated mesh so the 3D model needs to be very clean before using this feature.

**Comment by Calinou** [comment] 2019-12-07 15:24
Can anyone still reproduce this on 3.2beta3 or later? If so, please upload an example project and link it here.

**Comment by Calinou** [comment] 2020-04-23 07:37
I'll close this issue as no [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) was provided in time. This issue can be reopened if someone uploads a minimal reproduction project.

**Closed by Calinou** 2020-04-23 07:37 UTC
Labels: bug, confirmed, discussion, topic:core
