### ISSUE TITLE
HTML5 play button icon is blurry on high editor display scale

### ISSUE THREAD

**Issue by dzil123** [godotengine/godot#68333] opened 2022-11-06 15:23 UTC
### Godot version

4.0.beta4.official.e6751549c

### System information

Arch Linux

### Issue description

The HTML5 icon in the center here is noticeably blurrier than the other icons when the display scale is set to a high value. 
![screenshot](https://user-images.githubusercontent.com/5725958/200177567-7a514c02-678b-49d6-9e50-3abe64fcc481.png)

This is because this icon is a 16x16 png, while the other icons are svgs. Every export platform has a logo.png (used in the export window), and Android and HTML5 have run_icon.png (used as the play buttons).

All these could be replaced with svgs and made scalable.

### Steps to reproduce

Create a Web export preset.
In Editor Settings, set Editor Display Scale to 200% and restart the editor.
Observe blurry HTML5 icon in top right corner.

**Comment by Calinou** [comment] 2022-11-06 17:27
Duplicate of https://github.com/godotengine/godot-proposals/issues/2124.

**Closed by Calinou** 2022-11-06 17:27 UTC
