### ISSUE TITLE
Visual script/GraphEdit line drawing looks broken on master

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#42738] opened 2020-10-12 13:17 UTC
**Godot version:**

ab0907c

**Issue description:**

![image](https://user-images.githubusercontent.com/2223172/95750732-da7dac00-0c9d-11eb-8a53-a9f0ce7d25b8.png)
Flow arrows are invisible, some texts are unreadable and the lines have 1 width and are mostly black.

**Comment by coppolaemilio** [comment] 2020-10-22 00:19
Same in the current 3.2.4 beta1. Should I create a separate issue? or keep it here?
![beta](https://user-images.githubusercontent.com/2206700/96803591-0a9b1c80-140d-11eb-843c-abb6612641d2.PNG)

**Comment by KoBeWi** [comment] 2020-10-22 01:32
This looks related, so it can be kept here.

**Comment by Calinou** [comment] 2020-10-22 10:10
@coppolaemilio Do you have FXAA enabled? Logically, it should only apply to 3D elements (being part of the tonemapping shader), but we never know…

**Comment by coppolaemilio** [comment] 2020-10-22 22:30
@Calinou I actually don't even know where to check that 😅

**Comment by Calinou** [comment] 2020-10-22 22:32
@coppolaemilio It was added to 3.2.4beta1. You can enable it in the Project Settings.

Maybe this is a regression caused by GLES3 batching? cc @lawnjelly

**Comment by coppolaemilio** [comment] 2020-10-23 03:06
Tried changing GLES2, and GLES3, tried enabling FXAA, tried disabling FXAA, same outcome every time

**Comment by lawnjelly** [comment] 2020-10-23 07:32
Could well be a regression in 3.2.4 beta 1 if it works in earlier 3.2. However disabling batching in the editor will be interesting, due to another unrelated bug (sorry mine again lol) which makes the editor multicolored when batching is off.

This will probably have to wait till i'm home in a few days for me to look at.

**Comment by KoBeWi** [comment] 2020-11-04 23:48
Looks fine in c35517f
![image](https://user-images.githubusercontent.com/2223172/98180065-7e0a5700-1f00-11eb-8146-00535afb35b2.png)
probably due to the 2D rewrite.

Not sure if 3.2 branch is fixed too.

**Comment by lawnjelly** [comment] 2020-11-05 09:03
> @coppolaemilio FXAA was added to 3.2.4beta1. You can enable it in the Project Settings (**Rendering > Quality > Filters > Use Fxaa**).
> 
> Anyway, this might not be related to FXAA, especially if it's currently disabled. Maybe this is a regression caused by GLES3 batching. Does it improve if you disable batching in the editor in the Project Settings? Make sure to restart the editor to apply the change.
> 
> cc @lawnjelly

Sorry forgot about this issue, will look at, it may be related to another issue where I've not implemented anti-aliased polys yet, just doing that now. It is possibly something both me and juan hadn't yet implemented in the 2d in vulkan and in batching coincidentally at the same time.

To repeat Calinou's question, in 3.2.4 beta 1, is it cured by switching off batching in the editor (then restarting)? Also a small project containing something I can open that shows the problem would be welcome, I don't know how the visual script editor works.

**Comment by coppolaemilio** [comment] 2020-11-29 12:47
This is not happening to me anymore in 3.2.4.beta3
![image](https://user-images.githubusercontent.com/2206700/100542303-4c5b8600-3249-11eb-98c3-cc434484ba8b.png)

**Closed** 2020-11-29 13:22 UTC
Labels: bug, regression, topic:gui, topic:visualscript

**Comment by pycbouh** [comment] 2020-11-29 13:44
For posterity there was also #43828 which addressed the master branch recently.

As for the description in the OP here about black/invisible icons, texts and lines, I'm not sure it's related to the `GraphEdit` at all. I've seen this happen and it also affected the menus of the script editor itself, not just the internal part of the visual script's `GraphEdit`. And it also fixed itself if you closed one of the VS files or toggle between them, unreliably, but it did. So I recon it's an issue with the editor theme being propagated. I've seen it with a 3-week old master, so I'm not sure if it is fixed yet.
