### ISSUE TITLE
Copy-paste on Mac script editor

### ISSUE THREAD

**Issue by lifelike** [godotengine/godot#7185] opened 2016-11-25 10:32 UTC
**Operating system or device - Godot version:**

OS X 10.9.5, Godot 2.1.1 built from that git tag

**Issue description** (what happened, and what was expected):

Copy-paste is not working. Can't get clipboard to work in script editor at all, and not between other applications and the script editor either. Cut deletes text, but also fails to update clipboard.

**Steps to reproduce:**
1. copy (or cut) (from within script editor or in another application)
2. paste in script editor

Does not matter if using keyboard shortcuts or menu or right-click context menu.

I have the same version compiled on my Linux computer and it works fine to copy-paste there. Also never used Godot much in any previous version so I have no idea if this is something new or not but I find no existing issue.

**Comment by lifelike** [comment] 2016-11-25 12:55
I had a look in os_osx.mm where I guess the error will be, but could not see anything obvious (I have no clue about OSX programming or Objective C though). However by adding a member String variable to store the clipboard it works to copy-paste in the editor (although of course it will still not communicate with the system clipboard/pasteboard at all, so not really a fix).

**Comment by bottitytto** [comment] 2017-03-17 22:02
I am having this same problem in Manjaro Linux with Godot 2.1.2-stable.

**Comment by Calinou** [comment] 2017-03-17 22:17
> I am having this same problem in Manjaro Linux with Godot 2.1.2-stable.

Try installing the `xclip` package (using `sudo pacman -S xclip` in a terminal).

**Comment by Melix19** [comment] 2017-04-16 18:46
Tested on macOS Sierra 10.12.4 with Godot 2.1.3 stable and the latest commit of Godot 3.0 and copy-paste on script editor works fine.
Maybe it was fixed.

**Comment by Noshyaar** [comment] 2018-04-08 03:28
First of all thank you for your report and sorry for the delay.

We released Godot 3.0 in January 2018 after 18 months of work, fixing many old issues either directly, or by obsoleting/replacing the features they were referring to.

We still have hundreds of issues whose relevance/reproducibility needs to be checked against the [current stable version](https://godotengine.org/download), and that's where you can help us.
**Could you check if the issue that you described initially is still relevant/reproducible in Godot 3.0 or any newer version, and comment about it here?**

For bug reports, please also make sure that the issue contains detailed steps to reproduce the bug and, if possible, a zipped project that can be used to reproduce it right away. This greatly speeds up debugging and bugfixing tasks for our contributors.

Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

Thanks in advance.

*Note: This message is being copy-pasted to many "stale" issues (90+ days without activity). It might happen that it is not meaningful for this specific issue or appears oblivious of the issue's context, if so please comment to notify the Bugsquad about it.*

**Comment by lifelike** [comment] 2018-04-08 06:27
This does still not work for me with 3.0.2.stable.custom_build.2ff3b08 (OS X 10.12.6). I have used every official stable version since I reported this, and copy-paste never worked (other then when I edited the code as a workaround to make copy-paste work within the editor, but still not to or from other applications).

However I downloaded the official binary 3.0.2 for OS X now and that one seem to work without issues copy-paste both within Godot and from external application. Previous commenter was probably correct then that it worked in 2.1.3. But this still sounds like an issue, especially since more than one user has seen it.

**Comment by reduz** [comment] 2018-09-05 15:43
clipboard code is here:
https://github.com/godotengine/godot/blob/master/platform/osx/os_osx.mm#L1860
in case anyone wants to give it a check

**Comment by ViteFalcon** [comment] 2018-09-08 22:14
I tried this in the latest 3.1 alpha 1 version and it seems to work for me. I tried the following:

1. Copy-paste within the same script file
2. Copy-paste between script files
3. Copy from script and paste to external application (Sublime)
4. Copy from external application (Sublime) to Godot editor
5. Repeated the same steps with 'Cut' instead of 'Copy'

All of these were via keyboard shortcuts and a few steps with right-click context menu.

Other things to note:
* **Godot Renderer**: GLES2 (That's the only setting I have that is not the default in 3.1 alpha 1)
* **System**: MacBook Pro (Retina, 13-inch, Early 2015)
* **OS**: macOS Sierra
* **Processor**: 3.1 GHz Intel Core i7
* **Memory**: 16 GB 1867 MHz DDR3
* **Graphics**: Intel Iris Graphics 6100 1536 MB

@lifelike Am I missing any usecase here? Have you tried 3.1 alpha 1? Is your renderer GLES3

**Comment by remmah** [comment] 2018-10-03 16:58
@akien-mga Ok, sounds good! Pull request submitted: #22685

**Comment by samgreen** [comment] 2018-10-06 18:11
Chiming in to confirm that clipboard works for me as well on 10.13.6 with Godot 3.1!

**Comment by bojidar-bg** [comment] 2018-10-26 10:06
Seems like the PR was merged, and it worked successfully.

Going to close this issue for now, might be reopened if the fix was incomplete.

**Closed by bojidar-bg** 2018-10-26 10:06 UTC
Labels: bug, hero wanted!, platform:osx, topic:porting
