### ISSUE TITLE
[3.2.3 - "sTaBLe"] Godot Opens 'Project List' when you click Run

### ISSUE THREAD

**Issue by ThaddeusWilliams** [godotengine/godot#42519] opened 2020-10-02 21:36 UTC
Random chance that "Run" will open the Project list but keep the Editor open. Scared that when I export my game, this will just give the player another copy of Godot instead of my game... :(

**Comment by akien-mga** [comment] 2020-10-02 21:52
Duplicate of #28036.

**Closed by akien-mga** 2020-10-02 21:52 UTC

**Comment by Calinou** [comment] 2020-10-02 22:38
> Scared that when I export my game, this will just give the player another copy of Godot instead of my game... :(

This can't happen. When you export a project, you only get a PCK file that includes the resources as if they were imported by Godot.
