### ISSUE TITLE
Right dock or right part of the screen offsets

### ISSUE THREAD

**Issue by RikazuDev** [godotengine/godot#18175] opened 2018-04-13 14:31 UTC
**Godot version:** 3 ~ 3.0.2

**OS/device including version:** Windows 7 - 64 bit

**Issue description:** Godot right dock / right part offsets the screen. It somewhat resizes or like extends to the right part.

**Steps to reproduce:**
1. When accessing AnimatedSprite via Inspector:
  a,) By clicking the frames
  b.) By clicking one of the drop down list (New, Edit and etc)
Will show the lower dock that has the SpriteFrames / AnimationFrames, thus moving the right part offset the screen.

2. Changing Dock Options / Style.

**Sample Image(s)**
Before
![before](https://user-images.githubusercontent.com/23402006/38740507-54bbd3b0-3f6a-11e8-8691-736a79e2eb2d.JPG)

After
![after](https://user-images.githubusercontent.com/23402006/38740516-5948ed14-3f6a-11e8-98fd-d647a501efd1.JPG)

**Solution that sometimes work**
1. Resizing Godot window size. (But most of the time it doesn't work since the scaled or offset part is inside Godot.)
2. Changing to Fullscreen mode.
3. Restarting the application.

**Comment by eon-s** [comment] 2018-04-13 21:48
Related or duplicate of #18078.

**Comment by RikazuDev** [comment] 2018-04-14 02:34
Solution: Change HidpiMode of the Editor to VeryLoDPI then customize the font sizes

**Comment by akien-mga** [comment] 2018-04-18 11:04
Reopening as it's similar to #18078, but due to another plugin (Sprite frames editor).

**Closed** 2018-05-02 08:08 UTC
Labels: bug, topic:editor, usability
