### ISSUE TITLE
GLES2: 3d scene is extremly bright on Android

### ISSUE THREAD

**Issue by mbrlabs** [godotengine/godot#29765] opened 2019-06-13 21:20 UTC
**Godot version:**
latest master (8c11f883d9c96b08d2dd4b6bc72caf0c9d9543c5)

**OS/device including version:**
Development machine: Manjaro Linux
Target platform: Samsung Galaxy S8, Android 9

**Issue description:**
When using the GLES2 renderer on Android everything is rendered extremly bright. This only happens on Android and only with the GLES2 backend. The latest stable release (3.1.1) looks like as it should (see images below).

![android_gles2_3 1stable](https://user-images.githubusercontent.com/8750135/59466664-28766b80-8e2e-11e9-9d69-24d0e7176613.jpg)
GLES2 renderer on Android; godot.3.1.1.stable.official

![android_gles2_master](https://user-images.githubusercontent.com/8750135/59466704-447a0d00-8e2e-11e9-97a0-7e9ebe109ff2.jpg)
GLES2 renderer on Android; latest master

**Steps to reproduce:**
- Open the example project in the latest master build
- Build the android template and set it in the export settings
- Click on the Android button to build and deploy
- Everything is really bright 
- Than build and deploy that project on Android with the latest stable release and compare

**Minimal reproduction project:**
Below a very simple example with two meshes and a directional light. I disabled the effect the sky has on lighting. 

[LightingIssue.zip](https://github.com/godotengine/godot/files/3288059/LightingIssue.zip)

**Comment by KoBeWi** [comment] 2019-06-13 21:24
Duplicate of #29475

**Closed by KoBeWi** 2019-06-13 21:24 UTC
