### ISSUE TITLE
Vram compressed textures not working on iOS export with GLES2

### ISSUE THREAD

**Issue by HEAVYPOLY** [godotengine/godot#42040] opened 2020-09-14 01:18 UTC
**Godot version:**
3.2.3 RC6

**OS/device including version:**
iPad Pro 9.5" 2016
GLES2

**Issue description:**
on GLES3, Vram compressed textures work as expected.
on GLES2, with prtvc enabled, the textures don't show and I get an debug error on Xcode:

**ERROR**: Failed loading resource: res://BrushTextures/smudge_01.jpg.
   At: core/io/resource_loader.cpp:278:_load() - Condition "found" is true. Returned: RES()
 etc

<img width="784" alt="image" src="https://user-images.githubusercontent.com/24432677/93033977-5e843b80-f5ed-11ea-81d4-7ea51ae86042.png">

**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by Calinou** [comment] 2020-09-14 12:33
Duplicate of https://github.com/godotengine/godot/issues/38040, https://github.com/godotengine/godot/issues/28683 and https://github.com/godotengine/godot/issues/28669.

**Closed by Calinou** 2020-09-14 12:33 UTC
Labels: bug, platform:ios, topic:import
