### ISSUE TITLE
Vulkan: MangoHud breaks rendering unless single-window mode is enabled

### ISSUE THREAD

**Issue by Lasuch69** [godotengine/godot#57403] opened 2022-01-29 14:15 UTC
### Godot version

v4.0.alpha1.official [31a7ddbf8]

### System information

EndeavourOS(Arch linux) KDE, AMD Ryzen 5 3400g Vega11, AMDVLK 2022.Q1.1-1 64bit on Vulkan API 1.2.203

### Issue description

After opening Godot' projects lists there is dialog box asking about downloading projects from asset library or creating on your own and it doesn't load properly making UI basically useless, doesn't happen on 32bit version of the editor.
logs from the terminal:
```
Godot Engine v4.0.alpha1.official.31a7ddbf8 - https://godotengine.org
ERROR: GENERAL - Message Id Number: 0 | Message Id Name: Loader Message
        loader_scanned_icd_add: Driver /usr/lib/amdvlk64.so says it supports interface version 6 but still exports core entrypoints (Policy #LDP_DRIVER_6)
        Objects - 1
                Object[0] - VK_OBJECT_TYPE_INSTANCE, Handle 128156400
   at: _debug_messenger_callback (drivers/vulkan/vulkan_context.cpp:157)
[2022-01-29 15:10:24.472] [MANGOHUD] [info] [config.cpp:114] skipping config: '/home/boomer/Download/MangoHud.conf' [ not found ]
[2022-01-29 15:10:24.472] [MANGOHUD] [info] [config.cpp:114] skipping config: '/home/boomer/.config/MangoHud/Godot_v4.0-alpha1_linux.64.conf' [ not found ]
[2022-01-29 15:10:24.472] [MANGOHUD] [info] [config.cpp:119] parsing config: '/home/boomer/.config/MangoHud/MangoHud.conf'
Vulkan API 1.2.203 - Using Vulkan Device #0: AMD - AMD Radeon Vega 11 Graphics
[2022-01-29 15:10:24.569] [MANGOHUD] [info] [overlay.cpp:678] Uploading is disabled (permit_upload = 0)
```
 
HAPPEN ON THE RADEON DRIVER TOO!

### Steps to reproduce

Run 64bit of Godot 4.0 and load empty projects list

**Comment by Calinou** [comment] 2022-01-29 16:10
MangoHUD worked with Godot last time I tried on Fedora 34 + NVIDIA 495.46.

**Comment by afk-mario** [comment] 2022-02-14 18:01
Can confirm this happened to me and disabling MangoHud fixed it

**Comment by Calinou** [comment] 2022-02-14 19:25
> Can confirm this happened to me and disabling MangoHud fixed it

Which graphics card model and driver are you using?

**Comment by afk-mario** [comment] 2022-02-14 20:25
@Calinou 

```
OS: Arch Linux x86_64
Kernel: 5.15.22-1-lts
WM: sway
CPU: Intel i7-3770K (8) @ 3.900GHz
GPU: AMD ATI Radeon RX 470/480/
Godot: v4.0.alpha2.official [79077e6c1]
```

**Comment by CheesecakeCG** [comment] 2022-03-10 05:19
Is this still happening? I'm having a similar issue where the editor locks up with MangoHUD when you interact with anything that creates a new window while MangoHUD is enabled and Single Window Mode is disabled. 

```
OS: Arch Linux
Kernel: 5.16.13-zen1-1-zen
WM: KWin X11
CPU: Intel Xeon E3-1275 v1
GPU: AMD Radeon RX460
Godot Version: v4.0.alpha.custom_build [450ebaab9]
```

**Comment by KarolWojtasiuk** [comment] 2022-07-30 16:04
Can confirm this on:
Godot: v4.0.alpha13.official.59dcddc45
OS: Arch Linux (Kernel 5.18.14-arch1-1)
GPU: AMD Radeon RX 6900XT
Vulkan: 1.3.221
MangoHud: 0.6.7.1-4

"Please Confirm..." window does not respond to clicking, not even to the close window button, so I have to kill the process.
![image](https://user-images.githubusercontent.com/38188997/181924585-cc17b79d-8bcc-49a4-bb6a-fde6aa1f7dab.png)

Error does not occur when starting with `--single-window` and the overlay has correct size.
![image](https://user-images.githubusercontent.com/38188997/181925213-75e6b058-9692-46af-9643-8ca5ccbe5b88.png)

**Comment by TheJackiMonster** [comment] 2023-01-14 22:05
Godot: v4.0.beta12
OS: Arch Linux (Kernel 6.1.5-arch2-1)
GPU: AMD Radeon RX 6800
Vulkan: 1.3.235
MangoHud: 0.6.8-2

Dialogs on startup seem to be fine in newest beta releases with MangoHud enabled but interaction with some elements like the node graph are affected causing visual glitches and freezes (I need to kill the process actually and it ramps up cpu usage while being unresponsive).

![Screenshot from 2023-01-14 22-42-16](https://user-images.githubusercontent.com/13867397/212498780-5bb0d739-5c40-461a-9e9e-32553c52a635.png)

![Screenshot from 2023-01-14 22-45-23](https://user-images.githubusercontent.com/13867397/212498785-1247950d-2b91-4658-9b24-f39ecf4e5e76.png)

**Comment by Calinou** [comment] 2023-01-15 19:23
> Maybe as a workaround could the 4.0 release disable MangoHud until this issue is solved?

Is there a way we can do this? I've looked around and there doesn't seem to be a way to signal MangoHud (or other overlays such as RTSS) to prevent them from being added to a process.

**Comment by TheJackiMonster** [comment] 2023-01-15 20:39
> Is there a way we can do this?

At least from my experience MangoHud can be configured on a system to be used with any OpenGL or Vulkan application when the environment variable `MANGOHUD` is set to `1` (as mentioned [here](https://wiki.archlinux.org/title/MangoHud#Enable_for_all_Vulkan_games)). I'm not sure though if that's related to MangoHud itself or GOverlay (which I use for example to configure MangoHud).

So what I currently do to disable it to use Godot 4.0 is setting the variable to zero like this:
 `MANGOHUD=0 ./Godot_v4.0-beta12_linux.x86_64`

Maybe there's a better solution since that can not prevent people from starting Godot explicitly using MangoHud. But it could be a worth workaround until the issue is fixed.

**Comment by Calinou** [comment] 2023-01-15 20:45
Maybe you can try adding the following line here: https://github.com/godotengine/godot/blob/60d031777b2a922cba03210181c9ba7ad3a6f3ab/main/main.cpp#L648

```cpp
OS::get_singleton()->set_environment("MANGOHUD", 0);
```

See if it disables MangoHUD even when starting Godot with `MANGOHUD=1`.

**Comment by TheJackiMonster** [comment] 2023-01-15 21:26
Okay, so adding it right before ```engine = memnew(Engine);``` or right after that line in the main setup, it actually prevents MangoHud in the editor causing any issues.

Also I tried adding it later in the mentioned branch to only disable MangoHud in the editor. It did prevent it successfully. However the launched process from one of my games I tried running, didn't get any MangoHud overlay either. That makes sense, I assume because the process is launched by the editor with the same environment.

So I tried the following:
```
#ifdef TOOLS_ENABLED
    if (editor) {
        OS::get_singleton()->set_environment("MANGOHUD", "0");

        packed_data->set_disabled(true);
        Engine::get_singleton()->set_editor_hint(true);
        main_args.push_back("--editor");
        if (!init_windowed) {
            init_maximized = true;
            window_mode = DisplayServer::WINDOW_MODE_MAXIMIZED;
        }
    } else { 
        OS::get_singleton()->set_environment("MANGOHUD", "1");
    }
```
That works great! The glitches and freezes in the editor are prevented and I still get the overlay in the launched game.

Obviously that's not a good workaround since MangoHud shouldn't be activated/enabled when the global environment starting the editor does not enable it. But I think if the value from the environment variable could be read first by the editor and forward its value later overriding it correctly for the application, that should be a good workaround. So if there's a function like `OS::get_singleton()->get_environment()` to read the value, that should be possible.

**Comment by Calinou** [comment] 2023-01-15 22:55
> However the launched process from one of my games I tried running, didn't get any MangoHud overlay either.

This is likely because `OS.execute()` inherits environment variables from the parent process. This can likely be resolved by reading the current value of `MANGOHUD` *before* setting it to 0, storing it somewhere globally accessible (e.g. in the Engine singleton), then setting `MANGOHUD` to this previous value in `editor_run.cpp`.

**Comment by TheJackiMonster** [comment] 2023-01-16 11:26
I see.

I am not sure when you guys are planning the release date to be. So if it's not before mid February, I can probably write a patch with a proper workaround. Otherwise I would think it's totally fine to just set the environment variable to zero inside of the editor branch without the else path. Because given that it's just adding one like potentially preventing freezes, I think many users will be fine to not have the overlay in debug instances. It's still possible to use MangoHud with the exported builds anyway.

**Comment by akien-mga** [comment] 2023-01-16 11:34
I think just this should be enough and should not prevent using MangoHud when running the project from the editor / running from the command line:
```
if (editor || project_manager) {
        OS::get_singleton()->set_environment("MANGOHUD", "0");
}
```

In `main.cpp`, `editor` should only be true when actually running the editor (`Engine::get_singleton()->is_editor_hint()`), not when running the game using an editor binary. (And it should handle `project_manager` too.)

**Comment by akien-mga** [comment] 2023-01-18 08:15
Closed too early by misuse of the "fix" keyword :)

**Closed** 2023-01-19 09:18 UTC
Labels: bug, platform:linuxbsd, topic:rendering, topic:editor, confirmed, topic:thirdparty
