### ISSUE TITLE
Nodes show the icon of their script type

### ISSUE THREAD

**Issue by mieldepoche** [godotengine/godot#81276] opened 2023-09-03 16:00 UTC
### Godot version

4.1.1

### System information

linux

### Issue description

Related to #61126

when attaching a script to a node, the displayed icon is stupid (for lack of a better way to put it):
It chooses an icon matching the word after `extends` regardless of its validity as a type... (it picks it from the `editor/icons` directory it seems)

In this demo, the node is a `Node2D`:

[simplescreenrecorder-2023-09-03_17.55.26.webm](https://github.com/godotengine/godot/assets/71937306/76da88ff-9c47-44df-9252-5f6322ec839e)

as you can see extending the script with any class will make the node it's attached to use the class icon, without erroring about incompatibility (unless the word you put isn't actually a valid type).
An error happens only at runtime...

### Steps to reproduce

1. attach a script to a node
2. make the script extend any class you'd like, or put a random icon name
3. reload the scene
4. notice the icon usage

### Minimal reproduction project

any

**Comment by KoBeWi** [comment] 2023-09-03 19:35
Duplicate of #76983
This is fixed in 4.2

**Closed** 2023-09-03 20:20 UTC
