### ISSUE TITLE
Background gradient on highlighted GDScript comment text

### ISSUE THREAD

**Issue by 01010100010100100100100101000111** [godotengine/godot#66679] opened 2022-09-30 19:36 UTC
### Godot version

4.0 Beta 2

### System information

Windows 11 (22621), 3080 FE (517.48)

### Issue description

Gradient background shown when text is highlighted

### Steps to reproduce

Extract the attached project

With Godot 4 Beta 2, open the project 

Once loaded, open the test.gd script 

Start selecting (press and hold mouse 1) from the right of any on the 3 comment lines

I seem to get the below (when selecting right to left);

![1](https://user-images.githubusercontent.com/45572181/193343728-09d720b4-0ace-40d7-b40c-8284dc65b4ac.png)

![2](https://user-images.githubusercontent.com/45572181/193343740-f99863b0-2014-41d6-b771-37cf862f2ff2.png)

![3](https://user-images.githubusercontent.com/45572181/193343749-45839824-f170-44f2-93e5-59eed560ae9e.png)

![4](https://user-images.githubusercontent.com/45572181/193343755-a9eaf9f4-ff40-4300-b6b8-61c152bf3214.png)

![5](https://user-images.githubusercontent.com/45572181/193343764-b13fb5ff-4e97-4277-80d4-93076caebe29.png)

Is it just me or anyone else have the same?

### Minimal reproduction project

[HighlightGradient.zip](https://github.com/godotengine/godot/files/9687187/HighlightGradient.zip)

Edit:
(Also only seems to happen with 1 line being selected, two or more and it disappears)

Edit 2:
Actually, occurs with any multiple '*' symbols, selecting in any direction gives the same result (for me at least)

**Comment by kleonc** [comment] 2022-09-30 20:23
It's highlighting all occurences of the selected text. This can be turned off in the editor settings: `text_editor/appearance/caret/highlight_all_occurrences`.

However it indeed seem to work not as intended / not consistent as e.g. for letters it doesn't highlight overlapping occurences like in here:
![nx33Q4MQuZ](https://user-images.githubusercontent.com/9283098/193350176-e509f3d8-0632-4851-b7df-6efa7703fbf3.gif) ![zgL7IpVKXW](https://user-images.githubusercontent.com/9283098/193350033-8c9027ef-39bf-44da-ac38-1aff161bd229.gif)

**Comment by kleonc** [comment] 2022-09-30 20:31
Actually a duplicate of #59329.

**Closed by kleonc** 2022-09-30 20:31 UTC
Labels: bug, topic:editor, confirmed

**Comment by kleonc** [comment] 2022-09-30 20:44
It's fine, but for the future always try to find if the issue you're about to report is already reported. :slightly_smiling_face:
