### ISSUE TITLE
Painting a rotated or flipped tile in a Tilemap loses collision

### ISSUE THREAD

**Issue by warriormaster12** [godotengine/godot#83825] opened 2023-10-23 07:41 UTC
### Godot version

4.2 beta 2

### System information

Pop Os 22.04 lts 12th Gen Intel® Core™ i7-12700H × 20 NVIDIA RTX A2000 8GB 32.0  ram. Tested on Forward+ and Mobile

### Issue description

When painting a tile that is rotated or flipped, it looses its physics layer as demonstrated in this video:  

https://github.com/godotengine/godot/assets/33091666/c10f7325-838f-4112-b90d-0c3d9797d08f

Even though in the video I showed this only happening with one of the tiles, it happens with both of them as long as you rotate or flip it. 

### Steps to reproduce

1. Create a tilemap and a tileset
2. Create a physics layer and set collision_visibility_mode to force show. 
3. Assign just created physics layer to tiles
4. Paint the tiles and use rotate or flip tool. 

### Minimal reproduction project

[TileTest.zip](https://github.com/godotengine/godot/files/13067412/TileTest.zip)

**Comment by akien-mga** [comment] 2023-10-23 08:03
CC @KoBeWi @groud

**Comment by KoBeWi** [comment] 2023-10-23 10:01
Looks like editor-only bug. The tiles have correct collisions at runtime.

**Comment by warriormaster12** [comment] 2023-10-23 10:26
Only if you load the level directly. Calling get_tree().change_scene_from_file() breaks the collision.

**Comment by warriormaster12** [comment] 2023-10-23 10:26
Should have mentioned that

**Comment by KoBeWi** [comment] 2023-10-23 10:35
Your minimal project is a bit incomplete; you have a script for changing scenes, but it's not attached anywhere.
Anyway, I was able to reproduce the bug.

**Comment by warriormaster12** [comment] 2023-10-23 11:07
I originally intended to include a scene where you switch scenes because I thought that the issue was related to loading a scene. When I was able to produce the bug in the editor, I decided to delete the scene but forgot to do the same with the script. 

Clearly I should have kept it and mentioned it.

**Comment by dehboxturtle** [comment] 2023-10-23 16:25
I just saw this and I opened a similar ticket here. https://github.com/godotengine/godot/issues/83849

Mine has a minimal project that switches scenes and shows the breakage if you want to use that. Otherwise feel free to close the duplicate.

**Comment by KoBeWi** [comment] 2023-10-23 18:04
Removing this line fixes the issue:
https://github.com/godotengine/godot/blob/c21c2706ad33c59295f6a3ac1e128db6fa7cce69/scene/2d/tile_map.cpp#L3055
Just as I feared in https://github.com/godotengine/godot/pull/80144#issuecomment-1712308915, clearing cache at an arbitrary point will invalidate some polygons that are still in use. As a quick-fix we could remove this line at runtime to fix scene changing bug, not sure about the editor fix.

**Comment by dehboxturtle** [comment] 2023-10-23 21:29
MRP for anyone else who needs it 
[missing collisions.zip](https://github.com/godotengine/godot/files/13079344/missing.collisions.zip)

Repro steps:
1. Start game on Scene 1
2. step on the scene switch trigger in scene 1 to go to scene 2
3. Switch back to Scene 1 from Scene 2 via the scene switch trigger and observe collision boxes missing from rotated/flipped tiles.

**Comment by groud** [comment] 2023-11-15 10:39
Closing as fixed by #84261

**Closed by groud** 2023-11-15 10:39 UTC
Labels: bug, topic:physics, topic:2d
