### ISSUE TITLE
Visual Script get property class issue!

### ISSUE THREAD

**Issue by gamergamesz** [godotengine/godot#12420] opened 2017-10-26 15:41 UTC
Win10, 960m, i7

I don't know if it is the right process in VS but when i set a var(varient) for a class or simply get/call an instance of a class it show an obj input and show invalid property name error, 

![screenshot 131](https://user-images.githubusercontent.com/13883739/32062449-26a927a0-ba92-11e7-8d1b-a1da66d2ec77.png)

**Comment by fire** [comment] 2018-10-11 23:13
The cause seems to be the lack of a Object construct node. https://github.com/godotengine/godot/issues/9067

We're unable to construct a NetworkedMultiplayerENet and assign it to the variable.

I'll merge this issue with that one/

**Closed by fire** 2018-10-11 23:13 UTC
Labels: bug, discussion, topic:visualscript
