### ISSUE TITLE
Incorrect result with 2d normal mapped lighting when using a mask light and overlapped sprites

### ISSUE THREAD

**Issue by fracteed** [godotengine/godot#14361] opened 2017-12-07 04:02 UTC
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Win10 Godot beta1

**Issue description:**
As can be seen in this gif, when there is just a light2d in add mode, the result looks correct. The rock on the right overlaps the one on the left, so as the light moves across it, you cannot see the overlapped portion of the rock on the left:

![lighting1](https://user-images.githubusercontent.com/7741669/33697982-dc1b7408-db5d-11e7-8604-0adb7c3cd1d7.gif)

However, strange results occur when using a light2d in mask mode over these same normal mapped sprites. If these sprites are also lit with a light2d in add mode, the overlapping parts of the sprite start blending with each other and there is not the separation you would expect. Depending on where the light is, you will see the overlapped part  of rock left or rock right. You should only ever be seeing the overlapped part of rock right as it is on top.

![lighting3](https://user-images.githubusercontent.com/7741669/33698090-6bbeffa8-db5e-11e7-88af-210675987ceb.gif)

**Steps to reproduce:**

**Link to minimal example project:**

(https://github.com/godotengine/godot/files/1537745/normal_mapped_lighting_bug.zip)

**Comment by akien-mga** [comment] 2018-01-17 17:07
Not critical for the upcoming 3.0 release, so moving to the next milestone. A fix can still be cherry-picked for 3.0.x maintenance releases once available in the master branch.

**Comment by reduz** [comment] 2018-09-06 15:30
I think this is a duplicate, but i can't find the relevant issue. In any case, this will be fixed in 3.2 with single pass lighting, so kicking there.

**Comment by akien-mga** [comment] 2019-11-26 13:20
> I think this is a duplicate, but i can't find the relevant issue. 

Duplicate of #8685.

**Closed by akien-mga** 2019-11-26 13:20 UTC
Labels: bug, topic:rendering
