### ISSUE TITLE
set get accessors in tool scripts don't work for arrays, unless defined in separate functions

### ISSUE THREAD

**Issue by oOjor-elOo** [godotengine/godot#60968] opened 2022-05-12 12:14 UTC
### Godot version

Godot 4 alpha

### System information

Windows 10

### Issue description

In this tool script, the array's elements are not stored when saving and closing the scene. It works if the set, get are defined in separate functions.

![image](https://user-images.githubusercontent.com/105416199/168071435-d5a931bf-bde5-4ac0-a689-603c2b49aa59.png)

### Steps to reproduce

Open the example scene. 

Enter some data in the empty array: array_set_get_does_not_work.

Save the scene.

Close, and re-open the scene.

The array is now empty.

### Minimal reproduction project

https://github.com/oOjor-elOo/godot_set_get

**Comment by Calinou** [comment] 2022-05-12 15:50
Duplicate of https://github.com/godotengine/godot/issues/58285.

**Closed by Calinou** 2022-05-12 15:50 UTC
