### ISSUE TITLE
CRASH Editor 

### ISSUE THREAD

**Issue by bleknoir** [godotengine/godot#5185] opened 2016-06-13 09:57 UTC
**Operating system or device - Godot version:**
Linux

**Issue description** (what happened, and what was expected):
In script when you write this in gdscript :
                                                var variablename = variablename.
provok a violent crash without any feedback

**Link to minimal example project** (optional but very welcome):

**Comment by neikeq** [comment] 2016-06-13 10:23
It seems to be an code complete bug:

```
Program received signal SIGSEGV, Segmentation fault.
0x0000000000be11da in _guess_expression_type(GDCompletionContext&, GDParser::Node const*, int, GDCompletionIdentifier&) ()
```

**Comment by Paulb23** [comment] 2016-06-13 11:13
Duplicate / related to #4555 and #4641

**Comment by neikeq** [comment] 2016-06-13 11:19
Indeed, it's a duplicate of #4555.

**Closed by neikeq** 2016-06-13 11:19 UTC
Labels: bug, confirmed, topic:editor, topic:gdscript
