### ISSUE TITLE
Possible invalid memory read in body of is_instance_valid if check

### ISSUE THREAD

**Issue by mitchcurtis** [godotengine/godot#28191] opened 2019-04-19 07:52 UTC
**Godot version:**
v3.1.stable.official

**OS/device including version:**
MacBook Pro
macOS 10.14.4

**Issue description:**
I have the following script that spawns projectiles:

```
extends Node

var audio_player = null

func _ready():
    audio_player = AudioStreamPlayer.new()
    add_child(audio_player)

func _on_shoot(shooter, Projectile, direction, pos):
    var projectile = Projectile.instance()
    projectile.add_to_group("arrows")
    var projectile_spawn_pos_node = shooter.get_node("ProjectileSpawnPoint")
    var scene_node = owner
    scene_node.add_child(projectile)
    projectile.global_transform = projectile_spawn_pos_node.global_transform
    
    projectile.contact_monitor = true
    projectile.contacts_reported = 1
    Physics.set_item_collision_data_for_char(projectile, shooter)
    
#    var scene_spawn_pos = projectile_spawn_pos_node.global_position
    # We want to calculate the distance from the centre of the player,
    # not from the projectile spawn pos, since we use it to determine
    # the speed of the projecile, and the projectile spawn pos is not centered.
    var scene_spawn_pos = pos
    var distance = scene_node.get_global_mouse_position() - scene_spawn_pos
    projectile.apply_impulse(Vector2(), distance * projectile.speed)
    
    audio_player.stream = load("res://assets/audio/bow.wav")
    audio_player.play()
    
    var hit_ground_timer = Timer.new()
    # TODO: base this on the time the bow was pulled back
    hit_ground_timer.set_wait_time(0.6)
    hit_ground_timer.connect("timeout", self, "_hit_ground", [hit_ground_timer, projectile])
    hit_ground_timer.start()
    add_child(hit_ground_timer)

func _hit_ground(timer, projectile):
    # The arrow might have already been destroyed before it hits the ground.
    if (is_instance_valid(projectile)):
        projectile.linear_damp *= 3
    timer.queue_free()
```

I start a timer after each projectile is fired to simulate it hitting the ground. When it hits the ground, I slow it down by increasing its linear damping. When the projectile actually collides with something, I destroy it:

```
extends RigidBody2D

var speed = 10

func _ready():
    connect("body_entered", self, "_on_body_entered")
#    connect(

func _on_body_entered(body):
    # TODO: figure out a reliable way of getting velocity as a single float
    # and modify the volume of the sound effect based on that:
    # a slower-travelling arrow makes less noise when it hits something
    print("Arrow collided with " + body.get_path()
        + "linear_velocity " + str(linear_velocity)
        + " as single float " + str(linear_velocity.length()))
    #        print(body.get_path())
#        if not body.is_in_group("character"):
#            return
#        if is_owner(body):
#            return

#        if body.has_method("hit"):
#            body.hit(self)
    Audio.play("res://assets/audio/melee-wood-plastic.wav", get_tree().current_scene)
    contact_monitor = false
    queue_free()
```
The problem is that I get an error after spamming arrows:

> Invalid get index 'linear_damp' (on base: 'Node2D (PathVisualiser.gd)').

The error doesn't make sense though, because it says it's trying to access the linear_damp property on PathVisualiser.gd, which is a completely separate node in my scene, unrelated to projectiles. Each time I reproduce the problem, I see different objects reported as the base, which makes me suspect that is_instance_valid() is failing somehow and a random memory address is being read:

> Invalid get index 'linear_damp' (on base: 'AudioStreamPlaybackSample').

> Invalid get index 'linear_damp' (on base: 'CollisionShape2D').

> Invalid get index 'linear_damp' (on base: 'Timer').

> Invalid get index 'linear_damp' (on base: 'Sprite').

**Steps to reproduce:**
Run the attached project and spam left mouse button.

**Minimal reproduction project:**
[is_instance_valid.zip](https://github.com/godotengine/godot/files/3097474/is_instance_valid.zip)

**Comment by mitchcurtis** [comment] 2019-04-19 08:11
weakref() works without issues:

```
diff --git a/core/ProjectileManager.gd b/core/ProjectileManager.gd
index 1df632d..6658921 100644
--- a/core/ProjectileManager.gd
+++ b/core/ProjectileManager.gd
@@ -32,12 +32,12 @@ func _on_shoot(shooter, Projectile, direction, pos):
     var hit_ground_timer = Timer.new()
     # TODO: base this on the time the bow was pulled back
     hit_ground_timer.set_wait_time(0.6)
-    hit_ground_timer.connect("timeout", self, "_hit_ground", [hit_ground_timer, projectile])
+    hit_ground_timer.connect("timeout", self, "_hit_ground", [hit_ground_timer, weakref(projectile)])
     hit_ground_timer.start()
     add_child(hit_ground_timer)
 
 func _hit_ground(timer, projectile):
     # The arrow might have already been destroyed before it hits the ground.
-    if (is_instance_valid(projectile)):
-        projectile.linear_damp *= 3
+    if (projectile.get_ref()):
+        projectile.get_ref().linear_damp *= 3
     timer.queue_free()
```

**Comment by isaacremnant** [comment] 2019-04-19 14:39
Looks like the same as #22395.

**Comment by akien-mga** [comment] 2019-04-19 19:44
> Looks like the same as #22395.

Indeed, closing as duplicate of #22395. I'll link the MRP there.

**Closed by akien-mga** 2019-04-19 19:44 UTC
Labels: bug, topic:core
