### ISSUE TITLE
Android: `InputEventMouseMotion` not emitted after double click.

### ISSUE THREAD

**Issue by HolonProduction** [godotengine/godot#74436] opened 2023-03-05 13:32 UTC
### Godot version

v4.0.stable.official [92bee43ad]

### System information

Android 13, Mobile Renderer

### Issue description

When starting to move your finger after a touch that was a double click `InputEventMouseMotion` is not emitted.

### Steps to reproduce

- run the MRP with remote debug
- touch on the display of your phone and start moving your finger
- the console should print `"moving"`
- now touch two times and start moving your finger
- the console should print `"moving"` but it doesn't

### Minimal reproduction project

[mouse_motion_android.zip](https://github.com/godotengine/godot/files/10891907/mouse_motion_android.zip)

**Comment by akien-mga** [comment] 2023-03-05 16:34
CC @m4gr3d

**Comment by AlexandrKrivosheev** [comment] 2023-03-06 08:25
Might be same as https://github.com/godotengine/godot/issues/74358

**Comment by m4gr3d** [comment] 2023-05-08 16:12
Duplicate of https://github.com/godotengine/godot/issues/76587

**Closed by m4gr3d** 2023-05-08 16:12 UTC
Labels: bug, archived, platform:android, topic:platforms, topic:input
