### ISSUE TITLE
[Godot 4.0] If a texture is loaded on shader paramerter, the import file of it is distorted permanently.

### ISSUE THREAD

**Issue by luckyabsoluter** [godotengine/godot#74335] opened 2023-03-04 02:33 UTC
### Godot version

4.0.stable.official (92bee43)

### System information

Windows 10

### Issue description

[Godot 4.0] If a texture is loaded on shader paramerter, the import file of it is distorted immediately and permanently.
A import file of `icon.svg` is `icon.svg.import`.
if it is removed from shader parameter and save the scene and remove its import file, finally the import file will be not distorted.

Godot is not perfect.
We need `clean project`.

### Steps to reproduce

![image](https://user-images.githubusercontent.com/80892490/222871162-5b387052-be9f-4383-ba87-19444cc62f12.png)
![image](https://user-images.githubusercontent.com/80892490/222871170-0dd44178-a301-45b5-84b2-4c08e815562d.png)

### Minimal reproduction project

[shader texture distorted reproduction project.zip](https://github.com/godotengine/godot/files/10887280/shader.texture.distorted.reproduction.project.zip)

**Comment by lyuma** [comment] 2023-03-04 05:52
@luckyabsoluter Indeed, seems like a resurgence of issue #62087
Import settings before (I took the rest of the screenshot after assigning. there were no artifacts before I applied it):
![image](https://user-images.githubusercontent.com/39946030/222878611-c356d68f-1479-4bf2-bb06-c6b7db3807fb.png)

Import settings after dragging into this canvas_item material:
```
res://perfect.png: Texture detected as used in 3D. Enabling mipmap generation and setting the texture compression mode to VRAM Compressed (S3TC/ETC/BPTC).
```
![image](https://user-images.githubusercontent.com/39946030/222878542-a86a0aa0-59d8-45c4-8065-78be9484e4de.png)

**Comment by lyuma** [comment] 2023-03-04 05:54
@luckyabsoluter For now, as a workaround, set Compress Mode -> Lossless and make sure Detect 3D is set to Disabled.

**Comment by Calinou** [comment] 2023-03-04 08:27
Duplicate of https://github.com/godotengine/godot/issues/62087.

**Closed by Calinou** 2023-03-04 08:27 UTC
