### ISSUE TITLE
HTML5 export + HTTPClient = consistent failure

### ISSUE THREAD

**Issue by shecky2000** [godotengine/godot#23953] opened 2018-11-25 00:47 UTC
**Godot version:**
3.06

**OS/device including version:**
Windows 8.1

**Issue description:**
Trying to export a working Godot game w/remote DB into HTML5.  It has no problems running & accessing the remote DB when I hit "play" or export to Windows.    HTML5 exports produce errors that vary wildly according to browser and deployment methods:

--HTML5:  Run in browser 
[FF Quantum 61.0.1 (64-bit)]: 
I get an "assertion failed" error.
--HTML5: Deploy to server (with all files in the same folder)  
[Opera Version:56.0.3051.104]
Failed loading file 'filename.wasm': Not Found
[FF Quantum 61.0.1 (64-bit)]: 
Failed loading file 'filename.pck': Not Found
[Chrome Version 70.0.3538.110 (Official Build) (64-bit)]
Failed loading file 'filename.pck': Not Found

Was originally assuming this had something to do with the remote DB but, given that I'm getting these three very different errors, I now have absolutely no clue.  

**Steps to reproduce:**
1) load the attached minimal project
2) Try export to HTML5.   You will get the "assertion failed" efrror
3) Upload to a server
4) Use the different browsers and you will get the identical variety of errors

Thanks!

**Minimal reproduction project:**

[minimal.zip](https://github.com/godotengine/godot/files/2612714/minimal.zip)

**Comment by eska014** [comment] 2018-11-28 10:34
Cross-origin requests aren't allowed from `file://`, so the failure without server is expected.

Can't reproduce the *Not Found* errors with Python's built-in HTTP server, probably a configuration issue with your server

**Comment by shecky2000** [comment] 2018-11-28 20:51
@eska014 Thanks, but that's not the case.   Uploaded to the source server and put everything in the same folder.   In that case, there was no file:// used.   Still, got the WASM and PCK errors.

**Comment by shecky2000** [comment] 2018-12-04 02:04
Okay, did you guys refuse this bug?  It's real and has been quite time expensive for me (a couple pure weeks).  I really hope this is just me missing something, but I'm truly stuck.   Been working on this project for a very long time and, once I discovered the easy method of getting remote data didn't work on HTML5, I converted to this.  It just added 3 new errors like an indecipherable hydra.    Please don't dismiss this.   Really lost a lot trying to solve this.  Thank you!

**Comment by LikeLakers2** [comment] 2018-12-04 03:01
Unless the issue gets closed by someone, you shouldn't consider a bug "refused". Please do remember that only so many issues that can be worked on at once (since there's only so many people contributing to the issue).

That said, I tried replicating this on my own. Here's my findings:


When I double-click the HTML file and open it locally in Chrome (from `file://`), I receive the "File not found" error that you described, along with the "Cross origin requests" error in Chrome's console that @eska014 described:
<details><summary>Results from running locally</summary>

 
![image](https://user-images.githubusercontent.com/1008889/49415696-76a30780-f745-11e8-8d27-b79d869b0faf.png)

![image](https://user-images.githubusercontent.com/1008889/49415750-9afee400-f745-11e8-9791-ddb2da13aa4f.png)

(and a text version of that second screenshot, in case the image isn't readable on your device)
```
minimal.js:352 Access to XMLHttpRequest at 'file:///E:/Godot/Bug%20Report%20Projects/minimal%20exported/minimal.pck' from origin 'null' has been blocked by CORS policy: Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https.
[...]
minimal.js:352 Access to XMLHttpRequest at 'file:///E:/Godot/Bug%20Report%20Projects/minimal%20exported/minimal.wasm' from origin 'null' has been blocked by CORS policy: Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https.
```
</details>

<br>When I run it locally using a Python webserver, the browser then allows the requests to `minimal.pck` and `minimal.wasm`, allowing the game to run (as @eska014 described):
<details><summary>Results from hosting locally</summary>

![image](https://user-images.githubusercontent.com/1008889/49415871-fcbf4e00-f745-11e8-8883-d07a55e27936.png)
</details>

<br>I then uploaded the files to my own remote server, and ran a Python webserver on that, receiving the same results as when I ran it locally:
<details><summary>Results from hosting remotely</summary>

![image](https://user-images.githubusercontent.com/1008889/49416003-78b99600-f746-11e8-82e2-352bb5edc18d.png)
</details>

<br>Now I might be wrong here, but I imagine that something is actually up with your server's configuration, since I was capable of replicating @eska014's findings. Perhaps check the server's configuration? Or if you aren't the one running the server, bring up the issue with whoever is running the server.

**Comment by shecky2000** [comment] 2018-12-04 14:49
@LikeLakers2 Wow, thank you for the work!   I'm still learning Github as I code, so I guess I didn't understand how this all operates.     Interesting about the server configuration.   Not exactly sure what to ask the ISP to do, but it's a lead.   Appreciate your starting me in the right direction.

**Closed** 2019-01-31 11:13 UTC
Labels: bug, platform:html5, topic:porting
