### ISSUE TITLE
Black screen opening a Godot project on macOS

### ISSUE THREAD

**Issue by Melix19** [godotengine/godot#7847] opened 2017-02-19 19:43 UTC
**Operative system:**
macOS Sierra 10.12.3

**Godot version:**
Godot 3.0 (5e3fc7d)

**Issue description:**
Opening Godot, it shows the project manager, but opening a project it shows a black screen.

**Steps to reproduce:**
Build the lastest Godot commit on macOS, create a new project and open it.

**Comment by Melix19** [comment] 2017-02-19 20:23
I noticed that to solve this problem, just press the full screen button on Godot's app and it shows its interface instead of the black screen.

**Comment by bojidar-bg** [comment] 2017-02-19 20:53
Duplicate of #7663 as far as I can see.

**Closed by bojidar-bg** 2017-02-19 20:53 UTC
Labels: archived

**Comment by CharlesWoodhill** [comment] 2017-03-12 15:02
same behaviour on windows, just refreshed repo (master), built it and still there:

black screen after open project, toggle fullscreen fix it.

**Comment by bojidar-bg** [comment] 2017-03-13 10:19
@CharlesWoodhill Please, comment on the other issue, this one has been marked as a duplicate.
