### ISSUE TITLE
Internationalization issue, zh_CN is loaded instead of zh_HK, and reciprocally

### ISSUE THREAD

**Issue by lefay1982** [godotengine/godot#26346] opened 2019-02-27 10:31 UTC
**Godot version:**
Godot 3.1 beta8

**OS/device including version:**
Windows 7 x64
Windows 10 x64

**Issue description:**
I have a text.csv with three language en, zh_CN, zh_HK  

when i use  `TranslationServer.set_locale("zh_CN")` godot display the zh_HK's text

then i use  `TranslationServer.set_locale("zh_HK")` godot display  the zh_CN's text

finally i use `TranslationServer.set_locale("en")` godot display the correct en's text

the three  en.translation, zh_CN.translation, zh_HK.translation file is correct and the text.csv is correct.

**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by akien-mga** [comment] 2019-02-27 10:40
Could you provide a small project that reproduces the bug?

**Comment by lefay1982** [comment] 2019-02-27 11:42
a small international demo project is here:

[transDemo.zip](https://github.com/godotengine/godot/files/2910098/transDemo.zip)

**Comment by lefay1982** [comment] 2019-02-27 11:46
zh_CN change to zh the error is same.

**Comment by lefay1982** [comment] 2019-03-09 05:48
@akien-mga    Why not fix it in milestones 3.1 ???

**Comment by akien-mga** [comment] 2019-03-09 11:19
Because we're running out of time, and the bug already exists in 3.0 too, so it's not a recent regression.

It might still be fixed shortly after 3.1 and backported to a 3.1.x release.

**Comment by lefay1982** [comment] 2019-03-10 07:36
OK, Thanks

**Comment by lefay1982** [comment] 2019-03-10 07:36
OK, Thanks

**Comment by akien-mga** [comment] 2019-08-08 08:20
Should be fixed by #31198, sorry for the delay.

**Closed** 2019-08-08 08:49 UTC
Labels: bug, topic:core
