### ISSUE TITLE
GD.Randf() causes black screen in html5 project

### ISSUE THREAD

**Issue by MakovWait** [godotengine/godot#41210] opened 2020-08-12 22:50 UTC
**Godot version:** 3.2.2.stable.mono

**Issue description:** usage of GD.Randf() causes black screen in html5 project. Without it all works perfectly.

**Steps to reproduce:**
1. Call GD.Randf() in any .cs script.
2. Export project with html5 template.

**Minimal reproduction project:** [randf_test.zip](https://github.com/godotengine/godot/files/5066297/randf_test.zip)

Windows and Linux exporting works as expected.

Thank you!

**Comment by mariothedog** [comment] 2020-10-11 20:19
I can confirm this bug still occurs in 3.2.3.stable.mono.

**Comment by Calinou** [comment] 2020-10-11 21:05
cc @neikeq

**Comment by neikeq** [comment] 2020-12-14 18:48
Closing as duplicate of #36858 (same cause)

**Closed by neikeq** 2020-12-14 18:48 UTC
Labels: bug, confirmed, platform:html5, topic:mono
