### ISSUE TITLE
Strange panel with resize handle left to the scene viewport

### ISSUE THREAD

**Issue by matrem** [godotengine/godot#13420] opened 2017-11-30 20:22 UTC
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Windows 10 64bits godot beta 1 mono

**Issue description:**

A strange empty panel with resize handle is available left of the scene viewport. When pulled completly to the right, when can't see the scene no more, even when the resize handle is pulled to the left.

**Steps to reproduce:**

**Link to minimal example project:**

**Comment by Zylann** [comment] 2017-12-01 00:38
Already reported https://github.com/godotengine/godot/issues/13197

**Comment by groud** [comment] 2017-12-01 02:13
Closing as a duplicate of #13197

**Closed** 2017-12-01 02:14 UTC
