### ISSUE TITLE
Control Viewport resets position when stretched

### ISSUE THREAD

**Issue by TheoXD** [godotengine/godot#5141] opened 2016-06-10 14:44 UTC
Basically when "stretch_mode" is set to "viewport" in project settings, all controls that have viewport as a child reset their position to top left corner of the screen and never move. You can try with this test scene http://blenderstars.com/uploads/tmp/viewport_bug.zip, just go to project settings and change stretch mode, the cube will always be floating when scrolling.

**Comment by reduz** [comment] 2016-06-11 19:47
viewport stretch mode is kind of broken, again it's really difficult to fix in GLES2, so it will be rewritten/changed for 3.0

**Comment by reduz** [comment] 2017-08-05 12:23
duplicate of #1571

**Closed by reduz** 2017-08-05 12:23 UTC
Labels: bug, topic:core, topic:rendering
