### ISSUE TITLE
[feature request] Godot Editor - add Godot version number in title bar

### ISSUE THREAD

**Issue by randibit** [godotengine/godot#28946] opened 2019-05-16 23:29 UTC
**Godot version:**
All (new versions)

**OS/device including version:**
n/a

**Issue description:**
Godot Editor does not show the version number in the title bar.
(can be confusing when tutorial videos are not mentioning what version they are using)

Justification:
Having a minor feature added to clarify the version listed in the title bar would help when watching tutorial videos (ie. YouTube, Udemy, etc.).  GDScript issues can occur when using the incorrect version of the Godot Game engine and cause confusion.

**Steps to reproduce:**
Open Godot Editor

**Minimal reproduction project:**
Open Godot Editor

Thanks for the consideration.

**Comment by clayjohn** [comment] 2019-05-17 04:22
Duplicate of https://github.com/godotengine/godot/issues/27811

Thanks for the suggestion, but there is already an issue for this. Please search existing issues before creating one of your own.

**Closed by clayjohn** 2019-05-17 04:22 UTC

**Comment by randibit** [comment] 2019-05-17 20:14
Good to hear, sorry for the duplicate, I guess I didn't search well enough for a previous issue.

Thanks

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
