### ISSUE TITLE
call_deferred() on lambda functions in a thread causes crash

### ISSUE THREAD

**Issue by raccoon-path** [godotengine/godot#84325] opened 2023-11-01 20:46 UTC
### Godot version

v4.2.beta4.official [93cdacbb0]

### System information

Windows 10, Vulkan API 1.3.260,  Forward+, NVIDIA GeForce RTX 2080

### Issue description

Since **4.2-beta3**, Godot crashes when lambda function called through `call_deferred()` from thread. May be ralated to: #83486 or #81628, but I'm not sure.

This code causes crash:
```gdscript
#Func runs in a thread
func thread_func()->void:
    (func(): do_something()).call_deferred()
```
But this code works as expected:
```gdscript
#Func runs in a thread
func thread_func()->void:
    do_something.call_deferred()
```

### Steps to reproduce

1. Create a script (extends any node type) and add it to Node
2. Write the thread func:
```gdscript
#Runs in thread
func thread_func()->void:   
    #Any of following code blocks causes crash
    var lambda := func(): do_something()
    lambda.call_deferred()
    
    #It crashes too
    (func(): do_something()).call_deferred()
    
    #Let's remove everything unnecessary...  crashes too
    (func():return).call_deferred()
```
3. Start the thread: 
```gdscript
var thr:= Thread.new()
thr.start(thread_func)
#or
var id := WorkerThreadPool.add_task(thread_func)
```
5. It doesn't matter whether we are waiting for the thread to complete or not, the bug always occurs

### Minimal reproduction project

[LambdaInThreadBugMRP.zip](https://github.com/godotengine/godot/files/13231289/LambdaInThreadBugMRP.zip)

**Comment by AThousandShips** [comment] 2023-11-01 20:47
Duplicate of https://github.com/godotengine/godot/issues/84046

**Closed by AThousandShips** 2023-11-01 20:47 UTC
