### ISSUE TITLE
"No loader found" error occuring when loading images.  

### ISSUE THREAD

**Issue by stubbsy345** [godotengine/godot#18158] opened 2018-04-12 19:34 UTC
At random point I am encountering the following error:

0:00:29:0950 - No loader found for resource: res://Graphics/Images/Image1.jpg
----------
Type:Error
Description: No loader found for resource: res://Graphics/Images/Image1.jpg
Time: 0:00:29:0950
C Error: Method/Function Failed, returning: RES()
C Source: core/io/resource_loader.cpp:186
C Function: _load

Godot Version 3.02. 

The error appears at random occasions when loading a jpg into the TextureRect node. It seems to be occurring at random times as it works a lot of the time but on some occasions does not. 

To reproduce repeatedly load a jpeg image into a TextureRect node.

**Comment by Megalomaniak** [comment] 2019-01-07 10:09
I can confirm too, a user on the forums supplied a project that has this issue in exported game.
https://godotdevelopers.org/forum/discussion/comment/26585#Comment_26585

**Comment by Megalomaniak** [comment] 2019-01-07 10:13
Forgot to add, that I tested the project export in 3.0.6

**Comment by KoBeWi** [comment] 2019-04-29 23:29
Yeah, the error doesn't seem to happen when trying to reproduce what is described in OP (3.1).

If the issue is about broken dependencies after renaming resources externally, then this case is covered by #15673

**Comment by KoBeWi** [comment] 2020-07-10 10:45
Can anyone still reproduce this bug in [Godot 3.2.2](https://godotengine.org/article/maintenance-release-godot-3-2-2) or any later release?

If yes, please ensure that an up-to-date Minimal Reproduction Project (MRP) is included in this report (a MRP is a zipped Godot project with the minimal elements necessary to reliably trigger the bug). You can upload ZIP files in an issue comment with a drag and drop.

**Comment by KoBeWi** [comment] 2020-09-28 13:05
Closing due to lack of update. Please comment if you can still reproduce this issue in the latest stable version of Godot.

**Closed by KoBeWi** 2020-09-28 13:05 UTC
Labels: bug, topic:import
