### ISSUE TITLE
[Godot 4] Reload newer files from disk doesn't work as expected

### ISSUE THREAD

**Issue by DaSlang** [godotengine/godot#65537] opened 2022-09-08 20:00 UTC
### Godot version

4.0 alpha 16 ```86dd3f312```

### System information

Mac OS Monterey 12.2.1 (21D62)

### Issue description

Whenever it's required to reload a file from disk, the dialog window appears correctly, but the "Reload" button doesn't work.

I'm trying to reload a GDScript file edited using an external editor: the content of the file is not reloaded, and it's necessary to click the "Reload" button two times to close the dialog.

### Steps to reproduce

1. Create a new script
2. Edit the script using an external editor
3. Reload the content of the file

### Minimal reproduction project
It's just a new Godot 4 project with a simple test script

[reload-error.zip](https://github.com/godotengine/godot/files/9530258/reload-error.zip)

**Comment by tinmanjuggernaut** [comment] 2022-09-13 00:33
Duplicate of #59115?

**Comment by Rindbee** [comment] 2022-09-25 16:05
The issue of GDScript's external editing not being synced will be resolved by #63224 or #66405.

For text files, some extra work is required, and that might be a different issue.

**Comment by akien-mga** [comment] 2022-09-26 06:28
Fixed by #63224 and #66405.

**Closed by akien-mga** 2022-09-26 06:28 UTC
Labels: bug, topic:editor
