### ISSUE TITLE
Documentation not showing

### ISSUE THREAD

**Issue by BastiaanOlij** [godotengine/godot#12621] opened 2017-11-04 00:47 UTC
On todays master, I am not ruling out that I'm doing something wrong here however I am not seeing much of the documentation in editor help.

For instance, check this help page online:
http://docs.godotengine.org/en/latest/classes/class_arvrserver.html
Which shows all the information I expect to see and is in the XML files.

Check the same help page in the editor:
![editor help](https://user-images.githubusercontent.com/1945449/32400577-f36f68d4-c155-11e7-8441-98b9df6344ce.png)

I'm not seeing any of the info...

**Comment by bruvzg** [comment] 2017-11-04 14:26
Similar to #12584? Check for non .xml files in `/doc/classes`.

**Comment by akien-mga** [comment] 2017-11-08 10:13
Duplicate of #12584 (please comment/reopen if it's not the case).

**Closed by akien-mga** 2017-11-08 10:13 UTC
Labels: bug, documentation, topic:editor
