### ISSUE TITLE
Unwanted line breaks/formatting bugs in-app documentation pages

### ISSUE THREAD

**Issue by chrisoffner** [godotengine/godot#55057] opened 2021-11-17 13:56 UTC
### Godot version

3.4.stable [206ba70f4], 

### System information

macOS Monterey, MacBook Pro (13-inch, M1, 2020)

### Issue description

I just opened up Godot for the very first time and noticed these strange formatting issues, most notable on the `float` and `Vector2` labels. It happens both on the mono branch and the standard branch:

![](https://i.imgur.com/Ko6tFus.png)
![](https://i.imgur.com/NFHSk44.png)

### Steps to reproduce

1. Open Godot
2. Open an in-app documentation page
3. Observe strange line breaks that break text in the left type column and ruin the overall formatting

**Comment by Calinou** [comment] 2021-11-17 14:14
This is a duplicate of another issue, but I can't find it right now.

**Closed** 2021-11-17 14:15 UTC
Labels: bug, topic:editor
