### ISSUE TITLE
Pixel Snap not working (Tilemap borders visible again)

### ISSUE THREAD

**Issue by zzz-assault** [godotengine/godot#26730] opened 2019-03-06 20:57 UTC
**Godot version:**
- 3.1 (Beta 11) - 2D

**OS/device including version:**
- Windows 10
- RTX 2080
- I7 8700

**Issue description:**
- Tiles of Tilemap have sometimes visible borders, while camera moving. This effect was corrected by "Pixel Snap" … but since Beta 11 (just switched a moment ago from Beta 10 to 11) it's not fixing the issue anymore.

![screenshot_visible-tile-border](https://user-images.githubusercontent.com/47723585/53913083-c2be5a80-405a-11e9-97f2-f3478f68241d.png)

**Steps to reproduce:**
- create a new project with tileset (tiles should be > 128x128) and creating a small tilemap with it
- add kinematic body (include standard move script -> i.e. from demo project) and attach camera2D

**Comment by Sslaxx** [comment] 2019-03-06 21:21
Interesting. With one of my projects, pixel snap had been off, but with beta 11 it started showing glitches until I enabled pixel snap. Previous betas hadn't shown any issue.

**Comment by girng** [comment] 2019-03-07 02:11
regression from https://github.com/godotengine/godot/pull/26567?

**Comment by clayjohn** [comment] 2019-03-07 05:32
@zzz-assault Can you upload an minimal reproducible example, I'm having trouble reproducing the issue. 

But I think @girng is right. #26567 is likely the cause. But it means that the whole pixel snapping issue is more complicated than it seems.

**Comment by zzz-assault** [comment] 2019-03-07 09:29
I'll tried to reproduce the issue with a minimal project ... but also wasn't able to get the effect.

So I reduce my project to a minimum and the error seems to be connected to the spritesheet size ... really strange ... will upload a sample project this evening.

**Comment by CptPotato** [comment] 2019-03-07 13:03
I've seen similar artifacts as described in #26467 in a few games (Godot included). Mainly ones made in Gamemaker, but also some things that I was working on in a different engine. For me it results in a sporadic 1px offset along the diagonal of the viewport when using non-integer scales:

![corners](https://user-images.githubusercontent.com/3957610/53958459-66524e00-40e1-11e9-9ada-549b5470d38d.png)

From my experience this happens when you use "nearest-neighbour" filtering with non-integer scaling. The only way I could ever get rid of these was through assisting the nearest-neighbour filter by rounding the UV coordinates to the nearest pixel center myself.

**Comment by nightblade9** [comment] 2019-03-07 13:42
Might be related to my issue (#26734), but in that case, seams only appear when zoomed. Without pixel snapping, any time you move the camera, you see the seams.

**Comment by clayjohn** [comment] 2019-03-07 15:41
@zzz-assault if you haven't tried already, try reimporting the tilemap with filter and mip maps disabled.

**Comment by zzz-assault** [comment] 2019-03-07 15:59
You mean the spritesheet? ... I'll try when I'm back home.

**Comment by clayjohn** [comment] 2019-03-07 16:07
Yes, sorry, the spritesheet. It could be similar to #26734 which was fixed by reimporting without filter.

**Comment by zzz-assault** [comment] 2019-03-07 20:07
Tested positivly … removing filter & mipmap fixed the issue.

Is this by intend or do you still need a sample project to check the issue with activated mipmap & filter? 

I would prefer to use both options, as I use a trick by scaling up the tilemap (2.0, 2.0) and zooming out (2.0, 2.0) the camera (which helps for other effects) … so (if my understanding is correct) both options increase graphics quality in my case.

**Comment by clayjohn** [comment] 2019-03-07 20:12
Since you are zooming out, try it with mip maps and without filter. It may work fine for your needs.

I dont need a sample project anymore, thanks!

The issue here is with the way that filtering is implemented in OpenGL. Im not sure why you didnt see issues arise in previous versions. The fix for this problem actually needs to come from the way you design your assets. If you want to filter tilemaps like this, you should have a one-pixel transparent border around each tile that is the same color as its neighbouring tile. This is a common problem with spritesheets in all game engines.

**Comment by zzz-assault** [comment] 2019-03-07 20:36
Thx, didn't know this … as described no issue from 3.0.6 - 3.1 (Beta 10) … and I almost tested all Beta Versions. In addition my understanding was, that Pixel Snap exactly counters such issues.

But yes I will go for removing Filter for this Tilemap, just tested and also with MipMaps active, it's fixed.

**Comment by clayjohn** [comment] 2019-03-07 20:43
pixel snap snaps the vertices to pixel coordinates so you dont see lines appear between tiles as the camera moves. You may still want it to be active. 

Im not sure why pixel snap affected things before for you. But im glad things are working now! :)

**Comment by zzz-assault** [comment] 2019-03-07 22:19
Yeah … thx for your help … issue can be closed (at least from my perspective) … :)

**Closed** 2019-03-08 08:18 UTC
Labels: bug, topic:rendering
