### ISSUE TITLE
Remote view does not show on second project when running two projects at the same time

### ISSUE THREAD

**Issue by Syraleaf** [godotengine/godot#44967] opened 2021-01-06 16:56 UTC
(I tried really hard to find this but I don't think it's reported yet? Feels like something that is known but here we go regardless. Sorry for the potential dupe in advance!)

**Godot version:**
V3.2.3.stable.official

**OS/device including version:**
Windows

**Issue description:**
Playing the game in a second instance of the editor does not give me a remote view. 
![image](https://user-images.githubusercontent.com/13417427/103796866-095eb080-5048-11eb-9365-2887ce7a98a8.png)
As you can see here the left one does not have a remote (scene) view. The right one does. I started the one on the right first. 

**Steps to reproduce:**
Create two projects
Open the editor for each project
Play the first one (this one has a remote)
Play the second one (this one bugs out and has no remote)

**Minimal reproduction project:**
I've tried this in various projects and all of them have it. An empty project with a Node2D base is enough to trigger this bug. 
This bug has been around since V3.1-beta1 (windows)

**Comment by Calinou** [comment] 2021-01-06 17:57
Duplicate of https://github.com/godotengine/godot-proposals/issues/1335 (same cause).

**Closed by Calinou** 2021-01-06 17:57 UTC
