### ISSUE TITLE
Highlight rectangle in the About dialog is not clipped outside the ItemList

### ISSUE THREAD

**Issue by karroffel** [godotengine/godot#9612] opened 2017-07-11 23:24 UTC
**Operating system or device - Godot version:** v3.0.alpha.custom_build a7d1c90

**Issue description:**

If you select a section in the about window in the editor it gets highlighted. If you scroll up or down then that highlight does not respect the window boundaries.

![screenshot from 2017-07-12 01-20-40](https://user-images.githubusercontent.com/5209613/28095089-d152b9dc-66a0-11e7-8007-385dd4810d66.png)
![screenshot from 2017-07-12 01-20-47](https://user-images.githubusercontent.com/5209613/28095092-d32db720-66a0-11e7-86e4-71b83f94a5ca.png)

**Steps to reproduce:**
Open about window, select a section and scroll around 😄

**Comment by karroffel** [comment] 2017-07-11 23:25
cc @Noshyaar

**Comment by Noshyaar** [comment] 2017-07-11 23:59
I think it's the bug with ScrollContainer not clipping highlight correctly. I've tried to replicate the scene in CanvasItemEditor and the issue is there. It probably affects every controls with highlight, not only ItemList.
![image](https://user-images.githubusercontent.com/26753932/28095882-257478e2-66cf-11e7-9060-0ceeccaf6ea0.png)

**Comment by Noshyaar** [comment] 2017-07-23 06:32
This is the lines that cause the issue:
https://github.com/godotengine/godot/blob/master/scene/gui/rich_text_label.cpp#L647
https://github.com/godotengine/godot/blob/master/scene/gui/item_list.cpp#L775
https://github.com/godotengine/godot/blob/master/scene/gui/tree.cpp#L2816

Deleting it works for 3.0 editor theme and About dialog, but not for default project theme. (control's own clip makes the rectangle too thin)

**Comment by akien-mga** [comment] 2017-10-31 09:59
Reopening as the PR was reverted.

**Comment by Noshyaar** [comment] 2017-12-29 12:16
This is "Fixed" in EditorAbout by not showing the outline at all, but the issue still exists.

**Comment by akien-mga** [comment] 2018-01-09 17:02
We have now entered release freeze for Godot 3.0 and want to focus only on release critical issues for that milestone. Therefore, we're moving this issue to the 3.1 milestone, though a fix may be made available for a 3.0.x maintenance release after it has been tested in the master branch during 3.1 development. If you consider that this issue is critical enough to warrant blocking the 3.0 release until fixed, please comment so that we can assess it more in-depth.

**Comment by reduz** [comment] 2018-09-05 16:47
Too difficult to work around, kicking to 3.2 since most of this code will be re-written

**Comment by mrcdk** [comment] 2019-05-25 08:59
I've been hit with this issue too and, yes, a good fix is too difficult. The main issue is that when you enable `clip_contents` (and `ItemList` enables it by default) anything outside of the control's size will be clipped. This affects the whole control including the applied `StyleBoxes` that can add an extra margin around them. The only solution I can think of is to have 2 rects, one keeping the size of the control and the other keeping the size of the styleboxes and draw the control first with the stlyeboxes without clipping and then the content with it clipped to the control size. I don't know how could we do this.

In the meantime, because this is a bigger issue that affects all controls (well, `CanvasItems` because they are the one in charge of drawing the styleboxes), I think we can remove the exception in the `ItemList` for now because it's making it unusable right now if you apply any focused `StyleBox` to it and it gets clipped by another control.

**Comment by pycbouh** [comment] 2021-06-20 00:10
This issues seem to have reappeared a lot more prominently in master, as I think it's the same as https://github.com/godotengine/godot/issues/36164.

**Comment by akien-mga** [comment] 2021-09-27 08:01
Duplicate of #36164 indeed.

**Closed by akien-mga** 2021-09-27 08:01 UTC
Labels: bug, topic:gui
