### ISSUE TITLE
Keyboard shortcuts in Animation Editor remain active while multiple Viewports are active and in Freelook mode

### ISSUE THREAD

**Issue by swfira** [godotengine/godot#74998] opened 2023-03-16 19:32 UTC
### Godot version

4.0.1.rc1

### System information

Windows

### Issue description

The keyboard shortcuts for playback (A, S, D, Shift+A, Shift+D) in the Animation Editor remain usable while in Freelook mode in a 3D Editor Viewport when multiple viewports are open (View->2+ Viewports).  
  
These shortcuts are the same as the default Freelook movement shortcuts, so moving around with WASD repeatedly jumps around in the Animation Editor, making it difficult to make animation adjustments.  
  
This specifically only occurs when 2 or more Viewports are active in the Editor.
For **only one** of the Viewports, the animation shortcuts **do not activate**.
However, for **all of the other** Viewports, the animation shortcuts **do activate**.

The Animation Editor shortcuts do not activate when in Freelook mode with just 1 Viewport active.

### Steps to reproduce

1. Open the 3D Editor in a scene with an AnimationPlayer node.
2. Select the AnimationPlayer node and open the Animation Editor.
3. In the 3D Editor toolbar, select View->2 Viewports (The one that splits puts one at the top and the other at the bottom).
4. In the 3D editor, in the **top** Viewport, enter Freelook mode by holding down the right mouse button.
5. Move around in Freelook mode with WASD, and notice that the Animation Editor shortcuts are **active** when in the **top** Viewport.

Additional steps:
6. In the 3D editor, in the **bottom** Viewport, enter Freelook mode by holding down the right mouse button.
7. Move around with WASD, and notice that the Animation Editor shortcuts are **not active** when in the **bottom** Viewport.

### Minimal reproduction project

N/A

**Comment by ModuleCode** [comment] 2023-12-10 10:11
I also encountered this problem in v4.1.3.stable.official [f06b6836a]

**Comment by TheRedstoneScientist** [comment] 2024-02-27 17:52
I have just experienced this in 4.2.2.rc1.mono

**Comment by ryevdokimov** [comment] 2024-05-20 00:24
Duplicate of: https://github.com/godotengine/godot/issues/87639

Which was solved by: https://github.com/godotengine/godot/pull/88275

Specifically, by the addition of this (because the title of the PR doesn't suggest anything to do with this issue):

https://github.com/godotengine/godot/blob/daa81bbb7d1c6d75d1711595604178ee62a5801d/editor/plugins/node_3d_editor_plugin.cpp#L1503-L1506

**Closed** 2024-05-20 07:38 UTC
Labels: bug, topic:editor, confirmed, topic:input, topic:animation, topic:3d
