### ISSUE TITLE
Toolbar for some Control nodes is so wide it makes right dock unsuable

### ISSUE THREAD

**Issue by NineAlexT** [godotengine/godot#58953] opened 2022-03-09 21:50 UTC
### Godot version

4.0 Alpha 4

### System information

Kubuntu 20.04, Nvidia GTX 1060, Driver 510, Vulkan

### Issue description

When editing some Control nodes in a project with fonts in it the toolbar at the top becomes so wide it forces the docks on each side to shrink (this affects the right dock where the inspector is by default worse) making the dock uncomfortably small at 1080p, and unusable at <1080 (according to the Steam HW Survey sub-1080 primary displays account for 14.59% of all computers). In this situation the right dock cannot be made larger because the interface does not allow toolbar items to be hidden by the docks.
Here it is at 1920x1200:
![inspector1920](https://user-images.githubusercontent.com/60285548/157541139-d4e10469-5534-4bf2-8625-ded89672f112.png)
At 1680x1050:
![inspector1680](https://user-images.githubusercontent.com/60285548/157541168-2175e1bc-fbfd-409d-9821-6866f5fbae10.png)
And at 1280x720:
![inspector720](https://user-images.githubusercontent.com/60285548/157541225-e2f1a34a-50fc-4d08-af40-703f4d12d0a4.png)

### Steps to reproduce

Create a new project, add some fonts, make a new scene with a control node, give it a child like an OptionButton.

### Minimal reproduction project

[UnusableInspector.zip](https://github.com/godotengine/godot/files/8218391/UnusableInspector.zip)

**Comment by Calinou** [comment] 2022-03-09 22:13
This is a duplicate of another issue, but I can't find it right now.

**Closed** 2022-03-09 22:16 UTC
Labels: bug, topic:editor, usability, topic:gui

**Comment by NineAlexT** [comment] 2022-03-09 22:20
Ah, didn't see that, apologies.
