### ISSUE TITLE
Error trying to build godot with Visual Studio

### ISSUE THREAD

**Issue by codevenkat** [godotengine/godot#42152] opened 2020-09-18 01:09 UTC
**Godot version:** 2d9b409

**OS/device including version:** Windows 10 

**Issue description:**

When trying to build godot with visual studio after generating sln file with `scons p=windows vsproj=yes`, pressing build solution raises an error with build output with the following: `Build option 'custom_modules' must point to an existing directory.`. I tried commenting out lines 192-199 of the custom_modules code in SConscript in the root directory and it builds and runs.

**Steps to reproduce:**
* generate VS soln file with `vsproj=yes`
* try to build the solution

**Comment by jak6jak** [comment] 2020-09-18 02:26
I can confirm that this is an issue for me too.

**Comment by Listwon** [comment] 2020-09-18 15:43
@codevenkat @jak6jak can you tell me which versions of Scons and Python do you have installed? I can confirm that it raises error on Scons 4.0.1 and I fixed it here #42146

**Comment by Xrayez** [comment] 2020-09-18 16:57
I suspect so, the engine has not yet officially switched to SCons 4.0.1 and new users are likely to just install the latest SCons version upon `pip install SCons`.

https://github.com/godotengine/godot/blob/a332e2f5b2d4acfda639701d719ff415d73c5d0b/SConstruct#L3-L4

Can be checked with:
```
scons --version
python --version
```

If there are other reasons for the failure, I think #42146 should fix it for both SCons versions anyway, being more reliable than the current implementation.

**Comment by akien-mga** [comment] 2020-09-18 18:26
> the engine has not yet officially switched to SCons 4.0.1

The version in `SConstruct` is the *minimum* supported version. Using the latest stable version is always recommended.

**Comment by Xrayez** [comment] 2020-09-18 18:54
Yeah, just saying that I wouldn't recommend upgrading from SCons `3.1.1` to `4.0.1` because of *major* update by definition, else that's asking for troubles if you want to utilize the engine in a stable manner.

**Comment by codevenkat** [comment] 2020-09-18 19:39
@Listwon  Im on SCons 4.0.1, Python 3.8.2

**Comment by jak6jak** [comment] 2020-09-18 23:49
I have SCons 4.01 and Python 3.7.4

**Comment by TimStokes47** [comment] 2020-09-22 10:32
I had this problem and downgrading to SCons 3.1.1 fixed it. Make sure to delete all generated SCons files and the old Visual Studio files.

**Comment by Xrayez** [comment] 2020-09-22 10:40
The fix is already there but has to be merged first to the `master` branch: #42171.

**Closed** 2020-09-22 10:52 UTC
