### ISSUE TITLE
Image manipulation too slow

### ISSUE THREAD

**Issue by QushyQushy** [godotengine/godot#64884] opened 2022-08-25 14:17 UTC
### Godot version

3.5

### System information

Apline Linux

### Issue description

I am making a Jigsaw Puzzle and I have 3 difficulties. Each difficulty uses an encoded mask to break a random image into pieces. So for the first piece the mask has R=1,G=1,B=1,A=255, for the second piece it has R=2,G=2,B=2,A=255 and so on an so forth.
I am using the following code to break the image into pieces:

```
        var mask = Image.new();
	mask = $Viewport.get_texture().get_data();
	mask.flip_x();
	mask.lock();
	
	var pieceImage = Image.new();
	pieceImage = $"/root/GobalVars".selectedImage.get_data();
	pieceImage.resize(460,460);
	pieceImage.lock();
	
	for i in range (pieceImage.get_width()):
		for j in range (pieceImage.get_height()):
			var rgba255 = mask.get_pixel(i, j) * 255;
			var r = floor (rgba255.r);
			if (r > 0):
				if (rgba255.a == 255 && rgba255.g == rgba255.r && rgba255.b == rgba255.r):
					pieces[r-1].set_pixel(i,j, pieceImage.get_pixel(i,j));
					
					$"/root/GobalVars".pieces[r-1].minX = min ($"/root/GobalVars".pieces[r-1].minX, i);

					$"/root/GobalVars".pieces[r-1].maxX = max ($"/root/GobalVars".pieces[r-1].maxX, i);

					$"/root/GobalVars".pieces[r-1].minY = min ($"/root/GobalVars".pieces[r-1].minY, j);

					$"/root/GobalVars".pieces[r-1].maxY = max ($"/root/GobalVars".pieces[r-1].maxY, j);
	
	for i in range (len($"/root/GobalVars".pieces)):
		var pieceTexture = ImageTexture.new();
		pieceTexture.create_from_image(pieces[i]);
		$"/root/GobalVars".pieces[i].texture = pieceTexture;
		$"/root/GobalVars".pieces[i].position = Vector2 (570, 220) + Vector2 ($"/root/GobalVars".pieces[i].minX + ($"/root/GobalVars".pieces[i].maxX - $"/root/GobalVars".pieces[i].minX) /2, $"/root/GobalVars".pieces[i].minY + ($"/root/GobalVars".pieces[i].maxY - $"/root/GobalVars".pieces[i].minY) /2);
		$"/root/GobalVars".pieces[i].initialPosition = $"/root/GobalVars".pieces[i].position;
		$"/root/GobalVars".pieces[i].region_rect = Rect2($"/root/GobalVars".pieces[i].minX, $"/root/GobalVars".pieces[i].minY, $"/root/GobalVars".pieces[i].maxX - $"/root/GobalVars".pieces[i].minX, $"/root/GobalVars".pieces[i].maxY - $"/root/GobalVars".pieces[i].minY);
		pieces[i].unlock();
		yield(get_tree().create_timer(0.05), "timeout");
		var r = floor (rand_range(0,len(randomPuzzlePositions)));
		$"/root/GobalVars".pieces[i].randomPosition = Vector2 (randomPuzzlePositions[r][0], randomPuzzlePositions[r][1]);
		randomPuzzlePositions.erase(randomPuzzlePositions[r]);
		$"/root/GobalVars".pieces[i].moveToRandomPosition();
	
	mask.unlock();
	pieceImage.unlock();
	yield(get_tree().create_timer(0.05), "timeout");
	mask.queue_free();
	pieceImage.queue_free();
```

The code works just fine, the problem is that on a Tablet on Chrome it takes about 20 seconds for Godot to do the calculation. I have made the same game in Construct with Javascript and the pieces were made instantaneously (but the game didn't work on all Tablets so that's why we're moving to Godot).

Any advice that could help make this faster would be much appreciated, otherwise I think the Godot devs should look into this as it may be a hindrance for some projects.

### Steps to reproduce

Just try to manipulate a lot of pixels in WebGL.

### Minimal reproduction project
Minimal reproduction project [here](https://github.com/godotengine/godot/issues/64884#issuecomment-1227613961),

**Comment by Calinou** [comment] 2022-08-25 14:58
@QushyQushy Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot. We can't do anything without one.

**Comment by aaronfranke** [comment] 2022-08-25 15:08
There's some low hanging fruit to improve the performance of your code.

> ```gdscript
> $"/root/GobalVars"
> ```

GDScript `$` statements [are not cached](https://github.com/godotengine/godot-proposals/issues/996), so it gets the node every time. You can use `onready var` to cache them. Also, you misspelled Global as Gobal.

You could also skip the multiplication by 255 and just work with Godot's raw color values on the range of 0.0 to 1.0.

**Comment by QushyQushy** [comment] 2022-08-25 17:36
> @QushyQushy Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot. We can't do anything without one, as the code sample you provided is not a standalone project.
> 
> Also, which tablet model did you test this on? Is performance better on desktop?

Unfortunately I really can't share the project. I will try to make a really minimal on and upload it if I can.



> There's some low hanging fruit to improve the performance of your code.
> 
> > ```gdscript
> > $"/root/GobalVars"
> > ```
> 
> GDScript `$` statements [are not cached](https://github.com/godotengine/godot-proposals/issues/996), so it gets the node every time. You can use `onready var` to cache them. Also, you misspelled Global as Gobal.
> 
> You could also skip the multiplication by 255 and just work with Godot's raw color values on the range of 0.0 to 1.0.

I will try to fix the node caching issue. The `Gobal` is a long standing mispell but doesn't affect the code so I'm not changing ti cause it will take a considerably long time in all the projects we have.
The multiplication needs to be done cause of the encoding of the image. I can't tell the graphic designers to use floats as it will get seriously complicated and I'm afraid it may not even work properly with floats due to precision issues.

**Comment by QushyQushy** [comment] 2022-08-25 18:21
[PuzzleCalculation.zip](https://github.com/godotengine/godot/files/9427349/PuzzleCalculation.zip)

Here is the minimal project. For some reason it won't let me update the original post. If you need anything else let me know. :)
@Calinou

**Comment by QushyQushy** [comment] 2022-08-25 18:42
I also uploaded it to my Itch page if you want to test on mobile, just test how long it takes to load, it's about the same time it takes to change scenes in the original game. [Here is the HTML build](https://cosmichappiness.itch.io/puzzle-calculation).

**Comment by MGilleronFJ** [comment] 2022-08-26 12:58
Any way you could use shaders instead of per-pixel operations in GDScript? I dont understand the code well yet, but I feel there should be a more efficient way to do this.

**Comment by QushyQushy** [comment] 2022-08-26 13:21
> Any way you could use shaders instead of per-pixel operations in GDScript? Or a different approach? (being limited to 256 pieces with the current code doesnt seem right) I dont understand the code well yet, but to make a jigsaw puzzle I feel there should be a more efficient way to do this without involving that much image manipulation. Perhaps even the way they are rendered in the first place (without having to create individual images for every piece). Is every piece an image covering the entire puzzle with only the piece filtered in it? (if so that's probably a big time sink, and should rather consider processing only an area around the piece, which in turn could mean you dont need to identify them all with colors but only a few local colors). Image pixel manipulation is far from the fastest on earth, but your algorithm very likely can be optimized by an order of magnitude. I have no time to look in more details right now but I could investigate it later.

Every piece is an image as big as the entire puzzle. I then transfer this Image to an ImageTexture and set a Sprite texture with a specific region to be rendered.
What happens now is that it passes though the whole image one single time and according to the color of the mask on a particular pixel it automatically finds the correct piece Image and transfers the color of the original image to it. I really don't think I can go faster than that.

**Comment by MGilleronFJ** [comment] 2022-08-26 16:36
> Every piece is an image as big as the entire puzzle. I then transfer this Image to an ImageTexture and set a Sprite texture with a specific region to be rendered.

Well fixing this could give you a big performance boost. You shouldn't need the entire image for every piece of a jigsaw puzzle. It's wasting memory as well.

**Comment by MGilleronFJ** [comment] 2022-08-26 17:33
I think you could use a shader then. Instead of baking an image for every piece, you can use a shader that filters the piece, which will be instant.

**Comment by Calinou** [comment] 2022-11-06 20:46
@QushyQushy Did you manage to apply one of the solutions outlined above?

**Comment by QushyQushy** [comment] 2022-11-06 23:32
> @QushyQushy Did you manage to apply one of the solutions outlined above?

No the game i still extremely slow on mobile and it's a problem. I'm waiting for Godot 4.0 to come out to tweak it and export it there in case it works faster.

**Comment by Calinou** [comment] 2022-11-07 01:11
> No the game i still extremely slow on mobile and it's a problem. I'm waiting for Godot 4.0 to come out to tweak it and export it there in case it works faster.

I'd be surprised if upgrading to 4.0 made your project run any faster on low-end mobile devices. If anything, these are more likely to struggle more compared to 3.x (due to the higher baseline requirements, such as GLES3 and more RAM).

**Comment by Calinou** [comment] 2023-11-07 10:42
Closing, as there is nothing actionable we can do on our end.

**Closed by Calinou** 2023-11-07 10:42 UTC
Labels: topic:core, needs testing, performance
