### ISSUE TITLE
Vulkan: Console keeps spamming error when scene is empty while SDFGI is turned on

### ISSUE THREAD

**Issue by Hakimvira** [godotengine/godot#60533] opened 2022-04-26 14:52 UTC
### Godot version

Godot 4.0 Alpha 6

### System information

Windows 11, RTX 3050, 472.12, Vulkan Clustered

### Issue description

https://user-images.githubusercontent.com/62761946/165325976-df484680-2461-4847-a642-31b133a7d0a4.mp4

The console keep spamming

```
Storage buffer supplied (binding: 1) must provide one ID (0 provided).
./servers/rendering/renderer_rd/uniform_set_cache_rd.h:129 - Condition "rid.is_null()" is true. Returning: rid
drivers/vulkan/rendering_device_vulkan.cpp:7387 - Condition "!uniform_set" is true.
```
when no mesh exist in the scene. However the error disappear when a new mesh is added to the scene

### Steps to reproduce

1. Create a new empty scene
2. Add WorldEnviroment node
3. Enable SDFGI

**Comment by Calinou** [comment] 2022-04-26 15:43
I can confirm this on 4.0.alpha 5c54770b7.

**Comment by gaschneidr** [comment] 2022-04-28 00:08
I've been having a similar issue when trying to play a basic scene with SDFGI enabled.

This is the stack trace

![image](https://user-images.githubusercontent.com/16690454/165650335-d22514b1-2630-4914-aa79-85e1a9d09498.png)

I only create a ground plane and a capsule player to try and move around with.

![image](https://user-images.githubusercontent.com/16690454/165650485-c3f96240-8da6-4f20-b868-5738ce34fc7a.png)

This has been happening ever since 4.0 Alpha 1 for me here. Don't know what is causing this issue since I see people being able to use SDFGI in feature showcases.

Something new that happened with Alpha 6 and now 7 is when trying to play the scene the screen is all black. Even though there is an active camera.

![image](https://user-images.githubusercontent.com/16690454/165650694-4238ddfa-1024-4dbd-8264-5eeea2d55558.png)

As I'm writing this comment Godot is making my computer lag like crazy!

**Comment by Calinou** [comment] 2022-04-28 14:35
> I only create a ground plane and a capsule player to try and move around with.

Does the ground plane have its Global Illumination Mode property set to **Static** in the inspector? This is required for SDFGI to work.

**Comment by StefSSU** [comment] 2022-04-28 20:40
> > I only create a ground plane and a capsule player to try and move around with.
> 
> Does the ground plane have its Global Illumination Mode property set to **Static** in the inspector? This is required for SDFGI to work.

I was able to replicate the issue when both the ground plane and capsule had Global Illumination Mode disabled, setting the ground plane GI Mode to Static and restarting fixed the problem. Perhaps a clearer error message would be a good idea? Also, interestingly when I tried disabling the GI Mode and reloading the scene I did not see the errors reappear, only once I restarted the project.

Environment:
v4.0.alpha7.official [3e9ead05f]
macOS 12.3.1 arm64 Apple M1

**Comment by Calinou** [comment] 2022-04-28 23:54
> Perhaps a clearer error message would be a good idea?

The Vulkan errors need to be fixed first before we can consider adding a warning message that's printed only once (using `WARN_PRINT_ONCE()` in debug builds).

**Comment by Calinou** [comment] 2022-04-29 16:28
> What about the black viewport thing?

I don't know. Can you upload a minimal reproduction project here? You can attach a ZIP file by drag-and-dropping it.

**Comment by gaschneidr** [comment] 2022-04-29 17:31
Here it is. Thanks for the help!

I don't remember having to do anything other than putting a camera in the scene in previous versions of Godot to make the camera work. And also I was not facing this issue with Godot 4.0 alpha until version 6 I guess. Don't remember testing version 5.

[Alpha 7 Test.zip](https://github.com/godotengine/godot/files/8592330/Alpha.7.Test.zip)

**Comment by marstaik** [comment] 2022-05-08 21:07
I ran into the exact same issues as this post, and setting the GI on the static floor did fix it. One think I didn't see mentioned is that if you animate/move the player capsule/camera the entire screen will start flickering as these resource issues in vulkan keep getting hit over and over again.

>Does the ground plane have its Global Illumination Mode property set to Static in the inspector? This is required for SDFGI to work.

It's required if we want it to contribute to SDFGI, but it should still be fine for "disabled" to be a valid option and not cause this erratic behavior right?

**Comment by Calinou** [comment] 2022-05-08 21:52
> It's required if we want it to contribute to SDFGI, but it should still be fine for "disabled" to be a valid option and not cause this erratic behavior right?

Yes, but

To be fair, since imported 3D scenes (Collada/glTF/FBX) are already using the Static global illumination mode by default, I wonder if this should be done for *all* GeometryInstance3D nodes by default. This would result in more consistent behavior between primitive meshes, loaded OBJ meshes and imported 3D scenes.

**Comment by clayjohn** [comment] 2023-02-23 18:09
I can't reproduce on RC3. We have fixed a lot of errors like this, so I will close this as fixed. Please comment if you can reproduce

**Closed by clayjohn** 2023-02-23 18:09 UTC
Labels: bug, topic:rendering, confirmed, topic:3d
