### ISSUE TITLE
ViewportTexture is available as a texture in decal but isn't supported.

### ISSUE THREAD

**Issue by CarpenterBlue** [godotengine/godot#77585] opened 2023-05-28 19:29 UTC
### Godot version

4.1 dev3

### System information

Doesn't matter.
Not planned as feature according to #73400

### Issue description

The texture is available but not supported and there are no plans on supporting it.
No error/warnings are raised either.

### Steps to reproduce

1) add ViewportTexture as texture to Decal node
2) it doesn't work in game

### Minimal reproduction project

N/A

**Comment by clayjohn** [comment] 2023-06-08 17:42
Duplicate of https://github.com/godotengine/godot/issues/73400

Closing so that we can track the underlying issue in one place

**Closed by clayjohn** 2023-06-08 17:42 UTC
Labels: bug, enhancement, topic:editor
