### ISSUE TITLE
Occasional crashes in Mono project

### ISSUE THREAD

**Issue by Torguen** [godotengine/godot#35207] opened 2020-01-16 16:18 UTC
**Godot version:**
3.2 beta 6 mono

**OS/device including version:**
win10 64 home

**Issue description:**
Crashes on specific equipment when the game window is closed while a cursor is pressed, for example the right cursor.

Crash occurs on my laptop (GPU Radeon vega 8)

There is no crash on my desktop computer although it takes a while to close the window.

**Steps to reproduce:**
Run the scene.
Press and hold the right cursor during the entire process
Close the execution window

**Minimal reproduction project:**
[test.zip](https://github.com/godotengine/godot/files/4072258/test.zip)

**Comment by Torguen** [comment] 2020-01-16 22:46
I am experiencing more blockages with low framerate rates when I close the window on my laptop.
For example with 10fps I just suffered a lock when closing the window.

**Comment by akien-mga** [comment] 2020-01-22 13:13
I can't reproduce any crash in 3.2 RC 2 Mono with this project. Testing on Linux.

It is indeed very slow to close, but you configured it to run with 1 FPS and print stuff in `_Process`, so it seems normal to me that it takes 1 second to close the window.

Can you still reproduce any crash?

**Comment by Torguen** [comment] 2020-01-22 14:58
Hi, I'm still experiencing the locks with RC2.
  Where do I find the crash log file?

**Comment by akien-mga** [comment] 2020-01-23 13:10
Do you get the same issue with the non-Mono version of 3.2 RC 2?

There's no clear indication of a crash in the above log, the only issue seems to be that it can't find `BCrypt.dll`.

**Comment by Torguen** [comment] 2020-01-24 20:57
Hello, I have tried RC3 in mono and in windows but now the log does not register anything although the crash still happens.

**Comment by CloneDeath** [comment] 2020-02-02 18:44
I am able to reproduce the issue consistently in 3.2 stable. I'm not really sure what's causing it, but it's something I changed in commit `a3a5ad77bb44a0cf486d3d13cd7d32a0f0a8a554` in my repo https://github.com/CloneDeath/LegendsOfLove

Attached is the project files for that commit. Press any key to get past the title, then just walk 1 screen north. Once the transition finishes, and it attempts to unfreeze entities, it crashes trying to load this DLL (which I have no idea why it would try to load it).

[LegendsOfLove.zip](https://github.com/godotengine/godot/files/4144939/LegendsOfLove.zip)

I'll reply if I can narrow down what's causing it, or if I can provide a more stripped down project. (I'm in the middle of a game jam, so I'm in a rush right now)

**Comment by akien-mga** [comment] 2020-02-05 13:50
@CloneDeath I'm not sure if it's the same issue as we don't know much about what causes the OP's issue yet. The message about `BCrypt.dll` might be a red herring, I don't think it's related to the crash.

Still, I can also consistently reproduce a crash on Linux using your project and the steps to reproduce.

I'll get a stacktrace as soon as I can rebuild the mono version with debug symbols (currently in the middle of a git bisect).

**Comment by akien-mga** [comment] 2020-02-05 14:51
Here's the crash report on Linux with a debug build of the master branch using @CloneDeath's project:
```
$ godot-mono
Godot Engine v4.0.dev.mono.custom_build.9591ca3fe - https://godotengine.org
OpenGL ES 2.0 Renderer: Mesa DRI Intel(R) HD Graphics 630 (Kaby Lake GT2) 
 
Mono: Logfile is: /home/akien/.local/share/godot/mono/mono_logs/2020_02_05 15.50.22 (24483).txt
ERROR: mono_log_callback: Mono: FATAL ERROR, ABORTING! Logfile: '/home/akien/.local/share/godot/mono/mono_logs/2020_02_05 15.50.22 (24483).txt'.
   At: modules/mono/mono_gd/gd_mono_log.cpp:86.

=================================================================
        Native Crash Reporting
=================================================================
Got a SIGABRT while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries 
used by your application.
=================================================================
/proc/self/maps:
00400000-05493000 r-xp 00000000 103:07 8023084                           /home/akien/Projects/godot/godot.git/bin/godot.x11.tools.64.mono
05494000-05567000 r--p 05093000 103:07 8023084                           /home/akien/Projects/godot/godot.git/bin/godot.x11.tools.64.mono
05567000-0558c000 rw-p 05166000 103:07 8023084                           /home/akien/Projects/godot/godot.git/bin/godot.x11.tools.64.mono
0558c000-055a5000 rw-p 00000000 00:00 0 
059a6000-087ba000 rw-p 00000000 00:00 0                                  [heap]
401fd000-4020d000 rwxp 00000000 00:00 0 
405b1000-40731000 rwxp 00000000 00:00 0 
40edd000-40eed000 rwxp 00000000 00:00 0 
35dfc00000-35dfc01000 r--p 00000000 103:06 3148558                       /usr/lib64/ld-2.29.so
35dfc01000-35dfc1f000 r-xp 00001000 103:06 3148558                       /usr/lib64/ld-2.29.so
35dfc1f000-35dfc26000 r--p 0001f000 103:06 3148558                       /usr/lib64/ld-2.29.so
35dfc26000-35dfc27000 r--p 00025000 103:06 3148558                       /usr/lib64/ld-2.29.so
35dfc27000-35dfc28000 rw-p 00026000 103:06 3148558                       /usr/lib64/ld-2.29.so
35dfc28000-35dfc29000 rw-p 00000000 00:00 0 
35e0000000-35e0025000 r--p 00000000 103:06 3149698                       /usr/lib64/libc-2.29.so
35e0025000-35e0179000 r-xp 00025000 103:06 3149698                       /usr/lib64/libc-2.29.so
35e0179000-35e01bf000 r--p 00179000 103:06 3149698                       /usr/lib64/libc-2.29.so
35e01bf000-35e01c0000 ---p 001bf000 103:06 3149698                       /usr/lib64/libc-2.29.so
35e01c0000-35e01c3000 r--p 001bf000 103:06 3149698                       /usr/lib64/libc-2.29.so
35e01c3000-35e01c6000 rw-p 001c2000 103:06 3149698                       /usr/lib64/libc-2.29.so
35e01c6000-35e01ca000 rw-p 00000000 00:00 0 
35e0200000-35e0207000 r--p 00000000 103:06 3150098                       /usr/lib64/libpthread-2.29.so
35e0207000-35e0216000 r-xp 00007000 103:06 3150098                       /usr/lib64/libpthread-2.29.so
35e0216000-35e021a000 r--p 00016000 103:06 3150098                       /usr/lib64/libpthread-2.29.so
35e021a000-35e021b000 ---p 0001a000 103:06 3150098                       /usr/lib64/libpthread-2.29.so

=================================================================
        Basic Fault Adddress Reporting
=================================================================
Memory around native instruction pointer (0x35e003ca7a):0x35e003ca6a  d2 4c 89 ce bf 02 00 00 00 b8 0e 00 00 00 0f 05  .L..............
0x35e003ca7a  48 81 c4 88 00 00 00 44 89 c0 5b c3 66 2e 0f 1f  H......D..[.f...
0x35e003ca8a  84 00 00 00 00 00 64 48 8b 0c 25 00 00 00 00 48  ......dH..%....H
0x35e003ca9a  8b 15 d0 63 18 00 f7 d8 89 04 11 eb bc 66 0f 1f  ...c.........f..

=================================================================
        Native stacktrace:
=================================================================
        0x7f8d0f8fa1c8 - /lib64/libmonosgen-2.0.so.1 : (null)
        0x7f8d0f885f7c - /lib64/libmonosgen-2.0.so.1 : (null)
        0x35e0213570 - /lib64/libpthread.so.0 : (null)
        0x35e003ca7a - /lib64/libc.so.6 : gsignal
        0x35e0025524 - /lib64/libc.so.6 : abort
        0x169dedc - godot-mono : _ZN9GDMonoLog17mono_log_callbackEPKcS1_S1_iPv
        0x7f8d0fafd4fb - /lib64/libmonosgen-2.0.so.1 : (null)
        0x7f8d0fafdae3 - /lib64/libmonosgen-2.0.so.1 : monoeg_assertion_message
        0x7f8d0f8917c7 - /lib64/libmonosgen-2.0.so.1 : (null)
        0x7f8d0f8972e8 - /lib64/libmonosgen-2.0.so.1 : (null)
        0x7f8d0f897446 - /lib64/libmonosgen-2.0.so.1 : (null)
        0x7f8d0f888ddd - /lib64/libmonosgen-2.0.so.1 : (null)
        0x40edd893 - Unknown

=================================================================
        Telemetry Dumper:
=================================================================
Pkilling 0x7f8ceaf3a700 from 0x7f8d0f794fc0
Pkilling 0x7f8d003a7700 from 0x7f8d0f794fc0
Entering thread summarizer pause from 0x7f8d0f794fc0
Finished thread summarizer pause from 0x7f8d0f794fc0.
debugger-agent: Unable to listen on 11

Waiting for dumping threads to resume

=================================================================
        External Debugger Dump:
=================================================================
[New LWP 24484]
[New LWP 24485]
[New LWP 24486]
[New LWP 24487]
[New LWP 24488]
[New LWP 24489]
[New LWP 24490]
[New LWP 24505]
[New LWP 24506]
[New LWP 24507]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
0x00000035e0212f1a in waitpid () from /lib64/libpthread.so.0
  Id   Target Id                                          Frame 
* 1    Thread 0x7f8d0f794fc0 (LWP 24483) "godot-mono"     0x00000035e0212f1a in waitpid () from /lib64/libpthread.so.0
  2    Thread 0x7f8d03def700 (LWP 24484) "godot-mono"     0x00000035e0211686 in do_futex_wait.constprop () from /lib64/libpthread.so.0
  3    Thread 0x7f8d02e63700 (LWP 24485) "godot-m:disk$0" 0x00000035e020eaf5 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
  4    Thread 0x7f8d02662700 (LWP 24486) "godot-m:disk$1" 0x00000035e020eaf5 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
  5    Thread 0x7f8d01e61700 (LWP 24487) "godot-m:disk$2" 0x00000035e020eaf5 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
  6    Thread 0x7f8d01660700 (LWP 24488) "godot-m:disk$3" 0x00000035e020eaf5 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
  7    Thread 0x7f8d00a5a700 (LWP 24489) "godot-mono"     0x00000035e0211686 in do_futex_wait.constprop () from /lib64/libpthread.so.0
  8    Thread 0x7f8d00618700 (LWP 24490) "godot-mono"     0x00000035e0212a00 in nanosleep () from /lib64/libpthread.so.0
  9    Thread 0x7f8d005d7700 (LWP 24505) "godot-mono"     0x00000035e00cb600 in nanosleep () from /lib64/libc.so.6
  10   Thread 0x7f8cea7ff700 (LWP 24506) "SGen worker"    0x00000035e020eaf5 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
  11   Thread 0x7f8d003a7700 (LWP 24507) "Finalizer"      0x00000035e0211686 in do_futex_wait.constprop () from /lib64/libpthread.so.0

Thread 11 (Thread 0x7f8d003a7700 (LWP 24507)):
#0  0x00000035e0211686 in do_futex_wait.constprop () from /lib64/libpthread.so.0
#1  0x00000035e0211758 in __new_sem_wait_slow.constprop.0 () from /lib64/libpthread.so.0
#2  0x00007f8d0fa86138 in mono_os_sem_wait (flags=MONO_SEM_FLAGS_ALERTABLE, sem=0x7f8d0fe5bf80 <finalizer_sem>) at ../../mono/utils/mono-os-semaphore.h:203
#3  mono_coop_sem_wait (flags=MONO_SEM_FLAGS_ALERTABLE, sem=0x7f8d0fe5bf80 <finalizer_sem>) at ../../mono/utils/mono-coop-semaphore.h:41
#4  finalizer_thread (unused=unused@entry=0x0) at gc.c:920
#5  0x00007f8d0fa3398c in start_wrapper_internal (stack_ptr=0x7f8d003a8000, start_info=0x0) at threads.c:1178
#6  start_wrapper (data=0x6edce10) at threads.c:1238
#7  0x00000035e020904c in start_thread () from /lib64/libpthread.so.0
#8  0x00000035e010458f in clone () from /lib64/libc.so.6

Thread 10 (Thread 0x7f8cea7ff700 (LWP 24506)):
#0  0x00000035e020eaf5 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
#1  0x00007f8d0fad6fc3 in mono_os_cond_wait (mutex=0x7f8d0fe6a860 <lock>, cond=0x7f8d0fe6a820 <work_cond>) at ../../mono/utils/mono-os-mutex.h:168
#2  get_work (job=<synthetic pointer>, do_idle=<synthetic pointer>, work_context=<synthetic pointer>, worker_index=0) at sgen-thread-pool.c:165
#3  thread_func (data=<optimized out>) at sgen-thread-pool.c:196
#4  0x00000035e020904c in start_thread () from /lib64/libpthread.so.0
#5  0x00000035e010458f in clone () from /lib64/libc.so.6

Thread 9 (Thread 0x7f8d005d7700 (LWP 24505)):
#0  0x00000035e00cb600 in nanosleep () from /lib64/libc.so.6
#1  0x00000035e00fb624 in usleep () from /lib64/libc.so.6
#2  0x00000000014abea4 in JoypadLinux::monitor_joypads (this=0x65b6a50) at platform/x11/joypad_linux.cpp:216
#3  0x00000000014abdb4 in JoypadLinux::run_joypad_thread (this=0x65b6a50) at platform/x11/joypad_linux.cpp:114
#4  0x00000000014abd99 in JoypadLinux::joy_thread_func (p_user=0x65b6a50) at platform/x11/joypad_linux.cpp:102
#5  0x000000000207e79d in ThreadPosix::thread_callback (userdata=0x65b0c70) at drivers/unix/thread_posix.cpp:74
#6  0x00000035e020904c in start_thread () from /lib64/libpthread.so.0
#7  0x00000035e010458f in clone () from /lib64/libc.so.6

Thread 8 (Thread 0x7f8d00618700 (LWP 24490)):
#0  0x00000035e0212a00 in nanosleep () from /lib64/libpthread.so.0
#1  0x000000000207a5f5 in OS_Unix::delay_usec (this=0x7ffee50a2eb0, p_usec=1000) at drivers/unix/os_unix.cpp:261
#2  0x00000000020834d7 in AudioDriverPulseAudio::thread_func (p_udata=0x7ffee50a3350) at drivers/pulseaudio/audio_driver_pulseaudio.cpp:520
#3  0x000000000207e79d in ThreadPosix::thread_callback (userdata=0x6453d30) at drivers/unix/thread_posix.cpp:74
#4  0x00000035e020904c in start_thread () from /lib64/libpthread.so.0
#5  0x00000035e010458f in clone () from /lib64/libc.so.6

Thread 7 (Thread 0x7f8d00a5a700 (LWP 24489)):
#0  0x00000035e0211686 in do_futex_wait.constprop () from /lib64/libpthread.so.0
#1  0x00000035e0211758 in __new_sem_wait_slow.constprop.0 () from /lib64/libpthread.so.0
#2  0x000000000207e4a6 in SemaphorePosix::wait (this=0x5c8d7c0) at drivers/unix/semaphore_posix.cpp:41
#3  0x000000000374a195 in VisualServerScene::_gi_probe_bake_thread (this=0x7f8d00a5b020) at servers/visual/visual_server_scene.cpp:2549
#4  0x0000000003749100 in VisualServerScene::_gi_probe_bake_threads (self=0x7f8d00a5b020) at servers/visual/visual_server_scene.cpp:2335
#5  0x000000000207e79d in ThreadPosix::thread_callback (userdata=0x5c8fb80) at drivers/unix/thread_posix.cpp:74
#6  0x00000035e020904c in start_thread () from /lib64/libpthread.so.0
#7  0x00000035e010458f in clone () from /lib64/libc.so.6

Thread 6 (Thread 0x7f8d01660700 (LWP 24488)):
#0  0x00000035e020eaf5 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
#1  0x00007f8d0350c79b in util_queue_thread_func () from /usr/lib64/dri/i965_dri.so
#2  0x00007f8d0350c407 in impl_thrd_routine () from /usr/lib64/dri/i965_dri.so
#3  0x00000035e020904c in start_thread () from /lib64/libpthread.so.0
#4  0x00000035e010458f in clone () from /lib64/libc.so.6

Thread 5 (Thread 0x7f8d01e61700 (LWP 24487)):
#0  0x00000035e020eaf5 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
#1  0x00007f8d0350c79b in util_queue_thread_func () from /usr/lib64/dri/i965_dri.so
#2  0x00007f8d0350c407 in impl_thrd_routine () from /usr/lib64/dri/i965_dri.so
#3  0x00000035e020904c in start_thread () from /lib64/libpthread.so.0
#4  0x00000035e010458f in clone () from /lib64/libc.so.6

Thread 4 (Thread 0x7f8d02662700 (LWP 24486)):
#0  0x00000035e020eaf5 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
#1  0x00007f8d0350c79b in util_queue_thread_func () from /usr/lib64/dri/i965_dri.so
#2  0x00007f8d0350c407 in impl_thrd_routine () from /usr/lib64/dri/i965_dri.so
#3  0x00000035e020904c in start_thread () from /lib64/libpthread.so.0
#4  0x00000035e010458f in clone () from /lib64/libc.so.6

Thread 3 (Thread 0x7f8d02e63700 (LWP 24485)):
#0  0x00000035e020eaf5 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
#1  0x00007f8d0350c79b in util_queue_thread_func () from /usr/lib64/dri/i965_dri.so
#2  0x00007f8d0350c407 in impl_thrd_routine () from /usr/lib64/dri/i965_dri.so
#3  0x00000035e020904c in start_thread () from /lib64/libpthread.so.0
#4  0x00000035e010458f in clone () from /lib64/libc.so.6

Thread 2 (Thread 0x7f8d03def700 (LWP 24484)):
#0  0x00000035e0211686 in do_futex_wait.constprop () from /lib64/libpthread.so.0
#1  0x00000035e0211758 in __new_sem_wait_slow.constprop.0 () from /lib64/libpthread.so.0
#2  0x000000000207e4a6 in SemaphorePosix::wait (this=0x5a5bbc0) at drivers/unix/semaphore_posix.cpp:41
#3  0x0000000003b4baa3 in _IP_ResolverPrivate::_thread_function (self=0x5a5b620) at core/io/ip.cpp:101
#4  0x000000000207e79d in ThreadPosix::thread_callback (userdata=0x5a5bc00) at drivers/unix/thread_posix.cpp:74
#5  0x00000035e020904c in start_thread () from /lib64/libpthread.so.0
#6  0x00000035e010458f in clone () from /lib64/libc.so.6

Thread 1 (Thread 0x7f8d0f794fc0 (LWP 24483)):
#0  0x00000035e0212f1a in waitpid () from /lib64/libpthread.so.0
#1  0x00007f8d0f8fa417 in dump_native_stacktrace (ctx=ctx@entry=0x7ffee50a0d00, signal=0x7f8d0fb28ad8 "SIGABRT") at mini-posix.c:1115
#2  0x00007f8d0f8fa51e in mono_dump_native_crash_info (signal=signal@entry=0x7f8d0fb28ad8 "SIGABRT", ctx=ctx@entry=0x7ffee50a0d00, info=info@entry=0x7ffee50a0e30) at mini-posix.c:1159
#3  0x00007f8d0f885f7c in mono_handle_native_crash (signal=0x7f8d0fb28ad8 "SIGABRT", ctx=0x7ffee50a0d00, info=0x7ffee50a0e30) at mini-exceptions.c:3340
#4  <signal handler called>
#5  0x00000035e003ca7a in raise () from /lib64/libc.so.6
#6  0x00000035e0025524 in abort () from /lib64/libc.so.6
#7  0x000000000169dedc in GDMonoLog::mono_log_callback (log_domain=0x0, log_level=0x7f8d0fb50a1b "error", message=0x86bb020 "* Assertion at mini-generic-sharing.c:909, condition `oti' not met\n", fatal=4) at modules/mono/mono_gd/gd_mono_log.cpp:92
#8  0x00007f8d0fafd4fb in monoeg_g_logstr (msg=<optimized out>, log_level=G_LOG_LEVEL_ERROR, log_domain=0x0) at goutput.c:134
#9  monoeg_g_logv_nofree (log_domain=log_domain@entry=0x0, log_level=log_level@entry=G_LOG_LEVEL_ERROR, format=format@entry=0x7f8d0fb07108 "* Assertion at %s:%d, condition `%s' not met\n", args=args@entry=0x7ffee50a1600) at goutput.c:149
#10 0x00007f8d0fafdae3 in monoeg_g_logv_nofree (args=0x7ffee50a1600, format=0x7f8d0fb07108 "* Assertion at %s:%d, condition `%s' not met\n", log_level=G_LOG_LEVEL_ERROR, log_domain=0x0) at goutput.c:184
#11 monoeg_assertion_message (format=format@entry=0x7f8d0fb07108 "* Assertion at %s:%d, condition `%s' not met\n") at goutput.c:184
#12 0x00007f8d0f8917c7 in class_get_rgctx_template_oti (klass=0x8725750, type_argc=0, slot=slot@entry=3, temporary=temporary@entry=1, shared=shared@entry=1, do_free=0x7ffee50a17bc) at mini-generic-sharing.c:902
#13 0x00007f8d0f8972e8 in fill_runtime_generic_context (rgctx=<optimized out>, rgctx@entry=0x8727c08, slot=slot@entry=3, method_inst=method_inst@entry=0x0, is_mrgctx=is_mrgctx@entry=0, error=0x7ffee50a1870, class_vtable=<optimized out>, class_vtable=<optimized out>) at ../../mono/metadata/class-getters.h:47
#14 0x00007f8d0f897446 in mono_class_fill_runtime_generic_context (class_vtable=0x87278f0, slot=3, error=0x7ffee50a1870) at mini-generic-sharing.c:2915
#15 0x00007f8d0f888ddd in mono_rgctx_lazy_fetch_trampoline (regs=<optimized out>, code=<optimized out>, data=<optimized out>, tramp=<optimized out>) at mini-trampolines.c:1009
#16 0x0000000040edd893 in ?? ()
#17 0x0000000006ebe7f5 in ?? ()
#18 0x00000035e01c93d0 in __fork_generation_pointer () from /lib64/libc.so.6
#19 0x00007ffee50a1af0 in ?? ()
#20 0x00007ffee50a1928 in ?? ()
#21 0x0000000006ec53e0 in ?? ()
#22 0x0000000000000000 in ?? ()
[Inferior 1 (process 24483) detached]

=================================================================
        Managed Stacktrace:
=================================================================
          at <unknown> <0xffffffff>
          at System.Collections.Generic.List`1:GetEnumerator <0x000b3>
          at LegendsOfLove.Engine.GridAlignedCamera.GridAlignedCamera:UnfreezeNewAndResetOld <0x00117>
          at <Module>:runtime_invoke_void__this___object <0x000f0>
=================================================================
Aborted (core dumped)
```

**Comment by akien-mga** [comment] 2020-07-26 20:30
Can you still reproduce these issues with [Godot 3.2.3 RC 1](https://godotengine.org/article/release-candidate-godot-3-2-3-rc-1) or later?

**Comment by akien-mga** [comment] 2020-12-10 10:45
Closing due to lack of update.

I still can't reproduce @Torguen's issue in 3.2.4 beta 3, though I'm on Linux with different hardware.

@CloneDeath Your issue is likely unrelated, so if it's still reproducible in 3.2.4 beta 3 or later, please file a dedicated issue for it.

**Closed by akien-mga** 2020-12-10 10:45 UTC
Labels: bug, crash, topic:core, topic:mono
