### ISSUE TITLE
Cannot build GodotSharp project

### ISSUE THREAD

**Issue by xDGameStudios** [godotengine/godot#30127] opened 2019-06-27 16:22 UTC
**Godot version:**

The current build is #538c8eec1

**OS/device including version:**
Mac OSX Mojave

**Issue description:**
When I try to build I get a "Failed to generate GodotSharp solution. Error 30":

<img width="345" alt="Captura de ecrã 2019-06-27, às 17 17 08" src="https://user-images.githubusercontent.com/10358443/60282861-d1799780-98ff-11e9-8122-c5a33b218bd4.png">

I also have the following output error message:

<img width="1001" alt="Captura de ecrã 2019-06-27, às 17 21 06" src="https://user-images.githubusercontent.com/10358443/60282926-f8d06480-98ff-11e9-8d3a-10c4c0140c1f.png">

**Comment by akien-mga** [comment] 2019-06-27 16:41
That's likely caused by #29941.
There was a mismatch for the parent type of `EditorImportPlugin` which was fixed in https://github.com/godotengine/godot/pull/29941/files#diff-f8fca47e37ec343018622e4738ed772aR37

I'm not sure why it would cause an error though, especially since `ResourceImporter` is in core and is properly registered in ClassDB. CC @neikeq.

@xDGameStudios Did you rebuild your Mono glue?

**Comment by xDGameStudios** [comment] 2019-06-27 16:53
@akien-mga I used the following commands to compile... it should work... but... I guess it doesn't
```
scons platform=osx tools=yes module_mono_enabled=yes mono_glue=no
bin/godot.osx.tools.64.mono --generate-mono-glue modules/mono/glue
scons p=osx target=release_debug tools=yes module_mono_enabled=yes
```

also this is the output from the `--generate-mono-glue`

```
Mono: Logfile is: /Users/franciscodias/Library/Application Support/Godot/mono/mono_logs/2019_06_27 17.45.58 (42269).txt
WARNING: init: This binary is built with `mono_glue=no` and cannot be used for scripting
   At: modules/mono/csharp_script.cpp:113.
Ignoring type `BulletPhysicsDirectBodyState` because it's not exposed
Ignoring type `BulletPhysicsServer` because it's not exposed
Ignoring type `GDScriptNativeClass` because it's not exposed
Ignoring type `IP_Unix` because it's not exposed
Ignoring type `InputDefault` because it's not exposed
Ignoring type `Physics2DDirectBodyStateSW` because it's not exposed
Ignoring type `Physics2DServerSW` because it's not exposed
Name of method `Popup` is ambiguous with the name of its enclosing class `Popup`. Renaming method to `Popup_`
Name of method `Reference` is ambiguous with the name of its enclosing class `Reference`. Renaming method to `Reference_`
Ignoring type `ResourceImporter` because it's not exposed
Ignoring type `RootMotionView` because it's not enabled
Name of property `TextureProgress` is ambiguous with the name of its enclosing class `TextureProgress`. Renaming property to `TextureProgress_`
Generating ARVRAnchor...
Generating ARVRCamera...
Generating ARVRController...
Generating ARVRInterface...
...
```

then the list goes on!!

**Comment by neikeq** [comment] 2019-06-27 17:06
@akien-mga Are you sure `ResourceImporter` is exposed? I can't find where the `register_virtual_class<ResourceImporter>()` call is, but my fork is a few days behind.

**Comment by xDGameStudios** [comment] 2019-06-27 17:07
@akien-mga and @neikeq looking at the output from the glue generation:

`Ignoring type `ResourceImporter` because it's not exposed`

It doesn't seem to be exposed

**Comment by mysticfall** [comment] 2019-06-29 02:48
I encountered the same problem after updating my build from 05a0a68c7 to 6e0323657.

**Comment by piratesephiroth** [comment] 2019-07-03 03:40
yep, this makes the mono version unusable

**Comment by aaronfranke** [comment] 2019-07-04 18:17
Just tried to compile Godot and run my project, spent awhile regression testing to find that it was indeed caused by #29941 (eaaff9da3178fa515a0f051fda932c1dd04d53db), as the previous commit works fine (d8c96461183f0dc3208c3d624674fa4544212ea5)

```
 modules/mono/editor/bindings_generator.cpp:1211 - Base type 'ResourceImporter' does not exist, for class EditorImportPlugin
 modules/mono/editor/bindings_generator.cpp:1122 - Generation of the Editor API C# project failed
```

Please fix soon, as this makes Mono module impossible to use as far as I can tell.

**Closed** 2019-07-05 07:20 UTC
Labels: bug, topic:editor, topic:mono
