### ISSUE TITLE
Invalid get_index in gdscript when accessing property from C# that has only getter 

### ISSUE THREAD

**Issue by p10tr3k** [godotengine/godot#82134] opened 2023-09-22 17:22 UTC
### Godot version

v4.1.1.stable.mono.official [bd6af8e0e]

### System information

MacOS

### Issue description

If you try to access property with only getter method from C# class in gdscript it will throw exception:
```
Invalid get_index 'xxx' (on base: ...
```

### Steps to reproduce

Open attached project
Open scene GdCsProperty
Run project

### Minimal reproduction project

[GodotPrj2.zip](https://github.com/godotengine/godot/files/12703098/GodotPrj2.zip)

**Comment by raulsntos** [comment] 2023-09-22 18:16
Duplicate of https://github.com/godotengine/godot/issues/67167

**Closed by raulsntos** 2023-09-22 18:16 UTC
