### ISSUE TITLE
Remote view does't work with exported multi level dictionary

### ISSUE THREAD

**Issue by git2013vb** [godotengine/godot#58583] opened 2022-02-27 08:11 UTC
### Godot version

v3.5.beta1.mono.official [b9b23d222]

### System information

Debian 11

### Issue description

I have several exports like this one :

```
[Export]
private Dictionary debug_game_data = new Dictionary();
```
Some have other nested Dictionary

When I try to inspect the nested ones the editor don't allow me to expand them.

I work in C#

### Steps to reproduce

Export a multilevel Dictionary and try to inspect it in remote tab.

### Minimal reproduction project

NA . Its a simple thing that can be done in any C#  project without impact to any existing code :)

**Comment by Calinou** [comment] 2022-02-27 18:23
Duplicate of https://github.com/godotengine/godot/issues/25375.

**Closed by Calinou** 2022-02-27 18:23 UTC

**Comment by git2013vb** [comment] 2022-02-28 09:59
Sorry ,
I missed it :)
