### ISSUE TITLE
Navigation fails to bake NavMesh if mesh is too large

### ISSUE THREAD

**Issue by DataPlusProgram** [godotengine/godot#60907] opened 2022-05-09 21:23 UTC
### Godot version

3.5.beta5

### System information

Windows 10, GLES3, Radeon 5700xt, R7 5800X

### Issue description

![image](https://user-images.githubusercontent.com/62811101/167499745-058072bc-3a7d-467b-8b8e-1ebfcb16769f.png)

The Navigation node fails to bake nav mesh.
Clicking "Bake Navmesh" will go through the baking process without error but the navmesh will not be generated successfully 

### Steps to reproduce

In the example project there are two scenes a "navSingle.tscn" with a single large mesh instance and a "navMany.tscn" where the same geometry is present but its composed of many sub meshinstances. Both of these fail to generate.

### Minimal reproduction project

[navSample.zip](https://github.com/godotengine/godot/files/8655511/navSample.zip)

**Comment by akien-mga** [comment] 2022-05-10 06:20
CC @Scony @AndreaCatania @smix8

**Comment by smix8** [comment] 2022-05-10 08:44
There are multiple issues here related to settings and used mesh.
I agree that there should be an error msg / settings warning in this case instead of silent failure but everything else is not a bug.

While you can adjust the bake settings to your mesh the main issue here is with your mesh size / scale that is beyond reasonable for a single navmesh. You seem to be aware of your mesh (over)size as you already scaled the navigation node down to 0.05 and your mesh is still gigantic and at full scale it literally goes beyond camera cliprange. The bake runs into limits, errors out, and on top takes ages for a mesh that should be baked in less than a second.

In red is a very large 100 x 100 unit / meter plane. Compared to your mesh that is already scaled down to 0.05 by the navigation node it is still smaller than a single staircase. You need to scale down that source mesh. If you set your mesh scale further down to a reasonable 0.1 it bakes perfectly fine in less than 0.1 seconds.

![mesh_scale](https://user-images.githubusercontent.com/52464204/167584406-7525f572-c34b-4388-a284-3f3af8d0401f.png)

**Comment by DataPlusProgram** [comment] 2022-05-10 12:09
I have scaled down the source mesh as per recommendation and nav mesh baking now works correctly

![image](https://user-images.githubusercontent.com/62811101/167623351-7e54aa8a-12ae-4be1-99f7-552587c88e08.png)

If the silent failure could be changed that would be ideal to help other users in such a situation

**Comment by smix8** [comment] 2022-05-10 14:22
@ timshannon 
This depends on Godot Version and Navigation Setup.

In general for performance on very large maps the best way is to bake navigation mesh only around active agents and not for the entire map as each pathquery needs to parse the entire navmesh geometry. Rebaking navmesh at runtime is only possible in Godot 4.0 or 3.5 and this also is no buildin feature in Godot an requires custom code.

In Godot <3.5 a single large NavigationMesh is the way to go.

In this versions the NavigationMesh is only baked in Editor for each NavigationMeshInstance Node. The Navigation Node considers all NavigationMeshInstance children but only individual and not combined. If the start and end position of the path query are not on the same NavigationMesh the path will more or less fail so one single large NavigationMesh is the way to go. You can work around this limitations only with custom code like I did with my JumpLinks addon https://github.com/smix8/Godot_3D_Navigation_Jump_Links

In Godot 4.0 and 3.5 with the new NavigationServer things are different.

NavigationMesh can be rebaked at runtime and NavigationRegions create connections by edge proximity between different navmeshes. This also means the NavigationServer will consider all NavigationRegions with connections for the complete path query which can take a lot of resources if the map is very large. By default all navigation nodes register to the same default navigation map so a split of a large navmesh into smaller, but still connected ones, does not save performance as they will be merged again behind the scene. What it does help is with rebaking time, a smaller navmesh is faster to rebake than a large one. The recalculation of the entire navigation map is still the same cost but the rebaking happens faster on smaller meshes. With custom code it is possible to switch maps for different regions so not all of them are connected and updated at the same time.

**Closed** 2022-05-11 21:17 UTC
Labels: bug, topic:navigation, topic:3d
