### ISSUE TITLE
New PlayerController Prefab.

### ISSUE THREAD

**Issue by ca3games** [godotengine/godot#25040] opened 2019-01-16 15:36 UTC
Hi, I think a node where the user can easily set up a player Rigidbody configured to be the player node could be a great adition to new users.

It could have diferent setups for 4 directionals rpg, 8 directions arpgs, 2D platformer, Fighting game character, roguelike movement, car movement, tank movement, FPS movement and also their 3D version alternative.

**Comment by Ace-Dragon** [comment] 2019-01-16 15:47
This would probably be something better served with user-made custom nodes that can be downloaded from Godot's official website. The issue with having all of the possible control schemes as their own specialized node built into Godot is bloat for both the software and people's game projects (in which the latter is possible due to the engine not having an automated stripping feature as of now). The purpose is to keep the engine lightweight with good performance (so as to prevent the many performance issues and regressions seen in the big commercial solutions).

Of course it would help if the official website's asset section had a tag where you can show _just_ the custom node types people made.

**Comment by aaronfranke** [comment] 2019-01-16 16:17
KinematicBody already has the icon of a character, since it is intended to be used like this. But it would not be practical to code in all of those use cases.

**Comment by DleanJeans** [comment] 2019-01-16 16:44
I think there should official addons hosted on [Godot Engine GitHub Account](https://github.com/godotengine) like [godot-addons](https://github.com/godot-addons)

**Comment by eon-s** [comment] 2019-01-16 17:13
The asset library has character controllers already, a place to request scripts/plugins/etc would be nice to reduce this kind of request on the engine itself.

**Comment by arkology** [comment] 2019-01-17 17:14
I think the issue may be closed. There is no need to implement this in the engine itself. Own implementation will not take a lot of time, besides there are several assets in the asset library

**Comment by clayjohn** [comment] 2020-05-27 05:35
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!

**Closed by clayjohn** 2020-05-27 05:35 UTC
Labels: feature proposal, topic:core
