### ISSUE TITLE
Critical error with 3D Sprite

### ISSUE THREAD

**Issue by InkRobert** [godotengine/godot#63277] opened 2022-07-21 09:30 UTC
### Godot version

3.5 rc6 and 4.0 alpha

### System information

Windows 11 Pro, GLES3 and Vulkan(for Godot 4.0)

### Issue description

In godot there is a huge problem with 3D sprites, namely that the sprites in the background can overlap the foreground, this makes it simply impossible to work with sprites in 3D space! I no longer hope to fix this in Godot 3, but in Godot 4 this bug is also present, it's a small limitation that breaks a lot of plans for my project.
![godot_3 5](https://user-images.githubusercontent.com/91805483/180179522-866b8d6d-ed28-4228-adcd-0a2627bacc15.png)

### Steps to reproduce

I'm more of a designer than a programmer, so I can't imagine fixing this bug on a software level, but if godot already has a solution to this problem, I'd be happy to know it

**Comment by Zireael07** [comment] 2022-07-21 09:38
Yesterday there was a report of what I believe is the same issue. Search before opening issues...

Try unchecking Transparent in your Sprite3D material, this should fix it.

**Comment by InkRobert** [comment] 2022-07-21 10:40
> Yesterday there was a report of what I believe is the same issue. Search before opening issues...
> 
> Try unchecking Transparent in your Sprite3D material, this should fix it.

It didn't fix the situation...

**Comment by lawnjelly** [comment] 2022-07-21 11:31
The similar issue yesterday was #63182 .

**Comment by Calinou** [comment] 2022-07-21 17:03
Duplicate of https://github.com/godotengine/godot/issues/63182. Use alpha scissor if you want to avoid transparency sorting issues, or adjust render priority on the materials.

**Closed by Calinou** 2022-07-21 17:03 UTC
Labels: bug, topic:3d
