### ISSUE TITLE
Godot 4 alpha 14 Button Shortcut doesn't work with Gamepad

### ISSUE THREAD

**Issue by Intervel** [godotengine/godot#64688] opened 2022-08-21 10:43 UTC
### Godot version

4.0 alpha 14

### System information

Windows 11, Vulkan

### Issue description

i just discovered a bug with Button Shortcut, (i think)

Button Shortcut InputEventAction doesn't work with Gamepad, only Keyboard only.

please take a look at this video i recorded for better explainations

https://streamable.com/yxpiru

thanks! :) :) :)

### Steps to reproduce

what this

**Comment by KoBeWi** [comment] 2022-08-21 12:03
Duplicate of #62899

**Closed by KoBeWi** 2022-08-21 12:03 UTC
