### ISSUE TITLE
[Godot4] CollisionShape2D the edge is jagged

### ISSUE THREAD

**Issue by sakunix** [godotengine/godot#67597] opened 2022-10-18 22:55 UTC
### Godot version

4.0.beta3

### System information

GNU/Linux Debian testing

### Issue description

CollisionShape2D the edge is jagged.
![imagen](https://user-images.githubusercontent.com/22086570/196560109-eccdb0bc-b293-4570-891a-5d41af9f1f20.png)

### Steps to reproduce

CollisionShape2D

**Comment by rburing** [comment] 2022-10-18 22:59
Duplicate of https://github.com/godotengine/godot/issues/56320.

**Closed by rburing** 2022-10-18 22:59 UTC
