### ISSUE TITLE
Godot doesn't support custom cursor if a mouse was moved in CAPTURED mode

### ISSUE THREAD

**Issue by miskatonicstudio** [godotengine/godot#24719] opened 2019-01-02 14:43 UTC
**Godot version:**

3.0.6

**OS/device including version:**

Linux Pop!_OS 17.10 (Artful Aardvark)

**Issue description:**

If mouse was moved when in CAPTURE mode, Godot shows normal arrow cursor when going back to VISIBLE mode. Setting the cursor manually using `set_custom_mouse_cursor` doesn't work.

**Steps to reproduce:**
Issue 1:
* run the program
* press Enter without moving the mouse:
* the cursor shows as a normal arrow (bug)
* move the mouse
* the cursor shows as the custom image (correct)

Issue 2:
* run the program
* move the mouse (in CAPTURED mode)
* press Enter
* the cursor shows as a normal arrow
* move the mouse
* the cursor is still displayed as a normal arrow (bug)

**Minimal reproduction project:**

[CustomCursorError.zip](https://github.com/godotengine/godot/files/2721011/CustomCursorError.zip)

**Comment by BrodyEller** [comment] 2019-01-03 04:13
This seems like it is fixed in master.  When moving, the cursor is shown correctly.  If you don't move the mouse and press enter, the original cursor will show for a moment and then switches to the custom image.

**Comment by BrodyEller** [comment] 2019-01-03 22:48
Master is getting ready for the 3.1 release.  I'm not sure if the 3.0 branch will still be supported after 3.1 so it may not be worth it to fix the bug in 3.0.6.  Either way, I'll be looking into a fix in master.

**Comment by bojidar-bg** [comment] 2019-05-28 17:06
What is the status of this issue?

**Comment by Calinou** [comment] 2019-07-14 13:08
I cannot reproduce this issue (using the given example project) on commit https://github.com/godotengine/godot/commit/584ca0f156cec64c259382895e105cf27566a987.

**Closed** 2019-07-15 08:57 UTC
Labels: bug, platform:linuxbsd, topic:input, topic:porting
