### ISSUE TITLE
Editor help links sometimes have unexpected clickable area

### ISSUE THREAD

**Issue by timothyqiu** [godotengine/godot#60912] opened 2022-05-10 03:00 UTC
### Godot version

master(a12fe31e1f28ad5c4f4f0ea2f1c600aa4e34eb74)

### System information

Arch Linux, GLES 3, Mesa Intel(R) UHD Graphics (CML GT2)

### Issue description

![Peek 2022-05-10 10-53](https://user-images.githubusercontent.com/372476/167533843-830bb668-c36e-40d3-b61d-70578a5368b6.gif)

This happens since alpha2.

### Steps to reproduce

Open editor help for classes like `Control` and `Vector3`.

Click empty area after links in online tutorials / properties / theme properties.

**Comment by KoBeWi** [comment] 2022-05-10 22:40
Duplicate of #53599

**Closed by KoBeWi** 2022-05-10 22:40 UTC
Labels: bug, topic:editor, topic:gui
