### ISSUE TITLE
GLES3: Image get darkened after a download with HTTPrequest on Android

### ISSUE THREAD

**Issue by Arctia** [godotengine/godot#63833] opened 2022-08-02 15:16 UTC
### Godot version

3.4.2, 3.5-rc6

### System information

Android 
Redmi Note 8 Pro (Mali G76)

### Issue description

Every PNG downloaded and displayed on screen get darkened by a significative amount, that happens only on Android.

### Steps to reproduce

To reproduce the sample code on the documentation is enough: [https://docs.godotengine.org/en/3.5/classes/class_httprequest.html](url)

Switching the game project to GLES2 solves the problem, but what matters is that with GLES3 (so -Import ETC2-) doesn't work.

### Minimal reproduction project

[TestImgDownload.zip](https://github.com/godotengine/godot/files/9243438/TestImgDownload.zip)

**Comment by lawnjelly** [comment] 2022-08-02 17:25
Possibly related to #43342 .

**Comment by Calinou** [comment] 2022-10-15 18:24
Duplicate of https://github.com/godotengine/godot/issues/43342 (same cause).

**Closed by Calinou** 2022-10-15 18:24 UTC
Labels: bug, platform:android, topic:rendering
