### ISSUE TITLE
C# MySqlConnector error on connection

### ISSUE THREAD

**Issue by Zamir7** [godotengine/godot#86492] opened 2023-12-24 19:16 UTC
### Tested versions

C#, 4.2. Stable, nuget MySqlConnector 2.3.1

### System information

C#, 4.2. Stable, Windows 10 Pro, Android 13

### Issue description

When connecting to a database via MySqlConnector 2.3.1 on Windows it works flawlessly, but on Android it crashes with an error.
There is a feeling that the conflict is in the safety of Physics2DConstraintSolveIslands.
But again, there is no error on the Desktop and there is also no error in the .Net application on Android without Godot.

There may be an error at the permission level on Android; permissions are selected with a checkmark, but the application does not always ask about their permission during installation.

Here are the first lines of the error:

```
E 0:00:08:0044 :0 @ Interop+CryptoInitializer..cctor(): BUG: Unreferenced static string to 0: Physics2DConstraintSolveIslands
<C++ source code>core/string/string_name.cpp:127 @ unref()
:0 @ Interop+CryptoInitializer..cctor()
:0 @ Interop+Crypto..cctor()
:0 @ int System.Security.Cryptography.HashProviderDispenser+OneShotHashProvider.HashData(string, System.ReadOnlySpan1[System.Byte], System.Span1[System.Byte])
:0 @ bool System.Security.Cryptography.SHA1.TryHashData(System.ReadOnlySpan1[System.Byte], System.Span1[System.Byte], System.Int32&)

:0 @ System.Byte[] MySqlConnector.Protocol.Serialization.AuthenticationUtility.HashPassword(System.ReadOnlySpan1[System.Byte], string) :0 @ System.Byte[] MySqlConnector.Protocol.Serialization.AuthenticationUtility.CreateAuthenticationResponse(System.ReadOnlySpan1[System.Byte], string)
:0 @ MySqlConnector.Protocol.PayloadData MySqlConnector.Protocol.Payloads.HandshakeResponse41Payload.Create(MySqlConnector.Protocol.Payloads.InitialHandshakePayload, MySqlConnector.Core.ConnectionSettings, string, bool, MySqlConnector.Protocol.CharacterSet , System.Byte[])
:0 @ void MySqlConnector.Core.ServerSession+d__98.MoveNext()
:0 @ void
```

### Steps to reproduce

Install 4.2. Stable mono(C#), add the MySqlConnector 2.3 nuget, try to connect in the standard way, my connection is like this:
```
const string M_str_sqlcon = "server=xxx .xx .60.80;Port=3306;user id=ХХХ;password=PASSWORD;database=default_db;SslMode=none; AllowPublicKeyRetrieval = True; AllowZeroDateTime=True";
```

Launch on your Android device.

### Minimal reproduction project (MRP)

[mysql_test.zip](https://github.com/godotengine/godot/files/13762645/mysql_test.zip)

**Comment by Zamir7** [comment] 2023-12-24 19:29
[mysql_test2.zip](https://github.com/godotengine/godot/files/13762668/mysql_test2.zip)
Here is a version with a connection to my database, so as not to bother finding a server.
Just unzip and run, you should get lines like:
"rec1 rec2 rec3"

**Comment by markushaslinger** [comment] 2023-12-28 12:22
A potential problem in the hash implementation of `string_name` notwithstanding please _never_ have a database available directly via the internet but _always_ put a (web) API with proper authentication in front of it. 
Fetching and sending data via `HttpClient` would give you a more solid architecture while also solving this issue you are currently having and reducing the size of you APK by not having to pack the MySQL dependencies; win-win-win imho.

**Comment by Zamir7** [comment] 2023-12-31 15:06
> A potential problem in the hash implementation of `string_name` notwithstanding please _never_ have a database available 

Thanks for the advice, I perfectly understand the flaws of this method, and I am aware of what I am doing.
I use this scheme exclusively for personal purposes and rapid prototyping, and right now I don’t have the time and money to set up my own server and learn a new web language.
And it’s not required, since I need MySQL more in read mode than direct access. Therefore, everything is decided by user privileges.
In general, thanks for the advice, but unfortunately this does not apply to solving the problem described above. By all indications, there shouldn’t be a conflict, and perhaps solving this problem will reveal a certain chain of bugs.

**Comment by markushaslinger** [comment] 2023-12-31 15:33
> Thanks for the advice, I perfectly understand the flaws of this method, and I am aware of what I am doing. 

Apologies if I sounded condescending - experience levels on the internet differ and I got burned often enough that I now prefer to err on the side of caution even at the risk of annoying a colleague.
End of off-topic :)

**Comment by raulsntos** [comment] 2024-01-04 18:27
May be related to https://github.com/godotengine/godot/issues/84559. C# Android exports use linux bionic which doesn't provide OpenSSL.

Try the suggestion in https://github.com/godotengine/godot/issues/84559#issuecomment-1824365633:

> One thing you can try is downloading and extracting https://dl.google.com/android/maven2/com/android/ndk/thirdparty/openssl/1.1.1p-beta-1/openssl-1.1.1p-beta-1.aar and packaging libssl.so and libcrypto.so into the app and see if that helps.

**Comment by Zamir7** [comment] 2024-01-05 18:40
> Может быть связано с #84559 . При экспорте C# Android используется Linux Bionic, который не поддерживает OpenSSL.

When building a project without Godot on Android, I looked at the contents of the apk, and the libssl.so and libcrypto.so files you specified are also not there, is this the answer to your suspicion?

**Comment by raulsntos** [comment] 2024-01-09 17:34
Were you using the `linux-bionic` runtime identifier or `android`? `android` doesn't rely on OpenSSL so it doesn't need to include libssl.so or libcrypto.so. Godot uses `linux-bionic` but doesn't package OpenSSL so if that's your issue then it's a duplicate of https://github.com/godotengine/godot/issues/84559.

If you are able to package libssl.so and libcrypto.so into the app, then you can see if that's the issue. If it is it would confirm that it's a duplicate of https://github.com/godotengine/godot/issues/84559.

I'm not very familiar with MySql but I think the SslMode option only specifies the protocol used to connect to the database and not whether SSL will be used at all.

**Comment by Zamir7** [comment] 2024-01-12 15:32
> Were you using the `linux-bionic` runtime identifier or `android`? `android` doesn't rely on OpenSSL so it doesn't need to include libssl.so or libcrypto.so. Godot uses `linux-bionic` but doesn't package OpenSSL so if that's your issue then it's a duplicate of #84559.

You may be right, to be honest, I don’t know how to attach the files you specified to the created apk, although I understand that this is just an archive, but I previously experimented with assembling the apk, but none of the apk were installed on the Android platform.
If anyone has the opportunity and skill, I would be glad to hear the results of the experiment. Above is a project that connects to an existing database and you don’t need to write anything.

**Comment by raulsntos** [comment] 2024-02-25 06:42
I've tried exporting an APK with libssl.so and libcrypto.so included and it fixed the issue for me, so I'll close this issue to consolidate in https://github.com/godotengine/godot/issues/84559.

There's also a new PR that changes the way Android exports work to use the `android` runtime identifier instead of `linux-bionic`. This means we can use the JNI for crypto support, so it should fix the issue without you having to manually include the libssl.so and libcrypto.so libraries in the APK.
- https://github.com/godotengine/godot/pull/88803

**Closed by raulsntos** 2024-02-25 06:42 UTC
Labels: platform:android, topic:thirdparty, needs testing

**Comment by Zamir7** [comment] 2024-03-17 19:20
Unfortunately, it still crashes even though I specified the build option via gradle. And also libssl.so and libcrypto.so are missing from the assembly.
Godot 4.3 dev 5

**Comment by raulsntos** [comment] 2024-03-23 17:33
@Zamir7 The current Godot releases still use `linux-bionic` for Android exports and require that you add `libssl.so` and `libcrypto.so` yourself, they won't be added automatically by Godot. You'll have to wait until https://github.com/godotengine/godot/pull/88803 is merged or package the missing libraries in the APK.
