### ISSUE TITLE
Polygon2Ds break when attached to a Skeleton2D

### ISSUE THREAD

**Issue by dweremeichik** [godotengine/godot#57650] opened 2022-02-05 03:00 UTC
### Godot version

v4.0.alpha1.official [31a7ddbf8]

### System information

Windows10, Vulkan

### Issue description

When a Skeleton2D is imported with Polygon2Ds associated to it, it skews the Polygon2Ds.
![image](https://user-images.githubusercontent.com/4079608/152626202-77b28046-61f5-4c46-b895-fbd7d84bc0b1.png)

It should instead look something like this:
![image](https://user-images.githubusercontent.com/4079608/152626242-866dff5a-14b9-45f9-904d-8fd90e6487ab.png)

### Steps to reproduce

Import a project with a working Skeleton2D from stable into 4.0.1.alpha1.

### Minimal reproduction project

Godot 3.4.2:
[skeleton2d_mrp.zip](https://github.com/godotengine/godot/files/8007247/skeleton2d_mrp.zip)

Godot 4.0.alpha1
[skeleton2d_mrp-godot4.0.alpha1.zip](https://github.com/godotengine/godot/files/8007248/skeleton2d_mrp-godot4.0.alpha1.zip)

**Comment by dweremeichik** [comment] 2022-02-05 03:44
After more testing in 4.0.alpha1 this seems to be a problem with Skeleton2D in general and not an import/upgrade specific issue.
Possible related issue: #35726

**Comment by bneff84** [comment] 2022-09-18 01:45
[#59451](https://github.com/godotengine/godot/issues/59451) is probably also related to this as the errors reported in it are the same ones observed when this bug occurs.

**Comment by Calinou** [comment] 2022-10-04 22:27
Duplicate of https://github.com/godotengine/godot/issues/59451.

**Closed by Calinou** 2022-10-04 22:27 UTC
Labels: bug, topic:core, topic:2d
