### ISSUE TITLE
Godot editor popup menu starts with notable offset

### ISSUE THREAD

**Issue by zayngdev** [godotengine/godot#49254] opened 2021-06-02 12:10 UTC
**Godot version:**
Godot Engine v4.0.dev.custom_build.ac47e1d3e - https://godotengine.org
Vulkan API 1.2.162

**OS/device including version:**
GPU: nVidia Gefore 1050 Ti

**Issue description:**
Custom build godot latest source code then run the application, trying to add a new node, the pop up menu went to a new position in the editor with notable offset, the pop up menu suppose to open right under the node location, but it goes into another way. Here is the screenshot for reference. 
![panel_go_offset](https://user-images.githubusercontent.com/49690096/120477666-9bdc6380-c3de-11eb-85f5-68d27245b4c7.png)

**Comment by Chaosus** [comment] 2021-06-02 12:20
Duplicate of #45740

**Closed by Chaosus** 2021-06-02 12:20 UTC
