### ISSUE TITLE
Scaled+rotated controls move in the wrong directions

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#7064] opened 2016-11-07 21:59 UTC
Tested on Godot 2.1, Windows 10 64 bits

Repro:
1) Create a Control
2) Rotate it by 90 degrees
3) Set any of its Scale components to -1
4) Move the control: observe it moves in the wrong direction and won't follow the mouse

Test project:
[ControlMovesWrong.zip](https://github.com/godotengine/godot/files/576736/ControlMovesWrong.zip)

**Comment by Noshyaar** [comment] 2018-04-08 02:33
Can't reproduce on latest master. Does this still affect 2.1?

**Comment by Zylann** [comment] 2018-04-08 16:29
It still happens in 2.1.5 rc1.
It doesn't happen in 3.0.2.

**Comment by DualMatrix** [comment] 2018-09-16 15:53
Still relevant in 2.1.5

**Comment by akien-mga** [comment] 2018-09-17 13:40
The 2.1 branch is no longer actively worked on by engine developers, unless critical fixes are needed for current games in production. As such we are now closing non-critical bug reports affecting only the 2.1 branch.

Please comment if this was incorrectly triaged and is still relevant in 3.x versions.

**Closed by akien-mga** 2018-09-17 13:40 UTC
Labels: bug, topic:editor, usability
