### ISSUE TITLE
Can't move around items that are part of a Tree without scrolling it

### ISSUE THREAD

**Issue by YeldhamDev** [godotengine/godot#45893] opened 2021-02-11 13:52 UTC
**Godot version:**
`master`

**OS/device including version:**
Manjaro GNU/Linux

**Issue description:**
Attempting to move an item (e. g. a Node in the "Scene" dock) will resulting in the tree as a whole scrolling together with the item, making it impossible to actually move it from its previous spot.
![Peek 2021-02-11 11-27](https://user-images.githubusercontent.com/30739239/107649542-7849ad80-6c75-11eb-85f6-e183259d1717.gif)

**Comment by EricEzaM** [comment] 2021-02-11 22:05
This has been in master for a long time - several months at least. I thought I reported it but I guess not. I tried to look for the problematic code at some point but couldn't find it. `Tree` and its `gui_input` are quite convoluted.

**Comment by Calinou** [comment] 2021-02-11 22:25
Duplicate of https://github.com/godotengine/godot/issues/38665.

**Closed by Calinou** 2021-02-11 22:25 UTC
Labels: bug, confirmed, regression, topic:editor
