### ISSUE TITLE
V4.3 Audio is broken/loops when playing from inside an animation player with an animation tree

### ISSUE THREAD

**Issue by JoshuaWeissTBS** [godotengine/godot#95932] opened 2024-08-22 04:05 UTC
### Tested versions

- Reproducible in v4.3.stable.official [77dcf97d8]
- NOT reproducible in v4.2.2.stable.official [15073afe3]

### System information

Godot v4.3.stable - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3070 Ti (NVIDIA; 31.0.15.5222) - 12th Gen Intel(R) Core(TM) i9-12900K (24 Threads)

### Issue description

If you have an `AnimationTree` with an `AnimationNodeBlendTree` connected to an `AnimationPlayer` with an animation that has a keyframe to set the `playing` property to `true` from an `AudioStreamPlayer`, then play the scene the audio will break and loop making a terrible sound.

Playing the animation from the AnimationPlayer alone does not seem to reproduce the issue.

See video to see that the audio plays normally when you play it from the animation player but not when played from the animation tree or in the game.

https://github.com/user-attachments/assets/1ca170bd-ec0c-4207-b156-4cdc88fb5284

### Steps to reproduce

1. Create `AudioStreamPlayer` node and add a sound effect to it
2. Create `AnimationPlayer` node
3. Create an animation in the `AnimationPlayer` node that has a keyframe inside it setting the `playing` property of the `AudioStreamPlayer` node to `true`
4. Create an `AnimationTree` node and set it to `AnimationNodeBlendTree`, attach the `AnimationPlayer`
5. Inside the `AnimationNodeBlendTree` of the `AnimationTree`, right click and add an "Animation" and select the one previously created in the `AnimationPlayer` and drag it to the output.
6. Make sure the `AnimationTree` is active and playing the animation and observe that your ears hurt and it sounds like you're out of RAM

### Minimal reproduction project (MRP)

[audiobug.zip](https://github.com/user-attachments/files/16705208/audiobug.zip)

**Comment by TokageItLab** [comment] 2024-08-24 05:45
Dupe of https://github.com/godotengine/godot/issues/95684

**Closed by TokageItLab** 2024-08-24 05:45 UTC
Labels: bug, topic:audio, topic:animation
