### ISSUE TITLE
Not understandable error: "Resumed function 'function_name()' after yield, but script is gone"

### ISSUE THREAD

**Issue by fguillen** [godotengine/godot#73118] opened 2023-02-11 19:35 UTC
### Godot version

v3.5.1.stable.official [6fed1ffa3]

### System information

MacOS Ventura 13.1

### Issue description

Hello people, I am struggling to find what is the issue here. 

I have this function: 

```
func animate():  
	timer.start(1)
	print("Start")
	yield(timer, "timeout")
	print("Finished")
```
(It is a simplified version)

But when I execute the Scene I see this error:

> Resumed function 'animate()' after yield, but script is gone

In the line of the `yield`

The thing is that if I restart the Godot Editor the error is gone... until it is back.

I don't know what I am doing wrong. Any suggestion/idea?

## Update
I'm doing some debugging to see if the Node is freed but I don't see the object is freed. These are all the Notifications I am capturing with `_notification()`:

```
_notification: 20
_notification: 18
_notification: 12
_notification: 32
_notification: 10
_notification: 27
_notification: 13
Start
_notification: 2000
_notification: 31
_notification: 30
_notification: 12
_notification: 1002
_notification: 1003
_notification: 1005
_notification: 1004
_notification: 1002
_notification: 1003
_notification: 1005
```

See the `Start` is when the `yield` is invoked

## Update 2

I have connected the `timer.timeout()` with another method and on this method I can confirm the Node is still valid:

```
func animate():
	timer.start(1)
	print("Start")
	timer.connect("timeout", self, "on_timer_timeout")
	yield(timer, "timeout")
	print("Finished")

func on_timer_timeout():
	print("on_timer_timeout:", is_instance_valid(self))
```

I see in the Output: 

```
Start
on_timer_timeout:True
```

### Steps to reproduce

It is a random error. If I restart the Editor the error disappears for a while. And then appears again.

### Minimal reproduction project

I don't think I can create a minimal project that reproduces the issue :/. As I said, it is random and only occurs in my project at random moments. I hope I have added enough debug logs to identify if this is a real bug. Also I am newbie, sorry if my report is not completed.

I have a conversation in Reddit about this issue: https://www.reddit.com/r/godot/comments/10zmbqc/struggling_with_error_resumed_function_function/

**Comment by YuriSizov** [comment] 2023-02-11 20:35
The error means that you have freed the node holding that script in between the yield logic starting and the script resuming. If it is possible for your node to be freed mid yield, you should switch to full-featured signals instead of using yields, to avoid issues such as this one.

This was actually recently addressed in 4.0, but it's unlikely to be addressed in 3.x. Either way, there is no engine error, it's a problem with your project. Please prefer community platforms instead of GitHub to debug your projects.

**Closed by YuriSizov** 2023-02-11 20:35 UTC

**Comment by Maran23** [comment] 2023-02-13 20:45
> This was actually recently addressed in 4.0, but it's unlikely to be addressed in 3.x. Either way, there is no engine error, it's a problem with your project. Please prefer community platforms instead of GitHub to debug your projects.

Sorry for hijacking this report, but do you have a PR (or any information) for this?
I'm curious whether `yield`/`await` is always safe to use in 4.0 or (like in 3.x) only when you sure you won't `queue_free` the object in the meantime.

**Comment by YuriSizov** [comment] 2023-02-13 20:48
Here https://github.com/godotengine/godot/pull/65910

**Comment by mttkay** [comment] 2023-03-25 08:40
I think we should re-open this. I have a very minimal repro for this issue that does not involve any nodes being dynamically created or freed.

Create a single top-level node, then implement `_ready` like so:

```
extends Node


func _ready() -> void:
	print("await")
	yield(get_tree().create_timer(0.5), "timeout")
	print("done")
```

This will never print "done". It fails with the same error:

```
E 0:00:00.702   resume: Resumed function '_ready()' after yield, but script is gone. At script: res://main.gd:6
  <C++ Error>   Method failed. Returning: Variant()
  <C++ Source>  modules/gdscript/gdscript_function.cpp:1795 @ resume()
```

**Comment by mttkay** [comment] 2023-03-25 08:43
I noticed something interesting: when doing this in `_process()` instead, it works:

```
extends Node


func _process(delta) -> void:
	print("await")
	yield(get_tree().create_timer(0.5), "timeout")
	print("done")
```

prints:

```
await
done
await
done
await
done
await
done
...
```

I don't know how Godot manages memory internally, but it appears that if a script only has a `_ready` function that runs to completion, it frees the script resource that was associated with this node, perhaps because it knows that there is no additional logic that could ever run? :thinking:

**Comment by YuriSizov** [comment] 2023-03-25 12:36
@mttkay Scripts are not freed randomly after `_ready` is executed. Please upload an MRP if you have a reproduceable issue.

**Comment by mttkay** [comment] 2023-03-25 13:07
Sure thing. Done.

[godot-coroutine-repro.zip](https://github.com/godotengine/godot/files/11068944/godot-coroutine-repro.zip)

**Comment by nihiluis** [comment] 2023-09-29 08:04
This issue remains closed still?

**Comment by MattGoode92** [comment] 2024-04-16 19:48
Anyone have any updates on this? Currently banging my head against the wall with this error in my project in 4.2 and no idea how to fix it.

**Comment by KnightNine** [comment] 2024-07-25 02:30
If you aren't using multithreading and the signal is for a specific await call, you can add a bool before and after the await call, like so:
```gdscript
is_waiting = true
await added_to_entities_and_objects_needing_serialization
is_waiting = false
```
And only emit the signal in question when `is_waiting == true`, which negates the issue.
