### ISSUE TITLE
Blender-made model with armature and animation messed up when using gltf, fbx works fine

### ISSUE THREAD

**Issue by penguinroad** [godotengine/godot#40407] opened 2020-07-15 08:12 UTC
**Godot version:**

3.2.2

**OS/device including version:**

Nvidia GTX 750TI, NVidia 430XX, GLES3

**Issue description:**

Made a 3d model with armature and animation in Blender 2.80
[to_report_issue.zip](https://github.com/godotengine/godot/files/4923820/to_report_issue.zip)
, exported using gltf format (blender built in exporter) and the result is messed up model.

**Steps to reproduce:**
Open model file in blender, export to gltf, imported as a scene, open gltf file in godot 
[to_report_issue.zip](https://github.com/godotengine/godot/files/4923806/to_report_issue.zip)
![tanya](https://user-images.githubusercontent.com/27963743/87520692-e74a2e00-c6b5-11ea-8050-28388189a68b.png)

**Minimal reproduction project:**

**Comment by Calinou** [comment] 2020-07-15 08:18
Duplicate of #33057. Please upload a minimal reproduction project there to ease troubleshooting.

**Closed by Calinou** 2020-07-15 08:18 UTC

**Comment by fire** [comment] 2020-07-18 04:22
Blender 2.80 is not compatible please try 2.83.
