### ISSUE TITLE
The problem which in some cases isn't a problem with nodes with editable children

### ISSUE THREAD

**Issue by AtomaFajrovulpo** [godotengine/godot#34778] opened 2019-11-11 20:37 UTC
**Godot version:**

All

**OS/device including version:**

All

**Issue description:**

The issue is very hard to explain so below I have included instructions on how to reproduce the problem so that you can understand it better. The instructions are a way to illustrate this in an easy to see fashion but this can be reproduced many different ways.

**Steps to reproduce:**

0. Download the _Minimal reproduction project_ available below;
1. Open the project;
2. Open both _Node2D.tscn_ and _KinematicBody2D.tscn_;
3. Notice that in _Node2D.tscn_ there is an instanced node from _KinematicBody2D.tscn_ and this has editable children;
4. Check the Camera2D's limits. They should be as follows: L / T / R / B = 0 / 0 / 10000 / 10000;
5. Check the Camera2D's limits of the origial KinematicBody2D in _KinematicBody2D.tscn_. They should be as follows: L / T / R / B = -10000 / -10000 / 10000 / 10000;
6. Now let's say all in _Node2D.tscn_ is fine and how you want it. The KinematicBody2D's Camera limits (at L / T / R / B = 0 / 0 / 10000 / 10000) are exactly how you want them;
7. You then change the original KinematicBody2D from _KinematicBody2D.tscn_'s Camera2D's limits to L / T / R / B = -10000 / -10000 / 100 / 100;
8. You go back into _Node2D.tscn_ and noted that the R and B values of your KinematicBody2D's Camera2D's have changes from 10000 / 10000 to 100 / 100;
9. The rest (L / T) have kept the same.

Why ?

The Editor has stored the L / T values of the KinematicBody2D's Camera2D because it's children can be edited and they have changes.

However, the R and B are the same as 'normal', or the original KinematicBody2D, so they are remembered as being the same.

When the original KinematicBody2D's Camera2D's values changes, the ones which were the default in the _Node2D.tscn_ scene with the KinematicBody2D with editable children have changed to the 'new' default values.

This, in most cases is not wanted.

**However**, if the editor was to change in a way that 'copied' the Camera2D's limits, then this would act like a copied version, and no longer linked in any way to the original.

The feature that I think is missing that you can't make **some** children indepentant of an instanced node.

What if you made a copy of the node which is no longer linked and you wanted to change the script of the all ?

I feel like this is quite a conundrum ...

**Minimal reproduction project:**

[Editable Children Problem.zip](https://github.com/godotengine/godot-proposals/files/3833155/Editable.Children.Problem.zip)

**Comment by KoBeWi** [comment] 2020-01-06 22:00
It uses a bug report template, but it's actually a proposal. The described case works as intended.

I don't get the point of this issue. Is the camera just example or are you actually going to use multiple cameras per scene with different limits (which doesn't sound useful)? In any case, this problem can be avoided if in the instanced scene you set values that are different from the defaults. Implementing "unlinked" nodes would be rather unreasonable, especially because I doubt it's doable with less than 100 lines of code.

Also, what aaron suggested.

**Comment by AtomaFajrovulpo** [comment] 2020-01-07 18:05
So I have a Player with the Camera2D attached to it. I instance the Player and this gives me the Camera2D as well. I find it simpler that way.

**Comment by KoBeWi** [comment] 2020-11-27 21:00
Still valid in 3.2.3 beta3

**Comment by KoBeWi** [comment] 2022-02-25 15:42
This was resolved with the newly added property pinning.

**Closed by KoBeWi** 2022-02-25 15:42 UTC
Labels: bug, topic:editor, confirmed
