### ISSUE TITLE
Kinematic Body (3d) infinite_inertia false still moving RigidBody

### ISSUE THREAD

**Issue by orosmatthew** [godotengine/godot#38319] opened 2020-04-29 04:14 UTC
Godot version:
3.2.1 Stable

OS/device including version:
Windows 10

In the documentation, it says that if the infinite_inertia parameter for move_and_slide is false then it will not interact with RigidBody. It says that it would treat it as if it were a StaticBody. However, with this parameter false, it still is moving the RigidBody. If GodotPhysics is selected instead of Bullet for the physics engine, the game just crashes.

Also tested a similar setup with Godot 4.0 branch and the results are the same

[KinematicBug.zip](https://github.com/godotengine/godot/files/4549765/KinematicBug.zip)

**Comment by 19PHOBOSS98** [comment] 2020-05-23 02:26
duplicate:
https://github.com/godotengine/godot/issues/31981
https://github.com/godotengine/godot/issues/33988

**Comment by madmiraal** [comment] 2020-06-06 17:50
Closing as duplicate of #31981.

**Closed by madmiraal** 2020-06-06 17:50 UTC
Labels: bug, topic:physics
