### ISSUE TITLE
Console shows trio of errors on opening Godot.

### ISSUE THREAD

**Issue by Ace-Dragon** [godotengine/godot#1436] opened 2015-02-25 05:07 UTC
![godot errors](https://cloud.githubusercontent.com/assets/10081256/6365250/8d2d9674-bc79-11e4-92c8-3a0f0baf3ccd.jpg)
The console spits this out right when the Win64 dev. build is opened and the project list is displayed. The errors themselves don't cause any bugs, but just to make sure they don't become real bugs down the line.

Verified on Windows 7, I hope you would consider it good practice to report things like these.

**Comment by UsernameIsAReservedWord** [comment] 2015-02-25 12:05
these errors appear for each projects whose directory have been manually deleted (or renamed) without being Erased into the project-manager first.

into the editor, into the Editor Settings, there is a list of projects. The manually deleted projects are still listed here.

**Comment by akien-mga** [comment] 2015-11-17 15:45
Duplicate of #1267.

**Closed by akien-mga** 2015-11-17 15:45 UTC
Labels: archived, enhancement, topic:editor
