### ISSUE TITLE
Compile error "gradlew build"

### ISSUE THREAD

**Issue by git2013vb** [godotengine/godot#24066] opened 2018-11-29 21:33 UTC
**Godot version:**
5b8dde4

**OS/device including version:**
Win7-64

**Issue description:**
c:\godot\platform\android\java>gradlew build
Parallel execution is an incubating feature.

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'java'.
> Could not resolve all artifacts for configuration ':classpath'.
   > Could not resolve org.jetbrains.kotlin:kotlin-stdlib-jre8:1.2.0.
     Required by:
         project : > com.android.tools.build:gradle:3.2.0
         project : > com.android.tools.build:gradle:3.2.0 > com.android.tools.build:builder:3.2.0
         project : > com.android.tools.build:gradle:3.2.0 > com.android.tools.lint:lint-gradle-api:26.2.0
         project : > com.android.tools.build:gradle:3.2.0 > com.android.tools.build:gradle-api:3.2.0
         project : > com.android.tools.build:gradle:3.2.0 > androidx.databinding:databinding-compiler-common:3.2.0
         project : > com.android.tools.build:gradle:3.2.0 > com.android.tools.build:builder:3.2.0 > com.android.tools:sdk-common:26.2.0
         project : > com.android.tools.build:gradle:3.2.0 > com.android.tools.build:builder:3.2.0 > com.android.tools:common:26.2.0
         project : > com.android.tools.build:gradle:3.2.0 > com.android.tools.build:builder:3.2.0 > com.android.tools.build:manifest-merger:26.2.0
         project : > com.android.tools.build:gradle:3.2.0 > com.android.tools.build:builder:3.2.0 > com.android.tools:sdklib:26.2.0 > com.android.tools:repository:26.2.0
      > Could not resolve org.jetbrains.kotlin:kotlin-stdlib-jre8:1.2.0.
         > Could not get resource 'https://jcenter.bintray.com/org/jetbrains/kotlin/kotlin-stdlib-jre8/1.2.0/kotlin-stdlib-jre8-1.2.0.pom'.
            > Could not GET 'https://jcenter.bintray.com/org/jetbrains/kotlin/kotlin-stdlib-jre8/1.2.0/kotlin-stdlib-jre8-1.2.0.pom'.
               > Connection reset
   > Could not resolve org.ow2.asm:asm:6.0.
     Required by:
         project : > com.android.tools.build:gradle:3.2.0
         project : > com.android.tools.build:gradle:3.2.0 > com.android.tools.build:builder:3.2.0

From browser I can download the pom files.

**Minimal reproduction project:**
NA

**Comment by Calinou** [comment] 2020-01-18 21:16
I'll close this issue as I assume this error was due to a temporary issue on Bintray's server. Please comment if you can still reproduce this issue.

**Closed by Calinou** 2020-01-18 21:17 UTC
Labels: bug, platform:android, topic:porting
