### ISSUE TITLE
Sky not working in 4.4.dev1.

### ISSUE THREAD

**Issue by PhamDinhNghiep** [godotengine/godot#96252] opened 2024-08-29 01:06 UTC
### Tested versions

Reproducible in v4.4.dev1
Not Reproducible in v4.3.stable

### System information

Godot v4.4.dev1 - Windows 10.0.19045 - GLES3 (Compatibility) - NVIDIA GeForce RTX 3050 Ti Laptop GPU (NVIDIA; 31.0.15.4633) - 11th Gen Intel(R) Core(TM) i5-11400H @ 2.70GHz (12 Threads)

### Issue description

Sky works normally on 4.3.stable, but show gray color when open with 4.4.dev1.
![image](https://github.com/user-attachments/assets/d9c82cbe-c720-45c0-b2b0-cfc0f00d9c5d)
![image](https://github.com/user-attachments/assets/ce370c2e-da0a-41ac-b8e7-c67d5929cc31)

### Steps to reproduce

Open with 4.3.stable, sky show.
Open with 4.4.dev1, sky gray.

### Minimal reproduction project (MRP)

[sky_disappear.zip](https://github.com/user-attachments/files/16790486/sky_disappear.zip)

**Comment by matheusmdx** [comment] 2024-08-29 16:50
Actually this is not a bug/regression, you have fog enabled in your WorldEnvironment node but in 4.3 that was broken and sky wasn't affected by fog but that was fixed by #95662

![image](https://github.com/user-attachments/assets/71a36c02-bfbe-4381-b380-15ffdb3fc4d7)

<br>

To get the old behavior back you can just disable fog entirely or adjust how much the fog affect your sky

https://github.com/user-attachments/assets/d1a8b99b-ed26-40d6-8a7f-d1025e96ee29

**Closed** 2024-08-30 04:12 UTC
Labels: discussion, topic:rendering, documentation, topic:3d
