### ISSUE TITLE
Crashes when Importing multiple SVG files at once or multicolored SVG files

### ISSUE THREAD

**Issue by kcfresh53** [godotengine/godot#74718] opened 2023-03-10 13:20 UTC
### Godot version

4.0

### System information

Windows 11 22H2, GPU: Nvidia Mx330, CPU: intel core i5 10th gen, 12GB RAM

### Issue description

When importing multiple SVG files at once or importing a multicolored SVG file, Godot 4.0 crashes. The problem then goes away when the project is reopened for multiple SVG files, but it still crashes when dealing with multicolored SVGs.

### Steps to reproduce

Add a minimum of 30 monochrome SVG icons in a new project directory or one multicolored SVG file (e.g. Instagram logo) to recreate the issue. 

### Minimal reproduction project

"N/A"

**Comment by akien-mga** [comment] 2023-03-10 13:26
Please attach a reproduction project with SVG files which trigger the crash. This is highly dependent on the content of the files you're using so we can't necessarily reproduce it without them.

**Comment by kcfresh53** [comment] 2023-03-10 13:39
[Submission doc.zip](https://github.com/godotengine/godot/files/10942541/Submission.doc.zip)
![icons8-instagram](https://user-images.githubusercontent.com/62062589/224330371-05a5b801-2a50-4baf-9caa-209681715c17.svg)
![instagram-round-color-icon](https://user-images.githubusercontent.com/62062589/224330439-b48fcddf-92da-4650-8ef1-be8f4c1cfc85.svg)

Here. I was able to reproduce the problem with a different set of Icons as well.

**Comment by stmSi** [comment] 2023-03-15 11:05
I could not reproduce the crash. Removed `.import` files and `.godot` folder as well.. still cannot reproduce it.

**Comment by capnm** [comment] 2023-04-05 23:47
Tested with current godot tip. All images in your zip folder and the 48x48px one you posted directly have no problems at all.
The gigantic image is 88x88 meters (viewBox="0 0 333333 333333") takes a lot of time and memory (1GB). If you wait long enough, Godot doesn't crash...
```
WARNING: ImageLoaderSVG: Target canvas dimensions 333333×333333 (with scale 1.00) 
exceed the max supported dimensions 16384×16384. 
The target canvas will be scaled down.
     at: create_image_from_utf8_buffer (modules/svg/image_loader_svg.cpp:87)
```

**Comment by kcfresh53** [comment] 2023-04-10 11:36
I usually leave Godot running without clicking on anything and it still crashes. I tested it on a different computer with no problems but when trying a third computer, the problem persisted. The two computers that had the issue had a minimum of 12GB of ram, the one without issues uses 32GB of ram. I would assume it may have to do with memory but I am not sure.

**Comment by capnm** [comment] 2023-04-10 11:54
Try enabling _Editor Settings>Interface/Editor/Single Window Mode_, there are issues with external windows or look for _windows crash_ issues. It doesn't look like SVG related to me.

**Comment by YuriSizov** [comment] 2023-06-23 18:56
This does look like it is simply just too much to handle. Rasterizing such a large image requires quite a lot of memory. I'm not sure if there is a practical need for this, but I doubt it. So I'm going to close this issue.

**Closed by YuriSizov** 2023-06-23 18:56 UTC
Labels: bug, topic:thirdparty, topic:import, crash
