### ISSUE TITLE
The keyboard blocks my vision

### ISSUE THREAD

**Issue by HackFoxnew** [godotengine/godot#77054] opened 2023-05-14 08:04 UTC
### Godot version

4.1.0.dev2

### System information

Android 10

### Issue description

The keyboard obscures my vision

![Screenshot_20230514-033714](https://github.com/godotengine/godot/assets/100820447/19875f0a-a3b9-47c6-8ebb-cd28833f20f4)

![Screenshot_20230514-033720](https://github.com/godotengine/godot/assets/100820447/93fe9863-a15c-4d72-8197-e40c47db53b7)

In the images above you can see how the keyboard obscures my view when entering the folder name

![Screenshot_20230514-033936](https://github.com/godotengine/godot/assets/100820447/cc57bf9c-2069-492c-9611-58fb1883d8ff)
![Screenshot_20230514-033947](https://github.com/godotengine/godot/assets/100820447/846e3d16-cf4a-4a98-a2d9-8fdbe11841ec)

The problem intensifies in the code editor because I can't see what I'm doing.

### Ways to fix it

The first case when the keyboard obscures my vision when naming a folder can be implemented with this trick

![Screenshot_20230514-034043](https://github.com/godotengine/godot/assets/100820447/3365d201-bd8f-4ef6-92a3-8ec19a6c6525)
![Screenshot_20230514-034034](https://github.com/godotengine/godot/assets/100820447/5536d210-984c-4f28-8711-a29bb44a3d5b)

As you can see in the images I provided this trick is based on increasing the area where to write to take the entire screen, unfortunately I am not an Android developer so I can not say the specific name of this or how to put it.

And in the case of the code editor there are only two ways one better than the other

1-

![Screenshot_20230514-034108](https://github.com/godotengine/godot/assets/100820447/9f38ff06-208c-4c6d-ab79-6cd501e46d9c)

As you can see in the image, the first solution and the ugliest in my opinion is that the editor moves one or more lines after the | character, that is, the little line that marks where you are going to write the next character.

This solution is quite simple is just to give a line break whenever we put our | somewhere giving space so we can see what we are writing in that line.

The other solution and the best is to simply change the orientation of the editor to be vertical, this is the best because this is how you write in Android and phones in general vertically.

### Steps to reproduce

Simple just open Godot on your Mobil and try to code or do something with the keyboard.

### Minimal reproduction project

I really don't know what to put here

**Comment by AThousandShips** [comment] 2023-05-14 08:06
Duplicate of #76803

**Comment by Zireael07** [comment] 2023-05-14 08:07
duplicate of https://github.com/godotengine/godot/issues/76803

ninja'd

**Comment by AThousandShips** [comment] 2023-05-14 08:07
Please search before opening a new issue

**Comment by HackFoxnew** [comment] 2023-05-14 08:11
> Please search before opening a new issue 

Oh sorry I didn't realize, still I think the way I proposed to fix it is the best, is it ok to leave a comment with it?

**Comment by Zireael07** [comment] 2023-05-14 08:12
> The other solution and the best is to simply change the orientation of the editor to be vertical,

This won't work, as the side panels (tree/filesystem on the left and inspector on the right) take a lot of space. There's already an issue/proposal (I forgot which) open for this, as it's an issue on desktop too if you make the Godot window smaller (e.g. to fit another window side-by-side)

**Comment by HackFoxnew** [comment] 2023-05-14 08:16
> > The other solution and the best is to simply change the orientation of the editor to be vertical,
> 
> This won't work, as the side panels (tree/filesystem on the left and inspector on the right) take a lot of space. There's already an issue/proposal (I forgot which) open for this, as it's an issue on desktop too if you make the Godot window smaller (e.g. to fit another window side-by-side)

It is understandable but even so you can not make a line break in the editor, for example if the pointer or cursor is on line 14 the editor jumps to line 15 by placing the keyboard under line 14.

**Comment by Zireael07** [comment] 2023-05-14 08:19
The problem is NOT limited to the script editor. I had the issue with keyboard covering input when it comes to naming a scene or saving a file - places where adding a line break will not help at all. Another, more general solution is needed.

**Comment by HackFoxnew** [comment] 2023-05-14 08:30
> The problem is NOT limited to the script editor. I had the issue with keyboard covering input when it comes to naming a scene or saving a file - places where adding a line break will not help at all. Another, more general solution is needed.

Mm a general solution? I can't think of any, the only ones that come to my mind are in the editor to make a line break and in other places as you explain to make the input area maximized so that it occupies the whole screen as in the images.

Here you can see how when naming a folder the input area takes up the entire screen.

![Screenshot_20230514-034043.png](https://github.com/godotengine/godot/assets/100820447/5d877b5b-2cd8-4063-9682-76601e140983)


![Screenshot_20230514-034034.png](https://github.com/godotengine/godot/assets/100820447/3b87e52e-bb41-4c85-9247-80eba572e3c5)

**Comment by AThousandShips** [comment] 2023-05-14 08:32
Please continue this discussion on the other issue as this is a duplicate

**Comment by AThousandShips** [comment] 2023-05-14 09:32
Please go ahead and close this issue btw

**Comment by lawnjelly** [comment] 2023-05-14 09:57
Closing as duplicate of #76803 .

**Closed by lawnjelly** 2023-05-14 09:57 UTC
