### ISSUE TITLE
The preview turns grey after opening a screen

### ISSUE THREAD

**Issue by Caskader** [godotengine/godot#75348] opened 2023-03-26 07:22 UTC
### Godot version

3.4 stable

### System information

Chrome OS, GLSE3, INTEL CELERON  N4120 

### Issue description

It was one of my projects which I made in GODOT 3.1, Switching to  3.4, when I tried to preview a scene the editor turned grey and the background was invisible for settings . It was working fine when I ran the game. 
![Screenshot 2023-03-26 12 31 45 PM](https://user-images.githubusercontent.com/90761389/227761096-5ffe3d9f-fc19-44d7-b8b5-3f1870e32f73.png)

### Steps to reproduce

add a Worldenviroment node in godot 3.1 and run in godot 3.4 in a scene.

### Minimal reproduction project

[Archive.zip](https://github.com/godotengine/godot/files/11070994/Archive.zip)

**Comment by lawnjelly** [comment] 2023-03-26 09:54
The effect looks similar to #73799 . We haven't pinned this down yet, it seemed to be GLES3 specific, and could be a driver issue. It would be helpful to try in 3.5.2 on your machine, it could be a bug that was previously fixed.

https://godotengine.org/article/maintenance-release-godot-3-5-2/

**Comment by Caskader** [comment] 2023-03-26 16:59
Yes, it works on 3.5.2 GLES2. Thank you for your help!

**Comment by Calinou** [comment] 2023-03-26 17:01
- Duplicate of https://github.com/godotengine/godot/issues/73799.

**Closed by Calinou** 2023-03-26 17:01 UTC
Labels: bug, topic:rendering
