### ISSUE TITLE
"Callable" type is missing "Bind" method in C#, and maybe more.

### ISSUE THREAD

**Issue by Maveyyl** [godotengine/godot#68752] opened 2022-11-16 22:50 UTC
### Godot version

Godot_v4.0-beta4_mono_win64, Godot_v4.0-beta5_mono_win64

### System information

Windows 10

### Issue description

Up to godot v4.0 beta 3, Callable had a constructor in C# that took a delegate. I used that constructor to give lambda functions so that I could bind specific values to function calls.

In beta 4 and 5 that constructor disappeared. Therefore I'm supposed to use the "Bind" method to bind specific values, but that method is absent from the API.

### Steps to reproduce

Open any project on version Godot_v4.0-beta5_mono_win64 and Godot_v4.0-beta3_mono_win64, open the project in the c# editor of your choice, browse the Callable header, compare the API to the GDscript API of Callable.

**Comment by raulsntos** [comment] 2022-11-17 00:06
You can still use lambdas to construct a Callable using the `Callable.From` static method:

```csharp
Callable.From(() => GD.Print("Hello World"));
```

**Comment by Maveyyl** [comment] 2022-11-17 11:08
@raulsntos I missed that! Thanks!

**Comment by raulsntos** [comment] 2022-11-21 18:22
Duplicate of https://github.com/godotengine/godot/issues/66106

**Closed by raulsntos** 2022-11-21 18:22 UTC
Labels: bug, topic:dotnet
