### ISSUE TITLE
Random "Could not parse global class" errors that go away after saving the script in question

### ISSUE THREAD

**Issue by haroun-k** [godotengine/godot#74944] opened 2023-03-15 16:45 UTC
### Godot version

4.0.stable

### System information

Windows 11

### Issue description

While i was creating a resource "WorldResource", I tried to make an Array of another resource named "TiIeResource".
And that caused the error :
`"CouId not parse global class "TileResource" from "res://Scripts/TiIeResource.gd" . "`

There are the codes : 
WorldResource.gd
![image](https://user-images.githubusercontent.com/61124763/225376043-aaad5543-8e3e-41f1-866f-6bdec5511ef7.png)
TileResource.gd
![image](https://user-images.githubusercontent.com/61124763/225376491-b8e3397f-ad4d-45d2-b122-0173b2718fbc.png)

I then placed the "class_name" and the "extends" on separate lines in both files as such : 
![image](https://user-images.githubusercontent.com/61124763/225376822-8560afde-4df7-40e0-9403-483d90c6c165.png)

The error then disappeared and I was not able to reproduce it anymore, whether it was by reversing the changes or trying to replicate the situation in other files.  

### Steps to reproduce

N/A

### Minimal reproduction project

N/A

**Comment by pondc1** [comment] 2023-03-17 18:31
I also have run into this issue. Godot randomly decides to forget about certain class names unless I go to said problematic class file and change _something_ about it. Like your example, I rearranged the `class_name` and `extends` keyword, saved, and that seemed to fix it and I wasn't able to reproduce.

**Comment by LowFire** [comment] 2023-10-13 20:53
I had this exact thing happen to me while I was working on a GDExtension plugin and doing as suggested above fixed it. It's really weird because I didn't touch any of the GDScript in the plugin at all but it still happened. I decided to open the sample project for the plugin one day, and all of a sudden, I started getting tons of parser errors about classes not being recognized and the main global class for the plugin not being parsed. I had to go through each .gd file and change the script as suggested just to get the errors to go away. Also, the plugin didn't work at all until I got rid the errors. I was compiling and debugging the plugin from VSCode and it would throw errors there too.

I was working on a separate branch in my local repo, so at first I had thought I had did something in my C++ code that broke the plugin, but even after switching to the master branch, which is suppose to be the working branch, the parser errors still persisted.

**Comment by KoBeWi** [comment] 2024-08-04 12:33
This might be fixed in 4.3. Can anyone still reproduce it?

**Comment by akien-mga** [comment] 2024-08-08 09:19
Assuming fixed in 4.3 as there were indeed lots of fixes regarding parsing global classes. Please comment if you can still reproduce it in 4.3.rc3 or later.

**Closed by akien-mga** 2024-08-08 09:19 UTC
Labels: bug, topic:gdscript, needs testing

**Comment by Raikir-i-sh** [comment] 2025-01-27 05:24
Currently, i'm facing this issue. This issue comes up ONLY when i exported my game to android. It doesn't matter if its in Autoload class or not , i get this parser error . 

![Image](https://github.com/user-attachments/assets/eabcbbd6-3d16-42a3-b630-483929b79f4f)

**Comment by arian-nj** [comment] 2025-02-23 16:51
> Currently, i'm facing this issue. This issue comes up ONLY when i exported my game to android. It doesn't matter if its in Autoload class or not , i get this parser error .
> 
> ![Image](https://github.com/user-attachments/assets/eabcbbd6-3d16-42a3-b630-483929b79f4f)

did you find any solution having same problem when exporting to android

**Comment by KoBeWi** [comment] 2025-02-23 18:45
If it's only after export, maybe you are referencing editor-only class somehow?
