### ISSUE TITLE
GDScript 2.0 Can't Assign null to Signal-Typed Variable

### ISSUE THREAD

**Issue by Gastronok** [godotengine/godot#76589] opened 2023-04-29 19:24 UTC
### Godot version

v4.1.dev1.official [db1302637]

### System information

Windows 10

### Issue description

`var sig : Signal = null` results in "Cannot assign a value of type 'null' as 'Signal'".

Yet `var sig : Signal; print(sig)` prints "null::[Signal]", implying that they can in fact be null.

I'd like to include a strongly-typed Signal parameter in a function call that defaults to null.

### Steps to reproduce

`var sig : Signal = null`

### Minimal reproduction project

N/A

**Comment by dalexeev** [comment] 2023-04-30 04:56
All `Variant` types except `Object` (`Vector2`, `Color`, `Array`, etc.) are **not** nullable. Use `Signal()` for an empty signal.

```gdscript
var my_signal: Signal = Signal()
```

**Comment by kleonc** [comment] 2023-04-30 09:46
> Use `Signal()` for an empty signal.
> 
> ```gdscript
> var my_signal: Signal = Signal()
> ```

Which BTW is equivalent to:
```gdscript
var my_signal: Signal
```
as it will be initialized to the declared type's default value (which in this case is `Signal()`).

---

> `var sig : Signal = null` results in "Cannot assign a value of type 'null' as 'Signal'".
> 
> Yet `var sig : Signal; print(sig)` prints "null::[Signal]", implying that they can in fact be null.

I agree that's not a bug. What confused OP is how an empty Signal is being printed out: `null::[signal]`. But `null` in there tells what Object is assigned to the Signal, it doesn't mean the Signal itself is null. That's just how Signal is being formated/stringified:
https://github.com/godotengine/godot/blob/9f12e7b52d944281a39b7d3a33de6700c76cc23a/core/variant/callable.cpp#L443-L455

It seems consistent and not sure if anything in that aspect could be improved:
```gdscript
extends Node

signal signal_name

func _ready() -> void:
	print(Signal())
	print(signal_name)
```
Outputs:
```
null::[signal]
Node(script_name.gd)::[signal]signal_name
```

---

> I'd like to include a strongly-typed Signal parameter in a function call that defaults to null.

Just to be clear: so what you want is an empty Signal:
```gdscript
func foo(signal_parameter := Signal()) -> void:
	pass
```
Note there's `Signal.is_null` method and `Signal().is_null()` returns true. Yeah, this method's name might be a little confusing too. But it is what it is, it's too late for potential renaming. However, [the docs correctly explain what it actually returns](https://docs.godotengine.org/en/4.0/classes/class_signal.html#class-signal-method-is-null).

**Comment by dalexeev** [comment] 2023-07-06 09:55
* Duplicate of #72350.

**Closed by dalexeev** 2023-07-06 09:55 UTC
Labels: topic:gdscript
