### ISSUE TITLE
Flood of compute_list_bind_uniform_set errors when changing scenes that involve Volumetric Fog

### ISSUE THREAD

**Issue by cridenour** [godotengine/godot#77680] opened 2023-05-31 05:51 UTC
### Godot version

v4.0.3.stable.official [5222a99f5]

### System information

Windows 10, Forward+

### Issue description

If you have a scene that has a Sky and Volumetric Fog enabled in WorldEnvironment and change to a scene that has Volumetric Fog enabled, you will forever get a flood of errors like:

```
ERROR: Uniforms were never supplied for set (0) at the time of drawing, which are required by the pipeline
   at: (drivers\vulkan\rendering_device_vulkan.cpp:8007)
ERROR: Condition "!uniform_set" is true.
   at: RenderingDeviceVulkan::compute_list_bind_uniform_set (drivers\vulkan\rendering_device_vulkan.cpp:7808)
ERROR: Uniforms supplied for set (0):
Set: 0 Binding: 1 Type: Texture Writable: N Length: 1
Set: 0 Binding: 2 Type: Texture Writable: N Length: 1
Set: 0 Binding: 3 Type: StorageBuffer Writable: N Length: 0
Set: 0 Binding: 4 Type: StorageBuffer Writable: N Length: 0
Set: 0 Binding: 5 Type: UniformBuffer Writable: N Length: 3712
Set: 0 Binding: 6 Type: StorageBuffer Writable: N Length: 0
Set: 0 Binding: 7 Type: Sampler Writable: N Length: 1
Set: 0 Binding: 8 Type: Image Writable: Y Length: 1
Set: 0 Binding: 9 Type: Image Writable: Y Length: 1
Set: 0 Binding: 10 Type: Sampler Writable: N Length: 1
Set: 0 Binding: 11 Type: UniformBuffer Writable: N Length: 896
Set: 0 Binding: 12 Type: Texture Writable: N Length: 8
Set: 0 Binding: 13 Type: Sampler Writable: N Length: 1
Set: 0 Binding: 14 Type: UniformBuffer Writable: N Length: 304
are not the same format as required by the pipeline shader. Pipeline shader requires the following bindings:
Set: 0 Binding: 1 Type: Texture Writable: N Length: 1
Set: 0 Binding: 2 Type: Texture Writable: N Length: 1
Set: 0 Binding: 3 Type: StorageBuffer Writable: N Length: 0
Set: 0 Binding: 4 Type: StorageBuffer Writable: N Length: 0
Set: 0 Binding: 5 Type: UniformBuffer Writable: N Length: 3712
Set: 0 Binding: 6 Type: StorageBuffer Writable: N Length: 0
Set: 0 Binding: 7 Type: Sampler Writable: N Length: 1
Set: 0 Binding: 8 Type: Image Writable: Y Length: 1
Set: 0 Binding: 9 Type: Image Writable: Y Length: 1
Set: 0 Binding: 10 Type: Sampler Writable: N Length: 1
Set: 0 Binding: 11 Type: UniformBuffer Writable: N Length: 896
Set: 0 Binding: 12 Type: Texture Writable: N Length: 8
Set: 0 Binding: 13 Type: Sampler Writable: N Length: 1
Set: 0 Binding: 14 Type: UniformBuffer Writable: N Length: 304
Set: 0 Binding: 15 Type: Texture Writable: N Length: 1
Set: 0 Binding: 16 Type: Image Writable: Y Length: 1
Set: 0 Binding: 17 Type: Image Writable: Y Length: 1
Set: 0 Binding: 18 Type: Image Writable: Y Length: 1
Set: 0 Binding: 19 Type: Texture Writable: N Length: 1
   at: (drivers\vulkan\rendering_device_vulkan.cpp:8010)
```

This seems to be a problem introduced with 4.0.3 and potentially on a cursory glance, could be from #76437?

Currently a major blocker for anyone using fog. Have not found any workaround.

### Steps to reproduce

1. Create Scene 1 with Light, World Environment Camera.
2. Add a Sky (can be empty but must exist) and enable Volumetric Fog.
3. Create Scene 2 with the same, add Volumetric Fog.
4. Change from scene 1 to 2.

### Minimal reproduction project

[fog-uniform.zip](https://github.com/godotengine/godot/files/11609116/fog-uniform.zip)

**Comment by bitsawer** [comment] 2023-05-31 07:16
Duplicate of https://github.com/godotengine/godot/issues/77515?

**Comment by Lippanon** [comment] 2023-05-31 16:08
> Duplicate of #77515?

Yes, I think so.

**Comment by cridenour** [comment] 2023-05-31 17:20
> Duplicate of #77515?

Yes, weird that didn't come up searching the error message / function.

**Comment by Chaosus** [comment] 2023-05-31 17:42
Duplicate of https://github.com/godotengine/godot/issues/77515

**Closed by Chaosus** 2023-05-31 17:42 UTC
