### ISSUE TITLE
Godot Beta v2.0 crashes on Vista

### ISSUE THREAD

**Issue by techtonik** [godotengine/godot#3546] opened 2016-02-02 07:41 UTC
![image](https://cloud.githubusercontent.com/assets/515889/12742724/7067059c-c999-11e5-9d5f-4ea0a5f25283.png)

```
Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	Godot_v2.0_beta_20160126_win32.exe
  Application Version:	2.0.0.0
  Application Timestamp:	56a752a6
  Fault Module Name:	StackHash_b769
  Fault Module Version:	0.0.0.0
  Fault Module Timestamp:	00000000
  Exception Code:	c0000005
  Exception Offset:	00000000
  OS Version:	6.0.6002.2.2.0.768.2
  Locale ID:	1033
  Additional Information 1:	b769
  Additional Information 2:	440e673e508678a0cefed7e4a9f70c92
  Additional Information 3:	698e
  Additional Information 4:	492fe01a663e01fb29365e590414d405

Read our privacy statement:
  http://go.microsoft.com/fwlink/?linkid=50163&clcid=0x0409
 ```

**Comment by kubecz3k** [comment] 2016-02-02 09:33
It would be nice if you could provide some info on your system like at least gpu and cpu

**Comment by techtonik** [comment] 2016-02-02 12:21
@kubecz3k this seems to be rather critical piece of information. Is Godot_v2.0_beta_20160126_win32.exe able to provide such info? Or maybe there is a script in repository that I can run?

**Comment by techtonik** [comment] 2016-02-02 13:43
CPU:
```
>python -c "import cpuinfo, pprint; pprint.pprint(cpuinfo.cpu.info[0])"
...
 'Family': 6,
 'FeatureSet': 2687451135L,
 'Identifier': u'x86 Family 6 Model 23 Stepping 10',
 'Model': 23,
 'Platform ID': 128,
...
 'ProcessorNameString': u'Intel(R) Core(TM)2 Duo CPU     P8600  @ 2.40GHz',
 'Stepping': 10,
...
 'Update Status': 2,
 'VendorIdentifier': u'GenuineIntel',
 '~MHz': 2394}
```

**Comment by techtonik** [comment] 2016-02-02 13:55
```
RAM:  419/3029 MB
GPU:  Mobile Intel(R) GMA 4500MHD
```

**Comment by Calinou** [comment] 2016-02-02 14:19
> GPU:  Mobile Intel(R) GMA 4500MHD

Sorry, but this graphics adapter is really unsuited to gaming, and even more to game development. The Windows drivers for those are horrible. (They are in a much better state as of Sandy Bridge.)

**Comment by akien-mga** [comment] 2016-02-02 14:40
Duplicate of #1162 then.

**Closed by akien-mga** 2016-02-02 14:40 UTC
Labels: bug, platform:windows

**Comment by techtonik** [comment] 2016-02-02 15:05
> Sorry, but this graphics adapter is really unsuited to gaming, and even more to game development. The Windows drivers for those are horrible. (They are in a much better state as of Sandy Bridge.)

Well, `wesnoth` there works without problem, and I need an engine for 2D games (which Godot promises to deliver). I no need any of fancy 3D shaders - plain sprite moving is more than enough. It looks like Adobe Flash / Air is the only choice for such games, which is a pity, because 3D is really not a way to go for one man army.

**Comment by techtonik** [comment] 2016-02-02 15:08
> This may be more true in the future with the upcoming OpenGL ES 3.0 renderer.

Is there OpenGL ES 2.0 renderer already? I may use it through ANGLE (#3529) if it links to `libGLESv2.dll` driver - https://groups.google.com/forum/#!topic/angleproject/j97Ps7gtkug
