### ISSUE TITLE
Some GDExtension methods are unavailable in Release builds

### ISSUE THREAD

**Issue by Bromeon** [godotengine/godot#86206] opened 2023-12-15 17:39 UTC
### Tested versions

4.2.0-stable
4.2.1-stable

### System information

Windows 10

### Issue description

Godot release builds (aka export templates) do not provide the `ResourceImporterOggVorbis` methods `load_from_buffer()` and `load_from_file()`. There might be more (now or in the future).

In godot-rust, we noticed it because we check for method availability at startup time. Downstream issue: https://github.com/godot-rust/gdext/issues/489.
**However, this affects all bindings**, including godot-cpp. If someone tries to call the methods, it will fail for exported games. What makes this delicate is that it works in Debug mode but breaks in Release, so it can go undetected.

I think it's OK that not all methods are available, but this information should be exposed via `extension_api.json`, so that bindings can take appropriate steps, e.g. to remove the methods or warn upon their usage.

### Steps to reproduce

In a GDExtension binding, try to call either of the following methods:
- `ResourceImporterOggVorbis::load_from_buffer` 
- `ResourceImporterOggVorbis::load_from_file`

### Minimal reproduction project (MRP)

N/A

**Comment by AThousandShips** [comment] 2023-12-15 17:41
These shouldn't work in GDScript either from a glance at the code, can you confirm it does?

**Comment by YuriSizov** [comment] 2023-12-15 17:47
Indeed, this class seems to be only registered in editor builds (tools enabled) for the purpose of documenting import options. Likely all similar classes are affected.

Interestingly enough, the class is present in template builds anyway, because it's needed by `AudioStreamOggVorbis` to load OGG files at runtime. But it doesn't need to be exposed for that itself. So the question is, what should happen with classes which are exposed but are not supposed to be used in the API.

**Comment by AThousandShips** [comment] 2023-12-15 17:47
The importer itself isn't exposed on non-tool builds, what happens if you use the method on `AudioStreamOggVorbis` instead?

**Comment by YuriSizov** [comment] 2023-12-15 17:52
IIUC, the issue is that the class is marked as `core` and not as `editor`. This is what needs to be fixed:

```
			"name": "ResourceImporterOggVorbis",
			"is_refcounted": true,
			"is_instantiable": true,
			"inherits": "ResourceImporter",
			"api_type": "core",
```

**Closed** 2023-12-16 16:56 UTC
Labels: bug, topic:gdextension

**Comment by MeganSpencer** [comment] 2023-12-18 00:27
It looks like 4.3 is a long way off. I hit this bug on the very literal actual first simple Godot rust hello world project. I suspect that most people trying gdext with rust is going to hit this problem between now and May. So it may be worth considering merging this into an earlier minor release if one is planned.

**Comment by Bromeon** [comment] 2023-12-18 09:11
@MeganSpencer I implemented the same change downstream in godot-rust, to bridge the time until this hits a stable release. If you update your version to latest `master`, you should not have problems in export builds anymore.

https://github.com/godot-rust/gdext/pull/537

**Comment by YuriSizov** [comment] 2023-12-18 09:59
> So it may be worth considering merging this into an earlier minor release if one is planned.

It is already considered, hence the cherrypick label on the PR.
