### ISSUE TITLE
Angular Motor of 6DOF Joint isn't working predictably in Godot 4.0

### ISSUE THREAD

**Issue by Rinocrosser** [godotengine/godot#68852] opened 2022-11-18 19:53 UTC
### Godot version

4.0 Beta 5

### System information

Windows 10, Windows 11, irrelevant to the issue

### Issue description

Angular motor setup that worked in Godot 3.5 no longer works (recreated) in Godot 4 Beta 5.

- I make custom vehicle setup (instead of vehicle node for customization purpose)
- Each wheel is connected to the main body via a 6DOF joint
- I disable the X-axis rotation lock
- I enable X-axis angular motor
- It works in Godot 3.x, but do nothing in Godot 4
- In general, Godot 4 joints work (for example, if I rotate the ground, the car rolls on it)
- If we apply force to the car, it also gonna roll

Here is how it looks (meshes are just placeholders)

![image](https://user-images.githubusercontent.com/19660324/202789602-2769b23b-5ac3-4155-98d0-210fd94f604d.png)

### Steps to reproduce

Described above

### Minimal reproduction project

[GODOT_01.zip](https://github.com/godotengine/godot/files/10044429/GODOT_01.zip)

**Comment by Calinou** [comment] 2022-11-18 21:13
Can you test this on 3.5 with the 3D physics engine set to **GodotPhysics** instead of the default Bullet?

**Comment by Rinocrosser** [comment] 2022-11-18 21:23
> Can you test this on 3.5 with the 3D physics engine set to GodotPhysics instead of the default Bullet? 4.0 uses GodotPhysics by default.

Yep, it isn't working if I switch to Godot Physics in 3.5, only works in Default

**Comment by Rinocrosser** [comment] 2022-11-18 21:30
I left it for 3 minutes and after that one wheel (of two with motors) started to rotate oddly (Gofot Physics, 3.5)

https://user-images.githubusercontent.com/19660324/202806083-5a42732c-bedf-4e82-8d93-47e5ece9b124.mp4

**Comment by Rinocrosser** [comment] 2022-11-18 23:48
@Calinou another interesting point is that I switched to Hinge 3D instead and angular limits are not actually limiting anything if the motor is enabled (and if they crossed the original value)

![image](https://user-images.githubusercontent.com/19660324/202821398-26816839-77c5-4fd0-bbce-8407cd6b01ef.png)

**Comment by akien-mga** [comment] 2022-11-24 11:12
Duplicate of #66335.

**Closed by akien-mga** 2022-11-24 11:12 UTC
Labels: bug, topic:physics, topic:3d
