### ISSUE TITLE
Tile palette displays the tile index twice in tooltip

### ISSUE THREAD

**Issue by Torguen** [godotengine/godot#78215] opened 2023-06-14 08:24 UTC
### Godot version

v3.6.beta2.official [68c507f59]

### System information

w10 64

### Issue description

When you select a tile and the info box appears, the tile's index is displayed twice, once at the beginning and once at the end.

![Captura](https://github.com/godotengine/godot/assets/19652075/4c24708d-5f3f-4061-8eb2-a3fde3e193ee)

### Steps to reproduce

Select a tile and see the info box

### Minimal reproduction project

...

**Comment by Shivansh175** [comment] 2023-06-30 21:32
Is this issue fixed now...? If not I would love to select this as my first open source project to contribute.

**Comment by Miguel0312** [comment] 2023-07-11 05:32
I am not being able to reproduce the bug on Linux at least.
![Godot_TileSetLabel](https://github.com/godotengine/godot/assets/52176659/c1465ac1-9a2d-476d-a537-fbeb3f1e6641)

**Comment by Torguen** [comment] 2023-07-11 10:02
But has a consensus been reached on how to solve it?
I don't see anything here.

**Comment by ARez2** [comment] 2023-07-11 10:05
![image](https://github.com/godotengine/godot/assets/75789249/87e75426-6e49-43c3-9aa0-416c323a76fd)
Yes on the v3.6.beta2.official [68c507f59] version, I cannot reproduce this anymore.

(Kind of sad, since I just found the place where it was adding the ID behind the name and was ready to "fix" it. But the solution seems to have been to omit the first "<ID> - " before the name.)

**Comment by Torguen** [comment] 2023-07-11 10:11
But I have that version and in my version the index is still displayed twice.

![Captura](https://github.com/godotengine/godot/assets/19652075/8a67532f-a420-451e-80e8-b3b0412bb752)

v3.6.beta2.official [68c507f59]

**Comment by akien-mga** [comment] 2023-07-11 10:26
Are you sure you didn't name your file `0 - tilesetFondoEscenas.png`?

**Comment by ARez2** [comment] 2023-07-11 10:31
Also, can you create a new tileset/ add the tiles anew?

**Comment by Torguen** [comment] 2023-07-11 10:37
The original name has no numbers.

![Captura](https://github.com/godotengine/godot/assets/19652075/83714571-0dec-4ab3-88d0-7569b8bba451)

I can add new tiles/tilesets and the two numbers appear: "X tileset.png - X".

**Comment by akien-mga** [comment] 2023-07-11 10:46
The prefix `0 - ` is added by the editor setting `editors/tile_map/show_tile_ids` which @Torguen seems to have enabled. It needs to be enabled to reproduce the issue.

The suffix `0` must be added by mistake. The relevant code to debug is `TileMapEditor::_update_palette` in `editor/plugins/tile_map_editor_plugin.cpp`.

**Comment by kleonc** [comment] 2023-07-11 11:05
The thing is tiles created through the editor have their ID automatically added at the end of their name:
https://github.com/godotengine/godot/blob/ac5d7dc82187940a5fb2908e276cf8eb0861cac4/editor/plugins/tile_set_editor_plugin.cpp#L1349

And additional ID is added to the ItemList's item name as prefix/suffix according to the editor settings:
https://github.com/godotengine/godot/blob/ac5d7dc82187940a5fb2908e276cf8eb0861cac4/editor/plugins/tile_map_editor_plugin.cpp#L457-L458
https://github.com/godotengine/godot/blob/ac5d7dc82187940a5fb2908e276cf8eb0861cac4/editor/plugins/tile_map_editor_plugin.cpp#L475-L485

So if the tile names don't contain IDs themselves then it works ok-ish. Otherwise the ID is shown twice.

It could be solved by showing an explicit tooltip (for the ItemList items) like:
```
Name: ...
ID: ...
```
I guess the question is what should be shown as ItemList's item name when `editors/tile_map/show_tile_ids` is enabled.

**Comment by kleonc** [comment] 2023-07-12 10:57
> It could display something like:
> 
> ID = X
>Name = tileset.png

The issue is ItemList doesn't properly support new line character (`\n`) in item names. And it's set to auto wrap within max 2 lines.
Hence I think it can be something simple as e.g. "#ID Name" or "[ID] Name". And more details in the tooltip.
![U700pQ1eeR](https://github.com/godotengine/godot/assets/9283098/864cb49a-e3b0-4ae8-94b2-d275244ee1f1)
![CGDqGEw5c4](https://github.com/godotengine/godot/assets/9283098/eaa1bb40-9618-4ecd-8feb-147b14c13a0c) ![godot windows tools 64_1HWMA2y6FD](https://github.com/godotengine/godot/assets/9283098/67b67c52-7ed8-4cef-a001-519e821322c6)

**Comment by akien-mga** [comment] 2023-12-13 12:25
Fixed by #79376.

**Closed by akien-mga** 2023-12-13 12:25 UTC
Labels: bug, topic:editor
