### ISSUE TITLE
Theme editor - Clicking add or remove button under a Type's style causes theme editor window to close

### ISSUE THREAD

**Issue by nickjfrench** [godotengine/godot#73076] opened 2023-02-11 05:34 UTC
### Godot version

4.0 beta 17

### System information

Windows 10, GTX 1080ti (Driver #527.56), GL_Compatibility renderer

### Issue description

Within Theme Editor, if I add a new Type (e.g. RichTextLabel) then I click the plus (add) next to default_color it closes the theme editor window. This happens with trash can (removing) icon too. 

I've tried this with multiple Types and styles, all do the same. See video below.

https://user-images.githubusercontent.com/64120654/218242230-f0244258-1ab2-4068-9723-628920b4c5f2.mp4

EDIT: Happens on adding Fonts too, both on the pencil icon then on the New FontFile options.

### Steps to reproduce

1. Create new theme
2. Save into file
3. Add new Type (e.g. RichTextLabel)
4. Add new style or remove existing style (e.g. default_color)

### Minimal reproduction project

N/A

**Comment by EntityinArray** [comment] 2023-02-11 06:24
Happens to me on Godot_v4.0-rc1_win64 as well.
It also throws this error as theme editor closes:
```
  editor/plugins/theme_editor_plugin.cpp:2289 - Condition "edited_theme.is_null()" is true.
```
![Godot_v4 0-rc1_win64_kocyImbzyA](https://user-images.githubusercontent.com/18554021/218243983-3b881d91-3e9f-47bb-84cf-06192b6dcf89.png)

**Comment by akien-mga** [comment] 2023-02-11 10:14
Duplicate of #72271

**Closed by akien-mga** 2023-02-11 10:14 UTC
