### ISSUE TITLE
Regression: Crash double clicking on GLB file in Beta 7

### ISSUE THREAD

**Issue by Flynsarmy** [godotengine/godot#69706] opened 2022-12-07 07:10 UTC
### Godot version

v4.0.beta7.official.0bb1e89fb

### System information

Windows 11,  Vulkan API 1.2.0, NVIDIA GeForce RTX 3070 Ti

### Issue description

Double clicking on a GLB with a mesh crashes in Beta 7. The same file works fine in Beta 6 to open the advanced import popup.

Running Godot from the command line to get logs, I'm presented with the following:
 ./Godot_v4.0-beta7_win64.exe -v -e --path "C:\path\to\project"
> ...
> glTF: Total animations '3'.
> glTF: Converting spatial: game_rig
> glTF: Creating mesh for: BaseLady
> Illegal instruction

### Steps to reproduce

1. Extract the attached GLB to a new project in Beta 7. [baselady.zip](https://github.com/godotengine/godot/files/10173597/baselady.zip)
2. Double click on it.

### Minimal reproduction project

See steps to reproduct above.

**Comment by akien-mga** [comment] 2022-12-07 09:12
Duplicate of #69604

**Closed by akien-mga** 2022-12-07 09:12 UTC
Labels: bug, archived, topic:editor, crash, regression
