### ISSUE TITLE
When you click on the scrolling list with apple pencil, it will become a sliding effect(Version 3.5) 

### ISSUE THREAD

**Issue by jl1872002** [godotengine/godot#73030] opened 2023-02-10 06:47 UTC
### Godot version

3.5

### System information

macos 13.0.1 (22A400)

### Issue description

Godot exports the project to the iPad.
When you click on the list of iPad applications with an Apple pencil,
the list will have a little sliding effect.
scroll_deadzone has been set to 10.

It is a list in the godot app,
The control uses ScrollContainer and GridContainer.
As long as you try it on the scrollContainer with apple pencil, it is bound to occur.
If the deadzone is not set, the sliding distance will be greater.

The click event has been removed from the list item in the video, so there should be no response after clicking.
Click the small exclamation mark button to pop up the details page.
It's easy to operate with my fingers.

These are the logs when clicking list with apple pencil:
2023-02-10 14:21:14.456031+0800 Hdd[55108:2402134] [InputEventMouseButton:28160]
2023-02-10 14:21:14.456099+0800 Hdd[55108:2402134] [InputEventMouseButton:28160]
2023-02-10 14:21:14.456135+0800 Hdd[55108:2402134] [InputEventMouseButton:28160]
2023-02-10 14:21:14.456169+0800 Hdd[55108:2402134] [InputEventMouseButton:28160]
2023-02-10 14:21:14.456747+0800 Hdd[55108:2402134] [InputEventMouseMotion:28168]
2023-02-10 14:21:14.456791+0800 Hdd[55108:2402134] [InputEventMouseMotion:28168]
2023-02-10 14:21:14.456857+0800 Hdd[55108:2402134] [InputEventMouseMotion:28168]
2023-02-10 14:21:14.456878+0800 Hdd[55108:2402134] [InputEventMouseMotion:28168]
2023-02-10 14:21:14.457280+0800 Hdd[55108:2402134] [InputEventMouseButton:28177]
2023-02-10 14:21:14.457320+0800 Hdd[55108:2402134] [InputEventMouseButton:28177]
2023-02-10 14:21:14.457357+0800 Hdd[55108:2402134] [InputEventMouseButton:28177]
2023-02-10 14:21:14.457393+0800 Hdd[55108:2402134] [InputEventMouseButton:28177]

These are the logs when you click the list by hand:
2023-02-10 14:21:02.142501+0800 Hdd[55108:2402134] [InputEventMouseButton:28124]
2023-02-10 14:21:02.142572+0800 Hdd[55108:2402134] [InputEventMouseButton:28124]
2023-02-10 14:21:02.142608+0800 Hdd[55108:2402134] [InputEventMouseButton:28124]
2023-02-10 14:21:02.142644+0800 Hdd[55108:2402134] [InputEventMouseButton:28124]
2023-02-10 14:21:02.143101+0800 Hdd[55108:2402134] [InputEventScreenTouch:28132]
2023-02-10 14:21:02.143125+0800 Hdd[55108:2402134] [InputEventScreenTouch:28132]
2023-02-10 14:21:02.143143+0800 Hdd[55108:2402134] [InputEventScreenTouch:28132]
2023-02-10 14:21:02.143161+0800 Hdd[55108:2402134] [InputEventScreenTouch:28132]
2023-02-10 14:21:02.143378+0800 Hdd[55108:2402134] [InputEventMouseButton:28141]
2023-02-10 14:21:02.143418+0800 Hdd[55108:2402134] [InputEventMouseButton:28141]
2023-02-10 14:21:02.143451+0800 Hdd[55108:2402134] [InputEventMouseButton:28141]
2023-02-10 14:21:02.143485+0800 Hdd[55108:2402134] [InputEventMouseButton:28141]
2023-02-10 14:21:02.143734+0800 Hdd[55108:2402134] [InputEventScreenTouch:28149]
2023-02-10 14:21:02.143757+0800 Hdd[55108:2402134] [InputEventScreenTouch:28149]
2023-02-10 14:21:02.143788+0800 Hdd[55108:2402134] [InputEventScreenTouch:28149]
2023-02-10 14:21:02.143807+0800 Hdd[55108:2402134] [InputEventScreenTouch:28149]

### Steps to reproduce

When you click on the list of iPad applications with an Apple pencil

### Minimal reproduction project

N/A

**Comment by AThousandShips** [comment] 2023-02-10 09:23
What's the difference between this and #72644

**Comment by jl1872002** [comment] 2023-02-10 09:37
> What's the difference between this and #72644

This is the same question. I thought the new question would be answered

**Comment by akien-mga** [comment] 2023-02-10 10:20
Duplicate of #72644

**Closed by akien-mga** 2023-02-10 10:20 UTC
