### ISSUE TITLE
Selecting a field and scrolling out keeps drawing outline

### ISSUE THREAD

**Issue by coppolaemilio** [godotengine/godot#11707] opened 2017-09-29 20:16 UTC
Windows 10

**Issue description:**
If you select an about field (Authors or Donors) and scroll, the outline keeps drawing outside of the dialog.

**Steps to reproduce:**
1. Open the about dialog and select a field

![selecting](https://user-images.githubusercontent.com/2206700/31034270-9e501bcc-a563-11e7-888f-7d67f42b9552.JPG)

2. Scroll down

![scrolling](https://user-images.githubusercontent.com/2206700/31034279-a6a87f1c-a563-11e7-893a-9d959937dfe5.JPG)

**Comment by Noshyaar** [comment] 2017-09-29 21:18
Duplicate of #9612

**Closed by Noshyaar** 2017-09-29 21:18 UTC
