### ISSUE TITLE
Code helper tooltip misses base functions on script extending

### ISSUE THREAD

**Issue by MrModez** [godotengine/godot#3168] opened 2015-12-29 19:40 UTC
If you extend script file, code helper won't show you inherited functions/variables
![issue](https://i.imgur.com/4UVLdOm.png)

**Comment by MrModez** [comment] 2015-12-29 20:28
Well that's more a bug, than an enhancement offer

**Comment by vnen** [comment] 2015-12-29 20:54
This is related to (if not the same as) #1039.

**Comment by akien-mga** [comment] 2016-07-15 09:24
Closing as duplicate of #1039 indeed.

**Closed by akien-mga** 2016-07-15 09:24 UTC
Labels: enhancement, topic:editor, topic:gdscript
