### ISSUE TITLE
runtime error when using the range function in a for loop with a variable as argument

### ISSUE THREAD

**Issue by Gnumaru** [godotengine/godot#73850] opened 2023-02-23 23:31 UTC
### Godot version

4.0.rc4

### System information

windows 10

### Issue description

When iterating in a for loop using the range function directly, instead of keeping the result in a variable and looping over it, and using some value from another variable as parameter for the range function (instead of using only int literals):

```gdscript
var v = 10
for i in range(v, -1, -1): # runtime error: invalid type in gdscript utility function '<unknown function>'. cannot convert argument 2 from nil to float
	print(i)
```

it yields a runtime error.

![image](https://user-images.githubusercontent.com/5783414/221054989-4b438c29-a8fc-40ae-806f-ec46c76c7f57.png)

![image](https://user-images.githubusercontent.com/5783414/221054619-1cbc25b9-1353-4e0f-b88f-2b727db00473.png)

### Steps to reproduce

Copy and paste the code bellow on an empty script on an empty scene and run it
```gdscript
func _ready() -> void:
	var v = 10
	var r = range(v, -1, -1) # works fine
	for i in range(10, -1, -1): # works fine
		print(i)
	for i in range(v, -1, -1): # runtime error: invalid type in gdscript utility function '<unknown function>'. cannot convert argument 2 from nil to float
		print(i)
```

### Minimal reproduction project

[RangeProblem.zip](https://github.com/godotengine/godot/files/10819340/RangeProblem.zip)

**Comment by akien-mga** [comment] 2023-02-23 23:36
Thanks for the report! Duplicate of #73837

**Closed by akien-mga** 2023-02-23 23:36 UTC
