### ISSUE TITLE
Godot freeze entire OS for a while when using a lot of objects/functions

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#46831] opened 2021-03-09 15:49 UTC
**Godot version:**
4.0.dev.custom_build. 83b1acdc6

**OS/device including version:**
Ubuntu 20.04 Gnome Shell 3.36 X11
GTX 970 Nvidia 460

**Issue description:**
When I run scene which contains a lot of objects and functions, then OS freeze randomly for 1, 4 or even 10 seconds.

This don't happens with very similar code in Godot 3.2, so I suspect that this is caused by invalid handling of Vulkan(not exactly sure if this is Godot or Nvidia drivers issue)

**Steps to reproduce:**
1. Run project and wait

**Minimal reproduction project:**
[GDScript.zip](https://github.com/godotengine/godot/files/6109699/GDScript.zip)

**Comment by qarmin** [comment] 2021-05-02 10:20
I can't reproduce such freeze even on Intel HD 3000 and mesa 21.1.0, so this seems to be Nvidia only issue

**Comment by clayjohn** [comment] 2023-02-22 22:56
Can you still reproduce this freeze? A lot has changed so it wouldn't be surprising if it has been fixed in the meantime

**Comment by AThousandShips** [comment] 2024-07-29 17:35
Closing due to lack of response, if you can still reproduce this this can be reopened

**Closed by AThousandShips** 2024-07-29 17:35 UTC
Labels: bug, topic:rendering, needs testing, regression
