### ISSUE TITLE
Redundant line in Script Editor when Highlight Tabs is enabled

### ISSUE THREAD

**Issue by YeldhamDev** [godotengine/godot#10410] opened 2017-08-17 23:23 UTC
**Ubuntu 17.04 - Godot version: Since 3.0.alpha1**

**Issue description:**
It may be an intentional design choice, but this line in the very top of the Script Editor seems really off place:

![screenshot at 2017-08-17 20-19-55](https://user-images.githubusercontent.com/30739239/29437883-be7be472-8389-11e7-95aa-d90997b313c9.png)

**Comment by Zylann** [comment] 2017-08-17 23:52
I don't see this line in 3.0 alpha1.
It's not there either in 9575dbdf788e8a5154b3ec2f66913e731ac02850.

**Comment by YeldhamDev** [comment] 2017-08-17 23:54
Strange, maybe it's some configuration that triggers it?

**Comment by Zylann** [comment] 2017-08-17 23:56
No, I give versions where it doesn't show to narrow down the origin. Hang on

**Comment by YeldhamDev** [comment] 2017-08-17 23:56
Found it, it's the tab highlighting.

**Comment by Zylann** [comment] 2017-08-17 23:58
I think it might be @toger5 's changes on theming a8a6082dc07e8a00c8a546abf121d82599b1c39a but I'm not sure

**Comment by Zylann** [comment] 2017-08-18 00:14
What is highlight tabs doing beyond making them brighter?
Also the margin is also not visible with that setting on in alpha1.

**Comment by YeldhamDev** [comment] 2017-08-18 00:17
I think it basically that, it just makes them brighter.

**Comment by toger5** [comment] 2017-08-18 15:58
Thank you for pinging me.

**In short:**
Highlight tabs are deprecated when the white theme support is merged.
The line margin issue is caused by the stylebox pr.
(added the short section because i went into too much detail... But maybe its interesting for someone...)

**in detail**
 - highlight tabs did just make tabs brighter + a thin area underneath the tabs. I decided with djrm that they are not necassary and they result in a lot of additional and redundant code with the white theme feature (another pr) so they will be removed in that pr. (too little gain for the amount of code it uses) maybe it can be implemented later on in a better way.
 - the line is probably introduced by the theme changes. In the old styleboxflat there was an option for additional border. This border was drawn OUTSIDE of the control rect. I implemented expand margin. Expand margin in addition with border width results in the same thing. So i removed it. And replaced all occurances of additional border size with border_width + expand_margin. In the case of the tabs highlighting, I probably forgot the expand_margin.

**Comment by YeldhamDev** [comment] 2017-08-18 16:02
Sad to see them go, but if it is for the sake of cleaner code, I will just deal with it.

**Comment by toger5** [comment] 2017-08-18 16:12
@YeldhamDev
You are the first one heard of that he is needing the feature (havent talked to too many ppl yet, but still ;) )
So knowing you are interested i might add them again. Might look a little different, but i have an idea how i can do it with only 2 additional lines...

**Comment by djrm** [comment] 2017-08-19 01:24
@toger5 actually they dont need to go, please when you check my svg PR give it a check, i made them available without logic duplication

**Comment by toger5** [comment] 2017-08-19 12:12
@djrm just saw how you did it. and you are right. that is a pretty simple implementation.
So @YeldhamDev they won't go and I will try to fix the border now so you can close it.

**Comment by toger5** [comment] 2017-08-19 13:40
@YeldhamDev oh I meant closing when I fixed and my fix got merged. Don't have rights to open again. would u?

**Comment by YeldhamDev** [comment] 2017-08-19 14:13
@toger5 Oh crap, sorry!

**Closed** 2017-08-19 16:04 UTC
Labels: bug, topic:editor
