### ISSUE TITLE
Editor Popups with single-window mode lose focus too quickly

### ISSUE THREAD

**Issue by Yagich** [godotengine/godot#72189] opened 2023-01-27 18:12 UTC
### Godot version

4.0b16

### System information

Linux/Manjaro KDE Plasma/X11

### Issue description

There are two (and a half) separate, but I suspect related issues at hand. They only happen when the EditorSettings property `interface/editor/single_window_mode` is enabled.

1. While in the Script Editor, any of the top MenuBar popups disappear right after the button is clicked. This does not happen if the 2D or 3D views are active;
   1. Additionally, right-clicking a property in the EditorSettings dialog exhibits this behavior regardless of the currently active viewport. Interestingly, this does not happen in the ProjectSettings dialog.
1. Double-clicking a node in the scene tree to rename it too quickly will lose focus. If the double-click speed is not fast enough to lose focus, clicking on the selected text input field will make it lose focus. This does not happen when renaming a node with the F2 shortcut.

(Sorry, can't record the issue at the moment, OBS broke with the latest system update 🙁)

### Steps to reproduce

Enable single-window mode in the Editor Settings.
To reproduce the issues in order:
1. With the Script Editor active, try to activate any of the menu bar items (the renderer dropdown also has this issue);
1. In the EditorSettings dialog, try right-clicking any property;
1. Try double-clicking a node in the scene tree to rename it.

### Minimal reproduction project

N/A

**Comment by daviirodrig** [comment] 2023-01-28 06:01
I can reproduce this issue as well. Arch Linux and KDE Plasma

One thing I noticed is that it occurs whenever you have focused a TextEdit, including the Script Editor
In the example below after I focus on "Up direction" the issue appears.

https://user-images.githubusercontent.com/30713947/215248930-5eac4f50-e66a-4ffd-98f9-87cb9eae14d0.mp4

**Comment by Sauermann** [comment] 2023-01-30 19:19
I can replicate this with v4.0.beta.custom_build [17a859735] on Debian X11 Xfce.

**Comment by bruvzg** [comment] 2023-02-15 07:11
I can't reproduce it on the current master. Should be fixed by [the IME focus changes](https://github.com/godotengine/godot/pull/72785).

**Closed** 2023-02-15 07:32 UTC
Labels: bug, platform:linuxbsd, topic:editor, topic:input, regression
