### ISSUE TITLE
Editor crash when opening scene file

### ISSUE THREAD

**Issue by cbscribe** [godotengine/godot#12761] opened 2017-11-09 02:14 UTC
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
MacOS 10.12.6, Godot 3.0 5fb359d

**Issue description:**
Downloading the tutorial game, the editor crashes when opening the Player scene. Crash log attached. Problem does not occur with Alpha 2, but does using a more recent build.

**Steps to reproduce:**
Open the project, and try to open the Player scene. Editor crashes with attached log. Other scenes load fine.
[trace.txt](https://github.com/godotengine/godot/files/1456075/trace.txt)

**Link to minimal example project:**
https://github.com/kidscancode/Godot3_dodge

**Comment by cbscribe** [comment] 2017-11-09 02:23
Possibly a duplicate of #12760

**Comment by cbscribe** [comment] 2017-11-09 02:28
@karroffel : Your patch from https://github.com/godotengine/godot/issues/12715#issuecomment-342542006 seems to fix this.

**Comment by akien-mga** [comment] 2017-11-09 10:01
Duplicate of #12715.

**Closed by akien-mga** 2017-11-09 10:01 UTC
