### ISSUE TITLE
Scanlines/fickering tilemap on NVIDIA laptop (Moiré patterns due to mipmap aliasing)

### ISSUE THREAD

**Issue by Xarcaneo** [godotengine/godot#55241] opened 2021-11-22 22:27 UTC
### Godot version

Godot_v3.3.3-stable_win64

### System information

Windows 10, GLES 3, INTEL(R) Core i7-7820HK CPU @ 2.90Ghz 8CPUs

### Issue description

So I will appreciate any help because that project is important to me. I am making a game with 2D tilemaps but I have some problems with graphic glitches, I recorded video for you:
[Glitch example 1](https://www.youtube.com/watch?v=6DfKBHQnaRE)
And also moved my tilemap to another project and there is the same problem, even in editor:
[Glitch example 2](https://www.youtube.com/watch?v=k_nOMcGazQ0)

Pixel snap is on, filtering off, camera process mode set to physic, vsync on, I tried to switch from GLES3 to 2 but there is the same problem, I turned Nvidia rect ficker workaround but it doesnt help. I have no idea how to fix that. I tried GODOT 3.3.3 and 3.4

### Steps to reproduce

Put the tilemap and  player with camera then run the game and enjoy flicker.

**Comment by clayjohn** [comment] 2021-11-22 22:39
Do the textures have mipmapping enabled? In the video, the artifacts look like mipmap artifacts from using mipmaps on a texture atlas.

**Comment by Xarcaneo** [comment] 2021-11-22 23:12
No, Ill show you settings for all my textures in project:
![Bez tytułu](https://user-images.githubusercontent.com/5487881/142948764-a6254194-32b7-4bab-b4db-910d2abdfcb4.png)

**Comment by lawnjelly** [comment] 2021-11-23 06:23
Not absolutely sure, but it could just be aliasing? (especially if filtering is off)
https://en.wikipedia.org/wiki/Aliasing

This will occur when the source texels do not match up to a regular number of pixels on screen, especially when filtering is off, and is especially noticeable in some textures.

**Comment by Xarcaneo** [comment] 2021-11-23 17:05
So what should I try to do?

**Comment by Calinou** [comment] 2021-11-23 17:28
You most likely need to enable Mipmaps to avoid Moiré effects when the texture is not displayed at a 1:1 scale.

**Comment by Xarcaneo** [comment] 2021-11-23 17:41
Moiré patterns still visible with mipmaps enabled, I have to try to open project in another laptop and check if there is also this problem. Do you have any other suggestions?

**Comment by Calinou** [comment] 2021-11-23 17:53
@Xarcaneo Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

**Comment by Xarcaneo** [comment] 2021-11-23 18:22
[reproduction.zip](https://github.com/godotengine/godot/files/7590270/reproduction.zip)
Simple reproduction. Slower character movement == more visible effect. Effect only visible with camera on.

**Comment by lawnjelly** [comment] 2021-11-24 06:32
Yes it looks like aliasing between the viewport size (lower resolution rendered surface), and stretching it to fit on a fractionally scaled window. If you set the test window size to e.g. 960x640 (i.e. double the original) you don't get the problem, or presumably with other multiples 1:1, 2:1, 3:1 etc.

**Comment by Xarcaneo** [comment] 2021-11-24 12:37
That's right, there is no Moiré patterns when I set that test windows size, but how to make a project then to fits every screen resolution on every screen without that Moiré patterns ano no black bars on the sides?

**Comment by Calinou** [comment] 2021-11-24 19:39
For the record, this issue was cross-posted on the Godot forums: https://godotforums.org/discussion/28093/weird-graphic-behavior-in-pixelart-platformer

**Comment by Xarcaneo** [comment] 2021-11-25 17:17
Solution:
So I didn't give up and tried to figure it out what is going on so simply you was right, there is scaling on but no in the editor. I use Win10 that has scaling on by default in display settings 125%. When I changed it to 100 Moiré patterns disappeared. I wasn't satisfied by this solution because we can't force players to change scale of display when they play specific games so I found a setting Allow Hidpi and enabled it, now it work good even on scaled display. I also changed viewport to 640x360 and it also helped a lot coz can be easly multiplied to 1920x1080. For now I have only problem with flicker while camera is moving, it is not noticeable on video when I tried to record that and also tiles get blurry, if you guys gave any solution for that Ill appreciate.

**Comment by Calinou** [comment] 2021-11-25 18:18
Closing per the above comment. [Enabling **Allow Hidpi** by default was rejected in the past](https://github.com/godotengine/godot/pull/29553), but it may be considered again now that [built-in 3D resolution scaling](https://github.com/godotengine/godot/pull/51870) is available.

**Closed by Calinou** 2021-11-25 18:18 UTC
Labels: discussion, topic:rendering, needs testing, topic:2d
