### ISSUE TITLE
Viewport with transparent_bg is blending partial alpha values with black

### ISSUE THREAD

**Issue by Giwayume** [godotengine/godot#69870] opened 2022-12-10 21:27 UTC
### Godot version

3.5.stable

### System information

Windows 7 64 Bit GLES3 RTX 3080

### Issue description

Partial alpha values in viewports are inaccurately blended on top of wherever the viewport is drawn to. Anything that is partially transparent appears to be pre-multiplied by a black transparent color.

![image](https://user-images.githubusercontent.com/4075314/206875797-f5987358-c3f3-41b4-80db-6c8c2ad74ffb.png)

### Steps to reproduce

Set up a 2D viewport with transparent_bg setting enabled, draw anything to the viewport that has partial transparency. Draw the viewport on top of something else, such as a white background, that shows the inaccurate semi-transparent color.

### Minimal reproduction project

[SemiTransparentViewport.zip](https://github.com/godotengine/godot/files/10200995/SemiTransparentViewport.zip)

**Comment by kleonc** [comment] 2022-12-10 22:40
Duplicate of #32615.

That's expected behavior, see the linked issue for how to make it blend as you expect it to.

**Closed by kleonc** 2022-12-10 22:40 UTC
Labels: topic:rendering, topic:2d
