### ISSUE TITLE
Input "light" in light shader show blocky color when combined with diffuse.

### ISSUE THREAD

**Issue by warcanin** [godotengine/godot#76193] opened 2023-04-18 03:36 UTC
### Godot version

4.0.2

### System information

Windows 10, amd rx 5700xt, ryzen 3700x

### Issue description

![image](https://user-images.githubusercontent.com/57159438/232664075-142fea8d-cd74-4bc4-af3d-aebac15129fa.png)
![image](https://user-images.githubusercontent.com/57159438/232664140-210f0af4-8af8-42f0-b475-f7908a59bbcb.png)
![image](https://user-images.githubusercontent.com/57159438/232664165-a08d26ad-58c5-4380-a671-6d7c1b7f5e26.png)
The shader consist only of a light input added to a diffuse set on the light shader, i don't know how to express it correctly but on the falloff of the light the cutoff is blocky.

### Steps to reproduce

-Create meshinstance
-Add any mesh
-Add a light
-Create a visual shader go to light shader
-Add a light and diffuse input and add them together and then put the result in the diffuse output.

### Minimal reproduction project

N/A

**Comment by clayjohn** [comment] 2023-04-18 05:52
This is a duplicate of https://github.com/godotengine/godot/issues/73176

This isn't a bug with the engine, it is a bug with your shader. You are forgetting to include attenuation. So what you are seeing is the edges of the light cluster. The cluster is determined by your light's range. 

You can fix the issue either by increasing the light range to cover all the meshes you want it to shade, or by properly multiplying your light value by attenuation. 

https://github.com/godotengine/godot/issues/73176 also includes some more detailed discussion that you might find helpful

**Closed by clayjohn** 2023-04-18 05:52 UTC
