### ISSUE TITLE
GDScript 2.0: Setget variable does not enter the set block when a value is assigned in the declaration.

### ISSUE THREAD

**Issue by AttackButton** [godotengine/godot#54595] opened 2021-11-04 13:42 UTC
### Godot version

v4.0.dev.calinou.795cd2eb3

### System information

Windows 10

### Issue description

A variable that uses setget and that assign a value already in it's declaration does not enter in the set block.

In the MRP, the `test variable` is only to get it's value from inside the set block and not from the assignment from outside. 

### Steps to reproduce

Create a setget variable and assign a value right in it's declaration. Note that it will get the value from the assignment without entering in the set block.

### Minimal reproduction project

[setget_test_godot_4.zip](https://github.com/godotengine/godot/files/7475156/setget_test_godot_4.zip)

**Comment by KoBeWi** [comment] 2021-11-04 15:59
This is intended. Setters aren't called for default values. Not assigning value is the same as assigning 0.

**Comment by AttackButton** [comment] 2021-11-04 20:15
> 
> 
> This is intended. Setters aren't called for default values. Not assigning value is the same as assigning 0.

Interesting. The behavior changed from Godot 3.x. So in the situation below it will still be necessary to call the _ready function even using the @onready for the test variable.

```
1)
@onready var_1: int = 200
@onready var test : int = 100:
	get:
		return test
	set(value):
		var_1 = var + value
		test = value/10
```
var_1 == 200
test == 100

```
2)
@onready var_1: int = 200
@onready var test : int = 100:
	get:
		return test
	set(value):
		var_1 = var + value
		test = value/10

func _ready():
	test = 100
```
var_1 == 300
test == 10

**Comment by vnen** [comment] 2022-06-27 15:24
Closing since this is intended behavior.

**Closed by vnen** 2022-06-27 15:24 UTC
Labels: topic:gdscript
