### ISSUE TITLE
[2.1.5] Seemingly random crash in DynamicFont::set_font_data

### ISSUE THREAD

**Issue by plucian** [godotengine/godot#21268] opened 2018-08-21 16:29 UTC
**Godot version:* 2.1.5 -stable*

**OS/device including version:* windows 10*

**Issue description:**

running a rather complex project, I started getting this random crash with no error to chase after.

CrashHandlerException: Program crashed
Dumping the backtrace. Please include this when reporting the bug on https://github.com/godotengine/godot/issues
[0] Reference::reference (c:\godot\core\reference.cpp:68)
[1] Ref<DynamicFontAtSize>::ref (c:\godot\core\reference.h:92)
[2] Ref<DynamicFontAtSize>::operator= (c:\godot\core\reference.h:172)
[3] DynamicFont::set_font_data (c:\godot\scene\resources\dynamic_font.cpp:641)
[4] MethodBind1<DynamicFont,Ref<DynamicFontData> const & __ptr64>::call (c:\godot\core\method_bind.gen.inc:730)
[5] ObjectTypeDB::set_property (c:\godot\core\object_type_db.cpp:642)
[6] Object::set (c:\godot\core\object.cpp:322)
[7] ResourceInteractiveLoaderText::poll (c:\godot\scene\resources\scene_format_text.cpp:321)
[8] ResourceFormatLoader::load (c:\godot\core\io\resource_loader.cpp:126)
[9] ResourceLoader::load (c:\godot\core\io\resource_loader.cpp:187)
[10] _ResourceLoader::load (c:\godot\core\bind\core_bind.cpp:72)
[11] MethodBind3R<_ResourceLoader,Ref<Resource>,String const & __ptr64,String const & __ptr64,bool>::call (c:\godot\core\method_bind.gen.inc:2157)
[12] Object::call (c:\godot\core\object.cpp:853)
[13] Variant::call_ptr (c:\godot\core\variant_call.cpp:991)
[14] GDFunction::call (c:\godot\modules\gdscript\gd_function.cpp:636)
[15] GDInstance::call (c:\godot\modules\gdscript\gd_script.cpp:1112)
[16] Object::call (c:\godot\core\object.cpp:832)
[17] MessageQueue::_call_function (c:\godot\core\message_queue.cpp:298)
[18] MessageQueue::flush (c:\godot\core\message_queue.cpp:345)
[19] SceneTree::input_event (c:\godot\scene\main\scene_main_loop.cpp:434)
[20] InputDefault::parse_input_event (c:\godot\main\input_default.cpp:349)
[21] OS_Windows::WndProc (c:\godot\platform\windows\os_windows.cpp:624)
[22] WndProc (c:\godot\platform\windows\os_windows.cpp:810)
[23] CallWindowProcW
[24] CallWindowProcW
[25] glDebugEntry
[26] CallWindowProcW
[27] DispatchMessageW
[28] OS_Windows::process_events (c:\godot\platform\windows\os_windows.cpp:1944)
[29] OS_Windows::run (c:\godot\platform\windows\os_windows.cpp:2450)
[30] widechar_main (c:\godot\platform\windows\godot_win.cpp:149)
[31] _main (c:\godot\platform\windows\godot_win.cpp:171)
[32] main (c:\godot\platform\windows\godot_win.cpp:183)
[33] __scrt_common_main_seh (f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:253)
[34] BaseThreadInitThunk
-- END OF BACKTRACE --
shit?: No such file or directory
ERROR: StreamPeerWinsock::read: Server disconnected!

   At: platform\windows\stream_peer_winsock.cpp:202

**Steps to reproduce:**
Not sure, when or why it shows, seems kind of random

**Minimal reproduction project:**

**Comment by VitaZheltyakov** [comment] 2018-08-23 15:31
`Server disconnected!` - this is a [popular error](https://github.com/godotengine/godot/issues?q=is%3Aissue+Server+disconnected+is%3Aopen) caused by a bad caching system. For 3 years this problem has not been corrected.

**Comment by akien-mga** [comment] 2018-08-23 16:10
> Server disconnected! - this is a popular error caused by a bad caching system. For 3 years this problem has not been corrected.

`Server disconnected!` is not a "popular" error, it's what happens anytime *an* error will cause the debugger to disconnect (usually because the game crashed).

**Comment by VitaZheltyakov** [comment] 2018-08-24 05:47
This error happens when the caching system accesses a nonexistent file. This error is critical. This it causes the crash of the application. The problem is in a bad caching system.

**Comment by ICatRegister** [comment] 2018-08-24 19:57
I had same random crash, fixed this with changing some property of dynamic font. Don't remember which one, unchecking "mipmaps" it seems

**Comment by akien-mga** [comment] 2018-09-18 11:56
This looks quite similar to #15392, which was fixed by 526e637 and 8daf5491.

I've pushed bc0af4a73 and 2c47116a as cherry-picked in the `2.1` branch, could you compile it and confirm that it fixes the issue?

**Comment by plucian** [comment] 2018-09-18 13:26
I cannot reproduce the issue anymore. I think you can close this. If should happen again I'll open another thread. thanks !

**Comment by akien-mga** [comment] 2018-09-18 13:34
Great, thanks :)

Closing as fixed by bc0af4a and 2c47116.

**Closed by akien-mga** 2018-09-18 13:34 UTC
Labels: bug, topic:core
