### ISSUE TITLE
Scaled RigidBody should show a node warning in the scene tree as it's something that should not be done

### ISSUE THREAD

**Issue by ghur** [godotengine/godot#7615] opened 2017-01-23 12:39 UTC
*Bugsquad edit:* Repurposed the original issue to handle the suggestion in https://github.com/godotengine/godot/issues/7615#issuecomment-274485461

------

**Operating system or device - Godot version:**
v2.1.2

**Issue description:**
The player model  enlarges a lot of times when  I run the program than in the edit mode,anyone knows how to solve it?
I have uploaded the screencasts which reflect the problem here:
In the edit mode:
![cast](https://cloud.githubusercontent.com/assets/25295784/22201272/d97d55dc-e19d-11e6-9a3b-aa2b1dae116c.gif)
When I run the program:
![cast1](https://cloud.githubusercontent.com/assets/25295784/22201511/e67da09c-e19e-11e6-8e0c-f122fe68a540.gif)

And the tscn file here(Level1.tscn/Spatial/Player_1 in the zip file):
[question_asked.zip](https://github.com/godotengine/godot/files/723497/question_asked.zip)

**Steps to reproduce:**
just create a new project,unzip the file and open Level1.tscn

**Link to minimal example project:**
:
[question_asked.zip](https://github.com/godotengine/godot/files/723497/question_asked.zip)

**Comment by reduz** [comment] 2017-01-23 12:58
likely you scaled a rigidbody instead of the mesh. rigidbodies can't be
scaled

**Comment by ghur** [comment] 2017-01-23 13:15
@reduz Solved,thanks.

**Comment by reduz** [comment] 2017-01-23 13:17
we should add one of those node warnings when the rigid body is scaled

**Comment by akien-mga** [comment] 2017-01-23 13:34
Kind of duplicate of #5734, but repurpose this issue for adding warnings for scaled RigidBody's (while the other one is about making it possible to actually scale them).

**Comment by eon-s** [comment] 2017-01-23 14:38
What about disabling rigid body scaling in the inspector? 
And lock the scene editor resize tool, like is done with the pivot tool on 2D.

`set_scale` could show a warning on the console too for a complete "can't do this" thing.

**Comment by bojidar-bg** [comment] 2017-01-23 15:00
@eon-s What if you scale the parent of the rigidbody? The lock-down would get way too expensive if we have to check all children.

**Comment by eon-s** [comment] 2017-01-23 17:19
@bojidar-bg that affects even the the simple warning, but the rigid itself should have the option locked, like the pivot as I mentioned.

**Comment by avencherus** [comment] 2017-01-24 01:27
Heya.  Felt compelled to add my novice experience to this discussion.

When I first bumped into this, took me a while to figure it out.  It wasn't intuitive or consistent with the rest of the Godot node design.  Since RigidBody extend other nodes, they imply that it will accept  transformations in the same hierarchical manner as everything else.

I understand now that it's not sensible for the physics body to scale, but it would be nice if the transforms were at least coherently forwarded to the collision shapes and child nodes.  IE - Scaling up the meshes, sprites, collision shapes, etc.  There would be some value in having games objects that are made from physics bodies that could grow and shrink using the existing node semantics.

As it is currently, it seems to be scaling the child nodes in editor, and then you're in for surprises when you run it.  They certainly have an awkwardness because of their unclear exceptions.

**Comment by reduz** [comment] 2017-01-24 01:55
yes, to avoid this problem, a warning sign will appear in the RigidBody to
let you know it will not work the moment you scale it.

**Comment by nounoursheureux** [comment] 2017-01-24 06:13
@reduz should RigidBody2D also display a warning ?

**Comment by reduz** [comment] 2017-01-24 09:17
yeah, I guess so

**Comment by akien-mga** [comment] 2017-01-24 09:19
I think all types of CollisionShapes should also issue such a warning when resized.

**Comment by reduz** [comment] 2017-01-24 09:20
CollisionShapes are fine to be resized, I think the problem is some of them
(sphere or capsule) do not work well if the scale is non uniform

**Comment by akien-mga** [comment] 2017-01-24 09:24
Hm, in my experience scaling a CollisionShape (even uniformly) would cause weird issues in the physics engine. I've always seen people advising not to scale them, but to instead change their size properties.

**Comment by akien-mga** [comment] 2017-01-26 13:59
I reopened this issue, please don't close it.

**Comment by DjPale** [comment] 2017-04-28 10:27
Is the common agreement here that we need an Editor Warning on all the _collider_ objects if the scale != (1, 1)? Or is it at the RigidBody-level?

Is this being worked on BTW?

**Comment by reduz** [comment] 2017-08-05 18:36
collider objects should work, the problem is the body itself

**Closed** 2017-08-05 19:07 UTC
Labels: enhancement, junior job, topic:editor, usability
