### ISSUE TITLE
When renaming a node, Microsoft Pinyin input method cannot be switched to Chinese

### ISSUE THREAD

**Issue by a690089735** [godotengine/godot#77837] opened 2023-06-04 14:42 UTC
### Godot version

v4.0.3.stable.official [5222a99f5]

### System information

windows 10 v4.0.3.stable.official [5222a99f5] - Compatibility

### Issue description

When renaming a node, Microsoft Pinyin input method cannot be switched to Chinese.
But nodes can actually be named in Chinese. We can only do this by copying strings from Notepad and pasting them into the renamed text box.
(It's worth noting that I used Shift to switch between Microsoft Pinyin and English.)

### Steps to reproduce

Rename a node

### Minimal reproduction project

none

**Comment by AThousandShips** [comment] 2023-06-04 14:45
* Related? #77809

**Comment by a690089735** [comment] 2023-06-04 14:53
> * Related? [About the Chinese adaptation problem #77809](https://github.com/godotengine/godot/issues/77809)

It's related, but it's not the same. The problem #77809 is more on the garble(which is displayed differently in the engine than in the browser) only mentions this problem mentioned in passing

**Comment by saierXP** [comment] 2023-06-04 16:01
Duplicate of #60372
Duplicate of #73591

**Closed** 2023-06-09 09:09 UTC
Labels: bug, platform:windows, topic:porting, topic:input
