### ISSUE TITLE
[4.0]-Full Screen HTML5 On PC Windows/Linux Desktop Internet Browsers Is Very Slow?

### ISSUE THREAD

**Issue by ghost** [godotengine/godot#74034] opened 2023-02-27 09:09 UTC
### Godot version

v4.0.rc5.official [6296b4600]

### System information

[4.0 RC5 Win 11] - Full Screen HTML5 On PC Windows/Linux Desktop Internet Browsers

### Issue description

Hi,

Run below HTML5 build in your desktop Internet browser:
https://betamaxheroes.org/games/TS3-Godot_4/builds/RC0/WebVer/index.html

It's slower than a Microsoft Powerpoint slideshow.
Full screen HTML5/WebGL should not be this slow.
It is time to optimize the HTML5/WebGL graphic backend.

We have gone as far as possible with optimizations, we need you to step up now.
Need twice the performance then what 4.0 RC 5 is capable of.

Jesse

### Steps to reproduce

`# "TetriStory 110%" - Release Candidate ZERO+1`

https://betamaxheroes.org/games/TS3-Godot_4/builds/RC0/WebVer/index.html

### Minimal reproduction project

`# TS3 - 100% M.I.T. Open-Source`

https://github.com/BetaMaxHero/GDScript_Godot_4_T-Story

**Comment by michaldev** [comment] 2023-02-27 11:30
I confirm. I have created a game on Godot 4. Unfortunately, I am unable to release it. It is a multiplayer game where obtaining as many players as possible is crucial. The easiest way to get random players is through the browser version + native versions available on Android/iOS/Windows as an additional option. Currently, the browser version of the game completely hangs the browser (Chrome/Firefox) on macOS, and does not launch at all on iOS. It works on browsers on Windows and Linux, but very unstably.

**Comment by Zireael07** [comment] 2023-02-27 11:53
@michaldev if your issue is on MacOS only, you're running into a different, already reported issue specific to MacOS

**Comment by Calinou** [comment] 2023-02-27 16:52
@michaldev This is already being tracked in https://github.com/godotengine/godot/issues/72584.

**Comment by NanitesNanites** [comment] 2023-02-28 00:04
> Run below HTML5 build in your desktop Internet browser: https://betamaxheroes.org/games/TS3-Godot_4/builds/RC0/WebVer/index.html
> 
> It's slower than a Microsoft Powerpoint slideshow.

Ryzen3 3800X, GTX 1080ti, Windows 10, Firefox 110

Runs perfectly fine in terms of performance, no slideshow.

**Comment by Calinou** [comment] 2023-05-05 14:11
Closing, as OP removed their account and the issue is not actionable.

**Closed by Calinou** 2023-05-05 14:11 UTC
Labels: platform:web, needs testing, performance
