### ISSUE TITLE
Low frequency samples make high pitch noise

### ISSUE THREAD

**Issue by Yazir** [godotengine/godot#24348] opened 2018-12-14 14:33 UTC
**Godot version:**
Godot 3.1 Alpha3

**OS/device including version:**
Windows 10 Pro

**Issue description:**
After playing a specific sample through AudioStreamPlayer2D, the sound has a ringing noise after it plays.

**Steps to reproduce:**

A:
[spas12.zip](https://github.com/godotengine/godot/files/2680397/spas12.zip)
1. Get audio file above
2. Create a new empty project, add Node2D and AudioStreamPlayer2D as a child
3. Load the downloaded sound in the StreamPlayer

B:
[Sound tests.zip](https://github.com/godotengine/godot/files/2680393/Sound.tests.zip)
1. Download this project and open it.

After A or B turn on Playing in AudioStreamPlayer2D's inspector

**Media showing the issue:**
Raw audio:
https://streamable.com/2aydm

In godot:
https://streamable.com/vwvef
https://streamable.com/9v2d3

**Comment by Zylann** [comment] 2018-12-14 17:59
Same as https://github.com/godotengine/godot/issues/23544 ?

**Comment by Yazir** [comment] 2018-12-14 19:05
It seems similar.
When I downloaded the project and played the sound, the artifact was the same as on your recording.

**Comment by Yazir** [comment] 2018-12-14 19:15
I changed the mix rate in project settings -> audio to 48000 and artifacts seem to be gone. But there's other problem occuring which makes sounds start with a little crack noise (which happens when audio starts or ends on float or something like that).
There's also a crack when stopping / starting the sample.
https://streamable.com/430zl
Notice that I'm not using AudioStreamPlayer2D so it isn't the cause there.

**Comment by Zylann** [comment] 2018-12-14 19:35
![image](https://user-images.githubusercontent.com/1311555/50023425-0e6ee400-ffd7-11e8-8465-1fef9d2899e9.png)
That waveform looks suspicious...

I opened your file in Audacity:
![image](https://user-images.githubusercontent.com/1311555/50023469-2fcfd000-ffd7-11e8-88cb-9a5889a1fd7f.png)
I applied a 100Hz high pass and a very short fade-in to start at zero amplitude:
![image](https://user-images.githubusercontent.com/1311555/50023484-4118dc80-ffd7-11e8-9563-5084a6173a37.png)

Here is the new file:
[spas12_fixed.zip](https://github.com/godotengine/godot/files/2681494/spas12_fixed.zip)
Does it still have the same issue?

**Comment by Yazir** [comment] 2018-12-14 21:19
The fixed version works fine, also on default mix rate.

**Comment by Yazir** [comment] 2018-12-14 21:20
https://drive.google.com/uc?id=13VVhH_MawxkbBHb7O7Y5WD0UoRqJV4Av
Here is how it looks now.

**Comment by Calinou** [comment] 2020-05-27 07:16
Duplicate of #23544. Please open a separate issue about the audio preview after searching for possible duplicates if you can still reproduce it in Godot 3.2.1.

**Closed by Calinou** 2020-05-27 07:16 UTC
Labels: bug, topic:audio
