### ISSUE TITLE
The modified state of a script isn't changing

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#19533] opened 2018-06-12 21:28 UTC
Godot 3.0.2
Windows 10 64 bits

I'm not sure how it happened, but now if I save a script in the script editor, its modified state (asterisk *) doesn't go away.
It also doesn't appear anymore if I modify the file...
...
and as I tried to record a video showing it, the bug went away Oo
But it's there... happening at random.

Here is the video, you can see a part of the bug, and then me being surprised when the rest of it didn't reproduce:
https://www.youtube.com/watch?v=aYUqOplTpRk&feature=youtu.be

I'm noticing again a few minutes later... still no idea what triggers it

**Comment by akien-mga** [comment] 2019-01-22 11:42
Is this still reproducible in the current master branch?

**Comment by Zylann** [comment] 2019-01-22 20:43
I'm not sure how to reproduce the "not disappearing asterisk", I can't see it happen with a simple test project. However, I still notice that the `*` always takes a little while to appear.

**Comment by Anutrix** [comment] 2019-07-06 19:57
Could external changes trigger it?

**Comment by KoBeWi** [comment] 2019-12-30 19:01
It happens because names refresh when editor refresh (i.e. at the moment when code is parsed and errors appear etc. after user being idle). It's probably intended, but maybe could be improved. Also I just noticed that built-in scripts don't get the `(*)` suffix at all.

**Comment by KoBeWi** [comment] 2020-12-09 21:02
Still valid in d8825fb

**Comment by KoBeWi** [comment] 2021-12-13 11:35
There is still some delay, but it's not really a problem. The built-in script issue was resolved. Closing.

**Closed by KoBeWi** 2021-12-13 11:35 UTC
Labels: bug, topic:editor, confirmed
