### ISSUE TITLE
Cannot make smooth points on Curve3D in Godot 4

### ISSUE THREAD

**Issue by superlou** [godotengine/godot#56052] opened 2021-12-18 14:55 UTC
### Godot version

v4.0.dev.20211210.official [21b81998b]

### System information

Linux Mint 19.2

### Issue description

I can create a Path3D nodes and add a Curve3D to it and add sharp points. However, unlike in Godot 3, ctrl+dragging a point to create a smooth point (and move the control handles) does not work. Instead, the point appears to drag with a snap or quantization. Other modifier keys like `shift`, `alt`, and `ctrl+shift` don't seem to behave any differently. Points can be deleted as expected.

### Steps to reproduce

1. Create a new Godot 4 project.
2. Add a Path3D node
3. Add a Curve3D to the Path3D
4. Add points
5. Drag a point while holding `ctrl`

The point "snap" drags and control handles for a smooth point do not appear.

**Comment by Calinou** [comment] 2021-12-18 15:10
The Ctrl key press *is* read in the Path3D editor plugin: https://github.com/godotengine/godot/blob/8485d0c53a55ee0295187a3144b390f35787b57d/editor/plugins/path_3d_editor_plugin.cpp#L319

However, I guess this broke in the [editor subgizmos refactor](https://github.com/godotengine/godot/pull/50748) or something similar. cc @JFonS

**Comment by JFonS** [comment] 2022-01-24 11:01
Closing as fixed by #56692. Feel free to re-open if the issue is still valid in master.

**Closed by JFonS** 2022-01-24 11:01 UTC
Labels: bug, topic:editor, regression, topic:3d

**Comment by 32kda** [comment] 2024-03-15 01:40
Also seeing the same issue on v.4.2.1

**Comment by romifauzi** [comment] 2024-04-01 22:11
I can confirm this issue still exists in 4.2.1 stable, like @32kda said, it works in Perspective view, but doesn't work in Orthogonal view (Top view in my case).

**Comment by superlou** [comment] 2024-04-01 23:22
Same behavior on Linux Mint with 4.2.1 stable.

**Comment by Calinou** [comment] 2024-04-02 01:25
Please continue the discussion in https://github.com/godotengine/godot/issues/89138.
