### ISSUE TITLE
DirectionalLight3D specular intensity missing

### ISSUE THREAD

**Issue by SmartySmart702** [godotengine/godot#70778] opened 2022-12-31 17:58 UTC
### Godot version

Godot 4.0 Beta 10

### System information

Win 10, GTX 1070, forward_plus

### Issue description

Not sure if this is just no implemented yet or intended or a bug but specular intensity is missing for DirectionalLight3D.

### Steps to reproduce

See DirectionalLight3D settings.

### Minimal reproduction project

N/A

**Comment by Calinou** [comment] 2022-12-31 18:02
Duplicate of https://github.com/godotengine/godot/issues/54244.

**Closed by Calinou** 2022-12-31 18:02 UTC
