### ISSUE TITLE
C# extension is giving me "Some projects have trouble loading. Please review the output for more details."

### ISSUE THREAD

**Issue by MuktadaCreations** [godotengine/godot#35051] opened 2020-01-12 18:09 UTC
I'am having a very hard headec from this it give's me this log
I have the the C# extantion installed but every dam time I try to open a project this happens and yeahI run the latest VScode I really need help ;-;

Starting OmniSharp server at 1/12/2020, 9:05:47 PM
    Target: c:\Users\MuktadaCreations\Documents\[GODOT PROJECTS]\Bruh\TEST.sln

OmniSharp server started
    Path: C:\Users\MuktadaCreations\.vscode\extensions\ms-vscode.csharp-1.15.2\.omnisharp\1.30.1\OmniSharp.exe
    PID: 10052

[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on Windows 6.2.9200.0 (x64)
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 2 MSBuild instance(s)
            1: Visual Studio Professional 2019 16.3.29509.3 - "C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\15.0\Bin"
            2: StandAlone 15.0 - "C:\Users\MuktadaCreations\.vscode\extensions\ms-vscode.csharp-1.15.2\.omnisharp\1.30.1\msbuild\15.0\Bin"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: Visual Studio Professional 2019 16.3.29509.3 - "C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\15.0\Bin"
[info]: OmniSharp.Cake.CakeProjectSystem
        Detecting Cake files in 'c:\Users\MuktadaCreations\Documents\[GODOT PROJECTS]\Bruh'.
[info]: OmniSharp.Cake.CakeProjectSystem
        Could not find any Cake files
[info]: OmniSharp.DotNet.DotNetProjectSystem
        Initializing in c:\Users\MuktadaCreations\Documents\[GODOT PROJECTS]\Bruh
[info]: OmniSharp.DotNet.DotNetProjectSystem
        Auto package restore: False
[info]: OmniSharp.DotNet.DotNetProjectSystem
        Update workspace context
[info]: OmniSharp.DotNet.DotNetProjectSystem
        Resolving projects references
[info]: OmniSharp.MSBuild.ProjectSystem
        Detecting projects in 'c:\Users\MuktadaCreations\Documents\[GODOT PROJECTS]\Bruh\TEST.sln'.
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'c:\Users\MuktadaCreations\Documents\[GODOT PROJECTS]\Bruh\TEST.csproj'
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in 'c:\Users\MuktadaCreations\Documents\[GODOT PROJECTS]\Bruh'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Could not find any CSX files
[info]: OmniSharp.Stdio.Host
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpWorkspaceOptionsProvider
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: c:\Users\MuktadaCreations\Documents\[GODOT PROJECTS]\Bruh\TEST.csproj
[warn]: OmniSharp.MSBuild.ProjectManager
        Failed to load project file 'c:\Users\MuktadaCreations\Documents\[GODOT PROJECTS]\Bruh\TEST.csproj'.
c:\Users\MuktadaCreations\Documents\[GODOT PROJECTS]\Bruh\TEST.csproj(1,1)
System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Build, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
File name: 'Microsoft.Build, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at OmniSharp.MSBuild.ProjectFile.ProjectFileInfo.Load(String filePath, ProjectLoader loader)
   at OmniSharp.MSBuild.ProjectManager.LoadOrReloadProject(String projectFilePath, Func`1 loadFunc)

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

[info]: OmniSharp.Stdio.Host
        Configuration finished.
[info]: OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location 'c:\Users\MuktadaCreations\Documents\[GODOT PROJECTS]\Bruh' on host 2276.

**Comment by neikeq** [comment] 2020-01-12 20:16
What version of Godot is this?

**Comment by neikeq** [comment] 2020-01-13 13:04
Can you upload the `sln` and `csproj` files?

**Comment by MuktadaCreations** [comment] 2020-01-13 14:44
@neikeq  I dont think the version matter bec I use it on unity and did the same thing, and thats probibly the C# extansion, but anyway I use the latest mono version like 3.1.2 and this is the 


1- csproj
https://mega.nz/#!8nZhFIrR!hupe8J2bCGYHZncyZuVQuJPJZTOO66aChuHZ1U8HrYw

2-sin
https://mega.nz/#!8nZhFIrR!hupe8J2bCGYHZncyZuVQuJPJZTOO66aChuHZ1U8HrYw

**Comment by neikeq** [comment] 2020-01-13 21:00
You seem to have pasted the wrong link for the `sln` by mistake :stuck_out_tongue:

**Comment by MuktadaCreations** [comment] 2020-01-14 06:45
@neikeq sorry my dude there is the right one 

https://mega.nz/#!U2ZnFYYS!VaOQJtdIjuCTuXZDuflPz00CgVszZQlI1FGojSO7d7g

**Comment by neikeq** [comment] 2020-01-14 15:13
I cannot reproduce with the 1.21.9 of the C# addon on Linux. OmniSharp version is 1.34.9. Have you tried updating the extension? I'm going to try if I can reproduce on Windows.

**Comment by MuktadaCreations** [comment] 2020-01-14 15:49
@neikeq  I tried downgrading upgrading nothing worked

**Comment by neikeq** [comment] 2020-01-14 21:39
I cannot reproduce on Windows either. Any way, I'm closing this as the error suggests this is an issue with either OmniSharp or the VSCode extension. These are similar issues I found:

https://github.com/OmniSharp/omnisharp-vscode/issues/2815
https://github.com/OmniSharp/omnisharp-vscode/issues/3228

You could try doing what this comment says: https://github.com/OmniSharp/omnisharp-vscode/issues/3228#issuecomment-521212696

**Closed by neikeq** 2020-01-14 21:39 UTC
Labels: topic:mono
