### ISSUE TITLE
Crash when running C# build in RC1

### ISSUE THREAD

**Issue by jonbonazza** [godotengine/godot#15729] opened 2018-01-15 01:13 UTC
**Godot version:**
RC1 64-bit

**OS/device including version:**
Windows 10 64-bit

**Issue description:**
I deleted my ```.mono``` folder from my project, the C# solution and assembly, and also ```AppData/Roaming/Godot/mono/solutions/*``` and launched Godot RC1 64-bit. Loaded the project and it regenerated the C# jazz. So far so good. I think click the "Run" button after it laucnhes the game window, the game window crashes and I get the following error in the console:

```
running cmdline: "C:\Users\jbonazza\Documents\Godot_v3.0-rc1_mono_win64\Godot_v3.0-rc1_mono_win64\Godot_v3.0-rc1_mono_win64.exe" "--path" "C:/Users/jbonazza/Documents/rpgproject3.0" "--remote-debug" "127.0.0.1:6007" "--allow_focus_steal_pid" "1712" "--debug-collisions" "--position" "448,240"
OpenGL ES 3.0 Renderer: GeForce GTX 750 Ti/PCIe/SSE2
GLES3: max ubo light: 409
GLES3: max ubo reflections: 455, ubo size: 144
ARVR: Registered interface: Native mobile
Mono: Initializing module...
Mono: Runtime initialized
Mono: INITIALIZED
ERROR: gdmono_MonoLogCallback: Mono: FATAL ERROR, ABORTING! Logfile: C:\Users\jbonazza\AppData\Roaming/Godot/mono/mono_logs/1515978629.txt

   At: modules\mono\mono_gd\gd_mono_log.cpp:74
Nothing read: No such file or directory
ERROR: StreamPeerTCPWinsock::read: Server disconnected!

   At: drivers\windows\stream_peer_tcp_winsock.cpp:203
```

In the referenced log file, I find the following:

```
Config attempting to parse: 'C:\Program Files\Mono\etc\mono\config'. (in domain Mono, info)
Assembly Loader probing location: 'C:\Program Files\Mono\lib\mono\4.5\mscorlib.dll'. (in domain Mono, info)
Image addref mscorlib[000001C19825C7D0] -> C:\Program Files\Mono\lib\mono\4.5\mscorlib.dll[000001C19B0A3300]: 2 (in domain Mono, info)
Image addref mscorlib[000001C19825C860] -> C:\Program Files\Mono\lib\/mono/4.5/mscorlib.dll[000001C19B0A3A40]: 3 (in domain Mono, info)
Prepared to set up assembly 'mscorlib' (C:\Program Files\Mono\lib\/mono/4.5/mscorlib.dll) (in domain Mono, info)
AOT: image 'C:\Program Files\Mono\lib\/mono/4.5/mscorlib.dll.dll' not found: The system cannot find the file specified.
 (in domain Mono, info)
AOT: image 'C:\Program Files\Mono\lib\/mono/aot-cache/amd64/mscorlib.dll.dll' not found: The system cannot find the path specified.
 (in domain Mono, info)
Assembly Loader loaded assembly from location: 'C:\Program Files\Mono\lib\mono\4.5\mscorlib.dll'. (in domain Mono, info)
Config attempting to parse: 'C:\Program Files\Mono\lib\/mono/4.5/mscorlib.dll.config'. (in domain Mono, info)
Config attempting to parse: 'C:\Program Files\Mono\etc\mono\assemblies\mscorlib\mscorlib.config'. (in domain Mono, info)
Config attempting to parse: 'C:\Users\jbonazza\.mono\assemblies\mscorlib\mscorlib.config'. (in domain Mono, info)
Unloading image C:\Program Files\Mono\lib\mono\4.5\mscorlib.dll [000001C19B0A3300]. (in domain Mono, info)
Assembly mscorlib[000001C19825C860] added to domain GodotEngine.RootDomain, ref_count=1 (in domain Mono, info)
Found assembly remapping for mscorlib and was for the same version 4.0.0.0 (in domain Mono, debug)
Assembly mscorlib[000001C19825C860] added to domain GodotEngine.ToolsDomain, ref_count=2 (in domain Mono, info)
Image addref GodotSharpTools[000001C19825D430] -> C:\Users\jbonazza\Documents\Godot_v3.0-rc1_mono_win64\Godot_v3.0-rc1_mono_win64/GodotSharpTools.dll[000001C19B1630E0]: 2 (in domain Mono, info)
Prepared to set up assembly 'GodotSharpTools' (C:\Users\jbonazza\Documents\Godot_v3.0-rc1_mono_win64\Godot_v3.0-rc1_mono_win64/GodotSharpTools.dll) (in domain Mono, info)
Assembly GodotSharpTools[000001C19825D430] added to domain GodotEngine.ToolsDomain, ref_count=1 (in domain Mono, info)
AOT: image 'C:\Users\jbonazza\Documents\Godot_v3.0-rc1_mono_win64\Godot_v3.0-rc1_mono_win64/GodotSharpTools.dll.dll' not found: The system cannot find the file specified.
 (in domain Mono, info)
AOT: image 'C:\Program Files\Mono\lib\/mono/aot-cache/amd64/GodotSharpTools.dll.dll' not found: The system cannot find the path specified.
 (in domain Mono, info)
Assembly mscorlib[000001C19825C860] added to domain GodotEngine.ScriptsDomain, ref_count=3 (in domain Mono, info)
Symbol file LoadedFromMemory is not a mono symbol file (in domain , warning)
Image addref GodotSharp[000001C19825D5E0] -> res://.mono/assemblies/GodotSharp.dll[000001C19B163A90]: 3 (in domain Mono, info)
Prepared to set up assembly 'GodotSharp' (res://.mono/assemblies/GodotSharp.dll) (in domain Mono, info)
Assembly GodotSharp[000001C19825D5E0] added to domain GodotEngine.ScriptsDomain, ref_count=1 (in domain Mono, info)
AOT: image 'res://.mono/assemblies/GodotSharp.dll.dll' not found: The filename, directory name, or volume label syntax is incorrect.
 (in domain Mono, info)
AOT: image 'C:\Program Files\Mono\lib\/mono/aot-cache/amd64/GodotSharp.dll.dll' not found: The system cannot find the path specified.
 (in domain Mono, info)
Found assembly remapping for mscorlib and was for the same version 4.0.0.0 (in domain Mono, debug)
Config attempting to parse: ''. (in domain Mono, info)
Found assembly remapping for mscorlib and was for the same version 4.0.0.0 (in domain Mono, debug)
Assembly Ref addref GodotSharp[000001C19825D5E0] -> mscorlib[000001C19825C860]: 4 (in domain Mono, info)
Found assembly remapping for System and was for the same version 4.0.0.0 (in domain Mono, debug)
Found assembly remapping for System and was for the same version 4.0.0.0 (in domain Mono, debug)
Image addref System[000001C19344D910] -> C:\Program Files\Mono\lib\/mono/4.5/System.dll[000001C19B152090]: 2 (in domain Mono, info)
Prepared to set up assembly 'System' (C:\Program Files\Mono\lib\/mono/4.5/System.dll) (in domain Mono, info)
Assembly System[000001C19344D910] added to domain GodotEngine.ScriptsDomain, ref_count=1 (in domain Mono, info)
AOT: image 'C:\Program Files\Mono\lib\/mono/4.5/System.dll.dll' not found: The system cannot find the file specified.
 (in domain Mono, info)
AOT: image 'C:\Program Files\Mono\lib\/mono/aot-cache/amd64/System.dll.dll' not found: The system cannot find the path specified.
 (in domain Mono, info)
Assembly Ref addref GodotSharp[000001C19825D5E0] -> System[000001C19344D910]: 2 (in domain Mono, info)
Found assembly remapping for mscorlib and was for the same version 4.0.0.0 (in domain Mono, debug)
Found assembly remapping for mscorlib and was for the same version 4.0.0.0 (in domain Mono, debug)
Assembly Ref addref System[000001C19344D910] -> mscorlib[000001C19825C860]: 5 (in domain Mono, info)
Symbol file LoadedFromMemory is not a mono symbol file (in domain , warning)
Image addref GodotSharpEditor[000001C19B159670] -> res://.mono/assemblies/GodotSharpEditor.dll[000001C19B15B2D0]: 3 (in domain Mono, info)
Prepared to set up assembly 'GodotSharpEditor' (res://.mono/assemblies/GodotSharpEditor.dll) (in domain Mono, info)
Assembly GodotSharpEditor[000001C19B159670] added to domain GodotEngine.ScriptsDomain, ref_count=1 (in domain Mono, info)
AOT: image 'res://.mono/assemblies/GodotSharpEditor.dll.dll' not found: The filename, directory name, or volume label syntax is incorrect.
 (in domain Mono, info)
AOT: image 'C:\Program Files\Mono\lib\/mono/aot-cache/amd64/GodotSharpEditor.dll.dll' not found: The system cannot find the path specified.
 (in domain Mono, info)
Symbol file LoadedFromMemory is not a mono symbol file (in domain , warning)
Image addref rpgproject[000001C19B159DC0] -> res://.mono/temp/bin/Tools/rpgproject.dll[000001C19B1C6050]: 3 (in domain Mono, info)
Prepared to set up assembly 'rpgproject' (res://.mono/temp/bin/Tools/rpgproject.dll) (in domain Mono, info)
Assembly rpgproject[000001C19B159DC0] added to domain GodotEngine.ScriptsDomain, ref_count=1 (in domain Mono, info)
AOT: image 'res://.mono/temp/bin/Tools/rpgproject.dll.dll' not found: The filename, directory name, or volume label syntax is incorrect.
 (in domain Mono, info)
AOT: image 'C:\Program Files\Mono\lib\/mono/aot-cache/amd64/rpgproject.dll.dll' not found: The system cannot find the path specified.
 (in domain Mono, info)
Assembly Ref addref rpgproject[000001C19B159DC0] -> GodotSharp[000001C19825D5E0]: 2 (in domain Mono, info)
Found assembly remapping for mscorlib and was for the same version 4.0.0.0 (in domain Mono, debug)
Found assembly remapping for mscorlib and was for the same version 4.0.0.0 (in domain Mono, debug)
Assembly Ref addref rpgproject[000001C19B159DC0] -> mscorlib[000001C19825C860]: 6 (in domain Mono, info)
type 0x1 not handled in mono_runtime_invoke_array (in domain , error)

```

**Comment by deltasquad451** [comment] 2018-01-15 04:16
**Godot version:**
RC1 64-bit

**OS/device including version:**
Windows 7 64-bit

With the test case that was provided by @jonbonazza I was also getting the same error:


`Config attempting to parse: 'C:\Program Files\Mono\etc\mono\config'. (in domain Mono, info)
Assembly Loader probing location: 'C:\Program Files\Mono\lib\mono\4.5\mscorlib.dll'. (in domain Mono, info)
Image addref mscorlib[0000000007EF4D10] -> C:\Program Files\Mono\lib\mono\4.5\mscorlib.dll[00000000081332D0]: 2 (in domain Mono, info)
Image addref mscorlib[0000000007EF4DA0] -> C:\Program Files\Mono\lib\/mono/4.5/mscorlib.dll[0000000008133BB0]: 3 (in domain Mono, info)
Prepared to set up assembly 'mscorlib' (C:\Program Files\Mono\lib\/mono/4.5/mscorlib.dll) (in domain Mono, info)
AOT: image 'C:\Program Files\Mono\lib\/mono/4.5/mscorlib.dll.dll' not found: The system cannot find the file specified.
 (in domain Mono, info)
AOT: image 'C:\Program Files\Mono\lib\/mono/aot-cache/amd64/mscorlib.dll.dll' not found: The system cannot find the path specified.
 (in domain Mono, info)
Assembly Loader loaded assembly from location: 'C:\Program Files\Mono\lib\mono\4.5\mscorlib.dll'. (in domain Mono, info)
Config attempting to parse: 'C:\Program Files\Mono\lib\/mono/4.5/mscorlib.dll.config'. (in domain Mono, info)
Config attempting to parse: 'C:\Program Files\Mono\etc\mono\assemblies\mscorlib\mscorlib.config'. (in domain Mono, info)
Config attempting to parse: 'C:\Users\lando\.mono\assemblies\mscorlib\mscorlib.config'. (in domain Mono, info)
Unloading image C:\Program Files\Mono\lib\mono\4.5\mscorlib.dll [00000000081332D0]. (in domain Mono, info)
Assembly mscorlib[0000000007EF4DA0] added to domain GodotEngine.RootDomain, ref_count=1 (in domain Mono, info)
Found assembly remapping for mscorlib and was for the same version 4.0.0.0 (in domain Mono, debug)
Assembly mscorlib[0000000007EF4DA0] added to domain GodotEngine.ToolsDomain, ref_count=2 (in domain Mono, info)
Image addref GodotSharpTools[0000000007EF5220] -> D:\Documents\Programming\Godot Engine\Godot_v3.0-rc1_mono_win64/GodotSharpTools.dll[00000000081DEB10]: 2 (in domain Mono, info)
Prepared to set up assembly 'GodotSharpTools' (D:\Documents\Programming\Godot Engine\Godot_v3.0-rc1_mono_win64/GodotSharpTools.dll) (in domain Mono, info)
Assembly GodotSharpTools[0000000007EF5220] added to domain GodotEngine.ToolsDomain, ref_count=1 (in domain Mono, info)
AOT: image 'D:\Documents\Programming\Godot Engine\Godot_v3.0-rc1_mono_win64/GodotSharpTools.dll.dll' not found: The system cannot find the file specified.
 (in domain Mono, info)
AOT: image 'C:\Program Files\Mono\lib\/mono/aot-cache/amd64/GodotSharpTools.dll.dll' not found: The system cannot find the path specified.
 (in domain Mono, info)
Assembly mscorlib[0000000007EF4DA0] added to domain GodotEngine.ScriptsDomain, ref_count=3 (in domain Mono, info)
Symbol file LoadedFromMemory is not a mono symbol file (in domain , warning)
Image addref GodotSharp[0000000007EF52B0] -> res://.mono/assemblies/GodotSharp.dll[00000000081D9CB0]: 3 (in domain Mono, info)
Prepared to set up assembly 'GodotSharp' (res://.mono/assemblies/GodotSharp.dll) (in domain Mono, info)
Assembly GodotSharp[0000000007EF52B0] added to domain GodotEngine.ScriptsDomain, ref_count=1 (in domain Mono, info)
AOT: image 'res://.mono/assemblies/GodotSharp.dll.dll' not found: The filename, directory name, or volume label syntax is incorrect.
 (in domain Mono, info)
AOT: image 'C:\Program Files\Mono\lib\/mono/aot-cache/amd64/GodotSharp.dll.dll' not found: The system cannot find the path specified.
 (in domain Mono, info)
Found assembly remapping for mscorlib and was for the same version 4.0.0.0 (in domain Mono, debug)
Config attempting to parse: ''. (in domain Mono, info)
Found assembly remapping for mscorlib and was for the same version 4.0.0.0 (in domain Mono, debug)
Assembly Ref addref GodotSharp[0000000007EF52B0] -> mscorlib[0000000007EF4DA0]: 4 (in domain Mono, info)
Found assembly remapping for System and was for the same version 4.0.0.0 (in domain Mono, debug)
Found assembly remapping for System and was for the same version 4.0.0.0 (in domain Mono, debug)
Image addref System[0000000007EF53D0] -> C:\Program Files\Mono\lib\/mono/4.5/System.dll[0000000008211540]: 2 (in domain Mono, info)
Prepared to set up assembly 'System' (C:\Program Files\Mono\lib\/mono/4.5/System.dll) (in domain Mono, info)
Assembly System[0000000007EF53D0] added to domain GodotEngine.ScriptsDomain, ref_count=1 (in domain Mono, info)
AOT: image 'C:\Program Files\Mono\lib\/mono/4.5/System.dll.dll' not found: The system cannot find the file specified.
 (in domain Mono, info)
AOT: image 'C:\Program Files\Mono\lib\/mono/aot-cache/amd64/System.dll.dll' not found: The system cannot find the path specified.
 (in domain Mono, info)
Assembly Ref addref GodotSharp[0000000007EF52B0] -> System[0000000007EF53D0]: 2 (in domain Mono, info)
Found assembly remapping for mscorlib and was for the same version 4.0.0.0 (in domain Mono, debug)
Found assembly remapping for mscorlib and was for the same version 4.0.0.0 (in domain Mono, debug)
Assembly Ref addref System[0000000007EF53D0] -> mscorlib[0000000007EF4DA0]: 5 (in domain Mono, info)
Symbol file LoadedFromMemory is not a mono symbol file (in domain , warning)
Image addref GodotSharpEditor[0000000007EF56A0] -> res://.mono/assemblies/GodotSharpEditor.dll[00000000081C4CD0]: 3 (in domain Mono, info)
Prepared to set up assembly 'GodotSharpEditor' (res://.mono/assemblies/GodotSharpEditor.dll) (in domain Mono, info)
Assembly GodotSharpEditor[0000000007EF56A0] added to domain GodotEngine.ScriptsDomain, ref_count=1 (in domain Mono, info)
AOT: image 'res://.mono/assemblies/GodotSharpEditor.dll.dll' not found: The filename, directory name, or volume label syntax is incorrect.
 (in domain Mono, info)
AOT: image 'C:\Program Files\Mono\lib\/mono/aot-cache/amd64/GodotSharpEditor.dll.dll' not found: The system cannot find the path specified.
 (in domain Mono, info)
Symbol file LoadedFromMemory is not a mono symbol file (in domain , warning)
Image addref New Game Project[0000000007EF5730] -> res://.mono/temp/bin/Tools/New Game Project.dll[0000000008220A70]: 3 (in domain Mono, info)
Prepared to set up assembly 'New Game Project' (res://.mono/temp/bin/Tools/New Game Project.dll) (in domain Mono, info)
Assembly New Game Project[0000000007EF5730] added to domain GodotEngine.ScriptsDomain, ref_count=1 (in domain Mono, info)
AOT: image 'res://.mono/temp/bin/Tools/New Game Project.dll.dll' not found: The filename, directory name, or volume label syntax is incorrect.
 (in domain Mono, info)
AOT: image 'C:\Program Files\Mono\lib\/mono/aot-cache/amd64/New Game Project.dll.dll' not found: The system cannot find the path specified.
 (in domain Mono, info)
Assembly Ref addref New Game Project[0000000007EF5730] -> GodotSharp[0000000007EF52B0]: 2 (in domain Mono, info)
Found assembly remapping for mscorlib and was for the same version 4.0.0.0 (in domain Mono, debug)
Found assembly remapping for mscorlib and was for the same version 4.0.0.0 (in domain Mono, debug)
Assembly Ref addref New Game Project[0000000007EF5730] -> mscorlib[0000000007EF4DA0]: 6 (in domain Mono, info)
type 0x1 not handled in mono_runtime_invoke_array (in domain , error)
`

Another note, I had cleared the mono folder in the Godot user folder, in addition I had created a new project and manually re-imported each asset.

**Comment by akien-mga** [comment] 2018-01-15 06:50
CC @neikeq

**Comment by NathanWarden** [comment] 2018-01-15 13:16
Did you also clear the mono folder in [HOME]/AppData/Roaming/Godot?

**Comment by neikeq** [comment] 2018-01-15 13:45
Can you share an example project?

**Comment by nextdimension** [comment] 2018-01-15 16:50
I had a crash when I opened old c# project from beta 2 with the new RC1. I deleted the mono folders in the project and the  "[HOME]/AppData/Roaming/Godotroaming" and re imported the project. Its working fine now.

**Comment by deltasquad451** [comment] 2018-01-15 16:59
Link to example project:
https://drive.google.com/file/d/1mo4kWV205i4WKU4o3unz2wDhT9w54RXC/view?usp=sharing

I had cleared my "[HOME]/AppData/Roaming/Godot" and re imported the project, I still get the same error.

**Comment by nextdimension** [comment] 2018-01-15 17:34
In your player Scene Toggle the visibility of the camera to not visible and then the game works

**Comment by jonbonazza** [comment] 2018-01-15 23:23
@nextdimension Interesting. Admittedly, one time I removed the camera from the Player scene and it ran, then when I added it back, it continued to run until I restarted Godot. At that point, nothing I did would make it run again. I'm not sure what is causing havoc though.

**Comment by DleanJeans** [comment] 2018-01-18 16:26
Having the same problem with non-Mono Godot 3 RC1
The game just crashed with just this:
```
drivers/windows/stream_peer_tcp_winsock.cpp:203 - Server disconnected
```
It seems to correlate with adding a `VisibilityNotifier2D`.

**Comment by neikeq** [comment] 2018-01-25 23:08
I cannot reproduce on latest master with @deltasquad451's example. It looks to me like the same issue fixed by #15935

**Comment by akien-mga** [comment] 2018-01-25 23:14
Assuming fixed then, please comment if you can still reproduce it.

**Closed by akien-mga** 2018-01-25 23:14 UTC
Labels: bug, topic:mono

**Comment by MEJIOMAH17** [comment] 2020-10-17 18:52
Config attempting to parse: 'C:\Program Files\Mono\etc\mono\config'. (in domain Mono, info)
Image addref mscorlib[00000000181026A0] (asmctx DEFAULT) -> C:\Program Files\Mono\lib\/mono/4.5/mscorlib.dll[00000000182B6030]: 2 (in domain Mono, info)
Prepared to set up assembly 'mscorlib' (C:\Program Files\Mono\lib\/mono/4.5/mscorlib.dll) (in domain Mono, info)
AOT: image 'C:\Program Files\Mono\lib\/mono/4.5/mscorlib.dll.dll' not found: The system cannot find the file specified.
 (in domain Mono, info)
AOT: image 'C:\Program Files\Mono\lib\/mono/aot-cache/amd64/mscorlib.dll.dll' not found: The system cannot find the path specified.
 (in domain Mono, info)
Assembly mscorlib[00000000181026A0] added to domain GodotEngine.RootDomain, ref_count=1 (in domain Mono, info)
Assembly mscorlib[00000000181026A0] added to domain GodotEngine.Domain.Scripts, ref_count=2 (in domain Mono, info)

**Comment by Calinou** [comment] 2020-10-17 19:23
@MEJIOMAH17 Please open a new issue with a minimal reproduction project attached.
