### ISSUE TITLE
trunc(vector_type) broken in shaders (causes runtime GLSL compile failure)

### ISSUE THREAD

**Issue by gau-veldt** [godotengine/godot#6720] opened 2016-10-06 02:23 UTC
**Operating system or device - Godot version:**
Godot 2.2a linux x11 AMD FX8320 (8-core) 16GB RAM

**Issue description** (what happened, and what was expected):
The following code fails to compile in a shader:

F-shader (also triggers on V-shader - I never tested with L-shader):
vec3 vector_with_floaties=vec3(1.41421,2.71828,3.14159);
vec3 integral_vector=trunc(vector_with_floaties); // <-- fails to compile
// workaruond: vec3 integral_vector=vector_with_floaties-fract(vector_with_floaties);

No errors occur in the editor but the scene will have the tell-tale dull-grey shade (indicating shader didn't run) errors messages will have logged in Debug and the errors are visible in full when using the console (it's not possible to read the error in the Debug window due to the huge one-liner error message in a view that has no scrollbar).

**Steps to reproduce:**
See above.

**Link to minimal example project** (optional but very welcome):
See above.

**Comment by eska014** [comment] 2016-10-09 19:16
The full error can be seen by hovering over the message:
```
Type: Error
Description:
Time: 0:00:00:0400
C Error: MaterialShaderGLES2: Fragment Program Compilation Failed:
0(857): error C7532: global function trunc requires "#version 130" or later

C Source: drivers/gles2/shader_gles2.cpp:491
C Function: ShaderGLES2::get_current_version
```
Godot Engine uses `#version 120`.
GLSL 1.30 was released later than OpenGL ES 2, so I'm not sure if `trunc` can be made available before Godot 3.0 with OpenGL ES 3

**Comment by Noshyaar** [comment] 2018-04-07 07:32
First of all thank you for your report and sorry for the delay.

We released Godot 3.0 in January 2018 after 18 months of work, fixing many old issues either directly, or by obsoleting/replacing the features they were referring to.

We still have hundreds of issues whose relevance/reproducibility needs to be checked against the [current stable version](https://godotengine.org/download), and that's where you can help us.
**Could you check if the issue that you described initially is still relevant/reproducible in Godot 3.0 or any newer version, and comment about it here?**

For bug reports, please also make sure that the issue contains detailed steps to reproduce the bug and, if possible, a zipped project that can be used to reproduce it right away. This greatly speeds up debugging and bugfixing tasks for our contributors.

Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

Thanks in advance.

*Note: This message is being copy-pasted to many "stale" issues (90+ days without activity). It might happen that it is not meaningful for this specific issue or appears oblivious of the issue's context, if so please comment to notify the Bugsquad about it.*

**Comment by Chaosus** [comment] 2018-08-19 07:54
@vnen @akien-mga This issue is fixed in latest master, should be closed.

**Closed** 2018-08-19 07:59 UTC
Labels: bug, confirmed, topic:rendering

**Comment by kcaze** [comment] 2020-06-19 01:11
I just ran into this issue today on 3.2.1.stable, but only on the HTML5 build. Should I create a new issue for it?

**Comment by Calinou** [comment] 2020-06-19 07:23
@kcaze Since this issue is very old, I'd create a new issue for it.
