### ISSUE TITLE
Windows Task Manager GPU Resources being undetected

### ISSUE THREAD

**Issue by sanyi12** [godotengine/godot#74715] opened 2023-03-10 12:24 UTC
### Godot version

4.0

### System information

Windows 10, RTX3070

### Issue description

During tests I have observed an issue with the GPU monitoring while using Godot 4 - the task manager would show ~10% usage but the temperature would increase and the fps would drop _significantly_. The _significant_ fps drop and temperature rise usually occurs only when the GPU hits its 100% limit in the task manager. But while using Godot that does not show. 

I am posting this here only because it gets annoying - running multiple apps for development I check the task manager to see available resources. [It has nothing to do with the built-in Godot's profiler]
If Godot eats all GPU resources other apps will run much slower. 

### Steps to reproduce

Create any project with millions of polygons. 

### Minimal reproduction project

No project.

**Comment by clayjohn** [comment] 2023-03-10 18:54
This doesn't sound like an issue that we can address. We have no control over what the Windows task manager reports. 

Are you sure the issue is with the GPU? Perhaps your CPU is maxed out and that is causing the low frame rate and heat.

**Comment by sanyi12** [comment] 2023-03-11 13:40
Most software can be detected by the task manager resource profiler but for some reason Godot 4 has some hidden processes that do not allow that. If people become crazy they might even say there is a mining bitcoin virus inside Godot because it portrays similar behavior, hidden process that eats away resources without the user's knowledge. Pretty bad this was labeled as "thirdparty"

**Comment by AThousandShips** [comment] 2023-03-11 14:49
But the task manager is thirdparty so, and no reason to appeal to conspiracy theories or use ableist language

**Comment by AThousandShips** [comment] 2023-03-11 14:54
Unless there's some specific mistake being done, like not connecting separate threads of the editor so the task manager can find them, we can't really be bound to follow what ever arcane ways the task manager demands to make it work, that's what the tag means I'm sure

**Comment by MarioLiebisch** [comment] 2023-03-11 21:01
Since you're mentioning temperature/FPS drops: Are you 100% confident you're not causing 100% CPU load on one single core that causes the CPU to potentially bottleneck the GPU? This would **not** show up as 100% usage in Task Manager and instead as something liker 12.5% load on an 8 core CPU for example.

**Comment by sanyi12** [comment] 2023-03-11 22:49
<img width="568" alt="hjyp" src="https://user-images.githubusercontent.com/79376841/224514881-48b4e998-07a1-4cf4-aaea-319bee949fbe.png">

**Comment by sanyi12** [comment] 2023-03-11 22:51
On Open Hardware Monitor it shows the load - in the task manager it doesn't

**Comment by MarioLiebisch** [comment] 2023-04-24 19:00
Just stumbled over this again and for me it's working as expected. I have a passive 3D scene (read: nothing moving, no animations) and GPU resources drop down below 1% while the view isn't redraw. If I move the camera quickly, I can get up to around 80% load.

And something I completely forgot earlier:
- If you're on Windows 11, go to Windows' (default) Graphics settings, find "Variable Refresh Rate" (I think that's what it's called in the English version) and make sure to disable it.
- If this doesn't change anything, make sure to disable ShadowPlay's recording in background and if in doubt, reset the driver settings to defaults.
- Some of these settings might cause higher power consumption and even cause more redrawing than necessary.

**Comment by Calinou** [comment] 2023-04-24 22:43
Windows task manager's GPU readout is wildly known to be inaccurate. Use other tools instead, such as RTSS or GeForce Experience's overlay (<kbd>Alt + R</kbd>).

**Comment by Calinou** [comment] 2023-07-13 23:38
Closing, as this is an issue with the Windows task manager we can't resolve.

**Closed by Calinou** 2023-07-13 23:38 UTC
Labels: platform:windows, discussion, topic:thirdparty
