### ISSUE TITLE
MenuButton doesn't apply custom styles

### ISSUE THREAD

**Issue by boruok** [godotengine/godot#51612] opened 2021-08-13 07:35 UTC
### Godot version

3.3.2 and 3.4.beta

### System information

Windows 10, GTS 450

### Issue description

Tried to edit custom style to **MenuButton**, but node doesn't apply style on both **edtior** and **play**. I though it must be **PopupMenu** style wich appears when you click **MenuButton**, but even if overrided style **PopupMenu** appears with defaults.

![Example](https://user-images.githubusercontent.com/36783322/129321196-31af5924-3506-453a-8566-9a559246a939.png)

### Steps to reproduce

1. open attachment
2. try to change custom style

### Minimal reproduction project

[New Game Project.zip](https://github.com/godotengine/godot/files/6980659/New.Game.Project.zip)

**Comment by pycbouh** [comment] 2021-08-17 21:43
Duplicate of https://github.com/godotengine/godot/issues/30768

**Closed by pycbouh** 2021-08-17 21:43 UTC
Labels: enhancement, archived, topic:gui
