### ISSUE TITLE
The Layout menu for Control nodes inside a Viewport is not visible

### ISSUE THREAD

**Issue by groud** [godotengine/godot#22610] opened 2018-10-02 09:13 UTC
**Godot version:** Current master

**OS/device including version:** Archlinux

**Issue description:** 
The Layout menu should be visible in such situation :
![2018-10-02-111506_815x219_scrot](https://user-images.githubusercontent.com/6093119/46339972-6fbc2380-c634-11e8-8329-4f2bf13d950b.png)

**Steps to reproduce:**
Add a Control Node as a child of a Viewport, selected the control node = no layout menu.

**Comment by KoBeWi** [comment] 2019-05-19 21:58
Duplicate of #3572

**Comment by groud** [comment] 2019-05-19 22:02
Wow that's an old issue
Closing as a duplicate of #3572 then

**Closed** 2019-05-19 22:03 UTC
Labels: archived
