### ISSUE TITLE
Vulkan Mobile backend: Lights don't affect primitive meshes

### ISSUE THREAD

**Issue by mrjustaguy** [godotengine/godot#55892] opened 2021-12-13 10:02 UTC
### Godot version

v4.0.dev.calinou [6d58b968d]

### System information

Windows 11, Vulkan, Nvidia Quadro K2000 461.92

### Issue description

Lights don't work on the Mobile Renderer on non-pre-alpha builds.

![Mobile Lights](https://user-images.githubusercontent.com/50302479/145791249-bbc7603c-2ac9-4052-b1db-66c3172b1bfb.png)

This is quite possibly related to the specific GPU architecture, as Kepler GPUs are known to have plenty of issues with DX12 and Vulkan.
I don't have access to different GPU architectures that support Vulkan so I cannot test the theory out.

Do note - Changing shading of the mesh to Lambert and things like that don't fix the lack of lights.

### Steps to reproduce

Create a Mesh and try to apply Lights to it.

### Minimal reproduction project

[Bug.zip](https://github.com/godotengine/godot/files/7702797/Bug.zip)

**Comment by Calinou** [comment] 2021-12-13 12:08
I can reproduce this on `master` 2a9dd654b (Linux, GeForce GTX 1080):

![image](https://user-images.githubusercontent.com/180032/145809471-3b546fed-9a1c-4bd0-9dad-55288ec1df87.png)

It works in other scenes though, so it must be something specific to this project.

**Comment by Calinou** [comment] 2022-02-28 14:57
Note that this was *not* fixed by https://github.com/godotengine/godot/pull/58628. I tested the commit just before and after, and can confirm the issue is still present in both commits with the MRP linked.

**Comment by lufog** [comment] 2022-02-28 20:35
@Calinou, I believe #58628 fix the problem, but you need to delete `.godot` folder, maybe it cached?

I think #58628 fixes the problem, but you need to delete project's `.godot` folder. Perhaps this data is cached?

v4.0.alpha.custom_build [54a777b52]:
![image](https://user-images.githubusercontent.com/10379487/156054444-46113ecf-5141-4c30-8a2e-63798abc3fc9.png)

v4.0.alpha.custom_build [039ffda99]:
![image](https://user-images.githubusercontent.com/10379487/156054516-37739507-5349-4da3-813b-a0a29c7ea1ed.png)

**Comment by Calinou** [comment] 2022-02-28 20:57
@lufog I see, I guess we can consider this resolved then.

**Closed by Calinou** 2022-02-28 20:57 UTC
Labels: bug, topic:rendering, confirmed, topic:3d
