### ISSUE TITLE
GDScript 2.0: Can't write multiline assert statements

### ISSUE THREAD

**Issue by blaze-the-star** [godotengine/godot#69742] opened 2022-12-08 00:58 UTC
### Godot version

4.0.beta7.official

### System information

Ubuntu

### Issue description

Attempting to write an assert statement on multiple lines causes the following error:
`Expected expression to assert`

### Steps to reproduce

Example:
```
# This is fine
get_node(
    ""
)

# and this is fine
assert(true, "")

# but his is not
assert(
    true,
    ""
)
```

### Minimal reproduction project

N/A

**Comment by Calinou** [comment] 2022-12-08 01:00
Duplicate of https://github.com/godotengine/godot/issues/66535.

**Closed by Calinou** 2022-12-08 01:00 UTC
Labels: bug, archived, topic:gdscript, regression
