### ISSUE TITLE
The scene preview sometimes loads an image without antialiasing

### ISSUE THREAD

**Issue by Daw11** [godotengine/godot#28708] opened 2019-05-05 16:25 UTC
**Godot version:**
3.1.1 stable

**OS/device including version:**
Linux, radeon RX590, mesa

**Issue description:**
Saving a scene causes its preview to change after every save.

In particular it switches between two versions, one without antialiasing and one with it:
![same](https://user-images.githubusercontent.com/3595817/57196739-f553d900-6f5f-11e9-90e7-3139359ce07e.png)

**Steps to reproduce:**
Save a scene, go to another tab and look at its preview.
Go back, save the scene again and then look at the preview.

**Additional infos**
I couldn't pinpoint the exact cause but I did some research.
Inside the folder with the cached images the preview is always the same, regardless of what is shown inside of Godot.
Reloading the application fixes the image ( it becomes the one with the antialiasing ).
When a scene is saved, when the image with antialiasing is generated there's only one call to the `queue_resource_preview` method inside `EditorResourcePreview`, when the preview without antialising is created there are instead two calls.

I'm not sure if it's related to this bug, but I noticed that inside the function `_thread()` of the `EditorResourcePreview`, the mutex of the preview is released before the completion of all the operations.
https://github.com/godotengine/godot/blob/255ea11502dd91a91d98e6d1bd054ceaf3aee619/editor/editor_resource_preview.cpp#L212-L219
If I put it at the end of the function however Godot freezes at the line `texture.instance()`:
https://github.com/godotengine/godot/blob/255ea11502dd91a91d98e6d1bd054ceaf3aee619/editor/editor_resource_preview.cpp#L288-L292
My guess it that this line requires the mutex to be unlocked to work.

**Comment by Jummit** [comment] 2019-05-06 15:44
So the issue isn't that it saves after every save, but that it doesn't use anti-aliasing? The title is kinda confusing, as it is intended behavior that the icon gets generated every save (I think).

**Comment by Daw11** [comment] 2019-05-06 18:53
> So the issue isn't that it saves after every save, but that it doesn't use anti-aliasing? The title is kinda confusing, as it is intended behavior that the icon gets generated every save (I think).

Yes, I changed the title to make it more clear.
The scene is always the same and the camera angle doesn't change, so the image should be exactly the same.
The problem is that the preview cycle between the two versions after every save.

**Comment by CptPotato** [comment] 2019-05-07 05:50
I don't see any antialiasing in those images. It looks more like texture filtering to me.

**Comment by KoBeWi** [comment] 2020-09-27 21:17
Can anyone still reproduce this bug in Godot 3.2.3 or any later release?

If yes, please ensure that an up-to-date Minimal Reproduction Project (MRP) is included in this report (a MRP is a zipped Godot project with the minimal elements necessary to reliably trigger the bug). You can upload ZIP files in an issue comment with a drag and drop.

**Comment by akien-mga** [comment] 2020-12-10 23:01
No answer, so closing.

**Closed by akien-mga** 2020-12-10 23:01 UTC
Labels: bug, topic:editor, usability
