### ISSUE TITLE
2D shader only affects on the editor but not on the game.

### ISSUE THREAD

**Issue by ca3games** [godotengine/godot#57957] opened 2022-02-11 05:23 UTC
### Godot version

3.4.2

### System information

Manjaro, Vega 8 with Ryzen 3200 G

### Issue description

2D canvas layer shader made to recolor an animated Sprite doesnt recolor the sprites when playing the game, only on the editor.

![Screenshot_20220211_001317](https://user-images.githubusercontent.com/19626687/153541421-18e7adfc-f3d0-4e73-8d9f-a7e854b1ba61.png)

### Steps to reproduce

Create a basic shader that replaces pixel colors on 2D sprites inside an animatedSprite node.

### Minimal reproduction project

[Bug.zip](https://github.com/godotengine/godot/files/8046124/Bug.zip)

**Comment by clayjohn** [comment] 2022-02-11 07:06
Duplicate of https://github.com/godotengine/godot/issues/42140

The solution to your issue is described in the comments. It comes from trying to compare floating point values with the ``==`` operator.

**Closed by clayjohn** 2022-02-11 07:06 UTC
