### ISSUE TITLE
Some shortcuts apply to an open shader script instead of the focused gdscript script (or selected node in a scene)

### ISSUE THREAD

**Issue by GTcreyon** [godotengine/godot#54635] opened 2021-11-05 17:01 UTC
### Godot version

3.3.4.stable

### System information

Windows 10

### Issue description

When scripting with both a .gd file and a .gdshader open, some shortcuts exclusively act on the shader, never the .gd file, even if the .gd file is in focus.

Shortcuts I have found so far include:
* Ctrl+D
* Ctrl+K (also causes focus to be transferred to the .gdshader file)
* Ctrl+F
* F3
* Alt+Up/Down
* Ctrl+Shift+K
* etc.

Additionally, selecting a node in a scene editor, then opening the shader, then selecting the node again, allows the node to be moved and interacted with using the mouse, but shortcuts such as Ctrl+D are still stolen by the shader.

### Steps to reproduce

* Open a .gd file in the script editor.
* Open a .gdshader file alongside it.
* Select some text in the .gd file.
* Press Ctrl+D.
* A line in the .gdshader will duplicate instead of the selected text in the .gd script.

**Comment by Calinou** [comment] 2021-11-05 17:04
This is a duplicate of a longstanding issue with editor focus shortcuts in `3.x` (which can't be fixed completely there). It's been fixed in `master` with a backwards-incompatible overhaul of editor shortcuts.

**Comment by Paulb23** [comment] 2021-11-17 19:20
Duplicate of #52861

**Closed by Paulb23** 2021-11-17 19:20 UTC
Labels: bug, topic:editor
