### ISSUE TITLE
Unable to return to editor after project run

### ISSUE THREAD

**Issue by werryxgames** [godotengine/godot#65565] opened 2022-09-09 10:28 UTC
### Godot version

3.5.1rc1

### System information

Xiaomi Redmi 9C, GLES2

### Issue description

Unable to return to editor after project run. If I press back button, or run project with `get_tree().quit()`, Godot app closes, but it should return to editor

### Steps to reproduce

Create new project and run it

**Comment by RoniPerson** [comment] 2022-10-23 17:40
Can confirm on Lenovo Tab P11
Godot Version: v3.5.1.stable.official [6fed1ffa3]
Both with GLES2 and GLES3
```
adb logcat *:W
```
```
10-23 19:26:40.290  1490  1900 W InputDispatcher: channel '5fe2f6d org.godotengine.editor.v3/org.godotengine.editor.GodotGame (server)' ~ Consumer closed input channel or an error occurred.  events=0xd
10-23 19:26:40.290  1490  1900 E InputDispatcher: channel '5fe2f6d org.godotengine.editor.v3/org.godotengine.editor.GodotGame (server)' ~ Channel is unrecoverably broken and will be disposed!
10-23 19:26:40.331  1490  1552 W InputDispatcher: Attempted to unregister already unregistered input channel '5fe2f6d org.godotengine.editor.v3/org.godotengine.editor.GodotGame (server)'
10-23 19:26:40.366  1490  2656 W ActivityTaskManager: Force removing ActivityRecord{4090806 u0 org.godotengine.editor.v3/org.godotengine.editor.GodotGame t252}: app died, no saved state
10-23 19:26:40.472  1490  1575 W ActivityManager: setHasOverlayUi called on unknown pid: 22651
10-23 19:26:40.490  1490  1573 W Looper  : Slow dispatch took 125ms android.ui h=com.android.server.am.ActivityManagerService$UiHandler c=null m=53
10-23 19:26:40.600  1490  1576 E WindowManager: updateSurfaceSize>>>>0_0
10-23 19:26:40.829  1490  1576 E WindowManager: updateSurfaceSize>>>>0_0
```

**Comment by RoniPerson** [comment] 2022-10-23 17:42
could be related to #65966

**Comment by Calinou** [comment] 2022-11-24 15:09
Duplicate of https://github.com/godotengine/godot/issues/61611.

**Closed by Calinou** 2022-11-24 15:09 UTC
Labels: bug, platform:android, topic:editor, needs testing
