### ISSUE TITLE
Anchors don't work with negatively scaled Controls

### ISSUE THREAD

**Issue by kiriri** [godotengine/godot#41221] opened 2020-08-13 09:58 UTC
**Godot version:**
3.2.2

**OS/device including version:**
Any

**Issue description:**
Resizing a parent control node doesn't resize the child correctly, if the child has negative rect_scale

**Steps to reproduce:**
(Using the example project)
Select 'Control' node and resize it (via red bubbles / Q transformation tool).
The child will behave unexpected by leaving the parent's bounds.

**Minimal reproduction project:**
[Bug_NegativeScale-Anchors.zip](https://github.com/godotengine/godot/files/5068348/Bug_NegativeScale-Anchors.zip)

**Comment by KoBeWi** [comment] 2020-08-13 11:32
This happens with any scale other than 1,1.
Duplicate of #19068

**Closed by KoBeWi** 2020-08-13 11:32 UTC
