### ISSUE TITLE
NavigationAgent gets bugged when using tilemaps, NavigationRegion and NavigationObstacles

### ISSUE THREAD

**Issue by lpares12** [godotengine/godot#72518] opened 2023-02-01 15:19 UTC
### Godot version

4.0.beta (935a6ef46b7c6af4239b6adce41b8198f051b57a)

### System information

Ubuntu 20.04.5 LTS

### Issue description

NavigationAgent in combination with NavigationRegion seems to be broken.

First of all, there is a big issue when drawing the Polygons. I constantly get this kind of shapes, where the Navigation mesh is not correctly being recomputed.
![ploygon](https://user-images.githubusercontent.com/9217676/216076277-8f84943c-bc8e-4d24-bb30-7f3c4d0621d5.png)

With the following errors in the output:
```
  scene/resources/navigation_polygon.cpp:296 - NavigationPolygon: Convex partition failed! Failed to convert outlines to a valid NavigationMesh.
  NavigationPolygon outlines can not overlap vertices or edges inside same outline or with other outlines or have any intersections.
  Add the outmost and largest outline first. To add holes inside this outline add the smaller outlines with same winding order.
```
And the following error in the debugger:
```
E 0:00:00:0560   sync: Attempted to merge a navigation mesh triangle edge with another already-merged edge. This happens when the current `cell_size` is different from the one used to generate the navigation mesh. This will cause navigation problems.
  <C++ Source>   modules/navigation/nav_map.cpp:691 @ sync()
```

So to get around this issue, I opted to do small navigationRegions and link them with a NavigationLink. And I managed to make NPCs be able to navigate from A to B and B to A. The problem is that they get stuck if they cross paths:

![stuck](https://user-images.githubusercontent.com/9217676/216077246-3bbba066-c399-411f-af64-9db3982d5282.png)

So trying to avoid that I add a NavigationObstacle2D to the NPC class (CharacterBody2D). And after running the project, the NPCs start running to the walls, Michael Jackson style:

![mj](https://user-images.githubusercontent.com/9217676/216077450-bd1f7285-c9c0-4a64-9aae-b7796f79bea6.png)

Was using Godot 4 Beta 16, but since I found this issues I updated to latest master yesterday night in the hopes of fixing them. But still same behavior.

I am not sure at what point it get broken, not sure if it's the tilemap, or what, but the smallest minimal example works. As soon as you start adding stuff it breaks. One thing I thought could be, is that once you cross one vertex of the NavigationPolygon, everything in the project related to Navigation gets messed. Which is how I believe I broke the sample project.

### Steps to reproduce

I am not sure at what point it gets broken, not sure if it's the tilemap, or some other setting, but this small sample project reproduces some of these issues.

This project is trying to spawn some CharacterBody2D and move them from one side to the other. There is a tilemap (with no navigation configured) and a NavigationRegion to mark the navigation area.

This navigation region is already broken, meaning, I made some polygons inside following the winding order and holes were not made. Also, the mesh is not being reconfigured for the top vertex (if you see, the navigation area does not include the area of the top vertex).

Another thing is that the Character has a NavigationObstacle that seems to have no effect, since no NPCs are trying to avoid themselves? And in the original project makes them walk backwards, messing with the safe_velocity.

You can play with the sample project by moving the SpawnPoints and TargetPoints. For example, moving them to the right NavigationRegion depending on which area of it, makes the spawned nodes go to IDLE mode, since they don't find the target point as reachable.

### Minimal reproduction project

[sample.zip](https://github.com/godotengine/godot/files/10558494/sample.zip)

**Comment by Zireael07** [comment] 2023-02-01 15:32
cc @smix8 although I strongly suspect there is something not being used as intended...

**Comment by smix8** [comment] 2023-02-01 18:20
TileMap is completely unrelated to this error. You should not need NavigationLink2D for this layout you are trying to create, a simple NavigationRegion2D with NavigationPolygon resource should suffice.

The debug visuals alone tell me that your NavigationPolygon or your entire scene file is completely broken for whatever reason.

The error message with the Convex Partition fail confirms it. If you get that error you need to create a new / different polygon as at that point it did not convert to a valid NavigationMesh.

I don't know what caused it that your scene got corrupted but after deleting ALL navigation related nodes and recreating them fresh the error is gone for me. Maybe you had some filesystem / UID / resource conflict, it wouldn't be the first one in beta.

I can not recreate the error on a fresh project no matter how complicate or large the navigation layout gets, except if I do something obviously wrong like crossing polygon edges or overlapping them inside the same polygon outline.

**Comment by lpares12** [comment] 2023-02-01 18:34
I see. Good to know about the tilemap.

For me, I remove the NavigationPolygons, NavigationRegion2D and the NavigationLinks. Close godot and remove the `.godot` folder (just in case). After launching again, I create 1 NavigationRegion2D and start playing with it for a while (moving points, making holes and so on) and eventually breaks:

![image](https://user-images.githubusercontent.com/9217676/216131530-ee714a6c-78ab-4989-9662-e5386666ec43.png)

And then some navigation agents start missing the target point for a lot, and never emit the `target_reached` nor `navigation_finished` events.

**Comment by lpares12** [comment] 2023-02-01 18:42
By the way, I have not used Navigation nodes before, so it's not like something got broken recently. I'm just facing this issue since a couple of days, and no idea if it was already there before. Or as you said, if the nodes are being used correctly.

**Comment by smix8** [comment] 2023-02-01 18:50
If you get the Convex Partition error when drawing the NavigationPolygon you need to change the polygon and make sure there is no overlap / intersection. You don't have to delete the resource or the NavigationRegion2D node under normal circumstance.

**Comment by lpares12** [comment] 2023-02-01 19:01
I see, thanks for the answer. Then either I misunderstood or the last image I posted shows an issue, right? I don't see any intersections or overlaps, and the middle section is not being cut. Only way to go around it is to remove the polygon resource and remake it from scratch.

**Comment by smix8** [comment] 2023-02-01 19:11
Well that the entire drawing with all NavigationRegion2D was bugged was a project issue, something corrupted and I was only able to fix it in your project by removing all navigation related nodes and starting over. I can confirm that after doing that I can recreate your navigation layout without any issues using multiple NavigationRegion2D and polygons.

If you did that and now with a fresh single NavigationRegion2D and fresh NavigationPolygon resource still have this error it might be caused by the mentioned overlap / intersection or that the Editor 2D polygon draw tool can not figure out the outlines. That a single polygon gets the Convex Partition error can happen in rare cases due to how the outline vertices are placed and how the draw tool tries to figure out what is outside and what is inside. The Editor 2D polygon draw tool has some problems with detecting outlines when there are holes in the polygon and the vertices are placed in a way that if you draw a virtual straight line from an outside vertex to and inside vertex it crosses another vertex. You can fix this by moving the middle vertex a little so it does not stay directly on the virtual line between the other two vertices.

**Comment by Zireael07** [comment] 2023-02-01 19:45
> or instead of battling with holes have mutliple NavigationRegion2D with different NavigationPolygon, if you align their edges they will be merged by the NavigationServer.

Personally this is the way I'd go (speaking as someone whose dearest wish for a long time was merging multiple navregions)

**Comment by lpares12** [comment] 2023-02-02 07:29
Understood. So I'll try to keep lots of small polygons intersecting each other as you said, in case I need to remove one I can just remake it quick.

As for the NavigationObstacle, is it that I'm using it wrong somehow? Are NPCs with NavigationAgents not supposed to have a NavigationObstacle? If not, why do they crash, even though there is enough space for them to pass next to each other? I thought enabling Avoidance would also take into account other NavigationAgents.

**Comment by Zireael07** [comment] 2023-02-02 08:51
Agents and Obstacles are two different things. Agents will avoid other Agents w/o needing to be an Obstacle. So yes, it's possible it's crashing due to not being used as expected

**Comment by lpares12** [comment] 2023-02-02 10:13
Thank you, quite clearer now. So from the original issue I think there might be two problems:

1. This bug where the NavigationPolygon gets broken and must be removed.
2. NavigationAgents (sometimes) not really avoiding each other, even when they have a big mesh to walk to.

For number 2 I'm not so sure, but I wonder why they sometimes crash into each other, instead of avoiding, when they still have some space. And not sure this is reproduced in the sample code though.

**Comment by smix8** [comment] 2023-02-02 10:54
In current Godot 4 NavigationAgent and NavigationObstacle both create a NavAgent used in avoidance on the NavigationServer. They are basically the same thing just with different properties so by attaching an obstacle on top of your agent you are basically making the agent avoid itself in an impossible situation which can only result breaking the avoidance simulation. The current Godot 4 avoidance is also very broken so I would not really recommend using it until the rework in Godot 4.1 as it can bug out by itself without you doing anything wrong.

**Comment by smix8** [comment] 2023-02-09 14:56
I think this issue can be closed.

The main source of the bugs was the triple input of the Editor Plugin that added to many vertices and that was fixed recently.

All the other setup complication were explained.

**Comment by lpares12** [comment] 2023-02-09 15:17
Maybe it's better to keep track of this bug that makes the NavigationPolygon break? Or if an issue already exists, could you link it here so I can keep track of it for my project? (I couldn't find anything like that myself)

**Comment by smix8** [comment] 2023-02-09 18:15
The "Convex partition failed!" error is common error shared and tracked with older issues or very recent like e.g. https://github.com/godotengine/godot/issues/70823.

The pr https://github.com/godotengine/godot/pull/70724 should include a proper fix for that, currently not visible in the pr but included in a development branch to update it.

We can keep this issue here open and wait until it is merged / confirmed that the pr fixes this issue here as well.

**Comment by akien-mga** [comment] 2023-02-22 14:03
Closing as per above discussion.

**Closed by akien-mga** 2023-02-22 14:03 UTC
Labels: bug, discussion, topic:navigation, topic:2d
