### ISSUE TITLE
Particles system jitters back & forth when pausing the `SceneTree` if `Engine.time_scale != 1.0`

### ISSUE THREAD

**Issue by razcore-rad** [godotengine/godot#76056] opened 2023-04-14 11:45 UTC
### Godot version

v4.0.2.stable.official [7a0977ce2]

### System information

Ubuntu 22.10, Vulkan, NVIDIA GeForce RTX™ 2060 / NVIDIA GeForce RTX™ 2060

### Issue description

The title is self-explanatory, but here's a screen capture code & motion artifacts as well:

[Screencast from 2023-04-14 14-37-44.webm](https://user-images.githubusercontent.com/1177508/232034523-605c43f9-8fd5-468d-b32c-529b91420824.webm)

### Steps to reproduce

```gd
Engine.time_scale = ts # where `ts != 1.0`
get_tree().paused = true
```

Through some experimentation I found that setting `Engine.time_scale = 1.0` before setting `get_tree().paused = true` is a workaround for this edge case.

### Minimal reproduction project

[godot-4-dbg.zip](https://github.com/godotengine/godot/files/11232371/godot-4-dbg.zip)

**Comment by MikeFrom** [comment] 2023-04-14 13:09
when you want pause (particle) shaders, I think you have to set **Engine.time_scale = 0.0** in you pause mode.

**Comment by Calinou** [comment] 2023-04-14 16:41
- Duplicate of https://github.com/godotengine/godot/issues/50824.

**Closed by Calinou** 2023-04-14 16:41 UTC
