### ISSUE TITLE
Godot 4 alpha 9: UI panels lose focus. Also properties panel does not focus correctly when pressing TAB

### ISSUE THREAD

**Issue by jcarlosrc** [godotengine/godot#61722] opened 2022-06-05 15:43 UTC
### Godot version

Godot 4 alpha 9

### System information

Windows 10

### Issue description

The editor UI behaves consistently wrong:

* Pressing TAB to focus at the next property value does not work. Former still remain in focus, or both get in focus, or neither of them. Pressing TAB again does work. This is difficult to capture in video.
* The 3d editor panel view loses focus. As a result gizmos do not work and can't change dimensions of the panels. Changing to another program and going back makes the editor get focus again. In the video, we can see that the focus is lost, then it gets back after using another program and went back to the Godot editor.

https://user-images.githubusercontent.com/8985409/172058639-3396dc83-7956-4ff1-ad64-3bfde20f0d6a.mp4

### Steps to reproduce

In any spatial node, try changing position values x, y and z using TAB. This is, click x, then TAB to focus on y. The focus will not change reliably.
The 3d editor focus problem appears after making come operations like adding a mesh instance.

**Comment by Calinou** [comment] 2022-06-05 15:48
Duplicate of https://github.com/godotengine/godot/issues/37723 and https://github.com/godotengine/godot/issues/58609.

**Closed by Calinou** 2022-06-05 15:48 UTC
