### ISSUE TITLE
Sprite2D in SubViewPort cannot be moved in via editor gizmo/handles

### ISSUE THREAD

**Issue by thygrrr** [godotengine/godot#84775] opened 2023-11-11 22:52 UTC
### Godot version

4.2.dev

### System information

Windows 11

### Issue description

Sprite2Ds (probably all Node2Ds) in a Subviewport cannot be moved, scaled, nor rotated via the handles/drag and drop. They can be moved via the inspector. 

https://github.com/godotengine/godot/assets/8904620/fcb62775-8fd2-4fb0-a019-20db7eb9bd29

This is regardless of viewport size.

Additionally, when moving the sprite by changing it's transform values in the inspector, the "Center Selection" hotkey doesn't center on the sprite, but instead on the viewport's origin.

https://github.com/godotengine/godot/assets/8904620/ab65d145-d75d-4738-81cb-98d285b557d1

### Steps to reproduce

1. Place sprite in subviewport (or open demo project)
2. go to 2d edit mode
3. try to move sprite with the move tool
4. observe: inability to move the sprite
5. edit the sprite's position in the inspector
6. select Sprite and press "F"(or your respective hotkey) to Center Selection
7. observe: View centers not on selection, but on viewport origin

### Minimal reproduction project

[immovable-sprites-repro.zip](https://github.com/godotengine/godot/files/13326726/immovable-sprites-repro.zip)

**Comment by Calinou** [comment] 2023-11-12 12:00
This is likely a duplicate of another issue, but I can't find it right now.

**Comment by Sauermann** [comment] 2023-11-12 20:05
Could be a duplicate of #20619.

**Comment by manuq** [comment] 2023-11-13 10:48
The explanation is in https://github.com/godotengine/godot/issues/1383#issuecomment-174334399

I think that should be added to the SubViewPort documentation. Ideally a message like "please arrange things in a separate scene and instantiate it here" should appear when the user tries to move things directly from a viewport.

**Comment by KoBeWi** [comment] 2023-12-31 14:37
Duplicate of https://github.com/godotengine/godot/issues/20619.

**Closed by KoBeWi** 2023-12-31 14:37 UTC
Labels: discussion, topic:editor, usability, topic:2d
