### ISSUE TITLE
Children Class Nodes Can't Display Parent Classes' Exports

### ISSUE THREAD

**Issue by SolarLune** [godotengine/godot#756] opened 2014-10-06 22:58 UTC
Hey, there. So basically, if you have a node that's running a script that extends a parent's script, and that parent' script exports a variable, it won't reliably display in the "child" node. It can display after reloading the scene, but disappears again after you save.

Here's a forum thread talking about the problem.

http://www.godotengine.org/forum/viewtopic.php?f=11&t=980

**Comment by akien-mga** [comment] 2015-10-31 09:37
Actually a duplicate of #582.

**Closed by akien-mga** 2015-10-31 09:37 UTC
Labels: archived
