### ISSUE TITLE
Parse error when typing dictionary with custom class forvalues, and calling method on the value

### ISSUE THREAD

**Issue by Nexusbeeyst** [godotengine/godot#98903] opened 2024-11-06 19:35 UTC
### Tested versions

4.4dev3, 4.4dev2

### System information

Godot v4.4.dev3 - Windows 10.0.22631 - Multi-window, 2 monitors - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3060 (NVIDIA; 32.0.15.6094) - AMD Ryzen 7 5800X 8-Core Processor (16 threads)

### Issue description

Parse error when attempting to call a method on a dictionary value from a different class, when the value is of a custom class type.

eg: (where component inherits node2d with no other modifications)
```gdscript
/// entity.gd
class_name Entity
extends Node2D

var components: Dictionary[int, Component] = {
	1: null,
}

/// other_node.gd
class_name OtherNode
extends Node2D

func component_method(entity: Entity) -> void:
	entity.components[1].free()
```

```
Error at (5,5)
Parser bug(please report): Could not find external parser for class "Component". (Trying to resolve class inheritance)
```	

### Steps to reproduce

Create custom class A, in class B, make a typed dictionary where the values are of A, then in class C, attempt to call any method on an accessed dictionary value.

### Minimal reproduction project (MRP)

[4.4dev3mrp.zip](https://github.com/user-attachments/files/17652129/4.4dev3mrp.zip)

**Comment by dalexeev** [comment] 2024-11-06 19:45
* Most likely a duplicate of #96881.
* Please test if #98400 fixes this.

**Comment by Nexusbeeyst** [comment] 2024-11-08 23:21
Fix worked.

**Closed** 2024-11-08 23:20 UTC
Labels: bug, topic:gdscript, needs testing
