### ISSUE TITLE
Autocomplete for Input.is_action_just_pressed adds extra characters

### ISSUE THREAD

**Issue by Tobio89** [godotengine/godot#76639] opened 2023-05-01 05:02 UTC
### Godot version

v3.4.4.stable.official [419e713a2]

### System information

MacOS Ventura 13.3.1

### Issue description

I am currently using VSCode as my code editor, since I am more familiar with it, and it supports features I am very comfortable with using, such as line selection, duplication, and moving.

The VSCode version is `1.77.3` but this issue has been happening for a long time.

When I use autocomplete on strings such as ui_accept, if I accept the autocomplete, it prints extra quote and parenthesis characters that break the string, and I have to go back and fix it.

I mostly run into this issue with Input.is_action_Just_pressed, but a similar thing happens with most string-based autocompletes.

Example:
`if Input.is_action_just_pressed(""ui_accept"("`

![image](https://user-images.githubusercontent.com/44494591/235409015-8da712b2-4002-46aa-bae7-b4e8351a0c4a.png)

### Steps to reproduce

type `if Input.is_action_just_pressed("` and then press enter or tab to accept the autocomplete.

### Minimal reproduction project

N/A

**Comment by Tobio89** [comment] 2023-05-01 05:03
If this issue was solved in the Godot 4 release, that would be good to know

**Comment by Tefatika** [comment] 2023-05-01 09:57
Hmm are you sure this isn't an issue related with VS Code and it's autocomplete feature more than Godot's editor?

**Comment by atirut-w** [comment] 2023-05-01 10:12
According to https://github.com/godotengine/godot-vscode-plugin/issues/470#issuecomment-1528784285, no

**Comment by Calinou** [comment] 2023-05-01 21:41
- Duplicate of https://github.com/godotengine/godot/issues/48436.

**Closed by Calinou** 2023-05-01 21:41 UTC
Labels: bug, topic:gdscript, topic:editor
