### ISSUE TITLE
Node is deselected when a signal is connected

### ISSUE THREAD

**Issue by Torguen** [godotengine/godot#56226] opened 2021-12-24 19:33 UTC
### Godot version

3.4.2 stable oficial

### System information

w10 64

### Issue description

You want to connect several signals from the same node.
When a signal is connected, the editor automatically switches to the script editor.
If you now go back to the "2D" editor to connect another signal. The node will have been deselected and no signals will be available (this is normal).
Then, you will have to select the node again to continue connecting more signals.

https://user-images.githubusercontent.com/19652075/147370288-1654d067-68d6-4aaa-b43b-a164a1121fbc.mp4

### Steps to reproduce

watch the video

### Minimal reproduction project

...

**Comment by KoBeWi** [comment] 2021-12-24 19:47
Duplicate of #21950

**Closed by KoBeWi** 2021-12-24 19:47 UTC
