### ISSUE TITLE
Multiple shapes disabled in objects crash the engine

### ISSUE THREAD

**Issue by Alexia-AT-Digitecnology** [godotengine/godot#17099] opened 2018-02-28 09:15 UTC
**Godot version:**
All 3.0 branches (stable/master)

**OS/device including version:**
All

**Issue description:**
When you make a Scene with some disabled shapes and instance in a main scene, the engine crashes.

**Steps to reproduce:**
- Open the Project provided as attachment
- Click on "Pool Initialize" button
- Click on ">" many times
- The engine crashes

**Minimal reproduction project:**
[RigidBenchmarkOMatic.zip](https://github.com/godotengine/godot/files/1766400/RigidBenchmarkOMatic.zip)

**My opinion:**
The disabled shapes are acting like live physic objects (not really disabled) and crashes the engine due to a lot of physics processing. It must be really disabled, like there is no shape when you click on "Disabled" property.

**Comment by ShyRed** [comment] 2018-02-28 16:57
The engine crashes because the Asteroid.tscn scene in the example project contains an active and empty CollisionPolygon2D - Shape.

Open the Asteroid.tscn scene and check the last CollisionPolygon2D. It **is set as active** and does not contain any data.

When the engine starts this results in a shape with segments etc. set to `NULL` and segment size zero. When as asteroid collides / comes close to the player, the shape is tested and an exception is thrown.

If the shape is removed or disabled, the game runs fine.

**Comment by Alexia-AT-Digitecnology** [comment] 2018-03-01 07:21
Yes, @ShyRed, it was a shape uninitialized, i removed it, but the engine must not crash for this, there needs to add a if checking in the engine code to avoid crashing. But the main problem is that the disabled shapes are treated as active. I added 2 types of asteroids, Asteroid1 with 1 active shape and many disabled shapes, and Asteroid2 with only 1 active shape. When you check on "Asteroid1" checkbox the FPS goes down to 7 fps, but if you uncheck (use Asteroid2) there is 400 fps. Disabled shapes must be treated as disabled, not enabled in the physics system.

**This is the example modified:**
[RigidBenchmarkOMatic.zip](https://github.com/godotengine/godot/files/1770205/RigidBenchmarkOMatic.zip)

**Comment by AndreaCatania** [comment] 2018-09-19 17:10
Is this problem solved? I can't reproduce it

**Comment by akien-mga** [comment] 2018-09-19 18:08
The backtrace seems similar to that in #17789 which was fixed by #18144.

**Closed by akien-mga** 2018-09-19 18:08 UTC
Labels: bug, topic:physics
