### ISSUE TITLE
Random android crash

### ISSUE THREAD

**Issue by Yekez** [godotengine/godot#47181] opened 2021-03-20 03:51 UTC
I have checked for my issue all the way everywhere. I think we have similar stuff with #46768 I will also paste my log here during crash. I was using gles3 during this log, i switched back to gles2 and i am still having it. I tried playing with message queue, i think max buffer exceeds this limit but i get no errors in the editor. I use 3.2.3. I am testing this game on multiple android devices.

Also same crash occurs on a godot games website and i have no idea why.

Here is the log:

```
2021-03-02 17:42:10.962 30935-30935/? A/DEBUG: pid: 27262, tid: 27286, name: GLThread 190622  >>> org.godotengine.castedefence <<<
2021-03-02 17:42:11.231 30935-30935/? A/DEBUG:     #00 pc 00000000010c6c80  /data/app/org.godotengine.castedefence-Q9UY2GXMyQ3X2ppRlUI8dA==/lib/arm64/libgodot_android.so
2021-03-02 17:42:11.231 30935-30935/? A/DEBUG:     #01 pc 0000000000312704  /data/app/org.godotengine.castedefence-Q9UY2GXMyQ3X2ppRlUI8dA==/lib/arm64/libgodot_android.so
2021-03-02 17:42:11.231 30935-30935/? A/DEBUG:     #02 pc 0000000001046b60  /data/app/org.godotengine.castedefence-Q9UY2GXMyQ3X2ppRlUI8dA==/lib/arm64/libgodot_android.so
2021-03-02 17:42:11.231 30935-30935/? A/DEBUG:     #03 pc 0000000001040100  /data/app/org.godotengine.castedefence-Q9UY2GXMyQ3X2ppRlUI8dA==/lib/arm64/libgodot_android.so
2021-03-02 17:42:11.231 30935-30935/? A/DEBUG:     #04 pc 000000000104034c  /data/app/org.godotengine.castedefence-Q9UY2GXMyQ3X2ppRlUI8dA==/lib/arm64/libgodot_android.so
2021-03-02 17:42:11.231 30935-30935/? A/DEBUG:     #05 pc 00000000006efa44  /data/app/org.godotengine.castedefence-Q9UY2GXMyQ3X2ppRlUI8dA==/lib/arm64/libgodot_android.so
2021-03-02 17:42:11.231 30935-30935/? A/DEBUG:     #06 pc 00000000001839fc  /data/app/org.godotengine.castedefence-Q9UY2GXMyQ3X2ppRlUI8dA==/lib/arm64/libgodot_android.so
2021-03-02 17:42:11.231 30935-30935/? A/DEBUG:     #07 pc 0000000000155434  /data/app/org.godotengine.castedefence-Q9UY2GXMyQ3X2ppRlUI8dA==/lib/arm64/libgodot_android.so (Java_org_godotengine_godot_GodotLib_step+184)
2021-03-02 17:42:11.231 30935-30935/? A/DEBUG:     #08 pc 00000000000131d0  /data/app/org.godotengine.castedefence-Q9UY2GXMyQ3X2ppRlUI8dA==/oat/arm64/base.odex (offset 0x13000) (org.godotengine.godot.GodotLib.audio [DEDUPED]+144)
2021-03-02 17:42:11.231 30935-30935/? A/DEBUG:     #09 pc 0000000000023f4c  /data/app/org.godotengine.castedefence-Q9UY2GXMyQ3X2ppRlUI8dA==/oat/arm64/base.odex (offset 0x13000) (org.godotengine.godot.GodotRenderer.onDrawFrame+92)
2021-03-02 17:42:12.205 1199-1275/? E/InputDispatcher: channel 'dc0a2db org.godotengine.castedefence/com.godot.game.GodotApp (server)' ~ Channel is unrecoverably broken and will be disposed!
2021-03-02 17:42:12.096 1199-30940/? W/ActivityManager:   Force finishing activity org.godotengine.castedefence/com.godot.game.GodotApp
2021-03-02 17:42:12.099 1199-30940/? V/WindowManager: Set focused app to: AppWindowToken{d36a996 token=Token{21b40b1 ActivityRecord{60540be u0 com.miui.home/.launcher.Launcher t1}}} old focus=AppWindowToken{3b8043a token=Token{9dc8f65 ActivityRecord{238eecf u0 org.godotengine.castedefence/com.godot.game.GodotApp t5094}}} moveFocusNow=true
2021-03-02 17:42:12.099 1199-30940/? V/WindowManager: Changing focus from Window{dc0a2db u0 org.godotengine.castedefence/com.godot.game.GodotApp} to null Callers=com.android.server.wm.WindowManagerService.setFocusedApp:2842 com.android.server.am.ActivityStack.moveToFront:1102 com.android.server.am.ActivityStackSupervisor.moveFocusableActivityStackToFrontLocked:3589 com.android.server.am.ActivityStackSupervisor.moveHomeStackTaskToTop:775 
2021-03-02 17:42:12.101 1199-1223/? I/WindowManager: Focus moving from Window{dc0a2db u0 org.godotengine.castedefence/com.godot.game.GodotApp} to null
2021-03-02 17:42:12.203 537-608/? I/BufferQueueProducer: [org.godotengine.castedefence/com.godot.game.GodotApp#0](this:0x73fef7a800,id:130758,api:1,p:27262,c:537) disconnect(P): api 1
2021-03-02 17:42:12.203 537-608/? I/BufferQueueConsumer: [org.godotengine.castedefence/com.godot.game.GodotApp#0](this:0x73fef7a800,id:130758,api:1,p:-1,c:537) getReleasedBuffers: returning mask 0xffffffffffffffff
2021-03-02 17:42:12.203 537-608/? I/BufferQueueProducer: [SurfaceView - org.godotengine.castedefence/com.godot.game.GodotApp#0](this:0x73ebf05800,id:130759,api:1,p:27262,c:537) disconnect(P): api 1
2021-03-02 17:42:12.203 537-608/? I/BufferQueueConsumer: [SurfaceView - org.godotengine.castedefence/com.godot.game.GodotApp#0](this:0x73ebf05800,id:130759,api:1,p:-1,c:537) getReleasedBuffers: returning mask 0xffffffffffffffff
2021-03-02 17:42:12.203 1199-2535/? I/ActivityManager: Process org.godotengine.castedefence (pid 27262) has died: vis  +99TOP 
2021-03-02 17:42:12.204 1199-8027/? I/WindowManager: WIN DEATH: Window{dc0a2db u0 org.godotengine.castedefence/com.godot.game.GodotApp}
2021-03-02 17:42:12.204 508-546/? I/vendor.mediatek.hardware.power@2.1-impl: notifyAppState_2_1 pack:org.godotengine.castedefence, act:org.godotengine.castedefence, pid:27262, uid:10204, state:3
2021-03-02 17:42:12.205 1199-1275/? W/InputDispatcher: channel 'dc0a2db org.godotengine.castedefence/com.godot.game.GodotApp (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
2021-03-02 17:42:12.205 1199-1275/? E/InputDispatcher: channel 'dc0a2db org.godotengine.castedefence/com.godot.game.GodotApp (server)' ~ Channel is unrecoverably broken and will be disposed!
2021-03-02 17:42:12.205 1199-8027/? W/InputDispatcher: Attempted to unregister already unregistered input channel 'dc0a2db org.godotengine.castedefence/com.godot.game.GodotApp (server)'
2021-03-02 17:42:12.211 537-993/? W/SurfaceFlinger: Attempting to set client state on removed layer: org.godotengine.castedefence/com.godot.game.GodotApp#0
2021-03-02 17:42:12.211 537-993/? W/SurfaceFlinger: Attempting to destroy on removed layer: org.godotengine.castedefence/com.godot.game.GodotApp#0
2021-03-02 17:42:12.212 537-537/? I/BufferQueueConsumer: [SurfaceView - org.godotengine.castedefence/com.godot.game.GodotApp#0](this:0x73ebf05800,id:130759,api:1,p:-1,c:-1) disconnect(C)
2021-03-02 17:42:12.214 537-537/? I/BufferQueueConsumer: [dc0a2db org.godotengine.castedefence/com.godot.game.GodotApp#0](this:0x73e7fef800,id:130757,api:0,p:-1,c:-1) disconnect(C)
2021-03-02 17:42:12.214 537-537/? I/BufferQueueConsumer: [org.godotengine.castedefence/com.godot.game.GodotApp#0](this:0x73fef7a800,id:130758,api:1,p:-1,c:-1) disconnect(C)
2021-03-02 17:42:12.214 537-993/? I/BufferQueue: [org.godotengine.castedefence/com.godot.game.GodotApp#0](this:0x73fef7a800,id:130758,api:1,p:-1,c:-1) ~BufferQueueCore
2021-03-02 17:42:12.263 537-537/? I/BufferQueueConsumer: [AppWindowToken{3b8043a token=Token{9dc8f65 ActivityRecord{238eecf u0 org.godotengine.castedefence/com.godot.game.GodotApp t5094}}}#0](this:0x73e7f95800,id:130754,api:0,p:-1,c:-1) disconnect(C)
2021-03-02 17:42:12.273 3933-19260/? I/ProcessMonitor: onForegroundInfoChanged: ForegroundInfo{mForegroundPackageName='com.miui.home', mForegroundUid=10052, mForegroundPid=1613, mLastForegroundPackageName='org.godotengine.castedefence', mLastForegroundUid=10204, mLastForegroundPid=27262, mMultiWindowForegroundPackageName='null', mMultiWindowForegroundUid=-1, mFlags=0}
2021-03-02 17:42:12.273 3933-19260/? I/GameBoosterService: onForegroundInfoChanged: Cur=com.miui.home	 last=org.godotengine.castedefence
2021-03-02 17:42:12.276 3933-19260/? D/GameBoosterService: onGameStatusChange foreground:ForegroundInfo{mForegroundPackageName='com.miui.home', mForegroundUid=10052, mForegroundPid=1613, mLastForegroundPackageName='org.godotengine.castedefence', mLastForegroundUid=10204, mLastForegroundPid=27262, mMultiWindowForegroundPackageName='null', mMultiWindowForegroundUid=-1, mFlags=0}
2021-03-02 17:42:12.703 537-537/? I/BufferQueue: [SurfaceView - org.godotengine.castedefence/com.godot.game.GodotApp#0](this:0x73ebf05800,id:130759,api:1,p:-1,c:-1) ~BufferQueueCore
2021-03-02 17:42:14.997 537-1972/? I/BufferQueue: [AppWindowToken{3b8043a token=Token{9dc8f65 ActivityRecord{238eecf u0 org.godotengine.castedefence/com.godot.game.GodotApp t5094}}}#0](this:0x73e7f95800,id:130754,api:0,p:-1,c:-1) ~BufferQueueCore
2021-03-02 17:42:14.997 537-1972/? I/BufferQueue: [dc0a2db org.godotengine.castedefence/com.godot.game.GodotApp#0](this:0x73e7fef800,id:130757,api:0,p:-1,c:-1) ~BufferQueueCore
2021-03-02 17:43:44.880 31721-31739/? D/LR-AppUsageStatsFactory: loadTodayTotalTimeForPackage()......pkgName=org.godotengine.castedefence
```

**Comment by Calinou** [comment] 2021-03-20 13:58
I'll close this since we can't do anything without a minimal reproduction project. The backtrace isn't useful as it doesn't contain debug symbols.

**Closed by Calinou** 2021-03-20 13:58 UTC

**Comment by Yekez** [comment] 2021-03-21 15:38
yeah it was definately a danglish variant type of stuff. i fixed it by removing reasigning freed object variable.

**Comment by avnerh1** [comment] 2021-07-09 18:20
> I'll close this since we can't do anything without a minimal reproduction project. The backtrace isn't useful as it doesn't contain debug symbols.
> 

@Calinou What is the way to create debug symbols? I've been researching it for a few days and couldn't make it happen.
