### ISSUE TITLE
idle time peaks for 1 frame roughly 30 seconds after game starts

### ISSUE THREAD

**Issue by Libbae** [godotengine/godot#38815] opened 2020-05-18 01:43 UTC
**Godot version:**
3.2.1.stable

**OS/device including version:**
windows 10

**Issue description:**
idle time peaks for 1 frame roughly 30 seconds after game starts (image below is 144 fps)
![image](https://i.imgur.com/rq9VRhe.png)

the only solution ive found is to set the "force fps" debug setting to at least 1 frame lower than my monitors refresh rate (so 143 or less is fine). doing that makes it so there isnt even a little spike.

heres an (unresolved) reddit thread i found that had the same issue: https://www.reddit.com/r/godot/comments/bhq5ah/idle_time_peaks_some_seconds_after_game_starts/

**Steps to reproduce:**
hit play and wait 30 seconds

**Minimal reproduction project:**
any project in my testing (including brand new blank ones)

**Comment by clayjohn** [comment] 2020-05-18 01:51
Looks to be the same as https://github.com/godotengine/godot/issues/33969

**Comment by Calinou** [comment] 2020-05-18 07:20
Duplicate of #33969.

**Closed by Calinou** 2020-05-18 07:20 UTC
