### ISSUE TITLE
SpinBox (editor and in-game) division expression don't return float unless float is used in expression

### ISSUE THREAD

**Issue by NatGazer** [godotengine/godot#87420] opened 2024-01-20 20:27 UTC
### Tested versions

v4.2.1.stable.official

### System information

Windows 10 - Vulkan (Forward+)

### Issue description

Better explained with the example below (Steps to Reproduce)

### Steps to reproduce

1º - Add a SpinBox
2º - Set step to 0.01 or lower

**Try these inputs and then press Enter**

Input: "7/8"       Expected: "0.88"       Got: "0"
Input: "7.0/8"       Expected: "0.88"       Got: "0.88"

**For example, with trigonometric expressions, it works well:**

Input: "sin(1)"       Expected: "0.84"       Got: "0.84"

This is true for in-game SpinBoxes:
![image](https://github.com/godotengine/godot/assets/67602607/7a81a1af-d474-43c6-ab39-ed7f9cb2aa13)
And for editor SpinBoxes:
![image](https://github.com/godotengine/godot/assets/67602607/e436fcbb-057e-4944-8d71-5ef53e4bf411)

I know, I know, in programming, the division of two integers is and integer. But I believe it is much more convenient if Godot number input boxes (SpinBox) provides a decimal point number whenever an integer division is made. For example, if I want the scale of a Node3D to be exactly 1/3, I would have to write 1.0/3 which doesn't look very friendly for new users and even for the UI made for the game.

I hope this is a simple change like replacing "n/d" with "float(n)/d" but I don't actually know what I'm talking about. Anyway I hope this is a simple fix since this is really important for the project I'm working on.

### Minimal reproduction project (MRP)

N/A

**Comment by Zireael07** [comment] 2024-01-21 09:50
Already reported and by design I believe

**Comment by AThousandShips** [comment] 2024-01-21 09:59
See:
* https://github.com/godotengine/godot-proposals/issues/6281
* https://github.com/godotengine/godot-proposals/issues/5344
* https://github.com/godotengine/godot-proposals/issues/1888

This is by design and general convention, see those proposals, closing this as it's not a bug and already discussed elsewhere

**Closed by AThousandShips** 2024-01-21 09:59 UTC
