### ISSUE TITLE
Custom node types can't add a script via the Add A Script button.

### ISSUE THREAD

**Issue by willnationsdev** [godotengine/godot#10952] opened 2017-09-04 01:27 UTC
Specifically in Godot 2.1.4, when you add a custom node type to the node hierarchy, it will have it's script already attached. If you then remove that script by clicking on the trash can icon, you would expect the trash can to change to the Add A Script button, but it doesn't. Consequently, you can only add a script to a custom node type by directly editing the attached script value in the Inspector.

![2017-09-03 1](https://user-images.githubusercontent.com/16217563/30008543-3af7b6f2-90e6-11e7-9805-72f5828b36d4.png)

![2017-09-03 4](https://user-images.githubusercontent.com/16217563/30008545-3ebb5956-90e6-11e7-8c26-1d5a4d7ae942.png)

![2017-09-03 5](https://user-images.githubusercontent.com/16217563/30008546-425bfcb4-90e6-11e7-9dba-cbd11594407e.png)

**Comment by Zylann** [comment] 2017-09-04 01:47
Note: custom node types can't have a script attached to them other than the script defined by its plugin, because any object in Godot can have only 1 script. If you remove the script from the custom node, the node isn't custom anymore and should revert to its base node type.

**Comment by eon-s** [comment] 2017-09-04 02:27
I think this is the intended behaviour of custom nodes.

Some of your options are making the main logic in a loaded script, on a children of the custom node or extend the script with the logic so the custom node have a "clean" script.

**Comment by willnationsdev** [comment] 2017-09-04 03:51
Oh, I didn't realize that without the script, the custom type would cease to be custom...my mistake. I'll close this issue then. Thanks.

**Comment by willnationsdev** [comment] 2017-09-04 04:35
Upon re-examination, it would seem that this actually IS still a bug. I've tested that you can remove the custom node's script, reload it with a different script that extends the custom script, and it will still work properly, so you definitely CAN still use scripts other than the one defined by the plugin.

However, that's beside the point in this case. The trash can icon doesn't update when you remove the initially provided script. This makes it more difficult to add a new script that extends the plugin's script when it is removed. It's a usability issue. Perhaps clicking on the add a script button when selecting a custom node would have it inherit the custom script automatically as well?

**Comment by akien-mga** [comment] 2018-01-15 10:35
Is this still reproducible in Godot 3.0 RC1?

**Comment by willnationsdev** [comment] 2018-01-15 12:36
I will be able to check this in about two hours

**Comment by DualMatrix** [comment] 2018-09-16 16:33
This is fixed in master

**Comment by akien-mga** [comment] 2018-09-17 09:26
Thanks, closing as fixed in 3.1 then. At this stage only critical bug fixes will still be considered for the 2.1 branch.

**Closed by akien-mga** 2018-09-17 09:26 UTC
Labels: bug, topic:editor, usability
