### ISSUE TITLE
Godot Graphics Issue Win11 Nvdia GeForce RTX3060

### ISSUE THREAD

**Issue by hobik** [godotengine/godot#76102] opened 2023-04-15 21:18 UTC
### Godot version

3.5.2 and 4.0 both of them

### System information

Windows 11 Nvdia GeForce Rtx3060

### Issue description

I've some graphics problem when I use the Nvdia GeForce RTX3060 Graphics card to open Godot Editor. When I open with this, ide resolution and game resolution is very bad I see lots of pixels.
I also try open with these command --editor --video-driver GLES2 but it does not work.
When I switch to Graphics Card Nvdia 3060 to Intel Iris xe from Graphcs Settings in windows, then I open the Godot Editor, it looks everything perfect.

I'm using windows 11, also I try with Godot 4 and Godot 3 (LTS) version I get same result both of them.

Why I cant use Godot Ide with Nvdia GeForce Rtx 3060 Graphics Card ? My laptop brandnew so maybe I need some settings to open with this.
This is nvdia driver versions I think last version:
![image](https://user-images.githubusercontent.com/20272153/232253557-21e049d8-9090-4b82-bdba-e6e0178e3158.png)
### Steps to reproduce

I also try open with these command --editor --video-driver GLES2 but it does not work.

### Minimal reproduction project

I also try open with these command --editor --video-driver GLES2 but it does not work.

![image](https://user-images.githubusercontent.com/20272153/232253533-2ddcfcb6-d1da-484e-b2f9-9e56c823d0e8.png)
![image](https://user-images.githubusercontent.com/20272153/232253541-f71c0cd2-6a8f-403e-a946-18983243c135.png)

**Comment by Calinou** [comment] 2023-04-15 21:45
Can you take screenshots of the editor when it runs on the NVIDIA graphics card?

**Comment by hobik** [comment] 2023-04-15 21:58
> Can you take screenshots of the editor when it runs on the NVIDIA graphics card (in both 3.5.2 and 4.0.2)?

If I take screenshoot, image looks good but the editor not showing good quality with nvdia rtx 3060 card.

**Comment by Calinou** [comment] 2023-04-15 22:11
> If I take screenshoot, image looks good i think image resolution corrected some how. but the editor not showing good quality with nvdia rtx 3060 card.

Can you take a photo of the screen using a camera then?

**Comment by clayjohn** [comment] 2023-04-16 02:57
It may be a monitor issue if the issue isn't present in screenshots.

**Comment by hobik** [comment] 2023-04-16 04:56
> It may be a monitor issue if the issue isn't present in screenshots.

But when I switch the Intel iris xe graphics card it looks very good. My problem is nvdia

**Comment by hobik** [comment] 2023-04-16 19:28
This is Inter Irıs Xe Graphics result:
![Screenshot 2023-04-16 222524_2](https://user-images.githubusercontent.com/20272153/232337322-c7df4425-f218-4f25-acfb-d3083f7813a2.png)
![image](https://user-images.githubusercontent.com/20272153/232337339-265876c6-fd88-4903-a009-5702c5709881.png)
This is Nvdia Rtx3060 results:
![Screenshot 2023-04-16 222524](https://user-images.githubusercontent.com/20272153/232337360-4439e8c4-4e19-49fe-bf54-a6b9d2a139d8.png)
![image](https://user-images.githubusercontent.com/20272153/232337391-c2eec52a-c208-4acb-bb65-0b55afed3544.png)

**Comment by lawnjelly** [comment] 2023-04-16 19:47
Just trying to guess what you mean from the screenshots, they look very similar.

Could be a color management issue with the OS / Monitor / GPU driver. I'm not sure we do anything our side in this regard, we just output sRGB afaik. But OS often will try and color correct according to the monitor profile, maybe this is occurring differently for the two GPUs. This would tie in with the screenshot looking the same.

Another possibility is some slight difference in the filtering due to small differences in the full screen quad, but on balance I'd be suspecting color management.

**Comment by Calinou** [comment] 2023-04-16 22:11
This is caused by your NVIDIA graphics driver being told to sharpen the image, which affects all applications using a 3D rendering API to render their UI (be it OpenGL or Vulkan). You can disable this behavior in the NVIDIA Control Panel.

**Comment by hobik** [comment] 2023-04-18 19:23
> This is due to the same cause as #68053: sharpening forced by the graphics driver.
> 
> Looking at the screenshots, this is caused by your NVIDIA graphics driver being told to sharpen the image, which affects all applications using a 3D rendering API to render their UI (be it OpenGL or Vulkan). You can disable this behavior in the NVIDIA Control Panel. If you don't know how to do this, perform a full clean reinstall of the NVIDIA drivers, which should reinitialize all settings to their default.
> 
> Unfortunately, some OEMs like to enable sharpening by default even when it's not necessary and undesired. AMD is guilty of this too, but I didn't know some NVIDIA laptops even shipped with sharpening enabled by default.

Thank you very much when I configure Sharpen Off, everything looks good now. 
![image](https://user-images.githubusercontent.com/20272153/232883489-c9e6c531-497d-4ee3-8436-5051bb2c6adb.png)

**Comment by clayjohn** [comment] 2023-04-18 19:30
Oof, I had the same issue with my radeon graphics card. I went months thinking that someone had broken text rendering in Godot 4 before I realized that the Radeon graphics settings were applying sharpen to every single Vulkan application. 

I'm going to go ahead and close this as the issue is resolved and there is no action we can take on our end.

**Closed by clayjohn** 2023-04-18 19:30 UTC
Labels: platform:windows, archived, topic:rendering, topic:thirdparty
