### ISSUE TITLE
Duplicating a resource (CTRL+D) also duplicates the resource UID

### ISSUE THREAD

**Issue by mbrlabs** [godotengine/godot#57220] opened 2022-01-25 18:27 UTC
### Godot version

4.0 alpha1

### System information

Windows 11

### Issue description

Exported materials will not get saved correctly. They always reset when the scene is reopened. This does not happen when exporting primitive types or other resources like textures as far as i can tell.

https://user-images.githubusercontent.com/8750135/151036276-378b4eea-50f6-45ac-9adb-c3ba16e769d4.mp4

### Steps to reproduce

Make a script and export a material like this

````gdscript
@export var material: BaseMaterial3D
````

Add this to a node and assign a material. Then save the scene, close it and reopen it. Do this a couple of times and this happens.

### Minimal reproduction project

[ExportMaterialBug.zip](https://github.com/godotengine/godot/files/7936170/ExportMaterialBug.zip)

**Comment by mbrlabs** [comment] 2022-01-25 19:37
Ok, this is weird. This is also happening with built in nodes. Like when you assign a material to a MeshInstance via material override. 
https://user-images.githubusercontent.com/8750135/151046655-d5a4e74b-bd7e-4453-b003-b91a7e0f7a4c.mp4

**Comment by mbrlabs** [comment] 2022-01-25 19:40
I got it. I duplicated the materials and they have the same UUID now, so it's just always picking the same after reopening.

**Comment by akien-mga** [comment] 2022-01-25 19:50
This is listed in the known issues for 4.0 alpha 1 :)

Duplicate of #54774

**Closed by akien-mga** 2022-01-25 19:50 UTC
Labels: bug, topic:editor, regression
