### ISSUE TITLE
Unable to load .fnt fonts (error: "not a resource")

### ISSUE THREAD

**Issue by alexwbc** [godotengine/godot#8932] opened 2017-05-26 15:28 UTC
**Operating system or device - Godot version:**
Ubuntu 17.04 - Godot 98a329670227c726a5d7a196e5cba8dbdd54301b and later

**Issue description:**
Godot is unable to load .fnt fonts anymore

**Steps to reproduce:**
- Create a text node (such as "Label")
- Attempt to  load a .fnt file previously working on 9079ef46e72bc9738659a7399e4574e3ae186b38 and older commit)
- Godot refuse to load font (not a resource), node that had previously font loaded can't be loaded with fonts (which need to be removed)

**Link to minimal example project:**
[newpro.zip](https://github.com/godotengine/godot/files/1032292/newpro.zip)
this project loads fine in 9079ef46e72bc9738659a7399e4574e3ae186b38 but not in 98a329670227c726a5d7a196e5cba8dbdd54301b and later commits

**Comment by Noshyaar** [comment] 2017-10-22 06:21
#9610 probably is a duplicate of this. It's fixed by #11869.

**Closed** 2017-10-22 06:21 UTC
Labels: archived, bug, topic:core
