### ISSUE TITLE
No errors in threads

### ISSUE THREAD

**Issue by AlexHolly** [godotengine/godot#12358] opened 2017-10-23 17:52 UTC
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Godot master
Kubuntu 17.04

No error, no output
```
extends Node


func _ready():
	var thread = Thread.new()
	thread.start(self, "run_bg", null)
	

func get_d():
	return {}

func run_bg(value):
	
	var d = get_d()
	
	if d==-1:
		print("is -1")
	
	print("is dict")
```

Expected 
![image](https://user-images.githubusercontent.com/4741886/31904405-7048881a-b82b-11e7-9be9-fb4269c42c1a.png)

```
extends Node


func _ready():
	var d = get_d()
	
	if d==-1:
		print("is -1")
	
	print("is dict")

func get_d():
	return {}
```

Edit: Looks like it is happening with all errors inside a thread. I can see the errors in the terminal but not in the editor.

**Comment by bojidar-bg** [comment] 2017-11-08 20:35
Ping @hpvb, might be related to your recent-ish changes 😃

**Comment by bojidar-bg** [comment] 2017-11-08 20:44
Duplicate of #2446, as per https://github.com/godotengine/godot/issues/2446#issuecomment-299712137

**Closed by bojidar-bg** 2017-11-08 20:44 UTC
Labels: bug, topic:gdscript
