### ISSUE TITLE
folders sometimes appearing twice in the editor

### ISSUE THREAD

**Issue by ababen1** [godotengine/godot#66429] opened 2022-09-26 07:53 UTC
### Godot version

v4.0.beta1.official [20d667284]

### System information

Windows 11, GLES3, NVIDIA GeForce GTX 1650, i5-11300H

### Issue description

For example, the folder "UI" is appearing twice here, with different casing, but the content is identical on both folders. When I right click and press "open in file explorer", it leads to the same folder.
![image](https://user-images.githubusercontent.com/80917990/192221126-12ec3363-7561-4d02-a562-a1fd0d46e671.png)
here is the actual src folder, which has only one UI dir:
![image](https://user-images.githubusercontent.com/80917990/192221444-2f44b124-c04b-43c8-ab2b-df6849c556ca.png)

### Steps to reproduce

I'm not sure what causes this to happen, but last time it triggered it was right after i changed a line of code from
`@export var text: String : set = set_text`
to
`@export var text: String : set = set_text`

The issue fixes itself when I reopen the editor

edit: Ok I just noticed it happening again, this time I didn't even change any code or scenes, I just pressed control S to save and poof, a double folder

**Comment by kmadridr** [comment] 2022-09-28 04:29
I tried to reproduce it with Windows 11 and creating the same folder structure and I got no luck.

**Comment by ababen1** [comment] 2022-09-28 06:29
> I tried to reproduce it with Windows 11 and creating the same folder structure and I got no luck.

Maybe try creating the folders through windows and not through godot? I did copy some files from a different project so i did that. maybe it caused it?

**Comment by ababen1** [comment] 2022-09-29 08:35
could someone help me with this? I can't use `class_name` because of this problem (it detects it twice)
I can share my project with whoever is willing to help but i'd rather not post it here publicly

**Comment by YuriSizov** [comment] 2023-01-03 12:48
Duplicate of https://github.com/godotengine/godot/issues/22475.

**Closed by YuriSizov** 2023-01-03 12:48 UTC
Labels: bug, topic:editor, needs testing
