### ISSUE TITLE
Sony DS4 controler detected as peripheral #1 instead of #0 on Linux Mint (with only one controler connected)

### ISSUE THREAD

**Issue by xenicle** [godotengine/godot#41933] opened 2020-09-10 02:36 UTC
**Godot version:**
Steam Godot v3.2.2.stable.official

**OS/device including version:**
Linux Mint 20 - Sony DS4 Controller (with official Usb/BT dongle)

**Issue description:**
In my Game I have two player "Player one" linked with actions on peripheral #0 and "Player two" on peripheral #1. On Linux mint with only my DS4 connected it's the Player2 who respond to commands. (have verified with jstest-gtk there is only one controller...

**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by xenicle** [comment] 2020-09-10 04:30
I've tested with https://github.com/godotengine/godot-demo-projects/tree/master/misc/joypads and the DS4 is detected two times one time in device 0 (but the values move strangely when I move the controller like if it take the sisaxis sensor) and in device 1 it got the right controller. with good values.

**Comment by MrJustreborn** [comment] 2021-05-08 09:23
I've got the same problem on Manjaro using the DS4-Controller paired via bluetooth.
The device 0 seems to be the sixaxis sensor and device 1 are the correct inputs.

I only see one js in /dev/input

**Comment by akien-mga** [comment] 2022-01-11 10:31
Duplicate of #50273 (newer but with more details).

**Closed by akien-mga** 2022-01-11 10:31 UTC
Labels: bug, platform:linuxbsd, confirmed, topic:input
