### ISSUE TITLE
Shader editor focus grabbing error

### ISSUE THREAD

**Issue by aleksandrbazhin** [godotengine/godot#43976] opened 2020-11-30 04:22 UTC
https://github.com/godotengine/godot/issues/2087 here it was fixed for Ctrl+Z, Ctrl+Shift+Z
But the problem remains with Ctrl+K, Ctrl+D, and maybe some others.

**Godot version:**

3.2.3, 3.2.4 beta 3

**OS/device including version:**

Windows, Nvidia gf1060, GLES2

**Issue description:**

When script and shader editor are both open, Ctrl+K (comment section) always works only for shader editor, even if the script editor is focused. Ctrl+Z (undo) on the other hand works in the currently focused editor. So if you want to comment and then undo, you'll have everything messed up.
Same goes with Ctrl+D (duplicate line) but works properly for Ctrl+Z, Ctrl+Shift+Z, Ctrl+C, Ctrl+V, Ctlr+X .

**Steps to reproduce:**
Open script and shader editors. Focus on script one, press Ctrl+K, comments will appear in the currently not focused shader editor.

**Minimal reproduction project:**

Absolutely any project, tested in empty new ones.

Another, maybe connected to focus grab, issue is - after I have opened the shader editor, half of the time when I try to launch the project, (F5 or GUI button) project list is launched without closing current project. This behavior is not reproduced on new projects, though, but is super annoying.

**Comment by Chaosus** [comment] 2020-11-30 08:11
Seems like a duplicate of https://github.com/godotengine/godot/issues/17591 - not sure why that issue was closed - @akien-mga ?

**Comment by Chaosus** [comment] 2020-11-30 08:12
Ah, nvm it should be fixed by https://github.com/godotengine/godot/pull/42109

**Comment by akien-mga** [comment] 2020-11-30 08:53
Duplicate of #17591, fixed by #42109.

**Closed by akien-mga** 2020-11-30 08:53 UTC
