### ISSUE TITLE
Running the game right after working in external editor overrides changes in files

### ISSUE THREAD

**Issue by PLyczkowski** [godotengine/godot#31771] opened 2019-08-29 16:26 UTC
**Godot version:**
![image](https://user-images.githubusercontent.com/7307968/63958084-f28a7000-ca89-11e9-8b06-70cda9be91d1.png)

**OS/device including version:**
Windows 10 64

**Issue description:**
Running the game right after working in external editor overrides changes in files

**Steps to reproduce:**
Have big project. Have Godot editor open. Work on scripts in external editor. Switch to editor and run game. Work from external editor gets overridden by last version that editor had.

My guess is that the editor runs the game before all the file reads/script updates are completed. The issue started appearing recently, my guess is that the project has to get big enough for the delay to cause this.

**Comment by Zylann** [comment] 2019-08-29 16:50
Are you sure it's not rather due to the fact Godot saves everything before it runs the game, and what it had in memory didn't get reloaded fron disk?

**Comment by PLyczkowski** [comment] 2019-08-29 17:03
> Are you sure it's not rather due to the fact Godot saves everything before it runs the game, and what it had in memory didn't get reloaded fron disk? (causing it to save back old data).

I'm sure what you described is what happens. But only recently scripts started sometimes failing to be reloaded from disk before the game runs. My guess is that sometimes I click play too fast and they fail to be reloaded on time before the game runs, especially with a big project?

Editor checking that everything is correctly reloaded before saving stuff again when running the game would solve this I guess.

**Comment by rainbyte** [comment] 2020-02-03 05:00
I have also found this issue today. After fetching changes from git repo, Godot ignores some of them and tries to override them with an old version. 

Restarting Godot multiple times was needed to workaround this issue, because sometimes it tried to override the files again.

Even after `git reset --hard origin/master` the files were changed again and again, and code was broken without notice.

Maybe this is related to [issue #32243](https://github.com/godotengine/godot/issues/32243)

**Comment by Calinou** [comment] 2020-04-29 12:37
I suppose this can be alleviated by disabling **Run > Auto Save > Save Before Running** in the Editor Settings. I'm not sure if this can be fixed while preserving the current behavior (which is good, as it spares your <kbd>Ctrl + S</kbd> key).

**Comment by rainbyte** [comment] 2020-05-03 10:14
> I suppose this can be alleviated by disabling **Run > Auto Save > Save Before Running** in the Editor Settings. I'm not sure if this can be fixed while preserving the current behavior (which I think is good, as it spares your Ctrl + S key).

Maybe (auto)save should check if files were modified outside instead of overriding everything.

**Comment by Calinou** [comment] 2020-10-02 15:26
Duplicate of https://github.com/godotengine/godot/issues/20250.

**Closed by Calinou** 2020-10-02 15:26 UTC
Labels: bug, confirmed, topic:editor
