### ISSUE TITLE
[FBX] Arm bone and leg is has broken xform

### ISSUE THREAD

**Issue by mbrlabs** [godotengine/godot#43688] opened 2020-11-19 13:51 UTC
**Godot version:**
3.2.4 beta2

**OS/device including version:**
Windows 10

**Issue description:**
Arms and feet are distorted in 3.2.4. The scythe mesh is also positioned wrongly (probably because of the wrong arm position) but at least its visible as opposed to the 3.2.3 importer ;) The animations worked fine.
I used this model: https://sketchfab.com/3d-models/ruby-rose-2270ee59d38e409491a76451f6c6ef80

I have also tested other rigged meshes with similar results, but i don't think it's worth opening different issues for these things all the time, because the root problem might be the same. Should we open some kind of tracker issue for FBX models who failed to import correctly? @RevoluPowered 

3.2.3:
![3 2 3](https://user-images.githubusercontent.com/8750135/99673309-e3b82080-2a74-11eb-9c04-09998657b6fc.PNG)

3.2.4 beta2:
![3 2 4](https://user-images.githubusercontent.com/8750135/99673326-e9ae0180-2a74-11eb-8ef1-73a8a57ab8ec.PNG)

**Comment by RevoluPowered** [comment] 2020-11-20 14:07
OK so the problem with loading a random model from sketchfab is that I really need to know a lot of info about how the rig was made, what specific parts break.

Otherwise it will take many more hours to debug each model which is reported.

Please post the verbose log output run the editor with -v and open project with command line, when you re-import the file on the ticket and I can look into it further with the log which is required. Importer often reports errors in the verbose log output and it's more useful.

**Comment by RevoluPowered** [comment] 2020-11-20 14:08
If the rig previously worked then it will be related to an upstream issue in blender, because they use the assimp way of skinning FBX which is the incorrect algorithm for the FBX SDK.

**Comment by akien-mga** [comment] 2020-11-20 14:33
[ruby-rose.txt](https://github.com/godotengine/godot/files/5574130/ruby-rose.txt)

Here's the log. 7 MB.

**Comment by mbrlabs** [comment] 2020-11-20 14:33
I'm not sure of course since the artist did not state it in the description of the model, but i think it's done in Maya based on the comments and his previous work.

The verbose output is huge, so here is the 14MB text file: [fbx-import.log](https://github.com/godotengine/godot/files/5574117/fbx-import.log)

**Comment by RevoluPowered** [comment] 2020-11-20 14:51
OK the problem is the file was made in 3DS Max.

It has geometric pivots in the file which we don't have added into the formulas for pivots. I can add it but we need to validate it again and also have 3DS max available.

**Comment by norrath-hero** [comment] 2020-11-20 16:37
My models broken too

Is this possible to develop a tool like https://github.com/facebookincubator/FBX2glTF but for Godot's tscn format?

why so insist refuse to use the official FBX SDK?

**Comment by akien-mga** [comment] 2020-11-20 16:44
@norrath-hero Please open a new issue with your models attached and information on their provenance, how you exported them to FBX, etc.

One bug == one issue. Until proven otherwise, different meshes failing to import are not necessarily the same bug.

**Comment by RevoluPowered** [comment] 2020-11-30 15:50
bind poses here are fixed, one bug left in euler to quaternion code to make arm not go through the back of the character

**Comment by akien-mga** [comment] 2022-04-06 22:21
This is probably fixed with the new FBX importer using [FBX2glTF](https://github.com/V-Sekai/FBX2glTF/releases).
You can test it in Godot 4.0 alpha 6: https://godotengine.org/article/dev-snapshot-godot-4-0-alpha-6
This new importer might also be backported for the `3.x` branch eventually.

If you still find issues with these models using the new importer, we suggest opening a new issue with details about the problems in Godot 4.0 alpha 6 or later.

**Closed by akien-mga** 2022-04-06 22:21 UTC
Labels: bug, topic:import, regression
