### ISSUE TITLE
Array PackedScene Crash

### ISSUE THREAD

**Issue by ikicapitan** [godotengine/godot#27397] opened 2019-03-25 06:54 UTC
Godot version:
3.1

OS / device including version:
Windows 7 Ultimate, GeForce GTX 1050, i7-7700

Issue description:
I created via GDScript an "export" Array, to which I added a saved scene (PackedScene) to instantiate it, but I could not even run the program because it closed automatically ... even though I did not try to instantiate the scene, I just added it to the array list.
As an extra consequence, the project completely corrupted the scene set as a reference in the Array, and can not be opened again and has to be completely eliminated in order to re-establish the functioning of the project.

Steps to play:

Create a Node
Add a GDScript
Create an export (Array)
From the Inspector give him the value 1
Load a saved scene as PackedScene
Execute the Project

Minimal reproduction project:
[Pokemon Red.zip](https://github.com/godotengine/godot/files/3001884/Pokemon.Red.zip)

_Bugsquad edit: previous issue in spanish #27336_

**Comment by groud** [comment] 2019-03-25 10:28
Thanks for showing good willing, that's appreciated. :) I'll edit you post and link the previous issue just in case.

Note that regarding the language, it seems like contributors agreed on twitter to allow having both languages in the issue (English first and with English title, to simplify searching). That might help in case of a low quality automatic translation.

**Comment by bojidar-bg** [comment] 2019-03-25 10:49
Refs #24384.

**Comment by KoBeWi** [comment] 2019-11-30 11:12
I can't reproduce the crash in 3.2 nor in 3.1. Is the project supposed to crash on run? Because it doesn't. @ikicapitan Could you test again?

**Comment by akien-mga** [comment] 2020-01-15 11:35
No answer, so closing.

**Closed by akien-mga** 2020-01-15 11:35 UTC
Labels: bug, topic:core
