### ISSUE TITLE
canvas_item shader source_color hint not working

### ISSUE THREAD

**Issue by rickwight** [godotengine/godot#87102] opened 2024-01-12 07:26 UTC
### Tested versions

only tested v4.2.stable.official [46dc27791]

### System information

Windows 11 - Godot v4.2.stable.official [46dc27791]

### Issue description

When HDR 2D is enabled, the source_color type hint is suppose to do the sRGB color space conversion automatically for you, but it does not. When HDR 2D is enabled, in your shader you have to adjust color uniforms by raising them to the power of 2.2 to do the conversion manually.

### Steps to reproduce

Make a scene with a sprite. Give it a shader material, and give it a shader like this this:

```
shader_type canvas_item;
uniform vec3 color: source_color = vec3(0.5,0.5,0.0);
void fragment() {
	COLOR.rgb = color;
}
```

If you turn HDR 2D on, that color will appear brighter than it should. This only applies to colors with fractional channel values. The `source_color` type hint is supposed to automatically handle the color-space conversion for you, like it does in 3D, but it does not. In order for it to look right, you have to manually convert it with a line like this:

```
COLOR.rgb = pow(color, vec3(2.2));
```

### Minimal reproduction project (MRP)

N/A

**Comment by bitsawer** [comment] 2024-01-15 09:50
Thanks for the report. This looks like a duplicate of https://github.com/godotengine/godot/issues/84989, so closing this to keep discussion in one place.

**Closed by bitsawer** 2024-01-15 09:50 UTC
