### ISSUE TITLE
Typehints on inner classes do not recognize function argument types

### ISSUE THREAD

**Issue by bitbrain** [godotengine/godot#64915] opened 2022-08-26 07:04 UTC
### Godot version

9c9b8fcd34f21fb8a754621c5a6ae21cddaca9d9

### System information

Windows 10

### Issue description

I use a lot of inner classes in my project to structure my data better and in Godot 3.5+ I was able to instantiate an inner class and use it as a function argument type. Attempting this in Godot 4 results in a compilation error:

```
Invalid type in function '_print_string_value' in base 'Node2D ()'. The Object-derived class of argument 1 (RefCounted (ChildClassA)) is not a subclass of the expected argument class.
```
This line comes from https://github.com/godotengine/godot/blob/7199314eb39408da4f9f7286452c980a3d3da1c9/modules/gdscript/gdscript_vm.cpp#L166 and when debugging the project it looks like there is not a real type created but just a `RefCounted`:
![Capture](https://user-images.githubusercontent.com/822035/186843833-efde2fb2-9714-4549-bba4-fdf644c599a8.JPG)

This might relate to #61567 and #61635 however, they mention very specific use-cases while I am just trying to use the type itself.

### Steps to reproduce

Create some inner classes with inheritance and then register that namespace class as a autoload singleton:
![Capture2](https://user-images.githubusercontent.com/822035/186842151-fed9e7ec-3717-41df-8356-0d111c3a38ca.JPG)

Attempt to use the inner classes as types:
![Capture](https://user-images.githubusercontent.com/822035/186842149-d5785b55-4b40-4663-af34-6c3a87cb0bde.JPG)

### Minimal reproduction project

[gdscript-inner-classes.zip](https://github.com/godotengine/godot/files/9430575/gdscript-inner-classes.zip)

**Comment by olibombardier** [comment] 2022-09-18 14:46
I have the same issue, the workaround I found was to explicitly convert to the subclass when passing an argument to a method. (`_print_string_value(class1 as MyNamespace.MyParentClass)` would probably work)

**Comment by olibombardier** [comment] 2022-09-21 03:07
Turns out I was wrong, converting to the subclass returns null. With other corrections I needed to make to convert to Godot 4 I didn't realise that this was the cause of one of my bug. Should I open another bug report? It might be the same problem where some part of gdscript doesn't recognize an instance of a subclass as that

**Comment by lyuma** [comment] 2022-10-25 18:06
There have been issues with inner classes and type declarations before.
There are also issues I filed last year #47062 and #47063, both of which were fixed by #49105

But I was able to reproduce a similar issue here by referencing an inner class from a different file.
```
SCRIPT ERROR: Trying to assign value of type '' to a variable of type 'external_type.gd'.
          at: _enter_tree (res://addons/imported_type_test/plugin.gd:14)
SCRIPT ERROR: Trying to assign value of type '' to a variable of type 'inner_classes.gd'.
          at: _enter_tree (res://addons/inner_class_decl/plugin.gd:14)
```
here's a test project for this if you want to try it (see the versions `: Object` work fine, but type hints break it):
[ImportedTypeDecl.zip](https://github.com/godotengine/godot/files/9854470/ImportedTypeDecl.zip)

**Comment by adamscott** [comment] 2022-10-25 18:08
@lyuma I can't test right now, but can you test your project against my cyclic references PR #67714? It fixes this issue.

**Comment by rune-scape** [comment] 2022-11-14 11:46
tested that #68374 fixes this

**Closed** 2022-11-14 16:15 UTC
Labels: bug, topic:gdscript, regression
