### ISSUE TITLE
Shortcuts in code editor stop working (saving with CTRL+S, script navigation with ALT+ARROW)

### ISSUE THREAD

**Issue by AntonioDell** [godotengine/godot#74181] opened 2023-03-01 19:34 UTC
### Godot version

4.0.stable

### System information

Pop!_OS 22.04

### Issue description

When writing gdscript code for extended periods of time (~10 min) some keyboard shortcuts stop working and only start working again, if I navigate away from the godot editor, the shortcuts start working again for a time and then stop again (usually after less than a minute).  

This is possibly related to https://github.com/godotengine/godot/issues/63888.

### Steps to reproduce

I haven't found out, what actions exactly causes the shortcuts to stop working, so I cannot provide steps to reproduce sadly, but I know that this is an issue since at least RC 1. 

But on this screencast you can see the issue. You can't see the buttons I am pressing, but I try to navigate with ALT+Left and ALT+Right between the opened scripts history and it only works unreliably.
[Screencast from 03-01-2023 08:28:08 PM.webm](https://user-images.githubusercontent.com/29783330/222245098-8b7ad9e9-fce5-4014-b2a6-3a30f200d60a.webm)

Also using CTRL+S to save only prints the letter S into the code editor instead of saving sometimes. You can see it on the following screencast. The first time I use CTRL+S it saves, but after writing a little, it only prints s:
[Screencast from 03-01-2023 08:39:35 PM.webm](https://user-images.githubusercontent.com/29783330/222246899-5a1d78cf-efa7-43b5-b90c-22e9c30e74dd.webm)

### Minimal reproduction project

Any project will do as far as I know.

**Comment by AThousandShips** [comment] 2023-03-01 19:52
(for those unfamiliar STRG is CTRL)

**Comment by ddelvall** [comment] 2023-03-03 19:15
I haven´t used Godot 3 in a while, but i can confirm that I get this problem at least since Godot4 RC2, this problem also fixes itself when triggering save with mouse clicks. 

Don´t know how relevant, but it happens to me on Fedora 37 with Gnome wayland

**Comment by mieldepoche** [comment] 2023-03-04 01:56
I had those problems too on ubuntu. (since the latests RCs iirc)
I managed just now to somehow solve them but I do not understand how, as I did nothing that I can think of in godot that could be responsible. Ctrl+S now works. It seem to persist through godot and computer reboots.

I doubt this will be of any use but the exact sequence of things I did was:
 1. witness that Ctrl+S would not save and type S instead, over several days and in 4.0 and the latest rcs (not sure which exactly but I know I didn't report this for several days already)
 2. I built #74319 (by cloning their fork and switching to the good branch, no clue if that's what I actually have to do since I don't know how to git) and the Ctrl+S problem seemed to have disapeared. (as in I couldn't trigger it by the method mentioned above). 
 3. however once I got back to 4.0.stable, well... the problem was gone. Now Ctrl+S saves every time. Sorry I don't have more info :upside_down_face: 

And this looks related: my shortcut to show the script editor is `Ctrl+1` (Ctrl+& on my french keyboard layout) and when pressing this while in the script editor, it types the & character. Or in general it types the character as if it wasn't a shortcut. **this happens in both stable and the custom build I made**

Also I remember trying the Ctrl+Alt+S (save script) shortcut as a workaround when Ctrl+S was not working, and it too ended up being not working and typing S instead of saving the script.

**Comment by mieldepoche** [comment] 2023-03-04 02:01
also: #73978 is possibly related ?

**Comment by ddelvall** [comment] 2023-03-05 13:49
Is this a Linux problem? I haven´t seen windows users complaining about it. For all other users, are you using Wayland or Xorg?.

**Comment by AntonioDell** [comment] 2023-03-05 14:02
I am using Xorg (x11)

**Comment by mieldepoche** [comment] 2023-03-05 16:43
x11 too here

**Comment by akien-mga** [comment] 2023-03-05 17:00
CC @bruvzg

**Comment by Rindbee** [comment] 2023-03-06 12:54
After switching to Chinese input, using the shortcut key `Ctrl + S` multiple times may reproduce this issue.

https://user-images.githubusercontent.com/30386067/223110855-9f7d7830-531b-450a-a04a-36ed2868dd8c.mp4

During attempts to reproduce this issue, the `Ctrl` key is held down and only the `S` key is released/repressed. After the issue appears, the shortcut key will only take effect on the first attempt after the editor loses focus and regains focus, otherwise it will be invalid.

Might be related to the following code.

https://github.com/godotengine/godot/blob/2267646bf4c29acf1342951d8726626817c742bd/platform/linuxbsd/x11/display_server_x11.cpp#L3252-L3257

When the issue occurs, `echo` is set to `true`. It may be that `Input::keys_pressed` is not properly cleaned up when the key is released.

**Comment by Rindbee** [comment] 2023-03-06 15:38
https://github.com/godotengine/godot/blob/2267646bf4c29acf1342951d8726626817c742bd/platform/linuxbsd/x11/display_server_x11.cpp#L2927-L2932

After this issue occurs, the above code will cause the corresponding event to fail to be generated when the key is released. This caused `Input::keys_pressed` to end up not clearing the previous keys correctly.

**Closed** 2023-03-07 11:05 UTC
Labels: bug, platform:linuxbsd, topic:editor, usability
