### ISSUE TITLE
Shadow overlap sprite with billboard mode and "Shaded" flag enable

### ISSUE THREAD

**Issue by inara-work** [godotengine/godot#45148] opened 2021-01-13 00:12 UTC
**Godot v3.2.3:**

**OS/device including version:**
Linux 5.9.16-1-MANJARO 
Tested with GLES2 and 3, same problem. 

**Issue description:**
I want a sprites in billboard mode to cast shadows in a 3D environment. I've enabled billboard mode, check "Transparent", "Shaded" and "Double sided" flags and set "Alpha Cut" to "Opaque Pre-Pass". It casts shadows as expected, but there is some ugly shadow artifacts in front of my sprite, like this : 

![Capture1](https://user-images.githubusercontent.com/59919226/104387551-ab463780-5537-11eb-89f3-048e495eba2f.png)

This problem only occurs when I enable the "Shaded" flag. It work just fine when I disable it, like this : 

![Capture2](https://user-images.githubusercontent.com/59919226/104387792-27d91600-5538-11eb-8dd1-174e17222d8e.png)

**Steps to reproduce:**
I tried on different computers, with both Linux and Windows, I ran it with GLES 2 & 3, I tried with the Sprite node and the MeshInstance one, with Spot, Directional Omni Lights,  still the same... It really seems to be the Shaded flag fault.

To reproduce you just have to instantiate a Ground, a Sprite, and a OmniLight with Shadow enabled, set options described above on the sprite and watch.

**Minimal reproduction project:**
[BugReport.zip](https://github.com/godotengine/godot/files/5805491/BugReport.zip)

**Comment by pycbouh** [comment] 2021-01-13 01:07
Duplicate of #45147

**Closed by pycbouh** 2021-01-13 01:07 UTC
