### ISSUE TITLE
Reverse shifts horizon in Camera3D with frustum_offset.

### ISSUE THREAD

**Issue by arlez80** [godotengine/godot#73287] opened 2023-02-14 14:10 UTC
### Godot version

v4.0.rc1.official [8843d9ad3]

### System information

Windows 10, NVIDIA GeForce RTX 3060

### Issue description

Reverse shifts horizon in Camera3D with frustum_offset.

`$Camera3D.frustum_offset.y = 0`
![image](https://user-images.githubusercontent.com/5057625/218758149-f4fcfc01-7e2d-49a7-b931-17121b4610dd.png)

`$Camera3D.frustum_offset.y = 0.02` (reverse shifts horizon)
![image](https://user-images.githubusercontent.com/5057625/218758263-a79c86f1-d5e2-4adf-a528-8b8e55c37611.png)

Expected (it taken from Godot 3.5.1.stable):
![image](https://user-images.githubusercontent.com/5057625/218759650-2a57edd4-d84e-4ffa-aba2-afa323f91903.png)

### Steps to reproduce

1. Create WorldEnvironment with Sky.
2. Create MeshInstance3D and Sets BoxMesh
3. Create Camera3D
4. Set frustum projection to Camera3D.
5. Use Camera3D preview.
6. Change Camera3D's frustum_offset.y

### Minimal reproduction project

N/A

**Comment by Calinou** [comment] 2023-02-14 19:33
Duplicate of https://github.com/godotengine/godot/issues/63863.

**Closed by Calinou** 2023-02-14 19:33 UTC
