### ISSUE TITLE
font_hover_pressed_color not working for buttons

### ISSUE THREAD

**Issue by Moonman327Dev** [godotengine/godot#84154] opened 2023-10-29 16:59 UTC
### Godot version

4.1.1.stable.mono

### System information

Godot v4.1.1.stable.mono - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3060 Ti (NVIDIA; 31.0.15.3742) - AMD Ryzen 7 5800X 8-Core Processor (16 Threads)

### Issue description

Was going a bit crazy over font_hovered_pressed_color not seeming to work with my Buttons in my project, so I did some testing (including making a quick new project) and font_hovered_pressed_color doesn't seem to work at all. The only way I can get it to work is by forcing it to in a script.
![image](https://github.com/godotengine/godot/assets/115742751/11fd9814-f774-4a2f-be74-9c6ba59da89a)
![image](https://github.com/godotengine/godot/assets/115742751/55cc0abd-464e-4e55-9c9b-1045eab7ee60)
![image](https://github.com/godotengine/godot/assets/115742751/0ba72dbb-c178-4239-ac28-bdfc5c052a74)

### Steps to reproduce

1. Create a new project
2. Give a button a hover pressed color, some others for testing too.
3. Try to get it to show by hovering over it and pressing in both toggled and normal mode

### Minimal reproduction project

N/A

**Comment by AThousandShips** [comment] 2023-10-29 17:30
Duplicate of https://github.com/godotengine/godot/issues/83393

**Closed by AThousandShips** 2023-10-29 17:30 UTC
