### ISSUE TITLE
Renaming a node in AnimationTree and validating with Enter renames it to nonsense

### ISSUE THREAD

**Issue by ClemensOlivae** [godotengine/godot#65590] opened 2022-09-09 21:08 UTC
### Godot version

4.0 Alpha 16

### System information

Windows 10

### Issue description

In an AnimationNodeBlendTree, inside an AnimationTree, renaming a node and validating the new name by pressing Enter validates a different name than the one entered : it can be the name of en existing node with "2" added at the end, or even "null"
The behaviour is not constant, sometimes it works fine but there is a 50% chance it doesn't

Validating the new name by clicking outside the textbox instead of pressing Enter works fine
This happens even if the new name has not been used before, it's not a matter of renaming to an already used name and Godot adding "2" at the end :)

Not that serious an issue, but can be really annoying!

### Steps to reproduce

Add an AnimationTree, with an AnimationNodeBlendTree root
Add a few nodes
Rename one
Press enter

**Comment by Calinou** [comment] 2022-09-09 21:27
Duplicate of https://github.com/godotengine/godot/issues/58822.

**Closed by Calinou** 2022-09-09 21:27 UTC
