### ISSUE TITLE
Animation Player moves ui out of screen

### ISSUE THREAD

**Issue by LeonardMeagher2** [godotengine/godot#3526] opened 2016-01-31 03:33 UTC
![screenshot from 2016-01-30 19 30 25](https://cloud.githubusercontent.com/assets/1546044/12700057/fbc250a6-c787-11e5-9c41-d0fa17198630.png)

![screenshot from 2016-01-30 19 30 35](https://cloud.githubusercontent.com/assets/1546044/12700065/40d4a96e-c788-11e5-9005-814544be9b23.png)

When opening the Animation player editor, it shift the ui to the right, and the only way to get it back is close the ui and resize the screen.

**Comment by vnen** [comment] 2016-01-31 22:08
The same issue is reported on #3469, but using a window tiled to the side of the screen.

**Comment by akien-mga** [comment] 2016-02-01 11:05
I got a similar issue when showcasing Godot at FOSDEM using a beamer, it was quite annoying, I could not find a way to see the inspector. I don't remember if the AnimationPlayer was involved though.

**Comment by freemanfromgodotengine** [comment] 2016-02-01 11:41
I can confirm this with screen resolution 1280x720. It looks like animation editor's upper icons take too much space, so the whole Godot window is expanded to the right and going out of the screen. In the same time, when animation editor is opened, left or right Scene, FileSystem or Inspector panels can't be resized. After closing animation editor everything is back to normal, except the right edge of Godot's window is still outside the screen edge. 
The bug looks the same in maximized window and fullscreen mode.

I think somewhat IMPORTANT info:
The bug is present (at lease with screen resolution 1280x720) ONLY when Scene, FileSystem or Inspector panels use both, left and right panels at the same time.
When Scene, FileSystem or Inspector panels are moved to one side, left or right, then the screen expands to the right, but does not go off the screens edge and the Scene, FileSystem or Inspector panel CAN be resized.

**Closed** 2016-02-02 21:23 UTC
Labels: bug, confirmed, topic:editor
