### ISSUE TITLE
InputActionEvent propagated only one time

### ISSUE THREAD

**Issue by Cevantime** [godotengine/godot#37375] opened 2020-03-28 11:19 UTC
**Godot version:**
3.2.1 stable

**OS/device including version:**
Linux Mint 19.3, Firefox, Chrome, Android

**Issue description:**
I'm trying to emit custom event action to my game in order to deal with multitouch. So I create an action named "touch" and try to pass it to the tree like this :
```
var action = InputEventAction.new()
action.pressed = true
action.action = "touch"
Input.parse_input_event(action)
```
The code above is the one recommended in docs and is triggered when a button is pressed.

**However**, when I try to receive this event in the rest of the tree like this : 

```
func _process(delta):
	if Input.is_action_just_pressed("touch"):
                print("touched")
```
The event is only received once, even if a emit it multiple times (by spamming the button)

**Two things I noted** : 

1. the problem concerns `Input.is_action_*` methods only. Nothing wrong with methods such as `_input()` 
2. when I use `Input.is_action_pressed()` instead of `Input.is_action_just_pressed()`, sometimse the action is received, and sometimes it's not.

**Steps to reproduce:**

Just add a button to a scene and create a custom action (using the code above) when the button is pressed. 
Try to use `Input.is_action_pressed("name_of_the_action")` and see if the action is triggered.

**Minimal reproduction project:**

[InputActionIssue.zip](https://github.com/godotengine/godot/files/4396996/InputActionIssue.zip)

**Comment by Ev1lbl0w** [comment] 2020-03-28 12:57
I believe it's because you're generating a "pressed" event, but never create a "released" event. So, if you click 10 times in the button, it's the equivalent of having 10 fingers on the screen at the same time.

Maybe you should instead connect to the `bottom_up` and `bottom_down` signals, and generate the respective events, to fix this:

```gdscript
func _on_Button_button_down():
	var action = InputEventAction.new()
	action.pressed = true
	action.action = "touch"
	Input.parse_input_event(action)


func _on_Button_button_up():
	var action = InputEventAction.new()
	action.pressed = false
	action.action = "touch"
	Input.parse_input_event(action)
```

**Comment by Cevantime** [comment] 2020-03-28 13:18
Ooh, Now, it actually make sense. I didn't get that an action had to be created for both state (pressed and not pressed). But this seems perfectly consistent. And the snippet you sent works great. Thank you so so much !

**Comment by madmiraal** [comment] 2021-04-18 16:35
Closing as not a bug.

**Closed by madmiraal** 2021-04-18 16:35 UTC
Labels: topic:input
