### ISSUE TITLE
Context/Dropdown menus severely offset if the godot editor is opened in maximized mode at first.

### ISSUE THREAD

**Issue by Scarm2** [godotengine/godot#54593] opened 2021-11-04 13:28 UTC
### Godot version

v4.0.dev.custom_build [#54571]

### System information

Windows 10 Pro Build 19042, NVIDIA GeForce RTX 2060 SUPER, Vulkan API 1.2.170, Project running on Vulkan Mobile

### Issue description

Context/Dropdown menus are severely offset if the godot editor is opened maximized as shown in the screenshots below:

left-clicked on the project drop-down menu.
![image](https://user-images.githubusercontent.com/82760388/140318958-09e26eac-e32e-4705-833c-ea964a661ee5.png)

right-clicked the icon.png file
![image](https://user-images.githubusercontent.com/82760388/140320962-7d83f565-c575-4d73-b151-4e3669a9085e.png)

Dragging and dropping files is also affected by this. This has been around for a while and I never saw anyone reporting it.

The issue is fixed if the program is minimized and then maximized back. Must be done every time you reopen the godot editor to fully avoid the issue.

Doesn't happen in 3.x

### Steps to reproduce

1. Open Godot
2. Go to a project
3. Wait for Godot to start (must start maximized)
4. Right click somewhere

### Minimal reproduction project

None

**Comment by jmb462** [comment] 2021-11-04 13:33
Seems to be a duplicate of https://github.com/godotengine/godot/issues/45740

**Comment by KoBeWi** [comment] 2021-11-04 15:57
Yes

**Closed by KoBeWi** 2021-11-04 15:57 UTC
