### ISSUE TITLE
Path3D Node - First added point is duplicated

### ISSUE THREAD

**Issue by Bimbam360** [godotengine/godot#72744] opened 2023-02-05 02:13 UTC
### Godot version

v4.0.beta17.official [c40020513]

### System information

Windows 11

### Issue description

The first added point of a Path3D node is intermittently creating an unexpected duplicate, identical point.

### Steps to reproduce
Unclear exactly why it triggers (possibly relating to replacing the current curve with a new one), but once it has, it will continue to happen in newly created Scenes/nodes as follows until the editor is restarted:

Open a new 3d Scane. 
Add Path3D Node. 
Add a point.
![Path bug](https://user-images.githubusercontent.com/11803603/216797969-6efef96f-ca50-4e2b-a8a9-62cdf928c6a1.gif)

### Minimal reproduction project

N/A

**Comment by Bimbam360** [comment] 2023-02-05 02:23
Confusingly, I just re-opened Godot to find this behaviour is working again, so it's unclear what original cause is. Will continue testing.

**Comment by KoBeWi** [comment] 2023-02-06 14:38
Can't reproduce this one.

**Comment by KoBeWi** [comment] 2023-02-21 19:56
I bet it's fixed in rc3. Comment if you can still reproduce it.

**Closed by KoBeWi** 2023-02-21 19:56 UTC
Labels: bug, topic:editor, needs testing
