### ISSUE TITLE
RichTextLabel's [center] and [right] are still broken

### ISSUE THREAD

**Issue by somnivore** [godotengine/godot#34308] opened 2019-12-12 18:37 UTC
**Godot version:**
269145a346bddae5cbbf00fd17b6c8eac4cd4665
**OS/device including version:**
ArcoLinux
**Issue description:**
There seems to be a misconception in what's expected of RichTextLabel's [center] and [right] tags.  When the user attempts to center-align their text, for example, what they're looking for is precisely what Godot's label does:
![godotlabel](https://user-images.githubusercontent.com/28724859/70737944-4c314600-1cd9-11ea-996c-6cff33a854b1.png)

This expectation is also supported by this BBCode tester https://infinite-story.com/tools/bbcode.php
![infinite-story](https://user-images.githubusercontent.com/28724859/70737970-5f441600-1cd9-11ea-80b1-4987cd9be389.png)

When the RTL centers text, however, it winds up looking like this:
![godot](https://user-images.githubusercontent.com/28724859/70737991-6bc86e80-1cd9-11ea-8f52-b078297a2b86.png)

It centers the entire block of text to the middle of the control, but doesn't actually center-align.  The user wants to center-align, not center the entire contents.

[right] also suffers this same issue:
![image](https://user-images.githubusercontent.com/28724859/70738520-7a635580-1cda-11ea-8e73-758b7ceb226c.png)

```
[right]This is a test. This is only a test.  This is a test. This is only a test.  This is a test. This is only a test.  This is a test. This is only a test.  This is a test. This is only a test.  This is a test. This is only a test.[/right]
```

For contrast, here's what the BBCode tester outputs:
![image](https://user-images.githubusercontent.com/28724859/70738914-53595380-1cdb-11ea-9286-cdee8be0bad5.png)

According to https://github.com/godotengine/godot/pull/29785 , https://github.com/godotengine/godot/issues/6982 is fixed, but it seems to fix a problem that doesn't actually exist, or missed the point of the issue being raised.  The tags are expected to center-align and right-align the text itself, just like Label, and just like the BBCode tester, not shift the entire contents towards the center or the right while keeping the text alignment left.

**Comment by TheDuriel** [comment] 2019-12-13 15:26
possibly related to #31089 and #30632 and #27896 and #24570 and #24305

so yeah, someone plz nuke this node and rewrite it :D

**Comment by Capital-EX** [comment] 2020-02-06 02:24
Chiming in to say that this is still an issue with 3.2. It seems like Godot doesn't properly handle line wrapping:
![image](https://user-images.githubusercontent.com/13488718/73900244-2483d780-485d-11ea-9c1c-0bb8ca734392.png)


Hopefully this will be fixed one day, especially since Godot recently added text effect to the RTL node. But, in its current state, it is unusable.

**Comment by Nolkaloid** [comment] 2020-02-27 20:37
If I try to nuke it and rewrite it, do we care about backwards compatibility? Or should I just try to patch it here and there UwU?

**Comment by Janglee123** [comment] 2020-02-28 05:21
@Nolkaloid I think for 4.0, there are already lots of changes to break compatibility. But for 3.2, patches should be better.

**Comment by Poobslag** [comment] 2020-04-16 22:24
https://imgur.com/4flMKsq Godot 3.2 still has problems with wrapping centered text, including this weird edge-case where it overlaps itself. The RichTextArea is tall enough to accommodate four rows of text, and additional rows cause a scroll bar. But, sometimes the textarea will just plop a word on top of other words.

**Comment by Anutrix** [comment] 2020-06-04 06:53
Can we close this if it's fixed by https://github.com/godotengine/godot/pull/39164?

**Comment by Calinou** [comment] 2020-06-04 07:26
It was confirmed to be fixed by @pouleyKetchoupp in https://github.com/godotengine/godot/pull/39164#issuecomment-636312143, closing.

**Closed by Calinou** 2020-06-04 07:26 UTC
Labels: bug, confirmed, topic:gui
