### ISSUE TITLE
move_and_* does not work for pixel perfect collisions

### ISSUE THREAD

**Issue by Max-Hollywood** [godotengine/godot#38709] opened 2020-05-13 01:59 UTC
**Godot version:** 3.2.1.stable.official

**OS/device including version:** Windows 10.0.18362

**Issue description:** building top down grid like movement game, `move_and_slide`/`move_and_collide` add erroneous position data so it moves out of being pixel perfect.  So if `x, y` position vector of `32,24` would become `32.01216, 24.9389` if told to `move_and_slide`/`move_and_collide`.

**Steps to reproduce:** tiles are 16x16, CollisionShape Collision2D is 16x16, and using `move_and_*` means that the node has a float position, causing the collision shapes to meet, causing the movement to stop.

**Minimal reproduction project:**
For reference, here's the level:
![godotmoveref](https://user-images.githubusercontent.com/29140168/81762602-61243680-9510-11ea-8bfa-2476e5b83c03.jpg)

This is the issue when `move_and_*` is called:
![godotmove](https://user-images.githubusercontent.com/29140168/81762133-2f5ea000-950f-11ea-92d8-c313c9da9fa9.jpg)

The position according to Godot remote:
![godotissue](https://user-images.githubusercontent.com/29140168/81762828-f6272f80-9510-11ea-86d3-78ce7fa54e4d.png)

My solution is to have a smaller collision shape and an additional test `move_and_collide` and if there is a collision then don't move, and have a final `round()` when the node stops moving, to snap it back to pixel position.

**Comment by TheDuriel** [comment] 2020-05-13 06:37
Godot is inherently incapable of pixel perfect collision. If you want that, you'll need to write a physics engine based on Intergers and AABB tests exclusively.

So this isn't a bug, nor unexpected. You'll find this to be an issue with any Engine which does not feature a custom, pixel perfect, physics Engine.

I recommend you keep faking it. Like the entire rest of the games industry that rely on premade Engines.

**Comment by Zireael07** [comment] 2020-05-13 06:40
To add to what @TheDuriel said, I believe 99% of pixel perfect games out there don't use physics at all, instead just changing transforms by hand.

**Comment by Calinou** [comment] 2020-05-13 07:33
Duplicate of #37798 and #23140 (the underlying issue is the same).

**Closed by Calinou** 2020-05-13 07:33 UTC

**Comment by Max-Hollywood** [comment] 2020-05-25 11:03
Something I forgot to mention that you might already be aware of, which did contribute to this, was that the move_and_slide perpetually moved downwards.  On my tilemap, the node ends up further down and to the left of it's final resting position, instead of "in the center" of the tile.  This may be part of a tilemap issue, which I'm about to create an Issue for.  With both of these issues I can't make any levels larger than the screen area because the player gets stuck.

**Comment by SlitheringMule** [comment] 2021-06-27 18:05
Try `position = Vector2(round(position.x), round(position.y))` at the end of `_physics_process`
