### ISSUE TITLE
LineEdit and possably TextEdit and RichEdit cannot be focused out of with keyboard.

### ISSUE THREAD

**Issue by Shadowblitz16** [godotengine/godot#63050] opened 2022-07-15 20:59 UTC
### Godot version

4.0 alpha 11

### System information

KDE neon 5.25

### Issue description

You can't use the keyboard to focus a nabour when inside a line edit in 4.0.
It seems to work in 3.4.4

I haven't tested textedit and richedit

### Steps to reproduce

- Create a ui with a button and a line edit side by side
- Click on the line edit to focus it
- Try to navigate to the button with keyboard
- See it doesn't work

### Minimal reproduction project

[AstroWars.zip](https://github.com/godotengine/godot/files/9124026/AstroWars.zip)

**Comment by Paulb23** [comment] 2022-07-16 10:20
Duplicate of #27036

**Closed by Paulb23** 2022-07-16 10:20 UTC
Labels: needs testing, topic:gui
