### ISSUE TITLE
inspector gets squashed on osx

### ISSUE THREAD

**Issue by Reneator** [godotengine/godot#35428] opened 2020-01-22 06:32 UTC
**Godot version:**
3.2 beta6 and 3.2 rc 2

**OS/device including version:**
macOS Catalina, version 10.15.2
MacBook Pro (13-inch, 2018, Four Thunderbolt 3 Ports)

**Issue description:**
Whenever I change to the script context, the inspector on the right side gets squashed and I cant resize it while in the script context. When i change back to the 2D context, i can resize but the right side of the inspector seems out of whack.

See here:
https://youtu.be/ESTe0ER3trQ

This works properly in 3.1.2 or the same versions (3.2 beta 6, 3.2 rc 2) on windows also work properly in this regard.

**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by timothyqiu** [comment] 2020-01-22 07:11
I think this is a duplicate of #31133.

A temporary fix might be removing the text on these three buttons, and make the text the first line of its tooltip.

**Comment by akien-mga** [comment] 2020-01-22 07:30
Duplicate of #31133.

**Closed by akien-mga** 2020-01-22 07:30 UTC
