### ISSUE TITLE
Vulkan: resizing viewport causes artifacts appear on bottom and right sides. (Might be old hardware issue)

### ISSUE THREAD

**Issue by MegadronA03** [godotengine/godot#69067] opened 2022-11-23 20:32 UTC
### Godot version

4.0 beta 5

### System information

Windows 10, GT740-OC-2GD5 (ASUS GT 740)

### Issue description

![Снимок экрана (14)](https://user-images.githubusercontent.com/56801003/203639542-0f842a38-f570-40af-aedf-e80ba74c3b8f.png)
![Screenshot (54)](https://user-images.githubusercontent.com/56801003/203639549-dd7d976e-af99-45c3-86be-93d867192270.png)
![Screenshot (55)](https://user-images.githubusercontent.com/56801003/203639551-a3cbb94f-0e36-46c1-b43b-85ec9e1752b4.png)
Might be hardware fail, because this GPU is 8 years old, no more new drivers, and DXGI_ERROR_DEVICE_HUNG happens in Dx11 applications.

### Steps to reproduce

Resize any Viewport (even the one in editor), and artifacts will appear. SSAO "extends" this artifact.

### Minimal reproduction project

Resize the window, or bring console through "`", type "/freecam" and bring even more viewports to cause this bug(to move the camera press "V" and use arrows and mouse to move it)

https://github.com/MegadronA03/ShiftedPort-GodotProto (project exceeds 25mb)

**Comment by MegadronA03** [comment] 2022-11-23 20:35
whoops... this project doesnt fit description of minimal reproduction project, but whatever, because it happens in editor if viewport resized

**Comment by MegadronA03** [comment] 2022-11-23 20:37
![Screenshot (56)](https://user-images.githubusercontent.com/56801003/203641759-8961fdb3-e5fe-4047-a9ee-9b4e80738a94.png)

**Comment by MegadronA03** [comment] 2022-11-23 21:13
Update: this issue is specific to this project, but the only things I did there:
Downloaded and installed devcubes from AssetLib, placed them and added environment node to play with renderer settings.

**Comment by Calinou** [comment] 2022-11-23 23:15
Related to https://github.com/godotengine/godot/issues/56724 (possible duplicate)?

Can you reproduce this when all effects are disabled in WorldEnvironment, including glow?

**Comment by MegadronA03** [comment] 2022-11-24 05:47
Its related to #56724, but I didnt used any lighting.

**Comment by MegadronA03** [comment] 2022-11-24 14:55
![Screenshot (57)](https://user-images.githubusercontent.com/56801003/203812855-cbceb2de-16df-46e3-aebd-3b4846cff101.png)
Yep, thats SSIL Issue.
![image](https://user-images.githubusercontent.com/56801003/203813060-34757069-65b1-4214-b646-9be362e0d729.png)
Tho SSAO also have same but less noticeable issue (1~2 pixels on edge flickers)
![image](https://user-images.githubusercontent.com/56801003/203813551-eb0cc673-9cf3-429a-85e6-0ba55775885b.png)

**Comment by Calinou** [comment] 2022-11-24 15:03
The SSIL issue is a duplicate of https://github.com/godotengine/godot/issues/56724.

The SSAO issue is a duplicate of https://github.com/godotengine/godot/issues/62881.

**Closed by Calinou** 2022-11-24 15:03 UTC
Labels: bug, topic:rendering, topic:3d

**Comment by MegadronA03** [comment] 2022-11-24 15:19
> The SSAO issue is a duplicate of #62881.

this SSAO issue is not a duplicate of #62881, because that line (but its barely noticeable) also appears during window resizing, and also constantly flickers (but I think that should be in other issue)
![Screenshot (59)](https://user-images.githubusercontent.com/56801003/203818214-a88b7840-9027-469e-ac78-0ca9ba75b51e.png)
