### ISSUE TITLE
fatal error when using visual gradient inspector

### ISSUE THREAD

**Issue by s-e** [godotengine/godot#17298] opened 2018-03-06 07:59 UTC
**Version**: 3.0.2.stable.official
**OS**: Windows 10 Pro
**GPU**: GTX 1070 

**Issue description**:
Using the visual gradient editor sometimes triggers fatal error with:

```
ERROR: Vector<struct Gradient::Point>::operator []: FATAL: Index p_index=-1 out of size (size()=9)
At: c:\projects\godot-builds\godot\core\vector.h:138
CrashHandlerException: Program crashed
Dumping the backtrace. Please include this when reporting the bug on https://github.com/godotengine/godot/issues
[0] <couldn't map PC to fn name>
[1] <couldn't map PC to fn name>
[2] <couldn't map PC to fn name>
[3] <couldn't map PC to fn name>
[4] <couldn't map PC to fn name>
[5] <couldn't map PC to fn name>
[6] <couldn't map PC to fn name>
[7] <couldn't map PC to fn name>
[8] <couldn't map PC to fn name>
[9] <couldn't map PC to fn name>
[10] <couldn't map PC to fn name>
[11] <couldn't map PC to fn name>
[12] <couldn't map PC to fn name>
[13] <couldn't map PC to fn name>
[14] <couldn't map PC to fn name>
[15] <couldn't map PC to fn name>
[16] <couldn't map PC to fn name>
[17] <couldn't map PC to fn name>
[18] CallWindowProcW
[19] CallWindowProcW
[20] glDebugEntry
[21] CallWindowProcW
[22] DispatchMessageW
[23] <couldn't map PC to fn name>
[24] <couldn't map PC to fn name>
[25] <couldn't map PC to fn name>
[26] <couldn't map PC to fn name>
[27] <couldn't map PC to fn name>
[28] BaseThreadInitThunk
-- END OF BACKTRACE --
```

**Steps to reproduce:**
Appears to happen with the Gradient Editor open in the Inspector, after the Godot Editor receives focus with a running game. This does not always reliably reproduce. Specifically tested using the Color ~~Ramp~~ Modifier gradient in the Trails section of a Particle Process Material (I believe Color Ramp works too).

I'll try to update if I do manage to get a reliable reproduction.

**Comment by reduz** [comment] 2018-09-06 22:01
I think this was fixed, because i can't reproduce the problem any longer, closing.

**Closed by reduz** 2018-09-06 22:01 UTC
Labels: bug, topic:editor
