### ISSUE TITLE
Godot code completion not showing available signal when calling connect() on node reference

### ISSUE THREAD

**Issue by ryanalbrecht** [godotengine/godot#92878] opened 2024-06-07 16:17 UTC
### Tested versions

- Reproducible in  4.2.0, 4.2.1, 4.2.2, 4.3-beta1
- Not Reproducible in 4.1.4

### System information

Windows 10

### Issue description

In Godot version 4.1.4 there is a code completion feature that will list all the available signals a node will emit (including custom signals) when calling `.connect()` on a node reference using the `$` convention. 

![image](https://github.com/godotengine/godot/assets/21182836/fd8f1543-66bd-4a6e-a869-0cfaabe6fe77)

In subsequent versions this code completion feature no longer seems to work.

### Steps to reproduce

-Define a custom signal on a child node. (Eg. Area2D)
-In the `_ready():` function of the parent node called `$Area2D.connect()`

### Minimal reproduction project (MRP)

[test2.zip](https://github.com/user-attachments/files/15742299/test2.zip)

**Comment by KoBeWi** [comment] 2024-06-07 17:39
Why aren't you using the new syntax, i.e. `$Area2D.custom_signal.connect()`? The signals should be properly suggested this way.

**Comment by ryanalbrecht** [comment] 2024-06-07 18:20
@KoBeWi no particular reason. I am very new to Godot and I was following a tutorial and went down a rabbit hole to and figure out what was wrong with the editor and discovered this bug and thought I would report it.

On the subject of the new syntax I did start using this in favor of the old, however I do find the old syntax with the popup very useful to show exactly what signals are available.  At first the engine is difficult to get your mind around and this helps.

**Comment by JekSun97** [comment] 2024-06-07 18:38
> `$Area2D.custom_signal.connect()`? The signals should be properly suggested this way.

Just because it's new doesn't mean you have to use it :)
I'm used to the old syntax and don't regret it

**Comment by KoBeWi** [comment] 2024-06-07 19:59
It's not only new, it's better. You don't use strings but actual signal references, so it's safer.

**Comment by HolonProduction** [comment] 2024-06-08 09:11
Very likely another regression from #79386 which might be somewhat similar to #92219, in that the value does not end up in the final type.

Even though there is a better way for signal connection, this should be fixed, as it might turn up with other argument options like `AnimationPlayer.play`

Note to my self: extend the autocompletion tests to incorporate argument options on `get_node`

**Comment by HolonProduction** [comment] 2024-07-12 11:54
For people trying tor reproduce: This only happens when the node which the get node literal refers to has a script attached

**Closed** 2024-07-24 08:04 UTC
Labels: bug, topic:gdscript, topic:editor, regression
