### ISSUE TITLE
Tree column widths are not correctly calculated

### ISSUE THREAD

**Issue by jmb462** [godotengine/godot#52891] opened 2021-09-21 09:44 UTC
### Godot version

Master branch [2785ad32d]

### System information

Windows 10

### Issue description

Tree column widths are not correctly calculated.

You can see it in editor with autoload settings tree or input settings tree  : 

**Action map editor**
![image](https://user-images.githubusercontent.com/3649998/134151120-29e5dbc7-2a7c-4c40-b443-d5c6f851997b.png)
Here, bin icon is missing at the right.

**Autoload settings**
![image](https://user-images.githubusercontent.com/3649998/134147343-71af837f-b76c-4a8a-b9f3-1e0e1cbd9223.png)
Here, global variable column is truncated and 3 icons button are missing in the last one (up arrow, down arrow, and bin).

Since f4379cbc82cfe915e97a8e879567b820a10198f4 min_width column has been removed from these tree definition.
it shouldn't be necessary. But seems that something is wrong.

I've investigated on the issue and can't find were the problem is.

I've done a gdscript example that reproduce the autoload settings tree and I find a very weird behavior.
With the same tree settings, here are 2 results : 
![image](https://user-images.githubusercontent.com/3649998/134148019-01c134da-7a9e-4958-b6e8-133e8a02328c.png)
The only difference is the name of the first item : a long one and a short one.
In the first tree, the width of Global Variable column is correct but not in the second one.
Unfortunately, even in the first one, an icon is missing at the right in the last column.
The two first column should have exactly the same width as all item are smaller than the column width ratio ( 1/3 and 2/3 of left expand space) but you can see that path columns is much wider in the second case.

This could be "fixed" by re-adding min_width size for some columns but it will mask the true issue in column width calculation.

### Steps to reproduce

Go to Project Settings > Input Map (look at the missing icons in the last column)

Go to Project Settings > Autoload (same issue)

Try the minimal reproduction project below

### Minimal reproduction project

[tree_bug.zip](https://github.com/godotengine/godot/files/7202124/tree_bug.zip)

2 trees are generated.
Only difference is length of the name of the first colum item.
Columns size are totaly different as a result.

**Comment by EricEzaM** [comment] 2021-09-21 13:16
Duplicate of #51484 and #50657, but this contains some extra detail compared to those.

>This is a regression after f4379cb(#50146) CC @reduz
>Bisect:
>f4379cbc82cfe915e97a8e879567b820a10198f4 is the first bad commit

**Comment by floppyhammer** [comment] 2021-09-24 03:00
A workaround can be achieved by simply setting the last column as expanded by `set_column_expand()`.

![image](https://user-images.githubusercontent.com/28705694/134611356-982315d7-9ce1-416c-adf0-c02ccd8719fa.png)

**Comment by floppyhammer** [comment] 2021-09-24 08:14
This might be a regression from both f4379cbc82cfe915e97a8e879567b820a10198f4 and ace19bd4c6fb2712efc68df395409edadc73cd8b. See #53001.

**Comment by jmb462** [comment] 2021-09-24 10:59
> makeshift


> A makeshift workaround can be achieved by simply setting the last column as expanded by `set_column_expand()`.
A better one is to set a min_custom_width() for the column (as before). But it has been removed on purpose and will mask the true issue.

**Closed** 2021-09-28 14:21 UTC
Labels: bug, topic:editor, regression, topic:gui
