### ISSUE TITLE
Run Godot on travis as part of the tests

### ISSUE THREAD

**Issue by touilleMan** [godotengine/godot#17408] opened 2018-03-10 12:42 UTC
Following my post on #2641, I thing a good first start to add unit test in Godot would be to simply run the Godot binary on the CI platform once compiled.

I've encountered numerous trouble trying to do this on my side (see https://travis-ci.org/touilleMan/godot-python/jobs/351671519 and https://ci.appveyor.com/project/touilleMan/godot-python/build/1.0.241/job/q9j5tg176alem3y7)
- on travis/linux x11 server is not available, so I must rely on xvfb which doesn't seems to handle opengl 3.3 (even with `LIBGL_ALWAYS_SOFTWARE=1`)
- on appveyor/windows Godot starts but is frozen forever without outputing a single thing

I'm very aware those trouble could be caused by Pythonscript module (or by a misconfiguration), that's why having the command to run Godot on CI present (and executed !) on the official Godot repo would allow to narrow the possible source of errors.

**Comment by thorthur** [comment] 2018-03-22 16:12
Regarding the X11 issue, I am unsure as to what the problem really is but would adding the `--no-window` option to platform x11 (it currently only works for Windows) be a solution?

**Comment by Calinou** [comment] 2018-03-23 14:20
> on travis/linux x11 server is not available, so I must rely on xvfb which doesn't seems to handle opengl 3.3 (even with LIBGL_ALWAYS_SOFTWARE=1)

You could compile and run the `server` platform, which does not require an X server to function.

**Comment by touilleMan** [comment] 2018-03-23 18:01
@thorthur yep that would be a good solution I guess, but x11 without window would be roughly equivalent to the server target ?

**Comment by thorthur** [comment] 2018-03-23 18:25
While server is roughly equivalent to x11 without window _right now_, I would like to point out:
1. "server" by itself denotes more a mode than a platform. This is debatable of course, see ongoing #11389.
2. A possible use case could be to test with no graphics but with audio, in this case `--no-window` makes more sense.
3. There currently are slight differences in the initializations of platforms x11 and server, furthermore there is no guarantee those platforms will behave _exactly_ the same with time (separate platform code). So there could be a need to test x11, and no server, because one might want to test a desktop release beforehand on a headless CI server.

@touilleMan If your use case does not belong to these points, I agree the `--no-window` argument is moot.

**Comment by cmfcmf** [comment] 2018-04-03 11:45
We've been able to use both TravisCI and AppVeyor to automatically export our game. 
You can find more information in [our reddit post](https://www.reddit.com/r/godot/comments/89cu19/exporting_and_publishing_your_games_automagically/?ref=share&ref_source=link) and [our godot-export repository](https://github.com/GameDrivenDesign/docker-godot-export).

**Comment by Calinou** [comment] 2019-07-16 22:33
After noticing https://github.com/godotengine/godot/issues/30630, I think it would make sense to use the headless binary we already build to export a simple project automatically. This way, we can catch regressions immediately. Perhaps this project could be committed to [godot-tests](https://github.com/godotengine/godot-tests), which means the repository would be cloned as part of the CI step.

We could also try running a simple script using the `-s` command-line switch to check any regressions related to running standalone scripts.

**Comment by slapin** [comment] 2019-07-17 21:27
My humble opinion is test data and test code should go with main repository for easier maintenance of consistency. But that is generic perspective, unless problems arise.

Regarding full blown testing see this: https://github.com/smartscenes/sstk/wiki/Headless-Rendering
https://github.com/stackgl/headless-gl/ but still solution is not perfect. I think full software implementation of DRM/OpenGL is more practical, also Vulkan testing will need some thought later.

**Comment by fire** [comment] 2019-07-17 21:53
Having export being tested is already good, but it's common for the export to infinite loop on bugs.

**Comment by slapin** [comment] 2019-07-17 22:00
can't travis time limit process execution?

**Comment by Calinou** [comment] 2019-07-17 22:01
@slapin It already does so by default (jobs are limited to 1 hour), but we could use the `timeout` command an exit with a non-zero error code to restrict the execution time of a single command.

**Comment by slapin** [comment] 2019-07-17 23:21
Global limit is a problem as it will fail job w/o running other jobs (which
might indicate other errors and be useful), I think per job time limits
were available which would allow other jobs still run while the renegade
job will hit timeout...

**Comment by aaronfranke** [comment] 2020-03-15 06:10
Is there any update on this issue? I've been thinking about possibly setting up Travis CI for the demo projects repository, to provide contributors with immediate feedback and to help with reviewing. Some static things I can think of include checking formatting of files (LF vs CRLF, BOM, EOL at EOF), checking C# files via `clang-format`, and maybe validating markdown of README files.

Aside from static checks, it would be amazing if I could set up Travis to run Godot and run some basic checks on the projects. For example, it would be nice to have Godot check all scenes and all GDScript files for warnings and errors, and possibly even run the projects to check for runtime errors.

**Comment by Xrayez** [comment] 2020-05-31 15:05
I've already made some progress on this as described in godotengine/godot-tests#8, but since the 4.0 breakage the CI scripts and tests need to be updated again. 😛

**Comment by akien-mga** [comment] 2020-06-02 09:52
Partially superseded by https://github.com/godotengine/godot-proposals/issues/918, which would depend on https://github.com/godotengine/godot-proposals/issues/991 to actually run unit tests on CI without having to rely on `xvfb` or similar.

If we want to extend this to also run actual Godot projects and do checks on visual output, etc., I would suggest opening a dedicated proposal specific to a project/scene-based testing framework for the Node API (as we discussed at Godot Sprint a few times), which can then be integrated in CI once available.

**Closed by akien-mga** 2020-06-02 09:52 UTC
Labels: feature proposal, topic:buildsystem

**Comment by Calinou** [comment] 2020-08-04 19:55
For those stumbling upon this issue from a search engine, note that [unit testing using doctest has been integrated into the Godot development process](https://github.com/godotengine/godot/pull/40148).
