### ISSUE TITLE
Universal common effect shader even if the material is different for each modeling

### ISSUE THREAD

**Issue by efwff** [godotengine/godot#17096] opened 2018-02-28 05:17 UTC
example effect photo
![ryse_son_of_rome_analisis_gamerzona_441385571721](https://user-images.githubusercontent.com/13410907/36771161-0cac8f4c-1c92-11e8-95ea-18333ba14dcc.jpg)

Purpose of effect shader
Turns the target effect shader on or off during the action event time (attack or defense).

real time toggle target's effect shader.
rim light color change support please.

PS.
The following conditions must be met:
Add generic common effects shader even if the material is different for each modeling!

For example,
in all other material's .glsl ( shader source )

include "effect_shader.h" <-include effects header files in each and every material shader
// rim light effect

if %RIMLIGHT
color = function():
endif
style header add please!!!!

Godot Engine Material
HumanSkin shader - head, body 
illum shader - item ( weapon, shield, cloth )

head, body, cloth = material is different for each modeling
rim lighting = all material support effect file ( header file )

effect shader - effect header file for all other shader material support ( add please !!!! )

**Godot version:**
current final version not support
next version support please.

**OS/device including version:**
nvidia geforce 560ti, windows 10 64bit

**Comment by akien-mga** [comment] 2018-02-28 07:25
That issue is quite confusing, but I guess what you want is just support for `#include` in shader files to reuse common code? If so that's a duplicate of #11691.

**Comment by Calinou** [comment] 2019-08-17 15:32
This issue seems to be a duplicate of #11691, closing.

**Closed by Calinou** 2019-08-17 15:32 UTC
Labels: feature proposal
