### ISSUE TITLE
setget called whenever you save a script

### ISSUE THREAD

**Issue by chucklepie** [godotengine/godot#49675] opened 2021-06-17 08:35 UTC
### Godot version

3.3 stable

### System information

Linux

### Issue description

Consider the following basic tool that is expected to be called whenever you attach it to a scene and click the export button in the inspector.

Whenever you simply use the scene, such as save, the setter gets called. Before you know it, you've ran your 'one off' tool a hundred times and broken your scene tree. Note also, whether by design or not breakpoints are never called in tools either so you never know.

![image](https://user-images.githubusercontent.com/12863685/122360970-bc63fc00-cf4e-11eb-9e25-360bafccc291.png)

Apologies if this is all by design, but the documentation for tools is fairly lacking and I couldn't find reference to setters being called on saving a scene in the documentation.

### Steps to reproduce

1. create a setget
2. save the scene
3. it is ran

**Comment by Zylann** [comment] 2021-06-17 10:40
I think it is related to https://github.com/godotengine/godot/issues/17681
In the sense that Godot may be reloading the scene after you save

**Comment by chucklepie** [comment] 2021-06-17 15:09
Thanks. Just the lack of documentation and random things happening I didn't
know if it was me or not.

I guess outside the remit of this issue, what is the best way currently to
have a 'one off' tool, or a tool guaranteed to only run once when you
explicitly want it to run?

**Comment by Zylann** [comment] 2021-06-17 15:43
Like a button to press to do one thing in the editor?
One way is to make an `EditorPlugin`, and not trying to hack it within an edited scene node. This way you can even place that button wherever you want in the interface as well.
But if you want to hack it inside the node, then I guess you can make a `bool` property that sets itself back to false in the setter. This way you can click the checkbox in the inspector. It will call the setter with `true`, in which case you run your thing, and later you just dont actually set the variable so it will remain unchanged.

**Comment by KoBeWi** [comment] 2021-06-17 20:12
I'll close this as duplicate of #17681 (see my comments). The method is called, but most likely it doesn't affect your scene, because it's called on a temporary node.

**Closed by KoBeWi** 2021-06-17 20:12 UTC
