### ISSUE TITLE
Strange GI probe results when using Gridmap

### ISSUE THREAD

**Issue by TwistedTwigleg** [godotengine/godot#18056] opened 2018-04-08 14:43 UTC
**Godot version:**
Godot 3.0.2

**OS/device including version:**
Windows 10 64 bit
Nvidia Geforce 660 TI 2gb

**Issue description:**
GI probes and Gridmaps do not seem to be working with each other:
![gridmap_issue](https://user-images.githubusercontent.com/25082678/38468610-d4dc0cf2-3b16-11e8-9793-f90b8ca6995c.png)

It seems to be ignoring certain faces? I'm not sure what the problem actually is, but it seems something is missed/corrupted in the GI Probe when using Gridmaps.

It also seems ambient light is not taken into account. Here's a picture from the project I discovered the issue in:
![gridmap_issue_normalambient](https://user-images.githubusercontent.com/25082678/38468761-9d7b3592-3b18-11e8-94c4-9a4ba02d07ed.png)

And here's when you crank ambient light up to max:
![gridmap_issue_highambient](https://user-images.githubusercontent.com/25082678/38468765-a881de0a-3b18-11e8-8de7-d154bfe50b19.png)

I noticed that any object not in the grid map (the glowing orange pillars) are effected by the ambient light, but it seems objects in the grid map are not? Changing the metallic and/or roughness values does not fix the issue. Regardless of the inputted values into metallic/roughness, the tiles are still overly dark.

**Steps to reproduce:**
Bake the provided example project

**Minimal reproduction project:**
[Gridmap_Probe_Issue.zip](https://github.com/godotengine/godot/files/1887532/Gridmap_Probe_Issue.zip)

**Comment by reduz** [comment] 2018-11-16 19:51
This is not really a bug, but it may appear like one due to how you set up your scene. Green emission over blue objects will not account to any lighting.

 In next version I will attempt to do some more light bounces in order to improve quality.

**Comment by TwistedTwigleg** [comment] 2018-11-16 21:06
What about the FPS tutorial project? It uses a GridMap for the space level and it seems to have the same bug, which makes the whole scene rather dark and hard to see.

In the FPS tutorial project, objects outside of a GridMap (like the orange pillars) are effected by different ambient light settings while the GridMap does not change at all.

I am just curious because in the FPS tutorial project, removing the GI probe brightens everything else in the scene up dramatically:

![godot_fps_comparison](https://user-images.githubusercontent.com/25082678/48647146-1ed07680-e9b9-11e8-98bb-91fac645e69e.png)

It is hard to see in the picture above, but even objects that have `Used in Baked Light` enabled are effected (like the pillars).

I could be wrong, but I think there is still a bug here.

**Comment by EzraT** [comment] 2018-11-16 21:44
I agree with TwistedTwigleg, there is still clearly a problem here. 
I'll see about setting up a reproduction project for this issue later, but for now here are 2 comparison screenshots to demonstrate what I mean:

Here is a scene using just MeshInstances together with a GIProbe:
![meshinstance](https://user-images.githubusercontent.com/781121/48648706-a84f6b00-e9f0-11e8-82cc-1d1e26a7da77.jpg)

And here are the same Meshes and materials used in a Gridmap together with a GIProbe:
![gridmap](https://user-images.githubusercontent.com/781121/48648736-c1581c00-e9f0-11e8-91fc-15f3b837a9c9.jpg)

The materials I used here use emission maps, I'm not sure if that makes a difference but I thought I'd specify it anyway.

**Comment by EzraT** [comment] 2019-04-03 09:25
Could this one perhaps be re-opened?
These issues are still present in 3.1 stable.

**Comment by akien-mga** [comment] 2020-01-05 10:18
Is this still reproduce in the current master branch / 3.2 builds?

**Comment by akien-mga** [comment] 2020-01-05 10:35
Actually I'll close this as duplicate of #18836, which should be addressed by GIProbe changes in 4.0.

**Closed by akien-mga** 2020-01-05 10:35 UTC
Labels: bug, topic:rendering
