### ISSUE TITLE
Sky has ghosting effect during motion when TTA is enabled and Forward+ renderer is used

### ISSUE THREAD

**Issue by gmikhail** [godotengine/godot#78443] opened 2023-06-19 19:08 UTC
### Godot version

v4.0.3.stable.official [5222a99f5]

### System information

Windows 10 Pro 22H2, Intel i7-7700HQ, NVIDIA GeForce GTX 1060 with Max-Q Design

### Issue description

When panorama sky (`WorldEnvironment > Environment > Sky > Sky Material > PanoramaSkyMaterial > Panorama`) or camera moves, on sky appears ghosting effect.  The problem occurs if TTA is enabled and Forward+ renderer is used. Ghosting effect appears only on the sky, but not in static geometry.

TTA on

![1](https://github.com/godotengine/godot/assets/4838367/53a5019f-3978-4975-a5ac-b1f1c5b9f078)

TTA off

![2](https://github.com/godotengine/godot/assets/4838367/230682df-5f9f-4224-a8ca-5a9b2eea15ce)

Scene

![1](https://github.com/godotengine/godot/assets/4838367/415b0c75-89af-499a-b305-218e8ea9bfb5)

### Steps to reproduce

1. Open attached project.
2. Run game by pressing F5.
3. Watch how sky texture has ghosting effect during rotation.
4. Disable TTA (`Project > Project Settings > Rendering > Anti Aliasing > Use TTA`) and see how crisp the sky became during rotation.

### Minimal reproduction project

[sky-ghosting.zip](https://github.com/godotengine/godot/files/11791261/sky-ghosting.zip)

**Comment by clayjohn** [comment] 2023-06-19 19:12
Duplicate of https://github.com/godotengine/godot/issues/67332

Thank you for reporting this issue! I will close this issue in favour of https://github.com/godotengine/godot/issues/67332 so that we can track the issue in one place

**Closed by clayjohn** 2023-06-19 19:12 UTC
