### ISSUE TITLE
Audio sounds aliased in Godot.

### ISSUE THREAD

**Issue by norton-corbett** [godotengine/godot#37830] opened 2020-04-12 19:47 UTC
**Godot version:**
3.2

**OS/device including version:**
Windows 10, using WASAPI driver

**Issue description:**
A pure sine wave output by Godot has a noticeable high-pitched hissing/aliasing noise behind it, similar to a sample-rate reduction effect.

For comparison, here is a zip containing two wav files:
[sine-comparison.zip](https://github.com/godotengine/godot/files/4466894/sine-comparison.zip)

**synth1.wav** is a sine wave generated using the Synth1 VST in Renoise, at 44100hz.
**godot.wav** is output by Godot at 44100hz. In this case it was output by a version of the "audio/generator" demo project re-implemented in c++ but you can hear the same effect by importing synth1.wav into the editor and listening to it back.

(If you're not an audio person you might need headphones, and to listen very carefully, to notice the difference.)

Bizarrely, when producing the tone using the generator method, *reducing* the "audio/mix_rate" project setting from 44100 to 22050, and even 11025, actually improves the quality of the resulting sine wave a little bit. Something is wrong here!

**Steps to reproduce:**
1. Run the audio/generator demo project and listen to the result, or,
2. Import synth1.wav into the editor and listen to it, and compare to listening to it in some other program.

**Minimal reproduction project:**
https://github.com/godotengine/godot-demo-projects/tree/master/audio/generator

**Comment by Calinou** [comment] 2020-04-12 19:50
Duplicate of #23544.

**Closed by Calinou** 2020-04-12 19:50 UTC
