### ISSUE TITLE
Godot v4.0 Beta 4 HTML5 Builds Do Not Run On Popular Itch.io Publishing Site?

### ISSUE THREAD

**Issue by BetaMaxHero** [godotengine/godot#68435] opened 2022-11-09 04:31 UTC
### Godot version

v4.0.beta4.official [e6751549c]

### System information

Windows 11 Pro 64Bit Edge/Firefox/Chrome/Opera -|- Linux Mint 21 Cinnamon 64Bit Firefox/Chrome

### Issue description

Hi,

In Beta 5,
You need to add an opt out when building HTML5 for:
"Cross Origin Isolation"
"SharedArrayBuffer"

Our Godot v4.0 Beta 4 HTML5 game does not work on popular [itch.io](https://betamaxhero.itch.io/gdscript-godot-4-t-story) publishing website.

Jesse

### Steps to reproduce

View:
[https://betamaxhero.itch.io/gdscript-godot-4-t-story](https://betamaxhero.itch.io/gdscript-godot-4-t-story)
in your web browser of choice...

HTML5 working on New Grounds:
https://www.newgrounds.com/projects/games/1946017/preview

**Comment by clayjohn** [comment] 2022-11-09 06:23
Looks like you need to enable the required settings. Described here: https://github.com/godotengine/godot/issues/68180#issuecomment-1302352717 where the user got it working. 

At any rate, this is a duplicate of #68180. So closing in favour of #68180. Please remember to search through existing issues before opening a new issue

**Closed by clayjohn** 2022-11-09 06:23 UTC
