### ISSUE TITLE
Editor crash when using Polygon2D node

### ISSUE THREAD

**Issue by CHmSID** [godotengine/godot#59152] opened 2022-03-14 21:56 UTC
### Godot version

v4.0.alpha4.official [f47097973]

### System information

Linux Manjaro x86_64 Kernel 5.4.178-1-MANJARO

### Issue description

Editor hard crashes when using Polygon2D node. The issue seems similar to #51298 except in this case the array of points has not been resized down.

- The crash can be reproduced in an empty new project.
- I could not reproduce the crash in v3.4.stable.official [206ba70f4]

### Steps to reproduce

1. Create new project. As far as I can tell, it doesn't matter if Vulcan Clustered or Mobile is selected.
2. Set the scene to type of Node2D, then add a child node Polygon2D
![Screenshot_20220314_224317](https://user-images.githubusercontent.com/6818394/158266437-7e2da247-d0b7-4d58-a9fb-8823f5189ca9.jpeg)
3. Click on the Polygon array button and set the size to 4
![Screenshot_20220314_224604](https://user-images.githubusercontent.com/6818394/158266757-7e160f7b-49af-4f11-8d05-c8dc6f8513bf.jpeg)
4. Fill in the vertex data as shown on the screenshot below:
![Screenshot_20220314_224727](https://user-images.githubusercontent.com/6818394/158266902-b0e97906-4068-4b32-87ae-3191a1b413a9.jpeg)
5. IMPORTANT click again on the Polygon array button to close the vertex information panel:
![Screenshot_20220314_224833](https://user-images.githubusercontent.com/6818394/158266980-6dd6ddee-2612-48bd-8cca-ca2377964a5a.jpeg)
6. Click on the parent node
![Screenshot_20220314_224926](https://user-images.githubusercontent.com/6818394/158267085-bdbedc20-d183-4a39-a937-600cd09a2ce5.jpeg)
7. Editor hard crashes.

### Minimal reproduction project

I have attached a project with which you can reproduce the issue:
[test.zip](https://github.com/godotengine/godot/files/8248711/test.zip)

After opening the project, select the Polygon2D node, and in the properties dialog on the right simply close the Polygon array list by clicking on the blue text. Then click on the Node2D on the left.

I hope this helps. Let me know if you need more information.

**Comment by KoBeWi** [comment] 2022-03-15 00:01
Can't reproduce in the newest master nor in the mentioned version. Using Windows 10.

Stack trace would be useful.

**Comment by akien-mga** [comment] 2022-03-15 07:48
Sounds related to #59018 which was a crash in `EditorPropertyDictionary`, fixed by https://github.com/godotengine/godot/pull/58751/files#diff-17781aa265945f5f8988f4d66150a04b73fcdd99f5600b24409d731d24e6fbf1R1147.

`Polygon2D`'s inspector has various `EditorPropertyArray`s as shown above, and they seem to suffer from the same bug that #58751 did not fix.

**Comment by akien-mga** [comment] 2022-03-15 07:55
I could reproduce the issue too on latest `master` on Linux, here's a stacktrace:
```
================================================================
handle_crash: Program crashed with signal 11
Engine version: Godot Engine v4.0.alpha.custom_build (e4b94063137c57a723c227856497f36d063b7903)
Dumping the backtrace. Please include this when reporting the bug on https://github.com/godotengine/godot/issues
[1] /lib64/libc.so.6(+0x403a0) [0x7ffb682523a0] (??:0)
[2] /home/akien/Projects/godot/godot.git/bin/godot.linuxbsd.tools.64(__dynamic_cast+0x3f) [0x9a4e52f] (/home/iurt/rpmbuild/BUILD/gcc-12-20220306/obj-x86_64-mageia-linux/x86_64-mageia-linux/libstdc++-v3/libsupc++/../../../../libstdc++-v3/libsupc++/dyncast.cc:71)
[3] Button* Object::cast_to<Button>(Object*) (/home/akien/Projects/godot/godot.git/./core/object/object.h:656 (discriminator 1))
[4] EditorPropertyArray::_notification(int) (/home/akien/Projects/godot/godot.git/editor/editor_properties_array_dict.cpp:518 (discriminator 12))
[5] EditorPropertyArray::_notificationv(int, bool) (/home/akien/Projects/godot/godot.git/editor/editor_properties_array_dict.h:81 (discriminator 14))
[6] Object::notification(int, bool) (/home/akien/Projects/godot/godot.git/core/object/object.cpp:830)
[7] Control::_propagate_theme_changed(Node*, Control*, Window*, bool) (/home/akien/Projects/godot/godot.git/scene/gui/control.cpp:2575)
[8] Control::_propagate_theme_changed(Node*, Control*, Window*, bool) (/home/akien/Projects/godot/godot.git/scene/gui/control.cpp:2560)
[9] Control::_propagate_theme_changed(Node*, Control*, Window*, bool) (/home/akien/Projects/godot/godot.git/scene/gui/control.cpp:2560)
[10] Control::remove_child_notify(Node*) (/home/akien/Projects/godot/godot.git/scene/gui/control.cpp:672)
[11] Container::remove_child_notify(Node*) (/home/akien/Projects/godot/godot.git/scene/gui/container.cpp:73)
[12] Node::remove_child(Node*) (/home/akien/Projects/godot/godot.git/scene/main/node.cpp:1180)
[13] Node::_notification(int) (/home/akien/Projects/godot/godot.git/scene/main/node.cpp:157)
[14] Node::_notificationv(int, bool) (/home/akien/Projects/godot/godot.git/./scene/main/node.h:45 (discriminator 14))
[15] CanvasItem::_notificationv(int, bool) (/home/akien/Projects/godot/godot.git/./scene/main/canvas_item.h:45)
[16] Control::_notificationv(int, bool) (/home/akien/Projects/godot/godot.git/./scene/gui/control.h:46)
[17] Container::_notificationv(int, bool) (/home/akien/Projects/godot/godot.git/./scene/gui/container.h:37)
[18] EditorInspectorSection::_notificationv(int, bool) (/home/akien/Projects/godot/godot.git/editor/editor_inspector.h:261)
[19] Object::notification(int, bool) (/home/akien/Projects/godot/godot.git/core/object/object.cpp:830)
[20] Object::_predelete() (/home/akien/Projects/godot/godot.git/core/object/object.cpp:355)
[21] predelete_handler(Object*) (/home/akien/Projects/godot/godot.git/core/object/object.cpp:1872)
[22] void memdelete<Node>(Node*) (/home/akien/Projects/godot/godot.git/./core/os/memory.h:104)
[23] EditorInspector::_clear() (/home/akien/Projects/godot/godot.git/editor/editor_inspector.cpp:2965)
[24] EditorInspector::edit(Object*) (/home/akien/Projects/godot/godot.git/editor/editor_inspector.cpp:2986)
[25] EditorNode::_edit_current(bool) (/home/akien/Projects/godot/godot.git/editor/editor_node.cpp:2215)
[26] EditorNode::push_item(Object*, String const&, bool) (/home/akien/Projects/godot/godot.git/editor/editor_node.cpp:2112)
[27] SceneTreeDock::_push_item(Object*) (/home/akien/Projects/godot/godot.git/editor/scene_tree_dock.cpp:1342 (discriminator 2))
[28] SceneTreeDock::_node_selected() (/home/akien/Projects/godot/godot.git/editor/scene_tree_dock.cpp:1357)
[29] void call_with_variant_args_helper<SceneTreeDock>(SceneTreeDock*, void (SceneTreeDock::*)(), Variant const**, Callable::CallError&, IndexSequence<>) (/home/akien/Projects/godot/godot.git/./core/variant/binder_common.h:237 (discriminator 4))
[30] void call_with_variant_args<SceneTreeDock>(SceneTreeDock*, void (SceneTreeDock::*)(), Variant const**, int, Callable::CallError&) (/home/akien/Projects/godot/godot.git/./core/variant/binder_common.h:347)
[31] CallableCustomMethodPointer<SceneTreeDock>::call(Variant const**, int, Variant&, Callable::CallError&) const (/home/akien/Projects/godot/godot.git/./core/object/callable_method_pointer.h:105)
[32] Callable::call(Variant const**, int, Variant&, Callable::CallError&) const (/home/akien/Projects/godot/godot.git/core/variant/callable.cpp:64)
[33] MessageQueue::_call_function(Callable const&, Variant const*, int, bool) (/home/akien/Projects/godot/godot.git/core/object/message_queue.cpp:230)
[34] MessageQueue::flush() (/home/akien/Projects/godot/godot.git/core/object/message_queue.cpp:277)
[35] SceneTree::physics_process(double) (/home/akien/Projects/godot/godot.git/scene/main/scene_tree.cpp:421)
[36] Main::iteration() (/home/akien/Projects/godot/godot.git/main/main.cpp:2639)
[37] OS_LinuxBSD::run() (/home/akien/Projects/godot/godot.git/platform/linuxbsd/os_linuxbsd.cpp:357)
[38] /home/akien/Projects/godot/godot.git/bin/godot.linuxbsd.tools.64(main+0x136) [0x55d0f5c] (/home/akien/Projects/godot/godot.git/platform/linuxbsd/godot_linuxbsd.cpp:60)
[39] /lib64/libc.so.6(+0x2d177) [0x7ffb6823f177] (??:0)
[40] /lib64/libc.so.6(__libc_start_main+0x85) [0x7ffb6823f235] (??:0)
[41] /home/akien/Projects/godot/godot.git/bin/godot.linuxbsd.tools.64(_start+0x21) [0x55d0d61] (??:?)
-- END OF BACKTRACE --
================================================================
```

That confirms it's very similar to #59018 and my fix should work.

**Closed** 2022-03-15 08:36 UTC
Labels: bug, topic:editor, confirmed, crash, topic:2d
