### ISSUE TITLE
Shader noise issues with Forward+ renderer

### ISSUE THREAD

**Issue by pancelor** [godotengine/godot#84871] opened 2023-11-14 04:09 UTC
### Godot version

v4.2.beta.custom_build [4c96e9676]

### System information

Godot v4.2.beta (4c96e9676) - Manjaro Linux #1 SMP PREEMPT Sat Sep 23 10:10:02 UTC 2023 - X11 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 750 Ti (nvidia; 535.129.03) - AMD FX(tm)-8350 Eight-Core Processor (8 Threads)

### Issue description

I was having strange issues with some shader code; I tracked it down to my noise function producing weird discontinuities when running on the Forward+ renderer. The noise function itself is well-known/well-tested [code from the book of shaders ](https://thebookofshaders.com/11/)

Switching to Compatibility rendering fixes the discontinuities. (Mobile rendering looks the same as Forward+)

![visual discontinuities under Forward+ rendering in a noise texture](https://github.com/godotengine/godot/assets/11308928/a246446a-7373-496b-a348-f9244f58d629)

```glsl
shader_type canvas_item;

uniform float s1 = 10.0;

// random() + noise() from book of shaders:
// https://thebookofshaders.com/11/

float random (in vec2 st) {
	return fract(sin(dot(st.xy,vec2(12.9898,78.233))) * 43758.5453123);
}

// 2D Noise based on Morgan McGuire @morgan3d
// https://www.shadertoy.com/view/4dS3Wd
float noise (in vec2 st) {
	vec2 i = floor(st);
	vec2 f = fract(st);

	// Four corners in 2D of a tile
	float a = random(i);
	float b = random(i + vec2(1.0, 0.0));
	float c = random(i + vec2(0.0, 1.0));
	float d = random(i + vec2(1.0, 1.0));

	// Smooth Interpolation

	// Cubic Hermine Curve.  Same as SmoothStep()
	vec2 u = f*f*(3.0-2.0*f);
	// u = smoothstep(0.,1.,f);

	// Mix 4 coorners percentages
	return mix(a, b, u.x) +
		(c - a)* u.y * (1.0 - u.x) +
		(d - b) * u.x * u.y;
}

void fragment() {
	COLOR.rgb = vec3(noise(UV*s1));
}
```

The issue is also present in `v4.1.2.stable.arch_linux` on my machine

### Steps to reproduce

- Open the minimal repro project; notice the unexpected discontinuities in the noise texture (visible in the editor preview)
- Switch the renderer to Compatilibility; the discontinuities are gone (as expected)

### Minimal reproduction project

[shader-noise-bug.zip](https://github.com/godotengine/godot/files/13344307/shader-noise-bug.zip)

**Comment by bitsawer** [comment] 2023-11-14 06:20
Thanks for the report! This issue seems to be a duplicate of https://github.com/godotengine/godot/issues/67150. This is an NVIDIA specific Vulkan issue, there are several workarounds mentioned in the linked thread that might help. Closing as duplicate.

**Closed by bitsawer** 2023-11-14 06:20 UTC
