### ISSUE TITLE
Editor Menu Buttons remain in the pressed state

### ISSUE THREAD

**Issue by MattUV** [godotengine/godot#14881] opened 2017-12-20 20:16 UTC
**Godot version:**
3.0 current master 03823f1 (NOT in 3.0 beta, where it works well)

**OS/device including version:**
Winows 8.1

**Issue description:**

- [ ] When you click the Menu buttons in the editor, they get "pressed" and become blue (default theme), but they remain like this even when not pressed anymore.

- [ ] If a menu is open, the next click in the engine window will close the menu, but will be ignored.

I think that bug appeared approximately 24h ago. It is theme independant.

**Steps to reproduce:**
Open any project, and click on the Menu Button Scene, Project, Debug, Editor, Help
![menu](https://user-images.githubusercontent.com/13215043/34226724-e5ed6e56-e5ca-11e7-911d-1777b064c546.png)

**Comment by Noshyaar** [comment] 2017-12-20 20:23
Duplicate of #14854

**Closed by Noshyaar** 2017-12-20 20:23 UTC

**Comment by MattUV** [comment] 2017-12-20 20:25
Oops! Sorry about that...
