### ISSUE TITLE
Moving from GLES3 to GLES2 glitches some models

### ISSUE THREAD

**Issue by gamedevboi** [godotengine/godot#42781] opened 2020-10-13 19:52 UTC
**Godot version:**
Godot 3.2.3 Stable Standard x64

**OS/device including version:**
Android, mainly I'm testing in Google Pixel 2 (Emulated), But I also tested on the following: Asus ROG(Emulated), Samsung Galaxy A01(Real) Nexus 7 (Real), Moto g7 (Real), LG Q6 alpha (Real)

**Issue description:**
I created a 3d game for PC using GLES3, very low poly, I was going for a PSX look. I want to make the port to mobile, and in order to get better performance I switched to GLES2 that version of the project, most of it is good but lower quality just like I expected but there's 2 models, that are glitched out.  

This is how they're suppose to look:
![Screenshot_71](https://user-images.githubusercontent.com/22928178/95902115-f181d400-0d59-11eb-96e0-738563ffa0d2.png)

This is how they look on every mobile device I tested: 
![Screenshot_72](https://user-images.githubusercontent.com/22928178/95902185-0c544880-0d5a-11eb-9f96-2f55ce187e07.png)

**Steps to reproduce:**

I uploaded a simple project, with the models that are glitching, I'm not sure what I'm doing wrong, You just need add the android build yourself since I can't upload the whole project beacause it would be around 77mb, and then export to android and you'll see the issue once you open the app in a phone, real or simulated it's the same issue.

[Glitched models.zip](https://github.com/godotengine/godot/files/5373738/Glitched.models.zip)

Thanks everyone I hope you guys can help me find a solution, I'm thinking this may have something to do with how GLES2 handles bones or animations, because nothing else in the real game is broken, just this 2 and are the ones with animations and bones.

**Comment by gamedevboi** [comment] 2020-10-13 20:37
> Skinning is handled in a different way in GLES2. See #40313 which attempted to fix this, but there are regressions which need to be fixed.

Sorry I'm not getting this, Is there like an setting I need to turn on to enable software skinning? Im sorry to bother.

**Comment by Calinou** [comment] 2020-10-13 22:00
@gamedevboi As far as I know, there's no way to configure skinning using a setting (when using GLES2 at least).

**Comment by gamedevboi** [comment] 2020-10-13 22:10
Ohh, thank you! I hope this issue can be solved soon. :) 

> @gamedevboi As far as I know, there's no way to configure skinning using a setting (when using GLES2 at least). You'll have to wait for a fix to land in 3.2.4 or a later point release.
Oh gotcha! Thanks I hope this issue can be solved soon! :)

**Comment by lawnjelly** [comment] 2020-10-14 07:20
This looks like a bug in one of the hardware skinning paths.

You will be able to get around it by changing a project setting to `forcing software skinning` once the regressions are sorted, however it is not ideal because software skinning is intended as a backup path, with the defaults this same situation could still glitch for other developers.

I would normally suspect precision in the shader, but you say it is occurring on emulators which normally have full precision. What platform / OS / emulator are you running?

We may be delayed at looking at this until the software skinning regressions are fixed.

**Comment by gamedevboi** [comment] 2020-10-14 18:30
I'm using memu as emulator and usually I emulate a google pixel 2 tablet with the most recent android available, I think it's 7.1.2 atm, at least that's what the tablet says. Mmmm, it may be stupid for me to ask, but how you change that setting forcing software skinning? I can't find where can I change that to just try and see what happens

**Comment by lawnjelly** [comment] 2020-10-14 18:46
It's not possible to do yet in 3.2.3, software skinning has only just been merged into 3.2 branch, and there are still some regressions to fix. Should be available in 3.2.4... there will be betas quite soon I'm sure.

**Comment by akien-mga** [comment] 2022-04-06 21:37
Seems fixed in 3.4.

GLES3:
![image](https://user-images.githubusercontent.com/4701338/162075741-a9256cb6-aad5-4176-a082-51a17f701ed9.png)

GLES2:
![image](https://user-images.githubusercontent.com/4701338/162075806-59ad1b87-bf41-46d5-9a91-0acab7e83115.png)

**Closed by akien-mga** 2022-04-06 21:37 UTC
Labels: bug, topic:rendering
