### ISSUE TITLE
Label with custom font gets misaligned after resizing with 2d scretch mode

### ISSUE THREAD

**Issue by manokara** [godotengine/godot#42257] opened 2020-09-23 03:14 UTC
**Godot version:**
3.2.3 Stable Official

**OS & Hardware:**
Solus/Linux 5.6.19
Ryzen 5 2400G (+RX Vega 11 iGPU)
GLES2 renderer

**Issue description:**
Resizing the window shifts the label (which is anchored to the center) slightly to the right, making it not align with the Node2Ds behind it. This does not happen with the default font, and I have not tested if this also happens with a BitmapFont. My repro project below uses a DynamicFont.

- Demonstration 1: https://streamable.com/1da7gk
- Demonstration 2 (more perceptible): https://streamable.com/9j7qjl

**Steps to reproduce:**

1. Add one or more Node2Ds to the scene
2. Add a root Control node that covers the entire viewport and a Label as a child anchored to Center
3. Set viewport stretch mode to 2d
4. Run the scene: Resize the window so it becomes small enough, then resize it back to the original size or larger. The Node2Ds will not align with the label.

**Minimal reproduction project:**
https://mega.nz/file/fVdxEIYC#1XaMSVvjFN7YKNG8JLP5F38ooe1WtpLa7ffi5jjBbi4

**Comment by Calinou** [comment] 2020-09-23 12:00
As a workaround, try disabling **Rendering > Quality > Dynamic Fonts > Use Oversampling** in the Project Settings.

**Comment by Calinou** [comment] 2021-03-17 13:05
Duplicate of https://github.com/godotengine/godot/issues/37242 (same cause).

**Closed by Calinou** 2021-03-17 13:05 UTC
Labels: bug, topic:core, topic:rendering
