### ISSUE TITLE
Adding a CollisionShape2D node crashes Godot

### ISSUE THREAD

**Issue by SamDevelopsCode** [godotengine/godot#76618] opened 2023-04-30 15:29 UTC
### Godot version

4.0.3

### System information

Linux Mint 21.1 Cinnamon

### Issue description

Adding a CollisionShape2D crashes Godot Engine.

Crash replicated across scenes and projects. Completely fresh projects crash as well.

### Steps to reproduce

1. Create new scene or open existing.
2. Add new CollisionShape2D node. Crashes on step 2.

### Minimal reproduction project

N/A

**Comment by ghsoares** [comment] 2023-04-30 15:36
I had this exact same issue now when trying to add custom code to my engine build in 4.0 branch, does it also crash by simply adding the CollisionShape2D as child of any node?

I have a suspect that the `Ref<Shape2D> shape` is not initialized to an empty reference so it is initialized with random memory, looking like it is a valid reference, but when trying to get any property of the reference, the editor crashes. I'm testing right now to see if it's the culprit.

**Comment by SamDevelopsCode** [comment] 2023-04-30 15:40
Good catch! It actually is adding it to **any** node, not Area2Ds. Will edit

**Comment by ghsoares** [comment] 2023-04-30 15:52
Ok, I think I've found the issue, in `collision_shape_2d_editor_plugin.cpp` (source code to edit CollisionShape2D's) there is a variable called `shape_type`, which is used to check which type of shape the editor is currently editing, the problem is that it needs to be `-1` to represent an invalid or null shape reference, but the function that is called when the shape is changed (`_shape_changed`), isn't setting this variable to `-1` when the shape is null.

So the issue isn't with the CollisionShape2D node, but with the editor plugin that edits it. By making the edit function set `shape_type` to `-1` when shape is null makes it work. See the source  code: https://github.com/godotengine/godot/blob/fdf66b3472e5ca254a4f90c32f26c4702d46828b/editor/plugins/collision_shape_2d_editor_plugin.cpp#L377-L415
It should have `shape_type = -1;` on line 395, like this:
```cpp
	current_shape = node->get_shape();

	if (current_shape.is_valid()) {
		current_shape->connect(SceneStringNames::get_singleton()->changed, callable_mp(canvas_item_editor, &CanvasItemEditor::update_viewport));
	} else {
		shape_type = -1; // Here
		return;
	}
```

**Comment by adamscott** [comment] 2023-04-30 15:56
> It should have `shape_type = -1;` on line 395, like this:
> 
> ```c++
> 	current_shape = node->get_shape();
> 
> 	if (current_shape.is_valid()) {
> 		current_shape->connect(SceneStringNames::get_singleton()->changed, callable_mp(canvas_item_editor, &CanvasItemEditor::update_viewport));
> 	} else {
> 		shape_type = -1; // Here
> 		return;
> 	}
> ```

@KoBeWi Could you confirm?

**Comment by KoBeWi** [comment] 2023-04-30 16:01
Duplicate of #76543
The issue is already fixed on master.

> It should have shape_type = -1; on line 395, like this:

This is not needed. The crash only happened, because the initial value set in constructor was `0` instead of `-1`.

**Closed by KoBeWi** 2023-04-30 16:01 UTC
Labels: topic:editor, confirmed, topic:physics, crash, topic:2d
