### ISSUE TITLE
[Godot 4 - Alpha 4] Applying a new color ramp to GPUParticle require closing and reopening scene

### ISSUE THREAD

**Issue by profjle** [godotengine/godot#59032] opened 2022-03-11 14:35 UTC
### Godot version

4.0 Alpha 4

### System information

Windows 10

### This is for both 2D and 3D GPUParticles. 

Color ramps will initially work (most of the times) but if you intend on creating another ramp, you need to close the scene and reopen it. 

[Here's what happens](https://imgur.com/a/GBH8EaH)

### Steps to reproduce

Create particle and add a color ramp. You will not see the gradient applied to the mesh. You will then need to close and reopen the particle scene to see the gradient applied.

**Comment by Calinou** [comment] 2022-03-11 17:34
Duplicate of https://github.com/godotengine/godot/issues/57471.

**Closed by Calinou** 2022-03-11 17:34 UTC
