### ISSUE TITLE
In 2D games, movement in eight directions is not in a straight line.

### ISSUE THREAD

**Issue by aithority** [godotengine/godot#87224] opened 2024-01-15 16:40 UTC
### Tested versions

v4.2.1.stable.official [b09f793f5]

### System information

Window 11 v4.2.1.stable.official [b09f793f5]

### Issue description

In 2D games, movement in eight directions is not in a straight line. 

BUG Video：https://www.youtube.com/watch?v=Y5tSu1m3DBs

### Steps to reproduce

My code is as follows：

```
func _physics_process(_delta):
	# 获取窗口的边界
	var viewport_rect = get_viewport_rect()
	# 获取鼠标的位置
	var viewport_mouse_position = get_viewport().get_mouse_position()
	# 默认速度
	var speed = 0
	# 默认步长，将影响玩家最终的走位
	var step_length = 10
	# 检查鼠标是否在窗口内
	if viewport_rect.has_point(viewport_mouse_position):
		# 获取玩家的位置
		var player_position = position
		# 获取鼠标的位置
		var mouse_position = get_local_mouse_position()
		# 获取鼠标的角度(以弧度为单位)并捕捉最接近45度的倍数(0,1,2,3,4,-4,-3,-2,-1)
		var angle = snapped(mouse_position.angle(), PI/4) / (PI/4)
		# 将获取的倍数分别除以45度(0,1,2,3,4,5,6,7)
		player_angle = wrapi(int(angle), 0, 8)
		# 计算方向向量
		var direction = Vector2(cos(player_angle * PI/4), sin(player_angle * PI/4))
		# 鼠标左右键按下时触发
		if Input.is_action_pressed("walking") or Input.is_action_pressed("running"):
			# 更新速度
			if Input.is_action_pressed("walking"):
				player_action = "walking"
				# 鼠标左键行走
				speed = 60
			if Input.is_action_pressed("running"):
				player_action = "running"
				# 鼠标左键奔跑
				speed = 100
			if speed > 0:
				# 鼠标位置距离玩家多远才触发
				if mouse_position.length() > 10:
					$Father/Stand.animation = str(player_angle) + "_" + player_action
					velocity = direction.normalized() * speed
					move_and_slide()
		if Input.is_action_just_released("walking") or Input.is_action_just_released("running"):
			speed = 0
			velocity = Vector2.ZERO
			player_action = "stand"
			$Father/Stand.animation = str(player_angle) + "_" + player_action
```

### Minimal reproduction project (MRP)

Github：https://github.com/aithority/engine

**Comment by Calinou** [comment] 2024-01-15 16:49
This is very likely an issue with how your code calculates movement direction in diagonals (not all "isometric" game setups involve true 45-degree movement), or floating-point precision error (which is not something that can be fixed in the engine).

**Comment by bs-mwoerner** [comment] 2024-01-15 17:29
Yes. Your character walks in a 45° angle, but your map tiles are not arranged in a 45° grid.
![grafik](https://github.com/godotengine/godot/assets/35597337/dae02448-11db-4c97-946d-ee0814a15d46)

**Comment by kleonc** [comment] 2024-01-15 18:00
Movement works according to the code. This is a user error/misunderstanding, not a bug.

I don't see anything needing to be documented here. Hence closing.

@aithority For getting help with your project please use other [community channels](https://godotengine.org/community/) (Godot forum, Discord, Reddit, etc.), this is a bugtracker.

**Closed by kleonc** 2024-01-15 18:00 UTC
Labels: topic:core, needs testing
