### ISSUE TITLE
Arrays and Dictionary bracket not autocomplete with variable name

### ISSUE THREAD

**Issue by DexterFstone** [godotengine/godot#86149] opened 2023-12-14 07:11 UTC
### Tested versions

reproducible in Godot 4.2.stable

### System information

Windows 10, Godot 4.2 Stable

### Issue description

when I try to write [varable_name] it's not suggested a variable name
```gdscript
		var game_match : GameMatch = GameMatch.new()
		game_match.id = game_matchs.size() + 1
		game_matchs[game_match.id]
```
last line in [] a need to write `game_match.id` without any suggestion or autocompletion

https://github.com/godotengine/godot/assets/92402263/7017218d-602e-45d6-82be-944513056937

### Steps to reproduce

```gdscript
var test_value = 5
var arr = []
arr[t...]
```

### Minimal reproduction project (MRP)

N/A

**Comment by TheSofox** [comment] 2023-12-15 23:33
Confirmed.

Basically autocomplete within array brackets acts like it's a dot operator of the array rather than an index: Observe:

![image](https://github.com/godotengine/godot/assets/3089525/78b3a215-4e0c-427d-ba8d-c403de361859)

![image](https://github.com/godotengine/godot/assets/3089525/2c196751-a278-4595-95d2-bf4da94b9dd1)

**Comment by DexterFstone** [comment] 2023-12-16 06:15
@TheSofox write variable name inside brackets
![image](https://github.com/godotengine/godot/assets/92402263/6dcf9b42-9615-4b1e-b130-b0c5c8acb58a)
my num variable does not exist

**Comment by TheSofox** [comment] 2023-12-16 15:16
Duplicate of #76955 and #83074

Pull request https://github.com/godotengine/godot/pull/79378 claims to fix this but has not been merged yet.

**Comment by AThousandShips** [comment] 2023-12-16 17:50
Duplicate of https://github.com/godotengine/godot/issues/76955

**Closed by AThousandShips** 2023-12-16 17:50 UTC
