### ISSUE TITLE
Visual Script is not version control friendly

### ISSUE THREAD

**Issue by programingfrik** [godotengine/godot#64522] opened 2022-08-17 05:13 UTC
### Godot version

Any

### System information

Any

### Issue description

I like visual script in godot, I think is under appreciated, but one key feature that is missing is making it version control friendly. As it is right now visual scripts files are saved in some special binary format, so every time that some change is made git saves the whole thing over and over. That also means that multi-person projects are a bit more difficult with visual script.

I think that visual script files should be saved in some kind of text based format, json, xml, or its own thing. It should be something that keeps the file inside with the least changes possible, so if, for example I change the position of one node the representation inside the file of the other untouched nodes and their relative order should not change.

This is a hell of feature that I'm asking for, I know, but as it is said in the documentation one big reason for visual script to exist is presenting a tool for non-coders to change small behaviors on the game, in that scenario I can imagine that we are talking about a project with multiple people, if they can't diff or merge visual script files that makes that multi-person flow more difficult.

### Steps to reproduce

1 - Write a visual script
2 - Save it to your drive
3 - Put it on some version control system (git maybe)
4 - Make a change to the visual script and save it
5 - Try to see the diff (it won't allow you is a binary format)
6 - add and commit
7 - Try to see the diff between the two versions (it won't allow you is binary).

**Comment by timothyqiu** [comment] 2022-08-17 09:11
Although can't be created directly, you can save your visual script as a `tres` file. The `tres` file is the same as the `vs` file, but in text format.

**Comment by tinmanjuggernaut** [comment] 2022-08-17 10:17
> you can save your visual script as a tres file. 

This is the solution. All resources in Godot can (and should, IMO) be saved as text tres files so they are git friendly. Including materials, scenes, and we even do our meshes. The only thing we save as binary are textures - the only thing Godot won't arbitrarily change.

**Comment by Calinou** [comment] 2022-08-17 11:57
Duplicate of https://github.com/godotengine/godot-proposals/issues/938.

**Closed by Calinou** 2022-08-17 11:57 UTC
Labels: enhancement, topic:visualscript
