### ISSUE TITLE
CSGPolygon3D mode Path crashes when setting path_interval

### ISSUE THREAD

**Issue by Giganzo** [godotengine/godot#100073] opened 2024-12-05 22:31 UTC
### Tested versions

Godot v4.4.dev6

### System information

Fedora Linux 40 (KDE Plasma) on Wayland - X11 display driver, Multi-window

### Issue description

CSGPolygon3D mode Path crashes when setting path_interval in the inspector with a path that has in or out set on a point.
The value in path_interval for crash seems to depend on the path shape.

```
handle_crash: Program crashed with signal 11
Engine version: Godot Engine v4.4.dev6.official (1f47e4c4e3a09a422e96880a7918d986dd575a63)
Dumping the backtrace. Please include this when reporting the bug to the project developer.
Fatal glibc error: malloc.c:4192 (_int_malloc): assertion failed: chunk_main_arena (fwd)
```

### Steps to reproduce

Add a path3d and add 2 points and set in or out for a point.
Add a CSGPolygon3D and set mode to Path and assign the Path3d
Change path_interval value

### Minimal reproduction project (MRP)

[csgpath.zip](https://github.com/user-attachments/files/18030490/csgpath.zip)

**Comment by fire** [comment] 2024-12-05 22:38
Will see if the trigonometry fix pr can be modified to fix this.

**Comment by fire** [comment] 2024-12-05 22:48
I cannot reproduce but am on https://github.com/godotengine/godot/pull/100020 Will retry with dev6.

**Comment by fire** [comment] 2024-12-05 22:58
# dev6

Crashes 

# custom fork on top of 4.4 https://github.com/V-Sekai/godot/commit/75727b08dc2c675f5912562e89aa80bca91de269

Change path_interval value doesn't crash.

https://github.com/user-attachments/assets/b90be753-fd66-424c-bae8-f0ff33907799

# Next steps

Need to bisect git.

**Comment by fire** [comment] 2024-12-05 23:15
This doesn't happen on godot engine master eb5103093c1bfd4d527ec1255d28e9bc8d3625b5 only on https://github.com/godotengine/godot/commit/1f47e4c4e3a09a422e96880a7918d986dd575a63 commit.

```bash
% 2024-12-05 15:13:34.420 godot.macos.editor.universal[26548:1805135] +[IMKClient subclass]: chose IMKClient_Modern
2024-12-05 15:13:35.940 godot.macos.editor.universal[26548:1805135] +[IMKInputSession subclass]: chose IMKInputSession_Modern

================================================================
handle_crash: Program crashed with signal 11
Engine version: Godot Engine v4.4.dev.gh-100020 (58c119260602a3ca5a3a5ef1671e34eb65282003)
Dumping the backtrace. Please include this when reporting the bug to the project developer.
[1] 1   libsystem_platform.dylib            0x0000000191140184 _sigtramp + 56
[2] CameraServer* CameraServer::_create_builtin<CameraMacOS>()
[3] CameraServer* CameraServer::_create_builtin<CameraMacOS>()
[4] CameraServer* CameraServer::_create_builtin<CameraMacOS>()
[5] CameraServer* CameraServer::_create_builtin<CameraMacOS>()
[6] CameraServer* CameraServer::_create_builtin<CameraMacOS>()
[7] CameraServer* CameraServer::_create_builtin<CameraMacOS>()
[8] PlaceholderExtensionInstance::placeholder_class_recreate_instance(void*, void*)
[9] PlaceholderExtensionInstance::placeholder_class_recreate_instance(void*, void*)
[10] Node::atr_n(String const&, StringName const&, int, StringName const&) const
[11] RendererCompositorRD::_create_current()
[12] 12  godot.macos.editor.universal        0x0000000103244104 godot.macos.editor.universal + 3834116
[13] RendererCompositorRD::_create_current()
[14] 14  dyld                                0x0000000190d88274 start + 2840
-- END OF BACKTRACE --
================================================================
```

**Comment by fire** [comment] 2024-12-06 19:04
Closing due to comment https://github.com/godotengine/godot/issues/100095#issuecomment-2523372543

**Closed by fire** 2024-12-06 19:04 UTC
Labels: bug, crash, regression, topic:3d
