### ISSUE TITLE
Godot GUI bug on Windows 10 when I click on "Play Custom Scene (Shift+Ctrl+F5)

### ISSUE THREAD

**Issue by Qws** [godotengine/godot#7370] opened 2016-12-25 15:38 UTC
**Operating system or device - Godot version:**
Windows 10, Sony Vaio Pro 13, Godot 2.1.1 Stable.Official

**Issue description** (what happened, and what was expected):
When I click "Play Custom Scene (Shift Ctrl F5)" the pop-up will sometimes sit behind the code-editor, and no way to pull it to the front. 
![image](https://cloud.githubusercontent.com/assets/3944421/21471796/ad0ce12a-cabe-11e6-8410-88a49844c413.png)

If you look at the image you see what I mean, between the output Window and Code editor, you see 2 button: Open and Cancel. Which is from the "Play Custom Scene Shift Ctrl F5". I've absolutely no idea what I can do against it.

**Steps to reproduce:**
It seems it only happens on my laptop so far, and not on my desktop, and when it happens on my laptop there was most of the time some compile error.

**Link to minimal example project** (optional but very welcome):
I don't think it's relevant, but it who knows. It's just me testing out few things with Godot.
[Fire.zip](https://github.com/godotengine/godot/files/672244/Fire.zip)

**Comment by Zylann** [comment] 2016-12-25 15:44
Duplicate of https://github.com/godotengine/godot/issues/7187 and https://github.com/godotengine/godot/issues/7140, was it really fixed?
It happened to me too on other various dialogs in 2.1.1.

**Comment by volzhs** [comment] 2016-12-25 18:56
I saw a code causing this. But I've not found a way to fix it in proper way. :(

**Comment by bojidar-bg** [comment] 2016-12-27 11:58
@volzhs #6778 isn't enough?

Closing as duplicate of lots of lots of issues (like #7187 and #7140).

It was fixed in master, just not yet backported to 2.1. (@akien-mga)

**Closed by bojidar-bg** 2016-12-27 11:58 UTC

**Comment by akien-mga** [comment] 2017-01-02 12:55
It is backported to 2.1 already, just not released yet. ed2c3697854326a9023e65cb76763cf85ce0010f
