### ISSUE TITLE
Intel graphic driver bug?

### ISSUE THREAD

**Issue by albinaask** [godotengine/godot#42055] opened 2020-09-14 14:19 UTC
Two bugs that seem to be closely linked:
Everything looks fine
![bild](https://user-images.githubusercontent.com/11806563/93095964-12e09900-f6a4-11ea-9e76-9323f3247e19.png)

Grid's gone
![bild](https://user-images.githubusercontent.com/11806563/93096109-46bbbe80-f6a4-11ea-80d3-1782eaf87270.png)

As fast as any object with "null" or empty material is rendered it happends

![bild](https://user-images.githubusercontent.com/11806563/93096226-6bb03180-f6a4-11ea-9c93-71312841dbf6.png)

When a material is spawned everything's fine:

![bild](https://user-images.githubusercontent.com/11806563/93096291-81bdf200-f6a4-11ea-9def-945c2a9ad525.png)

This bug is somewhat annoying, however not terrible. The problem really starts when adding another material alongside it: 

only default material:

![bild](https://user-images.githubusercontent.com/11806563/93096678-f7c25900-f6a4-11ea-9e1c-0a325f4eed90.png)

only non-default material:

![bild](https://user-images.githubusercontent.com/11806563/93096733-09a3fc00-f6a5-11ea-85d9-f93bdf37f069.png)

Both: 

![bild](https://user-images.githubusercontent.com/11806563/93096814-1e808f80-f6a5-11ea-88a4-6872c1a56c7b.png)

However the other materials look, they instantly turn black when the cube with default material is showing.

This weird behaviour is only present on my laptop with Intel 510 integrated graphics, neither on my other computers with Nvidia 750ti and 1070ti respectively, so I presume it has to do with the intel driver somehow... idk

The minimum project is really easy to create, you need no assets, only a 3D-scene with one cube to show the grid bug and another to show the effect on other materials, rendering several cubes with default material does not conflict other than with the grid...

Bug is present both in 3.2 stable & 3.2.2 RC 6

**Comment by Calinou** [comment] 2020-09-14 14:25
Duplicate of https://github.com/godotengine/godot/issues/30330.

**Closed by Calinou** 2020-09-14 14:25 UTC
