### ISSUE TITLE
Incorrect handling of DPad UP on Ubuntu

### ISSUE THREAD

**Issue by czlowiekimadlo** [godotengine/godot#6419] opened 2016-09-07 14:03 UTC
**Operating system or device - Godot version:**
Ubuntu 14.04.03 using Godot 2.1-stable
Gamepad is XBOX 360 controller in wireless mode.
Installed package (dpkg -l | grep xb):
xboxdrv     0.8.5-1      amd64        Xbox360 gamepad driver for the userspace

**Issue description** (what happened, and what was expected):
When using dpad on a gamepad, pressing UP button doubles as an A button, making any button navigation difficult, as going UP also calls UI_ ACCEPT by default.

**Steps to reproduce:**
On Ubuntu 14.04.03
- run demo project named 'Joysticks'
- press UP on gamepad dpad
- observe buttons

Expected result:
only UP button lights up in the demo
Actual result:
both UP and A buttons light up

**Link to minimal example project** (optional but very welcome):
'Joysticks' demo from samples bundle

I have tested same gamepad on http://html5gamepad.com/ in Firefox, and all seems fine, though button numbering differs from godot one.

**Comment by Hinsbart** [comment] 2016-09-07 14:08
Ohwee.
Can't reproduce this on arch linux, downloading ubuntu 14.04...

In the meanwhile, what's the output when you do `print(Input.is_joy_known(0))` ?
Also, is there any specific you're using xboxdrv instead of the kernel driver?

**Comment by czlowiekimadlo** [comment] 2016-09-07 14:22
Can't run this at this moment, but will give you output as soon as I can.

I'm using xboxdrv because when I researched how to make it work on Ubuntu a year ago, all I found was to avoid kernel one and use this instead. Everyone on stackoverflow said it was broken. I remember having issues with syncing pad to the usb receiver with kernel one as well.

**Comment by czlowiekimadlo** [comment] 2016-09-07 14:24
It might be connected to the previous issue that I reported in an old thread - only half of dpad worked. It had something to do with old kernel version in Ubuntu 14.04. I'm upgrading that laptop to 16.04 right now anyway, so after it finishes I will test if the issue still exists.

**Comment by Hinsbart** [comment] 2016-09-07 15:39
@czlowiekimadlo Yeah, the xpad driver has improved a lot in recent kernel versions, so I suspect your issue will be solved on 16.04.

But still, I will test this on 14.04/xboxdrv during the next week and try to find the problem ^^

**Comment by czlowiekimadlo** [comment] 2016-09-08 08:51
@Hinsbart I have done that test you asked for:
`
print(Input.is_joy_known(0))
print(Input.is_joy_known(1))
print(Input.is_joy_known(2))
print(Input.is_joy_known(3))
`

And the output is:
`
True
True
True
True
`

I did check all four, because wireless receiver for XBOX 360 pad registers all four in OS, even though only one is synced.

Also, upgrading to Ubuntu16.04 did not help. Nor uninstalling xboxdrv and rebooting. Issue persists: pressing UP generates two InputEvents instead of one: Buttons 0 and 12

**Comment by czlowiekimadlo** [comment] 2016-09-08 11:02
I have tested using gamepad on an old Fedora 20 and it works, so it looks like only my Ubuntu machines (2 of them) have issues. Are gamepad settings cached somewhere?

**Comment by Hinsbart** [comment] 2016-09-08 12:00
@czlowiekimadlo should be fixed by #6431.
If you want to test it without recompiling the engine, you can use:
`Input.add_joy_mapping("030000005e0400001907000000010000,X360 Wireless Controller,leftx:a0,lefty:a1,dpdown:h0.4,rightstick:b10,rightshoulder:b5,rightx:a3,start:b7,righty:a4,dpleft:h0.8,lefttrigger:a2,x:b2,dpup:h0.1,back:b6,leftstick:b9,leftshoulder:b4,y:b3,a:b0,dpright:h0.2,righttrigger:a5,b:b1,", true)`

**Comment by czlowiekimadlo** [comment] 2016-09-08 12:24
@Hinsbart adding that mapping fixes it for me on my Ubuntu machine. Don't have any 14.04 hanging around anymore to check there, but on 16.04 it works. Thanks!

**Closed** 2016-09-08 12:26 UTC
Labels: bug, platform:linux, topic:core
