### ISSUE TITLE
Combining Control.SizeFlags produces warnings

### ISSUE THREAD

**Issue by Piratux** [godotengine/godot#76223] opened 2023-04-18 19:57 UTC
### Godot version

4.0.2

### System information

Windows 10

### Issue description

Combining SizeFlags in GDScript for `Control` attribute `size_flags_horizontal` produces following warnings, but it's not clear what's the correct way to combine these flags without producing warnings:
```
W 0:00:00:0918   Integer used when an enum value is expected. If this is intended cast the integer to the enum type.
  <GDScript Error>INT_AS_ENUM_WITHOUT_CAST
  <GDScript Source>Label.gd:5
W 0:00:00:0918   Cannot assign 10 as Enum "Control.SizeFlags": no enum member has matching value.
  <GDScript Error>INT_AS_ENUM_WITHOUT_MATCH
  <GDScript Source>Label.gd:5
```

### Steps to reproduce

Script that produces warnings:
```
extends Label

func _ready():
	size_flags_horizontal = Control.SIZE_EXPAND | Control.SIZE_SHRINK_END
```
Note: Script works as intended and sets correct value to 10. In other words, it produces identical results as manually setting these flags in editor.

### Minimal reproduction project

N/A

**Comment by AThousandShips** [comment] 2023-04-18 20:44
Duplicate of #74593

**Comment by Calinou** [comment] 2023-04-18 20:47
- Duplicate of https://github.com/godotengine/godot/issues/74593.

**Closed by Calinou** 2023-04-18 20:47 UTC
Labels: bug, topic:gdscript, topic:gui
