### ISSUE TITLE
Shadows are sometimes cast by not visible objects and always cast by cull_masked objects  

### ISSUE THREAD

**Issue by goatchurchprime** [godotengine/godot#43827] opened 2020-11-24 16:40 UTC
**Godot version:**
3.2.3.stable

**OS/device including version:**
Windows

**Issue description:**
I have been using layers and camera culling to turn on and off large sections of my scene instead of controlling the visibility flag on each one individually.  It also allows me to make some objects big enough to see in the overhead plan camera but not appear in the main game play window.  Unfortunately even though they are invisible, they still cast shadows.

When making this minimal reproduction project I discovered the second problem that the shadows do not always respect the visibility flag.

![image](https://user-images.githubusercontent.com/677254/100124483-9fad8d00-2e73-11eb-9bc3-9c1c5acc5537.png)

**Steps to reproduce:**
Run the example.  The camera has a cull_mask against layer 2.
Use the H and S key to toggle visibility on CubeLeft and layer on CubeRight. 
Both cubes disappear but their shadows remain.
If you "touch" the cubes by using the 1 key to rotate them by 10 degrees the CubeLeft shadow disappears, but the CubeRight always remains.

**Minimal reproduction project:**
[layershadow.zip](https://github.com/godotengine/godot/files/5591300/layershadow.zip)

**Comment by Calinou** [comment] 2020-11-24 16:48
Related to https://github.com/godotengine/godot/issues/19438 (which is fixed in `master`).

**Comment by lawnjelly** [comment] 2020-11-24 18:14
Also #32475 was merged after 3.2.3. May affect your project (haven't tested).

**Comment by goatchurchprime** [comment] 2020-11-25 08:02
Apologies for not doing an adequate bug database search before drafting this.  Must do better.  Hope I've not wasted too much time.  Please mark as duplicate, archive as appropriate.  I don't want to further mess up the system.

**Comment by akien-mga** [comment] 2020-11-25 08:18
@goatchurchprime No worry, it's not expected of users to know the bug tracker by heart :) A potential duplicate issue does not disrupt anything, at most it confirms the validity of a bug in the currently supported release.

**Comment by lawnjelly** [comment] 2020-11-25 08:32
@goatchurchprime can you try this in 3.2.4 and confirm or say whether any of these bugs are still present so we can either close or action?

**Comment by goatchurchprime** [comment] 2020-11-25 08:48
Changing the visible flag does now update shadows in the next frame for 3.2.4

Changing the cull_mask in the camera still leaves the shadows in place.  To be fair, this is different to the issue #19438 which is the cull_mask applied to the light and looks like it will be a won't fix.  This bug/feature could be handled in the documents at https://docs.godotengine.org/en/stable/classes/class_camera.html?highlight=cull_mask#class-camera-property-cull-mask with a note that it doesn't apply to shadows.  So if you're applying it to non-shadowed objects it will look just fine.

**Comment by tavurth** [comment] 2022-02-09 08:07
Confirmed, just ran across this in v3.4.3.rc1.official [894b6d504]

Far box is 
<img width="329" alt="Screenshot 2022-02-09 at 11 06 33" src="https://user-images.githubusercontent.com/100964/153151005-e6e4d711-efaa-46c6-ad29-3a2bf42a22a4.png">

Close box is:
<img width="334" alt="Screenshot 2022-02-09 at 11 06 52" src="https://user-images.githubusercontent.com/100964/153151165-c0a13c26-2972-4394-8a4f-96c413cb738e.png">

Directional light is:
<img width="314" alt="Screenshot 2022-02-09 at 11 07 15" src="https://user-images.githubusercontent.com/100964/153151375-45106407-622d-410a-9351-312fe41414b8.png">

<img width="1136" alt="Screenshot 2022-02-09 at 11 05 54" src="https://user-images.githubusercontent.com/100964/153150610-f60014bc-d4d7-4aa8-b491-ad95f9a9c1a4.png">

Sample project:
[godot-light-test.zip](https://github.com/godotengine/godot/files/8030679/godot-light-test.zip)

**Comment by akien-mga** [comment] 2022-09-23 07:44
Fixed by #61841.

**Closed by akien-mga** 2022-09-23 07:44 UTC
Labels: bug, topic:rendering, confirmed, topic:3d

**Comment by markusneg** [comment] 2022-10-07 10:59
> Confirmed, just ran across this in v3.4.3.rc1.official [[894b6d5](https://github.com/godotengine/godot/commit/894b6d50493756be25d7f25dc1138b0272f7532e)]

Your example probably points to an open issue different from the one mentioned above and fixed in my PR. Indeed the docs say:
> _light_cull_mask_
> The light will affect objects in the selected layers.
which (in my opinion) suggests that the non-affected objects (caused by mismatching light_cull_mask and visual instance layer) neither cast shadows. Should we create a new issue for that or is that wanted behavior?
