### ISSUE TITLE
Can't assign nodes to exported array

### ISSUE THREAD

**Issue by RustyLongbow** [godotengine/godot#62916] opened 2022-07-11 17:27 UTC
___

***Bugsquad note:** This issue has been confirmed several times already. No need to confirm it further.*

___

### Godot version

Godot 4.0 alpha 11

### System information

Solus OS and Windows

### Issue description

Can't assign nodes to an exported array of node pointers

https://user-images.githubusercontent.com/61121689/178321358-fe05eec9-17ab-4d94-ac87-f87b1e059b97.mp4

### Steps to reproduce

1) Export an array of node pointers (`@export var node_pointer_array: Array[Node2D]`)
2) Try to assign an element to the array on the editor
3) Element will not be assigned

Or: check out the minimal reproduction project below

### Minimal reproduction project

[export array of node pointers.zip](https://github.com/godotengine/godot/files/9086249/export.array.of.node.pointers.zip)

**Comment by Seubmarine** [comment] 2022-08-26 06:03
Can confirm the issue is still present in alpha 14

**Comment by Seubmarine** [comment] 2022-08-27 01:57
I've loooked into it EditorPropertyNodePath::update_property()  doesn't get the nodepath properly doing 
`p = get_edited_object()->get(_get_meta_pointer_property());` 

`_get_meta_pointer_property()` result in this String : "metadata/_editor_prop_ptr_indices/0"
I think it's wrong because an exported Node result in this: "metadata/_editor_prop_ptr_myvar" (myvar is the name of the exported Node)

It should be something different but I don't know what.
I guess something like "metadata/_editor_prop_myarray_indices/0" (myarray is the name of the array that is exported in this case)

Could someone with a bit more knowledge find what the proper metadata name should be ?

**Comment by wouldntsavezion** [comment] 2022-09-01 12:43
Still present in alpha 15, furthermore, if you save and close the scene then reopen it, you get actual broken links.

![image](https://user-images.githubusercontent.com/17103048/187916431-3737a891-35aa-48c7-8370-0561c92ab4d7.png)

**Comment by NoFr1ends** [comment] 2022-09-17 17:13
Following I noticed in beta 1:

It doesn't show when you assigned anything but if you click on it the right node is preselected in the dialog.
The saved scene doesn't contain the node paths and instead only saves it as e.g. ``[null, null]``.
Reopening the scene loses the preselection mentioned in the first point.

**Comment by CernyAdam** [comment] 2022-12-11 13:40
I can confirm that the bug is still present in beta5.

**Comment by Zireael07** [comment] 2022-12-11 15:55
We're up to beta **8** now though?

**Comment by Defaultsound** [comment] 2022-12-12 13:24
Still an issue in Beta 8. Also applies to custom node types as well.

**Comment by Seubmarine** [comment] 2022-12-12 13:38
I look at the source a month ago and it looked like it misinterpret the Nodes Type to be a Path if I recall correctly.

**Comment by muno777** [comment] 2022-12-29 02:02
Present in beta 10 also

**Comment by BeeRye** [comment] 2023-01-07 23:28
I believe this is the same bug. Godot Beta 10, Windows 10.

Assigning null values to texture arrays (and I would guess other resource-derived item arrays) functions correctly in all circumstances save for assigning them in the editor.

See project below:

Run scene to see results from loaded resources with and without null values, and results from creating new resources and adding or changing values while including null.

[Test Texture Array.zip](https://github.com/godotengine/godot/files/10367363/Test.Texture.Array.zip)

**Comment by Steveplays28** [comment] 2023-01-17 17:34
Still an issue in beta 12.

**Comment by 3FCO** [comment] 2023-01-18 08:19
This also persists in Godot 4 B13

**Comment by Badaxis** [comment] 2023-01-20 09:15
#69248

**Comment by vonagam** [comment] 2023-01-20 10:05
Sorry to disappoint, but no (at least not yet). Unfortunately at this point I don't know much about editor side of things, but the issue is easily reproduced and common, so I hope that it will be fixed in not-so-distant future.

**Comment by palodequeso** [comment] 2023-01-24 14:06
Can reproduce, can easily add to array in scripting onready, but is def still a bug.

**Comment by Calinou** [comment] 2023-02-07 15:37
This is still reproducible in 4.0.beta17 according to https://www.reddit.com/r/godot/comments/10r2z3n/dev_snapshot_godot_40_beta_17/j6uj30y/.

**Comment by paladinrose** [comment] 2023-02-10 19:01
Reproduceable in Godot 4 Official on Windows 10.

**Comment by joshua-maros** [comment] 2023-02-14 22:12
Temporary workaround: group all the nodes you want to assign under one parent node, then have your script export a single node and iterate over its children on `_ready`, adding them to the original array.

**Comment by honaj** [comment] 2023-02-18 14:34
This is still a problem in RC 2.

**Comment by Steveplays28** [comment] 2023-02-18 18:00
This is a relatively big issue for 4.0 if you ask me, it's got a lot of use cases and should definitely be fixed before 4.0 gets released imo.

**Comment by YuriSizov** [comment] 2023-02-18 18:36
> should definitely be fixed before 4.0 gets released imo.

While it is annoying and limiting, it's also not critical. This is not something inherently broken, just two _new_ features interacting and having issues. Issues in new features are to be expected from the first x.0 release, but we should be able to fix this in a patch release, i.e. 4.0.x.

**Comment by Steveplays28** [comment] 2023-02-18 19:28
That's fair enough. You guys are the one making decisions in the end, these are just my 2 cents.

Just curious though, how long after the release of 4.0 can we expect 4.0.1?
If you don't really know that's fine too.

**Comment by YuriSizov** [comment] 2023-02-18 19:43
4.0.1 can be out very shortly, but it's mostly going to be focused on critical regressions not found/not reported before 4.0-stable. Fixes that we wished to have in 4.0 but decided to err on the side of caution are likely to be included in releases after that. The timeline around March is hard to tell due to GDC.

**Comment by Steveplays28** [comment] 2023-02-18 19:50
Alright, thanks!

**Comment by sairam4123** [comment] 2023-03-16 11:09
A good work around would be to leverage the new array functions.

```
@export var switches: Array[Switch3D]
```
would become
```
@export var switch_nps: Array[NodePath]
@onready var switches = switch_nps.map(get_node)  # feels hacky but works, not in editor though!
```

**Comment by designer-trifonov** [comment] 2023-03-29 20:59
Godot 4.0.1. In the console you can see that nodes are added to the array, but in the inspector itself the list is not displayed.

**Comment by NaleVex** [comment] 2023-04-02 17:06
Godot 4.0.1: no effect on adding Node to array via inspector, no messages in console, actual value is Null

**Comment by Frontrider** [comment] 2023-04-08 14:26
> A good workaround would be to leverage the new array functions.

That was the obvious thing to try, but did not work for me immediately. This error was in the console.
```
  Attempted to set a variable of type 'NodePath' into a TypedArray of type 'Object'.
  core/variant/array.cpp:413 - Condition "!_p->typed.validate(value, "set")" is true.
```
I had to restart the editor to make it work.

Godot version 4.0.2.stable.

**Closed** 2023-04-12 11:28 UTC
Labels: bug, topic:gdscript, topic:editor, confirmed

**Comment by nfjdu** [comment] 2023-05-12 12:10
Stiil not fixed in 4.0.2.stable ? For me, at least. Have not tried @sairam4123 answer yet, but have same problem as on video.

**Comment by akien-mga** [comment] 2023-05-12 12:18
The PR which fixed this issue (referenced above, #73256) was merged in the `master` branch for Godot 4.1, and this happened after the 4.0.2 release, so it's expected that you still experience the issue in that version.

It may be cherry-picked for 4.0.4 (not for 4.0.3, as we're still ironing out issues in the `master` branch).

**Comment by timjbrown** [comment] 2023-05-19 11:19
I tried to do this not knowing it was even possible and ran into this issue. Cool feature hope to see it soon. Sorry for jumping on the dogpile but wanted to participate on godot github somehow 🤣

**Comment by VikingAntics** [comment] 2023-05-31 20:46
This is indeed fixed in Godot 4.1 dev 3, however, it still does not work if you have @Tool in your GDScript file.  The same bug occurs as prior to the fix, but only if you have @Tool.

**Comment by Legendilu** [comment] 2024-01-22 09:33
I was using 4.1 and had this issue. upgraded to 4.2 and its still happening. my script doesnt have @tool or anything like that. is there a fix? I cant make my custom resource instances like this.

**Comment by Legendilu** [comment] 2024-01-22 09:53
I'm still having this problem on 4.2. no @tool in my script.

**Comment by YuriSizov** [comment] 2024-01-22 15:30
@Legendilu Please provide a reproduction project for your issue.

**Comment by Legendilu** [comment] 2024-01-22 23:20
sorry im new to using github. what does that mean exactly? like a new project where ive recreated the issue? or just explain how to reproduce the issue?

> @Legendilu Please provide a reproduction project for your issue.

**Comment by Legendilu** [comment] 2024-01-22 23:41
Gods. nevermind. I fixed it.  😭
