### ISSUE TITLE
Visual Script Crash when trying to load Scene

### ISSUE THREAD

**Issue by mrjustaguy** [godotengine/godot#33881] opened 2019-11-25 13:25 UTC
**Godot version:**
Godot 3.2 Beta 2
**OS/device including version:**
Windows 10

**Issue description:**
When I was trying to load a scene, i noticed that whenever a scene is referenced at all it crashes when trying to run the project
Note: Only Tried With Visual Script, Might be an issue in GDScript and others, Also in the project where I found the bug i had a Node2D preload my Spatial.scn and even when i ran the Spatial.scn the project crashed even if there was no connection with the Node2D.scn

**Steps to reproduce:**
1.Create any scene (used Node2D in the reproduction project)
2.Create a Visual Script that runs in the project and attach it to some node
3.Create any sort of reference to the Scene (in this case just a drag & drop from the resources which creates a preload with the scene)
4.Run Project -> Crash
5.After the project crashes, just remove the reference to the scene
6.Run Project Again -> No Crash

**Minimal reproduction project:**
[Bug.zip](https://github.com/godotengine/godot/files/3886760/Bug.zip)

**Comment by pouleyKetchoupp** [comment] 2019-11-29 12:53
It's not actually a crash, it fails to load the scene because of cyclic dependencies and the game quits.

The problem is, it looks exactly like a silent crash because there's no error shown in the Script Debugger when errors are triggered during startup (it quits before the remote debugger has a chance to send errors to the editor).

You can see them in the terminal, but it's not obvious to find.
Here are the error that are supposed to show up:
```
ERROR: Resource: 'res://Node2D.tscn' is already being loaded. Cyclic reference?
   At: core\io\resource_loader.cpp:355
ERROR: Can't load dependency: res://Node2D.tscn.
   At: core\io\resource_format_binary.cpp:655
ERROR: Failed to load resource 'res://Node2D.vs'.
   At: core\io\resource_loader.cpp:208
ERROR: Failed loading resource: res://Node2D.vs.
   At: core\io\resource_loader.cpp:278
ERROR: ResourceInteractiveLoaderText::poll: res://Node2D.tscn:3 - Parse Error: [ext_resource] referenced nonexistent resource at: res://Node2D.vs
   At: scene\resources\resource_format_text.cpp:440
ERROR: Failed to load resource 'res://Node2D.tscn'.
   At: core\io\resource_loader.cpp:208
ERROR: Failed loading resource: res://Node2D.tscn.
   At: core\io\resource_loader.cpp:278
ERROR: Failed loading scene: res://Node2D.tscn
   At: main\main.cpp:1819
```

And the only error visible in the editor is this one when the game quits abruptly:
```
ERROR: NetSocketPosix::_get_socket_error: Socket error: 10054
   At: drivers\unix\net_socket_posix.cpp:202
```

I'm going to try and make a PR that handles this case, so you can get error messages in the editor when the game fails to start after some errors.

**Comment by Daniel-del-Castillo** [comment] 2020-01-10 13:47
Didn't #33994 fix this? or is the problem now the cyclic dependencies pouleyKetchoupp mentioned?

**Comment by pouleyKetchoupp** [comment] 2020-01-10 14:25
#33994 didn't fix the issue itself, it just shows errors that can help debugging it.

The actual problem to solve in this example is that the game doesn't start because the script references the scene and the scene references the script (cyclic dependency). It can be fixed by removing the reference to the scene in the script.

**Comment by akien-mga** [comment] 2020-01-22 10:27
Closing as the engine issue has been fixed, the rest is a project-specific issue.

**Closed by akien-mga** 2020-01-22 10:27 UTC
Labels: bug, crash, topic:visualscript
