### ISSUE TITLE
Methods at the last frame of an animation does not gets called when executed by AnimationTree

### ISSUE THREAD

**Issue by eh-jogos** [godotengine/godot#61766] opened 2022-06-06 23:12 UTC
### Godot version

4.0.alpha9

### System information

Manjaro Linux, Nvidia proprietary drivers, Vulkan Clustered

### Issue description

When controlling animations through an AnimationTree, and there is a method call track with a keyframe on the last frame of the animation, that method call becomes unreliable, working only rarely, and not being called most of the time. The same animation when called through AnimationPlayer, always calls the method correctly.

On further inspection, the error might be because of floating point imprecision, as when I hover the keyframe it shows it's not exactly at 0.4 even though snap is turned on:
![image](https://user-images.githubusercontent.com/13070158/172582416-7f8e93cf-57b8-4028-b5d3-730275dcb1d4.png)

This seems to be happening with other frames except multiples of 5, so 0.0 is fine, 0.5 as well, 1.0 too and so on, but any frame values in between are imprecise.

To solve my issue for now I'm just going into the details and manually puting it at 0.39
![image](https://user-images.githubusercontent.com/13070158/172263365-fd9a30f5-7914-4287-9c4d-081c88897216.png)
![image](https://user-images.githubusercontent.com/13070158/172582698-1b54c546-cab6-485f-88de-27cbdab8aa12.png)

Not super ideal, as I was already using this as a fix for AnimationPlayer signals being ignored when using AnimationTree (#28311)

**--- EDIT ---
Floating point inaccuracy might not be related to the problem: https://github.com/godotengine/godot/issues/61766#issuecomment-1149689153**

### Steps to reproduce

Create any animation that ends on anything other than a multiple of 5 and add a method call to the last frame
Then call this animation through an AnimationTree StateMachine.
Calling the function directly through Animation Player seems to work fine

### Minimal reproduction project
[floating_point_last_frame.zip](https://github.com/godotengine/godot/files/8862757/floating_point_last_frame.zip)
In this project there is a simple scene with three simple animations and one of them calls a function on the last frame that prints a message and emits a signal.

![image](https://user-images.githubusercontent.com/13070158/172644565-b3f3e84a-46ad-4ee5-8186-7ee57be3e084.png)

By executing the project and pressing "ui_up" you can play the animation though the AnimationPlayer, "ui_right" through and AnimationTree using BlendTree as root, and "ui_down" through an AnimationTree using AnimationStateMachine as root. Only when playing through AnimationPlayer the method at the last frame is called consistently. 

Changing the method call keyframe position from 0.4 to 0.39 fix it for both AnimationTrees.

**Comment by Rindbee** [comment] 2022-06-08 05:15
Maybe we can mark the callback function `called_at_the_end` according to the time, or record it in a list when editing, to avoid problems caused by inaccurate floating point numbers.

**Comment by eh-jogos** [comment] 2022-06-08 09:35
Hum, problem might not be related floating point inaccuracy after all, as one thing I had not though about testing when I was doing the MRP was to try it with an animation that actually ends on 0.5.

In this case hovering the keyframe on the editor shows no floating point inaccuracy, but if I try using the AnimationTree the method on the last keyframe still doesn't get called.
![image](https://user-images.githubusercontent.com/13070158/172584192-7e6359c3-b654-4cec-9756-00f5ca5f4a8a.png)

**Comment by TokageItLab** [comment] 2022-06-08 14:15
AFAIK, AnimationPlayer, AnimationTree and AnimationStateMachine each have a different playback time.

Is the problem only with the AnimationStateMachine? Does the problem occur if I playback it in the AnimationTree without using the AnimationStateMachine?

**Comment by Rindbee** [comment] 2022-06-08 23:13
https://github.com/godotengine/godot/blob/7e0c54e292f2813878d178bbb691a419ed6fb295/scene/animation/animation_tree.cpp#L1337-L1348
If the `delta` is small enough, keyframes may be lost here.

**Comment by TokageItLab** [comment] 2022-06-09 06:36
Repost from #61836:
If delta is small enough, the animation should be stopped. The problem that needs to be fixed is not the comparison, but the way keys are gotten at the end of the animation.

**Comment by Rindbee** [comment] 2022-06-09 06:56
> Repost from #61836: If delta is small enough, the animation should be stopped. The problem that needs to be fixed is not the comparison, but the way keys are gotten at the end of the animation.

Another way of thinking, if `delta` is `0`, it means the **end**, then we can get the **exact** length, so that there will be no loss. 
The rest is to determine, how to decide that a small enough `delta` is `0`.

**Comment by Rindbee** [comment] 2022-06-09 07:00
> Repost from #61836: If delta is small enough, the animation should be stopped. The problem that needs to be fixed is not the comparison, but the way keys are gotten at the end of the animation.

Another way of thinking, if `delta` is `0`, it means the **end**, then we can get the **exact** length, so that there will be no loss. 
The rest is to determine, when to decide that a small enough `delta` is `0`.

**Comment by akien-mga** [comment] 2022-06-09 07:03
I guess when the delay is near zero, it could snap to the end and play the last frame?

**Comment by Rindbee** [comment] 2022-06-09 07:09
> I guess when the delay is near zero, it could snap to the end and play the last frame?

When the delta is small enough for the first time, it is only marked and not processed. Let it be 0 directly the second time. One more step will be ok.

**Comment by TokageItLab** [comment] 2022-06-09 07:48
I looked into AnimationTree. Originally, #61836 state seems to address the fact that it fires continuously when the TimeScale is 0. And I think that we need to think of a special case for the end of animation.

**Comment by Rindbee** [comment] 2022-06-09 08:28
I think `delta==0` as the animation-finished flag will make things clearer.

For begin-to-end, and end-to-begin, it's linear, so it's easy to compute.

For situations where jitter may occur, like pingpong or bouncy balls (Instead, it's like a number axis of position). Count the number of times if delta is small enough and continue, when the number is big enough, end it and force the `delta` to `0`.

**Comment by TokageItLab** [comment] 2022-06-09 08:45
It is a rare case, but it cannot deal with the case where delta is 0 instead of a very small value at the end of the animation.

Rather than using `delta==0` as a substitute for the animation end flag, I recommend managing the flag as `if (Math::is_zero_approx(delta)) { end=true }`.

**Comment by Rindbee** [comment] 2022-06-09 09:17
`delta` should be calculated on a case-by-case basis, and this is not a good place to calculate it, the `delta` is related to `AnimationState`. The place where `AnimationState` is calculated should be appropriate, and the processing of the `delta` should be performed there.

The following is the processing logic for `delta` when `delta` is small enough. 
```
...
// outside the loop
int times = 0;
bool end = false;
...
// inside the loop
if(end and other_condition){
	delta = 0;
	break;
}

if(Math::is_zero_approx(delta)){
	times++;
	end = times > MAX_ALLOW;
}else{
	times = 0; // reset as need.
}
...
```

**Comment by TokageItLab** [comment] 2022-06-09 09:23
The end of animation should be determined by current_time, loop_mode, backward, and animation->length. So setting delta = 0 in that case is fine, but the end flag should be managed at the same time, and using delta to determine the end of the animation is a bad implementation.

**Comment by Rindbee** [comment] 2022-06-09 09:48
> The end of animation should be determined by `current_time`, `loop_mode`, `backward`, and `animation->length`.

Couldn’t agree more. So wherever you can get this information, that's a good place for computation. 

My idea is just to do further processing on the result after the calculation. According to the 4 parameters you mentioned.

**Comment by TokageItLab** [comment] 2022-06-10 09:25
Will be fixed by #61885. `delta == 0` was originally a **seeked** flag. Sorry but I had forgotten about that.

**Closed** 2022-06-23 08:07 UTC
Labels: bug, topic:animation

**Comment by eh-jogos** [comment] 2022-08-19 15:25
@TokageItLab 
I'm actually still having problems with this. For a while it seemed to have fixed, or became kind of hit or miss, some animations work perfectly and some just refuse to call the method.

Haven't found a predictive way to know when one animation will give me trouble or not (and avoid it), I'm not sure if the actual animation length influences this or not, but just realized now my AnimationTree has some BlendSpace1D nodes which it didn't before, so I have to check if the problem happens on the animations they use or not.

but the "workaround" I used before still works, which is to either turn off snap and move the method keyframe a few milliseconds back, or increase the length of the animation to be a few milliseconds longer, so it seems like the same problem to me?

**Comment by eh-jogos** [comment] 2022-08-19 15:35
Yeah, just tested the same animation I'm having trouble with on BlendSpace1D in a simple AnimationNodeAnimation and had the same problem, will see if I can separate only the character skin in a MRP later

**Comment by eh-jogos** [comment] 2022-08-19 15:44
Seems to be related to animation length. 
For the same animation, at 24 FPS: 
- when its length is 6 frames, a method at frame 6 never gets called.
- when its length is 4 frames, a method at frame 4 always gets called.

**Comment by TokageItLab** [comment] 2022-08-19 21:53
Please post a new issue along with the reproduction project. If it is due to the precision of the FPS mode, I have a feeling that using floor instead of round for the internal decimal rounding process may solve the problem.
