### ISSUE TITLE
Particles2D and 3D restart emision from 0 when window is minimized

### ISSUE THREAD

**Issue by Ranoller** [godotengine/godot#18242] opened 2018-04-17 00:50 UTC
**Godot version:**

Godot 3 stable and up to master

**OS/device including version:**

Tested on Win 7, 8.1 and 10.

**Issue description:**

Particle system restart emision from 0 when the window is minimized and later maximized. Same behavior if you click and sustain the window. Preprocessing time is not respected (don´t recalculate this time).

![particlesrestartbug](https://user-images.githubusercontent.com/11712737/38842394-0835ed50-41ea-11e8-892b-ae9a9cfba718.gif)

**Comment by Calinou** [comment] 2020-06-07 17:53
I can't reproduce this on Godot 3.2.2beta4 with Fedora 31. Maybe this is due to how windows are managed on Windows?

@Ranoller Can you (or anyone else) still reproduce this bug in Godot 3.2.1 or [3.2.2beta4](https://godotengine.org/article/dev-snapshot-godot-3-2-2-beta-4)?

**Comment by akien-mga** [comment] 2021-04-28 09:39
Closing for now then as it's not clear if this can still be reproduced. If it can, a minimal reproduction project would be helpful to ensure that all testers can see the same results.

**Closed by akien-mga** 2021-04-28 09:39 UTC
Labels: bug, topic:rendering
