### ISSUE TITLE
Dropdown in Environment editor goes gray when "Canvas" is selected

### ISSUE THREAD

**Issue by stur86** [godotengine/godot#65917] opened 2022-09-16 17:57 UTC
### Godot version

4.0 beta

### System information

Windows 10

### Issue description

Create a WorldEnvironment object, add an Environment, go to Background, select Canvas as the mode. When clicking on the dropdown again, it shows like this:

![image](https://user-images.githubusercontent.com/4365814/190702250-a241e02c-39b3-4847-bfc8-a3a8e129065f.png)

Happens reliably in my test project. The same problem seems to also affect other UI elements (it made the confirmation dialog to delete a node grey too).

### Steps to reproduce

* Create a new project
* Create a WorldEnvironment
* Add an Environment object
* Set the Background mode to Canvas
* Click on the Background mode dropdown again

### Minimal reproduction project

[Uploading Test.zip…]()

**Comment by Calinou** [comment] 2022-09-16 18:58
Duplicate of https://github.com/godotengine/godot/issues/52467.

PS: For future reference, the minimal reproduction project didn't upload (likely because you clicked away from the text field while it was still uploading).

**Closed by Calinou** 2022-09-16 18:58 UTC
