### ISSUE TITLE
.WAV files not loading properly when exported

### ISSUE THREAD

**Issue by Omiminpo** [godotengine/godot#18390] opened 2018-04-24 01:47 UTC
**Godot version:**
3.0.2.stable.official

**OS/device including version:**
"Windows 10

**Issue description:**
When exporting a game that loads .wav files procedurally into an audio stream player, the files aren't loaded and played properly in the exported game (as in, they're silent). The size of the resource package suggests that they might still have been exported, just not loading properly.

adding "*.wav" to the list of non-resources that get exported doesn't change this

putting the "Music" folder of my project, with the uncompressed files, in the same location as the .exe, makes the audio work in-game

If it is any help this is the code through which i load the sounds
`func _loadSounds(sounds, time):
	players = []
	soundlist = sounds
	
	maxtime = time
	curtime = 0
	
	for sound in sounds:
		var node = AudioStreamPlayer.new()
		node.set_name("node")
		call_deferred("add_child", node)
		
		players.append(node)
		
		var audio_file = "res://Music/" + sound
		
		if File.new().file_exists(audio_file):
			var sfx = load(audio_file) 
			node.stream = sfx
						
	for player in  players:
		player.play()`

Sounds that are in-built in other audiostreamplayer, which are not loaded through code, work normally

**Comment by Omiminpo** [comment] 2018-04-24 14:51
@Phoenix1747 did you find any workaround for this?

**Comment by Phoenix1747** [comment] 2018-04-24 14:53
Unfortunately, no. I'm waiting for 3.1 to come around and then have a look at it again, hoping this is fixed.

**Comment by vnen** [comment] 2018-04-24 17:10
Oh, I tagged this way too quickly. It's not an issue with the audio system. Check #14562 for a workaround.

This is also not exactly a bug, it works as @Phoenix1747 stated. The File API does not look at the path remapping.

This essentially a duplicate of #15380, so I'll close this.

**Closed by vnen** 2018-04-24 17:10 UTC
Labels: bug, topic:audio

**Comment by Phoenix1747** [comment] 2018-04-24 17:31
@vnen Problem with #14562 is that you also have to append the hash to get the real filename in `.import` but how to get the hash if the original files don't exist anymore?

**Comment by vnen** [comment] 2018-04-24 18:52
@Phoenix1747 you can call `load()` with the original path and it'll automatically load the on from the import folder. The problem is only when checking with `file_exists()` (the workaround is simply checking if the `file_name + ".import"` file exists instead).

If you really need the file from the `.import` folder (don't know why you would) you can either calculate the file name (it's simply a MD5 hash of the path) or load the `.import` file with ConfigFile and read the remapped path.
