### ISSUE TITLE
Godot crashes when creating a NoiseTexture3D in compatibility renderer

### ISSUE THREAD

**Issue by JUSTCAMH** [godotengine/godot#83174] opened 2023-10-11 23:47 UTC
### Godot version

4.1.1.stable

### System information

Godot v4.1.1.stable - Windows 10.0.19045 - Vulkan (Compatibility) - NVIDIA GeForce RTX 3070 (NVIDIA; 31.0.15.3619) - 11th Gen Intel(R) Core(TM) i7-11700K @ 3.60GHz (16 Threads)

### Issue description

When creating a NoiseTexture3D in the compatibility renderer, godot crashes. With other renderers, this doesn't occur. If NoiseTexture3D isn't supported on compatibility renderer, godot should gracefully handle this case, showing a descriptive error but not crashing. But of course it would be helpful if NoiseTexture3D could be supported on compatibility

### Steps to reproduce

- Create a new project with the compatibility renderer.
- Create a new NoiseTexture3D resource from the filesystem docker.
- (BUG): The moment you select the NoiseTexture3D, godot crashes. Doing this in a different renderer (mobile or forward+) doesn't result in a crash.

### Minimal reproduction project

N/A can be reproduced in any project with compatibility renderer

**Comment by Calinou** [comment] 2023-10-12 00:26
- Related to https://github.com/godotengine/godot/issues/71029.

https://github.com/godotengine/godot/pull/80363 is still on track to be merged for 4.2, so this may resolve the issue.

**Comment by clayjohn** [comment] 2023-10-12 01:10
Duplicate of https://github.com/godotengine/godot/issues/80302

Fixed by https://github.com/godotengine/godot/pull/80407

The fix is in 4.1.2 and 4.2

**Closed by clayjohn** 2023-10-12 01:10 UTC
Labels: bug, topic:rendering, crash
