### ISSUE TITLE
Button Cannot Be Clicked When Camera2D Moves

### ISSUE THREAD

**Issue by ALBATI-2005** [godotengine/godot#65622] opened 2022-09-10 15:09 UTC
### Godot version

3.4.3

### System information

Windows 10, GLES2

### Issue description

A Button node is added as a child of CanavasLayer (and CanvasLayer is set to follow viewport). When Camera2D moves, so does the button. However, the "clickable area" does not move. What I mean is, if say Camera2D is moved to the left, this means that the button will be to the right of the screen. However, clicking on the button does nothing, while clicking to the LEFT of the button (by the same amount the camera was moved) causes the button to actually be clicked. This is strange since, visibly, the button IS following the viewport, but in reality, the actual "clickable area' does NOT follow the viewport.

Update: The same glitch happens with TouchScreenButton, which inherits from Node2D, meaning the problem is not specific to GUI elements, but rather to all "buttons". The minimal reproduction project has been updated accordingly.

### Steps to reproduce

Create a scene with this hierarchy:
>Node2D
>>Camera2D (set current, moved to the left)
>>CanvasLayer (set to follow the viewport)
>>>Button

Update: The same glitch happens with TouchScreenButton, which inherits from Node2D, meaning the problem is not specific to GUI elements, but rather to all "buttons". The minimal reproduction project has been updated accordingly.

### Minimal reproduction project

[updated test project.zip](https://github.com/godotengine/godot/files/9542677/updated.test.project.zip)

**Comment by Calinou** [comment] 2022-09-10 20:42
> (and CanvasLayer is set to follow viewport).

Does this occur when Follow Viewport is disabled?

**Comment by ALBATI-2005** [comment] 2022-09-11 03:11
No, it doesn't occur when follow viewport is disabled... it works as expected and just stays in the same position.

Why would I need it, you ask. Well, I'm using TextureButton as a clickable in-game object (e.g. a bomb that when clicked will explode). Maybe it's not intended for it to be used that way... but the thing is, it actually works with no problems at all ONLY if it's outside CanvasLayer and instead its z_index is changed (technically I'm changing the z_index of an Area2D which has a texture button node as a child).

So, you see, things are working as expected when outside CanvasLayer, but really strangely when inside it. I mean, if visibly the button is actually moving, why is the clickable area not moving? Of course, there is a workaround, and that's by  abandoning CanvasLayers and using z_index instead, but that's annoying, and CanvasLayers have the benefit of kinda "grouping" nodes and organising things. Also, CanvasLayers when set to follow viewport do not necessarily create parallax effect if the scale is always set to 1, so that's not their only use.

I don't want to resort to change the whole structure of my nodes and abandon CanvasLayers organisation. So, please find a fix to this issue... it must be some kind of bug because what happens visibly doesn't actually happen... I don't know exactly how a button works so I'm just guessing.

**Comment by ALBATI-2005** [comment] 2022-09-11 03:45
I want to give another example of GUI elements that need to follow the viewport. Imagine if I want to add some text that mixes in with the terrain of a level. Naturally, I'll want the text to actually follow the viewport so that it stays in the same position relative to the terrain (just like, say, how
sprites of a tree would act). This works ok though, since there's no "clickable area". What doesn't work is the button, as described by this issue.

**Comment by ALBATI-2005** [comment] 2022-09-11 14:00
Update: The same glitch happens with TouchScreenButton, which inherits from Node2D, meaning the problem is not specific to GUI elements, but rather to all "buttons". The minimal reproduction project has been updated accordingly.

**Comment by kleonc** [comment] 2022-09-11 14:18
Duplicate of #35965.

**Closed** 2022-09-11 14:18 UTC
Labels: archived, topic:core, needs testing, topic:gui, topic:2d
