### ISSUE TITLE
New Image button does nothing.

### ISSUE THREAD

**Issue by Polirecyliente** [godotengine/godot#45046] opened 2021-01-09 18:58 UTC
**Godot version:**
3.2.3 (This is the latest official release as of today)

**OS/device including version:**
Linux 5.4.0-58-generic Ubuntu 20.04 x86_64
GPU: Intel Corporation Haswell-ULT Integrated Graphics Controller
Backend: GLES3

**Issue description:**

Clicking the "New Image" button from an ImageTexture does nothing.

**Expected result:** When clicking the "New Image" button, a new blank image is created.

**Steps to reproduce:**
1. Create a new project in Godot.

![Screenshot from 2021-01-09 13-43-36](https://user-images.githubusercontent.com/52269801/104106083-f3880000-5280-11eb-80f1-bb14edf01007.png)

2. Click on "Other Node", search for Sprite, select "Sprite" to create a Sprite node, and then click on "Create".

![Screenshot from 2021-01-09 13-50-13](https://user-images.githubusercontent.com/52269801/104106157-9ccef600-5281-11eb-95e0-398cdc4e78f8.png)

3. Click on the drop-down menu of the "Texture" property of the Sprite node in the Inspector. Then click on "New ImageTexture".

![Screenshot from 2021-01-09 13-52-19](https://user-images.githubusercontent.com/52269801/104106187-efa8ad80-5281-11eb-8f36-f198e2e55191.png)

4. Click on the newly created image, by clicking "Image" at the right side of the "Texture" property.

![Screenshot from 2021-01-09 13-53-34](https://user-images.githubusercontent.com/52269801/104106206-16ff7a80-5282-11eb-9f38-457d3d98bb2a.png)

5. At the bottom of this panel, click on the drop-down menu of the "Image" property. Then click on "New Image", this button does nothing.

![Screenshot from 2021-01-09 13-54-49](https://user-images.githubusercontent.com/52269801/104106227-41513800-5282-11eb-89ab-fc111136d0d6.png)

Nothing happens, the property "Image" still has the value "[empty]".

![Screenshot from 2021-01-09 13-56-21](https://user-images.githubusercontent.com/52269801/104106258-78274e00-5282-11eb-99ca-3a4f85d01cba.png)

At this point a new blank image should be created, and the value of the "Image" property should be set to that new image, instead of the "[empty]" value.

**Comment by Xrayez** [comment] 2021-01-09 19:48
See #38112.

To eliminate confusion, PNG files are not loaded via editor "Inspector" manually, but imported as resources within "FileSystem" dock, which you can drag-n-drop to any `texture` property.

**Comment by KoBeWi** [comment] 2021-01-09 20:52
Duplicate of #38112

**Closed by KoBeWi** 2021-01-09 20:52 UTC

**Comment by Polirecyliente** [comment] 2021-01-10 00:38
@Xrayez you said:

> To eliminate confusion, PNG files are not loaded via editor "Inspector" manually, but imported as resources within "FileSystem" dock, which you can drag-n-drop to any `texture` property.

But the issue I posted has no relationship to PNG files, nor importing any file, nor using drag-n-drop. This is specifically about creating a new image inside Godot using the "New Image" button. For example, in other programs like Blender, when you create a new image inside Blender, the program lets you choose the color and the resolution for the new image. But if it's not the intent for Godot to allow the creation of new images inside Godot, then that button should just be removed, so that images are only imported as you said.

**Comment by Xrayez** [comment] 2021-01-10 11:37
Yes, that's why I linked #38112 which can be fixed without removing the `ImageTexture` from the popup. But it's just that I don't see practical use cases for creating `ImageTexture`/`Image` from within the editor itself, mainly because there's no way to edit such image. Even if you do manage to edit and save it, the scene file (which is stored as text by default) is going to be bloated by a sequence of (mega)bytes, unless your image is small of course. Due to this, this sort of thing is usually done via code.

**Comment by Polirecyliente** [comment] 2021-01-11 02:51
@Xrayez you said "But it's just that I don't see practical use cases for creating `ImageTexture` / `Image` from within the editor itself", so this button should be removed, or be renamed to "Add Image" or something that does not create a new image, correct?

**Comment by Xrayez** [comment] 2021-01-11 11:27
Yes, but it's about Godot's simplified architecture: it's possible, but to make something configurable/optional/making an exception comes with a great cost with Godot development.

You've probably seen those "Configuration warning" icons next to nodes, this is also where the warning can be added for `Sprite`.
