### ISSUE TITLE
Output of Texture2D get_size() is Vector2 instead of Vector2i

### ISSUE THREAD

**Issue by Variable-ind** [godotengine/godot#74417] opened 2023-03-05 06:44 UTC
### Godot version

4.0 stable

### System information

Linux Mint 21.1 Cinnamon, Graphics: Intel Corporation HD Graphics 620, Processor: Intel© Core™ i5-7200U CPU @ 2.50GHz × 2

### Issue description

The output of Texture2D `get_size()` is of type `Vector2` instead of `Vector2i`
this issue may be already present in issues somewhere but i couldn't find it

### Steps to reproduce

N/A

### Minimal reproduction project

N/A

**Comment by AThousandShips** [comment] 2023-03-05 08:30
Duplicate of #66727

**Closed** 2023-03-05 11:12 UTC

**Comment by akien-mga** [comment] 2023-03-05 11:13
> Won't get a fix until 5.0

That's not decided actually. There are no plans for a hypothetical 5.0 milestone for now, we focus on 4.x.
