### ISSUE TITLE
Unable to create @ with Finnish keyboard layout

### ISSUE THREAD

**Issue by slasktotten** [godotengine/godot#64561] opened 2022-08-18 06:24 UTC
### Godot version

Godot 4 alpha 14

### System information

MacOS 12.1

### Issue description

On Finnish keyboard layout (I believe this is true for all nordic layouts) option + 2 is needed to create @ symbol. However now it is selecting 3D viewport instead - meaning you can't type @ in a script.

### Steps to reproduce

Set keyboard type to Finnish. Try to use option + 2 to make @ symbol in a script.

**Comment by Calinou** [comment] 2022-08-18 13:24
Duplicate of https://github.com/godotengine/godot/issues/61468.

**Closed by Calinou** 2022-08-18 13:24 UTC
Labels: bug, topic:input
