### ISSUE TITLE
Recursion Loop Error with the Graph Loop Class

### ISSUE THREAD

**Issue by Natthapolmnc** [godotengine/godot#88766] opened 2024-02-24 15:16 UTC
### Tested versions

4.1.3-stable_win64

### System information

Windows 10-Godot4.1.3-stable_win64

### Issue description

For example, we wanted to make a state classes that have variable, which contain the info of next state.
It is typical things that the State can loop each other. However, the recursion error will occur even if the classes doesn't contain any function that can caused the recursion error.
 
![image](https://github.com/godotengine/godot/assets/46791675/c0195dab-ac0f-470b-9e18-3ec9d635c1da)

### Steps to reproduce

make the class that contain variable of the same classes and have the repeat loop value.

### Minimal reproduction project (MRP)

```
extends Resource

class_name StateTest

@export var connectedState:StateTest

```

**Comment by AThousandShips** [comment] 2024-02-24 15:23
Circular references are not supported, instead you should use [weak references](https://docs.godotengine.org/en/stable/classes/class_weakref.html), see:
* https://github.com/godotengine/godot-proposals/issues/7363

Closing as this is not a bug, and it has a clear warning, see the above documentation and proposal

**Closed by AThousandShips** 2024-02-24 15:23 UTC

**Comment by Natthapolmnc** [comment] 2024-02-25 02:03
Sorry, I have read the discussion and still a bit confused. So in summary, we should use ```WeakRef``` instead but ```WeakRef``` still not serializeable and not able to be ```@export```. Therefore, we still dont have a way to hack the circular reference with ```@export``` and Serializeable????. If there are ways to please guide me a bit. This is very confused me. I also saw the uID method but it seem to be a bit lousy practice or that the best we got??

**Comment by AThousandShips** [comment] 2024-02-25 10:36
Please discuss this on the proposal issue, where I explain things a bit more, and my suggestion for a solution using weak references in export :)
