### ISSUE TITLE
Editor wrongly reports performance when large numbers of reflection probes are present with certain settings

### ISSUE THREAD

**Issue by InitialCon** [godotengine/godot#99275] opened 2024-11-15 10:20 UTC
### Tested versions

- Reproducible in: 4.3 Stable

### System information

Godot v4.3.stable - Windows 10.0.19045 - Vulkan (Forward+) - dedicated AMD Radeon RX 6800 (Advanced Micro Devices, Inc.; 32.0.11027.1003) - Intel(R) Core(TM) i5-8600K CPU @ 3.60GHz (6 Threads)

### Issue description

When a 3D scene contains a large amount of reflection probes set to update always with shadows enabled, The reported GPU frame time decreases with each reflection probe added. The correct frame time is displayed if every reflection probe is hidden but lowers when they are made visible again. This only occurs in the editor as running the game correctly shows a frame time increase when they are made visible.

### Steps to reproduce

1. Create a 3D scene
2. Add reflection probes set to update always with shadows enabled
3. Watch as the framerate magically increases

### Minimal reproduction project (MRP)

[mrp.zip](https://github.com/user-attachments/files/17773979/mrp.zip)

**Comment by clayjohn** [comment] 2024-11-23 05:25
This is a duplicate of https://github.com/godotengine/godot/issues/49117

So I'll go ahead and close this so we can track the issue in one place. 

As a heads up, in the meantime, you can get more accurate frame GPU frame timing using the visual profiler instead as that includes ReflectionProbes

**Closed by clayjohn** 2024-11-23 05:25 UTC
