### ISSUE TITLE
Uncaught (in promise) TypeError: Failed to execute 'compile' on 'WebAssembly': Incorrect response MIME type. Expected 'application/wasm'.

### ISSUE THREAD

**Issue by linux-man** [godotengine/godot#47357] opened 2021-03-25 12:05 UTC
**Godot version:**
3.3.rc6

**OS/device including version:**
HTML5 Export (GLES2) on Linux Mint 20.1

**Issue description:**
On opening the exported game moved to a webserver folder, the error "Uncaught (in promise) TypeError: Failed to execute 'compile' on 'WebAssembly': Incorrect response MIME type. Expected 'application/wasm'." stops game loading.
Same game exported on Godot 3.2.3 just works.

There are no issues on local html opening and Godot "Run in Browser" option. Only when the files are moved to a webserver (tried with 2 shared Linux webservers).

**Steps to reproduce:**
Export to HTML5.
Copy folder to a webserver.
Access the game webpage

**Minimal reproduction project:**
I don't a have a minimalist project to send,

**Comment by akien-mga** [comment] 2021-03-25 12:11
Duplicate of #47048, will be fixed in 3.3 RC 7.

**Closed by akien-mga** 2021-03-25 12:11 UTC
