### ISSUE TITLE
Area doesn't work with concave collision shapes

### ISSUE THREAD

**Issue by shakenov-chinga** [godotengine/godot#16392] opened 2018-02-04 15:59 UTC
Hi, guys! I'm trying to work with Area objects, and it seems that it doesn't work with imported concave shapes. But it works with box, sphere, capsule shapes.
`area.get_overlapping_bodies().size()` also output 0 for concave shape

**Godot version:**

Godot 3.0 latest stable (29 Jan)

**OS/device including version:**

PC, Linux Mint 18.2 'Sonya'

**Issue description:**

**Steps to reproduce:**
I created two Area objects with collision shapes and one Area with imported mesh. Imported mesh converted collision shape to concave by default.

**Minimal reproduction project:**

[TestCollisionConcave.zip](https://github.com/godotengine/godot/files/1692987/TestCollisionConcave.zip)

**Comment by akien-mga** [comment] 2018-02-13 11:13
Can the error be reproduced with both the Bullet backend (default) and the GodotPhysics backend?

**Comment by bojidar-bg** [comment] 2018-02-13 12:40
Likely related to #4591/#4159

**Comment by reduz** [comment] 2018-02-13 13:02
Well, this is not really expected to work if you expect the inside of the
shape to act like a solid.. we will eventually need to add a convex 3d
decomposition library..

**Comment by cosmicchipsocket** [comment] 2018-07-24 01:41
Ran into this while doing a test import of a hollow pipe mesh from Blender. I have an Area attached to the bottom of my player-controlled object which is used to determine whether said object is on the floor. Due to this bug, it was impossible to jump while inside the pipe (and a few other floor-only physics tweaks weren't being applied).

I'm not sure why Godot would need a new convex decomposition library just for this, if it can be done within the Bullet physics engine.

What is the recommended workaround for this situation? I could replace the Area with a raycast, but I'm concerned that this would prevent jumping when the object is close to the edge of the platform.

**Comment by AndreaCatania** [comment] 2018-07-24 06:11
This issue could be a bit weird to explain, the problem is that a concave shape has not an inner area, indeed you can imagine it composode of foils that give only a collision but doesn't define an area.

So the concave box doesn't have an area even if you can visualize it with your brain. do this test make this concave box a static body and put another rigidbody inside it, you will see that you the rigid body can stay inside it without any problem.

**Comment by cosmicchipsocket** [comment] 2018-07-24 21:59
That doesn't answer my question. I wanted to know why this can't just be done in Bullet because it knows how to make a capsule collide with a trimesh.

**Comment by EzraT** [comment] 2018-09-02 19:35
Same thing happens to me too in 3.0.6 and 3.1-alpha1 (Linux Mint 19)
Will this be fixed in the stable release of 3.1? This is kind of a showstopper for me.

**Comment by AndreaCatania** [comment] 2018-09-02 20:25
The best solution is to create areas using primitive and convex shapes..
Concave shapes are hollow inside and doesn't create a volume.

**Comment by EzraT** [comment] 2018-09-02 20:35
If thats the case, then how am I supposed to make any sort of indoor level design using gridmaps, like caves for example, together with projectile nodes that use Area's that are supposed to collide with the inside of the walls?
Using convex or primitive shapes is not really an option in that case because it will never match the shape of the gridmap meshes that way.

**Comment by AndreaCatania** [comment] 2018-09-02 20:46
I don't know it depends on the result that you want... But usually an area
doesn't need to be an high detail shape... Also I imagine that you could
split the cave in multiple convex shape...

**Comment by EzraT** [comment] 2018-09-02 21:01
Sorry if its unclear, its a bit hard to explain, I'm not trying to use complex concave shapes for my Area nodes, they have sphere colliders because I use them for a projectile type object.

I need my projectile Area nodes to collide with my cave gridmap walls, who use concave collision shapes to work correctly, but with the way the engine works currently, there's no way for me to do that.

Here's a picture of my setup, not sure if it helps.
![untitled](https://user-images.githubusercontent.com/781121/44960671-e7971100-af03-11e8-8b25-7ce87d179b95.jpg)

I'm not sure if its visible on the picture, but it would be quite hard to make proper collision shapes for these with just primitives, and convex shapes won't work because those are closed.

**Comment by AndreaCatania** [comment] 2018-09-03 05:15
I see what is the problem, I let you know if it can be improved

In the meantime you could change the bullet area with a rigid body or
kinematic because the areas are kind of static / kinematic sensor for rigid
/ kinematic body and not a sensor for static body

**Comment by AndreaCatania** [comment] 2018-09-05 11:43
Fixed #21774

**Closed** 2018-09-05 12:40 UTC
Labels: bug, topic:physics

**Comment by manythrough** [comment] 2023-06-01 19:24
the mentioned fix does not work

**Comment by Zireael07** [comment] 2023-06-02 08:28
Bullet is an external engine - you'd have to check if it was ever reported to Bullet upstream.
