### ISSUE TITLE
Assets import is broken

### ISSUE THREAD

**Issue by lufog** [godotengine/godot#57225] opened 2022-01-25 19:26 UTC
### Godot version

4.0.alpha1 (31a7ddbf8)

### System information

Windows 11 21H2, Vulkan Clustered, Geforce 1660 (511.23)

### Issue description

When I import a folder with `png` images, in `FileSystem` it shows as 2 folders instead of 1, and when I import a folder with `wav` files I get `Load Errors` window.

### Steps to reproduce

https://user-images.githubusercontent.com/10379487/151044215-61170f54-f5fa-43d2-b769-4b9792b92dbb.mp4

### Minimal reproduction project

Any empty project should do. ([assets](https://github.com/uheartbeast/youtube-tutorials/blob/master/Action%20RPG/Action%20RPG%20Resources.zip))

**Comment by Calinou** [comment] 2022-01-25 20:10
This is likely a duplicate of https://github.com/godotengine/godot/issues/54774.

**Comment by lufog** [comment] 2022-03-06 13:39
@Calinou, both problems:
 * duplicates in file browser;
 * crash during import wav files;
 
were fixed. I don't know exactly when, but I can no longer reproduce them on v4.0.alpha.custom_build [272b35595].

**Closed** 2022-03-06 13:44 UTC
Labels: bug, topic:editor, topic:import, regression
