### ISSUE TITLE
Won't create file 

### ISSUE THREAD

**Issue by mamadont** [godotengine/godot#7205] opened 2016-11-29 16:52 UTC
**Operating system or device - Godot version:**

**Issue description** (what happened, and what was expected):
I just downloaded this program on my macbook, and everytime i try to make a new project nothing happens. When is choose the file path and click "create" nothing happens.

**Steps to reproduce:**

**Link to minimal example project** (optional but very welcome):

**Comment by bojidar-bg** [comment] 2016-11-30 12:15
Please, include OS and godot version as well :smile:

**Comment by mamadont** [comment] 2016-11-30 16:36
I am using OSX on version 2.1.1

**Comment by Noshyaar** [comment] 2018-04-08 03:36
First of all thank you for your report and sorry for the delay.

We released Godot 3.0 in January 2018 after 18 months of work, fixing many old issues either directly, or by obsoleting/replacing the features they were referring to.

We still have hundreds of issues whose relevance/reproducibility needs to be checked against the [current stable version](https://godotengine.org/download), and that's where you can help us.
**Could you check if the issue that you described initially is still relevant/reproducible in Godot 3.0 or any newer version, and comment about it here?**

For bug reports, please also make sure that the issue contains detailed steps to reproduce the bug and, if possible, a zipped project that can be used to reproduce it right away. This greatly speeds up debugging and bugfixing tasks for our contributors.

Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

Thanks in advance.

*Note: This message is being copy-pasted to many "stale" issues (90+ days without activity). It might happen that it is not meaningful for this specific issue or appears oblivious of the issue's context, if so please comment to notify the Bugsquad about it.*

**Comment by tavurth** [comment] 2018-08-22 19:45
Tested on `Godot 3.06` `OSX 10.12` mid 2014 macbook air, could not reproduce.
Propose closure.

@mamadont

**Comment by akien-mga** [comment] 2018-08-22 20:30
Thanks for testing, closing then.

**Closed by akien-mga** 2018-08-22 20:30 UTC
Labels: bug, needs testing, platform:osx
