### ISSUE TITLE
3.5 HTML5 exports crash on Chrome for Android 117

### ISSUE THREAD

**Issue by netAction** [godotengine/godot#82356] opened 2023-09-26 08:49 UTC
### Godot version

3.5.2, 3.5.3

### System information

Windows 64

### Issue description

HTML5 exports from Godot 3.5 seem to crash on Chrome for Android with an AW SNAP message. It works on Chrome for Windows.
This does not affect all smartphones but about half of them. All 3 Oneplus and some of our Samsung are affected, non of our Huawei.
On devices that do not crash immediately after loading, the games run perfetly all the time.
This does not depend on the Godot minor release version, the HTML5 exporter, the Windows version or the game.
Even old games on itch.io are affected. And my exports that worked a month ago on the same phones. https://trhrichard.itch.io/minecraft-2d
The web servers are no reason, I tried many web servers.
I connected to a PC via USB and started the Chrome DevTools. The console does show the same messages as on desktop Chrome until it silently crashes.

### Steps to reproduce

Open Godot 3.5, create a minimal game (just one image), export to HTML5, view on Chrome for Android 117.

### Minimal reproduction project

N/A

**Comment by ChronoDK** [comment] 2023-09-26 09:10
Can confirm. This happened with the release of Chrome 117. Things were fine before.

**Comment by akien-mga** [comment] 2023-09-26 09:16
- Duplicate of #82015.

**Closed by akien-mga** 2023-09-26 09:16 UTC
