### ISSUE TITLE
[3.2.2 beta 1] Sliders apply incorrect hover mask

### ISSUE THREAD

**Issue by Chaosus** [godotengine/godot#38103] opened 2020-04-22 05:10 UTC
**Godot version:**
3.2.2 beta 1

**OS/device including version:**
Win10

**Issue description:**
In 3.2 when you hover a mouse on the stylized Slider it processes correctly:
![slider_ok](https://user-images.githubusercontent.com/3036176/79942707-1d3d9480-8470-11ea-9251-75f520a94c30.gif)
In 3.2.2 however, it turns dark:
![slider_bug](https://user-images.githubusercontent.com/3036176/79942744-36dedc00-8470-11ea-9e04-65b933114589.gif)

**Steps to reproduce:**
Create Theme for Sliders and play with it on 3.2 and 3.2.2, but better download the demo project down below.

**Minimal reproduction project:**
[SliderBug.zip](https://github.com/godotengine/godot/files/4513924/SliderBug.zip)

**Comment by Calinou** [comment] 2020-04-22 09:17
This is not a bug. This is because an hover style for the Slider "filled" area was added in #37517, and the default fallback texture is used since you didn't define one.

**Comment by avencherus** [comment] 2020-04-24 05:19
I may be missing something, but from your MRP I'm not seeing either result from the Beta 1.  😕 

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/13004169/80177325-1d6e9900-8604-11ea-921a-34f6ac241121.gif)

**Comment by Chaosus** [comment] 2020-04-26 20:31
Thanks for the notice @Calinou! Indeed, this should be mentioned in the release notes.
 @avencherus The problem is: because project is created in older version of engine the style in theme does not automatically updated to add support for a new style.

**Comment by Calinou** [comment] 2020-07-09 13:14
@akien-mga Should I open a pull request to update the changelog and close this issue?

**Comment by akien-mga** [comment] 2020-07-09 13:16
A changelog for 3.2.1 and 3.2.2 would be great to have, but in the meantime this can be mentioned in the Known incompatibilities in the Godot 3.2.2 release blog post: https://godotengine.org/article/maintenance-release-godot-3-2-2

**Comment by akien-mga** [comment] 2020-07-09 13:24
> in the meantime this can be mentioned in the Known incompatibilities in the Godot 3.2.2 release blog post: https://godotengine.org/article/maintenance-release-godot-3-2-2

Done.

**Closed by akien-mga** 2020-07-09 13:24 UTC
Labels: discussion, topic:gui
