### ISSUE TITLE
you can not make vibrate both controls and mobile devices

### ISSUE THREAD

**Issue by zero2000** [godotengine/godot#17656] opened 2018-03-20 16:24 UTC
Hello, I have waited for the release of version 3.0 to see if they had implemented a module to enable the vibration of both a command, as well as a smartphone and I am disappointed that it does not exist and safe and several people will have requested. my question is
Why have not they implemented it natively?

since to generate a better kinesthetic in the game, as well as having a Ludonarrative Dissonance for the lack of kinesthesia in the game

I hope with fervor that is implemented since for this engine it would be very necessary

**Comment by Hinsbart** [comment] 2018-03-20 18:16
Closing as duplicate of #4833 / #5013

**Closed by Hinsbart** 2018-03-20 18:16 UTC

**Comment by Hinsbart** [comment] 2018-03-20 18:21
> a command

Do you mean a controller (gamepad)? That's already implemented for Linux and Mac. On Windows it works with XInput (-> XBox compatible gamepads). If you're on windows and it doesn't work for you, you probably have a DirectInput device. See #17002

**Comment by zero2000** [comment] 2018-03-21 13:44
@Hinsbart 
Yes, but the switch is also implemented, I hope so, but what is worth emphasizing is that it is also in mobile devices. that is to say, the android as ios. in that sense. They are not there and what I mean the most is smartphones.
