### ISSUE TITLE
Crash with error "BadValue" using primusrun in linux 

### ISSUE THREAD

**Issue by git2013vb** [godotengine/godot#34588] opened 2019-12-24 20:59 UTC
**Godot version:**
3.2 beta4
OS:
debian 10

```
(base) vale@debianace:~$ primusrun ./Desktop/Godot_v3.2-beta4_x11.64 
/usr/bin/primusrun: line 41: warning: command substitution: ignored null byte in input
Godot Engine v3.2.beta4.official - https://godotengine.org
OpenGL ES 3.0 Renderer: GeForce GT 650M/PCIe/SSE2
 
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  151 (GLX)
  Minor opcode of failed request:  24 (X_GLXCreateNewContext)
  Value in failed request:  0x0
  Serial number of failed request:  19
  Current serial number in output stream:  20
Terminated
```

I have to kill gogot because it wont start,
I tried suggestions from another issue #26907 but seems not related

Also I tried to use export LIBGL_ALWAYS_SOFTWARE=1
to be able to use godot with video card intel in the meantime 
but I have this error:
```
(base) vale@debianace:~/Desktop$ ./Godot_v3.2-beta4_x11.64 
Godot Engine v3.2.beta4.official - https://godotengine.org
X Error of failed request:  GLXBadFBConfig
  Major opcode of failed request:  151 (GLX)
  Minor opcode of failed request:  34 ()
  Serial number of failed request:  17
  Current serial number in output stream:  18
X Error of failed request:  GLXBadFBConfig
  Major opcode of failed request:  151 (GLX)
  Minor opcode of failed request:  34 ()
  Serial number of failed request:  17
  Current serial number in output stream:  18
ERROR: initialize: Condition ' ctxErrorOccurred || !p->glx_context ' is true. returned: ERR_UNCONFIGURED
   At: platform/x11/context_gl_x11.cpp:190.
ERROR: initialize: Condition ' !p->glx_context ' is true. returned: ERR_UNCONFIGURED
   At: platform/x11/context_gl_x11.cpp:177.
ERROR: is_viable: Error initializing GLAD
   At: drivers/gles2/rasterizer_gles2.cpp:166.

```

while if I use primusrun glxinfo it work normally:
```
(base) vale@debianace:~$ primusrun glxinfo
/usr/bin/primusrun: line 41: warning: command substitution: ignored null byte in input
name of display: :0.0
display: :0  screen: 0
direct rendering: Yes
server glx vendor string: NVIDIA Corporation
server glx version string: 1.4
server glx extensions:
    GLX_ARB_context_flush_control, GLX_ARB_create_context, 
    GLX_ARB_create_context_no_error, GLX_ARB_create_context_profile, 
    GLX_ARB_create_context_robustness, GLX_ARB_fbconfig_float, 
    GLX_ARB_multisample, GLX_EXT_buffer_age, 
    GLX_EXT_create_context_es2_profile, GLX_EXT_create_context_es_profile, 
    GLX_EXT_framebuffer_sRGB, GLX_EXT_import_context, GLX_EXT_libglvnd, 
    GLX_EXT_stereo_tree, GLX_EXT_swap_control, GLX_EXT_swap_control_tear, 
    GLX_EXT_texture_from_pixmap, GLX_EXT_visual_info, GLX_EXT_visual_rating, 
    GLX_NV_copy_image, GLX_NV_delay_before_swap, GLX_NV_float_buffer, 
    GLX_NV_multisample_coverage, GLX_NV_robustness_video_memory_purge, 
    GLX_SGIX_fbconfig, GLX_SGIX_pbuffer, GLX_SGI_swap_control, 
    GLX_SGI_video_sync
client glx vendor string: primus
client glx version string: 1.4
client glx extensions:
    GLX_ARB_create_context, GLX_ARB_create_context_profile, 
    GLX_ARB_get_proc_address
GLX version: 1.4
GLX extensions:
    GLX_ARB_create_context, GLX_ARB_create_context_profile, 
    GLX_ARB_get_proc_address
Memory info (GL_NVX_gpu_memory_info):
<... snip...>

```

**Comment by git2013vb** [comment] 2019-12-26 14:24
I add more info:
I installed in my debian 10:
`intel-microcode firmware-linux-nonfree`
also i did:
`sudo dpkg --add-architecture i386`
 from [here](https://www.unixmen.com/how-to-make-nvidia-optimus-technology-work-properly-on-debian/)

now I can:

-  run godot in intel card
- run nvidia-smi and optirun nvidia-smi with no problems
```
(base) vale@debianace:~$ optirun nvidia-smi
Thu Dec 26 14:04:48 2019       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 418.74       Driver Version: 418.74       CUDA Version: N/A      |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GT 650M     On   | 00000000:01:00.0 N/A |                  N/A |
| N/A   49C    P8    N/A /  N/A |      5MiB /  1999MiB |     N/A      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0                    Not Supported                                       |
+-----------------------------------------------------------------------------+

```
- run glxgears (it run in intel video card I guess)
- NOT run optirun glxgears 
```
(base) vale@debianace:~$ optirun glxgears
X Error of failed request:  BadMatch (invalid parameter attributes)
  Major opcode of failed request:  152 (GLX)
  Minor opcode of failed request:  11 (X_GLXSwapBuffers)
  Serial number of failed request:  37
  Current serial number in output stream:  38
primus: warning: dropping a frame to avoid deadlock
primus: warning: timeout waiting for display worker
terminate called without an active exception
```
I tried to run a almost empty godot project (Node2D + godot icon)

```
(base) vale@debianace:~/Desktop$ optirun --debug ./Godot_v3.2-beta4_x11.64 -e --path /home/vale/godot/test_nvidia/
[ 2180.477263] [DEBUG]Reading file: /etc/bumblebee/bumblebee.conf
[ 2180.477896] [DEBUG]optirun version 3.2.1 starting...
[ 2180.477925] [DEBUG]Active configuration:
[ 2180.477933] [DEBUG] bumblebeed config file: /etc/bumblebee/bumblebee.conf
[ 2180.477941] [DEBUG] X display: :8
[ 2180.477947] [DEBUG] LD_LIBRARY_PATH: /usr/lib/mesa-diverted/x86_64-linux-gnu:/usr/lib/mesa-diverted/i386-linux-gnu
[ 2180.477959] [DEBUG] Socket path: /var/run/bumblebee.socket
[ 2180.477971] [DEBUG] Accel/display bridge: auto
[ 2180.477982] [DEBUG] VGL Compression: proxy
[ 2180.477991] [DEBUG] VGLrun extra options: 
[ 2180.478004] [DEBUG] Primus LD Path: /usr/lib/x86_64-linux-gnu/primus:/usr/lib/i386-linux-gnu/primus:/usr/lib/primus:/usr/lib32/primus
[ 2180.478086] [DEBUG]Using auto-detected bridge primus
[ 2180.646360] [INFO]Response: Yes. X is active.

[ 2180.646388] [INFO]Running application using primus.
[ 2180.646569] [DEBUG]Process ./Godot_v3.2-beta4_x11.64 started, PID 3345.
Godot Engine v3.2.beta4.official - https://godotengine.org
OpenGL ES 3.0 Renderer: GeForce GT 650M/PCIe/SSE2
 
X Error of failed request:  BadMatch (invalid parameter attributes)
  Major opcode of failed request:  152 (GLX)
  Minor opcode of failed request:  11 (X_GLXSwapBuffers)
  Serial number of failed request:  37
  Current serial number in output stream:  38
ERROR: _EDITOR_GET: Condition ' !EditorSettings::get_singleton()->has_setting(p_setting) ' is true. returned: Variant()
   At: editor/editor_settings.cpp:1150.
ERROR: _EDITOR_GET: Condition ' !EditorSettings::get_singleton()->has_setting(p_setting) ' is true. returned: Variant()
   At: editor/editor_settings.cpp:1150.
ERROR: _EDITOR_GET: Condition ' !EditorSettings::get_singleton()->has_setting(p_setting) ' is true. returned: Variant()
   At: editor/editor_settings.cpp:1150.
ERROR: _EDITOR_GET: Condition ' !EditorSettings::get_singleton()->has_setting(p_setting) ' is true. returned: Variant()
   At: editor/editor_settings.cpp:1150.
ERROR: _EDITOR_GET: Condition ' !EditorSettings::get_singleton()->has_setting(p_setting) ' is true. returned: Variant()
   At: editor/editor_settings.cpp:1150.
ERROR: _EDITOR_GET: Condition ' !EditorSettings::get_singleton()->has_setting(p_setting) ' is true. returned: Variant()
   At: editor/editor_settings.cpp:1150.
ERROR: _EDITOR_GET: Condition ' !EditorSettings::get_singleton()->has_setting(p_setting) ' is true. returned: Variant()
   At: editor/editor_settings.cpp:1150.
handle_crash: Program crashed with signal 11
Dumping the backtrace. Please include this when reporting the bug on https://github.com/godotengine/godot/issues
[1] /lib/x86_64-linux-gnu/libc.so.6(+0x37840) [0x7fbff62bf840] (??:0)
[2] ./Godot_v3.2-beta4_x11.64() [0x1eb4348] (??:?)
[3] ./Godot_v3.2-beta4_x11.64() [0x1ed6b7c] (??:?)
[4] ./Godot_v3.2-beta4_x11.64() [0x1e6f437] (??:?)
[5] ./Godot_v3.2-beta4_x11.64() [0xbb7d74] (??:?)
[6] ./Godot_v3.2-beta4_x11.64() [0x181c88e] (<artificial>:?)
[7] ./Godot_v3.2-beta4_x11.64() [0x185f44e] (??:?)
[8] ./Godot_v3.2-beta4_x11.64() [0x28d3010] (??:?)
[9] ./Godot_v3.2-beta4_x11.64() [0x84119d] (??:?)
[10] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xeb) [0x7fbff62ac09b] (??:0)
[11] ./Godot_v3.2-beta4_x11.64() [0x84e29e] (??:?)
-- END OF BACKTRACE --
[ 2184.051246] [DEBUG]SIGCHILD received, but wait failed with No child processes
[ 2184.051278] [DEBUG]Socket closed.
[ 2184.051295] [DEBUG]Killing all remaining processes.

```
I understand can be possible that its a linux problem, but I'm not sure 100%
So now the title of this issue is not matching anymore I guess, firstly because I don't use primusrun anymore j. I use optirun instead because of different libs.

**Comment by git2013vb** [comment] 2019-12-26 17:34
Some good news about this issue:

After several reconfig and reboots I found the problem:
was misssing VirtualGL [explanation from here](https://www.pcsuggest.com/install-and-configure-nvidia-optimus-with-bumblebee-in-debian/)

Now godot work as long I set the project path when I open it. Because if not it crash with this error:
`XIO:  fatal IO error 2 (No such file or directory) on X server ":8"`

**Comment by akien-mga** [comment] 2020-01-03 13:03
Duplicate of #26907.

**Closed by akien-mga** 2020-01-03 13:03 UTC
Labels: bug, crash, platform:linuxbsd, topic:editor, topic:rendering
