### ISSUE TITLE
[Godot 3.6 Beta 2] Unable to scroll inspector resource selector

### ISSUE THREAD

**Issue by dogboydog** [godotengine/godot#77619] opened 2023-05-29 15:53 UTC
### Godot version

v3.6.beta2.mono.official [68c507f59]

### System information

Windows 10

### Issue description

When exporting a Resource from a c# script, I can no longer scroll through the massive list of resource types to find "New Resource" or "Quick Load" in the list in 3.6 beta 2.  I appreciate the work being done to enhance version 3 though, thank you. 

Click `[empty]`
![image](https://github.com/godotengine/godot/assets/9920963/630970ef-bbdb-4870-a64b-af18b833ee16)

This list appears. If you need to select something further down in the list, you can't 
![image](https://github.com/godotengine/godot/assets/9920963/29d5e23b-3319-4c21-be8e-6a508defaf1a)

Coming from 3.5.2, this stopped working. I opened the repro project in 3.5.2 and I'm still able to scroll up and down in that version. 

### Steps to reproduce

Open the project. Open Scene.tscn. Select the root Node2D node and select the exported field in the inspector. Attempt to scroll with the mouse wheel or keyboard. You cannot scroll down. 

### Minimal reproduction project

[InspectorScrollingRepro.zip](https://github.com/godotengine/godot/files/11592891/InspectorScrollingRepro.zip)

**Comment by lawnjelly** [comment] 2023-05-30 12:25
BTW do let us know if you see this in any dialogs not related to mono. This issue will probably only get looked at by mono guys, but it may not be _due_ to mono, so may be difficult to investigate, whereas anything in vanilla Godot anyone can investigate.

It is possible it could be generic problem in this control, but on the other hand maybe the parameters used are e.g. wrong specifically for this dialog, in which case it will need a mono guy to debug.

**Comment by dogboydog** [comment] 2023-05-30 14:25
You are right, I just tested with a GDScript version and the same happens there, so this is just a specific impact of the linked issue. Sorry, did not see that other one

**Comment by lawnjelly** [comment] 2023-05-30 15:24
Closing as seems to be duplicate of #76289 .

**Closed by lawnjelly** 2023-05-30 15:24 UTC
Labels: bug, topic:editor, topic:dotnet, topic:gui
