### ISSUE TITLE
Web builds do not work with Safari Browser anymore

### ISSUE THREAD

**Issue by Faeovin** [godotengine/godot#68012] opened 2022-10-29 08:53 UTC
### Godot version

3.5.1.stable

### System information

MacOS 13.0, Safari Browser 16.1

### Issue description

After the latest update of MacOS and it's Safari Browser, my web build stopped working - when loading it will crash, then reload the page, crash again and display "A problem repeatedly occured on <url>". If the game is embedded into the page, the whole page will crash.

I tried to figure out is wrong and then eventually tried other projects, of which all had the same behaviour. I then went to Godot Discord and tried to open projects of others from the Release channel: not a single one of them loaded.

I asked a friend who also got a Mac to try a few of them and he had exactly the same issues. So it looks like no web build is working with the Safari Browser anymore. 

### Steps to reproduce

Web builds crash with Safari Browser

**Comment by Sauermann** [comment] 2022-10-29 09:36
Duplicate of #67949

**Comment by timothyqiu** [comment] 2022-10-30 01:48
Closing as duplicate of #67949.

**Closed by timothyqiu** 2022-10-30 01:48 UTC
