### ISSUE TITLE
get_rotation() returns confusing euler angles

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#8012] opened 2017-03-12 04:12 UTC
In Godot 2.1

I set the rotation of a Camera to `(0, 180, 0)` in the editor.
But if I print `get_rotation()` in `_ready()`, I get `(-3.141593, -0, -3.141593)`, which in degrees is `(-180, 0, -180)`.
EDIT: if I close and repoen the scene, the inspector now shows `(-180, 0, -180)` in the rotation field as well.

I understand the angles technically represent the same orientation, however I didn't expected that, and I'm confused about how to initialize my FPS lookat now.

I have a [camera script](https://github.com/Zylann/voxelgame/blob/master/project/debug_camera.gd#L75) that has its own `yaw` and `pitch` (the latter being clamped), and these need to represent the initial rotation of the camera when the game starts, and it obviously won't work given the funky values `get_rotation()` returns.

Is there a way to initialize the rotations properly? Did this change in 3.0? Should I rewrite my script?

Edit: my current shitty workaround:
```gdscript
	# Nope, can't do this
	#_yaw = get_rotation().y

	var v = get_transform().basis.xform(Vector3(1,0,0))
	if v.z <= 0:
		_yaw = rad2deg(acos(v.x))
	elif v.z > 0:
		_yaw = -rad2deg(acos(v.x))
```

**Comment by bojidar-bg** [comment] 2017-03-12 13:04
I think this is a duplicate of #1479, right?

**Comment by eon-s** [comment] 2017-03-12 14:51
You can try a `Quat` based solution, in particular if you need some smooth rotation.

I think 3.0 recently changed the way it works.

**Comment by Zylann** [comment] 2017-03-12 15:13
I tried Quat but the API itself is not exposing a Quat, and I have no idea how to clamp angles when using Quats :s

**Comment by akien-mga** [comment] 2017-03-13 10:28
Duplicate of #1479 indeed.

**Closed by akien-mga** 2017-03-13 10:28 UTC
