### ISSUE TITLE
replacing nodes leaves the name of the previous node

### ISSUE THREAD

**Issue by ghost** [godotengine/godot#3480] opened 2016-01-27 10:19 UTC
![screenshot from 2016-01-27 12-10-32](https://cloud.githubusercontent.com/assets/6195060/12610372/05e83ef0-c4f0-11e5-988f-085fe71cb909.png)

So i have kinematicbody for example. and I replace it with a rigid body.
it changes correctly and I can see the properties of the rigid body. but the name stays the same.
not sure if a bug. but it certainly confused me.

**Comment by bojidar-bg** [comment] 2016-01-27 10:22
Not a bug, IMO, because if I had a custom name on a node (say, `spawn_team_red`), and decided that it should be a `Position2D`, and not a `Node2D`, after which it changed name to `Position2D`, all my current code would stop working.

Maybe... you want the name to change only if it was default?

**Comment by lordadamson** [comment] 2016-01-27 10:24
yeah I guess it would be a very nice feature

**Comment by akien-mga** [comment] 2016-01-27 11:28
I don't think the name should be changed, even if it were default. If you add scripts referring to "KinematicBody" and change the node time to RigidBody, you don't want your scripts to break - and we don't want to do advanced refactoring that should find the script references to "KinematicBody" and change them just to cater for this case IMO.

**Comment by Hinsbart** [comment] 2016-01-27 11:37
Maybe this could be optionally enabled in the editor settings? I would use this feature, after all if I have to change the type of a node that has existing functionality, I allready expect my scripts to break.

**Comment by bojidar-bg** [comment] 2016-01-27 11:37
Just to make it clear, I don't think that we should change the name in any case, but I'm not against it anyway. Thus, I agree with @Hinsbart that this should go into settings.

**Comment by akien-mga** [comment] 2016-01-27 12:13
IMO adding editor settings for such corner cases is a bit overkill... It would have to apply only when nodes have their default name (e.g. "KinematicBody"), and not when they have a more specific name (like "my_cool_player"). I don't think that we change node types often enough that it's worth adding an editor parameter for such a corner case.

Actually most of the times when I change a node type, it's for a node with a custom name, like changing my "level" node from Node2D to YSort. All in all the code change would likely not be invasive, but we have to remember that having tons of editor settings means have tons of various workflows, and some might end up having bugs that will be hard to notice if only a handful of users ever noticed the opt-in feature when browsing through hundreds of editor parameters :)

**Comment by vnen** [comment] 2016-01-27 14:50
This does not make sense to me. Replacing node types is a rare action IMO, and you usually give proper names instead of using the default.

Changing the name might cause scripts to break, as stated, and then you'd have to change all the names in the script anyway, so editing one more name (of the actual node) won't be much trouble.

I think I said that in other issue: what we need is proper refactoring tools. And a general design for those tools before adding functionalities like the one requested here.

**Comment by mhilbrunner** [comment] 2020-05-11 11:58
Closing as there is no consensus for implementing this. Also, this is quite old. :)

**Closed by mhilbrunner** 2020-05-11 11:58 UTC
Labels: discussion, feature proposal, topic:editor
