### ISSUE TITLE
VideoPlayer not working on html export

### ISSUE THREAD

**Issue by guilhermefelipecgs** [godotengine/godot#19705] opened 2018-06-21 17:15 UTC
**Godot version:**
3.0.3

**OS/device including version:**
Firefox 60.0.2

**Issue description:**
I can't play webm and ogv files on web.

This error happens when I tried play a webm file:
```
Init OS
Init Audio
Init VS
Init Physicsserver
OpenGL ES 3.0 Renderer: Mozilla
**ERROR**: Failed loading resource: 'res://Temperature1.webm';
**ERROR**:    At: modules/webm/video_stream_webm.cpp:56:MkvReader() - Condition ' !file ' is true.
```

And with ogv:
```
Init OS
Init Audio
Init VS
Init Physicsserver
OpenGL ES 3.0 Renderer: Mozilla
**ERROR**: Condition ' !ti ' is true. returned: StringName()
**ERROR**:    At: core/class_db.cpp:331:get_parent_class() - Condition ' !ti ' is true. returned: StringName()
**ERROR**: No loader found for resource: res://.import/temp1.ogv-ab81cabbdb166e0488226ae04fa42a3a.ogvstr
**ERROR**:    At: core/io/resource_loader.cpp:186:_load() - Method/Function Failed, returning: RES()
**ERROR**: Failed loading resource: res://temp1.ogv
**ERROR**:    At: core/io/resource_loader.cpp:186:_load() - Method/Function Failed, returning: RES()
**ERROR**: **WARNING**: Couldn't load external resource: res://temp1.ogv
**ERROR**:    At: scene/resources/scene_format_text.cpp:174:_parse_ext_resource() - Couldn't load external resource: res://temp1.ogv
```

**Steps to reproduce:**
Downlaod the project below and run in browser.
![captura de tela de 2018-06-21 14-12-17](https://user-images.githubusercontent.com/1387165/41734420-3c82f386-755d-11e8-8caf-881245bf42ca.png)

**Minimal reproduction project:**
[Bug Video Player.zip](https://github.com/godotengine/godot/files/2124663/Bug.Video.Player.zip)

**Comment by guilhermefelipecgs** [comment] 2018-06-21 17:20
Maybe duplicate of #14954?

**Comment by eska014** [comment] 2018-06-21 21:55
Yes, as detailed in that thread, neither WebM nor Theora files are currently included when exporting.
Closing as duplicate of #14954

**Closed by eska014** 2018-06-21 21:55 UTC
