### ISSUE TITLE
Imported models are flat.

### ISSUE THREAD

**Issue by KnightNine** [godotengine/godot#82890] opened 2023-10-06 02:22 UTC
### Godot version

v4.2.dev.custom_build [f71259be3]

### System information

Windows 10

### **IT'S FLATT!?!?**
![flatt](https://github.com/godotengine/godot/assets/34152090/82a231a8-1166-4af2-badd-043c6f88f55c)

My custom changes shouldn't affect this but can someone confirm that this happens in the raw build?

### Steps to reproduce

1) Import a blender file containing a model into your project.
2) Open it.
3) Observe Flatness.

### Minimal reproduction project
[flatt test.zip](https://github.com/godotengine/godot/files/12827277/flatt.test.zip)

**Comment by aaronfranke** [comment] 2023-10-06 03:17
I don't observe this behavior with test models. You must provide a minimal reproduction project.

**Comment by KnightNine** [comment] 2023-10-06 05:29
@aaronfranke I did a fresh compile of the master branch (v4.2.dev.custom_build [9e455f424]) and the issue persists.
Did you open a `.blend` file?

Didn't think I needed to considering how visible this issue is but I'll post just an empty project with my models imported, the issue might still be visible.

**Comment by aaronfranke** [comment] 2023-10-06 06:38
@KnightNine I tested the project you posted with Godot 9e455f424a635549b295272d82757c7ff99f33d7 and Blender Blender 3.6.4 on macOS. It's not flat for me. Maybe it's a problem with the Blender version you are using?

<img width="1218" alt="Screenshot 2023-10-06 at 1 36 25 AM" src="https://github.com/godotengine/godot/assets/1646875/90765d6c-a52b-4b81-94c8-b47f8101460b">

<img width="624" alt="Screenshot 2023-10-06 at 1 37 37 AM" src="https://github.com/godotengine/godot/assets/1646875/378e17cb-346a-450a-8eb5-4087eddf4f1f">

**Comment by LiveTrower** [comment] 2023-10-06 14:21
I can confirm that this happens and it's because of #81138.
![Screenshot](https://github.com/godotengine/godot/assets/48926464/bf5820a9-3661-41ec-b73b-1c2637492c54)
If you enable the "Force Disable Compression" option, this gets resolved, but not its AABB.
![Screenshot2](https://github.com/godotengine/godot/assets/48926464/f4cd956b-63e0-4e61-8963-e24c1ecf33c0)

**Comment by clayjohn** [comment] 2023-10-06 19:46
The issue goes away with a reimport for any reason. I tested both just re-importing with the import button and deleting the .import folder. 

So it seems the issue here is that the mesh upgrade path is not being triggered for this mesh. I will investigate further

**Comment by clayjohn** [comment] 2023-10-06 20:55
@KnightNine Can you please elaborate on how you created the MRP? When I reimport the model the issue goes away. The issue also goes away if I reimport from an earlier dev release and run it in current master. This indicates that the issue is specific to how you imported the model in. 

To be clear, I can only reproduce if I use the copy of the mesh in the .import folder. Anything imported in Master or older appears to work correctly. Accordingly, like AaronFranke, I am suspecting that the blender version be causing this issue

**Comment by KnightNine** [comment] 2023-10-06 21:17
@clayjohn 
wdym by "MRP"?
I am using the same blender version (3.6.4) but through Steam.
I'll try validating the integrity of my files or downloading blender outside of steam to see if I can resolve the issue.
Could blender addons affect the import process somehow?

**Comment by clayjohn** [comment] 2023-10-06 21:36
> wdym by "MRP"?

Minimal Reproduction Project. I.e. "flatt test.zip"

**Comment by KnightNine** [comment] 2023-10-06 21:41
@clayjohn 
I simply created a new project and imported my blender models with the default settings by dragging the .blend file into the editor. 

Anyways I downloaded a fresh version of blender a and tried enabling "Force Disable Compression" before reimporting.... the issue still persists. 💀
The only other thing it could be is hardware related though it seems unlikely as previous versions of godot worked fine. 🤔

Idk where to go from here.

**Comment by clayjohn** [comment] 2023-10-06 21:46
Its definitely not hardware related as I get the flat model when using your .import folder.

Did you update the version of blender in the Editor Settings as well (filesystem/import/blender/blender3_path)?

**Comment by LiveTrower** [comment] 2023-10-06 22:35
@clayjohn I have a project that I use to test development versions, and since #81138 was merged, I've had various issues with the models, from them appearing flat to disappearing from the camera's view. It seems that the AABBs don't work even if I force the compression to be disabled.
It even happens with the built-in meshes.

https://github.com/godotengine/godot/assets/48926464/ad963b34-e765-410d-aec6-1253b7e172ed

Note: I did delete the .godot folder.

**Comment by KnightNine** [comment] 2023-10-06 22:38
> Did you update the version of blender in the Editor Settings as well (filesystem/import/blender/blender3_path)?

yes I did.

**Comment by LiveTrower** [comment] 2023-10-07 19:14
@clayjohn Ok, I've noticed something very strange. When I use the artifact from the master branch, these problems occur, but when I use a version that I've compiled from my own computer, everything works somewhat better.

https://github.com/godotengine/godot/assets/48926464/60f1e46d-c76f-46c7-94b6-0a85ebd7ee17

https://github.com/godotengine/godot/assets/48926464/70b498fc-d5d2-41b9-bfe9-ca5ff966fd7b

**Comment by KnightNine** [comment] 2023-10-08 02:34
> @clayjohn I have a project that I use to test development versions, and since #81138 was merged, I've had various issues with the models, from them appearing flat to disappearing from the camera's view. It seems that the AABBs don't work even if I force the compression to be disabled. It even happens with the built-in meshes.

Same here, the AABBs aren't correct even when compression is disabled.
And disabling compression doesn't show within the advanced import settings window and it only appears fixed (discounting the AABBs) if the blend file is opened as a scene, so I didn't realize it could be somewhat fixed by disabling compression until now.

![flatt aabb](https://github.com/godotengine/godot/assets/34152090/80224464-a41a-4215-abb7-0942997a1f1e)


I'm gonna try to undo https://github.com/godotengine/godot/pull/81138 so that I can take advantage of godot's recent fixes without this issue until this is fixed.

**Comment by kevinkuo52** [comment] 2023-10-08 20:14
also faced issue with flat imported models with my project separate from repro posted.
Just sharing my observation if it helps.

I exported a simple model from blender (ver 3.3.1) to .obj, glb, and .daw to test.
- I see this issue for .obj and .glb file (did not try .blend)
- .dae works fine
- when compiled to windows x86_32, i dont see this issue. I see this issue when compiled to x86_64

setting force_disable_mesh_compression to true in ResourceImporterOBJ.xml fixes the obj import for me
<member name="force_disable_mesh_compression" type="bool" setter="" getter="" default="true">

![image](https://github.com/godotengine/godot/assets/20428482/2bd353ff-c400-42e2-b714-6256f24bd446)
![image](https://github.com/godotengine/godot/assets/20428482/5b42b581-da3c-4a77-b324-c9825c7efa1e)

**Comment by kevinkuo52** [comment] 2023-10-09 00:03
sharing some more notes

debug print in add_surface_from_arrays after _surface_set_data 
![image](https://github.com/godotengine/godot/assets/20428482/18ba1bf3-f304-4971-86b5-78a9c698dd20)

format: 34896613399
aabb: [P: (-1, -1, -1), S: (2, 2.00001, **0.00001**)] 
array size: 288
vertex count: 24
index size: 72
index count: 36
primitive: 3
New Scene Root
Create Node

but after adding print line in _surface_set_data to print aabb values,  issue is gone............
![image](https://github.com/godotengine/godot/assets/20428482/ccc9f7c0-16cc-400d-a744-268013249eec)

**Comment by KnightNine** [comment] 2023-10-09 00:25
@kevinkuo52 
>.dae works fine

the AABBs are still broken with .dae.

> setting force_disable_mesh_compression to true in ResourceImporterOBJ.xml fixes the obj import for me

are the AABBs fixed with that method?

> but after adding print line in _surface_set_data to print aabb values, issue is gone............
looks like aabb somehow get fixed from 0.00001 to 2 in the 2nd aabb.expand_to

Strange, though I may be completely wrong, seems like a threading issue from my experience, the print causes a delay which allows something to update that would be unable to without it. Does the engine use threads for these base functions?

**Comment by kevinkuo52** [comment] 2023-10-09 00:42
No, AABB wasn't fix with turning off force_disable_mesh_compression. And also issue seems flaky, just tried again with turning off compression, but it no longer doesn't fix the mesh vertex either

**Comment by KnightNine** [comment] 2023-10-09 00:55
I am hoping for a workaround, as there seems to be no quick way of removing the PR merge from my fork of Godot with my limited knowledge of git if there even is a way. 😭

I guess I'll try adding that print statement.

**Comment by clayjohn** [comment] 2023-10-11 22:02
Re-opening until we have confirmation that this is fixed. I'm still not sure

**Comment by LiveTrower** [comment] 2023-10-11 23:49
@clayjohn Problems persist

**Comment by clayjohn** [comment] 2023-10-11 23:53
@LiveTrower Problems persist after pulling from master and building fresh in the last hour and reimporting your models?

Can you also let me know what system and build settings you are using?

**Comment by LiveTrower** [comment] 2023-10-12 00:03
@clayjohn I tested the artifact from the master branch v4.2.beta.custom_build [b1371806a] and the problem persists, but it seems that the artifact from PR #83169 wasn't compiled.
The configuration I used to compile on my PC is x64 Native Tools Command Prompt for VS 2019 with the command scons platform=windows.

**Comment by kevinkuo52** [comment] 2023-10-12 02:59
@clayjohn 
i tested with latest master #82431 and still see the issue

> * I see this issue for .obj and .glb file
> * .dae works fine
> * when compiled to windows x86_32, i dont see this issue. I see this issue when compiled to x86_64
@clayjohn just to clarify on this since I didnt pay attention to AABB on this first post, only on mesh vertices:
AABB for .dae was still messed up in both 64 and 32 bit builds
obj and .glb works fine in 32 bit build for both AABB and mesh vertices
![image](https://github.com/godotengine/godot/assets/20428482/12235f90-345c-403f-b555-72290e1726d4)

**Comment by KnightNine** [comment] 2023-10-12 05:09
@clayjohn 
That is not expected for .dae . Without https://github.com/godotengine/godot/pull/81138 .dae's AABBs fit properly to the mesh.

**Comment by clayjohn** [comment] 2023-10-12 17:49
I've now tested on a Windows 10 system to see if its a Windows related issue and I still can't reproduce. I have also tested debug and non-debug builds to see if that is the issue and can't reproduce (both on Linux and on Windows).

I'm going to keep investigating, but it is challenging to confirm anything without being able to reproduce the issue. 

Because the AABBs are broken both when using compressed and uncompressed, it seems there is something broken with calculating, storing, or retrieving the mesh AABBs. I will investigate that further and see if I can identify a situation where AABBs may change depending on build, OS, or hardware.

**Comment by clayjohn** [comment] 2023-10-12 20:09
Okay, I've made another PR that might help with this. 

I can't find anywhere where the AABB generation has changed. So my current theory is that at certain points of the pipeline the mesh is treated as compressed, while at others it isn't, leading to a disconnect between the size of the AABB and the underlying surface data.

Please test it and let me know if it helps

**Comment by LiveTrower** [comment] 2023-10-12 21:23
@clayjohn I tried PR #83211 but everything remains the same.
What's curious is that I tested the beta 1 version from here https://github.com/godotengine/godot-builds/releases/tag/4.2-beta1 and everything works fine. I tested both the x64 and x32 versions.

**Comment by clayjohn** [comment] 2023-10-12 21:26
> @clayjohn I tried PR #83211 but everything remains the same. What's curious is that I tested the beta 1 version from here https://github.com/godotengine/godot-builds/releases/tag/4.2-beta1 and everything works fine. I tested both the x64 and x32 versions.

Is there any chance that you are accidentally testing an old build? Perhaps a build with a slightly different name/config?

**Comment by LiveTrower** [comment] 2023-10-12 22:02
I don't think so. 
v4.2.beta.custom_build [f57748493]

https://github.com/godotengine/godot/assets/48926464/53bba981-e30a-45cd-8352-0423a6cb64c3

**Comment by kevinkuo52** [comment] 2023-10-13 00:31
@clayjohn tried I tried PR https://github.com/godotengine/godot/pull/83211, same behavior as before as well.
![image](https://github.com/godotengine/godot/assets/20428482/2f99c9c2-71df-4770-8a7c-356e1ae10c37)

pulled ur change and made sure i used the new built exe
![image](https://github.com/godotengine/godot/assets/20428482/d67737ba-66a4-4c47-8777-10958d7a55df)

Will try to investigate as well since I have repro, will update if I find anything useful.

**Comment by kevinkuo52** [comment] 2023-10-13 02:12
- found dev build for 64 bit dont have issue for me, scons platform=windows **dev_build=yes** (i see issue when scons platform=windows for 64)
- for me, .dae file import have large AABB for all scenario even on stable release... (maybe just my issue? not sure)

I can't seem to have break points hit if i dont build it with dev_build=yes, even with -e arg pass in to launch straight to editor. not sure if im missing something
`"configurations": [
        {
        "name": "Launch Project",
        "type": "cppvsdbg",
        "request": "launch",
        "program": "${workspaceFolder}/bin/godot.windows.editor.x86_64.exe",
        // Change the arguments below for the project you want to test with.
        // To run the project instead of editing it, remove the "--editor" argument.
        "args": [ "--editor", "--path", "C:/src/GodotProjects/Second" ],
        "stopAtEntry": false,
        "cwd": "${workspaceFolder}",
        "environment": [],
        "console": "internalConsole",
        "visualizerFile": "${workspaceFolder}/platform/windows/godot.natvis",
        "preLaunchTask": "build"
        }
    ]`

guess i can go back to add prints but that method will be slow

**Comment by LiveTrower** [comment] 2023-10-13 13:52
@kevinkuo52 I have no issues with command scons platform=windows for 64

**Comment by kevinkuo52** [comment] 2023-10-16 00:00
since scons platform=windows for 64 works for LiveTower, maybe root cause is different.

but at least on my machine, after debugging for some time, i _believe_ the issue is related to the aabb variable here got optimized out weirdly by the compiler (maybe because of some code logic pattern on aabb) when i do scons platform=windows for 64

https://github.com/godotengine/godot/blob/a574c0296b38d5f786f249b12e6251e562c528cc/servers/rendering_server.cpp#L445C6-L445C16

This matches the observation where adding print_line "fixes" the issue because aabb became not optimized out.

Debugging steps that lead to this suspicion:


aabb is of type Rect2 here from the (p_format & RS::ARRAY_FLAG_USE_2D_VERTICES) if block, but that code path was never reached. prob because optimize=debug not used
![image](https://github.com/godotengine/godot/assets/20428482/a91d3fde-b38d-45cf-89ad-088c979119ae)

So I renamed variable to Rect2 aabb_rect2 and AABB aabb3 to distinguish.
![image](https://github.com/godotengine/godot/assets/20428482/ab7a57be-a795-45b7-85fe-e0794b8192f8)

setting the if block  (p_format & RS::ARRAY_FLAG_USE_2D_VERTICES) to always false, now aabb_rect2 doesn't appear.
See aabb3 is left and optimized out
![image](https://github.com/godotengine/godot/assets/20428482/3cb535b5-f9ad-4713-9a02-be8fac41d351)


 compile with optimize=debug instead (or when printing aabb once, same behavior):
scons platform=windows debug_symbols=yes optimize=debug -j 5
and stepping thru the code, **aabb is not optimized out and flat model issue does not appear.** 

![image](https://github.com/godotengine/godot/assets/20428482/c40a0108-dbad-46f4-ad2d-6029784c823f)

Assembly:

from quick glanced, when optimized out, aabb3.expand_to seems to be flattened out from the loop

aabb optmized out:
```
					// Setting vertices means regenerating the AABB.
					AABB aabb3;
00007FF72F2B741C  xor         eax,eax  
00007FF72F2B741E  xorps       xmm6,xmm6  
00007FF72F2B7421  mov         qword ptr [rbp-48h],rax  
00007FF72F2B7425  movups      xmmword ptr [rbp-58h],xmm6  
					//print_line("aab3: " + aabb3);
					if (p_format & ARRAY_FLAG_COMPRESS_ATTRIBUTES) {
00007FF72F2B7429  cmp         qword ptr [rbp-80h],rax  
00007FF72F2B742D  je          RenderingServer::_surface_set_data+0E26h (07FF72F2B7D26h)  
						// First we need to generate the AABB for the entire surface.
						for (int i = 0; i < p_vertex_array_len; i++) {
00007FF72F2B7433  movss       xmm12,dword ptr [rbp-44h]  
00007FF72F2B7439  mov         rdi,r11  
00007FF72F2B743C  movss       xmm13,dword ptr [rbp-48h]  
00007FF72F2B7442  movsxd      r10,r15d  
00007FF72F2B7445  test        r15d,r15d  
00007FF72F2B7448  jle         RenderingServer::_surface_set_data+723h (07FF72F2B7623h)  
00007FF72F2B744E  movss       xmm10,dword ptr [rbp-4Ch]  
00007FF72F2B7454  xor         r13d,r13d  
00007FF72F2B7457  mov         esi,dword ptr [rbp-50h]  
00007FF72F2B745A  movsd       xmm8,mmword ptr [rbp-58h]  
00007FF72F2B7460  mov         r12,qword ptr [rbp+0A0h]  
							//print_line("i: " + i);
							//print_line("src[i]: " + src[i]);
							if (i == 0) {
00007FF72F2B7467  lea         rbx,[rdi+rdi*2]  
00007FF72F2B746B  test        rdi,rdi  
00007FF72F2B746E  jne         RenderingServer::_surface_set_data+5DCh (07FF72F2B74DCh)  
								aabb3 = AABB(src[i], SMALL_VEC3);
00007FF72F2B7470  movsd       xmm0,mmword ptr [r12+1A8h]  
00007FF72F2B747A  mov         eax,dword ptr [r14+rbx*4+8]  
00007FF72F2B747F  movsd       xmm1,mmword ptr [r14+rbx*4]  
00007FF72F2B7485  movsd       mmword ptr [rbp+58h],xmm0  
00007FF72F2B748A  mov         dword ptr [rbp+54h],eax  
00007FF72F2B748D  movups      xmm6,xmmword ptr [rbp+4Ch]  
00007FF72F2B7491  mov         eax,dword ptr [r12+1B0h]  
00007FF72F2B7499  mov         dword ptr [rbp+60h],eax  
00007FF72F2B749C  movsd       xmm6,xmm1  
00007FF72F2B74A0  movsd       xmm1,mmword ptr [rbp+5Ch]  
								//print_line("not (p_format & RS::ARRAY_FLAG_USE_2D_VERTICES) if (p_format & ARRAY_FLAG_COMPRESS_ATTRIBUTES) create - aabb: " + aabb);
							} else {
00007FF72F2B74A5  movaps      xmm0,xmm1  
00007FF72F2B74A8  movsd       mmword ptr [rbp-48h],xmm1  
00007FF72F2B74AD  shufps      xmm0,xmm0,55h  
00007FF72F2B74B1  movaps      xmm10,xmm6  
00007FF72F2B74B5  movaps      xmm12,xmm0  
00007FF72F2B74B9  shufps      xmm10,xmm6,0FFh  
00007FF72F2B74BE  movdqa      xmm0,xmm6  
00007FF72F2B74C2  movaps      xmm13,xmm1  
00007FF72F2B74C6  psrldq      xmm0,8  
00007FF72F2B74CB  movaps      xmm8,xmm6  
00007FF72F2B74CF  movd        esi,xmm0  
00007FF72F2B74D3  movups      xmmword ptr [rbp+4Ch],xmm6  
00007FF72F2B74D7  jmp         RenderingServer::_surface_set_data+6F8h (07FF72F2B75F8h)  
								aabb3.expand_to(src[i]);
00007FF72F2B74DC  comiss      xmm7,xmm10  
00007FF72F2B74E0  ja          RenderingServer::_surface_set_data+5EEh (07FF72F2B74EEh)  
00007FF72F2B74E2  comiss      xmm7,xmm13  
00007FF72F2B74E6  ja          RenderingServer::_surface_set_data+5EEh (07FF72F2B74EEh)  
00007FF72F2B74E8  comiss      xmm7,xmm12  
00007FF72F2B74EC  jbe         RenderingServer::_surface_set_data+61Bh (07FF72F2B751Bh)  
00007FF72F2B74EE  mov         dword ptr [rsp+28h],r13d  
00007FF72F2B74F3  lea         r9,[string "AABB size is negative, this is @"... (07FF730567C00h)]  
00007FF72F2B74FA  mov         r8d,153h  
00007FF72F2B7500  mov         byte ptr [rsp+20h],r13b  
00007FF72F2B7505  lea         rdx,[string "C:\\src\\GodotProjects\\godot\\core@"... (07FF730567C68h)]  
00007FF72F2B750C  lea         rcx,[string "AABB::expand_to" (07FF730567C98h)]  
00007FF72F2B7513  call        _err_print_error (07FF72FB9DAC0h)  
00007FF72F2B7518  movsxd      r10,r15d  
00007FF72F2B751B  movss       xmm1,dword ptr [rbp-58h]  
00007FF72F2B7520  movaps      xmm0,xmm8  
00007FF72F2B7524  movss       xmm2,dword ptr [r14+rbx*4]  
00007FF72F2B752A  addss       xmm10,xmm1  
00007FF72F2B752F  comiss      xmm1,xmm2  
00007FF72F2B7532  addss       xmm13,dword ptr [rbp-54h]  
00007FF72F2B7538  movaps      xmm4,xmm0  
00007FF72F2B753B  movsd       mmword ptr [rbp+80h],xmm0  
00007FF72F2B7543  movd        xmm0,esi  
00007FF72F2B7547  addss       xmm12,xmm0  
00007FF72F2B754C  jbe         RenderingServer::_surface_set_data+666h (07FF72F2B7566h)  
00007FF72F2B754E  movaps      xmm0,xmm8  
00007FF72F2B7552  movaps      xmm6,xmm2  
00007FF72F2B7555  movss       xmm0,xmm2  
00007FF72F2B7559  movsd       mmword ptr [rbp+80h],xmm0  
00007FF72F2B7561  movaps      xmm4,xmm0  
00007FF72F2B7564  jmp         RenderingServer::_surface_set_data+66Eh (07FF72F2B756Eh)  
00007FF72F2B7566  movss       xmm6,dword ptr [rbp+80h]  
00007FF72F2B756E  movss       xmm0,dword ptr [r14+rbx*4+4]  
00007FF72F2B7575  movss       xmm5,dword ptr [rbp+84h]  
00007FF72F2B757D  comiss      xmm5,xmm0  
00007FF72F2B7580  jbe         RenderingServer::_surface_set_data+68Bh (07FF72F2B758Bh)  
00007FF72F2B7582  movaps      xmm4,xmm6  
00007FF72F2B7585  movaps      xmm5,xmm0  
00007FF72F2B7588  unpcklps    xmm4,xmm0  
00007FF72F2B758B  movss       xmm1,dword ptr [r14+rbx*4+8]  
00007FF72F2B7592  movd        xmm3,esi  
00007FF72F2B7596  comiss      xmm3,xmm1  
00007FF72F2B7599  jbe         RenderingServer::_surface_set_data+6A2h (07FF72F2B75A2h)  
00007FF72F2B759B  movaps      xmm3,xmm1  
00007FF72F2B759E  movd        esi,xmm1  
00007FF72F2B75A2  comiss      xmm2,xmm10  
00007FF72F2B75A6  jbe         RenderingServer::_surface_set_data+6ACh (07FF72F2B75ACh)  
00007FF72F2B75A8  movaps      xmm10,xmm2  
00007FF72F2B75AC  comiss      xmm0,xmm13  
00007FF72F2B75B0  jbe         RenderingServer::_surface_set_data+6B6h (07FF72F2B75B6h)  
00007FF72F2B75B2  movaps      xmm13,xmm0  
00007FF72F2B75B6  comiss      xmm1,xmm12  
00007FF72F2B75BA  jbe         RenderingServer::_surface_set_data+6C0h (07FF72F2B75C0h)  
00007FF72F2B75BC  movaps      xmm12,xmm1  
00007FF72F2B75C0  subss       xmm10,xmm6  
00007FF72F2B75C5  mov         dword ptr [rbp-50h],esi  
00007FF72F2B75C8  movups      xmm6,xmmword ptr [rbp-58h]  
00007FF72F2B75CC  subss       xmm13,xmm5  
00007FF72F2B75D1  movaps      xmm8,xmm4  
00007FF72F2B75D5  movsd       xmm6,xmm4  
00007FF72F2B75D9  subss       xmm12,xmm3  
00007FF72F2B75DE  shufps      xmm6,xmm6,93h  
00007FF72F2B75E2  movss       xmm6,xmm10  
00007FF72F2B75E7  shufps      xmm6,xmm6,39h  
00007FF72F2B75EB  movaps      xmm0,xmm13  
00007FF72F2B75EF  unpcklps    xmm0,xmm12  
00007FF72F2B75F3  movss       dword ptr [rbp-48h],xmm0  
						// First we need to generate the AABB for the entire surface.
						for (int i = 0; i < p_vertex_array_len; i++) {
00007FF72F2B75F8  inc         rdi  
00007FF72F2B75FB  movups      xmmword ptr [rbp-58h],xmm6  
00007FF72F2B75FF  cmp         rdi,r10  
00007FF72F2B7602  jl          RenderingServer::_surface_set_data+567h (07FF72F2B7467h)  
00007FF72F2B7608  mov         r13,qword ptr [rsp+78h]  
00007FF72F2B760D  xor         r11d,r11d  
00007FF72F2B7610  mov         r12,qword ptr [rbp+30h]  
00007FF72F2B7614  movss       xmm8,dword ptr [__real@3f000000 (07FF7304C9BD8h)]  
00007FF72F2B761D  mov         esi,dword ptr [ai]  
00007FF72F2B7621  jmp         RenderingServer::_surface_set_data+73Bh (07FF72F2B763Bh)  
00007FF72F2B7623  movaps      xmm0,xmm13  
00007FF72F2B7627  xorps       xmm1,xmm1  
00007FF72F2B762A  unpcklps    xmm0,xmm12  
00007FF72F2B762E  shufps      xmm1,xmm6,0FFh  
00007FF72F2B7632  movss       dword ptr [rbp-48h],xmm0  
00007FF72F2B7637  movaps      xmm10,xmm1  
								//print_line("not (p_format & RS::ARRAY_FLAG_USE_2D_VERTICES) if (p_format & ARRAY_FLAG_COMPRESS_ATTRIBUTES) expand_to - aabb: " + aabb);
							}
						}
```
aabb not optmized out:
```
					// Setting vertices means regenerating the AABB.
					AABB aabb3;
00007FF6A4FC6C26  lea         rcx,[rsp+2B8h]  
00007FF6A4FC6C2E  call        AABB::AABB (07FF6A1A15FE0h)  
					//print_line("aab3: " + aabb3);
					if (p_format & ARRAY_FLAG_COMPRESS_ATTRIBUTES) {
00007FF6A4FC6C33  mov         rax,qword ptr [p_format]  
00007FF6A4FC6C3B  and         rax,20000000h  
00007FF6A4FC6C41  test        rax,rax  
00007FF6A4FC6C44  je          RenderingServer::_surface_set_data+14C3h (07FF6A4FC7883h)  
						// First we need to generate the AABB for the entire surface.
						for (int i = 0; i < p_vertex_array_len; i++) {
00007FF6A4FC6C4A  mov         dword ptr [rsp+88h],0  
00007FF6A4FC6C55  jmp         RenderingServer::_surface_set_data+8A7h (07FF6A4FC6C67h)  
00007FF6A4FC6C57  mov         eax,dword ptr [rsp+88h]  
00007FF6A4FC6C5E  inc         eax  
00007FF6A4FC6C60  mov         dword ptr [rsp+88h],eax  
00007FF6A4FC6C67  mov         eax,dword ptr [p_vertex_array_len]  
00007FF6A4FC6C6E  cmp         dword ptr [rsp+88h],eax  
00007FF6A4FC6C75  jge         RenderingServer::_surface_set_data+946h (07FF6A4FC6D06h)  
							//print_line("i: " + i);
							//print_line("src[i]: " + src[i]);
							if (i == 0) {
00007FF6A4FC6C7B  cmp         dword ptr [rsp+88h],0  
00007FF6A4FC6C83  jne         RenderingServer::_surface_set_data+917h (07FF6A4FC6CD7h)  
								aabb3 = AABB(src[i], SMALL_VEC3);
00007FF6A4FC6C85  mov         rax,qword ptr [this]  
00007FF6A4FC6C8D  add         rax,1A8h  
00007FF6A4FC6C93  movsxd      rcx,dword ptr [rsp+88h]  
00007FF6A4FC6C9B  imul        rcx,rcx,0Ch  
00007FF6A4FC6C9F  mov         rdx,qword ptr [rsp+0D0h]  
00007FF6A4FC6CA7  add         rdx,rcx  
00007FF6A4FC6CAA  mov         rcx,rdx  
00007FF6A4FC6CAD  mov         r8,rax  
00007FF6A4FC6CB0  mov         rdx,rcx  
00007FF6A4FC6CB3  lea         rcx,[rsp+848h]  
00007FF6A4FC6CBB  call        AABB::AABB (07FF6A20768F0h)  
00007FF6A4FC6CC0  lea         rcx,[rsp+2B8h]  
00007FF6A4FC6CC8  mov         rdi,rcx  
00007FF6A4FC6CCB  mov         rsi,rax  
00007FF6A4FC6CCE  mov         ecx,18h  
00007FF6A4FC6CD3  rep movs    byte ptr [rdi],byte ptr [rsi]  
								//print_line("not (p_format & RS::ARRAY_FLAG_USE_2D_VERTICES) if (p_format & ARRAY_FLAG_COMPRESS_ATTRIBUTES) create - aabb: " + aabb);
							} else {
00007FF6A4FC6CD5  jmp         RenderingServer::_surface_set_data+941h (07FF6A4FC6D01h)  
								aabb3.expand_to(src[i]);
00007FF6A4FC6CD7  movsxd      rax,dword ptr [rsp+88h]  
00007FF6A4FC6CDF  imul        rax,rax,0Ch  
00007FF6A4FC6CE3  mov         rcx,qword ptr [rsp+0D0h]  
00007FF6A4FC6CEB  add         rcx,rax  
00007FF6A4FC6CEE  mov         rax,rcx  
00007FF6A4FC6CF1  mov         rdx,rax  
00007FF6A4FC6CF4  lea         rcx,[rsp+2B8h]  
00007FF6A4FC6CFC  call        AABB::expand_to (07FF6A1A22630h)  
								//print_line("not (p_format & RS::ARRAY_FLAG_USE_2D_VERTICES) if (p_format & ARRAY_FLAG_COMPRESS_ATTRIBUTES) expand_to - aabb: " + aabb);
							}
						}
```


I will continue this direction when i got free time.
But let me know any thoughts, tips, idea, things I should check for etc.
thanks

**Comment by clayjohn** [comment] 2023-10-17 07:30
@kevinkuo52 That seems very likely. It must be a compiler-specific issue which is why AaronFranke and myself can't reproduce. 

Looking at the code with your post in mind. I am struck that there is a situation where the AABB may not get set at all: namely, when the mesh does not use normals or tangents. In that case, we fill the vertex array with positions only and then move on and ``r_aabb`` ends up uninitialized. 

https://github.com/godotengine/godot/blob/fd33c7b32f54e9ac3d346be718618575338cd7ef/servers/rendering_server.cpp#L459-L473

Instead of operating on ``aabb`` and then assigning to ``r_aabb``. Can you try modifying the code to operate on ``r_aabb`` directly? I.e.:

```
if (i == 0) {
	r_aabb = AABB(src[i], SMALL_VEC3);
} else {
	r_aabb.expand_to(src[i]);
}
```

**Comment by clayjohn** [comment] 2023-10-19 22:32
Looks like I am able to reproduce the issue now, but only on Windows and only when using compiled builds from our Github Actions (I tested https://github.com/godotengine/godot/actions/runs/6576288429/job/17865371862 for reference). Building locally with the exact same options does not reproduce the issue. 

My exact compiler version is MSVC 14.36.32532. For those of you who can reproduce the issue when building locally, can you also post what compiler version you are using?

**Comment by KnightNine** [comment] 2023-10-21 21:35
@clayjohn 
I am using MSVC 14.34.31933.
the imported models are still flat.

**Comment by kevinkuo52** [comment] 2023-10-22 00:23
> Looking at the code with your post in mind. I am struck that there is a situation where the AABB may not get set at all: namely, when the mesh does not use normals or tangents. In that case, we fill the vertex array with positions only and then move on and `r_aabb` ends up uninitialized.

Just to clarify, `using_normals_tangents` is true when i step thru it, so it does not skip and will set `r_aabb` in the end to an incorrect z value for size like this when aabb is optimized out by compiler:
[P: (-1, -1, -1), S: (2, 2.00001, 0.00001)]

> 
> Instead of operating on `aabb` and then assigning to `r_aabb`. Can you try modifying the code to operate on `r_aabb` directly? I.e.:
> 
> ```
> if (i == 0) {
> 	r_aabb = AABB(src[i], SMALL_VEC3);
> } else {
> 	r_aabb.expand_to(src[i]);
> }
> ```

Tried it, it does seem to mitigate the issue. Tho not sure if its an actual fix, suspect there's some underlying issue that cause aabb to be optimized out?
 (should i have time this weekend, will see if i can figure something out from the assembly difference... no promise tho..)

side note:
when step thru code i notice for 64 build, it will hit this condition here where `tangent_type == Variant::PACKED_FLOAT32_ARRAY) {`

Want to mentioned it just in case it seems off? or is it expected

https://github.com/godotengine/godot/blob/f71f4b80e32f6e98a4cd3cb1c06071223297e8fc/servers/rendering_server.cpp#L485C7-L486C66
![image](https://github.com/godotengine/godot/assets/20428482/d483aea9-7d10-4186-9a9b-1b3aace49e99)

I see it's set here 
https://github.com/godotengine/godot/blob/f71f4b80e32f6e98a4cd3cb1c06071223297e8fc/scene/resources/surface_tool.cpp#L474C4-L475C25
always seems to be type `Vector<float>` so not sure how it will ever be PACKED_FLOAT64_ARRAY, maybe some other flow.

**Comment by clayjohn** [comment] 2023-10-23 12:05
> Side note: when step thru code i notice for 64 build, it will hit this condition here where `tangent_type == Variant::PACKED_FLOAT32_ARRAY` Want to mentioned it just in case it seems off? or is it expected https://github.com/godotengine/godot/blob/f71f4b80e32f6e98a4cd3cb1c06071223297e8fc/servers/rendering_server.cpp#L485C7-L486C66 ![image](https://user-images.githubusercontent.com/20428482/277132796-d483aea9-7d10-4186-9a9b-1b3aace49e99.png)
> 
> I see it's set here https://github.com/godotengine/godot/blob/f71f4b80e32f6e98a4cd3cb1c06071223297e8fc/scene/resources/surface_tool.cpp#L474C4-L475C25 always seems to be type `Vector<float>` so not sure how it will ever be PACKED_FLOAT64_ARRAY, maybe some other flow.

Arrays can also be created by users directly with the ArrayMesh. In which case both floats and doubles are accepted. SurfaceTool always uses floats though and that is fine.

**Comment by clayjohn** [comment] 2023-10-23 12:07
> Just to clarify, `using_normals_tangents` is true when i step thru it, so it does not skip and will set `r_aabb` in the end with an incorrect z value for size like this when aabb is optimized out by compiler: [P: (-1, -1, -1), S: (2, 2.00001, 0.00001)]
> 
> > Instead of operating on `aabb` and then assigning to `r_aabb`. Can you try modifying the code to operate on `r_aabb` directly? I.e.:
> > ```
> > if (i == 0) {
> > 	r_aabb = AABB(src[i], SMALL_VEC3);
> > } else {
> > 	r_aabb.expand_to(src[i]);
> > }
> > ```
> 
> Tried it, it does seem to mitigate the issue. Tho not sure if its an actual fix, suspect there's some underlying issue that cause aabb to have weird behavior when optimized out? (i should have time this weekend, will see if i can figure something out... no promise tho..)

My working theory is that the compiler sees that ``r_aabb`` is only guaranteed to be written out in the 2D case so it thinks that it is okay to optimize out the z component.

**Closed** 2023-10-26 14:06 UTC
Labels: bug, topic:import, regression, topic:3d
