### ISSUE TITLE
Tab key doesn't move between editor fields in the inspector

### ISSUE THREAD

**Issue by spindlebink** [godotengine/godot#54602] opened 2021-11-04 16:55 UTC
### Godot version

4.0 dev (804406fcaf49789d4618d9c33f71d16996e95504)

### System information

Ubuntu 21.10

### Issue description

When using the editor, pressing the tab key while editing an inspector field does not appear to have any effect at all. In 3.x, tab moves between editable fields in order, as expected for a desktop app.

### Steps to reproduce

Open editor to any project (fresh or existing) -> select a node -> edit a field of the node (i.e. `transform.position`'s X/Y/Z coords) -> press tab key -> currently-selected field remains selected and editing.

**Comment by Calinou** [comment] 2021-11-04 17:08
Duplicate of https://github.com/godotengine/godot/issues/37723.

**Comment by spindlebink** [comment] 2021-11-04 17:16
I'm uncertain if that's the case--in this case, pressing tab does absolutely nothing at all on any fields, while in the other, the field does in fact change, it's just the input after tab that doesn't seem to be working. I could just be unaware of an underlying linked cause, though.

**Comment by dalexeev** [comment] 2021-12-01 11:16
Arrow keys don't work either, need fix. [Comment](https://github.com/godotengine/godot/issues/55169#issuecomment-983516261):

> #54842 will only fix Tab key but not arrow keys.

**Closed** 2022-01-26 12:35 UTC
Labels: bug, topic:editor, usability, regression, topic:gui
