### ISSUE TITLE
Dock sizes re-adjust themselves after the Godot Editor is minimized

### ISSUE THREAD

**Issue by Aaron-Fleisher** [godotengine/godot#23762] opened 2018-11-17 11:47 UTC
**Godot version:**
Latest, 0afdc5c559520204987544d30560745dbf29a390

**OS/device including version:**
Win 10, 64-bit, GTX 960

**Issue description:**
When you re-size a dock in the editor (width or height), and minimize the Godot Editor and re-open the editor, the dock positions will reset to their minimum size.
**This does not happen on 3.0.6**
 - I read #13439, but this is reproducible consistently and no errors are shown. Not sure 
![](https://i.gyazo.com/0603d2cf9293b1b521bf9be5f8625620.gif)

**Comment by groud** [comment] 2018-11-17 13:06
Duplicate of #23642

**Closed by groud** 2018-11-17 13:06 UTC
