### ISSUE TITLE
Editor crashes when method parameter is constant value

### ISSUE THREAD

**Issue by Breadp4ck** [godotengine/godot#96638] opened 2024-09-06 05:56 UTC
### Tested versions

- Reproducible in 4.4.dev1. It works fine with 4.3.stable.

### System information

Arch Linux

### Issue description

When I tried to write code that called a function with constant parameter (like `true`), the editor will crash.

```gdscript
func _ready() -> void:
    var object := SimpleObject.new()
    object.function( # I want to write "true)", but the editor will crash
```

But when I use a variable instead, all works fine.

```gdscript
func _ready() -> void:
    var object := SimpleObject.new()
    var value := true
    object.function(value) # No crashing!
```

Crash Dump:

```
handle_crash: Program crashed with signal 11
Engine version: Godot Engine v4.4.dev1.official (28a72fa4344befeae251d8e9b11b84acd601a244)
Dumping the backtrace. Please include this when reporting the bug to the project developer.
[1] /usr/lib/libc.so.6(+0x3d1d0) [0x7a7f18a651d0] (??:0)
[2] /home/alexander/Programs/Godot_v4.4-dev1_linux.x86_64() [0x744e3b] (??:0)
[3] /home/alexander/Programs/Godot_v4.4-dev1_linux.x86_64() [0x7892b6] (??:0)
[4] /home/alexander/Programs/Godot_v4.4-dev1_linux.x86_64() [0x789f21] (??:0)
[5] /home/alexander/Programs/Godot_v4.4-dev1_linux.x86_64() [0x789bf9] (??:0)
[6] /home/alexander/Programs/Godot_v4.4-dev1_linux.x86_64() [0x463acb0] (??:0)
[7] /home/alexander/Programs/Godot_v4.4-dev1_linux.x86_64() [0x7a81b9] (??:0)
[8] /home/alexander/Programs/Godot_v4.4-dev1_linux.x86_64() [0x1afd7c1] (??:0)
[9] /home/alexander/Programs/Godot_v4.4-dev1_linux.x86_64() [0x1efbd5b] (??:0)
[10] /home/alexander/Programs/Godot_v4.4-dev1_linux.x86_64() [0x426e0e1] (??:0)
[11] /home/alexander/Programs/Godot_v4.4-dev1_linux.x86_64() [0x23e322e] (??:0)
[12] /home/alexander/Programs/Godot_v4.4-dev1_linux.x86_64() [0x426e0e1] (??:0)
[13] /home/alexander/Programs/Godot_v4.4-dev1_linux.x86_64() [0x235e207] (??:0)
[14] /home/alexander/Programs/Godot_v4.4-dev1_linux.x86_64() [0x41fbc38] (??:0)
[15] /home/alexander/Programs/Godot_v4.4-dev1_linux.x86_64() [0x2355ffb] (??:0)
[16] /home/alexander/Programs/Godot_v4.4-dev1_linux.x86_64() [0x23b3083] (??:0)
[17] /home/alexander/Programs/Godot_v4.4-dev1_linux.x86_64() [0x23b3679] (??:0)
[18] /home/alexander/Programs/Godot_v4.4-dev1_linux.x86_64() [0x50cc8f] (??:0)
[19] /home/alexander/Programs/Godot_v4.4-dev1_linux.x86_64() [0x41e5d2] (??:0)
[20] /usr/lib/libc.so.6(+0x25e08) [0x7a7f18a4de08] (??:0)
[21] /usr/lib/libc.so.6(__libc_start_main+0x8c) [0x7a7f18a4decc] (??:0)
[22] /home/alexander/Programs/Godot_v4.4-dev1_linux.x86_64() [0x43a64a] (??:0)
```

### Steps to reproduce

You may try to call a function from the other user-specified script class. Just try to change `value` to `true`, when you called the object's method (`function`).

```gdscript

# main.gd
extends Object

func _ready() -> void:
    var object := SimpleObject.new()
    var value := true
    object.function(value)


# simple_object.gd
extends Object
class_name SimpleObject

func function(value: bool) -> void:
    pass

```

### Minimal reproduction project (MRP)

[godot-constant-parameter-crash.zip](https://github.com/user-attachments/files/16903393/godot-constant-parameter-crash.zip)

**Comment by HolonProduction** [comment] 2024-09-06 06:54
Duplicate of https://github.com/godotengine/godot/issues/96239, fixed by https://github.com/godotengine/godot/pull/96243

**Closed** 2024-09-06 07:09 UTC
