### ISSUE TITLE
HTML 5 Export - On Mobile Browser (FF/Chrome) on Android - FullScreen Toggle - Touch Button - Touch Area missbehaves

### ISSUE THREAD

**Issue by Zappo-II** [godotengine/godot#24399] opened 2018-12-16 11:35 UTC
**Godot version:**
3.0.6

**OS/device including version:**
Godot 3.0.6. on Arch Linux --> Html 5 Export --> Android 8.0.0 on 3.18.91 --> FireFox 63.0.2

**Issue description:**
A Game Export to HTML 5 with fixed Screen Size and FullScreen Toggle Function using TouchButtons on TouchEnabledDevices behaves as expected on Desktop Browsers in both "original" and toggled to FullScreen modes...

When Accessing the HTML 5 Export from a Mobile Browser (tested with current FireFox and Chrome) from Android, Game behaves as expected IF NOT Toggled To FullScreen...

WHEN TOGGLED TO FULLSCREEN the TouchButtons and the general Graphics Output is correctly Scaled and displayed but the Touch sensitive Area of the TouchButtons is misplaced (it seems as if the touch sensitive Area stays where it would be if the grafix was not being scaled at all)...

**Steps to reproduce:**
New Project, Add Node, add TouchButton, add Image to touchButton, add ui_action to touchButton, move touchButton to lower right corner of viewport, add func _input(ev) to Node, intercept ui_action there to toggle fullscreen, export to HTML 5, deploy to WebServer, access from Mobile Device via Browser, toggle fullscreen, try toggling back (won't work since the scaled Button Image is Placed/Displayed correctly but the touchArea is not, touching the screen were the touchButton would be if the scene was not scaled on the other hand works...)... 

**Minimal reproduction project:**
- none -

**Comment by eska014** [comment] 2019-01-23 16:14
I can't reproduce this. Please test if this is still valid in 3.1 (beta) and provide a reproduction project if so

**Comment by akien-mga** [comment] 2019-01-26 00:04
Closing for now, but if you can still reproduce it in the latest 3.1 beta, please comment and we can reopen it.

**Closed by akien-mga** 2019-01-26 00:04 UTC
Labels: bug, platform:html5, topic:porting
