### ISSUE TITLE
Opaque Pre-Pass Problem with GLES3

### ISSUE THREAD

**Issue by Saaamoth** [godotengine/godot#37233] opened 2020-03-22 18:17 UTC
**Godot version:** 3.2.1

**OS/device including version:** Windows 10 / AMD Radeon R9 380 (Driver 20.3.1)

**Issue description:**
When using GLES3, in the SpatialMaterial parameters, setting the Depth Draw Mode to "Opaque Pre-Pass" while using alpha scissors results in alpha transparency problems : 
- alpha cuts more than it should
- that alpha cut is stronger when moving the camera away from the object
- putting an object behind the alpha-cut surface sometimes helps, but not every time

_Note :_ GLES2 gives normal results in Godot 3.2.1. I launched the scene with Godot 3.1 and all is normal both in GLES2 & 3

_To illustrate that behaviour, left plane is "Opaque On" and right one is "Opaque Pre-Pass"_ 
![Bug01](https://user-images.githubusercontent.com/32795061/77256061-228aa200-6c6c-11ea-8137-9eef7c6c2697.PNG)

_Here with an opaque background object_
![Bug03](https://user-images.githubusercontent.com/32795061/77256138-92992800-6c6c-11ea-8e5c-f1444ebc62da.PNG)

**Steps to reproduce:**
- Get an albedo map with an alpha channel
- Create a SpatialMaterial, in the parameters, use "Opaque Pre-Pass" and "Use Alpha Scissors"

**Minimal reproduction project:** 

[GodotOpaquePrePassProblem.zip](https://github.com/godotengine/godot/files/4365820/GodotOpaquePrePassProblem.zip)

**Comment by clayjohn** [comment] 2020-03-22 18:22
Duplicate of https://github.com/godotengine/godot/issues/36669

Please search existing issues before opening a new one! But thanks for the detailed report. It is still appreciated. :)

**Closed by clayjohn** 2020-03-22 18:22 UTC

**Comment by Saaamoth** [comment] 2020-03-22 18:26
Oops, my bad !
