### ISSUE TITLE
Viewport [3D in 2D] enable "Transparent Background" disables 3D scene WorldEnviroment/Reflections/Metallic/Specular and leaving the Background turns WorldEnviroment upsidedown

### ISSUE THREAD

**Issue by rubenjavier** [godotengine/godot#11877] opened 2017-10-06 06:59 UTC
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Ubuntu 16.04 64 bits
Godot 3.0 commit d938de67fff288bf7f0a92fd51a2e890a1b5f245
IntelGPU

**Issue description:**
In a 2D scene, adding a Viewport to show a 3D scene and activating the Viewport "Transparent Bg" checkbox, disables the embeded 3D scene "WorldEnviroment" and this removes all the reflections/specular/metallic effects of the embedded scene, it doesnt matter if its its "Own World" or another created on the Viewport

**Steps to reproduce:**
Create a 2D Scene, reproducing the 3D in 2D godot demo and set it a as default scene
Create a 3D Scene with a MeshInstance (capsule, sphere) with a SpatialMaterial (I have used the textures from https://freepbr.com to create a metal)
Creata a Directional Light on the 3D Scene
Create a WorldEnviroment on the 3D scene
Create a Procedural Sky on the WorldEnviroment (the mesh will reflect the sky)
Go back to the main 2D Scene and enable "Transparent Bg" on the Viewport showing the 3D Scene, the world reflections will dissapear when you play the project
Disable the "Transparent Bg" on the Viewport, the world reflections will return but turned upsidedown

**Comment by rubenjavier** [comment] 2017-10-09 06:44
Added a Demo Project so you can check the bug.
.-Open the project
.-Compile, see the viewport showing the 3D scene with the WorldEnviroment upsidedown
.-Enable "Transparent Bg" on the Viewport
.-Compile, see the viewport showing the 3D scene without any WorldEnviroment

[3Din2D.zip](https://github.com/godotengine/godot/files/1367648/3Din2D.zip)

**Comment by rubenjavier** [comment] 2017-10-11 05:18
@Noshyaar 
Im attaching pictures of the bug showed in the demo for easier understanding

As you can see wih the "Transparent Bg" disabled, the WorldEnviroment shows upsidedown
and with the "Transparent Bg" enabled, there is no WorldEnviroment or reflections at all

![screenshot_20171011_071103](https://user-images.githubusercontent.com/15718876/31423261-ef6658c0-ae53-11e7-91a1-66cb4186c169.png)

![screenshot_20171011_071124](https://user-images.githubusercontent.com/15718876/31423263-f8348fc6-ae53-11e7-80a6-347d201d5688.png)

**Comment by rubenjavier** [comment] 2017-10-11 05:22
Maybe this is related? https://github.com/godotengine/godot/issues/10250
since all specularity is lost from the WorldEnviroment when the "Transparent Bg" option is enabled
...Thanks

**Comment by bojidar-bg** [comment] 2017-10-11 11:12
About the upside-down problem, you can check/uncheck the VFlip option on the Viewport.

**Comment by rubenjavier** [comment] 2017-10-11 13:01
@bojidar-bg 
Thanks, but the VFlip is not enabled, and after enabling it, the Viewport is still upsidedown, in other words, no matter the VFlip state, the Viewport is always upsidedown

**Comment by NathanWarden** [comment] 2017-10-12 04:30
I can confirm that vflip doesn't work.

VFlip Off
![vflip_off](https://user-images.githubusercontent.com/629422/31479341-20b5a13c-aedc-11e7-90fd-8076bcedb12c.jpg)

VFlip On:
![vflip_on](https://user-images.githubusercontent.com/629422/31479347-2dc4987e-aedc-11e7-82c1-a91624f9f6ed.jpg)

**Comment by hi-ogawa** [comment] 2017-10-12 05:34
Regarding viewport vflip option, it looks like this PR https://github.com/godotengine/godot/pull/11067 is fixing it.

**Comment by rubenjavier** [comment] 2017-10-12 07:08
@NathanWarden 
I see the  WorldEnviroment  is also upsidedown in your 3D with Viewports.
Can you check if "Transparent Bg" also makes the WorldEnviroment disappear (with the specularity / reflections) from the viewport?

**Comment by NathanWarden** [comment] 2017-10-12 14:08
It looks like vflip is working properly now :)

@rubenjavier Yes, it turns black and vflip is the opposite of what it is supposed to be. IE. when vflip is off it's upside down, but when it's turned on it's how it ought to be when it's off.

**Comment by kosz78** [comment] 2017-11-17 09:21
Confirm that `WorldEnvironment`  not work with `Transparent Bg` enabled in the latest master build

**Comment by akien-mga** [comment] 2018-01-06 23:44
Is this still reproducible in the current master branch?

**Comment by NathanWarden** [comment] 2018-01-09 15:44
@akien-mga I'll try and take a look and see if this is still a problem in an hour or two.

**Comment by NathanWarden** [comment] 2018-01-09 18:41
So, this issue is actually two bugs... one fixed, one not.

The first bug persists. When turning on "Transparent Bg" the objects go black.

![screenshot from 2018-01-09 13-35-16](https://user-images.githubusercontent.com/629422/34736778-0f5dca02-f542-11e7-8d17-8fe694ad12a8.png)

I think the second part is fixed. It now comes in upside down regardless of whether "Transparent Bg" is toggled or not. I personally think it being upside down is fine I think as long as it's consistent since vflip does turn it right-side up again.

![screenshot from 2018-01-09 13-35-01](https://user-images.githubusercontent.com/629422/34736789-183bd75e-f542-11e7-9395-3a14a20158eb.png)

Vflip works as expected, both are with vflip on:

![screenshot from 2018-01-09 13-31-36](https://user-images.githubusercontent.com/629422/34736858-5a8b4b44-f542-11e7-8977-f0547d315a66.png)
![screenshot from 2018-01-09 13-31-52](https://user-images.githubusercontent.com/629422/34736859-5aac5866-f542-11e7-9d4d-afd70ec1d89a.png)

I've seen this upside-downness in other engines so perhaps upside down is the default behavior when grabbing the render buffer? But, if being upside down is the default behavior for a viewport node then perhaps vflip should be defaulted to on?

**Comment by AndreaCatania** [comment] 2018-01-12 12:01
@NathanWarden I've just tested it and it works fine now, probably you forgot to add directional light. Can you please check it?

![untitled](https://user-images.githubusercontent.com/8342599/34874269-acb62eb8-f798-11e7-83b4-29bff9ea7e33.png)

**Comment by NathanWarden** [comment] 2018-01-12 17:03
Adding a light does add lighting, but the environment lighting doesn't apply at all. Shouldn't "Transparent Bg" just "cut out" the background? Instead it's not allowing the environment lighting/shading to apply. I'd still consider this a bug.

I'm not a rendering expert, but it seems possible to have environment lighting/shading apply to objects, but not render the environment itself as the background, right?

![screenshot from 2018-01-12 11-59-08](https://user-images.githubusercontent.com/629422/34886239-6cd01ba4-f790-11e7-98a5-10e3c1bb93ea.png)

**Comment by rubenjavier** [comment] 2018-01-12 18:01
@NathanWarden and @AndreaCatania , exactly, the lightning behaviour hasn't changed and I still consider this a bug, the environment lightning/shading its lost while directional light is not.
I understand that the new engine uses the environment to calculate part of the light wich is great and looks awesome, but not rendering it visible on the viewport shouldnt necessarily affect the calculation since it could still be rendered in a buffer, or am I mistaken?

**Comment by akien-mga** [comment] 2018-01-15 19:27
After discussing with @reduz, we're moving this issue to 3.1 so as not to take unnecessary risks to introduce regressions fixing it.

**Comment by kane-thornwyrd** [comment] 2019-06-17 08:24
I'm sad to let you know that there is a regression concerning this in the 3.1.1 and on master.
All the shader effects like: reflections, blur, DoF, bloom, etc. does not work in a viewport with the Transparent bg option turned On.

**Comment by bojidar-bg** [comment] 2019-06-17 11:58
Can confirm the same on v3.2.dev.custom_build. 7e108da07. Reopening..

**Comment by clayjohn** [comment] 2019-06-17 15:30
It appears intentional that the post-process settings do not apply when a transparent background is used. 

https://github.com/godotengine/godot/blob/813c0d84740b1d1c8ccece3540e945d1e821561d/drivers/gles3/rasterizer_scene_gles3.cpp#L3671-L3672

**Comment by Zireael07** [comment] 2019-06-17 15:33
@clayjohn: In that case, it would be worth putting a warning in editor for that case (I was fooling around with layering two viewports yesterday and was about to post an issue...)

**Comment by clayjohn** [comment] 2019-06-17 15:39
@Zireael07 Just because it appears intentional, doesn't mean we can't make it work! I'm not certain that it is impossible to get post-process settings to work with a transparent background. So I think we should attempt to improve this behaviour before putting in a warning/documentation

Also, I think this should be in its own issue. Post-processing settings are not related to displaying environment reflections. This is not a regression from the above issue, it is an issue in itself.

**Comment by clayjohn** [comment] 2019-06-17 15:40
@Zireael07 Just because it appears intentional, doesn't mean we can't make it work! I'm not certain that it is impossible to get post-process settings to work with a transparent background. So I think we should attempt to improve this behaviour before putting in a warning/documentation

Also, I think this should be in its own issue. Post-processing settings are not related to displaying environment reflections. This is not a regression from the above issue, it is an issue in itself.

**Comment by akien-mga** [comment] 2019-11-26 12:51
I just read through this issue and I think different bugs have been mentioned, some of which are fixed. The test project in OP works fine in the current master branch, you can enable `v_flip` on the Sprite to get the Viewport upright, and "Transparent Bg" seems functional:
![Screenshot_20191126_135056](https://user-images.githubusercontent.com/4701338/69635024-c748fa00-1053-11ea-85b0-3962e3cb4a11.png)

So I'll close this. If there are some issues discussed here which are still not fixed, I would suggest opening new bug reports against the master branch with their own reproduction projects.

**Closed by akien-mga** 2019-11-26 12:51 UTC
Labels: bug, topic:rendering
