### ISSUE TITLE
GDScript 2.0 calling overridden function does not work

### ISSUE THREAD

**Issue by firebelley** [godotengine/godot#69765] opened 2022-12-08 15:31 UTC
### Godot version

4.0.beta7.mono

### System information

Windows 11

### Issue description

If I extend a class in GDScript 2.0 and then override one of its functions, calling the overridden function calls the function of the base class rather than the function in the inheriting class. See the minimal reproduction project for an example.

Here is a brief overview:
```
# random_timer.gd
extends Timer
class_name RandomTimer

# ... some configuration here of minimum and maximum time

# overriding the "start" function
func start(time_sec: float = -1.0):
	if (time_sec > 0):
		super.start(time_sec)
	else:
		super.start(rng.randf_range(min_wait_time, max_wait_time))
```

And then from another script, I am calling it like this:

```
# main.gd
extends Node

@onready var random_timer: RandomTimer = $RandomTimer

func _ready():
	random_timer.connect("timeout", on_timer_timeout)
	start_timer()


func start_timer():
	# calling start here doesn't work, the RandomTimer's start function is not called.
        # the Timer's start function is called instead
	random_timer.start()
	
	# calling the start function like this, however, does properly call the overridden function
	# random_timer.call("start")
	
	print("Set wait time to %s" % random_timer.wait_time)


func on_timer_timeout():
	start_timer()
```

Instead, I would expect that calling `start` would properly call the overridden function.

I think this is slightly different from the discussions in #55024 and #53606 because I am explicitly getting a reference to my custom `RandomTimer` script and then calling `start`. I would expect that calling `start` would call the function defined in my `RandomTimer` script (since that's what I am referencing) and not bypass it entirely.

If this is indeed a duplicate issue, then I think I would really like to see some form of function overriding be made usable. The example I provided here is from a plugin that gives users a `RandomTimer` node whose goal is to have the same API as the built-in `Timer` node such that the `RandomTimer` can be used in exactly the same way albeit with different underlying behavior. Being unable to override functions prevents me from being able to provide that experience.

### Steps to reproduce

1. Download the MRP
2. Observe that `wait_time` is always printed in the output as `1` when called like so: `random_timer.start()`
3. Observe that `wait_time` is printed properly randomized in the output when called like so: `random_timer.call("start")`

### Minimal reproduction project

[Function Override MRP.zip](https://github.com/godotengine/godot/files/10186508/Function.Override.MRP.zip)

**Comment by KoBeWi** [comment] 2022-12-08 15:41
Duplicate of #55024

**Closed by KoBeWi** 2022-12-08 15:41 UTC

**Comment by firebelley** [comment] 2022-12-08 15:46
@KoBeWi  is it the case that no function that shares a name with a built in GDScript type can be shadowed/overridden? It doesn't seem to make sense that I can define a function called "start" but cannot call it.

**Comment by KoBeWi** [comment] 2022-12-08 15:53
The fact that it's allowed is a bug. Doing it should result in an error.
