### ISSUE TITLE
always_on_top hides the popup menu

### ISSUE THREAD

**Issue by Juna-Idler** [godotengine/godot#75044] opened 2023-03-17 22:00 UTC
### Godot version

4.0.1.rc1

### System information

Windows10

### Issue description

```
	get_window().always_on_top = true
	get_viewport().gui_embed_subwindows = false

	$PopupMenu.popup(Rect2(pos,Vector2.ZERO))
```

![image](https://user-images.githubusercontent.com/78989193/226058945-a578ab11-e7a2-41c1-9dad-70294bc2c788.png)
it's transparent window. I can't click the overlapping menu.

When I set always_on_top in the popup menu, it worked in a limited way, but I got scolded.
https://github.com/godotengine/godot/issues/75001

### Steps to reproduce

see https://github.com/godotengine/godot/issues/75001

### Minimal reproduction project

see https://github.com/godotengine/godot/issues/75001

**Comment by KoBeWi** [comment] 2023-03-19 23:53
Duplicate of #62382

**Closed by KoBeWi** 2023-03-19 23:53 UTC
