### ISSUE TITLE
HTML5, Chrome: joypad button events on scene start

### ISSUE THREAD

**Issue by AlexeyGrishin** [godotengine/godot#24988] opened 2019-01-14 18:39 UTC
**Godot version:**
3.0.6

**OS/device including version:**
macOS Sierra 10.12.6 

**Issue description:**
When I export my project in HTML5 and then open in Chrome, it looks like some input events appear on start. I do not see same behavior in Firefox. It is also not broken for empty project, so I suspect here is some set of input bindings that causes that behavior.

I got copy of my project and just removed anything from scene, so the only thing it differs from empty project is project settings (input bindings, etc)

**Steps to reproduce:**
1. Download attached zip archive
2. Run http-server for `build` folder 
3. Open in Chrome
4. You'll see several 'joypad button pressed' messages in console and 'Someone pressed up' which means that game received 'ui_up' action event even you just opened a game.

Also you may try to open project in Godot and export it to HTML - I expect it will the same result.

**Minimal reproduction project:**
[godot_bug_reproduce.zip](https://github.com/godotengine/godot/files/2756591/godot_bug_reproduce.zip)

**Comment by eska014** [comment] 2019-01-15 01:05
Duplicate of #16262, fix will be included in upcoming releases

**Closed by eska014** 2019-01-15 01:05 UTC

**Comment by triptych** [comment] 2019-01-18 17:12
@AlexeyGrishin Can you try out 3.1 beta and see if that issue is still there?
