### ISSUE TITLE
Mobile exports crash iOS when enabling post processing effects in quality settings.

### ISSUE THREAD

**Issue by KableChannel** [godotengine/godot#17397] opened 2018-03-10 04:09 UTC
**Godot version:**
3.0.2 (stable)

**OS/device including version:**
iPhone SE w. iOS 11.0.2

**Issue description:**
When exporting for mobile, the resulting app crashes on load due to a graphics issue.

**Steps to reproduce:**
With any project utilizing environment effects like contrast and bloom, under the quality settings, choose "3D" instead of "3D Without Effects" under the Framebuffer Allocation setting. Export to iOS and run on the test device. This is problematic because unless this is fixed, no built-in effects will run on mobile.

**Minimal reproduction project:**
[TestProject.zip](https://github.com/godotengine/godot/files/1799086/TestProject.zip)

**Comment by reduz** [comment] 2018-09-06 22:09
This will be modified in 3.2, so it will likely be solved there

**Comment by akien-mga** [comment] 2019-12-13 23:58
Is this still reproducible in the latest 3.2 builds?

**Comment by KoBeWi** [comment] 2020-11-07 13:36
Closing due to lack of update. Please comment if you can still reproduce this issue in the latest stable version of Godot.

**Closed by KoBeWi** 2020-11-07 13:36 UTC
Labels: bug, platform:ios, topic:porting
