### ISSUE TITLE
.csproj and .sln files are duplicated when the project is renamed

### ISSUE THREAD

**Issue by paulloz** [godotengine/godot#15624] opened 2018-01-12 14:08 UTC
**Godot version:** `master` / a26e6c8

**OS/device including version:** *Linux Mint 18.2*

**Issue description:**

After renaming my project, I have a `.csproj` and a `.sln` file for both the old and new project name. This is not a big issue in essence but it's trashing the project folder and confusing for the user.  
In addition, manual changes to the original `.csproj` file (e.g. a reference to an external `.dll`) are not applied to the newly created one.  

There are other issues open concerning `.csproj` files being out of sync: #12917 #12415

**Steps to reproduce:**
* Create a project
* Rename this project from the project list screen

**Comment by aaronfranke** [comment] 2020-10-06 17:52
@paulloz Please re-test with Godot 3.2.3 and/or the master branch. Both of these use the new C# project format, so issues related to the `csproj` file might just not exist anymore. Also, check if you have the latest Mono and .NET Core.

**Comment by paulloz** [comment] 2020-10-14 16:43
Hi there!
I just tried the same thing with 3.2.3, here's what is happening now.

- Create a project and call it A.
- Add some C#, build and run.
    - `A.sln` and `A.csproj` are created, everything runs fine.
- Go back to the project list screen, rename A into B and open the project.
- Run.
    - `A.sln` and `A.csproj` are still here (which is good imho, I'd rather have the user delete them manually), but no `B.sln` nor `B.csproj`.
    - The game errors out `ERROR: Cannot instance script because the project assembly is not loaded.`
- If I rename the files manually and update everything accordingly (in `B.sln` and `B.csproj`), everything runs fine once again.

**Comment by akien-mga** [comment] 2021-04-28 13:29
Duplicate of #27030 I think (at least with the current status).

**Closed by akien-mga** 2021-04-28 13:29 UTC
Labels: enhancement, topic:mono, usability
