### ISSUE TITLE
Godot C#/mono performance monitor OBJECT_COUNTER goes up when using _Input

### ISSUE THREAD

**Issue by EduardoLemos567** [godotengine/godot#49211] opened 2021-05-30 21:23 UTC
**Godot version:**
3.3.2.stable.mono

**OS/device including version:**
Windows 7
backend: GLES3
GPU: Geforce GTX 1660 ti
Nvidia Driver: 466.27

**Issue description:**
When using any C# script which overrides the _Input function, every event causes the performance monitor object counter to go up. 

**Steps to reproduce:**
- Create any project in godot with C#.
- Add a C# script (on a Spatial) and override the _Input method (can be empty).
- Run.
- Check Debuggers->Monitors->Object->Objects counter, it goes up.

**Expected:**
Counter goes up and down as objects are freed (checked on GDscript, it doesnt even change the counter).

**Detail:**
Memory usage on Task Manager stays the same (goes up and down in small increments like 10kb).

**Comment by Calinou** [comment] 2021-05-30 22:00
Duplicate of https://github.com/godotengine/godot/issues/41643.

**Closed by Calinou** 2021-05-30 22:00 UTC
