### ISSUE TITLE
Godot 3.2 alpha 2: Building of Android project failed, check output for the error.

### ISSUE THREAD

**Issue by Brayacon** [godotengine/godot#33891] opened 2019-11-25 16:17 UTC
Godot : 3.2 alpha 2

OS/device including version: Windows 7 / Accer Aspire 5251-1513 running on AMD processor

Issue description: Building of Android project failed, check output for the error.
Alternatively visit docs.godotengine.org for Android build documentation.

Steps to reproduce: when i pressed the android Icon for fast deploy, it installed the latest gradle (5.1.1) . the it brought the error : error occurred during initialization of VM,
could not reserve enough heap size.

**Minimal reproduction project:**

**Comment by Teashrock** [comment] 2019-11-25 16:51
> 3.2 alpha 2

But it's 3.2 beta 2 already.

**Comment by Brayacon** [comment] 2019-11-25 17:52
> > 3.2 alpha 2
> 
> But it's 3.2 beta 2 already.
what ?????
does it fix the problem

**Comment by aaronfranke** [comment] 2019-11-26 04:54
> error occurred during initialization of VM, could not reserve enough heap size.

> Acer Aspire 5251-1513, 2GB DDR3 Memory

Your computer is too old and under-powered, it does not have enough RAM. You either need to get a new computer, or upgrade the RAM, and/or use a lighter-weight operating system.

**Comment by name-here** [comment] 2019-11-26 18:49
It looks like it's pretty easy (and probably cheap) to [upgrade](https://www.ifixit.com/Guide/Acer+Aspire+5251-1513+RAM+Replacement/120406) the [memory](https://www.amazon.com/4AllDeals-Upgrade-5251-1513-DDR3-1066MHz-204-pin/dp/B008O52Y48), though, with the right screwdriver.  (the link to memory is just an example; there are probably other options for lower prices)

**Comment by KoBeWi** [comment] 2020-11-16 22:06
Can anyone still reproduce this bug in Godot 3.2.3 or any later release?

If yes, please ensure that an up-to-date Minimal Reproduction Project (MRP) is included in this report (a MRP is a zipped Godot project with the minimal elements necessary to reliably trigger the bug). You can upload ZIP files in an issue comment with a drag and drop.

**Comment by aaronfranke** [comment] 2020-11-16 22:48
Closing, this failure is to be expected, since OP's computer simply does not have enough RAM.

**Closed by aaronfranke** 2020-11-16 22:48 UTC
Labels: bug, platform:android, topic:buildsystem
