### ISSUE TITLE
Textures uses linear filtering in previews, regardless of node or default settings

### ISSUE THREAD

**Issue by markdibarry** [godotengine/godot#67316] opened 2022-10-12 16:32 UTC
### Godot version

4.0.dev (042e81f663)

### System information

Windows 10

### Issue description

Seems like this should be open because it's been around forever, but I can't find an open ticket associated with this. Feel free to close if otherwise.

When using a texture, while the node renders correctly, the preview uses linear filtering, even when used for a node with filtering set to `nearest` and `nearest` set as the project default import setting.

![image](https://user-images.githubusercontent.com/21325943/195398212-e98c0eae-858b-4e1c-97ec-70b0ed0c09a3.png)

### Steps to reproduce

Use a small pixel image as a texture.

**Comment by akien-mga** [comment] 2022-10-12 16:34
Duplicate of #60150

**Closed by akien-mga** 2022-10-12 16:34 UTC
