### ISSUE TITLE
Blend files failing to import Godot 4.1 with Blender package from Arch Linux

### ISSUE THREAD

**Issue by ZachAR3** [godotengine/godot#79881] opened 2023-07-25 11:57 UTC
### Godot version

4.1.1.stable.mono

### System information

Arch Linux Zen Kernel 6.3 Ryzen 5900x Nvidia RTX 2080TI 11GB (proprietary drivers)

### Issue description

I recently deleted (well moved I have the old one for testing) due to getting some errors stating that files are missing meta data and need to be re-imported. After doing this the engine fails to import any blend files giving instead the following error for each object:
```
 Error importing 'res://Resources/Blender/Objects/LootCrate.blend'.
  modules/gltf/gltf_document.cpp:7432 - Condition "err != OK" is true. Returning: ERR_FILE_CANT_OPEN
```
The project is too large to give here but I linked one of the blend files and the old (working) and new broken .Godot folder the errors occur even in new projects. 

### Steps to reproduce

Import any blend file into Godot 4.1

### Minimal reproduction project

(It's too big for Github >.<)
https://drive.google.com/file/d/1lEsk3VbJnL-c3yASSHBkTZ_b05oGGg6J/view?usp=sharing

**Comment by fire** [comment] 2023-07-26 00:31
What blender version are you using?

**Comment by ZachAR3** [comment] 2023-07-26 07:22
> What blender version are you using?

Latest stable which at time of writing is 3.6

**Comment by ZachAR3** [comment] 2023-07-26 13:57
I just tried on Godot 4.0.3 and still had the same issue, so it doesn't appear to be a regression so much as something being broken with connection between Blender and Godot.

**Comment by fire** [comment] 2023-07-26 17:11
I'm not able to investigate quickly, but the last thing I remembered is godot engine uses json rpc to communicate with blender

**Comment by ZachAR3** [comment] 2023-07-26 21:22
> I'm not able to investigate quickly, but the last thing I remembered is godot engine uses json rpc to communicate with blender

Ok, I'm really unsure of the issue because I did a fresh install of arch for other reasons and even deleted godots user app data and made a new project + new blender install and completely new blend file and still have the issue. I will try deleting the all of the .local/share/godot tomorrow, maybe something in that broke.

**Comment by ZachAR3** [comment] 2023-07-27 12:28
> I have the same issue on Arch too using the Pacman managed blender version (3.6.0). Manually using 3.5.1 or 3.6.1 fixed the issue. So we just need to wait for an update and use a downloaded 3.6.1 as workaround.

That fixed it for me as well, so it seems to be an Arch X Godot incompatibility or specifically Godot x Blender 3.6 (not 3.6.1) since it worked with manually downloaded 3.6.1. I will leave the issue up until an actual fix is implemented, but I appreciate the advice on the work-around.

**Comment by xbelanch** [comment] 2023-08-27 15:56
FYI just updated to Blender 3.6.2 and still raises this issue and then failing to import the .blend file

**Comment by ZachAR3** [comment] 2023-08-27 18:43
> FYI just updated to Blender 3.6.2 and still raises this issue and then failing to import the .blend file

*Sigh* ofc haha. I love Godot but some of these bugs are engine breaking, I would be far happier to see a few months of no new major features for the core dev team to focus on bug fixes.

**Comment by Calinou** [comment] 2023-08-27 19:50
> I would be far happier to see a few months of no new major features for the core dev team to focus on bug fixes.

In open source, people work on what they want to work on :slightly_smiling_face: 

We can't expect everyone to stop what they're doing to dedicate to bug fixes, as we don't decide what they should work on. That's what happens when the majority of contributors are volunteers.

Either way, this issue is likely due to Arch Linux packaging. Blender developers themselves recommend only using the blender.org package, nothing else.

**Comment by akien-mga** [comment] 2023-08-28 07:28
Please report the bug to Arch Linux maintainers if the official Blender binary works but their packaged version doesn't. That's a packaging bug.

**Comment by akien-mga** [comment] 2023-08-28 13:27
Duplicate of #76338.

**Closed by akien-mga** 2023-08-28 13:27 UTC
Labels: bug, topic:thirdparty, needs testing, topic:import
