### ISSUE TITLE
Minimal and maximal window size in project settings

### ISSUE THREAD

**Issue by BaseCrusher** [godotengine/godot#31303] opened 2019-08-11 20:17 UTC
**Godot version:** 3.1.1

**Issue description:**
Hey guys,
so I was wondering why there isn't an option for the minimal and the maximal window size in the  project settings.

I mean it's possible to solve this with a gdscript but I believe it would be a nice feature.

Regards
BaseCrusher

**Comment by Calinou** [comment] 2019-08-11 21:19
The [ability to set a minimum/maximum window size](https://github.com/godotengine/godot/pull/29752) was merged in the `master` branch in June, which means it isn't available in 3.1.1. It will be available in 3.2 though :slightly_smiling_face:

**Comment by BaseCrusher** [comment] 2019-08-12 04:46
Oh good to know.
Thx for the reply. :)

**Comment by akien-mga** [comment] 2019-08-12 07:37
For the reference, duplicate of ##14806.

**Comment by Calinou** [comment] 2019-08-12 13:35
@akien-mga This issue is still valid, as there's no way to define project settings to set a minimum/maximum window size specific to a project.

**Comment by Jummit** [comment] 2020-07-02 12:04
This should be reopened as #31367 was reverted in #31435.

**Comment by follower** [comment] 2020-07-26 18:56
Seems like the most recent related PR is: https://github.com/godotengine/godot/pull/31990

**Comment by DarkTimeStudio** [comment] 2023-07-08 12:37
Yep, I also feel like this would be a cool feature for someone who's developing software and not games. Considering that it's not much of a big deal when it comes to the project settings, and it could even be added to the "advanced" project settings, I see no reason not to add this feature.

**Comment by Calinou** [comment] 2023-08-30 20:48
Closing in favor of https://github.com/godotengine/godot-proposals/issues/7586, as feature proposals are now tracked in the Godot proposals repository.

**Closed by Calinou** 2023-08-30 20:48 UTC
Labels: feature proposal, topic:core
