### ISSUE TITLE
Collision is not visible in Debug mode for tilemaps

### ISSUE THREAD

**Issue by rennomarcus** [godotengine/godot#49232] opened 2021-05-31 23:58 UTC
**Godot version:**
Not working in 3.3.2
It was working in 3.2.2

**OS/device including version:**
Windows 10

**Issue description:**

Previously (Godot 3.2.2) when toggling the option `Debug -> Visible Collision Shape` it was possible to see the tiles that had collision applied to them. Now when running my game with the same option with Godot 3.3.2 I can only see the collisions in the CollisionShape2D nodes. I'm not sure if this is expected, but I couldn't see in the changelog. 

**Steps to reproduce:**
- Create a TileMap
- Create a TileSet 
- Apply collision to a "single tile" or a tile in an "atlas"
- Turn the option "Visible Collision Shape" on in the Debug menu
- You should see the collision area in your game

**Minimal reproduction project:**

N/A

**Comment by boruok** [comment] 2021-06-01 10:15
make sure that you enabled collision visibility in tilemap node properties. i'm confused about hour before find little checkbox in tilemap.

**Comment by dalexeev** [comment] 2021-06-01 10:15
See #47382.

**Comment by akien-mga** [comment] 2021-06-01 10:50
Duplicate of #48631.

**Closed by akien-mga** 2021-06-01 10:50 UTC
