### ISSUE TITLE
Calling print() on an array containing itself crashes a project without error messages.

### ISSUE THREAD

**Issue by Null-Ping** [godotengine/godot#80988] opened 2023-08-25 10:24 UTC
### Godot version

v4.2.dev3.official.013e8e3af

### System information

Windows 10.0.19045 - GLES3 (Compatibility)

### Issue description

Possibly a duplicate of https://github.com/godotengine/godot/issues/1289, but I can't reopen that one.

Running the following code instantly crashes a project in version 4.2.dev3, and does not leave any error messages in editor, cosole or logs:
```gdscript
var test = []
test.append(test)
print(test)
```

### Steps to reproduce

Run the code:
```gdscript
var test = []
test.append(test)
print(test)
```

### Minimal reproduction project

```gdscript
var test = []
test.append(test)
print(test)
```

**Comment by dalexeev** [comment] 2023-08-25 12:16
* Duplicate of #55256.
* Fixed by #79370.
* Will be included in 4.2 dev 4, not yet cherry-picked for stable branches.

Thanks for reporting the bug nonetheless!

**Closed by dalexeev** 2023-08-25 12:16 UTC
