### ISSUE TITLE
Shortcut (i.e. CTRL+D) in the scene tree is ignored when the script window is open

### ISSUE THREAD

**Issue by ivanskodje** [godotengine/godot#41366] opened 2020-08-19 07:55 UTC
**Godot version:**
v3.2.2.stable.official (on steam)

**OS/device including version:**
Windows 10 
(Version	10.0.19041 Build 19041)

**Issue description:**
When the script window is open, regardless if I click on a node in the scene tree, or click outside of the script to "unselect" the script window, shortcuts such as CTRL+D are ignored, and interpreted as duplicate line in the script window.

![image](https://user-images.githubusercontent.com/6776092/90607559-ad62cf00-e201-11ea-84ce-b0b9c7f410ac.png)

**Steps to reproduce:**
1. Create new project
2. Create node
3. Create new script to node
4. Select something in the script (not sure if needed or not)
5. Click on a node in the scene tree
6. Press CTRL+D in order to duplicate the node in the scene tree, notice that instead a line is duplicated in the script window

**Comment by Calinou** [comment] 2020-08-19 08:25
Duplicate of https://github.com/godotengine/godot/issues/36205.

**Closed by Calinou** 2020-08-19 08:25 UTC
