### ISSUE TITLE
Plugin custom type icon not scaled in Inspector tab

### ISSUE THREAD

**Issue by dzil123** [godotengine/godot#68613] opened 2022-11-13 15:23 UTC
### Godot version

v4.0.beta4.official and v3.5.1.stable

### System information

Arch Linux

### Issue description

A custom icon of a custom type created in a plugin with `add_custom_type` is not scaled in the Create Node dialog, scene dock, and inspector.

This is the demo project with custom types using icon.png, icon.svg, and icon.svg with "Scale With Editor Scale" enabled.

![Create Node dialog](https://user-images.githubusercontent.com/5725958/201529273-ca1e76f8-01e4-4ca4-9ca0-a28d0b606f94.png)

![Scene dock](https://user-images.githubusercontent.com/5725958/201529329-b42c13f4-42f8-4a3b-97bc-e6b15614089c.png)

![Inspector](https://user-images.githubusercontent.com/5725958/201529337-a8218bb9-c609-4e78-8487-4e7da433d835.png)

In addition, when the editor display scale is set to 200%, the svg with "Scale With Editor Scale" enabled is scaled incorrectly.

![scene_2](https://user-images.githubusercontent.com/5725958/201529522-284ce77b-29bf-4098-b9d3-222d0519a07e.png)

### Steps to reproduce

1. Follow [the tutorial](https://docs.godotengine.org/en/stable/tutorials/plugins/editor/making_plugins.html#a-custom-node) to make a plugin that creates a custom type with an icon, by passing the icon to `add_custom_type`.
2. Enable the plugin and reload the editor.
3. Observe the custom type icon is too large in the Create Node dialog, scene dock, and inspector.

### Minimal reproduction project

[demo.zip](https://github.com/godotengine/godot/files/9997517/demo.zip)

**Comment by kleonc** [comment] 2022-11-14 03:04
Duplicate of #57286.

**Closed by kleonc** 2022-11-14 03:04 UTC
