### ISSUE TITLE
Tabbing Between Editor Fields Can Unintentionally Select Multiple Fields

### ISSUE THREAD

**Issue by RocketPunches** [godotengine/godot#67538] opened 2022-10-17 14:23 UTC
### Godot version

4.0.beta2.official

### System information

Windows 11

### Issue description

Tabbing between editor fields can cause multiple fields to be selected accidentally, and in some circumstances capture the mouse and require Alt+Tabbing away from Godot to regain control.

![image](https://user-images.githubusercontent.com/32081610/196201070-e1cc989d-96f6-4762-abc0-788512e95c90.png)

It seems this happened most often when quickly tabbing after clicking into a field, though it does occasionally happen regardless of how long it's been since the field was clicked into. This seems to only happen when the mouse is left over the field, and on at least one occasion Godot capture my mouse as I purposefully held the left mouse button down and tabbed - although I was unable to reliably reproduce that after multiple attempts.

### Steps to reproduce

Should be reproduceable in any project.

**Comment by KoBeWi** [comment] 2022-10-17 14:52
Duplicate of #37723

**Closed by KoBeWi** 2022-10-17 14:52 UTC
