### ISSUE TITLE
Syntax Error Pointing to Wrong Line in If/Elif block

### ISSUE THREAD

**Issue by jontopielski** [godotengine/godot#37497] opened 2020-04-01 15:01 UTC
**Godot version:**
3.2.stable.official
**OS/device including version:**
Mac OS
**Issue description:**
Godot will point syntax error to the first line in an if/else block even if the error is contained in the elif section (not the if)

**Steps to reproduce:**
Ex:
```
1. var my_obj = {}
2.   if true == false:
3.     pass
4.   elif my_obj == "invalid_type_comparison":
6.     pass
```

In this case, Godot will point to line 2. and say Invalid Operands 'Dictionary' and 'String' in operator '==' even though that error is happening on line 4.

**Minimal reproduction project:**
Just 1 script file should be enough to reproduce.

**Comment by Calinou** [comment] 2020-04-01 16:35
Duplicate of #37197.

**Closed by Calinou** 2020-04-01 16:35 UTC
