### ISSUE TITLE
Second parameter of print is highlighted in green

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#33408] opened 2019-11-06 22:55 UTC
Godot 3.2 beta1

When I write this:

```gdscript
extends Node

func _ready():
	var word = 42
	word += 42
	print("-> ", word, word)
```

The first occurrence of `word` in `print` is highlighted green for seemingly no reason.

![image](https://user-images.githubusercontent.com/1311555/68345086-7004d900-00e8-11ea-8bf4-083671ba8296.png)

Same with `printerr` and `print_debug`.

**Comment by Calinou** [comment] 2019-11-06 23:02
This is due to the `->` which represents a function return type.

**Comment by KoBeWi** [comment] 2019-11-06 23:22
Duplicate of #33298 btw

**Closed by KoBeWi** 2019-11-06 23:22 UTC
Labels: bug, topic:editor, topic:gdscript
