### ISSUE TITLE
Cannot assign Nodes on @export: Array[NodeType]

### ISSUE THREAD

**Issue by JamesMWestbrook** [godotengine/godot#74137] opened 2023-03-01 01:21 UTC
### Godot version

4.0.rc3.official

### System information

Windows 11

### Issue description

When using @export and having it to go :Array[TYPE] it will show correctly in the editor with whatever type you set(in my example I tested with CheckBox and TextureRect) but when you click Assign and click the node, nothing happens. No errors come up.
Able to reproduce in a smaller project.

### Steps to reproduce

```
extends Control
@export  var buttons: Array[CheckBox]
@export var pictures: Array[TextureRect]
```
Have an @export line with an array of a Node.
Add at least 1 item to the array in editor.
Try to assign it to a node, or drag and drop.
Nothing happens. 

### Minimal reproduction project

[TestToZip.zip](https://github.com/godotengine/godot/files/10856105/TestToZip.zip)

**Comment by Calinou** [comment] 2023-03-01 01:25
Duplicate of https://github.com/godotengine/godot/issues/62916.

**Closed by Calinou** 2023-03-01 01:25 UTC
