### ISSUE TITLE
[3.0x] Shader error sin(vec4) and other Trig functions

### ISSUE THREAD

**Issue by RaXaR** [godotengine/godot#13258] opened 2017-11-24 23:31 UTC
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Win7, nVidia GTX 680

**Issue description:**
I tried to use the following shader code:
```
...
vec4 t = sin(vec4(1.0, 1.0, 1.0, 1.0));
...
````
but the thing complained about only allowing floats to be passed to sin().
On the [OpenGL ES 3.0 reference page](https://www.khronos.org/registry/OpenGL-Refpages/es3.0/) it says that it is okay to use vec2, vec3 and vec4 (genTypes).
In my local copy of the source I added:
```
// /servers/visual/shader_language.cpp:1355
{ "sin", TYPE_VEC4, { TYPE_VEC4, TYPE_VOID } },
```
The above shader code then worked fine.

Finally, is there a reason why it's omitted? If not, should I update the file and do a pull request?

**Steps to reproduce:**
Copy the first code above into a shader.

**Comment by RaXaR** [comment] 2017-11-24 23:32
Similar issue here #10562

**Comment by vnen** [comment] 2017-11-25 18:38
I think it's okay to have overloads for vector parameters, feel free to open a PR. In any case, I'll close as a duplicate of #10562 since there's no real distinction between the requests.

**Closed by vnen** 2017-11-25 18:38 UTC
