### ISSUE TITLE
How to export things not as .import files?

### ISSUE THREAD

**Issue by tempdoom** [godotengine/godot#25691] opened 2019-02-08 00:30 UTC
3.0.6 official
Windows 10

*.ogg files and *.json files work great in the editor, but are exported only as *.import files. I've already tried including those file types in the "files to export" section, even trying the full path inside the godot folder to get to them. I've ticked "export all resouces in the project". I've looked at some of the other threads on stuff like this but they don't seem to handle the situation I have well. Basically I have a script which loads a bunch of ogg files to be used as sound effects and music. They're added to a list that is editable and sortable in game. Additionally, they must be loaded at the start of the game and _not_ hardcoded because the contents of the "tracks" folder must be able to be changed down the road. The JSON loading script is essentially the same thing, except it loads JSON files. If I can get one to export properly, the other should as well.  Thanks in advance to anyone willing to help!

`
const dirpath = "res://tracks/"
const extension = ".ogg"
var tracklist = []

func _ready():
	_loadtracks()

func _loadtracks():
	var dir = Directory.new()
	if dir.open(dirpath) == OK:
		dir.list_dir_begin()
		var file = dir.get_next()
		while (file != ""):
			if file.ends_with(extension):
				tracklist.append(file)
			file = dir.get_next()`

**Comment by bruvzg** [comment] 2019-02-08 07:43
Relates issue #25672 (with some workarounds in the comments)

**Comment by LinuxUserGD** [comment] 2019-02-09 08:37
See my comment in the related issue.

**Comment by clayjohn** [comment] 2019-04-21 19:18
Closing as duplicate of #25672

**Closed by clayjohn** 2019-04-21 19:18 UTC
