### ISSUE TITLE
Some times the Project Manager window will apear instead of the game developed when pressing F5 or using the Play button

### ISSUE THREAD

**Issue by shackra** [godotengine/godot#14312] opened 2017-12-06 07:37 UTC
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**

Windows 10
v3.0.beta.build1

**Issue description:**

Sometimes, after pressing the play button or <kbd>F5</kbd> Godot will launch the project manager. Instead I want to see my game being develop.

**Steps to reproduce:**
start a new project and do something, then try to play it from the editor with F5.

**Link to minimal example project:**

TODO, will link my project's source code in a couple of minutes.

**Comment by Zireael07** [comment] 2017-12-06 07:39
Duplicate of #11391 which was already fixed in master.

**Closed** 2017-12-06 07:54 UTC
