### ISSUE TITLE
Ogg Vorbis stream not signalling finished

### ISSUE THREAD

**Issue by imekon** [godotengine/godot#15895] opened 2018-01-20 16:09 UTC
Godot V3.0 RC1

Windows 10

Ogg Vorbis audio stream not signalling finished.

**Steps to reproduce:**
Add an audio stream, assign finished to a function. Play a sound, finished never gets call, the original sound starts playing again

Since this was a converted project from 2.1.4, I reassigned the "finished" signal, however it never gets called, even with a breakpoint set.

**Minimal reproduction project:**

[oggstreamrc1.zip](https://github.com/godotengine/godot/files/1648965/oggstreamrc1.zip)

**Comment by reduz** [comment] 2018-01-20 16:17
did you try disabling loop?

**Comment by Sslaxx** [comment] 2018-01-20 16:47
To be more specific: .ogg files in Godot 3 are automatically assigned to loop. .wav files are not. You have to select the .ogg file in the FileSystem dock, and from the Import dock uncheck the Loop box then click re-import.

**Comment by imekon** [comment] 2018-01-20 16:49
Where's loop? I don't see it on AudioStreamPlayer

**Comment by Sslaxx** [comment] 2018-01-20 16:51
You won't.

Here's a couple of pics to show a bit about what I said:
![a](https://user-images.githubusercontent.com/324679/35185836-22c9e012-fe02-11e7-890c-27c89e6926a1.png)
![b](https://user-images.githubusercontent.com/324679/35185837-22df2ac6-fe02-11e7-87e9-c67c04c8838e.png)

**Comment by imekon** [comment] 2018-01-20 17:12
That's a bit hard to find. I found the import window on the same panel as Scene in my setup.

**Comment by imekon** [comment] 2018-01-20 17:24
OK turning looping off had no effect. It doesn't generate a finished event and replays the original stream. No breakpoint is fired, and the "next" print message doesn't appear.

**Comment by reduz** [comment] 2018-01-20 17:29
In Godot 3, pretty much all non-native file formats are imported. You tweak
the settings in the import panel.

**Comment by imekon** [comment] 2018-01-20 17:30
Ah, never noticed that before.

**Comment by imekon** [comment] 2018-01-20 17:53
OK, just noticed. I can't turn looping off on import. The checkbox turns off, I move away from the Ogg file, go back, its back on again.

**Comment by Sslaxx** [comment] 2018-01-20 18:00
Click on the button that says "Reimport".

**Comment by imekon** [comment] 2018-01-20 18:05
Or do this in code:

onready var introStream = load("res://music/the ethereal night intro.ogg")
onready var loopStream = load("res://music/the ethereal night loop.ogg")

func _ready():
	introStream.loop = false
	loopStream.loop = false

It does generate the finished signal once (woohoo) but stops completely after that. Trying reimport.

**Comment by volzhs** [comment] 2018-01-20 18:07
maybe, it's better to integrate import setting in file system dock... somehow

**Comment by imekon** [comment] 2018-01-20 18:16
It's still broken. Doesn't matter if I reimport or use the .loop syntax above. It now enters the finished callback ONCE then never again. The stream stops. I tried connect again in the callback, no effect.

    extends PanelContainer

    onready var introStream = load("res://music/the ethereal night intro.ogg")
    onready var loopStream = load("res://music/the ethereal night loop.ogg")
    onready var streamPlayer = $AudioStreamPlayer
    onready var statusLabel = $Panel/StatusLabel

    var count = 0

    # func _ready():
    #    introStream.loop = false
    #    loopStream.loop = false

    func _on_AudioStreamPlayerFinished():
        count += 1
        streamPlayer.stream = loopStream
        streamPlayer.play()
        statusLabel.text = "loop " + str(count)
        # connect("finished", streamPlayer, "_on_AudioStreamPlayerFinished")

    func _on_PlayButtonPressed():
        streamPlayer.stream = introStream
        streamPlayer.play()
        statusLabel.text = "intro"

**Comment by imekon** [comment] 2018-01-20 18:19
I've attached an updated version of the project, I recreated it from scratch in case it was related to exporting from 2.1.4

It plays the intro stream, then plays the loop stream, then stops. I could set the loop stream to looping I suppose, but what happens if I reuse this stream for different music, I wonder? Do I get the "finished" callback once then never again?

[oggvorbisrc1a.zip](https://github.com/godotengine/godot/files/1649129/oggvorbisrc1a.zip)

**Comment by imekon** [comment] 2018-01-20 18:30
I tried setting "the ethereal night loop.ogg" to looping, and that works, it keeps on playing, looping the second piece of music.

Stopping the stream and restarting works also. However, can't stream more than two pieces of music, the second piece must be set to looping and you only get the "finished" callback once after calling play. This sounds broken to me. What happens if I have three pieces of music I want to stream one after another?

**Comment by robfram** [comment] 2018-01-20 19:51
The problem is not changing streams. The problem here is calling play method inside the finished callback. I striped down your attached project to this script (and using a two second ogg vorbis to speed up testing) which also fail to do multiple finished signals:

```
func _on_AudioStreamPlayerFinished():
	count += 1
	streamPlayer.play()
	statusLabel.text = "loop " + str(count)

func _on_PlayButtonPressed():
	count = 0
	streamPlayer.stream = introStream
	streamPlayer.play()
	statusLabel.text = "intro"
```

The problem here is the signal is rose when the stream finish and calls set_processing_internal(false) *AFTER* streamPlayer.play() is called (which calls set_processing_internal(true)). So, the result here is the processing_internal *final value* being false, and not emiting signals anymore.

A possible workaround in your code is replace streamPlayer.play() by streamPlayer.call_deferred("play"). I tested that and it works fine.

I don't know if this is a bug or we must only be careful using calls inside callbacks.

**Comment by Zephilinox** [comment] 2018-01-20 20:07
That seems wrong to me, I'd expect to be able to play the sound again from within the signal callback, That would be one of its main uses. Would changing it so that set_processing_internal is set before the callback cause any issues?

Within a Finished() callback I'd expect streamPlayer.is_playing() to be false, but from what you said @robfram I'm guessing that's not the case? If so, I'd definitely call it a bug.

**Comment by imekon** [comment] 2018-01-20 20:14
It works though. It's not the same as V2.1.4 but that should work with call_deferred too, I assume?

If this is how you guys expect it to work, there needs to be documentation saying, "don't use play inside the finished handler, it may not work".

**Comment by robfram** [comment] 2018-01-20 20:43
@Zephilinox As I had tested briefly with this case, inside the callback streamPlayer.is_playing() returns false, but the processing_internal variable is set to true; when streamPlayer.play() is called, then the active variable will be set to true, and processing_internal too. But at some point, as the event ends its processing, the processing_internal is set to false.

@imekon @Zephilinox I don't know which is the expected behaviour, that's why I pointed the inner problem, a possible workaround, and I'm waiting for anyone with more experience to throw some light here. As far as it behaves right now, I agree with you both. It's a bug or lack of documentation.

Perhaps if the stream is active at the end of the callback, the processing_internal must be set to true, at it means the stream has been set to play again inside the callback function.

**Comment by reduz** [comment] 2018-01-20 21:45
i think the way the callback is emitted could probably be changed to allow
to call play() from within the callback

**Comment by imekon** [comment] 2018-01-20 22:35
Is that how 2.1.4 worked? Well... that's how it appeared to work, I called play and the stream played the next piece of music.

**Comment by robfram** [comment] 2018-01-21 16:34
I sent a PR #15910 to change the order of emit_signal and set_process_internal. The actual code sent first the signal, process all the callbacks, and then set process internal to false. I changed it to set process internal to false and then emit the signal and process all the callbacks.

```
if (!active || (setseek < 0 && !stream_playback->is_playing())) {
	active = false;
-	emit_signal("finished");
 	set_process_internal(false);
+	emit_signal("finished");
 }
```

I don't know if this can have any collateral effect, as the callbacks will be executed with process internal set to false. If this could be a problem, I think we could do it differently, using the active status to change the set process internal using the orignal order this way:

```
if (!active || (setseek < 0 && !stream_playback->is_playing())) {
	active = false;
	emit_signal("finished");
 	set_process_internal(active);
 }
```

**Comment by HummusSamurai** [comment] 2018-02-01 17:43
Fixed by https://github.com/godotengine/godot/pull/15910

**Closed** 2018-02-01 18:30 UTC
Labels: bug, topic:audio

**Comment by aaronfranke** [comment] 2019-01-16 12:53
> To be more specific: .ogg files in Godot 3 are automatically assigned to loop. .wav files are not.

Why?

**Comment by robodraif** [comment] 2020-03-22 10:00
> You won't. It's controlled from the Import dock.
> 
> Here's a couple of pics to show a bit about what I said:
> ![a](https://user-images.githubusercontent.com/324679/35185836-22c9e012-fe02-11e7-890c-27c89e6926a1.png)
> First, select the file you need from the FileSystem dock.
> 
> ![b](https://user-images.githubusercontent.com/324679/35185837-22df2ac6-fe02-11e7-87e9-c67c04c8838e.png)
> Second, go to Import, uncheck "Loop" and then click on Re-import.

Thanks!

**Comment by numonkeys** [comment] 2021-06-02 00:13
> It works though.

I'm debugging this same issue and came across this GitHub thread. Using Godot 3.2.3.stable.

Initially, only 1 song from a background music playlist in a game was looping over and over. So read about how to de-loop the OGG files, then did that.

After this change, the initial song would play and then stop.

I've de-looped the OGG files & reimported multiple times, rewritten code over and over to figure out what's going on. Just learned Godot, so maybe I'm missing something obvious, but what I'm seeing is that finished() signal is not firing at all. Not only is it not triggering the _on_AudioStreamPlayer_finished() in the AudioStreamPlayer script, it's not triggering the _on_AudioStreamPlayer_finished() test call to a different node that is supposed to pass a "this has triggered successfully!" message in the main game.

the .call_deferred("play") method works fine to play the initial song, but doesn't appear to have fixed the issue of not triggering the next song in the list.

Code from the AudioStreamPlayer script:

extends AudioStreamPlayer

onready var audio_player = AudioStreamPlayer.new()

var song0 = load("res://music/Example.ogg")
var song1 = load("res://music/Bonfire+-+320bit.ogg")
var song2 = load("res://music/Behind-the-Sword-320bit.ogg")
var song3 = load("res://music/Entertainment-320bit.ogg")
var song4 = load("res://music/Gjallar+-+320bit.ogg")
var song5 = load("res://music/Now+We+Feast+-+320bit.ogg")
var song6 = load("res://music/Vopna+-+320bit.ogg")
var which_song = 0

func _ready() -> void:
	cue_play_next()

func _on_AudioStreamPlayer_finished() -> void:
	which_song += 1
	var which_child = self.get_children()
	self.remove_child(which_child)
	cue_play_next()

func cue_play_next():
	if which_song == 7:
		which_song = 1
	if which_song == 0:
		audio_player.stream = song0
	if which_song == 1:
		audio_player.stream = song1
	if which_song == 2:
		audio_player.stream = song2
	if which_song == 3:
		audio_player.stream = song3
	if which_song == 4:
		audio_player.stream = song4
	if which_song == 5:
		audio_player.stream = song5
	if which_song == 6:
		audio_player.stream = song6
	self.add_child(audio_player)
#	audio_player.play()
	audio_player.call_deferred("play")
		

I'm at a loss. Any ideas/help?
