### ISSUE TITLE
background loading freezes game

### ISSUE THREAD

**Issue by ONION-777** [godotengine/godot#86252] opened 2023-12-17 07:15 UTC
### Tested versions

4.2.1.stable, 4.0.stable

### System information

Godot v4.2.1.stable - Windows 10.0.22621 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1650 (NVIDIA; 31.0.15.4601) - AMD Ryzen 5 2600 Six-Core Processor (12 Threads)

### Issue description

While loading a scene using ResourceLoader.load_threaded_request, the game hangs for a while

https://github.com/godotengine/godot/assets/101945951/4ba43c86-8800-4bfc-aaff-bfaa1b5b09c3

### Steps to reproduce

Follow this tutorial: https://www.youtube.com/watch?v=-renxc-EmUg&t=1s

### Minimal reproduction project (MRP)

[Test_load.zip](https://github.com/godotengine/godot/files/13695056/Test_load.zip)

**Comment by KoBeWi** [comment] 2023-12-17 10:14
Duplicate of #80770

**Closed by KoBeWi** 2023-12-17 10:14 UTC
