### ISSUE TITLE
SubViewports do not take inputs

### ISSUE THREAD

**Issue by NullNeska** [godotengine/godot#9950] opened 2017-07-28 15:22 UTC
**Operating system or device - Godot version:**
Windows 10, Godot 3.0.alpha1

**Issue description:**
A subviewport that i made, as a child of a viewport container wont take any inputs at all.

**Steps to reproduce:**
Make a viewportcontainer, make a viewport as a child of it. try to make inputs happen on any node in the viewport or the viewport itself. _input(event) is not ran. not even set_process_input(true) fixes it.

**Comment by Zylann** [comment] 2017-07-29 02:52
Is it happening in 2.1.3 too?

**Comment by reduz** [comment] 2017-07-29 04:05
You have to enable input manually

**Comment by ImFlavo** [comment] 2017-07-29 11:05
I read elsewhere it was automatic but this is fine too, not a big deal.

**Comment by reduz** [comment] 2017-07-29 16:20
The rationale is that it's better that viewports don't process input by
default, as a lot of use cases don't need it. It's better that you manually
have to enable it, that (due to ignorance) a lot of viewports are left to
process input uneccesarily

**Comment by vnen** [comment] 2017-07-29 17:14
[Documentation](http://docs.godotengine.org/en/latest/learning/features/viewports/viewports.html#input) says that "subviewports" (i.e. viewports that are child of a control) receive automatic input, while "render targets" does not.

**Comment by daviel** [comment] 2019-04-24 11:47
I think this problem persists in a way please see my post here: https://www.reddit.com/r/godot/comments/bewxc7/viewports_with_input_events/

**Comment by FilipLundby** [comment] 2020-01-05 20:10
I'm experiencing this in 3.2.beta4.

Sample project:
[ViewportCamera.zip](https://github.com/godotengine/godot/files/4023950/ViewportCamera.zip)

 A workaround is to use signals from outside the viewport, to trigger actions inside the viewport.

**Comment by KoBeWi** [comment] 2022-01-14 23:45
Seems fixed in 3.5.
The above project is unrelated, the viewport isn't rendered anywhere, so it won't receive input. The issue is about ViewportContainer.

**Closed by KoBeWi** 2022-01-14 23:45 UTC
Labels: enhancement, documentation
