### ISSUE TITLE
Can't add nodes to Array properties in Inspector

### ISSUE THREAD

**Issue by trollusk** [godotengine/godot#75053] opened 2023-03-18 06:53 UTC
### Godot version

4.0

### System information

Windows 11

### Issue description

If a node has an Array[Node3D] property, then it is impossible to assign nodes to its elements. Dragging nodes from the scene tree to the array has no effect. Clicking the "Assign..." button brings up a list of nodes, but after selecting a node and clicking OK, nothing changes and the array element remains unassigned.

### Steps to reproduce

- Create a new 3D scene.
- Attach a script to the root node, containing "@export var my_array : Array[Node3D]".
- Add a child node.
- In the inspector for the root node, click "Add element" under the my_array property.
- Unsuccessfully attempt to add the child node to the array.

### Minimal reproduction project

N/A

**Comment by qza2468** [comment] 2023-03-18 07:10
I tried, and it's like what you said. But i don't know too much of this.

Android12, godot4 download in play store

**Comment by capnm** [comment] 2023-03-18 08:00
I can confirm this. Looks like it makes somewhere internally similar errors:
![grafik](https://user-images.githubusercontent.com/4047289/226093203-f4b6cdeb-cb2f-4efc-bb93-b97b3b25b827.png)

**Comment by Zireael07** [comment] 2023-03-18 08:03
Seriously, search before opening yet another duplicate...

Dupe of #74975

**Comment by capnm** [comment] 2023-03-18 08:11
Too many open errors :) https://github.com/godotengine/godot/issues/62916

**Comment by Calinou** [comment] 2023-03-19 03:29
Duplicate of https://github.com/godotengine/godot/issues/62916.

**Closed by Calinou** 2023-03-19 03:29 UTC
