### ISSUE TITLE
Tab freeze when exporting a 3D scene for web

### ISSUE THREAD

**Issue by giangm9** [godotengine/godot#27486] opened 2019-03-28 11:23 UTC
**Godot version:**
3.0.6.stable.official.8314054

**OS/device including version:**

Description:	Ubuntu 18.04.2 
Google Chrome 73.0.3683.86

**Issue description:**
Tab freeze when run  a 3D scene

**Steps to reproduce:**
Create a 3D scene 
Buld to web
Host to localhost by `python3 -m http.server` command
tab freeze
The scene is very simple, just a cube in front of a camera
![Screenshot from 2019-03-28 18-22-30](https://user-images.githubusercontent.com/10234339/55154048-790eee80-5186-11e9-9801-ce0d06a020b9.png)

**Comment by Calinou** [comment] 2019-03-28 13:14
Try switching to the GLES2 renderer (in the top-right corner of the editor), so that WebGL 1 is used instead of WebGL 2 in the HTML5 export.

**Comment by giangm9** [comment] 2019-03-28 15:36
it works, thanks

**Comment by giangm9** [comment] 2019-03-28 15:49
It no longer freeze, but takes long time to show screen ( after loading bar disapeared ), after i refresh the page a couple of time, it shows correctly

**Comment by Faless** [comment] 2020-07-27 10:01
I'm unable to reproduce with latest Godot versions (`3.1.2` and `3.2.2`) and Chrome 84 on Ubuntu 20.04.

Seems fixed in both `3.1` and `3.2` releases. Closing. Feel free to comment if you are still experiencing this issue.

**Closed by Faless** 2020-07-27 10:01 UTC
Labels: bug, platform:html5, topic:porting
