### ISSUE TITLE
[Godot 4 beta 7] Canvas mode in WorldEnvironment influences editor's drop down menus and modal windows

### ISSUE THREAD

**Issue by Arfilish** [godotengine/godot#69478] opened 2022-12-02 08:12 UTC
### Godot version

4.0 beta 7

### System information

Linux 6.0.10-arch2-1, Intel UHD Graphics 630, Vulkan

### Issue description

Bug with empty dropdown menus and modal windows was already fixed in beta 6, though WorldEnvironment with Canvas background mode still influences it, this shouldn't happen.

### Steps to reproduce

For example i'll show this with brightness.

1. Create any type of scene and add WorldEnvironment node to it.
2. Create Environment resource, it doesn't matters if it's local or not - it should be in created WorldEnvironment node.
3. Change background mode to 'Canvas' in it.
4. Enable Adjustments, and change Brightness to  any value (i'll use value 3).
5. Look at any dropdown menu or modal window, for example, 'Create New Node'.
![Знімок екрана з 2022-12-02 10-09-29](https://user-images.githubusercontent.com/74733247/205246171-62f60c68-d341-4d70-8ae8-40f612987a67.png)
![Знімок екрана з 2022-12-02 10-09-41](https://user-images.githubusercontent.com/74733247/205246199-fb1ce725-4ddb-49a3-91eb-9811c639f4d6.png)

### Minimal reproduction project

N/A

**Comment by Calinou** [comment] 2022-12-02 15:13
Duplicate of https://github.com/godotengine/godot/issues/69122 (same cause).

**Closed by Calinou** 2022-12-02 15:13 UTC
