### ISSUE TITLE
[4.0 RC2] - HTML5 Build Does Not Work On Apple macOS Safari Internet Browser?

### ISSUE THREAD

**Issue by BetaMaxHero** [godotengine/godot#73640] opened 2023-02-20 18:14 UTC
### Godot version

v4.0.rc2.official [d2699dc7a]

### System information

Apple macOS Safari Internet Browser

### Issue description

Hi,

We had a tester run a HTML5 build of our game on a macOS desktop.
Game does not function in macOS Safari Internet browser?

Game does run on all Windows/Linux Internet browsers.
Any ideas?

Thanks!

Jesse

### Steps to reproduce

https://betamaxheroes.org/games/TS3-Godot_4/builds/RC0/WebVer/index.html

### Minimal reproduction project

N.A.

**Comment by Calinou** [comment] 2023-02-20 21:48
Duplicate of https://github.com/godotengine/godot/issues/65696 and/or https://github.com/godotengine/godot/issues/70691.

**Closed by Calinou** 2023-02-20 21:48 UTC
