### ISSUE TITLE
Godot 4.0 CollisionShape2D Rendering Issues?

### ISSUE THREAD

**Issue by iamjoeysox** [godotengine/godot#71131] opened 2023-01-09 20:15 UTC
### Godot version

4.0beta10

### System information

Mac 13.1

### Issue description

I am seeing some really odd issues with collision shapes within Godot 4.0 beta 10 where the corners are doing something weird and there seems to be some kind of inner outline applied? This is super confusing to me and I'm pretty sure it's not intended to happen? This also seems to be causing some odd collision issues sometimes for me, but not always.

### Steps to reproduce

1. Create new blank project
2. Add a CharacterBody2D node to the default scene
3. Add a CollisionShape2D node to the above node
4. Add a new rectangle shape to the above node
5. Resize via extents and watch it do odd stuff

### Minimal reproduction project

N/A

<img width="566" alt="Screenshot on 2023-01-09 at 12 08 37 PM" src="https://user-images.githubusercontent.com/10987800/211399608-c5434b47-5df4-44e7-94e3-7e81dac061d0.png">

**Comment by iamjoeysox** [comment] 2023-01-09 20:24
I did just notice I had the following settings turned on, can someone explain this to me?

<img width="675" alt="Screenshot on 2023-01-09 at 12 21 31 PM" src="https://user-images.githubusercontent.com/10987800/211401124-bcfe0ad5-cbfc-4a18-abf6-f897b188c494.png">

**Comment by stephannv** [comment] 2023-01-09 20:29
Yeah, here I facing the same "issue". Mac OS 12.6.

<img width="1157" alt="Screen Shot 2023-01-09 at 17 29 01" src="https://user-images.githubusercontent.com/3025661/211401965-e89e691f-2583-4f1e-9b7f-fc352dd2d501.png">

**Comment by markdibarry** [comment] 2023-01-09 20:50
Duplicate of #56320

**Closed** 2023-01-09 21:40 UTC
Labels: bug, topic:rendering, topic:2d
