### ISSUE TITLE
Opening project now opens 3D view every time (even in 2D scene)

### ISSUE THREAD

**Issue by kerskuchen** [godotengine/godot#11198] opened 2017-09-12 17:17 UTC
Ubuntu 16.04 LTS, Godot 3.0 master

Since recently Godot opens a project with a startup 2D scene in 3D view.
Earlier versions from 1-2 weeks ago did not show this behavior.

**Comment by Zireael07** [comment] 2017-09-12 17:38
Duplicate of #11045

**Closed** 2017-09-12 18:10 UTC
