### ISSUE TITLE
RtAudio warning while game is running, and audio has sound pops

### ISSUE THREAD

**Issue by CowThing** [godotengine/godot#10644] opened 2017-08-26 02:29 UTC
**Operating system or device, Godot version:**
Windows 10 64bit - Godot 2.1.4 RC

**Issue description:**
The warning "RtAudio output underflow!" shows up in the error log a few times per second while the game is running. And audio (specifically tested using the Platformer demo with the music) has a popping sound almost in sync with the warnings.

This was not present in 2.1.4 2017-08-17, the audio sounds completely normal in that build and there was no warnings.

**Steps to reproduce:**
Open any project or create a new project and run it.

**Comment by eon-s** [comment] 2017-08-26 04:13
Duplicate of #7288, and I suspect of some other programs (like browsers) that triggers the annoying warning on Windows.

**Comment by akien-mga** [comment] 2017-08-26 08:30
> This was not present in 2.1.4 2017-08-17, the audio sounds completely normal in that build and there was no warnings.

Can you confirm that the issue is systematically reproducible in the RC build but doesn't appear if testing the 2017-08-17 build in the same conditions?

**Comment by CowThing** [comment] 2017-08-26 13:46
Yes it happens every time I run the RC build, even just launching the RC editor, the warnings start appearing in the console.
![](http://i.imgur.com/55JkGip.png)

But with the 2017-08-17 build and earlier I've never seen the warning.

**Comment by Zireael07** [comment] 2017-08-26 13:49
@CowThing: That must have been a fluke, the warnings happen on Windows all the time, as I pointed out in #7288.

**Comment by CowThing** [comment] 2017-08-26 14:04
In the official Godot 3.0 alpha1 I don't see this warning. But in a more recent unofficial 3.0 build (from 8-22) I do see the same exact warning as I'm seeing in the 2.1.4 RC build.

**Comment by akien-mga** [comment] 2017-08-26 17:01
Seems to be a regression from #10406.

**Comment by akien-mga** [comment] 2017-08-27 08:17
For 2.1, the regression (this bug) is fixed with cf80fbc9, though it does not address the previous #7288 bug.
For master, #10683 aims at fixing both bugs, but since it seems non-trivial, I went the safe route for 2.1.4.

**Closed** 2017-08-28 21:03 UTC
Labels: bug, topic:audio
