### ISSUE TITLE
MenuButton not working on Android

### ISSUE THREAD

**Issue by Montecri** [godotengine/godot#36497] opened 2020-02-24 00:21 UTC
Godot version: 3.2 and 3.2.1-RC1

OS/device including version: Moto G7 Plus/Android 10, Nox / Android 7, Windows 10

Issue description: Create a menu button populated with 5 entries only. On Windows Godot environment it works as expected. You click the button, the menu is displayed, you click one of the menu entries, event is triggered. all good and well.

The same project exported to Android, you click the button and only a small grey rectangle right below the button appears. No menu entry, nothing.

Steps to reproduce: Add a MenuButton to a project, add a few entries to it. Export to Android (doesn't matter if custom template or not), click button, no menu appears.

**Comment by Calinou** [comment] 2020-02-24 08:16
@Montecri Please upload a minimal reproduction project to make this easier to reproduce.

**Comment by KoBeWi** [comment] 2020-12-20 19:34
Closing due to lack of update. Please comment if you can still reproduce this issue in the latest stable version of Godot.

**Closed by KoBeWi** 2020-12-20 19:34 UTC
Labels: bug, platform:android, topic:gui
