### ISSUE TITLE
Inconsistencies when moving between text fields with TAB

### ISSUE THREAD

**Issue by codespren** [godotengine/godot#66446] opened 2022-09-26 14:02 UTC
### Godot version

4.0 beta1 mono

### System information

macOS Monterey 12.4

### Issue description

When moving between text fields with TAB the text in the text field is not always editable (focus moves but the cursor doesn't).

### Steps to reproduce

1. Create a new object with Transform, for example Node3D.
2. Select a text field in the Inspector with mouse, in this example Position's x-field. Note that the focus is in the first field (blue line around it) and the cursor is no visible and it is possible to change the value by using keyboard.
3. Press TAB.

Expected: The focus should move to the next field, in this example Position's y-field and the cursor should be visible and value editable.

Actual: The focus moves to correct field but the cursor is not visible and it is not possible to edit the value. User has to click the field with mouse to make it editable.

Note: Sometimes the focus (blue line around the field) is moved to the next field but the cursor stays in the first field and it is not possible to move forward to the third field. The behaviour is slightly different depending where the cursor and the focus are when starting the reproduce sequence.

**Comment by KoBeWi** [comment] 2022-09-26 14:57
Duplicate of #37723

**Closed by KoBeWi** 2022-09-26 14:57 UTC
