### ISSUE TITLE
Dragging a 3D node in editor in 3D space gives an error 'Node3DEditorViewport::_get_drag_data_fw': Method not found.

### ISSUE THREAD

**Issue by viksl** [godotengine/godot#71693] opened 2023-01-19 20:43 UTC
### Godot version

4.0 Beta 13 mono

### System information

Windows 10, Nvidia GTX 1660Ti, Vulkan

### Issue description

It seems any 3D node when dragged in the editor to some position in 3D space gives this error everytime you drag it:

![Screenshot 2023-01-19 214122](https://user-images.githubusercontent.com/33526847/213555249-fdeaa93e-086f-4801-8bf5-d0381264cfba.png)

The node still ends up where it needs to be so it doesn't seem to be an editor breaking issues as far as I can tell but just to be sure I'm reporting it here.

### Steps to reproduce

1. Add a 3D node to a 3D space, for example Node3D or StaticBody3D
2. In the 3D editor grab one of the gizmo axes and drag it somewhere
3. Observer the error message in the Output tab.

### Minimal reproduction project

-

**Comment by akien-mga** [comment] 2023-01-19 20:46
Thanks for the report! Duplicate of #71412, will be fixed in 4.0 beta 14.

**Closed by akien-mga** 2023-01-19 20:46 UTC
