### ISSUE TITLE
Duplicating control node with Clip Children makes godot stop

### ISSUE THREAD

**Issue by Jowan-Spooner** [godotengine/godot#69778] opened 2022-12-08 20:25 UTC
### Godot version

4.0 beta 7

### System information

Linux Mint 20.2, HP laptop

### Issue description

Trying to duplicate a control node (PanelContainer) with `clip_children` set to `Clip+Draw` or `Clip Only` either with CTRL+D or the right click menu, consistently brings godot to a halt for me, forcing me to shut it down via a task manager.

### Steps to reproduce

This is the setup of nodes:
![grafik](https://user-images.githubusercontent.com/42868150/206560204-e0ed0dd6-01ce-4d2c-9a0b-19ff80260d0e.png)
I'm trying to duplicate the WelcomBox node (which has Clip Children set to Clip+Draw). Changing the WelcomBox to a control node or removing the Title label both enable me to duplicate without a problem.  

### Minimal reproduction project

[TestBug.zip](https://github.com/godotengine/godot/files/10189223/TestBug.zip)

**Comment by Jowan-Spooner** [comment] 2022-12-08 20:39
Probably related to this, so I won't create a new issue: Trying to set `clip children` on multiple nodes can also crash godot.
Easily reproducible using the reproduction project above as well:
- open home_page scene
- set Welcom Box clip children to disabled
- duplicate WelcomBox
- select both WelcomBox's
- try setting clip children to clip only or draw+clip

**Comment by KoBeWi** [comment] 2022-12-08 21:42
Can't reproduce.
Windows 10, GTX 1060

**Comment by TomSpalango** [comment] 2022-12-09 01:43
Cannot reproduce using steps above.  Does not crash.
OS: Windows 11 Home, Version 21H2, OS build 22000.1219
GPU: GTX 3080

**Comment by DissonantVoid** [comment] 2022-12-22 21:51
tried this both on windows 10 64bit and windows 7 64bit, can't reproduce
linux specific?

**Comment by Rindbee** [comment] 2023-03-05 13:08
Could not reproduce on Linux Mint 21.1.

**Comment by KoBeWi** [comment] 2023-03-05 13:57
Closing based on above comments.

**Closed by KoBeWi** 2023-03-05 13:57 UTC
Labels: bug, platform:linuxbsd, topic:rendering, topic:editor, needs testing
