### ISSUE TITLE
global_script_class_cache.cfg doesn't get properly generated if extension_list.cfg doesn't exist on first load

### ISSUE THREAD

**Issue by BrianWiz** [godotengine/godot#77478] opened 2023-05-25 16:16 UTC
### Godot version

Tested with 4.0, 4.0.1, 4.0.2 and 4.0.3 Mono editions

### System information

Tested on several Windows PCs and a Mac

### Issue description

When the `.godot` folder doesn't exist and you have a gdextension in your project, the first launch causes a crash and causes `global_script_class_cache.cfg` to not generate correctly, breaking all gdscripts until you force the `class_name` on every script to re-register in the cache. (by commenting `class_name` out, save, uncomment, save, on every gd script).

**Suggested workaround if you're working with git**
Allow `./godot/extension_list.cfg` in your `.gitignore`.

### Steps to reproduce

- Ensure `.godot` folder doesn't exist
- Ensure your project has at least one gdextension
- Ensure your project has at least one script with a global class name

### Minimal reproduction project

This can be reproduced with a modified demo from `godot-cpp`, here is one compiled for Windows x64.
[minimal_repro.zip](https://github.com/godotengine/godot/files/11567071/minimal_repro.zip)

The project is inside the `demo` directory. I have included a script which contains a `class_name` named `script_with_class_name.gd`

- The first launch should crash
- Look at the `.godot` folder, no `global_script_class_cache.cfg` exists
- Launch again, it shouldn't crash this time.
- Look at the `.godot` folder again, `global_script_class_cache.cfg` exists now, but it does not have the class name in there.

**Comment by saletrak** [comment] 2023-06-17 17:55
It happens to me also on Godot_v4.0.3-stable_macos.universal

**Comment by Hilderin** [comment] 2024-07-05 00:56
I tested the MRP with a build from master now that #92303 is merge. Godot does not crash on editor start if the `.godot` folder is missing and the `global_script_class_cache.cfg` is now correctly regenerated.

The only error I get is this one and I need to restart the editor to fix it:
![image](https://github.com/godotengine/godot/assets/81109165/d05e2ee2-47bc-4d44-a604-3de6fc1d1e34)

It comes from the fact that if `extension_list.cfg` is missing, `GDExtensions` are loaded after the `GDScriptLanguage::init` and globals are not updated after `GDExtensions` are loaded. I'll try to create a PR to fix that also.

**Comment by akien-mga** [comment] 2024-07-05 10:29
Yeah this error sounds related to #53163, which was closed as presumably fixed but I never confirmed it myself. I always thought restarting the editor once when loading a project with a GDExtension was still the "normal" workflow, like for plugins.

**Comment by Hilderin** [comment] 2024-07-05 11:23
Indeed, restarting the editor seems the preferred workflow. After a bit of investigation, it does not sound a good idea to modify that behavior.

**Comment by akien-mga** [comment] 2024-07-05 11:31
Well it's the preferred workflow due to bugs - ideally we should be able to resolve all imports and dependencies thereof on the first edit of a project, so that it works out of the box.

**Comment by Hilderin** [comment] 2024-07-05 11:38
I totally agree with you, the process should be a lot smoother. I did some modifications locally to make it work but I'm really not sure it will cover all possibilities. Maybe later I'll create a PR just to have some feedbacks, who knowns!

**Closed** 2024-08-30 08:10 UTC
Labels: bug, topic:core, topic:gdextension, crash
