### ISSUE TITLE
Godot v4.4-dev crashes on startup

### ISSUE THREAD

**Issue by knucklesncs** [godotengine/godot#99881] opened 2024-11-30 18:20 UTC
### Tested versions

Reproducible in v4.4-dev1 - v4.4-dev5
Works fine for any version prior

### System information

Ubuntu 22.04.5 LTS 22.04 - X11 - Vulkan (Forward+) - dedicated AMD Radeon RX 6700 XT (RADV NAVI22) - AMD Ryzen 9 7950X 16-Core Processor (32 Threads)

### Issue description

When trying to launch the Godot application on Linux, it crashes before it can even load the project manager.

Here is the information printed in the terminal when running the project with the debug flag:

```plain
WorkerThreadPool: 32 threads, 9 max low-priority.
Godot Engine v4.4.dev5.official.9e6098432 - https://godotengine.org
TextServer: Added interface "Dummy"
TextServer: Added interface "ICU / HarfBuzz / Graphite (Built-in)"
JoypadLinux: udev enabled and loaded successfully.
/lib/x86_64-linux-gnu/libX11.so.6: undefined symbol: XFreeThreads
Xshape 1.1 detected.
Xinerama 1.1 detected.
Xrandr 1.6 detected.
Xrender 0.11 detected.
Xinput 2.2 detected.
XInput: Refreshing devices.
XInput: No touch devices found.
Detecting GPUs, set DRI_PRIME in the environment to override GPU detection logic.
Only one GPU found, using default.
ScreenSaver: DBus 1.12.20 detected.
FreeDesktopScreenSaver: Acquired screensaver inhibition cookie: 17882
PortalDesktop: DBus 1.12.20 detected.
Using "default" pen tablet driver...
Shader 'CanvasSdfShaderGLES3' SHA256: d518c17f340b1e883671854949cead397ea9fc5850d7872b6b20e26c3d907de5
Shader 'SkeletonShaderGLES3' SHA256: 5380c4310c07d8eef12ffd385d47dd959a1eb0fc6f311beb760e3e94e6148c15
Shader 'ParticlesShaderGLES3' SHA256: 9755542d0a556b95174fcd04ea6d1f6e4e4c98898e529da4c7d4b8d2e5271dc0
Shader 'ParticlesCopyShaderGLES3' SHA256: e633c8477480c31fd09e6b6f690fe204aa7fccaeb83102ff68d597ab004cec36
Shader 'CopyShaderGLES3' SHA256: 7a5b8022233051fd832239e3e94ad556c3a74ece97ac31cc3dd9c9a03d3ab56d
Shader 'CubemapFilterShaderGLES3' SHA256: e0d7c124ebcf653d7336e4230829fc1bf16a86a0c34daafd89bd346469f77522
Shader 'GlowShaderGLES3' SHA256: eac3b6b0cbff3da2483dd50d9ffe957a1f7c647f8b4ffd7db9441dbcbbf50448
Shader 'PostShaderGLES3' SHA256: 04af0d53a49df9a29d9b2c444aac8a9fdece4cf8221faf2862d00791334a4fd9
Shader 'FeedShaderGLES3' SHA256: 44d70d119b848ad59201bbbcd7bd4d6ebf7b93edc160bc2e65bb1676d6ee6322
Shader 'CanvasShaderGLES3' SHA256: 51e04b8380256135a744daf58f997048725bd36d8a890f9a2eb4fab31e25109b
Shader 'CanvasOcclusionShaderGLES3' SHA256: dd09fd0c42a427ba25a86844f4e33bd8968fa8e7a80f3c8c0b9accaf4782cb2e
Shader 'SceneShaderGLES3' SHA256: 0311ab5e92c02b14470fe00800672357814fc282e76c71ebcd944b5d2a95332d
Shader 'SkyShaderGLES3' SHA256: 891ab6119a340af61e5d7127d92ca7d12a2cf4e479658ff9aca53c8bb47348df
OpenGL API 4.6 (Core Profile) Mesa 22.3.0-devel - Compatibility - Using Device: AMD - AMD Radeon RX 6700 XT (navi22, LLVM 15.0.3, DRM 3.49, 5.15.0-126-generic)

TextServer: Primary interface set to: "ICU / HarfBuzz / Graphite (Built-in)".
CORE API HASH: 4051078667
EDITOR API HASH: 804865399
Loading resource: /home/ncs/.config/godot/editor_settings-4.3.tres
EditorSettings: Load OK!
EditorTheme: Generating new theme for the config '66886095'.
EditorTheme: Generating new icons.
EditorTheme: Generating new fonts.
EditorTheme: Generating new styles.
: CommandLine Error: Option 'help-list' registered more than once!
LLVM ERROR: inconsistency in registered CommandLine options
Aborted (core dumped)
```

### Steps to reproduce

Launch the application.

### Minimal reproduction project (MRP)

-

**Comment by adamscott** [comment] 2024-11-30 19:51
Try running with the verbose flag instead of the debug flag.

**Comment by akien-mga** [comment] 2024-12-01 12:27
```
/lib/x86_64-linux-gnu/libX11.so.6: undefined symbol: XFreeThreads
```

This seems weird, though it may not be related to the crash. Do you have this in the logs also with 4.3.stable and previous 4.4.dev snapshots?

```
: CommandLine Error: Option 'help-list' registered more than once!
LLVM ERROR: inconsistency in registered CommandLine options
Aborted (core dumped)
```

So this is the main error. An internal LLVM error like this typically means a driver bug, in your case a Mesa issue.

I see you have Mesa 22.3.0-devel:
```
OpenGL API 4.6 (Core Profile) Mesa 22.3.0-devel - Compatibility - Using Device: AMD - AMD Radeon RX 6700 XT (navi22, LLVM 15.0.3, DRM 3.49, 5.15.0-126-generic)
```

Did you install this manually from a PPA or compile from source? A devel version of Mesa would likely not be shipped by Ubuntu in its LTS version.

In fact, Ubuntu 22.04 seems to have a much newer Mesa version, you might just need to update?
https://launchpad.net/ubuntu/+source/mesa/23.2.1-1ubuntu3.1~22.04.2

**Comment by adamscott** [comment] 2024-12-02 20:32
I would suggest to try Godot 4.4-dev5 on the latest Ubuntu LTS 22.04 LiveCD, if possible. If it crashes, it would underline something with your machine. If it doesn't crash, it would point towards a driver issue.

**Comment by akien-mga** [comment] 2024-12-02 20:52
@knucklesncs These packages with `amdgpu` in the name and version `1:22.3.0.50401` don't seem to be provided by Ubuntu. I suspect they're an old installation of the confusingly named AMDGPU (PRO) proprietary driver from AMD (presumably from https://www.amd.com/en/support/download/linux-drivers.html), which is now quite old and out of date compared to the rest of your Mesa (open source drivers) setup.

On Linux, there's not much reason to use the proprietary AMDGPU PRO driver as the open source driver which is part of the kernel + mesa (also named AMDGPU) is full-featured and maintained by AMD engineers. So I would suggest removing the packages with version `1:22.3.0.50401`, doing a round of normal `apt-get update`, and you might end up with a much better driver situation.

**Comment by fwsGonzo** [comment] 2024-12-05 21:20
I just tested `Godot_v4.4-dev6_linux.x86_64` and I got the `libX11.so.6: undefined symbol: XFreeThreads`, however the editor is starting up.

**Comment by akien-mga** [comment] 2024-12-05 21:32
> I just tested `Godot_v4.4-dev6_linux.x86_64` and I got the `libX11.so.6: undefined symbol: XFreeThreads`, however the editor is starting up.

Thanks for testing. Yeah the "undefined symbol: XFreeThreads" error is not what's causing the crash here for @knucklesncs - it's very likely caused by their mismatch between recent-ish Mesa and outdated AMDGPU PRO drivers.

The XFreeThreads warning is probably harmless and was likely caused by #98976 in 4.4-dev5 and later.

**Comment by akien-mga** [comment] 2024-12-05 21:32
I'll close this as debugging so far points at a user system configuration issue, not a Godot bug.

**Closed by akien-mga** 2024-12-05 21:32 UTC
Labels: bug, topic:editor, needs testing, crash
