### ISSUE TITLE
Light2D set to mix mode renders incorrectly within a Viewport in GLES3

### ISSUE THREAD

**Issue by svendixon** [godotengine/godot#71260] opened 2023-01-12 05:21 UTC
### Godot version

v3.5.stable.offical

### System information

Windows 11, GLES3, GTX 980 Ti (528.02)

### Issue description

Not sure if this is already a known issue.

Light2D set to mix mode ALWAYS renders the alpha of the texture incorrectly in the editor in GLES3, but strangely enough, if it's NOT within a viewport, it looks fine when you run the project. However, if it IS within a viewport, it renders it wrong even when you run the project.

GLES2 looks fine in both the editor and when you run the project.

### Steps to reproduce

1. Create a ViewportContainer
2. Create a Viewport within the ViewportContainer
3. Create a scene with some Light2Ds set to mix mode within the Viewport
5. Run in GLES3

or

If you open the minimal project, you should see right away that the lights are not rendered correctly. If you run the project, the issue persists. However, if you drag the World node above Viewport in the scene tree, the lights will still render wrong in the editor, but when you run the project, it looks fine. Again, in GLES2 it looks fine in both the editor and when you run the project.

### Minimal reproduction project

![light2d_viewport_issue_gles3](https://user-images.githubusercontent.com/14341036/211977370-937dc98e-1416-402d-a85d-355e501ca6e0.png)
[Light2DViewportIssueGLES3.zip](https://github.com/godotengine/godot/files/10398244/Light2DViewportIssueGLES3.zip)

**Comment by Calinou** [comment] 2023-01-12 16:48
Duplicate of https://github.com/godotengine/godot/issues/8685, https://github.com/godotengine/godot/issues/46153 and/or https://github.com/godotengine/godot/issues/45615.

**Closed by Calinou** 2023-01-12 16:48 UTC
Labels: bug, topic:rendering, topic:2d
