### ISSUE TITLE
The kinematic body always bounces when move across the edge of cube meshes

### ISSUE THREAD

**Issue by ekasit555** [godotengine/godot#38501] opened 2020-05-06 08:49 UTC
**Godot version:** 
3.2.1 stable

**OS/device including version:**
Win 10 x64

**Issue description:**
The kinematic body always bounces when move across the edge of cube meshes (static body collision)
The physic process is set at 60 fps

**Steps to reproduce:**
1.Make a kinetic body movement with gravity apply
2. make cubes of static body with collision shape and connect them together (you can also use grid map or manual connected)
3. move kinematic body across the edge of cube static body. you will see jagged bounce and sometime if kinematic body stands at the edge of static body, it also bounce without moving.

![ezgif-1-9f37ff82e869](https://user-images.githubusercontent.com/46420188/81155853-93351600-8faf-11ea-9f93-3a985dc63bcf.gif)

**Comment by madmiraal** [comment] 2020-05-06 10:14
Duplicate of #35780?

**Comment by ekasit555** [comment] 2020-05-06 11:49
@madmiraal yes it's the same problem.

**Comment by Calinou** [comment] 2020-05-06 12:39
Closing, as this is a duplicate of #35780.

**Closed by Calinou** 2020-05-06 12:39 UTC
