### ISSUE TITLE
MultiplayerSynchronizer Replication Tab Missing

### ISSUE THREAD

**Issue by GregHilston** [godotengine/godot#63898] opened 2022-08-04 03:13 UTC
### Godot version

4.0.alpha13

### System information

Windows 10

### Issue description

The replication tab that pops up at the bottom of the game engine UI does not always display.

### Steps to reproduce

I've seen it pop up once, and if I switch to another scene and come back, it is gone.

I'm able to get it to pop up again by modifying the scene file, `.tcsn` directly, and the having Godot report that the scene is malformed, and then undoing the change.

I've reverted my project down to Godot 4 Alpha 12 and can see the Replication tab consistently.

**Comment by jgillich** [comment] 2022-08-04 06:11
Duplicate of #63621 (and already fixed in master)

**Comment by Calinou** [comment] 2022-08-04 07:52
Duplicate of #63621.

**Closed by Calinou** 2022-08-04 07:52 UTC

**Comment by GregHilston** [comment] 2022-08-10 18:57
awesome, thanks everyone!
