### ISSUE TITLE
UI: Element focus visible through layers on top (only About?)

### ISSUE THREAD

**Issue by mhilbrunner** [godotengine/godot#12374] opened 2017-10-24 13:32 UTC
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Latest master as of this issue
Windows 7 x64, NVIDIA GTX 980 Ti

**Issue description:**
If you open Help -> About, select one of the cells in the popup window and scroll, the focus border is still visible if the element is scrolled out of view. See attached GIF.

**Steps to reproduce:**
See description above/GIF below

**Link to minimal example project:**
![GIF](https://i.imgur.com/epqeCv2.gif)

**Comment by akien-mga** [comment] 2017-10-24 13:34
Duplicate of #9612.

**Closed by akien-mga** 2017-10-24 13:34 UTC
