### ISSUE TITLE
Thread.start enforces calling method with one argument

### ISSUE THREAD

**Issue by Norrox** [godotengine/godot#24893] opened 2019-01-10 21:27 UTC
**Godot version:**
Godot 3.1 Beta 1

**Issue description:**
Is the function you are calling with myThread.start(self, "MyThreadFunc") supposed to always need an argument ? the thread wont start unless i provide the MyThreadFunc with one, even tho i'm not passing anything to it ?

![996dcd1afe97b8bc00ee6ad330edf001](https://user-images.githubusercontent.com/13393087/50998126-d2239a80-1526-11e9-97fa-9707881bf9bd.png)

[threadExample.zip](https://github.com/godotengine/godot/files/2747114/threadExample.zip)

**Comment by Naryosha** [comment] 2019-01-11 03:16
Can confirm
```
ERROR: _start_func: Could not call function 'MyFirstThreadFunc'' starting thread ID: 5 Reason: Too Many Arguments
   At: core/bind/core_bind.cpp:2436.
```

**Comment by timoschwarzer** [comment] 2019-01-11 13:03
Duplicate of https://github.com/godotengine/godot/issues/9924

**Closed** 2019-01-11 14:18 UTC
Labels: bug, topic:core
