### ISSUE TITLE
Visual script: call and call deferred functions doesn't have input parameter

### ISSUE THREAD

**Issue by sami8github** [godotengine/godot#21342] opened 2018-08-24 02:57 UTC
**Godot version:**
v3.1.dev.calinou.5df9109

**OS/device including version:**
windows 10 x64

**Issue description:**
in visual script :
call and call deferred functions take 1arg wich is a method , but they dont have input parameter.

**Steps to produce:**
create node >> create visual script >> drag and drop "Call" node from available nodes >> edit function to "Call" or "Call deferred"

**Comment by Noshyaar** [comment] 2018-08-24 07:49
Confirmed. It appears when the scene is reloaded.

**Comment by KoBeWi** [comment] 2020-06-18 23:45
Can anyone still reproduce this bug in Godot 3.2.1 or any later release (e.g. [3.2.2-rc2](https://godotengine.org/article/release-candidate-godot-3-2-2-rc-2))?
(for some reason I don't see the `call` method in VisualScript)

**Comment by KoBeWi** [comment] 2020-09-28 16:25
Closing due to lack of update. Please comment if you can still reproduce this issue in the latest stable version of Godot.

**Closed by KoBeWi** 2020-09-28 16:25 UTC
Labels: bug, confirmed, topic:visualscript
