### ISSUE TITLE
Several object and alloc leaks when a Node has any script attached

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#22776] opened 2018-10-05 21:31 UTC
Godot 3.1 f5a77f7bdd6d59f32f7d9aad81dabc5733221275
Windows 10 64 bits

I'm getting the following leaks:
```
WARNING: ObjectDB::cleanup: ObjectDB Instances still exist!
     At: core\object.cpp:2086
Leaked instance: ImageTexture:17701 - Resource name:  Path:
Leaked instance: Image:17700 - Resource name:  Path:
Orphan StringName: ImageTexture
Orphan StringName: Image
StringName: 2 unclaimed string names at exit.
ERROR: There are still MemoryPool allocs in use at exit!
   At: core\dvector.cpp:70
```

Reproduction:
[leak.zip](https://github.com/godotengine/godot/files/2452294/leak.zip)

Open the project in the editor, and close it.

**Comment by akien-mga** [comment] 2019-01-24 12:22
I can reproduce the leak in the current master (fb9c837).

Might be related to #19300 where material shader code is not freed (so maybe materials leak).

**Comment by akien-mga** [comment] 2019-01-24 12:30
Stripped down version that still leaks: [leak-2.zip](https://github.com/godotengine/godot/files/2791650/leak-2.zip)

It's basically an empty project with an empty script attached. The leak happens when the script is attached to the Node, if removed the leak does not happen.
Sounds like it might be the script preview image leaking?

**Comment by aaronfranke** [comment] 2019-01-28 10:50
I can also confirm, I experience the first and last item on my Linux computer. Terminal looks like this:

![d](https://user-images.githubusercontent.com/1646875/51831644-90ce1180-22c0-11e9-8206-a4083e9db7e0.png)

**Comment by IronicallySerious** [comment] 2019-01-30 20:47
Can confirm this on godot.x11.tools.64 build. I am getting the errors on exit as aaronfranke

**Comment by akien-mga** [comment] 2019-02-08 09:36
It should not be too hard to debug if anyone is interested, you should try to figure out what script-related feature can leak an Image and an ImageTexture.

I suspect the custom script icons, CC @willnationsdev (note that none is used in this case, but it might still erroneously allocate an empty ImageTexture?).

**Comment by willnationsdev** [comment] 2019-02-09 14:01
Oh, lovely. So how exactly does one leak an ImageTexture in the first place? Figured that would have to be something like adding an image and then somehow manually deleting the Ref without having it delete the image or something. Not sure what to look for given the whole "reference-counting" feature.

**Comment by akien-mga** [comment] 2019-02-11 12:32
I did some digging, the leaked `ImageTexture` is the one generated in `EditorScriptPreviewPlugin::generate()` here: https://github.com/godotengine/godot/blob/1c14da32732e8e0473f8650286deff10f394d0ac/editor/plugins/editor_preview_plugins.cpp#L592-L595

The leaked `Image` is the one assigned to it, generate just above.

I suspect that the leak is due to the new FileSystem dock, since it does not happen in 3.1 alpha 1, but it appeared in alpha 2 where the new dock was introduced (it seems it basically leaked the whole scene tree in alpha 2, which has since been fixed, but not the script preview leak). CC @groud

This seems confirmed by this finding: if you toggle Split Mode (where the script preview is actually displayed), the preview is not leaked. It's only leaked if you're using the List Mode, and open a scene which triggers the generation of the then unused script preview texture.

**Comment by behelit2** [comment] 2019-03-14 20:26
I'm seeing the same thing on my linux console when exiting 3.1 official:
```
WARNING: cleanup: ObjectDB Instances still exist!
   At: core/object.cpp:2092.
ERROR: cleanup: There are still MemoryPool allocs in use at exit!
   At: core/pool_vector.cpp:70.
```
Never saw these errors in my project before switching to 3.1.

**Comment by ConnorBP** [comment] 2019-04-02 20:45
Just noticed this while making some scripts to build my project from the command line. Doesn't exactly look awesome in build logs.

**Comment by qarmin** [comment] 2019-05-27 10:05
Not only Image leaks but also TreeItem
```
Leaked instance: TreeItem:22523
Leaked instance: Image:1751 - Resource name:  Path: 
Leaked instance: TreeItem:20616
Leaked instance: TreeItem:23767
Leaked instance: ImageTexture:1750 - Resource name:  Path: 
Leaked instance: TreeItem:25516
Leaked instance: TreeItem:20914
Leaked instance: TreeItem:22137
Leaked instance: TreeItem:22513
Orphan StringName: ImageTexture
Orphan StringName: TreeItem
Orphan StringName: Image
StringName: 3 unclaimed string names at exit.
ERROR: cleanup: There are still MemoryPool allocs in use at exit!
   At: core/pool_vector.cpp:70.
```
Project to reproduce: https://github.com/qarmin/Sea-of-Ground

Steps to reproduce:
1. Open project and Godot with verbose (e.g. ./godot.x11.tools.64 -e -v --path "/home/rafal/Projekty/Sea of Ground")
2. Open all tscn scenes
3. Close this scenes and Godot

**Comment by ibrahn** [comment] 2019-05-27 10:48
@qarmin looks like a different leak, probably better to open a separate issue, if you can create a minimal reproduction project for it

**Closed** 2019-05-27 11:29 UTC
Labels: bug, topic:core
