### ISSUE TITLE
[4.4dev7] Engine crashes when copy or duplicate 3d light (spotlight or omnilight)

### ISSUE THREAD

**Issue by cortrano** [godotengine/godot#100709] opened 2024-12-21 19:21 UTC
### Tested versions

- Godot 4.4.dev.7.mono

### System information

macOS 15.2

### Issue description

Godot 4.4 dev 7 crashes when copy or duplicate 3d light (spotlight or omnilight)

### Steps to reproduce

1) create empty node3d scene
2) add omniLight3d node
3) try to copy or duplicate it (or parent node containing this light)
4) get a crash

### Minimal reproduction project (MRP)

[copy_crash_reproduce.zip](https://github.com/user-attachments/files/18219688/copy_crash_reproduce.zip)

**Comment by AThousandShips** [comment] 2024-12-21 19:24
Thank you for reporting, this has already been solved, please see:
* https://github.com/godotengine/godot/issues/40543

**Comment by AThousandShips** [comment] 2024-12-21 19:26
My bad different issue

**Comment by Namey5** [comment] 2024-12-21 23:00
I believe this should have been fixed by https://github.com/godotengine/godot/pull/100632

**Comment by AThousandShips** [comment] 2024-12-21 23:02
Indeed, closing as a duplicate of:
* https://github.com/godotengine/godot/issues/100629

**Closed by AThousandShips** 2024-12-21 23:02 UTC
Labels: bug, topic:rendering, crash
