### ISSUE TITLE
[GDScript 2.0] [regression] complex constant parse error

### ISSUE THREAD

**Issue by Scony** [godotengine/godot#52031] opened 2021-08-23 17:41 UTC
### Godot version

master #fb176d5f6e6dc2b43c630a041a8ab7d737173ec4

### System information

manjaro linux

### Issue description

following script:
```
const X = {
	'x': [],
}
```
yields
```
SCRIPT ERROR: Parse Error: Initializer for a constant must be a constant expression.
          at: GDScript::reload (res://tests/potential-godot-bugs/const-dict.gd:1)
ERROR: Method/function failed. Returning: ERR_PARSE_ERROR
   at: reload (modules/gdscript/gdscript.cpp:840)
```
while it was working in Godot `3.x`

### Steps to reproduce

compile

**Comment by lyuma** [comment] 2021-08-25 04:51
Closing as duplicate of #50285

**Closed by lyuma** 2021-08-25 04:51 UTC
Labels: bug, topic:gdscript, regression
