### ISSUE TITLE
Any chance of changing assignment in conditional from error to warning?

### ISSUE THREAD

**Issue by rslepon** [godotengine/godot#31210] opened 2019-08-08 17:31 UTC
**Godot version:**
Godot_v3.1.1-stable_win64

**Issue description:**
At the moment, gdscript does not allow assignment in conditionals, such as "if a = b:", yielding an "Unexpected assign" error.

While I understand the wisdom of this, I can also see some scenarios where allowing these would make code more readable and maintainable, which is no less important. Here is one example, for parsing a string that may have a host of different formats:

```
if regexmatch = regex1.search(string):
   [extract some data from groups collected in regexmatch]
elif regexmatch = regex2.search(string):
   [extract some data from groups collected in regexmatch]
elif regexmatch = regex3.search(string):
   [extract some data from groups collected in regexmatch]
elif regexmatch = regex4.search(string):
   [extract some data from groups collected in regexmatch]
```
So, any chance of changing assignment in conditional from error to warning?

**Comment by KoBeWi** [comment] 2019-08-08 17:57
Oooh, this reminds me of #7222

I was going to revive it after the warnings were added. There's no reason to reject it now 😏

**Comment by vnen** [comment] 2020-06-22 15:56
Duplicate of #7222 and proposals have their own tracker now.

See also the proposal for a similar feature: https://github.com/godotengine/godot-proposals/issues/1103

**Closed by vnen** 2020-06-22 15:56 UTC
Labels: discussion, topic:gdscript
