### ISSUE TITLE
Godot crashes when using vscode

### ISSUE THREAD

**Issue by grazianobolla** [godotengine/godot#52201] opened 2021-08-28 22:11 UTC
### Godot version

3.3.3 

### System information

Manjaro Linux Kernel 5.10.60-1

### Issue description

Godot crashes when using vscode
```
handle_crash: Program crashed with signal 11
Dumping the backtrace. Please include this when reporting the bug on https://github.com/godotengine/godot/issues
[1] /usr/lib/libc.so.6(+0x3cda0) [0x7f14e6524da0] (??:0)
[2] /home/graziano/Escritorio/Godot_v3.3.3-stable_x11.64() [0xe15f97] (??:0)
[3] /home/graziano/Escritorio/Godot_v3.3.3-stable_x11.64() [0x2f78a1a] (??:?)
[4] /home/graziano/Escritorio/Godot_v3.3.3-stable_x11.64() [0x2f288f5] (??:?)
[5] /home/graziano/Escritorio/Godot_v3.3.3-stable_x11.64() [0xe50446] (??:0)
[6] /home/graziano/Escritorio/Godot_v3.3.3-stable_x11.64() [0xe447b5] (??:0)
[7] /home/graziano/Escritorio/Godot_v3.3.3-stable_x11.64() [0x2f2cec1] (??:?)
[8] /home/graziano/Escritorio/Godot_v3.3.3-stable_x11.64() [0x2f2d90c] (??:?)
[9] /home/graziano/Escritorio/Godot_v3.3.3-stable_x11.64() [0x2f64a28] (??:?)
[10] /home/graziano/Escritorio/Godot_v3.3.3-stable_x11.64() [0x2f7fd1b] (??:?)
[11] /home/graziano/Escritorio/Godot_v3.3.3-stable_x11.64() [0xe142e4] (??:0)
[12] /home/graziano/Escritorio/Godot_v3.3.3-stable_x11.64() [0x1cda1ae] (??:0)
[13] /home/graziano/Escritorio/Godot_v3.3.3-stable_x11.64() [0x1ceb9c8] (??:0)
[14] /home/graziano/Escritorio/Godot_v3.3.3-stable_x11.64() [0x3119a3d] (??:?)
[15] /home/graziano/Escritorio/Godot_v3.3.3-stable_x11.64() [0x990dcd] (??:0)
[16] /usr/lib/libc.so.6(__libc_start_main+0xd5) [0x7f14e650fb25] (??:0)
[17] /home/graziano/Escritorio/Godot_v3.3.3-stable_x11.64() [0x99f5ae] (??:0)
-- END OF BACKTRACE --
```

### Steps to reproduce

It doesn't seem to be reproducible in any specific way, but only happens when VSCODE is connected

**Comment by pycbouh** [comment] 2021-08-28 22:12
Duplicate of https://github.com/godotengine/godot/issues/51923.

**Closed by pycbouh** 2021-08-28 22:12 UTC
