### ISSUE TITLE
Shift + Tab doesn't work on a right side of line

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#53649] opened 2021-10-10 19:56 UTC
### Godot version

09b0293

### System information

W10

### Issue description

If you have caret at the right side of line, e.g like this:
![image](https://user-images.githubusercontent.com/2223172/136711220-1725a96b-5696-40c5-ae96-16bbaf7c8dc9.png)
you can't use Shift + Tab to decrease indentation.

### Steps to reproduce

1. Add indented text
2. Try Shift-Tabbing it when caret is at the end of line

**Comment by EricEzaM** [comment] 2021-10-10 23:39
cc @Paulb23 ?

**Comment by Calinou** [comment] 2021-10-11 01:26
Duplicate of https://github.com/godotengine/godot/issues/50279.

**Closed by Calinou** 2021-10-11 01:26 UTC
Labels: bug, topic:editor, usability, regression
