### ISSUE TITLE
Function autocomplete doesn't have default values

### ISSUE THREAD

**Issue by Jummit** [godotengine/godot#33260] opened 2019-11-02 10:01 UTC
**Godot version:**
3.1

**Issue description:**
When autocompleting a parent function, it doesn't have the default values, meaning there will be an error because the signatures don't match.

**Steps to reproduce:**
Creae a script extending EditorSpatialGizmo and autocomplete commit_handle.

**Comment by tom-jk** [comment] 2020-08-10 11:44
This is what I get in 3.1 and later if I start typing commit_handle and hit enter:

![Godot33260_Screen](https://user-images.githubusercontent.com/64640811/89776727-5b83c000-db02-11ea-8a1a-3c0d09783263.png)

I must enter the parameters myself, which is expected as Godot can't guess at what I want to do. The `cancel` parameter has a default variable, but since you aren't required to type it in the script for it to work, I also wouldn't expect or want it filled in.

If I type it outside of a function (eg. directly under `extends ...`) there's no autocomplete, which also makes sense.

Could you clarify what the issue is (and whether it's a bug or an enhancement/feature request)?

**Comment by KoBeWi** [comment] 2021-12-27 00:04
It was never clarified and there is no trace of this bug, so closing.
btw `commit_handle()` is a virtual function, so you shouldn't be calling it manually.

**Closed by KoBeWi** 2021-12-27 00:04 UTC
Labels: bug, topic:gdscript

**Comment by cesarizu** [comment] 2021-12-27 01:14
I believe this is about auto-completing the function definition to override the parent function, not about using parent functions in the code.

**Comment by KoBeWi** [comment] 2021-12-27 01:15
But when you override you also get all parameters with their types. It works correctly.

**Comment by cesarizu** [comment] 2021-12-27 03:51
I doesn't... If you add a `pass` to that you'll get an error:

![image](https://user-images.githubusercontent.com/658725/147432526-a879829b-06cd-4f9c-b955-b84f3a538c12.png)

The right autocomplete should be:

```
func commit_handle(index: int, restore, cancel: bool = false) -> void:
```

Note the `= false` that is missing from the original one.

**Comment by KoBeWi** [comment] 2021-12-27 22:18
I checked in 4.0 and this method doesn't have the default argument anymore. In fact, the binding system was changed and default arguments in virtual methods seem impossible now (it doesn't make much sense anyways). So the issue is effectively resolved.

**Comment by cesarizu** [comment] 2021-12-28 20:12
You are right, in 4.0 it seems all virtual methods seem to have lost their default values on gdscript, even though the C++ classes still have them.
