### ISSUE TITLE
Instancing a custom type throws an error

### ISSUE THREAD

**Issue by LeonardMeagher2** [godotengine/godot#2105] opened 2015-06-16 23:43 UTC
When instancing a custom type created by a script plugin
I get this error

```
ERROR: instance: Condition ' !ti ' is true. returned: __null
   At: core/object_type_db.cpp:283.
ERROR: _create: Condition ' !c ' is true.
   At: tools/editor/scene_tree_dock.cpp:1075.
```

I'm not sure what to do about this error.

__Here is all the code__
https://github.com/LeonardMeagher2/Godot-Assets/tree/master/Plugins/Trails

__Here is a gif to sort of demonstrate the situation__

![bug](https://cloud.githubusercontent.com/assets/1546044/8197480/5e23dbe6-144d-11e5-994a-b4954c79b616.gif)

**Comment by akien-mga** [comment] 2015-11-22 13:47
Confirmed in the current master branch.

**Comment by reduz** [comment] 2016-01-02 23:41
plugin system is still kinda wip, will work more on it on 2.1

**Comment by akien-mga** [comment] 2016-07-15 08:39
I guess this issue has been obsoleted by the new EditorPlugin API in 2.1. I'll close it, as even if there are still similar problems, their root cause and manifestation would likely have changed, so they'd be better suited in a new issue.

**Closed by akien-mga** 2016-07-15 08:39 UTC
Labels: bug, confirmed, topic:editor
