### ISSUE TITLE
Ask before breaking project.godot compatibility

### ISSUE THREAD

**Issue by eon-s** [godotengine/godot#20626] opened 2018-07-31 03:13 UTC
**Godot version:** master  3f01f40

**Issue description:**
When opening a project with versions that break compatibility, the editor open and modify the project without asking.

Would be nice to have a confirmation window before opening and breaking compatibility of a project, more now with the upcoming alpha.

**Comment by sriramsk1999** [comment] 2018-08-02 11:09
Hi, I'm a newbie to the Godot community and I would like to contribute in developing the engine. But the codebase is large and intimidating and I'm not sure how to start fixing any issue. I have a fork cloned into my system and understand the basics of Godot. 
Where do I go next? 
Thanks!

**Comment by LaBlazer** [comment] 2018-08-02 12:11
@sriramsk1999 You should probably join Discord or IRC to ask these questions...

**Comment by sriramsk1999** [comment] 2018-08-02 12:13
Ah sorry. My bad.

**Comment by eon-s** [comment] 2018-08-02 12:28
@sriramsk1999 try to get used to how Controls work (in general), check another similar confirmation dialogs and how to read the project data.

For how to contribute, refer to docs for details:
http://docs.godotengine.org/en/3.0/community/contributing/index.html

And you can do the PR directly and start conversation there, but may be faster to find help on IRC in case you are stuck with something.

**Comment by akien-mga** [comment] 2018-12-17 13:48
Duplicate of #18758.

**Comment by akien-mga** [comment] 2018-12-17 13:48
Actually no, this issue is the other way around (3.0 to 3.1, while #18758 is 3.1 to 3.0).

**Closed** 2018-12-21 13:43 UTC
Labels: enhancement, topic:editor, usability
