### ISSUE TITLE
Integer when changed becomes both the old value and the new value

### ISSUE THREAD

**Issue by Fable-git** [godotengine/godot#38033] opened 2020-04-20 02:35 UTC
**3.2.1.stable.official:**

**Linux - mxlinux:**

I wanted to change the hunger of my dog and instead of changing it, it seems to have split two realities: one where it was never changed and one where it was changed. When printing the variable, you get a mixture of the two different values, when it should only be the new value EXAMPLE: dog.hunger = 0, dog.hunger += 10, print(dog.hunger) returns 0, print(dog.hunger) returns 10, print dog.hunger return 10, print dog.hunger returns 0. I don't know what is happening, I swear I am only adding 10, but something seems to be fundamentally wrong

Write dog node with variable health and print it out in func _process(). Create an enemy node that at random time intervals removes health. Probably should use a timer node and a script to change it to random interval whenever it times out. That should do it. I tried to control it with a method inside the dog node, but didn't change the outcome.

**Minimal reproduction project:**
see above paragraph

**Comment by allkhor** [comment] 2020-04-20 07:08
[Dog_eat_int.zip](https://github.com/godotengine/godot/files/4501732/Dog_eat_int.zip)
Can't reproduce, please provide minimal project to easy understand problem.

**Comment by Fable-git** [comment] 2020-04-20 15:18
[Dog.zip](https://github.com/godotengine/godot/files/4504418/Dog.zip)
This is the exact project I'm having issues with. Thanks for looking into it!

**Comment by allkhor** [comment] 2020-04-20 16:43
Please provide valid minimal reproduction project.
You upload compiled version of scripts, files with .gdc extension.
1) Try to create a new project.
2) Add some nodes and scripts to show what wrong.
3) Upload project.

**Comment by allkhor** [comment] 2020-04-23 04:33
cc @akien-mga, @Calinou, I think this issue can be closed, without the additional information and reproduction project, dev's can't help. @Fable-git for discussion, Godot have many comunication places https://godotengine.org/community .

**Comment by madmiraal** [comment] 2020-05-26 15:28
Closing as unable to reproduce.

**Closed by madmiraal** 2020-05-26 15:28 UTC
