### ISSUE TITLE
animation editor cursor bug

### ISSUE THREAD

**Issue by xa8et67** [godotengine/godot#4900] opened 2016-05-30 06:17 UTC
![gif](https://cloud.githubusercontent.com/assets/19285181/15641152/64b168ca-2671-11e6-89fe-d143ca2671ae.gif)

**Comment by xa8et67** [comment] 2016-05-30 06:18
![image](https://cloud.githubusercontent.com/assets/19285181/15641143/4c637a88-2671-11e6-898c-cdf721a1bc02.png)

**Comment by eska014** [comment] 2016-05-30 12:26
Looks like a duplicate of #4418

**Closed by eska014** 2016-05-30 12:26 UTC
Labels: bug, topic:editor
