### ISSUE TITLE
Deleted 2d nodes not removed completely from scene tree

### ISSUE THREAD

**Issue by zarsystem** [godotengine/godot#11529] opened 2017-09-24 07:02 UTC
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
On OpenSuse tumbleweed and Godot version 3.0.alpha.custom_build

**Issue description:**
Deleted 2d nodes in unsaved scene tree not completely removed and using object navigator buttons in inspector(< >) you can swich between removed objects. but after saving the scene, that objects removed completely.

**Steps to reproduce:**
1- Create a scene and add some nodes and one or more sprites.
![1](https://user-images.githubusercontent.com/3175411/30780241-5b4a088c-a113-11e7-8577-661a71268dd7.png)
2- Delete nodes from scene tree.
![2](https://user-images.githubusercontent.com/3175411/30780242-5b6ab5fa-a113-11e7-91bf-5585de187fc1.png)
3- Try to navigate over deleted nodes using < > buttons in inspector.

**Comment by akien-mga** [comment] 2017-09-25 05:38
Duplicate of #11560.

**Closed by akien-mga** 2017-09-25 05:38 UTC
Labels: bug, topic:editor
