### ISSUE TITLE
[Bullet] PhysicsServer always reports 0 active objects due to reporting not being implemented

### ISSUE THREAD

**Issue by drwhut** [godotengine/godot#59279] opened 2022-03-18 13:08 UTC
### Godot version

3.3.4.stable, 3.4.3.stable

### System information

Linux Mint 20.3

### Issue description

I've been trying to write code for my game that, depending on how many active (i.e. not sleeping) objects there are, will determine how much network traffic the server sends to the clients when updating them on the physics object's states.

Specifically, I am trying to get the value of `PhysicsServer.get_process_info(PhysicsServer.INFO_ACTIVE_OBJECTS)`. According to [the documentation](https://docs.godotengine.org/en/stable/classes/class_physicsserver.html?highlight=number%20of%20physics%20objects#class-physicsserver-method-get-process-info), this should return a "constant to get the number of objects that are not sleeping.".

However, the function always seems to return the value `0`, even if there are clearly moving physics objects in the scene.

This seems to also affect the return value of `Performance.get_monitor(Performance.PHYSICS_3D_ACTIVE_OBJECTS)`, which after looking at the source code, uses the function mentioned above to get the value.

### Steps to reproduce

1. Open the ActiveObjectTest project.
2. Run the scene.
3. Observe that the RigidBody cube is falling to the floor, but that the print output of `PhysicsServer.get_process_info(PhysicsServer.INFO_ACTIVE_OBJECTS)` is always `0`, even when the cube is falling.

### Minimal reproduction project

[ActiveObjectTest.zip](https://github.com/godotengine/godot/files/8304581/ActiveObjectTest.zip)

**Comment by rburing** [comment] 2022-03-18 15:54
This is specific to the Bullet physics server:

https://github.com/godotengine/godot/blob/4739c821dcbe36138711a1a355cdd1ee5ec5d371/modules/bullet/bullet_physics_server.cpp#L1558-L1560

In GodotPhysics, the method is implemented as expected. This should at least be documented in the meantime.

**Comment by Calinou** [comment] 2022-04-06 22:49
Duplicate of https://github.com/godotengine/godot/issues/16540.

**Closed by Calinou** 2022-04-06 22:49 UTC
Labels: documentation, topic:physics, topic:3d
