### ISSUE TITLE
Remote and Local Tree Resource Assignment Inconsistency - Resource assigned to remote node is set to null instance.

### ISSUE THREAD

**Issue by Eoin-ONeill-Yokai** [godotengine/godot#55887] opened 2021-12-13 01:18 UTC
### Godot version

3.x branch

### System information

Manjaro KDE,  AMD Ryzen 7 5800X 8-Core Processor, AMD RX 590 GPU

### Issue description

While debugging, you can change a resource value inside the `local tree`'s inspector and have these changes be reflected in the game instantaneously -- this is useful for when you want to change properties during runtime to test out certain values or configurations. This works as long as you have the sync flag checked in the debugging options, obviously.

However, one strange behavior is that when you do the same thing in the `remote tree`, the value will instead be replace will a null value. This seems to occur with all resource fields in the remote tree, regardless how simple they are. Changing the debugger's synchronization settings seems to have no effect on the behavior. 

Here's a video illustrating the bug...
https://www.youtube.com/watch?v=ApuDR6nhnog  

### Steps to reproduce

  - Create a simple tree (like in the video in the description.) A Control node with an image is a good testing condition. No scripts necessary.
  - Have 2 images ready, and drag one of them onto the resource field before playing.
  - Play the scene. Have debugger scene synchronization enabled. 
  - On the `local` tree, select your image node and drag a new image onto the node's inspector panel. You will see the image be replaced successfully. 
  - Now click on `remote`, and then the node on the remote treee. You will see a new warning on the top of the inspector when you have the correct `remote` node selected as the active node.
  - Click+drag another image onto the node. You will see that this remote-tree version of the node won't accept the resource, and assigns it to null.

**Comment by Zireael07** [comment] 2021-12-13 08:53
Many resources ARE displayed as null in remote tree even when unchanged while debugging - I believe this is a display issue already reported.

**Comment by Eoin-ONeill-Yokai** [comment] 2021-12-14 06:16
@Zireael07 I don't know... It seems like this isn't just an inspector bug. Notice how swapping the image completely removes the image from the node.

**Comment by Calinou** [comment] 2022-02-06 11:08
Duplicate of https://github.com/godotengine/godot/issues/47237 (same cause).

**Closed by Calinou** 2022-02-06 11:08 UTC
Labels: bug, topic:core
