### ISSUE TITLE
crash , white screen

### ISSUE THREAD

**Issue by sayedbakeer3** [godotengine/godot#69422] opened 2022-11-30 23:50 UTC
### Godot version

godot 4 beta 4. 5 . 6

### System information

windows 7 bit 64 , core 5 i 1 G , intel(R) HD Graphics , 4 ram

### Issue description

the problem is when try to open godot 4 beta 4 or 5 or 6 it's going to crash every time 
white screen coming ... godot crash.

### Steps to reproduce

![godot 4 erorr](https://user-images.githubusercontent.com/97993670/204932379-ea133d6b-c695-4bac-a6b8-affcee2cbede.PNG)

### Minimal reproduction project

![2](https://user-images.githubusercontent.com/97993670/204932539-ca610c84-b379-4e17-a313-8868a15ae4ff.PNG)

this all what i can do

**Comment by bend-n** [comment] 2022-12-01 00:01
Do you have logs?

**Comment by mrbaggins** [comment] 2022-12-01 03:10
I had this hit me the other day, a PC restart fixed it, hasn't happened since. Mine eventually did work if you waited, but the engine was super slow and unresponsive.

**Comment by sayedbakeer3** [comment] 2022-12-01 10:12
> Do you have logs?

no,i don't because engine never start up

**Comment by sayedbakeer3** [comment] 2022-12-01 23:20
> Do you have logs?

![3](https://user-images.githubusercontent.com/97993670/205179677-acb49d72-a762-4de2-9684-20844a6bd874.PNG)
i hope that help you from godot 4 cmd

**Comment by Calinou** [comment] 2022-12-01 23:38
Does Godot 3.5.1 work on the same machine with the GLES3 renderer, or can you only use GLES2 there?

> core 5 i 1 G , intel(R) HD Graphics

Which exact CPU model do you have?

**Comment by sayedbakeer3** [comment] 2022-12-02 00:50
> I had this hit me the other day on beta5, a PC restart fixed it, hasn't happened since. Mine eventually did work if you waited, but the engine was super slow and unresponsive.

1-open engine 
2-wait sec
3-engine white screen after engine down and tell me to close progame

**Comment by sayedbakeer3** [comment] 2022-12-02 00:52
> Does Godot 3.5.1 work on the same machine with the GLES3 renderer, or can you only use GLES2 there? Depending on your CPU model, this may be related to #67595.
> 
> > core 5 i 1 G , intel(R) HD Graphics
> 
> Which exact CPU model do you have?

first time tell me only GLES2 only work but after add file (opengl32.dll) from mesa3d fixed and i can use GLES3 too.
so
i can use both of them

**Comment by Calinou** [comment] 2022-12-02 15:18
Alright, closing as a duplicate of https://github.com/godotengine/godot/issues/67595 since this is essentially the same problem.

**Closed by Calinou** 2022-12-02 15:18 UTC
Labels: bug, platform:windows, topic:rendering, needs testing, crash

**Comment by sayedbakeer3** [comment] 2022-12-02 18:36
> Alright, closing as a duplicate of #67595 since this is essentially the same problem.

so what can i do to fix problem ?

**Comment by sayedbakeer3** [comment] 2022-12-02 18:38
> > Alright, closing as a duplicate of #67595 since this is essentially the same problem.
> 
> so what can i do to fix problem ?

in least window didn't open or use GLSE2

**Comment by sayedbakeer3** [comment] 2022-12-02 18:44
> @sayedbakeer3
> 
> > so what can i do to fix problem ?
> 
> You can't and it hasn't been fixed yet. That's why #67595 is still open. This issue hasn't been completely closed, just see it as "merged"

thank you , i want developers to see problem 
i start to be game developer for long time but my laptop is low-end when i see godot 3 i said this my hero because light engine and free and good community will help anyone
