### ISSUE TITLE
Vulkan: Issue with parallax layers and mirroring (Intel driver bug)

### ISSUE THREAD

**Issue by Slowbro213** [godotengine/godot#82380] opened 2023-09-26 16:25 UTC
### Godot version

Godot_v4.1.1-stable_win64

### System information

Godot v4.1.1.stable - Windows 10.0.19045 - Vulkan (Mobile) - integrated Intel(R) HD Graphics 520 (Intel Corporation; 26.20.100.8142) - Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz (4 Threads)

### Issue description

The problem has to do with parallax layers. I am following a YouTube tutorial to learn Godot and I'm at the part where I'm trying to make a background that moves to the left infinitely in a loop.  I create a Parallax background Node Scene and attach two parallax layers to it, I then add a background photo to one of the layers, make the photo as big as the camera and then mirror it, but when i do mirror it, it doesn't show up. if i move to the right so that the photo isnt visible the mirrored photo suddenly appears, when i run the game the screen moves but half of the screen is just gray

![Screenshot 2023-09-26 180625](https://github.com/godotengine/godot/assets/100229861/eb88b871-db9b-4583-8e92-cc7ee779d2cf)

![Screenshot 2023-09-26 180832](https://github.com/godotengine/godot/assets/100229861/698db4f9-5474-415d-9002-9940171300be)

![Screenshot 2023-09-26 180851](https://github.com/godotengine/godot/assets/100229861/916d384a-80a7-4646-8c4a-21ff56cd52ad)

![Screenshot 2023-09-26 180929](https://github.com/godotengine/godot/assets/100229861/e505e3e6-c705-4aff-a4eb-1524097e625f)

if i try to add this Scene to my main scene , the play button is moved to the side for some reason.

![Screenshot 2023-09-26 181214](https://github.com/godotengine/godot/assets/100229861/51d70c54-c7f2-400f-910b-75ab453a7032)

![Screenshot 2023-09-26 181258](https://github.com/godotengine/godot/assets/100229861/c9556cb1-0b8e-4926-af88-b4d8866a402b)

### Steps to reproduce

Create a new scene with the parallax background node , add a parallax layer child Node , add a png to the parallax layer , make the png as big as the camera (as big as the zone outlined with blue) ,  if you try to mirror the parallax layer it wont work. if you then add that scene to some other scene , it causes issues. i added the project and you can see for yourself. the main scene already has the Background Scene which makes the Play button bugged.

### Minimal reproduction project

[Bug report.zip](https://github.com/godotengine/godot/files/12729817/Bug.report.zip)

**Comment by Sauermann** [comment] 2023-09-27 08:07
related: #67120 #30988

**Comment by ronddraaiend** [comment] 2023-10-01 03:51
I and another user also encountered this bug. It seems Vulkan specific. For us it disappeared if using the compatibility renderer. Both of us are on integrated graphics (just like the submitter of the above report). The issue does not exist in (any renderer) in Godot version 3.5.2. 

See also https://discord.com/channels/212250894228652034/1143708041682882720

**Comment by Calinou** [comment] 2023-10-01 18:08
This is likely due to the same cause as https://github.com/godotengine/godot/issues/58314.

**Comment by PetrVychopen** [comment] 2023-10-02 17:55
I bet you followed freecodecamp tutorial. I had the same problem. I found out that there is temporary workaround for it. 
Just make sure the Mirroring for Y axe is not zero, but really small number... e.g. like 0.001. I can't tell if it won't cause you trouble in the future, but at least, it is working. Cheers.

![image](https://github.com/godotengine/godot/assets/62891161/3ee55330-bbb6-4838-9ff0-04abc7af0783)

**Comment by Slowbro213** [comment] 2023-10-02 22:36
> I bet you followed freecodecamp tutorial. I had the same problem. I found out that there is temporary workaround for it. 
> Just make sure the Mirroring for Y axe is not zero but really small number... e.g. 0.001. I can't tell if it won't cause you any trouble in the future, but at least, it is working. Cheers.
> 
> ![image](https://github.com/godotengine/godot/assets/62891161/3ee55330-bbb6-4838-9ff0-04abc7af0783)
>  


Yep you're right that's the tutorial!

While the fix your proposed sort of works , it's still buggy on runtime , and even worse when I put the background I just created on the main scene , it still shifts some stuff on the right (as shown in the pictures I provided above). Although such a thing doesn't happen on Comparability, so ig for now I'll just stick to Compatibility or buy a new laptop in the future.

**Comment by akien-mga** [comment] 2024-03-04 13:35
I tested and can't reproduce this issue on 4.1.1 (same as OP) or 4.3-dev4 on Linux with AMD GPU, so @Calinou may be right that it's a duplicate of https://github.com/godotengine/godot/issues/58314, which seems to be a hardware/driver specific issue.

**Closed by akien-mga** 2024-03-04 13:35 UTC
Labels: bug, platform:windows, topic:rendering, confirmed, topic:thirdparty, topic:2d

**Comment by RajaMahanty** [comment] 2024-05-01 11:58
> ### Godot version
> Godot_v4.1.1-stable_win64
> 
> ### System information
> Godot v4.1.1.stable - Windows 10.0.19045 - Vulkan (Mobile) - integrated Intel(R) HD Graphics 520 (Intel Corporation; 26.20.100.8142) - Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz (4 Threads)
> 
> ### Issue description
> The problem has to do with parallax layers. I am following a YouTube tutorial to learn Godot and I'm at the part where I'm trying to make a background that moves to the left infinitely in a loop. I create a Parallax background Node Scene and attach two parallax layers to it, I then add a background photo to one of the layers, make the photo as big as the camera and then mirror it, but when i do mirror it, it doesn't show up. if i move to the right so that the photo isnt visible the mirrored photo suddenly appears, when i run the game the screen moves but half of the screen is just gray
> 
> ![Screenshot 2023-09-26 180625](https://private-user-images.githubusercontent.com/100229861/270722896-eb88b871-db9b-4583-8e92-cc7ee779d2cf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ1NjQ0NDUsIm5iZiI6MTcxNDU2NDE0NSwicGF0aCI6Ii8xMDAyMjk4NjEvMjcwNzIyODk2LWViODhiODcxLWRiOWItNDU4My04ZTkyLWNjN2VlNzc5ZDJjZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwMVQxMTQ5MDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iMDc4ZWQ2MWU1ZDI0ZjJhY2RmODE5MzNlMmZlZTliZWU1YzhlYzdkMjgxODUwYzkzZGQ2YmM1NmViOTU1M2ZjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.85k0AbwRTpHiLpiYNe34BkrAp-yo3hlIVgvqxRb2rdo)
> 
> ![Screenshot 2023-09-26 180832](https://private-user-images.githubusercontent.com/100229861/270722962-698db4f9-5474-415d-9002-9940171300be.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ1NjQ0NDUsIm5iZiI6MTcxNDU2NDE0NSwicGF0aCI6Ii8xMDAyMjk4NjEvMjcwNzIyOTYyLTY5OGRiNGY5LTU0NzQtNDE1ZC05MDAyLTk5NDAxNzEzMDBiZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwMVQxMTQ5MDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01YzEwMDNmNGZmMjYzZjc0MjVhZmNjZTEyNjM1NGMyZjkzMmU1MzdhZTQ2OTk1ODg4NTU5M2I5MTBmNjQ5MzQzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.PNm2z6MJ0S4hLtCs70z84iuXapODuwgYIsS6ie1MRx4)
> 
> ![Screenshot 2023-09-26 180851](https://private-user-images.githubusercontent.com/100229861/270723003-916d384a-80a7-4646-8c4a-21ff56cd52ad.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ1NjQ0NDUsIm5iZiI6MTcxNDU2NDE0NSwicGF0aCI6Ii8xMDAyMjk4NjEvMjcwNzIzMDAzLTkxNmQzODRhLTgwYTctNDY0Ni04YzRhLTIxZmY1NmNkNTJhZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwMVQxMTQ5MDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iODc0ODVlNDlhMTExMDc0MDA4MzNlNjE4ZGRlMGMyYTU0Y2ZmMmYxNDJmOWM0N2E2ZDE3NjExMWVmMzkxZmM5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.TAG0g0vyXToHYq-cgNKew67ChQrYvNR4Ufc-AfJ48z8)
> 
> ![Screenshot 2023-09-26 180929](https://private-user-images.githubusercontent.com/100229861/270723024-e505e3e6-c705-4aff-a4eb-1524097e625f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ1NjQ0NDUsIm5iZiI6MTcxNDU2NDE0NSwicGF0aCI6Ii8xMDAyMjk4NjEvMjcwNzIzMDI0LWU1MDVlM2U2LWM3MDUtNGFmZi1hNGViLTE1MjQwOTdlNjI1Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwMVQxMTQ5MDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hZjM3ZDg2MzUyYTYzN2RkMGNlMWNkZTM4OTI2YTRkZGFkMzkxYmQwZDcxMTk2NjZjYTYyODY1YjNhMWNiMjE5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.DSVE5To0eGWKCcUp5VrpeUuQ-qHEvmXe1cLkVpnLxHo)
> 
> if i try to add this Scene to my main scene , the play button is moved to the side for some reason.
> 
> ![Screenshot 2023-09-26 181214](https://private-user-images.githubusercontent.com/100229861/270724171-51d70c54-c7f2-400f-910b-75ab453a7032.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ1NjQ0NDUsIm5iZiI6MTcxNDU2NDE0NSwicGF0aCI6Ii8xMDAyMjk4NjEvMjcwNzI0MTcxLTUxZDcwYzU0LWM3ZjItNDAwZi05MTBiLTc1YWI0NTNhNzAzMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwMVQxMTQ5MDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNmRlNjI1MjM3NmYxZGNkZTUwYTJmODc1OTg3MzVhMTJhYzhkZTUzY2I5N2MwZTVmNGJjODlmYWRmMzk3YWYwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.rjGEXrSVVoKQQ0n6RGFXXitQpAO1voGfJwA1LinNP4s)
> 
> ![Screenshot 2023-09-26 181258](https://private-user-images.githubusercontent.com/100229861/270724181-c9556cb1-0b8e-4926-af88-b4d8866a402b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ1NjQ0NDUsIm5iZiI6MTcxNDU2NDE0NSwicGF0aCI6Ii8xMDAyMjk4NjEvMjcwNzI0MTgxLWM5NTU2Y2IxLTBiOGUtNDkyNi1hZjg4LWI0ZDg4NjZhNDAyYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwMVQxMTQ5MDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yMDcyODNhZDg1ZTBiZGQxYWQ1YjUxY2JlYmU1ZjZlMDc3Y2YxMTNlNTMwNmFmNTMzNjFkYTI5NDkyMzA2MmMyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.jBMylXfJ0Z7xurQjDCWi1SXK3mlQ45Ct7HDcXN7eYTo)
> 
> ### Steps to reproduce
> Create a new scene with the parallax background node , add a parallax layer child Node , add a png to the parallax layer , make the png as big as the camera (as big as the zone outlined with blue) , if you try to mirror the parallax layer it wont work. if you then add that scene to some other scene , it causes issues. i added the project and you can see for yourself. the main scene already has the Background Scene which makes the Play button bugged.
> 
> ### Minimal reproduction project
> [Bug report.zip](https://github.com/godotengine/godot/files/12729817/Bug.report.zip)

Its probably because of the integrated graphics card Intel(R) HD Graphics 520. change the rendering method to gl_compatibility in project setting.

![image](https://github.com/godotengine/godot/assets/94551338/9dd0d1b0-f316-424c-874a-efb9be54e4fb)

Project > Project Settings... > General Tab > Rendering > Renderer > Change Rendering Method to gl_compatibility

**Comment by JJJayw** [comment] 2025-05-04 16:50
You can try placing the Sprite from outside the screen range instead of from the starting position of the screen. Although it cannot eliminate the problem, it can work.
