### ISSUE TITLE
Crash after changing theme settings

### ISSUE THREAD

**Issue by William-Owen** [godotengine/godot#67028] opened 2022-10-07 14:06 UTC
### Godot version

4.0.beta2

### System information

Windows 11, Nvidia RTX3090, Froward +

### Issue description

After opening up the theme settings and changing between the themes Godot closed without warning or error.

### Steps to reproduce

1. Run Godot.
2. Editor > Editor Settings > Theme.
3. Select a different option for presents.
4. Repeat step thee multiple times (approximately 6).

Expected behaviour: Changing the theme repeatedly to explore the different theme options.
Actual behaviour: After multiple changes (approximately 6) Godot closes without warning. Upon reloading Godot the previous changes are still present.

### Minimal reproduction project

Empty project.

**Comment by akien-mga** [comment] 2022-10-07 14:11
Duplicate of #59798.

**Closed by akien-mga** 2022-10-07 14:11 UTC
