### ISSUE TITLE
C#: Project failed to build, "A Godot Engine build callback failed"

### ISSUE THREAD

**Issue by 11clock** [godotengine/godot#23562] opened 2018-11-07 03:14 UTC
**Godot version:**
3.1 alpha 2

**OS/device including version:**
Windows 10

**Issue description:**
My working alpha 1 project fails to build in alpha 2, without a specified reason.

![image](https://user-images.githubusercontent.com/21234930/48108459-0bbee900-e1f8-11e8-88bc-8a6966b9ecb9.png)

**Steps to reproduce:**
Try building the attached project in alpha 2.

[BeardHeroes.zip](https://github.com/godotengine/godot/files/2555901/BeardHeroes.zip)

**Comment by Grosskopf** [comment] 2018-11-07 13:38
i'm guessing .local/share/mono :) works now

**Comment by 11clock** [comment] 2018-11-09 03:18
@David-Ochoa Didn't work for me.

**Comment by daimeng** [comment] 2019-02-08 06:45
Getting this issue in Godot v3.1 beta 3 x64 mono.
I have Mono 5.18 SDK installed on a Windows x64 platform.

Previously followed directions here: https://github.com/godotengine/godot/issues/20013
This allowed me to get farther and not have ~20 errors on opening editor or trying to build.

Now I have the 1 Error above. Switching to VS Build seems to work also for me.

In my error log on build I see this #23825

**Comment by neikeq** [comment] 2019-02-11 20:21
I'm closing this as a duplicate of #23825. Let me know if that's not the case.

We're defaulting to `MSBuild (VS Build Tools)` where the problem is not present.

**Closed by neikeq** 2019-02-11 20:21 UTC
Labels: bug, topic:mono
