### ISSUE TITLE
class_name: "Class '_' could not be fully loaded"

### ISSUE THREAD

**Issue by 11clock** [godotengine/godot#22135] opened 2018-09-16 01:08 UTC
**Godot version:**
3.1 Alpha

**OS/device including version:**
Windows 10

**Issue description:**
Every class I export with "class_name" gives me the specified error when I attempt to reference them in other scripts.

```
extends Node2D
class_name Space

var row:int
var col:int

var piece:Piece setget SetPiece
func SetPiece(piece:Piece):
	self.piece = piece
	add_child(piece)
	piece.position = Vector2(0, 0)
	piece.space = self
	

func _ready():
	pass
```
![5998dd27f3413206978a27c0951810aa](https://user-images.githubusercontent.com/21234930/45591824-3a17fa80-b912-11e8-9ab0-327dda45b62a.png)

EDIT: I did some testing and it looks like that class_name breaks when you have references to two different exported classes in your code. In other words, you can only have one exported class in your whole project.

**Comment by vnen** [comment] 2018-09-16 01:27
The error says there's an error or a cyclic dependency (I actually need to change this error, because not only inheritance can cause this). I need a sample project with a complete reproduction to see if this is not an issue in the code, because the sample code is not complete (I don't know what `Piece` is).

It's very easy to make cycles when using `class_name` as types, and with `is` and `as` too.

**Comment by 11clock** [comment] 2018-09-16 01:31
@vnen 
[BeardHeroes.zip](https://github.com/godotengine/godot/files/2386230/BeardHeroes.zip)

**Comment by PLyczkowski** [comment] 2018-09-20 23:27
Why is referencing each other class_types cause inheritance issues? It's not inheritance after all... Inheritance comes from the extends keyword, unless I misunderstand.

I try all the time to use static typing between classes that reference each other and get the mentioned error.

**Comment by vnen** [comment] 2018-09-21 00:13
@PLyczkowski as I said, I will change the error message because not only inheritance can cause this. The cause is cyclic _dependency_.

**Comment by vnen** [comment] 2018-09-21 14:49
The problem is the way GDScript is wired: it needs the file fully compiled in order to use it in other scripts. And to fully compile the script, it needs first to fully compile the dependencies. So if any dependency also depend on the current script (that is not yet fully compiled), it won't be able to resolve the types.

This was _always_ a problem. It's just exacerbated now with typing because there are many more ways to create cycles.

Note that other languages have similar issues. C++ solves this by using definitions in headers (and even with that it can create unresolvable cycles).

In order to fix this we need to change how GDScript works, and it's not the time to do it now.

**Comment by PLyczkowski** [comment] 2018-09-21 15:36
I see, and thanks for explaining.

**Comment by 11clock** [comment] 2018-09-21 17:09
@vnen In the mean time, what do you recommend we do to have two-way references? Because this is a very common requirement, like in my case where a board game space and a game piece need references to each other.

In the meantime I will just be using C#, which doesn’t have such issues.

**Comment by TextusGames** [comment] 2018-12-06 15:49
Will with be fixed?

**Comment by vnen** [comment] 2018-12-06 23:23
I think this was fixed by #23789

**Comment by vnen** [comment] 2018-12-06 23:31
This is looks like a duplicate of #21461. And it's not really a bug, just that GDScript wasn't designed to handle circular references, since it never had class names and static typing until now.

**Comment by akien-mga** [comment] 2018-12-17 09:34
Closing as duplicate of #21461.

**Closed by akien-mga** 2018-12-17 09:34 UTC
Labels: bug, topic:gdscript

**Comment by michasng** [comment] 2020-03-04 18:17
> @vnen In the mean time, what do you recommend we do to have two-way references? Because this is a very common requirement, like in my case where a board game space and a game piece need references to each other.
> 
> In the meantime I will just be using C#, which doesn’t have such issues.

Simply don't use statically typed variables then.

**Comment by badunius** [comment] 2020-05-09 05:41
> 
> 
> @PLyczkowski as I said, I will change the error message because not only inheritance can cause this. The cause is cyclic _dependency_.

It's been 20 months and you didn't. Great job.
Also, I'm getting this message without any cyclic dependencies, just two classes extending same parent.

**Comment by akien-mga** [comment] 2020-05-09 07:52
@badunius We could do without your passive aggressiveness, thanks.

**Comment by badunius** [comment] 2020-05-09 08:09
@akien-mga I know, I know. And I could go without being misled. I can't help but picture an "American Chopper" meme in my head: —You have an error! — I don't! — You have an error! — I checked twice, there's no error!

And then I google this.

P.S. I'm not passive aggressive. I'm just trying to stay polite while being aggressive due to frustration.

**Comment by marcelocg** [comment] 2020-07-10 12:41
Just faced this error. I have 3 scripts. One of them is just a bunch of constants to be used in other scripts. The two other scripts do use these constants and I started to see the error. After lots of fighting, closing the editor and then reopening it got me rid of the infamous message,

**Comment by DJKero** [comment] 2020-07-14 01:18
I'm having this same issue too, can't use class_names in the way they're meant to, lol

**Comment by Mikeysax** [comment] 2021-08-29 13:35
I've noticed if I attempt to use a custom class as a type, I need to restart the editor for the error to go away. Especially if I'm using that class as part of defining a type for a given argument in the init of another class.

**Comment by superyuuki** [comment] 2022-10-16 23:10
This is still an issue

**Comment by maktoobgar** [comment] 2023-01-05 09:16
Yes yes...
This is still an issue in godot v3.5.1-stable.
