### ISSUE TITLE
Editor: macOS Project Settings window does not spawn in correct position 

### ISSUE THREAD

**Issue by ztc0611** [godotengine/godot#68216] opened 2022-11-03 16:23 UTC
### Godot version

4.0.beta4.official

### System information

macOS Ventura 13.0, Apple M1

### Issue description

The Project Settings window does not spawn correctly if you have two monitors, and will be placed in an inaccessible position in some circumstances. It will log an error in the console about the window being spawned at an invalid position. The editor is then locked and must be force quit with activity monitor.

<img width="1508" alt="image" src="https://user-images.githubusercontent.com/28269330/199775741-f6438302-10f6-436e-ac63-065cf11cc535.png">
Had to take this one with my phone because attempting to screenshot this produces a corrupted screenshot.
<img width="1508" alt="image" src="https://user-images.githubusercontent.com/28269330/199776161-0eb367ea-1b9c-466d-80df-2db339ac38bc.JPG">
My display setup
<img width="211" alt="image" src="https://user-images.githubusercontent.com/28269330/199776534-cc1d8f15-687f-4523-8a7d-51d84c7b52ea.png">

### Steps to reproduce

I am unsure about which specific monitor configurations it requires, but considering it appears to be improperly using virtual desktop coordinates it should occur on more than it doesn't. In my situation, this only occurs if Godot is open on the bottom, smaller monitor.

### Minimal reproduction project

Any project.

**Comment by Calinou** [comment] 2022-11-04 19:54
Can you reproduce this after enabling the **Single Window Mode** editor setting then restarting the editor?

**Comment by ztc0611** [comment] 2022-11-07 16:23
@Calinou No, but it spawns at the bottom right of my Godot window instead of the center.

**Comment by muchitto** [comment] 2022-11-22 18:29
I have the same problem. I have MacOS 13.0.1 and an external monitor and the Macbook monitor.

It just says this and does not show the window:

![Screenshot 2022-11-22 at 20 27 02](https://user-images.githubusercontent.com/359786/203392875-48102d42-352e-4b4f-9a97-f1b0f4455026.png)

**Comment by lostminds** [comment] 2022-12-23 09:04
Isn't this a more general issue that windows can be placed in invalid locations, and not just specific to the macOS project settings panel? In other words that we should never allow windows being placed completely outside all screens. Godot seems to catch it already since you're getting this error, but I think it should then also move the window to a valid location on screen to avoid this type of situation. 

I'm not sure if this is the cause in this case, but developing non-godot desktop apps I've run into this issue in cases when an app is trying to restore window locations for a user based on a previous monitor setup that has now changed (for example on an external monitor that is now not connected).

**Comment by taffyko** [comment] 2023-02-04 02:53
> I'm not sure if this is the cause in this case, but developing non-godot desktop apps I've run into this issue in cases when an app is trying to restore window locations for a user based on a previous monitor setup that has now changed (for example on an external monitor that is now not connected).

I'm very certain that this is the case.
Getting the same issue on GNU/Linux `6.1.6-arch1-3 #1 x86_64` (using KDE)

I frequently switch between these two monitor arrangements:

1. ![image](https://user-images.githubusercontent.com/89940937/216742106-0a8cbcd1-bd4a-4692-9b3d-468d80dff28e.png)
2. ![image](https://user-images.githubusercontent.com/89940937/216741810-9fed0ddf-baab-4744-8d67-c557788fe302.png)

If the Project Settings window was last open on the top-left monitor (monitor arrangement 1) and I subsequently reopen Project Settings after switching to monitor arrangement 2 — It still spawns at those same old coordinates, which are now off-screen:

![image](https://user-images.githubusercontent.com/89940937/216741837-26cb02fc-d22d-41bc-b0c9-a0496197080f.png)

Seems like the last location of windows like Project Settings is remembered persistently, even after restarting Godot.

**Comment by ztc0611** [comment] 2023-06-16 00:52
I've not run into this issue since 4.0 officially came out. I'm not sure if it was fixed or if it's just harder to cause. Anyone else in here still experiencing the issue? @muchitto?

**Comment by akien-mga** [comment] 2023-06-16 07:45
Thanks for the update, assuming fixed in 4.0. If anyone still reproduces it, please let us know.

**Closed by akien-mga** 2023-06-16 07:45 UTC
Labels: bug, platform:macos, topic:porting, confirmed
