### ISSUE TITLE
Right Edge of Android Editor Cut Off

### ISSUE THREAD

**Issue by DylanCheetah** [godotengine/godot#61208] opened 2022-05-19 23:52 UTC
### Godot version

3.5.rc1

### System information

Android 10, Google G7 Play

### Issue description

When I start the editor, the right edge of the UI is cut off by the edge of the screen. This makes it impossible to create or open a project.

![Screenshot_20220519-143644](https://user-images.githubusercontent.com/49259114/169422291-e967eaa2-a984-4144-a42b-3ec55e4ff877.png)

### Steps to reproduce

Start the editor.

### Minimal reproduction project

N/A

**Comment by Calinou** [comment] 2022-05-20 00:52
Duplicate of https://github.com/godotengine/godot/issues/60728.

**Closed by Calinou** 2022-05-20 00:52 UTC
