### ISSUE TITLE
Duplicated collision shape changes size altogether with all its copies

### ISSUE THREAD

**Issue by z80** [godotengine/godot#42443] opened 2020-10-01 00:06 UTC
Godot build "3.2.3-stable" on Windows 10

**Issue description:**
If collision shape is duplicated its size change affects all other copies. No matter which copy is resized, all copies are resized simultaneously. See the attached GIF.

**Steps to reproduce:**
1) Create a rigid body with box collision shape and box MeshInstance. 
2) Duplicate (Ctrl+D) the rigid body. 
3) Move it to a different place to be able to see both.
4) Drag visual size controls via mouse.

![_dimensions_change_simultaneously](https://user-images.githubusercontent.com/1449921/94752108-2136e200-033f-11eb-80ce-03b75a4c33c4.gif)

**Comment by EricEzaM** [comment] 2020-10-01 04:12
This is expected. In the inspector go to the shape resource and select 'make unique'.

**Comment by madmiraal** [comment] 2020-10-01 10:03
As @EricEzaM points out, this is by design.

Closing as not a bug.

**Closed by madmiraal** 2020-10-01 10:03 UTC
