### ISSUE TITLE
When closing the editor Godot stops working

### ISSUE THREAD

**Issue by henriiquecampos** [godotengine/godot#5664] opened 2016-07-12 23:38 UTC
**Operating system or device - Godot version:**
Windows 10 - Godot 2.1.0 Beta

**Issue description** (what happened, and what was expected):
Everytime I close the editor it just stop working. It also happens if I "Quit to Project List".

**Steps to reproduce:**
Open any project, close the editor, click OK on the dialog.
or
Go to Scene>Quit to Project List (also Shift + Ctrl + Q shortcut)

**Link to minimal example project** (optional but very welcome):

**Comment by vnen** [comment] 2016-07-13 00:18
BTW this is recent, I noticed a couple of days ago, but not sure what's causing it. I'll try to bisect it.

**Comment by vnen** [comment] 2016-07-13 01:37
Bisecting gave this as a first bad commit: 3b7b581d63053b9cf599c208c2d79318abba40a3

**Comment by vnen** [comment] 2016-07-13 04:15
This thing crashes on the exit procedure. It crashes [here](https://github.com/godotengine/godot/blob/5545afd52b912722bbdb6e412cce9593857c5726/core/safe_refcount.cpp#L52) with an invalid memory pointer.

Since the added class in 3b7b581 has no destructor, my guess is that some objects are not properly freed from memory.

**Comment by vnen** [comment] 2016-07-14 00:33
This seems beyond my debugging skills. @TheHX, since you made the commit, do you have any idea of what could be causing this?

**Comment by TheHX** [comment] 2016-07-14 10:20
By the local of crash, i think the problem is a bad use of StringName, by my part. I'll give a check on this when i get home, it's probably a simple fix.

**Comment by TheHX** [comment] 2016-07-14 15:14
I've found a orphan ```StringName``` caused by this commit, and maybe is the source of the problem. I've pushed a fix for this problem on my fork of the engine:

https://github.com/TheHX/godot/tree/issue-5664

Could test it @vnen, please. I don't have any windows machine, and i cannot reproduce this on linux.

**Comment by vnen** [comment] 2016-07-14 15:44
@TheHX I can confirm it solves the crash :smiley:

**Closed** 2016-07-14 17:29 UTC
Labels: bug, confirmed, platform:windows, topic:core
