### ISSUE TITLE
tile_modulate does not affect shader built-in MODULATE

### ISSUE THREAD

**Issue by Hex4F** [godotengine/godot#45677] opened 2021-02-03 06:27 UTC
**Godot version:**
3.2.3
GLES2 and GLES3

**OS/device including version:**
Windows 7, Radeon RX 570

**Issue description:**
TileSet has a modulation color for each tile, tile_modulate. However, it doesn't work if that tile has a ShaderMaterial. Within the shader, MODULATE is set to the TileMap's modulate color if it has one, unaffected by tile_modulate.

**Steps to reproduce:**
Set a material and a modulation color for the same tile.

**Minimal reproduction project:**
[TileModulate.zip](https://github.com/godotengine/godot/files/5916503/TileModulate.zip)

**Comment by clayjohn** [comment] 2021-02-03 06:36
``tile_modulate`` modulates the tiles by setting the vertex color. Your ShaderMaterial ignores the vertex color.

To make it work as intended you just have to include the vertex color like so:
```
COLOR = texture(TEXTURE, UV) * MODULATE * COLOR;
```

**Comment by Hex4F** [comment] 2021-02-03 08:14
You're absolutely right. I should be using COLOR instead of MODULATE, and if I had been doing so correctly there wouldn't be a problem.

Since the title is completely incorrect I'll change it. I don't know if this constitutes an issue anymore, but since the way tile_modulate works is a little confusing I'll leave it as you tagged it.

**Comment by akien-mga** [comment] 2022-01-24 22:18
Fixed by #57156.

**Closed by akien-mga** 2022-01-24 22:18 UTC
Labels: topic:rendering, junior job, documentation, topic:2d
