### ISSUE TITLE
Export to Mac produces 0-length files

### ISSUE THREAD

**Issue by tliron** [godotengine/godot#40192] opened 2020-07-07 21:18 UTC
**Godot version:**
3.2.2.stable.official

**OS/device including version:**
Fedora 32 64bit

**Issue description:**
Exporting using the standard templates. Linux X11 and Windows exports work. But when I export Mac I get a zip file in which the zipped files are zero length, so it cannot be run.

**Steps to reproduce:**
Open the project, export to Mac, check out the exported zip and see that though the directory structure is correct the files are empty.

**Minimal reproduction project:**
Attached is the "Dodge the Creeps" tutorial as I created it.

[dodge.zip](https://github.com/godotengine/godot/files/4887212/dodge.zip)

**Comment by akien-mga** [comment] 2020-07-08 04:44
Duplicate of #39931, this is fixed in the `3.2` branch and I will soon release 3.2.3 including it and other fixes.

In the meantime, since the problem is with the Zip flags and not the files themselves, you should be able to work it around by unzipping with a different tool than macOS' default archiver, make the Godot binary executable (which is missing) and re-zip.

**Closed by akien-mga** 2020-07-08 04:44 UTC

**Comment by tliron** [comment] 2020-07-08 14:28
I don't think this is a duplicate of that issue. I am not unzipping on Mac, but rather on Linux. The files are there in the zip but they are zero length.

**Comment by akien-mga** [comment] 2020-07-08 14:49
See https://github.com/godotengine/godot/issues/39931#issuecomment-651340043

It's a symptom of the same bug, which was fixed in #39977.

**Comment by tliron** [comment] 2020-07-08 16:37
Awesome, thanks! And I found a workaround and more details. Will post it here in case someone searches and find this:

The issue in Fedora Linux, specifically, was the GNOME Archive Manager app. It seems to have the same or similar problem as the Mac default archiver, whereby zip entries with bad attributes don't get read correctly. In the case of GNOME Archive Manager it does show those entries, but as length 0. And if you try to extract them, they will be skipped.

_However_, the "unzip" command line tool is more forgiving. The workaround then is simple in Linux: unzip from the command line, and then you can zip again (you can zip again using GNOME Archive Manager if you want, the files are good now).
