### ISSUE TITLE
Imported pixel art preview blur

### ISSUE THREAD

**Issue by PoisonousGame** [godotengine/godot#65897] opened 2022-09-16 12:32 UTC
### Godot version

4.0 beta1

### System information

Win11  GeForce GTX1060 6GB

### Issue description

Imported pixel art preview blur
![image](https://user-images.githubusercontent.com/39994989/190639267-d6b64bdf-2e89-480b-8e49-bf5b036991e0.png)

### Steps to reproduce

Imported pixel art, view preview

**Comment by Calinou** [comment] 2022-09-16 13:28
Duplicate of https://github.com/godotengine/godot/issues/60150.

**Closed by Calinou** 2022-09-16 13:28 UTC
