### ISSUE TITLE
Setting NodePath script variable from the editor is broken

### ISSUE THREAD

**Issue by m4nu3lf** [godotengine/godot#19746] opened 2018-06-24 09:31 UTC
**Godot version:**
Custom Build 012e212

**OS/device including version:**
Arch Linux

**Issue description:**
Setting NodePath script variable from editor is broken

**Steps to reproduce:**
Create a script exporting a NodePath variable and set it to an existing node in the editor

**Minimal reproduction project:**
[test.zip](https://github.com/godotengine/godot/files/2130640/test.zip)

**Comment by groud** [comment] 2018-06-24 16:09
Duplicate of #19712

**Closed by groud** 2018-06-24 16:09 UTC

**Comment by m4nu3lf** [comment] 2018-06-24 18:53
@groud I though I had written it in the description, but I actually didn't. I'll fix that
