### ISSUE TITLE
SSAO produces dark lines along the screen center in Editor

### ISSUE THREAD

**Issue by Swarkin** [godotengine/godot#70785] opened 2022-12-31 22:54 UTC
### Godot version

v4.0.beta9.official

### System information

Windows 10, Nvidia GPU

### Issue description

This seems to only happen inside the Editor, not when playing.

https://user-images.githubusercontent.com/102416174/210156999-1e326ce3-8dc5-4153-8856-6aafd9e76f33.mp4

### Steps to reproduce

1. Enable SSAO
2. Look at different objects

### Minimal reproduction project

N/A

**Comment by Calinou** [comment] 2022-12-31 23:11
Duplicate of https://github.com/godotengine/godot/issues/62881.

**Closed by Calinou** 2022-12-31 23:11 UTC
