### ISSUE TITLE
Doing a Save operation on Floating Editor opens main editor window

### ISSUE THREAD

**Issue by ultimateprogramer** [godotengine/godot#78506] opened 2023-06-21 07:49 UTC
### Godot version

4.1.beta2

### System information

Windows 11 - 4.1 beta2 - Compatibility

### Issue description

When editing code on a floating Code Editor Window and hitting Ctrl + S, the focus is taken back to the main Editor Window and you have to manually focus back onto the Floating Editor Window.

### Steps to reproduce

- Open Code Editor
- Click on "Make Floating"
- Edit some code
- Hit "Ctrl + S"
- Main Editor Window will show up instead of staying on Code Editor

### Minimal reproduction project

N/A

**Comment by akien-mga** [comment] 2023-06-21 07:58
CC @trollodel @KoBeWi

**Comment by KoBeWi** [comment] 2023-06-21 10:39
Probably caused by ProgressDialog, which returns focus to EditorNode once it disappears.

**Comment by trollodel** [comment] 2023-07-23 14:04
Isn't this a duplicate of #78672 (which has more information)?

**Comment by KoBeWi** [comment] 2023-07-23 14:35
Yes.

**Closed by KoBeWi** 2023-07-23 14:35 UTC
Labels: bug, topic:editor, usability
