### ISSUE TITLE
Tooltip do not appear on secondary screens

### ISSUE THREAD

**Issue by BraindeadBZH** [godotengine/godot#55961] opened 2021-12-15 14:59 UTC
### Godot version

v4.0.dev.20211210.official [21b81998b]

### System information

Windows 10

### Issue description

I have two screens connected to a laptop, one of them is defined as the "main display" in the Windows settings.
My laptop is sitting in-between the two screens, one on the right, one on the left (main display).
The laptop screen is a HiDPI 4K panel at 200% scale, the two other screens are 1920x1200 resolution at 100% scale.

If the Godot editor is moved to a screen that is not the "main display", the tooltips do not show, for example in the properties inspector.

### Steps to reproduce

1. Open Godot, it automatically opens on the main display
2. Start editing a project
3. Hovering over properties in the inspector pops up tooltips
4. Move the editor window to a secondary screen
5. The same tooltips do not show up anymore
6. Move the editor window back the main screen
7. The tooltips work again
8. Move the editor window to another secondary screen
9. The tooltips stop working

### Minimal reproduction project

Not project dependent.

**Comment by KoBeWi** [comment] 2021-12-15 16:19
This should've been already fixed by #41395

**Comment by KoBeWi** [comment] 2022-02-27 22:33
Can't reproduce in [3fab862](https://github.com/godotengine/godot/commit/3fab862c590b706aa5c6211415d3854140dbc5d3)

**Closed by KoBeWi** 2022-02-27 22:33 UTC
Labels: bug, topic:porting
