### ISSUE TITLE
Godot 4 Crash on Startup

### ISSUE THREAD

**Issue by vailrahmatulin** [godotengine/godot#66521] opened 2022-09-28 02:02 UTC
### Godot version

v4.0.beta1.official

### System information

Arch Linux; rolling GNOME 42.4 Wayland

### Issue description

handle_crash: Program crashed with signal 11
Engine version: Godot Engine v4.0.beta1.official (20d6672846b3fd1537603ac080116dcc914c10e3)
Dumping the backtrace. Please include this when reporting the bug on: https://github.com/godotengine/godot/issues
[1] /lib/libc.so.6(+0x38a00) [0x7f9d5bbeda00] (??:0)
[2] /usr/lib/libvulkan_radeon.so(+0x138937) [0x7f9d524d4937] (??:0)
[3] /usr/lib/libvulkan_radeon.so(+0x11ebb9) [0x7f9d524babb9] (??:0)
[4] godot4() [0x1900981] (??:0)
[5] godot4() [0x18af3cd] (??:0)
[6] godot4() [0x3aa6dd5] (??:0)
[7] godot4() [0xac7c07] (??:0)
[8] godot4() [0xa89f91] (??:0)
[9] godot4() [0xa7d5c2] (??:0)
[10] /lib/libc.so.6(+0x23290) [0x7f9d5bbd8290] (??:0)
[11] /lib/libc.so.6(__libc_start_main+0x8a) [0x7f9d5bbd834a] (??:0)
[12] godot4() [0xa88121] (??:0)
-- END OF BACKTRACE --
================================================================
fish: Job 1, 'godot4' terminated by signal SIGABRT (Abort)

### Steps to reproduce

Error on startup

**Comment by Calinou** [comment] 2022-09-28 06:17
Duplicate of https://github.com/godotengine/godot/issues/65409.

**Closed by Calinou** 2022-09-28 06:17 UTC
