### ISSUE TITLE
Vulkan: Light2d Blend Modes do not behave correctly

### ISSUE THREAD

**Issue by dweremeichik** [godotengine/godot#49922] opened 2021-06-26 05:11 UTC
### Godot version

4.0.dev (fdccc0b)

### System information

Windows 10, Vulkan, GTX 1070

### Issue description

Setting a Light2d to Mix blend mode does not produce the expected results:
3.2.3:
![Light Mix test 3 3 2](https://user-images.githubusercontent.com/4079608/123502519-12096a00-d61b-11eb-893b-306e0191c958.PNG)

4.0.dev:
![Light Mix test 4 0 dev](https://user-images.githubusercontent.com/4079608/123502527-19307800-d61b-11eb-8771-578f31af735a.PNG)

### Steps to reproduce

1. Create a scene with a background and a Light2d (point or directional).
2. Set the Light2d to Blend Mode "Mix".

### Minimal reproduction project

Without explicitly setting it, 4.0 changes the light source back to add mode on import.
[Light Mix Test 3.2.3.zip](https://github.com/godotengine/godot/files/6719606/Light.Mix.Test.3.2.3.zip)
[Light Mix Test 4.0.dev.zip](https://github.com/godotengine/godot/files/6719607/Light.Mix.Test.4.0.dev.zip)

**Comment by girng** [comment] 2021-11-18 03:59
I think my issue https://github.com/godotengine/godot/issues/53660 is a duplicate of this.  Same exact effect. 

GameFromScratch's [video](https://youtu.be/_VR-xHsio78) showcasing 4.0 and the new lighting system worked good. So somethig must have happened (just saw it has a regression label, that's good!)

**Comment by Calinou** [comment] 2021-11-18 17:36
> GameFromScratch's video showcasing 4.0 and the new lighting system worked good. So somethig must have happened (just saw it has a regression label, that's good!)

Indeed, the 2D lighting system broke in various ways at some point earlier this year (or last year). It would be good if someone could bisect it, although it'll require a lot of build steps (likely 30 or more).

**Comment by girng** [comment] 2021-11-30 04:20
@Calinou To my surprise, after compiling a bunch of different builds starting from March 2021, all the way back to December, 2020 (when GFS made his video). I found   the `PointLight2D` [issue] (https://i.gyazo.com/b2a37ba99645e79b4a897f448f1eed1c.mp4) was apparent on all. I also noticed on GFS's video he used a `CanvasTexture` and mapping images.

I'm not sure if Light2D was changed or if this a documentation issue and maybe PointLight2D needs to be setup differently than before. Although we should just be able to select a light texture like before, but with Vulkan and single pass lighting, there might be more the user needs to do

**Comment by Calinou** [comment] 2021-11-30 16:54
> Although we should just be able to select a light texture like before, but with Vulkan and single pass lighting, there might be more the user needs to do

The setup process remains exactly the same, even if Vulkan and single-pass lighting is used behind the scenes.

**Comment by ZeEndy** [comment] 2022-05-11 07:22
> @Calinou To my surprise, after compiling a bunch of different builds starting from March 2021, all the way back to December, 2020 (when GFS made his video). I found the `PointLight2D` [issue](https://i.gyazo.com/b2a37ba99645e79b4a897f448f1eed1c.mp4) was apparent on all. I also noticed on GFS's video he used a `CanvasTexture` and mapping images.
> 
> I'm not sure if Light2D was changed or if this a documentation issue and maybe PointLight2D needs to be setup differently than before. Although we should just be able to select a light texture like before, but with Vulkan and single pass lighting, there might be more the user needs to do

The build that still had a working 2d light system dates all the way back 28 November 2020 when it was shown in the [article about godot 4.0's improvments](https://godotengine.org/article/godots-2d-engine-gets-several-improvements-upcoming-40) , so I think thats a good starting point to do what @Calinou suggested

**Comment by ZeEndy** [comment] 2022-05-11 07:25
Added on to that I think it would also have the code to fix #55806

**Comment by h0lley** [comment] 2022-05-16 00:41
actually this didn't break - it was broken since implementation.
it still works in just the same way as when Juan posted that article and GameFromScratch made that video.
the difference is that they are using normal maps.

so this issue is really not about blend mode mix specifically, but about different behavior when omitting normal maps.

![image](https://user-images.githubusercontent.com/23386940/168501920-8e52910c-fdce-42ec-a82d-e5f46ea37a84.png)


> Added on to that I think it would also have the code to fix https://github.com/godotengine/godot/issues/55806

this one actually did work initially with vulkan and broke later. I've identified the commit and posted it in that issue.

**Comment by sakrel** [comment] 2022-07-19 14:59
I tried to fix this, but couldn't get it quite right. While mix and add blend modes look similar to what they looked like in godot 3.x, subtract looks cleary off. If anybody wants to have a look, this is the branch: https://github.com/sakrel/godot/tree/vulkan-fix-2d-light-blending

**Comment by bitbrain** [comment] 2022-08-21 13:56
There are definitely still issues with this. In Godot 3 it looks like this:
![Capture2](https://user-images.githubusercontent.com/822035/185794351-e5fb28fd-2a34-4a26-b924-d868697717c1.JPG)

While the same-ey setup in Godot 4 looks like this:

![Capture](https://user-images.githubusercontent.com/822035/185794350-ddbb7a4e-1843-48d5-9d95-cd74de22d936.JPG)

perhaps related to https://github.com/godotengine/godot/issues/58688?

**Comment by PetrVopa** [comment] 2022-08-21 19:13
from what I remember when creating #58688 it is the same thing

**Comment by PoisonousGame** [comment] 2022-09-12 03:39
In godot3, add a CanvasModulate node, and then a PointLight2d node. Set the CanvasModulate color to black and the light will illuminate things in range, this doesn't work in godot4. The documentation is also not updated and the 2D lights don't seem to be maintained!

**Comment by dweremeichik** [comment] 2022-09-12 20:37
@PoisonousGame this should probably be under a different issue (or multiple if necessary). If there is no specific fitting issue that is already opened with a minimal reproduction project, please feel free to create one. Please don't spam other issues with copy/paste.

Also note that Godot 4 is not production ready and anyone who is leading you to believe that it is; should not be doing so. With regards to documentation, it would be an effort in futility to "update" parts of it that are still subject to change/overhaul before release.

**Comment by h0lley** [comment] 2022-09-12 21:24
#58688 already exists which is most likely what PoisonousGame is referring to.
it was closed as duplicate of this issue. I'm uncertain if it really is a dupe though. I think once this issue is resolved, #58688 should be reassessed again.

**Comment by bitbrain** [comment] 2022-09-24 11:35
This commit https://github.com/godotengine/godot/commit/f123981a96c8ab7d7cb3e77ecbcf0048cb3b79e6 might contain some hints about what the issue might be.

**Closed** 2022-09-27 08:05 UTC
Labels: bug, topic:rendering, confirmed, regression, topic:2d
