### ISSUE TITLE
Duplicating Resource retains UID

### ISSUE THREAD

**Issue by Byteron** [godotengine/godot#55252] opened 2021-11-23 09:49 UTC
### Godot version

4.0.dev

### System information

Windows 11, AMD CPU & GPU

### Issue description

when a resource is duplicated, the UID is the same as for the original resource, resulting in only one resource being used when running the game even if you load the different duplicates from disk.

### Steps to reproduce

1) create some resource, e.g. a material
2) duplicate the resource
3) change the duplicate in some way
4) load both resource into the game
5) the different resources will appear the same in GD because the UIDs reference to the same imported resource.

**Comment by akien-mga** [comment] 2021-12-03 10:13
Duplicate of #54774.

**Closed by akien-mga** 2021-12-03 10:13 UTC
Labels: bug, topic:core, regression
