### ISSUE TITLE
Possible cyclic resource inclusion for .cs files

### ISSUE THREAD

**Issue by adikhel** [godotengine/godot#27257] opened 2019-03-20 07:10 UTC
**Godot version:**

Godot version 3.1

**OS/device including version:**

Windows 10 Desktop

**Issue description:**

I get possible cyclic resource inclusion for a .cs file. If I execute the project, it crashes Godot. The filename is same in Godot and the Windows File Directory.

**Steps to reproduce:**

**Minimal reproduction project:**

```
Godot Engine v3.1.stable.mono.official
(c) 2007-2019 Juan Linietsky, Ariel Manzur & Godot Contributors.
Switch Scene Tab
Another resource is loaded from path: res://Scripts/Main.cs (possible cyclic resource inclusion)
Switch Scene Tab
Switch Scene Tab
Another resource is loaded from path: res://Scripts/Main.cs (possible cyclic resource inclusion)
```

**Comment by neikeq** [comment] 2019-04-03 12:06
Can't do much without at least an example project and the steps to reproduce the issue.
The error message suggests it could be related to #17044 or #10946.

**Comment by nathanjwtx** [comment] 2019-04-30 12:04
This happens to me a lot but without any seeming consistency.

[(https://github.com/nathanjwtx/Jungle-Jump/tree/move_and_slide_snap](https://github.com/nathanjwtx/Jungle-Jump/tree/move_and_slide_snap)

Try making changes to SetMoveSlide(bool platform) in Player.cs, saving, and then switching back to the editor. It's been crashing/freezing a lot since I added that method.

`core/resource.cpp:79 - Condition ' exists ' is true` appears in the editor Output window. Sometimes it resolves itself other times not.

Godot 3.1.1 stable/Windows 10/VS Code/C#

**Comment by nathanjwtx** [comment] 2019-05-03 23:26
Godot has crashed on me nearly 2 dozen times today. I've now started seeing this error crop up:
```
ERROR: Another resource is loaded from path: res://player_animated.cs (possible cyclic resource inclusion)
   At: core/resource.cpp:79
ERROR: crop_from_point: Condition ' p_width <= 0 ' is true.
   At: core/image.cpp:965
erasing C:/Users/Nathan/Godot/Moving Platforms/.mono/metadata/scripts_metadata.editor
```

If there's any file that I can attach then please let me know how to find it. It **really** doesn't like me switching between external editor and main Godot window although I have had one back to back crash today; crash, restart, instantly froze again.

**Comment by nathanjwtx** [comment] 2019-05-05 14:16
Don't know if this log file helps or not

[2019_05_05 09.11.15 (6340).txt](https://github.com/godotengine/godot/files/3145614/2019_05_05.09.11.15.6340.txt)

**Comment by Larpon** [comment] 2019-06-04 19:27
I'm getting these when loading the same resource from different `Thread`s with both:
`ResourceLoader.load_interactive(path)`
and:
`ResourceLoader.load(path)`

**Comment by Spartan322** [comment] 2019-10-14 20:34
I've been getting
```
ERROR: set_path: Another resource is loaded from path: res://Source/Unit/SelectableGroup.cs (possible cyclic resource inclusion)
   At: core/resource.cpp:79.
```
```
ERROR: set_path: Condition ' exists ' is true.
   At: core/resource.cpp:79.
```
or
```
Mono: Unloading scripts domain...
ERROR: get_class: Condition ' !loaded ' is true. returned: __null
   At: modules/mono/mono_gd/gd_mono_assembly.cpp:376.
ERROR: get_class: Condition ' !loaded ' is true. returned: __null
   At: modules/mono/mono_gd/gd_mono_assembly.cpp:376.
```
in verbose logging.
Whenever my C# files are changed outside of Godot, it doesn't tend to crash Godot but instead freezes it where I need to kill it via a task manager. I'm using Linux with the official 3.1.1 mono release.

**Comment by Zireael07** [comment] 2019-10-15 06:35
@Spartan322 : I believe that's a separate issue?

**Comment by Spartan322** [comment] 2019-10-15 08:08
Maybe, it would help if I could actually get more verbose logging from Godot regarding Mono intercommunication, the only other thing I have is the Mono logs and Mono itself isn't the problem. Also the reason I'm unsure is that its a shared error with two other reports on this issue, if they're not associated with this issue (which we can't even determine) then I'm not the first to have these types of issues and I'm unsure where to put it and even more I'm not even sure how to report it better. Even weirder is I've yet to experience this problem inside Godot's text editor. Which suggests its Godot managing Mono very poorly at least for in the core/resource calls.

**Comment by Torguen** [comment] 2019-11-18 15:53
I am also getting this error.
If there is anything I can do to help I will be delighted.

![1](https://user-images.githubusercontent.com/19652075/69067726-e4fadb80-0a23-11ea-8452-4f1ca0a49607.png)

**Comment by akien-mga** [comment] 2020-01-15 11:09
Is this still reproducible in current 3.2 builds?

Note that this issue should stay about possible cycle resource inclusion for `.cs` files.

If you experience it with different kinds of files (e.g. `.png` files, which I've seen every now and then without clear explanations), please open another issue.

**Comment by Torguen** [comment] 2020-01-15 12:01
I continue to experience this error (3.2 beta 6 mono).
It happens when I edit the code of my .cs file and save the file, then when I activate the Godot window, the message appears:
![1](https://user-images.githubusercontent.com/19652075/72432359-221aea00-3797-11ea-9d8b-73443d343ddd.png)

**Comment by neikeq** [comment] 2020-01-16 20:40
This looks the same as either #10946 or #17044.

**Comment by neikeq** [comment] 2020-01-19 22:34
I'm changing the label as this is not a bug with the mono module but with godot core. And it may be a duplicate of the issues I mentioned.

**Comment by akien-mga** [comment] 2020-01-22 08:11
Closing as duplicate of #10946 then.

**Closed by akien-mga** 2020-01-22 08:11 UTC
Labels: bug, topic:core

**Comment by Torguen** [comment] 2020-01-22 09:36
It has been passed to milestone 4.0
I guess this is nothing serious.

**Comment by markdibarry** [comment] 2022-01-25 15:36
Still present in 4.0 alpha

**Comment by Calinou** [comment] 2022-01-25 16:35
@markdibarry Please open a new issue with a minimal reproduction project attached.
