### ISSUE TITLE
[3.5 Mac OS X] Flipping a filename case in FileSystem causes error

### ISSUE THREAD

**Issue by wyattbiker** [godotengine/godot#64863] opened 2022-08-25 00:57 UTC
### Godot version

v3.5.stable.official [991bb6ac7]

### System information

Mac OS X (Catalina) 10.15.7

### Issue description

Right clicking on a filename in the FileSystem panel and choosing Rename to flip the case of any letter in the name, will get you the error
`A file or folder with this name already exists.`

![image](https://user-images.githubusercontent.com/930478/186548943-40234ee2-49c7-4582-83d8-449baf87a4d4.png)

### Steps to reproduce

1. Open a project with files.
2. In the FileSystem right click and choose rename of any file
3. Flip the case of the first letter and click OK
4. You will get the popup message  `A file or folder with this name already exists.`

**Comment by akien-mga** [comment] 2022-08-25 05:48
Duplicate of https://github.com/godotengine/godot/issues/19592

**Closed by akien-mga** 2022-08-25 05:48 UTC
