### ISSUE TITLE
StyleBoxFlat setting any "corner radius" changes all "border width"

### ISSUE THREAD

**Issue by flurick** [godotengine/godot#16382] opened 2018-02-04 10:43 UTC
**Godot version:** 3.0 stable

Appears on two seperate machines: archlinux and windows10.

**Issue description:**

![godot-border-radius](https://user-images.githubusercontent.com/3645797/35776601-c85611ec-099f-11e8-9d73-23407083b275.png)

**Comment by akien-mga** [comment] 2018-02-13 10:40
CC @toger5

**Comment by toger5** [comment] 2018-11-26 02:06
@flurick Can u check it anti aliasing is activated? aa adds a faded additional border... And i think changing on corner_radius to != 0 activates it.

**Comment by Zylann** [comment] 2019-10-13 19:27
I have the same problem, trying to have a border only on two sides, but it's still drawing a thin line on the other sides:

![image](https://user-images.githubusercontent.com/1311555/66720654-b6239100-edf7-11e9-9d21-1e3c7ce6513f.png)

Tried without antialiasing but it's a bit ugly

![image](https://user-images.githubusercontent.com/1311555/66720666-d5bab980-edf7-11e9-96be-834a7358349f.png)

**Comment by toger5** [comment] 2019-10-22 12:05
The fix would be to add an if statement for the antialiasing faces are drawn in the correct color.
 - use the border color when boarder width > 0
 - otherwise use bg color

**Comment by ligazetom** [comment] 2020-01-06 14:56
@toger5 I'm looking to start contributing. Let's try it if it is not solved

**Comment by Calinou** [comment] 2020-01-06 17:36
I can't reproduce this on commit fa8366441, closing.

![Preview](https://user-images.githubusercontent.com/180032/71836012-531e5f00-30b3-11ea-8ad6-97e8bc4fa334.png)

![Inspector](https://user-images.githubusercontent.com/180032/71836035-63363e80-30b3-11ea-8861-a7830366475e.png)

**Closed by Calinou** 2020-01-06 17:36 UTC
Labels: bug, junior job, topic:gui
