### ISSUE TITLE
is_on_screen() not working on children of CanvasLayer

### ISSUE THREAD

**Issue by fredlim** [godotengine/godot#1269] opened 2015-01-19 16:53 UTC
If the parent node is CanvasLayer, the is_on_screen() will not work in child node.

More information. is_on_screen() will always return false if the parent node is CanvasLayer.

**Comment by reduz** [comment] 2015-02-15 14:31
you mean VisibilityNotifier::is_on_screen() ?

**Comment by akien-mga** [comment] 2015-11-08 16:05
Is this issue still valid in the current master branch?

**Comment by akien-mga** [comment] 2016-04-01 09:05
Could you provide steps to reproduce and/or a sample project that exhibits the issue?

**Comment by neikeq** [comment] 2016-04-01 10:44
I can reproduce this bug in the current master branch. Signals `_enter_screen` and `_exit_screen` won't work either.
Sample project (move the character inside and outside of the screen with the arrow keys): [SP_1269.zip](https://github.com/godotengine/godot/files/199411/SP_1269.zip)
- The player is child of _CanvasLayer_ by default. Nothing will be printed.
- Reparent the player to the root node so it's no longer a child of _CanvasLayer_. It should spam the Output with a lot of _"is_on_screen() returned true"_ messages.

**Comment by akien-mga** [comment] 2018-05-09 09:17
Just tested again with @neikeq's project. The bug is still reproducible in the 2.1 branch (pre-2.1.5), and fixed in the master branch. Closing as fixed in 3.0, feel free to comment if you would want a fix backported to the 2.1 branch (once identified, and if feasible).

**Comment by akien-mga** [comment] 2018-09-04 06:08
Test project for 3.x: [SP_1269_3.0.zip](https://github.com/godotengine/godot/files/2347347/SP_1269_3.0.zip)

I tested again and it's indeed fixed in the master branch (3.1), but still valid in 3.0.

**Comment by aaronfranke** [comment] 2018-12-10 01:49
Is the goal still to fix this in 3.0?

**Comment by akien-mga** [comment] 2018-12-10 07:08
It would be nice, if someone can identify what fixed the bug in the master branch, and that commit would be safe to backport.

**Comment by akien-mga** [comment] 2019-12-19 07:59
I'll close as fixed in 3.1, since we're about to release 3.2 there is little incentive for doing advanced bug fixing in the 3.0 branch. If anyone identifies what fixed the bug in 3.1, it might still be worth considering to cherry-pick.

**Closed by akien-mga** 2019-12-19 07:59 UTC
Labels: bug, confirmed, topic:core
