### ISSUE TITLE
OpenGL window rendering issue

### ISSUE THREAD

**Issue by BlueGameStudios** [godotengine/godot#72713] opened 2023-02-04 15:27 UTC
### Godot version

Godot 4 Beta 17

### System information

Windows 11, OpenGL, AMD Radeon RX 6700 XT

### Issue description

HOW IT SHOULD LOOK LIKE:
![image_2023-02-04_102145004](https://user-images.githubusercontent.com/120224184/216775333-346e0882-1ef8-481e-9c14-6741a1b704c9.png)

WINDOW MAXMIZED:
![image_2023-02-04_102043456](https://user-images.githubusercontent.com/120224184/216775273-5c2904a0-8237-4f59-85d3-a29414314a7d.png)

WINDOW RANDOM SIZE:
![image](https://user-images.githubusercontent.com/120224184/216775371-dbaaff18-d2a2-41df-9b36-5b1c68ad3fc1.png)

Also I have all setting on default except stretch mode, which is "canvas_items":
![image_2023-02-04_102340138](https://user-images.githubusercontent.com/120224184/216775429-2b898d35-7c82-4355-8e60-efd3018a9588.png)

### Steps to reproduce

Steps:
really none just make sure stretch mode is set to "canvas_items"

### Minimal reproduction project

[code_playground.zip](https://github.com/godotengine/godot/files/10608958/code_playground.zip)

**Comment by clayjohn** [comment] 2023-02-04 16:31
Duplicate of https://github.com/godotengine/godot/issues/71799

**Closed by clayjohn** 2023-02-04 16:31 UTC
