### ISSUE TITLE
Dictionary can't use keys such as 'continue' or 'else', etc..

### ISSUE THREAD

**Issue by prominentdetail** [godotengine/godot#68967] opened 2022-11-21 18:01 UTC
### Godot version

v4.0.beta.custom_build [0b958971f]

### System information

windows 10

### Issue description

Dictionary can't use keys such as 'continue', 'else', etc..

### Steps to reproduce

If you create a dictionary with those keys and try to assign values to them you'll get this error:

"Parse Error: Expected identifier after "." for attribute access."

### Minimal reproduction project

[dictionaryBug.zip](https://github.com/godotengine/godot/files/10059372/dictionaryBug.zip)

**Comment by Calinou** [comment] 2022-11-21 18:05
@prominentdetail Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

Which dictionary syntax are you using (traditional or Lua-style)?

**Comment by prominentdetail** [comment] 2022-11-21 18:12
Ok, updated with minimum reproduction project.

here's also screenshot:
![image](https://user-images.githubusercontent.com/10412778/203129361-c3b25ae3-ba1c-4967-a8dc-061e26aee377.png)

**Comment by Mickeon** [comment] 2022-11-21 18:57
I suppose in a warped sense I can imagine why. If that Dictionary were to be an Object with script attached, you may not name a property that way in GDScript, so by extension you shouldn't be able to refer to it, either. It's not exactly controllable, however, and different languages may have different reserved keywords. At least, as a workaround, you may refer to it with `test["continue"]`.

**Comment by AThousandShips** [comment] 2022-11-21 19:02
Can't you use things like `(1,2)` or `key 1` as dictionary keys as well? None of which are valid identifiers and can't be used to access members with this method

**Comment by AThousandShips** [comment] 2022-11-22 10:28
Note that gcc and clang does not throw a specific error for cases where a reserved keyword is used in a similar case, not sure about other languages, I don't know there's a specific need to add a special warning for this case

**Comment by AThousandShips** [comment] 2022-11-22 11:11
It does however work in 3.6 so it is a regression

**Comment by AThousandShips** [comment] 2022-11-22 12:11
In 3.6 you can name a method a reserved keyword, but the only way to call it from within the script is by calling it on `self`, this is also not allowed in 4.0, I think that doing anything to make 4.0 do this to match 3.x is not a good idea, unless we also bring those aspects in line with that

I feel it would cause new confusion, unless all uses of reserved keywords in these cases are allowed, with allowing dictionary keys but not object members or methods, it sounds like a pretty big set of changes to the code, with very limited actual use cases

**Comment by Mickeon** [comment] 2022-11-22 17:50
Now that I think of it, isn't this related to...?
- https://github.com/godotengine/godot/issues/61981#issue-1268742304

**Comment by Chaosus** [comment] 2022-11-24 11:18
Duplicate of https://github.com/godotengine/godot/issues/61981

**Closed by Chaosus** 2022-11-24 11:18 UTC
Labels: bug, discussion, topic:gdscript, regression
