### ISSUE TITLE
Build Error after .net7 installation

### ISSUE THREAD

**Issue by Tyreens** [godotengine/godot#68688] opened 2022-11-15 12:09 UTC
### Godot version

4.0dev

### System information

Windows 10

### Issue description

After the installation of the newest Visual Studio update 17.4.0 and the .NET 7.0 runtime, you cannot build the godot project with the editor. All .csprojs still have the target version .NET 6.0
The error:

```
modules/mono/glue/runtime_interop.cpp:1240 - System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. Das System kann die angegebene Datei nicht finden.
  File name: 'System.Runtime, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
     at GodotTools.ProjectEditor.ProjectUtils.Open(String path)
     at GodotTools.GodotSharpEditor.ApplyNecessaryChangesToSolution() in /root/godot/modules/mono/editor/GodotTools/GodotTools/GodotSharpEditor.cs:line 342
```

### Steps to reproduce

Install Visual Studio update 17.4.0
Build your godot project which has at least one c# script

**Comment by asolux** [comment] 2022-11-15 12:30
I think this is the same #68652

**Comment by akien-mga** [comment] 2022-11-15 12:33
Duplicate of #68652

**Closed by akien-mga** 2022-11-15 12:33 UTC
