### ISSUE TITLE
Parallax layers do not work with camera2d rotation

### ISSUE THREAD

**Issue by fossegutten** [godotengine/godot#35782] opened 2020-01-31 14:08 UTC
**Godot version:**
3.2 stable

**OS/device including version:**
Windows 10

**Issue description:**
When camera is at global_position 0,0 parallax background does not move at all. If not at zero position, the parallax background just jumps all over the place. This effect is magnified, the further away camera moves from zero position.

Related to #30988, but I think the issue needs some more description so i made a new one.

![parallax_rotation](https://user-images.githubusercontent.com/15088582/73545400-944c2980-443b-11ea-91b9-0d101a303e8d.gif)

**Steps to reproduce:**
Open my reproduction project. Move around with arrow keys and press space to start some rotation with the camera.

**Minimal reproduction project:**
[parallax_rotation.zip](https://github.com/godotengine/godot/files/4139725/parallax_rotation.zip)

**Comment by Calinou** [comment] 2020-01-31 14:22
Duplicate of #30988. When an issue lacks information, please comment on the existing issue instead of opening a new one.

**Closed by Calinou** 2020-01-31 14:22 UTC

**Comment by fossegutten** [comment] 2020-01-31 14:59
Sorry about that
