### ISSUE TITLE
HTML5 export rendering oddity - clear color not working

### ISSUE THREAD

**Issue by OvermindDL1** [godotengine/godot#4171] opened 2016-03-29 21:42 UTC
**Operating system or device:**
HTML5 (exported from Linux 64-bit but using the pre-generated exports from the website)

**Issue description** (what happened, and what was expected):
The scene is a blue background with a 2D particle emitter and a few other sprites, the blue background on everything else is gray in html5, and the 2d particle emitter appears to be completely absent, but all other sprites work entirely.

**Steps to reproduce:**
Take the 2D Particle Demo, change the background clear color in the project settings->Render->default_clear_color to be something like blue or red or yellow or something obvious, then export to html5, then open it in Chrome.

**Link to minimal example project** (optional but very welcome):
Demo project from website.
I also changed the website demo project background clear color to red and exported it to html5, currently temporarily on my website at:  http://overminddl1.com/godot/particles_export.html
The altered project I can upload to if really wanted, but it is just the stock 2d particle project with the clear color changed to demonstrate both issues, the clear color is not used in the html5 export and the 2d particle systems do not work in the html5 export.

EDIT:  Actually I exported it again and particles are working here, but not the clear color, that is an odd change...  Well consider this as the clear color not exporting to html5 then...

**Comment by eska014** [comment] 2016-03-30 14:58
If the issue has been reduced to clear color not working in web export, let's close it as duplicate of #2766

**Closed by eska014** 2016-03-30 14:58 UTC
Labels: bug, platform:html5, topic:porting
