### ISSUE TITLE
Vertex lighting objects disappear on Android, GLES 2.0 renderer

### ISSUE THREAD

**Issue by tree786** [godotengine/godot#27531] opened 2019-03-30 15:17 UTC
**Godot version:**
3.1 Stable (downloaded from godotengine.org)

**OS/device including version:**
Samsung Galaxy S6, Android 7.0

**Issue description:**
I don't know if this has been asked before.
Using the GLES 2.0 renderer, when the 'Vertex Lighting' checkbox is enabled, objects seem to disappear once they enter the range of an omni light. This doesn't happen on my desktop PC, but it occurs once I export the game to Android. I've tested with GLES 3.0 and this issue doesn't occur.

**Steps to reproduce:**
1. Use GLES 2.0 renderer
2. Add an omni light
3. Add a 'MeshInstance', assign it a material **making sure 'Vertex Lighting' is enabled**
4. Place this 'MeshInstance' below the omni, or inside it's range
5. Export to Android and run

**Minimal reproduction project:**
Please find the attached files
[vertex_light_issue.zip](https://github.com/godotengine/godot/files/3025631/vertex_light_issue.zip)

**Comment by Janders1800** [comment] 2019-04-18 16:51
Happens to me as well.

**Comment by Zizico2** [comment] 2019-04-18 23:44
Are you on a Samsung phone as well? Happens to me on Samsung J6, Android 8.1. And it's only for shaded materials with vertex lighting on (as expected). @Janders1800

**Comment by Janders1800** [comment] 2019-04-19 06:07
I'm on an Alcatel 1 with Android 8.1, also happens with directional light.

**Comment by yetha** [comment] 2019-09-25 12:13
I encountered this issue as well, GPU: Andreno 305, OS: Android 5.1, here's the error:

`--From Vertex Shader:
Error: Symbol m_roughness defined with different precision in vertex and fragment shaders.
--From Fragment Shader:
Error: Symbol m_roughness defined with different precision in vertex and fragment shaders.`
`  <C Source>     drivers/gles2/shader_gles2.cpp:129 @ _display_error_with_code()`

A workaround I made for this was to convert the SpatialMaterial to a ShaderMaterial, then add a high precision modifier to the roughness uniform.

Original: `uniform float roughness : hint_range(0,1);`
Fixed: `uniform highp float roughness : hint_range(0,1); `

Hopefully someone can find a real fix for it.

**Comment by akien-mga** [comment] 2019-09-25 12:16
@yetha What's your Godot version?

**Comment by yetha** [comment] 2019-09-25 13:00
3.1, the error still gets printed by the way (only once), but the mesh is visible and with vertex lighting.

**Comment by akien-mga** [comment] 2019-09-25 13:02
Can you test with this recent build of the master branch? https://downloads.tuxfamily.org/godotengine/3.2/alpha0-unofficial/

**Comment by yetha** [comment] 2019-09-25 13:45
Tested with that build and the issue no longer exists!

**Comment by akien-mga** [comment] 2019-09-25 13:49
It was possibly fixed by #30331, which has been cherry-picked to the 3.1 branch for Godot 3.1.2 (yet unreleased). If you're able to compile the `3.1` branch from source (both editor and Android template) to confirm that the issue is fixed there too, that would be great. Otherwise I might have a 3.1.2-rc1 build available within a week.

**Comment by clayjohn** [comment] 2019-10-12 03:26
Looks like it was fixed. Closing.

**Closed by clayjohn** 2019-10-12 03:26 UTC
Labels: bug, platform:android, topic:rendering
