### ISSUE TITLE
GridMap "Painting Tile" Always Visible

### ISSUE THREAD

**Issue by SolarLune** [godotengine/godot#887] opened 2014-11-17 20:23 UTC
Hey, there. So basically, if you use a GridMap to paint tiles and then select a new node (thereby "deselecting" the GridMap and "exiting" drawing mode), the last used tile will still be visible where it last was before you switched nodes.

**Comment by kubecz3k** [comment] 2015-11-02 10:00
Remember this bug. Tried to reproduce with d123c89c5802777e02402108d9271ed2f29368fe it looks like it's fixed now.

**Closed by kubecz3k** 2015-11-02 10:00 UTC
Labels: bug, topic:editor
