### ISSUE TITLE
Debugger displays `<null>` for non-null value

### ISSUE THREAD

**Issue by moritz-t-w** [godotengine/godot#81981] opened 2023-09-20 13:00 UTC
### Godot version

v4.1.1.stable.arch_linux

### System information

Arch Linux

### Issue description

I have not yet been able to find out exactly what is going on but this is what happened in my project:
The return value of `get_children()` in a `Node` (as a var called `nodes`) showed up in the debugger as `<null>` but the script checks `nodes == null:`, which is returning `false` and the script goes on to loop through what is still showing up as `<null>` and only throws `... on a null value` once it tries to do something with it. The same check `nodes == null` worked, when `nodes` was set to `null`.

## `nodes = null
![Screenshot from 2023-09-20 14-14-49](https://github.com/godotengine/godot/assets/90388353/ae6fae28-b10b-43cc-9d3d-7be13422a6b0)
![Screenshot from 2023-09-20 14-14-53](https://github.com/godotengine/godot/assets/90388353/838409e5-f5ee-4bf3-bd78-b71b59141e18)

## `nodes = node.get_children()`
![Screenshot from 2023-09-20 14-15-22](https://github.com/godotengine/godot/assets/90388353/46c9a9cc-9f3b-459e-a3e9-3aca2e8d7dbf)
![Screenshot from 2023-09-20 14-15-45](https://github.com/godotengine/godot/assets/90388353/776472d5-6410-4626-873a-5261b4a40719)
### Here it loops through supposed `<null>`
![Screenshot from 2023-09-20 14-43-01](https://github.com/godotengine/godot/assets/90388353/5acda7a3-bd54-42ad-861b-d8e4a76c6ef9)
Output: of `print_rich(node)`: `image:<TextureRect#34342962365>`
### Here I duplicate it and get another supposed `<null>`
![Screenshot from 2023-09-20 14-46-08](https://github.com/godotengine/godot/assets/90388353/ea184d36-068a-444f-a816-6bd5c553f38d)

### Steps to reproduce

I have not been able to reproduce this in a fresh project, however it has been consistantly happening in the same way. Unfortunately I don't have time to dig further, so I'll leave you with this and change my approach, cause it sucked anyways.

Here's the function in question. It happens at the 4th level of recursion when `nodes` should contain the children of `root3` (unbeknownst to the debugger):
![image](https://github.com/godotengine/godot/assets/90388353/b2c2b852-5fb7-410a-81e4-86a874f248c2)

```
func reload(nodes = null, transition = false):
	if nodes == null:
		print("Attempting to reload...")
		nodes = get_parent().get_children()
		print_rich(nodes)
	for node in nodes:
		if node is TextureRect:
			print_rich(node)
			var texture = node.texture
			print_rich(texture)
			if texture != null:
				if transition:
					var shadow = node.duplicate()
					transition(shadow.get_parent(), shadow)
				print("getting path...")
				var path = node.get_parent()._path
				print(path)
				if path != null && path != "":
					var path_array = path.split('_')
					var lang = read_config('language').split()[0].to_upper()
					print(lang)
					print(path_array[-1]+" == "+ lang + ".png")
					if path_array[-1] != lang + '.png':
						print('true')
						path_array[-1] = lang + '.png'
						print("reloading ("+lang+")")
						var new_path = '_'.join(path_array)
						node.texture = load_img(new_path)
						node.get_parent()._path = new_path
		reload(node.get_children(), transition)
```
Happens when called like this:
```
Daddy.reload(null, true)
```

Here's what the function looked like before the change that triggered this situation to come about:
```
func reload(nodes = null):
	if nodes == null:
		print("Attempting to reload...")
		nodes = get_parent().get_children()
		print_rich(nodes)
	for node in nodes:
		if node is TextureRect:
			print_rich(node)
			var texture = node.texture
			print_rich(texture)
			if texture != null:
				print("getting path...")
				var path = node.get_parent()._path
				print(path)
				if path != null && path != "":
					var path_array = path.split('_')
					var lang = read_config('language').split()[0].to_upper()
					print(lang)
					print(path_array[-1]+" == "+ lang + ".png")
					if path_array[-1] != lang + '.png':
						print('true')
						path_array[-1] = lang + '.png'
						print("reloading ("+lang+")")
						var new_path = '_'.join(path_array)
						node.texture = load_img(new_path)
						node.get_parent()._path = new_path
		reload(node.get_children())
```
```
Daddy.reload()
```

### Minimal reproduction project

I don't think my employer would allow me to just upload my entire project and as I said I haven't been able to reproduce this in a fresh one.

**Comment by AThousandShips** [comment] 2023-09-20 13:03
Duplicate of https://github.com/godotengine/godot/issues/39465

**Comment by Zireael07** [comment] 2023-09-20 13:03
Ninja'd by @AThousandShips

**Closed by AThousandShips** 2023-09-20 13:03 UTC

**Comment by moritz-t-w** [comment] 2023-09-20 13:06
damn u quick
