### ISSUE TITLE
Control nodes disappear after clicking the "Show Desktop" button

### ISSUE THREAD

**Issue by WINDGameDev** [godotengine/godot#46607] opened 2021-03-02 23:05 UTC
**Godot version:** 3.2.3

**OS/device including version:** Windows 10 Pro 64 Bit
My GPU is a GTX750, with an Intel i5 4440. I'm using the GLES3 backend, but on my experience, this happens with both GLES2 and GLES3.

**Issue description:**
 I was testing out UI nodes when i clicked the "Show Desktop" button on the bottom right, and the UI nodes (buttons, labels, etc) just disappeared. They were still there, but they were just invisible. When i moved them with animations, they appeared again.
 I don't know if this has anything to do with the bug, but i always make the control nodes children of Node2Ds. This is also not the first project it's happened on.

**Steps to reproduce:**
 Create a simple project with a Node2D and a button and a label as it's children. Run it and and click the "Show Desktop" button.

**Minimal reproduction project:**
I tried to replicate it but the bug didn't happen. Here's the project it's been happening on. Sorry for that.
[Take Your Children to School.zip](https://github.com/godotengine/godot/files/6072327/Take.Your.Children.to.School.zip)

Also, i'm kinda new to this GitHub stuff, so sorry for any missing things.

**Comment by Calinou** [comment] 2021-03-03 00:12
Duplicate of https://github.com/godotengine/godot/issues/42257 (same cause).

As a workaround, try disabling **Rendering > Quality > Dynamic Fonts > Use Oversampling** in the Project Settings.

You can also enforce a minimum window size to prevent the window from being resized to a very small size, which tends to cause this kind of issue. To do so, call `OS.min_window_size = Vector2(<width>, <height>)` in any script's `_ready()` method. This will be done by default if https://github.com/godotengine/godot/pull/37260 is merged.

**Closed by Calinou** 2021-03-03 00:12 UTC
