### ISSUE TITLE
Tool Script Exported Variable That References Node is Null

### ISSUE THREAD

**Issue by bozoVuksan** [godotengine/godot#70153] opened 2022-12-16 16:57 UTC
### Godot version

v4.0.beta8.mono.official [45cac42c0]

### System information

Windows 10 Home, Intel(R) Core(TM) i5-4210H CPU @ 2.90GHz   2.90 GHz, 

### Issue description

I am having a Node with a Tool Script applied.
This Tool Script has an exported Variable referencing a Node2D. 
That Variable is set via the Inspector. 

**Current Behaviour:**
The Variable is Null. 

**Expected Behaviour:**
The Variable should be referencing the Node set in the Inspector.

### Steps to reproduce

**ToolNode (Node2D) (ToolScript):** 
it prints the reference node. 
at the start, it should print null as expected. 

**ReferenceNode:**
This is the reference used by the tool script. 

1. In **ToolNode** set the Reference to the **ReferenceNode**
2. The Console should print null. (Expected behavior should be the reference to the **ReferenceNode**) 

_Info:
I tried a similar setup by exporting a node path which then loads the node. This seemed to work as intended. _ 

### Minimal reproduction project

[ToolScriptBugReport.zip](https://github.com/godotengine/godot/files/10247572/ToolScriptBugReport.zip)

**Comment by Calinou** [comment] 2022-12-16 17:00
Duplicate of https://github.com/godotengine/godot/issues/69356.

**Closed by Calinou** 2022-12-16 17:00 UTC
Labels: bug, topic:editor
