### ISSUE TITLE
KEY_CTRL is not detected when control-clicking on Button (on macOS)

### ISSUE THREAD

**Issue by resistor** [godotengine/godot#76081] opened 2023-04-15 07:13 UTC
### Godot version

4.0.2.stable.official [7a0977ce2]

### System information

macOS Vecture 13.3.1, M1 Max MacBook Pro

### Issue description

`Input.is_key_pressed(KEY_CTRL)` is always returning `false` in the `pressed` callback for a `Button`, when when `Input.is_key_pressed(KEY_CTRL)` returns true in `_process`.

This prevents implementing control-clicking a button in my game.

### Steps to reproduce

The attached reproduction project prints a message showing which modifier keys are pressed while clicking the button. It works correctly for `KEY_META`, `KEY_ALT`, and `KEY_SHIFT`, but not for `KEY_CTRL`.

It also includes code (commented out by default) that logs modifier key pressed status in `_process` to demonstrate that `KEY_CTRL` detection is working in general.

### Minimal reproduction project

[ControClickButton.zip](https://github.com/godotengine/godot/files/11238670/ControClickButton.zip)

**Comment by ajreckof** [comment] 2023-06-11 20:08
This is not a bug but default behavior of MacOS. When pressing ctrl and left click MacOS interprets it as right click. Therefore it is not that `Input.is_key_pressed(KEY_CTRL)` is always false but more that when it is true the `pressed`signal is never call because it is called only on left mouse button click (by default). To prevent that you can just add right click to the button mask.

**Comment by akien-mga** [comment] 2023-06-12 09:34
Thanks for the explanation! Closing as not a bug.

**Closed by akien-mga** 2023-06-12 09:34 UTC
Labels: bug, platform:macos, topic:input
