### ISSUE TITLE
Add visibility for "Node" and "CanvasLayer"

### ISSUE THREAD

**Issue by QbieShay** [godotengine/godot#30059] opened 2019-06-25 06:59 UTC
**Godot version:**
3.1-stable

**OS/device including version:**
5.1.11-arch1-1-ARCH

**Issue description:**
I think it could be useful to allow the "Node" class to have a visibility toggle (that does nothing). This is useful if you want to forward visibility in a subtree of your scene without caring if there are some possible "Node"s that are interrupting the inheritance of the visibility.
I understand that this might be done on purpose in some projects, so let's talk about it :)
Regarding CanvasLayer, here's the related issue #16532

**Detailed use case**:
I have a script that spawns objects and, due to its "abstract" nature, it inherits from Node (so that i can assign the export vars in the scene).
When the objects are spawned, they are put as a child of the spawner.
If i try to hide the level, since the spawners are part of the level, all the spawned object won't be hidden because they are children of a Node.

**Thoughts**
I'm very aware that this could be reimplemented in many ways to solve this issue, but I'd like to understand if this is something that only I am encountering or if it is common amongst other users.

If no action is to be taken inside of the engine code, it might be worth documenting with good/bad practices somewhere.

**Comment by KoBeWi** [comment] 2019-06-25 11:25
I don't know where the idea that you need to use "the most abstract node" came from. If you have a 2D scene, use Node2D as a root and for any other "abstract" object. It doesn't really introduce as much overhead as most people think. Like, there are nodes inheriting from Node2D, whose position and Z-index is irrelevant (e.g. CanvasModulate) and nobody has a problem with that. Node should be used for stuff that isn't supposed to interact with your scene at all (like singletons). btw, you can also use Node script inside Node2D.

However, assuming this is really needed, adding visibility to Node isn't really a good idea, as every node inheriting from it (so, every node) will get the property and it's rather useless for them. Instead, we could make CanvasItem non-abstract, to have a generic node that forwards visibility and color, but doesn't have a position. Or a RemoteVisibility, similar to RemoteTransform.

As for CanvasLayer, adding visibility there does make sense.

**Comment by Zireael07** [comment] 2019-06-25 11:52
Yeah, CanvasLayer could benefit from a visibility toggle.

**Comment by Anutrix** [comment] 2019-06-26 09:39
Will it work if we make CanvasLayer inherit CanvasItem?

**Comment by Xrayez** [comment] 2019-06-26 13:46
> If you have a 2D scene, use Node2D as a root and for any other "abstract" object.

I started to use `Node2D` for most stuff now even if I think that "I won't need to be able to inherit transform/visibility", boy I'm almost always wrong with this assumption and end up changing type and script to inherit `Node2D` instead of `Node`. 😄

So using a `Node` alone is a good decision for organizing pure game logic.

I do use visibility as a way to enable/disable certain nodes from executing internal logic:
```gdscript
for generator in $generators.get_children():
    if not generator.visible:
        continue # disabled, skip
    # do stuff
```

You can also recursively enable visibility for all children (not tested):
```gdscript
extends Node

export(bool) var visible = true setget set_visible

func set_visible(p_visible):
    visible = p_visible
    propagate_call("set_visible", [visible]) # only called if child has such method
```

**Comment by Calinou** [comment] 2020-07-07 08:23
(Partly) duplicate of #16532. I'd recommend gathering on a proposal made on the Godot proposals repository, since #16532 is just about CanvasLayer.

**Closed by Calinou** 2020-07-07 08:23 UTC
Labels: discussion, enhancement, topic:core
