### ISSUE TITLE
tileset editor: using shaders prevents editing the tileset

### ISSUE THREAD

**Issue by securas** [godotengine/godot#41094] opened 2020-08-07 06:39 UTC
Could not find one

**Godot version:**

3.2.3 RC3

**OS/device including version:**

win10, gtx1070

**Issue description:**

when creating a material and shader in a tile within the tileset editor, it becomes impossible to edit the tile properties.
As soon as the tile is selected, the shader editor comes up and superimposes on the tileset editor.

**Steps to reproduce:**
try to edit the tile on the example project.

**Minimal reproduction project:**

[test_tileset_shader.zip](https://github.com/godotengine/godot/files/5039725/test_tileset_shader.zip)

**Comment by Zireael07** [comment] 2020-08-07 06:42
IIRC was reported already, a long time ago, but can't find issue at the moment...

**Comment by neqs20** [comment] 2020-08-07 07:10
@Zireael07 I think that's the one: #32002

**Comment by pouleyKetchoupp** [comment] 2020-08-07 07:39
Closing as duplicate of #32002.

**Closed by pouleyKetchoupp** 2020-08-07 07:39 UTC
Labels: bug, topic:editor
