### ISSUE TITLE
Input actions conflict when using similar key bindings

### ISSUE THREAD

**Issue by Skaruts** [godotengine/godot#50863] opened 2021-07-25 17:42 UTC
### Godot version

3.3.2

### System information

Windows 7, GLES2

### Issue description

If you create two (or more) input actions that use similar key combos, they will conflict when using `is_action_pressed` or `is_action_released`. For example, if you create:

action `"foo"` -> `ctrl shift alt S`
action `"bar"` -> `ctrl alt S`

and you have this input code:
```gdscript
func _input(event: InputEvent) -> void:
    if event.is_action_pressed("foo"):    print("foo pressed")
    elif event.is_action_released("foo"): print("foo released")

    if event.is_action_pressed("bar"):    print("bar pressed")
    elif event.is_action_released("bar"): print("bar released")
```

The results will be:

- if you press `ctrl shift alt S`, **both actions** will trigger `is_action_pressed` and `is_action_released`.
- if you press `ctrl alt S`, only `"bar"` will trigger `is_action_pressed`, but both actions will trigger `is_action_released`

I haven't tested this further, but there's probably other combinations that have similar conflicts.

### Steps to reproduce

This should be easily reproduced in any project; just create those two actions with those same keys, and put the code above in a script, and then run it and try the keys out.

**Comment by raulsntos** [comment] 2021-07-25 18:50
Duplicate of #44180 and #18793 that was fixed in `master` with #44355 but I don't think it's in the 3.x branch and OP is using 3.3.2

**Comment by Calinou** [comment] 2021-07-25 20:08
Closing per @raulsntos' comment. Feel free to remake https://github.com/godotengine/godot/pull/44355 for the `3.x` branch, it should be backwards-compatible as the `exact` parameter defaults to `false` :slightly_smiling_face:

**Closed by Calinou** 2021-07-25 20:08 UTC
Labels: bug, topic:input

**Comment by Skaruts** [comment] 2021-07-26 19:15
@Calinou not sure I understand. Is it going to be backported?

**Comment by Calinou** [comment] 2021-07-26 19:31
> @Calinou not sure I understand. Is it going to be backported?

It's not backported yet, but backporting it is welcome.

**Comment by raulsntos** [comment] 2021-07-26 20:10
I opened PR #50874 to backport it
