### ISSUE TITLE
Script Editor with long lines in code, does not reopen script in same position as was saved, scrolling it to the right

### ISSUE THREAD

**Issue by wyattbiker** [godotengine/godot#91235] opened 2024-04-27 01:02 UTC
### Tested versions

v4.3.dev5.official [c9c17d6ca]

### System information

Linux Kubuntu 23.04 KDE Plasma Version: 5.27.4 KDE Frameworks Version: 5.104.0 Qt Version: 5.15.8

### Issue description

When opening up scripts from Filemanager, if the contain long lines and the cursor position is saved someplace in the middle, the script opens up scrolled to the right.  

### Steps to reproduce

If you have a script with some long lines that go past the viewing area of the editor, and save it, when you reopen it, the script and cursor may be positioned incorrectly such as in screen shot below:

![Screenshot_20240426_174711](https://github.com/godotengine/godot/assets/930478/1eeefbe0-a972-4920-9679-cc2672c29a5e)

### Minimal reproduction project (MRP)

Sample project:
[Archive.zip](https://github.com/godotengine/godot/files/15136172/Archive.zip)

**Comment by KoBeWi** [comment] 2024-04-27 07:55
Duplicate of #33865

**Closed by KoBeWi** 2024-04-27 07:55 UTC
Labels: bug, topic:gdscript, topic:editor, usability
