### ISSUE TITLE
indirect call to null in Firefox

### ISSUE THREAD

**Issue by duane-r** [godotengine/godot#46622] opened 2021-03-03 16:27 UTC
**Godot version:** 3.2.4.rc3

**OS/device including version:** archlinux (up to date) on Motile m142, gles2, Firefox 86.0

**Issue description:** I exported my version of Dodge the Creeps to html and tried to load it in Firefox 86.0, serving with a one-line python web server. The page created a requester box with an OK button, but no text in it. When I pressed OK, the message "indirect call to null" appeared. The same happened when I used the html preview button in the editor.

The web console gives the following output:
`exception thrown: RuntimeError: indirect call to null,godot_js_main(int, char**)@http://localhost:8000/dodge.js line 175 > WebAssembly.instantiate:wasm-function[11275]:0x21c48e
main@http://localhost:8000/dodge.js line 175 > WebAssembly.instantiate:wasm-function[23592]:0x589d14
Godot/Module._main@http://localhost:8000/dodge.js:9:329687
callMain@http://localhost:8000/dodge.js:9:334806
Engine.prototype.start/</</<@http://localhost:8000/dodge.js:402:15
Engine.prototype.start/</<@http://localhost:8000/dodge.js:397:12
dodge.js:215:17
indirect call to null index.html:212:13
    displayFailureNotice http://localhost:8000/index.html:212`

**Steps to reproduce:**
Load the attached project and attempt to preview html or export the project to html and try to load from a server.

I moved my .mozilla directory out of the way, and started a fresh copy of firefox, with no addons. I can't be sure that my code is good, but it works normally in android and linux.

**Minimal reproduction project:**

[dtc-error.zip](https://github.com/godotengine/godot/files/6077462/dtc-error.zip)

**Comment by duane-r** [comment] 2021-03-03 16:31
I doubt this helps much, but here are a couple of screenshots of the browser.
![error-shot-01](https://user-images.githubusercontent.com/14078065/109838211-9159d480-7c0b-11eb-805f-f9e40a897113.jpg)
![error-shot-02](https://user-images.githubusercontent.com/14078065/109838227-9585f200-7c0b-11eb-89a4-053bf507d7a9.jpg)

**Comment by Calinou** [comment] 2021-03-03 16:42
Duplicate of https://github.com/godotengine/godot/issues/46352 (fixed in the latest `3.2` branch).

**Closed by Calinou** 2021-03-03 16:42 UTC
