### ISSUE TITLE
Syntax error cancels auto-complete

### ISSUE THREAD

**Issue by T4g1** [godotengine/godot#37086] opened 2020-03-16 08:08 UTC
**Godot version:** 3.2.stable

**OS/device including version:** 5.5.2-arch1-1

**Issue description:**
Auto-completion does not works when there are one or multiple errors in the script

**Steps to reproduce:**
1. Create a new script
2. Make a typo
3. Start typing something else and `Ctrl + Space` to trigger auto complete
4. Nothing shown
5. Fix typo
6. Repeat step 3
7. Auto complete works

**Minimal reproduction project:**
Any project, new script with the following content:
```
extends Node

expot (PackedScene) var typo

func _re
```

**Comment by Calinou** [comment] 2020-03-16 09:00
I'm fairly sure this has already been reported, but I can't find the issue in question.

**Comment by Zylann** [comment] 2020-03-16 10:53
Similar to https://github.com/godotengine/godot/issues/33191

**Comment by Calinou** [comment] 2020-03-16 13:00
This is a duplicate of #33191 indeed. Thanks @Zylann :slightly_smiling_face:

**Closed by Calinou** 2020-03-16 13:00 UTC
