### ISSUE TITLE
Godot 4 Crash when opening project on ubuntu

### ISSUE THREAD

**Issue by nitricware** [godotengine/godot#74908] opened 2023-03-14 13:36 UTC
### Godot version

4.0.stable.mono.official

### System information

Ubuntu 22.04.2 LTS

### Issue description

I downloaded the most recent Godot 4 Engine with mono support, extracted the contents of the zip (the executable and the folder `GodotSharp`) to `/usr/local/bin/`. I renamed the executable to `godot-mono`

When I start `godot-mono` the project selection screen appears and when I create a new project or open an existing one, this appears in terminal and the windowed Godot application disappears.

`dotnet-sdk-6.0` is installed

```
================================================================
handle_crash: Program crashed with signal 11
Engine version: Godot Engine v4.0.stable.mono.official (92bee43adba8d2401ef40e2480e53087bcb1eaf1)
Dumping the backtrace. Please include this when reporting the bug to the project developer.
[1] /usr/lib/dotnet/shared/Microsoft.NETCore.App/6.0.13/libcoreclr.so(+0x4b5e94) [0x7ff0bfcb5e94] (??:0)
[2] /lib/x86_64-linux-gnu/libc.so.6(+0x42520) [0x7ff116842520] (??:0)
[3] llvm::CmpInst::Create(llvm::Instruction::OtherOps, llvm::CmpInst::Predicate, llvm::Value*, llvm::Value*, llvm::Twine const&, llvm::BasicBlock*) (??:0)
-- END OF BACKTRACE --
================================================================
```

What could go wrong there?

### Steps to reproduce

1. install godot as described
2. run godot as described
3. crash

### Minimal reproduction project

no project neccessary

**Comment by Calinou** [comment] 2023-03-21 18:43
- Duplicate of https://github.com/godotengine/godot/issues/58927 (most likely, given the `llvm::CmpInst::Create`` in the backtrace).

As a workaround, choose the Compatibility rendering method when creating a project. For existing projects, see https://github.com/godotengine/godot/issues/74159#issuecomment-1450427287.

**Closed by Calinou** 2023-03-21 18:43 UTC
