### ISSUE TITLE
Viewport catches mouse events despite being under Canvas Layer

### ISSUE THREAD

**Issue by haaldor** [godotengine/godot#45400] opened 2021-01-23 21:38 UTC
**Godot version:** 

3.2.3.stable.official

**OS/device including version:** 

GPU: GeForce GTX 1060 6GB
Using GLES2, happens on GLES3 as well.

**Issue description:**

What happened:

> When using Viewport to draw world and CanvasLayer to draw overlay, controls in Viewport are catching mouse input events despite being drawn under overlay.

What is expected: 

> Canvas layer should be one catching mouse events, as it is drawn on top.

**Steps to reproduce:**
1. Create new project
2. Add nodes as following:

```
- Node2D
-- Viewport Container (set rect_size to window size, f.e. 1024/600 )
--- Viewport (set size to match parent's rect_size)
---- Button (can add script to print something on pressed() signal to check it)
-- Canvas Layer
--- LineEdit
```

3. Save and play. LineEdit is not getting any inputs on where button is, despite being drawn over the button

**Minimal reproduction project:**

[Viewport_canvas_layer_bug.zip](https://github.com/godotengine/godot/files/5861103/Viewport_canvas_layer_bug.zip)

**Comment by akien-mga** [comment] 2022-02-11 14:24
Duplicate of #39666

**Closed by akien-mga** 2022-02-11 14:24 UTC
Labels: needs testing, topic:input, topic:gui
