### ISSUE TITLE
Debugger doesn't show local variables if debug line is the last line of file

### ISSUE THREAD

**Issue by breakmt** [godotengine/godot#28151] opened 2019-04-18 05:26 UTC
**Godot version:**
3.1 stable

**OS/device including version:**
Windows 7 x64

**Steps to reproduce:**
1. Make function with some local variables,
2. Make breakpoint in **the last line of file**,
3. Run project

**Result:** there are no local variables in debugger window 
![bug1](https://user-images.githubusercontent.com/1552169/56338609-5d11d200-61b3-11e9-940d-f3457f295c3d.png)

**Expected:** variables are displayed

**Note:** if you add one line, even empty one (which makes debugger line is not last of file) - variables are displayed in debugger
![bug2](https://user-images.githubusercontent.com/1552169/56338625-64d17680-61b3-11e9-95e4-f53b136f91f6.png)

**Minimal reproduction project:**
You should put break point in the last line of script file, run project and you will see than there are no local variables in debugger
[18042019.zip](https://github.com/godotengine/godot/files/3092845/18042019.zip)

**Comment by akien-mga** [comment] 2019-04-18 11:12
Confirmed in 2c0c1e3 (so it was not fixed by #27055, even if the bugs seem related).

**Comment by TicklesTheBrain** [comment] 2019-04-23 09:04
I have filed another breakpoint issue #27177 that I find really problematic for my project. Perhaps it is related and someone can have a look at it while fixing this?

**Comment by ArdaE** [comment] 2019-05-22 17:10
The issue is bigger than just the last line of a file; it affects the last line of **any indented section**, including if/else and match statements, where it's common to put the "else" or the next match pattern immediately following the previous section, without a line gap in between:

![image](https://user-images.githubusercontent.com/8313057/58193787-afde1e00-7c78-11e9-9137-3a21619a6886.png)

Until this is fixed, insert an extra line of "pass" as a workaround wherever you suffer from this issue.

**Comment by akien-mga** [comment] 2020-01-15 12:55
The issue in the OP seems fixed by #29262. The editor will now always ensure that the file ends with a newline, so you can't have a line of code being the last line anyway. Still, even using "Step Into" to reach the last line, it displays member variables fine now in the master branch.

As for the issue with the last line of indented blocks, it behaves as if it already returned to the outer scope (i.e. it's likely considering to be at the end of the line, after `/n`), while other debuggers would tend to stop at the beginning of the line, and thus still in scope. I suggest moving this to a dedicated issue though as it's not the same as the issue originally described.

**Closed by akien-mga** 2020-01-15 12:55 UTC
Labels: bug, confirmed, topic:core, topic:editor

**Comment by ArdaE** [comment] 2020-01-15 19:39
> I suggest moving this to a dedicated issue though as it's not the same as the issue originally described.

The two issues are one and the same. The new extra line at the end of the file just hides the issue in its limited description provided by the OP.

I haven't tried the new code, but if you place a breakpoint on the new extra line that it adds, you should still have the same issue; i.e. the debugger should fail to display the local variables, even though it would still consider that line to be a part of the method (try putting a breakpoint on it, and you should see that the debugger will stop on it when the method gets called).

Anyway, I'll create a new issue when I get a chance one day as per your request. In the end, one fix should fix both issues properly, without relying on #29262 which is a completely different thing.

**Comment by akien-mga** [comment] 2020-01-15 20:18
As I mentioned, if you step into the last line of the script, you do see all the member variables.

Similarly, if you break on the last line of a block, you see all the member and local variable, apart from those that have gone out of scope on the block.

So:
```
if true:
    var a = 1
    pass    # breakpoint
```
behaves like this:
```
if true:
    var a = 1
    pass
# breakpoint
```

Which is not wrong per se as I explained, but is not what one usually expects of a breakpoint (should break before the statement, not after).

On the other hand, the OP issue was that a breakpoint on the last line would not show *anything*, which is no longer the case and not the situation in a block.

**Comment by ArdaE** [comment] 2020-01-15 20:54
My point is that those empty lines that follow the method aren't out of the scope of the method. They are part of the method, as far as Godot is concerned, which you can verify by putting a breakpoint on them. (I don't think they _should_ be, but whether you or I think they should be part of the method is irrelevant; I'm just referring to how Godot interprets them).

I don't think you're correct about the breakpoint's location being at the end of the line either. When a breakpoint is placed on a line, the code stops before the statement on the line is executed, based on all my experience with Godot. You can test this by incrementing `a` by 1 in the code you've pasted, placing a breakpoint on that line, and checking if `a` is incremented yet or not.

Anyway, this disagreement is not big enough to have a conversation over. I'll just create a new issue that better describes the problem when I get a chance (just too busy with other projects right now, and I don't do anything with Godot other than donate to it at the time being). Thank you for all your hard work on Godot by the way.
