### ISSUE TITLE
Undo / redo via keyboard shortcut on macOS not working as expected in V4.0-alpha15

### ISSUE THREAD

**Issue by tservas** [godotengine/godot#65369] opened 2022-09-05 15:34 UTC
### Godot version

v4.0.alpha15.official [432b25d36]

### System information

MacOS 12.5.1

### Issue description

The keyboard shortcuts CMD + Z and CMD + SHIFT + Z in  V4.0-alpha15 do not work as expected inside the GDScript editor.  

Instead of triggering the respective commands in the GDEditor it seems that the corresponding Entries in the Scene Menu are triggered. Using the keyboard shortcuts results in the message 'Nothing to undo.' in the output tab.

Using the menu entries in the GDScript editor, i.e. Edit > Undo / Redo works as expected.

One and the same shortcuts seem to be assigned for different operations, cf. Scene Menu and Edit Menu inside GDScript editor.

### Steps to reproduce

- Open the GDScript editor
- Edit some code
- use the keyboard shortcuts

### Minimal reproduction project

No MRP necessary to reproduce the bug.

**Comment by Calinou** [comment] 2022-09-05 15:35
Duplicate of https://github.com/godotengine/godot/issues/65119.

**Closed by Calinou** 2022-09-05 15:35 UTC
