### ISSUE TITLE
Starting New Scene Leaves Outlines Lingering In Viewer

### ISSUE THREAD

**Issue by Zakkumaru** [godotengine/godot#18408] opened 2018-04-25 02:20 UTC
**Godot version:**

Godot Engine 3.0.2.stable.official

**OS/device including version:**

Xubuntu (Linux)
NVidia Geforce GTX 560M 3GB
NVidia proprietary binary driver v370

**Issue description:**

Clicking "New Scene" starts a new scene tab and switches to it; however, the outlines and icons from the previously-active scene window will linger in the viewer until you switch to another scene, and then back to the new one.

**Steps to reproduce:**
Edit a scene
Optionally, select an object so that its border is visible
Press, "New Scene"
Observe as the outlines and object icons (such as the lock symbol) are still visible
Click on another scene tab
Click back to the new scene tab
The outlines and icons should have now disappeared

**Minimal reproduction project:**

Minimal reproduction project wouldn't matter-- it's reproducible regardless of the project, or what's in it.  Even a fresh project does this.

**Comment by vnen** [comment] 2018-04-28 15:15
Duplicate of #14500

**Closed by vnen** 2018-04-28 15:15 UTC
Labels: bug, topic:editor
