### ISSUE TITLE
SubViewport renders clipped transparent pixels as black color.

### ISSUE THREAD

**Issue by srdj-abs** [godotengine/godot#100196] opened 2024-12-09 10:11 UTC
### Tested versions

- Reproducible in: v4.2.2.stable.official [15073afe3]

### System information

Arch Linux - Godot Engine v4.2.2.stable.official.15073afe3 - https://godotengine.org OpenGL API 3.3.0 NVIDIA 565.77 - Compatibility - Using Device: NVIDIA - NVIDIA GeForce GTX 1660 SUPER 

### Issue description

When I try to clip child nodes of any Node2D using the Clip Only option inside SubViewport it renders clipped transparent pixels black instead of hiding them.

The left output is wrong. The right output is when I move it out of the viewport.

![Image](https://github.com/user-attachments/assets/3b9aa924-de1b-40ea-84d0-d270dff839da)

### Steps to reproduce

- Create Subviewport and make Transparent BG true.
- Add one Label under it and write something in it.
- Change Clip Children to Clip Only.
- Add Polygon2D with a shape that overlaps the text under that Label.
- Instead of clipping and showing intersecting parts it will show non-intersecting parts of the label in black colour.

### Minimal reproduction project (MRP)

[Black Color Problem.zip](https://github.com/user-attachments/files/18059429/Black.Color.Problem.zip)

**Comment by AThousandShips** [comment] 2024-12-09 10:44
Thank you for reporting. This is a duplicate of a previously reported issue. We prefer to track issues in one place, so I am consolidating this with:
* https://github.com/godotengine/godot/issues/94208

See the linked issue for details. If you think it may not be the same and something was missed, please comment here and this issue can be reopened.

**Closed by AThousandShips** 2024-12-09 10:44 UTC
