### ISSUE TITLE
Tilemap - Hex Tiles overlap based on Quadrant size

### ISSUE THREAD

**Issue by MonetaryShoe253** [godotengine/godot#70594] opened 2022-12-26 15:55 UTC
### Godot version

Godot4 Beta 10

### System information

Windows 10

### Issue description

When creating a tile map, periodically, tiles will overlap incorrectly, this changes based on the cell quadrant size, not being visible at quadrant size 1 or 2, however larger values cause this bug. E.g when cell quadrant size is deafult (16), this happens 
![image](https://user-images.githubusercontent.com/83168300/209565373-44272ea7-bb5e-4f0f-b763-720e8365d399.png)

### Steps to reproduce

Create Hex tile map with vertical alignment. add tiles that stretch outside of the defined hexagonal region, e.g. to provide illusion of some depth to a map, e.g pictured above. Draw a large area of these tiles.

### Minimal reproduction project

N/A

**Comment by kleonc** [comment] 2022-12-26 16:52
> ### Steps to reproduce
> 
> Create Hex tile map with vertical alignment. add tiles that stretch outside of the defined hexagonal region, e.g. to provide illusion of some depth to a map, e.g pictured above. Draw a large area of these tiles.
> ### Minimal reproduction project
> 
> N/A

Please upload minimal reproduction project, it's not obvious what's your exact setup.

**Comment by akien-mga** [comment] 2023-01-17 13:10
Closing as it's not actionable without clear reproduction steps.

**Comment by kleonc** [comment] 2023-02-18 20:30
Reopening as there's user with the same issue and wanting to provide MRP (can't do so when archived/closed).

**Comment by kolumdium** [comment] 2023-02-18 20:50
Hello Here is a MRP
[TileMapBug.zip](https://github.com/godotengine/godot/files/10775166/TileMapBug.zip)

The Steps to Reproduce are easy too. 
1. Make a Tilemap with Hexagon, Vertical Offset, TileSize 32x28
2. Create Tileset
3. Add Texture to Tileset in my case the texture_region is 32x48
4. Print Tiles over the Quadrant Border

**Comment by kleonc** [comment] 2023-02-18 21:16
> TileMapBug.zip

@kolumdium For this specific setup the issue happens only in case of tile layouts (`TileSet.tile_layout` property): `Stacked`, `Stacked Offset`, `Stairs down`.
For tile layouts: `Stairs Right`, `Diamond Right`, `Diamond Down` it's rendering just fine (so it should do as a workaround).

cc @groud

**Comment by groud** [comment] 2023-02-20 09:18
> The issue doesn't happen when y-sorting / with quadrant size = 1.

This is expected behavior. 

You cannot have a vertical component to a tile and expect it to be drawn correctly without Y-sorting enabled. We added a [warning to isometric mode](https://github.com/godotengine/godot/pull/67050), as it is commonly used there, but not to hexagons as it is less common. To solve this problem, you must enable Y-sorting.

Closing as this is expected behavior.

**Closed by groud** 2023-02-20 09:18 UTC
Labels: bug, topic:core, confirmed, topic:2d

**Comment by kolumdium** [comment] 2023-02-23 09:54
Forgive my Question after it's closed but wouldn't it be possible to Y-sort the quadrants only? 
Because enabling Y-Sorting makes big tile maps impossible. 512x512 already lags alot and 1024x1024 just crashes without warning. I assume that is what you implemented Quadrants for in the first place.
For me Y-Sorting is not a solution I can use as of now.

**Comment by groud** [comment] 2023-02-23 10:08
> Forgive my Question after it's closed but wouldn't it be possible to Y-sort the quadrants only?

Not really, you cannot have a vertical component to a map without applying Y-sorting. If we don't do that, you'll always have weird artifacts at the borders of the quadrant, exactly like what you have now.
 
You have to imagine that quadrants are some sort of large planes you draw on, which then get Y sorted. So here, at the intersection of the planes, you cannot have a quadrant that is sometime on top and sometime below the next quadrant.

However, I discussed a bit with reduz, and it seems that we might have a solution. Instead of forcing the quadrant size to (1,1) when Y-sort is enabled, we could force it so something like (quadrant_size, 1), that should greatly improve performance and produce no visible artifacts, if I am not mistaking.

**Comment by groud** [comment] 2023-02-23 10:48
I made a PR: https://github.com/godotengine/godot/pull/73813

**Comment by kolumdium** [comment] 2023-02-23 15:59
Thank you anyway for thinking about it!

> you cannot have a quadrant that is sometime on top and sometime below the next quadrant.

Right, I understand the Problem now.
Would it be possible to make the chunks for Hexmaps also be Hexagons, or a square only filled with Tiles that amount to a bigger Hex.
Then it should work because it would be 2 different chunk borders that could be sorted. The same as for single Tiles.
It would basically be the same as the current Tilemap but with the "bigger" Tiles to render.
Not sure if I explained that properly.
Let me know if you understood my Idea or if I need to explain it better.

**Comment by kolumdium** [comment] 2023-02-24 14:01
Ok, understood.
That it could be possible is good enough fo me. :)
Thank you for your time.
