### ISSUE TITLE
ColorRect disappearing on Windows 10 with AMD Vega 64 [GLES3]

### ISSUE THREAD

**Issue by triptych** [godotengine/godot#25523] opened 2019-01-31 18:33 UTC
This is a courtesy filing based off a user's report from Reddit:
https://www.reddit.com/r/godot/comments/alhvil/node_disappearing/
"I have a strange bug I don't know if it's my machine or Godot 3.1 :

When I create a completely new project in 2D, with a simple 2D node as root and a ColorRect as a child , the ColorRect disappear after the first frame at the game startup.

All the settings are the default (once again completely new project).

Do you have an idea ? Thanks !

I was able to test the project on another computer and I don't have the issue.

I assume it's my machine (the renderer is a Vega 64 GPU) but I don't know what the issue could be"

**Steps to reproduce:**

You can check this simple project :

https://github.com/rafoufoun/GodotSandbox

It's a little more elaborated than what I've described in the post, but quite simple at the same time. When I launch the game, the PlayerOne and PlayerTwo disappear

**Comment by eon-s** [comment] 2019-01-31 23:55
The issue is missing the exact Godot version (there are many 3.1 including master) and OS.

I cannot reproduce on Ubuntu, with AMD R5, on 3.1b3 using the sample project.

**Comment by rafoufoun** [comment] 2019-02-01 08:02
Hi, 

I'm the user reddit who posted the issue. I didn't file a github issue because I didn't know if it was a godot issue. 

Here are all the informations about the environment : 
- Godot v3.1 beta 3
- Platform : Windows 10 
- GPU : AMD Vega 64 with latest drivers (19.1.2)
- Project set to GLES3

**Note** : 
- The exact same project on MacOS works
- On Windows, I switched from GLES3 to GLES2 and the node didn't disappear, I didn't have the issue

**Comment by clayjohn** [comment] 2020-01-10 06:24
Looks to be a GPU-specific issue. As it is not reproducible and GLES3 is disappearing next release, I am going to close this issue. 

If someone else experiences this issue, try updating your drivers. If that doesn't work, please comment here and I will reopen.

**Closed by clayjohn** 2020-01-10 06:24 UTC
Labels: bug, platform:windows, topic:rendering
