### ISSUE TITLE
Visual shader nodes with popup number edit eat middle mouse clicks until window is defocused and refocused

### ISSUE THREAD

**Issue by QbieShay** [godotengine/godot#72304] opened 2023-01-29 12:06 UTC
### Godot version

v4.0.beta.custom_build [218bef90a]

### System information

Fedora, RX 590, Gnome on XORG

### Issue description

UPDATE: any visual shader node that has a popup for numbers behave like that
![image](https://user-images.githubusercontent.com/7917475/215325139-27acb074-f6ba-44d0-aaca-0da537233dc1.png)

When changing the power value of the fresnel node, the mouse input is not fully responsive anymore. specifically, middle click stops working for turning the 3D view until the window is defocused and focused again.

![Screenshot from 2023-01-29 13-02-47](https://user-images.githubusercontent.com/7917475/215324847-f18e0664-565c-4a1e-9c65-3f441a85efe2.png)

### Steps to reproduce

Create a visual shader, create a fresnel node, change the power value, try to rotate the main 3d view.

### Minimal reproduction project

Here's the shader i was working on

[StoneShader.zip](https://github.com/godotengine/godot/files/10529708/StoneShader.zip)

**Comment by KoBeWi** [comment] 2023-01-29 12:08
Might be same as #72296
Related to #71685 maybe?

**Comment by QbieShay** [comment] 2023-01-29 12:09
Could be? @KoBeWi it seems to happe with any node that makes a small popup in visual shaders.

**Comment by QbieShay** [comment] 2023-01-29 12:15
Reproduced #72296, same behaviour as visual shaders. I'm on fedora. Not sure if im on wayland or X11

**Comment by KoBeWi** [comment] 2023-01-29 12:55
I'll close it as duplicate of #72296 then.
I can't reproduce this one on Windows either, so it seems Linux-specific.

**Closed by KoBeWi** 2023-01-29 12:55 UTC
