### ISSUE TITLE
`load_threaded_get_status()` providing incorrect loading progress values

### ISSUE THREAD

**Issue by markdibarry** [godotengine/godot#65380] opened 2022-09-05 20:18 UTC
### Godot version

4.0.dev (90801a4153)

### System information

Windows 10

### Issue description

When providing an array to `load_threaded_get_status()`, the array is only populated with 0 or 1, no in-between values.

### Steps to reproduce

Run MRP.
Note that the test scene has two images. Feel free to replace them with more/larger ones to make the effect more obvious.

### Minimal reproduction project

[LoadingBug.zip](https://github.com/godotengine/godot/files/9492389/LoadingBug.zip)

**Comment by Calinou** [comment] 2022-09-05 23:59
@markdibarry The minimal reproduction project didn't upload (likely because you clicked away from the text field while it was still uploading). Try editing your post and upload it again.

**Comment by markdibarry** [comment] 2022-09-06 00:01
Updated. Thanks!

**Comment by gotnospirit** [comment] 2022-09-11 05:43
For this specific problem, copying
https://github.com/godotengine/godot/blob/c658fa8b77eb701ddb504cba14fe2c966b7bb105/scene/resources/resource_format_text.cpp#L654-L656

just after https://github.com/godotengine/godot/blob/c658fa8b77eb701ddb504cba14fe2c966b7bb105/scene/resources/resource_format_text.cpp#L509
solves the problem.

/////

Beside that, I think current cache_mode should not be overwritten when making a "sub load"
https://github.com/godotengine/godot/blob/c658fa8b77eb701ddb504cba14fe2c966b7bb105/scene/resources/resource_format_text.cpp#L466
https://github.com/godotengine/godot/blob/c658fa8b77eb701ddb504cba14fe2c966b7bb105/scene/resources/resource_format_text.cpp#L480
when this kind of parameter is explicitly set, it is expected to be used "all the way down".

It may be related to how `ResourceLoader::load` decides to use its `load_threaded_request` or `_load` method, but at the end, it made it a bit harder to track things
https://github.com/godotengine/godot/blob/c658fa8b77eb701ddb504cba14fe2c966b7bb105/core/io/resource_loader.cpp#L522-L527

/////

To finish, it didn't happen everytime but I had this error few times while debugging (happens when you stop running the scene)
```
ERROR: 2 RID allocations of type 'class RendererRD::TextureStorage::Texture' were leaked at exit.
WARNING: 4 RIDs of type "Texture" were leaked.
     at: RenderingDeviceVulkan::finalize (drivers\vulkan\rendering_device_vulkan.cpp:9736)
 - RID:4101693767839
 - RID:4153233375393
 - RID:4097398800542
 - RID:4148938408096
```

**Comment by akien-mga** [comment] 2023-01-10 10:57
Duplicate of #56882

**Closed by akien-mga** 2023-01-10 10:57 UTC
Labels: bug, topic:core, confirmed
