### ISSUE TITLE
The downloading export template UI blinks when you click

### ISSUE THREAD

**Issue by a690089735** [godotengine/godot#77836] opened 2023-06-04 14:34 UTC
### Godot version

v4.0.3.stable.official [5222a99f5]

### System information

windows 10 - v4.0.3.stable.official [5222a99f5] - compatibility

### Issue description

When I was downloading the export template, I accidentally clicked on the bottom box and it started flashing. If I clicked a few more times, it would flash faster

https://github.com/godotengine/godot/assets/34900141/73cf9186-f021-42d4-8fbc-88e29f0e08ce

### Steps to reproduce

Click on the box below when downloading the export template

### Minimal reproduction project

none

**Comment by AThousandShips** [comment] 2023-06-04 15:08
* Duplicate of #74115

**Closed** 2023-06-07 12:33 UTC
