### ISSUE TITLE
AnimationTree undesired transition delay

### ISSUE THREAD

**Issue by marmitoTH** [godotengine/godot#52518] opened 2021-09-09 18:13 UTC
### Godot version

v3.3.stable.official

### System information

Windows 10, GLES3, GTX1650

### Issue description

AnimationTree transitions have an undesired delay, it takes one frame, and sometimes more than one, for the sprite to change to the next animation. I thought it was a problem related to the game's logic, but it's not, I've been debugging it for hours analyzing the process frame by frame, it's definitely an AnimationTree bug.

### Steps to reproduce

To reproduce the bug in a minimal way, I coded a very simple logic. By holding right, the player will start the running animation. By holding space, the player position will offset down by 10 pixels and switch to the rolling animation.

Expectation: The player offsets down and starts playing the animation immediately.
Bug: The player offsets down, waits for one frame and then the animation starts playing.

![image](https://user-images.githubusercontent.com/25598040/132737631-571eee88-5d6a-4b1a-b1e4-81cf0d3a1bd1.png)

*The same behavior also happens when transitioning back to the previous animation.*

There's another bug, probably related to this one, but harder to reproduce. It seems like that when one animation is about to transition to another, and I switch to another animation, the last animation being played freezes for several frames before actually changing the sprite. My AnimationTree looks like this (the `Xfade Time` in both transitions is 0):

![image](https://user-images.githubusercontent.com/25598040/132738923-067daf6d-d691-427e-a2a0-ac39d591b1a8.png)

### Minimal reproduction project

[animation_tree_bug.zip](https://github.com/godotengine/godot/files/7138844/animation_tree_bug.zip)

**Comment by Calinou** [comment] 2021-09-10 00:03
cc @TokageItLab

**Comment by TokageItLab** [comment] 2021-09-10 00:52
I remember a similar problem has been reported with StateMachine.
https://github.com/godotengine/godot/issues/46798

**Comment by TokageItLab** [comment] 2021-09-10 02:29
@marmitoTH @Calinou This PR problem is caused by the fact that the `AnimationNodeTransition::process()` takes place before the property set in the same frame. So, the solution is to set the `ProcessMode` of `AnimationTree` to `Manual` and use `AnimationTree.advance()` in GDScript.

Ex) animation.gd
```gd 
func _process(delta):
	handle_motion(delta)
	handle_animation()
	$"AnimationTree".advance(delta)
```

Nevertheless, it might be better to default to doing the animation `process()` at the end of the frame. So, we should discuss this with @reduz in the near future.

cc @lyuma @fire @SaracenOne

**Comment by marmitoTH** [comment] 2021-09-10 12:26
> @marmitoTH @Calinou This issue is caused by the fact that the `AnimationNodeTransition::process()` is run before the setting properties in the frame. So, the solution is to set the `ProcessMode` of `AnimationTree` to `Manual` and use `AnimationTree.advance()` in GDScript.
> 
> e.g. animation.gd
> 
> ```gap
> func _process(delta):
> 	handle_motion(delta)
> 	handle_animation()
> 	$"AnimationTree".advance(delta)
> ```
> 
> Nevertheless, it might be better to default the animation `process()` to run at the end of the frame. So, we should discuss this with @reduz in the near future.
> 
> cc @lyuma @fire @SaracenOne

I've tried it before and didn't work, still have the same issue. Just tried it again and the player still offsets down first before switching the animation but seems to happen only some times. The same bug happens when switching back to the ground animation.

![image](https://user-images.githubusercontent.com/25598040/132852522-31e76827-fceb-4798-8f4c-68a1cee40ecc.png)

Here's a video where you can skip frame by frame: https://i.imgur.com/hPnTdYg.mp4
And here's the updated project: [animation_tree_bug.zip](https://github.com/godotengine/godot/files/7143685/animation_tree_bug.zip)

**Comment by marmitoTH** [comment] 2021-09-10 15:05
@TokageItLab I changed it to Manual, I did exactly what you suggested.
![image](https://user-images.githubusercontent.com/25598040/132874880-1c368a55-7081-4d2b-a767-87f471847074.png)
![image](https://user-images.githubusercontent.com/25598040/132874948-697e90a8-05a5-4afe-af58-269febf42606.png)
I guess this is another bug then?

**Comment by TokageItLab** [comment] 2021-09-10 15:18
@marmitoTH If I change `_process()` to `_physics_process()`, won't that cause visual problems?

**Comment by TokageItLab** [comment] 2021-09-10 15:22
@marmitoTH Separately above, how about if the `AnimationPlayer` is also updated using `Manual` and `advance()`?

**Comment by marmitoTH** [comment] 2021-09-10 15:27
@TokageItLab It causes the same problem, seems to make no difference at all. I tried with both `_process` and `_physics_process`, using `Manual` for the `AnimationPlayer` and the `AnimationTree`. It takes at least one frame to switch the animation, it's inconsistent though, some times the problem doesn't happen (just like I mentioned before and how you can see in the video).

**Comment by TokageItLab** [comment] 2021-09-10 15:37
In the video, the fps was too high to be recognized, but I was able to reproduce the problem by fixing the fps at 5 in the Debug settings. I will investigate.

**Comment by ICatRegister** [comment] 2021-09-10 17:19
In my project, manual advance really switches animations within the current frame, no more one frame delay. However i am using `AnimationNodeStateMachinePlayback`, not the `AnimationNodeStateMachineTransition `

**Comment by TokageItLab** [comment] 2021-09-10 17:31
I found only one place where the calculation was wrong (#52543). After applying this fix and changing the animation interpolation method to "linear" instead of "discrete", the sample project should transition well.

I will have to look into the issue of the different behavior depending on the animation interpolation method, but it may be a problem with the blending of discrete keys.

**Comment by TokageItLab** [comment] 2021-09-10 21:05
This issue will be fixed by #52543 and #52555.

**Comment by ICatRegister** [comment] 2021-09-11 12:07
> This issue will be solved by #52543 and #52555.

`AnimationNodeStateMachine ` node still has a one frame delay issue

**Comment by TokageItLab** [comment] 2021-09-11 14:38
@ICatRegister Is this a separate issue from using `ProcessCallback = Manual` & `advance()`? The two PRs above are for this issue. For `StateMachine`, the behavior is different and we need to proceed in #46798.

**Closed** 2021-09-20 12:42 UTC
Labels: bug, topic:animation

**Comment by berarma** [comment] 2021-09-21 11:20
I think this is related. If the animation in AnimationPlayer has the loop option enabled, when transitioning from one node to another one in the state machine, it might start replaying the old animation (just the first frame) then switch to the new animation.

Let's say I have a walking animation with loop enabled in AnimationPlayer, when AnimationTree advances from this animation to the idle animation it will play the first frame of the walking animation inbetween. The transition switch mode is AtEnd. It should transition exactly when the animation ends without playing any more frames.

It's like the transition may get delayed for one frame and for this time it keeps playing the old animation. It happens most of the time but not always.

When disabling the animation loop this doesn't happen, I guess it's not noticed, but I think the final frame is still being displayed for two frames before changing to the new animation.

I haven't tried the PRs, I'm trying on 3.4-beta4. I'll try it as soon as there's a new beta release available.
