### ISSUE TITLE
NavigationAgent doesn't know how to handle going up a ramp

### ISSUE THREAD

**Issue by warriormaster12** [godotengine/godot#57003] opened 2022-01-20 15:03 UTC
### Godot version

3.5 beta 1

### System information

Manjaro KDE i5-4570, Gtx 1060 6gb (495.44), 16 gb ddr3, GLES3

### Issue description

When I implemented a character for this game, my expectation was that the navigation system would have been able to tell the character to go up a ramp when player character is on another floor. What it does instead is it goes to the position that is bellow the target location.

![ezgif com-gif-maker](https://user-images.githubusercontent.com/33091666/150361757-55fd8917-2229-4aa7-932f-d753a4828206.gif)

### Steps to reproduce

1. create a level that includes multiple floors.
2. put player character into upper floor and ai character into lower floor

### Minimal reproduction project

https://github.com/warriormaster12/FinalStand

**Comment by warriormaster12** [comment] 2022-03-16 04:57
The bug still exists in version 3.5-beta 2

**Comment by akien-mga** [comment] 2022-04-25 09:28
CC @Scony @AndreaCatania

**Comment by warriormaster12** [comment] 2022-04-25 17:00
I'll have access to my project on the weekend so I'll send a working build then.

**Comment by Scony** [comment] 2022-04-25 17:50
I've run the demo and I can tell that the navigation mesh is fine - it looks exactly as expected. However, I'm not sure if the character-follow algorithm is fine. The demo is too complex to analyze.

**Comment by warriormaster12** [comment] 2022-05-01 15:40
After doing a bit more testing, yes my character-follow implementation had a bug that has been resolved by changing "navigation_agent.set_target_location" from _pre_tick function to Timer's timeout function. Now the character can move up the ramp without any issues.

**Comment by warriormaster12** [comment] 2022-05-01 15:50
Or maybe target_desired_distance might have caused some issues

**Comment by warriormaster12** [comment] 2022-05-01 15:56
![ezgif com-gif-maker](https://user-images.githubusercontent.com/33091666/166153909-b76801bb-6ecd-47d9-8735-6e2d02dc31e8.gif)

The red capsule has a target_desired_distance = 15 and the original ai character has it set to default value 1.

**Comment by warriormaster12** [comment] 2022-05-01 16:00
Uploaded updated version of the project on github
https://github.com/warriormaster12/FinalStand

**Comment by warriormaster12** [comment] 2022-05-04 02:33
@Scony

**Comment by Scony** [comment] 2022-05-04 20:04
@AndreaCatania

**Comment by smix8** [comment] 2022-05-14 00:21
@warriormaster12 

The upper floor is inaccessible for the agents cause the navmesh is cut-off.
The agent height setting in the NavigationMesh bake settings are to big for the actors.

If the NavigationMesh `agent_height` is lowered to 1.5 and navmesh rebaked the blue agent can follow to every single corner of the map just fine.

If the `target_desired_distance` is set to high the navigationagent will skip multiple path points at the same frame.
The hovering red agent gets constantly stuck on collision cause it skips many pathpoints ahead and wants to move in a straight line to the remaining point but that is not a pathfinding bug, just a property set wrong. If you lower the `target_desired_distance` back to something reasonable the red agent can follow just fine too.

If possible please test again with changed / rebaked navmesh and agent settings to verify.
I don't find a bug with pathfinding here just improper setup due to maybe a lack of documentation.

**Comment by smix8** [comment] 2022-05-19 21:53
@Calinou @akien-mga 
Can be closed as this is not a bug but another navigation setup / lack of documentation issue.

**Closed** 2022-05-19 21:56 UTC
Labels: bug, topic:navigation, topic:3d
