### ISSUE TITLE
Class Range cannot be used to create other Range based controls.

### ISSUE THREAD

**Issue by wyattbiker** [godotengine/godot#33585] opened 2019-11-13 00:17 UTC
**Godot version:**
3.2.beta1 (probably others)

**OS/device including version:**
Mac OS X

**Issue description:**
Trying to create a custom Range control using this abstract class. However it does not allow to be extended using `extend Range` keyword

Message:
`Script inherits from native type 'Range', so it can't be instanced in object of type: 'Control'`

**Steps to reproduce:**
Create a Control Scene, add a script extending Range.

**Comment by Zylann** [comment] 2019-11-13 01:27
It looks like your have put a script extending `Range` on a `Control` node. If you want to customize `Range`, the node type you create as a base must match the class you extend from.

**Comment by groud** [comment] 2019-11-13 12:06
That's an expected behavior, Control are not Ranges. Ranges are Control nodes but not the other way around. So you cannot put a script extending Range on a Control, that's normal.

Though, if useful, the Range class could be made not abstract (basically like the Container class), so that you can implement your own version of a Range.

**Comment by KoBeWi** [comment] 2020-05-27 15:13
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!

**Closed by KoBeWi** 2020-05-27 15:13 UTC
Labels: feature proposal, topic:gui
