### ISSUE TITLE
Continuous line2d points animation does not work

### ISSUE THREAD

**Issue by rt9391** [godotengine/godot#83384] opened 2023-10-15 12:21 UTC
### Godot version

4.2.beta1

### System information

win11

### Issue description

Continuous line2d points animation does not work
![line2dAniamtion](https://github.com/godotengine/godot/assets/91177204/1fc0d277-b82c-4b18-8c31-dbdc3cf8900f)
4.1.2.stable
![line2dAniamtion2](https://github.com/godotengine/godot/assets/91177204/ff34b265-f677-4d55-9ddb-ca494b727e05)
(the end key frame is not the same as the first key frame)
4.2.beta1

### Steps to reproduce

1.create a scene with line2d and animationPlayer
2.make some Continuous line2d points animation( move the points in the array )
3.the points do not change at all when the animation is set to Continuous 

### Minimal reproduction project

N/A

**Comment by TokageItLab** [comment] 2023-10-15 15:17
Dupe of https://github.com/godotengine/godot/issues/73342

**Closed by TokageItLab** 2023-10-15 15:17 UTC
Labels: bug, regression, topic:animation, topic:2d

**Comment by TokageItLab** [comment] 2023-10-15 15:20
However, as with A, this also has the meaning of bringing a latent bug to the surface, I will elevate the priority of the issue.
