### ISSUE TITLE
EditorImportPlugin not working in C#

### ISSUE THREAD

**Issue by hedgehog90** [godotengine/godot#24306] opened 2018-12-12 18:03 UTC
I know this is an area that is still in early stages, but has anyone managed to get EditorImportPlugin working in C#?
Everytime I try reimporting a scene with the custom script referencing an EditorImportPlugin script I get an error message:
```
Error running post-import script: res://Importer.cs
```

The script in question is simply:

```
#if TOOLS
using Godot;
using Godot.Collections;
using System;

public class Importer : EditorImportPlugin
{
    public override int Import(string sourceFile, string savePath, Dictionary options, Godot.Collections.Array rPlatformVariants, Godot.Collections.Array rGenFiles)
    {
        GD.Print("Import", sourceFile);
        return base.Import(sourceFile, savePath, options, rPlatformVariants, rGenFiles);
    }
}
#endif
```

**Comment by KoBeWi** [comment] 2020-06-29 21:31
Can anyone still reproduce this bug in [Godot 3.2.2](https://godotengine.org/article/maintenance-release-godot-3-2-2) or any later release?

If yes, please ensure that an up-to-date Minimal Reproduction Project (MRP) is included in this report (a MRP is a zipped Godot project with the minimal elements necessary to reliably trigger the bug). You can upload ZIP files in an issue comment with a drag and drop.

**Comment by KoBeWi** [comment] 2020-09-28 22:33
Closing due to lack of update. Please comment if you can still reproduce this issue in the latest stable version of Godot.

**Closed by KoBeWi** 2020-09-28 22:33 UTC
Labels: bug, topic:mono
