### ISSUE TITLE
Child selection icon no longer automatically updating and throws error

### ISSUE THREAD

**Issue by filipworkson** [godotengine/godot#46323] opened 2021-02-22 18:20 UTC
**Godot version:**

3.2.4 RC2

**OS/device including version:**

NVIDIA GTX1650S
GLES2 

**Issue description:**

Clicking on the item group button causes errors to show up and is not visually updating the select icon beside the node anymore. Adding or deleting a node makes the icon appear/disappear.

![a](https://user-images.githubusercontent.com/36826319/108751758-9bdfe400-7510-11eb-8e31-a1ebbaee3891.gif)

![image](https://user-images.githubusercontent.com/36826319/108750582-33443780-750f-11eb-845a-de0bc52d0542.png)

**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by Calinou** [comment] 2021-02-22 19:04
Duplicate of https://github.com/godotengine/godot/issues/45988 (and others like https://github.com/godotengine/godot/issues/46047 and https://github.com/godotengine/godot/issues/46265). This should be fixed in the latest `3.2` branch.

**Closed by Calinou** 2021-02-22 19:04 UTC
