### ISSUE TITLE
Random particle life time doesn't affect 'over lifetime' changes

### ISSUE THREAD

**Issue by marianolarre** [godotengine/godot#63316] opened 2022-07-22 14:30 UTC
### Godot version

3.2.2.stable
EDIT: Also present in 3.4.4.stable

### System information

Windows 10

### Issue description

When particles have a random lifetime asigned, the properties that change over lifetime don't get compressed to end with the particle. Instead, the particles just disappear and cut off the animation.

For example, if you have fire particles that slowly fade out to 0 alpha, the random lifetime will have them pop instantly instead of fading out at a rate that would have them disappear in time for their new lifetime.

![1a380556c252990e3ed33dff75eb9e6c](https://user-images.githubusercontent.com/19352074/180461176-c644b476-7a00-44db-b837-9a4d6ae5225d.gif)

### Steps to reproduce

Make a particle system, asign an animation, a scale change or a color change for clearer effect. Give it a random lifetime of about 0.8, and observe as the particles' animations stay in sync

### Minimal reproduction project

[Particle lifetime problem.zip](https://github.com/godotengine/godot/files/9168472/Particle.lifetime.problem.zip)

**Comment by allenwp** [comment] 2022-07-22 17:22
Hi @marianolarre 

I downloaded your Minimal reproduction project and opened in with v3.4.4.stable.official [419e713a2]. I saw the following behaviour, which appears different than what your animated .gif image shows in the original post:

![particle lifetime problem](https://user-images.githubusercontent.com/17506573/180491680-1a7c9788-421a-491b-b30c-5863ae5bb32e.gif)

Should I be seeing something different or is this issue not correctly demonstrating itself on my setup (also Windows 10)?

**Comment by Calinou** [comment] 2022-07-22 17:27
Can you test 3.5rc6? See https://github.com/godotengine/godot/issues/54993.

**Comment by allenwp** [comment] 2022-07-22 17:37
Here's what I see I see in v3.5.rc7.official [e71cf7c56]:

![particle lifetime problem - 3 5 rc7](https://user-images.githubusercontent.com/17506573/180493936-c9e5f2af-54bd-4f64-80ed-e2a9b5ee5f13.gif)

I still don't see the issue you described in the original post...

**Comment by marianolarre** [comment] 2022-07-26 02:47
So its fixed in another version? Thats good to hear. Thank you!
My appologies Calinou, i didn't find that Issue before posting this one.

**Comment by Calinou** [comment] 2022-07-26 15:04
Duplicate of https://github.com/godotengine/godot/issues/54993 (fixed in 3.5.rc7).

**Closed by Calinou** 2022-07-26 15:04 UTC
Labels: bug, topic:rendering
