### ISSUE TITLE
I propose moving ~/.godot folder to ~/.config/godot on linux machine

### ISSUE THREAD

**Issue by razvanc87** [godotengine/godot#3594] opened 2016-02-05 11:20 UTC
Well... what the title says. It seems this is the trend nowadays...

**Comment by akien-mga** [comment] 2016-02-05 11:29
Duplicate of #3513 :)

**Closed by akien-mga** 2016-02-05 11:29 UTC
Labels: archived

**Comment by razvanc87** [comment] 2016-02-05 11:33
@akien-mga, well then... I didn't quite know what to search for :P. Thanks!

**Comment by akien-mga** [comment] 2016-02-05 11:43
That's fine, that's why we triage the issues ;) This link to this issue in #3513 is still an interesting addition so that we can consider using the default XDG_CONFIG_HOME path (~/.config/godot) on Linux when we rework this stuff for 3.0.
