### ISSUE TITLE
Changing a directory/folder's case causes "A file or folder with this name already exists." error

### ISSUE THREAD

**Issue by JarLowrey** [godotengine/godot#16644] opened 2018-02-12 14:31 UTC
True story, Godot 3.0

Example: `Gun/` -> `gun/` + error

**Comment by eon-s** [comment] 2018-02-12 14:36
I'm not sure if I understand the description, but looks like a duplicate of #16384

**Comment by vnen** [comment] 2018-02-12 14:43
Yes, it's a duplicate.

**Comment by vnen** [comment] 2018-02-12 14:44
Also, this is a platform-specific issue, that's why we ask for the OS in the issue template...

**Closed by vnen** 2018-02-12 14:43 UTC

**Comment by JarLowrey** [comment] 2018-02-12 14:57
Sorry about that. It is a duplicate, Win10
