### ISSUE TITLE
Label node turns low FPS

### ISSUE THREAD

**Issue by burstina** [godotengine/godot#26489] opened 2019-03-02 14:31 UTC
found none

**Godot version:**
3.0.6v - 3.1 beta 1-9

**OS/device including version:**
Windows 10

**Issue description:**
I waited a couple of month before posting this issue, because I'd rather think about misconfiguraton or miscoding. Then I had a confrontation with other godot developers and we both found this to be an engine issue:
Using Label nodes in an Android scrolling environment, FPS drastically hit the ground. Windows seems to be the lesser affected, probably because of better graphic chipset performance and support.

I used Arial Black and Arial as label's fonts.

My application is quite simple: it shows kind of "menu" made of 50 rows, 3 labels per row (description, quantity and price), for a total of 150 labs.
When I drag screen up and down(Camera2D), FPS turns from 50 to 7-8.

As a workaround, I run-time sampled each label to a new sprite, having 150 sprites instead of 150 labels. It works great, now I have always 60fps on Android, and over 500 on Windows.

Then I tried to add a single row as 3 labels (not sprites) and FPS dropped to 45.

**Steps to reproduce:**
Camera2D, allow scrolling
Panel
150 Label nodes as Panel's children

**Minimal reproduction project:**
My current project is not good since it uses external DB to generatelabels.
I'd like to attach one asap.

**Comment by Zireael07** [comment] 2019-03-02 14:57
I believe this is a duplicate of existing issue, but I can't find it atm.

**Comment by Calinou** [comment] 2019-03-02 16:23
Duplicate of https://github.com/godotengine/godot/issues/19917.

**Closed by Calinou** 2019-03-02 16:23 UTC
