### ISSUE TITLE
While saving other scene, if you've created and drawn a new TileMap, half it's blocks dissapear.

### ISSUE THREAD

**Issue by codeeg** [godotengine/godot#31076] opened 2019-08-04 14:03 UTC
**Godot version: 3.1.1**

**OS/device including version: Windows 10 v1809**
Intel HD Graphics, GLES 2.

**Issue description:**
I had created a new TileMap node, and a new Resource to go with it, and started drawing a map. After the map was done, before saving the scene where the new TileMap was on, i traveled onto another, changed a sprite and saved, to then see, in a interval of 2 blocks, they had dissapeared. Not a visual or spacing bug, they dissapeared and the only and best way i found to fix it was to redraw the blocks that went missing.
![Capture](https://user-images.githubusercontent.com/39866810/62424506-952b1b00-b6a5-11e9-88b8-5a4904fc84ae.PNG)

**Steps to reproduce:**

*1.* Create a new TileMap and choose a Resource for it.
*2.* Draw anything in the map.
*3.* Change scenes.
*4.* Save the other scene you've just navigated to.
*5.* Return to the scene with the TileMap to witness the chaos.

**Minimal reproduction project:**
[TileMapBug.zip](https://github.com/godotengine/godot/files/3464951/TileMapBug.zip)

**Comment by bojidar-bg** [comment] 2019-08-04 14:47
Duplicate of #29312.

**Closed by bojidar-bg** 2019-08-04 14:47 UTC
