### ISSUE TITLE
Path3D editor points need translation gizmo and 3D shape.

### ISSUE THREAD

**Issue by lucidpetal** [godotengine/godot#58975] opened 2022-03-10 08:31 UTC
### Godot version

3.4 stable

### System information

Linux

### Issue description

The points in the 3D path editor are difficult to author because they do not have placement gizmos are have the same size regardless of distance. The points are currently represented by small orange circles similar to Path2D, but these give no orientation clues in 3D. Moving them in the 3D editor is also solely based on camera perspective, which is unreliable.

I suggest giving the points a small 3D spherical shape and a translation gizmo. This will make them easier to position accurately in a 3D scene, and makes it easier to see where they are in the 3D world. These points are used in a lot of 3D plugins and tools, thus making them easier to control will be a significant improvement to the user experience for all those plugins.

I will be happy to do some work on this and contribute.

### Steps to reproduce

1. Download the test project below.
2. Try to create a smooth path through all the rings in the course.

### Minimal reproduction project

[3dpathediting.zip](https://github.com/godotengine/godot/files/8221505/3dpathediting.zip)

**Comment by Calinou** [comment] 2022-03-10 15:42
Duplicate of https://github.com/godotengine/godot-proposals/issues/527.

**Closed by Calinou** 2022-03-10 15:42 UTC
Labels: enhancement, topic:editor, topic:3d
