### ISSUE TITLE
Custom build features doesn't work (3.0.6)

### ISSUE THREAD

**Issue by DrMoriarty** [godotengine/godot#22444] opened 2018-09-26 07:42 UTC
**Godot version:**

Godot 3.0.6 official

**OS/device including version:**

MacOSX 10.13.6
Android 7.1.2

**Issue description:**

I have set additional building feature 'test':

![2018-09-26 10 40 26](https://user-images.githubusercontent.com/1177068/46064659-a8618600-c178-11e8-8f28-27ca0490d243.png)

I checked features at game start:
```
func _ready():
    OS.set_keep_screen_on(true)
    get_tree().set_auto_accept_quit(false)
    print("Android: %s"%var2str(OS.has_feature('Android')))
    print('Debug: %s'%var2str(OS.has_feature('debug')))
    print('Test: %s'%var2str(OS.has_feature('test')))
```

The output for release android build is:

```
09-26 10:35:36.921: I/godot(11368): Android: true
09-26 10:35:36.921: I/godot(11368): Debug: false
09-26 10:35:36.921: I/godot(11368): Test: false
```

**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by akien-mga** [comment] 2018-09-26 07:46
Duplicate of #16928, fixed by #20240 (which is labelled for cherry-picking into 3.0 branch).

**Closed by akien-mga** 2018-09-26 07:46 UTC
