### ISSUE TITLE
NormalMaps are weird in 4.4-dev3

### ISSUE THREAD

**Issue by caioraphael1** [godotengine/godot#97774] opened 2024-10-03 16:10 UTC
### Tested versions

Ok in 4.4-dev2, weird in 4.4-dev3

### System information

Windows 10, Ryzen 3 3300x, 16gb RAM 2666mhz, GTX 1660 6gb.

### Issue description

I don't know what's happening. I just opened my project on in 4.4-dev3, and there were a lot of regions completely black. After tracking the source of the problem, it seems to be related to the normalmap from a CanvasTexture

https://github.com/user-attachments/assets/d14b9cc7-b736-4217-84ef-a047dcf6276d

### Steps to reproduce

I don't know :/, I just happened after opening the project in 4.4-dev3

### Minimal reproduction project (MRP)

Sry

**Comment by AThousandShips** [comment] 2024-10-03 17:13
Please upload an MRP to make this easier to test and fix
- A small Godot project which reproduces the issue, with no unnecessary files included. Be sure to not include the `.godot` folder in the archive (but keep `project.godot`).
- Having an MRP is very important for contributors to be able to reproduce the bug in the same way that you are experiencing it. When testing a potential fix for the issue, contributors will use the MRP to validate that the fix is working as intended.
- Drag and drop a ZIP archive to upload it (max 10 MB). **Do not select another field until the project is done uploading.**
- **Note for C# users:** If your issue is *not* C#-specific, please upload a minimal reproduction project written in GDScript. This will make it easier for contributors to reproduce the issue locally as not everyone has a .NET setup available.

**Comment by DarioSamo** [comment] 2024-10-03 17:14
CanvasRenderer got a lot of changes in dev3 to introduce batching. I suspect some state related to the normal map might be leaking to the rest of the draw calls. I'd probably try with a commit before https://github.com/godotengine/godot/pull/92797 to start bisecting from.

**Comment by clayjohn** [comment] 2024-10-03 17:15
This might be fixed by https://github.com/godotengine/godot/pull/97340 which fixes a couple of bugs introduced by batching

**Comment by Lielay9** [comment] 2024-10-03 18:57
MRP (Forward/Mobile), content in tree after a CanvasTexture with NormalMap are dimmed.
[normaltexturebug.zip](https://github.com/user-attachments/files/17248630/normaltexturebug.zip)
Issue in Master [5ccbf6e4c]:
<img width="799" alt="Screenshot 2024-10-03 214135" src="https://github.com/user-attachments/assets/71f5ee17-7e07-4412-a90a-8f1a903408b4">

#97340 (Couple day old artifact), doesn't have this issue:
<img width="779" alt="Screenshot 2024-10-03 214305" src="https://github.com/user-attachments/assets/85e01624-839c-4fbf-81fc-62b10c78e3da">


Didn't bisect, but I had builds directly before and after https://github.com/godotengine/godot/pull/92797 and it doesn't seem to be caused by it (unless I messed up which build was which) but the behavior does seem related to batching.

**Comment by clayjohn** [comment] 2024-10-03 20:05
This might have been caused by https://github.com/godotengine/godot/pull/97554 which was a hotfix for a different issue introduced by batching. 

I checked and https://github.com/godotengine/godot/pull/97340 does fix this PR!

**Comment by Lielay9** [comment] 2024-10-03 20:10
> This might have been caused by #97554 which was a hotfix for a different issue introduced by batching.
> 
> I checked and #97340 does fix this PR!

Out of curiosity, and since I had builds for that too, I can confirm 4d635b7a3afafb62e9d9e2e09f00e5d62d317a8b was indeed the cause of the issue.

**Closed** 2024-10-30 00:28 UTC
Labels: bug, topic:rendering, confirmed, regression
