### ISSUE TITLE
Godot becomes smooth and then laggy!

### ISSUE THREAD

**Issue by Raj2032** [godotengine/godot#15143] opened 2017-12-29 04:19 UTC
**Godot version:**
Godot 3.0 Beta 1 and Beta 2

**OS/device including version:**
Windows 10

**Issue description:**
When rotating around the scene, sometimes Godot will be very smooth, but at other times it will rotate as if you are watching a movie filled in 30 frames per second.

**Comment by LinuxUserGD** [comment] 2017-12-29 22:47
Windows 10 32 bit or Windows 10 64 bit? What graphic driver (see output)?

**Comment by Raj2032** [comment] 2017-12-30 07:12
I have Windows 10 64 bit. I think the driver I have installed is Intel

**Comment by vnen** [comment] 2017-12-30 20:30
You need to give more details of what you were doing. Is the scene complex? Is there more stuff in the parts where it slows down? Can you provide a test scene where it happens?

Run `dxdiag` and look at the Display tab to see the graphics card and driver.

**Comment by Raj2032** [comment] 2017-12-31 03:22
It is an empty scene, just rotating around becomes a bit laggy, there is no
way for me to show you a test scene for something that is empty :/ I don't
have a graphics card, I did run dxdlag and it does not display the graphics
card and the drivers.

**Comment by vnen** [comment] 2017-12-31 04:04
Well, you should be able to tell what integrated graphics you have at least. It's very hard for devs to do anything about it if they can't reproduce and don't have info about your system to determine the cause of the hiccups.

**Comment by Raj2032** [comment] 2017-12-31 07:05
I have intel CPU 64 bit 2.7 GHz - 2.9 GHz and I have 16 GB of Ram. I don't
have a graphics card in my computer.

**Comment by LinuxUserGD** [comment] 2018-01-01 00:06
If you run Godot, you should get an output, e. g. "OpenGL ES 3.0 Renderer: Mesa DRI Intel(R) HD Graphics 620 (Kabylake GT2)"

**Comment by Raj2032** [comment] 2018-01-01 00:09
This is what I see "OpenGL ES 3.0 Renderer: Intel(R) HD Graphics 620"

**Comment by LinuxUserGD** [comment] 2018-01-01 00:09
Most computers and smartphobes have a graphic card. If you can run a Godot scene (which uses OpenGL), you have the right graphic drivers installed on your computer. The devs need to know your graphic card or your graphic card driver to be able to reproduce the issue.

**Comment by Raj2032** [comment] 2018-01-01 00:16
Oh ok well did I show all the necessary things so that the devs can
reproduce the problem?

**Comment by LinuxUserGD** [comment] 2018-01-01 00:34
Yes :+1:

**Comment by Raj2032** [comment] 2018-01-02 08:29
So have you guys been able to find out what the issue is by any chance?

**Comment by groud** [comment] 2018-01-02 08:44
I think this issue is a duplicate of #9725. It seems we have performances problem with Intel GPUs

**Comment by Raj2032** [comment] 2018-01-02 11:24
But for me why is it that it goes very smoothly at one point, but at
another point it gets laggy?

**Comment by mhilbrunner** [comment] 2018-01-12 04:11
Closing as duplicate of #9725 for now.

**Closed by mhilbrunner** 2018-01-12 04:11 UTC
Labels: bug
