### ISSUE TITLE
Improve Number Input for Inspector.

### ISSUE THREAD

**Issue by toger5** [godotengine/godot#9431] opened 2017-06-28 08:33 UTC
since the number input field inside the Inspector already has the option to drag up/down to decrease/increase the slider seems unnecessary. I never used it...

Would it be worth to remove it completely?

The drag gesture could be changed to left/right to be more similar to the slider.

**Comment by akien-mga** [comment] 2017-06-28 08:51
I agree that most sliders are mainly useless, and potentially harmful in the inspector.

We can either remove them as proposed here, or we can generalise the use of reasonable property hint ranges that tell the slider what the min and max values should be.

For the latter, we need IMO to distinguish two sets of hints:
- min and max value for the text input (should be any *possible* value, e.g. 100,000 particles is OK)
- min and max value for the slider (should be any *reasonable* value that makes sense to edit via a slider, e.g. 0 to 1000 particles).

**Comment by homer666** [comment] 2017-06-28 08:59
@toger5 I think the drag-slide axis should be left vertical, as that's how I've seen it function in most other programs.

@akien-mga's proposal would definitely go a long way towards making the slider an actually useful utility in a lot of cases, because as it is right now.........

![peek 2017-06-28 18-47](https://user-images.githubusercontent.com/27100585/27628457-6db0bc1c-5c32-11e7-9492-020400c188f2.gif)

Yeah.

**Comment by homer666** [comment] 2017-06-28 09:03
I'll also note that there's the issue of the slider drawing over whatever is under the field it's changing. It makes it a little awkward to access the field under it without accidentally clicking on the slider.

**Comment by toger5** [comment] 2017-06-28 09:16
I think we should get rid of the slider completely. The slider also has the issue that you have to be precise with the mouse to grab the slider -> slows down workflow...
Also a slider is limited in the range of mouse movement is supports. when wrapping the mouse the max min mouse drag distance could be increased to 10-20cm.

### other advantages of wrapped horizontal mouse dragging:
 - longer mouse range, therefore more precise
 - no additional ui element. Cleaner
 - less clicks: just drag, instead of clicking the number, and than clicking on the grabber (precisely)
 - (weaker point) more similar to blender. Godot will be used a lot alongside blender when the new  the new 3d engine is released!
 - allows for modifiers like `shift` for precise movement.
 - arrows can be placed on the left + right (instead of on top of each other), this decreases the probability of pressing the wrong arrow when increasing/ decreasing by one! easier/ faster to use.

I also really like the point made by @akien-mga that the limits should be implemented everywhere.

**Comment by homer666** [comment] 2017-06-28 09:24
Hmmm, having the number fields function like they do in Blender would be pretty cool, actually.

**Comment by Zireael07** [comment] 2017-06-28 09:35
@homer666 Hehe, yeah, I ran into that too. Either instate sensible default limits everywhere or dump sliders in editor.

**Comment by Zylann** [comment] 2017-06-28 09:44
One issue about removing arrows and sliders is, the user won't know it's possible to drag the field that way. I re-discovered this a few days ago, didn't remember it even existed.

**Comment by toger5** [comment] 2017-06-28 09:47
@Zylann I think the arrows should not be removed, just moved to the left/right. instead of stacking them at the right.

They are useful for `increasing by 1` and as you mentioned indicating the direction to change the value.

**Comment by homer666** [comment] 2017-06-28 10:12
I'm personally 100% down with the way Blender does it. All the functionality a number field should have, packed into one element:

![peek 2017-06-28 19-54](https://user-images.githubusercontent.com/27100585/27631875-65ac4a1c-5c3d-11e7-87ec-22d55dee5913.gif)

I don't know how well this would work with properties that have two or more numerical fields (position for example), but I think that's its own issue as the current number field system isn't even applied there.

**Comment by Zylann** [comment] 2017-06-28 11:28
It's not shown on the Blender screenshot, but seeing the slider position can also help to at a glance (it's usually shown as a shade of grey in the background). Other than that the Blender spinboxes work the same, except they are horizontal.

**Comment by toger5** [comment] 2017-06-28 11:32
@Zylann I really like the idea of the grey shade, which indicates the slider like a status bar. That would also be another reason for horizontal scrubbing, since the bar has more space -> would be more precise horizontally.

**Comment by homer666** [comment] 2017-06-28 11:33
From what I've seen they tend to be used for percentage values, or values that are between 0 and 1. Could be really useful:
![peek 2017-06-28 21-31](https://user-images.githubusercontent.com/27100585/27635169-51f237be-5c49-11e7-9975-e5ed7910b54e.gif)

(if the gifs are annoying just let me know!)

**Comment by sergey-push** [comment] 2017-06-29 03:37
what could also be done is adjustable scrolling (as a value gradient) when no limits are provided. 
e.g. when you are close to the center it will slowly increase (15 units per cm), but when you drag closer to the edges it will increase by a lot more (100 units per cm). When mouse released, it will re-center.

**Comment by reduz** [comment] 2017-08-07 01:39
The propertry editor needs to be rewritten to allow this kind of things better. This way we can also put buttons in there, or graphical editors in a way that makes more sense (more akin to Blender or Unity).

However, need to push 3.0 out first. As such, kicking this for 3.1

**Comment by toger5** [comment] 2017-08-07 10:13
@reduz It would be great if we could just pass a control node which than gets added as a child to a Item Column. than it is really easy to change how different inputs interact with user input and how they are drawn.

This also would allow to get rid of some of the tremendously huge switch statements. By having objects for each type in a Hash map and than we could just pass the correct object (control node with the input elements for that type. example vector, int...) and connect it to the property of the object.

**Comment by Zylann** [comment] 2017-08-07 10:56
@toger5 one advice though, going the "all-controls" way can be performance-expensive, knowing that the editor's UI isn't the fastest compared to Blender (saw this advice in several GUI frameworks already, Qt, WPF). IMGUI or Blender manage to get amazing perfs though, I'd like to see how it comes up^^

**Comment by kubecz3k** [comment] 2018-04-03 11:22
First of all thank you for your report and sorry for the delay.

We released Godot 3.0 in January 2018 after 18 months of work, fixing many old issues either directly, or by obsoleting/replacing the features they were referring to.

We still have hundreds of issues whose relevance/reproducibility needs to be checked against the [current stable version](https://godotengine.org/download), and that's where you can help us.
**Could you check if the issue that you described initially is still relevant/reproducible in Godot 3.0 or any newer version, and comment about its current status here?**

For bug reports, please also make sure that the issue contains detailed steps to reproduce the bug and, if possible, a zipped project that can be used to reproduce it right away. This greatly speeds up debugging and bugfixing tasks for our contributors.

Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

Thanks in advance.

*Note: This message is being copy-pasted to many "stale" issues (90+ days without activity). It might happen that it is not meaningful for this specific issue or appears oblivious of the issue's context, if so please comment to notify the Bugsquad about it.*

**Comment by akien-mga** [comment] 2018-05-16 12:41
The slider has been rewritten in 005b69c, and a new feature was added in dfd13316 to allow limiting the values that can be set with the slider (with PROPERTY_HINT_RANGE) while allowing greater or lesser manual input with the `or_greater` and/or `or_lesser` hints.

So I think most issues outlined here should be fixed. If not, they probably need to be recontextualized for the new system in 3.1, so I think it would be worth discussing in a new issue for clarity.

Note that only a handful of properties currently use the new optional `or_greater` or `or_lesser` hints, so more of those could be added. Similarly, some current non-limited fields should likely get a limited range (like the width in the above GIF, which could use e.g. `"1,4096,1,or_greater"`).

**Closed by akien-mga** 2018-05-16 12:41 UTC
Labels: discussion, enhancement, topic:editor, usability
