### ISSUE TITLE
macOS exported project don't run with "dot" in the name

### ISSUE THREAD

**Issue by bruvzg** [godotengine/godot#15188] opened 2017-12-30 10:08 UTC
**Godot version:**
Godot 3, beta 2
Godot 3, master 99960d9

**OS/device including version:**
macOS 10.13.2 (17C88)

**Issue description:**
Regression form: https://github.com/godotengine/godot/pull/11343

Exported project immediately exits when opening if bundle/executable/pck file name contains `.` (dot), with following error in console:
```
Error: Could not load game path '.'.
```

**Steps to reproduce:**
Export project with "dot" in the name e.g., `Test Project 2.0`

- [x] I searched the existing [GitHub issues](https://github.com/godotengine/godot/issues?utf8=%E2%9C%93&q=is%3Aissue+) for potential duplicates.

**Comment by haxpor** [comment] 2017-12-30 11:20
Confirm I faced the same issue (#15183). I have to rename the project name via Godot launcher although its project directory can include "dot".

**Comment by akien-mga** [comment] 2018-01-05 10:09
We have now entered release freeze for Godot 3.0 and want to focus only on release critical issues for that milestone. Therefore, we're moving this issue to the 3.1 milestone, though a fix may be made available for a 3.0.x maintenance release after it has been tested in the master branch during 3.1 development. If you consider that this issue is critical enough to warrant blocking the 3.0 release until fixed, please comment so that we can assess it more in-depth.

**Comment by haxpor** [comment] 2018-01-05 12:12
For me, it's fine and not critical as I can avoid having "dot" in the project name. Not sure about the owner of this issue.

**Comment by reduz** [comment] 2018-09-06 16:16
Maybe a check should be added for OSX and a warning?

**Comment by akien-mga** [comment] 2018-09-10 06:59
CC @BastiaanOlij, it seems to be caused by #11343.

**Comment by BastiaanOlij** [comment] 2018-09-10 10:33
Wow, thats going down memory lane..  Not sure what is the best fix here.

The original problem was that this function is meant to strip off the .exe from a windows executable file name to create the package file. So a "mygame.exe" becomes "mygame.pck". 
On Mac OS X the issue is that the path becomes something like /Applications/mybundle.app/Contents/MacOS/mygame
So finding the last . returns the wrong string.
By including the get_file() in there it would get the filename first by stripping off the path, then try and strip of the extension (the original fix was adding get_file, then the PR references re-added the get_basename when it broke the windows export).

But if you don't have an extension but instead a version number, it would end up with "Test Project 2.pck" in the example above, which does not exist, which means it keeps looking for further options and finally failing.

On face value, maybe we need to specifically check for .exe at the end and if its found, strip off .exe and leave any other path part of the filename alone? I don't know if any of the other platforms might need different logic?

**Comment by akien-mga** [comment] 2018-09-10 12:17
> On face value, maybe we need to specifically check for .exe at the end and if its found, strip off .exe and leave any other path part of the filename alone? I don't know if any of the other platforms might need different logic?

It shouldn't be specifically .exe, as e.g. Linux uses `.x86_64` on 64-bit. But `EditorExportPlatform::get_binary_extension` can be used to know the binary extension of the target platform, and strip it if non empty.

**Comment by akien-mga** [comment] 2018-10-24 18:18
#23259 should fix it, tests welcome to make sure that there are no regressions.

**Closed** 2018-10-25 08:57 UTC
Labels: bug, platform:osx, topic:porting

**Comment by colugomusic** [comment] 2020-12-01 14:52
This bug is present again in Godot 3.2.3 stable on macOS Big Sur.

**Comment by Calinou** [comment] 2020-12-01 15:00
@colugomusic Please open a new issue with a minimal reproduction project attached.
