### ISSUE TITLE
Godot 4 Mono - Can't set default value for exported variable of type generic Godot.Collections.Array<T>

### ISSUE THREAD

**Issue by BraydenCarlson** [godotengine/godot#68074] opened 2022-10-31 07:55 UTC
### Godot version

v4.0.beta3.mono.official [01ae26d31]

### System information

Windows 10

### Issue description

When attempting to set a default value for an exported variable of the generic type `Godot.Collections.Array<T>` with a specified type, an error is thrown and the default value is not set in the editor.

Example:
```C#
// Works
[Export]
private Godot.Collections.Array resources1 = new();

// Doesn't work
[Export]
private Godot.Collections.Array<Resource> resources2 = new();
```
Building or running the game then throws this error and a default value is not set in the editor:
```
E 0:00:00:0660   void Godot.Bridge.ScriptManagerBridge.GetOrCreateScriptBridgeForPath(Godot.NativeInterop.godot_string* , Godot.NativeInterop.godot_ref* ): Attempted to convert an unmarshallable managed type to Variant. Name: 'Godot.Collections.Dictionary`2[[System.String, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Int32, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].
  <C++ Source>   modules/mono/glue/runtime_interop.cpp:1234 @ godotsharp_pusherror()
  <Stack Trace>  Godot.NativeInterop.NativeFuncs.generated.cs:1453 @ void Godot.NativeInterop.NativeFuncs.godotsharp_pusherror(Godot.NativeInterop.godot_string& )()
                 GD.cs:202 @ void Godot.GD.PushError(System.String )()
                 Marshaling.cs:300 @ Godot.NativeInterop.godot_variant Godot.NativeInterop.Marshaling.ConvertManagedObjectToVariant(System.Object )()
                 ScriptManagerBridge.cs:963 @ void Godot.Bridge.ScriptManagerBridge.GetPropertyDefaultValuesForType(System.Type , IntPtr , IntPtr )()
                 ScriptManagerBridge.cs:906 @ void Godot.Bridge.ScriptManagerBridge.GetPropertyDefaultValues(IntPtr , IntPtr )()
                 Godot.NativeInterop.NativeFuncs.generated.cs:154 @ void Godot.NativeInterop.NativeFuncs.godotsharp_internal_reload_registered_script(IntPtr )()
                 ScriptManagerBridge.cs:479 @ void Godot.Bridge.ScriptManagerBridge.CreateScriptBridgeForType(System.Type , Godot.NativeInterop.godot_ref* )()
                 ScriptManagerBridge.cs:424 @ void Godot.Bridge.ScriptManagerBridge.GetOrCreateScriptBridgeForType(System.Type , Godot.NativeInterop.godot_ref* )()
                 ScriptManagerBridge.cs:409 @ void Godot.Bridge.ScriptManagerBridge.GetOrCreateScriptBridgeForPath(Godot.NativeInterop.godot_string* , Godot.NativeInterop.godot_ref* )()
```
You can see here that the first example gets a default value and the second one does not.
![image](https://user-images.githubusercontent.com/16909492/198958022-4abbfc93-3c99-429d-9fad-4d55a6625d80.png)

### Steps to reproduce

1. Create an exported variable of type `Godot.Collections.Array<T>` with a specified type for `T`. In my testing both Godot types and regular C# types like `int` don't work.
```C#
[Export]
private Godot.Collections.Array<Resource> resources = new();
```
2. Build or run the project. You should see an error and that the exported variable doesn't get a default value.

**Comment by raulsntos** [comment] 2022-10-31 11:05
Duplicate of https://github.com/godotengine/godot/issues/65883

**Closed by raulsntos** 2022-10-31 11:05 UTC
Labels: bug, topic:dotnet
