### ISSUE TITLE
Incorrect error message in parsing shader script in escn file

### ISSUE THREAD

**Issue by Jason0214** [godotengine/godot#23699] opened 2018-11-14 03:46 UTC
**Godot version:**

Godot 3.0.6

**OS/device including version:**

macOS 10.13

**Issue description:**

In importing a ESCN scene with shader script, error message thrown saying **Expected shader_type at beginning of shader**, however, shader are all correctly started with `shader_type` statement, so might be some issue in lexing shader script.  By the way, although the error is thrown, the scene could be open correctly at least on my platform.

<img width="966" alt="screen shot 2018-11-13 at 19 37 42" src="https://user-images.githubusercontent.com/19422835/48458760-7930c380-e77c-11e8-98ba-02886f63cd2a.png">

**Steps to reproduce:**
1. open attached zipped scene in a godot project
2. see the Output in the editor tabe
Note that it only happened in converting the escn to scn file, so the second time you want to reproduce it, you need to remove all the related .import files first.

**Minimal reproduction project:**

[material_anistropy.escn.zip](https://github.com/godotengine/godot/files/2579107/material_anistropy.escn.zip)

**Comment by reduz** [comment] 2019-01-25 16:50
I think this was fixed, and can't reproduce with above test project. Closing.

**Closed by reduz** 2019-01-25 16:50 UTC
Labels: bug, topic:import
