### ISSUE TITLE
Better collada: UnboundLocalError: local variable 'img_tmp_path'

### ISSUE THREAD

**Issue by beniwtv** [godotengine/godot#1302] opened 2015-01-24 17:02 UTC
Hi,

I think I have found a bug with the collada exporter. I get the following traceback:

```
Traceback (most recent call last):
  File "/home/xxx/.config/blender/2.73/scripts/addons/io_scene_dae/__init__.py", line 179, in execute
    return export_dae.save(self, context, **keywords)
  File "/home/xxx/.config/blender/2.73/scripts/addons/io_scene_dae/export_dae.py", line 1646, in save
    exp.export()
  File "/home/xxx/.config/blender/2.73/scripts/addons/io_scene_dae/export_dae.py", line 1571, in export
    self.export_scene()
  File "/home/xxx/.config/blender/2.73/scripts/addons/io_scene_dae/export_dae.py", line 1269, in export_scene
    self.export_node(obj,2)
  File "/home/xxx/.config/blender/2.73/scripts/addons/io_scene_dae/export_dae.py", line 1223, in export_node
    self.export_node(x,il)
  File "/home/xxx/.config/blender/2.73/scripts/addons/io_scene_dae/export_dae.py", line 1212, in export_node
    self.export_mesh_node(node,il)
  File "/home/xxx/.config/blender/2.73/scripts/addons/io_scene_dae/export_dae.py", line 907, in export_mesh_node
    meshdata = self.export_mesh(node,armature)
  File "/home/xxx/.config/blender/2.73/scripts/addons/io_scene_dae/export_dae.py", line 544, in export_mesh
    materials[f.material_index]=self.export_material( mat,mesh.show_double_sided )
  File "/home/xxx/.config/blender/2.73/scripts/addons/io_scene_dae/export_dae.py", line 256, in export_material
    imgid = self.export_image(ts.texture.image)
  File "/home/xxx/.config/blender/2.73/scripts/addons/io_scene_dae/export_dae.py", line 215, in export_image
    if img_tmp_path.endswith((".bmp",".rgb",".png",".jpeg",".jpg",".jp2",".tga",".cin",".dpx",".exr",".hdr",".tif")):
UnboundLocalError: local variable 'img_tmp_path' referenced before assignment
```

As far as I can see, this variable never gets defined. And putting in img_tmp_path = image.filepath results in no error, but some images seem to be missing :)

Cheers!
Benedikt

**Comment by akien-mga** [comment] 2015-11-18 09:44
Duplicate of #1332.

**Closed by akien-mga** 2015-11-18 09:44 UTC
Labels: archived
