### ISSUE TITLE
C# - "Position.Set()" property of nodes like sprite or label (RectPosition.Set()) not work

### ISSUE THREAD

**Issue by Torguen** [godotengine/godot#33390] opened 2019-11-06 13:27 UTC
**Godot version:**
3.1.1 stable mono

**OS/device including version:**
Win10 64 Home

**Issue description:**
The position.set()/RectPosition.Set() method of nodes such as label or sprite does not work. 
Nothing just happens.
Example:

        _label.RectPosition.Set(new Vector2(0, 48));
        GetNode<Sprite>("Sprite").Position.Set(new Vector2(0, 0));

That does nothing, nothing moves.
There is no console error, nothing just happens.

**Steps to reproduce:**
Simply try to set the position of a sprite using the Set position property.

**Minimal reproduction project:**
[testSet.zip](https://github.com/godotengine/godot/files/3814582/testSet.zip)
![1](https://user-images.githubusercontent.com/19652075/68301938-4f656080-00a1-11ea-9fa8-91cb7724320c.png)

**Comment by bojidar-bg** [comment] 2019-11-06 13:32
Duplicate of #30744?

**Comment by aaronfranke** [comment] 2019-11-06 17:59
This is my fault, but it's already fixed by https://github.com/godotengine/godot/pull/30774

**Closed** 2019-11-06 18:52 UTC
Labels: archived
