### ISSUE TITLE
Silent crash when resizing inferred Packed*Array

### ISSUE THREAD

**Issue by Badaxis** [godotengine/godot#71259] opened 2023-01-12 05:19 UTC
### Godot version

v4.0.beta11.official [91713ced8]

### System information

Windows 10

### Issue description

Trying to resize an inferred Packed*Array (I didn't test them all) makes the running project crash, the window closes and no error is printed in the output or the console.
It does work if the Packed*Array is not inferred.
It does work with Array.
It worked on the 4.0.beta10

### Steps to reproduce

```gdscript
extends Node

func _ready() -> void:
	var vertex_array := PackedVector3Array() # Resize crash when inferred
	vertex_array.resize(225)

	var normal_array = PackedVector3Array() # Does not crash
	normal_array.resize(225)
```

### Minimal reproduction project

[InferredPackedArrayCrash.zip](https://github.com/godotengine/godot/files/10398389/InferredPackedArrayCrash.zip)

**Comment by akien-mga** [comment] 2023-01-12 08:05
Duplicate of https://github.com/godotengine/godot/issues/71177

**Closed by akien-mga** 2023-01-12 08:05 UTC
Labels: bug, topic:gdscript, crash
