### ISSUE TITLE
[WebGL2] Freezing in Chromium-derived browsers, caused by 2D particles

### ISSUE THREAD

**Issue by Nodragem** [godotengine/godot#16281] opened 2018-02-01 11:53 UTC
**Godot version:**
3.0 (official)

**OS/device including version:**
Tested on Windows 10 with Opera, Chrome, Firefox and Edge

**Issue description:**
- Opera and Chrome:
_The moving platforms or the main character start shaking for few seconds when pressing space (i.e. shooting action). See below:_
https://youtu.be/OwxhPNTx2gY

- Firefox:
_No issue._

- Microsoft Edge:
_The game does not start at all._

**Steps to reproduce:**
1. Export the platformer 2D demo to HTML5
2. make a local server with `python -m SimpleHTTPServer 8000`
3. go to `localhost:8000` with your brower
4. wait the game to start
5. press `space`

**Minimal reproduction project:**
You can find the platformer 2d demo in the template projects in Godot 3.0's Project List screen.

**Comment by Nobelix** [comment] 2018-02-01 12:39
Same thing for me in my personal project, when I press space, moving trees do the same thing.

**Comment by akien-mga** [comment] 2018-02-01 12:52
CC @eska014

**Comment by eska014** [comment] 2018-04-06 10:58
This seems to be fixed in Chrome Canary (nightly) 67.0.3390.0, can anyone confirm?

**Comment by henriiquecampos** [comment] 2018-04-06 12:32
@eska014 
>This seems to be fixed in Chrome Canary (nightly) 67.0.3390.0, can anyone confirm?

Not fixed at least for me :(  at Chrome 67.0.3390.0 (Official Build) canary (64-bit)

**Comment by Ruud88x** [comment] 2018-05-28 09:48
Having the same issue. Really makes the HTML5 export feature useless, unless your game uses no particles at all.

**Comment by qrilin** [comment] 2018-05-28 10:58
Same issue here, using Chrome Version 66.0.3359.181 (Official Build) (64-bit) with Godot 3.0.2 stable official

**Comment by belen-albeza** [comment] 2018-06-03 13:40
Having the same issue with Godot 3.0.2 and Chrome 66 on Mac

**Comment by AlexAlappsis** [comment] 2018-06-18 23:39
Having the same issue with Godot 3.0.3 on Chrome 67.  Confirmed working on Firefox.

**Comment by kidandcat** [comment] 2018-08-09 09:11
Same with Godot Engine v3.0.6 on Chrome 69.0.3497.23 Linux

**Comment by akien-mga** [comment] 2019-01-20 11:06
Is this still reproducible with the GLES2 / WebGL 1 renderer in the current master branch?

**Comment by AlexAlappsis** [comment] 2019-01-20 16:15
Yea, even after building from current master, which fixes the _emscripten_get_num_gamepads error, there are still many other errors when running even a blank project in GLES2 exported to HTML.

**Comment by AlexAlappsis** [comment] 2019-01-28 06:33
Tested with 3.1 beta 3.  I think things are working as expected now.  Using Particle2D with GLES3 in HTML still freezes, but GLES2 does not.  They don't display in GLES2, but my understanding is that is expected?  CPUParticle2D does work in GLES2.

**Comment by DanielAccorsi** [comment] 2019-02-14 16:35
Tested export from in 3.1 beta 4 and using "Chrome 72.0.3626.109 - 64 bits" to play, but still not working.

**Comment by justinluk** [comment] 2019-02-22 18:22
Tested an export from 3.1 beta 6 on Chrome Version 72.0.3626.109 (Official Build) (64-bit) - also still not working.

**Comment by DanielAccorsi** [comment] 2019-02-22 21:38
> Tested an export from 3.1 beta 6 on Chrome Version 72.0.3626.109 (Official Build) (64-bit) - also still not working.

Did you try on Chrome Version 72.0.3626.119  ????

**Comment by justinluk** [comment] 2019-02-23 02:08
> > Tested an export from 3.1 beta 6 on Chrome Version 72.0.3626.109 (Official Build) (64-bit) - also still not working.
> 
> Did you try on Chrome Version 72.0.3626.**119** ????

No I haven't. I decided to drop the html5 release of my game as there were other issues like delayed audio. There are too many problems with web builds for it to be production ready.

**Comment by DanielAccorsi** [comment] 2019-02-26 13:39
> > > Tested an export from 3.1 beta 6 on Chrome Version 72.0.3626.109 (Official Build) (64-bit) - also still not working.
> > 
> > 
> > Did you try on Chrome Version 72.0.3626.**119** ????
> 
> No I haven't. I decided to drop the html5 release of my game as there were other issues like delayed audio. There are too many problems with web builds for it to be production ready.

I think this solution will come on 3.2 version. :/

**Comment by DoodlesEpic** [comment] 2019-03-23 22:12
I have the same problem with Godot 3.1-stable in Linux 64bit on Google Chrome, strangely enough everything works on Firefox but with a unplayable framerate.

**Comment by sarneeh** [comment] 2019-05-03 17:05
Same problem here. Although it works fine on GLES2!

**Comment by Goncharo** [comment] 2019-06-01 12:05
Confirmed that Particles2D are still causing the described 'screen shaking' issue when using Chrome 74.0.3729.169 and GLES3 on macOS.

Note that everything seems to work correctly on Firefox 67.0.

**Comment by Faless** [comment] 2020-07-27 09:47
This seems fixed in latest `3.1` (`3.1.2`) and `3.2` (`3.2.2`), tested on both Linux and Windows 10, with Chrome 84 (Nvidia GTX 980).

Closing for now, but feel free to comment if you are still experiencing this issue (possibly providing also hardware info at this point) and I'll reopen it.

If someone could try also on a Mac it would be great.

**Closed by Faless** 2020-07-27 09:47 UTC
Labels: bug, confirmed, platform:html5, topic:rendering
