### ISSUE TITLE
GDScript2.0: Function always return default value or null in release build

### ISSUE THREAD

**Issue by Xwdit** [godotengine/godot#59484] opened 2022-03-24 19:55 UTC
### Godot version

4.0.alpha(391633760b)

### System information

Windows11, Nvidia RTX 2060, Vulkan

### Issue description

When export to a release build, functions defined in a script will always return default value if defined a return type, otherwise will always return null.

### Steps to reproduce

Define a function in a GDScript, then test its return value in a release build export.

**Comment by novaplusplus** [comment] 2022-03-24 20:23
I believe I've encountered this as well (windows and linux, my own build). Somehow I managed to make it work once, but never again.

**Comment by Calinou** [comment] 2022-03-24 20:34
@Xwdit Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

**Comment by Calinou** [comment] 2022-03-24 20:37
Duplicate of https://github.com/godotengine/godot/issues/59239. Please don't open a new issue if you've already commented on the other issue;
 it doesn't get help things get fixed faster.

**Closed by Calinou** 2022-03-24 20:37 UTC
Labels: bug, topic:gdscript, needs testing
