### ISSUE TITLE
[Godot 4 Beta 16] Theme editor suddenly closing when overriding any item

### ISSUE THREAD

**Issue by Ahopness** [godotengine/godot#72408] opened 2023-01-30 20:02 UTC
### Godot version

4.0.beta16.official

### System information

Linux Mint 21.1, Gnome DE, Wayland, Intel Integrated HD Graphics 405, Vulkan Mobile GraphicsDevice

### Issue description

When i'm editing a theme in the theme editor, each time i click the '+' button to override an item, the theme editor closes suddenly and the given error is stdout'ed in the console: 
`editor/plugins/theme_editor_plugin.cpp:2289 - Condition "edited_theme.is_null()" is true.`

https://user-images.githubusercontent.com/56614267/215582963-add5e12b-fda4-4a01-a21f-1effacdf9a49.mp4

### Steps to reproduce

- create a theme
- add a type, any type
- override an item, any item

### Minimal reproduction project

N/A

**Comment by akien-mga** [comment] 2023-01-30 20:11
Duplicate of https://github.com/godotengine/godot/issues/72271

**Closed by akien-mga** 2023-01-30 20:11 UTC
