### ISSUE TITLE
Allow saving arrays as resource

### ISSUE THREAD

**Issue by eon-s** [godotengine/godot#7573] opened 2017-01-18 16:23 UTC
**Operating system or device - Godot version:**
Tested on 2.1.1 stable

**Issue description**
Resources like shapes and curves can be saved as files in the editor (with the save icon) but built in types like Arrays, which are often used like those resources (to make polygons and things like that), can't be saved, making it complicated to copy the data in a simple way.

**Steps to reproduce:**
Create a node that uses an Array or export an Array variable on a script, create a new array if needed and go to edit the array in the inspector, the save button is disabled.

PS: the load button is enabled ~~but I'm not sure if it works because arrays can't be saved~~ and may break things because it can load anything (only tried with a mesh library resource)...

**Comment by Zylann** [comment] 2017-01-18 17:13
They would have to inherit Resource, which is a bit too much to add to a fundamental datatype (also what about Dictionaries and all the other typed arrays?).
However you can probably make a new class inheriting Resource that contains what you want (and an array on its own actually doesn't mean much).
If the problem is actually copying stuff around, then the problem is not in resource.

**Comment by eon-s** [comment] 2017-01-18 19:58
@Zylann without being a resource, maybe the inspector could give the option/exception to save the basic arrays on a file (real, and vectors are the most important ones), so it can be loaded on another scene or another project from the inspector's array editor.

Creating a custom resource makes no sense (in general) because it can't be used with current nodes.

**Comment by Zylann** [comment] 2017-01-18 20:58
It can, just script the nodes and it works^^ not out of the box for sure, but the engine cant provide everything everytime out of the box (also I never needed to save such arrays in a file to share them, even in Unity). But that's my point of view of course.

**Comment by ClikCode** [comment] 2017-01-20 11:00
Something like PackedScene, but PackedValue instead.

**Comment by Zylann** [comment] 2017-01-20 11:30
You can also have a base scene and inherit it so base values will be "shared" (or a shared child scene).

**Comment by Noshyaar** [comment] 2018-04-10 16:26
Still reproducible/relevant in 3.1 master 48890b1 : array can't be directly saved as resource

**Comment by akien-mga** [comment] 2020-07-26 22:29
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!

**Closed by akien-mga** 2020-07-26 22:29 UTC
Labels: discussion, feature proposal, topic:core, usability
