### ISSUE TITLE
Vulkan: OmniLight3D and SpotLight3D not being rendered on macOS (Intel/AMD GPUs only)

### ISSUE THREAD

**Issue by jsa4000** [godotengine/godot#45661] opened 2021-02-02 13:50 UTC
Hello,

I have an issue with Omnilights and Spotlights using the current Godot 4.0 build in MacOS. These lights are not rendering inside the editor or in-game. I don't know if it can be related to the issue I opened this morning and it seems to be solved (https://github.com/godotengine/godot/issues/45656) since I was able to open Godot.

**Godot version:**

```
Identifier:            org.godotengine.godot
Version:               4.0 (4.0)
Code Type:             X86-64 (Native)
Commit:           ae6b2d6edc76de347ccb11c4608b6e8174e1884f (HEAD -> master, origin/master, origin/HEAD)

```

**OS/device including version:**

```
Date/Time:             2021-02-02 07:52:33.631 +0100
OS Version:            Mac OS X 10.15.7 (19H2)
Report Version:        12
Bridge OS Version:     4.6 (17P6610)
GPU:                        Radeon Pro 555X 4 GB graphics


Model: MacBookPro15,1, BootROM 1037.147.4.0.0 (iBridge: 17.16.16610.0.0,0), 6 processors, 6-Core Intel Core i7, 2,2 GHz, 16 GB, SMC 
Graphics: kHW_IntelUHDGraphics630Item, Intel UHD Graphics 630, spdisplays_builtin
Graphics: kHW_AMDRadeonPro555XItem, Radeon Pro 555X, spdisplays_pcie_device, 4 GB
Memory Module: BANK 0/ChannelA-DIMM0, 8 GB, DDR4, 2400 MHz, Micron, 8ATF1G64HZ-2G6E1
Memory Module: BANK 2/ChannelB-DIMM0, 8 GB, DDR4, 2400 MHz, Micron, 8ATF1G64HZ-2G6E1
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x7BF), wl0: Feb 28 2020 15:24:56 version 9.30.357.35.32.5.47 FWID 01-9ce4adf3
Bluetooth: Version 7.0.6f7, 3 services, 25 devices, 1 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
USB Device: USB 3.1 Bus
USB Device: Apple T2 Bus
USB Device: Touch Bar Backlight
USB Device: Touch Bar Display
USB Device: Apple Internal Keyboard / Trackpad
USB Device: Headset
USB Device: Ambient Light Sensor
USB Device: FaceTime HD Camera (Built-in)
USB Device: Apple T2 Controller
Thunderbolt Bus: MacBook Pro, Apple Inc., 47.4
Thunderbolt Bus: MacBook Pro, Apple Inc., 47.4
```

**Issue description:**

Spotlights and Omnilights are not rendering properly in current version on Godot 4.0; neither running the game or in the editor. The same scenario is currently working in previous builds (last tested build on 2021/01/16 ). In this case the spotlight or omnilight illuminates the sides of the box the light is facing. 

DirectionalLights however are working properly.

**Steps to reproduce:**

1. Created new proyect
2. Create new 3D scene
3. Create CSGBox3D and a Sporlight pointing to the Box
4. Verify no light it shown. 

Thanks in advance!

**Comment by jsa4000** [comment] 2021-02-06 17:22
I have just tested the steps to reproduce the error using the same version/commit for Godot build on Windows 10 and I confirm it works perfectly. Since previous builds it works for me, it might be something related only for MacOS in some change made. The Vulkan library I use is the same I am still using from a custom build from mid January with no problems so far.

I do not get any errors or warnings in the debugger to have some hints about the problem, sorry.

**Comment by Calinou** [comment] 2021-02-06 17:44
If you can build Godot from source, can you try [bisecting the regression](https://docs.godotengine.org/en/latest/community/contributing/bisecting_regressions.html)? I'd try using `HEAD` as the "bad" commit and `HEAD~300` as the "good" commit.

**Comment by jsa4000** [comment] 2021-02-13 08:16
> If you can build Godot from source, can you try [bisecting the regression](https://docs.godotengine.org/en/latest/community/contributing/bisecting_regressions.html)? I'd try using `HEAD` as the "bad" commit and `HEAD~300` as the "good" commit.
> 
> It's possible that #45466 broke rendering on macOS, but there may be further regressions down the line.

Thanks for the info. I have done some tests checking the version from which the issue started to appear.

**[KO] -> 099dee35f4 Added GPU based cluster builder**
[OK] -> 7008e3c6ea Shader optimizations to reduce VGPR usage and increase occupancy

It seems the commit 099dee35f4, broke the lighting on MacOS.

**Comment by jsa4000** [comment] 2021-05-01 17:34
With the newer version of Godot 4.0 I cannot still see any spotlight or omnilight being renderer. Even with the new Vulkan library version. Dunno If any other MacOs user are experiencing the same issue.

**Comment by Calinou** [comment] 2021-05-01 17:44
> Hi again, with the newer version of Godot 4.0 I cannot still see any spotlight or omnilight being rendered. Even with the new Vulkan library version. Dunno If any other MacOs user are experiencing the same issue.

The Vulkan renderer isn't being actively tested on macOS these days, so it may take a while for this to be fixed.

**Comment by sairam4123** [comment] 2021-06-19 12:38
Can confirm for Windows 10 as well, OmniLight and Spotlight are not being rendered.

**Comment by tcmug** [comment] 2022-02-07 06:59
Confirmed to not work on my mac either (MacBook 2019 w/AMD Radeon Pro 5500M 4 GB), also tried on master & didn't work there either. 

@Calinou Is there anything we can do to help or is this problem in the Vulkan lib Godot is using?

**Comment by Calinou** [comment] 2022-02-07 12:13
> @Calinou Is there anything we can do to help or is this problem in the Vulkan lib Godot is using?

I don't know whether this is a problem in Godot or MoltenVK. Maybe @bruvzg would be able to take a look (he managed to fix volumetric fog on macOS recently).

**Comment by jsa4000** [comment] 2022-02-07 13:59
> > If you can build Godot from source, can you try [bisecting the regression](https://docs.godotengine.org/en/latest/community/contributing/bisecting_regressions.html)? I'd try using `HEAD` as the "bad" commit and `HEAD~300` as the "good" commit.
> > It's possible that #45466 broke rendering on macOS, but there may be further regressions down the line.
> 
> Thanks for the info @Calinou. I have done some tests checking the version from which the issue started to appear.
> 
> **[KO] -> [099dee3](https://github.com/godotengine/godot/commit/099dee35f47db3e293cb8e60287ffe6a44f3d5d4) Added GPU based cluster builder** [OK] -> [7008e3c](https://github.com/godotengine/godot/commit/7008e3c6eafa374e5d64ee7867608abe696698c2) Shader optimizations to reduce VGPR usage and increase occupancy
> 
> It seems the commit [099dee3](https://github.com/godotengine/godot/commit/099dee35f47db3e293cb8e60287ffe6a44f3d5d4), broke the lighting on MacOS.

In my previous post, I commented there was something in a Godot source that broke the lighting.

**Comment by bruvzg** [comment] 2022-02-07 14:13
> I don't know whether this is a problem in Godot or MoltenVK.

Custom build of be1adf491a6b40642cba186167e6635efca37f99 with MoltenVK from 1.2.198.1 SDK on M1 Mac, `SpotLight`s seems to be working fine, might be AMD specific issue.

**Comment by akien-mga** [comment] 2022-02-07 15:33
> MoltenVK 1.1.7 (via homebrew)

For the record, this is indeed the latest release (included in Vulkan SDK 1.3.204): https://github.com/KhronosGroup/MoltenVK/releases/tag/v1.1.7

**Comment by tcmug** [comment] 2022-02-12 14:46
Had a chance to test the latest alpha on a MacBook Pro (Retina, 15-inch, Mid 2015, Intel Iris Pro graphics) with pretty weird results:

- Omni and spotlights do not work (so not AMD related)
-  ...and not sure if this is related, but some strange flickering is present when rotating the world axis in the editor
- The same kind of flickering happens when I add directional light in the scene and adjust it

https://user-images.githubusercontent.com/567207/153715826-19c2b351-576a-49c9-999c-99109f91d059.mp4

**Comment by jsa4000** [comment] 2022-02-12 18:30
Why don't you take a look the version I am talking about where this problem started?

**Comment by tcmug** [comment] 2022-02-16 14:24
Build of "Shader optimizations to reduce VGPR usage and increase occupancy" (7008e3c6eafa374e5d64ee7867608abe696698c2) against latest MVK (1.1.7)

Iris:
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/567207/154283124-056bd7f0-7df4-4035-a485-f90513e4eccd.png">

AMD:
Works OK

Seems that AMD stops working on the next commit "Added GPU based cluster builder" (099dee35f47db3e293cb8e60287ffe6a44f3d5d4) and it brings even more problems for Iris.

So I might try to compile earlier version of MoltenVK (1.2.198.1, which was mentioned above) and link it with these commits to see if it has any effect sometime later.

**Comment by gaudecker** [comment] 2022-02-21 11:51
I can confirm this is happening on macOS Monterey with Radeon Pro 560X.

I ran my project on Linux today and the same problem manifests there as well. My desktop has GTX 1070 Ti

**Comment by Calinou** [comment] 2022-03-03 17:52
The Vulkan Mobile backend does not use clustering for rendering lights – it uses a traditional single-pass forward approach. This makes it more universal, but also a more limited in the number of lights it can support (8 OmniLights per mesh + 8 SpotLights per mesh).

**Comment by sairam4123** [comment] 2022-05-20 17:13
> The Vulkan Mobile backend does not use clustering for rendering lights – it uses a traditional single-pass forward approach. This makes it more universal, but also more limited in the number of lights it can support (8 OmniLights per mesh + 8 SpotLights per mesh).

How much lights are supported per mesh in Clustered Renderer btw?

**Comment by Calinou** [comment] 2022-05-20 19:46
> How much lights are supported per mesh in Clustered Renderer btw?

1 DirectionalLight + 8 OmniLights + 8 SpotLights per mesh, like in Godot 3.2.3 and prior's GLES3 renderer.

**Comment by codespren** [comment] 2022-11-16 20:34
Omnilights are working after installing Godot 4 beta 5.

macOS Ventura 13.0, AMD Radeon Pro 5500 M.

**Comment by snougo** [comment] 2022-11-17 06:25
it's fixed in Godot beta5
macOS 11.7.1 intel iris GPU

**Comment by clayjohn** [comment] 2022-11-17 06:29
Woohoo! That is wonderful news.

Closing as fixed (likely by https://github.com/godotengine/godot/pull/67746)

**Closed by clayjohn** 2022-11-17 06:29 UTC
Labels: bug, platform:macos, topic:rendering, confirmed, regression, topic:3d
