### ISSUE TITLE
Godot4.0 beta3 crash when new project button is pressed

### ISSUE THREAD

**Issue by astrale-sharp** [godotengine/godot#67500] opened 2022-10-16 17:08 UTC
### Godot version

4.0.beta3

### System information

```
❯ screenfetch
                          ./+o+-       astrale@humility
                  yyyyy- -yyyyyy+      OS: Ubuntu 22.04 jammy
               ://+//////-yyyyyyo      Kernel: x86_64 Linux 5.15.0-50-generic
           .++ .:/++++++/-.+sss/`      Uptime: 11h 19m
         .:++o:  /++++++++/:--:/-      Packages: 3114
        o:+o+:++.`..```.-/oo+++++/     Shell: fish 3.3.1
       .:+o:+o/.          `+sssoo+/    Resolution: 1920x1080
  .++/+:+oo+o:`             /sssooo.   DE: GNOME 41.7
 /+++//+:`oo+o               /::--:.   WM: Mutter
 \+/+o+++`o++o               ++////.   WM Theme: Adwaita
  .++.o+++oo+:`             /dddhhh.   GTK Theme: Yaru-bark-dark [GTK2/3]
       .+.o+oo:.          `oddhhhh+    Icon Theme: Yaru-bark
        \+.++o+o``-````.:ohdhhhhh+     Font: Ubuntu 11
         `:o+++ `ohhhhhhhhyo++os:      Disk: 310G / 354G (93%)
           .o:`.syhhhhhhh/.oo++o`      CPU: AMD Ryzen 7 4800H with Radeon Graphics @ 16x 2,9GHz
               /osyyyyyyo++ooo+++/     GPU: AMD RENOIR (LLVM 13.0.1, DRM 3.42, 5.15.0-50-generic)
                   ````` +oo+++o\:     RAM: 4216MiB / 15393MiB
                          `oo++.      


```

### Issue description

When launching godot, the launcher crash when pressing new project button,
it also did crash on my computer for beta1 and beta2 but this time i've got a backtrace!

```
================================================================
handle_crash: Program crashed with signal 11
Engine version: Godot Engine v4.0.beta3.official (01ae26d31befb6679ecd92cd3c73aa5a76162e95)
Dumping the backtrace. Please include this when reporting the bug on: https://github.com/godotengine/godot/issues
[1] /lib/x86_64-linux-gnu/libc.so.6(+0x42520) [0x7f5097f7d520] (??:0)
[2] /usr/lib/x86_64-linux-gnu/libvulkan_radeon.so(+0x13334e) [0x7f50850ae34e] (??:0)
[3] /usr/lib/x86_64-linux-gnu/libvulkan_radeon.so(+0x114432) [0x7f508508f432] (??:0)
[4] ./godot4.0-beta3() [0x196fe6a] (??:0)
[5] ./godot4.0-beta3() [0x19700f0] (??:0)
[6] ./godot4.0-beta3() [0x3840f32] (??:0)
[7] ./godot4.0-beta3() [0xe5983a] (??:0)
[8] ./godot4.0-beta3() [0xd928ac] (??:0)
[9] /lib/x86_64-linux-gnu/libc.so.6(+0x29d90) [0x7f5097f64d90] (??:0)
[10] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0x80) [0x7f5097f64e40] (??:0)
[11] ./godot4.0-beta3() [0xdb3e3e] (??:0)
-- END OF BACKTRACE --
================================================================

```

### Steps to reproduce

-

### Minimal reproduction project

-

**Comment by Calinou** [comment] 2022-10-16 18:29
Duplicate of https://github.com/godotengine/godot/issues/65409.

**Closed by Calinou** 2022-10-16 18:29 UTC
