### ISSUE TITLE
Next pass in StandardMaterial3D is not working

### ISSUE THREAD

**Issue by esakylli** [godotengine/godot#76537] opened 2023-04-28 09:25 UTC
### Godot version

4.0.3.rc1.mono

### System information

Windows 11, Vulkan, Nvidia GeForce RTX 3070 Ti Laptop

### Issue description

I have trouble using "Next pass" in the StandardMaterial3D:
I have set it to a material with a shader that just outputs a color to ALBEDO, but the color is not rendered. Only the albedo color from the StandardMaterial3D.

### Steps to reproduce

Create an empty project.
Create a ShaderMaterial and a shader that outputs some color to ALBEDO.
Create a StandardMaterial3D and set some different albedo color, then set the ShaderMaterial in the "Next pass".
Create a MeshInstance3D and a PlaneMesh, and set "Surface Material Override" to the StandardMaterial3D.
The color from the shader is not rendered.

### Minimal reproduction project

[SecondTestGodot4.zip](https://github.com/godotengine/godot/files/11352067/SecondTestGodot4.zip)

**Comment by esakylli** [comment] 2023-04-28 13:58
Tested a little more:
It seems to work if I create new materials (and shader) that I apply to the MeshInstance.
But only in the editor. And if I run the sample or restart the project, it shows wrong again.

**Comment by Calinou** [comment] 2023-04-28 20:34
This is because the second pass is drawn at the same coordinates, which will cause only one of the two passes to be visible.

If you enable **Grow** and change its **Amount** on the original material, notice how the planes become separated:

![image](https://user-images.githubusercontent.com/180032/235249125-a1a260f0-52e8-41e8-a3d3-6625884f35e0.png)

This also occurs on the running project:

![image](https://user-images.githubusercontent.com/180032/235249156-b40b613c-7de5-4bc1-b854-aa8280dc852f.png)

Closing, as this is not a bug but a configuration issue.

**Closed by Calinou** 2023-04-28 20:34 UTC

**Comment by clayjohn** [comment] 2023-04-28 20:48
Also note for future readers, using rendering_priority will change the order in which the passes are rendered
