### ISSUE TITLE
[3.0] Compiling using MSVC fails 2 times

### ISSUE THREAD

**Issue by Ahmed0425** [godotengine/godot#8357] opened 2017-04-11 12:29 UTC
**Operating system or device - Godot version:**
windows 10 - Visual studio 2015 update 3 - Godot engine 3.0 alpha

**Issue description:**

x86 x64 Cross tools command prompt were used
compiling through MSVC is very fast but it fails 2 timed and succeeds in the third time (succeeds in the first time using MinGW)

**Steps to reproduce:**
Some commits that caused the Travis CI build to fail made Compiling through MSVC fails as well (at least in the first and second time
I'm sure that one of them was https://github.com/godotengine/godot/commit/1c480698ce0e881cbd28f1f0ddba95cee74ca834

**Link to minimal example project:**

**Comment by Zylann** [comment] 2017-04-11 12:40
Would this be caused by files generated too late? (explaining why a few reruns makes it work)

**Comment by bojidar-bg** [comment] 2017-04-11 13:47
Sounds related to #5042

**Comment by RayKoopa** [comment] 2017-04-11 13:58
Yes, -j**x** is causing this issue.

**Comment by Zylann** [comment] 2017-04-11 17:46
Can't these warning be fixed instead of silenced?

**Comment by RayKoopa** [comment] 2017-04-11 17:48
You want to make all inline functions non-inline?

**Comment by Zylann** [comment] 2017-04-11 17:59
The warning says "'function' : unreferenced inline function has been removed", which means it's unused. If it's unused, how about removing it?

**Comment by RayKoopa** [comment] 2017-04-11 18:06
Because it complains about ~15000 inline functions, and yes, they're surely not "unused". I don't even know why it complains. I uploaded a build log which freezes VS [here](http://ray.syroot.com/godot/freezing_log.zip) (`scons p=windows -j8`). That are 158 MB of raw text!
[C4820](https://msdn.microsoft.com/en-us/library/t7khkyth.aspx) is another useless warning, nobody cares about padding in data structures.

**Comment by Zylann** [comment] 2017-04-11 18:26
Looks like these come from macros like GDCLASS or VARIANT_ENUM_CAST, which define hidden functions that nobody uses? (and then you would get the warning for all Godot classes). I get that some might not be used because using these macros is "all-or-nothing"...

However:
`d:\projects\git\godot\core\hashfuncs.h(68): warning C4514: 'hash_djb2_one_32': unreferenced inline function has been removed`
Do we really don't use this hashing function? Oo I've seen it used in a few places, did it change now?

Other random functions lkike `GradientTexture::get_color_at_offset` are found as unused... so there is both "legit-unused" and "forgotten" stuff.

**Comment by RayKoopa** [comment] 2017-04-11 18:28
I guess so, but because of the things the compiler just can't understand, the warning is more useless than helpful (and when used in VS, harmful).

**Comment by Zylann** [comment] 2017-04-11 18:31
They would be useful if we could find a way to separate those we know as "not understandable" and the others. No idea how easy it would be though...

**Comment by bojidar-bg** [comment] 2017-06-27 18:50
Is this still valid?

**Comment by vnen** [comment] 2017-06-27 22:01
This is originally a duplicate of #5042. About the warnings freezing the IDE, it would be better to open a new issue if it's still a problem.

**Closed by vnen** 2017-06-27 22:01 UTC
Labels: bug, platform:windows, topic:buildsystem
