### ISSUE TITLE
Area2D priority property is not doing anything

### ISSUE THREAD

**Issue by kockahonza** [godotengine/godot#34131] opened 2019-12-06 00:15 UTC
**Godot version:** 3.1.1 stable

**OS/device including version:** Arch linux (up to date)

**Issue description:** The title says it all, I'm pretty sure now that the priority property of Area2D Nodes has no effect.

**Steps to reproduce:** Create 2 Area2D nodes which overlap, set different priorities. Then when an object enters both of them at the same time the one with the bigger priority should emit it's signals before the other (I really hope I understand the property correctly). But as the sample project shows the signals are emitted in a seemingly random order. 

**Minimal reproduction project:**
[PriorityTest.zip](https://github.com/godotengine/godot/files/3929711/PriorityTest.zip)
There are two Area2Ds which "share a border", both of them have a "signal connected to function" and there is an object to the right of those. The object can be moved with the arrow keys.

**Comment by avencherus** [comment] 2019-12-06 08:57
Same.  It looks like something that was never implemented.

I believe the current behavior is more like each Area2Ds intersection is tested in order it appears in the tree.  It would have to gather all intersection results and then sort by priority and fire the signals.

**Comment by kockahonza** [comment] 2019-12-06 16:08
> Same. It looks like something that was never implemented.
> 
> I believe the current behavior is more like each Area2Ds intersection is tested in order it appears in the tree. It would have to gather all intersection results and then sort by priority and fire the signals.

At first I thought the same but after trying it out with the test project the results really seem random despite the order not being changed (assuming the order in the tree is the same as is the order of the nodes in the GUI).

**Comment by kockahonza** [comment] 2019-12-06 22:15
Hi again, trying to be helpful I looked into the code to see where it would possibly be implemented. I think that the relevant functions would be both in the file `servers/physics_2d/space_2d_sw.cp`. Either `call_queries` to sort before calling each of the Area2Ds method. Or what would probably be better would be in the function `area_add_to_monitor_query_list` which is called when a new Area2D is added and adds a poiter to the Area2D to a SelfList. However currently I don't think there is a way to sort a SelfList or to add an element in such a way that it is always sorted.

**Comment by madmiraal** [comment] 2020-09-30 09:30
Closing, because this is not a bug. An `Area`'s priority does not apply to its signals. An `Area`'s priority setting applies to its `Space Override`.

Enabled `Space Override`s with higher priorities are applied first. Priorities are important, because if the `Area`'s `SpaceOverride` mode is `Combine-Replace` or `Replace`, `Area`s with a lower priority -- including the physics defaults -- are not applied.

Signals are emitted in the order they are detected by the physics engine. It is not dependent on the order they appear in the tree, and, as @avencherus indicates, there is no attempt to record all the signals, sort them according to a priority, and then emit them. Most of the time a `CollisionObject` will only enter or leave a single `Area`. However, as described in the OP, if the `Area`s share a border or, perhaps more relevantly, if a `CollisionObject` inside multiple `Area`s is removed (or added), the order of the signals emitted is undetermined.

If you think this this would be a useful feature, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template.

**Closed by madmiraal** 2020-09-30 09:30 UTC
Labels: bug, topic:core, topic:physics
