### ISSUE TITLE
Warnings when compiling on Linux with LTO

### ISSUE THREAD

**Issue by Swarkin** [godotengine/godot#97531] opened 2024-09-27 10:20 UTC
### Tested versions

Built from master [506d6e427a4eecfc1e5e5ee1180019a876119701]

### System information

Operating System: Debian GNU/Linux 12 KDE Plasma Version: 5.27.5 KDE Frameworks Version: 5.103.0 Qt Version: 5.15.8 Kernel Version: 6.1.0-25-amd64 (64-bit) Graphics Platform: X11 Processors: 6 × Intel® Core™ i5-9600K CPU @ 3.70GHz Memory: 9.4 GiB of RAM Graphics Processor: SVGA3D; build: RELEASE; LLVM; Manufacturer: VMware, Inc. Product Name: VMware Virtual Platform System Version: None

### Issue description

Compiling Godot on Linux produces warnings:
```cpp
Linking Program bin/godot.linuxbsd.template_release.x86_64 ...
thirdparty/freetype/src/autofit/afglobal.c: In function 'af_face_globals_new':
thirdparty/freetype/src/autofit/afglobal.c:344:5: warning: 'memset' writing 696 bytes into a region of size 0 overflows the destination [-Wstringop-overflow=]
  344 |     FT_ZERO( &globals->metrics );
      |     ^
thirdparty/clipper2/src/clipper.engine.cpp: In function 'AddPaths_':
thirdparty/clipper2/src/clipper.engine.cpp:625:53: warning: argument 1 value '18446744073709551615' exceeds maximum object size 9223372036854775807 [-Walloc-size-larger-than=]
  625 |     Vertex* vertices = new Vertex[total_vertex_count], * v = vertices;
      |                                                     ^
/usr/include/c++/12/new:128: note: in a call to allocation function 'operator new []' declared here
  128 | _GLIBCXX_NODISCARD void* operator new[](std::size_t) _GLIBCXX_THROW (std::bad_alloc)
      |
scene/resources/animation.cpp: In member function 'commit_temp_packets':
scene/resources/animation.cpp:4522:48: warning: writing 1 byte into a region of size 0 [-Wstringop-overflow=]
 4522 |                         header[header_bytes++] = 0;
      |                                                ^
scene/resources/animation.cpp:4500:25: note: at offset [9, 14] into destination object 'header' of size 8
 4500 |                 uint8_t header[8];
      |                         ^
scene/resources/animation.cpp:4522:48: warning: writing 1 byte into a region of size 0 [-Wstringop-overflow=]
 4522 |                         header[header_bytes++] = 0;
      |                                                ^
scene/resources/animation.cpp:4500:25: note: at offset 15 into destination object 'header' of size 8
 4500 |                 uint8_t header[8];
      |                         ^
scons: done building targets.
[Time elapsed: 00:07:56.49]
```

### Steps to reproduce

1. `git clone https://github.com/godotengine/godot --depth 1`
2. `cd godot`
3. Download `custom.py.txt` file below
4. Rename it to `custom.py` and move into the `godot` directory
5. `scons p=linux target=template_release`

### Minimal reproduction project (MRP)

[custom.py.txt](https://github.com/user-attachments/files/17162670/custom.py.txt)

**Comment by akien-mga** [comment] 2024-09-27 10:27
Duplicate of #88504, consolidating there. I'll add the `animation` warnings which seem newly introduced.

**Closed by akien-mga** 2024-09-27 10:27 UTC
Labels: bug, topic:buildsystem

**Comment by akien-mga** [comment] 2024-09-27 11:23
Actually I can't reproduce the `animation` warning with GCC 14.

It's a false positive from GCC: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=104789
We already worked it around in #58755, which seems to still work ok for me, but maybe not for GCC 12 which might have had more issues with this case.

**Comment by akien-mga** [comment] 2024-09-27 13:06
I'm not sure if there's an easy way to upgrade GCC on Debian, there would be on Ubuntu but I wouldn't advise mixing packages. Debian prides itself in stability and this usually means relatively old libraries and toolchains, which aren't always great for software development.

But you can ignore these warnings, they're not impacting anything. And getting a newer GCC would only remove the `animation` one but not the ones generated in thirdparty code, which can't be disabled due to another GCC bug: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=80922
