### ISSUE TITLE
Child node is duplicated incorrectly when instancing and adding a scene(which inherit another scene) to the scene tree through editor plugin

### ISSUE THREAD

**Issue by univeous** [godotengine/godot#54545] opened 2021-11-03 10:47 UTC
### Godot version

3.3.4.stable

### System information

Windows 11 21H2

### Issue description

I know the title is a little unclear and awkward, but I will try to explain.
Let's say there is a scene A:
![image](https://user-images.githubusercontent.com/40604180/140044260-42a73be5-083d-4d51-b5b3-bf007763d997.png)
and scene B inherits A and has its own children:
![image](https://user-images.githubusercontent.com/40604180/140044430-881962d3-90fb-48bf-bed9-fa63f757b2a3.png)
If we instance and add a B scene to scene tree through editor plugin:
``` gdscript
tool
extends EditorPlugin
…
	var node = load("res://Node2D_inherit.tscn").instance()
	#assume one node is selected.
	get_editor_interface().get_selection().get_selected_nodes()[0].add_child(node)
	node.set_owner(get_editor_interface().get_edited_scene_root())
…
```
If I right-click the newly added node and check "Editable Children", then save the scene and open it again, strange things will happen:
![image](https://user-images.githubusercontent.com/40604180/140045155-6240e595-8214-42a6-84fb-83ddd0c8c5e0.png)
Some children of scene B are duplicated. 
This seems only to happen with a scene that inherits another scene. If change the code to make it instance and add scene A, everything seems fine.

### Steps to reproduce

Open the Minimal reproduction project, select the root node, click the "Add Scene" button in the canvas editor menu:
![image](https://user-images.githubusercontent.com/40604180/140046151-919dce80-bc20-4227-ad19-2879bd8078c5.png)
Right-click the newly added node and check "Editable Children", then save the scene, close it and open it again.

### Minimal reproduction project

[EditableChildren.zip](https://github.com/godotengine/godot/files/7466944/EditableChildren.zip)

**Comment by kleonc** [comment] 2021-11-03 14:20
Duplicate of #49660, it's fixed since `3.4.beta5` (https://github.com/godotengine/godot/commit/389e67aa987869c67af7f2bab88c11191d3661c3).

**Closed** 2021-11-03 14:35 UTC
