### ISSUE TITLE
Code editor improvement: auto-format code

### ISSUE THREAD

**Issue by smedelyan** [godotengine/godot#27609] opened 2019-04-02 16:49 UTC
AFAIK, there's no such an ability in Godot code editor so I already do not get surprised if I forgot to type a space before `=` or typed it twice. Just an example

**Comment by Calinou** [comment] 2019-04-02 17:42
Duplicate of https://github.com/godotengine/godot/issues/7392.

**Closed by Calinou** 2019-04-02 17:42 UTC

**Comment by smedelyan** [comment] 2019-04-02 18:11
thanks, somehow overlooked this one
