### ISSUE TITLE
[godot 3.0] ImageTexture embedded into scene file

### ISSUE THREAD

**Issue by supagu** [godotengine/godot#8086] opened 2017-03-20 07:20 UTC
I have exposed in my C++ plugin a Ref<ImageTexture> and allowed this to be set in the editor for my heightmap terrain. 

Now when i set this heightmap in my scene and save it, it saves the texture it references INTO the scene, causing my scene to be around 40MB, and once closed is now no longer openable!

changing to Ref<Texture> works fine, so really the question is, should an ImageTexture be allowed to be embedded in the tscn?

**Comment by bojidar-bg** [comment] 2017-03-20 10:27
@supagu Are you sure it is an ImageTexture and not an Image? If it is an Image, then this is probably a dupe of #4240.
Also, can you give a small bit of example code which triggers the problem/bug?

**Comment by supagu** [comment] 2017-03-20 11:11
Yes, in the zip attached is the code, and a scene I setup with an ImageTexture.

1) I dropped my BTerrain node in the scene
2) clicked on my heightmap property
3) and select "New ImageTexture"
4) click the > to go into it ImageTexture
5) select the "Image" combo and select "Load"
6) select the texture I want to reference
7) save the scene

Now that image is embedded within the scene!

[bterrain_image_texture.zip](https://github.com/godotengine/godot/files/854558/bterrain_image_texture.zip)

**Comment by bojidar-bg** [comment] 2017-03-20 11:15
No, this is still an `Image`, not an `ImageTexture` that you are "Load"-ing. Can you try to load the .png/.jpg directly as the ImageTexture (without going through steps 3 and 4)?

**Comment by supagu** [comment] 2017-03-20 11:23
the combobox gives me the option to select:
1) New ImageTexture
2) Load

If I select "Load" it brings up a file picker, which has the following formats recognised:
DDS, PKM, PVR, RES, TEX, TRES, All Files

I tried selecting "All Files" and selecting my png but it didn't work.

**Comment by Zylann** [comment] 2017-03-20 13:25
ImageTexture extends Texture, so if you hit "New ImageTexture" in the inspector, then it will indeed embed it in the scene, as any other resource type. You should instead be able to Load directly instead of having to "New" it.

**Comment by supagu** [comment] 2017-03-23 01:19
okay, so this is not really a bug then? I'm happy to close it as I was just raising it as it seemed odd to embed an image into a scene.

**Comment by bojidar-bg** [comment] 2017-03-23 10:04
Closing in favour of #4240, since the other was first.

**Closed by bojidar-bg** 2017-03-23 10:04 UTC
Labels: bug, discussion, topic:core
