### ISSUE TITLE
GridMap accidental error

### ISSUE THREAD

**Issue by 2821869675** [godotengine/godot#37902] opened 2020-04-15 11:13 UTC
**Godot version:**
3.2.1.srable
**Issue description:**
Adding a cell after deleting a large number of cells reports an error
**Steps to reproduce:**
So let's create some blocks:
`	for x in range(32):
		for y in range(32):
			map.set_cell_item(x,0,y,0)`
And then delete them:
`	for x in range(32):
		for y in range(32):
			map.set_cell_item(x,0,y,-1)`
And then add:
`	for x in range(32):
		for y in range(32):
			map.set_cell_item(x,0,y,0)`
The console will have an error at this point

**Minimal reproduction project:**
[demo_Error.zip](https://github.com/godotengine/godot/files/4480819/demo_Error.zip)

**Comment by qarmin** [comment] 2020-04-15 11:32
Duplicate of #33648

**Closed by qarmin** 2020-04-15 11:32 UTC
Labels: archived
