### ISSUE TITLE
Unnecessary argument passed to method called by Thread.start

### ISSUE THREAD

**Issue by drtwisted** [godotengine/godot#18235] opened 2018-04-16 14:44 UTC
**Godot version:** 3.X

**OS/device including version:** Linux (Probably macOS & Windows as well)

**Issue description:**

When starting a thread using my_thread.start(self, "_run_thread") construction without userdata argument provided **_run_thread** is still called with argument which is equal to null, I assume it's because of the defualt value declared in Thread.start definition.

**Steps to reproduce:**
Run the following code:
```
func _run_thread():
    print("I am a thread")

func _ready():
   var thread = Thread.new()
   thread.start(self, "_run_thread")
```
**Expected result:**
_run_thread gets called and we see the output of "I am a thread"

**Actual result:**
Thread is not run because of an error:
```
ERROR: _start_func: Could not call function '_run_thread'' starting thread ID: 5 Reason: Too Many Arguments
   At: core/bind/core_bind.cpp:2286.
```

**Comment by vnen** [comment] 2018-04-17 03:47
Duplicate of #9924

**Closed by vnen** 2018-04-17 03:47 UTC
