### ISSUE TITLE
BakedLightmap crashes when baking in a large scene with hundreds of 3D objects

### ISSUE THREAD

**Issue by sanyi12** [godotengine/godot#62222] opened 2022-06-19 15:15 UTC
### Godot version

3.4.4 stable

### System information

Windows 10 GLES3 Nvidia version 512.95

### Issue description

Baking lightmaps crashes Godot. 
The scene has 4 omnilights and hundreds of 3d objects from a single GLTF file. BakedLightmap node is default except the quality which was set to low to speed up the baking time.

### Steps to reproduce

This is what the console says before crashing:

```
Godot Engine v3.4.4.stable.official.419e713a2 - https://godotengine.org
OpenGL ES 3.0 Renderer: NVIDIA GeForce RTX 3070 Laptop GPU/PCIe/SSE2
OpenGL ES Batching: ON

ERROR: FATAL: Index p_index = 5 is out of bounds (count = 4).
   at: operator[] (./core/local_vector.h:162)
ERROR:ERROR: FATAL: Index p_index = 5 is out of bounds (count = 4).
 FATAL: Index p_index = 5 is out of bounds (count = 4).
   at: ERROR:   at: operator[] (./core/local_vector.h:162)
 FATAL: Index p_index = 5 is out of bounds (count = 4).
operator[] (./core/local_vector.h:162)
   at: operator[] (./core/local_vector.h:162)
```

### Minimal reproduction project

Sadly the project has more than  4GBs.

**Comment by Calinou** [comment] 2022-06-19 16:09
> 3.3.4 stable

[Godot 3.3.x is not supported for bug fixes anymore](https://docs.godotengine.org/en/stable/about/release_policy.html#release-support-timeline), so please upgrade to [3.4.4](https://godotengine.org/article/maintenance-release-godot-3-4-4) and check if the issue still occurs there.

Also, I'd try [3.5.rc3](https://godotengine.org/article/release-candidate-godot-3-5-rc-3) as it supports [multiple images in atlases](https://github.com/godotengine/godot/pull/58102) when baking lightmaps.

**Comment by Calinou** [comment] 2022-06-21 19:06
> I also tested this in G4 and crashes. I do need to test it more as I am not sure on the testing method.

On Godot 4, this is likely the same cause as https://github.com/godotengine/godot/issues/45296.

**Comment by Calinou** [comment] 2023-04-30 23:41
- Duplicate of https://github.com/godotengine/godot/issues/45296 (same cause).

**Closed by Calinou** 2023-04-30 23:41 UTC
Labels: bug, topic:rendering, needs testing, crash, topic:3d
