### ISSUE TITLE
offset doesn't work on child node instance (3D)

### ISSUE THREAD

**Issue by DevMagicLord** [godotengine/godot#22056] opened 2018-09-13 22:41 UTC
Godot 3 alpha 1

Script on parent Spatial node to scale a child node works, but code to offset or set_translation on the child node doesn't work.

 
This is the code :

            nodeOrigin.add_child(playerModelNode) 

            #works            
            playerModelNode.set_scale(scaling)
            
            # doesn't work
            playerModelNode.global_transform.origin = playerModelNode.global_transform.origin+ offset

**Comment by DevMagicLord** [comment] 2018-09-14 21:02
The work around until that works, is to scale and offset the parent node instead.

`    nodeOrigin.global_transform.origin = nodeOrigin.global_transform.origin+ offset`

or 
`
nodeOrigin.set_translation(offset) `

**Comment by groud** [comment] 2018-09-28 14:02
What do you mean "it does not work" ? Please be a little bit more precise.

**Comment by KoBeWi** [comment] 2020-06-19 13:41
I can't reproduce it in 3.2.2, also OP never bothered to reply to the question, so closing.

**Closed by KoBeWi** 2020-06-19 13:41 UTC
Labels: bug, topic:core
