### ISSUE TITLE
Computer locks up when editing text in a popup dialogue (affects Project Manager and Editor)

### ISSUE THREAD

**Issue by voxelv** [godotengine/godot#49809] opened 2021-06-21 18:21 UTC
### Godot version

0a6a71973e50e31fef7b91658ab713ae5db5033f

### System information

Arch Linux (5.12.9-arch1-1), GTX970, using i3wm which is a Tiling Window Manager

### Issue description

When editing text (in places like "Project Name" in the "Project Manager -> New Project" popup, or the search box in the "Search Help" popup while in the "Script" viewer), the mouse freezes, and the computer appears to lock up for about 10-15 seconds, and Godot and its popup become unresponsive.

### Steps to reproduce

1. Open Project Manager.
2. Click "New Project".
3. Click and Drag in the "Project Name" field to select text.

**Comment by Zireael07** [comment] 2021-06-21 18:27
Is your video card NVIDIA? There's a similar issue open which is related to NVIDIA drivers...

**Comment by voxelv** [comment] 2021-06-21 18:46
> Is your video card NVIDIA? There's a similar issue open which is related to NVIDIA drivers...

Yes, GTX 970.

**Comment by Calinou** [comment] 2021-06-21 20:08
Duplicate of https://github.com/godotengine/godot/issues/41614.

**Closed by Calinou** 2021-06-21 20:08 UTC
