### ISSUE TITLE
Godot 4.2 crash on exit with GDScript addon / editor plugin

### ISSUE THREAD

**Issue by mhilbrunner** [godotengine/godot#84327] opened 2023-11-01 20:50 UTC
### Godot version

4.2.dev (up to and including beta4)

### System information

Linux and Windows

### Issue description

Closing the editor with the attached MVP project open crashes Godot 4.2 on both Windows or Linux. Same for trying to export the project from CLI. Seems something in the `W4GD` addon results in the engine crashing on exit.

This happens at least down to 4.2.dev3, if not earlier. 4.1.2 and earlier work fine.

### Steps to reproduce

Open the attached MVP project in Godot 4.2. Make sure the included editor plugin is enabled in project settings. Close the editor. You should experience a Godot crash along the lines of:
```
/usr/bin/bash: line 190:  4301 Segmentation fault      (core dumped)
```

The crash log looks like this on Windows, with other threads mostly idling/sleeping/waiting best I can tell:
```
Unhandled exception at 0x00007FF982C522C7 (ntdll.dll) in godot4.2-master.exe_231028_235202.dmp: 0xC0000005: Access violation reading location 0x000000870A600000.
 	ntdll.dll!__chkstk()	Unknown
 	ntdll.dll!RtlDispatchException()	Unknown
 	ntdll.dll!KiUserExceptionDispatch()	Unknown
>	godot4.2-master.exe!Node::is_accessible_from_caller_thread() Line 552	C++
 	godot4.2-master.exe!Node::propagate_notification(int p_notification) Line 2236	C++
 	godot4.2-master.exe!SceneTree::_notification(int p_notification) Line 697	C++
 	godot4.2-master.exe!SceneTree::_notificationv(int p_notification, bool p_reversed) Line 84	C++
 	godot4.2-master.exe!Object::notification(int p_notification, bool p_reversed) Line 839	C++
 	godot4.2-master.exe!CrashHandlerException(_EXCEPTION_POINTERS * ep) Line 141	C++
 	godot4.2-master.exe!main$filt$0() Line 219	C++
 	godot4.2-master.exe!__C_specific_handler(_EXCEPTION_RECORD * ExceptionRecord, void * EstablisherFrame, _CONTEXT * ContextRecord, _DISPATCHER_CONTEXT * DispatcherContext) Line 389	C++
 	ntdll.dll!RtlpExecuteHandlerForException()	Unknown
 	ntdll.dll!RtlDispatchException()	Unknown
 	ntdll.dll!KiUserExceptionDispatch()	Unknown
 	godot4.2-master.exe!Node::is_accessible_from_caller_thread() Line 552	C++
 	godot4.2-master.exe!Node::propagate_notification(int p_notification) Line 2236	C++
 	godot4.2-master.exe!SceneTree::_notification(int p_notification) Line 697	C++
 	godot4.2-master.exe!SceneTree::_notificationv(int p_notification, bool p_reversed) Line 84	C++
 	godot4.2-master.exe!Object::notification(int p_notification, bool p_reversed) Line 839	C++
 	godot4.2-master.exe!CrashHandlerException(_EXCEPTION_POINTERS * ep) Line 141	C++
 	godot4.2-master.exe!main$filt$0() Line 219	C++
 	godot4.2-master.exe!__C_specific_handler(_EXCEPTION_RECORD * ExceptionRecord, void * EstablisherFrame, _CONTEXT * ContextRecord, _DISPATCHER_CONTEXT * DispatcherContext) Line 389	C++
 	ntdll.dll!RtlpExecuteHandlerForException()	Unknown
 	ntdll.dll!RtlDispatchException()	Unknown
 	ntdll.dll!KiUserExceptionDispatch()	Unknown
 	...
 	The maximum number of stack frames supported by Visual Studio has been exceeded.
```

### Minimal reproduction project

[godot4.2-crashtest.zip](https://github.com/godotengine/godot/files/13231905/godot4.2-crashtest.zip)

**Note:** The MVP is provided by W4 Games solely for the purpose of debugging and fixing this issue. The included `W4GD` addon/plugin is for now proprietary, with all rights reserved, and intended to be published soon.

**Comment by YuriSizov** [comment] 2023-11-01 21:41
Confirmed a duplicate of https://github.com/godotengine/godot/issues/84000, fixed by https://github.com/godotengine/godot/pull/84302.

**Closed by YuriSizov** 2023-11-01 21:41 UTC
Labels: bug, topic:core, topic:gdscript, crash, regression
