### ISSUE TITLE
Export resource lost and cannot set when change csproj file

### ISSUE THREAD

**Issue by L2750558108** [godotengine/godot#79605] opened 2023-07-18 10:03 UTC
### Godot version

4.1.1 mono

### System information

windows10 x64

### Issue description

I try to use this to give C# project a global constant
\<DefineConstants\>isDebug\</DefineConstants\>
and get lots of error output when running
I check all scene and find the export resource are lost, and cannot be set in editor

### Steps to reproduce

N/A

### Minimal reproduction project

just a normal C# project

**Comment by raulsntos** [comment] 2023-07-19 08:51
Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/4c1f11944ebfe1204f21c6ac488c7a2294e1d520/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

Also, there's already a `DEBUG` constant when C# projects are build with the Debug configuration, and Godot adds custom constants (these Godot specific constants are documented in the [_C# features_](https://docs.godotengine.org/en/stable/tutorials/scripting/c_sharp/c_sharp_features.html#full-list-of-defines) page).

You are replacing all those constants with `<DefineConstants>isDebug</DefineConstants>`, if you meant to add to the existing constants you should be using `<DefineConstants>$(DefineConstants);isDebug</DefineConstants>` instead.

**Comment by raulsntos** [comment] 2023-07-24 09:58
It seems we are using `#if TOOLS` in the generated code. Since you are replacing the constants defined by Godot.NET.Sdk (and thus removing the `TOOLS` constant) the code inside the `#if TOOLS` is not included in the compilation.

**Comment by raulsntos** [comment] 2024-07-25 17:18
Closing since this is working as expected. See the comments above for the explanation.

**Closed by raulsntos** 2024-07-25 17:18 UTC
Labels: discussion, topic:dotnet
