### ISSUE TITLE
Adding TileSetAtlasSource from gdscript breaks TileSet instance.

### ISSUE THREAD

**Issue by SpiceyWolf** [godotengine/godot#65758] opened 2022-09-13 20:03 UTC
### Godot version

4.0.dev (alpha 15)

### System information

Windows 10, Vulkan

### Issue description

In gdscript, when accessing a tileset instance and attempting to add a source such as the example (from TileMap named map):

map.tile_set.add_source(TileSetAtlasSource.new())

the first time seems to do nothing, and when invoking that same command a second time, the host object becomes null (viewable from debugging in the editor)

This is the case whether you directly apply this to a tileset instance made separately (var tileset = TileSet.new()) which makes the tileset object become null, or from a TileMap (making the TileMap object become null)

Additionally, it seems trying to modify any of the sources that are already present breaks the source. I have tried swapping a texture on a source with one that is the same size, with the only difference of the tiles changed color, and the test display environment goes from working and displaying stuff to nothing is displaying.

### Steps to reproduce

Create a new Node2D scene

Add a script to the scene

add this code:
```
extends Node2D

func _ready():
    var tileset := TileSet.new()
    tileset.add_source(TileSetAtlasSource.new())
    print("do a break-line here, and view tileset in inspector") # it still has a reference
    tileset.add_source(TileSetAtlasSource.new())
    print("do a break-line here, and view tileset in inspector") # it prevents [null]
```

run it from editor

Update: I was playing with an alternate means of getting the effect I needed (which lead to me encountering the issue above), and I encountered a similar issue when trying to make any arrays of ImageTexture (Because I loaded them manually from external source at runtime), 

Update 2: The image texture array worked if I shrink the textures I was loading down to really small sizes... if I make any of them just slightly larger than they were, it will explode on just the first one being added. (256x1024)

**Comment by estebanfer** [comment] 2022-10-11 02:53
I had a similar issue, but I think the problem is only visible on the debugger, I had some issues today when I created a new object like an `Image`, it showed correctly in the debugger, but after calling a method like `img.load(path)`, it showed as null, but the object still existed, using print shows it correctly. Same happened with others like using `AtlasTexture.new()` and then using `atlas.set_atlas(texture)`.
It was on godot 4.0 beta 2.

**Comment by groud** [comment] 2023-06-21 09:31
I am going to close this issue for now, I was not able to replicate the bug back then, and it seems we didn't have anyone reporting the same issue.

If anyone is able to reproduce this issue, please mention it here or open a new issue with a minimal reproduction project.

**Closed by groud** 2023-06-21 09:31 UTC
Labels: bug, topic:core, topic:2d
