### ISSUE TITLE
Description of gdscript exported variables not showing in inspector when using `export_category`

### ISSUE THREAD

**Issue by ElPincheTopo** [godotengine/godot#89500] opened 2024-03-15 01:58 UTC
### Tested versions

- Reproducible in v4.2.1.stable.official [b09f793f5]

### System information

Windows 11 Pro

### Issue description

You can usually use comments starting with `##` to write decriptions for exported variables, and they show up in the tooltip in the inspector. E. g. 
![godot bug 2](https://github.com/godotengine/godot/assets/1082821/516efcd8-250e-40bd-83a1-9335df320f3b)

This does not work when the exported variable belongs to an export category e. g.
![godot bug](https://github.com/godotengine/godot/assets/1082821/ab0928c3-79ce-4499-b075-b2f910c5173a)

The issue seems to go away if there is at least one exported variable that does not belong to an export category e. g. 
![godot bug 3](https://github.com/godotengine/godot/assets/1082821/b2fbef6d-987d-43fe-9e68-b7084c970202)

### Steps to reproduce

You can reproduce the issue by just adding an export category to any exported variable in a gdscript file.

The issue seems to go away if there is at least one exported variable that  is not part of a group.

### Minimal reproduction project (MRP)

N/A

**Comment by dalexeev** [comment] 2024-03-15 06:23
* Duplicate of https://github.com/godotengine/godot/issues/64432#issuecomment-1941676792.
* Fixed by #88318 for future 4.3.
* Cherry-picked for future 4.2.2.

Thanks for reporting the bug nonetheless!

**Closed by dalexeev** 2024-03-15 06:23 UTC
