### ISSUE TITLE
Add to Favorites doesn't work in Godot 3.5 beta 4

### ISSUE THREAD

**Issue by amap1380** [godotengine/godot#60341] opened 2022-04-18 10:54 UTC
### Godot version

Godot Engine v3.5.beta4.official

### System information

Ubuntu 20.04 LTS

### Issue description

Add to Favorites does not work in 3.5 beta 4.
It's a regression.(It works in 3.4.4)

### Steps to reproduce

Create a project.
Select a file in file system dock.
Right click and select (Add to Favorites)

**Comment by amap1380** [comment] 2022-04-18 10:57
Draging files into Favorites folder doesn't work either.

**Comment by akien-mga** [comment] 2022-04-27 11:05
Duplicate of #59933, this will be fixed in the next beta.

**Closed by akien-mga** 2022-04-27 11:05 UTC
Labels: bug, topic:editor, regression
