### ISSUE TITLE
Trackpad scrolling in animation window inverted (macOS)

### ISSUE THREAD

**Issue by ariromano** [godotengine/godot#25730] opened 2019-02-09 06:58 UTC
**Godot version:**
3.06

**OS/device including version:**
macOS 10.14.2, MagicTrackpad 2

**Issue description:**
Scrolling in the animation window at the bottom is inverted. When two-finger dragging up, content moves down and when two-finger dragging down, content moves up. In the inspector, it works correctly.

**Steps to reproduce:**
• make sure that, in system preferences → trackpad → scroll & zoom, "Scroll direction: Natural" is enabled.
• open the "player scene" from the tutorial mentioned below.
• on the trackpad, two-finger drag up and down with the cursor inside the animation window
→ you'll see that the content moves opposite of the finger movement
• for comparison, make an inspector with enough content small enough to scroll and do the same in the inspector
→ you'll see that the scrolling is correct as expected.
• left/right are also inverted in the animation window only.

Side notes:
• when disabling "scroll direction: natural", everything is flipped. In the inspector, scrolling is inverted (as expected), but in the animation window, scrolling suddenly works as if set to "natural".
• with the mouse wheel, it works as expected in both settings (natural/inverted) and also both windows (animation and inspector).

proposed fix: invert trackpad scrolling in the animation window in all cases (as it's currently wrong, no matter the user preference).

**Minimal reproduction project:**
the Godot first person tutorial project (https://docs.godotengine.org/en/3.0/tutorials/3d/fps_tutorial/part_two.html) has a scene "Player" that contains enough animations to be scrolled when the window is too small.

**Comment by ArdaE** [comment] 2020-08-09 03:17
Hi @ariromano, is this still a problem? I'm on Godot 3.2.2, and the scroll direction looks normal and consistent with all the other panes/windows/other apps. Maybe this got fixed since 3.0.6?

**Comment by Calinou** [comment] 2020-08-09 13:57
Closing as resolved per @ArdaE's comment. Please comment if you can still reproduce it.

**Closed by Calinou** 2020-08-09 13:57 UTC
Labels: topic:editor, usability
