### ISSUE TITLE
TextureRegion dock is not working properly [GLES2]

### ISSUE THREAD

**Issue by williamd1k0** [godotengine/godot#20579] opened 2018-07-29 19:21 UTC
**Godot version:**

Godot 3.1 (c7dc066dc180149652006e86f07765e5326f324b)

**OS/device including version:**

Windows 10 x64; Intel HD Graphics 400

**Issue description:**

The texture is not being properly positioned inside the TextureRegion dock.

GLES2:
![texture-region-gles2](https://user-images.githubusercontent.com/10428035/43369821-d5f1b7b8-934a-11e8-9e5d-bc3e999a1524.gif)

GLES3(working correctly):
![texture-region-gles3](https://user-images.githubusercontent.com/10428035/43369827-fe3333e6-934a-11e8-9671-d644a355ac88.gif)

**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by volzhs** [comment] 2018-07-29 19:40
duplicate of #20519

**Closed by volzhs** 2018-07-29 19:40 UTC

**Comment by williamd1k0** [comment] 2018-07-29 19:53
Oh, sorry, I tried to find a related issue but I did not find anything :dizzy_face:
