### ISSUE TITLE
Inherited Scenes don't receive Base name changes, losing local resources

### ISSUE THREAD

**Issue by markdibarry** [godotengine/godot#56701] opened 2022-01-11 19:19 UTC
### Godot version

4.0 dev (b52490e)

### System information

Windows 10

### Issue description

When renaming a `Node` in a scene that is inherited by others, the inherited scenes do not receive the changes and keeps reference to the old name internally. Viewing the scene in the editor, the new name is honored, but all local resources are not found, since they are referenced under the old name in the `.tscn` file. Saving in-editor permanently removes old local resources from the `.tscn` file.

https://user-images.githubusercontent.com/21325943/149007252-bdfe7bf0-c35e-42a8-8980-158cc68ebcd5.mp4

### Steps to reproduce

Create new project.
Create scene with nodes that can contain local resources.
Create an inherited scene from that scene.
Add local resources to nodes in the inherited scene.
Rename the nodes in the base scene.

### Minimal reproduction project

[RenameBug.zip](https://github.com/godotengine/godot/files/7849435/RenameBug.zip)

_No response_

**Comment by markdibarry** [comment] 2022-01-11 23:06
Just tested in 3.x and the bug exists there as well. Changing a Node's name in a base scene unintentionally disconnects all resources from inherited scenes.

**Comment by Calinou** [comment] 2022-01-11 23:08
Duplicate of https://github.com/godotengine/godot/issues/56704 (same cause).

**Closed by Calinou** 2022-01-11 23:08 UTC
Labels: bug, topic:editor
