### ISSUE TITLE
GDScript: spurious error with class_name and is keyword

### ISSUE THREAD

**Issue by seadra** [godotengine/godot#38265] opened 2020-04-27 15:36 UTC
**Godot version:**
3.2

**OS/device including version:**
Debian

**Issue description:**
I have a base class (Base in base.gd), with a name specified using the `class_name` keyword.

If I use `something is Base` in base.gd anywhere, this causes all other scripts using `Base` fail. Strangely, `something as Base` seem to work fine.

**Steps to reproduce:**
See the example below.

**Minimal reproduction project:**
Reproducible in a project with only the following two files:

base.gd
```gdscript
extends Node

class_name Base


func _ready():
	var x := Node.new()
	if x is Base:
		pass
```

user.gd
```gdscript
extends Node
class_name User

var b : Base

func _ready():
	pass
```

When editing user.gd, the editor shows an error at the bottom:

> The class "Base" couldn't be fully loaded (script error or cyclic dependency)

**Comment by Calinou** [comment] 2020-04-27 15:39
Try restarting the editor, that might fix it.

**Comment by seadra** [comment] 2020-04-27 15:56
I tried restarting the editor, it had no effect.

**Comment by mhilbrunner** [comment] 2020-04-28 13:15
Closing as duplicate of https://github.com/godotengine/godot/issues/38265, referencing it there.

**Closed by mhilbrunner** 2020-04-28 13:15 UTC
