### ISSUE TITLE
[2.1.3] Massive meshes when I switch OSes

### ISSUE THREAD

**Issue by xyroclast** [godotengine/godot#8398] opened 2017-04-13 20:23 UTC
Linux Mint 18 -> Windows 10 , Godot 2.1.3

Shortly after 2.1.3 dropped, I decided to try out my game on my Windows partition (I develop on the Linux side, generally)
I updated to 2.1.3, and cloned my repo.
Upon loading my game in the editor, and running it, something very bizarre happened. Several of the meshes, mainly mountains and hills, were now about 100 times larger than they should be. I'm talking like, hill-sized changing to Mount Everest size, escaping my extremely liberal draw distance.
Many of the other meshes and the main groundplane were completely unaffected.
When I switched back to the Linux side and gave it another run, everything was back to normal.
I cannot say whether or not this was present in 2.1.2 as well, as I didn't try it before the update.
My dev partner runs it on Windows 7 and the issue did not occur, so it's possible it might be specific to Windows 10.
Anyone experience anything similar?
Cheers!

**Comment by vnen** [comment] 2017-04-14 19:45
A sample project for testing would be great.

**Comment by xyroclast** [comment] 2017-04-14 21:19
I'll see if I can isolate the effect in a test environment (Don't want to publicly post the project it's occurring in)

**Comment by kubecz3k** [comment] 2018-04-10 16:09
First of all thank you for your report and sorry for the delay.

We released Godot 3.0 in January 2018 after 18 months of work, fixing many old issues either directly, or by obsoleting/replacing the features they were referring to.

We still have hundreds of issues whose relevance/reproducibility needs to be checked against the [current stable version](https://godotengine.org/download), and that's where you can help us.
**Could you check if the issue that you described initially is still relevant/reproducible in Godot 3.0 or any newer version, and comment about its current status here?**

For bug reports, please also make sure that the issue contains detailed steps to reproduce the bug and, if possible, a zipped project that can be used to reproduce it right away. This greatly speeds up debugging and bugfixing tasks for our contributors.

Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

Thanks in advance.

*Note: This message is being copy-pasted to many "stale" issues (90+ days without activity). It might happen that it is not meaningful for this specific issue or appears oblivious of the issue's context, if so please comment to notify the Bugsquad about it.*

**Comment by akien-mga** [comment] 2019-04-15 14:21
> Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

As there was no update since the previous post, we close this issue.

If it is still relevant in the way it was described and discussed above, please comment to ask for it to be reevaluated. If it is only partly relevant, or if the original issue has changed, it would be better to open a new issue (potentially referring to this one) focused on the current state.

**Closed by akien-mga** 2019-04-15 14:21 UTC
Labels: bug, needs testing, topic:core
