### ISSUE TITLE
The name of the property in EditorPlugin does not show up

### ISSUE THREAD

**Issue by nongvantinh** [godotengine/godot#81838] opened 2023-09-18 00:30 UTC
### Godot version

4.1 stable

### System information

Windows 10

### Issue description

Add a new property to the Editor Inspector, but the name does not appear in the Inspector

### Steps to reproduce

just call `add_property_editor` when developing Inspector plugin

### Minimal reproduction project

[editor_property_hidden.zip](https://github.com/godotengine/godot/files/12644048/editor_property_hidden.zip)

https://github.com/godotengine/godot/assets/53887662/9052b86c-fa4b-4c3d-8b94-8986056805a1

**Comment by timothyqiu** [comment] 2023-09-18 03:00
This is not a bug.

`_parse_begin` is for adding things before any properties. `_parse_property` should be used instead.

The first parameter of `add_property_editor` is for telling the custom editor widget which property it's editing, not for telling inspector which property this widget should be used for. The latter is done via the return value of `_parse_property`.

See https://docs.godotengine.org/en/stable/tutorials/plugins/editor/inspector_plugins.html

**Comment by nongvantinh** [comment] 2023-09-18 03:41
I'm not sure I understand the usage of it. What I want to do is add a new property to a **specific resource** so that I can set up some configuration for the resource related to the one that was selected and save it to a JSON. That's why I put it in the `_parse_begin` method.

https://github.com/godotengine/godot/assets/53887662/8c2a013a-04ec-4daa-aed2-c02d31f8cee8

**Comment by timothyqiu** [comment] 2023-09-18 03:56
AFAIK, you can't add new properties to an object via inspector plugin. It's only for accessing existing ones.

If you just want to store arbitrary data on any object, you can used metadata instead.

**Comment by Calinou** [comment] 2023-09-18 16:56
Closing per the above comment.

**Closed by Calinou** 2023-09-18 16:56 UTC
Labels: bug, topic:editor, topic:plugin
