### ISSUE TITLE
Editor doesnt update Description Properly

### ISSUE THREAD

**Issue by IXLLEGACYIXL** [godotengine/godot#66265] opened 2022-09-22 16:08 UTC
### Godot version

4.0 mono

### System information

Windows 11

### Issue description

When i set the Description for a Node in Godot it doesnt Update even after saving 

Building the Project doesnt help in anyway

Closing Godot and reopen fixes the Issue, then descriptions get Updated

### Steps to reproduce

1. create a scene and type "My fancy Description"
2. save and close godot ( hover will show now My Fancy Description )
3. Add asdfgggggghz in the Description and save
4. Description is still "My fancy Description"
5. Restart Godot, now its Update

=> expected Behaviour is that on Change/Save the Description Updates and that not an Entire Restart is required

### Minimal reproduction project

1. Basic Project
2. one Node

**Comment by Calinou** [comment] 2022-09-22 16:13
Duplicate of https://github.com/godotengine/godot/issues/61521.

**Closed by Calinou** 2022-09-22 16:13 UTC
