### ISSUE TITLE
Editor freezes and can use all OS memory after clicking on a Skeleton node with high number of bones

### ISSUE THREAD

**Issue by marcinn** [godotengine/godot#63068] opened 2022-07-16 11:53 UTC
### Godot version

v3.5.rc.custom_build.a9920ae54

### System information

Manjaro Linux, 5.10.124-1-MANJARO, x86_64, NVIDIA GM107GLM [Quadro M620 Mobile] nvidia 515.48.07, X11

### Issue description

Godot hangs while clicking on the Skeleton node of imported gLTF rigged object.
After waiting a while it consumes all available memory, and OS becomes unresponsive.

Console output contains only one message repeated many times:
`Object was deleted while awaiting a callback`

![image](https://user-images.githubusercontent.com/139032/179353695-ad69ac40-7f7f-46a0-ae9e-4c2ba21a9a87.png)

The gLTF is a file exported from Blender.

### Steps to reproduce

1. Open the project and Cat.tscn
2. Click on the Skeleton node

### Minimal reproduction project

[SkeletonTest.zip](https://github.com/godotengine/godot/files/9125669/SkeletonTest.zip)

**Comment by marcinn** [comment] 2022-07-16 12:01
The model contains 760 bones. Is this too much for Godot, maybe?

**Comment by marcinn** [comment] 2022-07-16 15:07
OK, I slightly reduced number of bones to about 600. Now Editor is not crashing. It just hangs until all UI controls for bones will be initialized/rendered. I noticed that filtering properties of Skeleton node is also slow. And clicking other node and coming back to Skeleton node gives same result - a long time to render UI in the inspector pane.

So it's not a bug of a infinite loop. I will reduce amount of bones as low as possible. But I would strongly suggest adding a hard limit of supported bones (maybe configurable in editor settings) and display an error message to the user when the limit is reached, maybe with a hint like "Try to reduce bones count in your model or increase bones limit in editor settings".

**Comment by Calinou** [comment] 2022-07-16 16:10
Duplicate of https://github.com/godotengine/godot/issues/35653 (fixed in 4.0.alpha).

**Closed by Calinou** 2022-07-16 16:10 UTC
Labels: bug, topic:3d
