### ISSUE TITLE
lightmap_size_hint is 0 after generating physics object for mesh

### ISSUE THREAD

**Issue by JulianHeuser** [godotengine/godot#69274] opened 2022-11-28 00:40 UTC
### Godot version

v4.0.beta6.official [7f8ecffa5]

### System information

Linux Mint 21 Cinnamon

### Issue description

Using the new import window for models, you can choose to generate physics for a mesh. However, checking this sets the mesh's lightmap size hint to 0, effectively disabling baked lighting on it entirely. If this is unchecked and the model is reimported, the size hint will be set automatically like normal.

### Steps to reproduce

1) Import a .blend
2) Double click it to open the advanced import settings
3) Make sure static lightmaps are enabled (VoxelGI/SDFGI/LightmapGI). Select a mesh (red).
4) Enable physics on the mesh. (generate/physics)
![image](https://user-images.githubusercontent.com/25406449/204167753-c9dfb58f-0107-4533-b97c-f37288544bc2.png)
5) Reimport and place the mesh in a scene. Lightmaps won't build, and checking the scene shows that the "lightmap size hint" is zero:
![image](https://user-images.githubusercontent.com/25406449/204167790-801c3c96-91bb-4c43-bdc5-d5dd361a1d5b.png)

### Minimal reproduction project

[bug report.zip](https://github.com/godotengine/godot/files/10099551/bug.report.zip)

**Comment by clayjohn** [comment] 2023-01-26 19:17
Duplicate of https://github.com/godotengine/godot/issues/69274

**Closed by clayjohn** 2023-01-26 19:17 UTC
Labels: bug, topic:physics, topic:import, topic:3d
