### ISSUE TITLE
Builtin control nodes don't respond to touch if mouse event emulation is disabled

### ISSUE THREAD

**Issue by maiself** [godotengine/godot#71651] opened 2023-01-18 23:14 UTC
### Godot version

d93b66ad4d6b1dae42cc318c16224d03bd1a1472

### System information

arch linux, asus zenbook duo ux481 (dual touchscreen laptop)
goggle pixel 6

### Issue description

Builtin control nodes don't respond to touch if `emulate_mouse_from_touch` is disabled in the project settings. This makes them unusable if the project needs this disabled.

### Steps to reproduce

Place a button or text edit control into a scene. Attach a pressed event to the button and print to see if event is received.
Disable `emulate_mouse_from_touch`.
Attempt to interact with the controls on a touch capable device.

### Minimal reproduction project

none

**Comment by akien-mga** [comment] 2023-01-19 08:13
Duplicate of #24589

**Closed by akien-mga** 2023-01-19 08:13 UTC
