### ISSUE TITLE
AnimatedSprite2D loses SpriteFrames data on 3-to-4 conversion

### ISSUE THREAD

**Issue by naturally-intelligent** [godotengine/godot#73696] opened 2023-02-21 18:02 UTC
### Godot version

4.0.rc3

### System information

Ubuntu 20.04 LTS (probably not relevant)

### Issue description

When converting a project from v3 to v4, AnimatedSprite to AnimatedSprite2D loses data in SpriteFrames.

### Steps to reproduce

Open attached project with v4 and convert full project.

SpriteFrame data inside AnimatedSprite2D is now empty, ideally it should be preserved/converted.

Project was made with v3.4.5

### Minimal reproduction project

[AS2D34.zip](https://github.com/godotengine/godot/files/10796262/AS2D34.zip)

**Comment by Calinou** [comment] 2023-02-21 18:38
Duplicate of https://github.com/godotengine/godot/issues/50691.

**Closed by Calinou** 2023-02-21 18:38 UTC
Labels: enhancement, archived, topic:core, topic:import
