### ISSUE TITLE
Strange overlapping drawing bug in the "About" Window

### ISSUE THREAD

**Issue by EricEzaM** [godotengine/godot#53205] opened 2021-09-29 07:37 UTC
### Godot version

v4.0.dev.custom_build [f410852f9]

### System information

Win 10

### Issue description

Not sure if this also affects other things... Looks like this could be a bug with Tree? Not sure.

Look at the top of the window as I scroll in the video below.

https://user-images.githubusercontent.com/41730826/135223830-47fdc71d-1052-4cde-9a86-9b9af8967fb6.mp4

### Steps to reproduce

N/A

**Comment by akien-mga** [comment] 2021-09-29 07:38
Duplicate of #36164.

**Closed by akien-mga** 2021-09-29 07:38 UTC
