### ISSUE TITLE
Blank initial windows on macOS Majove when building against SDK 10.14

### ISSUE THREAD

**Issue by k7771911** [godotengine/godot#22689] opened 2018-10-03 18:12 UTC
**Godot version:**

v3.1.alpha.custom_build.344a453

**OS/device including version:**

macOS Mojave

**Issue description:**

The project selection screen and the initial editor windows show up blank, resizing the window even a tiny bit fixes the drawing.

**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by swarnimarun** [comment] 2018-10-03 19:10
Screenshots please....
A gif will be even better for devs who would try to work on the problem.

**Comment by bruvzg** [comment] 2018-10-03 19:55
I can confirm this on Mojave 10.14 (18A391).

Binaries built with Xcode 10.0 (10A255) and 10.14 SDK show up blank (solid white or grey depending on system theme), and display actual window content only after resizing, same binary works fine on High Sierra 10.13.6 (17G2208) and Mavericks 10.9.5 (13F1911).

Binaries built with Xcode 10.0 (10A255) and 10.13 SDK (extracted from Xcode 9.4.1 for 10.13 and set by adding `-isysroot` to `CPPFLAGS` and `LINKFLAGS`) works fine on all three macOS versions.

<details>
  <summary>Screenshot</summary>

![screenshot 2018-10-03 at 22 38 06](https://user-images.githubusercontent.com/7645683/46435564-4a780400-c75f-11e8-921c-f06ebb4a5df2.png)

</details>

**Comment by bruvzg** [comment] 2018-10-03 20:15
This can be fixed by adding NSOpenGLContext update to `swap_buffers`, but probably it's not necessary to call it on each frame, and it should be added somewhere in the window init process.

```diff
diff --git a/platform/osx/os_osx.mm b/platform/osx/os_osx.mm
index 886ff4b332..831b27f27b 100644
--- a/platform/osx/os_osx.mm
+++ b/platform/osx/os_osx.mm
@@ -1915,7 +1915,7 @@ String OS_OSX::get_locale() const {
 }
 
 void OS_OSX::swap_buffers() {
-
+	[context update];
 	[context flushBuffer];
 }
 
```

**Comment by akien-mga** [comment] 2018-10-05 06:29
This seems to be a general SDK change indeed that also affects SDL and GLFW: https://twitter.com/FlohOfWoe/status/1047926416745160705

`[context update]` is the correct fix, but it should likely only be done once after window creation, not in `swap_buffers`.

**Closed** 2018-10-24 13:37 UTC
Labels: bug, platform:osx, topic:rendering
