### ISSUE TITLE
Godot 4 Web Export crashes

### ISSUE THREAD

**Issue by mageowl** [godotengine/godot#72841] opened 2023-02-07 15:22 UTC
### Godot version

4.0.beta16

### System information

MacOS 13 (Ventura), Chrome 109

### Issue description

I tried to upload my game to itch.io as an HTML file. Whenever I start the game, my browser crashes. I have tried it with multiple projects, and got the same result. Chrome freezes, and then I have to force quit it.

### Steps to reproduce

1. Create and export a game to HTML
2. Upload to itch.io
3. Turn on SharedArrayBuffer
4. Run project
5. Browser crashes.

### Minimal reproduction project

Any project will do.

**Comment by lpares12** [comment] 2023-02-08 16:29
Having issues too. My project is set to "Mobile" and there are so many errors related to shdaer_gles3.cpp on the developer's console in Chrome. Same project works fine on other OSs.

This is the output in the console:

<img width="555" alt="mac1" src="https://user-images.githubusercontent.com/9217676/217590849-5823e014-2f81-4cf8-9012-ef61b5af0419.png">

<img width="555" alt="mac2" src="https://user-images.githubusercontent.com/9217676/217590938-7da9e732-e646-4916-a0ff-0d0313e59368.png">

<img width="555" alt="mac3" src="https://user-images.githubusercontent.com/9217676/217590955-54f9d688-8d81-4a9b-a734-92fe820900c8.png">

Also note that in one of the 4 macOS laptops I tried, it did work but took 3-4 minutes to load.

**Comment by mageowl** [comment] 2023-02-14 23:49
I think that is a different issue. Not just the game, but the _entire browser_ freezes (some sort of an infinite loop maybe?

**Comment by clayjohn** [comment] 2023-02-14 23:53
As far as the OP, it is likely related to https://github.com/godotengine/godot/issues/70691 which is an issue with how ANGLE compiles shaders

lpares12's issue sounds like it may be the same as https://github.com/godotengine/godot/issues/65696

**Comment by Calinou** [comment] 2023-02-15 18:56
Duplicate of https://github.com/godotengine/godot/issues/70691 (same cause).

**Closed by Calinou** 2023-02-15 18:56 UTC
Labels: bug, platform:web, topic:porting

**Comment by mageowl** [comment] 2023-02-16 01:05
Thank you!
