### ISSUE TITLE
Orientation issue on iOS 11

### ISSUE THREAD

**Issue by alexzheng** [godotengine/godot#11628] opened 2017-09-27 10:46 UTC
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
godot 2.1
iOS 11.0.1
![img_3047](https://user-images.githubusercontent.com/1130047/30909519-011ea5d6-a3b4-11e7-92a3-acc729b45924.PNG)
![img_3048](https://user-images.githubusercontent.com/1130047/30909521-0172fdd4-a3b4-11e7-8f98-eb4c979b0708.PNG)
![img_3049](https://user-images.githubusercontent.com/1130047/30909520-0172af5a-a3b4-11e7-919b-a1e8dcfb32af.PNG)

**Issue description:**

When rotate the device, the content can not displayed correctly.
It's OK for device before iOS 11.

**Steps to reproduce:**

**Link to minimal example project:**

**Comment by alexzheng** [comment] 2017-10-01 11:42
this issue is not exactly the same issue as #11547

**Comment by alexzheng** [comment] 2017-10-03 13:54
if only landscapeleft and right are enabled,the content will not rotate to the device orientation,all these issues won’t happen before iOS 11

**Comment by alexzheng** [comment] 2017-10-07 08:19
![img_3189](https://user-images.githubusercontent.com/1130047/31306081-ff43ac7e-ab7a-11e7-82e0-ebbdb84c7c71.PNG)
What may cause the image like this?
On device before iOS 11 it can rotate correctly.

**Comment by KoBeWi** [comment] 2020-06-13 14:13
Closing, because the author doesn't seem to respond anymore and no one else commented/reacted.

The issue can be reopened if someone can still reproduce it in 3.2.1 or newer.

**Closed by KoBeWi** 2020-06-13 14:13 UTC
Labels: bug, platform:ios, topic:rendering
