### ISSUE TITLE
typing in `bone_name` field goes backwards in SkeletonModification3DLookAt

### ISSUE THREAD

**Issue by vfig** [godotengine/godot#62876] opened 2022-07-10 08:43 UTC
### Godot version

v4.0.alpha11.official [afdae67cc]

### System information

Windows 10

### Issue description

When you try to type a bone name into the `bone_name` field in the inspector for SkeletonModification3DLookAt, with every keystroke the insertion point is reset to the start of the field, so that whatever you type comes out reversed.

![bug](https://user-images.githubusercontent.com/81129/178137758-c2ff1151-10b1-409d-8205-4f2cbff2f734.gif)

### Steps to reproduce

1. Import a skinned mesh with a skeleton as a scene.
2. Edit the scene (or an inherited scene).
3. Add a modification stack to the skeleton, and add a SkeletonModification3DLookAt to the stack.
4. Click in the `bone_name` field and try typing a bone name.

**Comment by vfig** [comment] 2022-07-10 08:43
Workaround: copy paste the bone name into the field instead.

**Comment by KoBeWi** [comment] 2022-07-10 10:47
Probably caused by inspector refreshing more than necessary.

**Comment by lyuma** [comment] 2023-01-14 17:52
I am closing this since we removed modifications for 3D. I believe SkeletonModification2D works differently and does not have this issue.

If you are able to reproduce it on SkeletonIK3D or Modification2D or any other nodes, feel free to reopen it.

**Closed by lyuma** 2023-01-14 17:52 UTC
Labels: bug, topic:editor, topic:3d
