### ISSUE TITLE
Tree's button's tooltip error when set column title is visible

### ISSUE THREAD

**Issue by CsloudX** [godotengine/godot#86497] opened 2023-12-25 02:33 UTC
### Tested versions

v4.2.1.stable.mono.official [b09f793f5]

### System information

Godot v4.2.1.stable.mono - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1060 5GB (NVIDIA; 31.0.15.3623) - AMD Ryzen 9 3900X 12-Core Processor (24 Threads)

### Issue description
Tree's button's tooltip error when set column tiltle visible
![GIF](https://github.com/godotengine/godot/assets/35988767/423601e8-a1c1-4141-9348-a7f44006b5b9)

### Steps to reproduce

.

### Minimal reproduction project (MRP)

[TreeTest.zip](https://github.com/godotengine/godot/files/13763503/TreeTest.zip)

**Comment by Illauriel** [comment] 2024-01-03 06:09
Looks like the same bug broke AnimationLibraryEditor's button tooltips too.


https://github.com/godotengine/godot/assets/10573379/bc487691-1228-4e54-95ff-fafbee7467f7

It seems like a pretty big problem, because half the editor is different tree views.

I've pinpointed this bug to somewhere between 4.1 and 4.2, because it's present as early as 4.2-rc1
It definitely has to do with rect calculations in Tree::get_tooltip(), and I blame this commit 8278a5f, because if I replace that part of code with code from 4.1 branch, AnimationLibraryEditor tooltips work correctly.

**Comment by akien-mga** [comment] 2024-01-03 08:38
Possibly regression from #79792 as per above comment, CC @Miguel0312 @KoBeWi @YuriSizov.

**Comment by KoBeWi** [comment] 2024-01-04 17:11
I confirmed that regression comes from the mentioned PR (or at least reverting it fixes the bug), but couldn't figure out why does it happen. Something is wrong with item rects.

**Comment by CsloudX** [comment] 2024-01-25 02:18
![GIF](https://github.com/godotengine/godot/assets/35988767/f233b17e-14af-4199-8410-3f106ca34817)
It like the text was error too when enabled treeitem editable.

**Comment by CsloudX** [comment] 2024-01-25 02:44
![GIF](https://github.com/godotengine/godot/assets/35988767/de58003e-a35c-4101-8ec6-eb1f434067dc)
It like the text was error too when enabled treeitem editable.

**Comment by akien-mga** [comment] 2024-04-18 10:35
Fixed by #90842.

**Closed by akien-mga** 2024-04-18 10:35 UTC
Labels: bug, needs testing, regression, topic:gui
