### ISSUE TITLE
Can't play any 3D scene on Android

### ISSUE THREAD

**Issue by guilhermefelipecgs** [godotengine/godot#11693] opened 2017-09-29 12:56 UTC
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
LG G3 (d855), Master branch (2c5fa0947d724c0dcb24643f692f7a9d686a5490), GPU: Qualcomm, Adreno (TM) 330, OpenGL ES 3.0

**Issue description:**
I can't play any 3D scene on android, only 2D.
Godot get stucks in the logo, without logs.

**Steps to reproduce:**
Just deploy any 3D scene on android.

**Comment by Zireael07** [comment] 2017-09-29 13:08
What OpenGL version does your device support?

**Comment by guilhermefelipecgs** [comment] 2017-09-29 13:43
GLES: Qualcomm, Adreno (TM) 330, OpenGL ES 3.0

**Comment by guilhermefelipecgs** [comment] 2017-09-29 13:58
Aparently it's a bug with my gpu model.

I tested now with other gpu model and works.
GLES: Qualcomm, Adreno (TM) 405, OpenGL ES 3.1 V@140.0 (GIT@I7d704ff208) **(this works)**

**Comment by khairul169** [comment] 2017-09-29 14:20
This is also occured with Snapdragon 650, Adreno 510.. 2D scenes works fine, don't know why.. Logcat prints nothing..

**Comment by groud** [comment] 2017-09-29 14:44
Master branch I guess ?

**Comment by guilhermefelipecgs** [comment] 2017-09-29 16:06
Yes

Em 29 de set de 2017 12:45, "Gilles Roudiere" <notifications@github.com>
escreveu:

Master branch I guess ?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/godotengine/godot/issues/11693#issuecomment-333146222>,
or mute the thread

**Comment by Calinou** [comment] 2017-09-29 19:16
3D works on Android with a Samsung Galaxy S7 edge running Android 7.0 for me (tested on commit https://github.com/godotengine/godot/commit/2c5fa0947d724c0dcb24643f692f7a9d686a5490).

![godot_3d_platformer_android](https://user-images.githubusercontent.com/180032/31032175-54d98bb6-a55b-11e7-93e6-9d5da21ebb37.png)

**Comment by guilhermefelipecgs** [comment] 2017-09-29 19:35
Tested with this model and not workls too:
GLES: Qualcomm, Adreno (TM) 505, OpenGL ES 3.2 V@145.0 (GIT@Id9e7eae3da)

**Comment by Alexia-AT-Digitecnology** [comment] 2017-10-19 22:51
I tested the Kinematic Character 3D demo and closes on my cellphone (it's a Xiaomi Redmi 3s Pro).

GPU: Adreno 505 (OpenGLES 3)
CPU: ARMv7 VFPv3 NEON | Cores x8 @1.4 Ghz
RAM: 3 gb
Android Version: 6.0.1

Here is the logcat log:

10-19 19:08:29.094 17646 17679 F libc    : Fatal signal 11 (SIGSEGV), code 1, fault addr 0x48 in tid 17679 (GLThread 530)
10-19 19:08:29.160   638   638 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
10-19 19:08:29.162   638   638 F DEBUG   : Build fingerprint: 'Xiaomi/land/land:6.0.1/MMB29M/V8.5.4.0.MALMIED:user/release-keys'
10-19 19:08:29.162   638   638 F DEBUG   : Revision: '0'
10-19 19:08:29.162   638   638 F DEBUG   : ABI: 'arm'
10-19 19:08:29.162   638   638 F DEBUG   : pid: 17646, tid: 17679, name: GLThread 530  >>> org.godotengine.kinematiccharacter3d <<<
10-19 19:08:29.163   638   638 F DEBUG   : signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x48
10-19 19:08:29.214   638   638 F DEBUG   :     r0 00000000  r1 00003a00  r2 80000000  r3 00000002
10-19 19:08:29.214   638   638 F DEBUG   :     r4 00000010  r5 ef8793e8  r6 00000000  r7 00000001
10-19 19:08:29.214   638   638 F DEBUG   :     r8 00000001  r9 ac6ccc40  sl 00000000  fp 00000040
10-19 19:08:29.214   638   638 F DEBUG   :     ip abbdb220  sp ef8793e0  lr 00000003  pc e947b554  cpsr 80070030
10-19 19:08:29.367   638   638 F DEBUG   : 
10-19 19:08:29.367   638   638 F DEBUG   : backtrace:
10-19 19:08:29.368   638   638 F DEBUG   :     #00 pc 00150554  /system/vendor/lib/egl/libESXGLESv2_adreno.so (_ZN9EsxGfxMem15UpdateTimestampEPK10EsxContext13EsxAccessTypeP20EsxBucketIdReference+307)
10-19 19:08:29.368   638   638 F DEBUG   :     #01 pc 00140ab7  /system/vendor/lib/egl/libESXGLESv2_adreno.so (_ZN9EsxCmdMgr16GfxMemReferencedEP9EsxGfxMem13EsxAccessType+22)
10-19 19:08:29.368   638   638 F DEBUG   :     #02 pc 001c30ab  /system/vendor/lib/egl/libESXGLESv2_adreno.so (_ZNK10A5xProgram25GenerateShaderCBSlotStateEP10A5xContext13EsxCmdBufType23EsxCompiledHwShaderTypejP20A5xShaderCBSlotState+778)
10-19 19:08:29.368   638   638 F DEBUG   :     #03 pc 001c156f  /system/vendor/lib/egl/libESXGLESv2_adreno.so (_ZN11A5xPipeline13WriteUboStateEP10A5xContext13EsxCmdBufType23EsxCompiledHwShaderTypejP14A5xStateBuffer+110)
10-19 19:08:29.368   638   638 F DEBUG   :     #04 pc 001cff3d  /system/vendor/lib/egl/libESXGLESv2_adreno.so (_ZN10A5xContext29WriteConstantBufferStateGroupE13EsxCmdBufTypej+28)
10-19 19:08:29.368   638   638 F DEBUG   :     #05 pc 001dfb25  /system/vendor/lib/egl/libESXGLESv2_adreno.so (_ZN10A5xContext13ValidateStateEPK17EsxDrawDescriptor+1636)
10-19 19:08:29.368   638   638 F DEBUG   :     #06 pc 001e0065  /system/vendor/lib/egl/libESXGLESv2_adreno.so (_ZN10A5xContext18HwValidateGfxStateEPK17EsxDrawDescriptor+4)
10-19 19:08:29.368   638   638 F DEBUG   :     #07 pc 000cd10d  /system/vendor/lib/egl/libESXGLESv2_adreno.so (_ZN10EsxContext16ValidateGfxStateEPK17EsxDrawDescriptor+556)
10-19 19:08:29.368   638   638 F DEBUG   :     #08 pc 000c2153  /system/vendor/lib/egl/libESXGLESv2_adreno.so (_ZN10EsxContext21DrawElementsInstancedE11EsxPrimTypej10EsxPixTypePKvji+338)
10-19 19:08:29.368   638   638 F DEBUG   :     #09 pc 000b3005  /system/vendor/lib/egl/libESXGLESv2_adreno.so (_ZN10EsxContext23GlDrawElementsInstancedEjijPKvi+68)
10-19 19:08:29.368   638   638 F DEBUG   :     #10 pc 000a5b49  /system/vendor/lib/egl/libESXGLESv2_adreno.so (glDrawElementsInstanced+40)
10-19 19:08:29.368   638   638 F DEBUG   :     #11 pc 004180c8  /data/app/org.godotengine.kinematiccharacter3d-2/lib/arm/libgodot_android.so (_ZN20RasterizerSceneGLES316_render_geometryEPNS_10RenderList7ElementE+872)
10-19 19:08:29.368   638   638 F DEBUG   :     #12 pc 00414edc  /data/app/org.godotengine.kinematiccharacter3d-2/lib/arm/libgodot_android.so (_ZN20RasterizerSceneGLES312_render_listEPPNS_10RenderList7ElementEiRK9TransformRK12CameraMatrixjbbbbb+7816)
10-19 19:08:29.368   638   638 F DEBUG   :     #13 pc 00429a10  /data/app/org.godotengine.kinematiccharacter3d-2/lib/arm/libgodot_android.so (_ZN20RasterizerSceneGLES312render_sceneERK9TransformRK12CameraMatrixbPPN15RasterizerScene12InstanceBaseEiP3RIDiSB_iSA_SA_SA_SA_i+5464)
10-19 19:08:29.368   638   638 F DEBUG   :     #14 pc 00e3d5e4  /data/app/org.godotengine.kinematiccharacter3d-2/lib/arm/libgodot_android.so (_ZN17VisualServerScene13_render_sceneE9TransformRK12CameraMatrixb3RIDjS4_S4_S4_i+4772)
10-19 19:08:29.368   638   638 F DEBUG   :     #15 pc 00e3c2e4  /data/app/org.godotengine.kinematiccharacter3d-2/lib/arm/libgodot_android.so (_ZN17VisualServerScene13render_cameraE3RIDS0_7Vector2S0_+580)
10-19 19:08:29.369   638   638 F DEBUG   :     #16 pc 00dcd364  /data/app/org.godotengine.kinematiccharacter3d-2/lib/arm/libgodot_android.so (_ZN20VisualServerViewport14_draw_viewportEPNS_8ViewportEN13ARVRInterface4EyesE+652)
10-19 19:08:29.369   638   638 F DEBUG   :     #17 pc 00dce3cc  /data/app/org.godotengine.kinematiccharacter3d-2/lib/arm/libgodot_android.so (_ZN20VisualServerViewport14draw_viewportsEv+996)
10-19 19:08:29.369   638   638 F DEBUG   :     #18 pc 00dc79f8  /data/app/org.godotengine.kinematiccharacter3d-2/lib/arm/libgodot_android.so (_ZN18VisualServerRaster4drawEv+92)
10-19 19:08:29.369   638   638 F DEBUG   :     #19 pc 000944d4  /data/app/org.godotengine.kinematiccharacter3d-2/lib/arm/libgodot_android.so (_ZN4Main9iterationEv+1124)
10-19 19:08:29.369   638   638 F DEBUG   :     #20 pc 00071ea0  /data/app/org.godotengine.kinematiccharacter3d-2/lib/arm/libgodot_android.so (Java_org_godotengine_godot_GodotLib_step+196)
10-19 19:08:29.369   638   638 F DEBUG   :     #21 pc 003440ad  /data/app/org.godotengine.kinematiccharacter3d-2/oat/arm/base.odex (offset 0x221000) (void org.godotengine.godot.GodotLib.step()+72)
10-19 19:08:29.369   638   638 F DEBUG   :     #22 pc 00347a21  /data/app/org.godotengine.kinematiccharacter3d-2/oat/arm/base.odex (offset 0x221000) (void org.godotengine.godot.GodotView$Renderer.onDrawFrame(javax.microedition.khronos.opengles.GL10)+84)
10-19 19:08:29.369   638   638 F DEBUG   :     #23 pc 74275d65  /data/dalvik-cache/arm/system@framework@boot.oat (offset 0x24a0000)
10-19 19:08:30.481   638   638 F DEBUG   : 
10-19 19:08:30.481   638   638 F DEBUG   : Tombstone written to: /data/tombstones/tombstone_06

**Comment by Alexia-AT-Digitecnology** [comment] 2017-10-19 22:53
Seems to be a duplicate of Issue #12192

**Comment by Alexia-AT-Digitecnology** [comment] 2017-10-20 22:48
I gave apk to a friend for testing on his cellphone and got crashed. His cellphone is a Samsung Galaxy J7.

GPU: Mali T-720 (OpenGLES3)
CPU: ARMv7 VFPv3 NEON | Cores x8 @1.5ghz
RAM: 1370 Mb

**Comment by guilhermefelipecgs** [comment] 2017-10-25 13:30
When Godot get stuck, I notice that cpu usage go to 100%.
![2017-10-25-110934_1595x714_scrot](https://user-images.githubusercontent.com/1387165/32000306-0da05ec2-b975-11e7-8a59-0d8ce3ffc488.png)
With 2D, cpu usage stay in ~70%

Godot 2 cpu usage in 3d stay in ~50%

**Comment by akien-mga** [comment] 2018-01-05 15:03
Let's close this one as a duplicate of the (newer, but more active) #11693.

**Closed by akien-mga** 2018-01-05 15:03 UTC
Labels: bug, platform:android, topic:rendering
