### ISSUE TITLE
Parent set to clip children with no children is drawn as completely black

### ISSUE THREAD

**Issue by SlugFiller** [godotengine/godot#71954] opened 2023-01-24 06:22 UTC
### Godot version

v4.0.beta14.official [28a24639c]

### System information

Windows 10, GTX 1080. Tested in various render backends

### Issue description

If a node is set to  Clip Children: Clip Only or Clip+Draw, and it has no visible children, it is drawn as completely black. The expected behavior is drawn normally for Clip+Draw, and made not visible for Clip Only.

### Steps to reproduce

1. Create any node that is drawn in 2D (e.g. `Polygon2D`, `Sprite2D`)
2. Set its Clip Children to anything other than Disabled.
3. Optional: Create a child node for it that is either non-drawing (e.g. `Node2D`), or is hidden (i.e. Set Visible to false)

### Minimal reproduction project

[reproduce_clip_nochildren.zip](https://github.com/godotengine/godot/files/10486803/reproduce_clip_nochildren.zip)

**Comment by clayjohn** [comment] 2023-01-24 06:24
Duplicate of https://github.com/godotengine/godot/issues/69179

**Closed by clayjohn** 2023-01-24 06:24 UTC
