### ISSUE TITLE
Shared animation's timeline when using multiple instances of a scene with AnimationTree

### ISSUE THREAD

**Issue by DGWana** [godotengine/godot#23529] opened 2018-11-05 15:51 UTC
**Godot version:**
Godot 3.1 d4028a3

**OS/device including version:**
Windows 10 64-bit

**Issue description:**
Apart from the issue with animation speed #22887 I cannot make each instanced character to have independent timelines. This is, of course, because AnimationNodeAnimation is a shared Resource and all instances of the same character must have the same playback for each animation, unless we manually make each AnimationNodeAnimation unique. But how to do that in code? Having all instance to share the timeline makes AnimationTree useless when you need to trigger the animations at different times.

![models](https://user-images.githubusercontent.com/29492561/48008302-0621b000-e0df-11e8-8145-df1061cf01bd.gif)

**Steps to reproduce:**
- Make a character scene with an AnimationTree using different animations
- In the main scene add multiple instances of the character scene
- Trigger one of the animations at different times in each instance of the character

**Minimal reproduction project:**
[AnimationTree.zip](https://github.com/godotengine/godot/files/2549412/AnimationTree.zip)

**Comment by DGWana** [comment] 2018-11-08 14:38
Is this just a duplicate of #22887? Animations having shared timelines will make each instance to update AnimationNodeAnimation each frame, once per instance. So if you have two instances, it will be updated twice per frame, doubling the speed. Is this the case?
I won't close the issue but if this is indeed a duplicate of the speed issue, it can be closed.

**Comment by akien-mga** [comment] 2018-11-08 14:44
It seems to be the same issue yes, closing as duplicate of #22887. I'll link your reproduction project there.

**Closed by akien-mga** 2018-11-08 14:44 UTC
