### ISSUE TITLE
Moving a project folder somewhere else causes entirety of assets to change MD5 hash

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#18841] opened 2018-05-13 17:27 UTC
Godot 3.0.2

I recently moved my projects around to reorganize my filesystem, then I noticed Godot generated a new MD5 for all of the assets in my project, and probably reimported them, for no reason (at least, no reason I would consider valid here).
To clarify: I didn't move assets within the project, I moved the project folder itself (the former would have been odd too though)

![image](https://user-images.githubusercontent.com/1311555/39969930-98ce04ac-56e3-11e8-9f38-cf05710fd8ed.png)

**Comment by Calinou** [comment] 2020-06-19 08:10
@Zylann Can you still reproduce this in Godot 3.2.1 or later?

**Comment by Zylann** [comment] 2020-06-19 22:42
MD5 hashes don't appear to be present in import files anymore.

However I just tried again on the same project: moved it to a different folder, opened it, but this time the *entirety* of `.import` files appeared in the Git diff... without actually being any different (and same line endings). I thought git repositories were self-contained Oo I have no idea how that happened.

**Comment by Calinou** [comment] 2020-06-19 22:52
@Zylann Alright, I'll close this then.

I'm not sure what could be causing the issue with text file differences. Maybe it was due to trailing whitespace or UTF-8 BOM?

**Closed by Calinou** 2020-06-19 22:52 UTC
Labels: enhancement, topic:editor, topic:import

**Comment by Zylann** [comment] 2020-06-19 23:01
@Calinou I highly doubt that a simple directory move would have inserted BOMs in all files. I checked them with Notepad++, nothing changed in them, really.
