### ISSUE TITLE
The editor crashes when selecting material node in advanced import settings for .blend file

### ISSUE THREAD

**Issue by joemicmc** [godotengine/godot#60380] opened 2022-04-19 20:52 UTC
### Godot version

4.0 alpha 6

### System information

Windows 10 x64, Blender 3.0.0

### Issue description

When trying to select the material node in the advanced import settings for a .blend file the editor crashes.

Running with --verbose shows the following:

```
Using present mode: VK_PRESENT_MODE_FIFO_KHR
Using present mode: VK_PRESENT_MODE_FIFO_KHR
Using present mode: VK_PRESENT_MODE_FIFO_KHR
Using present mode: VK_PRESENT_MODE_FIFO_KHR
Using present mode: VK_PRESENT_MODE_FIFO_KHR
Using present mode: VK_PRESENT_MODE_FIFO_KHR
import bpy, sys;print('Blender 3.0 or higher is required.', file=sys.stderr) if bpy.app.version < (3, 0, 0) else None;bpy.ops.wm.open_mainfile(filepath='D:/Applications/Godot/godot-blend-import-crash/cube.blend');bpy.ops.export_scene.gltf(export_keep_originals=True,filepath='D:/Applications/Godot/godot-blend-import-crash/.godot/imported/cube-872180318f08982aecd5834ac734b268.gltf',export_format='GLTF_SEPARATE',export_yup=True,export_extras=False,export_skins=False,export_materials='PLACEHOLDER',export_cameras=False,export_lights=False,export_colors=False,use_visible=False,use_renderable=False,export_texcoords=False,export_normals=False,export_tangents=False,export_nla_strips=False,export_frame_range=False,export_force_sampling=False,export_def_bones=False,export_apply=False);
C:\Program Files\Blender Foundation\Blender 3.0/blender.exe
'C:\Program Files\Blender Foundation\Blender 3.0\3.0\python\lib\site-packages\extern_draco.dll' exists, draco mesh compression is available
20:48:20 | INFO: Starting glTF 2.0 export
20:48:20 | INFO: Extracting primitive: Cube
20:48:20 | INFO: Primitives created: 1
20:48:20 | INFO: Finished glTF 2.0 export in 0.0020003318786621094 s

Blender 3.0.0 (hash f1cca3055776 built 2021-12-03 00:44:02)
Read prefs: C:\Users\joe\AppData\Roaming\Blender Foundation\Blender\3.0\config\userpref.blend
Read blend: D:/Applications/Godot/godot-blend-import-crash/cube.blend

Blender quit

glTF: Total buffers: 1
glTF: Total buffer views: 2
glTF: Total accessors: 2
glTF: Parsing mesh: 0
glTF: type vec3 component type: Float stride: 12 amount 8
glTF: accessor offset 0 view offset: 0 total buffer len: 168 view len 96
glTF: type float component type: UShort stride: 2 amount 36
glTF: accessor offset 0 view offset: 96 total buffer len: 168 view len 72
glTF: Total meshes: 1
glTF: Creating mesh for: Cube
Using present mode: VK_PRESENT_MODE_FIFO_KHR
Using present mode: VK_PRESENT_MODE_FIFO_KHR
Using present mode: VK_PRESENT_MODE_FIFO_KHR
ERROR: Attempted to append_array a variable of type 'Array' into a TypedArray of type 'Object'.
   at: (core/variant/container_type_validate.h:82)
ERROR: Condition "!_p->typed.validate(p_array, "append_array")" is true.
   at: append_array (core/variant/array.cpp:236)
Using present mode: VK_PRESENT_MODE_FIFO_KHR
Using present mode: VK_PRESENT_MODE_FIFO_KHR
```

### Steps to reproduce

- Create new general file in Blender (gives you a cube with default material)
- Save it inside a Godot project
- Open advance import settings by double clicking .blend file
- Select the material node

Outcome:
- Editor crashes

Expected:
- Can change material override settings etc.

![image](https://user-images.githubusercontent.com/7323103/164093501-98694d14-23a5-4f1f-9095-e872ace34977.png)

### Minimal reproduction project

[godot-blend-import-crash.zip](https://github.com/godotengine/godot/files/8516361/godot-blend-import-crash.zip)

**Comment by Calinou** [comment] 2022-04-19 23:02
Duplicate of https://github.com/godotengine/godot/issues/54807.

**Closed by Calinou** 2022-04-19 23:02 UTC
