### ISSUE TITLE
Missing icons in "Open a Directory" and "Open a File" dialogs

### ISSUE THREAD

**Issue by Kay-Eth** [godotengine/godot#65097] opened 2022-08-30 17:17 UTC
### Godot version

v4.0.alpha15.official [432b25d36]

### System information

Windows 11

### Issue description

There are missing icons at the top of the mentioned dialogs.

Open a Directory:
![image](https://user-images.githubusercontent.com/46926490/187500069-7650901b-b20f-487d-b686-b20f2725cba5.png)

Open a File:
![image](https://user-images.githubusercontent.com/46926490/187501000-cf2d9616-9308-40f8-b640-c84b7175d0be.png)

### Steps to reproduce

Just open any project, and (for example) try select a new project's icon using directory symbol on the right.

**Comment by Calinou** [comment] 2022-08-30 17:22
Duplicate of https://github.com/godotengine/godot/issues/65090.

**Closed by Calinou** 2022-08-30 17:22 UTC
