### ISSUE TITLE
Viewport Node 'Escapes' editors 2d vieport

### ISSUE THREAD

**Issue by Einlander** [godotengine/godot#6172] opened 2016-08-16 15:16 UTC
**Operating system or device - Godot version:**
Windows 2.1 stable Official (steam)

**Issue description** (what happened, and what was expected):
When using the viewport on a panel, if you drag the editors viewport to the left, the in scene viewport floats over the right side controls, If you drag to the right, the in scene viewport floats underneath the left side controls.

**Steps to reproduce:**
Use the attached project as I am unable to manually recreate it.
https://imgur.com/a/fU94S

**Link to minimal example project** (optional but very welcome):
[Building Gen.zip](https://github.com/godotengine/godot/files/420607/Building.Gen.zip)

**Comment by vnen** [comment] 2016-09-19 23:37
Another example by @Hinsbart, from the Platformer split screen demo:

![viewport_bug](https://cloud.githubusercontent.com/assets/8281916/18650808/7fae7074-7ec7-11e6-9e1d-4fb635b0a66a.gif)

**Comment by akien-mga** [comment] 2016-09-20 03:15
Actually a duplicate of the good old #1840.

**Closed by akien-mga** 2016-09-20 03:15 UTC
Labels: bug, topic:rendering, usability
