### ISSUE TITLE
Switching window_mode causes crash

### ISSUE THREAD

**Issue by SenhorPatolino** [godotengine/godot#68389] opened 2022-11-07 22:06 UTC
### Godot version

4.0.beta4

### System information

Windows 10, Vulkan, NVIDIA Driver V.526.47

### Issue description

Changing WINDOW_MODE causes project to crash, this seems to be pretty inconsistent whether it happens. When it crashes it causes audio jittering too:
https://user-images.githubusercontent.com/61413244/200417433-98155f68-a710-4bbb-89d8-e333c6ed4303.mp4

Debugger outputs no errors or warnings. Code:

```
@export var windowed = bool(false)

func _process(_delta):
	if Input.is_action_just_pressed("Switch_window_mode"):
			windowed = !windowed
			print(windowed)
			
	if windowed == true:
		DisplayServer.window_set_mode(DisplayServer.WINDOW_MODE_FULLSCREEN)
		
	elif windowed == false:
		DisplayServer.window_set_mode(DisplayServer.WINDOW_MODE_WINDOWED)
```

As you can see, im using `_process(_delta):` for changing the window mode, however using a "once" function like `_on_button_pressed():` also causes this crash.

This also seems to rely a lot scene complexity, while working on the Minimal reproduction project I noticed this did not happen, but when I applied the same line of code to my own project, it caused the crash depending on various factors, such as:

- Disabling the rotating fan makes the crashing a tiny bit less frequent
- Disabling the fade in-out object also helps a bit
- Disabling sound helps

So again, it depends on the scene complexity apparently, and so reproducing it in a brand new file might not cause such issue. Also note that I tried changing all stretch options to make sure that wasn't the issue, it wasn't, neither was viewport resolution or resizable.

https://user-images.githubusercontent.com/61413244/200425549-f06bf8fd-cbaa-4153-ab5f-92f28354dcae.mp4

### Steps to reproduce

Create a simple "toggle window_mode" code. Result is inconsistent.

### Minimal reproduction project

Even though I did not get the error in here, I'll still prove it for the sake of it:
[godot debug project.zip](https://github.com/godotengine/godot/files/9955830/godot.debug.project.zip)

**Comment by RumblingTurtle** [comment] 2022-12-06 12:01
MPR causes the whole window manager to freeze. Rebooting helps but it seems like you misplaced your last if/elif statement:
```
@export var windowed = bool(false)

func _process(_delta):
	if Input.is_action_just_pressed("Switch_window_mode"):
			windowed = !windowed
			print(windowed)
	
	if windowed == true:
		DisplayServer.window_set_mode(DisplayServer.WINDOW_MODE_FULLSCREEN)
		
	elif windowed == false:
		DisplayServer.window_set_mode(DisplayServer.WINDOW_MODE_WINDOWED)

```
Note that your example changes the window mode on every tick. So I assume you are just ddosing your window manager and it  crashes. You should probably make a change once when the `Switch_window_mode` is registered
```
extends Camera3D

@export var windowed = bool(false)

func _process(_delta):
	if Input.is_action_just_pressed("Switch_window_mode"):
			windowed = !windowed
			print(windowed)
			if windowed == true:
				DisplayServer.window_set_mode(DisplayServer.WINDOW_MODE_EXCLUSIVE_FULLSCREEN)
			else
				DisplayServer.window_set_mode(DisplayServer.WINDOW_MODE_WINDOWED)

```

**Comment by SenhorPatolino** [comment] 2022-12-07 04:02
Hello, the code I used in this report is quite old, im still a beginner in Godot so back then I wasn't aware of how to use functions very well

The video which I attached here already had this "sophisticated" way of doing it, by connecting the UI button "toggled" signal:

![image](https://user-images.githubusercontent.com/61413244/206084346-48d06895-0c28-48c2-ad53-aa87f60e0010.png)

I can confirm that in Beta 7, the crash no longer happens, however when it should've probably crashed, it just make the screen extremely small, plus, it causes issues with OBS ( black screen )


https://user-images.githubusercontent.com/61413244/206084833-c2a9743c-405d-4473-b930-dbcd9d2b0c29.mp4

Another thing worth mentioning, this issue ONLY happens with WINDOW_MODE_EXCLUSIVE_FULLSCREEN, if I use WINDOW_MODE_FULLSCREEN instead, it works perfectly, no crashes, no black screen with my record software and no problems with screen size

**Comment by RumblingTurtle** [comment] 2022-12-07 10:53
@SenhorPatolino can you please try out this example to see if the issue still can be reproduced on your machine?
[MRP.zip](https://github.com/godotengine/godot/files/10175290/MRP.zip)

**Comment by SenhorPatolino** [comment] 2022-12-07 19:07
About the pass, it was my mistake, im aware it does nothing but when I took the screenshot it was a left over, I just made the code a comment instead of deleting it :P

Tested your file and it works, im in another computer so I can't install OBS ( hell I shouldn't even install Godot but shh ), but I was able to test the fullscreen functionality and it worked correctly, but I wonder why doesn't it work on my project. 

My project spits out an error when it initializes but I feel like its unrelated, still, once I get home I'll be sending it here

**Comment by SenhorPatolino** [comment] 2022-12-08 03:52
This is the error that I get on my project ( MRP doesn't have it though ), I did a search on google and found nothing related to it

![image](https://user-images.githubusercontent.com/61413244/206351660-c6739e81-5703-4b31-9652-95e1fbbace70.png)

OBS Studio still got visual glitches

https://user-images.githubusercontent.com/61413244/206352375-dce15d73-d1ba-4eed-a9c5-cfb3c00b4363.mp4

In case you're wondering, I was just switching between windowed and fullscreen each 1 second or so

**Comment by SenhorPatolino** [comment] 2022-12-08 13:26
Yeah no worries, I just find it odd to happen.

However, I just found the issue, for some reason if my project starts with exclusive_fullscreen on by default, those issues happen, but if it starts in any other mode, it works properly ( even when I toggle with exclusive_fullscreen on my code )

**Comment by RumblingTurtle** [comment] 2022-12-08 14:57
> Yeah no worries, I just find it odd to happen.
> 
> However, I just found the issue, for some reason if my project starts with exclusive_fullscreen on by default, those issues happen, but if it starts in any other mode, it works properly ( even when I toggle with exclusive_fullscreen on my code )
> 
> Since the problem went from switching mode causing crash to exclusive_fullscreen causing issues, I might just close this as not planned and create a new one
> 
> Tested at the MRP and that also happened

I think reopening a new issue won't help without a reproducible example

**Comment by RumblingTurtle** [comment] 2022-12-08 16:12
I meant the cubemap thing. OBS' issue seems to be on the OBS' side

**Comment by akien-mga** [comment] 2023-02-22 13:16
The issue isn't super clear to me, but as I understand it the report is about:
- Issues with OBS, which are probably not Godot problems
- Specific issue with a project using Cubemaps, but we don't have clear steps for reproduce nor a MRP for this, so this can't really be looked into further

So closing for now.

**Closed by akien-mga** 2023-02-22 13:16 UTC
Labels: bug, topic:porting, crash
