### ISSUE TITLE
Intellisense can’t detect custom signal name with [Signal] attribute in C#

### ISSUE THREAD

**Issue by JNatheriver** [godotengine/godot#83580] opened 2023-10-18 20:09 UTC
### Godot version

v4.1.2.stable.mono.official [399c9dc39]

### System information

Godot v4.1.2.stable.mono - Visual Studio Code 1.83.1 - Windows 10.0.22621 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1050 (NVIDIA; 31.0.15.3742) - Intel(R) Core(TM) i5-9300H CPU @ 2.40GHz (8 Threads)

### Issue description

I have built the scripts and the signal appears in the node tab and works perfectly. Howerver, Intellisense in VSCode shows this error ‘Node2D.SignalName’ does not contain a definition for <CustomSignalName> (CS0117), (CS1061). This error is an annoying issue that can hinder the debugging process.

### Steps to reproduce

1. Create a new C# script in a node
2. Add [Signal] attribute to create a custom signal.
3. Try to use this custom signal by either using the signal name in the signal declaration script by emitting the signal or in an observer script to receive the signal.
4. Observe that intellisense shows an error ‘Node2D.SignalName’ does not contain a definition for <CustomSignalName> (CS0117) or (CS1061) when subscribing to the signal.

![image](https://github.com/godotengine/godot/assets/119390321/d5a877a1-bb2e-46b5-80cd-2e3a2fe6b466)
![image](https://github.com/godotengine/godot/assets/119390321/ecac0138-dcf0-42f8-b76e-7eec935844e2)

### Minimal reproduction project

N/A

**Comment by raulsntos** [comment] 2023-10-18 21:11
Duplicate of https://github.com/godotengine/godot-csharp-vscode/issues/57

**Closed by raulsntos** 2023-10-18 21:11 UTC
