### ISSUE TITLE
Tilemap offset when using odd numbered Tiles

### ISSUE THREAD

**Issue by jjtdeveloper** [godotengine/godot#74755] opened 2023-03-11 06:32 UTC
### Godot version

4.0.stable

### System information

Windows 10, Forward+, 1050ti

### Odd sized tiles have half pixel offset that cannot be fixed
The image below is of a minimal reproduction project

tiles function correctly when using any even numbered tileset, only odd numbered tilesets cause this issue.
I attempted to fix it using a 0.5 offset of the _**Paint Property : Texture Origin**_, however, the property can only be adjusted in steps of 1 pixel, therefore just causing a -0.5 offset issue.
![image](https://user-images.githubusercontent.com/57380566/224468431-a467747f-21a8-48ae-b48d-57f021fd5614.png)

### Steps to reproduce

1. Create a new Godot 4.0.stable project
2. Create a 2D scene
3. Add a tilemap node as a child of the scene
4. Set the tilemap property **_CanvasItem>Texture>Filter_** to "Nearest" (for pixel art)
5. Set the tilemap property **_Tilemap>Cell Quadrant_** to 15px (the width of your odd width tiles)
6. Create a new tileset in the tilemap
7. Drop in your tilemap file into the _**tiles**_ region of the **_tileset_** tab on the bottom bar
8. Select yes when prompted to automatically create tiles
9. Set **_texture_region_size_** property if not already set (same size as step 5)

### Minimal reproduction project

Minimal reproduction project (did only what was listed in the steps to reproduce)
[TilesetIssueMinimalProject.zip](https://github.com/godotengine/godot/files/10947803/TilesetIssueMinimalProject.zip)

**Comment by arkology** [comment] 2023-03-11 07:01
Duplicate of https://github.com/godotengine/godot/issues/62911?

**Comment by kleonc** [comment] 2023-03-11 12:56
Duplicate of #62911.

**Closed by kleonc** 2023-03-11 12:56 UTC
