### ISSUE TITLE
Astar node id to be a string or variant

### ISSUE THREAD

**Issue by cefleet** [godotengine/godot#6641] opened 2016-09-29 12:21 UTC
Pretty straight forward. It could mesh better with other utilities if the id wasn't required to be an integer.

**Comment by Zylann** [comment] 2016-09-29 12:33
Which use case are you thinking about? integers look fine for me, they are fast and even handy.

**Comment by cefleet** [comment] 2016-09-29 12:54
Well in my specific case, if I am tracking the nodes(or as I call them tiles) for other reasons, like what is placed on it, what tile type it is etc, I keep another dictionary with that information that has a string as the id. I then have to record the astar id in that dictionary. It would be nice to have the astar id be the same as the item id in the dictionary.
Now I can change my dictionary to accommodate that, but what if a plugin or module does not allow you to change the dictionary so easily. 
It really is just a suggestion. I'm loving how it generally works.

**Comment by Zylann** [comment] 2016-09-29 13:02
For now I would stick for integers because they are the cheapest option. Having Strings means memory has to be allocated for every name (unless StringName is used?).

**Comment by Noshyaar** [comment] 2018-04-06 11:38
Still reproducible/relevant in 3.1 master 9ad1800 : astar still uses int as index

**Comment by Toshiwoz** [comment] 2019-05-10 16:14
In an example I found [here](https://pastebin.com/eLxistVD), and also in my case I find hard to connect points, another array or dictionary have to be used in order to find an easy way to connect points.
I'm thinking if there's a way to do it without another array/dictionary.. but haven't till now.

**Comment by akien-mga** [comment] 2020-05-26 11:12
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!

**Closed by akien-mga** 2020-05-26 11:12 UTC
Labels: feature proposal, topic:core
