### ISSUE TITLE
RichTextLabel: changes to 'text' have no effect to text entered with append_text()

### ISSUE THREAD

**Issue by andrea-calligaris** [godotengine/godot#93812] opened 2024-07-01 13:06 UTC
### Tested versions

Godot Engine v4.2.2.stable.official

### System information

Xubuntu 22.04.4 LTS

### Issue description

Changes to RichTextLabel's `text` property have no effect to text previously entered with `append_text()`

Due to the particular way that RichTextLabel works, with the stack and everything, it's important to highlight that this behavior is **NOT** consistent with the documentation, see:

> **Description**
Any edits made to `text` will erase previous edits made from other manual sources such as `append_text()`

### Workaround

The workaround is to use `clear()`, despite the documentation explicitly says that just setting `text` should be enough:

> **void clear()**
Clears the tag stack.
Note: This method will not modify text, **but setting text to an empty string also clears the stack.**

### Steps to reproduce

**Example project provided.**
Alternatively:

### Steps

- Change the RichTextLabel with `append_text()`
- Later, through a button, attempt to clear the label with `$RichTextLabel.text = ""`
- Add some more text with `append_text()`
- The new text is going to be appended to the previously added text that was supposed to have been cleared.

### Minimal reproduction project (MRP)

[RichTextLabelBug.zip](https://github.com/user-attachments/files/16053237/RichTextLabelBug.zip)

**Comment by andrea-calligaris** [comment] 2024-07-01 13:12
Possibly related to:
#61260
#18413
#12882

**Comment by AThousandShips** [comment] 2024-07-01 13:52
Sounds like a duplicate of:
* https://github.com/godotengine/godot/issues/89091

Which has already been fixed but wasn't cherry picked for 4.2

**Comment by AThousandShips** [comment] 2024-07-28 09:59
This error being present in 4.2.2 but not latest means this is resolved, sorry that I didn't notice you reopened this

Please wait for a future 4.2.x version and that issue to be cherry picked, as it has been resolved

**Closed by AThousandShips** 2024-07-28 09:59 UTC
Labels: needs testing, topic:gui
