### ISSUE TITLE
When "save on focus loss" is enabled if you are out of godot and trigger mouse actions, godot save interrupts mouse actions

### ISSUE THREAD

**Issue by samangol** [godotengine/godot#69524] opened 2022-12-03 07:08 UTC
### Godot version

v4.0.beta7.official [0bb1e89fb]

### System information

Linux mint cynnimon, vulkan, intel hd graphics family 4400, core i5 4th

### Issue description

When "save on focus loss" is enabled if you are out of godot which means godot will auto save, every click in anywhere outside of godot editor makes engine auto save and interrupt mouse actions.
example: godot is open with save on focus loss option, i go to firefox to download an asset, when i right click to open in new tab, godot save window comes up and saves godot(this happens very fast i barely noticed) and closes the options menu of firefox, or when i wanted to select some code in vs code and right clicked same happens.

### Steps to reproduce

example: godot is open with save on focus loss option, i go to firefox to download an asset, when i right click to open in new tab, godot save window comes up and saves godot(this happens very fast i barely noticed) and closes the options menu of firefox, or when i wanted to select some code in vs code and right clicked same happens.

### Minimal reproduction project

[New Game bug report.zip](https://github.com/godotengine/godot/files/10145888/New.Game.bug.report.zip)

**Comment by Calinou** [comment] 2022-12-04 20:09
Can you reproduce this after enabling **Single Window Mode** in the Editor Settings then restarting the editor?

**Comment by Rindbee** [comment] 2022-12-29 13:16
Seems to be a duplicate of #61875.

**Comment by Calinou** [comment] 2022-12-29 19:52
Duplicate of https://github.com/godotengine/godot/issues/61875.

**Closed by Calinou** 2022-12-29 19:52 UTC
Labels: bug, topic:editor
