### ISSUE TITLE
Can't copy and paste tilemap 2D node from one scene to another

### ISSUE THREAD

**Issue by The2AndOnly** [godotengine/godot#86315] opened 2023-12-18 21:45 UTC
### Tested versions

Godot v4.2.stable

### System information

Godot v4.2.stable - Windows 10.0.22621 (I'm actually on Windows 11) - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 4050 Laptop GPU (NVIDIA; 31.0.15.3623) - 13th Gen Intel(R) Core(TM) i7-13650HX (20 Threads)

### Issue description

If you go on scene 1, copy a tilemap 2D node, then go to scene 2, paste the tilemap 2D node, then the tilemap 2D node on scene 1 will get it's source deleted and it will become corrupted. Copying and pasting a tilemap 2D node on the same scene works just fine. 

### Steps to reproduce

Step 1: Create 2D scene with tilemap with a source and draw some stuff with it
Step 2: Create a new 2D scene
Step 3: Go back to scene 1 and copy the tilemap 2D node
Step 4: Go to scene 2 and paste the tilemap 2D node
Step 5: Go back to scene 1 and see the tilemap 2D node corrupted
![image](https://github.com/godotengine/godot/assets/99462581/90206e22-4909-4bf8-9254-85b25ffe05af)

### Minimal reproduction project (MRP)

[broken.zip](https://github.com/godotengine/godot/files/13708835/broken.zip)

**Comment by KoBeWi** [comment] 2023-12-21 18:45
Duplicate of #80076
Copying TileMap to another scene will duplicate the TileSet. You should save the TileSet to file to avoid this issue. Or you can reload the original scene and the tiles will return to normal.

**Closed by KoBeWi** 2023-12-21 18:45 UTC
