### ISSUE TITLE
PoolStringArray doesn't work in Autoloads

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#29047] opened 2019-05-20 19:06 UTC
**Godot version:**
3.2.dev.custom_build. af731f8

**OS/device including version:**
Ubuntu 19.04

**Issue description:**
This is an empty PoolStringArray in Autoload script
```
extends Node

#var pool : Array = []
var pool : PoolStringArray = PoolStringArray([])
```
This is a code in node which doesn't work
```
extends Node2D

func _ready() -> void:
	AA.pool.append("FFF")
	print(AA.pool.size())
```
This print to output 0
When I change comment in Autoload script to create Array instead PoolStringArray, then Godot print to output 1

**Minimal reproduction project:**
[AA.zip](https://github.com/godotengine/godot/files/3199409/AA.zip)

**Comment by clayjohn** [comment] 2019-05-21 06:16
I think this has to do with the way that PoolArrays are accessed. I don't think this is supposed to work because PoolArrays get copied on read or write. So you can't call append on them and expect to alter the original. 

I may be wrong, but I think what you have to do is
```
var poo = AA.pool
poo.append("FFF")
AA.pool = poo
```

**Comment by qarmin** [comment] 2019-05-21 15:10
So why PoolStringArray have append function?

It is strange, that it works inside one file, but it won't work in autoload so for me it is definitely a bug.
This code which use autorun file from above prints to output: 0(bad) and 1(good)
```
extends Node2D

var pool : PoolStringArray = PoolStringArray([])

func _ready() -> void:
	AA.pool.append("FFF")
	print(AA.pool.size())
	
	pool.append("FFF")
	print(pool.size())
```

**Comment by akien-mga** [comment] 2020-01-18 14:21
Duplicate of #15265.

**Closed by akien-mga** 2020-01-18 14:21 UTC
Labels: topic:core
