### ISSUE TITLE
LineEdit problem on Android

### ISSUE THREAD

**Issue by comrade96** [godotengine/godot#35777] opened 2020-01-31 09:53 UTC
**Godot version:** 3.2 STABLE

**OS/device including version:** ANDROID 8.0

**Issue description:** Can not edit a LineEdit nodes on Android.Which works fine on PC

**Steps to reproduce:** Just create a LineEdit node, export it to android.

**Minimal reproduction project:**

**Comment by volzhs** [comment] 2020-01-31 10:04
duplicate of #35753

**Closed** 2020-01-31 10:04 UTC
