### ISSUE TITLE
No way to have convenient initial values when creating nodes

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#12425] opened 2017-10-26 21:53 UTC
Following this revert #12308, I'm asking for the possibility to set different default values on some nodes for convenience, when they are created in the editor.
For example, I made a PR earlier, where DirectionalLights created in the editor would spawn with a natural sun-like angle, instead of the default horizontal axis: https://github.com/godotengine/godot/pull/11587

The problem is, for some reason, even though I do this in the constructor, it overwrites the transform loaded from the scene. 
My theory is that Godot does very custom initialization of class fields by calling constructors manually and setting properties in between, while I expected this to happen AFTER all constructors were called.
This makes my proposal impossible, hence why it got reverted...

So... is there a better way to do it? Because I don't know how :/
cc @reduz

**Comment by Web-eWorks** [comment] 2018-06-16 02:44
After doing some digging, I can confirm that Godot is not doing custom construction. It all comes down to:
https://github.com/godotengine/godot/blob/78fbf507f034deac8ef5ac448baf0778455558c6/core/os/memory.h#L97
which allocates the memory, and then lets C++ handle the construction. The [default initializers](http://en.cppreference.com/w/cpp/language/default_initialization) are automatically called, oldest first (`Object::Object()`, `Node::Node()`, etc...) ending with the ctor of the class being constructed (e.g. `DirectionalLight::DirectionalLight()`).

For scene and resource loading, the construction happens here:
https://github.com/godotengine/godot/blob/78fbf507f034deac8ef5ac448baf0778455558c6/scene/resources/packed_scene.cpp#L156-L178
which checks the class exists, instances a default otherwise (based on the type of the node's parent), and casts the instanced `Object*` to `Node*`.

Then, later on, starting at [line 185](https://github.com/godotengine/godot/blob/78fbf507f034deac8ef5ac448baf0778455558c6/scene/resources/packed_scene.cpp#L185), the actual properties are set. If things aren't working, it's in this section that the culprit likely lies.

**Comment by Web-eWorks** [comment] 2018-06-16 03:28
Also, I figured out what the problem you were encountering was - at the time, the transform was built using the `data.rotation` variable, and the scene was only saving the `data.transform` property.
https://github.com/godotengine/godot/blob/14b1741cbf998f6d950a006681b15803362442d7/scene/3d/spatial.cpp#L86-L92
(Excerpt from the provided example project:)
```
[gd_scene format=2]

[node name="DirectionalLight" type="DirectionalLight"]

transform = Transform( 1, 0, 0, 0, 0, -1, 0, 1, 0, 0, 0, 0 )
```
When the node was initialized, `data.rotation` was set by your addition of `set_rotation_in_degrees`, and then never overridden by loading the scene. The transform was marked dirty (either by being added to the scene for the first time, or by `set_rotation_in_degrees`) and the transform was then recalculated, resetting the rotation to the initializer's value.

@Zylann, @akien-mga, I believe this resolves the issue, and it can be closed.

**Comment by Zylann** [comment] 2018-06-16 13:43
How can we have initial values when instancing a node in editor then?

**Comment by Web-eWorks** [comment] 2018-06-16 14:13
Like so:

```c++
DirectionalLight::DirectionalLight(){ 
//Depending on what you are doing, you may not need the TOOLS_ENABLED check
#ifdef TOOLS_ENABLED
set_transform(new_transform);
#endif
}
```

You just have to set your initial values in a way that doesn't cause loaded values to be overriden. This may warrant a new issue regarding how Spatial transforms are loaded from disk, but setting initial values works just fine.

**Comment by Web-eWorks** [comment] 2018-06-16 17:37
Fair warning, I came about this knowledge purely through reading the source, and it may not be 100% accurate. If you can still reproduce the bug on current source, I'll take another crack at it.

Here's how it went:
1. Construct the node. Your constructor sets `data.rotation` to the initial rotation (which marks `DIRTY_LOCAL`.)
2. Load the node's properties from the PackedScene. This sets `data.local_transform` (and marks `DIRTY_VECTORS`.)
3. Add the node to the scene: calls `_notification(NOTIFICATION_ENTER_TREE)`. If running standalone, skip to 5, as this calls `get_transform()`.
4. Something somewhere (probably editor code) calls `get_transform()` _before_ `get_rotation()` or `get_scale()` (the functions that update the vectors as a side-effect) have been called. None of the flags have been unset.
5. Because `DIRTY_LOCAL` hasn't been unset, `get_transform()` calls `_update_local_transform()` as linked above, which updates the transform using the value of `data.rotation`, which hasn't been changed to reflect the loaded transform. This clears `DIRTY_LOCAL`.
6. Later, `get_rotation()` or `get_scale()` are called. Because `DIRTY_VECTORS` is still set, it updates these values from the (now overridden) transform.
7. Voila, your light now always loads to be pointing in the direction set in the constructor. Aren't race conditions fun? :/

The workaround is simple - use `set_transform` instead of `set_rotation`, or have the loading code update the vectors right away when loading the scene.

**Comment by Calinou** [comment] 2020-12-01 13:56
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!

**Closed by Calinou** 2020-12-01 13:56 UTC
Labels: enhancement, topic:editor
