### ISSUE TITLE
Control nodes multiply in size when child animationPlayer contains RESET track and a different scene is launched

### ISSUE THREAD

**Issue by Voidraizer** [godotengine/godot#90079] opened 2024-03-31 18:22 UTC
### Tested versions

- Reproducible in Godot Engine v4.2.stable.mono.official [46dc27791]

_Bugsquad edited:_
- Reproducible in Godot Engine v4.2.stable
- Reproducible in Godot Engine v4.1.stable
- Reproducible in Godot Engine v4.0.stable

### System information

Godot v4.2.stable.mono - Windows 10.0.19045 - Vulkan (Mobile) - dedicated NVIDIA GeForce RTX 3090 Ti (NVIDIA; 31.0.15.5186) - 12th Gen Intel(R) Core(TM) i9-12900K (24 Threads)

### Issue description

Certain conditions cause nodes to erroneously change size. When this happens, each time the steps are reproduced, the relevant nodes will increase in size by a multiple of the original size - i.e. the first time they will end up 2x the original, then 3x, then 4x and so on.

### Steps to reproduce

The hierarchy [looks like this](https://imgur.com/LVxtMZC) where you have containers that structure the UI, an empty control node as a child to the container, and the another kind of node as a child of the empty control node. This last child also has an AnimationPlayer with a RESET track. This is to allow the other kind of node to be animated. Finally, set the control node and its child to use the anchor layout mode with the anchor preset set to Full Rect. I have tested this with Buttons, Labels, and LineEdits.

All of the above needs to be in 1 scene. Then while that scene is open in one tab, open a different scene in another tab and use **Run Current Scene** so the different scene is launched. You can immediately close that and go back to the original tab. In my example, [this is what it would have started looking like](https://imgur.com/Lbd4Nxu) and [this is how it will end up](https://i.imgur.com/XSXgzso.png). The new size of that node will be exactly 2x the starting size. If you repeat the process and launch the different scene again and come back, the node will now be 3x the starting size.

I recorded a video of this occurring, but I don't know how long it will remain available: https://streamable.com/5elh96.

### Minimal reproduction project (MRP)

[NodeSizeBug.zip](https://github.com/godotengine/godot/files/14817234/NodeSizeBug.zip)

Simply open both the main and different scenes so there are 2 tabs open. Launch the different scene with F6, then kill it. Go back to the main tab and the button should be a multiple bigger.

**Comment by Voidraizer** [comment] 2024-03-31 18:23
I forgot to include - Deleting the RESET track from the AnimationPlayer fixes the issue and nodes will no longer grow in size.

**Comment by TokageItLab** [comment] 2024-04-01 12:39
I assume it is a bug in `reset_on_save`. It seems like unintended behavior is occurring in the case of saving a background scene.

**Comment by Borges-IST-2003** [comment] 2024-04-01 16:22
Is there anyone already working to fix this?
I wanted to fix it.

**Comment by TokageItLab** [comment] 2024-04-01 17:10
@Borges-IST-2003 The challenge to fix it is welcome, but please work with attention to the following:

I think the easiest way to fix this is probably to insert an
```cpp
scene->propagate_notification(NOTIFICATION_INTERNAL_PROCESS);
```
in the `editor_node.cpp`, on the line immediately after the AnimationMixer reset/restore call. However, this one-frame forced process could cause a non-reset value to be stored in .tres, and we need to make sure that does not happen.

But before doing so, we need to investigate if there are any other Nodes that have this same bug.

If no other Node seems to have the same bug, then it is likely that the problem is specific to Button, and you may need to fix the update process of `Button::_notification()`.

If there are other Nodes that have the same bug, we need to figure out how to handle it correctly in editor_node.cpp or AnimationMixer.

**Comment by Borges-IST-2003** [comment] 2024-04-01 18:38
Ok, sounds good, I'll get on it.

**Comment by KoBeWi** [comment] 2024-04-01 18:38
Duplicate of #74047 btw.

**Comment by KoBeWi** [comment] 2024-04-02 18:10
No, that's #89877

**Comment by Borges-IST-2003** [comment] 2024-04-03 14:31
How do I debug this?
I'm trying to run the debugger the way that it says in the documentation [here](https://docs.godotengine.org/en/stable/contributing/development/debugging/index.html#debugging-the-editor), and Im getting the mistake "no executable file specified".
Is there a way to see what is going on in the code step by step, so I can see what is changing as I switch scenes while reset on save is on.
It's my first time contributing here so sorry for the questions.
![Screenshot from 2024-04-03 15-31-11](https://github.com/godotengine/godot/assets/105735770/c258472b-6db5-42dc-a9b9-bc09dc81cc7d)

**Comment by Borges-IST-2003** [comment] 2024-04-04 17:16
Ok, I believe that the bug is specific to the button because I have tried to replicate the bug with other control nodes but couldn't.
I'm having some dificulty locating where is the problem tho, because when the button is saved the correct size is stored, the problem is when the scene gets reloaded, that seems to be when the size is wrongly adjusted.
Any adivice on how to proceed?
Thanks

**Comment by TokageItLab** [comment] 2024-04-04 17:33
I guess this is probably due to the fact that the automatic size adjustment is done at the next frame or at the Draw frame, since the scene in the other tab is not drawn.

**Comment by Borges-IST-2003** [comment] 2024-04-04 19:23
What would be the "next frame"?
It's not at the draw frame, because when the button.cpp gets the NOTIFICATION_DRAW it already has the wrong height and width value.

**Comment by Borges-IST-2003** [comment] 2024-04-05 12:48
What do I have to do to propagate a notification?
I've tryed to do something like NOTIFICATION_EDITOR_PRE_SAVE but in the method _reset_animation_mixers.
I've also defined it in Node.xml, node.h and bind it in node.cpp, however Im gettign the error:
------------------------------------------------------------------------------
editor/editor_node.cpp:1770:36: error: 'NOTIFICATION_EDITOR_PRE_RESET' was not declared in this scope
 1770 |     p_node->propagate_notification(NOTIFICATION_EDITOR_PRE_RESET);
      |                                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
editor/editor_node.cpp:1795:36: error: 'NOTIFICATION_EDITOR_POST_RESET' was not declared in this scope
 1795 |     p_node->propagate_notification(NOTIFICATION_EDITOR_POST_RESET);
------------------------------------------------------------------------------
I cant propagate any notification here, including NOTIFICATION_EDITOR_PRE_SAVE.

**Comment by Borges-IST-2003** [comment] 2024-04-05 14:30
At the draw frame the button has already the wrong value, but if I render it again, on NOTIFICATION_EDITOR_POST_SAVE,  the button has the original values, it is somewhere between save and draw that the value gets changed it seems, but then it gets changed again back to the original value when I try to run the scene again, and then it gets the wrong value on draw.

**Comment by TokageItLab** [comment] 2024-04-05 23:29
Probably, this is a problem with the `ControlNode`, not just the `Button`.
Reset animation contains a position value, and the behavior of the bug differs depending on the Anchor mode. If you look at `ControlNode::set_position()`, there are several update methods in it, but perhaps something in it is not working in the hidden tab and is causing it to update to the wrong value.

**Closed** 2024-05-06 13:19 UTC
Labels: bug, confirmed, topic:gui, topic:animation
