### ISSUE TITLE
Hidden export hint for variables used only in PackedScenes

### ISSUE THREAD

**Issue by mrzapp** [godotengine/godot#30421] opened 2019-07-08 06:57 UTC
I'd like to propose a way for exported variables not to show up in the inspector. This is for when the variable needs to be saved into a PackedScene, but should not be editable by designers.

An example of such a variable could be the state of an NPC.

In order to not mess with the parser too much, it could be added as a keyword, like this:  
```
export hidden (STATE) var state : int = STATE.IDLE
```

**Comment by bojidar-bg** [comment] 2019-07-08 08:47
Duplicate of #5988. (even the `export hidden` idea: https://github.com/godotengine/godot/issues/5988#issuecomment-237230832. Great minds...)

**Closed by bojidar-bg** 2019-07-08 08:47 UTC
