### ISSUE TITLE
Inconsistent behavior with buttons when viewed in editor vs after exporting

### ISSUE THREAD

**Issue by Gamepro5** [godotengine/godot#76737] opened 2023-05-04 21:20 UTC
### Godot version

4.0.2 Stable

### System information

Windows 10; AMD Ryzen 7 3700X 8-Core Processor 3.60 GHz

### Issue description

Buttons with a text followed by a new line character do not show the newline in-editor, but does show it after exporting.

### Steps to reproduce

1.) Create a new project with a button control node.
2.) In the text attribute of the control node, put "play" followed by clicking the enter key (new line)
3.) Click play to view the project in-editor. Observe how the button reads "play", and pay attention to the height of the button.
4.) Export the project using a windows template. Run the exported project. Observe how the button reads "play" but renders the new line, making the button twice as tall as it was in the editor.

### Minimal reproduction project

N/A

**Comment by Calinou** [comment] 2023-05-04 21:42
- Duplicate of https://github.com/godotengine/godot/issues/74351

**Closed by Calinou** 2023-05-04 21:42 UTC
