### ISSUE TITLE
LineEdit's cursor sometimes disappears when set scale.X < 1

### ISSUE THREAD

**Issue by denghe** [godotengine/godot#44253] opened 2020-12-10 07:06 UTC
**Godot version:**
3.2.4 beta3

**OS/device including version:**
win10 / rx5700 GLES3

**Issue description:**
LineEdit's cursor sometimes disappears when set scale.X < 1
using custom font:  .fnt + .png

![image](https://user-images.githubusercontent.com/3364637/101733070-337c8b80-3af9-11eb-9823-64df02d77e4a.png)

![image](https://user-images.githubusercontent.com/3364637/101732977-03cd8380-3af9-11eb-9e25-5de3702f1117.png)

![image](https://user-images.githubusercontent.com/3364637/101732995-0e881880-3af9-11eb-9a45-9ec5da9555ee.png)

![image](https://user-images.githubusercontent.com/3364637/101733006-13e56300-3af9-11eb-8424-e19366373293.png)

![image](https://user-images.githubusercontent.com/3364637/101733030-1a73da80-3af9-11eb-9fca-dc90be913c00.png)

**Comment by allkhor** [comment] 2020-12-10 07:22
Duplicate of https://github.com/godotengine/godot/issues/24207 ?

**Comment by snougo** [comment] 2020-12-10 07:39
I can confirm this issue on MacOS but my case is when scale is setted to < 0.9

**Comment by Calinou** [comment] 2023-07-21 01:08
- Duplicate of https://github.com/godotengine/godot/issues/24207 (same cause).

**Closed by Calinou** 2023-07-21 01:08 UTC
Labels: bug, topic:rendering, confirmed, topic:gui
