### ISSUE TITLE
Project Settings > Display > Window > Stretch > Scale only applies after second Play

### ISSUE THREAD

**Issue by hsandt** [godotengine/godot#67794] opened 2022-10-23 12:43 UTC
### Godot version

v4.0.beta.custom_build [767f8fb48]

### System information

Linux Ubuntu 20.04 with Unity desktop

### Issue description

In Project Settings, you can change Display > Window > Stretch > Scale, but it won't apply immediately on next Play (project or edited scene), unless you save the scene first. It will however apply on second Play since setting change, even without saving the scene.

### Steps to reproduce

1. In Project Settings, change Display > Window > Stretch > Scale to something very different like 8 (to make it easier to see if it was applied)
2. Play either edited scene or project (note that if you play project without a current scene set, they will prompt you to select one the first time, in this case the bug won't appear; but it will appear the other times)
Expected: game plays at new scale
Actual: game plays at old scale
3. Repeat 2, this time it will play at new scale
4. You can repeat 1-2 by toggling between scales 1 and 8 to be sure.

### Minimal reproduction project

[v4.0.beta.custom_build [767f8fb48] - Scale change is only applied on second Play.zip](https://github.com/godotengine/godot/files/9846581/v4.0.beta.custom_build.767f8fb48.-.Scale.change.is.only.applied.on.second.Play.zip)

**Comment by Calinou** [comment] 2022-10-23 17:31
Duplicate of https://github.com/godotengine/godot/issues/55145.

**Closed by Calinou** 2022-10-23 17:31 UTC
