### ISSUE TITLE
Image.load_ from_file() and texture.get_image() returned null when the image to be loaded is too large.

### ISSUE THREAD

**Issue by hylea** [godotengine/godot#79231] opened 2023-07-09 06:31 UTC
### Godot version

v4.1.stable.official [970459615]

### System information

Windows 10 -  v4.1.stable 

### Issue description

Image.load_ from_file() and texture.get_image() returned null when the image to be loaded is too large (e.g. 512x512, 1280*256, 2048 * 1028, etc.) . However, loading smaller images returns as expected (e.g. 1280 * 128,  2048*127, etc.).
![image](https://github.com/godotengine/godot/assets/70103541/25bc5488-7ece-4946-8aaf-99146787eb56)
![image](https://github.com/godotengine/godot/assets/70103541/5e229a15-0f61-4fd0-9894-d84fd1c7f76c)

### Steps to reproduce

	var img_a = Image.load_from_file("res://Images/img_1280x1024.png")  # null 
	var img_b = Image.load_from_file("res://Images/img_1280x256.png")   # null 
	var img_c = Image.load_from_file("res://Images/img_1280x128.png")   #OK 
	
	var texture_a:Texture2D        = load("res://Images/img_1280x1024.png")    #OK
	var img_of_texture_a: Image = texture_a.get_image()                 # null 
	var texture_b:Texture2D        = load("res://Images/img_1280x256.png")     #OK
	var img_of_texture_b: Image = texture_b.get_image()                 # null
	var texture_c:Texture2D         = load("res://Images/img_1280x128.png")     #OK
	var img_of_texture_c: Image  = texture_c.get_image()                 #OK

### Minimal reproduction project

[Project_image_load.zip](https://github.com/godotengine/godot/files/11994586/Project_image_load.zip)

**Comment by RedworkDE** [comment] 2023-07-09 08:06
See also https://github.com/godotengine/godot/issues/36801

Try to add `print(img_a)` etc to check if this is just a debugger issue or if the image is actually null.

**Comment by hylea** [comment] 2023-07-09 09:18
> See also #36801
> 
> Try to add `print(img_a)` etc to check if this is just a debugger issue or if the image is actually null.

Yes. The output of 'print (img_a)' is not null.
Now, what should I do to deal with the debugger issue ?

**Comment by AThousandShips** [comment] 2023-07-09 09:21
Then this is a duplicate of #36801

**Closed by AThousandShips** 2023-07-09 09:21 UTC
Labels: bug, topic:editor
