### ISSUE TITLE
Shape offset property of TileSet only affects one shape in a tile

### ISSUE THREAD

**Issue by AstroBoogie** [godotengine/godot#34880] opened 2020-01-07 02:57 UTC
**Godot version:**
3.1.2.stable.official

**OS/device including version:**
macOS 10.15.2

**Issue description:**
The **Shape Offset** property in **TileSet** only affects one of the created collision shapes.

**Steps to reproduce:**

Create a tile in a tileset with two or more collision shapes:
<img width="211" alt="Screen Shot 2020-01-06 at 6 45 57 PM" src="https://user-images.githubusercontent.com/18710598/71864787-ab566080-30b5-11ea-861a-a244d6cc0c0f.png">

Set the shape offset of the tile:
<img width="236" alt="Screen Shot 2020-01-06 at 6 42 57 PM" src="https://user-images.githubusercontent.com/18710598/71864782-a691ac80-30b5-11ea-882a-acdffde3b9b9.png">

Observe the collision offset in only the first collision shape. Below is a preview with rectangles where the collision shapes for a shape offset of (0, -128) on a 128x128 tile.
<img width="334" alt="Screen Shot 2020-01-06 at 6 44 17 PM" src="https://user-images.githubusercontent.com/18710598/71864863-f1132900-30b5-11ea-8f28-f89c7f85d484.png">

**Minimal reproduction project:**
[OffsetBug.zip](https://github.com/godotengine/godot/files/4028699/OffsetBug.zip)

**Comment by Kanabenki** [comment] 2020-01-07 09:24
It seems this bug has been fixed on master by #31050, but the fix is not yet merged in the 3.1 branch.

**Comment by akien-mga** [comment] 2020-01-07 09:33
Indeed, thanks for looking it up.

Closing as duplicate of #30994.

**Closed by akien-mga** 2020-01-07 09:33 UTC
Labels: bug, topic:editor
