### ISSUE TITLE
Game auto-kills itself after error breakpoint is reached, if an array contains itself

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#29088] opened 2019-05-21 21:22 UTC
Godot 3.1.1
Windows 10 64 bits

When debugging an app I was making with Godot, I made a mistake (calling a `contains` function which doesn't exists) which the debugger pointed me at when I run it. However, quickly after that, the app just closes. I think it's not supposed to do that, it looks like a silent crash.
The app doesn't close if I repro the same mistake straight in `_ready()`, so I posted a redux of my project with a case where it happens.

[GraphRelax_redux_debuggerCrash.zip](https://github.com/godotengine/godot/files/3204587/GraphRelax_redux_debuggerCrash.zip)
Just run the main scene.

Note: after I fix the mistake, the debugger no longer breaks, the game hangs and still quits with no info at all.
It looks like `fname`, a var supposed to contain a string, is getting corrupted, because if I just try to print it the game also crashes.

## Here is why:
```
				func_names.append(func_names)
```
Fortunately that app was small.

**Comment by riklauder** [comment] 2019-06-02 17:43
Running locally on 3.2, I get the following error in terminal:

CrashHandlerException: Program crashed
ERROR: NetSocketPosix::_get_socket_error: Socket error: 10054
   At: drivers\unix\net_socket_posix.cpp:197

Can confirm the graph.gd line 44 is where things stop. The var func_names is an empty array of size=0.  
What is the expected behaviour if trying to append a var of size=0? Should the Debugger provide a warning?

**Comment by Zylann** [comment] 2019-06-03 01:44
This happened because I mistakenly inserted an array inside itself, which in Godot will create a reference cycle, leaking memory. Even worse, since array comparison uses values inside it (instead of reference), it might hang forever if performed at any point.
This situation is something the debugger should be able to warn about, however this crashed the game with no possibility for the debugger to even show that.

As for the app, I mistakenly used the wrong variable.

**Comment by bojidar-bg** [comment] 2019-06-03 11:53
Duplicate of #1289?

**Comment by riklauder** [comment] 2019-06-03 15:57
It appears related to #1289. The same thing happens if the var array has data elements or if it's empty.
The self-reference triggers a kernel access violation in a dynamic process.  Thread synchronization breaks as data is locked causing current thread to exit.

**Comment by akien-mga** [comment] 2019-11-12 05:54
Closing as duplicate of #1289.

**Closed by akien-mga** 2019-11-12 05:54 UTC
Labels: bug, crash, topic:core
