### ISSUE TITLE
local update() function overriden by global update() function

### ISSUE THREAD

**Issue by p-r-i-s** [godotengine/godot#58745] opened 2022-03-04 12:25 UTC
### Godot version

4.0

### System information

Windows 10, GTX 980TI, Vulkan

### Issue description

I have a small program which displays debugging information to the user.

I have declared a local 'update()' method in my .gd file, which updates this information. 

in earlier versions of godot (3.4) this works.
in godot 4.0. instead of using my locally declared update() function, it is using the global update function.
this means that the menu won't be updated (as the wrong update() function is being called) and also that there is no visible error

### Steps to reproduce

- Make a gd file with a local update() method
- call that update() method
- 4.0 will instead use the global update() method instead of the locally declared one.

**Comment by Sauermann** [comment] 2022-03-04 13:20
This issue happens only for Nodes, that inherit from `CanvasItem`. This Class defines its own [udpate()](https://docs.godotengine.org/en/latest/classes/class_canvasitem.html?highlight=CanvasItem#class-canvasitem-method-update) function. Same happens with other class-defined functions like `set_visible()`.

Simplest solution would be to rename your update() function to something else, so that it doesn't clash with the version of `CanvasItem`.

A different way to look at this problem is, that GDScript doesn't print a warning, that the function can not be overridden.

**Comment by Calinou** [comment] 2022-03-04 18:49
Duplicate of https://github.com/godotengine/godot/issues/55024.

**Closed by Calinou** 2022-03-04 18:49 UTC
