### ISSUE TITLE
Software Skinning doesn't work when using a Polygon2D with Antialiasing enabled.

### ISSUE THREAD

**Issue by Syntaxxor** [godotengine/godot#46466] opened 2021-02-27 03:14 UTC
**Godot version:**

3.2.4.rc3

**OS/device including version:**

Windows 10 PC with RTX 2060, using the most recent NVidia Game Ready drivers and the GLES3 backend.

**Issue description:**

When Software Skinning is enabled in the Project Settings, a Polygon2D doesn't deform to a skeleton if Antialiasing is enabled on that polygon. If it is disabled, skinning works as expected.

**Steps to reproduce:**
Create a Polygon2D and a Skeleton2D with some bones. Go through the usual process of attaching the Polygon2D to the Skeleton2D. Note that a texture is required to do so. Move around the bones to ensure that skinning is working. Then, enable Antialiasing on the Polygon2D and move the bones again. It will not work. This only occurs when Software Skinning is enabled in the Project Settings, which is the default condition.

**Minimal reproduction project:**

[Polygon2DSkinning.zip](https://github.com/godotengine/godot/files/6053644/Polygon2DSkinning.zip)

Possibly related to https://github.com/godotengine/godot/issues/46465?

**Comment by lawnjelly** [comment] 2021-02-27 08:24
I'll take a look.

It is probably occurring because when you use anti-aliasing, it can't draw the polygon using batching (it uses legacy method), and having 2d skinning switched on may override the sending the bones to the shader. I'll see if this can be worked around.

**Comment by lawnjelly** [comment] 2021-02-27 09:11
Some options:
1) Implement complex workaround
2) Disable software skinning entirely when an anti-aliased poly is used (overly limiting and confusing)
3) Disallow anti-aliasing in skinned polys when software skinning is on
4) Put in a warning / error message, and put a note in the docs

Looking at the code, I suspect this will be overly complex and bug prone to step back to the complete legacy path (with bones) when you use anti-aliased poly with skinning - it is somewhat of a chicken and egg solution. You don't discover the problem until it is too late in the code.

Suffice is to say a workaround would be *difficult* - I don't think the upsides (bugs, convoluted logic, code maintenance) outweigh the downsides (slightly easier for user).

So I'm tending towards 3 or 4, possibly 4. (3) would be seamless, although we will get people complaining that anti-aliasing isn't working, even if it is in the docs. And considering that software skinning is the default, this is highly likely to generate support issues (which we don't want).

If we go for (4), it should be pretty obvious that skinning isn't working in such a situation, and with an error message, detailing the problem and the solution (switch to hardware skinning, or don't use anti-aliasing on skinned polys) this should reduce support issues, so people know it is expected behaviour.

Anyone interested let us know any thoughts on this, I'll wait for any feedback before making PR.

**Comment by akien-mga** [comment] 2021-03-01 09:21
Fixed by #46520.

**Closed by akien-mga** 2021-03-01 09:21 UTC
Labels: bug, discussion, topic:rendering
