### ISSUE TITLE
It is not possible to add/read files named by non-ASCII characters using ZIPPackage and ZIPReader

### ISSUE THREAD

**Issue by Yanxiyimengya** [godotengine/godot#85676] opened 2023-12-02 17:45 UTC
### Godot version

4.2 stable

### System information

Godot v4.2.stable - Windows 10.0.19045 - GLES3 (Compatibility) - AMD Radeon(TM) Graphics (Advanced Micro Devices, Inc.; 30.0.13014.10001) - AMD Ryzen 5 5500U with Radeon Graphics (12 Threads)

### Issue description

version : Godot 4.2

When debugging the code, when using ZIPPacker to create a compressed package, I couldn't successfully write any non-ASCII characters as the file name, he would sometimes output garbled characters, and sometimes he wouldn't even write the file properly.
And most of the time, he just outputs garbled characters, and it is incorrect to check the compressed file name in the Windows compression manager interface.
However, the same file can be read with the same name in the code.
There are times when I use ZIPReader to unzip a file named with non-ASCII characters, I also get an error:
```
Unicode parsing error, some characters were replaced with � (U+FFFD): Invalid UTF-8 leading byte (b2)
`Unicode parsing error, some characters were replaced with � (U+FFFD): Invalid UTF-8 continuation byte (e3 ... c2 ...)`
```

### Steps to reproduce

code:
```
var path: String = "res://test.zip";
func _ready():
	var writer = ZIPPacker.new();
	var err = writer.open(path);
	if (err != OK) :
		print("ERROR!");
	writer.start_file("你好Godot.txt");
	writer.write_file("Hello World!".to_utf8_buffer());
	writer.close_file();
	# ...
	writer.close();
```

After running, the file name becomes garbled characters: "浣犲ソGodot.txt";
The ASCLL section is not affected

### Minimal reproduction project

[Test.zip](https://github.com/godotengine/godot/files/13536959/Test.zip)

**Comment by bitsawer** [comment] 2023-12-02 17:53
Possibly a duplicate of https://github.com/godotengine/godot/issues/78726, could also be fixed by https://github.com/godotengine/godot/pull/78732.

**Comment by Yanxiyimengya** [comment] 2023-12-02 18:16
> 可能是 #78726 的副本，也可以通过 #78732 修复。

This one seems to just fix the issue of ZIPReader reading files, I didn't see any fixes there for zipping files.

**Comment by jsjtxietian** [comment] 2023-12-10 12:12
Tested on master that it  looks lile the bug is fixed by https://github.com/godotengine/godot/pull/78732.

**Closed** 2023-12-10 13:00 UTC
Labels: bug, topic:core
