### ISSUE TITLE
Exporting for Iphone

### ISSUE THREAD

**Issue by nemesis567** [godotengine/godot#30724] opened 2019-07-21 03:50 UTC
**Godot version:**
3.1 stable

**Steps to reproduce:**
Set project name with spaces, export to iOS and pbxproj file will be corrupted. You will need to manually fix by enclosing quotes in your project name in several places where it appears.

I used the tool kin to diagnose these problems.

**Comment by Calinou** [comment] 2019-07-21 12:31
Duplicate of #25128.

**Closed by Calinou** 2019-07-21 12:31 UTC
Labels: bug, platform:ios, topic:editor
