### ISSUE TITLE
Parallax2D is missing when Repeat Times is bigger then 1

### ISSUE THREAD

**Issue by roydbt** [godotengine/godot#93204] opened 2024-06-15 18:20 UTC
### Tested versions

- Reproducible in: v4.3.beta1.official [a4f2ea91a]

### System information

Godot v4.3.beta1 - macOS 14.5.0 - Vulkan (Mobile) - integrated Apple M1 - Apple M1 (8 Threads)

### Issue description

My background is smaller than my viewport, so I thought that increasing the "Repeat Times" field in my Parallax2D node would solve the issue. Instead, I can no longer see the background at all.

### Steps to reproduce

1. Download the MRP
2. Run the project, and see that everything works
3. Increase the "Repeat Times" field to 2
4. Run the project again and see that the background is missing

### Minimal reproduction project (MRP)

[MRP.zip](https://github.com/user-attachments/files/15849350/MRP.zip)

**Comment by markdibarry** [comment] 2024-06-15 19:11
Thanks for the report! This is a duplicate of #92705. Luckily, this was fixed recently in https://github.com/godotengine/godot/pull/92763, so the fix will be in the next beta release.

Also, while `repeat_times` will solve the issue, it usually better and more flexible to prepare your backgrounds for your viewport by using the sprite region and repeat flags. `repeat_times` best use is for when you have a background that already is set up to fit your viewport, but you plan to zoom out at certain points. Good luck, and have fun!

**Comment by kleonc** [comment] 2024-06-15 19:20
Closing as duplicate of #92705 per the comment above.

**Closed by kleonc** 2024-06-15 19:20 UTC
Labels: bug, topic:2d
