### ISSUE TITLE
there will be a gap between up hexagon and down hexagon

### ISSUE THREAD

**Issue by newjbl** [godotengine/godot#74363] opened 2023-03-04 15:30 UTC
### Godot version

4.0 stable

### System information

windows 10

### Issue description

for godot 4.0 stable version. when i use tilemap and set tile shape as half-offset , and the tileset is a hexagon.
the tileset picture is 120140, so i set this size in the tileset.
and set the tilemap size as 120105, i caculate it and sure this is a right size.
![image](https://user-images.githubusercontent.com/30258466/222914723-262ee7b2-0acf-4e40-a32f-6d6c729ab43a.png)

but after running the game, there will be a gap between up hexagon and down hexagon. there is no gap between left hexagon and right hexagon.
![image](https://user-images.githubusercontent.com/30258466/222914716-e6cc32e6-e85a-4b98-9c31-6eaedb670c32.png)

i also try to use the tilemap set the tile shape as hexagon, but the issue still happend.

### Steps to reproduce

use tilemap and set tile shape as half-offset , and the tileset is a hexagon.
the tileset picture is 120140, so i set this size in the tileset.

### Minimal reproduction project

no

**Comment by kleonc** [comment] 2023-03-15 17:41
Looks like a duplicate of #62911 to me. Can't test as there's no minimal reproduction project provided.

@newjbl Can you test if #74814 fixes this for you? To do so you can download artifact from its CI actions ([here's a one for Windows](https://github.com/godotengine/godot/suites/11507692029/artifacts/594848893)).

**Closed** 2023-03-15 18:04 UTC
Labels: archived, topic:core, topic:2d
