### ISSUE TITLE
Wrong input_event position on CollisionObject when 3D Scaling

### ISSUE THREAD

**Issue by Whimfoome** [godotengine/godot#50558] opened 2021-07-17 14:37 UTC
### Godot version

3.3.2-stable

### System information

Windows 10

### Issue description

I use 3D scaling from the official godot demos for my mobile game.
I connect `input_event` of any CollisionObject signal to a script and do what I do.

Because of the scaling, there is something like offset. I need to click next to the collision place to detect the input, not on it.

I created a very simple reproduction project - try it and see for yourselves.

EDIT: forgot to tell, it work's the way it is expected when using ViewportContainer's Stretch Shrink parameter for 3D scaling, it's not good enough, because the scaling value is integer and not float (ex: a 1280x720 viewport with stretch_shrink set to 2 will be rendered at 640x360, there isn't something like 1.25)

![image](https://user-images.githubusercontent.com/42871796/126040393-96ad8d8d-d01f-4f51-a8de-f2404ad32062.png)

### Steps to reproduce

1. Implement the 3D scaling method from the official demo project.
2. Create any CollisionObject (StaticBody or Area) and connect `input_event` to a script.
3. When you try to click on the collision, it won't do anything when ViewportContainer is Stretched, because it's offsetted.

### Minimal reproduction project

[CollisionObject input_event scaling.zip](https://github.com/godotengine/godot/files/6834858/CollisionObject.input_event.scaling.zip)

**Comment by Calinou** [comment] 2021-07-17 16:55
Duplicate of https://github.com/godotengine/godot/issues/44915.

**Closed by Calinou** 2021-07-17 16:55 UTC

**Comment by Whimfoome** [comment] 2021-07-17 17:29
For anyone who doesn't know how to manipulate the mouse coordinates in a viewport, I decided to share at least how I did it:

1. Add script to the Viewport Node
2. You should manipulate it in the `_unhandled_input`

Here is how it should look:
```gdscript
extends Viewport

var scale_factor := 0.75

func _unhandled_input(event):
	if event is InputEventMouseButton:
		event.position = event.position * scale_factor
```
