### ISSUE TITLE
EditorImportPlugin throws errors when moving imported file that's saved as a custom resource.

### ISSUE THREAD

**Issue by Atlinx** [godotengine/godot#51816] opened 2021-08-17 23:25 UTC
### Godot version

3.3.2.stable.mono.official

### System information

Windows 10

### Issue description

Custom EditorImportPlugins throw errors when moving the imported file, saved as a custom resource, into another location.
Note that the resource seems to get saved correctly but a few errors are thrown.

```GDScript
# import_plugin.gd
tool
extends EditorImportPlugin

...

func import(source_file, save_path, options, r_platform_variants, r_gen_files):
	var file = File.new()
	var err = file.open(source_file, File.READ)
	if err != OK:
		return err

	var res = CustomResource.new()

	file.close()
	
	return ResourceSaver.save("%s.%s" % [save_path, get_save_extension()], res)
```

```GDScript
# custom_resource.gd
class_name CustomResource
extends Resource
```

### Steps to reproduce

1. Open up the reproduction project
2. Drag the `.txt` file into another folder.
3. Watch the editor print the error:
```
editor/editor_file_system.cpp:1782 - BUG: File queued for import, but can't be imported!
editor/editor_file_system.cpp:1783 - Method failed.
Another resource is loaded from path 'res://addons/plugin/custom_resource.gd' (possible cyclic resource inclusion).
```

### Minimal reproduction project

[ImportPluginBroken.zip](https://github.com/godotengine/godot/files/7003498/ImportPluginBroken.zip)

**Comment by cgbeutler** [comment] 2022-03-23 05:54
Possible duplicate of https://github.com/godotengine/godot/issues/46288
Not sure, though.

**Closed** 2022-11-30 14:00 UTC
Labels: bug, topic:plugin, topic:import
