### ISSUE TITLE
Godot 4: Wrong arguments help on method with the same name as built-ins

### ISSUE THREAD

**Issue by gustavi** [godotengine/godot#58202] opened 2022-02-16 18:30 UTC
### Godot version

v4.0.alpha2.official [79077e6c1]

### System information

Windows 10 64bit - Vulkan API 1.2.141 - GeForce GTX 1660 SUPER

### Issue description

When you write the `Vector2.snapped()` method you have the arguments help displayed for built-in `snapped()` method. All class are affected (you can reproduce it on `Array.min()` for example).

Only Godot 4 is affected (I can't reproduce it in 3.4.2). I found it on early 4.0 builds (20201027 for example).

![image](https://user-images.githubusercontent.com/2736557/154329315-dbc3add6-93db-4d18-a770-8ebf2717601e.png)

### Steps to reproduce

```gdscript
func _ready():
    var foo := Vector2(0, 0).snapped(...)
```

Note: you must write the line (the help is not displayed when you copy-paste the code)

### Minimal reproduction project

See **Steps to reproduce** section.

**Comment by akien-mga** [comment] 2022-08-10 10:31
Duplicate of #58403

**Closed by akien-mga** 2022-08-10 10:31 UTC
Labels: bug, topic:gdscript, topic:editor, regression
