### ISSUE TITLE
Importing (or reimporting) translation

### ISSUE THREAD

**Issue by draxdeveloper** [godotengine/godot#7819] opened 2017-02-15 21:25 UTC
**Operating system or device - Godot version:**
Ubuntu with steam, stable version

**Issue description:**
Every time that i try to import or re-import a translation godot force closes, don't even emits a message  

**Steps to reproduce:**
Try to import or re-import a translation

**Link to minimal example project:**
https://github.com/divesys/aEstradaAto1.git
Maybe i will need to comit WITH the error, but i will wait

**Comment by akien-mga** [comment] 2017-02-15 21:27
Duplicate of #7630.

**Closed by akien-mga** 2017-02-15 21:27 UTC
