### ISSUE TITLE
Mouse button input events not picked up consistently on macOS. Mono version

### ISSUE THREAD

**Issue by LordBrkica** [godotengine/godot#55156] opened 2021-11-20 12:49 UTC
Related to: https://github.com/godotengine/godot/issues/54458#issue-1040539866

I am encountering this issue on mac OS Monterey 12.0.1. Godot version is **3.4 stable mono.**
Device is mac mini i3 2018, with UHD 630 GPU.

Bug occurs sporadically, 1 out of 10 times when I start the game the bug will occur. 
When it occurs, its immediately obvious as my game starting UI elements (buttons) are also affected.

The Bug I would describe most simply as follows: 
- one normal left mouse click seems to be ignored/missed, one needs to double click and this is then registered as one normal click

GLES2/3 options are affected equally, and its not specific to one control type (e.g. Button) but seems to affect all controls equally.

Bug seems to go away after some time (window switching and window minimizing/ maximizing maybe helps).

If I understood correctly, this bug should have been solved in 3.4 but for me its still there. Could it be that only Mono version is still affected ?

P.S EDIT:
I just noticed one curiosity which might help someone. 

I have a sort of scenario editor at game beginning, an `ItemList` where one can select one scenarioName `string`. 

When starting the game where there is NO bug, the first item in the list is automatically selected/focused. 
When starting the game where the bug IS present, the first item in the list is NOT selected/focused.

**Comment by Calinou** [comment] 2021-11-20 15:28
> Could it be that only Mono version is still affected ?

No, as the input handling code is exactly the same between non-Mono and Mono versions.

**Comment by bruvzg** [comment] 2021-11-23 08:43
> when I start the game

Starting project from the editor, from terminal or starting the exported app?

> Related to: #54458 (comment)

When the bug happens, are window title text and close, minimize and full-screen buttons normal (bright text and colored buttons) or gray?

**Comment by sirgwain** [comment] 2021-11-23 22:03
I start mine from the terminal, always. It happens both in the editor and in my launched game. 3.4 Mono, macOS Monterey 12.0.1.

It's very sporadic.

**Comment by LordBrkica** [comment] 2021-11-26 17:35
> 

Sometimes I start from Terminal/Visual Studio Code F5, sometimes from Godot editor, it doesnt seem to make a difference.

**Comment by samdze** [comment] 2021-12-11 20:50
Don't know if related, but when I try to click to focus the Godot editor window on macOS (MacBook Pro M1 Max, Monterey 12.0.1) there's a delay of at least 1 or 2 seconds before it actually gets focused, very annoying.

It seems to be dependant on how complex the scene in the window I'm focusing is, with a simple running game I get less delay, but still noticeable if I try to drag the window at the same time.
I'm starting Godot normally, not from the terminal.

When I alt+tab to set the focused window (instead of clicking) I get less delay, but it's still there.

**Comment by Calinou** [comment] 2021-12-11 21:07
> Don't know if related, but when I try to click to focus the Godot editor window on macOS (MacBook Pro M1 Max, Monterey 12.0.1) there's a delay of at least 1 or 2 seconds before it actually gets focused, very annoying.

- Can you reproduce this if you enable **Update Continuously** in the Editor Settings?
- Can you reproduce this if you set **Unfocused Low Processor Mode Sleep Usec** to `6900` in the Editor settings (while **Update Continuously** is disabled)?

**Comment by sirgwain** [comment] 2021-12-11 21:54
> Can you reproduce this if you enable Update Continuously in the Editor Settings?

After setting Update Continuously to enabled, the issue still happens.

**Comment by sirgwain** [comment] 2021-12-11 21:56
> Can you reproduce this if you set Unfocused Low Processor Mode Sleep Usec to 6900 in the Editor settings (while Update Continuously is disabled)?

After Disabling Update Continuously and then setting Unfocused Low Processor Mode Sleep Usec to `6900`, the issue also still happens.

**Comment by samdze** [comment] 2021-12-11 22:00
> Can you reproduce this if you enable Update Continuously in the Editor Settings?
Can you reproduce this if you set Unfocused Low Processor Mode Sleep Usec to 6900 in the Editor settings (while Update Continuously is disabled)?

Ok, either way the issue doesn't appear anymore, or it's quite mitigated.

**Comment by sirgwain** [comment] 2021-12-11 22:01
Well that's interesting. I always launch godot from a terminal (`godot-mono -e .`) in order to see output logs. If I launch it from spotlight and open my project from there, I couldn't reproduce the issue when I tried closing and re-opening godot 5 times.

**Comment by sirgwain** [comment] 2021-12-11 22:02
> 

Oh I'm sorry, I was responding to the original issue, not this alt-tab issue. I'll delete my comments.

**Comment by LordBrkica** [comment] 2021-12-12 10:24
>     * Can you reproduce this if you enable **Update Continuously** in the Editor Settings?
> 
>     * Can you reproduce this if you set **Unfocused Low Processor Mode Sleep Usec** to `6900` in the Editor settings (while **Update Continuously** is disabled) ?

I tried these 2 tips and they don't prevent the problem. 

The bug I can spot upon starting my game by looking at the window icons:
![image](https://user-images.githubusercontent.com/51578785/145708493-88fed5a8-8cc0-4458-a3df-7dabb98798a8.png)

If these 3 icons are greyed out (like in the screenshoot) it means left click mouse input will fail to be detected.

Interestingly, I could NOT get this bug to appear when starting the game directly from Godot editor. 
Also, starting the game from godot editor and then starting it from terminal VSC seems to mitigates the problems.

So the bug appears most often when you dont start the game from editor at all.

**Closed** 2022-01-12 10:37 UTC
Labels: bug, platform:macos, needs testing, topic:input
