### ISSUE TITLE
Cannot open directory when importing project

### ISSUE THREAD

**Issue by MrMinimal** [godotengine/godot#60131] opened 2022-04-11 05:58 UTC
![grafik](https://user-images.githubusercontent.com/8739690/162674038-52b533ee-0ad0-4be9-b23f-678adbbae132.png)

### Godot version

4.0.alpha6

### System information

Windows 10

### Issue description

Directory shows up as file when browsing, cannot be entered by clicking to select godot.project within.
Workaround of adding the directory name to the path works though.
See video.
https://user-images.githubusercontent.com/8739690/162673120-1eef6584-e146-42d5-8a38-a250c8609bef.mp4

### Steps to reproduce

See video

### Minimal reproduction project

[godot-4-graphics-demo.zip](https://github.com/godotengine/godot/files/8461395/godot-4-graphics-demo.zip)

**Comment by MrMinimal** [comment] 2022-04-11 10:40
@BeayemX I don't think this is the same issue, as I can see the directory but it's shown as a normal file, not a directory.

**Comment by akien-mga** [comment] 2022-04-13 08:57
This is indeed a duplicate of #59578, fixed by #59962.

**Closed by akien-mga** 2022-04-13 08:57 UTC
Labels: bug, confirmed, regression, topic:gui
