### ISSUE TITLE
Make Toggle Comment respect indentation level in the Script Editor

### ISSUE THREAD

**Issue by PLyczkowski** [godotengine/godot#22177] opened 2018-09-17 09:28 UTC
Currently Toggle Comment inserts # symbols at the beginning of the line. If it would insert it at the lowest indentation level of the selected text, it would work better with code folding (code would fold with commented parts at the end of it). For a working example check out VSCode, there it's on by default.

**Comment by hsandt** [comment] 2019-01-23 00:03
I have a bug report related to this, and I think the bug would be fixed by this enhancement. I will write the bug report below to start with. If the other developers consider it should be handled independently (e.g. because bugs have higher priority and should be flagged as such), then I will file a separate bug report.

---

## Toggle comment does not remove # sign after indent in GD Script editor

**Godot version:**
v3.0.6 linux

**Issue description:**
The Toggle comment action in the GD Script editor (Ctrl+K by default) will not detect a `#` sign after a space or tab indent in GD script


**Steps to reproduce:**
Type this in the Script editor (mind the tabs, the most simple is to use the default script template):

			# Called me logic here.

Then try to toggle comment on it. (Ctrl+K by default)

_Result_

	#		# Called me logic here.

_Expected_

			Called me logic here

---

If we add `#` at the correct indentation level when commenting, we will probably also be checking the existence of a `#` at this level, which would allow to uncomment the line, effectively fixing the bug.

**Comment by hsandt** [comment] 2019-01-29 22:34
Located responsible code:

```
ScriptTextEditor::_edit_option
	case EDIT_TOGGLE_COMMENT:
		# fix here
```
Trying to fix on my branch.

**Comment by golddotasksquestions** [comment] 2019-10-07 15:01
@hsandt 
I don't have a problem with what you are describing. Actually I use this feature a lot to have different ways to comment out stuff:
If I want to comment out a whole block of code I use Ctrl+K, but if I just want to deactivate a single line in a block of code I just place a single # at the indentation level where my code starts. That's also a clear indicater for me for something like "I'm not so sure about this line" vs "I don't need this block of code right now". This makes the whole code a lot more readable imho, and very clear which code I just have "parked" in Ctrl+K hiding and which lines I'm currently working at this moment.

I also sometimes comment a line after the code to make a note. Your proposed fix would make this impossible too I suppose.

So I'd rather if Crtl+K would not remove all my indented comments as well but keep doing his thing just at the beginning of the line.

**Comment by hsandt** [comment] 2020-04-22 16:54
@golddotasksquestions You tackle an interesting point. Adding a proper comment in code vs commenting out code temporarily for testing.

Note that most of your concerns are actually related to adding indented comment symbols, as suggested by the OP. My post was dealing with actually removing comment symbols. And if all your comment symbols at are the beginning of the line, finding them is easy and it's unlikely that you will remove the wrong (indented) comment symbols. Anyway, I'll tackle both adding and removing comments.

Here are a few behaviours I found in editors:

* Behaviour A: Add and remove at beginning of line (current Godot Behaviour)
* Behaviour B: Add at maximum common indentation (skip empty lines), remove at any (Sublime Text, Atom, VS Code)
* Behaviour C: Add at beginning of line (except if all lines are empty), remove at any (Jetbrains)

In addition, all of them use line group detection to decide to add or remove comments (I found one IDE that toggled comments *individually* on lines one day, but it's very rare). If a single line is not commented (checking beginning of line or any indented comment symbol, depending on Behaviour), then all the lines get an extra comment symbol.

In the examples below I distinguish true comments, line of code being part of true comments (e.g. alternatives) and disabled lines of code.

**Behavior A: Add and remove at beginning of line**

```gdscript
func _ready():
	# True comment. We could also do this:
	# store_initial_size(OS.window_size)
	initial_size = OS.window_size

	# code disabled manually
	#a = 1
	#b = 2

	if not OS.window_fullscreen:
		if OS.has_feature("standalone"):
			# disabled line of code
#			print("Enabling fullscreen")
			call_deferred("toggle_fullscreen")
```

Single line:

```gdscript
func _ready():
	# True comment. We could also do this:
#	# store_initial_size(OS.window_size)         # <-- TOGGLED: ON again!
	initial_size = OS.window_size
#                                                    # <-- TOGGLED: ON
	# code disabled manually
#	#a = 1                                       # <-- TOGGLED: ON again!
	#b = 2

	if not OS.window_fullscreen:
#		if OS.has_feature("standalone"):     # <-- TOGGLED: ON
			# disabled line of code
			print("Enabling fullscreen") # <-- TOGGLED: OFF
			call_deferred("toggle_fullscreen")
```

Indented block:

```gdscript
func _ready():
	# True comment. We could also do this:
	# store_initial_size(OS.window_size)
	initial_size = OS.window_size

	# code disabled manually
#	#a = 1                                             # <-- BLOCK 1 START
#	#b = 2                                             # <-- BLOCK 1 END

#	if not OS.window_fullscreen:                       # <-- BLOCK 2 START
#		if OS.has_feature("standalone"):
#			# disabled line of code
##			print("Enabling fullscreen")
#			call_deferred("toggle_fullscreen") # <-- BLOCK 2 END
```

Full:

```gdscript
#func _ready():
#	# True comment. We could also do this:
#	# store_initial_size(OS.window_size)
#	initial_size = OS.window_size
#
#	# code disabled manually
#	#a = 1
#	#b = 2
#
#	if not OS.window_fullscreen:
#		if OS.has_feature("standalone"):
#			# disabled line of code
##			print("Enabling fullscreen")
#			call_deferred("toggle_fullscreen")
```

The comment symbol at the start of each line is something you wouldn't type while coding, and gives a feel of "disabling code temporarily to debug". As you said, it's easy to spot and doesn't mix up with existing "true" comments.

However, if the user happened to disable some lines of code manually, toggle comment will not detect that and just add another layer of comments (`TOGGLED: ON again!`). So the user must consistently use the Toggle Comment command. This is precisely what my post was about. And it can be fixed without changing the Comment behavior, only the Uncomment context detection (see Behavior C).

In addition, this behavior doesn't help starting a true comment, user must enter comment symbol manually (fortunately it's just `#` but in C# it would be `//`). In general, users do not enter a text comment then Toggle Comment (if you type a normal sentence outside a comment, chances are you'll be spammed with snippet suggestions on words like `do` and `for`; and you'll get funky syntax coloring). However, sometimes I instinctively press Toggle Comment *before* writing a comment, just to insert the comment symbol.

**Behavior B: Add at maximum common indentation (skip empty lines), remove at any**

Since indented every comment symbol individually for each line makes it hard to spot a "comment layer" at a glance, editors using indented comments generally pick the maximum common indent level among all selected lines. In the examples below, the disabled line of code does not have the `#` at the beginning of the line anymore, because it would mess up with the block comment (as the maximum indent level would be 0). On a single line, it would correctly be removed, though.

```gdscript
func _ready():
	# True comment. We could also do this:
	# store_initial_size(OS.window_size)
	initial_size = OS.window_size

	# code disabled manually
	#a = 1
	#b = 2

	if not OS.window_fullscreen:
		if OS.has_feature("standalone"):
			# disabled line of code
			# print("Enabling fullscreen")
			call_deferred("toggle_fullscreen")
```

Single line:

```gdscript
func _ready():
	# True comment. We could also do this:
	store_initial_size(OS.window_size)           # <-- TOGGLED: OFF
	initial_size = OS.window_size
	#                                            # <-- TOGGLED: ON
	# code disabled manually
	a = 1                                        # <-- TOGGLED: OFF
	#b = 2

	if not OS.window_fullscreen:
		# if OS.has_feature("standalone"):   # <-- TOGGLED: ON
			# disabled line of code
			print("Enabling fullscreen") # <-- TOGGLED: OFF
			call_deferred("toggle_fullscreen")
```

Indented block:

```gdscript
func _ready():
	# True comment. We could also do this:
	# store_initial_size(OS.window_size)
	initial_size = OS.window_size

	# code disabled manually
	a = 1                                              # <-- BLOCK 1 START
	b = 2                                              # <-- BLOCK 1 END

	# if not OS.window_fullscreen:                     # <-- BLOCK 2 START
	#	if OS.has_feature("standalone"):
	#		# disabled line of code
	#		# print("Enabling fullscreen")
	#		call_deferred("toggle_fullscreen") # <-- BLOCK 2 END
```

Full:

```gdscript
#func _ready():
#	# True comment. We could also do this:
#	# store_initial_size(OS.window_size)
#	initial_size = OS.window_size

#	# code disabled manually
#	#a = 1
#	#b = 2

#	if not OS.window_fullscreen:
#		if OS.has_feature("standalone"):
#			# disabled line of code
#			# print("Enabling fullscreen")
#			call_deferred("toggle_fullscreen")
```

I'd say it cover most cases, and as long as you disable a block of code that has enough indentations itself, it's easy to spot what parts of the code have been disabled to reenabled them.

As a bonus, if you Toggle Comment on an empty indented line, it adds the comment symbol indented, so you can start writing a true comment.

To identify two of the issues you mentioned, we need to try to comment different indented blocks.

> If I would then have to go in and start finding and commenting out those single lines again only because I have Ctrl+K the block, it would drive me nuts.

```gdscript
func _ready():
	# True comment. We could also do this:
	# store_initial_size(OS.window_size)
	initial_size = OS.window_size

	# code disabled manually
	#a = 1
	#b = 2

	if not OS.window_fullscreen:
		if OS.has_feature("standalone"):
			# # disabled line of code            # <-- BLOCK START
			# # print("Enabling fullscreen")
			# call_deferred("toggle_fullscreen") # <-- BLOCK END
```

The `# #` is harder to spot than the well-spaced comment symbols in Behaviour A. That's a point.

> I'd rather if Crtl+K would not remove all my indented comments as well

```gdscript
func _ready():
	# True comment. We could also do this:
	# store_initial_size(OS.window_size)
	initial_size = OS.window_size

	# code disabled manually
	#a = 1
	#b = 2

	if not OS.window_fullscreen:
		if OS.has_feature("standalone"):
			disabled line of code          # <-- BLOCK START
			print("Enabling fullscreen")   # <-- BLOCK END
			call_deferred("toggle_fullscreen") 
```

Oops, we wanted to disable 2 lines of code but ended up enabling them and worse, enabling a non-line of code so it won't even parse!

But thinking back, why would we try to disable lines that are already commented in the first place? Surely this will only happen if we mechanically press keys without really reading the code. And if we really want to do that, the best is to have some "Force Comment Line" command that always add a comment symbol, like Visual Studio. And maybe a "Force Uncomment Line" to massively reenable disabled code through a file, even if some lines are still active. But that would only be effective when placing `#` at the beginning of the line to identify disabled lines of code, anyway (Behavior A or C).

So, this is not really a problem if you always comment blocks with at least one enabled line of code.

**Behaviour C: Add at beginning of line (except if empty), remove at any**

```gdscript
func _ready():
	# True comment. We could also do this:
	# store_initial_size(OS.window_size)
	initial_size = OS.window_size

	# code disabled manually
	#a = 1
	#b = 2

	if not OS.window_fullscreen:
		if OS.has_feature("standalone"):
			# disabled line of code
#			print("Enabling fullscreen")
			call_deferred("toggle_fullscreen")
```

Single line:

```gdscript
func _ready():
	# True comment. We could also do this:
	store_initial_size(OS.window_size)           # <-- TOGGLED: OFF
	initial_size = OS.window_size
                                                     # <-- TOGGLED: nothing
	# code disabled manually
	a = 1                                        # <-- TOGGLED: OFF
	#b = 2

	if not OS.window_fullscreen:
#		if OS.has_feature("standalone"):     # <-- TOGGLED: ON
			# disabled line of code
			print("Enabling fullscreen") # <-- TOGGLED: OFF
			call_deferred("toggle_fullscreen")
```

Indented block:

```gdscript
func _ready():
	# True comment. We could also do this:
	# store_initial_size(OS.window_size)
	initial_size = OS.window_size

	# code disabled manually
	a = 1                                              # <-- BLOCK 1 START
	b = 2                                              # <-- BLOCK 1 END

#	if not OS.window_fullscreen:                       # <-- BLOCK 2 START
#		if OS.has_feature("standalone"):
#			# disabled line of code
##			print("Enabling fullscreen")
#			call_deferred("toggle_fullscreen") # <-- BLOCK 2 END
```

Full:

```gdscript
#func _ready():
#	# True comment. We could also do this:
#	# store_initial_size(OS.window_size)
#	initial_size = OS.window_size
#
#	# code disabled manually
#	#a = 1
#	#b = 2
#
#	if not OS.window_fullscreen:
#		if OS.has_feature("standalone"):
#			# disabled line of code
##			print("Enabling fullscreen")
#			call_deferred("toggle_fullscreen")
```

This would satisfy the need for clear disabled code, and my need for removing existing comments wherever the comment symbol is, but not the OP's request.

Now to address your remaining concerns:

> If I want to comment out a whole block of code I use Ctrl+K, but if I just want to deactivate a single line in a block of code I often just place a single # at the indentation level where my code starts.

> What also becomes possible this way is to comment out a single line, then comment out the whole codeblock (like a whole function) with Ctrl+K and then when reactivating the codeblock/function to still have your commented out line at the place it was before.

All Behaviors handle this. It's interesting that you mention adding a single `#` manually at the indentation level, because that's exactly what Behavior B does, yet you mentioned you preferred Behavior A because you can find lines actually disabled later.

If you use Behavior A or C, and comment a line then a block containing this line, it will simply place one `#` at the start, then when toggling comment on the whole block, it will add a second one: `##`. When you uncomment the block later, you still have your `#` and it's readable.

Considering your case of use though, I'd say it's more important to place `#` at the beginning of the line for a single line (harder to spot) than for blocks. 

To get the best of both worlds I see a few solutions:

- Add Editor Setting to decide if adding comments before or after indent. Comment symbols would always be removed wherever they are (as I explained it should be safe in Behavior B).
- Make a second command Toggle Indented Comment, that can be assigned to a different shortcut. The original Toggle Comment may detect Indented comment for removal, or not (but again, always removing them as long as only commented lines are selected should be safe).

**Comment by Paulb23** [comment] 2021-09-04 11:15
Closing in favour of godotengine/godot-proposals/issues/110

**Closed by Paulb23** 2021-09-04 11:15 UTC
Labels: enhancement, topic:editor
