### ISSUE TITLE
Search Help pages, selecting link text opens the link

### ISSUE THREAD

**Issue by duianto** [godotengine/godot#61119] opened 2022-05-17 14:24 UTC
### Godot version

v3.5.beta5.official [815f7fe63], and v3.4.4.stable.official [419e713a2]

### System information

Windows 10

### Issue description

When selecting text on a documentation page.
For example: `Help > Search Help` (F1), `Reference`

Releasing the left mouse button on a link, opens the link.

The link should not open while selecting text.

### Steps to reproduce

- Open the Search Help window: `Help > Search Help` (F1)
- Open the `Reference` page (the fifth item from the top)
- Under the heading: `Description`, at the end of the second paragraph
- Move the mouse pointer to the close parenthesis of the underlined text: `Object.free()`
- Hold down the left mouse button, to start a selection
- Move the mouse pointer to the left until the uppercase `O` is selected in: `Object.free()`
- With the mouse pointer still over the underlined text, release the left mouse button

### Observed
The documentation page for `Object` opens, scrolled to the description for `void free()`

https://user-images.githubusercontent.com/13420573/168833476-9f1d3b75-b8b4-4fbc-8ee8-077f9b88ce9d.mp4

Navigating backwards to the previous page.
(with for example the left arrow in the top right corner of the Script Editor,
or with a mouse back thumb button)

Shows a selection difference between Godot versions:
- In v3.4.4.stable.official [419e713a2], the selection on the previous page remains active.
This allows for pressing `Control + c` to copy the selected text.

- But in v3.5.beta5.official [815f7fe63], the selection is gone.

### Expected
The link should not open, when selecting text, and the left mouse button is released over a link.

The text selection should just stop following the mouse pointer.

Like it does when releasing the left mouse button outside a link.

### Workaround
The current workaround is to select more text than intended,
so that the mouse pointer is outside a link when the left mouse button is released.

The extra text or spaces outside the link, need to be removed when the selection is copied and pasted somewhere else.

### Notes
The reproduction steps used a right to left selection, because it's easier to demonstrate the issue that way.
But it also happens when selecting left to right.

**Comment by danielkariv** [comment] 2022-05-19 08:16
I did some search, it seems that the problem is related to editor_help.cpp, and rich_text_label.cpp. There is a connect call for a signal called 'meta_clicked' at RichTextLabel. From quick looking, it seems the signal from RickTextLabel called from function gui_input, which deals with the mouse clicks. The issue comes because it doesn't deal with mouse dragging, only mouse clicks. it seems that we already has some cases checked like scrolling and not double clicking, so fixing this probably related to around line 1561 in rich_text_label.cpp.

I will probably try to fix it today, but others can try if they want.

**Comment by akien-mga** [comment] 2022-05-20 13:40
Fixed by #61182.

**Closed by akien-mga** 2022-05-20 13:40 UTC
Labels: enhancement, topic:editor, usability, documentation
