### ISSUE TITLE
Android build unoptimized in 3.4.stable?

### ISSUE THREAD

**Issue by bennyschirm** [godotengine/godot#54638] opened 2021-11-05 18:07 UTC
### Godot version

3.4.stable

### System information

Windows 10

### Issue description

I compiled the Android templates from source like it is described in the docs and when running Gradle as final step i get the following message. Not sure if this can be ignored (since the build actually succeeds) or if it's an issue, but this error is definetely new:
```
> Task :app:mergeReleaseJniLibFolders
Execution optimizations have been disabled for task ':app:mergeReleaseJniLibFolders' to ensure correctness due to the following reasons:
  - Gradle detected a problem with the following location: 'C:\Users\benny\Documents\Projects\godot\platform\android\java\app\libs\release'. Reason: Task ':app:mergeReleaseJniLibFolders' uses this output of task ':copyReleaseAARToAppModule' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.2/userguide/validation_problems.html#implicit_dependency for more details about this problem.
Gradle detected a problem with the following location: 'C:\Users\benny\Documents\Projects\godot\platform\android\java\app\libs\release'. Reason: Task ':app:mergeReleaseJniLibFolders' uses this output of task ':copyReleaseAARToAppModule' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.2/userguide/validation_problems.html#implicit_dependency for more details about this problem. This behaviour has been deprecated and is scheduled to be removed in Gradle 8.0. Execution optimizations are disabled to ensure correctness. See https://docs.gradle.org/7.2/userguide/more_about_tasks.html#sec:up_to_date_checks for more details.
```

### Steps to reproduce

Follow the steps in https://docs.godotengine.org/en/stable/development/compiling/compiling_for_android.html for 3.4.stable

**Comment by Calinou** [comment] 2021-11-05 18:17
cc @m4gr3d

**Comment by akien-mga** [comment] 2021-11-05 18:18
This is intended, enabling this optimization breaks the prebuilt APKs. The deprecation warning is there to warn us that we need to figure out a solution for this before upgrading to Gradle 8.0, which aims at removing the option we're using.

Maybe we can silence the warning to avoid confusing users @m4gr3d?

**Comment by madmiraal** [comment] 2021-11-13 13:10
Duplicate of #53751.

**Closed** 2021-11-13 13:26 UTC
Labels: discussion, platform:android, topic:export
