### ISSUE TITLE
Feature Request: Multiple variable in one line

### ISSUE THREAD

**Issue by 2dvision** [godotengine/godot#8078] opened 2017-03-19 17:10 UTC
In python you can set variable like this:

`a, b, c, = 1, 2, 3`

I think It is useful in godot.

`var forceJump, jumpCount, MAX_JUMP_COUNT = 500, 0, 2`

**Comment by bojidar-bg** [comment] 2017-03-19 18:58
Duplicate of #7584.

**Closed by bojidar-bg** 2017-03-19 18:58 UTC
