### ISSUE TITLE
Particle system depth test fails

### ISSUE THREAD

**Issue by albinaask** [godotengine/godot#42757] opened 2020-10-13 00:31 UTC
**Godot version:**
v4.0.dev.calinou.fe6109101
(It's the version specified in the editor and the console)

**OS/device including version:**
Windows 10, GPU&Driver: Nvidia 1070ti, CPU: AMD Ryzen 7

**Issue description:**
When putting a MeshInstance in front of a particle system exactly as shown in the reproduction project the particles shine through said MeshInstance, Which exact particle setting causes this I haven't figured out yet.

I may add that the problem persists if the particle material is put onto any mesh, which probably means that it rather is a problem regarding the material than the actual particles, but if I recall correctly from Godot 3.2 the materials becomes slightly different when strapped onto particles and that may be what's causing it...
**Steps to reproduce:**

open the main scene of zipped project and observe that the particle system is visible from outside the cube despite being completely inside the cube.

**Minimal reproduction project:**

[errorous project.zip](https://github.com/godotengine/godot/files/5368231/errorous.project.zip)

**Comment by clayjohn** [comment] 2020-10-13 00:57
Particles use the same materials for drawing as any other mesh. If the problem persists when the material is placed on a MeshInstance3D, then the issue is specific to the material. 

With that being said, what kind of settings did you use on your material? I can't check the MRP right now, but I may be able to help figure out the cause.

**Comment by Chaosus** [comment] 2020-10-13 13:49
This is fixable by turning off Proximity fade of Draw pass material:

![image](https://user-images.githubusercontent.com/3036176/95869454-09665180-0d74-11eb-850f-0fb0299827e0.png)

not sure whether it's a bug or not

**Comment by Chaosus** [comment] 2020-10-13 14:45
Probably related to https://github.com/godotengine/godot/issues/35646

**Comment by Calinou** [comment] 2021-07-19 22:34
Duplicate of https://github.com/godotengine/godot/issues/35646 (same cause).

**Closed by Calinou** 2021-07-19 22:34 UTC
Labels: topic:rendering
