### ISSUE TITLE
Can't debug built-in GDS

### ISSUE THREAD

**Issue by CsloudX** [godotengine/godot#84351] opened 2023-11-02 09:26 UTC
### Godot version

v4.2.beta4.official [93cdacbb0]

### System information

Windows 10, 64bit

### Issue description

Sometimes, when hit crash script, it not stop the final line, and the script path only show a string of nubmers.
![image](https://github.com/godotengine/godot/assets/35988767/e86df21c-d063-46e3-bd8c-03f32c5608d7)

### Steps to reproduce

/

### Minimal reproduction project

Sorry, I'm not found a minimal reprodution project yet.

**Comment by KoBeWi** [comment] 2023-11-02 10:08
Duplicate of #72854 (same cause)

**Closed by KoBeWi** 2023-11-02 10:08 UTC
Labels: bug, topic:gdscript, topic:editor, needs testing
