### ISSUE TITLE
FileSystem must be smarter

### ISSUE THREAD

**Issue by VictorGonzalezFernandez** [godotengine/godot#18939] opened 2018-05-16 18:02 UTC
In Godot, move elements in FileSystem must update always references in the project.

For example, if you move the path
- Logon
- Icon

ERROR: ImageLoader::load_image: Error opening file: res://Shpere_logon.png
   At: core\io\image_loader.cpp:55
ERROR: Main::setup2: Non-existing or invalid boot splash at: res://Shpere_logon.png. Loading default splash.

ERROR: ImageLoader::load_image: Error opening file: C:/Users/victo/OneDrive/Godot_v3.0.2/WuaUP Sphere/icon.png
   At: core\io\image_loader.cpp:55

The user should never manually update it if he uses the FileSystem.

There is a difference between moving the route in the operating system and within Godot. Within Godot he must be smarter.

**Godot version:**

3.02

**OS/device including version:**

Windows 10 64

**Issue description:**

**Steps to reproduce:**
Move the project path

**Minimal reproduction project:**

**Comment by Zylann** [comment] 2018-05-16 18:12
Would be interesting to check https://github.com/godotengine/godot/issues/14900 too

**Comment by KoBeWi** [comment] 2019-04-29 22:48
Works in 3.1, at least in cases listed here.

**Comment by dreamsComeTrue** [comment] 2019-10-11 10:24
is it still relevant today? I mean - on my projects it works as expected too...

**Comment by Calinou** [comment] 2019-10-11 11:45
I'll close this as this doesn't appear to be an issue in 3.1 onwards, according to @KoBeWi's comment. I also can't reproduce this on commit https://github.com/godotengine/godot/commit/aad4d8648b4593b5edb479e85984730770e77c70 (renaming the splash image updates its path in the Project Settings automatically).

**Closed by Calinou** 2019-10-11 11:45 UTC
Labels: enhancement, topic:editor, usability
