### ISSUE TITLE
Subclass automatically calls parent's _ready()

### ISSUE THREAD

**Issue by MelimeliDev** [godotengine/godot#6669] opened 2016-10-01 13:45 UTC
**Operating system or device - Godot version:**
Windows 10, Godot 2.1

**Issue description** (what happened, and what was expected):
It's easier to just read the screenshot, pay attention to the Output tab...
The parent's _ready() are called automatically, even when the subclass' didn't call it. Not sure if bug or working as intended.
![error1](https://cloud.githubusercontent.com/assets/14923217/19014479/4297baf8-8820-11e6-9af2-f3ae0c4d8ff7.png)

**Comment by neikeq** [comment] 2016-10-01 15:30
Duplicate of #6500
It's not a bug.

**Closed by neikeq** 2016-10-01 15:30 UTC
