### ISSUE TITLE
Cyclic Reference Bug

### ISSUE THREAD

**Issue by bleakgh** [godotengine/godot#94376] opened 2024-07-15 03:23 UTC
### Tested versions

v4.2.2.stable.official [15073afe3]

### System information

Windows 10 - v4.2.2.stable.official [15073afe3] - Compatibility

### Issue description

Using v4.2.2.stable.official [15073afe3], in a Node2D as a child of Node2D Scene_1, I set an @export var name: PackedScene to reference Scene_2; and in a child of Scene_2, I did the same with a child using the same script and a reference to Scene_2. Saving the project and then reloading, without any warning, corrupted Scene_1.

### Steps to reproduce

Create cyclic reference between PackedScenes.

### Minimal reproduction project (MRP)

[TestingAndTroubleshooting.zip](https://github.com/user-attachments/files/16229747/TestingAndTroubleshooting.zip)

**Comment by dalexeev** [comment] 2024-07-15 07:25
* Duplicate of #79625 or another one from #80877?

**Comment by KoBeWi** [comment] 2024-07-16 12:22
Closing as duplicate. Cyclic scene references are not supported.

**Closed by KoBeWi** 2024-07-16 12:22 UTC
