### ISSUE TITLE
It is impossible for a custom node to have a "virtual" base

### ISSUE THREAD

**Issue by rcmz** [godotengine/godot#9495] opened 2017-07-04 11:59 UTC
For example I want to create a custom node that derives from Joint2D. But if I set Joint2D as it base class in the plugin's script, I can't see the node in the node menu

Tested on 2.1.3 and 3 alpha

**Comment by bojidar-bg** [comment] 2017-07-04 12:46
Duplicate of #8034, even if it is explained better here.

**Closed by bojidar-bg** 2017-07-04 12:46 UTC
