### ISSUE TITLE
Saving a scene cause an empty black window appearing

### ISSUE THREAD

**Issue by ThakeeNathees** [godotengine/godot#37378] opened 2020-03-28 11:54 UTC
**Godot version:** 307b1b3

**OS/device including version:** Windows10

**Issue description:**
saving a scene cause an empty black window appearing instead of saving progress window, which takes the main window's focus.
![saving-script-window-bug](https://user-images.githubusercontent.com/41085900/77822456-ef875900-7118-11ea-864c-99551f0c7eb1.gif)

**Comment by Ev1lbl0w** [comment] 2020-03-28 12:45
Probably related to #37322

**Comment by KoBeWi** [comment] 2020-03-28 12:52
Duplicate of #37322

**Closed by KoBeWi** 2020-03-28 12:52 UTC
