### ISSUE TITLE
AssetLib: Long plugin name break the UI

### ISSUE THREAD

**Issue by haruyou27** [godotengine/godot#80507] opened 2023-08-11 05:36 UTC
### Godot version

v4.1.1.stable.arch_linux

### System information

OpenGL API 4.2 (Core Profile) Mesa 23.1.4 - Compatibility - Using Device: Intel - Mesa Intel(R) HD Graphics 2500 (IVB GT1)  

### Issue description

The AssetLib container is set to the size of their children and will automatic resize itself to display all the text, ignore user and windows manager setting.

![20230811_12h25m58s_grim](https://github.com/godotengine/godot/assets/68549456/9c4e61e3-4673-4823-af49-b31cc029f6fc)

### Steps to reproduce

Find some plugin that has very long name like _VRM Importer and MToon Shader - Humanoid 3d Avatar Model Format_

### Minimal reproduction project

n/a

**Comment by akien-mga** [comment] 2023-08-11 07:07
The text should be made to wrap with an ellipsis so it doesn't exceed the column width.

**Comment by lyuma** [comment] 2023-08-11 09:08
I can't even get out of AssetLib without making maximizing the Godot window.
![image](https://github.com/godotengine/godot/assets/39946030/acf4434a-5dc2-44fb-b7ae-ffdeb9aab865)

Sorry for the long addon name. I submitted an edit for my addon to make it a bit shorter: "VRM Importer for 3D Avatars and MToon Shader", though I think even then it needs line wrapping or ...

**Comment by GrammAcc** [comment] 2023-08-11 22:04
Hi, I'm hoping to make my first engine contribution, and I'd like to take a shot at fixing this. I'll start working on a PR if this isn't already being worked on. :)

**Comment by GrammAcc** [comment] 2023-08-12 17:42
@haruyou27 I submitted a PR #80555 that solves the problem of screen overflow on my local machine, but I was unable to reproduce the differently sized columns shown in your screenshots on my system on both the current master branch and 4.1.1 stable. I'm using Linux though, so there might be something window manager or DPI related going on here as well.

Can you try out the PR, and if the fix there doesn't solve the problem on your system, can you provide more information about your local machine: OS, Window Manager/DE (if applicable), monitor resolution and DPI?

Thanks!

**Comment by GrammAcc** [comment] 2023-08-12 19:50
@haruyou27 Sorry, please disregard my previous comment. Working on a different solution for the PR.

**Comment by lyuma** [comment] 2023-10-02 12:36
I have a dual monitor setup, and the issue only happens if I previously closed the godot editor while looking at AssetLib, so the AssetLib is focused when the editor starts up. In this case, it seems to be the width of my largest monitor, even on my small monitor. There are no long plugin names, so I don't think that's actually the issue.

See here when maximized on my 1080p monitor:
![image](https://github.com/godotengine/godot/assets/39946030/a6ceef0c-e4e1-4900-b112-d05fa02701ae)

And now here I dragged it onto my 4k monitor:
![image](https://github.com/godotengine/godot/assets/39946030/e46bc6d2-1971-4d26-877e-c31b6ca674cf)

Ok actually it's just horridly inconsistent. every time I test it's different. Also, if I try to resize the window to be big enough to contain the inspector, the assetLib just keeps popping more items onto the first two rows, and it sort of ratchets bigger and bigger and won't get smaller. Now I can't even fit the godot window on my 4k monitor without losing the inspector.
![image](https://github.com/godotengine/godot/assets/39946030/c762d93d-1863-4659-81c6-bca88cce53d6)

**Comment by GrammAcc** [comment] 2023-10-02 13:18
> I have a dual monitor setup, and the issue only happens if I previously closed the godot editor while looking at AssetLib, so the AssetLib is focused when the editor starts up. In this case, it seems to be the width of my largest monitor, even on my small monitor. There are no long plugin names, so I don't think that's actually the issue.

This *might* be fixed by the PR I submitted for this. The AssetLib plugin calculates the number of columns based on the width of its control when it is created, but the width of the individual columns were being expanded to the width of their contents because of the long plugin names, so the overall width would extend past the screen width.

In your screenshots, the columns have varying widths, so I think the PR might fix it since it clamps the column contents to the uniform calculated column width, but if the window is being resized to the width of the larger screen, it might be a problem with the width reported by the `get_size` method of `Control`, which would probably be beyond the scope of this issue and affect other parts of the UI as well. I believe the `get_size` method returns a value from some kind of internal cache, so that might be what's causing it to report the wrong value on reload, but I'm not very familiar with the internals of the UI system, so I can't say for sure. A more experienced contributor would probably know. :)

Hopefully, the PR fixes this on the dual resolution setup, but if not, it might be a separate issue.

I have a two-monitor setup as well, but both of mine are 1080p, so I can't test this myself. :(

**Closed** 2023-10-02 13:22 UTC
Labels: bug, confirmed, topic:assetlib
