### ISSUE TITLE
Window placement centered ignores display scaling on Windows 10

### ISSUE THREAD

**Issue by adrianpacala** [godotengine/godot#56062] opened 2021-12-18 21:26 UTC
### Godot version

v3.4.stable.official.206ba70f4

### System information

Windows 10 19042.1415, 3840x2160, 150% scaling

### Issue description

When UI scaling is set to >100% (150% in my case), the game window doesn't get centered properly - it looks like it's getting it position set based on screen resolution (3840x2160) without applying display scaling.

![image](https://user-images.githubusercontent.com/9934/146655807-a49f74fe-8e4e-4072-a3b0-c71d3175c9f6.png)

### Steps to reproduce

1. Set Windows display resolution to 3840x2160.
2. Set Windows display scaling to 150%.
3. Set Godot Display Scale to 150% (should be the default value). EDIT: Happens also with 100% and any other value so I don't think it's dependent on Godot's UI scaling.
4. Set Godot Window Placement to Centered.
5. Run the game.

**Comment by Calinou** [comment] 2021-12-18 21:38
Duplicate of https://github.com/godotengine/godot/issues/13017.

**Closed by Calinou** 2021-12-18 21:38 UTC
