### ISSUE TITLE
Indenting multiple lines multiple times grabs an extra unintended line

### ISSUE THREAD

**Issue by ArdaE** [godotengine/godot#23751] opened 2018-11-16 19:59 UTC
**Godot version:**
3.0.6 (stable/official)
3.1 (stable/official)

**OS/device including version:**
macOS Mojave - 10.14.4
Windows 10 Pro - 10.0.17763

**Issue description:**
In the text editors (GDScript and Shader editor), if multiple lines are selected with the cursor at the very beginning of the lines, the Indent Right command works as expected the first time, but then grabs an extra line that follows the selection on all consecutive indents.

It doesn't seem to matter if the selection is made upward or downward (see steps to reproduce where I describe an upward selection).

**Steps to reproduce:**
1. Open the script or shader (text) editor
2. Enter multiple lines of text
3. Go to the beginning of a line
4. Press Shift and then the Up Arrow key to make a multi-line selection
5. Press Tab (at this point the selected lines will get indented once as expected)
6. Press Tab a second time (and observe that an extra line that follows the selection gets indented)

The problem seems to be that the selection is extended incorrectly after the first Tab press to include the first character of the line that follows the selection, hence causing consecutive indents to include that line.

**Screenshots:**

**- After upward selection:**

<img width="137" alt="U1" src="https://user-images.githubusercontent.com/8313057/48643631-149c8100-e995-11e8-9f22-d9266ee5b630.png">

Note how Line4, which is NOT included in the selection above, gets carried after the second indent.

<img width="132" alt="U2" src="https://user-images.githubusercontent.com/8313057/48643646-1b2af880-e995-11e8-9e73-494f1277fe75.png">
<img width="143" alt="U3" src="https://user-images.githubusercontent.com/8313057/48643661-21b97000-e995-11e8-9696-b4cf43b26915.png">
<img width="176" alt="a4b" src="https://user-images.githubusercontent.com/8313057/48643810-97254080-e995-11e8-9dbb-d3d69a9ac474.png">

**- After downward selection:**

<img width="114" alt="Db" src="https://user-images.githubusercontent.com/8313057/48643741-5fb69400-e995-11e8-9a4f-82b71f700fb3.png">

Again note how Line4, which is NOT included in the selection above, gets carried after the second indent. Note that the slightly brighter highlight on Line4 is not a selection; it's the current line indicator that shows the line the cursor is on.

<img width="171" alt="D2" src="https://user-images.githubusercontent.com/8313057/48643664-22520680-e995-11e8-9ca1-b5cd72ea0605.png">
<img width="165" alt="D3" src="https://user-images.githubusercontent.com/8313057/48643665-22520680-e995-11e8-9fff-9f2f0cf16515.png">
<img width="185" alt="D4" src="https://user-images.githubusercontent.com/8313057/48643666-22520680-e995-11e8-8347-167a89340912.png">

**Comment by bojidar-bg** [comment] 2018-11-17 08:48
Seems like (at least partially) a duplicate of #14559.

**Comment by clayjohn** [comment] 2019-04-20 19:36
Is this bug still present in 3.1? it seems it may have been fixed.

**Comment by ArdaE** [comment] 2019-04-21 01:45
Still present in 3.1. Tested on both macOS and Windows 10.

**Closed** 2019-12-30 15:20 UTC
Labels: bug, topic:editor
