### ISSUE TITLE
C# - Node references get lost when you instance a packed scene in another scene.

### ISSUE THREAD

**Issue by exts** [godotengine/godot#17586] opened 2018-03-17 16:07 UTC
**Godot version:**
3.0.2-Stable

**OS/device including version:**
Windows 10

**Issue description:**
If I create a scene and attached a script to it for example a scene containing a label. If I create a class member of `Label` type (or any type), instantiate it to a empy `new Label()` and reassign that value in the `_Ready()` (or `_Init()`) methods using the `GetNode` global function and proceed create an instance of this scene in another scene script. Then when I try to access the instanced class method which attempts to access that reference to that node that we reassigned to the class member in `_Ready()` or `_Init()` then the reassignment of that value never happens or "gets lost".

Funnily enough, if you play that scene as the top level scene (as there's no instance of it) then the reference stays persistent throughout the class without issue.

**Steps to reproduce:**
Check repo below

**Minimal reproduction project:**
https://github.com/exts/packedgotcha (should be a zip there) which is a minimal example of what's happening and an alternative workaround to this problem which seems... unnecessary.

**Comment by nazgulsenpai** [comment] 2018-03-17 17:27
I think you just have some issues with your code. _scene is still null when you're trying to call it's functions in _Ready().

If you add:

    public override void _Process(float delta){
        if(_scene != null && sceneUpdated == false)
        {
        _scene?.UpdateText("My Text");
        _scene?.MyLabel.SetPosition(new Vector2(100, 100));
        GD.Print("Updated text");
        sceneUpdated = true;
        }
    }

to Main.cs, you'll see the label gets updated.

**Comment by exts** [comment] 2018-03-17 17:45
@nazgulsenpai that doesn't make sense, I thought _Ready & _Init got called before process why would scene be null when I instance the packed scene?

**Comment by nazgulsenpai** [comment] 2018-03-17 17:46
Because the scene isn't pre loaded since it isn't referenced anywhere until you call it

**Comment by nazgulsenpai** [comment] 2018-03-17 17:46
Main is the scene that's "ready", the scene Example you're instancing hasn't yet been loaded

**Comment by exts** [comment] 2018-03-17 17:48
@nazgulsenpai That doesn't make sense. So you're telling me when I instance a packed scene in the main scene it's not being loaded when ... I load it there? Then tell me what is it doing when I'm loading the packed scene in the main scene?

**Comment by exts** [comment] 2018-03-17 21:17
@neikeq and @akien-mga can you guys elaborate on the order of execution when it comes to packed scenes (instanced scenes) in csharp because if @nazgulsenpai's example where he waits for _scene to get set while if i call getnode directly in a similar like I did with `UpdateAlternateText` it gets executed instantly?

Does GetNode() get executed as soon as possible before all other code? Understanding the order of execution at runtime would help explain what our limitations are with csharp and godot.

**Comment by vnen** [comment] 2018-04-03 20:27
I didn't understand the original issue, but given @paulloz comment, it looks like a misunderstanding of how Godot operates and not a bug. I'll close this issue, but feel free to keep discussing if more clarification is needed.

**Closed by vnen** 2018-04-03 20:27 UTC
