### ISSUE TITLE
built-in Android IAP bug - android 8 and 9

### ISSUE THREAD

**Issue by canvasbushi** [godotengine/godot#32142] opened 2019-09-14 23:18 UTC
**Godot version:**
3.1.1

**OS/device including version:**
android 8.1.0 and 9

**Issue description:**
Fatal Exception: java.lang.NullPointerException
Attempt to invoke interface method 'android.os.Bundle com.android.vending.billing.IInAppBillingService.getSkuDetails(int, java.lang.String, java.lang.String, android.os.Bundle)' on a null object reference
org.godotengine.godot.payments.PaymentsManager$7.run (PaymentsManager.java:390)
java.lang.Thread.run (Thread.java:780)

**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by AlexRixhardson** [comment] 2019-09-14 23:56
Possibly a duplicate of https://github.com/godotengine/godot/issues/30922?

What are the steps to reproduce the problem?

**Comment by clayjohn** [comment] 2019-09-17 16:38
Looks like duplicate of #30922. If, not OP can respond with more info and we can re-open.

**Closed by clayjohn** 2019-09-17 16:38 UTC
