### ISSUE TITLE
GDScript 2.0: If the _init() function is not defined in the inherited class, the _init() function in the parent class will be executed twice

### ISSUE THREAD

**Issue by Xwdit** [godotengine/godot#64378] opened 2022-08-13 22:56 UTC
### Godot version

4.0.alpha(f2a61684)

### System information

Windows 11

### Issue description

Create a global class and define the _init() function in it, then create a scene and attach a script that inherits this class without define _init(), then when the scene is instantiated, the _init() in the parent class will be executed twice.

### Steps to reproduce

Create a global class and define the _init() function in it, then create a scene and attach a script that inherits this class

**Comment by maniacalipsis** [comment] 2022-11-08 00:35
May be a related issue:
```
class_name ClassA
func _init(params)
    #Implementation...
...
```
```
class_name ClassB extends ClassA
#The _init() inherited without overridings.
...
```
```
class_name OwnerClass
var a:=ClassA.new({}) #This is ok.
var b:=ClassB.new({}) #<This throwing an error. "Parser Error: Can't load global class , cyclic reference?"
...
```

But if define _init() in all inherited classes, e.g. like this:
```
class_name ClassB extends ClassA
func _init(params)
   super(params) #Just pass arguments to the base class.
...
```
then it works fine.

**Comment by adamscott** [comment] 2023-01-08 17:07
Could not reproduce on master (fcba87e). @akien-mga, I suggest we close this issue.

### Minimal reproduction project
[64378.zip](https://github.com/godotengine/godot/files/10368979/64378.zip)

**Closed** 2023-01-08 20:21 UTC
Labels: bug, topic:gdscript

**Comment by maniacalipsis** [comment] 2023-01-10 08:04
Yes, in the v4.0b10 inheritance works fine.
