### ISSUE TITLE
[Godot 4 beta 17] Non-string characters entered into @export_category() crashes the engine.

### ISSUE THREAD

**Issue by kovitikus** [godotengine/godot#72759] opened 2023-02-05 13:17 UTC
### Godot version

4.0 beta 17

### System information

Windows 10

### Issue description

Entering characters such as `p`, `r`, `z` into `@export_category()` will cause the editor to close.

For example:
```
@export_category(z
```
Then crash.

### Steps to reproduce

Try to enter a character other than " into @export_category()

### Minimal reproduction project

N/A

**Comment by dalexeev** [comment] 2023-02-05 14:17
Duplicate of #72539. Fixed by #72567.

**Closed** 2023-02-05 15:31 UTC
