### ISSUE TITLE
CSG bug

### ISSUE THREAD

**Issue by BielNS06** [godotengine/godot#53200] opened 2021-09-29 03:48 UTC
### Godot version

i forgor but it was something on 3.0

### System information

Windows, I5, intel hd graphics idk

### Issue description

i was building a csg map some time ago and it got a bug where the walls had tiny holes that u could go inside it was very weird, it happened when i had built a 2nd room for the map which was basically 2 room and a corridor connecting them

### Steps to reproduce

build a small/medium sized map

### Minimal reproduction project

its in my google drive but im too sleepy and lazy to get it there because i would need to download each project and check them for the one

**Comment by akien-mga** [comment] 2021-09-29 05:29
There's not enough information for us to work with in this report, you need to provide detailed steps to reproduce, or a reproduction project, or at least _show_ what the issue is.

Bug reports are like talking to your general practitioner, if you only say that it hurt somewhere sometime ago, they're unlikely to come up with a diagnostic, much less with a cure.

**Comment by fire** [comment] 2021-09-29 22:02
Duplicate of https://github.com/godotengine/godot/issues/22988

**Closed** 2021-09-29 22:14 UTC
Labels: topic:core, needs testing, topic:3d
