### ISSUE TITLE
RSA is not implemented completely. Cannot sign using private key, and verify using public key.

### ISSUE THREAD

**Issue by alexander-yozzo** [godotengine/godot#86586] opened 2023-12-28 17:34 UTC
### Tested versions

Reproduceable in Godot Engine v4.2.stable.official.46dc27791

### System information

Godot v4.2.stable - Windows 10.0.22621 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 4060 Laptop GPU (NVIDIA; 31.0.15.4609) - 13th Gen Intel(R) Core(TM) i9-13900H (20 Threads)

### Issue description

You should be able to load a private key into a CryptoKey and use it to sign (using encrypt method) data, and then verify (using decrypt method) with the associated public key.

This results in an empty array being returned.

        var public_key_file_path = "full_path_to_public_key_file.pub"
	var crypto = Crypto.new()
	var key = CryptoKey.new()
	key.load(public_key_file_path, true)
	var data = "7201E7377C0" # example cypher data, signed with private key
	var encrypted = PackedByteArray(data.to_utf8_buffer())
	var decrypted = crypto.decrypt(key, encrypted) # BUG results in empty array

Running on Windows 11
Useful background
https://www.reddit.com/r/godot/comments/rcz49j/confused_with_cryptokeys/

### Steps to reproduce

Using a private RSA key, create some signed data.

Then try to decrypt that data in Godot, using the public RSA key.

You will get an empty array in return.

### Minimal reproduction project (MRP)

        var public_key_file_path = "full_path_to_public_key_file.pub"
	var crypto = Crypto.new()
	var key = CryptoKey.new()
	key.load(public_key_file_path, true)
	var data = "7201E7377C0" # example cypher data, signed with private key
	var encrypted = PackedByteArray(data.to_utf8_buffer())
	var decrypted = crypto.decrypt(key, encrypted) # BUG results in empty array

**Comment by AThousandShips** [comment] 2023-12-28 17:38
Since the documentation is clear this is something that should be discussed in a [proposal](https://github.com/godotengine/godot-proposals) as this is not a bug

**Comment by AThousandShips** [comment] 2023-12-28 18:31
Note that this would require a different library as, from what I can see, the mbedtls libary used doesn't allow decryption with public key, by design

**Comment by Kintar** [comment] 2023-12-28 18:48
Why would you want to use "encrypt" and "decrypt"? The sign-and-verify workflow is implemented with the "Sign" and "Verify" functions.

**Comment by Kintar** [comment] 2023-12-30 03:38
Proof that RSA signing _is_ implemented correctly, in case anyone is confused.

https://github.com/Kintar/godot_RSA_signature_example

**Comment by AThousandShips** [comment] 2023-12-31 22:37
Closing this as there's nothing wrong here, and this is based on the way the library used works

If you still want this considered for a change please open a proposal as instructed above, but be aware that this would require some additional code or even a separate library as the library used for RSA doesn't support this, or rather the support for it is deprecated and is gone in the latest version of the library, which we will at some point update to

**Closed by AThousandShips** 2023-12-31 22:37 UTC
Labels: feature proposal, discussion, topic:core
