### ISSUE TITLE
"Please Confirm..." "Exit the editor?" [cancel] [quit]

### ISSUE THREAD

**Issue by raould** [godotengine/godot#6126] opened 2016-08-12 05:35 UTC
(thanks for a crazy cool tool!)

Linux Ubuntu 16.04.1 x86_64 running MATE desktop.
Godot version "Godot_v2.1-stable_x11.64"

If I have *not changed anything in a scene* (eg. i just loaded it; or i used 'undo' enough times), when I go to quit that scene editor, the system should *not* ask me to "Please Confirm..." etc.

When it does ask, that is scary UX to the end user because they have no way of being sure thing are saved or not since we're apparently always asked.

**Comment by kubecz3k** [comment] 2016-08-12 08:23
Well editor already do this on scene level. As a workaround you could always close each individual scene and dismiss/save all the changes. The way how it works right now is ok for me personally, but it would be cool if dialog message would change if we have any unsaved changed to something like: "Are you sure you want to exit? You have unsaved changes!"

**Comment by akien-mga** [comment] 2016-08-12 08:28
This can of course be improved, but I think it's good that the editor asks before closing even if there are no unsaved changes. Sometimes you have no unsaved changes, but you have several scenes opened with a specific part of the viewport focused in each scene, a specific set of scripts and maybe even some debugging breakpoints set or output from previous runs in the Output panel or the debugging tools.

If you inadvertently press the close button and it stops without confirmation, you might lose all this "non-savable" setup, and it can be quite frustrating.

**Comment by akien-mga** [comment] 2016-08-12 08:28
It could of course be made optional via an editor setting.

**Comment by kubecz3k** [comment] 2016-08-12 09:57
Yeah it's good that this dialog is there, sometimes I'm quite messy with keyboard shortcuts, and I'm accidentally pressing 'exit editor' combination.

**Comment by vnen** [comment] 2016-08-14 16:36
To me it does not show this "(Unsaved changes will be lost)" message when I quit the editor. I get only this:

![godot windows tools 64_2016-08-14_13-35-33](https://cloud.githubusercontent.com/assets/5599796/17650432/0cbdd59c-6224-11e6-9383-9453a6ddf05c.png)

**Comment by akien-mga** [comment] 2016-08-15 08:07
Contrarily to the OP, I think now @raould is talking about the "Quit to Project Manager" dialog, which IIRC does warn about unsaved changes going lost. Which would be a duplicate of #4731.

**Comment by kubecz3k** [comment] 2016-08-15 15:16
Closing as a duplicate of https://github.com/godotengine/godot/issues/4731

**Closed by kubecz3k** 2016-08-15 15:16 UTC
Labels: archived
