### ISSUE TITLE
Shortcuts using PageUp/Down do not work when the script editor is open

### ISSUE THREAD

**Issue by letheed** [godotengine/godot#16228] opened 2018-01-31 10:04 UTC
e.g. set Ctrl+PageUp/Down for previous/next tab.

on 3.0-stable

**Comment by BeayemX** [comment] 2018-01-31 10:34
#12164

**Comment by akien-mga** [comment] 2018-02-01 13:18
Duplicate of #12164.

**Closed by akien-mga** 2018-02-01 13:18 UTC
