### ISSUE TITLE
Invalid call to built-in function 'dict2inst'. Expected 4 arguments.

### ISSUE THREAD

**Issue by noverd** [godotengine/godot#68244] opened 2022-11-04 07:12 UTC
### Godot version

3.5.1 stable steam

### System information

Ubuntu20.04, GLES3

### Issue description

i call the function 'dict2inst' which has only one argument and i pass it.
The error "Invalid call to built-in function 'dict2inst' appears. Expected 4 arguments."

### Steps to reproduce

I just turned the object into a dictionary and saved it to a file as json
Then downloaded and then used
dict2inst

**Comment by Calinou** [comment] 2022-11-04 19:53
@noverd Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

**Comment by noverd** [comment] 2022-11-05 09:15
[reproduction.zip](https://github.com/godotengine/godot/files/9943454/reproduction.zip)

**Comment by kleonc** [comment] 2022-11-05 10:27
Duplicate of #30572. Simpler repro:
```gdscript
tool
extends EditorScript

class A:
	func _init(arg) -> void:
		pass
		
func _run() -> void:
	var d = inst2dict(A.new(123))
	dict2inst(d) # <- error
```

**Closed** 2022-11-05 10:27 UTC
Labels: bug, topic:core, needs testing
