### ISSUE TITLE
GDScript: logical and/or between non boolean  value cause a parser error

### ISSUE THREAD

**Issue by ThakeeNathees** [godotengine/godot#44688] opened 2020-12-25 16:28 UTC
**Godot version:** 7d972b8c6

**OS/device including version:** windows10

**Issue description:**
if both operands of the and/or operator are compile time known non boolean values, the parser throws error (where it shouldn't)
```gdscript
func _ready():	
	if "" or []:
		pass
## Parse Error: Invalid operands "String" and "Array" for "or" operator.
```

**Minimal reproduction project:**
N/A

**Comment by lyuma** [comment] 2021-08-06 03:13
Confirmed on latest master 85186bc

**Comment by qarmin** [comment] 2021-10-04 04:42
I'm not sure if this should be fixed.
What exactly means `if ""`? Is true when is empty or always false because it is not bool?
I like Rust approach when everything must be clear(`if` can only check bool condition) and `""` will need to be changed to `!"".is_empty()`
But this will broke compatibilty and will need to add warning to 3.x branch to fix project earlier.

**Comment by vnen** [comment] 2021-10-04 14:46
I don't think this is a bug, the logical operators should only accept booleans.

**Comment by vnen** [comment] 2021-10-08 11:26
Reopening for discussion, since this worked on 3.x.

Is this really wanted? I can't see a lot of use cases for this TBH, I feel it's more likely to happen as an user error than anything else. Note that `if "":` should still work, just using boolean operations that doesn't work anymore.

cc @KoBeWi

**Comment by Vaasref** [comment] 2022-01-25 09:16
It goes beyond being easy to read. This issue is about not having a arbitrary language.

```
var arr:Array = []
if not arr:#error because you cannot use something that is not a bool with "not"
  print("array empty")
if arr:#no error
  print("not empty")
var other_condition:bool = true
if arr and other_condition:#error because you cannot use something that is not a bool with "and"
  print("not empty")
```
But it gets better !
GDScript is not supposed to force typing on you, is it ? So if my variable is not type then I need to also check for non-nullity before checking for emptiness, right ?
Nope, since it is not typed then I **can** just use the simpler check because ... reason ? (I mean if its not a bug then there must be a reason right ?)
```
var arr = []
if arr and arr[0] == 0:
  print("arr[0] is 0")
```
Typing your data  you want to be more sure of the data it contains to not have to be as explicit when trying to use that data.



Now for the addressing the "less readable" argument.
Do you really think that :

```
var arr:Array = []
if arr and arr[0] == 0:
  print("arr[0] is 0")
```
... is less readable than :
```
var arr:Array = []
if arr.is_empty() and arr[0] == 0:
  print("arr[0] is 0")
```
I take that example because that is an extremely common occurrence for me, checking if something exists or is null before actually using it. How can it not be readable ? Why would you **force** the use of a more explicit when it is already more than obvious in that common case.
I'm not against being more explicit at time when it is warranted, but here it seems to me like a case of Enterprise Edition coding.
If you cannot understand a simple check of a object right before calling one of its function then I thing there is no amount of "!= null" that will help you and you should better get some sleep because you won't write any good code until then.

```
Me: I want python
Mom: No, we have python at home 
Python at home: ...
```
The previous version of GDScript was already an ersatz of python, but ok, it was only a bit rougher and mostly due to the way classes and built-in types were different.
But now it's really going backward on a very common syntax like that doesn't even work.

So yeah, that may not be a "bug" but that's clearly an oversight and the discrepancy in behavior makes it an issue and not just a matter of opinion about readability.

**Comment by h0lley** [comment] 2022-05-01 23:18
I think a language should either be strict about `if`/`and`/`or`/`not` only taking boolean, or it should fully support truthy/falsey validation.

For a high level scripting language like GDScript I'd personally prefer the latter.
Users who want to be safe can always use `==` to ensure explicit boolean comparison.
Users / projects / cases where loose validation is fine should be able to use `if`/`and`/`or`/`not` with the same types.

When `if "":` is supported, then so should be `if true and "":`
When `if []:` is supported, then so should be `if true and []:` and `if not []:`

Got curious and made a breakdown:

| | if in 3.x | not in 3.x | and/or in 3.x | if in 4.0.alpha | not in 4.0.alpha | and/or in 4.0.alpha |
| ------------- | ------------- | ------------- | ------------- | ------------- | ------------- | ------------- |
| "" | false | true | supported | false | ⚠️ false, and only works with literal | ⚠️ not supported |
| "a" | true | false | supported | true | false, ⚠️ only works with literal | ⚠️ not supported |
| 0 | false | true | supported | false | true | supported |
| 1 | true | false | supported | true | false | supported |
| 0.0 | false | true | supported | false | true | supported |
| 1.0 | true | false | supported | true | false | supported |
| [] | false | true | supported | false | ⚠️ not supported | ⚠️ not supported |
| [1] | true | false | supported | true | ⚠️ not supported | ⚠️ not supported |
| {} | false | true | supported | false | ⚠️ not supported | ⚠️ not supported |
| {"a": 1} | true | false | supported | true | ⚠️ not supported | ⚠️ not supported |
| ^"" | false | true | supported | false | ⚠️ false, and only works with literal  | ⚠️ not supported |
| ^"a" | true | false | supported | true | false, ⚠️ only works with literal  | ⚠️ not supported |
| &"" | n/a | n/a | n/a | true | false, ⚠️ only works with literal  | ⚠️ not supported |
| &"a" | n/a | n/a | n/a | ⚠️ false | false, ⚠️ only works with literal  | ⚠️ not supported |
| Vector2.ZERO | false | true | supported | false | ⚠️ false, and only works with literal | ⚠️ not supported |
| Vector2.ONE | true | false | supported | true | false, ⚠️ only works with literal | ⚠️ not supported |
| null | false | true | supported | false | true | supported |
| [Object] | true | false | supported | true | false | supported |
| [Freed Object] | true | false | supported | true | ⚠️ true | supported |

String and Vector only working with `not` as literals as well as `not ""` and `not Vector2.ZERO` validating to false seem to be separate bugs. Also `[Freed Object]` behaving weirdly, that's reported here: #59816

Types like Vector3, AABB, Quaternion, Rect2, etc. seem to be suffering from the same issues as Vector2.

No idea what's going on with NodePath and StringName. They are probably not really relevant in this table but still weird how they behave.

**Comment by h0lley** [comment] 2022-07-14 00:11
I think it's helpful when things that cannot be null validate to false when their content is empty/0, like an empty string, a dictionary without items, or a vector of magnitude 0.

when an user writes something like `if arr:`, then it's obvious that they mean to do `if not arr.empty():` - I don't see how that could go against anyone's expectations, and find that it makes for better readability.

also, I am for `[Freed Object]` validating to false as that would allow us to do away with `is_instance_valid()`. I don't know if most, but I can tell that many new users expect to be able to treat a `[Freed Object]` as null.

**Comment by KoBeWi** [comment] 2022-07-14 00:26
> I think it's helpful when things that cannot be null validate to false when their content is empty/0, like an empty string, a dictionary without items, or a vector of magnitude 0.

Yeah I was against it initially, but then incorporated it in my code and it's indeed convenient. But it was a trap, as this issue appeared and it broke lots of my code xd And it doesn't seem like restoring the 3.x behavior is easy/possible. Maybe the solution is to completely forbid non-booleans (maybe except objects) in conditions.

Personally I'm fine either way, as I started using `is_empty()` etc anyway, just to avoid such bugs.

> also, I am for [Freed Object] validating to false as that would allow us to do away with is_instance_valid(). I don't know if most, but I can tell that many new users expect to be able to treat a [Freed Object] as null.

[Freed Object] is like that for technical reasons. Previously it was inconsistent between release and debug and it led to many bugs. IIRC making it evaluate to false implies some performance penalties due to validation.

**Comment by tavurth** [comment] 2022-09-25 22:57
For my use case this is very unusable in the current state. 

I'm very used to languages taking anything passed to a conditional `if` and automatically transforming to boolean.

```gdscript
if not true:
  pass
````
Works, whereas:

```gdscript
if not {}:
   pass
```
Fails with a compile error.

If we want to be so strict, we should offer a `converter` function type similar to in [nim](https://nim-lang.org/docs/manual.html#converters). Where I can explicitly convert my args of an `if` to bool.

Due to GDScripts "Open to Everyone" approach, I would say this is a bad idea.

Most JS & Python users are used to `and` or `not` reducing the operands to bool by default. Why should we force them an extra annoying step to coerce these values? It's `GD`script, not `GD`c.

**Comment by Vaasref** [comment] 2023-02-23 12:01
Thanks to give that issue some attention. I really need some features from Godot 4 but the amount of refactoring that issue would imply made it very impractical.
It's fine to have to have to refactor code when features purposefully changed, but refactoring for a regression due to an oversight doesn't feel right.

**Comment by tavurth** [comment] 2023-02-24 17:24
@Vaasref I'm sure this regression will be fixed soon, in some cases what I've done is simply added a helper to my `Utils` singleton:

```gdscript
func truthy(item) -> bool:
	return item and item != null

print(truthy({}))
print(truthy(null))
print(truthy({ "a": 5 }))
```

In that way it can be easily refactored later when fixed.

IMO Godot 4.x is now worth it, and have ported my main projects over already.

**Closed** 2023-06-18 14:36 UTC
Labels: bug, discussion, topic:gdscript, confirmed, regression
