### ISSUE TITLE
Godot UI suddenly exits (crash to desktop)

### ISSUE THREAD

**Issue by vjrossi** [godotengine/godot#4818] opened 2016-05-26 08:14 UTC
**Operating system or device - Godot version:**
Windows 10 - Godot 2.0.3 (not Steam)

**Issue description** (what happened, and what was expected):
Occasionally Godot editor disappears without warning while editing a script. If I happen to have my app running at the time, both it and the Godot DOS box remain. The last time this happened I captured the last few lines before the crash. I'm not sure of the relevance, but it's here anyway:

```
ERROR: Object::emit_signal: Error calling method from signal 'breaked': 'ScriptEditor::_breaked': Expected 2 arguments.
   At: core\object.cpp:1210
*User switched to another app*
ERROR: Object::emit_signal: Error calling method from signal 'breaked': 'ScriptEditor::_breaked': Expected 2 arguments.
   At: core\object.cpp:1210
shit?: No error
ERROR: StreamPeerWinsock::read: Server disconnected!

   At: platform\windows\stream_peer_winsock.cpp:210

```
The asterisked line is debugging output from my app.

**Steps to reproduce:**
Unfortunately the error is not easily reproduced, but the one common theme is that it seems to happen when I'm undoing/redoing code in the script editor. This has happened a number of times now (at least 1/2 dozen) and I'm also pretty sure it wasn't happening like this in earlier versions. I'm a pretty heavy undo/redo user so I would've noticed it in earlier versions. Sorry to be vague.

**Link to minimal example project** (optional but very welcome):
Not relevant due to nature of the issue.

**Comment by kubecz3k** [comment] 2016-05-26 10:24
This happens to me occasionally (Linux). If I recall correctly it must be somehow correlated with closing high amount of scripts and/or scenes and clicking `ctrl+z` after that. But I also can't reproduce this easily.

**Comment by Paulb23** [comment] 2016-05-26 10:49
Yeah it happens when redoing certain complex operations due to a null pointer, see #4326

**Comment by Marqin** [comment] 2016-05-26 15:22
I was asked by @bojidar-bg to check this issue via static analysis and there seems to be explicit null dereference: http://i.imgur.com/E2a3yAJ.png

**Comment by akien-mga** [comment] 2016-06-04 12:44
Did #4823 fix this issue?

**Comment by Marqin** [comment] 2016-06-04 13:59
It shouldn't if we would to belive static analysis.

**Comment by reduz** [comment] 2016-06-14 11:52
I think this is fixed, I also added some error checking just in case in undo/redo to avoid it from a potential crash situation

**Comment by reduz** [comment] 2016-06-20 14:38
well, closing for now, please re-open if you find something else

**Closed by reduz** 2016-06-20 14:38 UTC
Labels: bug, topic:editor
