### ISSUE TITLE
Resource setting tab is not collapsible when edited in an Array

### ISSUE THREAD

**Issue by Arrow-x** [godotengine/godot#44043] opened 2020-12-02 16:58 UTC
**Godot version:**

3.2.3 stable

**OS/device including version:**

Windows
RX 460 GLES2
R5 3600

**Issue description:**
Opening Up a Resource in the Inspector will show at the bottom a Collapsible tab for said resource settings, 
![ResourceSectionCorrect](https://user-images.githubusercontent.com/3308421/100904919-cd27b580-34c7-11eb-99af-a251a8cf75ee.png)
but when they are in an array, opening the array in the inspector and then opening a Resource in it will show the resource setting section fully open with no option to close it
![ResourceSectionArrays](https://user-images.githubusercontent.com/3308421/100905004-e0d31c00-34c7-11eb-9b69-1bed84dfdd15.png)

**Steps to reproduce:**
export an Array var and put a resource in it

**Minimal reproduction project:**

[ArrayResourceIssue.zip](https://github.com/godotengine/godot/files/5630789/ArrayResourceIssue.zip)

**Comment by Calinou** [comment] 2020-12-02 17:07
Duplicate of https://github.com/godotengine/godot/issues/23759.

**Closed by Calinou** 2020-12-02 17:07 UTC
