### ISSUE TITLE
Scanning for projects crashes the Editor, and any other Godot releases afterwards

### ISSUE THREAD

**Issue by YumaRowen** [godotengine/godot#60089] opened 2022-04-10 01:20 UTC
### Godot version

4.0 Alpha 6

### System information

Windows 11

### Issue description

After changing the drive used in the "Scan" window, the editor crashes and any version of Godot (even custom builds) crash on boot.

I wasn't even able to get to importing the project file, as right upon changing the drive, it crashed, and now I can't seem to be able to run any Godot versions at all, even non-official nightly builds or past releases...

EDIT: It seems to go away when you restart the OS entirely, though.

### Steps to reproduce

1. Open the "Scan" page on Godot's homepage.
2. Change the drive used.

**Comment by KoBeWi** [comment] 2022-06-09 20:04
Can't reproduce in d120b09
@RetsuOwen Is this still happening? Maybe it was some one-time hardware issue?

**Comment by KoBeWi** [comment] 2022-10-03 22:31
Closing due to lack of update. Please comment if you can still reproduce this issue in the latest version of Godot.

**Closed by KoBeWi** 2022-10-03 22:31 UTC
Labels: bug, platform:windows, topic:editor, crash, regression
