### ISSUE TITLE
Godot Mono v3.1.1 crash when casting Node to Camera2D

### ISSUE THREAD

**Issue by PanosTrak** [godotengine/godot#30603] opened 2019-07-15 21:41 UTC
**Godot version:**
Godot-mono stable v3.1.1
66baa3b

**OS/device including version:**
OS: Manjaro Linux
Kernel Version: 4.19.56-1
Mono JIT compiler version 5.20.1
GPU1: Intel Corporation HD Graphics 5500
GPU2: Advanced Micro Devices, Inc. [AMD/ATI] Opal XT [Radeon R7 M265/M365X/M465] (its the Radeon R7 M270 but it doesnt show up like this)

**Issue description:**
When i use 
`camera = (Camera2D)GetNode("camera");` 
i get this error
> drivers/unix/net_socket_posix.cpp:199 - Socket error: 104

**Minimal reproduction project:**
[Pirates.zip](https://github.com/godotengine/godot/files/3394304/Pirates.zip)

**Comment by KoBeWi** [comment] 2019-07-16 00:31
I can run the project just fine, no errors.

**Comment by PanosTrak** [comment] 2019-07-16 08:32
[2019_07_16 11.22.06 (1547).txt](https://github.com/godotengine/godot/files/3396049/2019_07_16.11.22.06.1547.txt)
[2019_07_16 11.21.57 (1504).txt](https://github.com/godotengine/godot/files/3396071/2019_07_16.11.21.57.1504.txt)

The pastebin bellow is the output to the terminal
https://pastebin.com/cdR05hzv

**Comment by akien-mga** [comment] 2019-07-16 08:50
Stacktrace on thread 1:
```
=================================================================
    Managed Stacktrace:
=================================================================
      at <unknown> <0xffffffff>
      at Godot.Object:godot_icall_Object_ClassDB_get_method <0x000c2>
      at Godot.Camera2D:.cctor <0x0008b>
      at System.Object:runtime_invoke_void <0x000cb>
      at <unknown> <0xffffffff>
      at Godot.NativeCalls:godot_icall_1_514 <0x000e8>
      at Godot.Node:GetNode <0x000e3>
      at Godot.Node:GetNode <0x0008f>
      at PlayerScript:_Ready <0x000db>
      at System.Object:runtime_invoke_void__this__ <0x000ce>
=================================================================
```

**Comment by akien-mga** [comment] 2020-01-19 18:25
Can you still reproduce the issue in the latest 3.2 builds?

I tried with 3.2 RC 1 on Linux and had no crash, the casted node is a `Camera2D` as expected.

**Comment by PanosTrak** [comment] 2020-01-19 19:13
Well, i have a fresh install of linux and it seems to work okay even on 3.1.2.stable.mono.official, i think the problem was that the msbuild was outdated because the maintainer of this package on AUR made this package to depend on the msbuild-stable which was outdated, now its set to msbuild which seems to be fine!

**Comment by akien-mga** [comment] 2020-01-19 21:14
Thanks, closing then.

**Closed by akien-mga** 2020-01-19 21:14 UTC
Labels: bug, topic:mono

**Comment by neikeq** [comment] 2020-01-19 22:40
Looking at the log, this is the same as #29812, which was fixed by #31784 (the issue is still open because the fix is just a workaround).
