### ISSUE TITLE
Color issue in HTML5

### ISSUE THREAD

**Issue by letheed** [godotengine/godot#13998] opened 2017-12-05 14:02 UTC
I reimplemented Blaster Faster with the 3.0 beta1 a few days ago and exported it to the `docs` folder in github. There are color artifacts which are not present when I run the game normally. Not sure if this is a Firefox or Godot issue. It doesn't run on Chromium so I can't compare.

![blasterfastercapture1small](https://user-images.githubusercontent.com/5330692/33610451-df2cf7ea-d9cb-11e7-9b93-d6cb1c36c3bf.png) ![blasterfastercapture2small](https://user-images.githubusercontent.com/5330692/33610454-e0ab3ae6-d9cb-11e7-8d91-82f1acdac287.png) ![blasterfastercapture4small](https://user-images.githubusercontent.com/5330692/33610833-cd2e18a2-d9cc-11e7-8f42-d1f5849148de.png)

[Source code](https://github.com/letheed/blaster-faster/)
[WASM version](https://letheed.github.io/blaster-faster/blaster-faster.html)

Info:
Godot 3.0 beta1
Firefox 57.0.1 (64 bits) on Ubuntu 17.10

**Comment by bojidar-bg** [comment] 2017-12-05 14:38
Duplicate of #13985.

**Closed by bojidar-bg** 2017-12-05 14:38 UTC
