### ISSUE TITLE
AnimatedSprite always starts and never stops playing when node processing is enabled

### ISSUE THREAD

**Issue by ProbDenis** [godotengine/godot#5586] opened 2016-07-07 21:09 UTC
**Operating system or device - Godot version:**
Godot 2.1 custom build. Linux 64 bit

**Issue description** (what happened, and what was expected):
When I add an AnimatedSprite to a scene and it is set to be processing, it always plays, even when the playing property is set to false, and even stopping it from a script doesn't do anything. Note that this doesn't happen when the node is not set to be processing.

**Steps to reproduce:**
- Create a new scene and add an AnimatedSprite
- Add a new SpriteFrames resource to it with a few frames.
- Add a script to the AnimatedSprite node. Write set_process(true) into _ready().
- Make sure that the "playing" property is not checked.
- Run the scene and see that the sprite is animating.
- Calling self.stop() (even in _process) doesn't help, the animation never stops.

**Comment by akien-mga** [comment] 2016-07-24 08:29
I cannot reproduce the part about:
> Calling self.stop() (even in _process) doesn't help, the animation never stops.

Actually I've tested to try to reproduce, and noticed that `_process` and playing are tightly coupled for AnitmatedSprite. Basically in what I could see, `play()` enforces `set_process(true)` and `stop()` enforces `set_process(false)`.

I've made this example project to test: [animatedsprite_process.zip](https://github.com/godotengine/godot/files/380186/animatedsprite_process.zip)

I'll leave it for @reduz to comment further, but I guess this behaviour is not a bug but by design.

**Comment by DenisComtesse** [comment] 2016-07-24 09:29
I'm going to test it again to see if I an reproduce it with with the latest beta.

But I don't believe that this behaviour is intended. Imagine writing a script for the AnimatedSprite node, and stopping the animation disables all your code in _process(delta) - that doesn't make any sense to me.

**Comment by DenisComtesse** [comment] 2016-07-25 11:55
I've added two buttons to the example projects to examine the start and stop behaviour:
https://dl.dropboxusercontent.com/u/1891681/animatedsprite.zip

Tested it with 2.1 RC1 and made the following observations:
- set_process(true) automatically starts playing the animation, no matter if the node is set to playing or not.
- Calling stop() doesn't do anything in this case.
- Calling play() and then calling stop() actually stops the animation.
- But this also disables the whole script in _process(delta)

So there's clearly something weird going on.

**Comment by bojidar-bg** [comment] 2016-07-25 13:06
Well, you would usually use a Sprite/AnimatedSprite to only draw the player/enemy/whatever, and keep them a child of another node, like a rigidbody or kinematicbody.

**Comment by DenisComtesse** [comment] 2016-07-25 13:35
That's the usual way to do it, but that doesn't make this behaviour any better. it's counter-intuitive at least, and undocumented. As far as I know, no other node type does this (maybe the AnimationPlayer, not sure about that). Godot allows you to write scripts for all kinds of node types, the new plugin system encourages you to write custom node types. So you'd expect that it's no problem to write a script that inherits from AnimatedSprite, if only to add some custom features to the AnimatedSprite node (this is exactly what I was trying to do).

**Comment by bojidar-bg** [comment] 2016-07-25 13:58
Note that Camera2D does a similar thing when disabling/enabling smoothing.

**Comment by reduz** [comment] 2016-07-25 14:06
This is expected, animatedsprite uses processing, so not really a bug

**Comment by DenisComtesse** [comment] 2016-07-25 14:15
It makes sense that play() makes it start processing, but why does it have to stop processing when the animation stops? Is this really necessary, or shouldn't it be possible to be processing while noit playing? Also, auto-playing although the "playing" property is set to false is clearly a bug in my book, as is a disabled stop() function under circumstances mentioned above.
But if all this is really intended, it should at least be documented.

**Comment by akien-mga** [comment] 2016-07-25 14:18
> Also, auto-playing although the "playing" property is set to false is clearly a bug in my book,

It's not auto-playing, it starts playing because you call `set_process(true)`, which is for this node equivalent to calling `play()`.

**Comment by DenisComtesse** [comment] 2016-07-25 14:29
This happens when you call set_process(true) without calling play(). Then it is impossible to stop, unless you call play() again.

My suggestion would be that stopping just holds the animation at its current frame (or resets it) without disabling the processing completely. This way it would still be possible to use stop() without disabling any code written in _process. Just my two cents.

**Comment by reduz** [comment] 2016-07-25 14:31
Since this is something pretty confusing for many users, I was thinkig that
nodes should just have an internal process notification instead of process,
so they dont mix

**Comment by reduz** [comment] 2016-07-25 15:29
noted it in the list for 3.0

**Comment by akien-mga** [comment] 2016-07-25 16:41
What's left for this issue is to update the docs then.

**Comment by akien-mga** [comment] 2017-08-08 12:25
> Since this is something pretty confusing for many users, I was thinkig that
nodes should just have an internal process notification instead of process,
so they dont mix

That was implemented, so it should be fixed in 3.0.

**Closed by akien-mga** 2017-08-08 12:25 UTC
Labels: documentation, enhancement, topic:core
