### ISSUE TITLE
Certain Control nodes cause a crash if `physics/3d/run_on_separate_thread` is enabled

### ISSUE THREAD

**Issue by jtnicholl** [godotengine/godot#67333] opened 2022-10-13 00:45 UTC
### Godot version

v4.0.beta.custom_build [ea47e03b3]

### System information

Linux (Fedora 36)

### Issue description

If 3D physics is set to run on a separate thread, some Control nodes will cause a crash. It does not matter if there are any 3D nodes actually in the scene tree at all.
Clicking a ColorPickerButton seems to crash the most frequently. I also got a crash from clicking around on a ColorPicker (sans button), leaving an empty Tree open for a while, and clicking on a regular Button. All produced the same stacktrace:
```
================================================================
handle_crash: Program crashed with signal 11
Engine version: Godot Engine v4.0.beta.custom_build (ea47e03b360d0aeee10c1f7ef798f5750c2b1aa8)
Dumping the backtrace. Please include this when reporting the bug on: https://github.com/godotengine/godot/issues
[1] /lib64/libc.so.6(+0x3ea70) [0x7f5da7241a70] (??:0)
[2] void memdelete<WorkerThreadPool::BaseTemplateUserdata>(WorkerThreadPool::BaseTemplateUserdata*) (/home/jtnicholl/godot/source/godot/./core/os/memory.h:109)
[3] WorkerThreadPool::_add_group_task(Callable const&, void (*)(void*, unsigned int), void*, WorkerThreadPool::BaseTemplateUserdata*, int, int, bool, String const&) (/home/jtnicholl/godot/source/godot/core/object/worker_thread_pool.cpp:303)
[4] long WorkerThreadPool::add_template_group_task<GodotStep3D, void (GodotStep3D::*)(unsigned int, void*), decltype(nullptr)>(GodotStep3D*, void (GodotStep3D::*)(unsigned int, void*), decltype(nullptr), int, int, bool, String const&) (/home/jtnicholl/godot/source/godot/./core/object/worker_thread_pool.h:181)
[5] GodotStep3D::step(GodotSpace3D*, float) (/home/jtnicholl/godot/source/godot/servers/physics_3d/godot_step_3d.cpp:346)
[6] GodotPhysicsServer3D::step(float) (/home/jtnicholl/godot/source/godot/servers/physics_3d/godot_physics_server_3d.cpp:1645 (discriminator 3))
[7] PhysicsServer3DWrapMT::thread_step(float) (/home/jtnicholl/godot/source/godot/servers/physics_server_3d_wrap_mt.cpp:41)
[8] CommandQueueMT::Command1<PhysicsServer3DWrapMT, void (PhysicsServer3DWrapMT::*)(float), float>::call() (/home/jtnicholl/godot/source/godot/./core/templates/command_queue_mt.h:322 (discriminator 4))
[9] CommandQueueMT::_flush() (/home/jtnicholl/godot/source/godot/./core/templates/command_queue_mt.h:374)
[10] CommandQueueMT::wait_and_flush() (/home/jtnicholl/godot/source/godot/./core/templates/command_queue_mt.h:414)
[11] PhysicsServer3DWrapMT::thread_loop() (/home/jtnicholl/godot/source/godot/servers/physics_server_3d_wrap_mt.cpp:57)
[12] PhysicsServer3DWrapMT::_thread_callback(void*) (/home/jtnicholl/godot/source/godot/servers/physics_server_3d_wrap_mt.cpp:48)
[13] Thread::callback(Thread*, Thread::Settings const&, void (*)(void*), void*) (/home/jtnicholl/godot/source/godot/core/os/thread.cpp:67)
[14] void std::__invoke_impl<void, void (*)(Thread*, Thread::Settings const&, void (*)(void*), void*), Thread*, Thread::Settings, void (*)(void*), void*>(std::__invoke_other, void (*&&)(Thread*, Thread::Settings const&, void (*)(void*), void*), Thread*&&, Thread::Settings&&, void (*&&)(void*), void*&&) (/usr/include/c++/12/bits/invoke.h:61)
[15] std::__invoke_result<void (*)(Thread*, Thread::Settings const&, void (*)(void*), void*), Thread*, Thread::Settings, void (*)(void*), void*>::type std::__invoke<void (*)(Thread*, Thread::Settings const&, void (*)(void*), void*), Thread*, Thread::Settings, void (*)(void*), void*>(void (*&&)(Thread*, Thread::Settings const&, void (*)(void*), void*), Thread*&&, Thread::Settings&&, void (*&&)(void*), void*&&) (/usr/include/c++/12/bits/invoke.h:97)
[16] void std::thread::_Invoker<std::tuple<void (*)(Thread*, Thread::Settings const&, void (*)(void*), void*), Thread*, Thread::Settings, void (*)(void*), void*> >::_M_invoke<0ul, 1ul, 2ul, 3ul, 4ul>(std::_Index_tuple<0ul, 1ul, 2ul, 3ul, 4ul>) (/usr/include/c++/12/bits/std_thread.h:252)
[17] std::thread::_Invoker<std::tuple<void (*)(Thread*, Thread::Settings const&, void (*)(void*), void*), Thread*, Thread::Settings, void (*)(void*), void*> >::operator()() (/usr/include/c++/12/bits/std_thread.h:259)
[18] std::thread::_State_impl<std::thread::_Invoker<std::tuple<void (*)(Thread*, Thread::Settings const&, void (*)(void*), void*), Thread*, Thread::Settings, void (*)(void*), void*> > >::_M_run() (/usr/include/c++/12/bits/std_thread.h:210)
[19] /home/jtnicholl/godot/source/godot/bin/godot.linuxbsd.editor.dev.x86_64() [0x72abf13] (thread.o:?)
[20] /lib64/libc.so.6(+0x8ce2d) [0x7f5da728fe2d] (??:0)
[21] /lib64/libc.so.6(+0x1121b0) [0x7f5da73151b0] (??:0)
-- END OF BACKTRACE --
================================================================
```

### Steps to reproduce

1. Enable threaded 3D physics
2. Open a scene with certain Control nodes
3. Wait, or click around a bit
4. Crash

### Minimal reproduction project

[PhysicsCrash.zip](https://github.com/godotengine/godot/files/9769472/PhysicsCrash.zip)

**Comment by lmurray** [comment] 2022-10-13 23:26
Possible duplicate of #63671.

**Comment by Calinou** [comment] 2022-10-13 23:29
Related to https://github.com/godotengine/godot/issues/61250.

**Comment by jtnicholl** [comment] 2022-10-14 00:24
> Possible duplicate of #63671.

It doesn't crash for me if there are no control nodes, and the stack trace is different. Not to mention this crash happens within seconds if you mess with a ColorPickerButton. It's definitely related, but I don't think it's a duplicate.

**Comment by lyuma** [comment] 2022-11-25 23:28
Can confirm #67680 fixes my original MRP (from #69186 )

The MRP in this issue is less reliable, so I wasn't able to confirm the fix for this one (it only ever crashed once for me)

**Comment by lyuma** [comment] 2022-11-25 23:30
This seems to trigger a different stack for me than what I saw in #69186, but the stack trace in the OP was the same.

Here's the stack that this MRP produces:
```
================================================================
CrashHandlerException: Program crashed
Engine version: Godot Engine v4.0.beta.custom_build (c7ceb94e372216b1b033d7c2ac26d5b7545c4dac)
Dumping the backtrace. Please include this when reporting the bug on: https://github.com/godotengine/godot/issues
[0] embree::TaskScheduler::wait
[1] embree::TaskScheduler::wait
[2] embree::TaskScheduler::wait
[3] embree::TaskScheduler::wait
[4] embree::TaskScheduler::wait
[5] <couldn't map PC to fn name>
[6] <couldn't map PC to fn name>
[7] <couldn't map PC to fn name>
[8] <couldn't map PC to fn name>
[9] <couldn't map PC to fn name>
[10] embree::TaskScheduler::wait
[11] BaseThreadInitThunk
-- END OF BACKTRACE --
================================================================
```

A bit strange, but I still think it's the same cause

**Comment by akien-mga** [comment] 2022-11-25 23:32
The embree stuff is a false positive, it's wrong resolving the (missing) symbols.

**Closed** 2022-11-29 12:42 UTC
Labels: bug, topic:physics, crash, topic:gui, topic:3d
