### ISSUE TITLE
GDScript 2.0: constant parameterized array is typed as a generic one

### ISSUE THREAD

**Issue by vonagam** [godotengine/godot#68978] opened 2022-11-21 23:11 UTC
### Godot version

4.0.beta5 and currently last build of 11e1c83

### System information

MacOS 10.15.7

### Issue description

The code in ***Steps to reproduce*** will produce a runtime error of:
```
Invalid type in function 'bar' in base 'Node2D ()'. Cannot convert argument 1 from Array to Array.
```
The array type should be parameterized with anything besides `Variant` to reproduce.
My guess is that constant array is wrongfully typed just as a usual array (of variants).

### Steps to reproduce

```gdscript
extends Node

const empty_array: Array[ int ] = []

func bar( array: Array[ int ] ) -> void:
  pass

func _ready() -> void:
  bar( empty_array )
```

### Minimal reproduction project

N/A

**Comment by Calinou** [comment] 2022-11-21 23:18
Duplicate of https://github.com/godotengine/godot/issues/58636.

**Comment by vonagam** [comment] 2022-11-21 23:55
Ok, now that I thought about it, it might be a duplicate but not of that issue.

The underlying problem here is that `const array: Array[int]` is wrongly typed as `Array[Variant]` and that produces the same error as in mentioned issue (since it is about problems with `Array[Variant]`). But this mismatch causes other issues not connected to arguments, for example from there:
```gd
var array : Array[String] = ["1", "2"]
array.push_back(3)
print(array)
```
This will print `["1", "2"]` and reject `3` with an error. But if you switch `var` to `const` than the protection will be gone.

**Comment by vonagam** [comment] 2022-11-22 21:30
@Calinou can this be reopened? Or should I open new separate issue?
```gd
var var_array: Array[String] = ["1", "2"]
const const_array: Array[String] = ["1", "2"]
assert( var_array == const_array ) # no error

var_array.push_back(3)
const_array.push_back(3)
assert( var_array == const_array ) # will fail here
```

**Closed** 2023-01-31 10:20 UTC
Labels: bug, topic:gdscript
