### ISSUE TITLE
Image resource preview incorrect with Lossy or Video RAM compression

### ISSUE THREAD

**Issue by matrem** [godotengine/godot#14333] opened 2017-12-06 20:56 UTC
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Linux mint 18.2 64 bits / godot master

**Issue description:**

An image resource is not well displayed in the resource property after I add it as diffuse texture in ma spatial material. And then after it is used as a resource, it not even well displayed in the resource explorer.

Also it seems the image is really not well sampled (in the spatial material, but even in particles material).

**Steps to reproduce:**

**Link to minimal example project:**

Here the image is well displayed in the resource explorer, but not in the right panel :
![screenshot from 2017-12-06 21-49-59](https://user-images.githubusercontent.com/9594859/33684950-4ce198ea-dad0-11e7-86d1-03ef2480cebe.png)
Then i change it from gimp and come back to godot, all preview are bad :
![screenshot from 2017-12-06 21-53-43](https://user-images.githubusercontent.com/9594859/33684959-504ec0f2-dad0-11e7-891f-9a8439d6d825.png)

minimal project :
[Image.zip](https://github.com/godotengine/godot/files/1536851/Image.zip)

**Comment by matrem** [comment] 2017-12-07 18:44
It seems to be link with compression.
As soon as compression mode is 2 (when use by a the material), preview as wrong : https://github.com/godotengine/godot/blob/6527f2e68465b06113b3960ad4e366f1373699c9/editor/import/resource_importer_texture.cpp#L412

**Comment by robfram** [comment] 2018-03-09 20:23
I have been looking around this bug. The problem also occurs with `Lossy` compression, not only with `Video RAM`.

And it only happens with small image sizes (8x8 pixels). If you scale your image up to a 16x16 PNG, all works fine.

I think the important part of your bug report is the debug message that appears: `modules/etc/image_etc.cpp:120 - Condition [...]`. I am not able to get that message, but the image get crappy when compressed to ETC2. I got this info messages instead the warning/error ones:

```
begin encoding, format: ETC2_RGB8
time encoding: 1
```

If you delete all .import files and directory and set a breakpoint just before the ETC2 compression (i.e. `modules/etc/image_etc.cpp:176`) and run godot in editor mode (`run -e image.tscn`), you will see the texture correctly applied until you continue the execution, then it will change to the corrupted one.

I think the problem is related to the implementation of the ETC2 compression algorithm. Acording to the compression algorithm [(Ericsson slides)](https://pdfs.semanticscholar.org/d62f/f7cb7ced249e52d75385008bf3c973b23dac.pdf), it divides the image in blocks of 4x4 pixels (or 2x4 pixels), and according to the member of Google who coded the library Godot is using, this specific implementation is blazing fast thank to some tricks commented in this [article](https://medium.com/@duhroach/building-a-blazing-fast-etc2-compressor-307f3e9aad99).

I also tested to update the full ETC2Comp, but it still fails.

I would like to test another tool to generate ETC2 files and visualize them, but I can't use the [Mali Texture Compression Tool](https://developer.arm.com/products/software-development-tools/graphics-development-tools/mali-texture-compression-tool/downloads) or the [PVRTexTool](https://community.imgtec.com/developers/powervr/tools/pvrtextool/) due to OS support.

Anyone can check something of this?

**Comment by reduz** [comment] 2018-09-06 15:30
Previews are generated here:
https://github.com/godotengine/godot/blob/master/editor/editor_resource_preview.cpp

**Comment by raphael10241024** [comment] 2019-05-06 09:57
Tested use ETCComp to compress the texture and generated a wrong image, and there is someone has commit an  issue here https://github.com/google/etc2comp/issues/40 .Maybe we should just don't compress it when image is small, or try to fix the code error?

**Comment by KurtYilmaz** [comment] 2019-10-06 01:55
> Tested use ETCComp to compress the texture and generated a wrong image, and there is someone has commit an issue here [google/etc2comp#40](https://github.com/google/etc2comp/issues/40) .Maybe we should just don't compress it when image is small, or try to fix the code error?

Looks like etc2comp already has a few PRs waiting that are 2 years old. Last merge/commit was 3 years ago, not sure if they are actively accepting changes right now. Would it be preferred to just disallow compression of small images like you suggested? This line already does the following for RGBA8 images; I think that would be a good spot to do an image size check.

https://github.com/godotengine/godot/blob/6527f2e68465b06113b3960ad4e366f1373699c9/editor/import/resource_importer_texture.cpp#L231-L233

I can make the PR if that method is okay!

**Comment by sas41** [comment] 2020-02-10 15:04
I managed to narrow down the issue to mostly images below 16x16 and only on HDR mode too.

From what I understand, the issue would be gone once Vulcan comes about, so perhaps mark this as a 4.0 milestone?

**Comment by Calinou** [comment] 2020-02-10 15:39
@sas41 Could you reproduce this issue with images of size 16×16 exactly, or only 15×15 and lower?

**Comment by sas41** [comment] 2020-02-11 12:45
@Calinou, okay, so further testing with the ``master`` branch and then the ``vulkan`` branch lead me to these following results:

Sample images used (10x zoom):
<img src="https://user-images.githubusercontent.com/2854477/74235946-cc275c80-4cd8-11ea-807d-029b380c7705.png " height="180">
16x16, 15x15, 14x14, 10x10, 4x4.


- Funny things happen when HDR is ENABLED with non HDR images under VRAM ``master``, image structure just gets all messed up:
![Issue_14333_VRAM](https://user-images.githubusercontent.com/2854477/74235948-ccbff300-4cd8-11ea-8e5e-cbc937308158.png)
![Issue_14333_VRAM_Sideways](https://user-images.githubusercontent.com/2854477/74235956-cdf12000-4cd8-11ea-86c3-a3a0228b5e50.png)

- Enabling Normal Map in VRAM mode while HDR is on, will preserve structure but mess up color.
![Issue_14333_VRAM_NORMAL_MAP_ENABLED](https://user-images.githubusercontent.com/2854477/74235949-ccbff300-4cd8-11ea-961c-396eb8c650bf.png)


- Without HDR, VRAM seems fine?:
![Issue_14333_VRAM_NO_HDR](https://user-images.githubusercontent.com/2854477/74235950-cd588980-4cd8-11ea-8bb0-ff406a83a978.png)
![Issue_14333_VRAM_NO_HDR_Sideways](https://user-images.githubusercontent.com/2854477/74235954-cd588980-4cd8-11ea-9644-220d909bda91.png)

- Lossy Compressions simply doesn't work as well for image sizes less than 16x16, there is just not enough pixels to work with by the looks of it. Results for both Normal Map on and off were the same.
![Issue_14333_LOSSY](https://user-images.githubusercontent.com/2854477/74235943-caf62f80-4cd8-11ea-8269-80e12287a92f.png)
![Issue_14333_LOSSY_Sideways](https://user-images.githubusercontent.com/2854477/74235945-cc275c80-4cd8-11ea-80a1-ef15fd75775c.png)

I then checked out ``vulkan``, to see what the differences were compared to current ``master``:

- Vulkan in Lossy mode:
![Issue_14333_VULKAN_LOSSY](https://user-images.githubusercontent.com/2854477/74235958-cdf12000-4cd8-11ea-9f3a-4730d18b1acd.png)

- Vulkan in VRAM Compressed, with HDR enabled but Normal Map disabled:
![Issue_14333_VULKAN_VRAM_COMPRESSED_HDR_NORMAL_MAP_DISABLED](https://user-images.githubusercontent.com/2854477/74235959-ce89b680-4cd8-11ea-9a6d-8c506f657f1b.png)

- Vulkan in VRAM Compressed, with HDR enabled but Normal Map enabled:
![Issue_14333_VULKAN_VRAM_COMPRESSED_HDR_NORMAL_MAP_ENABLED](https://user-images.githubusercontent.com/2854477/74235961-cf224d00-4cd8-11ea-9dc9-3d2dace3147a.png)

- Vulkan in VRAM Uncompressed, with HDR enabled:
![Issue_14333_VULKAN_VRAM_UNCOMPRESSED_HDR](https://user-images.githubusercontent.com/2854477/74235963-cf224d00-4cd8-11ea-9c98-0cb3b57fa384.png)

- Vulkan in VRAM Uncompressed, with HDR disabled:
![Issue_14333_VULKAN_VRAM_UNCOMPRESSED_NO_HDR](https://user-images.githubusercontent.com/2854477/74235965-cfbae380-4cd8-11ea-89f3-ef47f8674d13.png)

My conclusion is that the issue comes down to HDR mode and how it interacts with standard 8 bit per channel images, along with how HDR interacts with those 8bpc images when Normal Map is enabled.

Both of those cases result in unexpected behaviour, and from what I understand HDR mode won't be included when 4.0/``vulkan`` is merged in to ``master``.

**Comment by Calinou** [comment] 2020-02-11 13:42
@sas41 Thanks for doing this extensive testing work :slightly_smiling_face:

**Comment by sas41** [comment] 2020-02-11 13:47
@Calinou No problem, my pleasure.
Can we count this as a 4.0 milestone?
I hear ``vulkan`` will be merged to ``master`` later today (2020-02-11).

Also it is important to note, that the preview images are actual representations of what these textures look like when applied as a material (albedo/rgb) to a surface or mesh, hence, Image resource previews are fine, it's the way the texture data is interpreted/imported that is the problem.

**Comment by KoBeWi** [comment] 2020-12-24 22:00
![image](https://user-images.githubusercontent.com/2223172/103098255-6602aa00-460a-11eb-8d47-251975407797.png)
Looks fixed in 3.2.4 beta4, but not sure.

**Closed** 2024-04-23 17:34 UTC
Labels: bug, topic:editor, confirmed
