### ISSUE TITLE
OBJ meshes get corrupted on reimport on Android editor

### ISSUE THREAD

**Issue by Booklight12** [godotengine/godot#80371] opened 2023-08-07 11:48 UTC
### Godot version

4.1.stable

### System information

Android13

### Issue description

I'm trying to import the obj model file on Android but there seems to be some compatibility issues? You can do two tests on both the computer and the mobile side to make sure what I'm saying is true.
![Screenshot_2023-08-07-19-44-12-648_org godotengine editor v4](https://github.com/godotengine/godot/assets/64678717/69e05974-96df-460b-b062-ae99f62b8af2)

### Steps to reproduce

Create an obj file and import it into the Godot engine on Android.

### Minimal reproduction project
[test.zip](https://github.com/godotengine/godot/files/12279298/test.zip)

**Comment by Booklight12** [comment] 2023-08-07 11:52
Under no circumstances should a cube look like this
![Uploading Screenshot_2023-08-07-19-51-56-049_org.godotengine.editor.v4.jpg…]()

**Comment by Booklight12** [comment] 2023-08-07 11:53
Under no circumstances should a cube look like this
![Screenshot_2023-08-07-19-51-56-049_org godotengine editor v4](https://github.com/godotengine/godot/assets/64678717/e8f66cfd-a480-425f-89cb-736a50cbc45a)

**Comment by Booklight12** [comment] 2023-08-07 12:06
I need to declare that this is a "door" resource that I found from itch resources, but it appears in such a state in the engine.
![Screenshot_2023-08-07-20-05-20-338_org godotengine editor v4](https://github.com/godotengine/godot/assets/64678717/b142846e-8c59-4fd2-99aa-488aa240e904)

**Comment by Zireael07** [comment] 2023-08-07 12:21
Are you 100% sure the models look proper in Blender, that the materials aren't set as two-sided

**Comment by Booklight12** [comment] 2023-08-07 12:37
This is the obj file from my last photo, you can try opening it on blender
[door](https://github.com/Booklight12/text/blob/main/Door4.obj)

**Comment by Booklight12** [comment] 2023-08-07 12:46
For files exported by blender this is completely invisible in the editor
![Screenshot_2023-08-07-20-44-58-154_org godotengine editor v4](https://github.com/godotengine/godot/assets/64678717/258d5899-649b-4efb-a13b-a8bfdbaa7aa7)
![Screenshot_2023-08-07-20-44-23-163_org godotengine editor v4](https://github.com/godotengine/godot/assets/64678717/9e7704e1-8e84-4457-9d35-aff0592fd4cc)
![Screenshot_2023-08-07-20-44-13-733_org godotengine editor v4](https://github.com/godotengine/godot/assets/64678717/3dced36a-ad6f-4193-a9b3-fcb793387f9e)
![Screenshot_2023-08-07-20-44-05-785_org godotengine editor v4](https://github.com/godotengine/godot/assets/64678717/4a207050-480a-41aa-892b-f3d8dbb18fa0)

**Comment by Booklight12** [comment] 2023-08-07 12:46
You can see the object only in the preview

**Comment by Booklight12** [comment] 2023-08-07 16:51
[Watch this video](https://github.com/Booklight12/text/blame/main/Screenrecorder-2023-08-08-00-34-32-353.mp4)

**Comment by fire** [comment] 2023-08-07 19:38
I can confirm that that the cube's bottom triangle is missing on Gdoot Engine steam stable.

![editor_screenshot_2023-08-07T123811](https://github.com/godotengine/godot/assets/32321/46f0be32-0ac9-4f6a-bf4d-99546d5c09f2)

**Comment by fire** [comment] 2023-08-07 19:41
Maybe the 4.1.1 version fixed the problem.

**Comment by fire** [comment] 2023-08-07 19:49
@clayjohn @m4gr3d @BastiaanOlij Any ideas how to test on Android? The broken obj import seems to be a specific bug.

**Comment by Booklight12** [comment] 2023-08-07 23:49
4.1.1 did not fix the export problem, in fact, when I repeatedly tried to import obj files, I found that their shapes would become strange
![Screenshot_2023-08-08-07-47-21-868_org godotengine editor v4](https://github.com/godotengine/godot/assets/64678717/4f1881c3-37ae-451d-939d-4f010e30b501)

**Comment by akien-mga** [comment] 2023-08-08 07:06
I confirm the bug with 4.1.1 on Android (Xiaomi Poco F1). Both the mobile and GL renderer seem to have the same issue.

I tried switching the MRP's obj to import as scene, which didn't solve it, but after switching back to import as mesh I managed to get a good import (3 default cubes). Then hitting reimport again made the cubes disappear.

**Comment by Booklight12** [comment] 2023-08-08 12:28
sure

**Comment by Booklight12** [comment] 2023-08-09 13:10
Please, fixing this bug is important to me

**Comment by Calinou** [comment] 2023-08-09 16:50
> Please, fixing this bug is important to me

Issues are resolved by contributors on a best-effort basis. We can't provide an ETA on when this will be fixed.

**Comment by ZeroLikviz** [comment] 2023-10-30 17:10
hi guys, I have an idea why this might be happening. I have 2 devices: realme c21 with android 11 and Xiaomi pad 5 with android 13. I've been programming on both of them using C++. I have created a graphical application using SDL2. As you know, SDL2 uses double buffering, and if everything was fine on Realme, then on Xiaomi pad 5 the second buffer was constantly changing, various incomprehensible pieces appeared there, and sometimes it was completely cleaned. I solved the problem by manually creating a buffer.

As I said, the problem was only on the Xiaomi pad 5. I decided to check if the problem is related to the device. I asked a friend for a Poco 3 pro and after launching the program, I realized that the problem was related to either MIUI or android 13. 

In the end, I decided to download Godot 4 on Realme c21 and the result only confirmed my theory: the problem is related to either MIUI or android 13. As far as I understand, something affects dynamic memory when no one uses it and in order to solve the problem, it is necessary to save data in dynamic memory, until then, while this data will not be needed.  Also, the erase command sometimes breaks data in the container, I didn't look at the code, but if the erase command is used, then you should be more careful with it. 

I hope this information helps a little.


Realme c21:
![IMG-20231030-WA0000](https://github.com/godotengine/godot/assets/143567019/8ab91a0b-c105-4c16-bc8b-06e43579ffc9)

Xiaomi pad 5:

https://github.com/godotengine/godot/assets/143567019/1634c184-6a9b-4e8f-8773-445a3f0c2105

**Closed** 2023-12-04 22:06 UTC
Labels: bug, platform:android, confirmed, topic:import, topic:3d
