### ISSUE TITLE
project manager gui not loading completely

### ISSUE THREAD

**Issue by ritor1sefa** [godotengine/godot#77463] opened 2023-05-25 05:43 UTC
### Godot version

4.1dev2.mono (668cf3c66)

### System information

windows 10, intel HD4000

### Issue description

I have an old laptop that does not initialize the discrete graphics card = runs on a built-in HD4000.
Run with --rendering-driver opengl3 option, and .\_sc\_ file. It leads to the fact that on the screenshots - the gui is not loaded. In this case, the buttons work, you can create a project, select an already created one, run ..
The main editor is loaded normally, without problems. projects are no problem.

Without .\_sc\_ it runs without these visual issues.
I haven't tried the non-mono version, but I guess it doesn't depend on that.

![Godot_v4 1-dev2_mono_win64_2023-05-25_07-23-00](https://github.com/godotengine/godot/assets/10572388/4843cb5a-e08a-494b-aaec-f6009bc3bd90)
![Godot_v4 1-dev2_mono_win64_2023-05-25_07-23-21](https://github.com/godotengine/godot/assets/10572388/481ece62-7e13-4b4b-9f04-ebe8730bddc6)

### Steps to reproduce

Disable discrete graphics card
Create .\_sc\_ file
Run with: --rendering-driver opengl3

### Minimal reproduction project

N/A

**Comment by akien-mga** [comment] 2023-05-25 06:36
If it runs differently with and without a `._sc_` file, it means that there is an editor setting defined in either the self-contained or the global `editor_settings-4.tres` which impacts this. So it would be helpful to compare both and try to identify that option.

Then, you could check that your Intel graphics drivers are properly up to date. You need to make sure to install them from the Intel website, and not Windows Update, which often forces a rollback to ancient and buggy drivers on these old chipsets.

**Comment by ritor1sefa** [comment] 2023-05-25 08:01
> If it runs differently with and without a `._sc_` file, it means that there is an editor setting defined in either the self-contained or the global `editor_settings-4.tres` which impacts this. So it would be helpful to compare both and try to identify that option.
> 
I found & added this line to the same place, in the portable version. did not help.: 
project_manager/default_renderer = "gl_compatibility"
There was no other difference between them.

> Then, you could check that your Intel graphics drivers are properly up to date. You need to make sure to install them from the Intel website, and not Windows Update, which often forces a rollback to ancient and buggy drivers on these old chipsets.
Updated. did not help.

**Comment by akien-mga** [comment] 2023-05-25 08:19
Thanks for testing. Now I notice the 4.1 dev 2 version, so the issue is likely the same as https://github.com/godotengine/godot/issues/77136 which was fixed by https://github.com/godotengine/godot/pull/77163.

You can delete the cache manually as described in https://github.com/godotengine/godot/issues/77136#issuecomment-1550394417 to work it around.

**Closed by akien-mga** 2023-05-25 08:19 UTC
Labels: platform:windows, topic:rendering
