### ISSUE TITLE
Android build: cannot find -lc++ clang++: error: linker command failed with exit code android

### ISSUE THREAD

**Issue by MohammadKhashashneh** [godotengine/godot#33214] opened 2019-10-31 16:46 UTC
**Godot version:**
2.6.1 stable

**OS/device including version:**
Fedora 30 x86_64

**Issue description:**
Compiling custom export template from latest vanilla godot-2.6.1 release archive, getting following error:
`$ scons platform=android target=release android_arch=armv7
scons: Reading SConscript files ...
Godot Android!!!!! (armv7) (with neon)
Could not read source prop file '/home/moha/dev/bin/android/android-sdk/ndk-bundle/source.properties'
Using NDK deprecated headers
Could not read source prop file '/home/moha/dev/bin/android/android-sdk/ndk-bundle/source.properties'
scons: done reading SConscript files.
scons: Building targets ...
[Initial build] Compiling shared ==> platform/android/os_android.cpp
[Initial build] Compiling shared ==> platform/android/godot_android.cpp
[Initial build] Compiling shared ==> platform/android/file_access_android.cpp
[Initial build] Compiling shared ==> platform/android/dir_access_android.cpp
[Initial build] Compiling shared ==> platform/android/audio_driver_opensl.cpp
[Initial build] Compiling shared ==> platform/android/file_access_jandroid.cpp
[Initial build] Compiling shared ==> platform/android/dir_access_jandroid.cpp
[Initial build] Compiling shared ==> platform/android/thread_jandroid.cpp
[Initial build] Compiling shared ==> platform/android/audio_driver_jandroid.cpp
[Initial build] Compiling shared ==> platform/android/ifaddrs_android.cpp
[Initial build] Compiling shared ==> platform/android/android_native_app_glue.c
[Initial build] Compiling shared ==> platform/android/java_glue.cpp
[Initial build] Compiling shared ==> platform/android/cpu-features.c
[Initial build] Compiling shared ==> platform/android/java_class_wrapper.cpp
[Initial build] Linking Shared Library ==> bin/libgodot.android.opt.armv7.neon.so
/home/moha/dev/bin/android/android-sdk/ndk-bundle/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: cannot find -lc++
platform/android/ifaddrs_android.os:ifaddrs_android.cpp:function getifaddrs(ifaddrs**): error: undefined reference to 'operator new(unsigned int)'
platform/android/ifaddrs_android.os:ifaddrs_android.cpp:function getifaddrs(ifaddrs**): error: undefined reference to 'operator new[](unsigned int)'
platform/android/ifaddrs_android.os:ifaddrs_android.cpp:function getifaddrs(ifaddrs**): error: undefined reference to 'operator new(unsigned int)'
platform/android/ifaddrs_android.os:ifaddrs_android.cpp:function getifaddrs(ifaddrs**): error: undefined reference to 'operator new(unsigned int)'
platform/android/thread_jandroid.os:thread_jandroid.cpp:function ThreadAndroid::~ThreadAndroid(): error: undefined reference to 'operator delete(void*)'
platform/android/ifaddrs_android.os:ifaddrs_android.cpp:function getifaddrs(ifaddrs**): error: undefined reference to 'operator new(unsigned int)'
platform/android/file_access_jandroid.os:file_access_jandroid.cpp:function FileAccessJAndroid::~FileAccessJAndroid(): error: undefined reference to 'operator delete(void*)'
platform/android/ifaddrs_android.os:ifaddrs_android.cpp:function getifaddrs(ifaddrs**): error: undefined reference to 'operator delete[](void*)'
platform/android/ifaddrs_android.os:ifaddrs_android.cpp:function getifaddrs(ifaddrs**): error: undefined reference to 'operator delete(void*)'
platform/android/ifaddrs_android.os:ifaddrs_android.cpp:function getifaddrs(ifaddrs**): error: undefined reference to 'operator delete[](void*)'
platform/android/ifaddrs_android.os:ifaddrs_android.cpp:function getifaddrs(ifaddrs**): error: undefined reference to 'operator delete[](void*)'
platform/android/ifaddrs_android.os:ifaddrs_android.cpp:function freeifaddrs(ifaddrs*): error: undefined reference to 'operator delete[](void*)'
platform/android/file_access_android.os:file_access_android.cpp:function FileAccessAndroid::~FileAccessAndroid(): error: undefined reference to 'operator delete(void*)'
modules/libmodules.android.opt.armv7.neon.a(stream_peer_openssl.android.opt.armv7.neon.o):stream_peer_openssl.cpp:function StreamPeerOpenSSL::_cert_verify_callback(x509_store_ctx_st*, void*): error: undefined reference to 'stdout'
modules/libmodules.android.opt.armv7.neon.a(stream_peer_openssl.android.opt.armv7.neon.o):stream_peer_openssl.cpp:function StreamPeerOpenSSL::connect(Ref<StreamPeer>, bool, String const&): error: undefined reference to 'stdout'
drivers/libdrivers.android.opt.armv7.neon.a(os_unix.android.opt.armv7.neon.o):os_unix.cpp:function OS_Unix::initialize_core(): error: undefined reference to 'sigemptyset'
modules/libmodules.android.opt.armv7.neon.a(stream_peer_openssl.android.opt.armv7.neon.o):stream_peer_openssl.cpp:vtable for StreamPeerSSL: error: undefined reference to '__cxa_pure_virtual'
drivers/libdrivers.android.opt.armv7.neon.a(os_unix.android.opt.armv7.neon.o):os_unix.cpp:function OS_Unix::vprint(char const*, std::__va_list, bool): error: undefined reference to 'stderr'
modules/libmodules.android.opt.armv7.neon.a(stream_peer_openssl.android.opt.armv7.neon.o):stream_peer_openssl.cpp:vtable for StreamPeerSSL: error: undefined reference to '__cxa_pure_virtual'
drivers/libdrivers.android.opt.armv7.neon.a(os_unix.android.opt.armv7.neon.o):os_unix.cpp:function OS_Unix::vprint(char const*, std::__va_list, bool): error: undefined reference to 'stdout'
modules/libmodules.android.opt.armv7.neon.a(stream_peer_openssl.android.opt.armv7.neon.o):stream_peer_openssl.cpp:vtable for StreamPeerSSL: error: undefined reference to '__cxa_pure_virtual'
modules/libmodules.android.opt.armv7.neon.a(stream_peer_openssl.android.opt.armv7.neon.o):stream_peer_openssl.cpp:vtable for StreamPeerSSL: error: undefined reference to '__cxa_pure_virtual'
drivers/libdrivers.android.opt.armv7.neon.a(os_unix.android.opt.armv7.neon.o):os_unix.cpp:function OS_Unix::alert(String const&, String const&): error: undefined reference to 'stderr'
drivers/libdrivers.android.opt.armv7.neon.a(os_unix.android.opt.armv7.neon.o):os_unix.cpp:function OS_Unix::get_stdin_string(bool): error: undefined reference to '__FD_SET_chk'
drivers/libdrivers.android.opt.armv7.neon.a(os_unix.android.opt.armv7.neon.o):os_unix.cpp:function OS_Unix::get_stdin_string(bool): error: undefined reference to 'stdin'
drivers/libdrivers.android.opt.armv7.neon.a(os_unix.android.opt.armv7.neon.o):os_unix.cpp:function OS_Unix::get_stdin_string(bool): error: undefined reference to 'stdin'
drivers/libdrivers.android.opt.armv7.neon.a(os_unix.android.opt.armv7.neon.o):os_unix.cpp:function OS_Unix::execute(String const&, List<String, DefaultAllocator> const&, bool, long long*, String*, int*, bool): error: undefined reference to 'stderr'
drivers/libdrivers.android.opt.armv7.neon.a(tcp_server_posix.android.opt.armv7.neon.o):tcp_server_posix.cpp:function TCPServerPosix::listen(unsigned short, IP_Address): error: undefined reference to 'in6addr_any'
core/libcore.android.opt.armv7.neon.a(triangulator.android.opt.armv7.neon.o):triangulator.cpp:function TriangulatorPoly::Init(long): error: undefined reference to 'operator new[](unsigned int)'
drivers/libdrivers.android.opt.armv7.neon.a(packet_peer_udp_posix.android.opt.armv7.neon.o):packet_peer_udp_posix.cpp:function PacketPeerUDPPosix::listen(int, IP_Address, int): error: undefined reference to 'in6addr_any'
core/libcore.android.opt.armv7.neon.a(triangulator.android.opt.armv7.neon.o):triangulator.cpp:function TriangulatorPoly::operator=(TriangulatorPoly const&): error: undefined reference to 'operator new[](unsigned int)'
core/libcore.android.opt.armv7.neon.a(triangulator.android.opt.armv7.neon.o):triangulator.cpp:function TriangulatorPoly::SetOrientation(int): error: undefined reference to 'operator new[](unsigned int)'
drivers/libdrivers.android.opt.armv7.neon.a(rasterizer_gles2.android.opt.armv7.neon.o):rasterizer_gles2.cpp:function RasterizerGLES2::_render(RasterizerGLES2::Geometry const*, RasterizerGLES2::Material const*, RasterizerGLES2::Skeleton const*, RasterizerGLES2::GeometryOwner const*, Transform const&): error: undefined reference to '__cxa_guard_acquire'
drivers/libdrivers.android.opt.armv7.neon.a(rasterizer_gles2.android.opt.armv7.neon.o):rasterizer_gles2.cpp:function RasterizerGLES2::_render(RasterizerGLES2::Geometry const*, RasterizerGLES2::Material const*, RasterizerGLES2::Skeleton const*, RasterizerGLES2::GeometryOwner const*, Transform const&): error: undefined reference to '__cxa_guard_release'
drivers/libdrivers.android.opt.armv7.neon.a(rasterizer_gles2.android.opt.armv7.neon.o):rasterizer_gles2.cpp:function RasterizerGLES2::_render(RasterizerGLES2::Geometry const*, RasterizerGLES2::Material const*, RasterizerGLES2::Skeleton const*, RasterizerGLES2::GeometryOwner const*, Transform const&): error: undefined reference to '__cxa_guard_acquire'
drivers/libdrivers.android.opt.armv7.neon.a(rasterizer_gles2.android.opt.armv7.neon.o):rasterizer_gles2.cpp:function RasterizerGLES2::_render(RasterizerGLES2::Geometry const*, RasterizerGLES2::Material const*, RasterizerGLES2::Skeleton const*, RasterizerGLES2::GeometryOwner const*, Transform const&): error: undefined reference to '__cxa_guard_release'
drivers/libdrivers.android.opt.armv7.neon.a(rasterizer_gles2.android.opt.armv7.neon.o):rasterizer_gles2.cpp:function RasterizerGLES2::_render(RasterizerGLES2::Geometry const*, RasterizerGLES2::Material const*, RasterizerGLES2::Skeleton const*, RasterizerGLES2::GeometryOwner const*, Transform const&): error: undefined reference to '__cxa_guard_acquire'
drivers/libdrivers.android.opt.armv7.neon.a(rasterizer_gles2.android.opt.armv7.neon.o):rasterizer_gles2.cpp:function RasterizerGLES2::_render(RasterizerGLES2::Geometry const*, RasterizerGLES2::Material const*, RasterizerGLES2::Skeleton const*, RasterizerGLES2::GeometryOwner const*, Transform const&): error: undefined reference to '__cxa_guard_release'
drivers/libdrivers.android.opt.armv7.neon.a(rasterizer_gles2.android.opt.armv7.neon.o):rasterizer_gles2.cpp:function RasterizerGLES2::_render(RasterizerGLES2::Geometry const*, RasterizerGLES2::Material const*, RasterizerGLES2::Skeleton const*, RasterizerGLES2::GeometryOwner const*, Transform const&): error: undefined reference to '__cxa_guard_acquire'
drivers/libdrivers.android.opt.armv7.neon.a(rasterizer_gles2.android.opt.armv7.neon.o):rasterizer_gles2.cpp:function RasterizerGLES2::_render(RasterizerGLES2::Geometry const*, RasterizerGLES2::Material const*, RasterizerGLES2::Skeleton const*, RasterizerGLES2::GeometryOwner const*, Transform const&): error: undefined reference to '__cxa_guard_release'
modules/libmodules.android.opt.armv7.neon.a(video_stream_theora.android.opt.armv7.neon.o):video_stream_theora.cpp:function VideoStreamPlaybackTheora::set_file(String const&): error: undefined reference to 'stderr'
modules/libmodules.android.opt.armv7.neon.a(stream.android.opt.armv7.neon.o):stream.c:function op_fseek: error: undefined reference to 'fseeko64'
modules/libmodules.android.opt.armv7.neon.a(stream.android.opt.armv7.neon.o):stream.c:function op_ftell: error: undefined reference to 'ftello64'
modules/libmodules.android.opt.armv7.neon.a(ui_openssl.android.opt.armv7.neon.o):ui_openssl.c:function open_console: error: undefined reference to 'tcgetattr'
modules/libmodules.android.opt.armv7.neon.a(ui_openssl.android.opt.armv7.neon.o):ui_openssl.c:function open_console: error: undefined reference to 'stdin'
modules/libmodules.android.opt.armv7.neon.a(ui_openssl.android.opt.armv7.neon.o):ui_openssl.c:function close_console: error: undefined reference to 'stdin'
modules/libmodules.android.opt.armv7.neon.a(ui_openssl.android.opt.armv7.neon.o):ui_openssl.c:function read_string_inner: error: undefined reference to 'signal'
modules/libmodules.android.opt.armv7.neon.a(ui_openssl.android.opt.armv7.neon.o):ui_openssl.c:function read_string_inner: error: undefined reference to 'tcsetattr'
modules/libmodules.android.opt.armv7.neon.a(ui_openssl.android.opt.armv7.neon.o):ui_openssl.c:function read_string_inner: error: undefined reference to 'tcsetattr'
core/libcore.android.opt.armv7.neon.a(pck_packer.android.opt.armv7.neon.o):pck_packer.cpp:function PCKPacker::flush(bool): error: undefined reference to 'stdout'
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
scons: *** [bin/libgodot.android.opt.armv7.neon.so] Error 1
scons: building terminated because of errors.
`

**Steps to reproduce:**
`scons platform=android target=release android_arch=arm64v8`

**Comment by akien-mga** [comment] 2019-10-31 16:51
Note that it's 2.1.6, not 2.6.1.

You should use the latest `2.1` branch commit to have proper support for newer NDK. Alternatively you can use an older NDK version (I think `r16`-something should work for 2.1.6-stable).

**Comment by akien-mga** [comment] 2019-10-31 16:51
Duplicate of #30688

**Closed by akien-mga** 2019-10-31 16:51 UTC
