### ISSUE TITLE
Black screen shows up when a project is opened in godot.

### ISSUE THREAD

**Issue by Starboy10012011** [godotengine/godot#77313] opened 2023-05-21 15:58 UTC
### Godot version

4.3.stable

### System information

Windows 10, Intel Core i3-8130U, GL4.5, Intel UHD Graphics 620

### Issue description

When ever I am opening a project I only see a black screen, but the editor runs in the background. Can anyone help me with this problem.

### Steps to reproduce

Open the editor without having the black screen.

### Minimal reproduction project

N/A

**Comment by Starboy10012011** [comment] 2023-05-21 16:02
Can anyone help.

**Comment by AThousandShips** [comment] 2023-05-21 16:42
Please give things some time, this isn't a help desk but a big report tool where people will look when able

**Comment by Starboy10012011** [comment] 2023-05-22 06:57
> Please give things some time, this isn't a help desk but a big report tool where people will look when able, you gave it all of 5 minutes
> 
> If you want rapid responses turn to the other [community channels](https://godotengine.org/community)

Thank You

**Comment by KoBeWi** [comment] 2023-05-28 08:00
looks the same as #71104

**Comment by Calinou** [comment] 2023-06-09 19:15
- Duplicate of https://github.com/godotengine/godot/issues/71104 (same cause).

**Closed by Calinou** 2023-06-09 19:15 UTC
