### ISSUE TITLE
The first click on a link from the docs never works

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#30405] opened 2019-07-07 14:26 UTC
Godot 3.1.1
Windows 10 64 bits

In the script editor, the first time you click on a link from a newly opened doc tab, it never works. You have to click a second time.

**Comment by girng** [comment] 2019-07-08 06:51
glad i'm not the only who has been experiencing this.  thought my new mouse was screwing up again 😆

**Comment by Anutrix** [comment] 2019-07-08 08:17
Confirmed on 3.1.1 stable.
But issue not reproducible on latest master https://github.com/godotengine/godot/commit/3bfffcc568d87342e867f95c35a4a19e09072189.

**Comment by Ranoller** [comment] 2019-07-08 08:48
This was fixed in master some time ago.

**Comment by Ranoller** [comment] 2019-07-08 08:50
Duplicate of:
https://github.com/godotengine/godot/issues/27384
https://github.com/godotengine/godot/issues/27983
Closed by:
https://github.com/godotengine/godot/pull/28284

**Comment by Anutrix** [comment] 2019-07-08 11:24
Someone close this then.

**Closed** 2019-07-08 11:34 UTC
Labels: bug, topic:editor

**Comment by Ranoller** [comment] 2019-07-16 13:04
If 3.2 will be the stable branch of Godot 3 there is no needed to cherrypick to 3.1.1 
3.2 will superseded that... I think
