### ISSUE TITLE
apply_impulse resets rotation

### ISSUE THREAD

**Issue by imekon** [godotengine/godot#15001] opened 2017-12-24 10:08 UTC
**Godot version:** 

V3.0 beta 1 and 2

**OS/device including version:** 

Windows 10

**Issue description:**

Using rotation and apply_impulse no longer works. I rotated a ship then used apply_impulse to move it, however the rotation snapped back to 0. This used to work in V2.1.4

**Steps to reproduce:**

See here: https://godotengine.org/qa/21673/v3-0-beta2-how-to-make-apply_impulse-work-with-rotation

**Minimal reproduction project:**

[test3.zip](https://github.com/godotengine/godot/files/1584737/test3.zip)

- [x] I searched the existing [GitHub issues](https://github.com/godotengine/godot/issues?utf8=%E2%9C%93&q=is%3Aissue+) for potential duplicates.

**Comment by pwab** [comment] 2017-12-26 17:18
Despite from the fact that this could be a bug I wouldn't use `rotate()` on a RigidBody like that (as well as not setting the position by hand).

In your implementation you can use the `angular_velocity` parameter to get the same result. Like so:

```gdscript
extends RigidBody2D

const ROTATE_SPEED = 2
const ACCELERATION = 5

func rotate_ship(direction):
	angular_velocity = direction * ROTATE_SPEED

func _physics_process(delta):
	if Input.is_action_pressed("ui_left"):
		rotate_ship(-1)
	elif Input.is_action_pressed("ui_right"):
		rotate_ship(1)
	else:
		rotate_ship(0)

	if Input.is_action_pressed("ui_up"):
		apply_impulse(Vector2(), Vector2(0, -ACCELERATION).rotated(rotation))
```

**Adjusted your project accordingly:**
[issue_15001.zip](https://github.com/godotengine/godot/files/1587651/issue_15001.zip)

**Comment by imekon** [comment] 2017-12-26 18:33
That works!

**Comment by akien-mga** [comment] 2018-01-05 10:41
We have now entered release freeze for Godot 3.0 and want to focus only on release critical issues for that milestone. Therefore, we're moving this issue to the 3.1 milestone, though a fix may be made available for a 3.0.x maintenance release after it has been tested in the master branch during 3.1 development. If you consider that this issue is critical enough to warrant blocking the 3.0 release until fixed, please comment so that we can assess it more in-depth.

**Comment by juddrgledhill** [comment] 2018-08-13 17:04
I have the opposite problem and am not sure it is a bug, but thought I would ask here (I have asked elsewhere already). I have a ridigbody2d and am applying an impulse to it. At some point in my game, I want to reset that rigidbody2d to its initial, starting position. I get the position fine, but I cannot reset its rotation. Any ideas on that?

**Comment by pwab** [comment] 2018-08-14 06:44
Hey @juddrgledhill, I want to reproduce this behavior. Would you mind providing a minimal example project? Or could you at least describe how you reset the position and how you tried to reset the rotation?

**Comment by juddrgledhill** [comment] 2018-08-14 13:08
Hi @pwab I will try and do just that.

I fear that it is just a newb issue, but I have been trying for a while now... I was able to make a correction last night by saving the transform at start and setting it in the _integrate_forces call (on the body state object), but I should be able to set the rotation directly in that call, and not have to set the entire transform (that is why I think it might be a newb issue - because maybe that is how you "are supposed to" do it...?).

**Comment by pwab** [comment] 2018-08-15 07:30
So we are talking about a RigidBody in 3d space? (Just to keep it clear because the question was talking about RigidBody2D)

If you are resetting position **and** rotation why not using the transform? I was able to reset both without the `custom_integrator`. (I stumbled about a problem with the `custom_integrator` which I want to discuss in another issue [the referenced one])

It _shouldn't be done like that_ but you can use this approach:
```gdscript
var body_state

func _ready():
    body_state = $body.transform

func reset_body():
    $body.transform = body_state
```

Sample project: 
[issue15001.zip](https://github.com/godotengine/godot/files/2289500/issue15001.zip)

Just keep in mind that it is better to use the `custom_integrator`. If the referenced issue is solved I'll try to come back to your problem and solve it _"the right way"_.

**Comment by pwab** [comment] 2018-08-15 13:05
The bug with the `custom_integrator` seems to be fixed in current master. So you could use an alpha version, compile yourself or wait for the 3.1 release (if the fix isn't ported to the next stable release).

In the meantime your best bet would be to use the approach without utilizing the `_integrate_forces()`-function.

**Comment by juddrgledhill** [comment] 2018-08-15 15:48
Hi @pwab:

A rigidbody2d, not 3d.

I settled on the following approach, which is where you are...

```
func _remember_starting_state():
    _initial_transform = self.transform
```

Then in the middle, something like this happens in the _integrate_forces - an impulse gets applied when you bounce off of something:

```
func _physics_bounce(body_state):
    body_state.set_linear_velocity(self.linear_velocity * -1)
    self.apply_impulse(Vector2(10, 0), -(self.linear_velocity))
```


Then I timeout after bouncing around a little and do this:

```
func _reset_to_start(body_state): #reset everything to the beginning state
	body_state.set_transform(_initial_transform)
```

The issue I saw intially was that I could not address individual aspects of the transform. For instance, if I saved the global_rotation and then set the global_rotation, nothing would happen.

```
func _reset_to_start(body_state): #reset everything to the beginning state
	self.global_rotation = _initial_global_rotation
```

Is this a bug, or just user error? I thought I should be able to apply the rotation directly, but nothing seemed to happen.

Thanks.

**Comment by AndreaCatania** [comment] 2018-09-22 08:48
Change transform (translation / rotation) of a rigid body is not a wanted behaviour. You have to control position and rotation of rigid body using forces / torque / velocity / impulse.

**Closed by AndreaCatania** 2018-09-22 08:48 UTC
Labels: topic:physics
