### ISSUE TITLE
GPU Particles will crash in the macOS M1 chip.

### ISSUE THREAD

**Issue by whirlsyu** [godotengine/godot#74465] opened 2023-03-06 03:44 UTC
### Godot version

4.0-stable

### System information

macOS 13.1 (22C65)

### Issue description

GPU Particles will crash in the macOS M1 chip.

### Steps to reproduce

open godot, start a scene, and add GPU Particles.

### Minimal reproduction project

N/A

**Comment by clayjohn** [comment] 2023-03-06 06:39
Which renderer are you using? 

If it's the gl_compatibility renderer, then this is a duplicate of https://github.com/godotengine/godot/issues/72469

**Comment by whirlsyu** [comment] 2023-03-10 14:23
Yes, I am using gl_compatibility, this is a duplicate of https://github.com/godotengine/godot/issues/72469.
Then I wonder which renderer now is supported on macOS M1?

**Comment by akien-mga** [comment] 2023-03-10 14:41
All three renderers are supported on macOS. But supported doesn't mean bug free, especially with macOS's bitrotting OpenGL drivers.

Closing as duplicate of #72469.

**Closed by akien-mga** 2023-03-10 14:41 UTC
Labels: bug, platform:macos, crash, topic:particles
