### ISSUE TITLE
External editor causes Godot to not reload updated tool scripts

### ISSUE THREAD

**Issue by Lucrecious** [godotengine/godot#40027] opened 2020-07-01 17:36 UTC
**Godot version:**
3.2.2

**OS/device including version:**
I am using VSCode as an external editor with Godot.

When I use the external editor to edit a tool script and save, the tool script is not reloaded in the Godot editor whereas making the same edit in the Godot script editor does.

This makes the external editor unusable when editing tool scripts and forces use of the Godot editor when working on tool scripts.

Furthermore, Godot consistently gets script cycling errors when I switch from VSCode to the Godot editors.

The only workaround for this, as far as I know, is to restart the Godot editor completely, or disable the external editor and resave the tool script.

**Steps to reproduce:**
1. Make a Godot project
2. Add a scene with a tool script
3. Setup the external editor
4. Add an export variable to the tool script with a setter and getter
5. Print something in the setter
6. Switch to Godot and change the export variable with the UI

Expected: Print statement from the tool script
Actual: Nothing

**Minimal reproduction project:**
[external_editor_and_tool_script.zip](https://github.com/godotengine/godot/files/4859424/external_editor_and_tool_script.zip)

It would be nice to at least have a button that reloads all current tool scripts or something. Or maybe there is, is there?

**Comment by KoBeWi** [comment] 2020-07-06 10:17
Duplicate of #29379

**Closed by KoBeWi** 2020-07-06 10:17 UTC
