### ISSUE TITLE
OSX 10.10 crash on load project [Intel HD 3000]

### ISSUE THREAD

**Issue by Deph0** [godotengine/godot#19896] opened 2018-07-01 20:49 UTC
Godot Version: 3.0.4
Platform: OSX 10.10, Macbook air 2011, HD graphics 3000
```
$ ~/Applications/Godot.app/Contents/MacOS/Godot --verbose -e
arguments
0: /Users/*/Applications/Godot.app/Contents/MacOS/Godot
1: --verbose
2: -e
Current path: /Users/*/Applications/Godot.app/Contents/Resources
Using GLES3 video driver
OpenGL ES 3.0 Renderer: Intel HD Graphics 3000 OpenGL Engine
CoreAudio: detected 2 channels
CoreAudio: audio buffer frames: 512 calculated latency: 11ms
CORE API HASH: -1284725728439888228
EDITOR API HASH: -1018107378756857066
load resource: /Users/*/Library/Application Support/Godot/editor_settings-3.tres
EditorSettings: Load OK!
EditorSettings Save OK!
OPENING: /Users/*/GoDotProjects/NewGameProject (::Users::*::GoDotProjects::NewGameProject)
arguments
0: /Users/*/Applications/Godot.app/Contents/MacOS/Godot
1: --path
2: /Users/*/GoDotProjects/NewGameProject
3: --editor
Current path: /Users/*/Applications/Godot.app/Contents/Resources
EditorSettings Save OK!
OpenGL ES 3.0 Renderer: Intel HD Graphics 3000 OpenGL Engine
handle_crash: Program crashed with signal 11
Dumping the backtrace. Please include this when reporting the bug on https://github.com/godotengine/godot/issues
[1] 1   libsystem_platform.dylib            0x00007fff968f4f1a _sigtramp + 26
[2] 2   ???                                 0x00007fc01b0aeae0 0x0 + 140463064148704
[3] GHAL3D::ISAScheduler::CDependenceDAG::AddNodeEdges(GHAL3D::ISAScheduler::CDagNode*, GHAL3D::ISAScheduler::CDagNode*)
[4] GHAL3D::ISAScheduler::CDependenceDAG::Build()
[5] GHAL3D::ISAScheduler::CScheduler::Schedule()
[6] GHAL3D::CGen4CodeGeneratorContext::LocalScheduling(GHAL3D::CShader const*, GHAL3D::SKernelCompilerControls const&)
[7] GHAL3D::CGen6PixelShaderKernelProgram::LocalScheduling()
[8] GHAL3D::CGen6PixelShaderKernelProgram::Build()
[9] GHAL3D::CGen6PixelShaderKernelProgram::Create(void const*, PLATFORM_STR, S3DKernelHardwareCapabilities const&, GHAL3D::CPixelShader const*, GHAL3D::SGen6PixelShaderKernelProgramCacheKey const*, GHAL3D::CGen6PixelShaderKernelProgram*&)
[10] GHAL3D::CGen6PixelShaderKernelProgramCacheData::Initialize()
[11] GHAL3D::CGen6PixelShaderKernelProgramCacheData::Create(GHAL3D::CStateProcessorCache*, GHAL3D::SGen6PixelShaderKernelProgramCacheKey const&, GHAL3D::CGen6PixelShaderKernelProgramCacheData*&)
[12] GHAL3D::CStateCache<GHAL3D::SGen6PixelShaderKernelProgramCacheKey, GHAL3D::CGen6PixelShaderKernelProgramCacheData>::AllocateData(GHAL3D::SGen6PixelShaderKernelProgramCacheKey const&, GHAL3D::HANDLE_TYPE&)
[13] GHAL3D::CGen6StateProcessorCache::GetPixelShaderKernelProgram()
[14] GHAL3D::CGen6PrivateStateProcessor::BindIndirectState()
[15] GHAL3D::CGen6PrivateStateProcessor::BindPipeline()
[16] 16  AppleIntelHD3000GraphicsGLDriver    0x000000010d546222 glrAppleSyncState + 80
[17] 17  AppleIntelHD3000GraphicsGLDriver    0x000000010d866b4e glrRenderVertexArray + 1010
[18] 18  GLEngine                            0x00007fff89f8f7b9 glDrawArrays_GL3Exec + 258
[19] RasterizerSceneGLES3::_render_geometry(RasterizerSceneGLES3::RenderList::Element*) (in Godot) + 2417
[20] RasterizerSceneGLES3::_render_list(RasterizerSceneGLES3::RenderList::Element**, int, Transform const&, CameraMatrix const&, unsigned int, bool, bool, bool, bool, bool) (in Godot) + 6895
[21] RasterizerSceneGLES3::render_scene(Transform const&, CameraMatrix const&, bool, RasterizerScene::InstanceBase**, int, RID*, int, RID*, int, RID, RID, RID, RID, int) (in Godot) + 3497
[22] VisualServerScene::_render_scene(Transform, CameraMatrix const&, bool, RID, unsigned int, RID, RID, RID, int) (in Godot) + 4463
[23] VisualServerScene::render_camera(RID, RID, Vector2, RID) (in Godot) + 471
[24] VisualServerViewport::_draw_viewport(VisualServerViewport::Viewport*, ARVRInterface::Eyes) (in Godot) + 560
[25] VisualServerViewport::draw_viewports() (in Godot) + 749
[26] VisualServerRaster::draw(bool) (in Godot) + 97
[27] Main::iteration() (in Godot) + 992
[28] ProgressDialog::task_step(String const&, String const&, int, bool) (in Godot) + 387
[29] EditorFileSystem::reimport_files(Vector<String> const&) (in Godot) + 1362
[30] EditorFileSystem::_update_scan_actions() (in Godot) + 2050
[31] EditorFileSystem::_notification(int) (in Godot) + 1496
[32] EditorFileSystem::_notificationv(int, bool) (in Godot) + 76
[33] Object::notification(int, bool) (in Godot) + 22
[34] SceneTree::_notify_group_pause(StringName const&, int) (in Godot) + 457
[35] SceneTree::idle(float) (in Godot) + 394
[36] Main::iteration() (in Godot) + 855
[37] OS_OSX::run() (in Godot) + 402
[38] main (in Godot) + 832
[39] 39  libdyld.dylib                       0x00007fff909e35c9 start + 1
[40] 40  ???                                 0x0000000000000004 0x0 + 4
-- END OF BACKTRACE --

```
This happens when i try to load a project, or create a new blank project and loading it.
I can't quite tell what this is caused by, but i know apple has some terrible OpenGL drivers from past games and rendering tools, could be related?

**Comment by CarlGustavAlbertDwarfsteinYung** [comment] 2018-07-02 03:48
Is possible IntelHD3000 does not support OpenGL ES 3.0

**Comment by CarlGustavAlbertDwarfsteinYung** [comment] 2018-07-02 03:49
3.1 alpha is gonna come out sometimes soon and it should have a backport to OpenGL ES 2.0 it should work you could try again with the alpha version.

**Comment by vnen** [comment] 2018-07-02 05:57
Well, it supposedly supports OpenGL 3.3, but Apple drivers are really bad for OpenGL support.

**Comment by stonekase** [comment] 2018-07-16 16:00
That issue can be attributed to a bad access.I have raised this as an issue and has been ignored by the Godot developers.I went as far as getting the offensive .cpp file but was still ignored.

**Comment by akien-mga** [comment] 2018-07-17 07:46
> That issue can be attributed to a bad access.I have raised this as an issue and has been ignored by the Godot developers.I went as far as getting the offensive .cpp file but was still ignored.

Your issue has a different backtrace, so no, it's not related. And nobody is ignoring you, we're just not able to fix all issues magically by a snap of our fingers, especially when only one person can trigger them, which is points at a system-specific issue.

**Comment by reduz** [comment] 2018-09-07 18:49
Intel HD3000 is not supported, use GLES2 backend. GLES3 backend will be removed on next version.

**Comment by ImperatorS79** [comment] 2019-03-18 08:37
Hello, I also have a HD graphics 3000, on windows 7, OpenGL 3.1.
I tried to launch the Wesnoth's Godot demo, it worked in Godot 3.1 beta 7, but not in stable.
Here are the console outputs:
- beta 7 :
```
OpenGL ES 2.0 Renderer: Intel(R) HD Graphics 3000
ERROR: initialize: Directional shadow framebuffer status invalid
   At: drivers/gles2/rasterizer_scene_gles2.cpp:3250
```
- stable when godot start:
```
OpenGL ES 2.0 Renderer: Intel(R) HD Graphics 3000
ERROR: initialize: Directional shadow framebuffer status invalid
   At: drivers/gles2/rasterizer_scene_gles2.cpp:3355
```
- stable after launching project
```
ERROR: is_viable: Error initializing GLAD
   At: drivers/gles3/rasterizer_gles3.cpp:142
```

**Comment by akien-mga** [comment] 2019-04-03 07:07
@ImperatorS79 That's because your hardware does not support GLES3. You should advise the wesnoth devs to switch their rendering backend to GLES2, as it makes more sense for a 2D game if they want to aim for maximum compatibility.

It used to work for you because Godot would automatically fall back to GLES2 when GLES3 is unsupported, but that feature was made opt-in as it's not a 1:1 compatibility fallback, so it should only be used knowingly.

**Comment by akien-mga** [comment] 2019-08-12 06:40
@Deph0 Can you still reproduce this issue in Godot 3.1.1 or a nightly build of the master branch (see https://hugo.pro/projects/godot-builds/)?

**Comment by ImperatorS79** [comment] 2019-08-12 11:04
For what it is worth, I do not have any error when starting Godot with that version. Still, when launching Wesnoth's Godot version and explicitly requiring GLES2 in the editor, I still get the following error:
```
Godot Engine v3.2.dev.calinou.82a86e807 - https://godotengine.org
ERROR: is_viable: Error initializing GLAD
   At: drivers/gles3/rasterizer_gles3.cpp:141
ERROR: _get_socket_error: Socket error: 10054
   At: drivers/unix/net_socket_posix.cpp:197
```
I recall that, despite the error at launch, I was able to launch the project in Godot 3.1 beta 11 (last working beta).

**Comment by akien-mga** [comment] 2019-08-12 11:09
> Still, when launching Wesnoth's Godot version and explicitly requiring GLES2 in the editor, I still get the following error:

> ERROR: is_viable: Error initializing GLAD
   At: drivers/gles3/rasterizer_gles3.cpp:141

As you can see from the error, it's not using GLES2 but GLES3. To use GLES2 you should select GLES2 in the Project Settings. If your hardware doesn't support GLES2 and the project is GLES3, the editor with fall back to GLES2 and show it in the top right corner, but that's only for the editor instance, it doesn't impact the project config.

**Comment by ImperatorS79** [comment] 2019-08-12 11:56
And how can I modify this? Should it be a setting in project.godot, or another file? Should not Godot fallback to GLES2 at runtime automatically (if possible)?

**Comment by Zireael07** [comment] 2019-08-12 12:02
Godot used to fallback automatically, but that was disabled because especially in 3D, there is a LOT of difference between the two renderers in the feature set.

**Comment by ImperatorS79** [comment] 2019-08-12 12:04
Ok, I found the options hidden in the general parameters, and it works. Thanks for the infos !

**Comment by akien-mga** [comment] 2020-01-07 14:45
Closing as we can't support these old chipsets with GLES3. They should work properly when switched to GLES2.
Ideally these chipsets should not even advertise OpenGL 3.3 support - feel free to say so to the GPU drivers vendors, who might decide to drop nominal 3.3 support to be closer to the reality of what they *do* support properly.

**Closed by akien-mga** 2020-01-07 14:45 UTC
Labels: bug, platform:osx, topic:rendering
