### ISSUE TITLE
Animations not looping on inherited scenes from a 3D gltf animated mesh

### ISSUE THREAD

**Issue by BlueCatGamess** [godotengine/godot#67646] opened 2022-10-19 21:11 UTC
### Godot version

3.5.1 stable

### System information

Windows 10, GLES3, GEFORCE MX150

### Issue description
 related to  #34394

In inherited scenes from animated 3D meshes, animations won't loop at runtime even though I set the animations to loop on the animation player. The animation does loop in the editor, the problem is only in-game.

I follow the steps to import animations in separated files and check the keep_custom tracks box, but the problem persists.

### Steps to reproduce

Import a .glb or .fbx rigged and animated mesh in Godot
Create a new inherited scene from the imported mesh
Select the animation player and set an animation to autoplay and loop
Create a scene to see the character in the game
Play the game
The animation doesn't loop. The looping setting is properly saved in the inherited scene: if you set the animated mesh scene to "Editable children" in the game scene, you'll see the looping option is still checked on the AnimationPlayer.

Note that if you clear the inheritance on the animated character, looping will then work as expected.

**Comment by Calinou** [comment] 2022-10-19 22:14
Duplicate of https://github.com/godotengine/godot/issues/34394. Please don't open new issues for bugs that already have an issue :slightly_smiling_face:

**Closed by Calinou** 2022-10-19 22:14 UTC
