### ISSUE TITLE
Shader Graph - Deleting a node in the node editor auto-selects and auto-moves another node.

### ISSUE THREAD

**Issue by Ace-Dragon** [godotengine/godot#4433] opened 2016-04-25 03:03 UTC
**Operating system or device:**
Win10 64 bit; 24 gigs RAM; third-gen i7 CPU; ATI HD 7xxx GPU

**Issue description** **(what happened, and what was expected):**
When deleting a node in the visual node editor, the editor will often auto-grab another node and move it with the cursor. This is not desired and noticeably impacts usability.

**Steps to reproduce:**
Open the example file, open the node tree for the material, select a node, delete the node. Notice how another one automatically sticks to your cursor for no apparent reason.

**Link to minimal example project** **(optional but very welcome):**
[Bugs.zip](https://github.com/godotengine/godot/files/233840/Bugs.zip)

**Comment by hetdegon** [comment] 2016-04-27 12:37
You mean the visual shader editor? I've gotten this issue before as well, but I wasn't able to replicate consistently. I can now, though.

**Comment by mattiascibien** [comment] 2016-05-04 10:02
I actually replicated this using lastest master. When clicking on the x the second time you delete a node you get the node attached to the left in dragging mode.

**Comment by vnen** [comment] 2016-06-17 01:08
I cannot reproduce this issue.

**Comment by djrm** [comment] 2016-07-01 03:52
i am also unable to reproduce this one maybe it was fixed with #5308

**Comment by akien-mga** [comment] 2016-07-01 05:34
Closing then.

**Comment by rgrams** [comment] 2016-08-04 18:33
@akien-mga This bug is alive and well in 2.1 RC2

![shadergraph delete node issue](https://cloud.githubusercontent.com/assets/11370192/17413698/4c705894-5a50-11e6-94d1-e074d2fd33b4.gif)

**Comment by neikeq** [comment] 2016-08-04 18:42
I can reproduce this too. It doesn't always happens, you must try it multiple times. At least in my case. It also happens after adding new nodes.

**Comment by vnen** [comment] 2016-08-04 21:13
I also noticed this when playing with the visual scripting.

**Comment by hetdegon** [comment] 2016-08-05 03:15
I noticed it almost immediately when trying out the visual scripting thingy as well.

**Comment by bojidar-bg** [comment] 2016-08-05 06:23
Confirmed in the same circumstances.

**Comment by akien-mga** [comment] 2016-08-05 10:36
Can't check now, but I'm pretty sure we've got one or two recent duplicates of this issue.

**Comment by neikeq** [comment] 2016-08-05 11:04
@akien-mga I found #3568

**Comment by bojidar-bg** [comment] 2016-08-05 11:10
I found https://github.com/godotengine/godot/issues/4869

**Comment by quantum-entangler** [comment] 2016-09-06 13:48
This issue has existed for me since shadergraph was first introduced. I don't think theres been 1 build I've used where this wasn't an issue.

**Comment by akien-mga** [comment] 2016-10-03 19:48
I can't seem to reproduce anymore in the master branch, it might have been fixed while work was being done on the visual script editor. Can anyone confirm?

**Comment by volzhs** [comment] 2016-10-04 05:03
I can reproduce in current master head.
A random node is selected when adding, deleting nodes in Shader graph editor.
And also, strange random selection happens when changing `b` value with `Scalar+Vector Operator`

**Closed** 2016-10-09 12:35 UTC
Labels: bug, confirmed, hacktoberfest, topic:editor, usability
