### ISSUE TITLE
Popups/windowdialogs steal focus from sub-controls which pop up over them

### ISSUE THREAD

**Issue by jslater89** [godotengine/godot#7249] opened 2016-12-05 15:40 UTC
**Operating system or device - Godot version:**
Linux Mint 18 x64, Godot 2.1.1.stable.official

**Issue description** (what happened, and what was expected):
In the example project, an OptionButton is placed in a PopupPanel. Below it are several other UI controls. The PopupPanel is displayed with show() and is exclusive. (The bug also occurs with popup() and non-exclusive popups.) When the OptionButton is clicked, it displays its item list. Clicks on the item list above the PopupPanel's other UI controls are delivered to those controls instead of the OptionButton's item list. Expected behavior is that the OptionButton's item list will receive the clicks, since it is the top item.

This issue appears to be a general issue with any stacked popup. In a more complicated project, I have a windowdialog which displays above another windowdialog. Clicks to the top windowdialog are delivered preferentially to any clickable UI control in the bottom windowdialog, rather than to the top windowdialog as would be expected.

**Steps to reproduce:**
 1. Create a popup of some kind.
 2. To the first popup, add another popup.
 3. To the first popup, add some additional UI controls.
 4. Display the first popup, then display the second popup.
 5. Observe that clicks on the second popup, when they occur above the first popup's controls, are delivered to the first popup's controls instead of the second popup.

**Demo project:**
This project contains a minimal demo of the issue. Click the OptionButton and notice that clicking on the first few items is impossible, since the clicks go to the CheckBox and Button beneath the item list.
[BugDemo.zip](https://github.com/godotengine/godot/files/631502/BugDemo.zip)

**Comment by bojidar-bg** [comment] 2016-12-05 15:54
With three window dialogs on top of each other, which one receives the clicks?

**Comment by jslater89** [comment] 2016-12-05 16:11
In both the cases I can think of (where there are two popup windows with option buttons as siblings under a common parent, and where there are two popup windows, one of which is a child of the other), the topmost popup beneath the popup which demonstrates the bug receives clicks.

Further testing suggests that not all controls demonstrate this bug. Controls which I have observed allowing clicks through to the component below include ItemLists (in a WindowDialog on top of another WindowDialog; the bottom WindowDialog receives the clicks) and the item selection portion of OptionButtons.

[ParentChild.zip](https://github.com/godotengine/godot/files/631600/ParentChild.zip)
[Siblings.zip](https://github.com/godotengine/godot/files/631599/Siblings.zip)

**Comment by Noshyaar** [comment] 2018-04-08 03:50
First of all thank you for your report and sorry for the delay.

We released Godot 3.0 in January 2018 after 18 months of work, fixing many old issues either directly, or by obsoleting/replacing the features they were referring to.

We still have hundreds of issues whose relevance/reproducibility needs to be checked against the [current stable version](https://godotengine.org/download), and that's where you can help us.
**Could you check if the issue that you described initially is still relevant/reproducible in Godot 3.0 or any newer version, and comment about it here?**

For bug reports, please also make sure that the issue contains detailed steps to reproduce the bug and, if possible, a zipped project that can be used to reproduce it right away. This greatly speeds up debugging and bugfixing tasks for our contributors.

Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

Thanks in advance.

*Note: This message is being copy-pasted to many "stale" issues (90+ days without activity). It might happen that it is not meaningful for this specific issue or appears oblivious of the issue's context, if so please comment to notify the Bugsquad about it.*

**Comment by akien-mga** [comment] 2019-04-15 14:13
> Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

As there was no update since the previous post, we close this issue.

If it is still relevant in the way it was described and discussed above, please comment to ask for it to be reevaluated. If it is only partly relevant, or if the original issue has changed, it would be better to open a new issue (potentially referring to this one) focused on the current state.

**Closed by akien-mga** 2019-04-15 14:13 UTC
Labels: bug, topic:core
