### ISSUE TITLE
OGG playback errors printed occasionally when stopping specific OGG file near the end in audio preview dialog

### ISSUE THREAD

**Issue by lufog** [godotengine/godot#59348] opened 2022-03-20 12:19 UTC
### Godot version

v4.0.beta8.official (45cac42c0), v4.0.beta.custom_build (62a508276)

### System information

Windows 11, Forward+, GeForce GTX 1660 (527.56)

### Issue description

When you ~stop~ pause an audio file near the end, Godot crashes.

<details>
  <summary>console output</summary>
  
  ```cmd
Godot Engine v4.0.beta8.official.45cac42c0 - https://godotengine.org
Vulkan API 1.3.224 - Using Vulkan Device #0: NVIDIA - NVIDIA GeForce GTX 1660

ERROR: Condition "p_points.size() < 2" is true.
   at: canvas_item_add_multiline (servers/rendering/renderer_canvas_cull.cpp:1077)
WARNING: ran out of packets in stream
     at: _mix_frames_vorbis (modules/vorbis/audio_stream_ogg_vorbis.cpp:152)
ERROR: Condition "mixed < 0" is true. Returning: 0
   at: _mix_internal (modules/vorbis/audio_stream_ogg_vorbis.cpp:62)
ERROR: Index p_index = 13 is out of bounds (size() = 13).
   at: get (./core/templates/cowdata.h:155)
```
</details>

### Steps to reproduce

https://user-images.githubusercontent.com/10379487/159160668-88ab07c0-b986-47b9-b0fd-20d3b16712d1.mp4

### Minimal reproduction project

[StopSoudCrashTest_G4.zip](https://github.com/godotengine/godot/files/8311149/StopSoudCrashTest_G4.zip)

**Comment by KoBeWi** [comment] 2022-03-20 16:14
There is no crash stack trace, I only see this printed:
```
WARNING: Burning negative samples doesn't make sense. Check seek algorithm.
     at: AudioStreamPlaybackOGGVorbis::seek (modules\vorbis\audio_stream_ogg_vorbis.cpp:257)
WARNING: ran out of packets in stream
     at: AudioStreamPlaybackOGGVorbis::_mix_frames_vorbis (modules\vorbis\audio_stream_ogg_vorbis.cpp:90)
ERROR: Index p_index = 11 is out of bounds (size() = 11).
   at: CowData<class Vector<class Vector<unsigned char> > >::get (C:\godot_source\core/templates/cowdata.h:163)
```

**Comment by gustavi** [comment] 2022-03-29 21:30
@KoBeWi I can reproduce the "WARNING: Burning negative samples doesn't make sense. Check seek algorithm." with deterministic code (`audio_stream_player.play(9.29599952697754)`. Is that a bug?

**Comment by KoBeWi** [comment] 2022-03-29 21:47
If it doesn't involve user error (like wrong usage, corrupted file etc.) then it's a bug.

**Comment by NiclasEriksen** [comment] 2022-05-18 11:08
I get the same warnings, Linux / Vulkan / AMD 6600x.

It happens in my dynamic music system, where I seek on the next track to the position of the current playing one before cross-fading (Tween). There is no noticeable effects other than the warning being printed, the audio transitions smoothly and in sync. All tracks are of exactly equal length when exported, but I can't be sure that there aren't discrepancies anyway in how the audio is handled.

```swift
var t = get_track(current_track)
var sp = t.get_playback_position()
var nt = get_track(next)

nt.play()
nt.seek(sp)
last_track = current_track

reset_tweens()
fade_tween_current.tween_property(tracks[current_track], "volume", -80.0, crossfade_time)
fade_tween_next.tween_property(tracks[next], "volume", 0.0, crossfade_time)
current_track = next

$StopTimer.start(crossfade_time)  # stop() on the last track on timeout
```

**Comment by akien-mga** [comment] 2023-01-19 21:13
I can't reproduce this issue in 4.0 beta 13. Can you confirm that it's fixed?

**Comment by KoBeWi** [comment] 2023-01-19 21:16
Can't reproduce either. OGGs got new import dialog, so this could've fixed it.

**Comment by lufog** [comment] 2023-01-20 09:13
Can reproduce it on v4.0.beta13.official [caacade56]:

https://user-images.githubusercontent.com/10379487/213658529-28f3e639-be53-48f6-bff9-3046a2bb18e8.mp4

**Comment by lufog** [comment] 2023-01-20 09:28
Sorry for the false warning, this bug has indeed been fixed in master. Apparently, the fix didn't make it into beta13. From now on, I will try to check first on the latest dev builds.

**Comment by akien-mga** [comment] 2023-01-20 10:05
The `page_cursor` error was indeed added with #71314 which would prevent the crash.

I couldn't reproduce the crash with 4.0 beta 13 when testing a dozen times, but today I managed to trigger it after another dozen attempts. So I'm not sure this one specifically is about the OGG file being corrupted (unlike #67446), so let's keep it open to investigate why these errors come up in a seemingly random way.

**Comment by MJacred** [comment] 2023-05-10 19:43
As @ellenhp mentioned [here](https://github.com/godotengine/godot/issues/64775#issuecomment-1427145947), `the seek algorithm isn't sample accurate. The sample burning code is also wrong`, which confirms some, if not all, errors

**Comment by MJacred** [comment] 2023-08-24 16:25
Can confirm on Godot 4.1.1 on Ubuntu 20.04

```
modules/vorbis/audio_stream_ogg_vorbis.cpp:332 - Burning negative samples doesn't make sense. Check seek algorithm.
modules/vorbis/audio_stream_ogg_vorbis.cpp:153 - ran out of packets in stream
modules/vorbis/audio_stream_ogg_vorbis.cpp:63 - Condition "mixed < 0" is true. Returning: 0
modules/ogg/ogg_packet_sequence.cpp:140 - Condition "page_cursor >= ogg_packet_sequence->page_data.size()" is true. Returning: false
modules/vorbis/audio_stream_ogg_vorbis.cpp:153 - ran out of packets in stream
modules/vorbis/audio_stream_ogg_vorbis.cpp:63 - Condition "mixed < 0" is true. Returning: 0
modules/ogg/ogg_packet_sequence.cpp:140 - Condition "page_cursor >= ogg_packet_sequence->page_data.size()" is true. Returning: false
```

**Will be fixed, if PR https://github.com/godotengine/godot/pull/80452 is merged** (tested it couple dozen times).

**Closed** 2023-10-13 20:46 UTC
Labels: bug, confirmed, topic:audio
