### ISSUE TITLE
Can't use tilemap with shader

### ISSUE THREAD

**Issue by Torguen** [godotengine/godot#47565] opened 2021-04-02 12:46 UTC
**Godot version:**

3.3 rc7 mono

**OS/device including version:**

win10 64

**Issue description:**

Godot does not allow tiles to be placed in a tilemap node that has a shader enabled.
Notice the gif, the node that has a shader does not show the tiles window so that you can put tiles in the tilemap.
The node with the shader also has its tileset defined.

![behavior1](https://user-images.githubusercontent.com/19652075/113416624-031b6e80-93c2-11eb-842d-f63b59ff1c07.gif)

**Steps to reproduce:**
Add two tilemap nodes.
Set your tileset on both nodes.
Add a shader to one of the nodes.
The node with the shader will not allow writing to the tilemap.

**Minimal reproduction project:**

[testTilmap.zip](https://github.com/godotengine/godot/files/6249567/testTilmap.zip)

**Comment by Calinou** [comment] 2021-04-02 13:06
Duplicate of https://github.com/godotengine/godot/issues/32002.

**Closed by Calinou** 2021-04-02 13:06 UTC

**Comment by Torguen** [comment] 2021-04-02 13:09
Will it be fixed in 4? :(

**Comment by Calinou** [comment] 2021-04-02 13:21
> Will it be fixed in 4? :(

Yes, if https://github.com/godotengine/godot/pull/45085 is merged.

**Comment by Torguen** [comment] 2021-04-02 14:12
Ok, I think you can "skip" this problem.
You just have to create the tilemap without the shader, then, once the tilemap is created and does not need to be modified, then add the shader.
