### ISSUE TITLE
C# error during a RPC call

### ISSUE THREAD

**Issue by Scozor** [godotengine/godot#23969] opened 2018-11-25 19:16 UTC
**Godot version:**

**OS/device including version:**

**Issue description:**
When I try to use the RPC method, I get an error.
Yet the connection is well established

```
    // in _Ready
    GetTree().Connect("connected_to_server", this, "ConnectedOnServer");

    public void ConnectedOnServer()
    {
        myInfo["ID"] = GetTree().GetNetworkUniqueId();
        Rpc("RegisterPlayer", GetTree().GetNetworkUniqueId(), myInfo);
    }

    [Remote]
    public void RegisterPlayer(int id, Godot.Dictionary<string, object> info)
    {
        joueurs.Add(info);

        if(GetTree().IsNetworkServer())
        {
            //...
        }
    }

```
```
Nothing read: No such file or directory
ERROR: read: Server disconnected!

   At: drivers/windows/stream_peer_tcp_winsock.cpp:203
```

**Comment by akien-mga** [comment] 2019-02-23 14:12
Is this still reproducible in the current master branch or latest beta build?

**Comment by akien-mga** [comment] 2019-02-25 16:56
CC @Faless

**Comment by Faless** [comment] 2019-02-25 17:38
Not sure what the problem is.
The error `At: drivers/windows/stream_peer_tcp_winsock.cpp:203` it's the usual editor debugger getting disconnected (TCP).
The issue lacks reproductions steps/project.
The issue lacks of explanation of what happens next (crash?, networking not working?, editor debugger not working?, ecc).

**Comment by Faless** [comment] 2019-02-25 17:41
The issue also do not include the Godot version, which is either `3.0` or (unlikely) `3.1` before #21692

**Comment by neikeq** [comment] 2019-02-25 19:29
@Scozor Can you provide an example project where this can be reproduced?

**Comment by akien-mga** [comment] 2020-01-09 08:54
No answer, so closing.

**Closed by akien-mga** 2020-01-09 08:54 UTC
Labels: bug, topic:mono
