### ISSUE TITLE
[BUG] Shader glitch when using stretch_mode=VIEWPORT

### ISSUE THREAD

**Issue by FEDE0D** [godotengine/godot#2342] opened 2015-08-06 21:36 UTC
![shader_glitch](https://cloud.githubusercontent.com/assets/6296184/9124022/f3e0e310-3c69-11e5-97f2-f438b185e637.png)

When using the stretch mode "viewport" and stretching the screen, the shader fails and shows some weird glitch on the screen instead.

I also noticed that some UI elements gets chopped in half or doesn't show at all (inputs still work).
You can test this issue in the demo "screen_space_shaders" and changing the stretch mode to viewport.

PS: this also happens in android. It's not priority but it would be great to have fixed.

**Comment by akien-mga** [comment] 2015-11-01 22:28
Closing as a duplicate of #1571.

**Closed by akien-mga** 2015-11-01 22:28 UTC
Labels: archived
