### ISSUE TITLE
Alpha depth draw rendering issue on android

### ISSUE THREAD

**Issue by Tobi-La** [godotengine/godot#24261] opened 2018-12-10 14:21 UTC
**Godot version:**
v3.1.alpha.calinou.bf59b73
Tested with GLES2 and GLES3

**OS/device including version:**
Windows 10
Oukitel K6000 Pro
Samsung Galaxy S7

**Issue description:**
I experience some rendering issues on android with custom materials. It looks like the depth drawing isn't correctly done. It leads to meshes weirdly drawn or not being drawn at all.

Because I can't upload my main project here I created a minimal project. In this project, there is the issue that the given object isn't even rendered on android.

Windows 10:
![windows2](https://user-images.githubusercontent.com/25849067/49738200-12c19700-fc8f-11e8-9172-66eef6df481d.PNG)

Android:
![screenshot_20181210-131632_alphaissue](https://user-images.githubusercontent.com/25849067/49738221-1ce39580-fc8f-11e8-8c2a-f94d33f31b24.jpg)

**Steps to reproduce:**
Create a mesh instance with a shader material. Use the shader material to make some pixels use ALPHA and some not. It looks fine on windows, on Android, there are often rendering problems

**Minimal reproduction project:**
[AlphaIssue.zip](https://github.com/godotengine/godot/files/2663467/AlphaIssue.zip)

**Comment by CptPotato** [comment] 2018-12-10 14:46
duplicate of #23997?

**Comment by Tobi-La** [comment] 2018-12-10 15:52
Can't say for sure, so I created a new one. This one is for Godot 3.1 and gles2, so it's way more relevant than godot 3.0 with only supporting gles3, which isn't used much on mobile anyway

**Comment by reduz** [comment] 2019-01-26 18:06
I will give a check to this one very soon, but given many issues were fixed in GLES2, I would appreciate ensuring it remains broken in both GLES2 and GLES3.

**Comment by volzhs** [comment] 2019-01-26 18:34
These are what I got with gles 2 b203f80df

Ubuntu 18.10
![screenshot_20190127_033207](https://user-images.githubusercontent.com/8281454/51791298-395a7380-21e4-11e9-9ec2-fd9ff27ac1b0.png)

Android 8.0 / Galaxy s8+
![screenshot_20190127-033037_alphaissue](https://user-images.githubusercontent.com/8281454/51791305-5000ca80-21e4-11e9-9263-84348b4897c0.jpg)

**Comment by Tobi-La** [comment] 2019-02-11 07:49
@reduz Did you have the chance to look into it already? If there is something I can do to help let me know :)

**Comment by reduz** [comment] 2019-02-23 20:56
The error was actually a problem with the shader parser not detecting invalid implicit int -> float conversion.
This worked on desktop because drivers are very permissive there, but failed on mobile because they are strict there instead.

You shader will now fail to compile, so you will have to fix it.

**Closed** 2019-02-23 20:57 UTC
Labels: bug, platform:android, topic:rendering

**Comment by reduz** [comment] 2019-02-27 02:22
By the way, implicit conversions now work so you code should run as-is without needing to change.
