### ISSUE TITLE
Window Place "Centered" doens't work

### ISSUE THREAD

**Issue by samsimsom** [godotengine/godot#48738] opened 2021-05-15 16:18 UTC
**Godot version:**

3.3.1 rc2 and olders.

**OS/device including version:**

Huavei Matebook 14'' / Windows 10 / 2160x1440 screen resolution - %150 windows text and application scale on

**Issue description:**

Window Place "Centered" doens't work. When I start the project on debug mode from Godot Play the Project button.
New game windows starting right bottom corner on the screen.

**Steps to reproduce:**

**Minimal reproduction project:**

![image](https://user-images.githubusercontent.com/9305316/118370853-58968e00-b5b2-11eb-8a2e-03e628b1a745.png)

**Comment by Calinou** [comment] 2021-05-15 16:31
Duplicate of https://github.com/godotengine/godot/issues/13017.

**Closed by Calinou** 2021-05-15 16:31 UTC
