### ISSUE TITLE
App was crashed when toggled checkbox in project settings

### ISSUE THREAD

**Issue by massanchik** [godotengine/godot#8156] opened 2017-03-26 07:33 UTC
**Operating system or device - Godot version:**
MacOS

**Issue description:**

Engine crashed
Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x00007fc1fffffffc
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Segmentation fault: 11
Termination Reason:    Namespace SIGNAL, Code 0xb
Terminating Process:   exc handler [0]

VM Regions Near 0x7fc1fffffffc:
    Stack                  0000700009b89000-0000700009c0b000 [  520K] rw-/rwx SM=COW  thread 8
--> 
    MALLOC_TINY            00007fc226c00000-00007fc227000000 [ 4096K] rw-/rwx SM=PRV  

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   org.godotengine.godot         	0x00000001099e64e8 TreeItem::is_checked(int) const + 24
1   org.godotengine.godot         	0x000000010937b9bd PropertyEditor::_item_edited() + 1085
2   org.godotengine.godot         	0x000000010938c344 MethodBind0<PropertyEditor>::call(Object*, Variant const**, int, Variant::CallError&) + 212
3   org.godotengine.godot         	0x000000010a26d485 Object::call(StringName const&, Variant const**, int, Variant::CallError&) + 421
4   org.godotengine.godot         	0x000000010a266349 MessageQueue::_call_function(Object*, StringName const&, Variant const*, int, bool) + 329
5   org.godotengine.godot         	0x000000010a266591 MessageQueue::flush() + 177
6   org.godotengine.godot         	0x0000000109812d5f SceneTree::input_event(InputEvent const&) + 543
7   org.godotengine.godot         	0x0000000108c1bda9 InputDefault::parse_input_event(InputEvent const&) + 1081
8   org.godotengine.godot         	0x0000000108c0e66e -[GodotContentView mouseDown:] + 254
9   com.apple.AppKit              	0x00007fffb03a7603 -[NSWindow(NSEventRouting) _handleMouseDownEvent:isDelayedEvent:] + 6341
10  com.apple.AppKit              	0x00007fffb03a3e20 -[NSWindow(NSEventRouting) _reallySendEvent:isDelayedEvent:] + 1942
11  com.apple.AppKit              	0x00007fffb03a32be -[NSWindow(NSEventRouting) sendEvent:] + 541
12  com.apple.AppKit              	0x00007fffb022bbf5 -[NSApplication(NSEvent) sendEvent:] + 1145
13  org.godotengine.godot         	0x0000000108c0de42 -[GodotApplication sendEvent:] + 98
14  org.godotengine.godot         	0x0000000108c1236b OS_OSX::run() + 235
15  org.godotengine.godot         	0x0000000108c146c6 main + 470
16  libdyld.dylib                 	0x00007fffc757f255 start + 1
**Steps to reproduce:**
Toggle resizable checkbox
Scene -> Project Settings -> Display -> resizable
I'm noticed that this was happening only when not "en" editor lang was set.
I had "ru" one when it crashed couple of times.
**Link to minimal example project:**

**Comment by volzhs** [comment] 2017-03-26 07:49
Please edit title to be more descriptive.

**Comment by eon-s** [comment] 2017-04-02 17:27
This may be related or duplicate of #7696

**Comment by akien-mga** [comment] 2017-04-03 07:46
Looks like it indeed, even though the Godot version is not specified.. Closing as duplicate of #7696.

**Closed by akien-mga** 2017-04-03 07:46 UTC
Labels: bug, platform:osx, topic:editor
