### ISSUE TITLE
Right stick axis mapped with keyboard keys create "laggy" movements

### ISSUE THREAD

**Issue by guillaumepn** [godotengine/godot#57666] opened 2022-02-05 16:57 UTC
### Godot version

v3.4.2.stable.mono.official [45eaa2daf]

### System information

MacOS Monterey v12.1

### Issue description

When I create a new input map and combine a Right Stick Axis with a keyboard key, and then use the keyboard key ingame, I see some "lag" in the movement created

I attached a small project showing this, just run it and try moving the Godot image with Keyboard "L" to move right, and comparing it with Keyboard "J" to move left

I only tried it on a Mac

![image](https://user-images.githubusercontent.com/10799586/152650795-7e4c0556-3128-4c26-ba2d-646a117d8261.png)

### Steps to reproduce

- Create a new input map in Settings > Input Map called "joy_r_right" for example
- Assign to it : the keyboard key L and the "Right Stick Right" axis input
- Create a simple scene / script in which you move a sprite with this input
- The movement is not consistent 
- Now remove the "Right Stick Right" from the input map, and retry
- The movement is smooth 

### Minimal reproduction project
[GameTest.zip](https://github.com/godotengine/godot/files/8008424/GameTest.zip)

**Comment by Calinou** [comment] 2022-02-05 17:21
Can you reproduce this on Godot 3.3.4? If not, this is likely a duplicate of https://github.com/godotengine/godot/issues/55037.

**Comment by guillaumepn** [comment] 2022-02-05 17:30
Just tried on v3.3.4.stable.mono.official [faf3f883d], I still see the problem unfortunately

**Comment by Calinou** [comment] 2022-02-05 17:34
This could be related to https://github.com/godotengine/godot/issues/45628, especially if the joystick is connected and is continuously sending inputs due to the deadzone being too low.

Which controller model are you using?

**Comment by guillaumepn** [comment] 2022-02-05 17:41
Indeed when I disconnect my controller, the problem is solved! 

I use a PS5 controller

**Comment by Calinou** [comment] 2022-02-05 17:47
Could you test https://github.com/godotengine/godot/pull/48343 to see if it resolves the issue? See instructions in [Testing pull requests](https://docs.godotengine.org/en/latest/community/contributing/testing_pull_requests.html).

**Comment by Calinou** [comment] 2022-03-17 16:24
Duplicate of https://github.com/godotengine/godot/issues/39287.

**Closed by Calinou** 2022-03-17 16:24 UTC
Labels: bug, needs testing, topic:input
