### ISSUE TITLE
Can't cap Editor FPS in Godot 4.0x

### ISSUE THREAD

**Issue by LTC06** [godotengine/godot#72194] opened 2023-01-27 18:31 UTC
### Godot version

4.0x

### System information

Windows 11, Vulkan, AMD Radeon RX 6700 XT

### Issue description

While working in the editor your FPS will always be maxed out and can't be capped not matter what you do. I tried capping the FPS in the project settings but it only caps when you run the project or export it and I also tried capping the FPS using external software but that doesn't seem to work either. I'm pretty sure Godot 3.0x had this feature but I'm not sure, but I hope this feature comes soon to 4.0x because it kills me seeing my FPS being around 1000 for hours.

### Steps to reproduce

Project Settings/Application/Run/Max FPS

### Minimal reproduction project

N/A

**Comment by stephannv** [comment] 2023-01-27 18:34
@LTC06 you can open a proposal here: https://github.com/godotengine/godot-proposals

**Comment by clayjohn** [comment] 2023-01-27 19:00
@LTC06 What are you using to measure FPS?

**Comment by LTC06** [comment] 2023-01-27 19:30
@clayjohn I'm using the In editor "View Frame Time"

**Comment by clayjohn** [comment] 2023-01-27 19:38
Ah, the "View Frame Time" option doesn't actually report how many times the frame is updating per second, it reports the amount of time Godot took to render the frame and how many frames per second would be rendered if uncapped

From a [previous report](https://github.com/godotengine/godot/issues/69218) of the same issue:
> The frame time option in the 3D view prints how long it takes to get from the first render command to the last. It does not necessarily include the time waiting for Vsync (although on some systems it does depending on how the drivers implement vsync). Therefore, the FPS label is misleading, as you are not necessarily actually rendering that many frames, it's more like you could render that many frames in the absence of vsync.

> I believe the "print FPS" option in the project settings does a better job at accurately reporting FPS. If that doesn't work, see if you have NVidia tools that will do a screen overlay with FPS and other frame stats. This will be the most accurate measurement you can get.

Duplicate of https://github.com/godotengine/godot/issues/69218

There is a PR to improve the communication about this FPS measure as it is quite confusing https://github.com/godotengine/godot/pull/69228

**Comment by LTC06** [comment] 2023-01-27 19:54
@clayjohn Oh ok thanks!

**Closed** 2023-01-27 19:54 UTC
Labels: discussion
