### ISSUE TITLE
[Godot 4] RigidBody2D gets stuck when moving along tilemap floor

### ISSUE THREAD

**Issue by popcar2** [godotengine/godot#72372] opened 2023-01-30 11:58 UTC
### Godot version

4.0.beta16

### System information

Windows 11, RTX 3060Ti, Compatibility backend

## The Issue

RigidBody2D seems to have a tendency of getting stuck in-between tiles. Using square corners, my RigidBody2D box would constantly get stuck when I'm applying force along the X axis. This issue doesn't seem to happen when the RigidBody2D is on a completely smooth surface like a StaticBody2D. It's also worth noting that I have rotation disabled on the box.
I triple checked and am sure that my tiles all have a square physics shape.

Video showcasing the issue:

https://user-images.githubusercontent.com/16920817/215466673-3b1cfc45-4c62-4d5d-b779-8310bb860d2d.mp4

Video showcasing the same box on a StaticBody2D (this is how it should be):

https://user-images.githubusercontent.com/16920817/215466819-74403efc-50c1-4759-995c-450c4163afa1.mp4

## The Band-Aid Solution

A simple but not perfect fix would be to never use square edges when interacting with a tilemap. Something like this _sort of_ works:

![image](https://user-images.githubusercontent.com/16920817/215468544-4d8baec1-6b77-4232-bcfc-315c8025e390.png)

But unfortunately this makes stacking boxes more difficult, and the issue doesn't go away completely. The box still bumps slightly when moved along the tilemap:

https://user-images.githubusercontent.com/16920817/215468932-adada85f-144d-4cb0-b2a2-9255bfa9e3f9.mp4

## Proposal

As a Unity developer that's coming in hot to Godot, this is exactly why we have composite colliders there. Every tile having its own separate collider is bound to cause issues. A way to bake collisions would be an instant fix. I see that Godot already has a CollisionPolygon2D, maybe there can be an automatic way to wrap the Tilemap with it?

### Steps to reproduce

- Draw a tilemap
- Create a RigidBody2D with a rectangle collider
- Place it on the tilemap and apply force along the X axis
- Watch it get stuck at some point

### Minimal reproduction project

[Platformer Quickstart.zip](https://github.com/godotengine/godot/files/10535282/Platformer.Quickstart.zip)

Run the "Level 1" scene. Press 'X' to spawn a box, hold 'R' to restart the scene.

**Comment by Calinou** [comment] 2023-01-30 12:45
Duplicate of https://github.com/godotengine/godot/issues/47148 (and possibly others).

**Closed by Calinou** 2023-01-30 12:45 UTC
Labels: bug, topic:physics, topic:2d

**Comment by mbklassen** [comment] 2024-03-02 22:15
Just wondering if you ever found a fix for this

**Comment by Rulft44** [comment] 2024-03-27 19:56
Was looking for a fix on this issue too and stumbled across this https://github.com/popcar2/GodotTilemapBaker
It fixed the issue.
