### ISSUE TITLE
Distorted Pixel Art with frame animation on window resize

### ISSUE THREAD

**Issue by Theeverydayman** [godotengine/godot#74003] opened 2023-02-26 20:04 UTC
### Godot version

4rc5

### System information

Windows 10, Vulkan, GTX1060 6GB

### Issue description

Distorted pixel art - mostly visible on character eyes [with "keep-width" the eyes pop like 3 times the size, on simple "keep" they jump between what appears like 1.5 and .5 pixels] when window is resized to full screen. Viewport V and H are 640x360, Mode: Viewport, Aspect: Keep, Scale 1 int. Did not happen in Godot3, with pixel snap enabled. Both pixel snap options in Godot4 fail to fix it, AND add heavy jitter when moving diagonally. Clean project, with a tilemap, a sprite with animation frames and godot logo. Tried every option in project settings I could find.

Aspect: Keep / Keep height:
![image](https://user-images.githubusercontent.com/107764354/221433833-253dc550-730c-4e43-a15c-d136a85c2750.png)

Aspect: Keep Width:
![image2](https://user-images.githubusercontent.com/107764354/221433911-973f0985-92c0-4313-9e0a-d3f4355fceab.png)

It looks like the scale would not stay at a full integer, and instead go into an f, or might be a problem on my end - please advise.

### Steps to reproduce

Change the window size / maximize the minimal reproduction project

### Minimal reproduction project

[Minimal.zip](https://github.com/godotengine/godot/files/10834616/Minimal.zip)

**Comment by Calinou** [comment] 2023-02-26 20:31
- Duplicate of https://github.com/godotengine/godot-proposals/issues/1666.

This is due to uneven pixel scaling. The pixel snap project settings are not expected to fix this.

**Closed by Calinou** 2023-02-26 20:31 UTC
