### ISSUE TITLE
Plans to switch to .NET core instead of Mono? 

### ISSUE THREAD

**Issue by arijoon** [godotengine/godot#18503] opened 2018-04-29 12:49 UTC
Are there any plans to switch to .Net core (which is platform independent) instead of Mono?

**Comment by swarnimarun** [comment] 2018-04-29 14:10
I don't want to be rude but,
please don't waste the devs time by such issues just join the reddit.

Read this: [Why hasn't Godot used DotNet Core, as opposed to Mono?](https://www.reddit.com/r/godot/comments/7u1no6/why_hasnt_godot_used_dotnet_core_as_opposed_to/
)
It clearly says that .Net core is not ready yet and thus doesn't make it into priority and it's only about a couple of months old so such a issue doesn't make any sense.

**Comment by bojidar-bg** [comment] 2018-04-29 15:03
Duplicate of #10612 and maybe #17010.

**Closed by bojidar-bg** 2018-04-29 15:03 UTC

**Comment by nightblade9** [comment] 2019-06-17 18:53
This is very problematic for many of us who are .NET developers and use .NET Core. Many libraries are no longer available in "Framework" flavour (for example, SadConsole) and only available in .NET Core. This means we won't be able to integrate them with .NET in the foreseeable future.

.NET Core DLLs can call .NET Framework DLLs, so switching to .NET Core is actually more compatible. However, I understand and accept (to some degree) the argument that .NET Core does not (yet) run on mobile, and Godot does run on mobile today.

**Comment by NathanWarden** [comment] 2019-06-18 01:05
I think they plan on consolidating all of the .Net's (and Mono) in .Net 5, so it wouldn't make sense to change anything until that happens and any issues have been ironed out.

https://devblogs.microsoft.com/dotnet/introducing-net-5/

**Comment by samuelGrahame** [comment] 2019-06-28 00:07
> I think they plan on consolidating all of the .Net's (and Mono) in .Net 5, so it wouldn't make sense to change anything until that happens and any issues have been ironed out.
> 
> https://devblogs.microsoft.com/dotnet/introducing-net-5/

Yeah that is a good idea, as .net 3 is not released yet. only in preview and has a lot of changes between 2 and 3

.net 5 essential - you should just need to change the project type and it should work.

**Comment by ffMathy** [comment] 2019-09-24 18:33
3.0 is out now! :)

**Comment by borgdylan** [comment] 2019-09-24 18:38
Also a .NET Standard 2.0 library an be called from mono!
