### ISSUE TITLE
Very noticeable banding with SSAO.

### ISSUE THREAD

**Issue by antonyjones67** [godotengine/godot#13129] opened 2017-11-21 03:42 UTC
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Microsoft Windows Home. Micro-Star I7. Geforce GTX 1060.
Godot Engine 3.0.alpha.custom_build.6fd1b94.

**Issue description:**

SSAO causes very noticeable banding.

**Steps to reproduce:**
I'm not sure why the banding is so very obvious. I had the SSAO set to default settings. It was most noticeable at the left and right edges of the image.

**Link to minimal example project:**

![image](https://user-images.githubusercontent.com/3905646/33053817-e6f6ddbe-ce32-11e7-8006-205a29ae36f0.png)

**Comment by antonyjones67** [comment] 2017-11-21 21:25
I noticed today that if you mark the turn on the materials Ambient Occlusion that this problem is greatly reduced. But it still happens on large surfaces like the floor.

**Comment by reduz** [comment] 2017-11-21 21:30
an example scene would be appreciated, otherwise reproduction is next to
impossible

**Comment by antonyjones67** [comment] 2017-11-21 21:37
I have an Asset, but it is an Unreal Asset that I converted to work with Godot. It is quite large. It is a 286k zip file. Is it safe to add here? Since it is an Unreal Sample?

**Comment by Calinou** [comment] 2017-11-21 21:46
> Is it safe to add here? Since it is an Unreal Sample?

Probably not, perhaps email it to reduz directly (see his email on [his profile page](https://github.com/reduz)).

Alternatively, reproduce the issue using a from-scratch project (it doesn't have to look beautiful, it just needs to reproduce the bug) and upload it here as an attachment.

**Comment by reduz** [comment] 2017-11-21 22:34
send me email or share me drive folder if you wish

**Comment by reduz** [comment] 2017-11-21 23:37
Heh, I admit this is pretty neat:

![image](https://user-images.githubusercontent.com/6265307/33102473-bc764600-cefb-11e7-9bb0-cf09787d2df8.png)

But the scene does not import correctly, it seems you didn´t send me the whole project. With what I have so far, the bug is not reproducible (SSAO looks fine).

**Comment by reduz** [comment] 2017-11-21 23:38
We need someone to make demos like this for Godot :P

**Comment by antonyjones67** [comment] 2017-11-22 02:04
Here is a link to a video of what it is suppose to look like.
https://www.youtube.com/watch?v=c4wBeAqGFds

**Comment by reduz** [comment] 2017-12-05 22:49
I unfortunately can't reproduce the banding problem.. may need to try a lower end gpu for this..

**Comment by lehthanis** [comment] 2017-12-28 16:45
It's happening for me on a Quadro K5200...I don't think thats a low-end gpu is it? https://imgur.com/a/rNftU

**Comment by reduz** [comment] 2017-12-28 16:49
@lehthanis test scene and reproduction steps welcome

**Comment by lehthanis** [comment] 2017-12-28 18:02
@reduz Just sent you a google drive link.  Sorry it's not really that small.  But if you run the game (problem doesn't exist in editor) and face one of the hallway walls perpindicularly you'll see the banding...the closer you get to it, the worse it is.

**Comment by reduz** [comment] 2018-01-16 18:11
I could never really reproduce this issue, but i have seen it reported a few times.  I have your same hardware, which makes it even weirder. Will have to kick it to 3.1 until more information on reproduction or hardware where it fails can be obtained..

**Comment by remorse107** [comment] 2018-01-25 01:30
I'm seeing a very noticeable banding without SSAO on.
![capture](https://user-images.githubusercontent.com/7462993/35366046-f50585ee-013c-11e8-82a2-8523afd33d19.PNG)

**Comment by Calinou** [comment] 2018-01-25 01:37
This is likely due to shadow bias, try disabling the directional shadow and see if it's still there. To counter it, increase the shadow bias (and/or normal bias) value.

**Comment by remorse107** [comment] 2018-01-25 01:45
Thanks for the tip.  It was actually my GIProbe.  After playing with the bias there the banding disappeared.

**Comment by LinuxUserGD** [comment] 2018-09-01 09:33
I can also reproduce it in my game Solus Stunts (ambient occlusion: middle):
![bug](https://user-images.githubusercontent.com/34406967/44944656-d3a3c000-adda-11e8-9cb1-20d95f669bd3.png)

**Comment by reduz** [comment] 2018-09-06 12:30
Kicking to 3.2, where the AO code will probably be rewritten, I could never reproduce this problem and may be related to drivers.

**Comment by TheRadMatt** [comment] 2018-12-18 17:18
In my case, this hapens when the _far_ property of the **camera** is set too high (like 99999). AO looks ok when it's set to 100.

**Comment by Zireael07** [comment] 2018-12-18 17:20
You might be on to something, mine is not 100 either (but definitely not something egregiously high - I think it's 250 or 300?)

**Comment by LinuxUserGD** [comment] 2019-01-28 13:50
Seems to be fixed for me.

**Comment by akien-mga** [comment] 2019-11-26 13:12
It's been two years but we still lack a simple, public reproduction project to be able to confirm and investigate the bug. So it's pretty hard to do anything to fix it.

If anyone can reproduce the issue, please provide a project that exhibits it, otherwise we'll have to close it.

**Comment by Dimev** [comment] 2020-02-19 10:45
I was setting up a project in 3.2 stable when I encountered this issue. I've included the project as a file here, (it's still minimal). The banding is mostly noticeable on the sides of the cube in main.tscn
I hope this helps with fixing the issue

OS: Windows 10
GPU: NVidia GTX 1660
CPU: Intel core i5-9600KF @ 3.70 GHz
RAM: 16Gb

[minimal reproduction](https://github.com/godotengine/godot/files/4224516/voxels.rust.zip)

**Comment by Calinou** [comment] 2020-02-28 17:40
It seems SSAO banding no longer occurs in the `master` branch (which now uses Vulkan). :tada: 

### Editor with Zfar = 200

![2020-02-28_18 30 31](https://user-images.githubusercontent.com/180032/75571346-44bc4600-5a59-11ea-9eb9-72ca672d55c5.png)


### Editor with Zfar = 4000

![2020-02-28_18 30 41](https://user-images.githubusercontent.com/180032/75571378-57cf1600-5a59-11ea-8e64-e9cb11120a13.png)

There's no difference in terms of SSAO quality, and directional shadows look mostly identical.

**Closed by Calinou** 2020-02-28 17:40 UTC
Labels: bug, topic:rendering
