### ISSUE TITLE
Area3D wind target is not blowing SoftBody in a direction

### ISSUE THREAD

**Issue by yankscally** [godotengine/godot#94192] opened 2024-07-11 03:40 UTC
### Tested versions

4.3 beta2

### System information

win 10 

### Issue description

When using Area3D wind, it only blows the soft body in one direction, moving the target node seems to do nothing.

### Steps to reproduce

add a simple softbody, attach it to a staticbody, make an area3D with the softbody inside the collision , and turn up the wind amount. The wind works, but translating the wind target node around does not change its direction.

### Minimal reproduction project (MRP)

n/a

**Comment by huwpascoe** [comment] 2024-07-11 04:18
To clarify, is the target node being rotated?

**Comment by AThousandShips** [comment] 2024-07-11 08:39
Please confirm it *doesn't* get affected by the direction of the local z-axis of the source, otherwise this should just be covered by your documentation issue for clarity assuming it works as intended

**Comment by yankscally** [comment] 2024-07-11 10:47
Yeah I tried a bunch of stuff, moving the target around.. its not working. seems to just be blowing in 1 direction.

**Comment by AThousandShips** [comment] 2024-07-11 10:49
Please upload an MRP, there's not enough detail here to determine what you did

**Comment by yankscally** [comment] 2024-07-11 10:58
[softbody_wind.zip](https://github.com/user-attachments/files/16175725/softbody_wind.zip)


here is the project. transform the wind direction node and hit play. the wind always blows forwards.

**Comment by AThousandShips** [comment] 2024-07-11 11:03
It works perfectly when you rotate the source, just change the y-rotation of the source to 180 and see

Closing as this works as expected, and it's a matter of seemingly unclear documentation, but it works exactly as expected when *rotated*

**Closed by AThousandShips** 2024-07-11 11:03 UTC
Labels: topic:physics, needs testing, topic:3d
