### ISSUE TITLE
Create New Folder from Editor UI

### ISSUE THREAD

**Issue by Zarraya** [godotengine/godot#60084] opened 2022-04-09 21:46 UTC
### Godot version

4.0 beta v4.0.alpha6.official [e4f0fc50f]

### System information

Windows 10, Ryzen 5900X, RTX 3080, Vulkan

### Issue description

Trying to create a folder from the context menu in the FileSystem tab will return the message "Could not create folder. File with that name already exists." This happens no matter the name given. The issue can be worked around by making a folder with the OS file system.

### Steps to reproduce

Right click the FileSystem tab area and select New Folder. Give a name. Hit OK. No folder should be created.

**Comment by Calinou** [comment] 2022-04-09 21:48
Duplicate of https://github.com/godotengine/godot/issues/59956.

**Closed by Calinou** 2022-04-09 21:48 UTC
