### ISSUE TITLE
use atom as external editor and crash;mac os 

### ISSUE THREAD

**Issue by jinruozai** [godotengine/godot#39233] opened 2020-06-02 02:34 UTC
Godot version:3.2.1.
Mac OS:10.15.4
Description:use atom as editor and crash

step:
setting->text editor->external:
exec path:/Applications/Atom.app
exec flags:{file}:{line}

open a script,then crash

**Comment by bruvzg** [comment] 2020-06-02 05:06
> exec path:/Applications/Atom.app

Path should point to the executable, not the bundle. In case of Atom you should install command line tools from the atom menu `Atom` -> `Install Shell Commands`, and set path to `/usr/local/bin/atom`.

**Comment by akien-mga** [comment] 2020-06-02 11:31
Duplicate of #17615. (I guess -- there's hardly any info in this issue so we have to guess.)

**Closed by akien-mga** 2020-06-02 11:31 UTC
