### ISSUE TITLE
Regression in 3.4 RC1 from Beta 6 dealing with HTTPRequest or queue_free

### ISSUE THREAD

**Issue by bflanagin** [godotengine/godot#54310] opened 2021-10-27 16:33 UTC
### Godot version

3.4.rc1

### System information

Linux

### Issue description

I have a program that uses httprequest to pull image data from a webserver along with other various data sets. In 3.4 beta 6 the program behaves the same way it did in 3.3.4. However, in the latest RC the program locks up and becomes unresponsive. In diagnosing the issue I changed the request from threaded to non-threaded which allows the program to function but at a much diminished speed. 

Strangely, I have two other projects that uses the same code base for the retrieval that are not being affected by the lockup, on RC 1. I'd chalk it up to bad programming if it didn't work as expected in everything up to beta6

### Steps to reproduce

The setup is pretty straight forward. You have a function that spawns a HTTPRequest node, executes the request, receives the signal and feeds it into the image conversion function that sets the TextureRects texture.

```
func cache_img(img):
	var msg = {
		"act":["image_retrieval"],
		"url":img,
		"type":"cache"
		}
	
	var check = HTTPRequest.new()
	check.set_timeout(10)
	check.use_threads = true
	add_child(check)
	var fullurl = 'msg='+to_json(msg)
	check.connect("request_completed",self,"_on_HTTPRequest_request_completed",["cache"+str(img),check])
	check.request(http_url,[],true,HTTPClient.METHOD_POST,fullurl)

```
On Complete send the body (image data) and free the HTTPRequest. 

```
func _on_HTTPRequest_request_completed(_result, response_code, _headers, body,request_type,object):
	#print_debug(response_code," ",request_type)
	if response_code == 200:
            on_image_received(body)
       object.queue_free()
````
Checks image type based on data (not extension) converted, and set to TextureRect. ( This should be improved, but I haven't gotten around to it. )

```
func on_image_received(data):
	if img.load_png_from_buffer(data) == OK:
		imgTexture.create_from_image(img)
	elif img.load_jpg_from_buffer(data) == OK:
		imgTexture.create_from_image(img)
	$HSplitContainer/PanelContainer/Control/Profile/TextureRect.set_texture(imgTexture)
```

### Minimal reproduction project

Will provide a sample project. ASAP

**Comment by akien-mga** [comment] 2021-11-01 09:48
A minimal reproduction project would be very useful indeed so that we can confirm the bug and identify which commit caused the regression. I don't see much in the changes between 3.4 beta 6 and RC 1 that would seem related to this issue: https://github.com/godotengine/godot/compare/3e2bb415a9b186596b9ce02debc79590380c2355...90f8cd89a738316563dac9b133628df6bafe2cb2

The main changes related to either HTTPRequest or threading would be:
- #53800 (CC @Faless)
- #53490 (CC @briansemrau)

**Comment by mhilbrunner** [comment] 2021-11-01 11:30
I couldn't reproduce this by testing image downloads with Godot 3.4c1.
I then adapted the provided (non-working) code best as I could, and still could not reproduce it.

Please provide a minimal reproduction project if you can.

**Comment by briansemrau** [comment] 2021-11-01 14:14
The thread changes don't appear to have any mechanism that could have caused this.

Does this issue happen consistently with this project? You mentioned it didn't happen on other projects with the same code. I've been debugging multithreading issues on master and usually this indicates that something else might be deadlocking. Hard to say without getting a debugger on this project.

**Comment by bflanagin** [comment] 2021-11-01 22:05
Thanks for testing things @mhilbrunner. Like you, I haven't been able to cause the issue with just the code above. I'll pull in more code in the sample project until it dies, and upload it here. (if that is still useful)

@briansemrau It happens consistently in the project on RC1 and RC2. 

After more testing, even with `use_threads = false` the application will fail to load all the images and fail eventually. The number of images until lock is ~12 and the size of the file doesn't seem to matter. Curiously in the application that is unaffected setting `use_threads = false` causes the same failed image issue, but without the lock in RC1 & 2.

The biggest difference in the code between the working and non-working projects is the inclusion of `call_deferred`  when creating the objects that display the images. I believe this circumvents the issue by serializing the image gathering / displaying process, and could be used in the affected project as well as a work around.

**Comment by akien-mga** [comment] 2022-05-04 21:38
@bflanagin Are you still able to reproduce this issue in 3.4.4.stable or 3.5 beta 5 or later?
It seems like without a reproduction project this will be difficult to debug further from our end.

**Comment by akien-mga** [comment] 2022-06-10 09:39
Closing for now as we lack a project or more details to be able to reproduce and fix this.

**Closed by akien-mga** 2022-06-10 09:39 UTC
Labels: bug, needs testing, topic:network, crash, regression
