### ISSUE TITLE
10 errors `Caller thread can't call this function in this node`

### ISSUE THREAD

**Issue by golxzn** [godotengine/godot#80806] opened 2023-08-20 07:07 UTC
### Godot version

v4.1.1.stable.official [bd6af8e0e]

### System information

Windows 11 Pro (21H2) - AMD Ryzen 7 3700X 8-Core Processor - Mobile renderer

### Issue description

I use Visual Studio Code to write code, so when I open script in Godot, I've got those errors:
```
Godot Engine v4.1.1.stable.official (c) 2007-present Juan Linietsky, Ariel Manzur & Godot Contributors.
--- Debug adapter server started ---
--- GDScript language server started ---
[LSP] Connection Taken
  Caller thread can't call this function in this node (/root/@EditorNode@17637/@Control@697/@Panel@698/@VBoxContainer@706/@HSplitContainer@709/@HSplitContainer@717/@HSplitContainer@725/@VBoxContainer@726/@VSplitContainer@728/@PanelContainer@7498/@VBoxContainer@7499/@EditorLog@7529/@VBoxContainer@7513/@RichTextLabel@7515). Use call_deferred() or call_thread_group() instead.
  Caller thread can't call this function in this node (/root/@EditorNode@17637/@Control@697/@Panel@698/@VBoxContainer@706/@HSplitContainer@709/@HSplitContainer@717/@HSplitContainer@725/@VBoxContainer@726/@VSplitContainer@728/@PanelContainer@7498/@VBoxContainer@7499/@EditorLog@7529/@VBoxContainer@7513/@RichTextLabel@7515). Use call_deferred() or call_thread_group() instead.
  Caller thread can't call this function in this node (/root/@EditorNode@17637/@Control@697/@Panel@698/@VBoxContainer@706/@HSplitContainer@709/@HSplitContainer@717/@HSplitContainer@725/@VBoxContainer@726/@VSplitContainer@728/@PanelContainer@7498/@VBoxContainer@7499/@EditorLog@7529/@VBoxContainer@7513/@RichTextLabel@7515). Use call_deferred() or call_thread_group() instead.
  Caller thread can't call this function in this node (/root/@EditorNode@17637/@Control@697/@Panel@698/@VBoxContainer@706/@HSplitContainer@709/@HSplitContainer@717/@HSplitContainer@725/@VBoxContainer@726/@VSplitContainer@728/@PanelContainer@7498/@VBoxContainer@7499/@EditorLog@7529/@VBoxContainer@7513/@RichTextLabel@7515). Use call_deferred() or call_thread_group() instead.
  Caller thread can't call this function in this node (/root/@EditorNode@17637/@Control@697/@Panel@698/@VBoxContainer@706/@HSplitContainer@709/@HSplitContainer@717/@HSplitContainer@725/@VBoxContainer@726/@VSplitContainer@728/@PanelContainer@7498/@VBoxContainer@7499/@EditorLog@7529/@VBoxContainer@7513/@RichTextLabel@7515). Use call_deferred() or call_thread_group() instead.
  This function in this node (/root/@EditorNode@17637/@Control@697/@Panel@698/@VBoxContainer@706/@HSplitContainer@709/@HSplitContainer@717/@HSplitContainer@725/@VBoxContainer@726/@VSplitContainer@728/@PanelContainer@7498/@VBoxContainer@7499/@EditorLog@7529/@VBoxContainer@7517/@Button@7528) can only be accessed from either the main thread or a thread group. Use call_deferred() instead.
  Caller thread can't call this function in this node (/root/@EditorNode@17637/@Control@697/@Panel@698/@VBoxContainer@706/@HSplitContainer@709/@HSplitContainer@717/@HSplitContainer@725/@VBoxContainer@726/@VSplitContainer@728/@PanelContainer@7498/@VBoxContainer@7499/@EditorLog@7529/@VBoxContainer@7517/@Button@7528). Use call_deferred() or call_thread_group() instead.
  This function in this node (/root/@EditorNode@17637/@Control@697/@Panel@698/@VBoxContainer@706/@HSplitContainer@709/@HSplitContainer@717/@HSplitContainer@725/@VBoxContainer@726/@VSplitContainer@728/@PanelContainer@7498/@VBoxContainer@7499/@EditorLog@7529/@VBoxContainer@7517/@Button@7528) can only be accessed from the main thread. Use call_deferred() instead.
  Caller thread can't call this function in this node (/root/@EditorNode@17637). Use call_deferred() or call_thread_group() instead.
  Caller thread can't call this function in this node (/root/@EditorNode@17637/@EditorFileSystem@694). Use call_deferred() or call_thread_group() instead.
```

Actually, it happened after adding `@tool` keyword to my creature to highlight errors in `_get_configuration_warnings` method. 

### Steps to reproduce

I don't actually know how to reproduce this issue, but as I said, those errors happen every editor opening and code changing, that's annoying, and they have spawned just after my a little bit more advanced programming patterns usage like strategy.

### Minimal reproduction project

Here's the minimal reproduction project.
[IssueProjectTest.zip](https://github.com/godotengine/godot/files/12387446/IssueProjectTest.zip)

Here's the VSCode integration settings:
![image](https://github.com/godotengine/godot/assets/42336163/d0097458-20c3-4370-bf47-eca691276ddb)
![image](https://github.com/godotengine/godot/assets/42336163/e2919c95-1d1e-450a-a128-7703ffc59f53)
![image](https://github.com/godotengine/godot/assets/42336163/d4ff67a4-ea0e-4dd8-8917-08d9ee0d7565)
![image](https://github.com/godotengine/godot/assets/42336163/3fedbf69-ee24-4404-8733-8101e0dbc719)

**Comment by bitsawer** [comment] 2023-08-20 07:46
Thanks for the report. Looks like a duplicate of https://github.com/godotengine/godot/issues/79525, so closing to consolidate reports in one place.

**Closed by bitsawer** 2023-08-20 07:46 UTC
