### ISSUE TITLE
RichTextLabel clipping ignores rotation.

### ISSUE THREAD

**Issue by Jubjub** [godotengine/godot#23233] opened 2018-10-22 20:37 UTC
**Godot version:**
b77a41125847633509a2af7d2e693ebdd4c35c01 (latest master)

**Issue description:**
When the text overflows in a rotated RichTextLabel, it gets clipped to an axis-aligned rect instead of a rotated rectangle.

**Steps to reproduce:**
Create RichTextLabel with enough text that it overflows, and rotate it, or its parent.
 
![screenshot from 2018-10-22 22-36-10](https://user-images.githubusercontent.com/465818/47317890-edc78500-d64a-11e8-855a-eb8bfc7306a7.png)
#

**Comment by toger5** [comment] 2018-10-22 21:56
It si weired how the clipping works though... seems strange, that only the bottom left corner is clipped without rotation. Clipping box might be bigger...
I did changes to clipping, so i should look at it. Didn't think about rotation back than. The issue i fixed was about rendering viewports to textures.

**Comment by Jubjub** [comment] 2018-10-22 22:09
Thanks for taking a look.
Actually if you rotate it around you'll see that the clipping box is something like this:
![image](https://user-images.githubusercontent.com/465818/47322271-ad223880-d657-11e8-9f1e-9482aa7b0d78.png)

I tried to fix it myself but only got as far as seeing that the clipping rect is set in https://github.com/godotengine/godot/blob/master/scene/gui/control.cpp#L605 but I'm not familiar enough with the internals to know how to apply the control's rotation to that.

**Comment by toger5** [comment] 2018-10-23 06:49
Yea i think the glScissors is the issue. As u said, somewhere in the drivers/visual server file (there are two one for gles2 and one for gles3)
Don't know if the clipping can be applied before the transform?

**Comment by Jubjub** [comment] 2018-10-23 12:18
I was researching this last night, but as far as I can see the glScissor test is just a viewport thing that can't have transforms applied to it. One way to solve it would be to check for rotation, and then use a stencil test instead, which can be any arbitrary shape.

**Comment by KoBeWi** [comment] 2019-04-18 21:53
Related: #20671

**Comment by KoBeWi** [comment] 2020-11-13 10:48
Still valid in a6d4484e5

**Comment by Calinou** [comment] 2022-08-05 06:52
Duplicate of https://github.com/godotengine/godot/issues/20671.

**Closed by Calinou** 2022-08-05 06:52 UTC
Labels: bug, topic:rendering, confirmed, topic:gui
