### ISSUE TITLE
Slow debug stepping when using animated tiles

### ISSUE THREAD

**Issue by Gnumaru** [godotengine/godot#72118] opened 2023-01-26 14:07 UTC
### Godot version

4.0.beta15

### System information

windows 10, nvidia graphics

### Issue description

When using animated tiles, stepping through the debugger gets really slow. This happens with any of the three graphics backend: forward+, mobile and compatibility.

I have already reported two other "slow debug stepping" bugs in the past:

https://github.com/godotengine/godot/issues/68232
https://github.com/godotengine/godot/issues/67696

This other issue might probably be related as well
https://github.com/godotengine/godot/issues/70932

They must be related somehow. I don't know how animated tiles are implemented. If they are implemented with shaders, then all three bugs are shader related.

### Steps to reproduce

see the attached video

https://user-images.githubusercontent.com/5783414/214855103-e5cfb278-5301-41c3-bcc2-df5e2b8222ce.mp4

### Minimal reproduction project

[SlowDebugStepWithAnimatedTiles.zip](https://github.com/godotengine/godot/files/10509891/SlowDebugStepWithAnimatedTiles.zip)

**Comment by mmeissner** [comment] 2023-01-26 21:02
I had a hard time finding the cause of the extremely slow debugging in my project, but it became impossible to work with. I figured that when I used a much smaller map it became better but still noticeable. After removing all animated tiles in my map, the debugging speed became normal again. Thx

**Comment by clayjohn** [comment] 2023-01-26 21:44
Duplicate of https://github.com/godotengine/godot/issues/67696

All three of these reported bugs have the same cause and the same outcome. All three cases are places where the engine uses ``request_redraw()`` to ensure that the editor is updated continuously. I'll post some notes on the other issue to make that more clear

**Closed by clayjohn** 2023-01-26 21:44 UTC
Labels: bug, topic:editor, topic:animation
