### ISSUE TITLE
Navigation2D get_simple_path() does not always find the shortest path

### ISSUE THREAD

**Issue by timcode77** [godotengine/godot#48361] opened 2021-05-01 21:57 UTC
**Godot version:**
3.3.stable.official

**Issue description:**
Navigation2D get_simple_path() does not always find the shortest path. 

These may be related:
https://github.com/godotengine/godot/issues/15919
https://github.com/godotengine/godot/issues/17885

**Steps to reproduce:**
(see demo project / screengrabs)
1. Create a Navigation2D Node with a NavigationPolygonInstance as a child.
2. For the NavigationPolygonInstance, draw a shape with 4 vertices and a triangle inside it.
3. Call get_simple_path for two points inside the NavigationPolygonInstance.
4. The path generated might not be the shortest path.

See images from my test project that demonstrates the problem:

Shortest path:
![image](https://user-images.githubusercontent.com/82291606/116795811-b5626500-ab2b-11eb-80c8-0483f590b723.png)

Not shortest path:
![image](https://user-images.githubusercontent.com/82291606/116795828-d925ab00-ab2b-11eb-9fee-5da8f057ddc4.png)

**Minimal reproduction project:**

[nav_problem.zip](https://github.com/godotengine/godot/files/6410339/nav_problem.zip)

**Comment by Calinou** [comment] 2021-05-01 22:04
Duplicate of https://github.com/godotengine/godot/issues/19011.

**Closed by Calinou** 2021-05-01 22:04 UTC
