### ISSUE TITLE
Remote debug button for Android not enabling automatically after installing build template for Gradle build

### ISSUE THREAD

**Issue by BastiaanOlij** [godotengine/godot#93531] opened 2024-06-24 03:38 UTC
### Tested versions

- Reproducable in Godot 4.3 beta 2
- Reproducable in Godot 4.3 commit 04bf7d4cade645a5923cc80d87ac1c6109e2cdfe

### System information

Windows 10 - Quest 3

### Issue description

The remote debug button to push out a game to your android device, when you have "Use Gradle Build" stays disabled even after installing the Android build template. You have to restart the project before it finds out you've done so.

I'm assuming this is caused by a recent improvement where we're not adding entries to this menu that can't be run. However it is not reacting to resolving the reason.

Especially when you are testing fixes and continuously replacing the build template, it can get a little annoying :)

### Steps to reproduce

- Get a project that is designed to use android build templates
- Delete the `Android` folder
- Open it up in Godot
- Notice the Remote debug button is disabled
- Run Project->Install Android Build Template
- Notice the Remote debug button is still disabled
- Restart Godot
- Notice the Remote debug button is now enabled with your entry

### Minimal reproduction project (MRP)

n/a

**Comment by m4gr3d** [comment] 2024-06-24 12:56
@BastiaanOlij A quick workaround until the issue is fixed is to unplug and replug the Quest device.

**Comment by m4gr3d** [comment] 2024-06-24 12:57
cc @KoBeWi this is likely related to https://github.com/godotengine/godot/pull/87823

**Comment by BastiaanOlij** [comment] 2024-06-25 03:15
> @BastiaanOlij A quick workaround until the issue is fixed is to unplug and replug the Quest device.

I found that to not work consistently, though it could be that I plug it back in too quickly :)

**Comment by KoBeWi** [comment] 2024-06-28 13:03
How is #87823 related? Is runnable Android preset optional to debug on device? Why does re-plugging fix the issue? A solution could be expanding #87823 to look for Android folder, though that's a periodic I/O operation, so rather meh.

**Comment by BastiaanOlij** [comment] 2024-07-17 01:15
> How is #87823 related? Is runnable Android preset optional to debug on device? Why does re-plugging fix the issue? A solution could be expanding #87823 to look for Android folder, though that's a periodic I/O operation, so rather meh.

My guess is:
When the android build files aren't installed, the preset isn't runable and thus not added to the menu. 
When the build files are installed, we are not re-evaluating the presets that become runable.

**Comment by m4gr3d** [comment] 2024-07-17 01:39
> > How is #87823 related? Is runnable Android preset optional to debug on device? Why does re-plugging fix the issue? A solution could be expanding #87823 to look for Android folder, though that's a periodic I/O operation, so rather meh.
> 
> My guess is: When the android build files aren't installed, the preset isn't runable and thus not added to the menu. When the build files are installed, we are not re-evaluating the presets that become runable.

The issue was due to https://github.com/godotengine/godot/pull/92032 and is being resolved in https://github.com/godotengine/godot/pull/94425.

**Closed** 2024-07-17 10:04 UTC
Labels: bug, platform:android, regression, topic:export
