### ISSUE TITLE
Godot 3.1 android devices does not detect Left mouse click anymore

### ISSUE THREAD

**Issue by mani144** [godotengine/godot#27387] opened 2019-03-24 20:36 UTC
**Godot version:**

3.1 Stable

**OS/device including version:**

Android devices only, not desktop 

**Issue description:**

I have been developing a game since 3.0 , and when 3.1 beta has been released i keep testing it and shift my project to it, however my last testing was on godot 3.1beta 10. which the game was working correctly, however when stable came, everything changed. for a certain reason the touch is not detected anymore.

**Steps to reproduce:**
Android devices is needed!
Create any 2d node,and a label node , use the following script
func _process(delta):
	if Input.is_action_just_pressed("touch"):
		print('im touched')
		get_node("Label").text = 'im touched'

add touch map to left click on mouse.

this been tested on emulate mouse to touch and touch to mouse. none of them is working.

**Comment by mani144** [comment] 2019-03-25 16:53
i changed the device in input maps and made it from device:0 to device:all , this seems to solve the problem. who ever im not sure why it did stop working

**Comment by Calinou** [comment] 2019-03-28 13:39
Are you using a mouse on Android (which is possible, I'd just like to make sure)? Also, are you testing on a native device or in an emulator?

**Comment by mani144** [comment] 2019-03-31 15:16
> 
> 
> Are you using a mouse on Android (which is possible, I'd just like to make sure)? Also, are you testing on a native device or in an emulator?
> 
> It's good that it works when the device is set to "all", but I think it should still work when device ID 0 is specified.

I used native android samsung S9 with a regular touches.
thank you for the reply

**Comment by eon-s** [comment] 2019-03-31 17:03
Probably related to #26880, check if the id reported is -1 like on that issue.

**Comment by mani144** [comment] 2019-04-04 09:05
> Probably related to #26880, check if the id reported is -1 like on that issue.

im not sure how to do that, i think it is similar

**Comment by akien-mga** [comment] 2020-01-14 10:08
Closing as duplicate of #26880.

**Closed by akien-mga** 2020-01-14 10:08 UTC
Labels: bug, platform:android, topic:input

**Comment by rafrafek** [comment] 2024-04-29 08:01
Still broken on 4.2.2 Stable. `TouchScreenButton` detects mouse clicks when running in editor, but not in Android emulator. I have "Emulate Touch From Mouse" enabled.

**Comment by akien-mga** [comment] 2024-04-29 08:08
@rafrafek Please avoid commenting on issues closed 4 years ago, whatever was the problem back then is unlikely to be the same bug you're experiencing now, even if the description sounds similar.

Your issue is probably #88621, which is much newer (introduced in 4.2) than this one.
