### ISSUE TITLE
Buttons in Tree control stay high-lighted on right-click

### ISSUE THREAD

**Issue by tianer2820** [godotengine/godot#56113] opened 2021-12-20 22:00 UTC
### Godot version

v3.4.stable.official [206ba70f4]

### System information

Windows 11

### Issue description

Buttons in the Tree control stay in the highlighted state when being right-clicked.
This happens both in the Godot editor (the scene tree viewer) and in user projects (the "Tree" control)

### Steps to reproduce

Open Godot editor, add some nodes to the scene tree, right-click the "toggle visibility" button on any node.
The button will stay in the highlighted state.
![图片](https://user-images.githubusercontent.com/43716345/146838037-8f35cc20-08b8-40c2-adce-e2dbd9f08a98.png)

**Comment by Calinou** [comment] 2021-12-20 22:30
Duplicate of https://github.com/godotengine/godot/issues/16786.

**Closed by Calinou** 2021-12-20 22:30 UTC
