### ISSUE TITLE
Game lag when profiler is activated

### ISSUE THREAD

**Issue by pixel-boy** [godotengine/godot#51222] opened 2021-08-03 19:58 UTC
### Godot version

3.4.beta2

### System information

Windows 7, NVIDIA GeForce GTX 1050 Ti, Intel(R) Core(TM) i7 CPU 870 @ 2.93GHz, 8GB RAM

### Issue description

When the Profiler is active FPS drops (and camera jitter/stutter) in my case it makes the game unplayable on normal levels.

It's more visible when playing but I tried to capture the lag in video:
Profiler OFF: https://streamable.com/g564gj
Profiler ON ( lag ): https://streamable.com/ce33lo

### Steps to reproduce

Just have the profiler activated during gameplay phases (this does not take place in the menus in my game) 

I tried to remove as many elements as possible to find the source, and it seems that the problem appears when I add monsters or objects like the crates, both are physical objects so it may be related to that.

The problem isn't on version 3.3.2 stable, it seems to occur only on my computer, I tried to reproduce it on several others without success.

### Minimal reproduction project

I tried to reproduce the problem in an empty project but I did not succeed for the moment, on all my projects I have at least 2 which have the problem.

**Comment by akien-mga** [comment] 2021-08-03 20:05
Marking as "confirmed" as I've been debugging with @pixel-boy and it's pretty clear that they have a regression which happened between 3.3-stable and 3.4-beta1. A test builds of 59b6950034 (mid-way between 3.3 and 3.4 beta 1) did not reproduce the bug, so it's more recent. I couldn't reproduce the issue on my hardware yet.

**Comment by Calinou** [comment] 2021-10-12 12:32
My guess is that the project is stalling while waiting for the editor to respond to profiler requests. I'm not sure how we can fix this, other than finding a way to decouple the editor debugger from its rendered framerate (i.e. avoid `_process`).

**Closed** 2021-10-12 14:56 UTC
Labels: bug, topic:editor, confirmed, regression
