### ISSUE TITLE
RigidBody in Character mode can disappear when changing angular velocity in script

### ISSUE THREAD

**Issue by CowThing** [godotengine/godot#11334] opened 2017-09-16 18:25 UTC
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Windows 10 64bit - Godot 3.0 b9fddc5

**Issue description:**
The RigidBody in Character mode will disappear and these error messages will show up
![Error messages](https://i.imgur.com/cyCnKnK.png)

Here is the script that causes this issue:
```GDScript
extends RigidBody

func _ready():
	# Apply a small rotation force once
	angular_velocity = Vector3(0, 10, 0)

func _integrate_forces(state):
	var av = state.get_angular_velocity()
	av *= 0.5
	state.set_angular_velocity(av)
```

Specifically it's the `av *= 0.5` that's causing the problem. It only happens when av gets very very small but not exactly 0. Small enough that printing it shows it as 0.

**Link to minimal example project:**
[physics_glitch.zip](https://github.com/godotengine/godot/files/1308536/physics_glitch.zip)

**Comment by kubecz3k** [comment] 2017-11-05 09:48
can you check if its still valid? (#12641)

**Comment by CowThing** [comment] 2017-11-06 12:39
This doesn't happen with Bullet physics enabled. But it's not happening because the RigidBody in Character mode isn't affected by angular velocity at all, so this can't even really be recreated.

I don't know if angular velocity affecting a RigidBody in Character mode is the desired behavior or not.

**Comment by raymoo** [comment] 2017-11-06 19:24
@CowThing My understanding is that RigidBodys in Character mode are not supposed to rotate at all except instantaneously due to calls to set_rotation etc.

**Comment by kubecz3k** [comment] 2017-11-06 19:30
cc @AndreaCatania @reduz what would be the correct behavior in the case when someone use `state.set_angular_velocity(x)` in character manual integration?

**Comment by kubecz3k** [comment] 2017-11-06 19:36
Also worth to mention its a rotation only around Y Axis.

**Comment by CowThing** [comment] 2017-11-06 19:44
Actually in Godot's old physics Character mode could rotate around all axis, it's just that the user had to set the angular velocity, it wouldn't be affected by outside forces.

**Comment by AndreaCatania** [comment] 2017-11-07 01:38
@kubecz3k The dynamic character can't rotate, so we can assume the use of function `set_angular_velocity` in this case is undefined behaviour.

So this is not a bug, however you can still "rotate" it by changing its transform.

**Comment by akien-mga** [comment] 2017-11-21 22:12
Closing as per the above comment.

**Closed** 2017-11-21 22:12 UTC
Labels: bug, topic:physics
