### ISSUE TITLE
Flickering black rectangles on materials with alpha scissor [Intel Haswell graphics]

### ISSUE THREAD

**Issue by tcoxon** [godotengine/godot#45413] opened 2021-01-24 15:50 UTC
**Godot version:**
3.2.3, GLES3

**OS/device including version:**
2015 Apple Macbook Pro
Ubuntu 16.04 with Mesa 18.0.5 driver

**Issue description:**
On my laptop, which has an Intel Haswell Mobile graphics chip, materials with alpha scissor enabled appear to have flickering black boxes over them. The flickering black boxes appear to glow.

Performance is also really bad but that appears to have already been reported in #9725.

![graphics-bug-1](https://user-images.githubusercontent.com/165720/105635454-c9c30180-5e5a-11eb-8896-4f831736fd46.png)
![graphics-bug-2](https://user-images.githubusercontent.com/165720/105635456-cc255b80-5e5a-11eb-899f-1c069476e248.png)

**Steps to reproduce:**
1. Use a device with an Intel Haswell Mobile graphics chip.
2. Create a project using the GLES3 backend.
3. Create a scene with a camera pointing at either a Sprite3D or a MeshInstance with a SpatialMaterial that has transparency and alpha scissor enabled.
4. Optionally, give the camera an Environment that enables glow. You'll see the black rectangles without this, but they won't glow.
5. Or just run the Main.tscn scene in the attached reproducer.

![image_2021-01-24_15-32-56](https://user-images.githubusercontent.com/165720/105635579-80bf7d00-5e5b-11eb-83fd-bd63bed8e441.png)

**Minimal reproduction project:**
[haswell-glow-bug.zip](https://github.com/godotengine/godot/files/5862570/haswell-glow-bug.zip)

**Comment by Calinou** [comment] 2021-01-24 16:01
I see you're displaying the FPS in the window title. Doing this alone can decrease performance significantly as the window title will change very often, which X11 doesn't like.

I recommend using a Label to display the FPS instead.

**Comment by tcoxon** [comment] 2021-01-24 16:33
Thanks for the tips! Much appreciated.

Just tried Windows 10 on the same hardware, and it's unaffected by the flickering black rectangle bug.

**Comment by akien-mga** [comment] 2021-01-24 17:41
Which Haswell IGP is it exactly? See GPUs listed on https://en.m.wikipedia.org/wiki/Haswell_(microarchitecture)

I've been using Godot with an Ivy Bridge HD 4000 in the past with Mesa without major issues, but this might have regressed. I'll dig up the old machine to try again.

It might be worth testing olwith newer Mesa too as there's been tons of fixes since the version in Ubuntu 16.04.

**Comment by tcoxon** [comment] 2021-01-24 18:34
It's an Intel Iris Pro Graphics 5200.

**Comment by akien-mga** [comment] 2021-02-06 22:52
Might be worth testing with 3.2.2-stable to see if this glitch might have been exposed by changing Sprite3D from ImmediateGeometry to MeshInstance. CC @clayjohn

**Comment by akien-mga** [comment] 2021-02-15 14:03
Finally dug up my old laptop, I can't reproduce the bug on Mageia 7 with Mesa 19.1.0 running on Intel HD Graphics 4000 (Ivy Bridge).

I'd suggest testing with a newer Mesa version to see if it has been fixed since 18.0.5.

**Comment by tcoxon** [comment] 2021-08-08 22:36
I upgraded to a newer Ubuntu on my old laptop and verified that Mesa 20.0.8 doesn't have the black rectangles (and the performance is waaay better too).

That's with:
* The same hardware
* The same engine (although a different build of the game but that should make no difference)
* Ubuntu 18.04 instead of Ubuntu 16.04
* Mesa 20.0.8 instead of 18.0.5

It's possible that something else in the OS upgrade affected it, but it seems unlikely.

**Comment by akien-mga** [comment] 2021-08-08 22:46
Sounds like this was indeed a Mesa driver bug which has been fixed between 18.0.5 and 20.0.8. The overall reliability and performance of Mesa has increased a lot in recent years.

I guess we can close this as not a Godot bug / not fixable (or worth fixing)? The percentage of Linux gamers still on Ubuntu 16.04 is likely very low. More concerning might be users on Debian 10 which is the current stable version and also with Mesa 18.3.6... but Debian and Linux distros in general need to provide backports of recent Mesa versions if they want their users to have a decent gaming experience.

**Comment by tcoxon** [comment] 2021-08-08 22:53
Yes it makes sense to close it IMO. Thanks!

**Closed** 2021-08-08 22:56 UTC
Labels: bug, topic:rendering
