### ISSUE TITLE
Particle2D Gives Strange Values and inConsistent Format on Inspector

### ISSUE THREAD

**Issue by ScotFlux** [godotengine/godot#5839] opened 2016-07-21 14:29 UTC
- Win 7, Win 10 x64
- Godot 2.1beta

**Issue description : **

=> Happened : Strange Values and InConsistent Format on Particles2D node's Parameter Modifier.
[ Let's Modify Some Params values ]

a.) Spread --> type "180" --> 179.999996 displayed --> Now, type "22.3" --> Increase the value using up arrow until "22.5" --> Seeing some weird values and inconsistent format, right?
b.) Linear Velocity --> type "60" --> 59.999999 displayed --> Now, type "22.3" --> Increase the value using up arrow until "22.5" --> Seeing some weird values and inconsistent format, right?

=> Expected : It should be clear. When I put "180", then Editor should say "180". And the format should be consistent, if max decimal places allowed was 2, then the editor should cap the value to max 2 decimal place.

**Steps to reproduce : **

- Just do as described on the "Happened" section above.

**Link to minimal example project : **
- None

**Comment by bojidar-bg** [comment] 2016-07-21 14:34
Duplicate of #5826

**Closed by bojidar-bg** 2016-07-21 14:34 UTC

**Comment by ScotFlux** [comment] 2016-07-21 14:48
Actually, I've read #5826 before posting a new issue. What comes to my mind is Particles2D and Inconsistent decimal places the Editor (Inspector) took. Also, still on Particles2D, some parameter start its strange values not from 22.3, instead from 33.5.

But, I believe you (the awesome bugsquad) know what the best.

Now, waiting for (a fix) Godot. :smile:

**Comment by bojidar-bg** [comment] 2016-07-21 14:58
@ScotFlux Well, doesn't matter where it starts exactly, it should be the same underlining issue in the end.

**Comment by ScotFlux** [comment] 2016-08-06 02:47
Fixed by [https://github.com/godotengine/godot/commit/9151eb591dcab408d3a7e4d9e3b3874c2e281acf](url)

I feeeel good (whoa-oa-oa!)
