### ISSUE TITLE
3.2.4 beta 4: Image set in the Boot Splash->Image scaled very large

### ISSUE THREAD

**Issue by alexzheng** [godotengine/godot#44618] opened 2020-12-23 15:25 UTC
**Godot version:**

3.2.4 beta4

**OS/device including version:**

**Issue description:**

the boot splash is scaled even the Fullsize is not checked. 

**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by Calinou** [comment] 2020-12-23 18:14
> **OS/device including version:**

Please fill in the issue template and include a minimal reproduction project.

**Comment by alexzheng** [comment] 2020-12-24 03:29
maybe the same as #43726

**Comment by Calinou** [comment] 2020-12-24 13:47
Duplicate of #43726.

**Closed by Calinou** 2020-12-24 13:47 UTC
