### ISSUE TITLE
Environment Contribution in shader only updates after Tween or AnimationPlayer have finished playing their transition.

### ISSUE THREAD

**Issue by TheConceptBoy** [godotengine/godot#60217] opened 2022-04-13 18:18 UTC
### Godot version

3.4.3.stable

### System information

Win 10k, ATI RX570

### Issue description

Here you can see the ground shader only updates it's light contribution after the animation is finished. So this makes Day Night transition impossible with Procedural skies, which allows you to ,move the sun and control the colors of the sky/ ground / horizons.

https://user-images.githubusercontent.com/52581279/163244514-a72deef5-db8f-441c-956f-e28fb666480c.mp4

Now I am using a plugin for terrain so here I have also shown the spatial material on this tree also not reacting to sky contribution changes until the animation is finished:

https://user-images.githubusercontent.com/52581279/163245224-680927da-d9c3-4aed-9b16-2cfc8ad16660.mp4

### Steps to reproduce

1) Set up a procedural sky and ground mesh
2) animate it's sky Top Color and Horizon Color with an animation player
3) play the animation.

**Comment by Calinou** [comment] 2022-04-13 18:47
Due to how it's generated, the radiance map is not designed to be updated every frame in Godot 3.x.

**Comment by TheConceptBoy** [comment] 2022-04-13 18:59
Ah, I see. In that case, perhaps adding update frequency setting to Tween and Animation player could also be useful for animating these things?  Something that adds the ability for the tween and animation player to update the values every so often instead of every frame. Until then I can produce a manually written solution as you mentioned. 

Either that or add the ability to remove all sky contributions on the side of the environment node rather than in each and every spatial material but keep the sky color and control ambient light as a workaround. There is the energy slider for sky and ground but that also makes the sky disappear.

**Comment by Calinou** [comment] 2022-04-13 19:06
> Ah, I see. In that case, perhaps adding update frequency setting to Tween and Animation player could also be useful for animating these things?

AnimationPlayer has a **Manual** update mode, which allows you to step through the animation with a script (`stepify()` can be useful here).

**Comment by TheConceptBoy** [comment] 2022-04-13 20:09
Is it possible to force update the sky contribution? In my case sky contribution is already set to 0

**Comment by TheConceptBoy** [comment] 2022-04-13 20:26
Actually seems like the timer solution produces a very visible stutter every time the engine recalculates global illumination. So even if it's done every 5 seconds, that just causes a stutter every 5 seconds.

**Comment by Calinou** [comment] 2022-04-13 22:54
> Maybe there should be an option to do that.

These options are available in Godot 4.0, but not in Godot 3.x.

In the meantime, to reduce stuttering, you can reduce **Radiance Size** in ProceduralSky or PanoramaSky to its lowest allowed value.

Also, set the following project settings:

- `rendering/quality/reflections/texture_array_reflections` to `false`
- `rendering/quality/reflections/high_quality_ggx` to `false`
- `rendering/quality/reflections/irradiance_max_size` to `32`

**Comment by Calinou** [comment] 2023-04-11 23:11
- Duplicate of https://github.com/godotengine/godot/issues/54397 (same cause).

**Closed by Calinou** 2023-04-11 23:11 UTC
Labels: topic:rendering, documentation, topic:3d
