### ISSUE TITLE
Resizing Control sometime breaks it by setting position to -nan(id)

### ISSUE THREAD

**Issue by pgoral** [godotengine/godot#29826] opened 2019-06-16 10:10 UTC
**Godot version:**
9c7cce3c9b8062817e976676ff0f4772971895cb

**OS/device including version:**
Windows 10

**Issue description:**
![godotbugwithcontrolresize](https://user-images.githubusercontent.com/11059246/59562668-a2297780-902f-11e9-8db4-715d41e30d31.gif)

**Steps to reproduce:**
Add new child Control to Node2D. Now star dragging it's bottm right  corner. 
Control rectangle vanishes and it's Rect position and size are set to -nan(id) and cannot be changed. This happens sometimes (try several times)

**Comment by KoBeWi** [comment] 2019-06-16 12:20
Duplicate of #29305

**Closed by KoBeWi** 2019-06-16 12:20 UTC
