### ISSUE TITLE
Engine Crash with latest 3.5 Beta 2+, related to Outline Font Size, Dynamic Font

### ISSUE THREAD

**Issue by RebelliousX** [godotengine/godot#60863] opened 2022-05-07 19:55 UTC
### Godot version

3.5 Beta 5

### System information

Windows 11 Gles 2 or 3

### Issue description

In v3.4.x everything is working fine, issue started happening when I started using v3.5 betas.
I was trying to open a project that works fine in v3.4.x, but the engine crashes immediately after loading the project in v3.5.

The engine crashes without any error message to the console, I even ran Godot with --verbose, nothing shows up in the console
related to the crash.

I was able to pinpoint when the crash happens, it seems it is related to Font Outline size when it becomes larger than specific
number. The number can be different, depending on the size of the font. For example, when the font size is 16, it crashes at outline size 12. When font is 60, it crashes when outline is 10.

### Steps to reproduce

Using the provided minimal project:
Select Label, change the font Outline Size, increment it slowly, it will crash at 12. But this number can be different, it depends on the size of the font.

If you want to reproduce this yourself:
New Project -> Create Root Node: User Interface -> Add Label as a child ->
Text: Hello World!! -> Theme Overrides -> Fonts -> Font: New DynamicFont ->
Font Data: (Load any TTF font) -> Click on DynamicFont from Dropdown list-> 
Settings (just under DynamicFont dropdown list) -> Change the outline color to black (so we can see it easily) ->
Change Outline Size (SLOWLY INCREASING!!). Eventually it will crash!

In this example, it crashed at 12 Outline Size, if the size of the font is 60,
it will crash at 10 or any other number. It is just random.

It seems the max outline size is 255, which works fine in Beta1 and v3.4.x.

### Minimal reproduction project

[test 123.zip](https://github.com/godotengine/godot/files/8645845/test.123.zip)

**Comment by Calinou** [comment] 2022-05-07 20:03
@RebelliousX Can you reproduce this in any of the [older 3.5 betas](https://downloads.tuxfamily.org/godotengine/3.5/) to determine when the regression started?

**Comment by RebelliousX** [comment] 2022-05-07 20:09
@Calinou Yeah, sorry about that, I just tested it. Beta 1 is okay, crashes are happening on Beta 2+.

**Comment by Calinou** [comment] 2022-05-07 21:20
cc @bruvzg

**Comment by bruvzg** [comment] 2022-05-07 21:29
Can't reproduce it on macOS, and nothing in the Font or Label seems to be changed in between beta 1 and 2. So it might be Windows specific (will test it tomorrow).

**Comment by gotnospirit** [comment] 2022-05-07 23:12
Can't reproduce on Windows 10 also. Tried betas from 1 to 5, either 32 bits or 64 bits, randomly changing GLES, but still was able to manually change the outline size from 0 to 255 without any crash

**Comment by RebelliousX** [comment] 2022-05-08 00:22
This is a video showing the bug

<a href="http://www.youtube.com/watch?feature=player_embedded&v=3V5aT6xEl0w" target="_blank">
 <img src="http://img.youtube.com/vi/3V5aT6xEl0w/mqdefault.jpg" alt="Watch the video" width="495" height="270" border="10" />
</a>

**Comment by gotnospirit** [comment] 2022-05-09 03:53
Tried with Test.ttf found in #50951 with official beta 5 x64 but no crash too. @jnlopar What's your version of Windows?
![Sans titre](https://user-images.githubusercontent.com/12656483/167337721-bd9f38a6-bf75-467d-9ae9-1d5b6974df9d.png)

**Comment by jnlopar** [comment] 2022-05-09 03:59
@gotnospirit Windows 11 Pro 10.0.22000 Build 22000

**Comment by gotnospirit** [comment] 2022-05-09 04:09
Thank you. Just in case it can help the others, mine is "Windows 10 Family 10.0.18362 Build 18362"

**Comment by RebelliousX** [comment] 2022-05-22 06:27
Is this also related to this https://github.com/godotengine/godot/issues/59794
A freeTupe library update was done in 3.5 Beta 2. It changed the way it renders fonts?!

**Comment by meowyih** [comment] 2022-05-25 03:39
In my case, this is not really caused only by outline. I can reproduce the same crash issue using following two setting:
1. increase the font size to 128, or
2. increase the font size to 64 and outline size to 3

Window11 x64
Godot v3.5.beta5.official [815f7fe63]

[ThemeCrash.zip](https://github.com/godotengine/godot/files/8767704/ThemeCrash.zip)
![ThemeCrash](https://user-images.githubusercontent.com/32887778/170174444-9fde53ca-2e3a-4a9b-9609-3942eef06bbb.png)

**Comment by ondesic** [comment] 2022-05-26 16:19
Just tested 3.5 RC2.  I have a dynamic font set to 100 in size.  If I change the outline to 8, Godot crashes.  Godot 3.4.4 does not crash with the same settings.

**Comment by rambda** [comment] 2022-06-09 10:57
Can confirm.

These fonts cause crash, when over 100 size.
[Josefin_Sans.zip](https://github.com/godotengine/godot/files/8869583/Josefin_Sans.zip) SIL Open Font License, downloaded from Google font
[Nunito.zip](https://github.com/godotengine/godot/files/8869584/Nunito.zip) SIL Open Font License, downloaded from Google font

These are OK, size can be very big without causing a crash.
[Poppins.zip](https://github.com/godotengine/godot/files/8869585/Poppins.zip) SIL Open Font License, downloaded from Google font
[texgyreadventor.zip](https://github.com/godotengine/godot/files/8869589/texgyreadventor.zip) GUST Font License / LPPL License
[SourceHanSansCN-Regular.zip](https://github.com/godotengine/godot/files/8869595/SourceHanSansCN-Regular.zip) SIL Open Font License, downloaded from Adobe font

Also, even if the font size is set smaller, but the stretch mode is 2d expand.
In this case, if the game window size is small, below a certain threshold, like 800 x 450, the game will not crash at all. 
If the game window is larger than that threshold, the game will 100% crash.

**Comment by bruvzg** [comment] 2022-06-09 11:20
Seems like the same issue as #61499, so it should be fixed by #61803.

**Comment by akien-mga** [comment] 2022-06-09 11:22
Updated version of the MRP which should crash on start (can't test as I don't have Windows 11), with the font size set to 400:
[FreeTypeFontCrash.zip](https://github.com/godotengine/godot/files/8869826/FreeTypeFontCrash.zip)

**Comment by akien-mga** [comment] 2022-06-09 11:26
Here's a compiled version of current Godot `3.x` (19fec70580) with @bruvzg's fix: https://downloads.tuxfamily.org/godotengine/testing/Godot_v3.5-rc-freetype-fix_win64.exe.zip

Could you confirm that it solves your crash @RebelliousX @jnlopar @meowyih @ondesic @rambda?

**Comment by rambda** [comment] 2022-06-09 11:50
> Here's a compiled version of current Godot `3.x` ([19fec70](https://github.com/godotengine/godot/commit/19fec70580452a630841ea579e3ffcd0b5c2bf05)) with @bruvzg's fix: https://downloads.tuxfamily.org/godotengine/testing/Godot_v3.5-rc-freetype-fix_win64.exe.zip
> 
> Could you confirm that it solves your crash @RebelliousX @jnlopar @meowyih @ondesic @rambda?

Problem solved. Thanks! @bruvzg @akien-mga

**Comment by akien-mga** [comment] 2022-06-09 12:29
Fixed by #61803.

**Closed** 2022-06-09 12:28 UTC
Labels: bug, confirmed, crash, regression, topic:gui
