### ISSUE TITLE
CollisionObject in process pause mode doesn't emit mouse_entered/exited signals when paused

### ISSUE THREAD

**Issue by makepanic** [godotengine/godot#39094] opened 2020-05-27 17:54 UTC
**Godot version:**
3.2.1.stable.official

**Issue description:**

**given**:

* a `CollisionObject` (Area) with connections to`mouse_entered` and `mouse_exited`
* the `CollisionObject` pause mode is set to `process`
* the tree is paused

**expected**:

* `mouse_entered` / `mouse_existed` signals should fire if the mouse enters or exists the object

**actual**:

* no signal is emitted

Demo video: https://streamable.com/ini8fw

It might be possible that this is expected behavior. 
I found this issue when following the [GUI in 3D](https://github.com/godotengine/godot-demo-projects/tree/master/viewport/gui_in_3d) demo project. 

Without having the mouse entered/existed signals when paused, it seems to be impossible to use a GUI in 3D.

Is there maybe another recommended way to implement a GUI in 3D that supports pausing the tree?

**Minimal reproduction project:**
[area_paused.zip](https://github.com/godotengine/godot/files/4690816/area_paused.zip)

**Comment by madmiraal** [comment] 2020-05-28 09:08
Duplicate of #38370, but you make a valid point:
> Without having the mouse entered/existed signals when paused, it seems to be impossible to use a GUI in 3D.

**Closed** 2020-05-28 09:08 UTC
