### ISSUE TITLE
Add warning when importing SVGs using units other than pixels

### ISSUE THREAD

**Issue by novemberist** [godotengine/godot#10835] opened 2017-08-31 19:27 UTC
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Arch Linux, Godot 3 master https://github.com/godotengine/godot/commit/a717083235b3369aef9a3846b5071fac023a60b2

**Issue description:**
When I try to import svg graphics with mipmaps enabled, I get the following error messages in the console:

```
to gen mipmaps w 349 h 665 format RGBA8 mipmaps 9 new size is: 1235952
libpng warning: Image width is zero in IHDR
libpng error: Invalid IHDR data
ERROR: _lossless_pack_png: Method/Function Failed, returning: PoolVector<uint8_t>()
   At: drivers/png/image_loader_png.cpp:311.
success
ERROR: _lossless_unpack_png: Condition ' len < 4 ' is true. returned: Ref<Image>()
   At: drivers/png/image_loader_png.cpp:259.
ERROR: _load_data: Condition ' img.is_null() || img->empty() ' is true. returned: ERR_FILE_CORRUPT
   At: scene/resources/texture.cpp:526.
```

Running a project that uses these textures is not possible (game window closes immediately)

**Comment by djrm** [comment] 2017-09-01 16:58
@novemberist please post the svg you are trying to import

**Comment by novemberist** [comment] 2017-09-01 17:03
@djrm happens with any svg I have tried so far, even the most basic.

e.g.
[circle.tar.gz](https://github.com/godotengine/godot/files/1270972/circle.tar.gz)
*packed because github doesn't support uploading svgs

**Comment by djrm** [comment] 2017-09-01 17:18
@novemberlist the problem with your SVGs, is that they use millimeters as unit, and the current importer expects pixels, so set up your svg editor to use pixels instead.

**Comment by djrm** [comment] 2017-09-01 17:20
maybe it should be reported as an invalid file.

**Comment by novemberist** [comment] 2017-09-01 17:33
@djrm I don't think this makes a difference. I have set every  setting i could find to pixels in inkscape and it still gives me the same error.

besides, wouldn't there be a way to automatically convert from millimeters to pixels on import in some way? I think most vector editors (and thus most svg graphics) use millimeters by default...

**Comment by djrm** [comment] 2017-09-01 17:36
@novemberist the default unit for an svg is pixels, i dont know how hard would be to handle the several units used by svg, (in, cm, ...etc).

**Comment by novemberist** [comment] 2017-09-01 17:39
I never knew units were stored in the svg file itself, always assumed this was merely a setting relevant for editing. will check again and try different svg editors.

**Comment by novemberist** [comment] 2017-09-01 17:40
and to reiterate: importing svgs works fine for me unless i turn on mipmaps (which means there surely must be some way to import svgs that use mm as units?)

**Comment by djrm** [comment] 2017-09-01 17:45
@novemberist yeah i checked out your example, and indeed it fails when using mipmpas, however it does not fail when the same file uses pixels, i guess the importer is converting mm to pixels, like 1mm = 1px, simply ignoring the, i think i will add support for different units, and see if that solves this kind of problems

**Comment by novemberist** [comment] 2017-09-01 17:52
good to know that. but there should definitely be a warning/hint about using svgs in other units but pixels, given e.g. inkscape afaik doesn't use pixels by default and users might thus encounter crashes without knowing why this happens.

**Comment by djrm** [comment] 2017-09-01 17:53
@novemberist yeah, we will work on that.

**Comment by Zylann** [comment] 2017-09-02 14:12
Why are mm not a good idea? Is it because of the generated image could be too big? Note that if we were to add import SVG as mesh, that wouldn't be that problematic, should be remembered when this becomes supported

**Comment by djrm** [comment] 2017-09-04 18:55
@Zylann the problem, is that it could be misleading, maybe some people dont event expect those kind of units in their svgs, also, since the 2D engine uses pixels it would be better to match those units (to be honest i dont see the point in supporting those units, they are the for printing and html compatibility but not for games), im not sure about this one, but we need to check pixel density in order to correcly render non pixel units (i dont think nanosvg handles pixel density).

**Comment by reduz** [comment] 2017-11-06 13:53
@djrm is this a bug then or should we close?

**Comment by djrm** [comment] 2017-11-06 19:07
@reduz im not sure if this is a bug, but i cant figure out why it only happens when creating mipmaps using millimeters, but using px units solves the problem and pixels are the required unit for imported svgs.

**Comment by mhilbrunner** [comment] 2018-01-03 18:58
Should be renamed to **Add warning when importing SVGs using units other than pixels**.

**Comment by akien-mga** [comment] 2018-01-08 12:10
We have now entered release freeze for Godot 3.0 and want to focus only on release critical issues for that milestone. Therefore, we're moving this issue to the 3.1 milestone, though a fix may be made available for a 3.0.x maintenance release after it has been tested in the master branch during 3.1 development. If you consider that this issue is critical enough to warrant blocking the 3.0 release until fixed, please comment so that we can assess it more in-depth.

**Comment by 2shady4u** [comment] 2019-08-05 10:41
I can't replicate this error anymore in Godot v3.1 stable and it might have been fixed somewhere along the line.

Could this be confirmed? @novemberist @djrm @akien-mga

**Comment by BCleveland** [comment] 2019-08-05 15:46
I'm not getting any errors importing the given SVG either

**Comment by dsaltares** [comment] 2019-10-06 06:01
I tried the following:
* Create SVG on Inkscape with units set to cm
* Import the SVG into a Godot project enabling mipmaps
* Run project from the editor

It works just fine.

**Comment by KoBeWi** [comment] 2019-10-13 22:04
Yeah, this no longer happens. Tested with the .svg provided in the issue.

**Closed by KoBeWi** 2019-10-13 22:04 UTC
Labels: enhancement, junior job, topic:core
