### ISSUE TITLE
Applying materials to CSG meshes makes them invisible

### ISSUE THREAD

**Issue by OscarCookeAbbott** [godotengine/godot#60290] opened 2022-04-16 03:06 UTC
### Godot version

4.0 Alpha 6

### System information

macOS Monterey 12.3, Vulkan Mobile, Apple M1 Pro

### Issue description

When adding a material to any CSG node, the node becomes invisible but effects like AO still apply to nearby objects. Making the material transparent makes the node visible.

<img width="1728" alt="image" src="https://user-images.githubusercontent.com/19225102/163658989-452419c7-63d4-4ac3-8f01-08e6fd8f81e0.png">

Could it be something going awry with the depth buffer?

### Steps to reproduce

1. Open a scene in Godot
2. Create a CSG (Box, Cylinder, etc) node
3. Assign a material to the CSG node's `material` field

### Minimal reproduction project

[GodotCSGProject.zip](https://github.com/godotengine/godot/files/8499152/GodotCSGProject.zip)

**Comment by Calinou** [comment] 2022-04-16 10:55
Duplicate of https://github.com/godotengine/godot/issues/51898.

**Closed by Calinou** 2022-04-16 10:55 UTC
