### ISSUE TITLE
Godot v3 seems not implementing proper conversion for [win32 resolution]

### ISSUE THREAD

**Issue by talapink** [godotengine/godot#56360] opened 2021-12-30 23:10 UTC
### Godot version

v3.4.2.stable.official [45eaa2daf]

### System information

Windows 11 ASUS ROG flow X13 32GB GF1650

### Issue description

- I did find
   + all debug screen from [run? button] appear far right down of my screen.
- on environment
  + Windows 11
  + 4K real screen
  + 25% scale
  + logical full screen size for this is around 1500? X 700?
      ( Screen.PrimaryScreen for WinForm NET 4.8, NET 5 and up behave different, so I do not know. )
- I suggest
  + GL's answer for Rectangle is from driver, but when locate you need to get Local Logical desktop Value and convert
  + or your drawing go offscreen (too far).  I think Win11 relocate new window automatically as window go total offscreen.
  + forget about multiscreen resolution issue (this one require offscreen rendering and copy rendering result to 2 partial window, performance cost will be too expensive comparing return, let users to jump windows between screens will be more beneficial.)
- conclusion
  + I just start evaluating Godot so sorry for bad report
  + I just wished you guys don't forget to handle logical coordinate mapping for Godot 4 (quite important as most system start implementing multiple -virtual- workspace)
  + I start code again after 30 years ,so please forgive my lousy report (my start carrier was from 6502 and ended with PowerPC)
  + I wish you project to prosper

### Steps to reproduce

1 use Windows 11
2 change resolution to other than 100%
3 you will find windows appear funny places.

### Minimal reproduction project

all for your demo project (I did try 4 from search "multitouch")

**Comment by Calinou** [comment] 2021-12-30 23:27
Duplicate of https://github.com/godotengine/godot/issues/24922 and/or https://github.com/godotengine/godot/issues/13017.

**Closed by Calinou** 2021-12-30 23:27 UTC
