### ISSUE TITLE
Multiple Voxel GIs do not blend together properly

### ISSUE THREAD

**Issue by dam482** [godotengine/godot#86270] opened 2023-12-17 19:34 UTC
### Tested versions

Reproducible in v4.2.stable.mono.official

### System information

Windows 11 - Nvidia GTX 1070

### Issue description

It appears a Voxel GI node can only blend properly with at most one other Voxel GI node.  If you create a Voxel GI node that overlaps 2 others, only 1 edge will blend properly, all the other edges will be hard instead of blended.

### Steps to reproduce

In the example project, there are 3 voxel GI nodes, each with a small amount of overlap with other Voxel GIs in order to blend them. One of the edges is always correct, but the other edge will always have a hard edge.  You can toggle the visibility of the Voxel GI nodes, and it causes the hard edge to move depending on the order in which you toggle the Voxel GIs back on.

### Minimal reproduction project (MRP)

[VoxelGiBug.zip](https://github.com/godotengine/godot/files/13697526/VoxelGiBug.zip)

**Comment by bitsawer** [comment] 2023-12-17 20:10
Thanks for the report. This is an intentional design limitation, see https://github.com/godotengine/godot/issues/80361#issuecomment-1667292158. However, this should still be documented, so closing this as duplicate of https://github.com/godotengine/godot/issues/80361 to keep discussion in one place.

**Closed by bitsawer** 2023-12-17 20:10 UTC
Labels: bug, topic:rendering, needs testing, topic:3d
