### ISSUE TITLE
[3.2.2 beta 1] Broken shadows in GLES2 mode

### ISSUE THREAD

**Issue by drcucaracha** [godotengine/godot#38094] opened 2020-04-21 19:09 UTC
**Godot version:**
godot 3.2.2 beta 1
**OS/device including version:**
windows 7 64bit
**Issue description:**
in gles2 the shadows bug when having a winged character of another person with animation the leftovers follow it only in static walls it does not happen
(translated with google translator)
**Steps to reproduce:**
download 3d platform from the asett and stand next to an enemy
**Minimal reproduction project:**

<a href="https://ibb.co/N7GbHrX"><img src="https://i.ibb.co/b7GD8Fx/01.png" alt="01" border="0" /></a> godot 3.2.1 stable

<a href="https://ibb.co/PgRNTng"><img src="https://i.ibb.co/M7bs847/02.png" alt="02" border="0" /></a> godot 3.2.2 beta 1

<a href="https://ibb.co/0CGQDDH"><img src="https://i.ibb.co/pfLn00Y/03.png" alt="03" border="0" /></a> godot 3.2.2 beta 1

**Comment by clayjohn** [comment] 2020-04-21 21:38
I have been able to reproduce in the 3D platformer demo. but I have to go to the exact spot you are standing when you took that screenshot. I can't reproduce the issue anywhere else in the demo. I will look into the cause, 4d32652851b7af5ea6f70f05fca3cedd11808b1b seems to be the only likely candidate.

**Comment by drcucaracha** [comment] 2020-04-21 21:49
@clayjohn  If I know it in the first photos where I use a model of the doom guy it reproduces much easier only that the project weighs more than 300mb because it is for tests since I am learning to pica code for that reason I did not upload a test file and I did not I found something in the asset to reproduce since it has to have a character and an enemy with animations to make it more clearly visible

**Comment by clayjohn** [comment] 2020-04-22 00:52
@drcucaracha I have made a PR with a fix. Thanks for reporting this issue. :)

**Comment by drcucaracha** [comment] 2020-04-22 01:01
thanks so much for fixing the bug :)

**Comment by akien-mga** [comment] 2020-04-22 07:42
Fixed by #38099.

**Closed by akien-mga** 2020-04-22 07:42 UTC
Labels: bug, confirmed, regression, topic:rendering
