### ISSUE TITLE
Mono: exception creating TcpClient

### ISSUE THREAD

**Issue by shawkes** [godotengine/godot#25199] opened 2019-01-21 21:05 UTC
**Godot version:**

3.1 Beta 1 & 2 

**OS/device including version:**
Windows 10

**Issue description:**
Running the following code:
`var tcpClient = new TcpClient("127.0.0.1", 4649);`

results in:
```
ERROR: _get_socket_error: Socket error: 10054
   At: drivers/unix/net_socket_posix.cpp:190
```

Looks like NetSocketPosix::connect_to_host calls the winsock2 connect method which is failing, then WSAGetLastError returns that error.

Further investigation makes it appear that the arguments for that constructor aren't being passed to the lower level correctly because the following works with no error:

```
	IPAddress ip = IPAddress.Parse("127.0.0.1");
        tcpClient = new TcpClient();
        tcpClient.Connect(ip, 4649);
```

This can be used as a workaround, however any libraries that call that particular constructor will fail unless modified to use a different constructor (in this case I was attempting to use websocket-sharp).

**Steps to reproduce:**
Run a project that calls that particular constructor for TcpClient. The player will crash.

**Minimal reproduction project:**
Can be provided if wanted. Any project with the one line of code will fail. Create a node with a c# script using that particular constructor _System.Net.Socket.TcpClient(string, int)_

**Comment by akien-mga** [comment] 2019-01-22 08:13
CC @neikeq @hpvb

**Comment by sghawkes** [comment] 2019-01-22 20:58
> Yeah, detected it too, however at beta 1 it was ok(at least at custom builds)

I reproduced it on Beta 1 Windows 64 (official dev snapshot)

Strange it was fine on a custom builds. I think it's at the glue level (or wherever mono crosses over into core io). It's just that one constructor that is failing.

I changed the code in websocket-sharp from calling that constructor to my example workaround and it works (default constructor followed by connect with target) and it seems to work fine. I can use the library to connect to a websocket, send messages etc.

**Comment by sghawkes** [comment] 2019-01-23 17:54
How is the mono dev release built? I'm curious about this not being an issue on a custom build vs the dev release. Is some individual manually compiling the releases or is it some form of build automation?

If it's automated how is the multi-step build for mono being handled?

I'm not yet set up to build godot from source, though it looks like I may have to set myself up if I plan on using godot seriously so I can track down stuff like this myself.

**Comment by Chaosus** [comment] 2019-01-26 09:14
I think its a duplicate of #21655, same error condition..

**Closed by Chaosus** 2019-01-26 09:14 UTC
Labels: bug, confirmed, high priority, topic:mono, topic:network

**Comment by neikeq** [comment] 2019-01-27 17:54
I'm replying here because I don't know if this is related to #21655.

Running your example code resulted in the following unhandled exception that can be viewed in the editor: `System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:4649`.

Is there any server listening on that port? In my case, the following works:

``` C#
string address = "127.0.0.1";
int port = 4649;

var server = new TcpListener(IPAddress.Parse(address), port);
server.Start();

var tcpClient = new TcpClient(address, port);
```

**Comment by Chaosus** [comment] 2019-01-27 18:05
@neikeq Tested this code right now - it will crash at beta 3 **final** build

![image](https://user-images.githubusercontent.com/3036176/51804885-22189600-2277-11e9-9e29-0d408d1619bc.png)

**Comment by Chaosus** [comment] 2019-01-27 18:08
That means it will work at custom builds but failed when used binary from https://downloads.tuxfamily.org/godotengine/3.1/beta3/mono/

**Comment by neikeq** [comment] 2019-01-27 18:57
Forgot to test with the official builds. I can reproduce both this and #21655 now.
