### ISSUE TITLE
Minimizing editor on Windows causes crash.

### ISSUE THREAD

**Issue by MissEmbyr** [godotengine/godot#38423] opened 2020-05-03 02:48 UTC
Version: Master Branch (tested at f5cd33f)

Windows 10 / RTX 2070

Minimizing editor on Windows causes crash.

- Create empty Vulkan project, 
- Minimize editor.

**Comment by KoBeWi** [comment] 2020-05-03 08:07
Duplicate of #37327

**Closed by KoBeWi** 2020-05-03 08:07 UTC
