### ISSUE TITLE
Vulkan: ReflectionProbes bakes wrong side of mesh when cull mode is Disabled

### ISSUE THREAD

**Issue by jcostello** [godotengine/godot#63937] opened 2022-08-05 03:42 UTC
### Godot version

v4.0.alpha.custom_build [1afc83d0a]

### System information

Ubuntu 21.04. RTX 2060

### Issue description

ReflectionProbes bakes wrong side of mesh when curl mode is disabled

Disabled

![image](https://user-images.githubusercontent.com/1168582/182996924-1f153573-89c2-4265-94dd-565ab816f31a.png)

Back

![image](https://user-images.githubusercontent.com/1168582/182997002-0cb736b5-76e7-4d6d-9d2e-17642a2004c4.png)

### Steps to reproduce

Main scene in MRP

### Minimal reproduction project

[Reflections.zip](https://github.com/godotengine/godot/files/9265035/Reflections.zip)

**Comment by Calinou** [comment] 2022-08-05 06:53
Duplicate of https://github.com/godotengine/godot/issues/38442.

**Closed by Calinou** 2022-08-05 06:53 UTC
Labels: bug, topic:rendering, topic:3d
