### ISSUE TITLE
[LSP] Inconsistent autocomplete suggestion with `get_node` and typed variables.

### ISSUE THREAD

**Issue by linkpy** [godotengine/godot#43136] opened 2020-10-27 15:02 UTC
**Godot version:**
3.2.3

**OS/device including version:**
Linux 5.4.0 (Linux Mint)

**Issue description:**
If the node doesn't exist, the LSP doesn't give the right autocompletion (checked in debug mode, the LSP server's message doesn't contain any members of the `Sprite` class and thus is a bug on the LSP server) :

![image](https://user-images.githubusercontent.com/2700596/97319338-118eb880-186d-11eb-86c6-485480aae84e.png)

If the node exists, the autocompletion works as intended :

![image](https://user-images.githubusercontent.com/2700596/97319607-54e92700-186d-11eb-84d3-60f836eee94e.png)

The autocomplete works as intended too when the node doesn't exists if the `get_node` call is cast :

![image](https://user-images.githubusercontent.com/2700596/97319766-7518e600-186d-11eb-97ec-0b549cc766ef.png)

Linked with https://github.com/godotengine/godot-vscode-plugin/issues/235.

**Steps to reproduce:**
See above screenshots.

**Minimal reproduction project:**
/

**Comment by Razoric480** [comment] 2021-03-23 17:00
This is consistent with the built-in GDScript editor. In fact, this is a case where the language server does a _better_ job than the GDScript editor. If you take the above code in the screenshots and try to get `is_pixel_opaque()` from a node that does not exist, both will not return anything. If you try with a node that does exist, and the _scene is closed_, the language server will find it but the GDScript editor will not. If the scene is opened, both find it.

It's still _wrong_, mind you, but it's not an LSP bug, as the LSP forwards the call to `GDScriptLanguage::complete_code()`, which is also called by the GDScript editor.

Because its actual type is assumed to be "Node" because the scene is closed or `get_node()` found nothing because the node doesn't exist, that's what it uses. Unless we actively cast to force the return type, it ignores the variable's static type hint.

**Comment by timothyqiu** [comment] 2021-04-02 03:51
I encountered a similar issue in the GDScript editor.

```gdscript
onready var foo: Spatial = get_parent()
```

Here `foo` should be `Spatial` and `get_parent()` returns `Node`. But the final type is a `Viewport` when the scene is open because the script is on the root node.

**Comment by cdemirer** [comment] 2022-07-07 08:08
Also see: #42005

**Comment by HolonProduction** [comment] 2024-10-14 10:58
Closing as duplicate of #53318

**Closed by HolonProduction** 2024-10-14 10:58 UTC
Labels: bug, topic:gdscript, topic:editor
