### ISSUE TITLE
Add a scaling axis

### ISSUE THREAD

**Issue by Andev08** [godotengine/godot#11235] opened 2017-09-13 13:39 UTC
**Issue description:**
Maybe I'm doing it wrong, but I can't seem to find the axis that allows you to resize an object on a single axis, like in Blender:
![image](https://user-images.githubusercontent.com/31744099/30380142-b3fe8768-9890-11e7-9fbb-f524b53ae4f5.png)

I can only find one that scales the object equally on all axis:
![image](https://user-images.githubusercontent.com/31744099/30380187-d1705da8-9890-11e7-8b0a-4fa441002ba3.png)

Which sure, is definitely useful, but a specific axis one would be great as well? If you wanted to save space or keep those buttons minimal, you could just add a surrounding circle to scaling axis, like you get with lights:
![image](https://user-images.githubusercontent.com/31744099/30380301-27477d56-9891-11e7-8c33-4a8654bf8883.png)
and that would scale it equally on all axis, and leaving the arrows (or blocks for scaling) to handle the individual axis.

It would certainly be easier than trying to enter each one in the transform menu, I always forget to press enter and have to re-enter it a couple of times.

**Comment by fracteed** [comment] 2017-09-14 01:12
This is a duplicate of #7419. It is a feature that is very conspicuous by its absence :)

**Closed** 2017-09-14 05:45 UTC
Labels: feature proposal, topic:editor
