### ISSUE TITLE
apply_torque_impulse does not wake sleeping RigidBody2D

### ISSUE THREAD

**Issue by krscott** [godotengine/godot#41396] opened 2020-08-20 12:59 UTC
**Godot version:**

Godot v3.2.2.stable.official

**OS/device including version:**

Windows 10 64-bit

**Issue description:**

It seems like if a RigidBody2D is sleeping, it can not be affected by `apply_impulse_torque`.

The [documentation](https://docs.godotengine.org/en/stable/classes/class_rigidbody2d.html#class-rigidbody2d-property-sleeping) says that `apply_impulse` will wake a sleeping RigidBody2D, so it seems like this should apply to `apply_impulse_torque` as well.

**Steps to reproduce:**

Call `apply_impulse_torque` on a sleeping RigidBody2D. It will not move.

Setting `can_sleep` to `false` fixes the issue.

**Minimal reproduction project:**

Github project, with gifs and workaround in README:
https://github.com/krscott/godot-rigidbody-bug-demo

zip of project:
[godot-rigidbody-bug-demo-master.zip](https://github.com/godotengine/godot/files/5103077/godot-rigidbody-bug-demo-master.zip)

**Comment by madmiraal** [comment] 2020-08-28 07:26
Duplicate of #40939, fixed with #40941.

**Closed by madmiraal** 2020-08-28 07:26 UTC
Labels: bug, topic:physics
