### ISSUE TITLE
Editor interface slides off screen, must restart to fix

### ISSUE THREAD

**Issue by tinmanjuggernaut** [godotengine/godot#30787] opened 2019-07-24 05:36 UTC
**Godot version:**
Godot 3.1.1 (present, but fixable in editor)
Godot Engine v3.2.c7a427241 Jul 23, 2019 (must restart editor to fix)

GeForce GTX 1060
Intel HD4400

Win10/64
Linux

1920x1080 screen

**Issue description:**

Certain conditions will bump the editor interface off the right edge of the viewport if the interface width is too small.

The problem becomes super annoying when working on a single monitor and your smaller godot window starts sliding your distraction free button and panels off screen! You have to know the shortcut (CTRL+SHIFT+F11) to get out of distraction free mode. 

Note, this is not a matter of there being fixed minimum sizes for some panels. The interface actually slides off screen to the right and requires a restart (in 3.2) to fix it.

The first two examples are from 3.2. Note the GLES and the panels slipping right.

![offset1](https://user-images.githubusercontent.com/632766/61764648-ec62fd00-ae14-11e9-8c0f-6a3d07513eaf.png)

Here, I have repeated the steps and it slid right even further! This is with a different project also.

![offset2](https://user-images.githubusercontent.com/632766/61764649-ec62fd00-ae14-11e9-9aef-e08b04f77ca9.png)

This example is from 3.1. See the GLES slipping right and the distraction free button is off screen.

![offset3](https://user-images.githubusercontent.com/632766/61764972-1537c200-ae16-11e9-8dd5-12ddf20fd674.png)

**Steps to reproduce:**

1. Put the view in 2D or 3D mode
1. Resize the width of the editor window somewhere under 1060 (measured visually), or just go to the minimim width where you can still see the spinning wheel next to GLES in 3.1 or just GLES in 3.2
1. Switch to script viewer and watch GLES and the panels slide right. Switching to assetlib sometimes repeated the shift for me.
1. Switch back to 2D and the right side is still off to the right

In 3.1 it's fixable just by resizing the window.

In 3.2 it's permanent until you restart. This also means you can repeat the shift and make it worse if you:
1. Switch to 2D/3D mode
1. Decrease the window width smaller than it was
1. Switch to script viewer

Another way to make this happen is to:
Reset the windows larger so they fit properly.
1. Switch to 2D
1. Click the distraction free button
1. Resize the width to minimum size required to still see the distraction free button (and GLES) 
1. Click the distraction free button to return to normal view. (The interface slides right)

This method doesn't even us the script view but still has the issue. If you click the distraction free button again to go into that mode, the only way to get out of it is to press the hot key CTRL+SHIFT+F11. 

In 3.1 resizing the window will fix it, but that's the opposite of distraction free!

In 3.2 you're stuck until restarting the editor.

**Minimal reproduction project:**

Any project, whether it has scripts or not. 2D or 3D. Windows or Linux.

**Comment by qarmin** [comment] 2019-07-24 06:44
Part about 3.2 version is duplicate of #29495

**Comment by tinmanjuggernaut** [comment] 2019-07-24 06:52
Ah, you're right. But my test cases and reproduction steps are far more specific and demonstrate it is in the stable release and windows. Should I close this?

**Comment by groud** [comment] 2019-07-24 08:21
Yep, closing as a duplicate of #29495

**Closed by groud** 2019-07-24 08:21 UTC

**Comment by akien-mga** [comment] 2019-07-27 11:00
#29495 was fixed by reverting the problematic PR.

This issue mentions that it's valid to some extent in 3.1.1 too, for which we don't have a bug report open. I'd suggest to open a new issue specific to the behaviour in the stable release and the current master branch, which should now be the same now that #29495 is fixed.
