### ISSUE TITLE
Unable to Compile on Windows with Case-sensitive Directories

### ISSUE THREAD

**Issue by joealam** [godotengine/godot#26804] opened 2019-03-08 22:12 UTC
(Partly just reporting this to make it searchable for other people having the same problem, as I couldn't find anything when I was trying to solve it, but also it may be a sign of some underlying issue)

**Godot version:**
60d910b1916305c4b0ac5f92415083995b4f7c7a

**OS/device including version:**
Windows 10
MSVC 10.0A (installed with Visual Studio 2017)

**Issue description:**
When attempting to compile for Windows, I get the following error:
```
C:\Workspace\godot\thirdparty\glad\glad/glad.h(93): fatal error C1083: Cannot open include file: 'KHR/khrplatform.h': No such file or directory
scons: *** [platform\windows\os_windows.windows.tools.64.obj] Error 2
scons: building terminated because of errors.
```
However, the file does exist and is in the correct location.
Note: The actual error may slightly differ if the compilation order of the cpp files changes, but it will always be a "missing" file which does exist and is in the correct location.

After some investigation, it seems this is caused by the directories having case sensitivity enabled.

**Steps to reproduce:**

1. Clone the repository (tested at 60d910b1916305c4b0ac5f92415083995b4f7c7a)
2. Enable case sensitivity on the directories (this can easily be done by cloning via Windows Subsystem for Linux, or see https://blogs.msdn.microsoft.com/commandline/2018/02/28/per-directory-case-sensitivity-and-wsl/)
3. Compile!

**Workaround/Solution:**

It is possible to solve this issue by simply removing the case sensitivity.
This can be done with a command something along the lines of:
```
cd affectedDirectory/
for /r /d %f in (.) do (fsutil file setCaseSensitiveInfo %f disable)
```

However, as far as I can see all of the cases of the files in the include directives are correct - so it seems that this _should_ work even with case sensitivity enabled.
Is it possible that some part of the build process (either Godot-specific or scons) is changing the case internally?

**Comment by akien-mga** [comment] 2019-03-08 22:20
That's pretty weird, given that Godot builds on case-sensitive filesystems for Linux and macOS, so there's definitely no case issue in our filenames or includes.

I guess there's an issue with the include paths, can you build with `scons verbose=yes` to see the full build command when it fails?

**Comment by joealam** [comment] 2019-03-17 14:25
Here's the snippet from the error when built with `verbose=yes`:
```
[Initial build] cl /Foplatform\windows\os_windows.windows.tools.64.obj /c platform\windows\os_windows.cpp /TP /nologo /Z7 /Od /EHsc /MT /Gd /GR /W3 /wd4267 /wd4244 /wd4305 /wd4018 /wd4800 /EHsc -DZSTD_STATIC_LINKING_ONLY -DFREETYPE_ENABLED -DSVG_ENABLED -DGLAD_ENABLED -DGLES_OVER_GL /DDEBUG_MEMORY_ALLOC /DDISABLE_FORCED_INLINE /DDEBUG_ENABLED /DDEBUG_MEMORY_ENABLED /DD3D_DEBUG_INFO /DWINDOWS_ENABLED /DOPENGL_ENABLED /DWASAPI_ENABLED /DWINMIDI_ENABLED /DTYPED_METHOD_BIND /DWIN32 /DMSVC /DWINVER=0x0601 /D_WIN32_WINNT=0x0601 /DNOMINMAX /D_WIN64 /DPTRCALL_ENABLED /DTOOLS_ENABLED /DGDSCRIPT_ENABLED /DMINIZIP_ENABLED /Ieditor /I. /Iplatform\windows /Ithirdparty\zlib /Ithirdparty\zstd /Ithirdparty\glad /Ithirdparty\libpng /Ithirdparty\freetype\include /Ithirdparty\nanosvg
os_windows.cpp
C:\Users\joe\Documents\projects\godot\godotengine\thirdparty/glad/glad/glad.h(97): fatal error C1083: Cannot open include file: 'KHR/khrplatform.h': No such file or directory
scons: *** [platform\windows\os_windows.windows.tools.64.obj] Error 2
scons: building terminated because of errors.
```

To repro this issue, I enabled case sensitivity on thirdparty/glad/ and thirdparty/glad/KHR/

For anyone trying to play around with this, a quick cheat sheet:
* Query case sensitivity with: `fsutil file queryCaseSensitiveInfo dirName`
* Set case sensitivity with: `fsutil file setCaseSensitiveInfo dirName [enable|disable]`

**Comment by Calinou** [comment] 2019-11-15 20:57
@joealam Does this occur if you build Godot using MinGW instead of MSVC?

**Comment by akien-mga** [comment] 2020-07-26 20:20
No new answer, closing. Please comment if you can still reproduce the issue.

**Closed by akien-mga** 2020-07-26 20:20 UTC
Labels: bug, platform:windows, topic:buildsystem

**Comment by Calinou** [comment] 2020-07-31 21:13
For the record, I can't reproduce this on commit https://github.com/godotengine/godot/commit/5af533147482922a08fccc6b514225a6f0e9c2bc. I tested this on a case-insensitive Windows 10 2004 installation with MSVC 2019 (16.6.4).

When testing this issue, I made sure to enable case-sensitivity on all of Godot's subdirectories by running `for /r /d %f in (.) do (fsutil file setCaseSensitiveInfo %f disable)` in `cmd.exe` in the cloned repository folder.

**Comment by BlacRyu** [comment] 2022-02-03 07:40
I'm getting the same error when attempting to build from the latest master branch if I set the `opengl3` build option to false.
```
scons: Reading SConscript files ...
Configuring for Windows: target=release_debug, bits=64
Found MSVC version 14.2, arch amd64, bits=64
Checking for C header file mntent.h... (cached) no
scons: done reading SConscript files.
scons: Building targets ...
Compiling platform\windows\display_server_windows.cpp ...
display_server_windows.cpp
C:\Users\blacr\Desktop\godot source\thirdparty/glad/glad/glad.h(93): fatal error C1083: Cannot open include file: 'KHR/khrplatform.h': No such file or directory
scons: *** [platform\windows\display_server_windows.windows.double.opt.tools.64.obj] Error 2
scons: building terminated because of errors.
[Time elapsed: 00:00:08.306]
```

I was able to build successfully after changing `#include <KHR/khrplatform.h>` to `#include "../KHR/khrplatform.h"` in glad.h

These are the build options I used:
```platform        = "windows"
bits            = "64"
target          = "release_debug"
j               = "4"
float           = "64"
tools           = "yes"
optimize        = "speed"
vulkan          = "yes"
opengl3         = "no"
deprecated      = "no"
vsproj          = "yes"
```

**Comment by Calinou** [comment] 2022-02-03 17:11
@BlacRyu This is an unrelated issue. Please open a separate issue, but note that compiling with specific rendering backends is still largely untested so far.
