### ISSUE TITLE
Tween Slowdown After Signal

### ISSUE THREAD

**Issue by kuroodo** [godotengine/godot#35128] opened 2020-01-14 18:13 UTC
**Godot version:**
3.2 Beta 6

**OS/device including version:**
Windows 10 pro 64 bit
GTX 1080 Driver version 441.20
i7-6700k
16GB Ram

**Issue description:**
Tween animation in 3.2 Beta 6 is slow compared to 3.2 Beta 5.
After a tween animation ends, then starting the same animation in the tween_all_completed() or tween_completed(object, key) signal, the animation does not begin until after a few frames. This behavior did not occur in Beta 5. As a result, tween animations look rough or bumpy, compared to Beta 5 which looked smooth.

### 3.2 Beta 6
- Animation: https://gyazo.com/77d37654dd1278906e5e23c1b37b3801
- Slowed Down: https://gyazo.com/e71641e439e4d1f80dcdb704609e3efc

### 3.2 Beta 5
- Animation: https://gyazo.com/7d1f993626ae94d28fdf8c0e0f9ce241
- Slowed Down: https://gyazo.com/38f0cc615b6d49b95c2e5523ddf0d316

You will notice that the Beta 5 tween is much smoother than Beta 6. The difference is much more noticeable if you run the program in the attached project.

**Steps to reproduce:**
Refer to attached project for reproduction. Look at Test.tscn and Test.gd to see the script for the tween.
_Run the game, and click the screen with the left mouse button to start the tween._

**Minimal reproduction project:**
[TweenBugReplication.zip](https://github.com/godotengine/godot/files/4060625/TweenBugReplication.zip)

**Comment by akien-mga** [comment] 2020-01-14 19:54
This may be related to #35038, can you check if disabling `display/window/vsync/vsync_via_compositor` solves it?

**Comment by kuroodo** [comment] 2020-01-14 22:49
I can confirm that disabling vsync_via_compositor solves the issue

**Comment by akien-mga** [comment] 2020-01-14 22:50
Thanks, it's a duplicate of #35038. Most likely the slowdown you noticed is due to your framerate being halved.

**Closed by akien-mga** 2020-01-14 22:50 UTC
Labels: bug, regression, topic:core
