### ISSUE TITLE
Discontinuous texture in ParallaxBackground if the texture has to be drawn more than twice on screen

### ISSUE THREAD

**Issue by alexzheng** [godotengine/godot#27160] opened 2019-03-17 12:37 UTC
**Godot version:**
3.1

**OS/device including version:**

**Issue description:**

if the width of the texture is smaller than the width of the device, there is a short gap between the textures.

**Steps to reproduce:**

**Minimal reproduction project:**

[Uploading ParallaxBug.zip…]()

**Comment by akien-mga** [comment] 2019-04-01 11:31
Your project upload did not complete, so it's a bit hard to do anything for this issue without more details.

**Comment by bojidar-bg** [comment] 2019-04-17 18:25
@alexzheng Pretty bump, check above comment.

**Comment by alexzheng** [comment] 2019-04-18 02:06
[ParallaxBug.zip](https://github.com/godotengine/godot/files/3092184/ParallaxBug.zip)

**Comment by bojidar-bg** [comment] 2019-04-18 09:11
I think this is sort-of by design, since ParallaxLayer's Mirroring shows things at most twice. See #15359.

**Comment by Xrayez** [comment] 2019-08-11 18:02
I kinda work around this by setting `Sprite`/`TextureRect` `region_rect`/`rect_size` for them to repeat the texture and adjust mirroring size so that it matches viewport size or so (connecting `size_changed` in `Viewport`), and also multiply that by 2 to be sure. 😄 

This "bug" is also very prominent when you zoom out big time with camera.

@bojidar-bg:

>Mirroring shows things at most twice.

Should it repeat more than twice then? Something like `mirror_count`, which essentially translate to `repeat_count` which is a better name for this as you mentioned in https://github.com/godotengine/godot/issues/23243#issuecomment-432284154.

**Comment by Xrayez** [comment] 2019-08-11 18:15
Also here's my hacky workaround snippet:
```gdscript
func _update_size():

	for canvas_idx in get_child_count():

		var canvas_layer = get_child(canvas_idx)
		if not canvas_layer is CanvasLayer:
			continue

		for idx in canvas_layer.get_child_count():

			var layer_node = canvas_layer.get_child(idx)
			if not layer_node is ParallaxLayer:
				continue

			var canvas = layer_node.get_node('canvas')

			var tex_size = canvas.texture.get_size()
			var vp_size = viewport.size
			var vp_scale = viewport.canvas_transform.get_scale()

			var q = vp_size / tex_size
			q = q / vp_scale
			q = q.ceil()

			var x = q.x * tex_size.x
			var y = q.y * tex_size.y

			var new_size = Vector2(x, y)
			new_size *= 2 # just to be sure it covers all

			# Update mirroring
			var mirroring = layer_node.motion_mirroring

			if mirroring.x > 0.0:
				mirroring.x = new_size.x

			if mirroring.y > 0.0:
				mirroring.y = new_size.y

			layer_node.motion_mirroring = mirroring

			# Update canvas size
			var canvas_size
			if canvas is TextureRect:
				canvas_size = canvas.rect_size
			elif canvas is Sprite:
				canvas_size = canvas.region_rect.size

			if mirroring.x > 0.0:
				canvas_size.x = new_size.x

			if mirroring.y > 0.0:
				canvas_size.y = new_size.y

			if canvas is TextureRect:
				canvas.rect_size = canvas_size
			elif canvas is Sprite:
				canvas.region_rect.size = canvas_size

```

**Comment by theBSH** [comment] 2023-12-21 07:58
workaround might work but having mirror_count is something that I think should get added, don't think it will be hard to implement it.

**Comment by KoBeWi** [comment] 2024-11-16 22:09
Fixed with Parallax2D.

**Closed by KoBeWi** 2024-11-16 22:09 UTC
Labels: bug, topic:rendering, confirmed, topic:2d
