### ISSUE TITLE
Framerate drops on laptop when running scene and rotating camera with mouse movement

### ISSUE THREAD

**Issue by Kryper** [godotengine/godot#20749] opened 2018-08-05 22:28 UTC
**Godot version:**
3.0.6

**OS/device including version:**
OS: Windows 10
Device: Acer 300 Predator Helios
Processor: i5-7300HQ 2.5Ghz
Ram: 8GB DDR4
Graphics card: Intel(R) HD Graphics 630/Nvidia GTX1050Ti
Mouse: Logitech. Model number: M-U0026
USB ports: Two 2.0 and one 3.0

**Issue description:**
I got this laptop as my old PC died. I made a simple 3D scene with static mesh as floor, capsule and camera. I downloaded script from assetlib called "Camera Control Script".

If I move mouse in editor everything works as expected. If I will run the scene and move camera with mouse framerate drops down massively and comes back for just a moment to drop down again as mouse applies movement to camera. If I will use trackpad to move camera when scene is running everything is ok, stable 1200 FPS. If mouse do not move framerate is stable between 1200-1400 FPS.

I did set Nvidia card as default card.
I tested it with Blender no issues here.
I tested it with other games, no issues here.
I plugged mouse to all available ports, it did not solve problem.
It also happens when project is exported and run outside of editor.
I tested it with trackpad disabled from Device Manager as suspected device clash. Did not solve the issue.
Script have option to move camera with keyboard up, left, right, down buttons. Moving camera this way do not affect framerate in any way.
Script in question worked perfectly fine when used on my previous setup with the same mouse.

**Steps to reproduce:**
1. Laptop with trackpad and mouse.
2. Create new project.
3. Download "Camera Control Script" from Assetlib.
4. Add 3D Camera node to 3D scene.
4. Attach script to camera.
5. Run the game
6. Use mouse to move camera around.
7. Use trackpad to move camera around.

**Minimal reproduction project:**
[MouseBug.zip](https://github.com/godotengine/godot/files/2260717/MouseBug.zip)

**Comment by Zylann** [comment] 2018-08-06 12:34
I'm not getting the bug with the reproduction project.
Windows 10 64 bits desktop computer
OpenGL ES 3.0 Renderer: GeForce GTX 750 Ti/PCIe/SSE2

**Comment by slapin** [comment] 2018-08-06 18:25
I have this with my project on Linux, GTX660 on stationary PC with higher resolutions (>1024x600)

**Comment by slapin** [comment] 2018-08-06 18:27
This is not reproducible in editor though, only in running game.
Framerate drops to 10 FPS from 40-60

**Comment by Kryper** [comment] 2018-08-06 20:30
Ok I updated steps to reproduce with additional step to run the game so there is no confusion.

**Comment by KoBeWi** [comment] 2019-04-18 22:12
On GTX 1060 there's stable 1300+ FPS when running on Full HD.

**Comment by KoBeWi** [comment] 2020-07-17 20:46
Can anyone still reproduce this bug in [Godot 3.2.2](https://godotengine.org/article/maintenance-release-godot-3-2-2) or any later release?

**Comment by Calinou** [comment] 2020-07-17 20:54
@KoBeWi This was probably fixed in Godot 3.1 since raw input is now used for mouse movement when the mouse is captured.

**Comment by KoBeWi** [comment] 2020-09-28 16:33
Closing due to lack of update. Please comment if you can still reproduce this issue in the latest stable version of Godot.

**Closed by KoBeWi** 2020-09-28 16:33 UTC
Labels: bug, topic:core
