### ISSUE TITLE
Inconsistency in authoritative networked client control

### ISSUE THREAD

**Issue by tree786** [godotengine/godot#29933] opened 2019-06-20 15:22 UTC
**Godot version:**
v3.1.1 (godotengine.org)

**Issue description:**
Tricky to explain...
I have a networked game where clients can connect to a server (which is a godot engine instance). When the game is started, instances of client entities which are spawned in for each player using a for loop (similar to the 'multiplayer_bomber'. See: https://github.com/godotengine/godot-demo-projects/tree/master/networking/multiplayer_bomber). All works well when sending non-authoritative data, such as position vectors or basis matrices, but incorrect behaviour occurs when key presses (i.e. authoritative) are sent.  This time (using an authoritative key press model), the wrong clients are being controlled, even though everything was perfectly fine when directly sending non-authoritative data. FYI: I am calling `set_network_master` for each instance using the correct ID (of that client). Also, I don't think this is a latency problem, since that should not be the cause of controlling the wrong clients. Also, I am using an authoritative server, whereby clients are controlled remotely from key presses sent using the `rset_unreliable` method. Hopefully this makes some sense (see the attached project files below)

**Steps to reproduce:**
1. Set up networking as done in https://github.com/godotengine/godot-demo-projects/tree/master/networking/multiplayer_bomber

2. Create instances of each client entity locally using a for loop, and set them their correct unique ID using `set_network_master`

3. Use `rset_unreliable` to send key presses to each client and control their movement using these key presses (using `apply_impulse_central` or `move_and_slide` or `translate`, etc)

4. Open two instance of godot engine (first being a server and second being the client).

5. Observe how you are controlling the wrong characters on the other clients

**Minimal reproduction project:**
[networking_authorative_server_issue.zip](https://github.com/godotengine/godot/files/3311038/networking_authorative_server_issue.zip)

Note to use this file :  open 2 instances of godot engine; in the first instance press `create a server` button and in the second instance press `create a server`.  Control the character on instance one (using WSAD keys) and observe the incorrect control on instance two.

**Comment by tree786** [comment] 2019-06-21 23:27
I have made some more tests and it turns out that even sprites are affected. It seems that controlling instantiated clients remotely (using `rset_unreliable`) using key presses (i.e. authoritatively) causes incorrect client control, so you are controlling the wrong clients (and this leads to each player seeing different things)

**Comment by Faless** [comment] 2019-06-22 09:53
I see no issue here, add a label to the players, set it to the same string you use as network master, and you'll see that each player controls the right one.

The problem you are facing is that physics is non-deterministic, additionally, you spawn the players in the same position but in different order between client and server, resulting in them having different positions when they free themselves after the first step. At this point the elements are out of sync, and will keep being out-of-sync forever.

As a suggestion, I would disable physics completely in the client, have only the client sending keyboard presses, and have the server send positions to client instead.

Closing, as this works as intended.

**Closed by Faless** 2019-06-22 09:53 UTC
Labels: bug, topic:network
