### ISSUE TITLE
CPUParticles2D with global coordinates changing origin during parent transform

### ISSUE THREAD

**Issue by oeleo1** [godotengine/godot#32091] opened 2019-09-11 17:43 UTC
**Godot version:**
Godot v3.1.1.stable.official

**OS/device including version:**
All devices, tested on Windows 10, iPhone, iPad, Android

**Issue description:**
A CPUParticles2D node with global coordinates (local coords unchecked) change the particles coordinates when the parent node's scale/position changes.

The same settings with a GPU Particles2D node is fine - this is a bug with CPUParticles2D.

**Steps to reproduce:**
Press space (ui_select) to resize parent node.

**Minimal reproduction project:**
[CPUParticles2DResizeParentBug.zip](https://github.com/godotengine/godot/files/3602057/CPUParticles2DResizeParentBug.zip)

![CPUParticles2DResizeParentBug](https://user-images.githubusercontent.com/40200623/64721153-27f07e00-d4cc-11e9-987e-b4541720e61a.gif)

**Comment by clayjohn** [comment] 2019-09-11 17:59
Duplicate of https://github.com/godotengine/godot/issues/27743, fixed in https://github.com/godotengine/godot/pull/29700

The bugfix will be in the upcoming 3.2 release. :)

**Closed by clayjohn** 2019-09-11 17:59 UTC
