### ISSUE TITLE
Window cannot be closed after user clicking on its content

### ISSUE THREAD

**Issue by Chaosus** [godotengine/godot#57437] opened 2022-01-30 09:48 UTC
### Godot version

78e3e65e7c38d18128524e0822a106ac76e38800

### System information

Windows 10

### Issue description

![window_bug](https://user-images.githubusercontent.com/3036176/151694721-c403f48b-fca7-4ea6-b1fc-f9b9ca43f231.gif)

I think it may be reported but cannot find where.

### Steps to reproduce

- Open any sub-window in the editor (Single Window Mode should be disabled)
- Click on the content
- Note that it cannot be closed after that

### Minimal reproduction project

No need - too easy to reproduce

**Comment by bruvzg** [comment] 2022-01-31 11:03
I can't reproduce it, child windows seems to be closing fine (Windows 11, 21H2).

It might depend on window open animation speed. Probably `WINDOW_EVENT_CLOSE_REQUEST` sent from `WM_CLOSE` is not processed correctly, but I do not have any idea why this can happen.

**Comment by Calinou** [comment] 2022-01-31 12:24
> It might depend on window open animation speed. Probably WINDOW_EVENT_CLOSE_REQUEST sent from WM_CLOSE is not processed correctly, but I do not have any idea why this can happen.

If anyone wants to test, animations can be disabled in Windows' accessibility settings.

**Comment by Chaosus** [comment] 2022-02-26 05:41
Seems like it was fixed by https://github.com/godotengine/godot/pull/58490 thanks to @bruvzg!

**Comment by Chaosus** [comment] 2022-02-26 09:34
After https://github.com/godotengine/godot/pull/58490 it still happening but only after double-clicking on control inside window

**Comment by akien-mga** [comment] 2023-02-22 10:47
I'm pretty sure this was fixed a while ago.

**Closed by akien-mga** 2023-02-22 10:47 UTC
Labels: bug, platform:windows, topic:porting
