### ISSUE TITLE
Deleting a file leaves reference in csproj

### ISSUE THREAD

**Issue by trajano** [godotengine/godot#36928] opened 2020-03-09 01:02 UTC
**Godot version:**
3.2.stable.mono.official

**OS/device including version:**
Windows 10

**Issue description:**

I created a small Godot Project then I added a script then removed the script because I wanted it placed in a different folder.  The reference to the old script is still in the .csproj file so when I do a build it gives an error.

Not sure if it may be similar to #16327

**Steps to reproduce:**

Create a node, create a script delete the node.
Create another node.  create a script, just build (you'd get an error)

**Minimal reproduction project:**

**Comment by KoBeWi** [comment] 2020-03-09 03:12
Duplicate of #32157

**Closed by KoBeWi** 2020-03-09 03:12 UTC
