### ISSUE TITLE
GL ERROR: OpenGL Type: Undefined behavior every time Godot starts

### ISSUE THREAD

**Issue by germanbv** [godotengine/godot#85800] opened 2023-12-05 19:36 UTC
### Tested versions

4.2.stable_mono

### System information

Windows 10, NVidiaRTX 2070

### Issue description

100% of the time I open a project on Compatibility Mode using verbose, I get the following error:

```
ERROR: GL ERROR: Source: OpenGL Type: Undefined behavior        ID: 131222      Severity: Medium        Message: Program undefined behavior warning: The current GL state uses a sampler (0) that has depth comparisons enabled, with a texture object (1020) with a depth format, by a shader that samples it with a non-shadow sampler. Using this state to sample would result in undefined behavior
   at: _gl_debug_print (drivers/gles3/rasterizer_gles3.cpp:176)
```
I've read [this ](https://github.com/godotengine/godot/issues/84558)issue that has the same error, but I don't think it has to do with directional light, since it always happens, even if I create empty projects without any light.

### Steps to reproduce

Open Godot using --verbose
Create or open any project using compatibility mode

### Minimal reproduction project (MRP)

N/A

**Comment by clayjohn** [comment] 2023-12-05 19:43
I think this is most likely a duplicate of https://github.com/godotengine/godot/issues/84558

There is a default DirectionalLight3D in the editor and it is enabled by default. 
![image](https://github.com/godotengine/godot/assets/16521339/8b4b9032-e794-415f-b069-6e7656207317)

**Comment by germanbv** [comment] 2023-12-05 19:53
> I think this is most likely a duplicate of #84558
> 
> There is a default DirectionalLight3D in the editor and it is enabled by default. ![image](https://private-user-images.githubusercontent.com/16521339/288182341-8b4b9032-e794-415f-b069-6e7656207317.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE4MDYwODMsIm5iZiI6MTcwMTgwNTc4MywicGF0aCI6Ii8xNjUyMTMzOS8yODgxODIzNDEtOGI0YjkwMzItZTc5NC00MTVmLWIwNjktNmU3NjU2MjA3MzE3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA1VDE5NDk0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThhMzlhYWM2MTIwNDJlMDljZDhhM2VmMDkzMmM0YjdmZDJkNTc1NGMzYTRjYjRlZWRhMzE3YWY2MDNiYjczMTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BnhU5CoPuUcj17tFPTEg0_dXKFefEa92T6h3eBQs5qE)

If I disable that, the issue keeps triggering...

**Comment by Calinou** [comment] 2023-12-11 11:25
Thanks for the report! Consolidating in https://github.com/godotengine/godot/issues/84558, as this is due to the same cause (the texture ID is even the same).

**Closed by Calinou** 2023-12-11 11:25 UTC
Labels: bug, topic:rendering
