### ISSUE TITLE
C# Exported List<T> always return empty List<T> instead of the values set in the inspector

### ISSUE THREAD

**Issue by ToadsworthLP** [godotengine/godot#35601] opened 2020-01-26 21:15 UTC
**Godot version:**
3.2 RC3 64-bit Mono
**OS/device including version:**
Windows 10 64-bit 1903
**Issue description:**
When using [Export] on a generic List in C#, the property is displayed in the inspector and saved to the scene file (this definitely works since the value even survives an editor restart). Whenever the game is run, the value is reset to an empty list in-game. The value displayed in the editor, however, remains correct.
**Steps to reproduce:**
1. Create a new scene and attach a C# script to a node
2. In the C# script, [Export] a List<T> of any type T, I tested it with int, string and PackedScene with identical results
3. Try to use the list - it will be empty, no matter what was added to it in the inspector
**Minimal reproduction project:**
[BugPlayground.zip](https://github.com/godotengine/godot/files/4114357/BugPlayground.zip)
Example: No matter how the list is set up in the inspector, its Count always is 0. For comparison, an array of the same type works as intended.

**Comment by akien-mga** [comment] 2020-01-26 21:16
Duplicate of #20387.

**Closed by akien-mga** 2020-01-26 21:16 UTC

**Comment by nathanwfranke** [comment] 2020-01-27 22:18
Is this a duplicate? #20387 says there is nothing in the inspector but with this issue (#35601) I can see values in the inspector
![image](https://user-images.githubusercontent.com/14253836/73218366-7753e580-411f-11ea-9506-715fac6b977e.png)
![image](https://user-images.githubusercontent.com/14253836/73218389-7e7af380-411f-11ea-92f8-bcd243ad14cf.png)

As for this issue, I am getting very bizarre behaviour.

```
[Export]
public List<int> list {get; set;}

public override void _Ready()
{
	GD.Print("Length = " + list.Count);
	GD.Print("Values = " + string.Join(", ", list));
}
```

```
Length = 0
Values = 4, 2, 0
```

**Comment by Spartan322** [comment] 2020-02-09 05:21
Isn't the "original" issue technically a different problem? That one was was relatively old and I believe was from a time when List didn't properly export at all, unless I'm incorrect. This one is about the failure to update an ICollection's/IList's internal state. (specifically List's) which I believe is caused by Godot's Marshalling treating anything that derives from an IEnumerable which isn't an IDictionary as an IEnumerable, so it skips addressing the internal state. I'm also fairly certain its attempting to force a push back on an IEnumerable, which you aren't even suppose to natively treat as a modulative/additive enumeration. (say you create a readonly enumerable it will completely break)
