### ISSUE TITLE
My game crashes only in the HTML5 release version

### ISSUE THREAD

**Issue by MatiasVME** [godotengine/godot#40704] opened 2020-07-25 19:36 UTC
**Godot version:**

3.2.3.rc1.official

**OS/device including version:**

GLES2 / Linux (KDE Neon)

**Issue description:**

Hello, everybody! (Sorry for my english)

I wanted to report a bug related to a crash that happens only in the release version of HTML5 and it seems that other export releases also happen (so we were watching with my group).

I don't know the bugs, I didn't know how to see the bugs in a release version of html5, sorry about that.

In the debug version I didn't make the bug happen.

**Steps to reproduce:**

Play the release version (Sometimes crashing)

Here a video:

https://youtu.be/th9VveK1gUU

**Minimal reproduction project:**

[Crazy Crabs - HTML5 - v1.1.2 (release).zip](https://github.com/godotengine/godot/files/4976261/Crazy.Crabs.-.HTML5.-.v1.1.2.release.zip)

[Crazy Crabs - HTML5 - v1.1.2 (debug).zip](https://github.com/godotengine/godot/files/4976264/Crazy.Crabs.-.HTML5.-.v1.1.2.debug.zip)

[Code.zip](https://github.com/godotengine/godot/files/4976268/Code.zip)

**Comment by Calinou** [comment] 2020-07-25 20:58
@MatiasVME Does the project crash when exported to Linux in release mode?

**Comment by Calinou** [comment] 2020-07-25 21:00
Duplicate of https://github.com/godotengine/godot/issues/28922. Check your code for possibly dangling Variants, as these are only fixed in debug builds as of 3.2.2. (Godot 4.0 has been refactored to include a dangling Variant fix that also works in projects exported in release mode.)

**Closed by Calinou** 2020-07-25 21:00 UTC
Labels: bug, crash, platform:html5, topic:core
