### ISSUE TITLE
rotation editor property float inaccuracy 

### ISSUE THREAD

**Issue by a5hdev** [godotengine/godot#74313] opened 2023-03-03 18:04 UTC
### Godot version

4.0 

### System information

Windows 10

### Issue description

Changing 2D node (sprite2D in this case) rotation through rotation property is inaccurate. As an example, I set node it to `-15` in editor, but printing rotation_degrees in script outputs `-14.9999780654907`

### Steps to reproduce

N/A

### Minimal reproduction project

N/A

**Comment by Mickeon** [comment] 2023-03-03 20:52
Hm. It feels like a float inaccuracy caused by the fact that the value used by the rotations is in `real_t`. `real_t` is either 32 or 64 bits, depending on the precision the engine was compiled on.

In 4.0, `rotation` is the property being exposed, but converted to degrees when displayed in the editor. When set, it goes back through the conversion, in radians. Then, when fetching `rotation_degrees `instead, it converts that value back to degrees, which barely makes the value inaccurate.
Doesn't seem like this happens in 3.x, because the `rotation_degrees` property exposed to the editor is exactly that.

I'm not sure on the way to go about it. This rotation... degrees, not degrees mess is... certainly something.

**Comment by KoBeWi** [comment] 2023-03-05 21:04
This issue did already exist in 3.x:
https://github.com/godotengine/godot/issues/20616

It's a typical precision issue, which is expected.

**Comment by Mickeon** [comment] 2023-03-05 22:37
The problem is exacerbated by the displayed `rotation` property. Most users are not going to assume this kind of behavior as reasonable. If I print what should be 15 degrees, it *should* be 15 degrees back.

**Comment by KoBeWi** [comment] 2023-03-06 00:28
Previously it was called `rotation_degrees` and it had the same issue (just as I linked above) so I don't get your point.
The previous closed as WONTFIX.

Do you have any solution in mind?

**Closed** 2023-03-13 10:12 UTC
