### ISSUE TITLE
Meshes don't render if there is more than one skeleton

### ISSUE THREAD

**Issue by bkeys** [godotengine/godot#15715] opened 2018-01-14 19:17 UTC
**Godot version:**
3 beta, as well as the current master branch

**OS/device including version:**
Fedora 27

**Issue description:**
If you create a rigged scene with more than one armature, then in Godot it will be imported as multiple skeleton nodes, the issue is that only the last skeleton node get's rendered.
![the issue](http://storage2.static.itmages.com/i/18/0114/h_1515894357_7503598_e37390565d.png)
In this scene only Skeleton5 is being rendered

**Steps to reproduce:**
- Set up makehuman
- Make sure that the generated human comes with bones, I used the "Game engine" setting
- Export to glTF and import the scene into Godot

**Minimal reproduction project:**
https://my.mixtape.moe/lvrhvk.zip

**Comment by reduz** [comment] 2018-01-14 20:04
makehuman exporter is fucked up, it needs to be fixed

**Comment by bkeys** [comment] 2018-01-14 20:07
Well I don't think makehuman is the issue here becuase it imports into Blender without any issues, the animation plays and the model is properly rigged

**Comment by reduz** [comment] 2018-01-14 20:11
Maybe blender does some magic, last time I got a gltf2 from makehuman it
was really weird. Will check this during the week, though.

**Comment by bkeys** [comment] 2018-01-14 20:17
Well from makehuman I exported to .dae, which was imported by Blender, then I exported gltf out of blender.

**Comment by akien-mga** [comment] 2018-01-18 09:51
Not critical for the upcoming 3.0 release, so moving to the next milestone. A fix can still be cherry-picked for 3.0.x maintenance releases once available in the master branch.

**Comment by hungrymonkey** [comment] 2018-02-14 18:23
@reduz i here to say that the

makehuman -> mhx2 -> blender -> gltf2.0 is still kinda weird.

![screenshot_20180214_101913](https://user-images.githubusercontent.com/771339/36220782-bada809c-1170-11e8-9d8b-cb952c04f606.png)

https://bitbucket.org/Diffeomorphic/mhx2-makehuman-exchange/issues/62/separated-eye-and-body-bone-nodes-mk-mkhx

waiting for the author to replay for mhx2.

In this image, I am using the current master branch of the official khronos blender exporter. I am still using the previous mhx2 blender importer since it seems like nothing changed

**Comment by fire** [comment] 2018-08-07 06:39
Using https://www.dropbox.com/s/srh9o8ztwbzsrk5/mhx2_stable_027.zip and https://bitbucket.org/Diffeomorphic/mhx2-makehuman-exchange/issues/attachments/62/Diffeomorphic/mhx2-makehuman-exchange/1518632867.09/62/deafult_human_notoes.mhx2 in blender exportered to glb. Seems to work.


![godot windows opt tools 64_2018-08-06_23-38-29](https://user-images.githubusercontent.com/32321/43758764-fd0e9f90-99d1-11e8-8f37-e3d36fc2e369.png)

**Comment by fire** [comment] 2018-08-07 07:02
The mesh and the skeleton must be a different name to import successfully.

I tried going from fbx -> gltf and it seemed to work.


![godot windows opt tools 64_2018-08-07_00-01-36](https://user-images.githubusercontent.com/32321/43759761-18bfc4dc-99d5-11e8-9b70-0c829ea4b4a0.png)

**Comment by akien-mga** [comment] 2018-08-15 08:39
Assuming fixed as shown by @fire, as there were various glTF fixes in the master branch. Please open a new issue if you can still reproduce import issues with 3.1 alpha 1.

**Closed by akien-mga** 2018-08-15 08:39 UTC
Labels: bug, topic:import
