### ISSUE TITLE
Vulkan: Enabling Volumetric fog gives pixels on screen and console spam

### ISSUE THREAD

**Issue by Akira1San** [godotengine/godot#48736] opened 2021-05-15 15:58 UTC
**Godot version:**
Godot night build

**OS/device including version:**
Win 10 64, AMD RX 480 

**Issue description:**
When selecting the Volumetric fog pixels show on screen and the console spam.
image: 
https://drive.google.com/file/d/1UM8ZSN44-80xszp_4PC3dkmsupgoAMrU/view?usp=sharing
![CONSOLE_SPAM](https://user-images.githubusercontent.com/8281454/125361971-15397f80-e3a9-11eb-847a-f006a221f89f.jpg)

https://drive.google.com/file/d/1CD49YQbyYsSLJm2CXgUvwL85YTFpcn0W/view?usp=sharing
![VA_BUG](https://user-images.githubusercontent.com/8281454/125361985-1bc7f700-e3a9-11eb-8b89-d21a0888309c.jpg)

**Minimal reproduction project:**
https://drive.google.com/file/d/19tB0bPnnrq2gH2X_fkMjFi075padewWM/view?usp=sharing
[VF.zip](https://github.com/godotengine/godot/files/6804646/VF.zip)

**Comment by Akira1San** [comment] 2021-07-12 16:58
With the version v4.0.dev.calinou [d1f25bb5f] now theres no pixels on the screen, it works, but the console spam - condition !sky is true. And thats using the environment - Clear color.

**Comment by Calinou** [comment] 2021-07-12 21:49
>  it works, but the console spam - condition !sky is true. And thats using the environment - Clear color.

Volumetric fog currently requires a sky to work.

**Comment by Akira1San** [comment] 2021-07-13 13:11
Great, then the issue can be closed?

**Comment by Calinou** [comment] 2021-07-13 13:14
> Great, then the issue can be closed?

We should still fix the error spam, and possibly make fog work in this "fallback clear color sky" situation.

**Comment by clayjohn** [comment] 2021-07-13 16:21
I agree with Calinou. We should make fog work without requiring a sky

**Comment by clayjohn** [comment] 2021-10-07 04:52
Closing as the remaining bug here is a duplicate of https://github.com/godotengine/godot/issues/49866

**Closed by clayjohn** 2021-10-07 04:52 UTC
Labels: bug, topic:rendering, topic:3d
