### ISSUE TITLE
Animation bar + tilemap bar bug

### ISSUE THREAD

**Issue by Atssen** [godotengine/godot#51236] opened 2021-08-04 12:54 UTC
### Godot version

3.3.2

### System information

Windows 10, gles3, intel core 2 duo cpu 2.13ghz, 4gb ram, x64

### Issue description

First i click to animation player node then tilemap node. And this bug happened. Godot slided to right. So i cant use things like transform, modulate etc. in editor now.
![Yeni Bit Eşlem Resmi.png](https://user-images.githubusercontent.com/79864885/128188157-3cf54266-f537-445d-8e16-397d3bee76a9.png)

### Steps to reproduce

Pls fix the "scaling gray things" or something else i really dont know how godot works behind the scenes i just want to make my game.

### Minimal reproduction project

For some reason i cant send files in android so i drop a link to here

https://drive.google.com/file/d/1avFdyFH1PJkBs0UpQu3jWRZAInB_72rb/view?usp=drivesdk

**Comment by kleonc** [comment] 2021-08-04 13:24
Happens because with `AnimationPlayer`'s and `TileMap`'s items active in the toolbar the total min width for the editor controls exceeds screen width. In action on 1280x1024 monitor:
![Godot_v3 3 2-stable_win64_jWEkScJ7eI](https://user-images.githubusercontent.com/9283098/128187788-b3327037-6eb7-4c02-b77f-0cb306316417.png)
![KGuWavlPqR](https://user-images.githubusercontent.com/9283098/128187801-a457732e-9d57-4f6f-ab0c-98cb9026859a.png)

As a workaround in `Editor Settings` you can change `Display Scale` to some smaller value:
![Godot_v3 3 2-stable_win64_v0JTHQV95f](https://user-images.githubusercontent.com/9283098/128188219-24457219-dff5-4c0c-b74f-65655a3696e1.png)
![ZS7ENr9O6b](https://user-images.githubusercontent.com/9283098/128188279-61a40290-2112-46fd-9a08-6f0a765438a3.png)

**Comment by Atssen** [comment] 2021-08-04 13:27
Wow thanks for quick answer this solved my problem

**Comment by Atssen** [comment] 2021-08-04 13:28
Also thanks pybouch for tags
(i dont know how can i use tags lol)

**Comment by Atssen** [comment] 2021-08-04 13:29
So its time to close this repo

**Comment by pycbouh** [comment] 2021-08-04 13:34
Let's not close it just yet, we can look into what makes the animation editor too wide. We generally should support 800 pixels wide screens with normal scale.

**Comment by Atssen** [comment] 2021-08-04 13:36
Hmm yes you are right

**Comment by Atssen** [comment] 2021-08-04 13:37
Also 0.9 display scale ia really annoying

**Comment by Calinou** [comment] 2021-08-04 15:23
Duplicate of #31133.

> Also 0.9 display scale ia really annoying

Try decreasing the main font size to 12 instead.

**Closed by Calinou** 2021-08-04 15:23 UTC
Labels: enhancement, topic:animation, topic:editor, usability

**Comment by Atssen** [comment] 2021-08-07 11:01
Its still same

**Comment by Atssen** [comment] 2021-08-07 11:02
So its still an issue and not solved

**Comment by Atssen** [comment] 2021-08-07 11:06
Also why i cant reopen the issue? Lol

**Comment by Atssen** [comment] 2021-08-07 11:10
https://photos.app.goo.gl/CpFs6z5H9D1gRZmB9

**Comment by Atssen** [comment] 2021-08-07 11:12
![Screenshot_20210807_141146.jpg](https://user-images.githubusercontent.com/79864885/128598278-a858e4bc-d5d7-4470-b28f-664771505195.jpg)

**Comment by akien-mga** [comment] 2021-08-07 11:14
This is a duplicate of another issue, which is open. We don't keep duplicates open as one issue is enough to keep track of a given problem.

**Comment by Atssen** [comment] 2021-08-07 11:24
Which one is it?

**Comment by Atssen** [comment] 2021-08-07 11:31
Can you leave a link here?

**Comment by Calinou** [comment] 2021-08-07 11:45
> Can you leave it's link here?

It's https://github.com/godotengine/godot/issues/31133.

Also, please use the Edit button (hidden behind the **…** button next to your posts) instead of multi-posting.
