### ISSUE TITLE
`NavigationServer3D::sync` could be optimized 

### ISSUE THREAD

**Issue by 0x0ACB** [godotengine/godot#96483] opened 2024-09-02 16:03 UTC
### Tested versions

4.3-stable

### System information

Windows 11

### Issue description

I am currently evaluating switching to Godot navigation but after some testing I have some great concerns about the performance.

I have a map with with a size of roughly `(1720, 500, 1600)` and 2650 meshes.

First of all, due to some strange constraints I have to tile this map into multiple chunks. I am currently using chunks with an edge size of 256 in the x,z dimension. Building the 42 tiles is quite quick. **It takes roughly 2 seconds to build all of them**. The issue however is actually adding them to the `NavigationServer3D`. I am creating a new `NavigationRegion3D` for each tile and adding the mesh to it. **This takes 15 minutes**. That is way too long. Especially considering this needs to be done on every map load.

Via profiling I found that 100% of the time spend during this 15 minutes is inside `NavigationServer3D::sync` or more specifically `NavMap::sync`. Looking at the code a bit, the part that is connecting compatible edges has multiple issues:
- every edge is checked against every other edge already giving us O(N²). This should really be using some form of BVH. Even just comparing the navmesh `AABB`s would help a lot here.
- The filtering for navigation region internal edges does not seem to work given that I see a lot of purple even inside individual tiles:
![image](https://github.com/user-attachments/assets/c73749ec-60c2-4aed-9a20-852dcbe3a8e5)
Note that there is only a single tile in the Y direction so there should be no connections here. Also I am getting this error here:
```
<modules\navigation\nav_map.cpp(990): NavMap::sync> Navigation map synchronization error. Attempted to merge a navigation mesh polygon edge with another already-merged edge. This is usually caused by crossing edges, overlapping polygons, or a mismatch of the NavigationMesh / NavigationPolygon baked 'cell_size' and navigation map 'cell_size'. If you're certain none of above is the case, change 'navigation/3d/merge_rasterizer_cell_scale' to 0.001
```
- The navigation mesh does not seem to store any information about which edges are external and can even be connected to. Meaning this needs to be recomputed every time. The external edges do not change. This can be easily precomputed and stored in some form of BVH.
- it's single threaded.

In its current form this system does not seem so work at all for even moderately sized 3d maps. My current implementation using native recast with tiled navigation meshes of the same edge size of 256 takes 5ms to load and connect all tiles together. I hope I am just doing something very wrong.

As a side note: The build settings should really be a resource separate from the navigation mesh so they can be easily reused for multiple builds.

### Steps to reproduce

-

### Minimal reproduction project (MRP)

```
## Utility class to generate navmeshes
@tool
extends Node
class_name NavmeshBuilder

@export var agent_height: float = 1.75
@export var agent_radius: float = 0.75
@export var agent_max_climb: float = 0.75
@export var agent_max_slope: float = 50.0
@export var cell_size: float = 0.25
@export var cell_height: float = 0.25
@export var region_min_size: float = 8.0
@export var region_merge_size: float = 20.0
@export var edge_max_length: float = 8.0
@export var border_size: float = 1.0
@export var vertices_per_polygon: float = 6.0
@export var detail_sample_distance: float = 6.0
@export var detail_sample_max_error: float = 1.0
@export var tile_size: int = 256
@export var filter_ledge_spans: bool = false
@export var filter_low_hanging_obstacles: bool = true
@export var filter_walkable_low_height_spans: bool = true

var _tiles := {}

## Generates a list of AABBs for tiles that are above the water level
func calculate_ground_tiles(aabb: AABB, water_level: float = -1.25) -> Array[AABB]:
	water_level -= cell_height
	var bbs: Array[AABB] = []
	var num_tiles_x := int(ceil(aabb.size.x / tile_size))
	var num_tiles_z := int(ceil(aabb.size.z / tile_size))

	for x in range(num_tiles_x):
		for z in range(num_tiles_z):
			var tile_origin := Vector3(aabb.position.x + x * tile_size, water_level, aabb.position.z + z * tile_size)
			var tile_extents := Vector3(tile_size, (aabb.position.y + aabb.size.y) - water_level, tile_size)
			var aabb_above_water := AABB(tile_origin, tile_extents)
			bbs.append(aabb_above_water)

	return bbs

## Parses the source geometry data from the map
func parse_source_geometry_data(map: Map, tile_aabb: AABB) -> NavigationMeshSourceGeometryData3D:
	var objs := map.object_tree.query(tile_aabb)
	var nav_data := NavigationMeshSourceGeometryData3D.new()
	for obj in objs:
		if not obj.enabled:
			continue
		if obj.type == MapObject.MAP_OBJECT_ZONE:
			for xform: Transform3D in obj.transforms:
				nav_data.add_mesh(obj.mesh, xform)
		elif obj.type == MapObject.MAP_OBJECT_TERRAIN:
			nav_data.add_mesh(obj.mesh, Transform3D.IDENTITY)
		else:
			nav_data.add_mesh(obj.mesh, obj.transform)
	return nav_data

## Builds a tile for the given map
func build_tile(map: Map, tile_aabb: AABB) -> Promise:
	var ext_bbox := tile_aabb.grow(border_size)
	var nav_data := parse_source_geometry_data(map, ext_bbox)
	var mesh: NavigationMesh = NavigationMesh.new()
	mesh.agent_height = agent_height
	mesh.agent_radius = agent_radius
	mesh.agent_max_climb = agent_max_climb
	mesh.agent_max_slope = agent_max_slope
	mesh.cell_size = cell_size
	mesh.cell_height = cell_height
	mesh.region_min_size = region_min_size
	mesh.region_merge_size = region_merge_size
	mesh.edge_max_length = edge_max_length
	mesh.edge_max_error = border_size
	mesh.vertices_per_polygon = vertices_per_polygon
	mesh.detail_sample_distance = detail_sample_distance
	mesh.detail_sample_max_error = detail_sample_max_error
	mesh.filter_baking_aabb = ext_bbox
	mesh.border_size = border_size
	mesh.filter_ledge_spans = filter_ledge_spans
	mesh.filter_low_hanging_obstacles = filter_low_hanging_obstacles
	mesh.filter_walkable_low_height_spans = filter_walkable_low_height_spans
	
	var result := Promise.new()
	NavigationServer3D.bake_from_source_geometry_data_async(mesh, nav_data, func () -> void: result.fulfill(mesh))

	return result

func swap_tile(mesh: NavigationMesh) -> void:
	print("Swapping tile at ", mesh.filter_baking_aabb.position)
	var region: NavigationRegion3D
	region = _tiles.get(mesh.filter_baking_aabb)
	if not region:
		region = NavigationRegion3D.new()
		_tiles[mesh.filter_baking_aabb] = region
		add_child(region)
		region.owner = self

	region.navigation_mesh = mesh

## Builds the navmesh for the given map
func bake(map: Map) -> void:
	var aabb := map.bounds
	var water_level := map.water_plane.transform.origin.y
	var ground_tiles := calculate_ground_tiles(aabb, water_level)
	for tile_aabb in ground_tiles:
		build_tile(map, tile_aabb).future.connect(swap_tile)
```

**Comment by smix8** [comment] 2024-09-02 18:15
While there are some things that can be undeniably optimized (and are worked on) some of tthe main issues here are settings and geometry layout.

> every edge is checked against every other edge already giving us O(N²). This should really be using some form of BVH. Even just comparing the navmesh AABBs would help a lot here.

> The filtering for navigation region internal edges does not seem to work given that I see a lot of purple even inside individual tiles

This is the edge connection margin feature and its debug.

The edge connection margin is a feature to help beginners merge sloppy created and misaligned navigation meshes. Outside of that it is not needed to merge navigation meshes and it also does not performance scale well so should always be disabled for larger navigation maps.

The edge connection margin feature can be disabled in the ProjectSettings or per navigation map or per navigation region. Disabling it will give you an immediate huge performance boost with the sync on larger navigation maps.

The issue will be if you disable it right now the pathfinding will not work in your project. Half those edges in that image are connected wrong or not connected at all due to all kinds of geometry layout and rasterization issues.

There can be many reason for this but the most common is that the baked navmesh geometry does not match with the set navigation map rasterization cell size or the edges between the baked chunks are just misaligned and do not match.

The navigation map rasterizes all the navmesh edges and if a pair of edges occupies the same cells they are merged. If a third edge tries to occupy the same cells with an already paired edge key that is a logical error and rejected.

This can happen due to e.g navmesh overlap, thin or crossing edges or just float errors. If you zoom in on those problematic bug locations is is almost always a thin edge that nearly overlaps another, or some overlap or gap between the baked edges due to float errors or other misalignment when placing the region navmeshes.

If you can fix all those alignement issues and make all navmesh edges that should merge efficiently by edge key you can support a far larger map without noticeable issues even with the current "unoptimized" sync.

**Comment by 0x0ACB** [comment] 2024-09-03 04:03
> This is the edge connection margin feature and its debug.

> The edge connection margin is a feature to help beginners merge sloppy created and misaligned navigation meshes. Outside of that it is not needed to merge navigation meshes and it also does not performance scale well so should always be disabled for larger navigation maps.

> The edge connection margin feature can be disabled in the ProjectSettings or per navigation map or per navigation region. Disabling it will give you an immediate huge performance boost with the sync on larger navigation maps.

Thanks! This helped a lot. Building and adding the tiles is now indeed much faster. This should probably be made clearer in the docs. I was under the assumption meshes would not get merged at all without this. 

If I have a moving platform, is it enough to just enable this for the platform? The main reason I want to switch to godot navigation is support for moving platforms after all.

> The issue will be if you disable it right now the pathfinding will not work in your project. Half those edges in that image are connected wrong or not connected at all due to all kinds of geometry layout and rasterization issues.

> There can be many reason for this but the most common is that the baked navmesh geometry does not match with the set navigation map rasterization cell size or the edges between the baked chunks are just misaligned and do not match.

> The navigation map rasterizes all the navmesh edges and if a pair of edges occupies the same cells they are merged. If a third edge tries to occupy the same cells with an already paired edge key that is a logical error and rejected.

> This can happen due to e.g navmesh overlap, thin or crossing edges or just float errors. If you zoom in on those problematic bug locations is is almost always a thin edge that nearly overlaps another, or some overlap or gap between the baked edges due to float errors or other misalignment when placing the region navmeshes.

> If you can fix all those alignement issues and make all navmesh edges that should merge efficiently by edge key you can support a far larger map without noticeable issues even with the current "unoptimized" sync.

This assessment is incorrect. I have been using this map as a test for navigation for many years with recast. Always with the same settings. I never had a single issue. Indeed with the edge connections turned off everything works as expected. So I guess there is some bug in the edge connection code still.

**Comment by smix8** [comment] 2024-09-03 07:09
> This assessment is incorrect. I have been using this map as a test for navigation for many years with recast.

ReCast does not runtime rasterize navigation mesh edges, it bakes directly from the voxel rastered input geometry and uses the result directly.

The problem is not that ReCast bakes incorrectly by itself. The problem is that the baked and placed navmesh result does not rasterize in the navigation map cell grid correctly for the mentioned reasons.

> If I have a moving platform, is it enough to just enable this for the platform? The main reason I want to switch to godot navigation is support for moving platforms after all.

You can enable the edge connection margin selective on regions. Just be aware that the performance inefficent loop will run for all the unmerged edges from regions that have edge connection margin enabled. If both the platform and the platform docks are simple regions that should not matter, but if the dock region is more complex it might be more efficient to use a navigation link that gets enabled when docked instead.

> Those internal purple edges only appear when I bake the mesh a second time.

The edge connection margin debug and its update requires processing of the NavigationServer connections on the physics step. This can behave sometimes quirky with how the editor updates the nodes and gizmos missing the node based update intervals.

**Comment by 0x0ACB** [comment] 2024-09-03 08:01
> The edge connection margin debug and its update requires processing of the NavigationServer connections on the physics step. This can behave sometimes quirky with how the editor updates the nodes and gizmos missing the node based update intervals.

This doesn't seem to be all there is to it. If I build the map once with edge connections enabled on all nav meshes. Consecutive builds will always take 15min even if I disabled the edge connections. I could understand it taking longer the first time due to how I update the map. But not every time until I restart the editor or fully close the scene.

**Comment by smix8** [comment] 2024-09-03 08:49
> even if I disabled the edge connections

What do you use to disable the edge connection margin? The ProjectSettings, the NavigationRegion3D property or the NavigationServer3D API functions?

I just checked and both the NavMap and NavRegion get dirty for a rebuild when their `use_edge_connections` property is set to a different bool value.

> But do both the platform and the dock need to have it enabled

Both platform and dock region and the navigation map need it enabled.

The way it works in the sync is that first all the edges get merged by direct overlap by edge key. This is usually very quick and efficient. Then all the leftover edges are added for the edge connection margin pass but only if the map and the edge owner, aka the region, has it enabled. This pass is what makes things so very slow when there are many edges left, because all the edges get compared for compatibility by distance, length and angle in a loop which is what makes it so costly and slow.

Depending on what that platform needs to do you might not even need the edge connection margin. If you manage to make thge docking edges overlap with your platform they will connect just fine without the edge connection margin.

**Comment by 0x0ACB** [comment] 2024-09-03 09:17
> What do you use to disable the edge connection margin? The ProjectSettings, the NavigationRegion3D property or the NavigationServer3D API functions?

> I just checked and both the NavMap and NavRegion get dirty for a rebuild when their use_edge_connections property is set to a different bool value so that should take effect immediately with the next map sync on the next physics step.

I am actually fully deleting the `NavigationRegion3D` right now and create a new and set `use_edge_connections`

**Comment by smix8** [comment] 2024-09-03 20:59
I am having trouble reproducing this.

If you change properties of navigation objects they are inside the sync queue of the NavigationServer which gets executed on the next physics step before the navigation map updates.

When I create a new NavigationRegion3D and set the edge connection margin disabled it immediately sets this as a command on the NavigationServer so it is part of the very next sync and already updated before the navigation map rebuilds.

If I delete a NavigationRegion3D it gets freed it sends a free command to the server which is also executed on the next sync before all the navigation map updates are done so it should no longer exist at this point.

So the only explaination that I have right now is that the delete for whatever reason misses the sync and you have one frame that has you old region with the edge connection margin still on the map causing the performance issues. Maybe you can test if it still happens if you wait 2-3 physics steps before adding the new region as by that time anything stuck in any queue should be executed.

**Comment by 0x0ACB** [comment] 2024-09-13 13:43
Waiting before adding the new meshes does indeed get rid of the issue. But deleting the mesh should get rid of the connections either way. So I would still consider this a bug.

I am also still noticing significant performance hits even with `use_edge_connections = false` in both project settings and on all `NavigationRegion3D`. I have a map that is stitched together from ~306 tiles of size 96x96. Adding all tiles to the navigation map initially takes ~1.6s. So this is as quick as needed. However, swapping just a single tile also takes 1.6seconds. Again this seems to be because everything is recomputed in sync instead of just the parts that actually need to.

Initial set up::
![image](https://github.com/user-attachments/assets/cc9b60e4-cc0d-4ab1-a3ab-1461a63c7523)

Swapping a single tile:
![image](https://github.com/user-attachments/assets/0dc2f43d-9358-4596-8674-24b4926c883a)

**Comment by smix8** [comment] 2024-11-05 22:04
Made a PR to reduce those memory allocations. https://github.com/godotengine/godot/pull/98866

The map rebuild can reuse the majority of them while keeping the memory. This should speed things up after the first sync as long as most regions stay unchanged.

There was also PR https://github.com/godotengine/godot/pull/90182 merged recently that improved the edge pairing.

Further speed improvements will likely require larger and more complex changes to how the map graph is constructed.

**Closed** 2024-12-22 10:22 UTC
Labels: enhancement, discussion, topic:navigation
