### ISSUE TITLE
Compile Error on Windows & Linux (syntax error in object.h)

### ISSUE THREAD

**Issue by patchman** [godotengine/godot#6182] opened 2016-08-17 15:56 UTC
Windows 10 Home - VS Community 2015 - Python 2.7.12 - scons 2.5.0 - godot master
Linux Debian 8.5 - i686-w64-mingw32-gcc (GCC) 4.9.1 - python 2.7.9 - scons 2.3.1

Windows:
C:\godot\core\object.h(329): error C2059: syntax error: 'constant'
C:\godot\core\object.h(332): error C2143: syntax error: missing ';' before '}'
...
....
...
scons: *** [modules\enet\register_types.windows.tools.64.obj] Error 2
scons: building terminated because of errors.

Linux:
core/object.h:329:3: error: expected identifier before numeric constant
   CONNECT_DEFERRED=1,
   ^
core/object.h:329:3: error: expected '}' before numeric constant

Reproduce:
execute: c:\godot\scons platform=windows

**Comment by volzhs** [comment] 2016-08-17 16:49
oops, here is another one as same as #6180

**Comment by patchman** [comment] 2016-08-17 17:34
Workaround on Windows: Delete "Enet" in modules folder.

**Comment by vnen** [comment] 2016-08-17 18:22
Duplicate of #6156.

**Closed by vnen** 2016-08-17 18:22 UTC
