### ISSUE TITLE
set_as_top_level(true) causes issues when setting global position

### ISSUE THREAD

**Issue by B-rody** [godotengine/godot#43121] opened 2020-10-27 04:54 UTC
**Godot version:**
Godot v3.2.3

**OS/device including version:**
Win10 64 bit, GTX 1070ti

**Issue description:**
Setting set_as_toplevel(true), and then updating the global_position of the child sprite, does not reflect properly in the viewport. For me, it appears to stretch the sprite tremendously.

**Steps to reproduce:**
Create any node, and then a child sprite . On the child node, set_as_top_level(true). While running the game, somewhere in the script update the child node's global position - the dimensions of the sprite should be off.\

**Screenshot**
The top half screenshot is the initial configuration (the sprite on the right is the child). On the bottom, you can see the child sprite stretch horizontally across the screen after calling set_as_toplevel(true) and updating its global position to that of the parent.
![image](https://user-images.githubusercontent.com/44855384/97258872-aabec000-17d6-11eb-8833-a126bba986e4.png)

**Comment by mrjustaguy** [comment] 2020-10-27 09:10
Win 10, 64 bit 3.2.3 stable
Followed the steps..
Unable to reproduce, please add a MRP

However I did find another Possible bug when testing...

**Comment by akien-mga** [comment] 2020-10-27 14:21
Reopening as #43131 said "maybe fixes" and not "fixes". Needs testing to confirm.

**Comment by B-rody** [comment] 2020-10-27 16:14
@mrjustaguy what is a MRP?

**Comment by mrjustaguy** [comment] 2020-10-27 16:15
Minimal Reproduction Project

**Comment by B-rody** [comment] 2020-10-28 03:22
@mrjustaguy thank you very much for the explanation - I appreciate it. I've included the MRP below (hopefully to the minimization standards).

REPRO STEPS:

1. F5 to launch the project


[sandbox.zip](https://github.com/godotengine/godot/files/5449339/sandbox.zip)

**Comment by akien-mga** [comment] 2020-10-28 08:56
Tested the project, I didn't look in depth but I can confirm that there seems to be some unexpected behavior. I tested with #43131 cherry-picked so it doesn't seem to solve this issue (@groud).

**Comment by mrjustaguy** [comment] 2020-10-28 09:39
I've just tested it a little, There seems to be unexpected behavior due to scaling.. I'll update this when i know a little bit more.

**Comment by mrjustaguy** [comment] 2020-10-28 10:06
[Sandbox.zip](https://github.com/godotengine/godot/files/5450998/Sandbox.zip)

I was right.. there is a scaling issue with the sprites themselves.. when you are setting them as top level, the sprites don't change their scale to keep their size during the change... same goes for the position.. instead of their transform getting changed to match their transform pre top level change it just keeps the transform it used as a child, which when the parent node is scaled, as is the case, doesn't output the expected size for the child..

Above there is the project modified where i'm more or less changing the scale to keep it close to the original, thus proving the hypothesis. I've also changed the root node to node2d and moved the sprite to it, and added a camera to the child sprite in order to prevent it from running off screen. I've tested this on 3.2.3. stable, so the differences with #43131 haven't been tested yet.

**Comment by groud** [comment] 2020-10-28 10:41
> I was right.. there is a scaling issue with the sprites themselves.. when you are setting them as top level, the sprites don't change their scale to keep their size during the change... same goes for the position.. instead of their transform getting changed to match their transform pre top level change it just keeps the transform it used as a child, which when the parent node is scaled, as is the case, doesn't output the expected size for the child..

This is the expected behaviour, setting as top level should not change the position or scale you defined in the node. There's nowhere in the documentation stating that setting a node as toplevel changes its transform too. If you set a node as top_level, it simply does not inherit it's transform from its parents.

If you want to keep the same global transform, you should first store the global transform, then set as top_level, then reapply the same transform. Otherwise everything happening here seems correct to me.

**Comment by mrjustaguy** [comment] 2020-10-28 10:54
Yea I'd say this issue is closed as it's misuse and not an engine bug.. but hey, it did lead to a discovery of an actual bug.

To fix the "issue" just get the global transform of the streching sprite, then change toplevel, and then set the streching sprite's transform to the transform you got prior to toplevel change.

**Comment by groud** [comment] 2020-10-28 11:09
Yes, closing as this is not an actual bug. You can check using the remote inspector that the position/scale of the child node do not change when you change the top_level status, which is the expected behavior.

**Closed by groud** 2020-10-28 11:09 UTC
Labels: bug, topic:core

**Comment by B-rody** [comment] 2020-10-28 19:23
Thanks for the explanation as to how I should be using the functionality properly. Apologies the the false alarm - I'm glad it at least indirectly discovered a different bug!

**Comment by groud** [comment] 2020-10-28 19:45
No problem. :)
