### ISSUE TITLE
Vulkan Mobile: Curved MeshInstance3D's have strange lighting patterns

### ISSUE THREAD

**Issue by bepthomp** [godotengine/godot#67172] opened 2022-10-10 04:55 UTC
### Godot version

4.alpha3 -> 4.beta2

### System information

Windows 10, Vulkan Mobile, Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz 2.21 GHz

### Issue description

Curved surfaces on MeshInstance3D's such as spheres and capsules are being lighted strangely. 
This issue is not present in the Forward+ renderer or with cylinders.
This issue is present both in the editor and when rendered in a scene.
I have traced this back to version 4.alpha3

![image](https://user-images.githubusercontent.com/36116447/194800213-1269ae82-b7ed-4b61-a18b-b746da60a04f.png)

### Steps to reproduce

- Open up any Godot 4 version starting from 4.alpha3
- Spawn a MeshInstance3D
- Choose a sphere or capsule mesh

### Minimal reproduction project

[Sphere Lighting MRP beta-2.zip](https://github.com/godotengine/godot/files/9743396/Sphere.Lighting.MRP.beta-2.zip)

**Comment by Calinou** [comment] 2022-10-10 12:23
Duplicate of https://github.com/godotengine/godot/issues/58631 (same cause).

**Closed by Calinou** 2022-10-10 12:23 UTC
