### ISSUE TITLE
Some shader params not show in editors

### ISSUE THREAD

**Issue by marcosbitetti** [godotengine/godot#9068] opened 2017-06-06 11:33 UTC
**Operating system or device - Godot version:**
Ubuntu Studio 16.04 - Godot 3.0 (last commit 0fb99306ff747072dfabceeeba27ca4432b9aa49 )

Make any shader and put more than one uniform sampler2D bitmap to params not working!

![captura de tela_2017-06-05_20-32-46](https://cloud.githubusercontent.com/assets/85936/26827197/933ad8e8-4a92-11e7-8a10-cb3e596f35e6.png)

**Comment by bojidar-bg** [comment] 2017-06-06 11:58
Duplicate of #8353

**Closed by bojidar-bg** 2017-06-06 11:58 UTC

**Comment by quantum-entangler** [comment] 2017-06-06 18:34
@marcosbitetti should perhaps post the image to #8353?
