### ISSUE TITLE
AnimatedSprite2D animation frames picker pixel art is blurry

### ISSUE THREAD

**Issue by ViktorEvil** [godotengine/godot#69665] opened 2022-12-06 14:04 UTC
### Godot version

4.0.beta7

### System information

macOS Ventura 13.0.1, M1 Macbook Pro, Vulkan

### Issue description

The AnimatedSprite2D animation frames picker art is blurry even though the default texture filter is set to nearest in the project settings

<img width="625" alt="Screenshot 2022-12-06 at 13 54 22" src="https://user-images.githubusercontent.com/4403212/205932371-279799a1-cb07-478e-8471-c0ffdb6da78a.png">

### Steps to reproduce

use the AnimatedSprite2D node and assign pixel art to the animation frames and it is very blurry in the preview window

### Minimal reproduction project

N/A

**Comment by Calinou** [comment] 2022-12-06 15:19
Duplicate of https://github.com/godotengine/godot/issues/57550.

**Closed** 2022-12-06 15:19 UTC
