### ISSUE TITLE
Mesh flickering

### ISSUE THREAD

**Issue by nunodonato** [godotengine/godot#9328] opened 2017-06-23 10:53 UTC
**Operating system or device - Godot version:** Godot 3 master, Linux

**Issue description:**
My water plane (mesh instance plane) seems to flicker a lot when in game, but not in the editor.
I checked if it was related with the transparent flag but its not

gif:
https://media.giphy.com/media/3o7btSMiK0noEi1vAQ/giphy.gif

**Comment by Zylann** [comment] 2017-06-23 11:15
I don't see it flicker, however it "shakes" a little, looks like a float precision error

**Comment by nunodonato** [comment] 2017-06-23 11:20
perhaps, it seems to happen only the place where the 2 meshes meet
here's a better gif

![flick2](https://user-images.githubusercontent.com/1642015/27480025-45a591d4-580e-11e7-94dc-d6e1f588d70c.gif)

**Comment by reduz** [comment] 2017-06-23 11:25
it looks like it's moving up and down, are you sure the vertex shader is
not doing anything weird?

**Comment by nunodonato** [comment] 2017-06-23 11:26
@reduz absolutely sure, there is no shader, just a simple material :)

**Comment by reduz** [comment] 2017-06-23 11:27
again, if you can isolate a very simple test case, that would be great

**Comment by nunodonato** [comment] 2017-06-23 11:32
@reduz I think @Zylann might be right, it must be related with float precision.
I just changed the plane mesh parameters to have a depth of 10 instead of 1, and the "shakiness" is barely noticeable. So it might have to do with the fact that this plane is huge (2000x2000), and had too little vertices?

**Comment by reduz** [comment] 2017-06-23 11:46
oh, that is very possible

**Comment by kubecz3k** [comment] 2018-04-03 11:30
First of all thank you for your report and sorry for the delay.

We released Godot 3.0 in January 2018 after 18 months of work, fixing many old issues either directly, or by obsoleting/replacing the features they were referring to.

We still have hundreds of issues whose relevance/reproducibility needs to be checked against the [current stable version](https://godotengine.org/download), and that's where you can help us.
**Could you check if the issue that you described initially is still relevant/reproducible in Godot 3.0 or any newer version, and comment about its current status here?**

For bug reports, please also make sure that the issue contains detailed steps to reproduce the bug and, if possible, a zipped project that can be used to reproduce it right away. This greatly speeds up debugging and bugfixing tasks for our contributors.

Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

Thanks in advance.

*Note: This message is being copy-pasted to many "stale" issues (90+ days without activity). It might happen that it is not meaningful for this specific issue or appears oblivious of the issue's context, if so please comment to notify the Bugsquad about it.*

**Comment by akien-mga** [comment] 2018-05-29 08:41
> Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

As there was no update since the previous post, we close this issue.

If it is still relevant in the way it was described and discussed above, please comment to ask for it to be reevaluated. If it is only partly relevant, or if the original issue has changed, it would be better to open a new issue (potentially referring to this one) focused on the current state.

**Comment by Zylann** [comment] 2018-05-29 09:46
I got this happening too, in particular with big scaled meshes like a sea plane.

**Comment by akien-mga** [comment] 2018-05-29 10:03
We still lack any test case that could be used to debug it though.

**Comment by Zylann** [comment] 2018-05-29 19:40
Hmm I can only reproduce by making an island with some mesh and a sea as a PlaneMesh, which I scale by a factor of 20,000. I wonder if that's the case too for @nunodonato ?

**Comment by reduz** [comment] 2018-09-05 16:33
This is not a bug, guys. It's just lack of precision for floating point data. Just make your plane a grid and it will work better.

**Closed by reduz** 2018-09-05 16:33 UTC
Labels: bug, confirmed, topic:rendering

**Comment by roman-sitewits** [comment] 2020-12-09 19:26
It's a serious issue and a difficult one for beginners to describe and comprehend. The solution is to change the near and far planes of your camera (not the viewport in editor). You can change it to 5 and 999999 to maintain some precision between two **intersecting meshes**. This should prevent **z-index/z-buffer fighting** but will trim your front plane, you should probably try to adjust near/far clips dynamically for each camera as you move to ensure you don't clip the near objects when you are closer than 5m. You'd change it to 0.1 and 9999 if your camera is closer.
