### ISSUE TITLE
VS2015 (Win10) build failure: cannot open include file 'splash.gen.h' at main.cpp: line 42

### ISSUE THREAD

**Issue by willnationsdev** [godotengine/godot#9417] opened 2017-06-27 18:12 UTC
**Operating system or device - Godot version:**
Windows 10
Visual Studio 2015 Community Edition
Godot 3.0 (latest build, x64 Debug)

**Issue description:**
Pulled from origin/master. Attempted to make a build. Build error occurred.

Output below (lots of warnings too, but I won't post those unless desired):
`Error	C1083	Cannot open include file: 'splash.gen.h': No such file or directory	godot	godot\main\main.cpp	42	`
`Error	MSB3073	The command "echo Starting SCons && cmd /V /C set "plat=x86" ^& (if "x86"=="x64" (set "plat=x86_amd64")) ^& set "tools=yes" ^& (if "debug"=="release" (set "tools=no")) ^& call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" !plat! ^& scons platform=windows target=debug tools=!tools! -j2" exited with code 2.	godot	C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.MakeFile.Targets	41	`

**Comment by akien-mga** [comment] 2017-06-27 18:17
Retry, Windows needs several attempts if you use `-j2` to generate the relevant files.

**Comment by bojidar-bg** [comment] 2017-06-27 18:55
Duplicate of #5042.

**Closed by bojidar-bg** 2017-06-27 18:55 UTC

**Comment by willnationsdev** [comment] 2017-06-27 22:05
Ah, my mistake. Thank you for the correction.
