### ISSUE TITLE
Stuttering and LibPNG errors

### ISSUE THREAD

**Issue by StripedMonkey** [godotengine/godot#20442] opened 2018-07-25 10:45 UTC
**Godot version:**

3.0.5 & steam version

**OS/device including version:**

Ubuntu 18.04, R9 390x, and FX-8320
libpng-dev is installed @ 1.6.34, libpng++-dev @ 0.2.9, libpng-tools @ 1.6.34, libpng16-16 @ 1.6.34

**Issue description:**

When loading up the AssetLib or similar places I get this error:

```
ERROR: _png_error_function: Not a PNG file
   At: drivers/png/image_loader_png.cpp:62.
libpng error: Not a PNG file
ERROR: _load_image: PNG Corrupted
   At: drivers/png/image_loader_png.cpp:94.
ERROR: _load_mem_png: Condition ' err ' is true. returned: Ref<Image>()
   At: drivers/png/image_loader_png.cpp:252.
ERROR: copy_internals_from: Condition ' p_image.is_null() ' is true.
   At: core/image.h:327.
ERROR: _jpegd_mem_loader_func: Couldn't initialize ImageLoaderJPG with the given resource.
   At: modules/jpg/image_loader_jpegd.cpp:125.
ERROR: _png_error_function: Not a PNG file
   At: drivers/png/image_loader_png.cpp:62.
libpng error: Not a PNG file
ERROR: _load_image: PNG Corrupted
   At: drivers/png/image_loader_png.cpp:94.
ERROR: _load_mem_png: Condition ' err ' is true. returned: Ref<Image>()
   At: drivers/png/image_loader_png.cpp:252.
ERROR: copy_internals_from: Condition ' p_image.is_null() ' is true.
   At: core/image.h:327.
ERROR: _jpegd_mem_loader_func: Couldn't initialize ImageLoaderJPG with the given resource.
   At: modules/jpg/image_loader_jpegd.cpp:125.
```

**Steps to reproduce:**
Download via website or install via steam
Open up the AssetLib in the Project View
Stuttering and lag

**Comment by akien-mga** [comment] 2018-07-25 10:57
Duplicate of #17051.

**Closed by akien-mga** 2018-07-25 10:57 UTC
