### ISSUE TITLE
Undocking the 'script' tab to its own window causes collision shape resizers to disappear

### ISSUE THREAD

**Issue by amarraff** [godotengine/godot#82871] opened 2023-10-05 17:22 UTC
### Godot version

v4.1.1.stable

### System information

Godot v4.1.1.stable - Windows 10.0.22621 - Vulkan (Mobile) - dedicated NVIDIA GeForce RTX 3080 (NVIDIA; 31.0.15.3742) - AMD Ryzen 9 5900X 12-Core Processor (24 Threads)

### Issue description

When working with collision shapes, the orange resizer dots help to adjust them graphically without having to change values in the inspector. When the script tab is undocked from the editor, the resizer dots vanish. Upon re-docking the script window to the editor, they come back.

### Steps to reproduce

**The Bug**
1.) Create a new blank project, and begin with 'Node3D.'
2.) Add a 'StaticBody3D' as a child of the 'Node3D.'
3.) Add a 'CollisionShape3D' as a child of the 'StaticBody3D' and set it to 'new BoxShape3D.'
4.) Add a 'MeshInstance3D' as a child of the 'CollisionShape3D' set it to 'new BoxMesh.'
5.) In the node hierarchy, select the CollisionShape3D node. Note how the orange resizer dots appear in the viewport to help you adjust the collision shape graphically.
6.) Click on the 'Script' tab at the top of the editor.
7.) In the top right of the script tab, click the button that makes the script editor floating.
8.) Now that the script editor is floating, click on the '3D' tab at the top of the editor. The orange dots will likely still be visible, but may not be.
9.) In the node hierarchy, either click below all the nodes, or click another node, to deselect the collision shape.
10.) Click on the CollisionShape3D, and note how the orange resizer dots no longer appear. 

**To Undo the Bug**
1.) Navigate back to the floating script editor window and close it, which will dock it to the editor.
2.) In the node hierarchy, deselect the CollisionShape3D either by clicking below all the nodes, or clicking another node.
3.) Click on the CollisionShape3D, and note how the orange resizer dots appear again.

### Minimal reproduction project

N/A

### Image of the CollisionShape3D with the script tab docked
![image](https://github.com/godotengine/godot/assets/35876526/f658fa19-7c70-47d4-aeb6-056cc9979a4c)

### Image of the CollisionShape3D with the script tab floating
![image](https://github.com/godotengine/godot/assets/35876526/9400240f-d316-4f89-885d-362e071f7de6)

**Comment by jackwilsdon** [comment] 2023-10-07 20:43
It looks like this is a duplicate of #80588, which should be fixed in 4.2 (#80647).

**Comment by amarraff** [comment] 2023-10-07 21:04
> It looks like this is a duplicate of #80588, which should be fixed in 4.2 (#80647).

Oops! Thanks for letting me know, I did search through the open issues but didn't find those. Should I close this issue?

**Comment by jackwilsdon** [comment] 2023-10-07 21:09
If you're happy that it is fixed in 4.2 (I did test it on master but feel free to test it yourself - it was merged in dev snapshot 5), then it's probably worth closing :+1:

**Closed** 2023-10-07 22:00 UTC
