### ISSUE TITLE
Height fog turns itself on

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#9899] opened 2017-07-27 01:15 UTC
Godot 3.0 alpha1 official
Windows 10 64 bits

I restarted Godot a few times now without saving my scene, and I noticed that the height fog turns itself on randomly when I load the main scene. Sometimes it does, sometimes it doesnt. Maybe related to https://github.com/godotengine/godot/issues/9898.
`fog_height_enabled = false` in the .tscn, but it still shows as enabled in the scene.

![image](https://user-images.githubusercontent.com/1311555/28650045-47ad6274-7279-11e7-8e3f-f73dc6ded6b5.png)

Project: 
[Test3.zip](https://github.com/godotengine/godot/files/1178454/Test3.zip)

**Comment by RandomShaper** [comment] 2017-07-27 02:29
Could you try with a debug build?

**Comment by akien-mga** [comment] 2017-07-27 05:53
Duplicate of #9898, the setting is off, it's just the label which is wrong.

**Comment by Zylann** [comment] 2017-07-27 09:27
I'm pretty sure I've seen the fog turning itself on, as I said, the property was false in the scene but when I opened it the fog was on (even though the UI was wrong). Also the label is wrong but you can see the checkbox isn't checked in my screenshot. It's not 100% repro though.

**Comment by vnen** [comment] 2017-07-27 18:15
Well, I can clearly see the height fog in the OP's screenshot even though it's turned off in the Inspector.

**Comment by Zylann** [comment] 2017-07-27 22:10
It happened again when I launched the same project, back on my original computer.
The log doesn't say much, so me it looks like an uninitialized variable:

```
ERROR: RasterizerSceneGLES3::environment_set_tonemap: Condition ' !env ' is true.
   At: drivers\gles3\rasterizer_scene_gles3.cpp:914
ERROR: RasterizerSceneGLES3::environment_set_adjustment: Condition ' !env ' is true.
   At: drivers\gles3\rasterizer_scene_gles3.cpp:929
ERROR: RasterizerStorageGLES3::_render_target_allocate: Condition ' status != 0x8CD5 ' is true.
   At: drivers\gles3\rasterizer_storage_gles3.cpp:6237
loading scene DEFERRED
ERROR: RasterizerSceneGLES3::environment_set_tonemap: Condition ' !env ' is true.
   At: drivers\gles3\rasterizer_scene_gles3.cpp:914
ERROR: RasterizerSceneGLES3::environment_set_adjustment: Condition ' !env ' is true.
   At: drivers\gles3\rasterizer_scene_gles3.cpp:929
ERROR: PopupMenu::get_item_text: Index p_idx out of size (items.size()).
   At: scene\gui\popup_menu.cpp:696
ERROR: PopupMenu::set_item_checked: Index p_idx out of size (items.size()).
   At: scene\gui\popup_menu.cpp:644
```

**Comment by vnen** [comment] 2017-07-27 23:50
Is there any default environment set? Either a `default_env.tres` in the project root or whatever you set in the project settings (Rendering > Environment).

**Comment by Zylann** [comment] 2017-07-27 23:58
I don't have any default environment or `default_env.tres`.

**Comment by Noshyaar** [comment] 2017-07-28 00:35
For !env error, it happens to me too. I have the default environment resource file in the project root.

**Comment by reduz** [comment] 2017-08-22 13:03
can you try again?, this might be fixed now as other related bugs were fixed

**Comment by Zylann** [comment] 2017-08-22 19:50
I turned back fog in the project, and... it was a fail, height part is supposed to be disabled but I see it enabled:
![image](https://user-images.githubusercontent.com/1311555/29584369-cf72a5e2-8783-11e7-86c1-22d0b3846d02.png)

Toggling it a few times doesn't make a difference, it's still enabled in the viewport.

**Comment by reduz** [comment] 2017-08-25 12:23
@Zylann demo does not run, would appreciate a simpler demo

**Comment by Zylann** [comment] 2017-08-26 21:33
I made a simpler demo:
[HeightFogToggle.zip](https://github.com/godotengine/godot/files/1253982/HeightFogToggle.zip)
This project does have a default environment, but fog is disabled in it and the bug still shows.

![image](https://user-images.githubusercontent.com/1311555/29745277-b578aea8-8ab6-11e7-9667-26c34a24233a.png)

Note: while I was setting up the scene, I found that the console was completely filled with this error, to the point I could not see the initial console messages (logged every frame maybe?):
```
ERROR: _gl_debug_print: GL ERROR: Source: OpenGL        Type: Error     ID: 1282        Severity: High  Message: GL_INVALID_OPERATION error generated. Target doesn't match the texture's target.
   At: drivers\gles3\rasterizer_gles3.cpp:122
```

**Comment by reduz** [comment] 2017-08-29 17:49
I can't reproduce this with your demo project.. what hardware are you running it on? Tried with NVidia and AMD and simply does not happen..

**Comment by reduz** [comment] 2017-08-29 18:10
I did some changes to the struct and replaced bools by uin32_t, as this may be the compiler doing something funny. Can you try again?

**Comment by Zylann** [comment] 2017-08-29 19:22
I tested in two projects, looks like it's fixed :)

**Closed** 2017-08-29 20:41 UTC
Labels: bug, topic:editor, topic:rendering

**Comment by reduz** [comment] 2017-08-29 20:51
Guess size of bool is not 4 in all compilers..

**Comment by Zylann** [comment] 2017-08-29 20:55
Wow, I didn't imagine bool size would be 4 either^^  I always thought it would be 1 byte, but when size matters I just don't rely on it and prefer bitfields
