### ISSUE TITLE
Autocomplete incorrectly infers Autoload property types for custom class types

### ISSUE THREAD

**Issue by Haydoggo** [godotengine/godot#72990] opened 2023-02-09 20:54 UTC
### Godot version

v4.0.rc1.official [8843d9ad3]

### System information

Windows 10

### Issue description

When referencing an Autoload's property, if that property is a custom class, autocomplete will incorrectly infer the type of that property as `Object`.

In Godot 3.5.1, this issue is not present and autocomplete acts as expected.

### Steps to reproduce

Given the following 3 scripts:
```gdscript
# custom_class.gd
class_name CustomClass extends Node

var mesh : Mesh
```
_↓ Add this one to Autoloads in project settings_
```gdscript
# autoload.gd
extends Node

var mesh : Mesh
var custom_class : CustomClass
```
```gdscript
# main.gd
extends Node

func _ready():
	CustomClass.new().mesh # autocomplete works as expected
	Autoload.mesh # autocomplete works as expected
	Autoload.custom_class.mesh # autocomplete acts as though custom_class were of type Object
```
(At this point I restart the editor because there seem to be some issues with autocomplete and fresh autoloads/custom classes anyway)

In the final line of `main.gd`, after typing `Autoload.custom_class.`, autocomplete suggests only members of `Object` (eg. `free()`, `add_user_signal()`, etc.), and does not suggest any members of `CustomClass` nor of its base type `Node`

### Minimal reproduction project

[AutoCompleteBug.zip](https://github.com/godotengine/godot/files/10701400/AutoCompleteBug.zip)

**Comment by DragonAxe** [comment] 2023-03-09 07:29
I can confirm this still happens with Godot v4.0.stable.official [92bee43ad] on linux.

**Comment by thethunderingmarmot** [comment] 2023-03-22 07:20
This is also similar to a problem I have where an autoload singleton has some onready vars to reference its children and, when I access them outside of the singleton using its global variable, Godot only autocompletes their base class methods and not the ones I wrote in the child script, even if everything is statically typed.

**Comment by Calinou** [comment] 2023-04-01 17:03
- Duplicate of https://github.com/godotengine/godot/issues/71296.

**Closed by Calinou** 2023-04-01 17:03 UTC
Labels: bug, topic:editor
