### ISSUE TITLE
In editor indication of unique status of resource

### ISSUE THREAD

**Issue by Zireael07** [godotengine/godot#9037] opened 2017-06-03 18:33 UTC
**Operating system or device - Godot version:**
Win 7 x64

**Issue description:**
Toggling Make unique on a resource in editor has results that are very much not obvious (the only way to tell is to carefully watch the resource name - i.e. press Edit after toggling make unique).

Can we please get an output message telling us the current status? Even better, the resource might have some sort of an icon in the inspector indicating the uniqueness.

**Steps to reproduce:**
See description above

**Link to minimal example project:**

**Comment by akien-mga** [comment] 2017-06-29 09:56
Some visual info about the uniqueness would be nice to have indeed.

**Comment by mhilbrunner** [comment] 2017-11-08 04:03
@akien-mga This is a duplicate of #6922.

**Closed** 2017-11-08 09:24 UTC
Labels: enhancement, junior job, topic:editor, usability
