### ISSUE TITLE
boot_splash (improved).

### ISSUE THREAD

**Issue by ret80** [godotengine/godot#6057] opened 2016-08-06 12:20 UTC
**Operating system or device - Godot version:**
godot 2.x

**Issue description** (what happened, and what was expected):
Due to the feature of "iOS" need to be able to specify different boot splash for the platforms. Because for "ios" turns the double splash screen (1 - which is built in the "xcode" 2 - which is set in the project).

**Comment by Calinou** [comment] 2018-04-11 09:47
First of all thank you for your report and sorry for the delay.

We released Godot 3.0 in January 2018 after 18 months of work, fixing many old issues either directly, or by obsoleting/replacing the features they were referring to.

We still have hundreds of issues whose relevance/reproducibility needs to be checked against the [current stable version](https://godotengine.org/download), and that's where you can help us.
**Could you check if the issue that you described initially is still relevant/reproducible in Godot 3.0 or any newer version, and comment about it here?**

For bug reports, please also make sure that the issue contains detailed steps to reproduce the bug and, if possible, a zipped project that can be used to reproduce it right away. This greatly speeds up debugging and bugfixing tasks for our contributors.

Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

Thanks in advance.

*Note: This message is being copy-pasted to many "stale" issues (90+ days without activity). It might happen that it is not meaningful for this specific issue or appears oblivious of the issue's context, if so please comment to notify the Bugsquad about it.*

**Comment by Calinou** [comment] 2018-09-14 18:38
This appears to be a duplicate of https://github.com/godotengine/godot/issues/17427 which is more generic (and easier to understand), closing.

**Closed by Calinou** 2018-09-14 18:38 UTC
Labels: enhancement, platform:ios, topic:porting
