### ISSUE TITLE
inst_to_dict not support built-in script

### ISSUE THREAD

**Issue by CsloudX** [godotengine/godot#69486] opened 2022-12-02 12:23 UTC
### Godot version

v4.0.beta7.official [0bb1e89fb]

### System information

Windows10, 64bit

### Issue description

![image](https://user-images.githubusercontent.com/35988767/205292013-9891b8e5-b482-4451-a5cd-3bb8b8318420.png)

### Steps to reproduce

/

### Minimal reproduction project

[InstToDictTest.zip](https://github.com/godotengine/godot/files/10141032/InstToDictTest.zip)

**Comment by MewPurPur** [comment] 2022-12-02 13:15
Might be a duplicate of #6533?

**Comment by Chaosus** [comment] 2022-12-02 13:36
It seems like only built-in scripts are affected because `inst_to_dict` doesn't recognize them as resources and failed to check for it:
(https://github.com/godotengine/godot/blob/7bffdca41ccedd22eac831e916a02b890e90bb28/modules/gdscript/gdscript_utility_functions.cpp#L305-L314)

**Comment by Chaosus** [comment] 2022-12-02 13:41
This bug exists in the 3.x as well.

The check may be incorrect here and should be removed:

https://github.com/godotengine/godot/blob/7bffdca41ccedd22eac831e916a02b890e90bb28/modules/gdscript/gdscript_utility_functions.cpp#L305-L314

**Comment by KoBeWi** [comment] 2022-12-02 15:44
> This bug exists in the 3.x as well.

I tested in 3.5 and it works.

**Comment by Chaosus** [comment] 2022-12-02 16:06
@KoBeWi Are you sure?:

![image](https://user-images.githubusercontent.com/3036176/205334826-f47c9ca3-1d6d-4523-a221-66964505112d.png)

You must test it with a *built-in* script, run the following project in 3.5 stable version of Godot:
[Test.zip](https://github.com/godotengine/godot/files/10142543/Test.zip)

**Comment by KoBeWi** [comment] 2022-12-02 16:12
Ok I got confused, sorry.

But then if it's broken in both versions, it doesn't need 4.0 milestone.

**Comment by Chaosus** [comment] 2022-12-03 06:10
> But I think this is just a limitation. The method requires a script path to work, otherwise you won't be able to de-serialize the object. It's not possible to obtain a built-in resource from external scene (it's just not implemented. You can't preload them for the same reason).

Then I suggest adding it to the documentation of this method.

**Closed** 2022-12-19 17:22 UTC
Labels: topic:gdscript, documentation
