### ISSUE TITLE
.material file do not update the textures if they are packed in the .glb or .gltf embedded file

### ISSUE THREAD

**Issue by Linko-3D** [godotengine/godot#27410] opened 2019-03-25 15:50 UTC
Godot 3.1

If I export my model in .glb it is displayed correctly with his textures. But then if I change the texture, for example if I change the color of the albedo, it won't be updated. Even by deleting the .glb and .material and exporting the new .glb file the textures from the first time I imported the file are displayed.

**Comment by capnm** [comment] 2019-03-25 22:31
Duplicate of issue #20878 ;)

**Comment by Calinou** [comment] 2019-03-28 13:22
Duplicate of #20878.

**Closed by Calinou** 2019-03-28 13:22 UTC
