### ISSUE TITLE
Editor hangs, crashes desktop

### ISSUE THREAD

**Issue by mauriciomarinho2** [godotengine/godot#43190] opened 2020-10-29 19:37 UTC
**Godot version:** 
master 5bb7c7c36

**OS/device including version:** 
Pop_OS 20.10 - Gnome 3.38 - Kernel 5.8.0-7625-generic
GPU: Nvidia RTX 2070 Driver 455.28

**Issue description:**
Godot 4 hangs (some previous builds worked, although popups were like new windows), every time there seems to be a pop up or new window. Crashes X11 / Gnome desktop, window resizing stops updating its content after hanging.

Image showing the scaling issue
![Captura de tela de 2020-10-29 16-18-03](https://user-images.githubusercontent.com/2072617/97622758-77ad4400-1a03-11eb-8fc8-94754cb6b763.png)

Terminal output:

```
Godot Engine v4.0.dev.custom_build.5bb7c7c36 - https://godotengine.org
DisplayServer::_create_window 0 want rect: 448, 240, 1024, 600 got rect 448, 240, 1024, 600
DisplayServer::_window_changed: 0 rect: 109, 142, 1024, 600
Editing project: /home/mm/work/TEST (::home::mm::work::TEST)
Godot Engine v4.0.dev.custom_build.5bb7c7c36 - https://godotengine.org
DisplayServer::_create_window 0 want rect: 448, 240, 1024, 600 got rect 448, 240, 1024, 600
ERROR: Attempted to free invalid ID: 1017907249154
   at: _free_internal (drivers/vulkan/rendering_device_vulkan.cpp:6957)
DisplayServer::_window_changed: 0 rect: 0, 64, 1024, 600
DisplayServer::_window_changed: 0 rect: 0, 64, 1920, 1016
ERROR: Attempted to free invalid ID: 0
   at: _free_internal (drivers/vulkan/rendering_device_vulkan.cpp:6957)
DisplayServer::_create_window 1 want rect: 1770, 333, 150, 149 got rect 1770, 333, 150, 149
DisplayServer::_create_window 2 want rect: 510, 190, 900, 700 got rect 510, 190, 900, 700
DisplayServer::_window_changed: 2 rect: 510, 227, 900, 700
DisplayServer::_create_window 3 want rect: 142, 210, 173, 28 got rect 142, 210, 173, 28
DisplayServer::_window_changed: 2 rect: 581, 199, 900, 700
```

After using xkill to end the process:

```
X connection to :1 broken (explicit kill or server shutdown).
handle_crash: Program crashed with signal 11
Dumping the backtrace. Please include this when reporting the bug on https://github.com/godotengine/godot/issues
[1] /lib/x86_64-linux-gnu/libc.so.6(+0x41950) [0x7fa2319db950] (??:0)
[2] /lib/x86_64-linux-gnu/libnvidia-glcore.so.455.28(+0x1537c1b) [0x7fa229fb9c1b] (??:0)
[3] /lib/x86_64-linux-gnu/libnvidia-glcore.so.455.28(+0x152580c) [0x7fa229fa780c] (??:0)
[4] /lib/x86_64-linux-gnu/libnvidia-glcore.so.455.28(+0x1527d4f) [0x7fa229fa9d4f] (??:0)
[5] /lib/x86_64-linux-gnu/libnvidia-glcore.so.455.28(+0x15081ea) [0x7fa229f8a1ea] (??:0)
[6] /home/mm/Apps/godot/bin/godot.linuxbsd.tools.64(vkWaitForFences+0x54) [0x2dbb224] (/home/mm/Apps/godot/thirdparty/vulkan/loader/trampoline.c:1065)
[7] VulkanContext::prepare_buffers() (/home/mm/Apps/godot/drivers/vulkan/vulkan_context.cpp:1209)
[8] RenderingDeviceVulkan::prepare_screen_for_drawing() (/home/mm/Apps/godot/drivers/vulkan/rendering_device_vulkan.cpp:7170)
[9] RasterizerRD::prepare_for_blitting_render_targets() (/home/mm/Apps/godot/servers/rendering/rasterizer_rd/rasterizer_rd.cpp:37)
[10] RenderingServerViewport::draw_viewports() (/home/mm/Apps/godot/servers/rendering/rendering_server_viewport.cpp:455)
[11] RenderingServerRaster::draw(bool, double) (/home/mm/Apps/godot/servers/rendering/rendering_server_raster.cpp:116)
[12] RenderingServerWrapMT::draw(bool, double) (/home/mm/Apps/godot/servers/rendering/rendering_server_wrap_mt.cpp:93)
[13] Main::iteration() (/home/mm/Apps/godot/main/main.cpp:2444)
[14] OS_LinuxBSD::run() (/home/mm/Apps/godot/platform/linuxbsd/os_linuxbsd.cpp:261)
[15] /home/mm/Apps/godot/bin/godot.linuxbsd.tools.64(main+0x166) [0x1ca79cc] (/home/mm/Apps/godot/platform/linuxbsd/godot_linuxbsd.cpp:60)
[16] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf2) [0x7fa2319c2cb2] (??:0)
[17] /home/mm/Apps/godot/bin/godot.linuxbsd.tools.64(_start+0x2e) [0x1ca77ae] (??:?)
```

**Steps to reproduce:**

Create a new project, root 3D node, add a procedural sky, or just hold mouse until a pop up appears.

**Comment by mauriciomarinho2** [comment] 2020-10-29 19:48
Another screenshot showing scaling / updating issue

![Captura de tela de 2020-10-29 16-42-58](https://user-images.githubusercontent.com/2072617/97624565-09b64c00-1a06-11eb-98bc-0bbc64e4ca68.png)

Terminal output, lots of this:
```
ERROR: Condition "det == 0" is true.
   at: invert (core/math/basis.cpp:65)
```

Then this, after some time passed after scaling the window, still didn't update on screen though.
```
...
DisplayServer::_window_changed: 7 rect: 861, 146, 608, 513
DisplayServer::_window_changed: 7 rect: 861, 146, 609, 514
DisplayServer::_window_changed: 7 rect: 861, 146, 624, 520
DisplayServer::_window_changed: 7 rect: 861, 146, 643, 528
DisplayServer::_window_changed: 7 rect: 861, 146, 654, 536
DisplayServer::_window_changed: 7 rect: 861, 146, 660, 540
DisplayServer::_window_changed: 7 rect: 861, 146, 660, 541
...
```

Clicking the close button doesn't work, have to kill the process, hangs a bit on kill command, then frees up my mouse.

**Comment by Calinou** [comment] 2020-10-29 19:54
Duplicate of https://github.com/godotengine/godot/issues/41614.

**Closed by Calinou** 2020-10-29 19:54 UTC
