### ISSUE TITLE
Color picker hex textbox tooltip blocks keyboard input

### ISSUE THREAD

**Issue by Demkeys** [godotengine/godot#82106] opened 2023-09-22 09:29 UTC
### Godot version

v4.1.1.stable.official [bd6af8e0e]

### System information

Godot v4.1.1.stable - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce MX110 () - Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 Threads)

### Issue description

In the Color picker when you click on the Hex textbox to enter a value, if you leave your cursor on the textbox, a tooltip will appear. When this happens, keyboard input gets blocked and you can't enter text into the textbox until you do something that closes the tooltip. This behavior occurs on both Windows (Win 10) and Linux (Ubuntu Studio).
![GodotColorPicker](https://github.com/godotengine/godot/assets/18563612/028e93cc-7415-469b-8c3d-b6e781051b72)

### Steps to reproduce

To reproduce:
- Create root node
- Create ColorRect child node
- In Inspector, open the color picker by clicking Color. Then click on the Hex textbox and leave your mouse cursor there. Once the tooltip appears, keyboard input gets blocked.

### Minimal reproduction project

Given how simple the repro is I don't think uploading the project is necessary here. But if it's still required kindly let me know and I'll post it.

**Comment by AThousandShips** [comment] 2023-09-22 09:52
Duplicate of https://github.com/godotengine/godot/issues/79500

**Closed by AThousandShips** 2023-09-22 09:52 UTC
Labels: bug, confirmed, usability, topic:gui
