### ISSUE TITLE
3.6.beta5: WorldEnvironment SpaceScreen shaders are broken

### ISSUE THREAD

**Issue by ReanimatorXP** [godotengine/godot#92195] opened 2024-05-21 09:09 UTC
### Tested versions

- Reproducible in: 3.6.beta5
- Not reproducible in: 3.6.beta4, 3.5.2.stable

### System information

Windows 10 - Godot 3.6.beta5 - GLES3

### Issue description

Built-in shaders SSAO, SSR and DOF blur work incorrectly in GLES3. They strongly reduce lights from the light sources and completely ignore ambient light. 

![image](https://github.com/godotengine/godot/assets/24944063/af2c6a19-106e-4b8f-9f74-8a18d3b434ce)
![image](https://github.com/godotengine/godot/assets/24944063/40557d05-24d2-4302-960e-cfdbf8099eaf)

### Steps to reproduce

1. Create new empty project
2. Add some meshes (e.g. CSG boxes)
3. Add Directional Light
4. Add WorldEnvironment node
5. Set up WorldEnvironment:
6. Set any light color in the Ambient Light tab (e.g. #a0a0a0 )
7. Enable any of Screen Space or DOF shaders

### Minimal reproduction project (MRP)

[WorldEnvironmentMRP.zip](https://github.com/godotengine/godot/files/15387385/WorldEnvironmentMRP.zip)

**Comment by akien-mga** [comment] 2024-05-21 09:21
CC @lawnjelly

**Comment by lawnjelly** [comment] 2024-05-21 10:43
Presumably a duplicate of #91967 so already fixed.
I'll double check the project though.

Maybe we should leave #91967 open temporarily to prevent duplicates.

**Comment by lawnjelly** [comment] 2024-05-21 10:49
Yup this is fixed already, duplicate of #91967.

**Closed by lawnjelly** 2024-05-21 10:49 UTC
Labels: bug, topic:rendering, regression, topic:shaders
