### ISSUE TITLE
Undoing several times in TextEdit can lead to text being scrambled

### ISSUE THREAD

**Issue by YeldhamDev** [godotengine/godot#36188] opened 2020-02-13 18:22 UTC
**Godot version:**
3.2 and master.

**Issue description:**
Found this a couple of times while undoing in the script editor. It happens randomly, and this error generally pops up:
```
scene/gui/text_edit.cpp:3981 - Index p_to_column = 57 is out of bounds (text[p_to_line].length() + 1 = 57).
```

CC @Paulb23

**Comment by KoBeWi** [comment] 2020-02-14 13:24
Script editor generally does weird things when undoing autocompletion, especially with braces.
This one looks like duplicate of #34253 (same error)

**Closed by KoBeWi** 2020-02-14 13:24 UTC
Labels: bug, topic:core
