### ISSUE TITLE
Godot 3D Viewport not working correctly on my Linux machine

### ISSUE THREAD

**Issue by yohannes-jo** [godotengine/godot#64909] opened 2022-08-25 23:26 UTC
### Godot version

3.5 stable

### System information

Linux Mint, X11, GLES2/3, Intel HD Graphics 605

### Issue description

Any mesh instance I add to the project ends up being black, sometimes it works but then when it doesn't, it won't work again for an unspecified amount of time.
This problem extends to the runtime, 2D viewport works perfectly fine though.

### Steps to reproduce

Open a new/old project
- open a 3d scene
- create mesh instance and give it a shape (or resource, both end up the same way)
- that's it

**Comment by yohannes-jo** [comment] 2022-08-25 23:27
Didn't add a reproduction product since I'm writing through my phone at the moment, really sorry.

**Comment by jgillich** [comment] 2022-08-26 11:04
Does setting 2d size fix it? This is probably a duplicate of #55471

**Comment by yohannes-jo** [comment] 2022-08-26 11:28
> Does setting 2d size fix it? This is probably a duplicate of #55471

Since I'm using 3.5 stable, the renderer is GL, not vulkan
The 2D viewport works just fine, along with every node under it, it's just something with the mesh instances

**Comment by jgillich** [comment] 2022-08-26 12:24
Ah my bad, I didn't realize this is about 3.5

**Comment by Calinou** [comment] 2022-10-23 17:27
Duplicate of https://github.com/godotengine/godot/issues/25512.

**Comment by yohannes-jo** [comment] 2022-10-29 09:26
> Related to #25512, which occurs on Windows. The Windows Intel driver's codebase is entirely separate from the Linux driver, so rendering bugs aren't expected to be shared across platforms on Intel.
> 
> @yohannes-jo Do you have any lights in your projects? Also, please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

Yes, I do have lights in my projects. The problem doesn't stem from the lighting, it stems from the fact that every other time I open the editor, alongside the viewport, the meshes appear black unless light is reflecting off of them.
I would've assumed that happened as a result of lack of light (or a different implementation of it from GLES2, the one I use now as it works just fine) but it only happens half the time. Same with the exported or debug version of the project.
I will be sending a demo project now.

**Comment by yohannes-jo** [comment] 2022-10-29 09:46
[DemoProject.zip](https://github.com/godotengine/godot/files/9893365/DemoProject.zip)
I'll also be sending the occasions where it does work and when it does not. (it is not consistent at all)
[Photos.zip](https://github.com/godotengine/godot/files/9893368/Photos.zip)

**Comment by yohannes-jo** [comment] 2022-10-29 09:48
> [DemoProject.zip](https://github.com/godotengine/godot/files/9893365/DemoProject.zip) I'll also be sending the occasions where it does work and when it does not. (it is not consistent at all) [Photos.zip](https://github.com/godotengine/godot/files/9893368/Photos.zip)

**screenshots of the occasions, viewport usually doesn't glitch out until it gets re-opened, but the debug program is a roulette, you won't know what will happen whenever its opened/closed.

**Comment by yohannes-jo** [comment] 2022-10-29 09:49
> > [DemoProject.zip](https://github.com/godotengine/godot/files/9893365/DemoProject.zip) I'll also be sending the occasions where it does work and when it does not. (it is not consistent at all) [Photos.zip](https://github.com/godotengine/godot/files/9893368/Photos.zip)
> 
> **screenshots of the occasions, viewport usually doesn't glitch out until it gets re-opened, but the debug program is a roulette, you won't know what will happen whenever its opened/closed.

Half of the screenshots are the ones when it works as it should, and the rest are when it becomes pitch black.

**Comment by yohannes-jo** [comment] 2022-10-29 09:52
@Calinou here are the required files and descriptions. Sorry for the late reply.

**Comment by Calinou** [comment] 2022-10-29 19:51
@yohannes-jo PS: In the future, please use the **Edit** button (located behind the **…** icon in the top-right corner of your comments) instead of multi-posting.

**Comment by yohannes-jo** [comment] 2022-10-29 19:57
> @yohannes-jo PS: In the future, please use the **Edit** button (located behind the **…** icon in the top-right corner of your comments) instead of multi-posting.

Didn't notice it, will do.
Update on the issue: it seems to be only happening on GLES3, 2 works just fine.

But that disables a couple of good features so if there are solutions to this, much appreciated.

**Comment by Calinou** [comment] 2022-10-29 20:06
Duplicate of https://github.com/godotengine/godot/issues/43891.

**Closed by Calinou** 2022-10-29 20:06 UTC
Labels: bug, topic:rendering, topic:thirdparty, needs testing, topic:3d
