### ISSUE TITLE
Infinite recursive function calls crashes my game, throws Socket error: 10054

### ISSUE THREAD

**Issue by Dentrax** [godotengine/godot#27982] opened 2019-04-13 12:58 UTC
**Potential duplicates:** 
#27444 #22331 [and other issues](https://github.com/godotengine/godot/issues?utf8=%E2%9C%93&q=10054)

**Godot version:** 
`v3.1-stable_win64`

**OS/device including version:** 
`Windows 10 v1803 (x64)`

**Issue description:** 
When i trying to collect a object that have an area2d, and if i have a infinite resursive functions, game crashes instantly and throws an error:

```
ERROR: _get_socket_error: Socket error: 10054
   At: drivers/unix/net_socket_posix.cpp:190
```

```
func set_a(active):
	set_b(false)
        # codes
	
func set_b(active):
	set_a(false)
        # codes
```

There is only one this error. No other errors.

**Steps to reproduce:**
1. Add `area2d.connect("area_entered", self, "on_poweup_collected")` line
2. Call the `set_a(true)` function
3. That throws instantly when i interract with object's area2d.

**Minimal reproduction project:**
`N/A`

**Comment by Dentrax** [comment] 2019-04-13 13:25
After hard of working and debugging, i finally figured it out why it was happening. Thats because i was calling a recursive function like this:

```
func set_a(active):
	set_b(false)

	
func set_b(active):
	set_a(false)
```

When i call `set_a` in somewhere, that error happens. Debugger doesn't tell me that. I think, it should be print like this: "Hey, there is a recursive conflict, please check it out!"

**Comment by Zireael07** [comment] 2019-04-13 13:57
Socket error: 10054 is just the Godot debugger disconnecting, because your game crashed.

As for recursion, Godot not handling it nicely is I believe a preexisting issue.

**Comment by lupoDharkael** [comment] 2019-04-13 15:34
Relevant issue: https://github.com/godotengine/godot/issues/16435

**Comment by akien-mga** [comment] 2019-04-15 09:37
Duplicate of #16435 indeed.

**Closed by akien-mga** 2019-04-15 09:37 UTC
