### ISSUE TITLE
CollisionShape2D scale() not working?

### ISSUE THREAD

**Issue by Qws** [godotengine/godot#7375] opened 2016-12-27 01:56 UTC
This is my node hierarchy:
![image](https://cloud.githubusercontent.com/assets/3944421/21488277/f195d05c-cbdd-11e6-832f-8249b5527fd5.png)

```
Hierarchy:
RigidBody2D
  Sprite
  CollisionShape2D
```

I'm trying to scale down the Rigidbody2D node (Flame node):

![image](https://cloud.githubusercontent.com/assets/3944421/21488293/4320b7a2-cbde-11e6-94cb-3bd6f93e3f1f.png)

This is how I'm doing it. Sprite nodes scales down when I scale its parent down, but the Collision node does not.

Which is strange, because , if I do this in the graphical editor, everything scales perfectly fine, including the CollisionShape2D.

So I realise that I can't change CollisionShape2D size with the scale() method.

But how else can I scale a node with a CollisionShape2D?, I tried to to code within the CollisionShape2D node, it doesn't work either. So what can I do to dynamically shrink the Node with a collision?

Someone on IIRC told me to swap with 2 collision, but is that really the only way?

**Link to minimal example project** (optional but very welcome):

[Fire.zip](https://github.com/godotengine/godot/files/673461/Fire.zip)

**Comment by eon-s** [comment] 2016-12-27 04:45
I think is duplicated of #5734 

Apart from that, CollisionShape is a helper, wont scale the body's shapes or do anything other than add editor and debug tools.

You will have to scale the shape resources manually (get/set shape) and children (shapes are not children) instead of the body until Godot 3.x changes something on the way shapes are managed.

**Comment by Qws** [comment] 2016-12-31 22:51
I basically replaced it with KinematicBody2D.

I actually don't see the purpose of RigidBody2D... it's not programmeable in runtime, while the KinematicBody2D is.

**Comment by akien-mga** [comment] 2017-01-02 14:06
Duplicate of #5734 indeed.

**Closed by akien-mga** 2017-01-02 14:06 UTC
