### ISSUE TITLE
In node (Menu Button) is not running, the function (is_pressed ()) and in any case returns false ...

### ISSUE THREAD

**Issue by OlexiyKravchuk** [godotengine/godot#5000] opened 2016-06-02 18:44 UTC
In node (Menu Button) is not running, the function (is_pressed ()) and in any case returns false ...

**Comment by neikeq** [comment] 2016-06-02 18:52
It's hard to tell what the issue is about. Could you elaborate a bit more?
Are you expecting `is_pressed()` to return true when the `MenuButton` is clicked? If that's the case, did you keep the button pressed the enough time to be sure the state id not get lost between frames?

**Comment by slapin** [comment] 2016-06-02 18:59
Somebody just got a get!
Anyway, if node is not running == was not aded to scene, this is normal.
If it is about is_pressed() to return true, you don't want to use that, use signals instead.
```gdscript
button.connect("clicked", self, "_on_button_clicked")

func _on_button_clicked():
   print("Yeeeee!!!")
```

Should do the trick. If you need to set flag, set it from signal handler.

**Comment by OlexiyKravchuk** [comment] 2016-06-02 19:00
Of course I spent testing, and the button is clearly working, it can be seen because the pop-up menu appears after pressing, but the function does not return the truth ...

**Comment by neikeq** [comment] 2016-06-02 19:22
The pressed state is probably list between frames or reset immediately by the `MenuButton`. Check the following script:

``` GDScript

extends MenuButton

func _ready():
	set_process(true)
	set_fixed_process(true)
	connect("pressed", self, "_on_pressed")

func _process(delta):
	if is_pressed():
		prints("_process: is_pressed() is true")

func _fixed_process(delta):
	if is_pressed():
		prints("_fixed_process: is_pressed() is true")

func _on_pressed():
	prints("_on_pressed: is_pressed() is", str(is_pressed()))
```

In my tests, `is_pressed()` returned true inside `_on_pressed()` (which is the method connected to the `pressed` signal).

**Comment by slapin** [comment] 2016-06-03 08:37
Well, anyway, it is better to use signals which is my point.

**Comment by OlexiyKravchuk** [comment] 2016-06-03 14:42
guys let's not deviate from the topic, I have to inform you that there is "door stuck" and you offer me "climb up through the window," but it did not fix the bug, and I need exactly this function, instead of a signal ... =)

**Comment by neikeq** [comment] 2016-06-03 14:52
@OlexiyKravchuk The reason it's not working is because the button loses focus right after clicking it (since the `PopupMenu` grabs it). When Button loses focus, the pressed state is reset to false.
I don't see a way to change that. It would be easier to explain why exactly you need this method, so we can find a solution (if signal is not the right one for you).

**Comment by OlexiyKravchuk** [comment] 2016-06-03 15:54
@neikeq It is very strange behavior that immediately menu captures focus.
I did my version, in the script (the pop-up menu button), using simple buttons and attached to it a pop-up menu
and as long as I keep the button pressed, menu does not even appear, regardless of duration, and only then release the button pops up a menu, and the function (is_pressed ()) works correctly there ...

But I see another problem in the node (pop up menu) for some reason it does not want to become invisible when I call it a function hide (), and the same problem I see in all nodes inherit from the node (pop up)

**Comment by neikeq** [comment] 2016-06-03 16:02
That's weird. The PopupMenu should appear on mouse pressed, not released (at least it does so for me).

**Comment by OlexiyKravchuk** [comment] 2016-06-03 16:29
as I said, to work around this problem, I had to invent a "new wheel" instead of using the standard version of the node, but there I got another problem, which is now in the node (popup menu),.
But standard version (menu button) works, how it works for you, and this is the problem, it just needs to be fixed so that the menu appears when the button is released, this standard of conduct ...

**Comment by neikeq** [comment] 2016-06-03 21:09
You should have started from there :P
Then this is a feature request. I am not sure what's the opinions of others about showing the PopupMenu on mouse release instead of press, but I guess we could always add a flag for that.

**Comment by OlexiyKravchuk** [comment] 2016-06-04 15:28
@neikeq By the way (option button) works properly and function (is pressed) there, also works great, just as I have described before, and although it is almost the same as the (menu button) but at the (menu button), this functionality is broken ...
Give (option button) a chance to use it as an example of the standard ... =)

**Comment by akien-mga** [comment] 2020-05-26 09:32
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!

**Closed by akien-mga** 2020-05-26 09:32 UTC
Labels: feature proposal, topic:gui
