### ISSUE TITLE
Improve theme preview discoverability/usability

### ISSUE THREAD

**Issue by tehsquidge** [godotengine/godot#43106] opened 2020-10-26 20:00 UTC
**Godot version:**
3.2.3

**OS/device including version:**
Manjaro GNU/Linux

**Issue description:**
When adding a new theme I can double click on it in the Filesystem tab to bring up the "Theme Preview". After I add a new StyleBoxTexture to button, for example, I get the "Texture Region" panel and I can configure my texture. At this point I wanted to return to the "Theme Preview" panel and I expected double clicking on the theme in the Filesystem Browser would work as it had previously. Instead it always takes me back to the "Texture Region" editor.

The solution was to select the theme in the Control Node it was assigned too, in the Inspector tab, but this was not obvious to me at all.

I'm glad I was able to find a solution but I think this could be more intuitive.

**Steps to reproduce:**
* create a theme
* double click the theme in the Filesystem tab to open the "Theme Preview" panel
* Edit Theme -> Add Class Items -> Button
* Add a new StyleBoxTexture to the button
* Add the texture to the StyleBoxTexture and select it to open the "TextureRegion" panel
* Try double clicking on the theme again in the Filesystem tab. I expected the "Theme Preview" panel to open but I get the "TextureRegion" panel

**Comment by KoBeWi** [comment] 2020-10-26 20:37
Looks similar to #28341

**Comment by Calinou** [comment] 2021-01-05 17:28
Duplicate of #28341.

**Closed by Calinou** 2021-01-05 17:28 UTC
Labels: enhancement, topic:editor
