### ISSUE TITLE
Godot physics skeleton creation is broken

### ISSUE THREAD

**Issue by S-h-0-X** [godotengine/godot#39054] opened 2020-05-25 20:06 UTC
**Godot version:**
3.2.1, 3.2.2 beta 1, 3.2.2 beta 2, 3.2.2 beta 3

**OS/device including version:**
Linux - Arch Linux, Ubuntu 20.04, Ubuntu 18.04
Windows - 10

**Issue description:**
When imported any of the provided GLTF models, Godot seems to fail to create a correct physical bone structure, skewing the capsules and/or the underlying physical bones, resulting in an incorrect simulation of the model when the simulation starts.

**Steps to reproduce:**
- Open the Godot project provided within the issue
- Open any of the three GLTF models provided in the scene
- Select the skeleton and create a physical skeleton
- Attach a script to the skeleton node (located in Characters/Skeleton.gd)
- Save the scene with the model within the Characters folder
- Open the test level scene
- Drag the newly created .tscn model scene into the test scene, position, and scale accordingly if required
- Press play

**Minimal reproduction project:**
[GodotPhysicsTest.tar.gz](https://github.com/godotengine/godot/files/4678682/GodotPhysicsTest.tar.gz)

**Comment by Calinou** [comment] 2020-05-25 20:59
Duplicate of #33057?

**Comment by addmix** [comment] 2020-11-24 10:08
So you're trying to tell me that this isn't going to get fixed until 4.0
well crap.

**Comment by Calinou** [comment] 2020-11-24 14:31
Duplicate of #33057.

@addmix Bugs are fixed on a best-effort basis – in other words, when someone knows how to fix them :slightly_smiling_face:

**Closed by Calinou** 2020-11-24 14:31 UTC
Labels: bug, topic:import

**Comment by manglemix** [comment] 2021-04-11 05:30
Well i've recently been working with physical skeletons. From my experience the capsules created when clicking "Create physical skeletons" are not aligned with their parent bones. Weirdly enough, they are all offset by a predictable amount. My fix is as follows"
Attach this code to the Skeleton node, and reload the scene (close all other scenes which instance this scene too)
```tool
extends Skeleton


func _ready():
	for child in get_children():
		if child is PhysicalBone:
			child.global_transform = get_bone_global_pose(find_bone(child.bone_name))
			child.global_transform.origin += global_transform.origin
			child = child.get_child(0)
			child.rotation.x = PI / 2
			child.transform.origin.y = child.shape.height / 2 + child.shape.radius
```
