### ISSUE TITLE
Godot lose passthought ability on transparent window on 3.2.2

### ISSUE THREAD

**Issue by seyacat** [godotengine/godot#41061] opened 2020-08-06 04:20 UTC
**Godot version:**
3.2.2

**OS/device including version:**
Windows 10

**Issue description:**
when use trasparent window it lose mouse pass thought ability and block clicks, on 3.1.2 works OK

**Steps to reproduce:**
Display → Window → Per Pixel Transparency → Allowed
Display → Window → Per Pixel Transparency → Enabled
get_tree().get_root().set_transparent_background(true)
[OvelayBug.zip](https://github.com/godotengine/godot/files/5032518/OvelayBug.zip)

**Minimal reproduction project:**

**Comment by clayjohn** [comment] 2020-08-06 04:37
This is a duplicate of #39914. Specifically see [this comment](https://github.com/godotengine/godot/issues/39914#issuecomment-651068198) that explains why the behaviour changed between 3.1 and 3.2.

**Comment by pouleyKetchoupp** [comment] 2020-08-07 07:41
Closing as duplicate of #39914.

**Closed by pouleyKetchoupp** 2020-08-07 07:41 UTC
Labels: platform:windows, topic:rendering
