### ISSUE TITLE
Tilemap editor gui don't stay in place in Animation tab

### ISSUE THREAD

**Issue by ElefanteNoi** [godotengine/godot#31836] opened 2019-08-31 18:59 UTC
**Godot version:**
3.1.1 stable

**OS/device including version:**
Windows 7

**Issue description:**
~~https://im2.ezgif.com/tmp/ezgif-2-2744b0f33c16.gif~~
https://i.imgur.com/lJ6tDaY.gif

**Steps to reproduce:**
Select Animation tab in Tilemap Editor

**Comment by myhalibobo** [comment] 2019-09-03 03:19
Self-compiled 3.1.1 doesn't have this problem

**Comment by bojidar-bg** [comment] 2019-09-03 05:36
What is the size of the editor window, in pixels (or, if maximised, the size of your screen)?

**Comment by myhalibobo** [comment] 2019-09-03 06:15
@bojidar-bg I found this error, need to reduce the window, the full screen will not be a problem

**Comment by akien-mga** [comment] 2019-11-25 12:58
Duplicate of #28135, fixed by #33829.

**Closed by akien-mga** 2019-11-25 12:58 UTC
Labels: bug, topic:editor
