### ISSUE TITLE
RayCast2D appears to use previously collided item

### ISSUE THREAD

**Issue by ivanskodje** [godotengine/godot#6872] opened 2016-10-19 15:36 UTC
**Operating system or device - Godot version:**
x11.64 - v2.2.alpha 

**Issue description** (what happened, and what was expected):
When I change raycast position and cast_to, and stores the next item, it appears to print the previous item's name before the new item.

**Steps to reproduce:**
Download example code:
[RayCast2D Bug.zip](https://github.com/godotengine/godot/files/539453/RayCast2D.Bug.zip)

Run program;
- Click on Item#1 (nothing prints out)
- Click on Item#1 again (Item#1 name prints out)
- Click on Item#2 (name for Item#1 prints out)
- Click on Item#2 (name for Item#2 prints out)

As you can see, even after setting new positions and cast_to, it keeps displaying previous item after changing.

**Comment by rgrams** [comment] 2016-10-20 02:23
I just ran into this issue myself, it's not really a bug. Read http://docs.godotengine.org/en/latest/tutorials/ray-casting.html?highlight=raycast2d

The problem is collisions are part of the physics system, which only updates on fixed_process. So yes, you can move your ray around all you want, but until another fixed_process comes around, it won't update and will just give you the last collision. 

To do this, use `Physics2DDirectSpaceState.intersect_ray()`. Or `intersect_point()` or `intersect_shape()`, depending on your needs. It's a bit more clunky that setting things up in the editor, but I believe it's the only way to check collisions at arbitrary points like this. (if you don't want to update the position of your ray every frame.) It will still only detect collisions as things were last fixed_process, but unless you are moving things around and _then_ trying to detect them, I should think 60 fps would be fine. And if that's still game-breaking you can always increase the rate of fixed_process in your project settings.

**Comment by bojidar-bg** [comment] 2016-10-20 05:56
Related PR: #6090

**Comment by Tybobobo** [comment] 2016-10-20 20:31
Appreciate your suggestions. 
I hope this will be adjusted in the future, as it is not very intuitive for it not to update immediately when you set it :)

**Comment by razvanc-r** [comment] 2016-10-21 08:45
I agree with this, I would also have thought that `cast_to` will force an update in the physics server...

**Comment by razvanc-r** [comment] 2017-12-25 07:36
I was revisiting this issue, #6090 PR seems to partly fix this I guess. My question, shouldn't the engine automatically call `force_raycast_update` automatically (hidden) when `cast_to` is changed? I can't think of any instance when you wouldn't want a forced update after changing `cast_to`. Or another option would be to have a toggle property in the inspector, like `Force Auto Update` or something. I've also seen @reduz's point that if threaded physics is used this isn't reliable. Is this still an issue or was it fixed somehow? It isn't clear in the PR. How would this impact he auto-update should there be an option like this in the inspector? @WalasPrime

**Comment by WalasPrime** [comment] 2017-12-25 17:22
Not sure about the multi threaded reliability, but #6090 describes a similar use case, where I expected an automatic recalculation of the ray trace. Perhaps after changing any of the ray trace's properties it should be marked as _dirty_, and then, if any of the `is_colliding` etc. or `get_collider` etc. methods are called then recalculate if dirty (otherwise, ray cast is calculated on a physics frame, so use that result). This also would take care of a case in which a script would perhaps modify a raycast at the end of a frame without considering the result.
Then again, I'm not sure where we are in terms of querying the physics server if it's in another thread (does it block? does it use a state snapshot from previous frame?).

**Comment by akien-mga** [comment] 2018-11-22 10:19
Fixed in #21597.

**Closed by akien-mga** 2018-11-22 10:19 UTC
Labels: enhancement, topic:physics
