### ISSUE TITLE
Animation Tree + Bezier Curves = unexpected behaviour

### ISSUE THREAD

**Issue by fguillen** [godotengine/godot#77662] opened 2023-05-30 14:35 UTC
### Godot version

4.0.stable, 4.0.3 and 4.1-dev3

### System information

MacOS - Ventura 13.1 - Godot 4.0.stable, 4.0.3 and 4.1-dev3

### Issue description

I have 2 animations: 

- _appear_: it contains a track with _Bezier curves_ on the property _scale_
- _idle_: it contains _property_ track in the property _scale_

When I use both Animations in an AnimationTree the Bezier Curve Animation doesn't work properly.

Please see the video with the reproduction of the issue: https://youtu.be/AXDrEEJWysk

### Steps to reproduce

Add an AnimationPlayer Node

1) Create 2 Animations (creating the RESET Animation):
- _appear_: it contains a track with _Bezier curves_ on the property _scale_
- _idle_: it contains _property_ track in the property _scale_

2) Add an AnimationTree Node
Add a TreeRoot as AnimationNodeStateMachine
Assign the previous AnimationPlayer as the AnimPlayer
Add the 2 previous Animations
Concatenate them:

![Screenshot 2023-05-30 at 16 33 55](https://github.com/godotengine/godot/assets/23043/ce18e306-7b7c-4597-9a48-8dc3700460c4)

3) Activate the AnimationTree. One of the animations is not working.

The error is happening in the editor as well as in the running project on each Scene

Please see the video with the reproduction of the issue: https://youtu.be/AXDrEEJWysk

### Minimal reproduction project

[GodotBugReproductionProjectAnimationTreeAndBezierCurves.zip](https://github.com/godotengine/godot/files/11601073/GodotBugReproductionProjectAnimationTreeAndBezierCurves.zip)

**Comment by AThousandShips** [comment] 2023-05-30 14:41
Does it work in a running project, or is it broken both in editor and running? Can you test this on 4.0.3?

**Comment by fguillen** [comment] 2023-05-30 14:58
> Does it work in a running project, or is it broken both in editor and running? Can you test this on 4.0.3? Can you test it on 4.1.dev?

- Tested in 4.0.3 and 4.1-dev3: same issue. In 4.1-dev3 all the Animations stop working. in 4.0.3 only the Bezier Curve one
- The error is happening in the editor as well as in the running project on each Scene

**Comment by TokageItLab** [comment] 2023-06-23 06:26
Duplicate of https://github.com/godotengine/godot/issues/49431

**Closed** 2023-06-23 06:30 UTC
Labels: bug, archived, topic:animation
