### ISSUE TITLE
Cursor miss-alignment in the interface

### ISSUE THREAD

**Issue by Lulink13** [godotengine/godot#16209] opened 2018-01-30 19:57 UTC
**Godot version: 3.0 (but not exclusive to it)**
**OS/device including version: Windows 10 / ASUS VivoBook Flip 14**
**Graphic card: Intel HD Graphics 620**
**Issue description:**
All windows badly recognize the cursor position. 
The vertical miss-alignment is higher the higher in the window I point. It's acting like I'm aiming higher than I actually am. This miss-alignment seems to be gone on the very bottom of the window.
The horizontal miss-alignment is null in the center but high on each side. It's acting like I'm aiming farter on that side that I actually am.
It might be linked to how the window border (the one native to Windows 10) is rendered, as the miss-alignment is as high as the part displaying the title of the window.

I have tried a few compatibility options:
All compatibility packs yelled no results.
The option letting Godot do the up-scaling of the window fixes another problem where the title of the window would overlap with parts of Godot's interface, but doesn't change the way the cursor's position is interpreted.

As said before, I've had this issue in the last version of Godot too. This problem might be specific to my PC, as I've noticed it in 2 other programs so far, even though both of them had a way to fix or avoid the problem:
In LibreOffice, a text editor, using a compatibility pack fixed this problem as well as an overlap problem mentioned earlier (which I have found a fix to, for Godot's case) .
In Minecraft, the problem was only apparent in windowed mode, as the fullscreen mode made the window border disappear, fixing the miss-alignment in the process.

**Steps to reproduce: None.**

**Fix suggestions:**
Add a fullscreen mode to Godot (pointless for other users?).
Find how to change the way Window's borders are displayed.
I believe it's fixable as only Godot and the 2 other programs mentioned above have this problem, unlike all the others programs I use regularly, many of which do work fine using Windows 10's borders.

**Attached file: screenshot of Godot**
The cursor isn't rendered but you might see something weird I don't about the window borders.
![capture](https://user-images.githubusercontent.com/18289021/35588211-2f4899b8-0600-11e8-8a3a-bbf834cdb41f.PNG)

**Comment by reduz** [comment] 2018-01-30 20:00
This was a bug in the Intel drivers, from what I remember. It is fixed by
updating them or updating Windows.

**Comment by vnen** [comment] 2018-01-30 20:18
Yes, this is a duplicate of #8902. Since it's an issue with the Intel drivers, I don't think there's anything we can do.

**Closed by vnen** 2018-01-30 20:18 UTC

**Comment by Lulink13** [comment] 2018-01-30 20:26
I updated the driver of my graphic card through the peripheral management tool and it worked right-away. Thanks a lot and sorry for this duplicate!
This fixed my problem with Minecraft in Windowed mode too.
