### ISSUE TITLE
In Godot4 alpha 15 billboard particles are now missing Quad mesh option in the draw pass and shaders act weird

### ISSUE THREAD

**Issue by MeshVoid** [godotengine/godot#65186] opened 2022-09-01 09:19 UTC
### Godot version

4.0.alpha15 

### System information

Windows 10, Vulkan, Nvidia Gefore 1080, Nvidia Gefore 1070, Amd Ryzen 2700x

### Issue description

I have noticed that particles looked weird in the newest alpha release of Godot 4. At first I thought that it might be the problem with how engine renders mesh with materials that have billboard particles turned on. But then I noticed that in particle mode I don't even have an option to generate quad mesh:
![image](https://user-images.githubusercontent.com/35863328/187875172-cc8c3260-2960-4ec2-86ea-afedfa01b661.png)

All the GPUparticles that have had Quad mesh assigned in the draw pass, are now automatically substituted with Plane mesh, where Particle Billboard in the material options looks skewed (Should it look like that, or is it also a bug?).

For example, this used to be normal fire particle in Godot alpha 14, now it's broken in Godot alpha 15.
![image](https://user-images.githubusercontent.com/35863328/187876070-9edddf64-7277-416b-92c7-bcd91ca4d885.png)

Also, I have noticed that Godot4 alpha 15 permanently breaks compatibility of majority of shaders both visual and spatial and GPUparticles made in Godot4 alpha 14, completely corrupting the project? But that is my assumption so far. I don't know if it is intentional and now I should start everything from scratch in GD4alpha15.

Same scene in Godot4 alpha15 looks like this (previously made in Godot4 a14):![image](https://user-images.githubusercontent.com/35863328/187877988-4068fe14-3a73-47bc-8f18-ad3ded1395c8.png)

Same project in Godot4 loaded again in Godot4 alpha14:
![image](https://user-images.githubusercontent.com/35863328/187878522-0f033aa5-f322-4b4d-90ca-60cf78b8d4d5.png)

P.S. The whole project is weird now, even when shader cache is deleted and .godot folder inside the project is wiped.

### Steps to reproduce

1 - Add a GPUparticle scene
2 - Go to draw pass tab and look at the list of objects to draw

To reproduce the weirdness with shaders I experience:

1 - open a project with different shaders and GPUparticles made in GD4 alpha 14 with GD5 alpha 15, compare the two differences, it is impossible to not notice problems.

**Comment by Zireael07** [comment] 2022-09-01 09:28
Quad was merged with PlaneMesh. Pick the planemesh from the list and check if it fixes it?

If not, this is likely caused by octahedral compression...

**Comment by MeshVoid** [comment] 2022-09-01 09:39
Same.
![image](https://user-images.githubusercontent.com/35863328/187882975-2939d178-4fb9-4532-9ddf-1ad7e6bc8072.png)
I did that just now, and the first time I launched the project, that was my first thought that Quad mesh got merged with Plane mesh, because it was strange for me to have both. But, Plane mesh always skewed with Billboard particle mode turned on in the materials, so I guess when they merged the two, they forgot to fix Plane meshe Billboard particle mode bug.

To reproduce it do the following:
- Add GPUparticles scene
- go to drawing pass
- select plane mesh
- assign a material with Billboard particles mode turned on or make a new one
- observe that it is rendered incorrectly in the viewport.

**Comment by clayjohn** [comment] 2022-09-01 16:14
For the QuadMesh/PlaneMesh issue, you need to set the ``orientation`` property of the [PlaneMesh](https://docs.godotengine.org/en/latest/classes/class_planemesh.html) to ``FACE_Z`` then it will behave the same as QuadMesh did.

For the other issues, it indeed looks like an Octahedral compression issue. To fix it, you just need to reimport your assets

**Comment by MeshVoid** [comment] 2022-09-02 05:36
> For the QuadMesh/PlaneMesh issue, you need to set the `orientation` property of the [PlaneMesh](https://docs.godotengine.org/en/latest/classes/class_planemesh.html) to `FACE_Z` then it will behave the same as QuadMesh did.
> 
> For the other issues, it indeed looks like an Octahedral compression issue. To fix it, you just need to reimport your assets

OMG, thank you for your tip on resolving particle issue, I didn't even see that option there until you mentioned, always used QuadMesh because of that, thank you!

**Closed** 2022-09-19 20:06 UTC
Labels: bug, topic:rendering
