### ISSUE TITLE
Vector2/Vector3 shorthands

### ISSUE THREAD

**Issue by homer666** [godotengine/godot#10757] opened 2017-08-29 14:15 UTC
It would be handy to have shorthands for axis-aligned Vector2 and Vector3 values, like what is seen in Unity. Typing `Vector3.up` is a lot easier than `Vector3(0, 1, 0)`, and I'm pretty sure there are a few functions that require a common value like that (`move_and_slide()` is the one that comes to mind.) It comes up frequently enough that it becomes a little annoying to fully type out each time, and Unity set the precedent for this so a lot of people would also appreciate it. I know this is kind of an annoying request, but I think it's worth bringing up before 3.0 goes stable and compatibility-breaking changes like this can no longer be done.

**Comment by Zireael07** [comment] 2017-08-29 14:18
Oh yeah, I miss Vector3.forward() so much.

**Comment by akien-mga** [comment] 2017-08-29 14:19
Duplicate of #7317.

**Closed by akien-mga** 2017-08-29 14:19 UTC
Labels: archived
