### ISSUE TITLE
[Beta 11] `Your video card driver does not support selected Vulkan version.` error given when OpenXR is enabled.

### ISSUE THREAD

**Issue by addmix** [godotengine/godot#71266] opened 2023-01-12 10:42 UTC
### Godot version

4.0 Beta 11

### System information

Windows 10 version 22H2, GeForce Game Ready Driver Version 528.02, GTX 1070

### Issue description

Since Beta 11 this error is given whenever a project is run in the forward+ renderer with OpenXR enabled. This error is not present with Beta 10 and previous versions.
![image](https://user-images.githubusercontent.com/38119387/212044209-1179b908-f010-47a1-ae53-bc2faadc30de.png)

I've tested with projects created in previous versions as well as the current version (Beta 11)

### Steps to reproduce

Create project, enable OpenXR in project settings, and run.

### Minimal reproduction project

N/A

**Comment by Chaosus** [comment] 2023-01-12 11:29
cc @BastiaanOlij, @clayjohn

**Comment by BastiaanOlij** [comment] 2023-01-12 11:44
It would be good to run this from console with `--verbose` to get some more info but we've been adding a lot of checks to make sure the hardware on computers can actually run the renderer. Some limitations were being ignored until Godot crashed when you tried ran into the places where they were used.

That said, we may have become too strict in places where most of the renderer works and we should simply be disabling a feature.

**Comment by abderman** [comment] 2023-01-13 19:07
Godot version

4.0 Beta 11
Wersja	Windows 11 Home Insider Preview
Wersja	22H2
Zainstalowano dnia	‎13.‎01.‎2023
Kompilacja systemu operacyjnego	25276.1000
Możliwości	Windows Feature Experience Pack 1000.25276.1000.0
Nazwa urządzenia	drugi
Procesor	AMD Ryzen 5 3550H with Radeon Vega Mobile Gfx     2.10 GHz
Zainstalowana pamięć RAM	8,00 GB (dostępne: 7,81 GB)
Identyfikator urządzenia	4FF0DC26-6C50-4F35-A5E5-4400C8BABC04
Identyfikator produktu	00325-81979-88519-AAOEM
Typ systemu	64-bitowy system operacyjny, procesor x64
Pióro i urządzenia dotykowe	Brak obsługi pióra i wprowadzania dotykowego dla tego ekranu

![obraz](https://user-images.githubusercontent.com/5955262/212399088-4adbf8d4-74c5-440f-a9ba-38fed6b28ed7.png)


Microsoft Windows [Version 10.0.25276.1000]
(c) Microsoft Corporation. Wszelkie prawa zastrzeżone.

C:\Users\ja>C:\Users\ja\Desktop\Godot_v4.0-beta12_win64.exe --verbose

C:\Users\ja>Godot Engine v4.0.beta12.official.3c9bf4bc2 - https://godotengine.org
TextServer: Added interface "Dummy"
TextServer: Added interface "ICU / HarfBuzz / Graphite (Built-in)"
Text-to-Speech: SAPI initialized.
Using "winink" pen tablet driver...
OpenGL Renderer: NVIDIA GeForce GTX 1650/PCIe/SSE2
WASAPI: Activated device using IAudioClient3 interface
WASAPI: wFormatTag = 65534
WASAPI: nChannels = 2
WASAPI: nSamplesPerSec = 48000
WASAPI: nAvgBytesPerSec = 384000
WASAPI: nBlockAlign = 8
WASAPI: wBitsPerSample = 32
WASAPI: cbSize = 22
WASAPI: mix_rate = 48000
WASAPI: fundamental_period_frames = 480
WASAPI: min_period_frames = 480
WASAPI: max_period_frames = 480
WASAPI: selected a period frame size of 480
WASAPI: detected 2 channels
WASAPI: audio buffer frames: 480 calculated latency: 10ms

TextServer: Primary interface set to: "ICU / HarfBuzz / Graphite (Built-in)".
CORE API HASH: 4072604822
EDITOR API HASH: 1984282193
EditorSettings: Load OK!
Project is missing: C:/MyData/gravitY/project.godot
Project is missing: C:/MyData/gravitY2/project.godot
Project is missing: C:/MyData/gtKoo/project.godot
Project is missing: C:/MyData/hedge/project.godot
Project is missing: C:/MyData/hedge Ś kopia/project.godot
Project is missing: C:/Users/ja/Documents/four/project.godot
Project is missing: C:/MyData/listkiTEST/demo/project.godot
Project is missing: C:/MyData/listkiTEST/project.godot
Project is missing: C:/MyData/Pepper Clicker/project.godot
Loaded builtin certs
EditorSettings: Save OK!
ERROR: Error opening file 'C:/MyData/lost/ico.png'.
   at: (core/io/image_loader.cpp:90)
ERROR: Error opening file 'C:/MyData/BanieczkoTeoLogia Ś kopia (2)/ico.png'.
   at: (core/io/image_loader.cpp:90)
ERROR: Error opening file 'C:/Users/ja/Documents/Basic physics based object pickup/icon.png'.
   at: (core/io/image_loader.cpp:90)
ERROR: Error opening file 'C:/MyData/Godot-RichTextEffect-SampleProject-master/icon.png'.
   at: (core/io/image_loader.cpp:90)
Editing project: C:/Users/ja/Documents/f1
Godot Engine v4.0.beta12.official.3c9bf4bc2 - https://godotengine.org
TextServer: Added interface "Dummy"
TextServer: Added interface "ICU / HarfBuzz / Graphite (Built-in)"
EditorSettings: Save OK!
Text-to-Speech: SAPI initialized.
XR: Clearing primary interface
XR: Removed interfaceNative mobile
XR: Removed interfaceOpenXR
WARNING: GENERAL - Message Id Number: 0 | Message Id Name: Loader Message
        Layer name GalaxyOverlayVkLayer does not conform to naming standard (Policy #LLP_LAYER_3)
        Objects - 1
                Object[0] - VK_OBJECT_TYPE_INSTANCE, Handle 2337217660128
     at: _debug_messenger_callback (drivers/vulkan/vulkan_context.cpp:259)
WARNING: GENERAL - Message Id Number: 0 | Message Id Name: Loader Message
        Layer name GalaxyOverlayVkLayer_VERBOSE does not conform to naming standard (Policy #LLP_LAYER_3)
        Objects - 1
                Object[0] - VK_OBJECT_TYPE_INSTANCE, Handle 2337217660128
     at: _debug_messenger_callback (drivers/vulkan/vulkan_context.cpp:259)
WARNING: GENERAL - Message Id Number: 0 | Message Id Name: Loader Message
        Layer name GalaxyOverlayVkLayer_DEBUG does not conform tOor pnhaamni nSgt rsitnagnNdaamred:  (SPcoelniecMyu lt#iLpLlPa_LyAeYrE
R_3S)t
ri      nOgbNjaemcet:s  1-  u1n
        c       lOabijmeecdt [s0t]ri n-g  VnKa_mOeBsJ EaCtT _eTxYiPtE._
INSTANCE, Handle 2337217660128
     at: _debug_messenger_callback (drivers/vulkan/vulkan_context.cpp:259)
ERROR: Condition "err" is true. Returning: ERR_CANT_CREATE
   at: _create_physical_device (drivers/vulkan/vulkan_context.cpp:1094)
ERROR: Condition "err != OK" is true. Returning: ERR_CANT_CREATE
   at: _window_create (drivers/vulkan/vulkan_context.cpp:1624)
ERROR: Failed to create Vulkan Window.
   at: (platform/windows/display_server_windows.cpp:3749)
ERROR: Failed to create main window.
   at: (platform/windows/display_server_windows.cpp:4066)
ERROR: Unexpected window message 0x1f received for window we cannot recognize in our collection; sequence error.
   at: _handle_early_window_message (platform/windows/display_server_windows.cpp:2422)
ERROR: Unable to create DisplayServer, all display drivers failed.
   at: setup2 (main/main.cpp:1945)
ERROR: Pages in use exist at exit in PagedAllocator: N7Variant5Pools11BucketLargeE
   at: ~PagedAllocator (./core/templates/paged_allocator.h:140)

**Comment by TheMultii** [comment] 2023-01-13 19:34
Bug also occurs in beta 12 for RTX 3060 Ti.

**Comment by clayjohn** [comment] 2023-01-13 19:54
@BastiaanOlij  It looks like the initial call to ``vkEnumeratePhysicalDevices`` (the one to ascertain GPU count) is failing.

I wonder if this is a false positive from our error checking as ``vkEnumeratePhysicalDevices`` can return ``VK_INCOMPLETE`` on success. Although that is only supposed to happen when ``pPhysicalDevices`` is not ``NULL`` as far as I can tell.

From the [spec](https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/vkEnumeratePhysicalDevices.html)
> If pPhysicalDeviceCount is less than the number of physical devices available, at most pPhysicalDeviceCount structures will be written, and VK_INCOMPLETE will be returned instead of VK_SUCCESS, to indicate that not all the available physical devices were returned.

**Comment by clayjohn** [comment] 2023-01-14 01:05
Also, this may be a duplicate of https://github.com/godotengine/godot/issues/64584

**Comment by BastiaanOlij** [comment] 2023-01-14 07:05
@clayjohn doesn't it check the count it needs first?

This:
```
Layer name GalaxyOverlayVkLayer_DEBUG does not conform tOor pnhaamni nSgt rsitnagnNdaamred: (SPcoelniecMyu lt#iLpLlPa_LyAeYrE
R_3S)t
ri nOgbNjaemcet:s 1- u1n
c lOabijmeecdt [s0t]ri n-g VnKa_mOeBsJ EaCtT eTxYiPtE.
```
definately looks like we're overwriting memory we shouldn't be...

This one is pretty weird...

**Comment by clayjohn** [comment] 2023-01-14 07:52
> @clayjohn doesn't it check the count it needs first?

We call ``vkEnumeratePhysicalDevices`` multiple times. The first time it is called just to get the GPU count, but that appears to be the call that is failing. 

> This:
> 
> ```
> Layer name GalaxyOverlayVkLayer_DEBUG does not conform tOor pnhaamni nSgt rsitnagnNdaamred: (SPcoelniecMyu lt#iLpLlPa_LyAeYrE
> R_3S)t
> ri nOgbNjaemcet:s 1- u1n
> c lOabijmeecdt [s0t]ri n-g VnKa_mOeBsJ EaCtT eTxYiPtE.
> ```
> 
> definately looks like we're overwriting memory we shouldn't be...
> 
> This one is pretty weird...

This is what happens when errors are printed from multiple threads simultaneously. I'm not sure it indicates a memory issue

**Comment by BastiaanOlij** [comment] 2023-01-14 11:33
> We call vkEnumeratePhysicalDevices multiple times. The first time it is called just to get the GPU count, but that appears to be the call that is failing.

That is really strange because this is the proper way of handling all enumerations in Vulkan (and most Khronos APIs) and this has been unchanged for some time now.

> This is what happens when errors are printed from multiple threads simultaneously. I'm not sure it indicates a memory issue

Have we started any threads this early on?

**Comment by akien-mga** [comment] 2023-01-14 13:11
@BastiaanOlij From what Clay described above, the problem is that we fail if the result is `VK_INCOMPLETE`, while that's a success scenario too. It can mean the system has 3 physical devices, but only one of them works and is available to us (so we should use that one instead of failing).

It's just the err check which is wrong:
https://github.com/godotengine/godot/blob/1d14c054a12dacdc193b589e4afb0ef319ee2aae/drivers/vulkan/vulkan_context.cpp#L10931094

**Comment by BastiaanOlij** [comment] 2023-01-14 14:40
I doubt that is the problem also seeing this previously worked. Note that VK_INCOMPLETE is only returned when you call `vkEnumeratePhysicalDevices` with the 3rd parameter set, so the second time we call it when we're actually retrieving the device information.

See: https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/vkEnumeratePhysicalDevices.html
```
If pPhysicalDevices is NULL, then the number of physical devices available is returned in pPhysicalDeviceCount. Otherwise, pPhysicalDeviceCount must point to a variable set by the user to the number of elements in the pPhysicalDevices array, and on return the variable is overwritten with the number of handles actually written to pPhysicalDevices. If pPhysicalDeviceCount is less than the number of physical devices available, at most pPhysicalDeviceCount structures will be written, and VK_INCOMPLETE will be returned instead of VK_SUCCESS, to indicate that not all the available physical devices were returned.
```

Specifically that last line.

Seeing the weird errors around the `GalaxyOverlayVkLayer` layers, I wonder if incompatible layers were installed on this device. I don't believe we even instruct Vulkan to include those so this would have been configured externally.

**Comment by BastiaanOlij** [comment] 2023-01-15 05:30
Ok, wrote this on the other PR as well. I just ran into the same error and suddenly realized what is likely going on here.

When you enable OpenXR, Godot will attempt to start OpenXR. The problem here is that when you use a runtime like SteamVR, SteamVR will actually exit if no headset is found.

As under OpenXR, OpenXR is responsible for starting Vulkan, and OpenXR is now in an undefined state, things start to go wrong.

I'll improve the checking around OpenXR.

**Closed** 2023-01-19 09:19 UTC
Labels: bug, topic:rendering, topic:xr, regression
