### ISSUE TITLE
FileAccess `store_var()` and `get_var()` convert a typed array to an untyped array

### ISSUE THREAD

**Issue by charliewhitfield** [godotengine/godot#84749] opened 2023-11-11 12:02 UTC
### Godot version

4.2.beta5 and earlier 4.x

### System information

Windows 11

### Issue description

I have class members that I cache to file using FileAccess `store_var()` and `get_var()`. If the class member is a typed array, I get error 'Trying to assign an array of type "Array" to a variable of type "Array[xxx]"' when attempting to set the typed class member. In short, the array type is lost during the file store and get.

### Steps to reproduce

```
func _ready() -> void:
	var array: Array = [1, 2, 3]
	array = Array(array, TYPE_INT, &"", null)
	
	prints(array, array.is_typed()) # prints "[1, 2, 3] true"
	
	var file := FileAccess.open("user://file", FileAccess.WRITE)
	file.store_var(array)
	file.close()
	file = FileAccess.open("user://file", FileAccess.READ)
	var file_array: Array = file.get_var()
	
	prints(file_array, file_array.is_typed()) # prints "[1, 2, 3] false"

	var a: Array[int] = array
	var b: Array[int] = file_array # Error: 'Trying to assign an array of type "Array" to a variable of type "Array[int]"'.
```

### Minimal reproduction project

[test.zip](https://github.com/godotengine/godot/files/13325385/test.zip)

**Comment by dalexeev** [comment] 2023-11-11 12:09
* Duplicate of #76841 (`FileAccess` uses the same mechanism internally).
* May be fixed by #78219.

Thanks for reporting the bug nonetheless!

**Closed by dalexeev** 2023-11-11 12:09 UTC
