### ISSUE TITLE
Error when using navigation layer on a Tilemap

### ISSUE THREAD

**Issue by GregX999** [godotengine/godot#74518] opened 2023-03-06 22:14 UTC
### Godot version

4.0

### System information

Windows 11

### Issue description

I have project using a Tilemap, a Tileset with a Navigation Layer, and a Character2D with a NavigationAgent.

When I run the game, everything appears to work. The Character2D is pathfinding around, staying in the area defined in the Tilemap - as expected.

But in the debugger, I get this error:
```
E 0:00:00:0609   sync: Attempted to merge a navigation mesh triangle edge with another already-merged edge. This happens when the current `cell_size` is different from the one used to generate the navigation mesh. This will cause navigation problems.
  <C++ Source>   modules/navigation/nav_map.cpp:691 @ sync()
```

### Steps to reproduce

I created a Tilemap node and a Tileset.

The Tileset is divided into multiple tiles. I gave the Tileset a single Navigation Layer.
I created a polygon on ONE tile in the Navigation Layer of the Tileset - covering the entire tile. (I'll call this the "Nav Tile")

The Tilemap has three layers (Ground, Props, Nav).
I painted the Ground and Props layers with tiles that do not have any polygons in the Navigation Layer.
In the Nav layer, I painted an area of the map with the Nav Tile.

I created a Character2D with a NavAgent2d child node.
It uses a script very similar to that found here:
```https://docs.godotengine.org/en/stable/tutorials/navigation/navigation_introduction_2d.html```

### Minimal reproduction project

[TileMapsAndNav.zip](https://github.com/godotengine/godot/files/10903375/TileMapsAndNav.zip)

Move player with WASD keys. The emoji contains the NavigationAgent and will chase the player. (Ignore the pink blob.)

**Comment by smix8** [comment] 2023-03-06 22:52
This error is caused by navigation polygon edge overlap or duplicated vertices, the NavigationServer can not merge the navigation polygons. If you have different navigation polygons all stacked in the same TileMap cell you need to make sure that they are placed on different TileMap navigation layer layers.

**Comment by GregX999** [comment] 2023-03-06 23:05
I don't see how there could be any overlaps in my Tileset or Tilemap. Only one cell (tile) in my Tileset has a polygon defined in the (single) Navigation layer, the "default polygon", which covers the entire cell and has four vertices. And I only have a single layer in my Tilemap that contains these tiles (and only these tiles).

Let me know if I'm misunderstanding something - it's very possible.

**Comment by smix8** [comment] 2023-03-06 23:24
The TileMap has water and grass tiles in the same place and both have a navigation polygon.

**Comment by GregX999** [comment] 2023-03-06 23:58
Oh! I didn't know about that "Force Show" option - very handy. As well as changing the color from blue to red.

I'm not sure where I went wrong - I originally had nav polygons on multiple tiles, but decided to go with a single nav tile, and a single nav layer on the tilemap, and so removed the nav polygons from all the other tiles. But in the tilemap, some still had the polygons?

Well, at least now I know how to better find those issues.

Sorry for the "false alarm". ^_^

**Comment by smix8** [comment] 2023-03-07 11:00
No problem. If you have no future questions you can just close the issue.

**Closed** 2023-03-07 14:29 UTC
