### ISSUE TITLE
Undeclared identifier  'INFINITY' in animation_tree_player.cpp

### ISSUE THREAD

**Issue by Richard74Huang** [godotengine/godot#4567] opened 2016-05-06 08:02 UTC
**Operating system or device:**
Windows 7 pro 

**Issue description** (what happened, and what was expected):
Building error:
While compile godot for windows under windows 7 & VC 2010, it report:

_animation_tree_player.cpp
scene\animation\animation_tree_player.cpp(657) : error C2065: 'INFINITY' : undeclared identifier_

**Steps to reproduce:**

scons p=windows

**Link to minimal example project** (optional but very welcome):

**Comment by Richard74Huang** [comment] 2016-05-06 08:11
I found an [article](https://github.com/godotengine/godot/issues/4342) . It seems that VS 2010 was dropped from support list.

**Comment by kubecz3k** [comment] 2016-05-07 07:58
I'm archiving this issue since in it's roots it seems to be duplicate of https://github.com/godotengine/godot/issues/4342

**Closed by kubecz3k** 2016-05-07 07:58 UTC
Labels: archived, bug, topic:buildsystem
