### ISSUE TITLE
Class doc index doesn't go away when alone and closed

### ISSUE THREAD

**Issue by YeldhamDev** [godotengine/godot#12011] opened 2017-10-10 23:29 UTC
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
[Build](https://bintray.com/calinou/godot/editor) 3453bf5

**Issue description:**
When a class documentation is alone and closed, its index remains:
![screenshot at 2017-10-10 20-27-42](https://user-images.githubusercontent.com/30739239/31415395-aa87ef3e-adf9-11e7-90cf-3d4aac6311af.png)

**Comment by Zylann** [comment] 2017-10-11 09:13
Similar to #10407

**Comment by J08nY** [comment] 2017-10-11 17:34
This might actually be fixed in current master already, at least I couldn't reproduce it. Do you have some special steps?

**Comment by YeldhamDev** [comment] 2017-10-11 17:38
@J08nY I am using the latest build from [calinou](https://bintray.com/calinou/godot/editor), and the only thing you have to do is to close a lone doc, or close all.

**Comment by J08nY** [comment] 2017-10-11 17:46
Right, okay, reproduced that. Will look at a fix later.

**Closed** 2017-10-14 19:15 UTC
Labels: bug, confirmed, topic:editor
