### ISSUE TITLE
Scripts removed from nodes upon loading godot, seemingly randomly

### ISSUE THREAD

**Issue by FireCatMagic** [godotengine/godot#75039] opened 2023-03-17 19:47 UTC
### Godot version

4.0 stable

### System information

Windows 7 64-bit

### Issue description

Scripts attached to nodes seemingly randomly are no longer attached to nodes upon loading of Godot. This is found out when attempting to start the game and errors occur, and then checking out the scene where it came from. 
My friend also had this same issue.

### Steps to reproduce

Create a scene with a node and attatch a script
Close godot
Reopen godot
Sometimes the script is no longer attatched

### Minimal reproduction project

N/A

**Comment by Calinou** [comment] 2023-03-17 21:17
I've has this issue with the `bullet.gd` script in https://github.com/godotengine/godot-demo-projects/pull/849, but could never find a way to trigger this 100% of the time.

**Comment by Ezcha** [comment] 2023-03-18 00:01
I keep having this issue as well, unsure of how to reproduce it.

**Comment by Gerporgl** [comment] 2023-03-21 16:22
I have the same issue!

And you know what is interesting, it is only my scene called bullet.tscn with the script called bullet.gd
I've got other very similar scene with similar structure and never had that problem with those.

It is kind of annoying, since upon loading hte project, if I run I get an error, to realizze teh script association is gone again. I then have to reselect it in the editor (as it is empty)

For me, it seems to be doing that only on one of my 2 computers I use to edit the project and not always... (but it is very frequent, almost all the time I would say) that computer has a 5120 x 1440 monitor (super wide dual 1440P width), so I don't know if that could be related. My other one has 1920x1080 monitor.

The specs of both computers are very similar (Ryzen 3900x and 5950x CPU, AMD RX 6xxx gpus, etc.). The OS is the same, I am on Linux Pop!_OS 22.04

**Comment by FireCatMagic** [comment] 2023-04-21 03:07
An update - Sometimes this happens with instances. Only the root node is kept, and the script remains, but all children and the instance itself are removed.

**Comment by difof** [comment] 2023-04-30 13:49
Same issue here, only happens with tool scripts. I cannot 100% reproduce it because it's ok on some scenes. Very strange! And I notice it when the node lose focus in scene tree. Sometimes the editor puts the script as a built-in script which is annoying because I edit code and see no changes until I figure out this happened.

**Comment by adamscott** [comment] 2023-04-30 14:06
> Same issue here, only happens with tool scripts.

Thanks for the precision. It will help debugging.

**Comment by FireCatMagic** [comment] 2023-04-30 23:42
I do not use any tool scripts in my project and this still happens to me. My project is heavy in custom classes, though.

**Comment by Calinou** [comment] 2023-04-30 23:52
> I do not use any tool scripts in my project and this still happens to me. My project is heavy in custom classes, though.

https://github.com/godotengine/godot-demo-projects/pull/849 doesn't use any `@tool` scripts either.

**Comment by Calinou** [comment] 2023-05-01 21:30
Closing in favor of https://github.com/godotengine/godot/issues/76641, which has precise reproduction steps.

**Closed by Calinou** 2023-05-01 21:30 UTC
Labels: bug, topic:editor, needs testing
