### ISSUE TITLE
Shortcut Play (command + B) doesn't work when cursor is on code editor

### ISSUE THREAD

**Issue by stephannv** [godotengine/godot#57453] opened 2022-01-30 17:12 UTC
### Godot version

v4.0.alpha1.official.31a7ddbf8

### System information

macOS Monterey 12.1, Intel i9, Radeon Pro 560x 4GB

### Issue description

If cursor is on code editor, the shortcut "Play" (command+B) doesn't work. 

Useful info:
- The shortcut "Play Scene" (command+R) works fine.
- I mapped another key combination to command "Play" (eg. command+shift+9) and worked fine
- If code is on screen, but the mouse focus is on another pane (eg. file explorer, debugger, inspector, open scripts list, methods list), the shortcut (command+B) works.

### Steps to reproduce

- Create a godot project
- Create a scene
- Attach script to created scene
- Click inside code pane
- Try to use "command + B" shortcut

**Comment by Paulb23** [comment] 2022-01-30 18:03
Duplicate of #56961

**Closed by Paulb23** 2022-01-30 18:03 UTC

**Comment by stephannv** [comment] 2022-01-30 18:07
Sorry for the duplicated issue. I search for "command + b" and "play shortcut" and didn't find the other issue. 
Thanks.
