### ISSUE TITLE
when enable force software skinning, the shadow will become static

### ISSUE THREAD

**Issue by snougo** [godotengine/godot#53018] opened 2021-09-24 16:21 UTC
### Godot version

3.4 beta5

### System information

macOS 10.14.6 intelGPU GLES3 and GLES2

### Issue description

when enable force software skinning, the shadow will not update and become like static shadow, both GLES3 and GLES2, not sure is it only happen on macOS or not

**in Editor**

https://user-images.githubusercontent.com/64188282/134706250-352c5501-2266-440f-bd88-3ce6fbfd3d34.mov

**in Runtime**

https://user-images.githubusercontent.com/64188282/134706738-7f8c1cbc-d0a9-480e-a721-03e935f3f1d5.mov

**also see this**

https://user-images.githubusercontent.com/64188282/134708186-3dc2b701-7815-4e66-ab2e-afa059ada08f.mov

### Steps to reproduce

see Minimal reproduction project

### Minimal reproduction project

[TPS.zip](https://github.com/godotengine/godot/files/7227127/TPS.zip)

**Comment by snougo** [comment] 2021-09-24 16:24
both in Editor and Runtime

**Comment by Calinou** [comment] 2021-09-24 16:37
@snougo Can you reproduce this in 3.3.3?

**Comment by snougo** [comment] 2021-09-24 16:46
> @snougo Can you reproduce this in 3.3.3?

yes

**Comment by lawnjelly** [comment] 2021-09-25 06:12
At a guess it could be trying to use hardware skinning for the shadow (along with software for the main pass) and the bones aren't set. I wonder why we haven't seen this before... @pouleyKetchoupp

**Comment by pouleyKetchoupp** [comment] 2021-09-27 18:07
It looks like shadows are just not updated because the mesh needs to be marked for update on the render side. It's done in the standard skeleton update but not in software skinning.

I'll open a PR soon.

**Comment by akien-mga** [comment] 2021-09-28 05:31
Fixed by #53144.

**Closed by akien-mga** 2021-09-28 05:31 UTC
Labels: bug, topic:rendering, confirmed, topic:3d
