### ISSUE TITLE
Draw results are not displayed in "Remote" window.

### ISSUE THREAD

**Issue by AlexanderFarkas** [godotengine/godot#89561] opened 2024-03-16 10:05 UTC
### Tested versions

- Reproducible in 4.2.1 and 3.5.3

### System information

Godot v4.2.1.stable - macOS 14.0.0 - Vulkan (Mobile) - integrated Apple M1 Pro - Apple M1 Pro (10 Threads)

### Issue description

I expect `_draw` function results to be displayed on the "Remote" tab when game is running.
Now it's displayed in actual game window, but not in the "Remote" tab.

### Steps to reproduce

1. Create Node2D
2. Attach this script to it
```gdscript
extends Node2D


# Called when the node enters the scene tree for the first time.
func _ready():
	pass
	

func _draw():
	draw_polygon([
		Vector2(0, 100),
		Vector2(100, 0),
		Vector2(0, -100),
		Vector2(-100, 0),
	], [Color.AQUA])


# Called every frame. 'delta' is the elapsed time since the previous frame.
func _process(delta):
	pass
```
3. Run the scene and tap "Remote"

### Minimal reproduction project (MRP)

[Archive.zip](https://github.com/godotengine/godot/files/14623162/Archive.zip)

**Comment by AThousandShips** [comment] 2024-03-16 14:15
Displayed how? The remote window shows nodes, not rendering?

**Comment by AlexanderFarkas** [comment] 2024-03-16 14:21
I expected it to work the same way as in Unity, but some person in the Discord channel explained to me that only nodes are rendered, while drawing is done by the engine on a low level. 

Still wasn't sure if it's a bug or not.

**Comment by AThousandShips** [comment] 2024-03-16 14:26
Rendered how? Are you talking about the "Remote" tab in the scene tab? That's not rendered at all? It's just a list of nodes?

Can you show a screenshot because I don't know what you're talking about when you say "rendered in the remote tab"

**Comment by AlexanderFarkas** [comment] 2024-03-16 14:32
<img width="829" alt="Screenshot 2024-03-16 at 17 31 26" src="https://github.com/godotengine/godot/assets/35890159/45c3e678-9046-46cd-9696-b580111308c4">
In the game square figure is drawn, while in the Remote Preview it's not.

**Comment by AThousandShips** [comment] 2024-03-16 14:35
Nothing is drawn there, it's just the hierarchy, just the same as "local", it's not rendering things it just shows the nodes in the scene :)

**Comment by AlexanderFarkas** [comment] 2024-03-16 14:40
Yeah, I mean the grid behind the window. Thank you.

**Comment by AThousandShips** [comment] 2024-03-16 14:41
That's not something the editor does :)

Closing as this is not a bug

In the future I'd suggest asking these kinds of questions on the [forums](https://forum.godotengine.org/), if you're unsure if it's a bug or not, please ask there first :)

**Closed by AThousandShips** 2024-03-16 14:41 UTC
Labels: topic:editor, needs testing
