### ISSUE TITLE
"ambient_light_disabled" render mode in custom shader still gets ambient light contribution 

### ISSUE THREAD

**Issue by robojeb** [godotengine/godot#66726] opened 2022-10-01 20:26 UTC
### Godot version

4.0.dev (e69b7083d)

### System information

Manjaro Linux, NVidia 1080ti (nvidia drivers)

### Issue description

When writing a custom ShaderMaterial and setting `render_mode ambient_light_disabled` still gets contribution from the Ambient light source. 
For example I set the `DIFFUSE_LIGHT` output of my light function to `vec3(0.0)` which I would expect to render entirely black, but there is still contribution from the ambient light. 

This is most easily seen with the default Sky based world environment because there are differences in the ambient light based on direction. 

It seems like there is room for a feature request here as well. 
That when `render_mode ambient_light_disabled` is set, Godot disables automatic ambient light contribution and instead adds a pass (eg `if (AMBIENT_LIGHT_PASS)`) like how sky shaders have multiple passes. 
This would allow more flexibility on the shading. 

### Steps to reproduce

1. Open a new scene and insert a simple mesh like a Cube. 
2. Insert the sample world environment
3. Create a new shader material for the cube with the following code: 

```
shader_type spatial;
render_mode ambient_light_disabled;

void fragment() {
    ALBEDO = vec3(1.0);
}

void light() {
    DIFFUSE_LIGHT = vec3(0.0);
}
```

You will see that the mesh is still lit and has variations from the skybox radiance map. 

4. Modify the world environment and set "Ambient Light" to "Color" with a black color. 
This is what I would expect to see with no Ambient light contribution to the shader.

**Comment by Calinou** [comment] 2022-10-01 22:14
Duplicate of https://github.com/godotengine/godot/issues/56332 (same cause).

**Closed by Calinou** 2022-10-01 22:14 UTC
