### ISSUE TITLE
C# RpcId randomly crashing with no error

### ISSUE THREAD

**Issue by Kody06** [godotengine/godot#67966] opened 2022-10-28 02:21 UTC
### Godot version

4.0 Beta 3

### System information

Windows 10

### Issue description

I'm calling a RpcId at Server.cs Line 219 60 times a second and it randomly crashes with no error after 3-10 seconds.

### Steps to reproduce

Start Server
Start Client
Press Connect To Server Button
Press Spawn Button
Wait 3-10 Seconds

### Minimal reproduction project

https://github.com/Kody06/MovementStuff

**Comment by zCubed3** [comment] 2022-10-28 03:19
I downloaded the project and am experiencing the same crashes, the exit code is 3221226356 (0xC0000374). Meaning RpcId or some other code within this project is causing heap corruption

**Comment by zCubed3** [comment] 2022-10-28 03:52
I was not able to replicate this issue on Linux, I left the server to run in the background with the client in the foreground for about 1 minute and there was no crash, could this be limited to just windows? (If it matters, I am using Arch Linux with the latest packages installed, on kernel version 6.0.2-arch1-1)

**Comment by ozqf** [comment] 2022-12-01 12:40
I am unable to reproduce it reliably at the moment but I wanted to add I too are getting crash events with code 0xc0000374. Godot 4 beta 6 C#. I am not doing anything related to networking, it just happens as you play. Attempting to narrow it down.

**Comment by RedworkDE** [comment] 2023-03-27 15:43
Does this issue still exist with a 4.0-stable release? This issue sounds like a duplicate of a whole bunch of other issues that got fixed by https://github.com/godotengine/godot/pull/69194.

**Closed** 2023-03-27 17:42 UTC
Labels: bug, platform:windows, topic:network, topic:dotnet
