### ISSUE TITLE
[3.4.2 Web Editor] Scrolling with touchpad is unusable

### ISSUE THREAD

**Issue by ator-dev** [godotengine/godot#57428] opened 2022-01-30 00:35 UTC
### Godot version

3.4.2.stable

### System information

Chromium PWA on Ubuntu 21.10; Chrome PWA on Chrome OS

### Issue description

On most platforms, scrolling using the touchpad (3.x and 4.0) is perfectly acceptable if imperfect. However, the Godot Web Editor seems to handle scroll events poorly, making it almost impossible to use when (for example) scrolling in the offline docs. Scrolling is very fast and jittery, and can't even be slowed manually to a sensible speed (see #56317).

I find myself always moving the cursor to the scrollbar and trying to make small scroll adjustments there, which is made even harder when looking at a long page in the docs. Obviously the up/down arrow keys can be used in the documentation - though even then the increments are overly small - but in places like the Inspector/SceneTree/FileSystem (where the issue is just as bad) this doesn't work. The result is a very cumbersome editing and coding experience and makes Godot seem poorly designed/unattractive for people new to it.

Enhancements to this feature (and possibly arrow key scrolling as well) are greatly needed in my opinion.

### Steps to reproduce

Open any project in the [Web Editor](https://editor.godotengine.org), press F1 (or go to the 'Script' view then click 'Search Help'), open the first option '@GDScript' or similar, and try to scroll through the page.

_Note: On large screens it's just about possible to make out where you are (e.g. being at a particular method description and wishing to move to the next method) in order to control scrolling; but on small screens such as Chromebooks, it feels more like you're teleporting between random items that flash on the screen for a split second._

You can try to customise scrolling using the only relevant setting, `text_editor/navigation/v_scroll_speed`. This only seems to specifically affect scripts, however.

**Comment by Calinou** [comment] 2022-01-30 00:56
Related to https://github.com/godotengine/godot/issues/13139 (possible duplicate?).

**Comment by ator-dev** [comment] 2022-01-30 10:58
Probably a duplicate of #49873 linked from #13139 (which I didn't notice earlier, sorry) - should this be closed?

**Comment by Calinou** [comment] 2022-01-30 18:22
Duplicate of https://github.com/godotengine/godot/issues/49873.

**Closed by Calinou** 2022-01-30 18:22 UTC
Labels: bug, platform:html5, topic:editor, usability, topic:input
