### ISSUE TITLE
Godot Editor Does Not Remember Position/Size Between Sessions

### ISSUE THREAD

**Issue by SilverSurfer1221** [godotengine/godot#19350] opened 2018-06-03 22:00 UTC
**Godot version:**
v3.02

**OS/device including version:**
Windows 10 

**Issue description:**
If I move the Godot editor to a second monitor, shut down and restart, then Godot still opens on the first monitor. The Godot editor also always opens in full-screen mode. If I change it to windowed mode and shut the editor down, the next time I open it, it is back to full-screen mode.

**Steps to reproduce:**
- Start the Godot editor on Windows 10. It opens in full-screen mode.
- Resize to windowed mode and shut down.
- Restart Godot and the editor opens full-screen again.
- Resize again and move to a second monitor, then close.
- Open Godot again and it is, once again, open to full-screen on the first monitor.

**Comment by vnen** [comment] 2018-06-03 22:37
Duplicate of #5114

**Closed by vnen** 2018-06-03 22:37 UTC

**Comment by SilverSurfer1221** [comment] 2018-06-04 00:54
Hello,

You still consider it a duplicate if it was for v2 of Godot? I am 
reporting about v3.02?

Just asking.

Thanks,

Dan

------ Original Message ------

**Comment by vnen** [comment] 2018-06-04 01:51
Yes, it's still a duplicate. If anyone is up to implement, they'll do it in the latest version.
