### ISSUE TITLE
An after-image can be seen when switching to a new scene

### ISSUE THREAD

**Issue by malhotraprateek** [godotengine/godot#68081] opened 2022-10-31 13:49 UTC
### Godot version

v4.0.beta3.official [01ae26d31]

### System information

Windows 10, Nvidia GTX 1080 Ti

### Issue description

An after-image of the previous scene can be seen when we switch scene tabs.

I could not find an issue raised for this and while this is not a major issue considering that zooming in\out or changing the editor view in some way erodes the after-image, I thought I would raise it anyway.

Also, could not reproduce it with beta 2.

### Steps to reproduce

1. Add a mesh instance (any mesh will do)
2. Switch to a new scene

### Minimal reproduction project

![1](https://user-images.githubusercontent.com/10957697/199023001-844b434c-512f-4cb4-b871-623d2ca4559d.PNG)
![2](https://user-images.githubusercontent.com/10957697/199023074-cbfca2d4-50ff-46c1-848f-3044525fce0d.PNG)

**Comment by Lielay9** [comment] 2022-10-31 15:09
I assume TAA is enabled? With it, I can also see ghosting when changing scenes.

**Comment by malhotraprateek** [comment] 2022-10-31 19:23
Yes TAA was enabled! I was checking anti-aliasing and I guess I forgot to disable it.

**Comment by Calinou** [comment] 2022-10-31 20:51
Closing as duplicate of https://github.com/godotengine/godot/issues/62887 then.

**Closed by Calinou** 2022-10-31 20:51 UTC
Labels: bug, topic:rendering, topic:editor, needs testing, regression, topic:3d
