### ISSUE TITLE
Using 'as' keyword does nothing when attempting to cast typed arrays

### ISSUE THREAD

**Issue by moil23** [godotengine/godot#75004] opened 2023-03-16 21:38 UTC
### Godot version

Godot 4

### System information

Windows 10 

### Issue description

Don't think this is a duplicate - sorry if it's already been discussed.

Cannot cast from one typed array to another using the as keyword (this used to work in older G4 betas)

As it stands there is no way of converting typed arrays to another.

This is particularly relevant when attempting to use functional tools such as map, filter etc. on typed arrays and retain strong typing.

Several workarounds exists e.g. for loops and appending where conditions are met, but it would be nice to be able to cast arrays in some way, though maybe the as keyword is not the best way as it would not be clear what happens to elements that are not of the arrays type.

### Steps to reproduce

extends Node

@onready var sprites := get_children().filter(func(node): return node is Sprite2D) as Array[Sprite2D]

Attach this script and running a scene with it will get the error "Trying to assign an array of type "Array[Node]" to a variable of type "Array[Sprite2D]"."

### Minimal reproduction project

N/A

**Comment by AThousandShips** [comment] 2023-03-16 21:41
Duplicate of #72627

**Comment by Calinou** [comment] 2023-03-16 23:13
- Duplicate of https://github.com/godotengine/godot/issues/72627.

**Closed by Calinou** 2023-03-16 23:13 UTC
