### ISSUE TITLE
Scene re-import crashes

### ISSUE THREAD

**Issue by dpalais** [godotengine/godot#69625] opened 2022-12-05 21:11 UTC
### Godot version

4.0-git (1e3919c409)

### System information

Fedora 36

### Issue description

Working on a project for a long time with Godot 4, I have some imported scenes from some time ago. As I attempted to reimport some scene due to changing some import setting, the editor fails to show the advanced import settings window and crashes instead.

```
ERROR: FATAL: Condition "!exists" is true.
   at: operator[] (./core/templates/hash_map.h:504)

================================================================
handle_crash: Program crashed with signal 4
Engine version: Godot Engine v4.0.beta.mono.custom_build (3340fc2e13eee8d8ef009351b3d441fd1a2a66d5)
Dumping the backtrace. Please include this when reporting the bug to the project developer.
[1] /usr/lib64/dotnet/shared/Microsoft.NETCore.App/6.0.11/libcoreclr.so(+0x4d6c62) [0x7f6be0d7ec62] (??:0)
[2] /lib64/libc.so.6(+0x3ea30) [0x7f6bf8412a30] (??:0)
[3] HashMap<StringName, Variant, HashMapHasherDefault, HashMapComparatorDefault<StringName>, DefaultTypedAllocator<HashMapElement<StringName, Variant> > >::operator[](StringName const&) const (/var/home/user/Projects/Godot/./core/templates/hash_map.h:504 (discriminator 1))
[4] EditorSceneFormatImporterGLTF::import_scene(String const&, unsigned int, HashMap<StringName, Variant, HashMapHasherDefault, HashMapComparatorDefault<StringName>, DefaultTypedAllocator<HashMapElement<StringName, Variant> > > const&, List<String, DefaultAllocator>*, Error*) (/var/home/user/Projects/Godot/modules/gltf/editor/editor_scene_importer_gltf.cpp:66 (discriminator 2))
[5] ResourceImporterScene::pre_import(String const&, HashMap<StringName, Variant, HashMapHasherDefault, HashMapComparatorDefault<StringName>, DefaultTypedAllocator<HashMapElement<StringName, Variant> > > const&) (/var/home/user/Projects/Godot/editor/import/resource_importer_scene.cpp:2305)
[6] SceneImportSettings::open_settings(String const&, bool) (/var/home/user/Projects/Godot/editor/import/scene_import_settings.cpp:592)
[7] ResourceImporterScene::show_advanced_options(String const&) (/var/home/user/Projects/Godot/editor/import/resource_importer_scene.cpp:2601)
[8] FileSystemDock::_select_file(String const&, bool) (/var/home/user/Projects/Godot/editor/filesystem_dock.cpp:1010)
[9] FileSystemDock::_tree_activate_file() (/var/home/user/Projects/Godot/editor/filesystem_dock.cpp:1071 (discriminator 12))
[10] void call_with_variant_args_helper<FileSystemDock>(FileSystemDock*, void (FileSystemDock::*)(), Variant const**, Callable::CallError&, IndexSequence<>) (/var/home/user/Projects/Godot/./core/variant/binder_common.h:267 (discriminator 4))
[11] void call_with_variant_args<FileSystemDock>(FileSystemDock*, void (FileSystemDock::*)(), Variant const**, int, Callable::CallError&) (/var/home/user/Projects/Godot/./core/variant/binder_common.h:377)
[12] CallableCustomMethodPointer<FileSystemDock>::call(Variant const**, int, Variant&, Callable::CallError&) const (/var/home/user/Projects/Godot/./core/object/callable_method_pointer.h:105)
[13] Callable::callp(Variant const**, int, Variant&, Callable::CallError&) const (/var/home/user/Projects/Godot/core/variant/callable.cpp:64)
[14] Object::emit_signalp(StringName const&, Variant const**, int) (/var/home/user/Projects/Godot/core/object/object.cpp:1047)
[15] Error Object::emit_signal<>(StringName const&) (/var/home/user/Projects/Godot/./core/object/object.h:869)
[16] Tree::gui_input(Ref<InputEvent> const&) (/var/home/user/Projects/Godot/scene/gui/tree.cpp:3689 (discriminator 4))
[17] Control::_call_gui_input(Ref<InputEvent> const&) (/var/home/user/Projects/Godot/scene/gui/control.cpp:1714)
[18] Viewport::_gui_call_input(Control*, Ref<InputEvent> const&) (/var/home/user/Projects/Godot/scene/main/viewport.cpp:1329)
[19] Viewport::_gui_input_event(Ref<InputEvent>) (/var/home/user/Projects/Godot/scene/main/viewport.cpp:1559 (discriminator 2))
[20] Viewport::push_input(Ref<InputEvent> const&, bool) (/var/home/user/Projects/Godot/scene/main/viewport.cpp:2796 (discriminator 4))
[21] Window::_window_input(Ref<InputEvent> const&) (/var/home/user/Projects/Godot/scene/main/window.cpp:1090 (discriminator 4))
[22] void call_with_variant_args_helper<Window, Ref<InputEvent> const&, 0ul>(Window*, void (Window::*)(Ref<InputEvent> const&), Variant const**, Callable::CallError&, IndexSequence<0ul>) (/var/home/user/Projects/Godot/./core/variant/binder_common.h:262 (discriminator 8))
[23] void call_with_variant_args<Window, Ref<InputEvent> const&>(Window*, void (Window::*)(Ref<InputEvent> const&), Variant const**, int, Callable::CallError&) (/var/home/user/Projects/Godot/./core/variant/binder_common.h:377)
[24] CallableCustomMethodPointer<Window, Ref<InputEvent> const&>::call(Variant const**, int, Variant&, Callable::CallError&) const (/var/home/user/Projects/Godot/./core/object/callable_method_pointer.h:105)
[25] Callable::callp(Variant const**, int, Variant&, Callable::CallError&) const (/var/home/user/Projects/Godot/core/variant/callable.cpp:64)
[26] DisplayServerX11::_dispatch_input_event(Ref<InputEvent> const&) (/var/home/user/Projects/Godot/platform/linuxbsd/x11/display_server_x11.cpp:3248)
[27] DisplayServerX11::_dispatch_input_events(Ref<InputEvent> const&) (/var/home/user/Projects/Godot/platform/linuxbsd/x11/display_server_x11.cpp:3218)
[28] Input::_parse_input_event_impl(Ref<InputEvent> const&, bool) (/var/home/user/Projects/Godot/core/input/input.cpp:665)
[29] Input::flush_buffered_events() (/var/home/user/Projects/Godot/core/input/input.cpp:886)
[30] DisplayServerX11::process_events() (/var/home/user/Projects/Godot/platform/linuxbsd/x11/display_server_x11.cpp:4245)
[31] OS_LinuxBSD::run() (/var/home/user/Projects/Godot/platform/linuxbsd/os_linuxbsd.cpp:797)
[32] /home/user/Projects/Godot/bin/godot.linuxbsd.editor.dev.x86_64.mono(main+0x15a) [0x262c080] (/var/home/user/Projects/Godot/platform/linuxbsd/godot_linuxbsd.cpp:75)
[33] /lib64/libc.so.6(+0x29510) [0x7f6bf83fd510] (??:0)
[34] /lib64/libc.so.6(__libc_start_main+0x89) [0x7f6bf83fd5c9] (??:0)
[35] /home/user/Projects/Godot/bin/godot.linuxbsd.editor.dev.x86_64.mono(_start+0x25) [0x262be65] (??:?)
-- END OF BACKTRACE --
```

### Steps to reproduce

Open the MRP and double click on the imported cube scene.

### Minimal reproduction project

[MRP.zip](https://github.com/godotengine/godot/files/10157869/MRP.zip)
This minimal reproduction project was made with Godot 4 beta5 and it should crash with any latest Godot when you open the advanced import settings of the cube scene.

**Comment by RumblingTurtle** [comment] 2022-12-05 21:46
Reproducible on Ubuntu 20.04

**Comment by fire** [comment] 2022-12-05 22:04
I will be looking at this. However, will need some assistance if possible. Not able to work as much.

**Comment by TokageItLab** [comment] 2022-12-06 07:16
ref #69604

**Comment by akien-mga** [comment] 2022-12-07 09:12
Duplicate of #69604

**Closed by akien-mga** 2022-12-07 09:12 UTC
Labels: bug, topic:import, crash, topic:3d
