### ISSUE TITLE
Tooltips flash when Task Manager is open

### ISSUE THREAD

**Issue by mateusak** [godotengine/godot#4452] opened 2016-04-26 18:53 UTC
**Operating system or device:**
Windows 7 Ultimate 64x

**Issue description** (what happened, and what was expected):
The tooltip of menu elements are flashing, and it normally wouldn't.

**Steps to reproduce:**
Open Task Manager, put your mouse over any menu element, and wait a bit until the tooltip show up.

_Really unnecessary to fix, but maybe you find another problem related to what is causing this, so I decided to relate anyways._

**Comment by vnen** [comment] 2016-04-27 00:08
Duplicate of #3835.

**Closed by vnen** 2016-04-27 00:08 UTC
