### ISSUE TITLE
[Godot 4] Broken view of RectangeShape2D

### ISSUE THREAD

**Issue by DarkMessiah** [godotengine/godot#62076] opened 2022-06-15 16:57 UTC
### Godot version

4.0 alpha 10

### System information

Windows 11, RTX 3070 TI

### Issue description

RectangleShape2D looks broken.
| Godot 4 | Godot 3.5 |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/1756388/173882324-e22f67fa-f954-45a2-a3e5-cc988c105c0c.png) | ![image](https://user-images.githubusercontent.com/1756388/173882673-006c1b7c-a36a-435a-930e-e256dab1f69b.png) |

### Steps to reproduce

Create a new RectangleShape2D in a CollisionShape2D.

**Comment by markdibarry** [comment] 2022-06-15 17:25
Duplicate: #56320

**Comment by Calinou** [comment] 2022-06-15 17:57
Duplicate of #56320.

**Closed by Calinou** 2022-06-15 17:57 UTC
