### ISSUE TITLE
Program crashed with signal 11

### ISSUE THREAD

**Issue by Deveex** [godotengine/godot#95109] opened 2024-08-03 22:53 UTC
### Tested versions

Godot Engine v4.3 rc2 official [3978628c6]

### System information

Windows 10 - Godot_v4.3-rc2_win64.exe - Comptability

### Issue description

The Engine Crashes After i Minimize the window

### Steps to reproduce

CrashHandlerException: Program crashed with signal 11
Engine version: Godot Engine v4.3.rc2.official (3978628c6cc1227250fc6ed45c8d854d24c30c30)
Dumping the backtrace. Please include this when reporting the bug to the project developer.
[1] error(-1): no debug info in PE/COFF executable
[2] error(-1): no debug info in PE/COFF executable
[3] error(-1): no debug info in PE/COFF executable
[4] error(-1): no debug info in PE/COFF executable
[5] error(-1): no debug info in PE/COFF executable
[6] error(-1): no debug info in PE/COFF executable
[7] error(-1): no debug info in PE/COFF executable
[8] error(-1): no debug info in PE/COFF executable
[9] error(-1): no debug info in PE/COFF executable
[10] error(-1): no debug info in PE/COFF executable
[11] error(-1): no debug info in PE/COFF executable
[12] error(-1): no debug info in PE/COFF executable
[13] error(-1): no debug info in PE/COFF executable
[14] error(-1): no debug info in PE/COFF executable
[15] error(-1): no debug info in PE/COFF executable
[16] error(-1): no debug info in PE/COFF executable
[17] error(-1): no debug info in PE/COFF executable
[18] error(-1): no debug info in PE/COFF executable
[19] error(-1): no debug info in PE/COFF executable
-- END OF BACKTRACE --
================================================================

### Minimal reproduction project (MRP)

[Uploading my-game-with-godot.zip…]()

**Comment by kus04e4ek** [comment] 2024-08-04 08:49
Duplicate of: #95068

**Closed** 2024-08-04 14:31 UTC

**Comment by DongMofsh** [comment] 2024-08-24 13:45
me too, what can i do?

**Comment by DongMofsh** [comment] 2024-08-24 13:47
NVIDIA GeForce RTX 3070 Ti Laptop GPU  
 CrashHandlerException: Program crashed with signal 11
Engine version: Godot Engine v4.3.stable.mono.official (77dcf97)
Dumping the backtrace. Please include this when reporting the bug to the project developer.
[1] error(-1): no debug info in PE/COFF executable
[2] error(-1): no debug info in PE/COFF executable
[3] error(-1): no debug info in PE/COFF executable
[4] error(-1): no debug info in PE/COFF executable
[5] error(-1): no debug info in PE/COFF executable
[6] error(-1): no debug info in PE/COFF executable
[7] error(-1): no debug info in PE/COFF executable
[8] error(-1): no debug info in PE/COFF executable
[9] error(-1): no debug info in PE/COFF executable
[10] error(-1): no debug info in PE/COFF executable
[11] error(-1): no debug info in PE/COFF executable
[12] error(-1): no debug info in PE/COFF executable
[13] error(-1): no debug info in PE/COFF executable

**Comment by Hanred0** [comment] 2024-09-03 22:35
The same happens to me; if you're on Windows, run the program in compatibility mode—it worked for me.

**Comment by Hanred0** [comment] 2024-09-03 22:52
I've been testing it, and it's very slow for me. For now, the best option is to go back to version 4.2.2.

**Comment by akien-mga** [comment] 2024-09-04 09:44
Please open a dedicated bug reports with clear steps to reproduce. A crash with "signal 11" just means "crash", so there can be many different reasons for it to happen, which may not be related to the original bug report here (which was fixed in 4.3.stable).
