### ISSUE TITLE
Bug: Undo don't work after click on "Clear" in Script

### ISSUE THREAD

**Issue by 2dvision** [godotengine/godot#8181] opened 2017-03-28 04:31 UTC
Godot v2.1.2 stable, ubuntu 16.04 and windows 7, 64-bit

I clicked on "Clear" by mistake. Undo don't work, And all my codes cleared.

![undo dont work](https://cloud.githubusercontent.com/assets/16509592/24389181/2a91d012-136f-11e7-92dd-4416620dbf64.png)

**Comment by Hinsbart** [comment] 2017-03-28 04:44
Closing as duplicate of #6329 (already fixed in the master branch)

**Closed by Hinsbart** 2017-03-28 04:44 UTC
