### ISSUE TITLE
Window opens in corner on 4K display

### ISSUE THREAD

**Issue by nezvers** [godotengine/godot#47306] opened 2021-03-23 18:44 UTC
**Godot version:**
3.3 RC6 and previous versions

**OS/device including version:**
Win10

**Issue description:**
A new game window opens in the corner when using the 4K display.
Can be fixed with `OS.center_window()` but shouldn't be needed.
![image](https://user-images.githubusercontent.com/26794315/112200529-ffe0ef80-8c17-11eb-9e9b-dc27a6d198c3.png)

**Steps to reproduce:**
4k display or probably 2k will do.

**Minimal reproduction project:**
Any project.

**Comment by Calinou** [comment] 2021-03-23 20:24
Duplicate of https://github.com/godotengine/godot/issues/13017.

**Closed by Calinou** 2021-03-23 20:24 UTC
