### ISSUE TITLE
@export value does not change if the enum got updated

### ISSUE THREAD

**Issue by tiepduongvn** [godotengine/godot#95692] opened 2024-08-17 12:53 UTC
### Tested versions

- Reproduce: 4.3 stable.

### System information

- System: not system-related issues.

### Issue description

- I have an enum, @export a var using that enum (then I choose a value for it). Now if I insert a new key in middle of the enum, or just reorder keys to organize the project in a better way (improve readability) -> the value of the @export var does not change (which means their key will change) -> it can cause a lot of problem with other scripts which reference that key.
- The purpose of using enum is to use the key as references for all parts of the game, and re-order the enum is necessary in a lot of case to make the code readability better.

### Steps to reproduce

1. Code:
enum Types {
    TYPE_1,
    TYPE_3,
    TYPE_2,
}
@export var type: Types

2. In Editor: now set type = TYPE_2 (value = 2)

3. Rewrite enum to improve readability
enum Types {
    TYPE_1,
    TYPE_2,
    TYPE_3,
}

4. Result -> in editor type = TYPE_3 (auto change) because it keeps it value = 2.
Expected result: it should still be TYPE_2 -> the actual value would be 1 now.
There is no point of automatically changing the key in this case, the whole purpose of using enum so we can just use Enum.ENUM_KEY in other parts of the code without caring about its actual value, I do believe this is a bug.

### Minimal reproduction project (MRP)

N/A

**Comment by dalexeev** [comment] 2024-08-17 13:04
* Duplicate of #94395.

Note that Godot stores enum values ​​as integers. So updating a value in the enum is an incompatible change, the exported value in the scene file is **not** automatically updated to match the new value in the enum. You can use this instead:

```gdscript
@export_enum("a", "b", "c") var x: String = "a"
```

Thanks for the contribution nonetheless!

**Closed by dalexeev** 2024-08-17 13:04 UTC
