### ISSUE TITLE
Editor displaying exported variables twice for custom scripts

### ISSUE THREAD

**Issue by KappiWolf** [godotengine/godot#64080] opened 2022-08-07 22:42 UTC
### Godot version

4.0dev alpha13

### System information

Windows 10

### Issue description

When using @export in a custom script, the exported variable displays twice in the inspector. Changes in one export field is immediately reflected in the duplicate.
![image](https://user-images.githubusercontent.com/100701466/183313766-58580d1c-1293-4a1b-8291-9cb573692773.png)

### Steps to reproduce

open up a new script attached to a node.

export a variable using @export

error occurs with resource variables as well as values (int, vector3)

**Comment by akien-mga** [comment] 2022-08-08 05:41
Duplicate of https://github.com/godotengine/godot/issues/63668

**Closed by akien-mga** 2022-08-08 05:41 UTC
Labels: bug, topic:gdscript, topic:editor
