### ISSUE TITLE
3d environments don't render correctly when there's a shader with too many parameters in scene on M1 Macbook

### ISSUE THREAD

**Issue by Miziziziz** [godotengine/godot#71285] opened 2023-01-12 20:00 UTC
### Godot version

v3.5.1.stable.mono.official [6fed1ffa3]

### System information

Macbook Air M1 2020, MacOS Ventura 13.0.1

### Issue description

If you have a 3d model with a custom shader that has a lot of texture parameters on it, the scene it's in will have a lot of flicker and incorrect shading as you move the camera around. See attached video:

https://user-images.githubusercontent.com/7292421/212168487-db5cdab0-927f-424b-ad09-6f26f1cc6ca0.mov

### Steps to reproduce

Make a basic 3d scene, on one model add a custom shader, copy in this shader code:

```
shader_type spatial;

uniform sampler2D texture1 : hint_albedo;
uniform sampler2D texture2 : hint_albedo;
uniform sampler2D texture3 : hint_albedo;
uniform sampler2D texture4 : hint_albedo;
uniform sampler2D texture5 : hint_albedo;
uniform sampler2D texture6 : hint_albedo;
uniform sampler2D texture7 : hint_albedo;
uniform sampler2D texture8 : hint_albedo;
uniform sampler2D texture9 : hint_albedo;
uniform sampler2D texture10 : hint_albedo;
uniform sampler2D texture11 : hint_albedo;
uniform sampler2D texture12 : hint_albedo;


void fragment(){
	
}
```

Move the camera around

### Minimal reproduction project

[M1ShaderBugTest.zip](https://github.com/godotengine/godot/files/10405550/M1ShaderBugTest.zip)

**Comment by clayjohn** [comment] 2023-01-12 20:03
Duplicate of https://github.com/godotengine/godot/issues/54297

**Closed by clayjohn** 2023-01-12 20:03 UTC

**Comment by clayjohn** [comment] 2023-01-12 20:06
To provide some specific insight to your system. It looks like the M1 Mac only supports up to 16 textures per shader https://opengl.gpuinfo.org/displayreport.php?id=6210 We need to print a warning if users go over that limit which is what is tracked in https://github.com/godotengine/godot/issues/54297
