### ISSUE TITLE
[Mono] Compilation with Mono glue fails if `~/.local/share/godot/mono/GodotNuGetFallbackFolder` doesn't exist

### ISSUE THREAD

**Issue by nonunknown** [godotengine/godot#62965] opened 2022-07-12 22:19 UTC
### Godot version

42537daeb1819b72a700acfe7ab6486b1a5d45d8

### System information

manjaro linux

### Issue description

After compiling for: 42537daeb1819b72a700acfe7ab6486b1a5d45d8 + mono + linux the editor crashes without even opening project manager

[bug.txt](https://github.com/godotengine/godot/files/9097208/bug.txt)

### Steps to reproduce

* compile with mono
* open the engine

### Minimal reproduction project

Not possible

**Comment by raulsntos** [comment] 2022-07-13 14:57
I have compiled the engine at the same commit you mention but I can't reproduce it, I can even open and run a simple project that prints "Hello World" in the console.

Since compiling the engine for mono requires building the binary twice, it's likely you are using the wrong binary. You should be opening the one that has `opt` in the name, the other one is only used to generate the C# bindings.

**Comment by raulsntos** [comment] 2022-07-13 15:18
It seems the last command (the one that creates the `opt` binary) is failing due to not finding the directory `/home/nonunknown/.local/share/godot/mono/GodotNuGetFallbackFolder`. I don't know how that script could work before because we've always been using the `opt` binary (including in 3.x).

**Comment by raulsntos** [comment] 2022-07-13 15:39
When you run Godot the first time it creates the fallback folder and adds it to your `nuget.config`. Since you had run Godot before, your `nuget.config` was already pointing to that folder but, since you formatted, it didn't exist. When MSBuild tried to restore the necessary packages, it failed because `nuget.config` told it to look for the packages in a folder that doesn't exist.

**Comment by raulsntos** [comment] 2022-09-07 16:24
Duplicate of https://github.com/godotengine/godot/issues/44532

**Closed by raulsntos** 2022-09-07 16:24 UTC
Labels: bug, topic:buildsystem, topic:dotnet
