### ISSUE TITLE
Line2D Antialiased bug

### ISSUE THREAD

**Issue by Hapenia** [godotengine/godot#37433] opened 2020-03-30 13:50 UTC
**Godot version:**
Godot 3.2
**OS/device including version:**
Ubuntu19.04
**Issue description:**
When I set the alpha of the Line2D's "Default_Color" to a lower value than 255, enable "Antialiased"will  causes the the edges' not transparent.
**Steps to reproduce:**

 1. Create a Line2D
 2. Set the property "Default Color" to a value which has a lower alpha from 255.
 3. Open the option "Antialiased" in "Border".
 4. Add some points.
 5. Zoom in and watch.

![2020-03-30 21-47-36屏幕截图](https://user-images.githubusercontent.com/56782249/77919879-4f743000-72d0-11ea-8c92-ae03daf0f123.png)
![2020-03-30 21-49-00屏幕截图](https://user-images.githubusercontent.com/56782249/77919901-556a1100-72d0-11ea-8d19-c2d0f67ba9f1.png)

**Minimal reproduction project:**
[GraphEditAntialiasedBug.zip](https://github.com/godotengine/godot/files/4403191/GraphEditAntialiasedBug.zip)

**Comment by Calinou** [comment] 2020-03-30 15:04
Duplicate of #35878.

**Closed by Calinou** 2020-03-30 15:04 UTC
