### ISSUE TITLE
Segmentation faults on macOS Sierra.

### ISSUE THREAD

**Issue by thisismike97** [godotengine/godot#27779] opened 2019-04-07 18:17 UTC
**Godot version:**
2.1.5 stable

**OS/device including version:**
Macos Sierra (10.12.6)

**Issue description:**
2 of our players have reported crashes at our games launch, we noticed they were both on macos sierra and that they both had segfault: 11 in their console logs.

The full discussion from our players can be read below:
https://steamcommunity.com/app/466800/discussions/1/133256240740552280/

We run a custom module in godot for steamworks integration, unfortunatly we cant easily test if it is caused by the engine or our module since the game in question uses the module as a dependency and taking out all the code would be too time consuming. however because of the console logs mentioning physics 2D i think the cause lays within the engine.

The module in question and its instructions can be found here:

https://github.com/Gramps/GodotSteam/tree/godot2

The game in question can be found here:

https://store.steampowered.com/app/466800/The_Dope_Game/

I have requested one of the players to try and upgrade to high sierra or mojave to confirm if the cause of the problem really lies within that specific OS version. If any further information or other support is needed we will do our best to help out. We really want our players to be able to play without further issue.

**Steps to reproduce:**

I am unable to reproduce their issue as my own system is running macos mojave, where the game runs fine.

**Comment by Calinou** [comment] 2020-08-18 14:11
@thisismike97  Can you (or anyone else) still reproduce this bug in [Godot 3.2.2](https://godotengine.org/article/maintenance-release-godot-3-2-2) or any later release?

If yes, please ensure that an up-to-date Minimal Reproduction Project (MRP) is included in this report (a MRP is a zipped Godot project with the minimal elements necessary to reliably trigger the bug). You can upload ZIP files in an issue comment with a drag and drop.

**Comment by Calinou** [comment] 2020-09-13 20:08
Closing, since nobody has been able to reproduce this recently. Please comment if you can still reproduce this bug.

PS: If no [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) was included in the original bug report, please upload one as well to ease troubleshooting.

**Closed by Calinou** 2020-09-13 20:08 UTC
Labels: bug, platform:macos, topic:core
