### ISSUE TITLE
macOS 4.2dev6 (regular and Mono) crash when opening a new project after Jolt installed.

### ISSUE THREAD

**Issue by hawkwood** [godotengine/godot#82810] opened 2023-10-04 18:48 UTC
### Godot version

4.2dev6 regular and Mono

### System information

macOS 13.4.1 M1 MacbookPro

### Issue description

Dev6 crashes (fails to open) a project with Jolt physics installed.

Crash log attached
[Godot42d6-jolt-crash.txt](https://github.com/godotengine/godot/files/12807103/Godot42d6-jolt-crash.txt)

### Steps to reproduce

1. Open Godot 4.2dev6 on macOS
2. create new project
3. install Godot Jolt from AssetLib
4. restart Godot to that project
5. see it crash

### Minimal reproduction project

[JoltTestDev6.zip](https://github.com/godotengine/godot/files/12807078/JoltTestDev6.zip)

**Comment by hawkwood** [comment] 2023-10-04 18:51
It's worth noting that dev4 does not exhibit this issue, but dev5 and dev6 do.

**Comment by akien-mga** [comment] 2023-10-04 20:21
CC @mihe @dsnopek

**Comment by mihe** [comment] 2023-10-04 23:37
It doesn't look to be an issue with GDExtension compatibility specifically, as it crashes in [my editor plugin](https://github.com/godot-jolt/godot-jolt/blob/87a478f5f24e5dc3a012cef174a793c120d25324/src/servers/jolt_editor_plugin.cpp#L18) due to `get_editor_interface()->get_base_control()->get_theme()` now returning `nullptr` for some reason.

After doing some bisecting it appears that #81130 is the cause for this change in behavior.

Is this an intended breakage, or is it my questionable use of the theme API that's coming back to haunt me? Maybe @YuriSizov can shed some light on this?

**Comment by YuriSizov** [comment] 2023-10-04 23:42
@mihe Yes, this is intended. You can fetch the editor theme directly through `EditorInterface.get_editor_theme()` now.

> my questionable use of the theme API

It depends on why you're doing it this way. GDExtensions support defining icons for types via the configuration file, so if that's your need, then yes, this is pretty questionable 🙃  If there is some other reason, let me know! But in general I don't think we expect developers to manually modify the editor theme.

**Comment by mihe** [comment] 2023-10-05 00:09
> Yes, this is intended.

Right, then I guess this technically falls under me [not supporting](https://github.com/godot-jolt/godot-jolt#what-versions-of-godot-are-supported) anything but latest stable, and this issue can be closed.

> GDExtensions support defining icons for types via the configuration file, so if that's your need, then yes, this is pretty questionable

Yes, I am/was aware of this. I'm sure I won't make a very strong case for not just using this functionality, but in this particular case I was hoping to avoid bundling the extra resources with the extension and just use the existing icons, since these particular nodes are meant to substitute existing ones.

Funnily enough the project I borrowed this trick from has since transitioned to bundling `.svg` files instead, so maybe I ought to revisit this decision as well.

> As for the duplication trick, whenever you modify the theme it sends the changed signal which updates the entire editor UI, so 5 `set_icon`s, 5 whole UI updates. It should be avoided.

Right, yeah, I figured it was something along those lines. Even the one I update I'm causing right now is probably not ideal, so maybe that's reason enough to just do this properly with `[icons]` instead, assuming that would fare better.

**Comment by mihe** [comment] 2023-10-05 01:14
I just gave `[icons]` a try and was reminded of another reason why I chose not to use them, which is that they seem to require absolute `res://` paths in order to work, thereby more or less requiring that the extension be installed to a specific location, which I'd prefer to avoid. This also differs from how `[libraries]` behave, which allows for [relative paths](https://github.com/godot-jolt/godot-jolt/blob/87a478f5f24e5dc3a012cef174a793c120d25324/godot-jolt.gdextension#L8-L21).

Maybe I'll take you up on your `Theme::merge_with` solution after all, @YuriSizov. :)

Either way, that'll be for when 4.2-stable is out. Until then I suppose I can throw in a null check in that function and simply not add the icons if that's the case. It'll look a bit strange in the outliner, but at least it won't crash.

**Comment by akien-mga** [comment] 2023-10-05 07:19
Closing as it's a downstream godot-jolt issue.

**Closed by akien-mga** 2023-10-05 07:19 UTC
Labels: bug, topic:gdextension, crash

**Comment by YuriSizov** [comment] 2023-10-05 10:26
> This also differs from how `[libraries]` behave, which allows for [relative paths](https://github.com/godot-jolt/godot-jolt/blob/87a478f5f24e5dc3a012cef174a793c120d25324/godot-jolt.gdextension#L8-L21).

I don't see why we can't do the same for the icons, by the way. If we can resolve a project local path from that, then we can support it for icons as well.

**Comment by mihe** [comment] 2023-10-05 10:43
> If we can resolve a project local path from that, then we can support it for icons as well.

I'll see if I can make a PR for it.

**Comment by YuriSizov** [comment] 2023-10-05 10:43
@mihe I'm making one right now :)
