### ISSUE TITLE
Black rectangle appears on screen on project run

### ISSUE THREAD

**Issue by micwu562** [godotengine/godot#41481] opened 2020-08-24 01:30 UTC
**Godot version:**
58f5c2b

**OS/device including version:**
macOS Catalina 10.15.5

**Issue description:**
Every time I run a project in the editor after making a change, a black rectangle that acts like a window appears in place of the "saving scene" popup. The rectangle doesn't disappear until the project is run again.

**Steps to reproduce:**
1: modify a scene
2: run the project

**Minimal reproduction project:**
Happens to me on any project, including newly created ones.

**Comment by Calinou** [comment] 2020-09-07 12:53
Duplicate of #39620.

**Closed by Calinou** 2020-09-07 12:53 UTC
Labels: bug, topic:editor
