### ISSUE TITLE
Android build crashing when OBJ mesh instance is in the scene

### ISSUE THREAD

**Issue by DEXIT33** [godotengine/godot#16380] opened 2018-02-04 10:06 UTC
**Godot version:**
v3.0.stable.official

**OS/device including version:**
On PC it runs fine, problem is only on Android Device, currently I am testing it on Xiaomi Mi Max Prime (helium). Here are detailed specs: https://www.gsmarena.com/xiaomi_mi_max-8057.php

**Issue description:**
I created a normal scene and imported model exported to obj using blender. Model has only few vertices so this will not be a problem. If I run it on windows everything works fine, but on android it crashes right after the splashscreen - loading the scene with mesh instance, without meshinstance in the scene it works fine

**Steps to reproduce:**
Create new project, create root node, create Camera, Create MeshInstance and asign any obj file as a mesh, export it for android and run.

**Minimal reproduction project:**
I attached my project so you can see what is wrong.

[AndroidTest.zip](https://github.com/godotengine/godot/files/1692655/AndroidTest.zip)

**Comment by DEXIT33** [comment] 2018-02-04 12:13
Yes, it is.

**Comment by Zireael07** [comment] 2018-02-04 13:10
Then it's a duplicate of an existing issue  - I can't find it at the moment  but the gist is, Adreno's OpenGL implementation is very weird.

**Comment by DEXIT33** [comment] 2018-02-04 13:35
Oh, I see, so there aren't any solutions?

**Comment by akien-mga** [comment] 2018-02-13 10:54
Yes, it's #12816 (so closing as duplicate). Sadly we don't know of any decent solution for now, Adreno GPU drivers for OpenGL ES 3.0 are the worst... It should be fixed in Godot 3.1 with the new OpenGL ES 2.0 renderer, which we'll enforce on Adreno hardware (at least until they start providing working drivers).

**Closed by akien-mga** 2018-02-13 10:54 UTC
