### ISSUE TITLE
High Level Networking + TCP punchthrough?

### ISSUE THREAD

**Issue by radicaled** [godotengine/godot#7135] opened 2016-11-17 11:18 UTC
When using the high level networking functionality in Godot master, it seems you can either be a client or a server -- not both. However, in order to do NAT punchthrough for TCP, you have to attempt to both send and receive a TCP connection to both peers in order for it to work, and once the TCP connection is lost so is the NAT mapping. Well, that's my understanding of it, anyway. 

Is there a method of using the high level networking component while also enabling punchthrough? If not, will UPnP be supported before G3, since that mostly removes the need for punchthrough techniques?

**Comment by mhilbrunner** [comment] 2017-12-04 05:25
Duplicate of https://github.com/godotengine/godot/issues/2970.

@bojidar-bg Close please.

**Closed** 2017-12-04 09:08 UTC
Labels: feature proposal, topic:network

**Comment by bojidar-bg** [comment] 2017-12-04 12:38
@mhilbrunner BTW, you don't need to mention specific bugsquad members, you can either not mention anyone (since we are all subscribed to the repo), or mention `@`godotengine/bugsquad.
