### ISSUE TITLE
GD Script 2.0 Calling an overridden function of an engine class doesn't work if the reference is statically typed to that engine class

### ISSUE THREAD

**Issue by mrtripie** [godotengine/godot#53606] opened 2021-10-09 16:46 UTC
### Godot version

v4.0.dev.calinou.6f72d9d19

### System information

Win 10

### Issue description

When a function of an engine class is overridden, if  you call that function from a reference that is statically typed as the engine class, it will call the engine class's function instead of the overridden one.

It doesn't happen if the base class is a GDScript class.

### Steps to reproduce

I discovered this when working on a baseball game with multiple cameras. One is set to follow the ball after hit. When made current I wanted to determine what the offset position from the ball should be based on the balls velocity. So my example will use Camera3D, but I don't think it should be exclusive to it.

1: Make a scene with a Camera3D
2: Attach a script to the root and camera
3: add this to the root script:
```
@onready var camera: Camera3D = get_node("Camera3D")

func _ready():
    camera.make_current()
```
4: add this to the camera script:
```
func make_current():
    print("overridden function called")
```
5: Press play, the overridden function won't be called
6: If you remove the ": Camera3D" part from the root script, and press play, it will be called as expected

### Minimal reproduction project

[OverridenFuncMinReproduciton.zip](https://github.com/godotengine/godot/files/7316019/OverridenFuncMinReproduciton.zip)

**Comment by xsellier** [comment] 2021-11-18 13:29
I think it is a duplicate of https://github.com/godotengine/godot/issues/55024

**Comment by Calinou** [comment] 2021-11-18 17:09
Duplicate of https://github.com/godotengine/godot/issues/55024.

**Closed by Calinou** 2021-11-18 17:09 UTC
Labels: bug, topic:gdscript, regression
