### ISSUE TITLE
CTRL+A -> CTRL+C -> CTRL+V doesn't work in the Script editor

### ISSUE THREAD

**Issue by alxcyl** [godotengine/godot#1338] opened 2015-02-05 07:38 UTC
When on the script editor, when you select the script using CTRL+A, then copy it using CTRL+C, if you paste it using CTRL+V, no text will be pasted. However, if you select by dragging the selection throughout the whole script, then copy it, it will work when you paste.

For example, copy a whole script from script editor and paste it into Notepad++, nothing will be pasted into Notepad++. But if you select using the mouse, then paste it into Notepad++, it works fine. Also works fine from Notepad++ to Script Editor.

**Comment by theuserbl** [comment] 2015-03-05 23:19
It is only "copy" what not work.
And it have nothing to do with [CTRL]+[C], because that is only a shortcut of the mnu-entry Edit->Copy, what not work.
But if you have from anywhere else copied text, you can paste it in the editor. And the "Select All" [CTRL]+[A] works, too.

**Comment by reduz** [comment] 2015-03-08 12:52
This is on windows?

**Comment by tuga3d** [comment] 2015-03-12 01:23
i'm linux and i have the same behavior. this is the error i get on terminal:
ERROR: _base_get_text: Index p_to_column out of size (text[p_to_line].length()+1).
At: scene/gui/text_edit.cpp:2142.

**Comment by kubecz3k** [comment] 2015-11-11 18:09
I'm on Linux and I can't reproduce this issue in any way in Alpha 2.0. From test made by @eska014 it seems in Windows it's working good as well. Since the bug is quite old and it seems to be fixed now I will archive it. If someone still is experiencing it, please let me know so I could reopen.

**Closed by kubecz3k** 2015-11-11 18:09 UTC
Labels: archived, bug, topic:editor

**Comment by Ytachi1000** [comment] 2023-01-05 23:01
verry anonying bug
