### ISSUE TITLE
[4.0 beta10 Bug] When you try to close a running project, if the Node in the project activates the function _notification (), the project will report an error, as shown in the figure.

### ISSUE THREAD

**Issue by Atem1995** [godotengine/godot#70828] opened 2023-01-02 08:11 UTC
### Godot version

4.0 beta 10

### System information

Window10

### Issue description

When you try to close a running project, if the Node in the project activates the function _notification (), the project will report an error, as shown in the figure.
![捕获](https://user-images.githubusercontent.com/52338846/210206981-c6dfa3ad-b67d-4dd6-8d58-7cbf4f3e1452.PNG)

### Steps to reproduce

When you try to close a running project, if the Node in the project activates the function _notification (), the project will report an error, as shown in the figure.

### Minimal reproduction project

When you try to close a running project, if the Node in the project activates the function _notification (), the project will report an error, as shown in the figure.

**Comment by Rindbee** [comment] 2023-01-02 11:45
May be caused by `NOTIFICATION_PREDELETE`. Excluding it should help.

**Comment by Atem1995** [comment] 2023-01-02 12:53
Sorry, I don't quite understand the solution.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "godotengine/godot"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年1月2日(星期一) 晚上7:46
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [godotengine/godot] [4.0 beta10 Bug] When you try to close a running project, if the Node in the project activates the function _notification (), the project will report an error, as shown in the figure. (Issue #70828)





 
May be caused by NOTIFICATION_PREDELETE. Excluding it should help.

**Comment by Maran23** [comment] 2023-01-02 15:58
> Sorry, I don't quite understand the solution.

The notification `NOTIFICATION_PREDELETE` is send before the node is deleted. If you receive this signal, you better just do nothing since the object is about to be deleted.

**Comment by kleonc** [comment] 2023-01-02 17:12
The issue is `if state` check is not reliable (it evaluates to true when `state` refers to an already freed object). Using `if is_instance_valid(state)` should make it work as expected.

Duplicate of #44861, related to #59816.

**Closed by kleonc** 2023-01-02 17:12 UTC
Labels: bug, topic:core

**Comment by Atem1995** [comment] 2023-01-03 03:02
Thank you for your help, all of you!It works!


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "godotengine/godot"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年1月3日(星期二) 凌晨1:12
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [godotengine/godot] [4.0 beta10 Bug] When you try to close a running project, if the Node in the project activates the function _notification (), the project will report an error, as shown in the figure. (Issue #70828)





 
The issue is if state check is not reliable (it evaluates to true when state refers to an already freed object). Using if is_instance_valid(state) should make it work as expected.
 
Duplicate of #44861, related to #59816.
