### ISSUE TITLE
GDScript @export vars with setters do not set the value shown in the editor when the node is loaded, if it is the default value

### ISSUE THREAD

**Issue by immijimmi** [godotengine/godot#94969] opened 2024-07-31 05:28 UTC
### Tested versions

- Reproducible in: Godot v4.2.2.stable (Forward+) on Windows 10

### System information

Godot v4.2.2.stable (Forward+) on Windows 10

### Issue description

When using an `@export` variable *without* defining a custom getter/setter, the current behaviour uses whatever value the variable is initialised to in the script as the default value in the editor. This behaviour makes it unnecessary for Godot to additionally set the variable to that value (if it's left as default in the editor) upon loading the node, and it does not do so.

However, when a custom getter is defined for that variable, the above behaviour (using the value that the variable is initialised to as the default value in the editor) does not take place (presumably because the initial value is not static in this case).
As such, a situation can arise where the value of the variable when the node is loaded is not equivalent to the value shown in the editor.

In cases where a custom setter is also defined, this issue can be solved by setting the variable to the value displayed in the editor when the node is loaded, even when it is the default value.

One example use case in which this issue can arise is when creating an `@export` property in a subclass which constitutes the access functionality for an internal attribute declared in the base class. If the base class initialises that attribute to anything other than the default for its type, the property as shown in the editor by default will not match the value its getter returns once the node is loaded.

### Steps to reproduce

- Create a scene with a single Node2D as the root and attach a script to that node
- Define a bool variable in your script with an initial value of `true`
- Define an `@export` bool property in the same script, whose getter simply returns the above variable, and whose setter simply sets to the above variable
- Save the script, and look at the node in the inspector. It will show the above property with a default value of `false` (the box will be unticked)
- In the script, inside the `_ready()` function, `print` the above property
- Save the script again and run the scene. When the node is loaded, `true` will be printed to the console as the property's value, despite the inspector showing a value of `false` for that same property

### Minimal reproduction project (MRP)

[test.zip](https://github.com/user-attachments/files/16436631/test.zip)

**Comment by huwpascoe** [comment] 2024-07-31 06:20
A default value can be set for properties same as regular var:
```gdscript
var _foo: int = 3
@export var foo: int = 3:
	get: return _foo
	set(value): _foo = value
```
Note that the underlying var will be returned if default so they should match to avoid confusion.

It also works with the inline version
```gdscript
@export var bar: int = 6:
	get: return bar
	set(value): bar = value
```

**Comment by dalexeev** [comment] 2024-07-31 07:43
* Duplicate of #86494.

Thanks for the contribution nonetheless!

**Closed by dalexeev** 2024-07-31 07:43 UTC
