### ISSUE TITLE
Redeclaration of vars possible / Weird side effects

### ISSUE THREAD

**Issue by RayKoopa** [godotengine/godot#6454] opened 2016-09-11 14:35 UTC
**Operating system or device - Godot version:**
Windows 10 x64 - Godot 2.1 stable

**Issue description** (what happened, and what was expected):
Hence the following code:

```
func _process(delta):
    # Snap-move the grid to place it centered under the camera.
    var grid_pos = _grid.get_translation()
    print(grid_pos.y)
    var camera_pos = _camera.get_translation()
    var offset = grid_size * max_grid_steps / 2
    var grid_pos = Vector3(camera_pos.x - offset, grid_pos.y, camera_pos.z - offset)
    print(grid_pos.y)
    _grid.set_translation(grid_pos)
```

Note how `grid_pos` is declared in the first line of the function, then simply redeclared 4 lines later. This compiles without an error. The old value is lost then.

But wait, there's more! With some basic testing:

```
    var a = Vector3(0, 0, 0)
    var b = Vector3(2, 2, 2)
    var a = Vector3(b.x, a.y, b.z)
    print(a.y)
```

This will bug out at runtime, complaining `a` is `Nil` when wanting to combine `b` and `a` together.

```
    var a = _grid.get_translation()
    var b = Vector3(2, 2, 2)
    var a = Vector3(b.x, a.y, b.z)
    print(a.y)
```

This does **not** cause an error at runtime. `a` "correctly" becomes 2, 0, 2 (when the grid was at Y=0).

In the context of my above code, it gets even worse: The new value of `grid_pos.y` somehow becomes the Y value of `camera_pos`!

```
func _process(delta):
    # Snap-move the grid to place it centered under the camera.
    var grid_pos = _grid.get_translation() # Grid is at 0,0,0
    print(grid_pos.y) # Prints "0"
    var camera_pos = _camera.get_translation() # Camera is at 0,3,6
    var offset = grid_size * max_grid_steps / 2
    var grid_pos = Vector3(camera_pos.x - offset, grid_pos.y, camera_pos.z - offset)
    print(grid_pos.y) # This funnily prints 3 now, though grid_pos.y was 0 all along!
        # It seems to have taken camera_pos.y's value instead.
    _grid.set_translation(grid_pos)
```

To cut a long story short: Redeclaration should be an error, right? The other things might just be follow-up errors.
I fell over this several times already, getting values I totally do not expect.

Sorry if it has been discussed before and for some reason is allowed now. But the behavior with the Y value doesn't make any sense at all.

This also happens with local variables shadowing more global ones, though that would still be okay (even if it should raise a warning or something).

**Comment by vnen** [comment] 2016-09-11 16:11
>  Redeclaration should be an error, right?

Yes, it should not be allowed. It is a similar problem to #6221.

> This also happens with local variables shadowing more global ones

I'm not sure about a warning there. It will be annoying if the programmer is aware of the scope rules.

**Comment by RayKoopa** [comment] 2016-09-11 16:40
If a programmer is aware of the scope rules, he is probably also aware of naming variables the same is not a good idea =3c Maybe make warnings optional, if in doubt.

**Comment by Noshyaar** [comment] 2018-04-06 10:39
First of all thank you for your report and sorry for the delay.

We released Godot 3.0 in January 2018 after 18 months of work, fixing many old issues either directly, or by obsoleting/replacing the features they were referring to.

We still have hundreds of issues whose relevance/reproducibility needs to be checked against the [current stable version](https://godotengine.org/download), and that's where you can help us.
**Could you check if the issue that you described initially is still relevant/reproducible in Godot 3.0 or any newer version, and comment about it here?**

For bug reports, please also make sure that the issue contains detailed steps to reproduce the bug and, if possible, a zipped project that can be used to reproduce it right away. This greatly speeds up debugging and bugfixing tasks for our contributors.

Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

Thanks in advance.

*Note: This message is being copy-pasted to many "stale" issues (90+ days without activity). It might happen that it is not meaningful for this specific issue or appears oblivious of the issue's context, if so please comment to notify the Bugsquad about it.*

**Comment by vnen** [comment] 2018-05-11 22:03
Re-declaration in the same function triggers an error now. Shadowing class members was forbidden for a while, but since many things changed into members, people started complaining about it and it's now allowed.

I want to eventually add a warning system (#18271) which could catch things like shadowing class or global members.

**Comment by akien-mga** [comment] 2018-11-22 12:34
Closing as fixed as per the above.

**Closed by akien-mga** 2018-11-22 12:34 UTC
Labels: bug, topic:gdscript
