### ISSUE TITLE
signals attaching to wrong parent and using wrong collision data caused by godot collision bit mask assignment fault

### ISSUE THREAD

**Issue by chucklepie** [godotengine/godot#41532] opened 2020-08-26 09:25 UTC
**Godot version:**
stable 3.2.2

**OS/device including version:**
Linux

**Issue description:**
I have three area2D shapes, all have their own area entered signal, as shown:
![image](https://user-images.githubusercontent.com/12863685/91284233-879a7480-e783-11ea-948e-ffeeb825e1ff.png)

However, when you run the program and in the IDE drag each shape onto the green rectangle shape only one shape displays a message and it displays all messages.

The reason is despite the above showing all 3 areas having their own signal connection, they are all somehow latching on to one area2d only. If you add more areas and add their own collisions and signals, they too join onto the wrong area.

What is wrong, is that despite clearing all collision layers and masks in this scene  (i.e. to zero), they are instead some how accumulating themselves, as shown below. There are items with 2 billion as the value. If I manually edit every file with bad collision mask data the fault goes away. So far I have had to do with with over 10 separate bodies in my project for both the layer and collision, so this is not a one-off.

```
[node name="Area1" type="Area2D" parent="."]
position = Vector2( 65, 196 )
collision_layer = 2147483648
collision_mask = 0

[node name="A1Collision" type="CollisionShape2D" parent="Area1"]
modulate = Color( 1, 0.717647, 0.0980392, 1 )
position = Vector2( 96, -84 )
shape = SubResource( 1 )

[node name="Area2" type="Area2D" parent="."]
position = Vector2( 228, 205 )
collision_layer = 0
collision_mask = 0
```

In conversations many times it is happening to others, there is clearly an issue with how collision layer/mask updates the scene file.

**Steps to reproduce:**
You can download a simple project:
https://gitlab.com/chucklepie-productions/games/testarea2d.git

Simply start the program and from the ide drag the circles into the rectangle. The even weirder thing is the rectangle is not he shape taking all the signals either!

I have a feeling this is linked to renaming collision layers, but I could be wrong. Code is below

***Possible Solution***
Seems to me it's caused by adding/subtracting/shifting bit masks via the Godot collision layer/mask boxes and this will happen to every other type, e.g. lightbox.

1. When a bit is toggle on and off, recalculate the whole value and update the scene file and do not try and use maths

**Code**
Alternatively, here is the entire code:

**tscn**
```
[gd_scene load_steps=5 format=2]

[ext_resource path="res://area2d.gd" type="Script" id=2]

[sub_resource type="RectangleShape2D" id=1]
extents = Vector2( 19, 26 )

[sub_resource type="CircleShape2D" id=2]
radius = 36.4006

[sub_resource type="CircleShape2D" id=3]
radius = 38.0

[node name="Node2D" type="Node2D"]
script = ExtResource( 2 )

[node name="Area1" type="Area2D" parent="."]
position = Vector2( 65, 196 )
collision_layer = 2147483648
collision_mask = 0

[node name="A1Collision" type="CollisionShape2D" parent="Area1"]
modulate = Color( 1, 0.717647, 0.0980392, 1 )
position = Vector2( 96, -84 )
shape = SubResource( 1 )

[node name="Area2" type="Area2D" parent="."]
position = Vector2( 228, 205 )
collision_layer = 0
collision_mask = 0

[node name="A2Collision" type="CollisionShape2D" parent="Area2"]
position = Vector2( -6, -14 )
shape = SubResource( 2 )

[node name="Area3" type="Area2D" parent="."]
position = Vector2( 146, 66 )
collision_layer = 0
collision_mask = 2147483648

[node name="A3Collision" type="CollisionShape2D" parent="Area3"]
position = Vector2( -33, 132 )
shape = SubResource( 3 )
[connection signal="area_entered" from="Area1" to="." method="_on_Area1_area_entered"]
[connection signal="area_entered" from="Area2" to="." method="_on_Area2_area_entered"]
[connection signal="area_entered" from="Area3" to="." method="_on_Area3_area_entered"]
```

**gd**
```
extends Node2D

func _on_Area1_area_entered(area: Area2D) -> void:
	print("a1 spawn area point " + area.name)

func _on_Area2_area_entered(area: Area2D) -> void:
	print("a2 spawn area point " + area.name)


func _on_Area3_area_entered(area: Area2D) -> void:
	print("a3 spawn area point " + area.name)



```

**Comment by madmiraal** [comment] 2020-09-15 12:35
This is effectively a duplicate of #41281 aggravated by #7644. Otherwise the MRP is behaving as expected.

`Area1`'s `collision_layer` bits are the same as `Area3`'s `collision_mask` bits. So when `Area3` (one of the circles) enters `Area1` (the green rectangle) both `Area1` and `Area3`'s `area_entered()` signals are triggered. `Area2` (the other circle) has no `collision_layer` or `collision_mask` bits set so it doesn't trigger `area_entered()` signals.

Resetting `Area1`'s `collision_layer` and `Area3`'s `collision_mask` to zero stops all `area_entered()` signals as expected.

**Comment by madmiraal** [comment] 2020-09-23 11:08
Closing as duplicate.

**Closed by madmiraal** 2020-09-23 11:08 UTC
Labels: bug, topic:physics
