### ISSUE TITLE
Godot 3 consume 4x more memory than Godot 2

### ISSUE THREAD

**Issue by Scellow** [godotengine/godot#14845] opened 2017-12-19 22:36 UTC
**Godot version:**

- Godot 3 beta 1
- Godot 2.1.4

**OS/device including version:**
Windows 10 x64
GTX 960
16gb ram

**Issue description:**
Godot 3 consume 4x more memory than v2

**Steps to reproduce:**
Create empty scene, then export to Windows Desktop

![taskmgr_2017-12-19_08-03-33](https://user-images.githubusercontent.com/27389256/34182179-774a5d16-e515-11e7-9e17-fe60c1842ae0.png)

**Comment by groud** [comment] 2017-12-19 23:56
Well, the code is bigger. So it's normal it consumes more memory...
But maybe there's a leak somewhere.

**Comment by reduz** [comment] 2017-12-20 01:03
I have no idea how to debug what is using memory, is there any kind of
memory debugger?

**Comment by BastiaanOlij** [comment] 2017-12-20 01:36
I'd say, does it count how much memory is allocated on the GPU. All the effects buffers would take up a lot of memory. It be interesting to see if it gets less when you turn effects of in the project settings. I'll see if I can reproduce on my Windows machine.

All in all 126Mb is nothing in this day and age....

**Comment by vnen** [comment] 2017-12-20 04:25
> I'd say, does it count how much memory is allocated on the GPU?

No, the Windows task manager shows only the regular RAM there. The Fall Creators Update can show GPU memory but only in general, not per-process. I notice a 0.5 GB increase in the GPU memory usage when I open Godot.

I know Visual Studio has a heap profiler, but don't know how useful it is.

**Comment by hpvb** [comment] 2017-12-20 20:52
I can't really reproduce this on Linux/x86_64. Running a scene with just one node in it shows a peak memory use of 24MB:
![screenshot from 2017-12-20 21-43-41](https://user-images.githubusercontent.com/2591099/34227896-10a66ee6-e5cf-11e7-9e06-183722c41a61.png)

The editor uses a little more ram, a little over 130MB:
![screenshot from 2017-12-20 21-45-00](https://user-images.githubusercontent.com/2591099/34227895-108b76ae-e5cf-11e7-8e7a-5c72914567d1.png)

Most of the RAM usage for the editor are:
* Two static allocations of 16MB for the debugger interface used to communicate with the engine when you press the 'play' button in the editor.
* 11MB of RAM used to store the translations.
* about 8MB used by the OpenGL shader cache (Not Godot code)
* about 8MB used by bullet

In 3.0 the debug buffer size was dramatically increased to improve stability when debugging larger projects so this by itself already accounts for 1/3rd of the memory use increase. We also now use a nicer font which is larger, which accounts for quite a bit. 

I'm not sure if this is really a problem all in all. Maybe we could shrink memory use a little bit but an exported game seems to not really use much more RAM than in 2.1

**Comment by akien-mga** [comment] 2017-12-20 21:33
> 11MB of RAM used to store the translations.

Does this include all languages? Since a restart is needed to change translations, we could maybe avoid store them all and just keep the current language (+ EN used as fallback).

**Comment by mhilbrunner** [comment] 2017-12-21 15:13
Using a recent master compiled with `scons platform=windows` uses 60mb RAM in project manager and 120mb RAM in a empty test project on Windows 7 x64.

**Comment by Web-eWorks** [comment] 2017-12-21 20:13
On godot 3 master as of about 15 minutes ago, I get ~300MB in the project manager (and 260+MB of GPU memory usage). [Detailed breakdown](https://hastebin.com/raw/najisiyeci) here.
On godot 2.14 (from the distro), I get ~50MB in the project manager (and ~37MB of GPU mem). [Detailed breakdown](https://hastebin.com/raw/itedexigoq) here.

**Comment by firefly2442** [comment] 2017-12-31 17:25
[cppcheck](http://cppcheck.sourceforge.net/) identified two memory leaks.  I'm not sure if they're valid, someone else with more experience should probably check.

In [os_iphone.cpp](https://github.com/godotengine/godot/blob/548bd4ef1d3528cd77dd8fb77be8de9a5d5d044f/platform/iphone/os_iphone.cpp#L591) it's reporting a memory leak on `new_ptr` after line 591.

In [memory.cpp](https://github.com/godotengine/godot/blob/548bd4ef1d3528cd77dd8fb77be8de9a5d5d044f/core/os/memory.cpp#L98) it's reporting a memory leak on `mem` after line 98.

Hope that helps.

**Comment by Scellow** [comment] 2018-07-20 06:11
I think i figured out what's wrong with memory usage

Try to run the .exe multiple times, sometimes it takes 70mb, sometimes 130mb

Maybe something doesn't have time to be freed during initialization ?

**Comment by Calinou** [comment] 2020-05-19 13:54
Many memory leaks have been fixed since this issue was created. Can anyone reproduce high RAM usage on Godot 3.2.1 or [3.2.2beta2](https://godotengine.org/article/dev-snapshot-godot-3-2-2-beta-2)?

Note that Godot 4's RAM requirements will likely increase, in the interest of offering better performance (more things can be cached this way).

**Comment by Calinou** [comment] 2020-06-19 08:15
Closing per the above comment.

**Closed by Calinou** 2020-06-19 08:15 UTC
Labels: discussion
