### ISSUE TITLE
GDScript 2.0: Cannot append null to TypedArray

### ISSUE THREAD

**Issue by Frostings** [godotengine/godot#67231] opened 2022-10-11 04:46 UTC
### Godot version

4.0.beta2

### System information

Windows 10

### Issue description

Cannot append null to TypedArray

### Steps to reproduce

```
var test: Array = []
test.append(null)
print(test) # prints [<null>] correctly

var test2: Array[Sprite2D] = [] # Can be any object type
test2.append(null)
print(test2) # prints []
```

**Comment by KoBeWi** [comment] 2022-10-11 10:55
Duplicate of #63608

**Closed by KoBeWi** 2022-10-11 10:55 UTC
