### ISSUE TITLE
Opacity won't affect Polygon2D

### ISSUE THREAD

**Issue by zoiba** [godotengine/godot#8187] opened 2017-03-28 14:32 UTC
**Operating system or device - Godot version:**
Ubuntu 16.04 - Godot 2.1.2

**Issue description:**
Opacity won't affect Polygon2D

**Steps to reproduce:**
create a Polygon2D node
draw a polygon
change the Opacity value
you can see polygon is still visible even if Opacity is set to 0

**Comment by eon-s** [comment] 2017-03-28 16:10
Duplicate of #5151
And you can somehow change image opacity but changing the alpha on polygon's color property (or adding colors to the vertices).

**Comment by bojidar-bg** [comment] 2017-03-28 17:09
Yeah, indeed a duplicate of #5151.

**Closed by bojidar-bg** 2017-03-28 17:09 UTC

**Comment by zoiba** [comment] 2017-03-28 17:32
sure you can use alpha but I have a project made with Godot 2.0 with tons of complex  animation that using Opacity, I have to edit each animation by hand to correct them, this is not very nice

**Comment by eon-s** [comment] 2017-03-28 17:43
@zoiba yes, there is a regression on 2.1 (mentioned on the other issue), seems to be related to the exposed vertices.
Maybe you can add a property on a script with the setter linked to the polygon alpha to make it easier until you decide to change all with the color directly.

It is supposed to be fixed on 3.0 but 2D stuff is still broken there.

**Comment by zoiba** [comment] 2017-03-28 17:54
I will try as you suggested, thank you
