### ISSUE TITLE
Glow in Softlight and Screen mode create artifacts.

### ISSUE THREAD

**Issue by n-pigeon** [godotengine/godot#9568] opened 2017-07-08 18:59 UTC
**Godot version: 3.0 master**

**Issue description:**
If you set Glow blending to Softlight or Screen skybox texture starts looking weird. Occasionally in some places reflections also look weird.

**Steps to reproduce:**
1. Add Environment Node with sky texture (or use Material Tester demo)
2. Turn on Glow
3. Change Glow blending to softlight or screen.

![selection_147](https://user-images.githubusercontent.com/6152134/27988353-461d7726-6420-11e7-85a4-b99dbe31f131.png)

**Comment by vnen** [comment] 2017-07-09 01:06
Duplicate of #9106.

**Closed by vnen** 2017-07-09 01:06 UTC
