### ISSUE TITLE
Error ld cannot find -lgabi++_static when compiling in windows 10

### ISSUE THREAD

**Issue by alexandersmak** [godotengine/godot#7982] opened 2017-03-08 08:03 UTC
c:/godot/tools/android-ndk-r14/toolchains/arm-linux-androideabi-4.8/prebuilt/windows-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld.exe: cannot find -lgabi++_static
collect2.exe: error: ld returned 1 exit status

=====
scons: *** [bin\libgodot.android.opt.armv7.neon.so] Error 1
scons: building terminated because of errors.

How to fix it ?

**Comment by bojidar-bg** [comment] 2017-03-08 10:37
Looks that there was some discussion over at https://github.com/godotengine/godot/issues/4081#issuecomment-198779847. Not sure if it would be of any help though.

**Comment by alexandersmak** [comment] 2017-03-10 17:16
it's useful. thanks you

**Comment by kubecz3k** [comment] 2018-04-10 17:13
First of all thank you for your report and sorry for the delay.

We released Godot 3.0 in January 2018 after 18 months of work, fixing many old issues either directly, or by obsoleting/replacing the features they were referring to.

We still have hundreds of issues whose relevance/reproducibility needs to be checked against the [current stable version](https://godotengine.org/download), and that's where you can help us.
**Could you check if the issue that you described initially is still relevant/reproducible in Godot 3.0 or any newer version, and comment about its current status here?**

For bug reports, please also make sure that the issue contains detailed steps to reproduce the bug and, if possible, a zipped project that can be used to reproduce it right away. This greatly speeds up debugging and bugfixing tasks for our contributors.

Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

Thanks in advance.

*Note: This message is being copy-pasted to many "stale" issues (90+ days without activity). It might happen that it is not meaningful for this specific issue or appears oblivious of the issue's context, if so please comment to notify the Bugsquad about it.*

**Comment by vnen** [comment] 2018-07-31 03:47
> Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

As there was no update since the previous post, we close this issue.

If it is still relevant in the way it was described and discussed above, please comment to ask for it to be reevaluated. If it is only partly relevant, or if the original issue has changed, it would be better to open a new issue (potentially referring to this one) focused on the current state.

**Closed by vnen** 2018-07-31 03:47 UTC
Labels: bug, platform:android, topic:buildsystem, topic:porting
