### ISSUE TITLE
[v3.4.beta2] GPU particles not emitted when `direction` is zero

### ISSUE THREAD

**Issue by Leocesar3D** [godotengine/godot#51043] opened 2021-07-30 01:57 UTC
### Godot version

v3.4.beta2

### System information

Windows 10, GLES3, Geforce 1070

### Issue description

Animated texture on Spacial material for particle system does not work. It worked fine in Godot v3.3.

### Steps to reproduce

Open the provided 3.4 project, it should display the animated particle system working, but it doesn’t.
It works fine on the provided Godot 3.3 project.

### Minimal reproduction project

[AnimatedParticleNotWorking.zip](https://github.com/godotengine/godot/files/6904643/AnimatedParticleNotWorking.zip)

**Comment by akien-mga** [comment] 2021-07-30 07:18
I can confirm the issue in latest `3.x` (bab9c02f472044415845ce284c55c961402c9c7c).

The problem seems to be that the particles material uses a zero `direction`. That doesn't seem to be a problem in 3.3 but in 3.4 that makes everything invisible.

That's probably a regression from #47310, CC @mortarroad.

**Comment by mortarroad** [comment] 2021-07-30 17:38
Up to you to decide if this is a bug.

According to <https://docs.godotengine.org/en/stable/classes/class_particlesmaterial.html#class-particlesmaterial-property-direction>, `direction` it is a _"Unit vector specifying the particles' emission direction."_

And (0, 0, 0) is not a unit vector.

Fixing this would go in the shader, and I would really like to keep the shader short. (Although we got several special cases already, one more might not hurt.)


But at least for 4.x, I wouldn't fix this.

**Comment by Calinou** [comment] 2021-07-30 18:04
I agree this should be fixed in `3.x` at least. Particles could be emitted upwards in this case.

**Comment by akien-mga** [comment] 2021-07-30 18:11
Shouldn't it be possible to emit particles in no specific direction? In which case a zero vector makes sense for this IMO, otherwise it would have to be a boolean toggle of some sort?

**Comment by Calinou** [comment] 2021-07-30 18:43
> Shouldn't it be possible to emit particles in no specific direction?

I think this is done by setting any direction and setting the initial velocity to 0.

**Comment by Leocesar3D** [comment] 2021-07-31 03:47
> Up to you to decide if this is a bug.
> 
> According to https://docs.godotengine.org/en/stable/classes/class_particlesmaterial.html#class-particlesmaterial-property-direction, `direction` it is a _"Unit vector specifying the particles' emission direction."_
> 
> And (0, 0, 0) is not a unit vector.
> 
> Fixing this would go in the shader, and I would really like to keep the shader short. (Although we got several special cases already, one more might not hurt.)
> 
> But at least for 4.x, I wouldn't fix this.

If the parameter expects values different than zero, the editor should reinforce it somehow, or do it internally, otherwise, on the user side, it looks like a bug.

**Comment by akien-mga** [comment] 2021-08-07 07:35
I think zero should be special cased as it doesn't make sense as a value for a direction vector. IMO it should behave the same (no velocity, no direction) if either velocity or direction are zero.

**Comment by mortarroad** [comment] 2021-08-07 15:23
> I think zero should be special cased as it doesn't make sense as a value for a direction vector. IMO it should behave the same (no velocity, no direction) if either velocity or direction are zero.

That would still be a regression, since we handled the zero vector differently in 3.3. (Although spread was a broken mess in 3.3 anyway.)


Anyway, this line is causing the issue:
https://github.com/godotengine/godot/blob/41cf7f27607d29946575877eb8bebdc2d892e78d/scene/resources/particles_material.cpp#L348

Apparently, normalizing a zero-vector causes a division by zero.

Could be changed to something like
`vec3 direction_nrm = length(direction) > 0.0 ? normalize(direction) : vec3(1.0, 0.0, 0.0);`

**Comment by akien-mga** [comment] 2021-08-12 10:49
Fixed by #51553.

**Closed by akien-mga** 2021-08-12 10:49 UTC
Labels: bug, confirmed, regression, topic:animation
