### ISSUE TITLE
Grid is not aligned with pixel art sprite

### ISSUE THREAD

**Issue by lorenzo-arena** [godotengine/godot#70961] opened 2023-01-05 18:04 UTC
### Godot version

4.0-beta10.mono

### System information

Windows 11, Ryzen 3700U Vega 10 iGPU

### Issue description

When using a grid with a step of 1 pixel with snap enabled, the grid presents a strange offset against pixel art assets.

### Steps to reproduce

- Create a new scene and add a sprite node
- Use this image as the texture for the sprite: ![background](https://user-images.githubusercontent.com/22166510/210849256-dec85028-b0cb-44ce-bba0-6a57483b6e21.png)
- Enable "Use Grid Snap"
- in the "Configure Snap.." menu set the grid steps as 1px

### Minimal reproduction project

N/A

**Comment by kleonc** [comment] 2023-01-05 18:19
Duplicate of #70186 (it's already fixed for the next version).

**Closed by kleonc** 2023-01-05 18:19 UTC
