### ISSUE TITLE
Emulate touch from mouse won't work with TouchScreenButton node

### ISSUE THREAD

**Issue by Gnumaru** [godotengine/godot#73457] opened 2023-02-16 19:45 UTC
### Godot version

4.0.rc2

### System information

windows 10

### Issue description

The "emulate touch from mouse" project setting has no effect when trying to click a TouchScreenButton node. It may be a problem specific to the TouchScreenButton node OR it may be the entire touch emulation that doesn't work, but I haven tested deeply enough to check this.

### Steps to reproduce

1. Turn on the "emulate touch from mouse" project setting
2. Create a TouchScreenButton
3. Connect the "pressed" and "released" signals to a function that prints something
4. Run the scene, try to press the button and notice how the methods connected to the pressed and released signals doesn't get called.

### Minimal reproduction project

[EmulateTouchFromMouseWontWork.zip](https://github.com/godotengine/godot/files/10760029/EmulateTouchFromMouseWontWork.zip)

**Comment by akien-mga** [comment] 2023-02-16 19:59
This appears to be a regression, it worked in 4.0 beta 17 and broke in RC 1.
I would suspect one of these RC 1 input PRs: https://github.com/godotengine/godot/pulls?q=is%3Apr+merged%3A2023-02-01T12%3A00..2023-02-08T11%3A00+is%3Amerged+sort%3Acreated-asc+milestone%3A4.0+label%3Atopic%3Ainput (CC @Sauermann @bruvzg)

**Comment by akien-mga** [comment] 2023-02-17 00:03
I confirmed that the regression is caused by #72740 @Sauermann.

**Comment by Sauermann** [comment] 2023-02-17 00:05
Yes, it is related to `TouchScreenButton::input`
``` c++
	if (p_event->get_device() != 0) {
		return;
	}
```
I'm trying to figure out the meaning of this restriction.

**Comment by RandomShaper** [comment] 2023-02-17 07:42
That check dates back to Godot 1.0, nine years ago! Unfortunately, the commit adding it won't give much context (https://github.com/godotengine/godot/commit/2ee4ac183babedd679e901b0158f5268556deceb.)

I can't see the point of that condition. I've checked the Godot 1.0 codebase and the `device` member would not be initialized mot of the time one touch event was created, so I even wonder how touch could work reliably on that release. Or didn't it?

In any case, the only thing that I can contribute as of now to this issue is that the check is just removed.

**Closed** 2023-02-17 13:00 UTC
Labels: bug, topic:input, regression
