### ISSUE TITLE
Code completion in editor replaces numerical assignments with code suggestions

### ISSUE THREAD

**Issue by FarbrorMartin** [godotengine/godot#74424] opened 2023-03-05 09:24 UTC
### Godot version

4.0-stable

### System information

Windows 10, Forward+, Intel HD 620

### Issue description

When typing numerical assignments in the editor the code completion replaces the number with some code suggestion matching the number.
![image](https://user-images.githubusercontent.com/36861435/222952148-b5a9b21d-428a-4417-a180-8693d5b398cc.png)
Typing the `-2` and pressing enter makes the editor replace the number with a code snippet:
![image](https://user-images.githubusercontent.com/36861435/222952278-6efe904a-e4fa-4be1-950b-02c8938ba605.png)

Note that this is even though I have typed the variable as Int (which I usually wouldn't do for internal variables like this).

The code completion often overrides what I have written when I press Enter.
It's consistently making the wrong completion, often even when I type it in again if I don't hit enter before the completion box pops up.

I have not encountered this in other IDE:s. 

### Steps to reproduce

Enter code like in my example.
Type in a new assignment of a number to the variable.

### Minimal reproduction project

N/A

**Comment by akien-mga** [comment] 2023-03-05 10:05
Duplicate of https://github.com/godotengine/godot/issues/72565

**Closed by akien-mga** 2023-03-05 10:05 UTC
