### ISSUE TITLE
#4.0.stable.mono/web_debug.zip and web_release.zip, they are not working.

### ISSUE THREAD

**Issue by giovanigsilva** [godotengine/godot#74887] opened 2023-03-14 00:05 UTC
### Godot version

4.0.stable.mono

### System information

Windows 10

### Issue description

The export templates are installed and ready to be used. However, they are not working.

### Steps to reproduce

install templates and export HTML

### Minimal reproduction project

![godot](https://user-images.githubusercontent.com/39173940/224858648-a5345bd4-6c3a-457f-8626-fa7ca45accbf.png)

**Comment by don1ck** [comment] 2023-03-19 12:55
Well, looks like its  a limitation right now:
https://godotengine.org/article/whats-new-in-csharp-for-godot-4-0/#mobile-and-web-support

**Comment by KoBeWi** [comment] 2023-03-20 00:00
Duplicate of #70796

**Closed by KoBeWi** 2023-03-20 00:00 UTC
