### ISSUE TITLE
Export variables initialized with Object type appear uninitialized in Inspector

### ISSUE THREAD

**Issue by xDGameStudios** [godotengine/godot#26632] opened 2019-03-05 13:03 UTC
**Godot version:**
godot 3.1 beta 10

**OS/device including version:**
Mac OSX Mojave and Windows

**Issue description:**
Resource variables that are exported initialized will still be uninitialized in the inspector... i.e:

<img width="944" alt="captura de ecra 2019-03-05 as 13 00 06" src="https://user-images.githubusercontent.com/10358443/53807220-e8f2d600-3f46-11e9-9646-083e42288e93.png">

**Steps to reproduce:**

`export(Animation) var anim = Animation.new();`

variable is not initialized in the inspector.

**Comment by willnationsdev** [comment] 2019-03-05 13:37
Does this still happen if the `_init()` method initializes the value?

**Comment by xDGameStudios** [comment] 2019-03-05 13:40
> Does this still happen if the `_init()` method initializes the value?

Yeah :(

**Comment by tom-jk** [comment] 2020-07-19 17:01
Can sort-of reproduce on 3.2.2.stable on linux mint 18.3.

The field in the inspector is initially empty. But it _is_ correctly populated once the scene is reloaded (which is a recurring theme generally with tool scripts).

convenience project: [26632.zip](https://github.com/godotengine/godot/files/4944096/26632.zip)

**Comment by akien-mga** [comment] 2021-04-28 13:17
This is fixed in 4.0.

And sort-of duplicate of #37464 for 3.x, you have to notify the editor that values are being updated in a tool script.

**Closed by akien-mga** 2021-04-28 13:17 UTC
Labels: bug, topic:editor, topic:gdscript
