### ISSUE TITLE
Unable to perform operations after tooltip is displayed in Editor.

### ISSUE THREAD

**Issue by tokengamedev** [godotengine/godot#78313] opened 2023-06-16 06:30 UTC
### Godot version

4.0.3, 4.1.beta 2

### System information

Windows 11

### Issue description

Unable to perform any operation after tooltip is displayed on an editable field like text box or check box. 
You can perform the operation only when you dismiss the tooltip by clicking outside of tooltip.

Example when you try to toggle values in debug menus in editor. shown in the video below.

https://github.com/godotengine/godot/assets/84369217/b237b241-1a79-4e16-a670-12fb7170f6d6

It is trivial at first look but becomes obstructive when you are copy pasting color values in the color editor using hotkeys.

### Steps to reproduce

Example 1:
Open the debug menu in the editor and just hover over one of the editable menus till the tooltip comes up, 
after the tooltip is displayed moving the mouse will not highlight menus anymore until the tool tips is dismissed.

Example 2:
Copy a text value from any source(outside or inside of the editor).
Now open the color editor like one in ColorRect Color property
Hover the mouse over the editor and wait till the Tooltip is displayed.
Now try to paste using shortcut  Ctrl + V in windows. It will not work. 
but dismiss the tooltip, you can paste.

Even you cannot edit like pressing backspace or typing letters.

### Minimal reproduction project

N.A

**Comment by Chaosus** [comment] 2023-06-16 06:41
It's a trivial (and annoying) bug, reported several times in different forms in the past (need to find a proper duplicate, tho). You can use arrow keys and Enter to bypass it for now.

**Comment by Calinou** [comment] 2023-06-16 06:51
> It's a trivial (and annoying) bug, reported several times in different forms in the past (need to find a proper duplicate, tho). You can use arrow keys and Enter to bypass it for now.

By the way, I've noticed that pressing <kbd>Escape</kbd> doesn't dismiss the currently displayed tooltip like it does in Firefox or Dolphin (KDE).

**Comment by tokengamedev** [comment] 2023-06-16 09:07
Ideally on mouse exit the tooltip should close. It is working fine in most controls of inspector.
This seems to me like an isolated case after reviewing again.
Listing down the places where it is problematic.
1. Debug menu items in Menu
2. Editable box of color dialog

**Comment by Sauermann** [comment] 2023-06-17 15:55
Looks like a duplicate of #73926

**Comment by Calinou** [comment] 2023-06-17 17:47
Thanks for the report! Consolidating in https://github.com/godotengine/godot/issues/73926.

**Closed by Calinou** 2023-06-17 17:47 UTC
Labels: bug, platform:windows, topic:porting
