### ISSUE TITLE
AnimationPlayer signals are not emitting when animations played from AnimationTree

### ISSUE THREAD

**Issue by Calamander** [godotengine/godot#28311] opened 2019-04-22 19:26 UTC
***Bugsquad edit:** This issue has been confirmed several times already. No need to confirm it further.*

___

**Godot version:**
3.1 stable

**OS/device including version:**
Windows 10 Pro 1809

**Issue description:**
AnimationPlayer animations signals are not firing when animation played from within any AnimationTree node. I assume this is a bug, since AnimationPlayer directly attached to AnimationTree and AnimationTree doesn't have it's own signals controlling animation flow, so if tree is complex enough it becomes impossible to control it without signals.
I'm very confised since it is very important part of functionality but I couldn't find anyone bothered by its absence so I thought maybe I'm misunderstanding something, but couldn't find any solution so far.
#8521

**Steps to reproduce:**
Create (looping or not) animation in AnimationPlayer.
Create AnimationTree, assign AnimationPlayer to it. Inside AnimationTree (AnimationNodeBlendTree for ex) create Animation Node and connect it to output or any other combination. Activate AnimationTree, run.

**Minimal reproduction project:**
[Test.zip](https://github.com/godotengine/godot/files/3104586/Test.zip)
Enabling "autostart" on timer will allow signals emitting, since animations played directly from AnimationPlayer, indicating that it is perfectly fine by itself.

**Comment by JU-2094** [comment] 2019-05-26 04:33
I had the same problem. I solved it by adding a callback in the animation. In your animation add the track for functions callback. Then you set the track key, and specify the name of the callback.

**Comment by Calamander** [comment] 2019-05-26 15:45
> I had the same problem. I solved it by adding a callback in the animation. In your animation add the track for functions callback. Then you set the track key, and specify the name of the callback.

Yeah, I did it too, but the problem here is if function key too close to 0 or end of animation - it is sometimes not triggering so you have to move it +/- dozen milliseconds on animation timeline which makes timing animation even more cumbersome, even though I used the most simple animations, without any blending or time scaling/seeking.

**Comment by Rodeo-McCabe** [comment] 2019-07-06 14:52
I can confirm this bug is present on Linux as well (Manjaro).

Unfortunately, the above workaround is not possible for me, since the function I need to call is in a script attached to an AnimationNode inside the AnimationTree. When creating a call method track, you can only select nodes which are displayed in the scene dock, and AnimationNodes inside an AnimationTree are not displayed.

**Comment by mateusbds** [comment] 2020-02-16 14:10
I'm having this same problem in godot 3.2

**Comment by Rodeo-McCabe** [comment] 2020-03-02 16:44
@mateusbds https://github.com/godotengine/godot/pull/30508/files might be of interest to you.

**Comment by smks** [comment] 2020-04-26 17:49
Same problem for me...

**Comment by vvinhas** [comment] 2020-05-14 03:44
Same here

**Comment by JoshMooney** [comment] 2020-05-25 14:53
Seeing this issue atm as well.

**Comment by metcalf-putnam** [comment] 2020-06-26 15:19
Also having this issue, but this workaround worked like a charm for my use case: https://amp.reddit.com/r/godot/comments/7lsrga/animationtreeplayer_detecting_when_an_animation/

**Comment by metcalf-putnam** [comment] 2020-06-26 15:21
Also having this issue, but this workaround worked like a charm for my use case (adding call method tracks to the animation(s) in question): https://amp.reddit.com/r/godot/comments/7lsrga/animationtreeplayer_detecting_when_an_animation/

**Comment by sstelfox** [comment] 2020-09-27 03:00
Just hit this as well. The explicit "Call Method Track" to a node won't work for my specific use case as the target is dynamically created by a GdNative library.

**Comment by Azumist** [comment] 2020-11-18 03:29
Same issue. Resolved it by using timers and setting wait_time to animation length, but it's a very makeshift solution.

**Comment by fracteed** [comment] 2021-01-07 03:54
Damn, I am running into all sorts of issues with this limitation. You can't even get the current animation or position being played from the animation tree. None of the methods or signals from the animation player work when using a tree.

The timer workaround is not suitable if you have animations that blend in and out at different ramped speeds. The function track is not really suitable if you are importing gltf animations, but makes sense if your animations are created in Godot itself.

Hopefully there is a dev working on patch for this, as it is very difficult to work around!

**Comment by Gagege** [comment] 2021-03-07 06:15
Is there currently any other way to dynamically blend animations at runtime?

**Comment by Rodeo-McCabe** [comment] 2021-03-13 02:31
Why are those comments being marked as off-topic? They are other users that are confirming the issue, it's perfectly on topic.

**Comment by Rodeo-McCabe** [comment] 2021-03-20 17:09
Commenting to link this relevant issue and pull request:

https://github.com/godotengine/godot-proposals/issues/1462#issue-693602370  
#41771  

Possibly a better solution overall, since it means we don't have implement our own state machine to effectively use the built in state machine ....

**Comment by TokageItLab** [comment] 2021-05-24 19:18
@Rodeo-McCabe said #41771 is a solution to this, but this PR is only useful when using `AnimationStateMachine`, so feels insufficient such as in the case of `AnimationTree` calling animations with `NodeOneshot`.

**Comment by abumbalough** [comment] 2022-07-05 22:09
Confirming that I have the same issue when using AnimationPlayer from AnimationTree in 3.4.4.stable

**Comment by TokageItLab** [comment] 2022-07-05 22:35
AnimationTree only reads AnimationPlayer animations, it does not play the AnimationPlayer.

By the way, I remember @reduz and I were talking about AnimationTree loading animations from the Animation library.

There is also a fundamental problem with emitting signals from AnimationBlendTree's NodeAnimation and getting their playback position. This is because the AnimationTree is a node, but the AnimationBlendTree is a resource and can be referenced by multiple nodes.

So, if that is what you need, we will need to implement the signal correctly on the AnimationTree side.

**Comment by lufog** [comment] 2022-12-01 19:45
> AnimationTree only reads AnimationPlayer animations, it does not play the AnimationPlayer.

I always thought that `AnimationTree` was some kind of add-on to `AnimationPlayer`. And wondered why my
```gdscript
await animation_player.animation_finished
```
didn't work, when I used AnimationTree.

> By the way, I remember @reduz and I were talking about AnimationTree loading animations from the AnimationLibrary directly.

If the AnimationTree only uses animations from the AnimationPlayer and nothing else. It really makes sense to put them in a separate resource. To avoid similar confusion in the future. And remove the extra node from the scene tree.

**Closed** 2022-12-23 08:12 UTC
Labels: bug, confirmed, topic:animation
