### ISSUE TITLE
C# Custom Resource don't save changes

### ISSUE THREAD

**Issue by TvoyBatek** [godotengine/godot#35109] opened 2020-01-14 04:41 UTC
**Godot version:**
Godot Engine v3.2.beta6.mono.official

**OS/device including version:**
Windows 10

**Issue description:**
GDScript dont save changes in custom C# resources.

**Steps to reproduce:**
Create custom C# resource with export variable, change variable value, save resource, open it by GDScript, change value save/create new by ResourceSaver.save(). Open again resource - value dont changed.
PS. Excuse my English.

**Minimal reproduction project:**
[project.zip](https://github.com/godotengine/godot/files/4057354/project.zip)

**Comment by clayjohn** [comment] 2020-01-16 06:34
Duplicate of https://github.com/godotengine/godot/issues/24896

Please search existing issues before creating anew one.

**Closed by clayjohn** 2020-01-16 06:34 UTC
Labels: archived
