### ISSUE TITLE
Pool*Array instances should be references and not values in GDscript

### ISSUE THREAD

**Issue by ficoos** [godotengine/godot#8409] opened 2017-04-14 14:56 UTC
**Operating system or device - Godot version:**

**Issue description:**
Calling PoolStringArray.push_back() sometimes silently does nothing.

**Steps to reproduce:**

```gdscript
extends Node

class B:
	static func do_something_else(a):
		a.arr.push_back("I'm B")

class A:
	var arr = PoolStringArray()

	func do_something():
		arr.push_back("PRE")
		B.do_something_else(self)
		arr.push_back("POST")
		print(arr)

func _ready():
	var a = A.new()
	a.do_something()
```

outputs [PRE, POST] instead of [PRE, I'm B, POST]

**Link to minimal example project:**

**Comment by ficoos** [comment] 2017-04-14 16:34
OK, did some digging the problem seems to be that `void Variant::reference(const Variant &p_variant)` just doesn't work as advertised. It actually invokes copy constructors.
The only reason it works is because types are either immutable (int, float) don't have methods that modify them just members (this doesn't create a new variant) (Vector2) or have copy constructors that don't copy but create reference so you actually (String, Dictionary).
PoolVector actually does COW (regular Vector doesn't) so during resize it copies the internal data in the copy.

I think @reduz needs to way in on this.
IMHO I don't think that copy constructors should be used like this. This creates a lot of places that do reference count for their internal state. This is why smart pointers exist.

**Comment by ficoos** [comment] 2017-05-09 19:11
OK, After understanding a bit more.
The issues is that Pool*Array are native Variant types (note Object or Ref) this means that they are values. This means that they are copied on assignment (like Vector, Int, String, ...)

I don't think it's they should be values for them as Array and Dictionary are not Values.
Changing the title to reflect this

**Comment by Zylann** [comment] 2017-07-18 23:36
Just found this oddity as well, thankfully I was aware of other COW things but I thought they were due to be removed in GDScript for 3.0?

In Godot 2.1.3 and 3.0 master, the following test is a fail:

```gdscript
func _ready():
	test()

static func lol(a):
	a.resize(42)

static func test():
	var a = PoolVector3Array()
	lol(a)
	assert(a.size() == 42)
	print("Test succeeded ", a.size())
```

Context: I found this because I was using PoolArrays to use the Mesh API.

**Comment by reduz** [comment] 2017-08-06 13:47
those are often sent to other threads and require locking for manipulation, so making them share data can lead to unexpected behavior. A solution may be to use an internal variant reference counter and making them shared only in GDScript..

**Comment by Zylann** [comment] 2017-08-06 13:56
What about GDNative scripts that do mesh generation? Those also have to give PoolArrays back to Godot, but they can't lock them for performance AFAIK.

**Comment by reduz** [comment] 2017-08-06 14:18
Zylann It should be perfectly possible to lock them in GDNative, would need to ask Karroffel to implement it

**Comment by reduz** [comment] 2017-08-15 19:38
Still undecided on this, so kicking to 3.1

**Comment by garyo** [comment] 2018-04-02 14:32
I've run afoul of this as well, just as a data point. Exposing a lock/unlock method so you can get mutable references in GDscript/GDNative would be one way? Seems pretty important to be able to get a reference to a PoolArray somehow.

**Comment by Zylann** [comment] 2018-04-02 14:38
Read/write locks have been exposed to GDNative, but GDScript still doesn't have it (it's important to remember that even if GDScript doesn't touch them, it may pass them around quite often!)

**Comment by reduz** [comment] 2018-07-30 18:34
I still think these should be reference counted when inside of variant and shared (but not by themselves when passing to a function). This is considerable amount of work to change, though so for now will kick to 3.1 unless anyone wants to do it.

**Comment by avencherus** [comment] 2019-01-24 13:39
Also ran into this with dictionaries.

```gdscript
extends Node2D

func _ready():
	
	var dict = {
		vecs = PoolVector2Array()
	}
	
	print(dict.vecs)
	dict.vecs.append(Vector2())
	print(dict.vecs)
```
![image](https://user-images.githubusercontent.com/13004169/51681723-2e3df280-1fee-11e9-9606-3699934aad39.png)

**Comment by reduz** [comment] 2019-01-24 14:09
This is scheduled to change after 3.1 is out.

**Comment by Calinou** [comment] 2020-03-27 09:41
Is this still an issue with Packed*Array? cc @reduz

**Comment by akien-mga** [comment] 2020-03-27 10:14
Yes this is fixed by #36311.

**Closed by akien-mga** 2020-03-27 10:14 UTC
Labels: breaks compat, bug, topic:core

**Comment by Xrayez** [comment] 2020-05-01 15:53
In some cases this doesn't work:
```gdscript
func _ready():
	var p2d = Polygon2D.new()
	var polygon = PackedVector2Array([Vector2(0, 0), Vector2(100, 0), Vector2(100, 100), Vector2(0, 100)])

	p2d.polygon = polygon
	print(p2d.polygon)
	p2d.polygon.push_back(Vector2(213, 123))
	print(p2d.polygon) # same as `polygon`

#	var poly_copy = polygon
#	poly_copy.push_back(Vector2(213, 123))
#	p2d.polygon = poly_copy
```

But It does work with dictionaries as described above.

**Comment by sarchar** [comment] 2021-05-28 13:17
I have stumbled upon a similar bug and curious if this is also related:

```
func _ready():
	var arr = [1, 2, 3, 4]
	var pba = PoolByteArray(arr)
	var buf = StreamPeerBuffer.new()
	buf.data_array = pba
	var data = buf.get_data(4)
	print(data[1].hex_encode())
	data[1].invert()
	print(data[1].hex_encode())
```

prints:
```
01020304
01020304
```

however,

```
func _ready():
	var arr = [1, 2, 3, 4]
	var pba = PoolByteArray(arr)
	var buf = StreamPeerBuffer.new()
	buf.data_array = pba
	var data = buf.get_data(4)
	var copy = data[1]
	print(copy.hex_encode())
	copy.invert()
	print(copy.hex_encode())
```

prints

```
01020304
04030201
```
