### ISSUE TITLE
Commenting multi-line code may lead to unnecessary warning

### ISSUE THREAD

**Issue by roipoussiere** [godotengine/godot#33687] opened 2019-11-17 22:48 UTC
**Godot version:**

3.1.1 stable

**OS/device including version:**

Kubuntu

**Issue description:**

Commenting multi-line code may lead to unnecessary warning.

**Steps to reproduce:**

Type some code with multil-ine code:

```gd
func new_issue():
    if 'Roses' == 'blue' \
    and 'Violets' == 'blue' \
    and 'Sugar' == 'sweet':
        print('And so are you.')
```

![image](https://user-images.githubusercontent.com/1665542/69015418-e8468680-0993-11ea-8f8c-2079e748c7b3.png)

Then comment some line(s) inside:

```gd
func new_issue():
    if 'Roses' == 'blue' \
#    and 'Violets' == 'blue' \
    and 'Sugar' == 'sweet':
        print('And so are you.')
```

![image](https://user-images.githubusercontent.com/1665542/69015473-74f14480-0994-11ea-8ec2-1bca89b42cd9.png)

As you can see, this produces a red warning, even if the code without this line is syntactically correct.

**Comment by Calinou** [comment] 2019-11-17 22:58
Using parentheses to wrap a statement over multiple lines should avoid this issue, while being generally easier to refactor:

```gdscript
func new_issue():
    if (
        'Roses' == 'blue'
#        and 'Violets' == 'blue'
        and 'Sugar' == 'sweet'
    ):
        print('And so are you.')
```

**Comment by name-here** [comment] 2019-11-18 03:42
Fixing it would also allow you to avoid the frown at the end of your if statement.

**Comment by fsy98** [comment] 2019-11-24 01:38
Actually, this problem is because colon missing at the end of if - or func-line, so the next line will confused and show the mistake in the degugger. For C and C++ the syntax you give is ok, but for godoot make some problem like python.

**Comment by ThakeeNathees** [comment] 2020-03-10 11:35
I don't think that it's a bug, its an expected behavior the symbol "\" means just skip the next new line character 

in python
```python
if True and True\
## comment
    or False:
    print("test")

## output error
 File "test.py", line 3
    ## comment
            ^
SyntaxError: invalid syntax
```

in c++
```c++
#define TEST                       \
	if (true){                   \
		// comment
		print_line("test");   \
	}
// this is also an invalid define macro
```

**Comment by KoBeWi** [comment] 2020-12-17 00:27
Closing as per above comment.

**Closed by KoBeWi** 2020-12-17 00:27 UTC
Labels: bug, topic:gdscript
