### ISSUE TITLE
TEXTURE_PIXEL_SIZE not working for PlaceHolderTexture and ColorRect

### ISSUE THREAD

**Issue by alazifk** [godotengine/godot#84136] opened 2023-10-29 10:17 UTC
### Godot version

v4.1.2.stable.official [399c9dc39]

### System information

v4.1.2.stable.official [399c9dc39] Windows

### Issue description

TEXTURE_PIXEL_SIZE does just use the default value `4` and does not consider the size of a placeholder texture.
I also think it would be nice (if possible) if ColorRect could use the `transform.size` as the texture size because then you could change its size in the editor by dragging.

### Steps to reproduce

see the minimal reproduction project

### Minimal reproduction project

[texture_pixel_size.zip](https://github.com/godotengine/godot/files/13197763/texture_pixel_size.zip)

**Comment by arkology** [comment] 2023-10-29 11:39
There was another similar issue about PlaceholderTexture2D. It was closed as expected behaviour with addition of the following note to [documentation](https://docs.godotengine.org/en/stable/classes/class_placeholdertexture2d.html):
`Note: This is not intended to be used as an actual texture for rendering. It is not guaranteed to work like one in shaders or materials (for example when calculating UV).`

**Comment by AThousandShips** [comment] 2023-10-29 11:45
Duplicate of https://github.com/godotengine/godot/issues/65165

**Closed by AThousandShips** 2023-10-29 11:45 UTC
