### ISSUE TITLE
Creating a Camera node crashes Godot

### ISSUE THREAD

**Issue by ghost** [godotengine/godot#9682] opened 2017-07-18 01:24 UTC
**Windows 7 - Godot version: 2.1.4**

**Issue description:**
Simply put, creating or switching a node to be a Camera node crashes Godot.
Also happens with the InterpolatedCamera node.

**Comment by eon-s** [comment] 2017-07-18 02:43
I can't reproduce on the 2.1.4b "official" build on Ubuntu 17.04.

**Comment by Hassan-A** [comment] 2017-08-02 22:27
Windows 10 - can't reproduce on 2.1.4

**Comment by RandomShaper** [comment] 2017-08-03 07:36
Can you give more details? Does it happen under a specific scene setup?

**Comment by Mudley** [comment] 2017-08-03 15:31
Just creating the camera, nothing more.

The PC uses Intel HD Graphics 2500, if it helps in anything.

**Comment by Zireael07** [comment] 2017-08-03 15:38
@Mudley: What OpenGL version does your card support? I have a sneaking suspicion it's too weak for 3d stuff

**Comment by Mudley** [comment] 2017-08-03 15:51
@Zireael07 I don't think that's the problem, before downgrading from Windows 10, it used to work fine.

**Comment by Zireael07** [comment] 2017-08-03 16:36
Hmm, maybe Win10 installed some Win10-only drivers that are now acting up because it's no longer Win10?

**Comment by eon-s** [comment] 2017-08-03 18:57
Check the latest drivers from the official Intel site.

**Comment by akien-mga** [comment] 2018-09-17 14:08
Nobody could reproduce it, closing.

**Closed by akien-mga** 2018-09-17 14:08 UTC
Labels: bug, topic:editor
