### ISSUE TITLE
Error '12' when exporting for Android from headless systems (CI)

### ISSUE THREAD

**Issue by Filius-Patris** [godotengine/godot#38120] opened 2020-04-22 19:54 UTC
**Godot version:**
3.2.1 stable headless

**OS/device including version:**
Ubuntu 18.04 ([GitHub virtual environment](https://help.github.com/en/actions/reference/virtual-environments-for-github-hosted-runners#supported-runners-and-hardware-resources))
Installed Software: https://github.com/actions/virtual-environments/blob/master/images/linux/Ubuntu1804-README.md

**Issue description:**
Exporting to Android from commandline (without setting up via GUI before) is broken.
I think I have used every bit of relevant advice I've found and I still get this error message:
```
ERROR: _fs_changed: Project export failed with error code 12 for preset 'android'.
```
(More detailed logs are availible [here](https://github.com/Filius-Patris/godot-android-test/runs/609907928?check_suite_focus=true#step:7:82)).This is unfortunate for CI/CD systems.

**Steps to reproduce:**
 - New project
 - Add an android configuration
 - Try every possible way of running it on a clean system without ever touching a GUI (the environment a CI script would have to operate in)

**Minimal reproduction project:**
Take a look at https://github.com/Filius-Patris/godot-android-test. It has some test CI runs. The line of interest is [here](https://github.com/Filius-Patris/godot-android-test/runs/609907928?check_suite_focus=true#step:7:82).

I would really like to help to fix, but I have no experience in hacking the engine at all. If someone could point me into the right direction (eg, what does '12' mean), I'd may be able to help.

Also if I have made a mistake, or you'd like to try something with the CI pipeline, feel free to open a PR to the sample repo.

**Comment by Filius-Patris** [comment] 2020-04-22 20:11
It might however be an error on my side. Turns out for some reason I couldn't get rid of the empty default editor export settings.

See: https://github.com/Filius-Patris/godot-android-test/runs/609864630?check_suite_focus=true#step:6:269

I'll try to get my `sed` commands straight, but let me grumble about the horrible CLI for Godot in the meantime.

**Comment by Filius-Patris** [comment] 2020-04-22 20:25
My `sed` commands were not the issue. The same error still persists but the file is now as I'd like it to be.

Anyway, I DID once forget to set the paths and the error message is different (way clearer that error '12').

**Comment by aaronfranke** [comment] 2020-04-23 00:46
IIRC, this is a problem that affects exporting for any platform, not just Android, and it is a problem because the export system has to show a window. This should be fixed when 4.0 comes out with the DisplayServer and OS split, so we can hopefully export without showing any window.

**Comment by tommywalkie** [comment] 2020-04-24 11:58
@Filius-Patris Related with https://github.com/godotengine/godot/issues/29385. 
A few participants, including me, got the same error outputs, always before the `jarsigner` step. However one of them said he still manages to generate an APK with a [certain Dockerfile](https://github.com/tommywalkie/sample-godot-rust-app/blob/master/dockerfiles/godot-ci.Dockerfile) that looks correct to me but [I still get the same errors](https://github.com/tommywalkie/sample-godot-rust-app/runs/609566748?check_suite_focus=true#step:12:103) and no APK is being generated.

**Comment by Calinou** [comment] 2020-04-24 12:30
Duplicate of #29385.

**Closed by Calinou** 2020-04-24 12:30 UTC
Labels: bug, platform:android, topic:buildsystem

**Comment by Filius-Patris** [comment] 2020-04-24 14:04
Yup, fix worked. TLDR for future readers:
Try `--export-debug`. See [Calinou's comment](https://github.com/godotengine/godot/issues/29385#issuecomment-618984868).
Thanks!
