### ISSUE TITLE
[3.2.4 RC3] _set_size: Adjusting the size of Control nodes before they are fully initialized is unreliable.

### ISSUE THREAD

**Issue by daveTheOldCoder** [godotengine/godot#46765] opened 2021-03-07 16:54 UTC
I'm not sure whether this a bug. If it is, I can provide more details on request.

In a signal handler function, I'm setting a Control's rect_size.x:
$Bar.rect_size.x = 72 * player.health / player.health_max

That results in the warning message:
_set_size: Adjusting the size of Control nodes before they are fully initialized is unreliable. Consider deferring it with set_deferred().

I've taken precautions, i.e. using call_deferred(), to ensure that the signal is not emitted before the node is initialized. The project runs properly.

The warning message does not occur when the same project is run under version 3.2.3.

**Comment by Calinou** [comment] 2021-03-07 17:18
The warning was added here: https://github.com/godotengine/godot/pull/42427

It's known to be too eager though, so it's being fixed here: https://github.com/godotengine/godot/pull/46482

**Comment by KoBeWi** [comment] 2021-03-07 23:50
This is somewhat duplicate of #46376
The problematic PR was already reverted on 3.2 branch, so this will be fixed in rc4.

**Closed by KoBeWi** 2021-03-07 23:50 UTC
Labels: bug, regression, topic:gui
