### ISSUE TITLE
Editor crashes after laptop wake up from sleep

### ISSUE THREAD

**Issue by hakro** [godotengine/godot#99835] opened 2024-11-29 13:40 UTC
### Tested versions

- Reproducible in master (https://github.com/godotengine/godot/commit/0eadbdb5d0709e4e557e52377fa075d3e2f0ad1f)
- Not reproducible in 4.3 stable.

### System information

Godot v4.4.dev (0eadbdb5d) - TUXEDO OS 24.04.1 LTS on Wayland - X11 display driver, Multi-window, 2 monitors - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 4060 Laptop GPU, Driver version : Driver Version: 560.35.03  - 13th Gen Intel(R) Core(TM) i7-13700H (20 threads), KDE 6.2.3

### Issue description

The editor breaks when going out of sleep mode. Symptoms include, either Godot showing a black screen, along with any additional editor windows open, or a complete hard crash, with the following report : 

```
================================================================
handle_crash: Program crashed with signal 11
Engine version: Godot Engine v4.4.dev.custom_build (0eadbdb5d0709e4e557e52377fa075d3e2f0ad1f)
Dumping the backtrace. Please include this when reporting the bug to the project developer.
[1] /lib/x86_64-linux-gnu/libc.so.6(+0x45320) [0x733dd8645320] (??:0)
[2] /lib/x86_64-linux-gnu/libnvidia-glcore.so.560.35.03(+0xaf5ad7) [0x733dc10f5ad7] (??:0)
[3] /lib/x86_64-linux-gnu/libnvidia-glcore.so.560.35.03(+0x9f407e) [0x733dc0ff407e] (??:0)
[4] /lib/x86_64-linux-gnu/libnvidia-glcore.so.560.35.03(+0xac812e) [0x733dc10c812e] (??:0)
[5] /lib/x86_64-linux-gnu/libnvidia-glcore.so.560.35.03(+0xabc72f) [0x733dc10bc72f] (??:0)
[6] /lib/x86_64-linux-gnu/libnvidia-glcore.so.560.35.03(+0xd10131) [0x733dc1310131] (??:0)
[7] /lib/x86_64-linux-gnu/libnvidia-glcore.so.560.35.03(+0xe68e42) [0x733dc1468e42] (??:0)
[8] RenderingDeviceDriverVulkan::command_queue_execute_and_present(RenderingDeviceDriver::CommandQueueID, VectorView<RenderingDeviceDriver::SemaphoreID>, VectorView<RenderingDeviceDriver::CommandBufferID>, VectorView<RenderingDeviceDriver::SemaphoreID>, RenderingDeviceDriver::FenceID, VectorView<RenderingDeviceDriver::SwapChainID>) (/home/hakro/Projects/godot/drivers/vulkan/rendering_device_driver_vulkan.cpp:2582)
[9] RenderingDevice::_execute_frame(bool) (/home/hakro/Projects/godot/servers/rendering/rendering_device.cpp:5970)
[10] RenderingDevice::swap_buffers() (/home/hakro/Projects/godot/servers/rendering/rendering_device.cpp:5736)
[11] RendererCompositorRD::end_frame(bool) (/home/hakro/Projects/godot/servers/rendering/renderer_rd/renderer_compositor_rd.cpp:119)
[12] RenderingServerDefault::_draw(bool, double) (/home/hakro/Projects/godot/servers/rendering/rendering_server_default.cpp:93)
[13] RenderingServerDefault::draw(bool, double) (/home/hakro/Projects/godot/servers/rendering/rendering_server_default.cpp:419)
[14] Main::iteration() (/home/hakro/Projects/godot/main/main.cpp:4439)
[15] OS_LinuxBSD::run() (/home/hakro/Projects/godot/platform/linuxbsd/os_linuxbsd.cpp:962)
[16] bin/godot.linuxbsd.editor.dev.x86_64.llvm(main+0x18e) [0x60d2ce0b8a3e] (/home/hakro/Projects/godot/platform/linuxbsd/godot_linuxbsd.cpp:86)
[17] /lib/x86_64-linux-gnu/libc.so.6(+0x2a1ca) [0x733dd862a1ca] (??:0)
[18] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0x8b) [0x733dd862a28b] (??:0)
[19] bin/godot.linuxbsd.editor.dev.x86_64.llvm(_start+0x25) [0x60d2ce0b87e5] (??:?)
-- END OF BACKTRACE --
================================================================
Aborted
```

I tried other graphical software, Blender, Krita, Inkscape, and even Godot 4.3, but they were all working fine after wake up.
So it doesn't seem like it's a driver problem, but rather Godot master not playing nice with drivers.

### Steps to reproduce

- Open Godot, optionally open some sub-windows, like the `Project Settings`
- Get your computer into sleep mode
- Wake it up
- Editor shows a black screen or crashes

### Minimal reproduction project (MRP)

No need

**Comment by akien-mga** [comment] 2024-11-29 14:35
Can you try intermediate dev snapshots to pinpoint the first one that regressed?

And if you're feeling brave, bisect further between those two snapshots to find the regression commit?

**Comment by hakro** [comment] 2024-11-29 19:09
Alright, so when I tested earlier with 4.3 and it worked, I think I was just luck, or I might just have tested on a different project using the compatibility renderer.

I went back all the way to 4.0, and I had the same issue. 

But I tested all 3 renderers, and this seems to happen only on F+ and Mobile, but Compatibility renderer works just fine.

**Comment by AThousandShips** [comment] 2024-11-29 19:13
Possibly related:
* https://github.com/godotengine/godot/issues/87394
* https://github.com/godotengine/godot/issues/93388
* https://github.com/godotengine/godot/issues/85351

**Comment by akien-mga** [comment] 2024-11-29 21:06
Duplicate of #52738 which is documented here:
https://docs.godotengine.org/en/stable/tutorials/troubleshooting.html#the-editor-project-freezes-or-displays-glitched-visuals-after-resuming-the-pc-from-suspend

**Closed by akien-mga** 2024-11-29 21:06 UTC
Labels: bug, platform:linuxbsd, topic:rendering
