### ISSUE TITLE
[c#] Throw `NullReferenceException` when Serialize Signal Delegate On Tool Script

### ISSUE THREAD

**Issue by aidenmx** [godotengine/godot#66863] opened 2022-10-04 05:22 UTC
### Godot version

v4.0.beta2.mono.official [f8745f2f7]

### System information

Windows11

### Issue description

Godot Console show this Error When build c# project in editor, Build Passed:
```
 modules/mono/glue/runtime_interop.cpp:1233 - System.NullReferenceException: Object reference not set to an instance of an object.
     at Godot.DelegateUtils.TrySerializeSingleDelegate(Delegate delegate, Byte[]& buffer) in /root/godot/modules/mono/glue/GodotSharp/GodotSharp/Core/DelegateUtils.cs:line 113
     at Godot.DelegateUtils.TrySerializeDelegate(Delegate delegate, Array serializedData) in /root/godot/modules/mono/glue/GodotSharp/GodotSharp/Core/DelegateUtils.cs:line 100
     at Godot.Bridge.GodotSerializationInfo.AddSignalEventDelegate(StringName name, Delegate eventDelegate) in /root/godot/modules/mono/glue/GodotSharp/GodotSharp/Core/Bridge/GodotSerializationInfo.cs:line 47
     at TestScript.SaveGodotObjectData(GodotSerializationInfo info) in D:\Project\godot\Test\Godot.SourceGenerators\Godot.SourceGenerators.ScriptSerializationGenerator\TestScript_ScriptSerialization_Generated.cs:line 9
     at Godot.Bridge.CSharpInstanceBridge.SerializeState(IntPtr godotObjectGCHandle, godot_dictionary* propertiesState, godot_dictionary* signalEventsState) in /root/godot/modules/mono/glue/GodotSharp/GodotSharp/Core/Bridge/CSharpInstanceBridge.cs:line 212
```
`TestScript_ScriptSerialization_Generated.cs` Part
```
using Godot;
using Godot.NativeInterop;

partial class TestScript
{
    protected override void SaveGodotObjectData(global::Godot.Bridge.GodotSerializationInfo info)
    {
        base.SaveGodotObjectData(info);
line9>  info.AddSignalEventDelegate(SignalName.OnNodeStart, this.backing_OnNodeStart);
    }
    protected override void RestoreGodotObjectData(global::Godot.Bridge.GodotSerializationInfo info)
    {
        base.RestoreGodotObjectData(info);
        if (info.TryGetSignalEventDelegate<TestScript.OnNodeStartEventHandler>(SignalName.OnNodeStart, out var _value_OnNodeStart))
            this.backing_OnNodeStart = _value_OnNodeStart;
    }
}
```

`TestScript.cs` Script Part:

```
using Godot;

[Tool]
public partial class TestScript : Node {
    [Signal] public delegate void OnNodeStartEventHandler(string nodeName);
}
```

### Steps to reproduce

1. Mark Script As [Tool] And Attch Into Scene
2. Change Delegate Name To Others , Add Or Remove A Singal Delegate...
3. Build Again
4. Build Passed, But Error Shows In Editor Console.
---
- After Restart Godot Editor, No Error Shows Again. But Can Be Reproduced.
- Only Reproduced On Tool Script

### Minimal reproduction project

[Test.zip](https://github.com/godotengine/godot/files/9702985/Test.zip)

**Comment by raulsntos** [comment] 2022-12-04 13:37
Duplicate of https://github.com/godotengine/godot/issues/67212

**Closed by raulsntos** 2022-12-04 13:37 UTC
Labels: bug, topic:dotnet
