### ISSUE TITLE
Fixing Multiple Viewport's Environments

### ISSUE THREAD

**Issue by 3booodpro** [godotengine/godot#56433] opened 2022-01-02 13:37 UTC
### Godot version

3.4.2 stable

### System information

Windows 10, GLES3, GTX 1660 Super

### Issue description

I wanted to make a sprite pixelated so I used viewports!
when I did that I wanted the glow to be pixelated also.
but when ever I put an Environment on the Additional Viewport its not glowing
in fact its make the screen black :(
this is some gifs to explain

https://user-images.githubusercontent.com/78119395/147877363-742fa380-4d9c-4c1b-aad1-bce1300076fd.mp4

### Steps to reproduce

https://user-images.githubusercontent.com/78119395/147877387-55441495-db1d-4071-a3c8-965b17d2c2ae.mp4

**Comment by 3booodpro** [comment] 2022-01-02 13:37
oh yeah also I don't want everything to be pixelated
only the fire thingy :)

**Comment by Zireael07** [comment] 2022-01-02 13:44
Environment effects don't work on further viewports, it's a known limitation.

As for pixelation - play around with import settings of your textures,

**Comment by Calinou** [comment] 2022-01-02 16:39
Duplicate of https://github.com/godotengine/godot/issues/45208.

PS: You don't need to use a shader to make your game look pixelated. Instead, use the `viewport` stretch mode and a low base resolution (such as 320×240). See [Multiple resolutions](https://docs.godotengine.org/en/stable/tutorials/viewports/multiple_resolutions.html) in the documentation for more information.

**Closed by Calinou** 2022-01-02 16:39 UTC
