### ISSUE TITLE
"Search Help" Selection Color and bad filtering

### ISSUE THREAD

**Issue by AlexHolly** [godotengine/godot#20995] opened 2018-08-14 10:58 UTC
https://github.com/godotengine/godot/commit/9f8e2d5c5bb0ab56630768530025e9e36c4bd445

![peek 2018-08-14 12-53](https://user-images.githubusercontent.com/4741886/44087727-0c20c798-9fc1-11e8-8454-b541986e430b.gif)

1. Search for a method "set_focus_mode" -> No Result
2. If someone works in a bright environment the selection color(black) is almost not visible on the greyish background. (:thinking: maybe I should look for a basement to solve this issue :thinking: )

**Comment by CowThing** [comment] 2018-08-14 12:18
All set_ and get_ methods don't show up in search if they have a member that can set and get the value. Which I think is good since those set_ and get_ methods also don't show up in autocomplete, you're just supposed to use the member to do the setting and getting.

**Comment by akien-mga** [comment] 2018-08-14 12:43
Duplicate of #17796.

**Closed by akien-mga** 2018-08-14 12:43 UTC

**Comment by AlexHolly** [comment] 2018-08-14 12:47
:D So thats the reason I always have to search manually, thanks.

What is the auto completion used for, if you already know the exact word?

With set/get you eliminate 50% of possibilities most ppl do that(at least in Java). Thats why it is important that the method name contains the exact attribute name.

Mixing two concepts creates inconsistent code and confuses the user.

The Color issue is not part of #17796.

**Comment by akien-mga** [comment] 2018-08-14 13:01
> Mixing two concepts creates inconsistent code and confuses the user.
>
> The Color issue is not part of #17796.

Mixing two concepts creates inconsitent issues and confuses bug fixers :P

It would be clearer to open a specific issue for the theme color problem, as it's not related to the search behaviour itself.
