### ISSUE TITLE
Keyboard navigation no longer works

### ISSUE THREAD

**Issue by dalexeev** [godotengine/godot#55169] opened 2021-11-20 17:01 UTC
### Godot version

v4.0.dev.custom_build [eaa4445e1]

### System information

Kubuntu 21.10

### Issue description

Keyboard navigation with arrows and <kbd>Tab</kbd> key no longer works.

### Steps to reproduce

Focus on Button1 and try pressing the Down or <kbd>Tab</kbd> key.

### Minimal reproduction project

[keyboard_navigation_bug.zip](https://github.com/godotengine/godot/files/7574865/keyboard_navigation_bug.zip)

**Comment by Calinou** [comment] 2021-11-20 17:31
Duplicate of https://github.com/godotengine/godot/issues/54602 (will be fixed by https://github.com/godotengine/godot/pull/54842, as it's not editor-specific).

**Closed by Calinou** 2021-11-20 17:31 UTC

**Comment by univeous** [comment] 2021-12-01 10:48
#54842 will only fix Tab key but not arrow keys.
