### ISSUE TITLE
project crashes when resizing window and rendering model is set to Multi-Threaded

### ISSUE THREAD

**Issue by pnemtsev** [godotengine/godot#75151] opened 2023-03-20 19:01 UTC
### Godot version

v4.0.stable.official.92bee43ad

### System information

Ubuntu 22.04.2 LTS, RTX 3080 Ti, 525.85.05. Vulkan API 1.3.224

### Issue description

Empty project crashes on linux when i try to resize the window with mouse.
Can reproduce the problem only with the Multi-Threaded rendering model.

```
Running: /home/pnemtsev/bin/godot/Godot_v4.0-stable_linux.x86_64 --path /home/pnemtsev/bugproj --remote-debug tcp://127.0.0.1:6007 --editor-pid 35263 --position 704,396 res://node_2d.tscn
Godot Engine v4.0.stable.official.92bee43ad - https://godotengine.org
Vulkan API 1.3.224 - Forward+ - Using Vulkan Device #0: NVIDIA - NVIDIA GeForce RTX 3080 Ti
================================================================
handle_crash: Program crashed with signal 11
Engine version: Godot Engine v4.0.stable.official (92bee43adba8d2401ef40e2480e53087bcb1eaf1)
Dumping the backtrace. Please include this when reporting the bug to the project developer.
[1] /lib/x86_64-linux-gnu/libc.so.6(+0x42520) [0x7fc8c1842520] (??:0)
[2] /lib/x86_64-linux-gnu/libnvidia-glcore.so.525.85.05(+0x18722a3) [0x7fc8990722a3] (??:0)
[3] /lib/x86_64-linux-gnu/libnvidia-glcore.so.525.85.05(+0x18728d9) [0x7fc8990728d9] (??:0)
[4] /home/pnemtsev/bin/godot/Godot_v4.0-stable_linux.x86_64() [0x4c88dc6] (??:0)
[5] /home/pnemtsev/bin/godot/Godot_v4.0-stable_linux.x86_64() [0x1b02fe3] (??:0)
[6] /home/pnemtsev/bin/godot/Godot_v4.0-stable_linux.x86_64() [0x1a8499f] (??:0)
[7] /home/pnemtsev/bin/godot/Godot_v4.0-stable_linux.x86_64() [0x3a89df1] (??:0)
[8] /home/pnemtsev/bin/godot/Godot_v4.0-stable_linux.x86_64() [0x3b5e8c2] (??:0)
[9] /home/pnemtsev/bin/godot/Godot_v4.0-stable_linux.x86_64() [0x3b3c1af] (??:0)
[10] /home/pnemtsev/bin/godot/Godot_v4.0-stable_linux.x86_64() [0x41edd45] (??:0)
[11] /home/pnemtsev/bin/godot/Godot_v4.0-stable_linux.x86_64() [0x4dbfc60] (??:0)
[12] /lib/x86_64-linux-gnu/libc.so.6(+0x94b43) [0x7fc8c1894b43] (??:0)
[13] /lib/x86_64-linux-gnu/libc.so.6(+0x126a00) [0x7fc8c1926a00] (??:0)
-- END OF BACKTRACE --
================================================================
```

### Steps to reproduce

- Create a project.
- Create a new 2d scene.
- Run  the project.
- Resize the window dozen of times. Make sure that nothing bad happens.
- Stop the project.
- Select the Multi-Threaded rendering model.
- Run the project again.
- Resize the window until crash. Sometimes it is the first resizing attempt, sometimes it needs a couple of minutes.

### Minimal reproduction project

[bugproj.zip](https://github.com/godotengine/godot/files/11022069/bugproj.zip)

**Comment by pnemtsev** [comment] 2023-03-22 11:11
The bug persists in the recent stable build.
```
Running: /home/pnemtsev/bin/godot/Godot_v4.0.1-stable_linux.x86_64 --path /home/pnemtsev/projects/hvbgfh --remote-debug tcp://127.0.0.1:6007 --editor-pid 8109 --position 704,396 res://node_2d.tscn
Godot Engine v4.0.1.stable.official.cacf49999 - https://godotengine.org
Vulkan API 1.3.224 - Forward+ - Using Vulkan Device #0: NVIDIA - NVIDIA GeForce RTX 3080 Ti
================================================================
handle_crash: Program crashed with signal 11
Engine version: Godot Engine v4.0.1.stable.official (cacf49999e3fb37281d66cc591ca8bebc5712d4d)
Dumping the backtrace. Please include this when reporting the bug to the project developer.
[1] /lib/x86_64-linux-gnu/libc.so.6(+0x42520) [0x7eff50642520] (??:0)
[2] /lib/x86_64-linux-gnu/libnvidia-glcore.so.525.85.05(+0x18722a3) [0x7eff278722a3] (??:0)
[3] /lib/x86_64-linux-gnu/libnvidia-glcore.so.525.85.05(+0x18728d9) [0x7eff278728d9] (??:0)
[4] /home/pnemtsev/bin/godot/Godot_v4.0.1-stable_linux.x86_64() [0x4c90c66] (??:0)
[5] /home/pnemtsev/bin/godot/Godot_v4.0.1-stable_linux.x86_64() [0x1b04843] (??:0)
[6] /home/pnemtsev/bin/godot/Godot_v4.0.1-stable_linux.x86_64() [0x1a8702f] (??:0)
[7] /home/pnemtsev/bin/godot/Godot_v4.0.1-stable_linux.x86_64() [0x3a91cc1] (??:0)
[8] /home/pnemtsev/bin/godot/Godot_v4.0.1-stable_linux.x86_64() [0x3b661a2] (??:0)
[9] /home/pnemtsev/bin/godot/Godot_v4.0.1-stable_linux.x86_64() [0x3b4405f] (??:0)
[10] /home/pnemtsev/bin/godot/Godot_v4.0.1-stable_linux.x86_64() [0x41f6bd5] (??:0)
[11] /home/pnemtsev/bin/godot/Godot_v4.0.1-stable_linux.x86_64() [0x4dc7160] (??:0)
[12] /lib/x86_64-linux-gnu/libc.so.6(+0x94b43) [0x7eff50694b43] (??:0)
[13] /lib/x86_64-linux-gnu/libc.so.6(+0x126a00) [0x7eff50726a00] (??:0)
-- END OF BACKTRACE --
================================================================
```

**Comment by Calinou** [comment] 2023-03-26 17:19
- Duplicate of https://github.com/godotengine/godot/issues/64766.

**Closed by Calinou** 2023-03-26 17:19 UTC
Labels: bug, topic:core, crash
