### ISSUE TITLE
Color picker makes screen black on second monitor when picking colors

### ISSUE THREAD

**Issue by Shadowblitz16** [godotengine/godot#76602] opened 2023-04-30 00:30 UTC
### Godot version

v4.0.2.stable.mono.official [7a0977ce2]

### System information

Kubuntu 22.04 compatability

### Issue description

color picker blacks out screen when using color picker
![image](https://user-images.githubusercontent.com/2453707/235329720-d6f89996-8c21-43b7-86ab-f08095fd3c78.png)

![image](https://user-images.githubusercontent.com/2453707/235329709-6aecb46e-9917-44b5-b58f-5d8d337c14cd.png)

### Steps to reproduce

- use two montors 1 hdmi,1 display port
- use color picker on second monitor

### Minimal reproduction project

it happens on all projects.

**Comment by KoBeWi** [comment] 2023-04-30 00:38
Duplicate of #74048

**Closed by KoBeWi** 2023-04-30 00:38 UTC
