### ISSUE TITLE
Godot 4.1-beta3: compile error `Cannot call virtual function "_unhandled_input()"`

### ISSUE THREAD

**Issue by MikeSchulze** [godotengine/godot#78639] opened 2023-06-24 07:31 UTC
### Godot version

v4.1.beta3.official [ada712e06]

### System information

Windows 10

### Issue description

I try to run my plugin GdUnit4 on latest Godot v4.1.beta3.official [ada712e06] and it shows up an compile error.

`res://addons/gdUnit4/src/core/GdUnitSceneRunnerImpl.gd:335 - Parse Error: Cannot call virtual function "_unhandled_input()" because it hasn't been defined.`

I do not call this function without any check because it is a virtual function.
```
		if(_current_scene.has_method("_unhandled_input")):
			_current_scene._unhandled_input(event)
```

This error is only show up for `_unhandled_input` for others like `_gui_input` no error is shown

### Steps to reproduce

put this code in a new script

```gdscript
extends Node


var _current_scene :Node


func _handle_input_event(event :InputEvent):
	if(_current_scene.has_method("_gui_input")):
		_current_scene._gui_input(event)
	if(_current_scene.has_method("_unhandled_input")):
		_current_scene._unhandled_input(event)

```

  res://virtual_func_call.gd:11 - Parse Error: Cannot call virtual function "_unhandled_input()" because it hasn't been defined.

### Minimal reproduction project

n/a

**Comment by MikeSchulze** [comment] 2023-06-24 07:41
looks like a duplicate to https://github.com/godotengine/godot/issues/78532

**Comment by AThousandShips** [comment] 2023-06-24 08:01
Duplicate of #78532

**Closed by AThousandShips** 2023-06-24 08:01 UTC
