### ISSUE TITLE
crash in ordered_hash_map.h []

### ISSUE THREAD

**Issue by capnm** [godotengine/godot#12760] opened 2017-11-09 01:23 UTC
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
godot3 tip 5fb359d8b1d58061af2d64b304dc0e62c9228efc

**Issue description:**

The editor crashed (so far 2x) after instancing a scene with an animation player:

```
ERROR: operator[]: FATAL: Condition ' !e ' is true.
   At: core/ordered_hash_map.h:242.
handle_crash: Program crashed with signal 4
Dumping the backtrace. Please include this when reporting the bug on https://github.com/godotengine/godot/issues
[1] /lib/x86_64-linux-gnu/libc.so.6(+0x354b0) [0x7f1db2be04b0] (??:0)
[2] godot3() [0x1ab012c] (/data4/intranet/godot-build/godot-git-build/core/ordered_hash_map.h:242)
[3] godot3() [0xee8383] (/data4/intranet/godot-build/godot-git-build/editor/plugins/animation_player_editor_plugin.cpp:659)
[4] godot3() [0xd002d0] (/data4/intranet/godot-build/godot-git-build/editor/editor_data.cpp:347 (discriminator 8))
[5] godot3() [0xd03c20] (/data4/intranet/godot-build/godot-git-build/editor/editor_data.cpp:751)
[6] godot3() [0xb50912] (/data4/intranet/godot-build/godot-git-build/editor/editor_node.cpp:2890)
[7] godot3() [0x591c17] (/data4/intranet/godot-build/godot-git-build/./core/variant.h:412)
[8] godot3() [0x1b63ba6] (/data4/intranet/godot-build/godot-git-build/core/object.cpp:839 (discriminator 1))
[9] godot3() [0x1b5df01] (/data4/intranet/godot-build/godot-git-build/core/object.cpp:765)
[10] godot3() [0x1ac42c1] (/data4/intranet/godot-build/godot-git-build/core/variant.h:412)
[11] godot3() [0x1ac4495] (/data4/intranet/godot-build/godot-git-build/core/undo_redo.cpp:311)
[12] godot3() [0x1ac4664] (/data4/intranet/godot-build/godot-git-build/core/undo_redo.cpp:242)
[13] godot3() [0xb410fc] (/data4/intranet/godot-build/godot-git-build/editor/editor_node.cpp:3964)
[14] godot3() [0x591c17] (/data4/intranet/godot-build/godot-git-build/./core/variant.h:412)
[15] godot3() [0x1b63ba6] (/data4/intranet/godot-build/godot-git-build/core/object.cpp:839 (discriminator 1))
[16] godot3() [0x1b68d50] (/data4/intranet/godot-build/godot-git-build/core/variant.h:412)
[17] godot3() [0x1b69900] (/data4/intranet/godot-build/godot-git-build/core/object.cpp:1166)
[18] godot3() [0x112feed] (/data4/intranet/godot-build/godot-git-build/scene/gui/tabs.cpp:431 (discriminator 4))
[19] godot3() [0x1132cee] (/data4/intranet/godot-build/godot-git-build/scene/gui/tabs.cpp:229)
[20] godot3() [0x6c7814] (/data4/intranet/godot-build/godot-git-build/core/reference.h:278)
[21] godot3() [0x1b63819] (/data4/intranet/godot-build/godot-git-build/core/variant.h:412)
[22] godot3() [0x1b5df81] (/data4/intranet/godot-build/godot-git-build/core/object.cpp:780)
[23] godot3() [0x10a514f] (/data4/intranet/godot-build/godot-git-build/core/variant.h:412)
[24] godot3() [0x10a9711] (/data4/intranet/godot-build/godot-git-build/core/reference.h:278)
[25] godot3() [0x10abeb7] (/data4/intranet/godot-build/godot-git-build/core/reference.h:278)
[26] godot3() [0x10ac078] (/data4/intranet/godot-build/godot-git-build/core/reference.h:278)
[27] godot3() [0x6c7814] (/data4/intranet/godot-build/godot-git-build/core/reference.h:278)
[28] godot3() [0x1b63ba6] (/data4/intranet/godot-build/godot-git-build/core/object.cpp:839 (discriminator 1))
[29] godot3() [0x1b5df01] (/data4/intranet/godot-build/godot-git-build/core/object.cpp:765)
[30] godot3() [0x10dfae0] (/data4/intranet/godot-build/godot-git-build/core/variant.h:412)
[31] godot3() [0x10e1c3e] (/data4/intranet/godot-build/godot-git-build/scene/main/scene_tree.cpp:403 (discriminator 6))
[32] godot3() [0x43e4c4] (/data4/intranet/godot-build/godot-git-build/core/reference.h:278)
[33] godot3() [0x423bc2] (/data4/intranet/godot-build/godot-git-build/core/reference.h:278)
[34] godot3() [0x4248f0] (/data4/intranet/godot-build/godot-git-build/platform/x11/os_x11.cpp:2105)
[35] godot3(main+0xd3) [0x419da3] (/data4/intranet/godot-build/godot-git-build/platform/x11/godot_x11.cpp:54)
[36] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf0) [0x7f1db2bcb830] (??:0)
[37] godot3() [0x41d079] (??:?)
-- END OF BACKTRACE --
Abgebrochen
```

**Comment by cbscribe** [comment] 2017-11-09 02:29
See https://github.com/godotengine/godot/issues/12715#issuecomment-342542006 

Fixed the problem for me.

**Comment by akien-mga** [comment] 2017-11-09 10:01
Duplicate of #12715.

**Closed by akien-mga** 2017-11-09 10:01 UTC
