### ISSUE TITLE
Godot 4 Alpha 14 Reordering Custom Tile Set Data in Inspector Crashes Editor

### ISSUE THREAD

**Issue by xCISACx** [godotengine/godot#64978] opened 2022-08-28 02:10 UTC
### Godot version

v4.0.alpha14.official.106b68050

### System information

Windows 11, Vulkan, RTX 3060 Mobile, 516.94

### Issue description

Creating a tile set with multiple custom data entries and attempting to reorder them in the inspector causes Godot to crash.

The tile set MUST have a tile assigned to it in the tile set editor as simply creating a tile set and setting custom data through the inspector doesn't crash the editor.

It ONLY crashes when the tile set contains tiles.

### Steps to reproduce

1 - Create a tile set.
2 - Add more than 1 custom data entries to it.
3 - Add a tile to the tile set. (IMPORTANT, DOESN'T CRASH WITHOUT THIS STEP)
4 - Assign custom data values to a tile in the tile set. (OPTIONAL, crashes anyway without this step if a tile exists)
5 - Attempt to reorder them by dragging in the inspector window.
6 - Godot crashes.

### Minimal reproduction project

[CustomDataReorder.zip](https://github.com/godotengine/godot/files/9438977/CustomDataReorder.zip)

**Comment by groud** [comment] 2023-01-18 10:41
I cannot reproduce on the latest version, could you test again ?

**Comment by arkology** [comment] 2023-01-19 10:14
> I cannot reproduce on the latest version, could you test again ?

Same. Looks like it was fixed.

**Comment by groud** [comment] 2023-01-19 10:21
Awesome, thanks! Closing the issue.

**Closed by groud** 2023-01-19 10:21 UTC
Labels: bug, topic:editor, crash, topic:2d
