### ISSUE TITLE
Canvas Background mode causes UI to resize when rendering/scaling_3d/scale is changed

### ISSUE THREAD

**Issue by X64X32** [godotengine/godot#69375] opened 2022-11-30 07:49 UTC
### Godot version

4.0beta6

### System information

Windows 10, Vulkan

### Issue description

Whenever you change rendering/scaling_3d/scale and reload the editor, UI will get resized as well when canvas background mode is used
![image](https://user-images.githubusercontent.com/53514993/204737851-afff4c96-84d5-44bb-ac54-2f156ce36529.png)

### Steps to reproduce

Create a WorldEnvironment node
Change background_mode to BG_CANVAS
Change rendering/scaling_3d/scale at settings
Reload the editor
Enjoy the show 

### Minimal reproduction project

[LowRes.zip](https://github.com/godotengine/godot/files/10120736/LowRes.zip)

**Comment by clayjohn** [comment] 2022-11-30 20:15
Duplicate of https://github.com/godotengine/godot/issues/69122

Closes as the issue is best tracked in a single place

**Closed by clayjohn** 2022-11-30 20:15 UTC
