### ISSUE TITLE
Abysmal download speed

### ISSUE THREAD

**Issue by Eric-Arz** [godotengine/godot#41129] opened 2020-08-08 19:44 UTC
Downloads from the official godotengine.org are extremely slow (20-30 kb/s). Downloading the 70MB Mono Version takes over 1 hour. Downloading an export template from within the engine suffers from the same issue and takes multiple hours. The problem is **not my internet connection**, i am getting stable 5-6 mb/s on downloads from other websites.

After doing a bit of research i found out that this is a common issue and i am far from the only one having problems with download speed. It appears that depending on your location downloads from TuxFamily are basically unusable.

Please consider fixing this or at least offer alternative hosters.

**Comment by Calinou** [comment] 2020-08-08 20:10
Duplicate of https://github.com/godotengine/godot-website/issues/105.

In the meantime, use [this mirror hosted by yours truly](https://archive.hugo.pro/godot-tuxfamily/) :slightly_smiling_face:

**Closed by Calinou** 2020-08-08 20:10 UTC

**Comment by akien-mga** [comment] 2020-08-13 09:20
@Eric-Arz If you don't mind, can you send me (`remi@godotengine.org`) information on your geographical location and ISP? I would pass it on to TuxFamily admins to debug why you might be getting such a slow mirror.

**Comment by Eric-Arz** [comment] 2021-03-11 22:12
This problem still persists. Why you still 

> Duplicate of [godotengine/godot-website#105](https://github.com/godotengine/godot-website/issues/105). In the meantime, use [this mirror hosted by yours truly](https://archive.hugo.pro/godot-tuxfamily/) 
> 
> (Note that you don't _have_ to use the editor to download export templates. You can download the TPZ file and use the **Install From File** button in the export template manager.)

This problem still exists.

**Comment by Calinou** [comment] 2021-03-11 22:46
@Eric-Arz We are aware of this, but we don't have a definite plan towards fixing it yet.
