### ISSUE TITLE
ERROR: UndoRedo history mismatch: expected 0, got 5.

### ISSUE THREAD

**Issue by erikbgithub** [godotengine/godot#74088] opened 2023-02-27 22:53 UTC
### Godot version

0bc36c8954

### System information

Ubuntu 22.10 on Thinkpad T580

### Issue description

Running self-built Godot and started a new Scene2D file with just a Tilemap inside. Created a new Tileset and added a PNG. Now things are extremely slow (possibly because it's autotiling my 100x100 image into 16x16 tiles) and gives the following error message in bash:

```
ERROR: UndoRedo history mismatch: expected 0, got 5.
   at: get_history_for_object (editor/editor_undo_redo_manager.cpp:108)
```

### Steps to reproduce

Happy to give more details on request.

### Minimal reproduction project

Should be trivial enough. Happy to provide more input on request.

**Comment by KoBeWi** [comment] 2023-02-27 23:45
Looks like duplicate of #73603
Does the error persist after restarting editor?

**Comment by erikbgithub** [comment] 2023-02-28 15:15
I can reproduce it after a fresh reboot with the same commit (v4.0.rc.custom_build.0bc36c895) and the latest as well.

To be more precise.
[Here's my Godot project, the first commit.](https://github.com/Play2Learn-Org/hackerspace/tree/9a2dd99148bd763f93af323ad3a0b969d5f7065f)
If I start it in `v4.0.rc.custom_build.0bc36c895` I get this:

```
WARNING: Blend file import is enabled in the project settings, but no Blender path is configured in the editor settings. Blend files will not be imported.
     at: _editor_init (modules/gltf/register_types.cpp:70)
```

Then, when I go to the tileset and change the resolution from 500x500 (I miscalculated last time and each tile isn't 100x100 but 500x500) to 16x16, then I get this error:

```
ERROR: UndoRedo history mismatch: expected 0, got 3.
   at: get_history_for_object (editor/editor_undo_redo_manager.cpp:108)
```

And it repeats from time to time.

Then on closing Godot to recompile in the newest commit, I get more errors. I didn't check if and which came before resetting to 500x500, before the Save&Quit dialogue, and which came after:

```
ERROR: Index p_idx = -2 is out of bounds (edited_scene.size() = 2).
   at: set_scene_as_saved (editor/editor_data.cpp:373)
ERROR: Index p_idx = -2 is out of bounds (edited_scene.size() = 2).
   at: set_scene_modified_time (editor/editor_data.cpp:731)
ERROR: Index p_idx = -2 is out of bounds (edited_scene.size() = 2).
   at: remove_scene (editor/editor_data.cpp:574)
ERROR: Attempted to free invalid ID: 0
   at: _free_internal (drivers/vulkan/rendering_device_vulkan.cpp:8394)
ERROR: Attempted to free invalid ID: 0
   at: _free_internal (drivers/vulkan/rendering_device_vulkan.cpp:8394)
ERROR: Attempted to free invalid ID: 0
   at: _free_internal (drivers/vulkan/rendering_device_vulkan.cpp:8394)
ERROR: Attempted to free invalid ID: 0
   at: _free_internal (drivers/vulkan/rendering_device_vulkan.cpp:8394)
ERROR: Attempted to free invalid ID: 0
   at: _free_internal (drivers/vulkan/rendering_device_vulkan.cpp:8394)
ERROR: Condition "!shader" is true.
   at: shader_free (servers/rendering/renderer_rd/storage_rd/material_storage.cpp:2453)
ERROR: Condition "!material" is true.
   at: material_free (servers/rendering/renderer_rd/storage_rd/material_storage.cpp:2686)
```

Now after recompiling to `v4.0.rc.custom_build.491ded189`, it starts again with:

```
WARNING: Blend file import is enabled in the project settings, but no Blender path is configured in the editor settings. Blend files will not be imported.
     at: _editor_init (modules/gltf/register_types.cpp:70)
```

And then when I set it to 16x16, I get these two:

```
ERROR: UndoRedo history mismatch: expected 0, got 3.
   at: get_history_for_object (editor/editor_undo_redo_manager.cpp:108)
ERROR: UndoRedo history mismatch: expected 0, got 3.
   at: get_history_for_object (editor/editor_undo_redo_manager.cpp:108)
```

I wonder if one comes after setting `x` and the other after setting `y`.
Looking back at the previous test, altogether the error came 4x. So it might be that it happens not time based but based on me changing the tile resolution in the Godot UI.

Testing that on resetting to 500x500 seems to confirm it. Not time based but input based. In this version I also checked that the other error messages happen after I click the Save&Quit button in the pop-up menu, which comes after I click the red `x` in the top right.

**Comment by KoBeWi** [comment] 2023-02-28 15:50
So again, #73603 is about error that appears when you change TileSet properties. The error is mostly harmless, unless you want to undo something.
But this only happens when you edit the TileSet. I assume the are no errors when you use the TileMap node itself, without editing the TileSet?

**Comment by erikbgithub** [comment] 2023-02-28 19:10
Seems correct.

**Comment by KoBeWi** [comment] 2023-02-28 20:08
Closing as duplicate then.

**Closed by KoBeWi** 2023-02-28 20:08 UTC
