### ISSUE TITLE
3.2.2 Stuck On GLB Import

### ISSUE THREAD

**Issue by joshchristiane** [godotengine/godot#41805] opened 2020-09-06 09:25 UTC
GLES3, Windows 10, RTX 2070

**Issue description:**
Was importing basic glb file (which came from Blender export), the engine froze instantly and never recovered. Upon re-opening the program it continues with this fatal error.

**Steps to reproduce:**
When my main mesh has a child mesh (collider) named "-colonly" without a proceeding mesh name, it will crash consistently on import.

To anybody who runs into this problem of it infinitely crashing your project, just go to the folder and delete the import object from the actual Godot project files. It'll then open correctly.

**Comment by Calinou** [comment] 2020-09-06 13:01
@joshchristiane https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project

**Comment by fire** [comment] 2020-10-18 15:30
Closing due to no reply. Please comment if you can still reproduce in 3.2.2+.

**Closed by fire** 2020-10-18 15:30 UTC
Labels: bug, crash, topic:import
