### ISSUE TITLE
Failed to size multiple images in ScrollContainer

### ISSUE THREAD

**Issue by Caesar454905970** [godotengine/godot#96988] opened 2024-09-14 07:13 UTC
### Tested versions

Godot_v4.3-stable_win64.exe

### System information

Window10 godot4.3

### Issue description

Using ScrollContainer to display multiple images and manually setting the size of each image failed
![image](https://github.com/user-attachments/assets/2210e1d4-e1ab-4f98-908a-6fd57d7935a4)

### Steps to reproduce

```gdscript
extends Control

# Called when the node enters the scene tree for the first time.
func _ready() -> void:
	# 图片文件名列表
	var image_files = [
		"res://pdf_temp/output_page_1.png",
		"res://pdf_temp/output_page_2.png",
		"res://pdf_temp/output_page_3.png",
		"res://pdf_temp/output_page_4.png"
	]
	
	# 获取 ScrollContainer 和 VBoxContainer 节点
	var scroll_container = $ScrollContainer
	var vbox = scroll_container.get_node("VBoxContainer")
	
	# 固定宽度
	var fixed_width = 300.0
	
	# 加载图片并添加到 VBoxContainer 中
	for image_file in image_files:
		var texture_rect = TextureRect.new()
		
		# 这里可以设置一个默认的最小尺寸
		texture_rect.custom_minimum_size = Vector2(fixed_width, 150.0)  # 默认高度为150
		
		# 加载纹理
		var texture = load(image_file)
		texture_rect.texture = texture
		
		# 使用 STRETCH_KEEP_ASPECT_COVERED 以保持纵横比
		texture_rect.stretch_mode = TextureRect.STRETCH_KEEP_ASPECT_COVERED
		
		# 如果纹理已经加载成功，可以调整其宽高
		if texture:
			var original_width = texture.get_width()
			var original_height = texture.get_height()
			var scale = fixed_width / original_width
			var new_height = original_height * scale
			texture_rect.custom_minimum_size = Vector2(fixed_width, new_height)
		
		# 将 TextureRect 添加到 VBoxContainer 中
		vbox.add_child(texture_rect)
```

### Minimal reproduction project (MRP)

[game.zip](https://github.com/user-attachments/files/17001405/game.zip)

**Comment by kleonc** [comment] 2024-09-14 09:52
> Using ScrollContainer to display multiple images and manually setting the size of each image failed

1. You're adding the images to VBoxContainer, not to ScrollContainer.
2. You're setting images' `Control.custom_minimum_size`, not the `Control.size`.
3. Parent Container (here VBoxContainer) is responsible for placing/resizing child Controls, by design. So `Control.size` manually set for child Controls of some Container is expected to be overwritten anyway, when Container resorts its children.

AFAICT everything works as expected in the MRP, I don't see any bug in here.

**Comment by Caesar454905970** [comment] 2024-09-14 09:57
However, the size of the displayed texture has not been changed, the size is still the same as the image size！

**Comment by kleonc** [comment] 2024-09-14 10:07
> However, the size of the displayed texture has not been changed, the size is still the same as the image size！

Yes, according to the setup.
![Godot_v4 3-stable_win64_DiekppGTMf](https://github.com/user-attachments/assets/d250a3db-fdf8-4abe-82c9-82f5e24cdb2f)

**Comment by kleonc** [comment] 2024-09-14 10:35
> You mean to change Expand Mode,？

I mean with `TextureRect.expand_mode`  set to `TextureRect.EXPAND_KEEP_SIZE` it's expected that the texture size is preserved.

> please use the code example to implement, change the size of the texture display！

Note that this is a bugtracker, not a helpdesk / support forum. If you're not sure you're facing an in-engine bug, or you simply want some help with your project, then please firstly try asking for help on other [community channels](https://godotengine.org/community/) (forum, discord, etc.). This is not a place to ask this type of help questions.

---

But regardless the above: simply adding `texture_rect.expand_mode = TextureRect.EXPAND_IGNORE_SIZE` in the MRP would already make the textures be way smaller, yes. Whether this gives you the layout you want etc. I have no idea. But again: this is not a place to ask this type of help questions.

I'm closing this issue as not a bug.

If you'll find an actual bug then please comment with an update, the issue could be of course reopened in such case.

**Closed by kleonc** 2024-09-14 10:35 UTC
