### ISSUE TITLE
OptionButton icons not showing

### ISSUE THREAD

**Issue by nonunknown** [godotengine/godot#46871] opened 2021-03-10 14:49 UTC
**Godot version:**
3.2.4 RC4 mono

**OS/device including version:**
Windows 10 x64

**Issue description:**
When setting icons for OptionButton node they doesnt appear in-game

editor:
![image](https://user-images.githubusercontent.com/58845030/110647376-89171180-8196-11eb-9aaa-caea4ff13ff0.png)

in-game:
![image](https://user-images.githubusercontent.com/58845030/110647441-98965a80-8196-11eb-80d0-b6120cf3c237.png)

**Steps to reproduce:**
* Create a control node
* add a OptionButton child
* attach a texture to an item

**Minimal Reproduction Project**
[error-ob.zip](https://github.com/godotengine/godot/files/6116978/error-ob.zip)

**Comment by akien-mga** [comment] 2021-03-10 14:55
I can't reproduce the issue in 3.2.4 RC 4:
![Screenshot_20210310_155417](https://user-images.githubusercontent.com/4701338/110648324-e623bf00-81b8-11eb-908b-604c0a96afca.png)

Could you provide a reproduction project?

**Comment by nonunknown** [comment] 2021-03-10 15:28
youre using mono version?

**Comment by nonunknown** [comment] 2021-03-10 15:34
Done

**Comment by akien-mga** [comment] 2021-03-10 17:46
The items don't seem to have any icon assigned in the attached project:
![Screenshot_20210310_184500](https://user-images.githubusercontent.com/4701338/110673190-c26c7300-81d0-11eb-8297-9da80316341b.png)

**Comment by akien-mga** [comment] 2021-03-10 17:59
Hm after assigning some icons manually I think I can reproduce the bug. For me they don't even appear in the editor.

**Comment by nonunknown** [comment] 2021-03-10 18:30
@akien-mga I was praying to be an error on my side haha, but sadly it isnt :(

**Comment by KoBeWi** [comment] 2021-03-10 23:53
Seems like OptionButton assigns to `icon` the icon of currently selected item. Try creating 2 items, one with icon and one without, and change the `selected` property.

So you can fix this by assigning icon to each option. I guess the inspector shouldn't allow to modify the `icon` property for OptionButton.

**Comment by nonunknown** [comment] 2021-03-11 11:21
what? Sorry I didnt understand, also there are 16 items on the list.

**Comment by KoBeWi** [comment] 2021-03-11 11:37
In the ItemList Editor put a Texture for each element.

**Comment by nonunknown** [comment] 2021-03-11 11:48
this is what I did, and isnt working

**Comment by KoBeWi** [comment] 2021-03-11 11:50
Weird, because I tried this and it worked for me. What happens when you change `selected` property?

**Comment by nonunknown** [comment] 2021-03-11 11:50
WTF it has worked, LOL

![image](https://user-images.githubusercontent.com/58845030/110783084-b3c0a300-8246-11eb-9b79-b1dbdd5f9b11.png)

ok, but there's still a bug @KoBeWi because if I try to attach a atlas texture, I need to go to editor inspector and this way it doesnt work!

**Comment by KoBeWi** [comment] 2021-03-11 11:51
Yeah that's what I said. It's impossible to set the texture using the inspector.

**Comment by nonunknown** [comment] 2021-03-11 11:51
![image](https://user-images.githubusercontent.com/58845030/110783307-04380080-8247-11eb-90ac-50b8b33c2afe.png)

**Comment by Calinou** [comment] 2023-04-26 12:41
Closing in favor of https://github.com/godotengine/godot/issues/76460, which describes this in more detail.

**Closed by Calinou** 2023-04-26 12:41 UTC
Labels: bug, topic:editor, confirmed, topic:gui
