### ISSUE TITLE
vulkan compute_list_dispatch uniforms error

### ISSUE THREAD

**Issue by SaintGeo** [godotengine/godot#80484] opened 2023-08-10 13:28 UTC
### Godot version

v4.1.stable.custom_build [970459615]

### System information

Godot v4.1.stable (970459615) - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 2060 SUPER (NVIDIA; 31.0.15.3699) - Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz (12 Threads)

### Issue description

"renderingdevicevulkan::compute_list_dispatch uniforms were never supplied for set at time of drawing which are required by the pipeline" error appeared when running my project for the first time of the day (restarting windows and the godot editor).

This error did not appear to affect the game, it did not crash, no weird visuals or anything.

After restarting the project (F8 + F5) the error disappeared and did not re-appear.

### Steps to reproduce

Unknown - I have been running the project for ~3 weeks with no prior issues. Have not been able to reproduce.

### Minimal reproduction project

Haven't been able to reproduce.

**Comment by Calinou** [comment] 2023-08-10 13:36
What rendering features do you use in your project (VoxelGI, SDFGI, Environment properties, etc)?

**Comment by bitsawer** [comment] 2023-08-10 14:37
Some similar issues were fixed by https://github.com/godotengine/godot/pull/79849, could be that this one was too.

**Comment by SaintGeo** [comment] 2023-08-10 14:57
Here's a list of everything, not sure how applicable most of this is:
For environment there is volumetric fog and temporal reprojection.
Other nodes include:
- Fog volumes
- multimesh instancers - ~1500 instances w/ a spatial shader
- directional light 3D w/ shadows
- sprite 3Ds, animated sprite 3D, viewports + sprite 3D
- GPUparticle3D w/ particle shaders + planemesh w/ shader

for project settings:
- Volumetric fog : volume size 256, volume depth 128
- Anti aliasing: MSAA 2D : 8x, MSAA 3D 8x, screen space AA FXAA

**Comment by bitsawer** [comment] 2023-08-15 14:33
>GPUparticle3D w/ particle shaders

This issue was most likely fixed by https://github.com/godotengine/godot/pull/79849. Closing as duplicate of issues mentioned in the PR, but feel free to comment or reopen this issue if you can still reproduce this in next releases or up-to-date master build.

**Closed by bitsawer** 2023-08-15 14:33 UTC
Labels: bug, topic:rendering, needs testing
