### ISSUE TITLE
Incorrect rotation in armature animation imported from blender

### ISSUE THREAD

**Issue by rcorre** [godotengine/godot#77954] opened 2023-06-07 11:46 UTC
### Godot version

4.0.3-dev

### System information

Linxu

### Issue description

When I import an animation from blender, there is a slightly incorrect rotation halfway through the animation. This causes the camera to jitter. Here's a comparison of the 0.5s mark of the animation between blender and godot. Notice the slight camera rotation in godot

![1686137997](https://github.com/godotengine/godot/assets/2496231/48fce07f-7b53-4320-82b9-8e8a85b0cce8)

I've tried tweaking various import settings such as FPS and "export bones deforming mesh only" to no avail. https://github.com/godotengine/godot/issues/75635 mentions turning off the animation optimizer but I don't see an option for that in Godot 4.

All the animation curves are linear.

### Steps to reproduce

1. Open example project
2. Open either ThirdPersonModel.glb or ThirdPersonModel.blend (if you have blender set up for imports)
3. Set the editor camera to a top-down view (numpad 7)
4. Select the `RunForward` animation
5. Select the 0.5s time point
6. Notice the camera is rotated
7. Compare to the animation in blender

### Minimal reproduction project

[example.zip](https://github.com/godotengine/godot/files/11676569/example.zip)

**Comment by TokageItLab** [comment] 2023-06-07 16:46
Maybe duplicate of #https://github.com/godotengine/godot/issues/75159 or https://github.com/godotengine/godot/issues/65513.

> https://github.com/godotengine/godot/issues/75635 mentions turning off the animation optimizer but I don't see an option for that in Godot 4.

It can't be. Please look for it right.

**Comment by rcorre** [comment] 2023-06-08 10:48
Ah, I was looking for it in the `Import` tab. I didn't realize double-clicking on a file showed different options. Turning off the optimizer does fix the issue.

**Comment by Wolses** [comment] 2023-11-05 19:50
Hi, is there still an option to turn off the optimizer in Godot 4.1.2 ? I'm looking in the right spot but I don't see anything labelled 'optimizer'.  Has it been removed or split into separate options?

**Comment by rcorre** [comment] 2023-11-06 11:37
@Wolses double-click on the glb/blend file, then on the AnimationPlayer in the newly-opened dialog. 

![1699270427](https://github.com/godotengine/godot/assets/2496231/b1d02fdf-6ad6-41bc-9fec-68d0966d1021)


It was a bit confusing that there are two import setting UIs, and you can't find it in one of them.

**Comment by TokageItLab** [comment] 2024-02-11 09:32
After all, this is a threshold problem, which can be solved by setting the Max Precision Error of the Optimiser to 1.

**Closed by TokageItLab** 2024-02-11 09:32 UTC
Labels: bug, topic:import, topic:animation, topic:3d
