### ISSUE TITLE
DAE import with blend shapes is broken

### ISSUE THREAD

**Issue by MartiniMoe** [godotengine/godot#12618] opened 2017-11-03 22:07 UTC
Arch Linux, Godot 3 Alpha 2

When importing a DAE with blend shapes the mesh is not visible.
In Alpha 1 the same DAE can be imported succesfully and blend shapes work!

I attached a zip with the DAE file and the material for the mesh.

[stage-floor.zip](https://github.com/godotengine/godot/files/1442598/stage-floor.zip)

**Comment by Jubjub** [comment] 2017-11-04 15:29
I'm having the same problem, a workaround seems to be to manually triangulate the mesh before exporting it.

**Comment by akien-mga** [comment] 2018-01-05 15:31
Can you still reproduce it in the current master branch?

**Comment by Jerome67000** [comment] 2018-01-08 22:28
It's still reproductible with the current master.

According to the first line, workaround seems effectively to be to manually triangulate the mesh before exporting it."

Console :
```
WARNING: Collada::_parse_mesh_geometry: Primitive type "polygons" is not well supported (concave shapes may fail). To ensure that the geometry is properly imported, please re-export using "triangles" or "polylist".
     At: editor\collada\collada.cpp:1061
Warning, unreferenced material in geometry instance: id-trimat-8
ERROR: VisualServer::_surface_set_data: Condition ' array.size() != p_vertex_array_len ' is true. returned: ERR_INVALID_PARAMETER
   At: servers\visual_server.cpp:381
ERROR: Invalid blend shape array format for surface
   At: servers\visual_server.cpp:1002
ERROR: RasterizerStorageGLES3::mesh_surface_set_material: Index p_surface=0 out of size (mesh->surfaces.size()=0)
   At: drivers\gles3\rasterizer_storage_gles3.cpp:3152
node: Scene Root
node: Cube
ERROR: RasterizerStorageGLES3::mesh_surface_set_material: Index p_surface=0 out of size (mesh->surfaces.size()=0)
   At: drivers\gles3\rasterizer_storage_gles3.cpp:3152
node: AnimationPlayer
SAVING TO: res://.import/stage-floor.dae-86d1dc4caddbbbd1a015af151bf9a1a6.scn
ERROR: RasterizerStorageGLES3::mesh_surface_get_array: Index p_surface=0 out of size (mesh->surfaces.size()=0)
   At: drivers\gles3\rasterizer_storage_gles3.cpp:3199
ERROR: RasterizerStorageGLES3::mesh_surface_get_array_len: Index p_surface=0 out of size (mesh->surfaces.size()=0)
   At: drivers\gles3\rasterizer_storage_gles3.cpp:3182
ERROR: RasterizerStorageGLES3::mesh_surface_get_index_array: Index p_surface=0 out of size (mesh->surfaces.size()=0)
   At: drivers\gles3\rasterizer_storage_gles3.cpp:3224
ERROR: RasterizerStorageGLES3::mesh_surface_get_array_index_len: Index p_surface=0 out of size (mesh->surfaces.size()=0)
   At: drivers\gles3\rasterizer_storage_gles3.cpp:3190
ERROR: RasterizerStorageGLES3::mesh_surface_get_primitive_type: Index p_surface=0 out of size (mesh->surfaces.size()=0)
   At: drivers\gles3\rasterizer_storage_gles3.cpp:3263
ERROR: RasterizerStorageGLES3::mesh_surface_get_format: Index p_surface=0 out of size (mesh->surfaces.size()=0)
   At: drivers\gles3\rasterizer_storage_gles3.cpp:3254
ERROR: RasterizerStorageGLES3::mesh_surface_get_aabb: Index p_surface=0 out of size (mesh->surfaces.size()=0)
   At: drivers\gles3\rasterizer_storage_gles3.cpp:3272
ERROR: RasterizerStorageGLES3::mesh_surface_get_skeleton_aabb: Index p_surface=0 out of size (mesh->surfaces.size()=0)
   At: drivers\gles3\rasterizer_storage_gles3.cpp:3311
ERROR: RasterizerStorageGLES3::mesh_surface_get_blend_shapes: Index p_surface=0 out of size (mesh->surfaces.size()=0)
   At: drivers\gles3\rasterizer_storage_gles3.cpp:3280
ERROR: RasterizerStorageGLES3::mesh_surface_get_array: Index p_surface=0 out of size (mesh->surfaces.size()=0)
   At: drivers\gles3\rasterizer_storage_gles3.cpp:3199
ERROR: RasterizerStorageGLES3::mesh_surface_get_array_len: Index p_surface=0 out of size (mesh->surfaces.size()=0)
   At: drivers\gles3\rasterizer_storage_gles3.cpp:3182
ERROR: RasterizerStorageGLES3::mesh_surface_get_index_array: Index p_surface=0 out of size (mesh->surfaces.size()=0)
   At: drivers\gles3\rasterizer_storage_gles3.cpp:3224
ERROR: RasterizerStorageGLES3::mesh_surface_get_array_index_len: Index p_surface=0 out of size (mesh->surfaces.size()=0)
   At: drivers\gles3\rasterizer_storage_gles3.cpp:3190
ERROR: RasterizerStorageGLES3::mesh_surface_get_primitive_type: Index p_surface=0 out of size (mesh->surfaces.size()=0)
   At: drivers\gles3\rasterizer_storage_gles3.cpp:3263
ERROR: RasterizerStorageGLES3::mesh_surface_get_format: Index p_surface=0 out of size (mesh->surfaces.size()=0)
   At: drivers\gles3\rasterizer_storage_gles3.cpp:3254
ERROR: RasterizerStorageGLES3::mesh_surface_get_aabb: Index p_surface=0 out of size (mesh->surfaces.size()=0)
   At: drivers\gles3\rasterizer_storage_gles3.cpp:3272
ERROR: RasterizerStorageGLES3::mesh_surface_get_skeleton_aabb: Index p_surface=0 out of size (mesh->surfaces.size()=0)
   At: drivers\gles3\rasterizer_storage_gles3.cpp:3311
ERROR: RasterizerStorageGLES3::mesh_surface_get_blend_shapes: Index p_surface=0 out of size (mesh->surfaces.size()=0)
   At: drivers\gles3\rasterizer_storage_gles3.cpp:3280
```

**Comment by akien-mga** [comment] 2018-01-16 10:55
Not critical for the upcoming 3.0 release, so moving to the next milestone. A fix can still be cherry-picked for 3.0.x maintenance releases once available in the master branch.

**Comment by garyo** [comment] 2018-03-29 13:42
I just got this same error on a glTF import with recent godot:
```
ERROR: RasterizerStorageGLES3::mesh_surface_get_array_index_len: Index p_surface=0 out of size (mesh->surfaces.size()=0)
   At: drivers\gles3\rasterizer_storage_gles3.cpp:3190
```
Looking at the code there, I think if p_shape is 0 and there are no blend_values, it should just do nothing instead of giving an error, as in my XXX comment below:
```
void VisualServerScene::instance_set_blend_shape_weight(RID p_instance, int p_shape, float p_weight) {

	Instance *instance = instance_owner.get(p_instance);
	ERR_FAIL_COND(!instance);

	if (instance->update_item.in_list()) {
		_update_dirty_instance(instance);
	}

        // XXX: if (p_shape==0 && instance->blend_values.size() == 0) { return; }
	ERR_FAIL_INDEX(p_shape, instance->blend_values.size());
	instance->blend_values[p_shape] = p_weight;
}
```
There's no necessity to give an error in that case, IMHO.

**Comment by sxkod** [comment] 2018-04-03 19:18
I have the same problem. If I delete the shape-keys and reimport, that works. Hope this gets a fix soon. Thanks

**Comment by bahelit** [comment] 2018-09-20 03:15
Downloaded a model from blendswap and exported it with better collada, it appeared different in godot then in blender. After some googling about an import error in the godot console came across a thread that mentioned normalizing the model manually before exporting.

Pressed Control+T to manually normalize the model. There where a couple modifications that needed to be made to the model afterwards but it resolved the issue of the model looking different in godot.

**Comment by reduz** [comment] 2018-11-09 00:38
Actually, I remember forcing triangulation in the DAE exporter when blend shapes were used because otherwise this is impossible to do. This is probably an issue with BetterCollada, not Godot and should be opened there (as in, Force triangulation of meshes that use blend shapes).

**Closed** 2018-11-09 00:38 UTC
Labels: bug, topic:editor
