### ISSUE TITLE
Autocomplete and error reporting does not update for new code changes. Requires restart.

### ISSUE THREAD

**Issue by vibrunazo** [godotengine/godot#80674] opened 2023-08-16 02:48 UTC
### Godot version

v4.1.1.stable.official [bd6af8e0e]

### System information

Godot v4.1.1.stable - Windows 10.0.19045 - Vulkan (Compatibility) - GeForce MX110 () - Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 Threads)

### Issue description

On some projects, when first opening Godot, both gdscript autocomplete and the text editor error reporting will work ok. But they will not update on one class if you add new methods or change the code to another class. After adding a new method to a second class, this new method will not show up on autocomplete for the first class. Restarting Godot fixes the issue and the new method will now show up again on autocomplete. But then any new methods that requires referencing a different class won't show up on autocomplete again and another Godot restart will be necessary. Happens on any code update. 

The issue is easily reproducible 100% of the time in my project.

### Steps to reproduce

1. Open the reproduction project from https://github.com/vibrunazo/godot-vector in Godot 4.1.1
2. Create a new method at the end of `grid.gd` called `my_new_test_method()`
3. Open `car.gd` and try to call the new method with `grid.my_new_test_method()` to the end of the `_ready()` method. Autocomplete will not show the new method.
4. Close Godot and reopen it. Your new method will now show up fine in autocomplete.

### Minimal reproduction project

https://github.com/vibrunazo/godot-vector

I've tested and reproduced it in this specific commit: https://github.com/vibrunazo/godot-vector/tree/061202c04b46eaca9dcaa399dfa56ecc7d02adc2

**Comment by dalexeev** [comment] 2023-08-17 03:59
* See also #67740.

**Comment by HauntedBees** [comment] 2023-10-14 00:47
I run into this issue regularly, too, but I've found that you can save a few seconds by just selecting **Reload Current Project** instead of fully closing and reopening Godot to resolve this.

**Comment by Nickelvad** [comment] 2023-11-08 20:03
Happens on v4.2.beta5 as well, using built-in editor and external one.

**Comment by Jules5** [comment] 2024-03-04 21:40
Still happening on v4.2.1, this is a bit annoying.

**Comment by Calinou** [comment] 2024-03-05 14:25
Thanks for the report! Consolidating in https://github.com/godotengine/godot/issues/78074, as this is due to the same cause (cyclic reference).

**Closed by Calinou** 2024-03-05 14:25 UTC
Labels: bug, topic:gdscript, topic:editor

**Comment by LO-0116** [comment] 2025-03-19 00:56
error found again in v4.4.stable.official [4c311cbee]
again, this error only starts appearing when a project has reached a certain "size", making it difficult to reproduce minimally. Affects class constants as well as variables. Cyclic reference was used in my project (e.g. "Gun" class having a reference to "Bullet" class and vice versa)
