### ISSUE TITLE
'Shift' in the Input Map for actions does not work for HTML5 exported projects

### ISSUE THREAD

**Issue by kcaze** [godotengine/godot#10120] opened 2017-08-06 07:35 UTC
**Operating system or device - Godot version:**
Windows 64 bit - 2.1.3.stable.

**NOTE: The example project below does NOT exhibit the bug. See my second comment below for an updated project + a slightly different description of the issue.**

**Issue description:**
The expected behavior is for `Input.is_key_pressed(KEY_SHIFT)` to return true when the Shift key is pressed in the browser. The actual behavior is that `Input.is_key_pressed(KEY_SHIFT)` always returns false.

**Steps to reproduce:**
1. Download the minimal example project.
2. Run the project inside the editor and press Shift. Notice that the Sprite disappears when Shift is pressed.
3. Export the project to HTML5, run the HTML5 exported project, and press Shift. Notice that the Sprite does **not** disappear.

**Link to minimal example project:**
[shift-test.zip](https://github.com/godotengine/godot/files/1202940/shift-test.zip)

**Comment by Listwon** [comment] 2017-08-20 16:25
Actually in your minimal example project it doesn't disappear in both the editor and the HTML5 exported project. You set the processing to false (set_process(false)). When I changed it to true, it worked as intended.

Also make sure, that your game window have focus (click with your mouse inside the game area, clicking on browser's title may not be enough).

**Comment by kcaze** [comment] 2017-08-22 00:31
@Listwon, oops you're right. I actually encountered this error when using `event.is_action_pressed()` originally and incorrectly tried to produce a simpler example using `Input.is_key_pressed()`.

Here's an [updated project file](https://github.com/godotengine/godot/files/1240448/shift-test.zip)
 and the corresponding [html5 export](https://github.com/godotengine/godot/files/1240449/html5.zip).

In this example, I added "Shift" to the input map for the "ui_accept" action and used `event.is_action_pressed('ui_accept')` and `event.is_action_released('ui_accept')` to control the sprite's hidden value. When I tested again with this project, the sprite disappeared in the editor but not in the exported HTML5 project. Can you see if you are able to reproduce the same issue with this example now?

**Comment by Listwon** [comment] 2017-08-22 07:43
@kcaze hah, it's ok. Yeah, now I can reproduce it. "Shift" doesn't work in the exported HTML5 project. Other keys assigned by default to "ui_accept" (Enter, Space) work. Strange.

**Comment by Listwon** [comment] 2017-08-22 08:57
It also doesn't work for "Ctrl" and both "Alt" keys (on a side note: left "Alt" is mapped as "Menu", right "Alt" is mapped as "Control+Menu").

**Comment by Zireael07** [comment] 2018-08-10 09:40
Is this still an issue in 3.x?

**Comment by akien-mga** [comment] 2018-09-17 14:12
The 2.1 branch is no longer actively worked on by engine developers, unless critical fixes are needed for current games in production. As such we are now closing non-critical bug reports affecting only the 2.1 branch.

Please comment if this was incorrectly triaged and is still relevant in 3.x versions.

**Closed by akien-mga** 2018-09-17 14:12 UTC
Labels: bug, platform:html5, topic:porting
