### ISSUE TITLE
Corrupted rendering and crash when adding two CollisionShapes to one StaticBody

### ISSUE THREAD

**Issue by WolfgangSenff** [godotengine/godot#25561] opened 2019-02-01 22:31 UTC
Godot version: 3.1beta3 official

OS/device: MacBook Pro, 2018, Radeon Pro 560X and embedded Intel UHD Graphics 630, 16 GB RAM, 2.6 GHz Intel Core i7, Mojave OS v10.14.2.

Issue description:
I was playing around in 3D attempting to create a box, and one way I'd done that in the past was to create a simple StaticBody and give it five CollisionShapes: one for each side (and the top is open). When I do this in the current version, it appears to "tear" the screen and crashes Godot. I'm a bit worried about my machine at this point, so going to stop attempting this.

Steps to reproduce:
1) Create a new project
2) Tap the 3D Scene option
3) Add a StaticBody child node to the root Spatial
4) Add a CollisionShape child node to the StaticBody.
5) Set the shape of it to Box Shape.
6) Add a second CollisionShape child node to the StaticBody.
7) Also set it to Box Shape.
8) Play around with the extents on the second CollisionShape.

Nothing is saved when this crash occurs, leading to no project which inherently reproduces it; you just have to try it.

**Comment by kaadmy** [comment] 2019-02-25 02:19
Can't reproduce here either with 3.1-beta7, Arch Linux/Geforce 940MX.

**Comment by akien-mga** [comment] 2019-02-25 08:19
Assuming fixed in the meantime. Please comment if you can still reproduce it.

**Closed by akien-mga** 2019-02-25 08:19 UTC
Labels: bug, topic:rendering
