### ISSUE TITLE
Node.owner is unset too early to be useful when nodes are being removed

### ISSUE THREAD

**Issue by Macksaur** [godotengine/godot#56498] opened 2022-01-04 23:09 UTC
### Godot version

3.4.stable

### System information

Windows 10

### Issue description

When removing nodes the owner is set as null in _exit_tree() / "tree_exiting" signal / NOTIFICATION_PREDELETE / NOTIFICATION_EXIT_TREE, etc.

I break up my complex objects to use composition and hook everything up via signals/notifications but I can't work with the node's owner at all in any of the expected locations in order to pass data/events out in the removal cases.

>void _exit_tree() virtual
>
>Called when the node is ***about to leave the SceneTree*** (e.g. upon freeing, scene changing, or after calling remove_child() in a script). *If the node has children, its _exit_tree() callback will be called last, after all its children have left the tree.*

The docs imply that it should be possible to react to and prepare for proper deletion of objects and that the owner will be valid at least at some point in order to communicate with the tree.

### Steps to reproduce

Create the following node hierarchy and attach a script to the child node:
![image](https://user-images.githubusercontent.com/86566939/148135686-0d71c7e1-2699-4e83-b7a7-98657e11dac6.png)

```gdscript
extends Node2D

func _check_owner(where:String) -> void:
	print("has owner: %s in \"%s\"" % [owner != null, where])

func _ready() -> void:
	_check_owner("_ready")

	owner.connect("tree_entered", self, "_check_owner", ["owner.tree_entered"])
	owner.connect("tree_exited", self, "_check_owner", ["owner.tree_exited"])
	owner.connect("tree_exiting", self, "_check_owner", ["owner.tree_exiting"])
	owner.queue_free()
	#queue_free() # can try this also, also false

func _notification(what: int) -> void:
	match what:
		NOTIFICATION_ENTER_TREE:      _check_owner("NOTIFICATION_ENTER_TREE")
		NOTIFICATION_EXIT_TREE:       _check_owner("NOTIFICATION_EXIT_TREE")
		NOTIFICATION_READY:           _check_owner("NOTIFICATION_READY")
		NOTIFICATION_MOVED_IN_PARENT: _check_owner("NOTIFICATION_MOVED_IN_PARENT")
		NOTIFICATION_PREDELETE:       _check_owner("NOTIFICATION_PREDELETE")
		NOTIFICATION_PARENTED:        _check_owner("NOTIFICATION_PARENTED")
		NOTIFICATION_UNPARENTED:      _check_owner("NOTIFICATION_UNPARENTED")
		NOTIFICATION_PREDELETE:       _check_owner("NOTIFICATION_PREDELETE")

func _exit_tree() -> void:
	_check_owner("_exit_tree")
```

Observe that there is nowhere functional to react to deletion that hasn't already been accounted for elswhere:
```
has owner: False in "NOTIFICATION_PARENTED" # ok? maybe?
has owner: True in "NOTIFICATION_ENTER_TREE" # ok
has owner: True in "_ready" # ok
has owner: True in "NOTIFICATION_READY" # ok

# ??? from this point on there is no avenue for communication

has owner: False in "_exit_tree" # bug
has owner: False in "NOTIFICATION_EXIT_TREE" # bug
has owner: False in "owner.tree_exiting" # bug
has owner: False in "owner.tree_exited"
has owner: False in "NOTIFICATION_UNPARENTED"
has owner: False in "NOTIFICATION_PREDELETE"
```

**Comment by akien-mga** [comment] 2022-01-05 09:24
Duplicate of #22840

**Closed by akien-mga** 2022-01-05 09:24 UTC
Labels: discussion, topic:core

**Comment by shanayyy** [comment] 2024-07-09 05:46
> has owner: False in "NOTIFICATION_PARENTED" # ok? maybe?

I think this may not be OK, I am sure that currently the owner of the node is set immediately after NOTIFICATION_PARENTED, so it is unreasonable to let the owner be null in NOTIFICATION_PARENTED
