### ISSUE TITLE
[WebGL2] Game shows magenta

### ISSUE THREAD

**Issue by ghost** [godotengine/godot#18687] opened 2018-05-07 18:14 UTC
**Godot version:** 3.0

**OS/device including version:** Ubuntu 18.04 LTS

**Browser:** Chromium 65.0.3325.181 (Official Build) Built on Ubuntu , running on Ubuntu 18.04 (64-bit)

**Issue description:**
Game Loads and screen is magenta.

**Steps to reproduce:**
Export a 3d game for HTML5.

**Minimal reproduction project:**
[Issue.zip](https://github.com/godotengine/godot/files/1980950/Issue.zip)

**Comment by karlygeeky** [comment] 2018-06-03 07:02
Well the bug no longer appears in chromium 66.

**Comment by karlygeeky** [comment] 2018-09-20 10:41
It happened again in Godot 3.0.6
Chrome version 68

**Comment by karlygeeky** [comment] 2018-09-20 15:04
But on Linux (Ubuntu 18.04 also running Chrome 68) it works fine.

**Comment by toiletsnakes** [comment] 2018-10-14 23:32
I'm seeing this as well.
godot 3.0.6 html export.

works fine on chrome in ubuntu, but not windows 10.
the color is Magenta btw, not bright purple

**Comment by OFTekk** [comment] 2018-12-11 23:45
I had the same problem with Godot 3.0.6 on Chrome 70/71 on Windows 10. It seems to be related with GL_MAX_FRAGMENT_UNIFORM_VECTORS limit inside WebGL2 of this versions of Chrome. I tried hacking little bit on Godot 3.0.6 sources and it can be overrided by changing RenderList::MAX_LIGHTS and MAX_REFLECTIONS to smaller values and also comparing MAX_LIGHTS not only against GL_MAX_UNIFORM_BLOCK_SIZE in "rasterizer_scene_gles3.cpp" but GL_MAX_FRAGMENT_UNIFORM_VECTORS too and use it to MIN function for "state.max_ubo_lights" and "state.max_ubo_reflections". I found this limiting (but not as much as in Chrome) behaviour in Firefox 63 (Windows 10).

I hope, that this information may be somehow useful.

**Comment by akien-mga** [comment] 2020-01-05 10:32
There were lots of fixes to the GLES3 backend for Godot 3.2, which might have solved this issue, if it's still reproducible. As there were no recent reports about it, it might also have been fixed by browsers.

Therefore I'll close this issue, but if anyone can still reproduce it on a recent Godot 3.2 build, please comment and we'll reopen.

**Closed by akien-mga** 2020-01-05 10:32 UTC
Labels: bug, platform:html5, topic:rendering

**Comment by weir6360** [comment] 2021-01-27 18:08
As of 1/27/20201, I am currently running into this issue with Godot Engine v3.2.3.stable.official, Chrome version 88.0.4324.104 (Official Build) (64-bit) on Windows 10.
