### ISSUE TITLE
Code disappearing when switching windows

### ISSUE THREAD

**Issue by zatherz** [godotengine/godot#5343] opened 2016-06-21 16:37 UTC
**Operating system or device - Godot version:**
Arch Linux (rolling release), 64-bit
Godot 2.0.3

**Issue description** (what happened, and what was expected):
When switching windows, unsaved code in a script is deleted. This is demonstrated here: https://www.youtube.com/watch?v=C4ATdUzA_XA&feature=youtu.be.

**Steps to reproduce:**
Could not reproduce, reopening the project and trying to reproduce didn't work, but bug is critical enough that I decided to post it.

**Comment by vnen** [comment] 2016-06-21 17:33
Thanks for the report. I'll archive since it is a duplicate of #4444.

**Closed by vnen** 2016-06-21 17:33 UTC
