### ISSUE TITLE
`always_on_top` is not working on Linux

### ISSUE THREAD

**Issue by reptofrog** [godotengine/godot#73690] opened 2023-02-21 17:16 UTC
### Godot version

v4.0.rc2.official `d2699dc7a`

### System information

Fedora Linux 37 (Workstation Edition), GNOME on Wayland

### Issue description

`always_on_top` preference has no effect on my system.

I have to turn it on manually in window settings each time I run my project.

### Steps to reproduce

1. Turn on `always_on_top`
2. Run the project
3. Observe that always on top mode is not enabled

**Comment by reptofrog** [comment] 2023-02-21 17:18
I can confirm that it doesn't work on Xorg either.

**Comment by Calinou** [comment] 2023-02-21 18:44
Duplicate of https://github.com/godotengine/godot/issues/48060.

**Closed by Calinou** 2023-02-21 18:44 UTC
