### ISSUE TITLE
Editor Viewport Artifacting with WorldEnvironment node set to Canvas Mode

### ISSUE THREAD

**Issue by blipk** [godotengine/godot#65125] opened 2022-08-31 04:42 UTC
### Godot version

4.0alpha14

### System information

Arch AMD64

### Issue description

Editor and running scene appears like this after setting up a node tree with WorldEnvironment and CanvasLayer:
![Screenshot from 2022-08-31 14-21-29](https://user-images.githubusercontent.com/45532845/187592787-1c3ef09f-3f56-4a0a-852c-518e84ab9e95.png)

![Screenshot from 2022-08-31 14-28-35](https://user-images.githubusercontent.com/45532845/187593696-01a1d4df-f560-4da5-bd99-d44fc2af07ce.png)

### Steps to reproduce

- Create new project with node tree:
```
┖╴Node
   ┠╴CanvasLayer
   ┠╴WorldEnvironment
   ┖╴Node3D
       ┖╴Camera3D
```
- Set CanvasLayer layer to -100
- Create Environment resource on WorldEnvironment node
- Set Environment resource properties Mode = Canvas and CanvasMax = -100 
- Interact with editor viewport and enjoy the light show

Also occurs in editor if the Node3D and Camera3D aren't present, however the running scene is just a blank canvas.

I just followed this comment here: https://old.reddit.com/r/godot/comments/p6ncxw/using_the_3d_camera_with_canvas_mode/h9ejcgu/?context=3

Not sure if this is an issue specific to my hardware, however only occurs with this specific node setup.

### Minimal reproduction project

Project and editor verbose log are attached.

[Arch.zip](https://github.com/godotengine/godot/files/9458465/Arch.zip)
[godot31-08-22_14:10:48.log](https://github.com/godotengine/godot/files/9458472/godot31-08-22_14.10.48.log)

**Comment by clayjohn** [comment] 2022-08-31 05:04
Duplicate of: https://github.com/godotengine/godot/issues/50423

Closing this issue so that we can track the issue in one place.

**Closed by clayjohn** 2022-08-31 05:04 UTC
