### ISSUE TITLE
4.0 beta 3: instance uniforms not working in Spatial shaders

### ISSUE THREAD

**Issue by zodywoolsey** [godotengine/godot#67986] opened 2022-10-28 20:57 UTC
### Godot version

4.0 beta 3

### System information

Windows 10

### Issue description

When creating a Spatial shader on a MeshInstance3D and attaching a visualshader.tres or a shader.gdshader which contains a 
`instance uniform [type] [name];`
the uniform does not appear in the editor and cannot be updated with gdscript

When I discovered this, the engine was not throwing errors and would just not display the shader at all

### Steps to reproduce

1. create project
1. create 3d scene
1. add MeshInstance3D
1. add a mesh (ex: BoxMesh) to the MeshInstance3D
1. add a ShaderMaterial to the material on the BoxMesh
1. add a Shader or Visual Shader to the ShaderMaterial
1. create an Instance Uniform in either of the shader types

### Minimal reproduction project

[shaderIssueTest.zip](https://github.com/godotengine/godot/files/9891775/shaderIssueTest.zip)

**Comment by KoBeWi** [comment] 2022-10-28 23:47
You might be attaching your material to a wrong material slot. We should probably have some configuration warning for that (if it's possible).

**Comment by zodywoolsey** [comment] 2022-10-29 01:37
> You might be attaching your material to a wrong material slot. We should probably have some configuration warning for that (if it's possible).

I attached it to the mesh's material slot, not the override. Normal uniforms appear and work correctly as you can see in the attached example project.

**Comment by KoBeWi** [comment] 2022-10-29 14:27
Well...
![image](https://user-images.githubusercontent.com/2223172/198836780-a45a992f-e945-4334-9c72-bb09bb71da25.png)
It shows correctly, just not where the regular uniforms. btw your "hasGdshader" node has a visual shader attached.

**Comment by zodywoolsey** [comment] 2022-10-29 16:43
> Well... ![image](https://user-images.githubusercontent.com/2223172/198836780-a45a992f-e945-4334-9c72-bb09bb71da25.png) It shows correctly, just not where the regular uniforms. btw your "hasGdshader" node has a visual shader attached.

Well, I guess it's working then. I suppose my dyslexia probably wasn't helping as to why I couldn't find it. I still feel that it's a bit confusing that instance qualified uniforms appear in a different location under a different label. Non-qualified Uniforms are labeled "Shader Parameters" while the others are labeled "Shader Uniforms". It makes sense from the standpoint of the implementation in the underlying render api, but just feels a bit inconsistent in the engine frontend.

Thank you for showing me where these are located in the editor.

**Comment by KoBeWi** [comment] 2022-10-29 16:47
Instance uniforms are properties of the node not material (because you configure it per-node), so I think it makes sense. Anyway, the issue is resolved, so closing.

**Closed by KoBeWi** 2022-10-29 16:47 UTC
Labels: bug, topic:rendering, topic:shaders, topic:3d
