### ISSUE TITLE
Game viewport is cropped when launching any project on hiDPI displays

### ISSUE THREAD

**Issue by ace24713** [godotengine/godot#40733] opened 2020-07-26 21:02 UTC
**Godot version:**

currently v3.2.3.rc1, but I've also reproduced on 3.2.2, 3.2.1 and 3.1.2

**OS/device including version:**

Windows 10 v1607; AMD Radeon RX5700 XT Driver 20.10.17.01
reproduced on GLES3 and GLES2, didn't try Vulkan
 
**Issue description:**

Everytime I run a godot game in windowed mode, the viewport starts cropped as visible in attached screenshot.
![clipping](https://user-images.githubusercontent.com/753186/88488890-9f04f880-cf5e-11ea-8583-d391ad99213d.png)
As you can see the view is masked with a white region, and only the corner is visible. The issue fixes itself if I resize the window even by a pixel. Moving the window does not fix the issue, neither does minimize->restore.

Notably, it seems the offset of the viewport is the same as the window starting position found in Editor Settings -> Run -> Window Placement. So if I specify custom position (x,y) as (0,0) then the issue goes away completely, and if I give a negative (x,y) then the viewport is cropped to the upper left corner instead of the lower right.

It doesn't happen in fullscreen either, but that might just be because fullscreen is effectively window position (0,0)

**Steps to reproduce:**

It happens in every single project of mine whenever you "play" the game or any scene, including blank/new projects, and even when launching from the project ui via the "run" button.

I asked a friend to try this, and they couldn't reproduce it. But it's consistently reproducible on my machine.

This is also a new bug for me. I recently upgraded my graphics card, so maybe that's related?

**Minimal reproduction project:**

This happens with all my projects, including demo projects and blank projects.

**Comment by Calinou** [comment] 2020-07-27 08:45
Related to https://github.com/godotengine/godot/issues/13017.

**Comment by ace24713** [comment] 2020-07-27 18:46
Why did you add HiDPI? Well it so happens I do use a 4k monitor, but I just double checked and I can still reproduce the issue at 1080p (Godot scaling set to auto in both cases)

**Comment by ace24713** [comment] 2020-07-30 18:14
So I recently found a few other games that have the same issue, I hadn't observed this earlier because it only happens in games that use opengl and don't launch in full screen. So this is not godot specific and it's probably a problem with my graphics driver.

I'm not sure if godot can do anything to mitigate the problem, so I'll leave this open and to the discretion of the godot team if it should be closed without action.

**Comment by Calinou** [comment] 2020-07-30 18:27
@ace24713 I can see the editor UI being scaled at a 2× factor on your screenshot, so this is an hiDPI-related issue. (Anytime the editor is being rendered at a scale higher than 100% is considered "hiDPI".)

**Comment by Calinou** [comment] 2021-04-09 21:01
Duplicate of https://github.com/godotengine/godot/issues/13017 (same cause).

**Closed by Calinou** 2021-04-09 21:01 UTC
Labels: bug, platform:windows, topic:rendering
