### ISSUE TITLE
Mono/C# editor/editor_settings.cpp:151 - EditorSettings::_get - Property not found:

### ISSUE THREAD

**Issue by 111ukasz111** [godotengine/godot#37636] opened 2020-04-06 16:32 UTC
**Godot version:**
Godot_v3.2.1-stable_mono_win64
**OS/device including version:**
windows 10 geforce 920 
intel core i7 5500U
msBuild
**Issue description:**
Create new project:
editor/editor_settings.cpp:151 - EditorSettings::_get - Property not found: mono/editor/editor_path_optional
Run:
editor/editor_node.cpp:5268 - An EditorPlugin build callback failed.
**Steps to reproduce:**
1.Create godot project on Godot_v3.2.1-stable_mono_win64.(Project created in earlier version is working)
editor/editor_settings.cpp:151 - EditorSettings::_get - Property not found: mono/editor/editor_path_optional

2.Create node2d 
3.Add c# script to node2d.
4.Run project
editor/editor_node.cpp:5268 - An EditorPlugin build callback failed.

**Minimal reproduction project:**
Project that not works: Rocket
[Rocket.zip](https://github.com/godotengine/godot/files/4439591/Rocket.zip)

Project that works:
[c#.zip](https://github.com/godotengine/godot/files/4439606/c.zip)

**Comment by Calinou** [comment] 2020-04-08 14:11
Duplicate of #36995. The "property not found" warning was fixed by #37210 (which will be available in Godot 3.2.2).

**Closed by Calinou** 2020-04-08 14:11 UTC
