### ISSUE TITLE
Inform the editor crash log file path in the documentation

### ISSUE THREAD

**Issue by chalcosoma** [godotengine/godot#30568] opened 2019-07-13 20:15 UTC
**Godot version:**

3.1

**OS/device including version:**

N/A

**Issue description:**

I didn't find where Godot saves the editor log file on Windows 7. I searched in documentation, in Godot Q&A in Google and in %AppData%. I need to see the file because the Godot is printing in the console very fast and I can't read at that speed.

In the Q&A I only found a question not answered about it. (https://godotengine.org/qa/46783/editor-chrashlog-corrupted-scene-file)

**Steps to reproduce:**

**Minimal reproduction project:**

N/A

**Comment by Calinou** [comment] 2019-09-07 12:44
By default, the editor doesn't log its output to a file. There are two ways to accomplish this:

## File logging

If you can edit a project's settings, you can enable **Logging > File Logging > Enable File Logging** in the. By default, logs will be written to `user://logs/` (see [Data paths](https://docs.godotengine.org/en/latest/tutorials/io/data_paths.html) for the location of `user://` on each platform).

## Standard output/error redirection

You can redirect any program's standard output and error streams to a file using a command prompt:

```cmd
path\to\godot_binary.exe > log.txt 2>&1
```

This will create a file named `log.txt` in the command prompt's current working directory.

**Comment by Calinou** [comment] 2021-09-01 19:10
Closing as a duplicate of https://github.com/godotengine/godot/issues/47379, as Godot doesn't save crash logs to a text file anyway. Doing so would require modifying each crash handler.

**Closed by Calinou** 2021-09-01 19:10 UTC
Labels: enhancement, topic:editor, documentation
