### ISSUE TITLE
2D/3D/Script views changing not working after using new Search Help button

### ISSUE THREAD

**Issue by n-pigeon** [godotengine/godot#2816] opened 2015-11-18 23:40 UTC
When you use new Search Help button in Script Editor and select one entry, you can't change view nor by buttons and hotkeys F1/2/3. Only using Scene docker by clicking nodes or script buttons works.

**Comment by akien-mga** [comment] 2015-11-18 23:47
Duplicate of #2807, it was not that far down in the list ;)

**Closed by akien-mga** 2015-11-18 23:47 UTC
