### ISSUE TITLE
Can't open Animation tab with if a shader resource is expanded in the inspector, reverts to Shader Editor again

### ISSUE THREAD

**Issue by lostminds** [godotengine/godot#70705] opened 2022-12-29 14:59 UTC
### Godot version

4.0beta10

### System information

macOS 13.0.1

### Issue description

If you expand a shader resource in the inspector panel this automatically opens the Shader Editor tab in the bottom panel. However, there seems to be a bug with the Animation tab that somehow triggers this again when the animation tab is opened (maybe it refreshes the inspector?), resulting in the Shader Editor immediately being opened again. So, if you have a shader resource expended in the inspector you can't open the Animation tab to edit animations. If you just collapse the shader resource again it works as expected.

https://user-images.githubusercontent.com/17763524/209969815-adb9cd73-1cd7-4756-9af2-9042ccec9442.mov

I tried this in 4.0 beta 8 as well, and interestingly it had the same problem but also another bug/hack that caused the expanded shader resource to be collapsed when it switched back to the Shader Editor. So if you clicked the Animation tab a second time you could now switch to it.

### Steps to reproduce

Create new scene (2d or 3d)
Add an AnimationPlayer to the scene so there's something in the Animation tab
Open the animation tab with the Animation player selected
Create something (2d or 3d) that has a material
Assign a new shader material
Create a new shader for the material
Expand the material and shader resources in the inspector
Notice that this opens the shader editor in the bottom
Now try to open the animation tab, notice it will switch back to the shader editor tab immediately

### Minimal reproduction project

[animation_tab_test.zip](https://www.lostminds.com/godot/animation_tab_test.zip)

**Comment by Calinou** [comment] 2022-12-29 21:13
I can confirm this on 4.0.beta10 while working on https://github.com/godotengine/godot-demo-projects/pull/809.

**Comment by TokageItLab** [comment] 2022-12-31 10:01
Duplicate of #70588

**Comment by lostminds** [comment] 2023-01-26 09:00
This bug, and probably https://github.com/godotengine/godot/issues/70588 then too has reappeared again in 4.0b15 : If you have a Shader resource expanded in the inspector you can't switch to the Animation tab as it will keep the Shader Editor tab open.

**Comment by akien-mga** [comment] 2023-01-26 09:02
CC @KoBeWi

**Comment by KoBeWi** [comment] 2023-01-26 14:32
Caused by #70909
It's the same issue as the one fixed by the reverted PR, i.e. pressing Animation will reload inspector and reopen all properties.

**Closed** 2023-01-31 13:21 UTC
Labels: bug, topic:editor, confirmed, usability, topic:animation
