### ISSUE TITLE
focus error between gdscript & shader editor

### ISSUE THREAD

**Issue by frankiezafe** [godotengine/godot#25673] opened 2019-02-06 22:46 UTC
**Godot version:**

master branch, commit 96899b7ee1cb442ce9625232d558670fe7011c2c

**OS/device including version:**

 Linux Mint 18.2, Linux 4.8.0-53-generic x86-64, GTX 1080 

**Issue description:**

You need to have shader editor and gdscript editor open at the same time to reproduce this bug.

When commenting code with ctrl+k, the shader receive the command, no way to send the command to the gdscript editor without closing the shader editor first.

**Steps to reproduce:**
- open a shader and open editor
- switch to Script tab and open a .gd
- press ctrl + k 

Godot rocks!

**Comment by Chaosus** [comment] 2019-02-07 13:52
Duplicate of #12916

**Closed by Chaosus** 2019-02-07 13:52 UTC
