### ISSUE TITLE
[3.2.4 beta 2] Adding Normal Maps leads to defective rendering with Batching (GLES3) enabled.

### ISSUE THREAD

**Issue by RPicster** [godotengine/godot#43677] opened 2020-11-19 09:54 UTC
**Godot version:**
3.2.4 beta 2 - official build (Win 64)

**OS/device including version:**
Windows 10 Pro - 10.0.19042
Nvidia RTX 2080

**Issue description:**
When using normalmaps on sprites (I also tested it with Tilemaps and it produced the same result), the result is either not rendered, has strange coloring or is very dark.

**Steps to reproduce:**
* Create a new project
* Create a new scene (2D)
* Add a Sprite
* Add a normal map to the Sprite

**Minimal reproduction project:**
[3.2.4b2_normalmap_rendering.zip](https://github.com/godotengine/godot/files/5565902/3.2.4b2_normalmap_rendering.zip)

**Comment by lawnjelly** [comment] 2020-11-19 10:27
Looks like caused by the same bug as #43673.

So also fixed by #43679.

**Comment by akien-mga** [comment] 2020-11-19 10:56
Fixed by #43679.

**Closed by akien-mga** 2020-11-19 10:56 UTC
Labels: bug, topic:rendering
