### ISSUE TITLE
Projects freezing whilst loading in 3.x branch

### ISSUE THREAD

**Issue by lawnjelly** [godotengine/godot#49663] opened 2021-06-16 17:48 UTC
### Godot version

3.x branch 465ab36

### System information

Linux Mint 20, GLES3, Intel HD graphics 630

### Issue description

There is a recent (last few days is since I made last pull) regression in 3.x branch causing extremely long loading times in some projects, so slow that it fails to load and acts frozen.

`StreamTexture::load` seems to be very slow, and being called multiple times for the same textures again and again and again, as if it is not detecting that they are duplicates used in several meshes.

### Steps to reproduce

Not sure yet, will try and make minimum reproduction project asap.

### Minimal reproduction project
[SlowLoadingBug.zip](https://github.com/godotengine/godot/files/6665332/SlowLoadingBug.zip)

**Comment by lawnjelly** [comment] 2021-06-16 18:48
I think it's actually this PR causing it : #49625 but not 100% sure yet.

**Comment by pouleyKetchoupp** [comment] 2021-06-16 19:26
I'll investigate as soon as I can. I suspect it's specific to `StreamTexture` or a certain setup, because I haven't spotted this issue when testing, even with a complex project.

@lawnjelly It there's any minimal project you can share, it would help identifying the faulty case. But if I'm able to reproduce it myself I'll let you know.

**Comment by lawnjelly** [comment] 2021-06-16 19:28
Yup I managed to make one, see in the first post, I edited it in.

**Comment by pouleyKetchoupp** [comment] 2021-06-16 23:14
@lawnjelly Thanks for catching the issue and for the MRP, I've just opened #49668 to fix the regression. Sorry about that!

**Comment by akien-mga** [comment] 2021-06-16 23:24
Fixed by #49668.

**Closed by akien-mga** 2021-06-16 23:24 UTC
Labels: bug, regression, topic:core
