### ISSUE TITLE
PRIMITIVE_POINTS not visible in HTML5 export (3.1.2 and 3.2beta3)

### ISSUE THREAD

**Issue by charliewhitfield** [godotengine/godot#34213] opened 2019-12-09 02:03 UTC
**Godot version:**
Problem observed in both 3.1.2 and 3.2-beta3(official) **HTML5 exports**, GLES2

**OS/device including version:**
Tested using Chrome, Firefox and MSEdge (HTML5 export from Windows 10)

**Issue description:**
PRIMITIVE_POINTS are not visible in HTML5 export in Godot versions tested (3.1.2 and 3.2-beta3), but are visible in editor runs and Windows 10 exports (all GLES2).

My project uses Mesh.PRIMITIVE_POINTS in an ArrayMesh to display asteroids. Here is what it is supposed to look like. (Yes, I know there are a heck of a lot of points! But the problem is the same if I reduce the number of asteroids to just a few hundred.)
![I Voyager asteroids](https://user-images.githubusercontent.com/41218520/70401000-b1e0b200-19fb-11ea-9409-0514dc59be2c.jpg)

**Steps to reproduce:**
In any project using PRIMITIVE_POINTS, export to HTML5.

**Minimal reproduction project:**
~This is not a minimal project, but you can download "Planetarium" under Godot Projects on the [I, Voyager Download page](https://ivoyager.dev/download/). Run the project and click "All Asteroids" in the panel on the lower right. Sorry, this will take a while to download & import due to image assets. Please let me know if a smaller project is needed for testing.~ EDIT: That's a terrible MRP. Here's a real one: [test_primitive_points.zip](https://github.com/godotengine/godot/files/3946976/test_primitive_points.zip)

**Comment by charliewhitfield** [comment] 2019-12-10 17:33
OK, I've come to realize that what I did to make those points is not at all obvious. I'll work up a proper minimal project and post it here shortly.

**Comment by clayjohn** [comment] 2019-12-10 18:31
Try building from master and testing. I have a feeling this is the same problem as https://github.com/godotengine/godot/pull/34237

**Comment by charliewhitfield** [comment] 2019-12-10 20:21
@clayjohn, I'm not quite up to speed on compiling Godot (I'll get there...). It seem to me a different issue, since this one doesn't seem to be related to distance.

Here's an actual minimum reproduction project: [test_primitive_points.zip](https://github.com/godotengine/godot/files/3946955/test_primitive_points.zip)

Windows Export (3.2beta3.official):
![Screenshot (76)](https://user-images.githubusercontent.com/41218520/70565099-68a97300-1b5f-11ea-98c6-9af467e6ec85.jpg)

HTML5 export (3.2beta3.official):
![Screenshot (75)](https://user-images.githubusercontent.com/41218520/70565084-60e9ce80-1b5f-11ea-90cc-a6fbe4bb5cc7.jpg)

Here's the test code:
```
extends MeshInstance

func _ready():
	var circle_vertecies1 := PoolVector3Array()
	var circle_vertecies2 := PoolVector3Array()
	var th := 0.0
	for i in range(100):
		th = i * TAU / 100.0
		var vertex := Vector3(sin(th), cos(th), 0.0)
		circle_vertecies1.append(vertex)
		circle_vertecies2.append(vertex / 1.5)

	var points_mesh := ArrayMesh.new()
	var arrays1 := []
	arrays1.resize(ArrayMesh.ARRAY_MAX)
	arrays1[ArrayMesh.ARRAY_VERTEX] = circle_vertecies1
	var arrays2 := []
	arrays2.resize(ArrayMesh.ARRAY_MAX)
	arrays2[ArrayMesh.ARRAY_VERTEX] = circle_vertecies2
	points_mesh.add_surface_from_arrays(Mesh.PRIMITIVE_LINE_LOOP, arrays1, [], VisualServer.ARRAY_FORMAT_VERTEX)
	points_mesh.add_surface_from_arrays(Mesh.PRIMITIVE_POINTS, arrays2, [], VisualServer.ARRAY_FORMAT_VERTEX)
	mesh = points_mesh
```

**Comment by clayjohn** [comment] 2019-12-10 21:22
Thanks, I'll test it tonight and let you know how it goes!

**Comment by clayjohn** [comment] 2019-12-11 05:05
I am able to reproduce. I think that in HTML ``POINT_SIZE`` is defaulting to ``0``. Because if you set ``POINT_SIZE`` to any value, the points appear.

**Comment by charliewhitfield** [comment] 2019-12-11 13:55
`POINT_SIZE` **is** set in my solar system simulator, but they still aren't showing in HTML5 export specifically. Let me see if I can reproduce in the MRP.

**Comment by clayjohn** [comment] 2019-12-11 15:04
Likely a combination of this and https://github.com/godotengine/godot/pull/34237. I assume your asteroids are far away from the camera.

**Comment by charliewhitfield** [comment] 2019-12-11 15:18
@clayjohn, Would those distances be much different than LINE_LOOP? I think I will have to work up a specific MRP for my asteroids. My current guess is that it has something to do with the way I pass orbital parameters to the shader not working in HTML5. I build the asteroids using ArrayMesh, passing "Keplerian elements" (the fixed, unchanging part) via NORMAL, COLOR, etc. Then I make them orbit by updating only "time" uniform. Here's the shader part (you can see that POINT_SIZE was never the problem here):
```
shader_type spatial;
render_mode unshaded, cull_disabled, skip_vertex_transform;

uniform float time = 0.0;
uniform float point_size = 3.0;
uniform vec3 color = vec3(0.0, 1.0, 0.0);
//varying flat vec3 test_color;

void vertex() {
	// orbital elements
	float a = NORMAL.x;
	float e = NORMAL.y;
	float i = NORMAL.z;
	float Om = COLOR.x;
	float w = COLOR.y;
	float M0 = COLOR.z;
	float n = COLOR.w;
	
	float M = M0 + n * time;
	M = mod(M + 3.141592654, 6.283185307) - 3.141592654; // -PI to PI
	float E = M + e * sin(M);
	float dE = (E - M - e * sin(E)) / (1.0 - e * cos(E));
	E -= dE;
	int steps = 1;
	while (abs(dE) > 1e-5 && steps < 10) {
		// Some TNOs never converge w/ threshold 1e-6. I think they get close in
		// several steps and then flip between two values outside the threshold,
		// perhaps due to single-precision floats.
		dE = (E - M - e * sin(E)) / (1.0 - e * cos(E));
		E -= dE;
		steps += 1;
	}
	float nu = 2.0 * atan(sqrt((1.0 + e) / (1.0 - e)) * tan(E / 2.0));
	float r = a * (1.0 - e * cos(E));
	float cos_i = cos(i);
	float sin_Om = sin(Om);
	float cos_Om = cos(Om);
	float sin_w_nu = sin(w + nu);
	float cos_w_nu = cos(w + nu);
	float x = r * (cos_Om * cos_w_nu - sin_Om * sin_w_nu * cos_i);
	float y = r * (sin_Om * cos_w_nu + cos_Om * sin_w_nu * cos_i);
	float z = r * sin(i) * sin_w_nu;
	VERTEX = (MODELVIEW_MATRIX * vec4(x, y, z, 1.0)).xyz;
	POINT_SIZE = point_size;
}

void fragment() {
    ALBEDO = color;
}
```

**Comment by clayjohn** [comment] 2019-12-11 16:14
What im saying is, I think your running into two bugs at once. 1) is that points were not showing at all on web without a default size and 2) is that points that are far away are disappearing. 

You need both fixes to be merged before you can test.

**Comment by charliewhitfield** [comment] 2019-12-11 16:20
I got you. You can certainly close this issue.

I may post an asteroid MRP here later anyway. But I'll also compile Godot (about time for me to learn that) and try with your new fixes.

**Comment by clayjohn** [comment] 2019-12-11 16:30
We'll close the issue when #34262  is merged :) then you can double check that it works with a nightly build.

**Comment by charliewhitfield** [comment] 2019-12-11 17:16
I will do that. I did make a new MRP, if you are willing to indulge me in one more test...
[asteroid_test.zip](https://github.com/godotengine/godot/files/3951662/asteroid_test.zip)

**Comment by capnm** [comment] 2019-12-11 22:18
> I did make a new MRP, if you are willing to indulge me in one more test...
> while (abs(dE) > 1e-5 && steps < 10) {

gles2 compiles to webgl1, which doesn't support dynamic loops.
Don't do that if you want to export gles2 to HTML.

**Comment by charliewhitfield** [comment] 2019-12-11 22:56
@capnm, That was the problem. Thank you!

Should this be documented? I would not have figured that out without expert knowledge. There is no hint of this in either [Shading Language](https://docs.godotengine.org/en/latest/tutorials/shading/shading_reference/shading_language.html) nor [Export for the Web: Limitations](https://docs.godotengine.org/en/latest/getting_started/workflow/export/exporting_for_web.html#limitations).

**Comment by clayjohn** [comment] 2019-12-12 02:07
Should definitely be documented.

**Comment by charliewhitfield** [comment] 2019-12-12 02:29
Opened a doc issue [here](https://github.com/godotengine/godot-docs/issues/2980).

**Closed** 2019-12-12 05:45 UTC
Labels: bug, topic:rendering
