### ISSUE TITLE
tileset_script vs script in tileset editor!!

### ISSUE THREAD

**Issue by xDGameStudios** [godotengine/godot#23385] opened 2018-10-29 17:50 UTC
**Godot version:**
v3.1.alpha.calinou.0a80cea

**OS/device including version:**
Mac OSX Mojave 10.14

**Issue description:**
TileSets have two script assigning references. The "script" and the "tileset_script":

<img width="252" alt="captura de ecra 2018-10-29 as 17 39 57" src="https://user-images.githubusercontent.com/10358443/47669038-dbe16700-dba1-11e8-8433-3c226b50c780.png">

the top one doesn't show exported variables in the inspector but the variables can be accessed using 

`$Tilemap.tile_set.variable_name;`

the bottom one shows export variables inside the TileSet inspector editor but they can't be accessed anywhere else... is just like they don't exist!

**Small steps to verify bug**
For example here I have set a "script" and no tileset_script:

<img width="245" alt="captura de ecra 2018-10-29 as 18 04 03" src="https://user-images.githubusercontent.com/10358443/47670435-0e409380-dba5-11e8-9f4d-06cc1533002f.png">

when I print the script reference of the tileset:

<img width="276" alt="captura de ecra 2018-10-29 as 18 02 02" src="https://user-images.githubusercontent.com/10358443/47670344-d6395080-dba4-11e8-8ada-c50168b9b939.png">

I get this in the console window:

<img width="122" alt="captura de ecra 2018-10-29 as 18 02 10" src="https://user-images.githubusercontent.com/10358443/47670364-e5200300-dba4-11e8-97a3-1bd29703a267.png">

so there is no reference the the script even though I have it set. So I can't access the script variables even though I can export the variables in the inspector (first image)!!

Now if I remove the script and add it as a tileset_script:

<img width="247" alt="captura de ecra 2018-10-29 as 18 05 46" src="https://user-images.githubusercontent.com/10358443/47670513-4b0c8a80-dba5-11e8-8bf0-171302d06efa.png">

And when I print the reference to the script I get this output:

<img width="154" alt="captura de ecra 2018-10-29 as 18 07 05" src="https://user-images.githubusercontent.com/10358443/47670591-798a6580-dba5-11e8-85e4-c168118ff129.png">

Now I can access the script, and variables but as you can see I no longer can export the variables from the script.

**Comment by bojidar-bg** [comment] 2018-10-30 11:38
Note that the `script` property is refers to `TilesetEditorContext.script`, and not to `Tileset.script`.
`tileset_script` gets translated behind-the-scenes to `Tileset.script`.

Related to #23305, probably both can be fixed in one go.

**Comment by xDGameStudios** [comment] 2018-10-30 16:29
> Note that the `script` property is refers to `TilesetEditorContext.script`, and not to `Tileset.script`.

Hmmm okay then. Another thing is that creating a script for TileSet from within the inspector doesn't create a script that extends from TileSet, like it happens automatically with Nodes.

Another thing is I would like to know in what applications may the TilesetEditorContext.script be used?!

**Comment by willnationsdev** [comment] 2019-01-11 21:10
Seeing as how [TileSetEditorContext isn't an existing type in the scripting API](https://docs.godotengine.org/en/latest/classes/class_tileseteditorcontext.html), there isn't much use in it having a "script" property in the first place (since you can't extend it). As such, this issue can be "fixed" by simply not exposing the property. This makes the fact that `tileset_script` == `tileset.script` a bit more clear.

**Comment by MarianoGnu** [comment] 2019-01-11 23:54
This property is inherited from the Object class. The only reason it is there is because i dont know how to prevent it from being there.

**Comment by clayjohn** [comment] 2019-04-20 06:00
Is this still reproducible? https://github.com/godotengine/godot/issues/23305 was closed.

**Comment by bojidar-bg** [comment] 2019-04-20 09:23
It was fixed in #24205 (3.1).

**Closed by bojidar-bg** 2019-04-20 09:23 UTC
Labels: bug, topic:core, topic:editor
