### ISSUE TITLE
Mouse cursor disappears when leaving slider input in inspector after edition

### ISSUE THREAD

**Issue by Cevantime** [godotengine/godot#66909] opened 2022-10-04 21:51 UTC
### Godot version

4.0.beta2.mono.official (commit f8745f2f7)

### System information

Linux Mint, Vulkan, Nvidia Geforce GTX 1660 Ti, nvidia-driver-515.65.01

### Issue description

When I edit a slider value (float or integer) in the inspector and leave the mouse, the cursor disappears often (~80% of the times). After switching to another application, the cursor is back and I can move back to Godot and use the mouse again. Moving 
the cursor inside the selected input also changes the input value :  
![bug](https://user-images.githubusercontent.com/5015561/193936247-5c256d03-b69c-47c0-a969-117d536bfe77.gif)

Note that this also happens when I move the cursor _back_ into the input while it has been edited and is still selected.

### Steps to reproduce

Open any project. Try to change the value of a slider value in the inspector (float or int) and move the cursor inside the selected input. It should disappear quite often (roughly 80% of the time)

### Minimal reproduction project

No reproduction project is needed, since I can reproduce in any project on my system.

**Comment by Calinou** [comment] 2022-10-04 22:10
Can you reproduce this after enabling **Single Window Mode** in the Editor Settings then restarting the editor?

**Comment by Cevantime** [comment] 2022-10-05 07:40
Hello, I confirm I can reproduce it in single window mode.

**Comment by Sauermann** [comment] 2022-10-06 00:48
For me on Debian Linux with Xfce window manager I can not reproduce this issue with non-mono Godot
When I follow your instructions, my mouse cursor changes its form to the "Text"-mouse cursor:

https://user-images.githubusercontent.com/6299227/194187267-420fad9d-06ff-45a0-8ab4-a52a5df51831.mp4

Which window manager do you use?

In your video it looks like the mouse button gets pressed, which explains the vanishing mouse cursor and the value-change and afterwards gets into an inconsistent state (mouse is not pressed, but application assumes, that it is).

**Comment by salamandars** [comment] 2022-10-07 01:31
Are you using a laptop trackpad? I can reproduce this on windows but only by double-tapping inside the trackpad. Regular mouse interactions work normally.

**Comment by Cevantime** [comment] 2022-10-07 23:04
@salamandars 
Yes, I am ! 
@Sauermann, I'm using Cinnamon. Maybe I haven't been clear enaough. To reproduce, you have to edit the value, then press enter to validate, and only then try to move the cursor.
But as @salamandars says, it might be linked to trackpads.

**Comment by salamandars** [comment] 2022-10-10 09:24
Here's what I think is happening. A common way to click on (at least some) trackpads is to do a quick double-tap inside the touch area. Technically this actually registers as a double-click, at least in godot.

So when I do this on a spinbox, it seems to fire off 4 mouse button events:
1. "Left mouse button Pressed" **-> received by `EditorSpinSlider`**
2. "Left mouse button Not Pressed" **-> received by `EditorSpinSlider`**
3. "Left mouse button Pressed (Double click)" - almost the exact same time as 2. **-> received by `EditorSpinSlider`**
_3.5. usually mouse motion event occurs here due to nature of tapping_
4. "Left mouse button Not Pressed" **-> received by `LineEdit`**

Guesswork: The first two events work correctly to put the `LineEdit` into input mode... but perhaps because the second click comes at the same time, it seems to also fire off _before_(?) the deferred call to switch focus to the line edit. So the second mouse DOWN event is received by the `EditorSpinSlider`, and (with a bit of accidental mouse motion) it also triggers the `grabbing_spinner` mouse capture behavior. However the second UP event is received by the `LineEdit` object instead, so the mouse is never released.

Perhaps a fix for this would be to move the mouse capturing behavior to `Viewport` so that it can keep track of mouse events better?

**Comment by mastir** [comment] 2022-11-14 20:24
Hey @salamandars, i have same bug on ubuntu 22.04 without touchpad. And even without click event. Just click on input, write some number and press enter. Afte any move mouse starts altering already inactive input without cursor

**Comment by snougo** [comment] 2022-11-25 08:28
I tested in Godot4 beta6 on Mac and mouse cursor only disappears when using mouse (or trackpad) draging to change inspector value



https://user-images.githubusercontent.com/64188282/203935305-a2cb3b98-27cc-4c06-ac31-433c5d3123d6.mov

**Comment by akien-mga** [comment] 2023-02-16 22:19
Yeah this was fixed a while ago. The behavior described by @snougo is the intended behavior.

**Closed by akien-mga** 2023-02-16 22:19 UTC
Labels: bug, topic:editor, needs testing, topic:gui

**Comment by PIZZA-ALERT** [comment] 2024-06-30 17:30
Similar but different issue happening to me and some others online. Mouse cursor straight up hidden every time it's hovered over text input.
https://github.com/godotengine/godot/issues/93748
