### ISSUE TITLE
[4.0] EditorInspector doesn't reset scroll when a different object is inspected

### ISSUE THREAD

**Issue by AnidemDex** [godotengine/godot#64259] opened 2022-08-11 04:34 UTC
### Godot version

v4.0.alpha13.official [59dcddc45]

### System information

Windows 11 x64, Lenovo 81WH

### Issue description

If you select an object that has a lot of properties, scrolls a little and then select another object, `EditorInspector` will keep the scroll value.

https://user-images.githubusercontent.com/7025991/184065062-78832db9-1d8c-4760-8610-27e14af0a27d.mp4

This doesn't happens in 3.x

### Steps to reproduce

1. Select an object (node, resource) to inspect it in editor.
2. Select an object in scene (node) or a resource. It doesn't matter, just try to inspect something that has a lot of values.
3. Scroll in that inspector.
4. Now select object described in 1

**Comment by Rindbee** [comment] 2022-08-18 08:22
Duplicate of #63334, which has been fixed in alpha14.

**Closed** 2022-08-18 13:36 UTC
Labels: bug, topic:editor, regression
