### ISSUE TITLE
Editor inspector being hidden when the window size is small

### ISSUE THREAD

**Issue by floppyhammer** [godotengine/godot#59502] opened 2022-03-25 04:42 UTC
### Godot version

v4.0.alpha.custom_build [391633760]

### System information

Windows 11, Vulkan

### Issue description

![editor_layout](https://user-images.githubusercontent.com/28705694/160054390-f12ef46a-a952-4df8-95cb-6e213d3c42f1.gif)

How the editor currently adjusts dock layout makes it really hard to use Godot with small window size (not really small actually). A common scenario is learning Godot when watching tutorials. I suppose a better way to handle this is to make the operation bar scrollable, which has fixed size currently and decides the minimum width of the scene view.

![image](https://user-images.githubusercontent.com/28705694/160055199-2b3cf494-fa45-4c82-b27a-d597fd4faa42.png)

### Steps to reproduce

Try to use Godot with small window size, the inspector dock would be hidden.

**Comment by Zireael07** [comment] 2022-03-25 08:05
Hm, on 3.4 I see the inspector still (but it limits my scripting editor space a lot).

A candidate for an editor settings toggle?

**Comment by floppyhammer** [comment] 2022-03-25 08:36
@Zireael07 I think 3.x has got the same behavior. It just on 3.x we don't have very wide operation bar so the inspector won't be hidden much.

![image](https://user-images.githubusercontent.com/28705694/160084437-344c2be7-7943-4a55-b152-25bc454735d0.png)

**Comment by Calinou** [comment] 2022-03-25 15:51
Duplicate of https://github.com/godotengine/godot/issues/31133 (same cause).

**Closed by Calinou** 2022-03-25 15:51 UTC
