### ISSUE TITLE
Inspector shows MultiNodeEdit when only one node is selected after deselecting

### ISSUE THREAD

**Issue by timothyqiu** [godotengine/godot#49451] opened 2021-06-09 03:08 UTC
### Godot version

3.3.stable 3.x(f3d931410) master(090e4c4abd)

### System information

macOS 11.4

### Issue description

I selected two nodes in the editor and then decided to only change one of them, so I deselected the other one. But changing properties in the Inspector changes both nodes.

The inspector still shows `MultiNodeEdit` after the deselection.

Instead of CTRL-clicking to deselect one node, you can also click one of the nodes in the Scene dock. In this case, clicking the second node works fine, but clicking the first node still shows `MultiNodeEdit`.

### Steps to reproduce

1. Create an empty scene
2. Add two nodes (e.g. drag two icon.png into the scene)
3. Select both of them
4. Select only one of them by CTRL/CMD click the other one
5. Now the Inspector should still say `MultiNodeEdit`, and changing any property would affect both the nodes

**Comment by unsignedFoo** [comment] 2021-06-10 09:37
I'll take it

**Comment by akien-mga** [comment] 2021-06-16 00:14
Reopening as #49482 caused a regression and was reverted.

**Comment by unsignedFoo** [comment] 2021-06-17 08:41
Found a fix, and now it works, I'll record a video

**Comment by timothyqiu** [comment] 2021-08-16 02:01
Reopening as this is still reproducible on the latest `master` (1ed00dca88) and `3.x` (66497e2ecb) following the steps in OP.

**Comment by EricEzaM** [comment] 2021-09-29 07:33
Can't reproduce in master v4.0.dev.custom_build [f410852f9]

**Comment by akien-mga** [comment] 2021-09-29 07:37
Likely fixed by #52172.

**Closed by akien-mga** 2021-09-29 07:37 UTC
Labels: bug, topic:editor
