### ISSUE TITLE
Renaming a class is not updated in the script assigned to a node

### ISSUE THREAD

**Issue by Torguen** [godotengine/godot#52372] opened 2021-09-03 08:00 UTC
### Godot version

3.3.3 stable mono

### System information

w10 64

### Issue description

I had everything correct and running.
Then I changed the name of a class like this:
areaMouse.cs -> AreaMouse.cs
Later when trying to execute, Godot indicates the error of the image to me.
Godot recognized the renaming in the file explorer dock but did not recognize the scripts assigned to nodes.
![Captura](https://user-images.githubusercontent.com/19652075/131971424-6a3c3120-cb80-41bd-b216-9ec36c7a2ce3.PNG)

### Steps to reproduce

Create a class asigned to a node
change the name of the class

### Minimal reproduction project

...

**Comment by raulsntos** [comment] 2021-09-03 10:23
Did you rename the file from Godot, an external editor (like VSCode) or the File Explorer? Renaming from Godot should update the references to the new name but doing it from somewhere else would be impossible to keep track of.

Your case is a little special because the name only changed the casing so I think Godot "recognized" the new name by chance, because Windows file system is not case sensitive (so both names refer to the same file).

Also, I think the C# class has to have the same name as the file so make sure the class is also named `areaMouse` and not `AreaMouse`. This could be why it can't find it.

**Comment by Torguen** [comment] 2021-09-03 20:09
I changed the name from VSCode.

The class is called "AreaMouse" and the file "AreaMouse.cs"

**Comment by raulsntos** [comment] 2021-09-03 20:26
Since you changed it from outside Godot there will be references to the old name in the scene/resource files, you can manually open the `.tscn`/`.tres` files in VSCode and fix it, I don't think there's anything Godot can do about changes made from the outside.

What I meant with Windows not being case sensitive is it can't tell the difference between `AreaMouse` and `areaMouse` so it thinks it's the same file but it's not and that causes unexpected issues when the name is used with different casing in different places.

**Comment by Calinou** [comment] 2021-09-03 23:19
Is this issue considered a duplicate of https://github.com/godotengine/godot/issues/22475 given it has the same cause?

**Comment by raulsntos** [comment] 2021-09-04 11:09
I'd say it is.

**Closed** 2021-09-04 15:23 UTC
Labels: topic:mono
