### ISSUE TITLE
[Compositor] unable to access depth texture in shader

### ISSUE THREAD

**Issue by juspky** [godotengine/godot#99493] opened 2024-11-21 12:49 UTC
### Tested versions

- Reproducible in 4.3

### System information

Godot v4.3.stable.mono - Windows 10.0.22631 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3070 Ti (NVIDIA; 32.0.15.6614) - AMD Ryzen 7 7700X 8-Core Processor (16 Threads)

### Issue description

I was trying to use the compositor for post processing. And found no way to access the depth_image in a similar way as I can access color_image.

If I try to run the provided code I get:
`Image (binding: 1 index 0) needs the TEXTURE_USAGE_STORAGE_BIT usage flag set in order to be used as uniform.`

I also tried copying  the depth texture into a new texture to set the storage bit there but I can't due `TEXTURE_USAGE_CAN_COPY_FROM_BIT` also not being set.

### Steps to reproduce

I've followed [the compositor](https://docs.godotengine.org/en/stable/tutorials/rendering/compositor.html) guide and tried to add the depth_image I receive using render_scene_buffers.get_depth_layer() to the UniformSet.

```gdscript

@tool
extends CompositorEffect
class_name PostProcessShader

const template_shader : String = "#version 450

// Invocations in the (x, y, z) dimension
layout(local_size_x = 8, local_size_y = 8, local_size_z = 1) in;

layout(rgba16f, set = 0, binding = 0) uniform image2D color_image;
layout(rgba16f, set = 0, binding = 1) uniform image2D depth_image;

// Our push constant
layout(push_constant, std430) uniform Params {
	vec2 raster_size;
	vec2 reserved;
} params;

// The code we want to execute in each invocation
void main() {
	// number between 0 and resolution for example gl_GlobalInvocationID.x = [0, 1919] at full HD
	ivec2 uv = ivec2(gl_GlobalInvocationID.xy);
	ivec2 size = ivec2(params.raster_size);

	if (uv.x >= size.x || uv.y >= size.y) {
		return;
	}

	// vec4 color = imageLoad(color_image, uv);

	#COMPUTE_CODE

	// imageStore(color_image, uv, color);
}"

@export_multiline var shader_code : String = "":
	set(value):
		mutex.lock()
		shader_code = value
		shader_is_dirty = true
		mutex.unlock()

var rd : RenderingDevice
var shader : RID
var pipeline : RID

var mutex : Mutex = Mutex.new()
var shader_is_dirty : bool = true

# Called when this resource is constructed.
func _init():
	effect_callback_type = EFFECT_CALLBACK_TYPE_PRE_TRANSPARENT
	rd = RenderingServer.get_rendering_device()
	
# System notifications, we want to react on the notification that
# alerts us we are about to be destroyed.
func _notification(what):
	if what == NOTIFICATION_PREDELETE:
		if shader.is_valid():
			# Freeing our shader will also free any dependents such as the pipeline!
			rd.free_rid(shader)
			
# Check if our shader has changed and needs to be recompiled.
func _check_shader() -> bool:
	if not rd:
		return false

	var new_shader_code : String = ""

	# Check if our shader is dirty.
	mutex.lock()
	if shader_is_dirty:
		new_shader_code = shader_code
		shader_is_dirty = false
	mutex.unlock()

	# We don't have a (new) shader?
	if new_shader_code.is_empty():
		return pipeline.is_valid()

	# Apply template.
	new_shader_code = template_shader.replace("#COMPUTE_CODE", new_shader_code);

	# Out with the old.
	if shader.is_valid():
		rd.free_rid(shader)
		shader = RID()
		pipeline = RID()

	# In with the new.
	var shader_source : RDShaderSource = RDShaderSource.new()
	shader_source.language = RenderingDevice.SHADER_LANGUAGE_GLSL
	shader_source.source_compute = new_shader_code
	var shader_spirv : RDShaderSPIRV = rd.shader_compile_spirv_from_source(shader_source)

	if shader_spirv.compile_error_compute != "":
		push_error(shader_spirv.compile_error_compute)
		push_error("In: " + new_shader_code)
		return false

	shader = rd.shader_create_from_spirv(shader_spirv)
	if not shader.is_valid():
		return false

	pipeline = rd.compute_pipeline_create(shader)
	return pipeline.is_valid()
	
# Called by the rendering thread every frame.
func _render_callback(p_effect_callback_type, p_render_data):
	if rd and p_effect_callback_type == EFFECT_CALLBACK_TYPE_PRE_TRANSPARENT and _check_shader():
		# Get our render scene buffers object, this gives us access to our render buffers.
		# Note that implementation differs per renderer hence the need for the cast.
		var render_scene_buffers : RenderSceneBuffersRD = p_render_data.get_render_scene_buffers()
		var render_scene_data : RenderSceneDataRD = p_render_data.get_render_scene_data()
		
		if render_scene_buffers:
			# Get our render size, this is the 3D render resolution!
			var size = render_scene_buffers.get_internal_size()
			if size.x == 0 and size.y == 0:
				return

			# We can use a compute shader here
			var x_groups = (size.x - 1) / 8 + 1
			var y_groups = (size.y - 1) / 8 + 1
			var z_groups = 1

			# Push constant
			var push_constant : PackedFloat32Array = PackedFloat32Array()
			push_constant.push_back(size.x)
			push_constant.push_back(size.y)
			push_constant.push_back(0.0)
			push_constant.push_back(0.0)

			# Loop through views just in case we're doing stereo rendering. No extra cost if this is mono.
			var view_count = render_scene_buffers.get_view_count()
			for view in range(view_count):
				# Get the RID for our color image, we will be reading from and writing to it.
				var color_image = render_scene_buffers.get_color_layer(view)

				var color_uniform : RDUniform = RDUniform.new()
				color_uniform.uniform_type = RenderingDevice.UNIFORM_TYPE_IMAGE
				color_uniform.binding = 0
				color_uniform.add_id(color_image)
				
				var depth_image = render_scene_buffers.get_depth_layer(view)
				# var fmt = rd.texture_get_format(depth_image)
				# fmt.usage_bits = (
				#	RenderingDevice.TEXTURE_USAGE_CAN_UPDATE_BIT |
				#	RenderingDevice.TEXTURE_USAGE_STORAGE_BIT |
				#	RenderingDevice.TEXTURE_USAGE_CAN_COPY_FROM_BIT |
				#	RenderingDevice.TEXTURE_USAGE_CPU_READ_BIT
				# )
				# var depth_image_copy = rd.texture_create(fmt,RDTextureView.new(), rd.texture_get_data(depth_image, view));
				
				var depth_uniform : RDUniform = RDUniform.new()
				depth_uniform.uniform_type = RenderingDevice.UNIFORM_TYPE_IMAGE
				depth_uniform.binding = 1
				depth_uniform.add_id(depth_image)
				
				# Create a uniform set, this will be cached, the cache will be cleared if our viewports configuration is changed.
				var textures_uniform_set = UniformSetCacheRD.get_cache(shader, 0, [ color_uniform, depth_uniform ])
								
				# Run our compute shader.
				var compute_list := rd.compute_list_begin()
				rd.compute_list_bind_compute_pipeline(compute_list, pipeline)
				rd.compute_list_bind_uniform_set(compute_list, textures_uniform_set, 0)
				rd.compute_list_set_push_constant(compute_list, push_constant.to_byte_array(), push_constant.size() * 4)
				rd.compute_list_dispatch(compute_list, x_groups, y_groups, z_groups)
				rd.compute_list_end()
```

### Minimal reproduction project (MRP)

[compositor-depth-shader.zip](https://github.com/user-attachments/files/17845894/compositor-depth-shader.zip)

**Comment by clayjohn** [comment] 2024-11-22 03:26
Duplicate of https://github.com/godotengine/godot/issues/96737

Thank you for the report. I am closing this as a duplicate of https://github.com/godotengine/godot/issues/96737 so that we can track the issue in one place. Please provide further info as a response to https://github.com/godotengine/godot/issues/96737

**Closed by clayjohn** 2024-11-22 03:26 UTC

**Comment by juspky** [comment] 2024-11-22 12:30
@clayjohn are you sure this is a duplicate?  I know the problem is similar but https://github.com/godotengine/godot/issues/96737 is about the bit not being set on the mobile renderer, even for the color layer. since mobile doesn't support the storage bit on all hardware.

This is about the forward+ renderer which should support TEXTURE_USAGE_STORAGE_BIT, the bit not being set on the depth texture could be a different problem.

**Comment by juspky** [comment] 2024-11-22 16:51
@clayjohn are you sure this is a duplicate of #96737?

I might draw wrong conclusions since I don't know cpp very well and have no clue about the godot codebase.

_render_buffers_can_be_storage is false on mobile. Which causes the issue in #96737 
```cpp
bool RenderForwardMobile::_render_buffers_can_be_storage() {
	// Using 32bit buffers enables AFBC on mobile devices which should have a definite performance improvement (MALI G710 and newer support this on 64bit RTs)
	// Doesn't support storage
	return false;
}
```
But it is true for F+, so i don't believe these two issues are related
```cpp
bool RendererSceneRenderRD::_render_buffers_can_be_storage() {
	return true;
}
```

I suspect the last else block of  `get_depth_usage_bits` to be the cause, since it never sets the storage bit if p_resolve is false.
```cpp
uint32_t RenderSceneBuffersRD::get_depth_usage_bits(bool p_resolve, bool p_msaa, bool p_storage) {
	DEV_ASSERT((!p_resolve && !p_msaa) || (p_resolve != p_msaa));

	uint32_t usage_bits = RD::TEXTURE_USAGE_SAMPLING_BIT;
	if (p_msaa) {
		usage_bits |= RD::TEXTURE_USAGE_DEPTH_STENCIL_ATTACHMENT_BIT | RD::TEXTURE_USAGE_CAN_COPY_FROM_BIT;
	} else if (p_resolve) {
		usage_bits |= RD::TEXTURE_USAGE_CAN_COPY_TO_BIT | (p_storage ? RD::TEXTURE_USAGE_STORAGE_BIT : 0);
	} else {
		usage_bits |= RD::TEXTURE_USAGE_DEPTH_STENCIL_ATTACHMENT_BIT
	}

	return usage_bits;
}
```

get_color_usage_bits does set the storage bit in that branch.

```cpp
uint32_t RenderSceneBuffersRD::get_color_usage_bits(bool p_resolve, bool p_msaa, bool p_storage) {
	DEV_ASSERT((!p_resolve && !p_msaa) || (p_resolve != p_msaa));

	uint32_t usage_bits = RD::TEXTURE_USAGE_SAMPLING_BIT | RD::TEXTURE_USAGE_COLOR_ATTACHMENT_BIT | RD::TEXTURE_USAGE_INPUT_ATTACHMENT_BIT;
	if (p_msaa) {
		usage_bits |= RD::TEXTURE_USAGE_CAN_COPY_FROM_BIT;
	} else if (p_resolve) {
		usage_bits |= RD::TEXTURE_USAGE_CAN_COPY_TO_BIT | (p_storage ? RD::TEXTURE_USAGE_STORAGE_BIT : 0);
	} else {
		usage_bits |= (p_storage ? RD::TEXTURE_USAGE_STORAGE_BIT : 0);
	}

	return usage_bits;
}
```

Unfortunatly if I change the last branch of get_depth_usage_bits to 
```cpp
	} else {
		usage_bits |= RD::TEXTURE_USAGE_DEPTH_STENCIL_ATTACHMENT_BIT | (p_storage ? RD::TEXTURE_USAGE_STORAGE_BIT : 0);
	}
```
I get `Clear color values supplied (3) differ from the amount required for framebuffer color attachments (4)`

I don't know enough about rendering to further investigate at this point.

**Comment by clayjohn** [comment] 2024-11-22 18:29
The underlying cause and solution are the same. Right now Godot only uses the `TEXTURE_USAGE_STORAGE_BIT` when we need it internally. Whether it is needed is a factor of several things (one of them being whether the Mobile or Forward+ backend is used). Regardless of _why_ the texture was created without the bit, we need to make it so that you can request the bit if you need it.

**Comment by juspky** [comment] 2024-11-22 18:53
Oh alright, I understand
