### ISSUE TITLE
Document property_list_changed_notify

### ISSUE THREAD

**Issue by xDGameStudios** [godotengine/godot#23854] opened 2018-11-20 15:28 UTC
**Godot version:**
v3.1.alpha.calinou.d304228

**OS/device including version:**
Windows 10

**Issue description:**
There should be a way to force the redraw/refresh of the inspector when a property is changed (value is set). For example imagine working in a EditorInspectorPlugin that whenever an exported boolean is changed in a node the plugin should hide another exported property from the inspector! Right now the node must be unselected and reselected for the inspector to redraw!

I'm not saying it should be refreshed everytime as it could be bad for performance but there should be an option for plugin developers to force it! ;)

for example:
`_redraw_inspector();`

**Steps to reproduce:**

node with this code:
```
tool
extends Node
class_name TestNode

export(bool) var use_curve : bool = true;

export(Curve) var growth_curve : Curve
export(int) var fixed_value : int
```

plugin for inspector with this code:
```
extends EditorInspectorPlugin

func can_handle(object):
	if object is TestNode:
		return true;

func parse_property(object, type, path, hint, hint_text, usage):
	match path:
		'growth_curve':
			return !object.use_curve
		'fixed_value':
			return object.use_curve
```

**Comment by bojidar-bg** [comment] 2018-11-20 16:22
Does `property_list_changed_notify` work for you?

**Comment by xDGameStudios** [comment] 2018-11-20 17:39
It does work! I didn't know property_list_changed_notify() could do this! The documentation is not accurate about that!

**Comment by Calinou** [comment] 2020-04-17 20:22
Duplicate of #21009, which was resolved today.

**Closed by Calinou** 2020-04-17 20:22 UTC
Labels: documentation
