### ISSUE TITLE
Pixel Snap (-Grid) is off by a fraction of a pixel

### ISSUE THREAD

**Issue by whiteshampoo** [godotengine/godot#70813] opened 2023-01-01 20:57 UTC
### Godot version

Godot 4.0 Beta 10

### System information

Windows 10

### Issue description

The Pixel-Snap-Grid seems to be off by a small fraction of a pixel.

### Steps to reproduce

1. Create a Node2D
2. Create another Node2D as child
3. Use Grid Snap (Shift + G)
4. Configure Grid Snap to Grid Step 1x1 Pixel (easiest visible result, is broken on other settings, too!)
5. Drag Child-Node2D to (e.g.) x-coordinate 49
6. Zoom in, and you will see, that the node is exactly between grid-lines and that the grid-lines are not at integer values, but have an increasing decimal place
7. Try to move Child-Node2D to x-coordinate 50. It will jump to 51, which is also between grid-lines

### Minimal reproduction project

The root-/parentnode has no scaling or offset.

![grafik](https://user-images.githubusercontent.com/2029198/210184234-67e510e9-db10-4496-9946-22587cd8db01.png)
![gridsnap](https://user-images.githubusercontent.com/2029198/210184309-7b82c48b-c35c-412d-8fb1-6950dbe9caed.gif)

**Comment by kleonc** [comment] 2023-01-01 21:03
Duplicate of #70186.

**Closed by kleonc** 2023-01-01 21:03 UTC
