### ISSUE TITLE
ResourceSaver FLAG_CHANGE_PATH flag probably not behaving according to documentation or documentation is ambiguous

### ISSUE THREAD

**Issue by albinaask** [godotengine/godot#67367] opened 2022-10-13 21:15 UTC
### Godot version

3.5 stable

### System information

Windows 11

### Issue description

The documentation states that using the flag aforementioned, the saved resource changes it's path, but this is ambiguous since this could either refer to the resource object that has been saved or the resource file on disk. The behavior currently seems to be not changing the object's member "resource_path" according to the code supplied below. 

Again, I'm not sure this is a bug or just an unclear piece of documentation, but since there is no mention of resource_path in the .tres file, I just assumed this was a bug. But if it isn't feel free to close this issue and I'll open one for the docs instead.

### Steps to reproduce

1. open project
2. create scene
3. attach script
4. paste 
       `var res = load("default_env.tres")
	print("res path: " + res.resource_path)
	var err = ResourceSaver.save("res://env2.tres", res, ResourceSaver.FLAG_CHANGE_PATH)
	print("res path: " + res.resource_path)
	print("OK == true" + str(err == OK))`
5. Observe bug in console

**Comment by KoBeWi** [comment] 2022-10-14 15:33
Duplicate of #42697

**Closed by KoBeWi** 2022-10-14 15:33 UTC
Labels: bug, topic:core, documentation
