### ISSUE TITLE
LightmapGI: Some meshes become completely unlit or black when baking lightmaps

### ISSUE THREAD

**Issue by BlockyDK** [godotengine/godot#73124] opened 2023-02-11 20:32 UTC
### Godot version

Godot 4 RC1

### System information

Windows 10, GeForce 3070

### Issue description

When baking lightmaps, some meshes will occasionally show as completely unlit. Sometimes they will bake properly, and sometimes they will not, but I have not been able to find any sort of pattern to it. None of the LightmapGI settings I have tried, nor settings on the meshes themselves, have had any effect. All of the meshes in this scene were imported with Light Baking set to Static Lightmaps and they have their Global Illumination mode set to Static. They are all instances and share the exact settings, but some of them become completely black after baking. On occasion, they will bake correctly even if I have not changed any settings.

![Godot_RC1_LightmapRandomlyUnlitMeshes_01](https://user-images.githubusercontent.com/42628327/218279741-1067b6fb-8c00-4504-8ea1-7f45589422d7.jpg)

### Steps to reproduce

1. Create a scene where all the static meshes are imported with Light Baking set to Static Lightmaps and their Global Illumination mode is set to Static.
1. Place a directional light in that scene with shadows enabled and the Bake Mode set to Static.
1. Add a LightmapGI and Bake the Lightmaps for the scene.

### Minimal reproduction project

[RC1_LightmapGI_UnlitMeshes.zip](https://github.com/godotengine/godot/files/10714656/RC1_LightmapGI_UnlitMeshes.zip)

**Comment by mikatomik** [comment] 2023-03-16 16:14
I am still getting this in 4.0 stable. I have found something interesting, though. If I open up the inherited scene and go to one of the black meshes and manually re-UV unwrap layer two, it will bake the next time I try to bake. However, a different instance of the mesh that was displaying before will then go black at random. I'm definitely too dumb to understand what's going on but thought maybe that could be a clue for the smart brains.

**Comment by clayjohn** [comment] 2023-03-16 17:01
Now that you mention it, I have seen a similar issue that was caused by not having UV2s for the meshes. Typically reimporting with GI mode set to static + lightmaps has been enough. With the MRP, I reimported the mesh and tried baking again and the pillars were properly included in the bake.

**Comment by BlockyDK** [comment] 2023-03-16 17:29
Just to add to clayjohns comment, back when I encountered this in RC1, reimporting would sometimes fix it, and sometimes wouldn't. And even if it did fix it, they would sometimes break in a later bake. At all times I could view the uv2 on the mesh, even when it was not baking correctly. What makes it strange is that the way the scene was set up, all the meshes are instances of the same source, so it is strange that some would bake and others would not.

**Comment by mikatomik** [comment] 2023-03-17 06:00
>What makes it strange is that the way the scene was set up, all the meshes are instances of the same source, so it is strange that some would bake and others would not.

Yep same here. All of the wall meshes are identical, duplicated in blender and brought in through the blendfile.

![image](https://user-images.githubusercontent.com/109499937/225824769-07eab0b6-0fb9-4841-ac3e-1eda640f41a4.png)

**Comment by mikatomik** [comment] 2023-03-19 01:05
Apologies for blowing up this thread, and also for the picture of the screen. I don't have an internet connection at the moment. But something else that may be of interest. As I add more and more geometry to the scene, LightmapGI seems to start doing strange things. Here, you can see what looks like the UV outline of the plane... on the ground mesh? 

![image](https://user-images.githubusercontent.com/109499937/226148120-4ca3f0e8-6124-40b2-bc08-06a6bf47afd0.jpeg)

This appears after I bake the light map, and toggles when I toggle visibility of the light map. And I think the artifacts in my above post might be just this, coordinates being projected onto incorrect objects which might be what's causing unlit meshes.

**Comment by Calinou** [comment] 2023-03-19 02:49
The debug gizmos should have shadow casting disabled to prevent this, but the property is ignored by the GPU lightmapper: https://github.com/godotengine/godot/issues/56870

**Comment by lw64** [comment] 2023-03-22 21:48
I am not sure if it is related, but I have the same issue, some objects don't receive light, sometimes even only from certain lights, but not all. The environment lights the objects a bit up though. Also some objects are getting light, but there are really strange artifacts, like some parts of the mesh are glowing, as if there would be emission. And when enabling to bake also direct lighting, the artifacts like grey lines appear. After using a different lightmap scale than 1 it disappeared though. Another thing I discovered was that when baking the light, after it has finished, for a very short moment the correct lighting is visible, but then it disappears again and the wrong lighting remains.

I hope these information are useful for debugging. Maybe some of it is not related though.

Also this is blocking my project currently. Is there a workaround available?

**Comment by Calinou** [comment] 2023-03-23 01:46
> Another thing I discovered was that when baking the light, after it has finished, for a very short moment the correct lighting is visible, but then it disappears again and the wrong lighting remains.

This is most likely https://github.com/godotengine/godot/issues/71585.

> Also this is blocking my project currently. Is there a workaround available?

Not that I know of.

**Comment by mikatomik** [comment] 2023-03-23 11:29
> Also this is blocking my project currently. Is there a workaround available?

My issues happened while using Forward+. Inexplicably, it fixed itself after several reimports of the scene, deleting the unwrap cache, and tweaking the"Lightmap Texel Size" at the import dock. 

I do not know if those things directly fixed it, are even related, or if simply reimporting 100 times somehow fixed it, but that's how I got mine to bake properly. It kind of seems like chance.

I'm not a brain to pick for these things, and I have no idea how light baking works, but it really feels like a UV issue as sometimes I can see the outline of an objects UV layout on a completely separate object, like in my image above where you can see the plane's UV on the floor.

Also, if you are getting the black artifacts with reflection probes like shown above, that went away when I unchecked "directional" in the LightmapGI bake settings.

**Comment by Calinou** [comment] 2023-03-27 17:14
> @Calinou I tried to find some resources online on how to do this, but I wasn't really successful. Can you recommend some keywords or even articles explaining how to do this? I think I need to make Blender output a UV2 map and somehow tell Godot to use the UV2 map... is that correct? smile

It's been a long time since I've seen someone attempt using external lightmaps in Godot – last time I've seen it was in Godot 3.1, back when Godot used a different lightmapper with a different API. So I wouldn't know how to do it now.

**Comment by marius-se** [comment] 2023-03-27 19:55
I see, do I still need to add a LightmapGI to my scene?

**Comment by marius-se** [comment] 2023-03-27 21:41
I'll give that a try, many thanks!

**Comment by Racktash** [comment] 2023-06-28 18:20
Spent another few hours trying to dig deeper and at least figure out what separates "working" and "not working" instances.

I found I was able to make one of my meshes work by moving it in the node tree (like, just changing the order – the parent remained the same) and rebaking. I could then move it back to its original position, bake again, and it'd be broken again (see screenshots).

I think this suggests that node order may have something to do with this while it is broken.

![position1-bad](https://github.com/godotengine/godot/assets/2924680/23cae205-72f7-44ee-9e09-7c8ef49be6fd)
![position2-good](https://github.com/godotengine/godot/assets/2924680/f07b64f8-6aee-4f3f-be4c-8788443c6d24)

I thought at first the meshes were not being found or were being filtered out by _find_meshes_and_lights – but so far as I've been able to see, the meshes that are not getting baked properly are detected and added to the found_meshes vector.

As ever, hopefully some of this data lights a bulb above somebody's head. For me, I remain baffled. :)

**Comment by Calinou** [comment] 2023-09-18 22:04
I can confirm this on 4.2.dev 221884e6b (Linux, NVIDIA 535.104.05):

![Screenshot_20230918_235627](https://github.com/godotengine/godot/assets/180032/c9e84d3c-b967-4ed1-b2f2-53a5535bd21c)

**Testing project:** [test_dm6.zip](https://github.com/godotengine/godot/files/12653838/test_dm6.zip)

**Comment by jeffhube** [comment] 2023-09-19 02:42
I can also confirm on 4.2 dev 4 on (Windows 11, AMD).

I have two scenes with different arrangements of hundreds of identical 1x1 PlaneMesh. Both scenes will only successfully bake lighting for the first 784 meshes in the scene. All the others are black except for any real-time lighting. If I decrease the lightmap size hint from the default of 7x7, then it will successfully bake lighting for more meshes.

![image](https://github.com/godotengine/godot/assets/1283264/886afa36-ba8f-42c7-9cf6-6f6dfe0a09a0)

**Comment by jeffhube** [comment] 2023-09-19 04:42
I noticed that in my case, the lightmapper packs 7*7=49 meshes into each slice. One scene has 864 meshes, resulting in 18 slices. However, 16 slices * 7 * 7 = 784, which is exactly the number of meshes that are rendering correctly as I mentioned above.

Are we hitting some sort of limit at 16 lightmap slices?

**Comment by Racktash** [comment] 2023-09-19 07:40
> I noticed that in my case, the lightmapper packs 7*7=49 meshes into each slice. One scene has 864 meshes, resulting in 18 slices. However, 16 slices * 7 * 7 = 784, which is exactly the number of meshes that are rendering correctly as I mentioned above.
> 
> Are we hitting some sort of limit at 16 lightmap slices?

I didn't find the actual cause in my investigation, but I did recompile the lightmapper code with the debug definition in place. This spits out the generated bitmaps of the various stages of lightmap generation. I then printed the coordinates of each of my objects and matched the coordinates on the bitmaps and found the objects coming out black post bake were not black on the bitmaps. I also found I was able to fix the problem by clearing out my .Godot file (not sure which bit of it was relevant). 

So I never proved anything, but I was coming under the impression it was some filesystem / caching issue which would explain why when I imported the example project and baked I had zero problems – it's not a limits issue, it's a local project issue.

**Comment by jeffhube** [comment] 2023-09-19 17:00
I did some more investigation and the issue seems to be that when there are more than 16 lightmap slices, it messes up some exposure normalization calculation in the shader which causes the meshes to be black.

Inside scene_forward_clustered.glsl, there is a line which samples the lightmap texture and then multiples it by the exposure normalization.

```
ambient_light += textureLod(sampler2DArray(lightmap_textures[ofs], SAMPLER_LINEAR_CLAMP), uvw, 0.0).rgb * lightmaps.data[idx].exposure_normalization;
```

If you remove the last part, `* lightmaps.data[idx].exposure_normalization`, then the meshes are no longer black.

--- 

In my scene, the `lightmaps.data` array contains only one populated element, which has an exposure_normalization of 1. All others have a value of 0.
![image](https://github.com/godotengine/godot/assets/1283264/b49c2565-55e3-43ad-a482-e486cf738dc4)

So whenever `idx` is not 0, `* lightmaps.data[idx].exposure_normalization` effectively multiplies the lightmap by 0, turning it black.

`idx` is calculated as
```
uint idx = instances.data[instance_index].gi_offset >> 20;
```

`gi_offset` partially comes from here: (render_forward_clustered.cpp)
```
inst->gi_offset_cache = inst->lightmap_slice_index << 16;
inst->gi_offset_cache |= lightmap_cull_index;
```

So if I have a mesh that uses slice # 17 of the lightmap (index 16), then `gi_offset` is `16 << 16 = 1048576`, and `idx` is `1048576 >> 20 = 1`. Since `idx` is 1, `exposure_normalization` is 0, and so the mesh is black.

So at least in my scene, any mesh using the first 16 lightmap slices renders fine, and any others will appear black because the lightmap is multiplied by a 0 `exposure_normalization`.

---

As far as fixing this goes, I'm not clear on whether `lightmaps.data` is missing additional elements, whether the packing of data into `gi_offset` needs to be adjusted so that more than 16 lightmap slices doesn't change the index into `lightmaps.data`, or whether the lightmapper needs to be capped at 16 slices.

**Comment by bitsawer** [comment] 2023-09-19 17:25
I wonder if the exposure normalization from CameraAttributes is not always updated correctly, see https://github.com/godotengine/godot/issues/74139. I think the exposure normalization was added in https://github.com/godotengine/godot/pull/63751

I fixed a somewhat similar bug in VoxelGI: https://github.com/godotengine/godot/pull/81067, but there the effect was less noticeable (exposure was just reset to normal level).

**Closed** 2023-09-20 16:56 UTC
Labels: bug, topic:rendering, confirmed, topic:3d

**Comment by marius-se** [comment] 2023-09-21 02:45
Nice, thank you! 🙏🏼

**Comment by TerryCavanagh** [comment] 2025-04-23 23:03
Hi! Sorry for posting something unrelated on a closed issue, but I just spent a very long time trying to figure out why one of my meshes was completely black when I applied LightmapGI, and this issue comes up first on google. It worked fine with VoxelGI and was driving me crazy, I tried dozens of bakes with dozens of experimental adjustments and could not figure it out.

It turns out the faces on the mesh were just pointing the wrong way. 🤦

**Comment by Calinou** [comment] 2025-04-24 15:31
> It turns out the faces on the mesh were just pointing the wrong way. 🤦

I believe you can debug this more easily when using Forward+ by changing the debug draw mode to **Display Advanced > Normal Buffer** in the Perspective menu. It's not supported in Mobile and Compatibility though.
