### ISSUE TITLE
Invalid buttons for Sprite and Skeleton2D in empty project

### ISSUE THREAD

**Issue by Chaosus** [godotengine/godot#17600] opened 2018-03-18 06:16 UTC
**Godot version:**
760b056

**OS/device including version:**
Linux Mint 18.3

**Issue description:**
Buttons for Sprite and Skeleton2D is visible from beginning in empty project. If you press it and choose any option the engine will crash.

![image](https://user-images.githubusercontent.com/3036176/37563205-b0da4430-2a8c-11e8-9623-77caf6d0bab9.png)

**Steps to reproduce:**
1. Create new project
2. Switch to 2D mode
3. Observe these buttons

Im not sure if this is related - #16891

**Comment by groud** [comment] 2018-03-18 17:43
> Im not sure if this is related - #16891

Yes, this is a duplicate of #16891

**Closed by groud** 2018-03-18 17:43 UTC
Labels: bug, topic:editor
