### ISSUE TITLE
Mouse coordinates not matching cursor position.

### ISSUE THREAD

**Issue by avencherus** [godotengine/godot#17563] opened 2018-03-16 15:17 UTC
This one is very minor and so far is only appearing on my **laptop for version 2.1.4 using Windows 10**.

In the event where when _set_window_size()_ is used near the launch of the program, and it is in a window (with borders), and the size pushes these borders even slightly beyond the screen size (or edge) of the monitor, the mouse coordinates will be offset in the Y axis by some amount.

It resolves when the window size is dragged.

![mouse_coords](https://user-images.githubusercontent.com/13004169/37528364-25a90ff4-293d-11e8-843d-adba4e0eb835.gif)

The video card on my laptop is a GeForce 940MX/PCIe/SSE2.

No idea where the problem stems from, took me a long time to narrow down the cause, was expecting it to be a bug somewhere in my mouse code.

**Comment by Noshyaar** [comment] 2018-03-16 15:58
A minimal project is greatly appreciated.

**Comment by avencherus** [comment] 2018-03-16 16:26
@Noshyaar Sure thing, let me know if you can recreate it.  So far it only happens on my laptop.  I can't get the same problem with this project on my other computers.

[Mouse Test.zip](https://github.com/godotengine/godot/files/1819979/Mouse.Test.zip)


One thing maybe worth nothing is that the laptop is set to 1920x1080, but it's screen size is 1536x864.

Though that Y difference is 216, by drawing a line on the canvas, it looks like the offset I'm experiencing is more around 140 pixels on the Godot canvas.

**Comment by Noshyaar** [comment] 2018-03-16 16:45
I can't reproduce on Antergos x86_64 using Mesa driver with 1600x900 screen. I don't see anything wrong with your code however.

**Comment by avencherus** [comment] 2018-03-16 16:55
@Noshyaar Thanks for taking a look.  I teased it out with that project, since I couldn't find anything obviously off with my game's mouse position calls.  But yeah, it is a weird one, so I wonder what the conditions are, very specific drivers/hardware?  Didn't get the problem in 3.0.2 though, so maybe it will reappear in 3.1 if its related to OpenGL 2.0.

**Comment by eon-s** [comment] 2018-03-16 22:47
I could reproduce this on Windows 10 with 2.1.3, the screen size is 1920x1080. 

In the example, setting the screen size to (1920x1080)*0.8 or lower does not show the issue.
If I set the window smaller on project settings, the issue cannot be reproduced.

And... looking a bit more, if I do (1920*0.8x1080) cannot reproduce, looks like is the width settings the ones affecting the mouse Y (???).

**Comment by avencherus** [comment] 2018-03-16 22:59
@eons Interesting, so maybe something is lurking there.  They Y coordinate bit you tested might be a clue, I was thinking it may be when the title bar lands somewhere off the top of the screen.  Had a very similar experience with those values when I first was isolating it.  

For me it starts at around 90%, because I believe that is where the edge of the window starts creeping off screen for my laptop.  

Once I take it closer to 80% it will be fine again, because the window fits on screen.  I imagine the percentages might vary based on the resolutions involved.

**Comment by akien-mga** [comment] 2018-03-17 07:54
Does it affect 3.0/the master branch too, or only 2.1?

**Comment by aaronfranke** [comment] 2018-06-08 17:50
Have you tested other versions of 2.1?

**Comment by akien-mga** [comment] 2018-09-18 11:40
Thanks, closing as fixed in 3.0+ then. It's unlikely at this stage that much work will be done on 2.1-specific issues, unless game breaking and needed for some games in production.

**Closed by akien-mga** 2018-09-18 11:40 UTC
Labels: bug, platform:windows, topic:input

**Comment by cmcarey** [comment] 2018-10-01 09:03
I see this issue in 3.0.6.
This shows my mouse cursor hovering over the menu icon and it not highlighting (clicking also doesn't work):
![image](https://user-images.githubusercontent.com/32423458/46279521-336bc300-c561-11e8-8b2e-290d55af2677.png)

And my mouse cursor below the menu icon and it highlighting (clicking opens the menu):
![image](https://user-images.githubusercontent.com/32423458/46279538-3f578500-c561-11e8-9383-719eb04e78e3.png)

**Comment by Zireael07** [comment] 2018-10-01 09:27
What is your gfx card? This looks suspiciously like a bug with Intel drivers that was reported previously.

**Comment by vnen** [comment] 2018-10-01 17:18
Indeed, @cmcarey's issue looks like #8902.

**Comment by avencherus** [comment] 2018-10-01 20:13
@cmcarey My issue didn't happen within the editor at least.  It was a run-time thing that occurred when the window frame started off screen.  It corrected itself if the window was able to be adjusted, so it was being caused by something in the display code immediately during startup.  Hard to say if it would be related.

**Comment by Frooztyes** [comment] 2020-07-15 22:43
Hi, this issue is closed, but i am having this problem in Godot 3.2.2.stable. It like the screenshot at the start of the thread.

**Comment by Frooztyes** [comment] 2020-07-15 22:48
Hi, i am having the same issue on Windows 10 Godot 3.2.2.stable. But it's not resolving when i drag the window. Any idea ?

**Comment by avencherus** [comment] 2020-07-18 02:38
> Hi, i am having the same issue on Windows 10 Godot 3.2.2.stable. But it's not resolving when i drag the window. Any idea ?

I recommend opening a new issue and include your hardware / driver information with a reproduction project in the template.  This thread is quite cold, and I only saw this because I had forgotten to unsubscribe.

With a new issue, someone might be able reproduce the issue and help you from there.

This specific issue is still resolved for me in 3.2.2, so the cause for you is likely something else.  It seems from other cursor position issues over the years, people were having problems with certain vendor drivers, and upgrading them fixed their problem.

You may start by printing out `OS.get_screen_size()`, and see if your screen size matches the resolution you expect.
