### ISSUE TITLE
Support touch screen actions on desktop platforms

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot#7612] opened 2017-01-22 19:01 UTC
On many laptops, touch screens are now available. However, it isn't possible to scroll by flicking the scrollable area up and down in the Godot editor (in the script editor or scene tree, for example), like you can do on a mobile device. You currently need to drag the scroll bar, which can be very hard to do.

This ability could also be helpful in exported projects.

Exemple application which supports touch events: [Visual Studio Code](http://code.visualstudio.com/)

**Comment by akien-mga** [comment] 2017-08-31 05:41
Closing as duplicate of the more active #8028.

**Closed by akien-mga** 2017-08-31 05:41 UTC
Labels: feature proposal, topic:core, usability
