### ISSUE TITLE
LightmapGI long baking

### ISSUE THREAD

**Issue by SkanerSoft** [godotengine/godot#72997] opened 2023-02-09 21:35 UTC
### Godot version

Godot 4 RC 1

### System information

Ubuntu 22.04 Cinnamon

### Issue description

During baking, the process reaches the stage of re-import and freezes for a few minutes.

You have to wait a very long time every time.

### Steps to reproduce

Create any 3D scene, place several meshes on it and try to bake shadows with LightmapGI. 

### Minimal reproduction project

Any 3D project

**Comment by Calinou** [comment] 2023-02-09 21:38
Duplicate of https://github.com/godotengine/godot/issues/72666.

**Closed by Calinou** 2023-02-09 21:38 UTC
