### ISSUE TITLE
Can't Connect GraphNodes when GraphEdit is zoomed out 

### ISSUE THREAD

**Issue by cchipont** [godotengine/godot#47646] opened 2021-04-05 13:07 UTC
**Godot version:**

Godot 3.3*

**OS/device including version:**

Mac OSX / 10.15.7 Catalina

**Issue description:**

When zoomed out (less than 1:1) I can't seem to be able to connect nodes. Allthough the mouse pointer is placed correctly over the slot, the drag action doesn't produce a connection, but instead moves the whole node.

**Steps to reproduce:**
In a GraphEdit component, place two nodes, zoom out with the minus button at the top left corner and then try to drag a connection between the said nodes.

**Comment by akien-mga** [comment] 2021-04-05 13:18
Duplicate of #46425. This will be fixed by #47173 in 3.4 / 3.3.1.

**Closed by akien-mga** 2021-04-05 13:18 UTC
