### ISSUE TITLE
Increasing "rendering/environment/volumetric_fog/volume_size" in project settings causes visual errors with the volumetric fog.

### ISSUE THREAD

**Issue by Kadmioo** [godotengine/godot#87290] opened 2024-01-17 11:33 UTC
### Tested versions

- Reproducile in 4.2.1.stable.mono, 4.2.0.stable.mono and 4.1.3.stable.mono

### System information

Godot v4.2.1.stable.mono - Windows 10.0.22621 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 2080 Super with Max-Q Design (NVIDIA; 31.0.15.3742) - Intel(R) Core(TM) i7-10875H CPU @ 2.30GHz (16 Threads)

### Issue description

When moving around, you might see things like this: 

https://github.com/godotengine/godot/assets/148717949/0bb94dc1-2308-4eef-94ff-f8d7e305aea1

### Steps to reproduce

1- Create a new project
2- Add a World Environment Node and set "volumetric_fog_enabled" to True
3- Go to "rendering/environment/volumetric_fog/volume_size" (make sure you have enabled "advanced settings") and increase the value beyond 64
4- Move the camera around and after a while you should start seeing these bugs

### Minimal reproduction project (MRP)

N/A

**Comment by Lippanon** [comment] 2024-01-17 13:30
Related to (possible duplicate of) https://github.com/godotengine/godot/issues/87136

**Comment by Calinou** [comment] 2024-01-17 14:40
@Kadmioo Remember that for GitHub video previews to work, you need to have a blank line before *and* after the video URL. I edited your post accordingly, but remember to do this in the future :slightly_smiling_face:

**Comment by Kadmioo** [comment] 2024-01-18 12:24
According to my testing, disabling the temporal reprojection seems to solve this issue. Most likely because the reprojection causes the artifacts to be spread around. This can be used as a temporary solution while the bug gets fixed.

**Comment by Kadmioo** [comment] 2024-01-18 12:26
According to my testing, disabling the temporal reprojection seems to solve this issue. Most likely because the reprojection causes the artifacts to be spread around. This can be used as a temporary solution while the bug gets fixed.

**Comment by solitaryurt** [comment] 2024-03-25 18:08
I've experienced this as well.

**Comment by Calinou** [comment] 2024-08-20 21:55
Thanks for the report! Consolidating in https://github.com/godotengine/godot/issues/87136.

**Closed by Calinou** 2024-08-20 21:55 UTC
Labels: bug, topic:rendering, confirmed, topic:3d
