### ISSUE TITLE
Operator "is" doesn't suppress unsafe property/method access warnings

### ISSUE THREAD

**Issue by vicguedez** [godotengine/godot#93510] opened 2024-06-23 15:38 UTC
### Tested versions

Godot v4.3.beta2

### System information

Pop!_OS 22.04 LTS - X11 - Vulkan (Forward+) - integrated AMD Radeon Vega 8 Graphics (RADV RAVEN) - AMD Ryzen 5 3500U with Radeon Vega Mobile Gfx (8 Threads)

### Issue description

Having unsafe property and method access warning levels to "Warn", the following always produces a warning:

```gdscript

var node: Node

func test() -> void:
	if node is Node2D:
		print(node.position) # (UNSAFE_PROPERTY_ACCESS):The property "position" is not present on the inferred type "Node" (but may be present on a subtype).
	elif node is Node3D:
		print(node.basis) # (UNSAFE_PROPERTY_ACCESS):The property "basis" is not present on the inferred type "Node" (but may be present on a subtype).
```

Should `is` not get rid of the warnings as the class has been validated?

### Steps to reproduce

Set warning level of `debug/gdscript/warnings/unsafe_property_access` and `debug/gdscript/warnings/unsafe_method_access` to `Warn` and use provided code in issue description.

### Minimal reproduction project (MRP)

-none-

**Comment by AThousandShips** [comment] 2024-06-23 16:02
Thank you for reporting, this is not a bug but a discussed feature, see:
* https://github.com/godotengine/godot-proposals/issues/8530

Closing and please see there for further details

**Closed by AThousandShips** 2024-06-23 16:02 UTC

**Comment by dalexeev** [comment] 2024-06-23 16:04
This is not a bug, but a missing feature. Currently, static analysis in GDScript does not take into account local assignments and type checking. See the following proposals instead:

* godotengine/godot-proposals#6941
* godotengine/godot-proposals#8530

Thanks for the contribution nonetheless!
