### ISSUE TITLE
Tooltips not shown while MPC-HC is playing back file

### ISSUE THREAD

**Issue by StarWolf3000** [godotengine/godot#41251] opened 2020-08-14 11:15 UTC
**Godot version:**
v3.2.2.stable.official

**OS/device including version:**
Windows 8.1 64-bit
NVIDIA GeForce GTX 960 2GB

**Issue description:**
I'd like to play some music in the background while working in Godot. My prefered player for this is Media Player Classic - Home Cinema. But I have encountered the issue, that the editor won't show any tooltips, as long as the player is playing back any file. I have tested it with other players like VLC and Foobar2000, and there is no issue with them.

**Steps to reproduce:**
- Open Media Player Classic - Home Cinema, and load and play any file.
- As long as the player is playing back something, no tooltips at all will appear in the editor.
- Pause/Stop or close the player, and tooltips work again.
- Sending the player to minified state while playing back exposes the same issue.

**Minimal reproduction project:**
This is not related to any project, it can be tested with ANY project, as long as the steps are done as mentioned.

**Comment by Calinou** [comment] 2020-08-14 12:17
See also https://github.com/godotengine/godot/issues/3835.

**Comment by Calinou** [comment] 2022-11-04 23:10
Duplicate of https://github.com/godotengine/godot/issues/32990.

Note that MPC-HC is end-of-life – I recommend switching to [mpv](https://mpv.io) (preferably) or a maintained fork of MPC-HC.

**Closed by Calinou** 2022-11-04 23:10 UTC
Labels: bug, platform:windows, needs testing, topic:gui
