### ISSUE TITLE
Crash when accessing NinePatchRect Control Anchor properties

### ISSUE THREAD

**Issue by p-r-i-s** [godotengine/godot#65359] opened 2022-09-05 11:30 UTC
### Godot version

Godot 4 alpha 13

### System information

Windows 10, GTX 980TI, Vulkan

### Issue description

I'm trying to make some "cinematic" black bars for my Ztargetting system (as I did successfully in godot 3.4)
Similar to the way a Zelda game might do this:
example: https://www.youtube.com/watch?v=_AbVAJ-ZErI&ab_channel=AndrewWilliams

I did this in 3.4 and they work perfectly and as intended. 

They wouldn't import correctly so I was going to remake them.

All the black bars are  is a NinePatchRect inside of a VBoxContainer.
I have two of these for the Upper and Lower Bar respectively.
The top VBoxContainer named "Upper" has Control Anchors of Left = 0, Top = 0, Right = 1 and Bottom = 0.25.
The NinePatchRect has a Minimum Size (formally the Control Margin property) of Right = 1920, Bottom = 270

The bottom VBoxContainer named "Lower" has Control Anchors of Left = 0, Top = 0.75, Right = 1 and Bottom = 1.
The NinePatchRect has a Minimum Size (formally the Control Margin property) of Right = 1920, Bottom = 270

When accessing the NinePatchRect Control Margin Property, Godot 4 alpha 13 will unexpectedly crash.

I attempted to implement this twice and it crashed both times at the same point which is why I decided to report it. 

### Steps to reproduce

Start Godot 4 Alpha 13
Make a Control Node
Make two VBoxContainers
Call one Upper and one Lower

Inside of each have a NinePatchRect
set some properties:
The top VBoxContainer named "Upper" has Control Anchors of Left = 0, Top = 0, Right = 1 and Bottom = 0.25.
The NinePatchRect has a Minimum Size (formally the Control Margin property) of Right = 1920, Bottom = 270

The bottom VBoxContainer named "Lower" has Control Anchors of Left = 0, Top = 0.75, Right = 1 and Bottom = 1.
The NinePatchRect has a Minimum Size (formally the Control Margin property) of Right = 1920, Bottom = 270

Godot will crash

**Comment by ItsNL** [comment] 2022-09-05 21:15
I'm not able to reproduce the bug. I tried it on Alpha 14 and on Master branch (commit `#90801a4`). I can change everything without any problem. I attach two scene following your steps (One is for Alpha 14 and the other for the master commit).

[Issue65359_NinePatchRectCrash.zip](https://github.com/godotengine/godot/files/9491997/Issue65359_NinePatchRectCrash.zip)

I'll try in alpha 13 to see if I can reproduce it.

**Comment by YuriSizov** [comment] 2023-01-18 15:52
Closing based on the above comment. If it's still reproduceable with the latest beta releases, please provide a repro project so we can replicate the bug.

**Closed by YuriSizov** 2023-01-18 15:52 UTC
Labels: bug, crash, regression, topic:gui
