### ISSUE TITLE
[gltf2] Importing an armature with no mesh attached does not work

### ISSUE THREAD

**Issue by jamie-pate** [godotengine/godot#56615] opened 2022-01-08 07:48 UTC
### Godot version

3.3.4.stable, 3.4.2.stable

### System information

Linux Nvidia GLES2/3

### Issue description

Importing an armature exported from blender as a GLTF file won't work unless you have a mesh bound to the armature.

See this reddit thread also: https://www.reddit.com/r/godot/comments/p0xxjp/importing_glb_gltf_20_from_blender/hb6ab42/?utm_source=reddit&utm_medium=web2x&context=3

### Steps to reproduce

Download an animation (e.g. .dae file from mixamo with no mesh)

Import to blender.
Export as GLTF

All you get is a bunch of spatials. (no errors in the output)

![image](https://user-images.githubusercontent.com/682658/148636480-ac0c7f40-a49f-476a-8e2f-78b1d0f5c8e7.png)
![image](https://user-images.githubusercontent.com/682658/148636402-cea2e261-7907-43f3-9d64-58cf3282bde1.png)

### Minimal reproduction project

[gltf-armature-no-mesh.zip](https://github.com/godotengine/godot/files/7832831/gltf-armature-no-mesh.zip)

**Comment by fire** [comment] 2022-01-08 17:59
@lyuma and I made a special case hack where store all the nodes in the mesh skin. not sure how general purpose the hack is.

**Comment by lyuma** [comment] 2022-01-09 02:41
@fire's hack is to create an unused "skins" object in the glTF document with all nodes as elements. It's not too hard to do even by hand, but we should make it so you don't need a hack to force nodes to be imported as skeletons.

Such a feature would be really useful for cases like importing an animation downloaded from Mixamo which has no mesh attached.

I'm thinking either a global checkbox to make the whole scene into a skeleton (except the root node); or else a per-node checkbox in the advanced import settings, next to Skip Import, of course inviting questions about what if you want specific leaf nodes to become Bone Attachments instead of bones.

I'd also say that there is a related problem here which Blender conceals. On Blender, if you have at least one Mesh in the skeleton, Blender will add all nodes in the skeleton into the skin object, effectively causing @fire's hack.

However, for users of Maya or other software, it only includes bones which are weight-painted into the skin, which can cause Godot to fail to select all nodes to add to the skeleton... having an import setting to override node/bone conversion may help users of other modeling programs.

Since the current behavior is technically "by design" due to lack of a bone forcing feature, should this be migrated to godot-proposals?

Or maybe we can start with a global checkbox to force the entire model into a single skeleton? That would solve the most common cases perhaps.

**Comment by jamie-pate** [comment] 2022-01-09 05:39
Fyi Mixamo .dae imports work fine even if you check 'no skin'.

If this is something that can't be fixed due to the gltf export not containing enough info I feel like it's a documentation issue then? I mostly wanted to have an issue logged in this tracker since that improves visibility of the issue and workarounds.

**Comment by lentsius-bark** [comment] 2022-01-19 00:47
Happened to me as well, I thought this was expected behaviour.

**Comment by fire** [comment] 2022-04-24 13:53
Fixed in 4.0 via https://github.com/godotengine/godot/pull/60177 but it'll still be a node animation.

Fixed in the gltf blender io exporter via exporting only selected objects https://github.com/KhronosGroup/glTF-Blender-IO/issues/822.

**Comment by fire** [comment] 2022-04-24 13:54
We probably still need to note that importing animations without a mesh become node animations.

**Closed by fire** 2022-04-24 13:53 UTC
Labels: bug, topic:import
