### ISSUE TITLE
Threaded call to add_child() fails and the game stalls (no warning in editor) if instance being added contains text with custom fonts

### ISSUE THREAD

**Issue by EllaKrael** [godotengine/godot#16860] opened 2018-02-20 15:34 UTC
**Godot version:**
3.0 stable (off of steam)

**OS/device including version:**
Windows 10 x64

**Issue description:**
When using threads calls to .add_child() fail (game stalls but does not flag issue in editor) to add an Instance of a scene if the scene instance being added contains text elements that uses custom dynamic fonts. 
Hiding the text elements lets it get added, then using .show() to reveal the text elements once added displays correct custom font.

```gdscript
export (PackedScene) var resource
var scene = null
var loader_thread = Thread.new()

func _ready():
	loader_thread.start(self, "load_scene") # this will fail at add_child() if text elements are visible
	load_scene(null) # this will work

func load_scene(vars):
	scene = resource.instance()
	$game.add_child(scene) # fails if text elements are visible and threaded
```

**Comment by Zylann** [comment] 2018-02-20 15:43
The scene tree is not thread-safe by design.

**Comment by EllaKreal** [comment] 2018-02-20 16:03
This worked in 2.1 so I can continue developing with that - but is it not strange that it fails only when the scene to be added contains text elements that are visible and using a custom font, but work if those elements are hidden or the font is left as default?

**Comment by Zylann** [comment] 2018-02-20 17:41
@EllaKreal you were probably "lucky" :) When things are not thread-safe, it's all down to timing.

**Comment by EllaKreal** [comment] 2018-02-21 09:35
Probably not a bug, maybe a usability issue?
As @Zylann says: scene tree is not thread safe and, with thanks to Juan and Rémi on twitter, I am now using call_deferred without issues.
```
func load_scene(vars):
	scene = resource.instance()
	call_deferred("add_scene")
	
func add_scene(path): # might use get_node() with path to add to specific node later
	$game.add_child(scene)
```
Is there a way the engine can fail gracefully when there are thread issues rather than just a game freeze and no reason in debug/output?

**Comment by Calinou** [comment] 2020-06-07 20:36
SceneTree is indeed not thread-safe as documented in [Thread-safe APIs](https://docs.godotengine.org/en/latest/tutorials/threads/thread_safe_apis.html), so I'll close this.

**Closed by Calinou** 2020-06-07 20:36 UTC
Labels: bug, topic:core
