### ISSUE TITLE
Subsurface scattering error

### ISSUE THREAD

**Issue by gamergamesz** [godotengine/godot#9530] opened 2017-07-06 15:09 UTC
MSAA disabled
using nvidia and intel (screenshot is of both)
win10  nvidia 960m

and those box like shadow appears when i hit the screen margin of viewport

subsurface scattering error and no ssr or ssao (disabled)
![screenshot 52](https://user-images.githubusercontent.com/13883739/27916683-786f00cc-6287-11e7-9f70-226a3f847993.png)
![screenshot 49](https://user-images.githubusercontent.com/13883739/27916684-787e52e8-6287-11e7-9176-f664a3de8e36.png)
![screenshot 50](https://user-images.githubusercontent.com/13883739/27916681-785f9a88-6287-11e7-8969-afc3c8828648.png)
![screenshot 51](https://user-images.githubusercontent.com/13883739/27916685-7883b030-6287-11e7-90dd-fb951f0dec93.png)

**Comment by vnen** [comment] 2017-07-06 15:44
I think this is the same problem I see in the material tester demo:

![godot windows opt tools 64_2017-07-06_12-31-11](https://user-images.githubusercontent.com/5599796/27919192-6b838e7c-6247-11e7-8b1a-c1606b024fd0.png)

What I find funny is that it changes depending on the window size. For example, the difference I get just by changing the height of the window by a single pixel:

![godot windows opt tools 64_2017-07-06_12-41-09](https://user-images.githubusercontent.com/5599796/27919697-be974a80-6248-11e7-9369-597b6c1a5638.png)
![godot windows opt tools 64_2017-07-06_12-41-17](https://user-images.githubusercontent.com/5599796/27919699-bffb2752-6248-11e7-9eb1-617fabfe62f5.png)

**Comment by eon-s** [comment] 2017-07-07 15:12
I have tried turning on "follow surface", the problem disappears until you resize the window, some specific window sizes seems to glitch the cheese.

**Comment by reduz** [comment] 2017-07-07 15:29
follow surface fixes it but it really sucks performance. I think it can
probably be fixed in a simpler way

**Comment by HummusSamurai** [comment] 2017-08-08 06:06
Is this still reproducible? If so it could perhaps be added to the main tracker.

**Comment by gamergamesz** [comment] 2017-08-08 07:19
yes, still same problem!

**Closed** 2017-08-22 00:38 UTC
Labels: bug, platform:windows, topic:rendering

**Comment by gamergamesz** [comment] 2017-08-23 06:34
still same problem as shown in above pics

**Comment by gamergamesz** [comment] 2017-08-25 05:15
follow surface is showing total white on editor. good at low setting, low value but as soon as i turn setting high and crank slider to 1 it shows cross lines, two subsurface when crosses(if one is put in front) show weirdness, still some weird rectangle shadow when touched to border of view pannel and same with camera too.

![screenshot 94](https://user-images.githubusercontent.com/13883739/29700394-c6e507e4-8981-11e7-8b85-46fff3ff3964.png)
![screenshot 95](https://user-images.githubusercontent.com/13883739/29700395-c725e26e-8981-11e7-9ad8-fdafb4f94c84.png)
![screenshot 91](https://user-images.githubusercontent.com/13883739/29700396-c75508fa-8981-11e7-858a-7c844661d1e9.png)
![screenshot 92](https://user-images.githubusercontent.com/13883739/29700397-c75a51ac-8981-11e7-84b2-296593b628b0.png)
![screenshot 93](https://user-images.githubusercontent.com/13883739/29700398-c7614a3e-8981-11e7-930d-9e4b01d11039.png)

**Comment by Cygon** [comment] 2018-02-17 12:59
**Godot version:** 3.0-stable, custom build from 9bd402698cfa299b79b9144f8d7744c308a4e085
**OS/device including version:** Gentoo Linux 4.9.72, KDE Plasma 5.10.5
**GPU model and drivers:** NVidia GTX 1080 w/proprietary drivers 387.22

I am still seeing the exact effects demonstrated in the original report as of Godot 3.0 stable:

![subsurface-ghosting-artifacts](https://user-images.githubusercontent.com/3613175/36341031-3e27ec72-13e8-11e8-8d9d-39fc0dc96e1f.gif)

If I enable `Follow Surface`, the ghosting becomes less visible (but they're still there), but it also removes any visible effect of the subsurface option:

![godot-subsurface-on-off-with-follow-surface](https://user-images.githubusercontent.com/3613175/36341175-6c517b5c-13ea-11e8-876e-b00a218f227a.gif)

(*The above is an animated gif toggling between maximum subsurface effect and no subsurface effect every 500 ms, looking closely you can see ghosting appear and disappear, but nothing changing about the surface*).

@reduz I believe this issue should be reopened, since rather than `Follow Surface` fixing the issue, there appears to be a separate issue with `Follow Surface` disabling subsurface scattering entirely.

**Comment by reduz** [comment] 2018-02-18 14:06
Your problem is that the effect strenght is too large, this effect is meant
to be used with less strenght.  Maybe we should restrict it in the
inspector to avoid people from breaking it and thinking it's a bug..
