### ISSUE TITLE
Mac Godot not working on monitor

### ISSUE THREAD

**Issue by jababo** [godotengine/godot#8192] opened 2017-03-29 03:25 UTC
Mac OS Sierra | Godot V2.1.2 stable

*Issue
Upon opening godot for the first time, after creating a project, I was greeted with the weirdest screen possible. Upon further inspection, I realized that my godot screen was scaled up by about 4 times, so I was just seeing one of the corners, making this software unusable. All help would be vastly appreciated.

To reproduce,
Open Godot on a Macintosh laptop connected to an ASUS HDMI monitor.
Create a new project, and open it.

Here is what my screen looks like afterwards... 
![screen shot 2017-03-28 at 9 21 29 pm](https://cloud.githubusercontent.com/assets/26757096/24437198/fa1220f2-13fc-11e7-88dc-410f321d6791.png)

**Comment by dannytatom** [comment] 2017-03-31 18:58
Are you opening it on your external monitor? I had the same issue, quick fix for me was to open it on the laptop screen (might require changing that screen to default while you do it) then move it to the external one.

**Comment by jababo** [comment] 2017-03-31 19:18
I am opening it on my external monitor. Sadly, your recommended method was unsuccessful.

**Comment by estevancarlos** [comment] 2017-04-01 07:11
I am having the same problem. Moving it from the laptop to the external monitor did not fix it. It seemed to be _confused_ about the resolution and size of application when it was moved over.

**Comment by jababo** [comment] 2017-04-01 14:57
Yeah. It is very annoying.

**Comment by akien-mga** [comment] 2017-04-03 07:37
Duplicate of #5688.

**Closed by akien-mga** 2017-04-03 07:37 UTC
Labels: bug, platform:osx, topic:editor
