### ISSUE TITLE
Are there errors in the NinePatchRect algorithm?

### ISSUE THREAD

**Issue by qq715152910** [godotengine/godot#37077] opened 2020-03-15 23:54 UTC
**Godot version:3.2.1:**

I have to talk about NinePatchRect again. I wonder if there is an error in the NinePatchRect algorithm in the control?
Below is an example of the NinePatchtexture plugin I wrote. You can see the obvious differences by comparing the effects.

[NinePatchTexture-Demo](https://codeload.github.com/qq715152910/Godot-Bug/zip/master)
![-5e8aa7331e9a8573](https://user-images.githubusercontent.com/58715110/76725245-8b63ad00-6788-11ea-96c8-4bb62669d05e.png)

OK, this is normal, then you look at the second picture, I have updated the demo, you can download a new demo to see a new demo example.
In Jiugong's standard algorithm:
1.The four corners should be kept (tiled) to their original size
2. The four sides should keep one-way scaling
3. The middle area should maintain two-way scaling

But I think NinePatchRect's current algorithm has lost its practical significance.

![test2](https://user-images.githubusercontent.com/58715110/76756918-9be44980-67c1-11ea-814d-f233e11edfeb.png)

**Comment by swarnimarun** [comment] 2020-03-16 10:27
You need to disable Filter in the settings of the Import tab for the texture.
![image](https://user-images.githubusercontent.com/19930870/76747239-d8eb1480-679e-11ea-96fe-eae898f797cb.png)

**Comment by swarnimarun** [comment] 2020-03-16 10:42
Aah sorry I got confused... 
But it looks like the problem is more clear with the Editor in the bottom panel.

**Comment by qq715152910** [comment] 2020-03-16 11:16
> Aah sorry I got confused...
> But it looks like the problem is more clear with the Editor in the bottom panel.

Please download the new Demo again and observe its borders and corners.

**Comment by swarnimarun** [comment] 2020-03-16 11:43
Yep that looks like a problem.
So have you tried the master with the PR merged to see if it was fixed.

**Comment by qq715152910** [comment] 2020-03-16 12:21
> Yep that looks like a problem.
> So have you tried the master with the PR merged to see if it was fixed.



> Yep that looks like a problem.
> So have you tried the master with the PR merged to see if it was fixed.

I just heard that it was normal before a certain version was merged, but I cannot test it temporarily, please check this post.
->
[#32170](https://github.com/godotengine/godot/pull/32170#issue-318084114)

**Comment by KoBeWi** [comment] 2020-07-03 18:39
I ran into this issue too. These rectangles use the texture with the same margins, but you can see that the borders look different:
![image](https://user-images.githubusercontent.com/2223172/86492059-146d1700-bd6d-11ea-92a2-60f6c4d8658f.png)
And here's a closer look, observe the bottom:
![JImsk76jd3](https://user-images.githubusercontent.com/2223172/86492079-2ea6f500-bd6d-11ea-88eb-1c7ca9d2f067.gif)
This should not happen.

**Comment by justinbowes** [comment] 2020-07-04 00:52
Totally agree. Documentation claims NinePatchRect is a "Scalable texture-based frame that tiles the texture's centers and sides, but keeps the corners' original size."

1.  When resizing the NinePatchRect, the corners are scaled, preserving their original aspect ratio. This is incorrect. The corners should simply not be scaled. (If there is a hidpi scaling adjustment, then it should not be based on the size of the NinePatchRect).

2. The texture's centers and sides are scaled, not tiled, but that seems to be awaiting an implementation for `axis_stretch_horizontal` and `axis_stretch_vertical`.

**Comment by justinbowes** [comment] 2020-07-04 00:59
The issue occurs when sizing the NinePatchRect to a smaller size than the backing texture.

Workaround: make the center column & row extremely narrow, i.e. 1px. The frame is affected only on scaling down, not up. 

This is not a great workaround, because it limits the amount of detail you can put in the center columns, but the effect is less significant until center column tiling is implemented.

**Comment by bluenote10** [comment] 2020-10-18 18:14
> When resizing the NinePatchRect, the corners are scaled, preserving their original aspect ratio.

I'm wondering if this is the only problem.

Here is another repoduction example: [ProgressBar.zip](https://github.com/godotengine/godot/files/5397916/ProgressBar.zip) + [code on GitHub](https://github.com/bluenote10/GodotDebugProjects/tree/master/ProgressBar). This is an attempt to implement a custom progress bar. As you can see the bar degenerates to a fat blob when the center column is supposed to become zero size:

![Peek 2020-10-18 19-50](https://user-images.githubusercontent.com/3620703/96375775-4cad2f80-117b-11eb-9d3c-1b8aaed9c869.gif)

I have added some "debugging pixel" to the progress bar texture to show where the three columns are:

![image](https://user-images.githubusercontent.com/3620703/96375820-a0b81400-117b-11eb-8706-2de36090d95d.png)

Basically the texture has a width of 18 pixels (6 + 6 + 6 pixels for the three columns), and a height of 16 pixel (8 + 0 + 8 pixels for the three rows). Accordingly, the left/right margins are set to 6 pixel, the top/bottom to 8 pixels.

I've set the minimum size to a width of 12 pixel, which should allow for the case of having only the left and the right column, but no center, resulting in a prefect circle (the 6 + 0 + 6 case). What happens instead is:

![Peek 2020-10-18 20-00](https://user-images.githubusercontent.com/3620703/96375964-8a5e8800-117c-11eb-854e-ded11fea3242.gif)

Note that it would be possible to "preserve the aspect ratio of the corners" just fine in this case: Their aspect ratio is 3x4 pixels, and that would fit into the 12x16 minimum size rect with the correct aspect ratio -- if the center would shrink down to zero.

Thus, I would say the bug is rather that the center fails to shrink below its original size. Instead the algorithm messes with the size of the corners, failing to satisfy what the documentation says _"... keeps the corners' original size"_ (and what would be much more intuitive).

Also it is a bit strange that the stretched area actually shows a color gradient. The debugging pixel jump from green to red at the boundary of the left to the center patch. The smooth transition from green to red is not what I would have expected:

![image](https://user-images.githubusercontent.com/3620703/96376116-59328780-117d-11eb-8c8c-ff4fbb495c94.png)

Any ideas if this is intended behavior / should be tracked as a separate bug?

**Comment by akien-mga** [comment] 2020-10-21 15:15
Fixed by #42119.

(At least the OP, I don't know if @bluenote10's comment is handled, but if not it should be reported as a new issue.)

**Closed by akien-mga** 2020-10-21 15:15 UTC
Labels: bug, confirmed, topic:core
