### ISSUE TITLE
MeshLibrary items preview are displayed upsidedown

### ISSUE THREAD

**Issue by SuperUserNameMan** [godotengine/godot#1248] opened 2015-01-17 15:39 UTC
Hi, 

Godot 1.0stable official, win64.

preview images of the items displayed into a MeshLibrary pannel are displayed upsidedown.

**Comment by reduz** [comment] 2015-01-17 15:46
hehe nice bug

**Comment by akien-mga** [comment] 2015-11-06 15:07
Is this issue still valid in the current master branch?

**Comment by akien-mga** [comment] 2016-04-01 09:00
Ping :)

**Comment by neikeq** [comment] 2016-04-01 10:17
I cannot reproduce it on current master branch. A quick way to check it is with the Platformer 3D demo in the _stage.xml_ scene.

**Comment by akien-mga** [comment] 2016-04-01 10:27
Closing then.

**Closed by akien-mga** 2016-04-01 10:27 UTC
Labels: bug, topic:editor
