### ISSUE TITLE
MODEL_NORMAL_MATRIX fragment shader crash/hang

### ISSUE THREAD

**Issue by GiantLuigi4** [godotengine/godot#95841] opened 2024-08-20 03:01 UTC
### Tested versions

- Not sure where this starts, but it exists in 4.3.stable; I'm also currently limited on time

### System information

Windows 10 - Godot 4.3 - Vulkan 1.3.278 - Forward+ - NVIDIA RTX 3080

### Issue description

Using MODEL_NORMAL_MATRIX in a spatial shader's fragment code crashes the godot editor

However, this does not always crash it. Sometimes it just hangs for a while.

### Steps to reproduce

Write some code involving `MODEL_NORMAL_MATRIX` in the fragment portion of a spatial gdshader

Example:

```glsl
void fragment() {
    float viewDot = dot(NORMAL, CAMERA_DIRECTION_WORLD * MODEL_NORMAL_MATRIX);
}
```

This has nothing to do with even using it, simply including that in the fragment shader is enough.

```glsl
mat3 mNor = MODEL_NORMAL_MATRIX
```

[log.txt](https://github.com/user-attachments/files/16668259/log.txt) [I abruptly remembered that pastebin exists, so as a paste for anyone who prefers that](https://pastebin.com/sHAYDzst)

### Minimal reproduction project (MRP)

[project.zip](https://github.com/user-attachments/files/16668263/project.zip)

**Comment by GiantLuigi4** [comment] 2024-08-20 03:04
Also worth noting that even in the event that it doesn't crash, the shader doesn't load, and it also doesn't say that there's any error with the shader.

**Comment by tetrapod00** [comment] 2024-08-20 03:17
Confirmed. My specs: Windows 10.0.19045 - Vulkan (Mobile) - dedicated NVIDIA GeForce GTX 1660 Ti with Max-Q Design (NVIDIA; 32.0.15.5612) - AMD Ryzen 7 3750H with Radeon Vega Mobile Gfx (8 Threads)

No crash in 4.3 Compatibility.
Crash/hang confirmed in 4.3 Mobile.
Crash/hang confirmed in 4.3 Forward+

On 4.2.2.stable.mono Mobile, I get a very long console output but no hang or crash. I think this is the start of the log:
[model_normal_matrix_output_log_42.txt](https://github.com/user-attachments/files/16668403/model_normal_matrix_output_log_42.txt)

On 4.1.3.stable.mono, I get a very long console output but no hang or crash.

**Comment by clayjohn** [comment] 2024-08-20 03:36
I think this is a duplicate of https://github.com/godotengine/godot/issues/85586 combined with another issue. We have long had on again off again issues with especially long error prints causing freezes/crashes on windows. I suspect that is what is going on here

**Comment by jsjtxietian** [comment] 2024-08-20 03:38
> I suspect that is what is going on here

It is.

**Comment by akien-mga** [comment] 2024-08-20 08:44
Closing as #85586 was fixed.

**Closed by akien-mga** 2024-08-20 08:44 UTC
Labels: bug, topic:shaders
