### ISSUE TITLE
Tab is not working correctly on Inspector (Godot 4)

### ISSUE THREAD

**Issue by lexum0** [godotengine/godot#58951] opened 2022-03-09 21:22 UTC
### Godot version

4.0 Alpha 4

### System information

Windows 10

### Issue description

Using tab on Inspector behaves unexpectedly

<img width="293" alt="Screen Shot 2022-03-09 at 15 17 38" src="https://user-images.githubusercontent.com/2546522/157538134-d0dcbc54-12a6-4545-befd-eaf765c735c9.png">
<img width="287" alt="Screen Shot 2022-03-09 at 15 17 50" src="https://user-images.githubusercontent.com/2546522/157538151-efe510f8-5ce4-4820-9190-418a10203442.png">

### Steps to reproduce

Click a node, go to Transform, change the X value, then use tab twice to move forward and it will start behaving unexpectedly. Then use Shift + Tab twice and the same will happen

**Comment by Calinou** [comment] 2022-03-09 21:25
Duplicate of https://github.com/godotengine/godot/issues/37723.

**Closed by Calinou** 2022-03-09 21:25 UTC
