### ISSUE TITLE
Container children resetted when editing parent

### ISSUE THREAD

**Issue by H4kor** [godotengine/godot#4954] opened 2016-05-31 14:33 UTC
OS: Xubuntu 15.05
Godot Version: 2.0.3 stable

Elements placed inside a Container (ScrollContainer) are resetted when the parent is manipulated. 
The changes are also not applied when playing the scene.
(See video for behavior and steps to reproduce)

Recording of the issue: https://youtu.be/EGCjYfwX3PU
Forum entry of other people having the same problem: http://godotdevelopers.org/index.php?topic=15521.0

**Comment by bojidar-bg** [comment] 2016-05-31 15:12
This is not a bug, it is a "feature" -- containers are supposed to move and reposition their children according to the children's min-size property.

Since ScrollContainer is a Container, it behaves the same way, which is slightly incorrect probably. Thus, to fix this issue ScrollContainer should stop being a Container, or you should just add an additional child Control with a min-size as much as you want.

**Comment by bojidar-bg** [comment] 2017-01-20 12:21
So... what should be done on this one? I personally like the Containers concept myself...

**Comment by DualMatrix** [comment] 2018-09-21 11:37
Related to #20750

**Comment by HummusSamurai** [comment] 2018-10-05 13:49
Should be closed if I am not mistaken.

**Comment by akien-mga** [comment] 2018-10-05 14:06
Yes, the "discussion" part seems non consensual, and the "enhancement" part is fixed in #20750.

**Closed by akien-mga** 2018-10-05 14:06 UTC
Labels: discussion, enhancement, topic:core
