### ISSUE TITLE
String format strips quotation marks from values before printing

### ISSUE THREAD

**Issue by Mercerenies** [godotengine/godot#50600] opened 2021-07-19 00:02 UTC
### Godot version

3.3.2.stable.official

### System information

Fedora 31

### Issue description

The `format` method on strings strips off a matching outer pair of quotation marks. For example
```
var example = "\"Example\""
print("{}".format([example], "{}"))
```
The `example` string contains an open quotation mark, the word Example, and a close quotation mark. But when we print it using the above snippet of code, it will only print the word Example, without the quotes.

### Steps to reproduce

Open the attached project, run the scene `Main.tscn`. The expected output is `"Example"` (with quotes). The actual output on Godot 3.3 is `Example` (without quotes)

### Minimal reproduction project

[formatbug.zip](https://github.com/godotengine/godot/files/6837145/formatbug.zip)

**Comment by Calinou** [comment] 2021-07-19 00:20
Duplicate of https://github.com/godotengine/godot/issues/49262 (fixed by https://github.com/godotengine/godot/pull/49291 in 3.4bet1 and later).

**Closed by Calinou** 2021-07-19 00:20 UTC
