### ISSUE TITLE
[4.0.3rc1] Editor crashes when adding a CollisionShape2D as child to Area2D

### ISSUE THREAD

**Issue by tufduckhotmailcom** [godotengine/godot#76655] opened 2023-05-01 19:39 UTC
### Godot version

4.0.3 rc1

### System information

Windows 10

### Issue description

Seems like there's some issue with CollisionShape2Ds in 4.0.3. Everytime I try to add a collision shape to an Area2D the editor crashes.

It works in 4.0.2.

### Steps to reproduce

1) Create a new project in 4.0.3rc1. 
2) Add a new Area2D scene.
3) Add a CollisionShape 2D. Editor crashes.

### Minimal reproduction project

Not needed

**Comment by kleonc** [comment] 2023-05-01 20:55
Duplicate of #76543 (workaround: https://github.com/godotengine/godot/issues/76543#issuecomment-1527667759).

**Closed by kleonc** 2023-05-01 20:55 UTC
