### ISSUE TITLE
Image clip/cut off when using display/window/size/resizable - ON

### ISSUE THREAD

**Issue by drmar** [godotengine/godot#40620] opened 2020-07-23 05:43 UTC
**Godot version:**
Godot 3.2.3.beta1.official

**OS/device including version:**
macOS Catalina 10.15.6 / MacBookPro11,1 / GLES2

**Issue description:**
When using display/window/size/resizable - ON, the image gets clipped/cut off in the bottom part of the screen.

**display/window/size/resizable - OFF**

![Screenshot 2020-07-23 at 08 29 29](https://user-images.githubusercontent.com/13488692/88255196-69db7a80-ccc0-11ea-93fa-ec0caf792a78.png)

**display/window/size/resizable - ON**

![Screenshot 2020-07-23 at 08 29 40](https://user-images.githubusercontent.com/13488692/88255208-765fd300-ccc0-11ea-8a5e-bb90aece9689.png)

**Steps to reproduce:**
Run the attached project (Godot 3.2.3.beta1.official) **with** and **without** display/window/size/resizable **on/off**.

**Minimal reproduction project:**
[Image Tear.zip](https://github.com/godotengine/godot/files/4964011/Image.Tear.zip)

**Comment by Calinou** [comment] 2020-07-23 08:14
Related to https://github.com/godotengine/godot/issues/35899.

**Comment by akien-mga** [comment] 2021-04-28 13:22
Isn't this the same issue as #35899?

**Comment by drmar** [comment] 2021-06-13 05:28
> Isn't this the same issue as #35899?

No, different problem.

**Comment by Calinou** [comment] 2022-08-07 19:43
I think this is actually a duplicate of https://github.com/godotengine/godot/issues/35899. The entire viewport is slightly scaled above 1 on the Y axis, and since nearest-neighbor filtering is used to scale the viewport in Godot, you notice scaling artifacts (tearing lines in this case).

**Closed by Calinou** 2022-08-07 19:43 UTC
Labels: bug, platform:macos, topic:rendering
