### ISSUE TITLE
Tabs in TextEdit do not get highlighted when selected

### ISSUE THREAD

**Issue by EricEzaM** [godotengine/godot#44450] opened 2020-12-17 10:44 UTC
**Godot version:**
4.0 master 2020/12/17

**OS/device including version:**
WIN 10

**Issue description:**
Tabs do not get highlighted.
![tabs_no_highlight](https://user-images.githubusercontent.com/41730826/102477903-b1680600-40a8-11eb-96f5-ffbab5f0cf40.gif)

**Steps to reproduce:**
Try highlight tabs

**Comment by akien-mga** [comment] 2020-12-17 10:51
Duplicate of #42656, might be fixed by #42975 if you want to test/review.

**Comment by EricEzaM** [comment] 2020-12-17 10:58
@akien-mga No, that is RichTextLabel. This is a TextEdit.

**Closed** 2020-12-23 00:15 UTC
Labels: bug, topic:gui
