### ISSUE TITLE
Inconsistent _draw() behavior between Control and Node2D

### ISSUE THREAD

**Issue by null-digital** [godotengine/godot#34119] opened 2019-12-05 17:16 UTC
**Godot version:**
3.1.2

**OS/device including version:**
Ubuntu 18.04

**Issue description:**
In GDScript, Control can't draw things when created with new(), only with instance(). Node2D can draw on both cases.

**Steps to reproduce:**
-Create new object of a Control or a subclass of it that implements _draw().
-Add the object to the scene using add_child(). Nothing is drawn.

**Minimal reproduction project:**
[temp.zip](https://github.com/godotengine/godot/files/3928176/temp.zip)

**Comment by bojidar-bg** [comment] 2019-12-05 17:29
Checking with the remote scene tree like it just does not get proper anchors, and thus the Control created with `.new()` has a (0,0) size (and is positioned at (0,0)).
Adding code akin to this seems to fix it:
```
	control_new.anchor_bottom = 1
	control_new.anchor_right = 1
```
Thus, this is a duplicate of #17917.

**Closed by bojidar-bg** 2019-12-05 17:29 UTC
Labels: bug, topic:core
