### ISSUE TITLE
Godot 4 crash cause by function change_scene_to_packed

### ISSUE THREAD

**Issue by enemy141** [godotengine/godot#74278] opened 2023-03-03 08:26 UTC
### Godot version

4.0

### System information

Windows 10

### Issue description

Godot 4 crashes when using the function change_scene_to_packed to change the scene if the scene has the same script as the previous scene

### Steps to reproduce

https://user-images.githubusercontent.com/88548945/222669614-456330a8-b1bf-4922-a159-cd26e1698c78.mp4

### Minimal reproduction project

[change_scene_byPackedScene.zip](https://github.com/godotengine/godot/files/10880013/change_scene_byPackedScene.zip)

**Comment by dzil123** [comment] 2023-03-03 08:37
Duplicate of #24146

**Comment by Calinou** [comment] 2023-03-03 08:59
- Duplicate of https://github.com/godotengine/godot/issues/24146.

**Closed by Calinou** 2023-03-03 08:59 UTC
