### ISSUE TITLE
Mono: Base class members reset to their default values if derived class has [Tool]

### ISSUE THREAD

**Issue by Phischermen** [godotengine/godot#37812] opened 2020-04-11 19:13 UTC
**Godot version:**
3.2.1.stable.mono

**OS/device including version:**
Windows 10

**Issue description:**
C# base class members reset themselves to their default values every time the project is built if the derived class has the [Tool] attribute. I have not been able to reproduce the issue in gdscript.

**Steps to reproduce:**
1. Download the sample project.
2. Set exported variables to something other than their defaults. "B" is from Base.cs and "D" is from Derived.cs.
3. Make some changes to either Base.cs or Derived.cs (other than changing the [Tool] attribute) so that the project has to be rebuilt.
4. Press build.
5. Check "B." It should have reset its value.

**Minimal reproduction project:**
[DerivedC#BugTest.zip](https://github.com/godotengine/godot/files/4465226/DerivedC.BugTest.zip)

**Comment by Pahasz** [comment] 2020-04-27 22:17
I'm having the same problem but I didn't make an issue because I couldn't reproduce it reliably. It's super annoying now because I've converted a lot of scripts to C# and it's resetting (seemingly) random sets of nodes in my scenes.

For instance, if I have a wall, a couch, a vending machine, and a sink, it will sometimes decide to reset just the walls and the couch but not the others. They all derive from the same classes and all use the [Tool] functionality. Hope this gets looked at!

**Comment by Phischermen** [comment] 2020-04-27 23:17
@Pahasz Do you think you are now able to reproduce the issue by following my instructions?

**Comment by Pahasz** [comment] 2020-04-28 00:48
@Phischermen Yes I was able to reproduce it in the reproduction project using those exact steps.

**Comment by reimgrab** [comment] 2020-05-28 01:11
Same here and it is super annoying. Cannot really use the Godot editor to build test levels anymore as I could when my game was still written in GDScript.

**Comment by Pahasz** [comment] 2020-07-31 01:01
Any update on this?

**Comment by ksvslk** [comment] 2020-07-31 06:01
> Any update on this?

Also interested in the solution of this issue.

**Comment by Phischermen** [comment] 2020-07-31 14:07
There is this [post in the Godot Devblog](https://godotengine.org/article/csharp-vs-and-vscode). It seems that after Ignacio organizes the Godot API into namespaces and provides a .NET friendly IO API for the Godot virtual file system, he will dedicate a month to bug fixing

**Comment by rexfleischer** [comment] 2020-08-04 01:53
this is also happening on 3.2.2.stable.mono

**Comment by Paha-Zul** [comment] 2020-08-08 22:44
It's been happening from 3.2.1 through 3.2.3 beta-1 for me.

**Comment by Scripptor** [comment] 2021-02-18 07:37
Happens on 3.2.3.stable.mono
It only seems to affect scenes that are currently opened, active or in the background!
So if you want to save your work and you have a level with inherited tool scenes with script variables, please close the level scene before building! This might just save you some time!

**Comment by Paha-Zul** [comment] 2021-03-24 00:15
Still happens on 3.3 RC 6. Tested with the sample project to confirm.

**Comment by Drkie** [comment] 2021-12-07 04:03
Still happening on v3.4.stable.mono. This heavily discourages the use of `[Tool]` because of how easy it is to lose data in all your open scenes without any warning. Even innocuous changes to the class such as adding a comment will trigger this bug.

**Comment by Krumelur** [comment] 2021-12-14 20:27
Also seeing this here with 3.4 (stable and RC2). My observations, maybe they help:

* It seemingly never affects boolean values. But I see it with `string` and `Vector2`.
* It only affects exported properties, not member variables.
* It does not matter if a backing field is used or not.
* The `set` isn't called when the resetting happens. Suddenly, the default value of the backing field is returned from `get`.
* The entries for the property values in the TSCN file disappear (are removed), this can be seen when using source control.
* It happens only sporadically. I've been coding for 2h without a problem and now most of my property values are gone.
* It seems to affect `[Tool]` decorated classes that derive from custom base classes.

**Comment by Krumelur** [comment] 2021-12-15 05:58
Thank you @raulsntos! What’s the timeline for 3.5 and do you have a workaround for the meantime, even if it means changing some code?

**Comment by raulsntos** [comment] 2021-12-15 16:43
> Do you have a workaround for the meantime, even if it means changing some code?

You can workaround it by closing the scene before building, as described by **Scripptor**: https://github.com/godotengine/godot/issues/37812#issuecomment-781123464

**Comment by DwarfNinja** [comment] 2021-12-15 19:26
> Do you have a workaround for the meantime, even if it means changing some code?

The current workaround I've been using is to convert the C# Resources to GDScript and create a C# wrapper for them. Here's an example:
```cs
//The wrapper class of a resource
public class MyResourceWrapper {

    private Resource resource;

    public Resource Resource {
        get => resource;
        set => resource = value;
    }

    public MyResourceWrapper (Resource resource) {
        Resource = resource;
    }

    public static MyResourceWrapper LoadResource(string filePath) {
        return new MyResourceWrapper (ResourceLoader.Load<Resource>(filePath));
    }

    public string MyProperty1 {
        get => (string) Resource.Get("MyProperty1");
        set => Resource.Set("MyProperty1", value);
    }
    
        public int MyProperty2 {
        get => (int) Resource.Get("MyProperty2");
        set => Resource.Set("MyProperty2", value);
    }
}
```
PS. In practice I have the Resource field/property and constructor delegated to an abstract class.

When needing to use a Resource in a class I export a Resource property and use the getter and setter to handle the correct conversion/wrapping. (Perhaps not the the cleanest, the set/get functionality could also be delegated to the constructor but you get the idea).
```cs
 //Class that uses a Resource
    [Export] 
    public Resource MyResource {
        get => myResource?.Resource;
        set {
            myResource = value switch {
                null => null,
                MyResourceWrapper resource => resource,
                _ => new MyResourceWrapper(value)
            };
        } 
    }
    
    private MyResourceWrapper myResource;
```
This main advantage from this solution is that it allows me to use the ResourceWrappers like they are real C# Resources and keeps refactoring of my code minimal. This also futureproofs for when the fix releases, as all I need to do is switch the GDScript resources back to C#, and use those instead of the wrapper.

**Comment by Krumelur** [comment] 2021-12-18 15:19
What replacing all properties with class member variables also work? Or would they be reset randomly, just as well?

**Comment by Calinou** [comment] 2021-12-18 16:44
> Also, can we vote to get a 3.4.2 and include the fix there? The workarounds are not really options IMHO and waiting months for 3.5 isn't a pretty alternative :-(

Since https://github.com/godotengine/godot/pull/53942 doesn't break compatibility with existing projects, it should be safe to cherry-pick to 3.4.2.

In the meantime, you could [build a Mono-enabled editor and export templates from source](https://docs.godotengine.org/en/stable/development/compiling/compiling_with_mono.html) with https://github.com/godotengine/godot/pull/53942 included.

**Comment by erayzesen** [comment] 2021-12-26 06:30
I have struggled a lot in the past with this problem, I'm glad that this error is fixed in the next version. 

I suggest you a safe solution, it was always worked for me. Define your main variable as a **virtual** variable in base class and re-define your variable as **override** .

Example;

Base class;
```
public virtual float myVariable{get;set;};
[Export]
public float myVariableConfig{
  get{return myVariable;}
  set{myVariable=value; }
}
```
Inherited class;
`public override float myVariable;`
 
When we define the variable in this way with  "override", it treats its as a special variable that is not specific to heritage class. So we're fooling Godot.

**Comment by raulsntos** [comment] 2021-12-28 18:04
I'm sorry, I don't think I made myself clear. This issue is not fixed in `master` or `3.x`, I meant to say that the mentioned PR is unrelated and does not solve this issue but a different one.

**Closed** 2021-12-28 23:14 UTC
Labels: bug, topic:editor, confirmed, topic:mono, high priority
