### ISSUE TITLE
Stretch Mode "viewport" causes screen not to update / black screen

### ISSUE THREAD

**Issue by exploids** [godotengine/godot#23054] opened 2018-10-16 16:54 UTC
**Godot version:** 3.0.6

**OS/device including version:**
Windows 10 x86_64,
NVIDIA GeForce GTX 650 Ti/PCIe/SSE2

**Issue description:**
When setting the *Stretch Mode* in the project settings to "viewport" and running the game, it will render the splash screen as expected, but unless the window size is exactly the same as the viewport size, it won't render the game to the screen, keeping the splash screen displayed and filling the window with black when it's being resized.
Furthermore, there aren't any error messages printed and the frames seem to be rendered internally, but not displayed, if the framebuffer (?) had to be scaled.

![viewport](https://user-images.githubusercontent.com/32574654/47050843-21656380-d1a2-11e8-9319-c284026bc486.gif)

**Steps to reproduce:**
1. Go to the project settings and set *Stretch Mode* to "viewport"
1. Run the game, try different *Test Sizes* and try resizing the window
1. The game should only be rendered, if the window size matches the viewport size (note: if *Stretch Aspect* is set to "keep" only the width or the height need to match)

**Minimal reproduction project:**
[Viewport Bug.zip](https://github.com/godotengine/godot/files/2484097/Viewport.Bug.zip)

**Comment by Demiu** [comment] 2019-10-05 17:30
I have also encountered this issue

Godot version: 3.1.1

OS/device including version:
Windows 10 Pro N 1803
GTX 1060 6GB, Nvidia drivers 399.24

Additionally, switching to GLES 2 in the editor removes this issue

**Comment by Calinou** [comment] 2019-10-07 15:22
@exploids Are you forcing MSAA at the graphics driver level? If so, the cause may be similar to https://github.com/godotengine/godot/issues/18320#issuecomment-494470140.

**Comment by Demiu** [comment] 2019-10-07 23:08
@Calinou Can confirm that turning off AA in Nvidia's Control Panel fixes the issue

**Comment by Calinou** [comment] 2019-10-08 00:45
@Demiu Thanks for replying, I'll close this as a duplicate of #18320 then :slightly_smiling_face:

**Closed by Calinou** 2019-10-08 00:45 UTC
Labels: bug, confirmed, topic:core
