### ISSUE TITLE
Invalid importing model with skeleton only

### ISSUE THREAD

**Issue by caffeine-mgn** [godotengine/godot#54483] opened 2021-11-01 14:02 UTC
### Godot version

3.3.4.stable.mono.offical (faf3f883d)

### System information

Windows 10, GLSL3, Geforce 3090

### Issue description

In case when model doesn't have mesh glb import to godot as several spatials nodes.
And if add any mesh to skeleton godot will import as mesh + skeleton with bones.

### Steps to reproduce

In blender create any skeleton and then export it to glb or fbx. Import exported file to godot. Look that godot shows several spatial instead of skeleton.

And then add any mesh to you skeleton on blender and export again. And in this 

### Minimal reproduction project

[Test.zip](https://github.com/godotengine/godot/files/7453775/Test.zip)

**Comment by fire** [comment] 2021-11-01 16:33
Blender can only export its armature if it is part of a mesh. I'm not sure what to do in Godot to guess.

**Comment by aaronfranke** [comment] 2024-09-08 09:47
This was a bug in Blender, not a bug in Godot, and this is now fixed in Blender.

In the attached project, `fail.glb` does not contain skins. Therefore, Godot is correctly importing this as plain nodes, because nothing in the file indicates that there should be a skeleton.

However, with Blender 4.2, if using Godot's `.blend` file import feature, or re-exporting a `.glb` or .gltf` from Blender, the resulting file has skin data, indicating that this file contains a skeleton:

```json
    "skins": [
        {
            "inverseBindMatrices": 0,
            "joints": [6, 5, 4, 3, 2, 1, 0],
            "name": "Armature"
        }
    ],
```

And now that the data in the file is correct, the file correctly imports into Godot:

<img width="560" alt="Screenshot 2024-09-08 at 2 43 50 AM" src="https://github.com/user-attachments/assets/05867f9c-08db-408d-b000-bf00b4e6912a">

**Comment by fire** [comment] 2024-09-08 17:05
Thanks for investigating. We can close shortly.

**Closed** 2024-09-09 04:11 UTC
Labels: bug, topic:import, topic:3d
