### ISSUE TITLE
Selecting any [non spatial node] leaves the GIProbe grid highlighted

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#13849] opened 2017-12-03 04:55 UTC
Godot 3.0 beta 1
Godot 3.2.3
Windows 10 64 bits

Repro:
1) Select a GIProbe node: see the cubic green grid is highlighted. (It is even more visible with high res probes to the point it can even occlude what's behind it)
2) Now select a `Node`, or a `WorldEnvironment`: notice the green grid is still highlighted, this is unexpected
3) Click a `Spatial` node: the grid is no longer highlighted

Edit: also happens with Particles.

Edit 2: also happens with collision shapes and cameras

**Comment by kubecz3k** [comment] 2017-12-03 09:09
I confirmed on af27414b1c10173584539186e396668a899e06b2 Linux build

**Comment by akien-mga** [comment] 2017-12-11 11:05
Working on this one.

**Comment by akien-mga** [comment] 2017-12-11 12:15
The problem is the following:
- The drawing of SpatialEditor gizmos is triggered here: https://github.com/godotengine/godot/blob/dfb3634/editor/plugins/spatial_editor_plugin.cpp#L3995-L4030
- When switching from one Spatial to another, this code is properly triggered via https://github.com/godotengine/godot/blob/bdde821/editor/editor_node.cpp#L1594 which calls SpatialEditorPlugin->edit() on the new Spatial, cleaning up previous gizmos before adding new ones
- When switching to a non-Spatial, it can:
  * Change the main screen plugin, e.g. move to CanvasItemEditorPlugin if you pick a Node2D, thus triggering this branch: https://github.com/godotengine/godot/blob/bdde821/editor/editor_node.cpp#L1569-L1592 - but here it will call CanvasItemEditorPlugin->edit() on the newly selected 2D node, and that won't trigger the Spatial gizmo cleanup
  * If you pick Node (no linked editor plugin), it even bails out earlier and skips those branches altogether, so there's also no cleanup done

Not sure how to handle this properly.

**Comment by akien-mga** [comment] 2018-01-05 14:09
Unassigning myself for now, as I don't know how to go beyond the debugging I wrote above.

**Comment by akien-mga** [comment] 2018-01-05 14:09
We have now entered release freeze for Godot 3.0 and want to focus only on release critical issues for that milestone. Therefore, we're moving this issue to the 3.1 milestone, though a fix may be made available for a 3.0.x maintenance release after it has been tested in the master branch during 3.1 development. If you consider that this issue is critical enough to warrant blocking the 3.0 release until fixed, please comment so that we can assess it more in-depth.

**Comment by Zylann** [comment] 2018-01-15 20:08
The same happens with Particles in RC1.

**Comment by akien-mga** [comment] 2018-09-11 09:32
Reopening as #21831 was reverted with #21967.

**Comment by Zylann** [comment] 2020-10-23 22:15
I'm hitting https://github.com/godotengine/godot/issues/6459#issuecomment-653980413 again, and I think if some proper method can handle deselection it would be easy to fix issues like this.

**Comment by akien-mga** [comment] 2023-01-05 14:01
Reopening as #70907 undid the fix for this issue.

**Comment by xiongyaohua** [comment] 2023-01-06 02:05
Hi, I'd like to try my hand fixing this issue and related gizmo deselect issues in a proper way mentioned by @KoBeWi in https://github.com/godotengine/godot/pull/61292

> A more proper solution would be keeping track of plugins that successfully edited an object (i.e. returned true with handles()) and add an unedit() method (or just edit(null)) called when that plugin can no longer handle an object. But that requires more work and there doesn't seem to be much demand for it.

As I am quite new to the editor code. I think it is better to lay out my plan and get some feed back on whether it looks feasible, before dive into coding. So the plan is:
1. Assuming at most one `EditorPlugin` can be active at any moment,
2. Add an pointer to `EditorNode` singleton, tracking current active `EditorPlugin`, maybe called `EditorPlugin* active_editor_plugin`
3. In the `edit(p_object)` method of each subclass of `EditorPlugin`, test if `p_object` is going to be edited. If yes, first call `EditorNode::active_editor_plugin->edit(null)` to release the old editor plugin, then register current editor plugin to the `EditorNode::active_editor_plugin`.

**Comment by KoBeWi** [comment] 2023-01-20 00:57
@xiongyaohua Sorry for the late reply, but I recently started working on this. I took a similar approach to what you mentioned, except that I want to support multiple active plugins. For that, we need to track source of the edit (e.g. from scene tree or from unfolded property) and edit or unedit plugins accordingly. This will also take care of some other issues.

The problem with single active plugin is that it might not work in some cases, e.g. TileMap/TileSet (although AFAIK TileMap already uses some hack to support this).

**Closed** 2023-01-22 10:20 UTC
Labels: bug, topic:editor, confirmed
