### ISSUE TITLE
Rectangle collisionshap2d looks weird

### ISSUE THREAD

**Issue by JustADeer** [godotengine/godot#66089] opened 2022-09-19 07:09 UTC
### Godot version

4.0 beta 1

### System information

Windows 10, Vulcan Clustered, GTX 750ti

### Issue description

The rectangle shape is looking wonky theres likes a triangle on the end

### Steps to reproduce

make a collision shape with a rectangle shape

**Comment by akien-mga** [comment] 2022-09-19 08:32
Duplicate of #56320.

**Closed by akien-mga** 2022-09-19 08:32 UTC
