### ISSUE TITLE
3.1.1 Mono Stable OSX: Export project to .DMG not working

### ISSUE THREAD

**Issue by MMichael789** [godotengine/godot#28926] opened 2019-05-16 01:28 UTC
**Godot version:** 3.1.1 Stable

**OS/device including version:** OSX 10.14.4

**Issue description:**
When trying to export my game (as project/.dmg) for OSX (runnable), I get the error: "Failed to export the project for platform 'Mac OSX.' This might be due to a configuration issue in the export preset or your export settings." I feel like there is a problem with the export preset because exporting to Windows and Linux works fine. I've redownloaded the export template multiple times and removed any preference files to do a fresh reinstall to make sure that it wasn't corrupted or anything, but still no luck.

**UPDATE:** I also downgraded to 3.1.0 and tried the same thing, and even there it gave me the same error.

**Steps to reproduce:**
- Make any simple Godot project that uses GDScript on the Mono 3.1.1 version on OSX
- Download the 3.1.1.stable.mono export template and export the game to 'Mac OSX (runnable)'
- Error popup and console error about the stuff shown above

**Screenshots:**
<img width="897" alt="Screen Shot 2019-05-15 at 9 00 05 PM" src="https://user-images.githubusercontent.com/46657513/57819060-b0485780-7754-11e9-987f-66cd5b31ddad.png">

<img width="767" alt="Screen Shot 2019-05-15 at 9 00 41 PM" src="https://user-images.githubusercontent.com/46657513/57819065-b76f6580-7754-11e9-9b4d-1812cca9f73a.png">

**Export Settings (Only 'Options' was modified):**

<img width="434" alt="Screen Shot 2019-05-15 at 9 01 03 PM" src="https://user-images.githubusercontent.com/46657513/57819087-d837bb00-7754-11e9-9127-e79965984fd2.png">

<img width="422" alt="Screen Shot 2019-05-15 at 9 01 10 PM" src="https://user-images.githubusercontent.com/46657513/57819089-dc63d880-7754-11e9-8584-1f5dc1c332b8.png">

**Comment by akien-mga** [comment] 2019-05-16 06:52
Might be the same issue as #26126.

**Comment by MMichael789** [comment] 2019-05-16 12:14
I looked at that one but it had a different error at the top, but now I noticed it's the same thing. I mean I can export to ZIP like they showed there and then make my own customized DMG, but weird stuff.

**Comment by Viacheslav-Romanov** [comment] 2019-11-22 15:13
Any news on when it'll be fixed?

**Comment by akien-mga** [comment] 2020-01-02 17:37
Closing as duplicate of #26126.

**Closed by akien-mga** 2020-01-02 17:37 UTC
Labels: bug, platform:osx, topic:mono
