### ISSUE TITLE
Proximity fade does not work (again)

### ISSUE THREAD

**Issue by aqnuep** [godotengine/godot#27301] opened 2019-03-21 22:47 UTC
**Godot version:**
Since 0eb61c3106c0498114d796ef3baa52b31084fde9, including 3.1 stable.

**OS/device including version:**
All

**Issue description:**
Proximity fade got broken, issue was reported in #25870, was fixed with PR #25557 but in a way that introduced other problems according to #26258, so it was backed out in 0eb61c3106c0498114d796ef3baa52b31084fde9, but the original issue wasn't reopened.

**Steps to reproduce:**
See issue #25870.

(NOTE: it would make things easier if closed issues could be reopened instead of re-reporting them)

**Comment by clayjohn** [comment] 2019-03-22 00:14
Yes it was. https://github.com/godotengine/godot/issues/25535

**Comment by aqnuep** [comment] 2019-03-22 00:27
Fair enough, that's the wider issue which covers this as well.

Anyway, I'll come back with a PR, because there's quite a bit of a mess in the conditions of depth-prepass. I think it might be the reason why (at least it seems) SSAO doesn't work either.

**Comment by akien-mga** [comment] 2019-04-01 10:56
Duplicate of #25535.

**Closed by akien-mga** 2019-04-01 10:56 UTC
Labels: bug, topic:rendering
