### ISSUE TITLE
Changing transforms in process method breaks velocity in Visual Shader Particles

### ISSUE THREAD

**Issue by fracteed** [godotengine/godot#67524] opened 2022-10-17 08:49 UTC
### Godot version

4.0 beta 3

### System information

WIn10 960m

### Issue description

When connecting a constant or any value into the scale or angle sockets within the process method, the velocity breaks and all particles are repositioned at the origin. As can be seen in this screencapture, the scale or angle is updated, but velocity is zeroed out. 

https://user-images.githubusercontent.com/7741669/196132019-ce7feaab-da50-49fd-8798-60b922d2d5a3.mp4

@Chaosus is this a known bug?

### Steps to reproduce

Create a visual shader for a gpu particle system and add some velocity in the start method.

Try to change the scale or angle in the process method by plugging a constant (or any) node in.

### Minimal reproduction project

[particle_transform_bug.zip](https://github.com/godotengine/godot/files/9798568/particle_transform_bug.zip)

**Comment by Chaosus** [comment] 2022-10-17 09:16
> @Chaosus is this a known bug?

Can't remember really.

**Comment by Chaosus** [comment] 2022-10-17 09:47
Duplicate of https://github.com/godotengine/godot/issues/56358

**Closed by Chaosus** 2022-10-17 09:47 UTC
Labels: bug, topic:particles
