### ISSUE TITLE
Segmentation fault when closing

### ISSUE THREAD

**Issue by LeonardoDemartino** [godotengine/godot#95708] opened 2024-08-17 18:13 UTC
### Tested versions

- Reproducible: Godot 4.3

### System information

macOS Sonoma 14.5

### Issue description

Apple rejected an app made on Godot for macOS because:
> Issue Description
> The app crashed during review. Apps that crash negatively impact App Store users.
> Steps leading to crash:
> - Launched the app
> - Closed the main window
> - Crashed

And yes, indeed the app was segfaulting when closing (we didn't notice this before since it is inoffensive, a normal user will probably never notice that the app is crashing at the same time it closes).

So my mission after that was to start removing parts of my project until the segfault was gone, long story short: it has to do with C# references to AudioBuses (it doesn't happen if you use gdscript for some reason)
`AudioServer.GetBusEffect`
I have created a Minimal reproduction project.

A workaround to this crash is to:

```
public override void _Notification(int what) {
    if (what == NotificationWMCloseRequest) {
        // Clear AudioBuses
        int c = AudioServer.GetBusCount()-1;
        for (int b = 0; b < c; b++)
            AudioServer.RemoveBus(1);
        GetTree().Quit();
    }
}
```

### Steps to reproduce

* Build an .app (I don't know if this affects other OS)
* Run it from the terminal
* Close the app normally
* You'll see in the terminal "zsh: segmentation fault [app_path]"

### Minimal reproduction project (MRP)

[segfault.zip](https://github.com/user-attachments/files/16645891/segfault.zip)

**Comment by raulsntos** [comment] 2024-08-18 00:04
Sounds like it may be a duplicate of https://github.com/godotengine/godot/issues/95404 or https://github.com/godotengine/godot/issues/92076. Can you check if https://github.com/godotengine/godot/pull/93172 fixes it?

**Comment by LeonardoDemartino** [comment] 2024-08-18 15:02
Yes @raulsntos, that PR fixes the segfault. Thanks.

**Closed** 2024-08-19 12:38 UTC
Labels: bug, needs testing, topic:dotnet, crash
