### ISSUE TITLE
BBCode formatting does not synergize with visible_characters

### ISSUE THREAD

**Issue by Fotheringay** [godotengine/godot#30355] opened 2019-07-05 21:22 UTC
**Godot version:**
v.3.1.1

**OS/device including version:**
Windows 10 

**Issue description:**
Underlined and strike-through text in BBCode are shown even if characters are hidden. 
![image](https://i.imgur.com/Kxk9PKl.png) 
Neither visible_characters nor percent_visible manage to display it correctly.

**Comment by volzhs** [comment] 2019-07-05 21:36
attaching a reproducible project will help to fix this issue a little bit faster. :smile:

**Comment by Fotheringay** [comment] 2019-07-08 17:57
Right, sorry about that! Added one.

[BBCode error proofOfConcept.zip](https://github.com/godotengine/godot/files/3369648/BBCode.error.proofOfConcept.zip)

**Comment by cwook** [comment] 2019-12-05 23:38
Duplicate of #21637 ?

**Comment by Calinou** [comment] 2019-12-06 00:03
@cwook Indeed, this appears to be a duplicate of #21637. Thanks for letting me know :slightly_smiling_face:

**Closed by Calinou** 2019-12-06 00:03 UTC
Labels: bug, topic:core
