### ISSUE TITLE
Long lines are stacked in Editor Output

### ISSUE THREAD

**Issue by gustavi** [godotengine/godot#55004] opened 2021-11-15 19:01 UTC
### Godot version

v4.0.dev.20211108.official.596865366

### System information

Windows 10 64bit - Vulkan API 1.2.141 - GeForce GTX 1660 SUPER

### Issue description

2 lines can be a bit stacked in Editor Output tab.

![image](https://user-images.githubusercontent.com/2736557/141838115-b8f2a689-a52d-40fa-8b9a-9b28dce34fa1.png)

https://user-images.githubusercontent.com/2736557/141838904-4ed430e6-91f4-4095-a083-c64bffc9dd36.mp4

Godot 4 only. Tested on Windows 10 only.

### Steps to reproduce

1. Print an object displayed on multiple lines (a `Dictionary` for example)
2. Print a normal line
3. Lines stack when you resize (vertically) the bottom tabs part of the Editor

Code used:

```gdscript
extends Control

func _ready():
    var a := {}
    var b := ""
    for i in range(40):
        a[i] = "abcdefghijklmnopqrstuvwxyz0123456789"
        b += "b"
    print(a)
    print(b)

```

### Minimal reproduction project

[bug-stdout.zip](https://github.com/godotengine/godot/files/7541038/bug-stdout.zip)

---

EDIT 2021-11-15 : typo

**Comment by Calinou** [comment] 2021-11-15 19:12
This is likely related to https://github.com/godotengine/godot/pull/41321. cc @EricEzaM

**Comment by EricEzaM** [comment] 2021-11-16 00:34
Hmm, maybe. Editor log just uses RichTextLabel directly though in a pretty no-frills way, so it might be related to some changes in there also.

**Comment by KoBeWi** [comment] 2022-05-20 17:34
Can no longer reproduce in alpha 8

**Comment by gustavi** [comment] 2022-05-21 12:14
Just tested with alpha8: the bug is still there.

![image](https://user-images.githubusercontent.com/2736557/169651041-8a1187b8-86ad-49bc-9380-8832d8e3771b.png)

**Comment by KoBeWi** [comment] 2022-05-21 13:26
Looks like I tested wrongly, thanks for checking >_>

**Comment by akien-mga** [comment] 2022-08-03 13:00
According to https://github.com/godotengine/godot/pull/61856#pullrequestreview-1060251737 this was fixed by the latest Font refactoring.

**Closed by akien-mga** 2022-08-03 13:00 UTC
Labels: bug, topic:editor, regression
