### ISSUE TITLE
MonoDevelop can't open new .csproj

### ISSUE THREAD

**Issue by Lachlan-uts** [godotengine/godot#41936] opened 2020-09-10 06:41 UTC
**Godot version:**

3.2.3.rc6

**OS/device including version:**

Linux, PopOS 20.04 LTS

**Issue description:** 

I've been having some strange VScode problems in godot v3.2.1 stable, trying to work with extra libraries, which I solved by using mono develop. Today, upon realising that a new RC was out I went to try it (after backing up my project). It seemed to fix the VScode issues, howoever now monodevelop now is unable to open any .csproj, related to godot, both new and upgraded versions.

The exact error is "load failed: unknown solution item type: {8f3E2DF0-C35C-4265-82FC-BEA011F4A7ED}"

I found references to the GUID in [this patch to add VS support](https://github.com/godotengine/godot/pull/39578/files) and in the [merge request](https://github.com/godotengine/godot/pull/41408/files) for the new .csproj format, so I think that the culprit lies somewhere in there. However my sleuthing ends there as I don't really know enough to do more research, so I decided to make this bug report.

**Steps to reproduce:**
1. open/make new mono godot project using Godot 3.2.3.rc6
2. open the .sln file in monodevelop (I'm running version 7.8.4)
3. see the error.

**Minimal reproduction project:**

[New-Proj-Issues.zip](https://github.com/godotengine/godot/files/5199578/New-Proj-Issues.zip)
*it's a pretty meaningless zip*

**Comment by akien-mga** [comment] 2020-09-10 08:32
I can reproduce the issue with a brand new install of MonoDevelop 7.8.4 on Mageia 8.

But installing the godot-monodevelop add-in seems to fix it: https://github.com/godotengine/godot-monodevelop-addin/releases/tag/v1.1
Can you confirm that you didn't have the add-in installed and that it works once installed?

So it seems like it's just a matter of documentation / usability issue?

**Comment by neikeq** [comment] 2020-09-10 13:16
You need the plugin to be able to open with MonoDevelop and Visual Studio. I wonder where this would best documented. Maybe some info in the Godot editor itself?

**Comment by Lachlan-uts** [comment] 2020-09-11 07:53
Gotcha, so now I feel like a bit of a silly duffer. :facepalm:  

Installing that plugin did fix things. The difference being at least as of godot version 3.2.1 the plugin wasn't needed to open the project in in monodevelop at all, though obviously you need the plug-in for stuff like debugging to work correctly (which incidentally does now :D).

So from my perspective all is good, so you can probably close this now. Do you have any control over the error MonoDevelop produces? If not I guess I'd suggest just adding a text either to the info on start or to the page where you select what external editor is launched? Picture attached.

![image](https://user-images.githubusercontent.com/31094273/92887006-80e45080-f457-11ea-99a6-90c7e9acfefd.png)

**Comment by rafaelgdp** [comment] 2020-09-20 21:09
I'm on MacOS Catalina. I was facing this very issue with the latest 3.2.3 stable version. I could not open the project on VSCode nor on VS. When I installed the aforementioned Addin on VS, it finally worked (but only on Visual Studio itself). I still cannot open it properly on VSCode. Is there a solution to open Godot's C# project in VSCode?? When I open the Godot C# project on VSCode an error pops up saying it could not open the project and the autocompletion for Godot-specific classes is not working. It's as if the Godot's assemblies could not be loaded properly. I only get autocompletion for things inside the C# System namespace. I think this means that VSCode can detect the C# core libraries, but not Godot-related C# stuff. How can I solve this?

**Comment by akien-mga** [comment] 2020-09-21 05:38
You should install the Viscose plugin for Godot C#: https://marketplace.visualstudio.com/items?itemName=neikeq.godot-csharp-vscode

**Comment by rafaelgdp** [comment] 2020-09-21 08:04
> You should install the VSCode plugin for Godot C#: https://marketplace.visualstudio.com/items?itemName=neikeq.godot-csharp-vscode

The thing is I have already installed all the C#-related plugins on VSCode. The error message says when loading is that I do not have the reference assemblies for .NETFramework,Version=v4.7.2. This version specifically is not available for MacOS. But the thing is I can open it on Visual Studio and I can run the project normally on Godot. Here are some screenshots.

<img width="1920" alt="Screen Shot 2020-09-21 at 04 58 34" src="https://user-images.githubusercontent.com/9672536/93744176-cc210080-fbc7-11ea-9287-614aa07557d3.png">
<img width="1919" alt="Screen Shot 2020-09-21 at 04 58 47" src="https://user-images.githubusercontent.com/9672536/93744195-d17e4b00-fbc7-11ea-8bfd-0be0342d9118.png">
<img width="1917" alt="Screen Shot 2020-09-21 at 05 02 36" src="https://user-images.githubusercontent.com/9672536/93744204-d5aa6880-fbc7-11ea-8089-9f4d0321807d.png">
<img width="1919" alt="Screen Shot 2020-09-21 at 05 02 55" src="https://user-images.githubusercontent.com/9672536/93744215-db07b300-fbc7-11ea-9419-5e66c2a84a1c.png">

**Comment by akien-mga** [comment] 2020-09-21 08:37
@rafaeldelboni That's an OmniSharp bug: https://github.com/OmniSharp/omnisharp-vscode/issues/3063#issuecomment-678223360

**Comment by rafaelgdp** [comment] 2020-09-21 09:47
> @rafaeldelboni That's an OmniSharp bug: [OmniSharp/omnisharp-vscode#3063 (comment)](https://github.com/OmniSharp/omnisharp-vscode/issues/3063#issuecomment-678223360)

Thank you so much, @akien-mga ! This comment (https://github.com/OmniSharp/omnisharp-vscode/issues/3063#issuecomment-678223360) in the issue you mentioned solved the problem for me!!! Thank you!!

**Comment by wizardlu** [comment] 2020-10-03 08:16
> You need the plugin to be able to open with MonoDevelop and Visual Studio. I wonder where this would best documented. Maybe some info in the Godot editor itself?

Back to the original issue, I had this issue with version 3.2.3.mono.stable and Visual Studio on macOS Mojave and the Godot-MonoDevelop add-in solved it.
If the add-in is required from now on, I suggest adding a comment when Monodevelop or Visual Studio are selected in the Editor Settings Dialog.

**Comment by neikeq** [comment] 2020-10-03 08:56
We're likely to remove the project type guid in the Godot version, so the add-in won't be required anymore.

**Comment by satscape** [comment] 2020-10-07 10:30
Thank you for the link to the monodevelop plugin, I can finally get rid of VScode. For the past 3 mornings I'm greeted with this nonsense:
![2020-10-07-110732_1360x768_scrot](https://user-images.githubusercontent.com/248052/95319280-98b0c800-088f-11eb-973c-2623de2d4b79.png)
(I have all the relavent VScode plugins install, as I was developing with Unity, which I will be also uninstalling, Godot rocks!)

A hour of me mucking about with various settings finally gets it working. MonoDevelop installed, add plugin and everything works just fine. Thank you Godot devs, keep up the good work!

**Comment by jonhcassey** [comment] 2020-10-07 13:08
Thank you for the tip, plugin solved it for me in monodevelop, vscode isn't working even with the godot plugging for it, file opens and edits, saving and compiling all working fine but without auto completion is taping the dark, as much as i like vscode, for high level languages it has been more trouble than worth it.

**Comment by sericaer** [comment] 2020-12-14 10:21
I also have same problem, And when I install MonoDevelop-GodotAddin_1.1.mpack, it report " required MonoDevelop.core, 7.8.4, found:MonoDevelop.core,8.8.3",
could you make a new MonoDevelop-GodotAddin version, which support Mono 8.8.3?
Thanks a lot!

**Comment by neikeq** [comment] 2020-12-14 12:23
@sericaer Where did you get MonoDevelop 8.8.3 from? MonoDevelop never got a 8.x release and the open source repo has been inactive for quite some time unfortunately.
If it's Visual Studio for Mac then try the other mpack (it should be available from the addins repository as well).

**Comment by sericaer** [comment] 2020-12-15 01:39
@neikeq Thanks for you help! The problem is sovled after I install VisualStudioMac-GodotAddin_1.1.mpack.

**Comment by akien-mga** [comment] 2021-01-06 10:30
Closing as installing the latest addin seems to solve the issue at least for some users.

If you still experience issue using any supported IDE with Godot 3.2.3 or later, I would suggest opening an issue on the repository for the relevant IDE's addin so that it can be debugged further there.

**Closed by akien-mga** 2021-01-06 10:30 UTC
Labels: bug, regression, topic:mono
