### ISSUE TITLE
SSR shows through volumetric fog

### ISSUE THREAD

**Issue by QbieShay** [godotengine/godot#71392] opened 2023-01-14 12:42 UTC
### Godot version

Godot 4 beta 14

### System information

Windows 10

### Issue description

Enabling SSR and volumetric fog makes SSR show through fog

![image](https://user-images.githubusercontent.com/7917475/212472028-2b561bcf-cec7-494b-a41b-0f35672f6538.png)

### Steps to reproduce

Download MRP, open scene, rotate the camera until the fog is between the camera and the cube (like attached screenshot)

### Minimal reproduction project

[SSRFOG.zip](https://github.com/godotengine/godot/files/10417322/SSRFOG.zip)

**Comment by Calinou** [comment] 2023-01-15 19:45
Duplicate of https://github.com/godotengine/godot/issues/66934.

**Closed by Calinou** 2023-01-15 19:45 UTC
Labels: bug, topic:rendering

**Comment by QbieShay** [comment] 2023-01-20 20:04
I don't think it's a duplicate? the other issue says SSR reflects "too much" in volumetric fog, but the issue here is different: it's drawn on top.

**Comment by clayjohn** [comment] 2023-01-20 20:08
> I don't think it's a duplicate? the other issue says SSR reflects "too much" in volumetric fog, but the issue here is different: it's drawn on top.

Its the same issue. The user just didn't realize that it was drawing over top

**Comment by QbieShay** [comment] 2023-01-20 20:11
oh ok. i thought it was a regression,
