### ISSUE TITLE
Proximity fade does not work

### ISSUE THREAD

**Issue by CCODE05B** [godotengine/godot#25870] opened 2019-02-14 11:37 UTC
**Godot version:**
Godot 3.1 Beta 4

**OS/device including version:**
Windows 7 x64 , GTX 980 , 8GB Ram , i7 4970K

**Issue description:**
Proximity fade does not work 

**Steps to reproduce:**
Create 2 Meshes and make them close to each other , add spatial material to one of them  , Enable Proximity fade and see

**Comment by CCODE05B** [comment] 2019-02-14 13:02
why you guys Ignoring this issue ?

**Comment by akien-mga** [comment] 2019-02-14 13:15
> why you guys Ignoring this issue ?

Please be patient, we're all doing our best. Nobody is ignoring this issue, but triaging issues takes time.

**Comment by CCODE05B** [comment] 2019-02-14 13:26
@akien-mga i was just asking , because i keep always testing Godot and try to find issues .. and i found this one , i searched GitHub and i found it : https://github.com/godotengine/godot/issues/25387 
but you ignored it , i was thinking maybe you just missed it and you didn't see it , so i post it again here.
but what see is any new issue get labels and get notice , but this : https://github.com/godotengine/godot/issues/25387 or the Current one
this is what made me ask the question

**Comment by groud** [comment] 2019-02-14 13:55
Please, there are 4100 issues opened, with 245 issues without labels. So you are not the only one... : https://github.com/godotengine/godot/issues?q=is%3Aopen+is%3Aissue+no%3Alabel. We are doing our best to keep up the labeling work.

But also, sometimes we are not sure about what the issue is about. To help us, you can provide screenshots or videos, and a reproduction project (as asked on the issue template). 

So when you create a 2 lines long issue, with an issue description such as "blablabla does not work", it is unlikely it will get a pertinent label assigned fast.

**Comment by Calinou** [comment] 2019-02-14 14:14
I can't reproduce this on https://github.com/godotengine/godot/commit/325efb60b7b4f7cb4ed11097c8f2e2de973e00d0 (Linux, GTX 1080 with the NVIDIA 415.27 driver)

![image](https://user-images.githubusercontent.com/180032/52792165-fe24c500-306a-11e9-8355-51675e2fe417.png)

Reproduction project: [test_proximity_fade.zip](https://github.com/godotengine/godot/files/2865328/test_proximity_fade.zip)

**Comment by volzhs** [comment] 2019-02-14 14:20
and I've seen some issues are solved while they were making a sample project to reproduce.

**Comment by clayjohn** [comment] 2019-02-14 15:42
This is solved already in master PR #25557. It barely missed inclusion in beta 4

**Comment by groud** [comment] 2019-02-14 15:45
OK, closing as already fixed on master then. @CCODE05B if you try again with latest master and it still does not work, please comment here.

**Closed by groud** 2019-02-14 15:45 UTC
Labels: bug, topic:rendering

**Comment by dannyangmy** [comment] 2019-08-19 23:08
I had tested an Android export of Calinou's reproduction project.
I'm on Godot 3.1.1 stable.
Object with proximity fade is not visible when exporting with GLES3 to Android.
GLES2 export works fine and so does Windows export.
Is this a known issue or am I missing something here?

**Comment by Calinou** [comment] 2019-08-19 23:25
@dannyangmy Does it work if you uncheck **Rendering > Quality > Shading > Force Vertex Shading.mobile** in the Project Settings? I believe proximity fade requires per-pixel shading to be used.

**Comment by dannyangmy** [comment] 2019-08-19 23:51
I was testing it on a Samsung Note 4, Snapdragon, so the GPU would be an Adreno 420.
Let me test it on a few other Android devices and get back to you.

There are a few features that I would like to use that's only available on GLES3, plus from my googling the consensus seems to be that GLES2 is generally better for 2D games and not necessarily 3D games (I might be wrong).

**Comment by dannyangmy** [comment] 2019-08-20 22:54
I've tested it on a few other devices; a Xiaomi Mi A2 (Adreno 512), a Xiaomi Mi 9T (Adreno 618), and a Samsung Galaxy Note 5 (Mali-T760 MP8).

None of them worked.
