### ISSUE TITLE
Cannot access _get_child_nodes() in AnimationNodeBlendTree

### ISSUE THREAD

**Issue by stryker313** [godotengine/godot#62340] opened 2022-06-23 09:51 UTC
### Godot version

4.0 Alpha 9

### System information

Windows 10 i5 4690k gtx 1060

### Issue description

Trying to access (tree_root._get_child_nodes()), or any other underscore method in the class AnimationNode will through an error.

In my example, trying to get the children of the animationNodeBlendTree will return "nonexistent function"

AnimationNodeBlendTree inherits from AnimationNode, thus should contain the function?

### Steps to reproduce

Try to call _get_child_nodes() in AnimationNodeBlendTree

### Minimal reproduction project

[BrokenAnimationTree.zip](https://github.com/godotengine/godot/files/8966108/BrokenAnimationTree.zip)

**Comment by Calinou** [comment] 2022-06-24 16:20
Duplicate of https://github.com/godotengine/godot/issues/62379 (same cause).

**Closed by Calinou** 2022-06-24 16:20 UTC
Labels: documentation, topic:animation
