### ISSUE TITLE
Some Authors are misplaced in Help -> About

### ISSUE THREAD

**Issue by dragmz** [godotengine/godot#36195] opened 2020-02-13 21:19 UTC
4.0 17791363369eec42d097b426fc7aa4359e40fae8

1. Create a new Vulkan project and switch to Script in the editor
2. Open Help -> About
3. Scroll down to see some Authors misplaced

![image](https://user-images.githubusercontent.com/447143/74479071-dac76c80-4eae-11ea-8f2a-94c6fdff5b95.png)

**Comment by akien-mga** [comment] 2020-02-13 21:40
Duplicate of #36164.

**Closed by akien-mga** 2020-02-13 21:40 UTC
