### ISSUE TITLE
Executing preview in editor sometimes fails and open project manager.

### ISSUE THREAD

**Issue by Ranoller** [godotengine/godot#13441] opened 2017-12-01 09:22 UTC
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Godot 3 beta 1 - Win7 32 bit

**Issue description:**

Clicking in game preview sometimes fails and godot open project manager window.
Failure is intermittent, it happend few times.
When it happends in my system this is the console output:

running cmdline: "D:\Varios\Godot 3 beta1\Godot_v3.0-beta1_win32.exe" "--path" "D:/Varios/DATOS/bunnymark-tests-master/godot3" "--remote-debug" "127.0.0.1:6007" "--allow_focus_steal_pid" "6604" "--position" "128,212"
 core\io\image_loader.cpp:54 - Error opening file: res://bunny.scn::1
** Debug Process Started **
OpenGL ES 3.0 Renderer: Intel(R) HD Graphics 4600
GLES3: max ubo light: 102
GLES3: max ubo reflections: 113, ubo size: 144
ARVR: Registered interface: Native mobile

There are invalid textures in the project, but this is not problem to execute the preview most of the times. 

**Steps to reproduce:**
Click preview.

**Link to minimal example project:**

Execute project in #13443

**Comment by akien-mga** [comment] 2017-12-01 11:34
Thanks for the report. That's a duplicate of #11391.

**Closed by akien-mga** 2017-12-01 11:34 UTC
