### ISSUE TITLE
Nodes that already have children added in C++ being exposed to GDScript

### ISSUE THREAD

**Issue by williamd1k0** [godotengine/godot#12836] opened 2017-11-11 09:48 UTC
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Windows 10
Godot 2.1.4 and 3.0 alpha 2

**Issue description:**

I really don't know if it's by design but it seems like it's a hidden bug.
For some reason, if you use a node that already has some children created in C++, the children are being exposed to gdscript and remote inspector.
That looks strange because the children are "hidden".

**Steps to reproduce:**
Using the `LineEdit` node as an example:
In `line_edit.cpp`, it has 2 children, a Timer and a PopupMenu.
If you run the scene these nodes appear on the remote inspector.

![image](https://user-images.githubusercontent.com/10428035/32688118-1e598172-c6b2-11e7-8c6e-71176097fcd0.png)

If you try a simple `get_children` in this node the children also appear.

![image](https://user-images.githubusercontent.com/10428035/32688132-6e260e78-c6b2-11e7-8251-008eed184de8.png)

Also, if you add a Timer or a PopupMenu in a LineEdit, the name has a number if it was a repeated name.

![image](https://user-images.githubusercontent.com/10428035/32688229-383a3de6-c6b4-11e7-91af-4d563086068c.png)

**Link to minimal example project:**

**Comment by Zylann** [comment] 2017-11-11 14:29
I never thought of this as a bug. If these internal nodes would be exposed, deleting or altering them by mistake could cause trouble.

**Comment by CowThing** [comment] 2017-11-11 17:49
For a while I didn't realize some nodes created their own child nodes, until one time I was trying to modify all the children of a node but it kept messing up since a few of those child nodes were ones that I didn't create myself.

Maybe those created nodes should be shown in the editor but be marked in a way that they can't be moved or modified. They can have some note explaining that these nodes are added by the parent node, and aren't able to be modified.

**Comment by bojidar-bg** [comment] 2017-11-16 16:03
Duplicate of #7142, though with a different node.

**Closed by bojidar-bg** 2017-11-16 16:03 UTC
Labels: bug, confirmed, topic:core
