### ISSUE TITLE
HTML5 Exports have the WASM file greater then 25mb. This blocks the usage of CloudFlare Pages and GitHub.

### ISSUE THREAD

**Issue by PeterMarques** [godotengine/godot#70672] opened 2022-12-28 14:56 UTC
### Godot version

4.0 beta

### System information

Browser

### Issue description

I know of some sort of hack that compress the wasm file, that was used 5 years ago, but the discussion seen to indicate the method is not the greatest, and is broken on newers versions, so i assume on godot4 it will not work either.

But, i see that the Extensions version of the export, generate TWO wasm files, so, maybe it is feasible to split the engine into smaler files?

Having the HTML5 version to be acepted on several serverless hosting platforms is a must i believe, and even that Godot itself is not reponsible in having that to work (the 25Mb limit of upload), but trying to achieve that compliance can mantain the spread usage of the engine.

And even beyond that, having the option to split the PCK file as well would be very fruitful. 
There was instances when i manualy had to export the dependencies in packages and import then on the fly to workarroud.

I am using the version 3 on CloudFlare, and i cant use the version 4 because of that.

Any insights?

### Steps to reproduce

Export html5 project on godot4

### Minimal reproduction project

N/A

**Comment by Zireael07** [comment] 2022-12-28 16:11
duplicate of #68647

**Comment by PeterMarques** [comment] 2022-12-28 19:02
Okay... But, what about the solution of spliting the binary?
In godot 4 there is the option of selection parts of the engine to be exported with the project, and that does not seens to be working, because the binary size does not change, even if i only let barebone engine selected.

Maybe it is another bug, because it would be a temp fix to complying to size.

And the option to split the WASM bin into several files? Is that feasible, right?

**Comment by Zireael07** [comment] 2022-12-29 09:39
Yes, I would like to see the possibility to split the binary, too.

If the export parts doesn't affect the WASM size, that's a bummer, I've been hoping to use that to trim my WASM exports down

**Comment by Calinou** [comment] 2022-12-29 19:42
Duplicate of https://github.com/godotengine/godot/issues/68647.

**Closed by Calinou** 2022-12-29 19:42 UTC
