### ISSUE TITLE
[4.3 beta 1] Global Shader Uniforms of Type Sampler2D are not saved

### ISSUE THREAD

**Issue by DasCapschen** [godotengine/godot#93164] opened 2024-06-14 14:48 UTC
### Tested versions

v4.3.beta1.official [a4f2ea91a]

### System information

Godot v4.3.beta1 - openSUSE Tumbleweed 20240610 - Wayland - Vulkan (Forward+) - dedicated AMD Radeon RX 580 Series (RADV POLARIS10) () - Intel(R) Core(TM) i7-3770K CPU @ 3.50GHz (8 Threads)

### Issue description

After setting a global Shader Uniform of type Sampler2D, you can see it affect shaders in the editor. Starting the game, the shader uniform stops having an effect. Restarting the engine clears the uniform in the "Global Shader Uniforms" tab in the project settings.   

It seems that this is a regression of #60805

### Steps to reproduce

1. add a shader global of type sampler2d
2. give it a texture
3. save & restart the editor
4. check the shader globals tab
5. your sampler2d global is unset :(

### Minimal reproduction project (MRP)

na

**Comment by matheusmdx** [comment] 2024-06-14 23:41
This is a duplicate of #92178. Also the link in issue description is another issue so i assume the author means the pr that fixed this issue is the cause of this regression, but i tested the pr, reverted and both cases this bug continues. I also tested alpha 1, 10 and 15 and all of them is broken too so that looks a thing that was broken from the start

**Closed** 2024-06-15 08:17 UTC
Labels: bug, needs testing, regression, topic:shaders
