### ISSUE TITLE
Godot becomes completely unresponsive

### ISSUE THREAD

**Issue by unclearimage86** [godotengine/godot#34037] opened 2019-12-01 02:47 UTC
**Godot version:**
Godot 3.1.2 (And all other versions)
**OS/device including version:**
Microsoft Windows 10 Home (10.0.18363 Build 18363)
**Issue description:**
Basic app with just a panel, a label, a button, and a script increases in lag until it takes 45-60 seconds to run the app. Godot takes longer and longer to start.
**Steps to reproduce:**
Download Godot (or build with scons, Mingw, msvs, scoop)
Make a 2d app (Gui node) 
Add Panel, Button, Label
Add Script (GDScript)
Run application and Godot becomes more and more unresponsive
**Minimal reproduction project:**
https://drive.google.com/open?id=169Z3jrZw604LiifyDo-RDp2eQINghFUi

NVIDIA GeForce GTX 1060 3GB - Driver 26.21.14.4120
output from System Information - https://pastebin.com/q8z8zt7J 

I removed my USB hub I had before (it didn't help) and have tried every fix I could find online for Godot. I've come to the conclusion ,for whatever reason, Godot simply cannot be used on my Computer. However when I had linux mint installed on my pc Godot ran perfectly fine, and was very fast.

**Comment by girng** [comment] 2019-12-01 07:55
I tried 3.1.2 but can't reproduce this. I'm on Windows 10 as well.
Something else is going on, faulty driver perhaps?

**Comment by unclearimage86** [comment] 2019-12-01 10:00
> 
> 
> I tried with 3.1.2 but can't reproduce this. I'm on Windows 10 as well.
> Something else is going on, faulty driver perhaps? Is 26.21 the most recent one?

There's one that's a bit newer, but I've tried all kinds of driver versions (have reformatted this pc a few times, unrelated to Godot)

Also some new information, I downloaded Godot through itch.io; if I run my app and click the "X" in the top right of the app I get:

Loading resource: res://main.tscn
Loading resource: res://main.gd
Loading resource: res://Entity.gd
ERROR: ~List: Condition ' _first != __null ' is true.
   At: ./core/self_list.h:111
ERROR: ~List: Condition ' _first != __null ' is true.
   At: ./core/self_list.h:111
WARNING: cleanup: ObjectDB Instances still exist!
     At: core/object.cpp:2087

But if I hit the (STOP) key on the top right of godot (the debug actions) there is no ObjectDB instances still exist

**Comment by unclearimage86** [comment] 2019-12-01 11:11
UPDATE: Have found a workaround of sorts- If my scene is

-Control
    -Panel
         -Label
         -Button

and I attach a script to "Control" (the topmost node) it bugs out like this, but if I attach it to the node just under the topmost node (i.e. "Panel") I don't have issues of resources not being unloaded or bugging out.

**Comment by unclearimage86** [comment] 2019-12-01 11:23
I found a temporary work-around. I put this program in compatibility mode for Windows 8, now no more memory leaks when closing the app. Also I moved my script from the topmost node down to the first child node. 

Also attached 

i.e.
Node                       <----- Script was here at the topmost level
----Panel                 <----- Moved the script down here, so it can unload? I don't know but it works
--------Button
--------Label

**Comment by Calinou** [comment] 2020-07-19 19:53
@unclearimage86  Can you (or anyone else) still reproduce this bug in Godot 3.2.2 or any later release?

If yes, please ensure that an up-to-date Minimal Reproduction Project (MRP) is included in this report (a MRP is a zipped Godot project with the minimal elements necessary to reliably trigger the bug). You can upload ZIP files in an issue comment with a drag and drop.

**Comment by akien-mga** [comment] 2021-04-28 13:17
No answer, so closing. Please comment if you can still reproduce the issue in Godot 3.3 or later.

**Closed by akien-mga** 2021-04-28 13:17 UTC
Labels: bug, topic:editor
