### ISSUE TITLE
ItemList:  Item List Editor disappears under certain circumstances

### ISSUE THREAD

**Issue by nobuyukinyuu** [godotengine/godot#30636] opened 2019-07-16 23:19 UTC
**Godot version:**
3.1.1 stable

**Issue description:**

It appears that ItemList functionality has broken with the new inspector.  Unlike `OptionButton`, one can't "focus" on an item inside the actual ItemList and modify values outside of its special list editor.  When attempting to create a new, internal resource for an icon, the inspector enters an inconsistent state which appears to be "normal" (focused on the ItemList), but is now pulling up the resource handling context of the newly created resource (ie:  `EditorPlugin`s will believe it's handling an image resource when the ItemList is in focus, and the editor bottom bar will show the TextureRegion tab if the resource is an `AtlasTexture`).  This makes the Item List editor for the ItemList no longer accessible from the editor.

**Steps to reproduce:**
1.  Create an ItemList.
2.  Open the Item List editor and add an item.
3.  Change the `icon` property to a new texture (AtlasTexture recommended, to see the handling effect directly without an EditorPlugin)
4.  Notice the "Items" option in the top menu is gone and the list editor no longer functions.

**Comment by nobuyukinyuu** [comment] 2020-02-02 00:01
Hello,

This issue still persists in version 3.2 and can be replicated using the same method.

**Comment by KoBeWi** [comment] 2020-12-25 19:38
Duplicate of #28211

**Closed by KoBeWi** 2020-12-25 19:38 UTC
Labels: bug, topic:editor
