### ISSUE TITLE
Beta 17 crashed with signal 11 if ParallaxBackground above Camera2D

### ISSUE THREAD

**Issue by Variable-ind** [godotengine/godot#72752] opened 2023-02-05 11:04 UTC
### Godot version

Godot 4.0 beta 17

### System information

Linux Mint 21.1 Cinnamon, Graphics: Intel Corporation HD Graphics 620, Processor: Intel© Core™ i5-7200U CPU @ 2.50GHz × 2

### Note: This bug does not appear in beta 16
Program crashes with signal 11 when we attempt anything that effects the current scene (e.g, changing project, rearranging children etc)

The condition for this crash is when the ParallaxBackground node is above the Camera2d node

https://user-images.githubusercontent.com/77773850/216814780-4f898ad7-19c0-43b5-8611-94d897f317ce.mp4

The terminal text is:

```
Godot Engine v4.0.beta17.official.c40020513 - https://godotengine.org
OpenGL Renderer: Mesa Intel(R) HD Graphics 620 (KBL GT2)
 
Scanning projects at: /home/variable/Documents/Godot/Godot projects

Editing project: /home/variable/Documents/Godot/Godot projects/Seg fault Project
Godot Engine v4.0.beta17.official.c40020513 - https://godotengine.org
OpenGL Renderer: Mesa Intel(R) HD Graphics 620 (KBL GT2)
```

the Backtrace is
```
handle_crash: Program crashed with signal 11
Engine version: Godot Engine v4.0.beta17.official (c40020513ac8201a449b5ae2eeb58fef0ce0a2a4)
Dumping the backtrace. Please include this when reporting the bug to the project developer.
[1] /lib/x86_64-linux-gnu/libc.so.6(+0x42520) [0x7f2bcc76a520] (??:0)
[2] /home/variable/Softwares/Godot Engine/Godot_v4.0-beta17_linux.x86_64() [0x30d6515] (??:0)
[3] /home/variable/Softwares/Godot Engine/Godot_v4.0-beta17_linux.x86_64() [0x30d6708] (??:0)
[4] /home/variable/Softwares/Godot Engine/Godot_v4.0-beta17_linux.x86_64() [0x30d7389] (??:0)
[5] /home/variable/Softwares/Godot Engine/Godot_v4.0-beta17_linux.x86_64() [0x44ef5c4] (??:0)
[6] /home/variable/Softwares/Godot Engine/Godot_v4.0-beta17_linux.x86_64() [0x2b00a35] (??:0)
[7] /home/variable/Softwares/Godot Engine/Godot_v4.0-beta17_linux.x86_64() [0x2b00907] (??:0)
[8] /home/variable/Softwares/Godot Engine/Godot_v4.0-beta17_linux.x86_64() [0x2b016e3] (??:0)
[9] /home/variable/Softwares/Godot Engine/Godot_v4.0-beta17_linux.x86_64() [0x2b02c54] (??:0)
[10] /home/variable/Softwares/Godot Engine/Godot_v4.0-beta17_linux.x86_64() [0x1cb734d] (??:0)
[11] /home/variable/Softwares/Godot Engine/Godot_v4.0-beta17_linux.x86_64() [0x1cb8a7b] (??:0)
[12] /home/variable/Softwares/Godot Engine/Godot_v4.0-beta17_linux.x86_64() [0x4363ad2] (??:0)
[13] /home/variable/Softwares/Godot Engine/Godot_v4.0-beta17_linux.x86_64() [0x455dd2a] (??:0)
[14] /home/variable/Softwares/Godot Engine/Godot_v4.0-beta17_linux.x86_64() [0x2be9729] (??:0)
[15] /home/variable/Softwares/Godot Engine/Godot_v4.0-beta17_linux.x86_64() [0x2bea18b] (??:0)
[16] /home/variable/Softwares/Godot Engine/Godot_v4.0-beta17_linux.x86_64() [0x2b44965] (??:0)
[17] /home/variable/Softwares/Godot Engine/Godot_v4.0-beta17_linux.x86_64() [0x2b8dfc5] (??:0)
[18] /home/variable/Softwares/Godot Engine/Godot_v4.0-beta17_linux.x86_64() [0x2b91f71] (??:0)
[19] /home/variable/Softwares/Godot Engine/Godot_v4.0-beta17_linux.x86_64() [0x2bc51ab] (??:0)
[20] /home/variable/Softwares/Godot Engine/Godot_v4.0-beta17_linux.x86_64() [0x2bc22a5] (??:0)
[21] /home/variable/Softwares/Godot Engine/Godot_v4.0-beta17_linux.x86_64() [0xe74fc4] (??:0)
[22] /home/variable/Softwares/Godot Engine/Godot_v4.0-beta17_linux.x86_64() [0x42f15a4] (??:0)
[23] /home/variable/Softwares/Godot Engine/Godot_v4.0-beta17_linux.x86_64() [0x42f26a5] (??:0)
[24] /home/variable/Softwares/Godot Engine/Godot_v4.0-beta17_linux.x86_64() [0xe769dd] (??:0)
[25] /home/variable/Softwares/Godot Engine/Godot_v4.0-beta17_linux.x86_64() [0xde8ec2] (??:0)
[26] /lib/x86_64-linux-gnu/libc.so.6(+0x29d90) [0x7f2bcc751d90] (??:0)
[27] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0x80) [0x7f2bcc751e40] (??:0)
[28] /home/variable/Softwares/Godot Engine/Godot_v4.0-beta17_linux.x86_64() [0xe0908e] (??:0)
-- END OF BACKTRACE --
```

### Steps to reproduce

![Screenshot from 2023-02-05 15-41-45](https://user-images.githubusercontent.com/77773850/216814378-c734a33a-7022-4717-b499-03cc9d0c5d0a.png)

### Minimal reproduction project
[Seg fault.zip](https://github.com/godotengine/godot/files/10610776/Seg.fault.zip)

**Comment by KoBeWi** [comment] 2023-02-05 11:14
Duplicate of #72610

**Closed by KoBeWi** 2023-02-05 11:14 UTC
