### ISSUE TITLE
[Godot 4] Arrays and Dictionaries export as nil.

### ISSUE THREAD

**Issue by Nyksia** [godotengine/godot#52422] opened 2021-09-05 17:47 UTC
### Godot version

4.0.dev.calinou (18c0f0b3b)

### System information

Windows 10

### Issue description

When exported in a script, Arrays and Dictionaries are nil, no matter what value they have during the variable export.
Edit: To clarify, the values are assigned properly to Node and/or Resource and can be accessed, but in Editor they are shown as Nil Arrays and Dictionaries.
![image](https://user-images.githubusercontent.com/56171005/132136390-aca26b10-f9c9-4844-8107-ff4fa8e695f2.png)

### Steps to reproduce

1. Launch a 4.0 dev build.
2. Create new script extending Node or Resource.
3. Attempt to export an Array or Dictionary with predetermined values.
4. Check the variables with Arrays or Dictionaries in Node's or Resource's properties.

### Minimal reproduction project

[Test Project.zip](https://github.com/godotengine/godot/files/7112077/Test.Project.zip)

**Comment by elvisish** [comment] 2022-10-17 22:14
Is it still not possible to export dictionaries in 4.0 beta 3?

**Comment by Calinou** [comment] 2022-10-17 22:38
Duplicate of https://github.com/godotengine/godot/issues/62753.

**Closed by Calinou** 2022-10-17 22:38 UTC
Labels: bug, topic:gdscript, topic:editor, confirmed
