### ISSUE TITLE
Animation Player + Blend Shapes bug

### ISSUE THREAD

**Issue by nonunknown** [godotengine/godot#34658] opened 2019-12-28 21:28 UTC
**Godot version:**
3.2 beta 4 
**OS/device including version:**
ubuntu 18.04
**Issue description:**
I Have 2 object crates (bounce crate) they are a box animated using shape keys, but when in the test scene the animation sometimes doesnt play , sometimes they play , and sometimes they play at the same time being different objects 
**Steps to reproduce:** and **Minimal reproduction project:**
download source files and play Lab.tscn and look for the bounce crate
https://github.com/nonunknown/crashcreator/tree/alpha

**Comment by KoBeWi** [comment] 2020-11-27 20:17
Can anyone still reproduce this bug in Godot 3.2.3 or any later release?

**Comment by MJacred** [comment] 2022-07-19 22:12
related to / duplicate of https://github.com/godotengine/godot/issues/38443?

**Comment by KoBeWi** [comment] 2022-07-21 21:40
Well my question didn't get any reply, so closing this anyway.

**Closed by KoBeWi** 2022-07-21 21:40 UTC
Labels: bug, topic:core
