### ISSUE TITLE
Editor crash when changing scene in GLES 2

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#25569] opened 2019-02-02 14:23 UTC
**Godot version:**
3.1 463123a

**OS/device including version:**
Ubuntu 18.04 Nvidia 970 415.27

**Issue description:**
When I changed scene I got this backtrace:
```
[1] /lib/x86_64-linux-gnu/libc.so.6(+0x3ef20) [0x7feb5fb81f20] (??:0)
[2] /usr/lib/x86_64-linux-gnu/libnvidia-glcore.so.415.27(+0xeb7dd0) [0x7feb5a2e9dd0] (??:0)
[3] /usr/lib/x86_64-linux-gnu/libnvidia-glcore.so.415.27(+0xf8abf3) [0x7feb5a3bcbf3] (??:0)
[4] /usr/lib/x86_64-linux-gnu/libnvidia-glcore.so.415.27(+0xf906b5) [0x7feb5a3c26b5] (??:0)
[5] /usr/lib/x86_64-linux-gnu/libnvidia-glcore.so.415.27(+0xf9ad53) [0x7feb5a3ccd53] (??:0)
[6] /usr/lib/x86_64-linux-gnu/libnvidia-glcore.so.415.27(+0xb3808b) [0x7feb59f6a08b] (??:0)
[7] RasterizerCanvasGLES2::_draw_polygon(int const*, int, int, Vector2 const*, Vector2 const*, Color const*, bool, float const*, int const*) (/home/rafal/Pulpit/godot/drivers/gles2/rasterizer_canvas_gles2.cpp:327)
[8] RasterizerCanvasGLES2::_canvas_item_render_commands(RasterizerCanvas::Item*, RasterizerCanvas::Item*, bool&, RasterizerStorageGLES2::Material*) (/home/rafal/Pulpit/godot/drivers/gles2/rasterizer_canvas_gles2.cpp:877)
[9] RasterizerCanvasGLES2::canvas_render_items(RasterizerCanvas::Item*, int, Color const&, RasterizerCanvas::Light*, Transform2D const&) (/home/rafal/Pulpit/godot/drivers/gles2/rasterizer_canvas_gles2.cpp:1483)
[10] VisualServerCanvas::render_canvas(VisualServerCanvas::Canvas*, Transform2D const&, RasterizerCanvas::Light*, RasterizerCanvas::Light*, Rect2 const&) (/home/rafal/Pulpit/godot/servers/visual/visual_server_canvas.cpp:264)
[11] VisualServerViewport::_draw_viewport(VisualServerViewport::Viewport*, ARVRInterface::Eyes) (/home/rafal/Pulpit/godot/servers/visual/visual_server_viewport.cpp:210)
[12] VisualServerViewport::draw_viewports() (/home/rafal/Pulpit/godot/servers/visual/visual_server_viewport.cpp:308)
[13] VisualServerRaster::draw(bool, double) (/home/rafal/Pulpit/godot/servers/visual/visual_server_raster.cpp:107 (discriminator 2))
[14] VisualServerWrapMT::draw(bool, double) (/home/rafal/Pulpit/godot/servers/visual/visual_server_wrap_mt.cpp:104)
[15] Main::iteration() (/home/rafal/Pulpit/godot/main/main.cpp:1886)
[16] OS_X11::run() (/home/rafal/Pulpit/godot/platform/x11/os_x11.cpp:2975)
[17] /usr/bin/godot(main+0xdc) [0x1156893] (/home/rafal/Pulpit/godot/platform/x11/godot_x11.cpp:56)
[18] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xe7) [0x7feb5fb64b97] (??:0)
[19] /usr/bin/godot(_start+0x2a) [0x11566fa] (??:?)
```

**Steps to reproduce:**
1. Open TPS Demo
2. search ".tscn"
3. open each tscn scene

**Comment by QbieShay** [comment] 2019-02-03 18:14
@groud I think this is rendering, it's crashing in the Nvidia driver.

**Comment by qarmin** [comment] 2019-02-04 07:38
I have this backtrace in Windows 10 Intel HD 530:
```
[0] RegisterProcTableCallback
[1] RegisterProcTableCallback
[2] RegisterProcTableCallback
[3] RegisterProcTableCallback
[4] RegisterProcTableCallback
[5] RegisterProcTableCallback
[6] RegisterProcTableCallback
[7] RegisterProcTableCallback
[8] RegisterProcTableCallback
[9] RegisterProcTableCallback
[10] RasterizerCanvasGLES2::_draw_polygon (c:\pr\godot\drivers\gles2\rasterizer_canvas_gles2.cpp:328)
[11] RasterizerCanvasGLES2::_canvas_item_render_commands (c:\pr\godot\drivers\gles2\rasterizer_canvas_gles2.cpp:878)
[12] RasterizerCanvasGLES2::canvas_render_items (c:\pr\godot\drivers\gles2\rasterizer_canvas_gles2.cpp:1483)
[13] VisualServerCanvas::render_canvas (c:\pr\godot\servers\visual\visual_server_canvas.cpp:265)
[14] VisualServerViewport::_draw_viewport (c:\pr\godot\servers\visual\visual_server_viewport.cpp:210)
[15] VisualServerViewport::draw_viewports (c:\pr\godot\servers\visual\visual_server_viewport.cpp:308)
[16] VisualServerRaster::draw (c:\pr\godot\servers\visual\visual_server_raster.cpp:107)
[17] VisualServerWrapMT::draw (c:\pr\godot\servers\visual\visual_server_wrap_mt.cpp:104)
[18] Main::iteration (c:\pr\godot\main\main.cpp:1886)
[19] OS_Windows::run (c:\pr\godot\platform\windows\os_windows.cpp:2785)
[20] widechar_main (c:\pr\godot\platform\windows\godot_win.cpp:150)
[21] _main (c:\pr\godot\platform\windows\godot_win.cpp:172)
[22] main (c:\pr\godot\platform\windows\godot_win.cpp:184)
[23] __scrt_common_main_seh (d:\agent\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288)
[24] BaseThreadInitThunk
```

**Comment by akien-mga** [comment] 2019-02-28 11:20
I could reproduce it in the current master branch (a4b687bd) on Mageia 7 x86_64 with Nvidia GTX 670MX.
At least I could a crash with the steps in the OP, opening all .tscn files *at once*, after having already opened a few scenes including .dae ones. And I had the game running in parallel.

I don't have the backtrace anymore as the game instance flooded my terminal with these errors:
```
ERROR: slide: Condition ' !p_normal.is_normalized() ' is true. returned: Vector3()
   At: ./core/math/vector3.h:433.
```

**Comment by reduz** [comment] 2019-03-03 21:11
I can't reproduce this, maybe whatever was causing the crash is now fixed?

**Comment by akien-mga** [comment] 2019-03-04 10:28
Also couldn't reproduce it today with 3 attempts at stress testing the TPS demo, so I'll assume it's fixed. Please comment if you can still reproduce it.

**Closed by akien-mga** 2019-03-04 10:28 UTC
Labels: bug, topic:editor, topic:rendering
