### ISSUE TITLE
Multiple fields highlighted when tabbing between them

### ISSUE THREAD

**Issue by andersmmg** [godotengine/godot#57880] opened 2022-02-09 21:57 UTC
### Godot version

4.0.alpha2

### System information

Manjaro Linux

### Issue description

When tabbing between properties, the previous one stays highlighted. It doesn't seem to edit all at once though. Happens nearly every time for me. Also, I often can't edit the 3rd select field or after. I can only tab to the next one to edit it, but it usually breaks after that.
![image](https://user-images.githubusercontent.com/16022203/153296819-893f4559-7e87-4540-9264-8e9c3331bc18.png)

### Steps to reproduce

Select a field and tab to the next one, for me there doesn't seem to be a limit to how many.

**Comment by Calinou** [comment] 2022-02-09 23:11
Duplicate of https://github.com/godotengine/godot/issues/37723.

**Closed by Calinou** 2022-02-09 23:11 UTC
Labels: bug, topic:editor
