### ISSUE TITLE
3.2 Stable - Video Player does not play video

### ISSUE THREAD

**Issue by alexfreyre** [godotengine/godot#35738] opened 2020-01-30 12:28 UTC
**Godot version:**
3.2 Stable

**OS/device including version:**
Manjaro Linux 18.1.5  x64

**Issue description:**
I am using a VideoPlayer as the father of a sphere and calling the current frame as diffuse texture for the sphere. Previous versions reproduce and behave normal, 3.2 stable does not reproduce and the stream position is always 0. I am using webm vp9.

**Comment by KoBeWi** [comment] 2020-02-21 07:29
Reproduction project?

**Comment by akien-mga** [comment] 2020-02-21 07:34
Assuming duplicate of #35760.

**Closed by akien-mga** 2020-02-21 07:34 UTC
