### ISSUE TITLE
Editor Script Debugger does not show data of objects in locals watch

### ISSUE THREAD

**Issue by wyattbiker** [godotengine/godot#22170] opened 2018-09-16 22:08 UTC
**Godot version:**
3.1 alpha
Mac OS X, High Sierra

**Issue description:**
Editor Debugger does not show data of objects in locals watch but only shows [empty]

**Steps to reproduce:**
Create a Button with some text on a scene.
Add script to Button and the following code:

```
# Called when the node enters the scene tree for the first time.
func _ready():
	var btn = get_node("/root/Menu/Button")
	print(btn.get_text())
	pass
```
Set breakpoint on `pass` line and run scene. View the Locals when breakpoint hits. You will see that **btn** object is [empty]

**Comment by elasota** [comment] 2018-09-16 22:09
Duplicate of #22138

**Comment by wyattbiker** [comment] 2018-09-16 22:10
Just noticed it. Thanks.

**Comment by vnen** [comment] 2018-09-16 23:12
Closing as duplicate.

**Closed by vnen** 2018-09-16 23:12 UTC
