### ISSUE TITLE
Crash when selecting and CTRL+D

### ISSUE THREAD

**Issue by yzt123** [godotengine/godot#31886] opened 2019-09-02 06:14 UTC
**Godot version:`3.2.dev.offical`**

**OS/device including version:`windows10 64bit`**

**Issue description:**
Sorry for using Google Translate.
In 2D workspace, left mouse button selects a Node2D (press and hold), then press CTRL+D, Godot will crash.

**Comment by qarmin** [comment] 2019-09-02 06:43
Duplicate of #27523

**Closed** 2019-09-02 06:55 UTC
