### ISSUE TITLE
GDScript fails to export variables properly from within a tool script, whenever a singleton is accessed within that script.

### ISSUE THREAD

**Issue by RabbitB** [godotengine/godot#6886] opened 2016-10-21 01:26 UTC
**Operating system or device - Godot version:**
Windows 10 Pro - Godot 2.1.0.0

**Issue description** (what happened, and what was expected):
GDScript fails to export variables properly from a tool script, whenever a singleton is accessed within that script.

Extensive details and how to reproduce here: [Export var bug when using singletons within a tool](http://dfaction.net/godot-export-var-bug-when-using-singletons-within-a-tool/)

**Comment by RebelliousX** [comment] 2016-11-15 12:17
Happens also in latest master branch.

It worth mentioning, disabling some pats of code while in editor, like using:
```
if (get_tree().is_editor_hint()):
    set_fixed_process(false)
```

To disable any code that mentions the autoload singleton, that doesn't work too.  "[Autoload name] identifier not found"

**Comment by jandrewlong** [comment] 2016-12-29 18:24
As a workaround, I've been using:

`onready var global = get_node("/root/global")`

**Comment by RebelliousX** [comment] 2016-12-29 23:13
@jandrewlong I am not really sure that will work, since by doing that, according to my knowledge, you are instantiating a new object, you are not using the same shared singleton global object.

What I did as a workaround, create child node with script that has "tool" keyword, which that script read export variables from parent object. That way changing parent's export variables will effectively change the child script through signals "setget"

**Comment by Hinsbart** [comment] 2017-08-08 13:14
Duplicate of #4326

**Closed by Hinsbart** 2017-08-08 13:14 UTC
Labels: bug, topic:gdscript

**Comment by tperraut** [comment] 2018-04-11 11:46
Why this one and #4236 are closed ?
This code :
```tool
extends TextureButton

export(String, "Settings", "Themes", "Play", "Hints", "Undo") var mType = "Play" setget set_type

#GameVars is a Singleton

func _ready():
	if !Engine.editor_hint:
		connect("pressed", GameVars.game, "on_" + mType + "_pressed")


func set_type(type):
	mType = type
	texture_normal = load("res://Sprites/UI/Buttons/" + type + ".png")
```

In Godot 3.0.1 causes no script variable on my object and comment the ready function causes script variable appearing.

**Comment by lucaslcode** [comment] 2019-06-04 22:35
@Hinsbart can you reopen this (or should I make another issue?) because this is still affecting me on 3.1.1, and the workaround posted by @jandrewlong doesn't work for me

**Comment by lucaslcode** [comment] 2019-06-04 23:53
New bug: #29492
