### ISSUE TITLE
Slightly warped RectangleShape2D in CollisionShape2D

### ISSUE THREAD

**Issue by berarma** [godotengine/godot#67722] opened 2022-10-21 15:42 UTC
### Godot version

v4.0.beta3.official [01ae26d31]

### System information

Debian GNU/Linux 11.5, Nvidia RTX 2070 Super (470.141.03)

### Issue description

The RectangleShape2D looks warped when applied to a CollisionShape2D in the editor. I haven't tried anything else, it might happen in other ways too.

The lines at the left top corner are thicker than the rest. Maybe if it's only a visual thing but it's misleading. At first I thought I had moved some vertex out of place.

See the attached screenshot.

### Steps to reproduce

Create a CollisionShape2D inside a CharacterBody2D node, then add RectangleShape2D from the GUI. Zoom in to look closer.

### Minimal reproduction project

![Captura de pantalla de 2022-10-21 17-32-20](https://user-images.githubusercontent.com/162766/197234880-21e45f3b-d9ce-4bb6-b904-55baa502d60d.png)

**Comment by markdibarry** [comment] 2022-10-21 15:53
Duplicate of #56320

**Comment by berarma** [comment] 2022-10-21 17:04
Thanks, I couldn't find it. Take this as a confirmation the bug is still there. I found no issues with the circule and capsule shapes.

**Closed** 2022-10-21 17:13 UTC
