### ISSUE TITLE
The editor code prompted incorrectly

### ISSUE THREAD

**Issue by 2821869675** [godotengine/godot#37738] opened 2020-04-10 04:25 UTC
**Godot version:**

**OS/device including version:**
windows 7 Ultimate X64
**Issue description:**
The second argument editor for the open method of the file class was not prompted correctly
![截屏_2020-04-10_12-12-04](https://user-images.githubusercontent.com/35617666/78962028-ea1d0c00-7b25-11ea-9e8d-37b0cc308d27.png)
The editor thinks it should underline
But the run will report an error

**Comment by 2821869675** [comment] 2020-04-10 04:28
supplement:
The editor prompts several constants of the File class as constants of the _File class

**Comment by bojidar-bg** [comment] 2020-04-10 06:28
Duplicate of #35469

**Closed by bojidar-bg** 2020-04-10 06:28 UTC
