### ISSUE TITLE
[4.0b1 MacOS] Editor not launching, just hangs instead

### ISSUE THREAD

**Issue by okla** [godotengine/godot#65923] opened 2022-09-16 18:49 UTC
### Godot version

4.0 beta 1

### System information

MacOS Monterey 12.5.1 (21G83)

### Issue description

Trying to launch the editor, but it's not opening, Activity Monitor shows it as not responding. Sometimes project manager is launched, but creating and opening a project hangs the editor again.

<img width="1072" alt="Screen Shot 2022-09-16 at 21 36 41" src="https://user-images.githubusercontent.com/8558017/190709820-5e6baa9d-b461-44a9-9fa9-4b8a6e206fa5.png">

### Steps to reproduce

Just launch the editor

**Comment by okla** [comment] 2022-09-16 19:02
After several attempts and waiting it launched. But something is wrong, Godot 3.5 launches near instantly.

**Comment by Calinou** [comment] 2022-09-16 19:03
Duplicate of https://github.com/godotengine/godot/issues/62322.

**Closed by Calinou** 2022-09-16 19:03 UTC
