### ISSUE TITLE
[4.0 RC 1] Typed Array function return value inferring as Variant

### ISSUE THREAD

**Issue by alekthesixth** [godotengine/godot#72932] opened 2023-02-09 00:19 UTC
### Godot version

4.0 RC1

### System information

Arch Linux x86_64

### Issue description

When updating from *Godot 4.0 beta 17* to *Godot 4.0 RC1* (custom build with GodotSteam from [this commit](https://github.com/godotengine/godot/commit/2572f6800aef09bd6ea96f3b1c7a999a962eecb7)) I started getting this warning treated as an error that didn't happen before (regression).

![image](https://user-images.githubusercontent.com/101995884/217680996-8cf1b652-e0c7-41ff-98d3-617ae3ecb523.png)

Error line:
![image](https://user-images.githubusercontent.com/101995884/217681093-f11b78de-54bd-46a5-9350-c6cd6def6aa7.png)

Variable definition:
![image](https://user-images.githubusercontent.com/101995884/217681160-3ba2a1bc-b114-4189-b060-4f51e7f3cfc9.png)

I disabled the warning for now but just letting you guys know.

### Steps to reproduce

Create a variable typed as a typed array and try to use functions like `pop_back()` or `pop_at(idx)`.

![image](https://user-images.githubusercontent.com/101995884/217680281-48d7b2c0-2024-4446-878f-6b93757ec976.png)

### Minimal reproduction project

Minimal reproduction project: [Typed Array as Variant.zip](https://github.com/godotengine/godot/files/10691094/Typed.Array.as.Variant.zip)

**Comment by KoBeWi** [comment] 2023-02-09 02:08
Duplicate of #59721

**Closed by KoBeWi** 2023-02-09 02:08 UTC
