### ISSUE TITLE
Performance drop when camera get close to Particle system or MultiMeshInstance

### ISSUE THREAD

**Issue by OBKF** [godotengine/godot#26708] opened 2019-03-06 14:21 UTC
**Godot version:**
2.1, 3.0, 3.1

**OS/device including version:**
Ubuntu 18.04 / IntelHD 4600

**Issue description:**
I have noticed that when Particles (GPU and CPU ones) or MultiMeshInstance with a lot (32 only can cause this issue) of quads get close to the camera the performance go down drastically. 
I have a demo where when the camera is far the fps is about 200 but when I get closer it drops to 17.
The problem starts when some geometry gets out of camera bounds, this happens in Godot 2.1.6 and 3.1 so I guess it's a design thing! 

Here is a [video of the issue](https://youtu.be/ixEEoqgFgjU) in Godot 3.1 and screenshots from Godot 2.1.6

Particle system inside camera bounds 
![normal](https://user-images.githubusercontent.com/12987951/53887337-57f12d00-4022-11e9-923a-a66013581c85.png)
Particle system partially out of camera bounds
![bug](https://user-images.githubusercontent.com/12987951/53887391-76572880-4022-11e9-99fe-ea0feb18aba7.png)

**Comment by arkology** [comment] 2019-03-06 15:35
I can confirm it

**Comment by HoboGus** [comment] 2019-03-06 17:08
happens in my project as well, seems really important

**Comment by CptPotato** [comment] 2019-03-07 19:11
One thing to keep in mind is that transparent sprites - whether it's particles or not doesn't matter - cause a LOT of overdraw if used in high numbers. Overdraw means that some pixels of the screen are written to many times per frame.

The result is performance drops mostly proportional to the number of pixels covered which seems like plausible explanation to me: In your 2nd screenshot around 3-4 times as many pixels are covered by the effect and the render-time increases accordingly to that.

**Comment by OBKF** [comment] 2019-03-09 10:59
@CptPotato it's not that, I have tested with an additive shader where the texture is just white on black,
so no transparent is involved and the result is near the same.
I also have a level with a lot of trees with a lot of transparent leafs and it runs above 60FPS.
IMO the camera bounder y culling is the issue here cause it runs well unless something go partially out of camera.

**Comment by CptPotato** [comment] 2019-03-09 15:30
@OBKF Additive blending still causes all sprites to be drawn on top of each other. So it effectively has the same result since you're getting exactly the same amount of overdraw. Check the overdraw debug view in Godot to get a visual representation or how many times pixels are being drawn to.

Maybe it's not a GPU but CPU bottleneck. Though, I can't tell for sure because in my tests I could not reproduce this issue.

**Comment by Calinou** [comment] 2019-04-18 17:43
Is this fixable on Godot's side? We can't magically increase the GPU's fill rate :slightly_smiling_face:

**Comment by Calinou** [comment] 2020-11-28 16:16
Hardware fill rate are now documented in [GPU Optimization](https://docs.godotengine.org/en/3.2/tutorials/optimization/gpu_optimization.html#pixel-fragment-shaders-and-fill-rate), closing.

**Closed by Calinou** 2020-11-28 16:16 UTC
Labels: discussion, topic:rendering
