### ISSUE TITLE
CanvasItem modulate alpha is ignored when shader material is configured

### ISSUE THREAD

**Issue by bitbrain** [godotengine/godot#70340] opened 2022-12-20 09:39 UTC
### Godot version

4.0beta (dcb3754db09b7b8c35aae1fedbc485b91e9f9508)

### System information

MacOS, Vulkan Forward, Metal GPUFamily Apple 7

### Issue description

In Godot 3, a `CanvasItem` can be configured with a shader material that changes its colour. However, changing the `modulate` property would work independently of the shader. This is not the case in Godot 4. In Godot 4, the `modulate` property is ignored unless the alpha value drops to 0.

## Godot 3
<img width="1425" alt="Screenshot 2022-12-20 at 09 32 08" src="https://user-images.githubusercontent.com/822035/208634475-97e83320-598f-4800-8056-e18e8e7da794.png">

## Godot 4
<img width="1424" alt="Screenshot 2022-12-20 at 09 31 34" src="https://user-images.githubusercontent.com/822035/208634438-0eea8e43-a28b-4ee1-87b3-3b821518805b.png">

### Steps to reproduce

1. setup sprite with Godot logo
2. Set its modulate alpha to 0.5
3. create new shader material
4. attach the following script:
```glsl
shader_type canvas_item;

render_mode unshaded;

void fragment() {
	COLOR = vec4(texture(TEXTURE, UV).rgb, 1.0);
}
```

Expected result: the sprite is at 50% transparency
Actual result: the sprite is at 100% transparency

### Minimal reproduction project

[shader-transparency-gd3.zip](https://github.com/godotengine/godot/files/10267189/shader-transparency-gd3.zip)
[shader-transparency-gd4.zip](https://github.com/godotengine/godot/files/10267190/shader-transparency-gd4.zip)

**Comment by KoBeWi** [comment] 2022-12-20 10:27
Duplicate of #49781

**Closed by KoBeWi** 2022-12-20 10:27 UTC
