### ISSUE TITLE
[BUG] Editor icons broke after changing layout.

### ISSUE THREAD

**Issue by avril-gh** [godotengine/godot#6952] opened 2016-10-28 16:43 UTC
**Operating system or device - Godot version:**
OS - Windows 7 32bit
Godot - 2.2 alpha custom build 2016-10-26

**Issue description** (what happened, and what was expected):
After changing editor layout fiew times, editor icons randomly breaks.
if you click them, they might eventualy return to normal.

**Steps to reproduce:**
Play around with switching editor layout like shown on example animated gif

**Link to minimal example project** (optional but very welcome):
![editor_layout2](https://cloud.githubusercontent.com/assets/3224132/19814324/0c3fbce8-9d3e-11e6-85ae-4556f10fdd33.gif)

**Comment by bojidar-bg** [comment] 2016-10-28 17:12
Duplicate of #6302 and #6464 (and one other if I remember right...)

**Closed by bojidar-bg** 2016-10-28 17:12 UTC
