### ISSUE TITLE
uncaught exception: out of memory html export

### ISSUE THREAD

**Issue by PravinKumar95** [godotengine/godot#29968] opened 2019-06-21 20:35 UTC
**Godot version:**

Godot 3.1.1

**OS/device including version:**

Windows 10, firefox ,gpu-Geforce 1050Ti

**Issue description:**

Html exported game shows out of memory error on html(console) when refreshed.

**Steps to reproduce:**
1. export game to html
2. Refresh the page couple of times  (three or more)

**Minimal reproduction project:**

[build.zip](https://github.com/godotengine/godot/files/3315937/build.zip)

**Comment by KoBeWi** [comment] 2020-07-21 21:33
Can anyone still reproduce this bug in [Godot 3.2.2](https://godotengine.org/article/maintenance-release-godot-3-2-2) or any later release?

**Comment by Faless** [comment] 2020-07-27 12:45
I've seen this many times during development but it seems to be a browser issue (on page refresh, all memory should be freed, while it's not). Closing the tab or window, and re-opening it in a new one will free the memory.

See https://github.com/emscripten-core/emscripten/issues/9321
And https://bugzilla.mozilla.org/show_bug.cgi?id=1576829

I'm closing, since there is not much we can do about this, and it's already reported upstream where it can be fixed.

**Closed by Faless** 2020-07-27 12:45 UTC
Labels: bug, platform:html5, topic:porting
