### ISSUE TITLE
Godot 3.2 mipmap forced to viewport texture when it used in environment

### ISSUE THREAD

**Issue by danilw** [godotengine/godot#36718] opened 2020-03-02 02:30 UTC
**Godot version:**
3.2 stable

**OS/device including version:**
linux

**Issue description:**
it does not happen in 3.1
set viewport texture as `environment.background_sky.set_panorama`
mipmap will be forced on it
mipmap forced
![1](https://user-images.githubusercontent.com/24825887/75640469-44cd6900-5c46-11ea-92d1-3b545e18a585.png)
correct
![2](https://user-images.githubusercontent.com/24825887/75640471-46972c80-5c46-11ea-91ad-701a6397ac31.png)

**Steps to reproduce:**
```
	var iChannel=viewport.get_viewport().get_texture()
	camera.environment=load("res://default_env.tres") as Environment
	camera.environment.background_sky.set_panorama(iChannel)
```

**Minimal reproduction project:**
I dont have minimal project for it, not minimal [project link](https://github.com/danilw/godot-utils-and-other/tree/master/Dynamic%20sky%20and%20reflection)
open it(Dynamic sky and reflection) in Godot 3.2 launch youl see-one sphere become black, and bugs on other figures
then comment or delete line 51 in *scripts/scene_cam.gd*
`self.environment.background_sky.set_panorama(iChannel)` 
everything will work

**Comment by clayjohn** [comment] 2020-03-02 04:42
The panorama texture requires mipmaps in order to compute the sky radiance maps correctly. Computing mipmaps should be creating a big black sphere in the middle of the panorama though. There must be some other issue going on.

**Comment by danilw** [comment] 2020-03-02 08:46
in that project I use same texture as `background_sky.set_panorama` and on objects, so I send it to many shaders as uniform

in Godot 3.2 mipmap **forced** on every next this texture usage after `self.environment.background_sky.set_panorama()` call

in Godot 3.1 it does not forced, every next texture usage reset its flags

obvious fix to it set `iChannel.flags=Texture.FLAG_FILTER` (iChannel is viewport texture) on each next this viewport texture usage.

so bug is - this does not happen on Godot 3.1

**Comment by clayjohn** [comment] 2020-03-02 15:18
It doesn't happen every frame, it happens when you call ``set_panorama()``. 

``set_panorama()`` calls ``sky_set_texture()`` which computes the radiance maps. The radiance maps need mipmaps from the panorama sky, so if they aren't enabled, it forces them on. 

Again though. This won't cause the large black sphere you have appearing in that image. So there must be something else going on as well. 

Generating mipmaps is not a bug.

**Comment by danilw** [comment] 2020-03-02 15:35
ok nwm then
my point is - this changed form Godot 3.1

can be closed idk, do as you wish

**Comment by clayjohn** [comment] 2020-03-02 16:00
I'm just wondering if there is another bug? That first screenshot looks very broken.

**Comment by danilw** [comment] 2020-03-02 16:26
there no other bugs, whole project logic is display single "procedural panorama" on shapes and environment
this is only mipmap

I do not have time to test this "new feature" and why it happen, I already tell fix - just set texture flags before every next usage `iChannel.flags=Texture.FLAG_FILTER`

**Comment by clayjohn** [comment] 2020-03-02 19:25
Ah, if that is the case then this isn't a bug and I will close this issue. But you have provided useful notes for others who may be experiencing the same thing. Thanks. :)

**Closed by clayjohn** 2020-03-02 19:25 UTC
Labels: discussion, topic:rendering
