### ISSUE TITLE
error with wrong mark place and wrong infomation: " Error parsing expression, misplaced: '\n'"

### ISSUE THREAD

**Issue by zszen** [godotengine/godot#30097] opened 2019-06-26 17:32 UTC
**Godot version:**
3.1.1

**OS/device including version:**
mac10.14.4

**Issue description:**
type code:
```
val++
if val==30:
  ...
```

focus on if line with error info:  Error parsing expression, misplaced: '\n'

![image](https://user-images.githubusercontent.com/1890538/60201662-625a5f80-987b-11e9-8599-bcc548dd8a39.png)

**Comment by akien-mga** [comment] 2019-06-26 17:36
Duplicate of #19128

**Closed by akien-mga** 2019-06-26 17:36 UTC

**Comment by SrColoma** [comment] 2021-04-23 23:11
me volvio a pasar godot 3.2
![image](https://user-images.githubusercontent.com/51213418/115938147-4ae06380-a45f-11eb-9ec8-24efa4f4ac2f.png)
