### ISSUE TITLE
Custom variable/function can make notes for it

### ISSUE THREAD

**Issue by fish2091852127** [godotengine/godot#30955] opened 2019-07-30 08:38 UTC
new featrue propose:
user can add notes for scripts custom variable/function, (user can make a note for a self variable in scirpt,when cursor at the variable can be show the note)

**Comment by KoBeWi** [comment] 2019-07-30 11:24
I think there was already similar proposal, but I can't find it now >_>

**Comment by Calinou** [comment] 2019-07-30 13:28
Duplicate of https://github.com/godotengine/godot/issues/27607 and https://github.com/godotengine/godot/issues/4370.

**Closed by Calinou** 2019-07-30 13:28 UTC
Labels: feature proposal, topic:editor
