### ISSUE TITLE
editor_settings.tres file sometimes grows to ridiculous size

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#16838] opened 2018-02-19 23:33 UTC
**Godot version:** 3.0 (happened in 2.1.4 too)

**OS/device including version:** Windows 10 Home

**Issue description:** One time I noticed unusual editor startup and closing time, also some slowdowns during saving with errors about editor_settings.tres file (although this could be unrelated). Anyways, I looked into my %appdata%/godot directory and my editor settings file was... almost 200MB big. Somehow it got corrupted and grew into some ridiculous size. Well, I just deleted it and everything returned to normal, with new small settings file. But later it happened again. And again. No idea how to reproduce it, because it seems random, when I load projects or something.

I'm reporting this mainly because just today it happened in Godot 3 too. I did some search and seems like this issue is either unreported, or I'm the only one encountering it ;_; Anyways, the huge settings file can't be opened with notepad (it just freezes and becomes unresponsive) and using Notepad++ will freeze after scrolling down about 300 lines.

You can get the file here: https://ufile.io/fsr7i
(yes, it is a legit file produced by Godot editor)

**Comment by akien-mga** [comment] 2018-02-20 07:48
The issue happens at line 316 in the file:
```
314:editors/tile_map/palette_min_width = 80
315:editors/grid_map/palette_min_width = 230
316:_C:::Users::Tomek::Desktop::Studia::MadÃ^cÂ^cÃ^bÂ^cÃ^cÂ^bÃ^bÂ^cÃ^cÂ^cÃ^bÂ^bÃ^cÂ^bÃ^bÂ^cÃ^cÂ
```

The `^cÃ^cÂ` escape codes (in `nano` - in `konsole` it's directly `ÃÂÃÂ`) are repeated *ad lib* and make the file huge.

This seems to be an encoding issue with the name of your folder, could you share what its name is, and what is your encoding?

**Comment by KoBeWi** [comment] 2018-02-20 09:53
Well, I suspected that this might be the problem, but forgot to mention it. The name of the folder is Madżister. I'm not sure about encoding, it's likely Windows' default one for files. I inspected the name in irb (since I have Ruby installed) and it labels it as "Mad\xBFister" and encoding as Windows-1250.

**Comment by bojidar-bg** [comment] 2018-02-20 14:42
Duplicate of #6888.

**Closed by bojidar-bg** 2018-02-20 14:42 UTC
Labels: bug, topic:editor
