### ISSUE TITLE
ViewportTexture remains bright pink in some projects after upgrade to 4.0.3-stable

### ISSUE THREAD

**Issue by z80** [godotengine/godot#77678] opened 2023-05-31 05:00 UTC
### Godot version

4.0.3-stable

### System information

Windows 10

### Issue description

In some projects ViewportTexture remains pink and doesn't render viewport content after upgrading from 4.0.2-stable to 4.0.3-stable. If a pair of files viewport.h/viewport.cpp are downgraded back to what they were in 4.0.2-stable, problem goes away.

This is how it looks in 4.0.3-stable:
![4 0 3_stable_viewport_4 0 3](https://github.com/godotengine/godot/assets/1449921/44c191a9-4b67-4b02-90b6-4ab615f62a73)

And this is how it looks if viewport.h/viewport.cpp are downgraded back to what they were in 4.0.2-stable.
![4 0 3_stable_viewport_4 0 2](https://github.com/godotengine/godot/assets/1449921/f5abc605-f129-4222-9c0e-e9a07621dd9d)

### Steps to reproduce

Unfortunately, I cannot come up wit a simple demo project reproducing the problem. It exists in some projects and doesn't exist in others.

### Minimal reproduction project

Cannot produce a simple project reproducing the problem. In simple projects it works fine.

**Comment by KoBeWi** [comment] 2023-06-13 11:01
Does it occur in 4.1 beta?

**Comment by Rindbee** [comment] 2023-06-13 11:04
This seems to be an issue that has never been resolved.

It is related to the mechanism of `resource_local_to_scene` when the scene is initialized. `Resource` is set up before `Node`, `setup_local_to_scene()` is not called when setting the value of `viewport_path`, so you need to call `setup_local_to_scene()` when the scene is initialized. 

https://github.com/godotengine/godot/blob/ae896bbd85d0c9f1883c81f138045c3753ccef01/scene/resources/packed_scene.cpp#L459-L463

The resources cached by `resources_local_to_scene` require resources on the resource chain to enable `resource_local_to_scene`.

```
Node->R1->R2->R3->ViewportTexture(resource_local_to_scene)
```

R1, R2, and R3 all have to enable `resource_local_to_scene`.

**Comment by Rindbee** [comment] 2023-06-13 11:44
A duplicate of #68088.

**Comment by Rindbee** [comment] 2023-06-23 06:36
Related to #74331.

**Comment by z80** [comment] 2023-06-26 17:17
@Rindbee I'll check and let you know.

**Comment by z80** [comment] 2023-06-26 20:06
@Rindbee Hello! Based on the source code it feels that error messages do not all the details of what's happening. I made two videos with breakpoints placed in all methods of ViewportTexture. Please see the videos attached.

This one is a success when viewport.h/cpp are downgraded to what it was in 4.0.2:
https://github.com/godotengine/godot/assets/1449921/86eb2145-9d75-4bba-8b06-591505e84216

And this one is a failure as it happens in some projects in 4.0.3:
https://github.com/godotengine/godot/assets/1449921/e22f91ce-8d00-4b26-a3e0-39168c32e332

**Comment by Rindbee** [comment] 2023-06-26 21:26
OK, it's helpful. It is failing early in `ViewportTexture::_setup_local_to_scene()` (due to the target viewport not being in the tree yet), causing `vp_pending` to fail to reset its state. This makes the setup not yet complete and subsequent calls to `ViewportTexture::_setup_local_to_scene()` impossible.

**Closed** 2023-06-27 13:45 UTC
Labels: bug, topic:rendering, needs testing, regression
