### ISSUE TITLE
Theme not updating on tweak when it's set as custom theme in Project Settings

### ISSUE THREAD

**Issue by Grumoth** [godotengine/godot#79319] opened 2023-07-11 08:45 UTC
### Godot version

4.1 stable

### System information

Godot v4.1.stable unknown - Manjaro Linux #1 SMP PREEMPT_DYNAMIC Wed Jul  5 23:49:30 UTC 2023 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3060 (nvidia; 535.54.03) - AMD Ryzen 5 7600X 6-Core Processor (12 Threads)

### Issue description

When you set a custom theme in Project settings it doesn't update anymore on real time when you tweak it, so you have to change tabs or reload it in order to reflect this changes.
Real time visual feedback is quite  important and this bug consumes a lot of time while checking and reloading tabs.
The workaround would be to set the theme manually in every root node, but it's quite annoying when you have tons of elements in complex UI.

https://github.com/godotengine/godot/assets/7796648/3da81fd6-116f-4ef2-b3f1-88170ea5d5fd

### Steps to reproduce

-Create a new theme
-Set it as custom theme for the whole game in 'gui/theme/custom' in Project Settings
-Tweak any color and see it doesn't update in the viewport
-Change tab and go back and see that now it's updated

### Minimal reproduction project

[bug_update_theme.zip](https://github.com/godotengine/godot/files/12012632/bug_update_theme.zip)

**Comment by YuriSizov** [comment] 2023-07-11 09:10
Thanks for making a report. This is a duplicate of https://github.com/godotengine/godot/issues/33902. Global themes, like the default GUI theme and the custom one that you set in the project settings, do not have a mechanism to signal updates to the scenes that use them at the moment. So this is an old and known limitation.

I have a solution in works though.

**Closed by YuriSizov** 2023-07-11 09:10 UTC

**Comment by Grumoth** [comment] 2023-07-11 11:54
Ok! Couldn't find that topic, but thank you very much for your response. Hope you find some solution about.
Cheers!
