### ISSUE TITLE
UI Appears to be a Step Behind in Visual Updates

### ISSUE THREAD

**Issue by Apprehentice** [godotengine/godot#26222] opened 2019-02-24 06:13 UTC
**Godot version:** 3.0.6

**OS/device including version:** Windows 10 (Ver 1803 Build 17134.590)

NVidia GeForce 1050 TI (Notebook) (Driver Version 419.17)

**Issue description:** The UI appears to be a step behind in visual updates. For instance, typing in a text field doesn't show the last character typed until another character is entered (Ex. When typing "godot", The letter 'g' will not appear until the letter 'o' is entered.)

Of course, a picture is worth a thousand words: https://streamable.com/cuxpz

**Steps to reproduce:**

* Open Godot
* Click "New Project"
* Start typing in a text field, noting that it is a step behind in visual updates

**Minimal reproduction project:** N/A, happens on project selection

**Comment by JFonS** [comment] 2019-02-24 07:23
Related to #23069. But with a different graphics card/drivers?

**Comment by Apprehentice** [comment] 2019-02-24 09:26
My apologies for not finding the mentioned issue. The only other graphics card I've been able to test it on is an NVIDIA GeForce GTX 960, same Win10 and driver version, where it works fine.

**Comment by akien-mga** [comment] 2019-02-24 15:10
Are you sure that it's running on the Nvidia GPU and not on an integrated
Intel chipset? (Godot should output which GPU is used in the terminal.)

**Comment by Apprehentice** [comment] 2019-02-24 20:26
Forgive my ignorance, it appears that it is using the Intel(R) UHD Graphics 630 chipset. I'm in the process of downloading and installing new NVIDIA driver software to confirm that the problem is the NVIDIA chipset.

**Comment by SeleckyErik** [comment] 2019-02-24 21:32
You can force using Nvidia GPU with particular software (e.g. Godot} from the NVIDIA Control Panel.

**Comment by Apprehentice** [comment] 2019-02-26 20:17
My laptop lacks the NVIDIA Control Panel for some reason, but I was able to force Godot to use the NVIDIA GPU through the Windows context menu. The problem is not present on the NVIDIA GPU and remains a problem with the Intel GPU.

**Comment by akien-mga** [comment] 2019-02-27 10:27
Duplicate of #23069.

**Closed by akien-mga** 2019-02-27 10:27 UTC
