### ISSUE TITLE
Changing `global groups` of a scene and going to another scene crashes the editor

### ISSUE THREAD

**Issue by GustJc** [godotengine/godot#94501] opened 2024-07-18 09:58 UTC
### Tested versions

- Reproducible in: v4.3.beta3.mono.official [82cedc83c]

### System information

Windows 10 - Vulkan (forward+) - dedicated

### Issue description

Changing a scene root node group and switching scenes sometimes crashes the editor if the other scene has the that as a linked scene.
This is kinda inconsistent. But I think I got a clue.
It has something to do with linked scenes.
It happens when you change the global group on a scene. save it and go back to a scene that used that as a linked node.
It might also need to have that node previously selected when going back to the scene that has the linked scene.

There is no error in the console. And also no error in the appdata folder.

Here's a couple of videos showing how it happens to see if it helps.

https://github.com/user-attachments/assets/db38f2f6-6046-4f38-9e47-3734897dfae9

And here is another one, after I think I figure out what is the cause:
The first time, I didn't save the Mob scene. But after saving and going back. Crash.

https://github.com/user-attachments/assets/52b01b48-d1a2-4a62-b005-824bcaf00759

### Steps to reproduce

- Open the world scene and select the linked node 'Mob'
- Open the Node->Groups tab
- Open the Mob scene
- Add it to the global group 'mob'. Save the scene.
- Go back to the world scene
- Repeat going back and forth and changing the Mob scene group and saving (sometimes it doesn't happen on the first try?)

Result: Crashes editor. No error or logs.

### Minimal reproduction project (MRP)

[global_group_crash.zip](https://github.com/user-attachments/files/16281211/global_group_crash.zip)

**Comment by KoBeWi** [comment] 2024-07-18 14:00
Duplicate of #94274

**Closed by KoBeWi** 2024-07-18 14:00 UTC
Labels: bug, topic:editor, crash
