### ISSUE TITLE
Godot crashes at startup if the supported OpenGL version is too low

### ISSUE THREAD

**Issue by swenner** [godotengine/godot#1748] opened 2015-04-27 19:02 UTC
Master (1.1beta), 32bit debug build, Ubuntu 14.04. Executable: godot.x11.tools.32
Segfaults at start up.

Godot should print a friendly message, that it can't run. What are the minimal requirements to run the engine?

Program received signal SIGSEGV, Segmentation fault.
0x00000000 in ?? ()
(gdb) bt
#0  0x00000000 in ?? ()
#1  0x081705bc in RasterizerGLES2::init (this=0x97cda10)
    at drivers/gles2/rasterizer_gles2.cpp:10795
#2  0x08c0e503 in VisualServerRaster::init (this=0x97fdaf0)
    at servers/visual/visual_server_raster.cpp:7450
#3  0x08c43c74 in VisualServerWrapMT::init (this=0xb5862020)
    at servers/visual/visual_server_wrap_mt.cpp:152
#4  0x08051586 in OS_X11::initialize (this=0xbfffed6c, p_desired=..., 
    p_video_driver=0, p_audio_driver=0) at platform/x11/os_x11.cpp:425
#5  0x0805b30a in Main::setup2 () at main/main.cpp:771
#6  0x0805a68e in Main::setup (
    execpath=0xbffff2ae "bin/godot.x11.tools.32", argc=0, argv=0xbffff0d8, p_second_phase=true)
    at main/main.cpp:717
#7  0x0804f5ba in main (argc=1, argv=0xbffff0d4)
    at platform/x11/godot_x11.cpp:36

OpenGL vendor string: Intel Open Source Technology Center
OpenGL renderer string: Mesa DRI Intel(R) IGD x86/MMX/SSE2
OpenGL version string: 1.4 Mesa 10.1.3

**Comment by wawanbreton** [comment] 2015-06-08 20:47
Confirmed on LUbuntu 14.10 32 bits
Graphic board : Intel Corporation Mobile 945GSE Express Integrated Graphics Controller (rev 03)
All drivers up-to-date (or maybe I should upgrade to the most recent Ubuntu version ?)

Actually, it is quite a pain that Godot can't work on old devices.
As you say, it shoud at least print a nice message before crashing.

**Comment by reduz** [comment] 2015-06-08 20:49
I tried to print a nice message, but it crashes and I don't have an old
device to test why. patch for this welcome :)

**Comment by bvanevery** [comment] 2015-06-18 21:14
I'm affected by this too, on one of my 3 machines.  An old 2008 era laptop running Windows 7 Ultimate.  GPU Caps Viewer says "Mobile Intel(R) 4 Series Express Chipset Family", GMA 4500MDH.  GL_VERSION 2.1.0, GLSL version 1.2.0.  It's a DX10 class part, but looking at some forums, Intel didn't bother to do OpenGL 3.x for these devices.  OpenGL is definitely a deployment problem for old Windows laptops with integrated graphics.

**Comment by akien-mga** [comment] 2015-11-06 10:18
Duplicate of #156, related to #1162.

**Closed by akien-mga** 2015-11-06 10:18 UTC
