### ISSUE TITLE
Godot 4 Beta 17: Browser freezes for minutes when loading a web-exported Godot project in Chrome on macOS

### ISSUE THREAD

**Issue by konsuko** [godotengine/godot#72584] opened 2023-02-02 11:02 UTC
### Godot version

v4.0-beta17 c40020513

### System information

Windows 10, GLES3, Chrome Version 109.0.5414.120 (Official Build) (64-bit)

### Issue description

When uploading a new project without any content (I tried a simple scene with one 2D sprite and the Godot log graphic), and exporting this as a WebGL build, then loading it on e.g. itch.io, the entire browser freezes on macOS.

On itch.io the setting for `SharedArrayBuffer` **is set**, otherwise the project will not even load and shows [this error](https://cdn.discordapp.com/attachments/810529956609654835/1070626071852089446/image.png)

When loading the project, the Chrome console output shows this error:
`Blocking on the main thread is very dangerous, see https://emscripten.org/docs/porting/pthreads.html#blocking-on-the-main-browser-thread
onPrintError @ index.js:13991`

The error appears, then the entire tab *and the rest of the browser* freezes completely and becomes unresponsive for about 1-2 minutes.

After the freeze, the game seems to run again, normally.

**Important**: This freeze *only* happens on Chrome on my Macbook Pro, running the latest macOS Ventura 13.2 and the latest version of Chrome.

The freezes happens for a very short amount of time on my Windows PC as well, but it's not that noticeable.

### Steps to reproduce

- Create a new Godot 4 project with the latest beta 17, either on macOS or on Windows 10 (tested both).
- Add a main scene and a single 2d sprite node in the middle of the screen, just for testing purposes.
- Export the project with the default web export settings
- Upload the project to itch.io and load it
- Encounter the freeze

### Minimal reproduction project

This can be reproduced by playing it here: https://ghostbutter.itch.io/test-godot-freeze?secret=wK5roG3DyBXpWjStHef5yf98

**Comment by Zireael07** [comment] 2023-02-02 13:42
Does the freeze happen on other browsers/platforms? If not, it's likely the shaders crosscompiling to ANGLE...

**Comment by konsuko** [comment] 2023-02-02 13:56
> Does the freeze happen on other browsers/platforms? If not, it's likely the shaders crosscompiling to ANGLE...

The freeze barely happens on Windows/Chrome, it's only 1-2 seconds of noticeable freeze, compared to 1-2 minutes of unresponsive browser on macOS.

Unfortunately this makes current Godot WebGL games basically unplayable on macOS/Chrome.
Would be really appreciated if this could be fixed, if at all possible.

**Comment by Calinou** [comment] 2023-02-02 13:57
This is expected due to ANGLE making shader compilation very slow. There's no way to work around this issue, and is one of the reasons we recommend sticking to 3.x for web projects currently.

**Comment by konsuko** [comment] 2023-02-02 14:13
> This is expected due to ANGLE making shader compilation very slow. There's no way to work around this issue, and is one of the reasons we recommend sticking to 3.x for web projects currently.

That's unfortunate since I really need a feature that's only in 4.X, not in 3.X, so that's not an option for me.

I am also confused why this is not an urgent fix before the release of 4.0?

The way I see it, right now there is no way to make functioning web exports with Godot 4, which basically means that Godot can't really be used for game jams anymore.
Web exports are really important for game jam visibility (download-only game jam titles get wayyy less ratings)

Also: Is it even 100% clear that this is what's causing this?

The console error `Blocking on the main thread is very dangerous, see https://emscripten.org/docs/porting/pthreads.html#blocking-on-the-main-browser-thread onPrintError @ index.js:13991` seems to be quite relevant as well? Does this have nothing to do with it?

**Comment by Calinou** [comment] 2023-02-02 14:19
> I am also confused why this is not an urgent fix before the release of 4.0?

We can't fix it – ANGLE is very slow at compiling shaders, because it insists on doing strict validation of every compiled shader.

**Comment by konsuko** [comment] 2023-02-02 14:27
@Calinou Thanks for the detailed explanation! :)

But just to clarify: This means that - in the foreseeable future - I won't be able to make web games with Godot 4.X that run on macOS/Chrome? This directly affects my next project which I was about to plan making in Godot, unfortunately.

**Comment by Byteron** [comment] 2023-02-02 14:32
but it works in Godot 3, so there is a way to make it work.
Why would Godot 4 not be able to do the same thing?
I would understand it if we were talking about the Vulkan renderer.
But we're talking about the compatibility (OpenGL) renderer, which already worked fine in HTML Exports in 3.5.

**Comment by lostminds** [comment] 2023-02-02 14:45
Unfortunately it's not just a Chrome issue. Testing 4.0b17 web exports now: In Safari on macOS 13 the loading bar finishes but then you get a spinning white things that just stays indefinitely as far as I can tell. In Firefox on macOS 13 the progress bar gets stuck at about 95% for 10+minutes before surprisingly starting the game. 

In both these cases I think we can assume any normal player would just assume it was broken and give up. It would be great if this could be fixed somehow so Godot 4 web builds would work on macOS as well.

**Comment by Calinou** [comment] 2023-02-02 14:45
> But just to clarify: This means that - in the foreseeable future - I won't be able to make web games with Godot 4.X that run on macOS/Chrome?

It's possible that Godot 4.x will eventually run well on HTML5, but not before 4.1.

> but it works in Godot 3, so there is a way to make it work.

Godot 3.x's GLES3 renderer has a lot of issues on HTML5, including slow shader compilation in Chromium-based browsers. You need to use GLES2 to get a good experience, which is a far more limited renderer (that doesn't even use WebGL 2.0).

**Comment by konsuko** [comment] 2023-02-02 15:24
> Please keep the discussion about macOS in https://github.com/godotengine/godot/issues/67949.

It is definitely *only* a macOS issue from what I can see. Windows works fine for me on Chrome.
Firefox on Windows does not even load, though: `Error
The following features required to run Godot projects on the Web are missing:
Cross Origin Isolation - Check web server configuration (send correct headers)
SharedArrayBuffer - Check web server configuration (send correct headers)`

Overall, Web exports seem to be quite broken as of now, which is saddening because I always considered it one of Godot's huge strengths as my go-to gamejam engine.

**Comment by clayjohn** [comment] 2023-02-02 16:40
This is a duplicate of https://github.com/godotengine/godot/issues/70691

This indeed looks like a shader compilation issue. Likely it is due to ANGLE on chrome being very slow. We are doing some work on ANGLE for desktop macOS (to alleviate bad drivers) and we seem to have a solution there to the slow shader compiles. If we are lucky, we may be able to enable similar optimizations for web exports. 

I also have a few other ideas to increase shader compilation time in the gl_compatibility renderer generally, but will not have time to work on them until after 4.0 is out. 

Closing in favour of https://github.com/godotengine/godot/issues/70691

**Closed by clayjohn** 2023-02-02 16:40 UTC
Labels: bug, platform:web, topic:rendering, confirmed, topic:thirdparty, performance
