### ISSUE TITLE
Adding keyframe to camera causes problems with preview

### ISSUE THREAD

**Issue by antoni4040** [godotengine/godot#16167] opened 2018-01-29 22:09 UTC
**Godot version:**
Godot 3 RC3

**OS/device including version:**
Linux Mint 18.1 64-bit, Kernel version: 4.4.0-53-generic, GPU:GeForce GTX 750

**Issue description:**
The camera preview behaves weirdly when an animation player keyframe is added.

**Steps to reproduce:**
Not sure how to reproduce it in a new project. Maybe there's something specific in my project that messed it up.
Anyway, just open up the test project and you'll find a camera and an animation player. Click on the animation player and then on the camera and add a Transform > Rotation Degrees keyframe. Then click on another point in time on the animation timeline. You'll see in the preview that the camera is rotated towards the sky, and if you rotate it to see objects they will look as if the normals got flipped or something.
[Shmup_test_1.zip](https://github.com/godotengine/godot/files/1675424/Shmup_test_1.zip)
![weird](https://user-images.githubusercontent.com/5155109/35537029-6f1225d2-0551-11e8-90f2-88e9bf40ca99.png)

**Comment by antoni4040** [comment] 2018-01-30 09:05
A little update: with Godot 3 stable the problem persists, but I noticed that if the camera is a child of the AnimationPlayer then there are no problems. Not sure if this is intended behavior...

**Comment by KoBeWi** [comment] 2019-05-02 14:59
@antoni4040 Could you test if that still happens in 3.1 for you? Because I can't reproduce it there.

**Comment by KoBeWi** [comment] 2020-07-10 10:37
Closing due to no reply. Please comment if you can still reproduce in 3.2.2.

**Closed by KoBeWi** 2020-07-10 10:37 UTC
Labels: bug, topic:editor
