### ISSUE TITLE
[C#] Assembly export

### ISSUE THREAD

**Issue by IlyaStuurFedorov** [godotengine/godot#31390] opened 2019-08-15 13:48 UTC
I am currently trying to build a modding framework on top of the Godot, and I am having some troubles with it. I would like to propose some sort of an additional point in the config/export toolset to allow people to manually decide where to put their assemblies because for my game I would like to put GodotSharp.dll and GodotSharpEditor.dll as well as %GameName%.dll somewhere outside from .pck so other mods could easily reference them. I don't know how possible this is, or how valid of a request this is, but I simply could not find any other way around this problem.

**Comment by neikeq** [comment] 2019-08-15 14:09
It's definitely possible and I'm actually considering doing it by default as some libraries (like `Microsoft.CodeAnalysis.Scripting`) expect the assemblies to be in the file system.

**Comment by mhilbrunner** [comment] 2020-05-28 15:41
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!

**Closed by mhilbrunner** 2020-05-28 15:41 UTC
Labels: feature proposal, topic:mono

**Comment by neikeq** [comment] 2020-05-28 16:26
This was actually a duplicate of #29349. This is already implemented by #33982

**Comment by sericaer** [comment] 2020-12-19 07:08
> This was actually a duplicate of #29349. This is already implemented by #33982

Could you tell me how to use this option? 
Thanks a lot!
