### ISSUE TITLE
GDScript formatted strings overwritten with old values when passed an empty array.

### ISSUE THREAD

**Issue by Jack-023** [godotengine/godot#97176] opened 2024-09-19 03:40 UTC
### Tested versions

v4.3.stable.arch_linux

### System information

Godot v4.3.stable unknown - Arch Linux #1 SMP PREEMPT_DYNAMIC Thu, 12 Sep 2024 17:21:02 +0000 - X11 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3090 (nvidia; 560.35.03) - AMD Ryzen 7 5800X 8-Core Processor (16 Threads)

### Issue description

When a formatted string using the % operator is given an empty array of arguments, it will replace the entire string (not just the placeholder) with the previous formatted string.

```gdscript
print("working %s string" % "formatted")
print("non-formatted string")
print("broken %s string" % [])
```
Will output
```
> working formatted string
> non-formatted string
> working formatted string
```
It does produce an error saying there are not enough arguments for the format string but it still runs and the output it produces is pretty confusing.

### Steps to reproduce

See above.

### Minimal reproduction project (MRP)

N/A

**Comment by matheusmdx** [comment] 2024-09-19 05:52
Maybe a OS specific issue? Because here works as expected:

![image](https://github.com/user-attachments/assets/9829f745-ea14-44ad-8831-8761a6af6e17)

Godot v4.3.stable - Windows 10.0.19045 - Vulkan (Forward+) - dedicated AMD Radeon RX 580 2048SP (Advanced Micro Devices, Inc.; 31.0.21916.2) - AMD Ryzen 5 3600 6-Core Processor (12 Threads)

**Comment by akien-mga** [comment] 2024-09-19 11:21
I can't reproduce the issue either on Linux. I get, as expected:
```
working formatted string
non-formatted string
ERROR: not enough arguments for format string
   at: validated_evaluate (core/variant/variant_op.h:951)
```

Can you share a MRP that triggers that issue reliably for you?

**Comment by Jack-023** [comment] 2024-09-19 11:31
Just realised I made a mistake when writing this up again. The value that gets substituted can't be hard-coded.
```gdscript
var foo := "foo"
print("%s bar" % foo)
print("hard coded values have no effect %s" % "baz")
print("this gets replaced by the first line %s" % [])
```
Output
```
foo bar
hard coded values have no effect baz
foo bar
```
Should have double checked this before posting, my bad!

**Comment by akien-mga** [comment] 2024-09-19 11:38
I can confirm the issue with the code in https://github.com/godotengine/godot/issues/97176#issuecomment-2360733917.
Pretty weird bug.

**Comment by aaronp64** [comment] 2024-09-19 12:50
Looks like the same issue as https://github.com/godotengine/godot/issues/95152, should be fixed by https://github.com/godotengine/godot/pull/95166

**Comment by akien-mga** [comment] 2024-09-19 14:19
Thanks, consolidating in #95152.

**Closed by akien-mga** 2024-09-19 14:19 UTC
Labels: bug, topic:gdscript, confirmed
