### ISSUE TITLE
android.apk\assets\.import  is never compress

### ISSUE THREAD

**Issue by denghe** [godotengine/godot#44078] opened 2020-12-04 06:28 UTC
**Godot version:**
3.2.3.stable

**Issue description:**
when export android apk, the file size is huge: .apk\assets\.import  directory is never compress ! there are so many etc1/2 files need compress !
for example: 
![image](https://user-images.githubusercontent.com/3364637/101130262-1732a780-363e-11eb-9214-0c0502620e00.png)

**Comment by Riteo** [comment] 2020-12-04 07:54
maybe duplicate of #29415?

**Comment by bruvzg** [comment] 2020-12-04 08:01
The purpose of texture compression is to save video RAM, not a disk space. ETC have fixed 4:1 compression comparing to raw RGBA bitmap. ZIP or PNG have variable (and in most cases higher) compression rate, comparing it does not make much sense.

**Comment by denghe** [comment] 2020-12-04 10:33
![image](https://user-images.githubusercontent.com/3364637/101153337-40176480-365f-11eb-9266-c6d1426277a8.png)

**Comment by akien-mga** [comment] 2020-12-04 10:40
That's 100% binary data, there's likely nothing to compress for whatever compression algorithm is used by APK (probably zlib or similar). If you look at `icon.png` it also doesn't change size. It's the text-based data that the APK compresses.

**Comment by bruvzg** [comment] 2020-12-04 10:48
Some file types in APK are not compressed, here's relevant code:

https://github.com/godotengine/godot/blob/617031434f8ce48194a411e5406b22efce92c940/platform/android/export/export.cpp#L540-L566

**Comment by denghe** [comment] 2020-12-04 13:56
".stex" usually already compressed  but   ".etc.stex" is not

**Comment by Calinou** [comment] 2020-12-04 14:45
There's a pull request to compress VRAM-compressed textures to decrease file size at the cost of longer load times, but it wasn't merged: https://github.com/godotengine/godot/pull/24528

**Comment by Calinou** [comment] 2021-01-30 17:03
Duplicate of https://github.com/godotengine/godot/issues/24501.

**Closed by Calinou** 2021-01-30 17:03 UTC
Labels: discussion, platform:android, topic:porting
