### ISSUE TITLE
Game Crashes when resizing the screen from corners

### ISSUE THREAD

**Issue by RCodeStudios** [godotengine/godot#56316] opened 2021-12-29 11:49 UTC
### Godot version

3.4.2

### System information

Windows 10, Nvidia RTX 3050 & integrated radeon graphics, Gles3 & 2

### Issue description

So when I got a new laptop and fired up godot 3.4.2 and created a new project, added a node2d and saved then ran in editor and when i resizing the screen from corners(no bug if resized from edges) the game crashes, it happens with both gles2 and gles3. even if i change my gpu from nvidia rtx 3050 to my integrated radeon graphics from my ryzen 7 5880H, the problem still exists.
it happens when running from editor, exported debug exe and even the non-debug exe. I have attached a video of the problem below

https://user-images.githubusercontent.com/96679528/147659138-84e81b93-221b-445b-a15b-282e5b9f0855.mp4

### Steps to reproduce

1. create a new project
2. add a node 2d
3. save the scene
4. run the game
5. resize the game window from corners

### Minimal reproduction project

[ScreenResizeBug.zip](https://github.com/godotengine/godot/files/7788685/ScreenResizeBug.zip)

**Comment by RCodeStudios** [comment] 2021-12-30 04:51
This also happens with a 3d scene

**Comment by RCodeStudios** [comment] 2021-12-30 04:52
and if u want my laptop's specs then:

name: Dell g15 Ryzen edition
processor:Ryzen 7 5800H
gpu: Nvidia RTX 3050
Ram: 16gb
ssd: 512gb

**Comment by Calinou** [comment] 2021-12-30 20:47
Duplicate of https://github.com/godotengine/godot/issues/24702.

**Closed by Calinou** 2021-12-30 20:47 UTC
Labels: bug, topic:porting, crash
