### ISSUE TITLE
Input.action_release releases but stays pressed on Android device.

### ISSUE THREAD

**Issue by songproducer** [godotengine/godot#6625] opened 2016-09-26 23:10 UTC
**Operating system or device - Godot version:**
OSX Godot 2.1

**Issue description** (what happened, and what was expected):
Action releases on Android but stays pressed.

**Steps to reproduce:**
Run the linked project, and swipe up. The character keeps walking forward.

**Link to minimal example project** (optional but very welcome):
https://www.dropbox.com/s/q3ods65fxdjhml2/3rdperson-godot-master.zip?dl=0

**Comment by Sslaxx** [comment] 2016-09-26 23:19
Sounds like #6388 this.

**Comment by akien-mga** [comment] 2016-09-28 11:48
Closing as duplicate of #6388.

**Comment by Hinsbart** [comment] 2016-09-28 14:32
But the touch events on android don't have key modifiers set, do they?
So I fail to see how this could be a duplicate of that issue. 
Unfortunately I don't have recent android templates, so can't test this now. However using the "emulate_touchscreen" option, it doesn't happen.

**Comment by songproducer** [comment] 2016-09-29 19:09
I just tested with the emulate_touchscreen option on and it happened when walking forward (holding down 'w') while clicking in the screen.

**Comment by Hinsbart** [comment] 2016-09-29 20:02
Ok, it does indeed happen on 2.1.
So for the touchscreen emulation, this is fixed in the master branch.
Though we might still want to confirm it on android.

**Comment by Noshyaar** [comment] 2018-04-06 11:36
First of all thank you for your report and sorry for the delay.

We released Godot 3.0 in January 2018 after 18 months of work, fixing many old issues either directly, or by obsoleting/replacing the features they were referring to.

We still have hundreds of issues whose relevance/reproducibility needs to be checked against the [current stable version](https://godotengine.org/download), and that's where you can help us.
**Could you check if the issue that you described initially is still relevant/reproducible in Godot 3.0 or any newer version, and comment about it here?**

For bug reports, please also make sure that the issue contains detailed steps to reproduce the bug and, if possible, a zipped project that can be used to reproduce it right away. This greatly speeds up debugging and bugfixing tasks for our contributors.

Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

Thanks in advance.

*Note: This message is being copy-pasted to many "stale" issues (90+ days without activity). It might happen that it is not meaningful for this specific issue or appears oblivious of the issue's context, if so please comment to notify the Bugsquad about it.*

**Comment by Sslaxx** [comment] 2018-05-18 12:52
Has anyone been able to recreate this with 2.1.4/2.1.5 beta or 3.0.x or master?

**Comment by akien-mga** [comment] 2018-11-22 12:36
As there was no answer to the above request, we're closing this issue as inactive.
If you can still reproduce it, please open a new issue against a currently supported release of Godot.

**Closed by akien-mga** 2018-11-22 12:36 UTC
Labels: bug, platform:android, topic:core
