### ISSUE TITLE
Inconsistent behavior with lambdas using local scope

### ISSUE THREAD

**Issue by TheWalruzz** [godotengine/godot#79472] opened 2023-07-14 16:58 UTC
### Godot version

4.1

### System information

Godot v4.1.stable - Windows 10.0.22621 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1060 (NVIDIA; 31.0.15.3129) - Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 Threads)

### Issue description

When trying to write some unit tests for my library, I noticed that modifying a locally defined variable (i.e. in function's body) inside of a Callable won't persist those changes in the outside scope, like so:

```gdscript
func check_with_local_var() -> void:
	print("====== LAMBDA WITH LOCAL CONTEXT ======")
	var result := false
	prints("Before call:", result)
	var callable := func():
		result = true
		prints("Inside lambda:", result)
	callable.call()
	prints("Outside lambda:", result)
```
The output in console will show values: `false`, `true`, `false`.

This is not the case when you use a variable defined in the class body - then everything works as expected. I know this isn't probably a very common use case, but logically, since you can **access** them, you should be able to modify them too.

### Steps to reproduce

1. Run the minimal reproduction project
2. Check the console. The result is:
```
====== LAMBDA WITH LOCAL CONTEXT ======
Before call: false
Inside lambda: true
Outside lambda: false
====== LAMBDA WITH CLASS CONTEXT ======
Before call: false
Inside lambda: true
Outside lambda: true
```
First group of text shows the incorrect behavior, second one shows the correct one, using class variables.

### Minimal reproduction project

[LambdaLocalContextBug.zip](https://github.com/godotengine/godot/files/12052369/LambdaLocalContextBug.zip)

**Comment by AThousandShips** [comment] 2023-07-14 17:00
Duplicate of #69014

**Closed by AThousandShips** 2023-07-14 17:00 UTC
Labels: discussion, topic:gdscript
