### ISSUE TITLE
Godot FPS demo has buggy behavior of "Sticky Grenade" in 3.1 beta6 while beta4 works well

### ISSUE THREAD

**Issue by JustusPan** [godotengine/godot#26226] opened 2019-02-24 10:38 UTC
**Godot version:**
Godot 3.1 beta 6

**OS/device including version:**
Laptop XPS 13
Iris 640

**Issue description:**
"Sticky Grenade" in Godot 3.1 will not be "sticky" anymore.
And sometimes it will stick to your face immediately.

Godot 3.0.6 works well.

**Steps to reproduce:**
1. with Godot 3.0.6
Open the project, press F5. 
press V to equip "Sticky Grenade", and press G to throw it, everything works well.

2. with Godot 3.1 beta 6
Open the project, press F5. 
press V to equip "Sticky Grenade", and press G to throw it,
Three possible phenomena will be observed:
a) the grenade stick to your face immediatelly(collided to floor object, which is unreasonable)
b) the "Sticky Grenade" has been thrown out and bounce off the wall (without any "sticky" behavior)
c) works as expectation

a)b)c) are randam results.

**Minimal reproduction project:**
[Official FPS demo Part 5](https://docs.godotengine.org/en/3.0/_downloads/Godot_FPS_Part_5.zip)

**Comment by JustusPan** [comment] 2019-02-24 12:49
More Information:

beta4 works well

**Comment by JustusPan** [comment] 2019-02-24 12:53
in beta 6, 
rigidbody bullets of "turret" cannot hit charater.
It seems some physical parts was broken.

**Comment by Zireael07** [comment] 2019-02-24 13:35
Duplicate of #26149,  most likely -fixed on master and will ship in next beta.

**Comment by hpvb** [comment] 2019-02-24 15:01
Probably fixed in b7

**Closed by hpvb** 2019-02-24 15:01 UTC

**Comment by JustusPan** [comment] 2019-02-24 15:09
> Probably fixed in b7

Confirmed.

**Comment by akien-mga** [comment] 2019-02-24 15:14
Can you test beta 7?

**Comment by Zireael07** [comment] 2019-02-24 15:37
@akien-mga He literally just confirmed that it's fixed in b(eta)7
