### ISSUE TITLE
Multiple sibling AudioStreamPlayers behaving inconsistently (volume db)

### ISSUE THREAD

**Issue by yhwhey** [godotengine/godot#53074] opened 2021-09-25 23:51 UTC
### Godot version

3.3.stable

### System information

Windows 10

### Issue description

When using a scene with two AudioStreamPlayer2Ds, variation between values of the Volume Db parameter are being ignored when running (works correctly in editor). Audio playback on both stream players triggered by AnimationPlayer node

### Steps to reproduce

Scene setup:

```
KinematicBody2D
- AnimationPlayer
- AudioStreamPlayer2D_1 (volume db set to 0)
- AudioStreamPlayer2D_2 (volume db set to -50)
```

Different animations play audio through either stream player but ignore the differently configured volume db parameter. Pitch parameter behaves correctly

**Comment by TokageItLab** [comment] 2021-11-10 20:40
Did you used AnimationTree? Is it related by #49099?

**Comment by TokageItLab** [comment] 2021-11-27 11:04
@yhwhey I can't reproduce the problem unless I use AnimationTree, can you upload a sample project that can reproduce the problem without using AnimationTree?

**Comment by akien-mga** [comment] 2022-02-06 21:56
No answer from the reporter, closing.

**Closed by akien-mga** 2022-02-06 21:56 UTC
Labels: bug, topic:audio
