### ISSUE TITLE
Feature request: Add ability to set default save location to scripts, scenes etc.

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#20667] opened 2018-08-02 07:52 UTC
When I try save some script, scene or something else, the save window rarely points to prepared by me folders(_Scripts, _Scenes, _Fonts), so I must find it. I wanna to be able to set the default resource folders in the editor/project settings(like image below). I think this should be disabled by default.
![fasfas](https://user-images.githubusercontent.com/41945903/43569670-6e3b3450-9638-11e8-89c1-9a247b19b114.png)

The save window, probably take last save location, but this is only sometimes useful. Here is example, how I create a script, and path was automatically set to _Scenes
![afff](https://user-images.githubusercontent.com/41945903/43569043-a51fbbdc-9636-11e8-898b-49a4a272bf98.png)

**Comment by vnen** [comment] 2018-08-02 16:45
Duplicate of #15231

Just to note: Godot recommendation is not to use that structure (you should organize your project by meaning in-gem, not by type of file). You can also use the favorite directories feature.

**Closed by vnen** 2018-08-02 16:45 UTC
