### ISSUE TITLE
Arrow keys don't work properly in settings

### ISSUE THREAD

**Issue by noname1477** [godotengine/godot#33364] opened 2019-11-05 15:49 UTC
**Godot version:**
3.2.alpha.3

**OS/device including version:**
Windows 10 1903

**Issue description:**
In the settings menus, the left arrow cursor seems to be dead. Up and down work just fine, and the right button does the same as the down button. Only the left arrow is not working.

**Steps to reproduce:**
1. Open any project and open the settings (either 'Editor Settings' or 'Project Settings')
2. Try to navigate through the menu using the arrow keys

**Minimal reproduction project:**
None, since this happens in all projects.

**Comment by Arunkumar1998BOM** [comment] 2019-11-05 19:26
Godot version:
3.2.alpha custom build

OS/device including version:
VERSION="18.04.3 LTS (Bionic Beaver)"

Issue also observed in this OS for both the cases

**Comment by codecustard** [comment] 2019-11-06 23:31
The left arrow key is used for collapsing and the right is used for expanding. The left arrow key not doing anything in this case is probably due to the way that the items are populated in the project and editor settings. Notice the behavior in the "Input Map" within the project settings or in the SceneTree Dock or Filesystem Dock for an example of the collapsing/expanding behavior.

**Comment by KoBeWi** [comment] 2020-10-23 23:33
This is not a bug. The category list is a Tree, so it has controls like in scene tree for example. Up/down for navigation, left/right to fold/unfold. If you want to use keyboard only, you can press Tab to select the right panel with settings.

Closing this.

**Closed by KoBeWi** 2020-10-23 23:33 UTC
Labels: bug, confirmed, topic:editor, usability
