### ISSUE TITLE
Mac rendering warnings such as invalid format

### ISSUE THREAD

**Issue by fire** [godotengine/godot#78008] opened 2023-06-08 16:02 UTC
### Godot version

On top of 4.0 branch. https://github.com/godotengine/godot/commit/fd5dc25240c1537d90b80507683f78bcf574f547

### System information

Mac Mini, Apple Silicon on Firefox

### Issue description

Error message in log.

```
e[1;31mERROR:e[0;91m vkCreateGraphicsPipelines failed with error -3 for shader 'CanvasOcclusionShaderRD:0'.
e[0;90m   at: render_pipeline_create (drivers/vulkan/rendering_device_vulkan.cpp:6394)e[0m
[mvk-error] VK_ERROR_FORMAT_NOT_SUPPORTED: VkFormat VK_FORMAT_R64G64_SFLOAT is not supported for vertex buffers on this device.
```

### Steps to reproduce

Launching my project.

### Minimal reproduction project

I think it happens on all mac projects, but checking now.

**Comment by clayjohn** [comment] 2023-06-08 16:15
Is this with a doubles build of Godot? If so, it may be a duplicate of https://github.com/godotengine/godot/issues/70879

**Comment by fire** [comment] 2023-06-08 17:08
It is a double build. Close if wanted.

**Closed** 2023-12-08 16:18 UTC
Labels: bug, platform:macos, topic:rendering
