### ISSUE TITLE
C# [Export] not registering as language keyword, even after Mono->Build

### ISSUE THREAD

**Issue by Kaideu** [godotengine/godot#23609] opened 2018-11-09 04:32 UTC
**Godot version:**

3.0.6

**OS/device including version:**

Windows 10

**Issue description:**

using no external editor.
I'm following the First Game Tutorial in C# and I came across the first script. using [Export] it should turn blue along with the brackets just like in the tutorial. Every keyword/reserved word so far has changed color according to what looks to be a color scheme.

I thought, maybe it's just a glitch,
so i saved the scene and saved my script, then I followed the instructions and hit Mono->Build project

this closed down my engine. So I reopened it expecting to see the variable in the inspector, but it wasn't there.

I'm not sure what do at this point since I've spent hours trying to make this work like it does seemingly everywhere else.

this is my script

```
using Godot;
using System;

public class Player : Area2D
{
	[Export]
	public int Speed = 0;
	
	private Vector2 _ScreenSize;
    // Member variables here, example:
    // private int a = 2;
    // private string b = "textvar";

    public override void _Ready()
    {
        // Called every time the node is added to the scene.
        // Initialization here
        
    }

//    public override void _Process(float delta)
//    {
//        // Called every frame. Delta is time since last frame.
//        // Update game logic here.
//        
//    }
}
```
**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by akien-mga** [comment] 2018-11-09 08:21
> 3.0

Are you using 3.0 from January 2018? If so please update to 3.0.6.

**Comment by Kaideu** [comment] 2018-11-09 16:02
> > 3.0
> 
> Are you using 3.0 from January 2018? If so please update to 3.0.6.

Sorry, I meant 3.0.6
I downloaded Godot a few days ago.
I thought it was 3.0

**Comment by exts** [comment] 2019-01-09 16:57
`using no external editor.`

Godot's editor does not have c# syntax highlighting so it won't change colors and I don't think it'll ever have plans to do that. You either need to use a text editor with the Omnisharp extension or a c# ide and open the project solution for editing.

As for the editor crashing can you open the editor from the windows cli (cmd.exe) or powershell or w/e and it should spit something out in the editor if it crashes again.

**Comment by neikeq** [comment] 2019-01-10 00:50
I think Godot added an interface some time ago to provide custom syntax highlighting in its script text editor. If true, we could use that to provide proper C# syntax highlighting. How we would provide that is a different question.

**Comment by Kaideu** [comment] 2019-01-10 04:58
The problem is not ultimately the highlighting. The problem is that the export did not work as it should. It did not provide the variable in the editor/inspector of the object the script is attached to.
I haven't attempted this since posting this thread though, so I may try again to see if I made a rookie syntax mistake or not for the brackets when declaring the var type.

**Comment by KoBeWi** [comment] 2020-06-30 23:34
Can anyone still reproduce this bug in [Godot 3.2.2](https://godotengine.org/article/maintenance-release-godot-3-2-2) or any later release?

If yes, please ensure that an up-to-date Minimal Reproduction Project (MRP) is included in this report (a MRP is a zipped Godot project with the minimal elements necessary to reliably trigger the bug). You can upload ZIP files in an issue comment with a drag and drop.

**Comment by KoBeWi** [comment] 2020-09-28 22:21
Closing due to lack of update. Please comment if you can still reproduce this issue in the latest stable version of Godot.

**Closed by KoBeWi** 2020-09-28 22:21 UTC
Labels: bug, topic:mono
