### ISSUE TITLE
Bug : TextureProgress not rendering and there is an Error : bad polygon 

### ISSUE THREAD

**Issue by CCODE05B** [godotengine/godot#17011] opened 2018-02-25 13:27 UTC
**Godot version:**
Godot 3.0.1-RC1

**Issue description:**
TextureProgress not working well when using Clockwise Fill mode , it's not rendering if reaching some value and there is an Error say : bad polygon 

**Minimal reproduction project:**
[TestProgressTexture.zip](https://github.com/godotengine/godot/files/1756056/TestProgressTexture.zip)

**Comment by Jcozman** [comment] 2018-02-26 22:55
I am experiencing the same issue with the counter clockwise fill mode. Setting the min value to 0 and max value to 1, with a step of .01 will disallow me from using values greater than ~.63

**Comment by CCODE05B** [comment] 2018-02-27 17:27
@Jcozman For me this solution not working in my project it's still give me the same error
and why this issue not set as bug ?

**Comment by akien-mga** [comment] 2018-03-01 15:42
Duplicate of #17102.

No need to reopen an issue when there is one already. An issue not labelled as "bug" just means that no issue triager had time to look at it yet.

**Closed by akien-mga** 2018-03-01 15:42 UTC
Labels: bug, topic:rendering
