### ISSUE TITLE
Tooltip in Editor Inspector is blinking

### ISSUE THREAD

**Issue by jinyangcruise** [godotengine/godot#99523] opened 2024-11-22 07:02 UTC
### Tested versions

- Reproducible in 4.4.dev5
- Not Producible in 4.4.dev4

### System information

Windows 11 - Godot v4.4.dev5 - Windows 10.0.22631 - Multi-window, 1 monitor - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3060 Ti (NVIDIA; 32.0.15.6094) - 13th Gen Intel(R) Core(TM) i5-13600KF (20 threads)

### Issue description

Put mouse hover a property name in Inspector, the tooltip is blinking. Only in 4.4.dev5.

https://github.com/user-attachments/assets/4076863c-e0fc-488f-bf17-19779ba7d164

### Steps to reproduce

NA

### Minimal reproduction project (MRP)

NA

**Comment by Chaosus** [comment] 2024-11-22 07:48
Duplicate of https://github.com/godotengine/godot/issues/99287

**Closed by Chaosus** 2024-11-22 07:48 UTC
