### ISSUE TITLE
Plugins tab inside Project settings draws an extra rect when a plugin is selected

### ISSUE THREAD

**Issue by WhalesState** [godotengine/godot#80675] opened 2023-08-16 03:19 UTC
### Godot version

4.x

### System information

Windows 10

### Issue description

It happened with me many times that the Project settings draws a rect in a wrong position like this one.

![image](https://github.com/godotengine/godot/assets/53877170/7bc895cc-6523-4734-9f8a-53c6beb26a73)

Note: can't remember exactly if this happens with other tabs, but for now i can produce the issue with the plugins tab, so i will try to track it, if it happens with other tabs please tell me in comments so i can track this too. maybe there's an extra `draw_rect` inside the draw notification that should be deleted. or the position and size should be fixed to surround the current selected plugin. also the Name, Version and Author Labels doesn't look aligned, maybe we can add a separator between them or to align them to the left instead of center.

### Steps to reproduce

open project settings -> switch to plugins tab [must have one or more plugins] -> select a plugin or try to enable/disable it and the rect will appear.

Edit: Tried to reproduce the issue in another project and this happened, will try to find why it happens!

![image](https://github.com/godotengine/godot/assets/53877170/1f61d52b-bc8e-45bc-8f40-a159d9f26f55)

happens with input map too!

![image](https://github.com/godotengine/godot/assets/53877170/42a811f0-8ed8-4d9b-98ad-f9a4da016570)

localization and autoload also produce the same issue
![image](https://github.com/godotengine/godot/assets/53877170/82186023-cf26-4a03-a41a-ca14a6793a24)

### Minimal reproduction project

N/A

**Comment by WhalesState** [comment] 2023-08-16 03:56
where can i track this ? surely something is wrong with the position of focus rect, I have searched for a draw_rect in plugin settings cpp files and have found nothing! so i suspect that it's a stylebox.

**Comment by dalexeev** [comment] 2023-08-16 06:55
* Duplicate of #74115.

**Closed by dalexeev** 2023-08-16 06:55 UTC
