### ISSUE TITLE
Problem inserting accented characters: 'The caller thread cannot call this function'

### ISSUE THREAD

**Issue by CachorroVoador** [godotengine/godot#82608] opened 2023-10-01 03:03 UTC
### Godot version

v4.1.1.stable.official [bd6af8e0e]

### System information

Debian 12 i5 650 64 bits

### Issue description

When attempting to type accented characters in text fields or input areas in the Godot Engine, an error is displayed in the console with the message "Caller thread can't call this function in this node (/root). Use call_deferred() or call_thread_group() instead." Additionally, accented characters are not inserted correctly into the text.

**Expected Behavior:**

Accented characters should be inserted correctly into the text field without displaying errors in the console.

**Observed Behavior:**

When attempting to type accented characters, the following error message is displayed in the console:
`Caller thread can't call this function in this node (/root). Use call_deferred() or call_thread_group() instead.`

Accented characters are not inserted correctly into the text.

https://github.com/godotengine/godot/assets/87171245/769c0907-e489-4bf4-84ea-8dd0573ae9de

### Steps to reproduce

Open a project in the specified version of Godot Engine.
Open a text field or input area.
Try to type an accented character, such as "á" or "é."

### Minimal reproduction project

I believe it is not necessary, as it does not involve any interference from the project settings

**Comment by shazelquist** [comment] 2023-10-04 20:52
### System information

v4.1.1.stable.official [bd6af8e]

Debian 12 QEMU Virtual version 2.5+ x6

#### Observed Behavior:

I was able to reproduce the error message ``Caller thread can't call this function in this node (/root). Use call_deferred() or call_thread_group() instead.`` from [here](https://github.com/godotengine/godot/blob/bfd78bb917887cfc1fd842ba23570394cad8bedb/scene/main/node.h#L742) using both a Portuguese (Brazil) keyboard and Unicode entry on a English (US) keyboard. Using Unicode entry may serve as a mitigation until this is closed as it actually inserts accented characters, but the console still produced an error message for each keystroke. I tested (U+00E1) and (U+00E9).

**Comment by Calinou** [comment] 2023-10-04 21:28
Are you using IME, dead keys or standard keys to input accented characters?

I can't reproduce this on 4.2.dev fe8a58b9d (Fedora 38, fr-oss keyboard layout):

https://github.com/godotengine/godot/assets/180032/a4d60fe4-839f-45df-8ec7-91c1bf7e5871

**Comment by shazelquist** [comment] 2023-10-05 21:36
I used dead keys in my tests, but wasn't able to consistently replicate accented characters not inserting.

I wonder if the insertion problem is a clarity issue causing miss-input. Some other programs seem to actually represent the dead keys like an IME with an underlined version of the modifier, but it doesn't seem like godot's input visually supports that.
LibreOffice:
![image](https://github.com/godotengine/godot/assets/11480905/8ab21b1d-1223-4074-8ccc-63268d0616db)
Godot:
![image](https://github.com/godotengine/godot/assets/11480905/b104c6de-e69f-4e5b-884b-d712ff2fa546)

**Comment by CachorroVoador** [comment] 2023-10-07 23:22
I ended up having a problem with my Debian, where I had to format my PC. I ended up going to Arch Linux. The error does not persist in Arch

**Comment by shazelquist** [comment] 2023-10-08 06:28
I'll try and check out the font idea. It's also possible that Debian is doing something weird since I couldn't get the on-screen keyboard accessibility to recognize godot's input fields either.

**Comment by dkaste** [comment] 2023-10-23 19:03
I can reproduce this on Fedora 38, GNOME 44.5, Godot v4.2.beta2.official [f8818f85e] using both accented Latin characters and Chinese (Intelligent Pinyin) entered with GNOME "Input Sources".

**Comment by HolonProduction** [comment] 2023-11-23 16:42
Are you using `IBus` and if which version?

**Comment by shazelquist** [comment] 2023-11-24 05:24
Looks like my Debian 12 tests were using IBus version 1.5.27

**Comment by HolonProduction** [comment] 2023-11-24 12:17
> Looks like my Debian 12 tests were using IBus version 1.5.27

Do the accented characters get inserted for you?

**Comment by shazelquist** [comment] 2023-11-24 21:58
Accented characters seem to insert regularly now, though they still apply the ``Caller thread can't call this function in this node (/root). Use call_deferred() or call_thread_group() instead.`` error message. 

I can't seem to replicate any of the infrequent insertion problems using deadkeys. The current session is running wayland, and I think that's the default under Deb-12.

It looks like insertion problems might have been fixed somehow these package updates as they're the only updates between now and 2023-10-7.
```
libvpx7:amd64 1.12.0-1+deb12u2
libx11-6:amd64 2:1.8.4-2+deb12u2
libx11-xcb1:amd64 2:1.8.4-2+deb12u2
libx11-data:all 2:1.8.4-2+deb12u2
libxpm4:amd 1:3.5.12-1.1+deb12u1
libc-bin:amd64 2.36-9+deb12u3
```

**Comment by HolonProduction** [comment] 2023-11-24 22:49
The insertion problem only appears with a newer IBus version. Just wanted to confirm, that you only have the thread error message and we don't have another issue with IME.

**Closed** 2023-12-05 12:57 UTC
Labels: bug, platform:linuxbsd, confirmed, topic:input
