### ISSUE TITLE
CSGCombiner3D causing editor to crash

### ISSUE THREAD

**Issue by Skyvastern** [godotengine/godot#74343] opened 2023-03-04 07:15 UTC
### Godot version

4.0.stable

### System information

Windows 10 64-bit, 8GB RAM, Nvidia GTX 1650

### Issue description

When using CSGCombiner3D and CSGBox3D nodes to prototype level, the editor crashes. The exact point of crash is shown in this video.

### Steps to reproduce

The steps to reproduce is shown in this video.

https://user-images.githubusercontent.com/52847458/222881631-b1af8ab9-03b9-4e11-ad79-dbbdea4bf0a7.mp4

### Minimal reproduction project

[CSGCombiner3D Bug.zip](https://github.com/godotengine/godot/files/10887712/CSGCombiner3D.Bug.zip)

**Comment by Calinou** [comment] 2023-03-04 08:18
Duplicate of https://github.com/godotengine/godot/issues/73927.

**Closed by Calinou** 2023-03-04 08:18 UTC

**Comment by YuriSizov** [comment] 2023-03-08 20:44
Thanks for the repro project and the clip, it helped to pinpoint the issue very quickly.
