### ISSUE TITLE
External Editing Viewports

### ISSUE THREAD

**Issue by randyemens** [godotengine/godot#29634] opened 2019-06-09 20:16 UTC
Being able to see multiple scenes and their scripts side-by-side might be useful. It would help give a better picture of how everything works together. Something that could help resolve this is by allowing scenes and their scripts to be in external viewports so that they can be placed anywhere.

**Comment by KoBeWi** [comment] 2019-06-09 20:28
Somewhat related to #8250

**Comment by Calinou** [comment] 2019-06-09 20:40
Duplicate of https://github.com/godotengine/godot/issues/9059.

**Closed by Calinou** 2019-06-09 20:40 UTC
Labels: enhancement, feature proposal, topic:editor, usability
