### ISSUE TITLE
InputEvent Mouse wheel and viewport mouse coordinates

### ISSUE THREAD

**Issue by HisDivineShadow** [godotengine/godot#8427] opened 2017-04-16 21:58 UTC
Windows 10 pro Version 1703 - build 15063.183 - Godot 2.1.3 stable/official 

When testing/running a scene in a window and attempting to assess the mouse position when handling a MOUSE_BUTTON / BUTTON_WHEEL_xxx event the get_viewport().get_mouse_pos() returns the mouses location in relation to the operating system display size across all displays and not in relation to the game window itself.   Other MOUSE_BUTTON events are working as desired and returning expected values. 

This was working in Godot 2.1.2 stable as expected but after updating to 2.1.3 and testing a current project I discovered this change in behavior.  I am not certain if this is by design or an unexpected behavior, any input would be helpful. 

reproduction steps are:
1. create a new project that runs in a window (default behavior)
2. create a node in any scene.
3. Attach a script
4. set process input to true
5. in the input event function check for mouse button an button wheel input
6. print output of  get_viewport().get_mouse_pos()

Minimal project attached illustrating the issue:

[Debug.zip](https://github.com/godotengine/godot/files/924601/Debug.zip)

**Comment by bojidar-bg** [comment] 2017-04-17 08:39
Can someone test this on linux/mac? (to confirm if it is windows-only or not)?

**Comment by bojidar-bg** [comment] 2017-04-17 08:46
Ok, I **can't** confirm on linux using the provided project on 2.1.3/HEAD... -- The mouse down and mouse scroll events give the same position no matter the game window's position and size.

**Comment by Melix19** [comment] 2017-04-17 11:01
Tested on macOS and the mouse button and wheel give the same position based on the game window. I can confirm that this problem is present on windows only.

**Comment by spacehuhn** [comment] 2017-05-05 10:09
Got the same issue here using Godot 2.1.3 on windows, works fine on Linux or on windows using v2.1.2.

**Comment by GlOwl** [comment] 2017-05-05 10:15
For me in Linux (Ubuntu) it works all fine. 
I had the same problem with an Java project some years ago. windows says its mouse coordinates begin somewhere under its window border not at the inside of it (as everywhere else).

**Comment by akien-mga** [comment] 2017-05-05 10:20
CC'ing potential culprits for this regression ;)

@Hinsbart (ed31340), @SaracenOne (919c1d6)

**Comment by vnen** [comment] 2017-05-05 14:19
I fixed a bug like this one (#5841) and the related code hasn't changed since them. I wonder what caused the regression.

Looking at #8136, it seems a bit strange to me because `set_mouse_pos()` is not called anywhere else in that file. The function is usually called in the OS-specific event loops. But I'm not sure if that is the problem.

**Comment by akien-mga** [comment] 2017-06-15 16:25
Fixed by #9197.

**Closed by akien-mga** 2017-06-15 16:25 UTC
Labels: bug, confirmed, platform:windows, topic:porting
