### ISSUE TITLE
Godot editor do not open in GLES2

### ISSUE THREAD

**Issue by moizez102** [godotengine/godot#20588] opened 2018-07-29 23:27 UTC
**Godot version:**
3.1.dev.calinou.07129de, downloaded from this page: https://hugo.pro/projects/godot-builds/ 
edit: i try in the alpha 1 and it is the same, but! if you edit the "project.godot" or the "default_env.tres" with something like notepad++ it can be """fixed""" 

**OS/device including version:**
Mini laptop
OS:Windows 7 (with windows 10 theme) 
CPU: Intel Celeron CPU 847 1.10 GHz
PC Architecture: 32Bits 
 

**Issue description:**

Well ... I was testing version 3.1 because my computer does not have GLES 3 and I tried to open my test project, but when I tried to open it, only the godot logo came out, then the screen went black and I got an error from windows of "the video driver stopped working" i ask in discord if someone had this error (in the "Castilian" area) but I did not have an answer, so I put it here, to see if my computer is just regrettable or is it an editor error
(if you open only godot without going to a project, the project manager opens normally)

(i also try opening another proyect and it is the same)

(also sorry for my bad english)

**Steps to reproduce:**

1- Open the CMD in the folder where Godot.exe is
2- write the name of the executable next to the parameters to execute with GLES2

(example: Godot.exe --video-driver GLES2 D: \ Users \ Moises \ Documents \ New \ XD \ project.godot)

**Minimal reproduction project:**
i dont think that is posible xD but i recorded a video showing what happend, i hope that help
link: https://youtu.be/WDdt_ZKSCxw

**Comment by williamd1k0** [comment] 2018-07-30 00:18
On my PC, the Editor (with GLES2) is *randomly* getting stuck at the splash screen.
Project Manager works fine.
Same build. Windows 10 x64/Intel HD Graphics 400.

**Comment by williamd1k0** [comment] 2018-07-30 19:32
It worked again for me in the latest build (15db793ef277b6d2c3aae5e5a075ba2ece31b27a)
@moizez102 please try it again using the latest build.

**Comment by moizez102** [comment] 2018-07-31 15:52
still not working for me :( im trying the lastest build (3f01f40) and is the same, but i dont think is my computer because the project manager works normally...

this appears in the console 
![captura](https://user-images.githubusercontent.com/41637732/43470948-d9d88dfc-94b7-11e8-9c2f-5013f6bb5a94.PNG)

**Comment by akien-mga** [comment] 2018-08-13 08:09
CC @karroffel

**Comment by avril-gh** [comment] 2018-08-13 08:37
godot 3.1 (latest master branch) _rather_ works for me with GLES2 on Windows7 32bit OpenGL 4.6 GPU

but im geting exacly same error like moizes102 above, on various android devices with GLES2 GPU
look https://github.com/godotengine/godot/issues/20958 for reference

**Comment by williamd1k0** [comment] 2018-08-14 05:26
Update: I'm still having this issue on Windows.

When I try to open the editor using GLES2 it's randomly getting stuck at the splash screen. Sometimes it works normally, sometimes it takes a while to work and sometimes it gets stuck forever.
This also applies to the game run (debug and release).

My console does not have any error messages.

**Comment by Zimakili** [comment] 2018-08-31 19:12
As of 21ea1d8  this is still an issue, 

OS:Windows 7 
Processor: Intel Core i3-330M 2,13G
Graphics: Intel(R) HD Graphics (Driver Version 8.15.10.2993)
PC Architecture: 32Bits

The editor reboots the driver and crashes Godot

**Comment by Zimakili** [comment] 2018-08-31 20:15
@williamd1k0 Have you tried this: ( from issue #21551 )

> Go to the project directory, open the file called project.godot and remove this line:

> [rendering]

> environment/default_environment="res://default_env.tres"

It worked for me.

**Comment by moizez102** [comment] 2018-08-31 22:31
if you change the "default.env.tres like this image", the editor work again.... i dont know if that helps, but 
just in case


![fix](https://user-images.githubusercontent.com/41637732/44938200-66951980-ad4b-11e8-8a81-0893814786da.PNG)

**Comment by zarsystem** [comment] 2018-09-01 05:43
Setting default environment background mode to procedural sky crashes on gles2 on my work office PC with Intel HD graphics 4400 but changing that to custon color solves the crash problem.

**Comment by williamd1k0** [comment] 2018-09-01 10:59
@Zimakili I just tried to set the background_mode to 0 (clear color) and now I think it's working fine.

**Comment by SIsilicon** [comment] 2018-09-03 22:44
I get this problem on my PC too.
Windows 7 64-bit
Intel HD Graphics 4400

Whether I open the project it from the project select screen, or convert from gles3.0 to gles2.0, screen goes black and windows whines like a baby about the video driver crashing.

**Comment by akien-mga** [comment] 2018-09-10 16:54
Closing as duplicate of #21551. It's more recent, but has a clearer title and about the same amount of information - if anything is missing from there, feel free to copy paste it.

**Closed by akien-mga** 2018-09-10 16:54 UTC
Labels: bug, topic:editor, topic:rendering
