### ISSUE TITLE
Noticeable performance hit when using gdscript vs c# to do >1000s of matrix and vector math operations per frame in a single loop

### ISSUE THREAD

**Issue by Miziziziz** [godotengine/godot#46029] opened 2021-02-14 17:34 UTC
**Godot version:** Godot Mono v3.2.3 and Godot v3.2.3

**OS/device including version:** Windows 10, GLES3, Geforce 2060 rtx

**Issue description:**

I have this procedural hair generated using ImmediateGeometry:
https://user-images.githubusercontent.com/7292421/107883893-fb097d00-6eae-11eb-9c10-86a716994d3a.mov
Calculating all the vertice positions requires a lot of vector math (cross products and such) and then also has to be converted from local, to global, to local positions at one point. Doing this on my machine has a noticeable impact in the profiler:
![gdscriptprofiler](https://user-images.githubusercontent.com/7292421/107883954-50458e80-6eaf-11eb-9027-35c21aa2f76e.png)
Recreating this in C# gives about a 10fps improvement in my main project.
Can't really see frame time in the profiler but you can see the graph and compare:
![csprofiler](https://user-images.githubusercontent.com/7292421/107883991-900c7600-6eaf-11eb-9758-51ba0432f626.png)

Since math is done in c++ I figured the issue was probably related to how gdscript handles loops or arrays and might be worth reporting.

**Steps to reproduce:**
see example project

**Minimal reproduction project:**

contains a C# scene and GdScript scene
[ProcHairTest.zip](https://github.com/godotengine/godot/files/5978133/ProcHairTest.zip)

**Comment by Calinou** [comment] 2021-02-14 17:38
Duplicate of https://github.com/godotengine/godot/issues/36060. Please post your findings there as a comment.

**Closed by Calinou** 2021-02-14 17:38 UTC
Labels: discussion, topic:gdscript
