### ISSUE TITLE
crash on opening editor

### ISSUE THREAD

**Issue by tofuhead** [godotengine/godot#10824] opened 2017-08-31 16:36 UTC
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Kubuntu 17.04, Godot git master (updated just now), Nvidia  GeForce 840M, driver 375.66

**Issue description:**
when trying to open a existing project, or create a new one and editing that, it flashes the editor window and crashes immediately.

not much info on console. but this:
OpenGL ES 3.0 Renderer: GeForce 840M/PCIe/SSE2
GLES3: max ubo light: 409
GLES3: max ubo reflections: 455, ubo size: 144
[Thread 0x7fffe813e700 (LWP 12627) exited]
[Thread 0x7ffff7ff4700 (LWP 12623) exited]
[Thread 0x7fffee14e700 (LWP 12624) exited]
[Inferior 1 (process 12619) exited normally]
(gdb) ERROR: bind_methodfi: Class Script already has a method has_method
   At: core/class_db.cpp:1178.
SVG_GENERATION TIME: 0.279708
try to see fs update2
REIMPORT BECAUSE: modified resource time 0 vs 1500372002
import extension tried resource type for res://icon.png and its StreamTexture
REIMPORT BECAUSE: modified resource time 0 vs 1500373993
import extension tried resource type for res://screenshot.png and its StreamTexture
ERROR: _render_target_allocate: Condition ' status != 0x8CD5 ' is true.
   At: drivers/gles3/rasterizer_storage_gles3.cpp:6238.
REIMPORTING: res://icon.png
ERROR: operator[]: FATAL: Condition ' !e ' is true.
   At: core/map.h:604.

**Comment by novemberist** [comment] 2017-08-31 16:41
Probably the same issue as this https://github.com/godotengine/godot/issues/10815

**Comment by tofuhead** [comment] 2017-08-31 16:45
oh man, sorry it seems very similar indeed. I looked over the latest issues but didn't expect this was something about textures :) but sure, it's the same I think.

**Comment by toger5** [comment] 2017-08-31 16:54
Also fixed with #10825

**Comment by toger5** [comment] 2017-08-31 17:03
@akien-mga also can get closed

**Comment by akien-mga** [comment] 2017-08-31 17:10
Duplicate of #10815.

**Closed by akien-mga** 2017-08-31 17:10 UTC
Labels: archived
