### ISSUE TITLE
Dictionary member variable behaves like static if not initialized

### ISSUE THREAD

**Issue by pgoral** [godotengine/godot#28506] opened 2019-04-29 00:55 UTC
**Godot version:** 3.1.1

**Issue description:**
If I create class with Dictionary variable, and forget to initialize it, like this
	
```
class_name MyClass

var myDict:Dictionary
```
	
then this variable behaves like static variable. So when I create two instances of MyClass and in each one I will add one element to dictionary, then dictionary in both instances will have two items in it.

**Minimal reproduction project:**
[godotBugDictStatic.zip](https://github.com/godotengine/godot/files/3125717/godotBugDictStatic.zip)

**Comment by akien-mga** [comment] 2019-04-29 08:24
Duplicate of #24134.

**Closed by akien-mga** 2019-04-29 08:24 UTC
