### ISSUE TITLE
Inaccurate collision between Rigidbody (sphere) and StaticBody with a flat trimesh

### ISSUE THREAD

**Issue by AssimiIation** [godotengine/godot#57316] opened 2022-01-27 16:40 UTC
### Godot version

3.4.2 stable-mono-official

### System information

Win 10 GLES3 Intel-i7-10875H RTX 2060 Max-Q

### Issue description

Attempting to roll or bounce a RigidBody (sphere) across a StaticBody w/ flat trimesh collsion shape the collisions are not as anticipated. For example even though the trimesh is completely flat attempting to roll the Rigidbody will result in it "hitting bumps" and often deflecting from it's path. Bounces also often result in deflection and greatly reducing linear velocity.

Note - the vertex count of the StaticBody trimesh must be quite high. Lower vertex count trimeshes will not accurately reproduce the bug

### Steps to reproduce

Create a RigidBody with a sphere collision shape and StaticBody with a collision shape that is a flat trimesh (with high vertex count). Use ApplyCentralImpulse() to "roll" the RigidBody across the StaticBody and observe the unexpected bounces/deflections.

An example project is included below. Three StaticBodies are present with trimeshes generated from Zyllan's terrain add-on at different LOD values (1 - highest vertex count, 5 - medium vertex count, 10 - lowest vertex count). The individual collision meshes can be tested by making sure all other StaticBody's CollisionShape > Disabled property is checked ( it also helps visually to hide the unused StaticBodies ). Notice as the vertex count of the trimesh collision shape increases the erroneous collisions between RigidBody/StaticBody increase in frequency. The last StaticBody included uses a trimesh generated from a cube and has a very low vertex count - it most closely demonstrates what "expected" collisions should be.

It will help to ensure Debug > Visible Collision Shapes is checked as well as View Information being checked in the editor's camera perspective menu (for showing vertex counts.

### Minimal reproduction project

[Trimesh Collision Bug Report.zip](https://github.com/godotengine/godot/files/7952225/Trimesh.Collision.Bug.Report.zip)

**Comment by Calinou** [comment] 2022-01-27 16:49
Duplicate of https://github.com/godotengine/godot/issues/46596 and/or https://github.com/godotengine/godot/issues/50463.

**Closed by Calinou** 2022-01-27 16:49 UTC
Labels: bug, topic:physics, topic:3d
