### ISSUE TITLE
GridContainer in CenterContainer => Godot freez and take 100% of cpu

### ISSUE THREAD

**Issue by tperraut** [godotengine/godot#17956] opened 2018-04-04 07:14 UTC
**Godot version:**
Godot 3.0.2 AUR build version

**OS/device including version:**
Archlinux
intel graphics

**Issue description:**
When I switch a GridContainer in a CenterContainer, Godot freez and take 100% of cpu

**Steps to reproduce:**
Switch a GridContainer in a CenterContainer

**Minimal reproduction project:**
![capture d ecran_2018-04-04_09-13-07](https://user-images.githubusercontent.com/9951059/38293605-74535b50-37e8-11e8-91c0-badbc1c85c0c.png)

**Comment by groud** [comment] 2018-04-04 08:05
This is a duplicate of #17389, which has been fixed on master branch.

**Closed** 2018-04-04 08:05 UTC
Labels: archived
