### ISSUE TITLE
V-sync setting isn't saved

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#10725] opened 2017-08-28 16:05 UTC
Godot 3.0 master
Windows 10 64 bits
nVidia 940M

"use vsync" is true by default, so I wanted to disable it in my project. Then I closed the settings and closed the editor.
When I open the editor again, "use vsync" is still set to true.
`project.godot` was left unchanged.

**Comment by akien-mga** [comment] 2017-08-28 16:10
Duplicate of #10712.

**Closed by akien-mga** 2017-08-28 16:10 UTC

**Comment by mikeandtherest** [comment] 2017-12-11 07:16
Hi guys. Made the switch this night from Godot 2.1.4 to Godot 3.0 beta1_win 64. I'm not Win 10 Pro x64, with the latest driver for a GTX 780Ti. 
The actual persistence of the setting is now fixed, but with Vsync Off it still caps at 60 fps if I run the game and look in the Debugger -> Monitors panel. So it doesn't seem to take the setting into account by some reason. In 2.1.4 for the same 2D scene, without Vsync, I get 1000+ FPS.
