### ISSUE TITLE
Property "layout_mode" constantly removed and added

### ISSUE THREAD

**Issue by Cronos87** [godotengine/godot#67129] opened 2022-10-09 12:18 UTC
### Godot version

4.0.beta2

### System information

macOS Monterey 12.3.1

### Issue description

When running the game from the Godot Editor, the property `layout_mode` for the scenes opened in Godot tabs will be removed or added.

The expected behavior is to not remove/add the property `layout_mode`.

Here's a video to illustrate it:

https://user-images.githubusercontent.com/1923206/194756160-4c159262-77aa-4c4b-9394-cf9483652858.mp4

### Steps to reproduce

1) Open the sample project and open the 2 scenes included inside `test_layout_mode` and `another_scene`.
2) Check that the property `layout_mode` exists in `test_layout_mode` for almost all nodes.
3) Go to the scene `another_scene` and run the current scene (see the image).
4) Go to the file `test_layout_mode.tscn` and you will notice that the property `layout_mode` disappear from nodes.

**Note:** If you have another scenes opened, the property will disappear as well. It seems like all scenes opened in the editor will be impacted, but not the ones closed.

![CleanShot 2022-10-09 at 14 17 07@2x](https://user-images.githubusercontent.com/1923206/194756424-8a604754-5fbf-422c-99cf-b7536a471f84.png)

### Minimal reproduction project

[Uploading Test Project Issue Layout Mode.zip…]()

**Comment by Zireael07** [comment] 2022-10-09 12:23
Duplicate of #67095

**Closed** 2022-10-09 12:25 UTC

**Comment by yohan-descours-cabaud** [comment] 2022-10-09 12:26
Oh yes indeed. Sorry I checked yesterday and didn't see any issue but I didn't think to check today 😅
By the way, I provided more information if you need to reproduced the issue.
I hope it can helps.

**Comment by Cronos87** [comment] 2022-10-09 12:27
Oh yes indeed. Sorry I checked yesterday and didn't see any issue but I didn't think to check today 😅
By the way, I provided more information if you need to reproduced the issue.
I hope it can helps.

**Comment by KoBeWi** [comment] 2022-10-09 12:34
The reproduction project didn't finish loading btw.

**Comment by Cronos87** [comment] 2022-10-09 12:38
Indeed 🤔
I just uploaded it again and seems OK now.
