### ISSUE TITLE
Crash in Theme editor Manage Theme items, Import selected with no items selected

### ISSUE THREAD

**Issue by lostminds** [godotengine/godot#77807] opened 2023-06-03 15:08 UTC
### Godot version

4.1.dev4

### System information

macOS 13.3.1

### Issue description

I was trying to add an item for Panel in my theme, not sure I figured it out, but I found a crash I can reproduce:

### Steps to reproduce

- In the Theme editor click "Manage items..."
- In the dialogue change to the "Import items" tab
- Select an item in the list (in my case Panel) but don't check any of the check boxes
- Click the "Import selected" button

Now you get an error "Alert! Nothing was selected for the import", so I figure you should probably have selected either the "Import" or "With Data" check boxes?

- Click OK in the Alert and the editor crashes.

Interestingly, I noticed that the Alert dialogue also has a window close button, and if you close the alert window using that instead of pressing OK it doesn't crash. I'd assume this sort of dialogue was supposed to be modal and would only be possible to close by pressing the OK button. Or at least closing it would be the same as pressing the OK button, and in this case at least it isn't

![Screenshot 2023-06-03 at 16 54 45](https://github.com/godotengine/godot/assets/17763524/8ecaa35c-952d-45c8-8943-83a45e1ecde4)

### Minimal reproduction project

Not project related I think. All you need to do is to use the theme editor and follow the steps above.

**Comment by RedworkDE** [comment] 2023-06-03 20:38
Duplicate of #77752

**Closed** 2023-06-04 15:55 UTC
