### ISSUE TITLE
Tooltips not updating after first set

### ISSUE THREAD

**Issue by felixkriechbaum** [godotengine/godot#70217] opened 2022-12-17 20:43 UTC
### Godot version

4.0 beta 8

### System information

Windows 11 22H2

### Issue description

As soon as I have set a tooltip with ##, it is no longer updated when I change it again.
Even if I remove the script and add it again completely. 

![image](https://user-images.githubusercontent.com/1184644/208265211-6538dd2d-71d7-43a9-a9da-3652108e0b8c.png)
![image](https://user-images.githubusercontent.com/1184644/208265220-73dc540c-d2f0-4c11-8766-a7a4511a3735.png)

After I have set a second tooltip with ##, the third tooltip is no longer displayed at all.
![image](https://user-images.githubusercontent.com/1184644/208265239-8958375b-0543-4810-8098-d851e4619f1a.png)
![image](https://user-images.githubusercontent.com/1184644/208265242-ffc0190a-3b7d-4e45-a820-57ff70191e4f.png)

After restarting the Engine, the problem was gone.
Until I want to change one of these 3 tooltips again, the same problem appears again.
Nevertheless, I do not find it unnecessary to mention such a thing.

p.s. Pardon my bad english

### Steps to reproduce

Create a blank Project Forward+.
Create a mesh, add a script and export 3 Variables.
After they appear in the Inspector, add for every variable's 3 tooltips at once and switch to the inspector again.

The first & second tooltip appear and the third is not set and not possible to change the tooltips (not updating) until restart of the engine.

### Minimal reproduction project

Since the Problem was gone, after engine restart. No reproduction project available

**Comment by hsandt** [comment] 2023-02-15 11:31
To say it otherwise:

- defining a new @export var with a tooltip already available on the first save, will properly generate the tooltip. However, changes to this tooltip, including, removal, will not be taken into account (until restart).
- defining a new @export var without a tooltip and saving, will not generate a tooltip, and prevent any further addition of tooltip (until restart).

I see that PR #71843 spot the issue being related to caching though, so it should be fixed soon!

**Comment by anvilfolk** [comment] 2023-04-17 13:43
Related: #63997!

**Comment by kinami-imai** [comment] 2023-06-21 20:33
I can reproduce on 4.0.3, but not on the latest master branch, so I think this has been fixed. The fix should be delivered with the 4.1 release.

I suggest we close this issue.

**Comment by akien-mga** [comment] 2023-06-21 20:42
- Duplicate of https://github.com/godotengine/godot/issues/63997.

**Closed by akien-mga** 2023-06-21 20:42 UTC
Labels: bug, topic:gdscript, topic:editor
