### ISSUE TITLE
Godot 4: glow effect relative radius changes with resolution

### ISSUE THREAD

**Issue by Rytelier** [godotengine/godot#65587] opened 2022-09-09 19:57 UTC
### Godot version

Godot 4 alpha 16

### System information

Vulkan

### Issue description

Glow post processing effect works independently of resolution - its relative radius will change on resolution/rendering scale change. At lower resolution, glow will appear larger than with high resolution.
![image](https://user-images.githubusercontent.com/45795134/189432961-56b7db85-120b-47cb-9d87-291aebb4ac07.png)
![image](https://user-images.githubusercontent.com/45795134/189432996-194980b5-5e7a-4dca-a030-f319fb461aec.png)

### Steps to reproduce

Create scene with environment, with glow effect enabled.
Run scene, resize the window to observe the glow appearance.

**Comment by Calinou** [comment] 2022-09-09 21:23
Duplicate of https://github.com/godotengine/godot/issues/54518.

**Closed by Calinou** 2022-09-09 21:23 UTC
