### ISSUE TITLE
The theme editor is opened only once

### ISSUE THREAD

**Issue by JekSun97** [godotengine/godot#97278] opened 2024-09-21 12:50 UTC
### Tested versions

4.3 stable, 4.4 dev2

### System information

Godot v4.4.dev2 - Windows 10.0.19045 - OpenGL 3 (Compatibility) - Radeon RX 560 Series (Advanced Micro Devices, Inc.; 31.0.14001.45012) - Intel(R) Core(TM) i5-4570 CPU @ 3.20GHz (4 Threads)

### Issue description

When we create a new theme for any Control node, clicking on the resource opens the theme editor, then if we close this editor, the theme editor can no longer be opened by clicking on the resource in the inspector.
![scr](https://github.com/user-attachments/assets/14cab29b-3670-4ff5-a17e-e34b0819df56)

However, we can open the theme editor if we select the theme in the file manager

### Steps to reproduce

1. Create a new theme for any Control node
2. Select this theme in the inspector to open the theme editor
3. Close the theme editor
4. Repeat step 2 and the theme editor will not open

### Minimal reproduction project (MRP)

N/A

**Comment by JekSun97** [comment] 2024-09-21 16:21
@AThousandShips  Isn't this a mistake?

**Comment by AThousandShips** [comment] 2024-09-21 16:23
I have no clue? I haven't tagged this as anything nor have I done any triage on this

**Comment by JekSun97** [comment] 2024-09-21 16:26
Could you please mark this as a bug? Usually the issues that are marked as a bug are the ones that are prioritized for fixing

**Comment by AThousandShips** [comment] 2024-09-21 16:28
Calm down and be patient, I'm not working right now, it's the weekend, and I'm not the only one who does bug triage

**Comment by AThousandShips** [comment] 2024-09-22 09:38
Can confirm this behavior, however it is the same with other editors in the bar, so unsure if this is intentional or a bug, will see what the relevant teams think

**Comment by shahriarlabib000** [comment] 2024-09-22 18:01
I don't think it's intentional cause if you clear theme and add a new one the preview still doesn't open.
Here is a branch that sort of fixes it but not really https://github.com/shahriarlabib000/godot/tree/theme

- Still have to figure out a way to detect when the preview is closed.
- have to do something about the inspector theme expand/contract thing. Otherwise you have to press the theme twice.

Here is a video:
https://github.com/user-attachments/assets/82847276-fb3f-4084-93fa-9b8c345608b0

But idk if this is the right way to do it or if this is intended behavior or not so sorry for that

**Comment by AThousandShips** [comment] 2024-09-22 18:04
It'd be good to identify when this was changed if it was different in the past

But that solution doesn't look right it shows it regardless of the theme is valid, and `edit` can be called in some cases

**Comment by shahriarlabib000** [comment] 2024-09-22 18:08
I can confirm this much that this is Reproducible in 4.2.2.stable

**Comment by shahriarlabib000** [comment] 2024-09-22 18:24
How can I create an invalid theme kinda curious what will happen

**Comment by AThousandShips** [comment] 2024-09-22 20:30
You don't, `edit` can be called with `nullptr`, it's done to clear things

**Comment by JekSun97** [comment] 2024-09-23 20:29
> It'd be good to identify when this was changed if it was different in the past

I can't check it yet, but I definitely remember that this behavior didn't happen in 3.x, since I often switched between nodes and called the theme editor in this way

**Comment by JekSun97** [comment] 2024-09-24 09:16
As it turned out, this is indeed the case, in 3.x there is no such problem, most likely this is an old error that arose in 4.0, I doubt that this behavior is intended on purpose, because if we do not save this topic to disk, we will not be able to open it until we reload the project

https://github.com/user-attachments/assets/e9e509b4-3e05-4cb9-b634-785b0d4e445c

**Comment by shahriarlabib000** [comment] 2024-09-25 05:57
I think the close button was added in 4.2

**Comment by AThousandShips** [comment] 2024-09-27 08:47
This is not my area so I can't comment on this

**Comment by AThousandShips** [comment] 2024-09-27 10:20
@JekSun97 To clarify, as we've discussed different things in this thread, and there's no clear instructions, do you mean the "Close" button in the theme editor, or closing the theme editor from the bottom bar?

**Closed** 2024-10-04 20:46 UTC
Labels: bug, topic:editor, confirmed, usability
