### ISSUE TITLE
VisualServer::material_get_param() returns wrong default value

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#20291] opened 2018-07-19 23:33 UTC
Godot 3.0.5
Windows 10 64 bits
GeForce GTX 1060 6GB/PCIe/SSE2

Repro steps:
1) Create a shader containing a uniform with a default value
2) Create a new `ShaderMaterial` and assign the shader to it:
notice that despite the renderer applies the default value, the inspector shows a wrong value.

This also means scripts using `VisualServer::material_get_param()` will not get the default value either until it is manually set...
In my use case that means the inspector of my custom node shows wrong initial values in its `Shading` section.

**Comment by akien-mga** [comment] 2018-09-01 10:06
Confirmed in the current master branch, all uniforms appear with default 0 values of their type in the "Shader param" section, even though the default value set in the shader is applied.

If you change the value, there is no indication that you overrode the default (no "revert" icon), and you can't get back to following the default value either (resetting to "0" means actually setting 0 as the uniform value).

**Comment by akien-mga** [comment] 2018-09-09 17:55
Closing as duplicate of #17887.

**Closed by akien-mga** 2018-09-09 17:55 UTC
Labels: bug, topic:rendering
