### ISSUE TITLE
Editor does not show anything apart form splash screen for some projects

### ISSUE THREAD

**Issue by javiermtorres** [godotengine/godot#42608] opened 2020-10-06 22:09 UTC
**Godot version:**

3.2.3 stable mono win64

**OS/device including version:**

Win10 on Intel i5 4200U, Intel HD4400 (driver v20.19.15.5144), 8GB RAM, GLES3

**Issue description:**

The project manager starts. For newly created projects, the editor works as expected. But for e.g. the FPS tutorial, the editor does not show anything beside the splash screen. There are some hints indicating that the GUI works (pressing Alt+F4 causes the window icon in the bar to blink and shine, as if waiting for input), but nothing beside the splash window is shown. Resizing the editor window does not fix the issue. Memory does not seem to be an issue (~60% memory usage). The editor is not shown to use the GPU according to the task manager. Weirdly enough, *running* the project does work as intended.

**Steps to reproduce:**
Just open the FPS tutorial project.

**Minimal reproduction project:**

The FPS tutorial here: https://docs.godotengine.org/es/stable/_downloads/2512b12c1dd54cded37bd8c18fc4ecff/Godot_FPS_Starter.zip

**Comment by javiermtorres** [comment] 2020-10-06 22:13
Starting with -v shows the following:

C:\Users\jmtor>cd LocalDocs\Godot_v3.2.3-stable_mono_win64

C:\Users\jmtor\LocalDocs\Godot_v3.2.3-stable_mono_win64>dir
 El volumen de la unidad C no tiene etiqueta.
 El número de serie del volumen es: 3AE1-4710

 Directorio de C:\Users\jmtor\LocalDocs\Godot_v3.2.3-stable_mono_win64

17/09/2020  08:55    <DIR>          .
17/09/2020  08:55    <DIR>          ..
16/09/2020  17:34    <DIR>          GodotSharp
17/09/2020  08:55        70.594.968 Godot_v3.2.3-stable_mono_win64.exe
               1 archivos     70.594.968 bytes
               3 dirs  16.043.790.336 bytes libres

C:\Users\jmtor\LocalDocs\Godot_v3.2.3-stable_mono_win64>Godot_v3.2.3-stable_mono_win64.exe -v
Godot Engine v3.2.3.stable.mono.official - https://godotengine.org
Using GLES3 video driver
OpenGL ES 3.0 Renderer: Intel(R) HD Graphics 4400
WASAPI: wFormatTag = 65534
WASAPI: nChannels = 2
WASAPI: nSamplesPerSec = 48000
WASAPI: nAvgBytesPerSec = 384000
WASAPI: nBlockAlign = 8
WASAPI: wBitsPerSample = 32
WASAPI: cbSize = 22
WASAPI: detected 2 channels
WASAPI: audio buffer frames: 1962 calculated latency: 44ms

Mono: Initializing module...
Mono JIT compiler version 6.6.0 ((no/d9001b5a)
Mono: Log file is: 'C:\Users\jmtor\AppData\Roaming/Godot/mono/mono_logs/2020_10_07 00.11.50 (6924).txt'
Mono: Runtime initialized
Mono: Loading assembly mscorlib...
Mono: Assembly mscorlib loaded from path: C:\Users\jmtor\LocalDocs\Godot_v3.2.3-stable_mono_win64/GodotSharp/Mono/lib/mono/4.5/mscorlib.dll
Mono: Loading scripts domain...
Mono: Creating domain 'GodotEngine.Domain.Scripts'...
Mono: INITIALIZED
Mono: Loading assembly GodotSharp...
Mono: Assembly GodotSharp loaded from path: C:\Users\jmtor\LocalDocs\Godot_v3.2.3-stable_mono_win64/GodotSharp/Api/Debug/GodotSharp.dll
Mono: Loading assembly GodotSharpEditor...
Mono: Assembly GodotSharpEditor loaded from path: C:\Users\jmtor\LocalDocs\Godot_v3.2.3-stable_mono_win64/GodotSharp/Api/Debug/GodotSharpEditor.dll
Mono: Loading assembly GodotTools...
Mono: Assembly GodotTools loaded from path: C:\Users\jmtor\LocalDocs\Godot_v3.2.3-stable_mono_win64/GodotSharp/Tools/GodotTools.dll
Mono: Loading assembly GodotTools.ProjectEditor...
Mono: Assembly GodotTools.ProjectEditor loaded from path: C:\Users\jmtor\LocalDocs\Godot_v3.2.3-stable_mono_win64/GodotSharp/Tools/GodotTools.ProjectEditor.dll
CORE API HASH: 13116283933631344335
EDITOR API HASH: 6348957170305068143
Loading resource: C:\Users/jmtor/AppData/Roaming/Godot/editor_settings-3.tres
EditorSettings: Load OK!
EditorSettings: Save OK!
Loaded builtin certs
Editing project: C:/Users/jmtor/LocalDocs/Godot_FPS_Part_1_FAILING (C:::Users::jmtor::LocalDocs::Godot_FPS_Part_1_FAILING)
EditorSettings: Save OK!
GodMono: Finalizing scripts domain...
ot Engine v3.2.3.stable.mono.official - httpMso:n/o:/ gUonldooatdienngg isncreip.tosr gd
omain...
Mono: Runtime cleanup...
Mono: Finalized
Using GLES3 video driver
OpenGL ES 3.0 Renderer: Intel(R) HD Graphics 4400

C:\Users\jmtor\LocalDocs\Godot_v3.2.3-stable_mono_win64>WASAPI: wFormatTag = 65534
WASAPI: nChannels = 2
WASAPI: nSamplesPerSec = 48000
WASAPI: nAvgBytesPerSec = 384000
WASAPI: nBlockAlign = 8
WASAPI: wBitsPerSample = 32
WASAPI: cbSize = 22
WASAPI: detected 2 channels
WASAPI: audio buffer frames: 1962 calculated latency: 44ms

Mono: Initializing module...
Mono JIT compiler version 6.6.0 ((no/d9001b5a)
Mono: Log file is: 'C:\Users\jmtor\AppData\Roaming/Godot/mono/mono_logs/2020_10_07 00.12.02 (11828).txt'
Mono: Runtime initialized
Mono: Loading assembly mscorlib...
Mono: Assembly mscorlib loaded from path: C:\Users\jmtor\LocalDocs\Godot_v3.2.3-stable_mono_win64/GodotSharp/Mono/lib/mono/4.5/mscorlib.dll
Mono: Loading scripts domain...
Mono: Creating domain 'GodotEngine.Domain.Scripts'...
Mono: INITIALIZED
Mono: Loading assembly GodotSharp...
Mono: Assembly GodotSharp loaded from path: C:/Users/jmtor/LocalDocs/Godot_FPS_Part_1_FAILING/.mono/assemblies/Debug/GodotSharp.dll
Mono: Loading assembly GodotSharpEditor...
Mono: Assembly GodotSharpEditor loaded from path: C:/Users/jmtor/LocalDocs/Godot_FPS_Part_1_FAILING/.mono/assemblies/Debug/GodotSharpEditor.dll
Mono: Loading assembly GodotTools...
Mono: Assembly GodotTools loaded from path: C:\Users\jmtor\LocalDocs\Godot_v3.2.3-stable_mono_win64/GodotSharp/Tools/GodotTools.dll
Mono: Loading assembly GodotTools.ProjectEditor...
Mono: Assembly GodotTools.ProjectEditor loaded from path: C:\Users\jmtor\LocalDocs\Godot_v3.2.3-stable_mono_win64/GodotSharp/Tools/GodotTools.ProjectEditor.dll
Mono: Loading assembly GodotTest...
Mono: Failed to load project assembly
CORE API HASH: 13116283933631344335
EDITOR API HASH: 6348957170305068143
Loading resource: res://default_env.tres
Construct gdnative interface

Destruct gdnative interface

Class 'BulletPhysicsDirectBodyState' is not exposed, skipping.
Class 'BulletPhysicsDirectSpaceState' is not exposed, skipping.
Class 'BulletPhysicsServer' is not exposed, skipping.
Class 'GDScriptNativeClass' is not exposed, skipping.
Class 'IP_Unix' is not exposed, skipping.
Class 'InputDefault' is not exposed, skipping.
Class 'MonoGCHandle' is not exposed, skipping.
Class 'Physics2DDirectBodyStateSW' is not exposed, skipping.
Class 'Physics2DDirectSpaceStateSW' is not exposed, skipping.
Class 'Physics2DServerSW' is not exposed, skipping.
Class 'ResourceImporterOGGVorbis' is not exposed, skipping.
Loading resource: C:\Users/jmtor/AppData/Roaming/Godot/editor_settings-3.tres
EditorSettings: Load OK!
Loaded builtin certs
EditorSettings: Save OK!
Loading resource: res://Animation_Player_Manager.gd
Loading resource: res://Player.gd
Loading resource: res://Testing_Area.tscn
Loading resource: res://Player.tscn
Loading resource: res://assets/Colors.material
Loading resource: res://assets/GodotBattleBot_Colors.png
Loading resource: res://assets/Emission.material
Loading resource: res://assets/GunTextures.png
Loading resource: res://assets/GunMaterial.material
Loading resource: res://assets/MuzzleFlash.material
Loading resource: res://assets/Gun_Emission.material
Loading resource: res://assets/32-32_white.png
Loading resource: res://assets/Titillium-Regular.otf

**Comment by bmolyneaux** [comment] 2020-10-08 04:16
I couldn't reproduce this issue with 3.2.3 stable (no Mono) on Windows.

**Comment by javiermtorres** [comment] 2020-10-08 06:39
I'm fairly sure it must be quite specific, but after ruling out the usual suspects (memory, drivers), I'd need to gather more info. Is there a way to get more tracing? Or do I need to debug the editor?

**Comment by javiermtorres** [comment] 2020-10-08 06:41
> I couldn't reproduce this issue with 3.2.3 stable (no Mono) on Windows.

I get the same results without Mono 🙁

**Comment by akien-mga** [comment] 2020-10-08 06:49
Sounds like https://docs.godotengine.org/en/stable/about/troubleshooting.html#everything-i-do-in-the-editor-or-project-manager-appears-delayed-by-one-frame, try to upgrade to the latest Intel drivers **provided by Intel** for 4th gen HD 4400, not by Windows Updates or your computer vendor.

The latest one seems to be https://downloadcenter.intel.com/download/29804/Intel-Graphics-Driver-for-Windows-15-40-?product=81497

**Comment by javiermtorres** [comment] 2020-10-08 07:31
I already have that exact version 🙁 Plus, Godot does not draw even if I change tabs, click on other applications. It's quite weird that it only happens in the FPS tutorial but not in a newly created project.

**Comment by javiermtorres** [comment] 2020-10-23 17:07
Starting the project from the command line, the editor starts if I use GLES2, but then it spews lines like this:

ERROR: _gl_debug_print: GL ERROR: Source: OpenGL        Type: Error     ID: 1282        Severity: High  Message: Error has been generated. GL error GL_INVALID_OPERATION in (null): (ID: 173538523) Generic error

Fortunately the editor seems to work ok for the moment. I'll try to work with GLES2 as much as I can. But I'd really want to know where the error comes from. Where would be the most promising place to debug? Thanks in advance.

**Comment by Zireael07** [comment] 2020-10-23 18:16
@javiermtorres: In that case, it's likely your drivers that are the problem, not Godot...

**Comment by Calinou** [comment] 2020-10-23 18:55
As a workaround, try starting the Godot editor with the `--verbose` command-line argument or enable **Update Continuously** in the Editor Settings.

**Comment by SmTheDev** [comment] 2021-05-26 09:36
Unfortunately, its not just the FPS tutorial, any project that has a few scenes and scripts will begin to run in the background while the splash screen is still there, I found this out after running my Main Menu Scene.
After the splash screen wouldn't go away, I decided to click where I knew my play button was. Surprisingly, it printed to the console that the button was pressed. So hopefully it will be addressed in the near future.

**Comment by Calinou** [comment] 2022-07-23 20:41
@javiermtorres @SmTheDev Can you (or anyone else) still reproduce this bug in [Godot 3.4.4](https://godotengine.org/article/maintenance-release-godot-3-4-4) or any later release?

If yes, please ensure that an up-to-date Minimal Reproduction Project (MRP) is included in this report (a MRP is a zipped Godot project with the minimal elements necessary to reliably trigger the bug). You can upload ZIP files in an issue comment with a drag and drop.

**Comment by Calinou** [comment] 2022-08-17 20:44
Closing due to lack of response. Please comment if you can still reproduce this bug.

PS: If no [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) was included in the original bug report, please upload one as well to ease troubleshooting.

**Closed by Calinou** 2022-08-17 20:44 UTC
Labels: bug, topic:editor, needs testing
