### ISSUE TITLE
Process mode enum still isn't updated by project converter

### ISSUE THREAD

**Issue by Koopa1018** [godotengine/godot#78965] opened 2023-07-03 02:28 UTC
### Godot version

v4.1.beta1.official [828ec2c5d]

### System information

Godot v4.1.beta1 - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 2070 SUPER (NVIDIA; 30.0.14.7247) - AMD Ryzen 7 3700X 8-Core Processor (16 Threads)

### Issue description

When converting our project from 3.5 to 4.1, we found that many nodes' `pause_mode = 2` property (`PAUSE_MODE_PROCESS`) was incorrectly updated to `process_mode = 2` (`PROCESS_MODE_WHEN_PAUSED`) instead of `process_mode = 3` (`PROCESS_MODE_ALWAYS`).

It looks like this bug was already reported in #74845 and should have been fixed by #76179, but it still seems to be broken as of 4.1rc1? The contributing guidelines don't say what to do in this case; if you'd rather I comment on that issue or its PR instead of opening a new issue, just let me know.

### Steps to reproduce

1. Open repro project in 3.5.*. Open TestScene.tscn and observe that the AnimationPlayer's pause mode is "Process."
2. Convert project to 4.1.*. Observe that AnimationPlayer's process mode is now "When Paused."

### Minimal reproduction project

[GD4 Pause Mode Convert.zip](https://github.com/godotengine/godot/files/11932320/GD4.Pause.Mode.Convert.zip)

**Comment by Maran23** [comment] 2023-07-03 06:33
You are using `Godot v4.1 beta1`, which was released 4 weeks ago. 
But my fix was merged only 2 weeks ago and is therefore not included in this version.

I just tried it with the newest `Godot v4.1 RC-2` which was released some days ago and everything works. 
You can download it here: https://godotengine.org/article/release-candidate-godot-4-1-rc-2/

**Comment by kleonc** [comment] 2023-07-03 06:44
Duplicate of #74845 (fixed since `v4.1.beta3`).

**Closed by kleonc** 2023-07-03 06:44 UTC
