### ISSUE TITLE
Inspector focus next Tab key not working

### ISSUE THREAD

**Issue by cgbeutler** [godotengine/godot#58523] opened 2022-02-25 07:38 UTC
### Godot version

3.4.3.rc2_mono_win64

### System information

Windows 10

### Issue description

The inspector no longer seems to respect the tab key to go to the next field.
Color editing panel doesn't either.
I tried creating a brand new project, in case it was a plugin or something, but the issue persists.

### Steps to reproduce

Create a new scene with a Node2D.
Bring up the node in the inspector.
Click the transform position x field.
Hit tab.
Expect it to go to the next field, it does not.

### Minimal reproduction project

N/A

**Comment by cgbeutler** [comment] 2022-02-25 07:39
Seems like a big issue. There is a slight chance this is a duplicate, but I couldn't find it in my cursory search.

**Comment by akien-mga** [comment] 2022-02-25 09:15
Indeed that was a regression in 3.4.3 RC 2, fixed since.

Duplicate of #58460

**Closed by akien-mga** 2022-02-25 09:15 UTC
