### ISSUE TITLE
Window zoom menu items in German on English OS

### ISSUE THREAD

**Issue by AnmAtAnm** [godotengine/godot#58328] opened 2022-02-19 21:11 UTC
### Godot version

Godot Engine v4.0.alpha2.official.79077e6c1

### System information

MacOS 11.6, Vulkan API 1.1.198 - Using Vulkan Device #0: AMD - AMD Radeon Pro 5500M

### Issue description

When the user hovers the mouse cursor over the window's green zoom button (both editor window and project dev builds), the menu items are in German.

Expected:
<img width="249" alt="Screen Shot 2022-02-19 at 1 05 12 PM" src="https://user-images.githubusercontent.com/9916202/154819095-e21a3c52-f75e-46ee-aec3-46c8f0da0b4b.png">

Actual:
<img width="403" alt="Screen Shot 2022-02-19 at 1 08 29 PM" src="https://user-images.githubusercontent.com/9916202/154819138-39896a6a-6b5b-481f-a680-16dbe1226207.png">

### Steps to reproduce

1. Open Godot.app on English Mac (possibly any non-German).
2. Hover mouse cursor over the editor window's green Zoom button, in upper left/start of window.
3.  Note the menu items in German.

**Comment by Calinou** [comment] 2022-02-19 21:24
@AnmAtAnm Can you reproduce this in 3.4.2?

cc @bruvzg

**Comment by bruvzg** [comment] 2022-02-19 21:26
Duplicate of #58000, should be already fixed by #58001.

**Closed** 2022-02-19 21:33 UTC
Labels: bug, platform:macos, topic:editor, topic:porting
