### ISSUE TITLE
Godot keeps running after determining there is no support for vulkan.

### ISSUE THREAD

**Issue by MiniAlfa** [godotengine/godot#58475] opened 2022-02-23 18:31 UTC
### Godot version

4.0

### System information

windows 10

### Issue description

When running Godot 4.0 on my PC which does not support Vulkan, an error is displayed. 
![godot](https://user-images.githubusercontent.com/39923434/155383865-764ddfd7-4548-4c05-85d8-a24a8309803c.PNG)

**But Godot keeps running in the background after confirming the error.** 
Removing the app will then require restarting the PC.

### Steps to reproduce

1. Open godot on pc without vulkan support
2. Press OK on the error message
3. Try deleting the godot file

**Comment by Zireael07** [comment] 2022-02-23 18:34
dupe of #58414 ?

**Closed** 2022-02-23 18:44 UTC
