### ISSUE TITLE
ResourceLoader setting `noCache` is ignored for nested resources

### ISSUE THREAD

**Issue by derkork** [godotengine/godot#59686] opened 2022-03-30 07:06 UTC
### Godot version

v3.4.4.stable.mono.official [419e713a2]

### System information

Manjaro Linux

### Issue description

Assume you have a custom resource that contains nested resources:

```csharp
public class SomeResource : Resource
{
    [Export()]
    public NestedResource NestedResource {get; set;}
}

public class NestedResource : Resource
{
        [Export]
        // this is a Godot dictionary
        public Dictionary<string, string> Foo = new Dictionary<string, string>();
}
```
When you load such a resource like this:

```csharp
private static SomeResource DoLoad()
{
    return ResourceLoader.Load("res://narf.tres", noCache: true) as SomeResource;
}
```
then the nested resource will still be cached even if `noCache`  is set to `true`. 

### Steps to reproduce

Run `save_load_test.tscn` in the attached project. It will do the following things:

1. Create an instance if `SomeResource` and fill its nested resource with values.
2. Save this instance to a `.tres`  file with `ResourceSaver`.
3. Load the resource again with `noCache` true and compare the values.
4. Create another instance of `SomeResource`  and fill its nested resource with different values.
5. Save this instance over the same `.tres`  file as in step 2.
6. Load the resource again with `noCache` true and compare the values.

In step 6 the comparison will fail as the nested resource is still cached and has the values from step 1 instead the values from step 4.

### Minimal reproduction project

C#
[cache.zip](https://github.com/godotengine/godot/files/8377885/cache.zip)

GDScript
[cache_test_gdscript.zip](https://github.com/godotengine/godot/files/8386361/cache_test_gdscript.zip)

**Comment by derkork** [comment] 2022-03-30 07:16
Probably caused by https://github.com/godotengine/godot/blob/3.4.4-stable/core/io/resource_loader.cpp#L253 as the `p_no_cache` flag is not given to the `ResourceFormatImporters` (the parameter is actually unused).  Recursive loading calls in https://github.com/godotengine/godot/blob/3.4.4-stable/core/io/resource_importer.cpp#L131 will then be just made with `p_no_cache`  = `false`.

**Comment by Calinou** [comment] 2022-03-30 21:10
Related to https://github.com/godotengine/godot/issues/59669.

Please create a minimal reproduction project in GDScript instead of C# for two reasons:

- Non-Mono builds of Godot are easier to set up and have less moving parts.
- This rules out C# being the cause of the bug.

**Comment by derkork** [comment] 2022-03-31 05:55
Thank you for having a look into this. I have attached a GDScript version of the reproduction project.

**Comment by akien-mga** [comment] 2022-08-05 21:44
Fixed by #62408.

**Closed by akien-mga** 2022-08-05 21:44 UTC
Labels: bug, topic:core, confirmed
