### ISSUE TITLE
Parser bug (please report): Trying to check compatibility of unset value type

### ISSUE THREAD

**Issue by 1xch** [godotengine/godot#62219] opened 2022-06-19 14:09 UTC
### Godot version

4.0.alpha10.official.4bbe7f0b9

### System information

Linux Ubuntu 20.04

### Issue description

I get about 30-40 instances of:

```
ERROR: Parser bug (please report): Trying to check compatibility of unset value type
   at: is_type_compatible (modules/gdscript/gdscript_analyzer.cpp:4037)
```
when running through the editor. Examining the error shows that its popping up at gdscript 'load' function e.g.:

```
# load("res://addons/worker/bin/loader.gd")   # used once to a script that handles loading
# load(Dir.full_path(dir,fil))                              # full path of directory and file 
# load(p)                                                        # p is a string of a path
```
ok. So trying to work through it I created a function:

```
static func xoad(p:String) -> Resource:
	var x = ResourceLoader.load_threaded_request(p, "", true)
	if x != OK:
		prints("lload xrror", p)
		return null
	var tls = ResourceLoader.THREAD_LOAD_IN_PROGRESS
	while tls == ResourceLoader.THREAD_LOAD_IN_PROGRESS:
		tls = ResourceLoader.load_threaded_get_status(p)
	prints("lload result", p, "==", tls)
	if tls == ResourceLoader.THREAD_LOAD_FAILED:
		prints("lload xrror", p)
		return null
	if tls == ResourceLoader.THREAD_LOAD_LOADED: 
		var res = ResourceLoader.load_threaded_get(p)
		print(res)
		return res
	else:
		return null
```
to handle loading like this now:
```
LL.xoad("res://addons/worker/bin/loader.gd")
```
it does eliminate the previous editor error, but seemingly replaces it with:
```
E 0:00:08:0268   is_type_compatible: Parser bug (please report): Trying to check compatibility of unset value type
  <C++ Error>    Condition "!p_source.is_set()" is true. Returning: true
  <C++ Source>   modules/gdscript/gdscript_analyzer.cpp:4037 @ is_type_compatible()
```
while I still get the previous error in the terminal, but doesn't appear to bubble up to the editor.

I decided to tackle this as I'm having a signaling issue I don't know if it is related so I thougth I'd try to get this first in case its causing further issues for me. To be clear the above isn't breaking, app still runs. 

### Steps to reproduce

Running an app with F5.

### Minimal reproduction project

I will try to get this, seems like a thing to try if the above is not informative enough to start.

**Comment by Chaosus** [comment] 2022-06-19 14:29
Duplicate of https://github.com/godotengine/godot/issues/44375

**Closed by Chaosus** 2022-06-19 14:29 UTC
