### ISSUE TITLE
Blender Import Fail

### ISSUE THREAD

**Issue by nano13** [godotengine/godot#80052] opened 2023-07-30 11:01 UTC
### Godot version

v4.2.dev.custom_build [75f9c97de]

### System information

Godot v4.2.dev (75f9c97de) - Arch Linux #1 SMP PREEMPT_DYNAMIC Mon, 24 Jul 2023 20:19:38 +0000 - X11 - Vulkan (Forward+) - dedicated AMD Radeon RX 5500 XT () - AMD Ryzen 7 2700X Eight-Core Processor (16 Threads)

### Issue description

Related to
https://github.com/godotengine/godot/issues/80049
https://github.com/godotengine/godot/issues/80051

Check out this project and try to load it up:
https://github.com/nano13/GodotFirstPersonController/tree/main

```
ERROR: Condition "err != OK" is true. Returning: ERR_FILE_CANT_OPEN
   at: append_from_file (modules/gltf/gltf_document.cpp:7447)
ERROR: Error importing 'res://Models/suzuki_motorbike_wheel_front.blend'.
   at: _reimport_file (editor/editor_file_system.cpp:2044)
Blender 3.6.0 (hash c7fc78b81ecb built 2023-07-07 13:20:07)
Read prefs: "/home/samuel/.config/blender/3.6/config/userpref.blend"
Read blend: "/home/samuel/programmierung/godot/GodotFirstPersonController/Models/suzuki_motorbike_wheel_rear.blend"
Error: Python: Traceback (most recent call last):
  File "<string>", line 9, in <module>
  File "/usr/share/blender/3.6/scripts/modules/bpy/ops.py", line 113, in __call__
    ret = _op_call(self.idname_py(), None, kw)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Converting py args to operator properties: : keyword "export_nla_strips" unrecognized

Blender quit
```

### Steps to reproduce

Check out the aforementioned project and try to load it up:

https://github.com/nano13/GodotFirstPersonController/tree/main

### Minimal reproduction project

Check out the aforementioned project and try to load it up:

https://github.com/nano13/GodotFirstPersonController/tree/main

**Comment by AThousandShips** [comment] 2023-07-30 11:12
Looks like a duplicate of:
* #76338

**Comment by nano13** [comment] 2023-07-30 11:17
> Looks like a duplicate of (it also applies to 3.6, see comments):
> 
>     * [Failure to import `.blend` with Blender 3.5 #76338](https://github.com/godotengine/godot/issues/76338)

True, looks very similar.

**Comment by AThousandShips** [comment] 2023-07-30 11:18
Duplicate of #76338

**Closed by AThousandShips** 2023-07-30 11:18 UTC
