### ISSUE TITLE
Exported Array with set function size in tool script gets reset to 0 after closing and reopening the editor

### ISSUE THREAD

**Issue by BanchouBoo** [godotengine/godot#66615] opened 2022-09-29 18:31 UTC
### Godot version

4.0.beta2.official.f8745f2f7

### System information

Void Linux

### Issue description

I have a tool script that has an exported array and a set function, when I close and reopen the editor (or the scene if it's a built-in resource rather than it's own file) the size of the array gets reset to 0. With an identical script that doesn't have `@tool`, the array does *not* get reset. It also does not reset if it is a tool script but has no set function. The values within the array are still stored properly in the resource file until after spending some time in the editor modifying and saving stuff.

### Steps to reproduce

This is the script in question that I'm trying to use.
```gdscript
@tool
class_name PaletteTexture
extends ImageTexture

@export var palette: Array[Color]:
    set(new_palette):
        palette = new_palette
        if Engine.is_editor_hint():
            var data = PackedByteArray()
            for color in palette:
                data.append(color.r8)
                data.append(color.g8)
                data.append(color.b8)
                data.append(color.a8)
            image = Image.new()
            image.create_from_data(palette.size(), 1, false, Image.FORMAT_RGBA8, data)
            self.set_image(image)
@export var image: Image
```

### Minimal reproduction project

[export_array_bug.zip](https://github.com/godotengine/godot/files/9678122/export_array_bug.zip)

**Comment by Calinou** [comment] 2022-09-29 22:29
Duplicate of https://github.com/godotengine/godot/issues/62753.

**Closed by Calinou** 2022-09-29 22:29 UTC
