### ISSUE TITLE
[4.0.beta9] "INSTALL_PARSE_FAILED_NO_CERTIFICATES" error when stream-installing APKs on Android with standard build

### ISSUE THREAD

**Issue by Overvault-64** [godotengine/godot#70344] opened 2022-12-20 10:37 UTC
### Godot version

4.0.beta9

### System information

Windows 10

### Issue description

When I perform stream-install (direct deploy on debug-usb Android device) I get this error:

```
Installing to device (please wait...): Samsung SM-G935F
  editor/export/editor_export_platform.h:164 - Run: Could not install to device: adb: failed to install C:/Users/andre/AppData/Local/Godot/tmpexport.1671531696.apk: Failure [INSTALL_PARSE_FAILED_NO_CERTIFICATES: Failed to collect certificates from /data/app/vmdl579386029.tmp/base.apk: Attempt to get length of null array]
  Performing Streamed Install
```

 ![image](https://user-images.githubusercontent.com/96829602/208644511-8bddd925-ac23-4801-a7af-80ea18ebc03e.png)

Apparently fixed when ticking Use custom build in the export menu, but it wasn't necessary in Godot 3.5.1 (same project).
This issue was already present in beta6, 7 and 8.

### Steps to reproduce

1. Create a blank project with a basic scene
2. Install Android templates from the Project menu
3. Create an Android build from Project > Export (don't set anything)
4. Connect your debug-enabled Android device
5. Click on the Android icon in the upper-right corner of the editor

### Minimal reproduction project

Not necessary

**Comment by Derektamente** [comment] 2023-03-18 18:19
i think now it's called "gradle build"
![image](https://user-images.githubusercontent.com/96829602/226126560-737ec630-b434-4de0-adf3-020da2cd52e4.png)

**Comment by m4gr3d** [comment] 2023-05-30 00:31
Duplicate of https://github.com/godotengine/godot/issues/58192, should be resolved by https://github.com/godotengine/godot/pull/67668

**Closed by m4gr3d** 2023-05-30 00:31 UTC
Labels: bug, platform:android, topic:editor
