### ISSUE TITLE
Build for iOS failed with Xcode 8.1

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot#7096] opened 2016-11-11 12:35 UTC
**Operating system or device - Godot version:** macOS Sierra, Xcode 8.1 - Godot Git https://github.com/godotengine/godot/commit/7751a933a924ddd3c96369c5f54c3e60450a6d04

I'm getting this error when compiling for iOS:
```
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: archive member: modules/libmodules.iphone.opt.arm64.a(intrapred_neon_asm.iphone.opt.arm64.o) cputype (12) does not match previous archive members cputype (16777228) (all members must match)
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: archive member: modules/libmodules.iphone.opt.arm64.a(loopfilter_mb_neon.iphone.opt.arm64.o) cputype (12) does not match previous archive members cputype (16777228) (all members must match)
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: archive member: modules/libmodules.iphone.opt.arm64.a(save_reg_neon.iphone.opt.arm64.o) cputype (12) does not match previous archive members cputype (16777228) (all members must match)
Ranlib Library         ==> modules/libmodules.iphone.opt.arm64.a
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: archive member: modules/libmodules.iphone.opt.arm64.a(intrapred_neon_asm.iphone.opt.arm64.o) cputype (12) does not match previous archive members cputype (16777228) (all members must match)
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: archive member: modules/libmodules.iphone.opt.arm64.a(loopfilter_mb_neon.iphone.opt.arm64.o) cputype (12) does not match previous archive members cputype (16777228) (all members must match)
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: archive member: modules/libmodules.iphone.opt.arm64.a(save_reg_neon.iphone.opt.arm64.o) cputype (12) does not match previous archive members cputype (16777228) (all members must match)
Compiling ==> bin/tests/test_physics_2d.cpp
Compiling ==> bin/tests/test_render.cpp
scons: *** [modules/libmodules.iphone.opt.arm64.a] Error 1
scons: building terminated because of errors.
```

**Comment by vnen** [comment] 2016-11-11 12:53
Duplicate of #6849.

**Closed by vnen** 2016-11-11 12:53 UTC
