### ISSUE TITLE
Camera3D FOV not shown in Editor (Godot 4 stable)

### ISSUE THREAD

**Issue by dannygaray60** [godotengine/godot#74371] opened 2023-03-04 16:58 UTC
### Godot version

4.0 stable

### System information

Windows 10, Vulkan/Opengl, Intel HD graphics 530

### Issue description

The fov camera3d not shown in godot 4 editor, tested in Vulkan+, vulkan mobile, opengl: 
![Captura de pantalla 2023-03-03 225422](https://user-images.githubusercontent.com/30391210/222918825-173b9bbd-a2b9-499d-9678-5ce4cb3660f1.png)

In godot 3.5.1 is visible the FOV box:
![Captura de pantalla (297)](https://user-images.githubusercontent.com/30391210/222918840-4b111d25-c124-4faa-af9d-3801b147adcd.png)

### Steps to reproduce

Add camera3d node

### Minimal reproduction project

Not neccesary, it happens with empty project

**Comment by Calinou** [comment] 2023-03-19 03:44
I can't reproduce this on 4.0.stable (Linux, GeForce RTX 4090 with NVIDIA 525.89.02):

![image](https://user-images.githubusercontent.com/180032/226152382-4dbf93d0-29ca-45d7-a7ce-8826d2aea1e4.png)

Double-check your **View > Gizmos** settings at the top of the 3D editor viewport, and ensure **View Gizmos** is enabled in the **Perspective** menu.

**Comment by dannygaray60** [comment] 2023-03-20 04:38
![Captura de pantalla (305)](https://user-images.githubusercontent.com/30391210/226248269-a2dbfe0e-5133-4b55-acf8-09314f626c7a.png)
all options in "view" are enabled, maybe is a problem related to integrated graphics

**Comment by dannygaray60** [comment] 2023-07-09 21:55
The fov is working in Godot 4.1! Thanks! <3
![Captura de pantalla 2023-07-09 155438](https://github.com/godotengine/godot/assets/30391210/b32de5fe-210f-4b6b-adbe-502bb2691ff5)

**Comment by akien-mga** [comment] 2023-07-09 22:00
Great, closing as fixed then :)

**Closed by akien-mga** 2023-07-09 22:00 UTC
Labels: bug, topic:editor, needs testing, topic:3d
