### ISSUE TITLE
3D nodes position sprite icon ON/OFF switching and max size

### ISSUE THREAD

**Issue by n-pigeon** [godotengine/godot#748] opened 2014-10-04 07:58 UTC
Some nodes like lights use sprites to display their position, but often when zooming out they become so big, compared to rest of the scene, that they are more in the way than help.

They need editable maximum size settings, and ON/OFF switching.

**Comment by akien-mga** [comment] 2015-10-31 09:33
Is this still needed in the current master branch, or has it been addressed somehow?

**Comment by n-pigeon** [comment] 2015-11-01 22:08
Nope, they are still rendered as 2D sprites covering too much space while zoomed out.

**Comment by akien-mga** [comment] 2016-03-23 12:31
Closing as a duplicate of #2792.

**Closed by akien-mga** 2016-03-23 12:31 UTC
Labels: confirmed, enhancement, topic:editor, usability
