### ISSUE TITLE
Weird vector floating point comparison bug（magic number 4.54）

### ISSUE THREAD

**Issue by kaluluosi** [godotengine/godot#63676] opened 2022-07-30 12:40 UTC
### Godot version

3.4.4.stable

### System information

Win10, Core I7-9700,RTX2080

### Issue description

I found a weird size comparison bug. The vector's x value should also be 4.54, 4.54<4.54 should return False. But godot returns True.
![image](https://user-images.githubusercontent.com/1620585/181914462-5052832a-db90-402a-a93b-32d9d8fa0372.png)
![image](https://user-images.githubusercontent.com/1620585/181914463-90429230-2655-4445-89b5-a01d966006ed.png)

I use two floats to compare, but it is not got True.
![image](https://user-images.githubusercontent.com/1620585/181914478-267d75c5-f732-4913-b99e-c60cc96e6296.png)
![image](https://user-images.githubusercontent.com/1620585/181914486-5a77de27-a378-402c-a744-bd62a94ddb41.png)

I thought any same number Vector2‘s member variant will less than float one. But i'm wrong.
There just 4.54 has the strange result.
![image](https://user-images.githubusercontent.com/1620585/181914632-72a7558d-ab4e-487e-8857-9df478ceb9b4.png)
![image](https://user-images.githubusercontent.com/1620585/181914627-3ad181dd-3739-4ff7-ac68-5ee892793014.png)

Is someone know how it happen？

### Steps to reproduce

just look my description

**Comment by MJacred** [comment] 2022-07-30 13:12
Same happens in Godot 3.3.4

But I think this is because of the natural imprecision of floats.

try wrapping your float values with `stepify`, e.g.
```gdscript
	var v = Vector2(4.54,0)
	var stepped_vx = stepify(v.x, 0.01)
	printt(stepped_vx, 4.54, stepped_vx < 4.54)
```
returns
`4.54	4.54	False`

**Comment by TheDuriel** [comment] 2022-07-30 13:42
Classic case of: https://floating-point-gui.de/

**Comment by kleonc** [comment] 2022-07-30 14:43
Duplicate of #50022, #50251, and other similar issues.

The cause is that in GDScript (in the official releases) `Vector2` is composed of 32-bit floats (C++ `float`) but `float` is a 64-bit float (C++ `double`). Meaning docs for most (all?:thinking:) properties of type `float` kinda lie because, although their setter/getter takes in/returns 64-bit float, what's really stored is a 32-bit float.

If anything, it's a documentation issue, users seem to notice this on and on and keep reporting it as a bug. But it's not really a bug. Not sure if/how the docs could be improved. Mentioning this 32-bit vs 64-bit thing in the docs of every float property is rather insane. And it's already mentioned in the docs of `float`:
https://github.com/godotengine/godot/blob/284dbef73347dea569437b1b8aa29bfd649e9dc8/doc/classes/float.xml#L6-L10

**Comment by TheDuriel** [comment] 2022-07-30 14:49
Iirc godot 4 was going to move the engine over to predominantly rely on doubles. Not sure what the status on that is.

The same precision errors would of course still occur, but at least we would no longer blame conversion on it.

**Comment by kleonc** [comment] 2022-07-30 15:23
cc @aaronfranke (who worked much on float/double related stuff): you might want to add/clarify something here (and probably close this issue).

**Comment by aaronfranke** [comment] 2022-07-30 16:26
This is already thoroughly documented: https://docs.godotengine.org/en/latest/classes/class_float.html

For anyone who wants to avoid this bug in the future, you can compile Godot with `float=64` to use doubles in Vector2.

**Closed by aaronfranke** 2022-07-30 16:26 UTC
Labels: archived, topic:core
