### ISSUE TITLE
3.5 rc1 editor layout loading is broken

### ISSUE THREAD

**Issue by mieldepoche** [godotengine/godot#61223] opened 2022-05-20 13:24 UTC
### Godot version

v3.5.rc1.official.e86d840d4

### System information

linux

### Issue description
Editor layout loading is broken in rc1 (things used to work fine in beta 5):
 1. you can load the default layout
 2. but to load the nth custom layout, you must press the n+1th option

Note that opening a project with a layout set in beta 5 loads the layout correctly.

### Steps to reproduce
1. create two different custom layouts
2. try loading the first one: nothing happens
4. try loading the second one: the first one is loaded

https://user-images.githubusercontent.com/71937306/169539531-de5e54a1-c725-4626-a1be-155102716531.mp4

**Comment by Calinou** [comment] 2022-05-20 13:44
Duplicate of https://github.com/godotengine/godot/issues/61179 (fixed by https://github.com/godotengine/godot/pull/61181 in the latest `3.x` branch).

**Closed by Calinou** 2022-05-20 13:44 UTC
Labels: bug, topic:editor, regression
