### ISSUE TITLE
set_drag_preview - Starting without actually dragging

### ISSUE THREAD

**Issue by Dillybob92** [godotengine/godot#4676] opened 2016-05-16 18:31 UTC
Hey guys, I have the following code inside `func _ready()`:
My scene is just a basic scene with a button.

    var MyButton = get_node("Button")
	var cpb = ColorPickerButton.new()
	cpb.set_size(Vector2(150, 150))
	MyButton.set_drag_preview(cpb)

After calling set_drag_preview and starting up my app I receive:

https://i.gyazo.com/8dfa0f45fe56b8b986a3f8d032cbfd25.gif

It seems like the drag event starts automatically but I am actually not dragging my button or even holding down my mouse to move.. Not sure if this is intended

Edit: Also, it could be any item, not just a ColorPicker

**Comment by reduz** [comment] 2016-06-17 19:26
This is actually intended, there are some clever ways you can use the drag and drop API to do complex things. @punto- used them many times.

set_drag_preview has to be used only when you are called get_drag_data() and you are intended to return anything anyway, it's no use setting it at any other time unless you know what you are doing.

Closing as this is not a bug.

**Closed by reduz** 2016-06-17 19:26 UTC
Labels: bug, topic:core
