### ISSUE TITLE
AcceptDialog crashes editor

### ISSUE THREAD

**Issue by mcihad** [godotengine/godot#56971] opened 2022-01-19 19:45 UTC
### Godot version

Godot_v4.0-dev.20220118_win64

### System information

Windows 11 RTX3050

### Issue description

If AcceptDialog is open when the game is run, the game does not close. Also, when the visible property of the AcceptDialog component is set to true, the editor freezes and can only be closed from the operating system task manager.

### Steps to reproduce

![Animation](https://user-images.githubusercontent.com/74842/150202691-5d732d9a-ad2d-4f6f-8f27-62b7e400735f.gif)

**Comment by qarmin** [comment] 2022-01-19 21:03
Please provide minimal project to reproduce bug

**Comment by mcihad** [comment] 2022-01-20 05:05
[AcceptDialogTest.zip](https://github.com/godotengine/godot/files/7902460/AcceptDialogTest.zip)
If you set the AcceptDialog component's visible property to true, it will crash.

**Comment by floppyhammer** [comment] 2022-01-20 11:28
Can confirm. But it doesn't seem like a crash, more like freezing. No crash info in the console and debugger caught nothing.

**Comment by Chaosus** [comment] 2022-01-20 13:15
Duplicate of https://github.com/godotengine/godot/issues/51362

**Closed by Chaosus** 2022-01-20 13:15 UTC
Labels: bug, topic:editor, needs testing, topic:gui
