### ISSUE TITLE
event.relative in _input-function is broken on mac os

### ISSUE THREAD

**Issue by grusad** [godotengine/godot#28017] opened 2019-04-14 15:43 UTC
**Godot version:**

3.1 stable

**OS/device including version:**

Imac 5k, AMD Radeon R9 M390

**Issue description:**

Using the code form the official FPS demo.

In the _input function I update the cameras position by the event.relative position. If i press the left mouse-button and move the mouse simultaneously i get a laggy outcome. When the left mouse button is pressed the relative position creates a huge gap and the camera snaps to the new position. This ONLY happends on mac os, on windows it works just fine!

Heres an image of the relative position and what happends to it in the _input function(event) when the left mouse button get pressed.

<img width="320" alt="Screenshot 2019-04-14 at 17 41 18" src="https://user-images.githubusercontent.com/23147905/56095384-87763d80-5edc-11e9-9057-e26e3cb3ebb8.png">

**Steps to reproduce:**
For simplicity you could use: https://github.com/TwistedTwigleg/Godot_FPS_Tutorial
and run it on a mac os.

**Minimal reproduction project:**

https://github.com/TwistedTwigleg/Godot_FPS_Tutorial

**Comment by akien-mga** [comment] 2019-04-15 10:42
CC @godotengine/macos

**Comment by bruvzg** [comment] 2019-04-15 10:57
Can't reproduce on current master and 3.1 stable, relative mouse position seems identical with or without button pressed and smooth in both cases, macOS 10.14.4 (18E226), tested with ROG Sica wired and TeckNet WM289 wireless mouse.

**Comment by grusad** [comment] 2019-04-15 14:17
well thats weird. Im using the same macOS version. I've bootcamped my imac and tested on windows aswell. On windows its all smooth, but on macOS its not.

**Comment by samgreen** [comment] 2019-04-17 23:04
@bruvzg @grusad Can you share details about the monitor you're usiing? I have a hunch this may be related to retina screen scaling.

**Comment by grusad** [comment] 2019-04-19 11:19
@samgreen Im using the 5k monitor on the iMac 27 inch. 2015 model.

**Comment by Zireael07** [comment] 2019-04-19 11:47
@grusad: Do you have DPI scaling on in Windows? In Mac?

**Comment by bruvzg** [comment] 2019-04-19 11:55
> Can you share details about the monitor you're usiing?

I'm using late 2013 Mac Pro (aka "trash can") with two 32'', 1440p Samsung displays. Displays are not HiDPI, but I'm testing all macOS staff in manually enabled 720p HiDPI mode (probably this is somewhat different from real retina display since I can't reproduce some other HiDPI related issues as well).

**Comment by samgreen** [comment] 2019-04-19 20:27
@grusad I don't have access to a 5k iMac and cannot repro on other retina screens I have tried. Would you mind changing your resolution to something closer to non-retina and testing my hunch? You can drag the slider all the way to the right in the `Displays` preferences pane from `System Preferences`.

<img width="780" alt="Screen Shot 2019-04-19 at 1 25 57 PM" src="https://user-images.githubusercontent.com/276118/56442804-db9b6c00-62a6-11e9-9599-691cc5d3f518.png">


https://www.eizoglobal.com/support/compatibility/dpi_scaling_settings_mac_os_x/

**Comment by bruvzg** [comment] 2019-04-19 20:33
In case of Mac Pro without built-in display there's no slider, but resolution list:

![Screenshot 2019-04-19 at 23 30 48](https://user-images.githubusercontent.com/7645683/56442963-3a8ad080-62fb-11e9-8431-6f3f5a00722f.png)

**Comment by grusad** [comment] 2019-04-20 05:56
<img width="666" alt="result" src="https://user-images.githubusercontent.com/23147905/56453343-852f3b80-6341-11e9-9bde-7f941e697b80.png">
As default i had the "Defauly for display" checked. I can now confirmt hat the options in the green rect solves the problem, and the ones in the red rect gives the same problem as if i had the "Default for display" checked.

**Comment by samgreen** [comment] 2019-04-24 20:44
Thanks, I have a plan for a fix on this one.

**Comment by KoBeWi** [comment] 2020-08-20 23:18
Can anyone still reproduce this bug in [Godot 3.2.3 rc3](https://godotengine.org/article/release-candidate-3-2-3-rc-3) or any later release?

**Comment by akien-mga** [comment] 2020-12-10 16:09
No answer, so closing. Please comment if you can still reproduce it, and make sure that an up-to-date reproduction project is included.

**Closed by akien-mga** 2020-12-10 16:09 UTC
Labels: bug, platform:macos, topic:input
