### ISSUE TITLE
Rainmeter "Stay Topmost" interferes with tooltips

### ISSUE THREAD

**Issue by JulGvoz** [godotengine/godot#39008] opened 2020-05-24 11:33 UTC
**Godot version:**
v3.2.1.stable.official
**OS/device including version:**
Windows 10 Education
**Issue description:**
When using Rainmeter skins (in my specific case, https://github.com/MarcoPixel/monstercat-visualizer), and making skin's position to "Stay Topmost", tooltips do not appear when hovering over various tools and options in Godot. Pressing Alt-Tab will make the tooltip appear over the item mouse hovers on.
**Steps to reproduce:**
1. Install Rainmeter
2. Install a Rainmeter skin
3. Enable the skin
4. In skin's settings -> Position -> Select "Stay Topmost"
5. In Godot Engine, tooltips do not appear.

**Minimal reproduction project:**
Any project

(also, not sure if it matters, but I have 2 rainmeter skins staying on top)

**Comment by JulGvoz** [comment] 2020-05-24 11:35
My guess on why this happens is that Godot, having a custom tooltip implementation of some kind, assumes the current active window will always be topmost window, but when other applications try to stay topmost, it Godot Engine thinks it is not the active window.

**Comment by Calinou** [comment] 2021-09-22 13:33
Duplicate of https://github.com/godotengine/godot/issues/32990 (same cause).

**Closed by Calinou** 2021-09-22 13:33 UTC
Labels: bug, platform:windows, topic:porting, topic:gui
