### ISSUE TITLE
Parallax layers have an offset

### ISSUE THREAD

**Issue by NicoLira** [godotengine/godot#17764] opened 2018-03-25 19:59 UTC
**Godot version:**

2.1.5 RC1

**OS/device including version:**

Windows 7 / Nvidia GeForce 730

**Issue description:**

The parallax layers have an offset from how they should look in the editor and how they appear when I run the proyect

It used to be working fine on version 2.1.4
**Steps to reproduce:**

[parallax.zip](https://github.com/godotengine/godot/files/1845732/parallax.zip)

**Minimal reproduction project:**

**Comment by eon-s** [comment] 2018-03-26 09:35
Can you check if this is related to the new parallax layer features @TheSofox ?

**Comment by TheSofox** [comment] 2018-03-26 13:47
It honestly probably is related. I'll look into it.

**Comment by akien-mga** [comment] 2018-04-03 14:08
I can confirm the regression with the provided project, comparing 2.1.4-stable with current 2.1 branch (0b180a07) on Linux x86_64.

**Comment by akien-mga** [comment] 2018-04-11 07:39
@TheSofox Did you have any chance to look at it yet? Don't want to put pressure but it's the last regression I know of preventing the 2.1.5 release :P

**Comment by TheSofox** [comment] 2018-04-23 21:35
I'm really sorry. I really should be fixing this up, but a lot of things have been taking up my time and attention. I can probably look to fixing this within 2 weeks. Depending on how things go I may get it fixed before then, but I don't want to give a deadline that I can't stick to.

Apologies again, I will fix this.

**Comment by akien-mga** [comment] 2018-05-16 16:28
For now I've reverted the parallax changes made since 2.1.4-stable, as I really want to release 2.1.5-stable ASAP which is long overdue. (Revert commit: f19768575)

I'd gladly merge them back in the 2.1 branch for 2.1.6 once the cause for this regression has been found and fixed.

In the meantime, closing this issue as fixed by the revert - I'll reopen the ones the original commits were fixing.

**Closed by akien-mga** 2018-05-16 16:28 UTC
Labels: bug, confirmed, topic:core
