### ISSUE TITLE
The viewport pixel grid is misaligned and innacurate in Godot 4 beta 9

### ISSUE THREAD

**Issue by fractalcounty** [godotengine/godot#70336] opened 2022-12-20 06:34 UTC
### Godot version

4.0-beta9 (Standard and .NET6) 

### System information

Windows 11 22H2, RTX 3080 (527.37)

### Issue description

In Godot 4, the pixel grid is slightly misaligned from the true position of pixels. Objects placed near the world origin will appear to fit within the pixel grid, but the grid will become steadily more misaligned the farther an object is from world origin. This causes critical visual issues in lower resolution projects, breaks tilemaps, and makes it impossible to make "pixel perfect" games in Godot 4.

Here is an example I was provided by another user, who used a 1px x 1px TextureRect that has been placed at two varying positions in the scene.
![example](https://user-images.githubusercontent.com/121070110/208594359-4406b3ea-f222-420d-b06a-02900b52222e.png)

Here is a comparison between how sprites appear in the editor vs. how they appear in-game, which displays the massive side effects that this bug has on visual quality of certain games:
![example2](https://user-images.githubusercontent.com/121070110/208597250-39345ec4-ef56-43c5-98c5-d0538cfc4418.png)

### Steps to reproduce

- Start a new project in Godot beta 9
- Create a 2D scene and add a ColorRect that's 1 px by 1 px in size
- Go to "Viewport Snapping Options", turn on Pixel Snap, and then click "Configure Snap"
- Change the "Grid Step" option to something like 1x1, 2x2, etc. and press OK.
- Drag the 1x1 ColorRect from the world origin. The farther it is, the more misaligned.

### Minimal reproduction project

No reproduction project necessary (UI bug)

**Comment by KoBeWi** [comment] 2022-12-20 15:15
Actually, duplicate of #70186

**Closed by KoBeWi** 2022-12-20 15:15 UTC
Labels: bug, topic:editor, usability
