### ISSUE TITLE
Visual shader editor blocks misbehave after another block gets deleted

### ISSUE THREAD

**Issue by Bonfi96** [godotengine/godot#5974] opened 2016-07-30 16:35 UTC
**Operating system or device - Godot version:**
Windows 10, Godot 2.1 rc1

**Issue description** (what happened, and what was expected):
Blocks in the visual shader editor get locked to the mouse after deleting another block.

**Steps to reproduce:**
Open the visual shader editor, crete any block, delete it by clicking on the X.
Sometimes one of the other blocks will follow the mouse around the editor

**Comment by vnen** [comment] 2016-07-30 23:52
Duplicate of #4869.

**Closed by vnen** 2016-07-30 23:52 UTC

**Comment by akien-mga** [comment] 2016-08-08 08:25
Actually duplicate of #4433 too :)
