### ISSUE TITLE
Import gltf generate 6x bigger material file

### ISSUE THREAD

**Issue by jdoohen52** [godotengine/godot#48740] opened 2021-05-15 18:41 UTC
Might be related: #31632

**Godot version:**

v3.3.stable.official

**OS/device including version:**

Might be unrelated. Nvidia GTX1650Ti. GLES3.

**Issue description:**

Import gltf file exported from blender generate a 6x bigger material file in godot and similar file size increase in project export. I think it's okay that godot generate large file in project, but ideally project exports should only increase the size of original asset (gltf file).

**Steps to reproduce:**
Open an empty project, create a 3D scene, export project and see result binary + data size.
Import this gltf file exported from blender: https://drive.google.com/file/d/1HkD-9YrCcRWWObRZI7En2SkHihWAtIEg/view?usp=sharing
It's about `30MB`. But godot generate a `~200MB` `.material` file:
![image](https://user-images.githubusercontent.com/73770882/118374528-742d7480-b571-11eb-8451-9807c4fdc6c7.png)
Export project again, it adds about `~200M` in size:
![image](https://user-images.githubusercontent.com/73770882/118374733-aab7bf00-b572-11eb-85cf-d96fb9425424.png)

**Minimal reproduction project:**

Project is too big to upload in github so I upload to google drive: https://drive.google.com/file/d/1rlYPFk1vYoal-z1XbqPESJiHm7bL46XH/view?usp=sharing. You can also just create a new project and import above glb file.

**Comment by Calinou** [comment] 2021-05-15 19:27
Duplicate of https://github.com/godotengine/godot/issues/34641.

**Closed by Calinou** 2021-05-15 19:27 UTC
