### ISSUE TITLE
Compilation fail again in Webassembly templates : drivers/unix/os_unix_global_settings_path.gen.cpp

### ISSUE THREAD

**Issue by nylnook** [godotengine/godot#13078] opened 2017-11-20 08:14 UTC
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Archlinux (Antergos) 64 bit, current git version (today)

**Issue description:**
Following #12720 fix, I tried to compile again and ran into another compilation error:

```
$ export EMSCRIPTEN_ROOT=/usr/lib/emscripten
$ scons platform=javascript target=release wasm=yes
scons: Reading SConscript files ...
WebM SIMD optimizations are disabled. Check if your CPU architecture, CPU bits or platform are supported!
Checking for C header file mntent.h... yes
scons: done reading SConscript files.
scons: Building targets ...
[  0%] Install file: "misc/dist/html/default.html" as "bin/.javascript_zip/godot.html"

...

[ 93%] Compiling ==> thirdparty/zlib/zutil.c
[ 93%] Compiling ==> drivers/unix/syslog_logger.cpp
[ 93%] Compiling ==> drivers/unix/dir_access_unix.cpp
[ 93%] Compiling ==> drivers/unix/packet_peer_udp_posix.cpp
[ 93%] Compiling ==> drivers/unix/stream_peer_tcp_posix.cpp
[ 93%] Compiling ==> drivers/unix/os_unix_global_settings_path.gen.cpp
drivers/unix/os_unix_global_settings_path.gen.cpp:3:17: error: out-of-line definition of 'get_global_settings_path' does not
      match any declaration in 'OS_Unix'
String OS_Unix::get_global_settings_path() const {
                ^~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
ERROR:root:compiler frontend failed to generate LLVM bitcode, halting
scons: *** [drivers/unix/os_unix_global_settings_path.gen.javascript.opt.bc] Error 1
scons: building terminated because of errors.
```

My hopes are falling apart... I'd really use a freshly compiled template before next week  ;p

Thanks for your work !

**Comment by akien-mga** [comment] 2017-11-20 08:30
Duplicate of #13076.

**Closed by akien-mga** 2017-11-20 08:30 UTC

**Comment by nylnook** [comment] 2017-11-20 09:27
Sorry for the duplicate (I searched but didn't found), and thanks a lot, compilation worked for both release and debug!
