### ISSUE TITLE
Clicking away from a dialog box or dropdown menu shouldn't interact with other elements

### ISSUE THREAD

**Issue by ghost** [godotengine/godot#10249] opened 2017-08-11 04:34 UTC
**Operating system or device - Godot version:**
Linux Mint 18.2 Cinnamon x64
Godot master 81dde26

**Issue description:**
When you click outside of an open dialog box or dropdown menu to close it, the click will also interact with whatever the mouse is over. Given that, at least in the dialog box's case, the background now darkens to indicate a lack of focus/interactivity, there should be some protections against unintentionally clicking on something... 

**Steps to reproduce:**
- Open up the Project/Editor Settings, or just click on any title bar menu
- Position mouse over an element in the background
- Click to close the dialog box/dropdown menu
- Whatever the mouse was over will also be clicked

**Comment by coppolaemilio** [comment] 2018-01-15 08:38
I can't reproduce this one on windows using the latest version. Can you check if it is still there?

**Comment by tom-jk** [comment] 2020-07-26 09:57
Interacting on clicking away from dropdown menus was resolved by 3.1.alpha2.
Interacting on clicking away from dialogs with shaded backgrounds was resolved by 3.2.2.stable.

Interacting on clicking away from the following (possibly others too, list not exhaustive) is not resolved in 3.2.3.stable:

- new resource menu (eg. sprite->texture in Inspector)
- color picker
- file dialog (when unshaded, eg. project settings->autoload tab->path file dialog, then interact with project settings)
- mask/layer name dropdown menu
- editor dock position popup
- right-click context menu

some of these may be intentional/desirable though.

**Comment by KoBeWi** [comment] 2024-04-23 15:48
Fixed in Godot 4, at least for multi-window mode.

**Closed by KoBeWi** 2024-04-23 15:48 UTC
Labels: enhancement, topic:editor, usability, topic:gui
