### ISSUE TITLE
UI font is too small on Mac(retina)

### ISSUE THREAD

**Issue by labolado** [godotengine/godot#3035] opened 2015-12-10 05:03 UTC
Compiled from source, and the ui font is very small on mac(retina).
<img width="1244" alt="2015-12-10 12 46 10" src="https://cloud.githubusercontent.com/assets/12539642/11707337/34f21e3c-9f3e-11e5-9ef5-b2b3878aae5f.png">

**Comment by akien-mga** [comment] 2015-12-10 06:33
Duplicate of #20..

**Closed by akien-mga** 2015-12-10 06:33 UTC
Labels: archived
