### ISSUE TITLE
Godot 3.4 closes when opening project.

### ISSUE THREAD

**Issue by l33tlinuxh4x0r** [godotengine/godot#54860] opened 2021-11-11 03:13 UTC
### Godot version

v3.4-stable_win64

### System information

Windows 11, Amd 6900xt, AMD 5950x

### Issue description

When running Godot 3.4 by double clicking the executable the project manager opens. When I try to open a project it crashes without error. If Godot is run from command prompt in windows cmd -> cd Desktop -> Godot_v3.4-stable_win64.exe godot works correctly.

Also on a side note: There is an additional empty window that spawns when launching Godot.
![image](https://user-images.githubusercontent.com/1632838/141230761-a583e3a0-5d8d-4d09-8669-5fc8084cff79.png)

### Steps to reproduce

1. Download Godot 3.4 form the godotengine.org
2. Run Godot by double clicking on the executable
3. Create a new project (or open an existing one)
4. Godot crashes without an error on Windows 11 (I haven't tried other versions of Windows)

### Minimal reproduction project

NA/Any project reproduces this.

**Comment by l33tlinuxh4x0r** [comment] 2021-11-11 03:16
Running from command line is a workaround for this bug.
Running as Administrator is another workaround for this bug.

**Comment by sairam4123** [comment] 2021-11-11 03:33
Related #54076

**Comment by l33tlinuxh4x0r** [comment] 2021-11-11 03:34
I just downloaded windows editor from https://github.com/godotengine/godot/actions/runs/1446148801 and it still gets the weird empty window but after opening a project the empty window disappears and so does the cmd prompt but Godot seems to be working on the 4.0 branch.

**Comment by l33tlinuxh4x0r** [comment] 2021-11-11 03:39
> 
> 
> Related #54076

Confirmed using "Windows Console Host" instead of "Windows Terminal" fixes the issue as per the related bug posted above.

**Comment by akien-mga** [comment] 2021-11-11 06:54
Duplicate of #54076

**Closed by akien-mga** 2021-11-11 06:54 UTC
