### ISSUE TITLE
Optimize out OS.is_debug_build(), implement debug_assert()

### ISSUE THREAD

**Issue by RandomShaper** [godotengine/godot#7993] opened 2017-03-09 15:44 UTC
# A) Optimizing out `OS.is_debug_build()`

I tend to put assertions here and there in my GDScripts. Sometimes just not a plain assert but a call to a more complex routine to check if certain preconditions are met:

```
func _ready():
    if OS.is_debug_build():
        debug_check_nodes_z():
```

Do you think that letting the compiler handle ' OS.is_debug_build()'  as a constant could provide some benefit in terms of performance or something?

# B) Implementing `debug_assert()`

Sometimes I don't want a certain assert to crash the game if failed. In case it's checking about something that should be some way but is not critical, I have to write::

```
if OS.is_debug_build():
    assert(...)
```

What do yoy think about adding a `debug_assert()` that gets checked only on debug builds?

**Comment by bojidar-bg** [comment] 2017-03-10 11:33
I think asserts would just issue a CallError, and won't break a running non-debugger game (make sure to test).

**Comment by bojidar-bg** [comment] 2017-03-10 11:35
Also, the first part looks like a duplicate of #6340.

**Comment by RandomShaper** [comment] 2017-03-10 13:02
Yes, I will close this one and add my proposal there.

**Closed** 2017-03-10 13:14 UTC
Labels: discussion, enhancement, feature proposal, topic:core, topic:gdscript

**Comment by RandomShaper** [comment] 2017-03-10 13:27
@bojidar-bg, I've checked and I've found that `assert()`s indeed are not checked on release builds.
