### ISSUE TITLE
If a scene is open in godot and the scene file is modified outside godot a prompt should be given on whether or not to update or overwrite

### ISSUE THREAD

**Issue by AlekhineDev** [godotengine/godot#11803] opened 2017-10-03 14:48 UTC
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Linux Mint.
Godot 2.1.4.
GPU irrelevant.

**Issue description:**
If a scene is open in Godot and the scene file is externally modified no prompt is given of this conflict, if changes are made in Godot, saving will overwrite the external modifications to the scene file.
It should prompt the user whether or not to update the scene according to the new scene file or whether to overwrite these.
Ideally it should prompt immediately as the external changes are made.

**Steps to reproduce:**
Create a scene, make a change and save.
With the scene still open in Godot then externally modify the scene file(i.e by git pulling a commit with modifications to the scene)

**Link to minimal example project:**
An example project with its own readme.
https://github.com/AlekhineDev/godot-bug-scene-conflict

**Comment by AlekhineDev** [comment] 2017-10-03 14:51
This is a nuisance when working with a team on a project, when for instance git pulling while godot is open, without realizing the conflict, then overwriting the pulled changes when saving.

**Comment by puppetmaster-** [comment] 2017-10-04 06:59
@AlekhineDev You got less problem when changed are made from external source (coder or repository pull) when you disable this editor setting "**Auto Save Before Running**" #8994

There is also this issue. #8615

**Comment by uldall** [comment] 2017-10-06 09:44
On Linux I guess this could be done with inotify. When a change happens to a scene file in the filesystem  (and the scene has unsaved in-memory changes) a popup could appear in Godot prompting the user to take actions. Either discard current changes or overwrite the filesystem version with the current in-memory working copy.

**Comment by raymoo** [comment] 2017-10-06 22:25
You could also read the timestamp when reading in the file initially, then the timestamp can be checked again on saving to see if it has been modified. You could poll for the timestamp if you want to get notifications during editing.

**Comment by NathanWarden** [comment] 2017-10-06 22:34
I'm quite sure every OS has a way to get notifications to your program when a file has been changed (like inotify as @uldall mentioned above). This would be the "correct" way to implement this.

**Comment by Zylann** [comment] 2020-10-03 16:26
Note related to @NathanWarden : 
Listening to file notifications might not be the only way. In Unity, I turned off the auto-reimport precisely to avoid messing with situations where I do a complex merge: sometimes when merging I need to take a look at the editor to verify the state of something, without having it reimport half-broken stuff or blocking me with a prompt. Then, when I'm done with the merge, I use their Ctrl+R shortcut *which triggers the reimport-modified-stuff behavior*. Which means there is a way to do it in a deferred way as well. I think Godot does this on re-focus without even giving you a choice, and yet it does that only on specific regions of the editor such as the script editor (at least that's how it was last time I checked).

**Comment by rzuf79** [comment] 2020-10-03 17:20
For the time being - is there a way around this issue that's better than quitting the editor before every git pull?

**Comment by Zylann** [comment] 2020-10-03 17:26
It's interesting because the title of the issue says `a prompt should be given on whether or not to update or overwrite`. Closing Godot does not works this around in any way, in fact it means you DO want to keep the file on disk in every case.

**Comment by rzuf79** [comment] 2020-10-03 17:57
@Zylann 
> Closing Godot does not works this around in any way
It does work around the issue of the editor overwriting any changes pulled from remote. As it is now, any external changes are simply discarded.

**Comment by Calinou** [comment] 2020-10-03 17:58
Duplicate of https://github.com/godotengine/godot/issues/20250.

**Closed by Calinou** 2020-10-03 17:58 UTC
Labels: enhancement, topic:editor
