### ISSUE TITLE
Export int range is smaller than can be set in inspector

### ISSUE THREAD

**Issue by ShatReal** [godotengine/godot#46949] opened 2021-03-12 20:07 UTC
**Godot version:**

3.2.4-rc4

**OS/device including version:**

Windows 10

**Issue description:**

Attempted to set max value of exported int to (2^64)/2-1. It said it was too big. However, when setting the value of the exported int in the Inspector I can set it that high.

It appears that the exported int's range can only take numbers between -(2^32)/2 and (2^32)/2-1 while its actual value can be the values specified in the documentation.

**Steps to reproduce:**
Paste this line in some script:
`export(int, -9223372036854775808, 9223372036854775807) var number`

**Minimal reproduction project:**

**Comment by pycbouh** [comment] 2021-03-12 20:11
Duplicate of #33095

**Closed by pycbouh** 2021-03-12 20:11 UTC
