### ISSUE TITLE
setup_local_to_scene: ViewportTexture: Path to node is invalid

### ISSUE THREAD

**Issue by 1419427247** [godotengine/godot#74290] opened 2023-03-03 11:46 UTC
### Godot version

V4.0. table. official [92bee43ad] Still the same

### System information

Win10

### Issue description

![image](https://user-images.githubusercontent.com/33598732/222712126-1565e599-9c4d-41a6-a0f4-be64531faac1.png)
When I use ViewportTexture, it will not actually affect the game, but it will always output errors

### Steps to reproduce

Using ViewportTexture in Sprite3D

### Minimal reproduction project

N/A

**Comment by 1419427247** [comment] 2023-03-03 11:49
![image](https://user-images.githubusercontent.com/33598732/222713144-84f3c6f9-cdf4-46c9-9884-b2a5126508a0.png)
![image](https://user-images.githubusercontent.com/33598732/222713157-828b5752-5fea-49d3-a25f-2730722c9d2a.png)
![image](https://user-images.githubusercontent.com/33598732/222713164-9ecc30d8-a0a7-4f88-a109-e1fb41ae054c.png)

**Comment by akien-mga** [comment] 2023-03-03 11:54
Duplicate of #66247, where you commented already. Please don't open duplicate issues knowingly.

**Closed by akien-mga** 2023-03-03 11:54 UTC
