### ISSUE TITLE
Chorus effect inspector doesn't update voices automatically

### ISSUE THREAD

**Issue by Kentarosan** [godotengine/godot#31627] opened 2019-08-24 14:22 UTC
**Godot version:**
3.1

**OS/device including version:**
Windows 10

**Issue description:**
When changing the number of voices in the chorus audio effect in the inspector, the voices doesn't appears or disappears accordingly in the panel beneath.

**Steps to reproduce:**
Add the Chorus effect to an audio bus, click on it and modify the number of voices in the first parameter of the inspector.

**Comment by KoBeWi** [comment] 2020-09-16 14:46
Duplicate of #20003

**Closed by KoBeWi** 2020-09-16 14:46 UTC
Labels: bug, confirmed, topic:editor
