### ISSUE TITLE
Debanding breaks rendering on mobile (GLES3)

### ISSUE THREAD

**Issue by ATHellboy** [godotengine/godot#49989] opened 2021-06-29 08:46 UTC
### Godot version

3.3.2

### System information

Android, Mali-G72

### Issue description

I have Samsung S9+. When I export the game with GLES3, it doesn't work properly on my phone.
It looks like this:
![Screenshot_20210628-154559_Realm](https://user-images.githubusercontent.com/10496528/123764367-f7b0e400-d8d9-11eb-89d9-0af6780aad09.jpg)

Although it should look like this:
![Screenshot_20210629-125547_Realm](https://user-images.githubusercontent.com/10496528/123764517-1a42fd00-d8da-11eb-9ac8-e614da2c867a.jpg)

I have tested it with GLES2 and it works. (The above image is from GLES2 build)

Samsung S9+ supports OpenGL ES 3.2, Vulkan 1.0, OpenCL 2.0, DirectX 11 and Renderscript. (GPU: Mali-G72)

I have tested same GLES3 build and GLES2 build on my other phone which is Samsung S4 and same result.
Samsung S4 supports OpenGL ES 3.0, OpenCL 1.1 (GPU: PowerVR SGX544MP3)

Same GLES3 build works on my friends phones which are LG G5, OnePlus 5, OnePlus 6

### Steps to reproduce

Set Project > Project Settings > Rendering > Quality > Drive Name > GLES3 > Save and Restart
Then export for android. (Fallback To Gles2 is disabled and Import ETC is disabled too)

**Comment by Zireael07** [comment] 2021-06-29 09:16
Mali chipsets are infamous for badly implementing GLES3, GLES2 is the only practical option for those.

(A prime example for the "fallback to GLES2 for specified video cards" feature that was discussed several times)

**Comment by ATHellboy** [comment] 2021-06-29 09:27
> Mali chipsets are infamous for badly implementing GLES3, GLES2 is the only practical option for those.
> 
> (A prime example for the "fallback to GLES2 for specified video cards" feature that was discussed several times)

But as I remember, I have never had this issue in Unity.

**Comment by Calinou** [comment] 2021-06-29 12:17
The current GLES3 renderer is unsuited for mobile due to its high-end orientation (single-pass lighting).

**Comment by ATHellboy** [comment] 2021-06-30 05:02
> The current GLES3 renderer is unsuited for mobile due to its high-end orientation (single-pass lighting). Use GLES2 when targeting mobile platforms.
> 
> Also, can you reproduce the rendering bug on GLES3 if you hide the skinned character?

Yup, I have tested it without skinned character and just a camera in that scene. It is same.

**Comment by avnerh1** [comment] 2021-06-30 14:54
Are you using relying heavily on shaders for rendering?

**Comment by ATHellboy** [comment] 2021-07-01 07:11
> Are you using relying heavily on shaders for rendering?

After testing with completely new project. I figured out it is because of a setting in Project Settings but I have not spent time on figuring out what makes this issue.

**Comment by minosvasilias** [comment] 2021-07-01 08:09
Hey, same team as @ATHellboy here, the setting responsible was `quality/filters/use_debanding`. Turning that off fixes this particular issue, which also happens on iOS export on some iPhones. (tested on **6s**, **12** and **12 Pro**, of which only **6s** works)

**Comment by Calinou** [comment] 2021-07-01 10:40
For reference, here's the debanding shader: https://github.com/godotengine/godot/blob/ef3c346df23ea6d8c1dfbb215d599db73b616664/drivers/gles3/shaders/tonemap.glsl#L314-L324

**Comment by Calinou** [comment] 2021-07-01 11:40
Duplicate of https://github.com/godotengine/godot/issues/45366.

**Closed by Calinou** 2021-07-01 11:40 UTC
Labels: bug, platform:android, platform:ios, topic:3d, topic:rendering
