### ISSUE TITLE
ReflectionProbe captures incomplete image of scene surroundings when async shader compilation is enabled

### ISSUE THREAD

**Issue by EzraT** [godotengine/godot#56823] opened 2022-01-15 22:27 UTC
### Godot version

v3.5.beta1.official

### System information

Windows 10, GLES3, Hybrid Laptop - AMD iGPU(Ryzen 7 4800HS) + GTX 1660 Ti Max-Q

### Issue description

Async Shader Compilation disabled:
![image](https://user-images.githubusercontent.com/781121/149639133-644afda4-0dfe-4260-b048-805c237b5f50.png)

Async Shader Compilation Enabled:
![image](https://user-images.githubusercontent.com/781121/149639160-8e742660-d5d6-4b0e-b5a8-d412b12cdbba.png)

I suspect the ReflectionProbe node captures an image of the scene _**before**_ asynchronous shader compilation finishes, causing the resulting capture to be incomplete and look broken.
If you set the Update Mode for the ReflectionProbe to always, the image looks correct, but this is obviously not a proper solution.

UPDATE: I can only reproduce this when Godot is running on my integrated AMD GPU, when using the dedicated NVIDIA GPU the reflectionprobe displays correctly, so it could potentially be an AMD or iGPU specific issue.

### Steps to reproduce

Try using ReflectionProbe in any scene in a project with Asynchronous shader compilation enabled, preferably in a scene with at least a couple different Shaders or SpatialMaterial configurations.
Use a Mesh with a material that has roughness 0 and metallic 1 for easier testing.
Make sure to run Godot using an Integrated GPU if you have access to one.

### Minimal reproduction project

[MRP.zip](https://github.com/godotengine/godot/files/7876061/MRP.zip)

**Comment by Calinou** [comment] 2022-01-15 22:42
cc @RandomShaper

**Comment by EzraT** [comment] 2022-01-15 23:11
MRP added.
[MRP.zip](https://github.com/godotengine/godot/files/7876061/MRP.zip)

**Comment by RandomShaper** [comment] 2022-01-16 10:47
I can't reproduce the issue with the MRP. Neither out of the box nor by tweaking some materials to fall back to hidden during compilation.

Furthermote, currently reflection probes are already protected against this issue, which is only relevant to materials configured like that. For materials that use the ubershader during compilation (the default), reflections can be rendered just fine from the very beginning.

Since the MRP doesn't correspond to the screenhots, @EzraT, could you tell, or show, exactly how the issue shows itself for you in it?

**Comment by EzraT** [comment] 2022-01-16 11:21
@RandomShaper 

Synchronous:
![image](https://user-images.githubusercontent.com/781121/149657688-955f6a56-d698-4787-b50d-5695eb326d74.png)

Asynchronous:
![image](https://user-images.githubusercontent.com/781121/149657703-f8fc83d8-c57b-45e9-b6d0-3830821502fe.png)

Are you testing on a dedicated GPU?
I found out just now, that this only seems to happen when Godot is running on my integrated GPU.

**Comment by akien-mga** [comment] 2022-01-16 11:32
Might be that the iGPU doesn't support `GL_KHR_parallel_shader_compile`?

I can't find it on https://opengl.gpuinfo.org (at least with `4800` or `Ryzen`, maybe it the GPU component has another identifier?), might be worth using glCapsViewer to upload a report if there's none for this iGPU: https://opengl.gpuinfo.org/download.php

**Comment by EzraT** [comment] 2022-01-16 11:36
![image](https://user-images.githubusercontent.com/781121/149658216-1a70ec42-2377-499f-8563-571ca405f3b9.png)

**Comment by akien-mga** [comment] 2022-01-16 11:41
That was just a hunch, but good to see that it's supported :+1: 

I tested the MRP and I can also reproduce the issue on Linux with both:

> AMD VEGAM (DRM 3.42.0, 5.15.14-desktop-1.mga9, LLVM 13.0.0)

and:

> Mesa Intel(R) HD Graphics 630 (KBL GT2)

With both `Asynchronous` and `Asynchronous + Cache` (not sure the latter actually works properly for me, it still takes a while to process the materials which appear one at a time).

**Comment by EzraT** [comment] 2022-01-16 11:43
Interesting, I actually wasn't expecting it to also happen on an Intel iGPU, since AMD's OpenGL drivers have never been that great, so it is indeed an iGPU related problem.

**Comment by RandomShaper** [comment] 2022-01-16 12:56
Yes, I'm testing with a discrete GPU. Now, I think I now what's going on. I have been trying to fix a bug on Android that maybe is precisely this one: the ubershader won't be rendered at all even if it's ready because it may be too complex or, more likely, reaching invalid states on the non taken branches. Therefore, only when the conditioned shaders are ready you start to get stuff rendered.

I'll try to reproduce on the ntegrated Intel GPU because that would help a lot.

P. S.:

> With both `Asynchronous` and `Asynchronous + Cache` (not sure the latter actually works properly for me, it still takes a while to process the materials which appear one at a time).
Currently only the ubershaders are cached. That was not always the case, but it turned out that caching the conditioned shaders was causing a huge cache while not providing performance benefits. Therefore, the conditioned shaders will take the same time to get ready regardless caching is enabled or not. So to speak, caching can only save "loading" time.

**Comment by akien-mga** [comment] 2022-03-12 23:54
(Probably) fixed by #57674.

Please test in the upcoming 3.5 beta 2 to confirm.

**Closed by akien-mga** 2022-03-12 23:54 UTC
Labels: bug, topic:rendering, confirmed, topic:3d

**Comment by EzraT** [comment] 2022-03-23 13:10
Tested in 3.5 beta 2, and no longer able to reproduce, thanks!
