### ISSUE TITLE
Adding a polygon to a disabled CollisionPolygon2D will allow it to trigger collisions even when disabled

### ISSUE THREAD

**Issue by Bcheow** [godotengine/godot#35026] opened 2020-01-11 22:36 UTC
**Godot version:**  v3.1.1

**OS/device including version:** WIndows 10

**Issue description:** Adding a polygon to a disabled CollisionPolygon2D will allow it to trigger collisions even when disabled

**Steps to reproduce:**
Create Area2D
Create CollisionPolygon2D as child (do not add a polygon in the editor)
Add **CollisionPolygon2D.disabled = true** in _ready() 
After disabling the CollisionPolygon2D, create and populate a **PoolVector2Array** and assign it to **$CollisionPolygon2D.polygon**.
This Area2D should now collide with other objects even though disabled = true

**Minimal reproduction project:**

**Comment by tom-jk** [comment] 2020-07-21 18:19
Can't reproduce in 3.2.2.stable or 3.2.3.beta1, looks to be resolved.

convenience project: [35026.zip](https://github.com/godotengine/godot/files/4955422/35026.zip)

**Comment by akien-mga** [comment] 2020-12-10 10:36
Thanks for testing @tom-jk, closing as fixed in 3.2.

**Closed by akien-mga** 2020-12-10 10:36 UTC
Labels: bug, topic:physics
