### ISSUE TITLE
Can't get DTLS SSL to work (TLS handshake error: -9984)

### ISSUE THREAD

**Issue by Toupoc** [godotengine/godot#59148] opened 2022-03-14 18:37 UTC
### Godot version

3.4.3

### System information

windows 10, linux CentOS

### Issue description

I've never posted to github before yesterday and I accidentally closed this issue before it was solved so I'm re-opening it.

I'm using godot 3.4.3 to edit and export my projects. I'm running the server projects through godot 3.4.2 linux_server version. I have my server code running in the document root of a dedicated server. I bought an SSL from a 3rd party. I tried runnning the server project as the root user, as well as a non-root user. My cert and keys load properly in godot on the server and on the client ( I checked by having it print them when they're loaded) I tried loading the cert and key directly from where they are installed on the server, AND i tryed loading copies of them from the res:// directory in godot instead. My SSL definately works in some respect because when I go to the URL that's connected to my server I do get the little lock icon.

THE PROBLEM: when I try to use this dang SSL for a DTLS connection when the player signs in (and change setdtlsvarifyenabled() to TRUE) I just keep getting a handshake error. When I keep it false, everything works fine. But when I try to use my newly aquired SSL and switch it to true. Handshake errors for days. This is the error I get --> E 0:00:04.727 _dohandshake: TLS handshake error: -9984
<C++ Source> modules/mbedtls/packetpeermbeddtls.cpp:102 @ _dohandshake()
Gateway.gd:23 @ _process()
I've been grappling with this issue for weeks now. I really need this DTLS to work for sign in. Does anyone have any idea what could be wrong? I'm losing my mind over here.

### Steps to reproduce

NOTE:     I WILL KEEP MY SERVER RUNNING INDEFINATELY SO THAT YOU BEAUTIFUL PEOPLE CAN TEST THIS.

1.) make UI scene.
2.) Add a script to the root node. 
3.) Paste the following code into the script.
4.) Add the stopclock.crt from the ZIP file at the bottom into the res:// directory of the godot project.
5.) Save scene as main and press play.

```
extends Node

var cert = load("res://stopclock.crt")
var network = NetworkedMultiplayerENet.new()
var gateway_api = MultiplayerAPI.new()
var ip = "www.stopclock.app" #<--- Server domain
#var ip = "72.52.134.20" #<--- Server IP
var port = 42092

##-----------------------------------------> READ ME <-----------------------------------------##
#	This minimal recreation is attempting to connect to a dedicated server. The server is running with
#	Godot 3.4.2 Linux-server.64 -- when DTLS verify in disabled (set to false) you can see the connection works.
#	BUT when you enable DTLS verify using the servers 3rd party SSL cert. It gives us a handshake error. 
##---------------------------------------------------------------------------------------------##

func _ready():
	ConnectToServer()

func _process(_delta):
	if get_custom_multiplayer() == null: return
	if not custom_multiplayer.has_network_peer():
		return;
	custom_multiplayer.poll();

func ConnectToServer():
	network = NetworkedMultiplayerENet.new()
	gateway_api = MultiplayerAPI.new()
	network.set_dtls_enabled(true)
	network.set_dtls_certificate(cert)
	network.set_dtls_verify_enabled(false) ##<--- THIS is where the problem lies.
	network.create_client(ip, port)
	set_custom_multiplayer(gateway_api)
	custom_multiplayer.set_root_node(self)
	custom_multiplayer.set_network_peer(network)
	
	network.connect("connection_failed", self, "_OnConnectionFailed")
	network.connect("connection_succeeded", self, "_OnConnectionSucceeded")

func _OnConnectionFailed():
	print("Failed to connect to login server")
	$Label.text = "Connection failed. :("

func _OnConnectionSucceeded():
	print("Succesfully connected to login server")
	$Label.text = "Connection succeeded!"
```

stopclock.ctr zip file:
[stopclock.zip](https://github.com/godotengine/godot/files/8247674/stopclock.zip)

### Minimal reproduction project

I couldn't upload the zip file containing the minimal reproduction. I don't know why. I think perhaps it was too big. Even though it was only 240MB. Instead, I listed steps to reproduce the issue above.

**Comment by Calinou** [comment] 2022-03-14 18:43
Duplicate of https://github.com/godotengine/godot/issues/59080. You can reopen issues you closed using the "Reopen" button at the bottom :slightly_smiling_face:

**Closed by Calinou** 2022-03-14 18:43 UTC

**Comment by Toupoc** [comment] 2022-03-14 19:13
> Duplicate of #59080. You can reopen issues you closed using the **Reopen issue** button at the bottom 🙂
> 
> > I couldn't upload the zip file containing the minimal reproduction. I don't know why. I think perhaps it was too big. Even though it was only 240MB.
> 
> Attachments are limited to 10 MB on GitHub. That said, if your minimal reproduction project weighs 240 MB, it is probably not minimal – especially if you remove the `.import/` folder before creating a ZIP.

It's the android export folder. I'm trying to delete it.
