### ISSUE TITLE
Save Scene Viewport On Exit

### ISSUE THREAD

**Issue by toliaferrode** [godotengine/godot#5804] opened 2016-07-19 07:55 UTC
**Operating system or device - Godot version:**
Any OS, Godot 2.1-beta

**Issue description** (what happened, and what was expected):
On exit and reload of my scene the editor camera position isn't saved. When I reload my scene the editor camera is zoomed way in and I have to rotate it by default get back to the previous view I had.

**Steps to reproduce:**
Save a scene, exit, re-open Godot, and reload the scene.

**Link to minimal example project** (optional but very welcome):

**Comment by akien-mga** [comment] 2016-07-19 07:58
Duplicate of #5713.

**Closed by akien-mga** 2016-07-19 07:58 UTC
