### ISSUE TITLE
Add Metadata just crashes

### ISSUE THREAD

**Issue by AnnoyingB** [godotengine/godot#68803] opened 2022-11-17 19:48 UTC
### Godot version

4.0 beta 1

### System information

Windows 11, NVIDIA GeForce RTX 3060, Vulkan

### Issue description

I created a AudioStreamWav resource and clicked "Add Metadata" and godot just crashed.

### Steps to reproduce

Create AudioStreamWav resource and click on "Add Metadata"

**Comment by akien-mga** [comment] 2022-11-17 20:07
Duplicate of #65855, fixed in 4.0 beta 2.

We're now at 4.0 beta 5, be sure to upgrade to get the latest fixes.

**Closed by akien-mga** 2022-11-17 20:07 UTC
