### ISSUE TITLE
Vulkan - Wrong transparency sorting

### ISSUE THREAD

**Issue by nonunknown** [godotengine/godot#54226] opened 2021-10-25 12:44 UTC
### Godot version

v4.0.dev.custom_build [7d907ea90] 

### System information

manjaro 21, AMD Radeon r7 200 series, Vulkan, 8GB Memory

### Issue description

When a model has a lot of merged objects in different places, the engine renders it wrong:

https://user-images.githubusercontent.com/58845030/138697285-6f8bd806-834f-494b-89c5-ab804a7bfe89.mp4

### Steps to reproduce

* Just Import the model
* Fly around

### Minimal reproduction project

[model_map_village.glb.zip](https://github.com/godotengine/godot/files/7409999/model_map_village.glb.zip)

**Comment by tinmanjuggernaut** [comment] 2022-07-30 12:31
I don't see it as a duplicate of #43253 when it's closed, merged, and for a different renderer and server that has been rewritten. That issue was object sorting problem in VisualServer, which doesn't exist anymore.

However, I opened up the glb in alpha13 on windows 10/64, gtx1060. Everything displayed properly. The objects material shows depth prepass mode and looks fine.

![image](https://user-images.githubusercontent.com/632766/181914120-581fa6d7-41d1-4697-8553-736bbb04dca9.png)

**Comment by Calinou** [comment] 2022-07-30 17:30
Closing in favor of https://github.com/godotengine/godot/issues/63675, which is a more recent issue with more details.

**Closed by Calinou** 2022-07-30 17:30 UTC
Labels: bug, topic:rendering, regression, topic:3d
