### ISSUE TITLE
Surprising behaviour from`Geometry.is_point_in_polygon`

### ISSUE THREAD

**Issue by opyate** [godotengine/godot#52872] opened 2021-09-20 13:29 UTC
### Godot version

v3.3.3.stable.official

### System information

Windows 11

### Issue description

I'm trying polygon operations with `v3.3.3.stable.official`, downloaded from Github Releases.

For each point in each polygon, check if the point is in/on the polygon with [`Geometry.is_point_in_polygon`](https://docs.godotengine.org/en/stable/classes/class_geometry.html#class-geometry-method-is-point-in-polygon), and draw a yellow dot if `true`.

Here I expect to see yellow dots on every corner. At the very least, I expect to see yellow dots in the same positions across the polygons.

(green dot is start vertex; blue dot is end vertex, just FYI)

![image](https://user-images.githubusercontent.com/96808/134008618-71a6467c-406a-40eb-bcf0-2941e8a8c70f.png)

### Steps to reproduce

Check out the reproducible case at https://github.com/opyate/godot-geometry-polygon-bugreport and run the only scene.

### Minimal reproduction project

https://github.com/opyate/godot-geometry-polygon-bugreport

**Comment by opyate** [comment] 2021-09-20 13:36
cc @Xrayez , as I know you're interested in polygon-related problems :)

**Comment by Xrayez** [comment] 2021-09-20 14:12
I'd say Godot's implementation looks quite hacky:

https://github.com/godotengine/godot/blob/0316d50ece15caef29c34e053dbf1df33bf418cc/core/math/geometry.h#L929-L956

I think it's mainly used for editor-only stuff like determining canvas item picks in the viewport, and there was some issues with segment/segment intersection tests which might be already fixed in `master`: #52110.

Actually I've been proposing to replace the existing implementation some time ago with more robust method. With [Goost](https://goostengine.github.io/), you can correctly find all points **on** the polygon:

![image](https://user-images.githubusercontent.com/17108460/134015597-12601b72-c2aa-479f-b7cc-555805ebb37f.png)

```gdscript
func record_points_on_polygon(poly: PoolVector2Array):
	for point in poly:
		if GoostGeometry2D.point_in_polygon(point, poly) == -1:
			on_polygon.append(point)
```

> Here I expect to see yellow dots on every corner. At the very least, I expect to see yellow dots in the same positions across the polygons.

I have slightly updated your reproduction project to show points on polygon instead:
[godot-geometry-polygon-bugreport.zip](https://github.com/godotengine/godot/files/7196279/godot-geometry-polygon-bugreport.zip) (requires [Goost](https://goostengine.github.io/download.html) to run).

**Comment by opyate** [comment] 2021-09-20 14:30
> By the way, if you're interested in geometry stuff, Goost has a lot more methods to play with

Thanks for the reply, @Xrayez - I'm glad the bug could be confirmed, and I'm not doing something wrongly.

I'll give Goost a shot right now :-)

**Comment by pouleyKetchoupp** [comment] 2021-09-20 14:30
This inconsistent behavior will be fixed in 4.0 as part of https://github.com/godotengine/godot/pull/52110, so I'm closing the issue.

Unfortunately it can't be fixed in 3.x as some systems and projects might rely on the current behavior even if not ideal.

**Closed by pouleyKetchoupp** 2021-09-20 14:30 UTC
Labels: bug, topic:core, confirmed, topic:2d

**Comment by Xrayez** [comment] 2021-09-20 14:41
Yeah, the only major difference in API is that implementation in Goost allows to distinguish between inside, outside, and exactly on polygon's boundary separately (`-1` and `+1` will act in a boolean context to mean both inside or exactly on the polygon, `0` - outside).

The [implementation that you can see in Goost](https://github.com/goostengine/goost/blob/1685593d6e9d5ec357494fc63298c8890ce06acb/core/math/geometry/2d/goost_geometry_2d.cpp#L403-L450) originates from Clipper, based on [Winding number algorithm](https://en.wikipedia.org/wiki/Point_in_polygon#Winding_number_algorithm).

**Comment by Calinou** [comment] 2021-09-20 14:42
> Unfortunately it can't be fixed in 3.x as some systems and projects might rely on the current behavior even if not ideal.

Could we expose the new behavior in `3.x` as an opt-in project setting?

**Comment by pouleyKetchoupp** [comment] 2021-09-20 14:51
> Could we expose the new behavior in `3.x` as an opt-in project setting? It'd make upgrades to 4.0 smoother for those who plan to upgrade.

Yes, that seems possible since the code update is localized in just two specific places.
