### ISSUE TITLE
GDScript : default value of an exported variable can be modified at run time

### ISSUE THREAD

**Issue by ChickenStorm** [godotengine/godot#41953] opened 2020-09-10 15:56 UTC
**Godot version:**  v3.2.2.stable.official

**OS/device including version:** Windows 8.1

**Issue description:**
When using `export var variable : Type = default_value`, if `default_value` is a reference, it can be modified at run time. At the creation every `variable` will point to the same value. It means that one can modify `variable` of other instances of the class. It will also affect the value of `variable` at the creation of a new instance.

**Steps to reproduce:**

minimal code to reproduce

```GDscript
class_name CustomObject
extends Object

export var dict : Dictionary = {}
```
```GDscript
extends Node


func _ready():
	var a = CustomObject.new()
	a.dict["key"] = "test"
	a.free()
	var b = CustomObject.new()
	print(b.dict)
	b.free()
```
output : `{key:test}`

**Minimal reproduction project:**
[minimal-project-export-default.zip](https://github.com/godotengine/godot/files/5202895/minimal-project-export-default.zip)

**Comment by akien-mga** [comment] 2020-09-10 16:06
Related to #20436, might be duplicate of another issue but can't find it right now. CC @ThakeeNathees @vnen @bojidar-bg

**Closed** 2020-10-20 18:43 UTC
Labels: bug, topic:gdscript
