### ISSUE TITLE
draw_string() only renders blocks and throw thousands of errors

### ISSUE THREAD

**Issue by leoddd** [godotengine/godot#15023] opened 2017-12-25 02:11 UTC
**Godot version:**

Godot 3 e1da26184

**OS/device including version:**

Ubuntu 16.04, Radeon HD 6450

**Issue description:**

When using draw_string() within _draw(), Godot draws rectangles the width and height of the letters it should be drawing instead of the actual letters. for both Dynamic and Bitmap fonts.
They always display fine inside a Label. BitmapFont seems to render fine in-game, but retains the block issue when used in-editor in a tool script, while DynamicFont has the same issue in-game.

While it draws the rectangles, it outputs thousands of copies of this error to the error log:
```
core/rid.h:164 - Condition ' !id_map.has(p_rid.get_data()) ' is true. returned: __null
```
This is how a drawn string looks:
![image](https://user-images.githubusercontent.com/20242421/34330677-bb8ff5f4-e91f-11e7-9e33-695b3cc528e4.png)

**Steps to reproduce:**
Try using draw_string() in any CanvasItem's _draw() method. Reproduction project is attached.

Example code:
```GDScript
	var font = DynamicFont.new()
	var data = DynamicFontData.new()
	data.font_path = "res://fonts/freepixel.ttf"
	font.font_data = data
	font.size = 16
	draw_string(font, Vector2(), "Test", Color("FFFFFF"))
```

**Minimal reproduction project:**

[MinimalTTF.zip](https://github.com/godotengine/godot/files/1585188/MinimalTTF.zip)

- [x] I searched the existing [GitHub issues](https://github.com/godotengine/godot/issues?utf8=%E2%9C%93&q=is%3Aissue+) for potential duplicates.

**Comment by volzhs** [comment] 2017-12-25 08:01
```gdscript
var font = DynamicFont.new()

func _ready():
	var data = DynamicFontData.new()
	data.font_path = "res://freepixel.ttf"
	font.font_data = data
	font.size = 17

func _draw():
	draw_string(font, Vector2(5, font.get_height()+5), get_name(), Color("000000"))
	draw_string(font, Vector2(4, font.get_height()+4), get_name(), Color("FFFFFF"))
```

this will fix your problem.
I'm not sure but you can't probably create a resource in `_draw`

**Comment by volzhs** [comment] 2017-12-25 11:17
I'm not sure if it's a bug.

**Comment by leoddd** [comment] 2017-12-25 12:34
I see, thanks! Strange limitation but it'll have its reasons, anyone know if it's mentioned in any docs?

**Comment by reduz** [comment] 2017-12-26 13:32
well, this could technically be fixed by forcing to update cache if a char is requested, but usage is definitely not optimal at all..

**Comment by reduz** [comment] 2017-12-26 13:37
no, nevermind, this is not a bug. you are deleting the font after using it, this is why you see those white recangles. this is not a bug.

**Closed by reduz** 2017-12-26 13:37 UTC
Labels: bug, confirmed, topic:rendering

**Comment by leoddd** [comment] 2017-12-27 20:18
That makes a lot more sense than an arbitrary restriction on resource creation during _draw.
I always figured that calling draw_* methods inside _draw() made the drawing happen immediately, meaning it would be fine to use temporary resources, but this is fine now that I'm aware.

**Comment by Soaku** [comment] 2019-08-26 12:55
Well, I think this could at least get a more meaningful error message. I had no idea what it means when I got it.

**Comment by wajrou** [comment] 2022-08-26 18:50
I get these errors when I put Label (2D) under Viewport (in 3D scene as TextureViewport in Sprite3D). The strange thing is font is working (from Project Settings theme)... until window is resized, maximized, switched to fullscreen. After that font in Labels is drawn very strange (filled rectangles or some fragments) and debugger is full of these errors.

Thanks to @reduz I just put theme / font to Labels under Viewport and everything is working without errors.

**Comment by Calinou** [comment] 2022-08-26 20:47
> I get these errors when I put Label (2D) under Viewport (in 3D scene as TextureViewport in Sprite3D). The strange thing is font is working (from Project Settings theme)... until window is resized, maximized or switched to fullscreen. After that font in Labels is forgotten? And drawn strangely, filled rectangles or some font fragments, and debugger is full of these errors.

This is likely a bug caused by font oversampling, which you can disable in the Project Settings as a workaround.

**Comment by Calinou** [comment] 2024-12-05 14:15
This works as of Godot 4.3, likely because of DynamicFont -> FontFile refactoring (there is no longer an intermediate DynamicFontData resource).

**Testing project:** [test_draw_font.zip](https://github.com/user-attachments/files/18024486/test_draw_font.zip)
