### ISSUE TITLE
Toggle Visibility button in scene tree throws an error in output if clicked at the edge

### ISSUE THREAD

**Issue by VerMishelb** [godotengine/godot#44502] opened 2020-12-18 16:03 UTC
**Godot version:**
3.2.3 (Steam)

**OS/device including version:**
Windows 10

**Issue description:**
When clicking on the edge of Toggle Visibility button, output throws an error and doesn't show/hide the node. However, highlight box still appears.

**Steps to reproduce:**
Move your mouse pointer to the point at the edge of Toggle Visibility button's selection highlight (hold and drag to make it easier) and click few times at 1 pixel after edge of this box (not overlapping te box, but near it).
Representation of how it looks:
![Без имени-1](https://user-images.githubusercontent.com/57833258/102634170-8346fc80-4162-11eb-89c2-985519bc6d9c.png)

**Minimal reproduction project:**
[Toggle Visibility button issue.zip](https://github.com/godotengine/godot/files/5716723/Toggle.Visibility.button.issue.zip)

**Comment by volzhs** [comment] 2020-12-18 16:42
duplicate of #27580

**Closed** 2020-12-18 16:42 UTC
