### ISSUE TITLE
SCREEN_TEXTURE gives instant framerate drop on Intel GPU.

### ISSUE THREAD

**Issue by marmitoTH** [godotengine/godot#25632] opened 2019-02-05 12:10 UTC
**Godot version:**
3.0.6 (Stable)

**OS/device including version:**
Windows 10
Intel HD graphics 520

**Issue description:**
I'm trying to make a custom post-processing shader, but no matter what I do the simple use of SCREEN_TEXTURE cause a massive framerate drop, from constant 60 to 52~54. It's not a powerfull gpu, but can handle the built in post processing just fine, like Glow, Tonemap and Auto Exposure.

**Steps to reproduce:**
This line in a fragment shader is enough to cause frame drops: vec4 col = texture(SCREEN_TEXTURE, SCREEN_UV)

**Comment by groud** [comment] 2019-02-06 13:03
I think this is more or less expected, since modifying the screen texture requires another processing step.

**Comment by marmitaTH** [comment] 2019-02-06 13:55
But the built in post-processing do it really faster with a much better performance, there should be scope for optimizations. It would be nice to have access to the environment image effects source inside the engine, so we would not need to generate a new screen texture to make some minor changes.

**Comment by toger5** [comment] 2019-02-06 19:32
Maybe there are ideas when vulkan gets added. @reduz

**Comment by kaadmy** [comment] 2019-02-25 02:15
The screen texture is slow because of the gaussian blur levels being generated any time `SCREEN_TEXTURE` is used in a shader.

Maybe there should be a way to get the screen texture without any blur processing instead?

**Comment by clayjohn** [comment] 2019-10-01 15:17
@kaadmy I think there should be a project setting called ``generate_mipmaps`` for screen texture. That way you could specify. Right now we haven't implemented ``SCREEN_TEXTURE`` mipmaps in GLES2 because it would be too slow. But it would be nice to opt-in.

**Comment by KoBeWi** [comment] 2020-11-03 21:37
Can anyone still reproduce this bug in Godot 3.2.3 or any later release?

If yes, please ensure that an up-to-date Minimal Reproduction Project (MRP) is included in this report (a MRP is a zipped Godot project with the minimal elements necessary to reliably trigger the bug). You can upload ZIP files in an issue comment with a drag and drop.

**Comment by Calinou** [comment] 2021-02-03 17:49
I'll close this as nobody else has been able to reproduce this recently. Please comment (with the [issue template](https://github.com/godotengine/godot/blob/master/.github/ISSUE_TEMPLATE/bug_report.md) filled) if you can still reproduce this.

**Closed by Calinou** 2021-02-03 17:49 UTC
Labels: bug, discussion, topic:rendering, topic:shaders
