### ISSUE TITLE
godot 4.3, shader issue

### ISSUE THREAD

**Issue by AndySamoil** [godotengine/godot#94770] opened 2024-07-26 03:28 UTC
### Tested versions

Shader works in godot 4.2, not in 4.3

### System information

Windows 11

### Issue description

When saving a shader, it does not load it in the game while it is running. Also my shader from 4.2 worked fine, as soon as it was transfered to 4.3 it didn't work. what changed to make it not work properly?

### Steps to reproduce

s

### Minimal reproduction project (MRP)

s

**Comment by clayjohn** [comment] 2024-07-26 04:27
Could you please fill out the rest of the information in the bug report?

We need the reproduction steps and MRP in order to be able to figure out the cause of this issue and to help you. 

Without them, we will have to close the issue as you haven't given us enough information.

**Comment by theraot** [comment] 2024-07-26 17:34
Likely this: https://godotengine.org/article/introducing-reverse-z/

**Comment by AThousandShips** [comment] 2024-09-14 15:25
Closing due to lack of response, if you provide the requested information this can be reopened

**Closed by AThousandShips** 2024-09-14 15:25 UTC
Labels: needs testing, topic:shaders
