### ISSUE TITLE
Delta isn't calculated correctly for _process

### ISSUE THREAD

**Issue by Warlaan** [godotengine/godot#20642] opened 2018-07-31 18:09 UTC
**Godot version:**
3.06

**OS/device including version:**
Windows 10

**Issue description:**
I created a very simple 2D scene with a script on the root node that only prints out the value of delta and a script on one child node that duplicates that child node if ui_accept is pressed.  
So by pressing ui_accept you can create new nodes and thus lower the framerate.  
Besides I activated the FPS display in the project settigns and started Fraps to have another tool that displays the frame rate.

The result is this:  
[...]  
process: 0.013333  
process: 0.013333  
Game FPS: 10  
process: 0.013333  
process: 0.013333  
process: 0.013333  
process: 0.013333  
process: 0.013333  
process: 0.013333  
process: 0.013333  
process: 0.013333  
process: 0.013333  
process: 0.013333  
Game FPS: 10  

The _process method is called only 10 times per second, but the delta value is still fixed to 0.013333, when it should rise to ~0.1.

**Steps to reproduce:**
Create any scene that results in a low frame rate and add a script with a _process-method like this:  

    func _process(delta):
        print(delta)

**Comment by goodyttoor** [comment] 2018-08-01 07:47
Bang on values on x11 for me on the current master. Probably platform specific?

**Comment by Warlaan** [comment] 2018-08-01 08:44
I just tested it with the current master on Windows, and I do get more "realistic" values, but they still don't look much better:

process: 0.012107
process: 0.012893
process: 0.015
process: 0.013333
process: 0.012909
process: 0.012345
process: 0.013079
process: 0.014172
process: 0.012494
process: 0.014047
process: 0.013857
process: 0.013762
process: 0.011667
process: 0.013755
process: 0.013406
Game FPS: 15

As you can see the values vary now, but they still don't add up to a second as I imagine they should.

I'll test it in Manjaro using 3.0.6 next.

@goodyttoor What did you do to lower the frame rate? I created lots of nodes, so I imagine it might be related to the kind of load that is actually responsible for the larger delta value.

**Comment by goodyttoor** [comment] 2018-08-02 02:59
Aha, I now see what you mean. Last time I just created some nodes to lower framerate (~45). I try it again with a whole lot more. With lower fps (~15), I got some values which clearly not sum up to 1. Also, there are zero which probably impossible.

0.133599
0.122222
0.138889
0.123333
0.015556
0
0
0.002128
0.000448
0.000402
0.000378
0.000415
0.000395
0.000741
0.136774
0.140741
Game FPS: 16

**Comment by CptPotato** [comment] 2018-08-02 06:32
I thought that maybe godot uses a minimum fps setting where the engine doesn't allow delta to get too high. This can be used to make the game not break because of the huge timesteps from unrealistically bad framerates. The downside is that the game will slow down at some point if the fps becomes too low.

But reading that even negative values or 0 were reported this doesn't seem to be the case.

**Comment by Warlaan** [comment] 2018-08-02 07:48
@CptPotato That would have been an explanation, but I didn't find anything like that and values of 0.01333 would mean that this minimum fps value was set to 75 which would mean that on any computer where vsync enforces a frame rate of no more than 60 frames your games would lag.

**Comment by samuelpedrajas** [comment] 2018-09-12 10:45
I sometimes get negative values on Android too (delta value is -139812) and it messes up my game completely. Could this be related to this issue? Otherwise I could open a new one.

**Comment by samuelpedrajas** [comment] 2018-09-13 15:11
On Android I've been able to reproduce the negative delta thing only by toggling the phone's "plane mode" 2 or 3 times while some object is processing. Here's an illustration of it:

![deltatest](https://user-images.githubusercontent.com/8157352/45497305-bde9af80-b777-11e8-86af-9d953368a30c.gif)

As I said, sometimes I need to toggle the plane mode on and off several times since it happens, so it's not that easy to reproduce.

Source code:
[DeltaTest.zip](https://github.com/godotengine/godot/files/2379851/DeltaTest.zip)

**Comment by Zireael07** [comment] 2018-09-13 15:17
Is your game an online game? Does toggling other Android settings have the same effect?

**Comment by akien-mga** [comment] 2018-09-13 15:20
This is likely unrelated to the Windows issue, please open a new issue for this Android negative delta.

**Comment by akien-mga** [comment] 2018-12-18 15:36
@Warlaan Could you provide the project you're using to test this?

**Comment by reduz** [comment] 2019-01-07 14:44
Closing this as I have no way to test or understand it. Given no one else reported or commented having similar problems and given this is such a core thing, my belief as this is more a misunderstanding han a bug.

**Closed by reduz** 2019-01-07 14:44 UTC
Labels: bug, high priority, platform:windows, topic:core
