### ISSUE TITLE
Particle system seams broken on 3.2

### ISSUE THREAD

**Issue by richardjuan** [godotengine/godot#36348] opened 2020-02-19 09:11 UTC
As soon as I add a process material, the particles stop showing off

https://youtu.be/dDNJ2rdJNwQ

PS: works on 3.1.2 version of godot

( Using Godot 3.2 on windows 10 64bits )

**Comment by akien-mga** [comment] 2020-02-19 09:36
Please fill the issue template. An 11 min video is useful context, but it's not a bug report.

**Comment by akien-mga** [comment] 2020-02-19 09:37
In any case, this is likely a duplicate of #35492. Can you confirm that enabling `Disable Z` fixes it?

**Comment by akien-mga** [comment] 2020-02-19 10:43
> Can you confirm that enabling Disable Z fixes it?

Closing for now as duplicate of #35492. If this workaround doesn't work for you, we can reopen it.

**Closed by akien-mga** 2020-02-19 10:43 UTC

**Comment by richardjuan** [comment] 2020-02-19 12:22
somebody tried it and got this error:
ERROR: get_draw_pass_mesh: Index p_pass = 3 is out of bounds (draw_passes.size() = 1).At: scene/3d/particles.cpp:218

**Comment by akien-mga** [comment] 2020-02-19 12:26
> ERROR: get_draw_pass_mesh: Index p_pass = 3 is out of bounds (draw_passes.size() = 1).At: scene/3d/particles.cpp:218

That error should be harmless, but was also supposed to be fixed in 3.2, so if you can find how to reproduce it reliably with an example project, please file a new issue for it :)

**Comment by richardjuan** [comment] 2020-02-19 12:32
i don't see the error on my computer ( since i've the particles error ) but somebody tried my scene and got the particles working out of the box and got the error message instead.
[New Game Project.zip](https://github.com/godotengine/godot/files/4225030/New.Game.Project.zip)

**Comment by akien-mga** [comment] 2020-02-19 12:45
Thanks for the test project, I can confirm the errors on Linux with 3.2-stable, and it's fixed in the current `3.2` branch (future 3.2.1), so those were likely fixed by #36031 too. It should work fine for you too in 3.2.1.

**Comment by richardjuan** [comment] 2020-02-19 13:53
@akien-mga ,  thanks for your time and contribution , it's really appreciated
