### ISSUE TITLE
Adding a signal to a C# class in a namespace creates the signal outside of the class/namespace

### ISSUE THREAD

**Issue by nightblade9** [godotengine/godot#31817] opened 2019-08-31 01:25 UTC
**Godot version:** 3.1.1.1 (Mono)
**Issue description:** When adding a signal to a C# class in a namespace, the signal appears at the bottom of the file (outside the namespace/class). It's simple enough to move it into the namespace. 

i.e. if I have this:

```
namespace Foo.Bar {
  public class MainScene extends Godot.Node2D {
    override public function _Ready() { } 
    // ...
  }
}
```

Adding a signal `NewGameClicked` on a button gives me this:

```
namespace Foo.Bar {
  public class MainScene extends Godot.Node2D {
    override public function _Ready() { } 
    // ...
  }
}

public void NewGameClicked() { }
```

It should give me this:

```
namespace Foo.Bar {
  public class MainScene extends Godot.Node2D {
    override public function _Ready() { } 
    // ...

    public void NewGameClicked() { }
  }
}
```

**Steps to reproduce:**
- Create a new Mono project
- Create a scene
- Create a `.cs` file script for the scene
- Edit the `.cs` file to put a namspace in it
- Add any control in the scene `.tscn` and bind to any signal

Expected: the newly-created function is in the namespace/class
Actual: the newly-created function is outside the namespace/class

**Comment by nightblade9** [comment] 2019-08-31 01:25
This is similar to https://github.com/godotengine/godot/issues/18721, with the added goodness of being in a namespace.

**Comment by KoBeWi** [comment] 2020-09-14 18:49
Can anyone still reproduce this bug in [Godot 3.2.3 rc6](https://godotengine.org/article/release-candidate-godot-3-2-3-rc-6) or any later release?

**Comment by nightblade9** [comment] 2020-09-14 20:30
I can still see this in 3.2.3 RC6. I don't think an MVP is required because the steps are very straight-forward, and it's the generation (not the final code) that's the problem. The linked issue (#18271) mentions that #12908 needs to be fixed before this can be fixed, and that issue is still open.

Regardless, I downloaded 3.2.3 RC6 just now and tried the repro steps, and they still reproduced. I can't upload the MVP right now for some reason (I keep getting a 502 in my browser logs) but I have one if needed.

**Comment by arpichord** [comment] 2023-03-31 02:51
This is still happening in 4.0

**Comment by raulsntos** [comment] 2023-03-31 11:27
Duplicate of https://github.com/godotengine/godot/issues/18721

**Closed by raulsntos** 2023-03-31 11:27 UTC
Labels: bug, topic:editor, confirmed, usability, topic:dotnet
