### ISSUE TITLE
Each tile gets rendered in a separate draw call when using 2D lights

### ISSUE THREAD

**Issue by darthdeus** [godotengine/godot#51161] opened 2021-08-01 22:30 UTC
### Godot version

3.3.2.stable.official

### System information

Windows 10, GTX 1080ti 471.41, GLES3

### Issue description

It seems when using a Light2D in combination with a TileMap that each tile (or tile type in a row) gets re-rendered (or rather the light on top) in a separate OpenGL draw call, as illustrated by the following screen capture from [RenderDoc](https://renderdoc.org/).

I'd expect the whole tilemap quadrant to be rendered at once.

https://user-images.githubusercontent.com/123374/127787163-5abd7caf-f3b3-4096-bb7c-5e28d21f6772.mp4

### Steps to reproduce

1. Create a tilemap
2. Add a 2D light to the scene
3. Observe draw calls in Debugger -> Monitors -> 2D -> Draw Calls or using RenderDoc

**Comment by Calinou** [comment] 2021-08-01 23:28
Duplicate of https://github.com/godotengine/godot/issues/23593. This is a design limitation of Light2D in `3.x`, which has been lifted in the `master` branch thanks to a single-pass approach.

**Closed by Calinou** 2021-08-01 23:28 UTC
