### ISSUE TITLE
Lost modulate in custom shader's texture function.

### ISSUE THREAD

**Issue by harrisyu** [godotengine/godot#58464] opened 2022-02-23 15:38 UTC
### Godot version

Godot 4 alpha 3

### System information

Windows 11, Vulkan, nvidia T600 driver 472.39

### Issue description

In gdshader 'texture(TEXTURE, UV)' output only color from origin texture without modulate.
This is diffrent from CanvasItem Material shader, and diffrent from godot 3 too.

![godot4-modulate-bug](https://user-images.githubusercontent.com/4844464/155441279-5f45e920-0570-4550-b9bd-fac657206073.png)

### Steps to reproduce

1. create a sprite.
2. attach a new shader material to the sprite.
3. create a new visual shader to the material.
4. create a Texture2D node in visual shader editor.
5. connect Texture2D node to Output node.
6. change node modulate color, nothing happen.

### Minimal reproduction project

[Godot4-Shader-Modulate-Bug.zip](https://github.com/godotengine/godot/files/8128985/Godot4-Shader-Modulate-Bug.zip)

**Comment by Calinou** [comment] 2022-02-23 16:51
@harrisyu Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

**Comment by harrisyu** [comment] 2022-02-24 01:46
'Minimal reproduction project' was added.

**Comment by h0lley** [comment] 2022-03-03 23:28
although this examples uses visual shaders, it's probably duplicate of #49781

**Comment by Calinou** [comment] 2022-03-04 06:46
Duplicate of https://github.com/godotengine/godot/issues/49781.

**Closed by Calinou** 2022-03-04 06:46 UTC
Labels: bug, needs testing, topic:shaders
