### ISSUE TITLE
Godot crashes on Android port

### ISSUE THREAD

**Issue by WaterExpensive** [godotengine/godot#62883] opened 2022-07-10 13:33 UTC
### Godot version

4.0.dev (alpha11)

### System information

Xiaomi Pad 5, MiUI Global 13.0.3, Adreno 640, Vulkan (mobile)

### Issue description

Greetings,
I've been trying to use my android tablet (Xiaomi Pad 5) as a main machine to code with Godot. However, everything seems to be working fine until I press the Escape button to return to the code window, whereby the program crashes completely and I have to restart it in order to begin again.

https://user-images.githubusercontent.com/34092413/178146869-dbf42b0b-610a-4b6f-a16f-fc057094e6f4.mp4

As you can see in this video, I can run my code perfectly but when I return it crashes.

### Steps to reproduce

1- Download Godot 4 Alpha 11 for android from the official Godot website.
2- Create a project with the Vulkan Mobile renderer
3- Make a simple scene and run it in the Editor
4- Press the Escapr button on the keyboard to return to code (Alternatively, just use the back button in the android)

### Minimal reproduction project

[New Game.zip](https://github.com/godotengine/godot/files/9079162/New.Game.zip)
 This is the project I've created in the above video.

**Comment by Calinou** [comment] 2022-07-10 15:59
Duplicate of https://github.com/godotengine/godot/issues/61611.

**Closed by Calinou** 2022-07-10 15:59 UTC
Labels: platform:android, topic:editor

**Comment by WaterExpensive** [comment] 2022-07-10 23:40
Ah I see. Thank you for the workaround
