### ISSUE TITLE
Tween.stop_all() not canceling a currently running property interpolation

### ISSUE THREAD

**Issue by gramozilho** [godotengine/godot#51915] opened 2021-08-20 11:13 UTC
### Godot version

3.4.beta3

### System information

Windows 10

### Issue description

$Tween.stop_all() does not cancel a running interpolation. 

![Example](https://user-images.githubusercontent.com/56160987/130224819-2d10354b-18c1-4b1c-9d52-9f0083e5d4c3.gif).
In the minimal reproduction project pressing the up/down keys triggers movement up or down and updates the Label accordingly.

Happens with Control, PanelContainer and Sprite nodes.

In version 3.3.2.stable the $Tween.stop_all() behaves as expected.

### Steps to reproduce

- Tween the position of a control-like node for a few seconds.
- Interrupt with a $Tween.stop_all() and interpolate to another value.
- The control-like now will complete the second interpolation and the resume the initial tween.

### Minimal reproduction project

[TweenTest.zip](https://github.com/godotengine/godot/files/7021032/TweenTest.zip)

**Comment by kleonc** [comment] 2021-08-20 12:46
Most likely caused by the fix in #47142.

@gramozilho Seems like you want to use [`remove_all`](https://docs.godotengine.org/en/3.4/classes/class_tween.html#class-tween-method-remove-all) method instead of [`stop_all`](https://docs.godotengine.org/en/3.4/classes/class_tween.html#class-tween-method-stop-all) method.

**Comment by gramozilho** [comment] 2021-08-20 13:11
@kleonc this solves it! should I close the issue?

**Comment by kleonc** [comment] 2021-08-21 12:37
If both behavior and docs are fine then feel free to close it. I'm not sure if anything here needs to be clarified in the docs. :thinking:

**Comment by Calinou** [comment] 2021-08-21 19:40
Closing per @kleonc's comment.

**Closed by Calinou** 2021-08-21 19:40 UTC
Labels: documentation, topic:animation
