### ISSUE TITLE
Distraction mode keeps opening script editor (external editor) on every click.

### ISSUE THREAD

**Issue by viksl** [godotengine/godot#90847] opened 2024-04-18 12:03 UTC
### Tested versions

Reproducible: 4.3[3b1806182a3564736ad64793b203c2c13c251f56]
(it was ok in 4.3 master just couple days ago, I just don't know how far right now)

### System information

Windows 11 - Vulkan - Nvidia RTX 4070 - intel i5 13600KF

### Issue description

Watching the video is probably the best to see what happens but to briefly describe it.

Video: https://youtu.be/dGkHY-nPvoU

When I open a project now 4.3 master (doesn't matter which) - C# version - and open an external script editor once then when I press on the Distraction Free mode it keeps opening the external editor every time I press the button or press the shortcut.
It was not happening in a couple days old 4.3 master, I have no idea what changed.
If I open a new tab in the godot editor, switch to distraction free mode again then it doesn't happen anymore. But if I close the editor again and have it open through godot again then we are back and it keeps happening. I don't know why, it's not related to my project or to any particualr scene.
The same happens with the built in script editor.
I turned off the settings to open the dominant script and some other options in the editor but nothing chanes this behaviour.

### Steps to reproduce

See above.

### Minimal reproduction project (MRP)

N/A - not tied to any particular project, it's the editor issue.

**Comment by AeioMuch** [comment] 2024-04-18 14:08
Duplicate of https://github.com/godotengine/godot/issues/90654

**Comment by Sauermann** [comment] 2024-04-22 07:32
Consolidating in #90654. Thanks for your report. Please continue the discussion in that report.

**Closed by Sauermann** 2024-04-22 07:32 UTC
