### ISSUE TITLE
Exported properties not updating when using external editor

### ISSUE THREAD

**Issue by creikey** [godotengine/godot#33906] opened 2019-11-26 02:11 UTC
**Godot version:**
`Godot Engine v3.2.beta.calinou.636bc5c32`
**OS/device including version:**
arch linux
**Issue description:**
After exporting a new property in an external editor such as VsCode with the godot extension installed, the new exported property does not show up in the editor
**Steps to reproduce:**
1. Export property while editing a script in vscode
2. This property will not be visible in the editor
**Minimal reproduction project:**

**Comment by gururise** [comment] 2019-11-26 21:01
duplicate of #33896 ??

**Comment by creikey** [comment] 2019-11-27 04:06
@gururise yeah, what needs to happen is the editor needs to watch for changes in the filesystem. I'm not sure if there's a platform agnostic way to do so so probably new hooks in each platform file

**Comment by KoBeWi** [comment] 2019-11-28 13:00
Duplicate of #22144

**Closed by KoBeWi** 2019-11-28 13:00 UTC
