### ISSUE TITLE
Support for [ctrl] + [alt] + special character == [Alt Gr] + special character

### ISSUE THREAD

**Issue by kondelik** [godotengine/godot#6851] opened 2016-10-17 11:44 UTC
**Operating system or device - Godot version:** Windows & non-english keyboard layout - All versions

**Issue description:** When not using english keyboard, writing special chars like '>' and '<' (and many more) must be done with shortcut (right) <kbd>Alt Gr</kbd> + <kbd><</kbd>. Thats normal and fine, but on windows, lots of folks (like me) are used to (left) <kbd>ctrl</kbd> + (left)<kbd>alt</kbd> + <kbd><</kbd> which does not work and is very annoying (you know, you are used to _type_ code one way for 8+ years and then, this one editor does not support it).

Source: [https://en.wikipedia.org/wiki/AltGr_key#Control_.2B_Alt_as_a_substitute](https://en.wikipedia.org/wiki/AltGr_key#Control_.2B_Alt_as_a_substitute)

**Steps to reproduce:** 
set non english keyboard (czech in my case)
Godot -> script editor
<kbd>Alt gr</kbd> + <kbd>></kbd> = '>'
<kbd>Ctrl</kbd> + <kbd>Alt</kbd> + <kbd>></kbd> = ''

Every native windows app (eh, native... even GIMP support this):
<kbd>Ctrl</kbd> + <kbd>Alt</kbd> + <kbd>></kbd> = '>'

**Comment by tajmone** [comment] 2017-02-16 09:17
Same problem on Win 10, Italian keyboard: can't access Alt-Code characters via Numeric Pad inside Godot's editor.

Example: The Bitwise NOT tilde character `~` is not present in Italian keyboards, and requires using an alt-code  (<kbd>Alt</kbd><kbd>1</kbd><kbd>2</kbd><kbd>6</kbd>)  to display it. Currently the only way to produce a tilde in Godot's editor seems to be via cut-&-paste.

This is a list of commonly used characters which are not present in non-US keyboards and require an alt-code sequence under Windows OS:

* `~` tilde
* `` ` `` backtick

They are all crucial character in programming/development envinroment, yet uneasy to obtain on many keyboards (especially on laptops which don't have numeric pad and require additional keystrokes).

Since different keyboard layouts might suffer from different lacks of characters, it would be nice to have Godot editor support standard Windows alt-codes, or (even better) offer some keystroke-combinations customization to make some characters easily reachable. (for example, in SublimeText is rather easy to set up custom key-combination, like <kbd>Alt</kbd><kbd>'</kbd> for `` ` ``)

**Comment by tajmone** [comment] 2017-02-16 09:18
The only other current alternative I can think of is switching the keyboard layout to US-EN keyboard during work sessions, which isn't an ideal solution for other open tools which support alt-codes.

**Comment by phas0r** [comment] 2017-05-18 19:03
Is there an ETA on this? I don't know of any workaround. Is it complicated to support this?

**Comment by vnen** [comment] 2018-04-04 15:27
I remember looking at this but it's not that easy to fix (at least I couldn't find any good documentation).

**Comment by athal24** [comment] 2018-09-03 11:11
I have this same problem with Spanish keyboard, no Ctrl + Alt support. I can't use this engine like this and I see this problem is still here since 2016. I dont understand why this crucial issue is not being solved, I was enthusiast about this engine.

Godot 3.06 64 bits Windows 10

**Comment by Silinsar** [comment] 2018-11-04 23:01
Another bump for this, it's annoying to have to use uncommon / unpractised key combos on a QWERTZ keyboard layout to input symbols frequently needed when coding (~ | { } [ ]).

**Comment by Luna-Rex** [comment] 2020-03-16 18:52
This issue still affects both the Godot script editor and the various text editing nodes. (3.2) This unfortunately makes Godot much less useful for making internationally supported applications and games involving lots of text entry.

**Comment by tajmone** [comment] 2020-03-17 01:13
> This issue still affects both the Godot script editor and the various text editing nodes. (3.2)

I'm surprised that after four years this issue hasn't been solved yet. Also, it's quite rare to find editors that _don't_ support Alt-codes (after all, they are part of the native OS).

> This unfortunately makes Godot much less useful for making internationally supported applications and games involving lots of text entry.

Indeed, I agree on this. At least, for me this has been a major draw back that ultimately kept me away from Godot. It's not just because it makes coding a slow and painful process (which does matter), but also due to the fact that it makes Godot a rather US-centric app — i.e., assumes users are working on a US keyboard.

I can't wrap my head around this. It's something rare to find in editors, and makes you wonder.

**Comment by Calinou** [comment] 2020-03-17 08:33
> I'm surprised that after four years this issue hasn't been solved yet. 

I didn't even know <kbd>Ctrl</kbd> + <kbd>Alt</kbd> could be used as an alternative to <kbd>AltGr</kbd> until this issue was bumped yesterday :slightly_smiling_face: 

That said, that combination doesn't seem to work on Linux (using the "French - alternate" keyboard layout). I guess it's a Windows-only thing?

**Comment by tajmone** [comment] 2020-03-17 11:38
@Calinou:

> That said, that combination doesn't seem to work on Linux (using the "French - alternate" keyboard layout). I guess it's a Windows-only thing?

Yes, Alt-codes are Windows only, although often the term is used to indicate any shortcut to access special characters absent in a keyboard. There are some equivalent short cuts on *nix machines, but these might be distro specific; I remember that working on Ubuntu I had to struggle because whenever I needed to access a special char I'd go in «auto-mode» and use the Windows combinations, which of course did not work.

> Godot doesn't use a standard UI toolkit such as GTK+ or Qt, which may be a reason for this feature being absent. 

I also think that's the root of the problem. The advantage of using well established UI libraries is that they already take care of this low-level stuff. Alt-codes is usually an expected feature in editors and text input controls, so it's not something you'll see advertised with neon lights in the features list of such libraries (or any editing application), it's just something we all expect to be present, due to usage experience.

> I didn't even know Ctrl + Alt could be used as an alternative to AltGr until this issue was bumped yesterday

Actually, under Windows OS there are multiple ways to access special chars, depending on the required char (ASCII, Unicode, emoji, etc.), and in some cases on the application being used.

Probably the most important issue right now is being able to access standard ASCII characters which are required for coding (`~`, `` ` ``, etc.), rather than the whole Unicode characters set. Although probably the best cross-platform solution would be to leverage the native OS API that deals with these type of shortcuts (which should cover all characters) rather than writing a custom code that can intercept key-combinations in real time and convert them to the desired characters (I agree, this would be a non-trivial task).

**Comment by splite** [comment] 2020-03-17 12:58
Thanks for bump. Four years later and I'm still annoyed. (Godot hobbyist but full-time c# dev - so, lots and lots of code typed in Win :) )

**Comment by Luna-Rex** [comment] 2020-03-17 19:17
> I didn't even know Ctrl + Alt could be used as an alternative to AltGr until this issue was bumped yesterday 🙂

It can indeed. I _think_ Windows treats Ctrl + Alt and AltGr as functionally equivalent in most situations, with the possible exception of some specific keyboard layouts and system hotkeys. Although I'm not sure of specifics. (I know AltGr + Delete isn't possible though. 😋)

However, on some countries' keyboard layouts, constantly using AltGr instead of Ctrl + Alt can be pretty straining on the wrist and fingers. I've also met many people who don't even realize AltGr can be used for anything. Older people, schoolkids, and even some programmers and tech specialists.

A possible hack might be detecting when Ctrl + Alt is held and converting it to an AltGr input? Although with no knowledge of how Godot handles key input, I wouldn't be surprised if this is easier said than done, and might just introduce a bunch of other issues.

**Comment by tajmone** [comment] 2020-03-18 01:23
> A possible hack might be detecting when Ctrl + Alt is held and converting it to an AltGr input? Although with no knowledge of how Godot handles key input, I wouldn't be surprised if this is easier said than done, and might just introduce a bunch of other issues.

I think the problem here is providing a cross-platform solution. The best thing would be to find a ready-made library that leverages each OS native functionality and provides a good customization interface. I don't know of any, but there must something in the wild.

**Comment by akien-mga** [comment] 2020-03-18 07:18
It doesn't need to be cross-platform since it's a Windows feature. And it also shouldn't require any hacks as the OS should serve the input pre-processed if it's an OS feature, like Linux distros will do whenever you use AltGr or the Compose key to input special characters (which works out of the box on Godot and any Linux application).

So this needs look into how Windows' Ctrl+Alt == AltGr feature works internally, and then try to figure out why it's not working with Godot's input processing. Could be that Windows does not pre-processor the input and lets all applications do the handling manually, but if so that's pretty bad design on their end.

**Comment by tajmone** [comment] 2020-03-18 23:47
Good to know that at least on Linux Alt keys work as expected.

> So this needs looking into how Windows' Ctrl+Alt == AltGr feature works internally, 

The feature is available in any of Windows OS native text-input controls, coders don't have to do anything special to enable it. But I have no idea how the same functionality can be enabled in custom controls. Probably a good starting point would be to look at some cross platform third party GUI libraries that don't use Win native UI controls, check if they support Alt codes, and if they do find out how they managed that.

**Comment by tajmone** [comment] 2020-03-19 00:33
I've been peeking at MSDN documentation on keyboard input; the whole issue seems complicated by the fact that Alt codes work partly due to the keyboard (hardware + driver) itself, and partly due to how the WinAPI interprets these "virtual key" sequences.

What I did find, though, is a very interesting document by keyboard manufacturers:

- https://metacpan.org/pod/UI::KeyboardLayout

this rather lengthy document covers also the topic of special key combinations for generating Unicode chars, and goes into the nitty gritty of how Windows intercepts them, etc., also covering some undocumented features. So the above link might be helpful (and at least it's all in a single page).

As of MSDN, these links are probably good starting points:

- https://docs.microsoft.com/en-us/windows/win32/learnwin32/keyboard-input 
- https://docs.microsoft.com/en-us/windows/win32/inputdev/keyboard-input

**Comment by akien-mga** [comment] 2021-01-05 13:44
Reopening as #37769 was reverted by #44935.

**Comment by juse4pro** [comment] 2021-03-31 12:48
Players of my game mostly use a German keyboard layout and can not enter the "@" character with Ctrl-Alt-Q. Which is pretty bad because they have to enter an mail address to login the game.

Too bad that the fix generated some regression issues. :(

**Comment by madmiraal** [comment] 2021-04-18 08:37
The problem here is that the issue is normally the other way around i.e. people wanting to disable `Ctrl`+`Alt` == `Alt Gr` on Windows, because many applications use `Ctrl`+`Alt`+`<some key>` as shortcuts; especially web applications like Google docs [[1](https://superuser.com/questions/592970/can-i-make-ctrlalt-not-act-like-altgr-on-windows)] and even Microsoft's own OneNote 365 [[2](https://answers.microsoft.com/en-us/msoffice/forum/msoffice_onenote-mso_win10-mso_o365b/disable-ctrlalt-altgr/78fff2b4-c20c-4408-9547-e323114ae522)].

Godot also uses a number of `Ctrl`+`Alt`+`<some key>` shortcuts e.g. `Ctrl`+`Alt`+`S` to save the current script or `Ctrl`+`Alt`+`O` to quickly open a script. Therefore, without disabling all `Ctrl`+`Alt`+`<some key>` shortcuts, it's impossible to make `Ctrl`+`Alt` == `Alt Gr`.

As @akien-mga [suggests](https://github.com/godotengine/godot/issues/6851#issuecomment-600462791), it's a bad design on Microsoft's part, but as the [link](https://en.wikipedia.org/wiki/AltGr_key#Control_.2B_Alt_as_a_substitute) in the OP explains, it was implemented as a work around, because "_Originally, US PC keyboards (specifically, the US 101-key PC/AT keyboards) did not have an AltGr key because it was relevant only in non-US markets: US keyboards simply had "left" and "right" Alt keys._" Although it's worth noting that "_some compact keyboards like those of netbooks, the right Alt key may be missing altogether._" [[3](https://en.wikipedia.org/wiki/AltGr_key#Control_.2B_Alt_as_a_substitute)]

Ultimately, having `Ctrl`+`Alt` == `Alt Gr` would need to be a non-default option in the editor or project settings, because the side-effect would be all the `Ctrl`+`Alt`+`<some key>` shortcuts would be disabled.

**Comment by EricEzaM** [comment] 2021-04-18 13:08
I believe on keyboard with an `AltGr` key, it is only on the right hand side alt? Left had side is still the same?

If that is the case, if #43888 is ever merged it could potentially be used to solve this issue.

**Comment by kondelik** [comment] 2021-04-18 18:04
>The problem here is that the issue is normally the other way around i.e. people wanting to disable Ctrl+Alt == Alt Gr on Windows, because many applications use (...)

Still vast majority of users are BFU and not power users. It work in Notepad, it should work in godot TextBox. Whats the difference, really? (Well - i know what the difference is, you know that too, ordinary user doesnt have slightest idea.)

That `@` in germany is great example. Well, if i press <kbd>L Ctrl</kbd> + <kbd>L Alt</kbd> + <kbd>2</kbd> in Google Doc you know what happens? It write `ˇ` - and i am totally ok with that, becouse it is CONSISTENT with any other app i am using. But not godot.

> I believe on keyboard with an AltGr key, it is only on the right hand side alt? Left had side is still the same?

Yes, it is:

<kbd>L Ctrl</kbd> + <kbd>L Alt</kbd> + <kbd>v</kbd> = `@`
<kbd>R Ctrl</kbd> + <kbd>R Alt</kbd> (= AltGr) + <kbd>v</kbd>) = `@` (not sure if this isnt the same as alt gr+
<kbd>Alt Gr</kbd> (thats the one on the right side) + <kbd>v</kbd> = `@`
<kbd>Alt</kbd> (thats the one on the left side) + <kbd>v</kbd> = (no char)

(I am literally pressing the keys right here & right now)

**Comment by EricEzaM** [comment] 2021-04-18 22:04
What happens in VS code for example?

If you have a shortcut bound to ctrl shift V, for example, what will it do?

**Comment by kondelik** [comment] 2021-04-19 11:59
Anyway:

@madmiraal 
> The problem here is that the issue is normally the other way around

Can you be more specific about "normally"? I dont think your linked stack oveflow question with +/- 40 upvotes can represent the general opinion on (yes, poor&flawed, but used*) i18n design choice.

>Ultimately, having Ctrl+Alt == Alt Gr would need to be a non-default option in the editor or project settings, because the side-effect would be all the Ctrl+Alt+<some key> shortcuts would be disabled.

Let me disagree:

You are thinking about it like it is some "whole world on/whole world off" checkbox somewhere (in editor / project settings) but that is not the right approach - thats oversimplification of somewhat complex i18n problem.

I am not talking about script editor, but mainly I care about ingame textboxes - but because godot editor is "ingame editor by design" in the end it is the same thing.

Yes, for foreign keyboard it will be disabled. If you're used to "there arent any <kbd>ctrl</kbd> + <kbd>alt</kbd> shortcuts because thats shortcut for <kbd>AltGr</kbd>" you will be confused when things work differently.
Yes, for en-keyboard you will be confused that your <kbd>ctrl</kbd> + <kbd>alt</kbd>+<kbd>s</kbd> doesnt work.
No, you cant solve it with "opt-in/out" - there will still be a subset of confused users (worse, confused customers). You have to be consistent with OS. There is no other way: What if i want to ship my game to EN and Germany? Should i enable it or disable it for ingame textboxes? And then, when i enable it: what about EN? When i disable it, what about Germany? This "opt-in/out" is not a solution.

It is complex i18n problem and because Godot decided to roll own keyboard setting (because reasons) and ignore every other keyboard settings then ENG setting, [we have problem with customers from germany  (and... you know... rest of the world...) who cant write `@` to login box.](#issuecomment-811041180) Thats showstopper for many.

Please, be consistent with whole world. On ENG (and other?) keyboard settings yes, disable it. On foreign keyboard settings no, enable it. Its much deeper (and thats why it is problematic) i18n system setting then some checkbox setting in project (or `|| (k->get_command() && k->get_alt())` as in #37769 )

*:By the way, i asked my colegue to write `@` on his non-EN keyboard - without thinking, he wrote it with <kbd>L Alt</kbd> + <kbd>numpad 6</kbd> -> <kbd>numpad 4</kbd> = `@` -- and surprise, in Godot [alt - codes](https://en.wikipedia.org/wiki/Alt_code) doesn't work either. So the underlaying problem is much deeper then <kbd>ctrl</kbd> + <kbd>alt</kbd>.

**Comment by kondelik** [comment] 2021-04-19 12:05
> What happens in VS code for example?
> 
> If you have a shortcut bound to ctrl shift V, for example, what will it do?

Well, i dont have any :)

![image](https://user-images.githubusercontent.com/4945875/115233069-bf419c80-a117-11eb-9fb9-bc17b6b89c01.png)

I added one just for you:
![image](https://user-images.githubusercontent.com/4945875/115233316-06c82880-a118-11eb-9f8d-a6c144e4b4ba.png)
(please note this conflict with `@` char )

and...

(... testing :) ... )

It stopped writing `@` and start saving document. Shortcut just override key print.

**Closed** 2022-04-05 12:03 UTC
Labels: bug, platform:windows, topic:core, confirmed, topic:input

**Comment by DavidMag** [comment] 2022-04-10 12:16
@akien-mga
Im still getting this issue using the alpha6 version.
Attaching video, of course you cannot see what I'm actually pressing but Im pressing left option key + 2 which in Swedish keyboard layout is @, reproduced in 4.0.alpha6 on a intel 16" MacBook Pro running macOS Monterey 12.3.1.

https://user-images.githubusercontent.com/22000931/162617622-41f3faa1-35b3-4b0b-9deb-9c8bf922b2f2.mov

**Comment by bruvzg** [comment] 2022-04-10 12:23
> Im still getting this issue using the alpha6 version.

There are some default shortcuts using `Alt+`, you can unbind or change them in the editor settings to enabled input.

<img width="868" alt="Screenshot 2022-04-10 at 15 21 04" src="https://user-images.githubusercontent.com/7645683/162617896-27986946-d937-457b-ae8e-befc49ebcbe6.png">

**Comment by DavidMag** [comment] 2022-04-10 14:35
> > Im still getting this issue using the alpha6 version.
> 
> There are some default shortcuts using `Alt+`, you can unbind or change them in the editor settings to enabled input.
> 
> <img alt="Screenshot 2022-04-10 at 15 21 04" width="868" src="https://user-images.githubusercontent.com/7645683/162617896-27986946-d937-457b-ae8e-befc49ebcbe6.png">

Lifesaver, thank you 🙏

**Comment by bruvzg** [comment] 2022-04-11 09:49
A list of shortcuts conflicting with input:

- `file_dialog/toggle_favorite` - ALT + F - `ƒ` on macOS U.S. English keyboard (as input example).
- `file_dialog/toggle_mode` - ALT + V - `√`
- `editor/quick_open` - SHIFT + ALT + O - `Ø`
- `editor/quit_to_project_list` - SHIFT + ALT + Q - `Œ`
- `editor/editor_2d` - ALT + 1 - `¡`
- `editor/editor_3d` - ALT + 2 - `™`
- `editor/editor_script` - ALT + 3 - `£`
- `editor/editor_assetlib` - ALT + 4 - `¢`
- `script_text_editor/toggle_fold_line` - ALT + F

We probably should change them to something else by default.

**Comment by DavidMag** [comment] 2022-05-01 12:07
So it really feels like I'm nagging here but the shortcuts seems to reset every time I restart the Godot, should I report a separate issue on that?
