### ISSUE TITLE
Editor Camera Bug

### ISSUE THREAD

**Issue by CCODE05B** [godotengine/godot#16210] opened 2018-01-30 21:36 UTC
**Godot version:**
Godot 3 official release

**Issue description:**
When navigating in the Editor using WASD keys and mouse .. you can stuck in free looking mode

**Steps to reproduce:**
start navigating using WASD keys and mouse .. then do mouse wheel up or down , now if you release every key you can still rotate the Editor camera and look around .. this should not happen

**Comment by Zylann** [comment] 2018-01-30 23:54
Similar to https://github.com/godotengine/godot/issues/14373#issuecomment-350515100, the input system again seems to ignore the event where RMB is released...

**Comment by Chaosus** [comment] 2018-08-19 12:56
Closed as duplicate of #14373 (and looks like its fixed already)

**Closed by Chaosus** 2018-08-19 12:56 UTC
Labels: bug, topic:editor, usability
