### ISSUE TITLE
starting godot "ERROR: Resource file not found: res://InputEventKey_*"

### ISSUE THREAD

**Issue by magian1127** [godotengine/godot#78038] opened 2023-06-09 09:23 UTC
### Godot version

4.1b

### System information

win11

### Issue description

Just reporting an error, no other impact found.
![image](https://github.com/godotengine/godot/assets/14800320/d5c322a2-10f1-4361-a7a6-2f8d7cb9188d)

### Steps to reproduce

Editor -> Editor Settings -> Shortcuts -> Set any shortcut key
![image](https://github.com/godotengine/godot/assets/14800320/4c27b7e9-9d46-489c-9bf8-87eb3c9bbcb4)

### Minimal reproduction project

NOT REQUIRED

**Comment by raulsntos** [comment] 2023-06-09 09:30
Duplicate of https://github.com/godotengine/godot/issues/76384

**Closed by raulsntos** 2023-06-09 09:30 UTC
