### ISSUE TITLE
Engine crashes on Android when OTG keyboard is plugged in

### ISSUE THREAD

**Issue by 3demax** [godotengine/godot#8032] opened 2017-03-15 04:00 UTC
**Platform:** Android 5.1.1 - Godot v2.1.2

**Issue description:**
I have created simple game that reacts to keys W and S. Exported game runs fine without keyboard connected. 
When I connect usb keyboard via OTG cable while game is running, it crashes.
When I first plug the keybord, then run the game, it doesn't react to key presses.

Expectation is for keyboard to function properly whenever it's plugged before or while running an app.

Crash log: [otg_keyboard_crash.txt](https://github.com/godotengine/godot/files/843400/otg_keyboard_crash.txt)

**Steps to reproduce:**
1) install apk
2) run game
3) connect keyboard via otg
4) see the game crashed

**Link to minimal example project:**
[test_project.zip](https://github.com/godotengine/godot/files/843402/test_project.zip)

**Comment by kubecz3k** [comment] 2018-04-10 16:35
First of all thank you for your report and sorry for the delay.

We released Godot 3.0 in January 2018 after 18 months of work, fixing many old issues either directly, or by obsoleting/replacing the features they were referring to.

We still have hundreds of issues whose relevance/reproducibility needs to be checked against the [current stable version](https://godotengine.org/download), and that's where you can help us.
**Could you check if the issue that you described initially is still relevant/reproducible in Godot 3.0 or any newer version, and comment about its current status here?**

For bug reports, please also make sure that the issue contains detailed steps to reproduce the bug and, if possible, a zipped project that can be used to reproduce it right away. This greatly speeds up debugging and bugfixing tasks for our contributors.

Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

Thanks in advance.

*Note: This message is being copy-pasted to many "stale" issues (90+ days without activity). It might happen that it is not meaningful for this specific issue or appears oblivious of the issue's context, if so please comment to notify the Bugsquad about it.*

**Comment by ProbDenis** [comment] 2018-12-21 12:13
I can confirm that this bug still exists. I can reproduce it with a Bluetooth keyboard. When the keyboard is already connected, it seems to work just fine and I can use it to type text in LineEdit nodes etc. When it's not connected, the on-screen keyboard works just as well. However, when the keyboard connects or disconnects _while the app is running_, it crashes the engine. The remote debug doesn't output any error messages and just quits.
This is particularly annoying, since these keyboards usually disconnect after a while and connect again when a key is pressed.

**Comment by Anutrix** [comment] 2019-08-12 14:25
Any updates? Is this still reproducible with the latest master build?

**Comment by akien-mga** [comment] 2020-07-26 23:10
No answer, so closing.

Please comment if you can still reproduce it.

**Closed by akien-mga** 2020-07-26 23:10 UTC
Labels: bug, confirmed, platform:android, topic:input, topic:porting
