### ISSUE TITLE
Cpp documentation request

### ISSUE THREAD

**Issue by AdarshRise** [godotengine/godot#38404] opened 2020-05-02 01:55 UTC
First, Thankyou for making this awesome game engine.

I have been following Godot for a year now, and always wanted to dive in, but two things held me back,
 1: I wanted to start with 3D than of 2D 2: I wanted to start with CPP as my core language.

I knew that Godot is capable of doing both, just that it's a bit harder and time consuming, than going with 2D and GDscript.

I thought I will give it a shot, but kinda got lost in CPP documentation, and read at many places that C# documentation is better than Cpp's.

**Request: Please, I see Godot 4.0 as the engine I was looking for, before you release it's stable Version, do focus on providing better CPP documentation with a lot of examples.**

Thankyou once again =)

**Comment by clayjohn** [comment] 2020-05-02 02:04
Are you referring to scripting your game in C++ via GDNative or are you asking for documentation of the C++ source code?

**Comment by avril-gh** [comment] 2020-05-02 04:39
> I knew that Godot is capable of doing both, just that 3D is a bit harder and time consuming.

this is stereotype from times before engines, where everything had to be written from scratch.
With Godot, 3D is as easy as 2D, just one more coordination axis,
and with GDScript built straight in editor - its ultra rapid development.

**Comment by Xrayez** [comment] 2020-05-02 07:49
@AdarshRise additionally, you can look at some [tests](https://github.com/godotengine/godot/tree/master/main/tests) to learn C++ development which look more like real-life examples (mainly instantiating a `MainLoop` and other core stuff not typically seen in GDScript).

**Comment by AdarshRise** [comment] 2020-05-02 10:52
> Are you referring to scripting your game in C++ via GDNative or are you asking for documentation of the C++ source code?

I meant, making games directly using Cpp

**Comment by AdarshRise** [comment] 2020-05-02 10:56
> > I knew that Godot is capable of doing both, just that 3D is a bit harder and time consuming.
> 
> this is stereotype from times before engines, where everything had to be written from scratch.
> With Godot, 3D is as easy as 2D, just one more coordination axis,
> and with GDScript built straight in editor - its zero compile time ultra rapid development / debugging

Indeed, I too plan to create prototypes in GDscript, But once I am satisfied with it. I plan to rebuild it using CPP. So, a good documentation will help in this transition.

**Comment by AdarshRise** [comment] 2020-05-02 10:58
> @AdarshRise additionally, you can look at some [tests](https://github.com/godotengine/godot/tree/master/main/tests) to learn C++ development which look more like real-life examples (mainly instantiating a `MainLoop` and other core stuff not typically seen in GDScript).

Yeah, they look very useful.

**Comment by Calinou** [comment] 2020-05-02 12:00
Duplicate of #5312.

**Closed by Calinou** 2020-05-02 12:00 UTC
