### ISSUE TITLE
Collision shape outline issue in top left

### ISSUE THREAD

**Issue by mlepage** [godotengine/godot#59591] opened 2022-03-27 17:48 UTC
### Godot version

Godot 4 alpha 5

### System information

Windows 11

### Issue description

The outline of a rect collision shape has an anomoly in the top left, and along the top edge.

The top left is missing a chunk, and the top edge of the rect has inconsistent thickness (seems to go from thicker on the left to thinner on the right). See screenshot.

![image](https://user-images.githubusercontent.com/590016/160293924-2ba7b3d5-4f92-40d1-9c50-b2a57b732e75.png)

### Steps to reproduce

Make a rect CollisionShape2D, zoom in and examine it. Seems reproducible.

**Comment by mlepage** [comment] 2022-03-27 17:50
I would assume this has to do with how the outline is "stroked"? It would be nice if it could be cleaned up.

**Comment by Calinou** [comment] 2022-03-27 17:56
Duplicate of https://github.com/godotengine/godot/issues/56320.

**Closed by Calinou** 2022-03-27 17:56 UTC
