### ISSUE TITLE
.ogg files path change after Exporting game

### ISSUE THREAD

**Issue by LavandePotions** [godotengine/godot#70266] opened 2022-12-18 17:40 UTC
### Godot version

3.5

### System information

Windows 10

### Issue description

With gdscript you can load an .ogg file by its path like this one :
```gdscript
var music_path = 'res://Symphony-Nr-5-in-C-Minor-(1st-Movement).ogg'
```
But when you export the game, without telling you, Godot change the path inside the .pck from .ogg to .oggstr with some md5 hash
```gdscript
var exported_path_in_pck = 'res://.import/Symphony-Nr-5-in-C-Minor-(1st-Movement).ogg-ddee16cf28ebd776db9cd88d611ab1f8.oggstr'
```
I had to load the .pck with GodotPckExplorer to notice the change.

After some discutions on the Godot Engine Discord, one the Godot dev tell me :

> Godot does some preprocessing on the ogg stream [...], so the preprocessed-serialized stream gets put into an oggstr file and then that's what gets included in the export

### Steps to reproduce

1. Import an .ogg file.
2. Export the game.
3. Open the .pck file (with program like GodotPckExplorer)
4. Compare the path before and after export.

### Minimal reproduction project

In this project there is one scene with an AudioStreamPlayer
The .ogg file is loaded by script

![image](https://user-images.githubusercontent.com/120951599/208310426-161dccc7-5494-4f81-987c-320f946c93f7.png)

Run from the editor the game load the .ogg correctly.
But if you run the exported .exe the .ogg path is broken.

[GodotOggExportIssue.zip](https://github.com/godotengine/godot/files/10254296/GodotOggExportIssue.zip)
or link to the repo
https://github.com/LavandePotions/lpGodotOggExportIssue

**Comment by KoBeWi** [comment] 2022-12-18 19:32
Duplicate of #25672
Use `load()` and `ResourceLoader.exists()` for files within the project.

**Closed by KoBeWi** 2022-12-18 19:32 UTC
