### ISSUE TITLE
Path to node error with Viewports.

### ISSUE THREAD

**Issue by avencherus** [godotengine/godot#44024] opened 2020-12-02 00:20 UTC
**Godot version:**

037a6c5b574316b8475f4886e37fb50a8b12be50

**OS/device including version:**

Win10

**Issue description:**

When using a viewport with camera in a scene, the editor regularly throws the following error.  *Seems to be caused by the assignment of the Viewport Texture in the inspector, combined with saving the scene.*

![image](https://user-images.githubusercontent.com/13004169/100812036-c310a300-3444-11eb-9436-fafddb8e28bb.png)

**Steps to reproduce:**
A setup like this should reproduce it.  MRP below.
![image](https://user-images.githubusercontent.com/13004169/100812068-d15ebf00-3444-11eb-9af8-bc6432cd74d0.png)

**Minimal reproduction project:**

[Path to Node Error.zip](https://github.com/godotengine/godot/files/5626184/Path.to.Node.Error.zip)

**Comment by avencherus** [comment] 2020-12-02 00:24
Stack looks like it might be related to saving.

```
Node::get_node(const NodePath & p_path) Line 1381	C++
ViewportTexture::setup_local_to_scene() Line 68	C++
ViewportTexture::set_viewport_path_in_scene(const NodePath & p_path) Line 93	C++
MethodBind1<ViewportTexture,NodePath const &>::call(Object * p_object, const Variant * * p_args, int p_arg_count, Variant::CallError & r_error) Line 867	C++
ClassDB::set_property(Object * p_object, const StringName & p_property, const Variant & p_value, bool * r_valid) Line 1049	C++
Object::set(const StringName & p_name, const Variant & p_value, bool * r_valid) Line 423	C++
Resource::duplicate_for_local_scene(Node * p_for_scene, Map<Ref<Resource>,Ref<Resource>,Comparator<Ref<Resource>>,DefaultAllocator> & remap_cache) Line 186	C++
SceneState::instance(SceneState::GenEditState p_edit_state) Line 244	C++
PackedScene::instance(PackedScene::GenEditState p_edit_state) Line 1698	C++
EditorNode::_save_scene(String p_file, int idx) Line 1433	C++
EditorNode::_save_scene_with_preview(String p_file, int p_idx) Line 1303	C++
EditorNode::_run(bool p_current, const String & p_custom) Line 2131	C++
EditorNode::run_play() Line 4656	C++
EditorNode::_menu_option_confirm(int p_option, bool p_confirmed) Line 2508	C++
EditorNode::_menu_option(int p_option) Line 985	C++
MethodBind1<EditorNode,int>::call(Object * p_object, const Variant * * p_args, int p_arg_count, Variant::CallError & r_error) Line 867	C++
Object::call(const StringName & p_method, const Variant * * p_args, int p_argcount, Variant::CallError & r_error) Line 919	C++
Object::emit_signal(const StringName & p_name, const Variant * * p_args, int p_argcount) Line 1246	C++
Object::emit_signal(const StringName & p_name, const Variant & p_arg1, const Variant & p_arg2, const Variant & p_arg3, const Variant & p_arg4, const Variant & p_arg5) Line 1304	C++
BaseButton::_pressed() Line 135	C++
BaseButton::on_action_event(Ref<InputEvent> p_event) Line 167	C++
BaseButton::_gui_input(Ref<InputEvent> p_event) Line 64	C++
MethodBind1<BaseButton,Ref<InputEvent>>::call(Object * p_object, const Variant * * p_args, int p_arg_count, Variant::CallError & r_error) Line 867	C++
Object::call_multilevel(const StringName & p_method, const Variant * * p_args, int p_argcount) Line 761	C++
Object::call_multilevel(const StringName & p_name, const Variant & p_arg1, const Variant & p_arg2, const Variant & p_arg3, const Variant & p_arg4, const Variant & p_arg5) Line 862	C++
Viewport::_gui_call_input(Control * p_control, const Ref<InputEvent> & p_input) Line 1688	C++
Viewport::_gui_input_event(Ref<InputEvent> p_event) Line 2068	C++
Viewport::input(const Ref<InputEvent> & p_event) Line 2861	C++
Viewport::_vp_input(const Ref<InputEvent> & p_ev) Line 1453	C++
MethodBind1<Viewport,Ref<InputEvent> const &>::call(Object * p_object, const Variant * * p_args, int p_arg_count, Variant::CallError & r_error) Line 867	C++
Object::call(const StringName & p_method, const Variant * * p_args, int p_argcount, Variant::CallError & r_error) Line 919	C++
Object::call(const StringName & p_name, const Variant & p_arg1, const Variant & p_arg2, const Variant & p_arg3, const Variant & p_arg4, const Variant & p_arg5) Line 845	C++
SceneTree::call_group_flags(unsigned int p_call_flags, const StringName & p_group, const StringName & p_function, const Variant & p_arg1, const Variant & p_arg2, const Variant & p_arg3, const Variant & p_arg4, const Variant & p_arg5) Line 275	C++
SceneTree::input_event(const Ref<InputEvent> & p_event) Line 431	C++
InputDefault::_parse_input_event_impl(const Ref<InputEvent> & p_event, bool p_is_emulated) Line 442	C++
InputDefault::parse_input_event(const Ref<InputEvent> & p_event) Line 260	C++
InputDefault::flush_accumulated_events() Line 679	C++
OS_Windows::process_events() Line 2660	C++
OS_Windows::run() Line 3459	C++
widechar_main(int argc, wchar_t * * argv) Line 162	C++
_main() Line 184	C++
main(int _argc, char * * _argv) Line 196	C++
```

**Comment by Calinou** [comment] 2020-12-02 14:34
Duplicate of https://github.com/godotengine/godot/issues/27790.

**Closed by Calinou** 2020-12-02 14:34 UTC
