### ISSUE TITLE
Clip Contents has no effect on TextEdit Control

### ISSUE THREAD

**Issue by wyattbiker** [godotengine/godot#89918] opened 2024-03-26 19:18 UTC
### Tested versions

v4.3.dev3.official [36e943b6b]

### System information

Linux Kubuntu 23.04 KDE Plasma Version: 5.27.4 KDE Frameworks Version: 5.104.0 Qt Version: 5.15.8

### Issue description

Clip Contents property has no effect on TextEdit. Although the default is Off, it behaves as if it is always On.

### Steps to reproduce

Add a `TextEdit` to a scene and add a child `Label` or `Button` with some description and or background colors. Drag the `Label` or `Button` control away, you will notice it gets clipped. Trying to adjust Clip Contents to on or off, has no effect. I only noticed it with `TextEdit`. Other controls obey the Clip Contents setting.

This code will not work either:
```gdscript
extends TextEdit

func _ready():
	clip_contents=false
```
But this code works:

```gdscript
func _draw() -> void:
	RenderingServer.canvas_item_set_clip(get_canvas_item(), false)

```

Attached is sample screen shot  with `TextEdit` and `Label` and `Button` as children. The other controls obey Clip Content

![image](https://github.com/godotengine/godot/assets/930478/e9e80414-0d79-4152-a3e8-5b257f655979)

### Minimal reproduction project (MRP)

See screen shot and description.

**Comment by MrPersonDev** [comment] 2024-03-27 17:24
Does anyone know why clipping is set to true [here](https://github.com/godotengine/godot/blob/7d151c83811f8ac8873439826c16d88c83aba12f/scene/gui/text_edit.cpp#L542)?
```
void TextEdit::_notification(int p_what) {
	// ...
	case NOTIFICATION_DRAW: {
		// ...
		RID ci = get_canvas_item();
		RenderingServer::get_singleton()->canvas_item_set_clip(get_canvas_item(), true);
		int xmargin_beg = theme_cache.style_normal->get_margin(SIDE_LEFT) + gutters_width + gutter_padding;
		// ...
	} break;
	// ...
}
```

Changing it to 
```
RenderingServer::get_singleton()->canvas_item_set_clip(get_canvas_item(), is_clipping_contents());
```
seems to work for me, but I don't want to break some important functionality.

**Comment by wyattbiker** [comment] 2024-03-29 19:56
This should be a bug, not an ehnacement. The user should be allowed to chek/uncheck clipping as desired.

**Comment by AThousandShips** [comment] 2024-03-29 20:01
It's not a bug, it's a missing feature, so that's considered an enhancement

**Comment by wyattbiker** [comment] 2024-03-29 22:52
FYI: The **Clip Contents** (`clip_contents`) checkbox for `TextEdit` is there in the inspector. See my screenshot above. It just doesn't do anything when you click it on on/off, but it is saved and loaded with the scene.

**Comment by Sauermann** [comment] 2024-03-31 11:31
It could be argued, that this is a bug, because changing `clip_contents` has no effect. I believe it is in the gray area between the two and changing it will not have an impact on when the pull request gets merged.

**Closed** 2024-04-04 12:45 UTC
Labels: enhancement, topic:gui
