### ISSUE TITLE
Clicking the Preset selection bar in the Theme section of Editor Settings again after theme changes causing the bar to disappear after a short time

### ISSUE THREAD

**Issue by MXH-program** [godotengine/godot#43919] opened 2020-11-27 14:33 UTC
- Godot version: v3.2.4.beta.custom_build

- OS/device including version: Windows 10 Home on Legion Y7000 2019 PG0

- Issue description:

After a theme is selected and changed under Preset in the Theme section of Editor Settings, when the Preset selection bar is clicked again, the bar disappeared after a short time without choosing any of the themes. 

Here is a GIF to better illustrate the issue:

![Preset-Issue](https://user-images.githubusercontent.com/73571300/100457936-e31b2c00-30fd-11eb-99b3-6fbecd76caf0.gif)

**Comment by Calinou** [comment] 2020-11-27 14:38
This is because the editor is recreating its theme after a short delay when a setting is changed.

**Comment by MXH-program** [comment] 2020-11-27 14:45
So the new theme is actually not completely recreated even if the colour scheme changes?

**Comment by Calinou** [comment] 2020-11-27 14:46
@MXH-program The theme is recreated correctly, it's just that the act of recreating the theme will reset the Editor Settings dialog to its "default" state. The same issue also happens with color pickers.

**Comment by Calinou** [comment] 2020-11-27 14:47
Duplicate of https://github.com/godotengine/godot/issues/23626.

**Closed by Calinou** 2020-11-27 14:47 UTC

**Comment by MXH-program** [comment] 2020-11-27 14:49
Ok thanks!
