### ISSUE TITLE
Godot not responding when saving project

### ISSUE THREAD

**Issue by MrSirDolph** [godotengine/godot#67007] opened 2022-10-06 23:16 UTC
### Godot version

v4.0.beta2.mono.official [f8745f2f7]

### System information

Windows 11 Home. RTX 2070 Version 517.48, Mobile Renderer

### Issue description

Every time I try to open Godot (doesn't matter whether it's mono or not) it takes a long time than it usually should to open project explorer and takes even longer to open the actual project itself. When I try to save the project it just freezes, this never happened before and only on my Alienware m17 r3 did this recently start happening. Yes, I reinstalled  NET .6 multiple times for the mono support but no luck.

### Steps to reproduce

???

**Comment by Calinou** [comment] 2022-10-07 17:26
Can you reproduce this without .NET (in a pure GDScript project)?

**Comment by MrSirDolph** [comment] 2022-10-07 20:59
> 

I will try that now

**Comment by MrSirDolph** [comment] 2022-10-07 21:06
> Can you reproduce this without .NET (in a pure GDScript project)?

Yep the same thing happened, but I have realized its only when I save the valve hand models

**Comment by Calinou** [comment] 2022-10-07 21:53
> Edit: It does end up saving, but it takes way longer than it should

You probably have mesh data (or something else like VoxelGIData) embedded within the scene. Save it to external resources instead. If you used Ctrl + C to copy nodes, this likely occurred because of https://github.com/godotengine/godot/issues/66991.

**Comment by MrSirDolph** [comment] 2022-10-07 22:33
> > Edit: It does end up saving, but it takes way longer than it should
> 
> You probably have mesh data (or something else like VoxelGIData) embedded within the scene, which causes it to be serialized as Base64 in a `.tscn` file (which is slow). Save it to external binary resources (`.res`) instead. If you used Ctrl + C to copy nodes, this likely occurred because of #66991.

Yep seems like the problem, I dragged the nodes in aswell as instansiated them and it was still slow.

**Comment by Calinou** [comment] 2022-10-07 22:49
Duplicate of https://github.com/godotengine/godot/issues/29381 and/or https://github.com/godotengine/godot/issues/33379.

**Closed by Calinou** 2022-10-07 22:49 UTC
Labels: bug, topic:editor, needs testing, topic:dotnet
