### ISSUE TITLE
Multiple node types glitching, disappearing and moving irregularly

### ISSUE THREAD

**Issue by eltharionx** [godotengine/godot#46639] opened 2021-03-03 23:02 UTC
**Godot version:**
Godot v3.2.4.rc3.official

**OS/device including version:**
Windows 7
GLES3
OpenGL ES 3.0 Renderer: ATI Radeon HD 5450
OpenGL ES Batching: ON

**Issue description:**
Game works 100% perfectly with Godot 3.2.3

When running the game with Godot 3.2.4 RC3, various nodes flicker on/off and show up in other places.  Please see link for a video capture of issue.

VIDEO OF ISSUE:
https://vimeo.com/519264212

Pretty much everything shown in the video above should not be moving.  The text should not move/disappear, neither the artwork in the background.  Even the the starting scene should be all black with the logo "Telestians" in the center.

**Comment by Calinou** [comment] 2021-03-03 23:45
cc @lawnjelly 

@eltharionx Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

This is likely an issue with the BVH. You can disable it in the Project Settings as a worakround.

**Comment by eltharionx** [comment] 2021-03-03 23:59
@Calinou Interesting... You are correct, when I turned off Batching in the Project Settings (Save & Restarted the Editor) there no longer is an issue.  However, looking in my Project Settings for v3.2.3 I have both "Use Batching" and "Use Batching in Editor" turned on and it works perfectly.

I am unable to use GLES2 as much of the core game requires nine-patch tiling, which is still an outstanding (or dead?) issue on GLES2 - https://github.com/godotengine/godot/issues/26168
cc @lawnjelly

Would a minimal project still be helpful in this case?  I could try to create one...

**Comment by Calinou** [comment] 2021-03-04 00:01
> However, looking in my Project Settings for v3.2.3 I have both "Use Batching" and "Use Batching in Editor" turned on and it works perfectly.

In 3.2.3, batching is only implemented in GLES2. In 3.2.4beta1 and later, it's also implemented in GLES3 with a new unified approach.

> Would a minimal project still be helpful in this case? I could try to create one...

Yes, always :slightly_smiling_face:

**Comment by eltharionx** [comment] 2021-03-04 00:03
Interesting, I didn't even consider that for 3.2.3 it was only used for GLES2 and ignored for GLES3.

OK, I'll try to put together a minimal project here within the next 24 hours.  Thank you

**Comment by lawnjelly** [comment] 2021-03-04 08:04
Note there are some differences to ninepatch behaviour (and the defaults for ninepatches) in 3.2.4. In particular if you look in `rendering/quality/ninepatchmode` there is a setting to try (you may need to restart). But yes a minimal reproduction project should show what the problem is. :+1:

**Comment by eltharionx** [comment] 2021-03-06 00:03
Hello, I have attached a minimal reproduction project that show the node glitching, and placed incorrectly when the project is run.  Please let me know if you have any questions.  I didn't have to add much at all to the project, and only a few changes with the Project Settings.

FYR
Nodes
--------------
Panel
	bg color: #000
	size: 3840x2160
	no min size
	> Vbox
		layout: center
		800x554
		> label
		> textrect
			800x110


Application
--------------
	1x1.png
	fullsize: off
	use filter: off
	bg color: black

Rendering
--------------
Quality
	Use pixel snap
	Framebuffer Allocation 2d .mobile 2d
	Shadows: disabled
Vram
	Import s3 tc & etc2 on, everything else off

Display
--------------
Window
	3840x2160
	Resizable: off
	Test 1360x768
	Allow hidpi: on

Gui
--------------
Theme
	hidpi: on


[MRP-Nodes-glitching.zip](https://github.com/godotengine/godot/files/6094177/MRP-Nodes-glitching.zip)

**Comment by eltharionx** [comment] 2021-03-06 00:12
> Note there are some differences to ninepatch behaviour (and the defaults for ninepatches) in 3.2.4. In particular if you look in `rendering/quality/ninepatchmode` there is a setting to try (you may need to restart). But yes a minimal reproduction project should show what the problem is.

Tried this and unfortunately the "tile" part still only "stretches" (instead of tile repeat keeping the image aspect ratio).

**Comment by lawnjelly** [comment] 2021-03-06 07:02
Tried the demo project and I can't reproduce it here. Is there anything special I should be doing?

I noticed the window size is set at 3840x2160 then the test size is 1360x768. Does it occur on yours with a smaller window size (not test size)?

**Comment by eltharionx** [comment] 2021-03-06 16:34
Hi @lawnjelly, no, nothing special, just "play the project" and it causes this issue.

"I noticed the window size is set at 3840x2160 then the test size is 1360x768. Does it occur on yours with a smaller window size (not test size)?"
Yes.  I changed the window size in the Project Settings to "1360x768" and still get the same issue.

"The rects seem fairly simple, there's no ninepatches, so I'll check what the polys are doing (drawing the Panel). Does the problem disappear if you change the panel to e.g. a Node2d (that doesn't draw anything), or hide any of the elements?"
When I hide the two elements (See Step 3 & 4 below) it seems to work.
Changing the Panel to a Node2D, requires that I also change the VBoxContainer Layout = Top Left so you can see the elements. The text seems misplaced, but I don't see any flickering/jumping of the text.  See: node2d-vbox-layout-top-left.png


---
Minimal Reproduction Project 2

I have made an even more "minimal" project and attached here (MRP2).  This one only changes the window and test size, and I believe all other Project Settings are the defaults.

Step 1:
Add a Panel node
* Layout = Full Rect
* Custom Styles = New StyleBoxFlat
* StyleBoxFlat Bg Color = #000000

Run project: NO VISUAL ISSUES DETECTED

Step 2:
Add a VBoxContainer as child node to Panel
* Rect.Min Size.x = 800
* Rect.Min Size.y = 500
* Layout = Center

Run project: NO VISUAL ISSUES DETECTED

Step 3:
Add a Label as child node to VBoxContainer
* Add text = "test test test test test"

Run project: VISUAL ISSUE DETECTED
* See ss-step3.png

Step 4:
Add a TextureRect as child node to VBoxContainer
* Add Texture: icon.png (Godot logo)

Run project: MORE VISUAL ISSUES DETECTED
* label text flicks/jumps up/down a line
* See ss-step4.png


---
ERRORS

I noticed too with v3.2.4.rc3 when I first start up Godot that the Project Manager is discombobulated, but then after a second or two, it reforms and looks perfect.  See: errors-project-manager.png.

Also attached error.png, but I see these same errors when running v3.2.3.stable, and it works properly.
[MRP2.zip](https://github.com/godotengine/godot/files/6095690/MRP2.zip)
![node2d-vbox-layout-top-left](https://user-images.githubusercontent.com/4984444/110213847-ab3b2780-7e56-11eb-848a-c115b2fa9748.png)
![ss-step3](https://user-images.githubusercontent.com/4984444/110213849-ad04eb00-7e56-11eb-83d6-95060254b6ec.png)
![ss-step4](https://user-images.githubusercontent.com/4984444/110213851-ad9d8180-7e56-11eb-93f6-e557f198e288.png)
![errors-project-manager](https://user-images.githubusercontent.com/4984444/110213854-af674500-7e56-11eb-9b36-ecdd275d9bba.png)
![errors](https://user-images.githubusercontent.com/4984444/110213856-b0987200-7e56-11eb-975d-8bfa0bc2c5ec.png)

**Comment by lawnjelly** [comment] 2021-03-06 16:54
Have to say this is looking more and more like a driver issue, or your system isn't capable of running Godot GLES3. We haven't had any other similar reports, especially just running the project manager. My best guess it that the transform uniforms aren't working on your system.

The errors in `rasterizer_scene_gles3.cpp` look to be to do with setting up a shadow cubemap (that's more @clayjohn 's area), but are unlikely to be causing the problems you are seeing.

I suspect if you ran a graphics debugger, captured a trace, then replayed it, you'd get a different result each time.

**Comment by Zireael07** [comment] 2021-03-07 14:49
@lawnjelly: The error status != 0x8CD5 is something I used to have with an old Radeon 6630M and I did report it, and it was closed because, paraphrasing to the best of my memory: "Radeon 5xxx/6xxx series GLES3 isn't up to stuff". I could run a 3D Godot project back then no problem, so it's a red herring, especially as this is a 2D project.

Vote to close as a driver issue - btw yet another example why we need a blacklist for those spotty GLES3 graphics cards/devices.

**Comment by Calinou** [comment] 2021-03-07 14:53
> btw yet another example why we need a blacklist for those spotty GLES3 graphics cards/devices.

This was proposed in https://github.com/godotengine/godot-proposals/issues/1609 already, but nobody has started working on it yet.

**Comment by eltharionx** [comment] 2021-03-08 21:36
I did try the same scene with a computer with a newer graphics card and it worked correctly.

If it's the case that the ATI Radeon HD 5450 is not fully supported by the Godot community with GLES 3.0, I guess I can accept that and consider this issue closed.  Though I would agree @Zireael07 that we should have some sort of warning saying these types of graphic cards can be used but are not fully supported.

**Comment by Calinou** [comment] 2021-08-07 12:05
Closing in favor of https://github.com/godotengine/godot-proposals/issues/1609.

**Closed by Calinou** 2021-08-07 12:05 UTC
Labels: bug, topic:rendering, regression, topic:2d
