### ISSUE TITLE
"Property not found" warning spam after renaming a project in the project manager

### ISSUE THREAD

**Issue by Kylogias** [godotengine/godot#51072] opened 2021-07-30 15:57 UTC
### Godot version

3.4-beta2

### System information

Windows 10, Intel i7-10700K, project manager

### Issue description

When renaming a project, I was (and still am) getting spammed, output in the following screenshot. From further testing, it appears that it's not just that one setting

![image](https://user-images.githubusercontent.com/45217130/127679148-681a5f40-a136-4d70-aaad-f01070c72042.png)

### Steps to reproduce

Optional:
1. Put a copy of Godot in a new folder in self contained mode
2. Create a new project
3. Exit said project

Required:
4. Rename project
You should be spammed with property not found warnings

**Comment by timothyqiu** [comment] 2021-07-31 01:56
Possible duplicate of #25661

**Comment by Calinou** [comment] 2021-07-31 12:38
Closing per @timothyqiu's comment.

**Closed by Calinou** 2021-07-31 12:38 UTC
Labels: bug, needs testing, topic:editor
