### ISSUE TITLE
[Godot 4] Engine crashes when closing scene

### ISSUE THREAD

**Issue by nonunknown** [godotengine/godot#53803] opened 2021-10-14 11:37 UTC
### Godot version

v4.0.dev.custom_build [004b44e91]

### System information

manjaro 21, AMD Radeon r7 200 series, Vulkan, 8GB Memory

### Issue description

maybe a regression of: #53697

PS: The computer starts to scream (loud noise)

```
EditorSettings: Save OK!
XR: Clearing primary interface
XR: Removed interfaceNative mobile
PulseAudio: context terminated
ERROR: 3 RID allocations of type 'N17RendererStorageRD7TextureE' were leaked at exit.
WARNING: 2 RIDs of type "UniformBuffer" were leaked.
     at: _free_rids (drivers/vulkan/rendering_device_vulkan.cpp:8962)
WARNING: 4 RIDs of type "Texture" were leaked.
     at: finalize (drivers/vulkan/rendering_device_vulkan.cpp:9266)
ERROR: 14 RID allocations of type 'PN18TextServerAdvanced16FontDataAdvancedE' were leaked at exit.
WARNING: ObjectDB instances leaked at exit (run with --verbose for details).
     at: cleanup (core/object/object.cpp:2022)
Leaked instance: ImageTexture:-9221092749250394754 - Resource path: 
Leaked instance: FontData:-9220163661924923474 - Resource path: 
Leaked instance: FontData:-9220162562413295696 - Resource path: 
Leaked instance: FontData:-9220161462901667918 - Resource path: 
Leaked instance: FontData:-9220160363390040140 - Resource path: 
Leaked instance: FontData:-9220159263878412362 - Resource path: 
Leaked instance: FontData:-9220158164366784584 - Resource path: 
Leaked instance: FontData:-9220157064855156806 - Resource path: 
Leaked instance: FontData:-9220155965343529028 - Resource path: 
Leaked instance: FontData:-9220154865831901250 - Resource path: 
Leaked instance: FontData:-9220153766320273472 - Resource path: 
Leaked instance: FontData:-9220152666808645694 - Resource path: 
Leaked instance: FontData:-9220151567297017916 - Resource path: 
Leaked instance: FontData:-9220151017541204027 - Resource path: 
Leaked instance: FontData:-9220150467785390138 - Resource path: 
Leaked instance: Font:-9220148818517948471 - Resource path: 
Leaked instance: ImageTexture:-9177507558569505678 - Resource path: 
Leaked instance: ImageTexture:-9165429973094187875 - Resource path: 
Hint: Leaked instances typically happen when nodes are removed from the scene tree (with `remove_child()`) but not freed (with `free()` or `queue_free()`).
Orphan StringName: ImageTexture
Orphan StringName: Font
Orphan StringName: FontData
Orphan StringName: changed
StringName: 593 unclaimed string names at exit.
```

Complete log file: 
[log.txt](https://github.com/godotengine/godot/files/7345827/log.txt)

### Steps to reproduce

Open the main scene (Game.tscn) and close it

### Minimal reproduction project
[Error.zip](https://drive.google.com/file/d/16yCs6i6VrGtOkHWRVOlhrgVVueEzdud3/view?usp=sharing)

**Comment by bruvzg** [comment] 2021-10-14 11:58
I can't reproduce crash (is it crashing, this log looks like a normal editor exit process?) or leak (seems like a font is leaking, probably font instanced is not freed by something in the specific project).

> maybe a regression of: #53697

If it's caused by the recent TextServer changes, it's more likely from #52192.

**Comment by bruvzg** [comment] 2021-10-14 12:20
> Minimal reproduction project
> 
> Game.zip

I'm getting `Scene file 'Game.tscn' appears to be invalid/corrupt.` error and a bunch of resource loading errors, but no crash or leak (there's 2 RIDs of type "UniformBuffer" leak, but it's probably unrelated) on exit.

```
  scene/resources/resource_format_text.cpp:423 - res://objects/BaseCharacter.tscn:13 - ext_resource, invalid UUID: uid://45a8tbxtlan - using text path instead: res://sounds/fx/0000_0000.wav
  Resource file not found: res://sounds/fx/0000_0000.wav.
  modules/gdscript/gdscript.cpp:1005 - Condition "err" is true. Returning: err
  modules/gdscript/gdscript.cpp:1005 - Condition "err" is true. Returning: err
  Failed to get modified time for: res://TrailRenderer.gd.
  scene/resources/resource_format_text.cpp:170 - res://objects/BaseCharacter.tscn:205 - Parse Error: [ext_resource] referenced non-loaded resource at: res://sounds/fx/0000_0000.wav
  scene/resources/resource_format_text.cpp:269 - res://objects/BaseCharacter.tscn:205 - Parse Error: [ext_resource] referenced non-loaded resource at: res://sounds/fx/0000_0000.wav
  Failed loading resource: res://objects/BaseCharacter.tscn. Make sure resources have been imported by opening the project in the editor at least once.
  scene/resources/resource_format_text.cpp:170 - res://Game.tscn:53 - Parse Error: [ext_resource] referenced non-loaded resource at: res://objects/BaseCharacter.tscn
  scene/resources/resource_format_text.cpp:269 - res://Game.tscn:53 - Parse Error: [ext_resource] referenced non-loaded resource at: res://objects/BaseCharacter.tscn
  servers/rendering/renderer_rd/renderer_storage_rd.cpp:1547 - Condition "!material" is true.
  Failed loading resource: res://Game.tscn. Make sure resources have been imported by opening the project in the editor at least once.
  editor/editor_data.cpp:554 - Index p_idx = 1 is out of bounds (edited_scene.size() = 1).
```

**Comment by nonunknown** [comment] 2021-10-14 12:32
@bruvzg updated the project to avoid corrupt!

**Comment by bruvzg** [comment] 2021-11-23 20:48
> and some rendering issues, but also no crash and 1 RIDs of type "UniformBuffer" leak on exit.

Re-tested it again. All black spot rendering artifacts and material errors seems to be fixed by updating Vulkan SDK to 1.2.198.0, it's still running without any crashes.

![Screenshot 2021-11-23 at 22 43 42](https://user-images.githubusercontent.com/7645683/143109749-d2261eb8-077e-466a-bb3b-801c58a56033.png)

**Comment by KoBeWi** [comment] 2022-05-19 23:48
Tested, no crash or error.
@nonunknown Is the issue resolved for you?

**Comment by nonunknown** [comment] 2022-05-20 11:02
as @bruvzg mentioned:

> Project is also running, I'm getting ERROR: Condition "!material" is true. errors and some rendering issues, but also no crash and 1 RIDs of type "UniformBuffer" leak on exit.

still happens to man, its even worse

**Comment by KoBeWi** [comment] 2023-02-22 23:02
@nonunknown Any chance this is fixed now for you?

**Comment by nonunknown** [comment] 2023-02-23 10:58
YEah for sure, this was fixed long ago if I'm right!

**Closed** 2023-02-23 11:01 UTC
Labels: bug, topic:editor
