### ISSUE TITLE
[3.2.2] Fixing compatiblity with C#

### ISSUE THREAD

**Issue by ondesic** [godotengine/godot#39962] opened 2020-06-29 19:46 UTC
I am using VS Code and c#.  Work flow has been great with 3.2.1.  However, after installing 3.2.2 I now get the following errors:

`C:\Users\me\Documents\Godot\PGM\Pgm.sln.metaproj : error MSB4126: The specified solution configuration "Tools|Any CPU" is invalid. Please specify a valid solution configuration using the Configuration and Platform properties (e.g. MSBuild.exe Solution.sln /p:Configuration=Debug /p:Platform="Any CPU") or leave those properties blank to use the default solution configuration . [C:\Users\me\Documents\Godot\PGM\Pgm.sln]`

I saw a note in the release that compatiblity may be broken with the latest 3.2.2.  I didn't see a solution other than go back to 3.2.1.  I also searched and found Debug, Release, and Tools had been changed to ExportDebug, ExportRelease, Debug respectively.  The error above seems to be releated to this.

I asked on the main forum but no one was able to figure it out.  Is there a work around to get my 3.2.1 project running in 3.2.2?

**Comment by nobuyukinyuu** [comment] 2020-06-29 21:09
The default build task is probably still attempting to use the old configuration.  You'll need to update `tasks.json` to point to the new configuration.  See here:
https://github.com/godotengine/godot/issues/38153#issuecomment-651367177

This issue may also be a duplicate of #38153.

**Comment by ondesic** [comment] 2020-06-30 04:58
After making the changes mentioned, I get a new error:
`The program '[33956] Godot_v3.2.2-stable_mono_win64.exe' has exited with code -1073741819`
The program opens the splash screen, then crashes.
If I revert back to 3.2.1 it works fine :(

I feel like I am so close.

**Comment by rafaelgdp** [comment] 2020-06-30 05:41
@ondesic I had this exact problem. I used mono on a project I've been developing since 3.2.1 and when I switched to the newer 3.2.2 versions it crashed every time. I don't remember exactly what solved the issue for me, but I think I simply deleted the .mono folder and tweaked the .csproj/sln files. Then, I simply rebuilt the project and everything worked fine! Try creating a new mono project on the 3.2.2 version and compare these files. Some configurations changed between versions.

**Comment by Calinou** [comment] 2020-06-30 07:59
Duplicate of #38153.

**Closed by Calinou** 2020-06-30 07:59 UTC
Labels: topic:mono

**Comment by nobuyukinyuu** [comment] 2020-06-30 11:22
> After making the changes mentioned, I get a new error:
> `The program '[33956] Godot_v3.2.2-stable_mono_win64.exe' has exited with code -1073741819`
> The program opens the splash screen, then crashes.
> If I revert back to 3.2.1 it works fine :(
> 
> I feel like I am so close.

Make sure to do a clean and rebuild as i also had some strange issues at first until doing this.  I believe i also deleted the cache files in the `.mono` folder but don't try that until doing `dotnet clean` and `nuget restore` and seeing if that works.

**Comment by ondesic** [comment] 2020-06-30 15:24
Dang, I have dotnet clean and nuget restore.  I have deleted the .mono folder.
The same thing happens each time.  The splash windows opens, then it closes with no errors other than:
`The program '[33956] Godot_v3.2.2-stable_mono_win64.exe' has exited with code -1073741819`
