### ISSUE TITLE
Godot doesn't close when using Run from launcher.

### ISSUE THREAD

**Issue by OGMP-Gyrth** [godotengine/godot#17024] opened 2018-02-25 23:10 UTC
OS: Ubuntu Linux 17.10
Godot version: Godot_v3.0.1-stable_x11.64

When I use the Run option to launch my game without the editor, and then proceed to close the game, Godot doesn't exit properly.
More importantly it seems to use 100% of one of my cores.

The way I close my game is by pressing escape and using ``	get_tree().quit()``

[recording.zip](https://github.com/godotengine/godot/files/1756827/recording.zip)

**Comment by hpvb** [comment] 2018-02-26 01:16
Can you please run your game from a console and see if there's any output after you call get_tree().quit()? It could point us in the right direction.

**Comment by OGMP-Gyrth** [comment] 2018-02-26 02:52
```
ERROR: _area_inout: Condition ' !area_in && !E ' is true.
   At: scene/3d/area.cpp:357.
ERROR: _area_inout: Condition ' !area_in && !E ' is true.
   At: scene/3d/area.cpp:357.
ERROR: _area_inout: Condition ' !area_in && !E ' is true.
   At: scene/3d/area.cpp:357.
ERROR: _area_inout: Condition ' !area_in && !E ' is true.
   At: scene/3d/area.cpp:357.
ERROR: ~List: Condition ' _first != __null ' is true.
   At: core/self_list.h:100.
ERROR: ~List: Condition ' _first != __null ' is true.
   At: core/self_list.h:100.
WARNING: cleanup: ObjectDB Instances still exist!
   At: core/object.cpp:1989.
ERROR: clear: Resources Still in use at Exit!
   At: core/resource.cpp:418.
ERROR: cleanup: There are still MemoryPool allocs in use at exit!
   At: core/dvector.cpp:70.
```

**Comment by OGMP-Gyrth** [comment] 2018-03-04 15:18
This still seems to be an issue in 3.0.2. I left it running for a couple of minutes, thinking it might just close after a while. But it seems permanently stuck.

![image](https://user-images.githubusercontent.com/14081613/36947088-aa497cfa-1fc7-11e8-8372-caa8b90eca8d.png)

**Comment by OGMP-Gyrth** [comment] 2018-03-19 17:28
I found out this actually happens when I just open the editor, and then close it again without running the game. I have to kill the process each time or else it will continue using 100% of one core. :frowning: 

Here is the full output.

```gyrth@Gyrth-Desktop:~/Documents$ ./Godot_v3.0.2-stable_x11.64 
OpenGL ES 3.0 Renderer: GeForce GTX 1060 6GB/PCIe/SSE2
OPENING: /home/gyrth/Documents/blacktrace-game (::home::gyrth::Documents::blacktrace-game)
OpenGL ES 3.0 Renderer: GeForce GTX 1060 6GB/PCIe/SSE2
Boot splash path: res://Textures/logo.png
gyrth@Gyrth-Desktop:~/Documents$ ERROR: add_node: Condition ' node_map.has(p_node) ' is true.
   At: scene/animation/animation_tree_player.cpp:920.
ERROR: add_node: Condition ' node_map.has(p_node) ' is true.
   At: scene/animation/animation_tree_player.cpp:920.
ERROR: add_node: Condition ' node_map.has(p_node) ' is true.
   At: scene/animation/animation_tree_player.cpp:920.
ERROR: add_node: Condition ' node_map.has(p_node) ' is true.
   At: scene/animation/animation_tree_player.cpp:920.
ERROR: add_node: Condition ' node_map.has(p_node) ' is true.
   At: scene/animation/animation_tree_player.cpp:920.
ERROR: add_node: Condition ' node_map.has(p_node) ' is true.
   At: scene/animation/animation_tree_player.cpp:920.
ERROR: add_node: Condition ' node_map.has(p_node) ' is true.
   At: scene/animation/animation_tree_player.cpp:920.
ERROR: add_node: Condition ' node_map.has(p_node) ' is true.
   At: scene/animation/animation_tree_player.cpp:920.
ERROR: add_node: Condition ' node_map.has(p_node) ' is true.
   At: scene/animation/animation_tree_player.cpp:920.
ERROR: add_node: Condition ' node_map.has(p_node) ' is true.
   At: scene/animation/animation_tree_player.cpp:920.
ERROR: ~List: Condition ' _first != __null ' is true.
   At: core/self_list.h:100.
ERROR: ~List: Condition ' _first != __null ' is true.
   At: core/self_list.h:100.
WARNING: cleanup: ObjectDB Instances still exist!
   At: core/object.cpp:1989.
ERROR: clear: Resources Still in use at Exit!
   At: core/resource.cpp:418.
ERROR: cleanup: There are still MemoryPool allocs in use at exit!
   At: core/dvector.cpp:70.```

**Comment by wdevan** [comment] 2018-04-15 14:32
OS: Archlinux
Godot Version: v3.1.dev.custom_build.3ad9e47

The same thing happens to me

Output on close:

```
ERROR: ~List: Condition ' _first != __null ' is true.
At: core/self_list.h:100.
ERROR: ~List: Condition ' _first != __null ' is true.
At: core/self_list.h:100.
WARNING: cleanup: ObjectDB Instances still exist!
At: core/object.cpp:1989.
ERROR: clear: Resources Still in use at Exit!
At: core/resource.cpp:418.
```

**Comment by wdevan** [comment] 2018-07-09 22:52
Apparently the application enter in loop on function:

```
void OS::print_error(const char *p_function, const char *p_file, int p_line, const char *p_code, const char *p_rationale, Logger::ErrorType p_type) {

	_logger->log_error(p_function, p_file, p_line, p_code, p_rationale, p_type);
}

```

**Comment by akien-mga** [comment] 2018-09-23 13:13
Closing as duplicate of #18429.

**Closed by akien-mga** 2018-09-23 13:13 UTC
Labels: bug, topic:core
