### ISSUE TITLE
android template build failed.

### ISSUE THREAD

**Issue by lengyue524** [godotengine/godot#1612] opened 2015-04-03 16:10 UTC
I build windows template sucess,but android failed.
Follow the tutorial I get the error.
My NDK is android-ndk-r9d and system is windows 8.1
How to fix it?

```
G:\godot>scons -j 4 p=android target=release
scons: Reading SConscript files ...
Godot Android!!!!!
scons: done reading SConscript files.
scons: Building targets ...
d:\android-ndk-r9d/toolchains/arm-linux-androideabi-4.8/prebuilt//windows/bin/ar
m-linux-androideabi-g++ /Foplatform\android\os_android.os /c platform\android\os
_android.cpp /TP -DNO_STATVFS -MMD -MP -MF -fpic -ffunction-sections -funwind-ta
bles -fstack-protector -fvisibility=hidden -D__ARM_ARCH_7__ -D__GLIBC__ -Wno-psa
bi -march=armv6 -mfpu=neon -mfloat-abi=softfp -ftree-vectorize -funsafe-math-opt
imizations -fno-strict-aliasing -DANDROID -Wa,--noexecstack -DGLES2_ENABLED -O2
-ffast-math -fomit-frame-pointer -fno-exceptions -DNO_SAFE_CAST -DANDROID_ENABLE
D -DUNIX_ENABLED -DNO_FCNTL -DMPC_FIXED_POINT -DMUSEPACK_ENABLED -DOPENSSL_ENABL
ED -DSQUISH_ENABLED -DVORBIS_ENABLED -DPNG_ENABLED -DDDS_ENABLED -DPVR_ENABLED -
DJPG_ENABLED -DWEBP_ENABLED -DSPEEX_ENABLED -DGDSCRIPT_ENABLED -DMINIZIP_ENABLED
 -DXML_ENABLED -DOPENSSL_NO_ASM -DOPENSSL_THREADS -DL_ENDIAN -Icore -Icore\math
-Itools -Idrivers -I. -Iplatform\android -ID:\android-ndk-r9d\platforms\android-
15\arch-arm\usr\include -ID:\android-ndk-r9d\sources\cxx-stl\gabi++\include -ID:
\android-ndk-r9d\sources\cpufeatures -Idrivers\builtin_openssl2 -Iplatform\andro
id\vorbis -Idrivers\builtin_openssl2\crypto -Idrivers\builtin_openssl2\openssl -
Idrivers\builtin_openssl2\crypto\evp -Idrivers\builtin_openssl2\crypto\asn1 -Idr
ivers\builtin_openssl2\crypto\modes
d:\android-ndk-r9d/toolchains/arm-linux-androideabi-4.8/prebuilt//windows/bin/ar
m-linux-androideabi-g++ /Foplatform\android\godot_android.os /c platform\android
\godot_android.cpp /TP -DNO_STATVFS -MMD -MP -MF -fpic -ffunction-sections -funw
ind-tables -fstack-protector -fvisibility=hidden -D__ARM_ARCH_7__ -D__GLIBC__ -W
no-psabi -march=armv6 -mfpu=neon -mfloat-abi=softfp -ftree-vectorize -funsafe-ma
th-optimizations -fno-strict-aliasing -DANDROID -Wa,--noexecstack -DGLES2_ENABLE
D -O2 -ffast-math -fomit-frame-pointer -fno-exceptions -DNO_SAFE_CAST -DANDROID_
ENABLED -DUNIX_ENABLED -DNO_FCNTL -DMPC_FIXED_POINT -DMUSEPACK_ENABLED -DOPENSSL
_ENABLED -DSQUISH_ENABLED -DVORBIS_ENABLED -DPNG_ENABLED -DDDS_ENABLED -DPVR_ENA
BLED -DJPG_ENABLED -DWEBP_ENABLED -DSPEEX_ENABLED -DGDSCRIPT_ENABLED -DMINIZIP_E
NABLED -DXML_ENABLED -DOPENSSL_NO_ASM -DOPENSSL_THREADS -DL_ENDIAN -Icore -Icore
\math -Itools -Idrivers -I. -Iplatform\android -ID:\android-ndk-r9d\platforms\an
droid-15\arch-arm\usr\include -ID:\android-ndk-r9d\sources\cxx-stl\gabi++\includ
e -ID:\android-ndk-r9d\sources\cpufeatures -Idrivers\builtin_openssl2 -Iplatform
\android\vorbis -Idrivers\builtin_openssl2\crypto -Idrivers\builtin_openssl2\ope
nssl -Idrivers\builtin_openssl2\crypto\evp -Idrivers\builtin_openssl2\crypto\asn
1 -Idrivers\builtin_openssl2\crypto\modes
d:\android-ndk-r9d/toolchains/arm-linux-androideabi-4.8/prebuilt//windows/bin/ar
m-linux-androideabi-g++ /Foplatform\android\file_access_android.os /c platform\a
ndroid\file_access_android.cpp /TP -DNO_STATVFS -MMD -MP -MF -fpic -ffunction-se
ctions -funwind-tables -fstack-protector -fvisibility=hidden -D__ARM_ARCH_7__ -D
__GLIBC__ -Wno-psabi -march=armv6 -mfpu=neon -mfloat-abi=softfp -ftree-vectorize
 -funsafe-math-optimizations -fno-strict-aliasing -DANDROID -Wa,--noexecstack -D
GLES2_ENABLED -O2 -ffast-math -fomit-frame-pointer -fno-exceptions -DNO_SAFE_CAS
T -DANDROID_ENABLED -DUNIX_ENABLED -DNO_FCNTL -DMPC_FIXED_POINT -DMUSEPACK_ENABL
ED -DOPENSSL_ENABLED -DSQUISH_ENABLED -DVORBIS_ENABLED -DPNG_ENABLED -DDDS_ENABL
ED -DPVR_ENABLED -DJPG_ENABLED -DWEBP_ENABLED -DSPEEX_ENABLED -DGDSCRIPT_ENABLED
 -DMINIZIP_ENABLED -DXML_ENABLED -DOPENSSL_NO_ASM -DOPENSSL_THREADS -DL_ENDIAN -
Icore -Icore\math -Itools -Idrivers -I. -Iplatform\android -ID:\android-ndk-r9d\
platforms\android-15\arch-arm\usr\include -ID:\android-ndk-r9d\sources\cxx-stl\g
abi++\include -ID:\android-ndk-r9d\sources\cpufeatures -Idrivers\builtin_openssl
2 -Iplatform\android\vorbis -Idrivers\builtin_openssl2\crypto -Idrivers\builtin_
openssl2\openssl -Idrivers\builtin_openssl2\crypto\evp -Idrivers\builtin_openssl
2\crypto\asn1 -Idrivers\builtin_openssl2\crypto\modes
scons: *** [platform\android\os_android.os]
scons: *** [platform\android\godot_android.os]
scons: *** [platform\android\file_access_android.os]
d:\android-ndk-r9d/toolchains/arm-linux-androideabi-4.8/prebuilt//windows/bin/ar
m-linux-androideabi-g++ /Foplatform\android\dir_access_android.os /c platform\an
droid\dir_access_android.cpp /TP -DNO_STATVFS -MMD -MP -MF -fpic -ffunction-sect
ions -funwind-tables -fstack-protector -fvisibility=hidden -D__ARM_ARCH_7__ -D__
GLIBC__ -Wno-psabi -march=armv6 -mfpu=neon -mfloat-abi=softfp -ftree-vectorize -
funsafe-math-optimizations -fno-strict-aliasing -DANDROID -Wa,--noexecstack -DGL
ES2_ENABLED -O2 -ffast-math -fomit-frame-pointer -fno-exceptions -DNO_SAFE_CAST
-DANDROID_ENABLED -DUNIX_ENABLED -DNO_FCNTL -DMPC_FIXED_POINT -DMUSEPACK_ENABLED
 -DOPENSSL_ENABLED -DSQUISH_ENABLED -DVORBIS_ENABLED -DPNG_ENABLED -DDDS_ENABLED
 -DPVR_ENABLED -DJPG_ENABLED -DWEBP_ENABLED -DSPEEX_ENABLED -DGDSCRIPT_ENABLED -
DMINIZIP_ENABLED -DXML_ENABLED -DOPENSSL_NO_ASM -DOPENSSL_THREADS -DL_ENDIAN -Ic
ore -Icore\math -Itools -Idrivers -I. -Iplatform\android -ID:\android-ndk-r9d\pl
atforms\android-15\arch-arm\usr\include -ID:\android-ndk-r9d\sources\cxx-stl\gab
i++\include -ID:\android-ndk-r9d\sources\cpufeatures -Idrivers\builtin_openssl2
-Iplatform\android\vorbis -Idrivers\builtin_openssl2\crypto -Idrivers\builtin_op
enssl2\openssl -Idrivers\builtin_openssl2\crypto\evp -Idrivers\builtin_openssl2\
crypto\asn1 -Idrivers\builtin_openssl2\crypto\modes
scons: *** [platform\android\dir_access_android.os]
scons: building terminated because of errors.
```

**Comment by hurikhan** [comment] 2015-04-03 19:12
android-ndk-r10d works for me on ubuntu 14.10.
Please try it again with r10d.

**Comment by lengyue524** [comment] 2015-04-04 05:40
after change ndk to r10d and detect.py edit.
I get the error same as #1403

**Comment by danurrahmajati** [comment] 2015-04-20 12:19
look at the error path  double  "//"
d:\android-ndk-r9d/toolchains/arm-linux-androideabi-4.8/prebuilt//windows/bin/ar
m-linux-androideabi-g++ /Foplatform\android\os_android.os /  

you should edit detec.py at godot-master/platform/android 

Ubuntu 64 bit should work since the code is right, but other os isnt.

**Comment by akien-mga** [comment] 2015-11-05 14:34
Duplicate of #1403 I guess.

**Closed by akien-mga** 2015-11-05 14:34 UTC
