### ISSUE TITLE
Function hint shows wrong function with same name

### ISSUE THREAD

**Issue by aXu-AP** [godotengine/godot#58403] opened 2022-02-21 21:39 UTC
### Godot version

v4.0.alpha2.official [79077e6c1]

### System information

Windows 10

### Issue description

Code editor shows wrong function hint if there's function with same name in global scope.

Notice that this affects only editor hint, the code runs fine.

### Steps to reproduce

Example:
![nimetön](https://user-images.githubusercontent.com/1621768/155028833-00ab91db-f84d-4a81-b7d1-b981295207de.png)
In this case hint for float lerp is shown, not Vector2.

*Bugsquad edit (keywords for easier searching): completion, call hint, callhint*

**Comment by lyuma** [comment] 2022-02-28 06:11
@Akylzhan if I understand it, the issue is the first three if statements are not checking that `get_callee_type() == Type::NONE` so I think adding that check would be more correct than reordering them

I'm assuming `callee_type` is the type of the object before the `.`

I'd imagine the same issue as the Variant::utility function is also true for `GDScriptUtilityFunctions` and `GDScriptParser::get_builtin_type()` ... (first, second and third branches of that if statements). You can see some of other the incorrect cases in this screenshot, which autocomplete but shouldn't.
![improper Autocompletes](https://user-images.githubusercontent.com/39946030/155933073-b7dd28d1-5c22-4988-9a64-ce0368e71711.png)

I have also run into this `Vector2.lerp()` issue before and it would be nice to get that fixed.

**Comment by vnen** [comment] 2022-02-28 13:40
> if I understand it, the issue is the first three if statements are not checking that `get_callee_type() == Type::NONE` so I think adding that check would be more correct than reordering them

This seems to be the issue, though it should be checking if `callee_type == GDScriptParser::Node::IDENTIFIER`. This `callee_type` in this case is actually the type of the parser node, which may be an attribute access (`something.function()`) or an identifier directly (`function()`).

Moving the test to the end won't work because the `if (call->is_super || callee_type == GDScriptParser::Node::IDENTIFIER)` test will consume everything, including utility functions and builtin type constructors.

> I'd imagine the same issue as the Variant::utility function is also true for `GDScriptUtilityFunctions` and `GDScriptParser::get_builtin_type()` ... (first, second and third branches of that if statements). You can see some of other the incorrect cases in this screenshot, which autocomplete but shouldn't.

Yeah, it's likely the same issue.

**Comment by cdemirer** [comment] 2022-03-02 09:27
Also see: #58202

**Comment by Akylzhan** [comment] 2022-03-18 06:08
Can someone suggest examples where wrong arguments were shown?

**Comment by Chaosus** [comment] 2022-08-11 05:00
Closed by https://github.com/godotengine/godot/pull/64206

**Closed by Chaosus** 2022-08-11 05:00 UTC
Labels: bug, topic:editor, regression
