### ISSUE TITLE
Crash when closing a Godot game

### ISSUE THREAD

**Issue by GumaD3v** [godotengine/godot#67940] opened 2022-10-27 12:24 UTC
### Godot version

4.0beta3

### System information

Android 12, vulkan mobile 

### Issue description

Editor crashes when closing a Godot game

### Steps to reproduce

Run any project and press back, the editor will crash with the game

**Comment by clayjohn** [comment] 2022-10-27 20:36
Can you provide any more information? As it is there isn't really anything actionable here for contributors to look into. 

Could you at the very least provide the requested system information and an MRP?

**Comment by Calinou** [comment] 2022-10-27 20:48
Duplicate of https://github.com/godotengine/godot/issues/61611.

**Closed by Calinou** 2022-10-27 20:48 UTC
Labels: bug, platform:android, topic:core, needs testing, crash
