### ISSUE TITLE
Script on an instanced node doesn't get saved.

### ISSUE THREAD

**Issue by ranmaru90** [godotengine/godot#5403] opened 2016-06-25 06:09 UTC
**Operating system or device - Godot version:**
Windows 10. Compile the latest source from GitHub.

**Issue description** (what happened, and what was expected):
After instancing a scene that has a script attached to its root node, editing that script doesn't get saved.

**Steps to reproduce:**
1. Create a scene, Scene A, put a script on its root node.
2. Create another scene, Scene B, instance Scene A in it. 
3. In Scene B, edit the script on the instanced Scene A.
4. Save.
5. Restart Godot.
6. Open Scene A and check the script attached to its root node. The changes didn't get saved.

ps: **the said script is never saved to a separate file.**

**Comment by reduz** [comment] 2016-07-01 15:09
This is a little confusing, could you record a video of what's going on?

**Comment by ranmaru90** [comment] 2016-07-05 05:49
To be more precise, built-in scripts when edited from instanced nodes, they can't be saved.

Hope this [video](https://youtu.be/JCNyPocsaVM) can explain it.

**Comment by Sslaxx** [comment] 2016-07-06 10:41
Yet another reason to remove built-in scripts?

**Comment by bojidar-bg** [comment] 2016-07-06 10:57
Dupe of #5535?

**Comment by reduz** [comment] 2016-07-06 12:45
This is kind of expected, the built-in script will only save when you save the scene it comes from. Maybe a warning should be shown while editing this script that it can't be saved?

**Comment by ranmaru90** [comment] 2016-07-06 12:57
I have the habit of mashing Ctrl + S everytime I code. Then, many times, I didn't save the built-in scripts. How about when saving a built-in script, the scene gets saved too? I think removing built-in scripts is okay too.

**Comment by reduz** [comment] 2016-07-06 13:05
May users seem to like built-in scripts, and removing them is impossible because Godot allows any resource to be built-in.   As mentioned before, we can't save the built-in script if the scene where it comes from is not loaded for editing.  you have to open the scene it comes from in the editor for that script to save.

What we can do is, again, show you a warning if you are editing the script that your changes will not be saved, and ask you to open the scene where the script comes from instead.

**Comment by akien-mga** [comment] 2016-07-06 13:08
> What we can do is, again, show you a warning if you are editing the script that your changes will not be saved, and ask you to open the scene where the script comes from instead.

Alternatively, we could prevent having built-in scripts opened without the corresponding scene opened. This might be an inconvenience to some users, but should also encourage them to use built-in scripts only sparsely. Opening a scene would open its built-in scripts in the script editor; closing the scene would close its built-in scripts, and thus saving either the built-in scripts or the scene would save the full scene.

**Comment by reduz** [comment] 2016-07-06 13:11
@akien-mga That could work, and the editor could show a warning that it won't open such scripts if the scene is not loaded.

**Closed** 2016-07-06 23:38 UTC
Labels: bug, topic:editor

**Comment by hetdegon** [comment] 2016-07-07 00:17
I opened #5535, guess I can close it since a78226c solves the problem. It's a bit inconvenient, but not a big deal, at least it'll prevent "forgetting" to switch to the right scene.
