### ISSUE TITLE
Bitmap font text can't align vertical center in the button

### ISSUE THREAD

**Issue by alexzheng** [godotengine/godot#23349] opened 2018-10-28 11:20 UTC
<img width="233" alt="button" src="https://user-images.githubusercontent.com/1130047/47615110-aa0aca80-dae5-11e8-8782-c1fa4234aacc.png">

**Godot version:3.0.6

**OS/device including version:**

**Issue description:**

It seems like the bottom of the text is at the vertical center of the button, it's impossible to place the center of the text at the center of the button. When use DynamicFont, the center of the text is at the vertical center.
Please check the image and the font file for detail.

**Steps to reproduce:**
Add a button
Set Align to Center. (I know this determine the horizontal align, but the vertical can't align center for bitmap font text)

[font.zip](https://github.com/godotengine/godot/files/2522738/font.zip)

**Minimal reproduction project:**

**Comment by alexzheng** [comment] 2018-10-28 14:00
Also, bitmap font for Label can't work well, the Auto wrap can not place correct margin between lines.

**Comment by bojidar-bg** [comment] 2018-10-28 15:09
Can't reproduce either on master (970b58148f579f741934f64af437d01b985df15d) or 3.0.6 (8314054) with the provided .fnt sample.
Screenshot (same from both versions, the button and both labels have the same height):
![image](https://user-images.githubusercontent.com/5276727/47617795-c9006100-dad3-11e8-9e22-9eb7dd2e9f88.png)


(Note: Please try to give full sample projects for reproduction, not just one or two files)

**Comment by alexzheng** [comment] 2018-10-29 01:47
I found what the problem was.
The *.fnt file is not included in the All Recognized file type when load file for the font property.
I made a new BitmapFont and set the fnt file as the Fallback but forgot to set the Height.
I think the *.fnt file type should include in the All Recognized file type.

**Comment by clayjohn** [comment] 2019-04-20 05:58
Looks like this has been fixed. I am closing now. If there is a different issue we can reopen, or open a new issue.

**Closed by clayjohn** 2019-04-20 05:58 UTC
