### ISSUE TITLE
Godot crashes on autocomplete when a Signal is in the script

### ISSUE THREAD

**Issue by Arakash** [godotengine/godot#41484] opened 2020-08-24 09:10 UTC
**Godot version:**
I'm on the latest master version, commit 58f5c2b

**OS/device including version:**
Windows ,10, Version 10.0.18363 Build 18363
Vulkan renderer

**Issue description:**
when I have a Signal variable in mz godot script, godot crashes to desktop as soon as I try to complete anything.

Stacktrace
```
CrashHandlerException: Program crashed
Dumping the backtrace. Please include this when reporting the bug on https://github.com/godotengine/godot/issues
[0] CowData<GDScriptParser::ClassNode::Member>::_get_size (C:\Projects\Godot\godot\core\cowdata.h:70)
[1] CowData<GDScriptParser::ClassNode::Member>::size (C:\Projects\Godot\godot\core\cowdata.h:127)
[2] Vector<GDScriptParser::ClassNode::Member>::size (C:\Projects\Godot\godot\core\vector.h:87)
[3] _find_identifiers_in_class (C:\Projects\Godot\godot\modules\gdscript\gdscript_editor.cpp:776)
[4] _find_identifiers (C:\Projects\Godot\godot\modules\gdscript\gdscript_editor.cpp:1020)
[5] GDScriptLanguage::complete_code (C:\Projects\Godot\godot\modules\gdscript\gdscript_editor.cpp:2474)
[6] ScriptTextEditor::_code_complete_script (C:\Projects\Godot\godot\editor\plugins\script_text_editor.cpp:705)
[7] ScriptTextEditor::_code_complete_scripts (C:\Projects\Godot\godot\editor\plugins\script_text_editor.cpp:694)
[8] CodeTextEditor::_complete_request (C:\Projects\Godot\godot\editor\code_editor.cpp:835)
[9] call_with_variant_args_helper<CodeTextEditor> (C:\Projects\Godot\godot\core\callable_method_pointer.h:136)
[10] call_with_variant_args<CodeTextEditor> (C:\Projects\Godot\godot\core\callable_method_pointer.h:158)
[11] CallableCustomMethodPointer<CodeTextEditor>::call (C:\Projects\Godot\godot\core\callable_method_pointer.h:185)
[12] Callable::call (C:\Projects\Godot\godot\core\callable.cpp:50)
[13] Object::emit_signal (C:\Projects\Godot\godot\core\object.cpp:1077)
[14] Object::emit_signal (C:\Projects\Godot\godot\core\object.cpp:1132)
[15] TextEdit::query_code_comple (C:\Projects\Godot\godot\scene\gui\text_edit.cpp:6386)
[16] TextEdit::_confirm_completion (C:\Projects\Godot\godot\scene\gui\text_edit.cpp:6145)
[17] TextEdit::_gui_input (C:\Projects\Godot\godot\scene\gui\text_edit.cpp:2521)
[18] MethodBind1<TextEdit,Ref<InputEvent> const &>::call (C:\Projects\Godot\godot\core\method_bind.gen.inc:867)
[19] Object::call (C:\Projects\Godot\godot\core\object.cpp:797)
[20] Object::call (C:\Projects\Godot\godot\core\object.cpp:741)
[21] Viewport::_gui_input_event (C:\Projects\Godot\godot\scene\main\viewport.cpp:2319)
[22] Viewport::input (C:\Projects\Godot\godot\scene\main\viewport.cpp:2979)
[23] Window::_window_input (C:\Projects\Godot\godot\scene\main\window.cpp:911)
[24] call_with_variant_args_helper<Window,Ref<InputEvent> const &,0> (C:\Projects\Godot\godot\core\callable_method_pointer.h:132)
[25] call_with_variant_args<Window,Ref<InputEvent> const &> (C:\Projects\Godot\godot\core\callable_method_pointer.h:158)
[26] CallableCustomMethodPointer<Window,Ref<InputEvent> const &>::call (C:\Projects\Godot\godot\core\callable_method_pointer.h:185)
[27] Callable::call (C:\Projects\Godot\godot\core\callable.cpp:50)
[28] DisplayServerWindows::_dispatch_input_event (C:\Projects\Godot\godot\platform\windows\display_server_windows.cpp:1759)
[29] DisplayServerWindows::_dispatch_input_events (C:\Projects\Godot\godot\platform\windows\display_server_windows.cpp:1736)
[30] Input::_parse_input_event_impl (C:\Projects\Godot\godot\core\input\input.cpp:614)
[31] Input::parse_input_event (C:\Projects\Godot\godot\core\input\input.cpp:440)
[32] Input::flush_accumulated_events (C:\Projects\Godot\godot\core\input\input.cpp:830)
[33] DisplayServerWindows::process_events (C:\Projects\Godot\godot\platform\windows\display_server_windows.cpp:1498)
[34] OS_Windows::run (C:\Projects\Godot\godot\platform\windows\os_windows.cpp:627)
[35] widechar_main (C:\Projects\Godot\godot\platform\windows\godot_windows.cpp:163)
[36] _main (C:\Projects\Godot\godot\platform\windows\godot_windows.cpp:185)
[37] main (C:\Projects\Godot\godot\platform\windows\godot_windows.cpp:199)
[38] WinMain (C:\Projects\Godot\godot\platform\windows\godot_windows.cpp:213)
[39] __scrt_common_main_seh (D:\agent\_work\9\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288)
[40] BaseThreadInitThunk
-- END OF BACKTRACE --
```

**Steps to reproduce:**
I can reproduce this behaviour in a single script in  2 Lines:
```
extends Node3D

signal testSignal

func _ready():
	emi #try to autocomplete this to "emit_signal", godot will crash
	pass 
```

**Minimal reproduction project:**

[crashTest.zip](https://github.com/godotengine/godot/files/5116863/crashTest.zip)

**Comment by ThakeeNathees** [comment] 2020-08-25 09:19
duplicate of #40976

**Closed** 2020-08-25 10:57 UTC
Labels: bug, crash, topic:editor, topic:gdscript
