### ISSUE TITLE
In-editor documentation can appear vertical

### ISSUE THREAD

**Issue by Lemonymous** [godotengine/godot#79028] opened 2023-07-04 15:05 UTC
### Godot version

4.1 beta2

### System information

Windows 10, Forward+, NVIDIA GeForce GTX 1050 Ti (31.0.15.3179)

### Issue description

Sometimes the layout of class documentation can appear wrapped in such a way that every character has its own line. This makes all the properties and function names and description appear vertical.
- Restarting the editor may fix the issue.
- One user has reported that resizing the editor window can also fix it.

Example:
![help-layout](https://github.com/godotengine/godot/assets/10490534/2d879293-3f1d-4ccf-83f3-a0e04ac72917)

### Steps to reproduce

I do not know how to reproduce the issue.

### Minimal reproduction project

N/A

**Comment by AThousandShips** [comment] 2023-07-04 15:06
* Duplicate of #77558

Has been fixed, please try a more recent version

**Closed by AThousandShips** 2023-07-04 15:06 UTC
