### ISSUE TITLE
`for i in n` has no type hint

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#65950] opened 2022-09-16 22:44 UTC
### Godot version

4.0 57bdddc

### System information

Windows 10 x64

### Issue description

`range(n)` correctly returns `Array[int]` (or similiar) and `for` loop on range is properly typed. But if you omit `range` and iterate on integer, the variable is not typed.

See here:
![image](https://user-images.githubusercontent.com/2223172/190827177-eb88f820-060b-44aa-a030-3abd3255f014.png)
Line 10 is unsafe, because `i` isn't typed as integer.

### Steps to reproduce

1. Use `for i in 10`
2. Do something with `i`
3. Unsafe

**Comment by aaronfranke** [comment] 2022-09-16 23:53
`for i in range(10):` does not allocate an array: https://github.com/godotengine/godot/blob/master/modules/gdscript/gdscript_analyzer.cpp#L1324

**Comment by KoBeWi** [comment] 2022-09-16 23:59
But standalone `range(10)` is an array. I assume this is why it's properly typed in a loop.

**Comment by okla** [comment] 2022-09-17 13:17
Little unrelated: does line number color show code (un)safety?

**Comment by KoBeWi** [comment] 2022-09-17 13:19
Yes, "safe" lines have line number tinted green.

**Comment by kleonc** [comment] 2022-11-01 01:45
Duplicate of #61727.

**Closed** 2022-11-01 06:13 UTC
Labels: bug, archived, topic:gdscript
