### ISSUE TITLE
GodotSharp Error 

### ISSUE THREAD

**Issue by rama0x9** [godotengine/godot#18883] opened 2018-05-15 08:15 UTC
**Godot version:**

GODOT 3.0.3 RC 2

**OS/device including version:**

Windows 10 64bit

**Issue description:**

Fresh project, press play and everything works but as soon as i make a new *.cs and attach to a node godot shows me an error : "Failed to build GodotSharp Solution". It was the same with 3.0.3 rc1. Current 3.0.2 stable works. Using Mono 5.4.1

![godot303rc2error](https://user-images.githubusercontent.com/21042841/40044674-655665ec-5828-11e8-9a24-e88cb19a0181.png)

**Steps to reproduce:**

**Minimal reproduction project:**

Fresh Prpject

**Comment by hpvb** [comment] 2018-05-15 09:34
What version of mono do you have installed? For 3.0.3 you must have mono 5.10

**Comment by akien-mga** [comment] 2018-05-15 09:51
> What version of mono do you have installed? For 3.0.3 you must have mono 5.10

OP says: Using Mono 5.4.1

Wasn't the idea behind bundling DLLs that we wouldn't have a strong requirement on the Mono version though? Or does that mean that people can use 5.10 *or newer*, but not older?

**Comment by rama0x9** [comment] 2018-05-15 11:05
5.10 did the trick

did a few tests with different mono versions for clarification:

* mono-5.4.1.7-x64-0 _not working_
* mono-5.10.1.49-x64-0 **working**
* mono-5.12.0.234-x64-0 _not working_
* mono-5.14.0.81-x64-0 _not working_

**Comment by bruvzg** [comment] 2018-05-15 12:01
> Wasn't the idea behind bundling DLLs that we wouldn't have a strong requirement on the Mono version though? Or does that mean that people can use 5.10 or newer, but not older?

Bundling `mscorlib` only prevents editor from crashing on start, but it will work only with assemblies from exactly same runtime version (at least `System.dll` and `System.Core.dll` are usually incompatible).

**Comment by hpvb** [comment] 2018-05-15 12:03
> Wasn't  the idea behind bundling DLLs that we wouldn't have a strong  requirement on the Mono version though? Or does that mean that people  can use 5.10 or newer, but not older?

I was under the impression that was for running games, not necessarily developing them.

**Comment by neikeq** [comment] 2018-05-15 20:42
@akien-mga We have to bundle a few more assemblies, not only mscorlib. I mention this in #18364. It's more even noticeable with 5.10 which [replaced](http://www.mono-project.com/docs/about-mono/releases/5.10.0/#class-libraries) some assemblies with the CoreFX implementation. I ask for patience until I'm done with my obligations in a month, although I hope I can make some good progress with these issues by then in my free time.

**Comment by aaronfranke** [comment] 2020-10-06 17:37
@rama0x9 Please re-test with Godot 3.2.3 and/or the master branch. Also, check if you have the latest Mono and .NET Core.

If this issue does still exist for you, then you will need to include a minimal reproduction project.

**Comment by KoBeWi** [comment] 2021-05-20 23:03
Closing due to lack of update. Please comment if you can still reproduce this issue in the latest stable version of Godot.

**Closed by KoBeWi** 2021-05-20 23:03 UTC
Labels: topic:mono
