### ISSUE TITLE
Can't use `free()` as Callable

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#86706] opened 2024-01-02 12:16 UTC
### Tested versions

Confirmed in 4.2, but likely applies to all current 4.x versions

### System information

Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1060 (NVIDIA; 30.0.15.1403) - Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 Threads)

### Issue description

When trying to use `free()` as a Callable (e.g. for connecting signal or using `call_deferred()`), it fails with `Parser Error: Identifier not found: free`, but only at runtime.

### Steps to reproduce

1.
```GDScript
func _ready():
	free.call_deferred()
```
2. Run.

### Minimal reproduction project (MRP)

N/A

**Comment by akien-mga** [comment] 2024-01-02 13:11
Related to #82251, and duplicate of #58912 (but closed after adding docs).
Should be fixed by #82264.

**Comment by KoBeWi** [comment] 2024-01-02 14:06
Hmm I knew it was reported before, but couldn't find it 🤔
It's a bug though, because the error appears only at runtime.

**Comment by KoBeWi** [comment] 2024-01-02 15:14
#82264 does not fix it.

**Comment by dalexeev** [comment] 2024-01-02 15:26
#82264 is about methods of `Variant` types, `free()` is an `Object` method. I'm guessing the reason is that `Object.free()` is bound in a special way:

https://github.com/godotengine/godot/blob/06bb9f28e740aa005b9d48643becfefa5156487d/core/object/object.cpp#L1648

**Closed** 2024-01-18 15:36 UTC
Labels: bug, topic:core, topic:gdscript
