### ISSUE TITLE
No scene when using one click deploy on Android

### ISSUE THREAD

**Issue by FEDE0D** [godotengine/godot#2604] opened 2015-10-14 00:02 UTC
This is for the latest nighly on the website (Godot_v2.0_alpha_20151003_x11)

The application starts correctly but there's nothing on the scene (it shows only the gray background) and there's no crash.

This only occurs when using any or both "Visible Collision Shapes" and "Deploy Remote Debug" on the options list.

```
LogCat info after settting on Live Editing & Deploy Remote Debug

10-13 20:52:40.987: D/GODOT(16388): ** GODOT ACTIVITY CREATED HERE ***
10-13 20:52:41.268: D/GODOT(16388): command_line is null? no
10-13 20:52:41.268: I/godot(16388): **INIT EVENT! - 0x41388188
10-13 20:52:41.268: I/godot(16388): ***************** HELLO FROM JNI!!!!!!!!
10-13 20:52:41.268: I/godot(16388): *******CLASS FOUND!!!
10-13 20:52:41.268: I/godot(16388): STEP2, 0x1d20021e
10-13 20:52:41.268: I/godot(16388): STEP3 1102828408
10-13 20:52:41.268: I/godot(16388): STEP4, 0xc230002d
10-13 20:52:41.268: I/godot(16388): STEP4.5, 0x1d200222
10-13 20:52:41.268: I/godot(16388): STEP7
10-13 20:52:41.268: I/godot(16388): STEP8
10-13 20:52:41.268: I/godot(16388): *******GOT METHOD _dir_open ok!!
10-13 20:52:41.268: I/godot(16388): *******GOT METHOD _dir_next ok!!
10-13 20:52:41.268: I/godot(16388): *******GOT METHOD _dir_close ok!!
10-13 20:52:41.268: I/godot(16388): *******GOT METHOD _dir_is_dir ok!!
10-13 20:52:41.268: I/godot(16388): starting to attempt get methods
10-13 20:52:41.268: I/godot(16388): *******GOT METHOD _init_audio ok!!
10-13 20:52:41.268: I/godot(16388): *******GOT METHOD _write_buffer ok!!
10-13 20:52:41.268: I/godot(16388): *******GOT METHOD _quit ok!!
10-13 20:52:41.268: I/godot(16388): *******GOT METHOD _pause ok!!
10-13 20:52:41.268: I/godot(16388): CMDLINE LEN 2 - APK EXPANSION I
10-13 20:52:41.283: I/godot(16388): [1;31;40mERROR: create: [1;37;40mCondition ' !create_func ' is true. returned: 0
10-13 20:52:41.283: I/godot(16388): [0;31;40m   At: core/os/mutex.cpp:39.[0;0;37m
10-13 20:52:41.283: I/godot(16388): test construction 5
10-13 20:52:41.283: I/godot(16388): running from dir /
10-13 20:52:41.283: I/godot(16388): **SETUP
10-13 20:52:42.073: I/godot(16388): [1;31;40mERROR: _resolve_hostname: [1;37;40mgethostbyname failed!
10-13 20:52:42.073: I/godot(16388): [0;31;40m   At: drivers/unix/ip_unix.cpp:69.[0;0;37m
10-13 20:52:42.096: I/godot(16388): [1;31;40mERROR: connect: [1;37;40mCondition ' p_host.host == 0 ' is true. returned: ERR_INVALID_PARAMETER
10-13 20:52:42.096: I/godot(16388): [0;31;40m   At: drivers/unix/stream_peer_tcp_posix.cpp:138.[0;0;37m
10-13 20:52:43.096: I/godot(16388): Remote Debugger: Connection failed with status: 0'', retrying in 1 sec.
10-13 20:52:44.096: I/godot(16388): Remote Debugger: Connection failed with status: 0'', retrying in 1 sec.
10-13 20:52:45.096: I/godot(16388): Remote Debugger: Connection failed with status: 0'', retrying in 1 sec.
10-13 20:52:45.096: I/godot(16388): Remote Debugger: Unable to connect
10-13 20:52:45.096: I/godot(16388): pre-removing print handler...
10-13 20:52:45.096: I/godot(16388): removing print handler...
10-13 20:52:45.096: I/godot(16388): found
10-13 20:52:45.096: I/godot(16388): print hanlder list is 0x0
10-13 20:52:45.112: I/godot(16388): has res dir: 
10-13 20:52:45.112: I/godot(16388): exists engine cfg? 0
10-13 20:52:45.135: I/godot(16388): *****SETUP OK
10-13 20:52:45.354: I/godot(16388): **START
10-13 20:52:45.627: W/GodotView(16388): creating OpenGL ES 2.0 context :
10-13 20:52:45.744: I/godot(16388): ^_^_^_^_^ newcontext 1089369056
10-13 20:52:45.744: I/godot(16388): ^_^_^_^_^ resize 1089369056, 1280, 752
10-13 20:52:45.744: I/godot(16388): ANDROID MODULES : 
10-13 20:52:45.744: I/godot(16388): mod count: 0
10-13 20:52:46.362: I/godot(16388): GL_EXT_debug_marker
10-13 20:52:46.362: I/godot(16388): GL_EXT_discard_framebuffer
10-13 20:52:46.362: I/godot(16388): GL_EXT_multi_draw_arrays
10-13 20:52:46.369: I/godot(16388): GL_EXT_shader_texture_lod
10-13 20:52:46.369: I/godot(16388): GL_EXT_texture_format_BGRA8888
10-13 20:52:46.369: I/godot(16388): GL_IMG_multisampled_render_to_texture
10-13 20:52:46.369: I/godot(16388): GL_IMG_program_binary
10-13 20:52:46.369: I/godot(16388): GL_IMG_read_format
10-13 20:52:46.369: I/godot(16388): GL_IMG_shader_binary
10-13 20:52:46.369: I/godot(16388): GL_IMG_texture_compression_pvrtc
10-13 20:52:46.369: I/godot(16388): GL_IMG_texture_format_BGRA8888
10-13 20:52:46.369: I/godot(16388): GL_IMG_texture_npot
10-13 20:52:46.369: I/godot(16388): GL_IMG_uniform_buffer_object
10-13 20:52:46.369: I/godot(16388): GL_OES_EGL_image
10-13 20:52:46.369: I/godot(16388): GL_OES_EGL_image_external
10-13 20:52:46.369: I/godot(16388): GL_OES_compressed_ETC1_RGB8_texture
10-13 20:52:46.369: I/godot(16388): GL_OES_depth24
10-13 20:52:46.369: I/godot(16388): GL_OES_depth_texture
10-13 20:52:46.369: I/godot(16388): GL_OES_egl_sync
10-13 20:52:46.369: I/godot(16388): GL_OES_element_index_uint
10-13 20:52:46.369: I/godot(16388): GL_OES_fragment_precision_high
10-13 20:52:46.369: I/godot(16388): GL_OES_get_program_binary
10-13 20:52:46.369: I/godot(16388): GL_OES_mapbuffer
10-13 20:52:46.369: I/godot(16388): GL_OES_packed_depth_stencil
10-13 20:52:46.369: I/godot(16388): GL_OES_required_internalformat
10-13 20:52:46.369: I/godot(16388): GL_OES_rgb8_rgba8
10-13 20:52:46.369: I/godot(16388): GL_OES_standard_derivatives
10-13 20:52:46.377: I/godot(16388): GL_OES_texture_float
10-13 20:52:46.377: I/godot(16388): GL_OES_texture_half_float
10-13 20:52:46.377: I/godot(16388): GL_OES_vertex_array_object
10-13 20:52:46.377: I/godot(16388): GL_OES_vertex_half_float
10-13 20:52:46.377: I/godot(16388): S3TC: 0 ATITC: 0
10-13 20:52:46.627: I/godot(16388): OpenSL Init OK!
10-13 20:52:46.948: I/godot(16388): BOOT SPLASH: 
10-13 20:52:46.948: I/godot(16388): BOOT SPLASH IS : 
10-13 20:52:52.307: I/godot(16388): BACK PRESSED

```

I'm using the latest binaries from the website for Linux 32 and the latest templates.
This is running on a Samsung Galaxy Tab 2

![datos](https://cloud.githubusercontent.com/assets/6296184/10471550/a00f2508-71ed-11e5-89a3-2fd63d0068f1.png)

**Comment by volzhs** [comment] 2015-10-14 03:10
I guess this part causes problem.

```
10-13 20:52:42.073: I/godot(16388): �[1;31;40mERROR: _resolve_hostname: �[1;37;40mgethostbyname failed!
10-13 20:52:42.073: I/godot(16388): �[0;31;40m   At: drivers/unix/ip_unix.cpp:69.�[0;0;37m
10-13 20:52:42.096: I/godot(16388): �[1;31;40mERROR: connect: �[1;37;40mCondition ' p_host.host == 0 ' is true. returned: ERR_INVALID_PARAMETER
10-13 20:52:42.096: I/godot(16388): �[0;31;40m   At: drivers/unix/stream_peer_tcp_posix.cpp:138.�[0;0;37m
10-13 20:52:43.096: I/godot(16388): Remote Debugger: Connection failed with status: 0'', retrying in 1 sec.
10-13 20:52:44.096: I/godot(16388): Remote Debugger: Connection failed with status: 0'', retrying in 1 sec.
10-13 20:52:45.096: I/godot(16388): Remote Debugger: Connection failed with status: 0'', retrying in 1 sec.
10-13 20:52:45.096: I/godot(16388): Remote Debugger: Unable to connect
```

try to set correct IP address at ``Settings > Editor Settings > Network > Debug host``.
and deploy again.

**Comment by FEDE0D** [comment] 2015-10-14 03:22
Nope. I've checked it out and the IP adress is ok both inside the editor and in the file.
I've tested ping back and forth between the device and the computer and it works fine.

**Comment by FEDE0D** [comment] 2015-10-14 03:29
Oh. I've made another try and now it shows some debug info in the editor console.
Nothing on the device screen tough.
Also, when I pressed the back button to quit the game, my linux session crashed and I had to loggin again.

I don't know if this is related to Godot. I might try it on another pc and see what happens.

**Comment by volzhs** [comment] 2015-10-22 13:49
any good news? :)

**Comment by FEDE0D** [comment] 2015-10-22 15:13
I tried but still no luck.
I also noticed that for some reason files are not being exported (I needed to read some files from my game that weren't there). So I went the export dialog > Resources and set "Export all files in the directory ". Now I can read the files. I still get an "ERROR OPENING FILE: icon.png" tough.

```
10-22 11:26:23.992: D/GODOT(32752): ** GODOT ACTIVITY CREATED HERE ***
10-22 11:26:24.109: D/GODOT(32752): command_line is null? yes
10-22 11:26:24.124: I/godot(32752): **INIT EVENT! - 0x414d8790
10-22 11:26:24.124: I/godot(32752): ***************** HELLO FROM JNI!!!!!!!!
10-22 11:26:24.124: I/godot(32752): *******CLASS FOUND!!!
10-22 11:26:24.124: I/godot(32752): STEP2, 0x1d20021e
10-22 11:26:24.124: I/godot(32752): STEP3 1101814120
10-22 11:26:24.124: I/godot(32752): STEP4, 0x73200029
10-22 11:26:24.124: I/godot(32752): STEP4.5, 0x1d200222
10-22 11:26:24.132: I/godot(32752): STEP7
10-22 11:26:24.132: I/godot(32752): STEP8
10-22 11:26:24.132: I/godot(32752): *******GOT METHOD _dir_open ok!!
10-22 11:26:24.132: I/godot(32752): *******GOT METHOD _dir_next ok!!
10-22 11:26:24.132: I/godot(32752): *******GOT METHOD _dir_close ok!!
10-22 11:26:24.132: I/godot(32752): *******GOT METHOD _dir_is_dir ok!!
10-22 11:26:24.132: I/godot(32752): starting to attempt get methods
10-22 11:26:24.132: I/godot(32752): *******GOT METHOD _init_audio ok!!
10-22 11:26:24.132: I/godot(32752): *******GOT METHOD _write_buffer ok!!
10-22 11:26:24.132: I/godot(32752): *******GOT METHOD _quit ok!!
10-22 11:26:24.132: I/godot(32752): *******GOT METHOD _pause ok!!
10-22 11:26:24.132: I/godot(32752): CMDLINE LEN 0 - APK EXPANSION I
10-22 11:26:24.195: I/godot(32752): [1;31;40mERROR: create: [1;37;40mCondition ' !create_func ' is true. returned: 0
10-22 11:26:24.195: I/godot(32752): [0;31;40m   At: core/os/mutex.cpp:39.[0;0;37m
10-22 11:26:24.195: I/godot(32752): test construction 5
10-22 11:26:24.195: I/godot(32752): running from dir /
10-22 11:26:24.195: I/godot(32752): **SETUP
10-22 11:26:24.578: I/godot(32752): has res dir: 
10-22 11:26:24.578: I/godot(32752): exists engine cfg? 0
10-22 11:26:24.578: I/godot(32752): loaded engine.cfg
10-22 11:26:24.609: I/godot(32752): *****SETUP OK
10-22 11:26:24.679: I/godot(32752): **START
10-22 11:26:24.929: W/GodotView(32752): creating OpenGL ES 2.0 context :
10-22 11:26:25.179: I/godot(32752): ^_^_^_^_^ newcontext 1523499528
10-22 11:26:25.179: I/godot(32752): ^_^_^_^_^ resize 1523499528, 1280, 752
10-22 11:26:25.179: I/godot(32752): ANDROID MODULES : 
10-22 11:26:25.195: I/godot(32752): mod count: 0
10-22 11:26:25.328: I/godot(32752): GL_EXT_debug_marker
10-22 11:26:25.328: I/godot(32752): GL_EXT_discard_framebuffer
10-22 11:26:25.328: I/godot(32752): GL_EXT_multi_draw_arrays
10-22 11:26:25.328: I/godot(32752): GL_EXT_shader_texture_lod
10-22 11:26:25.328: I/godot(32752): GL_EXT_texture_format_BGRA8888
10-22 11:26:25.328: I/godot(32752): GL_IMG_multisampled_render_to_texture
10-22 11:26:25.328: I/godot(32752): GL_IMG_program_binary
10-22 11:26:25.328: I/godot(32752): GL_IMG_read_format
10-22 11:26:25.328: I/godot(32752): GL_IMG_shader_binary
10-22 11:26:25.328: I/godot(32752): GL_IMG_texture_compression_pvrtc
10-22 11:26:25.328: I/godot(32752): GL_IMG_texture_format_BGRA8888
10-22 11:26:25.328: I/godot(32752): GL_IMG_texture_npot
10-22 11:26:25.328: I/godot(32752): GL_IMG_uniform_buffer_object
10-22 11:26:25.328: I/godot(32752): GL_OES_EGL_image
10-22 11:26:25.328: I/godot(32752): GL_OES_EGL_image_external
10-22 11:26:25.328: I/godot(32752): GL_OES_compressed_ETC1_RGB8_texture
10-22 11:26:25.328: I/godot(32752): GL_OES_depth24
10-22 11:26:25.328: I/godot(32752): GL_OES_depth_texture
10-22 11:26:25.328: I/godot(32752): GL_OES_egl_sync
10-22 11:26:25.328: I/godot(32752): GL_OES_element_index_uint
10-22 11:26:25.328: I/godot(32752): GL_OES_fragment_precision_high
10-22 11:26:25.328: I/godot(32752): GL_OES_get_program_binary
10-22 11:26:25.328: I/godot(32752): GL_OES_mapbuffer
10-22 11:26:25.328: I/godot(32752): GL_OES_packed_depth_stencil
10-22 11:26:25.328: I/godot(32752): GL_OES_required_internalformat
10-22 11:26:25.328: I/godot(32752): GL_OES_rgb8_rgba8
10-22 11:26:25.328: I/godot(32752): GL_OES_standard_derivatives
10-22 11:26:25.328: I/godot(32752): GL_OES_texture_float
10-22 11:26:25.328: I/godot(32752): GL_OES_texture_half_float
10-22 11:26:25.328: I/godot(32752): GL_OES_vertex_array_object
10-22 11:26:25.328: I/godot(32752): GL_OES_vertex_half_float
10-22 11:26:25.328: I/godot(32752): S3TC: 0 ATITC: 0
10-22 11:26:25.515: I/godot(32752): OpenSL Init OK!
10-22 11:26:25.664: I/godot(32752): BOOT SPLASH: 
10-22 11:26:25.664: I/godot(32752): BOOT SPLASH IS : 
10-22 11:26:26.945: I/godot(32752): ERROR OPENING FILE: icon.png
10-22 11:26:33.953: I/godot(32752): BACK PRESSED
10-22 11:27:16.664: D/GODOT(632): ** GODOT ACTIVITY CREATED HERE ***
10-22 11:27:16.781: D/GODOT(632): command_line is null? no
10-22 11:27:16.796: I/godot(632): **INIT EVENT! - 0x414d8790
10-22 11:27:16.796: I/godot(632): ***************** HELLO FROM JNI!!!!!!!!
10-22 11:27:16.796: I/godot(632): *******CLASS FOUND!!!
10-22 11:27:16.796: I/godot(632): STEP2, 0x1d20021e
10-22 11:27:16.796: I/godot(632): STEP3 1101821248
10-22 11:27:16.796: I/godot(632): STEP4, 0x5940002d
10-22 11:27:16.796: I/godot(632): STEP4.5, 0x1d200222
10-22 11:27:16.804: I/godot(632): STEP7
10-22 11:27:16.804: I/godot(632): STEP8
10-22 11:27:16.804: I/godot(632): *******GOT METHOD _dir_open ok!!
10-22 11:27:16.804: I/godot(632): *******GOT METHOD _dir_next ok!!
10-22 11:27:16.804: I/godot(632): *******GOT METHOD _dir_close ok!!
10-22 11:27:16.804: I/godot(632): *******GOT METHOD _dir_is_dir ok!!
10-22 11:27:16.804: I/godot(632): starting to attempt get methods
10-22 11:27:16.804: I/godot(632): *******GOT METHOD _init_audio ok!!
10-22 11:27:16.804: I/godot(632): *******GOT METHOD _write_buffer ok!!
10-22 11:27:16.804: I/godot(632): *******GOT METHOD _quit ok!!
10-22 11:27:16.804: I/godot(632): *******GOT METHOD _pause ok!!
10-22 11:27:16.804: I/godot(632): CMDLINE LEN 3 - APK EXPANSION I
10-22 11:27:16.867: I/godot(632): [1;31;40mERROR: create: [1;37;40mCondition ' !create_func ' is true. returned: 0
10-22 11:27:16.867: I/godot(632): [0;31;40m   At: core/os/mutex.cpp:39.[0;0;37m
10-22 11:27:16.867: I/godot(632): test construction 5
10-22 11:27:16.867: I/godot(632): running from dir /
10-22 11:27:16.867: I/godot(632): **SETUP
10-22 11:27:18.281: I/godot(632): Remote Debugger: Connection failed with status: 2'', retrying in 1 sec.
10-22 11:27:18.281: I/godot(632): has res dir: 
10-22 11:27:18.281: I/godot(632): exists engine cfg? 0
10-22 11:27:18.289: I/godot(632): *****SETUP OK
10-22 11:27:18.328: I/godot(632): **START
10-22 11:27:18.531: W/GodotView(632): creating OpenGL ES 2.0 context :
10-22 11:27:18.867: I/godot(632): ^_^_^_^_^ newcontext 1523516752
10-22 11:27:18.867: I/godot(632): ^_^_^_^_^ resize 1523516752, 1280, 752
10-22 11:27:18.874: I/godot(632): ANDROID MODULES : 
10-22 11:27:18.874: I/godot(632): mod count: 0
10-22 11:27:19.015: I/godot(632): GL_EXT_debug_marker
10-22 11:27:19.023: I/godot(632): GL_EXT_discard_framebuffer
10-22 11:27:19.023: I/godot(632): GL_EXT_multi_draw_arrays
10-22 11:27:19.023: I/godot(632): GL_EXT_shader_texture_lod
10-22 11:27:19.023: I/godot(632): GL_EXT_texture_format_BGRA8888
10-22 11:27:19.023: I/godot(632): GL_IMG_multisampled_render_to_texture
10-22 11:27:19.023: I/godot(632): GL_IMG_program_binary
10-22 11:27:19.023: I/godot(632): GL_IMG_read_format
10-22 11:27:19.023: I/godot(632): GL_IMG_shader_binary
10-22 11:27:19.023: I/godot(632): GL_IMG_texture_compression_pvrtc
10-22 11:27:19.023: I/godot(632): GL_IMG_texture_format_BGRA8888
10-22 11:27:19.023: I/godot(632): GL_IMG_texture_npot
10-22 11:27:19.023: I/godot(632): GL_IMG_uniform_buffer_object
10-22 11:27:19.023: I/godot(632): GL_OES_EGL_image
10-22 11:27:19.023: I/godot(632): GL_OES_EGL_image_external
10-22 11:27:19.023: I/godot(632): GL_OES_compressed_ETC1_RGB8_texture
10-22 11:27:19.023: I/godot(632): GL_OES_depth24
10-22 11:27:19.023: I/godot(632): GL_OES_depth_texture
10-22 11:27:19.031: I/godot(632): GL_OES_egl_sync
10-22 11:27:19.031: I/godot(632): GL_OES_element_index_uint
10-22 11:27:19.031: I/godot(632): GL_OES_fragment_precision_high
10-22 11:27:19.031: I/godot(632): GL_OES_get_program_binary
10-22 11:27:19.031: I/godot(632): GL_OES_mapbuffer
10-22 11:27:19.031: I/godot(632): GL_OES_packed_depth_stencil
10-22 11:27:19.031: I/godot(632): GL_OES_required_internalformat
10-22 11:27:19.031: I/godot(632): GL_OES_rgb8_rgba8
10-22 11:27:19.031: I/godot(632): GL_OES_standard_derivatives
10-22 11:27:19.031: I/godot(632): GL_OES_texture_float
10-22 11:27:19.031: I/godot(632): GL_OES_texture_half_float
10-22 11:27:19.031: I/godot(632): GL_OES_vertex_array_object
10-22 11:27:19.031: I/godot(632): GL_OES_vertex_half_float
10-22 11:27:19.031: I/godot(632): S3TC: 0 ATITC: 0
10-22 11:27:19.179: I/godot(632): OpenSL Init OK!
10-22 11:27:19.398: I/godot(632): BOOT SPLASH: 
10-22 11:27:19.398: I/godot(632): BOOT SPLASH IS : 
```

The "network/debug_host" property is set properly and I can ping back and forth between pc and tablet.
I don't know what "Connection failed with status: 2" means, I can see the debug text on the editor console.

I also checked using netstat in the tablet and it says there is a connection established between 192.168.10.102:34722 (tablet) and 192.168.10.101:6007 (pc) while running the app.

Am I missing some kind of permission setup?
I'm using Android SDK Tools v23, Platform Tools v20 and SDK for Android 4.0.3 (API 15).
Should I update some of these libs?

**Comment by reduz** [comment] 2015-12-29 00:18
Oh, may it be your export templates are old?

**Comment by FEDE0D** [comment] 2015-12-29 00:40
Nope. I compiled several times from the repo and still the same behaiviour.
Log: https://gist.github.com/FEDE0D/b569185f211333be618e

It's wierd because It makes the same thing on another phone, a Sony Xperia ST21a

![phone](https://cloud.githubusercontent.com/assets/6296184/12027797/50746ebe-adab-11e5-8f5c-a0a3b2a004cd.png)

May it be something on my network config? I don't think so, because the IP it's there on the editor and I tried pinging back and forth between pc and phone.

**Comment by FEDE0D** [comment] 2015-12-29 00:41
I will try hardcoding the IP on the engine code and see if that works.

**Comment by akien-mga** [comment] 2016-05-20 12:01
Do you still get the same issue with 2.0.3?

**Comment by FEDE0D** [comment] 2016-05-21 15:30
Yeap, the same with 2.0.3. I got the same error message about **gethostbyname failed**

**Comment by FEDE0D** [comment] 2016-05-21 15:32
It seems like I'm the only one getting this error.
I'll try to test this on windows and on another computer and see if the device I'm using (Samsung Galaxy Tab 2.0) has something to do with it.

**Comment by akien-mga** [comment] 2018-07-02 17:34
PR #8699 mentions that it might have fixed this issue - given that 2 years passed since it was last reported, I'll close it. Please comment if you can still reproduce it on Godot 3.0.x.

**Closed by akien-mga** 2018-07-02 17:34 UTC
Labels: bug, confirmed, platform:android, topic:core
