### ISSUE TITLE
Double clicking single character words ("1", "i", "n", etc.) doesn't select them in some circumstances

### ISSUE THREAD

**Issue by mathgeniuszach** [godotengine/godot#97430] opened 2024-09-24 23:25 UTC
### Tested versions

- Reproducible in: 4.4.dev2, 4.3.stable, and 4.0.4.stable
- Not Reproducible in 3.5.3.stable, 3.0.6.stable, and other Godot 3.0 builds

### System information

Godot v4.3.stable (77dcf97d8) - NixOS #1-NixOS SMP PREEMPT_DYNAMIC Wed Sep 18 17:24:10 UTC 2024 - X11 - GLES3 (Compatibility)

### Issue description

Double clicking single character identifiers/words does not automatically select them, similar to how double clicking parenthesis or braces does not select them.

### Steps to reproduce

1. Place this code in any script in the editor:
```gdscript
func print_ten():
	for i in range(10):
		print(i)
	return 1
```
2. Double click on the "i" variable and the "1", and also to the left and right of them
3. Notice that sometimes the word is selected, other times it isn't

### Minimal reproduction project (MRP)

Not necessary - just follow the steps to reproduce.

**Comment by kitbdev** [comment] 2024-09-25 17:52
- duplicate of https://github.com/godotengine/godot/issues/89551

**Closed** 2024-09-25 17:53 UTC
Labels: bug, topic:editor, usability
