### ISSUE TITLE
FontVariations saved into TSCN create huge file sizes

### ISSUE THREAD

**Issue by elvisish** [godotengine/godot#86096] opened 2023-12-12 22:32 UTC
### Tested versions

4.1.3

### System information

Windows 10

### Issue description

Saving a font variation on a tscn creates a huge file size, here's part of a tscn with a FontVariation stored on the tscn:
`[sub_resource type="FontVariation" id="FontVariation_eg52i"]
base_font = ExtResource("2_dvnvg")
spacing_glyph = -1
spacing_top = -5

[sub_resource type="Image" id="Image_qgb6d"]
data = {
"data": PackedByteArray(255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0,.....`

The file is 20,000,000 characters long and 1,300 lines because of this. It should be documented that it inflates the file sizes if not saved as an external file.

### Steps to reproduce

Create a FontVariation on a Label or other node that uses a theme override and keep the FontVariation stored inside the tscn (don't save externally as a resource file).

### Minimal reproduction project (MRP)

N/A.

**Comment by AThousandShips** [comment] 2023-12-12 22:33
Sounds like a duplicate of:
* https://github.com/godotengine/godot/issues/82254

**Comment by elvisish** [comment] 2023-12-12 22:35
> Sounds like a duplicate of:
> 
> * [FontFile's cached images are always duplicates of set images, and are bundled with resource when saved to disk. #82254](https://github.com/godotengine/godot/issues/82254)

Is the solution to save the FontVariation externally? I need to backup my project and experiment to see what gets the size down but not entirely sure what the best strategy is first.

**Comment by Calinou** [comment] 2023-12-12 22:41
Thanks for the report! Consolidating in https://github.com/godotengine/godot/issues/82254.

**Closed by Calinou** 2023-12-12 22:41 UTC

**Comment by elvisish** [comment] 2023-12-13 00:19
Just wanted to add that it was actually the FontFile and not FontVariant that was causing the huge file size.
