### ISSUE TITLE
Cannot save script file if no scene file is open

### ISSUE THREAD

**Issue by chucklepie** [godotengine/godot#30546] opened 2019-07-12 20:17 UTC
**Godot version:**
3.1.1 stable

Windows 10

**Issue description:**
I am editing a .gd file, it is a global file I have for singleton autoload. If I do not have a scene file open (i.e. something showing in the scene pane) I cannot save the script file, I get a 'a root node is required to save the scene'. 

The .gd file is not associated with any scene, and I am not saving a scene, just a script.

Additionally to compound this, if I have scene1.gd script file open (associated with scene1.tscn), but I have open the scene file scene2.tscn (which does not associate with scene1.gd), then it lets me save. 

i.e. The IDE isn't bothered what you have open as a scene, it will not let you save a gd script file if you have something, anything, open. 

Pretty sure this is a historical thing when script files were (possibly) only embedded in scenes so having an external script was not applicable. However, if this really is 'as designed' then perhaps a less cryptic message would be useful (e.g. instead of ' root node is required to save the scene', 'you must have a scene open to save a script').

btw, possibly linked to this is when you open a .gd file the tab always displays the name of the currently open scene. So regardless of whether the .gd file is associated with the scene or not, you get the name of the open scene as the tab for the script file. Or 'empty' if you have no open scene. Indeed, as a side issue, I think related to this issue is the reason why you cannot have more than one .gd script file open, you have to use another pane that sucks up screen width just to open another script file and replace the current one...

**Steps to reproduce:**
1. open a .gd file
2. close the current scene
3. press ctrl-s
4. profit

**Minimal reproduction project:**
A project with a gd and a tscn file.

**Comment by Calinou** [comment] 2019-07-12 20:26
Duplicate of #22730.

**Closed by Calinou** 2019-07-12 20:26 UTC

**Comment by chucklepie** [comment] 2019-07-12 20:35
I did try to search, honest! but found nothing.

I will raise another suggestion for my other points.
