### ISSUE TITLE
Clear all children of a node

### ISSUE THREAD

**Issue by AlexHolly** [godotengine/godot#8125] opened 2017-03-23 20:37 UTC
I am looking for something like `node.clear()` in gd.

Can we add this to node?

**Comment by Zylann** [comment] 2017-03-24 00:33
You can do it quite easily with this:

```gdscript
for i in range(0, get_child_count()):
    get_child(i).queue_free()
```

**Comment by eon-s** [comment] 2017-03-24 02:27
or
`while get_child_count(): remove_child(get_child(0))`

**Comment by CowThing** [comment] 2017-03-24 03:52
@eon-s Just removing the child node would leave them in the aether, taking up space. The node needs to be freed for it to be deleted.

Another way would be
```GDScript
for child in get_children():
	child.qeue_free()
```

**Comment by eon-s** [comment] 2017-03-24 04:16
@CowThing I don't think Godot works like that https://github.com/godotengine/godot/blob/5dbf1809c6e3e905b94b8764e99491e608122261/scene/main/node.cpp#L1462

**Comment by CowThing** [comment] 2017-03-24 04:34
I think the nodes still exist, even when they're not in the tree and have no reference. I've had cases before where I forgot to free nodes after I was done with them, and even though they had no parent and were not in the tree, they still increased the number of objects in the game. After changing it to free them the object count no longer increased.

**Comment by eon-s** [comment] 2017-03-24 04:36
@CowThing interesting (that may be a bug)

**Comment by akien-mga** [comment] 2017-03-24 06:47
That's not a bug and @CowThing is right, `remove_child` just removes the node from the current SceneTree. If you keep a handle on it, you can still `add_child` it later to the same node or another one.

**Comment by CharlesWoodhill** [comment] 2017-03-26 13:09
isnt this a good example for why nodes should be refcounted?
is the "overhead" of refcounting that big?

doesnt it produce "memory leaks"
and nodes are used by scripters maybe not aware about memory issues, or they should not have to think about it.

**Comment by bojidar-bg** [comment] 2017-03-28 10:39
@CharlesWoodhill That would indeed be a nice thing to do, would you mind moving it to a seperate issue? :smiley:

**Closed** 2017-04-12 12:59 UTC
Labels: feature proposal, topic:core

**Comment by karroffel** [comment] 2017-09-09 15:26
Just dropping this, in 3.0 you can use `some_node.propagate_call("queue_free", [])` to free an entire branch of nodes.

**Comment by canadaduane** [comment] 2018-04-03 03:33
Just a note regarding @karroffel's solution: note that the `propagate_call` call also sends `queue_free` to the parent of the children, which is not the same result as @CowThing's `for` loop solution. I believe OP is asking for a method to remove all children, not including the parent node.

**Comment by ryancheung** [comment] 2019-01-26 07:05
Do we still need to manually free nodes now (latest 3.0/3.1), I notice nodes would automatically get freed on change scene or game exit, using `use_leak_sanitizer=yes` on build.

**Comment by CowThing** [comment] 2019-01-26 13:46
Nodes have always been automatically freed on scene change or game exit. You only have to manually free() or queue_free() nodes when you want those nodes deleted.

**Comment by muchitto** [comment] 2019-08-06 10:56
Sooo we still have to put this script:

`for child in get_children():
		child.queue_free()`

Everywhere we want this to happen, even though this probably is something that is written a lot and so should just be a oneliner (`queue_free_children()` or something) or am I missing something? 😄

**Comment by richard-porteous** [comment] 2020-12-16 21:57
using the info above I came up with this and it seems to work for me
rows is my vboxcontainer

	for child in rows.get_children():
		rows.remove_child(child)
		child.propagate_call("queue_free", [])
