### ISSUE TITLE
Possible bug? Tween won't animate all if 'set_repeat" is unchecked.

### ISSUE THREAD

**Issue by Barina** [godotengine/godot#6923] opened 2016-10-26 00:20 UTC
**Operating system or device - Godot version:**
Godot Engine 2.2 on Windows 7 64bit

**Issue description** (what happened, and what was expected):
When stacking animations with interpolate_method, for the same method in the same object, only the first animation is actuated.
I'm getting that issue on 2.2 but it works fine in 2.1 stable.

**Steps to reproduce:**
Create a Sprite (for instance)
Create new Tween
In code write:
```
tween.interpolate_method(sprite, "set_scale", from, to, 1, tween.TRANS_LINEAR, t.EASE_IN)
tween.interpolate_method(sprite, "set_scale", to, from, 1, tween.TRANS_LINEAR, t.EASE_IN, 1) <- set delay 
tween.set_repeat(false)
tween.start
```
Run the project
Watch it won't scale back to initial scale

Now pass True to set_repeat and run again.

**Link to minimal example project** (optional but very welcome):

**Comment by vnen** [comment] 2016-10-26 00:53
Seems related (or the same as) #6864.

**Comment by Barina** [comment] 2016-10-26 01:08
Yes seems like the same issue. I didn't find it earlier..

**Comment by bojidar-bg** [comment] 2016-10-26 09:13
Closing as duplicate of #6864 then.

**Closed by bojidar-bg** 2016-10-26 09:13 UTC
