### ISSUE TITLE
After installation file is getting force closed on windows 10 64bit

### ISSUE THREAD

**Issue by SilverFoxA** [godotengine/godot#2580] opened 2015-10-07 18:15 UTC
I have downloaded the game engine binary files and tried running it, but on run stage the shell command gets executed and directly after that i get a message from the OS that the file has stop working. Its happening all the time, i tried downloading the fresh copy multiple time as well but that's of no use.

Looking forward to hear back from you.

**Comment by bojidar-bg** [comment] 2015-11-05 13:47
Possible duplicate of #495 , #1693 , or #2267 (and probably many more issues). Please provide more info (esp. logs) so that your issue is easier to understand. :smile:

**Comment by reduz** [comment] 2015-12-29 12:36
closed because not much information has been provided. It' s likely missing GLES2 compatible hardware

**Closed by reduz** 2015-12-29 12:36 UTC
Labels: bug, platform:windows
