### ISSUE TITLE
C# Beta 8: Editor crash on new C# script or preexisting project

### ISSUE THREAD

**Issue by Bombfuse** [godotengine/godot#26315] opened 2019-02-26 17:21 UTC
**Godot version:**

3.1 Mono Beta 8

**OS/device including version:**
MacOS Mojave

**Issue description:**
Projects crash on new C# script. Additionally, when loading previous projects with preexisting C# scripts, the editor crashes.
[1551201337.txt](https://github.com/godotengine/godot/files/2906691/1551201337.txt)
<img width="647" alt="screen shot 2019-02-26 at 9 20 47 am" src="https://user-images.githubusercontent.com/26308406/53432878-36e86680-39a8-11e9-99c8-ac15253b847f.png">

<img width="1083" alt="image" src="https://user-images.githubusercontent.com/26308406/53432664-c80b0d80-39a7-11e9-82ae-cd7229b8ce39.png">

**Steps to reproduce:**
Start a new project, create a node, create a new C# script.

**Minimal reproduction project:**

[thing.zip](https://github.com/godotengine/godot/files/2906686/thing.zip)

**Comment by akien-mga** [comment] 2019-02-26 18:11
Can't reproduce on Linux with 3.1 beta 8 and MSBuild 16.0.0.0.

**Comment by hpvb** [comment] 2019-02-26 20:36
I moved the contents of the GodotSharp directory around as indicated here: https://docs.godotengine.org/en/latest/development/compiling/compiling_with_mono.html#editor. Perhaps my original approach of just placing the GodotSharp directory in Contents/MacOS was actually correct?

**Comment by hpvb** [comment] 2019-02-26 20:40
I made a mistake, I placed it in Contents/MacOS and it should've been one below.

**Comment by hpvb** [comment] 2019-02-26 20:46
I've reuploaded https://download.tuxfamily.org/godotengine/3.1/beta8/mono/Godot_v3.1-beta8_mono_osx.64.zip it should be fixed now.

**Closed by hpvb** 2019-02-26 20:46 UTC
Labels: bug, platform:osx, topic:mono

**Comment by neikeq** [comment] 2019-02-26 20:51
Placing the `GodotSharp` dir in `Contents/MacOS` should also work. Was it not?

**Comment by hpvb** [comment] 2019-02-26 21:18
@neikeq yeah that worked fine but I thought I should follow the docs page instead :)
