### ISSUE TITLE
Odd results when setting mouse mode to captured.

### ISSUE THREAD

**Issue by Einlander** [godotengine/godot#14855] opened 2017-12-20 02:50 UTC
Build date: 2017-12-15 12:12:09
Git commit id (short): 433cb6f49
Windows 10 Pro x64

Issue:
When setting the mouse mode to Input.set_mouse_mode(Input.MOUSE_MODE_CAPTURED) to track mouse movement for a 3d controller, the node._input() seems to sporadically update. 

I expected it to give similar results as MOUSE_MODE_HIDDEN or MOUSE_MODE_CONFINED.

**Steps to reproduce:**
In a 3d Scene add  Input.set_mouse_mode(Input.MOUSE_MODE_CAPTURED) to _enter_tree() or _ready()

**Minimal reproduction project:**

[FPS_Controller_Kinematic.zip](https://github.com/godotengine/godot/files/1574009/FPS_Controller_Kinematic.zip)

**Comment by LeonardMeagher2** [comment] 2017-12-20 03:16
There is an issue with an infinite loop being created in the event loop.
When the mouse is warped to the center, it fires an event, which then warps the mouse again.

A work-around I found was to check mouse position, determine delta, and warp the mouse in `_(physics_)process()` to avoid the loop.

**Comment by Einlander** [comment] 2017-12-20 03:28
So manually do the relative calculation yourself? That's what I started doing, but i put it in the regular process. Will try this way.

**Comment by Einlander** [comment] 2018-01-04 09:05
So on IRC I discovered that godot does not like my screen dpi.

> [02:59:20:79] <Einlander> i think i found the problem
[02:59:23:94] <tilpner> Yes, the relative movements are larger when moving faster
[02:59:55:76] <tilpner> (And I of course stop receiving events when I stop moving the mouse)
[03:00:08:50] <Einlander> it dosnet play well with custom scaling
[03:00:26:88] <Einlander> i have my pc set to 125% scaling
[03:00:32:60] <Einlander> it shits the bed
[03:00:39:14] <Einlander> 100% it's fine
[03:00:49:11] <Calinou> set the executable as DPI-aware
[03:00:58:44] <Calinou> right-click -> Properties -> Compatibility -> Force scaling mode to Application
[03:01:13:38] <Calinou> Godot currently doesn't mark itself as DPI-aware, so you'll have to do this for now
[03:01:21:72] <Calinou> (it's already reported on GitHub)
[03:01:29:39] <Einlander> and it's finde
[03:01:33:13] <Einlander> *fine

As Calinou pointed out you need to set the programs dpi compatibility.

**Comment by VictorGonzalezFernandez** [comment] 2018-06-11 16:42
In 2D same problem detected in Windows 10. It is not only in 3D. Not fixed to the current date.
Version Godot 3.0.2

**Comment by EzraT** [comment] 2018-06-21 11:35
Could you elaborate a little bit on your workaround @LeonardMeagher2 ?
Perhaps with an example?
I've been trying to find a fix for this issue since 3.0's release and haven't been able to pull it off.
It still happens to me in 3.0.3 using all the methods I can think of, using _input, or _process/_physics_process doing the mouse calculation myself, its all the same.

I really hope this bug can be fixed soon, making any game that uses MOUSE_MODE_CAPTURED is pretty much a no go like this.

**Comment by VictorGonzalezFernandez** [comment] 2018-06-21 11:49
A temporary solution, but it is bad and only serves for development is

No use:
Input.set_mouse_mode(Input.MOUSE_MODE_CAPTURED)

Use:
Input.set_mouse_mode(Input.MOUSE_MODE_HIDDEN )

The failure must be fixed, before projects go into production!

**Comment by Calinou** [comment] 2018-06-21 14:42
Can this be reproduced on Linux, macOS or Windows 7/8.1?

**Comment by EzraT** [comment] 2018-06-21 14:57
I have reproduced it multiple times on Linux, on Xubuntu 17.10, and Ubuntu Budgie 18.04 specifically.
I currently do not have any Windows or OSX machines at my disposal, but here is an issue of someone with the same problem, on Windows 10.
https://github.com/godotengine/godot/issues/17288

**Comment by EzraT** [comment] 2018-07-21 20:40
I'm starting to think that this is at-least partially OS related, I recently switched Linux distro's (from Ubuntu Budgie 18.04, to Linux Mint 19 specifically) and, to my surprise, this issue doesn't seem to happen anymore in the projects I've tried it with so far, I no longer get the weird stuttering and hitching after the switch, with the same Nvidia Driver version installed as-well.

I don't know for sure if this is actually related to something in Linux Mint being setup differently or something, but I do find it quite odd that the previous distro's I used, namely Xubuntu 17.04, and Ubuntu Budgie 18.04, all very clearly suffer from this problem, there are even people on Windows 10 who have reported on it too.

I am of course happy that it no longer happens on my end, but at the same time I still have no idea what it is exactly causing this issue, this should work the same way across all OS's right?

Tested on both 3.0.5 and the (at the time of writing) latest master.

**Comment by KoBeWi** [comment] 2020-06-14 19:09
I tried the demo it is seems fine. Can anyone still reproduce it in 3.2.x?

**Comment by akien-mga** [comment] 2021-04-28 09:55
No answer, so assuming fixed.

**Closed by akien-mga** 2021-04-28 09:55 UTC
Labels: bug, topic:core

**Comment by EzraT** [comment] 2021-04-28 10:53
Yeah, I have not been able to reproduce this one either.
