### ISSUE TITLE
GridMap tiles with textures rendered completely black

### ISSUE THREAD

**Issue by blackears** [godotengine/godot#75094] opened 2023-03-19 09:02 UTC
### Godot version

v4.0.stable.official [92bee43ad]

### System information

Windows 10, Compatability

### Issue description

I'm trying to use GridMap to create a level for a game.  I've created my blocks and exported them into a MeshLibrary.  Unfortunately, when I use them, the texture is rendered as if albedo were set to pure black.

### Steps to reproduce

Create a MeshLibrary by
- Making a new scene
- add a block (with a texture map on it) to the scene
- Selecting Scene/Export As/Mesh Library from the main menu

Create a GridMap
- Create a new scene
- Add a GridMap
- Set the MeshLibraray you created earlier as the MeshLibrary of the grid map
- Click on a block 
- Drag in the viewport to draw with the block

You will see that all the blocks laid out in the viewport will be rendered as black.

### Minimal reproduction project

[GridMapError.zip](https://github.com/godotengine/godot/files/11010567/GridMapError.zip)

**Comment by KoBeWi** [comment] 2023-03-19 14:20
Duplicate of #74111

**Closed by KoBeWi** 2023-03-19 14:20 UTC
