### ISSUE TITLE
`Tree` column titles have weird sizes across the editor

### ISSUE THREAD

**Issue by YeldhamDev** [godotengine/godot#51484] opened 2021-08-11 00:28 UTC
### Godot version

18bd0fee5a8aa360177cbe14a16d6be69f088d8f

### System information

N/A

### Issue description

Across various areas of the editor, `Tree` items that have visible column names have very weird spacing, often resulting in cutoff strings:

![Screenshot at 2021-08-10 21-14-58](https://user-images.githubusercontent.com/30739239/128951306-b4076bd8-4732-4583-886d-d0726eb168b3.png)
![Screenshot at 2021-08-10 21-15-30](https://user-images.githubusercontent.com/30739239/128951319-5fbab3ab-38bf-4bd2-9cb3-2d2ba5540627.png)

They also seem to ignore the right border:

![Screenshot at 2021-08-10 21-17-04](https://user-images.githubusercontent.com/30739239/128951623-58d97516-4815-48f7-8c5f-0e2015fddb1f.png)

~~I'm almost certain that is related to this PR: #49917~~

~~CC @groud~~ Never mind, it caused by #50146, CC @reduz

### Steps to reproduce

Just search for `Tree` elements with visible column names.

**Comment by timothyqiu** [comment] 2021-08-11 01:36
See also: #50657

**Comment by akien-mga** [comment] 2021-09-21 14:25
Duplicate of #52891.

**Closed by akien-mga** 2021-09-21 14:25 UTC
Labels: bug, topic:editor, confirmed, regression, topic:gui
