### ISSUE TITLE
Quick load @export custom resource shows no result

### ISSUE THREAD

**Issue by Ohan17** [godotengine/godot#71061] opened 2023-01-08 12:39 UTC
### Godot version

4.0-beta10_win64

### System information

Windows 10, RTX 3050 Laptop GPU

### Issue description

Quick loading not working with custom resources.
 
![image](https://user-images.githubusercontent.com/66206021/211196163-a13b1ce9-6aea-43d9-8418-495ee36a7177.png)
![image](https://user-images.githubusercontent.com/66206021/211196247-c743be36-8d0e-4d56-a0fa-4112fabec3a6.png)
![image](https://user-images.githubusercontent.com/66206021/211196120-e5fcf387-64a5-439f-9cdd-0a65ecd53683.png)
![image](https://user-images.githubusercontent.com/66206021/211196139-c4783439-3e2e-4404-adbf-7ac88aeb492f.png)

### Steps to reproduce

See images above.

### Minimal reproduction project

[MRP.zip](https://github.com/godotengine/godot/files/10368421/MRP.zip)

**Comment by KoBeWi** [comment] 2023-01-08 20:31
Duplicate of #67119

**Closed by KoBeWi** 2023-01-08 20:31 UTC
