### ISSUE TITLE
The Android version of the script editor cannot wrap lines

### ISSUE THREAD

**Issue by Vasilyevski** [godotengine/godot#72301] opened 2023-01-29 09:27 UTC
### Godot version

4.0beta15

### System information

Android10 MT6765 Mobile

### Issue description

When I press the newline key in the script editor, it does nothing.
Normally it should switch to the next line.
Copy and paste the script with line breaks into the script editor and everything will appear on one line.
(I am following the tutorial in https://docs.godotengine.org/zh_CN/latest/getting_started/step_by_step/scripting_first_script.html#)

### Steps to reproduce

Create a project, open the script editor, create the script, press the newline key.

### Minimal reproduction project

N/A

**Comment by akien-mga** [comment] 2023-01-29 10:03
Duplicate of #72105

**Closed by akien-mga** 2023-01-29 10:03 UTC
