### ISSUE TITLE
Improve gamepad support

### ISSUE THREAD

**Issue by larmi** [godotengine/godot#49] opened 2014-02-12 14:31 UTC
gamepad doesn't work with linux or win 7.
i got some random keys to work like:
10 A
11 Y
4 right stick button
7 left stick button
8 B
9 on x
gamepad doesn't work with linux or win 7.
i got some random keys to work like:
10 A
11 Y
4 right stick button
7 left stick button
8 B
9 X.
i used xboxdrv in Linux with mimic and it should be recognized as normal controller.
with win 7 nothing. all axis doesn't give anything with both platforms doesn't work.
sorry for English language  i tried to use translate to fix typos.

**Comment by MangelMaxime** [comment] 2015-01-17 22:28
The Joystick example is not working under OSX 10.10

For information, I haven't try adolson solution yet.

**Comment by adolson** [comment] 2015-01-17 22:32
I wrote the joystick example, and if it doesn't work at all on OSX, then my
remapping stuff won't work either, I'm sure. Maybe there's just no joystick
support at all in OSX? I know Windows is almost completely broken (see
#909).

**Comment by reduz** [comment] 2015-01-17 23:26
does OSX port even have joystick support? :P

**Comment by MangelMaxime** [comment] 2015-01-17 23:47
Under OSX we have a controller for xbox 360. It's working with other games.

Ressource :
http://www.jacobtomlinson.co.uk/2014/10/17/use-xbox-360-pad-with-yosemite/
https://github.com/d235j/360Controller/releases

**Comment by kennethsg** [comment] 2015-01-23 20:36
Has somebody been able to use the controller on Ouya ?

**Comment by Krzycho666** [comment] 2015-02-27 14:17
How about making a SDL_GameControllerDB to Godot wrapper?

**Comment by adolson** [comment] 2015-02-27 14:22
This has been suggested already.
Currently, Godot is using the /dev/input/js* API which doesn't appear to
show hats (or at least there's none presented to the Godot input events),
whereas SDL2 is using the /dev/input/event* API which does, so the mappings
are impossible.
Ariel is working on fixing this, however.

**Comment by punto-** [comment] 2015-02-27 15:06
I have code that reads the sdl gamecontrollerdb format and remaps the
joystick events. As adolson mentions we have to change the method we use to
get events on linux, and we also need to figure out how to get the GUID for
the joysticks (I'm not sure how SDL does this).

and I have to make a pull request with my code so people can test it.

**Comment by w84death** [comment] 2015-04-03 12:56
We tested OUYA controller (on the OUYA) and it works ok.

**Comment by ShadowKyogre** [comment] 2015-07-01 20:38
Was talking with @punto- earlier today on IRC since [this comment](https://github.com/okamstudio/godot/issues/49#issuecomment-76401302) is affecting my attempts at developing games on Godot quite a bit. That's because that without doing checks like what SDL does to make sure something is a joystick, it will think that certain pieces of hardware like the ones listed [here](https://gist.github.com/denilsonsa/978f1d842cf5430f57f6) are joysticks.

I'm reposting the links I showed @punto- on IRC to make sure that they don't get lost and can be referred to in the future.

# Linux
http://hg.libsdl.org/SDL/file/d968c87f2a5d/src/joystick/linux/SDL_sysjoystick.c#l730

# Android
http://hg.libsdl.org/SDL/file/d968c87f2a5d/src/joystick/android/SDL_sysjoystick.c#l509
# Macs
http://hg.libsdl.org/SDL/file/d968c87f2a5d/src/joystick/darwin/SDL_sysjoystick.c#l679

# Windows
* http://hg.libsdl.org/SDL/file/d968c87f2a5d/src/joystick/windows/SDL_dinputjoystick.c#l830 for Windows's dinput
* http://hg.libsdl.org/SDL/file/d968c87f2a5d/src/joystick/windows/SDL_xinputjoystick.c#l289 for xinput
* http://hg.libsdl.org/SDL/file/d968c87f2a5d/src/joystick/windows/SDL_mmjoystick.c#l309 and this other one that also reaches into the same registry bits that Godot currently uses

**Comment by Hinsbart** [comment] 2015-07-01 22:52
As already mentioned in a few other places, I'm currently working on making @punto- s remapping code actually usable so I'm giving you an update on this^^
 
So far I've got it running nicely on linux, with correct uids (some weird stuff happening in SDLs code here), events, hotplugging and detection of false devices as mentioned by @ShadowKyogre (I also use one of those MS keyboards :P ).

I wanted to publish it some weeks ago but decided to tackle windows first... Unfortunately MS decided to cripple xinput compatible controllers under directInput, so one has to support both APIs.
As of now, I'm almost done with the dinput implementation (having troubles with hotplugging). After that, xinput should be pretty straightforward. 

I plan on writing a post in the dev mailing list  to ask for help with some decisions like deadzone handling, trigger as axis, how to deal with gamepads not mappable by SDL (their implementation has flaws) and some other stuff. By that time I should have a cleaned up version of my linux code available for you to test ;)

**Comment by adolson** [comment] 2015-07-01 22:58
I'll be watching for your devel post... I will have input to give you, no
doubt, from my experiences writing and feedback received on the SUTjoystick
module for Godot.

**Comment by akien-mga** [comment] 2015-10-29 10:10
What's the status on this issue guys?

**Comment by punto-** [comment] 2015-10-29 10:23
We found a library with the code we need to retrieve the correct input
events from the OS (we can probably adapt the code to our OS classes
instead of merging the library), and we have the code that maps the events
using SDL's mapping db. We still don't know how SDL comes up with the UUID
for each controller tho, that's the last missing piece to have full support.

**Comment by agameraaron** [comment] 2015-11-16 00:57
I'm the one who created the recently closed referenced issue. Bit of an update to that with my input on this issue.

I ended up making my setup program have an input config that makes no assumptions so the player can assign the keys how they wish with no default. It would be nice if it had this feature so there would be less hassle involved in general and I could just include some kind of default. I'm biased since I hate the 360's D-pad & apparently everyone else wants to make it standard. Pfft.

I still have the Dual Shock 4, but I now use a Gamecube controller as standard because the mini USB plug keeps disconnecting from the base of the controller. I'm sure the DS4 makes a better wireless controller.

Once this issue is addressed, I'll go through each of my gamepads to see what works.

**Comment by benmoran56** [comment] 2015-11-16 01:02
I could supply some example code to show how the guid is generated on Linux. I haven't figured out yet on Mac/Windows.

**Comment by Hinsbart** [comment] 2015-12-30 18:47
Guess this can be closed now. I haven't recieved much feedback for the new gamepad code but I assume it's fine now ^^

The only thing left that I'd like would be a way to get analog values for the shoulder triggers. But I don't know if that's really related to this issue or if I should open a new one.

**Comment by punto-** [comment] 2015-12-30 19:53
Those are usually reported as axis values, are they mapped on the sdl
database? (would they have to be mapped twice, one for a button index, one
for an axis?) On some joysticks, _all_ the buttons have analog values, I
don't think we need that, but for the triggers it's reasonable..

**Comment by adolson** [comment] 2015-12-30 21:41
I wasn't aware there was new gamepad code to test, since I haven't been monitoring the commits, only the issues I am subscribed to.

Not all gamepads have analog triggers, by the way.

**Comment by Hinsbart** [comment] 2015-12-30 23:10
Yeah, most gamepads allready report anolog trigger values internally. And of couse they are also mapped. After remapping they are recieved as button 5 and 6.

The problem is, that a raw gamepad event can only be mapped to a single godot event currently.
So it's either "trigger as analog" or "trigger as button".

That makes it a question of backwards compatibility. If it's a concern to have anolog values per default, then we need to tweak the remapping mechanism a bit to allow both at the same time. If not then it's basically a one-liner ^^

**Comment by punto-** [comment] 2015-12-30 23:26
I think we should send both, a button event and an axis event. We probably
don't need the information on the SDL db if it's standard that L2 and R2
are triggers, we can just add a condition when they're analog values, we
adjust the range (0 to 1) and send the additional axis value.

**Comment by Hinsbart** [comment] 2015-12-31 00:37
Ahh yeah, I forgot that we already know whether an event is a trigger. It's easy then, I'm waiting for it to compile ^^ 

I suppose axes 4 and 5 are ok for that? I guess I'll also add 2 new constants like: "JOY_L2_ANALOG".
Right now there are "JOY_ANALOG_2_X" and "JOY_ANALOG_2_Y" that map to axes 4 & 5.
Should we keep those?

**Comment by Hinsbart** [comment] 2015-12-31 00:58
Another thing, should we also send axis events for non-analog triggers? So users can decide to just check the axis values for triggers without the need for a fallback to buttons.

**Comment by adolson** [comment] 2015-12-31 01:01
Yes. That is what I did with my SUTjoystick module, just sent a 0 or 1 for
non-analog triggers.

Also, I'd say get rid of any unneeded constants. They're just going to wind
up confusing people.

**Comment by punto-** [comment] 2015-12-31 01:10
non-analog triggers (like L and R you mean?) should be button events. Most
games want button events, you only want the analog value for specific
things, like a racing game maybe? Also the Input class keeps track of the
axis values, so I wouldn't create a bunch of extra axis that don't actually
come from the hardware.. I'm not sure which values to use for the axis, is
there ever a 3rd analog? What about the accelerometers on the pad, do those
ever map as an axis? I think on the microsoft apis those triggers are
actually axis Z of the analogs right?

I think use axis 6 and 7 just in case..

**Comment by adolson** [comment] 2015-12-31 01:14
So then if we don't "fake" analog values for gamepads with digital-only
triggers, and a game is coded to use analog trigger values only, what
happens when someone has a gamepad with digital-only triggers tries to play
said game?

Sure, every developer can code for this case, but why should they have to
when we can have a built-in solution that means the gamedevs don't have to
concern themselves with those kinds of details?

(One example off the top of my head is the Hori GemPad 3. No analog values
on the triggers.)

**Comment by Hinsbart** [comment] 2015-12-31 01:35
Yes, that's exactly what I had in mind.
Everything else (including L1 and R1) should stay as button events of couse.

Also, regarding accelerometers and such: right now we just ignore every event that isn't mapped in the db. So currently gamepads with a valid mapping will never output any axis above 3.

**Comment by punto-** [comment] 2015-12-31 02:34
ok adolson is right, fake axis values for non-analog L2 and R2, since I
don't have any pads around me that don't have analog triggers (except for
the wii u one), it's safe to assume that a pc pad will have them. There's
still the possibility that the pad won't have L2 and R2 at all (the
bluetooth from the Gear VR, and the Vita for example), so games will have
to keep that in mind, but the most common pads are the xbox ones, so it's a
safe assumption for PC.

**Comment by Hinsbart** [comment] 2015-12-31 03:36
Another thing that came to my mind is exposing a few functions like `is_joy_mapped()`, `get_joy_guid()` and `set_joy_mapping()`.

That way we can provide a simple mapping demo which one can use to easily get gamepad mappings without going through steam or compiling the sdl2 mapping program.
You could also use it for an in-game dialog, or just to ignore non-mapped gamepads.

**Comment by punto-** [comment] 2015-12-31 13:52
That's good, but assume that the default implementation is that all
joysticks are "known" by the system, and not mapped, because the OS already
sends the events with the rights indices for everything, etc. That's how we
want it to work with no effort from the game (that's kinda how it works
right now if you plug a known joystick) This is how a console works for
example, since there's only 1 type of joystick. I guess the default
implementation is "is_joy_mapped()" returns true, and "get_guid" returns
"default" or something like that, and on PC it does the extra work of
mapping, etc.

**Comment by adolson** [comment] 2016-01-01 23:21
On Linux, some gamepads require Xboxdrv to be useful. One such example is the Nexus gamepad. I tried it out, but it doesn't work in Godot anymore (used to, same gamepad works in Steam and virtually every game supporting a 360 pad). I only quickly tried the Godot joystick demo, so maybe it's possible that the demo itself needs to be updated?

**Comment by punto-** [comment] 2016-01-01 23:42
Stem and all those games are on linux? Does it work on SDL on linux? also
does it work on godot on windows?

**Comment by adolson** [comment] 2016-01-02 00:17
You are asking me? I don't have Windows (since 2002), so I can't answer any questions about that. So yes, I have over 800 games installed on my machine. Here is the sdl2-jstest output showing my Nexus pad (which uses Xboxdrv and works with my gamepad-supported games on Steam, like Metro Last Light Redux, Rogue Legacy, GRID Autosport, Alien Isolation, Borderlands 2, Hammerwatch, just to name a few that come to mind):

```
dana@tenfoot:~/.bin/sdl-jstest$ ./sdl2-jstest --list
Found 1 joystick(s)

Joystick Name:     'Microsoft X-Box 360 pad'
Joystick GUID:     030000005e0400008e02000010010000
Joystick Number:    0
Number of Axes:     6
Number of Buttons: 11
Number of Hats:     1
Number of Balls:    0
GameController:
  Name:    'X360 Controller'
  Mapping: '030000005e0400008e02000010010000,X360 Controller,a:b0,b:b1,back:b6,dpdown:h0.4,dpleft:h0.8,dpright:h0.2,dpup:h0.1,guide:b8,leftshoulder:b4,leftstick:b9,lefttrigger:a2,leftx:a0,lefty:a1,rightshoulder:b5,rightstick:b10,righttrigger:a5,rightx:a3,righty:a4,start:b7,x:b2,y:b3,'
```

**Comment by punto-** [comment] 2016-01-02 00:32
Yes, I don't have this pad so I can only ask :) Ok, if it works with SDL it
should work with ours.. So this xbox driver masks the pad as an xbox pad
isted of "nexus"? We have the device with this guid in the code.. Are you
compiling with "libevdev" on linux?

**Comment by Hinsbart** [comment] 2016-01-02 02:05
Mhh, I can't test that particular controller but I just did some tests with xboxdrv and it's working fine for me.
I used the `--emulate-xpad` option, which I suppose you also did considering the jstest output.

Are other gamepads working for you?

**Comment by punto-** [comment] 2016-01-02 02:16
I'm only using the sony pads, the PS3 and PS4 are working on linux and
windows. The thing is, the libevdev is optional at the moment, if you don't
have the libraries (I think there was also libudev?), it'll compile the
engine without that code, and the joysticks don't work. You should make
sure you have a binary compiled with that.

**Comment by adolson** [comment] 2016-01-05 05:21
Yep, this was my fault. I did not have libevdev-dev and libudev-dev
installed. I installed those and recompiled, now Xboxdrv pads work fine, as
does my DualShock 3, and they both have the exact same button/axis
numberings. :D I will have to test all my other gamepads soon too, but
honestly, I only use a Steam Controller myself, nowadays.

**Comment by punto-** [comment] 2016-01-05 07:12
Yeah.. I think we should make those libraries as normal dependencies, not
optional. For windows it makes sense because we don't want to have to
distribute the dlls with the editor, and it's a pain to install them, but
on linux they're pretty easy to get, just add them to the apt-get command
on the wiki and make them mandatory like the rest of the stuff we detect
with pkg-config.

**Comment by akien-mga** [comment] 2016-01-05 07:24
Typically they should be opt-out like the other dependencies: add a "joystick" build option which defaults to "yes", and use it to trigger both the pkg-config check (which errors out if the libs are missing) and the related functionalities.

**Comment by punto-** [comment] 2016-01-05 07:30
I don't think there's an advantage to compiling without joystick support on
linux. It's not a lot of code, and it's only on the x11 build (not the
server), and it's not like those libraries are super hard to get. We can
just make them dependencies, and avoid these kind of errors.

**Comment by akien-mga** [comment] 2016-01-05 07:40
That's what I just said :) But if we support compiling without png support or without gdscript, why not support compiling without joystick support for the poor guys that run a crappy distro without those lib packaged? :) Adding another build parameter is not a big deal.

**Comment by akien-mga** [comment] 2016-01-05 07:42
To clarify, "opt-out" means that the average joe running ```scons p=x11``` will get an error if he doesn't have libedev/libevdev installed. It's only when checking ```scons --help``` and then running purposedly ```scons p=x11 joystick=no``` that they'll be able to build without joystick support if they really want to (and then they won't make bug reports about buggy joystick normally ;)).

**Comment by punto-** [comment] 2016-01-05 07:43
Oh sorry, I meant to say there *isn't* an advantage :p We support compiling
without all that stuff for many reasons, but those aren't external
dependencies, we include all that code in the tree.. There's no risk of
accidentally turning off support for something because you don't have the
library installed.

**Comment by punto-** [comment] 2016-01-05 07:45
Yeah, that'd be a good choice too, just throw an error if the library is
not present and make them specifically disable it.

**Comment by Hinsbart** [comment] 2016-01-05 15:04
Alright, will give this a shot in my next PR.
Also, are there any other platforms beside OSX that need work on gamepad support?
I think it'd be pretty easy for html5, as emscripten provides a nice api for that, but html export is broken right now so I can't check it out.
What about android? I only tested it very briefly a while ago and don't remember if there were any issues :P 

Another thing @adolson : Your SUTjoystick plugin is MIT licensed right? So I suppose I can use this nice little [image](https://gitlab.com/shine-upon-thee/joystick/blob/master/diagram.png) to update the joystick demo and give it a bit of visual feedback. I'd also use it for the new mapping demo.

**Comment by adolson** [comment] 2016-01-05 16:52
Yes, you can use SUTjoystick for whatever you want. Funny fact: it actually
started life as the joystick demo. :) I need to revisit it in light of
these changes, since a large chunk of it will be obsolete (though I will
still want some of the features I added).

I tested Android stuff before, and all of the gamepads are mapped
differently there, too, so it would be good to have a solution in place
there. If SDL doesn't have a mapping db for Android, I can help for
gamepads I have (Ouya, Nexus, Logitech F310, DualShock 3, Xbox 360
knockoff, 3dfx HammerheadFX, Rock Candy PS3 Wireless, and maybe more, I
forget). I have OTG adapters for the USB ones.

**Comment by Hinsbart** [comment] 2016-01-05 17:33
SDL uses a fixed mapping for android, just like we do atm.
I think I only ever tested it with one joystick that happened to send the correct events, so I assumed that's alright. But I guess we have to add android mappings ourselves then... I wonder why sdl doesn't do this.

Reading through some android docs, it shouldn't be hard to adapt the code to work with our remapping system. I'll set up my android toolchain. That will also adress #1839.

Regarding SUTjoystick: I'd appreciate an updated version of that since, apart from the remapping stuff, it's very useful for keeping track of which player owns which device, deadzone handling etc.
Things that we can't really do inside the engine cause every other game wants to do it a little differently. But still, many won't need their own sophisticated behaviour, so it's totally worth it to have this as a plugin ;)
Also I guess some of the new stuff like singletons will come in handy there ^^

**Comment by adolson** [comment] 2016-01-05 17:48
I'm not sure about SDL, but I did try to make SUTjoystick work for this on
Android, but the device name was not passed, so I had no way to distinguish
devices. I tried to investigate the Android code in Godot at the time but
it was above my skill level.

I haven't really done much gamedev for the past year, so I'm out of the
loop about what has been changed recently (and don't grasp your reference
to new singleton stuff). In any case, I think I may rename SUTjoystick to
SUTgamepad, which I should have called it from the start, and have that
pared down to the essential, non-mapping features. SUTjoystick can stay
exactly how it is currently, as it may still be useful for those on an
older stable branch of Godot. (I'm not 100% sure about the name change yet,
though it's always kinda bugged me).

**Comment by punto-** [comment] 2016-01-05 17:54
The Android API seems to imply that it does its own mapping, and I only
tested that code with the gear vr pad, and the nvidia shield, it worked
fine. But I guess Android is capable of connecting to any joystick that can
do usb or bluetooth, and SDL has some entries for android, so it makes
sense that they do remapping there..

I guess Apple TV can use joysticks too? I've no idea how well that works
tho. I might get one in the near future.

**Comment by Hinsbart** [comment] 2016-01-05 18:03
Ah right, now I see. sdl does indeed have remapping for android. But it only has one mapping inside the db, guess I overlooked that :P

**Comment by Hinsbart** [comment] 2016-01-08 15:59
Ok, I can't seem to find any android mapping on the internet beside the one mentioned above.
In this case, is it even worth it to aim for sdl2 compatibility on android?

**Comment by Hinsbart** [comment] 2016-01-22 16:31
Any thoughts about this? The code for android remapping has been sitting on my disk for a while now.
But it's not compatible with the (afaik nonexistent) sdl2 mapping strings, so I wasn't sure whether or not to publish it.

**Comment by punto-** [comment] 2016-01-22 18:10
what is the issue exactly? I remember there were some entries for Android
in the SDL remaps, if we can get the uuid for devices on android we should
be able to remap them?

**Comment by Hinsbart** [comment] 2016-02-22 11:07
Almost forgot about this.
@adolson : The android-remapping code has been merged. So if you could test it with your gamepads and supply mappings if needed, that'd be awesome :)

You can export [this project](https://github.com/Hinsbart/joystick-mapping) to android to test the pads and generate mappings.

**Comment by adolson** [comment] 2016-02-22 18:59
Cool, I will get on that ASAP!

**Comment by adolson** [comment] 2016-02-23 06:22
I'm trying to use this project, but it doesn't seem to work on Android.
After I try to map all the buttons on my Nexus pad, nothing is shoved into
the two mapping boxes for me to test by Applying them, and the diagram does
not light up at all when I activate any inputs at this point (it does prior
to beginning mapping, though the buttons are incorrect).

It works fine on my PC, though that doesn't help, obviously.

I will look a bit at the code and see if I can see what is going wrong, but
thought I'd mention it in case you had some ideas of what might be
happening. Oh yeah, I can't map the "back" or "start" buttons for this pad,
because it's a real Android gamepad, and those buttons seem to be
hard-coded to system functions (back and home). The big middle power button
does get picked up, however, so I think I will map it in place of "start"
if/when I can get the mapping tool to work correctly.

**Comment by adolson** [comment] 2016-02-23 07:10
Ignore that - I think I figured it out. I shouldn't be doing coding at 2am.
:\

One interesting thing is that trying to use this mapping app with the Ouya
controller just makes it crash. Every time. WTF, Ouya!?

Also, I discovered that I am not able to get my Wii Classic Controller to
work with Godot anymore. It did work in 1.1 when I was using my joystick
module stuff. I am not sure if it's an issue on my end or if it's something
to do with the newer joystick code in 2.0.

**Comment by Hinsbart** [comment] 2016-02-23 10:29
Aww, that sounds.. bad :P
Can you post the output of `adb logcat` when it crashes with the ouya pad?

**Comment by adolson** [comment] 2016-02-23 17:29
I'll need time to learn how to use adb... I am not using it to get the Android mappings (I just added a feature to the tool that submits it to a PHP script via the browser, so I can just submit a bunch and then get them from a txt file later... This was easier, somehow, than taking a minute to research adb... lol).

**Comment by w84death** [comment] 2016-02-23 17:36
I just test OUYA and Xbox360 (wireless) on my Arch 32bit linux and Godot 2.0 stable.

What worked:

- thumb pads
- thumbs buttons (only 360)
- A/B/X/Y buttons
- LB/RB
- LT/RT (only on 360)

What not:
basically the dpad - its working but both pads have wrong mappings and whats worse on each gamepad they are totally different

**Comment by Hinsbart** [comment] 2016-02-23 17:45
@w84death oh wow, that sounds strange.. The wireless x360 is working flawlessly on my systems (arch and manjaro, 64bit, tested on kernels 3.18, 4.2, 4.3 and 4.4).

Could you try making a working mapping for your pad with [this](https://github.com/Hinsbart/joystick-mapping)? Maybe it'll give me a clue on what's happening.

**Comment by Hinsbart** [comment] 2016-02-23 17:48
@adolson it's not that hard ^^ 
just connect the device via usb and enable developer mode.
Then a simple `adb logcat` will print out everything that's happening on the hardware.
Basically, that's as far as I got into adb :P

**Comment by w84death** [comment] 2016-02-23 17:56
@Hinsbart I run the project and dont know what shoudl I do?
The app quits (or crash without error) when I press "start mappping".
All other buttons are disabled. I click (mouse) on inputs but nothing changes.

dpad has wrong mappings (exacly the same as official gamepad sample).

**Comment by adolson** [comment] 2016-02-23 20:13
@Hinsbart - I only have one USB port on my Android devices though, so I
won't be able to hook up a controller AND my computer to use adb at the
same time... That's fine to debug the OUYA pad crash, though.

**Comment by Hinsbart** [comment] 2016-02-23 20:27
@adolson allright ^^

@w84death ok, your ouya pad seems to be a different revision than the ones that are already in our db (it's guid is a bit different, but also the mapping). 

Could you please try to add the following line to `_ready()` on either the joystick demo or joystick-mapping and see if the mapping's ok:

`Input.add_joy_mapping("05000000362800000100000003010000,OUYA Game Controller,leftx:a0,lefty:a1,dpdown:b9,rightstick:b7,rightshoulder:b5,rightx:a3,start:b16,righty:a4,dpleft:b10,lefttrigger:b12,x:b1,dpup:b8,back:b14,leftstick:b6,leftshoulder:b4,y:b2,a:b0,dpright:b11,righttrigger:b13,b:b3,")` 

If it doesn't work, I'll add your mapping to the db.
Thanks :)

**Comment by w84death** [comment] 2016-02-23 21:29
You have error in the code. It took me a wile to realize that there shouidl be "true" as the second parameter ;)

No, this do not worked. So this is my OUYA code that **is working**:
`Input.add_joy_mapping("05000000362800000100000004010000,OUYA Game Controller,leftx:a0,lefty:a1,dpdown:b9,rightstick:b7,rightshoulder:b5,rightx:a3,righty:a4,dpleft:b10,lefttrigger:a2,x:b1,dpup:b8,leftstick:b6,leftshoulder:b4,y:b2,a:b0,dpright:b11,righttrigger:a5,b:b3,", true)`

I will use it for our game for now :) but it will be nice to have it in the db. Thanks!

**Comment by Hinsbart** [comment] 2016-02-23 22:10
oops, pasted the wrong guid, sorry. But your new mappings seems to be ok

**Comment by adolson** [comment] 2016-02-24 05:46
OK. the Ouya pad doesn't crash my Nexus tablet, just my Moto E phone. But I
can't map it or my other Bluetooth pad, the ASUS Nexus... The triggers or
other inputs seem to dismiss Godot and swap back to the desktop, but ONLY
in Godot... If I open Gmail or something, those inputs don't go back to the
desktop. Weird. I thought it might be the InputMapper stuff, so I cleared
it all out and that solved a few problems with wired gamepads, but not the
Bluetooth pads. Also, a lot of the gamepads' back buttons don't work, as
they trigger the Android back button functionality.

In any case, I managed to map a few things and submitted a PR.

**Comment by czlowiekimadlo** [comment] 2016-02-24 08:51
@Hinsbart I have the xbox 360 pad that i have borrowed to @w84death for his tests
My test made on Ubuntu 14.04, that never had a pad installed before:
- sudo apt-get install xboxdrv joystick
- downloaded Godot 2.0-stable with demos
- downloaded your mapping project

In the demo, all axis are working fine. All buttons are working fine except dpad, which does not work at all.
In your tool, defaults are working exactly the same as the demo. After using mapping funcionality, some controlls are messed up:
- button A is interpreded as dpad Right
- dpad Right is ok (on my other computer, dpad Right is interpreted as A though)
- dpad Up is ok
- dpad Left is interpreted as dpad Up
- dpad Down is interpreted as dpad Right
I have tried applying both a and b settings, but there is no difference.

This is the recorded mapping for b (dpad as buttons)
`030000005e0400001907000000010000,Xbox 360 Wireless Receiver,leftx:a0,lefty:a1,dpdown:b0,rightstick:b10,rightshoulder:b5,rightx:a3,start:b7,righty:a4,dpleft:b-1,lefttrigger:a2,x:b2,dpup:b-1,back:b6,leftstick:b9,leftshoulder:b4,y:b3,a:b0,dpright:b0,righttrigger:a5,b:b1,`

Godot is clearly not able to tell some buttons apart. Tested this pad with Joystick utility available for Ubuntu, and with http://html5gamepad.com/ both show dpad buttons as separate ones. Godot 1.1 also allowed me to map these buttons using JOY_BUTTON_[num] consts.

Also both projects are not mapping the xbox logo button, but that is fine I think.

**Comment by Hinsbart** [comment] 2016-02-24 11:15
@czlowiekimadlo seems like there were xpad driver changes in kernel 4.3, so for previous kernels this device sends a bit different events which are not properly handled currently.

But it's easy to fix... man had we just discovered this a few days earlier ^^

**Comment by czlowiekimadlo** [comment] 2016-02-24 11:57
@Hinsbart glad to hear it is fixable ;)

My bad, I knew about this issues for some time (since latest 2.0 beta I think), but was slacking with the report :( Sorry!

**Comment by Hinsbart** [comment] 2016-02-24 11:59
Well, no problem :P 
Should be fixed now in current master

**Comment by Hinsbart** [comment] 2016-02-24 12:34
@adolson mhh, that does indeed sound wierd. I'll try to get my hands on some other android devices to test this further, as my phone (sony z2) only supports the ps4 pad via bluetooth. All my other pads do nothing at all on this thing :/

**Comment by adolson** [comment] 2016-02-25 02:19
Do you have an OTG cable, or just Bluetooth? I am wondering why the Godot
apps close - it seems to be with any axis input on my two Bluetooth pads...
Very strange.

I have a PS3 pad but I am not sure if/how to connect it to my device. USB
OTG doesn't work, oddly (I was sure it had in the past...).

Anyhow, I got a few more mappings merged. I need to investigate the HTML5
stuff soon and try my pads there too.

**Comment by Hinsbart** [comment] 2016-02-25 11:29
I have an OTG cable, yes. But it doesn't work with my phone, at least with gamepads.
Either it doesn't have otg support (which I doubt, was a flagship model after all ^^) or sony locked it so you can only use the DS4 :/

**Comment by Krzycho666** [comment] 2016-02-27 21:50
I've checked some different pads on Windows 7x64 and Nvidia Shield tablet with android 5.1.1. Most of them were fine, but there were some problems:

On Windows:
- I couldn't map WiiMote controller - Godot didn't recognized it at all.

Android:
- Back button on some pads ( those one with better support - like XInput ones, and PS4 controller ) cosed the app close while mapping, so it was interrupted every single time
-  Logitech F310: not detected in Dinput, on XInput detected only when plugged right after unpluging other pad. When changing to Dinput and back to Xinput it stops being detected
- There was some problem with D-Pad after mapping on some pads . App was showing, that all the D-Pad buttons are pressed all the time.
- Unpluging pads while app was working cosed app crash a couple of time. I couldnt exactly find the problem.
- I also couldn't map joy-buttons and D-Pad up only ( wtf? ) button on some very old Green Asia ( Apollo GP-3020PC ) pad.

While Windows build seem to work flawlessly, the android version seem to be quite unstable and buggy afterall.

I did tried:
- OUYA pad
- PS4 pad ( both bluetooth and cable )
- XBOX one pad ( not detected by android )
- SpeedLink Torid ( both D/Xinput )
- Genesis P65 ( both D/Xinput )
- SpeedLink Xeox Pro ( both D/Xinput )
- Apollo GP-3020PC ( problems on android )
- WiiMote ( not detected by godot on Windows, can't get connected to android - common problem )
- Logitech F310 ( android problems as described ).

All dpads worked fine so as other buttons and axes.

How about detecting tilt? Like on PS pads and the one from Wii ?
Were are the new mappings storred? They weren't saved after the app closing.

It also funny, that device names are much better on Android then on Windows. It probably the driver stuff but I get super precise commercial names on Android while getting some generic, universal ones on Windows for same devices.

Since I'm going to update my Shield tablet to android v6 I'll make some test on it too. I can test it OSX in free time if you want.

PS. I've been using v2.0 stable for the tests.

**Comment by adolson** [comment] 2016-02-28 00:22
The problem with back buttons on controllers on Android is not a Godot
problem, it's built into Android that way. You will need to Skip the
buttons that cause issues like that. The mappings aren't stored anywhere.
You need to capture them with adb or edit the project some other way. I
forked it and changed it so it would submit them to my server, and then I
could get my mappings from my server instead. On Windows or Linux you can
just copy the mapping to your clipboard, for ease of adding to the Godot
source code.

**Comment by Krzycho666** [comment] 2016-02-28 12:03
Hmmm... So what will be the approach for updateding this db? Are we going to copy new pads from guys from SDL db manualy, every single time they make some updates and add ( manualy also ) our own bindings to the cpp file and then recompile the engine/templates? This doesn't seem to be a good idea to me :/ At least not for the players.
How about holding those bindings in seperate file ( like SDL db is holden ), to make it possible to update mappings on client site, by downloading it directly from github server and cheking if there are any new mappings on game start? It could be holden in some universal godot config directory, so it could be reused by other Godot apps.

**Comment by Hinsbart** [comment] 2016-02-28 15:54
You can already add mappings at runtime so your game can load them from a file.
I guess we could also look for this file in user:// and add that functionality in-engine.
But I don't think it would be a good idea to get it from github automatically. The community db is kinda flawed.. I don't trust it completely :P

About the android problems: I'm terribly sorry and will check it asap ^^

**Comment by Krzycho666** [comment] 2016-02-28 16:32
Haha... Don't be sorry =D I'm glad that it's 99% ready. It's a huge milestone to me in mobile/android game development.

**Comment by adolson** [comment] 2016-02-28 17:50
Godot picks up the SDL_GAMECONTROLLERCONFIG environment variable, just like
all the SDL2 games out there do. There's no need to have the player muck
around with source code and whatever.

**Comment by Krzycho666** [comment] 2016-02-28 20:11
Yes it does. But he can't save it ( for now at least ), so it's quite useless when it comes for ingame bidings. If it is about environment variables on windows it's always a problem, since windows needs to get restarted to get it work. Holding some local db seem to be a good idea - so as the SUTjoystick does. It should be engine's task, to keep them all in one place for all godot games - not the game's.
By the way. I've found a bug about the mapping. When godot gets a mapping from the environment variable he shows a name from a driver - not from the binding itself.

**Comment by Hinsbart** [comment] 2016-02-28 20:17
Well, ingame bindings are not handled by our gamepad-remapping system. Also, the env variable is set automatically by steam, which I guess is the most common way to launch games on PCs these days.

Lastly, the name thing is not a bug as we don't use the names from the mappings. They are just there so we humans know which hardware the different strings belong to.

**Comment by Krzycho666** [comment] 2016-02-28 20:29
It's funny, bacause steam doesn't set it up on my pc. Also steam is not the only one on the market. Many small games are disributed DRM-free, or on some other digital distubution places like GOG, Desura, HumbleStore or Indiegamestand.
When it comes to names, I think we should show the names from the mappings. I can imagine many situations ( especially with local multiplayer games ) when viewing the correnct device name is crusial - not something like "Generic USB Pad".

**Comment by Hinsbart** [comment] 2016-02-28 20:40
Local multiplayer games have used color to differentiate the players since, well forever ^^
I guess that would be the best practice as your game is safe for a console release this way.

But apart from that, it sounds reasonable. And it's also true that the mapping names are often more precise then the ones from the hardware. So taking the mapping names is fine by me ;)

**Comment by adolson** [comment] 2016-02-28 21:30
SUTjoystick is useless now, deprecated by the changes in 2.0. Please, don't
use it anymore. I started working on SUTgamepad, which will be compatible
with 2.0+, but it won't even touch mapping-related stuff so it's not
relevant to this discussion.

Maybe the function that returns the joystick name should return the name as
provided by the mapping, and if the pad is not mapped, then fall back to
the driver name?

**Comment by Hinsbart** [comment] 2016-02-28 21:49
Yep, that's what I was thinking.

**Comment by nunodonato** [comment] 2016-04-15 20:05
Hi all, 
I dont know if this is related or if I should open a new issue.
I have my gamepad working fine, using both dpad and left stick to control player movement.

Today I noticed that after exporting, the left stick doesnt work anymore. (values are correctly read, but it doesnt trigger the is_action_pressed). Tried in both windows and linux

**Comment by Hinsbart** [comment] 2016-04-22 12:50
@nunodonato I think it might be related to the binary engine.cfb that exported games use.
I've added some debug prints to `Globals::set` and made a small test project with actions defined for the left stick. Result:

editor:
```
input/up = axis 1, -1
input/down = axis 1, 1
input/left = axis 0, -1
input/right = axis 0, 1
```
exported:
```
input/up = axis 1, 0
input/down = axis 1, 0
input/left = axis 0, 0
input/right = axis 0, 0
```

The seconds value is the `InputEvent.joy_motion.axis_value` property that defines whether the action will be triggered on the positive or negative axis direction.
So, I guess it either isn't correctly set during the cfg->cfb conversion or it isn't read properly from that format.
Will let you know when I find out more.

Sample project:
[joy_export_bug.zip](https://github.com/godotengine/godot/files/231782/joy_export_bug.zip)

**Comment by akien-mga** [comment] 2016-04-22 12:53
> I dont know if this is related or if I should open a new issue.

Opening a new issue would be nice, this old issue has been used to discuss a thousand different things, it's becoming hard to read :)

**Comment by adolson** [comment] 2016-04-22 13:39
Yeah, I think this one should be closed. Gamepad support has been _immensely_ improved and most of the discussion is no longer relevant.

**Comment by Hinsbart** [comment] 2016-04-24 13:40
@nunodonato fixed by 4409, so no need for an issue ;)

And I agree that this one can be closed.

**Comment by akien-mga** [comment] 2016-04-24 13:51
Let's close then. Thanks everyone for the discussions and contributions for gamepad support :)

**Closed by akien-mga** 2016-04-24 13:51 UTC
Labels: confirmed, enhancement, topic:core
