### ISSUE TITLE
[Godot 4] Root Motion rig from Blender calculated wrong in Godot

### ISSUE THREAD

**Issue by TypeOverride** [godotengine/godot#77087] opened 2023-05-15 05:14 UTC
### Godot version

4.1.dev2

### System information

Windows 10

### Issue description

Root motion is not working proper in Godot when exporting a rig from Blender.

Furthermore it seems that the imported asset looks into the wrong direction in Godot.
Front view in Blender is showing the front of the character, while in Godot you see the back of the character.

(I think i know what the problem is now - the rotation of the root bone. So maybe it goes into a proposal here - to get an option in Godot for determine the axis or orientation for correcting the caluclation?)

### Steps to reproduce

Create in Blender a character with a root motion rig
Import it to Godot (gltf)
Create a Node3D scene with a AnimationTree and setted root motion to the root bone
Create a RootMotionView and set the animationPath to AnimationTree

### Minimal reproduction project

[https://www.youtube.com/watch?v=t_2i6Sv_On4](url)

**Comment by TokageItLab** [comment] 2023-05-16 22:57
Dupe of https://github.com/godotengine/godot/issues/75228. See also https://github.com/godotengine/godot/pull/76052.

**Closed by TokageItLab** 2023-05-16 22:57 UTC
Labels: needs testing, topic:import, topic:animation, topic:3d
