### ISSUE TITLE
extremal cpu usage, when model have bones

### ISSUE THREAD

**Issue by v0van1981** [godotengine/godot#1034] opened 2014-12-23 07:46 UTC
model have no bones - 1% cpu usage
add bone to model (without animation) - 100% cpu usage

(when exported from bleder)

**Comment by akien-mga** [comment] 2015-11-05 09:41
I believed this is also something @slapin has been looking into recently?

**Comment by slapin** [comment] 2015-11-05 14:06
Even though I can confirm that skeletal transform consume more CPU than
expected even comparing to
different engines (especially seen on android/ARMv7, as any skeleton mesh
reduces frame rate up to 10x),
I have no idea yet where the problem is. Farther research is needed to
optimize this routine.

**Comment by akien-mga** [comment] 2016-03-24 10:04
@reduz wrote:
> skeletal transform is running on CPU right now, will be reverted back to
GPU shortly (unless blend shapes are used)

What's the status on this?

**Comment by slapin** [comment] 2016-03-25 18:26
There are bugs in some common cases, need to investigate farther to report
something. At least the case of multiple material planes + morph target,
and some variations around this produce distorted output.

**Comment by reduz** [comment] 2017-08-04 15:54
Godot 3.0 now fully uses GPU for everything from bones to blend shapes, so closing this issue..

**Closed by reduz** 2017-08-04 15:54 UTC
Labels: bug, topic:core
