### ISSUE TITLE
Can't change the flags from GradientTexture

### ISSUE THREAD

**Issue by ghsoares** [godotengine/godot#41693] opened 2020-09-02 00:22 UTC
**Godot version:**

v3.2.3.beta1.mono.official

**OS/device including version:**

Windows 10

**Issue description:**

I'm trying to create a repeatable GradientTexture, but the flags from it can't be changed. If this is or not a desired behaviour, I think this could be able to be changed. Note that if I try to change, the message "Set flags" is printed on output, but is not changed in resource.

**Steps to reproduce:**
1. In an Sprite node, insert a GradientTexture as texture variable;
2. In the GradientTexture flags, try to change any flag.

**Comment by KoBeWi** [comment] 2020-09-02 01:43
Duplicate of #18388

**Closed by KoBeWi** 2020-09-02 01:43 UTC
