### ISSUE TITLE
Scaled 3D Models causes light issues

### ISSUE THREAD

**Issue by nonunknown** [godotengine/godot#37797] opened 2020-04-11 11:46 UTC
**Godot version:**
3.2 mono
**OS/device including version:**
ubuntu 19.10
**Issue description:**
If you scale a model from for example: 1 to -1, the light does not reflect as spected:
![bug](https://user-images.githubusercontent.com/58845030/79042666-083f4680-7bd0-11ea-90bc-3adac59b6341.gif)

**Steps to reproduce:**

* create a spotlight
* place 3d model
* scale model's Z to -1
* light will be shown as the gif

**Minimal reproduction project:**
[mrp.zip](https://github.com/godotengine/godot/files/4464531/mrp.zip)

**Workarounds**
The workaround for the moment is creating animations for the model scaled inside the modeling software. (if you have 10 animations, create another 10 scaled -1?)

Related to #26710 but the issue is from **Mar 6, 2019** 
Related to #20599 from far back in time **Jul 30,2018**

**Comment by Zireael07** [comment] 2020-04-11 12:13
duplicate of #29317

**Comment by Calinou** [comment] 2020-04-11 12:20
Duplicate of #29317 indeed.

**Closed by Calinou** 2020-04-11 12:20 UTC
