### ISSUE TITLE
timer gets delayed when wait_time is under 0.2 seconds

### ISSUE THREAD

**Issue by rezgi** [godotengine/godot#33247] opened 2019-11-01 20:22 UTC
**Godot version:**
3.2 alpha-3

**OS/device including version:**
OSX Sierra

**Issue description:**
I'm making a metronome and I noticed that over 150bpm, eigth notes (0,19s duration) get delayed and not regular. Checked the numbers many times and they're fine, to me it seems like the engine doesn't follow through when playing a short metronome sound.

**Steps to reproduce:**
```
func _ready():
    $timer.wait_time = 0.19
    $timer.start()

on_timer_timeout():
    $metronomeSound.play()
    $timer.start()
```

**Minimal reproduction project:**
project with one scene and a small sound (0,2s) to check the regularity of the timer.

**Comment by Calinou** [comment] 2019-11-01 20:54
Posible duplicate of #32382?

**Comment by rezgi** [comment] 2019-11-02 12:24
Went through the whole discussion in #32383 and yup it seems like the same issue. Do you have any tip for finding these similar issues ? I searched before issuing this bug and didn't find this. Thanks ! Should I close this issue ?

**Comment by Chaosus** [comment] 2019-11-02 12:41
>  Should I close this issue ?

Yes, duplicates should be closed.

**Closed by Chaosus** 2019-11-02 12:41 UTC
