### ISSUE TITLE
Internal Script Error! opcode #38 (report please).

### ISSUE THREAD

**Issue by telaviv** [godotengine/godot#33438] opened 2019-11-08 07:35 UTC
**Godot version:**
3.1.1

**OS/device including version:**
Linux/x86_64

**Issue description:**
Running a script gives me the following error:

```
Internal Script Error! opcode #38 (report please).
```

**Steps to reproduce:**
You can run the following sets of scripts

```
# res://main.gd
extends Sprite

func _ready():
	var Bar = preload('res://bar.gd').Bar
	Bar.new()
```

```
# res://bar.gd
class Foo:

	func _init():
		pass
		
class Bar:
	var pos = Foo.new()

	func _init():
		pass
```

**Comment by qarmin** [comment] 2019-11-08 09:49
Confirm on Ubuntu 19.04 Godot 3.2 Beta 1
Minimal project - [import.zip](https://github.com/godotengine/godot/files/3823948/import.zip)

**Comment by bojidar-bg** [comment] 2019-11-08 14:30
This is a duplicate of #24786, which is in turn a duplicate of #5843. This might potentially be resolved when the circular reference problems with scripts are.

**Closed by bojidar-bg** 2019-11-08 14:30 UTC
Labels: bug, topic:gdscript
