### ISSUE TITLE
Raycast array

### ISSUE THREAD

**Issue by pro100taA** [godotengine/godot#7358] opened 2016-12-23 12:08 UTC
**Operating system or device - Godot version:**
Ubuntu 16.04 - Godot 2.1
**Issue description** (what happened, and what was expected):
However I also realize that the results of intersect_shape() don't contain the position of the intersections, so I used hit.collider.get_pos(), which is less precise but should at least order the objects.

I get the output array that is sorted by id.
I need to get in the order in which they enter the ray.

**Comment by bojidar-bg** [comment] 2017-03-24 19:28
@pro100taA I don't really think that `intersect_shape` should in any way care about the shape type, unless it starts caring about the intersection positions. The problem with intersection positions is that you can have multiple of them, which raises the question of which should be kept....

So far, I think that for this (poorly-described) usecase, there are two things that might be done:
1. Make `intersect_shape` return intersection pos, and probably sort intersections by distance to shape_transform's origin.
2. Make `intersect_ray_multiple`, which would just keep intersecting with the raycast, even after the first hit.
3. (Keep things as-is, we can fake `intersect_ray_multiple` using the current `intersect_ray` already.)

Which one do you this is better for Godot and gamedev? :smiley:

**Comment by Noshyaar** [comment] 2018-04-10 15:58
First of all thank you for your report and sorry for the delay.

We released Godot 3.0 in January 2018 after 18 months of work, fixing many old issues either directly, or by obsoleting/replacing the features they were referring to.

We still have hundreds of issues whose relevance/reproducibility needs to be checked against the [current stable version](https://godotengine.org/download), and that's where you can help us.
**Could you check if the issue that you described initially is still relevant/reproducible in Godot 3.0 or any newer version, and comment about it here?**

For bug reports, please also make sure that the issue contains detailed steps to reproduce the bug and, if possible, a zipped project that can be used to reproduce it right away. This greatly speeds up debugging and bugfixing tasks for our contributors.

Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

Thanks in advance.

*Note: This message is being copy-pasted to many "stale" issues (90+ days without activity). It might happen that it is not meaningful for this specific issue or appears oblivious of the issue's context, if so please comment to notify the Bugsquad about it.*

**Comment by bojidar-bg** [comment] 2018-04-10 16:09
Still relevant in 3.0, there is still no builtin way to get multiple intersection with a ray in 2D or 3D.

**Comment by akien-mga** [comment] 2019-04-15 14:18
The issue does not properly describe what the use case is and what should actually be implemented, so it's a bit difficult for any contributor to work on it (and first of all to find it given its unclear title).

As such I'll close it, if the intended use case is still not covered in 3.1, I would advise to open a new issue with a clearer description.

**Closed by akien-mga** 2019-04-15 14:18 UTC
Labels: discussion, topic:physics
