### ISSUE TITLE
Radial gradient converted to linear gradient when using get_image()

### ISSUE THREAD

**Issue by 01271** [godotengine/godot#80837] opened 2023-08-21 03:04 UTC
### Godot version

4.1.1

### System information

Godot v4.1.1.stable - Windows 10.0.22621 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3080 (NVIDIA; 31.0.15.3168) - AMD Ryzen 7 7800X3D 8-Core Processor (16 Threads)

### Issue description

Using get_image on a radial GradientTexture2D returns a linear gradient instead of a radial gradient.
![image](https://github.com/godotengine/godot/assets/3951049/ce4b509a-6f7c-42f0-aa64-f6da89f9fd62)
This image illustrates the same gradient in two places. The one on the left has been converted using get_image() and the one on the right uses the same texture but has not been converted.

### Steps to reproduce

Create 2d radial gradient, turn into image texture, draw image texture.

### Minimal reproduction project

[GradientDemo.zip](https://github.com/godotengine/godot/files/12391019/GradientDemo.zip)

**Comment by 01271** [comment] 2023-08-21 03:05
This issue is present on all 3 renderers. Forward, mobile, compatibility.

**Comment by kleonc** [comment] 2023-08-21 11:59
Duplicate of #66627 (when `get_image` is called GradientTexture2D has not yet been generated/updated its texture as it is deferred).

A workaround is to call `get_image` also in a deferred manner (e.g. after awaiting `SceneTree.process_frame` signal).

**Closed by kleonc** 2023-08-21 11:59 UTC
