### ISSUE TITLE
Mono exported variables don't show up in the properties panel

### ISSUE THREAD

**Issue by ghost** [godotengine/godot#11955] opened 2017-10-08 23:07 UTC
Mono exported variables don't show up in the properties panel.
Attached an example project.

[monoexport.zip](https://github.com/godotengine/godot/files/1367277/monoexport.zip)

**Comment by neikeq** [comment] 2017-10-08 23:19
Does it still happen after ff28569? Also you must build the project manually for now (for the Tools configuration)...

**Comment by tagcup** [comment] 2017-10-08 23:20
Yes, I tested the attached project with current master

**Comment by tagcup** [comment] 2017-10-08 23:26
> Also you must build the project manually for now (for the Tools configuration)...

I guess I don't know what this means. Do you mean something like running the C# compiler manually?

**Comment by neikeq** [comment] 2017-10-08 23:51
@tagcup Yes, either MSBuild with `/p:Configuration=Tools` or from an IDE (making sure you select the `Tools` config). Also, right now it only check for reloading on wm focus.

All of those things need to be polished (automatic building on background for the editor, watching for assembly file modifications, etc), but I've been focused on other bugs and usability improvements...

**Comment by tagcup** [comment] 2017-10-08 23:59
Sure, sounds good.

Although there's a related bug here too; when I run msbuild, I do see them added in the properties panel as script variables, but I can't set an image for the exported Texture variable in the panel. It just shows <null> and clicking on it has no effect.

**Comment by neikeq** [comment] 2017-11-17 23:07
BTW, you can now build from the editor with the "Build Project" button in the bottom panel. Automatic background builds will come soon.

**Comment by akien-mga** [comment] 2018-01-05 15:38
Closing as duplicate of #12518 (AFAIU).

**Closed by akien-mga** 2018-01-05 15:38 UTC
Labels: bug, topic:mono
