### ISSUE TITLE
Double quotes at end of autocompleted strings

### ISSUE THREAD

**Issue by WolfgangSenff** [godotengine/godot#70692] opened 2022-12-29 02:36 UTC
### Godot version

4.0beta10

### System information

Windows 11

### Issue description

Whenever I hit enter to autocomplete a string in the script editor, it includes the first quote, then two quotes at the end of it - seems like maybe a template got messed up or something? Tough to say. It's happening everywhere I've tried to do autocompletion on strings, though. This does not appear to be project-specific. I looked through as many issues as I could find pertaining to this stuff but didn't see an exact match - apologies if this ends up as a dupe.

### Steps to reproduce

1. Autocomplete a string for (say) get_tree().change_scene_to_file(). Note that whatever autocompleted string you put into the parentheses will have the triple quote (one beginning, two end) problem.

### Minimal reproduction project

N/A, but here's a video showing it:

https://user-images.githubusercontent.com/148612/209895938-21f7fc35-9b65-4350-89ec-76152c954a9b.mp4

**Comment by matt08-prog** [comment] 2022-12-29 06:55
I had this same problem today so I had a look around. This is a duplicate of #70535. I also believe this bug was caused by #70297.

**Comment by Chaosus** [comment] 2022-12-29 09:08
Duplicate of https://github.com/godotengine/godot/issues/70535

**Closed by Chaosus** 2022-12-29 09:08 UTC
Labels: bug, confirmed, topic:gui

**Comment by WolfgangSenff** [comment] 2022-12-29 19:11
@matt08-prog - ahh, thanks! Good find. I don't know how I missed that.
