### ISSUE TITLE
When stretch-mode set to viewport all viewports pos are set to (0,0)

### ISSUE THREAD

**Issue by jtaart** [godotengine/godot#6537] opened 2016-09-18 18:19 UTC
Godot version: 
A windows 64-bit build (September 15, 2016 at 09:28) form [http://fixnum.org/godot/](http://fixnum.org/godot/)

Issue description:
I was testing out the new split-screen 2d viewport stuff with the demo. The only problem I could find with it was, when displays stretch mode is set to viewport. All the viewport's positions are set to (0,0) automatically. So, basically all the viewports just stack on top of each other in the left corner.

Steps to reproduce:

[https://youtu.be/7JPq4hGbbRY](https://youtu.be/7JPq4hGbbRY)

**Comment by mprasil** [comment] 2017-09-25 21:06
This seems to be duplicate of #7066

**Comment by bojidar-bg** [comment] 2017-09-26 12:51
Indeed, this is a duplicate of #7066.

**Closed by bojidar-bg** 2017-09-26 12:51 UTC
Labels: bug, topic:core, topic:rendering
