### ISSUE TITLE
CSG with collision is not baked in NavigationRegion3D with "Static Colliders" as geometry type

### ISSUE THREAD

**Issue by Wiggan** [godotengine/godot#81027] opened 2023-08-26 22:11 UTC
### Godot version

4.1.stable

### System information

Windows10, AMD Ryzen 9 5900X, NVIDIA GeForce RTX 3060 Ti, driver version 30.0.15.1179, compatibility.

### Issue description

When having a CSG based environment, navigation region 3d cannot use static colliders as geometry type. This limits the use of CSG I think.
I would love to be able to have CSGs with different collision layers and some to be baked into the nav region and others not.

### Steps to reproduce

1. Add a NavigationRegion3D to a scene
2. Add a CSG box of 5, 1, 5m, enable collision
3. Bake the nav region with geometry type set to static colliders
4. See that nothing was baked.

### Minimal reproduction project

Trivial to reproduce

**Comment by Calinou** [comment] 2023-08-26 22:15
StaticBodies and their collision shapes for CSG nodes are created using low-level PhysicsServer functions as opposed to StaticBody/CollisionShape nodes: https://github.com/DarioSamo/godot/blob/e3c4fa2455dc8c42da4c7485d48d5af50a76cdfe/modules/csg/csg_shape.cpp#L35-L64

This likely impacts the navigation bake step if it doesn't look for those PhysicsServer-created bodies/shapes.

**Comment by smix8** [comment] 2023-08-27 02:51
Duplicate of https://github.com/godotengine/godot/issues/79843 already fixed in master with https://github.com/godotengine/godot/pull/79643.

When parsing static colliders it now checks both the csg use_collision property and if there is a match with the csg collision_layers.

**Closed by smix8** 2023-08-27 02:51 UTC
Labels: bug, topic:core, topic:navigation, topic:3d
