### ISSUE TITLE
Top part of application hidden by the window title bar

### ISSUE THREAD

**Issue by MRFaria** [godotengine/godot#9601] opened 2017-07-11 10:39 UTC
**Operating system or device - Godot version:**
Dell XPS - WIndows 10
Steam version of Godot

**Issue description:**
Since this morning Godot starts with this issue where the menu bar, run button and other things are hidden by the application/window title bar. My resolution is 1920x1080

**Link to minimal example project:**

**Comment by eon-s** [comment] 2017-07-11 11:27
If the graphics card is Intel, this may be duplicate of #8902

**Comment by MRFaria** [comment] 2017-07-11 11:38
Ah sorry, didn't see that. In fact it is the same graphics card

**Comment by akien-mga** [comment] 2017-07-11 11:44
Closing as duplicate of #8902 then. Sounds like Intel released buggy drivers on Windows 10...

**Closed by akien-mga** 2017-07-11 11:44 UTC
