### ISSUE TITLE
Voxel GI don't work with SpotLight3D

### ISSUE THREAD

**Issue by chena1982** [godotengine/godot#81961] opened 2023-09-20 06:48 UTC
### Godot version

4.1.1 stable mono win64

### System information

win10 forward+

### Issue description

Voxel GI don't work with SpotLight3D

turn on voxel gi, emissive box get gi effect, it prove voxel gi settings is correct, but the spotlight3d don't get gi effect.

![image](https://github.com/godotengine/godot/assets/5953033/b8b2f11f-0a43-44b2-8983-0950e7f007ec)

turn off voxel gi , emissive box don't get gi effect now
![image](https://github.com/godotengine/godot/assets/5953033/e578824b-1b7e-41cd-835c-45e7f946e855)

### Steps to reproduce

1. create worldenvironment, set background to custom color, and color to black.
2. create directlight3d, set energy to 0, so the scene is black now.
3. create some csg box.
4. create spotlight3d to light the scene.
5. create voxel gi node and bake.
6. the spotlight3d don't get gi effect.

### Minimal reproduction project

N/A

**Comment by bitsawer** [comment] 2023-09-20 14:02
Thanks for the report, looks like a duplicate of https://github.com/godotengine/godot/issues/57754 or https://github.com/godotengine/godot/issues/38020. If you think this is a new issue, feel free to comment or re-open the issue. Howeve, in that case please also provide a test project so we can compare them.

**Closed by bitsawer** 2023-09-20 14:02 UTC
