### ISSUE TITLE
Tile Set Editor tabs in Godot 4 are very tiny in 4K / Full HD screens (changing display scale does not work)

### ISSUE THREAD

**Issue by knadoor** [godotengine/godot#48612] opened 2021-05-10 14:04 UTC
**Godot version:**
Godot 4.0 latest build as at 11/5/2021 (Non-Mono)

**OS/device including version:**
Windows 10.

**Issue description:**
When in the Tileset Editor in Godot 4, the Tiles and Terrains tabs are super small on 4K screens and Full HD resolutions.
![image](https://user-images.githubusercontent.com/8476589/117671568-47353680-b1ec-11eb-9466-195c78858bd5.png)

**Steps to reproduce:**
1) Add a Tile Map Load and create a Tile Set to open the editor
2) Observe the Tiles and Terrain tab being super small (including the text).

**Minimal reproduction project:**
N/A

**Comment by Calinou** [comment] 2021-05-10 15:13
It looks like the font isn't defined correctly for the tab name titles. This kind of font propagation issue has became quite common in `master` due to the TextServer refactoring.

**Comment by KoBeWi** [comment] 2022-06-02 00:18
Can't reproduce in newest alpha.
![image](https://user-images.githubusercontent.com/2223172/171522183-3c3025b5-c9e4-4683-8faf-847cfbe0d1dd.png)
@knadoor Can you confirm if this is resolved?

**Comment by groud** [comment] 2023-01-13 16:05
I'll close this issue. We hadn't have any other report about this and the last comment here makes it seem like it has been solved already. If anyone is still experiencing this issue please comment here, I'll reopen it.

**Closed by groud** 2023-01-13 16:05 UTC
Labels: bug, topic:editor, regression
