### ISSUE TITLE
Multiple Godot icons appear in macOS dock until editor is reloaded

### ISSUE THREAD

**Issue by CenTdemeern1** [godotengine/godot#77736] opened 2023-06-01 15:48 UTC
### Godot version

v4.0.2.stable.official [7a0977ce2]

### System information

Apple Mac mini M2 running macOS Ventura 13.4 (22F66)

### Issue description

I have placed Godot 4 in my dock. However, when I open a project, it always shows a new duplicate icon in the recents section of the dock. This duplicate isn't used anymore when the editor is reloaded however and the original pinned icon is used instead.

https://github.com/godotengine/godot/assets/24682280/26d56de0-52b8-4fc6-896f-879b9d69de53

Note that, in the video, the icon to the left of the Godot 4 icon I used to start the engine is a Godot 3 icon and not another duplicate of Godot 4:
![image](https://github.com/godotengine/godot/assets/24682280/19928922-7d49-4e54-bee3-3908998ec469)

### Steps to reproduce

- Pin Godot to your dock
- Open it, and launch a project
- (The issue should be visible)
- Reload the project
- (The issue should have disappeared)

### Minimal reproduction project

N/A

**Comment by Calinou** [comment] 2023-06-01 15:51
- Duplicate of https://github.com/godotengine/godot/issues/60339 (same cause).

**Closed by Calinou** 2023-06-01 15:51 UTC

**Comment by CenTdemeern1** [comment] 2023-06-01 15:53
Apologies, seems like my search for duplicates wasn't thorough enough

**Comment by akien-mga** [comment] 2023-06-01 15:56
No worry! Identifying duplicates is pretty difficult, it's part of the normal process that engine maintainers often have to locate them.
