### ISSUE TITLE
"Quit to project list" sometimes triggers playing the project instead of showing the project list

### ISSUE THREAD

**Issue by wangjeifei1** [godotengine/godot#2321] opened 2015-07-31 01:49 UTC
While using "quit to project list" in the scene menu,sometimes It will cause play the project.It only happens in godot x64.

**Comment by leezh** [comment] 2015-08-04 10:27
I can't reproduce this bug. Could you give more details about it? Which platform (Windows/Linux) are you using it on?

**Comment by akien-mga** [comment] 2015-11-10 15:36
Hey, me too, I found "a bug"!
![cat release day](https://cloud.githubusercontent.com/assets/4701338/11066565/10faebd0-87c9-11e5-835f-291b6f37feda.jpeg)
Please use a more descriptive title next time though, an issue title should tell at a glance what the issue is about.

**Comment by akien-mga** [comment] 2015-11-10 15:44
I never experienced this issue, but the only explanation that I could see for such a bug would be if the editor was run from within a project directory with engine.cfg with e.g. ```godot -e```. Then maybe "Quit to project list" just runs a plain "godot" and expects it to show the project list, but it actually runs the game. I'll experiment a bit.

**Comment by akien-mga** [comment] 2015-11-10 21:59
Can't reproduce either in the current master branch. Will give it some days to see if we get more info from the initial reporter, if not I'll close it.

**Comment by reduz** [comment] 2015-12-31 22:32
I can't reproduce this either :( closing, maybe it was fixed by some other PR

**Closed by reduz** 2015-12-31 22:32 UTC
Labels: bug, topic:editor
