### ISSUE TITLE
keep Navigation with TileMap up to date

### ISSUE THREAD

**Issue by 0ttoman** [godotengine/godot#11077] opened 2017-09-08 22:32 UTC
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Linux 64 bit Fedora 26, Godot 2.1.4

**Issue description:**
Removing a Cell containing NavigationPolygonInstance from the TileMap should update the get_simple_path() function of the Navigation2D node in the same frame. It shouldn't return a path through the removed cell.

**Link to minimal example project:**
[nav.zip](https://github.com/godotengine/godot/files/1289255/nav.zip)

**Comment by 0ttoman** [comment] 2017-11-13 21:03
Bug is still existent in Godot 3 Alpha 2. Please add a Milestone
I recreated the project in the new alpha: 
[nav.zip](https://github.com/godotengine/godot/files/1468467/nav.zip)

**Comment by bojidar-bg** [comment] 2018-06-03 13:49
(should be) Fixed by #15909.

**Closed by bojidar-bg** 2018-06-03 13:49 UTC
Labels: bug, topic:core

**Comment by akien-mga** [comment] 2018-07-22 14:10
Note that #20352 made the update of quadrants deferred again, so this issue would technically still be valid. But it's not a bug, it's a design decision that quadrants update should be deferred, otherwise performance takes a great hit. You can call `update_dirty_quadrants()` manually after using `set_cell` if needed.
