### ISSUE TITLE
Compatibility's New Shadows doesn't appear when running the game

### ISSUE THREAD

**Issue by TKHDev21** [godotengine/godot#82856] opened 2023-10-05 14:51 UTC
### Godot version

v4.2.dev6.official [57a6813bb]

### System information

Godot v4.2.dev6 - Windows 10.0.19045 - GLES3 (Compatibility) - GeForce GT 630M () - Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz (4 Threads)

### Issue description

When i add shadows to my game, they appear in the editor as you can see here:

![image](https://github.com/godotengine/godot/assets/116759222/e07c5442-12fa-4a4c-a69a-04b66484f339)

In-game picture:

![image](https://github.com/godotengine/godot/assets/116759222/2757dded-f685-483b-a77f-2c06f72d0c00)

### Steps to reproduce

Head to the "CSP" scene, everything you need is there

### Minimal reproduction project

[CSP.zip](https://github.com/godotengine/godot/files/12819836/CSP.zip)

**Comment by lostminds** [comment] 2023-10-05 14:57
Looks like you don't have any lights in your scene and the editor is using the preview light, casting the shadows. You can toggle this off to see if it looks the same as when you run the game, or add the light to your scene if you want it in your game as well.

![Screenshot 2023-10-05 at 16 55 23](https://github.com/godotengine/godot/assets/17763524/a241c6ae-3113-4129-ad7d-1f53fa3cd636)

**Comment by bitsawer** [comment] 2023-10-05 16:03
Thanks for the report. Duplicate of https://github.com/godotengine/godot/issues/82503, so closing this to keep discussion in one place.

**Closed by bitsawer** 2023-10-05 16:03 UTC
