### ISSUE TITLE
I can't start Godot

### ISSUE THREAD

**Issue by ITomi78** [godotengine/godot#11912] opened 2017-10-07 14:07 UTC
Hello!

I have download Godot v1.0 and 2.1.4 for my Windows 10 operating system but I can't start it: flash a title screen and a kind of text screen on the background but these disappearing suddenly.
What is wrong?

**Comment by marcelofg55** [comment] 2017-10-07 14:57
Is there any error on the console? Does your GPU support OpenGL 2.1?

**Comment by ITomi78** [comment] 2017-10-07 16:14
I can't see the messages on the console, because it disappear too quickly.
My GPU is an AMD Radeon HD 7480D (on board VGA).

**Comment by Calinou** [comment] 2017-10-07 16:22
Try to start the Godot executable from a command prompt:

1. Open a command prompt in the folder where the Godot executable is located. You can do this by using <kbd>Shift + Right click</kbd> on an empty space (in the Explorer, or on the desktop), then choosing **Open command window here** or **Open PowerShell window here** (depending on your Windows version).
2. In the window that appeared, type the name of the Godot executable, which is `godot.windows.opt.tools.64.exe` for a 64-bit Windows executable, unless you renamed it. Note that you can complete names using `Tab`.
3. You should see messages from the command prompt (and it won't disappear when Godot closes). Copy the entire log and post it here, surrounding it with three backticks (```) for formatting.

**Comment by ITomi78** [comment] 2017-10-08 07:26
Thanks, Calinou!
I  got the following messages:
D:\progsetup\AndroidGM>Godot_v2.1.4-stable_win64
ERROR: No loader found for resource: res://jatekter
   At: core\io\resource_loader.cpp:210
ERROR: Failed loading scene: res://jatekter
   At: main\main.cpp:1409
ERROR: SpatialSoundServerSW::free: Attempt to free invalid ID
   At: servers\spatial_sound\spatial_sound_server_sw.cpp:598
ERROR: SpatialSound2DServerSW::free: Attempt to free invalid ID
   At: servers\spatial_sound_2d\spatial_sound_2d_server_sw.cpp:595
WARNING: ObjectDB::cleanup: ObjectDB Instances still exist!
     At: core\object.cpp:1845

**Comment by ITomi78** [comment] 2017-10-08 07:29
"jatekter" ("gamespace") is something ruin of my older game project.

**Comment by Zireael07** [comment] 2017-10-08 12:29
Do you have two Godot executables in the same folder?

**Comment by Noshyaar** [comment] 2017-10-08 14:26
Does that folder contain `engine.cfg`?

**Comment by ITomi78** [comment] 2017-10-09 13:30
Yes, that folder contains Godot v.2.1.4. and v.1.0 and **engine.cfg** too.

**Comment by Noshyaar** [comment] 2017-10-09 13:38
Godot will try to run the game instead if `engine.cfg` exists.

**Comment by marcelofg55** [comment] 2017-10-09 15:44
Maybe we could implemented a "--run" flag for Godot when compiled with tools support? To prevent users getting this kind of problems. That way if godot is compiled with tools support it will only run a project if executed with --run, and for the godot templates that don't have tools support the current behaviour is used.

**Comment by marcelofg55** [comment] 2017-10-09 17:46
@akien-mga @reduz What do you say about this "--run" idea?

**Comment by bojidar-bg** [comment] 2017-10-09 17:47
Duplicate of the closed #9020, which was marked duplicate of #7764.

**Closed by bojidar-bg** 2017-10-09 17:47 UTC
Labels: archived

**Comment by akien-mga** [comment] 2017-10-13 13:58
>  Edit: Nevermind this, just saw that there is a PR that fixes this issue.

Not that I know of. If you mean the one about upwards godot.project lookup, it doesn't change the fact that a godot.project file *in* the executable folder will make the project run.

> What do you say about this "--run" idea?

I thought about this already and mentioned it a couple times, but I'm not sure what's best as default behaviour. We already have `--editor` to force running the editor instead of the default behaviour of running the game, so if we implement `--run` we'd have to flip the default behaviour and drop `--editor`.

It all boils down to the question of which use case is the most widespread. It's not uncommon that beginners are surprised by the current default behaviour, but one past the initial surprise, I think many Godot users like that they can run the game directly without having to pass a switch.

There are pros and cons to both systems. The advantage of the current one is that the tools and non-tools binaries behave the same way: they run the project in their folder, if any. It makes sense that only the tools binary has the `--editor` switch, but would it make sense that the non-tools binary lacks the (for it, useless) `--run` that the editor would have?

**Comment by hello432369** [comment] 2023-07-22 06:35
<img width="480" alt="屏幕截图 2023-07-22 143410" src="https://github.com/godotengine/godot/assets/31066493/d1e2ac2b-4f5d-4a0d-a25f-e26f44187f81">

**Comment by AThousandShips** [comment] 2023-07-22 08:32
@hello432369 please don't comment on issues that have been closed for 6 years, this was closed as a duplicate in any case, no need to resurrect ancient issues
