### ISSUE TITLE
Rendering issues with intel HD5500 (config.rgtc_supported == false)

### ISSUE THREAD

**Issue by alejodiazg** [godotengine/godot#9970] opened 2017-07-29 17:02 UTC
**Operating system or device - Godot version:**
Windows 10
Intel HD Graphics 5500
Using the 3.0 alpha
Driver version 20.19.15.4549

**Issue description:**

There are some rendering issues with the new rendered

Rendering issues in supposed to be compatible device, has im not a rendering savy guy would like to help get more info, just need more guidance on how to debug the problem

Examples:
The cheesse looks terrible
![image](https://user-images.githubusercontent.com/5624658/28746542-b8d6764a-745c-11e7-819e-3eec448843ac.png)

The same error is visible in the bricks and the rocks

![image](https://user-images.githubusercontent.com/5624658/28746554-fe0cc30e-745c-11e7-85ba-5818c1a2173a.png)

Console output when godot starts

```
OpenGL ES 3.0 Renderer: Intel(R) HD Graphics 5500
WARNING: not found: rendering/quality/anisotropic_filter_level
WARNING: not found: rendering/quality/anisotropic_filter_level
GLES3: max ubo light: 409
GLES3: max ubo reflections: 455, ubo size: 144
WARNING: not found: locale/translation_remaps
EditorSettings::_get - Warning, not found: import/pvrtc_texture_tool
EditorSettings::_get - Warning, not found: import/pvrtc_texture_tool
```

Console output while the demo is running
```
ERROR: RasterizerSceneGLES3::environment_set_tonemap: Condition ' !env ' is true.
   At: drivers\gles3\rasterizer_scene_gles3.cpp:914
ERROR: RasterizerSceneGLES3::environment_set_adjustment: Condition ' !env ' is true.
   At: drivers\gles3\rasterizer_scene_gles3.cpp:929
ERROR: RID_Owner<struct RasterizerSceneGLES3::LightInstance>::getornull: Condition ' !id_map.has(p_rid.get_data()) ' is true. returned: 0
   At: c:\projects\godot-builds\godot\core\rid.h:164
ERROR: RasterizerSceneGLES3::shadow_atlas_set_size: Condition ' !li ' is true. Continuing..:
   At: drivers\gles3\rasterizer_scene_gles3.cpp:145
ERROR: RID_Owner<struct RasterizerSceneGLES3::LightInstance>::getornull: Condition ' !id_map.has(p_rid.get_data()) ' is true. returned: 0
   At: c:\projects\godot-builds\godot\core\rid.h:164
ERROR: RasterizerSceneGLES3::shadow_atlas_set_size: Condition ' !li ' is true. Continuing..:
   At: drivers\gles3\rasterizer_scene_gles3.cpp:145
ERROR: RID_Owner<struct RasterizerSceneGLES3::LightInstance>::getornull: Condition ' !id_map.has(p_rid.get_data()) ' is true. returned: 0
   At: c:\projects\godot-builds\godot\core\rid.h:164
ERROR: RasterizerSceneGLES3::shadow_atlas_set_size: Condition ' !li ' is true. Continuing..:
   At: drivers\gles3\rasterizer_scene_gles3.cpp:145
ERROR: RID_Owner<struct RasterizerSceneGLES3::LightInstance>::getornull: Condition ' !id_map.has(p_rid.get_data()) ' is true. returned: 0
   At: c:\projects\godot-builds\godot\core\rid.h:164
ERROR: RasterizerSceneGLES3::shadow_atlas_set_size: Condition ' !li ' is true. Continuing..:
   At: drivers\gles3\rasterizer_scene_gles3.cpp:145
ERROR: RID_Owner<struct RasterizerSceneGLES3::LightInstance>::getornull: Condition ' !id_map.has(p_rid.get_data()) ' is true. returned: 0
   At: c:\projects\godot-builds\godot\core\rid.h:164
ERROR: RasterizerSceneGLES3::shadow_atlas_set_size: Condition ' !li ' is true. Continuing..:
   At: drivers\gles3\rasterizer_scene_gles3.cpp:145
ERROR: RID_Owner<struct RasterizerSceneGLES3::LightInstance>::getornull: Condition ' !id_map.has(p_rid.get_data()) ' is true. returned: 0
   At: c:\projects\godot-builds\godot\core\rid.h:164
ERROR: RasterizerSceneGLES3::shadow_atlas_set_size: Condition ' !li ' is true. Continuing..:
   At: drivers\gles3\rasterizer_scene_gles3.cpp:145
ERROR: RID_Owner<struct RasterizerSceneGLES3::LightInstance>::getornull: Condition ' !id_map.has(p_rid.get_data()) ' is true. returned: 0
   At: c:\projects\godot-builds\godot\core\rid.h:164
ERROR: RasterizerSceneGLES3::shadow_atlas_set_size: Condition ' !li ' is true. Continuing..:
   At: drivers\gles3\rasterizer_scene_gles3.cpp:145
ERROR: RID_Owner<struct RasterizerSceneGLES3::LightInstance>::getornull: Condition ' !id_map.has(p_rid.get_data()) ' is true. returned: 0
   At: c:\projects\godot-builds\godot\core\rid.h:164
ERROR: RasterizerSceneGLES3::shadow_atlas_set_size: Condition ' !li ' is true. Continuing..:
   At: drivers\gles3\rasterizer_scene_gles3.cpp:145
ERROR: RID_Owner<struct RasterizerSceneGLES3::LightInstance>::getornull: Condition ' !id_map.has(p_rid.get_data()) ' is true. returned: 0
   At: c:\projects\godot-builds\godot\core\rid.h:164
ERROR: RasterizerSceneGLES3::shadow_atlas_set_size: Condition ' !li ' is true. Continuing..:
   At: drivers\gles3\rasterizer_scene_gles3.cpp:145
ERROR: RID_Owner<struct RasterizerSceneGLES3::LightInstance>::getornull: Condition ' !id_map.has(p_rid.get_data()) ' is true. returned: 0
   At: c:\projects\godot-builds\godot\core\rid.h:164
ERROR: RasterizerSceneGLES3::shadow_atlas_set_size: Condition ' !li ' is true. Continuing..:
   At: drivers\gles3\rasterizer_scene_gles3.cpp:145
ERROR: RID_Owner<struct RasterizerSceneGLES3::LightInstance>::getornull: Condition ' !id_map.has(p_rid.get_data()) ' is true. returned: 0
   At: c:\projects\godot-builds\godot\core\rid.h:164
ERROR: RasterizerSceneGLES3::shadow_atlas_set_size: Condition ' !li ' is true. Continuing..:
   At: drivers\gles3\rasterizer_scene_gles3.cpp:145
ERROR: RID_Owner<struct RasterizerSceneGLES3::LightInstance>::getornull: Condition ' !id_map.has(p_rid.get_data()) ' is true. returned: 0
   At: c:\projects\godot-builds\godot\core\rid.h:164
ERROR: RasterizerSceneGLES3::shadow_atlas_set_size: Condition ' !li ' is true. Continuing..:
   At: drivers\gles3\rasterizer_scene_gles3.cpp:145
ERROR: RID_Owner<struct RasterizerSceneGLES3::LightInstance>::getornull: Condition ' !id_map.has(p_rid.get_data()) ' is true. returned: 0
   At: c:\projects\godot-builds\godot\core\rid.h:164
ERROR: RasterizerSceneGLES3::shadow_atlas_set_size: Condition ' !li ' is true. Continuing..:
   At: drivers\gles3\rasterizer_scene_gles3.cpp:145

```

**Steps to reproduce:**
Run the material tester demo

** Note **
If u can help me debug a bit more would gladly provide more information

**Comment by bruvzg** [comment] 2017-07-29 19:40
Unlikely it is Intel HD 5500 specific issue. Cheese rendering on macOS (FirePro D300) is even worse.

![sc1](https://user-images.githubusercontent.com/7645683/28747665-30d1f5de-74ad-11e7-9999-72c06c67050a.png)

![sc2](https://user-images.githubusercontent.com/7645683/28747667-3c7c139c-74ad-11e7-9e48-49e2ad66620a.png)

**Comment by reduz** [comment] 2017-07-29 19:46
I think the problem is related to RGTC not being supported properly, do you
think you could research if the opengl drivers support:

GL_ARB_texture_compression_rgtc ?

**Comment by bruvzg** [comment] 2017-07-29 19:56
@reduz Supported in both Core and Compatibility profiles.

![sup](https://user-images.githubusercontent.com/7645683/28747827-c6295b2e-74b0-11e7-9c67-22b8520b1758.png)

**Comment by bruvzg** [comment] 2017-07-29 20:08
And its much better under Window 10 on the same machine, but without shadow
![sc3](https://user-images.githubusercontent.com/7645683/28747876-39621472-74b2-11e7-9c06-18cead1a836a.png)

**Comment by alejodiazg** [comment] 2017-07-30 04:26
@reduz Ill check, im away from that pc, the driver is a bit old tough.

**Comment by george-norton** [comment] 2017-08-01 20:13
Not really sure how related this is, but the rendering is much worse on my Intel HD Graphics 620 (Windows 10 build 1703, Graphics driver version 21.20.16.4590).

![cheese](https://user-images.githubusercontent.com/30636555/28844646-4403716c-76fd-11e7-9943-d3c31bb93782.png)
![ice](https://user-images.githubusercontent.com/30636555/28844649-440dba3c-76fd-11e7-9c7f-40ab2cc15307.png)
![plastic](https://user-images.githubusercontent.com/30636555/28844647-4408874c-76fd-11e7-906f-aed97da45f76.png)
![stones](https://user-images.githubusercontent.com/30636555/28844648-440dfe84-76fd-11e7-90f1-a6a130da770c.png)

Logs when Godot starts:
> DETECTED MONITORS: 1
> Activated GL 3.3 contextERROR: ProjectSettings::set_custom_property_info: Condition ' !props.has(p_prop) ' is true.
>    At: core\project_settings.cpp:841
> ERROR: ProjectSettings::set_custom_property_info: Condition ' !props.has(p_prop) ' is true.
>    At: core\project_settings.cpp:841
> OpenGL ES 3.0 Renderer: Intel(R) HD Graphics 620
> WARNING: not found: rendering/quality/anisotropic_filter_level
> WARNING: not found: rendering/quality/anisotropic_filter_level
> GLES3: max ubo light: 409
> GLES3: max ubo reflections: 455, ubo size: 144
> WARNING: not found: locale/translation_remaps
> EditorSettings::_get - Warning, not found: import/pvrtc_texture_tool
> EditorSettings::_get - Warning, not found: import/pvrtc_texture_tool

And when the application is run:

> OPENING: C:/Users/georg/Documents/src/godot-demo-projects/3d/material_testers (C:::Users::georg::Documents::src::godot-demo-projects::3d::material_testers)
> running cmdline: "C:\Program Files\Godot_v3.0-alpha1_win64.exe" "-path" "C:/Users/georg/Documents/src/godot-demo-projects/3d/material_testers"
> DETECTED MONITORS: 1
> Activated GL 3.3 contextERROR: ProjectSettings::set_custom_property_info: Condition ' !props.has(p_prop) ' is true.
>    At: core\project_settings.cpp:841
> ERROR: ProjectSettings::set_custom_property_info: Condition ' !props.has(p_prop) ' is true.
>    At: core\project_settings.cpp:841
> OpenGL ES 3.0 Renderer: Intel(R) HD Graphics 620
> WARNING: not found: rendering/quality/anisotropic_filter_level
> WARNING: not found: rendering/quality/anisotropic_filter_level
> GLES3: max ubo light: 409
> GLES3: max ubo reflections: 455, ubo size: 144
> WARNING: not found: locale/translation_remaps
> load external res: res://tester.gd
> load external res: res://schelde.hdr
> load external res: res://test_bed.scn
> load external res: res://godot_ball.mesh
> load external res: res://texture_wood.png
> load external res: res://texture_cheese_albedo.png
> load external res: res://texture_cheese_normal.png
> load external res: res://texture_cheese_ao.png
> load external res: res://texture_cheese_depth.png
> load external res: res://texture_rock_albedo.png
> load external res: res://texture_rock_metal.png
> load external res: res://texture_rock_normal.png
> load external res: res://texture_rock_ao.png
> load external res: res://texture_rock_depth.png
> load external res: res://texture_bricks.jpg
> load external res: res://texture_bricks_metal.jpg
> load external res: res://texture_bricks_normal.jpg
> load external res: res://texture_bricks_depth.jpg
> load external res: res://wool_albedo.png
> load external res: res://wool_normal.png
> load external res: res://wool_depth.png
> load external res: res://aluminium_albedo.png
> load external res: res://aluminium_normal.png
> load external res: res://marble_albedo.png
> load external res: res://sand_albedo.jpg
> load external res: res://sand_metal.jpg
> load external res: res://sand_rough.jpg
> load external res: res://sand_normal.jpg
> load external res: res://rock_albedo.jpg
> load external res: res://rock_rough.jpg
> load external res: res://rock_metal.jpg
> load external res: res://rock_ao.jpg
> ERROR: RasterizerSceneGLES3::environment_set_tonemap: Condition ' !env ' is true.
>    At: drivers\gles3\rasterizer_scene_gles3.cpp:914
> ERROR: RasterizerSceneGLES3::environment_set_adjustment: Condition ' !env ' is true.
>    At: drivers\gles3\rasterizer_scene_gles3.cpp:929

**Comment by bruvzg** [comment] 2017-08-01 20:42
Looks like it is something wrong with `normal map` importing, converting it to `jpeg` solve the problem.
![sc6](https://user-images.githubusercontent.com/7645683/28846122-e28e2c0e-7712-11e7-911f-b14894046d2f.png)

Normal map preview in editor is also broken.
![sc7](https://user-images.githubusercontent.com/7645683/28846113-dccb3f0a-7712-11e7-941d-cf4f3f15f1aa.png)

**Comment by reduz** [comment] 2017-08-01 21:03
godot converts the normalmaps to RG format, so I wonder if something is
wrong with this format on intel driver...

**Comment by reduz** [comment] 2017-08-01 21:06
https://github.com/godotengine/godot/blob/master/drivers/gles3/rasterizer_storage_gles3.cpp#L318

As you can see, the texture is registered as RGTC. I wonder if the Intel driver does not support this for some reason. Here is the code to see if rgtc is supported:

config.rgtc_supported = config.extensions.has("GL_EXT_texture_compression_rgtc");

maybe for some reason this is false on intel?

**Comment by bruvzg** [comment] 2017-08-01 21:06
@reduz I am using AMD GPU, and looks like each reimport produce different result for normal maps.

**Comment by reduz** [comment] 2017-08-01 21:07
ok, first time i hear of this bug on AMD, so the issue may be something different then...

**Comment by george-norton** [comment] 2017-08-02 06:57
I have dumped the full list of available extensions. I see `GL_ARB_texture_compression_rgtc` rather than `GL_EXT_texture_compression_rgtc`. The full list is:
```GL_3DFX_texture_compression_FXT1
GL_AMD_depth_clamp_separate
GL_AMD_vertex_shader_layer
GL_AMD_vertex_shader_viewport_index
GL_ARB_ES2_compatibility
GL_ARB_ES3_compatibility
GL_ARB_arrays_of_arrays
GL_ARB_base_instance
GL_ARB_bindless_texture
GL_ARB_blend_func_extended
GL_ARB_buffer_storage
GL_ARB_cl_event
GL_ARB_clear_buffer_object
GL_ARB_clear_texture
GL_ARB_clip_control
GL_ARB_color_buffer_float
GL_ARB_compressed_texture_pixel_storage
GL_ARB_compute_shader
GL_ARB_conservative_depth
GL_ARB_copy_buffer
GL_ARB_copy_image
GL_ARB_debug_output
GL_ARB_depth_buffer_float
GL_ARB_depth_clamp
GL_ARB_depth_texture
GL_ARB_derivative_control
GL_ARB_draw_buffers
GL_ARB_draw_buffers_blend
GL_ARB_draw_elements_base_vertex
GL_ARB_draw_indirect
GL_ARB_draw_instanced
GL_ARB_enhanced_layouts
GL_ARB_explicit_attrib_location
GL_ARB_explicit_uniform_location
GL_ARB_fragment_coord_conventions
GL_ARB_fragment_layer_viewport
GL_ARB_fragment_program
GL_ARB_fragment_program_shadow
GL_ARB_fragment_shader
GL_ARB_fragment_shader_interlock
GL_ARB_framebuffer_no_attachments
GL_ARB_framebuffer_object
GL_ARB_framebuffer_sRGB
GL_ARB_geometry_shader4
GL_ARB_get_program_binary
GL_ARB_gpu_shader5
GL_ARB_gpu_shader_fp64
GL_ARB_half_float_pixel
GL_ARB_half_float_vertex
GL_ARB_indirect_parameters
GL_ARB_instanced_arrays
GL_ARB_internalformat_query
GL_ARB_internalformat_query2
GL_ARB_invalidate_subdata
GL_ARB_map_buffer_alignment
GL_ARB_map_buffer_range
GL_ARB_multi_bind
GL_ARB_multi_draw_indirect
GL_ARB_multisample
GL_ARB_multitexture
GL_ARB_occlusion_query
GL_ARB_occlusion_query2
GL_ARB_pixel_buffer_object
GL_ARB_point_parameters
GL_ARB_point_sprite
GL_ARB_post_depth_coverage
GL_ARB_program_interface_query
GL_ARB_provoking_vertex
GL_ARB_query_buffer_object
GL_ARB_robust_buffer_access_behavior
GL_ARB_robustness
GL_ARB_robustness_isolation
GL_ARB_sample_shading
GL_ARB_sampler_objects
GL_ARB_seamless_cube_map
GL_ARB_seamless_cubemap_per_texture
GL_ARB_separate_shader_objects
GL_ARB_shader_atomic_counters
GL_ARB_shader_bit_encoding
GL_ARB_shader_image_load_store
GL_ARB_shader_image_size
GL_ARB_shader_objects
GL_ARB_shader_precision
GL_ARB_shader_stencil_export
GL_ARB_shader_storage_buffer_object
GL_ARB_shader_subroutine
GL_ARB_shading_language_100
GL_ARB_shading_language_420pack
GL_ARB_shading_language_packing
GL_ARB_shadow
GL_ARB_stencil_texturing
GL_ARB_sync
GL_ARB_tessellation_shader
GL_ARB_texture_barrier
GL_ARB_texture_border_clamp
GL_ARB_texture_buffer_object_rgb32
GL_ARB_texture_buffer_range
GL_ARB_texture_compression
GL_ARB_texture_compression_bptc
GL_ARB_texture_compression_rgtc
GL_ARB_texture_cube_map
GL_ARB_texture_cube_map_array
GL_ARB_texture_env_add
GL_ARB_texture_env_combine
GL_ARB_texture_env_crossbar
GL_ARB_texture_env_dot3
GL_ARB_texture_float
GL_ARB_texture_gather
GL_ARB_texture_mirror_clamp_to_edge
GL_ARB_texture_mirrored_repeat
GL_ARB_texture_multisample
GL_ARB_texture_non_power_of_two
GL_ARB_texture_query_levels
GL_ARB_texture_query_lod
GL_ARB_texture_rectangle
GL_ARB_texture_rg
GL_ARB_texture_rgb10_a2ui
GL_ARB_texture_stencil8
GL_ARB_texture_storage
GL_ARB_texture_storage_multisample
GL_ARB_texture_swizzle
GL_ARB_texture_view
GL_ARB_timer_query
GL_ARB_transform_feedback2
GL_ARB_transform_feedback3
GL_ARB_transform_feedback_instanced
GL_ARB_transpose_matrix
GL_ARB_uniform_buffer_object
GL_ARB_vertex_array_bgra
GL_ARB_vertex_array_object
GL_ARB_vertex_attrib_64bit
GL_ARB_vertex_attrib_binding
GL_ARB_vertex_buffer_object
GL_ARB_vertex_program
GL_ARB_vertex_shader
GL_ARB_vertex_type_10f_11f_11f_rev
GL_ARB_vertex_type_2_10_10_10_rev
GL_ARB_viewport_array
GL_ARB_window_pos
GL_ATI_separate_stencil
GL_EXT_abgr
GL_EXT_bgra
GL_EXT_blend_color
GL_EXT_blend_equation_separate
GL_EXT_blend_func_separate
GL_EXT_blend_minmax
GL_EXT_blend_subtract
GL_EXT_clip_volume_hint
GL_EXT_compiled_vertex_array
GL_EXT_direct_state_access
GL_EXT_draw_buffers2
GL_EXT_draw_range_elements
GL_EXT_fog_coord
GL_EXT_framebuffer_blit
GL_EXT_framebuffer_multisample
GL_EXT_framebuffer_object
GL_EXT_geometry_shader4
GL_EXT_gpu_program_parameters
GL_EXT_gpu_shader4
GL_EXT_multi_draw_arrays
GL_EXT_packed_depth_stencil
GL_EXT_packed_float
GL_EXT_packed_pixels
GL_EXT_polygon_offset_clamp
GL_EXT_rescale_normal
GL_EXT_secondary_color
GL_EXT_separate_specular_color
GL_EXT_shader_framebuffer_fetch
GL_EXT_shader_integer_mix
GL_EXT_shadow_funcs
GL_EXT_stencil_two_side
GL_EXT_stencil_wrap
GL_EXT_texture3D
GL_EXT_texture_array
GL_EXT_texture_compression_s3tc
GL_EXT_texture_edge_clamp
GL_EXT_texture_env_add
GL_EXT_texture_env_combine
GL_EXT_texture_filter_anisotropic
GL_EXT_texture_integer
GL_EXT_texture_lod_bias
GL_EXT_texture_rectangle
GL_EXT_texture_sRGB
GL_EXT_texture_sRGB_decode
GL_EXT_texture_shared_exponent
GL_EXT_texture_snorm
GL_EXT_texture_storage
GL_EXT_texture_swizzle
GL_EXT_timer_query
GL_EXT_transform_feedback
GL_IBM_texture_mirrored_repeat
GL_INTEL_conservative_rasterization
GL_INTEL_fragment_shader_ordering
GL_INTEL_framebuffer_CMAA
GL_INTEL_map_texture
GL_INTEL_multi_rate_fragment_shader
GL_INTEL_performance_query
GL_KHR_blend_equation_advanced
GL_KHR_blend_equation_advanced_coherent
GL_KHR_debug
GL_KHR_texture_compression_astc_hdr
GL_KHR_texture_compression_astc_ldr
GL_NV_blend_square
GL_NV_conditional_render
GL_NV_primitive_restart
GL_NV_texgen_reflection
GL_SGIS_generate_mipmap
GL_SGIS_texture_edge_clamp
GL_SGIS_texture_lod
GL_SUN_multi_draw_arrays
GL_WIN_swap_hint
WGL_EXT_depth_float
WGL_ARB_buffer_region
WGL_ARB_extensions_string
WGL_ARB_make_current_read
WGL_ARB_pixel_format
WGL_ARB_pbuffer
WGL_EXT_extensions_string
WGL_EXT_swap_control
WGL_ARB_multisample
WGL_ARB_pixel_format_float
WGL_ARB_framebuffer_sRGB
WGL_ARB_create_context
WGL_ARB_create_context_profile
WGL_EXT_pixel_format_packed_float
WGL_EXT_create_context_es_profile
WGL_EXT_create_context_es2_profile
WGL_NV_DX_interop
WGL_INTEL_cl_sharing
WGL_NV_DX_interop2
WGL_ARB_create_context_robustness```

**Comment by bruvzg** [comment] 2017-08-02 07:37
`config.rgtc_supported` is false on `AMD FirePro D300`, forcing it to true fix the issue.

`GL_ARB_texture_compression_rgtc` and `GL_EXT_texture_compression_rgtc` are **NOT** in the extension list, but RGTC is supported.

Looks like Apple's drivers only list extensions that aren't core in the current context version, and RGTC is part of core OpenGL since version 3.0

**Comment by reduz** [comment] 2017-08-02 12:49
if it's core, since we are using 3.3, it should not even be detected then.
Just wrap it aruond an #ifdef GLES_OVER_GL

**Comment by reduz** [comment] 2017-08-07 02:05
i fixed this, closing

**Closed by reduz** 2017-08-07 02:05 UTC
Labels: bug, topic:rendering
