### ISSUE TITLE
Class extending itself crashes the editor

### ISSUE THREAD

**Issue by siriamez** [godotengine/godot#27100] opened 2019-03-15 16:14 UTC
**Godot version:** 3.1 Stable

**OS/device including version:** Windows 10 64-bit

**Issue description:** Creating a new script file, assigning it a unique `class_name` and then letting it extend itself crashes Godot and renders it impossible to reopen the project.

**Steps to reproduce:**
1. Create an empty script file that `extends Node`
2. Add the line `class_name Test`
3. Change the line `extends Node` to `extends Test`
4. Save the script file

**Minimal reproduction project:** [inheritance_bug.zip](https://github.com/godotengine/godot/files/2971946/inheritance_bug.zip)

**Comment by karliss** [comment] 2019-03-16 09:53
Description looks very similar to #25339

**Comment by akien-mga** [comment] 2019-04-01 09:31
Duplicate of #25339.

**Closed by akien-mga** 2019-04-01 09:31 UTC
Labels: bug, topic:gdscript
