### ISSUE TITLE
Animations not correctly imported in godot 4

### ISSUE THREAD

**Issue by mallerius** [godotengine/godot#63547] opened 2022-07-27 17:07 UTC
### Godot version

4.0a12

### System information

Windows 11

### Issue description

When importing assets from blender, the included animations are not played as intended. The motions of the animated objects dont correspond correctly to the ones in blender. I tested with the same file imported into Godot 3 where it worked without issues. 

### Steps to reproduce

Make a rigged model in blender. Animate it. Exxport it to gltf. Import into Godot 4.0a12. Try to play the animations from the AnimationPlayer. 

### Minimal reproduction project

[testproject.zip](https://github.com/godotengine/godot/files/9201231/testproject.zip)

**Comment by Zireael07** [comment] 2022-07-27 17:09
Did you try disabling optimizer?

**Comment by mallerius** [comment] 2022-07-27 17:10
> 

do you mean in the export options of blender "Optimize Animation size"?

**Comment by Zireael07** [comment] 2022-07-27 17:11
No, Godot has built in optimization, this sometimes leads to losing entire tracks on import.

**Comment by mallerius** [comment] 2022-07-27 17:14
Thanks! This indeed was the issue. thank you very much!

**Comment by Zireael07** [comment] 2022-07-27 17:16
np :)

**Comment by Calinou** [comment] 2022-07-27 17:18
Duplicate of https://github.com/godotengine/godot/issues/58968 (same cause).

**Closed by Calinou** 2022-07-27 17:18 UTC
