### ISSUE TITLE
Saving paths in binary when importing font

### ISSUE THREAD

**Issue by Keetz** [godotengine/godot#7309] opened 2016-12-16 08:50 UTC
Was discussing the problem on IRC and was advised to create an issue here about this.

Some paths to the original files are saved in the binary when importing a font, causing  problems when sharing the project with the rest of our team. Check out the link below for more details.

Original post https://godotdevelopers.org/forum/discussion/18094/what-is-the-correct-way-to-import-a-bitmap-font-we-get-load-errors#latest

**Comment by bojidar-bg** [comment] 2016-12-16 12:03
Is there the same issue with other kinds of imported resources, like 3D scenes?

**Comment by Keetz** [comment] 2016-12-16 13:02
@bojidar-bg We just tried importing a simple 3D asset, adding it to a scene and push the project, and doesn't seem to be a problem there.

Just remembered, we are also using some imported translations files which are fine, only complains if the .csv file isn't included but that's of course something different and ok.

So far, just the fonts causing trouble here.

**Comment by bojidar-bg** [comment] 2016-12-16 13:13
Related to #7248

**Comment by Keetz** [comment] 2016-12-16 13:29
@bojidar-bg ah perfect, we will give the temp solution addressed there a look, and if that solves our problem, ill go ahead and close this issue and throw an upvote over there instead so we don't have multiple issues for the same bug

**Comment by bojidar-bg** [comment] 2016-12-16 13:31
I'd close the other one, as this is more general though... What is your opinion @godotengine/bugsquad

**Comment by kubecz3k** [comment] 2016-12-16 15:36
@bojidar-bg I think you are right

**Comment by Keetz** [comment] 2016-12-16 15:45
I think we at least should include the temporary solution somehow :) Always great with a quickfix

**Comment by kubecz3k** [comment] 2016-12-16 15:52
@Keetz you mean to resave font as tres?

**Comment by Keetz** [comment] 2016-12-16 16:55
@kubecz3k well, yea, there we go, the temporary solution is now in this thread too xD
But it's nice with the picture and everything, we for sure didn't think of saving as tres and editing the path in that file

**Comment by eska014** [comment] 2016-12-18 22:46
Seems to occur only when importing on Windows

**Comment by bojidar-bg** [comment] 2016-12-19 13:31
If it indeed happens only on windows, then the problem is either somewhere in the platform's filesystem management (esp. if there are other similar issues here and there which only happen on windows), or has something to do with `/` vs. `\` and disk drives.

**Comment by eska014** [comment] 2016-12-20 00:54
Can't reproduce this on Win7, maybe a Win10 issue

**Comment by uldall** [comment] 2017-01-05 11:41
This is possibly also related to #6153

**Comment by tapir** [comment] 2017-01-12 18:39
I was victim of this bug. Windows 7 64 bit.

Here is the *.fnt file that I created with ShoeBox: [pxelfont.zip](https://github.com/godotengine/godot/files/702549/pxelfont.zip)

There is 2 problems with it
1 - The importer creates it's own *.fnt (in binary) and *.png but the binary *.fnt still have reference to the old *.png created with ShoeBox.
2 - The reference itself is an absolute path so it really took me hours to debug why my android export wasn't working.

**Comment by reduz** [comment] 2017-01-23 20:31
This method of importing will go away in Godot 3.0, and no change will happen for 2.x at this point

**Comment by tapir** [comment] 2017-01-24 09:10
That's a shame. I'll try to fix it myself as it's a blocker for our game. @reduz any input/direction would be appreciated

**Comment by akien-mga** [comment] 2017-01-24 09:16
I do believe it must be possible (and needed) to fix this in 2.1.x even if 3.0 will have a different import system.

IMO it's much better not to have an automatic reimport of fonts than to have their source path hardcoded in the file. So if someone comes up with a fix, please still make a PR so that we can review it for merging into 2.1 :)
Note also that #7248 documents a workaround to fix the issue (save as .tres, edit the path manually).

I guess a place to start looking at would be the font importing code: https://github.com/godotengine/godot/blob/master/tools/editor/io_plugins/editor_font_import_plugin.cpp

**Comment by tapir** [comment] 2017-01-24 09:20
@akien-mga I'll do my best to solve it
About saving it in *.tres format, how do I do that? When I manually put a *.tres extension to the export filename godot complains about it should be *.fnt.

**Comment by akien-mga** [comment] 2017-01-24 09:22
@tapir See https://github.com/godotengine/godot/issues/7248#issue-193475491 it's explained there.

**Comment by Noshyaar** [comment] 2018-04-10 15:53
First of all thank you for your report and sorry for the delay.

We released Godot 3.0 in January 2018 after 18 months of work, fixing many old issues either directly, or by obsoleting/replacing the features they were referring to.

We still have hundreds of issues whose relevance/reproducibility needs to be checked against the [current stable version](https://godotengine.org/download), and that's where you can help us.
**Could you check if the issue that you described initially is still relevant/reproducible in Godot 3.0 or any newer version, and comment about it here?**

For bug reports, please also make sure that the issue contains detailed steps to reproduce the bug and, if possible, a zipped project that can be used to reproduce it right away. This greatly speeds up debugging and bugfixing tasks for our contributors.

Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

Thanks in advance.

*Note: This message is being copy-pasted to many "stale" issues (90+ days without activity). It might happen that it is not meaningful for this specific issue or appears oblivious of the issue's context, if so please comment to notify the Bugsquad about it.*

**Comment by akien-mga** [comment] 2018-09-17 13:42
The 2.1 branch is no longer actively worked on by engine developers, unless critical fixes are needed for current games in production. As such we are now closing non-critical bug reports affecting only the 2.1 branch.

Please comment if this was incorrectly triaged and is still relevant in 3.x versions.

**Closed by akien-mga** 2018-09-17 13:42 UTC
Labels: bug, platform:windows, topic:editor
