### ISSUE TITLE
Godot Engine 3.1 ALPHA 2 don´t respond (resolved)

### ISSUE THREAD

**Issue by hyperJJmaster** [godotengine/godot#23585] opened 2018-11-08 01:46 UTC
**Godot version:**
3.1 ALPHA 2

**OS/device including version:**
Windows 7 64x
Intel HD Graphics SandyBridge or 2nd generation

**Issue description:**
godot don´t respond when open proyect or create new proyect

![error](https://user-images.githubusercontent.com/24927155/48172486-03d17880-e2ce-11e8-8123-b887113d764d.png)

**Steps to reproduce:**
Just open proyect or create new proyect

**Comment by MightyPrinny** [comment] 2018-11-08 03:04
Try editing the project file and delete the default environment, that seems to break gles2 projects

**Comment by hyperJJmaster** [comment] 2018-11-08 14:34
I think that can not be done from the project manager or is it? because I can not access the editor

**Comment by Calinou** [comment] 2018-11-08 15:49
@hyperJJmaster The `default_env.tres` file is located in the project directory, try accessing it from a file manager and remove it.

**Comment by hyperJJmaster** [comment] 2018-11-08 17:13
OOhhh thanks

**Comment by StraToN** [comment] 2018-11-09 10:36
If the problem is resolved, I'll close the issue. Thanks @Calinou :)

**Closed by StraToN** 2018-11-09 10:36 UTC
