### ISSUE TITLE
Zoom visual script editor via mouse scrolling

### ISSUE THREAD

**Issue by agameraaron** [godotengine/godot#6168] opened 2016-08-16 09:31 UTC
Linux Mint 17.3 - Godot version: 2.2 alpha (Aug 14th)

This is a feature request for the visual scripting system: the mouse scroll wheel will increase the zoom level as it is scrolled forward. When scrolled backward it should zoom out at the same rate. Would that not be ideal? It currently does nothing and it's what I expected it to do when I first tried it out. Thanks!

**Comment by djrm** [comment] 2016-08-29 16:17
should be moved to 3.0 since zooming in graphs is not optimal for now, and it seems it will require better rendering methods.

**Comment by reduz** [comment] 2017-08-05 13:08
moving to 3.1, also, i'm not sure if scrolling is right for zooming here.. most people would expect to scroll through a large script instead..

**Comment by agameraaron** [comment] 2017-08-06 12:09
I figured grabbing an empty area with the first mouse button is expected behavior for moving around the script as the graph can expand not only vertically (the only way the scroll on an average mouse wheel would adjust), but also expand out horizontally.

**Comment by reduz** [comment] 2017-08-06 12:12
I was thinking we might get away by using the editor functions to create
lodpi/highdpi themes, so we can just change the theme for zoom..

**Comment by agameraaron** [comment] 2017-08-06 12:21
Considering I regularly use 720p and easily made some very large scripts with only a little bit of use, I find it hard to believe you could make any theme low enough for my DPI. Not that my personal opinion matters, I plan to stick to GDscript myself. But for others in my situation that also expect to scroll around scripts by grabbing it & moving it around, I just can't see how theming would do anything more than make it slightly less annoying to use.

**Comment by RyanJEC** [comment] 2019-01-13 23:10
Really this was removed from 3.1 milestone *sigh*

There has to be a better way than just clicking the zoom buttons in the editor. This is really cumbersome.

**Comment by TheRealCatherine** [comment] 2019-04-10 13:51
Zooming via mouse wheel would match UE4 Blueprints and is what my muscles keep trying to do.

Currently it scrolls vetically which is silly since node trees tend to go left-to-right and grow horizontally more than vertically.

Regarding the look - yeah when you zoom out the text starts to look bad but it still allows you see the overall structure and zoom in on a different part.

Ideally, IMHO, the zoom location should be centered on the cursor location (rather than screen center) as in Photoshop.

**Comment by Chaosus** [comment] 2020-10-06 17:20
The https://github.com/godotengine/godot/issues/41538 is a duplicate of this, but since it targets the whole GraphEdit element and not only Visual Scripts, I close this issue instead.

**Closed by Chaosus** 2020-10-06 17:20 UTC
Labels: enhancement, topic:editor, topic:visualscript, usability
