### ISSUE TITLE
Toggling Fullscreen Doesn't Work When Always on Top is Enabled

### ISSUE THREAD

**Issue by cybereality** [godotengine/godot#48312] opened 2021-04-29 23:36 UTC
**Godot version:**

Godot 3.3

**OS/device including version:**

Ubuntu Linux 64-bit, Nvidia 2080 Ti, Driver 460, GLES2/3

**Issue description:**

Toggling fullscreen mode with `OS.window_fullscreen = !OS.window_fullscreen` initially causes a windowed app to go fullscreen. However, calling it again will result in strange behavior. Either fullscreen mode is exited, but the window remains maximized, or it seems to do nothing and requires calling the toggle function 2 or 3 more times before the windowed mode is restored. This only happens when "Always on Top" is enabled, and seems to be specific to Linux, as it works in Windows.

Expected behavior is that every time you call `OS.window_fullscreen = !OS.window_fullscreen` that the window switches between fullscreen and windowed mode. This works when disabling "Always on Top".

**Steps to reproduce:**
Test the sample project and press "F" to toggle fullscreen. Or make a new project and bind an input map to:
`OS.window_fullscreen = !OS.window_fullscreen` and also be sure to enable "Always on Top".

**Minimal reproduction project:**

[Fullscreen.zip](https://github.com/godotengine/godot/files/6402155/Fullscreen.zip)

**Comment by akien-mga** [comment] 2021-04-30 07:33
Tested on Mageia 9 64-bit with KDE Plasma 5.21.4, I can confirm part of the issue, namely that toggling between fullscreen and non-fullscreen with "Always on Top" keeps the windowed mode maximized.

I can't reproduce that part though:

> or it seems to do nothing and requires calling the toggle function 2 or 3 more times before the windowed mode is restored

For me pressing "F" in the example project always properly toggles between fullscreen and (maximized) windowed mode. It does however feel a bit slow to respond compared to how it works without "Always on Top".

CC @godotengine/linux-bsd

**Comment by Wolfe2x7** [comment] 2021-06-05 20:07
I can confirm this is issue affects Linux Mint 20.1 (Cinnamon). I had not tracked it down to Always on Top being enabled; good to know.

**Comment by Wolfe2x7** [comment] 2021-06-18 20:35
For what it's worth, I have successfully worked around this by calling `OS.set_window_always_on_top(false)` before switching to fullscreen and setting it to true after switching back to a window. The switch seems to work perfectly, and I'm happy not combining always on top with fullscreen anyway, in case of errors.

**Comment by cybereality** [comment] 2021-11-13 02:51
I've discovered something. If you disable Resizable in the Window Project settings, then this problem goes away. I can now toggle Fullscreen on and off, while keeping Always on Top, and everything works. Since I rarely need to resize a window, and most shipped games don't allow window resizing, I would consider this an acceptable work-around for the time being.

**Comment by akien-mga** [comment] 2022-07-19 07:16
Fixed by #62543.

**Closed by akien-mga** 2022-07-19 07:16 UTC
Labels: bug, platform:linuxbsd, topic:porting, needs testing
