### ISSUE TITLE
Rendering artifacts with exported iOS project

### ISSUE THREAD

**Issue by maxqsoftware** [godotengine/godot#40551] opened 2020-07-20 21:15 UTC
**Godot version:**
v3.2.1

**OS/device including version:**
iPhone 11, iOS 13.5.1
Exported on macOS Catalina 10.15.2

**Issue description:**
Observing artifacts with rendering on iOS device. Initially tried with the default mobile rendering settings, then tried setting mobile settings equal to the default desktop rendering settings to see if there was an issue using lower-level settings but the artifacts persisted.

I boiled the issue down to a single mesh which is a large plane with a shader applied to it to give it the appearance of Saturn's rings.

Artifacts were not observed using iPhone 11 Simulator.

<img width="896" alt="20200720_205409535_iOS" src="https://user-images.githubusercontent.com/49388568/87986612-35827700-ca92-11ea-86d1-b4c65ce8ac53.png">

**Steps to reproduce:**
Issues occur on boot.

**Minimal reproduction project:**

Note: I have stripped out the export details since that contains confidential information for my AppStore account.

[archive.zip](https://github.com/godotengine/godot/files/4950078/archive.zip)

**Comment by naithar** [comment] 2020-07-21 20:41
Same behavior on stable 3.2.2 on both GLES2 and GLES3.

**Comment by clayjohn** [comment] 2020-07-21 20:57
To clarify. Hiding that one mesh gets rid of the artifacts?

**Comment by naithar** [comment] 2020-07-22 10:37
If Mesh hidden there is no issue (no surprise there). WIth different settings artifacts are still there. I've tried to tweak different settings, but there was no effect.
Also changing shader to just apply a color, I've got artifacts in an editor: 
<img width="500" alt="Снимок экрана 2020-07-22 в 13 29 55" src="https://user-images.githubusercontent.com/3750083/88166301-b9b63500-cc1f-11ea-8860-b7734ce379eb.png">

**Comment by naithar** [comment] 2020-07-22 10:46
The problem seems to be in `return;` statement used in `fragment()`. When i removed it from color shader, artifacts was gone from editor and did not appear in iOS build. Also removing `return;` statement from original shader removed an artifacts too.
iOS:
<img width="500" alt="iOS" src="https://user-images.githubusercontent.com/3750083/88167398-6e9d2180-cc21-11ea-8017-8732504f4de3.jpg">
Editor:
<img width="500" alt="Снимок экрана 2020-07-22 в 13 45 11" src="https://user-images.githubusercontent.com/3750083/88167535-a73cfb00-cc21-11ea-9454-7c4df45c4253.png">

**Comment by akien-mga** [comment] 2020-07-22 11:21
@naithar #39863 was fixed after the 3.2.2-stable release, and the fix is included in 3.2.3-beta1. Which version did you test?

**Comment by naithar** [comment] 2020-07-22 11:29
@akien-mga rechecked with `3.2.2-stable` from website and `3.2.3-beta1`. `3.2.2` doesn't give an error, while `3.2.3` results in `:78 - Using 'return' in 'fragment' processor function results in undefined behavior!` on using `return;`

**Comment by akien-mga** [comment] 2020-07-22 11:42
Thanks, so it's indeed a duplicate of #39863, fixed by #39869 (`master`) and #39870 (3.2.3).

**Closed by akien-mga** 2020-07-22 11:42 UTC
Labels: bug, confirmed, platform:ios, topic:rendering
