### ISSUE TITLE
Atlas Texture Reimport not work

### ISSUE THREAD

**Issue by firecloud888** [godotengine/godot#37429] opened 2020-03-30 12:37 UTC
**Godot 3.2.1:**

**Windows 10**

When I select multiple images and reimport them as a texture atlas, the editor will restart and reimport the images, but finally I can't find the file in the editor or the explorer, but single file works.
I do the reimport as this [link](https://godotengine.org/article/atlas-support-returns-godot-3-2)
But still not work

Reproduce

Add multiple image files into a folder of the project
Select images in Filesystem dock
In Import tab, choose TextureAtlas
Set a filename and a mode
Click on Reimport button

Minimal reproduction project:
N/A

Link to this one:[Atlas reimport procedure does not create atlas file](https://github.com/godotengine/godot/issues/36976)

**Comment by AiurTemplar** [comment] 2020-04-05 14:06
I have exactly the same problem with you and I found a same feedback here:
https://gamedev.stackexchange.com/questions/181298/godot-3-2-atlastexture-not-creating-any-texture-atlas

**Comment by firecloud888** [comment] 2020-04-05 14:13
Yes, I think maybe some updates mess with some code then cause this

**Comment by AiurTemplar** [comment] 2020-04-05 14:35
> Yes, I think maybe some updates mess with some code then cause this

你是中国的？？幸会幸会……

**Comment by guilhermefelipecgs** [comment] 2020-04-05 14:54
Closing as duplicate of #36976

**Closed by guilhermefelipecgs** 2020-04-05 14:54 UTC
Labels: bug, regression, topic:import
