### ISSUE TITLE
PopupMenu, MenuButton, OptionButton text becomes blurry on canvas_items stretch mode when screen is resized

### ISSUE THREAD

**Issue by lesleyrs** [godotengine/godot#70791] opened 2023-01-01 01:40 UTC
### Godot version

4.0 beta 10

### System information

Windows 10

### Issue description

On both GLES and Vulkan renderer the optionbutton options become blurry when screen is resized other than the default size.

### Steps to reproduce

Load repro project, run scene and try the options.

### Minimal reproduction project

[low_res_options.zip](https://github.com/godotengine/godot/files/10328180/low_res_options.zip)

PS: happy new year!

**Comment by Calinou** [comment] 2023-01-01 04:39
Related to https://github.com/godotengine/godot/issues/69749.

This occurs because font oversampling isn't used when rendering the PopupMenu.

**Comment by bruvzg** [comment] 2023-01-03 07:33
> This occurs because font oversampling isn't used when rendering the PopupMenu.

Oversampling is a global value and should be applied to all text, it this case it seems like it's something wrong with embedded window scale mode in general.

**Comment by bruvzg** [comment] 2023-01-03 08:17
>  it this case it seems like it's something wrong with embedded window scale mode in general.

Parent window content scale seems to be completely ignored by embedded windows.

**Comment by 2fd5** [comment] 2023-01-25 17:46
For me same issue on regular `Button` with text value , when camera zoom level is increased.
Only text that is on CanvasLayer is not affected as it is not affected by the zoom level. 
Godot 4.0.beta15 on macOS 13

Below the "Add" button is the one with the issue.
![Screenshot 2023-01-25 at 18 41 02](https://user-images.githubusercontent.com/64538990/214641894-2057cf0e-dcc8-4f4e-b7d8-df3a8bfaec94.png)

**Comment by Calinou** [comment] 2023-01-25 18:30
>  , when camera zoom level is increased.

This is expected. Fonts are not re-rasterized to take Camera2D zoom into account. If you want text to remain crisp in this situation, you need to enable **Multichannel Signed Distance Field** on the font in the Import dock. For the default project font, you need to enable the **Default Font Multichannel Signed Distance Field** advanced project setting instead.

**Comment by justdaft** [comment] 2023-05-18 09:41
I am having a similar issue with a texture looking blurry when the scale is reduced  inside  popup window.
[popup_test.zip](https://github.com/godotengine/godot/files/11506541/popup_test.zip)

**Comment by Calinou** [comment] 2023-05-22 21:42
- Duplicate of https://github.com/godotengine/godot/issues/54030 (same cause).

**Closed by Calinou** 2023-05-22 21:42 UTC
Labels: bug, confirmed, regression, topic:gui

**Comment by 2fd5** [comment] 2023-06-27 17:12
> > For me same issue on regular `Button` with text value , when camera zoom level is increased.
> 
> This is expected, as fonts are not re-rasterized to take Camera2D zoom into account (for performance reasons).
> 
> If you want text to remain crisp in this situation, you need to enable **Multichannel Signed Distance Field** on the font in the Import dock. For the default project font, you need to enable the **Default Font Multichannel Signed Distance Field** advanced project setting instead.

Using **Default Font Multichannel Signed Distance Field** made most of the fonts at zoom level 1.0 look weird and choppy:
![image](https://github.com/godotengine/godot/assets/64538990/c66fd26c-686a-4dde-906c-d208879caf10)

This is with **Default Font Multichannel Signed Distance Field**  off:
![image](https://github.com/godotengine/godot/assets/64538990/4f9c5cde-2635-43f6-a7a8-87df81b56603)

The examples above are displayed on canvas item. Having said that **Multichannel Signed Distance Field** made fonts on the game map look better.

My workaround was to to keep the zoom operate in range of 1.0 and lower for zooming out. Effectively making it so that maximal zoom in game is 1.0, everything is crisp and readable, and can go lower for zooming out and seeing more of the map.

**Comment by Calinou** [comment] 2023-06-28 08:28
>  Using Default Font Multichannel Signed Distance Field made most of the fonts at zoom level 1.0 look weird and choppy:

Self-intersecting outlines are not supported by MSDF. This is a design limitation that could be fixed by [integrating Skia](https://github.com/godotengine/godot/pull/61555), but this is a huge dependency given the size of the problem at hand.
