### ISSUE TITLE
Dragging *.obj files imported as Mesh to the editor's viewport issue

### ISSUE THREAD

**Issue by mrcdk** [godotengine/godot#12571] opened 2017-11-01 21:34 UTC
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Godot 3.0 master https://github.com/godotengine/godot/commit/025f13856138918b13956b085a586a73a584bc04

**Issue description:**

When dragging an *.obj file imported as a Mesh from the filesystem dock to the viewport the created `MeshInstance` will be treated as a scene and won't let you save the scene because this error:
![https://i.imgur.com/Imjltm2.png](https://i.imgur.com/Imjltm2.png)

It can be added to the scene if you create a `MeshInstance` and you manually add it to the `Mesh` property. This way you will be able to save the scene.

**Steps to reproduce:**
1. Drag an *.obj file imported as a Mesh into the editor's viewport
2. Try to save the scene

**Comment by RodeoMcCabe** [comment] 2017-11-03 03:39
I experienced this problem about a week ago on Linux with a nightly build. I found the same workaround of creating a MeshInstance and manually adding the .obj to the Mesh property.

FWIW I was using Debian and Xfce at the time. I'm now using Manjaro and i3, will test with alpha 2 and report back later.

**Comment by Shane-S** [comment] 2017-11-03 23:07
I don't know enough about the scene saving system to fix this right now, but the problem is here:
https://github.com/godotengine/godot/blob/67a706fc1b9721f3f06eef8be7312f175e2041ce/scene/resources/packed_scene.cpp#L427
`ResourceLoader::load` is returning a `Ref<Resource>`. so the [cast](https://github.com/godotengine/godot/blob/master/core/reference.h#L158) to `Ref<PackedScene>` fails. `p_node->get_filename() != String() && p_node->get_owner() == p_owner && instanced_by_owner` is `false` when creating the instance and assigning the mesh manually, so this error doesn't happen in that case.

**Comment by Zireael07** [comment] 2017-11-06 13:27
Alpha 2 seems not to consider obj as meshes, so they can't be assigned to mesh instances :(

**Closed** 2017-11-12 19:31 UTC
Labels: bug, topic:editor
