### ISSUE TITLE
"Drag Margin Camera" in  debug mode have problems

### ISSUE THREAD

**Issue by git2013vb** [godotengine/godot#22558] opened 2018-09-30 14:52 UTC
**Godot version:**
![image](https://user-images.githubusercontent.com/13235119/46258793-061f0680-c4c8-11e8-9b8b-8afdbcc691e9.png)

**OS/device including version:**
Win7-64 
![image](https://user-images.githubusercontent.com/13235119/46258808-2353d500-c4c8-11e8-8f0f-80e7e767b5bd.png)

**Issue description:**
The mouse get stuck + hidden in editor and I cant move outside from it. I have to use ctrl+tab to go in prototype then alt + f4 to close it. Same for the editor.

**Steps to reproduce:**
I run a prototype and in editor I try to change Camera -> Drag Margin -> Right (I guess it is the same in any parameter)

**Minimal reproduction project:**
NA

**Comment by Anutrix** [comment] 2019-07-10 16:27
Can you provide more info or a minimal project?
Also, what do you mean by prototype?

**Comment by git2013vb** [comment] 2019-08-10 12:09
A prototype mean "test", "small project just to test something" :) I will try soon. thanks :)

**Comment by KoBeWi** [comment] 2020-08-23 21:37
Can anyone still reproduce this bug in [Godot 3.2.3 rc4](https://godotengine.org/article/release-candidate-godot-3-2-3-rc-4) or any later release?

If yes, please ensure that an up-to-date Minimal Reproduction Project (MRP) is included in this report (a MRP is a zipped Godot project with the minimal elements necessary to reliably trigger the bug). You can upload ZIP files in an issue comment with a drag and drop.

**Comment by KoBeWi** [comment] 2020-09-28 17:16
Closing due to lack of update. Please comment if you can still reproduce this issue in the latest stable version of Godot.

**Closed by KoBeWi** 2020-09-28 17:16 UTC
Labels: bug, topic:editor
