### ISSUE TITLE
Godot fails to cross-compile to Windows using MinGW, `target=debug` and `use_lto=yes`

### ISSUE THREAD

**Issue by Xrayez** [godotengine/godot#49212] opened 2021-05-30 21:45 UTC
**Godot version:**
3.4-beta e9909b763af

**OS/device including version:**
Fedora 34 host.
GCC/x86_64-w64-mingw32/10.3.1

**Issue description:**
```
[100%] Linking Program        ==> bin/godot.windows.tools.64.exe
/usr/lib/gcc/x86_64-w64-mingw32/10.3.1/../../../../x86_64-w64-mingw32/bin/ld: btAlignedAllocator.windows.tools.64.o (symbol from plugin): warning: no symbol for section '_Z14btAlignPointerIcEPT_S1_y' found
lto1: error: two or more sections for .gnu.lto__ZN4ListIPN9Octree_CLIN17VisualServerScene8InstanceELb1E16DefaultAllocatorE8PairDataES3_E5clearEv.9678572.e6925aa0daa7c15
(null):0: confused by earlier errors, bailing out
make: *** [/tmp/cchKQabt.mk:17: /tmp/godot.windows.tools.64.exe.s4Jwiu.ltrans5.ltrans.o] Error 1
make: *** Waiting for unfinished jobs....
lto-wrapper: fatal error: make returned 2 exit status
compilation terminated.
/usr/lib/gcc/x86_64-w64-mingw32/10.3.1/../../../../x86_64-w64-mingw32/bin/ld: error: lto-wrapper failed
collect2: error: ld returned 1 exit status
scons: *** [bin/godot.windows.tools.64.exe] Error 1
scons: building terminated because of errors.
```

Not sure if this should/can be supported, but the error is here. The use case is to debug issues caused by LTO, see goostengine/goost#83 (which seems to be jpgd issue).

**Steps to reproduce:**
```
scons platform=windows target=debug use_lto=yes debug_symbols=yes bits=64
```
`debug_symbols=yes` likely not needed but that's what I used while compiling.

**Minimal reproduction project:**
N/A

**Comment by akien-mga** [comment] 2021-05-31 12:01
I can confirm the issue on Mageia 8 with:
```
mingw64-binutils-2.34-2.mga8
mingw64-gcc-10.2.1-2.mga8
mingw64-headers-8.0.0-1.mga8
```

**Comment by akien-mga** [comment] 2021-05-31 12:22
For the reference, I tried with the bullet module disabled (as the error references a bullet struct), but that just moves the issue someplace else:
```
lto1: error: two or more sections for .gnu.lto__ZN3MapIN18CanvasItemMaterial11MaterialKeyENS0_10ShaderDataE10ComparatorIS1_E16DefaultAllocatorE5_Data10_free_rootEv.7524010.3187f6e5341ddf31
```

**Comment by IlyaStuurFedorov** [comment] 2021-06-24 20:14
This is also a problem for a native debug LTO MinGW Windows build of 3.2.2

**Comment by Xrayez** [comment] 2021-12-08 12:58
Still valid in 3.5-beta. I stumbled upon this by accident again when I forgot to specify `target` when using `production=yes`.

**Comment by Atem1995** [comment] 2022-02-23 12:54
Still valid in 3.4.2 release. When use_mingw=yes target=release_debug use_lto=yes

**Comment by akien-mga** [comment] 2022-02-23 13:02
@Atem1995 What error are you having exactly, on what OS, and with what mingw versions?

This error is about `target=debug`, not `release_debug`. Building `target=debug` with LTO is not really useful and unsupported, and what this issue is about (finding a fix would still be good, but there's not much reason to do such a build).

**Comment by Atem1995** [comment] 2022-02-23 13:29
@akien-mga I tried to compile the source code for the 3.4.2 release In window 10. Use x86_64-w64-mingw32-gcc 11.2.0. Command is “Scons -j 12 platform= Windows bits=64 Tools =yes USe_mingw =yes Target = release_DEBUG USe_LTO =yes”. It took a long time in the final phase, and then ultimately no executable was generated. I did it with reference to official documentation, which could have been generated without using mingw.

**Comment by akien-mga** [comment] 2022-02-23 13:53
Thanks, that confirms that it's not the same issue. For this issue you should see an error like the one described in the first post: `warning: no symbol for section '_Z14btAlignPointerIcEPT_S1_y' found`.

In your case, is there really no error in the terminal?
It's normal that it takes a very long time to link with LTO, it can easily take 30 min or more. But ultimately it should finish with `scons: done building targets` and you should have a binary in the `bin` folder. If it doesn't do that, then most likely there was an error printed in the terminal.

**Comment by Atem1995** [comment] 2022-02-23 14:02
@akien-mga Thank you for your attention to my problems. Please wait a moment, I just tried compiling again and am waiting for the result or error. News will be posted.

**Comment by akien-mga** [comment] 2022-02-23 16:00
Besides the warnings, this is the error:
```
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: i386 architecture of input file `platform\\windows\\godot_res.windows.opt.tools.64.o' is incompatible with i386:x86-64 output
collect2.exe: error: ld returned 1 exit status\n"
```

That seems to be the same issue as #40286, we should continue the discussion there.

**Comment by allkhor** [comment] 2022-05-13 04:42
I don't know if it's worth creating a new issue, but if compiled with the flags **optimize=size use_lto=yes** i got errors like:
```
/usr/lib/gcc/i686-w64-mingw32/10.3.1/../../../../i686-w64-mingw32/bin/ld: /tmp/godot.windows.opt.32.exe.XFme3F.ltrans127.ltrans.o:<artificial>:(.text+0x3343f): undefined reference to `GDScriptParser::DataType::DataType() [clone .lto_priv.1] [clone .lto_priv.0]'
/usr/lib/gcc/i686-w64-mingw32/10.3.1/../../../../i686-w64-mingw32/bin/ld: /tmp/godot.windows.opt.32.exe.XFme3F.ltrans127.ltrans.o:<artificial>:(.text+0x334e2): undefined reference to `GDScriptParser::DataType::DataType() [clone .lto_priv.1] [clone .lto_priv.0]'
/usr/lib/gcc/i686-w64-mingw32/10.3.1/../../../../i686-w64-mingw32/bin/ld: /tmp/godot.windows.opt.32.exe.XFme3F.ltrans127.ltrans.o:<artificial>:(.text+0x335ec): undefined reference to `GDScriptParser::DataType::DataType() [clone .lto_priv.1] [clone .lto_priv.0]'
/usr/lib/gcc/i686-w64-mingw32/10.3.1/../../../../i686-w64-mingw32/bin/ld: /tmp/godot.windows.opt.32.exe.XFme3F.ltrans127.ltrans.o:<artificial>:(.text+0x33b67): undefined reference to `Ref<GDScript>::Ref<Script>(Ref<Script> const&) [clone .lto_priv.1] [clone .lto_priv.0]'
collect2: error: ld returned 1 exit status
scons: *** [bin/godot.windows.opt.32.exe] Error 1
scons: building terminated because of errors.
```
Full flags:  scons -j4 platform=windows use_mingw=yes target=release bits=32 tools=no production=yes verbose=yes warnings=no progress=no optimize=size
Compiled in Docker with Fedora 34, GCC/x86_64-w64-mingw32/10.3.1, Godot 3.4.4
Is this a documentation issue of the incompatible optimise=size and use_lto=True flags with mingw, or is this a bug?

**Comment by akien-mga** [comment] 2024-06-19 11:38
I'll close this as wontfix, as I don't think it's fixable. GCC LTO just isn't capable of dealing with too large objects, which they inevitably are when debug symbols are enabled (hundreds of MBs for some).

It's also not a useful build configuration (LTO depends on doing optimizations, debugging depends on not doing optimizations), so aside from the theoretical wish for all build options to work, there's not much to gain here by trying to workaround GCC LTO bugs.

**Closed by akien-mga** 2024-06-19 11:38 UTC
Labels: bug, platform:windows, topic:buildsystem, confirmed
