### ISSUE TITLE
Vulkan: SDFGI Spams console after a Light3D with dynamic bake mode has been removed from the scene

### ISSUE THREAD

**Issue by Szotyi2501** [godotengine/godot#62852] opened 2022-07-09 10:05 UTC
### Godot version

4.0.alpha11

### System information

Windows 10, Vulkan, any GPU

### Issue description

When SDFGI is enabled, and an object that has a Light3D node is removed from the scene for example wiht a script, it starts spamming the console with this error message:
```
E 0:00:01:0759   pre_process_gi: Condition "!li" is true. Continuing.
  <C++ Source>   servers/rendering/renderer_rd/environment/gi.cpp:1895 @ pre_process_gi()
```

A workaround is to set the Node's visibility to false right before you call `queue_free()` on it.

### Steps to reproduce

Create a new environment with SDFGI enabled, add a Light3D object, then remove it dynamically e.g. with a timer.

### Minimal reproduction project

[SDFGI_Error.zip](https://github.com/godotengine/godot/files/9076241/SDFGI_Error.zip)

**Comment by Calinou** [comment] 2022-07-09 16:47
Duplicate of https://github.com/godotengine/godot/issues/57840.

**Closed by Calinou** 2022-07-09 16:47 UTC
Labels: bug, topic:rendering, topic:3d

**Comment by Szotyi2501** [comment] 2022-07-10 09:46
No problem, I checked this list and it's not here, I think that's why I missed it: https://github.com/godotengine/godot/issues/55327

Perhaps you could add the other issue there? :)
