### ISSUE TITLE
Methods from base class aren't visible from animation player Insert Call Method Keyframe

### ISSUE THREAD

**Issue by Lucrecious** [godotengine/godot#26558] opened 2019-03-04 02:40 UTC
Sorry, I accidently pressed enter prematurely and it opened an issue. Hope this is not a duplicate. :(

**Godot version:**
3.1 beta 10

**OS/device including version:**
Latest OSX

**Issue description:**
Tried to add a Call Method key frame for a method in inherited class, but it wasn't in the list

**Steps to reproduce:**
1. Create a new node (A) and attach a script to it, put a method in that script
2. Create a new node (B) and attach a script to it that inherits from A
3. Add animation player to B
4. Add track for method calls
5. Add keyframe for method in A

Expected: See method from A in the list for script methods in B
Actual: Can't find method from A in the list for script methods in B

**Comment by mitchcurtis** [comment] 2019-05-16 18:51
I think this is a duplicate of https://github.com/godotengine/godot/issues/23384, which is apparently fixed... except it's not. I have a base class method and an overridden subclass method, and I can only call the subclass method, not the base.

**Comment by akien-mga** [comment] 2020-01-14 14:27
This seems to work fine in the current master branch.

**Closed by akien-mga** 2020-01-14 14:27 UTC
Labels: bug, topic:editor
