### ISSUE TITLE
Jerky movement of KinematicBody2D and PathFollow2D

### ISSUE THREAD

**Issue by Wend1go** [godotengine/godot#1659] opened 2015-04-09 08:55 UTC
KinematicBody2D and PathFollow2D nodes (probably other higer level nodes too) jitter in movement.
Moving a simple sprite through set_pos works much smoother. In both cases FPS are quite constant.
The issue seems quite common, even visible on some youtube tutorials.
https://www.youtube.com/watch?v=aMzPvouGqpM&feature=youtu.be&t=8m8s

OS: Linux Mint 17 64Bit, Windows 7 64Bit, OSX 
GPU Driver: Nvidia binary blobb and nouveau (only tested myself on linux, have no access to AMD hardware)

Example projects and further information can be found here:
path follow: 
http://www.godotengine.org/forum/viewtopic.php?f=11&t=1815
kinematicbody: 
http://www.godotengine.org/forum/viewtopic.php?f=11&t=1607&sid=6f044f9ee42cda9278a572e34c5d34c7

**Comment by zendorf** [comment] 2015-04-11 22:50
I am also finding this a big show stopper for my 2d game. I have tried various Windows pc's (Win7 and Win8 and both AMD and Nvidia cards) and they all exhibit some jerkiness even thought the fps is solid at 60. It seems to not matter if the movement is set_pos based or phsyics based. Even a slow moving camera movement will not look smooth.

Strangely enough, sometimes I have noticed that when the game is allowed to run for a while it smoothes out, but generally it is very unpredictable and even worse on fullscreen mode. I don't have these problems with a 3d scene...just 2d. This is a serious issue that really needs to be addressed!

**Comment by reduz** [comment] 2015-04-13 12:42
the choppy movement in pathfollow is definitely due to the cubic interpolation, try disabling it and it will work

**Comment by reduz** [comment] 2015-04-13 12:48
cubic interpolator is now fixed, pathfollow is no longer choppy

**Comment by reduz** [comment] 2015-04-13 13:05
I really can't get any choppiness on the car demo..  Ubuntu sometimes (every a few seconds) skips a frame and that looks a tiny bit choppy, but it seems unrelated to the engine

**Comment by freemanfromgodotengine** [comment] 2015-04-13 22:07
I can confirm jerky movement of the cars, with different speeds of the cars running together on the screen.
I do not use Noveau driver.
My specs:
Xubuntu 14.04 64-bit, 
gfx card: GeForce Go 7300
Nvidia driver version 304.125

There are no any messages in the console when jerky movement happens.

**Comment by reduz** [comment] 2015-04-13 23:21
I wish i could reproduce but i have a feeling this is unrelated to godot...
Will still try some more stuff though

**Comment by Wend1go** [comment] 2015-04-15 07:13
On my side the car demo runs smooth on my Linux machine (don't even notice any skipped frames) but stutters on Windows 7.

**Comment by freemanfromgodotengine** [comment] 2015-04-27 00:03
Maybe this will help in some way.
This is how resource monitor looks when demo runs:
https://github.com/freemanfromgodotengine/my_repository/blob/master/video/Kinematic_motion_problem.mp4

The video is much more jerky then the actual movement was on my screen, probably because movie was captured in only 25 fps, that comparing to 60 fps of the engine created an additional video smoothness problem.

You can see the debug stats as well as htop showing how hard two cores of my laptop's Core 2 Duo 2GHz CPU work. Of course most CPU work was created by capturing full screen video. Without screen capture when running the kinematic jerky demo, CPU works at max 35-38%, so I do not think it has much to do with the work of the CPU.

**Comment by Zamaroht** [comment] 2015-05-05 21:04
I have the same issue. I'm running with an Intel Pentium B940 (2 cores @2Ghz), onboard graphics and 4GB ram, Windows 7 32bit.

The example moves the three cars at the same time side by side, and while the kinematicbody stutters a lot, the other two travel smoothly, which makes me think that this is unrelated to OS or even rendering problems. If that was the case, all of them should stutter the same, at the low level they are all just an image moving, just with different logic.

**Comment by reduz** [comment] 2015-05-12 11:34
how do you put 3 cars together?

**Comment by Zamaroht** [comment] 2015-05-12 12:00
They are in the example project posted in the forum thread linked in the issue:
https://github.com/bitwes/kinematic_jittery_movement

**Comment by bitwes** [comment] 2015-05-13 02:18
I stated in the thread, but not here.  I updated the demo to use a couple different types of movement and icons.  I see the issue with all 3 but to a lesser extent on the node and sprite which use _process and set_pos.  

I've tried 1.1-rc2 and another build from source as of today (May 12) and I haven't noticed any difference.  The jitters are still there in windows.

**Comment by NikhilJolly** [comment] 2015-05-16 19:36
Hi! I am experiences similar jitters/glitches while using RigidBody2ds especially on android devices.

To make sure something else is not the culprit, I have made is a very simple prototype which includes just about 5-10 rigidbody2ds with a simple sprite and a collisionshape2d as children.

**Comment by reduz** [comment] 2015-05-16 20:10
Do you guys get jitter in this html5 game too?
http://jlongster.github.io/canvas-game-bootstrap/

**Comment by reduz** [comment] 2015-05-16 20:13
I also added a motion demo (demos/2d/motion), can you test if you get
jitter in all cars at the same time or they are different?

**Comment by Zamaroht** [comment] 2015-05-16 20:46
I don't get jitter in that html5 game. In the demo you just uploaded, the fixed process code and fixed process animation have a lot of jitter, the idle process ones don't jitter at all (or it is barely noticable at least). Tested this in windows 7 32bit with onboard graphics.

**Comment by reduz** [comment] 2015-05-16 20:54
can you do me a favor? please edit

main/main.cpp:1322

 and uncomment the following lines:

//if (time_accum+step < frame_slice)
//      return false;

recompile and let me know if you still have jitter

**Comment by NikhilJolly** [comment] 2015-05-16 21:23
Hi! Sorry I forgot to mention: 
I have made a simple prototype which includes just about 5-10 rigidbody2ds "falling from different heights".
Also the html5 game didn't gave me any jitters.
I will try that main edit and get back to you.

**Comment by Zamaroht** [comment] 2015-05-16 21:56
Just tried it. Now I get jitter in all them four, and the 'Idle Process Code' car is lagging behind a bit. The FPS seem to be steady at 60, sometimes changing to 59/61.

**Comment by NikhilJolly** [comment] 2015-05-16 22:42
I also finished testing. But in my case the performance is now much better.
Although sometimes jitter still occurs but when it does it occurs on all 4 of them.
And yes the Idle Process Code car lags behind.
But should this happen? I mean even slightly noticeable jitters?

Also, i tried that rigidbody2d prototype and it also showed very less jitters.
PS: Onto compiling android template, to test on device.

**Comment by NikhilJolly** [comment] 2015-05-16 23:08
Offtopic:Strange...I am getting error on Ubuntu while building template with latest repo:

modules/gdscript/gd_script.cpp: In member function 'Variant GDFunction::call(GDInstance*, const Variant**, int, Variant::CallError&, GDFunction::CallState*)':
modules/gdscript/gd_script.cpp:346:10: error: 'ret' was not declared in this scope
      if (ret.get_type()==Variant::STRING) {
          ^
scons: *** [modules/gdscript/gd_script.android.opt.o] Error 1
scons: building terminated because of errors.

Can't test on android.

**Comment by reduz** [comment] 2015-05-16 23:20
ah thanx for that issue, just fixed.

I restarted on windows and the demo I made works fine.. I just can't figure
out what is needed for the jitter to happen

**Comment by NikhilJolly** [comment] 2015-05-17 21:49
Hi reduz. Did it work fine with or without that edit of time_accum?
Plus have you tried it on any android device?

**Comment by reduz** [comment] 2015-05-17 22:34
it works fine with and without de edit

**Comment by NikhilJolly** [comment] 2015-05-17 23:19
How can I better address the problem?

**Comment by reduz** [comment] 2015-05-20 13:45
No Idea, it happens to some people but I can't reproduce it.. what is your
hardware? maybe i can find something similar to test

**Comment by NikhilJolly** [comment] 2015-06-02 03:39
Hey reduz! Any update regarding this?
Did you get some time to implement interpolation?

**Comment by okamstudio** [comment] 2015-06-02 03:54
not yet, but will eventually

On Tue, Jun 2, 2015 at 12:39 AM, NikhilJolly <notifications@github.com>
wrote:

> Hey reduz! Any update regarding this?
> Did you get some time to implement interpolation?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/okamstudio/godot/issues/1659#issuecomment-107788735>.
>



-- 

*OkamStudio*

**Comment by akien-mga** [comment] 2016-04-29 09:06
Is this issue still valid in the current master branch/2.0.x releases?

**Comment by kubecz3k** [comment] 2016-04-29 13:21
@akien-mga If I understand the issue correctly it's still valid. But the issue itself is a duplicate of https://github.com/godotengine/godot/issues/2043 (if I understand it correctly)

**Closed** 2016-04-29 13:23 UTC
Labels: archived, bug, topic:rendering
