### ISSUE TITLE
Assigning params programmatically to a `Material` no longer works in beta15

### ISSUE THREAD

**Issue by dotnetdummy** [godotengine/godot#72143] opened 2023-01-26 22:04 UTC
### Godot version

v4.0.beta15.mono.official and also v4.0.rc1

Not present in v4.0.beta14.mono.official (regression)

### System information

Windows 11, NVidia RTX 3080

### Issue description

Assigning params programmatically to a `Material` no longer works in beta15. Same project below works fine in beta14.

Edit(lyuma): there seems to be some difference between deferred and not.

### Steps to reproduce

Old Steps: Run the provided project several times in a row. The color of the icon should change between each run.

Edit(lyuma): New steps to reproduce:
1. Open the scene
2. Click the checkbox Use Standard on and off. This serializes a new material and then loads it from disk.
3. Starting from beta15, the serialized material has no `shader_parameter` assigned, so when using `CACHE_MODE_REPLACE`, they are loaded.
4. If correct, it should have stripes with the selected color. if the color is not serialized correctly, it will use the default color in the shader which is greyish.

### Minimal reproduction project

Edit(lyuma): I'm adding a new MRP that illustrates this regression using `set_shader_parameter`: 
[set_shader_parameter_test.zip](https://github.com/godotengine/godot/files/10689912/set_shader_parameter_test.zip)

Old MRP (using set_deferred without `shader_parameter`) [GD4ShaderSet.zip](https://github.com/godotengine/godot/files/10513740/GD4ShaderSet.zip)

**Comment by clayjohn** [comment] 2023-01-26 22:13
Perhaps caused by https://github.com/godotengine/godot/pull/71797 I wonder if this plays poorly with something in the .Net code

I don't know .Net stuff well, but the equivalent GDScript works (or at least what I think is equivalent)
```
$Icon.material.set_shader_parameter("u_replacement_color", Color(rnd.randf(), rnd.randf(), rnd.randf()))
```
I don't know what ``SetDeferred()`` does, but the issue likely lies there

**Comment by akien-mga** [comment] 2023-01-26 22:16
It's not a .NET issue, `SetDeferred()` is `Object.set_deferred()` in C++/GDScript - it's calling `Object.set()` as deferred. So it's for setting object properties, not shader parameters.

Before #71797, shader parameters no longer had the `shader_parameter/` prefix which differentiates them from normal properties. #71797 reintroduced it, so OP's code should call `SetDeferred()` on `"shader_parameter/u_replacement_color"` I assume.

Or better, use `SetShaderParameter` which is intended for this, as a deferred call if needed:
```
CallDeferred("SetShaderParameter", "u_replacement_color", ...);
```
(didn't test)

**Comment by clayjohn** [comment] 2023-01-26 22:17
> shader_parameter/

Ah, you sniped my edit above. Indeed:
```
$Icon.material.set_deferred("shader_parameter/u_replacement_color", Color(rnd.randf(), rnd.randf(), rnd.randf()))
```
Works as intended.

**Comment by dotnetdummy** [comment] 2023-01-27 10:24
Ah great! Thanks for the clarifications. 

It works both with `.SetDeferred("shader_parameter/u_replacement_color", ...);` and using the `.CallDeferred("set_shader_parameter", "u_replacement_color", ...);` in C#

**Comment by lyuma** [comment] 2023-02-08 21:15
I'm attaching a new MRP which reproduces the issue when using `set_shader_parameter`. While the original MRP seems wrong somehow, I think there may be some relation to the OP's original issue, likely led them down the path of using set_deferred which seems to have fixed it for them.

While that `set_shader_parameter` by itself seems to work, the bug seems to affect serialization if serialized in the same frame that shader is assigned.

**Comment by lyuma** [comment] 2023-02-08 21:28
Okay this history got too confusing so I'm closing this issue and opened #72923

Thanks for the original report, @dotnetdummy . you definitely hit some regression between b14 and b15. I hit some related regression between b14 and b15 but it's somehow a bit different. This issue could be relevant in diagnosing what happened, so it's still a useful report.

**Closed by lyuma** 2023-02-08 21:28 UTC
Labels: archived, topic:core, documentation
