### ISSUE TITLE
Problems with Deep Parallax

### ISSUE THREAD

**Issue by guilhermefelipecgs** [godotengine/godot#20854] opened 2018-08-09 18:51 UTC
**Godot version:**
a71a5fc0c3f5d487d3f18c3b9e9a768052795e86

**OS/device including version:**
Linux 4.17.12

**Issue description:**
What I was expecting:
![captura de tela de 2018-08-09 15-26-29](https://user-images.githubusercontent.com/1387165/43919097-5357368a-9beb-11e8-8099-7d1ffcb3ca33.png)
![captura de tela de 2018-08-09 15-27-20](https://user-images.githubusercontent.com/1387165/43919100-53ddc830-9beb-11e8-8057-18bf72133e6d.png)

What I got:
![captura de tela de 2018-08-09 15-26-41](https://user-images.githubusercontent.com/1387165/43919098-5381b0cc-9beb-11e8-9794-cf0127b55bfd.png)
![captura de tela de 2018-08-09 15-27-06](https://user-images.githubusercontent.com/1387165/43919099-53aef0dc-9beb-11e8-9a48-6e2e29acc353.png)

It looks like the parallax is a bit buggy :(

Blender file included in the project.

**Minimal reproduction project:**
[Deep Parallax.zip](https://github.com/godotengine/godot/files/2275559/Deep.Parallax.zip)

**Comment by Calinou** [comment] 2018-08-09 21:36
Duplicate of https://github.com/godotengine/godot/issues/15934.

**Closed by Calinou** 2018-08-09 21:36 UTC

**Comment by guilhermefelipecgs** [comment] 2018-08-09 22:36
It's seems my height map was not compatible for godot. I made some tweaks with krita and solves the depth problem.
