### ISSUE TITLE
Editor interface lags behind aproximately one state update

### ISSUE THREAD

**Issue by cbondurant** [godotengine/godot#39999] opened 2020-06-30 19:31 UTC
**Godot version:** Version 3.2.2 stable

**OS/device including version:**
Windows 10, version 1909, OS build 18363.900
Hardware: Integrated Graphics powered through an Intel i5-7300U on a dell laptop.

**Issue description:**
Directly after downloading Godot, I ran the exe provided. I attempt to interact with the user interface, creating a new project, etc.

Most interactions fail to properly refresh the screen to show new state, and instead show the previous state instead. For instance typing "test project" in the dialog for a new project name instead results in visibly seeing only "test projec". This can be temporarily remedied through doing some other ui updating action, such as hovering over a button, which causes the text box to update, but for the button to not highlight as if hovered over.

This makes the ui nearly impossible to use, as the disjoint between the visible state and the true state cause many confusing cases. A strong example being that scroll able menus, such as the node menu, will become disjointed, and clicking on what looks visibly as one node will select a different node, as there was another scroll update that was not represented visually. 

**Steps to reproduce:**
I honestly have no idea how to reproduce this issue, as it is both a constant issue across my entire Godot experience, and also exists from the default installation. I cannot assume this is a widespread problem, (otherwise Godot would be unusable). However I hope that I will be able to communicate with Godot contributors so that I can start using Godot myself.

**Comment by vntxx** [comment] 2020-06-30 20:08
Try to update your Intel HD Graphics driver
You can get it [Here](https://downloadcenter.intel.com/product/80939/Graphics)

**Comment by cbondurant** [comment] 2020-06-30 20:15
I realized I did not think to make sure I was looking at all tickets and not only open tickets, this can probably be closed safely as I see that there are many tickets regarding difficulties with intel graphics drivers.

Apologies for the duplicate.

**Comment by Calinou** [comment] 2020-06-30 20:22
Duplicate of #23069. Try updating your graphics driver to the latest version *provided by Intel*. Alternatively, start the Godot editor with the `--verbose` command-line argument, which can also mitigate the issue.

**Closed by Calinou** 2020-06-30 20:22 UTC
