### ISSUE TITLE
Script Editor Non-English Characters Problem

### ISSUE THREAD

**Issue by lacriment** [godotengine/godot#2867] opened 2015-11-22 09:42 UTC
I'm using a Turkish keyboard and Turkish keymap. When I press the Turkish characters on my keyboard it doesn't shows Turkish characters on script editor but it cause syntax error, "unknown character". So everytime I press turkish characters by mistake or by forgetting GDScript doesn't support utf-8 I have to open script file with another text editor and delete the unknown(turkish) characters.

**Comment by lacriment** [comment] 2015-11-22 09:43
ÜĞİŞÇÖüğşçöı these are the Turkish characters.

**Comment by akien-mga** [comment] 2015-11-22 11:23
Duplicate of #871.

**Closed by akien-mga** 2015-11-22 11:23 UTC
Labels: archived
