### ISSUE TITLE
Create Node Dialog: hangs for around 10s when open and using search

### ISSUE THREAD

**Issue by MikeSchulze** [godotengine/godot#73204] opened 2023-02-13 07:41 UTC
### Godot version

v4.0.rc1.official [8843d9ad3]

### System information

Windows 10, MacOS

### Issue description

I provide a plugin GdUnit4 with a lot of custom class implementations, by using `class_name`.

e.g. GdUnitTestSuite, which is inherited by many test classes.

When I try to open the `Create Node Dialog` by pressing the add icon in the scene editor, the dialog hangs for about 10s.
I can see all the engine nodes and my custom nodes.
When I use the filter, it hangs again every time I enter something and makes using the dialog bad
I guess this is relates to the massive increased loading time of script classes.

I want to exclude my plugin classes from the this Dialog.
On the latest beta version is used this pice of code to remove, but it not works on RC1 anymore

plugin.gd
```gdscript
func _fixup_node_inspector() -> void:
	var classes := PackedStringArray([
		"GdUnitTestSuite",
		"_TestCase",
		"GdUnitInspecor",
		"GdUnitExecutor",
		"GdUnitTcpClient",
		"GdUnitTcpServer"])
	for clazz in classes:
		remove_custom_type(clazz)

func _enter_tree():
   ...
   _fixup_node_inspector()
```

### Steps to reproduce

- Download the latest branch (master) of [GdUnit4](https://github.com/MikeSchulze/gdUnit4/archive/refs/heads/master.zip) and activate the plugin
- create a new scene
- using the add node button to open the Create Node Dialog

### Minimal reproduction project

N/A

**Comment by YuriSizov** [comment] 2023-06-22 11:00
This seems to be a duplicate of https://github.com/godotengine/godot/issues/27333, actually. So consolidating. Thanks for your report!

**Closed by YuriSizov** 2023-06-22 11:00 UTC
Labels: topic:gdscript, topic:editor, performance
