### ISSUE TITLE
"About" dialog window is misaligned.

### ISSUE THREAD

**Issue by milkowski** [godotengine/godot#19216] opened 2018-05-28 11:41 UTC
GUI dialogs in "About" dialog window are not formated properly when they are opened first time. On consecutive views they behave properly.

![image](https://user-images.githubusercontent.com/136565/40612829-541c7510-627c-11e8-8ceb-4b8a4025772f.png)

Godot 3.1 dev

Tested on Windows build.

Steps to reproduce:
1. Run Godot editor and open some/empty/new project
2. Go to menu Help->About
3. Click on the tabs inside, especially "Thirdparty License"

**Comment by bojidar-bg** [comment] 2018-05-28 12:27
Duplicate of #18940.

**Closed by bojidar-bg** 2018-05-28 12:27 UTC
