### ISSUE TITLE
Clicking on anything in the Project Tree prints an error in the console

### ISSUE THREAD

**Issue by inhalt120g** [godotengine/godot#93640] opened 2024-06-26 18:36 UTC
### Tested versions

v4.3.beta2.official [b75f0485b]

### System information

Godot v4.3.beta2 - macOS 14.5.0 - Vulkan (Forward+) - integrated Apple M1 - Apple M1 (8 Threads)

### Issue description

When I click on any clickable element in the IDE (an entry in the Project Tree, Godot build version, a file in the File System window…), an error gets printed to the console:
![image](https://github.com/godotengine/godot/assets/106015575/bd811990-97a0-45b7-a224-2d1ebd56aede)

### Steps to reproduce

I don't know what triggers it, but it gets triggered within the first few minutes of workin in Godot and once it's triggered, the only way for me to stop it is to restart Godot.

### Minimal reproduction project (MRP)

It's project independent.

**Comment by Chaosus** [comment] 2024-06-26 19:16
> v4.3.beta2.official

It's very old version of Godot - can you reproduce it on latest beta 2?

**Comment by JekSun97** [comment] 2024-06-26 19:29
Dublicate #93565

**Comment by Chaosus** [comment] 2024-06-26 19:38
Duplicate of https://github.com/godotengine/godot/issues/93565

**Closed by Chaosus** 2024-06-26 19:38 UTC
Labels: bug, topic:editor, regression, topic:gui
