### ISSUE TITLE
Unrelated Completion Suggestions

### ISSUE THREAD

**Issue by leogott** [godotengine/godot#73352] opened 2023-02-15 12:02 UTC
### Godot version

4.0 rc 1

### System information

Fedora 36

### Issue description

The completion suggestions are mostly completely unrelated results.
* **All of them contain the letters of the prompt in order**
* In the first ones, for some reason the last letter gets highlighted as matching the prompt
![grafik](https://user-images.githubusercontent.com/61663141/219020031-deaac828-6a2c-4148-9479-b5dcc43d51dd.png)
![grafik](https://user-images.githubusercontent.com/61663141/219020262-fe6ca5a3-3390-4b2c-b668-2019cd731cfb.png)
Notice somewhere in between the one (1) result actually containing `reset` as a substring.

Looks like fuzzy search went a bit overboard. Possibly the same underlying problem as #69912

### Steps to reproduce

1) create a new script
2) somewhere, for example in the _ready function body write `reset`

### Minimal reproduction project

N/A

**Comment by akien-mga** [comment] 2023-02-15 12:54
Duplicate of #63706. We ran out of time to finalize the improvements to completion for 4.0 (#65655), but this will be in 4.1 (and probably backported to 4.0.x because the results are indeed often quite unusable).

**Closed by akien-mga** 2023-02-15 12:54 UTC
