### ISSUE TITLE
Windows Export broken in 3.5.beta5

### ISSUE THREAD

**Issue by duarteroso** [godotengine/godot#61028] opened 2022-05-14 10:34 UTC
### Godot version

3.5.beta5

### System information

Windows 10

### Issue description

Exporting from `3.4.4` created a valid `.exe` that could be run
![3 4 4](https://user-images.githubusercontent.com/11413364/168421994-094e5603-1323-4611-ab7e-ebe0781be612.PNG)

Upgrading the project to `3.5.beta5`, exporting using the exact same export preset seems to not export the `data_{NAME}` folder
![3 5 beta5](https://user-images.githubusercontent.com/11413364/168422025-29b9aa7b-7329-4bfc-922a-37e6e64a2ba7.PNG)

When running the game with the exported `3.5.beta5` version, since the data is missing, nothing much show up...

### Steps to reproduce

Difficult to reproduce. I have tried a simple Hello World label but that worked.
Seeing the contents of the `data_{NAME}` folder, am unsure how to generate it in a simple project.

**Comment by anderlli0053** [comment] 2022-05-14 11:07
Is this not the duplicate of [this](https://github.com/godotengine/godot/issues/60753) issue, which is also pinned..??

**Comment by Sslaxx** [comment] 2022-05-14 11:25
See also https://github.com/godotengine/godot/pull/60752

**Comment by akien-mga** [comment] 2022-05-14 11:50
Duplicate of #60753.

**Closed by akien-mga** 2022-05-14 11:50 UTC
Labels: bug, topic:export
