### ISSUE TITLE
"Reload Current Project" prompts the user to open Project Manager

### ISSUE THREAD

**Issue by Mickeon** [godotengine/godot#60783] opened 2022-05-05 10:54 UTC
### Godot version

3.5 Beta 5

### System information

Windows 10

### Issue description

Reloading the current project asks the user if they want to open the Project Manager, despite it having not much to do with the operation.
![bfdb3880b6d18810abfd0756d8fdc9bc](https://user-images.githubusercontent.com/66727710/166908712-b1892073-aa37-4c38-8b28-8fa9cea5e2ca.gif)

Clicking on "Yes" reloads the project just fine, without ever showing the Project Manager.

This does **not** happen in Godot 3.3.3. The project reloads without any prompt.

### Steps to reproduce

Click on Project on the top-left, then click on "Reload Current Project".

### Minimal reproduction project

No need.

**Comment by akien-mga** [comment] 2022-05-05 11:13
Looks like an off by one error, it's using the next action ("Quit to Project List").

**Comment by akien-mga** [comment] 2022-05-06 06:33
As identified in https://github.com/godotengine/godot/pull/60804#issuecomment-1119149675 this is a regression from #59442, CC @Vitika9. The issue should also be fixed in `master`, not just in `3.x` as attempted in #60804.

**Comment by RedHeadphone** [comment] 2022-05-06 07:23
@akien-mga but this issue doesn't exist in master branch, am I missing something?

**Comment by akien-mga** [comment] 2022-05-06 07:38
Alright, then the bug is specific to the cherry-pick of #59442, I might have missed that there were differences and that the `master` version would not work as is.

**Comment by RedHeadphone** [comment] 2022-05-06 09:48
I might be wrong but this bug has nothing to with #59442 , the confirmation on 'reload project'/ 'run project manager' when files are saved was simply not from 3.x version.

**Closed** 2022-05-10 09:02 UTC
Labels: bug, topic:editor, good first issue, regression
