### ISSUE TITLE
Multiplayer Enet error

### ISSUE THREAD

**Issue by rieniter** [godotengine/godot#35605] opened 2020-01-27 00:16 UTC
**Godot version:**
3.1.2 Stable
**OS/device including version:**
Ubuntu 19
**Issue description:**
![2020-01-27_071149](https://user-images.githubusercontent.com/34160378/73144106-6af66b00-40d4-11ea-98b8-6693f4f97c8d.png)
I have tried to create a server and run it on ubuntu, but i always get this 
problem

**Comment by nathanwfranke** [comment] 2020-01-27 08:12
Can you post what motherboard you have (not sure if will make a difference) along with a reproduction project / code sample?

**Comment by rieniter** [comment] 2020-01-27 11:37
> Can you post what motherboard you have (not sure if will make a difference) along with a reproduction project / code sample?

I have following the sample code from this to create a test server:
https://docs.godotengine.org/en/3.1/tutorials/networking/high_level_multiplayer.html

And it worked well in debug without any problem. I'm using Windows 10 to debug this and try to export the test project to Linux x11 OS, then I run it in my Ubuntu 19 of VMware but always get above error when tried to open it in both normal or headless server

**Comment by rieniter** [comment] 2020-01-27 16:33
Edited: It look like that not worked on NAT vmware server as i keep get that errors, so i switch to local direct connect and worked well, but don't know above problem can happen on real network or not

**Comment by Calinou** [comment] 2020-02-02 18:04
Closing, as the error appears to be due to a network configuration issue per https://github.com/godotengine/godot/issues/35605#issuecomment-578833476.

**Closed by Calinou** 2020-02-02 18:04 UTC
