### ISSUE TITLE
CollisionObject2D _input_event don't emitted then scene has a canvas layer node

### ISSUE THREAD

**Issue by Summersay415** [godotengine/godot#44290] opened 2020-12-11 09:08 UTC
**Godot version:**

3.2.3.stable

**OS/device including version:**

GLES2, Ubuntu 20.04 LTS

**Issue description:**

See title.

**Steps to reproduce:**
1. Create some scene with CollisionObject2D with pickable option.
2. Add CanvasLayer and some Controls as childs.
3. Create script that print something to console when _input_event emitted and attach to scene at first step.
4. Run project and try click the CollisionObject2D. Nothing in console.

**Minimal reproduction project:**

[Del Me.zip](https://github.com/godotengine/godot/files/5678165/Del.Me.zip)

**Comment by madmiraal** [comment] 2020-12-12 08:43
Closing, because, as explained by @Zireael07 and @YeldhamDev, this is by design.

If you don't want the `Control` to intercept the mouse events, you can disable it through the [`mouse_filter`](https://docs.godotengine.org/en/stable/classes/class_control.html#class-control-property-mouse-filter) property.

**Closed by madmiraal** 2020-12-12 08:43 UTC
Labels: topic:gui, topic:physics

**Comment by Summersay415** [comment] 2020-12-14 11:45
Thanks
