### ISSUE TITLE
Multiline comment literal `"""` does not work in 4.0

### ISSUE THREAD

**Issue by azul372** [godotengine/godot#62330] opened 2022-06-23 02:25 UTC
### Godot version

4.0alpha10

### System information

Windows 10, GLES3, NVIDIA Quadro P2000

### Issue description

Godot's multiple line comments are not working in 4.0 alpha 10.

![image](https://user-images.githubusercontent.com/80684394/175192811-24eb3663-3cc1-4c65-ba1a-d451c1ff551c.png)

This code works perfectly in 3.4.x. Was there any change as to how multiple line comments work?

### Steps to reproduce

Just write multiple line comments with """ and you'll see the error aforementioned.

**Comment by akien-mga** [comment] 2022-06-23 07:09
GDScript doesn't have multiline comments, this syntax is actually multiline strings - and putting them standalone is basically the same as writing
```
extends Node2D

"hello world"
```

A standalone literal like this is not useful so now it's raising an error. In 3.x there was some workaround to allow this kind of standalone multiline string to mimic the Python multiline comments, maybe that code was lost in the rewrite.

**Comment by Maran23** [comment] 2023-01-04 07:02
Duplicate of https://github.com/godotengine/godot/issues/66577
I can confirm that this is still happening (0160fea).
\> `Unexpected "Literal" in class body`

With that said, is there an agreement whether we want to support this style or not?
If this is intended, we may want to think about a way to do documentation without excessive using of `#` (probably a proposal then).

**Closed** 2023-02-09 15:25 UTC
Labels: bug, topic:gdscript, regression
