### ISSUE TITLE
Unrecognised binary resource file error(s) with PBM files

### ISSUE THREAD

**Issue by nylnook** [godotengine/godot#14828] opened 2017-12-19 15:24 UTC
**Godot version:**
Archlinux 64b, Godot 3b1

**Issue description:**
When used in TextureButtons Click Masks, Netpbm or PNM files give `Unrecognised binary resource file error(s)` and `Condition err!=OK is true. Returned RES()` messages in the debugger.
Ans there is no choice but to use this format for creating click masks.

This can be just a result of not using the [correct subformat](https://github.com/godotengine/godot-docs/issues/909), or corrupted files.

This is a repeated issue from downstream https://github.com/flossmanualsfr/escoria/issues/9
See also #14700 for a sum-up in and a minimal project example
Theses errors are reported at least in HTML5 export.

**Comment by reduz** [comment] 2017-12-26 15:07
Yes, use PBM, not PNM, closing as this is not a bug.

**Comment by nylnook** [comment] 2017-12-26 16:35
I'm sorry to insist, I know you are overwhelmed by bugs, this maybe poorly formulated, but we are indeed using PBM files (see [here](https://github.com/flossmanualsfr/escoria/tree/master/device/scenes/second_scene/sprites/click_mask)), which is a sub-format of PNM, and the bug **is** happening, please see the minimal project example in #14700 ...

**Comment by nylnook** [comment] 2017-12-26 16:36
Please reopen, I can't...

**Comment by nylnook** [comment] 2017-12-28 08:43
@reduz, @akien-mga please ?

**Comment by Noshyaar** [comment] 2017-12-28 12:09
Can confirm that this issue is valid with `PBM` file.

**Comment by nylnook** [comment] 2017-12-28 14:17
Thank you @Noshyaar ! 
Do you mind to reopen also the siblings https://github.com/godotengine/godot-docs/issues/909 and #14830 ?
Cheers !

**Comment by reduz** [comment] 2017-12-28 14:21
The best fix would probably be to add the ability to import images as
images and deprecate bitmask/pbm

**Comment by nylnook** [comment] 2017-12-29 13:02
IMHO, if you plan to deprecate PBM files, you have 4 options:
- simply said the way to do it is to use a `Area2D > CollisionPolygon2D` structure as a workaround and document it. But it change the node structure, I don't know if it can work in all situations, and calling the physic engine every time is not so lightweight.
- Allow any image as a click mask and do the math from theses various sources to define in and out
- Allow to use TextureButton image alpha as a click mask (implement #5432), which should cover most of use case, but can be tricky in some situations (buttons with a halo, degradés..). But it's good to avoid another resource.
- Allow only 1 bit indexed image with only two colors: black and white (.png, .gif and .tiff for uncompressed data), which what I suggested in #14700. But document it.

Or combine several of theses options (for example alpha + indexed images)... I can help for documentation if the choice is clear to me. You can use the minimal example in #14700 to test.

Thanks for your work !

**Comment by Noshyaar** [comment] 2017-12-29 14:25
Have you tried this?: http://docs.godotengine.org/en/latest/classes/class_bitmap.html#class-bitmap-create-from-image-alpha

**Comment by reduz** [comment] 2018-01-06 19:39
PBM format is now gone, closing this.

**Closed** 2018-01-06 19:39 UTC
Labels: bug, confirmed, topic:core

**Comment by nylnook** [comment] 2018-01-08 09:21
Hi @reduz, and thanks a lot for your work ! 

But I tested this morning with a compiled Godot, and I'm afraid it doesn't work ... at least with PNG files... PNM format is rejected, I can choose any image file format for the click mask in the file explorer, but after it's choosed the Click Mask line still show <null> in the editor and it do not apply.

You can test with [this minimal example](https://github.com/godotengine/godot/files/1572105/click-masks.zip).

If you prefer I can open another bug report...
Keep up the good work !

**Comment by akien-mga** [comment] 2018-01-08 10:01
Yes please open another ticket for click masks not working properly with PNGs.

**Comment by Noshyaar** [comment] 2018-01-08 10:02
Well, it works if it's imported as BitMap and not Texture. I use the minimal example and it works as expected except dimension is flipped.

**Comment by nylnook** [comment] 2018-01-08 10:30
I just tested with .jpg, .tga and .svg, nothing is working for me... But before to report another bug, I'd like to understand your comment @Noshyaar ... 

I'm just cliking "Load" here in a Texture Button: 
![capture d ecran de 2018-01-08 11-26-15](https://user-images.githubusercontent.com/456282/34666906-e48effa2-f466-11e7-83a7-205d9f1b369b.png)

How do you do do it so it works ?

**Comment by Noshyaar** [comment] 2018-01-08 14:00
You have to select the file you want to use as a mask (must not be the same as Texture), go to Import dock, choose import as BitMap, finally click Reimport.

After that, load that file as Click Mask as in the image.

**Comment by reduz** [comment] 2018-01-08 14:04
I suppose documentation and class reference should be updated to reflect this

**Comment by nylnook** [comment] 2018-01-08 14:51
Thanks for your answer, I got it (I see the resource named or see the image in the editor at the Click Mask line)...

But I'm sorry:
1. If I use the import dock, it's mostly working, but as you said dimension is flipped (rotated 90°) (I never used that dock before, after 2 Godot projects of several weeks !)
2. If I use the button "Create a new resource in memory and edit it" in the Inspector dock, then select Bitmap, then provide a path and a name, then load in the click mask button, the click mask is not working I can click everywhere in the texture surface and click respond, even in the black parts of the click mask...
3. that's really confusing (why in this case should we import then open - plus provide a path to select the same file later - when everywhere else simply using "load" is working)...  IMHO, the Godot project will have bug reports about that even if it's documented... Or remove the button ;p

Is that several bugs, only one, or should we reopen this one ?

Thanks again
