### ISSUE TITLE
Godot doesn't allow exporting a enum variable using a singleton constant enum

### ISSUE THREAD

**Issue by ygypt** [godotengine/godot#60314] opened 2022-04-17 04:30 UTC
### Godot version

3.4.4

### System information

Windows 11

### Issue description

normally if you want to export a variable to the editor with an enumerator dropdown tool, you can do:
```py
enum FooEnum {
  FOO,
  BAR,
  QUX,
}

export (FooEnum) var Bar := FooEnum.FOO
# the editor will now have an exported dropdown menu instead of an integer field for Bar
```

additionally, if you have a singleton script added to the Autoload, you can declare a enum constant that inherits the name of the singleton:
```py
QuxSingleton.gd
enum {
  FOO,
  BAR,
  QUX,
}
# this allows you to access the enum globally using QuxSingleton.FOO, basically a global constant
```

but unfortunately you cannot combine these features; attempting to export a variable using the singleton name like this results in an error:
```py
export (QuxSingleton) var Bar := QuxSingleton.FOO
#  built-in:8 - Parse Error: The export hint isn't a resource type.
```

this is probably because it's treating QuxSingleton as a class and not as an enum, but it would be nice to see that functionality added, bc the workaround is to name the enumerator `export (QuxSingleton.FooEnum)`, which ultimately isnt the worst thing in the world but it feels inconsistent

### Steps to reproduce

create a script and add it to autoload as a singleton:
```py
QuxSingleton.gd
enum {
  FOO,
  BAR,
  QUX,
}
```
create a new Node and attach a script:
```py
FooNode.gd
export (QuxSingleton) var Bar := QuxSingleton.FOO
```
witness error

**Comment by Calinou** [comment] 2022-04-17 16:18
Related to https://github.com/godotengine/godot/issues/14681.

**Comment by kleonc** [comment] 2022-05-11 20:07
Duplicate of #49220.

That's not a bug, it's expected behavior (more info in the linked issue).

**Closed** 2022-05-11 20:10 UTC
Labels: topic:gdscript

**Comment by msaadullah37** [comment] 2025-07-27 14:27
Duplicate of #49220.
that's not a bug, it's expected behaviour ( more info in the linked issue)
