### ISSUE TITLE
New directories aren't read/scanned without restarting editor

### ISSUE THREAD

**Issue by Qu-inn** [godotengine/godot#9207] opened 2017-06-16 04:21 UTC
**Operating system or device - Godot version:**
3.0, master branch, has been an issue for two months at least, including on current revision (7a8a789)
Arch Linux (x11), Windows 10

**Issue description:**
New directories (e.g. created when saving a new scene) are not updated/read correctly in the FileSystem panel, until the editor is restarted.

The new directory appears in the directory tree (top half of FileSystem) but when selected, the file contents (lower panel) appear as if the root (res://) is selected. Likewise, trying to mark the new dir as a favourite adds the root as a favourite.

**Steps to reproduce:**
Create a new folder and save a resource in it with the normal file chooser dialog.
Select the new folder in the FileSystem panel

**Comment by bojidar-bg** [comment] 2017-06-16 09:35
Aaand, yet another duplicate of #3662. It has been around long before 3.0..

**Closed by bojidar-bg** 2017-06-16 09:35 UTC
