### ISSUE TITLE
Setting emulate_touch_screen in project settings, results in editor simulating touch screen as well

### ISSUE THREAD

**Issue by kubecz3k** [godotengine/godot#4392] opened 2016-04-21 15:25 UTC
**Operating system or device:**
Ubuntu 15.10

**Issue description** (what happened, and what was expected):
In project settings if you set `Display->emulate_touch_screen` to true, then Godot editor will emulate touch screen as well. As a result of this it's impossible to select multiple lines of text in Help window. 
![cantselectlines](https://cloud.githubusercontent.com/assets/6129594/14714548/b7ea1ad2-07e5-11e6-9393-9a444593b0a2.gif)
Probably there are also other side effects of this setting.

**Steps to reproduce:**
1. Go into `Scene->Project Settings`
2. `Display` section.
3. Check `emulate_touch_screen`
4. Restart Godot Editor
5. Open Godot help window
6. Try to select multiple lines

**Link to minimal example project** (optional but very welcome):

**Comment by bojidar-bg** [comment] 2016-04-21 19:59
Note that the same happens with splash_screen setting :smile:

**Comment by akien-mga** [comment] 2016-06-07 07:38
Closing as duplicate of #4739, it's a more global editor bug.

**Closed by akien-mga** 2016-06-07 07:38 UTC
Labels: bug, topic:editor, usability
