### ISSUE TITLE
Setting rect_min_size.x in _ready() has no effect on Control that is a child of ScrollContainer

### ISSUE THREAD

**Issue by mitchcurtis** [godotengine/godot#28463] opened 2019-04-27 11:21 UTC
**Godot version:**
v3.1

**OS/device including version:**
MacBook Pro
macOS 10.14.4

**Issue description:**
I have the following scene:

<img width="229" alt="Screen Shot 2019-04-27 at 1 17 56 PM" src="https://user-images.githubusercontent.com/6002340/56848988-ed0bf600-68ee-11e9-8ad8-ad2b6f593fd1.png">

I'm creating a grid of items within a SrollContainer. In InventoryGrid's script, I have the following code:

```
func _ready():
    # We don't care how wide we are; that's up to our parent.
    # The parent should ensure that its width is a multiple of item_size, though,
    # because otherwise there will be extra, unused space on the right-hand side.
    # Note that we do control our height: see fill_grid().
    rect_size.x = get_parent_control().rect_size.x# - get_parent_control().get_h_scrollbar().rect_size.x
    fill_grid()
```

If I use rect_min_size.x instead of rect_size.x, the grid is not resized. If I use rect_size.x, it works. This is confusing, because in the editor, it's not possible to set the size of InventoryGrid via rect_size: you have to use rect_min_size or your changes aren't respected.

What makes it even more confusing is that further down in fill_grid(), I have to use rect_min_size.y or the grid won't resize vertically (and fill_grid() is called in _ready()):

`    rect_min_size.y = rows * item_size`

So the issue, to me, is that rect_min_size.x has no effect in _ready().

**Minimal reproduction project:**
[inventory-grid.zip](https://github.com/godotengine/godot/files/3123797/inventory-grid.zip)

**Comment by mitchcurtis** [comment] 2019-04-27 11:48
And actually the rect_size reverts back to its original value shortly afterwards, so it seems that it's necessary to set **both**:

 ```
    rect_size.x = get_parent_control().rect_size.x# - get_parent_control().get_h_scrollbar().rect_size.x
    rect_min_size.x = rect_size.x
```

**Comment by guilhermefelipecgs** [comment] 2019-04-27 13:25
Actually, any `Control` node that is children of a container will have their size determined by container, this means you can't edit `rect_size` directly, only `rect_min_size` will take effect.

Running your example, we can confirm this by going to the Remote tab:
![Captura de tela de 2019-04-27 10-19-36](https://user-images.githubusercontent.com/1387165/56850230-0e141d00-68d6-11e9-91f8-711e3f1c840e.png)
![Captura de tela de 2019-04-27 10-19-55](https://user-images.githubusercontent.com/1387165/56850231-0e141d00-68d6-11e9-963c-d90c8944d958.png)

**Comment by guilhermefelipecgs** [comment] 2019-04-27 13:29
If you want to create a grid, I suggest you to use `GridContainer`. Probabily you got confused about that because your logic to fill the grid may be wrong.

**Comment by guilhermefelipecgs** [comment] 2019-04-27 13:33
Sorry, I think you're right.

**Comment by guilhermefelipecgs** [comment] 2019-04-27 13:42
ok, this is not a bug indeed, your `fill_grid` are not right, if I change the fill grid with a button you can easily see the difference:
![Captura de tela de 2019-04-27 10-41-43](https://user-images.githubusercontent.com/1387165/56850435-1588f580-68d9-11e9-875b-fefa0e3625a0.png)
![Captura de tela de 2019-04-27 10-41-26](https://user-images.githubusercontent.com/1387165/56850441-1de13080-68d9-11e9-9c96-ed0f39ce32c0.png)
![Captura de tela de 2019-04-27 10-41-39](https://user-images.githubusercontent.com/1387165/56850442-1e79c700-68d9-11e9-9df3-b53f519619e4.png)

**Comment by mitchcurtis** [comment] 2019-04-27 13:52
Sorry, but I don't see the connection between that and my issue.

**Comment by guilhermefelipecgs** [comment] 2019-04-27 13:55
You report that `rect_min_size` doesn't take effect when called on `_ready` function, but they actually works  as expected.

**Comment by guilhermefelipecgs** [comment] 2019-04-27 13:57
See here:
![Captura de tela de 2019-04-27 10-19-36](https://user-images.githubusercontent.com/1387165/56850590-2fc3d300-68db-11e9-89fb-8cbc60ca1216.png)
![Captura de tela de 2019-04-27 10-19-55](https://user-images.githubusercontent.com/1387165/56850591-2fc3d300-68db-11e9-8d18-0cbf3d6eac30.png)
Reading the remote tab you can see that.

**Comment by groud** [comment] 2019-04-27 14:05
That's expected behavior, children of container get their size fixed by their parent.
So setting rect_size will be overridden.

**Closed by groud** 2019-04-27 14:05 UTC
