### ISSUE TITLE
Android custom build 3.1

### ISSUE THREAD

**Issue by cemeai** [godotengine/godot#37899] opened 2020-04-15 09:34 UTC
**Godot version:** 3.1

**OS/device including version:** macOS Mojave 10.14.6

**Issue description:** Trying to run the custom build for android, to generate the release and debug apk's. the .so are being generated in the bin folder but when i run gradlew build it return succes but it doesn't generate the apk

**Steps to reproduce:** 
ANDROID_HOME=/Users/name/Library/Android/sdk
ANDROID_NDK_HOME=/Users/name/Library/Android/sdk/ndk/21.0.6113669/
ANDROID_NDK_ROOT=/Users/name/Library/Android/sdk/ndk/21.0.6113669/
run 
scons platform=android target=release android_arch=armv7
scons platform=android target=release android_arch=arm64v8
cd platform/android/java
./gradlew build

Response:
> Configure project :
WARNING: Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.
It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html

> Task :lint
Ran lint on variant debug: 8 issues found
Ran lint on variant release: 8 issues found
Wrote HTML report to file:///Users/name/Documents/godot_3.1/platform/android/java/build/reports/lint-results.html
Wrote XML report to file:///Users/name/Documents/godot_3.1/platform/android/java/build/reports/lint-results.xml

Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.1.1/userguide/command_line_interface.html#sec:command_line_warnings

I know this may be an old issue but i can't work it out. Maybe point to the right direction.

**Comment by akien-mga** [comment] 2020-04-15 10:11
Those are only warnings, not errors. The build should still succeed, or there should be an error message further up or down.

**Comment by akien-mga** [comment] 2020-04-15 10:18
I tried on Linux with NDK r21 and the `3.1` branch but I can't reproduce it, the APKs are properly generated as `bin/android_debug.apk` and `bin/android_release.apk`. (Note that your commands only build the release libraries, so the `android_debug.apk`, though generated, will be invalid.)

**Comment by cemeai** [comment] 2020-04-15 16:07
hmm I have no idea what is going on then all i see in the bin folder are the .so for each arch but no apk. I'll try downloading the repo again

**Closed** 2021-01-05 10:21 UTC
Labels: platform:android, topic:buildsystem
