### ISSUE TITLE
`not` statements or `and` statements do not resolve operands to bool automatically

### ISSUE THREAD

**Issue by tavurth** [godotengine/godot#66396] opened 2022-09-25 11:28 UTC
### Godot version

4.beta.1

### System information

MacBook Pro (13-inch, 2019) 2.4 GHz Quad-Core Intel Core i5

### Issue description

```gdscript
var my_dict = {}
if not my_dict:
  pass
```

The above will throw a compile error:

<img width="515" alt="Screenshot 2022-09-25 at 15 27 48" src="https://user-images.githubusercontent.com/100964/192141117-259d41e0-60cb-4a97-a1f3-48beed7ad9af.png">

### Steps to reproduce

```gdscript
var my_dict = {}
if not my_dict:
  pass
```

```gdscript
var my_str = ""
if not my_str:
  pass
```

```gdscript
if not self.name:
  pass
```

This was previously working in Godot 3.5 but not in Godot 4.x

**Comment by KoBeWi** [comment] 2022-09-25 18:25
Duplicate of #44688

**Closed by KoBeWi** 2022-09-25 18:25 UTC
Labels: bug, topic:gdscript
