### ISSUE TITLE
GraphEdit.get_connection_list() returns dict with `from_node` and `to_node` keys instead of `from` and `to` according to documentation

### ISSUE THREAD

**Issue by adrientremblay** [godotengine/godot#86780] opened 2024-01-04 13:00 UTC
### Tested versions

- Reproduced in version 4.2.1 stable

### System information

Linux Mint - Version 4.2.1 stable

### Issue description

The documentation states that GraphEdit.get_connection_list "Returns an Array containing the list of connections. A connection consists in a structure of the form `{ from_port: 0, from: "GraphNode name 0", to_port: 1, to: "GraphNode name 1" }`."

Instead it seems to return a result in the format `{ from_port: 0, **from_node**: "GraphNode name 0", to_port: 1, **to_node**: "GraphNode name 1" }`.

### Steps to reproduce

- Create a minimal GraphEdit node with Nodes and connections
- Call get_connection_list() in the GraphEdit
- Observe that the format the dict is { from_port: 0, from_node: "GraphNode name 0", to_port: 1, to_node: "GraphNode name 1" }.

### Minimal reproduction project (MRP)

N/A

**Comment by AThousandShips** [comment] 2024-01-04 13:01
Duplicate of https://github.com/godotengine/godot-docs/issues/8625

**Closed by AThousandShips** 2024-01-04 13:01 UTC

**Comment by adrientremblay** [comment] 2024-01-04 13:02
@AThousandShips Oh crap! Didn't see that
