### ISSUE TITLE
Unable to open C# script from Editor

### ISSUE THREAD

**Issue by daredloco** [godotengine/godot#88608] opened 2024-02-20 22:30 UTC
### Tested versions

- Reproducible in: v4.3.dev3.mono.official [36e943b6b]
- Not Reproducible in: v4.2.1.stable.mono.official [b09f793f5]

### System information

Godot v4.3.dev3.mono - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3050 Laptop GPU (NVIDIA; 31.0.15.3179) - 11th Gen Intel(R) Core(TM) i5-11400H @ 2.70GHz (12 Threads)

### Issue description

If you try to open a script file either from the Projects "datasystem" [Figure 1] or from the nodes list [Figure 2] the following error will be shown:
> /root/godot/modules/mono/editor/GodotTools/GodotTools/GodotSharpEditor.cs:279 - Error when trying to run code editor: VisualStudio. Exception message: 'An error occurred trying to start process 'C:/Apps/Godot/Test/GodotSharp/Tools\GodotTools.OpenVisualStudio.exe' with working directory 'C:\OwnGames\WastelandWanderer'. Das System kann die angegebene Datei nicht finden.'

Works fine if you open the Solution from the Windows Filemanager.

![errors](https://github.com/godotengine/godot/assets/60240491/fac2ee0f-a962-41aa-8c17-d3d4d4b81475)

### Steps to reproduce

1) Create a new project with v4.3.dev3.mono.official [36e943b6b]
2) Try to open a C# script with a double click on it or clicking the "script icon" inside the scene nodes
3) Error message is shown in Output

### Minimal reproduction project (MRP)

Not needed as it is not project related. (Happens with any project if you try to open a C# script)

**Comment by Cass-dev-web** [comment] 2024-02-20 22:35
My German is a bit rusty, but I'm guessing that would mean that the system cannot find the file which you're trying to access, meaning something must've happened to the file in your project directory (also I think you only have to click once on the project tree's script icons to open them). Can you check your project directory and verify the existence of these scripts?

**Comment by paulloz** [comment] 2024-02-20 22:37
Duplicate of
- #88447
- #88448

**Comment by daredloco** [comment] 2024-02-20 22:38
Sure thing I can give you further informations.
The files are in the projects folder, they, and the solution, can be opened with Visual Studio just fine. In fact the project also builds just fine, so no missing scripts or something like that.
They can also be opened just fine with v4.2.1.stable.mono.official [b09f793f5] so there doesn't seem to be a problem with the project or its structure.

**Closed** 2024-02-20 22:42 UTC
Labels: bug, topic:dotnet
