### ISSUE TITLE
ERROR: Vulkan: Cannot submit graphics queue. Error code: VK_ERROR_DEVICE_LOST

### ISSUE THREAD

**Issue by lorenuars19** [godotengine/godot#74774] opened 2023-03-11 15:46 UTC
### Godot version

Godot Engine v4.0.stable.official.92bee43ad

### System information

Vulkan API 1.2.194 - Forward+ - Using Vulkan Device #0: Intel - Intel(R) Iris(R) Xe Graphics

### Issue description

Crash after using engine for about 30 seconds

### Steps to reproduce

open any project in godot 4 on my computer with an intel irisXE graphics intel i7-1165G7 on an asus zenbook UX425EA.317 on windows 11 10.0.22621
with arc drivers at version 30.0.101.1003

### Minimal reproduction project

Just any project

EDIT : Compiled the 4.0 branch on this system, seems to be fixed in 4.0.1rc

**Comment by clayjohn** [comment] 2023-03-13 18:31
I see you reopened this issue after closing. Did it come up again in 4.0.1rc?

**Comment by lorenuars19** [comment] 2023-03-13 19:05
No because I'm not sure it is fixed because it was not a `release` build
But, hopefully that was fixed and won't come up ever again
And I also forgot to mention that when I did the first build on the master branch there so much errors and it crashed a lot
And between the build on master branch and the 4.0 branch I did use DDU and completely reinstalled the intel drivers and even tried older versions and legacy drivers, but nothing worked with the master build, and the 4.0 stable official build

So, all in all, I think the bug was fixed in 4.0.1rc but not sure since I did change other stuff
I will update this issue if I find anything else

**Comment by clayjohn** [comment] 2023-03-13 20:03
Hmm. In that case I think I will still close this. 

I think this is actually a duplicate of https://github.com/godotengine/godot/issues/71929 which references many open reports which contain more clear details about how to reproduce the bug. 

I think it is likely just chance that 4.0.1rc isn't crashing for you as this issue appears to come up quite randomnly. If you have more details to share, please share them by adding a comment to https://github.com/godotengine/godot/issues/71929

**Closed by clayjohn** 2023-03-13 20:03 UTC
Labels: bug, topic:rendering, needs testing

**Comment by lorenuars19** [comment] 2023-03-14 08:06
oh thanks for linking the tracker I did not find it earlier

**Comment by tremisabdoul** [comment] 2023-03-17 22:55
![image](https://user-images.githubusercontent.com/75373856/226066001-b0bbf8d5-fdce-47b5-9f4a-229f8bcc1bd9.png)
I have the same problem i apprear today after an update of my drivers https://www.intel.com/content/www/us/en/download/762755/intel-6th-10th-gen-processor-graphics-windows.html

**Comment by tremisabdoul** [comment] 2023-03-17 22:58
@Calinou sry for the ping but that's an closed issue so i don't think that an admin will be notified of it

**Comment by SylviaChalencon** [comment] 2023-04-03 16:24
I have the same error! Did you find a solution @tremisabdoul ?
<img width="985" alt="error_godot_vk_lost" src="https://user-images.githubusercontent.com/29229733/229569929-4a68ee08-e19e-4dea-ba87-e09b3a30c076.png">

**Comment by Otamendy-N** [comment] 2023-05-24 00:47
Hi there, same error here, after a few seconds of running the game:
![image](https://github.com/godotengine/godot/assets/45830169/25cb9921-43f9-4612-8307-ff09d732d10b)

**Comment by Calinou** [comment] 2023-05-24 09:44
- This issue is now being tracked in https://github.com/godotengine/godot/issues/71929.

**Comment by mxaddict** [comment] 2023-05-25 16:45
```
ERROR: Vulkan: Cannot submit graphics queue. Error code: VK_ERROR_DEVICE_LOST
   at: swap_buffers (drivers/vulkan/vulkan_context.cpp:2357)
ERROR: Vulkan: Cannot submit graphics queue. Error code: VK_ERROR_DEVICE_LOST
   at: swap_buffers (drivers/vulkan/vulkan_context.cpp:2357)
   ```

Also getting this error on `4.0.2.stable.arch_linux`

```
Vulkan API 1.3.236 - Forward+ - Using Vulkan Device #0: NVIDIA - NVIDIA GeForce RTX 2080 Ti
```

**Comment by Calinou** [comment] 2023-05-25 20:28
- This issue is now being tracked in https://github.com/godotengine/godot/issues/71929.
