### ISSUE TITLE
Particle 3d issues

### ISSUE THREAD

**Issue by gamergamesz** [godotengine/godot#10234] opened 2017-08-10 17:31 UTC
win 10 i7 960m
![screenshot 75](https://user-images.githubusercontent.com/13883739/29183186-5cd22912-7e1f-11e7-988f-64e8da6f406b.png)
color and hue variation and animation doesn't seems to have any effect in particle material
plus align and rotation is also broken
plus transparency is also seems to be broken
plus initial velocity at 0 makes it flicker

**Comment by Zylann** [comment] 2017-08-10 17:48
Coloring is potentially duplicate of  #9781
Flickering when velocity is 0 is duplicate of #10183
Rotation related to #10182

**Comment by kubecz3k** [comment] 2017-08-10 17:48
guys please wait I will create a proper tracker

**Closed** 2019-08-27 04:48 UTC
Labels: bug, discussion, topic:rendering
