### ISSUE TITLE
GPUParticles3D: enabling standard material particles billboard creates an outsider single instance of the pass mesh at origin.

### ISSUE THREAD

**Issue by jcarlosrc** [godotengine/godot#74690] opened 2023-03-09 21:58 UTC
### Godot version

4.0 Stable

### System information

Ubuntu 22.04

### Issue description

The issue comes from using GPUParticles3D. Enabling Particle Billboard option to the standard material of the mesh pass creates a single instance of the mesh at origin. This instance even casts shadows but is not visible. It appears everytime the particles node  starts emitting. Of course this instance does not belong to the particles themselves.
In the video, we can already see a shadow. It comes from this "ghost" instance. It appears everytime the particle systems restars.

https://user-images.githubusercontent.com/8985409/224169519-dd47aba4-6b10-4d45-bea2-55b179a04d46.mp4

### Steps to reproduce

Add a GPUParticles3D node. Assign a standard material to the mesh pass and enable particle billboard. There will appear an outsider instance of the pass mesh at origin everytime the particle system restarts.

### Minimal reproduction project

[particles_billboard_bug.zip](https://github.com/godotengine/godot/files/10936399/particles_billboard_bug.zip)

**Comment by clayjohn** [comment] 2023-03-09 23:14
Duplicate of https://github.com/godotengine/godot/issues/72650

**Closed by clayjohn** 2023-03-09 23:14 UTC
