### ISSUE TITLE
Android 3D export does not run on Adreno chipsets

### ISSUE THREAD

**Issue by masonjoyers** [godotengine/godot#14928] opened 2017-12-22 05:56 UTC
**Godot version:**
3.0 Beta 2 various build dates, and self compiled and daily builds attempt

**OS/device including version:**
Windows 10 Pro
Android 7.1.1 on Samsung SM-N950U

**Issue description:**
App installs, Godot splash screen displays, then error that app has stopped. Full console output is here: https://pastebin.com/S9ATF74H

**Steps to reproduce:**
Choose any project and export to Android

**Minimal reproduction project:**
Simple test cube

**Comment by volzhs** [comment] 2017-12-22 07:12
logs from `adb logcat` will help better to find out what problem is.
these logs from godot editor don't give much information.

**Comment by sionroberts** [comment] 2017-12-22 11:48
I have exactly the same problem, Beta 1 was ok. Here is my logcat
[godot3b2.log](https://github.com/godotengine/godot/files/1582396/godot3b2.log)

Thanks!

**Comment by gattila** [comment] 2017-12-22 16:33
I also have problem with android export, if I try to display 3D content. 2D export is Ok.

Android version 6.0, phone is Xiaomi Redmini Note 3 Plus.
The system want to send the following error log information:

*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'Xiaomi/kate/kate:6.0.1/MMB29M/7.12.14:user/release-keys'
Revision: '0'
ABI: 'arm'
pid: 18142, tid: 18183, name: GLThread 801  >>> org.godotengine.playground <<<
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x640
    r0 00000190  r1 00000000  r2 ab20fd38  r3 00000023
    r4 ab22b1d0  r5 00000004  r6 00000001  r7 00000000
    r8 00000000  r9 aba477c8  sl 00000001  fp f3e94140
    ip 00000000  sp f3e94050  lr e8be898b  pc e8c1a8ca  cpsr 60070030

backtrace:
    #00 pc 001bd8ca  /system/vendor/lib/egl/libGLESv2_adreno.so (_ZN9EsxCmdMgr16GfxMemReferencedEP9EsxGfxMem13EsxAccessType+41)
    #01 pc 0018b987  /system/vendor/lib/egl/libGLESv2_adreno.so (_ZNK10A5xProgram25GenerateShaderCBSlotStateEP10A5xContext13EsxCmdBufType23EsxCompiledHwShaderTypejP20A5xShaderCBSlotState+518)
    #02 pc 00189c1f  /system/vendor/lib/egl/libGLESv2_adreno.so (_ZN11A5xPipeline13WriteUboStateEP10A5xContext13EsxCmdBufType23EsxCompiledHwShaderTypejP14A5xStateBuffer+126)
    #03 pc 0019867d  /system/vendor/lib/egl/libGLESv2_adreno.so (_ZN10A5xContext29WriteConstantBufferStateGroupE13EsxCmdBufTypej+28)
    #04 pc 001a82ad  /system/vendor/lib/egl/libGLESv2_adreno.so (_ZN10A5xContext13ValidateStateEPK17EsxDrawDescriptor+1516)
    #05 pc 001a8805  /system/vendor/lib/egl/libGLESv2_adreno.so (_ZN10A5xContext18HwValidateGfxStateEPK17EsxDrawDescriptor+4)
    #06 pc 000ed567  /system/vendor/lib/egl/libGLESv2_adreno.so (_ZN10EsxContext16ValidateGfxStateEPK17EsxDrawDescriptor+454)
    #07 pc 000e2625  /system/vendor/lib/egl/libGLESv2_adreno.so (_ZN10EsxContext21DrawElementsInstancedE11EsxPrimTypej10EsxPixTypePKvj+324)
    #08 pc 000ccee1  /system/vendor/lib/egl/libGLESv2_adreno.so (_ZN10EsxContext14GlDrawElementsEjijPKv+64)
    #09 pc 000c3503  /system/vendor/lib/egl/libGLESv2_adreno.so (glDrawElements+34)
    #10 pc 00626f84  /data/app/org.godotengine.playground-2/lib/arm/libgodot_android.so (_ZN20RasterizerSceneGLES316_render_geometryEPNS_10RenderList7ElementE+852)
    #11 pc 00623ac8  /data/app/org.godotengine.playground-2/lib/arm/libgodot_android.so (_ZN20RasterizerSceneGLES312_render_listEPPNS_10RenderList7ElementEiRK9TransformRK12CameraMatrixjbbbbb+10716)
    #12 pc 0063a62c  /data/app/org.godotengine.playground-2/lib/arm/libgodot_android.so (_ZN20RasterizerSceneGLES312render_sceneERK9TransformRK12CameraMatrixbPPN15RasterizerScene12InstanceBaseEiP3RIDiSB_iSA_SA_SA_SA_i+5372)
    #13 pc 0129914c  /data/app/org.godotengine.playground-2/lib/arm/libgodot_android.so (_ZN17VisualServerScene13_render_sceneE9TransformRK12CameraMatrixb3RIDjS4_S4_S4_i+4508)
    #14 pc 01297f44  /data/app/org.godotengine.playground-2/lib/arm/libgodot_android.so (_ZN17VisualServerScene13render_cameraE3RIDS0_7Vector2S0_+568)
    #15 pc 012afee4  /data/app/org.godotengine.playground-2/lib/arm/libgodot_android.so (_ZN20VisualServerViewport14_draw_viewportEPNS_8ViewportEN13ARVRInterface4EyesE+516)
    #16 pc 012b1124  /data/app/org.godotengine.playground-2/lib/arm/libgodot_android.so (_ZN20VisualServerViewport14draw_viewportsEv+1076)
    #17 pc 0128c540  /data/app/org.godotengine.playground-2/lib/arm/libgodot_android.so (_ZN18VisualServerRaster4drawEb+96)
    #18 pc 000d0640  /data/app/org.godotengine.playground-2/lib/arm/libgodot_android.so (_ZN4Main9iterationEv+1120)
    #19 pc 00086658  /data/app/org.godotengine.playground-2/lib/arm/libgodot_android.so (_ZN10OS_Android17main_loop_iterateEv+20)
    #20 pc 000970a0  /data/app/org.godotengine.playground-2/lib/arm/libgodot_android.so (Java_org_godotengine_godot_GodotLib_step+216)
    #21 pc 0034426d  /data/app/org.godotengine.playground-2/oat/arm/base.odex (offset 0x221000) (void org.godotengine.godot.GodotLib.step()+72)
    #22 pc 00347be1  /data/app/org.godotengine.playground-2/oat/arm/base.odex (offset 0x221000) (void org.godotengine.godot.GodotView$Renderer.onDrawFrame(javax.microedition.khronos.opengles.GL10)+84)
    #23 pc 72f3e865  /data/dalvik-cache/arm/system@framework@boot.oat (offset 0x24b9000)

**Comment by gattila** [comment] 2017-12-22 17:12
Steps to reproduce:
1. Create an empty project, copy the dae file and the texture to the project folder (another bug on windows: file locked, but it is a minor issue)
2. Add a spatial as root node. Rename it as Main
3. Drag a dae file to the screen.
4. Click to the media icon on the tree, and confirm new inherited.
5. Save a new scene as Ship.tscn.
6. Edit the mesh, add new material, set the albedo.
7. Save the screen again.
8. Go to main screen. delete the original Scene Root under the Spatial.
9. Add a new Ship.tscn to the scene.
10. Add a Spatial Camera to the main screen. Set it enabled and current.
11. Save the main screen and set it to main screen.
12. Start the application. The program will display your 3d model.
13. Export as apk. Install it to your phone.
14. Run your app on your phone.

I tried it with anoher DAE file and with LG Leon too, with same result.

**Comment by gattila** [comment] 2017-12-22 17:15
And it was same as with beta 1 and alpha.

I also created a demo app here:
https://github.com/gattila/gamedemo

It works fine on my two phones, except the lates menu item, the simple 3D animation. It failed with same error.

**Comment by Zireael07** [comment] 2017-12-22 17:16
@gattila: There are a number of known crash/freeze issues with Adreno devices. I can see (from the log) that the Xiaomi is an Adreno device, is the Leon an Adreno device too?

**Comment by gattila** [comment] 2017-12-22 18:10
Yes, it uses Adreno too. Unfortunately it is a widely used GPU on Android.

**Comment by masonjoyers** [comment] 2017-12-22 20:51
Is this a bug that is planned to be fixed?

**Comment by akien-mga** [comment] 2018-01-05 15:04
This is actually a duplicate of #12816.

**Closed by akien-mga** 2018-01-05 15:04 UTC
Labels: bug, platform:android, topic:rendering
