### ISSUE TITLE
offer hint/info when shared resources are used

### ISSUE THREAD

**Issue by razcore-art** [godotengine/godot#6922] opened 2016-10-26 00:13 UTC
Sometimes is difficult to find a bug in the code just because it turns out all you had to do is make some resources unique. I like how blender offers info on how many times a certain resource is used and I think godot can benefit from something like this as well.

Example gotcha which isn't easy to detect: make an Area2D with CollisionShape2D and set the Shape parameter, Duplicate the Area2D and reuse it (say you have multiple objects that have the same Shape, but different scaling). Let's say we have 10 of these objects but 2 of them have are smaller, they still look the same so the Shape can work with them but it just needs to have different extents. We don't want to use scale here cause it might involve physics etc. (and if it isn't Area2D maybe it's Static2D, it's the same).

Problem is, if I make a script with an export var called scale_extents for example so that I can calculate different dimensions for Shape, then all of the Area2D nodes will be affected and it isn't easy to remember which resource is being reused.

A counter in the inspector on the property with reused resource would be nice, something like blender has perhaps

**Comment by kubecz3k** [comment] 2017-11-08 10:37
I would add the indicator to the resources that are unique, since by default all resources are shared.

**Comment by Zireael07** [comment] 2017-11-08 11:08
Yeah, I think this should be closed and #9037 reopened.

**Comment by Noshyaar** [comment] 2018-04-07 05:30
Still reproducible/relevant in 3.1 master 3ad9e47 : there's not yet a clear indication whether a resource is shared or unique.

**Comment by mitchcurtis** [comment] 2019-04-21 08:25
This is so confusing if you're new to Godot. The documentation is already sparse enough; having hidden behaviour like this just makes it that much harder:

https://github.com/godotengine/godot/issues/28246

**Comment by akien-mga** [comment] 2020-05-26 11:24
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!

**Closed by akien-mga** 2020-05-26 11:24 UTC
Labels: feature proposal, topic:editor, usability
