### ISSUE TITLE
Android Build Error

### ISSUE THREAD

**Issue by carlosmarti** [godotengine/godot#2648] opened 2015-10-21 00:23 UTC
When i try to build the android platform with scons on the command prompt using this (scons platform=android) it terminates the build because it seems that it is missing a file. This is what the command prompt displays

scons platform=android
scons: Reading SConscript files ...
MSVC Not detected, attempting mingw.
Godot Android!!!!!
scons: done reading SConscript files.
scons: Building targets ...
C:\Program Files\android-ndk\platforms/toolchains/arm-linux-androideabi-4.8/prebuilt//windows/bin/arm-linux-androideabi-g++ -o platform\android\os_android.os -c -DNO_STATVFS -MMD -MP -MF -fpic -ffunction-sections -funwind-tables -fstack-protector -D__ARM_ARCH_7__ -D__GLIBC__ -Wno-psabi -march=armv6 -mfpu=neon -mfloat-abi=softfp -ftree-vectorize -funsafe-math-optimizations -fno-strict-aliasing -DANDROID -Wa,--noexecstack -DGLES2_ENABLED -DGLES1_ENABLED -D_DEBUG -g1 -Wall -O0 -DDEBUG_ENABLED -fno-exceptions -DNO_SAFE_CAST -DDEBUG_MEMORY_ALLOC -DSCI_NAMESPACE -DDEBUG_MEMORY_ALLOC -DANDROID_ENABLED -DUNIX_ENABLED -DNO_FCNTL -DMPC_FIXED_POINT -DMUSEPACK_ENABLED -DOPENSSL_ENABLED -DSQUISH_ENABLED -DVORBIS_ENABLED -DPNG_ENABLED -DDDS_ENABLED -DPVR_ENABLED -DJPG_ENABLED -DWEBP_ENABLED -DSPEEX_ENABLED -DGDSCRIPT_ENABLED -DMINIZIP_ENABLED -DXML_ENABLED -DOPENSSL_NO_ASM -DOPENSSL_THREADS -DL_ENDIAN -Icore -Icore\math -Itools -Idrivers -I. -Iplatform\android "-IC:\Program Files\android-ndk\platforms\platforms\android-15\arch-arm\usr\include" "-IC:\Program Files\android-ndk\platforms\sources\cxx-stl\gabi++\include" "-IC:\Program Files\android-ndk\platforms\sources\cpufeatures" -Idrivers\builtin_openssl2 -Iplatform\android\vorbis -Idrivers\builtin_openssl2\crypto -Idrivers\builtin_openssl2\openssl -Idrivers\builtin_openssl2\crypto\evp -Idrivers\builtin_openssl2\crypto\asn1 -Idrivers\builtin_openssl2\crypto\modes platform\android\os_android.cpp
scons: *** [platform\android\os_android.os] The system cannot find the file specified
scons: building terminated because of errors.

**Comment by vnen** [comment] 2015-10-30 13:40
This is a duplicate of #1403. Follow the discussion there for possible workarounds.

**Closed by vnen** 2015-10-30 13:40 UTC
Labels: archived, bug, platform:android, platform:windows, topic:buildsystem
