### ISSUE TITLE
RigidBody CylinderShape can temporarily penetrate a KinematicBody BoxShape upon landing

### ISSUE THREAD

**Issue by rogeriodec** [godotengine/godot#27212] opened 2019-03-18 17:50 UTC
**Godot version:**
3.1

**OS/device including version:**
Windows 10 x64

**Issue description:**

**The cylinder CollisionShape is going through the Box CollisionShape.**

The cylinder is a RigidBody and the floor is a KinematicBody BoxShape.

I created a project from scratch and did only the scene that is in the image, without any modification other than resizing the CollisionShape cube and moving the cylinder CollisionShape up.

![c](https://user-images.githubusercontent.com/11199752/54551047-fd45c280-498b-11e9-9687-0c44f11a1e84.gif)

![](https://media.discordapp.net/attachments/212250894228652034/557240780960301057/unknown.png?width=1440&height=514)

**Steps to reproduce:**
Run the attached project or just create a new one the follow the steps of the image above.

**Minimal reproduction project:**
[CollisionShape.zip 2019-03-18 134353.zip](https://github.com/godotengine/godot/files/2979523/CollisionShape.zip.2019-03-18.134353.zip)

**Comment by jezv** [comment] 2019-03-18 21:02
[BoxAndCylinder.zip](https://github.com/godotengine/godot/files/2980396/BoxAndCylinder.zip)
My hunch is this is to do with the cyclinder shape.  Not sure how its implemented but using a box collision in the middle seems to result in more stable behaviour (see BoxAndCylinder.zip).

**Comment by rogeriodec** [comment] 2019-03-18 23:31
> [BoxAndCylinder.zip](https://github.com/godotengine/godot/files/2980396/BoxAndCylinder.zip)
> My hunch is this is to do with the cyclinder shape. Not sure how its implemented but using a box collision in the middle seems to result in more stable behaviour (see BoxAndCylinder.zip).

Interesting approach. However, if the CollisionShape turns sideways, it will not behave like a cylinder, that is, it will not roll...

**Comment by rogeriodec** [comment] 2019-04-01 05:59
Studying a little, mainly based on [this video](https://youtu.be/7_nKOET6zwI), I realized that is not easy to calculate a precise collision.
But I saw the there is a [continuous collision detection](https://docs.godotengine.org/uk/latest/classes/class_rigidbody.html#class-rigidbody-property-continuous-cd) option, which theoricaly might make a difference, but not. 
Where this option would be effective?

**Comment by jezv** [comment] 2019-04-19 13:09
> > [BoxAndCylinder.zip](https://github.com/godotengine/godot/files/2980396/BoxAndCylinder.zip)
> > My hunch is this is to do with the cyclinder shape. Not sure how its implemented but using a box collision in the middle seems to result in more stable behaviour (see BoxAndCylinder.zip).
> 
> Interesting approach. However, if the CollisionShape turns sideways, it will not behave like a cylinder, that is, it will not roll...

The box can be thinner than the cyclinder but slightly longer.  See my attached BoxAndCyclinder.zip

**Comment by jitspoe** [comment] 2019-07-11 21:20
I've had some rare instances with box-on-box collision penetrating, so even that's not 100% stable.  Can't come up with a consistent repro case, though.  Here's a clip of it happening: https://clips.twitch.tv/YawningDifferentCocoaTheTarFu

Character is a KinematicBody with a box shape using move_and_collide().  Box in the world is a StaticBody with a box shape.

**Comment by Calinou** [comment] 2020-05-05 15:11
Duplicate of #16505.

**Closed by Calinou** 2020-05-05 15:11 UTC
Labels: bug, discussion, topic:physics
