### ISSUE TITLE
Input:get_last_mouse_speed() returns wrong value if mouse is clicked

### ISSUE THREAD

**Issue by timcode77** [godotengine/godot#48983] opened 2021-05-22 22:39 UTC
**Godot version:**
v3.3.1.stable.official

**Issue description:**
Input:get_last_mouse_speed() returns the correct value, but if you then click a mouse button and do not actually move the mouse, it starts returning incorrect values.

**Steps to reproduce:**
[See attached project.]
1. Create a Node2D with this code:
```
extends Node2D

func _process(delta):
	print(Input.get_last_mouse_speed())
```

2. Run the project and move your mouse around. You will see the last mouse speed print out. That's correct behavour.
3. Hold the mouse completely still and click. The last mouse speed changes. That is incorrect behavour. 

**Minimal reproduction project:**

[Mouse_speed_problem.zip](https://github.com/godotengine/godot/files/6527265/Mouse_speed_problem.zip)

**Comment by madmiraal** [comment] 2021-05-23 07:23
Duplicate of #20357.

@timecode77 Please don't delete parts of the Issue Template it includes:
```
**OS/device including version:**
<!-- Specify GPU model, drivers, and the backend (GLES2, GLES3, Vulkan) if graphics-related. -->
```

**Closed by madmiraal** 2021-05-23 07:23 UTC
Labels: bug, topic:input
