### ISSUE TITLE
iOS export does not like spaces

### ISSUE THREAD

**Issue by BastiaanOlij** [godotengine/godot#25128] opened 2019-01-19 10:33 UTC
**Godot version:**
Master build from today but I think this applies to any Godot 3.1 build atm

**OS/device including version:**
Any iOS device

**Issue description:**
Exporting to iOS does not behave well when spaces are involved. 

**Steps to reproduce:**
There are two main issues, one is with the file names so simply ensure there is a space in your project name.

Spaces within file names as written into the project file need to be escaped with a backslash
So: My Godot Test.a
Becomes: My\ Godot\ Test.a

Spaces within fields such as the developer team should result in the string enclosed in double quotes
So: Bastiaan Olij
Becomes: "Bastiaan Olij"

**Comment by IronicallySerious** [comment] 2019-01-30 19:55
I would like to take this up. Looks like a short junior job once I find out where I should go looking for an issue like this. I am guessing it should be related to the files inside the `editor/` directory. I will be looking

**Comment by naithar** [comment] 2020-06-25 19:48
This one seems to be fixed in both master (21d1ea60a7193eae9be574c1730f39b0fd2bceb2) and 3.2 (b765e42c151a74287911a26eccdab862373ef939) and is not reproducible in 3.2.2 RC4

**Comment by akien-mga** [comment] 2020-06-25 20:41
Thanks for testing. Closing as fixed.

**Closed by akien-mga** 2020-06-25 20:41 UTC
Labels: bug, cherrypick:3.2, junior job, platform:ios, topic:editor
