### ISSUE TITLE
v4 Beta 2 Linux IDE - Never Ending GUI Loop - Not Sure About Windows (I use Linux)

### ISSUE THREAD

**Issue by BetaMaxHero** [godotengine/godot#67372] opened 2022-10-13 23:41 UTC
### Godot version

v4.0.beta2.official [f8745f2f7]

### System information

Linux Mint 21 Cinnamon 64Bit

### Issue description

Hi,

On Linux the v4 Beta 2 IDE goes into a never ending GUI cycle that can't be escaped (must KILL app in Process Manager)?

Jesse

### Steps to reproduce

1. Run Godot 4 Beta 2 v4.0.beta2.official [f8745f2f7] on Linux(Using Linux Mint Cinnamon here).
2. Open game project into IDE.
3. Minimize Godot IDE.
4. Open game project folder.
5. Modify one of the *.GD files and save it(with an external text editor).
6. Maximize Godot IDE.
7. Now stuck in endless GUI loop about one of the files being changed externally.
8. KILL app in Process Manager

### Minimal reproduction project

https://github.com/BetaMaxHero/GDScript_Godot_4_T-Story

**Comment by Calinou** [comment] 2022-10-13 23:47
Duplicate of https://github.com/godotengine/godot/issues/66644.

**Closed by Calinou** 2022-10-13 23:47 UTC
