### ISSUE TITLE
Godot editor fields are less responsive : "Field Input" mode is too sticky

### ISSUE THREAD

**Issue by Stealcase** [godotengine/godot#67792] opened 2022-10-23 12:07 UTC
### Godot version

Godot 4 Beta 3

### System information

Windows 10

### Issue description
2 Different issues with Tab Focus and field input mode. 
Including both of in 1 issue because there seems to be some overlapping logic. 

# Scenario 1
Trying to navigate inspector properties with the Tab key, or quickly manipulate several fields.

## Expected behaviour
When tabbing to an input field, I expect the input field to be focused and accept keyboard inputs. If I press tab again, I expect the next selectable input field to be focused and editable. This worked (mostly, with slight stickyness) in godot 3.5

![Godot 3_5 Properties tabbing_v2](https://user-images.githubusercontent.com/38126357/197390050-de33973b-292c-4cd4-a105-f07e40be4f50.gif)

## Actual Behaviour
* Input fields sometimes become "Sticky", and don't allow continuous tabbing. When pressing the tab key, you are "soft selecting" the next property, while still stuck in "input mode" on the previous property. Tabbing/shift+Tabbing does NOT let you escape from this bug, only mouse clicking can help you. 
* Only "Sticky" fields where the caret are visible are editable with the NumKeys. Other fields are "Focused", but cannot accept input until you press "spacebar" or "enter".

### In-action in Godot 4 Beta 3
![Bugged Properties](https://user-images.githubusercontent.com/38126357/197388936-2a31ecb3-aba0-4f25-97e8-1a81e7cd274c.gif)

### Spesific Example:
Freeze-frame of the "Stickyness". Pressing "Tab" while in this state will not let you exit.
![image](https://user-images.githubusercontent.com/38126357/197388690-c6c6ea41-63f0-4cbe-b42f-f10aa8a749ca.png)

# Scenario 2
Trying to rename 1 or several files in the scene hierarchy.

## Expected behaviour
1. Pressing tab while in the "Rename State" should switch focus to the next node below, and enter the Rename State. Pressing Shift + Tab should open the node above in Rename State.
2. Mouse clicking on Node Y while in Rename State on Node X should instantly exit Rename State on Node X, and select Node Y. This worked in Godot 3.5

## Actual Behaviour
1. Pressing tab while in Rename State does nothing.
2.  Clicking on another node while in rename state *only exits* the rename state: The original node retains focus. 

![Godot 3_5 renaming](https://user-images.githubusercontent.com/38126357/197390886-1b422cd8-7b47-4374-91cc-f0daf79ec335.gif)
### Godot 4:
2 Clicks are required to select a new node.
![Bugged Scene Tree](https://user-images.githubusercontent.com/38126357/197390893-8b3c36cd-f2a3-4470-86aa-b10143bc1ab9.gif)

### Steps to reproduce

These are editor issues which can be reproduced in any node with input properties or scene hierarchies described above.

**Comment by Mickeon** [comment] 2022-10-23 12:31
Yeah, this is kind of a regression of the way Popups are handled. They really do steal all inputs even if they do not make use of them. Very nice demonstration, it's difficult to put it to words, and it's really annoying. In Godot 4.0 you have to currently click twice to select another element, which wasn't the case in 3.x, and shouldn't be.

**Comment by Calinou** [comment] 2022-10-23 16:01
Duplicate of https://github.com/godotengine/godot/issues/37723.

**Closed by Calinou** 2022-10-23 16:01 UTC
