### ISSUE TITLE
GDScript 2.0: Can't instance a inner class in a `class_name` script

### ISSUE THREAD

**Issue by CsloudX** [godotengine/godot#63014] opened 2022-07-15 01:01 UTC
### Godot version

v4.0.alpha11.official [afdae67cc]

### System information

Windows 10 64bit

### Issue description

When new a inner class, it report error:
`Invalid get index 'xxx'(on base: 'GDScript')`

### Steps to reproduce

1. Create a new gd file:
![1](https://user-images.githubusercontent.com/35988767/179125704-fd49e6e5-9992-4c9d-94fe-d7375bc49560.PNG)

2. New a inner class:
![2](https://user-images.githubusercontent.com/35988767/179125739-31b3139d-7aad-4d95-bd5b-5b7e3f45365c.PNG)

 
4. Run and it report error:
![3](https://user-images.githubusercontent.com/35988767/179125787-1ea29f59-5c10-455c-88ba-7dbe00411fd2.PNG)

### Minimal reproduction project

[GDTst.zip](https://github.com/godotengine/godot/files/9116839/GDTst.zip)

**Comment by KoBeWi** [comment] 2022-08-10 12:55
Duplicate of #51538

You can do
```GDScript
func _ready():
	Cls
	var n = Cls.P.new()
```
as a workaround.

**Closed by KoBeWi** 2022-08-10 12:55 UTC
Labels: bug, topic:gdscript
