### ISSUE TITLE
panel reparent error and blank container

### ISSUE THREAD

**Issue by ni-code** [godotengine/godot#2568] opened 2015-10-03 23:47 UTC
Found 2 minor issues, I think they were not reported yet.
When performing a reparent of the FileSystem panel the terminal shows some errors. Also there is a empty container when opening "old" projects.
Screen-shoot attached for better clarification.
![screenshot_gd_2015-10-04 00 28 26](https://cloud.githubusercontent.com/assets/10292929/10265656/645153ec-6a31-11e5-9c9b-de29f3be61ba.png)

**Comment by akien-mga** [comment] 2015-11-09 10:04
See #2349 for the second bug.

Is the first bug still valid in the current master branch? Please also make sure to open one issue per bug next time, it makes tracking each bug easier :)

**Comment by vnen** [comment] 2015-11-09 18:11
Yes, it does happen on current master. The empty container also appear after the reparent.

**Comment by akien-mga** [comment] 2015-11-19 06:37
The second issue has been fixed in #2349.

**Comment by ni-code** [comment] 2015-11-19 18:32
@akien-mga sry, next time I will create one issue per bug.

**Comment by akien-mga** [comment] 2015-11-19 18:50
No problem, in the end it looks like some contributors found how to address both bugs :)

**Comment by reduz** [comment] 2015-12-29 18:17
i can't reproduce either of them, so it seems like it's closed

**Closed by reduz** 2015-12-29 18:17 UTC
Labels: bug, confirmed, topic:editor
