### ISSUE TITLE
Menu popup to back when when gui_embed_subwindows = false

### ISSUE THREAD

**Issue by CsloudX** [godotengine/godot#73335] opened 2023-02-15 06:21 UTC
### Godot version

v4.0.rc2.official [d2699dc7a]

### System information

Windows 10, 64bit

### Issue description

![GIF](https://user-images.githubusercontent.com/35988767/218948456-77b857a9-f4ff-4e46-9404-5c1b2b21ac92.gif)

### Steps to reproduce

/

### Minimal reproduction project

[MenuTest.zip](https://github.com/godotengine/godot/files/10739923/MenuTest.zip)

**Comment by Sauermann** [comment] 2023-06-26 15:53
looks like a duplicate of #62382

**Comment by KoBeWi** [comment] 2024-08-02 11:04
Looks like it's some special case. If `always_on_top` is enabled from the start and not changed, it works correctly.

**Comment by KoBeWi** [comment] 2024-10-12 21:42
Closing again as duplicate, seems like that issue is not fixed.

**Closed by KoBeWi** 2024-10-12 21:42 UTC
Labels: bug, topic:gui
