### ISSUE TITLE
get_shader_parameter and get_instance_shader_parameter return Nil instead of default parameter values

### ISSUE THREAD

**Issue by lostminds** [godotengine/godot#71720] opened 2023-01-20 10:15 UTC
### Godot version

4.0b13

### System information

macOS 13.0.1

### Issue description

I've run into an issue with reading shader parameters. I'll just use the shader parameter example below, but the issue seems to be the same for instance shader parameters.

If you set up your shader to have parameters with a default value you do not need to set these shader parameters in each shader material, and the default value will be used instead. However, if you use get_shader_parameter to get what value the shader material is using for a parameter this will return null instead of the default value I would expect in these cases. You could argue that this is expected since it's correctly reporting this parameter is not set on the material, but it's not returning what value will be used for this parameter (the default value) and that is probably what the user is interested in.

Another issue with this is that since Nil is not a valid value to assign to some typed vars this unexpected return can cause the game to crash if you've used a typed variable like so:
`var floatShaderParameter:float = material.get_shader_parameter("MyParameter")`
With the error `Trying to assign value of type 'Nil' to a variable of type 'float'.` which might be confusing if you think the error is in get_shader_parameter which shouldn't be setting anything.

If this is by design, a helpful improvement would be to at least add a warning on get_shader_parameter to indicate the material does not have the requested parameter. This would be a good improvement for other cases as well.

 

### Steps to reproduce

- Set up a basic 3d scen with a mesh and a camera
- Create a new shader material and a shader assigned to the mesh
- In the shader, add a shader parameter with a default value and hook it up to something
- Observe that the default value is used in the shader
- In code, try to read the shader parameter value on the material using get_shader_parameter
- Instead of returning the default value it will return null/Nil

### Minimal reproduction project

[shader_parameter_default.zip](https://www.lostminds.com/godot/shader_parameter_default.zip)

**Comment by Lippanon** [comment] 2023-01-20 12:08
I think this is a duplicate of https://github.com/godotengine/godot/issues/44454.
Your MRP works if you first click this arrow to 'initialise' the parameter: 
![image](https://user-images.githubusercontent.com/115422160/213691376-d334cbb7-6455-4314-937a-37d9dee5a1ce.png)
The problem is that uniforms don't automatically get assigned their default values in the resource, I've noticed this before but hadn't opened an issue, when you add uniforms you have to always click that arrow.

**Comment by Calinou** [comment] 2023-01-20 12:10
Duplicate of https://github.com/godotengine/godot/issues/44454.

**Closed by Calinou** 2023-01-20 12:10 UTC
