### ISSUE TITLE
Remote scene tree values editing doesn't work anymore in 4.0 alpha 6

### ISSUE THREAD

**Issue by Zireael07** [godotengine/godot#60133] opened 2022-04-11 06:54 UTC
### Godot version

4.0 alpha 6

### System information

Linux Manjaro, Vulkan, Intel Kaby Lake

### Issue description

I noticed that if I edit a value in remote scene tree, the output will say 'Set <variable name>' (once) but it then immediately resets to the previous (with no additional info in output) and nothing changes in the running game

So far I have seen it affect bools, transform and Strings

### Steps to reproduce

Open a Godot project, attempt to edit a value in remote scene tree.

### Minimal reproduction project

I don't have a minimal repro project, I experienced it on https://github.com/Zireael07/FreeRoamRoguelikeRacerPrototype/tree/4.x

**Comment by Calinou** [comment] 2022-04-11 13:13
Does it work in previous 4.0 alphas?

**Comment by Zireael07** [comment] 2022-04-11 13:17
I *think* (but I'm not 100% certain because it was a pretty long time ago) it worked in alpha 1 and 2 (and going back from alpha 6 to check is very difficult due to numerous API/import changes)

**Comment by KoBeWi** [comment] 2022-05-12 14:53
Duplicate of #54977
This was broken for a long time.

**Closed by KoBeWi** 2022-05-12 14:53 UTC
Labels: bug, topic:editor, regression
