### ISSUE TITLE
Exported variables are not displayed in remote when using C#

### ISSUE THREAD

**Issue by Torguen** [godotengine/godot#33896] opened 2019-11-25 19:09 UTC
**Godot version:**
3.2 beta 1 mono

**OS/device including version:**
win10 64 home

**Issue description:**
I have an exported variable in my node and when I look at the remote mode to see the value of the variable in execution, the variable is not displayed.

**Steps to reproduce:**
Use [Export] with a variable and execute and display the remote mode.
The variable does not appear, its values cannot be seen.

**Minimal reproduction project:**
[testRemote2.zip](https://github.com/godotengine/godot/files/3888287/testRemote2.zip)

**Comment by Calinou** [comment] 2019-11-25 21:05
According to #4773, it should already work with exported variables, but only in GDScript. I guess it hasn't been implemented yet for Mono?

**Comment by Torguen** [comment] 2019-11-25 21:54
In remote mode (with the game running) they are not visible but in the editor they are visible.

**Comment by Torguen** [comment] 2019-11-26 18:42
To clarify, I mean that the variable is not displayed in the "inspector" dock.

**Comment by gururise** [comment] 2019-11-26 20:36
Hmm.... works for me on 3.2 Beta2 on Linux:

![image](https://user-images.githubusercontent.com/4380009/69670681-48e75a80-1049-11ea-9fe9-66e06c689412.png)

![image](https://user-images.githubusercontent.com/4380009/69670659-3a993e80-1049-11ea-9f1a-6dd100f1c72d.png)

Did you "BUILD" project after making the changes to the c# script?

**Comment by Torguen** [comment] 2019-11-26 20:45
I already specified that information above.

The exported variable is correctly seen in the editor but cannot be seen in the "remote" tab with the game running.

**Comment by neikeq** [comment] 2020-05-21 23:03
I couldn't reproduce the properties not being visible in the inspector. That one was likely fixed by #38638.
However, the values were not being updated in the inspector, which is fixed by #38940.

**Closed** 2020-05-22 07:09 UTC
Labels: bug, confirmed, high priority, topic:editor, topic:mono
