### ISSUE TITLE
Missing file errors when compiling Godot with VS Studio.

### ISSUE THREAD

**Issue by Darenn** [godotengine/godot#37624] opened 2020-04-06 07:46 UTC
**Godot version:**
commit hash : 11f31a732922571bf6e0398a5192132ae67aee16

**OS/device including version:**
Windows 10

**Issue description:**
After following [this tutorial](https://docs.godotengine.org/en/3.1/development/compiling/compiling_for_windows.html#development-in-visual-studio-or-other-ides) to contribute to the Godot Engine using Visual Studio IDE, I've got those errors : [vs_errors.txt](https://github.com/godotengine/godot/files/4436677/vs_errors.txt)

**Steps to reproduce:**
Follow the tutorial, launch VS Studio and try to build godot.

**Comment by Calinou** [comment] 2020-04-06 07:57
The last error message is related to #37620. I don't know what's causing all the other error messages though.

**Comment by akien-mga** [comment] 2020-04-06 08:01
You likely omitted some components when installing Visual Studio's C++ compiler, notably the Windows SDK.

**Comment by akien-mga** [comment] 2020-04-06 08:28
Closing for now as I'm fairly sure that it's a combination of both a missing Windows SDK and a duplicate of #37620 for the latter part.

**Closed by akien-mga** 2020-04-06 08:28 UTC
Labels: platform:windows, topic:buildsystem

**Comment by Darenn** [comment] 2020-04-06 08:38
Thanks for your help!
Do you think the tutorial should be updated then?
It says only to add the C++ component when installing visual studio, unless I misunderstood something.

**Comment by akien-mga** [comment] 2020-04-06 09:27
Indeed, it should mention **Windows 10 SDK** in https://docs.godotengine.org/en/latest/development/compiling/compiling_for_windows.html#installing-visual-studio-caveats

**Comment by Darenn** [comment] 2020-04-06 11:31
Installing the Windows 10 SDK resolved the issue.
Also note that you need to specifiy to build godot for x64 to work (by default it's Win32)
