### ISSUE TITLE
Code complete not working.

### ISSUE THREAD

**Issue by Deyaero** [godotengine/godot#87416] opened 2024-01-20 16:35 UTC
### Tested versions

v4.2.1.stable.official [b09f793f5]
After testing previous versions the bug could not be reproduced and autocomplete was working perfectly completing properties and methods.

### System information

Godot v4.2.1.stable - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 2060 (NVIDIA; 31.0.15.4584) - AMD Ryzen 7 5800X 8-Core Processor (16 Threads)

### Issue description

Autocomplete has stopped finishing node properties and methods. I will use animation player nodes as an example. If you type "$AnimationPlayer.p" you should see a suggestion for play and then which animation to auto fill the string but nothing appears for play. This problem has persited through multiple devices and projects which leads to assume that this could be the engines bug. (just so i knew it wasn't the animation player only. cpuparticles also failed to complete the proporties. It wouldn't autocomplete "emmiting" which is important for particle managment and slows down the work flow.
![Desktop Screenshot 2024 01 20 - 11 08 07 14](https://github.com/godotengine/godot/assets/146136191/df600c98-0ab5-4a1a-8e0d-bae1a6049622)
![Desktop Screenshot 2024 01 20 - 11 08 00 54](https://github.com/godotengine/godot/assets/146136191/3e2005ab-2b0e-4259-8ab4-8d3baa23bd61)

### Steps to reproduce

Add a root node (2d or 3d) and add an AnimationPlayer node as a child. Create and animation for the node. (could be anything, the problem still persists) and now write the line of code to play the animation, it typically looks like this "$AnimationPlayer.play("**_whatever_you_named_the_animation_**"). Play nor anything past that written will autocomplete. The line of code still works if written by memory with the correct syntax but it harder, inconvinent, and time wasting.

### Minimal reproduction project (MRP)

[MRP.zip](https://github.com/godotengine/godot/files/13998579/MRP.zip)
Apologies for not knowing how to create and MRP.

**Comment by HolonProduction** [comment] 2024-01-20 23:50
Duplicate of https://github.com/godotengine/godot/issues/86108

**Comment by dalexeev** [comment] 2024-01-22 20:37
* Duplicate of #86108, as @HolonProduction said.
* Fixed by #86111 for future 4.3.
* Will be cherry-picked for 4.2.x.

Thanks for reporting the bug nonetheless!

**Closed by dalexeev** 2024-01-22 20:37 UTC
