### ISSUE TITLE
The Rigidbody2D cannot rotate after set the CollisionShape2D disabled first and enabled later

### ISSUE THREAD

**Issue by spkingr** [godotengine/godot#30551] opened 2019-07-13 01:44 UTC
The Rigidbody2D cannot rotate if you disable the collision shape and then enable it again. But it's fine if you do nothing to the collision shape.

**Godot version:**
3.1.1

**OS/device including version:**
Windows 10

**Issue description:**
The rotation by `apply_torque_impulse` of the RigidBody2D may work incorrectly in Godot 3.1.1.
If you never disable the collision shape of the RigidBody2D, everything is normal, but if you first disable the shape use `$CollisionShape2D.set_deferred('disabled', true)` then after some events trigger and set it enabled with `$CollisionShape2D.set_deferred('disabled', false)`, then the rotation looks like "broken", the node can only work with `apply_central_impulse` but no effect with `apply_torque_impulse` now.

**Steps to reproduce:**
```
func _ready():
	$CollisionShape2D.set_deferred('disabled', false)
```
The code above works fine, but you cannot rotate with the code below:
```
func _ready():
	$CollisionShape2D.set_deferred('disabled', true)
	yield(get_tree().create_timer(3), 'timeout')
	$CollisionShape2D.set_deferred('disabled', false)
```

This is not the actual code but for the test is enough, and I upload the very little represented project in Github: [https://github.com/spkingr/test-git/tree/master/SpaceShipRotation](https://github.com/spkingr/test-git/tree/master/SpaceShipRotation)

**Minimal reproduction project:**
[https://github.com/spkingr/test-git/tree/master/SpaceShipRotation](https://github.com/spkingr/test-git/tree/master/SpaceShipRotation)

The images:
![cannot rotate image](https://github.com/spkingr/test-git/raw/master/images/godot/Rotation_of_rigidbody2d_1.gif)
![normal rotation image](https://github.com/spkingr/test-git/raw/master/images/godot/Rotation_of_rigidbody2d_2.gif)

**Comment by raphael10241024** [comment] 2019-07-14 09:15
Unable to reproduce with latest build, seems already fixed.

**Comment by spkingr** [comment] 2019-07-14 11:06
> Unable to reproduce with latest build, seems already fixed.

So how to use the latest API in Godot 3.1 stable version to solve this bug?

**Comment by raphael10241024** [comment] 2019-07-14 14:33
Not stable version,  just built with latest master source code. See here to build it https://docs.godotengine.org/en/3.1/development/compiling/index.html

**Comment by asheraryam** [comment] 2019-07-17 11:55
There are nightly binaries here everyday.
https://hugo.pro/projects/godot-builds/

**Comment by mcbloch** [comment] 2019-10-06 23:34
Had the same issue disabling and enabling the collision shape. I can confirm that it is fixed on a nightly build.
Extra information should this be usefull:
Godot Engine v3.2.alpha.calinou.1d9233c38
OpenGL ES 3.0 Renderer: GeForce GTX 970M/PCIe/SSE2

**Comment by spkingr** [comment] 2020-02-02 01:19
Fixed in 3.2.

**Closed** 2020-02-02 01:19 UTC
Labels: bug, topic:physics

**Comment by lukepass** [comment] 2020-08-04 14:00
Hello, I am using the version 3.2.2 and I have exactly the same problem. I cannot apply torque forces when the collision shape is disabled. Any solution?

Thanks.

**Comment by Calinou** [comment] 2020-08-04 14:09
@lukepass Please create a new issue with a minimal reproduction project attached.

**Comment by lukepass** [comment] 2020-08-04 14:32
@Calinou I uploaded the project and opened a new issuje:

https://github.com/godotengine/godot/issues/41024

Thanks!
