### ISSUE TITLE
Line2D with repeating texture enabled stretched in-game

### ISSUE THREAD

**Issue by ZikaaZ** [godotengine/godot#22529] opened 2018-09-29 09:09 UTC
**Godot version:**
3.0.6

**OS/device including version:**
Windows 10 64bit, r9 290x 

**Issue description:**
Using the Line2D node, the desired effect is achieved in the editor but looks stretched out when run.
![capture1](https://user-images.githubusercontent.com/19575446/46243627-b3b1ed00-c3d6-11e8-8499-6a97ff554b33.png)

**Steps to reproduce:**
Make a Line2D and give it a texture with repeat enabled, set Line2D Texture Mode to Tile.
The texture is 64x64 pixels.
While the scale of Line2D y axis was set to 0.5 in the screenshot above, behaviour was the same with (1,1) scale,
![capture](https://user-images.githubusercontent.com/19575446/46243799-e4465680-c3d7-11e8-82c7-9f27923bc0ec.PNG)

Could be related to https://github.com/godotengine/godot/issues/16961

**Comment by Zylann** [comment] 2018-09-29 12:28
It would be really weird to be related to #16961 because if it was, you would have glitches in the editor too.

**Comment by Calinou** [comment] 2020-05-19 19:42
@ZikaaZ Can you reproduce this in Godot 3.2.1 or [3.2.2beta2](https://godotengine.org/article/dev-snapshot-godot-3-2-2-beta-2)?

**Comment by tom-jk** [comment] 2020-07-09 10:12
Can't reproduce here.

Linux Mint 18.3, GeForce GTX 750 Ti
Godot 3.2.2.stable

![Godot22529_Screen](https://user-images.githubusercontent.com/64640811/87026917-51edfc00-c1d4-11ea-93d1-d32951ea3ebc.png)

Editor and game identical. Tested with a few different render settings and under gles2 and gles3.

Minimal project:
[22529.zip](https://github.com/godotengine/godot/files/4896011/22529.zip)

**Comment by Calinou** [comment] 2020-07-09 11:59
@tom-jk Thanks for testing this :slightly_smiling_face: Closing as resolved then.

**Closed by Calinou** 2020-07-09 11:59 UTC
Labels: bug, topic:rendering
