### ISSUE TITLE
CMD+Z does not effect selected editor Godot 4.0 MacOS

### ISSUE THREAD

**Issue by mageowl** [godotengine/godot#65221] opened 2022-09-01 23:46 UTC
### Godot version

4.0.alpha15

### System information

MacOS 12

### Issue description

When I press CMD+Z when editing code it instead undoes a change in my animation...

https://user-images.githubusercontent.com/32573897/188030694-0f232161-5246-4781-804c-7ccb48b9b3bf.mov

### Steps to reproduce

1. Make a change in a scene or animation editor on MacOS.
2. Switch to Script Editor and open Output.
3. Press CMD+Z and check output.

**Comment by Calinou** [comment] 2022-09-01 23:48
Duplicate of https://github.com/godotengine/godot/issues/65119.

**Closed by Calinou** 2022-09-01 23:48 UTC
