### ISSUE TITLE
Live syncing of transforms now only works through inspector

### ISSUE THREAD

**Issue by MajorMcDoom** [godotengine/godot#93004] opened 2024-06-10 22:23 UTC
### Tested versions

Reproducible in 4.3.beta1

### System information

Godot v4.3.beta1 - Windows 10.0.22631 - Vulkan (Mobile) - dedicated NVIDIA GeForce GTX 1660 SUPER (NVIDIA; 31.0.15.5212) - Intel(R) Core(TM) i7-10700F CPU @ 2.90GHz (16 Threads)

### Issue description

Live syncing of transforms has regressed, and now only works through editing the transform in the inspector. It no longer works by dragging the transform gizmo, or by using the Transform dialog, or any other operation that changes the Transform.

This applies to 2D as well as 3D transforms.

### Steps to reproduce

- Make sure the "Synchronize Scene Changes" editor option is turned on.
- Run any scene with a visible node.
- Move the node from the editor by dragging it with its gizmo.
- Note that the node in the running game does not move.

### Minimal reproduction project (MRP)

N/A

**Comment by matheusmdx** [comment] 2024-06-18 00:30
This looks like a duplicate of #92695 and that was solved by 9492943

**Closed** 2024-06-18 14:15 UTC
Labels: bug, topic:editor, regression
