### ISSUE TITLE
High pulseaudio cpu usage with Godot Editor

### ISSUE THREAD

**Issue by wb14123** [godotengine/godot#76880] opened 2023-05-09 14:41 UTC
### Godot version

v4.0.2.stable.arch_linux

### System information

ArchLinux, Intel i5-6600k

### Issue description

When I open Godot Editor, even before I open any project, pulseaudio uses ~12% CPU on the project selection dialog.

I'm using ArchLinux with X11.

Not sure if it's a regression of https://github.com/godotengine/godot/issues/15266

### Steps to reproduce

Open Godot editor

### Minimal reproduction project

Just open Godot editor without selecting any project

**Comment by Calinou** [comment] 2023-05-09 14:46
Can you reproduce this in 3.5.2?

Can you reproduce this when starting the project manager with `--audio-driver ALSA`?

**Comment by wb14123** [comment] 2023-05-09 15:16
@Calinou Just tried this version `v3.5.2.stable.official.170ba337a` downloaded from official website. It has the same problem, even with `--audio-driver ALSA`.

**Comment by lawnjelly** [comment] 2023-05-09 15:17
For me in 3.x, pulse audio was also the biggest CPU hog after selecting `vital updates only` mode (Using >5% CPU for pulse audio).

This is why I wrote #63458 . This PR turns off the audio driver when sound is not playing, especially useful in the editor, when 99% of time there is no need to use CPU on sound. You can also use it in exported projects, and mute when losing focus, sleeping etc. It is merged in https://github.com/godot-plus/godot-plus/releases which may be worth a try for comparison, if the linux build works for you.

This is useful for low power / mobile / battery devices, as the audio will drain the battery needlessly. In official Godot the only way to prevent this I think is to run using the dummy audio driver in the command line argument, but it will play no audio.

**Comment by Calinou** [comment] 2023-05-09 15:19
- Duplicate of https://github.com/godotengine/godot/issues/55608.

**Closed by Calinou** 2023-05-09 15:19 UTC
Labels: bug, topic:audio, performance
