### ISSUE TITLE
Convert CSG to mesh and export features

### ISSUE THREAD

**Issue by DevMagicLord** [godotengine/godot#24798] opened 2019-01-05 23:13 UTC
Godot 3 alpha 5.

A great feature would be to convert CSG node and child nodes to a mesh, when there is no more CSG modification needed.
And the ability to export the model to some obj format to work in Blender for example.

**Comment by pgruenbacher** [comment] 2019-01-07 17:44
mmm, without having tried myself, I would presume this is not possible since openCSG is not actually calculating a new mesh internally, it's using OpenGL to render the meshes combined, so it's not available to the cpu.

**Comment by pgruenbacher** [comment] 2019-01-07 17:50
if you were to play with CSG nodes with wireframe rendering, you should see that the vertices are not forming seams with the other objects, but are instead jsut being masked. if I'm right, then this would require quite a bit of feature work and would likely involve integrating a CAD package, which I think you'd be better off using 3rd party resource.

**Comment by bojidar-bg** [comment] 2019-01-07 20:14
First part was discussed in #19232 (and will be required for it), second part is duplicate of #8510.

Closing as duplicate of the above-linked issues, correct me if I am wrong.

**Closed by bojidar-bg** 2019-01-07 20:14 UTC
