### ISSUE TITLE
wraparoundLayer : ability to wraparound mirror in positive and negative x and y

### ISSUE THREAD

**Issue by blurymind** [godotengine/godot#15359] opened 2018-01-05 11:23 UTC
I am trying to implement a tiling canvas. 
For that to work, I need to be able to get the 2 bats to tile as 8 bats in at least one of the grid squares:
 
![capture](https://user-images.githubusercontent.com/6495061/34607384-304b10f6-f20b-11e7-80bd-5561ba5bae2a.PNG)

Here is a minimal example project  with bats:
[tilingProblem.zip](https://github.com/godotengine/godot/files/1606742/tilingProblem.zip)

Is that possible to do at all?
Its seems like ParalaxLayer can only mirror once in positive x and y. For my design to work, I need it to mirror at least twice (once positive and once negative). As you can see all grid squares are missing either 3 or 2 tiled bats

looking into doing it with parallax layer , I found out that it has a limitation that prevents complete tiling on non-moving screen with sprites moving inside it.

It only tiles partially, its not very good for games where the camera doesn't move, but you need the screen to wraparound. Classic examples can be found in many arcade games, such as pacman, some of the first mario arcades, 
https://youtu.be/j4lKDTgifl8?t=52s

See this article for a better description:
https://en.wikipedia.org/wiki/Wraparound_(video_games)

We can't easily achieve it in godot at the moment. 
In my case I can't  do it via teleporting because it looks ugly - especially on bigger sprites to disappear and reappear. 
 I also want to use it for a tiling texture editor I am making in godot, so that absolutely needs to show both halves of the sprite on two ends of the screen

**Comment by blurymind** [comment] 2018-01-05 12:19
I was wondering if I can achieve this with the shaderGraph screen shader

Is it possible to set it as tiling in the graph?

**Comment by blurymind** [comment] 2018-01-05 12:51
I found that in order to achieve it, I need at least three paralax layers:
![3paralaxlayers](https://user-images.githubusercontent.com/6495061/34609999-0c4cf73a-f217-11e7-8a4d-c1439c220d9c.png)

However this will not work, because the three layers contain different instances of the sprites. 
I need to be able to do this in one paralax layer

**Comment by akien-mga** [comment] 2018-01-05 13:24
This used to work in 2.1, no?

**Comment by blurymind** [comment] 2018-01-05 13:29
@akien-mga I am using 2.1.4
Is there a way to tell a parallaxLayer to repeat the mirror more than once in x and y?
If not- then - it doesnt work.
I can make an example project if you want to

**Comment by akien-mga** [comment] 2018-01-05 13:32
>  I am using 2.1.4

It would be good that you keep the issue template and fill it then, you're a seasoned bug reporter now and we should not need to guess your Godot version, OS, steps to reproduce, etc.

**Comment by blurymind** [comment] 2018-01-05 13:35
@akien-mga sorry, I felt that this is a limitation of the node, rather than a bug. I will attach a minimal example project with the bats some time later today

**Comment by blurymind** [comment] 2018-01-05 13:52
Here is an example project:
[tilingProblem.zip](https://github.com/godotengine/godot/files/1606742/tilingProblem.zip)

Ideally I would love to have at least one of the grid squares populated with 8 bats, using just one parallaxLayer - that is currently not possible

It would greatly simplify things if that grid square could be the one that contains the original sprites, but that seems to also be impossible to do

**Comment by vnen** [comment] 2018-01-05 15:14
BTW, in the editor the parallax won't be shown, it appears only in game.

**Comment by blurymind** [comment] 2018-01-05 15:28
@vnen Here is a screenshot of both in editor and in runtime- parallaxLayer failing to create tiling for 2 of the 4 walls of the origin grid square:
![missingtiling](https://user-images.githubusercontent.com/6495061/34615509-0cac07c8-f22d-11e7-9c0e-2a32201ff6dc.PNG)
This is a problem

**Comment by vnen** [comment] 2018-01-05 15:36
Hm, now I recall seeing something like this. I think when the parallax layer is smaller than the window, it won't mirror correctly.

**Comment by blurymind** [comment] 2018-01-05 15:38
@vnen feel free to play with the example project :)
[tilingProblem.zip](https://github.com/godotengine/godot/files/1606742/tilingProblem.zip)

Scaling has not been touched

I am interested in tiling without scrolling

**Comment by reduz** [comment] 2018-01-05 17:27
This is not a bug, it's working as intended. Maybe it needs to be documented better? Mirroring only happens once..

**Comment by blurymind** [comment] 2018-01-05 17:34
@reduz would it be possible to add a wraparound mode, as described in my last post? It will really help make this feature useful for much more scenarios, such as the ones described.

Is there perhaps a workaround I can use?

**Comment by reduz** [comment] 2018-01-05 17:38
@blurymind no.. you will have more luck implementing something custom on your own

**Comment by reduz** [comment] 2018-01-05 17:40
this feature is intended to replicate drawing of a scene in different axes, it works nicely even if you have animations or lights, so making it work more generic will not work. It's best you create your own layer that does what you want. Maybe what we could do is a small tutorial on hoooking to camera motion, so you can do your own parallax effects.

**Comment by reduz** [comment] 2018-01-05 17:41
Also, probably parallax needs more documentation and a tutorial

**Comment by blurymind** [comment] 2018-01-05 17:44
@reduz So do you mean creating a new node type?
To my knowledge godot currently does not offer this functionality via gdscript 

In that case, this would require a more experienced programmer than me to write it in c++,perhaps base it on the paralaxLayer node

**Comment by blurymind** [comment] 2018-01-05 20:13
perhaps this could be done with a screen shader? I have been trying to come up with one with no luck :(

**Comment by blurymind** [comment] 2018-01-05 20:58
I could make a sprite shader that does it to some extent:
```
uniform vec2 offset=vec2(155,44);

vec2 ps = TEXTURE_PIXEL_SIZE;

vec4 tile1 = vec4(tex(TEXTURE,UV-offset*ps).rgb,tex(TEXTURE,UV-offset*ps).a);
vec4 tile2 = vec4(tex(TEXTURE,UV+offset*ps).rgb,tex(TEXTURE,UV+offset*ps).a);
vec4 tile3 = vec4(tex(TEXTURE,UV+offset*vec2(1,-1)*ps).rgb,tex(TEXTURE,UV+offset*vec2(1,-1)*ps).a);
vec4 tile4 = vec4(tex(TEXTURE,UV+offset*vec2(-1,1)*ps).rgb,tex(TEXTURE,UV+offset*vec2(-1,1)*ps).a);

vec4 result = mix(tile1,tile2,tile2.a);
result = mix(result,tile3,tile3.a);
result = mix(result,tile4,tile4.a);

vec4 col = tex(TEXTURE,UV);

COLOR=mix(result,col,col.a);
```

The problem is that it won't do like that- it needs to be a screen shader to allow me to move the sprites inside .How do I turn it into a screen shader? Any ideas?

**Comment by blurymind** [comment] 2018-01-06 13:43
Ok after playing with this for a while I found that approaching this with a screen shader solution is probably not going to work for me.
It looks like godot's screen shaders cant get the alpha channel of what they are  affecting. There is also a number of other limitations that would make that solution too limited 

I wish I knew more about c++ to be able to create a new wraparoundLayer node, based on the parallaxLayer node. I looked at the code and can't understand exactly what it does. My knowledge in c++ is so poor that I don't even understand the concept of *.h and *.cpp files

**Comment by blurymind** [comment] 2018-01-08 19:59
Here is a solution using the _draw() method and specifically animatedSprite nodes:
```
func _draw(): 
	for node in ChidSprites():
		var spriteFTex = node.get_sprite_frames().get_frame(node.get_animation(),node.get_frame())#( String anim, int idx ) 
		#right
		draw_texture(spriteFTex,Vector2(node.get_pos().x+get_size().x-spriteFTex.get_width()/2,  node.get_pos().y-spriteFTex.get_height()/2))
		#left
		draw_texture(spriteFTex,Vector2(node.get_pos().x-get_size().x-spriteFTex.get_width()/2,  node.get_pos().y-spriteFTex.get_height()/2))
		#bottom
		draw_texture(spriteFTex,Vector2(node.get_pos().x-spriteFTex.get_width()/2,  node.get_pos().y+get_size().y-spriteFTex.get_height()/2))
		#top
		draw_texture(spriteFTex,Vector2(node.get_pos().x-spriteFTex.get_width()/2,  node.get_pos().y-get_size().y-spriteFTex.get_height()/2))
		#top left
		draw_texture(spriteFTex,Vector2(node.get_pos().x-get_size().x-spriteFTex.get_width()/2, node.get_pos().y-get_size().y-spriteFTex.get_height()/2))
		#bottom left
		draw_texture(spriteFTex,Vector2(node.get_pos().x-get_size().x-spriteFTex.get_width()/2, node.get_pos().y+get_size().y-spriteFTex.get_height()/2))
		#bottom right
		draw_texture(spriteFTex,Vector2(node.get_pos().x+get_size().x-spriteFTex.get_width()/2,  node.get_pos().y+get_size().y-spriteFTex.get_height()/2))
		#top right
		draw_texture(spriteFTex,Vector2(node.get_pos().x+get_size().x-spriteFTex.get_width()/2,  node.get_pos().y-get_size().y-spriteFTex.get_height()/2))
```
Unfortunately it is broken and will not work for me because draw_texture can not do any operations on the sprite that it is drawing - It can only modulate the color :'((

I wish there was a draw method that draws the node after it has had effects applied to it - rotation, scale, flip, modulate - everything. Modulate is not enough and you have to write quite a long line of code to get it to access the node's resources

**Comment by blurymind** [comment] 2018-01-09 10:17
Ok, I came up with a limited solution, but my feature request still stands - as it would be definitely very helpful for games with a single screen wraparound behavior. I renamed this issue for more clarity.

Thanks everyone for the patience

**Comment by KoBeWi** [comment] 2019-02-26 21:04
So I was just about to post an issue about repeated mirroring for parallax backgrounds. Is it what this issue is about?
It's bothersome when you have a texture too small to loop it properly, so you either need to mess with regions or place few sprites next to each other. If we were able to repeat the sprite in parallax X times, it would be much easier.

**Comment by Xrayez** [comment] 2019-08-11 18:13
> So I was just about to post an issue about repeated mirroring for parallax backgrounds.

@KoBeWi I think this pertains to #27160 more but I see how these are quite connected, posted my workaround hacky snippet there to "fix" this as you described it.

> If we were able to repeat the sprite in parallax X times, it would be much easier.

That's also why I put attention on `mirror_count` (or rather `repeat_count`) there in #27160 which should also help *this* issue.

**Comment by Calinou** [comment] 2020-05-17 20:40
Closing in favor of https://github.com/godotengine/godot-proposals/issues/658, as feature proposals are now tracked on the Godot proposals repository.

**Closed by Calinou** 2020-05-17 20:40 UTC
Labels: feature proposal, topic:core
