### ISSUE TITLE
Activating AnimationTree under certain conditions causes editor to freeze forever

### ISSUE THREAD

**Issue by thomdionqwe** [godotengine/godot#79229] opened 2023-07-09 03:04 UTC
### Godot version

v4.1.stable.official [970459615]

### System information

Godot v4.1.stable - Windows 10.0.19045 - Vulkan (Compatibility) - AMD Radeon(TM) Graphics (Advanced Micro Devices, Inc.; 31.0.14057.5006) - AMD Ryzen 5 5600G with Radeon Graphics (12 Threads)

### Issue description

A specific AnimationNodeStateMachine layout freezes the editor under certain conditions (Seems fine when parented to a Node2D). I've tried waiting for it to unfreeze for a few minutes with no improvement.

### Steps to reproduce

Activate the scene tree in the minimal reproduction project to freeze the editor. The contents of each animation does not matter.

### Minimal reproduction project

[Minimal reproduction project](https://github.com/godotengine/godot/files/11994251/Project.zip)

**Comment by LeeWannacott** [comment] 2023-07-09 10:05
I am encountering this issue as well while using `AnimationNodeStateMachine`. It completely crashes Godot.
Specs: Godot v4.1.stable from steam with Pop_os! 22.04 LTS and 5900x CPU and 6800xt GPU)

**Comment by akien-mga** [comment] 2023-07-09 10:28
- Duplicate of #79012.

**Closed by akien-mga** 2023-07-09 10:28 UTC
Labels: bug, crash, topic:animation
