### ISSUE TITLE
In a multilevel inheritance, changes to nodes from an inherited scene only affect up to the next inherited scene

### ISSUE THREAD

**Issue by AttackButton** [godotengine/godot#55964] opened 2021-12-15 17:21 UTC
### Godot version

v4.0.dev.calinou [f09d88443]

### System information

Windows 10

### Issue description

As the title says, in a multilevel inheritance, changes to nodes in the editor in a scene will only affect up to the next inherited scene, not to all subsequent ones, as expected.

### Steps to reproduce

Create a base scene and an A scene that inherits Base, and a B scene that inherits A, and a C scene that inherits B, and so on.

Any change you make to the nodes from one of these scenes will only take effect up to the next scene.  Changes in B only affect C and changes in C only affect D, etc.

### Minimal reproduction project

[inherited_scenes_nodes_problem.zip](https://github.com/godotengine/godot/files/7721459/inherited_scenes_nodes_problem.zip)

**Comment by Calinou** [comment] 2021-12-15 17:36
@AttackButton Can you reproduce this in 3.4?

**Comment by AttackButton** [comment] 2021-12-15 19:08
> @AttackButton Can you reproduce this in 3.4?

Yeah, this happens in 3.4 stable too.

[test_3.4.zip](https://github.com/godotengine/godot/files/7722054/test_3.4.zip)

**Comment by AttackButton** [comment] 2021-12-15 19:42
As a side note, apparently some properties like the raycast2D's `collision mask` has no effect on the next inherited scene. Others like `enabled`, `cast to` and `exclude parent` does.

**Comment by RCastroAB** [comment] 2022-01-09 09:55
I managed to reproduce the bug with the collision mask as well. Could it not be the case, as discussed in #56584, that the grandchild scene was closed during the test?

**Comment by Calinou** [comment] 2022-09-01 16:42
Duplicate of https://github.com/godotengine/godot/issues/7984.

**Closed by Calinou** 2022-09-01 16:42 UTC
Labels: bug, topic:editor
