### ISSUE TITLE
CPUParticles2D not working when using GLES2

### ISSUE THREAD

**Issue by samuelpedrajas** [godotengine/godot#21839] opened 2018-09-07 15:42 UTC
**Godot version:**
Godot 3.1 Alpha

**OS/device including version:**
Linux Mint 18.3 with Intel(R) HD Graphics 520 (Skylake GT2)

**Issue description:**
CPUParticles2D work (can be seen) when using GLES3 but they don't when using GLES2. I can check the "Emitting" property but particles are not shown.

**Steps to reproduce:**
1. Download and open with Godot the attached project.
2. Play it in  the editor using GLES3: particles should be showing.
3. Change to GLES2 and run the project: particles are not shown.

**Minimal reproduction project:**
[cpu_particles_2d.zip](https://github.com/godotengine/godot/files/2361656/cpu_particles_2d.zip)

**Comment by kiidmale** [comment] 2018-12-19 13:13
The issue is still reproducible in alpha3.
According to cf834a22dc78950a9fba484a7f9db98da84cae59, it seems TYPE_MESH and TYPE_MULTIMESH handling is not implemented yet in RasterizerCanvasGLES2.
Hope it will be fixed before beta.

**Closed** 2018-12-27 23:41 UTC
Labels: bug, high priority, topic:rendering
