### ISSUE TITLE
Lerp function not work on ARM arch(Linux x11)

### ISSUE THREAD

**Issue by shar0** [godotengine/godot#34031] opened 2019-11-30 20:13 UTC
**Godot version:** 3.1.2

**OS/device including version:** Debian(Clockwork OS) based on ARM (Cortex-A7), Linux X11

**Issue description:** lerp() function not work.

**Steps to reproduce:** linear_vel.x = lerp(linear_vel.x, target_speed, 0.1)

**Minimal reproduction project:** Platformer 2D (Godot Official Project)

**Comment by akien-mga** [comment] 2019-11-30 21:15
What does it mean that it doesn't work?

**Comment by lawnjelly** [comment] 2019-12-01 11:52
Yes .. more info. If you place a breakpoint on this line when it is 'not working', what are the input values, and what is the result?

**Comment by shar0** [comment] 2019-12-01 13:27
In GodotScript lerp() return 0 and whatever params input.

**Comment by FeralBytes** [comment] 2019-12-02 00:18
@shar0 please provide your test input values and the matched output values, thank you.

**Comment by KoBeWi** [comment] 2020-11-15 00:18
Closing due to lack of update. Please comment if you can still reproduce this issue in the latest stable version of Godot.

**Closed by KoBeWi** 2020-11-15 00:18 UTC
Labels: bug, topic:core
