### ISSUE TITLE
Godot Performance Problems, a bug (in 2.1.4)?

### ISSUE THREAD

**Issue by abhaskumarsinha** [godotengine/godot#12458] opened 2017-10-28 13:25 UTC
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Operating System information:-
Microsoft Windows 7 (Service pack 1)
64 bit machine, but 32 bit OS installed
System Type:- x86 based pc
processor :- Intel (R) Core(TM) i3 CPU M370 @2.40GHz, 2399MHz, 2 cores and 4 logic processors
BIOS :- American Megatrends 8/17/2010
RAM :- 4 GB

Graphics Info;-

card - Intel (R) HD Graphics
Driver Version:- 8.15.10.2993
driver date;- 1/30/2013
 

**Issue description:**

Issue

My PC supports :- 
1. NFS MW (OpenGL 2) having 1 million poly in a scene. **It runs smoothly. Inspite of having large materials and shaders.**
2. half-life 2: Downfall (OpenGL 2) having 1.3 million poly in a scene. **Runs smoothly, Inspite of having large materials and shaders.**

**When i create a 70,000 poly object in godot 2.1.4 (stable) and run it. It laggs and runs at 4 - 5 frames per second.**

So, I've 2 questions in my mind:-
1. Is there any **terrain/vegetation/grass/trees** option in godot like other engines, which runs smoothly without having much increase in poly count.
2. How to fix it, and **get high poly in godot** in my system?

**Note:- In Unity OpenGL 2 version does't lags.**

**Steps to reproduce:**

**Link to minimal example project:**

[version_0.0.zip](https://github.com/godotengine/godot/files/1424258/version_0.0.zip)

**Comment by volzhs** [comment] 2017-10-28 14:01
maybe this will help.
https://github.com/marcosbitetti/grass_plugin_4_godot

**Comment by abhaskumarsinha** [comment] 2017-10-28 14:13
@volzhs does't works, the engine and game are laggy

**Comment by Zylann** [comment] 2017-10-28 14:20
You have to compare the number of draw calls, overdraw and the cost of shaders involved. Polycount isn't the only factor.

**Comment by abhaskumarsinha** [comment] 2017-10-28 14:31
@Zylann I did't had any shaders? Btw, what are draw cells? and overdraw?
How to reduce them?

**Comment by Zylann** [comment] 2017-10-28 14:43
Draw calls is the number of times the engines asks the graphics card to draw something. It's especially important if it switches between many shaders because it involves rebindings.
Overdraw is when you draw objects above others, it increases the amount of pixels the graphics card has to calculate. Especially when objects are transparent, because these pixels cannot be discarded with the Z-buffer so the full pixel shader code gets executed everytime. You can have some info on the viewport by enabling rendering info. Also verify which material you have, because Godot always use one even if you didn't set one manually.

**Comment by Zylann** [comment] 2017-10-28 14:44
I'll have a look at your project later I'm on a phone, it could also be a problem with the engine on your machine

**Comment by abhaskumarsinha** [comment] 2017-10-28 14:44
@Zylann I made did a fixed shader, which does't recieves light as well as shadow, its static everytime, still lags

**Comment by abhaskumarsinha** [comment] 2017-10-28 14:45
@Zylann please do have a look, unity gets better performance than godot, but I hate Unity too much.... :(

**Comment by Zylann** [comment] 2017-10-28 15:12
@abhaskumarsinha also try this on Godot 3.0, because your games may be using OpenGL 2.0 they might use extensions that Godot 2 doesn't use (like VBOs). Also there are many ways to draw models with different performance pros and cons. For example, grass may be 10000 blades to draw, it can be made 10 times faster with hardware instancing compared to individual mesh drawing.

**Comment by abhaskumarsinha** [comment] 2017-10-28 15:16
@Zylann bad luck, my PC does't supports OpenGL 3+, my PC supports only upto Open2 which godot 2.1 and godot 3.1 supports

**Comment by Zylann** [comment] 2017-10-28 15:18
I tested the project in 2.1.4, runs smoothly for me.
By any chance, do you have two graphics cards on your computer? Mine has two, one of them being very slow (but good to optimize battery) and it happened to me that Godot would run on the wrong one.

**Comment by abhaskumarsinha** [comment] 2017-10-28 15:18
@Zylann Please do tell me how to do instancing, i need it in godot, I've used multiple meshes of grass, bushes and trees.
I'm not sure that Godot 2.1.4 supports that.....

**Comment by abhaskumarsinha** [comment] 2017-10-28 15:18
@Zylann i have only one graphics card

**Comment by abhaskumarsinha** [comment] 2017-10-28 15:20
@Zylann games having higher poly and higher materials runs fine, unity also runs good with same mesh, so i think that there might be a problem in godot.....

**Comment by raymoo** [comment] 2017-10-28 16:50
@abhaskumarsinha Instancing can be done with `MultiMeshInstance` I think.

**Comment by Zylann** [comment] 2017-10-28 16:53
@abhaskumarsinha well as I showed you, the problem you have right now is something between Godot and your graphics driver, not something you would fix by changing your project...

**Comment by abhaskumarsinha** [comment] 2017-10-29 01:52
@zylann I see as when I remove grasses to decrease poly,  then it works fine.  No there is no lag in 2d.

**Comment by abhaskumarsinha** [comment] 2017-10-29 01:58
@zylann I removed about 10000 poly then it works fine. Again to test it,  I replaced it with a 10000 poly sphere to see if my model may have problems,  it Laggs again

**Comment by Zylann** [comment] 2017-10-29 02:19
@abhaskumarsinha is it becoming brutally slow when you reach above a fixed polycount, or is it gradually slower the more you add?

**Comment by abhaskumarsinha** [comment] 2017-10-29 06:59
@Zylann g**radually slower the more I add**, i modelled them in blender which did't lag even a very little.

## I did an experiment and found that even if **I copy and duplicate that model 35 times, still it does't lags**, Blender also works on OpenGL.

This shows that there is a large gap between Godot and unity/blender which also work on same machine on **OpenGL 2.1**

**_This bug should be fixed immediately as soon as possible!_**

Anyway, should I test this again in **Linux OS**, I also have a Linux, I've heard that those things which are slow in **_Linux are faster in windows and vice-versa_**?

**Comment by Zylann** [comment] 2017-10-29 15:47
I know it works fine for you in other software... I asked you to test this in Godot specifically to have more info about how this bug behaves in Godot on your machine, because I cannot reproduce this on mine, so I can't help much. Unless anyone else has info about this on an Intel GPU on OpenGL 2...

**Comment by abhaskumarsinha** [comment] 2017-10-29 16:09
@Zylann Strange, the model works fine on Linux' version but still lags on windows one.
for windows :- 
when I start my PC, it works upto 20 FPS for about 15 minutes and again slows down to 3 - 4 FPS. But, when I do same in Linux, it works perfectly........

**Comment by abhaskumarsinha** [comment] 2017-10-29 16:14
@Zylann i sent the same file to my friend, he tests it in Godot 3 alpha build, it works about 140 FPS when there are a lot of over draw, and ~240 FPS at good angles,

but when it tests them in Godot 2.1.4, FPS drops noticeably, also, the FPS count is not working......

Confirmed that this is a Bug in Godot!

**Comment by akien-mga** [comment] 2018-09-18 08:34
The 2.1 branch is no longer actively worked on by engine developers, unless critical fixes are needed for current games in production. As such we are now closing non-critical bug reports affecting only the 2.1 branch.

Please comment if this was incorrectly triaged and is still relevant in 3.x versions.

**Closed by akien-mga** 2018-09-18 08:34 UTC
Labels: discussion, topic:rendering
