### ISSUE TITLE
Calling RPC function results in error even though the function being called is marked with @rpc

### ISSUE THREAD

**Issue by BoomerDev** [godotengine/godot#59704] opened 2022-03-30 21:14 UTC
### Godot version

4.0.alpha5

### System information

Windows 10, Vulkan Clustered, GeForce RTX 2060

### Issue description

I am working on a multiplayer prototype with Godot 4.0 alpha5, and I have run into an issue with the RPC system. I am using a client-server model, and on my client, I have this test function:

@rpc
func some_function():
    print("Test function called.")

and on my server I have this code:

func _on_peer_connected(pid: int):
    rpc_id(pid, "some_function")

All my Godot multiplayer knowledge is coming from 3.x, so maybe this could be a bug, or me just being stupid.

### Steps to reproduce

none

Edit: I forgot to note that the error I keep getting is this: 'Unable to get the RPC configuration for the function "some_function" at path: "/root/Network". This happens when the method is missing or not marked for RPCs in the local script.'

**Comment by Calinou** [comment] 2022-03-30 22:01
@BoomerDev Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

**Comment by Noiros** [comment] 2022-04-02 20:20
Same problem here, if you send a rpc with out arg like : rpc(&"testfunc")

**Comment by renacava** [comment] 2022-04-22 13:28
try putting @rpc before any functions that contain an rpc_id().

**Comment by Faless** [comment] 2022-05-23 08:56
Likely a duplicate of #59939 / https://github.com/godotengine/godot/issues/59972#issuecomment-1091971779

**Comment by Faless** [comment] 2022-07-16 00:02
Closing in favor of #59939 which has more details.

**Closed by Faless** 2022-07-16 00:02 UTC
Labels: bug, topic:network, topic:multiplayer
