### ISSUE TITLE
vulkan - 4.0 dev - shaders sometimes fail to compile

### ISSUE THREAD

**Issue by supagu** [godotengine/godot#34343] opened 2019-12-14 00:13 UTC
**Godot version:** Godot vulkan branch

**OS/device including version:** Arch Linux/Manjaro

**Issue description:** I have noticed on different levels of my game some shaders will fail to compile, while on other levels I load the shader will compile fine.
Typically the editor seems to suffer this problem far less, ie. if I open my level to edit it seems far less likely to fail.

**Steps to reproduce:**
**Minimal reproduction project:**
I have some sample C++ material here that seems to fail to compile rather a lot
[https://drive.google.com/file/d/19onSdZR23YJfLb4yvXqralKUX_tsj8qF/view?usp=sharing](https://drive.google.com/file/d/19onSdZR23YJfLb4yvXqralKUX_tsj8qF/view?usp=sharing)

The compile error I get:
```
At: servers/visual/rasterizer_rd/shader_rd.cpp:346.
    ERROR: _compile_variant: Failed parse:
    ERROR: 0:355: 'location' : overlapping use of location 11
    ERROR: 1 compilation errors.  No code generated.
```

the problematic line it is complaining about:
`varying float 	vertex_height;`

**Comment by KoBeWi** [comment] 2020-11-13 00:22
@supagu Is the issue still valid in the newest master?

**Comment by supagu** [comment] 2020-11-13 04:32
Hey @KoBeWi I unfortunately don't have time to look at this issue any time soon. I will check again next year when I hopefully have some time to get back to working on my game.

**Comment by KoBeWi** [comment] 2020-11-13 08:33
So it can be assumed the issue is fixed by that time. Comment if you can still reproduce.

**Closed by KoBeWi** 2020-11-13 08:33 UTC
Labels: bug, topic:rendering
