### ISSUE TITLE
Can't evaluate string variables in if statements using the "not" operator

### ISSUE THREAD

**Issue by sundle** [godotengine/godot#75911] opened 2023-04-10 21:27 UTC
### Godot version

4.0.2.stable

### System information

Linux

### Issue description

The following produces the Parser Error: Invalid operand of type "String" for unary operator "not".

`var foo1 : String = ""`
`if not foo1:`
`    print("bar")`

This is inconsistent behaviour, as changing foo1 to an int works fine.

`var foo1 : int = 0`
`if not foo1:`
`    print("bar")`

### Steps to reproduce

See description.

### Minimal reproduction project

N/A

**Comment by Calinou** [comment] 2023-04-10 21:42
Duplicate of https://github.com/godotengine/godot/issues/44688.

**Closed by Calinou** 2023-04-10 21:42 UTC
Labels: topic:gdscript
