### ISSUE TITLE
MeshInstance3D's mesh slot doesn't retain model after restarting the editor

### ISSUE THREAD

**Issue by DelinWorks** [godotengine/godot#57053] opened 2022-01-22 02:33 UTC
### Godot version

4.0.dev

### System information

Windows 10, Vulkan, GeForce GTX 1060 3GB

### Issue description

when creating a MeshInstance3D node and putting a mesh inside the mesh field, when restarting the editor the field becomes empty, even when saving the scene and then restarting

### Steps to reproduce

1. Create project and put MeshInstance3D node 
2. assign a model to the node (.res format)
3. save as a scene and restart the editor
4. the model is not there and when you look at the mesh field of the mesh node it's empty

### Minimal reproduction project

[#57053 Issue 4.0.zip](https://github.com/godotengine/godot/files/7918995/57053.Issue.4.0.zip)

**Comment by Calinou** [comment] 2022-01-22 15:03
@DelinWorks Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

**Comment by DelinWorks** [comment] 2022-01-22 15:23
Haven't tested it yet, I'll do when I have the time

**Comment by DelinWorks** [comment] 2022-01-22 17:51
3.4.2 doesn't have this issue, but 4.0 does, only when using the model provided in the mini project and clicking on the fbx file and clicking on the arrayMesh and enabling Save To File .res format, the problem didn't happen with other models except for this model, also it says some weird error when I run the editor in the console that I can't digest

![image](https://user-images.githubusercontent.com/45469625/150649768-2d605945-b910-473c-891e-8050918b5ab0.png)

```
Godot Engine v4.0.dev.custom_build (c) 2007-2022 Juan Linietsky, Ariel Manzur & Godot Contributors.
--- Debug adapter server started ---
  In Object of type 'InspectorDock': Attempt to connect nonexistent signal 'property_keyed' to callable 'AnimationPlayerEditorPlugin::_property_keyed'.
  In Object of type 'InspectorDock': Attempt to connect nonexistent signal 'edited_object_changed' to callable 'AnimationTrackEditor::update_keying'.
--- GDScript language server started ---
Switch Scene Tab
Switch Scene Tab
  core\io\resource_format_binary.cpp:939 - res://Models/vikree2aw_LOD0.fbx: In external resource #0, invalid UUID: uid://odvgllbrndhp - using text path instead: res://Models/model_001.res
  Storage buffer supplied (binding: 1) is invalid.
  drivers\vulkan\rendering_device_vulkan.cpp:7215 - Condition "!uniform_set" is true.
  Storage buffer supplied (binding: 1) is invalid.
  drivers\vulkan\rendering_device_vulkan.cpp:7215 - Condition "!uniform_set" is true.
  Storage buffer supplied (binding: 1) is invalid.
  drivers\vulkan\rendering_device_vulkan.cpp:7215 - Condition "!uniform_set" is true.
  Storage buffer supplied (binding: 1) is invalid.
  drivers\vulkan\rendering_device_vulkan.cpp:7215 - Condition "!uniform_set" is true.
  Storage buffer supplied (binding: 1) is invalid.
  drivers\vulkan\rendering_device_vulkan.cpp:7215 - Condition "!uniform_set" is true.
  Storage buffer supplied (binding: 1) is invalid.
  drivers\vulkan\rendering_device_vulkan.cpp:7215 - Condition "!uniform_set" is true.
  Storage buffer supplied (binding: 1) is invalid.
  drivers\vulkan\rendering_device_vulkan.cpp:7215 - Condition "!uniform_set" is true.
  Storage buffer supplied (binding: 1) is invalid.
  drivers\vulkan\rendering_device_vulkan.cpp:7215 - Condition "!uniform_set" is true.
  Storage buffer supplied (binding: 1) is invalid.
  drivers\vulkan\rendering_device_vulkan.cpp:7215 - Condition "!uniform_set" is true.
  Storage buffer supplied (binding: 1) is invalid.
  drivers\vulkan\rendering_device_vulkan.cpp:7215 - Condition "!uniform_set" is true.
  Storage buffer supplied (binding: 1) is invalid.
  drivers\vulkan\rendering_device_vulkan.cpp:7215 - Condition "!uniform_set" is true.
  Storage buffer supplied (binding: 1) is invalid.
  drivers\vulkan\rendering_device_vulkan.cpp:7215 - Condition "!uniform_set" is true.
  Storage buffer supplied (binding: 1) is invalid.
  drivers\vulkan\rendering_device_vulkan.cpp:7215 - Condition "!uniform_set" is true.
  Storage buffer supplied (binding: 1) is invalid.
  drivers\vulkan\rendering_device_vulkan.cpp:7215 - Condition "!uniform_set" is true.
  Storage buffer supplied (binding: 1) is invalid.
  drivers\vulkan\rendering_device_vulkan.cpp:7215 - Condition "!uniform_set" is true.
  Storage buffer supplied (binding: 1) is invalid.
  drivers\vulkan\rendering_device_vulkan.cpp:7215 - Condition "!uniform_set" is true.
  Storage buffer supplied (binding: 1) is invalid.
  drivers\vulkan\rendering_device_vulkan.cpp:7215 - Condition "!uniform_set" is true.
  Storage buffer supplied (binding: 1) is invalid.
  drivers\vulkan\rendering_device_vulkan.cpp:7215 - Condition "!uniform_set" is true.
```

[#57053 Issue 4.0.zip](https://github.com/godotengine/godot/files/7918956/57053.Issue.4.0.zip)

**Comment by KoBeWi** [comment] 2022-06-04 00:48
Can't reproduce in alpha 9
The scene in MRP has the model included normally. Creating a new one also works correctly.
@DelinWorks Can you confirm if this is fixed?

**Comment by KoBeWi** [comment] 2023-02-25 01:15
No answer, closing.

**Closed by KoBeWi** 2023-02-25 01:15 UTC
Labels: bug, topic:editor, topic:3d
