### ISSUE TITLE
Black noise in GLES2 when rendering on Oculus Quest

### ISSUE THREAD

**Issue by Tubeliar** [godotengine/godot#44546] opened 2020-12-20 11:55 UTC
**Godot version:**
3.2.3

**OS/device including version:**
Android/Oculus Quest 1 GLES2

**Issue description:**
Black noise appears on surfaces. Enabling high precision (Enable High Float.Andoid) turns the noise into smoothened black areas. The issue only appears when deployed on the Oculus Quest. It doesn't show up in the editor or in desktop builds. The tiled rendering strategy of the Quest is clearly visible as the noise seems to be different on each tile.
[A youtube demonstration with standard precision](https://www.youtube.com/embed/LlzcAJu3AGU)
[A youtube demonstration with high precision](https://www.youtube.com/embed/euSqJAeUq50)

**Minimal reproduction project:**
[GodotGuardian.zip](https://github.com/godotengine/godot/files/5720842/GodotGuardian.zip)

**Related issues:**
https://github.com/godotengine/godot/issues/43667
The artifacts look similar but this issue is not related to reflections. It appears even if I disable specularity on the material.

https://github.com/GodotVR/godot_oculus_mobile/issues/68
Again similar looking artifacts but this issue doesn't seem to be related to the material's roughness.

**Comment by Tubeliar** [comment] 2020-12-20 11:58
I first reported this issue in this forum thread: https://godotforums.org/discussion/comment/44401

**Comment by Calinou** [comment] 2020-12-20 14:03
This may be fixed by https://github.com/godotengine/godot/pull/44489.

**Comment by ForestKatsch** [comment] 2020-12-20 16:47
Yes, #44489 should solve this issue. In fact, I first encountered this issue on Oculus Quest, and the fix was tested on Oculus Quest.)

**Comment by clayjohn** [comment] 2020-12-20 18:04
Duplicate of https://github.com/godotengine/godot/issues/43667

Will be fixed by https://github.com/godotengine/godot/pull/44489

**Closed by clayjohn** 2020-12-20 18:04 UTC
Labels: bug, topic:rendering
