### ISSUE TITLE
Crash on renaming an audio bus

### ISSUE THREAD

**Issue by Lord-Vlad** [godotengine/godot#74981] opened 2023-03-16 10:59 UTC
### Godot version

v4.0.stable.flathub (92bee43ad)

### System information

Fedora 37 KDE, Compatibility, NVIDIA

### Issue description

Crash on naming an  audio bus.

### Steps to reproduce

1. Got to the audio tab.
2. Add a new audio bus.
3. Change the name and hit enter.
4. Godot freezes for a second and then crashes.

### Minimal reproduction project

N/A

**Comment by AThousandShips** [comment] 2023-03-16 11:04
Duplicate of #74374, fixed in #74560

**Comment by YuriSizov** [comment] 2023-03-16 11:06
Yes indeed, thanks.

**Closed by YuriSizov** 2023-03-16 11:06 UTC
