### ISSUE TITLE
Error when freeing MeshInstances built in another thread on the main thread.

### ISSUE THREAD

**Issue by drwhut** [godotengine/godot#46463] opened 2021-02-27 01:02 UTC
**Godot version:**
Godot 3.2.3-stable

**OS/device including version:**
Linux Mint 20.1

**Issue description:**
I'm not sure whether this is a problem with Godot, but I'm pretty sure the code should be ok, hence my doubt - I'm trying to use a separate thread to generate mesh instances that have textures on them, and I'm sending the results to the main thread to add them to the scene tree. But some of these meshes I don't want anymore by the time they are built, so I free them in the main thread.

The problem somehow arises when I free the mesh instances in the main thread, as errors like the following get spammed out:
```
ERROR: get: Condition "!id_map.has(p_rid.get_data())" is true. Returned: __null
   At: ./core/rid.h:150.
ERROR: material_set_param: Condition "!material" is true.
   At: drivers/gles3/rasterizer_storage_gles3.cpp:2648.
```

```
ERROR: getornull: Condition "!id_map.has(p_rid.get_data())" is true. Returned: __null
   At: ./core/rid.h:160.
ERROR: mesh_clear: Condition "!mesh" is true.
   At: drivers/gles3/rasterizer_storage_gles3.cpp:4327.
```

This happens with both GLES2 and GLES3.

**Steps to reproduce:**
1. Create a script.
2. Start a thread that generates meshes with materials (that also include a texture) from scratch.
3. Send the meshes to the main thread with a mutex.
4. Free the meshes in the main thread.

**Minimal reproduction project:**
[ThreadBugProject.zip](https://github.com/godotengine/godot/files/6053419/ThreadBugProject.zip)

**Comment by Calinou** [comment] 2021-02-27 01:48
See https://github.com/godotengine/godot/issues/20964.

**Comment by drwhut** [comment] 2021-02-27 02:10
Ah, I followed the issue you mentioned, and switching the `Rendering/Thread/thread_model` setting to multi-threaded worked for the project I provided! I didn't know that setting existed before.

My personal project seems to straight-up crash with this fix though, but I'm guessing that's a separate issue.

Thank you!

**Comment by Calinou** [comment] 2021-02-27 02:12
@drwhut Good to hear it worked :slightly_smiling_face:  I'll close this as a duplicate of #20964 then
.

**Closed by Calinou** 2021-02-27 02:12 UTC
