### ISSUE TITLE
Glow not supported warning on opening Compatibility project with no glow

### ISSUE THREAD

**Issue by lostminds** [godotengine/godot#85375] opened 2023-11-26 10:21 UTC
### Godot version

4.2.rc2

### System information

macOS 14.1

### Issue description

If you create a new Mobile renderer project and then change the project to Compatibility renderer you get a warning when loading the project in the editor:

`servers/rendering/storage/environment_storage.cpp:387 - Glow is not supported when using the GL Compatibility backend yet. Support will be added in a future release. (User)`

Even if you don't have any environments using glow in the project and only view 2d UI scenes. This only happens if you create the project as non-compatibility, so I'm guessing it's then adding some default environment somewhere with glow enabled that is generating this warning when loaded, even if this is not used in the game or any scenes. 
Maybe it's the editor preview environment that is loaded with glow enabled?

### Steps to reproduce

- Create a new Mobile renderer project
- Change it to Compatibility renderer
- Open the project and get the warning above, even though no glow is used in project

### Minimal reproduction project

[NoGlow.zip](https://github.com/godotengine/godot/files/13466488/NoGlow.zip)

**Comment by AThousandShips** [comment] 2023-11-26 10:32
Is the glow option enabled in the environment settings in the 3D editor? It defaults to enabled when non-compatibility and is saved, so it is likely the cause of this

**Comment by lostminds** [comment] 2023-11-26 11:04
> Is the glow option enabled in the environment settings in the 3D editor?

Yes, this seems like the cause. However, the project doesn't have any 3d scenes, so I've not used the 3d editor. Despite this it seems that for each scene loaded this default 3d editor environment is loaded, even though they are not 3d scenes and the 3d editor is not open. I can open the 3d editor for a scene and open the settings for the environment and toggle off glow and save to toggle it off for this scene, which removed the warning if I open only that scene. But that doesn't seem to affect other scenes, so opening any other scene will get the warning again. The change doesn't seem to be saved in the scene file as I don't see any change in the file for this preview environment change, so I'm guessing the override for this scene and what defaults to use are saved somewhere else?

**Comment by geekley** [comment] 2024-01-10 19:36
There should be a way to edit the default preview environment used in the editor for every new scene. It would solve this and other problems. I hate the brown ground. And I don't want to set a runtime default environment in the project.

**Comment by Calinou** [comment] 2024-02-24 18:37
Glow was implemented by https://github.com/godotengine/godot/pull/87360, so this warning is no longer printed. Closing.

**Closed by Calinou** 2024-02-24 18:37 UTC
Labels: bug, topic:rendering, topic:editor, confirmed
