### ISSUE TITLE
Method keyframes don't call method when playing in editor

### ISSUE THREAD

**Issue by GammaGames** [godotengine/godot#24438] opened 2018-12-18 04:57 UTC
**Godot version:**
v3.1.alpha.official (alpha 3)

**OS/device including version:**
elementary OS 5.0 Juno

**Issue description:**
I have an AnimationPlayer that calls custom methods at set intervals. When previewing the animation in the editor the methods aren't called, but when running the game they work as expected.

**Steps to reproduce:**
1. Create method track
2. Add keyframes for methods
3. Play animation in editor, method's side effects aren't seen
4. Play game with F5, method's side effects are seen

In editor:
![peek 2018-12-17 21-51](https://user-images.githubusercontent.com/7832163/50132920-a1fa1c00-0246-11e9-8624-70142d902d41.gif)

In game:
![peek 2018-12-17 21-52](https://user-images.githubusercontent.com/7832163/50132927-a7576680-0246-11e9-8850-e4a2f2a444da.gif)

**Comment by JFonS** [comment] 2018-12-18 13:45
Is the script with the method marked as a `tool` script?

**Comment by GammaGames** [comment] 2018-12-18 14:30
Is that as simple as adding the `tool` keyword to the top of the script? I tried that and it still does nothing, even after editor restart.

**Comment by akien-mga** [comment] 2018-12-19 08:39
I think this might be on purpose, as those methods may have an impact on your scene that you don't want in the editor, only in the running game. E.g. if your die animation calls `queue_free()` at the last frame, should it delete the node in your scene?

**Comment by rcorre** [comment] 2019-05-06 14:30
Dupe of #21388?

**Comment by Calinou** [comment] 2019-08-19 13:18
Duplicate of #21388.

**Closed by Calinou** 2019-08-19 13:18 UTC
Labels: discussion, topic:editor
