### ISSUE TITLE
Double size Godot, when the window goes from an High DPI screen to a standard screen one

### ISSUE THREAD

**Issue by fab918** [godotengine/godot#39488] opened 2020-06-12 21:26 UTC
**Godot version:**
Godot 3.2.2 RC 1

**OS/device including version:**
Mac OS Catalina

**Issue description:**
My laptop has a high dpi screen, but my external monitor not.

If I open Godot on the high dpi screen, et move the window in the other, the window will be double sized. (it does the opposite if on the opens on the other monitor)

**Steps to reproduce:**
Open Godot, move the window to another screen with a different DPI resolution.

**Comment by Calinou** [comment] 2020-06-12 21:38
Duplicate of #30880 (and possibly other issues).

**Closed by Calinou** 2020-06-12 21:38 UTC
