### ISSUE TITLE
Godot editor using ~70% cpu. (macOS) Latest build as of 10-23-2017

### ISSUE THREAD

**Issue by ismyhc** [godotengine/godot#12366] opened 2017-10-24 02:03 UTC
macOS Sierra
10.12.6 (16G29)
MacBook Pro (Retina, 13-inch, Late 2013)
2.4 GHz Intel Core i5
8 GB 1600 MHz DDR3
Intel Iris 1536 MB

I've compiled for OSX as the docs list.
```
user@host:~/godot$ scons platform=osx
user@host:~/godot$ cp -r misc/dist/osx_tools.app ./Godot.app
user@host:~/godot$ mkdir -p Godot.app/Contents/MacOS
user@host:~/godot$ cp bin/godot.osx.opt.tools.64 Godot.app/Contents/MacOS/Godot
user@host:~/godot$ chmod +x Godot.app/Contents/MacOS/Godot
```

Editor uses around 70% cpu. 

[zuexeuz.zip](https://github.com/godotengine/godot/files/1409300/zuexeuz.zip)

**Comment by mhilbrunner** [comment] 2017-10-24 12:07
I can confirm that at least on Windows x64, the current master@`4396712` idles at 0-1% with a project open in the editor. Seems to be a Mac OS X specific?

**Comment by marcelofg55** [comment] 2017-10-24 12:33
I tested it with OS X Yosemite and for me it idles at 1-2%.

**Comment by Zylann** [comment] 2017-10-24 12:39
@ismyhc is there any message in the console?

**Comment by ismyhc** [comment] 2017-10-24 13:10
@Zylann no messages in the console. I think its related to the project I attached. I Just opened a new project and the editor hovers around 6-8 %. Could you try loading the project I attached. Its very possible I may have changed some setting that may be causing the issue. Im going to recreate the project from scratch. Its very small.

**Comment by bruvzg** [comment] 2017-10-24 13:31
macOS 10.13 (17A405): 2-3% idle with attached project opened.

**Comment by ismyhc** [comment] 2017-10-24 13:53
@bruvzg Unfortunately Im not in a position to upgrade to High Sierra quite yet. :( Im trying to figure out what it is about the project that is causing the issue.

**Comment by eon-s** [comment] 2017-10-25 02:36
This is for master, right? there are other reports of apparently the same issue on 2.1 #8766

**Comment by ismyhc** [comment] 2017-10-25 12:30
@eon-s yes, this is for master as of 2 days ago. Im going to try and do more testing today.

**Comment by ismyhc** [comment] 2017-10-25 17:14
Is this output correct?

OpenGL ES 3.0 Renderer: Intel Iris OpenGL Engine
GLES3: max ubo light: 409
GLES3: max ubo reflections: 455, ubo size: 144
ARVR: Registered interface: Native mobile

Should my mac laptop be using OpenGL ES 3.0? I wouldn't expect be using OpenGL ES.

**Comment by mhilbrunner** [comment] 2017-10-25 17:28
I think Godot 3.0 always uses OpenGL ES 3.0, yes.

**Comment by bruvzg** [comment] 2017-10-25 17:33
@ismyhc It is correct, same renderer use OpenGL 3.0+ on desktop platforms and GL ES 3.0 on mobile/web.

**Comment by ismyhc** [comment] 2017-10-25 17:52
@mhilbrunner @bruvzg ah, okay. Well I just started a brand new project. One main scene with nothing in it, one scene which is just a node with script attached that draws rect and boom, back up to ~70% cpu. Deleted all the scenes, and still stays at ~70%. Im baffled as to what is causing this.

**Comment by bruvzg** [comment] 2017-10-25 19:10
@ismyhc Try using profiler: `Xcode` > `Open Developer Tool` > `Instruments` > `Time Profiler`, maybe it will give some additional information.

**Comment by ismyhc** [comment] 2017-10-25 20:35
@bruvzg Okay, I did upgrade to High Sierra, but still same issue. I opened up Time Profiler and heres a screenshot. 

This seems like the start of it: RasterizerCanvasGLES3::_canvas_item_render_commands(RasterizerCanvas::Item*, RasterizerCanvas::Item*, bool&)

<img width="1261" alt="screen shot 2017-10-25 at 4 31 23 pm" src="https://user-images.githubusercontent.com/840551/32021829-8c6bc98a-b9a2-11e7-8c16-c2d75c9bb15c.png">

**Comment by ismyhc** [comment] 2017-10-26 12:38
Just an FYI. Alpha 1 doesn't have this problem. Im going to start backtracking master to see if I can determine when the problem starts.

**Comment by akien-mga** [comment] 2017-10-26 12:40
Before attempting a bisect, make sure to build alpha 1 (f55211ae0dc202cc015c247495af8e05af81b24b) locally to confirm that it's not affected by this issue, as it's possible that official binaries work fine but that you self-compiled ones are problematic.

**Comment by bruvzg** [comment] 2017-10-26 13:08
>This seems like the start of it: 
>RasterizerCanvasGLES3::_canvas_item_render_commands

Maybe v-sync is not working (it is [enabled](https://github.com/godotengine/godot/blob/master/main/main.cpp#L115) by default). Related to #12355?

**Comment by reduz** [comment] 2017-10-26 13:23
Is the spinning wheel in Godot top right corner spinning when you see this
cpu usage, even if you do nothing?

**Comment by ismyhc** [comment] 2017-10-26 13:26
@reduz yes, spinning wheel is always spinning. Im building alpha-1 as @akien-mga suggested right now to see if the issue is happening from my local build.

**Comment by ismyhc** [comment] 2017-10-26 13:42
1. I can confirm building alpha 1 (f55211a) locally works as expected. No cpu issues.
2. As of Sep 27, and commit 4f39ce3 the cpu issues DO exist.

**Comment by ismyhc** [comment] 2017-10-26 14:39
So I just noticed something. When clicking the spinner, the option "Update Always" is checked. If i set this to "Update Changes", the cpu usage hovers around 8% - 12%. Im not sure if this is the fix, but it does help.

**Comment by reduz** [comment] 2017-10-26 16:08
That is not a bug, it's a feature...

**Comment by ismyhc** [comment] 2017-10-26 19:27
@reduz im satisfied with that answer :)

**Comment by reduz** [comment] 2017-10-26 19:29
It's supposed to be enabled by default.. (update changes)

**Comment by ismyhc** [comment] 2017-10-26 19:40
@reduz I think what happened was that I not knowing what it meant, clicked on it and it popped up a alert that said it was a deprecated setting. I must have assumed since the alert popped up that the change didn't occur so I never thought twice about it, but in fact it was changed to (update always).

Anyways, mostly just  confusion on my part. Feel free to close this ticket. :)

**Comment by akien-mga** [comment] 2017-10-26 19:57
Well no, the 70% CPU usage is not a feature :) What @reduz was referring to is the Update Always / Update Changes and its impact on CPU usage, which is expected. But 8%-12% CPU usage in Update Changes and 70% in Update Always is a bug.

**Comment by eon-s** [comment] 2017-10-27 02:33
Wait, the popup that talks about the deprecated function actually turns on the deprecated function? 

Why not disable it at all if should not be used anymore?

**Comment by akien-mga** [comment] 2017-10-27 05:48
> Why not disable it at all if should not be used anymore?

Because it's still needed in some cases due to bugs, so we need to be able to enable it to debug and fix bugs.

**Comment by Zylann** [comment] 2017-10-27 09:12
@eon-s And this #11030

**Comment by eon-s** [comment] 2017-10-27 16:17
@akien-mga ah, ok, but the popup message is kind of confusing, like meaning the option is not working, maybe a "deprecated" or "for testing only" text on the menu may be better.

**Comment by volzhs** [comment] 2017-11-20 14:46
Intel(R) Core(TM) i5-6600 CPU @ 3.30GHz
GeForce GTX 670
Ubuntu 16.04
master 4d5b828

now spinner keeps rotating and editor uses 50% cpu usage on my machine on idle in Update changes setting. :confused:

**Comment by bruvzg** [comment] 2017-11-20 15:07
> now spinner keeps rotating and editor uses 50% cpu usage

Same on macOS.

**Comment by volzhs** [comment] 2017-11-21 10:35
with c846e49a7d3439d9aef5d499ad403304d89a3b3c
editor uses 4~5% CPU now.

**Comment by icnikerazah** [comment] 2017-11-25 22:50
Macbook Pro 15 (2016) intel core i7 - Sierra 10.12.6
Editor uses %17 cpu on idle. and cpu temp too high.

**Comment by reduz** [comment] 2017-11-25 22:55
Is the spinning wheel spinning while this happens?

**Comment by icnikerazah** [comment] 2017-11-26 16:38
this is happens random, between %5 and % 20, empy project on idle. (sorry for my english)
<img width="222" alt="ekran resmi 2017-11-26 19 30 04" src="https://user-images.githubusercontent.com/33985414/33242116-d9874b70-d2e0-11e7-88b0-7636a24fdc90.png">

**Comment by reduz** [comment] 2017-11-26 16:40
Can you enable the update spinner and set to update changes?

**Comment by icnikerazah** [comment] 2017-11-26 16:47
spinner is not affecting cpu.  This is like a Editor gui problem or driver, When mouse scroll zoom out in viewport cpu is %17  when minimize to dock cpu %5

**Comment by reduz** [comment] 2017-11-26 16:53
alright, but unless you update the spinner and set it to update changes,
then tell me what's going on (if it's spinning or not), it's difficult to
help.
Also you have VSync enabled?

**Comment by icnikerazah** [comment] 2017-11-26 16:55
it's spinning but not always,

**Comment by reduz** [comment] 2017-11-26 17:05
Do you see high CPU usage when it's not spinning? Also again, do you have
VSync off?

**Comment by icnikerazah** [comment] 2017-11-26 17:21
anyway forget it. i don't want to test unstable builds. thank you for your attention.

**Comment by akien-mga** [comment] 2018-08-28 15:39
Closing as there were no updates since reduz's questions a year ago.

**Closed by akien-mga** 2018-08-28 15:39 UTC
Labels: platform:osx, topic:editor

**Comment by L3V147H4N** [comment] 2020-12-26 19:54
I'm testing Godot 3.2.3.stable.official on macOS Catalina 10.15.7 and on some projects the Spinner wheel spins all the time in all in all scenes/viewports even on Script editor. (it is set to Update when Changed)
I started a new project and now it works correctly so it seems the issue gets stuck per-project

**Comment by Calinou** [comment] 2020-12-26 21:24
@L3V147H4N This is already being tracked in https://github.com/godotengine/godot/issues/39758. See [this page](https://docs.godotengine.org/en/latest/about/troubleshooting.html#the-editor-runs-slowly-and-uses-all-my-cpu-and-gpu-resources-making-my-computer-noisy) for a workaround.
