### ISSUE TITLE
Godot improperly imports meshes

### ISSUE THREAD

**Issue by bkeys** [godotengine/godot#7691] opened 2017-01-31 19:03 UTC
**Operating system or device - Godot version:**
Fedora 25, Godot 2.1.2

**Issue description:**
Importing my mesh (with either the .obj exporter or the .dae exporter) causes issues 
![selection_075](https://cloud.githubusercontent.com/assets/12195202/22479943/ab8b20ca-e7bd-11e6-9dd0-8257905d32d9.png)
You can see the side of my building being gone.

![selection_076](https://cloud.githubusercontent.com/assets/12195202/22479970/c4b86c9c-e7bd-11e6-8f18-9948ec91e314.png)
There is also issues with my ice cream truck (the brown area around the wheels). It shows up on the back wheels and slightly on the front (the brown area is not supposed to be there at all, at least visually). Triangulating the mesh pre-export in Blender helps but does not solve the issue.

**Steps to reproduce:**
No real reliable way but for the most part there is a chance of this happening on a somewhat complex shape. And re importing does not solve the problem.

**Comment by reduz** [comment] 2017-01-31 19:15
if exporting from Blender, use the triangulate option

**Comment by bkeys** [comment] 2017-01-31 19:45
I mentioned that the triangulate option helps (sometimes), but does not solve the issue. Perhaps in the collada exporter we should make the triangulate option be "on" by default?

**Comment by bkeys** [comment] 2017-01-31 20:13
Out of curiosity I re exported my city and the apartment blocks still have their missing sides

**Comment by Zylann** [comment] 2017-01-31 20:43
Are they missing or are they visible looking on the other side?

**Comment by bkeys** [comment] 2017-01-31 21:44
@Zylann Yes I am sure because I can drive through my city with the car and see the sides of the building missing (this also applies to my ice cream truck)

**Comment by reduz** [comment] 2017-02-01 01:26
did you also check that normals are pointing to the correct sides?

**Comment by bojidar-bg** [comment] 2017-03-10 14:43
Bump, this got stale. @bkeys, can you confirm that normals are pointing outside, or that a double-sided material fixes it?

**Comment by Noshyaar** [comment] 2018-04-10 16:09
First of all thank you for your report and sorry for the delay.

We released Godot 3.0 in January 2018 after 18 months of work, fixing many old issues either directly, or by obsoleting/replacing the features they were referring to.

We still have hundreds of issues whose relevance/reproducibility needs to be checked against the [current stable version](https://godotengine.org/download), and that's where you can help us.
**Could you check if the issue that you described initially is still relevant/reproducible in Godot 3.0 or any newer version, and comment about it here?**

For bug reports, please also make sure that the issue contains detailed steps to reproduce the bug and, if possible, a zipped project that can be used to reproduce it right away. This greatly speeds up debugging and bugfixing tasks for our contributors.

Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

Thanks in advance.

*Note: This message is being copy-pasted to many "stale" issues (90+ days without activity). It might happen that it is not meaningful for this specific issue or appears oblivious of the issue's context, if so please comment to notify the Bugsquad about it.*

**Comment by akien-mga** [comment] 2019-04-15 14:21
> Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

As there was no update since the previous post, we close this issue.

If it is still relevant in the way it was described and discussed above, please comment to ask for it to be reevaluated. If it is only partly relevant, or if the original issue has changed, it would be better to open a new issue (potentially referring to this one) focused on the current state.

**Closed by akien-mga** 2019-04-15 14:21 UTC
Labels: bug, topic:core
