### ISSUE TITLE
How to save copy of a project?

### ISSUE THREAD

**Issue by brylie** [godotengine/godot#17544] opened 2018-03-15 20:50 UTC
**Godot version:** 3.0.2

**OS/device including version:** Ubuntu 17.10

**Issue description:**
I would like to duplicate a project in Godot. How can I save a copy of the project from the Godot UI?

**Comment by Zylann** [comment] 2018-03-15 22:22
How to copy a project:
1) Copy the folder of that project in your system's file explorer
2) Open the project manager
3) Click "import"
4) Select the copy and validate
5) You now have both projects in the project manager

Would your request rather be duplicating projects from the manager, given it's trivial to do it in explorer? Or do you really want to do it from the editor?

**Comment by brylie** [comment] 2018-03-16 11:49
> Would your request rather be duplicating projects from the manager, given it's trivial to do it in file manager? Or do you really want to do it from the editor?

It seems that both options would be relatively common:
- duplicate project from project manager
- save project as copy from the editor ('save as...')

**Comment by sdfgeoff** [comment] 2018-03-16 12:52
I can only see two cases when you want to save a copy of a project:

1. When you are making lots of similar games
2. When you are making backups of your project

The first is better served by creating multiple levels inside a single game, and the second is better solved by a version control system such as git.

What do you intend to do with your copies of your project? Is there a reason that isn't better solved by the methods above?

**Comment by groud** [comment] 2018-03-16 13:50
Honestly I don't see the point in duplicating project, that's not something you do often.
For me just copy-pasting the folder is simple enough, there's no need to make it built-in

**Comment by vnen** [comment] 2018-03-16 14:03
This is a duplicate of #9632.

**Closed by vnen** 2018-03-16 14:03 UTC
Labels: discussion, feature proposal, topic:editor
