### ISSUE TITLE
Shader error

### ISSUE THREAD

**Issue by SmithJohnFirst** [godotengine/godot#21981] opened 2018-09-11 18:09 UTC
**Godot version:**
3.0.6 and 3.1 alpha

**OS/device including version:**
Windows 7

**Issue description:**
In my project, I added a shader to one object. Then I got an error:
```
Expected 'shader_type' at the beginning of shader.
RasterizerStorageGLES3::_update_shader: Condition ' err != OK ' is true.
drivers\gles3\rasterizer_storage_gles3.cpp:1697
```
Then I created a new scene. Added the same shader. The error was no longer there.

**Comment by 0nepixel** [comment] 2018-09-11 20:06
well, there's the solution "Expected shader_type" you have to put the shader_type, canvas_item, spatial, etc
![image](https://user-images.githubusercontent.com/22958303/45384645-f442f580-b5e4-11e8-9b87-da083fe236d5.png)

**Comment by vnen** [comment] 2018-09-11 20:58
Would be nice to have a sample project or at least the problematic shader code.

**Comment by SmithJohnFirst** [comment] 2018-09-12 18:41
I ran the test and found out that this error occurs if the scene is loaded using multiple threads.
http://docs.godotengine.org/en/3.0/tutorials/io/background_loading.html?highlight=resource-queue#id1

**Comment by Zireael07** [comment] 2018-09-12 18:47
@SmithJohnFirst I think that was already reported then.

**Comment by VitaZheltyakov** [comment] 2018-09-12 18:48
https://github.com/godotengine/godot/issues/15998

**Comment by akien-mga** [comment] 2018-09-12 19:47
Thanks, duplicate of #15998 indeed.

**Closed by akien-mga** 2018-09-12 19:47 UTC
