### ISSUE TITLE
possible bug when calling new() after calling queuefree()

### ISSUE THREAD

**Issue by timvheck** [godotengine/godot#37612] opened 2020-04-05 19:53 UTC
**Godot version:** 3.2.1

**OS/device including version:** Windows 10

After i delete a node (TextureRect) by calling queuefree(), i create a new node (TextureButton) by calling TextureButton.new(). 

By printing the variable test_texture every frame in notice that after i create the textureButton, it is in this variable, even tho i never set it to this variable. 

If i set test_texture = null after queuefree(), this doesnt happen.

Is this intended behaviour ?

**Steps to reproduce:**

create a Control node with this script, run and press :
H to create texturerect
J to destroy it
K to create texturebutton

`extends Control`

`var test_texture : TextureRect`
`var new_texture_button : TextureButton`

`func _process(delta):`
	`print(test_texture)`

`func _input(event):`
`	if event is InputEventKey:`
`		if event.pressed:`
`			match event.scancode:`
`				KEY_H:`
`					test_texture = TextureRect.new()`
`				KEY_J:`
`					test_texture.queue_free()`
`				KEY_K:`
`					var new_texture_button = TextureButton.new()`

**Comment by dreamsComeTrue** [comment] 2020-04-05 20:09
```
KEY_K:
var new_texture_button = TextureButton.new()
```
you are assigning new object to local variable here, not a member variable of a Script

**Comment by Calinou** [comment] 2020-04-05 20:15
Duplicate of #32383.

**Closed by Calinou** 2020-04-05 20:15 UTC
