### ISSUE TITLE
Shortcuts involving the Alt key are not detected in the script editor

### ISSUE THREAD

**Issue by HungryProton** [godotengine/godot#41942] opened 2020-09-10 08:56 UTC
**Godot version:**
4.0 - 2410016638a1fbf4c5e11ffe76dc2cd2d50d3771

**OS/device including version:**
Ubuntu 20.04

**Issue description:**
Script editor shortcuts involving the `alt` key doesn't trigger anything. The associated action does work if you manually click on it. Shortcuts in the 3D view seems to work however (for example, `control + alt + 2` to split the viewport works as expected).

One exception is the `alt + arrow key` (up and down moves the current line, left and right moves through the history). These four shortcuts work so it's only the shortcuts involving alt and a letter.

This issue only happens with Godot 4 (latest commit of master). It does not happen with the 3.x versions, nor on Windows.

**Steps to reproduce:**
- Open the editor
- Create a new script and open it
- Try any shortcut involving the `alt` key and a letter like:
  + `control + alt + s` (Save)
  + `shift + alt + s` (Save all)

**Minimal reproduction project:**
Any empty project exhibits this behavior.

**Comment by EricEzaM** [comment] 2020-09-10 10:48
Can't repro on Windows 10 - so looks to be a Unix/Linux issue

**Comment by Calinou** [comment] 2020-09-10 13:00
This is an issue with window managers on Linux taking <kbd>Alt</kbd> for themselves. You need to change your window manager's manipulation key to <kbd>Meta</kbd> ("Super") instead.

**Comment by HungryProton** [comment] 2020-09-10 13:24
All my shortcuts are individually defined in the settings panel, some of them uses the Meta key while others uses the Alt key. (There's no global way I could find to switch from one to another.)   
None of them conflicts with Godot shortcuts though and these shortcuts **work with 3.x** so I'm really not sure the WM is to blame here. I need to try this again with a different desktop environment (Currently using Budgie).

However, I tried changing my keyboard from Azerty to Qwerty and then, the `Control + Alt + 2` shortcut in the 3D view worked. Turns out I have to do the same thing in 3.x, I never noticed. That's a different issue though. But Godot 4 did caught that `control + alt` shortcut in the 3D view, now it's just the shortcuts from the text editor that doesn't trigger anything. Shortcuts only starting with `Alt` work as expected. I'll update the first post.

**Comment by capnm** [comment] 2020-09-11 15:11
@HungryProton There is also a central option for this in gnome-tweaks.
I set it always to super ;)

![grafik](https://user-images.githubusercontent.com/4047289/92941854-2fd15e00-f451-11ea-90b2-200382e52eab.png)

**Comment by Leleat** [comment] 2020-09-12 23:30
I can't reproduce it on Fedora 32 either. I tried setting the "Close All" scripts in the Script Editor to Ctrl+Alt+W and it works in 3.2.2 and current master for me.

**Comment by BigZaphod** [comment] 2020-09-13 19:44
Unsure if this is the same problem, but I have a situation like this with Godot 3.2.2 on macOS. Using Alt(Option)-1, 2, 3 works everywhere except when I'm in the script editor which is super annoying. Instead it just inserts some weird character into the source code depending on which key combo I used.

**Comment by boruok** [comment] 2020-12-30 07:38
I've got issue with fold/unfold (ALT+F) key doesn't recognized too on my ***PopOS 20.10** *based on **Ubuntu 20.10**

**Comment by Cykyrios** [comment] 2021-01-02 12:11
This issue may be caused by #37769, which was also merged in the 3.2 branch on September 24.

**Comment by HungryProton** [comment] 2021-01-02 12:17
I can confirm this only happens in 3.2.4 and master, not in 3.2.3.

**Comment by akien-mga** [comment] 2021-01-02 12:23
Yes that's caused by #37769. The question is whether we should simply revert it and reintroduce #6851, or find a way to improve the fix to support both use cases. CC @EricEzaM @Paulb23 @groud.

**Closed** 2021-01-05 13:59 UTC
Labels: bug, confirmed, platform:linuxbsd, regression, topic:editor, topic:input
