### ISSUE TITLE
Resources don't show correctly in remote inspector

### ISSUE THREAD

**Issue by pouleyKetchoupp** [godotengine/godot#38970] opened 2020-05-22 21:06 UTC
**Godot version:**
Introduced in 3.2.1
Still present on 3.2.2 beta 3
Not present on 4.0

**OS/device including version:**
Windows 10

**Issue description:**
When inspecting an object remotely, properties based on resources are not displayed correctly in the editor (no preview, can't show details within object properties).
| 3.2  | 3.2.1 |
| ------------- | ------------- |
| <img src="https://user-images.githubusercontent.com/1075032/82708833-80913100-9c7f-11ea-89a7-ef38a8d5110a.png" width="200"/> | <img src="https://user-images.githubusercontent.com/1075032/82708852-8f77e380-9c7f-11ea-92ad-97f4300228ab.png" width="200"/>  |

It seems the regression has been introduced in #36532 (assigning the reference with `res = *r` always ends up with a null reference in this case).
cc @Faless 

**Steps to reproduce:**
- Create a scene with mesh instances
- Start debugging
- Check mesh property in remote inspector

**Minimal reproduction project:**
[model-remote-inspector2.zip](https://github.com/godotengine/godot/files/4670368/model-remote-inspector2.zip)

**Comment by Calinou** [comment] 2020-05-22 21:32
Duplicate of #37000. Thanks for providing additional information about the issue at hand, still :slightly_smiling_face:

**Closed by Calinou** 2020-05-22 21:32 UTC
