### ISSUE TITLE
Mono build panel only show warnings of last build

### ISSUE THREAD

**Issue by paulloz** [godotengine/godot#15779] opened 2018-01-16 13:12 UTC
Sorry if the name of this issue is not really understandable but the explanation below will make sense.

**Godot version:** `master` / 3def642

**OS/device including version:** *Linux Mint 18.2 + Cinnamon 3.4.6, Mono 5.4.1.6*

**Issue description:**
Warnings from C# files that were not rebuilt during the last compilation aren't displayed.

**Steps to reproduce:**
* Open the minimal reproduction project below
* Click on **Build project** in the **Mono** bottom panel -> 1 warning
* Click once again on the same button -> no warning
* Remove `.mono/temp` (so the next build will rebuild everything)
* Click on the same button again -> 1 warning
* Same button -> no warning
* And so on...

**Minimal reproduction project:**
[bug_warnings-csharp.zip](https://github.com/godotengine/godot/files/1635186/bug_warnings-csharp.zip)

**Comment by akien-mga** [comment] 2020-09-04 10:05
Is this still valid in the current 3.2.3 or master branch?

**Comment by paulloz** [comment] 2020-09-04 23:16
Same behaviour on current 3.2 (41b9e1d). I'm not really able to build master atm.

**Comment by neikeq** [comment] 2020-10-01 09:23
I noticed this a few weeks ago and was planning for a possible solution, but then I noticed this same behaviour is present in Rider and VSMac/MonoDevelop (I didn't check Visual Studio yet). Considering this, rather than going through the trouble of keeping warnings when a target is skipped, should we consider this to be the expected behaviour?

**Comment by neikeq** [comment] 2022-07-16 11:17
This is still a thing in all versions of Godot, but I'm going to close it as I consider it to be the expected behavior.

In addition to Rider and VSMac, I've tested this on Visual Studio recently. The warnings are cleared after building again if the display option is set to `Build Only`. The default option is `Build + IntelliSense`, which does keep the warnings, but that's because the IDE is running live code analysis. Godot is not a C# IDE, and it will never do C# code analysis.

I've tried the same on Unity, to see how another engine with C# scripting behaves. The only way I know of toggling a second build there is to play the game, and when doing that the warnings are cleared.

This may be possible to solve by caching the warnings and analyzing the MSBuild logs to only clear the warnings from targets/tasks that were executed again. But it would require a considerable amount of work to fix something that already works the same as it does elsewhere.

**Closed by neikeq** 2022-07-16 11:17 UTC
Labels: enhancement, topic:dotnet
