### ISSUE TITLE
EditorPlugin set_state() isn't called.

### ISSUE THREAD

**Issue by ninetones** [godotengine/godot#10707] opened 2017-08-28 04:30 UTC
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Windows10, Godot current stable 2.1.3

**Issue description:**

In a script extending EditorPlugin, I expect that set_state() is called when a scene is opened in the editor.
But It seems that the method is not called.

**Steps to reproduce:**
Implementing set_state() ,e.g. print("set_state is called.") results nothing.

**Link to minimal example project:**

[editorplugin_issue.zip](https://github.com/godotengine/godot/files/1255117/editorplugin_issue.zip)

**Comment by akien-mga** [comment] 2018-09-17 14:18
The 2.1 branch is no longer actively worked on by engine developers, unless critical fixes are needed for current games in production. As such we are now closing non-critical bug reports affecting only the 2.1 branch.

Please comment if this was incorrectly triaged and is still relevant in 3.x versions.

**Closed by akien-mga** 2018-09-17 14:18 UTC
Labels: bug, topic:editor, topic:plugin

**Comment by nicktgn** [comment] 2020-06-26 02:41
@akien-mga This seems to be still the case in `3.2.1.stable`.

**Comment by akien-mga** [comment] 2020-06-26 06:02
Please open a new issue with detailed steps to reproduce and a reproduction project that works on recent Godot versions.
