### ISSUE TITLE
Signal connection "Make function" option does not work on C# when using an external editor

### ISSUE THREAD

**Issue by ArthurAttout** [godotengine/godot#23208] opened 2018-10-21 21:44 UTC
___

***Bugsquad edit:** This issue has been confirmed several times already. Please don't comment to confirm that this issue still occurs.*

___

**Godot version:**
Godot Engine v3.0.6.stable.mono.official.8314054

**OS/device including version:**
Windows 10, Nvidia GT710

**Issue description:**
The C# function that is supposed to receive the signal is not created, hence never called. 

**Steps to reproduce:**

- Create a main node
- Create a subnode "HTTPRequest"
- Click HTTPRequest > Node > Signals
- Choose request_completed
- Click "Connect ..."
- Choose the main node
- Enable "Make Function"
- Leave defaults
- Click "Connect"

**Note**

I'm new to Godot so maybe I did something wrong there, but from my understanding, using "connect" to bind the signal to a C# script should create the function automatically and be called when the event is triggered. Should it be done manually when using C# ? (Although I saw some videos showing it was generated automatically, even in C#)

**Comment by ArthurAttout** [comment] 2018-10-22 15:41
Okay, it finally worked. 

It was linked to the use of Visual Studio Code. Switching to the embedded Godot text editor made it work properly. This functionality seems broken when using VSCode.

**Comment by nik0la-vr** [comment] 2019-09-25 10:04
> It was linked to the use of Visual Studio Code. Switching to the embedded Godot text editor made it work properly. This functionality seems broken when using VSCode.

This is still an issue. Is it possible to fix?

**Comment by neikeq** [comment] 2019-09-25 20:23
This issue should be renamed to clarify this issue happens when using external editors. The probably happens with GDScript as well. Can anyone confirm?

**Comment by shawkes** [comment] 2019-09-25 20:47
This all really boils down to #12908 

Yes it "works" with the built-in editor, but it simply appends the code, which is a problem for C# since it ends up outside the class.

**Comment by nik0la-vr** [comment] 2019-09-25 20:53
As far I can tell #12908 is about function being placed at the wrong spot? When using VSCode function is not generated at all.

**Comment by neikeq** [comment] 2019-09-25 21:33
#18721 is about the function being placed outside the class. #12908 is about changing the script language API to make it possible to control the way the method is added, but it does not include actually implementing it for C#, so it's more like a first step towards fixing #18721.

This issue is about the new method not appearing in the file that is open in the external editor.

**Comment by akien-mga** [comment] 2020-02-15 15:42
This is still valid in 3.2 as seen by @fasterthanlime on stream.

It makes it pretty difficult to handle signals with a lot of parameters like HTTPRequest ones. Would be great to have a fix soon-ish that could be backported to 3.2.x.

**Comment by brentbartlett** [comment] 2020-02-24 01:48
Can confirm this is still happening I ran into it today using VS Code as an external editor.  Would like to have this fixed.

**Comment by Lerke** [comment] 2020-05-03 21:30
This issue just occured for me as well. I'm going through Godot's 'Your First Game' walkthrough using C# and Rider as the external editor. The connected methods are not being created. It works perfectly when using the integrated editor.

**Comment by trolog** [comment] 2020-06-30 21:10
Can also Confirm VSCode editor with the latest v3.2.2.rc4 not creating void when connecting a signal from godot editor. It opens the script, so I can just write the void myself, though it would be nice for it to work as it does in GDScript.

**Comment by lazyvainglory** [comment] 2020-06-30 23:09
This is still an issue with Godot v3.2.2 and godot-tools v1.1.1 for VSCode

**Comment by Calinou** [comment] 2020-07-01 07:52
We don't really need more confirmations anymore at this point :slightly_smiling_face: 

This will be fixed when someone who knows to fix it opens a pull request.

**Comment by shiMusa** [comment] 2020-07-19 13:54
I'm using latest Rider and Godot 3.2.2, same issue

**Comment by Mirodil** [comment] 2020-08-31 14:39
@Calinou I can help with PR if you can help with point where I can start to look to fix this issue.

**Comment by Calinou** [comment] 2020-08-31 14:48
@Mirodil I don't know where exactly this should be fixed, but it probably has to do with saving the script automatically when using Make Function so the external editor can reload it.

**Comment by kendinitto** [comment] 2020-09-20 07:12
This is actually a major workflow problem if you want to develop in C# while using an external editor like VScode. Someone mentioned this problem does not happen with gdscript, so whatever the bridge is between gdscript and external editors should be able to be ported over to C# I'm guessing ? I wish I had the time to figure it out :(

**Comment by Calinou** [comment] 2020-09-20 12:11
@kendinitto I think the issue has more to do with using an external editor than C# in itself.

**Comment by kendinitto** [comment] 2020-09-21 06:22
**@Calinou**  If you look higher up in this thread I see the statement (pasted below) that seems to indicate that when using GDscript and an external editor the functionality being discussed is working correctly. That functionality being, when linking signals, the new signal function gets inserted into the external editor. That's what was leading me to believe the issue was related to C#.

Statement Referenced:
------------------------------------------------
ArthurAttout commented on Oct 21, 2018
Yes, it worked properly when using GDScript
------------------------------------------------

**Comment by kendinitto** [comment] 2020-09-21 06:31
Too bad Godot cant display a copy of the function somewhere other than the built in editor so you can copy and paste it into the external editor. When I set Godot to use an external editor the built in editor does not work at all its just a black screen. The main issue is when it comes to c# I am not always sure what the proper structure of the function is supposed to be as it seems to be different based on  the type of signal. Sometimes it has object variable in there and sometimes not for example.

**Comment by kendinitto** [comment] 2020-09-24 05:15
For what it is worth I noticed if you go to editor settings and under mono settings select an external editor, in my case VS code, but under text editors > external do not turn this on, what this does is it will use the external editor to edit while leaving the internal editor turned on as well. If you save in either editor the other one gets updated. So if you create a signal it will insert it into the internal editor and you just save it (cntrl-s) and the external editor will be updated with the new function code. Its not perfect but it seems to be a workflow that can work since the only time you need to deal with the internal editor is if you create a signal.

**Comment by K1ll3rM** [comment] 2020-09-29 18:23
Would be nice if this could get fixed, I'm having the same problem with Rider

**Comment by Calinou** [comment] 2020-09-29 18:29
Duplicate of https://github.com/godotengine/godot/issues/41283. This issue isn't specific to C# usage; it's specific to external editors.

**Closed by Calinou** 2020-09-29 18:29 UTC
Labels: bug, confirmed, topic:editor, topic:mono

**Comment by Elfahor** [comment] 2022-08-16 15:03
This is maybe just straight impossible. Once the file is opened in the external editor, wouldn't it become impossible for an other process (here the Godot editor) to edit it?
