### ISSUE TITLE
ParticlesMaterial property doesn't have "revert" button

### ISSUE THREAD

**Issue by NelloDev** [godotengine/godot#33024] opened 2019-10-24 06:11 UTC
**Godot version:**
3.1.1
3.2.alpha 35944aebdeb4c3b5869aaeedaaded02397b7ce92
**OS/device including version:**
5.3.7.arch1-1
**Issue description:**
The "Orbit Velocity" property of Particles2D -> ParticlesMaterial doesn't have a "revert" button after the property values are changed.
**Steps to reproduce:**
1. Add a Particles2D to the SceneTree
2. In the Inspector panel navigate to Particles2D -> Process Material and add a new ParticlesMaterial
3. Click on the ParticlesMaterial and navigate to Orbit Velocity
4. Change any of the property's values

**Minimal reproduction project:**
[particles.zip](https://github.com/godotengine/godot/files/3765958/particles.zip)

**Comment by KoBeWi** [comment] 2019-11-03 15:04
Actually a duplicate of #30651

**Closed by KoBeWi** 2019-11-03 15:04 UTC
Labels: bug, topic:core, topic:editor
