### ISSUE TITLE
Crash due to GDScript code `variable-.`

### ISSUE THREAD

**Issue by theraot** [godotengine/godot#56318] opened 2021-12-29 16:07 UTC
### Godot version

v4.0.dev.custom_build [9f058674a]

### System information

Windows 10

### Issue description

Typing `.` after a variable followed by an operator will cause Godot to crash. It is the act of typing, not having the problematic code. Also, it only causes a crash with an existing variable.

*I'm not sure how to name the issue, nor how to search for it. Thus, I'm unaware if this is a duplicate.*

### Steps to reproduce

Type this code in some script func:

```
	var n = self
	n-.
```

Typing, I repeat, typing the final `.` will cause the crash. Copying and pasting will not cause the crash. Loading a file with the code will not cause the crash.

*The same result can be archived with other operators aside form `-`.*

**Comment by cdemirer** [comment] 2021-12-29 16:49
It is a duplicate indeed 🙂  #55553
I agree that it is difficult to find since Github's search doesn't seem to work with symbols.

**Comment by Chaosus** [comment] 2021-12-29 17:38
Duplicate of #55553.

**Closed by Chaosus** 2021-12-29 17:38 UTC
Labels: bug, topic:gdscript, crash
