### ISSUE TITLE
Godot 4 Alpha janking while moving the window and resizing it

### ISSUE THREAD

**Issue by hakro** [godotengine/godot#63788] opened 2022-08-01 18:23 UTC
### Godot version

4.0 Alpha 13

### System information

PopOS 22.04 - NVIDIA Corporation GP107GLM

### Issue description

I don't know if it's time to start reporting performance issues this early, given that Godot 4 is still in Alpha, but maybe it will help.

So compared to 3.5 RC 8, Godot 4 Alpha is noticeably slower on startup, closing, and it's quite janky when trying to resize it's window, or moving it around.
It feels quite heavy.

Hopefully this video won't be to distorted due to compression.

https://user-images.githubusercontent.com/3624853/182217211-3cb9799a-d4dd-4d61-9bdd-5340c0889f91.mp4

### Steps to reproduce

Just open both Godots, resize them, or move them around, or both.

### Minimal reproduction project

This happens even with a fresh and empty Godot 4

**Comment by Calinou** [comment] 2022-08-01 21:28
Duplicate of https://github.com/godotengine/godot/issues/39222.

**Closed by Calinou** 2022-08-01 21:28 UTC
