### ISSUE TITLE
Multiline comments are unsafe lines

### ISSUE THREAD

**Issue by MaaaxiKing** [godotengine/godot#39323] opened 2020-06-05 14:10 UTC
**Godot version:**
3.2.1.stable
**OS/device including version:**
Windows 10 Home 1909
Intel(R) UHD Graphics 620
GLES3
**Issue description:**
My multiline comment was marked as an unsafe line. Since comments can't be unsafe this is a bug.
For the ones who don't know what (un)safe lines are: https://docs.godotengine.org/en/stable/getting_started/scripting/gdscript/static_typing.html#safe-lines
**Steps to reproduce:**
Create a project. Create a script. Write a multiline comment (triple quotation mark, new line, triple quotation mark)
**Minimal reproduction project:**

[multiline comment bug.zip](https://github.com/godotengine/godot/files/4736552/multiline.comment.bug.zip)

**Comment by Calinou** [comment] 2020-06-05 14:18
Duplicate of #34127. Also, note that GDScript doesn't feature actual multiline comments, only multiline strings. Therefore, multiline comments in GDScript are actually multiline strings that are standalone expressions.

**Closed by Calinou** 2020-06-05 14:18 UTC
