### ISSUE TITLE
Incomplete OpenGL 3.3 support with Intel HD 4000 on Windows 8

### ISSUE THREAD

**Issue by fabiomodesto** [godotengine/godot#17660] opened 2018-03-20 23:16 UTC
I´m using godot version 3.0.2.
Windows 8
intelgraphics 4000

I´m construing 2d game when I´m going scale shape x=0.5 and y 0.5 this error happens, the right side objects (scene and inspector) hide

![screenshot_4](https://user-images.githubusercontent.com/22896345/37687755-969b9740-2c7b-11e8-8d29-400f3be9bdd6.jpg)

`

**Godot version: 3.0.2.**

**OS/device including version Windows 8 64bits 
GPU: IntelGraphics 4000**

**Comment by mysticfall** [comment] 2018-03-21 01:20
Since the description doesn't mention any shields or swords, I suppose it was just a typo in the title.

I think changing the title to something more descriptive (and also searchable), like _"RasterizerSceneGLES3::initialize throws error when ..."_ might help to attract attention of those who know more about the issue.

**Comment by akien-mga** [comment] 2018-03-21 07:57
Sounds like your drivers don't support OpenGL 3.3 properly (they support it "enough" to pass the check "is OpenGL 3.3 available?", otherwise Godot wouldn't start, but then they misbehave).

Intel drivers on Windows are notoriously bad, especially on Windows 8 and 10. Try to upgrade the drivers, if it doesn't work, try Linux... Or wait for Godot 3.1 with OpenGL 2.1 support.

**Comment by efornara** [comment] 2018-03-21 12:21
If you don't want / can't update drivers, or if this doesn't solve your problem, or if you don't want / can't switch to Linux, and if you can live with some [glitches and limitations](https://github.com/efornara/godot/blob/3.0-gles2/GLES2.md), you can also try my unofficial / unsupported branch:

https://github.com/efornara/godot/releases

**Comment by reduz** [comment] 2018-09-07 00:43
This is not a bug, unfortunately the only way out is upgrading to Windows 10, where it works.
Closing. You can use GLES2 driver now, while the GLES3 driver will be gone by the time 3.2 comes out.

**Closed by reduz** 2018-09-07 00:43 UTC
Labels: bug, topic:rendering
