### ISSUE TITLE
Wacom tablet incompatibility

### ISSUE THREAD

**Issue by nonomiyo** [godotengine/godot#20474] opened 2018-07-26 07:47 UTC
Godot version:
since Godot Engine v3.0.3 - stable_win64

OS/device including version:
Windows 10
Screen resolution : 1920x1080

Issue description:

hello, my wacom tablet (intuos 2015 - model CTH 690) is not working properly with godot since version 3.0.3 (it worked perfectly fine before)

- On the project selection screen and when I run the game, I just can't click at all
- On the editor, it clicks at the bottom of the arrow (mouse cursor) instead of clicking at the top of it

apparently, it happens with the wacom Intuos CTH-490 as well :
https://godotengine.org/qa/31141/godot-and-wacom-tablet-incompatibility 

>  Couldn't test it with other types of tablets / other brands.
>  It worked fine up to Godot version 3.0.2 stable win64

thanks !

**Comment by akien-mga** [comment] 2018-07-26 08:07
CC @RandomShaper

**Comment by RandomShaper** [comment] 2018-07-26 16:53
Looks as a dupe of #11586, already fixed by #19708.

@nonomiyo , you can expect it to be fixed on 3.0.6.

**Comment by nonomiyo** [comment] 2018-07-26 20:58
wow, that's a relief !   You're all doing a great job on Godot, please keep up  💯

**Comment by AnnA-Ayms** [comment] 2018-07-30 06:55
I've found that it has only fixed touch but the wacom pens are still not recognized in 3.06. I can get the pens to be recognized if I set (or disable on my other less sophisticated hardware) Windows ink. I've tried with 3 different computers. A Fujitsu t904 with Windows 7 x64, disabling the "Tablet PC Input Service" restored pen function in Godot 3.0.5 and 3.0.6 but at the expense of some functionality within Windows itself. A Fujitsu q584 with Windows 8.1 32 bit where I couldn't figure how to disable Windows ink in 8.1 as disabling the equivalent of "Tablet PC Input Service" didn't help and I couldn't find any other options as the "Feel" drivers on penabled Tablets are much simpler configuration option wise to the professional tablet drivers (which aren't compatible either) so the pen still doesn't work with 3.0.6 (not a concern for me personally but that doesn't invalidate the issue). A HP Zbook X2 with Windows 10 (1703) x64 which uses a more professional pen driver so there is an option to disable Windows ink on a program by program basis. When it is set to off the pen works on 3.0.5 and 3.0.6 but when ink is set to be used it doesn't work.

**Comment by RandomShaper** [comment] 2018-07-30 18:42
Oh, that's interesting feedback. Thank you.

I'll research and try to make a definitive fix for this.

**Comment by RandomShaper** [comment] 2018-08-28 19:02
@AnnA-Ayms, would you try again with [this patched Godot binary](https://drive.google.com/open?id=1LLPMgiZ88_kAKvYpJj0g1ER5GHtnFlSl)?

It it works, for you, then I'll submit a PR with the fix.

**Comment by AnnA-Ayms** [comment] 2018-08-29 19:15
Quick answer: I've tested it and the Wacom EMR pen is still unusable in the Godot build you provided unfortunately, but thank you for your effort.

Detailed answer:
With the Fujitsu t904 with Windows 7 x64 the pen doesn't work right but I did now notice that the pen will sometimes be recognized as a single click if I double tap/press with pen so I can open a project and can select nodes in the scene tab or select a property in the inspector tab, as well as toggle boxes on or off with the pen. The pen can not be used even with the double tap to switch between 2D, 3D. Script, AssetLib but the options will get highlighted by the pen (text turns blue) when I double tap but the view doesn't change. The finger touch recognition works fine though. Also a tap then tap and hold down does not get treated as a click hold it is only treated as a single click when it is even recognized as that. In the 3D view I can't select (single click) with the double click/press trick anything though but 2D view does treat the double click/press/tap as a single click. With the script view double click/press jumps to empty lines with no code in them but won't usually select a line with even just a tab in it. It will sometimes select a line with code but not one where I was clicking at and I could not find any order or pattern to which it selected after some experimenting. It was consistent to which line with code it would jump to if the script was the same but I couldn't figure why that line was selected over those around it and changing the script would change which lines with code if any it would jump to. Also I noticed once I used the pen to click (or try to click) anything that pen, touch. and touch-pad didn't seem to be recognized by the minimize/restore/close buttons of the window and I had to use the close button in the command line window to get Godot to close unless I first switched to another program (file explore for example) then went back to Godot and in that case even the pen could minimize/restore/close with a regular single click. If I didn't use the pen then touch-screen and touch-pad both worked fine with the minimize/restore/close buttons at any time. The close confirmation box ("Save & Close" "Cancel" "Don't Save") is similar to 2D, 3D. Script, AssetLib in that the pen only highlights the option if I double tap (single tap does nothing).

With the HP Zbook X2 with Windows 10 (1703) x64 it will work properly as it did before if I disable Windows Ink in the Wacom driver's options but that option is only available on that device out of what I have as it is marketed/sold as a "pro" device so the pen and its drivers are better. With Windows Ink on The behavior seems similar to the Fujitsu t904 with Windows 7 x64 but I didn't test it as thoroughly that way.

I could not test with the Fujitsu q584 with Windows 8.1 32 bit as the provided build was 64 bit (for good measure I did try but got the obvious this program isn't supported by this version of windows error or however it was worded) but I suspect it would be the same as described above.

**Comment by RandomShaper** [comment] 2018-08-30 20:38
I'm very happy to hear that. I'm submitting a PR shortly.

**Closed** 2018-08-31 06:16 UTC
Labels: bug, platform:windows, topic:input

**Comment by BrahRah** [comment] 2018-09-04 06:40
Got the same problem with 3.0.4 and 3.0.6. My Wacom Intuos 3 clicks aren't registered at all if I switch to a mouse it works perfectly.

**Comment by RandomShaper** [comment] 2018-09-04 08:31
@BrahRah, could you try with the patched binary from the comments above?
