### ISSUE TITLE
Decal crashes & culling behavior when placing at rapid pace

### ISSUE THREAD

**Issue by ynot01** [godotengine/godot#67353] opened 2022-10-13 15:58 UTC
### Godot version

v4.0.beta2.official.f8745f2f7

### System information

Windows 10, Vulkan Forward Plus, NVIDIA GeForce GTX 1070

### Issue description

Placing lots of decals on a mesh silently crashes, and when it reaches the thousands it starts to cull decals.

### Steps to reproduce

To achieve silent crash (Closing unprompted with no errors), place a lot of decals in rapid succession.

![Godot_v4 0-beta2_win64_0Xp58hmtBt](https://user-images.githubusercontent.com/28408322/195646207-02241ebe-04fe-4a52-8059-88af2043075b.gif)

```
--- Debugging process started ---
Godot Engine v4.0.beta2.official.f8745f2f7 - https://godotengine.org
Vulkan API 1.2.0 - Using Vulkan Device #0: NVIDIA - NVIDIA GeForce GTX 1070
 
1
2
...
```
```
...
204
205
--- Debugging process stopped ---
```

When it doesn't crash (achievable often by placing at a slower pace), you can see some of the odd behavior that seems to occur around 1,000 decals, old decals will get culled at random but still contribute to nodes and active objects, as can be seen in the debug monitor.

![Godot_v4 0-beta2_win64_jFXbTaBghL](https://user-images.githubusercontent.com/28408322/195646271-56de0b58-87d3-4339-8a1c-b6be2ddfdfb5.gif)

## To use the reproduction project:
**Left-click and drag** on the sphere to rapidly place decals
Can rotate the sphere with right-click and drag
Zooming achievable by scrolling

### Minimal reproduction project

[PaintGlobe.zip](https://github.com/godotengine/godot/files/9778210/PaintGlobe.zip)

**Comment by Calinou** [comment] 2022-10-13 18:01
Duplicate of https://github.com/godotengine/godot/issues/56657.

The culling behavior is expected – you need to increase **Max Clustered Elemenets** to circumvent it, at the cost of performance on some GPUs.

**Closed by Calinou** 2022-10-13 18:01 UTC
