### ISSUE TITLE
WebXR in "immersive-ar" session mode shows opaque artifacts overshadowing the background

### ISSUE THREAD

**Issue by DionHo** [godotengine/godot#75581] opened 2023-04-01 23:29 UTC
### Godot version

3.5.x

### System information

Meta Quest 2

### Issue description

After starting the AR session, 

- every pixel in the viewport to which an opaque object was rendered stays opaque. This kind of looks like a ghosting artifact, but the trail is not vanishing. As if the transparency information is not cleared between the drawing of frames.
- Transparent objects get more and opaque at the position on the screen, where I look at them (as if they are 'burning in')
-  I used the amazing tutorial from @dsnopek at [his website](https://www.snopekgames.com/tutorial/2020/how-make-vr-game-webxr-godot-3) to build a simple AR application by replacing `immersive-vr` with `immersive-ar` and setting `get_viewport.transparent_bg = true` before entering AR mode (otherwise I would get a similar artifact as shown in https://github.com/godotengine/godot/pull/45548)

Further information:

- I also built an example in **godot 4** and it **does work**, no artifacts at all
- There are also no artifacts visible when I use my smartphone for immersive-ar
- The [immersive-web webxr examples](https://immersive-web.github.io/webxr-samples/) are working just fine on my Quest 2, so it does not seem to me that this is an issue with my device or browser I am using.

### Steps to reproduce

The easiest way for me is to just view this example project of @dsnopek (https://bit.ly/godot-webxr-10) in the Meta Quest 2 browser.

Regarding the projects I built, I was able to reproduce the problem with the 3.5-stable and 3.5.2-stable releases.

### Minimal reproduction project

Here is a minimal example using the code from the tutorial (leaving out the controllers) and adding two meshes to show the rendering problems.
[webxr-ar-bug-minimal.zip](https://github.com/godotengine/godot/files/11130800/webxr-ar-bug-minimal.zip)

**Comment by dsnopek** [comment] 2023-04-12 22:32
Thanks for the report!

I'm able to reproduce this on the Meta Quest 2. However, I checked with AR on my smartphone, and it's still working, so I think this is unrelated to PR #45548

Perhaps we aren't clearing the render target with the clear color when doing stereo rendering?

Needs more investigation!

**Comment by dsnopek** [comment] 2023-04-12 22:58
An untested theory: it looks like Godot is clearing the render target before each eye as it should. But in Godot 3, we're using a shader to draw the texture from the render target from Godot onto the framebuffer provided by WebXR. I think that means that any transparent pixels in the texture won't overwrite pixels that are already on the framebuffer.

So, perhaps we need to either:

1. Clear the framebuffer from WebXR at the beginning of each frame. I think we could do this when `commit_for_eye()` is being called with either the LEFT or MONO eye.
2. Change the way we're doing the shader, so the resulting fragment overwrites what's there, rather than mixing it. Perhaps doing something clever with [blendFunc()](https://developer.mozilla.org/en-US/docs/Web/API/WebGLRenderingContext/blendFunc)?

**Comment by dsnopek** [comment] 2023-04-14 22:46
My untested theory turned out to be correct!

PR #76072 fixes this issue in my testing

**Comment by DionHo** [comment] 2023-04-15 09:47
Awesome! I just tested it on my Quest 2 ... thank you!

**Comment by dsnopek** [comment] 2023-04-16 03:23
That's great! Thanks for testing the PR :-)

Let's keep this issue open until it gets merged though

**Comment by dsnopek** [comment] 2023-04-17 17:25
PR #76072 was just merged - yay! So, closing again :-)

**Closed by dsnopek** 2023-04-17 17:25 UTC
Labels: bug, platform:web, confirmed, topic:xr
