### ISSUE TITLE
AMD GPU and Engine crash when running OpenXR scene.

### ISSUE THREAD

**Issue by 1SMOL** [godotengine/godot#65527] opened 2022-09-08 16:36 UTC
### Godot version

v4.0.alpha16.official [86dd3f312]

### System information

Windows 11 64-bit, AMD Radeon RX 6800 XT

### Issue description

When attempting to run a project made in OpenXR, as soon as the game window appears, my system will freeze and blackscreen.

Log
```
OpenXR: Running on OpenXR runtime:  SteamVR/OpenXR   0.1.0
Godot Engine v4.0.alpha16.official.86dd3f312 - https://godotengine.org
OpenXR: XrGraphicsRequirementsVulkan2KHR:
 - minApiVersionSupported:  1.0.0
 - maxApiVersionSupported:  1.2.0
Vulkan API 1.2.0 - Using Vulkan Device #0: AMD - AMD Radeon RX 6800 XT
 
OpenXR: Found supported reference space  XR_REFERENCE_SPACE_TYPE_VIEW
OpenXR: Found supported reference space  XR_REFERENCE_SPACE_TYPE_LOCAL
OpenXR: Found supported reference space  XR_REFERENCE_SPACE_TYPE_STAGE
OpenXR: Found supported swapchain format  VK_FORMAT_R8G8B8A8_SRGB
OpenXR: Found supported swapchain format  VK_FORMAT_B8G8R8A8_SRGB
OpenXR: Found supported swapchain format  VK_FORMAT_R32G32B32A32_SFLOAT
OpenXR: Found supported swapchain format  VK_FORMAT_R32G32B32_SFLOAT
OpenXR: Found supported swapchain format  VK_FORMAT_R16G16B16A16_SFLOAT
OpenXR: Found supported swapchain format  VK_FORMAT_D32_SFLOAT
OpenXR: Found supported swapchain format  VK_FORMAT_D16_UNORM
OpenXR: Found supported swapchain format  VK_FORMAT_D24_UNORM_S8_UINT
OpenXR: Found supported swapchain format  VK_FORMAT_D32_SFLOAT_S8_UINT
USER ERROR: Parser bug (please report): tried to assign unset node without an identifier.
   at: resolve_class_interface (modules/gdscript/gdscript_analyzer.cpp:656) - Parser bug (please report): tried to assign unset node without an identifier.
USER ERROR: Parser bug (please report): tried to assign unset node without an identifier.
   at: resolve_class_interface (modules/gdscript/gdscript_analyzer.cpp:656) - Parser bug (please report): tried to assign unset node without an identifier.
USER ERROR: Parser bug (please report): tried to assign unset node without an identifier.
   at: resolve_class_interface (modules/gdscript/gdscript_analyzer.cpp:656) - Parser bug (please report): tried to assign unset node without an identifier.
USER WARNING: res://assets/misc/ladder.tscn:4 - ext_resource, invalid UUID: uid://d346yp1mwx747 - using text path instead: res://assets/misc/ladder.glb
   at: load (scene/resources/resource_format_text.cpp:448) - res://assets/misc/ladder.tscn:4 - ext_resource, invalid UUID: uid://d346yp1mwx747 - using text path instead: res://assets/misc/ladder.glb
USER WARNING: res://scenes/BasketballCourt.tscn:3 - ext_resource, invalid UUID: uid://cnfvt5mnclsgo - using text path instead: res://assets/misc/ring.glb
   at: load (scene/resources/resource_format_text.cpp:448) - res://scenes/BasketballCourt.tscn:3 - ext_resource, invalid UUID: uid://cnfvt5mnclsgo - using text path instead: res://assets/misc/ring.glb
USER WARNING: res://assets/sketchfab.com/basketball/basketball.tscn:5 - ext_resource, invalid UUID: uid://beketqaubosqr - using text path instead: res://assets/sketchfab.com/basketball/scene.gltf
   at: load (scene/resources/resource_format_text.cpp:448) - res://assets/sketchfab.com/basketball/basketball.tscn:5 - ext_resource, invalid UUID: uid://beketqaubosqr - using text path instead: res://assets/sketchfab.com/basketball/scene.gltf
OpenXR initialised successfully
Using swap chain format: VK_FORMAT_R8G8B8A8_SRGB
USER ERROR: Condition "err" is true. Returning: ERR_CANT_CREATE
   at: _update_swap_chain (drivers/vulkan/vulkan_context.cpp:1746) - Condition "err" is true. Returning: ERR_CANT_CREATE
USER ERROR: Condition "err" is true. Returning: ERR_CANT_CREATE
   at: _update_swap_chain (drivers/vulkan/vulkan_context.cpp:1746) - Condition "err" is true. Returning: ERR_CANT_CREATE
USER ERROR: Condition "err" is true. Returning: ERR_CANT_CREATE
   at: _update_swap_chain (drivers/vulkan/vulkan_context.cpp:1746) - Condition "err" is true. Returning: ERR_CANT_CREATE
USER ERROR: Condition "err" is true. Returning: ERR_CANT_CREATE
   at: _update_swap_chain (drivers/vulkan/vulkan_context.cpp:1746) - Condition "err" is true. Returning: ERR_CANT_CREATE
OpenXR: Failed to locate view space in play space [ XR_ERROR_TIME_INVALID ]
USER ERROR: vkCreateGraphicsPipelines failed with error -4 for shader 'SceneForwardClusteredShaderRD:13'.
   at: render_pipeline_create (drivers/vulkan/rendering_device_vulkan.cpp:6850) - Condition "err" is true. Returning: RID()
USER ERROR: Condition "pipeline.is_null()" is true. Returning: RID()
   at: _generate_version (servers/rendering/renderer_rd/pipeline_cache_rd.cpp:60) - Condition "pipeline.is_null()" is true. Returning: RID()
USER ERROR: Condition "!pipeline" is true.
   at: draw_list_bind_render_pipeline (drivers/vulkan/rendering_device_vulkan.cpp:7572) - Condition "!pipeline" is true.
USER ERROR: The vertex format used to create the pipeline does not match the vertex format bound.
   at: draw_list_draw (drivers/vulkan/rendering_device_vulkan.cpp:7778) - Condition "dl->validation.pipeline_vertex_format != dl->validation.vertex_format" is true.
USER ERROR: Condition "err" is true. Returning: ERR_CANT_CREATE
   at: swap_buffers (drivers/vulkan/vulkan_context.cpp:2133) - Condition "err" is true. Returning: ERR_CANT_CREATE
USER ERROR: vkBeginCommandBuffer failed with error -4.
   at: _begin_frame (drivers/vulkan/rendering_device_vulkan.cpp:8974) - Condition "err" is true.
OpenXR: Failed to locate view space in play space [ XR_ERROR_TIME_INVALID ]

```

### Steps to reproduce

- On windows 11
- Download any of the recent alpha builds of godot 4
- Create a basic OpenXR project 
- Run the project

### Minimal reproduction project

[Godot 4 openxr demo](https://github.com/BastiaanOlij/godot4_openxr_demo.git)

**Comment by Calinou** [comment] 2022-09-09 00:05
Duplicate of https://github.com/godotengine/godot/issues/59505.

**Closed by Calinou** 2022-09-09 00:05 UTC
Labels: bug, topic:rendering, topic:thirdparty, topic:xr, crash
