### ISSUE TITLE
Cannot edit autotile after navigating away from the autotile editor (workaround: reset zoom by clicking the "1" button)

### ISSUE THREAD

**Issue by matsjs** [godotengine/godot#54691] opened 2021-11-07 00:16 UTC
### Godot version

3.4

### System information

OSX, GLES3

### Issue description

There appears to be a bug in 3.4 where you can no longer edit a tilesets autotile after navigating away from the autotile editor. This is not an issue in 3.3.4.

### Steps to reproduce

- Create a new project
- Create a TileMap node
- Add a tileset
- Add a texture
- Navigate away (place some tiles for example)
- Go back to the tileset - it can now no longer be edited

**Comment by akien-mga** [comment] 2021-11-07 00:19
Might be related to #52760.

**Comment by matsjs** [comment] 2021-11-07 00:57
> Might be related to #52760.

It seems so. Zooming in and out fixes it for me too. Feel free to close this issue, thank you!

**Comment by golddotasksquestions** [comment] 2021-11-07 00:57
Can confirm also with Single Tile or Atlas Tile.
Once you navigated away from the Tileset editor, you cannot create another Tile with the same texture either.

However if you add another Texture, then the bug seems to have disappeared. You suddenly can again edit the tiles and create new Tiles

**Comment by MatteoPiovanelli-Laser** [comment] 2021-11-23 22:17
I think I'm seeing the same issue. If I navigate away from the TileSet Editor I can't even edit existing tiles. Changing/resetting the zoom seems to make it work again.

**Comment by akien-mga** [comment] 2021-11-24 08:29
Duplicate of #52760

**Closed by akien-mga** 2021-11-24 08:29 UTC
Labels: bug, topic:editor, confirmed, regression, topic:2d
