### ISSUE TITLE
Gravity factor = 0.1 causes ideal pendulum stop at not equilibrium point

### ISSUE THREAD

**Issue by genete** [godotengine/godot#6314] opened 2016-08-28 16:43 UTC
**Operating system or device - Godot version:**
OS X 10.10.3 Godot 2.1 stable official

**Issue description** (what happened, and what was expected):
A perfect pendulum (no friction) created with a PinJoint2D and a RigidBody2d and a capsule collision shape stops after first oscillation if gravity scale is 0.1. It starts rotated 90 degrees and stops after rotates 180 degrees in a non equilibrium position.

I expect that it would endless move like a pendulum.

**Steps to reproduce:**
See minimal exampled attached

**Link to minimal example project** (optional but very welcome):
[Pendulum.zip](https://github.com/godotengine/godot/files/441232/Pendulum.zip)

**Comment by genete** [comment] 2016-08-28 16:43
Please check visible collision shapes on Debug menu

**Comment by bojidar-bg** [comment] 2016-08-29 07:18
@genete Can you try disabling sleep on the pendulum's rigidbodies?

**Comment by genete** [comment] 2016-08-29 16:14
Checking "Can Sleep" to off, fixes the issue (pendulum goes back and forth endless)

**Comment by eon-s** [comment] 2017-11-19 21:46
This happens on master too but I do not know if is a bug or the body is expected to sleep when reaches velocities close to zero for a while.

Project for 3:
[pendulumv3.zip](https://github.com/godotengine/godot/files/1486021/pendulumv3.zip)

**Comment by Anutrix** [comment] 2019-06-28 10:13
I think bodies are expected to sleep below threshold velocities but the threshold for it could be adjusted.
servers/physics_2d/space_2d_sw.cpp:1348:        body_linear_velocity_sleep_threshold = GLOBAL_DEF("physics/2d/sleep_threshold_linear", 2.0);
servers/physics_2d/space_2d_sw.cpp:1349:        body_angular_velocity_sleep_threshold = GLOBAL_DEF("physics/2d/sleep_threshold_angular", (8.0 / 180.0 * Math_PI));

**Comment by eon-s** [comment] 2019-06-30 15:46
I cannot reproduce this on 3.1.1 with the converted project.

**Comment by akien-mga** [comment] 2019-06-30 20:27
Assuming fixed in 3.1 then. Please comment if you can still reproduce it.

**Closed by akien-mga** 2019-06-30 20:27 UTC
Labels: bug, topic:physics
