### ISSUE TITLE
Godot doesn't support Mono Output devices

### ISSUE THREAD

**Issue by sc312** [godotengine/godot#39065] opened 2020-05-26 14:27 UTC
**Godot version:**
3.2

**OS/device including version:**
Any mono output device. In this case, specifically the WH1000XM3 bluetooth headphones in "Hands free AG Audio Mode".
Windows 10.
I'm not sure about other OSes.

**Issue description:**
When opening the Godot engine with a mono device as the default audio device I get the error "WASAPI: Unsupported number of channels: 1". I can see from the audio driver cpp files that this is intentional but I wonder why? If I've got a mono output device then surely other people must too, and wouldn't mono audio be the easiest to support?
If I run the game with this mono device then all audio is distorted to be pitched deeper than it is supposed to be. Presumably because Godot is assuming that the input device has two channels.

**Steps to reproduce:**
Clone the mic-record project from the Godot Demo Projects github repo and open it in the

**Comment by akien-mga** [comment] 2020-05-27 13:15
>  "PulseAudio: Unsupported number of channels: 1"

It's weird as the case where you have only one channel is explicitly handled in the Pulseaudio driver, it should not print this warning.

https://github.com/godotengine/godot/blob/b0eca5828ccd3a5c07b77e82e567c45937de9056/drivers/pulseaudio/audio_driver_pulseaudio.cpp#L158-L183

Apart from that yes, support for Mono should be added in the various drivers. The engine (`AudioServer`) can keep processing audio as stereo, and the `AudioDriver` can average left and right to generate mono output for mono devices.

**Comment by sc312** [comment] 2020-05-27 13:25
Ah, that's my bad.
I've only run my code on Windows so far. I checked the other AudioDriver implementations to check whether they were set up in the same way and it looked like they were but I think I might've been looking at an old commit.
I'll modify the issue.

**Comment by Calinou** [comment] 2021-03-12 19:49
Confimed by someone on Godot Forums: https://godotforums.org/discussion/25713/wasapi-channel-number-causes-audio-gliches#latest

**Comment by Nubilous** [comment] 2021-06-03 13:51
Can also confirm this for another Sony WH1000XM3, for the Sony WF1000XM3, Sennheiser HD350BT, and the Steelseries Arctic and another Steelseries Arctic Pro. All on Windows 10.

As far as I can tell, this issue basically **breaks audio for everyone using a bluetooth headset and voice chat**, because bluetooth (at least in pretty much all hardware/stacks available atm) doesn't support stereo playback + microphone, so they require you to switch to a non-stereo setting to use that, or do it automatically. A few of our testers hadn't even realized their headset was set to mono. Might become a bit of a support problem, since that's a lot of people.

**Comment by SanderVanhove** [comment] 2022-08-03 11:46
I have this warning coming up too for my Sony H.ear too, but only in Hands-Free AG Audio mode, which is basically the mode when using the microphone.

**Comment by Ithamar** [comment] 2023-02-04 09:23
I can confirm this is still the case on Windows 10 with 4.0beta17. Is the "interleave left-right" suggestion in https://github.com/godotengine/godot/issues/39065#issuecomment-634651829 still seen as an acceptable solution? If so, would you prefer a PR based on `master` for this, or rather a `3.x` one?

**Comment by Calinou** [comment] 2023-02-04 17:37
> Is the "interleave left-right" suggestion in https://github.com/godotengine/godot/issues/39065#issuecomment-634651829 still seen as an acceptable solution

Sounds good to me (no pun intended) :slightly_smiling_face:

**Comment by dreadpon** [comment] 2023-04-25 10:56
It seems very closely related to https://github.com/godotengine/godot/issues/25875 at least in my case.
I have reports that both mono devices as well as 7.1 headsets have the same symptoms of severely distorted audio.

In my case it is reproducible by connecting a wireless headset with "Hands-free" capability to Windows machine and trying to play any audio through from the engine. It doesn't even have to be in-game - imported audio files (wav/ogg) are distorted as well.

A common workaround I've seen is to disable "Hands-free" mode and use the headset purel as headphones, but my app features a voice chat so I need both to work on the same device. 

Discord and Telegram seem to be handling this just fine, so there's likely something wrong with either WASAPI middleware Godot is using or Audio/AudioServer itself.

For my Godot 3.5.2 project I'm currently working around this by installing [3rd-party software](https://vb-audio.com/Cable/) that allows me to remap audio devices and expose them to Godot.

This works, but isn't really user-friendly, especially when said users have other VOIP apps (such as aforementioned Discord and Telegram) working just fine.

Hopefully this message would be helpful, I do not currently posses the knowledge to decipher the way audio works in Godot ^^

**Comment by Calinou** [comment] 2023-04-27 20:42
- Duplicate of https://github.com/godotengine/godot/issues/25875.

**Closed by Calinou** 2023-04-27 20:42 UTC
Labels: bug, platform:windows, platform:linuxbsd, confirmed, topic:audio
