### ISSUE TITLE
A sprite can not be selected and move when flipH or flipV is on.

### ISSUE THREAD

**Issue by technobroken** [godotengine/godot#17433] opened 2018-03-11 11:28 UTC
Godot Version: v3.0.stable.official

OS Version: Fedora 27

A sprite can not be selected and move when flipH or flipV is on.

An scene with a Node2D and a Sprite as child with a texture and FlipV On.

**Comment by Noshyaar** [comment] 2018-03-11 14:20
Duplicate of #16461

**Closed by Noshyaar** 2018-03-11 14:20 UTC
