### ISSUE TITLE
Tilemap tiles are clipped

### ISSUE THREAD

**Issue by gavriil07** [godotengine/godot#22754] opened 2018-10-05 07:13 UTC
**Godot version:**
3.1 alpha 8fc92ae

**OS/device including version:**
Windows 10

**Issue description:**
![sep](https://user-images.githubusercontent.com/28069262/46521061-0122d400-c887-11e8-8a6b-f1e33169af84.gif)

**Steps to reproduce:**
Have a tilemap 30x30, quadrant size 16
Tile size: 32x32px

**Comment by groud** [comment] 2018-10-05 07:43
Are you using an Nvidia card ?
Probably a duplicate of #9913

**Comment by gavriil07** [comment] 2018-10-05 09:21
Yes, I have a Nvidia GTX 1070, seems like it is, this is a bummer :/

**Comment by akien-mga** [comment] 2018-10-05 09:43
Closing as duplicate of #9913.

**Closed by akien-mga** 2018-10-05 09:43 UTC
Labels: bug, topic:rendering
