### ISSUE TITLE
Objects are null if they share a name with an export category.

### ISSUE THREAD

**Issue by DreamsOfGrandeur** [godotengine/godot#74921] opened 2023-03-14 19:26 UTC
### Godot version

4.0.stable

### System information

MacOS 13.2.1

### Issue description

When an exported category is created with `@export_category`, any object that shares the same name will always be `Nil`. A variable with the same name will work as expected if assigned after `@export_category` is called, but will crash if assigned before and referenced after.

### Steps to reproduce

The following code will fail because `Example` is `Nil`.

```
extends Node


@export_category("Example")


func _ready() -> void:
	var example_class: Example = Example.new()
	
	print_debug(example_class.foo)


class Example extends Node:
	
	var foo: String = "bar"
```

This seems to be reproducible with any object, including built-in objects like 'Input'. However, if the `@export_category` call is removed or altered so that the category name differs from the class name, then the code executes as expected. The two must match exactly, including case.

### Minimal reproduction project

N\A: no project files required to reproduce.

**Comment by vnen** [comment] 2023-03-15 18:29
Duplicate of #73843

**Closed** 2023-03-15 18:29 UTC
