### ISSUE TITLE
Viewports do not register 2D Cameras while in the editor 

### ISSUE THREAD

**Issue by ghost** [godotengine/godot#40441] opened 2020-07-16 07:31 UTC
**Godot version:**
v3.2.1

**OS:**
Windows 10

**Issue description:**
When rendering the contents of a Viewport while in the editor, it ignores Camera2Ds. The bug does not occur when rendering 3D objects using a viewport.

**Steps to reproduce:**
1. Open reproduction project 
4. Observe editor preview of a Viewport with a 2D scene with 2D.tscn

![image](https://user-images.githubusercontent.com/34634373/87640338-8e5db280-c714-11ea-8f3b-4d2d0811cc7b.png)

5. Run 2D.tscn (the view now correctly uses the Camera2D)
![image](https://user-images.githubusercontent.com/34634373/87640385-a3d2dc80-c714-11ea-9f9b-45facbe8877e.png)

**Minimal reproduction project:**
[ViewportTextureEditorBug.zip](https://github.com/godotengine/godot/files/4929957/ViewportTextureEditorBug.zip)

**Comment by Nikhil-42** [comment] 2020-07-16 07:32
The error does not occur when rendering 3D nodes with a viewport.

**Comment by Calinou** [comment] 2020-07-16 07:33
Duplicate of https://github.com/godotengine/godot/issues/39387 and possibly others.

**Comment by Nikhil-42** [comment] 2020-07-16 07:37
Wow, that was fast, how did you find a duplicate so quickly? I spent almost an hour scanning through the issue tracker.

**Comment by Nikhil-42** [comment] 2020-07-16 07:43
@Calinou Actually I don't believe this issue is a duplicate of #39387, that one is about the viewport's child nodes not displaying when selected but this issue is about 2D cameras not registering with the viewport until runtime.

**Comment by Calinou** [comment] 2020-07-16 07:48
@Nikhil-42 This one then? https://github.com/godotengine/godot/issues/19638

**Comment by Nikhil-42** [comment] 2020-07-16 07:55
@Calinou #19638 is more similar but my issue is persistent even after restarting the editor and duplicating the viewport container.

**Comment by Nikhil-42** [comment] 2020-07-17 18:29
@Calinou do you know where in the source 2d cameras are registered to a viewport? I checked viewport.cpp and viewport.h but the only mention of a Camera2D was an unused forward class declaration.

**Comment by Calinou** [comment] 2020-07-17 20:46
@Nikhil-42 I don't know, sorry.

**Comment by Nikhil-42** [comment] 2020-07-17 21:27
@Nikhil-42 No worries, I'll just look a little deeper.

**Comment by Nikhil-42** [comment] 2020-07-24 14:08
@Calinou I found that there is a return statement preventing the Camera2D from acting on the Viewport while in the editor.
![image](https://user-images.githubusercontent.com/34634373/88399758-5d752180-cd95-11ea-89b7-4265bdfa9c51.png)
The issue is fixed by removing the return statement. This is my first time contributing to an open-source project. Should I open a PR now?

**Comment by Nikhil-42** [comment] 2020-07-24 14:11
![image](https://user-images.githubusercontent.com/34634373/88400221-06238100-cd96-11ea-8070-2444078ed7f4.png)
-after removing the return statement

**Comment by Nikhil-42** [comment] 2020-07-24 15:39
Also, I get errors while compiling the master branch. When opening a pull request should I still merge into master even though I cannot test it?

**Comment by Nikhil-42** [comment] 2020-07-24 19:30
#40677

**Closed** 2022-12-09 17:07 UTC
Labels: bug, topic:editor, topic:2d

**Comment by SpyrexDE** [comment] 2023-10-30 15:45
Same issue persists in v4.1.1.stable.official [bd6af8e0e], however the editor displays the camera's view correctly when the Camera2D's `enabled` property is unchecked and checked again.
