### ISSUE TITLE
MeshDataTool.create_from_surface() : Index r[i] is out of bounds 

### ISSUE THREAD

**Issue by VirgilusGalacticus** [godotengine/godot#85622] opened 2023-12-01 19:00 UTC
### Godot version

v4.2 stable

### System information

Godot v4.2.stable - Windows 10.0.22621 - Vulkan (Mobile) - dedicated NVIDIA GeForce RTX 4060 Laptop GPU (NVIDIA; 31.0.15.2887) - 13th Gen Intel(R) Core(TM) i7-13700H (20 Threads) - Android 13

### Issue description

Hello everyone,
I  wanted to implement that : https://www.youtube.com/watch?v=4DFpLnEnKFk&t=293s
I found an issue when I wanted to use the MeshDataTool.create_from_surface() function. My code works perfectly on local debugging on my PC but when I tried to deploy/debug on my mobile it throwed:

`
E 0:00:03:0197   UVPosition.gd:19 @ set_mesh(): Index r[i] = 65534 is out of bounds (vcount = 24).
  <Source C++>   scene/resources/mesh_data_tool.cpp:73 @ create_from_surface()
  <Pile des appels>UVPosition.gd:19 @ set_mesh()
                 SetUVPositionMesh.gd:4 @ _ready()
`

![image](https://github.com/godotengine/godot/assets/56887120/12187dbc-6934-44b3-9f59-639bfbc58b76)

I also tried to test with the version 4.1.1 and had the same issue

If someone has a workaround for this issue or can help me
Thanks in advance 

### Steps to reproduce

1. Create a node and attach a script
2. Script:`
func _ready():
	var mesh = ArrayMesh.new()
	mesh.add_surface_from_arrays(Mesh.PRIMITIVE_TRIANGLES, BoxMesh.new().get_mesh_arrays())
	var mdt = MeshDataTool.new()
	mdt.create_from_surface(mesh, 0)
	print(mdt.get_edge_count())
`
3. Test in local : OK (edge count 30)
4. Test with distance debugg on mobile : KO (error + edge count 0)

You can use your own mesh it will always be the same.

### Minimal reproduction project

Or use the following projet (4.2): 
[MeshDataToolTest.zip](https://github.com/godotengine/godot/files/13531041/MeshDataToolTest.zip)

**Comment by bitsawer** [comment] 2023-12-01 20:08
Thanks for the report. This is probably a duplicate of https://github.com/godotengine/godot/issues/75599 or some of its variants, the PR fixing it (https://github.com/godotengine/godot/pull/84852) should hopefully be in the next 4.2.x patch relese. I'm closing this as duplicate, but feel free to comment or reopen this issue if the bug has not been fixed by that PR.

**Closed by bitsawer** 2023-12-01 20:08 UTC
