### ISSUE TITLE
Issue about Rigidbody2D when changed from STATIC to RIGID

### ISSUE THREAD

**Issue by Oberon-Tonya** [godotengine/godot#8909] opened 2017-05-25 15:13 UTC
**Operating system or device - Godot version:**
Win 10 - v2.1.3

**Issue description:**

As for Rigidbody2D , when I changed its mode from RIGID to STATIC , it works properl but not vice versa. When its converted from STATIC to RIGID , it won't be affected by gravity until something touches it. (Well, if I remembered properly, in one of my projects, it's still immovable, though mode has been changed into RIGID).

**Steps to reproduce:**

**Link to minimal example project:**

Left Click to change the one beneath from STATIC to RIGID

[Physics Test.zip](https://github.com/godotengine/godot/files/1029424/Physics.Test.zip)

**Comment by bojidar-bg** [comment] 2017-05-25 20:54
Looks like a duplicate of #7024 to me (though they change it to character instead of rigid there).

**Comment by eon-s** [comment] 2017-05-25 21:01
This is because the body is sleeping, `set_sleeping(false)` when you change the mode (not sure what I would expect when changing modes).

I'm not sure if is the same problem @bojidar-bg but I will do some tests (can't remember if tried the sleep for the other, I will check for 3 too).

**Comment by eon-s** [comment] 2017-05-26 00:39
@bojidar-bg ok, tested and both look like the same sleeping issue, and do not seems to affect Master

**Comment by akien-mga** [comment] 2017-06-29 09:27
Closing as duplicate of #7024.

**Closed by akien-mga** 2017-06-29 09:27 UTC
