### ISSUE TITLE
Windows_maximized can't un-maximize the window in the Linux builds

### ISSUE THREAD

**Issue by SleepyTonia** [godotengine/godot#52986] opened 2021-09-23 23:10 UTC
### Godot version

3.3.3.stable

### System information

Linux Manjaro, KWin, KDE Plasma

### Issue description

Setting `OS.window_maximized` to true maximizes the window with both the Linux and Windows builds, natively and through wine, but setting it to false only un-maximizes the window when using the Windows build through wine in Linux.

### Steps to reproduce

Create a new scene and give the root node this script:
```
extends Node

func _process(delta: float) -> void:
	if Input.is_action_just_pressed("ui_accept"): OS.window_maximized = !OS.window_maximized
```

If the program worked as expected, the window would maximize and then un-maximize every time you press space.

### Minimal reproduction project

[window_maximized.zip](https://github.com/godotengine/godot/files/7221212/window_maximized.zip)

**Comment by Calinou** [comment] 2021-09-23 23:22
Duplicate of https://github.com/godotengine/godot/issues/46840.

**Closed by Calinou** 2021-09-23 23:22 UTC

**Comment by SleepyTonia** [comment] 2021-09-23 23:28
Sorry 😰 Must've mis-typed my search earlier.
