### ISSUE TITLE
WebsocketClient.poll() sometime can crash a thread.

### ISSUE THREAD

**Issue by fian46** [godotengine/godot#28602] opened 2019-05-02 10:48 UTC
as state in title

**Comment by akien-mga** [comment] 2019-05-02 12:22
The sarcasm is not necessary.

Please be more specific, the issue title says "sometime" and the steps to reproduce are "just call poll()".

Is it random? Does it happen only in some situations? What situations? How do you set up your thread and WebSocketClient?

What do you mean by crash? The game crashes with a backtrace?

**Comment by fian46** [comment] 2019-05-02 12:33
wow i dont think it sarcasm. english is not my native language. if you think so i am sorry. i will edit the point where you think it sarcasm. 

'crash the thread' the game is not crash the thread is just not running. and hang forever in poll(). i check is_active is always true. means it still running. but it is not. but the 

is it random ? yes that is why i put 'sometimes'.

**Comment by fian46** [comment] 2019-05-02 12:50
step to reproduce i just loop forever and call pool() in thread

**Comment by Faless** [comment] 2019-05-02 15:03
> step to reproduce i just loop forever and call pool() in thread

Please note that network functions are not thread safe. If you are accessing it from different threads, you need to properly protect critical sections with a mutex.

@fian46 Can you provide a minimal reproduction project?

**Comment by fian46** [comment] 2019-05-02 15:41
[WSRepro.zip](https://github.com/godotengine/godot/files/3138814/WSRepro.zip)
i am sure i use mutex here. i never touch socket when write and read message with game thread only network thread can touch socket and passing message with guarded shared object. but still it crash the thread.

**Comment by fian46** [comment] 2019-05-02 15:43
minimal reproduction project need websocket server running and send pong message back after the project send ping to server.

**Comment by fian46** [comment] 2019-05-02 15:48
[WSRepro.zip](https://github.com/godotengine/godot/files/3138846/WSRepro.zip)
wrong files use this i am sorry

**Comment by Faless** [comment] 2019-05-02 16:44
> 'crash the thread' the game is not crash the thread is just not running. and hang forever in poll(). i check is_active is always true. means it still running. but it is not.

That's still not a `crash`.

In any case, I added prints here an there to your reproduction project all seems to work fine (I've been running ~10 mins now). Note that in your project the Timer is set as oneshot so it sends the data only once (I changed it not to be oneshot so I get constant 1 sec pings)

**Comment by fian46** [comment] 2019-05-02 16:49
i dont know sometimes it stop poll() forever. no shutdown log print in debugger.

**Comment by Faless** [comment] 2019-05-02 17:11
If it stops polling you should get a disconnect in the server after few
minutes. Do you see the disconnect in the server?

**Comment by fian46** [comment] 2019-05-02 17:15
server never get disconnect from client.

**Comment by Faless** [comment] 2019-05-02 17:26
Then it seems like poll is working, why you think it's not? Did you try
stopping the server and see if the client disconnects?

**Comment by fian46** [comment] 2019-05-02 17:31
but the message is never write to server. the server never get any message. i also put log in client loop poll() to check if loop is still running in thread but it stop print anything. i assume thread already crash

**Comment by fian46** [comment] 2019-05-02 17:33
after it stuck client still connected but thread stop running. server detect client still connected but no message arrive. when i close client the server detect connection closed. it means no poll anymore.

**Comment by Faless** [comment] 2019-05-02 17:44
As I said, if you are using the reproduction project you sent me:

The data is only sent one, because the timer is oneshot.
The print inside the poll is outside the while loop, so it will only be
print once.

**Comment by fian46** [comment] 2019-05-02 17:48
my bad can you make it not one shot ? and test it wit wait time 0.1 ?

**Comment by Faless** [comment] 2019-05-02 18:05
Did you try? I tried without lowering the time (left 1 sec) and it was
working.

**Comment by fian46** [comment] 2019-05-02 18:08
so it hang ? and thread is killed but socket still connected right ?

**Comment by Faless** [comment] 2019-05-02 18:25
No, it doesn't hang, it works as expected

**Comment by Faless** [comment] 2019-05-03 15:49
It also works with wait time `0.1`.

**Comment by ryanhuellen** [comment] 2019-06-03 17:58
WebSockets in Godot randomly spit out this error https://cdn.discordapp.com/attachments/583800946639896579/584497147458617350/error1.PNG causing our game to crash. Not sure at all, we need an answer ASAP. Our game jam ends today!

**Comment by Faless** [comment] 2019-06-04 02:51
@ryanhuellen hard to tell the cause, it seems like you are trying to poll a websocket that's been closed or failed to connect. Are you checking that `connect_to_url` returns `OK`? Are you connected to the various signals (`connection_closed`, `connection_error`)? Are you receiving any of them? Can you provide a minimum reproduction project?

**Comment by Faless** [comment] 2019-11-21 15:32
Closing, not really a crash, not apparently a bug, just a bogus game script.

**Closed by Faless** 2019-11-21 15:32 UTC
Labels: bug, topic:network
