### ISSUE TITLE
changing the pitch of an audio pitch effect in audio bus, doesn't change back correctly

### ISSUE THREAD

**Issue by ccuntd** [godotengine/godot#56647] opened 2022-01-09 16:18 UTC
### Godot version

v4.0.dev.custom_build [5a61822d7]

### System information

Linux, Vulkan

### Issue description

the sound will sound worse after changing pitches around, and the pitch won't reset completely.

### Steps to reproduce

change the pitches of the sound and/or via an audio stream bus pitch shift

### Minimal reproduction project

[APE.zip](https://github.com/godotengine/godot/files/7835422/APE.zip)

change the slider around a bit (don't forget to click play on the sound, or it won't break), and then set them back to 1
the sound will sound worse than before.

**Comment by ccuntd** [comment] 2022-01-09 16:18
can someone come up with a better title?

**Comment by ccuntd** [comment] 2022-01-09 16:34
oh and these weird logs:
```
ERROR: Condition "p_pitch_scale <= 0.0" is true.
   at: set_pitch_scale (scene/audio/audio_stream_player.cpp:107)
ERROR: Condition "p_pitch_scale <= 0.0" is true.
   at: set_pitch_scale (scene/audio/audio_stream_player.cpp:107)
ERROR: Condition "p_pitch_scale <= 0.0" is true.
   at: set_pitch_scale (scene/audio/audio_stream_player.cpp:107)
ERROR: Condition "p_pitch_scale <= 0.0" is true.
   at: set_pitch_scale (servers/audio/effects/audio_effect_pitch_shift.cpp:312)
ERROR: Condition "p_pitch_scale <= 0.0" is true.
   at: set_pitch_scale (servers/audio/effects/audio_effect_pitch_shift.cpp:312)
ERROR: Condition "p_pitch_scale <= 0.0" is true.
   at: set_pitch_scale (servers/audio/effects/audio_effect_pitch_shift.cpp:312)
ERROR: Condition "p_pitch_scale <= 0.0" is true.
   at: set_pitch_scale (servers/audio/effects/audio_effect_pitch_shift.cpp:312)
```

**Comment by Calinou** [comment] 2022-01-09 19:02
@©cuntd Can you reproduce this in 3.4.2?

**Comment by ccuntd** [comment] 2022-01-09 19:40
yes, and i found out that only the audio bus causes the issue (audio pitch effect works fine in both versions)
[APE3.zip](https://github.com/godotengine/godot/files/7835776/APE3.zip)

**Comment by ccuntd** [comment] 2022-01-09 20:18
[APE.zip](https://github.com/godotengine/godot/files/7835849/APE.zip)
audio speed scale is also affected

**Comment by ccuntd** [comment] 2022-01-09 20:22
![image](https://user-images.githubusercontent.com/85245131/148699322-abd53139-6d3a-40b9-80e3-6054e7adc967.png)
also, trying to make the effects cancel out each other with speed scale and audio bus is still wrong
(0.1 * 1 * 10 = 1)

**Comment by EviTRea** [comment] 2022-01-14 04:06
This is just like #55090 is it?

**Comment by akien-mga** [comment] 2022-01-14 10:30
Duplicate of #55090

**Closed by akien-mga** 2022-01-14 10:30 UTC
Labels: bug, topic:audio
