### ISSUE TITLE
CPUParticles rendering bug when used together with a delay

### ISSUE THREAD

**Issue by Keetz** [godotengine/godot#30672] opened 2019-07-18 08:37 UTC
**Godot version:**

Godot 3.1.1 Stable
GLES 2 using CPU Particles

**OS/device including version:**

Linux Mint 18.3 Sylvia 64-bit
GPU: GTX 1050ti

Windows 8.1
GPU: GTX 1060

**Issue description:**

When instantiating a scene with a simple particle effect in conjunction with a SceneTreeTimer **yield(get_tree().create_timer(1), "timeout")** the particles starts to render completely wrong, they seem to stretch insanely large, skew, getting weird colors and so on.

**Steps to reproduce:**
Run the included project and try two things.
I setup two inputs **left arrow** and **right arrow**

**left arrow** will just run the function spawning and later removing some particles once.
**right arrow** will run a for loop that runs the same function 100 times, with a 0.1 second delay.

Try and spam the **left arrow** as much as you can! Nothing weird happens, you can spawn particles as fast as you can click, and it looks fine.

Now try and press the **right arrow** just once and let the function run and spawn particles, and a big **WARNING** here if you are sensitive to flashing screens, the particles will go crazy.

![ParticleBug](https://user-images.githubusercontent.com/6707330/61442261-8cb5af00-a947-11e9-939a-1f11f6f5d34e.png)

The picture is from an earlier version of the reproduction project, but the result is the same.

**Minimal reproduction project:**

[ParticleRendererBug.tar.gz](https://github.com/godotengine/godot/files/3405565/ParticleRendererBug.tar.gz)

**EDIT**
It could be somewhat related to #29952 but not really the same visual glitch

**Comment by Keetz** [comment] 2019-07-18 08:44
I tried using a regular timer instead of the SceneTreeTimer, but the same graphical glitch happens.
I will update the title

**Comment by Keetz** [comment] 2019-07-18 12:09
Definitely seems to be an issue with CPU Particles. I tried CPU and GPU particles in GLES3 too, and CPU Particles still has the visual glitches while gpu particles works just fine.

**Comment by Keetz** [comment] 2019-07-18 13:34
Just tested on master (708092f), I don't get the visual glitches  on that commit, but performance is waaaay worse. The reproduction project doesn't lag at all for me on 3.1.1 but on master it does.

So this issue seem to have been fixed, but if someone could point me in the direction of which commit might have fixed the visual glitches I would happily try to cherry pick that and test if it also did something to the performance or if that is caused by something else.

**Comment by akien-mga** [comment] 2019-07-18 13:45
CC @clayjohn

**Comment by clayjohn** [comment] 2019-07-21 22:40
I think it is related to https://github.com/godotengine/godot/commit/24b7f088927e17d80e1e21573b16bee8d3d5d50b

Which in the 3.1 branch was reverted before release https://github.com/godotengine/godot/commit/4aa7760c74075b558d3c530d21e275183b9ca1e7#diff-531cda3564322c1a2ce4d0a3b33f5852

**Comment by akien-mga** [comment] 2019-07-22 07:46
> Which in the 3.1 branch was reverted before release 4aa7760#diff-531cda3564322c1a2ce4d0a3b33f5852

Note that it was released in 3.1-stable, and reverted before 3.1.1-stable.

**Comment by clayjohn** [comment] 2019-07-29 00:17
@Keetz Somehow I missed your comment! Sorry about that. I am looking into this again. I am not seeing the same slowdown on my device that you are getting. However, the fact that there is a slowdown is no surprise now that I am looking into 24b7f08. What 24b7f08 does is set internal_process whenever emitting is true, and whenever internal process is called, it requests a redraw. This is likely responsible for the performance degradation.

**Comment by clayjohn** [comment] 2019-07-29 01:38
@Keetz Just made a PR that should help. I wasnt able to replicate the performance loss you experienced. For me the drop was only about 20 FPS. The PR definitely makes up that difference on my computer. Please test on your system and let me know how it goes.

**3.1.1**
~200 FPS
**Master before**
~180 FPS
**This PR**
~210 FPS

**Comment by Keetz** [comment] 2019-07-29 07:18
@clayjohn I see the exact same drop as on the commit I tested on master before.

Checked out your pull request and this is the result:
The project runs ~2300 fps for me on idle.
Pressing right arrow and starting the spawning drops the fps to ~68

3.1.1-stable + cb4d145:
The project runs ~2300 fps for me on idle.
Pressing right arrow and starting the spawning drops the fps to ~68

Also just cherry picking cb4d145 of course doesn't fix the glitches, I just wanted to test the performance.

**Comment by clayjohn** [comment] 2019-07-31 18:01
@Keetz This gets more and more confusing. Now testing on my low-end laptop to see what difference is made. I get the same performance between master and 3.1.1 stable.

> 3.1.1-stable + cb4d145:
The project runs ~2300 fps for me on idle.
Pressing right arrow and starting the spawning drops the fps to ~68

There is no reason that cb4d145 should reduce performance on your device. We may need to look at alternative causes of the performance drop. 

For starters, how are you measuring FPS? I am using the monitor in Godot's built in debugger, are you using an external tool? 

Second, try building from master with optimizations enabled, maybe the release build has some optimizations enabled that your build doesn't and that is making up the difference. I find it very odd that even 3.1.1-stable + cb4d145 showed the exact same drop as master if the drop is actually caused by 24b7f08.

**Comment by Keetz** [comment] 2019-07-31 18:13
@clayjohn i usually just build with "platform=x11 bits=64" so that could definietly be why. What should i be building with for more accurate results?

I use the monitor in Godot too, so no difference there.

**Comment by clayjohn** [comment] 2019-07-31 18:21
Aha! That may just be it. scons compiles a debug version with optimizations disabled by default in order to increase compilation speed. To use optimizations use the option ``target=release_debug``.

**Comment by Keetz** [comment] 2019-07-31 18:28
Perfect, sorry for that 😄 I will compile some new versions and test, first thing tomorrow!

**Comment by clayjohn** [comment] 2019-07-31 18:46
Great! Let me know the results!

**Comment by akien-mga** [comment] 2019-07-31 19:20
Or simpler, build `3.1.1-stable` with the same command as you build from master, to have the same build conditions.

Otherwise to have the same conditions as the official release builds you also need to enable LTO, build on an old Ubuntu but with a recent GCC, etc., so there are various factors which can have an impact on the final performance (though the major factor should still be the `target` argument, so the tests should still be valid, but possibly with *some* performance difference still).

**Comment by Keetz** [comment] 2019-08-01 08:47
@clayjohn 

Everything build with "scons platform=x11 bits=64 target=release_debug"

3.1.1-stable:
Idle ~2300 fps
Running ~335 fps

3.1.1-stable + cb4d145:
Idle ~2300 fps
Running ~335 fps

master a967ece:
Idle ~2300 fps
Running ~315 fps

#30905:
Idle ~2300 fps
Running ~315 fps

Sorry for the time wasted here, I didn't think about the fact that I was running the official stable version vs. my own compiled versions without optimizations.

**Comment by clayjohn** [comment] 2019-08-01 15:38
No problem! Now that the issue of frame rate is settled I consider this issue closed. :)

**Closed by clayjohn** 2019-08-01 15:38 UTC
Labels: bug, topic:core, topic:rendering
