### ISSUE TITLE
StyleBoxTexture axis stretch tile and tilefit doesn't work when using GLES2

### ISSUE THREAD

**Issue by Shadowblitz16** [godotengine/godot#35186] opened 2020-01-16 04:59 UTC
**Godot version:**
v3.1.2

**OS/device including version:**
Windows 10 pro education 64 bit

**Issue description:**
styles that use tile or tilefit as their axis stretch just stretch it and don't actully tile it.
![image](https://user-images.githubusercontent.com/2453707/72494626-57482c00-37d9-11ea-9e0d-c1c3b55cec32.png)
![image](https://user-images.githubusercontent.com/2453707/72494899-2c120c80-37da-11ea-87d7-d91f833fc288.png)

**Steps to reproduce:**
- make new theme
- create the hscrollbar templates 
- make the hscrollbar scroll style use a tile streach mode for both axes
- back out to theme editor and see it still stretches and doesn't tile at all

**Minimal reproduction project:**
[GUITest.zip](https://github.com/godotengine/godot/files/4069388/GUITest.zip)

**Comment by Oen44** [comment] 2020-08-11 18:06
3.2.2 stable, still a thing.

**Comment by wadim-al** [comment] 2023-05-18 16:46
Can still reproduce on v3.5.2.stable.official [170ba337a]

**Comment by Calinou** [comment] 2023-05-18 20:41
- Duplicate of https://github.com/godotengine/godot/issues/26168.

**Closed by Calinou** 2023-05-18 20:41 UTC
Labels: bug, topic:rendering, confirmed, topic:gui, topic:2d
