### ISSUE TITLE
.res files and uuids keep chaning when using git

### ISSUE THREAD

**Issue by betalars** [godotengine/godot#87614] opened 2024-01-26 13:14 UTC
### Tested versions

- Reproducable in 4.2.1 stable

### System information

nixos unstable

### Issue description

I am importing 3D meshes from a GLTF File. The .res files being generated by this keep on chaning. This causes UUIDs to keep breaking, causing a huge mess in my git repository.

I have not fully understood what the issue is, and it is really confusing.

My gut feeling is: something is messed up with how the UUIDs are being generated that causes them to be non-deterministic ... and that causes a lot of weird quirks down the line. I have encountered a lot of other weird behaviors revolving around this, but I was not able to reproduce most of them. :c

### Steps to reproduce

- initialise a git repo and godot project
- set a save path for a mesh in the advanced options for importing 3D meshes
- add that mesh to a scene and save it
- add *, commit, push
- clone the project to a different folder
- open the scene save it
- observe uuids chaning in the diff
- observe res files changing out of the blue

### Minimal reproduction project (MRP)

[See this repository on gitlab](https://gitlab.com/betalars/minimal-res-uuid-issue)

**Comment by AThousandShips** [comment] 2024-01-26 13:52
Duplicate of https://github.com/godotengine/godot/issues/68672

**Closed by AThousandShips** 2024-01-26 13:52 UTC

**Comment by betalars** [comment] 2024-02-02 15:28
I think there might be more to it than just the UUID issue

I've managed to get [an unexpected res diff without uuids changing when starting from a blank project made in godot 4.2](https://github.com/betalars/godot-uuid-bug/commit/b50a8f5ad64fc5d5669691efc49451ae1fd9c115)

**Steps to reproduce:**
1. git clone git@github.com:betalars/godot-uuid-bug.git
2. open the project with godot
3. git status

**expected:**
clean status
**observed:**
suzanne_Suzanne.res got modified

**Comment by betalars** [comment] 2024-02-02 15:37
Updated Issue Description to reflect new findings
