### ISSUE TITLE
Godot scene is corrupted when saving

### ISSUE THREAD

**Issue by CorneliusChristian** [godotengine/godot#78721] opened 2023-06-26 17:54 UTC
### Godot version

v4.1.dev2.official [668cf3c66]

### System information

Pop OS - v4.1.dev2.official [668cf3c66] - Forward+ Compability

### Issue description

Okay, so I am using Godot 4.1 alpha (Yes, i know it's still in development version). 

When I am about to save my project, I got an error: `"Condition "fwrite(p_src, 1, p_length, f) != p_length" is true."`. 
I close my project, when I go back to edit my project ALL of my scenes are **CORRUPTED**, I put a lot of work in this project, now it's all gone! I don't know what to do, I think godot should have autosave. Can you imagine if other people that have worked on their project for **YEARS** and just gone because of stupid error.

So, please, I really need an autosave feature.
If anyone knows how to recover my files, please tell me.

![image](https://github.com/godotengine/godot/assets/78033120/6dca1a6d-4ec4-4e63-8688-b2df5c7ee7bd)
The image above is files of my scenes that already gone.

### Steps to reproduce

No example.

### Minimal reproduction project

No reproduction steps.

**Comment by trommlbomml** [comment] 2023-06-26 18:34
Hi,

I am very sorry that you face this problem. But as it is always stated is that this a version is not ready for production use, so it should be used with care. In addition even in any stable software it is recommended to use a version control system so that the loss is very small. Maybe you consider using this, e.g. just having git locally. This would at least reduce some friction for you in general regardless of your chosen technically, you are never safe on this side.

Nontheless, I think what would help is if you can reproduce this error, for ideal with a small project to that others do not run into this problem as well.

I cannot say something about restoring your data, as I previously said, is normally minimized using a version control system.

**Comment by Calinou** [comment] 2023-06-27 06:19
Can you describe some reproduction steps? We can't do anything without detailed reproduction steps.

> If anyone knows how to recover my files, please tell me.

There's no way to recover those files as they were never written to disk, judging by the description.

**Comment by CorneliusChristian** [comment] 2023-06-27 06:46
Thanks everyone for the support and help! I think the error/bug is caused because of my full disk. But I think Godot should have a warning message if it can't save the scene correctly.

**Comment by akien-mga** [comment] 2023-06-27 06:52
- Duplicate of #45354
-

**Comment by Zireael07** [comment] 2023-06-27 06:52
ninja'd

**Closed by akien-mga** 2023-06-27 06:52 UTC
Labels: topic:editor, needs testing
