### ISSUE TITLE
Vulkan: Adding a material to a mesh renders it black (clustered) or invisible (mobile)

### ISSUE THREAD

**Issue by Schroedi** [godotengine/godot#57161] opened 2022-01-24 22:28 UTC
### Godot version

4.0 alpha 1

### System information

MacBook Pro (13-inch, M1, 2020), MacOS: 11.6.2

### Issue description

Adding a material to a mesh renders the mesh black or invisible.
- Black in the clustered renderer
- Invisible in the mobile renderer

Changing material parameters, I tried albedo, metallic and roughness do not have any effect. 
It also did not help to add a WorldEnvironment with a procedural sky or custom clear color. 

In the clustered renderer, the color matches the clear color if no sky is used.

Clustered renderer:
<img width="1326" alt="Screen Shot 2022-01-24 at 23 19 58" src="https://user-images.githubusercontent.com/97124/150874601-4530378d-110e-4c7c-8f03-d2f3690f3103.png">

Mobile renderer (effect is the same w/o shadows):
<img width="1748" alt="Screen Shot 2022-01-24 at 23 26 12" src="https://user-images.githubusercontent.com/97124/150875396-1474d157-bfa1-4c53-bca7-5a0fdb44bb80.png">

### Steps to reproduce

Create a MeshInstance and add a material override.

### Minimal reproduction project

[MatTest4.zip](https://github.com/godotengine/godot/files/7929254/MatTest4.zip)

**Comment by fabriceci** [comment] 2022-01-24 22:49
seems to be a duplicate of #51898

**Comment by Calinou** [comment] 2022-02-02 18:51
Duplicate of https://github.com/godotengine/godot/issues/51898 (same cause).

**Closed by Calinou** 2022-02-02 18:51 UTC
Labels: bug, platform:macos, topic:rendering, regression
