### ISSUE TITLE
FileSystem dock leaks resources when filtering over files with the same name

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#29215] opened 2019-05-27 10:57 UTC
**Godot version:**
3.2 b9ee3f3

**OS/device including version:**
Ubuntu 19.04

**Issue description:**
When I open project and scenes, then when I exit Godot, then a lot of leaks like this are shown:
```
Leaked instance: TreeItem:22523
Leaked instance: Image:1751 - Resource name:  Path: 
Leaked instance: TreeItem:20616
Leaked instance: TreeItem:23767
Leaked instance: ImageTexture:1750 - Resource name:  Path: 
Leaked instance: TreeItem:25516
Leaked instance: TreeItem:20914
Leaked instance: TreeItem:22137
Leaked instance: TreeItem:22513
Orphan StringName: ImageTexture
Orphan StringName: TreeItem
Orphan StringName: Image
StringName: 3 unclaimed string names at exit.
ERROR: cleanup: There are still MemoryPool allocs in use at exit!
   At: core/pool_vector.cpp:70.
```
This is similar issue to #22776
**Steps to reproduce:**

1. Open minimal project and Godot with verbose (e.g. ./godot.x11.tools.64 -e -v --path "/home/rafal/Projekty/Sea of Ground")
2. Open all tscn scenes
3. Close this scenes and Godot

**Minimal reproduction project:**
https://github.com/qarmin/Sea-of-Ground

**Comment by akien-mga** [comment] 2019-05-27 11:33
I can't reproduce the issue after #29001.

**Comment by qarmin** [comment] 2019-05-27 11:42
I still can reproduce in  86f9d1b
![file](https://user-images.githubusercontent.com/41945903/58417396-fbcc0100-8084-11e9-835e-e513f73a1a09.gif)

**Comment by akien-mga** [comment] 2019-05-27 12:00
Ok I could reproduce it, it seems dependent on the order in which you open the scene tabs as main screen plugin. When opening all scenes with Quick Open Scene (so in tree alphabetical order, instead of filename alphabetical order), and then closing all of them starting from the first, I don't reproduce the leak.

But if I open them from the FileSystem dock as shown in the video, or if I close them in a different order, then I can reproduce the leaks.

I also noticed that the Map and Town scene (the one of type `Places`) seem to get reloaded all the time when selected.

**Comment by akien-mga** [comment] 2019-05-27 12:09
Actually it seems to be the search in the FileSystem dock which triggers the leak... I can reproduce it with:
- Open project
- Toggle split mode in FS dock
- Search "tscn" in filter
- Close editor

**Comment by akien-mga** [comment] 2019-05-27 12:16
The bug is reproducible in a minimal project, and seems to be triggered when you have two files with the same name in different folders, e.g. two scene files with the same name (which is the case in OP's project, and why searching for "tscn" triggers the bug).

MRP: [Test project.zip](https://github.com/godotengine/godot/files/3223667/Test.project.zip)

Steps to reproduce:
- Open MRP with `--verbose` flag
- Switch to split mode in FS dock
- Search either "tscn" or "png", both return two results with the same name
- Close editor and check terminal

AFAIK the files with the same name don't need to have similar content, the FS dock just trips itself over `TreeItem`s with the same when filtering.

**Comment by qarmin** [comment] 2019-05-27 13:12
Log from Valgrind - [FFFFF.txt](https://github.com/godotengine/godot/files/3223855/FFFFF.txt)
Some of errors:
```
202,048 (74,256 direct, 127,792 indirect) bytes in 238 blocks are definitely lost in loss record 257 of 266
   at 0x581274F: malloc (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
   by 0x379A263: Memory::alloc_static(unsigned long, bool) (memory.cpp:85)
   by 0x379A20C: operator new(unsigned long, char const*) (memory.cpp:42)
   by 0x2B14854: Tree::create_item(TreeItem*, int) (tree.cpp:3012)
   by 0x2115427: FileSystemDock::_create_tree(TreeItem*, EditorFileSystemDirectory*, Vector<String>&, bool) (filesystem_dock.cpp:59)
   by 0x21157AA: FileSystemDock::_create_tree(TreeItem*, EditorFileSystemDirectory*, Vector<String>&, bool) (filesystem_dock.cpp:84)
   by 0x21157AA: FileSystemDock::_create_tree(TreeItem*, EditorFileSystemDirectory*, Vector<String>&, bool) (filesystem_dock.cpp:84)
   by 0x21157AA: FileSystemDock::_create_tree(TreeItem*, EditorFileSystemDirectory*, Vector<String>&, bool) (filesystem_dock.cpp:84)
   by 0x21169F8: FileSystemDock::_update_tree(Vector<String>, bool, bool) (filesystem_dock.cpp:234)
   by 0x2119A28: FileSystemDock::_navigate_to_path(String const&, bool) (filesystem_dock.cpp:462)
   by 0x211D511: FileSystemDock::_select_file(String, bool) (filesystem_dock.cpp:826)
   by 0x2124AAB: FileSystemDock::_file_option(int, Vector<String>) (filesystem_dock.cpp:1504)
```
```
1,952,080 (646,464 direct, 1,305,616 indirect) bytes in 26 blocks are definitely lost in loss record 264 of 266
   at 0x581274F: malloc (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
   by 0x379A263: Memory::alloc_static(unsigned long, bool) (memory.cpp:85)
   by 0x379A20C: operator new(unsigned long, char const*) (memory.cpp:42)
   by 0x33AC0BC: Physics2DServerSW::space_create() (physics_2d_server_sw.cpp:248)
   by 0x33BA145: Physics2DServerWrapMT::spaceallocn() (physics_2d_server_wrap_mt.h:105)
   by 0x33D03C3: CommandQueueMT::CommandRet0<Physics2DServerWrapMT, int (Physics2DServerWrapMT::*)(), int>::call() (command_queue_mt.h:308)
   by 0x33B8702: CommandQueueMT::flush_one(bool) (command_queue_mt.h:428)
   by 0x33B8802: CommandQueueMT::wait_and_flush_one() (command_queue_mt.h:461)
   by 0x33B7CEC: Physics2DServerWrapMT::thread_loop() (physics_2d_server_wrap_mt.cpp:65)
   by 0x33B7C51: Physics2DServerWrapMT::_thread_callback(void*) (physics_2d_server_wrap_mt.cpp:50)
   by 0x1E18F5C: ThreadPosix::thread_callback(void*) (thread_posix.cpp:74)
   by 0x62AF181: start_thread (pthread_create.c:486)
```
```
7,896 (504 direct, 7,392 indirect) bytes in 7 blocks are definitely lost in loss record 229 of 266
   at 0x581274F: malloc (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
   by 0x379A263: Memory::alloc_static(unsigned long, bool) (memory.cpp:85)
   by 0x379A20C: operator new(unsigned long, char const*) (memory.cpp:42)
   by 0x1E16E58: FileAccess* FileAccess::_create_builtin<FileAccessUnix>() (file_access.h:77)
   by 0x376EFAC: FileAccess::create(FileAccess::AccessType) (file_access.cpp:51)
   by 0x376F0DB: FileAccess::create_for_path(String const&) (file_access.cpp:85)
   by 0x376F1B1: FileAccess::open(String const&, int, Error*) (file_access.cpp:110)
   by 0x2377803: EditorAssetLibrary::_image_request_completed(int, int, PoolVector<String> const&, PoolVector<unsigned char> const&, int) (asset_library_editor_plugin.cpp:814)
   by 0x2389D68: MethodBind5<int, int, PoolVector<String> const&, PoolVector<unsigned char> const&, int>::call(Object*, Variant const**, int, Variant::CallError&) (method_bind.gen.inc:3959)
   by 0x3660234: Object::call(StringName const&, Variant const**, int, Variant::CallError&) (object.cpp:940)
   by 0x3661F50: Object::emit_signal(StringName const&, Variant const**, int) (object.cpp:1240)
   by 0x366260F: Object::emit_signal(StringName const&, Variant const&, Variant const&, Variant const&, Variant const&, Variant const&) (object.cpp:1296)
```

**Comment by qarmin** [comment] 2019-10-28 15:08
The simplest way to remove leak is to add memdelete
```
diff --git a/editor/filesystem_dock.cpp b/editor/filesystem_dock.cpp
index e3f0021fb..6a6b904c9 100644
--- a/editor/filesystem_dock.cpp
+++ b/editor/filesystem_dock.cpp
@@ -127,9 +127,9 @@ bool FileSystemDock::_create_tree(TreeItem *p_parent, EditorFileSystemDirectory
                        subdirectory_item->set_collapsed(false);
                } else if (dname != "res://") {
                        subdirectory_item->get_parent()->remove_child(subdirectory_item);
+                       memdelete(subdirectory_item);
                }
        }

        return parent_should_expand;
 }
```
This is not best solution, because I got this errors(but 0 crashes)
```
ERROR: get: Condition ' !p_rid.is_valid() ' is true. returned: __null
   At: ./core/rid.h:149.
ERROR: instance_set_transform: Condition ' !instance ' is true.
   At: servers/visual/visual_server_scene.cpp:589.
ERROR: get: Condition ' !p_rid.is_valid() ' is true. returned: __null
   At: ./core/rid.h:149.
ERROR: instance_set_transform: Condition ' !instance ' is true.
   At: servers/visual/visual_server_scene.cpp:589.
ERROR: get: Condition ' !p_rid.is_valid() ' is true. returned: __null
   At: ./core/rid.h:149.
ERROR: instance_set_transform: Condition ' !instance ' is true.
   At: servers/visual/visual_server_scene.cpp:589.
ERROR: get: Condition ' !p_rid.is_valid() ' is true. returned: __null
   At: ./core/rid.h:149.
ERROR: instance_set_transform: Condition ' !instance ' is true.
   At: servers/visual/visual_server_scene.cpp:589.
```

**Closed** 2020-01-15 21:58 UTC
Labels: bug, confirmed, topic:editor
