### ISSUE TITLE
AABB boxes do not move with the animation

### ISSUE THREAD

**Issue by HoboGus** [godotengine/godot#23227] opened 2018-10-22 17:35 UTC
I cant find any issues already reported on this and im not sure if this is an intended behavior

**Godot version:**
3.0.6 from steam

**OS/device including version:**
Ubuntu 18.04

**Issue description:**
bounding boxes do not move along the animation
![screenshot from 2018-10-23 00-16-52](https://user-images.githubusercontent.com/12368918/47307734-fbd0d200-d659-11e8-9a50-1fe24414af35.png)
and because of that when boxes are off the screen meshes are hidden even if you actually could see them or rather where they are supposed to be, that happens in both editor and ingame
![screenshot from 2018-10-23 00-17-08](https://user-images.githubusercontent.com/12368918/47307884-59fdb500-d65a-11e8-926c-a1da39a7a230.png)

**Steps to reproduce:**
i just imported a model with a bunch of separate meshes for different parts of it

**Minimal reproduction project:**
if needed i could provide my model for testing

**Comment by Cygon** [comment] 2019-01-18 21:52
Related: #16115 (repro product also demonstrates the same issue, just not as good :))

**Comment by KoBeWi** [comment] 2020-06-27 23:32
Can anyone still reproduce this bug in [Godot 3.2.2](https://godotengine.org/article/maintenance-release-godot-3-2-2) or any later release?

If yes, please ensure that an up-to-date Minimal Reproduction Project (MRP) is included in this report (a MRP is a zipped Godot project with the minimal elements necessary to reliably trigger the bug). You can upload ZIP files in an issue comment with a drag and drop.

**Comment by KoBeWi** [comment] 2020-09-28 16:41
Closing due to lack of update. Please comment if you can still reproduce this issue in the latest stable version of Godot.

**Closed by KoBeWi** 2020-09-28 16:41 UTC
Labels: bug, topic:import, topic:rendering
