### ISSUE TITLE
await_signal(obj, "signal")

### ISSUE THREAD

**Issue by dalexeev** [godotengine/godot#31494] opened 2019-08-20 00:04 UTC
**Issue description:**

Situation 1.
```gdscript
func f():
    print(1)

func g():
    f()
    print(2)
    # 1; 2
```
Typical situation: `g()` will wait until `f()` is over.

Situation 2.
```gdscript
func f():
    yield(obj, "signal")
    print(1)

func g():
    f()
    print(2)
    # 2; 1
```
`f()` will pause and wait for the signal, and `g()` will continue and will not wait for `f()`.

If I need to avoid this behavior, now I have to use the following construction:
```gdscript
func f():
    yield(get_tree().create_timer(0.0), "timeout")
    yield(obj, "signal")
    print(1)

func g():
    yield(f(), "completed")
    print(2)
    # 1; 2
```

Why not just pause `f()` without resuming `g()`? Something like that:
```gdscript
func f():
    await_signal(obj, "signal")
    print(1)

func g():
    f()
    print(2)
    # 1; 2
```
Thus, `g()` waits for `f()`, which waits for the signal.

Probably, this issue is related to #22947, but I still decided to propose this option, because it is different.

**Comment by KoBeWi** [comment] 2019-08-20 01:30
Sounds like a duplicate of #25511

**Comment by dalexeev** [comment] 2019-08-20 06:25
Theoretically, the last example from the previous comment is equivalent to the following code:
```gdscript
func f():
    yield(obj, "signal")
    print(1)

func g():
    await f()
    print(2)
    # 1; 2
```
But the proposed feature provides for this rare case:
```gdscript
func f():
    yield_local(obj, "signal")
    print(1)
    yield(obj2, "signal2")
    print(2)

func g():
    f()
    print(3)
    # 1; 3; 2
```

I don't know what is the best option, but considering how many of the proposals received, there must be some consensus.

**Comment by dalexeev** [comment] 2019-08-20 07:25
I understood why these features are different:
`await f()` - waits for the **function** to complete.
`yield_local(obj, "signal")` - waits until the **signal** is emitted.

Probably, the name `await_signal` is better.

**Comment by hilfazer** [comment] 2019-09-01 07:53
What would happen to h() function that calls g()? Would it be suspended as well?

**Comment by dalexeev** [comment] 2019-09-01 08:33
Yes it will. See Situation 1.

**Comment by mhilbrunner** [comment] 2020-05-28 15:44
See https://github.com/godotengine/godot/pull/39093 - if this isn't done in Godot 4.0/GDScript 2.0, you may consider opening a new proposal in the dedicated proposals repository:

---

Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!

**Closed by mhilbrunner** 2020-05-28 15:44 UTC
Labels: feature proposal, topic:gdscript
