### ISSUE TITLE
Renaming folder causes crash + scripts still heading to old paths

### ISSUE THREAD

**Issue by quantumcode-martin** [godotengine/godot#62100] opened 2022-06-16 09:05 UTC
### Godot version

4.0.alpha10

### System information

Windows 10

### Issue description

I renamed a folder in my project, the editor closed with an error popup visible during only a few seconds.
Then I can reopen the project, the folder has been renamed correctly.
But for a lot of scenes, the path leading to script in the scene file is still the old one `[ext_resource type="Script" path="res://OldPath/script.gd" id="1_axulu"]`.

When I use the console I can see a lot of errors:

```
SCRIPT ERROR: Parse Error: Could not find script for class "ClassA".
          at: GDScript::reload (res://new_folder/script_1.gd:74)
```
and
```
ERROR: Attempt to open script 'res://OldFolder/script_2.gd' resulted in error 'File not found'.
   at: (modules/gdscript/gdscript.cpp:1041)
```

It seems there are 2 problems:
1) The renaming causes issues with classes declared using `class_name`
2) There is an ordering issue, Godot tries to access some script files in the old folder, using the old name.

### Steps to reproduce

Create a Godot project with scripts, linked to saved scenes in a folder.
Also create scripts with `class_name`.

Then try to rename the folder (from the editor).

**Comment by KoBeWi** [comment] 2022-10-13 12:00
Can't reproduce in newest beta.

@quantumcode-martin Do you have any minimal reproduction project?

**Comment by KoBeWi** [comment] 2022-11-28 12:15
Closing due to lack of update.
Comment if you can still reproduce in the newest beta (also be sure to attach MRP).

**Closed by KoBeWi** 2022-11-28 12:15 UTC
Labels: bug, topic:gdscript, topic:editor, crash
