### ISSUE TITLE
exported static typed arrays can't be filled with the nodes specified

### ISSUE THREAD

**Issue by agrimminck** [godotengine/godot#77494] opened 2023-05-26 02:00 UTC
### Godot version

4.0.3

### System information

Windows 10, Intel icore7, NVIDIA 730, 16Gb RAM

### Issue description

When I write this code
`@export var array_of_nodes : Array[Node]`
And try to assign nodes to the elements of the array through the inspector, the program will not allow it and keep the values as "empty"

### Steps to reproduce

write the piece of code
`@export var array_of_nodes : Array[Node]`
and try to assign any node in the scene to that script

### Minimal reproduction project

[project.zip](https://github.com/godotengine/godot/files/11570774/project.zip)

**Comment by KoBeWi** [comment] 2023-05-26 03:57
Duplicate of #62916

**Closed by KoBeWi** 2023-05-26 03:57 UTC
