### ISSUE TITLE
TAA doesn't work for the sky

### ISSUE THREAD

**Issue by ValeronSA** [godotengine/godot#87480] opened 2024-01-22 17:52 UTC
### Tested versions

v4.2.1.stable.official [b09f793f5]

### System information

Windows 10 - Godot Engine v4.2.1.stable - Vulkan API 1.3.260 - Forward+ -  NVIDIA GeForce GTX 1050 Ti

### Issue description

Motion vectors are not calculated when the camera is rotated, which is why the sky is blurred when rotated. At the same time, for FSR2 the sky is calculated correctly.

### Steps to reproduce

1. Create Camera3D
2. Add any script to control the rotation of the camera
3. Create WorldEnvironment
4. Add new Environment in WorldEnvironment
5. Set Sky in Background mode in Environment
6. Add new Sky in Environment
7. Add new ShaderMaterial in Sky
8. Add any contrast Sky Shader in ShaderMaterial 
9. Enable the "Use TAA" option in Anti Alising settings
10. Disable "FSR2.2" option in Scaling 3D settings
11. Enjoy

### Minimal reproduction project (MRP)

[Uploading TAA BUG.zip…]()

**Comment by AThousandShips** [comment] 2024-01-22 17:54
Possibly a duplicate of:
* https://github.com/godotengine/godot/issues/67332

**Comment by ValeronSA** [comment] 2024-01-22 17:55
Yes, that's her, thank you

**Closed** 2024-01-22 17:56 UTC
Labels: bug, topic:rendering, topic:3d
