### ISSUE TITLE
Godot 3.5 RC 7,  iOS 16 safari  HTML 5,  engine load crash

### ISSUE THREAD

**Issue by nne998** [godotengine/godot#63525] opened 2022-07-27 09:40 UTC
### Godot version

Godot 3.5 RC 7

### System information

iOS 16 beta 3

### Issue description

 godot engine load crash

### Steps to reproduce

1、Create a new project
2、Exported to  HTML 5 , upload to server
3、Load the url on iPhone safari

 

### Minimal reproduction project
Simply visit this exported page at the following url:
[https://dl.lookingpet.com/temp/ios16_test/game.html](https://dl.lookingpet.com/temp/ios16_test/game.html)

project source code:
[ios16_test1.zip](https://github.com/godotengine/godot/files/9197050/ios16_test1.zip)

**Comment by akien-mga** [comment] 2022-07-27 10:06
Duplicate of #62445.

**Closed by akien-mga** 2022-07-27 10:06 UTC

**Comment by akien-mga** [comment] 2022-07-27 10:07
You had commented on that issue already, please don't open new issues if there's already one for the same problem.
