### ISSUE TITLE
Generated lightmap artifacts on certain geometries

### ISSUE THREAD

**Issue by knrewp** [godotengine/godot#16966] opened 2018-02-24 01:08 UTC
**Godot version:**

v3.0 stable x64

**OS/device including version:**
windows

**Issue description:**

generated lightmap shows visual issues on certain meshes as tested. 3 meshes were tried made in blender with different tehniques. raytrace was used as it shows more issues than conetrace.

**Steps to reproduce:**
load the model files from the project, add a single point light inside of each object, add BakedLightmap nodes and hit bake

**Minimal reproduction project:**

[Export.zip](https://github.com/godotengine/godot/files/1753684/Export.zip)
open the Spatial scene for testing

![image](https://user-images.githubusercontent.com/36779716/36623704-2502f542-1907-11e8-9d02-55d6428ab43e.png)
![image](https://user-images.githubusercontent.com/36779716/36623712-33658758-1907-11e8-9fd0-70303be94462.png)

**Comment by qarmin** [comment] 2019-12-26 09:15
I can't reproduce issue in 3.2 beta 4

**Comment by Calinou** [comment] 2019-12-26 14:17
I can't reproduce this either on commit https://github.com/godotengine/godot/commit/318c69351624f7794c51b5385d252af397c0404a, closing.

Other kinds of BakedLightmap artifacts are already covered in #30929.

**Closed by Calinou** 2019-12-26 14:17 UTC
Labels: bug, topic:rendering
