### ISSUE TITLE
Popup script section.featurerequest

### ISSUE THREAD

**Issue by bkoklu001** [godotengine/godot#31552] opened 2019-08-22 02:11 UTC
Feature Request!
I don't know if this has been requested but, here we go:
For people with dual monitors, it would be easier to not use an external editor and use Godot's script section. If you could have the script section popup into another window, that would be a whole lot easier for me and others.

**Comment by bojidar-bg** [comment] 2019-08-22 06:54
I guess this would be a duplicate of #9059?

**Comment by akien-mga** [comment] 2019-08-22 07:07
Duplicate of #9059 indeed.

**Closed by akien-mga** 2019-08-22 07:07 UTC
