### ISSUE TITLE
Duplicating/Copying CollisionShape2D's causes the Collision shapes to be linked

### ISSUE THREAD

**Issue by CC-Cosmos** [godotengine/godot#49916] opened 2021-06-25 19:14 UTC
### Godot version

3.3.2 stable

### System information

Linux, GLES3

### Issue description

Duplicated CollisionShape2D nodes have a linked collision shape size with the collision shape it was duplicated/copied from. 

It should be noted this can be stopped by simply deleting the collision shape 2D node and re-adding it or by simply resetting the nodes collision shape to default.

### Steps to reproduce

Create a collision shape 2D, give it any shape, then duplicate it. 

Move the shape of the duplicate outside of the original (for better visibility)

Change the scale of one of them and both will follow. 

video demonstration vvv

https://user-images.githubusercontent.com/76600284/123474417-ed37d700-d5c7-11eb-9087-5f2d03b2b444.mp4

### Minimal reproduction project

[Collision Shape 2d.zip](https://github.com/godotengine/godot/files/6718324/Collision.Shape.2d.zip)

**Comment by kleonc** [comment] 2021-06-25 20:21
It's intended/correct behavior, that's how [Resources](https://docs.godotengine.org/en/3.3/getting_started/step_by_step/resources.html) work by design.

After duplicating you can make any Resource unique:
![eOzhgFqMBO](https://user-images.githubusercontent.com/9283098/123481110-94862f80-d603-11eb-92c1-cffb27aa7583.png)

You can make all sub-Resources unique:
![Godot_v3 3 2-stable_win64_Fqa19y81MQ](https://user-images.githubusercontent.com/9283098/123480723-0f9b1600-d603-11eb-9908-b372098e869b.png)

You can also mark a Resource as local to scene:
![B5KoFRsFNU](https://user-images.githubusercontent.com/9283098/123480728-1164d980-d603-11eb-8d20-45feeb492523.png)

**Comment by Calinou** [comment] 2021-06-25 20:22
Closing per @kleonc's comment.

**Closed by Calinou** 2021-06-25 20:22 UTC

**Comment by shoeffner** [comment] 2025-04-29 20:36
I solved this problem for Shape resources of CollisionShape2D with the following plugin script, which duplicates selected CollisionShape2D nodes and their Shape resources when you press `Ctrl+E`:
```
@tool
extends EditorPlugin


func _enter_tree() -> void:
	# Initialization of the plugin goes here.
	pass

func _input(event: InputEvent) -> void:
	if event.is_pressed() and event.as_text() == "Ctrl+E":
		for node in EditorInterface.get_selection().get_selected_nodes():
			var collision_shape = node as CollisionShape2D
			if collision_shape == null:
				print("Cannot duplicate %s with unique Shape resource (no CollisionShape2D)" % node)
				continue
			print("Duplicating %s with unique Shape resource" % node)
			var new_collision_shape = collision_shape.duplicate() as CollisionShape2D
			new_collision_shape.shape = new_collision_shape.shape.duplicate()
			collision_shape.get_parent().add_child(new_collision_shape, true)
			new_collision_shape.owner = collision_shape.owner

func _exit_tree() -> void:
	# Clean-up of the plugin goes here.
	pass

```
(It uses `event.is_pressed() and event.as_text()` because of https://github.com/godotengine/godot/issues/74993, otherwise this could be an input action...)
