### ISSUE TITLE
Full screen flickering in the editor

### ISSUE THREAD

**Issue by Torguen** [godotengine/godot#34780] opened 2020-01-03 10:48 UTC
**Godot version:**
3.2 beta 4 mono

**OS/device including version:**
Win10 64 Home

**Issue description:**
With the option "Editor -> Change to fullscreen mode" activated:
A blink occurs when executing a scene.
A blink occurs when the execution window is closed.
A blink occurs when you select another window (for example Chrome) and use two monitors.
In short, a blink occurs when the editor receives or loses focus with the "Editor -> Change to fullscreen mode" option activated.

**Steps to reproduce:**
Activate the "Editor -> Change to fullscreen mode" option and execute a scene.

**Minimal reproduction project:**

**Comment by qarmin** [comment] 2020-01-03 11:24
Similar or duplicate https://github.com/godotengine/godot/issues/21475

**Comment by akien-mga** [comment] 2020-01-03 11:53
Closing as duplicate of #21475.

**Closed by akien-mga** 2020-01-03 11:53 UTC
