### ISSUE TITLE
Issue with Texture rect stretch mode Tile

### ISSUE THREAD

**Issue by a2576** [godotengine/godot#82312] opened 2023-09-25 16:11 UTC
### Godot version

v4.1.1.stable.mono.official

### System information

Godot v4.1.1.stable.mono - Windows 10.0.19045 - Vulkan (Compatibility) - GeForce GT 520 () - Intel(R) Core(TM) i3-2120 CPU @ 3.30GHz (4 Threads)

### Issue description

When I set texture rect stretch mode to Tile and open fullscreen while scene is running texture rect changes to only one Tile with lines coming from the right side and down these line change colour depending on image colour

https://github.com/godotengine/godot/assets/146011432/22573f03-2c3d-4d05-ab25-c44a021cff19

### Steps to reproduce

Put a Texture Rect 
add an image to Texture Rect
Change Texture Rect Stretch mode to Tile
Run Scene

### Minimal reproduction project

N/A

**Comment by dylancusson** [comment] 2023-09-25 17:04
This bug is only when using the Compatibility renderer correct? Was able to reproduce on both regular and mono versions when using the compatibility renderer. Bug did not occur on Forward+ or Mobile renderers.

**Comment by a2576** [comment] 2023-09-25 19:21
Yes I was using compatibility because of my bad hardware but I didn't test mobile

**Comment by kleonc** [comment] 2023-09-25 20:46
Likely a duplicate of #79315 which is fixed since `v4.2.dev2`. The fix was also backported to `v4.1.2` (included since `v4.1.2.rc1`). Please test these or newer versions.

**Comment by a2576** [comment] 2023-09-25 21:16
THANK YOU SO MUCH

**Closed** 2023-09-25 21:17 UTC
