### ISSUE TITLE
Instancing a viewport in runtime stops godot half a second

### ISSUE THREAD

**Issue by Ranoller** [godotengine/godot#19769] opened 2018-06-25 18:30 UTC
**Godot version:**

Godot 3 to 3.1 dev

**OS/device including version:**

Win 7 GeForce GTX 660/PCIe/SSE2

**Issue description:**

Playing a game from GodotJam2018 i find an issue that stops godot several frames. This is the game:
https://securas.itch.io/skrolls-of-thermos
(source is included)
The designer instance scenes that contain **viewports**. Every time one of this scenes is instanciated, godot spikes half a second (to big stutter, about 0.40 sec). Stutter happends in instancing, not in node entering tree. I don´t know if this behaviour of viewport is normal, but I report.

**Steps to reproduce:**
Open the game and play, in some computers, every time a enemy or a shoot is spammed, the multi-frame skip happends.

**Minimal reproduction project:**

https://github.com/securas/Skrolls-of-Thermos

**Comment by KoBeWi** [comment] 2020-06-15 22:09
Can anyone still reproduce this bug in Godot 3.2.1 or any later release (e.g. [3.2.2rc1](https://godotengine.org/article/release-candidate-godot-3-2-2-rc-1))?

If yes, please ensure that an up-to-date Minimal Reproduction Project (MRP) is included in this report (a MRP is a zipped Godot project with the minimal elements necessary to reliably trigger the bug). You can upload ZIP files in an issue comment with a drag and drop.
(the provided link is dead)

**Comment by KoBeWi** [comment] 2020-09-28 00:26
Closing due to no reply. Please comment if you can still reproduce in 3.2.3+.

**Closed by KoBeWi** 2020-09-28 00:26 UTC
Labels: bug, topic:core
