### ISSUE TITLE
Godot 3.1 error: condition´_debug_parse_err_line >= 0 is true. returned: null someone could help me(alguien me puede ayudar)

### ISSUE THREAD

**Issue by pingul003** [godotengine/godot#29522] opened 2019-06-06 01:54 UTC
Using the latest Godot
I get error: condition´_debug_parse_err_line >= 0 is true. returned: null 
someone could help me

```
extends Node2D
var pantalla_tamano
var pad_tamano


func _ready():
	pantalla_tamano= get_viewport_rect().size
	pad_tamano= get_node($izquierda). get_textures().get_size()
	set_process(true)
	
	
	var bola_velocidad = 80
	var direccion = Vector2 (-1,0)

const pad_velocidad= 150

func _process(delta):
	
	var bola_posicion = get_node($pelota).get_pos()
	var rect_izq = Rect2(get_node($izquierda).get_pos() - pad_tamano/2, pad_tamano)
	var rect_der = Rect2(get_node($derecha).get_pos() - pad_tamano/2, pad_tamano)
	
	bola_posicion += direccion * bola_velocidad * delta
	
	if((bola_posicion.y < 0 and direccion.y < 0) or (bola_posicion.y > pantalla_tamano.y and direccion.y > 0)):
		direccion.y = -direccion.y
		
	if ((rect_izq.has_point(bola_posicion)and direccion.x < 0) or (rect_der.has_point(bola_posicion) and direccion.x >0)):
		direccion.x = -direccion.x
		bola_velocidad*= 1.1
		direccion.y = randf() * 2.0 - 1
		direccion = direccion.rormalized()
		
	if (bola_posicion.x < 0 or bola_posicion.x > pantalla_tamano.x):
		bola_posicion= pantalla_tamano *0.5 #la pelota va al centro de la pantalla
		bola_velocidad= 80
		direccion= Vector2 (-1,0)
	
	get_node($pelota).set_pos(bola_posicion)
	
	#movimiento pad izquierdo
	var izq_posicion= get_node($izquierda).get_pos()
	
	if (izq_posicion.y > 0 and Input.is_action_pressed("izq_mover_arriba")):
		izq_posicion.y += -pad_velocidad * delta
	if (izq_posicion.y < pantalla_tamano.y and Input.is_action_pressed("izq_mover_abajo")):
		izq_posicion.y += pad_velocidad * delta
	get_node($izquierda).set_pos(izq_posicion)
	
	#moviminto pad derecho
	var der_posicion= get_node($derecha).get_pos()
	
	if (der_posicion.y > 0 and Input.is_action_pressed("der_mover_arriba")):
		der_posicion.y += -pad_velocidad * delta
	if(der_posicion.y < pantalla_tamano.y and Input.is_action_pressed("der_mover_abajo")):
		der_posicion += pad_velocidad * delta
	
	get_node($derecha).set_pos (der_posicion)
```
_bugsquad edit:_ Added back ticks for multiline code formatting

**Comment by Paulb23** [comment] 2019-06-06 21:16
Duplicate of #26691?

**Comment by pingul003** [comment] 2019-06-07 01:14
no

**Comment by bojidar-bg** [comment] 2019-06-07 14:59
Error seems to come from here:
https://github.com/godotengine/godot/blob/b9dc2e7e4dd38621ef0dd07d208ffc5468954adb/modules/gdscript/gdscript_editor.cpp#L330

`_debug_parse_err_line` comes from `debug_break_parse`:
https://github.com/godotengine/godot/blob/b44cb4e3b9b573a3cbbd6f71aff81e6c3465d84b/modules/gdscript/gdscript_editor.cpp#L175
or `debug_break`:
https://github.com/godotengine/godot/blob/b44cb4e3b9b573a3cbbd6f71aff81e6c3465d84b/modules/gdscript/gdscript_editor.cpp#L189

...
Is there a parsing error in the script?
Also, note that `get_node($...)` translates to `get_node(get_node("..."))`, which is certainly not what you want. You should either write just `$...` or `get_node("...")`.

**Comment by akien-mga** [comment] 2020-01-14 23:09
Bug in the script:
```
direccion = direccion.rormalized()
```

That's a duplicate of #26691.

**Closed by akien-mga** 2020-01-14 23:09 UTC
Labels: topic:gdscript
