### ISSUE TITLE
Advance expression for AnimationTree doesn't seem to work 

### ISSUE THREAD

**Issue by joaopedrosgs** [godotengine/godot#62530] opened 2022-06-29 17:02 UTC
### Godot version

v4.0.alpha.calinou [caa9ec8ac]

### System information

Windows 10, Vulkan

### Issue description

I'm using a simple state machine within the AnimationTree
![image](https://user-images.githubusercontent.com/16986475/176492352-ff511995-7054-459d-871e-da1f38041e91.png)

Along with Advance Expressions like (this one is for idle_1 to walking):
![image](https://user-images.githubusercontent.com/16986475/176492434-dad82f02-0758-4bcd-9881-c57d1ec0b883.png)
 
However, it simply doesn't trigger the transition

### Steps to reproduce

1. Create a CharacterBody3D
2. Drop a model with animations (a gltf with a character for example) inside the CharacterBody3D
3. Add an AnimationTree node, assign it to the AnimationPlayer from your model, enable it and assign the Advance expression base node to be the CharacterBody3D
4. Create a new Tree Root in your AnimationTree. I used a simple State Machine.
5. Setup your tree using Advance Expressions. I just created an idle and a walking state, with a transition idle->walking using the expression "velocity.length()>1.0"
6. Check the results in-game

### Minimal reproduction project

[TestExpressions.zip](https://github.com/godotengine/godot/files/9012606/TestExpressions.zip)

**Comment by Calinou** [comment] 2022-06-29 18:18
For reference, advance expressions were added in https://github.com/godotengine/godot/pull/61196.

cc @fire

**Comment by fire** [comment] 2022-06-29 18:36
I'll take a look. Is length a const method?

**Comment by permelin** [comment] 2022-07-01 19:14
You can set the expression to simply `true` and it still won't advance **if** _Expression Base Node_ has been assigned on the transition. But if I clear the _Expression Base Node_, it does trigger, as long as _Advance Expression Base Node_ is set on the AnimationTree itself.

**Comment by permelin** [comment] 2022-07-01 20:31
I also just noticed that which node I assign to _Advance Expression Base Node_ doesn't matter. The expression will always be executed in the context of the AnimationTree node.

**Comment by joaopedrosgs** [comment] 2022-07-15 10:32
any news about this?

**Comment by permelin** [comment] 2022-07-20 15:52
> Hey, I've created a new pull request #63238 that solves this issue

Nice. I have a theory about the second issue: why not even `true` works when _Expression Base Node_ is set on the transition itself.

When you set the node property in the inspector on the transition, the editor makes a path that is **relative to the scene root.**
When you set the corresponding property on the AnimationPlayer you get a path that is **relative to the player node.**

The path is then used relative to the AnimationTree node with `tree_base->get_node_or_null(advance_expression_base_node_path)` which is correct in one case but wrong in the other. The expression is then silently ignored if the path can't be resolved.

I assume this happens because `AnimationNodeStateMachineTransition` is not a node but a resource, and therefore not part of the tree, so the path can't be made relative to it.

**Comment by permelin** [comment] 2022-07-20 17:00
> I'm not sure how to solve that

Maybe the solution is to take a step back. Should this base node property exist on the individual transitions in the first place? It creates dependencies deep inside a nested resource on the structure of the node tree in which the resource will be used. Doesn't seem like something that should be encouraged.

**Comment by alfredbaudisch** [comment] 2022-09-14 14:16
It seems that the issue is still present in alpha17, no matter the expression you put, even if you write `true` directly, the transition does not happen.

I don't think attaching a reproduction project is needed because it's simply the same issue as OP - or simply write `true` in the expression, there's no transition.

**Comment by permelin** [comment] 2022-09-14 14:43
@alfredbaudisch Are you setting the Expression Base Node field directly on the transition? There were two parts to this issue. One was fixed and one was not.

IIRC, if you set the expression base node only on the animation tree and not on the transition then it should work now.

That field should be removed from the transition node unless someone can figure out a solution.

**Comment by joaopedrosgs** [comment] 2022-09-15 09:51
Yep, precisely what @permelin said. If you leave the Base Node blank, it will work (and use the animation tree node as the source for the variables).

**Comment by alfredbaudisch** [comment] 2022-09-15 10:07
> Are you setting the Expression Base Node field directly on the transition?

That was it, thanks. Confirmed the issue as you said: setting in the animation tree directly made it work, on the other hand the transition base node is ignored.

**Comment by GuilhermeGSousa** [comment] 2022-09-28 20:47
@akien-mga I was testing and my previous fix does not work if there are autoloaded nodes in the tree, this issue should probably be reopened.

**Comment by fire** [comment] 2022-09-28 21:30
Thanks for testing!

**Comment by GuilhermeGSousa** [comment] 2022-09-28 21:37
I'm sorry for not testing it in depth to begin with!

**Closed** 2022-10-07 12:23 UTC
Labels: bug, topic:animation
