### ISSUE TITLE
Zoom Out the graph using '-',then move the block, and the block don't follow the mouse.

### ISSUE THREAD

**Issue by zhagsenkk** [godotengine/godot#4783] opened 2016-05-23 15:44 UTC
**Operating system or device - Godot version:**
win10-2.0.3

**Issue description** (what happened, and what was expected):
![default](https://cloud.githubusercontent.com/assets/10054853/15476175/3f51526a-2140-11e6-985a-53f56034bfe5.png)

Zoom Out the graph using '-',then move the block, and the block don't follow the mouse.

**Steps to reproduce:**
Zoom Out the graph using '-',then move the block, and the block don't follow the mouse.

**Link to minimal example project** (optional but very welcome):

**Comment by akien-mga** [comment] 2016-05-23 16:30
Duplicate of #4782 (GitHub was having issues).

**Closed by akien-mga** 2016-05-23 16:30 UTC
