### ISSUE TITLE
SpotLight3D shadows exhibit flickering when moved around.

### ISSUE THREAD

**Issue by catboy-catfish** [godotengine/godot#91976] opened 2024-05-15 10:59 UTC
### Tested versions

Only tested v4.3.dev6.mono.official [89850d553] and v4.2.2.stable.official [15073afe3]. Reproducible in v4.3, doesn't seem to be reproducible in v4.2.2.

### System information

Godot v4.3.dev6.mono - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1650 (NVIDIA; 31.0.15.5186) - Intel(R) Core(TM) i3-6100 CPU @ 3.70GHz (4 Threads)

### Issue description

The shadows from a SpotLight3D start to flicker whenever moved around in 4.3.dev6 official build. The issue can be seen more clearly in the linked video. (There are more files in the video's file browser than there are in the MRP because I didn't delete as much files beforehand.)

https://github.com/godotengine/godot/assets/94094139/bdaad887-ae8d-4ba5-88f4-d86f38ef3452

### Steps to reproduce

1. Open the MRP listed below.
2. Hit the play button.
3. Controls - WASD: movement | Mouse: look around | Space: jump | Shift: run | Ctrl: walk slowly |

### Minimal reproduction project (MRP)

[flickering-shadows-mrp 4.3-dev6.zip](https://github.com/godotengine/godot/files/15320281/flickering-shadows-mrp.4.3-dev6.zip)

**Comment by lawnjelly** [comment] 2024-05-15 11:22
It might be worth turning off tighter shadow culling in project settings advanced , rendering lights and shadows, to check whether this is a regression due to tighter culling.

If so I can investigate saturday. There is currently a known bug with directional lights in dev6, but spots and omnis no bugs currently reported.

**Comment by matheusmdx** [comment] 2024-05-15 11:51
> It might be worth turning off tighter shadow culling in project settings advanced , rendering lights and shadows, to check whether this is a regression due to tighter culling.

I can confirm disabling tighter shadow culling stops the flickering

**Comment by catboy-catfish** [comment] 2024-05-15 22:39
> It might be worth turning off tighter shadow culling in project settings advanced , rendering lights and shadows, to check whether this is a regression due to tighter culling.
> 
> If so I can investigate saturday. There is currently a known bug with directional lights in dev6, but spots and omnis no bugs currently reported.



> > It might be worth turning off tighter shadow culling in project settings advanced , rendering lights and shadows, to check whether this is a regression due to tighter culling.
> 
> I can confirm disabling tighter shadow culling stops the flickering

Just tried this out, it does seem to solve the flickering issue, but apparently tighter shadow caster culling can increase performance, which is exactly what I want. Maybe tighter shadow caster culling could be set separately for each light?

**Comment by matheusmdx** [comment] 2024-05-15 22:59
@catboy-catfish Don't worry, this was just to know where the problem started, is not the final solution. As lawnjelly said this will be investigated to make work with tighter shadow culling

**Comment by catboy-catfish** [comment] 2024-05-15 23:35
> @catboy-catfish Don't worry, this was just to know where the problem started, is not the final solution. As lawnjelly said this will be investigated to make work with tighter shadow culling

Cool cool, maybe I could make a proposal out of this

**Comment by lawnjelly** [comment] 2024-05-16 12:39
Re-opening as this is not fixed yet. Disabling was to identify the bug, not to fix.

**Comment by lawnjelly** [comment] 2024-05-18 08:55
First step was making a more usable MRP, then converting to 3.x:
[spotlight_tight_cull_bug.zip](https://github.com/godotengine/godot/files/15360912/spotlight_tight_cull_bug.zip)

**Comment by lawnjelly** [comment] 2024-05-18 10:57
Getting clues now. It seems to be due to the spotlight being attached to the camera, at 0, 0 on the y and z axis.

The light position is therefore on the exact boundary for the top and bottom camera frustum planes, and sometimes the distance check is returning +0 and sometimes -0 due to float inaccuracy.

This may need an epsilon to prevent this edge condition.

**Closed** 2024-05-21 09:24 UTC
Labels: bug, topic:rendering, regression, topic:3d
