### ISSUE TITLE
Assets projects are blury (In the library minature and inside the editor.

### ISSUE THREAD

**Issue by SvOTM** [godotengine/godot#58797] opened 2022-03-05 04:17 UTC
Godot version: 3.4.3

 Issue description: I'm new to Godot and trying it for the very first time. Wanted to check some
                             demo assets from the library, but when I get into them they are totally blury, also
                             the miniature are blury. Did search for the fix but only found the "uncheck the Fliter box
                             and reimport for 2d pixel" solution but it didn't work. What can I do to solve that?
                             Will the new projects look like that if I don't fix it? I'm droping screeshots from the 
                             Assets Library and the Multiplayer Pong Asset.

![Screenshot (300)](https://user-images.githubusercontent.com/99998898/156867267-cd46c4e8-f681-4fdd-acbc-0bcde1229861.png)
![Screenshot (298)](https://user-images.githubusercontent.com/99998898/156867269-9accd143-8001-402d-ad7c-68437749badc.png)

**Comment by Calinou** [comment] 2022-03-05 18:34
Duplicate of https://github.com/godotengine/godot/issues/55343.

**Closed by Calinou** 2022-03-05 18:34 UTC
Labels: bug

**Comment by SvOTM** [comment] 2022-03-06 00:08
I tried it on another machine with better grapichs (Geforce8400 GS 1gb; Intel dual core 2.7; 3b RAM)
and it throws another Error. This time it says: 
![Error de godot](https://user-images.githubusercontent.com/99998898/156903784-2822b92b-0aa2-4f44-b4b3-724d9c41b7ea.png)

What could be the problem now? 
That pc has Openlg 3.3, if it has something to do with it.

**Comment by Calinou** [comment] 2022-03-06 00:16
> I tried it on another machine with better grapichs (Geforce8400 GS 1gb; Intel dual core 2.7ghz; 3gb RAM)

GeForce 8/9 series GPUs don't support the GLES3 renderer, so you need to switch to GLES2. You can do so in the project creation dialog, or for existing projects, open them in a [command prompt](https://docs.godotengine.org/en/stable/getting_started/editor/command_line_tutorial.html) with the `--video-driver GLES2` option.

**Comment by SvOTM** [comment] 2022-03-06 01:39
> You can do so in the project creation dialog
How do i do that? o.o

I mean. Can actually use Godot with my GeForce 8 series GPU or get a better one?

**Comment by Zireael07** [comment] 2022-03-06 09:13
In the Project Manager, when creating a project, you have a choice of GLES 3 or GLES 2.

**Comment by Calinou** [comment] 2022-03-06 16:27
![image](https://user-images.githubusercontent.com/180032/156932120-79290743-24a3-4350-bdf6-6b13e15b1c16.png)
