### ISSUE TITLE
making RigidBody2D::_integrate_forces editable in code

### ISSUE THREAD

**Issue by IllusiveS** [godotengine/godot#7779] opened 2017-02-10 22:59 UTC
**Operating system or device - Godot version:**
2.1.2, mint

So i was trying to learn c++ in godot by making in it simple top-down car physics, some investigation lead me to finding `_integrate_forces` within RigidBody2D in gdscript, so after diving down in c++ i found something that i am not sure how to workaround.  
It seems that `_integrate_forces` is being called from non virtual function `_direct_state_changed` and is bind as VMETHOD (i assume its virtual), using `BIND_VMETHOD(MethodInfo("_integrate_forces",PropertyInfo(Variant::OBJECT,"state:Physics2DDirectBodyState")));`  
Shouldn't there be a possibility of overriding `_integrate_forces` in c++?   
I think that would be a nice improvement and with some pointers from some more experienced C++ godot devs, i would gladly add that option.  
The simplest solution to that issue is making `_direct_state_changed` virtual and overriding it in child of RigidBody2D but it doesn't seem right.
I also hope that i did not misunderstood guidelines for contributing, since its my first time doing that in godot repo.

**Comment by Calinou** [comment] 2020-01-30 21:31
I'll close this, as this issue may not be relevant in Godot's current state (much has changed since Godot 3.0's release).

If you can reproduce this in Godot 3.2 and still have a need for this feature, please open a proposal on the [Godot Proposals](https://github.com/godotengine/godot-proposals) repository.

**Closed by Calinou** 2020-01-30 21:31 UTC
Labels: enhancement, topic:core
