### ISSUE TITLE
GodotSharp .NET binding lib isn't AOT compliant

### ISSUE THREAD

**Issue by joined72** [godotengine/godot#85518] opened 2023-11-29 17:59 UTC
### Godot version

4.2rc2

### System information

Linux Mint 21.2 (Ubuntu 20.04)

### Issue description

Trying to build my test C# project with the AOT compilation using the csproj `<PublishAOT>true</PublishAOT>` flag, will return error because the GodotSharp lib isn't AOT compliant

### Steps to reproduce

Create an empty Godot 4 C# project, add the csproj `<PublishAOT>true</PublishAOT>` flag and try to export it. 

### Minimal reproduction project

Take a look at the previous step.

**Comment by raulsntos** [comment] 2023-11-29 18:09
- This seems like a duplicate of https://github.com/godotengine/godot/issues/85476

**Closed** 2023-11-29 21:31 UTC
