### ISSUE TITLE
2DEditor: Zoom buttons move upper-left after creating new animation.

### ISSUE THREAD

**Issue by Naryosha** [godotengine/godot#23857] opened 2018-11-20 16:46 UTC
**Godot version:**

14cf450

**OS/device including version:**

Manjaro x86_64

**Issue description:**

![image](https://user-images.githubusercontent.com/43379543/48788471-7bb39000-ed1d-11e8-837a-d071b66b344e.png)
The green buttons are the original location and are visible when Onion skin is turned on.

**Steps to reproduce:**
1. New 2D scene
2. New AnimationPlayer
3. Select Animation tab
4. In Animation tab: Animation > New > [default name] > OK

**Comment by akien-mga** [comment] 2019-01-25 17:24
Seems fixed in the current master branch.

**Comment by akien-mga** [comment] 2019-02-08 10:44
Can you provide more detailed steps to reproduce? The ones in OP don't seem sufficient for me.

**Comment by Naryosha** [comment] 2019-02-08 14:28
Buttons move after creating new animation.

Full steps:
1. New 2D scene
2. New AnimationPlayer
3. Select Animation tab
4. In Animation tab: Animation > New > [default name] > OK

I'll update the original description. Also IMO this is only a minor issue. Moving it to later milestones should be fine.

**Comment by karliss** [comment] 2019-02-21 20:30
Reproduction steps are missing one step:
5. Enable onion skinning

**Comment by Naryosha** [comment] 2019-02-22 00:38
Buttons move regardless of onion skinning. (I think it's not supposed to move at all?) Enabling onion skinning simply makes the issue more apparent.

**Comment by YeldhamDev** [comment] 2019-05-14 04:05
@Naryosha Actually, having an animation and toggling onion skinning is enough to trigger the effect.

**Comment by akien-mga** [comment] 2020-01-09 08:54
Can't reproduce in the current master branch, and IIRC there were fixes to the onion skinning code, so they might have fix this bug.

**Closed by akien-mga** 2020-01-09 08:54 UTC
Labels: bug, topic:editor
