### ISSUE TITLE
Dragging a Node2d inside a CanvasLayer with scale != (1,1) results in a scaled dragging 

### ISSUE THREAD

**Issue by jhm-ciberman** [godotengine/godot#17715] opened 2018-03-23 07:57 UTC
**Godot version:** v3.0.2.stable.official

**OS/device including version:** Windows 10

**Issue description:**

When you drag a Node2d inside a CanvasLayer Node with a sacale different than (1,1) the movement of the child Node2D does not follow the mouse movement. 
If the scale of the CanvasLayer is for example (8, 8), and you drag 10 screen pixels the child Node2D, then the Node will be translated 80 screen pixels instead of 8 pixels (the nearest rouned number)
This is matematically correct but it's not intuitive nor facilitates the scene edition process. 

**Steps to reproduce:**
- Create a CanvasLayer Node
- Set their scale to (8, 8)
- Add any Node2D as a child (For example an AnimatedSprite) 
- Drag the Node2D about 10 pixels to the right. It will be tranlated 80 pixels. This is matematically correct but it's not intuitive nor facilitates the scene edition process. 

**Minimal reproduction project:** ---

**Comment by groud** [comment] 2018-03-23 10:34
I can't reproduce on master, It probably has been fixed already.

**Comment by groud** [comment] 2018-03-23 10:35
But it might be still valid on the 3.0 branch

**Comment by groud** [comment] 2018-09-19 16:42
Closing as probably fixed on master now.

**Closed by groud** 2018-09-19 16:42 UTC
Labels: bug, topic:editor, usability
