### ISSUE TITLE
Dragging any file into the editor after having just deleted a file, fails to import

### ISSUE THREAD

**Issue by ByTheQuietLake** [godotengine/godot#22984] opened 2018-10-13 13:05 UTC
**Godot version:**

fe0db6c

**OS/device including version:**

Win 7, Intel HD 4000

**Issue description:**

When you delete a file either in the editor or in the project directory and then try to drag and drop that file or any other file into the editor the import fails with the following error in console:

ERROR: DirAccess::copy: Failed to open Example/file/path
    At: core\os\dir_access.cpp:309

However, dragging a file into the project directory is unaffected by this issue.

**Steps to reproduce:**
1. Delete any file either through the editor or the project directory
2. Drag any file( doesn't have to be the same as the deleted) into the editor

**Comment by remorse107** [comment] 2018-10-15 23:28
I've also noticed that if you remove the name of the previously deleted from the text box just below the "FileSystem" tab that dropping the file will work again.  If that provides any clue to the fix.

**Comment by ByTheQuietLake** [comment] 2018-10-16 03:29
@remorse107 I don't see any text box below the FileSystem tab, could clarify with a pic please?

**Comment by Ashafix** [comment] 2018-10-16 15:55
I tried looking at the code which might cause this issue but I'm not 100% sure if I got the bug description right.
@ByTheQuietLake: What kind of files are you drag&droping? where are you droping them exactly?

**Comment by ByTheQuietLake** [comment] 2018-10-16 18:32
I have tried with a png file and also an ogg file. I dragged and dropped them into the FileSystem tab, irrespective of weather split mode for the filesystem tab is on or not, it behaves the same way. 

To be clear, when I say delete a file I mean any file, gdscript, png, ogg, tscn and then try to drag and drop an asset into the filesystem tab and it does nothing. However you can drag and drop it into your project directory without any issue, it is dragging into the editor after deleting any file that is a issue.

**Comment by ByTheQuietLake** [comment] 2018-10-18 05:33
@groud would this be under your domain?

**Comment by Calinou** [comment] 2018-11-08 16:50
This issue seems to be a duplicate of https://github.com/godotengine/godot/issues/22815, so I'll close it.

**Closed by Calinou** 2018-11-08 16:50 UTC
