### ISSUE TITLE
Editor crash when reverting Script Variables

### ISSUE THREAD

**Issue by Conferencier** [godotengine/godot#29853] opened 2019-06-17 17:49 UTC
**Godot version:**
v3.1.1.stable.official

**OS/device including version:**
Windows 10  64 bit (1803)

**Issue description:**
The Editor crashes if you try to revert Script Variables.

**Steps to reproduce:**
1) Select one of the "Story" nodes
2) Unfold the variable in the Inspector
3) Klick on the Revert button

![screenshot](https://user-images.githubusercontent.com/51924615/59624905-4991d180-9138-11e9-8886-0c7088abeebd.png)

**Minimal reproduction project:**
[RevertScriptVariablesCrash.zip](https://github.com/godotengine/godot/files/3298193/RevertScriptVariablesCrash.zip)

**Comment by qarmin** [comment] 2019-06-17 18:13
Backtrace
```
[1] /lib/x86_64-linux-gnu/libc.so.6(+0x43f60) [0x7fc67d4f9f60] (??:0)
[2] EditorProperty::get_minimum_size() const (/home/rafal/Pulpit/godot/editor/editor_inspector.cpp:74 (discriminator 3))
[3] Control::_update_minimum_size_cache() (/home/rafal/Pulpit/godot/scene/gui/control.cpp:173)
[4] Control::get_combined_minimum_size() const (/home/rafal/Pulpit/godot/scene/gui/control.cpp:193)
[5] Control::_update_minimum_size() (/home/rafal/Pulpit/godot/scene/gui/control.cpp:289)
[6] MethodBind0::call(Object*, Variant const**, int, Variant::CallError&) (/home/rafal/Pulpit/godot/./core/method_bind.gen.inc:61 (discriminator 4))
[7] Object::call(StringName const&, Variant const**, int, Variant::CallError&) (/home/rafal/Pulpit/godot/core/object.cpp:940 (discriminator 1))
[8] MessageQueue::_call_function(Object*, StringName const&, Variant const*, int, bool) (/home/rafal/Pulpit/godot/core/message_queue.cpp:256)
[9] MessageQueue::flush() (/home/rafal/Pulpit/godot/core/message_queue.cpp:305)
[10] SceneTree::iteration(float) (/home/rafal/Pulpit/godot/scene/main/scene_tree.cpp:481 (discriminator 2))
[11] Main::iteration() (/home/rafal/Pulpit/godot/main/main.cpp:1897)
[12] OS_X11::run() (/home/rafal/Pulpit/godot/platform/x11/os_x11.cpp:3163)
[13] godot(main+0xdc) [0x139699e] (/home/rafal/Pulpit/godot/platform/x11/godot_x11.cpp:56)
[14] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xeb) [0x7fc67d4dcb6b] (??:0)
[15] godot(_start+0x2a) [0x139680a] (??:?)
```

**Comment by KoBeWi** [comment] 2019-06-17 18:25
Duplicate of #28988

**Closed by KoBeWi** 2019-06-17 18:25 UTC
