### ISSUE TITLE
Text Editor Obstructed by Error Window

### ISSUE THREAD

**Issue by jaggygames** [godotengine/godot#25214] opened 2019-01-22 07:51 UTC
**Godot version:**
3.1 Beta 2

**OS/device including version:**
Windows 10

**Issue description:**
So I unfortunately named a function `get_class` in a previous build and while refactoring and updating my project for 3.1, I found the error shown to be so big it hid a large chunk of the editor. I love the feature but perhaps could be toned down a little bit for smaller resolutions. Or have it so it can be dismissed or minimised?

I couldn't find any options in the editor settings as I'm not sure what this window is called.

![error window](https://user-images.githubusercontent.com/3285214/51519797-9062f000-1e54-11e9-9d8e-ab45299a6e7d.gif)

**Steps to reproduce:**
Have an error in a script. Messing with `get_class `seems to produce a large window.

**Comment by akien-mga** [comment] 2019-01-22 08:01
Duplicate of #22302.

**Closed by akien-mga** 2019-01-22 08:01 UTC
