### ISSUE TITLE
one-liner Godot crash when printing odd characters on MacOS

### ISSUE THREAD

**Issue by Hunam6** [godotengine/godot#75902] opened 2023-04-10 16:59 UTC
<details>
<summary>Previous issue</summary>

### Godot version

v4.0.1.stable.official [cacf49999]

### System information

MacOS Ventura 13.2.1

### Issue description

Using `String.get_string_from_ascii` on specific string makes Godot crash.
Well, I'm not sure on which function makes Godot crash, my is that it's either `get_string_from_ascii` or `print`.

### Steps to reproduce

```gdscript
func _ready() -> void:
	print("simon".sha1_buffer().get_string_from_ascii())
```

### Minimal reproduction project

[very-very-minimal-example.zip](https://github.com/godotengine/godot/files/11192251/very-very-minimal-example.zip)

</details>

### Godot version

v4.0.2.stable.official [7a0977ce2]

### System information

MacOS Ventura 13.2.1

### Issue description

Printing odd characters on MacOS makes Godot crash. It doesn't seem to occur on Windows.

### Steps to reproduce

```gdscript
func _ready() -> void:
	print("\u001e A")
```

### Minimal reproduction project

N/A

**Comment by AThousandShips** [comment] 2023-04-10 17:04
`sha1_buffer` returns a string, not a `PackedByteArray`

**Comment by AThousandShips** [comment] 2023-04-10 17:07
The result of `sha1_buffer` isn't ASCII code but bytes

**Comment by Hunam6** [comment] 2023-04-10 18:18
@AThousandShips yes I noticed it before submitting the bug don't worry, but Godot shouldn't crash anyway

**Comment by AThousandShips** [comment] 2023-04-10 18:20
Then that should have been specified in the issue

**Comment by AThousandShips** [comment] 2023-04-10 18:26
I cannot replicate this on master, it just spits out unicode errors, can you replicate this on 4.0.2?

**Comment by AThousandShips** [comment] 2023-04-10 18:40
I can't replicate a crash on Windows 11 on 4.0.2, so probably related to incorrect handling of printing odd characters on MacOS rather than the core implementation

**Comment by Hunam6** [comment] 2023-04-10 19:02
I just compiled master, same.

Just tried printing what you suggested and it crashes, you spotted the bug perfectly!

**Comment by AThousandShips** [comment] 2023-04-10 20:27
To see if this is related to the console or to the engine itself can you please create a scene with a label and attach the following script:
```gdscript
extends Label

func _ready():
    text = "\u001e0"
```

If it doesn't crash we can narrow it down a bit

**Comment by Hunam6** [comment] 2023-04-10 21:58
I get a lot of non-very-helpful errors but no crash

<img width="580" alt="Screenshot 2023-04-11 at 00 57 53" src="https://user-images.githubusercontent.com/38606542/231006857-4f734fe7-ee92-463a-a3be-bf22aaeff320.png">

**Comment by Hunam6** [comment] 2023-04-10 22:00
I guess the error is already happening here, it should probably catch the error earlier and print something like "illegal character in a string"

**Comment by AThousandShips** [comment] 2023-04-11 04:51
This gives further evidence to what I suspect, that the crash is caused by the terminal in MacOS failing to handle this character

The errors are helpful actually though less than they could be, they're saying that the sequence is illegal unicode and that it can't be shaped, it isn't what's causing the crash though

**Comment by bruvzg** [comment] 2023-04-11 06:38
When the print with the invalid characters is added to the log, it's calling error print in the middle of the RTL update and overwrite the first print changes, so after returning to the first print its data is corrupted. Can be fixed by RTL multithreaded processing - https://github.com/godotengine/godot/pull/73812, but probably log prints should have some interlocking of its own.

**Closed** 2023-04-12 11:28 UTC
Labels: bug, topic:core, crash
