### ISSUE TITLE
Array/Dictionary variable shared between instances when using typed gdscript

### ISSUE THREAD

**Issue by pouleyKetchoupp** [godotengine/godot#24995] opened 2019-01-14 23:54 UTC
**Godot version:**
Master dev c23710adde23a0e415097dee7d8e6f9ba76a0970

**OS/device including version:**
Windows 10

**Issue description:**
When using typed gdscript and this syntax to add an Array or Dictionary variable to a custom class:
`var dict : Dictionary`
`var array: Array`
All the instances share the same container, instead of creating a new container for each one.
At least raising an error in the script would be fine, as it wouldn't result in bugs in script that are difficult to spot.

**Steps to reproduce:**
1. Add this script to your project:
```
extends Node

class test_class:
	var dict : Dictionary

var instance1
var instance2

func _ready():
	instance1 = test_class.new()
	instance1.dict[0] = 0
	
	instance2 = test_class.new()
	instance2.dict[1] = 1
	
	print("instance1:")
	for value in instance1.dict.values():
		print(value)
		
	print("instance2:")
	for value in instance2.dict.values():
		print(value)
```
2. Check the output:
```
instance1:
0
1
instance2:
0
1
```
**Expected result:**
Each instance of the class has a separate Dictionary/Array instead of all sharing the same container.
**OR**
Show an error message in the script editor.

**Comment by bojidar-bg** [comment] 2019-01-15 12:32
Duplicate of #24134 (which is badly-titled though).

**Closed by bojidar-bg** 2019-01-15 12:32 UTC
