### ISSUE TITLE
Corrupted control offset values (when animated) in non-focused scene

### ISSUE THREAD

**Issue by GreyDodger** [godotengine/godot#74991] opened 2023-03-16 17:27 UTC
### Godot version

4.0

### System information

Windows 10

### Issue description

related #69226

If...
* scene A has a control with an animation player animating its position (with a non-zero anchor)
* scene B is open in another editor tab and that is the current focused tab
* you start the game (or any trigger that resets the Scene A's control's animation player while it's not in the scene tree I think)

The control in scene A's position is corrupted. That control is trying to reset its position based on its parent rect but because it's not inside the tree anymore it can't retrieve its parent rect so it repositions it incorrectly. 

the temp fix is to make sure that scene is never open in another tab while working on any other scene which is a bit annoying.

### Steps to reproduce

create a project as described above (you may need to close/reopen godot before the issue reveals itself)

### Minimal reproduction project

[bug-control-position-corrupted-repro.zip](https://github.com/godotengine/godot/files/10993869/bug-control-position-corrupted-repro.zip)

**Comment by YuriSizov** [comment] 2023-03-16 18:13
Thanks for your report. This is a duplicate of https://github.com/godotengine/godot/issues/74047

**Closed** 2023-03-16 18:13 UTC
