### ISSUE TITLE
problems with "files newer on disk" dialog

### ISSUE THREAD

**Issue by FyiurAmron** [godotengine/godot#67452] opened 2022-10-15 16:08 UTC
### Godot version

4.0.x (up to at least beta3)

### System information

probably any (Windows 7/10 in this case)

### Issue description

This one is related to https://github.com/godotengine/godot/issues/65824 (and its dupes), so it concerns the same code as https://github.com/godotengine/godot/pull/66812 Basically, after having a file deleted outside of editor while also open in the editor, this comes up (as expected):
![image](https://user-images.githubusercontent.com/11016998/195995683-e7bf26c0-ef37-4470-826a-471e7be87a3e.png)

* "Resave" works as expected, if it's just a file that was deleted. If the file got deleted with the directory, this option doesn't work (although there isn't a real reason it shouldn't, since it can just recursively recreate the parent directory of the file), displaying 
![image](https://user-images.githubusercontent.com/11016998/195996432-bbed135f-f8da-43a9-8728-a8fa34633f7a.png)
instead.

* Selecting "Cancel" works as expected-ish - yet, arguably, the caption here should be "Ignore" and not "Cancel" (what are we cancelling? the action? the dialog? The semantic UX design rule is that you can only cancel an action you explicitly executed, because otherwise there ain't anything to cancel).

* Selecting "Reload" does nothing in this case, which makes little sense - if the file would be edited, this would reload the edited version from disk. In case of a deleted file, one would expect to see e.g. an empty file here, or have the editor script window closed (like Ctrl+W), since the file no longer exists. Also, I can see
```
ERROR: Error calling from signal 'confirmed' to callable: 'ScriptEditor::ScriptE
ditor::reload_scripts': Method expected 1 arguments, but called with 0..
   at: emit_signalp (core/object/object.cpp:1057)
```
in the console (same if the file was just edited outside, not deleted) - after I tried using "Reload" on an edited file, it instead re-saved it for some reason. (??)

* Also, the message itself is misleading - in case the file is missing, the message should just state that, by e.g. having the filenames decorated with " (Deleted)" or similar. Saying "the files are newer on disk" is highly misleading here, if all or some of the files in the list were deleted instead of edited, because something can't be "newer" if it doesn't exist.

* And finally, after selecting any of the options, this check is re-triggered every time the window gets focus again, even if I chose the "Reload" or "Cancel". This is extremely annoying, since there is no way to suppress this dialog from appearing either permanently or semi-permanently, other that re-saving the file (which is usually not what one wants in such situation) or manually closing the file via Ctrl+W (in which having to select any option in the dialog itself results in nothing, expect from extracting the lifespan of the game developer via having him to click on inconsequential buttons in dialog boxes :smile_cat: ).

### Steps to reproduce

1. create a script and open it in the Godot script edtior,
2. remove the script (with or without parent directory) outside of the editor,
3. do any of the actions described above.

**Comment by TechnicJelle** [comment] 2022-10-17 11:37
I'm having the same issue.
When I'm done with editing a script in Rider and go back to Godot to press Play, it gives me that same pop-up:
![image](https://user-images.githubusercontent.com/22576047/196167289-d90f71f2-4a9f-44c0-838a-965ec955e998.png)
And when I click `Reload`, it prints out this error and doesn't actually reload the script.
```diff
- core/object/object.cpp:1057 - Error calling from signal 'confirmed' to callable: 'ScriptEditor::ScriptEditor::reload_scripts': Method expected 1 arguments, but called with 0..
```
I'm currently working around it by restarting Godot completely after each edit, but even with how fast Godot is, that does get old, pretty quick..

**Comment by Calinou** [comment] 2022-10-17 12:11
Duplicate of https://github.com/godotengine/godot/issues/66644.

**Closed by Calinou** 2022-10-17 12:11 UTC
Labels: bug, topic:editor, needs testing
