### ISSUE TITLE
Icons of clickable button not being rendered in GUI

### ISSUE THREAD

**Issue by retr0cube** [godotengine/godot#64624] opened 2022-08-19 15:41 UTC
### Godot version

v3.5.stable.official [991bb6ac7]

### System information

Windows 10 Pro, GLES2, Mobile Intel(R) 4 Express Chipset Family (8.15.10.2413))

### Issue description

Hi! 
I've just installed Godot, but when i run it every clickable object has no icon, and when going to `Help -> About Godot` the logo is extremely blurred.

**Screenshots:**
![image](https://user-images.githubusercontent.com/61835816/185656074-e8e89279-b877-4459-8ffe-d9d7befbfe1a.png)
![image](https://user-images.githubusercontent.com/61835816/185656112-a9dcf1df-f187-4eb0-8fe8-978b9f3f2b18.png)

### Steps to reproduce

**_Install Godot -> Run it_**

**Comment by retr0cube** [comment] 2022-08-19 15:44
**_Maybe related:_**
![image](https://user-images.githubusercontent.com/61835816/185656721-6b4aafc1-3290-49ca-9419-dd45a1c8a770.png)

**Comment by Calinou** [comment] 2022-08-19 16:09
Duplicate of https://github.com/godotengine/godot/issues/55343.

**Closed by Calinou** 2022-08-19 16:09 UTC

**Comment by retr0cube** [comment] 2022-08-19 16:33
Thx @Calinou

**Comment by retr0cube** [comment] 2022-08-19 18:44
@Calinou  It doesn't work, trying to deploy it per app or system wide will not work!
