### ISSUE TITLE
Godot screen update problems after waking up from hibernation

### ISSUE THREAD

**Issue by Godot-Developer** [godotengine/godot#78391] opened 2023-06-18 09:05 UTC
### Godot version

v4.0.3.stable.official [5222a99f5]

### System information

Operating System: Manjaro Linux  KDE Plasma Version: 5.27.5 KDE Frameworks Version: 5.106.0 Qt Version: 5.15.9 Kernel Version: 6.3.5-2-MANJARO (64-bit) Graphics Platform: X11 Processors: 8 × Intel® Core™ i7-3630QM CPU @ 2.40GHz Memory: 11.6 GiB of RAM Graphics Processor: Mesa Intel® HD Graphics 4000 Manufacturer: Micro-Star International Co., Ltd. Product Name: GT70 System Version: REV:1.0 ========== VULKANINFO ==========  Vulkan Instance Version: 1.3.246 Graphics Card: GK 104M[GeForce GTX680M](Nvidia Corp)

### Issue description

There are some screen update problems with Godot after waking up from Hibernate.

Please check out the image I attached here.

Although I click on player scene (title of the main window is player.tscn), Mob.tscn is shown in the 3D view port. Also there seems to be no way to change the mob scene (which was up when I hibernated my machine).

I clicked on the different components of the Mob scene on the left, however Inspector was left totally empty no matter what I clicked.

I also tried to select a menu option (first menu option under Help menu) and you see the the pop up window titled "Search Help" came out empty (transparent). 

In another case, I had a dirty scene before hibernation. After waking up hibernation, I tried to discard changes. The pop up warning window also appeared empty (transparent). It looked emtpy, but I COULD click an invisible button (just made a rough guess where the button should have been), and managed to save my work and exit Godot application. 

If I restart the Godot suit, everything goes back to normal. 

![godotBug01](https://github.com/godotengine/godot/assets/136956933/3dc8f99e-5cf1-4b6d-8c87-1c3eef3eb926)

### Steps to reproduce

So simple. 

1. Start Godot suit. 
2. Open a project (I used the 3D tutorial squash the creeps project)
3. Create a new scene (but do not save it)
4. Hibernate the machine
5. Wake up from hibernation
6. Try a different scene other than one on the screen (observe the scene on the 3D viewport does not change)
7. Try to save the project by pressing CTRL + S ( it should ask you for a name for the new scene but observe that the pop-up comes empty)
8. Try to exit godot by pressing the X on the upper right corner (observe the pop-up that comes to warn to user about unsaved work appears empty)
 

### Minimal reproduction project

[godot-3d-dodge-the-creeps-master.zip](https://github.com/godotengine/godot/files/11781007/godot-3d-dodge-the-creeps-master.zip)

**Comment by AThousandShips** [comment] 2023-06-18 13:54
* See: #52738

Probably related, see [here](https://docs.godotengine.org/en/stable/about/troubleshooting.html#the-editor-project-freezes-or-displays-glitched-visuals-after-resuming-the-pc-from-suspend)

**Comment by Godot-Developer** [comment] 2023-06-18 14:26
I think you are right @AThousandShips . I actually searched the issue knowledge base before hand, but looks like I hadn't put the correct key words get a match. I only came across a few years old issue which was already closed.  My apologies for the redundancy and thank you for your response.

**Comment by AThousandShips** [comment] 2023-06-18 14:27
No problems! Does this resolve/answer your problem? If so we can close this as a duplicate

**Comment by Godot-Developer** [comment] 2023-06-19 06:01
I believe it is safe to close this issue as it has been discovered and documented earlier. Thanks so much.

**Comment by AThousandShips** [comment] 2023-06-19 06:26
Duplicate of #52738

**Closed by AThousandShips** 2023-06-19 06:26 UTC
Labels: bug, platform:linuxbsd, topic:editor
