### ISSUE TITLE
Godot 3.3.3-stable crashes on typing new func in vim with YouCompleteMe

### ISSUE THREAD

**Issue by AlbeyAmakiir** [godotengine/godot#52181] opened 2021-08-28 05:27 UTC
### Godot version

Godot_v3.3.3-stable_x11.64

### System information

openSUSE Leap 15.3 x86_64 (linux 5.3.18-59.19-preempt)

### Issue description

I edit my code in gVim using the language server. Connection is through YouCompleteMe. I write using GDScript only.

On some scripts, when I finish typing the signature of a function, Godot immediately crashes.

This does not happen under identical conditions but in Godot 3.3.2 stable. Only 3.3.3.

```
handle_crash: Program crashed with signal 11                                                                                                                                                                        [15:10:06]
Dumping the backtrace. Please include this when reporting the bug on https://github.com/godotengine/godot/issues
[1] /lib64/libc.so.6(+0x3a210) [0x7f71abe49210] (??:0)
[2] /home/albey/Software/Godot/Godot_v3.3.3-stable_x11.64() [0xe15f97] (??:0)
[3] /home/albey/Software/Godot/Godot_v3.3.3-stable_x11.64() [0x2f78a1a] (??:?)
[4] /home/albey/Software/Godot/Godot_v3.3.3-stable_x11.64() [0x2f288f5] (??:?)
[5] /home/albey/Software/Godot/Godot_v3.3.3-stable_x11.64() [0xe50446] (??:0)
[6] /home/albey/Software/Godot/Godot_v3.3.3-stable_x11.64() [0xe447b5] (??:0)
[7] /home/albey/Software/Godot/Godot_v3.3.3-stable_x11.64() [0x2f2cec1] (??:?)
[8] /home/albey/Software/Godot/Godot_v3.3.3-stable_x11.64() [0x2f2d90c] (??:?)
[9] /home/albey/Software/Godot/Godot_v3.3.3-stable_x11.64() [0x2f64a28] (??:?)
[10] /home/albey/Software/Godot/Godot_v3.3.3-stable_x11.64() [0x2f7fd1b] (??:?)
[11] /home/albey/Software/Godot/Godot_v3.3.3-stable_x11.64() [0xe142e4] (??:0)
[12] /home/albey/Software/Godot/Godot_v3.3.3-stable_x11.64() [0x1cda1ae] (??:0)
[13] /home/albey/Software/Godot/Godot_v3.3.3-stable_x11.64() [0x1ceb9c8] (??:0)
[14] /home/albey/Software/Godot/Godot_v3.3.3-stable_x11.64() [0x3119a3d] (??:?)
[15] /home/albey/Software/Godot/Godot_v3.3.3-stable_x11.64() [0x990dcd] (??:0)
[16] /lib64/libc.so.6(__libc_start_main+0xed) [0x7f71abe3434d] (??:0)
[17] /home/albey/Software/Godot/Godot_v3.3.3-stable_x11.64() [0x99f5ae] (??:0)
-- END OF BACKTRACE --
```

### Steps to reproduce

1. Install vim (with gvim)
2. Install the YouCompleteMe vim plugin (I did it with vim-plug), and set it to handle the Godot Language Server. These were my YCM-godot settings in my vimrc:
```
set completeopt=popup,menuone

if !has_key( g:, 'ycm_language_server' )
  let g:ycm_language_server = []
endif

let g:ycm_language_server += [
      \ {
      \   'name': 'godot',
      \   'filetypes': [ 'gdscript' ],
      \   'project_root_files': [ 'project.godot' ],
      \   'port': 6008
      \ }
      \]

let g:ycm_semantic_triggers =  {
  \   'gdscript': [':', '.']
  \ }
```
3. Set Godot to use gvim as its external editor. I called these exec flags: `--remote "+call cursor({line}, {col})" {file}`
4. Create a new script, and open it through Godot, so it opens in vim.
5. Start typing a new function: `func tester():`
6. Once the `:` is typed, Godot crashes after half a second.

### Minimal reproduction project

[Reproduce.zip](https://github.com/godotengine/godot/files/7070189/Reproduce.zip)

**Comment by Calinou** [comment] 2021-08-28 09:55
Duplicate of https://github.com/godotengine/godot/issues/51923.

**Closed by Calinou** 2021-08-28 09:55 UTC
