### ISSUE TITLE
Subsurface Scatter issues

### ISSUE THREAD

**Issue by djrm** [godotengine/godot#10696] opened 2017-08-27 19:17 UTC
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Fedora 26, bd282ff43f23fe845f29a3e25c8efc01bd65ffb0, Nvidia Proprietary driver 384.59

**Issue description:**

Enabling Subsurf scatter makes the screen white on old projects and does not seem to have effect on new projects on both cases spams the console with this message:
```
   At: drivers/gles3/rasterizer_gles3.cpp:122.
ERROR: _gl_debug_print: GL ERROR: Source: OpenGL	Type: Error	ID: 1282Severity: High	Message: GL_INVALID_OPERATION error generated. No active program.
```

This is on an old project, it used to be good, but now the SS causes the mentioned problem.
![peek 2017-08-27 13-56](https://user-images.githubusercontent.com/1103897/29753085-9d0cb4b2-8b2f-11e7-8720-538480f7e957.gif)

these are on new projects, created with the mentioned version.
![screenshot from 2017-08-27 14-06-40](https://user-images.githubusercontent.com/1103897/29753225-31738a3e-8b32-11e7-8325-d7663dab973c.png)
![screenshot from 2017-08-27 14-14-09](https://user-images.githubusercontent.com/1103897/29753226-31959840-8b32-11e7-80ee-eea00f3a357d.png)

**Steps to reproduce:**
Just set a SS on a material, by default you will get this
![screenshot from 2017-08-27 14-06-40](https://user-images.githubusercontent.com/1103897/29753165-f7ceda1e-8b30-11e7-951e-a77e63b2388d.png)
notice the weird white lines at the center

**Link to minimal example project:**

**Comment by gamergamesz** [comment] 2017-08-28 04:03
#9530 latest comment and pics

**Comment by djrm** [comment] 2017-08-28 04:13
@gamergamesz i know but your issue was closed, also it is not good if an issue evolves into another one, so opening other issue is better.

**Comment by gamergamesz** [comment] 2017-08-28 04:28
well i also faced some issue  like white screen when follow surface is on and on high value and high option it is showing same cross error and i posted latest pics after closing of the issue so probably it's worth looking at it since it is sss issue

**Comment by groud** [comment] 2017-08-28 16:54
According to #10728, this is here since "reduz's subsurf scatter fixes in b3ff7ca "

**Comment by reduz** [comment] 2017-09-05 23:51
I just can't reproduce, please attach a project where you see this failing

**Comment by gamergamesz** [comment] 2017-09-06 14:31
[sss.zip](https://github.com/godotengine/godot/files/1281431/sss.zip)
From my side turning off "follow shape" will remove white screen

**Closed** 2017-09-07 00:46 UTC
Labels: bug, topic:rendering
