### ISSUE TITLE
Vulkan: Lingering Ambient Occlusion masks appear when enabling Camera3D preview in the editor

### ISSUE THREAD

**Issue by nonunknown** [godotengine/godot#49545] opened 2021-06-12 23:12 UTC
### Godot version

v4.0.dev.custom_build.0c7cb9878

### System information

Manjaro Gnome, AMD R7 200

### Issue description

Even using a little "old" commit, I can confirm this happening on newer ones.

![image](https://user-images.githubusercontent.com/58845030/121790775-44e24580-cbb9-11eb-9c7e-d9b87e19dccd.png)

As you can see, its perfectly visible on the top (the free cam of the editor) the ambient occlusion (at least I think it is) from the Camera3D's preview from bellow.

### Steps to reproduce

* Create a new scene
* Add world environment (with HDRI sky)
* Add Camera3D
* turn your layout into two views (side by side or any other)
* in one of them use as camera3d's preview

### Minimal reproduction project

[FPS-Demo.zip](https://github.com/godotengine/godot/files/6643006/FPS-Demo.zip)

**Comment by Calinou** [comment] 2021-06-12 23:19
I've been able to reproduce this since the new SSAO was merged in December 2020. It mainly happens while in the editor, and can sometimes be triggered by resizing the viewport or window.

**Comment by clayjohn** [comment] 2021-06-13 17:18
I think I know what is going on. The SSAO attempts to cache uniform sets between frames, but the uniform set is saved globally rather than per viewport. I'll fix this and make a PR soon.

**Closed** 2021-06-14 17:05 UTC
Labels: bug, confirmed, regression, topic:3d, topic:editor, topic:rendering
