### ISSUE TITLE
Key icon for animation player not displaying

### ISSUE THREAD

**Issue by malkav182** [godotengine/godot#37855] opened 2020-04-13 19:34 UTC
**Godot version:**
Godot V3.2

**OS/device including version:**
Ubuntu 19.10 eoan

**Issue description:**
The key icon from the animation player is not displaying in other nodes (only displays the icon in the animation player node properties itself). It only displays if you close the animation menu and open it again. Pretty much similar to https://github.com/godotengine/godot/issues/18929 case.

**Steps to reproduce:**
1) add an animation player.
2) add a property track, like a sprite position.
3) click in the other node (this example, the sprite node). None of its properties will display the key icon
4). close the animation player menu and open it again.
5) check the other node again. It will display the key icon.

**Minimal reproduction project:**
https://github.com/malkav182/cute_brick

**Comment by Calinou** [comment] 2020-04-13 20:02
cc @guilhermefelipecgs, as they fixed it last time the bug appeared.

**Comment by guilhermefelipecgs** [comment] 2020-04-13 20:49
Looks good in v3.2.1
![Peek 2020-04-13 17-46](https://user-images.githubusercontent.com/1387165/79159685-e7811780-7dae-11ea-89d5-1c48a3622eee.gif)

**Comment by DocGabrielGamma** [comment] 2020-11-07 10:17
Greetings i can still reproduce this error in 3.2.3 stable in steam
![2020-11-07](https://user-images.githubusercontent.com/49282387/98438479-6d193b80-20e2-11eb-9f17-1ff23eb64357.png)

**Comment by YeldhamDev** [comment] 2021-08-08 23:22
I'm quite sure that this happens because of the texture region editor overriding the animation one, a bigger problem that has a lot of issues opened about it already (e.g. #28341). So I will just be closing this.

**Closed by YeldhamDev** 2021-08-08 23:22 UTC
Labels: bug, topic:editor
