### ISSUE TITLE
[C#] _Notification has a int param while all Notification consts are long

### ISSUE THREAD

**Issue by AndreSacilotto** [godotengine/godot#73111] opened 2023-02-11 18:14 UTC
### Godot version

4.0.RC1

### System information

Windows

### Issue description

The _Notification func as the follow signature:
```cs
public override void _Notification(int what) {}
```

And all Notification const like `NotificationReady`/`NotificationDragBegin` are long type.
```cs
public const long NotificationApplicationFocusOut = 2017L;
```
You can cast `long` to `int`, but I don't see a reason to things be like this.

Would have more sense to Notifications consts to be all int (since there not enough of them to justify the long type)

### Steps to reproduce

Try calling _Notification with a Notication const like: `_Notification(NotificationReady);`

Or use as case switch inside the _Notification virtual method.

### Minimal reproduction project

Not necessary

**Comment by YuriSizov** [comment] 2023-02-11 18:19
Duplicate of https://github.com/godotengine/godot/issues/66460.

**Closed by YuriSizov** 2023-02-11 18:19 UTC
