### ISSUE TITLE
CanvasLayer doesn't work correctly in Mobile and Forward+ modes.

### ISSUE THREAD

**Issue by GradienIsBored** [godotengine/godot#77607] opened 2023-05-29 10:41 UTC
### Godot version

4.0.3

### System information

-OS: Windows 10
-Rendering method: Mobile, Forward+

### Issue description

The CanvasLayer node doesn't draw anything other than text relative to screen coords like HUD elements, instead anything other than text moves away from the camera. This happens when the rendering mode is set to Mobile or Forward+, but the issue doesn't persist when the rendering mode is set to Compatibility. I made sure that follow viewport is off, and also tried making the CanvasLayer a child of the player, then a child of the Camera, none seemed to work.

### Steps to reproduce

1. Create a basic player controller.
2. Add a Camera2D node as a child of the player.
3. Add a CanvasLayer node as a sibling of the player.
4. Add a Button node as a child of the CanvasLayer.
5. Add text to the button.

### Minimal reproduction project

1. Create a basic player controller.
2. Add a Camera2D node as a child of the player.
3. Add a CanvasLayer node as a sibling of the player.
4. Add a Button node as a child of the CanvasLayer.
5. Add text to the button.

**Comment by arkology** [comment] 2023-05-29 11:50
https://github.com/godotengine/godot/issues/58314

**Comment by Calinou** [comment] 2023-05-29 14:51
- Duplicate of https://github.com/godotengine/godot/issues/58314.

**Closed by Calinou** 2023-05-29 14:51 UTC
