### ISSUE TITLE
Built-in Scripts cannot instance user-defined resources.

### ISSUE THREAD

**Issue by MoleMage** [godotengine/godot#66123] opened 2022-09-19 17:00 UTC
### Godot version

4.0 beta 1

### System information

Windows 10 Pro version 21H1

### Issue description

When using built-in scripts, classes defined in other scripts using **class_name** cannot be called with the .new() function, preventing built-in scripts from creating new instances of those scripts.

> Invalid call. Nonexistent function 'new' in base 'GDScript'.

This issue does not occur on non-built-in scripts.

### Steps to reproduce

In an empty project, create a new GDScript named "MyCustomResource.gd"

```
#"res://MyCustomResource.gd"
class_name MyCustomResource extends Resource

```

Create a new scene with (assumed) any root node (tested with Node, Node2D, Control, and Node3D with identical results). Attach the following built-in script to the root node. The code example is for a Control node:

```
#"res://control.tscn"
extends Control

var myCustomResource : MyCustomResource

func _ready():
	myCustomResource = MyCustomResource.new()
```

Attempt to run the scene using Play Scene in the editor and it will throw the error "Invalid call. Nonexistent function 'new' in base 'GDScript'."

### Minimal reproduction project

[New Game Project.zip](https://github.com/godotengine/godot/files/9600886/New.Game.Project.zip)

**Comment by Chaosus** [comment] 2022-09-19 19:29
Does it work correctly on 3.x?

**Comment by MoleMage** [comment] 2022-09-19 20:56
> Does it work correctly on 3.x?

I just followed the same instructions on `v3.4.4.stable.mono.official [419e713a2]` and yes, it's working as intended on that release. The MyCustomResource is created properly, no error message is thrown, and the myCustomResource variable is filled with an instance of MyCustomResource in the remote inspector when the scene is run.

**Comment by vpellen** [comment] 2022-10-16 18:24
Still an issue in Beta 3, wasted a good hour of my time. Appreciate the workaround.

**Comment by KoBeWi** [comment] 2022-10-25 15:43
Duplicate of #51538

**Closed by KoBeWi** 2022-10-25 15:43 UTC
Labels: bug, topic:gdscript
