### ISSUE TITLE
Mono 3.2.3 rc4 crash issue when exporting

### ISSUE THREAD

**Issue by qdwang** [godotengine/godot#41537] opened 2020-08-26 11:14 UTC
**Godot version:**

mono 3.2.3 rc4 from https://downloads.tuxfamily.org/godotengine/3.2.3/rc4/mono/

**OS/device including version:**

Windows 10 2004 GLES3

**Issue description:**

The project runs fine in Godot editor but the whole Godot editor will crash when exporting a windows exe file.

**Steps to reproduce:**
1. New a project.
2. Add a scene.
3. Add a C# script to the scene.
4. Run the project with no problem.
5. Export by windows(runnable) scheme.
6. Crash without any error.

**Minimal reproduction project:**

[CrashTest.zip](https://github.com/godotengine/godot/files/5129429/CrashTest.zip)

**Comment by Calinou** [comment] 2020-08-26 12:38
Duplicate of https://github.com/godotengine/godot/issues/41444.

**Closed by Calinou** 2020-08-26 12:38 UTC
