### ISSUE TITLE
move() turns KinematicBody2D's scale from negative to positive

### ISSUE THREAD

**Issue by p4ngy4** [godotengine/godot#5929] opened 2016-07-27 03:13 UTC
on v2.1_beta_20160721_win64

If you use the move() function on a KinematicBody2D, and it's scale is set to negative, it's scale will become positive after moving.

```
extends KinematicBody2D

func _ready():
    set_scale(Vector2(-2,-2))
    print("before move: ",get_scale())
    move(Vector2(3,3))
    print("after move: ",get_scale())
```

This code should print:
before move: -2,-2
after move: 2,2

**Comment by akien-mga** [comment] 2016-07-27 05:52
Confirmed in the current master branch. It also seems to behave weirdly as the children that were inheriting the negative scale of their parents are still displayed as scaled negatively (e.g. a Sprite would be h- and v-flipped), but setting the scale anew seems to trigger weird mood swings...

**Comment by reduz** [comment] 2016-07-27 12:49
I don't think physics likes negative scaled shapes, so this is probably not a bug. I suggest you scale/flip the artwork instead

**Comment by p4ngy4** [comment] 2016-07-28 03:08
well I also want to flip a couple different hitboxes attached to the kinematicbody. Maybe change this to a feature request to allow negative scaled shapes in physics.

**Comment by Keyaku** [comment] 2016-07-30 17:01
Mine works fine; all I do is constantly scale very time it detects a change in direction (left-to-right and vice-versa).

**Comment by Sslaxx** [comment] 2016-07-31 20:40
@Keyaku - does this affect performance at all?

**Comment by Keyaku** [comment] 2016-07-31 20:50
@Sslaxx My project is in early stages, so the environment this piece of code is in hasn't that many things happening at once yet; that being said, I can see no performance loss (and I'm working on a Mac i5@1.6Ghz with Intel HD 3000).

**Comment by bruno-ortiz** [comment] 2017-03-21 01:50
Any news on this?

**Comment by reduz** [comment] 2017-03-21 02:09
Yes, do not set scale to negative, collision detection will not work
properly.
If you want to flip your sprite, flip the sprite, not the kinematicbody.

**Comment by bruno-ortiz** [comment] 2017-03-21 02:13
At least can i set the rotation of a shape? I have a polygonShape2d that i want to rotate with the sprite.

**Comment by reduz** [comment] 2017-03-21 02:34
yeah, rotation is fine, just scale won't work

**Comment by Keyaku** [comment] 2017-03-21 08:20
Forgot to give an update on this: Just like @reduz said, use sprite flipping.

**Comment by akien-mga** [comment] 2017-08-08 11:40
As mentioned above, this is not a bug but a limitation of physics bodies, so closing.

**Closed by akien-mga** 2017-08-08 11:40 UTC
Labels: confirmed, topic:core

**Comment by fabriceci** [comment] 2019-10-21 19:59
I faced the same issue today, It would be nice if in some way this property is disabled for those kind of node (or at least a warning display if we tried to use it)

**Comment by Sslaxx** [comment] 2019-10-21 20:21
@fabriceci - With 2.1.x or 3.1.x or a latest Git build of 3.2? If it's one of the 3.x series might be worth opening a new bug and referring to this one.

**Comment by fabriceci** [comment] 2019-10-21 21:25
@Sslaxx It's on the 3.2 alpha 2. I will open a new issue.

**Comment by Muller-Castro** [comment] 2019-12-26 19:56
I had the same issue here... I've just set `scale.x = -1.0` and called `move_and_slide` and it ended up flipping the Y axis and the rotation went from 0 to -180

![image](https://user-images.githubusercontent.com/37383316/71488547-e1672b00-27ff-11ea-8d3f-c4b74e79bcbc.png)

**Comment by chucklepie** [comment] 2020-09-20 22:35
Honestly, what a complete and utter waste of time spending hours trying to figure out why weird things are happening.

How do you expect a node with a dozen child nodes, including ray casts, collision boxes, area2d, etc to reverse it? it's just just a case of flipping the image...

**Comment by Calinou** [comment] 2020-09-20 22:59
@chucklepie We know physics issues are frustrating, but please don't bump issues out of frustration.
