### ISSUE TITLE
Add a CanvasItemMaterial with mode to light only to a Sprite2D does not work

### ISSUE THREAD

**Issue by Datoh** [godotengine/godot#67804] opened 2022-10-23 15:12 UTC
### Godot version

4.0-beta3

### System information

Windows 11

### Issue description

Hi,

I have a PointLight2D, I want a Sprite2D disapears if not in light range. So I added a CanvasItemMaterial with mode to light only to the sprite. But it does not work.

I joined a minimal project reproduction.

Regards.

### Steps to reproduce

1. Launch the reproduction project
2. Move the player with arrows
3. Enemy Sprite2D should appears when is in light range

### Minimal reproduction project

[TestLight2D.zip](https://github.com/godotengine/godot/files/9846860/TestLight2D.zip)

**Comment by Calinou** [comment] 2022-10-23 17:14
Duplicate of https://github.com/godotengine/godot/issues/49909.

**Closed by Calinou** 2022-10-23 17:14 UTC
