### ISSUE TITLE
In any text field, when text is selected (highlighted), pressing left/right doesn't move the caret to the beginning/end of selection

### ISSUE THREAD

**Issue by hsandt** [godotengine/godot#50374] opened 2021-07-11 17:24 UTC
### Godot version

3.3.2.stable.official

### System information

Linux Ubuntu 18.04 under Unity desktop

### Issue description

In any text field, when selecting (highlighting) a text, pressing left/right with the keyboard does not send the caret to the beginning/end of selected text, as in other text editor apps. This could be by design, in which case I will convert this bug report to a suggestion to change the caret move behavior when text is selected. If you think the current behavior is also good, then for retrocompatibility you could add an option in Editor Settings > Text Editor > Cursor to apply the behavior seen in other apps.

In the rest of this description, I'll assume this is a bug.

More details on a case-by-case basis:

* In small, one-line text fields like the Asset rename popup, the Find panel, the Find in Files pop-up, double-clicking on a word with highlight the word, but keep the caret position on the clicked position. Pressing Ctrl+A to Select All will not move the caret at all. Then, pressing left/right will simply move the caret to the left or right of the confirmed position.
* In a big text field like the Code Editor, double-click of Select All will move the caret to the end of the selection. Therefore, pressing right will move the caret to the end of the selection as expected. However, pressing left will move the character to the penultimate character, instead of the beginning of the selection.

The difference may come from LineEdit vs TextEdit behavior.

In addition, one-line text fields have different behaviors regarding caret position initialisation:
* Asset rename popup selects the basename automatically (without extension) and place the caret at the beginning
* Find in Files (while selecting code in the editor) select all characters and place the caret at the beginning
* Find (while selecting code in the editor) select all characters and place the caret at the end

This means that some cases make it easier to move the caret to the beginning, others make it easier to move it to the end.

A concrete example (how I actually found the bug) is when you double-click on a word to search it, press Ctrl+Shift+F to Find in Files, want to add a suffix (such as '(' to make sure you're dealing with a function definition or call) by pressing right, and notice the caret just moved to the 2nd character.

Workaround:
You need to remember not to rely on current selection and use either Ctrl+Left/Right (for word navigation) or Home/End (for line navigation) or Ctrl+Home/End (for full text navigation) instead of Left/Right to move the caret where you want to (if your selection is across words and lines, then there may not be a good shortcut to do what you want; although I'm more concerned about the 99% cases of selecting a word to Find).

### Steps to reproduce

1. In the Code Editor, select a word or expression. Press Ctrl+Shift+F / Find in Files
2. Press Right with the intention of adding something at the end of the string
3. Notice that caret is only on the 2nd character now

Variants:
A. Rename an asset, and press right trying to go to the end
B. Select text in Code Editor, press Ctrl+F / Find and then press left trying to go the beginning

**Comment by Calinou** [comment] 2021-07-11 18:05
cc @Paulb23

**Comment by KoBeWi** [comment] 2021-07-11 22:37
Wasn't there a PR fixing this? 🤔

**Comment by Paulb23** [comment] 2021-07-12 17:37
Not a PR, but duplicate of a proposal: godotengine/godot-proposals/issues/1607.

**Closed by Paulb23** 2021-07-12 17:37 UTC
Labels: bug, topic:gui, usability
