### ISSUE TITLE
The right part of the ui gets pushed off screen whenever a script gets opened

### ISSUE THREAD

**Issue by dryluggage** [godotengine/godot#41392] opened 2020-08-20 11:19 UTC
os : Linux Mint 20 Ulyana
godot version 3.2.2

steps to rep : open godot , make a node , attach a script , click on the script.
![vokoscreen-2020-08-20_12-56-56](https://user-images.githubusercontent.com/58333865/90762316-21c26e80-e2e5-11ea-84bf-4bb6c4b7c9d5.gif)

doesnt need example project

when the godot is not in fullscreenmode then you cant turn it back by going into fullscreen mode and back

**Comment by bojidar-bg** [comment] 2020-08-20 12:01
Duplicate of #31133, esp https://github.com/godotengine/godot/issues/31133#issuecomment-562565593.

**Closed by bojidar-bg** 2020-08-20 12:01 UTC
