### ISSUE TITLE
Vulkan: Bouncy Particles and YVelocity Billboard Extreme Spinning

### ISSUE THREAD

**Issue by ccuntd** [godotengine/godot#57197] opened 2022-01-25 14:26 UTC
### Godot version

v4.0.alpha.custom_build [310266051]

### System information

Linux, Vulkan

### Issue description

When having YVelocity Billboard, the particles go extremely spinny (i like that they get a new rotation on each time they hit the floor, but it seems to cause the extreme spinniness when they keep re-hitting the floor)

### Steps to reproduce

Get particles with YVelocity Billobard make them collide and Bouncy Enough.

### Minimal reproduction project

[BRPAC.zip](https://github.com/godotengine/godot/files/7934285/BRPAC.zip)

**Comment by Calinou** [comment] 2022-01-25 14:45
This should probably be fixed by adding a property that limits the maximum amount of rotation per frame, effectively making rotations happen with some delay.

As a workaround, only rely on velocity-based rotation change for fast-moving particles that don't slow down significantly.

**Comment by ccuntd** [comment] 2022-01-26 11:13
a bounce threshold would also be nice, lets say its .01 bouncy, all you would see at that would be a horribly bobbing particle
so how about setting the bouncy of the particle to 0 if its under .01 or so

**Comment by Calinou** [comment] 2022-05-21 11:07
Duplicate of https://github.com/godotengine/godot/issues/57249 (same cause, as this is also fixed by https://github.com/godotengine/godot/pull/61245).

**Closed by Calinou** 2022-05-21 11:07 UTC
Labels: enhancement, topic:rendering, confirmed
