### ISSUE TITLE
Dragging an image resource into a 2D scene crashes the editor immediately

### ISSUE THREAD

**Issue by zhehangd** [godotengine/godot#89272] opened 2024-03-08 06:22 UTC
### Tested versions

Godot v4.3.dev4. No such issue with Godot v4.1.1.stable. 

### System information

Ubuntu 23.04 23.04 - X11 - Vulkan (Forward+) 

### Issue description

Dragging an image resource (Image, not Texture2D) from the file system dock into a 2D scene crashes the editor immediately.

![Screenshot_20240308_140259](https://github.com/godotengine/godot/assets/9572364/c3fdef99-3e4a-4dfc-aabb-acdf1534067b)

In terminal I saw an error on crash

```text
ERROR: Index p_index = 0 is out of bounds ((int)data.children_cache.size() = 0).
   at: get_child (scene/main/node.cpp:1608)
```

Note: I have no intention to drop an image into a scene, I was dragging it to the inspector and the mouse was just passing though.

### Steps to reproduce

1. Create an image in the project directory.
2. Reimport the image as Image.
3. Drag the image from the file system dock to a 2D scene.
4. Crash

### Minimal reproduction project (MRP)

[dragging_image_crash.zip](https://github.com/godotengine/godot/files/14534078/dragging_image_crash.zip)

**Comment by timothyqiu** [comment] 2024-03-08 06:49
I can't reproduce this on the current master. This should already fixed by #89126 :)

**Closed by timothyqiu** 2024-03-08 06:49 UTC
