### ISSUE TITLE
Gamewindow closes when you call popup after freeing all of the windowdialog children

### ISSUE THREAD

**Issue by dryluggage** [godotengine/godot#35433] opened 2020-01-22 13:14 UTC
**Godot version:**
3.1.2
**OS/device including version:**
Linux Mint 19.3
**Issue description:**
when repeatedly pressing a button that is connected to a function that uses queue_free on all of the windowdialog children (even itself) then tells the windowdialog to popup()
gamewindow closes and there is no errormessage it just says "debug process ended"

it might not be a bug but there is no errormessage so i wasnt sure

**Steps to reproduce:**
Make a new empty scene add an "control" node add an "windowdialog node" as a child to the "control"
and add a "button" as a child to the "windowdialog" and add a script to the "control" node and then connect the "pressed" signal from the "button" to the "control" node
and paste this code in the "control" script:
```

func _ready():
	$WindowDialog.popup()

func clean_window():
	for i in $WindowDialog.get_children():
		i.queue_free()

func _on_Button_pressed():
	
	clean_window()
	$WindowDialog.popup()
	
	var button = Button.new()
	$WindowDialog.add_child(button)
	button.connect("pressed",self,"_on_Button_pressed")

```

then run the scene and repeatetly click the button and then the Gamewindow should close

**Minimal reproduction project:**

[test.tar.gz](https://github.com/godotengine/godot/files/4097402/test.tar.gz)

**Comment by Faless** [comment] 2020-01-22 13:30
This happens because you are freeing elements needed by the WindowDialog to work (e.g. the `X` close button in the top).
You might want to use a control for the content of the window, and delete that control or it's children, not all the children of WindowDialog.

**Comment by KoBeWi** [comment] 2020-01-28 19:33
Duplicate of #21458

**Closed by KoBeWi** 2020-01-28 19:33 UTC
