### ISSUE TITLE
Failed to the click resource in editor

### ISSUE THREAD

**Issue by 1419427247** [godotengine/godot#67448] opened 2022-10-15 14:00 UTC
### Godot version

v4.0.beta2.official [f8745f2f7]

### System information

Win10

### Issue description

Errors will be reported if my customized resources are added to the editor

### Steps to reproduce

```
class_name Weapon extends Resource

@export
var damage : int = 0

@export
var range : int = 1
```
I added it to the new script
```
@export
var weapon : Weapon = null
```

![image](https://user-images.githubusercontent.com/33598732/195990367-a60610e1-9f51-4b87-b933-2c2f6bd29eff.png)
console output:
Failed to set a resource of the type 'Resource' because this EditorResourcePicker only accepts 'Weapon' and its derivatives.

**Comment by kleonc** [comment] 2022-10-15 15:43
Seems like it's caused by the global class cache not being updated properly.

1. Adding script as in "Steps to reproduce" results in the mentioned error.
2. After restarting the editor the errors go away.
3. Then after adding another class like `class_name SubWeapon extends Weapon` such class is not available from the EditorResourcePicker's popup menu:
![Godot_v4 0-beta3_win64_kIq172IPpX](https://user-images.githubusercontent.com/9283098/195995281-c7443446-7681-467d-bdb7-ec2fa2cc6ecf.png)
4. After restarting the editor it works properly:
![EaIj3PdmpF](https://user-images.githubusercontent.com/9283098/195995317-c7849863-2b8f-4763-be87-c389e6dcd00e.png)
5. Then after removing such `SubWeapon` class it still shows it in the EditorResourcePicker's popup menu:
![EaIj3PdmpF](https://user-images.githubusercontent.com/9283098/195995317-c7849863-2b8f-4763-be87-c389e6dcd00e.png)
6. After restarting the editor it's updated properly again:
![Godot_v4 0-beta3_win64_kIq172IPpX](https://user-images.githubusercontent.com/9283098/195995281-c7443446-7681-467d-bdb7-ec2fa2cc6ecf.png)

**Comment by 1419427247** [comment] 2022-10-16 12:12
> 

This bug will no longer appear in v4.0. beta3. official [01ae26d31]. Good o (* ￣ ▽￣ *) o

**Comment by kleonc** [comment] 2022-10-16 13:03
> > 
> 
> This bug will no longer appear in v4.0. beta3. official [[01ae26d](https://github.com/godotengine/godot/commit/01ae26d31befb6679ecd92cd3c73aa5a76162e95)]. Good o (* ￣ ▽￣ *) o

It does happen, my previous comment is based on the testing done in v4.0.beta3.official [01ae26d31].

**Comment by RedMser** [comment] 2022-10-16 19:23
This seems to be a duplicate of #66862

**Comment by kleonc** [comment] 2022-10-16 20:52
Indeed, duplicate of #66862. Thanks @RedMser!

**Closed by kleonc** 2022-10-16 20:52 UTC
Labels: bug, topic:gdscript, topic:editor, confirmed
