### ISSUE TITLE
Inputs getting stuck enabled

### ISSUE THREAD

**Issue by sodium-chloride** [godotengine/godot#33468] opened 2019-11-09 01:20 UTC
Godot version 3.1.1-stable mono

Ubuntu 18.04

When quickly pressing and releasing keys used as inputs to control a character sometimes when I let go the character continues to move due to the inputs still being enabled even though I have released the key(s).

Create a 2D scene
Add a simple movement system such as the one I used:

        bool LEFT = Input.IsActionPressed("ui_left");
        bool RIGHT = Input.IsActionPressed("ui_right");
        bool UP = Input.IsActionPressed("ui_up");
        bool DOWN = Input.IsActionPressed("ui_down");

        moveDirection.x = -Convert.ToInt32(LEFT) + Convert.ToInt32(RIGHT);
        moveDirection.y = -Convert.ToInt32(UP) + Convert.ToInt32(DOWN);

        Vector2 motion = moveDirection.Normalized() * speed;
        MoveAndSlide(motion, ZERO);

Then run the scene and quickly hit the movement keys until the character continues to move.

**Comment by Calinou** [comment] 2019-11-09 16:15
Duplicate of #27104.

**Closed by Calinou** 2019-11-09 16:15 UTC
