### ISSUE TITLE
There are always some minor errors on mobile

### ISSUE THREAD

**Issue by 451507056** [godotengine/godot#76409] opened 2023-04-24 18:08 UTC
### Godot version

4.0.2.stable

### System information

windows10，gtx1050ti

### Issue description

The mobile terminal always prompts some small errors, I don't know if I am the only one encountering this error.

### Steps to reproduce

Create a new mobile project, run the project, close it, and the console displays an error.
![QQ截图20230425015503](https://user-images.githubusercontent.com/6943500/234079775-69b9f2d6-2843-49b3-896b-1d9db40f8d74.png)
![QQ截图20230425015348](https://user-images.githubusercontent.com/6943500/234079794-7d90ae3e-ced4-47ae-83ac-51c061f6234a.png)

### Minimal reproduction project

[aaa.zip](https://github.com/godotengine/godot/files/11313331/aaa.zip)

**Comment by Calinou** [comment] 2023-04-24 22:47
- Duplicate of https://github.com/godotengine/godot/issues/67406.

**Closed by Calinou** 2023-04-24 22:47 UTC
Labels: bug, topic:rendering
