### ISSUE TITLE
Saving scene hangs on Creating Thumbnail on Wayland

### ISSUE THREAD

**Issue by UQuark** [godotengine/godot#79102] opened 2023-07-06 12:55 UTC
### Godot version

4.1 stable

### System information

Arch Linux 6.4.1-zen2-1-zen / GNOME @ Wayland

### Issue description

I downloaded a new 4.1 binary and imported my early-in-development 4.0 project into it.
Every time I attempt to save a scene, it hangs during the "Creating Thumbnail"
![Screenshot from 2023-07-06 15-37-09](https://github.com/godotengine/godot/assets/20577158/6b21ed8c-b6a1-4705-a59f-77a1b5e12662)
The UI becomes completely unresponsive and I have to pkill Godot every time
The issue persists even in a newly created project

P. S. The "Copy System Info" function also causes a hang, but I understand that might need a separate issue

### Steps to reproduce

1. Launch Godot 4.1 from official binaries
2. Create a new project
3. Try to save a scene
4. Observe the hang

### Minimal reproduction project

Any empty project

**Comment by UQuark** [comment] 2023-07-06 12:57
UPD: Tested 4.1 on Xorg, seems to be working

**Comment by Selenyhr** [comment] 2023-07-07 14:48
Also using Arch with Wayland + GNOME here. Using v4.1.stable.official [970459615].

The engine freezing issue seems to happen whenever a window opens up in the editor. Opening up a blank project and trying to access any of the contextual menu after any project has been loaded.
![image](https://github.com/godotengine/godot/assets/31015897/8f723f66-5e29-4a07-80e9-a786e88589a6)

Trying to alt-tab after the engine has frozen leaves the window in place. This is with Firefox in foreground:
![image](https://github.com/godotengine/godot/assets/31015897/6c950aed-1847-4f5f-af43-270229678192)

This doesn't seem to happen with the language selection on the launcher though, this window as well as the entire launcher pop-up windows work fine on my machine: 
![image](https://github.com/godotengine/godot/assets/31015897/de3dae62-bc03-40ea-95e0-7de3c895895e)

**Comment by akien-mga** [comment] 2023-07-07 14:53
- Duplicate of #78487

**Closed by akien-mga** 2023-07-07 14:53 UTC
Labels: bug, platform:linuxbsd, topic:porting
