### ISSUE TITLE
GDScript 2.0: `Array.size()` returning `null` with typed array hint

### ISSUE THREAD

**Issue by DrAlta** [godotengine/godot#62193] opened 2022-06-19 01:36 UTC
### Godot version

v4.0.alpha10.official [4bbe7f0b9]

### System information

Ubuntu 21.10

### Issue description

The size method on a typed array is returning null instead of the size of the array.

### Steps to reproduce

Create an enum.

Create a class with one of its properties typed as that enum, but not initialized to a value.

Create an array typed as that class.

Access that uninitialized value on one of the members of the array, like my_array[0].my_property.

Call the size method of the array.

I've included alternate versions that doesn't do one of those step, and in those cases it returns the correct size.

### Minimal reproduction project

[MRE.zip](https://github.com/godotengine/godot/files/8934597/MRE.zip)

**Comment by vonagam** [comment] 2023-01-20 17:20
Could not reproduce. Can you check if it still happens of fixed in last release?

**Comment by DrAlta** [comment] 2023-01-21 00:10
> Could not reproduce. Can you check if it still happens of fixed in last release?

The enum property has to uninitialized and the newer version of Godot initialize it automagically
```godot
enum Party {HAREM, NEUTRAL,  SAEVA}
var line : Array[Creature]
class Creature:
	var party : Party
func _ready() -> void:
	line.append(Creature.new())
	print("bar:", line[0].party)
	print("foo:",line.size())
```

on newer version, such as v4.0.beta10.official [d0398f62f], will print
```
bar:0
foo:1
```

while on v4.0.alpha10.official [4bbe7f0b9] it prints:
```
bar:null
foo:null
```

I don't know is automagically initializing values is the correct behavior, either; I think it's more of a design decision; Who's in charge of the design of GDscript 2.0

**Comment by vonagam** [comment] 2023-01-24 21:51
Enum is non-nullable type, so it was bug that `party` was null and maybe this what was causing the reported problem. Since now it seems values are initialized properly the issue is gone and can be closed.

**Comment by kleonc** [comment] 2023-01-24 22:02
Closing as fixed per https://github.com/godotengine/godot/issues/62193#issuecomment-1399091370 and https://github.com/godotengine/godot/issues/62193#issuecomment-1402738261.

**Closed by kleonc** 2023-01-24 22:02 UTC
Labels: bug, topic:gdscript
