### ISSUE TITLE
Jittery animation when blending an animation with another animation player track

### ISSUE THREAD

**Issue by MUTEDGALAXY** [godotengine/godot#56721] opened 2022-01-12 12:45 UTC
### Godot version

3.4.2.stable

### System information

Windows 11, RTX 2060, Core i9-10900KF, GLES3

### Issue description

Whenever i try to use Blend2/Add2 in AnimationTree with an animation that contains an Animation track, animation just flickers between "in" and "blend/add" animation.

![image](https://user-images.githubusercontent.com/53514993/149141987-379c1415-a524-4808-9292-f6e9b618fbe4.png)
![image](https://user-images.githubusercontent.com/53514993/149142028-1fa559bf-27c8-452d-9908-3f9a00ba96c5.png)

### Steps to reproduce

Select AnimationTree node in the repoduction project, then click on the little "Play" Button of a BlendTree node.
![image](https://user-images.githubusercontent.com/53514993/149142488-84d56951-cc7b-4b1a-8345-5fa0f75df77f.png)
![image](https://user-images.githubusercontent.com/53514993/149142497-f56180fa-fc98-4b04-ada1-6ef02f5b0f10.png)

### Minimal reproduction project

[Animation.zip](https://github.com/godotengine/godot/files/7854590/Animation.zip)

**Comment by TokageItLab** [comment] 2022-01-21 21:43
It is caused by track caches conflict, duplicate of #43848, and fixed by #56902.

**Closed** 2022-01-21 21:47 UTC
Labels: bug, topic:animation

**Comment by MUTEDGALAXY** [comment] 2022-01-23 02:02
> It is caused by track caches are incompatible/conflicted between PropertyTrack and BezierTrack. Duplicate of #43848, and fixed by #56902.
> 
> Still you need to match the paths between the 2 tracks, see [#49411 (comment)](https://github.com/godotengine/godot/pull/49411#issuecomment-858141010).

As you mentioned SkeletonRetarget works only in 3D, i don't really think that's the case but my problem relates to a Skeleton2D node, anyway, i already wrote a small bone merger thing, might upload it to asset lib later.

**Comment by TokageItLab** [comment] 2022-01-23 06:39
@MUTEDGALAXY That's PR include #49411, see description.
