### ISSUE TITLE
Naming an @export_group after built-in type causes godot to fail to recognize the type within the script.

### ISSUE THREAD

**Issue by Pyxus** [godotengine/godot#78493] opened 2023-06-20 22:18 UTC
### Godot version

4.0.3.stable

### System information

Windows 10 - Ryzen 7 2700 - GTX 1080ti - Vulkan (Forward+)

### Issue description

Godot will fail to recognize a built-in type in a script if that script contains an `@export_group` with the same name as the built-in type; the type will be treated as null if you attempt to use it.

This may relate to #78252 but I decided to post the issue since they're slightly different.

### Steps to reproduce

1. Attach the following script to a node:
```
extends Node

@export_group("Node")

func _ready():
   var node = Node.new()
```

2. Run the scene with this node and it should trigger an "Invalid call. Nonexistent function 'new' in base 'Nil'." error since the type `Node` is null.

### Minimal reproduction project

N/A

**Comment by dalexeev** [comment] 2023-06-21 04:12
* Duplicate of #73843.

**Closed** 2023-06-21 07:54 UTC
