### ISSUE TITLE
Godot 4.0 alpha 1 crashes when renaming/deleting Script that contains cyclic references

### ISSUE THREAD

**Issue by ThunderFD** [godotengine/godot#57191] opened 2022-01-25 13:07 UTC
### Godot version

v4.0.alpha1.official [31a7ddbf8]

### System information

macOS 12.1 (21C52) - MacBook Air (M1, 2020, 8GB)

### Issue description

Godot 4.0 alpha 1 crashes when renaming or deleting a Script that contains cyclic references.

It crashes only once the reference **to each other** are made via the print line in _ready:

Test1.gd:
```
extends Node3D

class_name TestName1

const test1 = 1

# Called when the node enters the scene tree for the first time.
func _ready():
	print(TestName2.test2)
```
Test2.gd:
```
extends Node3D

class_name TestName2

const test2 = 2

# Called when the node enters the scene tree for the first time.
func _ready():
	print(TestName1.test1)
```

### Steps to reproduce

Open the minimal reproduction project.

either:
1. rename Test2.gd to Test3.gd -> Godot crashes
2. delete Node1 and Node2 from the Scene, then rename Test2.gd to Test3.gd, and then back to Test2.gd -> Godot crashes
3. delete Test2.gd -> Godot crashes
4. delete Node1 and Node2 from the Scene, then delete Test2.gd -> Godot crashes

Opening the Project afterwards makes Godot crash immediately.

### Minimal reproduction project

[ScriptRenameCrash.zip](https://github.com/godotengine/godot/files/7933707/ScriptRenameCrash.zip)

**Comment by adamscott** [comment] 2022-10-29 20:36
Could not reproduce in Godot 4.0 beta 2.

**Comment by adamscott** [comment] 2023-01-07 18:56
@akien-mga I think we can close this issue. Tried summarily to reproduce on master (fcba87e) and couldn't.

**Closed** 2023-01-07 21:29 UTC
Labels: bug, topic:gdscript, topic:editor, crash
