### ISSUE TITLE
Feature request pan mode button

### ISSUE THREAD

**Issue by sami8github** [godotengine/godot#20846] opened 2018-08-09 13:08 UTC
**Godot version:**
v3.1.dev.calinou.1800664

**OS/device including version:**
windows 10 x64

**Issue description:**
In 2d view and visual script area :If there is a possibility to make pan with right mouse button instead of middle button or make option to change the button of pan.

**Comment by akien-mga** [comment] 2018-08-15 18:46
Duplicate of #8582.

**Closed by akien-mga** 2018-08-15 18:46 UTC
Labels: enhancement, topic:editor
