### ISSUE TITLE
Ctrl+left click on editor(jump to function or variable) sometimes not jump to token line in the same script

### ISSUE THREAD

**Issue by fian46** [godotengine/godot#33262] opened 2019-11-02 10:57 UTC
**Godot version:** 3.1.1 from website

**OS/device including version:** linux mint

**Issue description:** this only happened if the intended function is below the current function. This is also happened in declared variable in the same script.

**Steps to reproduce:**-

**Minimal reproduction project:**-

**Comment by KoBeWi** [comment] 2019-11-02 13:29
Duplicate of #20393

Fixed in 3.2

**Closed by KoBeWi** 2019-11-02 13:29 UTC
