### ISSUE TITLE
godot freeze

### ISSUE THREAD

**Issue by HacsonRED123** [godotengine/godot#17363] opened 2018-03-08 12:09 UTC
Whenever I launch godot mono version, the normal window pop up but it just stay there and nothing happen. This doesn't happen when I use the none mono version.

I'm using ubuntu 17.10, godot 3.0.2

If somebody could help that would be great

**Comment by hpvb** [comment] 2018-03-08 12:13
Do you know what version of Mono you have installed on your system? Currently the official binaries are only compatible with a local install of Mono 5.4

**Comment by HacsonRED123** [comment] 2018-03-08 12:19
my mono version are (by typing "mono -V") 5.10

**Comment by Zireael07** [comment] 2018-03-08 12:25
Install Mono 5.4, Godot is only compatible with 5.4. (btw we seem to get tons of people somehow missing this memo and trying other versions?)

**Comment by hpvb** [comment] 2018-03-08 12:27
Godot will work with Mono 5.10 but you will have to build from sources then. Our official binaries currently only work against 5.4. Sorry!

**Comment by neikeq** [comment] 2018-03-08 12:38
Actually 3.0.2 shouldn't depend on exactly Mono 5.4. It worked well for me with 5.8. I will test with 5.10.

**Comment by hpvb** [comment] 2018-03-08 12:40
It works with 5.10 for me though, but I'm on Fedora not Ubuntu. There's a good chance that this is dependent on where you got your SDK from also. I get mine from the upstream repos from the mono project. The Ubuntu binaries may be built in such a way that it's not compatible.

**Comment by neikeq** [comment] 2018-03-08 13:09
I can reproduce this on Windows 10 with Mono 5.10. The mono log:

```
DllImport attempting to load: 'advapi32.dll'. (in domain Mono, info)
DllImport error loading library 'C:\Users\Ignacio.DESKTOP-V1VR6JF\Desktop\Godot_v3.0.2-rc1_mono_win64\advapi32.dll': 'El sistema no puede encontrar el archivo especificado.
'. (in domain Mono, info)
DllImport error loading library 'C:\Users\Ignacio.DESKTOP-V1VR6JF\Desktop\Godot_v3.0.2-rc1_mono_win64\advapi32.dll': 'El sistema no puede encontrar el archivo especificado.
'. (in domain Mono, info)
DllImport loaded library 'advapi32.dll'. (in domain Mono, info)
DllImport searching in: 'advapi32.dll' ('advapi32.dll'). (in domain Mono, info)
Searching for 'RegOpenKeyEx'. (in domain Mono, info)
Probing 'RegOpenKeyExW'. (in domain Mono, info)
```

and the pretty much useless backtrace:

```
[0] mono_image_get_name
[1] mono_image_get_name
[2] mono_image_get_name
[3] mono_image_get_name
[4] mono_image_get_name
[5] mono_image_get_name
[6] mono_image_get_name
[7] <couldn't map PC to fn name>
[8] <couldn't map PC to fn name>
-- END OF BACKTRACE --
```

**Comment by HacsonRED123** [comment] 2018-03-08 14:16
so I install mono 5.4 but now the window just instantly close when I launch godot

**Comment by hpvb** [comment] 2018-03-08 14:54
@HacsonRED123 Can you run the program from the CLI and paste the output here please?

**Comment by neikeq** [comment] 2018-03-08 20:13
I just tested with Mono 5.10 again but with the assemblies `System` and `System.Xml` from Mono 5.4 in the godot's executable directory, and it no longer crashes. I'm not sure why this happens though, since there is no error message...

**Comment by juan-garcia-m** [comment] 2018-03-11 18:17
@HacsonRED123

I had the same issue as you (Ubuntu 17.10 and Mono 5.10), and after downgrading mono to 5.4 it works.
I am using the Debian repo.
Here is what I did:

First uninstall the current version:

```
$ sudo apt autoremove mono-devel
$ sudo apt purge mono-devel
```
If you installed from the Ubuntu repo you might need to do this:

```
$ sudo apt autoremove mono-complete
$ sudo apt purge mono-complete
$ # See: http://www.mono-project.com/download/stable/#download-lin-debian
$ sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
```

Then edit the sources:

```
$ sudo gedit /etc/apt/sources.list.d/mono-official-stable.list
```

Either replace the first line with this or add it if the file is empty:

```
deb http://download.mono-project.com/repo/debian wheezy/snapshots/5.4/. main
```

Save the file.
Update the sources and install mono 5.4:

```
sudo apt update
sudo apt install mono-devel
```

Run Godot 3.0.2 from the command line.
I would recommend you to always run Godot from the command line to get a log when it crashes.
If everything works, then this issue can be closed.

**Comment by akien-mga** [comment] 2018-08-31 18:05
This should be fixed by now, but for the time being it's important to always use the exact Mono version that is documented on our download page (and which was used for the build).

**Closed by akien-mga** 2018-08-31 18:05 UTC
Labels: bug, topic:mono
