### ISSUE TITLE
project.godot becomes overwritten when focusing back to editor window even if there are no changes in the file

### ISSUE THREAD

**Issue by me2beats** [godotengine/godot#42349] opened 2020-09-26 02:25 UTC
**Godot version:**

3.2.3

**OS/device including version:**

Windows

**Issue description:**

When I focus to another window then focus back to Godot Editor window, `project.godot` becomes overwritten, 
even if there are no changes in the `project.godot` file.

This in the long run can lead to faster wear on the disk, depending on the number of switches between windows and `project.godot` file size

**Steps to reproduce:**
1. Open a Godot project
2. Focus to another window
3. Focus back to godot Editor
`project.godot` is overwritten now

**Minimal reproduction project:**

**Comment by Calinou** [comment] 2020-10-01 22:06
Duplicate of https://github.com/godotengine/godot/issues/32086.

> This in the long run can lead to faster wear on the disk

This will **not** wear down a SSD in any meaningful manner :slightly_smiling_face:

**Closed by Calinou** 2020-10-01 22:06 UTC
