### ISSUE TITLE
Vulkan: LightmapGI banding visible on baked lighting due to 8 bpc lossless compression being used by default (even with denoising enabled)

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot#53436] opened 2021-10-05 15:25 UTC
### Godot version

4.0.dev (2fc31fdfc)

### System information

Fedora 34, GeForce GTX 1080 (NVIDIA 470.57.02)

### Issue description

A significant amount of banding is visible on direct baked lighting (even with denoising enabled). This applies to lights whose bake mode is set to **Static** rather than the default **Dynamic**, and becomes more noticeable when you disable bounces entirely. ~~I suspect there's a precision issue somewhere in the compute shader used to bake the lightmap.~~
**Edit:** This is caused by lightmaps using Lossless compression by default instead of VRAM Compressed (or VRAM Uncompressed). Standard lossless and lossy compression does not support HDR – only VRAM compression, Basis Universal or the uncompressed storage modes do.

Enabling denoising does not improve the situation, since denoising isn't meant to combat banding anyway. Enabling the screen-space debanding filter doesn't resolve this issue either, as the banding is part of the lightmap texture itself.

GLES3 does feature [bicubic lightmap sampling](https://github.com/godotengine/godot/issues/49935) which can hide banding a little. Nonetheless, there's still a lot of banding in the lightmap texture that wouldn't be hidden by bicubic sampling once it's implemented in the Vulkan renderer.

### Real-time light in Vulkan (good)

![light_vulkan_realtime](https://user-images.githubusercontent.com/180032/136053388-540155a6-74fd-4652-bc7b-0bc4ffde7804.png)

### Fully baked light in Vulkan (bad)

![lightmap_vulkan](https://user-images.githubusercontent.com/180032/136053379-f1968a56-d829-4859-a30d-d7bda161136d.png)

### GLES3 in `3.x` (good)

![lightmap_gles3](https://user-images.githubusercontent.com/180032/136053386-535ab8fc-7d60-4f0e-a64d-b55d7094510f.png)

### Minimal reproduction project

- `master`: [test_light_attenuation_lightmap_master.zip](https://github.com/godotengine/godot/files/7287080/test_light_attenuation_lightmap_master.zip)
- `3.x` (for comparison, baked with https://github.com/godotengine/godot/pull/52918 enabled): [test_light_attenuation_lightmap_3.x.zip](https://github.com/godotengine/godot/files/7287079/test_light_attenuation_lightmap_3.x.zip)

**Comment by williamd67** [comment] 2021-11-01 21:41
I think this is caused by an incorrect setting for the compress mode of the lightmap texture. For the reproduction project is the lightmap data stored in 'test.lmbake'. This data contains a texture `test.exr` which compress mode is set to `Lossless (PNG)` which is a `RGB8` format. This compress mode can be seen in the `Import` tab of the scene, when the `test.exr` tecture is selected. The default setting for the compress mode is `Video RAM` which is a `RGBE9995` format.

The first setting does not have enough precision causing the banding effect. The latter is much better and the banding is reduced.

**Comment by williamd67** [comment] 2021-11-01 21:45
I did find another effect which is that the color between real-time light and bake-light differs. This can also be seen in the reproduction project. Maybe we should open a separate issue for that. Any way I will investigate those color differences.

**Comment by Calinou** [comment] 2021-11-01 21:46
See https://github.com/godotengine/godot/issues/53388 for the different color output between baked and real-time lights.

**Comment by WilliamDeurwaarder-TomTom** [comment] 2021-12-21 17:38
I propose to close this issue as it is caused by an incorrect setting (see [comment](https://github.com/godotengine/godot/issues/53436#issuecomment-956662987)).

In case this explanation is not considered a solution, I like to understand what needs to be done further for this issue.

**Comment by Calinou** [comment] 2021-12-21 17:50
I can confirm that changing the compression mode to **VRAM Compressed**, **VRAM Uncompressed** or **Basis Universal** resolves the issue:

![2021-12-21_18 48 50](https://user-images.githubusercontent.com/180032/146975744-b67cfbae-2835-48d0-943f-a5a5c732034b.png)
![2021-12-21_18 48 59](https://user-images.githubusercontent.com/180032/146975749-28c11b82-72bc-47f6-8e89-74772f4a3e53.png)
![2021-12-21_18 49 09](https://user-images.githubusercontent.com/180032/146975750-e9673e4f-6c4b-4699-9b71-0f88a9cfd926.png)
![2021-12-21_18 49 18](https://user-images.githubusercontent.com/180032/146975753-9dccd98d-627e-4816-8e48-315b3b7bad51.png)

However, we should make sure that newly created lightmap textures automatically use the right compression setting (VRAM Compressed setting in this case).

**Comment by KoBeWi** [comment] 2022-06-04 16:18
Needs updated MRP, the attached one is completely black in alpha 9 and spams errors.

**Comment by clayjohn** [comment] 2024-08-19 19:40
this was fixed by https://github.com/godotengine/godot/pull/73136

**Comment by clayjohn** [comment] 2024-08-19 19:41
For future reference, the default will need to change from VRAM Uncompressed to VRAM compressed once we get betsy merged

**Closed by clayjohn** 2024-08-19 19:40 UTC
Labels: bug, topic:rendering, topic:editor, topic:3d
