### ISSUE TITLE
Black screen in editor OPENGL 3.3

### ISSUE THREAD

**Issue by sezit** [godotengine/godot#7663] opened 2017-01-28 12:18 UTC
**Operating system or device - Godot version:**
Windows 10 Nvidia GTX550Ti

**Issue description:**

When run build from 26.01.2017 editor loaded but its look like this.
![1](https://cloud.githubusercontent.com/assets/6241034/22396460/1f281c90-e56b-11e6-9f44-202405c5795d.png)
But if change monitor resolution to lower and change back its looks normal.
![2](https://cloud.githubusercontent.com/assets/6241034/22396463/4f8a0df8-e56b-11e6-96e9-22c65f25b53c.png)

I think maybe it's because my graphics card very old or maybe something else.
I know that no need to spam issue about 3.0, but maybe it helps somebody with same problem.
Don't be angry at me :З

**Comment by akien-mga** [comment] 2017-01-28 14:44
Why close it? That's a known but valid issue.

**Comment by sezit** [comment] 2017-01-28 16:25
Ok then i reopen issue. I close because i thought its just problem with editor only, but its problem with different parts of render... shadow atlas dont work at all, and if change atlas parameters it start to work, but its start create shadow from transform manipulator, so i think this issue not significant :З
![1](https://cloud.githubusercontent.com/assets/6241034/22397956/cc3412ae-e58e-11e6-8141-5f1c8cbe2080.png)
![2](https://cloud.githubusercontent.com/assets/6241034/22397957/d03ed7e4-e58e-11e6-9da2-91e6a0aa8c39.png)

**Comment by eon-s** [comment] 2017-01-28 17:07
Here, the editor starts with a black maximized window but is all visible when I change size/move the window

**Comment by MrMaidx** [comment] 2017-01-28 18:47
Issue like this happens on X11 too. But I think that reduz had noticed it too so it will be repaired once debugging starts. The fact that editor load time is much longer than in 2.1 might be caused by the same bug which is causing this.

**Comment by BastiaanOlij** [comment] 2017-02-04 05:46
And on OSX :)

There is another issue report about this from some time ago

**Comment by Noshyaar** [comment] 2018-04-10 16:15
First of all thank you for your report and sorry for the delay.

We released Godot 3.0 in January 2018 after 18 months of work, fixing many old issues either directly, or by obsoleting/replacing the features they were referring to.

We still have hundreds of issues whose relevance/reproducibility needs to be checked against the [current stable version](https://godotengine.org/download), and that's where you can help us.
**Could you check if the issue that you described initially is still relevant/reproducible in Godot 3.0 or any newer version, and comment about it here?**

For bug reports, please also make sure that the issue contains detailed steps to reproduce the bug and, if possible, a zipped project that can be used to reproduce it right away. This greatly speeds up debugging and bugfixing tasks for our contributors.

Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

Thanks in advance.

*Note: This message is being copy-pasted to many "stale" issues (90+ days without activity). It might happen that it is not meaningful for this specific issue or appears oblivious of the issue's context, if so please comment to notify the Bugsquad about it.*

**Comment by sszigeti** [comment] 2018-05-04 21:56
@Noshyaar I'm not sure if what I'm experiencing is the same or a separate issue, but there's some resemblance so I thought I'd mention it.

In my case the editor is visible regardless of resolution, however I have a test app for changing fullscreen and resolution during runtime. It's working perfectly when my display is set to its default 1920×1080, but with any other resolution I can only see black when fullscreen is enabled.
(Windows 10 64 bit; Nvidia GeForce GTX 970; Godot v3.0.2.stable.official)

I have a simple test project for this:
https://github.com/sszigeti/godot-display-test

**Comment by akien-mga** [comment] 2019-04-15 14:57
@sszigeti That's likely a separate issue, so it would be better to report it separately.

There was no answer from the OP regarding whether the issue is still valid, so closing.

**Closed by akien-mga** 2019-04-15 14:57 UTC
Labels: bug, confirmed, topic:porting, topic:rendering
