### ISSUE TITLE
FreeBSD builds not working because of ThorVG

### ISSUE THREAD

**Issue by mundusnine** [godotengine/godot#61036] opened 2022-05-14 18:05 UTC
### Godot version

The version on the 7 April: https://cirrus-ci.com/build/4750479493169152

### System information

FreeBSD

### Issue description

alloca.h wasn't available in FreeBSD for [ThorVG](https://cirrus-ci.com/task/5485473287110656?logs=build#L657)

### Steps to reproduce

Download github master, try building it on FreeBSD.

[Fix](https://github.com/Samsung/thorvg/pull/1223) merged on ThorVG. Next update of thorvg should contain the fix, this issue should be fixed when godot updates to the new version.

**Comment by Calinou** [comment] 2022-05-14 18:16
Duplicate of https://github.com/godotengine/godot/issues/60003.

**Closed by Calinou** 2022-05-14 18:16 UTC
