### ISSUE TITLE
Light theme, no Accent Color in toolbar

### ISSUE THREAD

**Issue by Jeb187** [godotengine/godot#31763] opened 2019-08-29 10:54 UTC
**Godot version:**
V3.1.1

**OS/device including version:**
Manjaro Linux

**Issue description:**
What happened:

I went to the editor theme settings and chose the Light theme. All Icons in the toolbar (Select Mode, Move Mode, ...) turned to black. None is highlighted in the Accent color.

and what was expected.
The selected mode or snap toggle should be highlighted in the accent color.

**Steps to reproduce:**
Switch default theme to Light.

**Comment by Chaosus** [comment] 2019-08-29 17:02
Duplicate of #28941

**Closed by Chaosus** 2019-08-29 17:02 UTC
Labels: bug, topic:editor, usability
