### ISSUE TITLE
Area3D gravity problem in Godot 4

### ISSUE THREAD

**Issue by Lubarius** [godotengine/godot#77682] opened 2023-05-31 06:30 UTC
### Godot version

v4.0.3.stable.official [5222a99f5]

### System information

Linux Mint 21.1 - v4.0.3.stable - Vulkan (Forward+) - Intel(R) Graphics (ADL GT2)

### Issue description

When RigidBody enters an area with gravity space override, gets pulled to the middle (gravity point enabled), then its position is set to the outside of this area (or area is deleted), it is then still attracted by the area's gravity no matter where it is located. In Godot 3, this worked well.

Link to my forum post where it was suggested that this could be a bug:
[https://godotforums.org/d/33811-area3d-gravity-problem-in-godot-4](url)

![gravity_Godot4](https://github.com/godotengine/godot/assets/133772534/9b68bebb-e589-4c03-8f3a-0f92fa594f45)

### Steps to reproduce

1. Create Area3D with gravity space override (combine mode in my case).
2. Let RigidBody3D be attracted to the middle (gravity point enabled).
3. Then either change position of RigidBody3D outside the Area3D or just delete Area3D (queue_free).

### Minimal reproduction project

[Area_gravity_sample_Godot4.zip](https://github.com/godotengine/godot/files/11609411/Area_gravity_sample_Godot4.zip)

**Comment by Occalepsus** [comment] 2023-09-25 11:19
Could reproduce with in the latest dev version at commit [df0a822](https://github.com/godotengine/godot/commit/df0a822323a79e1a645f0c6a17d51c7602f23166).
I think the problem is that when the RigidBody does not leave the Area3D (I mean leaving my moving through its borders), it does not update the gravity status of the Rigidbody. That means if the Area is disabled, deleted, moved away, or if the rigidbody, like here, is moved outside, then its gravity is not updated.

I will look deeper into that, please let me know if you have any update!

**Comment by altranaen** [comment] 2023-10-31 18:41
I encountered this as well, for anybody wanting a temporary hack until the fix is merged, you can flip off the collision layer for the object intending to move out of the area and wait a frame or two before moving the object

**Closed** 2023-12-22 16:23 UTC
Labels: bug, topic:physics
