### ISSUE TITLE
The GUI sometimes expands

### ISSUE THREAD

**Issue by AlphinAlbukhari** [godotengine/godot#35398] opened 2020-01-21 09:40 UTC
**Godot version:** 3.2 RC2

**OS/device including version:** Windows 10

**Issue description:** The GUI sometimes expands (I don't know why), so I can't click on anything at the bottom
https://youtu.be/M725NcCJuqY

**Steps to reproduce:** Sometimes it happens if I change workspaces, for example 2D to 3D, Script Editor to 2D, etc.

**Minimal reproduction project:** -

**Comment by bojidar-bg** [comment] 2020-01-21 10:43
For a workaround: resize the editor window when it happens, so that it resizes the Container nodes involved.

**Comment by AlphinAlbukhari** [comment] 2020-01-23 09:06
yes, sometimes it can, but sometimes it can't be recovered at all. To overcome this, I must exit to the Project Manager and then open the project again

**Comment by bojidar-bg** [comment] 2020-01-23 14:24
@AlphinAlbukhari A screenshot of the editor in state where resizing it does not bring the bottom bar back on-screen would be welcome, as it would allow us to spot which panels are pushing it down.

**Comment by Calinou** [comment] 2020-05-22 12:37
Duplicate of #33133 and possibly others.

**Closed by Calinou** 2020-05-22 12:37 UTC
Labels: bug, topic:editor

**Comment by bojidar-bg** [comment] 2020-05-22 14:11
> Duplicate of #33133 and possibly others.

@Calinou Wrong issue reference?

**Comment by Calinou** [comment] 2020-05-22 14:33
@bojidar-bg Fixed.
