### ISSUE TITLE
Godot 3.2.3 GLES3 handles transparency wrong

### ISSUE THREAD

**Issue by nerdnils** [godotengine/godot#43569] opened 2020-11-15 16:46 UTC
I already posted this as #43559 but it was closed and I was told to post it again.
This is not #26779 as this works in GLES3 but not in GLES2. Mine works in GLES2 but not in GLES3. And #26779 was already fixed. Mine also happens in the newest godot-Version.

I have a viewport inside of a Viewportcontainer or I can use the texture of this viewport in a TextureRect it does not matter.
Parallaxbackground having a sprite used as background for everything. So this Viewport has transparency set on. Everything where transparency should be is 100% pure black. When adding a CanvasItemMaterial I can see this only happens on Blend Mode Mix. Add and Sub handle the transparency right. But that way the colors are off. When switching to GLES2, the transparency is handled right, no black.

Second issue I found: when using the texture as texture for TextureRect, VFlip is upside down/works the other way around.

Godot version: 3.2.3

Archlinux 5.4.77-1-lts

NVIDIA Corporation GP106 [GeForce GTX 1060 6GB]

When creating the minimal project file including this bug I saw that it has something to do with the Worldenvironment. The bug only happens when this environment is there. Bug does not happen without the environment. But I can not find any setting which would cause this behaviour.
[test.zip](https://github.com/godotengine/godot/files/5542754/test.zip)

**Comment by nerdnils** [comment] 2020-11-15 16:54
The relevant Option seems to be Background "Canvas".

**Comment by Calinou** [comment] 2020-11-15 17:19
@nerdnils I didn't close #43559…

**Comment by nerdnils** [comment] 2020-11-15 20:19
Sorry, didn't know I could reopen it myself.

**Comment by Calinou** [comment] 2020-11-21 14:49
Duplicate of https://github.com/godotengine/godot/issues/43559.

**Closed by Calinou** 2020-11-21 14:49 UTC
