### ISSUE TITLE
Undo/Redo Broke When It Reached "Nothing to Undo/Redo"?

### ISSUE THREAD

**Issue by treblig-punisher** [godotengine/godot#54722] opened 2021-11-07 15:44 UTC
### Godot version

3.4 Stable

### System information

Windows 10 Pro, GPU GTX 1070Ti, rendering backend GLES3

### Issue description

**Today 11-7-2021**, while I was editing some scenes, One I instantiated as and new inherited scene, and the source one, I started hitting undo a couple times, and I noticed that doing so would go to a scene i recently fiddled around with(newly inherited) besides the one I was currently working on(source). Everything went fine until I got the console message: nothing else to undo/redo. After getting this, every change I made I couldn't undo. The only way I could fix this was by restarting the engine. I can't seem to get it to happen again.

### Steps to reproduce

Hitting Undo while editing multiple scenes until reaching **_Nothing to undo_** broke the undo, redo system.

**Comment by Calinou** [comment] 2021-11-07 15:46
Did you switch scene tabs as part of the undo/redo process? If so, that may be the causz of this issue. (Switching scene tabs is logged as UndoRedo actions, since the scene needs to be open in the current tab for undo/redo to work.)

**Comment by treblig-punisher** [comment] 2021-11-07 16:26
> 
> 
> Did you switch scene tabs as part of the undo/redo process? If so, that may be the causz of this issue. (Switching scene tabs is logged as UndoRedo actions, since the scene needs to be open in the current tab for undo/redo to work.)

Yeah. I didn't know that even switching scenes would count as undo, so I was a  little surprised, but then undo/redo stopped working, and I was wondering what happened. I reopened my project and this stopped happening though, but I found it quite puzzling

**Comment by KoBeWi** [comment] 2022-10-11 14:40
@treblig-punisher Were you (or anyone else) able to reproduce this issue again?

If it's related to scene tabs, it's probably resolved in 4.0.

**Comment by treblig-punisher** [comment] 2022-10-11 21:06
> 

I haven't tried to replicate this. I've been using version 3.5, and I might have to give it a go to see if it's still present. Glad to hear it might be fixed for 4.0!

**Comment by KoBeWi** [comment] 2022-10-11 21:09
Closing then. Comment if you manage to reproduce it again.

**Closed by KoBeWi** 2022-10-11 21:09 UTC
Labels: bug, topic:editor, needs testing
