### ISSUE TITLE
[LIGHT CULL AND SHADOWS]When light culls an object, its shadow is still rendering

### ISSUE THREAD

**Issue by Atem1995** [godotengine/godot#59654] opened 2022-03-29 03:44 UTC
### Godot version

3.4.4 stable

### System information

window 10 

### Issue description

When light culls an object, its shadow is still rendering.It seems like a bug.But Geometry's shadow rendering setting is in the GeometryInstance.So I don't know whether it is a bug or not.Just report it. : )

### Steps to reproduce

#

### Minimal reproduction project

_No response
![light_cull_and_shadows](https://user-images.githubusercontent.com/52338846/160528997-3401d8ce-b7c7-44c1-9a45-cda5c3fe5a40.PNG)
_

**Comment by clayjohn** [comment] 2022-03-29 06:05
I'm not sure if it is a bug or not either. The cull layer impacts whether the objects receives light from a given light source. Intuitively, I guess if a surface doesn't receive light, the light must be passing right through it. At the same time though, it seems odd that the cull layer of one object should impact the lighting on another object.

**Comment by Atem1995** [comment] 2022-03-29 06:26
> I'm not sure if it is a bug or not either. The cull layer impacts whether the objects receives light from a given light source. Intuitively, I guess if a surface doesn't receive light, the light must be passing right through it. At the same time though, it seems odd that the cull layer of one object should impact the lighting on another object.
![light_cull](https://user-images.githubusercontent.com/52338846/160546968-0df6eae6-3e4f-4cdb-a741-b76a4b170fef.PNG)
This also happens in 4.0 alpha。

**Comment by lawnjelly** [comment] 2022-03-29 06:48
It seems to me from a user perspective I'm wondering if it might be nicer to have an option like:

* Never cast shadow
* Always cast shadow
* Cast shadow if parent object showing
 
And the "double sided" should be a separate option.

It may actually be easier to do this kind of thing now than it used to be, now we have templated checks in the BVH, the callback could possibly handle this extra logic (before we had an object mask, which was set beforehand, and a test mask, and that was it). The only thing would be the backward compatibility aspect for the UI, but if we could figure a way around that this might be doable.

**Comment by Atem1995** [comment] 2022-03-29 07:24
> It seems to me from a user perspective I'm wondering if it might be nicer to have an option like:
> 
> * Never cast shadow
> * Always cast shadow
> * Cast shadow if parent object showing
> 
> And the "double sided" should be a separate option.
> 
> It may actually be easier to do this kind of thing now than it used to be, now we have templated checks in the BVH, the callback could possibly handle this extra logic (before we had an object mask, which was set beforehand, and a test mask, and that was it). The only thing would be the backward compatibility aspect for the UI, but if we could figure a way around that this might be doable.

It seems to me that when an object doesn't receive a certain light, it also doesn't produce shadows from that light. I think light culling should reduce the amount of computation.

**Comment by lawnjelly** [comment] 2022-03-29 08:11
> It seems to me that when an object doesn't receive a certain light, it also doesn't produce shadows from that light. I think light culling should reduce the amount of computation.

Oh yep sure that makes sense to be the default. I'm not sure why this doesn't work already, maybe the light mask is not passed during shadow culling. I will try and have a look. :+1:

**Comment by Atem1995** [comment] 2022-03-29 08:14
Thank you for your work.



---Original---
From: ***@***.***&gt;
Date: Tue, Mar 29, 2022 16:11 PM
To: ***@***.***&gt;;
Cc: "吾也君( Atem ***@***.******@***.***&gt;;
Subject: Re: [godotengine/godot] [LIGHT CULL AND SHADOWS]When light culls anobject, its shadow is still rendering (Issue #59654)




  
It seems to me that when an object doesn't receive a certain light, it also doesn't produce shadows from that light. I think light culling should reduce the amount of computation.
  
Oh yep sure that makes sense to be the default. I'm not sure why this doesn't work already, maybe the light mask is not passed during shadow culling. I will try and have a look. 👍

**Comment by mrjustaguy** [comment] 2022-03-29 10:43
this is present in 4.0 too and I would call it unexpected behavior from the user's point of view, as only makes sense for an object to cast shadows if it is also getting lit, and is just hurting performance

**Comment by Atem1995** [comment] 2022-03-29 14:14
> > It seems to me that when an object doesn't receive a certain light, it also doesn't produce shadows from that light. I think light culling should reduce the amount of computation.
> 
> Oh yep sure that makes sense to be the default. I'm not sure why this doesn't work already, maybe the light mask is not passed during shadow culling. I will try and have a look. 👍
> 
> It looks like it may not be that tricky to get working (at least for non-directionals, I think directionals use pairing but it may be possible). I have to sort some other bugs though before I can properly look at this.

I like the development mode of godot very much. I can write some C++ code, but I don't know how I should understand the architecture code of godot step by step. Can you tell me where to start to learn the source code of godot?

**Comment by Calinou** [comment] 2022-03-29 14:30
Duplicate of https://github.com/godotengine/godot/issues/54613.

> It seems to me from a user perspective I'm wondering if it might be nicer to have an option like:

I'd recommend opening a proposal for this.

**Closed by Calinou** 2022-03-29 14:30 UTC
Labels: discussion, topic:rendering

**Comment by eddieataberk** [comment] 2024-05-03 02:21
It says completed but the issue is still prevalent in 4.2.2 and 4.3 dev 6 is there a fix for it?
![image](https://github.com/godotengine/godot/assets/48696693/105ee42c-a1f2-428c-b38b-8577055ae244)

**Comment by Calinou** [comment] 2024-05-06 22:35
This was fixed by https://github.com/godotengine/godot/pull/61841 in `3.x` and subsequently by https://github.com/godotengine/godot/pull/70638 in `master`.

However, there's a new issue tracking this, so please continue the discussion there: https://github.com/godotengine/godot/issues/70556
