### ISSUE TITLE
Scaling TileMap scales physics layer incorrectly

### ISSUE THREAD

**Issue by miscbill** [godotengine/godot#67601] opened 2022-10-19 00:06 UTC
### Godot version

4.0.beta3

### System information

macos 12.1, Vulkan API 1.1.216 - Using Vulkan Device #0: Apple - Apple M1 Max

### Issue description

When a TileMap is scaled, the collision polygons in its physics layers are scaled, but translated too far.

In this screen capture, the purple tiles have collision boxes. I expected the boxes to line up with the tiles. (The Node2D containing this TileMap has a scale of Vector2(1.5,1.5)
<img width="591" alt="Screen Shot 2022-10-18 at 7 52 24 PM" src="https://user-images.githubusercontent.com/1789350/196566592-f5dffa38-c603-434b-b500-a5235f0878e6.png">

### Steps to reproduce

Create a tilemap. 
In it's TileSet, add an atlas texture, make a few tiles from it. 
Add a physics_layer to the TileSet.
Use the paint tool to give tiles distinguishable collision boxes in that physics layer.
On the TileMap, set "Collision Visibility Mode" to "Force Show".
Draw some tiles on your TileMap.
On the TileMap, set scale x and y to 1.5.
Run the scene, note the weirdly place collision polys.

### Minimal reproduction project

[tile_scale_test.zip](https://github.com/godotengine/godot/files/9815752/tile_scale_test.zip)

**Comment by Calinou** [comment] 2022-10-20 20:57
This is a duplicate of another issue, but I can't find it right now.

**Closed** 2022-10-29 22:15 UTC
Labels: bug, topic:core, confirmed, topic:2d
