### ISSUE TITLE
Logfile accumulation in mono_logs directory [Godot 3.2 mono]

### ISSUE THREAD

**Issue by rick551a** [godotengine/godot#45051] opened 2021-01-09 19:50 UTC
**Godot version: 3.2 mono (all)**

**OS/device including version: Windows 10**

**Issue description:**
After each build, a log file is generated in AppData\Roaming\Godot\mono\mono_logs.
These start to seriously accumulate after a while. I have 50 after only a few days testing. 

Many users would have no idea these files exist and there is no way (from the editor) to clean this directory.

Maybe a 'Clean logs directory' button beside the build button on the panel in the editor. Or even an indicator that shows how many KB and files count in the AppData\Roaming\Godot\mono\mono_logs. directory.

**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by Calinou** [comment] 2021-01-09 22:28
Duplicate of https://github.com/godotengine/godot/issues/21895.

**Closed by Calinou** 2021-01-09 22:28 UTC
