### ISSUE TITLE
Color picker in Editor settings closes by itself

### ISSUE THREAD

**Issue by carllacan** [godotengine/godot#54696] opened 2021-11-07 06:32 UTC
### Godot version

3.4 stable

### System information

Manjaro with Plasma KDE, Atx Radeon 580 GLES3

### Issue description

It happens when I try to change the highlight colors of the text editor. The color picker opens but it closes by itself while I am choosing the color and the chosen color is not saved.

### Steps to reproduce

Open Editor settings
Open Text editor/Hightlighting
Try to change a color
Click around the color picker a few times
The color picker closes by itself and the chosen color is not saved.

It doesn't happen reliably. It takes a few clicks to trigger it, and sometimes it doesn't happen at all no matter how long you keep trying.

**Comment by kleonc** [comment] 2021-11-07 11:08
Duplicate of #23626.

**Closed** 2021-11-07 12:58 UTC
Labels: bug, topic:editor, topic:gui
