### ISSUE TITLE
Cant write @ (alt + 2) in code editor on macOS 

### ISSUE THREAD

**Issue by DavidMag** [godotengine/godot#59811] opened 2022-04-02 12:53 UTC
### Godot version

4.0.alpha5

### System information

macOS 

### Issue description

When in code editor and pressing alt + 2 which is @ on Swedish keyboards I get moved to 3D window instead of inputing a @.

### Steps to reproduce

Included in description

**Comment by bruvzg** [comment] 2022-04-02 13:17
Duplicate of https://github.com/godotengine/godot/issues/6851, https://github.com/godotengine/godot/issues/54303, and https://github.com/godotengine/godot/issues/56319, should be fixed by #56695

**Closed** 2022-04-02 13:36 UTC
