### ISSUE TITLE
Exporting from the command line with --no-window on Windows opens the editor

### ISSUE THREAD

**Issue by samdze** [godotengine/godot#39710] opened 2020-06-20 14:02 UTC
**Godot version:**
3.2.1

**OS/device including version:**
Windows 10 64 bit

**Issue description:**
Exporting a game from the command line in Windows using the `--no-window` option still opens the Godot editor window.

This is probably relevant for 3.2.x only, as a more clean and complete solution is being evaluated for Godot 4.0:
https://github.com/godotengine/godot-proposals/issues/991

**Steps to reproduce:**
Export a project from the command line, using something like:
`godot --no-window --export "Windows Desktop" builds/Test.exe`

**Comment by Calinou** [comment] 2021-08-08 13:27
Duplicate of https://github.com/godotengine/godot/issues/43752 (same cause).

**Closed by Calinou** 2021-08-08 13:27 UTC
Labels: bug, platform:windows, topic:editor
