### ISSUE TITLE
Can't open or create a project in the web editor

### ISSUE THREAD

**Issue by astrale-sharp** [godotengine/godot#45762] opened 2021-02-06 13:26 UTC
**Godot version:**
  3.2.4.rc1.official 

**OS/device including version:**

```
❯ screenfetch
                                       astrale@Sharp
 MMMMMMMMMMMMMMMMMMMMMMMMMmds+.        OS: Linuxmint 20.1 ulyssa
 MMm----::-://////////////oymNMd+`     Kernel: x86_64 Linux 5.4.0-65-generic
 MMd      /++                -sNMd:    Uptime: 4h 19m
 MMNso/`  dMM    `.::-. .-::.` .hMN:   Packages: 3899
 ddddMMh  dMM   :hNMNMNhNMNMNh: `NMm   Shell: fish 3.1.0
     NMm  dMM  .NMN/-+MMM+-/NMN` dMM   Resolution: 1920x1080
     NMm  dMM  -MMm  `MMM   dMM. dMM   DE: Cinnamon 4.8.6
     NMm  dMM  -MMm  `MMM   dMM. dMM   WM: Muffin
     NMm  dMM  .mmd  `mmm   yMM. dMM   WM Theme: Mint-Y-Dark-Blue (Mint-Y)
     NMm  dMM`  ..`   ...   ydm. dMM   GTK Theme: Mint-Y-Dark-Red [GTK2/3]
     hMM- +MMd/-------...-:sdds  dMM   Icon Theme: breeze-dark
     -NMm- :hNMNNNmdddddddddy/`  dMM   Font: Ubuntu Condensed, 24
      -dMNs-``-::::-------.``    dMM   Disk: 719G / 1,1T (74%)
       `/dMNmy+/:-------------:/yMMM   CPU: Intel Core i3-2330M @ 4x 2.2GHz [60.0°C]
          ./ydNMMMMMMMMMMMMMMMMMMMMM   GPU: GeForce GT 630M
             \.MMMMMMMMMMMMMMMMMMM     RAM: 2668MiB / 3844MiB
                                      
```

**Issue description:**

I downloaded the demo.zip project example, loaded it into the editor and pressed "Start Godot editor", instead of opening the project it showed the project was missing.
![Capture d’écran du 2021-02-06 14-17-24](https://user-images.githubusercontent.com/53686698/107119294-f7f70700-6886-11eb-9771-6306a8928cf1.png)

![Capture d’écran du 2021-02-06 14-18-26](https://user-images.githubusercontent.com/53686698/107119327-24128800-6887-11eb-8f52-1f20a378da86.png)

Same thing happens if I try to start a new project from the online editor.

**Steps to reproduce:**
1 : download the demo.zip project
2 : try to import it

**Comment by Calinou** [comment] 2021-02-06 15:40
Duplicate of https://github.com/godotengine/godot/issues/44754.

**Closed by Calinou** 2021-02-06 15:40 UTC
