### ISSUE TITLE
Crash after creating global group and switching scene

### ISSUE THREAD

**Issue by EmilPastelka** [godotengine/godot#94668] opened 2024-07-23 17:54 UTC
### Tested versions

Reproducible in: 4.3 beta 3

### System information

Godot v4.3.beta3 - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 4060 (NVIDIA; 31.0.15.5212) - AMD Ryzen 5 7600 6-Core Processor (12 Threads)

### Issue description

The error occurs when creating a new global group and assigning it to a node inside its own scene and then trying to switch to the main scene.
Tested on multiple Windows 10 PCs.

### Steps to reproduce

- there is a main scene "level"
- inside scene "level" is scene "player"
- both "level" and "player" scenes are open
- when editing the "player" scene, a new global group is created
- the group is assigned to an element inside the "player" scene
- click on the tab of the main scene "level" and switch to it
- crash

### Minimal reproduction project (MRP)

The error shows up in any new project.

**Comment by KoBeWi** [comment] 2024-07-23 22:10
Thanks for the report, duplicate of #94274

**Closed by KoBeWi** 2024-07-23 22:10 UTC
Labels: bug, topic:editor, needs testing, crash
