### ISSUE TITLE
godot script: clone sub class (improvement)

### ISSUE THREAD

**Issue by ret80** [godotengine/godot#4796] opened 2016-05-24 13:20 UTC
I wrote here such script:
fuzzy.gd

```
extends Node
# sub class
class FzSet:
   var st
   func _init(v):
      st = v.st
   func clone():
      return FzSet.new(self)
```

eventually I found that this does not work. should be replaced

```
return FzSet.new(self)
```

 to

```
extends Node
# sub class
class FzSet:
   var st
   func _init(v):
      st = v.st
   func clone():
      return load("res:/fuzzy.gd").FzSet.new(self)
```

But it looks like that scary.

PS.
Perhaps there is another way, and I just do not know about it.

**Comment by reduz** [comment] 2016-05-24 14:27
return get_class().new()

**Comment by ret80** [comment] 2016-05-24 14:37
Invalid call. Nonexistent function 'get_class' in base 'Reference ()'.

> return get_class().new()

**Comment by eska014** [comment] 2016-05-24 16:10
`return get_script().new()`

**Comment by eska014** [comment] 2016-05-24 16:44
You can't reference `FzSet` within `FzSet`, so you call `get_script()` to retrieve the class instead.
So you would change your original `clone()` function like this:

    func clone():
        return get_script().new(self)

**Comment by ret80** [comment] 2016-05-24 18:11
Yes, that's it ``` return get_script().new() ``` works. But it is not pretty. Probably still worth making improvement.

**Comment by vnen** [comment] 2016-06-19 04:08
Apparently `get_script().new()` does not work in the main class of the file. I'm gonna try to remember to test this tomorrow, but it also fits this proposal, I think.

**Comment by bojidar-bg** [comment] 2017-02-20 19:58
Is this by any chance a duplicate of #944?

**Comment by Calinou** [comment] 2020-01-30 21:32
Superseded by https://github.com/godotengine/godot-proposals/issues/391, closing.

**Closed by Calinou** 2020-01-30 21:32 UTC
Labels: feature proposal, topic:gdscript
