### ISSUE TITLE
SSL certificate(s) not included in Packaged data

### ISSUE THREAD

**Issue by supagu** [godotengine/godot#19095] opened 2018-05-22 06:51 UTC
3.0-stable-1811-g228b09baf

Running my game unpacked works fine. When I run it packed, it fails in StreamPeerSSL::get_project_cert_array.

FileAccess::open returns NULL as it cannot find my SSL certificate which is in my project.godot file:

`[network]

ssl/certificates="res://SSL/ca-bundle.crt"`

I tried exporting the pck as a zip, and have noticed that it has not included the SSL directory in the zip file.

here are my linux export presets:
`[preset.0]

exclude_filter=""
export_filter="all_resources"
include_filter=""
name="Linux/X11"
patch_list=PoolStringArray(  )
platform="Linux/X11"
runnable=true

[preset.0.options]

binary_format/64_bits=true
custom_template/debug=""
custom_template/release=""
texture_format/etc=false
texture_format/etc2=false
texture_format/s3tc=true`

**Comment by Keetz** [comment] 2018-05-22 07:44
You have to add the .crt file at the export filters.

"Filters to export non-resource files (comma separated, e.g: *.json, *.txt)"

So just add "*.crt" to your filter

**Comment by mhilbrunner** [comment] 2018-05-22 08:34
Should we do that as a default?

**Comment by Keetz** [comment] 2018-05-22 08:44
@mhilbrunner best case scenario, no.
In my opinion the best case scenario is that godot uses its own default certificates or OS provided certificates. See the discussion in #17328

**Comment by supagu** [comment] 2018-05-22 09:07
So is my SSL certificate redundant then? I only have it so I can use SSL, but if godot will default to work with SSL then I don't need it.
I would still expect godot to by default include any certificates files with out needing a special filter. I have translation files *.po that get included that don't need a special filter, so why should *.ca be different?

**Comment by Keetz** [comment] 2018-05-22 09:13
@supagu as of now it is NOT redundant. In the future, hopefully, it will be though.
I think it makes good sense that you have to include the file in the filters as long as Godot offers a default certificate, because then a certificate file is not something Godot uses, like a plain .txt file for example.

Again, in my opinion, this should stay as it is, and some sort of default certificate handling should be added instead.

**Comment by mhilbrunner** [comment] 2018-05-22 13:29
Closing as duplicate of https://github.com/godotengine/godot/issues/17328 then, as thats the best solution. See discussion there. For now, include the `*.crt` filter.

**Closed by mhilbrunner** 2018-05-22 13:29 UTC
