### ISSUE TITLE
typed array copied/unusable in cross-language scripting

### ISSUE THREAD

**Issue by tvenclovas96** [godotengine/godot#96112] opened 2024-08-26 11:19 UTC
### Tested versions

- tested in 4.3 mono release version

### System information

Godot v4.3.stable.mono - Windows 10.0.19045 - Vulkan (Mobile) - dedicated NVIDIA GeForce RTX 3080 (NVIDIA; 31.0.15.4601) - AMD Ryzen 5 5600X 6-Core Processor (12 Threads)

### Issue description

Recently, an issue was fixed in godot-cpp and the engine where typedarrays were copied instead of passed by reference, such as when calling gdextension methods from gdscript https://github.com/godotengine/godot/pull/89197

However, if accessing gdextension from C# using `Call(StringName method, params Variant[] args)` the same issue persists, where untyped arrays work as expected when passed an `Array`,  while typed arrays are copied when passing a variant-compatible `Array<T>`

This also turns out to be an issue when calling GDscript from C#. If we call a GDscript function using `Call`, it will accept an untyped `Array`, but will fail and throw an error if passed an `Array<T>` for a typed array argument, despite the same type being used.

```
void Godot.GD.PushError(string): Invalid type in function 'change_typed' in base 'Godot.Node'. The array of argument 2 (Array) does not have the same element type as the expected typed array argument.
```

### Steps to reproduce

Use the `Call` function with an `Array<T>` argument from c# to an appropriate function in the engine/gdscript

### Minimal reproduction project (MRP)

[typedarraymrp.zip](https://github.com/user-attachments/files/16747874/typedarraymrp.zip)

**Comment by raulsntos** [comment] 2024-08-29 23:55
Duplicate of https://github.com/godotengine/godot/issues/74936

**Closed by raulsntos** 2024-08-29 23:55 UTC
Labels: bug, topic:gdextension, topic:dotnet
