### ISSUE TITLE
Godot immediately focuses script editor after crash.

### ISSUE THREAD

**Issue by CarpenterBlue** [godotengine/godot#69496] opened 2022-12-02 15:27 UTC
### Godot version

3.5.1

### System information

Irrelevant

### Issue description

Godot immediately focuses the script editor after crash, this means that user will accidentally type something into the script editor 99% of the time because they were holding a key.
Because of this, I accidentally inserted empty space into a string and didn't notice which broke my state manager in very un-noticeable way.

### Steps to reproduce

Crash the game while holding a key, preferably a letter or spacebar.

### Minimal reproduction project

N/A

**Comment by Calinou** [comment] 2022-12-02 15:30
By "crash", are you referring to a script error or a hard crash of the game process? These are handled differently by the editor.

**Comment by KoBeWi** [comment] 2022-12-02 15:43
Duplicate of #21812

**Closed by KoBeWi** 2022-12-02 15:43 UTC
Labels: discussion, topic:editor
