### ISSUE TITLE
event.is_action(...) returns false for release events of modifier keys (ctrl, alt)

### ISSUE THREAD

**Issue by romlok** [godotengine/godot#5901] opened 2016-07-25 13:52 UTC
**Operating system or device - Godot version:**

Debian Linux X11 64bit
Godot 2.0.4.1 and 2.1-rc1

**Issue description**:

When handling input events with `_input()`, for input map actions triggered by modifier keys (tested: ctrl, alt), only the press event has its `is_action()` report `true` - the release event reports `false` for that same action name.

Expected behaviour is for both the press and release events of modifier keys to return the same value for `event.is_action(...)`.

**Steps to reproduce:**

```
extends Sprite

func _ready():
	set_process_input(true)

func _input(event):
	if event.is_action("boop"):
		set_flip_v(event.is_pressed())
```
When triggered by a modifier key, the Sprite is never un-flipped.

**Link to minimal example project**:

https://github.com/raumkraut/godot-tests
Open and run "input.tscn".
Space and Ctrl are set up to flip/unflip the sprite.

**Comment by akien-mga** [comment] 2016-07-25 13:56
As mentioned on IRC already, duplicate of #2597.

**Comment by raumkraut** [comment] 2016-07-25 14:10
I looked at #2597, but I can't see how this is a duplicate of that behaviour.
I find that checking `Input.is_action_pressed` in `_process` responds as expected when ctrl is released - at the same time that `event.is_action(...)` does not.

**Comment by eska014** [comment] 2016-07-25 21:49
Yeah, the `Input` singleton ignores modifiers, but InputEvents are strict about them
Can't reproduce this bug on Win7 though, only on FreeBSD, so it's probably X11-related

**Comment by akien-mga** [comment] 2016-07-27 12:34
Not critical for the upcoming 2.1, so moving to the next milestone.

**Closed** 2016-09-22 13:33 UTC
Labels: bug, confirmed, platform:linux, topic:porting
