### ISSUE TITLE
[Godot 4] Opening a "store_var" file from 3.5 gets loaded as Matrix instead of actual content

### ISSUE THREAD

**Issue by Reneator** [godotengine/godot#74811] opened 2023-03-12 08:53 UTC
### Godot version

v4.0.stable.official [92bee43ad]

### System information

Windows 10

### Issue description

Loading a file i created in v3.5.1.stable.official [6fed1ffa3] and saved a dictionary with "store_var" in, loads in 3.5.1 correctly, but when it is being opened in godot 4 and then loaded the content via "get_var" will then be a matrix instead.

If i do the same thing within Godot 4 it works as expected and loads the contents of the file as dictionary.

My Expectation here is that the Content of the Godot 3 files will be loaded in the same way as the godot 4 ones, as this would completely break compatability with any save-games of my game from previous versions.

I tried using alternative means of loading the contents of the godot 3 files, but for example get_as_text only return the first symbol in the file.

### Steps to reproduce

https://user-images.githubusercontent.com/24807557/224534274-cef532a6-8692-4135-85bf-9b9381555401.mp4

Open the v3 reproduction project in godot 3.5.1, start it once and check the console output. It should be the dictionary that was defined in the field (see video).

Open the v4 reproduction project in godot 4.0

Open the app_userdatar folder for the v3 reproduction project and copy the test_file.file to the v4 reproduction project

start the v4 reproduction project.

Check console output:

The Godot 4 store_var/get_var operation should result in a correct dictionary.
The get_var on the file from godot 3 will result in a Matrix.

### Minimal reproduction project

[Reproduction store var dictionary v3.zip](https://github.com/godotengine/godot/files/10950354/Reproduction.store.var.dictionary.v3.zip)

[Reproduction load file get_var godot 4.zip](https://github.com/godotengine/godot/files/10950352/Reproduction.load.file.get_var.godot.4.zip)

**Comment by AThousandShips** [comment] 2023-03-12 08:57
I don't think this is expected to work, being able to load data from across a major version change

**Comment by AThousandShips** [comment] 2023-03-12 09:01
When encountering a problem I would recommend first going to the [community channels](https://godotengine.org/community) and discuss it to see if you're actually encountering a bug

**Comment by Reneator** [comment] 2023-03-12 09:09
I would agree if the stored var were a complex type, but just having 100% text based dictionaries not being able to load anymore just because of a new version is extremely painful.
 
 My expectations would have been to have a way to convert files that were stored in 3.5.1 to convert to be godot 4 compatible, or having a compatability mode to be able to load those files once.

**Comment by AThousandShips** [comment] 2023-03-12 09:10
But it's not realistic to be bound to backwards compatibility forever, and as I said no such guarantee has been made

If you want compatibility use a portable format like JSON

**Comment by AThousandShips** [comment] 2023-03-12 09:11
Also from the documentation:
> As such, it is generally not recommended to move projects between major versions during their development, especially if you've been working on them for a significant amount of time.

**Comment by Reneator** [comment] 2023-03-12 09:13
No need to lecture me, i was just stating a problem and trying to communicate it, to help with development and solve a problem im having.

**Comment by AThousandShips** [comment] 2023-03-12 09:14
I'm not lecturing you?:8? Sorry if I'm coming across as such, I'm explaining why your assumption is wtong

**Comment by Reneator** [comment] 2023-03-12 09:20
I mean, i totally understand that for complex objects, like if you were to try and save an entire scene via store_var and not being able to load that in godot 4 via get_var. I fully agree on that.

But for a dictionary only containing Strings, to just say "nah, its major change, your expectations/assumptions are wrong" instead of explaining WHY its not possible, feels a bit condescending.

If its like "ok, in godot 4 we changed the way dictionaries are structured and how strings are saved" im 100% on board with it. 
But just waving around the rules without trying to clarify the circumstances is counterproductive imo.

**Comment by AThousandShips** [comment] 2023-03-12 09:23
I explained that the variant types changed which changes the encoding, dictionary in 3.x and 4.0 doesn't have the same id number now

Godot uses a variant of semantic versioning, meaning that 4.0 and 3.x are incompatible, 4.0 is a compatibility breaking change, no guarantees are made about anything being compatible

**Comment by Reneator** [comment] 2023-03-12 09:23
Ok, Thanks for the explanation!

**Comment by Reneator** [comment] 2023-03-12 09:31
And thanks for pointing me in the right direction. I will try to migrate the save files of my current version into the JSON Format to make a migration to godot 4 possible.

I still think the premise of the ticket could be interesting what conclusion will result from this.

will be accepting it if this is a non-issue. But would be interesting if there could be anything valuable for the engine development taken/extracted from the premise.

**Comment by AThousandShips** [comment] 2023-03-12 09:32
Making the binary serialisation in 4.x backwards compatible is not likely, it would involve an overhead and also make compatibility breaking changes with 4.0

**Comment by Zireael07** [comment] 2023-03-12 09:33
What "premise of this ticket"? Godot 4 was supposed to break compatibility and it DID so. There is therefore no expectation that you can load variables across different versions.

As for documentation, it does suggest using JSON first and foremost

**Comment by Reneator** [comment] 2023-03-12 09:50
Premise of the ticket is:

There is a specific problem with the migration to godot 4 from godot 3.5.1 to which i didnt find any information or ticket before, so i tried to contribute by posting about it.

If i just wanted to solve this for myself i would have used other channels.

**Comment by AThousandShips** [comment] 2023-03-12 09:51
But you should use other channels to make sure it *is* a bug

**Comment by AThousandShips** [comment] 2023-03-12 10:41
The documentation on binary seralization has to be updated though as it is out of date in regards to the format, will work on that

**Comment by KoBeWi** [comment] 2023-03-12 11:46
Indeed binary formats may be incompatible, but it should work if you use `var2str`.

**Comment by YuriSizov** [comment] 2023-03-13 10:19
This is a duplicate of https://github.com/godotengine/godot/issues/73530, see the comment there (though it's been explained in this discussion more or less already). One thing we should make sure is to mention something about this in the migration guide, if we don't already. Please open a ticket in https://github.com/godotengine/godot-docs.

**Closed** 2023-03-13 10:19 UTC
Labels: discussion, topic:core, documentation
