### ISSUE TITLE
TileMap patterns crash editor in large quantities

### ISSUE THREAD

**Issue by WolfgangSenff** [godotengine/godot#86097] opened 2023-12-12 23:39 UTC
### Tested versions

I tested this in the latest, 4.2.1 release, but I imagine it has been there since 4.0 or so.

### System information

Windows 11, 16 gb RAM, 11th Gen Intel i7

### Issue description

If you add lots of patterns to a single tileset, it does two things:

1. With every new pattern added, it reloads all the patterns in the tileset - and if those patterns are somewhat large, it can take quite some time to reload them.
2. It will sometimes crash if there are a lot of patterns already. Around 50 apparently, or perhaps exactly 50?

### Steps to reproduce

1. Create a project
2. Create a new main scene
3. Add a TileMap node, create a tileset for it, add something with a few tiles you can make patterns out of
4. Go through the process of creating a bunch of patterns
5. At some point, it will start reloading all of the patterns and it'll be obvious - they'll all disappear and then start showing up more slowly
6. At some point, it will crash, and if you haven't saved (possibly even if you have), you will lose all of your hard-earned patterns. The limit on the patterns appears to be around 50, although that might be based on the number of other tiles I have in the tileset, if patterns take up the same space as tiles. 

### Minimal reproduction project (MRP)

No MRP since it's not dependent on the situation at all.

**Comment by ConstantChange** [comment] 2023-12-16 10:32
Working and editing large tilesets seem to crash the engine too.

**Comment by AThousandShips** [comment] 2024-01-22 16:56
Duplicate of https://github.com/godotengine/godot/issues/86226

**Closed by AThousandShips** 2024-01-22 16:56 UTC
Labels: bug, topic:editor, crash, topic:2d

**Comment by WolfgangSenff** [comment] 2024-01-23 02:45
It does seem to fix the crash (tested on the same machine that was borked before)! I did notice however it is still horrendously slow, and it feels like the algorithm just needs to be rethought, perhaps. You can even cause some interesting visual glitches when the patterns get up to a high enough count and then you add patterns to it while it's still reloading them all.

**Comment by AThousandShips** [comment] 2024-01-23 09:16
Not slow for me, but wasn't changed by this PR but instead due to the massive size, please open a new issue report and provide a minimum project to show this issue (couldn't see any glitches or slow processing with the above issue report, which has a project)

**Comment by WolfgangSenff** [comment] 2024-01-23 20:41
I will go ahead and do that, then! It only starts really happening at 50+ patterns, but in any case, I'll save it for the next report.
