### ISSUE TITLE
Nodes in the "Remote" window do not match the node name

### ISSUE THREAD

**Issue by JekSun97** [godotengine/godot#92687] opened 2024-06-02 13:03 UTC
### Tested versions

I checked version 4.2.2 and 4.3 beta1, in 3.5.3 this problem is missing

### System information

Godot v4.3.beta1 - Windows 10.0.19045 - GLES3 (Compatibility) - Radeon RX 560 Series (Advanced Micro Devices, Inc.; 31.0.14001.45012) - Intel(R) Core(TM) i5-4570 CPU @ 3.20GHz (4 Threads)

### Issue description

When scenes are dynamically created, their names do not correspond to their name, instead they use the name of the node type.

3.5.3:
![3 5](https://github.com/godotengine/godot/assets/130399274/42984a2e-91da-4c73-ad29-f9cf68273601)

4.x:
![4 plus](https://github.com/godotengine/godot/assets/130399274/f7479ca6-e5da-4867-a039-011bf9799a8c)

### Steps to reproduce

1. Create a node with a non-standard name and save it.
2. Load this node in any way and add it to the scene as a child node using code.
3. Open the "Remote" tab while the game is running, make sure that the names of the created nodes do not match their names in the file manager.

### Minimal reproduction project (MRP)

[test_for 4.3 beta1.zip](https://github.com/user-attachments/files/15525395/test_for.4.3.beta1.zip)

**Comment by timothyqiu** [comment] 2024-06-02 14:09
This is intended behavior (see [Node.add_child()](https://docs.godotengine.org/en/stable/classes/class_node.html#class-node-method-add-child)).

> If `force_readable_name` is true, improves the readability of the added node. If not named, the node is renamed to its type, and if it shares `name` with a sibling, a number is suffixed more appropriately. This operation is very slow. As such, it is recommended leaving this to false, which assigns a dummy name featuring `@` in both situations.

Pass true for the second parameter if you want the adjusted name to be based on the original one.

**Comment by JekSun97** [comment] 2024-06-02 14:22
@timothyqiu  The second argument in my test project doesn't change anything.

In cases where this problem is fixed, I would suggest changing the second argument to true by default. I often use "Remote" in my projects, and searching by name is quite logical, rather than by type.

**Comment by AThousandShips** [comment] 2024-06-02 14:24
> I would suggest changing the second argument to true by default.

This would break compatibility so won't be possible, it's also undesirable for default performance

**Comment by JekSun97** [comment] 2024-06-02 14:30
Please. Demonstration of the problem with the second argument.
[test3.zip](https://github.com/user-attachments/files/15525655/test3.zip)

**Comment by AThousandShips** [comment] 2024-06-02 14:33
What problem? It worked according to your previous comment? Are you talking about the default value?

**Comment by JekSun97** [comment] 2024-06-02 14:37
> What problem? It worked according to your previous comment? Are you talking about the default value?

Perhaps I am not sufficiently informed about the big changes in the fourth version, and to be honest I’m surprised by this behavior of “Remote”, but I write add_child(scn,true) and add_child(scn,false), nothing changes, the name remains the name of the node type

**Comment by AThousandShips** [comment] 2024-06-02 14:41
The node is just named `Node2D` so what's wrong here? It's named what the node is named?

**Comment by JekSun97** [comment] 2024-06-02 15:01
> The node is just named `Node2D` so what's wrong here? It's named what the node is named?
> 
> ```
> [node name="Node2D" type="Node2D"]
> ```
> 
> You've not named it `Test` like in 3.x

![32](https://github.com/godotengine/godot/assets/130399274/f3a1647d-424d-4500-ab65-205958e57491)

**Comment by JekSun97** [comment] 2024-06-02 15:04
I'm sorry, I renamed the file itself, but not the host name, my fault...

**Comment by AThousandShips** [comment] 2024-06-02 15:31
That would be a lot of extra fragile code instead of just using the function properly, I'm sorry but this isn't really a good change, it's well documented and can't be changed for compatibility, and a project setting would be a significant cost to performance and be confusing

**Comment by JekSun97** [comment] 2024-06-02 15:40
I'm not very well versed in the source code, but this is only one condition, checking the project settings for add_child, compatibility would not be broken if this setting was not found in the project settings, the usual add_child would be used as before

If I migrate my entire old project to version 4, I will have to rewrite all the add_child functions in order to find them quickly in "Remote" and change them for testing

**Comment by AThousandShips** [comment] 2024-06-02 15:47
It would hurt performance since you'd have to check the settings each time the method is called, and it'd be confusing that the argument to the method is ignored if the setting is set, that's not done *anywhere else*

The desired default is to not make the name readable, as explained in the documentation description, if you want it the simple solution is to just set the argument to `true`, this is not a big task

Having to do this when migrating from 3.x is a tiny hurdle compared to *everything else* involved in migrating source, it's nowhere as involved as doing other changes based on names

Further the usage to test things is not really generally how this would be used, you don't have to change the condition back and forth like that, that's not how most people use this AFAIK

But I could be wrong about how likely this is to be relevant, so please open a proposal if you want that feature and that'll let us know if others have the same need for this

**Comment by AThousandShips** [comment] 2024-06-02 16:11
Closing in favor of:
* https://github.com/godotengine/godot-proposals/issues/9873

Thank you for your contribution

**Closed by AThousandShips** 2024-06-02 16:11 UTC
Labels: discussion, topic:editor
