### ISSUE TITLE
Glitchy 3d editing window

### ISSUE THREAD

**Issue by lukostello** [godotengine/godot#35694] opened 2020-01-29 12:59 UTC
**Godot version:**
Godot v3.2.rc4.offical
**OS/device including version:**
Windows 10. CPU: AMD Fx 6300, GPU: NVidea GeForce gtx 750 ti 
**Issue description:**
![editproblem](https://user-images.githubusercontent.com/53994293/73358364-767c9a00-426c-11ea-8b22-8a9a8f62b874.gif)

**Steps to reproduce:**
if you look at any of my 3d assets in editor while zoomed in and rotating, it should reproduce the error. I don't think it is my PC because it works right on some example projects.

**Minimal reproduction project:**
[Gater.zip](https://github.com/godotengine/godot/files/4128054/Gater.zip)

**Comment by MadaraZ** [comment] 2020-01-29 13:49
3.2 stable
linux debian 10, GTS 450
screen Perspective excellent and Orthogonal have problem) same result gles2/gles3

![out](https://user-images.githubusercontent.com/17591539/73361967-07786300-42b7-11ea-8a7e-f07c3e6e046a.gif)

**Comment by Sslaxx** [comment] 2020-01-29 14:51
To be clear, this is in-editor only and not applicable to exported projects?

**Comment by lukostello** [comment] 2020-01-29 15:25
@Sslaxx as far as I can tell. Sorry I wasn't able to give you a version where my code worked so I can show it as working in export. But I have not encountered any error in that dept and I have used both orthographic and perspective camera types while running the game.

**Comment by clayjohn** [comment] 2020-01-29 16:34
I can confirm that it is happening, but only in orthogonal mode.

@lukostello Were you having this issue in 3.1 as well?

If not, https://github.com/godotengine/godot/pull/35406 may be related.

**Comment by GlaDOSik** [comment] 2020-01-29 17:14
I think this is a duplicate of #18809

**Comment by clayjohn** [comment] 2020-01-29 18:35
@GlaDOSik Thanks. It indeed is a duplicate of #18809 Closing in favour of that.

**Closed by clayjohn** 2020-01-29 18:35 UTC
Labels: archived, bug, topic:editor, topic:rendering
