### ISSUE TITLE
Godot crash when disconnecting audio source

### ISSUE THREAD

**Issue by pikmeir** [godotengine/godot#7272] opened 2016-12-09 20:36 UTC
**Operating system or device - Godot version:**
Windows 8.1 64bit Godot 2.1.1 (Steam)

**Issue description** (what happened, and what was expected):
The program will completely crash when disconnecting the current audio device (such as Bluetooth).

**Steps to reproduce:**
Turn on Bluetooth headset/speaker that is connected to the computer. Open Godot. Turn off Bluetooth headset/speaker. Godot crashes.

**Link to minimal example project** (optional but very welcome):

**Comment by xxDeathskillxx** [comment] 2016-12-10 08:47
Same with normal Audio-Jack. After unplugging Godot crashes.

**Comment by bojidar-bg** [comment] 2016-12-11 13:06
Related #1684 and even more to #5211. (and probably duplicate of the latter)

**Comment by timoschwarzer** [comment] 2016-12-14 22:32
Seems like it affects all OSes

**Comment by timoschwarzer** [comment] 2017-05-28 20:05
@bojidar-bg I tried this with 2.1.3-stable and Godot does no longer crash.
So this issue and #5211 can be closed.

**Comment by bojidar-bg** [comment] 2017-05-28 20:19
Assuming fixed then 👍

**Closed by bojidar-bg** 2017-05-28 20:19 UTC
Labels: bug, platform:windows, topic:drivers, topic:porting
