### ISSUE TITLE
Godot freezes when I open a tileset tres file

### ISSUE THREAD

**Issue by linememory** [godotengine/godot#26870] opened 2019-03-10 14:23 UTC
**Godot version:**
3.1 RC1

**OS/device including version:**
Kubuntu 18.10 x86_64 

**Issue description:**
When I try to open a tileset in Godot, it freezes and one core of the CPU goes up to 100% until I kill the process. The tileset works on a Tilemap node.

**Steps to reproduce:**
Open the tileset.tres file from the test project in Godot

**Minimal reproduction project:**
[test.zip](https://github.com/godotengine/godot/files/2949504/test.zip)

**Comment by akien-mga** [comment] 2019-03-10 14:56
Confirmed on Mageia 7 with 59aa79f.

Seems to be some kind of endless loop that then overflows the MessageQueue. This error spam starts after 3-4 seconds of freeze:
```
Failed method: PopupMenu:_update_callback target ID: 54776
TOTAL BYTES: 1048560
NULL count: 0
CALL _update_callback: 28659
CALL _update_minimum_size: 459
CALL _sort_children: 14561
CALL _update_script_names: 1
CALL _test_update_tree: 9
CALL _update_bone_list: 1
ERROR: push_call: Message queue out of memory. Try increasing 'message_queue_size_kb' in project settings.
   At: core/message_queue.cpp:56.
Failed method: ToolButton:_update_callback target ID: 8174
TOTAL BYTES: 1048560
NULL count: 0
CALL _update_callback: 28659
CALL _update_minimum_size: 459
CALL _sort_children: 14561
CALL _update_script_names: 1
CALL _test_update_tree: 9
CALL _update_bone_list: 1
ERROR: push_call: Message queue out of memory. Try increasing 'message_queue_size_kb' in project settings.
   At: core/message_queue.cpp:56.
Failed method: ToolButton:_update_minimum_size target ID: 8174
TOTAL BYTES: 1048560
NULL count: 0
CALL _update_callback: 28659
CALL _update_minimum_size: 459
CALL _sort_children: 14561
CALL _update_script_names: 1
CALL _test_update_tree: 9
CALL _update_bone_list: 1
ERROR: push_call: Message queue out of memory. Try increasing 'message_queue_size_kb' in project settings.
   At: core/message_queue.cpp:56.
Failed method: EditorPropertyVector2:_update_callback target ID: 54778
TOTAL BYTES: 1048560
NULL count: 0
CALL _update_callback: 28659
CALL _update_minimum_size: 459
CALL _sort_children: 14561
CALL _update_script_names: 1
CALL _test_update_tree: 9
CALL _update_bone_list: 1
ERROR: push_call: Message queue out of memory. Try increasing 'message_queue_size_kb' in project settings.
   At: core/message_queue.cpp:56.
Failed method: EditorPropertyVector2:_sort_children target ID: 54778
TOTAL BYTES: 1048560
NULL count: 0
CALL _update_callback: 28659
CALL _update_minimum_size: 459
CALL _sort_children: 14561
CALL _update_script_names: 1
CALL _test_update_tree: 9
CALL _update_bone_list: 1
ERROR: push_call: Message queue out of memory. Try increasing 'message_queue_size_kb' in project settings.
   At: core/message_queue.cpp:56.
Failed method: EditorPropertyVector2:_sort_children target ID: 54778
TOTAL BYTES: 1048560
NULL count: 0
CALL _update_callback: 28659
CALL _update_minimum_size: 459
CALL _sort_children: 14561
CALL _update_script_names: 1
CALL _test_update_tree: 9
CALL _update_bone_list: 1
ERROR: push_call: Message queue out of memory. Try increasing 'message_queue_size_kb' in project settings.
   At: core/message_queue.cpp:56.
Failed method: VBoxContainer:_update_callback target ID: 54779
TOTAL BYTES: 1048560
NULL count: 0
CALL _update_callback: 28659
CALL _update_minimum_size: 459
CALL _sort_children: 14561
CALL _update_script_names: 1
CALL _test_update_tree: 9
CALL _update_bone_list: 1
ERROR: push_call: Message queue out of memory. Try increasing 'message_queue_size_kb' in project settings.
   At: core/message_queue.cpp:56.
Failed method: VBoxContainer:_sort_children target ID: 54779
TOTAL BYTES: 1048560
NULL count: 0
CALL _update_callback: 28659
CALL _update_minimum_size: 459
CALL _sort_children: 14561
CALL _update_script_names: 1
CALL _test_update_tree: 9
CALL _update_bone_list: 1
ERROR: push_call: Message queue out of memory. Try increasing 'message_queue_size_kb' in project settings.
   At: core/message_queue.cpp:56.
Failed method: VBoxContainer:_sort_children target ID: 54779
TOTAL BYTES: 1048560
NULL count: 0
CALL _update_callback: 28659
CALL _update_minimum_size: 459
CALL _sort_children: 14561
CALL _update_script_names: 1
CALL _test_update_tree: 9
CALL _update_bone_list: 1
ERROR: push_call: Message queue out of memory. Try increasing 'message_queue_size_kb' in project settings.
   At: core/message_queue.cpp:56.
Failed method: EditorSpinSlider:_update_callback target ID: 54780
TOTAL BYTES: 1048560
NULL count: 0
CALL _update_callback: 28659
CALL _update_minimum_size: 459
CALL _sort_children: 14561
CALL _update_script_names: 1
CALL _test_update_tree: 9
CALL _update_bone_list: 1
ERROR: push_call: Message queue out of memory. Try increasing 'message_queue_size_kb' in project settings.
   At: core/message_queue.cpp:56.
Failed method: TextureRect:_update_callback target ID: 54781
TOTAL BYTES: 1048560
NULL count: 0
CALL _update_callback: 28659
CALL _update_minimum_size: 459
CALL _sort_children: 14561
CALL _update_script_names: 1
CALL _test_update_tree: 9
CALL _update_bone_list: 1
ERROR: push_call: Message queue out of memory. Try increasing 'message_queue_size_kb' in project settings.
   At: core/message_queue.cpp:56.
Failed method: LineEdit:_update_callback target ID: 54782
cTOTAL BYTES: 1048560
NULL count: 0
CALL _update_callback: 28659
CALL _update_minimum_size: 459
CALL _sort_children: 14561
CALL _update_script_names: 1
CALL _test_update_tree: 9
CALL _update_bone_list: 1
ERROR: push_call: Message queue out of memory. Try increasing 'message_queue_size_kb' in project settings.
   At: core/message_queue.cpp:56.
Failed method: PopupMenu:_update_callback target ID: 54784
TOTAL BYTES: 1048560
NULL count: 0
CALL _update_callback: 28659
CALL _update_minimum_size: 459
CALL _sort_children: 14561
CALL _update_script_names: 1
CALL _test_update_tree: 9
CALL _update_bone_list: 1
ERROR: push_call: Message queue out of memory. Try increasing 'message_queue_size_kb' in project settings.
   At: core/message_queue.cpp:56.
Failed method: EditorSpinSlider:_update_callback target ID: 54786
TOTAL BYTES: 1048560
NULL count: 0
CALL _update_callback: 28659
CALL _update_minimum_size: 459
CALL _sort_children: 14561
CALL _update_script_names: 1
CALL _test_update_tree: 9
CALL _update_bone_list: 1
ERROR: push_call: Message queue out of memory. Try increasing 'message_queue_size_kb' in project settings.
   At: core/message_queue.cpp:56.
Failed method: TextureRect:_update_callback target ID: 54787
TOTAL BYTES: 1048560
NULL count: 0
CALL _update_callback: 28659
CALL _update_minimum_size: 459
CALL _sort_children: 14561
CALL _update_script_names: 1
CALL _test_update_tree: 9
CALL _update_bone_list: 1
ERROR: push_call: Message queue out of memory. Try increasing 'message_queue_size_kb' in project settings.
   At: core/message_queue.cpp:56.
Failed method: LineEdit:_update_callback target ID: 54788
TOTAL BYTES: 1048560
NULL count: 0
CALL _update_callback: 28659
CALL _update_minimum_size: 459
CALL _sort_children: 14561
CALL _update_script_names: 1
CALL _test_update_tree: 9
CALL _update_bone_list: 1
ERROR: push_call: Message queue out of memory. Try increasing 'message_queue_size_kb' in project settings.
   At: core/message_queue.cpp:56.
Failed method: PopupMenu:_update_callback target ID: 54790
TOTAL BYTES: 1048560
NULL count: 0
CALL _update_callback: 28659
CALL _update_minimum_size: 459
CALL _sort_children: 14561
CALL _update_script_names: 1
CALL _test_update_tree: 9
CALL _update_bone_list: 1
ERROR: push_call: Message queue out of memory. Try increasing 'message_queue_size_kb' in project settings.
   At: core/message_queue.cpp:56.
Failed method: EditorPropertyResource:_update_callback target ID: 54792
TOTAL BYTES: 1048560
NULL count: 0
CALL _update_callback: 28659
CALL _update_minimum_size: 459
CALL _sort_children: 14561
CALL _update_script_names: 1
CALL _test_update_tree: 9
CALL _update_bone_list: 1
ERROR: push_call: Message queue out of memory. Try increasing 'message_queue_size_kb' in project settings.
   At: core/message_queue.cpp:56.
<ad lib>
```

**Comment by zzz-assault** [comment] 2019-03-10 20:16
**Windows 10 (64 bit) and 64 bit Godot 3.1 RC1**

No crash @ Microsoft OS.

**Comment by Ranoller** [comment] 2019-03-10 20:29
Well... in the error is the solution.... a big tileset? , try to increasing "message_queue_size_kb" in project settings. Probably not a bug.

**Comment by MarianoGnu** [comment] 2019-03-12 12:50
The editor hangs in this loop, i could not confirm a CRC, looks like it's just the time it needs to process every property of all 1023 tiles:
![image](https://user-images.githubusercontent.com/1776044/54201385-4689a400-44ac-11e9-9200-eb8a2506535f.png)

**Comment by MarianoGnu** [comment] 2019-03-12 13:01
i confirmed that there's no CRC, godot just needs this time to create controls for 19465 properties **cheers**

**Comment by MarianoGnu** [comment] 2019-03-12 13:06
the solution for this is in part removing unneded properties, but also display information in pages, like arrays does:
![image](https://user-images.githubusercontent.com/1776044/54202299-7c2f8c80-44ae-11e9-848b-622bbb3749df.png)

**Comment by akien-mga** [comment] 2020-01-14 23:43
Duplicate of #29238.

**Closed by akien-mga** 2020-01-14 23:43 UTC
Labels: bug, confirmed, topic:editor
