### ISSUE TITLE
"Direction" property for Particles is missing

### ISSUE THREAD

**Issue by vybr** [godotengine/godot#13492] opened 2017-12-01 21:36 UTC
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Godot 3.0 Beta - Windows

**Issue description:**

It's no longer possible to specify the direction of Initial Velocity for particles it seems. I have to rotate the Particles2D object itself and change the particle angle to offset this. If I'm using gravity I also have to alter this based on whatever rotation I am currently using. It's really quite cumbersome.
Could this property be added back please? It's quite important for users who make heavy use of particles, like me.

**Comment by noidexe** [comment] 2017-12-21 14:42
@vybr you can set Local Coords to false as a temporary workaround to avoid having to alter the gravity vector every time you rotate the particles2d object.

**Comment by akien-mga** [comment] 2018-01-05 14:26
We have now entered release freeze for Godot 3.0 and want to focus only on release critical issues for that milestone. Therefore, we're moving this issue to the 3.1 milestone, though a fix may be made available for a 3.0.x maintenance release after it has been tested in the master branch during 3.1 development. If you consider that this issue is critical enough to warrant blocking the 3.0 release until fixed, please comment so that we can assess it more in-depth.

**Comment by arccoza** [comment] 2018-01-25 01:47
I just ran into this, and it does throw you. The first thing you look to do after creating an emitter is point it somewhere, and when Godot 2.x had `direction` and the 3.x [docs](http://docs.godotengine.org/en/latest/learning/features/2d/particle_systems_2d.html#particlesmaterial-settings) talk about `direction` in `ParticlesMaterial`, only for it to be absent in code is confusing and frustrating. This doesn't seem like a feature request, but a bug fix for a regression.

I understand that the particle system is marked for replacement with something shinier in 3.1, and I'm looking forward to those features, but for now this limits what can be done with particles without non-obvious workarounds, for a fairly fundamental feature.

Fixes:
* Best option: Actually reinstate direction either in the node or the `ParticlesMaterial` resource, (or maybe make `initial_velocity` a vector).
* Quickest option: Update the docs with a note about the missing feature and workarounds; such as rotating the emitter and manually adjusting the gravity vector, or disabling `local_coords`, with caveats.

**Comment by GammaGames** [comment] 2018-05-01 03:09
If this is an enhancement (as the issue is tagged) then the documentation should be updated to not list the setting. 
If this is a bug, which it is, then the docs should have a note that it is currently not available in the build, with the note removed when the bug has been fixed.

**Comment by akien-mga** [comment] 2018-05-02 08:20
@GammaGames A missing feature is not a bug, it's a missing feature. Otherwise all issues could be labeled as "bug". Once the feature is implemented, it will enhance the existing features of Particles.

**Comment by akien-mga** [comment] 2018-05-02 20:49
Done: https://github.com/godotengine/godot-docs/commit/a85c3956c12a2aea6ad22765141491c2921360ba

**Comment by Zylann** [comment] 2018-11-04 23:49
Bumped into this too, it's also really annoying because rotating the whole Particles2D node also rotates the emission shape.

**Comment by reduz** [comment] 2019-01-18 20:13
Not a bug so I wont work on it before 3.1, but if anyone wants to give it a try feel free

**Comment by terepaii** [comment] 2019-02-02 17:57
If nobody's working on this, mind if I take a stab?

**Comment by serados** [comment] 2019-02-25 15:33
Hi @terepaii, are there any updates on your progress? I'm interested in giving this a go as well.

**Comment by terepaii** [comment] 2019-02-25 21:23
@serados I've made only a small bit of progress. Feel free to make a PR though. Not sure when I can take a look at this again.

**Closed** 2019-07-02 09:33 UTC
Labels: enhancement, hero wanted!, junior job, topic:rendering, usability
