### ISSUE TITLE
Crashed right after dragging the image to animation tab

### ISSUE THREAD

**Issue by quangcrazymen** [godotengine/godot#72712] opened 2023-02-04 14:33 UTC
### Godot version

4.0 dev (1ed549e)

### System information

Linux mint 20.3 Cinnamon 5.2.7 Intel core i5-7300HQ GTX-1060 Mobile 6gb

### Issue description

![image](https://user-images.githubusercontent.com/80439365/216772734-4c1a856e-ed3c-4461-af67-dd71bc485eaf.png)

### Steps to reproduce

Crashed right after dragging the image to animation tab

### Minimal reproduction project

[project.zip](https://github.com/godotengine/godot/files/10608864/project.zip)

**Comment by YuriSizov** [comment] 2023-03-09 18:03
As mentioned above it's currently impossible to reproduce this issue because there isn't enough information and the MRP is not an actual project. I'm going to close this report, but if you can provide more information and a better demonstration of the problem that leads to a crash, we can reopen it.

**Closed by YuriSizov** 2023-03-09 18:03 UTC
Labels: bug, topic:editor, needs testing, crash, topic:animation
