### ISSUE TITLE
New Camera2D instance doesn't control view

### ISSUE THREAD

**Issue by nezvers** [godotengine/godot#72697] opened 2023-02-04 00:37 UTC
### Godot version

4.0, Beta 17

### System information

Windows, Compatibility

### Issue description

Spawning a new Camera2D in place while the previous one isn't freed yet, breaks the ability to control the view.
Previously setting `current` was a great way to force a new Camera to take over the control.
Now the only way to make it work is to delay spawning to the next `process_frame`. That creates problems with scene transition control.
Delaying set `enabled = true` also doesn't work on the new camera.

### Steps to reproduce

- Have a Camera2D in the scene
- trigger `queue_free()` on it
- spawn a new Camera2D
- the new camera doesn't control the view

### Minimal reproduction project

[Camera2d position.zip](https://github.com/godotengine/godot/files/10593528/Camera2d.position.zip)
Example:
`Main` node options to wait for `process_frame` to spawn new Camera2D. Also, remove reference to the existing camera to test coexistence.
`Camera2D` scene to test setting new as enabled and waiting for `process_frame` to set it.

**Comment by KoBeWi** [comment] 2023-02-04 09:42
Duplicate of #72529
There is a workaround in the issue, until beta 18.

**Closed by KoBeWi** 2023-02-04 09:42 UTC

**Comment by nezvers** [comment] 2023-02-04 09:46
My bad, I didn't notice that there is introduced a method `make_current( )`.
That seems to be working.
