### ISSUE TITLE
ARM64V8 build error

### ISSUE THREAD

**Issue by dankan1890** [godotengine/godot#33679] opened 2019-11-17 16:32 UTC
**Godot version:**
v3.2.beta.custom_build.d75b43e96

**OS/device including version:**
Windows 10 1903

**Issue description:**
As the title suggests, the compilation ends with the following error:

> =====
> b"modules\\libmodules.android.opt.debug.armv8.a(opus_decoder.android.opt.debug.armv8.o): In function `opus_decoder_init':\r\nopus_decoder.c:(.text.opus_decoder_init+0x180): undefined reference to `opus_select_arch'\r\nmodules\\libmodules.android.opt.debug.armv8.a(celt_decoder.android.opt.debug.armv8.o): In function `celt_decoder_init':\r\ncelt_decoder.c:(.text.celt_decoder_init+0x9c): undefined reference to `opus_select_arch'\r\nmodules\\libmodules.android.opt.debug.armv8.a(pitch.android.opt.debug.armv8.o): In function `pitch_search':\r\npitch.c:(.text.pitch_search+0x4a8): undefined reference to `CELT_PITCH_XCORR_IMPL'\r\npitch.c:(.text.pitch_search+0x4ac): undefined reference to `CELT_PITCH_XCORR_IMPL'\r\nmodules\\libmodules.android.opt.debug.armv8.a(celt_lpc.android.opt.debug.armv8.o): In function `_celt_autocorr':\r\ncelt_lpc.c:(.text._celt_autocorr+0x258): undefined reference to `CELT_PITCH_XCORR_IMPL'\r\ncelt_lpc.c:(.text._celt_autocorr+0x25c): undefined reference to `CELT_PITCH_XCORR_IMPL'\r\nmodules\\libmodules.android.opt.debug.armv8.a(init_decoder.android.opt.debug.armv8.o): In function `silk_init_decoder':\r\ninit_decoder.c:(.text.silk_init_decoder+0x24): undefined reference to `opus_select_arch'\r\nclang++: error: linker command failed with exit code 1 (use -v to see invocation)\r\n"
=====

**Steps to reproduce:**
scons platform=android target=release_debug android_arch=arm64v8 -j4
scons platform=android target=release android_arch=arm64v8 -j4

**Minimal reproduction project:**

**Comment by Calinou** [comment] 2019-11-17 17:36
Duplicate of #33606.

**Closed by Calinou** 2019-11-17 17:36 UTC

**Comment by dankan1890** [comment] 2019-11-17 18:25
Oops ... sorry, I searched for "arm" and didn't see that issue.
My bad
