### ISSUE TITLE
Errors when open a project using Godot physics.

### ISSUE THREAD

**Issue by madmiraal** [godotengine/godot#42455] opened 2020-10-01 09:38 UTC
**Godot version:**
master and 3.2.3-stable

**OS/device including version:**
Ubuntu 20.04

**Issue description:**
When running Godot from a command console and opening a project that uses Godot Physics, the following error messages are printed to the command console:
```
ERROR: Condition "!shape->is_configured()" is true. Returning: Variant()
   at: shape_get_data (servers/physics_3d/physics_server_3d_sw.cpp:109)
ERROR: CylinderShape3D is not supported in GodotPhysics3D. Please switch to Bullet in the Project Settings.
   at: shape_create (servers/physics_3d/physics_server_3d_sw.cpp:65)
ERROR: Condition "!shape" is true.
   at: shape_set_data (servers/physics_3d/physics_server_3d_sw.cpp:90)
ERROR: Invalid ID.
   at: free (servers/physics_3d/physics_server_3d_sw.cpp:1281)
ERROR: Condition "!d.has("cell_size")" is true.
   at: set_data (servers/physics_3d/shape_3d_sw.cpp:1491)
ERROR: Condition "!body" is true.
   at: body_attach_object_instance_id (servers/physics_3d/physics_server_3d_sw.cpp:611)
ERROR: Invalid ID.
   at: free (servers/physics_3d/physics_server_3d_sw.cpp:1281)
```

**Steps to reproduce:**
Run Godot from a command prompt.
Create a project, set Project Settings -> Physics -> 3D -> Physics Engine to GodotPhysics
Save, close and reopen the project.

**Minimal reproduction project:**
4.0: [GodotPhysicsErrors-4.0.zip](https://github.com/godotengine/godot/files/5310896/GodotPhysicsErrors-4.0.zip)
3.2: [GodotPhysicsErrors-3.2.zip](https://github.com/godotengine/godot/files/5310900/GodotPhysicsErrors-3.2.zip)

Note: The error messages are created when calling `doc->generate(true);` in `EditorHelp::generate_doc()`:
https://github.com/godotengine/godot/blob/894b0a010bd3617ae09baa3b571d60154b9877e1/editor/editor_help.cpp#L1532-L1534

**Comment by akien-mga** [comment] 2020-10-01 10:05
Interesting timing as I was reviewing it just an hour ago :) Duplicate of #32216.

**Closed by akien-mga** 2020-10-01 10:05 UTC
Labels: bug, topic:editor, topic:physics

**Comment by madmiraal** [comment] 2020-10-01 10:13
It's not really a duplicate of #32216, because one doesn't have to disable the Bullet module to receive the errors, just enable Godot physics.

**Comment by akien-mga** [comment] 2020-10-01 10:21
It's still the same issue, it happens when bullet is disabled because that forces GodotPhysics on :)
But I see you edited the title of #32216 accordingly.
