### ISSUE TITLE
Spatial translation not updating transform in inspector

### ISSUE THREAD

**Issue by DGWana** [godotengine/godot#20378] opened 2018-07-23 12:23 UTC
**Godot version:**
Godot 3.1 17b44e44b9a34e540cf48ee0a7335ecefcd0c3b7

**OS/device including version:**
Windows 64-bits

**Issue description:**
When changing the translation, rotation or scale of a spatial node in the inspector, the transform values doesn't update. Visually the node updates correctly. If transform is changed, the corresponding values (translation, rotation or scale) change correctly in the inspector.
![spatial](https://user-images.githubusercontent.com/29492561/43076138-8ab25742-8e83-11e8-8c53-cf6fa913b1c6.png)

**Steps to reproduce:**
Just change the position (or rotation or scale) values of a Spatial node

**Comment by DualMatrix** [comment] 2018-09-24 16:45
Duplicate of #10574

**Closed** 2018-09-24 16:48 UTC
