### ISSUE TITLE
Video player still not working

### ISSUE THREAD

**Issue by ajk2196** [godotengine/godot#52580] opened 2021-09-11 18:57 UTC
### Godot version

3.3 stable

### System information

Windows 10, Ryzen 3700x, 2x RTX 2070 supers

### Issue description

Hello,

It is still difficult to play videos using Video player in Godot 3.3. I even tried it to all other formats (like .ogv) as mentioned in many other similar discussions, but it just doesn't play the video. The app starts, shows a black screen, and quits by itself without giving any error or playing anything on the screen. It is literally shameful for us to not have a feature for playing videos in game. If you research it, this issue has been pending since long, from like Godot v3.2.

### Steps to reproduce

Add 2D node to an empty scene.
Add Video Player node to it.
Respect the limitations before adding the video to its 'Stream' field: Size less than 20Mb. (We also need to work to remove this size limit.)
Add the video to 'stream' field.
Play the scene.
See the scene start and quit within 5 seconds.

**Comment by Calinou** [comment] 2021-09-11 21:27
Duplicate of https://github.com/godotengine/godot/issues/50862, https://github.com/godotengine/godot/issues/37211 and likely others.


Please don't open duplicate issues to raise attention on an existing bug. Remember that the goal for Godot 4.0 is to move video playback out of core and into GDExtensions to resolve issues related to the complexity of handling video playback in a game engine.

**Closed by Calinou** 2021-09-11 21:27 UTC
