### ISSUE TITLE
GridMap editor acts bizzare if parent node is transformed

### ISSUE THREAD

**Issue by SuperUserNameMan** [godotengine/godot#906] opened 2014-11-25 14:14 UTC
Hi again,
I'm using November 13 version, windows 64.

If I try to edit the tiles of a GridMap whose Spatial parent node is translated or rotated, there is a distance between the "tile cursor" and the mouse cursor.
New tiles appear to be placed where the "tile cursor" is displayed in the editor, but when I run the scene, they are displayed where the mouse cursor was when I clicked to add them.
All the new tiles I added get moved to somewhere else if I modify the transformations of the parent node, or if I reload the scene into the editor.

**Comment by kubecz3k** [comment] 2015-11-02 09:47
Archiving this one since it's duplicate of https://github.com/godotengine/godot/issues/2668 and that one is tested in newest godot builds and is already confirmed.

**Closed by kubecz3k** 2015-11-02 09:47 UTC
Labels: archived, bug, topic:editor
