### ISSUE TITLE
_enum_values warning

### ISSUE THREAD

**Issue by BastiaanOlij** [godotengine/godot#7456] opened 2017-01-07 07:27 UTC
@reduz I'm getting a lot of these warnings compiling:
In file included from drivers/gles3/rasterizer_scene_gles3.h:14:
./drivers/gles3/shaders/exposure.glsl.h:140:27: warning: unused variable '_enum_values' [-Wunused-variable,30]
                static const EnumValue *_enum_values=NULL;
                                         ^
./drivers/gles3/shaders/exposure.glsl.h:139:22: warning: unused variable '_enums' [-Wunused-variable,30]
                static const Enum *_enums=NULL;

Are _enums and _enum_values really unused and can they be removed? I'll spend the time clearing them out if they are old stuff..

**Comment by akien-mga** [comment] 2017-12-10 14:57
Duplicate of #5534.

**Closed by akien-mga** 2017-12-10 14:57 UTC
Labels: topic:rendering
