### ISSUE TITLE
AnimationPlayer Step value can cause issues when starting another Animation from Track

### ISSUE THREAD

**Issue by jesperkondrup** [godotengine/godot#27459] opened 2019-03-27 15:33 UTC
Windows 10 and Linux, Godot 3.1 stable

So this is a really wierd issue. But we found out (after a good long hour) that the step value which has a default value of 0.1 is actually influencing how the Animation is played.

Reproduce simply by:
1. Make a sprite and an animation player. Make the sprite rotate (or something similar) and set the animation to loop and 1 second.
2. Make a new animationplayer thats also 1 second and start the first animation 0.5 seconds in.
3. Keep pressing "Play animation from start" button.

If the step value is set to 0.1 it will work every time and the looping animation will start perfectly and keep playing. But if the value is 0.01 then the looping animation will only work sporadically.

It seems wierd that this value has any influence over how the animation is playing?

![image](https://user-images.githubusercontent.com/24936603/55088359-e863e000-50ab-11e9-8e7c-d8e3d25a8626.png)

**Comment by Keetz** [comment] 2019-03-27 15:34
Can confirm.

Linux Mint 18.3 Sylvia 64 bit

**Comment by avencherus** [comment] 2019-03-28 07:05
@reduz Might this be in the area of this issue:  https://github.com/godotengine/godot/issues/25245

**Comment by akien-mga** [comment] 2020-01-15 11:46
I've tried to reproduce the issue but I'm not 100% sure that I understood how to do it. Everything seems to play back the same regardless of the step for me.

Could you provide an example project if it's still reproducible in latest 3.2 builds?

**Comment by jesperkondrup** [comment] 2020-01-16 07:54
@akien-mga I am not able to reproduce it either, it seems to work perfectly now.

I imported my old test project (that I described in the issue) and I could see that the way the AnimationPlayer usually works had been changed. 

- In the current version of godot 3.1.2 you can start a looping animation from another AnimationPlayer and it will continue looping in the editor even when the AnimationPlayer has finished.

- But in the new 3.2 beta 6 it works differently. in 3.2 the looping animation stops when the AnimationPlayer is done playing. Also you can now drag the time slider to see how the looping animation looks at a certain frame, which is a very nice feature.

We got a bit worried for a second because the aniamtion stops in the editor, but when we tried playing the scene it looped perfectly :)

**Comment by akien-mga** [comment] 2020-01-16 08:34
> We got a bit worried for a second because the aniamtion stops in the editor, but when we tried playing the scene it looped perfectly :)

Yeah I'm not sure if it's a bug or intended, but might be worth discussing in a new issue.

Good to hear that the original bug of this issue is fixed, so closing.

**Closed by akien-mga** 2020-01-16 08:34 UTC
Labels: bug, topic:core
