### ISSUE TITLE
"Clip Children" doesn't work like before

### ISSUE THREAD

**Issue by Banduck** [godotengine/godot#75761] opened 2023-04-06 16:31 UTC
### Godot version

v4.0.1.stable.official [cacf49999]

### System information

Windows 10

### Issue description

In Godot v4.0.stable.official [92bee43ad], this was possible:
ColorRect1: Clip + Draw
ColorRect2: Clip Only

<img width="660" alt="Godot4_DsWnN1m24C" src="https://user-images.githubusercontent.com/42905358/230429760-188fcdd6-0d2f-412e-ac15-2a48d7b66ac7.png">

but in v4.0.1.stable.official [cacf49999] and v4.0.2.stable.official [7a0977ce2], nothing happens:

<img width="662" alt="Godot_v4 0 1-stable_win64_2Jaq3wTlrn" src="https://user-images.githubusercontent.com/42905358/230430090-f89f86b1-1554-4706-bf66-d1c2b1a79899.png">

### Steps to reproduce

Create a large ColorRect1 and a smaller ColorRect2 as child.
ColorRect1: Clip + Draw
ColorRect2: Clip Only

### Minimal reproduction project

[clip_children.zip](https://github.com/godotengine/godot/files/11172356/clip_children.zip)

**Comment by clayjohn** [comment] 2023-04-06 16:39
Unfortunately the behaviour in 4.0.stable was actually a bug and it did not work like that consistently. The behaviour in 4.0.1 is the correct behaviour, Nodes with ``clip_children`` cannot be nested under other nodes with ``clip_children``. 

Accordingly, this is a duplicate of https://github.com/godotengine/godot/issues/75042

Also note, there is a PR to add nesting to clip_children that I believe would restore the previous behaviour you observed, but would do so in a way that didn't break 50% of the time https://github.com/godotengine/godot/pull/74859

**Closed by clayjohn** 2023-04-06 16:39 UTC
