### ISSUE TITLE
Basis and Quat missing constructor that accepts euler angles in C#

### ISSUE THREAD

**Issue by mysticfall** [godotengine/godot#17198] opened 2018-03-03 00:27 UTC
**Godot version:**
`master` / 3d03bcd0636aacfe530c52fc1cdc32c2edffea04

**OS/device including version:**
_Manjaro Linux 17.1_

**Issue description:**
According to the documentation and #10721, it seems that `Basis` should have a constructor that accepts euler angles as `Vector3` but it is not the case with the C# binding.

The same goes for `Quat`, which should have `new Quat(Vector3 from)` according to the API reference for GDScript.

**Comment by Vega-KH** [comment] 2018-04-23 17:04
It appears that the ```Basis (Vector3 from)``` constructor that is available in GDScript just returns the result of ``` Basis->set_euler_xyz(const Vector3 &p_euler) ``` from matrix3.cpp.  But looking at that, I realize that the C# API is also missing that function.  Lots of Euler functions are missing in the C# API like:

set_euler_xyz
set_euler_yxz
get_euler_xyz
get_euler_yxz
get_rotation
get_rotation_axis_angle

And probably a few more.  At least some of these are important and need to be added to the API before 3.1.

**Comment by Giacom** [comment] 2019-04-06 21:53
Quat is also missing the euler constructor in GDScript 3.1 stable

```GDScript
var test := Quat(Vector3(0, 0, 0))
```

>Invalid arguments for 'Quat' constructor

**Comment by fossegutten** [comment] 2019-04-18 14:54
Same as Giacom. I get this error when trying to construct Quaternion from euler angle: "Invalid call. Nonexistent 'Quat' constructor."

**Comment by kmare** [comment] 2019-05-12 00:22
Yeah, I just noticed that GDscript is missing the constructor with the euler angle (Godot 3.1.1). Is it an omission or something we're supposed to avoid? (using euler for rotations etc)

**Comment by vybr** [comment] 2019-06-05 00:50
Seems like an omission. If it isn't, the constructor should be removed from the class reference.

**Comment by bojidar-bg** [comment] 2019-06-05 11:54
Duplicate of #28086?

**Comment by aaronfranke** [comment] 2019-12-03 04:54
This has already been fixed a long time ago. Basis: https://github.com/godotengine/godot/pull/18974 Quat: https://github.com/godotengine/godot/pull/21205

**Closed** 2019-12-03 06:53 UTC
Labels: enhancement, topic:mono
