### ISSUE TITLE
Suggestion: Allow access to the Editor Settings from the project list

### ISSUE THREAD

**Issue by exts** [godotengine/godot#20027] opened 2018-07-08 00:10 UTC
**Godot version:**
All

**OS/device including version:**
All

**Issue description:**
In my opinion I think you should be allowed to access the editor settings from the project list. An instance where this would be useful is changing the default project path (for creating projects) outside of a project. There's also a few other settings that could be useful for accessing outside of the project setup.

Not a huge suggestion, very minor/low priority suggestion, but I think it could be useful.

**Comment by vnen** [comment] 2018-07-08 03:28
Duplicate of #2771

**Closed by vnen** 2018-07-08 03:28 UTC
