### ISSUE TITLE
[4.3] NoiseTexture2D & FastNoiseLite not updating in Web exports

### ISSUE THREAD

**Issue by Pizza-Script** [godotengine/godot#97350] opened 2024-09-23 07:32 UTC
### Tested versions

- reproducible in: v4.3.stable.official [77dcf97d8]
- not reproducible in: v4.2.stable.official [46dc27791]

### System information

Godot v4.3.stable - Windows 10.0.19045 - GLES3 (Compatibility) - NVIDIA GeForce GTX 1660 SUPER (NVIDIA; 32.0.15.6109) - 11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz (16 Threads)

### Issue description

Editing NoiseTexture2D & FastNoiseLite through code is not reflected in Web export in 4.3.

Works correctly in Windows export and 4.2 Web exports.

### Steps to reproduce

simply edit NoiseTexture2D & FastNoiseLite through code

### Minimal reproduction project (MRP)

[4.3] - https://quietgodot.itch.io/resource-43-web
[4.3.zip](https://github.com/user-attachments/files/17093989/4.3.zip)

[4.2] - https://quietgodot.itch.io/resource-42-web
[4.2.zip](https://github.com/user-attachments/files/17093982/4.2.zip)

<KEY_SPACE> to randomize fast_noise_lite.noise_type
<KEY_T> to toggle noise_texture.invert

**Comment by tetrapod00** [comment] 2024-09-23 08:04
NoiseTexture2D [uses threads](https://docs.godotengine.org/en/stable/classes/class_noisetexture2d.html#description), and 4.3 introduced [single-threaded web export](https://godotengine.org/article/progress-report-web-export-in-4-3/#single-threaded-web-export). Possibly related, either by you exporting single-threaded in 4.3, or some bug introduced by single-threaded export?

**Comment by Pizza-Script** [comment] 2024-09-23 08:11
> NoiseTexture2D [uses threads](https://docs.godotengine.org/en/stable/classes/class_noisetexture2d.html#description), and 4.3 introduced [single-threaded web export](https://godotengine.org/article/progress-report-web-export-in-4-3/#single-threaded-web-export). Possibly related, either by you exporting single-threaded in 4.3, or some bug introduced by single-threaded export?

Thank you, that seems to be it! Enabling 'Thread Support' in the web export have fixed the issue - https://quietgodot.itch.io/resource-43-web-thread

Although I'm not sure if this is considered a bug? Or maybe just an update to the docs to warn about this?

**Comment by tetrapod00** [comment] 2024-09-23 08:19
The docs should be changed. [Exporting for Web](https://docs.godotengine.org/en/stable/tutorials/export/exporting_for_web.html) should mention the single-threaded export somewhere. 

I believe that NoiseTexture2D already sufficiently documents the fact that it uses threads, but perhaps improvements can be made.

**Comment by akien-mga** [comment] 2024-09-23 08:20
Duplicate of #96098, already fixed for 4.3.1.

**Closed by akien-mga** 2024-09-23 08:20 UTC
