### ISSUE TITLE
Vulkan: LightmapProbes only bake indirect light

### ISSUE THREAD

**Issue by ghost** [godotengine/godot#40181] opened 2020-07-07 16:57 UTC
**Godot version:**
master (d0e0a19)

**OS/device including version:**
NVIDIA GeForce GTX 1060 6GB
Driver 451.48
Windows 10 Home
Backend: Vulkan

**Issue description:**
LightmapProbes disregard DirectionalLight3Ds, instead baking only indirect light. The lightmap itself does bake DirectionalLight3Ds, however the LightmapProbes that are generated only bake indirect light.

**Steps to reproduce:**
Create a test scene which contains a BakedLightmap node and meshes with a UV2 channel for lightmap baking. Create a DirectionalLight3D and set its bake mode to Static. View the lightmap probes and see how they only have indirect lighting data and not direct lighting data.

*Bugsquad edit (keywords for easier searching): LightmapGI*

**Comment by Mobs1024** [comment] 2021-07-04 18:12
Godot version: 5c3055e0fe363e08e8cdd3f922313ec9dacfaf43
Linux , RX5500XT (Mesa 21.1.3)

LightmapProbe does not work on the cube ignore in indirect light apparently does not work

![image](https://user-images.githubusercontent.com/17591539/124395085-d9e4e400-dd0a-11eb-990b-36dfee21c936.png)

[TestLightmapProbe.tar.gz](https://github.com/godotengine/godot/files/6760375/TestLightmapProbe.tar.gz)

**Comment by Calinou** [comment] 2021-07-04 18:21
Note that this behavior may also be pressent in `3.x`. However, in `3.x`, lights with the bake mode set to **All** will light up dynamic objects so that they can receive direct light (and receive shadows from other objects, including baked ones).

**Comment by Calinou** [comment] 2023-03-15 22:07
- Duplicate of https://github.com/godotengine/godot/issues/57890 (same cause).

**Closed by Calinou** 2023-03-15 22:07 UTC
Labels: bug, topic:rendering, confirmed, topic:3d
