### ISSUE TITLE
godot with mono crash when open a new project

### ISSUE THREAD

**Issue by jerrychoux** [godotengine/godot#73021] opened 2023-02-10 03:21 UTC
### Godot version

master (929ee611)

### System information

Windows 11, 22H2, 11th Gen Intel(R) Core(TM) i5-11400, 16.0 GB RAM, Interl UHD Graphics

### Issue description

clone the last commit in master, and compile with mono, godot crash when open a new project.

### Steps to reproduce

scons -j6 platform=windows module_mono_enabled=yes mono_glue=no
./bin/godot.windows.editor.x86_64.mono --generate-mono-glue modules/mono/glue
scons -j6 platform=windows target=release_debug module_mono_enabled=yes

godot can startup, but crash when new a project and open it

![screenshot-20230210-110737](https://user-images.githubusercontent.com/37604487/217991926-982ed66e-f63b-4e8e-848e-1e53824245a3.png)

### Minimal reproduction project

[test.zip](https://github.com/godotengine/godot/files/10703373/test.zip)

**Comment by raulsntos** [comment] 2023-02-10 04:04
Duplicate of https://github.com/godotengine/godot/issues/72891

**Closed by raulsntos** 2023-02-10 04:04 UTC
