### ISSUE TITLE
Flipped tiles wobble when "Snap 2D Vertices to Pixel" is true in 4.3

### ISSUE THREAD

**Issue by svendixon** [godotengine/godot#96256] opened 2024-08-29 02:53 UTC
### Tested versions

- Reproduceable in: 4.3
- Not Reproduceable in: 4.2.2

### System information

Windows 11 - Godot v4.3.stable - Vulkan (Forward+) - dedicated

### Issue description

Flipped tiles wobble when in a pixel perfect setup in 4.3. The issue does not appear to happen in 4.2.2. 

![flipped_tiles_wobble](https://github.com/user-attachments/assets/93035150-cd55-4cbc-b43b-0e392ea141b5)

In the video below the diagonals are flipped both vertically and horizontally. And you can see a gaps as well as double pixels appearing. The original diagonal which is not flipped looks fine. 

https://github.com/user-attachments/assets/4d126f59-7eb4-4692-ad29-8614b3f21a79

In 4.2 it doesn't happen.

https://github.com/user-attachments/assets/202c0b5a-26f2-4cbd-a270-aedc2ab1c686

However if you leave `Snap 2D Transforms to Pixel` on and turn off `Snap 2D Vertices to Pixel`, it seems the problem is resolved. So it's not a big deal. But I figured I'd post this, since flipped tiles are not behaving the same as the original tiles with this setting on.

### Steps to reproduce

Create a project with a tile map layer and assign a tile set with a tile and flip it. (example projects below)

Projects settings:

Display:
- Window Size = 640x360
- Window Width Override = 1280x720
- Stretch Mode = viewport
- Scale Mode = integer

Rendering:
- Default Texture Filter = Nearest
- Snap 2D Transforms to Pixel = True
- Snap 2D Vertices to Pixel = True

### Minimal reproduction project (MRP)

4.3 Project - [flipped_tiles_wobble_4_3.zip](https://github.com/user-attachments/files/16791233/flipped_tiles_wobble_4_3.zip)
4.2.2 Project - [flipped_tiles_wobble_4_2.zip](https://github.com/user-attachments/files/16791197/flipped_tiles_wobble_4_2.zip)

**Comment by akien-mga** [comment] 2024-08-29 08:33
CC @adamscott @markdibarry

**Comment by markdibarry** [comment] 2024-08-29 13:37
I believe this is a duplicate of https://github.com/godotengine/godot/issues/95571, but feel free to correct me. I'm not totally familiar with `Snap 2D Vertices to Pixel`, but the docs recommend against using `Snap 2D Vertices to Pixel` at all and to only use `Snap 2D Transforms to Pixel`, so I'm not sure if anything else needs done?

**Comment by markdibarry** [comment] 2024-09-21 14:23
This is fixed by just using `snap_2d_transforms_to_pixel`, but https://github.com/godotengine/godot/pull/97260 also fixed `snap_2d_vertices_to_pixel` as well.

**Closed** 2024-09-21 14:24 UTC
Labels: needs testing, topic:2d
