### ISSUE TITLE
[Linux] Upon any file/folder creation inside of Godot; crashes the Hyprland session

### ISSUE THREAD

**Issue by Migzus** [godotengine/godot#75752] opened 2023-04-06 13:03 UTC
### Godot version

4.0.x-stable

### System information

Hyprland Arch Linux v0.23.0beta

### Issue description

By simply just creating any file, resource or directory the Hyprland session crashes. It is quite difficult to give more context than that. In the aftermath of the crash, it does spam the message:
```
"!EditorSettings::get_singleton() || !EditorSettings::get_singleton()->has_setting(p_setting)" is true. returning Variant()
at: _EDITOR_GET (editor/editor_settings.cpp:1101)
```
I do not believe that this is the cause of the crash. Because I am not interacting with the editor settings at all.
However, I did get another error message in some of my tests, when the spam stopped
```
Fatal glibc error: pthread_mutex_lock.c:94 (___pthread_mutex_lock): assertion failed: mutex->__data.owner == 0
```
This tells us that something tried to lock a thread but failed. Not sure if that specifically is Godot's side or Hyprland's side.

I would also like to mention I have tried Godot 3.x versions, it works just fine.

This crash might be due to the setup I have or on Hyprland's part.
I would like to briefly mention that Hyprland is a window tile manager, and works similarly to i3/sway. Though I have not tested if this crash happens there too. The reason why I am mentioning this is mostly because there _might_ be some conflicts between when Godot opens a new window, and how Hyprland handles windows. If, we keep in mind what I mentiond earlier about the mutex error. So it could be a Hyprland problem.

Other than that, there is not a whole lot to work off of from here. I might just have to wait this out and see if it might be because of my setup. So I might have to wait for new updates and such.

And the reason as to why I do not think I have to open an issue in the Hyprland repo. Is because it seems to be a Godot 4.0.x specific issue.

Also one more thing, it seems this does not happen with the saving scenes window, but only when you right-click the FileSystem-tab and attempt to create any resource from there.

UPDATE: Got some more errors that might be a little more helpful
```
ERROR:connection.cc(46) X connection error received 
```
So XWayland may be involved in this

Additionally, I can create sub-resources in the inspector (i.e. a new Shader) and store the file that way. That works. Odd...

### Steps to reproduce

Setup a Hyprland session, then install Godot 4.0.x (be it through the website or through pacman/yay it does not matter)
Create/import any project
Attempt to create a file or a directory inside of godot
Then prepare for the session to crash

### Minimal reproduction project

Any project.

**Comment by Calinou** [comment] 2023-04-06 17:12
Can you reproduce this after enabling **Single Window Mode** in the Editor Settings?

**Comment by Migzus** [comment] 2023-04-07 07:58
No that seems to fix it, and I re-enabled it right after to see if the error was predictable. And yes, it crashes again if I turn Single Window Mode off.

**Comment by quinnyo** [comment] 2023-07-10 22:21
May be worth trying to reproduce this since #79143 was merged.

**Comment by Migzus** [comment] 2023-07-11 07:37
Yes, that seems to be correct. I can now create files and resources from the file system tab, with single window mode disabled. Closing this issue and can be assumed fixed.
Tested with v4.2.dev.custom_build [b7c2fd2e9]

**Closed** 2023-07-11 07:37 UTC
Labels: bug, platform:linuxbsd, topic:editor, topic:porting
