### ISSUE TITLE
Blue dot appears when using the default sky

### ISSUE THREAD

**Issue by hinlopen** [godotengine/godot#41515] opened 2020-08-25 18:37 UTC
**Godot version:**

Occurred both on 3.2.3.rc4 and 3.2.2.stable

**OS/device including version:**

Windows, GLES3

**Issue description:**
A blue dot appears under the Y-axis gizmo. It is visible both in the editor and when running the scene. It might be related to the default sky texture, as loading a different texture into the environment sky, or using a clear color, seems to make it disappear.
![image](https://user-images.githubusercontent.com/25907608/91212702-e1158b80-e710-11ea-92bf-edb9d2f87b07.png)
![Naamloos](https://user-images.githubusercontent.com/25907608/91212582-b592a100-e710-11ea-8b7f-5e1db06b865b.png)

**Steps to reproduce:**
Create a new scene (spatial or nothing) and look down on the Y-axis gizmo.

**Minimal reproduction project:**
Not relevant.

**Comment by Calinou** [comment] 2020-08-25 18:49
See also https://github.com/godotengine/godot/issues/10204.

**Comment by clayjohn** [comment] 2020-08-25 19:37
Duplicate of https://github.com/godotengine/godot/issues/37192

Please search existing issues before opening a new one. 

For future reference this issue has already been solved in 4.0, but needs a different solution for 3.x

**Closed by clayjohn** 2020-08-25 19:37 UTC
Labels: bug, topic:rendering
