### ISSUE TITLE
Search functionality in script editor doesn't indicate number of occurrences based on current search position

### ISSUE THREAD

**Issue by artism90** [godotengine/godot#41342] opened 2020-08-18 00:13 UTC
**Godot version:**

3.2.3.rc3 (verified also on 3.2.2 stable)

**OS/device including version:**

Windows 10

**Issue description:**

The search functionality of the script editor currently lacks a simple yet useful indicator on how far you search-stepped a term (e.g. "**4th of 7 occurrences**"). Being a common feature of like literally *any* code editor this should eventually become also part of GDScript's one.

**Comment by Calinou** [comment] 2020-08-18 13:00
Duplicate of https://github.com/godotengine/godot-proposals/issues/600.

(PS: Please open feature proposals on the Godot proposals repository, not here as this repository is intended to be used for bug reports only.)

**Closed by Calinou** 2020-08-18 13:00 UTC
Labels: enhancement, topic:editor
