### ISSUE TITLE
Overlaping logs in console

### ISSUE THREAD

**Issue by iwek7** [godotengine/godot#61706] opened 2022-06-04 22:35 UTC
### Godot version

8e3084cc91

### System information

Linux Mint 20

### Issue description

When printing logs to console and first log takes up big amount of space, logs start to overlap.

### Steps to reproduce

1. Write following code
```
	print("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa(...) ") # write so many characters so that first log takes up whole console window
	print("bbbbbb")
```
2. Following thing is displayed in output console:
![image](https://user-images.githubusercontent.com/9964886/172027477-c8197d59-4960-4f99-9171-a72eb377191b.png)
as you can see `aaa...` log and `bbbb` log are mixed up as well as end of process message

**Comment by KoBeWi** [comment] 2022-06-04 22:45
Duplicate of #55004

**Closed by KoBeWi** 2022-06-04 22:45 UTC
