### ISSUE TITLE
Weird exception when using constants from Autoloaded scripts which use preload

### ISSUE THREAD

**Issue by Mastermori** [godotengine/godot#38106] opened 2020-04-22 11:52 UTC
**Godot version:**
3.2.1.stable

**OS/device including version:**
Win7

**Issue description:**
When using a const variable from an autoloaded script in a non autoloaded script, which contains a preload() anywhere, the editor throws a non-sensical exception everytime you reopen the project.
By renaming the constant and then renaming it to the original name again, the exception disappears, so it is only thrown once the project is opened, until the constant was removed and added back.

This only happens when using preload() not when using load(), so it can be fixed by using load() instead, but it's still very weird and unexpected behaviour.

**Steps to reproduce:**

1. Create a "Globals" script which defines a constant expression
2. Add a preload() call anywhere in the Globals script
3. Autoload the "Globals" script
4. Create a new scene and add a script to it.
5. In this script use the Global constant
6. Restart the project

**Screenshots:**
Globals.gd:
![grafik](https://user-images.githubusercontent.com/21044348/79977679-f2b70000-849e-11ea-8793-e291cd19f9d6.png)
Test.gd:
![grafik](https://user-images.githubusercontent.com/21044348/79977738-095d5700-849f-11ea-883b-6ca7138fdcf4.png)
Exception:
![grafik](https://user-images.githubusercontent.com/21044348/79977782-1a0dcd00-849f-11ea-9938-29a9a7ce835e.png)

**Minimal reproduction project:**
[PreloadBug.zip](https://github.com/godotengine/godot/files/4515883/PreloadBug.zip)

**Comment by bojidar-bg** [comment] 2020-04-22 12:56
Duplicate of #14681. The fact that it only happens when `preload`-ing probably means it is partially fixed, but not fully (as was mentioned in the other issue).

**Closed by bojidar-bg** 2020-04-22 12:56 UTC
