### ISSUE TITLE
Shift+Tab Behaviour Regression in 4.0

### ISSUE THREAD

**Issue by CarpenterBlue** [godotengine/godot#67073] opened 2022-10-08 10:22 UTC
### Godot version

4.0 Beta 2

### System information

Windows 10

### Issue description

Shift + Tab doesn't remove leftmost tab if the caret is anywhere but next to a tab which it then proceeds to remove even if it is in middle of the text. Current behaviour is exactly the same as just pressing backspace.

In 3.x you can Shift + Tab to remove the leftmost tab no matter the caret's position in the line which is much more useful.

### Steps to reproduce

Copy paste the following line into the Script Editor in Godot 4.0 and put the caret at the end of the sentence.
```
	# then try pressing Shift+Tab
```
In 3.x this would have deleted the tab at the beginning of the line.

**Comment by Calinou** [comment] 2022-10-08 16:44
Duplicate of https://github.com/godotengine/godot/issues/50279.

**Closed by Calinou** 2022-10-08 16:44 UTC
