### ISSUE TITLE
Godot 4: Certain keys make click sound when editing gdscripts or editor inputs

### ISSUE THREAD

**Issue by toddgibson** [godotengine/godot#58226] opened 2022-02-17 03:42 UTC
### Godot version

4.0.alpha2

### System information

macOS 12.1, M1 Max CPU/GPU

### Issue description

When editing gdscript or changing values in the editor fields, anytime I press enter, arrow keys, backspace, delete, or tab an annoying click sound plays.  This does not happen in 3.4.2 stable.

### Steps to reproduce

See above.

**Comment by akien-mga** [comment] 2022-02-17 06:48
Duplicate of https://github.com/godotengine/godot/issues/58016, this will be fixed in 4.0 alpha 3.

**Closed by akien-mga** 2022-02-17 06:48 UTC
