### ISSUE TITLE
Enabling MSAA 2D makes 3D scenes render to a black screen

### ISSUE THREAD

**Issue by clement-or** [godotengine/godot#78785] opened 2023-06-28 08:42 UTC
### Godot version

v4.0.3.stable.official

### System information

Windows 10.0.19044 Build 19044 - Mobile Renderer - Nvidia GTX 1660 Ti (Driver 516.94)

### Issue description

On a Mobile renderer project, if you set MSAA 2D to any value, 3D scenes will show a black screen when running them. However, if you add a Sprite to the scene with a texture set, the scene will render properly only if it's visible on the viewport.

I would expect MSAA 2D not to affect 3D rendering in any capacity

### Steps to reproduce

* Try to start the minimal repro project
* Black screen
* Add a sprite2D under the Main node and fill the texture
* Try to run
* Beautiful cylinder sunbathing as you stare in awe

### Minimal reproduction project

[ReproProject.zip](https://github.com/godotengine/godot/files/11892098/ReproProject.zip)

**Comment by Calinou** [comment] 2023-06-28 09:09
Thanks for the report! Consolidating in https://github.com/godotengine/godot/issues/67234.

**Comment by BastiaanOlij** [comment] 2023-10-30 02:45
This is likely fixed by #83649

**Comment by akien-mga** [comment] 2023-10-30 09:40
Like Calinou, I can't reproduce the issue on Linux with AMD Radeon RX Vega M GL Graphics, nor Intel HD Graphics 630, neither in 4.0.3.stable (like the OP) nor latest 4.2-beta.

Assuming fixed by #83649 anyway as suggested, please test in the upcoming 4.2-beta4 (or artifacts from the master branch) to confirm.

**Closed by akien-mga** 2023-10-30 09:40 UTC
Labels: bug, topic:rendering, topic:2d
