### ISSUE TITLE
Unpause Game

### ISSUE THREAD

**Issue by pitfritsch** [godotengine/godot#4941] opened 2016-05-31 00:11 UTC
I have an `if` to test if the game is paused or not, should unpause if paused, but I don't how to unpause, help

Here is my code:

````gdscript
if(Input.is_key_pressed(KEY_ESCAPE)):
    if get_tree().is_paused() == false:
        get_tree().set_pause(true)
    else:
        get_tree().set_pause(false)
````

**Comment by trollworkout** [comment] 2016-05-31 03:20
ask it on Godot Q&A  . this is only for bug reports and issues.

**Comment by trollworkout** [comment] 2016-05-31 03:21
try this

```
if(Input.is_key_pressed(KEY_ESCAPE)) && !event.is_echo():
if get_tree().is_paused() == false:
get_tree().set_pause(true)
else:
get_tree().set_pause(false)
```

**Comment by bojidar-bg** [comment] 2016-05-31 08:11
The problem is that you probably didn't set "Process Mode" to "Process".

**Comment by vnen** [comment] 2016-05-31 15:19
Closing this as non-issue. The discussion on the question may go on but as stated you should use our Q&A forum for those questions in the future.

**Closed by vnen** 2016-05-31 15:19 UTC
