### ISSUE TITLE
Subviewport rendering different than non-viewport rendering

### ISSUE THREAD

**Issue by newobj** [godotengine/godot#86975] opened 2024-01-08 22:10 UTC
### Tested versions

- Reproducible in v4.2.1.stable.mono.official [b09f793f5]
- I never experienced this issue in 3.x

### System information

Windows 10 - v4.2.1.stable.mono.official, Forward+ and gl_compat renderers

### Issue description

Having an issue with subviewports: scaled down sprites that I place into a 1:1 window-sized subviewport either render jaggedy or blurry, compared to the same scaled-down sprite outside of the subviewport. In this image, I’ve got a 1920x1080 subviewport inside the same size window. In this screen shot you can see how the three different sprites render. All 3 are scaled by the same factor, about 0.14 (512x512px source texture → 72x72px) (Might need to open the image in a new tab to see at full resolution) Yet, the sprites in the subviewport look terrible with both types of filters, and the sprite looks perfect in the root viewport.

<img width="902" alt="image" src="https://github.com/godotengine/godot/assets/205457/1713800e-7f99-4ac7-ad8f-4af0dd738b52">

### Steps to reproduce

Create a window at 1920x1080, create a subviewport of the same size, put a large sprite in the subviewport and scale it down, e.g. 512x512 at 0.14,0.14 scale. Add the same sprite and scale, but outside of the subviewport. The same sprite, outside of the viewport, renders fare more crisply than the sprite inside the subviewport. See attached project.

### Minimal reproduction project (MRP)

[SubviewportRenderingIssue.zip](https://github.com/godotengine/godot/files/13866695/SubviewportRenderingIssue.zip)

Just run the scene to see the differences.

**Comment by AThousandShips** [comment] 2024-01-08 22:39
See also:
* https://github.com/godotengine/godot/issues/54030

**Comment by Calinou** [comment] 2024-01-08 22:57
This is what I see on my end with 4.3.dev 13a0d6e9b:

![image](https://github.com/godotengine/godot/assets/180032/50edb52f-5d23-4b74-9bff-8290787d7f46)

This is a different variant of https://github.com/godotengine/godot/issues/77149. This one occurs because of Camera2D zoom, rather than stretch scale factor.

This is expected behavior, since you're zooming in with the Camera2D node (1.8× factor), but SubViewport textures are not automatically resized to take Camera2D zoom into account. Doing so would impact performance negatively, especially when zoom changes at runtime (as changing viewport resolution is a relatively slow operation, requiring buffers to be recreated every time).

To have crisp rendering in a SubViewport at any zoom level, you need to resize it so it's pixel-perfect when fully zoomed in. The exact resolution you should use depends on the maximum expected zoom level of your Camera2D node. Note that this will result in graininess when fully zoomed out, since ViewportTexture doesn't generate mipmaps in real-time.

**Comment by Calinou** [comment] 2024-01-09 01:21
This is indeed the same issue as https://github.com/godotengine/godot/issues/77149 (as the updated MRP uses the `canvas_items` stretch mode), closing.

**Comment by newobj** [comment] 2024-01-09 01:21
[Issue86975-fixed.zip](https://github.com/godotengine/godot/files/13867699/Issue86975-fixed.zip)

Here's a solution where i think I got things working? Including camera? It's mainly [OhiraKyou](https://github.com/OhiraKyou)'s solution, with a couple tweaks: Subviewport size override set to match size, override stretch on, and display > window > aspect set to keep.

Looks fine to me? Is there a danger with what I've done here?

**Closed by Calinou** 2024-01-09 01:21 UTC
Labels: topic:rendering, documentation, topic:2d
