### ISSUE TITLE
TextEdit focus outline is not drawn correctly

### ISSUE THREAD

**Issue by YeldhamDev** [godotengine/godot#12810] opened 2017-11-10 14:55 UTC
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Godot Build: 05fc741bd

**Issue description:**
Comparison between LineEdit(how it should look) and TextEdit:
![outline](https://user-images.githubusercontent.com/30739239/32663819-70835fb4-c616-11e7-92bf-b7933e03e62e.gif)

**Comment by akien-mga** [comment] 2017-11-27 15:42
Related to #9612.

**Comment by KoBeWi** [comment] 2020-11-22 18:20
Still valid in 3.2.4 beta2
I noticed that the two have different stylebox assigned for focus:
https://github.com/godotengine/godot/blob/5ab727b460febd1af6621e078f0eb3a8ea42ef75/editor/editor_themes.cpp#L859-L861
https://github.com/godotengine/godot/blob/5ab727b460febd1af6621e078f0eb3a8ea42ef75/editor/editor_themes.cpp#L872-L874
But TextEdit seems to draw it wrongly:
![image](https://user-images.githubusercontent.com/2223172/99911888-9a2b3800-2cf7-11eb-8cf6-64acd3619acc.png)

**Comment by Calinou** [comment] 2021-09-03 23:50
Duplicate of https://github.com/godotengine/godot/issues/32996 (same cause).

**Closed by Calinou** 2021-09-03 23:50 UTC
Labels: bug, confirmed, topic:gui
