### ISSUE TITLE
No disconnect when changing node type with less joints in visual shader editor

### ISSUE THREAD

**Issue by timkrief** [godotengine/godot#79417] opened 2023-07-13 10:29 UTC
### Godot version

4.1.stable

### System information

Ubuntu 22.04

### Issue description

Visual shader editor should disconnect (at least visually) when we change the number of joints

before changing the type
![image](https://github.com/godotengine/godot/assets/14089949/6124a5cc-d6ef-42dc-996b-d7ceebf77ad1)

after
![image](https://github.com/godotengine/godot/assets/14089949/f43ce0cf-d0f9-4138-810c-10ee8a2d9285)
![image](https://github.com/godotengine/godot/assets/14089949/52988ed8-dca1-448c-9322-b36cfe428036)

this one break things
![image](https://github.com/godotengine/godot/assets/14089949/b7d22fd8-6822-4f2d-968b-4fe25db8ddf7)

### Steps to reproduce

You can see what to do to reproduce the bug in the screenshot

### Minimal reproduction project

A visual shader, two nodes.

**Comment by EddieBreeg** [comment] 2023-07-13 14:20
I'd like to give this one a shot if no one is working on it

**Comment by EddieBreeg** [comment] 2023-07-13 16:55
I found the source of the issue, however I really am not sure about how to fix it.
When you change a compose/decompose type, the `set_op_type` method of the relevant node class gets called.
https://github.com/godotengine/godot/blob/60f3b7967cbd00b4e1f52d33d372646f7bec02f6/scene/resources/visual_shader_nodes.cpp#L4767
https://github.com/godotengine/godot/blob/60f3b7967cbd00b4e1f52d33d372646f7bec02f6/scene/resources/visual_shader_nodes.cpp#L4946

These methods just set the new vector type, and emit a signal to the editor. This signal gets handled by this method:
https://github.com/godotengine/godot/blob/60f3b7967cbd00b4e1f52d33d372646f7bec02f6/editor/plugins/visual_shader_editor_plugin.cpp#L180-L186

As far as I can see, the update method has no way of knowing the number of ports has changed, so it can't take care of removing the extra connections when needed.

**Comment by EddieBreeg** [comment] 2023-07-19 02:01
I sort of managed to fix the issue, but unfortunately it created an even weirder bug.

Here if I changed the vector compose node to vector2, it will correctly disconnected the ports.
![image](https://github.com/godotengine/godot/assets/28712424/c2ee773a-339f-4f96-ac43-1836d44c8dae)
![image](https://github.com/godotengine/godot/assets/28712424/63989c8f-595c-4758-968a-8e0677a9e37e)

But if I then switch the node back to 3D, and then try to recreate that EXACT same connection, it won't allow me: nothing happens. The connection doesn't register. If I now try to create a different connection to that port, it works as expected and everything goes back to normal.
![image](https://github.com/godotengine/godot/assets/28712424/469c89d5-d8bf-47f1-886d-cda04bf1387c)

**Comment by EddieBreeg** [comment] 2023-08-10 11:02
https://github.com/godotengine/godot/issues/79417#issuecomment-1641272449

This is now fixed, it was in fact caused by my original code not fully fixing the problem

**Closed** 2024-04-08 16:44 UTC
Labels: bug, topic:editor, confirmed, topic:shaders
