### ISSUE TITLE
project loading failing with failed loading resource / failed to instantiate scene  with cyclic preload

### ISSUE THREAD

**Issue by tlobig** [godotengine/godot#86154] opened 2023-12-14 12:25 UTC
### Tested versions

- Reproducible with 4.2.1 stable

### System information

Godot v4.2.1.stable - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3080 Laptop GPU (NVIDIA; 31.0.15.4617) - AMD Ryzen 9 5900HX with Radeon Graphics (16 Threads)

### Issue description

When opening an affected project it fails to load, for example: 

 ```
  scene/resources/resource_format_text.cpp:284 - res://a.tscn:6 - Parse Error: 
  Failed loading resource: res://a.tscn. Make sure resources have been imported by opening the project in the editor at least once.
 ```

when trying to load the scene from the FileSystem view:

 ```
  Failed to instantiate scene state of "res://a.tscn", node count is 0. Make sure the PackedScene resource is valid.
  editor/editor_data.cpp:626 - Index p_idx = 1 is out of bounds (edited_scene.size() = 1).
 ```

Only workaround I know: break the cycle in the script. In a larger project where I first found the issue it also helped to close all open scenes and just reload.

### Steps to reproduce

minimal steps:

1. Create a 2D scene A and a 2D scene B
2. Attach a script a.gd to A's root and a script b.gd to B'
3. in a add a variable b like this: var b = preload("res://b.tscn")
4. in b add a variable a like this: var a = preload("res://a.tscn"), which creates a cycle.
5. safe all scenes (ctrl + s)
6. from the menu execute Project -> Reload Current Project

### Minimal reproduction project (MRP)

[project_loading_bug_test.zip](https://github.com/godotengine/godot/files/13673175/project_loading_bug_test.zip)

**Comment by tlobig** [comment] 2023-12-14 12:34
the cyclic preloads seem to be no issue during runtime, and from an uninformed user's perspective it looks like the project is just broken beyond repair. Even though the error message points to the offending script, there seems to be no way to find the issue without loading the scene in an external editor. Also even when looking at the line it just points to the script and the error is still hard to guess.

If the cyclic preload is generally bad, I would prefer if the project loader detects the cycle und gives a specific error message, maybe even breaking the cycle where it is first detected.

**Comment by isaaccp** [comment] 2023-12-15 01:33
fwiw, i am seeing the same without any cycles

**Comment by isaaccp** [comment] 2023-12-15 01:35
I think this is probably the same as #85907

**Comment by tlobig** [comment] 2023-12-15 04:40
it is almost exactly the same, i just didn't find it, was going through a few pages of search before opening this issue

**Comment by BriarSMC** [comment] 2023-12-20 14:13
HP Elitedesk 800 G2
Fedora Workstation 39 w/Gnome 45. 
Godot 4.2.1.stable_official [b09f793f5]

Godot Editor crashed. Just up and went away. File __mfput.log__ showed up in my project directory.
```
This is METAFONT, Version 2.71828182 (preloaded base=mf 2023.11.16)  20 DEC 2023 07:03
**.godot/

! Emergency stop.
<*> .godot/
           
End of file on the terminal!
```

Then this started happening to my project when I open it from the Project List. 

Editor output window
```
Godot Engine v4.2.1.stable.official (c) 2007-present Juan Linietsky, Ariel Manzur & Godot Contributors.
  modules/gltf/register_types.cpp:63 - Blend file import is enabled in the project settings, but no Blender path is configured in the editor settings. Blend files will not be imported.
--- Debug adapter server started ---
--- GDScript language server started on port 6005 ---
  scene/resources/resource_format_text.cpp:284 - res://addedit_list_screen.tscn:17 - Parse Error: 
  Failed loading resource: res://addedit_list_screen.tscn. Make sure resources have been imported by opening the project in the editor at least once.
  Failed to instantiate scene state of "res://addedit_list_screen.tscn", node count is 0. Make sure the PackedScene resource is valid.
  editor/editor_data.cpp:880 - Index p_idx = 1 is out of bounds (edited_scene.size() = 1).
  editor/editor_data.cpp:683 - Index p_idx = 1 is out of bounds (edited_scene.size() = 1).
  editor/editor_data.cpp:745 - Index p_idx = 1 is out of bounds (edited_scene.size() = 1).
```
If I delete .__godot/__, then it goes away. For awhile anyway before it starts happening again. Rinse, Repeat. Always dies at the same line in my __.tscn__ file:
```
script = ExtResource("1_fllos")
```

**Comment by tlobig** [comment] 2023-12-22 20:35
Tested with dev snapshot 1 of 4.3.1 it still prints an error at load, but does fixes the corruption.

**Comment by KoBeWi** [comment] 2023-12-22 21:37
Fixed by #85159

**Closed by KoBeWi** 2023-12-22 21:37 UTC
Labels: bug, topic:core

**Comment by 3ter** [comment] 2024-02-07 19:46
For the time being for me this happened when I removed a plugin.
The workaround was to go through the ` .godot/global_script_class_cache.cfg` and remove all entries for this plugin and then everything was fine again.

**Comment by devingDev** [comment] 2024-06-04 20:49
Still happening to me.
All I did is reopen the project 😂

**Comment by hosmaznazfar** [comment] 2024-07-09 16:58
if  you encounter this problem after Godot crushing like me you can open the corrupted scene in text editor save it in other name delete the origin and rename the new file,problem solved 
hope it help others like me

**Comment by Quanthon** [comment] 2024-07-25 02:30
> if you encounter this problem after Godot crushing like me you can open the corrupted scene in text editor save it in other name delete the origin and rename the new file,problem solved hope it help others like me

Thanks. It worked for me.

**Comment by PefectParry** [comment] 2024-08-22 20:55
Had two files Godot told me were corrupted. Going into a text editor and removing the "script = ExtResource()" lines from the affected .tscn files. I assume this is due to an issue with dependencies when extending the same script to different related scenes in my case. I have no clue how to properly reproduce the issue but I probably could if need be.

**Comment by GreatNateDev** [comment] 2024-08-24 15:57
```
func load_data():
	data = ResourceLoader.load(save_path+save_name).duplicate(true)
func save_data():
	ResourceSaver.save(data,save_path+save_name)
```
![image](https://github.com/user-attachments/assets/42901811-4122-4729-97aa-da725960d2dd)
i get a whole lot of errors :/
