### ISSUE TITLE
Can't assign exported array of nodes

### ISSUE THREAD

**Issue by Badaxis** [godotengine/godot#71603] opened 2023-01-18 10:14 UTC
### Godot version

v4.0.beta12.official [3c9bf4bc2], v4.0.beta13.official [caacade56]

### System information

Windows 10

### Issue description

There seems to be an issue with typed array of nodes, assign in the inspector doesn't work.
For example I used:
```gdscript
@export var arr_node: Array[Node3D]
```
In the inspector I have the contextual menu to assign a node from the tree but when I select it, it's not assigned.

These work properly with the same contextual menu to assign:
```gdscript
@export var node: Node3D
@export var arr_path: Array[NodePath]
```

### Steps to reproduce

1) Create a basic scene with a script
2) Export an Array[Node3D] or other node type
3) In the inspector, try to assign a node from the tree into the array

### Minimal reproduction project

[array_node.zip](https://github.com/godotengine/godot/files/10444637/array_node.zip)

**Comment by Gnumaru** [comment] 2023-01-21 09:12
This also happens on beta 14.

A nodepath array export is persisted differently than a node export or node array export, if I'm not mistaken. A nodepath **value** can be serialized and unserialized directly in the .tscn, but in the case of node exports I think there is some metadata juggling in order to make it work. I haven't looked the code but I think it should be something like serializing an array of nulls but, in the metadata, holding an array of nodepaths, and after unserializing, after the whole tree has been set up and every node exists in its expected path, then the metadata is used to get the nodes and fill the array.

**Comment by andersonmadeira** [comment] 2023-01-28 07:07
Also saw this on beta 16.

**Comment by dark-elf1** [comment] 2023-01-29 17:58
Still present on v4.0.beta.custom_build [d01ac9c73] on linux.

**Comment by raulsntos** [comment] 2023-01-29 18:03
Duplicate of https://github.com/godotengine/godot/issues/62916

**Closed by raulsntos** 2023-01-29 18:03 UTC
