### ISSUE TITLE
Can put a keyframe before 0 seconds on the Animation track

### ISSUE THREAD

**Issue by Oranjoose** [godotengine/godot#24406] opened 2018-12-16 22:24 UTC
Godot 3.1 alpha 3
Windows 10 x64

![image](https://user-images.githubusercontent.com/15862731/50059615-371de780-0157-11e9-9767-83c91ce21532.png)

As seen in the image above, you can drag a keyframe to before 0 seconds on the animation track. The Time value for the keyframe remains 0, so I don't think it causes actual unexpected behavior, but it is visually incongruent and nonsensical. Is this intended behavior?

**Comment by akien-mga** [comment] 2018-12-17 09:36
Duplicate of #19416, according to @reduz this is intended/OK. I'm not sure what's the use case though.

**Closed by akien-mga** 2018-12-17 09:36 UTC
