### ISSUE TITLE
Expanding a dock that can be closed by selecting another node doesn't correctly resize the bar when selecting other node

### ISSUE THREAD

**Issue by mrcdk** [godotengine/godot#13251] opened 2017-11-24 17:55 UTC
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Godot 3.0 master https://github.com/godotengine/godot/commit/f5c513ca7beef75759cdff4d50760aebe7118df2

**Issue description:**

For example:
![https://i.imgur.com/ZyyutC4.gifv](https://i.imgur.com/ZyyutC4.gif)

![https://i.imgur.com/KSg4PZ4.gifv](https://i.imgur.com/KSg4PZ4.gif)

**Steps to reproduce:**
1. Open the Autotiles or the TextureRegion dock
2. Expand it
3. Select another node

**Comment by Zylann** [comment] 2017-11-24 17:57
I've seen this several times, not only with auto tiles

**Comment by mrcdk** [comment] 2017-11-24 18:00
Yup, you are right, updated with another example

**Comment by reduz** [comment] 2017-12-05 22:42
@MarianoGnu have the feeling you should give a check to this

**Comment by MarianoGnu** [comment] 2017-12-05 23:05
does this happen with other bottom panels? ie shader editor?

**Comment by akien-mga** [comment] 2018-01-05 14:43
We have now entered release freeze for Godot 3.0 and want to focus only on release critical issues for that milestone. Therefore, we're moving this issue to the 3.1 milestone, though a fix may be made available for a 3.0.x maintenance release after it has been tested in the master branch during 3.1 development. If you consider that this issue is critical enough to warrant blocking the 3.0 release until fixed, please comment so that we can assess it more in-depth.

**Comment by mrcdk** [comment] 2018-01-06 02:48
Oh, sorry, totally forgot about this. No, it doesn't happen with the shader editor @MarianoGnu It does, at least, happen with the autotile and the texture region docks

**Comment by reduz** [comment] 2018-09-06 12:38
Does this still happen on current master? I can't reproduce.

**Comment by MarianoGnu** [comment] 2018-09-07 00:00
i think this was fixed by #21010
Specifically 
https://github.com/godotengine/godot/commit/609d97b6d4e14f45a90432cdb02fc633586576b4#diff-2d9f1cb0e1811a2708191a967c4b7d63R2371
and
https://github.com/godotengine/godot/commit/609d97b6d4e14f45a90432cdb02fc633586576b4#diff-2d9f1cb0e1811a2708191a967c4b7d63R2374

**Comment by vnen** [comment] 2018-09-08 18:55
Closing as fixed. Comment here or open a new issue if the bug can still be reproduced.

**Closed by vnen** 2018-09-08 18:55 UTC
Labels: bug, topic:editor
