### ISSUE TITLE
Ability to add custom icons to scenes.

### ISSUE THREAD

**Issue by johnhamilton** [godotengine/godot#6767] opened 2016-10-10 00:31 UTC
Ability to add custom icons to scenes so that when you link in a scene instead of the icon of the root node you get the custom icon.

Why do we need this? Because when you link in your player or some other instance it can be hard to tell the difference between them if thay have the same root node, this would just help to make you scenes more readable and clean.

Of course i dont know if this would slow down the editor as i dont know how icons are handled in the editor.

**Comment by hetdegon** [comment] 2016-10-10 03:02
This would be quite convenient for instances, I like the idea.

**Comment by bojidar-bg** [comment] 2016-10-10 08:37
BTW, this is already possible by using addons, though it would probably look ugly to implement.

**Comment by johnhamilton** [comment] 2016-10-10 10:08
True, but it would be much nicer and cleaner to just have a setting per scene. addons are a messy way of doing it. and maybe you don't want it as a new node type. right now you would have to have a custom node type per icon.

**Comment by kubecz3k** [comment] 2016-10-12 11:10
@bojidar-bg actually it's not possible with addons since you cant use scenes as a base for plugin (https://github.com/godotengine/godot/issues/3895)

**Comment by arypbatista** [comment] 2017-02-02 16:02
I think this is really important to better identify instances through Scene Tree.

**Comment by Noshyaar** [comment] 2018-04-07 06:58
First of all thank you for your report and sorry for the delay.

We released Godot 3.0 in January 2018 after 18 months of work, fixing many old issues either directly, or by obsoleting/replacing the features they were referring to.

We still have hundreds of issues whose relevance/reproducibility needs to be checked against the [current stable version](https://godotengine.org/download), and that's where you can help us.
**Could you check if the issue that you described initially is still relevant/reproducible in Godot 3.0 or any newer version, and comment about it here?**

Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

Thanks in advance.

*Note: This message is being copy-pasted to many "stale" issues (90+ days without activity). It might happen that it is not meaningful for this specific issue or appears oblivious of the issue's context, if so please comment to notify the Bugsquad about it.*

**Comment by aaronfranke** [comment] 2018-08-01 05:28
@Noshyaar Yes it is still relevant. It is a low priority feature, but I would appreciate having it.

**Comment by akien-mga** [comment] 2018-11-22 12:44
Fixed by #20560.

**Closed by akien-mga** 2018-11-22 12:44 UTC
Labels: feature proposal, topic:editor, usability

**Comment by andrejp88** [comment] 2019-10-27 20:25
@akien-mga I believe this issue is slightly different than that pull request. I might be misunderstanding something, but it seems the pull request allows adding custom icons for custom nodes (using the class_name syntax), not instanced scenes (which don't necessarily have an attached script). Perhaps Node could have an exported "editor_icon" property or something like that?

**Comment by aaronfranke** [comment] 2019-12-19 21:05
@andrejp88 The current system is not exactly what the feature request described, but they still fit the same use cases. For any given scene, attach an icon via the script class system.

**Comment by me2beats** [comment] 2021-05-01 23:56
How does it solve the issue? This adds an ability to set custom icons to `custom classes`, not to `scenes instances`.

**Comment by CSaratakij** [comment] 2023-10-08 02:23
@akien-mga Kinda expect this to works like drawing icon into the scene.
The same features CPUParticles3D draw its icon in the scene.
![image](https://github.com/godotengine/godot/assets/9628627/6121a8cc-5d1f-4f0d-a2fd-2c47c4a99a87)

**Comment by aaronfranke** [comment] 2023-10-08 02:29
@CSaratakij Those gizmos are drawn by editor plugins with special code. It's possible for you to make your own editor plugins too. But anyway, that's unrelated to this issue.
