### ISSUE TITLE
Script file name for Export section in Inspector is not centered

### ISSUE THREAD

**Issue by Vignesh1-art** [godotengine/godot#51774] opened 2021-08-17 03:38 UTC
### Godot version

4.0 dev

### System information

windows 10

### Issue description

![Screenshot (1)](https://user-images.githubusercontent.com/52810607/129659699-7094b2c0-5155-49e1-b903-3bf185850463.png)

As you see file name is not in center.
For some reason this happen randomly. Sometimes it is centered sometimes not and not limited Script file name.

### Steps to reproduce

Just create a export variable check it out

### Minimal reproduction project

No need

**Comment by jmb462** [comment] 2021-08-18 20:48
It happens not only for script name and even without any export variables.
Node2D is always impacted but I can't find another node.

![image](https://user-images.githubusercontent.com/3649998/129970041-40ae810b-4f75-49e7-a17d-62810e21986c.png)

**Comment by jmb462** [comment] 2022-01-08 20:13
This issue seems to no longer happen now.
Can't reproduce it anymore.

**Comment by akien-mga** [comment] 2022-01-08 22:33
Closing then, please comment of the issue shows up again.

**Closed by akien-mga** 2022-01-08 22:33 UTC
Labels: bug, topic:editor, confirmed, junior job, usability
