### ISSUE TITLE
glTF import won't update extracted texture

### ISSUE THREAD

**Issue by jbw80** [godotengine/godot#83154] opened 2023-10-11 15:58 UTC
### Godot version

4.1.2 stable

### System information

Godot v4.1.2.stable - Windows 10.0.19045 - Vulkan (Forward+) - dedicated Quadro P620 () - 11th Gen Intel(R) Core(TM) i9-11900K @ 3.50GHz (16 Threads)

### Issue description

The textures packed into glb exports won't always update when the inherited glb is updated from blender.  It might use an old texture, appear textureless, or sometimes just work and I simply cannot figure out what i am doing wrong.

### Steps to reproduce

- open project in godot and browse empty testcube folder
- copy testcube-1.glb from zip root into godot_project\testcube as testcube.glb
- switch back to godot and import glb as new inherited scene and save tscn in testcube folder. glb may appear with red "x", but reimporting fixes it?
- copy testcube-2.glb from zip root into godot_project\testcube as testcube.glb
- switch back to godot, image texture should change with some errors in output log
- copy testcube-1.glb from zip root into godot_project\testcube as testcube.glb
- cube might appear with changed texture or appear white/textureless. it has been difficult to get this to predictably happen

![white-cube-errors](https://github.com/godotengine/godot/assets/26756972/75712e03-96ce-4883-87e6-60f08dc40f28)

errors in output log appear: 

```
  Can't find file 'uid://w87lq3421wmi::::res://testcube/testcube_godette.png'.
  Attempt to disconnect a nonexistent connection from 'testcube:<Node3D#2317655010421>'. Signal: 'replacing_by', callable: 'EditorNode::set_edited_scene'.
  Can't find file 'uid://c5oarbyq0oygi::::res://testcube/testcube_godot.png'.
  Attempt to disconnect a nonexistent connection from 'testcube:<Node3D#2486517690152>'. Signal: 'replacing_by', callable: 'EditorNode::set_edited_scene'.
```

blend file notes: Blender 3.6.0, this is the default cube and default material with an image texture of a png file, the only difference between the two glb exports is which files is used. glbs are exported "limited to selected objects" with only the cube selected.

### Minimal reproduction project

[glb-import-issue.zip](https://github.com/godotengine/godot/files/12872041/glb-import-issue.zip)

**Comment by rogerdv** [comment] 2023-10-27 02:16
I can confirm that this happens in 4.1.2 and 4.2. It is totally unpredictable, I had my project with all models working ok, made some changes in the scenes (no need to export from Blender, just reimported GLBs) and suddenly all textures were gone. In 4.2 never managed to have one of those models ever show anything but white material. When you open the GLB, all materials are marked as <Unnamed material>
[test_materials.zip](https://github.com/godotengine/godot/files/13184347/test_materials.zip)

**Comment by jojorne** [comment] 2023-10-27 17:58
In my case, this happens if I open the mesh directly as a `New Inherited Scene`. It looks exactly like the screenshot above.

**Comment by golddotasksquestions** [comment] 2023-11-09 13:15
I can also reproduce this in Godot 4.1.2 stable, 4.1.3 rc1 and Godot 4.2 Beta 5.

1. Add a Material and image texture to the default cube in Blender. In the TexturePaint tab, draw something on the mesh.
2. Export the selected cube as glb into your Godot res folder and instance the glb in a 3D scene.
3. Go back to Blender in the Texture Paint tab and draw something else on the cube.
4. Export the selected cube again as glb with the same name (override existing file) into your Godot res folder.
5. Observe Godot reimporting the instanced glb, but not updating the texture anywhere.

You can also try to change the mesh by sculpting the topology for example, and the reimport will update the mesh in Godot, but not the texture.

[This has been a problem ever since the early Alphas of Godot 4](https://github.com/godotengine/godot/issues/63513) and really needs to be fixed as it makes working with custom 3D art assets and and iterative work in 3D a huge pain.

**Comment by F1shb0ne** [comment] 2023-11-09 15:19
Can also confirm in 4.2 beta 5

Completely agree with @golddotasksquestions regarding this being a particularly irksome problem with iterative 3d workflow for texture painting revisions.

**Comment by KoBeWi** [comment] 2023-12-11 21:44
Can't reproduce in 4.2 stable.
(though the red X issue is still there)

**Comment by golddotasksquestions** [comment] 2023-12-19 23:31
I tested this again in Godot 4.2.1 stable on Win 10 with my old Blender version as well with the latest stable version (4.0.2). I tested this also with low res textures (16x16) as well as higher res textures (1024x1024). Always following[ these exact steps](https://github.com/godotengine/godot/issues/83154#issuecomment-1803812865), with the same result described in the original issue (the texture won't update after Godot auto-reimport). Manually reimporting also does not help.

I did notice a red error in the Output panel though:
`Can't find file 'uid://v3m44k5ov3mj::::res://cube_mat.png'.`

I have a file with that name in the FileSystem as it was generated I believe when the glb was first imported. This file is just the Color (Albedo) texture, but it does not show the shanges I made.
When I double-click the cube.glb file to open it up in the Advanced Import Panel, the texture also shows it's old face. It's like the texture never reimported. 

Changes on the mesh to update as expected after the auto-reimport.

**Comment by KoBeWi** [comment] 2023-12-19 23:53
The commit that closed this issue was not included in 4.2.1.

You can test a build with the fix here: https://github.com/godotengine/godot/suites/18889002007/artifacts/1102777269
See if you can still reproduce.

**Comment by golddotasksquestions** [comment] 2023-12-20 00:12
Unfortunately I can still reproduce it with this artifact as well. Exact same issue.

**Comment by lyuma** [comment] 2023-12-24 07:41
Confirmed. This issue has been solved with #85922

As a workaround and to demonstrate that this is fixed by that PR, copy the file as "bestcube" instead of "testcube" and you will observe that the issue no longer happens: the bug only affected files whose names sort alphabetically greater than the word "res".

**Comment by golddotasksquestions** [comment] 2023-12-25 02:39
@lyuma 

I believe https://github.com/godotengine/godot/pull/85922 has not been changed since I last tested it in the artifact 5 days ago. The issue is also still present exactly as described in Godot 4.3. Dev1. 

Please reopen.

**Comment by lyuma** [comment] 2023-12-25 02:52
Just to completely rule out that bug, can you reproduce it using a freshly unzipped project with no .godot
use "bestcube.glb" (a file name whose first letter is below "r")

I will reopen but I was unable to reproduce it two times in a row using either that filename or a fresh build on master.

**Comment by golddotasksquestions** [comment] 2023-12-25 03:30
I have now created yet another completely new project in Godot 4.3 Dev1, and two completely new blender cubes (new files each), both unique and new materials and new textures. One named "cccc" and the other "tttt".

After they imported I dragged them into a scene. Then I went back to Blender and repainted their texture in Blender with a different color, changed to Godot, which then auto-reimports the cube as it should but the textures do not update.

This is exactly the same behavior described I have already described in this issue and even back with early alphas [here](https://github.com/godotengine/godot/issues/63513).

**Comment by lyuma** [comment] 2023-12-25 09:08
@golddotasksquestions Thank you SO much for clarifying the reproduction steps. Using texture paint in blender and re-exporting made it more reliable to reproduce the issue.

I found **three** additional bugs in the import system, not including #85922 (in other words, when originally reported there were actually 4 different issues preventing the texture from updating.) and attempted to address all of them. modified textures in glb files now update reliably in the testing I did so far.

Once it compiles, feel free to give the artifact in #86504 a try, and happy holidays 🌲

**Closed** 2024-01-02 17:06 UTC
Labels: bug, confirmed, topic:import, topic:3d

**Comment by golddotasksquestions** [comment] 2024-01-11 22:33
@lyuma Thanks so much for this fix!

Finally, for the first time in two years (actually ever since the first alphas of Godot 4 existed), I can update textures!

**Comment by fragmentventures** [comment] 2024-01-13 13:48
I still get this error in 4.3 Dev2. If I do some some small changes like move some UVs around or some of the verticies. Im not touching the image texture connected to my material at all in blender on a default cube. Hit "Save", my .blend file gets re-imported. My model actually updates, but I get an error that it cant find the texture. Im using the texture located in my godot asset folder in blender. So should be the same: "Can't find file 'uid://coadexe5lmrim::::res://assets/textures/gradient.png'."

**Comment by golddotasksquestions** [comment] 2024-02-02 13:13
@fragmentventures 
Maybe open a new issue to get more eyes on this? The texture does update now, even in your example, so I doubt anything will be done here.
