### ISSUE TITLE
Godot game was force killed in background on Android when the sdk showed ad

### ISSUE THREAD

**Issue by SmallKi** [godotengine/godot#84069] opened 2023-10-27 18:15 UTC
### Godot version

4.1.2

### System information

Windows11, GLES3

### Issue description

I wrote a game running on android and used advertisement sdk  to show ad.
But once some advertisment popup, the goodt game will crash, but the ad is ok.  I try to get the error info, here is:
<img width="889" alt="Snipaste_2023-10-27_21-42-31" src="https://github.com/godotengine/godot/assets/37371850/553c7077-6e2b-487b-86b9-f32a5531f869">

It seemd that my game was killed because it was running in the background. 
And the error info below shows that there has some memory leak in godot. 

There are just few ads will encounter this crash, others are normal. 

I want to know is this the godot engine's bug or just  my faults maybe? 
Which direction could I  to dig out？
Thank you very much.

### Steps to reproduce

no 

### Minimal reproduction project

N/A

**Comment by timothyqiu** [comment] 2023-10-31 09:23
Sounds the same as #83924.

It's fixed by #83954. You can try the build artifacts of the PR, or try changing `android:launchMode` to `"singleInstancePerTask"` in your AndroidManifest.xml.

**Comment by m4gr3d** [comment] 2023-11-01 03:04
Duplicate of https://github.com/godotengine/godot/issues/83924

**Closed by m4gr3d** 2023-11-01 03:04 UTC
Labels: bug, platform:android, topic:thirdparty, needs testing, crash
