### ISSUE TITLE
I found that the handle cannot vibrate when using PS5 and switch pro on Windows，They seem to be recognized as dinput

### ISSUE THREAD

**Issue by kc991229** [godotengine/godot#85200] opened 2023-11-22 01:53 UTC
### Godot version

3.5

### System information

windows10

### Issue description

I found that the handle cannot vibrate when using PS5 and switch pro on Windows. They seem to be recognized as dinputs,I don't know if it's caused by this, what do I need to do

### Steps to reproduce

ues switch pro in Windows

### Minimal reproduction project

I found that the handle cannot vibrate when using PS5 and switch pro on Windows，I don't know if it's caused by this, what do I need to do

**Comment by akien-mga** [comment] 2023-11-22 08:56
Duplicate of #85166, which was closed as duplicate of #14634.

Please add further information to #14634 instead of re-opening new issues.

**Closed by akien-mga** 2023-11-22 08:56 UTC
