### ISSUE TITLE
Renaming a text file makes it unusable with parse error

### ISSUE THREAD

**Issue by Pinchanzee** [godotengine/godot#28138] opened 2019-04-17 20:45 UTC
**Godot version:**
v3.1.stable.official

**OS/device including version:**
Ubuntu 18

**Issue description:**
"Rename..." on a text file created through "New Resource" causes it to become unusable, with the following error:
scene/resources/resource_format_text.cpp:1186 - res://c.tres:1 - Parse Error: Expected '['

**Steps to reproduce:**
1. Add a "New Resource" of type text file
2. "Rename..." the text file
3. Attempt to open the text file

**Minimal reproduction project:**
Fresh project

**Comment by Pinchanzee** [comment] 2019-04-17 20:49
Actually it looks like there are 2 issues.
The error code provided actually seems to have no impact on whether the file can be opened.

The actual error that prevents the opening of the file is:

`core/io/resource_loader.cpp:208 - Condition ' err != OK ' is true. returned: RES()
 Failed loading resource: res://coddventions.tres
 editor/editor_node.cpp:586 - Condition ' !res.is_valid() ' is true. returned: ERR_CANT_OPEN`

This error doesn't happen every time, but seems to occur when renaming the file a few times.

**Comment by KoBeWi** [comment] 2020-08-20 21:11
The problem is that you save the save file with `.tres` extension and Godot tries to load it as an actual Resource. In 3.2.2 it results in the error, but file opens normally in the script text editor.

TextFile shouldn't appear in the Resource list. It's only exposed, because the text editor breaks otherwise. See #36182 and the issue it spawned.

**Comment by KoBeWi** [comment] 2022-01-17 00:37
Fixed in 4.0, TextFile resource no longer exists. There's a proper support for text files now.

**Closed by KoBeWi** 2022-01-17 00:37 UTC
Labels: bug, topic:core, topic:editor, confirmed
