### ISSUE TITLE
Godot 4, C#: Not possible to emit signals with enum parameter

### ISSUE THREAD

**Issue by wp2000x** [godotengine/godot#67549] opened 2022-10-17 18:51 UTC
### Godot version

4.0b3

### System information

Windows 10

### Issue description

The signal arguments of the EmitSignal method are now of type Variant, and Variant is a value type. But enum types are now no longer possible.

It used to be possible to emit signals with enum arguments in Godot 3.

### Steps to reproduce

Code will not compile anymore (see MRP)
It results in the compiler error "Cannot convert CameraActions to 'Variant'" on the line that calls EmitSignal.

### Minimal reproduction project

[Godot4CSharpEnumSignalArguments.zip](https://github.com/godotengine/godot/files/9803627/Godot4CSharpEnumSignalArguments.zip)

**Comment by raulsntos** [comment] 2022-10-29 16:58
You should be able to create the Variant type from enums using their underlying type. I also noticed in your MRP you are using the wrong name for the signal (you should be using the name of the event, not the name of the delegate), I recommend using the exposed StringName in the SignalName class to use the cached StringName instance.

```csharp
public override void _Ready()
{
    EmitSignal(SignalName.OnChangeAction, (int)CameraActions.Moving);
}
```

---

Duplicate of https://github.com/godotengine/godot/issues/66013

**Closed** 2024-09-27 11:55 UTC
Labels: bug, topic:dotnet, regression
