### ISSUE TITLE
Engine crashes when closing a scene with a Tiled-based tileset

### ISSUE THREAD

**Issue by Ertain** [godotengine/godot#19337] opened 2018-06-02 18:58 UTC
**Custom version:** v3.1.dev.mono.custom_build.fe82b5a

**OS:** Linux Mint 18.3, 64-bit, Mono version 5.12.0.226, desktop

**Issue description:** tried to close a scene by clicking on the "X" in the scenes tabs, and it crashes the editor. The nodes in question have Tiled-based tilesets attached to them.

**Steps to reproduce:** Build the engine on Linux Mint 18.3 with version 5.12.0.226 of Mono (from the official Mono builds). Utilize the build script described in my Gist [seen here](https://gist.github.com/Ertain/3b22ebc12f6f9032255241d768030f1a). Then install vnen's Tiled Importer plugin. Create a couple of scenes, add some tilesets to them, and close one of the scenes.

**Minimal reproduction project:** [Tileset crash example.zip](https://github.com/godotengine/godot/files/2065271/Tileset.crash.example.zip)

Backtrace from gdb:
```
#0  pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
No locals.
#1  0x00007ffff5d82f2f in ?? () from /usr/lib/libmonosgen-2.0.so.1
No symbol table info available.
#2  0x00007ffff5d831c2 in ?? () from /usr/lib/libmonosgen-2.0.so.1
No symbol table info available.
#3  0x00007ffff5d98a6d in ?? () from /usr/lib/libmonosgen-2.0.so.1
No symbol table info available.
#4  0x00007ffff5c40c0f in mono_domain_try_unload () from /usr/lib/libmonosgen-2.0.so.1
No symbol table info available.
#5  0x0000000000c21270 in GDMono::_unload_scripts_domain () at modules/mono/mono_gd/gd_mono.cpp:656
No locals.
#6  0x0000000000c21336 in GDMono::~GDMono () at modules/mono/mono_gd/gd_mono.cpp:854
No locals.
#7  0x0000000000c06ac3 in memdelete<GDMono> () at core/os/memory.h:118
No locals.
#8  CSharpLanguage::finish () at modules/mono/csharp_script.cpp:142
No locals.
#9  0x000000000246c7d1 in ScriptServer::finish_languages () at core/script_language.cpp:114
No locals.
#10 0x0000000000a510c7 in Main::cleanup () at main/main.cpp:2145
No locals.
#11 0x0000000000a32d9f in main () at platform/x11/godot_x11.cpp:56
```

**Comment by vnen** [comment] 2018-06-02 19:58
Based on the backtrace seems to be an issue with Mono, not directly related to tilesets.

**Comment by Ertain** [comment] 2018-06-02 21:27
Hmm, if that's the case, then _why_ would it be doing that? This project doesn't involve any Mono.

**Comment by ByTheQuietLake** [comment] 2018-06-03 02:01
I believe this is related to this issue #18833.

**Comment by KingDuckZ** [comment] 2018-06-11 18:56
Possibly related. I've just compiled godot and downloaded the hex tilemap demo project. Then I selected Scene -> Close Scene and after a few seconds the editor crashed:

```
handle_crash: Program crashed with signal 11
Dumping the backtrace. Please include this when reporting the bug on https://github.com/godotengine/godot/issues
[1] /lib64/libc.so.6(+0x35a30) [0x7f11f9acba30] (??:0)
[2] StringName::operator=(StringName const&) (??:0)
[3] ScriptDebuggerRemote::add_profiling_frame_data(StringName const&, Array const&) (??:0)
[4] CanvasItemEditor::_draw_hover() (??:0)
[5] CanvasItemEditor::_draw_viewport() (??:0)
[6] MethodBind0::call(Object*, Variant const**, int, Variant::CallError&) (??:0)
[7] Object::call(StringName const&, Variant const**, int, Variant::CallError&) (??:0)
[8] Object::emit_signal(StringName const&, Variant const**, int) (??:0)
[9] Object::emit_signal(StringName const&, Variant const&, Variant const&, Variant const&, Variant const&, Variant const&) (??:0)
[10] CanvasItem::_update_callback() (??:0)
[11] MethodBind0::call(Object*, Variant const**, int, Variant::CallError&) (??:0)
[12] Object::call(StringName const&, Variant const**, int, Variant::CallError&) (??:0)
[13] MessageQueue::_call_function(Object*, StringName const&, Variant const*, int, bool) (??:0)
[14] MessageQueue::flush() (??:0)
[15] SceneTree::iteration(float) (??:0)
[16] Main::iteration() (??:0)
[17] OS_X11::run() (??:0)
[18] /home/michele/dev/thirdparty/godot/bin/godot.x11.tools.64(main+0xd5) [0x5602df476d1f] (??:0)
[19] /lib64/libc.so.6(__libc_start_main+0xec) [0x7f11f9ab6eec] (??:0)
[20] /home/michele/dev/thirdparty/godot/bin/godot.x11.tools.64(_start+0x2a) [0x5602df476b8a] (??:0)
-- END OF BACKTRACE --
```

Using Gentoo with glibc-2.26-r7, Godot from commit acd9646ede45f8c34f423e392e60bf128c953bd1.

**Comment by akien-mga** [comment] 2018-11-08 14:05
Closing as likely duplicate of #18833 (which is clearer as it doesn't involve Mono, which is probably a red herring here).

**Comment by akien-mga** [comment] 2018-11-08 14:08
Well actually I'm not sure yet it's the same bug, this one seems related to the Tiled imported given the log output I get:
```
SCRIPT ERROR: GDScript::reload: Parse Error: Too few arguments for 'parse_group_layer()' call. Expected at least 2.
   At: res://addons/vnen.tiled_importer/tiled_xml_to_dict.gd:488.
ERROR: reload: Method/Function Failed, returning: ERR_PARSE_ERROR
   At: modules/gdscript/gdscript.cpp:564.
SCRIPT ERROR: GDScript::reload: Parse Error: Could not fully preload the script, possible cyclic reference or compilation error.
   At: res://addons/vnen.tiled_importer/tiled_map_reader.gd:33.
ERROR: reload: Method/Function Failed, returning: ERR_PARSE_ERROR
   At: modules/gdscript/gdscript.cpp:564.
SCRIPT ERROR: GDScript::reload: Parse Error: Could not fully preload the script, possible cyclic reference or compilation error.
   At: res://addons/vnen.tiled_importer/tiled_import_plugin.gd:28.
ERROR: reload: Method/Function Failed, returning: ERR_PARSE_ERROR
   At: modules/gdscript/gdscript.cpp:564.
SCRIPT ERROR: GDScript::reload: Parse Error: Could not fully preload the script, possible cyclic reference or compilation error.
   At: res://addons/vnen.tiled_importer/vnen.tiled_importer.gd:33.
ERROR: reload: Method/Function Failed, returning: ERR_PARSE_ERROR
   At: modules/gdscript/gdscript.cpp:564.
ERROR: get_global_transform: Condition ' !is_inside_tree() ' is true. returned: get_transform()
   At: scene/2d/canvas_item.cpp:466.
ERROR: get_viewport_rect: Condition ' !is_inside_tree() ' is true. returned: Rect2()
   At: scene/2d/canvas_item.cpp:954.
ERROR: get_viewport_rect: Condition ' !is_inside_tree() ' is true. returned: Rect2()
   At: scene/2d/canvas_item.cpp:954.
ERROR: show_modal: Condition ' !is_inside_tree() ' is true.
   At: scene/gui/control.cpp:2092.
ERROR: get_global_transform: Condition ' !is_inside_tree() ' is true. returned: get_transform()
   At: scene/2d/canvas_item.cpp:466.
ERROR: get_viewport_rect: Condition ' !is_inside_tree() ' is true. returned: Rect2()
   At: scene/2d/canvas_item.cpp:954.
ERROR: grab_focus: Condition ' !is_inside_tree() ' is true.
   At: scene/gui/control.cpp:2063.
ERROR: get_tree: Condition ' !data.tree ' is true. returned: __null
   At: ./scene/main/node.h:263.
SCRIPT ERROR: GDScript::reload: Parse Error: Too few arguments for 'parse_group_layer()' call. Expected at least 2.
   At: res://addons/vnen.tiled_importer/tiled_xml_to_dict.gd:488.
ERROR: reload: Method/Function Failed, returning: ERR_PARSE_ERROR
   At: modules/gdscript/gdscript.cpp:564.
SCRIPT ERROR: GDScript::reload: Parse Error: Could not fully preload the script, possible cyclic reference or compilation error.
   At: res://addons/vnen.tiled_importer/tiled_map_reader.gd:33.
ERROR: reload: Method/Function Failed, returning: ERR_PARSE_ERROR
   At: modules/gdscript/gdscript.cpp:564.
SCRIPT ERROR: GDScript::reload: Parse Error: Too few arguments for 'parse_group_layer()' call. Expected at least 2.
   At: res://addons/vnen.tiled_importer/tiled_xml_to_dict.gd:488.
ERROR: reload: Method/Function Failed, returning: ERR_PARSE_ERROR
   At: modules/gdscript/gdscript.cpp:564.
SCRIPT ERROR: GDScript::reload: Parse Error: Could not fully preload the script, possible cyclic reference or compilation error.
   At: res://addons/vnen.tiled_importer/tiled_import_plugin.gd:28.
ERROR: reload: Method/Function Failed, returning: ERR_PARSE_ERROR
   At: modules/gdscript/gdscript.cpp:564.
SCRIPT ERROR: GDScript::reload: Parse Error: Could not fully preload the script, possible cyclic reference or compilation error.
   At: res://addons/vnen.tiled_importer/tiled_tileset_import_plugin.gd:28.
ERROR: reload: Method/Function Failed, returning: ERR_PARSE_ERROR
   At: modules/gdscript/gdscript.cpp:564.
SCRIPT ERROR: GDScript::reload: Parse Error: Could not fully preload the script, possible cyclic reference or compilation error.
   At: res://addons/vnen.tiled_importer/vnen.tiled_importer.gd:33.
ERROR: reload: Method/Function Failed, returning: ERR_PARSE_ERROR
   At: modules/gdscript/gdscript.cpp:564.
```

**Comment by akien-mga** [comment] 2019-01-22 11:03
I can't reproduce the crash on the current master branch either (79a4c41b).

There are a lot of script errors as mentioned above, but they all seem related to scripts in the tiled importer plugin, so they should be reported there if still reproducible in the latest version: https://github.com/vnen/godot-tiled-importer

**Closed by akien-mga** 2019-01-22 11:03 UTC
Labels: bug, topic:editor
