### ISSUE TITLE
Custom class icon display exception.

### ISSUE THREAD

**Issue by hdcheng** [godotengine/godot#74338] opened 2023-03-04 05:28 UTC
### Godot version

4.0.stable.official [92bee43ad]

### System information

Windows10,Vulkan,Intel i7-9700K ,NVIDIA GeForce GTX 1660 SUPER

### Issue description

I customized a class that inherits from Area2D.
Then i use @icon("res://assets/svgs/node.svg") to set the icon,but the icon displays abnormally on the inspector page.

my code:
```
@icon("res://assets/svgs/node.svg")
class_name Door
extends Area2D

@export var door_id : StringName

@export var target : PackedScene
```

![20230304132445](https://user-images.githubusercontent.com/51691177/222877615-e1c4b2c2-d9e7-4fa8-9262-60cbf20cc16a.jpg)

inspector display:

![20230304131134](https://user-images.githubusercontent.com/51691177/222877213-2167ccff-a03e-44e4-9756-477932b4263b.jpg)

### Steps to reproduce

user code:
```
@icon("res://xxxx/xxx.svg")
class_name CustomClass
extends Area2D

@export var str : StringName
```

### Minimal reproduction project

demo:
[Uploading BugDemo.7z…]()

**Comment by YuriSizov** [comment] 2023-03-04 12:23
Duplicate of https://github.com/godotengine/godot/issues/68962

**Closed by YuriSizov** 2023-03-04 12:23 UTC
