### ISSUE TITLE
Vulkan: Volumetric fog not rendering since 4.0.alpha13

### ISSUE THREAD

**Issue by isaacwilliams** [godotengine/godot#64029] opened 2022-08-07 02:31 UTC
### Godot version

4.0.alpha13

### System information

MacOS Monetary 12.4, ARM64 (Apple M1 Max)

### Issue description

Volumetric fog — including global world environment and fog volumes, are not rendered in Godot 4.0.alpha13, on my M1 Mac.

Godot 4.0, alpha 13:

<img width="1184" alt="alpha13" src="https://user-images.githubusercontent.com/819616/183272418-1dd8bb13-aa7b-4437-b677-86cb8c091c31.png">

Godot 4.0, alpha 12:

<img width="1183" alt="alpha12" src="https://user-images.githubusercontent.com/819616/183272421-24702b1f-7497-44cd-a1f3-2eedc458f6a8.png">

### Steps to reproduce

Open minimal reproduction project in Godot 4.0, alpha 13. Volumetric fog is not rendered.

### Minimal reproduction project

[volumetric-fog-minimal.zip](https://github.com/godotengine/godot/files/9276051/volumetric-fog-minimal.zip)

**Comment by Calinou** [comment] 2022-08-07 05:33
If you can [compile the engine from source](https://docs.godotengine.org/en/stable/development/compiling/index.html), you could look into [bisecting the regression](https://docs.godotengine.org/en/stable/community/contributing/bisecting_regressions.html) to greatly speed up troubleshooting.

4.0.alpha12 (`good`)'s commit hash is: `2c11e6d9efc42370a8d7537eaff8b1ea78a283e5`
4.0.alpha13 (`bad`)'s commit hash is: `82811367cb36d3124d4e8c0a9c4c7f82dc64f9e4`

**Comment by isaacwilliams** [comment] 2022-08-07 06:51
That was surprisingly easy to get it to compile from source!

Bisected to this commit: https://github.com/godotengine/godot/commit/bad5c659a42cf31e9004280dfa61838be1f6280a

Also noticed in any builds that were bad, I'm getting a _lot_ of error reports:

<img width="863" alt="Screen Shot 2022-08-07 at 4 42 29 pm" src="https://user-images.githubusercontent.com/819616/183278926-f1caaba8-d459-458c-80e7-0a7b42ea3eb6.png">

**Comment by RandomCatDude** [comment] 2022-08-07 08:12
I've noticed this too. though I should note that in my case, volumetric fog works fine, until I move the camera a bit, at which point it stops working and error spam just like this begins.

**Comment by pooroligarch** [comment] 2022-08-07 11:02
Can't reproduce this (Linux, GTX 1650) but the command line output shows:
```
ERROR: 1 shaders of type VolumetricFogShaderRD were never freed
   at: ~ShaderRD (servers/rendering/renderer_rd/shader_rd.cpp:702)
ERROR: 1 RID allocations of type 'N10RendererRD6ShaderE' were leaked at exit.
ERROR: 1 shaders of type VolumetricFogShaderRD were never freed
   at: ~ShaderRD (servers/rendering/renderer_rd/shader_rd.cpp:702)
```
Could be an issue the Nvidia driver ignores for some reason.

**Comment by BastiaanOlij** [comment] 2022-08-11 00:25
This is working fine for me: 

![image](https://user-images.githubusercontent.com/1945449/184045068-ed50ca8e-7aa7-481d-b1c0-4214f5893226.png)

However this includes #63901 which may end up fixing things.

**Comment by akien-mga** [comment] 2022-08-11 07:35
This is likely macOS only, and fixed by https://github.com/godotengine/godot/pull/64106.

**Closed by akien-mga** 2022-08-11 07:35 UTC
Labels: bug, topic:rendering, confirmed, regression, topic:3d

**Comment by isaacwilliams** [comment] 2022-08-11 22:23
@akien-mga @bruvzg thanks guys! Just built from master and it's working for me 🙏 

<img width="1182" alt="Screen Shot 2022-08-12 at 8 21 32 am" src="https://user-images.githubusercontent.com/819616/184252554-326efaad-ee43-45ee-9a26-05070a6842a9.png">
