### ISSUE TITLE
Godot headless export shader problem.

### ISSUE THREAD

**Issue by darthLeviN** [godotengine/godot#75530] opened 2023-03-31 10:42 UTC
### Godot version

godot 4.0+

### System information

Ubuntu 22, github actions

### Issue description

Godot headless doesn't import shaders properly.
I have tested it locally. the result is also available to see in the github actions for v0.0.7 tag :
https://github.com/darthLeviN/test-godot-release
https://github.com/darthLeviN/test-godot-release/actions/runs/4574117368

Since the logs are available in github actions it might make the job of detecting the problem easier.

### Steps to reproduce

Delete the ```.godot``` folder. Export with headless. if there is any problem with script import bugs, export twice so that this bug shows instead.

### Minimal reproduction project

https://github.com/darthLeviN/test-godot-release/releases/tag/v0.0.7

**Comment by Calinou** [comment] 2023-04-01 17:00
- Duplicate of https://github.com/godotengine/godot/issues/66842.

**Closed by Calinou** 2023-04-01 17:00 UTC
