### ISSUE TITLE
Easier camera placement and orientation via 3D viewport controls

### ISSUE THREAD

**Issue by abaky** [godotengine/godot#20248] opened 2018-07-18 15:36 UTC
When setting a camera in 3d space, right now you have to position it using move/rotate manipulators. Align selection with view is the only workaround right now to make camera placement a little easier. 

It would be nice to have option to go in the camera preview and then drive camera directly like you do with the default 3d view camera.

**Comment by akien-mga** [comment] 2018-07-18 16:01
That could be interesting, I just struggled today trying to place a camera and set its orientation with the move/rotation gizmos too. There could be an option to set a Camera node at the location of the 3D viewport's "camera". An alternative could be an option to click on a position the camera should look at.

**Comment by abaky** [comment] 2018-07-18 16:31
Align selection with view already does set camera node at the location of the 3d viewport camera. But it gets annoying having to constantly reposition viewport camera and realign camera node with it. 

My suggestion would be to add button on the top bar like you have when selecting mesh node or GIprobe node you get option to bake, when selecting camera node, top bar could present option to posses camera and drive camera directly, you would be able to position it exactly like you want and when you are done, you would press that button again and drop camera to that current position. 

The button could just fake driving camera node, it could just hide camera in the viewport and copy camera node FOV to work camera, you would be just basicly positioning the work camera to where you want camera node to end up and when you have placed camera, you press button again and camera node gets aligned with work camera and unhidden, work camera FOV is restored. 

If your scene has more cameras, button would have drop down where you could select which camera would you like to reposition.

(NOT a programmer, so my implementation is just me pushing hot air)

**Comment by dodgyville** [comment] 2018-07-19 09:40
it should work for any type of 3D node, not just Camera. It would be great to drive Lights and Position3D objects too.

**Comment by tinmanjuggernaut** [comment] 2019-05-29 07:26
It would be very nice to have a fly mode for the previewed camera that sets its position and rotation (like Blender's shift+f when looking through a camera). I think that the controls to move the editor camera should automatically work on the look-through camera once they check the Preview box. That seamless transition is what is expected by at least a few people on this thread.

**Comment by Calinou** [comment] 2019-12-24 09:53
Duplicate of #9550.

**Closed by Calinou** 2019-12-24 09:53 UTC
Labels: feature proposal, topic:editor, usability

**Comment by golddotasksquestions** [comment] 2021-09-14 23:51
For those interested, I created a proposal for this feature here: godotengine/godot-proposals#3297
