### ISSUE TITLE
function signature mismatch - ubuntu - html5 export

### ISSUE THREAD

**Issue by ripperdave** [godotengine/godot#46509] opened 2021-02-28 13:11 UTC
**Godot version:**
3.2.4 rc3
https://downloads.tuxfamily.org/godotengine/3.2.4/rc3/

**OS/device including version:**
![image](https://user-images.githubusercontent.com/46633266/109419480-f58f5500-79cd-11eb-8b3b-c9d2f726dd43.png)

**Issue description:**
HTML5 export does not work. Browser shows:
alert and function signature mismatch error message

f12:
exception thrown: RuntimeError: function signature mismatch,RuntimeError: function signature mismatch
    at godot_js_main(int, char**) (<anonymous>:wasm-function[11275]:0x21c48e)
    at main (<anonymous>:wasm-function[23592]:0x589d14)
    at Module._main (http://localhost:8060/tmp_js_export.js:9:329687)
    at Object.callMain (http://localhost:8060/tmp_js_export.js:9:334793)
    at http://localhost:8060/tmp_js_export.js:402:26
    at new Promise (<anonymous>)
    at http://localhost:8060/tmp_js_export.js:397:12
EngineConfig.onPrintError @ tmp_js_export.js:215
tmp_js_export.html:212 function signature mismatch
displayFailureNotice @ tmp_js_export.html:212

**Steps to reproduce:**
Export any project, add html5 export, select quick run. (firefox, brave browsers replicate the issue.)
Export was fine with 3.2.4 rc2

**Minimal reproduction project:**
[html5.zip](https://github.com/godotengine/godot/files/6056828/html5.zip)

**Comment by Calinou** [comment] 2021-02-28 13:47
Duplicate of https://github.com/godotengine/godot/issues/46352.

**Closed by Calinou** 2021-02-28 13:47 UTC
