### ISSUE TITLE
All key shortcuts starts not working

### ISSUE THREAD

**Issue by Clamydeef** [godotengine/godot#75449] opened 2023-03-29 07:15 UTC
### Godot version

4.0.1.stable

### System information

Windows 11

### Issue description

After a while after starting work, all keyboard shortcuts stop working, for example - Ctrl+S, Q, R, W, E, S, Shift+F11, Shift+F12 and others. Restarting Godot helps. The keyboard layout doesn't matter

### Steps to reproduce

Some time after the start of work (maybe switching between windows)

### Minimal reproduction project

Any

**Comment by YuriSizov** [comment] 2023-03-29 09:07
Thanks for the report, this is a duplicate of https://github.com/godotengine/godot/issues/74957, fixed by https://github.com/godotengine/godot/pull/75172. Will be available in 4.0.2.

**Closed by YuriSizov** 2023-03-29 09:07 UTC
