### ISSUE TITLE
VRAM Textures with transparency aren't correctly displayed on Android

### ISSUE THREAD

**Issue by Tobi-La** [godotengine/godot#29476] opened 2019-06-04 15:10 UTC
**Godot version:**
3.1.1 stable GLES 2

**OS/device including version:**
Oukitel K600 Pro
Samsung Galxy J5 duos

**Issue description:**
If you have a texture with transparency and import it with vram compression it looks like this:

![android](https://user-images.githubusercontent.com/25849067/58890647-500d5b80-86eb-11e9-925c-868bc1ec3429.png)

This is how it looks on windows:

![windows](https://user-images.githubusercontent.com/25849067/58890660-57cd0000-86eb-11e9-818a-32b1fdaa4763.PNG)

It's also working on Android if you set the compression method to something else.

**Steps to reproduce:**
- Import a texture with transparency with vram compression
- Activate transparency in the material

**Minimal reproduction project:**

[VRAMTransparency.zip](https://github.com/godotengine/godot/files/3253081/VRAMTransparency.zip)

**Comment by Calinou** [comment] 2019-06-04 15:51
This is a limitation with ETC1, which is the compression format used with the GLES2 renderer. I'll close this as a duplicate of https://github.com/godotengine/godot/issues/26211 :slightly_smiling_face:

**Closed by Calinou** 2019-06-04 15:51 UTC
Labels: bug, platform:android, topic:rendering
