### ISSUE TITLE
Collapse / Expand All doesn't work with mouse input

### ISSUE THREAD

**Issue by ssoher** [godotengine/godot#28626] opened 2019-05-02 21:30 UTC
In lists (Like the scene window list of nodes or the Create New Node window) Alt + Left Cursor key collapses all the nodes and their children and Alt + Right Cursor key expands the whole hierarchy of the children. 

But Alt + mouse clicks do not replicate the same behavior. When working with such UI items one tends to use the mouse so the behavior should be the same with mouse input and Alt key should be a modifier to the mouse clicks also.

![collapse](https://user-images.githubusercontent.com/4283979/57108065-5ac68080-6d3a-11e9-8014-e7d60ac26e1f.gif)

**Comment by Xrayez** [comment] 2019-07-24 12:36
#19936 was merged a bit late to fix this I guess, I wasn't aware of <kbd>Alt + Left/Right</kbd> feature, maybe because it wasn't present at the moment I started working on it or simply not documented. It also uses <kbd>Shift</kbd> for this instead. 🤔

**Comment by Calinou** [comment] 2020-07-16 09:59
@ssoher  Can you (or anyone else) still reproduce this bug in Godot 3.2.2 or any later release?

If yes, please ensure that an up-to-date Minimal Reproduction Project (MRP) is included in this report (a MRP is a zipped Godot project with the minimal elements necessary to reliably trigger the bug). You can upload ZIP files in an issue comment with a drag and drop.

**Comment by Xrayez** [comment] 2020-07-16 10:24
It currently doesn't work in 3.2.3 with <kbd>Alt</kbd> being pressed (works with keyboard arrows). Only <kbd>Shift</kbd> works as implemented in #19936. Perhaps this could be remapped to <kbd>Alt</kbd> if that's a big deal. 😮

**Comment by Calinou** [comment] 2020-07-16 12:08
@Xrayez I guess you could make it so it works with both <kbd>Alt</kbd> *or* <kbd>Shift</kbd>, just in case.

**Comment by Xrayez** [comment] 2020-07-16 12:17
@Calinou you previously mentioned that <kbd>Ctrl</kbd> is also common in other software: https://github.com/godotengine/godot/pull/19936#issuecomment-505522374. Perhaps we could handle all the modifiers, just in case? 😃

**Comment by Xrayez** [comment] 2020-07-16 14:40
I got curious how currently <kbd>Alt</kbd> works as described in OP.

https://github.com/godotengine/godot/blob/45d0799b5b4a62f7764c0b9e318a9d1547c7083b/scene/gui/tree.cpp#L2188-L2194

So yeah... All that was needed is simply adding the logic directly to `Tree` input handling to support mouse input (mainly talking about #19936). But given [solutions must be local](https://docs.godotengine.org/en/latest/community/contributing/best_practices_for_engine_contributors.html#solutions-must-be-local), it's no big deal after all!

Also CC @FeatherAntennae to be aware of this possibly hidden feature, in relation to #33984.

**Comment by FeatherAntennae** [comment] 2020-07-17 00:45
CTRL or SHIFT won't interfere directly if clicking on the arrow, but I recommend against using them for this. Some software do use them, but it's generally not seen as a good practice as it conflicts with the multi-select functionality which is also standard in a list.

People trying to select many things using Shift or CTRL, especially if trying to go as fast as possible, might accidentally hit the arrow, collapsing everything recursively. This could be a bit frustrating on big lists.

In #36926 I went with ALT, because it doesn't interfere with anything and it's kind of this key's purpose to alter or to give an alternative function! ^^

**Comment by KoBeWi** [comment] 2022-10-13 09:53
Scene tree already supports this, with Shift+Click.

**Closed by KoBeWi** 2022-10-13 09:53 UTC
Labels: enhancement, topic:core, topic:editor, usability
