### ISSUE TITLE
Stutters in linux mint 20 cinnamon

### ISSUE THREAD

**Issue by antonandrosov338** [godotengine/godot#47037] opened 2021-03-15 18:36 UTC
Hi, I encountered stuttering in godot when moving KinematicBody2D on linux mint 20 cinnamon and linux mint 18 xfce.

Tested on an old laptop with a Radeon HD 6400M / 7400M Series graphics card and an Intel (R) Celeron (R) CPU B820 @ 1.70GHz. 

When vsync is on, the frame rate fluctuates between 59-61, if it is off then the fps fluctuates between 394-397, In full screen mode the same results. 

I have attached a video, a project, and also the profiler results:

![Screenshot from 2021-03-15 21-27-25](https://user-images.githubusercontent.com/65621302/111203528-2f6b7880-85d6-11eb-8aaf-3a9975ef58fd.png)

[Video.zip](https://github.com/godotengine/godot/files/6143690/Video.zip)
[StuttersProject.zip](https://github.com/godotengine/godot/files/6143694/StuttersProject.zip)

**Comment by Calinou** [comment] 2021-03-15 19:17
Duplicate of https://github.com/godotengine/godot/issues/16766.

**Closed by Calinou** 2021-03-15 19:17 UTC

**Comment by antonandrosov338** [comment] 2021-03-15 20:37
> Duplicate of #16766 and possibly others. See [Fixing jitter and stutter](https://docs.godotengine.org/en/stable/tutorials/misc/jitter_stutter.html) in the documentation.

 This does not solve my problem

**Comment by Calinou** [comment] 2021-03-15 20:52
> This does not solve my problem

If you want a smooth gaming experience on Linux, you need to disable compositing in your window manager. Some window managers can do this automatically when an application is made fullscreen or when they detect specific applications as running, but this is far from something that always works.

Unfortunately, most window managers nowadays no longer allow disabling compositing. Notable exceptions to this rule are Xfxm (part of Xfce) and KWin (part of KDE).

**Comment by antonandrosov338** [comment] 2021-03-15 21:27
> > This does not solve my problem
> 
> If you want a smooth gaming experience on Linux, you need to disable compositing in your window manager. Some window managers can do this automatically when an application is made fullscreen or when they detect specific applications as running, but this is far from something that always works.
> 
> Unfortunately, most window managers nowadays no longer allow disabling compositing. Notable exceptions to this rule are Xfwm (part of Xfce) and KWin (part of KDE).

There is such a function, but it does not work for me. Stuttering disappears when I export the project without debugging.

**Comment by antonandrosov338** [comment] 2021-03-16 12:59
> > This does not solve my problem
> 
> If you want a smooth gaming experience on Linux, you need to disable compositing in your window manager. Some window managers can do this automatically when an application is made fullscreen or when they detect specific applications as running, but this is far from something that always works.
> 
> Unfortunately, most window managers nowadays no longer allow disabling compositing. Notable exceptions to this rule are Xfwm (part of Xfce) and KWin (part of KDE).

I managed to fix the stutter by enabling two features namely Debug->Deploy with Remote debug and Debug->Small Deploy with Network FS.
