### ISSUE TITLE
Scenes unable to be opened upon cylic preload() in script

### ISSUE THREAD

**Issue by FireCatMagic** [godotengine/godot#78128] opened 2023-06-12 02:12 UTC
### Godot version

4.1 beta1

### System information

Godot v4.1.beta1 - Windows 10.0.19045 - Vulkan (Mobile) - dedicated NVIDIA GeForce GTX 750 Ti (NVIDIA; 31.0.15.1694) - 12th Gen Intel(R) Core(TM) i5-12400F (12 Threads)

### Issue description
Update: I had a cylic preload in my script that prevented the file from being opened.
preload("res://Client/Scenes/GUI/Interface/Interface.tscn").instantiate()

Seemingly randomly, several of my scene files have failed to open with the following message in the console:
![image](https://github.com/godotengine/godot/assets/40964335/61c38e04-8b9f-448b-a038-69f10ef44eb6)

Oddly enough, after giving up on one of my old scenes that had corrupted, I tried to reopen it a few days later and it was working fine again despite displaying the "scene is invalid/corrupt" message.
Despite displaying as corrupted, the scene is still loaded into my game through and instance and works just fine, I just can't access it in editor.

### Steps to reproduce

According to my version control, I haven't updated the scene at all even though it worked earlier.
Today I edited the script that scene contained, saved it, and later came back and the scene couldn't be opened any more.

### Minimal reproduction project

n/a

**Comment by mrjustaguy** [comment] 2023-06-12 07:04
seems like something is going on in cache..

**Comment by KoBeWi** [comment] 2023-06-12 13:10
`nc == 0` error means there are no nodes. Can you send an example corrupted scene?

**Comment by dalexeev** [comment] 2023-06-12 15:17
> According to my version control, I haven't updated the scene at all even though it worked earlier.
> Today I edited the script that scene contained, saved it, and later came back and the scene couldn't be opened any more.

Can you attach the corrupted scene? If it hasn't changed, perhaps this is due to cyclic `preload()`. See https://github.com/godotengine/godot/issues/74253#issuecomment-1564227775.

**Comment by FireCatMagic** [comment] 2023-06-12 15:36
> `nc == 0` error means there are no nodes. Can you send an example corrupted scene?

Here!
[Scene.zip](https://github.com/godotengine/godot/files/11725267/Scene.zip)

**Comment by FireCatMagic** [comment] 2023-06-12 15:38
> seems like something is going on in cache..

I deleted my .godot folder, but the scene remains corrupted

**Comment by dalexeev** [comment] 2023-06-12 15:59
The file is not corrupted. Probably the problem is the one I wrote above or similar. Try replacing `preload()` in your scripts with `load()`, restart the editor and try opening the scene again.

**Comment by FireCatMagic** [comment] 2023-06-12 16:36
> The file is not corrupted. Probably the problem is the one I wrote above or similar. Try replacing `preload()` in your scripts with `load()`, restart the editor and try opening the scene again.

This was it. I changed the post title, but if this is a duplicate you can close it.

**Comment by dalexeev** [comment] 2023-06-12 16:38
CC @adamscott

**Comment by adamscott** [comment] 2023-06-12 18:34
I would close this issue as duplicate of #70985.

**Closed** 2023-06-12 20:18 UTC
Labels: bug, topic:core, topic:gdscript

**Comment by PLyczkowski** [comment] 2023-11-16 14:03
Here's what working for me to fix this error: close editor, search in the .editor folder for all files containing the corrupted scene's name (they are going to be name something like your_scene_name.tscn-editstate-2e5312b3e75d2338868814f479b1feeb.cfg), delete them, restart editor.
