### ISSUE TITLE
The font size is too small in Macosx Monterey

### ISSUE THREAD

**Issue by pingzh1215** [godotengine/godot#63391] opened 2022-07-24 15:23 UTC
### Godot version

4.0 alpha 12

### System information

Macosx Monterey 12.4 on Macbook Air M1

### Issue description

When I used Godot 3.4 and reopen Godot 4.0 alpha 12, I found the font is too small to see it clearly.

### Steps to reproduce

Open Godot 3.4, close godot 3.4 and open Godot 4.0, the bug will appear.

**Comment by Calinou** [comment] 2022-07-24 16:19
Can you take comparison screenshots between 3.4 and 4.0?

**Comment by pingzh1215** [comment] 2022-07-25 23:40
This is the screenshot of Godot 3.4:
<img width="1440" alt="Screen Shot 2022-07-26 at 07 35 12" src="https://user-images.githubusercontent.com/94329250/180892133-27b419ce-dab9-4492-8027-f69fc2aa87af.png">

and this is the screenshot of Godot 4.0:
<img width="1439" alt="Screen Shot 2022-07-26 at 07 37 05" src="https://user-images.githubusercontent.com/94329250/180892328-fb853747-43ec-4bce-8764-f8c76bcbe86d.png">

The font size of the Godot UI is too small relative to Godot 3.4.

**Comment by Calinou** [comment] 2022-07-25 23:46
It looks like something related to seamless display scaling isn't working as expected. Are you using a multi-monitor display by any chance?

cc @bruvzg

**Comment by pingzh1215** [comment] 2022-07-26 01:25
I use both Godot 4.0 and Godot 3.4.
When I set  **Interface > Editor > Display Scale** to 200% in the Editor Settings, the UI of editor seems good now.

<img width="1440" alt="Screen Shot 2022-07-26 at 09 21 05" src="https://user-images.githubusercontent.com/94329250/180902148-e4348db9-2607-4638-a236-6f1d268c174b.png">

but when I play the scene, it seems that all nodes in the scene was scaled to 50%:

<img width="1440" alt="Screen Shot 2022-07-26 at 09 25 15" src="https://user-images.githubusercontent.com/94329250/180902571-47ac92e1-a15f-4721-89b1-11f657bafc94.png">

**Comment by bruvzg** [comment] 2022-07-26 04:56
> Open Godot 3.4, close godot 3.4 and open Godot 4.0, the bug will appear.

What's your display configuration (single/multiple, scaling mode of each display)? Also, how exactly multiple copies of Godot are installed (locations, bundle names).

> You can see that the text of the label "Hello world" was too small.

This is expected, we do not have auto DPI scaling implemented for the project UI, it's only done for the editor, so you should track DPI changes and adjust UI scaling yourself. Or you can disable hiDPI support in the project settings (it was disabled by default in 3.x).

**Comment by pingzh1215** [comment] 2022-07-26 10:40
I use a single display in my Macbook air.

When I disable my hiDPI setting for my project, all things seems good now, thank you @bruvzg .

**Comment by Calinou** [comment] 2022-07-26 14:53
> Or you can disable hiDPI support in the project settings (it was disabled by default in 3.x).

Note that doing this is **not recommended** for production games, as lowDPI fallbacks suffer from all kinds of issues. Instead, follow the advice outlined in [Multiple resolutions](https://docs.godotengine.org/en/stable/tutorials/rendering/multiple_resolutions.html) so your game can correctly display at any resolution.

**Comment by lostminds** [comment] 2022-12-14 15:12
I've been using Godot 4.0.beta 2-8 on macOS 13.0.1 with two hiDPI monitors (with different scales even) and apart from some rare instances (like the color picker visualization icon) I've not seen any issues with retina interface scaling in the editor. So perhaps this is fixed for you as well @pingzh1215 and can be closed?

**Comment by Calinou** [comment] 2022-12-29 21:29
Closing per the above comment. Please comment if you can still reproduce this on the latest Godot version.

**Closed by Calinou** 2022-12-29 21:29 UTC
Labels: bug, platform:macos, topic:editor, needs testing, regression
