### ISSUE TITLE
Can't assign 'Nil' to a hinted variable

### ISSUE THREAD

**Issue by aaforcebox** [godotengine/godot#35392] opened 2020-01-21 02:45 UTC
**Godot version:** 3.2.rc2

**OS/device including version:** Windows 10

**Issue description:** We can't assign a 'Nil' to a hinted variable, so it becomes somewhat inconvenient in cases where a function returns either a valid value or Nil, like 'parse_json()':

```
var invalid_json = "{key;value}"
var dict:Dictionary = parse_json(invalid_json)
```

![print_error](https://user-images.githubusercontent.com/35024229/72771067-7b8f7880-3bde-11ea-8ccd-70b2d21a51a5.PNG)

This used to work on 3.1.2 ('invalid_json' would be null, so we could just check if it's null before using it), but then I tried to port a 3.1.2 project to 3.2.rc2 and every code using this 'feature' broke. If we remove the hint (Dictionary, in the example), it works just like before, but then we lose the benefits of a hinted variable.

**Steps to reproduce:** Run the code above on a 3.2.rc1 or rc2. It works on 3.2.beta3, so it was 'patched' after that.

**Minimal reproduction project:**
[parse_json_bug_3.2rc2.zip](https://github.com/godotengine/godot/files/4088940/parse_json_bug_3.2rc2.zip)

**Comment by volzhs** [comment] 2020-01-21 03:06
related with #27261?

**Comment by aaronfranke** [comment] 2020-01-21 05:33
This is intended behavior. For a feature proposal for making this possible, we already have https://github.com/godotengine/godot-proposals/issues/162, so we can probably close this and #27261

**Closed** 2020-01-21 18:09 UTC
Labels: archived
