### ISSUE TITLE
Control Node Navigation impossible using Joystick

### ISSUE THREAD

**Issue by meloonics** [godotengine/godot#55504] opened 2021-12-01 04:55 UTC
### Godot version

3.4.stable.official [206ba70f4]

### System information

Windows 10 Pro, GLES3, AMD Ryzen 7 2700X, NVIDIA GeForce GTX 1660 SUPER (Driver ver. 27.21.14.5671)

### Issue description

When using the Joystick on a gamepad, the game registers a change in focus every frame, which makes it impossible to navigate Menus. I submitted a similar issue a year ago [here](https://github.com/godotengine/godot/issues/42230#issue-705942840), but back then it only applied to OptionButton Nodes. This time (since I changed to 3.4) all Control Nodes seem to be affected.

### Steps to reproduce

Create a scene with a couple of Button Nodes.
Map `ui_left, ui_right, ui_up, ui_down` to your the corresponding Joystick axis of your gamepad in Project Settings.
Try to navigate the Buttons, using the Joystick (not the D-Pad!)
You will notice that the cursor moves erratically, because focus changes rapidly.

### Minimal reproduction project

[ui_test.zip](https://github.com/godotengine/godot/files/7630926/ui_test.zip)

**Comment by Zireael07** [comment] 2021-12-01 08:03
dupe of #54959

**Closed** 2021-12-01 08:13 UTC
