### ISSUE TITLE
The script editor reports a wrong error line.

### ISSUE THREAD

**Issue by Torguen** [godotengine/godot#88451] opened 2024-02-17 17:31 UTC
### Tested versions

v4.3.dev3.official [36e943b6b]

### System information

w10 64

### Issue description

Watch the video.
When I remove the last parenthesis, the editor indicates error on line 72, but the error occurs on line 70.

https://github.com/godotengine/godot/assets/19652075/baf6ff80-882f-4506-9ef7-80bbea0db1f2

### Steps to reproduce

Watch the video

### Minimal reproduction project (MRP)

...

**Comment by AThousandShips** [comment] 2024-02-17 17:40
Duplicate of https://github.com/godotengine/godot/issues/81046

**Closed by AThousandShips** 2024-02-17 17:40 UTC

**Comment by Torguen** [comment] 2024-02-17 17:47
https://github.com/godotengine/godot/assets/19652075/969bdb2a-a1d5-45d2-a7ed-66584bcbc770

Are you sure this is the same error?
Even though I don't have empty lines above it, the error still occurs.

**Comment by AThousandShips** [comment] 2024-02-17 18:10
It is, it points to the line where the error actually occurs, rather than the line that starts the parentheses, you could just do
```gdscript
foo(bar(
)
```
And it'd point to the second line, as you can put the expression on multiple lines, so the missing parentheses occurs when the expression fails

**Comment by AThousandShips** [comment] 2024-02-17 18:15
Also please paste the actual error message in text as well as the video in the future, it's much easier than having to find it in a small video on some devices :)
