### ISSUE TITLE
Disabling Window Resize feature should not disable the minimize button as well

### ISSUE THREAD

**Issue by alexandervrs** [godotengine/godot#4428] opened 2016-04-24 23:38 UTC
Tested on Windows. Mac & Linux possibly have this issue as well.

Disabling the **Resizable** feature through Project Settings or OS.set_window_resizable(false) should not disable BOTH maximize and minimize button, but just maximize.

_Using Godot 2.0.2_

**Comment by akien-mga** [comment] 2016-04-25 07:28
Relevant code chunks for:

- OSX: https://github.com/godotengine/godot/blob/master/platform/osx/os_osx.mm#L1407
- Windows: https://github.com/godotengine/godot/blob/a895e2e372c9df2a9972f38134ae0ea9c8bf45a8/platform/windows/os_windows.cpp#L1462
- X11: https://github.com/godotengine/godot/blob/67682b35b0e3057b2d630592815cd84596e741e3/platform/x11/os_x11.cpp#L792

(Note: haven't checked yet if the issue appears on OSX or X11)

**Comment by mattiascibien** [comment] 2016-05-03 12:07
Is this already fixed?

**Comment by akien-mga** [comment] 2016-05-03 12:15
> Is this already fixed?

Not willingly. Are you unable to reproduce it?

**Comment by mattiascibien** [comment] 2016-05-03 12:19
@akien-mga On Windows, I have tried on my godot compiled from master and it seems fine (using project settings)

**Comment by mattiascibien** [comment] 2016-05-03 12:24
I think [this](https://github.com/godotengine/godot/blob/a895e2e372c9df2a9972f38134ae0ea9c8bf45a8/platform/windows/os_windows.cpp#L1481) is the incriminating line as per http://stackoverflow.com/questions/8034053/removing-the-maximize-button-from-a-window-created-using-glfw

**Comment by akien-mga** [comment] 2016-05-03 17:17
For the reference, I checked on X11 and there is no bug, so I guess it's fine to close this issue once the Windows fix is merged.

**Closed** 2016-05-03 17:17 UTC
Labels: bug, junior job, platform:windows, topic:core
