### ISSUE TITLE
Cannot undo "Clear" action from script editors context menu

### ISSUE THREAD

**Issue by Keetz** [godotengine/godot#7567] opened 2017-01-17 11:10 UTC
Godot 2.1.1 stable
Ubuntu 16.04

Description:
Pressing the "Clear" option in the script editors context menu causes the script to be cleared, as expected, but it isn't possible to undo the clear (Ctrl+z or "Undo" in the context menu)

Steps to reproduce:
1. Create a script
2. Add some lines of awesome code
3. Right click and press "Clear"
4. Press undo as you want your lines of awesome code back
5. Start crying because your code is now gone

I'm guessing it is just "undo_redo->add_do_method()" and "undo_redo->add_undo_method()" that should be done where the clear method is located. Please correct me if I'm wrong.

**Comment by bojidar-bg** [comment] 2017-01-17 11:30
Actually, I'm not sure why the "clear" option exists altogether... does it make sense to keep it?

**Comment by Keetz** [comment] 2017-01-17 11:45
@bojidar-bg good question. @akien-mga had the same thoughts when i mentioned it on IRC.

Personally i wouldn't mind it gone, I only pressed it because i wanted to see if it did something clever. It is easy enough to clear your script without a dedicated button for it.

**Comment by bojidar-bg** [comment] 2017-01-17 12:02
@Keetz It is three keys or four mouse clicks without this option -- <kbd>Ctrl-A</kbd><kbd>Delete</kbd> or Right click -> Select all, Right click -> Delete.

**Comment by akien-mga** [comment] 2017-01-17 12:18
Sounds good enough to me, it's not like people clear scripts ten times a day.

**Comment by Hinsbart** [comment] 2017-01-29 11:19
Duplicate of #6329.
Also the clear option has already been removed from the script editor context menu in master, so closing.

**Closed by Hinsbart** 2017-01-29 11:19 UTC
Labels: bug, topic:editor
