### ISSUE TITLE
Godot 'Event' interface seems to be shifted

### ISSUE THREAD

**Issue by cpodgell** [godotengine/godot#25231] opened 2019-01-22 16:01 UTC
**Godot version:**

3.1 Beta

**OS/device including version:**

Windows 10 Pro Version 1703

**Issue description:**

When my mouse hovers over a button, it's not selected.  This is throughout the entire interface.  It seems the interfaces graphical display is in one spot, and the 'detectors' are shifter to another.  A picture attach illustrated the issue

**Steps to reproduce:**
Notice in the picture, the mouse is hovered below the button?  That's how you selected a button.  This occurs for every selectable control in Godot
![godotscreen](https://user-images.githubusercontent.com/46933015/51547790-cfc11a80-1e1b-11e9-89ec-70bc862b4d71.png)

**Minimal reproduction project:**

**Comment by groud** [comment] 2019-01-22 16:12
I cannot reproduce the bug on ArchLinux

**Comment by Zireael07** [comment] 2019-01-22 16:14
What GPU? I seem to recall Intel drivers bug manifesting exactly like this...

**Comment by groud** [comment] 2019-01-22 16:18
Related to #17563

**Comment by groud** [comment] 2019-01-22 16:19
And to #8902. This is likely driver bug, could you please update your driver and try again ?

**Comment by cpodgell** [comment] 2019-01-22 16:52
My video card driver is:

Intel(R) HD Graphics 620
Chip type: HD Graphics Family

I will try to update the driver and get back

**Comment by akien-mga** [comment] 2019-01-22 22:11
It could also be #23069. If so current drivers are still buggy, but a fix should hopefully be rolled out by Intel in coming weeks.

**Comment by akien-mga** [comment] 2019-01-26 00:54
Closing as duplicate of #23069 for now, the symptoms are quite similar. Please comment if it doesn't seem to be that.

**Closed by akien-mga** 2019-01-26 00:54 UTC
Labels: bug, topic:editor
