### ISSUE TITLE
GDscript documentation comments: tooltip not showing up for custom signals

### ISSUE THREAD

**Issue by Necco-Z** [godotengine/godot#81058] opened 2023-08-27 22:13 UTC
### Godot version

4.1.1 stable

### System information

Godot v4.1.1.stable unknown - Arch Linux #1 SMP PREEMPT_DYNAMIC Mon, 31 Jul 2023 11:41:04 +0000 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1650 () - Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz (12 Threads)

### Issue description

When using GDScript documentation comments, the tooltips show in the editor for variables (excluding the cases mentioned in #78934), but it doesn't show for custom signals.
When using comments for variables, the following shows up, as expected:
![image](https://github.com/godotengine/godot/assets/41708431/19c07bcf-76bd-4ef2-8b4f-31be7cc86e16)
For signals, however, nothing is shown, as if nothing was set:
![image](https://github.com/godotengine/godot/assets/41708431/1ffec539-927a-4aec-a94a-c9e528dc1937)

### Steps to reproduce

- Create a new scene with a Node in it
- Add the following script:
```
extends Node

signal test_signal ## This won't show.

@export var test_variable := 0 ## This shows in the tooltip.
```
- Test the tooltips.

### Minimal reproduction project

Any project will do, the lines in the steps to reproduce are enough.

**Comment by dalexeev** [comment] 2023-08-28 06:10
* Duplicate of #80397.
* Fixed by #80411.
* Will be included in 4.2 dev 4.

Thanks for reporting the bug nonetheless!

**Closed by dalexeev** 2023-08-28 06:10 UTC
