### ISSUE TITLE
is_type_compatible: Parser bug (please report): Trying to check compatibility of unset target type

### ISSUE THREAD

**Issue by Liam19** [godotengine/godot#65958] opened 2022-09-17 02:56 UTC
### Godot version

4.0 Beta 1

### System information

Windows 10

### Issue description

Seemingly randomly, most of my scripts that reference autoload singletons suddenly stopped working. 

The error they all have is:
Could not parse global class "*class*" from "*path*".

Example of one of my scripts:
![Godot bug](https://user-images.githubusercontent.com/22169419/190837739-c37e504e-159c-467d-a19e-3338a8cc60c5.png)

Error that appears in the debugger tab:
![Godot bug](https://user-images.githubusercontent.com/22169419/190837847-78339c6d-91a5-461e-a957-68adc85d8006.png)

I tried making a minimal reproduction project but it seems to happen randomly.  One minute my code works, then suddenly it started throwing multiple instances of that same error. My project is stuck in a state of not working and a restart of Godot doesn't fix it. [](url)

### Steps to reproduce

Have scripts that reference global classes (autoload singletons). 

That's about the limit of my understanding sorry.

**Comment by Calinou** [comment] 2022-09-17 17:52
Duplicate of https://github.com/godotengine/godot/issues/44375.

**Closed by Calinou** 2022-09-17 17:52 UTC
