### ISSUE TITLE
[4.0 a1] Performance issues & script profiler not working

### ISSUE THREAD

**Issue by Zireael07** [godotengine/godot#57309] opened 2022-01-27 13:33 UTC
### Godot version

4.0 alpha 1

### System information

Linux Manjaro, Vulkan, Intel Kaby Lake

### Issue description

Very simple testing scene has massively degraded performance compared to the Godot 3 version. 

Godot 3 had 30+ fps in this scene. Godot 4 has 11-12 (!!!!) and monitor shows process to be at fault, taking HUNDREDS of ms. The project is basically a ported project from Godot 3, no code changes apart from API upgrades and some things removed/commented out to get it running (so if anything, there's LESS code now than there used to be, so it should run better). This seems to point at some sort of an engine regression!

Cannot debug it further as script profiler doesn't work (can't switch it on after running the scene, if I press start before running the scene/project it just stays empty) 
Interestingly, remote scene tree works fine <3

### Steps to reproduce

Open the project below, try to run Spatial_simple.tscn.

(Don't pay attention to some meshes/UI elements being in weird spots or not working, like the mirror, or, well, the kinematic car not moving :P)

@ me if it doesn't run on your computer, since it likely means I missed committing some fix/file.

### Minimal reproduction project

Not minimal :P

https://github.com/Zireael07/FreeRoamRoguelikeRacerPrototype/commit/d8cc2dfa3aa120c30f493223a86350837c65140d

**Comment by Calinou** [comment] 2022-01-27 13:37
Could you try to compile a debug build of the editor and [use a C++ profiler](https://docs.godotengine.org/en/latest/development/cpp/using_cpp_profilers.html) to run it?

**Comment by Zireael07** [comment] 2022-01-27 13:41
I probably could - I did it a couple of times with the earlier builds but a) not any time soon (weekend at the earliest - day job takes up time) and b) I suspect it's some sort of a user error on my end, like misusing the new dynamic character API or something. (Since well, the car doesn't move and it should :P )

**Comment by Calinou** [comment] 2022-01-27 15:45
> (I didn't close the issue because there's STILL the problem of the script profiler NOT working AT ALL)

This is already reported in https://github.com/godotengine/godot/issues/44252, so I'll close this issue as a duplicate of https://github.com/godotengine/godot/issues/44252.

**Closed by Calinou** 2022-01-27 15:45 UTC
Labels: bug, topic:core, topic:gdscript, needs testing, regression, performance

**Comment by Zireael07** [comment] 2022-01-27 15:48
Got it. I'll reopen if I manage to get a debug build and find out what is going on with the viewports regressions, though.

**Comment by Calinou** [comment] 2022-01-27 15:49
> Got it. I'll reopen if I manage to get a debug build and find out what is going on with the viewports regressions, though.

It's likely that viewports became more expensive to instance and housekeep: https://github.com/godotengine/godot/issues/48978

**Comment by tavurth** [comment] 2022-03-11 15:31
Damn, this was the dealbreaker for me about moving to Godot 4 already :(
