### ISSUE TITLE
`modulate` stops working on CanvasItem node that has `y_sort_enabled=true`  and is a child of another CanvasItem node with `y_sort_enabled=true`

### ISSUE THREAD

**Issue by eh-jogos** [godotengine/godot#75589] opened 2023-04-02 11:00 UTC
### Godot version

4.0.1 stable

### System information

Manjaro Linux using i3, Foward+

### Issue description

Previously in Godot 3.x you could have something like this:
![image](https://user-images.githubusercontent.com/13070158/229348455-7a0bb3f2-d1e8-4634-87a8-b3e9490d2ec3.png)

And it would just work. You could use modulate on children YSort in any way you wanted.

Now the corresponding setup in Godot 4 doesn't work
![image](https://user-images.githubusercontent.com/13070158/229348497-5817426f-96f0-4a47-9e50-c3149a1de046.png)

This is also true for Controls:
![image](https://user-images.githubusercontent.com/13070158/229348390-c3432efc-833a-4cd0-a8e8-18d9a5e269bf.png)

I did not try to mix and match Node2Ds and Controls.

In my game what I'm actually trying to do is just animate alpha in one of these nodes that have `y_sort_enabled` but are not the "root" of the `y_sort_enabled` chain.

I tried to look at the documentation both for `modulate`  and for `y_sort_enable` and found no mention or warning about this behavior, and compared to how it worked on 3.x, seems like a bug to me.

### Steps to reproduce

Use MRP below or:
- Create a CanvasItem node and enable `y_sort_enabled` 
- Add a CanvasItem node to it as a child and also enable `y_sort_enabled`  on it
- Add a CanvasItem node to the previous node, something with any visual feedback.
- Try to change the `modulate`  property of each node that has `y_sort_enabled` , you'll see it will work on the "root" but not on the "child"

### Minimal reproduction project

[y_sort_enabled_modulate.zip](https://github.com/godotengine/godot/files/11131980/y_sort_enabled_modulate.zip)

**Comment by KoBeWi** [comment] 2023-04-02 11:24
Duplicate of #63994

**Closed by KoBeWi** 2023-04-02 11:24 UTC
