### ISSUE TITLE
Sprite Texture Flags are reset to have Filter ticked / on every time I load my project

### ISSUE THREAD

**Issue by therealrobster** [godotengine/godot#16458] opened 2018-02-07 01:50 UTC
**Godot version:**
3.0 Official 

**OS/device including version:**
Ubuntu Linux 16.0.4 LTS
Intel® Iris Pro Graphics 580 (Skylake GT4e) 
Intel® Core™ i7-6770HQ CPU @ 2.60GHz × 8 

**Issue description:**
I have a scene that will be a character.  It's made up of many sprites (one for each arm, leg, etc).  When I import the texture I have to manually turn off the Filter Texture Flag.  That's fine, but then:
- If I reload the project, the filter flags are all ticked again.
- If I place this character scene into another scene (say the game level), then the flags are unticked again.

**Steps to reproduce:**
Create a sprite, import texture, turn off Filter, save scene, import into another scene and texture filters will be back on.  If not in the viewer/Editor then definitely in the game when running with F5.
[soldat.zip](https://github.com/godotengine/godot/files/1701425/soldat.zip)

**Minimal reproduction project:**
Attached a test project to show.

**Comment by Noshyaar** [comment] 2018-02-07 02:27
Reimport the textures using the Import Dock with Filter option disabled.

**Comment by therealrobster** [comment] 2018-02-07 02:34
That worked.  Am I going to have to do that every time for every sprite though?

**Comment by Noshyaar** [comment] 2018-02-07 02:59
You can set import options as default by clicking on the 'Preset..'

**Comment by Arkhano** [comment] 2018-02-12 21:58
Thank you for the the help. 

Also, isn't better to make the filter checkbox false as default in the next version of godot (3.1)? Even this being easy to setup in the import settings almost all the tutorials I have watched turned this as false in the check box.

**Comment by vnen** [comment] 2018-02-12 23:40
I think filter is more common than non-filter. If you're looking at pixel-art games only, then it's common to remove the filtering, but that's just one art style between many. 3D textures should have filter by default, for instance.

Anyway, I'm closing this since it's not a bug.

**Closed by vnen** 2018-02-12 23:40 UTC

**Comment by zappedfish** [comment] 2019-02-17 14:30
Hate to comment on an archived bug, but this is soooooo unintuitive. Any chance for this weird work flow to change in the future?
