### ISSUE TITLE
Built-in method binds with arguments are broken in the release builds.

### ISSUE THREAD

**Issue by bruvzg** [godotengine/godot#43161] opened 2020-10-28 13:15 UTC
**Godot version:**
4.0, 7495fdfc5b

**OS/device including version:**
macOS 10.15.7, Windows (Using Wine on macOS, llvm-mingw build).

**Issue description:**
All built-in class methods with the arguments, called from GDScript fail with the following error ("expected at most 0" for any method):

```
SCRIPT ERROR: Parse Error: Too many arguments for "<method_name>" call. Expected at most 0 but received <x>
          at: GDScript::reload (<res>)
ERROR: Method/function failed. Returning: ERR_PARSE_ERROR
   at: reload (modules/gdscript/gdscript.cpp:633)
```

Same code runs fine in the editor, code editor also shows correct number of arguments.

**Steps to reproduce:**
Run any project with GDScript using release export template binary.

**Minimal reproduction project:**
[rel_fail.zip](https://github.com/godotengine/godot/files/5451982/rel_fail.zip)

**Comment by akien-mga** [comment] 2020-10-28 13:32
Duplicate of #41706.

**Closed by akien-mga** 2020-10-28 13:32 UTC
Labels: bug, regression, topic:gdscript
