### ISSUE TITLE
Color picked from screen doesn't immediately update the button

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#62858] opened 2022-07-09 15:32 UTC
### Godot version

d26442e

### System information

Windows 10 x64

### Issue description

![godot_bvWp9WYBiX](https://user-images.githubusercontent.com/2223172/178112275-a80faf93-1266-48c6-965a-cf6ddf97a755.gif)
Probably some signal isn't emitted.

### Steps to reproduce

1. Have a ColorPickerButton (can use one from the inspector)
2. Click it and use the pick button to pick color from screen

**Comment by fire** [comment] 2022-07-09 16:28
I can reproduce this and have seen this bug when using the color picker.

**Comment by Rindbee** [comment] 2022-07-10 10:40
Because when sampling, the signal is emitted when the LMB is released, but the internal PopupPanel closes when the left button is pressed. So when sampling, the `color_changed` signal will not be emitted.

**Comment by MinusKube** [comment] 2022-07-11 14:38
I believe the problem appeared with a change to how the popup/viewport works.
Even with the `screen` Control set as top level, it's still behind the picker's PopupPanel. So, when you click on the screen, instead of calling the `_screen_input` method, it's calling the ColorPicker's notification method with a `NOTIFICATION_WM_CLOSE_REQUEST`, which simply hides `screen` without updating the color.

This could be worked around by adding a `emit_signal(SNAME("color_changed"), color);` before the `screen->hide();` here:
https://github.com/godotengine/godot/blob/d26442e709f6361af9ac755ec9291bb43f2cd69b/scene/gui/color_picker.cpp#L103-L107

But there's probably a better way of doing that?

I tried to fix it more cleanly by creating a new fullscreen popup with a transparent background, but I didn't manage to do this, the background always appeared black.

**Comment by Rindbee** [comment] 2022-07-11 15:09
I'm a little curious about how the screenshot tool/screen recording tool works. Get the image behind the window and draw inside the front window to simulate transparency?

**Comment by fire** [comment] 2022-07-11 16:14
This describes the screen tool works.

1. https://github.com/godotengine/godot/blob/d26442e709f6361af9ac755ec9291bb43f2cd69b/editor/editor_node.cpp#L2897-L2898
2. https://github.com/godotengine/godot/blob/d26442e709f6361af9ac755ec9291bb43f2cd69b/editor/editor_node.cpp#L2970-L2981
3. https://github.com/godotengine/godot/blob/d26442e709f6361af9ac755ec9291bb43f2cd69b/editor/editor_node.cpp#L2957-L2968

The screen recording tool uses another path.

**Comment by JohanAR** [comment] 2022-08-02 20:05
I'm looking at this right now, I think it happens because _screen_input never gets a valid InputEventMouseButton:

```
Ref<InputEventMouseButton> bev = p_event;
if (bev.is_valid() && bev->get_button_index() == MouseButton::LEFT && !bev->is_pressed()) {
	emit_signal(SNAME("color_changed"), color);
```

Which leads to that it never emits the color_changed event.

Couldn't figure out what's causing it, might continue with it tomorrow unless someone else fixes it faster.

**Comment by JohanAR** [comment] 2022-08-03 19:12
@MinusKube added your suggested workaround to a PR. I think fixing it for now is preferable to holding off for a proper solution.

**Comment by akien-mga** [comment] 2023-02-17 08:37
This appears to be fixed in `master` according to https://github.com/godotengine/godot/pull/63886#issuecomment-1434293609.

**Closed by akien-mga** 2023-02-17 08:37 UTC
Labels: bug, topic:gui
