### ISSUE TITLE
Animation Player animation drop-down not showing scrollbars sometimes with a long list with 4.3-beta1

### ISSUE THREAD

**Issue by lazaromenezes** [godotengine/godot#93333] opened 2024-06-19 01:14 UTC
### Tested versions

- Bug happens in v4.3.beta1.official [a4f2ea91a]
- It **doesn't** happen in v4.2.2.stable.official [15073afe3]

I haven't checked 4.3 prior beta1 yet.

### System information

Godot v4.3.beta1 - Windows 10.0.22631 - GLES3 (Compatibility) - NVIDIA GeForce MX450 (NVIDIA; 31.0.15.5222) - 11th Gen Intel(R) Core(TM) i7-11390H @ 3.40GHz (8 Threads)

### Issue description

I've imported a 3D model with a long collection of animations that, when using the dropdown, gets bigger than my screen height. It intermittently hides the scrollbar, making it impossible to reach lower items into the list, as seen in the video bellow. It happens in both drop-downs: Inspector and Animation tab.

https://github.com/godotengine/godot/assets/8123916/b000738f-4736-4db0-b5ac-87706c2a59a1

I couldn't reproduce it using 4.2.2

https://github.com/godotengine/godot/assets/8123916/b875dbd4-f9a5-4d23-81c9-972109326437

Notice I haven't checked other drop-downs yet, but I can do it next if needed.

### Steps to reproduce

1. Create a new project
2. Create a new 3d scene
3. Import a model with a lot of animations
4. Add the model in your scene and make it local
5. Check the animation player drop downs

### Minimal reproduction project (MRP)

[sandbox_43.zip](https://github.com/user-attachments/files/15894169/sandbox_43.zip)

**Comment by lazaromenezes** [comment] 2024-06-19 01:22
Ohh nice, I just noticed the drop-downs weren't captured in my screen recorder :(

I'll try grabbing new videos with a different tool, mean while, I'm posting some screenshots

4.3-beta1 - No scrollbar within animation tab drop-down

![4 3_animation_tab_without_scrollbar](https://github.com/godotengine/godot/assets/8123916/f104d3f4-a13a-4a33-b02f-114070d25d40)

4.3-beta1 - With scrollbar when looking at the inspector

![4 3_inspector_with_scrollbar](https://github.com/godotengine/godot/assets/8123916/2ed1a320-f789-4cdb-aaec-db555a9147a3)

4.3-beta1 - No scrollbar when looking at the inspector

![4 3_inspector_without_scrollbar](https://github.com/godotengine/godot/assets/8123916/b640f126-1d68-4b8f-9fc3-6c8ce2a2b8e2)

**Comment by JekSun97** [comment] 2024-06-19 03:15
I confirm this problem.
My slider disappears after the second click on the animation selection.
However, for some reason the editor with your project freezes terribly, the mouse cursor moves jerkily, most likely there is some kind of memory leak here.

https://github.com/godotengine/godot/assets/130399274/c826b1b9-bded-46c7-a6cf-59e095e003b4

I could not find out which version this starts with, since before 4.3 beta1 your glb file cannot be created anywhere, not in one of the dev versions.

**Comment by matheusmdx** [comment] 2024-06-19 10:28
The slider dissapearing part is a duplicate of https://github.com/godotengine/godot/issues/92614 and was already solved in pr https://github.com/godotengine/godot/pull/92664

<br>

> However, for some reason the editor with your project freezes terribly, the mouse cursor moves jerkily, most likely there is some kind of memory leak here.

I can't reproduce the lag here, make sure you're not reproducing bug #92759 somehow

**Comment by lazaromenezes** [comment] 2024-06-19 11:38
> The scroll dissapearing part is a duplicate of #92614 and was already solved in pr #92664

Awesome! I missed it searching the issues. So I believe we should close this one?

**Comment by Calinou** [comment] 2024-06-19 13:46
Thanks for the report! Consolidating in https://github.com/godotengine/godot/issues/92614. The fix will be available in 4.3.beta2 (or you can [build the `master` branch from source](https://docs.godotengine.org/en/latest/contributing/development/compiling/index.html) right now).

**Comment by matheusmdx** [comment] 2024-06-19 16:41
> > The scroll dissapearing part is a duplicate of #92614 and was already solved in pr #92664
> 
> Awesome! I missed it searching the issues. So I believe we should close this one?

Yes, you can close the issue (Calinou forgot to close 😆 )

**Closed** 2024-06-19 16:43 UTC
Labels: bug, archived, topic:editor, regression
