### ISSUE TITLE
only one blendshape from multiple mesh instances can apply to a shared resource at a time

### ISSUE THREAD

**Issue by lukostello** [godotengine/godot#54062] opened 2021-10-21 09:13 UTC
### Godot version

v3.3.4.stable.official [faf3f883d]

### System information

Windows 10, GLES3, GeForce 750ti

### Issue description

I've got a bunch of meshes instances which should be able to share the same mesh resource but have their own independent blendshapes the same way they can have independent material overrides or shader parameters as I fully expect given that the blendshapes are stored as a mesh instance variable not a mesh resource property. But instead any changes made to one mesh will effect all others. 
![blendshapebug](https://user-images.githubusercontent.com/53994293/138245698-6a69a25e-c2af-44d9-bf91-60d6a900e677.gif)

### Steps to reproduce

run the code, pressing enter changes it from 0 to 1 and back. I encourage you to change which wall is set to wall. And check out the values of the blendshapes in the other walls. 

### Minimal reproduction project

[BlendshapesBug.zip](https://github.com/godotengine/godot/files/7387650/BlendshapesBug.zip)

**Comment by Chaosus** [comment] 2021-10-21 10:13
It's not a bug. The mesh can be shared across multiple mesh instances. In order to "fix" this you should simply make it unique:

![image](https://user-images.githubusercontent.com/3036176/138257763-329c0c7a-bdb4-4544-8314-2e8ccba98f0b.png)

**Comment by Calinou** [comment] 2021-10-21 14:15
> I know that blender 4.0 is doing a thing where each instance can have its own uniforms. I think a similar structure would work here. Perhaps the code can be reused.

[This is already available in 4.0 with per-instance uniforms.](https://godotengine.org/article/godot-40-gets-global-and-instance-shader-uniforms) It can't be backported to `3.x` though.

**Comment by lukostello** [comment] 2021-10-21 17:06
can't believe I said blender 4.0 I  meant godot 4.0

**Comment by lukostello** [comment] 2021-10-24 00:33
@fire I hear you're handling the importing stuff. Whats your take on this? Is it even possible to have one mesh resource apply different blendshapes for each instance? In order for it to render would it have to make mesh resources for each time there are different blendshapes applied? Either way it is implemented this should be a 4.0 milestone. Mostly because for all instances sharing one mesh resource only one instance can apply them to the shared mesh and it is often difficult to tell which one can.

**Comment by fire** [comment] 2021-10-24 01:31
Does forcing importer make the mesh resources unique as a fix sound good?

This appeared to be a rendering feature, so the most local solution is to make the importer duplicate the resource.

**Comment by lukostello** [comment] 2021-10-24 02:08
@fire that sounds like a good quick fix for 3.0 but for 4.0 I think it shouldn't have to compensate by having the blendshapes with the mesh resource from the getgo or even do the mesh details resource thing like I was talking about but that only in the instance that one mesh resource can handle multiple blendshape values. In my game I've got lots of objects who I want to share both mesh and blendshapes so your quick fix doesn't help my scenario. Although I'm probably in a small minority.

**Comment by lukostello** [comment] 2021-10-29 20:32
@starry-abyss doing so would make it impossible for me to share mesh resources on a bunch of mesh instances which all have the same blendshapes.

**Comment by lyuma** [comment] 2021-10-29 22:29
I think this should be closed as duplicate of #10402. Or is this a different issue?

Also, how does this issue relate with the proposal godotengine/godot-proposals#2465

**Comment by lukostello** [comment] 2021-10-29 22:36
@lyuma these are different but probably related bugs. I'm not experiencing any visual glitches like that. In mine its that I've got multiple mesh instances that share a mesh resource and only one of the instance's blend shape values are applied the rest are ignored.

**Comment by starry-abyss** [comment] 2021-10-30 04:09
Sharing as in for optimization or sharing as in they are the same visually? I'm not sure how it works in Godot, but I guess it's possible to make it shared in .pck, while have it duplicated in RAM.

Then if you want sharing even in RAM, for rendering optimization (#53244), the temporary solution of just duplicating could be undone as part of the next PR. I don't see how one prevents the other. I understand that the temporary solution is probably not an improvement for your project because of #53244, but there are other users with less blend shapes at the same mesh at once, for whom it's an improvement.

**Comment by smix8** [comment] 2023-05-02 13:44
I think this is fixed in Godot 4, I can not reproduce the issue anymore.

Properly because in Godot 4 the BlendShape blend_weights are no longer part of the Mesh Surface but now part of the MeshInstance in the RenderingServer mesh storage so each instance has its own weights.

**Comment by fire** [comment] 2023-05-02 14:15
Closing based on the previous comment

**Closed by fire** 2023-05-02 14:15 UTC
Labels: enhancement, topic:core
