### ISSUE TITLE
move_and_slide's infinite_inertia = false  depends on rigidbody's sleeping status

### ISSUE THREAD

**Issue by Einlander** [godotengine/godot#33988] opened 2019-11-29 08:56 UTC
**Godot version: 3.1.1 (Steam Version)**

**Windows 10 1903**

**Issue description:**
When using using move_and_slide in a Kinematicbody with infinite_inertia = false will push a rigidbody if the object is not sleeping.

**Expected Behavior:**
I expected move_and_slide to not move a rigidbody at all

**Steps to reproduce:**
Hit a RigidBody a KinematicBody before the rigidbody falls asleep.

**Minimal reproduction project:**
Will upload when I have time.

**Comment by madmiraal** [comment] 2019-12-01 08:29
Duplicate of #31981?
Duplicate of #25857?

**Comment by akien-mga** [comment] 2020-01-13 14:22
Closing as duplicate of #31981.

**Closed by akien-mga** 2020-01-13 14:22 UTC
Labels: bug, topic:physics
