### ISSUE TITLE
Export menu expands below my phone screen

### ISSUE THREAD

**Issue by Karyl256** [godotengine/godot#82739] opened 2023-10-03 19:19 UTC
### Godot version

4.0 from google play

### System information

Android

### Issue description

I was trying to export my game and after I changed from a app which was rotated other way, the bottom two buttons of the export menu are inaccesible (beyond screen)

![Screenshot_20231003-211609_Godot Editor 4](https://github.com/godotengine/godot/assets/115658627/9185a6e2-f7c3-4942-80a1-74fbb6f70ade)

### Steps to reproduce

I don't know how it happened (sorry)

### Minimal reproduction project

.

**Comment by AThousandShips** [comment] 2023-10-08 10:34
Duplicate of https://github.com/godotengine/godot/issues/73130

**Closed by AThousandShips** 2023-10-08 10:34 UTC
Labels: bug, platform:android, topic:editor, topic:gui
