### ISSUE TITLE
Show Tilemap Collision will cause lag in editor

### ISSUE THREAD

**Issue by firecloud888** [godotengine/godot#47780] opened 2021-04-10 21:29 UTC
**Godot version:**
Godot 3.3 RC6

**OS/device including version:**
Windows 10 Professional

**Issue description:**
Editor has a very severe lag if tilemap show collision shape is on.

**Steps to reproduce:**
Make a simple tileset and add it to tilemap,  turn on the show collision shape

**Minimal reproduction project:**
[TilemapBboxLag.zip](https://github.com/godotengine/godot/files/6290795/TilemapBboxLag.zip)

**Comment by Calinou** [comment] 2021-04-10 21:34
Duplicate of https://github.com/godotengine/godot/issues/47509 (fixed in 3.3rc8).

**Closed by Calinou** 2021-04-10 21:34 UTC
