### ISSUE TITLE
[Workflow] Bloom Effect is applied to gizmos

### ISSUE THREAD

**Issue by nonunknown** [godotengine/godot#50610] opened 2021-07-19 13:14 UTC
### Godot version

3.3.4 beta-1

### System information

manjaro Gnome 21, AMD R7 200 series, Intel i3 3.0 GHZ,8GB RAM

### Issue description

When you apply the bloom shader effect from worldenvironment node it is applied to the editor gizmos, which makes harder to use it:

Night:
![image](https://user-images.githubusercontent.com/58845030/126165152-9f0e87d2-8de4-452d-bf31-b7784f93121f.png)

Day:
![image](https://user-images.githubusercontent.com/58845030/126165179-45a00106-b34b-4239-9c56-d485e6164565.png)

*Workarounds*

* You can save the worldenviroment res, clear it, and just load when about to play (which makes the workflow a cumbersome)

* See https://github.com/godotengine/godot/issues/50522

### Steps to reproduce

* Create a 3d Scene
* Attach a WorldEnvironment Node
* Enable Bloom

### Minimal reproduction project

N/a

**Comment by Zireael07** [comment] 2021-07-19 13:57
1) 3.3.4 beta 1? I can't find an announcement of such a version.
2) Vulkan issue is likely unrelated as Godot 3.x is OpenGL
3) This is 90% certain a dupe of an existing issue (and not limited to Bloom, all world environment effects apply to gizmos too)

**Comment by Calinou** [comment] 2021-07-19 15:33
Duplicate of https://github.com/godotengine/godot-proposals/issues/2138.

**Closed by Calinou** 2021-07-19 15:33 UTC

**Comment by nonunknown** [comment] 2021-07-19 16:00
@Zireael07 

1 - SOrry mistake of mine its `3.4 beta-1`
2 - This is 3.x so its not vulkan, its OpenGL 3
