### ISSUE TITLE
Crash/force close when pressing return while running in editor

### ISSUE THREAD

**Issue by AhmadZairin** [godotengine/godot#70335] opened 2022-12-20 06:21 UTC
### Godot version

v4.0.beta9.official [e780dc332]

### System information

Android 10

### Issue description

[The bug is in this video, please watch it until it's finished, it's only less than 2 minutes](https://drive.google.com/file/d/1Zee5opFis9oueLaKzgTDoc1pjMXmINT8/view?usp=drivesdk) 

### Steps to reproduce

Detail my system
![Info my system 1](https://user-images.githubusercontent.com/83836349/208597392-279ab22f-619f-4d3d-a500-0c64c928adf3.jpg)
![info my system 2](https://user-images.githubusercontent.com/83836349/208597406-a6527384-4a33-4050-8b98-d8681418a770.jpg)
![info my system 3](https://user-images.githubusercontent.com/83836349/208597410-30318a96-3a6d-4bac-85dd-7266b49e5109.jpg)

### Minimal reproduction project

ㅤ

**Comment by AhmadZairin** [comment] 2022-12-20 15:44
Very sad, I'm like a peanut that still has a shell, and no one wants to eat with unpeeled peanuts, Like you who don't care at all about the current problem (don't fix known bugs) please... this should be fixable . It's like you can eat peanuts painlessly by peeling them, and by the way I have no hope in version (3.5.1stable) because of the problem with the mouse not working with right click, that's why I switched to godot4, so I hope godot4 will be more in the future friendly for mobile users and i am very mobile dependent , how sad i am

**Comment by m4gr3d** [comment] 2023-01-22 06:20
Duplicate of https://github.com/godotengine/godot/issues/61611

**Closed by m4gr3d** 2023-01-22 06:20 UTC
Labels: bug, platform:android, topic:editor, crash
