### ISSUE TITLE
Gridmap not rendering on Android with GLES2

### ISSUE THREAD

**Issue by crazychenz** [godotengine/godot#23616] opened 2018-11-09 17:40 UTC
**Godot version:** 3.1 alpha 2

**OS/device including version:** Android 7.0 / Moto G5 Plus / GPU: Adreno 506 w/ GLES2

**Issue description:** When using a standalone Static Mesh and a Gridmap on a very simple project, everything renders fine on the Windows 10 machine. When the exact same project is built for Android, only the Static Mesh is shown. Its as if the Gridmap's meshes or the gridmap are not rendering at all.

**Steps to reproduce:** 
1. Create MeshLibrary.
2. Create Spatial scene with GridMap.
3. Export and run for Android in GLES2 mode.
4. No gridmap shown on Android device.

**Minimal reproduction project:**
[sanitycheck.zip](https://github.com/godotengine/godot/files/2566909/sanitycheck.zip)

**Comment by Zireael07** [comment] 2018-11-09 17:50
Do you run GLES2 or GLES3 on Windows 10?

**Comment by crazychenz** [comment] 2018-11-10 07:13
GLES2

**Comment by TIBI4** [comment] 2019-01-27 20:46
I want to change something about my last comment, because when my game started to crash I started searching the source of the error, and while kept trying to solve the problem, I found that is not something about Mesh Libraries, but their SpatialMaterial>Albedo>Texture. So:

- Game blinks on splash screen **when there is a GridMap with _SpatialMaterial>Albedo>Texture_** or when I use **models with _SpatialMaterials>Albedo>Texture_**.
- When the GridMap is using **plain colors** **(_Material>Albedo>Texture [empty]_)** or when I use **models** **without their respective _Material>Albedo>Texture_** ([empty]), Godot **does not crash** in Android.

**Please take a moment to see these images.**
Windows export: It can be used with SpatialMaterial>Albedo>Texture attached, so I used Materials>Albedo>Texture different to [empty]. ([Image](https://i.imgur.com/DdPPahk.png))
Android export: It can't be used with SpatialMaterial>Albedo>Texture attached, so I did not use them. ([Image](https://i.imgur.com/3fB0FW3.png))
That's it.

If it was not understood, please just ask me for a video or a gif, I will reply as soon as possible.

> Game blinks on splash screen when there is a **_GridMap_** with a _**Mesh Library**_ set, and then crashes.
> If _**GridMap's Mesh Library**_ is _**[empty]**_ it does not happen.
> 
> Android export with **GLES2** and **Godot 3.1 beta 2**.

**Comment by akien-mga** [comment] 2019-01-27 21:06
Make sure that you are importing the textures in ETC format:
- Enable `rendering/vram_compression/import_etc`
- Delete your `res://.import` folder to force a reimport

**Comment by TIBI4** [comment] 2019-01-27 23:01
I just updated Godot to beta 3, and done what you said, but it is not working.

**Comment by TIBI4** [comment] 2019-01-27 23:49
I found this: https://github.com/godotengine/godot/issues/25365

And there, you said that we need to disable ETC2. I did it, and worked!. Thanks!.

**Comment by akien-mga** [comment] 2019-02-23 14:06
Closing as duplicate of #23650 then. Please comment if you can still reproduce it after following these steps: https://github.com/godotengine/godot/issues/23616#issuecomment-457954263

**Closed by akien-mga** 2019-02-23 14:06 UTC
Labels: bug, topic:rendering
