### ISSUE TITLE
Editor lag when cursor hovering over Sprite or while moving a Sprite in 2D

### ISSUE THREAD

**Issue by neonsoup** [godotengine/godot#21251] opened 2018-08-20 23:15 UTC
**Godot version:**
5dc2b12efa161ca48d893fc930ff5501ba51e809

**OS/device including version:**
Windows 10 x64

GPU: Nvidia gtx 1080
DRIVER: GeForce 398.11

**Issue description:**
Editor lags (freezes for half of a second) when the mouse cursor is hovering over Sprite that is displaying a large texture (for example, mine was 750x733), or even a small part of large texture file. This is mostly noticeable when i pan the scene around with middle mouse button while the cursor is above the sprite, or if i move the sprite itself with left mouse button.

This does not happen if mouse cursor is not positioned over the sprite.
This does not happen in official GODOT v3.0.6 release.
This does not happen with small textures (for example, 40x40 pixels).

**Steps to reproduce:**
-Create a new scene
-Add Node2D as its root
-Add a Sprite as a child of root node
-Attach a large texture (mine was 750x733) to the sprite
-Drag the sprite around or pan the scene, both so that the mouse cursor is positioned over the sprite

**Minimal reproduction project:**

[Sprite_hover_lag_Example_project.zip](https://github.com/godotengine/godot/files/2304194/Sprite_hover_lag_Example_project.zip)

**Comment by somnivore** [comment] 2018-08-21 02:55
https://github.com/godotengine/godot/issues/21059

**Comment by akien-mga** [comment] 2018-08-21 06:02
Thanks for the report! Closing as duplicate of #21059.

**Closed by akien-mga** 2018-08-21 06:02 UTC
