### ISSUE TITLE
Problem with Vector2.move_toward

### ISSUE THREAD

**Issue by Torguen** [godotengine/godot#50022] opened 2021-06-30 10:18 UTC
### Godot version

3.3.2 stable official

### System information

w10 64

### Issue description

move_toward seems to work fine and the scale reaches its 1.4 value correctly, however the if is never true.
The value print shows "1.4" so apparently there are no decimals, however someone advises me to use "is_equal_approx" but then if it is for that approximation reason, shouldn't the decimals be shown in the text?

![Captura](https://user-images.githubusercontent.com/19652075/123944295-48d5dc00-d99d-11eb-83c3-48a285ffea14.PNG)

### Steps to reproduce

run the project

### Minimal reproduction project

[testToward.zip](https://github.com/godotengine/godot/files/6740047/testToward.zip)

**Comment by Zireael07** [comment] 2021-06-30 11:41
Don't trust the value print. It sometimes does a little rounding (at least in 3.3.2)

In general, with floats is_equal_approx should ALWAYS be used.

**Comment by Torguen** [comment] 2021-06-30 12:13
move towards should use is_equals internally

**Comment by kleonc** [comment] 2021-06-30 13:22
> move towards should use is_equal internally

`Vector2.move_toward` is implemented properly:
https://github.com/godotengine/godot/blob/7610409b8a14b8499763efa76578795c755a846d/core/math/vector2.cpp#L180-L185

---

The problem here seems to be that floating-point number literal (like `1.4`) in GDScript is being a `double`:
https://github.com/godotengine/godot/blob/7610409b8a14b8499763efa76578795c755a846d/modules/gdscript/gdscript_tokenizer.cpp#L957-L959
Meanwhile `Vector2.x`, `Vector2.y` are of type `real_t`:
https://github.com/godotengine/godot/blob/7610409b8a14b8499763efa76578795c755a846d/core/math/vector2.h#L46-L53
which can be either `float` or `double`:
https://github.com/godotengine/godot/blob/7610409b8a14b8499763efa76578795c755a846d/core/math/math_defs.h#L104-L113

and they seem to be `float` indeed. Surprisingly, Godot's `float` seems to be `double` no matter what (otherwise it would be as precise as `Vector2.x` in the snippet below):
```
var f: float = 1.4
var v: Vector2 = Vector2(1.4, 1.4)
print("%.20f" % [ 1.4 ]) # 1.39999999999999990000
print("%.20f" % [ f ]) # 1.39999999999999990000
print("%.20f" % [ v.x ]) # 1.39999997615814210000
```
So the real problem is that `Vector2` claims (e.g. [in the docs](https://docs.godotengine.org/en/3.3/classes/class_vector2.html#properties)) that its `x`, `y` properties are of type [Godot `float`](https://docs.godotengine.org/en/3.3/classes/class_float.html#class-float) but it's not neccesarily true. Just by looking at the docs it's perfectly valid to assume that such `assert` should hold:
```
var f: float = 1.4
assert(Vector2(f, f).x == f)
```
so it clearly needs to be fixed somehow.

**Comment by clayjohn** [comment] 2021-06-30 16:15
This is not a problem with move_toward but a problem with floating point comparison in general. As kleonc shows above, the problem lies in the fact that Vector2 always uses single precision floating point while GDScript uses double precision.

While this is annoying, it isn't a bug. The solution is to use ``is_equal_approx`` when comparing floating point (or double) values. You should almost never use ``==`` on two floating point values. Even comparing two floats of the same precision is a problem, for example:
 ```
float a = 0.15 + 0.15
float b = 0.1 + 0.2
if(a == b) // can be false!
if(a >= b) // can also be false!
```
(Example taken from [the floating point guide](https://floating-point-gui.de/errors/comparison/))

**Comment by kleonc** [comment] 2021-06-30 18:31
@clayjohn Floating point precision is not the problem here. The real issue is the mismatch between "declared" and "used" types. Looking at the `master` branch I bet the same issue is present in `Vector2i` (which is exposed to GDScript in there):
- in GDScript `int` is being said to be a signed 64-bit integer,
- in GDScript `Vec2i.x`, `Vec2i.y` are claimed to be `int`,
- [in C++ `Vec2i.x`, `Vec2i.y` are `int32_t`](https://github.com/godotengine/godot/blob/a02620f3a5f3b94c68dfbe18874b34ac1c32374a/core/math/vector2.h#L287-L294).

So this probably fails on `master` too (didn't test it):
```
var i: int = 1 << 32
assert(Vector2i(i, i).x == i)
```
and concluding that "_it's a problem with integer comparison in general_" would be obviously wrong.

**Comment by aaronfranke** [comment] 2021-07-01 23:50
> however someone advises me to use "is_equal_approx" 

Yes, you should usually use this when comparing floats.

> but then if it is for that approximation reason, shouldn't the decimals be shown in the text?

Not by default, but try this (you may need to increase the "16" for small numbers):

```gdscript
print("%.16f" % your_value_here)
```

> The problem here seems to be that floating-point number literal (like `1.4`) in GDScript is being a `double`:
> Meanwhile `Vector2.x`, `Vector2.y` are of type `real_t`:
> which can be either `float` or `double`:
> and they seem to be `float` indeed.
> The real issue is the mismatch between "declared" and "used" types. 

Yes, and changing / fixing this is a well-known feature request: https://github.com/godotengine/godot-proposals/issues/892

Closing because this is not a bug, it's working as intended. For vectors using doubles, see proposal 892. For float comparison, use the `is_equal_approx` helper method instead of `==` in most situations.

**Closed by aaronfranke** 2021-07-01 23:50 UTC
Labels: discussion, topic:core
