### ISSUE TITLE
Semi-Transparent Anti-aliased Line2Ds have artifacting

### ISSUE THREAD

**Issue by EIREXE** [godotengine/godot#34617] opened 2019-12-26 14:33 UTC
**Godot version:**
master, 318c69351624f7794c51b5385d252af397c0404a
**OS/device including version:**
Arch Linux, X11

Line2Ds have some artifacting when you use anti-aliasing with them combined with semi-transparent colors:

![imagen](https://user-images.githubusercontent.com/3101690/71479531-1326c480-27f5-11ea-95e2-651224a1eb9f.png)

**Comment by akien-mga** [comment] 2020-01-03 13:11
Likely related to #34568, might be fixed by #34726 (cc @pouleyKetchoupp).

**Comment by EIREXE** [comment] 2020-01-03 14:59
Still there on master 
![imagen](https://user-images.githubusercontent.com/3101690/71730253-f5cfa700-2e41-11ea-8e14-9ebfc8975a3b.png)

**Comment by pouleyKetchoupp** [comment] 2020-01-03 15:06
AA for Line2D with transparency is not well supported for now, you need to turn AA off in this case. The AA system will be replaced in 4.0.

**Comment by EIREXE** [comment] 2020-01-03 15:34
aww, well, i'll live without AA until then

**Comment by Calinou** [comment] 2020-05-19 19:37
Duplicate of #35878.

**Closed by Calinou** 2020-05-19 19:37 UTC
Labels: bug, topic:rendering
