### ISSUE TITLE
Can't cast shadows on other objects when camera is child of viewport

### ISSUE THREAD

**Issue by SereneMango** [godotengine/godot#54498] opened 2021-11-02 01:53 UTC
### Godot version

3.3.4 (stable)

### System information

Windows 10, GTX 950 (driver ver. 496.49), GLES3

### Issue description

![image](https://user-images.githubusercontent.com/38365757/139772534-6718fe1a-0bba-4bb9-a233-27b7baca8e64.png)

It happens with the 3 types of light nodes (Directional, Omni, Spot).

Camera is child of a Viewport node, which is a child of a ViewportContainer node. The shadows are visible when the camera is anywhere else.

At first I thought it was part of a custom shader, but then it was tested without assigning any material (pictured above), and it's the same result.

### Steps to reproduce

Just a scene with two mesh instances, a light (any kind), a WorldEnvironment, and a ViewportContainer, with a Viewport as a child, and a Camera as Viewport's child. One of the two MeshInstance should be between the other one, and the light, which is pointing to the two meshes. Their materials and the WorldEnvironment can be left with their default settings.

**Comment by floppyhammer** [comment] 2021-11-02 07:15
You need to add a new Environment to the Viewport, then enable `shadow` for the Environment.

**Comment by floppyhammer** [comment] 2021-11-02 07:21
Duplicate of https://github.com/godotengine/godot/issues/23732.

**Closed** 2021-11-02 10:37 UTC
