### ISSUE TITLE
CSGSphere generating wrong geometry

### ISSUE THREAD

**Issue by theraot** [godotengine/godot#50959] opened 2021-07-28 00:03 UTC
### Godot version

3.4.beta1, 3.4.beta2

### System information

Windows 10

### Issue description

CSG sometimes generate triangles that should not be there (Either when subtracting geometry form a sphere, or when using a sphere to subtract geometry):

![image](https://user-images.githubusercontent.com/1212509/127241232-4340eef9-2d21-4522-ba9e-938f3a66944c.png)

The CSGSphere seems to be missing top and bottom caps:

![image](https://user-images.githubusercontent.com/1212509/127242194-20980ce8-f81b-4fb6-98f5-42e786cd5b7d.png)

And adding some other geometry to subtract from it causes problems:

![image](https://user-images.githubusercontent.com/1212509/127242504-e33eb164-09b3-4e34-962c-9b978cb0430e.png)

These are not editor only issue. It looks the same when running the game. Also, none of this happen in Godot 3.3.2.

### Steps to reproduce

For the sphere missing caps, just add a CSGSphere.

For the other cases, you need a CSGCombiner node.

For the subtraction from the sphere case, create a CSGCombiner node, with two children: a large CSGSphere, and a CSGBox (or some other CSG node) set to subtraction intercepting its surface.

For the other case, create a CSGCombiner node, with two children: a large CSGCylinder (or some other CSG node), and a CSGSphere set to subtraction placed off center. Not all sizes and position of the sphere will cause the problem.

### Minimal reproduction project

[CSGTest.zip](https://github.com/godotengine/godot/files/6889279/CSGTest.zip)

Note: the reproduction project is the sphere subtracting from a cylinder (the first screen shot above).

**Comment by timothyqiu** [comment] 2021-07-28 06:22
This can be reproduced on `master` too, but not in the current stable 3.3.2.

**Comment by mrjustaguy** [comment] 2021-07-28 06:55
Duplicate of https://github.com/godotengine/godot/issues/47339 if i'm not mistaken.

**Comment by timothyqiu** [comment] 2021-07-28 08:07
Closing as duplicate of #47339.

The issue has just been fixed on `master`, and will be fixed on `3.x` once cherry-picked.

**Closed by timothyqiu** 2021-07-28 08:07 UTC
Labels: bug, topic:3d, topic:core
