### ISSUE TITLE
Vulkan: Baking VoxelGI causes Editor Hang if no meshes have global illumination set to either Baked or Dynamic

### ISSUE THREAD

**Issue by sairam4123** [godotengine/godot#53348] opened 2021-10-03 06:39 UTC
### Godot version

4.0.dev [`ab063ade7`](https://github.com/godotengine/godot/pull/53338)

### System information

Windows 10, Nvidia GeForce GTX 1050, 27.21.14.5771

### Issue description

Baking VoxelGI causes Editor Hang, I'm trying to bake VoxelGI and clicking Bake GI Probe causes Editor hang and I can't find any workarounds for this.

### Steps to reproduce

1. Add VoxelGI
2. Set Extents
3. Click Bake GI Probe.
4. Observe the Editor hang.

**Comment by INdIEDeV016** [comment] 2021-10-03 07:06
In my case the editor after I hit `Bake`, the editor sits for a moment (hangs), then it again starts working. But it seems that it didn't bake anything and also pushes a error spam...
![image](https://user-images.githubusercontent.com/80198819/135743824-f26bdb06-aaf4-47cf-b6b9-47b96b3ceac3.png)

**Comment by Calinou** [comment] 2021-11-28 17:26
@sairam4123 @INdIEDeV016 Can you upload a minimal reproduction project? I can't reproduce this issue on 4.0.dev.custom_build [52b7d5fa3] (Linux, GeForce GTX 1080).

**Comment by sairam4123** [comment] 2021-11-28 17:28
I can try it again, do you have a prebuilt version for Windows?

**Comment by Calinou** [comment] 2021-11-28 17:36
> I can try it again, do you have a prebuilt version for Windows?

https://hugo.pro/projects/godot-builds/ as always :slightly_smiling_face:

**Comment by sairam4123** [comment] 2021-11-28 17:41
I can't seem to download the builds for some reason, the download speed seems slow.

**Comment by INdIEDeV016** [comment] 2021-12-02 04:34
@Calinou Alright, it works in `v4.0.dev.custom_build [2681d93b8]` But when I changed the `gi_mode` property of some `MeshInstance` Nodes and after clicking bake in `VoxelGI`, the editor suffered lags. The FPS fell below 5.

**Comment by INdIEDeV016** [comment] 2021-12-02 04:39
Btw, I am unable to open the console window in Windows builds of Godot 4.0, is it a known issue?

**Comment by Calinou** [comment] 2021-12-02 15:18
Closing as resolved. Please comment if you can still reproduce this issue on a recent build of the `master` branch.

**Comment by sairam4123** [comment] 2021-12-02 16:45
I can confirm this issue on build `702ffc624`, the editor hangs and spits out this error.
![image](https://user-images.githubusercontent.com/61322406/144465520-8e5c87c7-a371-4c02-b706-d5e8e90c1338.png)

**Comment by INdIEDeV016** [comment] 2021-12-02 16:47
It looks like a Windows 11 specific error

**Comment by INdIEDeV016** [comment] 2021-12-02 16:53
Minimal reproduction: (Even though there is no error in my project):

1) Start a fresh project
2) Click `3D scene` button
3) Add 2 `MeshInstance3D` Nodes
4) Configure one mesh as a Cylinder other a Plane
5) Change the `gi_mode` of Cylinder Mesh Instance to `dynamic` and other (the plane) as `baked`
6) Add `VoxelGI` Node and click `Bake GI`

**Comment by sairam4123** [comment] 2021-12-02 16:57
> Minimal reproduction: (Even though there is no error in my project):
> 
> 1. Start a fresh project
> 2. Click `3D scene` button
> 3. Add 2 `MeshInstance3D` Nodes
> 4. Configure one mesh as a Cylinder other a Plane
> 5. Change the `gi_mode` of Cylinder Mesh Instance to `dynamic` and other (the Plane) as `baked`
> 6. Add `VoxelGI` Node and click `Bake GI`

This works.

**Comment by INdIEDeV016** [comment] 2021-12-02 17:01
> This works.

So, no need to reopen this issue, right?

**Comment by sairam4123** [comment] 2021-12-02 17:14
> > This works.
> 
> So, no need to reopen this issue, right?

It shouldn't crash if I didn't set the global illumation to baked or dynamic right?

**Comment by INdIEDeV016** [comment] 2021-12-02 17:16
> > > This works.
> > 
> > 
> > So, no need to reopen this issue, right?
> 
> It shouldn't crash if I didn't set the global illumation to baked or dynamic right?

Didn't test that aspect

**Comment by INdIEDeV016** [comment] 2021-12-03 03:41
Well, it seems VoxelGI won't work if we don't set any `gi_mode` for the Mesh Instance.

![image](https://user-images.githubusercontent.com/80198819/144541406-24ba63f1-c27f-4b1f-a1c0-d53329074fc6.png)

**Comment by INdIEDeV016** [comment] 2021-12-03 04:12
Oh yeah, but now if I change the `gi_mode` to Dynamic from Disabled for the Cylinder, then the editor starts performing very badly. It starts using 100% of my GPU in the Task Manager

**Comment by Calinou** [comment] 2021-12-03 10:56
> Oh yeah, but now if I change the gi_mode to Disabled to Dynamic for the Cylinder, then the editor starts performing very badly. It starts using 100% of my GPU in the Task Manager

This is a known issue, see https://github.com/godotengine/godot/issues/55359.

**Comment by INdIEDeV016** [comment] 2021-12-03 11:48
And turning up the `subdiv` for `VoxelGI` makes your Godot go mad! 😵

**Comment by INdIEDeV016** [comment] 2021-12-03 11:58
Found some errors. I don't know if it's related.....
![image](https://user-images.githubusercontent.com/80198819/144598868-12bb34c4-72fa-4324-9c1f-9c3e496d7299.png)

**Comment by Calinou** [comment] 2021-12-03 14:18
> Found some errors. I don't know if it's related..... ![image](https://user-images.githubusercontent.com/80198819/144598868-12bb34c4-72fa-4324-9c1f-9c3e496d7299.png)

The layer manifest files message is unrelated – it's being tracked in https://github.com/godotengine/godot/issues/45725.

**Comment by Calinou** [comment] 2021-12-08 18:08
Duplicate of https://github.com/godotengine/godot/issues/36121 (same cause).

**Closed by Calinou** 2021-12-08 18:08 UTC
Labels: bug, topic:rendering, topic:3d
