### ISSUE TITLE
Is this normal?

### ISSUE THREAD

**Issue by niu2x** [godotengine/godot#2664] opened 2015-10-23 14:32 UTC
VBoxContainer: 136,100
ERROR: get_edited_scene_root: Index current_edited_scene out of size (edited_scene.size()).
   At: tools/editor/editor_data.cpp:500.

**Comment by firefly2442** [comment] 2015-10-23 18:09
Duplicate issue reported here #2654

**Comment by vnen** [comment] 2015-10-29 16:29
Closing as duplicate of #2654.

**Closed by vnen** 2015-10-29 16:29 UTC
Labels: archived
