### ISSUE TITLE
.blend file import from Blender 4.2 files not working.

### ISSUE THREAD

**Issue by ap-gabriel** [godotengine/godot#94478] opened 2024-07-17 17:41 UTC
### Tested versions

Reproducible in Godot 4.2.2 Stable

### System information

Windows 10 - Godot 4.2.2 Stable

### Issue description

Trying to import .blend files from Blender newest stable release (4.2), doesn't work.

### Steps to reproduce

1 - Create a fresh project in godot.
2 - Open Blender 4.2, create a any project and save to godot project directory, or get any .blend file from Blender 4.2.

### Minimal reproduction project (MRP)

[New Game Project.zip](https://github.com/user-attachments/files/16272277/New.Game.Project.zip)

**Comment by MrBlockers** [comment] 2024-07-17 18:32
I think this is a duplicate of https://github.com/godotengine/godot/issues/92365

**Comment by AThousandShips** [comment] 2024-07-17 18:45
Indeed, has already been fixed and fix will be cherry picked for 4.2

**Closed by AThousandShips** 2024-07-17 18:45 UTC
