### ISSUE TITLE
Error on 2d collision

### ISSUE THREAD

**Issue by alperencaliskan** [godotengine/godot#12468] opened 2017-10-28 20:01 UTC
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Linux Mint 18.2 Sonya, Godot master https://github.com/godotengine/godot/commit/feb30bf329d5de8a6b35acaae0cd122f53e40826 , Intel hd4400 GPU

**Issue description:**
Created two 2d kinematic body and one 2d rigid body. After rigid body falls down on moving kinematic body then two kinematic body collide, "Indexp_idx=1 out of size (shapes.size()=1)" error occurs repeatedly.

![image](https://user-images.githubusercontent.com/9333745/32137947-9cd30b98-bc32-11e7-8a85-c0a1e1d5b1fc.png)

Terminal error:

> ERROR: is_shape_set_as_one_way_collision: Indexp_idx=1 out of size (shapes.size()=1)
   At: servers/physics_2d/collision_object_2d_sw.h:152.

**Steps to reproduce:**
Example project attached. Just run it. If you move rigid body even by a little, this error doesn't occur. No idea how did i do this. Using c#/mono script.

**Link to minimal example project:**
[cbgame.zip](https://github.com/godotengine/godot/files/1424566/cbgame.zip)

**Comment by akien-mga** [comment] 2018-01-05 15:41
Can this still be reproduced in the current master branch?

**Comment by akien-mga** [comment] 2018-01-06 22:52
Just tried, I can't reproduce the issue with the provided example, so I assume that it got fixed in the meantime. Please comment if you can still reproduce it so that the issue can be reopened.

**Closed by akien-mga** 2018-01-06 22:52 UTC
Labels: bug, topic:physics
