### ISSUE TITLE
GDScript: Built in methods that match the name of a core function will be highlighted incorrectly with the wrong colour

### ISSUE THREAD

**Issue by Giacom** [godotengine/godot#29434] opened 2019-06-03 14:43 UTC
**Godot version:**
b9dc2e7e4dd38621ef0dd07d208ffc5468954adb

**Issue description:**
If there is a built in method with the same name as a core function, it will be highlighted incorrectly with the wrong colour.

For example, 'move_toward()' and 'Vector3.move_toward()'

![Capture](https://user-images.githubusercontent.com/1524810/58810402-be7fea00-8615-11e9-9554-61c9b5cfbc1f.PNG)

The 'move_toward' Vector2 method is incorrectly coloured, it should instead be blue like the distance_to() method.

**Minimal reproduction project:**
[movetowards.zip](https://github.com/godotengine/godot/files/3248084/movetowards.zip)

**Comment by KoBeWi** [comment] 2019-06-03 16:39
Duplicate of #28866

**Closed by KoBeWi** 2019-06-03 16:39 UTC
