### ISSUE TITLE
VisibilityNotifier is Broken

### ISSUE THREAD

**Issue by OriginalAGP** [godotengine/godot#29769] opened 2019-06-14 05:09 UTC
```
print("Is starfighter's notifier null? ", (starfighterNotifier==null))

func _process(deltaTime):
	if (Input.is_action_pressed("Right")):
		rotate_y(-deltaTime)
	if (Input.is_action_pressed("Left")):
		rotate_y(deltaTime)
	if (Input.is_action_just_pressed("ui_accept")):
		look_at(bigShip.transform.origin, Vector3(0, 1, 0))
	if (starfighterNotifier.is_on_screen()):
		selectedShip = starfighter
```

**Godot version:**
3.1.1 Stable

**OS/device including version:**
Windows 10, GPU NVidia Optimus

**Issue description:**
The above printout tells me the visibility notifier variable is NOT null. But in _process, I repeatedly get the message, "Attempt to call function 'is_on_screen' in base 'null instance' on a null instance."

**Comment by slapin** [comment] 2019-06-14 05:16
please use triple backticks to quote code, otherwise it is unreadable.
Also you quote not enough information to point you in right direction.
How do you define variable starfighterNotifier is defined and initialized?
Please provide more information.

**Comment by OriginalAGP** [comment] 2019-06-14 15:50
`starfighterNotifier = starfighter.get_node("./StarfighterNotifier")`

StarfighterNotifier was created in the GUI as a child of starfighter. Its variable is filled in the above code; it's not null, as the print statement states. And I'm using the "insert code" button to quote code.

**Comment by TheDuriel** [comment] 2019-06-14 18:04
A null instance is not equal to null. Use is_instance_valid() for your comparison.

99% chance your get_node nodepath is wrong.

**Comment by OriginalAGP** [comment] 2019-06-14 21:53
Is_instance_valid(starfighterNotifier) returns true.

**Comment by groud** [comment] 2019-06-15 10:18
Please provide an example project. You likely made a mistake in you script.

**Comment by OriginalAGP** [comment] 2019-06-19 19:05
Must I really upload the whole thing? I accept the premise that I made a mistake, but the project is big. This is the entire script:

`extends Camera

var aWing : Spatial
var xWing : Spatial
var xWing_T70 : Spatial
var yWing : Spatial
var snowspeeder : Spatial
var starfighter : Spatial
var falcon : Spatial
var selectedShip : Spatial
var ray : RayCast
var xWingNotifier : VisibilityNotifier
var starfighterNotifier : VisibilityNotifier
# Called when the node enters the scene tree for the first time.
func _ready():
	aWing = get_parent().get_node("HangarShips/Ships/A-Wing")
	xWing = get_parent().get_node("HangarShips/Ships/X-Wing")
	xWing_T70 = get_parent().get_node("HangarShips/Ships/X-Wing_T70")
	yWing = get_parent().get_node("HangarShips/Ships/YWing")
	while (yWing == null):
		yWing = get_parent().get_node("HangarShips/Ships/YWing")
	snowspeeder = get_parent().get_node("Hangar/Ships/Snowspeeder")
	starfighter = get_parent().get_node("Hangar/Ships/Starfighter")
	falcon = get_parent().get_node("Hangar/Ships/MillenniumFalcon")
	while (starfighter == null):
		starfighter = get_parent().get_node("HangarShips/Ships/Starfighter")
	while (falcon == null):
		falcon = get_parent().get_node("HangarShips/Ships/MillenniumFalcon")
	ray = get_node("RayCast")
	xWingNotifier = xWing.get_node("./X-WingNotifier")
	starfighterNotifier = starfighter.get_node("./StarfighterNotifier")
	print("Is xWing's Notifier null? ", (xWingNotifier==null), " Is starfighter's notifier valid? ", (is_instance_valid(starfighterNotifier)))

# Called every frame. 'delta' is the elapsed time since the previous frame.
func _process(deltaTime):
	if (Input.is_action_pressed("Right")):
		rotate_y(-deltaTime)
	if (Input.is_action_pressed("Left")):
		rotate_y(deltaTime)
	if (Input.is_action_just_pressed("ui_accept")):
		#var xWing = get_parent().get_node("HangarShips/Ships/X-Wing")
		look_at(xWing.transform.origin, Vector3(0, 1, 0))
	#var result = get_world().direct_space_state.intersect_ray(global_transform.origin, self.global_transform.origin, [self])
	#print("Result: ", result)
#	if (ray.is_enabled() and ray.is_colliding()):
#		selectedShip = ray.get_collider()
#		print("Selected ship: ", selectedShip.get_name())
	#starfighter.get
	if (starfighterNotifier.is_on_screen()):
		selectedShip = starfighter
	elif (xWingNotifier.is_on_screen()):
		selectedShip = xWing
	elif (get_parent().get_node("HangarShips/Ships/Snowspeeder/SnowspeederNotifier").is_on_screen()):
		selectedShip = snowspeeder
	elif (get_parent().get_node("HangarShips/Ships/A-Wing/A-WingNotifier").is_on_screen()):
		selectedShip = aWing
	elif (yWing.get_node("Y-WingNotifier").is_on_screen()):
		selectedShip = yWing
	elif (xWing_T70.get_node("./T70Notifier").is_on_screen()):
		selectedShip = xWing_T70
	elif (falcon.get_node("./MillenniumFalcon/FalconNotifier").is_on_screen()):
		selectedShip = falcon
	if (selectedShip != null):
		print("Selected ship: ", selectedShip.get_name())`

And this is what the project looks like:
[https://www.dropbox.com/s/7iwvuazz1aqycjg/RS_Screen.png?dl=0](url)

**Comment by Toshiwoz** [comment] 2019-09-03 22:23
A minimum reproduction project would be very useful. Otherwise it would be just guessing what it might be.

Anyhow, I don't think it's a visilibitynotifier problem:
Being notified that is null means that it was not initialized or somehow the node is freed.
Check if the _process function is called before the _ready, if so then the problem is there.

Tip: you may want to consider moving some of the nodes into separate scenes.

**Comment by groud** [comment] 2019-09-04 08:06
Sorry, but without a **minimal** reproduction project we cannot solve this problem. I will close this issue, but I will be happy to reopen it if you identify the exact problem in the engine or provide such minimal reproduction project.

**Closed by groud** 2019-09-04 08:06 UTC
Labels: bug, needs testing, topic:core

**Comment by groud** [comment] 2019-09-04 15:59
@Toshiwoz Oh sorry, the bold word was not for you. It was only here to insist on the fact such reproduction project have to be simple ^^
