### ISSUE TITLE
[3.2.3] godot freezes when clicking root bone in imported FBX

### ISSUE THREAD

**Issue by dark-stalker** [godotengine/godot#43939] opened 2020-11-28 17:30 UTC
**Godot version:**
3.2.3 stable

**OS**
windows 10

**Issue description:**
I imported fbx file that exported from blender.
Selected new inherited and then if i click the root bone it freezes.

Here is the console when it happens.
![Ekran Görüntüsü (15)](https://user-images.githubusercontent.com/64694971/100521465-343e2500-31bd-11eb-80b5-fe2f6147abab.png)

**Steps to reproduce:**
open minimal project
click new inherited
click root bone

**Minimal reproduction project:**
[Project Test.zip](https://github.com/godotengine/godot/files/5610963/Project.Test.zip)

**Comment by Calinou** [comment] 2020-11-28 19:04
Duplicate of #35653

(the underlying issue is the same).

As a workaround, try increasing the message queue size to 4096 in the Project Settings.

**Closed by Calinou** 2020-11-28 19:04 UTC
Labels: bug

**Comment by dark-stalker** [comment] 2020-11-28 19:30
It worked. Thanks
