### ISSUE TITLE
Window Node Top bar doesn't reappear when Mode changed back to "Windowed" from "FullScreen"

### ISSUE THREAD

**Issue by omarbassam88** [godotengine/godot#40221] opened 2020-07-08 22:31 UTC
**Godot version:**

18c51d3f0c4ddf0bdf347638ca2d781a42de16d2

**OS/device including version:**

Linux POP OS 20.04 LTS Godot 4.0 with the Vulkan setup.

**Issue description:**

The New  Window Node, when you change the mode from "Windowed" to "Fullscreen" it works fine. However, if you change it back to "Windowed", the top bar doesn't come back.

**Steps to reproduce:**
1. Add Window Node
2. Change the Mode from "Windowed" to "FullScreen".
3. Change it back again to "Windowed".

**Minimal reproduction project:**

**Comment by Rubonnek** [comment] 2020-07-10 16:18
Are you using `x11` or `wayland`?

**Comment by omarbassam88** [comment] 2020-07-13 00:51
> Are you using `x11` or `wayland`?

I am on POP OS that uses X11.

**Comment by Rubonnek** [comment] 2020-07-13 00:57
This seems to be a duplicate of #40037 -- could you try the borderless test there and see if the top back doesn't come back? 

This is also related to #40007 as toggling fullscreen changes the borderless value.

**Comment by omarbassam88** [comment] 2020-07-15 12:14
I guess the Issues you mentioned are related to the Main window manager of the Editor and the settings in the Project settings. I was actually talking about the new "Window" Node presented in the new Godot 4. 

![image](https://user-images.githubusercontent.com/49006410/87543667-684cf980-c6a5-11ea-9b1b-01d9d71cc4a0.png)


![image](https://user-images.githubusercontent.com/49006410/87543744-84509b00-c6a5-11ea-9e8b-c0a5a1c0e25a.png)

**Comment by akien-mga** [comment] 2022-07-19 08:23
I tested if this was still reproducible in current `master` (d29e17d9d2ad1d6b6380b6de01fe283c3937955b) and it seems fixed.

Using this script:
```gdscript
extends Control

func _ready():
	$/root.gui_embed_subwindows = false
	
	var w = Window.new()
	w.title = "Hi"
	w.position = Vector2(200, 200)
	w.size = Vector2(300, 100)
	var l = Label.new()
	l.text = "I'm the subwindow"
	w.add_child(l)
	add_child(w)

	w.mode = Window.MODE_WINDOWED
	await get_tree().create_timer(2.0).timeout

	w.mode = Window.MODE_FULLSCREEN
	await get_tree().create_timer(2.0).timeout

	w.mode = Window.MODE_WINDOWED
```

Here's how it looks like on Mageia 9 KDE Plasma/KWin on X11:

https://user-images.githubusercontent.com/4701338/179703124-715d857e-916a-494a-8020-dd0c3e977302.mp4

I do reproduce a situation where the window title bar disappears while being in windowed, but that's on the main window when setting fullscreen in project settings, which doesn't work properly (that's #54065).

**Closed by akien-mga** 2022-07-19 08:23 UTC
Labels: bug, platform:linuxbsd, topic:porting, topic:gui
