### ISSUE TITLE
Exported array isn't unqiue per scene instance

### ISSUE THREAD

**Issue by Keetz** [godotengine/godot#17507] opened 2018-03-14 14:50 UTC
**Godot version:**

Godot 3.0.1 / Godot 3.0.2

**Issue description:**

I have an exported array variable in a scene that is instanced in other scenes.
The idea is that I instance the scene with the array in some other scenes, and each instance has its own unique stuff in the array.

This worked perfectly fine in Godot 2.x but since 3.0.1 (maybe earlier) it isn't.

This is only the case with array as far as I have tested.

**Steps to reproduce:**
1. Open the project included
2. Change the script variable **Array** on the instanced Test scene in the Main scene
3. Open the Test scene and notice how the original value has changed
4. Repeat 2 and 3 if needed to see what's going on

I also included a 2.1.4 project just to show that it works.

**Minimal reproduction project:**

[PerSceneTest_Godot3.tar.gz](https://github.com/godotengine/godot/files/1811617/PerSceneTest_Godot3.tar.gz)
[PerSceneTest_Godot2.tar.gz](https://github.com/godotengine/godot/files/1811618/PerSceneTest_Godot2.tar.gz)

**Comment by akien-mga** [comment] 2018-03-14 14:56
Duplicate of #16478 I think. But it would be worth mentioning there that it worked differently in 2.1.x.

**Comment by Keetz** [comment] 2018-03-14 15:05
@akien-mga it is indeed, d'oh. I commented on that issue too, so this can be closed I guess ;)

**Closed** 2018-03-14 15:50 UTC
