### ISSUE TITLE
Vulkan: When an unshaded object is facing the background sky with Glow enabled, there's a strange red outline which isn't supposed to be

### ISSUE THREAD

**Issue by AbdouMadjidi** [godotengine/godot#70719] opened 2022-12-29 21:59 UTC
### Godot version

4.0 beta 10

### System information

windows 10, vulkan, GTX 970, latest drivers

### Issue description

Look at the image
![image](https://user-images.githubusercontent.com/87293515/210014780-f68eb1b4-6a09-4c90-aa14-89d8e5fdfd52.png)

![image](https://user-images.githubusercontent.com/87293515/210014738-fcddbcd8-3242-4c7f-ac2e-b978bfcbd021.png)

### Steps to reproduce

It happens even if there's no world Environment and it also happened to me with beta 8

### Minimal reproduction project

[project.zip](https://github.com/godotengine/godot/files/10322254/project.zip)

**Comment by BastiaanOlij** [comment] 2023-02-23 10:23
Had a bit of a play with this too, it's actually not the glow, it's the DOF that is causing this. This is with DOF on only (glow and fog disabled):
![image](https://user-images.githubusercontent.com/1945449/220878778-29417506-fd55-4eb2-a6c0-06d0b7434eb9.png)

The ring is caused by the color of the globe having an extremely high red component:
![image](https://user-images.githubusercontent.com/1945449/220880166-6f353842-c93a-41c5-89ad-316e3b29928b.png)

This is overpowering the blur effect, any pixel blurred due to the far DOF which the blur radius touches this sphere will immediately mix in enough red to saturate the pixel. 

I don't think this is a bug.

**Comment by clayjohn** [comment] 2023-02-23 16:54
I agree, there is nothing actionable for us, so closing

**Closed by clayjohn** 2023-02-23 16:54 UTC
Labels: bug, topic:rendering, topic:3d
