### ISSUE TITLE
Dropdown is blank when Canvas is chosen for Environment Background Mode

### ISSUE THREAD

**Issue by ericlothspeich** [godotengine/godot#66199] opened 2022-09-21 04:29 UTC
### Godot version

v4.0.beta1.mono.official [4ba934bf3]

### System information

OSX 12.3.1, Intel UHD Graphics 630 1536 MB

### Issue description

The drop-down menu is blank when Canvas is chosen for the Environment, Background, Mode. 
<img width="1536" alt="Screen Shot 2022-09-20 at 11 23 35 PM" src="https://user-images.githubusercontent.com/64578626/191414093-707abeac-d058-4b99-bb61-88eb155f280d.png">

### Steps to reproduce

Create a new project with a new scene and make a WorldEnvironment Node. Add a new Environment and then set the Background Mode to Canvas. Click the mode option again, and when the drop-down menu appears, it's blank. You can still select other modes from the bank drop-down, and the other options are there if the Mode is not Canvas. It will become blank again when Canvas is selected.

### Minimal reproduction project

It's a brand new project, and only other things I have added to the scene are a MeshInstance3D with a cube mesh and a camera that I translated to look at the cube from a 45 degree angle.

**Comment by arkology** [comment] 2022-09-21 04:46
Duplicate of https://github.com/godotengine/godot/issues/52467

**Comment by Chaosus** [comment] 2022-09-21 07:45
Duplicate of https://github.com/godotengine/godot/issues/52467

**Closed by Chaosus** 2022-09-21 07:45 UTC
