### ISSUE TITLE
CollisionShape2D can't disabled while using AnimatonTree

### ISSUE THREAD

**Issue by dennykurniawan48** [godotengine/godot#69149] opened 2022-11-25 03:24 UTC
### Godot version

4.Beta.6

### System information

Linux Manjaro

### Issue description

In Godot 4 Beta 6 disabling CollisionShape2D is not disable Collison on runtime.
This work as expected in Godot 4 Beta 5.

Project runtime on Godot 4 Beta 5:

![godot 4b5](https://user-images.githubusercontent.com/24972902/203893343-f986137c-df94-4248-965d-4787c1a127d5.png)

Project runtime on Godot 4 Beta 6:

![godot 4b6](https://user-images.githubusercontent.com/24972902/203893409-0d0d98bf-e8fa-4dad-b96f-64e22a92480d.png)

Ps: This project try to replicate [a tutorial on youtube](https://www.youtube.com/playlist?list=PL9FzW-m48fn2SlrW0KoLT4n5egNdX-W9a).

### Steps to reproduce

1. Download Minimal reproduction project
2. Activate Debug -> Visible collision shape
3. Run the project on Godot 4 Beta 5 and Godot 4 Beta 6
4. In the Godot 4 Beta 5 collision is disabled on runtime but in Godot 4 Beta 6 it is not disabled.

### Minimal reproduction project

[Collision Godot 4.zip](https://github.com/godotengine/godot/files/10088328/Collision.Godot.4.zip)

**Comment by rburing** [comment] 2022-11-25 09:19
Could you please add a more minimal reproduction project? Preferably using GDScript instead of C#, if the issue persists there. This would be helpful for triaging. My guess is that the issue is with C#.

**Comment by dennykurniawan48** [comment] 2022-11-25 14:39
I suppose the leading cause of this issue is that while using AnimationTree the Collision inside CharacterBody2D can't be disabled in Godot 4.0 Beta 6. I've updated my Minimum Reproduction Project with no C# or GDScript.

[Updated Minimum Reproduction Project](https://github.com/godotengine/godot/files/10093521/CollisonTree.zip)

**Comment by rburing** [comment] 2022-11-25 17:37
Thanks for investigating! This is a known issue in beta 6, duplicate of https://github.com/godotengine/godot/issues/68261. This will be fixed in beta 7.

**Closed by rburing** 2022-11-25 17:37 UTC
Labels: bug, topic:animation, topic:2d
