### ISSUE TITLE
Unexpected default font size behavior in script editor

### ISSUE THREAD

**Issue by freemanfromgodotengine** [godotengine/godot#3768] opened 2016-02-19 02:55 UTC
**Operating system or device:**
Xubuntu 14.04 LTS 64-bit

**Issue description** (what happened, and what was expected):
Already opened scenes use smaller editor's font than the newly opened one.

**Steps to reproduce:**
~~Make sure not to have set your custom font in text editor's setting.~~

Start to edit the platformer or simple shooter demo.
Go to Scene menu and use Open scene to load one of the xml scenes. 
The font looks like this:
![fonts_normal](https://cloud.githubusercontent.com/assets/11817561/13165260/d74655e0-d6bb-11e5-99d0-90fc952fa64b.png)

Load and open another xml scene in the editor.
Now, when you go back to the previously loaded scene, the font is smaller:
![fonts_smaller](https://cloud.githubusercontent.com/assets/11817561/13165265/e2acee62-d6bb-11e5-81fe-79870fc5a0f5.png)

**Comment by akien-mga** [comment] 2016-02-19 06:41
> Make sure not to have set your custom font in text editor's setting.

I can't reproduce this the way you described it. Are you sure that you did not change the custom editor font between the opening of the two scenes? It kind of looks like #2159, but it would involve setting a custom font.

**Comment by freemanfromgodotengine** [comment] 2016-02-19 11:39
Yes, I am sure Godot uses it's default fonts. Editor Settings/Text Editor/Font field is cleared.
When I set custom font there, the issue is gone and the editor's fonts look the same in newly opened script as well as the previously opened one.

I can try to compile master tonight on different machine and see if I'll be able to reproduce it there.
Can my window manager be involved in this one? I use [i3](http://i3wm.org/) .

**Comment by akien-mga** [comment] 2016-02-19 11:50
I don't think the WM would be involved, it looks like the second screenshot uses on non monospaced font (maybe the same font as in the help or the other GUI elements?), so it looks like you found a corner case where the editor font is not properly set to monospaced.

I did not manage to reproduce with the steps you gave, but could you try again to give very precise steps on how you can reproduce it? Like how you run the editor, how you open let's say the simple shooter demo, which scene you open first and how, what you do then to see the script (e.g. clicking on the Script tab vs clicking the script icon of a node), etc.

**Comment by freemanfromgodotengine** [comment] 2016-02-21 01:13
OK, I could not reproduce it anymore next day. But finally I got it.
What you need to do is to actually upload a font as a editor font and not like I said before to clear the font and use whatever is Godot's default - so I crossed that remarks in my comments above.
So it should stade "Make sure to have set your custom font in text editor's setting." and the subject of the issue should be changed to "Unexpected **customized** font size behavior in script editor"
Then newly loaded scene will be shown with some "default" font, that is not the font you set in editors setting (I think). Every other scene script previously loaded will be displayed using set font.

If you still can't reproduce it, I will prepare video or something. Let me know, please.

**Comment by freemanfromgodotengine** [comment] 2016-02-22 01:14
Maybe the movie will explain it better.
https://raw.githubusercontent.com/freemanfromgodotengine/my_repository/master/video/godot_font_issue.mp4

**Comment by MarianoGnu** [comment] 2016-05-28 20:57
The video can't be reproduced

I just tryed and could not reproduce the bug. In fact, when switching or removing the default font there's no change at all until the Editor is closed and reopened...

@akien-mga this could be resolved withouth noticing? font should be changed at once when font is swapped?

**Comment by akien-mga** [comment] 2016-09-02 06:33
@freemanfromgodotengine Can you still reproduce in 2.1? With the many changes done to the fonts system and editor fonts, I guess this bug might have been fixed by chance too.

**Comment by freemanfromgodotengine** [comment] 2016-09-20 12:19
@akien-mga I think it's gone. I can't reproduce it in current master.

**Closed** 2016-09-20 12:24 UTC
Labels: bug, topic:editor, usability
