### ISSUE TITLE
3.2 Beta 1 "Export All" is broken

### ISSUE THREAD

**Issue by Wavesonics** [godotengine/godot#33469] opened 2019-11-09 01:55 UTC
**Godot version:**
3.2 Beta 1

**OS/device including version:**
Windows 10

**Issue description:**
Clicking "Export All" in the export window gives the error:
"Given export path doesn't exist: xxx"

When the path does exist. It happens for all types of export targets.

**Steps to reproduce:**

1. Create an export target
2. Project -> Export
3. Export All

**Minimal reproduction project:**

**Comment by Anutrix** [comment] 2019-11-11 15:50
I can confirm this.

**Comment by Wavesonics** [comment] 2019-11-12 00:14
I just got the engine building locally, wouldn't mind taking a look at this issue. Could someone who knows more than I point me in the right direction? What files/classes are involved in this?

**Comment by Calinou** [comment] 2019-11-12 10:33
@Wavesonics This is the file you're looking for: https://github.com/godotengine/godot/blob/7d836a7cc399fd388550d8e3af2e5b70e6e2daa7/editor/project_export.cpp#L1245

PS: Searching in the codebase for a button's text is a good way to find the file involved :slightly_smiling_face:

**Comment by akien-mga** [comment] 2019-11-12 10:49
Related to #31427, possibly fixed by #31840.

**Comment by volzhs** [comment] 2020-01-10 00:33
can't reproduce it with a0ce88f953
possibly fixed by #34348

**Closed** 2020-01-10 06:39 UTC
Labels: bug, regression, topic:editor
