### ISSUE TITLE
Running Godot 2.1.2 and playing music causes static noise

### ISSUE THREAD

**Issue by Tybobobo** [godotengine/godot#7761] opened 2017-02-08 19:02 UTC
A short disclaimer; I hope this is just an issue with my own computer. Perhaps I have messed something up - or deleted something that I shouldn't. Regardless, just in case I will report it here as a possible bug.

This sound glitch only happens when I run Godot - not when I run other Steam applications, or applications. I have attempted to uninstall and reinstall Godot on Steam, but it does not change anything.
If you have suggestions or ideas of what I could try to troubleshoot the problem, please let me know. :)

**Operating system or device - Godot version:**
Running on Linux Mint 18.1 Cinnamon 64-bit
Godot Engine v2.1.2 (Steam)

**Issue description:**

Whenever I start Godot Engine, regardless if music is already playing or not - it causes the music that is being played to become very static. The static noise levels matches the music levels being played.

When I run v2.2 alpha custom build, there is no static. Only when I use the steam version. Doing more tests.

**Steps to reproduce:**
Play music.
Start Godot 2.1.2

**Audio Clip of what I am hearing:**
https://clyp.it/klnjopjk

**Comment by bojidar-bg** [comment] 2017-02-08 19:16
@Tybobobo Hm, I'm actually having the same issue when using MuseScore, thought it usually sorts itself out if I relaunch the program. Can you try if that's the case?

**Comment by Tybobobo** [comment] 2017-02-08 19:16
I have restarted the program, reinstalled the program, I have restarted the machine, I have done a little rain dance and thrown salt all over the floor. No luck yet. Still working on a few more tests.

**Comment by hpvb** [comment] 2017-02-16 23:15
Are you able to build Godot from sources? If so could you test building the tag 2.1.2-stable with d2240404e39e50b19281dd31c0ef8b0120da11ee reverted? If not I can provide you with a build like that.

**Comment by Tybobobo** [comment] 2017-02-17 12:15
@hpvb I am already using a different build that works just fine for personal use.

**Comment by hpvb** [comment] 2017-02-17 13:29
OK @akien-mga I suggest closing this issue then and assume it's fixed somewhere in 2.1.3. I can't reproduce it and the submitter doesn't have the problem any longer.

**Comment by akien-mga** [comment] 2017-02-17 13:31
Great, thanks for testing guys :)

**Closed by akien-mga** 2017-02-17 13:31 UTC
