### ISSUE TITLE
[Godot 4] Installing nigthly build Throws error message

### ISSUE THREAD

**Issue by nonunknown** [godotengine/godot#45739] opened 2021-02-05 21:00 UTC
**Godot version:**
![image](https://user-images.githubusercontent.com/58845030/107088474-c117e700-67db-11eb-84ba-bf39f8cba7b9.png)

**OS/device including version:**
Windows 10 x64
Using Vulkan Device #0: AMD - AMD Radeon R7 200 Series

**Issue description:**
Installing the latest nightly build from calinou throws this message when finished installing:
![image](https://user-images.githubusercontent.com/58845030/107088459-b9f0d900-67db-11eb-94b2-6c224684c5b3.png)

but in the end godot launches, with the following message:

![image](https://user-images.githubusercontent.com/58845030/107088608-f8869380-67db-11eb-8ec6-1a19a4edec07.png)

**Steps to reproduce:**
Just install

**Comment by clayjohn** [comment] 2021-02-05 21:04
The first error appears to be from the installer itself and likely has nothing to do with Godot cc @Calinou

The second message is a duplicate of https://github.com/godotengine/godot/issues/45725

**Comment by Calinou** [comment] 2021-02-05 21:20
Closing per @clayjohn's comment. If you have trouble with the installer, use the ZIP archive instead.

**Closed by Calinou** 2021-02-05 21:20 UTC
