### ISSUE TITLE
Errors Compiling Android-Export-Templates Linux

### ISSUE THREAD

**Issue by yuyoDev** [godotengine/godot#11361] opened 2017-09-17 16:40 UTC
ArchLinux-64bits AMD-FX8350 Godot3.0-Master-Repository 

Error trying compile export template for Android:
[ 69%] Compiling ==> drivers/unix/file_access_unix.cpp
[ 69%] Compiling ==> drivers/unix/stream_peer_tcp_posix.cpp
[ 69%] Compiling ==> drivers/unix/ip_unix.cpp
[ 69%] Compiling ==> drivers/unix/rw_lock_posix.cpp
[ 69%] Compiling ==> drivers/unix/dir_access_unix.cpp
[ 69%] Compiling ==> drivers/unix/thread_posix.cpp
drivers/unix/dir_access_unix.cpp:209:15: error: use of undeclared identifier 'setmntent'
        FILE *mtab = setmntent("/etc/mtab", "r");
                     ^
drivers/unix/dir_access_unix.cpp:214:10: error: use of undeclared identifier 'getmntent_r'
                while (getmntent_r(mtab, &mnt, strings, sizeof(strings))) {
                       ^
drivers/unix/dir_access_unix.cpp:223:3: error: use of undeclared identifier 'endmntent'; did you mean
      'getmntent'?
                endmntent(mtab);
                ^~~~~~~~~
                getmntent
/mypath/Android/Sdk/ndk-bundle//platforms/android-18/arch-arm/usr/include/mntent.h:49:16: note: 
      'getmntent' declared here
struct mntent* getmntent(FILE*);
               ^
3 errors generated.
scons: *** [drivers/unix/dir_access_unix.android.opt.armv7.neon.o] Error 1
Ranlib Library         ==> modules/libmodules.android.opt.armv7.neon.a
scons: building terminated because of errors.

Compile with: 
scons platform=android target=release builtin_openssl=yes -j 7

**Comment by akien-mga** [comment] 2017-09-17 16:44
Duplicate of #11270.

**Closed by akien-mga** 2017-09-17 16:44 UTC
