### ISSUE TITLE
Procedural mesh has blurry edges

### ISSUE THREAD

**Issue by BenjaTK** [godotengine/godot#83591] opened 2023-10-18 23:59 UTC
### Godot version

v4.1.1.stable.official [bd6af8e0e]

### System information

Godot v4.1.1.stable - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 750 Ti (NVIDIA; 31.0.15.3623) - Intel(R) Core(TM) i3-9100F CPU @ 3.60GHz (4 Threads)

### Issue description

I'm procedurally generating a terrain mesh using ArrayMesh and SurfaceTool. However, it doesn't look like it's intended to. The edges are blurry and the lighting works really weirdly. 

![image](https://github.com/godotengine/godot/assets/73806216/9d2a1b65-5306-47be-98e1-a2aa06e4c682)

It looks way better when it's using smooth group -1, and the normals are flat. However, I'd like to have both options.

![image](https://github.com/godotengine/godot/assets/73806216/d7f7ffb5-42b6-4026-988e-33d936abbbd3)

### Steps to reproduce

```gdscript
@tool
class_name MeshGaeaRenderer
extends GaeaRenderer3D


@export var mesh_instance: MeshInstance3D
## If [code]true[/code], normals will not be smoothed,
## meaning the mesh will look more low-poly.
@export var flat_normals: bool = false


func _draw_area(area: AABB) -> void:
	if area.size == Vector3.ZERO:
		mesh_instance.mesh = null
		return

	var array_mesh: ArrayMesh = ArrayMesh.new()
	var surface_tool: SurfaceTool = SurfaceTool.new()

	surface_tool.begin(Mesh.PRIMITIVE_TRIANGLES)
	if flat_normals:
		surface_tool.set_smooth_group(-1)

	for z in range(area.position.z, area.end.z + 1):
		for x in range(area.position.x, area.end.x + 1):
			var max_height: int
			for y in range(area.position.y, area.end.y + 1):
				var tile_position := Vector3(x, y, z)

				if not generator.grid.has(tile_position):
					continue

				max_height = maxi(
					tile_position.y, max_height
				)

			surface_tool.add_vertex(Vector3(x, max_height, z))


	var vert: int = 0
	for z in area.size.z:
		for x in area.size.x:
			surface_tool.add_index(vert)
			surface_tool.add_index(vert + 1)
			surface_tool.add_index(vert + area.size.x + 1)
			surface_tool.add_index(vert + area.size.x + 1)
			surface_tool.add_index(vert + 1)
			surface_tool.add_index(vert + area.size.x + 2)
			vert += 1
		vert += 1

	surface_tool.generate_normals()

	array_mesh = surface_tool.commit()

	mesh_instance.mesh = array_mesh
```
Here's the code for the renderer. It's using my addon Gaea, which just gives it a grid of heightmap positions to generate from. 

### Minimal reproduction project

[blurry_edges_procedural_mesh.zip](https://github.com/godotengine/godot/files/13047101/blurry_edges_procedural_mesh.zip)
To use: click the generate boolean to generate the mesh in-editor.

**Comment by Calinou** [comment] 2023-10-19 16:06
This is likely intended. Smooth normals are intended to be used when your mesh is detailed. When it lacks detail, lighting differences will be hard to see due to vertex normal interpolation.

If you want lighting to be more detailed with smooth normals, subdivide your meshes or use a bevel-style operation (preferably, as this is more efficient).

**Comment by BenjaTK** [comment] 2023-10-19 19:46
> This is likely intended. Smooth normals are intended to be used when your mesh is detailed. When it lacks detail, lighting differences will be hard to see due to vertex normal interpolation. The way your DirectionalLight3D is rotated can also make a big difference.
> 
> If you want lighting to be more detailed with smooth normals, subdivide your meshes or use a bevel-style operation (preferably, as this is more efficient).
> 
> Also, please upload a minimal reproduction project[1](#user-content-fn-1-65e4169d238b8332c31427ad407bc41b) to make this easier to troubleshoot.
> ## Footnotes
> 
>     1. A small Godot project which reproduces the issue, with no unnecessary files included. Be sure to not include the `.godot` folder in the archive (but keep `project.godot`).Drag and drop a ZIP archive to upload it. **Do not select another field until the project is done uploading.****Note for C# users:** If your issue is _not_ Mono-specific, please upload a minimal reproduction project written in GDScript or VisualScript. This will make it easier for contributors to reproduce the issue locally as not everyone has a Mono setup available. [↩](#user-content-fnref-1-65e4169d238b8332c31427ad407bc41b)

Uploaded a reproduction project! Hope that helps. How would I go around subdividing the mesh/using a bevel operation?

**Comment by Calinou** [comment] 2023-10-19 20:29
> Uploaded a reproduction project! Hope that helps. How would I go around subdividing the mesh/using a bevel operation?

Please don't ask support questions here, as this issue tracker is meant to be used for bug reports only. Use one of the other [community channels](https://godotengine.org/community) instead.

**Comment by clayjohn** [comment] 2023-10-19 21:45
The described issue in the OP is not a bug. The "blurriness" you see is from using smooth normals. If you think flat normals look better for your game, then you can use those. If you want to blend between smooth and flat normals, you can also do that by calculating normals yourself and using smooth groups. 

This is not a place to receive support for how to actually implement the effect you want to implement. This space is for reporting bugs only. Since the issue you have is not a bug with the engine, I will close this report. As Calinou pointed out above. Please ask for support on one of the various community channels

**Closed by clayjohn** 2023-10-19 21:45 UTC
Labels: topic:rendering, needs testing, topic:3d
