### ISSUE TITLE
Open a directory prompt popup shows weird rectangle in sub-folder

### ISSUE THREAD

**Issue by hsandt** [godotengine/godot#82959] opened 2023-10-07 12:19 UTC
### Godot version

v4.1.1.stable.official [bd6af8e0e]

### System information

Godot v4.1.1.stable - Ubuntu 22.04.3 LTS 22.04 - Vulkan (Compatibility) - Mesa Intel(R) HD Graphics 4600 (HSW GT2) () - Intel(R) Core(TM) i7-4710HQ CPU @ 2.50GHz (8 Threads)

### Issue description

I was using GUT which relies on folder selection to find test scripts, and the popups started showing weird blue rectangles when I entered the test subfolder.

The rectangle changes position depending on whether a folder is selected or not.

![Godot 4 1 1 GUT select dir popup weird rectangle](https://github.com/godotengine/godot/assets/1067772/7fc5e6cc-0b6e-4afd-97c3-57d8d2b4ce87)
![Godot 4 1 1 GUT select dir popup weird rectangle 2](https://github.com/godotengine/godot/assets/1067772/31872d10-126d-46e2-9fb2-bc5ce627d761)

I assume GUT is using a native function and therefore this is a Godot bug.

I'm not familiar with the API to prompt folder selection myself so I couldn't write a true MWE but feel free to upload your own, or point me to said API (honestly it's more a matter of time as I want to go on with my project right now).

### Steps to reproduce

1. In any project, install GUT and activate add-on, see https://github.com/bitwes/Gut/wiki/Install
2. Open GUT panel, on the right side scroll down, and under Test Directories, select Directory 1 > ...
3. In the folder selection popup, enter any subfolder and click on a folder, then outside a folder area to test both rectangle positions

### Minimal reproduction project

N/A

**Comment by timothyqiu** [comment] 2023-10-07 12:51
Duplicate of #74115

Thanks for reporting the bug nonetheless!

**Closed by timothyqiu** 2023-10-07 12:51 UTC
