### ISSUE TITLE
Generate procedural-sky texture with gpu(based on shader)

### ISSUE THREAD

**Issue by MadIcecream** [godotengine/godot#11433] opened 2017-09-20 05:30 UTC
Currently godot generates skybox texture with cpu.
How about make it based on shader? I think it would be faster and be possible to make a realtime dynamic sky.

Here is unity's procedural-sky shader, hope it would be helpful: https://gist.github.com/cutepig49/450897569df1df5d1c996ae653610a3b

**Comment by Zylann** [comment] 2017-09-20 12:50
Last time I talked to @reduz about dynamic skyboxes in general the problem is that Godot not only needs the "visible" sky texture, but also other various textures used for PBR. You would need to also generate them on GPU?

**Comment by bojidar-bg** [comment] 2018-06-08 18:04
Isn't this obsoleted by #17510?

**Comment by Zylann** [comment] 2018-06-08 18:44
@bojidar-bg does it also address the fact PBR textures need to be realtime as well?

**Comment by bojidar-bg** [comment] 2018-06-08 21:09
I'm not completely sure, but I think so, yea.

**Comment by BastiaanOlij** [comment] 2018-06-08 23:35
Duplicate of #8668 ?

Read my full comments there on the good/bad/ugly.
And see working solution: https://github.com/BastiaanOlij/godot-sky-asset/tree/use_proxy_fix and video of said asset: https://youtu.be/-2YWV1NWwGY

**Comment by bojidar-bg** [comment] 2018-06-09 11:00
Ok, closing as obsolete/duplicate of the above-mentioned issues.

**Closed by bojidar-bg** 2018-06-09 11:00 UTC
Labels: feature proposal, topic:rendering
