### ISSUE TITLE
GDScript deletes custom GDNative objects on change of scope.

### ISSUE THREAD

**Issue by SnailBones** [godotengine/godot#31252] opened 2019-08-09 22:06 UTC
**Godot version:**
3.1-stable

**OS/device including version:**
Windows 10

Working with two nested GDNative classes called by GDScript, the inner class is sometimes unexpectedly returned as a [Deleted Object]. This occurs appears to happen in a change of scope after modifying the object, unfortunately this interferes with creating objects in a loop.

Gdscrpt:
```
const ARRAY2D = preload("bin/grid.gdns")
const CELLSCRIPT = preload("bin/cell.gdns")

onready var next_state = ARRAY2D.new()

func _ready():
	next_state.init(ROWS, COLUMNS) # My custom setup function

	next_state.setCell(0, 0, CELLSCRIPT.new())
	var cell0 = next_state.getCell(0, 0)
	print("cell at 0 0 is ", cell0)
	print("height is ", cell0.height)

	next_state.setCell(0, 1, CELLSCRIPT.new())
	var cell1 = next_state.getCell(0, 1)
	print("cell at 0 1 is ", cell1)
	print("height is ", cell1.height)

	cell0 = next_state.getCell(0, 0)
	print("cell at 0 0 is ", cell0)
	print("height is ", cell0.height)

	for i in range(2):
		# Sets the same cells as above
		next_state.setCell(0, i, CELLSCRIPT.new())

	cell0 = next_state.getCell(0, 0)
	print("cell at 0 0 is ", cell0)
	print("height is ", cell0.height)
```

Output:
```
cell at 0 0 is [Reference:1152]
height is 0
cell at 0 1 is [Reference:1153]
height is 0
cell at 0 0 is [Reference:1152]
height is 0
cell at 0 0 is [Deleted Object]
```

The game then crashes with error message:

"Invalid get index 'height' (on base: 'previously freed instance')."

C++:

```
void Grid::setCell(int x, int y, Cell *val)
{
	grid[x][y] = *val;
}

Cell *Grid::getCell(int x, int y)
{
	Cell *v = &(grid[x][y]);
	return v;
}
```

I'm not completely confident about these functions, as I'm new to C++ and I've been unable to find much documentation on GDNative. I've also tried returning a `Ref<Cell>` from getCell(), and the issue remains.

**Comment by SnailBones** [comment] 2019-08-11 04:23
Ran it in debug mode, here's the backtrace:
```
[0] Variant::reference (C:\Users\Aidan\Downloads\godot-master\godot-master\core\variant.cpp:915)
[1] Variant::reference (C:\Users\Aidan\Downloads\godot-master\godot-master\core\variant.cpp:915)
[2] Variant::Variant (C:\Users\Aidan\Downloads\godot-master\godot-master\core\variant.cpp:2664)
[3] godot_variant_new_copy (C:\Users\Aidan\Downloads\godot-master\godot-master\modules\gdnative\gdnative\variant.cpp:66)
[4] godot::Variant::Variant (C:\Users\Aidan\Documents\Fun Stuff\Godot\gdnative_cpp_example\godot-cpp\src\core\Variant.cpp:20)
[5] godot::_WrappedMethod<godot::Grid,godot::Ref<godot::Cell>,int,int,float>::apply<0,1,2> (C:\Users\Aidan\Documents\Fun Stuff\Godot\Cells d2\godot-cpp\include\core\Godot.hpp:183)
[6] godot::__wrapped_method<godot::Grid,godot::Ref<godot::Cell>,int,int,float> (C:\Users\Aidan\Documents\Fun Stuff\Godot\Cells d2\godot-cpp\include\core\Godot.hpp:210)
[7] NativeScriptInstance::call (C:\Users\Aidan\Downloads\godot-master\godot-master\modules\gdnative\nativescript\nativescript.cpp:719)
[8] Object::call (C:\Users\Aidan\Downloads\godot-master\godot-master\core\object.cpp:912)
[9] Variant::call_ptr (C:\Users\Aidan\Downloads\godot-master\godot-master\core\variant_call.cpp:1074)
[10] GDScriptFunction::call (C:\Users\Aidan\Downloads\godot-master\godot-master\modules\gdscript\gdscript_function.cpp:1079)
[11] GDScriptInstance::call_multilevel (C:\Users\Aidan\Downloads\godot-master\godot-master\modules\gdscript\gdscript.cpp:1180)
[12] Node::_notification (C:\Users\Aidan\Downloads\godot-master\godot-master\scene\main\node.cpp:60)
[13] Node::_notificationv (C:\Users\Aidan\Downloads\godot-master\godot-master\scene\main\node.h:46)
[14] CanvasItem::_notificationv (C:\Users\Aidan\Downloads\godot-master\godot-master\scene\2d\canvas_item.h:166)
[15] Control::_notificationv (C:\Users\Aidan\Downloads\godot-master\godot-master\scene\gui\control.h:51)
[16] Object::notification (C:\Users\Aidan\Downloads\godot-master\godot-master\core\object.cpp:945)
[17] SceneTree::_notify_group_pause (C:\Users\Aidan\Downloads\godot-master\godot-master\scene\main\scene_tree.cpp:959)
[18] SceneTree::idle (C:\Users\Aidan\Downloads\godot-master\godot-master\scene\main\scene_tree.cpp:515)
[19] Main::iteration (C:\Users\Aidan\Downloads\godot-master\godot-master\main\main.cpp:1920)
[20] OS_Windows::run (C:\Users\Aidan\Downloads\godot-master\godot-master\platform\windows\os_windows.cpp:3010)
[21] widechar_main (C:\Users\Aidan\Downloads\godot-master\godot-master\platform\windows\godot_windows.cpp:162)
[22] _main (C:\Users\Aidan\Downloads\godot-master\godot-master\platform\windows\godot_windows.cpp:184)
[23] main (C:\Users\Aidan\Downloads\godot-master\godot-master\platform\windows\godot_windows.cpp:196)
[24] __scrt_common_main_seh (d:\agent\_work\2\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288)
[25] BaseThreadInitThunk
-- END OF BACKTRACE --
```

**Comment by vnen** [comment] 2019-11-01 17:16
Looks like the GDNative code is not hanging to the reference, so when GDScript releases after going out of scope (which is the correct behavior) the reference counter reaches zero and frees the object.

Not sure if this is a problem in the bindings or your code. But I do think you should send and receive `Ref<Cell>` to/from the C++ functions. The raw pointer doesn't really increase the reference counter.

**Comment by vnen** [comment] 2020-01-16 15:10
Pretty sure this is not a bug, but an incorrect use of references. As I mentioned, and as stated in https://github.com/GodotNativeTools/godot-cpp/issues/320#issuecomment-520303910, the right way would be using `Ref<Cell>` instead of raw pointers so the reference counts are properly updated.

**Closed by vnen** 2020-01-16 15:10 UTC
Labels: bug, topic:gdnative, topic:gdscript
