### ISSUE TITLE
Exported Web Project does not work on Linux with Mesa 22.2+

### ISSUE THREAD

**Issue by ngreve** [godotengine/godot#68180] opened 2022-11-02 19:20 UTC
### Godot version

v4.0.beta4.official [e6751549c]

### System information

- Chromium Version 107.0.5304.87 (Official Build) Arch Linux (64-bit)
- Firefox 107.0b8

- OS: Arch Linux
- ~KERNEL: 6.0.6-arch1-1~
- ~KERNEL: 6.0.7-arch1-1~
- ~KERNEL: 6.0.8-arch1-1~
- KERNEL: 6.0.9-arch1-1
- CPU: AMD Ryzen 7 3700X 8-Core
- GPU: AMD Radeon RX 6900 XT (navi21, LLVM 14.0.6, DRM 3.48, 6.0.6-arch1-1)
- GPU DRIVER: 4.6 Mesa 22.2.1

### Issue description

When I try to start the provided minimal project as a web project, the mesh in the scene is not visible and the browser console is showing this error right after the site loaded:
![Screenshot from 2022-11-02 20-01-35](https://user-images.githubusercontent.com/18660100/199584004-2ab31cd9-374c-46c3-b3d3-2688cce7d7c8.png)

After that, the console is flooded with these error messages:
![Screenshot from 2022-11-02 19-49-14](https://user-images.githubusercontent.com/18660100/199581514-45acf4c0-b883-4e7a-9dbe-136e08f34df7.png)

### Steps to reproduce

Use the [official beta4](https://downloads.tuxfamily.org/godotengine/4.0/beta4/) with the provided templates and try to start the provided project as a web application

### Minimal reproduction project
[beta4_webtest.zip](https://github.com/godotengine/godot/files/9923528/beta4_webtest.zip)

**Comment by dzil123** [comment] 2022-11-03 06:44
I've tested the project on the same system and browser versions listed and I can't reproduce this.

**Comment by ngreve** [comment] 2022-11-03 07:04
When I am working with godot I am actually always building from source, using the master branch. Here I used the official beta, to make sure my build process is not broken in any way.

So, does anyone know about any build cache/temporary files/config file which could cause this?
Does Godot somewhere store files, which could cause some sort of compatability issues, when I continuously "switch versions" this way?

The thing is, that it also worked for me, up until ~2 weeks ago. And since then, I am stuck with the shown errors.

**Comment by dzil123** [comment] 2022-11-03 08:39
I think those are the only folders that could be the culprit. You can try cleaning `.godot` in the project and running the official binary with a [`_sc_`](https://docs.godotengine.org/en/stable/tutorials/io/data_paths.html#self-contained-mode) file in the same directory.

Just to confirm, this is on the non-mono version, and the web export prints `v4.0.beta4.official.e6751549c`?

If that doesn't resolve it, can you please upload a build showcasing these errors to itch.io? Could this be a gpu driver issue?

**Comment by ngreve** [comment] 2022-11-03 16:19
> Just to confirm, this is on the non-mono version, and the web export prints v4.0.beta4.official.e6751549c?

non-mono version and yes, it prints `v4.0.beta4.official.e6751549c`:
![image](https://user-images.githubusercontent.com/18660100/199773727-3610fd73-ce21-470b-ab71-6aab96024451.png)

https://nico-g.itch.io/godot-bug-testing?secret=QyWWf5yhEeVCqjMq1imFUYBmuA
itch.io is showing me this error now:
![image](https://user-images.githubusercontent.com/18660100/199774233-17ab2cef-9b9d-45e6-abb5-4a7bae7a3dc2.png)

But I did enable `SharedBufferArray` support:
![image](https://user-images.githubusercontent.com/18660100/199774388-235661a1-5009-421d-9e5a-cfd1a6a84ba8.png)

This is the exported project:
[index.zip](https://github.com/godotengine/godot/files/9930993/index.zip)

> Could this be a gpu driver issue?

.... I am open for ideas on how to test it

**Comment by akien-mga** [comment] 2022-11-03 16:25
itch's SharedArrayBuffer support only works in Chrome I think, so if the above test was in Firefox it may be why.

**Comment by ngreve** [comment] 2022-11-03 16:27
Thanks! I got it running with Chromium. But unfortunately the issue is still there for me.

**Comment by ngreve** [comment] 2022-11-03 22:07
I've managed to install an older version (`mesa-22.1.7`) of the mesa drivers from my package cache.

Even though the capsule in the web version is not lighted properly, it is at least there now.
![image](https://user-images.githubusercontent.com/18660100/199843301-47dafd4a-d26c-46b1-9f4b-9fa7139f9052.png)


The error messages also disappeared. It is probably a faulty GPU driver of some sort.

**Comment by dzil123** [comment] 2022-11-04 00:06
What is the first broken mesa version? There's a few versions in between 22.1.7 and 22.2.1: https://archive.archlinux.org/packages/m/mesa/

**Comment by ngreve** [comment] 2022-11-04 17:43
I've now tested `22.0.0-2` and `22.0.0-1`, both are broken for me. `22.0.0-1` even partially broke my windows manager (gnome); missing letters all over the place.

`22.1.7` is the last version that works

**Comment by akien-mga** [comment] 2022-11-04 18:38
> I've now tested `22.0.0-2` and `22.0.0-1`, both are broken for me. `22.0.0-1` even partially broke my windows manager (gnome); missing letters all over the place.

I suppose you meant `22.2.0`?

**Comment by ngreve** [comment] 2022-11-04 18:42
Yes, sorry. I've corrected it.

**Comment by AntonioDell** [comment] 2022-12-02 07:53
I have a similar problem with Godot 4 Beta 7. The only difference for me is that I do not get spammed with messages after the initial error.
It happens on Pop_OS! 22.04 with Firefox and Chrome.

You can check this out on my projects website: https://pip-melville.de/

**Comment by ngreve** [comment] 2022-12-07 18:39
I've just compiled the newest version from master v4.0.beta.custom_build [a7937fe54]. And it seems to get better ...

![image](https://user-images.githubusercontent.com/18660100/206267016-0d35fa46-15a4-45ef-a945-4dfcef7c60d8.png)

I do see the capsule now, but there are still errors in the console output

Current system information:
```
KERNEL: 6.0.11-arch1-1
GPU: AMD Radeon RX 6900 XT (navi21, LLVM 14.0.6, DRM 3.48, 6.0.11-arch1-1)
GPU DRIVER: 4.6 Mesa 22.2.3
```

**Comment by AntonioDell** [comment] 2022-12-10 08:14
I can confirm that Godot 4 beta 8 solved the gray screen issue I was experiencing with Godot 4 beta 7.

**Comment by clayjohn** [comment] 2022-12-12 21:59
The remaining issues reported here should be fixed by https://github.com/godotengine/godot/pull/69634 and https://github.com/godotengine/godot/pull/69901

Since you are building from master can you confirm @ngreve?

**Comment by ngreve** [comment] 2022-12-12 22:31
Can not confirm.
I've built v4.0.beta.custom_build [ba4bd7f00] and the error outputs from my last post are still there, so no difference for me.
Tested with Firefox and Chromium.

**Comment by AntonioDell** [comment] 2022-12-13 06:47
My project is 2D only, since the screenshot from your comment shows a 3D object, maybe this is a hint to the discrepancies?

**Comment by ngreve** [comment] 2022-12-14 18:48
The issue also appears to me with an empty 2DNode as the main scene.
Just to clarify: The `out of bounds` error is gone since v4.0.beta.custom_build[a7937fe]. Since then the capsule from the minimal project is rendered and visible.
The only error I get at this point is this  `USER ERROR: SceneShaderGLES3: Fragment shader compilation failed:` error. I can not tell how crucial that is.
I've put a random shader on the capsule - a little bit metallic, blueish color and and red emission. When I put the web project (left) and the native project (right) side by side, you can definitely see a difference. But I can not tell if this is expected behavior, or if that's caused by the the `Fragment shader compilation failed:` 
![image](https://user-images.githubusercontent.com/18660100/207684694-03f1fff1-56a4-4075-b495-38b09b3e1825.png)

**Comment by clayjohn** [comment] 2022-12-14 19:56
> The issue also appears to me with an empty 2DNode as the main scene. Just to clarify: The `out of bounds` error is gone since v4.0.beta.custom_build[[a7937fe](https://github.com/godotengine/godot/commit/a7937fe54cd2c1f407a529e46e2708aea5ce7243)]. Since then the capsule from the minimal project is rendered and visible. The only error I get at this point is this `USER ERROR: SceneShaderGLES3: Fragment shader compilation failed:` error. I can not tell how crucial that is. I've put a random shader on the capsule - a little bit metallic, blueish color and and red emission. When I put the web project (left) and the native project (right) side by side, you can definitely see a difference. But I can not tell if this is expected behavior, or if that's caused by the the `Fragment shader compilation failed:` ![image](https://user-images.githubusercontent.com/18660100/207684694-03f1fff1-56a4-4075-b495-38b09b3e1825.png)

Are you using the gl_compatibility renderer in both cases?

The fragment shader error is very interesting I can see the shader printout from your original post says that ``MAX_LIGHT_DATA_STRUCTS`` is 0. This can only happen two ways:
1. You set it to 0 in your project settings (it is set to 32 in the MRP) or
2. Your GPU reports a maximum uniform block size of less than 64 (16384 is the bare minimum for any compliant OpenGL driver). 

In either case it is getting set to a value that it should never be set to and we will need to figure out why. Would you be okay compiling and running a custom build that prints a bunch more debug info?

Also would be useful to test from a more up-to-date build as https://github.com/godotengine/godot/commit/a7937fe54cd2c1f407a529e46e2708aea5ce7243 does not include https://github.com/godotengine/godot/pull/69901 which is the PR I think may help

**Comment by ngreve** [comment] 2022-12-16 16:58
> Also would be useful to test from a more up-to-date build

The post of https://github.com/godotengine/godot/issues/68180#issuecomment-1351968598 was done using the newest available version from master at this time. And I tested it again with the now newest version v4.0.beta.custom_build [2e657e51f] and the issue is still there.

> You set it to 0 in your project settings (it is set to 32 in the MRP) or

Where can I check that?


> Are you using the gl_compatibility renderer in both cases?

Good point, I didn't
But I did now:
![image](https://user-images.githubusercontent.com/18660100/208148502-9659ad4b-447f-42ab-8c28-a71706695a9b.png)
![image](https://user-images.githubusercontent.com/18660100/208148679-4b35edd5-a34f-427e-8cf7-3e11898325d3.png)
Again, on the left side the web project, the right side shows the native project. Still very different.

> Would you be okay compiling and running a custom build that prints a bunch more debug info?

Sure, but someone has to tell me what I should do and where I should do it.

**Comment by akien-mga** [comment] 2023-02-22 15:24
Is this still reproducible in 4.0 RC 3 or later?

**Comment by turnercore** [comment] 2023-02-24 00:42
I'm getting console errors and extremely long load times (if it _ever_ starts) right out of the box on RC4. This is with a project that is just one scene with the godot icon in it. This is on the Arc browser on MacOS (although I also tried other browsers with similar results). 

I haven't tested on Windows or Linux versions of Godot, when I get back where I can get to my VM I can try it on other builds to see if it's better.

<img width="541" alt="Screenshot of Arc" src="https://user-images.githubusercontent.com/85597948/221062883-edaae067-0f82-4cae-9c2b-e8f35756d162.png">

[web-export-RC4.log](https://github.com/godotengine/godot/files/10819617/web-export-RC4.log)

**Comment by clayjohn** [comment] 2023-02-24 01:46
> I'm getting console errors and extremely long load times (if it _ever_ starts) right out of the box on RC4. This is with a project that is just one scene with the godot icon in it. This is on the Arc browser on MacOS (although I also tried other browsers with similar results).
> 
> I haven't tested on Windows or Linux versions of Godot, when I get back where I can get to my VM I can try it on other builds to see if it's better.
> 
> <img alt="Screenshot of Arc" width="541" src="https://user-images.githubusercontent.com/85597948/221062883-edaae067-0f82-4cae-9c2b-e8f35756d162.png">
> 
> [web-export-RC4.log](https://github.com/godotengine/godot/files/10819617/web-export-RC4.log)

You seem to be experiencing https://github.com/godotengine/godot/issues/70691. Which is a macOS specific issue. This issue is Linux/mesa specific.

**Comment by inbouto** [comment] 2023-05-06 17:19
I'm having the same issue, on archlinux, with a 6700XT and up-to-date drivers, when using spotlights and omnilights.

**Closed** 2023-08-28 13:08 UTC
Labels: bug, platform:linuxbsd, platform:web, topic:export
