### ISSUE TITLE
First time opening a project throws TimerTimeout error message.

### ISSUE THREAD

**Issue by chalcosoma** [godotengine/godot#35671] opened 2020-01-28 18:57 UTC
**Godot version:**
3.2 RC 4 Mono x64

**OS/device including version:**
Windows 10 Pro x64 1909

**Issue description:**
When I first started the new Godot version and pressed 'Run' the error showed up.
I don't remember the error message exactly but it was something saying the TimerTimeout function was non-existent and saying something about "timeout". I could not find the Godot log so I don't know how to provide more information on this. I followed Calinou's answer to my other issue about the crash log of Godot to find the log path but I didn't find the log https://github.com/godotengine/godot/issues/30568 . I found the Mono log but it does not have anything about this error.

**Steps to reproduce:**
I could not reproduce the error after opening the project for the second time.

**Minimal reproduction project:**

**Comment by Calinou** [comment] 2020-04-17 19:36
Closing, as the issue seems to be difficult to reproduce and nobody else has been able to reproduce it. Please comment if you can still reproduce it.

**Closed by Calinou** 2020-04-17 19:36 UTC
Labels: bug, needs testing, topic:core
