### ISSUE TITLE
Moving Objects under nested YSort crashes 3.1 Beta

### ISSUE THREAD

**Issue by nazgum** [godotengine/godot#24915] opened 2019-01-11 17:31 UTC
**Godot version:**
3.1 Beta

**OS/device including version:**
Linux/Nvidia

**Issue description:**
If I have the following nested ysort setup:

- YSort
  - YSort
    - Obj1
    - Obj2

If I move Obj2 under Obj1, to end up with:

- YSort
  - YSort
    - Obj1
      - Obj2

Godot crashes.  Similarly, if I already have this setup, if I try to move Obj2 out from under Obj1 to say be under the nested YSort, Godot crashes.

**Crash Backtrace**
handle_crash: Program crashed with signal 11
Dumping the backtrace. Please include this when reporting the bug on https://github.com/godotengine/godot/issues
[1] /lib/x86_64-linux-gnu/libc.so.6(+0x41100) [0x7f79824a7100] (??:0)
[2] /home/nazgum/Apps/godot/godot-v3.1-beta1() [0x223ccd0] (<artificial>:?)
[3] /home/nazgum/Apps/godot/godot-v3.1-beta1() [0x223bc9f] (<artificial>:?)
[4] /home/nazgum/Apps/godot/godot-v3.1-beta1() [0x227bf93] (<artificial>:?)
[5] /home/nazgum/Apps/godot/godot-v3.1-beta1() [0x227cde6] (<artificial>:?)
[6] /home/nazgum/Apps/godot/godot-v3.1-beta1() [0x227f148] (<artificial>:?)
[7] /home/nazgum/Apps/godot/godot-v3.1-beta1() [0x998bfd] (??:?)
[8] /home/nazgum/Apps/godot/godot-v3.1-beta1() [0x7a7d9d] (??:?)
[9] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xeb) [0x7f798248a09b] (??:0)
[10] /home/nazgum/Apps/godot/godot-v3.1-beta1() [0x7b5fae] (??:?)
-- END OF BACKTRACE --

**Comment by volzhs** [comment] 2019-01-11 17:38
probably it's fixed by #24826 in recent...

**Comment by FlamyAT** [comment] 2019-01-11 18:50
I can't reproduce it with version bf79924


> probably it's fixed by #24826 in recent...

I approve with @volzhs

**Comment by akien-mga** [comment] 2019-01-11 18:56
Duplicate of #24918 then.

**Closed by akien-mga** 2019-01-11 18:56 UTC
