### ISSUE TITLE
Tooltip offset in editor is too close

### ISSUE THREAD

**Issue by satscape** [godotengine/godot#3759] opened 2016-02-18 09:34 UTC
When I'm typing code, the code completion tooltip is above where I'm typing and too close for my liking. Ideally, it should be below where I'm typing so that I can see the line I've just typed so I can see variable names etc instead of having to hit ESC to see them, but the main issue is it's too close. This is on Linux if that makes any difference. It may be fine on other operating systems.
Ideally, I'd like to see a setting in the "editor settings" window for "editor tooltip y-offset".
exhibit A: http://i.imgur.com/u2BXq7L.png
Thank you.

**Comment by nunodonato** [comment] 2016-02-18 09:46
I've noticed it too, sometimes it gets in the way :)
Not so sure about the editing settings.. is it really that relevant that should be a setting or is it better to set a sane default for everyone? I mean, who changes tooltips y offsets? :)

**Comment by KioriSun** [comment] 2016-02-18 12:32
+1 this has annoyed me also.

**Comment by freemanfromgodotengine** [comment] 2016-02-18 13:01
+1 as well. The hint should pop-up below or to the left of the scroll-up list. Now it always hides the last available option there.

**Comment by akien-mga** [comment] 2016-02-18 13:06
Duplicate of #1261. Pull requests welcome :)

**Closed by akien-mga** 2016-02-18 13:06 UTC
Labels: enhancement, topic:editor
