### ISSUE TITLE
Memory leak when running the scene in the editor

### ISSUE THREAD

**Issue by Rindbee** [godotengine/godot#68816] opened 2022-11-18 05:54 UTC
### Godot version

v4.0.beta5.official [89a33d28f], cca9f780252f48beb9a7a39826b40bcb3a4ade54

### System information

Linux Mint 21, Vulkan API 1.2.0, NVIDIA GeForce GTX 1050 Ti

### Issue description

Build the editor with the following flags `use_llvm=yes linker=lld use_ubsan=yes use_asan=yes dev_build=yes`.

Run the built editor, create/open a project, and run any scene, the following memory leak message will be printed when exiting the editor:
```
Direct leak of 312 byte(s) in 1 object(s) allocated from:
    #0 0x55cf11e841ae in malloc (/opt/godot/godot/bin/godot.linuxbsd.editor.dev.x86_64.llvm.san+0x199e31ae) (BuildId: 1f9282c27aaf75c3)
    #1 0x55cf2ff112cd in Memory::alloc_static(unsigned long, bool) /opt/godot/godot/core/os/memory.cpp:75:14
    #2 0x55cf2ff11122 in operator new(unsigned long, char const*) /opt/godot/godot/core/os/memory.cpp:40:9
    #3 0x55cf2e666430 in RendererRD::TextureStorage::canvas_texture_get_uniform_set(RID, RenderingServer::CanvasItemTextureFilter, RenderingServer::CanvasItemTextureRepeat, RID, int, RID&, Vector2i&, Color&, bool&, bool&) /opt/godot/godot/servers/rendering/renderer_rd/storage_rd/texture_storage.cpp:579:24
    #4 0x55cf2dc32fab in RendererCanvasRenderRD::_bind_canvas_texture(long, RID, RenderingServer::CanvasItemTextureFilter, RenderingServer::CanvasItemTextureRepeat, RID&, RendererCanvasRenderRD::PushConstant&, Vector2&) /opt/godot/godot/servers/rendering/renderer_rd/renderer_canvas_render_rd.cpp:366:62
    #5 0x55cf2dba8340 in RendererCanvasRenderRD::_render_item(long, RID, RendererCanvasRender::Item const*, long, Transform2D const&, RendererCanvasRender::Item*&, RendererCanvasRender::Light*, RendererCanvasRenderRD::PipelineVariants*) /opt/godot/godot/servers/rendering/renderer_rd/renderer_canvas_render_rd.cpp:508:5
    #6 0x55cf2dbd434c in RendererCanvasRenderRD::_render_items(RID, int, Transform2D const&, RendererCanvasRender::Light*, bool) /opt/godot/godot/servers/rendering/renderer_rd/renderer_canvas_render_rd.cpp:1151:3
    #7 0x55cf2dbea63a in RendererCanvasRenderRD::canvas_render_items(RID, RendererCanvasRender::Item*, Color const&, RendererCanvasRender::Light*, RendererCanvasRender::Light*, Transform2D const&, RenderingServer::CanvasItemTextureFilter, RenderingServer::CanvasItemTextureRepeat, bool, bool&) /opt/godot/godot/servers/rendering/renderer_rd/renderer_canvas_render_rd.cpp:1526:4
    #8 0x55cf2d57c330 in RendererCanvasCull::_render_canvas_item_tree(RID, RendererCanvasCull::Canvas::ChildItem*, int, RendererCanvasCull::Item*, Transform2D const&, Rect2 const&, Color const&, RendererCanvasRender::Light*, RendererCanvasRender::Light*, RenderingServer::CanvasItemTextureFilter, RenderingServer::CanvasItemTextureRepeat, bool, unsigned int) /opt/godot/godot/servers/rendering/renderer_canvas_cull.cpp:73:22
    #9 0x55cf2d589ea7 in RendererCanvasCull::render_canvas(RID, RendererCanvasCull::Canvas*, Transform2D const&, RendererCanvasRender::Light*, RendererCanvasRender::Light*, Rect2 const&, RenderingServer::CanvasItemTextureFilter, RenderingServer::CanvasItemTextureRepeat, bool, bool, unsigned int) /opt/godot/godot/servers/rendering/renderer_canvas_cull.cpp:379:3
    #10 0x55cf2d68374d in RendererViewport::_draw_viewport(RendererViewport::Viewport*) /opt/godot/godot/servers/rendering/renderer_viewport.cpp:533:17
    #11 0x55cf2d68ceb9 in RendererViewport::draw_viewports() /opt/godot/godot/servers/rendering/renderer_viewport.cpp:711:4
    #12 0x55cf2d2cc0bb in RenderingServerDefault::_draw(bool, double) /opt/godot/godot/servers/rendering/rendering_server_default.cpp:91:17
    #13 0x55cf2d2d7324 in RenderingServerDefault::draw(bool, double) /opt/godot/godot/servers/rendering/rendering_server_default.cpp:391:3
    #14 0x55cf120fe159 in Main::iteration() /opt/godot/godot/main/main.cpp:3181:39
    #15 0x55cf11ee8c2f in OS_LinuxBSD::run() /opt/godot/godot/platform/linuxbsd/os_linuxbsd.cpp:799:7
    #16 0x55cf11ec1e29 in main /opt/godot/godot/platform/linuxbsd/godot_linuxbsd.cpp:73:6
    #17 0x7f97aa1dfd8f in __libc_start_call_main csu/../sysdeps/nptl/libc_start_call_main.h:58:16
```
In the latest commit cca9f780252f48beb9a7a39826b40bcb3a4ade54, after using `git reset --hard HEAD~5000` and rebuilding, this problem can still be reproduced.

Run the editor alone, or run the scene alone (similar to `godot --path code/godot/a/ res://node.tscn`), there is no above message when exiting.

### Steps to reproduce

1. Run the built editor via command line;
2. Create/open a project;
3. Run any scene;
4. Stop the scene and exit the editor;
5. Check the message on exit in the terminal.

### Minimal reproduction project

N/A

**Comment by timothyqiu** [comment] 2022-11-18 06:39
Duplicate of #65484

**Closed by timothyqiu** 2022-11-18 06:39 UTC
