### ISSUE TITLE
Blender Empty Cube not being converted into a collision body

### ISSUE THREAD

**Issue by A-Lamia** [godotengine/godot#40729] opened 2020-07-26 15:16 UTC
**Godot Version:** _v4.0._

**OS Version: Windows** _10._

I have used the same test blender file shared in https://github.com/godotengine/godot/issues/32678 and added a empty cube with -colonly as the doc said.

**Steps:**
Export blender file as single GLTF2 (.glb) file Add to local Godot project folder to auto import.

**Problem:**
Empty Cube being imported as a node3D

**Desired Effect:**
Empty Cube should be converted to a StaticBody with a collision node child set to BoxShape as the docs have said.

![godot windows tools 64_FxlPJjH1b](https://user-images.githubusercontent.com/6450181/88482627-d4810480-cfa5-11ea-8fcb-be2d97402ad9.png)

[32678-respect-import-hints-with-empty.zip](https://github.com/godotengine/godot/files/4977830/32678-respect-import-hints-with-empty.zip)

_Originally posted by @A-Lamia in https://github.com/godotengine/godot/issues/32678#issuecomment-664000245_

**Comment by A-Lamia** [comment] 2020-07-28 09:29
After further inspection it seems that exporting empties with gltf2 from blender (version 2.8X, 2.9X) does not export the needed information for Godot to correctly import the collision body.

**Comment by ConorLPBoyle** [comment] 2020-07-28 16:44
Export to gltf with custom properties on:

```
{
    "asset" : {
        "generator" : "Khronos glTF Blender I/O v1.2.75",
        "version" : "2.0"
    },
    "scene" : 0,
    "scenes" : [
        {
            "extras" : {
                "MM" : {
                    "revision" : "f94854aaf7ac8d09d521a6c5437361196822e46e"
                }
            },
            "name" : "Scene",
            "nodes" : [
                0
            ]
        }
    ],
    "nodes" : [
        {
            "extras" : {},
            "name" : "cube_empty-colonly",
            "rotation" : [
                0.2389068305492401,
                0.12964144349098206,
                -0.251981258392334,
                0.9287744760513306
            ],
            "scale" : [
                1.3872629404067993,
                1.3872630596160889,
                1.3872629404067993
            ],
            "translation" : [
                0,
                0,
                -16.017648696899414
            ]
        }
    ]
}
```

I also checked the Collada exporter and it doesn't export this property either. As far as Blender is concerned, it's just an empty transform that happens to be visualized as a cube.

On the Blender side, the exporter would either need to treat an empty node with an appropriate Display As property as if it had a mesh and export it with geometry, or output some custom properties defining the appropriate Display As and Size properties for that empty node which Godot would then use to generate the appropriate geometry.

One way, you have the unexpected behavior of Blender's exporter generating geometry based on what's intended to be a viewport visualization property. The other way, you end up with Godot's importer treating certain model files differently based on non-spec metadata.

**Comment by valeev-iv** [comment] 2020-10-31 13:58
Collada has an additional property (empty_draw_type) for empty objects which is not available in glTF
https://github.com/godotengine/godot/issues/32363#issuecomment-535522017

glTF exporter uses custom properties that were added manually
![Снимок0](https://user-images.githubusercontent.com/6941132/97780331-b98ae580-1bcf-11eb-8118-01c58c5dc352.PNG)

As far as I understand the problem is on two sides. Blender does not export required properties, and Godot looks for them in the wrong place.
You can write your own extensions for the glTF Blender exporter (https://docs.blender.org/manual/en/dev/addons/import_export/scene_gltf2.html#third-party-gltf-extensions)
I wrote one. Installed as a regular addon and allows you to add data to glTF file
![Снимок](https://user-images.githubusercontent.com/6941132/97779912-fdc8b680-1bcc-11eb-837d-93d3fa191ce6.PNG)
Then just activate the extension on export
![Снимок1](https://user-images.githubusercontent.com/6941132/97780159-aa576800-1bce-11eb-89dc-ad0de1665bd4.PNG)

I tried options with extensions and/or extras properties. It looks like specification allows this
https://github.com/KhronosGroup/glTF/blob/master/specification/2.0/README.md#nodeextensions
https://github.com/KhronosGroup/glTF/blob/master/specification/2.0/README.md#nodeextras
```
{
    "nodes" : [
        {
            "extensions" : {
                "GODOT_glTF_extension" : {
                    "empty_draw_type" : "CUBE"
                }
            },
            "extras" : {
                "Godot_custom_property" : 1,
                "empty_draw_type" : "CUBE"
            },
            "name" : "Empty -colonly"
        },
        {
            "children" : [
                0
            ],
            "mesh" : 0,
            "name" : "Cube"
        }
    ],
}
```
Unfortunately, Godot glTF importer ignores both options.
Need to find out how exactly should "empty_draw_type" property look like

There is Blender 2.90 add-on prototype, maybe it will be useful to someone.
[Godot glTF extension.zip](https://github.com/godotengine/godot/files/5469150/Godot.glTF.extension.zip)

PS: Sorry for my English. Translated by Google Translate

**Comment by fire** [comment] 2020-12-26 15:40
The gltf importer / exporter was changed recently. Please see how gltf2 extensions are implemented. Available for questions.

**Comment by william-lohan** [comment] 2022-06-17 06:28
I'm still running into this issue with Godot 3.4.4 and Blender 3.1.2

**Comment by akien-mga** [comment] 2022-07-17 13:50
Duplicate of #32363

**Closed by akien-mga** 2022-07-17 13:50 UTC
Labels: bug, confirmed, topic:import, topic:3d
