### ISSUE TITLE
Documentation for scripts is not available on start of the project most of the times.

### ISSUE THREAD

**Issue by tokengamedev** [godotengine/godot#84922] opened 2023-11-15 00:19 UTC
### Godot version

4.2.beta.6
Edit: Updated the correct version of Godot
### System information

Windows 11

### Issue description

When you have documentation for the code (from the code comments), the documentation is available when editing, but when you restart the project all the documentation is gone.

This is kind of hard to reproduce, but once it is, it will stick, but the output documentation has issues, explained below.

### Steps to reproduce

- Create documentaion by adding code like this 

```gdscript

## The color of the object. See [enum GameColors.COLOR].
@export var color: COLOR = COLOR.RED 
```

- Now save the file and exit the editor.
- After some time (Could not figure out how much time) you restart the editor. You will not find the documentation
- Waited for few minutes after opening, as it is a backend process to update documentation. Still no documentation.
- Now changed some of the commented code to trigger documentation scripts. Voila!! the documentation is available.

Wait !! 

There are issues, which was working earlier.
For Enum value property, it used to list all the values, it is no more there. It was a very useful feature.

**My thoughts on this:**
- Why the documentation needs to be updated on the start of the project, can it not be cached, based on the file modified timestamp
- If we have to live with the issues, can a menu option **"Clear cache and Restart"** to be provided like the Reload project

### Minimal reproduction project

Not required as it is not project specific or scenario specific

**Comment by and-rad** [comment] 2023-11-15 10:46
Sounds like #72952 or a variation of it.

**Comment by YuriSizov** [comment] 2023-11-15 10:57
Thanks for your report! This is a duplicate of https://github.com/godotengine/godot/issues/72406, so consolidating.

**Closed by YuriSizov** 2023-11-15 10:57 UTC
Labels: topic:gdscript, topic:editor, documentation, needs testing
