### ISSUE TITLE
Cursor disappears permanently when dialog is closed

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#42596] opened 2020-10-06 13:22 UTC
**Godot version:**

3.2.3 / ed33324

**Steps to reproduce:**
1. Open editor settings
2. Edit some color
3. Drag a value in a spin box
4. RIP
![xtnyLxdqD6](https://user-images.githubusercontent.com/2223172/95206910-8ed38a00-07e7-11eb-86db-4e7c5cdcd5c0.gif)

**Comment by theoway** [comment] 2020-10-06 14:11
Not able to produce it in 3.2 . Can you upload an MRP?

**Comment by KoBeWi** [comment] 2020-10-06 14:13
It happens in any project. You need to drag the number in a way that makes the cursor disappear.

**Comment by KoBeWi** [comment] 2020-10-06 15:25
It needs to disappear before closing. It's a bit tricky, because you need to drag it without selecting (the GIF is a bit misleading, sorry)

**Comment by JakubDemocko** [comment] 2020-10-06 19:10
Hello, I was able to reproduce the problem and I would love to contribute to this project :) Can you confirm me as a person dealing with this issue, please?

**Comment by JakubDemocko** [comment] 2020-10-10 15:54
I've found out that other sliders were broken too. For example when trying to adjust value for contrast which has horizontal slider it didn't work at all. I clicked somewhere on the slider, then moved my mouse - cursor is supposed to disappear and value change and after releasing the mouse button cursor should reappear. This didn't happen.

I've found out, that commenting out one line solves the mentioned problem and also the whole issue. It's the "SetCapture(wd.hWnd);" in DisplayServerWindows::_set_mouse_mode_impl() function. After commenting this everything seems to be working well. I can't tell what it's good for. It's used twice in the whole project.

Only one problem remains - when adjusting color value in editor->theme->accent/base color, you can adjust it with no problem by clicking arrow next to text area of some color and holding left mouse button and moving it up or down. But when you keep holding mouse button pressed and don't move for a while, the window to adjust color disappears and you're left without cursor.

So the questions now are:
- what does the "SetCapture(wd.hWnd);" do? Can I comment it?
- why does the color adjustment window disappear when I'm holding button pressed, changing the color value, but not moving for a while? How can I make it stop disappearing? Or how can I make the cursor reappear after the window has disappeared and I release it?

**Comment by KoBeWi** [comment] 2020-10-10 16:41
> what does the "SetCapture(wd.hWnd);" do? Can I comment it?

It's a method that hides mouse, don't touch it. The proper solution for this issue would be setting mouse capture to none when the control that captured it gets hidden. This should be done somewhere in LineEdit or SpinEdit.

> why does the color adjustment window disappear when I'm holding button pressed, changing the color value, but not moving for a while? How can I make it stop disappearing? Or how can I make the cursor reappear after the window has disappeared and I release it?

#23626

**Comment by JakubDemocko** [comment] 2020-10-11 19:58
Are we sure, that the SetCapture function is mentioned to hide the cursor? Because this is how it looks, when I comment that function - notice, that cursor will be hidden:

![gif_after_comment](https://user-images.githubusercontent.com/22524145/95688733-97bfc380-0c0c-11eb-8f76-569a0f2e2f4c.gif)

How can I see the body of this function? (ctrl + click gives me essentially no info this time :/ ).

**Comment by JakubDemocko** [comment] 2020-10-11 20:08
Are we sure, that the SetCapture function is mentioned to hide the cursor? Because this is how it looks, when I comment that function - notice, that cursor will be hidden:

![godot_after_commented](https://user-images.githubusercontent.com/22524145/95688989-3b5da380-0c0e-11eb-9675-f840d88c03d2.gif)

How can I see the body of this function? (ctrl + click gives me essentialy no info this time :/ ).

**Comment by KoBeWi** [comment] 2020-10-11 20:14
These two lines are probably responsible for hiding the mouse:
https://github.com/godotengine/godot/blob/bf37ab52b3ee4b14f235cfa1ea9e48c24c616bb3/scene/gui/spin_box.cpp#L154
and
https://github.com/godotengine/godot/blob/bf37ab52b3ee4b14f235cfa1ea9e48c24c616bb3/editor/editor_spin_slider.cpp#L104

**Comment by JakubDemocko** [comment] 2020-10-11 20:27
Ok, so I investigated it a bit, and this is the part responsible for hiding the cursor:

![_set_mouse_mode_impl](https://user-images.githubusercontent.com/22524145/95689367-8c6e9700-0c10-11eb-84cf-c2ce98ead041.png)

After commenting it, it stays visible in the same scenario - changing the value, as seen in the gif above. (sry if this isn't the best way of referencing to the code)

**Comment by JakubDemocko** [comment] 2020-10-11 20:30
Ok, so I investigated it a bit, and this is the part responsible for hiding the cursor:

https://github.com/godotengine/godot/blob/bf37ab52b3ee4b14f235cfa1ea9e48c24c616bb3/platform/windows/display_server_windows.cpp#L108-L112

After commenting it, it stays visible in the same scenario - changing the value, as seen in the gif above. (sry if this isn't the best way of referencing to the code)

**Comment by JakubDemocko** [comment] 2020-10-11 20:32
And this is the line I previously mentioned:

https://github.com/godotengine/godot/blob/bf37ab52b3ee4b14f235cfa1ea9e48c24c616bb3/platform/windows/display_server_windows.cpp#L100

**Comment by JakubDemocko** [comment] 2020-10-11 20:47
It would help me quiet a bit if I was able to look into that SetCapture function's body, to see what it does. @KoBeWi , can you help me with that? 🙂

**Comment by KoBeWi** [comment] 2020-10-11 21:06
SetCapture is irrelevant here. It's a Windows API method. As I said, the problem is in on higher level. Any control that captures cursor should release it when it (control) gets hidden. You can use `NOTIFICATION_VISIBILITY_CHANGED` and `Input::get_singleton()->set_mouse_mode(Input::MOUSE_MODE_VISIBLE)`.

**Comment by KoBeWi** [comment] 2021-02-26 00:05
So uh, seems like this is fixed in 94f78f2 by some other PR than the one linked. Closing as resolved.

**Comment by KoBeWi** [comment] 2021-02-26 00:09
;_;
Ok I didn't test properly, it's still bugged.

**Closed** 2021-03-06 23:06 UTC
Labels: bug, topic:editor
