### ISSUE TITLE
Vsync for monitor refresh rate of 59Hz seems to place game fps at 60 leading to stutters

### ISSUE THREAD

**Issue by ghost** [godotengine/godot#27504] opened 2019-03-29 03:23 UTC
**Godot version:**

master  805eec7 

**OS/device including version:**

Win7, Intel HD 4000

**Issue description:**

I have a monitor which turns out by default is at 59Hz Refresh rate with options to change it to 50, 59 and 60Hz in the Intel graphics control panel. I have always noticed there being a stutter about every 15 seconds or so, Printing the game fps shows the game running at 60 instead of 59. I find the Game fps actually does become 59 when I minimize the game while running.

I tried changing my Refresh Rate to 50 and the Game Fps shows 50 fps and I made sure I changed my physics fps to 50 too, else it leads to jitters, as stated [here](https://docs.godotengine.org/en/latest/tutorials/misc/jitter_stutter.html#jitter). Refresh Rate of 60Hz showed similar results with no issues.

| Refresh Rate  | Physics Fps | Game Fps | Stutter or Jitter |
| ------------- | ------------- | ------------- | ------------- |
| 59  | 60  | 60(59 when minimized) | stutter every 15 seconds |
| 59  | 59  | 60(59 when minimized) | semi random jitters about 15 seconds |
| 60  | 60  | 60 | no stutter |
| 50  | 50  | 50 | no stutter |

The first row was the default settings and the problem I had, **it makes me think if 59Hz is actually the default in many monitors and might be the cause for stutters that some users are reporting.**

So the issue is the Vsync is not matching the refresh rate of 59 and makes the game fps 60 instead, the game fps becomes 59 when the game is minimized

**Steps to reproduce:**
Try changing the refresh rate to 59 in your graphics control panel and run a game in godot with moving sprites. 
Try Alt+Tabbing and notice the game fps goes to 59.

**Minimal reproduction project:**

Any project with a moving sprite to look for stutters and jitters.
https://github.com/qarmin/Sea-of-Ground
@qarmin Hope its alright to link your repo, was running my tests with it.

**Comment by asheraryam** [comment] 2019-03-29 06:13
Can you try turning off V-Sync from the settings and see if that helps? It's under "Display -> Window"

**Comment by TryPixel** [comment] 2019-03-29 08:25
Actually the issue here is how Vsync in godot seems to handle certain refresh rates, turning it off would lead to uncapped fps based on the device performance and its not what we want here or in an usual release build of most games. It also leads to screen tearing.

**Comment by asheraryam** [comment] 2019-03-29 08:29
Oh I see. Well I can confirm that I have had the same issue recently this week, I couldn't solve it on my own so I just turned off V-Sync, but if it's an engine issue then fixing it would be quite nice.

**Comment by Calinou** [comment] 2019-03-29 08:36
Are you testing the project in fullscreen or windowed mode? On Windows, there's going to be [more jitter in windowed mode compared to fullscreen](http://docs.godotengine.org/en/latest/tutorials/misc/jitter_stutter.html).

**Comment by TryPixel** [comment] 2019-03-29 09:22
I am testing in fullscreen mode, I am aware that windowed mode has its own stuttering issue that isn't present in fullscreen mode. The stutters due to windowed mode is because of the opengl drivers in windows and not due to godot. The stutter I mentioned above is due to Vsync in godot and how it handled 59Hz in particular, even after changing to physics fps to 59 to match it, [which can be another source of stutter or jitter if there is a mismatch](http://docs.godotengine.org/en/latest/tutorials/misc/jitter_stutter.html#jitter).

**Comment by TryPixel** [comment] 2019-03-29 09:26
Do note that, there is no stutters when when I try a refresh rate of 50 or 60Hz and made sure that physics fps is set to match those refresh rate and also that I run it in fullscreen.

**Comment by eon-s** [comment] 2019-03-30 16:22
Duplicate of... all the other stutter-reated issues, this problem may need a tracker because all opened issues have links or tests that may be useful in the future or for anyone who may want to create a patch to their games, until Godot can finally have a solution in the engine...

**Comment by TryPixel** [comment] 2019-04-01 04:33
No I don't think its a duplicate, stutter had many causes, one of them being the driver issue and other is the physics and refresh rate mismatch and I believe this is but another source of it. While the ultimate problem is a stutter in this case, I am trying to emphasize how the vsync fails to handle 59Hz which then leads to a stutter. I agree a tracker would be nice to keep track of all the stutter issues.

**Comment by grevius5** [comment] 2019-04-03 13:26
I also have stutter in my game with vsync on (2D game, Linux, GTX1070) but I have also noticed that turning off vsync make my game run smoother (not always) but using yield(get_tree().create_timer(0.10), "timeout") is not working anymore...

**Comment by TryPixel** [comment] 2019-04-04 16:33
@grevius5  The stutter may or may not be due to this issue, you may want to refer to other stutter issues here on github for potential solutions but I would suggest you try some of the following:

-  Try running your game in fullscreen mode(project settings) 
- Check to see if your Monitors Refresh rate is 60Hz(or 144Hz) in your graphics control panel
- Make sure you your physics fps (in project settings) matches your monitor refresh rate when you have vsync on( turning off vsync as a solution is not advisable)
- Try GLES 2 
- See to it your thread model(in project settings) is set to single-safe

All of the above helped in my case, other solutions that were suggested, which I cant attest for, were:
- Unchecking Auto Switch to Remote Tree in project settings
- Try changing the power management setting in Nvidia control panel

**Comment by Calinou** [comment] 2021-05-06 18:09
Duplicate of https://github.com/godotengine/godot/issues/30791 (same cause). See also [Fixing jitter and stutter](https://docs.godotengine.org/en/stable/tutorials/misc/jitter_stutter.html) in the documentation.

**Closed by Calinou** 2021-05-06 18:09 UTC
Labels: bug, topic:rendering
