### ISSUE TITLE
AnimationPlayer: Ability to Edit Animation in Frames / Steps (in addition to Seconds / Time)

### ISSUE THREAD

**Issue by ghost** [godotengine/godot#12165] opened 2017-10-16 23:27 UTC
In Godot 2.14, animating using a AnimationPlayer and I am having a painfully slow experience. The issue is the timing in AnimationPlayer is done by seconds and not frames.

Can we add an interim fix that will show the frame number of wherever the timeline head is? Right now I am trying to make a simple NES era style animation and I find that I need to keep my calculator open and keep converting seconds to frames by taking the seconds and dividing it by 30 in order to get the frame number.

I'm thinking adding something like this should be simple, no?

I would also like to see previewing Animation by scrubbing the playhead in the timeline. 

Thoughts?

**Comment by fracteed** [comment] 2017-10-17 00:37
Funnily enough I asked the same thing yesterday and got a nice response from reduz. It would most likely be  3.1 feature. See #10752

**Comment by davidpgil** [comment] 2017-10-17 01:31
I'm tempted to try adding this myself. I have never worked on as advanced an app as Godot though :/

**Comment by davidpgil** [comment] 2017-11-01 08:00
I recommend the Godot team gain inspiration by how After Effects handles its keyframing system. Here is an example video but feel free to investigate others. I am not saying Godot should copy this system by the way. Just a suggestion to gain from the UI design/features: [After Effects Tutorial - Keyframes & Interpolation](https://www.youtube.com/watch?v=u5YxwHkjMHc)

**Comment by DualMatrix** [comment] 2018-09-30 17:51
Duplicate of #6149

**Closed** 2018-10-01 06:39 UTC
Labels: enhancement, topic:editor
