### ISSUE TITLE
GDscript  not support chinese variables

### ISSUE THREAD

**Issue by rjdgheart** [godotengine/godot#26917] opened 2019-03-11 14:19 UTC
English script ：var bullet=9
Chinese script ：var 子弹=9
But Chinese script report errors.
Different countries, different languages,but you can use your native language in GDscript,it is so cool.
Hope it will come true.

**Comment by bojidar-bg** [comment] 2019-03-11 14:34
Duplicate of #24785.

**Closed by bojidar-bg** 2019-03-11 14:34 UTC

**Comment by harrisyu** [comment] 2019-03-11 14:36
I personaly don't like this request as a Chinese.
Reason:
1. That's not a programer's thingking.
2. Switching IME when coding cause low efficiency.
3. Not good for reading.
4. Complex naming will slow GDscript down.
5. Will be a lots of side-effects.

**Comment by freekoy** [comment] 2020-05-15 15:42
You can do this.
var cc = {}
cc['子弹'] = 9
