### ISSUE TITLE
2D Physics interpolation not working with Y-Sort enabled

### ISSUE THREAD

**Issue by maidopi-usagi** [godotengine/godot#92982] opened 2024-06-10 15:33 UTC
### Tested versions

Tested in Godot v4.3.beta1

### System information

Windows 10.0.22631 - Vulkan (Mobile) - dedicated NVIDIA GeForce RTX 3090 (NVIDIA; 31.0.15.4592) - 13th Gen Intel(R) Core(TM) i7-13700F (24 Threads)

### Issue description

Just as title describes, with parent Node2D's y-sort enabled, a child node will not be smoothed when its y-sort is enabled.

https://github.com/godotengine/godot/assets/33864304/05cc327a-0831-4c84-82b6-a6ba66d86549

### Steps to reproduce

1. Open and Run MRP
2. The CharacterBody2D disables y-sort by default. use directional keys to move around and the movement is smooth.
3. Press SPACE key and move the CharacterBody2D  again, the movement will not be smoothed.

### Minimal reproduction project (MRP)

[2d_interp_mrp.zip](https://github.com/user-attachments/files/15775700/2d_interp_mrp.zip)

**Comment by Shalankwa** [comment] 2024-09-01 09:18
Any updates on when this may be merged? I've encountered the same issue on my current project.

**Comment by deventide** [comment] 2024-09-13 10:41
The seems to be present in 3.6 as well. Deactivating the sorting on a y-sort node made the interpolation work for a few seconds.

**Comment by SphyxDev** [comment] 2024-09-23 11:36
If anyone else needs a solution until this issue gets resolved, [lawnjelly's smoothing addon](https://github.com/lawnjelly/smoothing-addon/tree/4.x) thankfully doesn't have the issue with y-sorting.

**Closed** 2024-10-14 19:17 UTC
Labels: bug, topic:rendering, topic:physics, topic:2d

**Comment by elvisish** [comment] 2025-04-08 22:11
> The seems to be present in 3.6 as well. Deactivating the sorting on a y-sort node made the interpolation work.

Was this fixed? I'm finishing up with 3.3 and was thinking of trying 3.6 soon, but I use a lot of y-sort and I'm concerned it won't work properly.

**Comment by kleonc** [comment] 2025-04-09 12:20
> > The seems to be present in 3.6 as well. Deactivating the sorting on a y-sort node made the interpolation work.
> 
> Was this fixed? I'm finishing up with 3.3 and was thinking of trying 3.6 soon, but I use a lot of y-sort and I'm concerned it won't work properly.

#93025 fixed it only in 4.x (merged in 4.4.dev4), whether the issue occurs in 3.x no idea. Based on https://github.com/godotengine/godot/pull/93025#issuecomment-2160377571 @lawnjelly couldn't reproduce it in 3.x back then. 🤔

I'd say if any of you can reproduce it in 3.x then please open a separate issue with all the details provided there (including MRP for 3.x).

**Comment by lawnjelly** [comment] 2025-04-09 12:54
> The seems to be present in 3.6 as well. Deactivating the sorting on a y-sort node made the interpolation work.

I hadn't seen this post.

As @kleonc says above, this would need it's own issue and most importantly an MRP if it occurs in 3.x too (I couldn't seem to reproduce so maybe it needed some conditions I missed at the time, 4.x may work differently for y sort). In most cases we can only fix bugs that we can reproduce.
