### ISSUE TITLE
Auto save when focus lost is enabled can lock the editor

### ISSUE THREAD

**Issue by cphillips83** [godotengine/godot#70632] opened 2022-12-27 14:31 UTC
### Godot version

4.0.dev.10

### System information

Windows 11

### Issue description

If you enable the auto save feature when you leave focus of the editor (for example when using VSCode as your debugger), if you hit escape on that save dialog the editor will become unresponsive. It still renders properly and seems to be executing as I still see some events like the editor gaining and losing focus in the console window, but it seems like the ditor input capture logic not working.

### Steps to reproduce

1. Enable auto save when editor loses focus.
2. Create new scene
3. Alt-tab and hit escape on the save dialog that pops up
4. Note that the editor is no longer interactable.

### Minimal reproduction project

Not needed

**Comment by cphillips83** [comment] 2022-12-27 14:42
Note: Had this happen even after saving the scene this time. When this triggers the console log fills with these errors...

```
ERROR: Signal 'focus_entered' is already connected to given callable 'AcceptDialog::_parent_focused' in that object.
   at: (core/object/object.cpp:1270)
ERROR: Can't make active a Viewport that is already active.
   at: (servers/rendering/renderer_viewport.cpp:868)
ERROR: Signal 'focus_entered' is already connected to given callable 'AcceptDialog::_parent_focused' in that object.
   at: (core/object/object.cpp:1270)
ERROR: Can't make active a Viewport that is already active.
   at: (servers/rendering/renderer_viewport.cpp:868)
ERROR: Transient parent has another exclusive child.
ERROR: Condition "!windows.has(p_window)" is true. Returning: Point2i()
   at: window_get_position (platform/windows/display_server_windows.cpp:896)
``

**Comment by Calinou** [comment] 2022-12-29 19:52
Duplicate of https://github.com/godotengine/godot/issues/61875.

**Closed by Calinou** 2022-12-29 19:52 UTC
