### ISSUE TITLE
TSCN/TRES subresource random reordering

### ISSUE THREAD

**Issue by Zadck** [godotengine/godot#18283] opened 2018-04-18 21:54 UTC
I am still having the exact same issue as described in the now-closed topic https://github.com/godotengine/godot/issues/5889 as of Godot 3.0.2. This has not been resolved and was "assumed fixed" but is still present, and still seems to occur randomly following the same steps explained in that issue.

Original issue description:

> Loading a tileset source TSCN and saving it, and/or exporting/saving again an existing TRES tileset resource generates random redistribution of the subresources' IDs, leading to unnecessary diffs.

It is easy to see as described in that discussion or when changing even just the sprite on a node in a tileset and then saving it as new or merging it--it causes scenes to have tiles in the wrong places and makes swapping-out art impossible without manually reconstructing the entire scene. It effects collision objects, sprites, and more, and does not occur only when re-building the tileset. As with the original issue, this is not consistent and "If it doesn't, close the editor...it might take several attempts to happen."

**Comment by Calinou** [comment] 2020-06-07 17:44
Duplicate of #22226, which has more information about the issue at hand. See also #20994.

**Closed by Calinou** 2020-06-07 17:44 UTC
Labels: bug, topic:core
