### ISSUE TITLE
TextEdit in plugin with wrap and `fit_content_height` enabled can result in crash

### ISSUE THREAD

**Issue by Jowan-Spooner** [godotengine/godot#80546] opened 2023-08-12 13:18 UTC
### Godot version

4.2.dev3, 4.1.1-stable

### System information

Windows 10, (probably macOS 13.4.1 as well)

### Issue description

When used in a plugin, a TextEdit that has fit_content_height and wrap mode enabled but only limited space to extend to will crash godot once the text get's too long. 

I discovered this bug while fixing a bug for dialogic: https://github.com/coppolaemilio/dialogic/issues/1675
The user that discovered it was using mac OS 13.4.1 and godot 4.1.1 so I assume that this issue is present there too.

This issue seemed similar, but has to do with the RichTextLabel and is apparently fixed: [ RichTextLabel freezes Godot 4.1-rc2 on Fit Content #78932 ](https://github.com/godotengine/godot/issues/78932)

I was not able to reproduce the problem in running games, only in plugins!
![2023-08-12-15-16-36](https://github.com/godotengine/godot/assets/42868150/77fbb873-ed89-43e7-8521-739ac7496cd1)

### Steps to reproduce

- create a super simple plugin with code like this:
```gdscript
@tool
extends EditorPlugin

func _enter_tree():
	if get_editor_interface().is_plugin_enabled('test'):
		_enable_plugin()

func _enable_plugin():
	get_editor_interface().get_editor_main_screen().add_child(preload("res://Test.tscn").instantiate())

func _get_plugin_name():
	return "Test"

func _has_main_screen():
	return true
```

- setup the "res://Test.tscn" scene like this:
     - Control 
     ---- Scroll Container (make it relatively small, so you need less text to enter for the crash)
     -------- Vbox (expand horizontal & vertical)
     ----------- TextEdit (fit_content_height = true; wrap_mode = Boundary)
- enable the plugin
- select the TextEdit in the new editor tab and start spamming any letters.
 -> once the text edit fills the whole Scroll Container godot crashes

### Minimal reproduction project

[TestTextEditCrashBug.zip](https://github.com/godotengine/godot/files/12327373/TestTextEditCrashBug.zip) (has been created following the steps above)

- Open project
- Switch to the "Test" tab
- select the Text edit
- start spamming any letter until the field is filled.
-> crash

**Comment by Rindbee** [comment] 2023-08-15 07:47
It seems to be stuck in an infinite loop, similar to #75713.

**Comment by exelia-antonov** [comment] 2023-09-01 19:57
I can confirm experiencing this on macOS as well, latest version on an M2 Macbook 24GB. What makes this significantly worse is a plugin automatically loading data and building UI at start, once hitting this limit, will create continuous crashes requiring the user to edit data outside of Godot to remove the offending data load

**Comment by kitbdev** [comment] 2024-04-25 20:17
Cannot reproduce in v4.2.1.stable.official [b09f793f5] or master (v4.3.dev.custom_build [11d376813])
- may have been fixed by https://github.com/godotengine/godot/pull/83286

**Closed** 2024-04-25 20:56 UTC
Labels: bug, topic:editor, topic:plugin, crash, topic:gui
