### ISSUE TITLE
DRAFT: When selecting Checkbox, it makes the UI tools too long on a 1080p-ish screen

### ISSUE THREAD

**Issue by duchainer** [godotengine/godot#61957] opened 2022-06-12 01:32 UTC
### Godot version

4.0 dev (0810b0d)

### System information

MacBook Air M1 

### Issue description

The UI gets too long when selecting a checkbox, it gets "out of the screen" too long on my display:

<img width="1552" alt="Screen Shot 2022-06-11 at 9 22 39 PM" src="https://user-images.githubusercontent.com/11084784/173210341-9ecb3633-9c62-4631-a256-3a7abfa26146.png">

I'll get a more detailed report next week, and check if it affects all the UI that have Fonts to take into account (like other Buttons, etc)

### Steps to reproduce

1. Create a new Scene
2. Add a checkbox
3. Select it
4. See that the MainScreen window for 2d is now taking more spaces on the right than it used to, instead of:
  a. Add some arrows like with the Scene tabs
  b. Overflowing under as a second row of options/tools 

### Minimal reproduction project

I'll upload one Monday, sorry for the wait. Just wanted not to forget this issue when I just encountered it.

Also I'll make one for the latest commits instead of a 2-weekish old commit like I currently have ^^""

**Comment by akien-mga** [comment] 2022-06-12 08:11
Duplicate of https://github.com/godotengine/godot/issues/58052

**Closed by akien-mga** 2022-06-12 08:11 UTC
Labels: bug, topic:gui
