### ISSUE TITLE
PhysicalBoneEditor leaks on exit

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#19482] opened 2018-06-10 03:07 UTC
Godot 3 master a18fe067736c2136e451ab183b53d228f5568c0d
Windows 10 64 bits

```
WARNING: ObjectDB::cleanup: ObjectDB Instances still exist!
     At: core\object.cpp:1986
Leaked Instance: PhysicalBoneEditor:16450
Orphan StringName: PhysicalBoneEditor
StringName: 1 unclaimed string names at exit.
```

**Comment by AndreaCatania** [comment] 2018-06-10 07:18
Hi Zylann, Can you please send a sample project?

**Comment by Zylann** [comment] 2018-06-10 13:58
Just open the editor and close it.

**Comment by akien-mga** [comment] 2018-09-14 21:53
Closing as duplicate of #22086 which is slightly more detailed.

**Closed by akien-mga** 2018-09-14 21:53 UTC
Labels: bug, topic:editor, topic:physics
