### ISSUE TITLE
Font is rendered pixalated in editor due to font oversampling not being effective when zooming

### ISSUE THREAD

**Issue by letsgamedev** [godotengine/godot#33968] opened 2019-11-28 15:10 UTC
**Godot version:**
3.2.beta2 and all before that :)

**OS/device including version:**
Windows and MacOS

**Issue description:**
Texts in the editor are rendered super pixelated but in-game normal.
I am making a game with a resolution of 320*90.
So I think, the font is rendered good if the zoom is set to 100% but is not rerendered if I zoom closer in. This makes the positioning of elements very time-consuming.

**Steps to reproduce:**
Add a Label and zoom in.

The upper image is from editor, the lower from in-game.

![rect837](https://user-images.githubusercontent.com/4989757/69816826-796df680-11f9-11ea-8401-be97653aeafe.png)

**Comment by Calinou** [comment] 2019-11-28 15:47
The DyanmicFont oversampling factor is global, which means it can't be set on a per-font basis. We'd need this to be able to oversample the font when zooming in and out.

As a workaround, you can increase your game's base resolution. If you need to run it at a lower resolution for testing purposes, you can change **Test Width** and **Test Height** in the Project Settings.

**Comment by girng** [comment] 2019-11-29 19:33
> This makes the positioning of elements very time-consuming.

No it doesn't

**Comment by akien-mga** [comment] 2019-11-29 19:37
@girng Please only comment if you have something constructive to say.

**Comment by pwnorbitals** [comment] 2020-10-01 05:03
> The DynamicFont oversampling factor is global, which means it can't be set on a per-font basis. 

Is this still the case today ? 

> We'd need this to be able to oversample the font when zooming in and out.

Is this implemented / implementable ? I wouldn’t really know where to start

**Comment by Calinou** [comment] 2020-10-01 12:47
> Is this still the case today ?

Yes.

> Is this implemented / implementable ? I wouldn’t really know where to start

This will require per-font oversampling factors to be implementable.

**Comment by bruvzg** [comment] 2021-03-02 14:10
> With the upcoming addition of MSDF fonts, this issue may be solved as distance field fonts can be rendered at any scale without loss of quality

And, as a side effect of MSDF implementation, oversampling can be overridden on the font basis as well.

**Comment by Calinou** [comment] 2021-04-11 20:31
Note that this could argued to be done by design, since you generally want your text to always be readable at the base resolution. If you want text to look crisper in the editor, it means you should probably be working with a higher base resolution.

**Comment by Calinou** [comment] 2021-08-30 11:39
MSDF fonts were implemented in https://github.com/godotengine/godot/pull/51908, closing.

**Closed by Calinou** 2021-08-30 11:39 UTC
Labels: discussion, topic:rendering, topic:editor, documentation, topic:gui
