### ISSUE TITLE
Re-importing assets crashes

### ISSUE THREAD

**Issue by walidsantos** [godotengine/godot#72819] opened 2023-02-07 02:23 UTC
### Godot version

4.0.dev beta 17

### System information

Windows 10

### Issue description

![image](https://user-images.githubusercontent.com/53328867/217131270-1f82f6e5-a405-4698-9c88-ebac3c8239b1.png)

![image](https://user-images.githubusercontent.com/53328867/217131972-2db1cabe-04ea-4b7b-ac6d-6d13a1ccb54b.png)

it's been a minute seens i imported my image(png)
i've been occuring this problem everytime importing an image
i have to restart the editor to fix this problem it's really annoying!

### Steps to reproduce

![image](https://user-images.githubusercontent.com/53328867/217131760-57b1f684-5000-4a80-9230-815121e33998.png)

### Minimal reproduction project

N\A

**Comment by bluefeversoft** [comment] 2023-02-07 16:55
Just confirming same for me on Windows 10.

**Comment by sholesy** [comment] 2023-02-07 18:21
This is also happening on Windows 11

# Version
I've tested both versions of Godot 4 Beta 17

# Standard
![image](https://user-images.githubusercontent.com/97705927/217330812-2c4f238a-c35a-46e8-88ab-4e6e92f83383.png)

# Mono
![image](https://user-images.githubusercontent.com/97705927/217331598-4d72fcd6-fbbf-43cd-8f97-8ac5e69b868e.png)

**Comment by sholesy** [comment] 2023-02-07 18:26
This is also happening on windows 11

![image](https://user-images.githubusercontent.com/97705927/217332929-7f83576b-b9e5-4452-a876-43868b2f23c2.png)

**Comment by maddsua** [comment] 2023-02-07 22:54
\+ Sometimes that happens to me too. The interface itself isn't very responsive through the importing process regardless if it to fail or not

**Comment by lyuma** [comment] 2023-02-09 09:06
Has anyone reproduced this on RC1?

**Comment by edisonlee55** [comment] 2023-02-09 11:18
I can still reproduce this on RC1 with image files (Both `.png` and `.jpg`).

Both small (128x128px) and huge (4096x4096px) image textures crash the editor when it's being imported the first time.

After the .import file is created, even deleting the `.godot` folder and reopening the project won't cause crash the editor on my side.

Below are 4 fully white images I used to reproduce the crash (you can also re-create one in any kind of image editing software), two are png, another two are jpg. With 128x128 and 4096x4096 sizes.
[white-images.zip](https://github.com/godotengine/godot/files/10696470/white-images.zip)

Creating an entirely new project and importing the images can reproduce this issue.

**Comment by YuriSizov** [comment] 2023-02-11 21:21
Duplicate of https://github.com/godotengine/godot/issues/53871.

**Closed by YuriSizov** 2023-02-11 21:21 UTC
Labels: bug, topic:import, crash
