### ISSUE TITLE
Control+F "whole words" option very slow after upgrading from 3.1 to 3.2

### ISSUE THREAD

**Issue by squished-01** [godotengine/godot#37600] opened 2020-04-05 04:01 UTC
**Godot version:**
3.2.1-stable.official

**OS/device including version:**
Desktop with 64-bit Windows 7 Home Premium SP 1
Intel core i7 CPU 950 @ 3.68 GHz
12 GB Ram 

**Issue description:**
The godot engine hangs, and the screen goes white when I click it.  No output in the console window.  If I wait a couple minutes it eventually unfreezes.  This was NOT an issue in godot 3.1.2.  It only occurs with godot 3.2.1 on the same computer on the exact same large files.

**Steps to reproduce:**
Ctrl+F in a gdscript editor window with 4000 or more lines of code.  Previous versions of godot could easily handle files this size.

**Comment by Anutrix** [comment] 2020-04-05 09:05
Probably a duplicate of #33473.

**Comment by Calinou** [comment] 2020-04-05 12:31
Duplicate of #33473.

**Closed by Calinou** 2020-04-05 12:31 UTC
Labels: bug, confirmed, regression, topic:editor
