### ISSUE TITLE
Class variable reported as unused when used in propagate_call

### ISSUE THREAD

**Issue by rcorre** [godotengine/godot#33943] opened 2019-11-27 15:00 UTC
**Godot version:**

3.1.1.stable.custom_build

**OS/device including version:**

Linux 5.3.11-arch1-1 

**Steps to reproduce:**

```
extends Spatial

var team := "red"

func _ready():
	propagate_call("set_team", [team])
```

Produces the warning:

```
W 0:00:00:0234   The class variable 'team' is declared but never used in the script.
  <Source>       Spatial.gd:3
```

Moving the variable to a local scope supresses the error:

```
extends Spatial

func _ready():
    var team := "red"
    propagate_call("set_team", [team])
```

**Minimal reproduction project:**

**Comment by Zylann** [comment] 2019-11-27 18:27
Is that extending to any kind of "Referencing a function through its string name"?

**Comment by bojidar-bg** [comment] 2019-11-27 19:03
Does it happen when passing `[team]` to any other function?

**Comment by rcorre** [comment] 2019-11-27 22:13
```
extends Spatial

var a := "a"
var b := "b"
var c := "c"
var d := "d"

func _ready():
	propagate_call("fun", [a]) # warning
	call("fun", b) # ok
	fun(c) # ok
	fun2([d]) # warning

func fun(s: String):
	print(s)

func fun2(a: Array):
	print(a)
```

So it seems that it is related to arrays, not to name-based function access.

**Comment by rcorre** [comment] 2019-11-27 22:13
The result is the same without type hints

**Comment by bojidar-bg** [comment] 2019-11-27 23:20
Hm, I cannot reproduce on 3.2 with the example script. (It raises just one warning related to `a` being reused as a parameter name.)

I suppose that this was fixed as a side effect of #29433.

And, checking other issues related to that PR, this issue is a duplicate of #30418.

**Closed by bojidar-bg** 2019-11-27 23:20 UTC
Labels: bug, topic:gdscript

**Comment by rcorre** [comment] 2019-11-28 00:12
Sounds good, but I think you duped the wrong issue, #30418 seems completely unrelated.

**Comment by bojidar-bg** [comment] 2019-11-28 09:51
Hm, that's strange. I meant #30143, but I feel GitHub somehow auto-"corrected" it into 3014**8** instead
