### ISSUE TITLE
Code hinting is getting overlapped by the side panels

### ISSUE THREAD

**Issue by meem40** [godotengine/godot#6282] opened 2016-08-25 18:50 UTC
When typing long line of code, code hinting tool tip is getting overlapped by side panel. 
![2016-08-26_0-48-18](https://cloud.githubusercontent.com/assets/10063554/17981823/1a69ec06-6b27-11e6-82d5-5a437dce4212.jpg)

**Comment by neikeq** [comment] 2016-08-25 18:53
Closing as a duplicate of #1257

**Closed by neikeq** 2016-08-25 18:53 UTC
