### ISSUE TITLE
2 arrays only work as expected if instantiated

### ISSUE THREAD

**Issue by sharp-94** [godotengine/godot#29168] opened 2019-05-25 10:44 UTC
Godot version:
Godot_v3.1.1-stable_win64

OS/device including version:
Windows 10 Home

Issue description:

If i have two arrays as written as below. And if add something to them separately, they are both adding it.

```
var a : Array
var b : Array

func _ready():
	a.append(true)
	b.append(false)
	
	print("a=", a)
	print("b=", b)
```

It outputs: 
```
a=[True, False]
b=[True, False]
```

I found out that it works when I instantiate the arrays as empty:

```
var a : Array = []
var b : Array = []

func _ready():
	
	a.append(true)
	b.append(false)
	
	print("a=", a)
	print("b=", b)
```

The output then is what you normaly would expect:
```
a=[True]
b=[False]
```

Is this on purpose?
Are they both using some kind of static array if i don't instantiate them?

**Comment by akien-mga** [comment] 2019-05-25 11:21
Duplicate of #24134, fixed in the master branch.

**Closed by akien-mga** 2019-05-25 11:21 UTC
