### ISSUE TITLE
Godot4 | Duplicated 'Code Complete Delay' parameter on Editor Settings -> Text Editor -> Behavior 

### ISSUE THREAD

**Issue by zMenta** [godotengine/godot#72117] opened 2023-01-26 13:15 UTC
### Godot version

4.0 beta 15

### System information

EndeavourOS

### Issue description

The option **Code Complete Delay** that is found on the menu **Editor Settings -> Text Editor -> Completion.**

Is also found on Editor Settings -> Text Editor -> Behavior.

![image](https://user-images.githubusercontent.com/70714721/214843553-69ef8a84-f4d3-40ac-9da0-8ed69c21f42b.png)

The value on the Behavior section can also be set to a negative value. 
It also don´t have the return to default option button (circular arrow) on it.

![image](https://user-images.githubusercontent.com/70714721/214844471-8f5e8312-8213-46fc-a894-04ba70bdf6a4.png)

### Steps to reproduce

Open any project, go to Editor settings by clicking on the top left options in the editor. Scroll the Text Editor category and select Behavior sub-category, the option appears as the first one.

### Minimal reproduction project

Any project.

**Comment by Calinou** [comment] 2023-01-26 14:20
Duplicate of https://github.com/godotengine/godot-proposals/issues/3526.

You're seeing an outdated setting from a previous Godot version, as the setting is only defined once in the codebase:

![image](https://user-images.githubusercontent.com/180032/214859327-ecfe3d7a-830a-4a84-a852-90a2cbfbdf42.png)

**Closed by Calinou** 2023-01-26 14:20 UTC

**Comment by zMenta** [comment] 2023-01-26 19:12
Thanks for the clarification!
