### ISSUE TITLE
Saved state of scene with VBoxContainer "oscillates"

### ISSUE THREAD

**Issue by vmedea** [godotengine/godot#70115] opened 2022-12-15 18:17 UTC
### Godot version

4.0.beta8

### System information

Linux, Vulkan

### Issue description

With git I noticed that the same scene is saved differently sometimes, even though I've made no changes to it. This is a small annoyance when using source control, but not terribly serious.

It concerns a simple scene consisting of a CanvasLayer with a VBoxLayout with Panels inside, instanced from another scene file.

Sometimes they're saved as:
```
[node name="Slot1" parent="Inventory" instance=ExtResource("5_6q3jk")]
layout_mode = 2
```
and the other time as:
```
[node name="Slot1" parent="Inventory" instance=ExtResource("5_6q3jk")]
offset_right = 32.0
offset_bottom = 32.0
```

My first thought was that this is a side effect of the Panels being instantiated. However, after making them local, the problem persisted.

### Steps to reproduce

- Open the minimal reproduction project in the editor
- In the console, type `git diff`. There should be no output:
```
$ git diff
```
- Open `scenes/dummy.scene` and `scenes/hud.scene` in the editor.
- Make sure `dummy.scene` is currently open (**this is important**). Run the project with F5. It wil re-save.
- In the console, again type `git diff`. The output will have coordinates in it instead of `layout_mode`:
```
$ git diff
index 0fdc331a7aa15e2dbe791c3d9d8d89a136290c20..d66908370131f6ee36166a123eaf7c63693374bf 100644
--- a/scenes/hud.tscn
+++ b/scenes/hud.tscn
@@ -11,25 +11,40 @@ offset_right = 624.0
 offset_bottom = 371.0
 
 [node name="Slot1" parent="Inventory" instance=ExtResource("5_6q3jk")]
-layout_mode = 2
+offset_right = 32.0
+offset_bottom = 32.0
...
```
- Stop the "game".
- Go to `scenes/hud.scene` tab in the editor.
- Type Ctrl-S to save directly.
- In the console, again type `git diff`. There will be no output! We're back at the original state.

### Minimal reproduction project

[repro5.tar.gz](https://github.com/godotengine/godot/files/10239548/repro5.tar.gz)

**Comment by KoBeWi** [comment] 2022-12-15 18:45
Duplicate of #67095

**Closed by KoBeWi** 2022-12-15 18:45 UTC
