### ISSUE TITLE
Vulkan: Volumetric fog looks incorrect for SpotLight3D with shadow enabled, depending on the camera angle

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot#57722] opened 2022-02-06 19:19 UTC
### Godot version

4.0.alpha (9d1626b4d)

### System information

Fedora 34, GeForce GTX 1080 (NVIDIA 495.46)

### Issue description

Volumetric fog looks incorrect for SpotLight3D with shadow enabled, depending on the camera angle. This does not affect OmniLight3D, which looks correct _after reloading the scene_ if shadows were enabled for the first time after enabling volumetric fog. (That issue should be reported separately, but I haven't been able to reproduce it consistently yet.)

When reaching a "broken" camera angle, very little fog albedo will be lit (if any). It flickers on and off depending on the camera angle and position.

*Left (green): OmniLight3D with shadow enabled, right (red): SpotLight3D with shadow enabled*

### Shadows disabled

![2022-02-06_20 13 03](https://user-images.githubusercontent.com/180032/152697671-c4df3072-133e-4d4c-8c4f-efdc2d690de8.png)

### Shadows enabled with working camera angle

![2022-02-06_20 13 28](https://user-images.githubusercontent.com/180032/152697672-35dc490e-515b-44c3-a067-e0f9fbd9a54c.png)

### Shadows enabled with broken camera angle

![2022-02-06_20 14 26](https://user-images.githubusercontent.com/180032/152697685-cf4ddd2b-7c1a-4c32-b3ec-47bf3bffd166.png)

See also this video:

https://user-images.githubusercontent.com/180032/152697632-e21359c1-d77a-467b-9b9a-8ec346745f65.mp4

### Steps to reproduce

- Place some MeshInstances for the light to cast a shadow.
- Enable **Shadow** in the SpotLight3D.
- Enable **Volumetric Fog** in the Environment resource.

### Minimal reproduction project

[test_volumetric_fog_point_shadows.zip](https://github.com/godotengine/godot/files/8011043/test_volumetric_fog_point_shadows.zip)

**Comment by Calinou** [comment] 2022-09-01 16:45
As a workaround, use a [FogVolume with a Cone shape](https://github.com/godotengine/godot/pull/61243) parented to the SpotLight3D node. It won't be able to have shadows though (but the light itself will still be able to cast shadows).

**Comment by SilentPenguin** [comment] 2022-11-10 19:46
I've noticed that the range of a spotlight also influences interaction with fog volumes as well as viewing angle. For a spotlight which visibly interacts with fog, extending the range reduces the visible effect of this issue, including making the artifacting easier to see at range.

![image](https://user-images.githubusercontent.com/186290/201188541-459e4ba2-2427-4a85-b86c-1978bc9519c9.png)
![image](https://user-images.githubusercontent.com/186290/201188595-b0e61ef3-f9ca-4656-9efc-f650ff343907.png)

The above pictures show these effects with a spotlight with a range of 2k, from two different viewing angles.

It's worth noting that even with shadows enabled, the projected effect doesn't interact with cast shadows at all.
Below is setup illistrating an omni light top and a spotlight bottom, both with range 30 and shadows enabled.

![image](https://user-images.githubusercontent.com/186290/201190934-5dbb6615-35cc-460e-9148-7ab09e54634f.png)

Hopefully these observations make it easier to locate a root cause.

**Comment by Saul2022** [comment] 2023-01-24 17:10
Yea i can reproduce this issue in beta 14 

![Uploading Captura de pantalla 2023-01-24 180746.png…]()


not sure if this pr fixes it  https://github.com/godotengine/godot/pull/71832 f

**Comment by clayjohn** [comment] 2023-01-24 18:53
> not sure if this pr fixes it #71832 

Unfortunately #71832 does not fix this issue

**Comment by akien-mga** [comment] 2023-03-02 10:34
Fixed by #73919.

**Closed by akien-mga** 2023-03-02 10:34 UTC
Labels: bug, topic:rendering, confirmed, topic:3d
