### ISSUE TITLE
_exit_tree is called when switching scenes in tool mode

### ISSUE THREAD

**Issue by blaze-the-star** [godotengine/godot#33806] opened 2019-11-21 23:06 UTC
**Godot version:**
3.2

**OS/device including version:**
PopOs 19.04

**Issue description:**
Switching scenes in the Godot Editor causes _exit_tree() to execute in tool scripts. This is very bizarre considering the same doesn't happen when closing a scene. I use _exit_tree() to clear up my plugin's meta data* whenever my plugin node is moved or deleted and _exit_tree being called whenever scenes are switched is very bad because it ends up resetting that meta data when it was still needed. It would be very helpful if _exit_tree is not called when switching tabs or if there were some way to tell the difference between the node being moved, the node being deleted, and the scene being switched.

*My plugin node needs to set meta data in a node higher in the tree and the meta data needs to be removed whenever my plugin node is moved or deleted. 

**Steps to reproduce:**
1. Add a tool script to a node.
2. In that script, override the _exit_tree function.
3. Add a print statement (or any other means of telling when _exit_tree is called) to _exit_tree.
4. Switch to a different scene and check the Output terminal for if the print statement was called.

**Minimal reproduction project:**
[Exit Tree Error.zip](https://github.com/godotengine/godot/files/3877154/Exit.Tree.Error.zip)

**Comment by Hubber116sx** [comment] 2019-11-21 23:11
On a side note, my plugin node needs to add meta data to a node higher in the tree because of this issue #12990.

**Comment by Zylann** [comment] 2019-11-22 01:33
This is not a bug. I think switching causes that because Godot internally removes your scene from the tree and then adds the other one. And indeed `_exit_tree` may also be called if you reparent your node, not just when switching scenes. Closing a scene not calling `_exit_tree` is quite weird though.

**Comment by Hubber116sx** [comment] 2019-11-22 02:47
I'll try the notification thing, I haven't really used them before because they seemed to be the same as signals. If it doesn't end up working I have written the two paragraphs below explaining what my code does.

Do you know Little Big Planet's create mode?* I'm essentially recreating the logic engine from that game to make level design easier. If you had a button scene and you wanted the button to work with this system you would add an IOHub as a child of that button scene, then set up an Output node as a child of that IOHub that activates whenever the button is pressed. You would then be able to connect the Output of that button to the Input of something that you set up earlier, like a door, and whenever the button's Output is activated the Input would be triggered and run a function that does something, like open the door.

*If you aren't familiar with Little Big Planet this short video demonstrates the idea: https://www.youtube.com/watch?v=0o9ADwmJwJQ

The problem is getting the engine to save the state of when an Output is connected to an Input. Variables inside an instanced scene aren't saved when changed so I have to store the information somewhere else. The best answer I could come up with is to save that information to the parent of the button as meta data. It works pretty well, except for when you delete or move the button in the tree. The information would stay in the button's old parent cluttering the scene file with data that isn't being used. The user of the engine can't even remove the clutter manually because meta data is not shown to them. To fix this I decided to override _exit_tree() in the Output node to delete the meta data from the button's old parent, but _exit_tree() is also called whenever you switch scenes so it ends up deleting all the connections you make between Inputs and Outputs.

**Comment by Hubber116sx** [comment] 2019-11-22 03:40
Notifications wouldn't work because the notifications that would be relevant to Outputs or even to the IOHub would be received by the IOHub's parent (which would be the button from my previous example) with no way for the IOHub or Output to receive that information without manually adding code to the button that gives it to them. I would prefer if I could get the IOHub or Output to handle everything without having to manually write new code for every case they would be used in.

**Comment by takaturre** [comment] 2020-01-19 11:33
I hope this stays as it is, as it's very useful for some tool scripts - although it can also be quite annoying for others. It's anyway very logical in that the nodes do exit and enter the tree.

**Comment by KoBeWi** [comment] 2020-12-16 01:05
Closing, because this isn't a bug. Also

> This is very bizarre considering the same doesn't happen when closing a scene.

seems to be no longer true.

**Closed by KoBeWi** 2020-12-16 01:05 UTC
Labels: bug, topic:editor, topic:plugin
