### ISSUE TITLE
Can't rename files just changing case in FileSystem panel

### ISSUE THREAD

**Issue by lostminds** [godotengine/godot#68245] opened 2022-11-04 09:22 UTC
### Godot version

4.0.beta3

### System information

macOS 12.6.1

### Issue description

If you try to rename a project resource file using context menu rename in the FileSystem panel browser Godot checks if the new proposed filename is available. However, it seems that this check is case insensitive (possibly for good reason). However, this has the specific problem that you can't change case of filenames. For example renaming "World.tscn" to "world.tscn" or the other way around. If you do you simply get an error that "A file or folder with this name already exists.", which is technically true, but shouldn't be blocking since this is the file you're renaming. This can be annoying since a lot of developers are particular about what case they want to suite their conventions. 

### Steps to reproduce

- Select a file in your project FileSystem panel list
- Select Rename from the context menu (or just hit enter) to bring up the rename dialogue
- Rename the file to the same name but changing the case (ie: "Name.ext" to "name.ext")
- Get warning (should be error since it failed?) instead of renaming the file

### Minimal reproduction project

Since this is a basic interface thing, it should be reproducible in any project and not related to project settings. At least on macOS if it's file system-related.

**Comment by Zireael07** [comment] 2022-11-04 09:56
Is your macos case sensitive or case insentitive?

**Comment by lostminds** [comment] 2022-11-04 10:07
The drive is case insensitive it seems, so maybe that is probably the issue if godot assumes the drive is case sensitive. Good catch. It should still be possible to rename files though.

**Comment by akien-mga** [comment] 2022-11-04 10:12
Duplicate of #19592

**Closed by akien-mga** 2022-11-04 10:12 UTC
