### ISSUE TITLE
Button not working when project exported to HTML5

### ISSUE THREAD

**Issue by NoohAlavi** [godotengine/godot#37590] opened 2020-04-04 19:42 UTC
**Godot Version**: 3.2 Mono Stable

**Device/OS:** Windows 10 Probook. Exported to Chrome Browser.

**Description:** Button Node with simple C# code to change scenes works in the editor, but when I export to HTML5, the button does not work. Instead, it gives this error:

![image](https://user-images.githubusercontent.com/59208101/78459882-41386200-768a-11ea-8164-800dd483aa0e.png)

**Steps to reproduce:** Make a Godot mono project. The main scene should have a button that changes scenes. Export this project. to HTML5.

Here's my project: https://github.com/NoohAlavi/bullet-hell-2

Edit 1: Just tried Windows Dekstop build.... it works... HTML5 doesn't.
Edit 2: I accidentally wrote Chrome OS before; meant chrome browser.
Edit 3: Updated Steps to reproduce and fixed Godot Version.

**Comment by Calinou** [comment] 2020-04-04 20:15
@NoohAlavi Please upload a minimal reproduction project to make this easier to troubleshoot. (It seems you didn't include a download link in OP.)

**Comment by NoohAlavi** [comment] 2020-04-04 20:18
@Calinou Should I put the github link to the project?

**Comment by Calinou** [comment] 2020-04-04 23:20
@NoohAlavi Yes, that works fine :slightly_smiling_face:

**Comment by machineman357** [comment] 2020-05-30 21:48
CANNOT HANDLE COOKIE

**Comment by NoohAlavi** [comment] 2020-05-30 23:41
@Calinou hey, just wanted to tell you that I experienced this same issue again, in a different project: html5 export, godot 3.2 mono, C#

**Comment by neikeq** [comment] 2020-12-14 18:57
> CANNOT HANDLE COOKIE F

Judging by this warning I'm closing this issue as a duplicate of #36858

**Closed by neikeq** 2020-12-14 18:57 UTC
Labels: bug, platform:html5, topic:mono, topic:porting
