### ISSUE TITLE
Visibility Notifier in 3D scenes spams errors when there's signals and no camera

### ISSUE THREAD

**Issue by Ace-Dragon** [godotengine/godot#21876] opened 2018-09-08 18:26 UTC
**Godot version:**

**OS/device including version:**

**Issue description:**
When you have a scene with a visibility notifier and it has the camera_entered and camera_exited signals connected to a script in the root node, Godot will throw an error. The thing to note though, as to why these errors shouldn't happen, is because of how you typically don't use the game camera to assemble and edit the scene, yet the view is not seen as a legitimate camera so an error will be thrown complaining of a method not being found. The game meanwhile runs fine since you are looking through an actual camera.

**Steps to reproduce:**
Download the example project and pan the current view so the notifier bounding box is not seen, then pan the view back.

**Minimal reproduction project:**
[Test3.zip](https://github.com/godotengine/godot/files/2363602/Test3.zip)

**Comment by DualMatrix** [comment] 2018-09-14 00:34
I think this might be related to #13070

**Comment by akien-mga** [comment] 2018-09-14 08:35
Duplicate of #13070 indeed.

**Closed by akien-mga** 2018-09-14 08:35 UTC
Labels: bug, topic:core
