### ISSUE TITLE
Android exports with Vulkan even in compatibility mode

### ISSUE THREAD

**Issue by theromis** [godotengine/godot#79269] opened 2023-07-10 08:15 UTC
### Godot version

4.1

### System information

Macos - godot 4.1 - compatibility mode

### Issue description

Can switch GL compatibility mode for android

### Steps to reproduce

Export project (it have glow enabled) which should not work in GL compatibility mode but on android it still glowing

### Minimal reproduction project

[AndroidTest.zip](https://github.com/godotengine/godot/files/11999371/AndroidTest.zip)

**Comment by clayjohn** [comment] 2023-07-10 08:43
I can't reproduce this issue. I have tested using the example project in 4.0.3 and 4.1-stable. In both cases the project runs on Android without glow. 

Notably however, the MRP doesn't contain an export preset, have you overridden any export options locally that may be affecting this?

**Comment by theromis** [comment] 2023-07-10 09:43
checked without gradle build same issue

**Comment by clayjohn** [comment] 2023-07-10 10:30
Are you sure that you are actually installing the new version then? Perhaps something is going wrong in your installation process and you are just running the same executable over and over?

**Comment by theromis** [comment] 2023-07-10 14:17
@clayjohn doing uninstall on android every time and running `adb install test.apk`

**Comment by akien-mga** [comment] 2023-07-10 14:33
Can you reproduce the issue with the reproduction project that you attached? It's configured to use `gl_compatibility` for all platforms (default, and `.mobile` override), so it would never show glow on any platform.

If you only reproduce it in another project, can you show how the `rendering_method` setting and its overrides are configured there?

**Comment by clayjohn** [comment] 2023-07-10 15:24
> please correct me if I'm wrong `rendering_method = Mobile` (vulkan on, GLES3 off and glow works) `rendering_method = Compatibility` (vulkan off, GLES3 on and glow not works) in the last attached project `rendering_method = Mobile` meaning to me vulkan should be on and glow should work but glow not works

The second MRP had

``rendering_method = Mobile`` (Vulkan on, Glow works; used when exporting to desktop)
``rendering_method.mobile = GL_Compatibility`` (GLES3 on, Glow does not work; used when exporting to Android/iOS)

When I tested, glow was working when viewing the scene in the editor on desktop, but there was no glow when exporting to Android, as expected

**Comment by theromis** [comment] 2023-07-10 15:24
just found
<img width="912" alt="Screenshot 2023-07-10 at 8 23 45 AM" src="https://github.com/godotengine/godot/assets/3720229/a8d2a610-bf32-4a30-96d7-e12c1ee32edb">
```
renderer/rendering_method="mobile"
renderer/rendering_method.mobile="gl_compatibility"
```
this is my problem, have to do extra switch for it
thank you for helping me

**Comment by clayjohn** [comment] 2023-07-10 15:26
Do you still have an issue with the first MRP? Your original post said that you were still getting glow when you set the rendering_method to gl_compatibility. 

Or is your main scene set to?
```
rendering_method = GL_Compatibility
rendering_method.mobile =  Mobile 
```

**Comment by theromis** [comment] 2023-07-10 15:33
```
renderer/rendering_method="mobile"
renderer/rendering_method.mobile="mobile"
```
tested, now it glowing

maybe for easier future development better to switch both of this parameters on top right menu change, because it confusing

**Comment by Calinou** [comment] 2023-07-10 15:55
- Duplicate of https://github.com/godotengine/godot/issues/73712.

**Closed by Calinou** 2023-07-10 15:55 UTC
Labels: discussion, platform:android, topic:porting
