### ISSUE TITLE
godot does not start (not responding error)

### ISSUE THREAD

**Issue by miladh06** [godotengine/godot#5807] opened 2016-07-19 11:33 UTC
Hi there
I'm using a windows 10 (64-bit).whenever I want to open Godot, it gives a not responding error and therefore I cannot use it . 
I should add that I tested all versions but the same response.
I attached my system configuration to this issue post.
@reduz 
[DESKTOP-UEMKURN.txt](https://github.com/godotengine/godot/files/371328/DESKTOP-UEMKURN.txt)

**Comment by akien-mga** [comment] 2016-07-19 11:42
Sadly your graphics card is Intel(R) G33/G31 Express Chipset Family, and I'm pretty sure this model does not support OpenGL 2.1 which is a strong requirement for running Godot Engine or Godot games. From what I can read this card series might not even support OpenGL 2.0.

So in essence this issue is a duplicate of #1162, as Godot should ideally not crash but tell you that your graphics driver is not supported.

**Closed by akien-mga** 2016-07-19 11:42 UTC
