### ISSUE TITLE
implement pythonic len()

### ISSUE THREAD

**Issue by oxrock** [godotengine/godot#3126] opened 2015-12-23 15:25 UTC
len() in python is a simple builtin utility to count the number of items in a tuple,list,dictionary and then simply return the results. something like this:

func len(list):
    var x = 0
    for i in list:
        x+=1
    return x

Maybe I'm the only one, but I tend to implement something similar quite often in my scripts.

**Comment by ni-code** [comment] 2015-12-23 17:41
There is a size() func that does that. Not the same name, but I think is what you looking for.
see ex:
https://github.com/godotengine/godot/wiki/class_dictionary#size
https://github.com/godotengine/godot/wiki/class_array#size

**Comment by akien-mga** [comment] 2015-12-23 23:28
Duplicate of #1960.

**Closed by akien-mga** 2015-12-23 23:28 UTC
Labels: enhancement, junior job, topic:gdscript

**Comment by reduz** [comment] 2016-01-22 16:14
could have been implemented, but now adding that as a keyword would most
likely break existing games. Maybe for 3.0
