### ISSUE TITLE
Error Index = p_index = 1 is out of bounds (size() = 0)

### ISSUE THREAD

**Issue by gooficat** [godotengine/godot#76900] opened 2023-05-10 06:03 UTC
### Godot version

4.0.2.stable.official

### System information

Linux Lubuntu 20.04 i3 1st gen mobile, intel igpu [supports latest vulkan]

### Issue description

crash and error during project launch and then if you launch the project manager again the error shows up with a crash.
```
handle_crash: Program crashed with signal 4
Engine version: Godot Engine v4.0.2.stable.official (7a0977ce2c558fe6219f0a14f8bd4d05aea8f019)
Dumping the backtrace. Please include this when reporting the bug to the project developer.
ERROR: FATAL: Index p_index = 1 is out of bounds (size() = 0).
   at: get (./core/templates/cowdata.h:155)                                                                                           

```

### Steps to reproduce

Launch the Engine with the --rendering-driver vulkan
Create a project and it will crash while launching the editor

### Minimal reproduction project

[project.zip](https://github.com/godotengine/godot/files/11438566/project.zip)

**Comment by AThousandShips** [comment] 2023-05-10 06:15
Duplicate of #76447

**Comment by AThousandShips** [comment] 2023-05-10 06:17
Please search for issues before opening a new one

**Comment by akien-mga** [comment] 2023-05-10 06:39
It's not necessarily a duplicate, there are many possible causes for this error message which aren't related. The error just means out if bounds read on an array. The other bug is about using the LSP, this one doesn't mention it.

**Comment by Calinou** [comment] 2023-06-19 07:49
> i3 1st gen mobile, intel igpu [supports latest vulkan]

No, first-gen Intel IGPs definitely don't support Vulkan.

**Comment by Calinou** [comment] 2023-07-03 23:31
Closing in favor of https://github.com/godotengine/godot/issues/58927.

**Closed by Calinou** 2023-07-03 23:31 UTC
Labels: bug, topic:editor, needs testing, crash
