### ISSUE TITLE
Splash screen transitions to black screen on Android

### ISSUE THREAD

**Issue by CGcaspar** [godotengine/godot#74348] opened 2023-03-04 10:05 UTC
### Godot version

4.0

### System information

Pixel 5, Adreno 620, Forward Mobile

### Issue description

In exported Android projects, the configured splash screen is only visible for a very brief moment. Immediately afterwards, there is a transition to a black screen which, depending on how many resources are loaded in a project, remains until the first frame is rendered.

In larger projects where more resources are loaded, the black screen is visible for around 3 seconds depending on the device.

The same black screen is also visible when you check "Use Gradle Build".

Release vs. Debug build also makes no difference.

https://user-images.githubusercontent.com/120789048/222893477-b2ec2e8e-05f0-4ed4-948e-33a139b8a71b.mp4

### Steps to reproduce

1. Create new empty project
2. Create an empty main scene with a Control node
3. Check "Import ETC2 ASTC" in Project Settings
4. Configure Export for Android
5. Export to device

### Minimal reproduction project

N/A

**Comment by phil-hudson** [comment] 2023-09-30 06:56
hey @CGcaspar  - did you find a solution to this? I'm having the same issue

**Comment by phil-hudson** [comment] 2023-10-01 01:26
FYI - changing to gl_compatiblity renderer resolved this for me!

**Comment by Zireael07** [comment] 2023-12-02 14:21
That's because Compatibility equals OpenGL3

**Comment by fieldbit** [comment] 2023-12-08 09:35
Any update /workaround? i see black splash screen on Android (works perfectly on Windows), godot 4.0.4, Samsung S20

**Comment by mahdisml** [comment] 2023-12-08 11:22
> Any update /workaround? i see black splash screen on Android (works perfectly on Windows), godot 4.0.4, Samsung S20

Update to 4.2 Version (https://github.com/godotengine/godot/issues/82525)

**Comment by juse4pro** [comment] 2023-12-08 13:37
> Update to 4.2 Version (#82525)

Unfortunately pushing to 4.2 does not solve the problem.

**Comment by ceyhundrlc** [comment] 2023-12-09 10:13
![Adsız](https://github.com/godotengine/godot/assets/100091602/1dd0ffc2-24cb-45d5-87c5-8a9c95998c23)

**Comment by goranovs** [comment] 2024-02-01 08:25
This still exists on 4.2.1 switching to compatibility is not an option. It happens even on high end devices as Samsung galaxy ultra s20.

**Comment by Zireael07** [comment] 2024-02-01 08:52
@goranovs Compatibility is recommended for actual mobile devices because Vulkan drivers on mobile suck.

**Comment by goranovs** [comment] 2024-02-03 08:32
I don't see any difference in performance. It's just that black screen that seems to be reported multiple times across all versions of Godot. Including here https://github.com/godotengine/godot/issues/62863

**Comment by pudlik** [comment] 2024-02-10 11:44
I'm begging anyone for a solution. I'm about to release the project I worked on for months and this is totally a release-breaking issue. None of the solutions listed anywhere seem to work. Can we get devs to fix it for 4.3 in April??? Please!

**Comment by goranovs** [comment] 2024-02-18 10:28
If I set `Rendering.mobile = gl_compatibility` the only difference is that it does the black screen very quickly after the game icon, but  yet no splash image is displayed.

**Comment by djrain** [comment] 2024-02-28 17:23
This issue is very serious. I'm pretty sure Google rejected our app because it's taking so long on this black screen that they thought it was frozen. Meanwhile it starts up immediately on iOS. Would love to help, but I'm no android dev...

**Comment by djrain** [comment] 2024-02-28 18:45
@brcontainer thanks for the suggestion. I edited my comment to say 6-7 seconds, it was only taking 10 seconds on the debug build straight from Godot. It's faster on a release build. But 7 seconds is still unacceptable. And our game already loads resources on our custom splash scene, so this is not the issue, unfortunately

**Comment by brcontainer** [comment] 2024-02-29 00:52
@djrain I have 5 games (prototypes) for mobile, none of my games take more than 0.5 seconds after the splascreen. The black screen appears, but only for 0.5 seconds, my main scene in all games are custom load screens with a progress bar, using code similar to what I showed you above, so the game itself, with all the features, is just presented later. Every game I see, even light ones, has a loading screen, even PC games.

**Comment by BachDovn** [comment] 2024-04-11 03:08
hey @CGcaspar - did you find a solution to this? I'm having the same issue

**Comment by brcontainer** [comment] 2024-04-11 03:30
@BachDovn It's not something that can be resolved in the settings or via script, it's a bug that needs to be fixed in the Godot core. As long as the issue is open it is unlikely that the problem will be fixed. I recommend that you follow what I said in the previous comment:

> I have 5 games (prototypes) for mobile, none of my games take more than 0.5 seconds after the splascreen. The black screen appears, but only for 0.5 seconds, my main scene in all games are custom load screens with a progress bar, using code similar to what I showed you above, so the game itself, with all the features, is just presented later. Every game I see, even light ones, has a loading screen, even PC games.
> 
> Adding a load screen is a matter of user experience, as if it doesn't have this the user may think that the game has frozen. Another thing that might be interesting to add is the screen transition between scenes.

Create a simple scene, this scene should be the main one, then add a load for the larger scene, using `ResourceLoader.load_threaded_request(scene)`, script example:

``` gdscript
extends Control

const SAMPLE_SCENE := "res://rooms/sample_room.tscn"

var progress: Array[float] = []
var loading: bool = false
var status: ResourceLoader.ThreadLoadStatus

@onready var tree: SceneTree = get_tree()
@onready var progressbar: ProgressBar = $VBoxContainer/ProgressBar

func _process(_delta) -> void:
    if loading:
        status = ResourceLoader.load_threaded_get_status(SAMPLE_SCENE, progress)

        match status:
            ResourceLoader.THREAD_LOAD_IN_PROGRESS:
                progressbar.value = progress[0] * 100.0

            ResourceLoader.THREAD_LOAD_FAILED, ResourceLoader.THREAD_LOAD_INVALID_RESOURCE:
                loading = false
                Global.quit("Error", "ResourceLoader load failed", status)

            ResourceLoader.THREAD_LOAD_LOADED:
                loading = false

                progressbar.value = 100.0

                tree.change_scene_to_packed(ResourceLoader.load_threaded_get(SAMPLE_SCENE))
```
A scene sample, `intro.tscn`:

```
[gd_scene load_steps=2 format=3 uid="uid://cn1t7w3x5k6pk"]

[sub_resource type="GDScript" id="GDScript_2s2fu"]
script/source = "extends Control

const SAMPLE_SCENE := \"res://rooms/sample_room.tscn\"

var progress: Array[float] = []
var loading: bool = false
var status: ResourceLoader.ThreadLoadStatus

@onready var tree: SceneTree = get_tree()
@onready var progressbar: ProgressBar = $VBoxContainer/ProgressBar

func _process(_delta) -> void:
    if loading:
        status = ResourceLoader.load_threaded_get_status(SAMPLE_SCENE, progress)

        match status:
            ResourceLoader.THREAD_LOAD_IN_PROGRESS:
                progressbar.value = progress[0] * 100.0

            ResourceLoader.THREAD_LOAD_FAILED, ResourceLoader.THREAD_LOAD_INVALID_RESOURCE:
                loading = false
                Global.quit(\"Error\", \"ResourceLoader load failed\", status)

            ResourceLoader.THREAD_LOAD_LOADED:
                loading = false

                progressbar.value = 100.0

                tree.change_scene_to_packed(ResourceLoader.load_threaded_get(SAMPLE_SCENE))
"

[node name="Intro" type="Control"]
layout_mode = 3
anchors_preset = 15
anchor_right = 1.0
anchor_bottom = 1.0
grow_horizontal = 2
grow_vertical = 2
script = SubResource("GDScript_2s2fu")

[node name="VBoxContainer" type="VBoxContainer" parent="."]
layout_mode = 1
anchors_preset = 14
anchor_top = 0.5
anchor_right = 1.0
anchor_bottom = 0.5
offset_top = -13.5
offset_bottom = 13.5
grow_horizontal = 2
grow_vertical = 2

[node name="ProgressBar" type="ProgressBar" parent="VBoxContainer"]
layout_mode = 2
```

**Comment by BachDovn** [comment] 2024-04-11 04:31
@brcontainer I understand your code, you mean make a loading screen, and when load sence done, can change to that sence.
I already use for my project, it working perfect on window but, on android still same. on android mobile it show full progress bar when it done 100% and yes change to that sence but still black screen dont see any 3d sence, but 2d is show.

**Comment by brcontainer** [comment] 2024-04-11 04:44
@BachDovn But it's the black screen on Android that I'm talking about, as I mentioned in the penultimate comment and I still say, read it, if the main scene is small, it will take a maximum of 0.5 seconds, which is acceptable, even if perceptive. But if the main scene is large, the black screen will be even more noticeable, so a loading screen is better.

And I reiterate what I said in the penultimate comment, all my projects are mobile, mainly Android, and I test on slow and old devices, all my projects use a small and intermediate load scene, so this 0.5s (half a second) of the screen black is the result I got on all devices. This time is perfectly acceptable.

And just for better understanding, the main reason I commented is that this bug has not yet been resolved, when the issue is, it will be marked as "closed". Subscribe to this issue and you will be notified.

Thank you for understanding.

**Comment by BachDovn** [comment] 2024-04-11 05:33
@brcontainer are you sure that solve for 3d? because I only have proplem with 3d sence. if your code work for 3d sence that would be nice. I want to learn deeper, and thank you so much for that.

**Comment by brcontainer** [comment] 2024-04-11 06:45
@BachDovn All my projects are 3D and in all of them I follow what I suggested, creating a simple scene that is just of type `Control`:

And Control scene will call the 3D scene using `ResourceLoader.load_threaded_request(...)` + `ResourceLoader.load_threaded_get_status(..., progress)`.

**Comment by BachDovn** [comment] 2024-04-11 13:23
@brcontainer I do try, but no progress. Out put show that it run 3d sence, but screen doesnt, it stop at loading screen. My phone running android 11, so I dont think it weak. I think Godot didnt support 3d on mobile. I am disappointed. Maybe it is time to learn and try other engine. Thank you

**Comment by brcontainer** [comment] 2024-04-11 16:57
@BachDovn From what you explained, it seems to me that the problem is something else, unrelated to the current bug reported. The problem should only occur after the splashscreen, if the problem is occurring in other situations it could be a fault in something you did.

**Comment by djrain** [comment] 2024-04-11 19:19
@brcontainer I'd be curious to know how your projects run in 4.2, since in this issue #85264 they say that the black screen time became longer in 4.2

**Comment by brcontainer** [comment] 2024-04-11 22:12
I actually use 4.1, but I tweaked a project for 4.2 and made a video for you to see. Details about the video:

1. My device is bad
2. The video recorder degrades the overall performance of the device.
3. All my projects are 3D

https://github.com/godotengine/godot/assets/4368952/6df848e5-e26c-4c79-a9ee-7504cdf7ca46

Black screen took 0.8s to load the "intro.tscn" scene

**Comment by djrain** [comment] 2024-04-11 23:04
That's encouraging to see, thanks :) Still struggling to get the time down in our game - main scene is a tiny one, and got rid of almost all preloaded resources, but still almost 4 seconds on black screen. I guess the problem must be in autoloads or `class_name` scripts...

**Comment by BachDovn** [comment] 2024-04-12 00:37
@brcontainer wow...what good news. If you don't mind, can you tell me about your godot settings, which jdk do you use? Do you run it on USB remote debugging or do you export it and install it? How do you set up export? Do you have a YouTube tutorial channel?
I use Godot 4.2.1, template 4.2.1 stable, gradle 7.4.2, jdk17 provided by https://docs.godotengine.org/.
Mobile: Oppo a54, Android 11, 4G ram

**Comment by BachDovn** [comment] 2024-04-12 01:24
@brcontainer help me bro,do I setting correct.
main sence 2d:
![image](https://github.com/godotengine/godot/assets/132882686/ade51d23-7986-4827-92c6-0c7713caab8f).
main script( not auto load):
extends Control

@onready var SAMPLE_SCENE = "res://node_3d.tscn"

@onready var progress:Array = []
@onready var loading: bool = false
@onready var status: ResourceLoader.ThreadLoadStatus
@onready var progressbar = $VBoxContainer/ProgressBar

func _ready():
	ResourceLoader.load_threaded_request(SAMPLE_SCENE) # initiate loading scene
	loading = true
	pass
func _process(_delta):
	if loading:
		status = ResourceLoader.load_threaded_get_status(SAMPLE_SCENE, progress)
		match status:
			#ResourceLoader.THREAD_LOAD_IN_PROGRESS:
			1:
				progressbar.value = progress[0] * 100.0
				print(progressbar.value)
			#ResourceLoader.THREAD_LOAD_FAILED, ResourceLoader.THREAD_LOAD_INVALID_RESOURCE:
			0,2:
				loading = false
				print("Loading fail")
				return
			#ResourceLoader.THREAD_LOAD_LOADED:
			3:
				loading = false
				progressbar.value = 100.0
				get_tree().change_scene_to_packed(ResourceLoader.load_threaded_get(SAMPLE_SCENE))
				print("Done")

simple sence 3d:
![image](https://github.com/godotengine/godot/assets/132882686/c81c874c-42f4-4ddb-93d2-652615d5d120)
setting export:

Export with debug: yes
name="Android"
platform="Android"
runnable=true
dedicated_server=false
custom_features=""
export_filter="all_resources"
include_filter=""
exclude_filter=""
export_path="../../Godot Export/Test.apk"
encryption_include_filters=""
encryption_exclude_filters=""
encrypt_pck=false
encrypt_directory=false

[preset.0.options]

custom_template/debug=""
custom_template/release=""
gradle_build/use_gradle_build=true
gradle_build/export_format=0
gradle_build/min_sdk="24"
gradle_build/target_sdk="30"
architectures/armeabi-v7a=false
architectures/arm64-v8a=true
architectures/x86=false
architectures/x86_64=false
version/code=1
version/name=""
package/unique_name="com.example.$genname"
package/name=""
package/signed=true
package/app_category=2
package/retain_data_on_uninstall=false
package/exclude_from_recents=false
package/show_in_android_tv=false
package/show_in_app_library=true
package/show_as_launcher_app=false
launcher_icons/main_192x192=""
launcher_icons/adaptive_foreground_432x432=""
launcher_icons/adaptive_background_432x432=""
graphics/opengl_debug=true
xr_features/xr_mode=0
screen/immersive_mode=true
screen/support_small=true
screen/support_normal=true
screen/support_large=true
screen/support_xlarge=true
user_data_backup/allow=true
command_line/extra_args=""
apk_expansion/enable=false
apk_expansion/SALT=""
apk_expansion/public_key=""
permissions/custom_permissions=PackedStringArray()
permissions/access_checkin_properties=false
permissions/access_coarse_location=false
permissions/access_fine_location=false
permissions/access_location_extra_commands=false
permissions/access_mock_location=false
just false for all permissions.

**Comment by brcontainer** [comment] 2024-04-12 05:53
@djrain @BachDovn 

I created a simple sample, made some adjustments to "project.godot" to optimize on mobile devices. Test to confirm if the black screen takes longer than 1s on your devices:

- Source: https://github.com/brcontainer/godot-loading-sample
- Release APK: https://github.com/brcontainer/godot-loading-sample/releases/download/1.0.0/sample-release.apk
- Debug APK: https://github.com/brcontainer/godot-loading-sample/releases/download/1.0.0/sample-debug.apk

**Comment by BachDovn** [comment] 2024-04-12 06:31
@brcontainer yes, 2 file apk run in my mobile android is stop at 0% progress bar, and just stay that forever

**Comment by brcontainer** [comment] 2024-04-12 07:02
@BachDovn It seems to be the problem I mentioned, 4.2 has problems with different devices, so I'm sticking with 4.1 until 4.3 is ready.

Anyway, here's a test I did on my device with `sample-release.apk`:

https://github.com/godotengine/godot/assets/4368952/ff87e16c-feb7-4269-ba4f-1bd369e46945

**Comment by BachDovn** [comment] 2024-04-21 08:21
@brcontainer so, i just try Godot 3.5.3  and change to gles2 and enable import etc.....that solve.

**Comment by ivanreyne** [comment] 2024-04-29 18:53
Same happening to me.

I am using Godot 4.2.2 and when deploying to Android the boot splash screen config gets ignored and whilst loading the first scene it shows a black screen (not even picking up the  boot splash custom background colour).

I already tried to have as initial scene a very simple one just to make sure it was not a problem loading resources or something like that but made no difference.

The other thing I realised is that it depends a lot on the device. I have a Motorola G9 phone where it happens but you can barely notice, but on a Samsung Galaxy Tablet it lasts about 5-6 seconds. As I am trying to publish the game I have tried to local install through usb cable as well as downloading the app through the play store for internal testing and the results are the same.

When uploading the app to the Samsung Galaxy Tablet with the usb debug cable I noticed the following output messages:

```
Exporting Poing AdMob '.cfg' file
0 param: --remote-debug
1 param: tcp://localhost:6007
2 param: --xr_mode_regular
3 param: --use_immersive
Installing to device (please wait...): Samsung SM-T220
--- Device API >= 21; debugging over USB ---
--- DEVICE API >= 21; DEBUGGING OVER USB ---
Reverse result: 0
Godot Engine v4.2.2.stable.official.15073afe3 - https://godotengine.org
Vulkan API 1.1.131 - Forward Mobile - Using Vulkan Device #0: ImgTec - PowerVR Rogue GE8320
```
 
and the 5-6 seconds delay happens between
_"Reverse result: 0"_
and
_"Godot Engine v4.2.2.stable.official.15073afe3 - https://godotengine.org"_
and then the first scene loaded without any sign of the boot splash screen.

I am using a custom gradle build as I intend to use AdMob. But even without the plugin the problem is the same.

On a side note I had it first with the compatibility render and it also showed the same problem (maybe it took a bit less time to load). But I cannot go back to the compatibility render because it gives me now an error on a skeleton shader compilation. Obviously this is a different issue.

I hope this additional info helps.

**Comment by ivanreyne** [comment] 2024-05-07 21:47
Hi, a bit more information about this problem.

It seems that from Android 12 the splash screen config/rules have changed. Moreover the "new" Android splash screens can only contain a icon image (that can be animated) on the center plus a background colour. This is what the users will see since they start loading the app until the very first scene is loaded by the Godot engine. It is possible that this is a bit of a breaking change compared to what was allowed to do until now.

This is the relevant link to the Android documentation:
[https://developer.android.com/develop/ui/views/launch/splash-screen](https://developer.android.com/develop/ui/views/launch/splash-screen)
And they also provide info on how to migrate to the new system:
[https://developer.android.com/develop/ui/views/launch/splash-screen/migrate](https://developer.android.com/develop/ui/views/launch/splash-screen/migrate)

There is [this repository](https://github.com/MiqueiasDevGames/Godot-SplashScreen-Android-12)  that shows you how to configure the entire thing. All the "res" files, changes on the AndroidManifest.xml, etc. I think it is based on Godot 3.x but the changes on the Android files are the same. The only thing that changes is the way it loads the "game scene" after the Android splash screen closes.

In my case (I already had a custom graddle build) I ended up using the splash screen configuration very similar to what is described in that repository and then I followed some other comments to have a very simple "initial main scene" that shows the actual "nice splash scene" and that is the responsible for loading the "game main scene" on the background. And then on that "nice splash scene", as it is a proper Godot scene, you can have anything (any animations, progress loaders, etc) you want. 

Hope it helps and gives and overview of the problem to the maintainer of the default graddle build template.

**Comment by Alex2782** [comment] 2024-05-09 00:39
Does it make sense to display the "desktop"-version splash screen again on Android?

`implementation "androidx.core:core-splashscreen:1.0.0"` This also increases the APK size.

https://github.com/godotengine/godot/blob/cff016d6dd2aa3345c1e6bcc0c49477c40488f97/main/main.cpp#L2848-L2849

The configuration `Minimum Display Time` should also not be used on Android, this extends the black screen.

--------

`show_logo = true` works identically (like on desktop) in the master branch, but the black screen is still briefly visible on Android. Could be Vulkan initialization process.

![Bildschirmfoto 2024-05-09 um 02 08 05](https://github.com/godotengine/godot/assets/41921395/4904eea7-78bc-48cc-8a20-78d8cd5e2855)

**Closed** 2024-06-13 15:21 UTC
Labels: bug, platform:android, topic:porting, confirmed

**Comment by unforgiven1990** [comment] 2024-08-07 14:41
> @brcontainer I understand your code, you mean make a loading screen, and when load sence done, can change to that sence. I already use for my project, it working perfect on window but, on android still same. on android mobile it show full progress bar when it done 100% and yes change to that sence but still black screen dont see any 3d sence, but 2d is show.



> @brcontainer I understand your code, you mean make a loading screen, and when load sence done, can change to that sence. I already use for my project, it working perfect on window but, on android still same. on android mobile it show full progress bar when it done 100% and yes change to that sence but still black screen dont see any 3d sence, but 2d is show.

This is exactly my issue too! So frustrating
