### ISSUE TITLE
"Use Alpha Scissor" material parameter prevents shadow casting

### ISSUE THREAD

**Issue by starry-abyss** [godotengine/godot#13350] opened 2017-11-27 18:46 UTC
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Win 7 64 bit, 31f62f5, NVIDIA GTX 660, driver 388.00

**Issue description:**
![default](https://user-images.githubusercontent.com/11571820/33283040-a68d82e4-d3bb-11e7-844f-7da49bc8f358.png)
![default](https://user-images.githubusercontent.com/11571820/33283061-b56408ce-d3bb-11e7-8a4b-3ff9224c761d.png)

**Steps to reproduce:**
1. Get the attached project
2. Open `tree.material` in the filesystem
3. In the inspector enable `Parameters->Use Alpha Scissor`

**Link to minimal example project:**
[use-alpha-scissor-shadow.zip](https://github.com/godotengine/godot/files/1507148/use-alpha-scissor-shadow.zip)

**Comment by mrcdk** [comment] 2017-11-27 19:32
You need to set the Depth Draw Mode to Opaque pre-pass for transparent objects to cast a shadow

**Comment by starry-abyss** [comment] 2017-11-27 20:32
Thank you, it worked!

**Comment by starry-abyss** [comment] 2017-11-28 04:15
@Noshyaar Not sure to close it, maybe it should be then re-tagged "usability"?

**Comment by Noshyaar** [comment] 2017-11-28 07:56
I don't know much about 3D rendering, but I think this should be closed as "not a bug". You could open a new one regarding the workflow issues, unclear options etc.

**Closed by Noshyaar** 2017-11-28 07:56 UTC
Labels: bug, topic:rendering
