### ISSUE TITLE
Godot crash after typing delete in visual script.

### ISSUE THREAD

**Issue by cryptonosaurus** [godotengine/godot#64760] opened 2022-08-23 00:56 UTC
### Godot version

3.5-stable

### System information

Windows 11 64bits, GTX 1060, GLES3

### Issue description

Godot crash after typing delete in visual script, but not in visual shader editor.
It crash only if i hit delete key on my keyboard and i have a node closable node in the selection.
In the mono and non mono version.
I tryed to remove the delete node shortcut in the visual scripting shortcut settings, but it crash anyway.
I set the shortcut to 'X' button, it delete the node and dont crash.
It come from the delete button itself.

![Capture d’écran 2022-08-23 024043](https://user-images.githubusercontent.com/93253123/186044645-cbfc3558-69a3-41ec-a895-746d95196a66.png)

Here the error in the console when the crash happend:
![Capture d’écran 2022-08-23 023732](https://user-images.githubusercontent.com/93253123/186044707-843e751a-ab5f-40ab-a8b5-b8a151194269.png)

### Steps to reproduce

Create a project.
Create visual script file.
Edit the vs file.
Create at least one closable (with close button) node.
Select as much nodes as you want, but make sure to have at least one closable button in the selection.
Hit delete on the keyboard.

### Minimal reproduction project

[Visual Script Crash.zip](https://github.com/godotengine/godot/files/9398510/Visual.Script.Crash.zip)

**Comment by cryptonosaurus** [comment] 2022-08-23 02:19
Update the bug don't exist in 3.4.5-stable.

**Comment by akien-mga** [comment] 2022-08-23 08:33
Duplicate of #64662.

**Closed by akien-mga** 2022-08-23 08:33 UTC
Labels: bug, topic:editor, topic:visualscript, crash, regression
