### ISSUE TITLE
Grow Amount in the SpatialMaterial editor automatically rounds to 0.01 intervals

### ISSUE THREAD

**Issue by xKamuna** [godotengine/godot#25933] opened 2019-02-16 11:11 UTC
**Godot version:**

Godot 3.1 beta 3

**OS/device including version:**

Windows 10

**Issue description:**

Grow Amount will not accept any custom value that isn't in 0.01 intervals (for example, it'll round 0.001 to 0).  This makes getting thin lines in a toon shader impossible without scaling the model or using a shader.

**Steps to reproduce:**
1. Attempt to change Grow Amount to something less than 0.01 intervals.

**Comment by Chaosus** [comment] 2019-02-16 11:30
Duplicate of https://github.com/godotengine/godot/issues/25887

**Closed by Chaosus** 2019-02-16 11:30 UTC
