### ISSUE TITLE
The tile is outside the texture error.

### ISSUE THREAD

**Issue by Isenther** [godotengine/godot#80230] opened 2023-08-03 22:01 UTC
### Godot version

4.2 Dev 2

### System information

Windows 11, Intel(R) Core(TM) i5-10400F CPU, NVIDIA GeForce GTX 1060 6GB, 24 ram

### Issue description

If you change the resolution of a tileset texture to a smaller resolution, while it was already implemented in a tilemap with selected tiles outside that resolution, it will throw an error instead of unselecting the tiles.

### Steps to reproduce

1. Open scene in testscene folder. You will see that i already put a tileset texture in the tilemap with everything selected.
2. Replace that texture with the other texture i mention on the tileset folder, either by exporting it with the krita file as an png, or replacing with the png i included.
3. Save the project and quit. Open it again. Thats when the error appears. 

### Minimal reproduction project

[InvalidTileReproduction.zip](https://github.com/godotengine/godot/files/12255373/InvalidTileReproduction.zip)

**Comment by KoBeWi** [comment] 2023-08-03 23:01
Duplicate of #61296

**Closed by KoBeWi** 2023-08-03 23:01 UTC

**Comment by qalmurri** [comment] 2023-12-14 07:06
If you have a 32x32.png spritesheet for Isometric. In Tilemap, use Isometric 32x32 first, then import spritesheet 32x32.png. If so, set the Tilemap to 32x16. It's like a reversal method. You have to try it..
