### ISSUE TITLE
Godot 3.1.1 ignores invalid command line options and continues with execution

### ISSUE THREAD

**Issue by wyattbiker** [godotengine/godot#32579] opened 2019-10-06 02:26 UTC
**Godot version:**
v3.1.1.stable.official

**OS/device including version:**
Mac OS X

**Issue description:**
1) Godot does not validate command line options. Instead continues executing.
2) Command line option `-v` does not work. Use --version instead.

**Steps to reproduce:**
E.g. `godot -xyz` will run godot anyway.
 Also `godot -v `is ignored. However `godot --version` works

**Expected behavior**
Should produce an error message when option is invalid.

**Comment by lupoDharkael** [comment] 2019-10-06 12:20
will be fixed by https://github.com/godotengine/godot/pull/26213

**Comment by Calinou** [comment] 2019-10-06 13:21
Duplicate of #20000.

> Also `godot -v` is ignored. However `godot --version` works

This is because `-v` is short for `--verbose` :slightly_smiling_face: We could have `-V` as a shorthand for version.

**Closed by Calinou** 2019-10-06 13:21 UTC
