### ISSUE TITLE
A way to filter nodes that gets rendered in a specific viewports

### ISSUE THREAD

**Issue by puthre** [godotengine/godot#31312] opened 2019-08-12 08:38 UTC
It would be very useful to have a way to render only a group of nodes to a specific viewport (in 2D) or a type of node that can have multiple viewport parents so you can have nodes attached to multiple viewports.

Right now you can either render DIFFERENT nodes to different viewports or ALL the nodes to different viewports but some times you will need to render some of the same nodes to different viewports so you can use the resulting viewport textures for different effects (like glow for example)

**Comment by Zireael07** [comment] 2019-08-12 09:35
I thought 2D had VisualInstance layers, too? (Look in the inspector, above transform, matrix, visibility, the visual instance heading should be there).

You can disable a camera from showing a specific visual instance layer, therefore you can easily hide nodes on specific viewports (e.g. my mirror viewport doesn't show the clouds in the sky)

**Comment by puthre** [comment] 2019-08-12 10:30
> I thought 2D had VisualInstance layers, too? (Look in the inspector, above transform, matrix, visibility, the visual instance heading should be there).

That's only in 3D.

**Comment by Xrayez** [comment] 2019-08-12 10:53
> to render only a group of nodes

As you mention groups, you could try `add_to_group()` your nodes and filter them by visibility so that they don't get rendered.

> node that can have multiple viewport parents

Nodes cannot have more than one parent, I think that's by design.

You can also switch different `world_2d` to a single `Viewport`. The world resource has all the associated canvas and physics spaces that you could somehow manipulate using a `VisualServer` perhaps but that's quite low-level.

**Comment by puthre** [comment] 2019-08-12 12:36
> > to render only a group of nodes
> 
> As you mention groups, you could try `add_to_group()` your nodes and filter them by visibility so that they don't get rendered.
How would you filter them for one viewport and not for another?

**Comment by Xrayez** [comment] 2019-08-12 12:43
Well the issue remains I guess in this case since you want to share these nodes between viewports anyway, I just listed all possible solutions that came to my mind really.

But you could probably somehow append a special identifier to a group if that makes sense for your use case, like `add_to_group("nodes_a")` and `add_to_group("nodes_b")`.

**Comment by puthre** [comment] 2019-08-12 12:50
> But you could probably somehow append a special identifier to a group if that makes sense for your use case, like `add_to_group("nodes_a")` and `add_to_group("nodes_b")`,
> 
> or even:
> `add_to_group("nodes_" + viewport.name)`
Still this won't change the fact that the viewport does not care in which groups the nodes are.

**Comment by bojidar-bg** [comment] 2019-08-15 09:38
Related: #5441.

**Comment by puthre** [comment] 2019-09-01 23:17
Added ##31877 to fix this issue

**Comment by mhilbrunner** [comment] 2020-05-28 15:38
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!

**Closed by mhilbrunner** 2020-05-28 15:38 UTC
Labels: feature proposal, topic:rendering
