### ISSUE TITLE
Godot 4.0 HTML5 export does never work on Ios

### ISSUE THREAD

**Issue by netAction** [godotengine/godot#75281] opened 2023-03-24 06:20 UTC
### Godot version

4.0.1

### System information

IpadOS 16.3.1, Ipad Pro 2022

### Issue description

I tried many settings, searched the Internet and the bug reports but could not find any hint.

I cannot run any HTML5 game on Ios, neither in Chrome or Safari.

### Steps to reproduce

Run Godot 4.0.1

New project with Renderer: Compatibility (OpenGL 3.3/ES 3.0/WebGL2)

Add a 2D Scene which creates a scene with Node2D

Add one Sprite with JPG to the Node2D

Save scene and set it as main scene

In Export settings: Add Web

Leave all settings on the right side of export window on default

Export... and turn Debug information off

Upload to 2 different Webhoster services, both with Let's encrypt HTTPS

Disable Nginx cache, just Apache

Minimal .htaccess file
```
Header set cross-origin-embedder-policy "require-corp"
Header set cross-origin-opener-policy "same-origin"
```

Open Safari on Ipad Pro from 2022 with Ipados 16.3.1

The bar loads in 2 seconds but the following spinner rotates for minutes without any progress.

### Minimal reproduction project

N/A

**Comment by Calinou** [comment] 2023-03-24 18:26
- Duplicate of https://github.com/godotengine/godot/issues/70621.

**Closed by Calinou** 2023-03-24 18:26 UTC

**Comment by netAction** [comment] 2023-03-25 11:46
Thanks for the hint to Safari's Debug console. This is not a duplicate of #70621 but might be a duplicate of #74512.

In my case, Safari throws:
`CompileError: WebAssembly.Module doesn't parse at byte 1140: can't get 1th argument Type`

**Comment by netAction** [comment] 2024-04-19 07:52
Still not solved and still not the duplicate.

**Comment by akien-mga** [comment] 2024-04-19 10:44
Well, it's a duplicate of #74512 as you pointed out, so let's keep the debugging focused there.
