### ISSUE TITLE
shortcut parity with blender(or sync/import config)

### ISSUE THREAD

**Issue by Elmapul** [godotengine/godot#6110] opened 2016-08-11 05:16 UTC
its a bit anoying to have different shortcuts for any program i use, it break the workflow.
there is anyway to import an configuration file defining shortcuts for common features? 
(eg: blender use: g for translate, r for rotate, s for scale)

or to export the godot shortcut config to blender? (or keep their configuration sync)

**Comment by Calinou** [comment] 2019-07-14 15:36
Duplicate of #3995 (which also has more information).

**Closed by Calinou** 2019-07-14 15:36 UTC
Labels: feature proposal, topic:editor, usability
