### ISSUE TITLE
Nodes with scripts overriding _init to accept a parameter instance without a script at run-time

### ISSUE THREAD

**Issue by Topodic** [godotengine/godot#58303] opened 2022-02-19 02:36 UTC
### Godot version

v3.4.1.stable.official [aa1b95889]

### System information

Pop_OS! v21.10

### Issue description

Attaching a script to a Node that overrides _init to accept a parameter breaks run-time instancing of that Node. If this Node is instanced from any other Node, the script attached to it will be completely missing, which can be verified in the Remote tab during run-time. An error is thrown in the log:
```swift
E 0:00:00.415   _create_instance: Condition "r_error.error != Variant::CallError::CALL_OK" is true. Returned: nullptr
  <C++ Source>  modules/gdscript/gdscript.cpp:115 @ _create_instance()
  <Stack Trace> Instancer.gd:6 @ _ready()
```
I would expect this to behave as any other Node and retain the script, or behave as it does within the editor, instancing normally, script intact.

### Steps to reproduce

1. Attach a script to a scene and override _init to accept any parameter.
2. Instance this Node at run-time from another Node.
3. Check the instanced Node while running in Remote to see that the script is now missing from it.
-   Alternatively, try setting any variable that Node contained to prompt an error.

### Minimal reproduction project

[InstanceIssue.zip](https://github.com/godotengine/godot/files/8101290/InstanceIssue.zip)

**Comment by Calinou** [comment] 2022-02-19 18:02
Duplicate of https://github.com/godotengine/godot/issues/15866.

**Closed by Calinou** 2022-02-19 18:02 UTC
