### ISSUE TITLE
Tool script prevents machine from going to sleep

### ISSUE THREAD

**Issue by yhwhey** [godotengine/godot#68941] opened 2022-11-21 06:50 UTC
### Godot version

4.0b5

### System information

Windows 10 and macOS

### Issue description

Having an active tool script in the editor prevent machine from automatically going to sleep. 
Tested on both macOS and Windows 10 with same behaviour

### Steps to reproduce

add tool script to scene. set your machine's sleep timer to a short time and note that machine will not go to sleep while tool script is running

see attached project

### Minimal reproduction project

[tool_sleep_issue.zip](https://github.com/godotengine/godot/files/10061741/tool_sleep_issue.zip)

**Comment by bend-n** [comment] 2022-11-21 07:11
Why is this a problem?

**Comment by yhwhey** [comment] 2022-11-21 07:16
Many projects have tool scripts for various things which are often open during development. It is pretty inconvenient for these scripts to prevent your computer from going to sleep at all. 
Having to remember to manually put computer to sleep seems like a bug to me

**Comment by Mickeon** [comment] 2022-11-21 13:34
It's a pretty situational problem, but it does feel like this shouldn't be the case, anyhow.

**Comment by bend-n** [comment] 2022-11-21 23:00
Your mrp does not work.

**Comment by yhwhey** [comment] 2022-11-22 01:22
mrp upload looks to have failed. fixed now

**Comment by akien-mga** [comment] 2022-11-26 09:09
Might be related to https://github.com/godotengine/godot/issues/69167 though that one would happen even without tool script.

**Comment by Calinou** [comment] 2022-12-16 21:27
Duplicate of #69167 (same cause).

**Closed by Calinou** 2022-12-16 21:27 UTC
Labels: bug, topic:editor, topic:porting, needs testing
