### ISSUE TITLE
Git Version Control Plugin Does Not Refresh Commit List

### ISSUE THREAD

**Issue by JohnDevlopment** [godotengine/godot#62859] opened 2022-07-09 16:38 UTC
### Godot version

v3.5.rc6.official [f05cecdc4]

### System information

Linux Mint 19.3 Tricia

### Issue description

When the refresh button (tooltip: "Detect new changes") is pressed, the plugin does refresh the index; however, the commit list does not.

Let's say I want to run this command: `git commit --fixup HEAD` on the commandline. I do so, go back into Godot (which I never closed or restarted) and I press this button. Any files that were shown under "staged changes" are no longer displayed. But the commit list isn't refreshed. Instead an error is displayed on the console: "core/object.cpp:1242 - Error calling method from signal 'pressed': 'VersionControlEditorPlugin::_refresh_commit_list': Method expected 1 arguments, but called with 0."

### Steps to reproduce

Open a project with the git plugin enabled. Change any random file and stage the changes. Go into a terminal and use `git commit` to commit the changes. Then press the refresh button in Godot to see the error.

### Minimal reproduction project

Here is the example project I used.
[git-refresh-bug.zip](https://github.com/godotengine/godot/files/9077526/git-refresh-bug.zip)

**Comment by Calinou** [comment] 2022-07-09 17:02
cc @ChronicallySerious

**Comment by ChronicallySerious** [comment] 2022-07-09 17:44
I was able to reproduce this bug with godot-git-plugin 2.1.0. 

Your example project seems to be using the 2.0.1 version of the plugin which isn't compatible with Godot 3.5rc6 (calling a specific function from this version of the plugin seems to crash the editor because of a difference in the GDNative API). 

So just something to note if anyone is trying to replicate this.

**Comment by JohnDevlopment** [comment] 2022-07-11 19:19
So how do I get version 2.1? Do I need to compile it?

**Comment by ChronicallySerious** [comment] 2022-07-12 05:14
Yes, you are using the correct plugin version and Godot version. Just your example project was using an older plugin version that crashes with new Godot 3.5 beta/rc releases, so I switched the plugin binaries with the new ones in my testing. 

I have reproduced the error and opened a PR to fix it. It's been added to the 3.5 milestone so that should mean that it goes into 3.5 stable as well. 

Thanks for reporting this bug!

**Comment by JohnDevlopment** [comment] 2022-07-12 05:40
No problem. I guess this issue is close then.

**Comment by ChronicallySerious** [comment] 2022-07-12 10:48
We can keep this opened. The PR hasn't been merged yet, but the automation will take care to closing issue once the PR is merged

**Comment by JohnDevlopment** [comment] 2022-07-12 14:17
Okay.

**Comment by akien-mga** [comment] 2022-07-18 07:20
Fixed by #62862.

**Closed by akien-mga** 2022-07-18 07:20 UTC
Labels: bug, topic:editor, confirmed
