### ISSUE TITLE
rect_scale on Control Nodes inside VBox or HBox Container

### ISSUE THREAD

**Issue by salvob41** [godotengine/godot#21629] opened 2018-08-31 16:46 UTC
I have a GUI setup like this....

![image](https://user-images.githubusercontent.com/6097015/44925176-e9b76f00-ad4d-11e8-86d1-1f67a19674e1.png)

I would like to have the group to the right mirrored respect to the the group to the left. 
I can reach this setting `rect_scale` to `Vector2(-1,1)` and setting properly the Pivot offset. 

But since it is inside a BoxContainer, Godot at runtime doesn't care about this setting.... Is there a way to put some sense into it and leave it mirrored? 

Is it a bug? or it is supposed to work like this? 

**Godot version:**
3.0.6

**Minimal reproduction project:**
I will put  an example project as an example. 
https://www.dropbox.com/s/im976ib4wo96yee/flip-bug.zip

**Comment by groud** [comment] 2019-01-24 22:38
This is a duplicate of #19068

**Closed by groud** 2019-01-24 22:38 UTC
