### ISSUE TITLE
Vulkan: Particle ramp textures are set to repeat, causing visual artifacts when they restart

### ISSUE THREAD

**Issue by Silvanuz** [godotengine/godot#60032] opened 2022-04-08 15:33 UTC
This is my first issue report ever so I hope everything is correct.
English is not my mother tongue so please understand..

Godot 4 Alpha 6

Issue description:
So there are a few Bugs with the GPUParticles2D.
**I recommend to look in the project because it's very hard to descripe the bugs.**

1. If you use a colored gradient with transparent at the end, then the particles at the end of their lifetime are suddenly displayed again in the color that is at the beginning of the gradient
2. At the start the particles have the last Color from the gradient. This happens when you have a high amount of particles.
3. If the FPS are set to 30 in the particles and you change the amount, there are a lot of visual glitches happening

Here is the 3. issue in my project: https://twitter.com/proj_Aetheria/status/1512212234952491014

I created an example object with all the things + A video.
[Project.zip](https://github.com/godotengine/godot-docs/files/8453343/Project.zip)

I also have a small improvement suggestion for the gradient handling.
If you drag the slider in the gradient, for example, from the far left to the far right with the mouse and you want to undo it, then you have to press ctrl+z 1000 times because it tracks every color on the way. Maybe the retraction point should be where you started with the mouse?

Edit:

I thought of 2 new things that I had the last few days

1. When I first add the Color Gradient to the Particle - Nothing happend. Reload the Scene fixed it. This happens everytime when I create a new Particle with Gradient
2. I'm using an Animated Texture in the "texture" property. Sometimes in the Editor the animation doesn't work. When I run the game everything is ok. This only happens sometimes in the Editor. Fix -> Restart Godot

**Comment by clayjohn** [comment] 2022-04-08 15:39
Thanks for your bug report. I have transferred it to the main Godot repository which is where we track bug requests. You posted it on the Godot-docs page which is where we track issues with the engine documentation.

It sounds like 1 and 2 are the same root cause, the gradient texture appears to be set to "repeat" instead of being set to "clamp".

**Comment by Calinou** [comment] 2022-04-08 16:05
Related to https://github.com/godotengine/godot/issues/56691 and https://github.com/godotengine/godot/issues/56886.

**Comment by MagnusL3D-code** [comment] 2022-04-09 11:43
This seem to happen with CurveTextures as well. Tried it on particles Scale and scaling them down over age but just before they de-spawn they'll popp back to start size.

**Comment by clayjohn** [comment] 2022-04-19 18:35
@fire-forge I opened a PR right before your comment (#60378) Please review when you have the chance!

**Comment by fire-forge** [comment] 2022-04-19 18:39
@clayjohn I was referring to the Gradient editor undo/redo bug. But I will try to review your PR anyways.

**Comment by clayjohn** [comment] 2022-04-19 18:41
@fire-forge Whoops! My bad. 

> But I will try to review your PR anyways.

Much appreciated :)

**Closed** 2022-04-24 17:37 UTC
Labels: bug, topic:rendering, confirmed
