### ISSUE TITLE
Code region is expanded on project relaunch

### ISSUE THREAD

**Issue by 0-Vanes-0** [godotengine/godot#85980] opened 2023-12-09 22:22 UTC
### Tested versions

4.2.stable;
code regions were introduced in this version

### System information

Godot v4.2.stable - Windows 10.0.19045 - GLES3 (Compatibility) - NVIDIA GeForce RTX 3050 Ti Laptop GPU (NVIDIA; 31.0.15.4617) - 12th Gen Intel(R) Core(TM) i5-12500H (16 Threads)

### Issue description

After creating a code region we can collapse it in a single line (same for functions that have arrows at the beginning of line).
However, if we reload the project, code regions are expanded, unlike with collapsed functions.
![image](https://github.com/godotengine/godot/assets/38129195/65c5956d-189a-4a80-9b75-fa94d954045d)
![image2](https://github.com/godotengine/godot/assets/38129195/d6b9603b-e819-47a6-932f-e7824332a164)

### Steps to reproduce

1. Write inside of any script a function e.g.
```
func some_function():
	pass
```
2. Write some code and create region e.g.
```
#region My setup code
func _ready() -> void:
	print_debug(self.name)
#endregion
```
3. Collapse both function and region with pressing arrow
4. Project -> Reload Current Project
5. Open your script after reload
6. Witness the function still collapsed AND the region expanded :/

### Minimal reproduction project (MRP)

N/A

**Comment by AThousandShips** [comment] 2023-12-09 22:34
Duplicate of https://github.com/godotengine/godot/issues/85780

**Closed by AThousandShips** 2023-12-09 22:34 UTC
