### ISSUE TITLE
Vulkan Mobile: Decals are not showing on meshes deformed using `vertex()` in a shader if far away from the AABB (unless Extra Cull Margin is increased)

### ISSUE THREAD

**Issue by jcarlosrc** [godotengine/godot#72614] opened 2023-02-02 16:45 UTC
### Godot version

4.0 beta 17

### System information

Ubuntu 22.04

### Issue description

Decals are not showing on a mesh deformed using the vertex() function in a shader. They show on the original mesh, not counting shader mesh deformations. This only happens in Vulkan mobile. Forward+ shows the decal correctly.

![Screenshot from 2023-02-02 11-43-44](https://user-images.githubusercontent.com/8985409/216387454-d6fb3bc8-e6ad-4917-a94b-adf292f2a473.png)

### Steps to reproduce

Create a Mobile project. Add a plane and a shader to deform it using the vertex() funcion.  Try to show a decal on the resulting surface.

### Minimal reproduction project

[decal_vertex_shader.zip](https://github.com/godotengine/godot/files/10571274/decal_vertex_shader.zip)

**Comment by Calinou** [comment] 2023-02-02 16:51
This is related to a culling issue, rather than a rendering issue. If you modify the shader to move all vertices downwards (closer to the mesh's AABB), rendering is correct:

![image](https://user-images.githubusercontent.com/180032/216389215-afe6eb03-63ad-41ab-93eb-606a98d1d364.png)

**Comment by jcarlosrc** [comment] 2023-02-02 16:57
Well, at least there is a inconsistency over how foward+ and mobile are behaving under the same conditions. Foward+ shows the decal.

**Comment by clayjohn** [comment] 2023-02-02 17:08
I also don't think this is a bug per se. Forward+ renderer and Mobile renderer work differently from each other. 

Namely the Forward+ renderer uses clustering to group together lights and decals into frustum-spaced bins. In the shader, we just have to take a fragments position in frustum-space to see what decals/lights impact it. 

The Mobile renderer has to know about all lights and decals up front. So it keeps track of which AABBs intersect each other so decals and lights can be assigned to MeshInstance at draw time. 

When using vertex displacement, you need to increase the size of your AABB to account for the changes you make in the shader. Not only is it necessary for proper lighting/decals. It is necessary for proper culling. 

Take a look at what happens when you move your camera slightly:

![Screenshot from 2023-02-02 09-06-53](https://user-images.githubusercontent.com/16521339/216393310-dc570588-d84a-4a19-b39a-f2ab9f971c20.png)
![Screenshot from 2023-02-02 09-06-50](https://user-images.githubusercontent.com/16521339/216393320-c0843b9d-bfd4-43fa-beea-7b31edfaeabb.png)

As you see, a tiny movement of the camera caused the entire terrain to disappear because the AABB no longer intersects the camera frustum.

**Comment by BastiaanOlij** [comment] 2023-02-02 22:57
Note also that if you have a heightmap, and you deform the vertices in the shader, you have to make sure the AABB encompasses the end result properly. Godot can't do this for you as it can't predict the outcome of the vertex shader on the CPU (kind of defies the point).

Decals not showing is only a small part of the problems that ensues if you do not set a proper AABB manually. Just put your camera above your height map so it would only see the peaks. Your terrain will disappear because the AABB is not visible, as the culling still thinks you're dealing with a flat plane.

This is definitely a documentation issue, not a bug.

**Comment by jcarlosrc** [comment] 2023-02-03 16:30
Got it, it makes sense. Thanks.

**Closed** 2023-02-04 18:36 UTC
Labels: topic:rendering, documentation, topic:3d
