### ISSUE TITLE
Vulkan: Polygon2D disapears once skeleton is added

### ISSUE THREAD

**Issue by jonSP12** [godotengine/godot#60724] opened 2022-05-03 11:06 UTC
### Godot version

v4.0-alpha7

### System information

Windows10 Vulkan

### Issue description

the polygon2D disapears once the skeleton2D is added
![err01](https://user-images.githubusercontent.com/77213594/166441730-f9e74172-c7cc-4061-a634-5731c21c821e.png)

### Steps to reproduce

add a polygon2D, a sprite texture,
add vertexs around the sprite and 4 internal vertexs, 
connect the dots in polygons

add a sekelton2D with bones ( the image disapears )
connect the bones to the polygons
![err02](https://user-images.githubusercontent.com/77213594/166442225-31bd1b29-071e-4987-b881-139d74541136.png)

### Minimal reproduction project

https://drive.google.com/file/d/1yeqa3hYPK6PuIki8pxtLnMib9q2hssgh/view?usp=sharing

**Comment by Calinou** [comment] 2022-05-03 17:46
Duplicate of https://github.com/godotengine/godot/issues/59451.

**Closed by Calinou** 2022-05-03 17:46 UTC
Labels: bug, topic:rendering, regression, topic:2d
