### ISSUE TITLE
GDScript Parser Bug: Exported projects have case sensitive paths in GDScript, but the editor does not?

### ISSUE THREAD

**Issue by Gamepro5** [godotengine/godot#68230] opened 2022-11-03 19:39 UTC
### Godot version

4.0 Beta 4 (or a custom build of godot using the latest branch)

### System information

Windows 10; AMD Ryzen 7 3700X 8-Core Processor 3.60 GHz

### Issue description

The export preset for versions after beta 3 are broken for windows. They are unable to understand GDScript. I don't get this issue when running the project from the editor, and don't get the issue from exporting in Godot beta 3.
![image](https://user-images.githubusercontent.com/23440295/199818419-70fd6531-9939-4bbc-87c3-5e53ab9ea190.png)
The game then lags out my operating system and crashes after a short while. The crashing happens in the editor too.

The reason why this issue happens is because, while in the editor, the path doesn't seem to be case sensitive for some reason. When exporting to windows, however, it does become case sensitive. This causes a parsing error because the GDscript presumably can't convert this path into something that makes sense in the windows filesystem.

Suggested fix would be to make the Godot in-editor file system case sensitive.

### Steps to reproduce

1. Export the project
2. Run the project by using the .cmd file
3. See the error.

### Minimal reproduction project
[GDScriptParserBug.zip](https://github.com/godotengine/godot/files/9932456/GDScriptParserBug.zip)

**Comment by Calinou** [comment] 2022-11-04 19:53
Duplicate of https://github.com/godotengine/godot/issues/24107.

**Closed by Calinou** 2022-11-04 19:53 UTC
