### ISSUE TITLE
Issue with contextual shortcuts can lead to loss of data

### ISSUE THREAD

**Issue by noidexe** [godotengine/godot#41883] opened 2020-09-08 17:00 UTC
**Godot version:**
3.2.2

**OS/device including version:**
Any OS

**Issue description:**
In the editor, some shortcuts do more than one thing depending on context. For example Ctrl+D can duplicate nodes, keyframes or lines of code. Delete can delete keyframes, files or nodes. 
Sometimes Godot fails to identify the right context. Some examples:
Ctrl-D to duplicate a keyframe and a line of code gets duplicated. Easy to miss if it doesn't immediately break the script, can be hard to debug otherwise.
Ctrl-D to duplicate a keyframe and a node gets duplicated. Again this this easy to miss and can cause trouble. 
Delete to detele a keyframe and a file/node gets deleted. This gives you a warning but again it is easy to miss it, especially if you are a beginner. 

It also happens for other shortcuts and in other context but I'm not sure how to reproduce it consistently

**Comment by Calinou** [comment] 2020-09-08 18:23
Duplicate of https://github.com/godotengine/godot/issues/36205.

**Closed by Calinou** 2020-09-08 18:23 UTC
Labels: bug, topic:editor
