### ISSUE TITLE
Settings from subresources are not being saved, and don't show up when playing project

### ISSUE THREAD

**Issue by jahd2602** [godotengine/godot#19984] opened 2018-07-05 14:38 UTC
**Godot version:**
master @ 92bfde531cea21555dc74ad928a79120fbc9c34d

**OS/device including version:**
Windows 10 Home Version 1803 Build 17134.147
Processor i9-8950HK
Nvidia GTX 1050 Ti

**Issue description:**
The settings that appear when clicking in an arrow only work in the editor, they are not applied when playing the game, and also those settings are not being saved. For example, I enabled repeat for the texture, the repeating shows in the editor, but not in-game, and when I save, close and reopen the scene, the repeat checkbox is unchecked.
![](https://i.imgur.com/tmAXxAe.jpg)

**Steps to reproduce:**
1. Create polygon2D
2. Assign texture
3. Enable repeat
4. When playing, the repeating has no effect
5. When saving, closing, and reopening the scene, repeat is disabled, when it should be enabled

**Comment by vnen** [comment] 2018-07-05 15:35
AFAIK this is an issue with textures in general (not particularly sub-resources). Textures tend to use only their import settings.

**Comment by jahd2602** [comment] 2018-07-05 17:16
Yes, but that means that you'd need to duplicate the texture to use different flags in different places, and also it is not intuitive as now it shows the flags as independent from the import settings.
Also, the Make Unique option doesn't seem to fix the issue either.

**Comment by vnen** [comment] 2018-07-05 19:12
What I mean is that it's not related to saving sub-resources, unless you have this issue with other resource types as well. If the problem is only the texture properties, then this is a duplicate of #17550.

**Comment by AlexHolly** [comment] 2018-07-06 02:02
I have a similar same issue. Flags are not saved on Node "Button"->Icon, load a .png from filesystem.

**Comment by jahd2602** [comment] 2018-07-06 14:39
That means the issue is with the new inspector, and not specifically with textures. Note that with the previous inspector, those settings were working fine.

**Comment by ibrahn** [comment] 2018-07-11 15:55
Had something similar with a ShaderMaterial.
The material is a tres with the shader code as a subresource within it.
Editing the shader didn't mark the material as changed, so ctrl-s saved nothing and no "unsaved changes" warning is displayed when quitting the editor.

**Comment by ordigdug** [comment] 2018-07-13 18:51
@jahd2602 When in the inspector in v3.0.5 there is an warning message "Changes may be lost!" and if you click on it "Alert! This resource was imported, so it's not editable. Change its settings in the import panel and then re-import." So what version did this work in previously?

**Comment by jahd2602** [comment] 2018-07-13 19:44
@ordigdug It was working in v3.0.2, I never saw that alert.

> Change its settings in the import panel and then re-import.
And if you want some setting for one usage and a different setting for another usage? You would need to duplicate the asset which is not ideal.

**Comment by Wiadomy** [comment] 2018-09-03 15:41
I have the same issue.

**Comment by AlexHolly** [comment] 2018-09-03 15:54
As a workaround use the Import Tab to reimport the Image
![image](https://user-images.githubusercontent.com/4741886/44995216-54f97f00-afa2-11e8-8136-87e68eced3bd.png)

**Comment by Calinou** [comment] 2021-09-03 21:38
Closing per @AlexHolly's comment. I think this was reported in another issue already, but this was resolved in 4.0 as texture flags are no longer stored in the texture but in the place where they are used instead. This behavior relies on Vulkan bindless textures and isn't available in GLES 3.0/2.0, so it can't be backported to `3.x`.

**Closed by Calinou** 2021-09-03 21:38 UTC
Labels: enhancement, topic:editor, usability
