### ISSUE TITLE
GDScript 2.0: GODOT4-beta3--when I was extend script,  the extend script reported an error

### ISSUE THREAD

**Issue by DJRockTime** [godotengine/godot#67555] opened 2022-10-17 21:55 UTC
### Godot version

GODOT4.0-beta3

### System information

Window10 

### Issue description

I created the parent script and then the inheritance script. In the child script, the extend script reported an error

 editor/script_create_dialog.cpp:379 - Parameter "type" is null.

### Steps to reproduce

![微信图片_20221018055022](https://user-images.githubusercontent.com/38347978/196290544-d1a5cdde-2501-44e7-a0ec-49dcdd7b42c0.jpg)
<img width="1284" alt="微信图片_20221018055414" src="https://user-images.githubusercontent.com/38347978/196291115-65f80844-dca3-4232-bc07-a9518cdda5e4.png">

**Comment by Calinou** [comment] 2022-10-17 22:40
@DJRockTime Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

**Comment by KoBeWi** [comment] 2022-11-06 01:05
Duplicate of #65827

**Closed by KoBeWi** 2022-11-06 01:05 UTC
Labels: bug, topic:editor, needs testing
