### ISSUE TITLE
The script debugger is totally broken after thread started from gdscript

### ISSUE THREAD

**Issue by Geequlim** [godotengine/godot#19809] opened 2018-06-27 17:51 UTC
**Godot version:**

Godot 3.1 compiled with 07af826051ffe5b8500e60ed1a6d53d24a1771cd

**OS/device including version:**

Arch Linux x64

**Issue description:**

The debugger client cannot send any kind of message to the remote debugger after breakpoint triggered.

![2018-06-28 01-48-57](https://user-images.githubusercontent.com/6964556/41990604-783b1490-7a75-11e8-9500-94623b06f487.png)

Empty stack dump. No error meessage.
It do nothing with step into and step out or continue button.

**Steps to reproduce:**

* Press F9 in script editor to set a breakpoint
* Click run button in godot editor to start the debugger

**Minimal reproduction project:**

**Comment by Geequlim** [comment] 2018-06-27 17:55
With debug the C++ code for both the debugger client and the remote debugger.
The remote debugger can't recive any message from the debugger client.
https://github.com/godotengine/godot/blob/68f7cf13c7326c077cc6ff8a6a267ae2610c4519/core/script_debugger_remote.cpp#L183-L192

The `packet_peer_stream->get_available_packet_count()` always returns 0.

**Comment by vnen** [comment] 2018-06-27 19:10
Is this a recent thing? It works for me but my build is a bit old.

**Comment by reduz** [comment] 2018-09-07 18:43
Multi threaded GDScript debugging is yet again kicked forward :(

**Comment by akien-mga** [comment] 2020-01-07 14:24
Duplicate of #2446.

**Closed by akien-mga** 2020-01-07 14:24 UTC
Labels: bug, topic:editor
