### ISSUE TITLE
Cannot open AssetLib and build templates

### ISSUE THREAD

**Issue by CaptainDario** [godotengine/godot#37045] opened 2020-03-14 13:07 UTC
**Godot version:**
Godot 3.2 stable official

**OS/device including version:**
Manjaro i3 
**cat /etc/lsb-release:**
DISTRIB_ID=ManjaroLinux
DISTRIB_RELEASE=19.0.2
DISTRIB_CODENAME=Kyria
DISTRIB_DESCRIPTION="Manjaro Linux"

**Issue description:**
Whenever I open the AssetLib tab it does only show "Loading..." and never actually finishes or crashes. When starting Godot from the command line there is no output too.

**Steps to reproduce:**
1. Open Godot
2. Click on the AssetLib tab

**Minimal reproduction project:**
Does never work even with an empty project.

**Comment by CaptainDario** [comment] 2020-03-14 18:29
Just downloaded 3.2.1 on the same system and the problem persists.

**Comment by Calinou** [comment] 2020-03-14 20:17
The cause could be similar to #36418.

**Comment by CaptainDario** [comment] 2020-03-14 21:04
Thanks for the reply.
I did the ping from #36418f and got this result:
```
ping godotengine.org
PING godotengine.org(web.tuxfamily.net (2a02:2178:1000:201::4)) 56 data bytes
--- godotengine.org ping statistics ---
5 packets transmitted, 0 received, 100% packet loss, time 4062ms

ping -4 godotengine.org
PING godotengine.org (212.85.158.4) 56(84) bytes of data.
64 bytes from web.tuxfamily.net (212.85.158.4): icmp_seq=1 ttl=48 time=42.4 ms
^C
--- godotengine.org ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 42.413/42.413/42.413/0.000 ms

```
Manjaro uses piv6 as default so I guess my ipv6 connection is somehow broken too :(

**Comment by Calinou** [comment] 2020-03-14 21:39
Thanks for confirming this! I'll close this as a duplicate of #36418 then.

**Closed by Calinou** 2020-03-14 21:39 UTC
Labels: bug, topic:assetlib, topic:editor
