### ISSUE TITLE
AnimatedSprite2D animation frame previews are displayed without regard to the selected filter

### ISSUE THREAD

**Issue by lufog** [godotengine/godot#57550] opened 2022-02-02 14:08 UTC
### Godot version

v4.0.alpha.custom_build (bf12719cc)

### System information

Windows 11, Geforce 1660

### Issue description

In 4.x previews are blurry, although the sprite is displayed correctly on the scene.

https://user-images.githubusercontent.com/10379487/152166892-b03eb757-7c3d-4ac1-b13f-ee4cc60fe72a.mp4

In 3.x previews are crisp:

![image](https://user-images.githubusercontent.com/10379487/152167120-05e84752-ed9a-4f70-b101-d37348a6f3a8.png)

### Steps to reproduce

-open bat scene;
-select AnimatedSprite2D node.

### Minimal reproduction project

[PreviewTest_G4.zip](https://github.com/godotengine/godot/files/7987096/PreviewTest_G4.zip)

*Bugsquad edit (keywords for easier searching): SpriteFrames, nearest, nearest-neighbor*

**Comment by sakunix** [comment] 2022-10-19 21:20
Godot4.beta3 ,  debian
![imagen](https://user-images.githubusercontent.com/22086570/196806083-31c6bf79-94b5-4a5f-8752-58d5e369c861.png)

**Comment by carnifexx** [comment] 2022-12-10 19:15
I already collected Screenshots to report this, its really annoying ty for that
(but its called "AnimatedSprite2D" not "AnimationSprite2D" in the title though)
The sprite frames from AnimatedSprite2D in the AnimationPlayer have the same Issue.

**Comment by akien-mga** [comment] 2023-02-14 14:08
Still reproducible in 4.0 RC 2.

**Comment by naturally-intelligent** [comment] 2023-02-21 17:48
Have this same issue in rc3 although it's not a big deal.

More problematic for me is losing SpriteFrames from 3-to-4 conversion.

Does anyone know how to keep SpriteFrame data from v3?

https://godotforums.org/d/32908-animatedsprite2d-spriteframes-lost-from-3-to-4-conversion

**Comment by Calinou** [comment] 2023-02-21 18:37
@naturally-intelligent Please continue the discussion in https://github.com/godotengine/godot/issues/73696.

**Comment by elvisish** [comment] 2023-04-10 20:13
Still an issue in 4.0.2 stable.

**Comment by dalexeev** [comment] 2023-05-22 12:18
Duplicate of #74337, fixed by #74341.

**Closed** 2023-05-22 12:22 UTC
Labels: bug, topic:editor, confirmed, usability, regression, topic:animation, topic:2d

**Comment by akien-mga** [comment] 2023-05-22 12:24
Technically, #74341 is more of a workaround as it's not respecting the filter configured for the resource. So it solves the symptoms most users will face doing pixel art projects, but might not cut it for games which actually need filtering.

Anyway, we can consider this fixed and see if anyone complains about the new default filtering.

**Comment by carnifexx** [comment] 2023-06-28 19:40
just wanted to confirm as well, seemed to be fixed now in 4.1 RC1, awesome work
![blurry_fixed](https://github.com/godotengine/godot/assets/844546/afa2a570-f6ad-4ac9-905e-a7a1417f303e)
