### ISSUE TITLE
Problem with selection in tilemap node and zoom

### ISSUE THREAD

**Issue by Torguen** [godotengine/godot#55194] opened 2021-11-21 12:44 UTC
### Godot version

3.4 stable mono

### System information

w10 64

### Issue description

The tilemap node does not allow you to select individual tiles if the zoom level is 1.
To solve this you have to apply zoom or press the "1" button, then now the purple box appears and the individual tiles can be selected.

https://user-images.githubusercontent.com/19652075/142762306-6588ec5d-5686-435b-a342-2c383a8a7083.mp4

### Steps to reproduce

see the video

### Minimal reproduction project

...

**Comment by Calinou** [comment] 2021-11-21 13:13
Duplicate of https://github.com/godotengine/godot/issues/54691.

**Closed by Calinou** 2021-11-21 13:13 UTC
Labels: bug, topic:editor, topic:2d
