### ISSUE TITLE
[TextEdit]TextEdit‘s background_color can not set to transparent.

### ISSUE THREAD

**Issue by Atem1995** [godotengine/godot#63531] opened 2022-07-27 12:01 UTC
### Godot version

3.x

### System information

window 10

### Issue description

TextEdit‘s background_color can not set to transparent
![捕获](https://user-images.githubusercontent.com/52338846/181241435-686b803f-2a00-4336-bb0b-b2fbdca40a1f.PNG)
.

### Steps to reproduce

Add a TextEdit Node and change the theme overrides's background color, but it still has color and overlays other textures.

**Comment by Paulb23** [comment] 2022-07-27 16:02
Duplicate of #52482

**Closed by Paulb23** 2022-07-27 16:02 UTC
