### ISSUE TITLE
"Editable Children" of instanced scenes' export variables not updated during duplication

### ISSUE THREAD

**Issue by willnationsdev** [godotengine/godot#12075] opened 2017-10-13 15:02 UTC
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Windows 10
Godot 3.0, commit d5189d2 from Calinou's builds

**Issue description:**
I added a sub-scene to another scene. I then edited the properties of children in the sub-scene after exposing the children using the "Editable Children" flag. When duplicating the root node of the sub-scene with `duplicate()`, default parameters, the generated children, but not the root node that was used to call `duplicate()`, were created with initialization values rather than the design-time values assigned.

If the children themselves are duplicated directly, then the values are set properly, but if you duplicate the root of the instanced scene, their children are not updated.

**Steps to reproduce:**
1. Create a scene with a root Node 'parent' and child Node 'child'
2. Add a script to 'child' with an exported variable.
3. Create a scene with a root Node 'root'. Then add an instance of scene 1 as a child of node 'root'.
4. Expose the children of the instanced scene using the "Editable Children" flag.
5. Change the value of the 'child' node's exported variable.
6. Add a script to the 'root' node. In the ready function, duplicate 'parent' and compare the value of its 'child' node's exported variable to the original's exported value which you explicitly assigned. They will be different.

**Link to minimal example project:**
[InstancedSceneDuplicatedExportValueFailureTest.zip](https://github.com/godotengine/godot/files/1382994/InstancedSceneDuplicatedExportValueFailureTest.zip)

"a" and "b" in this picture are exported bools that default to `true`, but have all been manually assigned `false` from the editor at design-time.

![exportvarfailure](https://user-images.githubusercontent.com/16217563/31552601-92ccdc46-affd-11e7-9f48-35de6dae8510.PNG)

**Comment by willnationsdev** [comment] 2017-10-13 15:16
As far as I understand it, these design-time values for editable children are recorded in the *.tscn file. Doesn't that mean that, when duplicating a node that is the root of an instanced scene, we have to then recursively dive into any instanced scenes to see if the duplicated nodes' exports have been edited, and then continue chaining back up until you finally evaluate the currently running scene? After all, I could instance a scene that is already instancing another scene with edited children from a 3rd scene (and its instanced scenes' nodes and so on).

**Comment by willnationsdev** [comment] 2017-10-13 15:48
Examining the code (`scene/main/node.cpp: lines 2067-2158`, method name `_duplicate`. It seems as though, in the case of duplicating a node that is the root of an instanced scene, it...

1. instances all of the necessary nodes
2. copies over their scripts, groups, and/or signals based on flags (so all of them for this bug scenario)
3. examines the children, but then checks `if (instanced && get_child(i)->data.owner == this)` and `continue`s, doing nothing since it is trying to do further recursive duplications.

At the end of the function, we need to check for the `DUPLICATE_USE_INSTANCING` flag again and, if true, compare the `node` return value's PackedScene representation with the original node's `data.instance_state` in order to make sure the exact state gets copied over to the new instanced scene.

I would make the fix myself, but I've been having trouble getting Godot to compile on my machine.

**Comment by reduz** [comment] 2017-10-20 20:59
is this duplication in editor or in run-time?

**Comment by willnationsdev** [comment] 2017-10-20 22:18
@reduz the export values are defined in the editor, but the duplicate function is called at runtime. It is the return value of that duplicate function which contains the nodes where the children do not have the same values as their original equivalents. The root node will have the same values however.

**Comment by kedodrill** [comment] 2020-05-14 21:12
I think I might be having the same issue. I know this is old, so it could be something different.
Anyways, I am making a small JRPG, with turn-based combat. Everything so far is pretty modular - my similar issue here is that I have a Skill node that I'm trying to reuse using exported vars, and each party member has editable children.

![godot](https://user-images.githubusercontent.com/41304094/81986412-c1e16b00-9605-11ea-8ef2-f1003024290f.png)

In the output, the first two numbers (2 and 2) are the values before duplication. The 0 and 0 are after duplication. I have a custom Copy() function that duplicates the required node...what's interesting is that the 2 and 2 values are there until I add this copy to another node using AddChild().

Possible that C# has anything to do with this if it's not the same as this issue? Let me know if other information is required...

**Comment by kedodrill** [comment] 2020-05-15 02:52
@willnationsdev Could you share how you got around this? I've tried copying the values over from a previous script, but they always reset...

**Comment by KoBeWi** [comment] 2020-10-25 22:21
This seems to be fixed in 3.2.3
The reproduction project prints all `false` when running test3.tscn

**Closed by KoBeWi** 2020-10-25 22:21 UTC
Labels: bug, topic:editor

**Comment by hsandt** [comment] 2021-07-10 22:13
Wow, I found a more complex case still not fixed in 3.2.3, with exactly the same case as @kedodrill since I'm using the Godot Open RPG Template, where all data is defined via scene objects, and duplicating a PartyMember will lose custom children defining Skills, etc.

**Deep scene instance editable children do not preserve exported variables nor their own children on duplication of parent scene instance**

This means that if the scene you instantiate as parent object ParentPrefab contains another scene instance of SubPrefab, the exported variables and own children of the editable children under the SubPrefab instance will not be duplicated.

In the OP's case that will show with exported variables, in the Open RPG case this will show with children. But I believe the cause is the same:

**Editable Children flag of scene instance under scene instance is not copied on duplication of parent scene instance**

This means the sub-scene instance will not be expanded after duplication, and this has the same effect as unchecking "Editable Children", as explained by the warning popup: "Disabling "editable_instance" will cause all properties of the node to be reverted to their default." which includes exported variables and custom children.

Checking Editable Children on them is too late, and the custom properties/children do not reappear.

Here are the repro steps for an empty project:

1. Create a scene with a root Node2D 'SubPrefab' and a Node2D child 'SubPrefabChild' (it's the only node where the type matters, as using a Node2D allows you change Transform). Save the scene as 'SubPrefab.tscn'. No need for scripts, we'll just use Transform to demonstrate.
2. Create a scene with a root Node2D 'ParentPrefab' and instantiate a 'SubPrefab' node as child under 'ParentPrefab'. Save the scene as 'ParentPrefab.tscn'.
3. Create a new scene and instantiate a 'ParentPrefab.tscn' node.
4. Right-click and check "Editable Children" on the ParentPrefab instance.
5. Right-click and check "Editable Children" again, but on the SubPrefab instance now revealed.
6. We'll now modify things on the SubPrefabChild now revealed: click on it and set the Transform position X to 1 (assuming it was 0). If you used another node type, you can just set the Process Priority instead.
7. Also add some node of any type as child of the SubPrefabChild instance, named 'MUST BE COPIED'.
8. Duplicate ParentPrefab.
9. Note that the copy ParentPrefab2 is immediately expanded with "Editable Children" checked. However, the instance of SubPrefab is not. Now check "Editable Children on the instance of SubPrefab".
10. It's too late, the node "MUIST BE COPIED" is missing and the Transfrom position X of SubPrefabChild is back to 0.

Or, if you copy https://github.com/GDquest/godot-open-rpg:

1-7. Just open res://src/party/Party.tscn
8. Duplicate Godette or Robi
9. Note that Battler is not expanded. Check "Editable Children" on it.
10. It's too late, custom Skill children and other nodes are missing.

**Comment by hsandt** [comment] 2021-07-10 22:14
Do you need me to open another ticket just for the Deep Scene Instance case, or do you consider it should have been part of this issue and will reopen this ticket to work on it directly?

**Comment by KoBeWi** [comment] 2021-07-10 22:15
I think at this point it's better to open a new issue.
