### ISSUE TITLE
Godot 3.0.2 crashes due to simple fragment shader (minimal project included)

### ISSUE THREAD

**Issue by viktor-ferenczi** [godotengine/godot#17269] opened 2018-03-05 01:36 UTC
**Godot version:** 3.0.2

**OS/device including version:** Windows 10 Pro 64 bit, geForce 1080, latest nVidia driver

**Issue description:**

Added shader material to a label which renders with a 100px dynamic font. A single 0 character was rendered.

Entered code into shader editor:

```
shader_type canvas_item;

uniform vec4 outline_color = vec4(0.0);

void fragment() {
	COLOR = vec4(0.0);
}
```

Godot editor crashed when I entered the following line and pressed Ctrl-S:

`uniform vec4 outline_color = vec4(0.0);`

It crashed again on loading the project. Had to revert the scene file to get it back operational.

Also figured that Godot actually crashes when opening the scene with the shader code in it. If that reopens by default, then it crashes right on startup.

**Steps to reproduce:**

- Create new project
- Switch to 2D view
- Add a label node directly to the scene with text "0"
- Add a theme to the label node
- Set a the default font to a dynamic font of 100px size
- Add shader material to the label node
- Enter the above shader code
- Press Ctrl-S
- Crash

**Minimal reproduction project:**
https://www.dropbox.com/s/lsdrbujoejtzr7u/CrashRepro1.zip?dl=1

**Comment by Smellyhobo101** [comment] 2018-03-05 03:15
I don't think you're meant to assign variables to uniforms in the fragment shader itself. You just declare them at the top, and then you set the values in the ShaderMaterial.

**Comment by viktor-ferenczi** [comment] 2018-03-05 09:22
The `vec4(0.0)` is supposed to be the default value.

This works without crashing:
`uniform float outline_width = 0.0;`

This also works without crashing:
`uniform vec4 outline_color : hint_color;`

**Comment by akien-mga** [comment] 2018-03-05 10:02
Thanks for the report, that's a duplicate of #15166.

**Closed by akien-mga** 2018-03-05 10:02 UTC

**Comment by MrAnima** [comment] 2018-09-27 18:05
Hello, I'm having this exact same problem in _v3.0.6.stable.official.8314054_ downloaded from Steam. Godot crashes when I add a semi-column to a uniform definition line and hit Ctrl+S (and only in this case, never when I do it elsewhere or change anything else). The software crashes with no message whatsoever.

Here's the file:
```glsl
shader_type spatial;

uniform vec4 br : hint_color = vec4(0) // Adding a semi-column here makes the whole software close with no warning

void fragment() {
	int e = 0; // I added this to see if it would crash, and it doesn't
}
```

**Comment by Zireael07** [comment] 2018-09-27 18:13
"semi-column"? I think you meant semi-colon. aka ;

**Comment by MrAnima** [comment] 2018-09-27 18:19
Obviously :laughing:
