### ISSUE TITLE
CollisionShape3D don't have "grabbable" points in OpenGL 3

### ISSUE THREAD

**Issue by Fantoser** [godotengine/godot#75481] opened 2023-03-29 23:52 UTC
### Godot version

v4.0.rc1.official [8843d9ad3]

### System information

Windows 10, GLES3, NVIDIA GeForce GTS 450

### Issue description

CollisionShape3D in Compatibility renderer don't have "grabbable" points used for resizing. 
Also tested on a different Vulkan compatible device and the result is the same.

The same issue still present on v4.0.stable.official [92bee43ad]  and v4.0.1.stable.official [cacf49999]

![image](https://user-images.githubusercontent.com/29687518/228691136-8250cb1f-dbf7-4631-b55a-0c3da1e3aabb.png)

### Steps to reproduce

- Change renderer to Compatibility
- Create a CollisionShape3D
- Change shape to box/capsule/cylinder
- Select it

### Minimal reproduction project

[No_grabbables.zip](https://github.com/godotengine/godot/files/11106435/No_grabbables.zip)

**Comment by Calinou** [comment] 2023-03-30 00:15
- Duplicate of https://github.com/godotengine/godot/issues/74005 (fixed by https://github.com/godotengine/godot/pull/73966, which will be in 4.0.2).

**Closed by Calinou** 2023-03-30 00:15 UTC

**Comment by Zireael07** [comment] 2023-03-30 06:40
@Calinou Someone recently reported collision shape point being a single pixel (sorry can''t find issue number now), could this be yet another duplicate of #74005 too

**Comment by Calinou** [comment] 2023-03-30 16:06
> @Calinou Someone recently reported collision shape point being a single pixel (sorry can''t find issue number now), could this be yet another duplicate of #74005 too

Yes, it's due to point size not being passed correctly in OpenGL (so it's always 1).
