### ISSUE TITLE
Godot 4 ignores TAB key in the editor

### ISSUE THREAD

**Issue by Rinocrosser** [godotengine/godot#57115] opened 2022-01-24 10:38 UTC
### Godot version

4.0 Alpha 1

### System information

Windows 10 64-Bit

### Issue description

To edit multiple values or objects one after another it's very common to use TAB key to switch between them, instead of using the mouse, which is much slower. But somewhy, TAB isn't working in Godot 4.0 Alpha 1.

### Steps to reproduce

Open any editable value, for example, Transform tab or UV-scale, start editing one value, try to switch to another with TAB-key.

![image](https://user-images.githubusercontent.com/19660324/150767833-5e59e300-a46c-400e-a995-aea27bf6193e.png)

**Comment by bruvzg** [comment] 2022-01-24 11:24
Seems like it's not editor specific, `Tab` switching is also not working in the project UI.

**Comment by akien-mga** [comment] 2022-01-24 11:38
Duplicate of #54602

**Closed by akien-mga** 2022-01-24 11:38 UTC
Labels: bug, topic:input, topic:gui

**Comment by Rinocrosser** [comment] 2022-01-24 12:04
> Duplicate of #54602

Wow, I haven't scrolled back that far, but how on earth that pretty obvious issue haven't been fixed since November 4, it's almost three month ago? And it's definitely a daily usage pain for everyone.

**Comment by akien-mga** [comment] 2022-01-24 12:13
We're aware of the bug, but fixing bugs *correctly* takes time. There's a PR that might fix that issue but it's awaiting review from contributors who are competent with that very core code path. We don't rush things in Godot development, even if it means that known bugs stay unsolved for month. Please remember that this is an **alpha** build, and that bugs are expected.

**Comment by Rinocrosser** [comment] 2022-01-24 12:37
> We're aware of the bug, but fixing bugs _correctly_ takes time. There's a PR that might fix that issue but it's awaiting review from contributors who are competent with that very core code path. We don't rush things in Godot development, even if it means that known bugs stay unsolved for months in the development branch. Please remember that this is an **alpha** build, and that bugs are expected.

Sure, gonna wait for the fix.
