### ISSUE TITLE
Editor Scene Tree Sprites Not Updated After Type Change

### ISSUE THREAD

**Issue by wez470** [godotengine/godot#80969] opened 2023-08-24 18:19 UTC
### Godot version

v4.1.stable.official [970459615]

### System information

Godot v4.1.stable - Windows 10.0.22000 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 2070 SUPER (NVIDIA; 31.0.15.3713) - Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz (8 Threads)

### Issue description

Unfortunately I can't find a way to get this to reproduce consistently, but sometimes when changing the type of an object, the editor sprite displayed for the object type will remain the same as the previous type. The type itself is properly updated. A video shows this problem. The object starts as a CharacterBody2D, with the properly displayed CharacterBody2D sprite. Then I change its type to be of Node2D. The editor sprite remains the CharacterBody2D one, though when we hover over the object, it correctly identifies its type as Node2D. Closing and re-opening the scene does not fix the editor sprite.

https://github.com/godotengine/godot/assets/4305699/583b4c1d-21c4-4be4-ad24-cf91b9e3746f

### Steps to reproduce

I'm not entirely sure how to consistently reproduce this issue unfortunately. I've tried creating brand new scenes and changing their types and it seems to work fine when I do that. I've ran into this about 3-4 times in the past couple weeks now (all on 4.1) however.

### Minimal reproduction project

None

**Comment by AThousandShips** [comment] 2023-08-24 18:22
Duplicate of #80733

**Closed by AThousandShips** 2023-08-24 18:22 UTC

**Comment by wez470** [comment] 2023-08-24 18:23
Ah, sorry. I looked a bit for an existing issue but didn't see that one.

**Comment by AThousandShips** [comment] 2023-08-24 18:25
The images for the nodes are called "icons" that's probably what made the search confusing for you
