### ISSUE TITLE
Default path when creating text files

### ISSUE THREAD

**Issue by manolocanton** [godotengine/godot#70928] opened 2023-01-04 21:23 UTC
### Godot version

4.0.beta10.official [d0398f62f]

### System information

Windows 10

### Issue description

I've been watching this for a while and seeing how the creation of scenes and scripts works, I think it's not right to create a text file in the project root folder by default instead of the selected one.

### Steps to reproduce

1. Create a new TextFile... on FileSystem dock using right-click menu.
2. Note that the "New Text File..." window starts at the root folder of the project.

### Minimal reproduction project

N/A

**Comment by Cretezy** [comment] 2023-01-04 21:32
I agree this also doesn't seem right. Here's a video example:

https://user-images.githubusercontent.com/2672503/210653843-d12c1405-46ae-4925-886e-7de4515b15eb.mp4

I'll take a poke at this shortly.

**Comment by Paulb23** [comment] 2023-01-04 21:39
Duplicate of #63200

**Closed by Paulb23** 2023-01-04 21:39 UTC
