### ISSUE TITLE
C# Export members no more initialized

### ISSUE THREAD

**Issue by ZwieBit** [godotengine/godot#54414] opened 2021-10-30 09:59 UTC
### Godot version

3.4 RC2 / Mono

### System information

Windows 11, Intel 655

### Issue description

Opening my existing project in the editor shows all variables initialized.

![variables1](https://user-images.githubusercontent.com/25595246/139528429-46f9b987-dd23-422e-92da-84a94dab64d8.png)

Starting the project gives me errors because they are actually set to zero.

Upon closing and opening the scene all variables are actually set to zero.

![variables2](https://user-images.githubusercontent.com/25595246/139528447-580d7cc6-0bee-4835-9170-4b4342c4231e.png)

Even assigning new values and saving the scene has no effect.

Maybe this is related to 
https://github.com/godotengine/godot/pull/54199 ? (Keep order of c# export members)

### Steps to reproduce

Having a RC1 Project with export members, open the scene and run it - everything is not initialized. In RC1 everything works fine but variables are displayed unordered:

![image](https://user-images.githubusercontent.com/25595246/139528582-ed010ec8-0417-4a6a-bbdf-2becfd1882b4.png)

**Comment by raulsntos** [comment] 2021-10-30 11:55
I can't reproduce this issue, can you upload a minimal reproduction project?

This could be related to #37812 and/or #51626 but both of those issues already existed before 3.4 RC2. Are you sure you couldn't reproduce it in RC1? The PR you mentioned shouldn't be causing this issue and don't see any commits between RC1 and RC2 that could be causing this.

**Comment by ZwieBit** [comment] 2021-10-30 11:58
I'll try to create a minimal project. Currently i'm working with RC1 without any issues and as soon as i switch to RC2 it's not.

**Comment by ZwieBit** [comment] 2021-10-30 12:10
[ExportTest.zip](https://github.com/godotengine/godot/files/7446457/ExportTest.zip)

Actually it seems related to [Tool] - When i open the project with RC1 i can change the variable and it is reflected by a program start (GD Print Output). If i open it with RC2 i can change it, but it will stay to 0.

**Comment by raulsntos** [comment] 2021-10-30 12:19
I can reproduce this with 3.4 beta 6 so I think your issue is not specific to RC2, what I also noticed is your scene looks like this:

```ini
[gd_scene load_steps=2 format=2]

[ext_resource path="res://SpatialTest.cs" type="Script" id=1]

[node name="Spatial" type="Spatial"]
SomeVariable = 4
script = ExtResource( 1 )
```

When opening the scene in Godot, `SomeVariable` value is 0 but if you move `SomeVariable` below the `script` like this:

```ini
[gd_scene load_steps=2 format=2]

[ext_resource path="res://SpatialTest.cs" type="Script" id=1]

[node name="Spatial" type="Spatial"]
script = ExtResource( 1 )
SomeVariable = 4
```

Then it seems to work fine, so I guess the problem is due to the order in which the scene is deserialized. I don't know how the scene ended up being serialized in that order though.

**Comment by ZwieBit** [comment] 2021-10-30 12:30
After removing [Tool] it also works fine in my main project in RC2 after reassigning the variables. Reopening / Closing the project works flawless then - But in the upgrade process they broke.

**Comment by Chaosus** [comment] 2021-10-30 15:09
> Adding [Tool] again, they are all zero again at launch of my game and after saving.

It's a duplicate of https://github.com/godotengine/godot/issues/37812 then and should be closed

**Comment by raulsntos** [comment] 2021-10-30 15:12
@Chaosus I don't think so since this is caused by different reasons.

**Comment by Chaosus** [comment] 2021-10-30 15:25
Even if they come from slightly different reasons - they are very similar and easy to be confused - I don't see a reason why we should differentiate them by topics. cc @akien-mga Maybe you could clarify and correct my decision.

**Closed** 2021-10-31 08:10 UTC
Labels: bug, topic:mono, regression
