### ISSUE TITLE
Filled array with array iterates "wrongly".

### ISSUE THREAD

**Issue by PeterMarques** [godotengine/godot#91501] opened 2024-05-03 06:38 UTC
### Tested versions

3.5.3

### System information

editor

### Issue description

When running:

```
extends Node

func _ready():
	var a = []
	
	a.resize(3)
	a.fill([])
	
	for each in a.size():
		a[each].append(randi())
		
	print(a)
	
	var b = []
	b.resize(3)
	
	for each in b.size():
		b[each] = []
		b[each].append(randi())
		
	print(b)
```

you get:

[[3161026589, 2668139190, 4134715227], [3161026589, 2668139190, 4134715227], [3161026589, 2668139190, 4134715227]]
[[4204663500], [1099556929], [3154986942]]

It seens  that both outputs must be like the second one.

The first case is iterating again inside the branches, and copying the values.

Or i am missing something? i tried using fill([].duplicate()) but same behaviour.

### Steps to reproduce

run the code

### Minimal reproduction project (MRP)

[Bug Array.zip](https://github.com/godotengine/godot/files/15196820/Bug.Array.zip)

**Comment by AThousandShips** [comment] 2024-05-03 08:23
This is due to shared constant arrays, this has been solved in 4.x I believe, can you check if it's solved in [3.6](https://godotengine.org/article/dev-snapshot-godot-3-6-beta-4/)?

**Comment by dalexeev** [comment] 2024-05-03 08:45
> a.fill([])

Arrays are passed by reference, you fill the outer array with a reference to the same array. This is already documented:

> Note: If value is of a reference type (Object-derived, Array, Dictionary, etc.) then the array is filled with the references to the same object, i.e. no duplicates are created.

We could solve this by adding the optional parameter `deep = false`.

**Comment by AThousandShips** [comment] 2024-05-03 08:46
This is a constant though

**Comment by PeterMarques** [comment] 2024-05-04 01:23
> > a.fill([])
> We could solve this by adding optional parameters `duplicate = false` and `deep = false`.
and 

>[...] has been solved in 4.x I][...]


changing to a.fill([].duplicate(false)) still produces the same output, even on 4.3dev5

**Comment by dalexeev** [comment] 2024-05-04 06:06
> changing to a.fill([].duplicate(false)) still produces the same output, even on 4.3dev5

This shouldn't change anything. You create the array **once**, make a duplicate **once**, and pass the duplicate to `fill()`, which fills the entire outer array with the same reference, as the documentation says. To create N different arrays you need to use a loop.

**Comment by AThousandShips** [comment] 2024-05-04 07:25
(note the outdated hidden comment, I got this confused with another bug related to shared literals)

**Comment by PeterMarques** [comment] 2024-05-04 16:16
So, the patterns are NOT and SHOULD NOT be equivalent?

Ok, so there is NO WAY to fill a array with a blank arrays using fill() and one need to use the iterator to alocate/or push the blank non referenced arrays inside it, and this is the only way to do that?


If so, ok, no more to discuss, but i, nonetheless, find it odd.

Will just stick to iterate it fully and forget about the fill, and maybe even the resize, on that use case.

Thanks.

**Comment by dalexeev** [comment] 2024-05-08 19:08
> So, the patterns are NOT and SHOULD NOT be equivalent?

Yes, they shouldn't.

> We could solve this by adding optional parameters `duplicate = false` and `deep = false`.

I think this should be opened as a proposal instead, if you're interested. However, the current behavior appears to be correct as is: `fill()` is intended to fill an array with _identical_ elements. Arrays that are value-equal but not reference-value probably cannot be considered the same (see also [`is_same()`](https://docs.godotengine.org/en/stable/classes/class_%40globalscope.html#class-globalscope-method-is-same)).

Given the above, let's close this issue, since the behavior is not a bug and is correctly documented.

**Closed by dalexeev** 2024-05-08 19:08 UTC
Labels: discussion, topic:core
