### ISSUE TITLE
Uninitialized array retains value, even after leaving scope

### ISSUE THREAD

**Issue by SpaceAceMonkey** [godotengine/godot#28978] opened 2019-05-18 05:51 UTC
Possibly related to 
https://github.com/godotengine/godot/issues/25703

**Godot version:**
3.1.1.stable.mono.official
3.1.1.stable.official

**OS/device including version:**
Windows 10

**Issue description:**
Edit: Forgot to try inheriting from something other than reference. Will try that in the morning, and update this issue if that changes anything. 

Edit II: Changed test class to extend Node. Added additional information in new reply.

When calling a function with an array as an argument, that argument retains its value between calls, even if both the function in question and the one that called it have completed and all variables have gone out of scope. Initializing the array on each execution stops this from happening.

**Steps to reproduce:**

array_scope_bug.gd
```
extends Reference

class_name array_scope

func dummy_append_pre():
    var j:Array
    dummy_append(j)
    print(j)

func dummy_append_pre_with_initialization():
    var j:Array = []
    dummy_append(j)
    print(j)

func dummy_append(an_array:Array):
    an_array.append("a")
```

array_scope_bug_main.gd
```
extends Node

func _ready():
	var _as = preload("res://array_scope.gd").new()
	_as.dummy_append_pre()
	_as.dummy_append_pre()
	_as.dummy_append_pre()
	_as.dummy_append_pre()
	_as.dummy_append_pre_with_initialization()
	_as.dummy_append_pre_with_initialization()
	_as.dummy_append_pre_with_initialization()
	_as.dummy_append_pre_with_initialization()
```

**Minimal reproduction project:**
[array_reference_bug_files.zip](https://github.com/godotengine/godot/files/3193695/array_reference_bug_files.zip)

**Comment by YeldhamDev** [comment] 2019-05-18 13:12
CC @bojidar-bg @vnen

**Comment by SpaceAceMonkey** [comment] 2019-05-18 19:43
Additional information: when the array_scope class is extended from Node, the same issue occurs, but I also see this additional output in the debug console:

```ERROR: ~List: Condition ' _first != __null ' is true.
   At: ./core/self_list.h:111
ERROR: ~List: Condition ' _first != __null ' is true.
   At: ./core/self_list.h:111
WARNING: cleanup: ObjectDB Instances still exist!
     At: core/object.cpp:2095
ERROR: clear: Resources Still in use at Exit!
   At: core/resource.cpp:425```

**Comment by akien-mga** [comment] 2019-05-18 19:50
Probably duplicate of #24134 which is fixed by #28603 already.

**Comment by SpaceAceMonkey** [comment] 2019-05-19 03:49
> Probably duplicate of #24134 which is fixed by #28603 already.

I just built master, and the issue persists.

**Comment by TheDuriel** [comment] 2019-08-10 11:53
Still observed on master

```

func _correct_behavior():
	var ar_1: Array = []
	var ar_2: Array = []
	var ar_3: Array = []
	ar_1.append("test")
	print(ar_1)
	print(ar_2)
	print(ar_3)


func _incorrect_behavior():
	var ar_1: Array
	var ar_2: Array
	var ar_3: Array
	ar_1.append("test")
	print(ar_1)
	print(ar_2)
	print(ar_3)

```

**Comment by akien-mga** [comment] 2019-08-12 06:25
See also reproducer in #31242.

**Closed** 2019-09-19 18:31 UTC
Labels: bug, topic:gdscript
