### ISSUE TITLE
Label with dynamic font, adding outline crashes editor

### ISSUE THREAD

**Issue by rick551a** [godotengine/godot#50951] opened 2021-07-27 20:18 UTC
### Godot version

Godot_v3.4-beta2_mono_win64

### System information

Windows10, nvidia 1650

### Issue description

Adding an outline to a dynamic font causes the project to crash to desktop.
The Label has animation & bbcode also, I dont know if this contributes to crash.
Worked fine in 3.3.

### Steps to reproduce

Open the project.  Run it, it's just a Label, should work fine (no outline on font).

Now, in the editor, click the Label, 
on the inspector scroll down to 'Custom Fonts', 
expand 'Dynamic Font'
Change 'Outline size' to 1.
Run, observe crash.

### Minimal reproduction project

https://ufile.io/fyf1qrs4

 file name is 3_4b2 Labelcrash.zip

**Comment by bruvzg** [comment] 2021-07-27 20:33
I can't reproduce the crash on macOS, outline seems to be working fine. Is it editor crashing on running project? Is there any output in the console?

**Comment by rick551a** [comment] 2021-07-27 20:39
It's an instant crash to desktop when I just click the 'up' to increase the outline, or press return after manually typing it.

Windows event viewer message:
Faulting application name: Godot_v3.4-beta2_mono_win64.exe, version: 3.4.0.0, time stamp: 0x00000000
Faulting module name: ntdll.dll, version: 10.0.19041.488, time stamp: 0x70e69bad
Exception code: 0xc0000028
Fault offset: 0x0000000000101f46
Faulting process id: 0x1658
Faulting application start time: 0x01d7832879cabd58
Faulting application path: C:\Users\p\Downloads\Godotbetas\3_4\Godot_v3.4-beta2_mono_win64\Godot_v3.4-beta2_mono_win64.exe
Faulting module path: C:\Windows\SYSTEM32\ntdll.dll
Report Id: 511345b9-d8f1-4516-b207-770eff010d5d
Faulting package full name: 
Faulting package-relative application ID:

**Comment by Calinou** [comment] 2021-07-27 21:01
> Worked fine in 3.3.

Did it work in 3.3.2 too?

I'd look into [bisecting the regression](https://docs.godotengine.org/en/latest/community/contributing/bisecting_regressions.html) on your own machine.

**Comment by rick551a** [comment] 2021-07-27 21:26
Yes it worked fine in 3.3.2 (mono). 
Just tested it on 3.4b2 mono with Windows 7 x64, same crash to desktop.

**Comment by ondesic** [comment] 2021-07-28 04:47
I can replicate the problem that rick551a is having.  I have been working on this all day.  After updating from 3.3.2 to 3.4b2 my massive project that used to load perfectly is now crashing on loading.  I kept narrowing down the problem and I finally got it down to a certain font I use.  I then narrowed it down to a Glyph in the font.  
Something has changed in the way dynamic fonts are processed from 3.3.2 to the new beta.  It has to do with the size of the font.  If it gets too big it crashes.  Sometimes that happens with increasing the outline, other times it happens by increasing the size of the font.  I am working on another minimal reproduction project to help narrow it down.

**Comment by ondesic** [comment] 2021-07-28 04:55
Here is a custom Font that has a Glyph that crashes.  If I use this font, 
1) type something
2) set size to 50 
3) and then change Outline to 1, it will crash.  

Subsequently, setting the size to 40, then increasing the outline to 8 will also cause it to crash as well.

[Test.zip](https://github.com/godotengine/godot/files/6890405/Test.zip)

**Comment by ondesic** [comment] 2021-07-29 15:01
I noticed this in the recent change log:
"Font: Re-add support for kernic in DynamicFont (GH-49377)." (I think they meant "kerning").  I wonder if this is where the problem stems from?

**Comment by Calinou** [comment] 2021-07-29 15:06
> I noticed this in the recent change log:
> "Font: Re-add support for kernic in DynamicFont ([GH-49377](https://github.com/godotengine/godot/pull/49377))." (I think they meant "kerning"). I wonder if this is where the problem stems from?

I would try to bisect the regression to make sure. You only need to build two commits to test this:

- c5ed95a52617efbff4d96348411f28dda6af52d7 (after the PR was merged)
- dbf75931d08f5d3250a24749f41968190054dd99 (before the PR was merged)

**Comment by akien-mga** [comment] 2021-08-03 19:20
Given the findings in #50970, this might be an issue linked to building official binaries with MinGW-GCC from Fedora 34 (and matching versions of MinGW and GCC).

**Comment by akien-mga** [comment] 2021-08-03 19:56
> I'll make a test build with a revert of #49377 to see if that confirms it as the trigger.

Reverting #49377 doesn't solve it, so we have to dig deeper.

**Comment by akien-mga** [comment] 2021-08-05 13:08
I found the fix, it was a regression in GCC 10.3.0+. See #50970 for details (which ended up being a duplicate of this issue, so I'll close this one to keep track of further updates there).

**Closed by akien-mga** 2021-08-05 13:08 UTC
Labels: bug, confirmed, crash, regression, topic:gui
