### ISSUE TITLE
OS.low_processor_usage_mode in Android makes problems to Anim, Tween, and CheckButton nodes

### ISSUE THREAD

**Issue by tam0705** [godotengine/godot#19304] opened 2018-06-01 13:25 UTC
**Godot version:**
Godot 3.0.2 stable

**OS/device including version:**
Windows 10 Pro
Exporting to Android 6.0, Samsung Galaxy J2 Prime

**Issue description:**
When being played in the project, OS.low_processor_usage_mode made my animations not smooth, which is very normal for me. But when being exported and run in Android, it made weird and actually funny problems to my animations, tweens, and checkbuttons. Every scene of mine has its own anims and tweens, where some scenes only had their anims affected and the others had their tweens affected. The settings scene is the only one who has CheckButtons and those nodes were also affected. It is really hard to explain the problem so I just provide a video: https://youtu.be/nSS_nzAhR6g

Notice in the video that I tested the game before enabling low usage mode, then something weird happened after I turned it on. (It is when I enabled power saving)

Note: I used Tweens only for moving the cards and the buttons in the bottom of the screen. Other motions besides them are made using AnimationPlayers

**Comment by romeojulietthotel** [comment] 2018-06-02 19:45
You may follow these threads, if you haven't already. Maybe they help?

- https://github.com/godotengine/godot/issues/6727
- https://github.com/godotengine/godot/issues/7980

Did you test without _OS.low_processor_usage_mode_ to make sure?

**Comment by bojidar-bg** [comment] 2018-06-03 08:21
Just to confirm, it happens only on android, right? (also, might be nice to mention the device tested)

From what I can see on the video, what happens is that the after the animation is over, the last two frames start swapping in quick succession, presumably because someone continues swapping the buffers, even if nothing is rerendered.

**Comment by tam0705** [comment] 2018-06-03 12:50
@romeojulietthotel I've tested it in the Android itself both with OS.low_processor_usage_mode and without it. You can see it on the video. About the issues you linked, I don't think they helped, seeing I myself don't actually understand the #6727 one. XD
@bojidar-bg  Yes, it only happened in my android. The device is Samsung Galaxy J2 Prime. I think I have to test in my family's devices too, since those devices have the different versions of Android.

**Comment by reduz** [comment] 2018-06-08 16:29
I dont think this feature was ever properly implemented on Android

**Comment by tam0705** [comment] 2018-06-09 14:18
Well, I failed to test it in my other's family devices because of many outside.. issues.
Lmao XD @reduz If that's so I think I have to disable power saving feature in my game for a while :v

**Comment by zhagsenkk** [comment] 2018-08-14 14:53
![1](https://user-images.githubusercontent.com/10054853/44099026-3f7120ea-a014-11e8-8027-8c6f8d52f8c4.gif)
![2](https://user-images.githubusercontent.com/10054853/44099028-40960de6-a014-11e8-833d-2d10689e4b1a.gif)
![3](https://user-images.githubusercontent.com/10054853/44099236-c8d33396-a014-11e8-8014-fdd26ed87225.gif)

link: https://gamejolt.com/games/mult/360731

Win10 64，Chrome 68.0.3440.106（32 bit）

I dont know if these are related.

**Comment by tavurth** [comment] 2020-08-02 19:02
Just a note that this issue has now been present for almost 5 years, spreading across several different issues, notably:

https://github.com/godotengine/godot/issues/6727
https://github.com/godotengine/godot/issues/19304
https://github.com/godotengine/godot/issues/7980

As a newer Godot developer I ran across this the first time when one of my GUI apps was blocked from the play store as it was unresponsive due to "OS.low_processor_usage".

Perhaps if this issue will not be fixed until Godot 4.0, it would be better to automatically disable this when exporting to Android devices.

The feature description is alluring, and yet causes problems for new developers and inhibits adoption.

**Comment by Gromph** [comment] 2021-12-02 22:42
I found a simple solution to this problem, which is to force draw 2 more frames after the last changed frame. Here is my fix for 3.x:
https://github.com/SilverCreekEntertainment/godot/commit/30d337ccd23f116d4eb5927ed2f4a1c204bfbe7b

It is important for our games, because there can be periods of time when the user is looking at their hand in a card game deciding their next move with no drawing going on. 

I don't know if this is still an issue on master, but the code in main.cpp looks the same and the same fix could be applied to master.

Let me know if this fix looks good and I can make it a pull request.

**Comment by Gromph** [comment] 2021-12-02 22:54
Oops, the flicker returns if you task to another app and back.   So probably need to force draw a few more frames when re-gaining focus.

**Comment by Gromph** [comment] 2021-12-03 01:17
Ok, I think I got all the flickers fixed, the fix was to force redraw 3 frames after GodotRenderer::onSurfaceChanged gets called.
Here is my new fix for 3.x: https://github.com/SilverCreekEntertainment/godot/commit/94364e3d9a660df8ccb81af28478654baf297ce2

I reworked Main::force_redraw to take number of frames to redraw and have Main::iteration  redraw that many in a row. I'm not sure if this is the best solution or not, it's working pretty good for our games though.  But could use lots more testing.  I set it to redraw 3 frames by trial and error.
To test thoroughly you need to try things that cause the gl surface to be lost, like switch apps, turn screen off and on, rotate phone, etc.

**Comment by Calinou** [comment] 2021-12-03 11:26
> Ok, I think I got all the flickers fixed, the fix was to force redraw 3 frames after GodotRenderer::onSurfaceChanged gets called.
> Here is my new fix for 3.x: [SilverCreekEntertainment@94364e3](https://github.com/SilverCreekEntertainment/godot/commit/94364e3d9a660df8ccb81af28478654baf297ce2)

Feel free to open a pull request for this :slightly_smiling_face: 

Note that we'll need a `master` version of the pull request for the `3.x` version to be merged, but the `3.x` version should still be opened since the `master` PR will use different, incompatible code.

**Comment by fahrstuhl** [comment] 2021-12-03 11:32
Any idea what the source of the problem could be? If the magic number seems to be 2 or 3, is this solution filling the buffers of VSync or triple buffering that otherwise contain older frames?

**Comment by tavurth** [comment] 2021-12-03 16:08
My idea: Maybe when the app reloads it creates a lag frame from the foreground activities, then loading the last rendered frame which was done at app exit.

This seems a bit weird though because the app is often flickering rather than some black screen, and there is also some frozen logic from what I've seen.

Perhaps somehow the back-side of the buffer ends up out of sync and it just renders over and over again? (Idea being that the app is rendering always OK on one buffer but the back-side is intermittent.)

Just jamming ideas 😄

**Comment by Gromph** [comment] 2021-12-03 19:24
> Any idea what the source of the problem could be? If the magic number seems to be 2 or 3, is this solution filling the buffers of VSync or triple buffering that otherwise contain older frames?

That would be my assumption, but I'm not a gpu expert. 


> My idea: Maybe when the app reloads it creates a lag frame from the foreground activities, then loading the last rendered frame which was done at app exit (black).

The App isn't reloading, it's just losing and recreating the open gl surface.  I don't know if there would be some way to render one frame and fill all buffers.


I'm testing version v4.0.dev.20211117.official [175690957]. And have not reproduced the flicker when it stops rendering, but the screen does go black if surface is lost do to app switching, screen off/on. Rotating phone is working ok though.

**Closed** 2022-03-29 19:52 UTC
Labels: bug, topic:rendering, topic:porting, confirmed
