### ISSUE TITLE
Area2D receives signal even with no collision mask set

### ISSUE THREAD

**Issue by luizcarlos1405** [godotengine/godot#26139] opened 2019-02-21 22:00 UTC
**Godot version:**
3.1 beta 5

**Issue description:**
An Area2D receives the signal area_entered and body_entered even if it has nothing marked in its collision mask. If the entering area/body has the Area2D layer marked in its mask then the signal is triggered for Area2D.

if said Area2D bitmask is 0b00 and layer 0b10 and a body with mask 0b10 and layer 0b00 enters the area, the body's bitmask BITAND Area2D's layer is != 0 so the body detects the Area2D BUT, the opposite is not true, so the Area2D shouldn't detect the body and should not have it's body_entered called.

If the above example is done with 2 Area2D's, then both receive the signal.

Sorry if this is the intended behaviour, I couldn't find anything related anywhere.

Edit:
A project showing the above example.

Minimal reproduction project:

[area2D with no collision mask.zip](https://github.com/godotengine/godot/files/2895640/area2D.with.no.collision.mask.zip)

**Comment by avencherus** [comment] 2019-04-20 11:39
I believe this is intended behavior.  A bug would be if a 0 bit mask collided with a 0 bit layer.

The determining factor of the contact test is if a mask matches a layer.  In your demo, the 0 layer areas are masked to layer 1, and the test area is on layer 1.

**Comment by akien-mga** [comment] 2020-01-14 13:14
Closing as per above comment, this is indeed behaving as expected.

Area2 and Body both scan layer 1 (that's their collision mask), and Area is in layer 1 (that's its collision layer), so that's a match.

**Closed by akien-mga** 2020-01-14 13:14 UTC
Labels: bug, topic:physics
