### ISSUE TITLE
AudioStreamPlayer2D 

### ISSUE THREAD

**Issue by cody82** [godotengine/godot#60767] opened 2022-05-04 23:11 UTC
### Godot version

v3.4.4.stable.official.419e713a2

### System information

Windows 11

### Issue description

AudioStreamPlayer2D does not play any sound with multiple viewports(splitscreen).

### Steps to reproduce

1. Setup splitscreen like in splitscreen_demo project
2. Add an AudioStreamPlayer2D to the world
3. Play some sound with it
4. I can not hear anything.

**Comment by Calinou** [comment] 2022-05-04 23:13
@cody82 Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

Is the listener property enabled on your Camera2Ds?

**Comment by cody82** [comment] 2022-05-04 23:19
Sorry, will try to strip down the project for reproduction.

I can not find a listener property in the inspector tab or in the Camera2D documentation? So maybe thats already the solution...

**Comment by ellenhp** [comment] 2022-05-05 15:53
I think Calinou is referring to this: https://docs.godotengine.org/en/stable/classes/class_viewport.html#class-viewport-property-audio-listener-enable-2d

Make sure that's set to true on at least one of your viewports to hear 2d audio. If that doesn't work then this is definitely a bug.

**Comment by cody82** [comment] 2022-05-05 21:47
Thank you, it works when enabling audio listener for the viewports. One minor problem is that the audio seems to be added for each viewport? So with 4 viewports it is extremely loud. Is there a simple way to fix this?

**Comment by Calinou** [comment] 2022-05-05 22:54
> Thank you, it works when enabling audio listener for the viewports. One minor problem is that the audio seems to be added for each viewport? So with 4 viewports it is extremely loud. Is there a simple way to fix this?

You probably want to redirect all game audio to a separate bus, and modulate the global volume of this bus depending on how many viewports have a listener active. For instance, -6 dB with 2 viewports active, -12 dB with 3 viewports active, -18 dB with 4 viewport active.

**Comment by ellenhp** [comment] 2022-05-05 23:17
It's going to be -3db with 2, -4.8db for 3, -6db for 4, etc. `linear2db(1.0/num_listener_viewports)` in general.

**Comment by ellenhp** [comment] 2022-05-06 00:16
I'm going to close this because it seems resolved. This behavior is expected for multi-viewport situations. It might not be ideal but it's not a bug either.

**Closed by ellenhp** 2022-05-06 00:16 UTC
Labels: needs testing, topic:audio, topic:2d
