### ISSUE TITLE
Crash at editor startup on Linux

### ISSUE THREAD

**Issue by jmf** [godotengine/godot#15248] opened 2018-01-01 16:15 UTC
**Godot version:**
All versions after 6f3486c4866a0a0e0408c2e0dbd65f128995abf4

**OS/device including version:**
Linux 4.14.4
mesa 17.2.8
xorg-server 1.19.6
i3 4.14.1 / dwm 6.0

**Issue description:**
The project manager starts normally.
When the editor is started (from the project manager or standalone), it produces an unresponsive window.

Removing the code added in 6f3486c4866a0a0e0408c2e0dbd65f128995abf4 fixes this bug.
I have only tested this with the i3wm and dwm window managers (versions above), both tiling WMs.

**Comment by vnen** [comment] 2018-01-01 16:19
Duplicate of #15068.

**Closed by vnen** 2018-01-01 16:19 UTC

**Comment by jmf** [comment] 2018-01-02 19:54
Ah, I looked for the keywords "freeze" and "crash" in the issues before posting, which are not present in the earlier one.
