### ISSUE TITLE
[4.0 beta 7] Duplicated nodes' signals can't be disconnected within the editor

### ISSUE THREAD

**Issue by handre-dev** [godotengine/godot#70014] opened 2022-12-13 11:01 UTC
### Godot version

4.0 beta 7

### System information

Windows 10

### Issue description

When you duplicate a node that has signals connected to one or more methods via editor, the duplicated node will have the same signals connected but they'll be coloured in yellow and you'd be unable to disconnect them.

Reloading the project apparently fixes the issue

![image](https://user-images.githubusercontent.com/96829602/207299654-d9cf5c80-d22a-4448-8f68-fa1f2bb283a3.png)

### Steps to reproduce

1. Create a node in your scene (it doesn't matter if a blank project or an existing one)
2. Connect a signal from the Signals menu to an existing method or a new one
3. Duplicate the node
4. Try to disconnect the connected methods from the duplicated node's signal.

### Minimal reproduction project

Unnecessary

**Comment by Zireael07** [comment] 2022-12-13 11:05
Does the issue still occur in beta **8**?

**Comment by KoBeWi** [comment] 2022-12-13 13:33
Duplicate of #69348

**Closed by KoBeWi** 2022-12-13 13:33 UTC
