### ISSUE TITLE
GDScript 2.0: @onready var using static func results in Parser bug

### ISSUE THREAD

**Issue by MikeSchulze** [godotengine/godot#69763] opened 2022-12-08 13:54 UTC
### Godot version

v4.0.beta6.official [7f8ecffa5]

### System information

Windows 10, MacOS

### Issue description

I using a texture image converter as a static function called add ready var assignment.

```gdscript

extends Control


@onready var ICON_SPINNER = load("res://assets/spinner.tres")
@onready var ICON_TEST_DEFAULT :ImageTexture = load_resized_texture("res://assets/TestCase.svg")

@onready var _tree :Tree = $Tree


var _tree_root :TreeItem


static func load_resized_texture(path :String, width :int = 16, height :int = 16) -> ImageTexture:
	var texture :CompressedTexture2D = load(path)
	var image = texture.get_image()
	if width > 0 && height > 0:
		image.resize(width, height)
	return ImageTexture.create_from_image(image)

```
The editor console shows an error during loading the script.

```
  modules/gdscript/gdscript_analyzer.cpp:667 - Parser bug (please report): tried to assign unset node without an identifier.
  Parser bug (please report): Trying to check compatibility of unset value type
  modules/gdscript/gdscript_analyzer.cpp:667 - Parser bug (please report): tried to assign unset node without an identifier.
  Parser bug (please report): Trying to check compatibility of unset value type
  modules/gdscript/gdscript_analyzer.cpp:667 - Parser bug (please report): tried to assign unset node without an identifier.
  Parser bug (please report): Trying to check compatibility of unset value type
  modules/gdscript/gdscript_analyzer.cpp:667 - Parser bug (please report): tried to assign unset node without an identifier.
  Parser bug (please report): Trying to check compatibility of unset value type
  modules/gdscript/gdscript_analyzer.cpp:667 - Parser bug (please report): tried to assign unset node without an identifier.
  Parser bug (please report): Trying to check compatibility of unset value type
  modules/gdscript/gdscript_analyzer.cpp:667 - Parser bug (please report): tried to assign unset node without an identifier.
  Parser bug (please report): Trying to check compatibility of unset value type
````

And additional errors when run the scene
![image](https://user-images.githubusercontent.com/347037/206462287-18b13def-7335-4d34-8397-9354625b3e16.png)

### Steps to reproduce

download the example project and run the scene

### Minimal reproduction project

[onready_bug.zip](https://github.com/godotengine/godot/files/10185945/onready_bug.zip)

**Comment by adamscott** [comment] 2022-12-09 00:59
@rune-scape Does your PR #69471 fix this issue?

**Comment by rune-scape** [comment] 2022-12-09 04:04
it does!

**Comment by rune-scape** [comment] 2022-12-09 04:07
but it looks like a duplicate of https://github.com/godotengine/godot/issues/69479

**Closed** 2022-12-09 06:13 UTC
Labels: bug, topic:gdscript, confirmed

**Comment by MikeSchulze** [comment] 2022-12-09 10:37
nice thanks
