### ISSUE TITLE
move_and_collide breaks near seams (3.1)

### ISSUE THREAD

**Issue by klhrt** [godotengine/godot#31664] opened 2019-08-25 20:42 UTC
**Godot version:**
3.1.1-Stable

**OS/device including version:**
Windows 10

![godot_bug](https://user-images.githubusercontent.com/54511837/63655539-20547980-c757-11e9-9b60-21b57db7d92c.gif)

**Issue description:**
`move_and_collide()` (and its variants `move_and_slide()` and `move_and_slide_with_snap()`)pushes a KinematicBody away from seams between collision objects, making 3D level design via gridmaps currently unusable

**Steps to reproduce:**
put a KinematicBody on a seam between two collision objects

**Minimal reproduction project:**
[Seams.zip](https://github.com/godotengine/godot/files/3538578/Seams.zip)

**Comment by KoBeWi** [comment] 2019-08-25 21:12
Duplicate of  #29392

**Closed by KoBeWi** 2019-08-25 21:12 UTC

**Comment by cbscribe** [comment] 2019-08-25 21:57
Related: #28438
