### ISSUE TITLE
Setting up name for a new project gets overwritten by directory selection.

### ISSUE THREAD

**Issue by viksl** [godotengine/godot#84703] opened 2023-11-10 10:43 UTC
### Godot version

4.2 beta 5

### System information

Windows 11 - Vulkan - Nvidia RTX 4070 - intel i5 13600KF

### Issue description

In 4.2 when you set up the Project Name first and then change path (browse button) the project name gets overriden by the directory name. It does not happen in 4.1.3. I don't know if this is intended or not but haven't found an issue about it. In any case it's pretty annoying to create new projects now especially when you test more projects plus the project name is the first thing you meet and the first thing you can set up so it makes sense to me that if you change it then the manager shouldn't change it back (?).

Before:
![image](https://github.com/godotengine/godot/assets/33526847/be97644a-edf3-45e8-aa79-64e20cae4b11)
After:
![image](https://github.com/godotengine/godot/assets/33526847/a79be86e-ea3f-4a5d-8de7-f22621c5304a)

### Steps to reproduce

1. Create a new project
2. Set up the name
3. change project path
4. Observer the project name changed again

### Minimal reproduction project

None.

**Comment by AThousandShips** [comment] 2023-11-10 10:47
Duplicate of https://github.com/godotengine/godot/issues/83605

**Closed** 2023-11-10 10:48 UTC
Labels: archived, discussion, topic:editor, usability
