### ISSUE TITLE
"Flags" export hint is not working

### ISSUE THREAD

**Issue by kubecz3k** [godotengine/godot#13184] opened 2017-11-22 16:54 UTC
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
9ebc6ab45a375310f650bf3afd31f076215ac52c 

**Issue description:**
`export(int, FLAGS) var some_bit_flags` is not working currently. 
In inspector it's treated as ordinary `export (int) var some_bit_flags`

**Steps to reproduce:**
1. Add `export(int, FLAGS) var some_bit_flags` to any script
2. Check it in inspector

**Comment by akien-mga** [comment] 2018-01-05 14:46
We have now entered release freeze for Godot 3.0 and want to focus only on release critical issues for that milestone. Therefore, we're moving this issue to the 3.1 milestone, though a fix may be made available for a 3.0.x maintenance release after it has been tested in the master branch during 3.1 development. If you consider that this issue is critical enough to warrant blocking the 3.0 release until fixed, please comment so that we can assess it more in-depth.

**Comment by ordigdug** [comment] 2018-08-06 18:13
@kubecz3k That is the way its suppose to work according to the docs. Your individually editing the bits of an integer. 
example: 
export(int, FLAGS) var some_bit_flags = 2 | 8 
Which equals an int of 10

If you want FLAG options in the inspector to choose from: 
export(int, FLAGS, "Flag1", "Flag2", "Flag4", "Flag8") var some_bit_flags = 0

http://docs.godotengine.org/en/3.0/getting_started/scripting/gdscript/gdscript_basics.html#exporting-bit-flags

**Comment by reduz** [comment] 2018-09-06 12:36
closing then, as not a bug.

**Closed by reduz** 2018-09-06 12:36 UTC
Labels: bug, topic:editor

**Comment by akien-mga** [comment] 2018-09-09 14:32
Actually this was a bug as `export(int, FLAGS)` is documented as a hint that lets you edit the bits individually (same widget as for physics layers).

This doesn't work (as this bug mentions), but the feature was deprecated in #21369, so it's indeed "fixed".

**Comment by akien-mga** [comment] 2018-09-09 14:54
Note that the feature did exist and work in 2.1, it was broken when @reduz removed `PROPERTY_HINT_ALL_FLAGS` to replace it by `PROPERTY_HINT_LAYERS_{2,3}D_{RENDER,PHYSICS}`, so that there is no longer a generic bit flags widget.

**Comment by akien-mga** [comment] 2018-09-09 16:32
See also #21349 (which was actually a duplicate of this one).

**Comment by thebluefish** [comment] 2019-03-28 13:56
Seeing the same behavior in 3.1.

@akien-mga can we re-open this issue?

**Comment by thebluefish** [comment] 2019-03-28 14:01
Here's an example of what it looked like in 2.1.5, what I expect to see in the current version of Godot.

![](https://user-images.githubusercontent.com/4490910/55163595-4d105080-5127-11e9-9abd-bc83083e158a.png)

**Comment by Calinou** [comment] 2019-03-28 14:26
@thebluefish What does your `export var` declaration look like?

**Comment by thebluefish** [comment] 2019-03-28 14:38
```godot
export(int, FLAGS) var my_var
```
Which produces the following in 2.1:
![](https://user-images.githubusercontent.com/4490910/55166369-37e9f080-512c-11e9-9adf-7d2da069ece8.png)

The following in 3.0/3.1:
![](https://user-images.githubusercontent.com/4490910/55166453-636cdb00-512c-11e9-8dee-454b0a58a904.png)
