### ISSUE TITLE
Line2D rendering does not apply proper settings

### ISSUE THREAD

**Issue by inhalt120g** [godotengine/godot#86426] opened 2023-12-22 09:44 UTC
### Tested versions

v4.2.1.stable.official [b09f793f5]

### System information

Godot v4.2.1.stable - macOS 14.2.1 - Vulkan (Forward+) - integrated Apple M1 - Apple M1 (8 Threads)

### Issue description

I'm trying to use Line2D nodes as markers within IDE in my project. For that, I'd like certain lines to be rendered in a specific way to help me distinguish them from "regular" Line2Ds. So I'm trying to add a texture to them or a gradient, but the rendering results are unexpected. For example if I use a gradient and set it to be only black and white, the line is still rendered with smooth gradation:
![image](https://github.com/godotengine/godot/assets/106015575/5ae8bf6a-1ac3-465d-8cc6-fe3b1868f9a8)

Another thing I'm trying to achieve is the "stitched line" look of marker lines by applying a texture to them. Again, the results are unexpected. For example, if I set the Texture of a Line2D to use an AtlasTexture with a region like in this image:
![image](https://github.com/godotengine/godot/assets/106015575/5c26d938-d83e-46a7-b841-6350a5f0e6eb)
I'd expect that if I set the "Texture Mode" to "tile", I'd get the line to look like it's stitched (so few pixels red, few pixels transparent, few pixels red, few pixels transparent etc). Instead it looks like this:
![image](https://github.com/godotengine/godot/assets/106015575/3208c24d-fec2-43e5-9e05-9b9f38bc6b47)

And if I zoom in on top, it looks really strange:
![image](https://github.com/godotengine/godot/assets/106015575/d9b0e91b-d307-4069-86c8-7c0d38783abc)

### Steps to reproduce

Make a Line2D… add a gradient.
Remove the ramping from the gradient… but the line will still be rendered with a gradient.

Same with a texture.

### Minimal reproduction project (MRP)

Godot 4.2.1

Edit: just for the sake of the example I'm using a 10 pixels wide line here so it's easier to see but the same thing happens when the width is 1 pixel, mentioning it because the width of the texture in the example is 1 pixel.

**Comment by arkology** [comment] 2023-12-22 10:14
Duplicate of https://github.com/godotengine/godot/issues/43268

**Comment by inhalt120g** [comment] 2023-12-22 11:31
The linked issue does not mention gradient (so not exact duplicate), and concentrates primarily on the fact that AtlasTexture is used. So I tried it with a "regular" texture too, but the result is the same. I'm attaching the 1-pixel wide texture.
![stitch line 01](https://github.com/godotengine/godot/assets/106015575/7df4683a-9467-479d-8c79-656756751a08)

**Comment by Calinou** [comment] 2023-12-22 15:19
Please upload a minimal reproduction project[^1] to make this easier to troubleshoot.

[^1]: A small Godot project which reproduces the issue, with no unnecessary files included. Be sure to not include the `.godot` folder in the archive (but keep `project.godot`).<br><br>Drag and drop a ZIP archive to upload it. **Do not select another field until the project is done uploading.**<br><br>**Note for C# users:** If your issue is *not* Mono-specific, please upload a minimal reproduction project written in GDScript or VisualScript. This will make it easier for contributors to reproduce the issue locally as not everyone has a Mono setup available.

**Comment by kleonc** [comment] 2023-12-22 17:19
The gradient part is pretty much a duplicate of #50076.

**Comment by inhalt120g** [comment] 2023-12-23 01:21
@Calinou Sorry for the omission, here it is:
[Godot engage 010.zip](https://github.com/godotengine/godot/files/13757508/Godot.engage.010.zip)

This is what it looks like on my end:
![image](https://github.com/godotengine/godot/assets/106015575/3c018d25-2988-4204-b444-eb8a738b6a7f)

**Comment by kleonc** [comment] 2023-12-23 09:54
> [Godot engage 010.zip](https://github.com/godotengine/godot/files/13757508/Godot.engage.010.zip)
> 
> This is what it looks like on my end: ![image](https://private-user-images.githubusercontent.com/106015575/292602748-3c018d25-2988-4204-b444-eb8a738b6a7f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMzMjE0NTUsIm5iZiI6MTcwMzMyMTE1NSwicGF0aCI6Ii8xMDYwMTU1NzUvMjkyNjAyNzQ4LTNjMDE4ZDI1LTI5ODgtNDIwNC1iNDQ0LWViOGE3MzhiNmE3Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyM1QwODQ1NTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NmUwZThhZTQ3YTkxMmVhODJhOTRiYTYwZTU4MjcxMzYwODAzMWIyYWM0ZWFlZmU2NjlkYWUyMTk0MjkwZGYzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.1rj14dC3VmY5AC13dS4BadQE4-Q2hSkkl7rIzpfr_-k)

You don't have texture repeating enabled for any of them (all are set to `Inherit` and the `rendering/textures/canvas_textures/default_texture_repeat` project setting is set to its default value which is `Disabled`).

So seems like that's what you want:
![W58lhVKCk4](https://github.com/godotengine/godot/assets/9283098/3e364744-5692-4177-9894-772158c06b42)

This is already documented:
![fqRwxBKx5s](https://github.com/godotengine/godot/assets/9283098/bb4d2650-7643-4226-b8ce-e1b2a5d897f0)

---


> I'm trying to use Line2D nodes as markers within IDE in my project. For that, I'd like certain lines to be rendered in a specific way to help me distinguish them from "regular" Line2Ds. So I'm trying to add a texture to them or a gradient, but the rendering results are unexpected. For example if I use a gradient and set it to be only black and white, the line is still rendered with smooth gradation:
> ![image](https://private-user-images.githubusercontent.com/106015575/292454996-5ae8bf6a-1ac3-465d-8cc6-fe3b1868f9a8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMzMjE0NTUsIm5iZiI6MTcwMzMyMTE1NSwicGF0aCI6Ii8xMDYwMTU1NzUvMjkyNDU0OTk2LTVhZThiZjZhLTFhYzMtNDY1ZC04Y2M2LWZlM2IxODY4ZjlhOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyM1QwODQ1NTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03YmM2OTM1YWY0NjEzYmQzNWMwNGE0ZjkxMzE3YTU5MDk3OGEwZDJiMjc0ZjVjNGUwZDFhOTQzNGM0MTlhNTVlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.iuZhdajH5m-wMSgMDB8qbijQn5n7UUg0b83uWBJpYKc)

As mentioned this is a duplicate of #43268. For it to be rendered as expected the gradient would need to be sampled right before / right after the "color step" so the smooth interpolation of different colors would be pretty much invisible (as gradient is sampled only for the vertices, and such sampled color is set as the vertex color). E.g.:

![f8XzNMN2ZP](https://github.com/godotengine/godot/assets/9283098/347a3f49-0268-4cb4-9988-3f065f27f42d)


---


> And if I zoom in on top, it looks really strange:
> ![image](https://private-user-images.githubusercontent.com/106015575/292456244-d9b0e91b-d307-4069-86c8-7c0d38783abc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMzMjE0NTUsIm5iZiI6MTcwMzMyMTE1NSwicGF0aCI6Ii8xMDYwMTU1NzUvMjkyNDU2MjQ0LWQ5YjBlOTFiLWQzMDctNDA2OS04NmM4LTdjMGQzODc4M2FiYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyM1QwODQ1NTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kZWNmOTZkZjcyZjdmNTE4ODA1NDgwY2RkMDg3N2Q2NDk3YTliNzE0YzY1YjNjYzFiOGQyODUxZmU4ZjYxMWVlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.-xDKx79CFXObTRo36sjk3kGupwFG5Xm-EBxG4C8iwlA)

This "strange part" is the whole `AtlasTexture.atlas` rendered in there. The rest is the result of the disabled texture repeating. So it's the same as #43268.

![Godot_v4 2 1-stable_win64_xi5Mzbm56o](https://github.com/godotengine/godot/assets/9283098/579ece83-ea5c-471e-9e16-2af444b3904f)
![eJoZurpqYJ](https://github.com/godotengine/godot/assets/9283098/8c82d806-b58a-4cec-9542-4b3886b0ba9d)


---

I don't see any other issue being reported in here than the already reported/tracked #43268 and #50076. Hence closing this issue as a duplicate.
@inhalt120g In case I'm missing something please point it up, it can always be reopened. :slightly_smiling_face:

**Closed by kleonc** 2023-12-23 09:54 UTC
Labels: topic:rendering, needs testing, topic:2d

**Comment by inhalt120g** [comment] 2023-12-23 10:16
Thanks for the help @kleonc yes I think everything's covered! 👍
