### ISSUE TITLE
[4.x] unexpected behaviour from to_byte_array method on PackedStringArray

### ISSUE THREAD

**Issue by OsakiTsukiko** [godotengine/godot#76097] opened 2023-04-15 18:25 UTC
### Godot version

4.x (a7276f1)

### System information

Arch Linux x86_64 Kernel 6.2.10-arch1-1

### Issue description

The to_byte_array method on PackedStringArray returns a PackedByteArray that only contains references to the string locations in memory (even tho the docs state `Returns a PackedByteArray with each string encoded as bytes.`). I can not think of a use for the returned PackedByteArray, which is NOT constant and might even pose memory errors (if somehow decoded). The PackedStringArray might be better without it as it only causes confusion and doesn't have any real benefits (or at least I couldn't find any), or a custom to_byte_array specialized for PackedStringArray.

### Steps to reproduce

```gdscript
var psa := PackedStringArray(
	[
		"TEST",
		"TEST",
		"TEST"
	]
)
	
var s_pba := psa.to_byte_array()
print(s_pba) # REFERENCES, NOT CONSISTENT
```

### Minimal reproduction project

N/A

**Comment by AThousandShips** [comment] 2023-04-15 18:27
Duplicate of #66526

**Closed** 2023-04-15 18:28 UTC
