### ISSUE TITLE
v4.0-beta1 crash when change Editor Settings->Theme->Accent color

### ISSUE THREAD

**Issue by 838116504** [godotengine/godot#66239] opened 2022-09-22 00:51 UTC
### Godot version

4.0.beta1

### System information

Windows 10, gtx 960

### Issue description

Choose accent color multiple times in Editor Settings window, then crash.

### Steps to reproduce

Edit new Project.
Open Editor Settings window.
Switch Theme page.
Click Accent Color to choose color multiple times.
Click other place to close Accent Color color wheel.
Godot crash.

**Comment by KoBeWi** [comment] 2022-09-22 00:54
Duplicate of #59798

**Closed by KoBeWi** 2022-09-22 00:54 UTC
