### ISSUE TITLE
Demo - 3d Platformer gives error and low fps

### ISSUE THREAD

**Issue by Akira1San** [godotengine/godot#14984] opened 2017-12-23 15:07 UTC
Godot 3 beta 2 64b
OS Win8.1 64b AMD R7 200 series

**Issue description:**
Downloaded the demos to test the 3d platformer.
The platformer game gives a lot of errors and lower fps 1-3 fps. I suspect the animation errors running every frame are the cos. I made some images:
image: http://pasteall.org/pic/show.php?id=121238
image; http://pasteall.org/pic/index.php?id=121239
image: http://pasteall.org/pic/index.php?id=121240

**Comment by Calinou** [comment] 2017-12-23 17:02
Duplicate of https://github.com/godotengine/godot-demo-projects/issues/174. Issues about official demo projects should be reported on [godotengine/godot-demo-projects](https://github.com/godotengine/godot-demo-projects/issues/new).

**Closed by Calinou** 2017-12-23 17:02 UTC
