### ISSUE TITLE
[3.5beta2] Action input will trigger even if incomplete, ignoring modifiers

### ISSUE THREAD

**Issue by adamscott** [godotengine/godot#59395] opened 2022-03-21 20:01 UTC
### Godot version

3.5.beta2.official

### System information

Windows 10

### Issue description

Modifiers on inputs are ignored in the 3.5beta2. An action with "Alt+Enter" keys binded will trigger on "Enter" key, whether or not "Alt" is pressed.

There is no issue of this type in 3.5beta1.

### Steps to reproduce

- Add an input action which includes a modifier (e.g. alt+enter)
- Try inputting the action without the modifier (e.g. enter)
- The action is considered triggered without the modifier

### Minimal reproduction project

[modifiers_ignored_on_input.zip](https://github.com/godotengine/godot/files/8318866/modifiers_ignored_on_input.zip)

**Comment by akien-mga** [comment] 2022-03-22 06:17
Duplicate of https://github.com/godotengine/godot/issues/57943, should be fixed in beta 3.

**Closed by akien-mga** 2022-03-22 06:18 UTC
Labels: bug, topic:input, regression
