### ISSUE TITLE
Debugger shows null on large arrays from FileAccess.get_buffer()

### ISSUE THREAD

**Issue by handre-dev** [godotengine/godot#71920] opened 2023-01-23 15:49 UTC
### Godot version

4.0.beta14 and previous

### System information

Windows 10 x64

### Issue description

Seems the debugger shows `PackedByteArray` with more than ~500k elements as `null`

### Steps to reproduce

- Call `var a = getbuffer(file.length())` on a random 1 MB file
- Inspect `a` in the debugger

### Minimal reproduction project

N/A

**Comment by Zireael07** [comment] 2023-01-23 16:42
I seem to remember it was already reported, but can't find it.

**Comment by Calinou** [comment] 2023-01-23 16:52
Duplicate of https://github.com/godotengine/godot/issues/70493.

**Closed by Calinou** 2023-01-23 16:52 UTC
