### ISSUE TITLE
Linux/windows Joystick Bug

### ISSUE THREAD

**Issue by gusthe** [godotengine/godot#6488] opened 2016-09-14 18:21 UTC
**Operating system or device - Godot version:**

Ubuntu 16.04
I'm not sure if it effects any other OS, as I only have a Linux machine.

Edit: I was able to get a hold of a machine running window 7.

Master

**Issue description** (what happened, and what was expected):

Joystick release events seems to not happen occasionally resulting in input events while the joystick has been released. 

Edit: Additionally once it has gotten stuck, moving the Joystick in any other direction like the opposite direction to the direction it is stuck on does not cancel out the effect. For example If it gets stuck in the right direction, moving the joystick left does not stop the right movement, and the character will continue to move right after releasing. Only moving in the effected direction cancels the effect.

I made sure it was not a bad gamepad on my end by testing two wired 360, and 5 wireless 360 game pads, and they all experience the same behaviour where direction input remains after completely releasing the joystick. 

I bisected the commit where it starts. https://github.com/godotengine/godot/commit/8c886b9d7a22bfacf25a5f3303c25c099abf55f9

Previous commits do not have the issue.

**Steps to reproduce:**

Map a joystick to any of the demo games. I used the 2d platformer demo, and mapped left and right movement to the joystick. It dosen't happen every time, but if you move the joystick left then quickly move right and release the joystick the moment it hits completely to the right the character will continue to move as if the joystick hasn't been released. It usually takes me two of three times before it happens. Moving the joystick in a 360 movement then releasing also causes as well.

**Link to minimal example project** (optional but very welcome):

**Comment by rgrams** [comment] 2016-09-14 19:37
I had the same issue on Windows. It seemed to be because there is no dead zone and the stick doesn't quite go back to 0 every time, but I'm not sure. I have one controller with a rather wobbly stick and it happens a lot with that one, less with tighter sticks. I wrote some GDScript code to manage the analog input myself and use a dead zone, now only the wobbly stick gets stuck on, and not every time.

**Comment by gusthe** [comment] 2016-09-14 19:44
This isn't related to deadzones. The stuck direction is still being imputed while moving the joystick in the opposite direction, and I've tested this on seven different gamepads.

**Comment by punto-** [comment] 2016-09-14 20:30
I think it's the same as #3727 ?

**Comment by gusthe** [comment] 2016-09-14 21:02
That sounds like the same issue. I have other controllers as well as a PS3 controller I could test if needed.

**Comment by gusthe** [comment] 2016-09-15 03:26
I was able to get a hold of my brothers computer with windows 7 to test this, and I get the same issue as I saw on Linux.

**Comment by Hinsbart** [comment] 2016-09-15 13:41
Ok, I can reproduce this but it's different from #3727, as in this case no events are actually lost.
You can check this by calling `Input.get_joy_axis(device, axis)` during the time when the stick is centered but still registered as pressed left or right. It will be something in the range of +-0.25 (obviously not pressed, the deadzone is 0.5).

The issue here is that the axis value quickly changes from a high (absolute > 0.5) value to one of the opposite sign, before first going back to the abs < 0.5 range. When this happens, it doesn't pick the right inputmap action, as that's dependant on the sign.

Example from my test project:
[Frame 1]
Event: JoystickMotion Axis: 0 Value: 0.936369 Pressed: True
(Value is > 0.5 and sign is postive, so action "right" is pressed)
[Frame 2]
Event: JoystickMotion Axis: 0 Value: -0.155797 Pressed: False
(Value is < 0.5, but sign is negative so action "left" is released instead of "right")

**Closed** 2016-09-17 16:37 UTC
Labels: bug, topic:core
