### ISSUE TITLE
Can't add nodes 

### ISSUE THREAD

**Issue by MrJeet-7** [godotengine/godot#64918] opened 2022-08-26 10:50 UTC
### Godot version

3.5 stable

### System information

Android 

### Issue description

Can't able to add node after adding 1st node 
Whenever I try to add any other note it just froze

### Steps to reproduce

Add one note using + icon after that press + icon again

**Comment by Calinou** [comment] 2022-08-26 18:31
Duplicate of https://github.com/godotengine/godot/issues/64166.

**Closed by Calinou** 2022-08-26 18:31 UTC
