### ISSUE TITLE
[Bug, Godot 4 Beta 4 C#] ExportAttribute string named "name" breaks *.generated.cs file's SetGodotClassPropertyValue function

### ISSUE THREAD

**Issue by roushk** [godotengine/godot#68773] opened 2022-11-17 07:15 UTC
### Godot version

Godot_v4.0-beta4_mono_win64

### System information

Windows 10 19043.2130, Visual Studio Community 2022 17.3.6

### Issue description

Porting C# 3.x project to 4.0 Beta 4, got the following errors inside of *.generated.cs files for a *.cs class file. my custom type derived from a Resource. Dug around and figured out it was because of the exported string's name. 

```
CS8331 Cannot assign to variable 'in godot_string_name' because it is a readonly variable
CS1503 Argument 1: cannot convert from 'Godot.NativeInterop.godot_string_name' to 'string?'
```

### Steps to reproduce

Create new variable on a C# class like so:
```
[Export]
public string name { get; set; } = "Test";
```
The public string named name will interfere with the .generated.cs file's SetGodotClassPropertyValue because the in godot_string_name variable is named "name" as well as the static StringName and because they're both strings  VS2022 fails to select the correct one and fails to build. 

Fixed by renaming the poorly named variable to Name or literally anything else. 

### Minimal reproduction project

DNA, Create new .cs script file. Add the new variable and build.

**Comment by raulsntos** [comment] 2022-11-17 11:57
Duplicate of https://github.com/godotengine/godot/issues/66819

**Closed** 2022-11-17 11:57 UTC
