### ISSUE TITLE
Renaming a file causes the FileSystem panel to lose focus

### ISSUE THREAD

**Issue by duianto** [godotengine/godot#56806] opened 2022-01-15 01:01 UTC
### Godot version

v3.4.1.stable.official [aa1b95889]

### System information

Windows 10 21H1

### Issue description

The FileSystem panel loses focus when a file is renamed.

It should be possible to select/rename multiple files,
without having to mouse click in the FileSystem panel first.

### Steps to reproduce

In the FileSystem panel
- Create a new script
- Rename the script
- Press `arrow up` or `arrow down` to select the previous or next file
- Or `F2` to rename the selected file again.

### Observed
`arrow keys`: Nothing happens.
`F2`: If a Scene panel node was selected before renaming the file,
then `F2` makes the Scene panel nodes text editable.

### Expected
The FileSystem panel should remain focused.

And the file/folder above or below the renamed file should become selected.
Or the rename window should open for the selected file.

**Comment by Calinou** [comment] 2022-01-15 01:05
Duplicate of https://github.com/godotengine/godot/issues/33126.

**Closed by Calinou** 2022-01-15 01:05 UTC
Labels: bug, topic:editor, usability
