### ISSUE TITLE
Color Picker Dropper not retrieving the correct colour

### ISSUE THREAD

**Issue by vybr** [godotengine/godot#15487] opened 2018-01-08 14:22 UTC
**Godot version:** fe841fe

**OS/device including version:**
Windows 7 - Radeon HD 6950

**Issue description:**

The colour picker DROPPER tool doesn't work correctly. As seen in the image below, selecting the darkest red color of the sprite gives blue instead. 
When selecting elements of Godot's UI I get the wrong shades of blue and sometimes purple with different alpha values.

[Example](https://imgur.com/1zG3we7)

**Comment by akien-mga** [comment] 2018-01-08 14:35
Duplicate of #14964.

**Closed by akien-mga** 2018-01-08 14:35 UTC
