### ISSUE TITLE
Folder color resets if folder is renamed or moved

### ISSUE THREAD

**Issue by miv391** [godotengine/godot#81366] opened 2023-09-06 09:19 UTC
### Godot version

v4.2.dev4.official [549fcce5f]

### System information

Godot v4.2.dev4 - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1060 6GB (NVIDIA; 31.0.15.3640) - Intel(R) Core(TM) i5-3570K CPU @ 3.40GHz (4 Threads)

### Issue description

If the folder has assigned a color, the color is reset to default when the folder name is changed. Also subfolder colors are reset.

Also moving a folder resets its and its subfolders' colors.

I would expect that renaming or moving doesn't rest the folder color. Especially if you have a large folder structure with many folder levels and assigned colors, it is a unfortunate to have all colors reset if the top level folder is renamed.

### Steps to reproduce

1. Create folder structure 

```
level1
	level2
		level3
```

2. Set folder colors to `level1` and `level2.`

3. Rename `level1` to `foobar` 

-> All folders are now using the default color.

### Minimal reproduction project

N/A

**Comment by AThousandShips** [comment] 2023-09-06 09:20
Duplicate of https://github.com/godotengine/godot/issues/81342

**Comment by AThousandShips** [comment] 2023-09-06 09:22
This is more of a missing feature than a bug, or an expected behaviour not included

**Comment by miv391** [comment] 2023-09-06 09:41
I guess it's not trivial to update the folder names in `project.godot`. Is the `project.godot` the only possible place to store the folder colors? How about adding e.g. `.custom` or `.settings` file in the folder itself. That file would then contain the folder color. Now renaming or moving the folder would not break the color.

**Comment by formerlybased** [comment] 2023-09-06 09:49
I think it would be possible to just update the project.godot when the folders are renamed, moved, or deleted to clear entries or update the colour, instead of putting a settings file _every single folder_

**Closed** 2023-09-08 22:00 UTC
Labels: enhancement, topic:editor
