### ISSUE TITLE
Magnet tool does not work when a 2D object is rotated

### ISSUE THREAD

**Issue by Raj2032** [godotengine/godot#16935] opened 2018-02-23 00:08 UTC
While the magnet tool is enabled, when I rotate a 2D object in Godot 3.0, when you move the object around suddenly it is no longer restricted to the magnet movements in terms of the x and y positions.

**Comment by Noshyaar** [comment] 2018-02-23 03:10
Duplicate of #14496
PR to fix #15573

**Closed by Noshyaar** 2018-02-23 03:10 UTC
