### ISSUE TITLE
Rapid Button Presses Not Being Registered Correctly on Android

### ISSUE THREAD

**Issue by kcl101** [godotengine/godot#39673] opened 2020-06-19 10:18 UTC
**Godot version:**

v3.2.stable.mono.official

**OS/device including version:**

Android 7.0 - GLES2 - ASUS Z01KD

**Issue description:**

Press Button1 then Button2 quickly, engine could not register button press on Button2, but register 2 presses on Button1 instead.

**InputEventScreenTouch can register correct touch positions. I don't know what is wrong.

**Steps to reproduce:**
1. Create 2 (or more) buttons
2. Write code to print a line (in debug console or on screen) when each button is pressed
3. Deploy on Android, press different buttons quickly.
4. Read the printed lines.

**Minimal reproduction project:**

[ButtonTest.zip](https://github.com/godotengine/godot/files/4803918/ButtonTest.zip)

**Comment by akien-mga** [comment] 2020-06-19 10:59
Duplicate of #35655, fixed in 3.2.1.

**Closed by akien-mga** 2020-06-19 10:59 UTC

**Comment by kcl101** [comment] 2020-06-19 11:05
Thank you!
