### ISSUE TITLE
Incorrect Mipmapping with non power 2 textures

### ISSUE THREAD

**Issue by DualLayer** [godotengine/godot#17993] opened 2018-04-05 08:15 UTC
**Godot version:**
Godot_v3.0.2-stable

**OS/device including version:**
- Win 10 64 Bit
- GeForce GTX 1080 - Driver: 388.13

**Issue description:**
Imported "non power two" images with activated mipmaps look grainy when scaled down.

Left rocket is non power two, right image is power two. Both images have identical import settings
![screenshot](https://user-images.githubusercontent.com/20717445/38353852-08c1f024-38b8-11e8-85a3-0604a27f28f2.png)

It's related with https://github.com/godotengine/godot/issues/16367, but I'm not sure if it is a duplicate.

This issue doesn't appear in 2.1.5-rc even when the image is explicitly imported with mipmaps.

**Minimal reproduction project:**
[MipMaps.zip](https://github.com/godotengine/godot/files/1879042/MipMaps.zip)

**Comment by akien-mga** [comment] 2018-04-05 11:35
That's a duplicate of #16367.

**Closed by akien-mga** 2018-04-05 11:35 UTC
Labels: bug, topic:rendering
