### ISSUE TITLE
[4.0 stable] Node3D global_position and global_rotation variables not set before calling add_child

### ISSUE THREAD

**Issue by MackyK** [godotengine/godot#74631] opened 2023-03-09 02:47 UTC
### Godot version

4.0 stable

### System information

Windows 10

### Issue description

When setting global_position or global_rotation variables after creating a Node3D in code then using add_child to append it to the current node. Only the last one is set and the others are ignored.

### Steps to reproduce

Create Node3D variable in code
`var node3d = Node3D.new()`

Set Positions before add_child
```
node3d.global_position.x = 64 
node3d.global_position.z = 64
```

then add_child to Node
`add_child(node3d)`

Only the global position Z is set.

### Minimal reproduction project

[bug.zip](https://github.com/godotengine/godot/files/10927163/bug.zip)

**Comment by dalexeev** [comment] 2023-03-09 04:26
To me this looks to be expected. Until you add a node to the tree, it cannot have a global position, rotation, etc., since we don't yet know which branch the node will be added to. Perhaps we need to clarify this point in the docs and/or add a warning.

**Comment by capnm** [comment] 2023-03-09 06:27
> Only the global position Z is set.

I think that should not happen??

> To me this looks to be expected. Until you add a node to the tree, it cannot have a global position, rotation, etc., since we don't yet know which branch the node will be added to. Perhaps we need to clarify this point in the docs and/or add a warning.

```ERROR: Condition "!is_inside_tree()" is true. Returning: Transform3D()
   at: get_global_transform (scene/3d/node_3d.cpp:308)
ERROR: Condition "!is_inside_tree()" is true. Returning: Transform3D()
   at: get_global_transform (scene/3d/node_3d.cpp:308)
ERROR: Condition "!is_inside_tree()" is true. Returning: Transform3D()
   at: get_global_transform (scene/3d/node_3d.cpp:308)
ERROR: Condition "!is_inside_tree()" is true. Returning: Transform3D()
   at: get_global_transform (scene/3d/node_3d.cpp:308)
ERROR: Condition "!is_inside_tree()" is true. Returning: Transform3D()
   at: get_global_transform (scene/3d/node_3d.cpp:308)
ERROR: Condition "!is_inside_tree()" is true. Returning: Transform3D()
   at: get_global_transform (scene/3d/node_3d.cpp:308)
```

https://github.com/godotengine/godot/blob/dac2d8fb4214d3394bfb33b28f35f6d1e61518a8/scene/3d/node_3d.cpp#L308

Another good example of how the Godot's excessive use of warnings/errors may not be a good approach. If a node is outside the tree, I would probably just **document** it as NOP and _return_ here...

**Comment by akien-mga** [comment] 2023-03-09 06:57
Duplicate of #30445

**Closed by akien-mga** 2023-03-09 06:57 UTC
