### ISSUE TITLE
setget doesn't work on export variables

### ISSUE THREAD

**Issue by blurymind** [godotengine/godot#10859] opened 2017-09-01 13:47 UTC
In this video
https://youtu.be/whRWwVFGxms?t=4m16s

The presenter adds a setget on a variable that is exposed to the editor. Then tests it with a print like this:

```
#tool #<-- when enabled, test prints only in terminal, but not in the output area of the editor
export (int) var myvar setget myvar_set,myvar_get

func myvar_set(newvalue):
	print("Test") #<-- doesn't print
	myvar=newvalue

func myvar_get():
	return myvar # getter must return a value
```
When he changes the variable in editor, while the game is not running, the test message prints out 

In Godot 2.1.4 and 2.1.2 this doesn't work

**Comment by akien-mga** [comment] 2017-09-01 13:55
Well it seems to work in 2.1 according to #10856. Is it a regression?

**Comment by blurymind** [comment] 2017-09-01 13:59
@akien-mga This seems to be a bug that is specific to the output area of the editor.
The message does print out in terminal:
![outputsetget](https://user-images.githubusercontent.com/6495061/29973066-20eb1cc0-8f26-11e7-84db-8cc7763d6f18.PNG)

**Comment by Noshyaar** [comment] 2017-09-01 16:31
Duplicate of #8748?

**Comment by blurymind** [comment] 2017-09-02 00:53
@Noshyaar  yeah you are right. they look similar.

In my bug report however I would like to note that the print failure happens in a setget function specifically.
An exported setget print as described in the first post should work even without the 'tool' keyword btw

So the bigger problem in the bug report for me is that it doesnt print out in the setget function, considering that it's variable is exposed to the editor. It doesnt print out even in cmd terminal when the script is not in tool mode. This leads me to believe that setgets on exported variables no longer work as expected - not only the prints

**Comment by fleskesvor** [comment] 2017-11-08 22:57
I have a similar project where I have a KinematicBody2D with a child Sprite, and I'm exporting the texture of the Sprite as a variable with a setget from a script attached to the Kinematic so that I can use it as a common base for a player character and a crate, which have similar properties. What's interesting though, is that the setter seem to be working, as it's updating the texture when set in the editor. However, I've tried adding print statements to the setter, but I'm not seeing any output in the editor, except the default "Set texture". Whether it's a tool or not seems to make no difference. I have made the extending scripts tools though, since otherwise I wouldn't see their textures while working with them in the editor.

Here's my small project which shows how I have this set up currently:

https://github.com/fleskesvor/game-off-2017/tree/2f79879ee88a1c17e758982a64c300c158be0b52

**Comment by akien-mga** [comment] 2018-09-17 14:19
The 2.1 branch is no longer actively worked on by engine developers, unless critical fixes are needed for current games in production. As such we are now closing non-critical bug reports affecting only the 2.1 branch.

Please comment if this was incorrectly triaged and is still relevant in 3.x versions.

**Closed by akien-mga** 2018-09-17 14:19 UTC
Labels: bug, topic:editor
