### ISSUE TITLE
question about websockets ?

### ISSUE THREAD

**Issue by JoseMcMaster** [godotengine/godot#11415] opened 2017-09-19 13:21 UTC
> On 22 June 2016, Godot received a $20,000 Mozilla Open Source Support (MOSS) “Mission Partners” award to be used to add Web Sockets, WebAssembly and WebGL 2.0 support.[16]

just curious if web socket support is planned yet? i know a lot of work has been don with 3.0, but i'm currently wanting to use the [uws nodejs](https://github.com/uNetworking/bindings/tree/master/nodejs) library (**fastest** websocket lib for nodejs), and really want to use Godot with it!!

i have a large game i made in html 5 that uses that library but don't really want to mess with TCP and doing my own message protocol solution.  but, game is around 10,000 lines of code and already converting it over to Godot now with the beautiful `gdscript` language. really easy coming from javascript tbh :) cannot wait

god bless, ty for the engine!!  sorry for english

**Comment by akien-mga** [comment] 2017-09-19 13:23
Duplicate of #5806.

**Closed by akien-mga** 2017-09-19 13:23 UTC

**Comment by JoseMcMaster** [comment] 2017-09-19 13:25
why you close my thread?

**Comment by akien-mga** [comment] 2017-09-19 13:27
Because it's a duplicate of the other issue I mentioned above. To keep the issue tracker efficient, we need to avoid spreading conversation about a same topic over different issues. So you can read issue #5806 instead and enquire of the status there if need be :)

**Comment by JoseMcMaster** [comment] 2017-09-19 13:30
ok ty, thought this was forum :)
