### ISSUE TITLE
GLES2 depth broken on AMD hardware

### ISSUE THREAD

**Issue by danilw** [godotengine/godot#36812] opened 2020-03-05 11:13 UTC
**Godot version:**
3.2 stable

**OS/device including version:**
Windows 10

**Issue description:**
GLES2 depth broken in AMD video driver.
AMD Vega 8 hardware. (on other AMD hardware same)

**Steps to reproduce:**
1. **GLES2** download this [gles2 build](https://danilw.github.io/godot-utils-and-other/bug_depth/gles2_depth_exe.zip) and run its exe
that what I see on AMD 
![1](https://danilw.github.io/godot-utils-and-other/bug_depth/img/amd_gles2_bug_m.png)

2. **GLES3** download this [gles3 build](https://danilw.github.io/godot-utils-and-other/bug_depth/gles3_depth_exe.zip) and run its exe
everything work correct
![2](https://danilw.github.io/godot-utils-and-other/bug_depth/img/amd_gles3_nbug_m.png)

**Minimal reproduction project:**
source zip [link](https://danilw.github.io/godot-utils-and-other/bug_depth/gles2_depth.zip)

**Comment by danilw** [comment] 2020-03-05 11:46
I made also [bugreport to AMD](https://community.amd.com/thread/249742), maybe its their driver bug

**Comment by akien-mga** [comment] 2020-03-05 12:06
I can't reproduce it on Linux with AMD Radeon RX Vega M (Mesa 19.3.4, kernel 5.5.6).

**Comment by danilw** [comment] 2020-03-05 12:32
@akien-mga because I write:

OS/device including version:
**Windows 10**

.............

**Comment by akien-mga** [comment] 2020-03-05 13:02
I saw that, but it's still relevant information that it can't be reproduced on Linux, and is therefore likely a Windows-specific issue. You reproducing it on Windows doesn't mean by itself that it's a Windows-only problem.

**Comment by danilw** [comment] 2020-03-05 19:39
maybe related to https://github.com/godotengine/godot/issues/33273

**Comment by Calinou** [comment] 2020-10-04 15:01
Duplicate of https://github.com/godotengine/godot/issues/33273.

**Closed by Calinou** 2020-10-04 15:01 UTC
Labels: bug, topic:rendering
