### ISSUE TITLE
[Godot Beta 7] Selecting world environment background mode to canvas causes some glitches on the scene view window when selecting a node.

### ISSUE THREAD

**Issue by AdilDevStuff** [godotengine/godot#69502] opened 2022-12-02 18:03 UTC
### Godot version

Godot 4 beta 7

### System information

Windows 10 22H2  (OS Build 19045.2251) GPU: AMD RADEON R7 Built-in Gpu

### Issue description

![image](https://user-images.githubusercontent.com/94475453/205355603-03146b49-c63a-4395-9281-f47ee44dbea2.png)

This glitch happens when i select the background mode of world env node to canvas and then select any node in my hierarchy window.

### Steps to reproduce

**HOW TO REPRODUCE THE BUG** 

1. Add World Environment Node to a 2d scene
2. Set the background to canvas mode
3. Add any other node or a tilemap node as the child of the main scene.
4. Select any node from your hierarchy.
5. Boom, the screen is glitched

If the bug is not reproduced, this might be happening only with me, but do check!

### Minimal reproduction project

N\A

**Comment by Zireael07** [comment] 2022-12-02 18:07
Duplicate of https://github.com/godotengine/godot/issues/69122 (same cause).

**Comment by AdilDevStuff** [comment] 2022-12-02 18:09
> Duplicate of #69122 (same cause).

its not same, here its glitching the scene view and that bug is already fixed in godot 4 beta 7

**Comment by AdilDevStuff** [comment] 2022-12-02 18:15
> > GPU: AMD 7600 RADEON R7
> 
> To clarify, are you using a recent Zen 4 CPU with integrated graphics (Ryzen 7600X) or an older dedicated GPU?

Its older dedicated gpu

**Comment by clayjohn** [comment] 2022-12-05 20:02
> Duplicate of #69122 (same cause).

I don't think this is a duplicate of #69122. I think this is the same as https://github.com/godotengine/godot/pull/68805#issuecomment-1326611296

**Comment by clayjohn** [comment] 2023-02-23 19:32
I think this is fixed, but I was never able to reproduce in the first place. Can you test again with RC3?

**Comment by AdilDevStuff** [comment] 2023-02-23 19:48
Its fixed now! It just happened on the beta builds but now working fine on rc versions

**Closed** 2023-02-23 20:07 UTC
Labels: bug, topic:rendering, confirmed, topic:2d
