### ISSUE TITLE
Can't open C# scripts with spaces in path in external IDE because Godot doesn't escape/parse spaces in quoted args properly

### ISSUE THREAD

**Issue by geekley** [godotengine/godot#86368] opened 2023-12-21 00:04 UTC
### Tested versions

Reproducible in:
- v3.5.3.stable.mono.official [6c814135b]
- v4.2.1.stable.mono.flathub [b09f793f5]

### System information

Kubuntu 23.10 amd64 Linux 6.5.0-14-generic | Freedesktop SDK 23.08 (Flatpak runtime)

### Issue description

The editor settings for `mono|dotnet/editor/...` don't support paths with spaces at all as arguments. This is both in the built-in IDE options as well as when setting custom args. Quoting `{file}` (and probably `{project}` too) won't solve the issue. This seems to be a bug similar to #72935, so maybe it should have a similar fix.
I have only tested this on Kubuntu, but presumably a similar issue happens on other OSes like Windows.

Fix: Please make sure arguments are properly parsed (both in custom and in built-in IDE options) and sent to the executable considering the possibility of containing spaces.

Proposed compatible fix:
For custom args, make sure:
1. `{file}` and `{project}` are substituted with the escaped path.  
    Implementation possibilities (e.g. for `--goto {file}:{line}:{col}`):
    a. Replace with quoted path, e.g. `--goto "/path with spaces/my script.cs":1:2`. This is simpler and more intuitive.
    b. Replace with escaped path, e.g. `--goto /path\ with\ spaces/my\ script.cs:1:2`. Investigate which character sequences other than space, quotes and backslash may need to be escaped.
    c. Replace raw, but expect user to quote it like `--goto "{file}":{line}:{col}`. Not recommended because it kinda breaks current settings and you still need to properly parse the quoted args in the result anyway.
2. Properly parse the resulting args like a shell would, correctly escaping characters and treating quoted parts like an atomic argument part without splitting. May require a regex(-like behavior) to apply the split and some research to do it properly wrt. escaping sequences (which shell/syntax to use?), but shouldn't be too difficult. It's important this works independently of the substitution because arbitrary custom args unrelated to the variables above could also need to accept spaces.

Alternative (breaking?) fix:
An easier and IMO much better alternative would be to convert the args setting into a string array. This simplifies the code handling it and makes the intent more explicit on the user side too, without having to worry about shell-like escaping/quoting syntax (is it different cross-platform? I dunno). Maybe there's a way to avoid breakage by accepting both a string and a string array for that setting?

Note: it's unlikely, but just in case, I haven't tested if the same issue happens on the other setting, i.e. the executable path when it contains spaces. I only tested custom/built-in args with spaces for `{file}` name like described below.

Note 2: These settings are undocumented in the editor tooltips and API. Use this opportunity to also add tooltip docs e.g. with info from https://docs.godotengine.org/en/stable/tutorials/editor/external_editor.html#using-an-external-text-editor

### Steps to reproduce

1. Create a new C# script in .NET/Mono-enabled Godot with a path containing spaces (e.g. in the script itself or in a parent folder, like: `res://new folder/new_script.cs`).
2. Have **Editor Settings > Mono/Dotnet Editor > External Editor** set to something other than Disabled. The bug can be easily seen when it's set to VSCode (Codium is what I used to test). You may also use custom args to see how even quoting the args in the setting won't solve the issue - e.g. in Flatpak'd Godot: `flatpak-spawn` `--host code {project} -g "{file}:{line}:{col}"` or with `--goto "{file}":{line}:{col}`.
3. Double click the script to open it in the IDE.

VSCode opens more than one file because the space in the path is being inserted in a way that breaks it into multiple arguments. So, instead of loading the correct file, it opens e.g. 2 untitled documents for each part of the broken path. Even if you quote `{file}` in the custom args, it won't work, and even the `"` character may be sent as part of the argument too.

### Minimal reproduction project (MRP)

N/A

**Comment by raulsntos** [comment] 2023-12-23 04:11
Escaping command line arguments is extremely complicated and difficult to get right for every platform and shell. I think it's not feasible to handle everything ourselves, but if we had the arguments as an array we should be able to use the [`ProcessStartInfo.ArgumentList`](https://learn.microsoft.com/en-us/dotnet/api/system.diagnostics.processstartinfo.argumentlist) property and let .NET take care of it.

To launch the editor we are already using `ProcessStartInfo.ArgumentList`, but since the editor setting is a single string we still have to split it. It seems we're currently splitting the arguments string by space, but we don't replace `{file}` and `{project}` until after splitting to avoid splitting paths with spaces in its name.

https://github.com/godotengine/godot/blob/13a0d6e9b253654f5cc2a44f3d0b3cae10440443/modules/mono/editor/GodotTools/GodotTools/GodotSharpEditor.cs#L195-L253

In the case of the built-in editor options we are also using `ProcessStartInfo.ArgumentList` but here we don't have to split a string, we already construct the list of arguments as separate strings so I'd expect .NET to take care of escaping the arguments correctly.

So I think this should already be working similar to how you describe in option **1.b**.

In my testing, I've been unable to reproduce with Godot 4.2.1 in Linux with VSCode (both the built-in option and the custom editor option) with a project with spaces in the path.

Can you try Godot 4 without using Flatpak? AFAIK the flatpak is [not official](https://github.com/flathub/org.godotengine.Godot/issues/141) so I don't know if everything is setup correctly or if Flatpak sandboxing may be messing with launching processes or something.

You also mention that this issue applies to Godot 3, I haven't tested it but since we can't use `ProcessStartInfo.ArgumentList` there (because it requires at least .NET 5) I'd say it's very likely that it could fail. However, looking at the 3.x implementation it looks like we quote every argument that contains spaces and I feel like that should be good enough:

https://github.com/godotengine/godot/blob/4c4cb12e38dd862c1eedcb8ad17ca39ae9e3474e/modules/mono/editor/GodotTools/GodotTools/Utils/OS.cs#L166-L171

**Comment by geekley** [comment] 2023-12-23 04:41
Oof, never mind. I'm so dumb. Turns out it was a problem on my machine.

I'm using VSCodium instead of VSCode so I was redirecting the `code` command like this in my local bin path:
```sh
#!/usr/bin/env bash
/snap/bin/codium --unity-launch $@
```
I guess back then I didn't know you should ***always*** quote the `"$@"` in such scripts.

I'm embarrassed, sorry. This bug is invalid.
@raulsntos Feel free to close this as I suppose the args as strings suggestion is also no longer needed or useful (?)

**Comment by raulsntos** [comment] 2024-04-11 17:27
Closing as resolved.

**Closed by raulsntos** 2024-04-11 17:27 UTC
Labels: bug, needs testing, topic:dotnet
