### ISSUE TITLE
Rigidbody's force and torque should be constant

### ISSUE THREAD

**Issue by raphael10241024** [godotengine/godot#30061] opened 2019-06-25 07:42 UTC
**Issue description:**

According to the document and consistence with RigidBody2D's behavior, RigidBody's applied force and torque should be constant, but it's cleared each frame now.

**Comment by madmiraal** [comment] 2020-06-04 17:03
#38646 is a duplicate of this, but since there is more of a discussion there, I suggest closing this one.

**Closed by madmiraal** 2020-06-04 17:03 UTC
Labels: documentation, enhancement, topic:physics
