### ISSUE TITLE
Compilation error on Linux

### ISSUE THREAD

**Issue by nimenko** [godotengine/godot#13076] opened 2017-11-20 06:02 UTC
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Arch Linux, 8e6c281a0489ee908eb1666d30b65fb22edba670.

**Issue description:**

Godot Engine compilation fails on Linux.

**`scons platform=x11 -j 4`**

> scons: Reading SConscript files ...
> Enabling ALSA
> Enabling PulseAudio
> YASM is necessary for WebM SIMD optimizations.
> WebM SIMD optimizations are disabled. Check if your CPU architecture, CPU bits or platform are supported!
> Checking for C header file mntent.h... (cached) yes
> scons: done reading SConscript files.
> scons: Building targets ...
> [ 49%] Compiling ==> drivers/unix/os_unix_global_settings_path.gen.cpp
> [ 49%] Compiling ==> drivers/unix/stream_peer_tcp_posix.cpp
> [ 49%] Compiling ==> drivers/windows/shell_windows.cpp
> [ 49%] Compiling ==> drivers/windows/file_access_windows.cpp
> [ 49%] Compiling ==> drivers/windows/thread_windows.cpp
> [ 49%] Compiling ==> drivers/windows/dir_access_windows.cpp
> [ 49%] Compiling ==> drivers/windows/mutex_windows.cpp
> [ 49%] Compiling ==> drivers/windows/semaphore_windows.cpp
> [ 49%] Compiling ==> drivers/windows/rw_lock_windows.cpp
> [ 49%] Compiling ==> drivers/alsa/audio_driver_alsa.cpp
> [ 49%] Compiling ==> drivers/coreaudio/audio_driver_coreaudio.cpp
> [ 50%] Compiling ==> drivers/pulseaudio/audio_driver_pulseaudio.cpp
> drivers/unix/os_unix_global_settings_path.gen.cpp:3:44: error: no 'String OS_Unix::get_global_settings_path() const' member function declared in class 'OS_Unix'
>  String OS_Unix::get_global_settings_path() const {
>                                             ^~~~~
> scons: *** [drivers/unix/os_unix_global_settings_path.gen.x11.tools.64.o] Error 1
> scons: building terminated because of errors.

**Comment by rubenjavier** [comment] 2017-11-20 06:24
I can confirm this error
Ubuntu 16.04 64bits commit 8e6c281a0489ee908eb1666d30b65fb22edba670

**Comment by djrm** [comment] 2017-11-20 06:27
just delete that file

**Comment by djrm** [comment] 2017-11-20 06:27
drivers/unix/os_unix_global_settings_path.gen.cpp

**Comment by akien-mga** [comment] 2017-11-20 06:48
Yes, that file is now obsolete and should be removed manually.

**Comment by rubenjavier** [comment] 2017-11-20 06:53
Thanks, that worked, please remove the file from the git repo to avoid this for the other linux users.

**Comment by akien-mga** [comment] 2017-11-20 06:54
It's not in the git repo, that's why you need to remove it manually.

**Comment by rubenjavier** [comment] 2017-11-20 06:56
Got it, thanks

**Comment by akien-mga** [comment] 2017-11-20 08:03
Closing as it's not a bug, but I've referenced it in #13064 so that people find it.

**Comment by akien-mga** [comment] 2017-11-20 09:40
Well let's keep it open for a while so that it shows up when people look for potential duplicates.

**Closed** 2017-11-20 22:56 UTC
Labels: archived, platform:linux, platform:osx, topic:buildsystem

**Comment by AllanDaemon** [comment] 2017-12-06 19:44
I had this problem too. But I tried to use `scons -c` or `scons -c p=x11` for deleting the files and it didn't solve it. So, am I using the scons wrong or the clean up process is supposed to clear this file?

**Comment by akien-mga** [comment] 2017-12-06 20:04
`scons -c` doesn't know about our generated files and doesn't clear them, so you need to delete them manually when such errors happen (but they're rare, only when we change the names of generated files).
