### ISSUE TITLE
tile_get_name, why returns name + ID of the tile?

### ISSUE THREAD

**Issue by Torguen** [godotengine/godot#90423] opened 2024-04-09 08:24 UTC
### Tested versions

v3.6.beta4.official [93ac21cf8]

### System information

w10 64

### Issue description
The tile name should not include the ID.
When I use tile "tile_get_name( ID )" I already include the ID, what is the use of obtaining the ID assigned to the name of the tile?
The "tile_get_name" function indicates that it returns the name of the tile, not the ID.
Now I must separate the ID from the tile name, because I only need the tile name.
The problem is not that I should split the returned string (or maybe yes), the problem is that that is not what I would expect to obtain, I did not request the ID, just the name.
I consider this something to solve.

My tileset name is:
terrain.png
When use tile_get_name obtain:
terrain.png X
The name includes his ID

### Steps to reproduce

Simply get the name of a tile using "tile_get_name( ID )" from a tilemap node.

### Minimal reproduction project (MRP)

...

**Comment by AThousandShips** [comment] 2024-04-09 10:50
The default name of the tile if you haven't set it is the file plus the id, otherwise what would it be called if you have multiple tiles?

**Comment by Torguen** [comment] 2024-04-09 15:04
Ok I understand, I had not taken that into account, the ID is used to distinguish when there is more than one mosaic.

**Comment by AThousandShips** [comment] 2024-04-09 15:13
It should not add this if you actually set the name of the tile, please confirm

**Comment by Torguen** [comment] 2024-04-09 15:37
Confirmed, I assume that godot adds the index to the name only when the tile is created. Afterwards it never changes the name again.

**Comment by lawnjelly** [comment] 2024-04-12 09:52
Closing as this seems to be expected behaviour.

**Closed by lawnjelly** 2024-04-12 09:52 UTC
Labels: discussion, topic:2d
