### ISSUE TITLE
Object was deleted while awaiting a callback

### ISSUE THREAD

**Issue by Gerarama** [godotengine/godot#40594] opened 2020-07-22 12:11 UTC
**Godot version:**
Godot 3.2.2 Stable

**OS/device including version:**

Windows 10 1909 . 451.67 Nvidia GTX 1070

**Issue description:**

when you open a project, the commend display `Object was deleted while awaiting a callback` repeatedly provent me from getting into the project.

**Steps to reproduce:**
Its not clear, but it happen when you close a project, and reopen it.

In theory it happen when you quit without saving, or quit while having many tabs and scripts openned, or quit when you have just finished playing.

![as5](https://user-images.githubusercontent.com/61591052/88174844-3b5c9180-cc25-11ea-9a0a-7193a2d74a7e.gif)

**Comment by Xrayez** [comment] 2020-07-22 13:56
Yeah this is a known issue: #35653. The current workaround is increasing the `memory/limits/message_queue/max_size_kb` in project settings (I have it set to like 4096, just to be sure).

Honestly I'd change the default to like 2048 at least.

**Comment by Calinou** [comment] 2020-07-22 14:13
Duplicate of #35653 (the underlying issue is the same).

**Closed by Calinou** 2020-07-22 14:13 UTC

**Comment by Gerarama** [comment] 2020-07-22 15:02
I have checked #35653 before i opened this, i thought its normal to have this message, but having it repeate infinitely is the problem.
