### ISSUE TITLE
Extending TileMap causing crash from Add Child Dialog

### ISSUE THREAD

**Issue by Haledire** [godotengine/godot#58054] opened 2022-02-13 15:21 UTC
### Godot version

4.0 alpha 2

### System information

Windows 10

### Issue description

Creating a script extending `TileMap` with a class_name identifier is removing `TileMap` from the Add Child dialog window.
Because it has been removed, if you attempt to do anything in the Dialog that would try to select `TileMap` (typing in `T` with a Node2D scene open for example) will crash the editor.

### Steps to reproduce

Create a script file that extends `TileMap` and give that script a class_name:

```
extends TileMap
class_name RandomName
```

create a scene with a `Node2D` root, click the `+` button to add a child node.  If you don't immediately crash (which is also a possibility) scroll down to where `TileMap` should be in the `Node2D` class list and notice it isn't there.

![image](https://user-images.githubusercontent.com/164616/153759940-1b022bdb-dde8-4240-8b2c-e5d59272405c.png)

type `t` and the editor will crash attempting to select `TileMap` which is supposed to be the first entry it will react to because a `Node2D` scene is open.

Bizarrely this is specific to `TileMap`, the same behaviour isn't seen by Node, Node2D, or CharacterBody2D which I have checked (did not go through the entire list of nodes to test this)

### Minimal reproduction project

[TileMapExtendsIssue.zip](https://github.com/godotengine/godot/files/8055862/TileMapExtendsIssue.zip)

**Comment by jmb462** [comment] 2022-02-13 16:43
May be related to #57573

**Comment by KoBeWi** [comment] 2022-02-17 19:20
Duplicate of #57573 (same stack trace)

**Closed by KoBeWi** 2022-02-17 19:20 UTC
Labels: bug, topic:editor, crash, topic:2d
