### ISSUE TITLE
Spamming errors in iOS export

### ISSUE THREAD

**Issue by DavidMag** [godotengine/godot#64509] opened 2022-08-16 20:20 UTC
### Godot version

4.0.alpha14

### System information

MacOS Monterey 12.5, MacBook Pro 16" (intel), Forward Mobile

### Issue description

Getting an error message when launching a basically empty projected exported to iOS.

I'm not using RefCounted in the project at all.
<img width="780" alt="image" src="https://user-images.githubusercontent.com/22000931/184977153-69d52ef0-d389-4718-8d49-eef16e091de3.png">

This is the error and just the startup I get over 1000 matches when searching "StringName" in the logs
```
2022-08-16 22:10:48.761756+0200 Godot_Ios_Issues[89170:6545352] USER ERROR: Cannot get class 'RefCounted'.
2022-08-16 22:10:48.761766+0200 Godot_Ios_Issues[89170:6545352]    at: _get_parent_class (core/object/class_db.cpp:144) - Condition "!ti" is true. Returning: StringName()
USER ERROR: Cannot get class 'RefCounted'.
```
<img width="192" alt="image" src="https://user-images.githubusercontent.com/22000931/184976846-a053b669-3902-4686-94ff-3c0fc9a1d33f.png">

**I also have a bigger project where I get the same issue but also get the same message every input I do.**

### Steps to reproduce

Just export a project to iOS and run on a device (have not tested on emulator)

### Minimal reproduction project

To avoid the size from getting to big I won't include an export but just say the word and I will provide that as well.
[Uploading godot_ios_issues.zip…]()

**Comment by akien-mga** [comment] 2022-08-29 10:28
Duplicate of #64508.

**Closed by akien-mga** 2022-08-29 10:28 UTC
Labels: bug, platform:ios, topic:porting, needs testing
