### ISSUE TITLE
IDE frozen after waking up from sleep on Linux Mint

### ISSUE THREAD

**Issue by Colins2** [godotengine/godot#76807] opened 2023-05-07 13:56 UTC
### Godot version

Godot_v4.0.2-stable_linux.x86_64

### System information

Linux Mint 21

### Issue description

If the IDE is open when the computer goes to sleep, either automatically after a timeout, or after using the sleep button, (which I do every night when I am finished) when I wake the computer up, the IDE is frozen and has to be 'killed' and re-started. Other programs simply resume.

### Steps to reproduce

For me, simply putting the computer to sleep and waking it up again. 

### Minimal reproduction project

It doesn't seem to be project reated.

**Comment by Zireael07** [comment] 2023-05-07 14:50
What is your GPU? Most similar issues reported in the past were down to bad resume behavior on part of the GPU

**Comment by Colins2** [comment] 2023-05-07 15:02
Current GPU is Nvidia GTX 1650s. CPU is Xeon E5-1660, 32gb ram.
sleeping/waking up is not normally an issue.

**Comment by Calinou** [comment] 2023-05-07 15:08
- Duplicate of https://github.com/godotengine/godot/issues/52738.

**Closed by Calinou** 2023-05-07 15:08 UTC

**Comment by Colins2** [comment] 2023-05-07 15:21
For me, the editor (IDE) is completely frozen, nothing works at all. Others have mentioned varying degrees of 'frozen-ness' mine is complete.
I have not found any other program that freezes like this. I regularly sleep with Qt Creator running, QGis, Virtual Box, and I never shut down Firefox with GMail open and normally other tabs but of course, this is all 1 app, Firefox.

**Comment by Calinou** [comment] 2023-05-07 15:30
>  I have not found any other program that freezes like this. I regularly sleep with Qt Creator running, QGis, Virtual Box, and I never shut down Firefox with GMail open and normally other tabs but of course, this is all 1 app, Firefox.

These programs either don't use hardware acceleration, or they use OpenGL instead of Vulkan.

**Comment by imvenx** [comment] 2025-01-17 15:34
same problem

**Comment by Calinou** [comment] 2025-01-20 18:40
> same problem on 4.3, now on 4.4 beta it just crashes

Please continue the discussion in https://github.com/godotengine/godot/issues/52738.
