### ISSUE TITLE
Godot 1.0 Stable isn't on 'older' MacOS :)

### ISSUE THREAD

**Issue by robertwatkins** [godotengine/godot#1283] opened 2015-01-20 16:31 UTC
the MacOS version crashes on launch.
__________________________________
My system:
__________________________________
Model Name:	MacBook
  Model Identifier:	MacBook4,1
  Processor Name:	Intel Core 2 Duo
  Processor Speed:	2.1 GHz
  Number Of Processors:	1
  Total Number Of Cores:	2
  L2 Cache:	3 MB
  Memory:	4 GB
  Bus Speed:	800 MHz
  Boot ROM Version:	MB41.00C1.B00

____________________________
GDB output
____________________________
robert-watkinss-macbook:MacOS rwatkins$ set start-with-shell 0
robert-watkinss-macbook:MacOS rwatkins$ gdb ./Godot
GNU gdb 6.3.50-20050815 (Apple version gdb-1515) (Sat Jan 15 08:33:48 UTC 2011)
Copyright 2004 Free Software Foundation, Inc.
GDB is free software, covered by the GNU General Public License, and you are
welcome to change it and/or distribute copies of it under certain conditions.
Type "show copying" to see the conditions.
There is absolutely no warranty for GDB.  Type "show warranty" for details.
This GDB was configured as "x86_64-apple-darwin"...unable to read unknown load command 0x80000028

warning: Unable to read symbols for /usr/lib/libc++.1.dylib (file not found).

warning: Unable to read symbols from "libc++.1.dylib" (not yet mapped into memory).

warning: Unable to read symbols for /System/Library/Frameworks/CoreGraphics.framework/Versions/A/CoreGraphics (file not found).

warning: Unable to read symbols from "CoreGraphics" (not yet mapped into memory).
Reading symbols for shared libraries ........... done
unable to read unknown load command 0x80000028

(gdb) run
Starting program: /Applications/Godot.app/Contents/MacOS/Godot 
warning: The target crashed on startup, maybe the shell is crashing.
"Try set start-with-shell 0" to workaround.
Abort trap

**Comment by TheoXD** [comment] 2015-01-20 16:45
My guess is that your computer is too old, Godot doesn't work on old GMA graphics cards, your laptop has GMA X3100, which I believe is considered as old.

**Comment by Krzycho666** [comment] 2015-01-21 01:27
I was going to write, that OpenGL 2.1 should be enough, but then I realized, that framebuffers came in OpenGL 3.0 - sorry...

**Comment by tonymtbird** [comment] 2015-01-21 04:04
godot is working fine on OSX 10.10

**Comment by robertwatkins** [comment] 2015-01-21 17:58
Sadly, it seems that I have a system old enough to not support the requirements. So, for others that may be experiencing the same kind of issues, would these steps be appropriate for them to determine if their mac hardware doesn't support this app?

click apple menu -> about this mac -> more info 
Then expand 'hardware' -> 'Graphics/Displays' and read the 'Chipset Model' information.

check out Apple's information on hardware support (https://developer.apple.com/opengl/capabilities/GLInfo_1075.html ) 
 - You may need to toggle the 'Legacy' / 'Core' links
 - You may also need to search for the specific version of OSX using the links on the page
 - For example, I have the 'GMA X3100' chipset, the 'Legacy' link on version '10.7.5' shows that I support OpenGL up through 2.1.

If  the hardware doesn't support at least 3.0, you're going to have a bad time...

**Comment by tonymtbird** [comment] 2015-02-04 17:35
I think the title of this issue should be changed to indicate it as a feature request as opposed to a bug/issue. As an example.: Feature request:  Godotengine for Opengl 2.x.   
this is more accurately since Godot is built from the ground up to not support Opengl 2.x .

**Comment by robertwatkins** [comment] 2015-02-04 17:43
Yeah, as bug reports get updated and investigated, the original understanding of them can change. Rather than making it a feature request, it could just as easily be addressed by updated documentation indicating minimum version of MacOS (or possibly a version check on execution).

From a selfish standpoint, this bug helped me justify getting a new mac :)

**Comment by akien-mga** [comment] 2015-10-29 11:02
As pointed out by @tonymtbird this is likely a duplicate of #156, so closing it as such.

**Closed by akien-mga** 2015-10-29 11:02 UTC
Labels: archived, platform:osx
