### ISSUE TITLE
RigidBody2D Weight field strange behavior

### ISSUE THREAD

**Issue by AlexHolly** [godotengine/godot#16320] opened 2018-02-02 12:21 UTC
Godot Master

![peek 2018-02-02 13-13](https://user-images.githubusercontent.com/4741886/35732793-15527214-081b-11e8-9f37-2207e5371753.gif)

![peek 2018-02-02 13-12](https://user-images.githubusercontent.com/4741886/35732809-2b8d54d6-081b-11e8-82d9-21f31aa30fc8.gif)

Change the gravity to 0 in project settings leads to this behavior
![peek 2018-02-02 13-17](https://user-images.githubusercontent.com/4741886/35732878-7598a5d0-081b-11e8-8857-04bea5cd93ef.gif)

starting the game with this setting crashes the game.
`Parse Error: Unexpected identifier: 'inf'.`

**Comment by vnen** [comment] 2018-02-02 13:31
This is a duplicate of #16038

**Closed by vnen** 2018-02-02 13:31 UTC
Labels: bug, topic:editor
