### ISSUE TITLE
Godot doesn't detect my custom user inputs when using native?

### ISSUE THREAD

**Issue by nvanfleet** [godotengine/godot#77864] opened 2023-06-05 04:40 UTC
### Godot version

4.0.3 

### System information

Mac OS Arm64

### Issue description

Somehow when I am using a native build of my code it doesn't detect the user input types that I added into the project. These inputs used to work with my project when it was in GDScript but now show an error for some reason. I reported this to the SwiftGodot project but they have no idea. And the error seems to specifically be coming from the Godot app and aren't error strings from the SwiftGodot project. 

Attached is a test project that shows the error.

original report here
https://github.com/migueldeicaza/SwiftGodot/issues/77#issuecomment-1575760267

### Steps to reproduce

1. Build the project using the build.sh script (on Mac or do some extra config of the script for windows etc).
2. open the project
3. Launch the game which will launch the test scene

### Minimal reproduction project

[TestSwiftGodot.zip](https://github.com/godotengine/godot/files/11648555/TestSwiftGodot.zip)

**Comment by AThousandShips** [comment] 2023-06-05 16:12
* Duplicate of #74993?

**Closed** 2023-06-29 14:56 UTC
Labels: needs testing, topic:gdextension
