### ISSUE TITLE
Extremely annoying bug makes Beta 4 crash all the time

### ISSUE THREAD

**Issue by thomasdorone** [godotengine/godot#68610] opened 2022-11-13 13:23 UTC
### Godot version

Godot 4 beta 4

### System information

Mac os 13 2.3 GHz Dual-Core Intel Core i5 Intel Iris Plus Graphics 640 1536 MB

### Issue description

Probably the most annoying issue I have encountered in Godot 4. It simply prevents from working.
When saving a scene and then moving to another open scene, Godot crashes and then... for some reason, the mac dock is stuck. It just doesnt show when looking for it! Extremely annoying and strange.
As you can see the end of the video, I'm trying to access the dock and it doesn't show.

https://user-images.githubusercontent.com/104303630/201523852-a626da91-e20e-46d8-8075-1910ab4a5de5.mp4

### Steps to reproduce

1. Create a scene.
2. Create another scene with an instance of the first scene
3. Change something in the original scene and save it.
4. Go back to the scene with the instance

**Comment by Chaosus** [comment] 2022-11-13 13:36
Duplicate of https://github.com/godotengine/godot/issues/68417

**Closed by Chaosus** 2022-11-13 13:36 UTC
