### ISSUE TITLE
Android CLI build fails due to locate Android SDK

### ISSUE THREAD

**Issue by Cnidarias** [godotengine/godot#29385] opened 2019-06-01 16:44 UTC
**Godot version: 3.1.1 stable**

**OS/device including version: Linux**

**Issue description:**
I cannot figure out how to export a project to android using the CLI

When I run
`godot -v --export-debug "Android" build/project.apk` 

I get the following error

```
ERROR: instance: Class 'EditorSettings' can only be instantiated by editor.
   At: core/class_db.cpp:523.
ERROR: poll: /home/cnidarias/.config/godot/editor_settings-3.tres:3 - Parse Error: Can't create sub resource of type: EditorSettings
   At: scene/resources/resource_format_text.cpp:561.
ERROR: load: Condition ' err != OK ' is true. returned: RES()
   At: core/io/resource_loader.cpp:208.
ERROR: _load: Failed loading resource: /home/cnidarias/.config/godot/editor_settings-3.tres
   At: core/io/resource_loader.cpp:285.
WARNING: create: Could not open config file.
   At: editor/editor_settings.cpp:871.
```
It then continues adding and such and ends like this

```
      export: step 103: File: res://server/scripts/DatabaseHandler.gd.remap
        export: step 103: File: res://server/scripts/MainServer.gd.remap
        export: step 103: File: res://assets/icon_192x192.png
        export: step 103: File: res://assets/splashScreen.png
        export: step 103: File: res://project.binary
0 param: --use_depth_32
1 param: --use_immersive
export: end
WARNING: cleanup: ObjectDB Instances still exist!
   At: core/object.cpp:2095.
ERROR: cleanup: There are still MemoryPool allocs in use at exit!
   At: core/pool_vector.cpp:70.
```

with no output apk being produced.

I am assuming that the reason the APK is not being produced is because the jarsigning cannot happen as the configuration for the jarsigning bin as well as the default keystore are defined in the editor settings that it initially failed to parse.

The result of executing the command is that the original `editor_settings-3.tres` will be overwritten with a default one

Reproducing is pretty simple just run the command for any project. 

Just to point out, when I set the settings for exporting in the GUI I am able to generate the apk, so this is strictly the CLI not working correctly.

It would be _really_ nice if CLI was working though so that we could have automated builds for our game using Docker to compile the apk

Furthermore this might be related #16949 but I don't think it is the same because I am able to build it for linux without issues

**Comment by bemyak** [comment] 2019-06-17 22:58
I'm facing this bug too.  
I noticed that if you change the output file extension to `zip`, the file will be created successfully. My guess is that in this case `jarsigner` and `apk` are not executed.

Something seems to be wrong with config reading when launching godot in CLI-mode. If `export/android/adb` or `export/android/jarsigner` specified in `~/.config/godot/editor_settings-3.tres`, then I've got the same error as @Cnidarias .  
After that the config is getting reset to vanilla but the error is keep showing every time the exporter launches. The only way to get rid of it is to delete entire `~/.config/godot` directory.

I made a docker container with android-sdk and godot so it'll be a little easier to reproduce: `bemyak/godot-ci:3.1.1`, hope this will help.

**Comment by bemyak** [comment] 2019-06-19 07:18
I don't know if this is related to this issue or not, but HTML5 versions exported from GUI and CLI are different.
Here is the version exported from GUI:
![Screenshot_20190619_100338](https://user-images.githubusercontent.com/6333105/59743747-a77a0280-9279-11e9-97ea-afb02b714cc5.png)
And here is the same scene from CLI:
![Screenshot_20190619_100403](https://user-images.githubusercontent.com/6333105/59743774-b6f94b80-9279-11e9-9e53-e370ed06cffa.png)
As you can see, there are some texture corruptions on the forest behind main character and the clouds shader behaves differently: instead of repeating the entire texture only the last vertical pixel line is repeated and clouds are looking glitchy.
Here is my clouds shader code:
```glsl
shader_type canvas_item;

uniform float speed = 0.01;
uniform vec2 repeat = vec2(2.0, 1.0);

void fragment() {
	vec2 shift_vec = vec2(TIME, cos(TIME)) * speed;
	COLOR = texture(TEXTURE, UV * repeat + shift_vec);
}
```

`repeat` is getting set from GDScript as `Vector2(screen_width / texture_width, 1.0)`

**Comment by bemyak** [comment] 2019-10-24 16:53
The issue is still can be reproduced with Godot 3.2 alpha 3.  
Can we bring it into 3.2 milestone?

**Comment by bemyak** [comment] 2019-11-03 11:20
Well, actually I was wrong, apk file is created and can be successfully installed on device.

Couple of errors is still there
```
ERROR: bind: Method/Function Failed, returning: ERR_UNAVAILABLE
At: drivers/unix/net_socket_posix.cpp:386.
ERROR: bind: Method/Function Failed, returning: ERR_UNAVAILABLE
At: drivers/unix/net_socket_posix.cpp:386.
```
at the start of the export and
```
ERROR: ~List: Condition ' _first != __null ' is true.
At: ./core/self_list.h:112.
ERROR: cleanup: There are still MemoryPool allocs in use at exit!
At: core/pool_vector.cpp:69.
```
at the end. But they are no longer preventing apk from being generated.

**Comment by tommywalkie** [comment] 2020-04-21 13:58
Can confirm I got a similar error output as @bemyak on a Ubuntu based CI environment, using headless Godot Engine instance **v3.2.1** :
```
ERROR: _fs_changed: Project export failed with error code 12 for preset 'Android'.
export: end
   At: editor/editor_node.cpp:634.
ERROR: ~List: Condition ' _first != __null ' is true.
At: ./core/self_list.h:112.
ERROR: cleanup: There are still MemoryPool allocs in use at exit!
At: core/pool_vector.cpp:69.
```
However in my case, no APK is generated.

**Comment by bemyak** [comment] 2020-04-21 14:27
@tommywalkie , check that you have `jarsigner` and other stuff installed. Check this Dockerfile, it does everything that needed: https://github.com/bemyak/godot-ci/blob/master/Dockerfile

**Comment by tommywalkie** [comment] 2020-04-21 16:24
@bemyak I was actually trying to [implement it](https://github.com/tommywalkie/sample-godot-rust-app/blob/master/dockerfiles/godot-ci.Dockerfile) in a Github Actions way and figuring out how to interact with it with Docker CLI. 

I was previously doing the _same_ configuration steps from scratch on Github's Ubuntu machine because [it litterally has everything and anything](https://github.com/actions/virtual-environments/blob/master/images/linux/Ubuntu1804-README.md).

> check that you have `jarsigner` and other stuff installed.

I've noticed when I set **adb** path to `$ANDROID_HOME/platform-tools/adb` instead of `/usr/local/lib/android/sdk/platform-tools/adb`, or **jarsigner** path to `$JAVA_HOME/bin/jarsigner` instead of `/usr/lib/jvm/zulu-8-azure-amd64/bin/jarsigner`, in the context of Github's Ubuntu machine, the CLI was warning me I was using incorrect paths. Setting them to the right path solved these warnings. So I'm supposing the issue is somewhere else.

**Comment by tommywalkie** [comment] 2020-04-22 18:33
@bemyak Could build the Docker image, using this [Dockerfile](https://github.com/tommywalkie/sample-godot-rust-app/blob/master/dockerfiles/godot-ci.Dockerfile), and could reproduce the issue [here](https://github.com/tommywalkie/sample-godot-rust-app/runs/609566748?check_suite_focus=true#step:12:103). I also added two steps where I just do a `ls` command in container's `WORKDIR` before and after the export attempt, maybe I could learn something from it.

Runned this command in the Docker container :
```bash
# 'godot-ci' is the container name
docker exec godot-ci godot --export "Android" ./sample_godot_rust_app.apk
```
I can confirm no APK is being generated and some `res:` directory appeared after the build.
```diff
🢒 Run docker exec godot-ci ls
Cargo.toml
Cross.toml
LICENSE
README.md
assets
build
default_env.tres
dockerfiles
export_presets.cfg
+ output.log
project.godot
+ res:
scenes
src
target
templates
```

**Comment by Calinou** [comment] 2020-04-24 12:35
> I've noticed when I set adb path to $ANDROID_HOME/platform-tools/adb instead of /usr/local/lib/android/sdk/platform-tools/adb, or jarsigner path to $JAVA_HOME/bin/jarsigner instead of /usr/lib/jvm/zulu-8-azure-amd64/bin/jarsigner, the CLI was warning me I was using incorrect paths. Setting them with the right paths solved these warnings. So I was supposing the issue is somewhere else but I may be wrong.

This is because paths are directly sent to `OS::execute()`, rather than using a shell to expand environment variables and find the binary in `PATH`. We could change this but I'm not sure how difficult it would be.

**Comment by Calinou** [comment] 2020-04-24 12:40
@tommywalkie Also, I may have found out what went wrong in your particular CI script. When you export a project to Android in release mode, the debug keystore in the Editor Settings is ignored. Instead, you *must* define the path to the release keystore and the credentials in `export_presets.cfg`. (Remember not to commit this information to version control, so use `sed` and secrets to set it in the CI step.)

**Comment by tommywalkie** [comment] 2020-04-24 12:49
@Calinou Oh it makes sense ! Thanks for your response, I'll try that !
Also, as a side question : Is there a difference between the following fields ?
- `debug_keystore_user` / `debug_keystore_pass`
- `debug_user` / `debug_pass`

**Comment by Calinou** [comment] 2020-04-24 13:06
@tommywalkie I believe `debug_user` and `debug_pass` is for remote debugging, no?

**Comment by Filius-Patris** [comment] 2020-04-24 14:39
@tommywalkie Digging through [source][1], I found that `debug_keystore_user` is what the [manpage][2] of `jarsigner` calls `alias`. AndroidStudio uses the same term, if you're familiar with it. You can imagine it as the name of the specific key in the keystore (there can be multiple).
`debug_user` and `debug_pass` are the same respectively, just that they overwrite the before mentioned, if defined. They seem to be defined in export_config.cfg though.

[1]: https://github.com/godotengine/godot/blob/85ed2edc0685b7868813ee53d14964af9158eaf2/platform/android/export/export.cpp#L2182
[2]: https://manpages.debian.org/unstable/openjdk-8-jdk-headless/jarsigner.1.en.html

**Comment by tommywalkie** [comment] 2020-04-24 17:23
I was trying the two different approaches in a single run, the [first job](https://github.com/tommywalkie/sample-godot-rust-app/runs/615994583?check_suite_focus=true) using `--export-debug` worked while the [second job](https://github.com/tommywalkie/sample-godot-rust-app/runs/615994556?check_suite_focus=true) ([Source of the CI job](https://github.com/tommywalkie/sample-godot-rust-app/blob/better-build-for-android/.github/workflows/ci.yml#L294-L377)), which is using `--export` and a release keystore and Github Secrets, didn't work.

> `debug_user` and `debug_pass` are the same respectively

@Filius-Patris Mmmmm this maybe explains why I got an `jarsigner error: java.lang.RuntimeException: keystore load: Keystore was tampered with, or password was incorrect` error while I did set up export presets like this :

```yaml
- name: Set new export presets for release, using secrets
  env:
    ANDROID_RELEASE_KEYSTORE: ${{ secrets.ANDROID_RELEASE_KEYSTORE }}
    ANDROID_RELEASE_KEYSTORE_USER: ${{ secrets.ANDROID_RELEASE_KEYSTORE_USER }}
    ANDROID_RELEASE_KEYSTORE_PASS: ${{ secrets.ANDROID_RELEASE_KEYSTORE_PASS }}
  run: |
    sed -i '/\[preset.2.options\]/a keystore\/release = "'$ANDROID_RELEASE_KEYSTORE'"' ./export_presets.cfg
    sed -i '/\[preset.2.options\]/a keystore\/release_user = "'$ANDROID_RELEASE_KEYSTORE_USER'"' ./export_presets.cfg
    sed -i '/\[preset.2.options\]/a keystore\/release_pass = "'$ANDROID_RELEASE_KEYSTORE_PASS'"' ./export_presets.cfg
```

**Comment by tommywalkie** [comment] 2020-04-25 12:33
As @Filius-Patris explained me in https://github.com/tommywalkie/sample-godot-rust-app/issues/14, I was wrong on how to handle `jarsigner` and release keystore.
So for reference, for anyone who wants to know how to resolve it, following @Filius-Patris's advices, here is what I did :
```bash
# From your own terminal, create a release keystore and choose an alias.
# This assumes you have Android SDK (which might come with keytool CLI) installed.
# You will be asked to answer questions and provide a passphrase and confirm it.
keytool -genkeypair -v -keystore ./release.keystore -alias some-alias -keyalg RSA -keysize 2048 -validity 10000

# Then, create a GPG key, using GPG CLI, which is provided by GnuPG
# This will ask you to provide twice the passphrase you used before.
# It will create a .gpg file.
gpg -c .\release.keystore
```
Finally, in the CI workflow, decrypt the key that will be used for the keystore and don't forget to set correctly the keystore path, keystore password and the alias in export presets, in `keystore/release`, `keystore/release_user` and `keystore/release_pass` fields.
```bash
gpg --quiet --batch --yes --passphrase="$DECRYPTION_KEY" --output release.keystore release.keystore.gpg
```

**Comment by FeralBytes** [comment] 2020-06-14 21:59
Just FYI to any future users using Godot 3.2.2 my issue was that export_presets.cfg had a different value than the other files.
So to the Godot developers I think we should have 1 and preferably only one spot in which to set this information, as opposed to currently have 3 potentially conflicting places.

**Comment by Calinou** [comment] 2020-06-15 07:31
@FeralBytes #35930 implements environment variable overrides for Android keystore information.

**Comment by FeralBytes** [comment] 2020-06-20 22:14
@Calinou Thank you!

**Comment by dbrova15** [comment] 2020-07-02 14:01
**Godot version:**
3.2.2
**OS/device including version:**
gitlab/docker

**Issue description:**
I want to configure a custom build for android on gitlab. My docker image is at https://github.com/dbrova15/godot-ci-android-bakz
An error occurs during assembly

![image](https://user-images.githubusercontent.com/20703983/86366952-19a26700-bc84-11ea-9dcf-d0ab962aff6a.png)

A project with no problem is exported to my computer. I move the android folder to the docker unchanged.

Tell me what am I doing wrong?

**Steps to reproduce:**
In any project, set the custom build ON.

![image](https://user-images.githubusercontent.com/20703983/86367698-f6c48280-bc84-11ea-8744-2387bbf8b6b8.png)


Follow instructions from repository:
https://github.com/dbrova15/godot-ci-android-bakz

**Comment by dbrova15** [comment] 2020-07-02 14:08
> Just FYI to any future users using Godot 3.2.2 my issue was that export_presets.cfg had a different value than the other files.
> So to the Godot developers I think we should have 1 and preferably only one spot in which to set this information, as opposed to currently have 3 potentially conflicting places.
> Although having an environmental variable override the settings is still fine by me for my purposes on GitLab CI too.

Was there a problem somewhere in the file? What value did you need to change?

**Comment by bemyak** [comment] 2020-07-02 14:09
@dbrova15 , instead of just appending lines to `~/.config/godot/editor_settings-3.tres` try deleting them first, they can already be defined somewhere earlier, which makes your config invalid.

Check my [Docker file](https://github.com/bemyak/godot-ci/blob/master/Dockerfile) for an example.

**Comment by dbrova15** [comment] 2020-07-03 08:14
> 
> 
> @dbrova15 , instead of just appending lines to `~/.config/godot/editor_settings-3.tres` try deleting them first, they can already be defined somewhere earlier, which makes your config invalid.
> 
> Check my [Docker file](https://github.com/bemyak/godot-ci/blob/master/Dockerfile) for an example.

Did as you advised. Nothing changed.

An error occurs only if you set Usa custom build True. If this parameter is set to False, then everything works fine.

**Comment by FeralBytes** [comment] 2020-07-16 23:52
You can see the blame here, where I made fixes 1 month ago to get CI working. https://gitlab.com/FeralBytes/FreecoiL/-/blame/master/.gitlab/ci_scripts/editor_settings-3.tres
NOTE: my CI is failing right now to build but that is due to the docker image that I am using. It was working fine for 3.2.2-beta4, but the image broke, not my fault just the docker image is bad. I will either revert or make my own soon.

**Comment by akien-mga** [comment] 2021-04-28 13:01
I renamed the issue since as of 3.3, we no longer use `jarsigner` but `apksigner` from the Android SDK. The editor settings now have a single setting for this which is the path to the Android SDK (which will be used to locate both `apksigner` in `build-tools` and `adb` in `platform-tools`).

But it's likely that the CI-specific issues discussed here are still reproducible with this changed setup.

**Comment by Calinou** [comment] 2023-06-19 07:29
@Cnidarias Can you (or anyone else) still reproduce this bug in [Godot 3.5.2](https://godotengine.org/article/maintenance-release-godot-3-5-2) or any later release?

**Comment by FeralBytes** [comment] 2023-06-23 18:20
@Calinou unable to confirm at this time. I think closing is appropriate. If I find the issue returns I will re-open at that point in time.

**Closed** 2023-06-23 18:29 UTC
Labels: bug, platform:android, topic:buildsystem, topic:porting, confirmed
