### ISSUE TITLE
A bucket of issues with OptionButton (Dropdown)

### ISSUE THREAD

**Issue by ivanskodje** [godotengine/godot#6558] opened 2016-09-20 05:32 UTC
(Godot build from 20.09.16)
# Deleting Items

If you select an item and delete the same item, OptionButton does not change the selected text visible.
If you use the clear() function, selected id turns to -1 and there won't be any text visible; however, if you delete the last item without using clear(), selected item is still 0.

A possible solution, If you are deleting last item is to set selected id to -1

Another possibility would be to add an extra optional bool in remove_item() where false would be to return to the first item (if any) or -1 if it was the last item. True could be to move to the next item in selection (i.e. you delete ID 3, you select the new ID at 3).

Currently, when there are more items; simply deleting selected item will just 

---
# Selecting previously deleted ID

Currently when you try to select another item which have the same ID like the deleted item, it wont allow you to select it. 
1. Delete item#1 with ID 3
2. Item#2 takes the place if ID3 after item#1 is gone
3. Attempting to select item#2 does not work.

---
# Adding an Item

After deleting the last item (having selected id at 0, problem with deletion), adding a new item does not automatically select the first item.

If you fix the problem with deletion, the selected_id should by default be -1 (when there are no previous item added) - which should automatically set selected to 0 when the first item is added.
(Of course you should not automatically select the LAST item if there are previous items available)

---
# Cannot set selected to none

You are unable to set selected to -1 (none). You can use .select(id) to choose any existing ID, but we should definitely implement the option to set to -1 (none), which also is the same selected id you get when you use .clear().

---
# OptionButton is a misleading name

Godot would benefit from renaming OptionButton to DropdownButton or something similar that gives you the perfect description of what it is. :)

**Comment by Tybobobo** [comment] 2016-09-20 05:34
Here is an OptionButton demo I made that should help you visualize the issues.
[optionbutton_demo.zip](https://github.com/godotengine/godot/files/481682/optionbutton_demo.zip)

**Comment by neikeq** [comment] 2016-09-20 07:16
Referencing #3188 since this issue is related to the PopupMenu API which is likely to be refactored for 3.0. That issue does not mention your problems though.

**Comment by AlexHolly** [comment] 2018-03-14 16:40
Is there a reason why `OptionButton.get_selected_id()` returns always -1
I have to use `OptionButton.selected`

**Comment by tom-jk** [comment] 2020-07-24 22:16
Testing with a Godot 3-compatible remake of above demo: [6558_Demo2.zip](https://github.com/godotengine/godot/files/4974433/6558_Demo2.zip)

Testing on linux mint 18.3 with Godot 3.2.3.beta1

Deleting selected item does not update selection/text: still true
Deleting last item does not set selection=-1: still true
Selecting previously deleted ID: can't reproduce (maybe I misunderstand it)
New item unselected after deleting all (and selection=0): still true
Can't set selected to none (-1): still true
Get_selected_id() returns -1: not true (but returns 0 when selected=-1, though docs suggest this is intentional/known)

**Comment by akien-mga** [comment] 2022-01-28 23:01
Several of these listed issues have been fixed in #57330. It would be good to review the list and see what's left - possibly moving them to dedicated proposals or bug reports.

**Comment by KoBeWi** [comment] 2022-03-12 00:54
I checked all points and they seem to be resolved.
Here's the updated project from the 1st comment:
[optionbuttontest.zip](https://github.com/godotengine/godot/files/8236685/optionbuttontest.zip)

**Closed by KoBeWi** 2022-03-12 00:54 UTC
Labels: enhancement, topic:gui
