### ISSUE TITLE
Increase RAM Usage on Scaling Animation Nodes

### ISSUE THREAD

**Issue by nrfaikar** [godotengine/godot#24757] opened 2019-01-04 08:28 UTC
**Godot version:**
Version 3.1 Alpha 5

**OS/device including version:**
Fedora 29 Silverblue 64-bit

**Issue description:**
The image below shows the issue:
![screenshot from 2019-01-04 15-20-59](https://user-images.githubusercontent.com/26834955/50679262-5d87c200-1035-11e9-8a08-b8beb6ee674c.png)

**Steps to reproduce:**
Scaling animation nodes and hit OK

**Minimal reproduction project:**
I don't know

**Comment by bojidar-bg** [comment] 2019-01-04 12:10
Can confirm a slight memory leak when scaling, probably it is worse when scaling animations with many keyframes. (Couldn't test with one, since I don't have huge animations at hand)

**Comment by reduz** [comment] 2019-02-13 19:58
I don't think this is a bug, It's most likely the undo/redo memory.

**Comment by reduz** [comment] 2019-02-14 14:39
Closing because this is not a bug. The editor uses more memory each time because these values are kept in memory for undo/redo. This is probably not a very good way to check for leaks also, Godot has an internal leak checker when you run verbose (-v) and also Llvm or Vlgrind.

**Closed by reduz** 2019-02-14 14:39 UTC
Labels: bug, topic:editor

**Comment by volzhs** [comment] 2019-02-14 14:46
is there a way not to use huge memory consumption while scaling animation has a lot of keyframes?

**Comment by arkology** [comment] 2019-02-14 14:55
Even if this is not a bug, using 4.5 Gb of RAM is not normal

**Comment by volzhs** [comment] 2019-02-14 17:01
@arkology I agreed.
you can convince it by adding a sample project to reproduce it easily.
