### ISSUE TITLE
GDextension can't access bin folder in projects due to Windows file locking limitations

### ISSUE THREAD

**Issue by ash-hashtag** [godotengine/godot#65971] opened 2022-09-17 08:35 UTC
### Godot version

4.0 beta 1

### System information

Windows 11

### Issue description

Can't access bin folder when the project is open, can't write to it. so scons build fails, can't delete it and paste it either, says the folder is open somewhere. So the only way to compile the c++ code is closing the godot completely, and open again to test, you can compile it tho but to include/paste the bin in project you have to close godot.

### Steps to reproduce

use gdextension, try to build when the project is open in godot

### Minimal reproduction project

https://github.com/nathanfranke/gdextension/tree/main/project

**Comment by WildRackoon** [comment] 2022-12-14 16:35
Indeed, GDNative had the `reloadable` property to prevent that, I am unsure what is planned to address this issue in GDExtension.
See [GDNative Documentation](https://docs.godotengine.org/en/stable/classes/class_gdnativelibrary.html?highlight=reloadable%20)

**Comment by akien-mga** [comment] 2022-12-14 18:10
I'll close this as duplicate of #66231 which covers this and some more considerations.

**Closed by akien-mga** 2022-12-14 18:10 UTC
Labels: bug, platform:windows, topic:editor, topic:gdextension
