### ISSUE TITLE
large arrays show up as <null> in Godot debugger

### ISSUE THREAD

**Issue by Spycemyster** [godotengine/godot#76124] opened 2023-04-16 10:41 UTC
### Godot version

4.0.2.stable

### System information

Windows 11, GLES2

### Issue description

When there is a sufficiently large array, the Godot debugger will display it as  `<null>`. It should probably be displayed as "too large to display" or anything other than `null` as that can be confusing.
![image](https://user-images.githubusercontent.com/6189001/232299179-86f18520-6c8e-48c9-8612-a57bc27c7c1a.png)
I first discovered this when downloading images through an HTTPRequest. I was trying to find out why my image was displaying incorrectly, but the debugger kept showing `<null>` and made me incorrectly think that there was an issue with the request.

### Steps to reproduce

Create an array and fill it with a large amount of elements. In the MVP I just kept doubling an array. After 17 times (131072 elements), that's when it started getting displayed as `<null>`. 

### Minimal reproduction project

[LargeArrayMVP.zip](https://github.com/godotengine/godot/files/11241962/LargeArrayMVP.zip)

**Comment by Spycemyster** [comment] 2023-04-16 10:49
Also, if this is something that should be changed, I would like to take this issue on as my first issue.

**Comment by Calinou** [comment] 2023-04-16 15:15
- Duplicate of https://github.com/godotengine/godot/issues/70493.

> Also, if this is something that should be changed, I would like to take this issue on as my first issue.

There's a pull request working around the issue: https://github.com/godotengine/godot/pull/74148

As per the PR's description, it's difficult to create a definitive fix that does not introduce network stalling due to data being too large.

**Closed by Calinou** 2023-04-16 15:16 UTC
