### ISSUE TITLE
Buttons in Export window are too big and pixelated

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#28339] opened 2019-04-23 15:59 UTC
**Godot version:**
3.2.dev.custom_build. 49b6423

**OS/device including version:**
Ubuntu 18.04

**Issue description:**
In export project window some of icons are too big
Project -> |Choose or create preset| -> Export Project
![Zrzut ekranu z 2019-04-23 17-54-08](https://user-images.githubusercontent.com/41945903/56596640-34de0500-65f1-11e9-9c44-974f38893645.png)

**Minimal reproduction project:**
This happens only in this project

https://github.com/wesnoth/haldric

**Comment by Calinou** [comment] 2019-04-23 16:49
The [`theme/use_hidpi` setting](https://github.com/wesnoth/haldric/blob/3d6b75b30ed01b05e2d8666aa83bf791813d3f6b/project.godot#L312-L314) in that project's `project.godot` file may be responsible for the issue.

**Comment by Vultraz** [comment] 2019-04-23 22:54
@Calinou I couldn't figure out what the difference between `theme/use_hidpi` and `display/window/dpi/allow_hidpi` was so I enabled both. I don't actually seem to see any difference whether the former is on or off. 🤔I don't see any pixelated icons on my 4K monitor

Could this also be related to how custom themes affect the editor's built-in theme?

**Comment by Calinou** [comment] 2019-06-08 09:44
As of https://github.com/godotengine/godot/commit/693582f00837bb4ce4fb3ce91d2366ee359eecf4, I can notice a similar issue in the Project Manager file dialogs (icons are too small):

![image](https://user-images.githubusercontent.com/180032/59145340-98c25e80-89e2-11e9-910e-39af643ad45e.png)

However, this doesn't occur in the editor's file dialogs.

**Comment by akien-mga** [comment] 2019-12-20 09:22
I can't reproduce the issue in 3.2 beta 4, and #34479 might further prevent it from happening again, so closing. Please comment if you can still reproduce it.

**Closed by akien-mga** 2019-12-20 09:22 UTC
Labels: bug, topic:editor
