### ISSUE TITLE
Standard material is behaving incorrectly 

### ISSUE THREAD

**Issue by KuuttiProductions** [godotengine/godot#60685] opened 2022-05-01 10:05 UTC
### Godot version

4.0.alpha7

### System information

MacOS 12.3.1, Vulkan Clustered, Apple M1 Pro

### Issue description

https://user-images.githubusercontent.com/74451594/166141206-aadafef9-30bc-493a-9fc9-64e2e6a52d01.mov 

Materials are black/transparent by default. When refraction or no depth test are checked color works correctly but there are no shadows and it should work without them anyway. Also It would seem that if I'm not looking at any other mesh it works as intended. 

### Steps to reproduce

Add a MeshInstance 3D and set the mesh to cube. Add a standard material.
At this point it should have turned black even though color is set to white in albedo. 

### Minimal reproduction project

[BrilliantBar.zip](https://github.com/godotengine/godot/files/8598662/BrilliantBar.zip)

**Comment by Calinou** [comment] 2022-05-01 17:21
Duplicate of https://github.com/godotengine/godot/issues/51898.

**Closed by Calinou** 2022-05-01 17:21 UTC
Labels: bug, topic:rendering, regression, topic:3d
