### ISSUE TITLE
Crash on Android draw with a MeshInstance (V3.0)

### ISSUE THREAD

**Issue by ret80** [godotengine/godot#16831] opened 2018-02-19 19:48 UTC
**Godot version:**

3.0

**OS/device including version:**

OnePlus 3  Android 8.0 

**Issue description:**
If any mesh is displayed on the screen, the application fails. 
If you hide it then all at once starts to work.
PS
The project has a log file from your phone "logcat.txt"

**Steps to reproduce:**

**Minimal reproduction project:**
https://yadi.sk/d/rRuIW0x73SafYg

**Comment by Zireael07** [comment] 2018-02-19 20:02
Lemme guess, an Adreno device?

**Comment by ret80** [comment] 2018-02-19 21:00
Qualcomm Snapdragon 820 MSM8996 
Adreno 530

**Comment by alex9099** [comment] 2018-02-19 22:27
Similar to #12816 ?

**Comment by ret80** [comment] 2018-02-20 06:12
Yeah, looks like the same problem.

**Comment by akien-mga** [comment] 2018-02-20 08:42
Closing as duplicate of #12816.

**Closed by akien-mga** 2018-02-20 08:42 UTC
