### ISSUE TITLE
Inverse of Vector2 Unhandled

### ISSUE THREAD

**Issue by dnadan2** [godotengine/godot#15179] opened 2017-12-29 22:33 UTC
**Godot version:**

2.1.4

**OS/device including version:**

Windows 10

**Issue description:**

Attempted to get the inverse of a Vector2 (scale to be precise) in the form of:
1/scale 
and it threw an error that it cannot handle INT divided by Vector2

Vector2(1,1)/scale works perfectly.

**Steps to reproduce:**
1 / Vector2(2,2)

**Minimal reproduction project:**

- [Y ] I searched the existing [GitHub issues](https://github.com/godotengine/godot/issues?utf8=%E2%9C%93&q=is%3Aissue+) for potential duplicates.

**Comment by LinuxUserGD** [comment] 2017-12-29 22:52
You could try to convert INT to Double

**Comment by dnadan2** [comment] 2017-12-29 23:03
Attempted, recieving the following error code: "Invalid operands 'float' and 'Vector2' in operator '/'."
Again it is unable to handle it (It doesn't seem Double is implemented let me know if I'm wrong).
I've used a 1 Vector instead which works fine for this problem, this thread is more to highlight the issue than ask for solutions.

**Comment by vnen** [comment] 2017-12-29 23:08
> 1 / Vector2(2,2)

This does not make sense to me, you cannot divide a scalar by a vector.

**Comment by Zylann** [comment] 2017-12-30 00:41
You can in GLSL, you can also do `Vector2(1,1) / Vector2(2,2)`, but GDScript isn't going far in linear algebra.
Workaround is to do `var inv = Vector2(1.0 / s.x, 1.0 / s.y)`.

**Comment by vnen** [comment] 2017-12-30 01:14
Yeah, GDScript doesn't make shortcuts for things that aren't defined in math.

I'll close this since it's the intended behavior.

**Closed by vnen** 2017-12-30 01:14 UTC
