### ISSUE TITLE
Showing AcceptDialog with Exclusive flag in edited scene steals input events from editor, effectively freezing it (DisplayServer regression)

### ISSUE THREAD

**Issue by MagdielM** [godotengine/godot#55740] opened 2021-12-08 19:37 UTC
### Godot version

v4.0.dev.calinou [97034939f]

### System information

Windows 10

### Issue description

In a scene with an `AcceptDialog` (and presumably any of it's derived types), making it visible with the Exclusive flag enabled stops the editor from taking input events. This is, of course, what the flag is supposed to do, but the dialog can't be dismissed after this happens either.

(Haven't bothered to check if the weird window corruption you see in the video has been reported, by the way.)

https://user-images.githubusercontent.com/56076033/145272219-79b8821a-a3aa-4e5a-a48f-73991924e8e0.mp4

### Steps to reproduce

1. Make a scene with an `AcceptDialog` node.
2. Ensure its Exclusive flag is on.
3. Toggle its Visible flag.
4. Notice how the editor isn't frozen (UI still reacts to window size changes), but inputs do nothing.

The reproduction project already includes a scene with an `AcceptDialog` set up, you can open the scene and make the dialog visible to reach the same result.

### Minimal reproduction project

[AcceptDialog Freeze Repro.zip](https://github.com/godotengine/godot/files/7678448/AcceptDialog.Freeze.Repro.zip)

**Comment by MagdielM** [comment] 2021-12-08 19:50
Turns out this could be a duplicate of #51362. Not sure if worth keeping open.

**Comment by Calinou** [comment] 2021-12-08 21:30
Duplicate of https://github.com/godotengine/godot/issues/51362 (same cause).

**Closed by Calinou** 2021-12-08 21:30 UTC
Labels: bug, regression, topic:gui
