### ISSUE TITLE
HTML5 web export on mobile - keyboard native won't appear for line edit node

### ISSUE THREAD

**Issue by MelimeliDev** [godotengine/godot#39124] opened 2020-05-28 14:36 UTC
Is there a way to fix this? The text input / edit won't work on mobile because mobile native keyboard won't popup :(

**Comment by Zireael07** [comment] 2020-05-28 14:43
Duplicate of https://github.com/godotengine/godot/issues/32680

**Closed** 2020-05-28 14:50 UTC
