### ISSUE TITLE
GUI containers cause editor to update continuously

### ISSUE THREAD

**Issue by fractilegames** [godotengine/godot#31371] opened 2019-08-14 08:47 UTC
**Godot version:** 3.1.1

**OS/device including version:** Xubuntu 19.04 64 bit

**Issue description:**
When a simple scene with GUI containers (at least VBoxContainer, HBoxContainer or GridContainer) with one or more child nodes is open and a child node is selected, the editor keeps updating continuously (the spinner rotates and CPU usage is high).

**Steps to reproduce:**

- Create a new GUI scene
- Add a VBoxContainer node
- Add a Label node as child of the container
- Select Label node

**Comment by Xrayez** [comment] 2019-08-14 09:21
I wonder if this is the culprit of performance drop when I attempt to resize panels/docks, doesn't seem smooth at all indeed (if talking about the Godot editor itself, not edited scene).

**Comment by KoBeWi** [comment] 2019-08-14 11:22
Duplicate of #29313, already fixed in master (you can test it with nightly build).

**Closed by KoBeWi** 2019-08-14 11:22 UTC
