### ISSUE TITLE
CSGMesh only shows Capsule and Spheres

### ISSUE THREAD

**Issue by TheNeoGameFactory** [godotengine/godot#54702] opened 2021-11-07 09:18 UTC
### Godot version

3.4

### System information

Windows 7, GLES3, 2x Radeon HD8950, 64gb RAM

### Issue description

If I want to add a CubeMesh to a CSGMesh I got the following error.

`` drivers/gles3/rasterizer_storage_gles3.cpp:3927 - Index p_surface = 0 is out of bounds (mesh->surfaces.size() = 0).
 servers/visual_server.cpp:1787 - Condition "vertex_data.size() == 0" is true. Returned: Array()
 modules/csg/csg_shape.cpp:738 - Condition "arrays.size() == 0" is true. Returned: _post_initialize(new ("") CSGBrush) ``

(Also on Plane and many others, but Sphere and Capsule works)

Maybe the same as #46610

A colleque tells me that a CSGBox works perfect.

### Steps to reproduce

1. have a 3D Scene open with a CSGMesh as Child or Root.
2. add a New CubeMesh to the CSGMesh
3. look at the Console ;) you get an error :P

**Comment by akien-mga** [comment] 2021-11-07 09:39
Duplicate of #46610

**Closed by akien-mga** 2021-11-07 09:39 UTC
Labels: bug, topic:core, topic:3d
