### ISSUE TITLE
Usability issues in Godot 4.0 compared to Godot 3.5.1

### ISSUE THREAD

**Issue by seppoday** [godotengine/godot#69757] opened 2022-12-08 10:48 UTC
### Godot version

Godot 4.0 Beta 6

### System information

Windows 10

### Issue description

Hello, that issue will probably be duplicate, but I couldn't find anything like that. I've found 2 problems in G4 that are rather annoying comapred to G3.

1. When you try to add node by using CTRL + A it is very unresponsive in Godot 4. In Godot 3 it is instant. In Godot 4 you need to tap CTRL + A like 3 or 4 times.
2. You can't tab between values in inspector. In Godot 3 when I had a lot of values to fill in the inspector I used tab to jump between inputs. In Godot 4 it is sometimes possible and sometimes not. I've found that if you jump between scenes it starts to lock and you can't tab between inputs. But when you start to click on inputs with mouse and tab at same time it unlocks. Weird.

### Steps to reproduce

Try in editor.

### Minimal reproduction project

.

**Comment by KoBeWi** [comment] 2022-12-08 12:24
> When you try to add node by using CTRL + A it is very unresponsive in Godot 4. In Godot 3 it is instant. In Godot 4 you need to tap CTRL + A like 3 or 4 times.

Can't reproduce, the dialog opens after single press. It *might* take some time to open if you have many classes, but mashing the button is not required.

> You can't tab between values in inspector. 

Duplicate of #37723
The main problem is that editing a value will sometimes lock tabbing. You can press Enter to accept the value and Tab works again.

**Comment by bend-n** [comment] 2022-12-11 01:51
The <key>ctrl</key>+<key>a</key> thing is a legitimate problem if you press it too fast. It only works if you <key>ctrl</key>.. 1 second .. <key>a</key>.

**Comment by KoBeWi** [comment] 2022-12-11 01:54
Then it's duplicate of #45033

**Closed by KoBeWi** 2022-12-11 01:54 UTC
Labels: bug, topic:editor, regression
