### ISSUE TITLE
Editor lag with big canvas polygon buffer

### ISSUE THREAD

**Issue by kristijandraca** [godotengine/godot#47833] opened 2021-04-12 16:55 UTC
**Godot version:**
v3.3.rc8

**OS/device including version:**
Macbook Pro 2019 ([details](https://i.ibb.co/88NddJY/Screenshot-2021-04-12-at-18-47-06.png))

**Issue description:**
The whole Godot editor is extremely laggy and unresponsive on version v3.3 RC but works fine on v3.2.3 (stable)

**Steps to reproduce:**
Create new project
Change rendering/limits/buffers/canvas_polygon_buffer_size_kb 
and rendering/limits/buffers/canvas_polygon_index_buffer_size_kb
to something big like 32*1024

**Minimal reproduction project:**
[GodotIssue.zip](https://github.com/godotengine/godot/files/6298428/GodotIssue.zip)

**Comment by clayjohn** [comment] 2021-04-12 17:31
By 3.2 (stable) do you mean 3.2.3?

**Comment by kristijandraca** [comment] 2021-04-12 17:51
Yes, I did mean 3.2.3 :)

**Comment by ttencate** [comment] 2021-04-12 18:30
FWIW, I'm unable to reproduce this with rc8 on Arch Linux. Tried both with GLES2 and GLES3. @kristijandraca which of these are you using and does it make a difference?

**Comment by kristijandraca** [comment] 2021-04-12 18:37
Originally I noticed on GLES3 but I tried now with GLES2 and its the same thing. 
Here is quick demo of Main scene from reproduction project running 3.3 RC8

https://user-images.githubusercontent.com/53337160/114444130-cc6a0300-9bce-11eb-9645-5c1e17bfc695.mov

And here is same project running on 3.2.3

https://user-images.githubusercontent.com/53337160/114444194-ddb30f80-9bce-11eb-9077-8ecee2cdd23c.mov

**Comment by lawnjelly** [comment] 2021-04-12 18:53
Unfortunately we've had all kinds of problems with performance on various Macs in different builds for a long time, and made many attempts to pin them down in conjunction with users, but realistically it is complete guesswork as none of the render guys seem to use / have access to Macs, and there are too many variables. We would welcome interest to investigate this from any contributor that does use Macs.

It could be due to the Mac drivers not liking some way we use OpenGL, or frame rate limiting in the editor, or any number of reasons.

You could try switching off batching to see if you get any better performance. Batching doesn't use the `canvas_polygon` buffers as far as I can remember.

One long term option may be to use ANGLE to translate OpenGL into Metal. We haven't used it so far because apparently it is a pain to compile. Also in Godot 4.0 there may be MoltenVK to convert Vulkan to Metal. Apple support for Metal is much better than OpenGL.

**Comment by kristijandraca** [comment] 2021-04-12 19:02
I tried switching off
rendering/batching/options/use_batching_in_editor
rendering/batching/options/use_batching
restart Godot and still problem persist.

**Comment by lawnjelly** [comment] 2021-04-12 19:11
You may have some joy trying out 3.2.4 beta 2:
https://github.com/godotengine/godot/issues/43038#issuecomment-722336615

We had these extra settings for buffer orphaning available for some of the betas, but unfortunately I don't think many people tried them.

**Comment by kristijandraca** [comment] 2021-04-12 19:27
Ok, so switching off 
rendering->options->api_usage_legacy->orphan_buffers
solves the issue for me

**Comment by lawnjelly** [comment] 2021-04-13 07:22
> Ok, so switching off
> rendering->options->api_usage_legacy->orphan_buffers
> solves the issue for me
> on 3.2.4 beta 2

Yes as I suspected the orphaning / flags are having effects on machines with dodgy drivers. See here for another example:
https://github.com/godotengine/godot/issues/47824#issuecomment-818184804

This is somewhat of a difficult problem, in that OpenGL isn't absolutely clear about the best way to dynamically use buffers. As such it seems that different vendors / driver versions have their own interpretation, and what works best on some hardware may not be what works best on others. I'm not sure whether to blame OpenGL or the driver guys, but it is a difficult problem to solve on our side.

Ideally we'd like to have a certain 'correct' usage and apply it to all platforms. We can certainly have a distinction between mobile and desktop, with mobile seeming to work better with orphaning. My desktop doesn't make a lot of difference if orphaning is used or not, and that seems the case with a lot of desktop. However macs seem to drop a lot of performance when their preferred method is not used, and this seems to vary on different Macs, possibly even between OS versions.

The problem is not so much using the editor, as it is feasible (but not ideal) to have a developer change these options, but the end users, game players, who will not want to change these options and will expect it to work.

So maybe we will have to work towards a hardware database as @Calinou has suggested in the past.

To start with it maybe an idea for us to reintroduce the orphan / flag options in the project settings in some way. And also it may be wise to add command line options to choose these for the engine, so that worst case an end user can choose them.

At this stage (with the RCs) we have to tread with extreme caution changing the defaults for different platforms. Although 1 person may shout about low performance, if we change the default on that platform, we may get 1 happy person, and 1000 unhappy people because the old default worked better on theirs.

**Comment by kristijandraca** [comment] 2021-04-15 09:49
@lawnjelly I can confirm **way better** performance with RC9

**Comment by akien-mga** [comment] 2021-05-09 23:20
I guess we can close this as fixed by #47864?

**Comment by lawnjelly** [comment] 2021-05-10 07:04
> I guess we can close this as fixed by #47864?

Maybe but I suspect this may be part of an ongoing saga. Although the Godot IDE user can set these to their machine's preference, if the end users machines (i.e. people using exported projects) also have different preferences we still potentially have a problem. We'll have to see if we get bug reports.

There are still 2 immediate things which may be worth adding:
* Command line / runtime options for the buffer orphaning. This is a bit last ditch, but it could save a few end users who use susceptible desktop,  or aid in remotely diagnosing problems, and is fairly simple to add.
* A hardware database to switch options for known problematic machines / OS. This may be a bit more involved, and is a difficult undertaking.

**Comment by akien-mga** [comment] 2023-10-30 13:26
It's been two years and I think the performance of Godot 3.x is decent on macOS, so I think we can close this as fixed.

**Closed by akien-mga** 2023-10-30 13:26 UTC
Labels: bug, platform:macos, topic:rendering, regression
