### ISSUE TITLE
Expected constant string for assert error message

### ISSUE THREAD

**Issue by pkowal1982** [godotengine/godot#59274] opened 2022-03-18 12:19 UTC
### Godot version

4.0.alpha4.official

### System information

Ubuntu 21

### Issue description

Using non constant string message in assert gives an error.
Documentation says it can be var.
Using only const (if it was intentional) is in my opinion too restrictive.

### Steps to reproduce

Try to use such syntax:
assert(speed < 20, "speed = %f, but the speed limit is 20" % speed)
or use the provided test project.

### Minimal reproduction project

[assert_bug.zip](https://github.com/godotengine/godot/files/8304370/assert_bug.zip)

**Comment by KoBeWi** [comment] 2022-03-18 14:35
Duplicate of #47157

**Closed by KoBeWi** 2022-03-18 14:35 UTC
