### ISSUE TITLE
[Godot 4] Enabling SS Reflections infinite loop error

### ISSUE THREAD

**Issue by nonunknown** [godotengine/godot#49164] opened 2021-05-28 12:00 UTC
**Godot version:**
https://github.com/godotengine/godot/commit/364ea7f280a3f074795e542b16b1d0ec76cf6ce2

**OS/device including version:**
Windows 10 x64

**Issue description:**
When using worldevironment and enables the SS Reflections, console throws infinite loop error:

```
   at: (drivers\vulkan\rendering_device_vulkan.cpp:7133)
ERROR: Attempted to use an unused shader variant (shader is null),
   at: (C:\Users\nonunknown\Desktop\godot\servers/rendering/renderer_rd/pipeline_cache_rd.h:71)
ERROR: This render pipeline requires (0) bytes of push constant data, supplied: (16)
   at: (drivers\vulkan\rendering_device_vulkan.cpp:6562)
ERROR: No render pipeline was set before attempting to draw.
   at: (drivers\vulkan\rendering_device_vulkan.cpp:6579)
ERROR: Uniforms supplied for set (3):
Set: 1 Binding: 0 Type: CombinedSampler Length: 1
Set: 1 Binding: 1 Type: CombinedSampler Length: 1
are not the same format as required by the pipeline shader. Pipeline shader requires the following bindings:
Set: 0 Binding: 0 Type: Image Length: 1
Set: 0 Binding: 1 Type: Image Length: 1
Set: 1 Binding: 0 Type: Image Length: 1
Set: 1 Binding: 1 Type: Image Length: 1
Set: 2 Binding: 0 Type: Image Length: 1
Set: 3 Binding: 0 Type: CombinedSampler Length: 1
```

**Steps to reproduce:**
* Create a 3d Scene
* Add a WorldEnvironment node
* Enable SS Reflections

**Minimal reproduction project:**
N/A

**Comment by clayjohn** [comment] 2021-05-28 14:24
Duplicate of https://github.com/godotengine/godot/issues/40779

**Closed by clayjohn** 2021-05-28 14:24 UTC
