### ISSUE TITLE
Predictive Input on iOS appears under upper line of virtual keyboard.

### ISSUE THREAD

**Issue by stayseek** [godotengine/godot#19673] opened 2018-06-20 13:54 UTC
**Godot version:**
2.1.4 stable, 2.1.5rc

**OS/device including version:**
MacBook Air (13-inch, Early 2014) (1,4 GHz Intel Core i5)
MacOS High Sierra 10.13.3
iPhone 5S

**Issue description:**
When Predictive Input in iOS keyboard settings is set, predictive input fields appears under upper buttons of virtual keyboard.

**Steps to reproduce:**
In script used OS.show_virtual_keyboard("")
Also tries OS.show_virtual_keyboard()
![error](https://user-images.githubusercontent.com/20367996/41662759-78d492a8-74aa-11e8-86d0-7c39879f2c4e.png)

**Comment by alekmlynek** [comment] 2018-08-03 15:14
I've run into this bug with the latest Godot. Also, 'hiding' the keyboard doesn't work either without using OS.hide_virtual_keyboard but that's a separate issue.

Godot 3.0.2 Stable
iPhone 8
iOS 11.4.1

![img_f7bc105875f5-1_preview](https://user-images.githubusercontent.com/4039858/43650548-48353e84-96fd-11e8-8b39-a83693377025.jpeg)
 Godot 3.0.2stable.official

**Comment by KoBeWi** [comment] 2020-06-17 08:59
Can anyone still reproduce this bug in Godot 3.2.1 or any later release (e.g. [3.2.2-rc1](https://godotengine.org/article/release-candidate-godot-3-2-2-rc-1))?

**Comment by KoBeWi** [comment] 2020-09-28 00:24
Closing due to no reply. Please comment if you can still reproduce in 3.2.3+.

**Closed by KoBeWi** 2020-09-28 00:24 UTC
Labels: bug, platform:ios, topic:porting
