### ISSUE TITLE
Mac export does not set the binary as executable

### ISSUE THREAD

**Issue by azurvii** [godotengine/godot#4618] opened 2016-05-11 10:48 UTC
**Operating system or device - Godot version:**
Mac OS X 10.11.4, Godot 2.0.2.stable.official

**Issue description** (what happened, and what was expected):
Exporting Mac binary, the app does not run. I went in the directory, it looks like the binary file is not set as executable. chmod +x the binary file could resolve the issue.

It's similar to #4219's first point, but it's not crashing for me, and whether or not 64-bit option is on ends the same for me (non-executable).

**Comment by akien-mga** [comment] 2016-05-11 12:05
Can you check in the OSX export template directly if the binary is executable? IINM, the build script used for 2.0.1 and 2.0.2 is supposed to make the binary executable, and then zip the .app; the .zip should then keep the executable bit for the binary inside (in theory).

**Comment by azurvii** [comment] 2016-05-11 13:21
The template itself contains multiple executables:

    $ ll osx_template.app/Contents/MacOS/
    -rwxr-xr-x@ 1 user  staff    25M Apr 12 01:57 osx_template.app/Contents/MacOS/godot_osx_debug.32
    -rwxr-xr-x@ 1 user  staff    25M Apr 12 01:57 osx_template.app/Contents/MacOS/godot_osx_debug.64
    -rwxr-xr-x@ 1 user  staff    24M Apr 12 01:57 osx_template.app/Contents/MacOS/godot_osx_release.32
    -rwxr-xr-x@ 1 user  staff    24M Apr 12 01:57 osx_template.app/Contents/MacOS/godot_osx_release.64

The bundle generated is not:

    $ ll FirstGodotGameBundle.app/Contents/MacOS/FirstGodotGameBundle 
    -rw-r--r--  1 user  staff    24M Apr 11 19:57 FirstGodotGameBundle.app/Contents/MacOS/FirstGodotGameBundle

Am I not looking at the export directory "directly"?

**Comment by akien-mga** [comment] 2016-05-11 13:25
@punto- Any idea?

All in all it's similar to #527, but it seems people were not complaining about this some months ago so could it be a regression?

**Comment by punto-** [comment] 2016-05-11 17:24
I think this should be set when we construct the .zip during the final
export. Remember that it should be possible to export for OSX from a
Windows machine, and even if the file is set to executable in the template,
the exporter will unzip the template, and rebuild a new .app structure with
the game and the binaries inside a .zip. So whatever needs to happen, it's
some flag that goes in during the .zip creation..

**Comment by akien-mga** [comment] 2016-05-11 17:26
Ok, so it's the same problem as #527. We can't just use ``chmod +x`` for that as it's not cross-platform. Are there platform-specific APIs we can use to write binaries with the execution bit?

**Comment by azurvii** [comment] 2016-05-12 05:24
I have not tried: https://stackoverflow.com/a/434689/1066506, which needs python.
I don't know what tools are available for the exporter to use, but how about using .tar.gz instead of .zip? Both formats are open-able by Mac's stock Archive Utility.

**Comment by azurvii** [comment] 2016-07-12 07:55
Not sure if there has been any progress on this, and/or #527. Mac binaries from 2.0.4.1 and the Mac template I compiled 1 or 2 weeks ago still failed to run.

IMHO, I think it's better to apply the quick fix @akien-mga mentioned in that issue to use chmod for the time being. i.e. to only leave the Windows cross-compiling part broken (which maybe not even many people care about?) while figuring out the solution and letting other platforms work which do care about these exports.

**Comment by akien-mga** [comment] 2016-07-14 07:54
Closing as duplicate of #527 since both issues are being discussed together.

**Closed by akien-mga** 2016-07-14 07:54 UTC
Labels: bug, platform:osx, topic:porting
