### ISSUE TITLE
Artifact at the bottom of the scene

### ISSUE THREAD

**Issue by QazPolma** [godotengine/godot#55750] opened 2021-12-09 10:30 UTC
### Godot version

3.4.stable

### System information

Linux Mint 20.2, OpenGL ES 3.0 AMD Vega 8

### Issue description

There is an artifact at the bottom of the scene. When running the scene from the editor, it's only a dot. When exporting to android, it becomes a rectangle shaped artifact. The artifact even distorts a custom sky environment.
Editor scene
![debug_scene_dot](https://user-images.githubusercontent.com/19222931/145378299-41903168-7811-4a07-9697-abf48e7ca663.png)
Android with default sky environment
![android_scene_artifact](https://user-images.githubusercontent.com/19222931/145378362-4436f975-5134-41b2-baff-59ac087baacf.png)
Android with custom sky environment
![android_scene_artifact_2](https://user-images.githubusercontent.com/19222931/145378371-7d02e053-0e08-4527-8bf4-76ed72fbe495.png)

### Steps to reproduce

Add a camera to 3d scene.
Run scene from editor.
Angle camera downwards until the "dot" comes into view.
Export this scene to android.

### Minimal reproduction project

[CameraArtifact.zip](https://github.com/godotengine/godot/files/7684232/CameraArtifact.zip)

**Comment by Chaosus** [comment] 2021-12-09 10:44
Duplicate of https://github.com/godotengine/godot/issues/37192

**Closed by Chaosus** 2021-12-09 10:44 UTC
