### ISSUE TITLE
Can't export anything to HTML5 on 3.2.4.rc3

### ISSUE THREAD

**Issue by eh-jogos** [godotengine/godot#46637] opened 2021-03-03 22:19 UTC
**Godot version:** 3.2.4.rc-3 official

**OS/device including version:** Manjaro Linux (i3 Distribution)

**Issue description:**
I was trying out 3.2.4.rc-3 for my daytime job as we could use some of the html 5 optimizations, so I downloaded it from the site, downloaded the export templates from within Godot and tried out our project. Everything seems fine in the editor and as well as running it with F5, but once I clicked in the HTML5 button to test it in the browser (Firefox) it didn't work. It opens an empty popup with no message and just an "ok" button and when you click it I get a "indirect call to null" error.

So I created an empty project (attached below) with only a scene with a label and godot's icon, and tried to play in browser. Same error. On chrome I get the same empty popup but the error aftewards is "function signature mismatch". I'm suspcious that this is something on my end? I mean, it seems like something too noticeable for me to be the first to report it, but I also have no idea what could be causing it on my end.

When I open this same project in 3.2.3 and run it in the browser again, it works fine. Haven't tested it on windows yet.

**Steps to reproduce:**
Open the attached project in Godot 3.2.4-rc3 and click the play in browser button.

**Minimal reproduction project:**
[324rc3_teste.zip](https://github.com/godotengine/godot/files/6079521/324rc3_teste.zip)

**Comment by Calinou** [comment] 2021-03-03 22:21
Duplicate of https://github.com/godotengine/godot/issues/46352.

**Closed by Calinou** 2021-03-03 22:21 UTC

**Comment by eh-jogos** [comment] 2021-03-04 00:24
oh well, I searched for he html5 tag, but I guess I only searched on open issues, so I missed the closed one! Sorry for the duplicate.

**Comment by akien-mga** [comment] 2021-03-04 07:19
No worry, that's easy to miss, especially when we fix new issues so fast :P
Thanks for reporting it, it's much better to have duplicate reports than to miss a critical regression.
