### ISSUE TITLE
"Visible Paths" ignores top_level.

### ISSUE THREAD

**Issue by simnba** [godotengine/godot#90087] opened 2024-03-31 23:59 UTC
### Tested versions

Found in v4.2.1.stable.official [b09f793f5]

### System information

Godot v4.2.1.stable - Windows 10.0.22631 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3070 (NVIDIA; 30.0.15.1165) - AMD Ryzen 5 3600 6-Core Processor (12 Threads)

### Issue description

Debug > Visible Paths displays Path3D nodes with parent transform applied, even though top_level is true.  

### Steps to reproduce

- Create Node3D.
- Add child Path3D, set some curve, set "Top Level" to on
- Change position of Node3D (Path3D does not move)
- Enable Debug > Visible Paths
- Run project
Observed: Path is displayed with its position being relative to the parent Node3D.
Expected: Path is displayed without parent transform (as in the editor).

### Minimal reproduction project (MRP)

N/A

**Comment by ajreckof** [comment] 2024-04-01 06:55
Can reproduce on 4.2.1 but can't reproduce on master most likely it was already reported and fixed.

**Comment by ajreckof** [comment] 2024-04-02 03:32
Duplicate of #84290 and fixed by #84643

**Closed** 2024-04-05 12:57 UTC
Labels: bug, topic:editor, needs testing
