### ISSUE TITLE
Clicking in Output window crashes 

### ISSUE THREAD

**Issue by addmix** [godotengine/godot#36524] opened 2020-02-25 03:24 UTC
**Godot version:**
3.2 Stable
**OS/device including version:**
Win 10 64 bit
**Issue description:**
If you click in the output window of Godot, the next time you run the project it hangs on loading 100%
**Steps to reproduce:**
Open a project, go into Godot output window, click anywhere, run project
**Minimal reproduction project:**
A default node (not Node2D or Spactial) scene

https://youtu.be/mbVYmt3HDCQ

**Comment by nathanwfranke** [comment] 2020-02-25 04:59
When you "Select" in the windows command line, the program execution will be forcefully paused. I am not sure if it is possible for any program (let alone Godot) to override this.

**Comment by qarmin** [comment] 2020-02-25 06:13
Duplicate of #34200 and this is normal Windows behaviour

**Closed by qarmin** 2020-02-25 06:13 UTC
Labels: archived
