### ISSUE TITLE
Crash changing type of multiple nodes

### ISSUE THREAD

**Issue by NewNodeGames** [godotengine/godot#23853] opened 2018-11-20 15:11 UTC
**Godot version:**

3.1 dev

**OS/device including version:**

Archlinux (4 GB Ram + swap)

**Issue description:**

Godot eats lots of ram, freezes and finally crash changing node type on multiple nodes.

**Steps to reproduce:**
open the reproduction project, select all grass+number nodes and try to change type. I tried change to mesh instance.

**Minimal reproduction project:**

[node_issue.zip](https://github.com/godotengine/godot/files/2600311/node_issue.zip)

**Comment by qarmin** [comment] 2018-11-20 16:42
This is in console log 
'''
TOTAL BYTES: 1048560
NULL count: 42672
CALL set_value: 128
CALL _request_gizmo: 144
CALL _update_callback: 25
CALL _update_minimum_size: 2
CALL _sort_children: 6
CALL _update_script_names: 1
CALL _update_tree: 143
CALL _test_update_tree: 296
CALL _update_bone_list: 1
ERROR: push_call: Message queue out of memory. Try increasing 'message_queue_size_kb' in project settings.
   At: core/message_queue.cpp:56.
Failed method: EditorPropertyInteger:_sort_children target ID: 434036
'''
And of course, almost all console is spammed by
'''
Object was deleted while awaiting a callback
'''

**Comment by Xrayez** [comment] 2018-11-20 17:01
Something tells me that default message queue size should be increased, I've experienced this error while developing a plugin that used a lot of signal calls (changing resource properties). Modifying multiple nodes at the same time causes these errors apparently...

**Comment by radishes** [comment] 2018-12-27 18:41
I ran into a similar issue while trying to simply load a certain tileset .tres file in the editor. I increased my project's `message_queue_size_kb` from 1024 to 102400 and it no longer occurs.

**Comment by henriiquecampos** [comment] 2019-11-18 17:49
This is still happening on Godot 3.2.beta1

**Comment by akien-mga** [comment] 2020-01-28 08:01
Related to #35653.

**Comment by akien-mga** [comment] 2022-03-26 12:28
This is no longer reproducible as is in the current `3.x` branch as the operation in the steps to reproduce is now illegal:
![image](https://user-images.githubusercontent.com/4701338/160239410-6f7ace3e-ab29-4bf1-8490-95a95c8fd001.png)

I don't know if that's intentional or if that's a bug, but if the latter this is material for a new bug report.

Otherwise the original issue here is another consequence of #35653, so closing as duplicate of #35653.

**Closed by akien-mga** 2022-03-26 12:28 UTC
Labels: bug, topic:editor, confirmed, usability
