### ISSUE TITLE
An error occurs in the computed position of the function _can_drop_data

### ISSUE THREAD

**Issue by xiaoxustudio** [godotengine/godot#88595] opened 2024-02-20 13:33 UTC
### Tested versions

4.2.stable

### System information

Godot v4.2.stable - Windows 10.0.22631 - GLES3 (Compatibility) - Intel(R) Iris(R) Xe Graphics (Intel Corporation; 31.0.101.4953) - 12th Gen Intel(R) Core(TM) i7-1255U (12 Threads)

### Issue description

When I disable `display/window/subwindows/embed_subwindows` 
option in the project Settings, and the `display/window/stretch/mode` set to **canvas_item**, zoom window function after `_can_drop_data` calculated position deviation happened, then I create a new project, The problem still exists

### Steps to reproduce

1. Set the `display/window/subwindows/embed_subwindows` to false
2. Set the `display/window/stretch/mode`  to canvas_item
3. Create the basic drag functions _get_drag_data, _can_drop_data  and _drop_data
4. In the end they will not work as expected

### Minimal reproduction project (MRP)

[test.zip](https://github.com/godotengine/godot/files/14345110/test.zip)

**Comment by kleonc** [comment] 2024-02-20 15:03
Duplicate of #86493 (allready fixed by #86511).

**Closed by kleonc** 2024-02-20 15:03 UTC
Labels: bug, topic:gui
