### ISSUE TITLE
Singleton not autoloaded when in editor mode

### ISSUE THREAD

**Issue by nadnam** [godotengine/godot#16012] opened 2018-01-23 23:05 UTC
**Godot version:**
 v3.0.rc2.official

**Issue description:**
Scripts using singletons don't recognize singleton identifiers while in editor, as they are not loaded. Both script and singleton have "tool" first line. In more complex projects, this problem silently crashes script loading in editor, no error messages are shown at all except for missing exported variables in tree node editors & nodes being invisible in 3d world (meshes fail to load etc). Running these projects work correctly, though.

**Steps to reproduce:**
Open project in editor, check output tab for error messages. When project is run everything works as expected.

**Minimal reproduction project:**
[BugTest.zip](https://github.com/godotengine/godot/files/1657930/BugTest.zip)

**Comment by vnen** [comment] 2018-01-23 23:39
Thanks for the report, but this is an old known issue. Closing as duplicate of #4236.

**Closed by vnen** 2018-01-23 23:39 UTC
