### ISSUE TITLE
Projects lost from project list when multiple editor instances are running

### ISSUE THREAD

**Issue by tx350z** [godotengine/godot#57445] opened 2022-01-30 13:10 UTC
### Godot version

v3.4.1.stable.official

### System information

Windows 11 Home Version: 21H2 OS build: 22000.434 Experience	Windows Feature Experience Pack 1000.22000.434.0

### Issue description

I often have multiple projects open in separate editor instances. Until recently this was not a problem. Now, if I open an additional editor instance and create a new project, the new project eventually disappears from the project list. I'm assuming that one of the other editor instances is overwrites the entire project list.

### Steps to reproduce

1 Open the editor on a project.
2 Open a second editor instance and create a new project.
3 Close the editor second instance.
4 Close the first editor instance.
5 Open the editor again.
6 The project created in step 2 does not appear in the project list.

**Comment by KoBeWi** [comment] 2022-01-30 20:03
This is because project list is stored in editor settings and they are saved automatically upon exit.

**Comment by Calinou** [comment] 2022-01-30 21:08
Duplicate of https://github.com/godotengine/godot/issues/40968 (same cause).

**Closed by Calinou** 2022-01-30 21:08 UTC
