### ISSUE TITLE
game crashes without any error when using GD.Print to print a just queuefreed node instance in C#.

### ISSUE THREAD

**Issue by Kadaka** [godotengine/godot#38632] opened 2020-05-10 14:44 UTC
**Godot version:**
Godot_v3.2.1-stable_mono_win64

**OS/device including version:**
Windows 10 latest version

**Issue description:**
After a node instance is queuefreed,  if it is printed by GD.Print, the game will crash without any error.

**Steps to reproduce:**
Just run this piece of code, the bug will appear.

using Godot;
using System;

public class NewScene : Node2D
{
	Node2D newNode = new Node2D();
		
	public override void _Ready()
	{

		GD.Print("ready!");		
		AddChild(newNode);
		GD.Print(newNode);

	}

	public override void _Process(float delta)
	{
		newNode.QueueFree();
		GD.Print(newNode);
	}
}
**Minimal reproduction project:**

**Comment by akien-mga** [comment] 2020-05-10 14:50
Duplicate of #38544.

**Closed by akien-mga** 2020-05-10 14:50 UTC
