### ISSUE TITLE
drag and drop back from FileSystem tab delete scene

### ISSUE THREAD

**Issue by puppetmaster-** [godotengine/godot#10467] opened 2017-08-19 22:29 UTC
**Operating system or device - Godot version:**
Windows 7, Godot Engine v2.1.3.stable.official

**Issue description:**
drag and drop back from FileSystem tab delete scene

**Steps to reproduce:**
![drag_and_drop_delete_node](https://user-images.githubusercontent.com/10463138/29490494-68f9e9a2-853e-11e7-8b7c-fbd41342046f.gif)

**Comment by akien-mga** [comment] 2017-08-20 11:20
Uh, that's bad. Needs to be fixed for 3.0 if valid there, and ideally for 2.1.4 too.

**Comment by akien-mga** [comment] 2017-08-20 11:27
Can't reproduce in the master branch, so 2.1 only.

**Comment by akien-mga** [comment] 2018-09-17 14:17
The 2.1 branch is no longer actively worked on by engine developers, unless critical fixes are needed for current games in production. As such we are now closing non-critical bug reports affecting only the 2.1 branch.

Please comment if this was incorrectly triaged and is still relevant in 3.x versions.

**Closed by akien-mga** 2018-09-17 14:17 UTC
Labels: bug, topic:editor
