### ISSUE TITLE
Godot 3.1 few feature Request

### ISSUE THREAD

**Issue by abhaskumarsinha** [godotengine/godot#14938] opened 2017-12-22 10:08 UTC
Please add PBS, BRDF And PBR in Godot 3.1, also, please release alpha release as soon as possible.
And these are optional features -
1. God Rays
2. Unity like material editor which supports glossy, reflective, metallic and specular
3. Unreal Engine like Terrain Editor
4. PSP2 and PSP4 support,

Also, if you'd ask, why these features should be given top priority, its because, these effects/features are mostly used in game dev by AAA Engines (as per Ubi-magzine 2017 November edition) 

All these are not orders which are to be completed until 3.1, these are request which should be completed at own pace,
I know you developers are doing too much hard work, so, please comment, if any help is needed for Godot 3.1, like Docs or any other stuff, 
It'd be my pleasure to work with you talented guys!

**Comment by mhilbrunner** [comment] 2017-12-22 10:59
1 is planned I think.
2 and 3 are a cool idea :)
Can you explain 4 a little more?

**Comment by Zireael07** [comment] 2017-12-22 11:05
Godot 3.0 already has a PBR renderer which has metallic and specular?

**Comment by LinuxUserGD** [comment] 2017-12-22 11:28
Godot already has a material editor where you can tweak the material itself and add special textures. So 2 is already a feature.

**Comment by levrik** [comment] 2017-12-22 12:12
there is already a terrain plugin for Godot (2): https://github.com/Zylann/godot_terrain_plugin
Don't know if it's good tho.

**Comment by Zylann** [comment] 2017-12-22 12:30
@levrik forget about the plugin, it's outdated. The C++ module is better and I may consider working more on it if needed for 3.1, see https://github.com/godotengine/godot/issues/9046

**Comment by Calinou** [comment] 2017-12-22 15:05
Please create one issue per proposed feature, *after* checking for potential duplicates.

Also, note that the specular + glossiness workflow is unlikely to be supported in the near future.

**Comment by abhaskumarsinha** [comment] 2017-12-23 11:52
Those who are not able to understand what are wishes, let me explain :- 
1. God Rays (Volumetric effect, is a effect caused by a scientific phenomenon called Tyndall effect)
- Tyndall effect is a effect which most of us have commonly have seen them in foggy morning in a forest, where a ray of light becomes visible. Scientifically,
When dust particles are suspended in air, the ray of light start scattering, and the color of scattering of light depends upon the size of the particles. If particles are bigger, then they scatter blue light (due to their wave length) and if they are smaller, they scatter red. (Note violet is not scattered.)

example images -
1. [Experiment](http://www.epicphysics.com/wp-content/uploads/2012/03/the-tyndall-effect-300x300.jpg)
2. [Forest](http://www.epicphysics.com/wp-content/uploads/2012/03/the-tyndall-effect-300x300.jpg)

2. Need a plugin/asset which is similar to crazybump, (Unity and Unreal have this), in which we will be able to adjust the sliders with different options, until we get realistic material. I mean how much of normal power, specularity and other sliders, will be there in opengl 2.1 version also, I know they are in Opengl3, but I want that in opengl2 also.
example -

1.[Tutorial to use of Crazy Bump](https://www.google.co.in/search?q=crazy+bump+tutorial&dcr=0&tbm=vid&source=lnms&sa=X&ved=0ahUKEwigtOrkh6DYAhUIM48KHVqrA48Q_AUICigB&biw=1366&bih=606&dpr=1)

3. For those who don't know Unreal Engine, it has most advanced Terrain/Vegetation editor, that can use multimesh instance and you can even grow grasses and trees over any mesh with few click,

4. Play Station 2 and Play Station 4, are the most difficult Console to make game for. So, if we are able to target them, we may reach other console which use OpenGL before the finish of PS.


@Calinou @Zylann @levrik @LinuxUserGD @Zireael07 @mhilbrunner

**Comment by LinuxUserGD** [comment] 2017-12-23 12:30
3. Gimp has a plugin called insane bump and Godot has some sliders to tweak normal maps...

**Comment by mhilbrunner** [comment] 2017-12-23 13:44
I don't think that Godot needs Playstation 2 support. :,D

Support for terrains and god rays are planned in some capacity.

Btw, you don't need to mention everyone, all that are subscribed to the issue get a notification anyway. :)

**Comment by LinuxUserGD** [comment] 2017-12-23 18:15
And change the title pls

**Comment by vnen** [comment] 2017-12-24 02:11
Console ports ain't gonna happen like that, for a variety of (mostly legal) reasons. It's not a work anyone is willing to do for free. Even if someone in the community is willing, they could share the console port only with licensed developers.

I know everyone is excited about Godot 3, but you can't expect all advanced features of engines made by big companies with lots of full-time devs. Maybe Godot gets to that stage (we hope so) but it takes quite some time.

**Comment by aaronfranke** [comment] 2018-01-21 00:30
@abhaskumarsinha Please create individual issues per topic.

**Comment by mhilbrunner** [comment] 2018-01-21 11:53
Closing this, as the issue is vague and all of these were answered above.

As explained, your requests are either already planned or on the roadmap, have issues or will not happen.

If you still have additional requests, please open one issue per request. Thank you!

**Closed by mhilbrunner** 2018-01-21 11:53 UTC
Labels: feature proposal
