### ISSUE TITLE
Is_action_pressed stay presed but is not truth

### ISSUE THREAD

**Issue by davidkbd** [godotengine/godot#31952] opened 2019-09-04 09:32 UTC
**Godot version:**
3.2 (nightly)

**OS/device including version:**

Linux davidkbd-Vostro-3558 4.15.0-58-generic #64-Ubuntu SMP Tue Aug 6 11:12:41 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
00:02.0 VGA compatible controller: Intel Corporation HD Graphics 5500 (rev 09)

**Issue description:**
Sometimes when a key is pressed, the is_action_pressed method persists returning true after I have released the key.
I know that similar bugs were fixed: on change scene, on window lost focus, etc. But the bug persists.
I think it could be produced by a cpu saturation but I'm not sure. It is very randomly and is difficult to reproduce. Hours can pass without it happening...

**Steps to reproduce:**
I dont know but this bug is not when:
- Ctrl or shift or alt is pressed at same time than other key.
- window lost focus
- press during a change between scenes

All time I have this   ##behavior is pressing "ui_up", "ui_down", "ui_left", or "ui_right".

**Minimal reproduction project:**

**Comment by sashton** [comment] 2019-09-15 22:09
Here are some steps I've found to reproduce this behavior consistently:

**Minimal project code**
```
# Single root Node with the following script

extends Node

func _process(delta):
	if Input.is_action_just_pressed("ui_right"):
		print("right - PRESSED")
	if Input.is_action_just_released("ui_right"):
		print("right - RELEASED\n")
	if Input.is_action_pressed("ui_right"):
		print("right - > HELD")
```
**Steps**
* launch game, but **don't click on the game title bar**
* __quickly__ tap the input button a few times (probably less than 20 times)
* after a few attempts, you will see the output continue to print `HELD` even after the key has been released.
* looking back in the log output, you will notice that `RELEASED` was never triggered in the case where `HELD` is continuously printed

To avoid this behavior, at any time, click on the title bar of the game window. Thereafter, `RELEASED` will trigger as expected every time.

**Godot Version**
3.1.1.stable.official

**OS**
Linux steve-xps 4.15.0-60-generic #67-Ubuntu SMP Thu Aug 22 16:55:30 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Video Card**
00:02.0 VGA compatible controller: Intel Corporation UHD Graphics 620 (rev 07) (prog-if 00 [VGA controller])

**Comment by Calinou** [comment] 2019-11-28 12:35
Duplicate of #27104. As a workaround, you can call `Input.set_use_accumulated_input(false)` in any script's `_ready()` function.

**Closed by Calinou** 2019-11-28 12:35 UTC
Labels: bug, needs testing, topic:input
