### ISSUE TITLE
Inspector > Hint > Tooltip; mouse scroll wheel down does not work

### ISSUE THREAD

**Issue by eltharionx** [godotengine/godot#36036] opened 2020-02-08 22:33 UTC
**Godot version:**
v3.2.stable.official

**OS/device including version:**
Windows 7

**Issue description:**
When using the mouse scroll wheel to scroll down the inspector properties, there is an area inside the Hint>Tooltip that ignores the scroll wheel "down".  The area does recognize a scroll wheel "up", but not a scroll wheel "down".  See screenshot here: [https://i.imgur.com/6cRryj5.png](https://i.imgur.com/6cRryj5.png)

**Steps to reproduce:**
Open up Godot, add a button node, click on the button to see the inspector tab, then scroll your mouse wheel down.  It will stop scrolling in that Hint>Tooltip area.

**Minimal reproduction project:**
n\a

**Comment by Calinou** [comment] 2020-02-08 23:09
Duplicate of #34622. (The underlying issue is the same.)

**Closed by Calinou** 2020-02-08 23:09 UTC
