### ISSUE TITLE
Running a C# project with a 32 bits binary on a 64 bits windows causes a crash

### ISSUE THREAD

**Issue by LaurentOngaro** [godotengine/godot#17299] opened 2018-03-06 10:13 UTC
**Godot version:**
commit : SHA-1: 91ed6787088f888e196331915d59154ef2a6ce58
(but occurs with previous versions too)

**OS/device including version:**
Microsoft Windows 10 Professionnel 64 Bits
OS Version: 10.0.16299 Numéro 16299
NVIDIA GeForce GTX 1060 6GB (driver Version 23.21.13.9077)

**Issue description:**
I've managed to compile the GODOT sources from github for windows x86 and x64 but only the 64 bits version of the editor (and export templates) can open and run a very basic C# project on my PC.
The 32 bits version of all the binaries crashes when I try to run the game (in the editor or after exporting to a 32 bits version). 

Details and tested solutions:
- both mono versions are installed and sync (anyway, I use the dlls created by the compilation). 
Note that exporting the C# project to win32 or win64 produce similar results: win64 runs well whereas win32 crashes
- the generated Dlls and exe are copied to a specific folder between 32 and 64 build to avoid files replacement 
- the tested project is very basic: single scene with a sprite moved by script
- I've tried to put the ._sc_ file in each version of the editor to avoid conflicts that can appear if they share the same data folder.
- removing the .mono folder in the project changes nothing on running but avoids a crash on opening.
- the output window displays several "<couldn't map PC to fn name>" warnings just before crash

I think that maybe something is trying to load a 64bit dll in the 32bit environment.

This is the backtrace when a crash occurs:
OpenGL ES 3.0 Renderer: GeForce GTX 1060 6GB/PCIe/SSE2
Mono: Initializing module...
Mono: Runtime initialized
Mono: INITIALIZED
GO!
CrashHandlerException: Program crashed
Dumping the backtrace. Please include this when reporting the bug on https://github.com/godotengine/godot/issues
[0] mono_runtime_resource_limit
[1] <couldn't map PC to fn name>
[2] <couldn't map PC to fn name>
[3] <couldn't map PC to fn name>
[4] RtlRbInsertNodeEx
-- END OF BACKTRACE --

**Steps to reproduce:**

1. Compile the source WITH MONO on a 64 bits windows system.
2. Open and run a c# project with a 32 bits binary.

You can find the DOS batch file I use for compilation with Visual studio 2017 here:
https://gitlab.com/snippets/1701292

**Minimal reproduction project:**
[BuildTest_CS.zip](https://github.com/godotengine/godot/files/1784488/BuildTest_CS.zip)

**Comment by LaurentOngaro** [comment] 2018-03-06 10:36
message windows when a crash occurs

![image](https://user-images.githubusercontent.com/2209551/37027744-7c6229c4-2132-11e8-9937-87259ade48f6.png)

**Comment by akien-mga** [comment] 2018-03-06 10:47
CC @neikeq

**Comment by LaurentOngaro** [comment] 2018-03-06 13:57
I've just tested it with the builds available here
https://downloads.tuxfamily.org/godotengine/3.0.2/mono
and ..... Same issue

**Comment by LaurentOngaro** [comment] 2018-03-23 14:02
Recently I've tested a build on a x86 windows 10 system from master branch and ....... Same issue.
So It doesn't seem to be a cross compiling issue

**Comment by exts** [comment] 2018-07-11 16:56
Reproduced on windows 10 64 bit system. Build using 3.0.5 stable and unchecked 64bit. 

CC @hpvb

**Comment by Kiotenhariyo** [comment] 2018-11-21 15:43
Same here win10
Can open projects created with 64bit Godot in 32bit Godot - ONLY if no "64bit" C# files exists in project.
Any project generated in 64 bit godot with C# files/solution crashes if opened in Godotmono 32bitmono

Have both 64 and 32 recommended mono versions installed

**Comment by exts** [comment] 2019-01-09 19:03
Reproduce again with 3.1 beta1 (cc: @hpvb @neikeq)

```
Stacktrace:

Memory around native instruction pointer (0242F775):
0242F765  11 00 12 00 13 00 14 00 15 00 16 00 17 00 18 00  ................
0242F775  ff ff 01 02 00 00 ff ff 01 08 00 00 01 00 02 00  ................
0242F785  03 00 ff ff 01 02 00 00 ff ff 01 00 ff ff 01 02  ................
0242F795  00 00 ff ff 01 02 00 00 ff ff 01 08 00 00 01 00  ................

=================================================================
Got a SIGILL while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries
used by your application.
=================================================================
```

**Comment by akien-mga** [comment] 2019-02-23 13:04
Is this still reproducible in the latest beta build?

**Comment by exts** [comment] 2019-02-23 17:51
Still an issue with beta6 https://g4mr.itch.io/godotsharp-shooter look for `3.1beta6-win32-debug.7z`

**Comment by exts** [comment] 2019-02-28 18:48
@akien-mga 

![image](https://user-images.githubusercontent.com/16387107/53590220-e95e2c00-3b56-11e9-9795-e97ea67e9ece.png)
![image](https://user-images.githubusercontent.com/16387107/53590233-f1b66700-3b56-11e9-8dd0-e31f927edc2c.png)

You could probably move this to 3.2 for now as the 32bit editor exports 32bits correctly (at least there's a way to get these builds, just tedious atm), but this should definitely get looked at down the line.

**Comment by neikeq** [comment] 2019-07-25 19:24
I cannot reproduce it on latest master, building against Mono 6.0.0.313 32bit.
I can reproduce it with 3.1.1 stable, but I cannot get a backtrace (it doesn't get handled by our crash handler somehow).

**Comment by exts** [comment] 2019-12-21 16:48
Still an issue with 3.2beta4 on windows 10.

**Comment by GeorgeS2019** [comment] 2020-01-02 10:46
@akien-mga  Thanks for taking care of ALL THINGS windows for Godot.  Please try your best!

**Comment by neikeq** [comment] 2020-01-20 13:43
I can reproduce this with 3.2 RC2. However, there's no error or crash report, so it's not very helpful.

I just tried to build from source again with latest master (c3fd1012de2d0913a375ddfe6ee93035fe5260eb) and MSVC 14.1.

Command:

```
scons.bat p=windows -j 3 target=debug tools=yes verbose=yes module_mono_enabled=yes bits=32 mono_prefix=PATH_TO_32_BIT_MONO_PREFIX mono_static=yes copy_mono_root=yes
```

I also tested without `mono_static=yes`. Make sure to include `copy_mono_root=yes`.

I could **not** reproduce any crash.

Please, if any one can still reproduce this when building with MSVC, try to include as much information as possible on the steps to reproduce. A backtrace from a debug build would also be welcome.

If no one else can reproduce this with MSVC, maybe it has something to do with the official builds, which use MinGW.

**Comment by LaurentOngaro** [comment] 2020-01-20 14:54
I'm not able to test it because I'm no longer on Windows, so I don't know if the bug is still present
I'm on Arch Linux now, and I cross compiling the binaries for windows

**Comment by akien-mga** [comment] 2020-01-22 08:04
@neikeq had some users test on Discord and they also didn't have issues when building with MSVC on Windows.

So something is faulty in our MinGW cross-compiled setup for 32-bit C# projects.

It's unlikely that we'll have time to dig into it for 3.2, so moving to the next milestone. If we find a fix we'll use it for future 3.2.x releases.

**Comment by akien-mga** [comment] 2020-07-14 08:33
According to @piratesephiroth in https://github.com/godotengine/godot/issues/30689#issuecomment-657038577, the 32-bit Mono version now works on 64-bit Windows as of Godot 3.2.2. Can others confirm?

**Comment by akien-mga** [comment] 2020-09-04 14:24
No answer, but I tested the 32-bit version of Godot 3.2.3 RC 5 on Windows 10 x64 and it seems to work just fine, so closing.

**Closed by akien-mga** 2020-09-04 14:24 UTC
Labels: bug, cherrypick:3.2, platform:windows, topic:mono
