### ISSUE TITLE
Crashes with Godot 4 no-threads Web builds on iOS Safari

### ISSUE THREAD

**Issue by ChronoDK** [godotengine/godot#88321] opened 2024-02-14 12:09 UTC
### Tested versions

Godot 4.3 Dev 3

### System information

iOS Safari, tested on different iPhone models

### Issue description

Running a game on iOS Safari does not work. The game will crash/reload after a while. In a full game project, this happens only a few seconds after loading and playing the game. In a minimum project, with only the Godot Sprite on screen it takes several minutes - but it will still crash. This also happened with threaded builds - I was just hoping no-threads would be the solution. It doesn't seem to be.

I tried making different changes in detect.py and building new export templates, but none seemed to make a difference. Don't know what else to test.

### Steps to reproduce

Just load any project in iOS Safari and wait for it to crash/reload. It can take several minutes if it's a simple project.

### Minimal reproduction project (MRP)

[minimum.zip](https://github.com/godotengine/godot/files/14279227/minimum.zip)

**Comment by adamscott** [comment] 2024-02-28 14:15
I don't have an iPhone, unfortunately. Can you try to [inspect the webpage](https://developer.apple.com/documentation/safari-developer-tools/inspecting-ios#Inspecting-a-webpage) and give me the console log? Maybe there's an error that could show why it crashes.

**Comment by ChronoDK** [comment] 2024-03-04 08:59
> @ChronoDK I don't have an iPhone, unfortunately. Can you try to [inspect the webpage](https://developer.apple.com/documentation/safari-developer-tools/inspecting-ios#Inspecting-a-webpage) and give me the console log? Maybe there's an error that could show why it crashes.

That requires a Mac, and I don't have that. Apple not trying to make things easy to debug..

**Comment by lawtonnichols** [comment] 2024-03-21 08:05
I can confirm this is happening on 4.3dev5 for my projects. I exported a project similar to @ChronoDK's minimal reproduction project [here](https://nichols.dev/godot_88321/) [(repo here)](https://github.com/lawtonnichols/godot_88321/) and it took about 6 minutes for the page to crash and reload itself on an iPhone 15 Pro running iOS 17.3.1.

Here is the console log:
<img width="1294" alt="image" src="https://github.com/godotengine/godot/assets/1699779/64e9540c-6082-4f08-9829-fe8ad5eeea25">

Unfortunately, nothing is printed to the console when the crash occurs.

**Comment by augustmon** [comment] 2024-04-22 07:37
Also having this issue with 4.3 dev 5. 
I had some collaborators test my project on Android devices, which works fine, apparently. 
With iPhone and iPad, it reloads after some 10-30 seconds.

**Comment by syedisamhashmi** [comment] 2024-06-03 05:26
Just tested this with my project and it seems like it is still happening on 4.3.beta1...

Per the above comment mentioning buffer size, I tried lowering my buffer size, to no avail .

Additionally, I also tried changing the renderer from forward, to mobile, to compatibility, and it went from reloading to throwing an error along the lines of the GL context being lost. 

I'm still investigating, but wanted to share in the event that it may help someone else

**Comment by ChronoDK** [comment] 2024-06-03 15:48
@adamscott mentioned in the recent Web Export blog post that "We’re currently investigating to fix this ASAP." - so I believe there is a fix underway. I'm really curious to hear what the problem was once it has been solved.

**Comment by adamscott** [comment] 2024-06-03 16:15
> @adamscott mentioned in the recent Web Export blog post that "We’re currently investigating to fix this ASAP." - so I believe there is a fix underway. I'm really curious to hear what the problem was once it has been solved.

I'll test your minimal project. I still get the crash on certain projects, but I couldn't reproduce it myself with an MRP.

**Comment by Avangelista** [comment] 2024-07-11 12:32
Still occurring in 4.3 beta 2. Exactly as described in OP

**Comment by RoopeAnkka** [comment] 2024-07-13 03:11
My projects are also crashing 4.3 beta 2.

**Comment by tr-afa-ret** [comment] 2024-07-25 06:24
Still happening in 4.3 beta 3

**Comment by adamscott** [comment] 2024-07-25 17:05
Could not reproduce on my iPhone 13 and my iPad Pro M4 on iOS 17.5.1 both.

**Comment by adamscott** [comment] 2024-07-25 17:09
@Avangelista @RoopeAnkka @tr-afa-ret Can you share the errors in the console that you have?

**Comment by RoopeAnkka** [comment] 2024-07-26 05:56
@adamscott my game just reloads the page with iOS. I will investigate with my gf’s mac.

Where I could give link to the game to you? Cannot shere it now in public forum (it has now some copyrighted assets)

**Comment by RoopeAnkka** [comment] 2024-07-26 06:55
![IMG_2904](https://github.com/user-attachments/assets/d56d02e6-656d-4e75-8fcc-63ce9ce229f8)

I get these errors. !is_inside_tree() seems to trigger everytime I change scenes. In the first scene there is just 2 buttons. (I’m noobie with errors)

sorry for the pic. It’s not my laptop so I took a pic instead of screenshot. 

Usually crash happens straight away when Godot loads. It reloads the page. Sometimes it will run good 10-15mins before reloading the page again. Usually then safari gives ”too many problems with page”-error.

**Comment by RoopeAnkka** [comment] 2024-07-26 10:38
@adamscott I investigated further.

My crashes were mostly from audio. When making every audio in my project a sample the crashes stoped when played first time.

When revisiting site it starts crashing with these errors:

![IMG_2906](https://github.com/user-attachments/assets/2effd53c-136a-4f2f-89ae-1cd5a72073d6)

**Comment by tr-afa-ret** [comment] 2024-07-26 12:42
Got hold of several iphones and a mac to test. Issue was reproducable on all phones, but not on desktop.
Checking the errors while connected to mac, I also got Out of memory errors as shown above.

Was unable to create a test project to reproduce the error.

Looking at the error messages further it turned out to be related to using a cutom font, in a Label node, and scaling the font size of the label with [add_theme_font_size_override](https://docs.godotengine.org/en/stable/classes/class_control.html#class-control-method-add-theme-font-size-override), gradually in the _process function
If either not using a custom font, or not changing the font size, the game doesn't crash

**Comment by adamscott** [comment] 2024-07-30 16:36
> Where I could give link to the game to you? Cannot shere it now in public forum (it has now some copyrighted assets)

> Was unable to create a test project to reproduce the error.

It's important to create MRPs. There's so many factors that can be there in an actual project, it's not really useful to have a full project.

**Comment by adamscott** [comment] 2024-07-30 16:50
> @adamscott I investigated further.
> 
> My crashes were mostly from audio. When making every audio in my project a sample the crashes stoped when played first time.
> 
> When revisiting site it starts crashing with these errors:
> 
> ![IMG_2906](https://private-user-images.githubusercontent.com/81559157/352501713-2effd53c-136a-4f2f-89ae-1cd5a72073d6.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIzNTc4NDQsIm5iZiI6MTcyMjM1NzU0NCwicGF0aCI6Ii84MTU1OTE1Ny8zNTI1MDE3MTMtMmVmZmQ1M2MtMTM2YS00ZjJmLTg5YWUtMWNkNWE3MjA3M2Q2LmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDczMFQxNjM5MDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02Y2VlMmU2YmVhY2MxOTU2OGFjYzIyZmIzZmMwY2I0YzhjYjNmNGI2MGIyOTcwN2NkOWM5ZGIxZGY0NWZjZGQxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.yBuA6MtGSrfy0fGhoDpOII9ETtbaFYpVi0OQq6i9Ixc)

If there's anything, this seems to be a Safari bug relating to WASM memory allocation, not a Godot one. Safari currently has an issue that refreshing the page doesn't free memory allocated, making the new page have less memory than before.

https://bugs.webkit.org/show_bug.cgi?id=222097

Here, I tested the issue on my iPad Pro and it still exists on Safari right now.

Closing the thread for now. There's nothing we can do currently to assess the issue that users have, based on the information I have right now.

If you can reproduce your errors on a brand-new minimal project, making sure that's not related to the Safari issue mentionned, feel free to share it here, I may reopen the issue.

**Closed by adamscott** 2024-07-30 16:50 UTC
Labels: bug, platform:web, topic:porting, needs testing, crash
