### ISSUE TITLE
Overwriting scene using "save as scene" causes node to get replaced with existing scene

### ISSUE THREAD

**Issue by dbiton** [godotengine/godot#8587] opened 2017-04-30 00:25 UTC
**Operating system or device - Godot version:**
Windows 7, godot ver 2.1.2

**Issue description:**

Tried to save node as a scene, given prompt "scene exists, overwrite?", chose to overwrite, node I tried to save was replaced. Unable to recover lost data.

**Steps to reproduce:**
Follow steps above

**Link to minimal example project:**

**Comment by Renari** [comment] 2017-04-30 07:19
I wasn't able to reproduce this on W10, Godot 2.1.3.

**Comment by Renari** [comment] 2017-04-30 07:21
Ah it seems that the save isn't outputting, it should be mentioned that if you use save as it doesn't load the scene from the file deleting your work (which is what I thought was being described). Rather if you then open the saved file it was never overwritten.

**Comment by eon-s** [comment] 2017-04-30 17:22
I was unable to reproduce with the given steps on Linux.

Having the other scene opened and modified, sometimes, showed the previous on the tree (solved by changing tabs to update the tree).

**Comment by kubecz3k** [comment] 2018-04-07 10:48
First of all thank you for your report and sorry for the delay.

We released Godot 3.0 in January 2018 after 18 months of work, fixing many old issues either directly, or by obsoleting/replacing the features they were referring to.

We still have hundreds of issues whose relevance/reproducibility needs to be checked against the [current stable version](https://godotengine.org/download), and that's where you can help us.
**Could you check if the issue that you described initially is still relevant/reproducible in Godot 3.0 or any newer version, and comment about its current status here?**

For bug reports, please also make sure that the issue contains detailed steps to reproduce the bug and, if possible, a zipped project that can be used to reproduce it right away. This greatly speeds up debugging and bugfixing tasks for our contributors.

Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

Thanks in advance.

*Note: This message is being copy-pasted to many "stale" issues (90+ days without activity). It might happen that it is not meaningful for this specific issue or appears oblivious of the issue's context, if so please comment to notify the Bugsquad about it.*

**Comment by Renari** [comment] 2018-04-07 12:01
I tested on v3.0.2.stable.mono.official on W10 and everything was working as expected.

- Created a new scene
- Added a 2DNode to the scene
- Saved the scene
- Replaced the 2DNode with a Node and a child Control component
- Used the save as feature overwriting the previously saved scene
- Closed the scene
- Reloaded the scene from the saved file
- The scene showed a Node with a child Control component and not a 2DNode.

**Comment by kubecz3k** [comment] 2018-04-08 08:11
@Renari thank you for testing this! Closing, if anyone still have the problem please let us know.

**Closed by kubecz3k** 2018-04-08 08:11 UTC
Labels: bug, topic:editor
