### ISSUE TITLE
The problem of blackness in the model when adding materials 

### ISSUE THREAD

**Issue by Sorshx** [godotengine/godot#86455] opened 2023-12-22 20:56 UTC
### Tested versions

4.2

### System information

mobile android 

### Issue description

There is a problem when adding materials to the model and exporting the model to Godot. There are black parts in the model and the sun is in one direction and there is blackness. I do not understand what the problem is, but I hope you can help me. 
![Screenshot_٢٠٢٣١٢٢٢-٢٣٤٠٣٥](https://github.com/godotengine/godot/assets/153130532/edcc59a2-43fc-4cb0-a929-73270336540b)
![Screenshot_٢٠٢٣١٢٢٢-٢٣٤٢٠٧](https://github.com/godotengine/godot/assets/153130532/73b48a2d-f068-4eb7-8eda-263aa947088c)

### Steps to reproduce

The figure is black in some parts 

### Minimal reproduction project (MRP)

It is exported obj

```[tasklist]
### Tasks
```

**Comment by Calinou** [comment] 2023-12-23 16:58
@Sorshx Please upload a minimal reproduction project[^1] to make this easier to troubleshoot.

This looks like an issue with broken mesh normals, which may be an issue with the source OBJ file. Make sure to include this file in the ZIP as well.

[^1]: A small Godot project which reproduces the issue, with no unnecessary files included. Be sure to not include the `.godot` folder in the archive (but keep `project.godot`).<br><br>Drag and drop a ZIP archive to upload it. **Do not select another field until the project is done uploading.**<br><br>**Note for C# users:** If your issue is *not* Mono-specific, please upload a minimal reproduction project written in GDScript or VisualScript. This will make it easier for contributors to reproduce the issue locally as not everyone has a Mono setup available.

**Comment by Sorshx** [comment] 2023-12-23 19:53
This is the project 

[Uploading تجارب(Copy).zip…]()

**Comment by AThousandShips** [comment] 2023-12-23 19:54
You clicked away before done, please try again

**Comment by Sorshx** [comment] 2023-12-23 19:57
This is the project 

[تجارب(Copy).zip](https://github.com/godotengine/godot/files/13760101/Copy.zip)

**Comment by lyuma** [comment] 2023-12-24 04:02
I believe the source model has incorrect normals when exported from `3DMap.Constructor. (Free) 7861 for android`.
![image](https://github.com/godotengine/godot/assets/39946030/81709621-d4f6-48d9-83d8-3e5fabb76f9e)

Unfortunately there is something wrong with the normals on this model, and I spend several minutes trying to correct the issue in blender too, but I was unable to fix it without disabling "Auto-Smooth Normals" and using flat shading on the model.

Auto-Smooth off in Blender
![image](https://github.com/godotengine/godot/assets/39946030/e8ad271e-518b-45a6-ac9c-0c1c63298acb)
Auto-Smooth on in Blender
![image](https://github.com/godotengine/godot/assets/39946030/c26934c9-3f74-40e6-93b3-eebd75ddb563)

I hate to say it, but it seems that somehow this 3D modeling software has produced extremely poor topology and it will be extremely difficult to clean up the artifacts.

As an example, I was able to clean up the roof, but it required selecting the inside bottom faces of the roof (the "base") and using the `p` key to split them into a separate mesh. Additionally, I could not get good shading without using a subdivision surface modifier.
![image](https://github.com/godotengine/godot/assets/39946030/56d1a4d1-895b-485f-a87d-84c6fe8cd6ab)
Here is how it appears in Godot after re-exporting the fixed roof:
![image](https://github.com/godotengine/godot/assets/39946030/0612c8ee-6177-46e3-8a42-28e5168613fa)
As you can see, if the model is made to look clean in Blender, it will also import correctly into Godot.

I'll attached my "fixed roof" version here if you'd like to play with it or continue fixing artifacts:
[fixed_roof.zip](https://github.com/godotengine/godot/files/13760794/fixed_roof.zip)

Unfortunately, 3D modeling is very complex and there many things to consider related to topology, normals and shading. My assessment is that if even Blender is unable to automatically correct the artifacts in this mesh without human intervention, it is not something that can be solved reasonably within Godot either. For this reason I am closing this issue. I'm sorry that the model ended up with so many artifacts, and if you have any further insight into steps that can be used to correct these artifacts, feel free to add more comments.

**Closed by lyuma** 2023-12-24 04:02 UTC
Labels: needs testing, topic:import, topic:3d

**Comment by Sorshx** [comment] 2023-12-24 12:13
Thank you for helping me ❤
