### ISSUE TITLE
Godot physics RigidBody size is overriden by the physics engine

### ISSUE THREAD

**Issue by japietru2004** [godotengine/godot#42973] opened 2020-10-21 18:52 UTC
**Godot version:**
3.2.3

**OS/device including version:**
Windows 10 - GLES3

**Issue description:**
Rigid bodies after changing physic engine from default to godot physics don't save size on application/game start - giant boxes appear.
(Additionally move and slide with kinematic characters seams buggy - I can fly normal but when I walk on some surface, I get stuck sometimes (In my game it is critical error - because I need to use constant_linear_velocity but it is not supported in default physics engine))

**Steps to reproduce:**
Change physics engine to godot physics.
Make rigid body - with collision box and mesh instance.
add Camera and some surface so box won't escape camera field of view
run project

**Minimal reproduction project:**
[Test.zip](https://github.com/godotengine/godot/files/5418142/Test.zip)

**Comment by rcorre** [comment] 2020-10-22 11:54
Looknig at the forum post, I see @TwistedTwigleg said:

> What is strange with this, in my opinion, is that jumping even works with this solution! I thought move_and_slide_with_snap made jumping hard because the snapping code would force the character to stick to the ground, but I guess this is not the case.

 I would have expected this as well. Are these docs no longer accurate? https://docs.godotengine.org/en/stable/classes/class_kinematicbody.html#class-kinematicbody-method-move-and-slide-with-snap:

> As long as the snap vector is in contact with the ground, the body will remain attached to the surface. This means you must disable snap in order to jump, for example. You can do this by setting snap to (0, 0, 0) or by using move_and_slide instead.

**Comment by japietru2004** [comment] 2020-10-22 12:37
Erm I meant rigid body does not save size + My player character is kinematic body when I use move_and_slide without snap. After I changed from default("bullet") physics engine to "godot physics" physics engine

**Comment by rcorre** [comment] 2020-10-22 12:46
Sorry, commented on the wrong issue :bow:

**Comment by japietru2004** [comment] 2020-10-22 12:48
ok, no problem @rcorre

**Comment by madmiraal** [comment] 2020-10-23 11:04
There is a warning in the editor notifying that this will happen:
![RigidBodySizeWarning](https://user-images.githubusercontent.com/9253928/96996234-69ed4f80-1527-11eb-9069-61a15a4aa0a6.png)

That been said, I'm not sure there is an open issue to address this in Godot physics; so I suggest keeping it open.

**Comment by madmiraal** [comment] 2020-10-23 11:10
> (Additionally move and slide with kinematic characters seams buggy - I can fly normal but when I walk on some surface, I get stuck sometimes (In my game it is critical error - because I need to use constant_linear_velocity but it is not supported in default physics engine))

Please only report one issue per issue report. Assuming it's not a duplicate of an existing issue, please open a separate issue for each issue you're experiencing.

**Comment by japietru2004** [comment] 2020-10-23 13:31
I tested it with changing size of collision shape and that seams right - above.

**Comment by pouleyKetchoupp** [comment] 2021-01-15 00:23
Closing as duplicate of #5734.

**Closed by pouleyKetchoupp** 2021-01-15 00:23 UTC
Labels: enhancement, topic:physics

**Comment by rascar-capac** [comment] 2024-02-20 22:27
https://github.com/godotengine/godot/issues/42973 👌
