### ISSUE TITLE
[3.5rc1] DOF Near Blur artifact

### ISSUE THREAD

**Issue by tinmanjuggernaut** [godotengine/godot#61165] opened 2022-05-18 18:24 UTC
### Godot version

3.5-rc1

### System information

Win 10/64 NVIDIA GeForce GTX 1060/PCIe/SSE2

### Issue description

DoF Near Blur has a rendering artifact.
It doesn't affect 3.5 beta 5. Far blur is unaffected.

![image](https://user-images.githubusercontent.com/632766/169117029-2019005c-ad78-4460-9934-42d9d05ee29a.png)

### Steps to reproduce

Look through a camera, enable DOF Near Blur, and adjust the distance. It's obvious.

### Minimal reproduction project

[neardof.zip](https://github.com/godotengine/godot/files/8719230/neardof.zip)

**Comment by clayjohn** [comment] 2022-05-18 18:27
Likely regression caused by https://github.com/godotengine/godot/pull/54585. Looking into it now.

**Comment by akien-mga** [comment] 2022-05-18 20:49
Fixed by #61171.

**Closed by akien-mga** 2022-05-18 20:49 UTC
Labels: bug, topic:rendering, confirmed, regression
