### ISSUE TITLE
text rendering can break with small font size and depending on the font

### ISSUE THREAD

**Issue by mieldepoche** [godotengine/godot#75316] opened 2023-03-25 11:07 UTC
### Godot version

4.0.1

### System information

linux

### Issue description

See the screenshot and mrp. As you can see just putting the text and using the provided kenney font, some of it is blurry. And this changes depending on like, the control size?

![image](https://user-images.githubusercontent.com/71937306/227713392-5f78b8c3-14d3-4a29-a39e-d68bb6fc5746.png)

it can also break in the middle of a line if you put the wrong character (→ in this case)
![image](https://user-images.githubusercontent.com/71937306/227714233-7e8c8754-6e94-4f4b-8dd5-60fe95fc5b26.png)

### Steps to reproduce

see mrp

### Minimal reproduction project

[blurryfont.zip](https://github.com/godotengine/godot/files/11068705/blurryfont.zip)

**Comment by Zireael07** [comment] 2023-03-25 11:31
duplicate of #74694

**Comment by YuriSizov** [comment] 2023-03-25 14:13
Thanks, seems like it is.

**Closed by YuriSizov** 2023-03-25 14:13 UTC
