### ISSUE TITLE
The slider in Area2D goes beyond the permitted area

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#31217] opened 2019-08-08 21:56 UTC
**Godot version:**
3.2.dev.custom_build. 765839b2a

**Issue description:**
![Screenshot_20190808_235043](https://user-images.githubusercontent.com/41945903/62740315-cace5c00-ba37-11e9-9e53-559ec405c362.png)

**Comment by akien-mga** [comment] 2019-08-09 06:53
Duplicate of #24191.

**Closed by akien-mga** 2019-08-09 06:53 UTC
Labels: bug, topic:core
