### ISSUE TITLE
Once shadows are enabled for OmniLight and Spotlight, cannot be disabled

### ISSUE THREAD

**Issue by jcostello** [godotengine/godot#64290] opened 2022-08-11 19:18 UTC
### Godot version

v4.0.alpha.custom_build [7355dfb50]

### System information

Ubuntu 21.04. RTX 2060

### Issue description

And a OmniLight or Spotlight and enabling shadows for any, it set the shadows enabled for ever

### Steps to reproduce

Add a SpotLight or OmniLight
Enable shadows
Disable shadows (shadows still enabled)

### Minimal reproduction project

I doesn't require a MRP since you have to add the light to reproduce

**Comment by Calinou** [comment] 2022-08-11 19:46
Duplicate of https://github.com/godotengine/godot/issues/50343.

**Closed by Calinou** 2022-08-11 19:46 UTC
