### ISSUE TITLE
Script Editor's 'Run' command key shortcut (ctrl+shift+X) is not working

### ISSUE THREAD

**Issue by bfishman** [godotengine/godot#21500] opened 2018-08-27 19:04 UTC
**Godot version:** 3.0.6 stable

**OS/device including version:**   Windows 10

**Issue description:**
Script Editor will run EditorScript from File -> run menu, but the keyboard shortcut for this (Control + Shift+ X) does nothing.

**Steps to reproduce:**
create a simple EditorScript
```
tool
extends EditorScript

func _run():
    print("Hello from the Godot Editor!")
```
Run it from the File -> run menu.  It runs.
Now press Control+Shift+X.  Nothing happens.

**Comment by tko** [comment] 2018-08-28 17:25
Looks like Control+Shift+X is assigned to two separate commands

https://github.com/godotengine/godot/blob/6f9416b2b6cff4272f69bbf0cff80f2b2c01de1b/editor/plugins/script_editor_plugin.cpp#L3044

https://github.com/godotengine/godot/blob/6f9416b2b6cff4272f69bbf0cff80f2b2c01de1b/editor/plugins/script_text_editor.cpp#L1559

**Comment by akien-mga** [comment] 2018-09-13 10:07
Duplicate of #19104.

**Closed by akien-mga** 2018-09-13 10:07 UTC
Labels: bug, junior job, topic:editor, usability
