### ISSUE TITLE
One_way_collision dont work if the platform is moving (regression) 

### ISSUE THREAD

**Issue by ni-code** [godotengine/godot#16170] opened 2018-01-30 01:46 UTC
**Godot version:**
godot3.0 stable release

**OS/device including version:**
arch linux

**Issue description:**
One_way_collision doesn't work if the platform is moving. It is a regression, It works fine in 2.1.4.

**Steps to reproduce:**
Open the attached project, and jump into the moving platform.
(arrow keys to move, space to jump)

I searched for similar issue in github, but didn't found anything related.

![on_way_bug_col](https://user-images.githubusercontent.com/10292929/35543870-557ec950-055f-11e8-9412-cd465a9e273d.gif)

[one_way_col_bug.zip](https://github.com/godotengine/godot/files/1675963/one_way_col_bug.zip)

**Comment by eon-s** [comment] 2018-02-01 19:51
Duplicate of #9399

**Closed** 2018-02-01 20:15 UTC
Labels: bug, topic:physics
