### ISSUE TITLE
Extreme Android slowdown when reading file content in scoped storage

### ISSUE THREAD

**Issue by ondesic** [godotengine/godot#63434] opened 2022-07-25 11:35 UTC
### Godot version

3.5 rc7

### System information

Windows 11

### Issue description

The previous bug with using "copy" dir in Scoped Storage was fixed in [62969](https://github.com/godotengine/godot/issues/62969).  However, accessing a file's content in Scoped Storage also has extreme slowdown.
I use `file.get_as_text()` here, but probably ALL functions that reads content, like `get_line`, need to be fixed.

Subsequently I also tested the "Write" function and "Make Directory", and they seem to have no slowdowns.  I hope Reading a file's content is the last hiccup. 

### Steps to reproduce

Make sure each time you install it, you allow and accept the two permissions, **THEN close and run again to now allow the loadtext.txt file to be copied to the file system (this should only need to be done once to get the test file created.)**

Once file is on device, press the "Read" button.  There will be a large slowdown before assigning the content of the file to the label.

### Minimal reproduction project

[StorageRead.zip](https://github.com/godotengine/godot/files/9180738/StorageRead.zip)

**Comment by m4gr3d** [comment] 2022-07-25 15:15
@ondesic Thanks for creating and reporting the issue. I was able to reproduce it and have identified the cause of the slowdown.

It's similar to the previous issue as in we're reading the file one byte at a time, which causes a significant overhead with the new scoped storage implementation as we're going through jni each time.

I'm working on a fix, but I'm also expanding your repro project to cover all the APIs exposed by `File` and `Directory` to ensure there are no other regressions.

@akien-mga The tests I'm using to troubleshoot may be useful to include in the recently discussed `godot-benchmarks` repo.
Are we looking at how to configure and support benchmarking on mobile devices?

**Comment by m4gr3d** [comment] 2022-07-26 07:31
@ondesic I expanded upon your repro project to validate the rest of the implementation to ensure we address all the remaining regressions.

[ScopedStorageTests.zip](https://github.com/godotengine/godot/files/9187560/ScopedStorageTests.zip)

**Comment by akien-mga** [comment] 2022-07-26 16:16
Fixed by #63480.

>[The tests I'm using to troubleshoot may be useful to include in the recently discussed godot-benchmarks repo.
Are we looking at how to configure and support benchmarking on mobile devices?

Yeah adding those tests to the benchmark repo makes sense! The current system we're setting up is desktop only but we can definitely look into how to run benchmarks on mobile eventually too.

**Closed by akien-mga** 2022-07-26 16:16 UTC
Labels: bug, platform:android, topic:porting, regression, performance

**Comment by ondesic** [comment] 2022-07-29 05:16
@m4gr3d With RC8 the files are reading fast, however, I have had a few crashes because "get_as_text()" now is reading the files different than before.  All "\n" newlines have been changed to "\r\n" with a carriage return followed by newline.  This introduced new crashes because original code is only looking for "\n", not "\r\n"

**Comment by m4gr3d** [comment] 2022-07-29 05:22
> @m4gr3d With RC8 the files are reading fast, however, I have had a few crashes because "get_as_text()" now is reading the files different than before. All "\n" newlines have been changed to "\r\n" with a carriage return followed by newline. This introduced new crashes because original code is only looking for "\n", not "\r\n"

@ondesic The new implementation is actually the correct one now. The previous logic was actively discarding the carriage return in content from the file, which is why you were not seeing them.
But it also means the content returned by the previous `get_as_text()` implementation was not matching the content in the file.
The new implementation loads the entire file in a buffer and returns it. So you're getting the file as it actually is.

**Comment by akien-mga** [comment] 2022-07-29 06:32
I think `get_as_text` is meant to parse the file as a Godot compatible string and that's using only `\n` for line breaks, so this should probably be fixed. Too bad we didn't have enough test coverage in `master` to catch this yet.

**Comment by m4gr3d** [comment] 2022-07-29 06:52
> I think `get_as_text` is meant to parse the file as a Godot compatible string and that's using only `\n` for line breaks, so this should probably be fixed. Too bad we didn't have enough test coverage in `master` to catch this yet.

Not sure I agree for a few reasons:
- The file content loaded in the buffer is successfully parsed as a utf8 string. If the carriage return wasn't supported, I'd expect the parsing to fail
- The converse of `get_as_text` is `store_string`. With the previous logic storing the string returned from `get_as_text` gives you a different file when it should be the same. The new logic fixes that behavior
- The new logic loads the entire file in a buffer. Scanning the buffer for carriage returns, removing them, then resizing the buffer would incur significant slowdowns
- The described crash seems to originate from the assumption of the game logic, not from Godot being unable to process the string

**Comment by ondesic** [comment] 2022-07-30 13:36
I see pros and cons to both views.  Here is an observation that favors the new line only.  Godot's nodes like RichTextEdit and TextEdit both receive and read text in this form "There once was a boy named Godot.\nHe was cool."  We currently have never used "\r\n" in these nodes.
There is a possibility of thousands of apps effected by this in which the developer is unaware of this change and this goes silently unnoticed until a user encounters crashes without realizing this subtle change.  The big app I tested this on has over 35k lines of code.  I would guess over 1000 lines of that code specifically use the "\n" character.

I don't know the right solution because I like having the true file format of "\r\n", but as I mentioned, Godot doesn't use this in any of their nodes.  I just need Godot to choose so I can either spend the hours and change my app code, or leave the code until the next RC release.

**Comment by m4gr3d** [comment] 2022-07-31 00:06
@ondesic Can you describe or reproduce the line of code that causes the crash.

I'm surprised a crash would be caused by an additional character, since the logic can just ignore the '\r' character and just parse the following newline character.

**Comment by m4gr3d** [comment] 2022-07-31 00:17
@ondesic Also to clarify Godot is not introducing additional character.
We just read the file and return its value raw. If the carriage return character is present, it means it was already in the file.

**Comment by ondesic** [comment] 2022-07-31 00:44
@m4gr3d Yes, Godot is not adding any characters.  
Previously Godot loaded/imported all text as a Unix (LF) type text.  With the new update, Godot is now reading all files raw.  If the file is using Windows (CRLF) format and logic is being used with the expected "\n" linefeed, unexpected results occur.  In my case the code was used to split a large file with the "\n" character as the delimiter.  For some reason the new Godot did not return the number of items usual returned from earlier versions and crashed.
As a time-consuming workaround, I went and opened over 20 text files needed for data and converted them to Unix format.

I'll have to go back and look at the code to tell you for sure, but it definitely did not play well with the "\r".

**Comment by akien-mga** [comment] 2022-07-31 10:34
I think that for `3.x` at least we should avoid breaking compat and just do `.replace("\r", "")` on the result (which is what `get_line()` does, it skips `\r` explicitly).
