### ISSUE TITLE
Issue with emission property of mesh materials

### ISSUE THREAD

**Issue by Eorlanas** [godotengine/godot#71009] opened 2023-01-06 22:51 UTC
### Godot version

v4.0.beta6.official

### System information

Windows 10, AMD Radeon 6900 XT, 

### Issue description

I'm not 100% sure that this is a bug, but it certainly feels like one and the godot discord seems to agree. Essentially, the emission propriety seems to have difficulties with thinner meshes (or at least, that seems to be what triggers the issue). 
![image](https://user-images.githubusercontent.com/114264403/211112212-cdf45fae-2766-4b82-8fca-c206a8a7e2ae.png)
In this picture, the red rectangles to the right have the same material options as the one to the left, but the one on the left gives off a lot less light compared to it. The issue is lessened when moving the camera close to the object, but it remains still, and the behavior appears to be the same from editor to runtime.

### Steps to reproduce

Take mesh "a" (in the project below, they're the "green" meshes), drive its emission to max, do the same to any of the other meshes, and compare.

### Minimal reproduction project

https://drive.google.com/file/d/1DyvWJuHTwUIXYjRMt11AJW2akNGhsNFK/view?usp=sharing

**Comment by clayjohn** [comment] 2023-01-07 00:07
Duplicate of https://github.com/godotengine/godot/issues/56452

**Closed by clayjohn** 2023-01-07 00:07 UTC
