### ISSUE TITLE
Undo-Redo will crash on a missing object.

### ISSUE THREAD

**Issue by jagt** [godotengine/godot#11785] opened 2017-10-02 17:41 UTC
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Activated GL 3.3 contextOpenGL ES 3.0 Renderer: GeForce GTX 1080 Ti/PCIe/SSE2 git @ 36298186f

**Issue description:**
When `UndoRedo::_process_operation_list()` encounters a corrupt objects, it will crash the editor.

**Steps to reproduce:**
Randomly doing undo and resizing array inspector will likely to reproduce this issue.
Stacktrace pasted below.

```
ERROR: UndoRedo::_process_operation_list: Condition ' !obj ' is true.
   At: core\undo_redo.cpp:264
ERROR: Vector<struct UndoRedo::Action>::operator []: FATAL: Index p_index out of size (size()).
   At: c:\dev1\gamedev\repos\godot\core\vector.h:137
CrashHandlerException: Program crashed
Dumping the backtrace. Please include this when reporting the bug on https://github.com/godotengine/godot/issues
[0] Vector<UndoRedo::Action>::operator[] (c:\dev1\gamedev\repos\godot\core\vector.h:137)
[1] UndoRedo::_discard_redo (c:\dev1\gamedev\repos\godot\core\undo_redo.cpp:41)
[2] UndoRedo::create_action (c:\dev1\gamedev\repos\godot\core\undo_redo.cpp:65)
[3] ArrayPropertyEdit::_set (c:\dev1\gamedev\repos\godot\editor\array_property_edit.cpp:144)
[4] ArrayPropertyEdit::_setv (c:\dev1\gamedev\repos\godot\editor\array_property_edit.h:37)
[5] Object::set (c:\dev1\gamedev\repos\godot\core\object.cpp:454)
[6] PropertyEditor::_edit_set (c:\dev1\gamedev\repos\godot\editor\property_editor.cpp:3585)
[7] PropertyEditor::_item_edited (c:\dev1\gamedev\repos\godot\editor\property_editor.cpp:3694)
[8] MethodBind0<PropertyEditor>::call (c:\dev1\gamedev\repos\godot\core\method_bind.gen.inc:139)
[9] Object::call (c:\dev1\gamedev\repos\godot\core\object.cpp:839)
[10] MessageQueue::_call_function (c:\dev1\gamedev\repos\godot\core\message_queue.cpp:259)
[11] MessageQueue::flush (c:\dev1\gamedev\repos\godot\core\message_queue.cpp:306)
[12] SceneTree::iteration (c:\dev1\gamedev\repos\godot\scene\main\scene_tree.cpp:457)
[13] Main::iteration (c:\dev1\gamedev\repos\godot\main\main.cpp:1630)
[14] OS_Windows::run (c:\dev1\gamedev\repos\godot\platform\windows\os_windows.cpp:2263)
[15] widechar_main (c:\dev1\gamedev\repos\godot\platform\windows\godot_win.cpp:149)
[16] _main (c:\dev1\gamedev\repos\godot\platform\windows\godot_win.cpp:171)
[17] main (c:\dev1\gamedev\repos\godot\platform\windows\godot_win.cpp:183)
[18] __scrt_common_main_seh (f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:253)
[19] BaseThreadInitThunk
-- END OF BACKTRACE --
```

**Link to minimal example project:**
None

**Comment by Geequlim** [comment] 2018-01-07 10:58
Does this problem still avaliabe? I can't reproduct it with the master.

**Comment by akien-mga** [comment] 2018-01-08 10:21
That error:
```
ERROR: UndoRedo::_process_operation_list: Condition ' !obj ' is true.
   At: core\undo_redo.cpp:264
```
Comes from here, and confirms that something fishy is happening.
https://github.com/godotengine/godot/blob/a6e0dcdcbfe90905bf34007a3d1387a48e1ed5b9/core/undo_redo.cpp#L267-L272

I'd suggest to add `current_action = -1` to https://github.com/godotengine/godot/blob/a6e0dcdcbfe90905bf34007a3d1387a48e1ed5b9/core/undo_redo.cpp#L267-L272 (as well as adding the index check mentioned above, which could be of the form `ERR_FAIL_COND((current_action + 1) >= actions.size());` for consistency with existing code.

**Comment by akien-mga** [comment] 2018-01-16 10:26
Not critical for the upcoming 3.0 release, so moving to the next milestone. A fix can still be cherry-picked for 3.0.x maintenance releases once available in the master branch.

**Comment by reduz** [comment] 2018-09-05 21:19
Any progress on this?

**Comment by DualMatrix** [comment] 2018-09-17 15:18
I could not reproduce this in master but I'm not sure I'm doing it right. Is there a better way to reproduce this crash?

**Comment by akien-mga** [comment] 2019-01-19 10:55
Can anyone reproduce this issue? If so, how?

**Comment by Anutrix** [comment] 2019-07-03 05:45
Can anyone reproduce this now?

**Comment by akien-mga** [comment] 2019-07-03 05:50
I'll assume this fixed for now. If anyone can reproduce it, please comment and we'll reopen.

**Closed by akien-mga** 2019-07-03 05:50 UTC
Labels: bug, hero wanted!, topic:editor
