### ISSUE TITLE
NavigationAgent3D crashes game if a path to target is not possible

### ISSUE THREAD

**Issue by rustwork** [godotengine/godot#67343] opened 2022-10-13 09:19 UTC
### Godot version

4.0 Beta 2

### System information

Windows 10, Vulkan, Nvidia RTX 3060 Ti

### Issue description

If the NavigationAgent3D tries to even check if a target is reachable, the game crashes with the log entry:
`USER ERROR: Index p_index = 43 is out of bounds (count = 1)`

[godot.log](https://github.com/godotengine/godot/files/9774788/godot.log)

NOTE: This seems to have been broken with Beta 2, testing it in Beta 1 works fine. In Beta 1 if no path can be found, the agent simply doesn't move because it can test if the target is reachable.

![NavigationBug](https://user-images.githubusercontent.com/2095704/195552669-5939b6f1-6019-402d-9527-1edb28917e81.jpg)

### Steps to reproduce

- Create a simple scene with an agent, target and obstacles
- Put the target object in a spot that is cut off completely from the agent by obstacles
- in the agent's script set the agent's target with the `set_target_location` function
- in the agent's script check if the target is reachable with the `navAgent.is_target_reachable()` function
- run the game
- crash

### Minimal reproduction project

The project contains a scene with a simple script attached to the green agent which tries to navigate to the pink target as soon as the game is launched. 

Simply run the project to have the game immediately crash after launch.

Note: If you move one of the long obstacles out of the way to clear the path and bake the navmesh, then the navigation works and the green agent moves to the target.

[NavBug.zip](https://github.com/godotengine/godot/files/9774924/NavBug.zip)

**Comment by Zireael07** [comment] 2022-10-13 09:53
Duplicate of #66783 fixed in #66784

I think the fix will be in the next beta

**Closed** 2022-10-13 09:59 UTC
