### ISSUE TITLE
Q and W hotkeys not working for GridMap

### ISSUE THREAD

**Issue by blackears** [godotengine/godot#74900] opened 2023-03-14 11:01 UTC
### Godot version

v4.0.stable.official [92bee43ad]

### System information

Windows 10

### Issue description

Trying to use the GridMap in Godot 4.  The hotkeys Q and E which raise and lower the floor do not seem to be functional.  

### Steps to reproduce

Create a new 3D scene and add a GripMap to it.  
Draw some tiles in the map. 
Press Q and E keys to adjust the floor height.  
Observe the floor height does not change,

### Minimal reproduction project

[SilverBall.zip](https://github.com/godotengine/godot/files/10967537/SilverBall.zip)

**Comment by blackears** [comment] 2023-03-14 17:34
They worked in Godot 3, so this is a regression at least.  They also look like shortcuts in the drop down menu, so if they aren't those short cut indicators should be removed.

**Comment by jkulawik** [comment] 2023-04-06 21:24
Cursor Clear Rotation (W) does not work too

**Comment by Calinou** [comment] 2023-04-06 23:45
- Duplicate of https://github.com/godotengine/godot/issues/71916.

**Closed by Calinou** 2023-04-06 23:45 UTC
Labels: bug, topic:editor, usability, regression, topic:3d
