### ISSUE TITLE
Vulkan: depth_prepass_alpha shaders don't discard 0 alpha parts

### ISSUE THREAD

**Issue by Arnklit** [godotengine/godot#59015] opened 2022-03-11 08:59 UTC
### Godot version

4.0.alpha4

### System information

Windows 10, GLES3, GTX 980Ti

### Issue description

Shouldn't Godot discard no alpha parts of a material automatically?

Currently it doesn't and it comes at a big performance cost for no benefit as far as I can see.

Shader Example:
```
shader_type spatial;
render_mode depth_draw_opaque, cull_disabled, depth_prepass_alpha;
uniform vec4 albedo : hint_color;
uniform sampler2D texture_albedo : hint_albedo,filter_linear_mipmap,repeat_enable;

void fragment() {
	vec4 albedo_tex = texture(texture_albedo, UV);
	ALBEDO = albedo.rgb * albedo_tex.rgb;
	ALPHA *= albedo.a * albedo_tex.a;
}
```

This shader on a few planes of grass close to the camera tanks performance:

![image](https://user-images.githubusercontent.com/4955051/157834391-038b2a20-0a08-4fbe-b571-2468b8bf36f5.png)

Add this to the end of the fragment shader:

```
if (ALPHA == 0.00)
	discard;
```

And performance improves a lot:

![image](https://user-images.githubusercontent.com/4955051/157834641-68d1a548-3341-45b3-89ee-574c9f2995b5.png)

Shouldn't this happen automatically?

### Steps to reproduce

Open the attached project.

### Minimal reproduction project

[TransparencyTests.zip](https://github.com/godotengine/godot/files/8230510/TransparencyTests.zip)

**Comment by lewiji** [comment] 2022-03-13 00:50
I've been porting a Godot 3 project to 4 which uses a lot of 3d-in-2d things - mostly flat geometry (planes or quads), and AnimatedSprite3D for animations. Couldn't get reflections working with the sprites, not with SSR, nor SDFGI.

Set up the test scene shown in the attached video, and yeah, if I make a shader which ever sets ALPHA (even to 1.0), I get no reflections or shadows with any depth draw mode, even with discarding or alpha scissor. 

If I never set ALPHA at all, and manually discard pixels by sampling the *texture* rather than the ALPHA as above, it works for both reflections and shadows:

```
if (albedo_tex.a == 0.0)
        discard;
```

https://user-images.githubusercontent.com/233380/158039916-de76542f-3006-4221-9f4a-a208f57c1b69.mp4

Interestingly, if I set up a StandardMaterial with alpha scissor enabled (which I also expected would discard the pixels like this), and convert it to a shader in the right click menu of the material, it adds the line:

`ALPHA *= albedo.a * albedo_tex.a;`

before setting alpha scissor. If I remove that line, or change it to `ALPHA = 1.0`, then the alpha scissor does nothing, no pixels get discarded, and you get no shadows or reflections.

**Comment by clayjohn** [comment] 2022-03-14 04:46
> Shouldn't this happen automatically?

I need to double check, but I think discard breaks the calculation of pixel derivatives (as the GPU relies on neighbouring pixels). So this optimization may only be helpful for simple objects. Not that I am downplaying its benefit, it seems really helpful for vegetation like grass and bushes and stuff.

**Comment by lewiji** [comment] 2022-03-14 09:24
>  pixel derivatives

What would be the impact of losing these? Would they only be lost for the discarded fragments (and/or their original neighbours)? 

It seems that there is currently no option in a StandardMaterial3D to get proper reflections with a texture that has transparency in some form, and at least in the screen space reflections generated by setting prepass alpha mode, most of the colour pixel data is lost (rendering a greyish blob as the reflection), whereas doing the manual discard "optimisation" in a shader gives full colour, full depth reflections. 

So it would seem to me that, at least for reflections/sdfgi, *more* pixel data is retained/available when doing the discard optimisation vs any of the options currently available in the StandardMaterial3D. But I suppose these effects may not rely on these pixel derivatives.

I think part of the issue vs 3.x is that alpha scissor and depth prepass are now bundled under one option in godot 4's StandardMaterial3D, but for cases such as these, both options are wanted - scissoring alpha and rendering in opaque mode, while also doing alpha prepass.

The thing I don't quite get is why setting ALPHA in the shader to 1.0, using opaque depth mode, discarding transparent fragments, and using depth prepass doesn't seem to give any reflection at all, as if the depth isn't being calculated - until you remove the assignment to ALPHA, which it seems the StandardMaterial3D will always do.

**Comment by clayjohn** [comment] 2022-11-13 21:59
Thinking more about this potential optimization. It works well in this situation because the texture is essentially a flat colour. But in more complex scenarios the improper pixel derivatives will create visible artifacts at the edge of the visible texture caused by a failure to calculate the proper mipmap. 

For something like a built-in vegetation shader you would handle this by adding a discard clause like in the OP, but you would also switch to using either manual LOD, or manually calculate LOD yourself. 

The other big downside is that discard disables the early-z depth test and totally messes with TBDR optimizations in mobile GPUs. In a simple example the impact would not be visible, but on a more complex project (where you actually benefit from depth-testing) this would be detrimental to performance (of course, this depends on shader complexity).

The "proper" solution here is to actually not use quads for the grass, but create a simple mesh that roughly follows the contours of the texture so that you minimize pixel overdraw, but can leave the shader itself alone. 

I'm closing for now as this is a performance optimization that I do not think is worth making. I hope the discussion is interesting and helpful for users down the road though!

**Closed by clayjohn** 2022-11-13 21:59 UTC
Labels: discussion, topic:rendering, topic:shaders, topic:3d
