### ISSUE TITLE
Editor crashes when switching to new [empty] scene tab

### ISSUE THREAD

**Issue by dorjoosoft** [godotengine/godot#62058] opened 2022-06-15 04:03 UTC
### Godot version

Godot_v4.0-alpha9_win64

### System information

Windows 10 and ubuntu 20.4 LTS, Intel(R) HD Graphics 530, both Vulkan and OpenGL rendering drivers tested

### Issue description

Editor crashes after click tab of switching to new scene.

**Godot start log from windows power shell is:**
```
PS E:\GD\Godot_v4.0-alpha9_win64> ./godot.exe
Godot Engine v4.0.alpha9.official.fc18891db - https://godotengine.org
Vulkan API 1.2.176 - Using Vulkan Device #0: Intel - Intel(R) HD Graphics 530

Editing project: E:/GD/ngp2 (E:::GD::ngp2)

Godot Engine v4.0.alpha9.official.fc18891db - https://godotengine.org
ERROR: Condition "!windows.has(p_window)" is true.
   at: window_resize (drivers/vulkan/vulkan_context.cpp:1404)
Vulkan API 1.2.176 - Using Vulkan Device #0: Intel - Intel(R) HD Graphics 530

ERROR: Used ED_GET_SHORTCUT with invalid shortcut: canvas_item_editor/zoom_100_percent.
   at: (editor/editor_settings.cpp:1459)
WARNING: FBX file import is enabled, but no FBX2glTF path is configured. FBX files will not be imported.
     at: _editor_init (modules/gltf/register_types.cpp:92)

```

### Steps to reproduce

1. Create a new test project
2. Create a scene and add a node2d
3. Save the scene
4. Create another [empty] scene and left it empty.
5. Try to switch between them two or three times **before adding anything to new [empty] scene**
6. Editor freezes and crashes

Note: After adding a single node to new empty scene switching between them working without any problem for me!

### Minimal reproduction project

[ngp2.zip](https://github.com/godotengine/godot/files/8905645/ngp2.zip)

**Comment by dorjoosoft** [comment] 2022-06-15 04:06
Minimal reproduction project
[ngp2.zip](https://github.com/godotengine/godot/files/8905558/ngp2.zip)
Sorry! I forgot to attach project on it's place!

**Comment by akien-mga** [comment] 2022-06-15 05:46
Duplicate of https://github.com/godotengine/godot/issues/61654

**Closed by akien-mga** 2022-06-15 05:46 UTC
