### ISSUE TITLE
Clicking on StyleBox Texture collapses Theme rather than expanding Style Box Texture

### ISSUE THREAD

**Issue by Feniks-Gaming** [godotengine/godot#32439] opened 2019-09-30 09:39 UTC
**Godot version:3.1

**OS/device including version: Windows 10 

**Issue description:

When working with theme I have Button that I want to add theme to I add StyleBoxTexture
![1](https://user-images.githubusercontent.com/30668026/65866759-4a5c1580-e36d-11e9-94ac-bc8e75e3f53c.PNG)

I then click on StyleBoxTexture in order to expand it and rather than expand it whole theme collapses to this 
![2](https://user-images.githubusercontent.com/30668026/65866899-81322b80-e36d-11e9-9ac2-6e79f64ccb65.PNG)

I have tried closing and reopening a scene i have Tried saving and closing Godot editor but still no change. 

**Steps to reproduce:**

As above. There is a way around it if You first select New StyleBox Empty and expand it and then change it to StyleBox Texture it will remain expanded as expected. 
![3](https://user-images.githubusercontent.com/30668026/65867498-7330da80-e36e-11e9-8456-bd0588247167.PNG)

**Minimal reproduction project:**

N/A

**Comment by KoBeWi** [comment] 2019-09-30 10:13
Duplicate of #29873

**Closed by KoBeWi** 2019-09-30 10:13 UTC
