### ISSUE TITLE
Godot4.0.2 import glb file too slow

### ISSUE THREAD

**Issue by FrankLeeC** [godotengine/godot#77203] opened 2023-05-18 13:26 UTC
### Godot version

4.0.2.stable

### System information

Windows 11, CPU: 1th Gen Intel Core i7-11700F,  Renderer: Forward+, GPU: NVIDIA GeForce RTX 3060

### Issue description

Version: Godot4.0.2.stable
importing .glb file too slow, cost at least 3minutes. however using 3.5.x version is very fast.
![import](https://github.com/godotengine/godot/assets/16380650/cc393c07-59b8-4b37-b72d-c79174d8b233)

### Steps to reproduce

1.create a new project
2.create a floder named "t1"
3.drap s22.glb file to floder "t1"

### Minimal reproduction project

[test1.zip](https://github.com/godotengine/godot/files/11508111/test1.zip)

**Comment by AThousandShips** [comment] 2023-05-18 13:31
> however using 3.5.x version is very fast.

How long does it take? To give an idea of the slowdown

**Comment by FrankLeeC** [comment] 2023-05-18 13:41
> 

3.5.1.stable cost about 2 seconds.

**Comment by FrankLeeC** [comment] 2023-05-18 13:41
> > however using 3.5.x version is very fast.
> 
> How long does it take? To give an idea of the slowdown
3.5.1.stable cost about 2 seconds.

**Comment by FrankLeeC** [comment] 2023-05-18 13:42
> > however using 3.5.x version is very fast.
> 
> How long does it take? To give an idea of the slowdown

3.5.1.stable cost about 2 seconds.

**Comment by AThousandShips** [comment] 2023-05-18 13:48
Cannot replicate on latest version, debug build, it takes no longer than 10 seconds (didn't measure exactly)

Can you test with the latest [release candidate](https://godotengine.org/article/release-candidate-godot-4-0-3-rc-2/)?

**Comment by FrankLeeC** [comment] 2023-05-18 14:07
> Cannot replicate on latest version, debug build, it takes no longer than 10 seconds (didn't measure exactly, but nowhere near 3 minutes), I'm running AMD so could be NVIDIA related if it persists
> 
> Can you test with the latest [release candidate](https://godotengine.org/article/release-candidate-godot-4-0-3-rc-2/) or latest [snapshot](https://godotengine.org/article/dev-snapshot-godot-4-1-dev-2/)?

both 4.0.3 RC 2 & 4.1-dev2 take 3~4 minutes.

by the way, console error log of 4.1-dev2


![console_error](https://github.com/godotengine/godot/assets/16380650/d3601ddc-ab97-43cd-a1c4-93a5c6a85632)

**Comment by AThousandShips** [comment] 2023-05-18 14:09
That was fixed by #76910 but thank you for pointing out!

**Comment by AThousandShips** [comment] 2023-05-18 14:21
Could we get some testing from other people with AMD and Intel/NVIDIA hardware to see if there's a pattern there, could be any number of factors on my end but that is one potentially big one, NVIDIA in #64751 as well

**Comment by smix8** [comment] 2023-05-18 18:47
What makes it so slow is the Embree BVH Intersector, it consumes 98% of the entire processing time.

**Comment by Calinou** [comment] 2023-05-21 22:50
> What makes it so slow is the Embree BVH Intersector, it consumes 98% of the entire processing time.

This is due to LOD generation, which calls Embree to improve its quality.

- Duplicate of https://github.com/godotengine/godot/issues/64751 (same cause).

**Closed by Calinou** 2023-05-21 22:50 UTC
