### ISSUE TITLE
Empty tooltips for display/window/stretch/* property settings

### ISSUE THREAD

**Issue by CitrusWire** [godotengine/godot#42481] opened 2020-10-01 20:54 UTC
3.2.3
(This may be a docs bug?)

Project Settings -> Display / Window - at the bottom there's "Stretch". It has three settings:
Mode, Aspect, Shrink.
These properties:
display/window/stretch/mode
display/window/stretch/aspect
display/window/stretch/shrink

None of these have tooltip text. The tooltip box for all three is empty apart from the property name.

(I don't know how you're doing tooltips behind the scenes, but generally this seems like a good thing for a unit-test to catch: that all properties have tooltips).

**Comment by Calinou** [comment] 2020-10-01 21:08
> (I don't know how you're doing tooltips behind the scenes, but generally this seems like a good thing for a unit-test to catch: that all properties have tooltips).

We have a documentation coverage checker script for that: https://github.com/godotengine/godot/blob/master/doc/tools/makerst.py

See https://godotengine.github.io/doc-status/ for HTML-formatted output.

**Comment by CitrusWire** [comment] 2020-10-01 21:10
> We have a documentation coverage checker script for that: https://github.com/godotengine/godot/blob/master/doc/tools/makerst.py
Great minds think alike. ;-)

**Comment by Calinou** [comment] 2020-10-01 21:57
It seems this is caused by the stretch mode settings not being part of the generated [`ProjectSettings.xml`](https://github.com/godotengine/godot/blob/master/doc/classes/ProjectSettings.xml). To fix this, the settings in question need to have their default values declared elsewhere.

**Comment by EricEzaM** [comment] 2020-10-01 22:02
Yep, there are many places where this happens. See some discussion and my 'investigation' at https://github.com/godotengine/godot-proposals/issues/1339

**Comment by Ybaedbaenn** [comment] 2023-07-13 17:38
The issue is still relevant in Godot version 4.1, for example:
- threading/worker_pool/use_system_threads_for_low_priority_tasks
- threading/worker_pool/low_priority_thread_ratio

Have got empty tooltips in the editor.

**Comment by Calinou** [comment] 2023-07-13 18:08
This was fixed by https://github.com/godotengine/godot/pull/76272, closing.

> The issue is still relevant in Godot version 4.1, for example:
> 
>     * threading/worker_pool/use_system_threads_for_low_priority_tasks
> 
>     * threading/worker_pool/low_priority_thread_ratio
> 
> 
> Have got empty tooltips in the editor.

This is because these project settings don't have any descriptions. They *are* correctly generated in `doc/classes/ProjectSettings.xml`, so this is not a bug but missing documentation.

@RandomShaper Could you open a PR to document those two project settings (and describe why you'd want to adjust them, specifically)? Thanks in advance :slightly_smiling_face:

**Closed by Calinou** 2023-07-13 18:08 UTC
Labels: bug, topic:core, documentation

**Comment by Ybaedbaenn** [comment] 2023-07-13 19:18
- gui/fonts/dynamic_fonts/use_oversampling
- rendering/shader_compiler/shader_cache/compress
- rendering/shader_compiler/shader_cache/use_zstd_compression
- rendering/shader_compiler/shader_cache/strip_debug
- rendering/shader_compiler/shader_cache/strip_debug.release
- rendering/limits/time/time_rollover_secs
- rendering/limits/global_shader_variables/buffer_size
- rendering/limits/spatial_indexer/update_iterations_per_frame
- rendering/limits/spatial_indexer/threaded_cull_minimum_instances
- rendering/limits/forward_renderer/threaded_render_minimum_instances
- rendering/rendering_device/staging_buffer/block_size_kb
- rendering/rendering_device/staging_buffer/max_size_mb
- rendering/rendering_device/staging_buffer/texture_upload_region_size_px
- rendering/rendering_device/vulkan/max_descriptors_per_pool
- editor/version_control/plugin_name
- editor/version_control/autoload_on_startup
- editor/import/reimport_missing_imported_files

also don't have tooltips

**Comment by Ybaedbaenn** [comment] 2023-07-13 19:19
Since I've checked them by hand something may be missing from the list.
Should I open a new issue, and post the list there?
