### ISSUE TITLE
WorldEnviorment: When background is set to canvas, any description or pop-up shows up as empty

### ISSUE THREAD

**Issue by DaZelC77** [godotengine/godot#68000] opened 2022-10-29 03:04 UTC
### Godot version

v4.0.beta3.official [01ae26d31]

### System information

Windows 11

### Issue description

If a WorldEnviorment node is added to a scene, and the background setting is set to canvas, any pop up in the editor becomes blank. Any buttons that would come up still are functional (for example, a pop up that has the option to save and quit still functions), but they are not visible. 

![image](https://user-images.githubusercontent.com/96361809/198792783-a719e60b-1edc-49a6-bcb2-e3bb58453c9e.png)

![image](https://user-images.githubusercontent.com/96361809/198793197-a63f20ff-f2e8-4f80-9278-fb8940b4e5cb.png)

### Steps to reproduce

1.  Make a new project file
2.  Add a WorldEnviorment Node
3.  Change the background setting to Canvas
4.  Hover over something in the editor to check the pop-up

**Comment by alexamy** [comment] 2022-10-29 22:33
Minimal reproduction project:
[bug_blank_canvas.zip](https://github.com/godotengine/godot/files/9894696/bug_blank_canvas.zip)

**Comment by Calinou** [comment] 2022-10-29 22:44
Duplicate of https://github.com/godotengine/godot/issues/52467.

**Closed by Calinou** 2022-10-29 22:44 UTC
