### ISSUE TITLE
global_script_class_cache.cfg saves deleted plugins

### ISSUE THREAD

**Issue by M3CK4** [godotengine/godot#79752] opened 2023-07-21 17:00 UTC
### Godot version

4.1

### System information

Godot v4.1.stable - Windows 10.0.19045 - Vulkan (Forward+) - dedicated GeForce GT 740M () - Intel(R) Core(TM) i5-3337U CPU @ 1.80GHz

### Issue description

When I start the project and start the main scene, I get errors from plugins that I tried using earlier for terrain, like Terrain, Godot-MTerrain, TerrainPlugin. They exist in the global_script_class_cache.cfg but I don't have the files from those plugins and when I start the game I get errors that the path couldn't be found and if I try to delete the list where that path is stored it just comes back when I start the scene.

### Steps to reproduce

Install one of the Terrain Plugins: Godot-MTerrain, TerrainPlugin or Terrain.
Click on enable in the plugin manager.
If the enable isn't working delete the plugin folder.
And the errors come.

### Minimal reproduction project

[project.zip](https://github.com/godotengine/godot/files/12130801/project.zip)

**Comment by dalexeev** [comment] 2023-07-22 17:15
* Looks like a duplicate of #78642:

> This class existed for some manual testing, but has been deleted for some time.
> A restart of the editor do not fix the `.godot/global_script_class_cache.cfg`

I guess it doesn't matter if the deleted script belongs to a plugin or not.

**Closed by dalexeev** 2023-07-22 17:15 UTC
