### ISSUE TITLE
Named class in addons folder doesn't show in Create New Node dialog

### ISSUE THREAD

**Issue by 37Rb** [godotengine/godot#74403] opened 2023-03-04 23:29 UTC
### Godot version

4.0.stable

### System information

OSX Ventura 13.1

### Issue description

I created a node class that extends CharacterBody2D and would like to share it in the asset library. So I moved the script to the addons folder to test it. When it was in my project directly (not under addons) it would show up in the "Create New Node" dialog under CharacterBody2D. When I move it to addons it no longer shows up as an option when creating a new node. So if I share it in the asset library it won't work for others.

In the documentation it says you don't have to make an editor plugin for this.

https://docs.godotengine.org/en/4.0/tutorials/plugins/editor/making_plugins.html#a-custom-node

> Nodes added via an EditorPlugin are "CustomType" nodes. While they work with any scripting language, they have fewer features than the Script Class system. If you are writing GDScript or NativeScript, we recommend using Script Classes instead.

The docs say it should "appear with its new icon in the editor".

https://docs.godotengine.org/en/4.0/tutorials/scripting/gdscript/gdscript_basics.html#registering-named-classes

> You can give your class a name to register it as a new type in Godot's editor. For that, you use the class_name keyword. You can optionally use the @icon annotation with a path to an image, to use it as an icon. **Your class will then appear with its new icon in the editor:**

Here's the repo but I'll wait until this is resolved before I submit it to the asset library.

https://github.com/37Rb/godot-overhead-car-2d

### Steps to reproduce

1. Create a named class that extends a node class but put the file in the addons folder.
2. Try to create a new node of your named class type with the Create New Node dialog.

### Minimal reproduction project

[AddonsSubclassTest.zip](https://github.com/godotengine/godot/files/10889867/AddonsSubclassTest.zip)

Notice that the class in file addons/in_addons_subclass.gd doesn't show in the Create New Node dialog.

**Comment by KoBeWi** [comment] 2023-03-05 00:55
Duplicate of #30048

**Closed by KoBeWi** 2023-03-05 00:55 UTC

**Comment by 37Rb** [comment] 2023-03-05 02:51
I see. So then I guess I can't share a custom node with others in a useful way unless I make it a plugin. I recommend changing how [this warning](https://docs.godotengine.org/en/4.0/tutorials/plugins/editor/making_plugins.html#a-custom-node) is written.

> Nodes added via an EditorPlugin are "CustomType" nodes. While they work with any scripting language, they have fewer features than [the Script Class system](https://docs.godotengine.org/en/4.0/tutorials/scripting/gdscript/gdscript_basics.html#doc-gdscript-basics-class-name). If you are writing GDScript or NativeScript, we recommend using Script Classes instead.

I started out reading that doc section to make a custom node as a plugin but that warning threw me off and made me think I didn't need a plugin, and even that it was not recommended because I should use the Script Classes instead. It turns out I should use script classes but I still have to make a plugin to share it.

**Comment by KoBeWi** [comment] 2023-03-05 18:58
You don't need a plugin, just share the script. The class name is global, so it doesn't matter where the script is located.

**Comment by 37Rb** [comment] 2023-03-05 20:59
Share it how? People probably won't find it unless it's in the asset library. It has to be an add-on to be in the asset library. It has to be in the addons folder to be an add-on. If I put it in the addons folder then the editor won't scan for it unless it's a plugin and the plugin is enabled. So unless I'm misunderstanding something then it has to be a plugin in order to be shared in the asset library. Right?

**Comment by KoBeWi** [comment] 2023-03-05 21:04
No, you don't need "addon" to submit it to AssetLib. It can be a simple script.

Example:
https://github.com/KoBeWi/Godot-Frame-Converter
https://godotengine.org/asset-library/asset/426
Downloads as one `.gd` file.

**Comment by 37Rb** [comment] 2023-03-06 01:07
Ahhh that helps. I thought you had to make either an Addon or a Project to publish in the asset library. In [the documentation](https://docs.godotengine.org/en/stable/community/asset_library/submitting_to_assetlib.html) it says:

> The category that your asset belongs to, and will be shown in search results. The category is split into Addons and Projects. In-editor, assets of the Project type (Templates, Demos, Projects) only show up when viewing the AssetLib from the Project Manager, while assets of the Addon type will only be visible from inside a project.

Then when you go to submit an asset the two main categories are Addons and Projects, and Scripts is under Addons.

<img width="1100" alt="Screenshot 2023-03-05 at 6 59 55 PM" src="https://user-images.githubusercontent.com/82692355/222997533-7177df6d-8bb0-4046-ae16-031d13e895aa.png">

So I assumed it had to be one or the other. I'm probably not the only one to interpret it that way. It could help to change the wording and to not put Scripts as a subcategory under Addons in the asset library.

But at least I understand it now. I'll submit mine as script that's not an addon.
