### ISSUE TITLE
KinematicBody get_floor_velocity() inconsistent result in 3.4beta

### ISSUE THREAD

**Issue by babypandabear3** [godotengine/godot#52484] opened 2021-09-08 06:23 UTC
### Godot version

3.4 Beta 3

### System information

Windows 10, NVIDIA GTX 750TI, GLES3

### Issue description

when doing moving and rotating platform by adding get_floor_velocity to velocity, returned values difference breaks either moving or rotating platform depend if times with delta or not. It works correctly in 3.3.3

in Godot 3.4 Beta 3
moving platform : velocity + get_floor_velocity() * delta
rotating platform : velocity + get_floor_velocity()

in Godot 3.3.3 both platforms works with 
velocity + get_floor_velocity() * delta

### Steps to reproduce

Create 2 platform, for moving and rotating platform. Animate them using animation player
Make kinematicbody with script
put both kinematic body on top of platform

`extends KinematicBody

var velocity = Vector3()

# Called when the node enters the scene tree for the first time.
func _ready():
	pass # Replace with function body.

func _physics_process(delta):
	if is_on_floor():
		
		velocity = (Vector3.DOWN * 0.1) + (get_floor_velocity() * delta)
		#TO MAkE ROTATING PLATFORM WORK, REPLACE WITH
		#velocity = (Vector3.DOWN * 0.1) + (get_floor_velocity())
		#BUT THEN MOVING PLATFORM WILL BREAK
	else:
		velocity = Vector3.DOWN
		
	var _vel = move_and_slide(velocity, Vector3.UP)`

### Minimal reproduction project

[br_get_floor_velocity.zip](https://github.com/godotengine/godot/files/7126379/br_get_floor_velocity.zip)

In 3.4 Beta 3 kinematic body failed to follow rotating platform

In 3.3.3 it works fine

**Comment by Calinou** [comment] 2021-09-08 12:33
cc @pouleyKetchoupp

**Comment by pouleyKetchoupp** [comment] 2021-09-08 17:09
Closing as duplicate of #51047, this is fixed in 3.4 Beta 4.

Also for info:
1. You don't need to apply any floor velocity in your script, it's already done automatically in `move_and_slide`.
So in the floor case, you can just apply `velocity = Vector3.DOWN * 0.1`.
2. In order to improve the results for the moving platform, you can also set your `AnimationPlayer` playback mode to `Physics` instead of `Idle`. It will help getting things well synchronized.
3. In 3.4 you can also enable `motion/sync_to_physics` for the platforms. It can help keeping the platform in sync when the direction changes.

**Closed by pouleyKetchoupp** 2021-09-08 17:09 UTC
Labels: bug, topic:physics, regression, topic:3d
