### ISSUE TITLE
Vulkan: Low FPS with default environment on low-end graphics cards

### ISSUE THREAD

**Issue by floppyhammer** [godotengine/godot#54717] opened 2021-11-07 13:19 UTC
### Godot version

v4.0.dev.calinou [bd31af37b]

### System information

Ubuntu 21.10, Vulkan Clustered, AMD Radeon R7 260X

### Issue description

Low FPS in 3D scenes compared to 3.4. 2D scenes seem normal.

4.0
![Screenshot from 2021-11-07 21-04-19](https://user-images.githubusercontent.com/28705694/140646398-273040b9-4061-4e63-ba6b-7be8614f9dff.png)

3.4
![Screenshot from 2021-11-07 21-03-35](https://user-images.githubusercontent.com/28705694/140646400-e3785b52-dce4-44d9-873c-c18364b1b225.png)

### Steps to reproduce

Just create an empty 3D scene and enable `View Frame Time` to check FPS.

**Comment by akien-mga** [comment] 2021-11-07 13:26
Vulkan Clustered is the high end renderer, so low framerate on low-end hardware is expected.
You should try Vulkan Mobile which should hopefully perform somewhat better.

There might be ways to optimize and get some more performance out of low end eventually, but it's not really a bug, it's a natural consequence of high end backend on low end hardware.

**Comment by floppyhammer** [comment] 2021-11-07 13:36
@akien-mga Vulkan Mobile doesn't perform any better. If it was expected, should probably close this issue.

**Comment by Zireael07** [comment] 2021-11-07 13:42
OP, are you sure you're using actual Vulkan drivers and not software MESA?

**Comment by mrjustaguy** [comment] 2021-11-07 13:45
My GPU (Quadro K2000) which is significantly worse, doesn't preform nearly as badly as that on 4.0 FCR, I get this sort of performance with a million triangles and a handful of lights (1 directional, point lights for the rest) all with shadows at ~ 1mpx/frame

**Comment by Calinou** [comment] 2021-11-07 15:30
Glow is enabled in the default preview environment. You can disable it by clicking the 3 vertical dots at the top of the 3D editor viewport.

Since it doesn't make much of a visual difference most of the time, I suggest disabling glow by default.

**Comment by mrjustaguy** [comment] 2021-11-07 15:54
Glow doesn't explain the low FPS here, SDFGI maaaaybe, but even that is unlikely.

**Comment by floppyhammer** [comment] 2021-11-08 13:03
@Zireael07 I didn't know such software implementation of Vulkan exists...

If I add an empty `WorldEnvironment`, the FPS just soars:

![image](https://user-images.githubusercontent.com/28705694/140746415-d8d3261f-8e65-4b97-9f1d-19fb2257f45f.png)

And it increases further after adding an `Environment`:

![image](https://user-images.githubusercontent.com/28705694/140746337-ee1cf5cd-aa14-4ba6-baf3-28474594784b.png)

**Comment by Calinou** [comment] 2021-11-08 13:53
The blank/default environment has glow disabled, which likely explains the performance difference.

**Comment by clayjohn** [comment] 2021-11-08 18:52
@floppyhammer In the first screenshot did you move the editor camera around at all? The editor pauses frames until there is some change on screen. If the GPU is waiting on something from the CPU, sometimes this will result in the GPU reporting the full time it waited as part of the frame time. 

If you are still seeing the same FPS as the camera moves around in the 3D editor, then the performance is almost certainly caused by glow as Calinou suggested.

**Comment by floppyhammer** [comment] 2021-11-09 01:47
@clayjohn Same FPS when the camera moves around.

**Comment by Zireael07** [comment] 2021-11-09 08:06
> it doesn't make much of a visual difference most of the time

If it doesn't make much of a difference, why not disable glow on preview environments then?

**Comment by Calinou** [comment] 2021-11-09 11:08
> If it doesn't make much of a difference, why not disable glow on preview environments then?

I just amended https://github.com/godotengine/godot/pull/49736 to disable glow by default :slightly_smiling_face:

**Comment by Whimfoome** [comment] 2021-12-12 22:26
> OP, are you sure you're using actual Vulkan drivers and not software MESA?

Maybe there should be a warning when using software MESA, because on Linux with my GPU (AMD R9 280X), to enable Vulkan to work as intended I have to add `radeon.cik_support=0 radeon.si_support=0 amdgpu.cik_support=1 amdgpu.si_support=1` as kernel parameters, or I get like 5 fps per minute. When added everything is running butter smooth, but maybe that's a problem related to my GPU only

**Comment by Calinou** [comment] 2021-12-12 22:58
> Maybe there should be a warning when using software MESA, because on Linux with my GPU (AMD R9 280X), to enable Vulkan to work as intended I have to add `radeon.cik_support=0 radeon.si_support=0 amdgpu.cik_support=1 amdgpu.si_support=1` as kernel parameters, or I get like 5 frames per minute. When added everything is running butter smooth, but maybe that's a problem related to my GPU only

This can be done once https://github.com/godotengine/godot/pull/55790 is merged.

**Comment by FlykeSpice** [comment] 2021-12-25 16:17
> Vulkan Clustered is the high end renderer, so low framerate on low-end hardware is expected. You should try Vulkan Mobile which should hopefully perform somewhat better.
> 
> There might be ways to optimize and get some more performance out of low end eventually, but it's not really a bug, it's a natural consequence of high end backend on low end hardware.

Excuse me, wasn't the introduction of a Vulkan backend supposed to make Godot's renderer more efficient compared to the existing opengl backends(which is also the main point of the api) on low-end devices? What do you mean it being "high end" backend?

**Comment by Zireael07** [comment] 2021-12-25 16:25
> wasn't the introduction of a Vulkan backend supposed to make Godot's renderer more efficient compared to the existing opengl backends(which is also the main point of the api) on low-end devices?

In short, you're right in the first half of your sentence (it's supposed to be more efficient) but Vulkan is NOT a low-end option. It's just more efficient than OpenGL on devices that ARE able to run it, plus it doesn't have the "broken drivers on mobile" problem GLES has. But it's definitely NOT low-end, evidenced by the fact that very FEW Android devices have this capability.

**Comment by KoBeWi** [comment] 2022-06-04 15:58
Is it by chance any better now?
There is an opengl3 driver available now that you could try, but not sure if it supports 3D already.

**Comment by floppyhammer** [comment] 2022-06-07 05:01
@KoBeWi have no access to any low-end graphics cards currently, so I can't tell if there's any improvement.

**Comment by clayjohn** [comment] 2023-01-12 21:06
Closing as the OP no longer has the ability to confirm if performance has improved. The performance is consistent with what I see on my 2013 chromebook running Lubuntu (Intel Celeron N2840 2.16GHz). It seems likely the OP was either running a software fallback, or Godot is running on an integrated CPU instead of using the GPU. In either case there is nothing actionable for us.

**Closed by clayjohn** 2023-01-12 21:06 UTC
Labels: topic:rendering, topic:editor, usability, needs testing, regression, topic:3d, performance
