### ISSUE TITLE
Unexpected results about array type hints

### ISSUE THREAD

**Issue by upizpp** [godotengine/godot#80016] opened 2023-07-29 15:07 UTC
### Godot version

4.1.1.stable

### System information

Windows 11 - Godot v4.1.1.stable - Vulkan (Forward+)

### Issue description

When attempting to assign a regular array to an array with a specified content type, a type mismatch error will be reported, even if the as keyword has been used for type casting.

### Steps to reproduce

```
@tool
extends EditorScript

# Invalid
func test1() -> void:
	var a = Array(["test", "test", "test"])
	var b: Array[String] = a as Array[String] # Trying to assign an array of type "Array" to a variable of type "Array[String]".
	print(b)

# Valid
func test2() -> void:
	var a = Array(["test", "test", "test"])
	var b: Array = a as Array[String]
	print(b)

func _run() -> void:
	test1()
	test2()
```

### Minimal reproduction project

N/A

**Comment by AThousandShips** [comment] 2023-07-29 15:09
Duplicate of #72627

**Closed by AThousandShips** 2023-07-29 15:09 UTC
