### ISSUE TITLE
C# NativeAOT export fails to load resources with ResourceLoader.LoadThreadedRequest() or any async resource loading, but runs fine in non-NativeAOT exports

### ISSUE THREAD

**Issue by moldovanedy** [godotengine/godot#87752] opened 2024-01-30 18:32 UTC
### Tested versions

- Reproductible in 4.2.0.stable.mono

### System information

Godot v4.2.stable.mono - Windows 11 - Vulkan (Mobile) - dedicated NVIDIA GeForce RTX 3050 Laptop GPU (NVIDIA; 31.0.15.2904) - 11th Gen Intel(R) Core(TM) i5-11320H @ 3.20GHz (8 Threads)

### Issue description

When launching the game from Godot, everything works fine, it also works with normal export (without NativeAOT), but for some reason the ```ResourceLoader.LoadThreadedGet(scenePath)``` will hang the application (if called from non-async function, if the function is async then it will just wait forever). I've also tried this code:
```
PackedScene? scene = null;
await Task.Run(() =>
{
    scene = ResourceLoader.Load<PackedScene>(scenePath);
});
```
which works just fine when launching from Godot or non-NativeAOT deployment, but for some reason will not work with NativeAOT. I have to mention that calling ResourceLoader.Load() works ok, but it just seems weird that async code won't work correctly. Is there a problem with async/await in NativeAOT?

I know that NativeAOT needs special configuration in Godot, but I already did that:
```
<PublishAOT>true</PublishAOT>
...
<ItemGroup>
  <TrimmerRootAssembly Include="GodotSharp" />
  <TrimmerRootAssembly Include="$(TargetName)" />
</ItemGroup>
```
Also, there are a lot of warnings after the AOT build finishes (further detailed [here](https://github.com/godotengine/godot/issues/85476#issuecomment-1833473767)), but from my understanding it shouldn't be such a big problem with it.

### Steps to reproduce

See MRP below. The code will fail if the export is NativeAOT. To enable NativeAOT, follow [this Godot blog post](https://godotengine.org/article/platform-state-in-csharp-for-godot-4-2/).

### Minimal reproduction project (MRP)

```
private async Task<PackedScene?> GetSceneDataAsync(string scenePath)
{
    PackedScene? scene = null;
    await Task.Run(() =>
    {
        LoadScene(scenePath, out scene);
    });
    GD.Print("Scene loaded!");

    return scene;
}

private void LoadScene(string scenePath, out PackedScene? scene)
{
    GD.Print("Started loading scene...");
    scene = null;
    ResourceLoader.LoadThreadedRequest(scenePath);

    ResourceLoader.ThreadLoadStatus status = ResourceLoader.LoadThreadedGetStatus(scenePath);
    if (status == ResourceLoader.ThreadLoadStatus.Failed)
    {
        GD.Print("Loading failed.");
        throw new System.Exception();
    }
    else if (status == ResourceLoader.ThreadLoadStatus.InvalidResource)
    {
        GD.Print("Loading failed.");
        throw new System.Exception();
    }
    else
    {
        GD.Print("Getting scene...");
        scene = (PackedScene)ResourceLoader.LoadThreadedGet(scenePath);
        GD.Print("Scene obtained.");
    }
}
```

Here, "Getting scene" will be written (sometimes also "Scene obtained"), but "Scene loaded" never will.

**Comment by raulsntos** [comment] 2024-01-30 19:33
Duplicate of https://github.com/godotengine/godot/issues/87596

**Closed by raulsntos** 2024-01-30 19:33 UTC
