### ISSUE TITLE
Import animation clips not working (3D)

### ISSUE THREAD

**Issue by Juankz** [godotengine/godot#36587] opened 2020-02-27 04:51 UTC
**Godot version:**
3.2

**OS/device including version:**
Linux 5.5 - Nvidia GTX1050

**Issue description:**
I have a 3d model with multiple animations within a single timeline. I'm trying to use the clips property under the import panel to separate those multiple animations. However I don't get anymore animations than the single long timeline.

This is my configuration:
![clips_import](https://user-images.githubusercontent.com/18577412/75412862-d14bf480-58f1-11ea-930b-9de4da1bfeb7.png)

**Steps to reproduce:**
1. Create a new project
1. Import the attached gltf file
2. Under the import menu create two tracks:
  - Idle from 0 to 110
  - Run from 130 to 200
3. Set animation FPS to 24
4. Hit reimport

**Minimal reproduction project:**
[Character_Animation.zip](https://github.com/godotengine/godot/files/4259467/Character_Animation.zip)

**Comment by Calinou** [comment] 2020-02-27 10:08
Duplicate of #25599.

**Closed by Calinou** 2020-02-27 10:08 UTC
