### ISSUE TITLE
Text added to RichTextLabel using append_bbcode is removed if the screen is resized

### ISSUE THREAD

**Issue by MarianoGnu** [godotengine/godot#27027] opened 2019-03-13 21:31 UTC
**Godot version:**

3.1 master

**OS/device including version:**

Windows 10 Pro

**Issue description:**

adding text to a rich text label using append_bbcode and resizing the window causes the text to be deleted

**Steps to reproduce:**
this line works good:
`	Messages.bbcode_text += new_bbcode`
this line works bad
`	Messages.append_bbcode(new_bbcode)`

**Comment by TheDuriel** [comment] 2019-03-14 20:43
probably related to #24173

**Comment by MarianoGnu** [comment] 2019-03-17 20:18
yeah, calling update makes new text added to be discarded, the same that when window is resized

**Comment by akien-mga** [comment] 2019-04-02 10:12
Closing as duplicate of #24173 then.

**Closed by akien-mga** 2019-04-02 10:12 UTC
Labels: bug, topic:core

**Comment by OsakiTsukiko** [comment] 2022-12-25 19:04
This issue is not a duplicate of #24173 as that issue was fixed yet this one still persists.  24173 uses the bbcode_text property on RichTextLabel which seems to be fixed, while this one uses the append_bbcode method which is still buggy!  I think this issue should be reopened.

**Comment by OsakiTsukiko** [comment] 2022-12-25 19:15
Although this issue is fixed in Godot 4.0 as the whole BBCode system had major changes.

**Comment by OsakiTsukiko** [comment] 2022-12-25 20:06
Hmm. I can not replicate this issue outside of my project for some reason. The only thing I can think of is that I'm using async functions and the append_bbcode method is called at the same time twice on the same node.

**Comment by OsakiTsukiko** [comment] 2022-12-25 23:17
After some more testing, I managed to recreate the issue outside of my project. The issue seems to only occur when using a custom (Dynamic) font.

**Comment by OsakiTsukiko** [comment] 2022-12-25 23:26
https://user-images.githubusercontent.com/104794884/209484429-52c7aa16-9e26-4d33-a1ad-9490c2864edc.mp4

Showcase of issue
