### ISSUE TITLE
Color Picker in Editor: can't remove preset using RMB

### ISSUE THREAD

**Issue by mrimvo** [godotengine/godot#47309] opened 2021-03-23 20:17 UTC
**Godot version:**
Version 3.3 RC6

**OS/device including version:**
Ubuntu 18.04

**Issue description:**
Using the color picker in the editor, I want to delete a color from the *second row*, but it will delete the ones from the first row.

**Steps to reproduce:**
1. In the Scene, click on any node featuring the `modulate` property.
2. In the Inspector, click on "modulate" to open the Color Picker
3. Add lots of colors to the preset, such that a second line of colors appears
4. try to remove a color from the second line using RMB

Expected: the right-clicked color is removed
Observed: the color from the first line (same row) is removed

In this example, I click the dark purple color, but the red one is removed.

![Auswahl_581](https://user-images.githubusercontent.com/6030346/112212264-0d4ca880-8c1d-11eb-803e-738bd40e5ea6.png)

**Comment by Calinou** [comment] 2021-03-23 20:37
Duplicate of https://github.com/godotengine/godot/issues/43270.

**Closed by Calinou** 2021-03-23 20:37 UTC
Labels: bug, topic:gui, topic:input
