### ISSUE TITLE
AnimationTree BlendTree nodes appearing in the wrong place on creation

### ISSUE THREAD

**Issue by sayaks** [godotengine/godot#58064] opened 2022-02-13 21:11 UTC
### Godot version

4.0.alpha2

### System information

Linux, 5.10.96-1-MANJARO, x86_64

### Issue description

When in a blend tree on an AnimationTree, if i create a new node it will appear very far away from where i clicked. typically very far outside of my view.

![image](https://user-images.githubusercontent.com/9107253/153774684-faae5fcf-54aa-49a7-bd35-8776bea8f83d.png)

In this image of the minimap, i made two nodes inside of the view and they appeared far outside as you can see on the black squares to the right in the minimap.

 When i create a node i expect it to appear where i right-clicked to make it.

This does not appear to be a problem for any other graph-like view. I have tried: visual scripts, animation node state machines, and visual shaders. None of which showed this same problem.

### Steps to reproduce

1. Create AnimationTree
2. Set Tree Root to an AnimationNodeBlendTree
3. Right click in the view of the blend tree and create any node
4. Node should not appear where you right clicked, but somewhere else.  

### Minimal reproduction project

[minimal_example.zip](https://github.com/godotengine/godot/files/8056657/minimal_example.zip)

result of following the steps outlined above.

**Comment by Calinou** [comment] 2022-02-13 21:26
I remember this being reported elsewhere already (maybe for the visual shader editor), but I can't find the issue right now.

**Comment by TokageItLab** [comment] 2022-03-08 21:32
Dupe of #57410.

**Closed by TokageItLab** 2022-03-08 21:32 UTC
Labels: bug, topic:gui
