### ISSUE TITLE
The Label That is inside a scene, childed with another scene first text is not following CanvasLayer

### ISSUE THREAD

**Issue by Muhammad-Fiqri** [godotengine/godot#78956] opened 2023-07-02 17:02 UTC
### Godot version

4.0.3 Stable

### System information

Windows 10; Godot 4.0.2 Stable; Intel UHD Graphics 620; Intel i5; Ram 8GB; Lenovo Idepad

### Issue description

![image](https://github.com/godotengine/godot/assets/60091975/21a47455-fad8-4826-bcb5-082493bdaeb9)
"P" is not Symmetrical with "layer 1 Turn"

### Steps to reproduce

make a canvas layer node
make a control node
make a label as a child of that control node
make a name the label through code
run scene and the first text is not syncing

### Minimal reproduction project

P.S This is the Repo of my Freelance Work and my client forbade me to make this repo open source, therefore don't publish this to the public for commerce use without his permission.
[Here is the repo](https://drive.google.com/file/d/152TkKfFjw02WO9Wu1AgGXh_8GFupyAF7/view?usp=sharing)

**Comment by arkology** [comment] 2023-07-02 17:05
Duplicate of https://github.com/godotengine/godot/issues/58314

**Comment by KoBeWi** [comment] 2023-07-02 17:38
Closing as duplicate.

**Closed by KoBeWi** 2023-07-02 17:38 UTC

**Comment by Muhammad-Fiqri** [comment] 2023-07-03 05:28
Thank you Mr @arkology and Mr @KoBeWi for helping me.
I will contribute to this FOSS Project when I have the time, cheers.
