### ISSUE TITLE
Running module_mono_enabled=yes and mono_glue=no crashes

### ISSUE THREAD

**Issue by blackwc** [godotengine/godot#12184] opened 2017-10-17 15:49 UTC
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**

Ubuntu 16 Godot 3

**Issue description:**

Tried to generate glue and it crashed.

**Steps to reproduce:**

scons p=x11 module_mono_enable=yes mono_glue=no

run it and it crashes. Doesn't matter if you use --generate-mono-glue or not.

mono_log:

* Assertion at sgen-alloc.c:558, condition `tlab_next_addr_offset != -1' not met
 (in domain , error)

pkg-config mono-2 --cflags --libs:
-D_REENTRANT -I/usr/lib/pkgconfig/../../include/mono-2.0 -L/usr/lib/pkgconfig/../../lib -lmono-2.0 -lm -lrt -ldl -lpthread

**Comment by kubecz3k** [comment] 2017-10-17 16:46
duplicate of https://github.com/godotengine/godot/issues/12142

**Comment by akien-mga** [comment] 2017-10-17 16:54
Nope, the error is different.

**Comment by akien-mga** [comment] 2017-10-17 17:27
@blackwc What's your mono version?

**Comment by blackwc** [comment] 2017-10-17 17:42
mono --version
Mono JIT compiler version 4.2.1 (Debian 4.2.1.102+dfsg2-7ubuntu4)

**Comment by akien-mga** [comment] 2017-10-17 19:22
#12142 hints that it might affect only old versions of Mono; you could try to update your mono version using the Ubuntu repos provided by upstream: http://www.mono-project.com/download/

**Comment by blackwc** [comment] 2017-10-17 21:45
That worked.

**Comment by akien-mga** [comment] 2017-10-18 08:15
I've discussed a bit with @neikeq, and we'll make Mono 5.2 the minimum required version, so I think we can close this issue and mine.

**Closed by akien-mga** 2017-10-18 08:15 UTC
Labels: bug, topic:mono
