### ISSUE TITLE
Resource.duplicate returns a PackedScene without nodes although loaded Scene has them 

### ISSUE THREAD

**Issue by David-Ochoa** [godotengine/godot#20009] opened 2018-07-06 21:18 UTC
**Godot version:**
3.0 custom build e19388df97743939efd0cfda3dae6de2db393897

**OS/device including version:**
Windows 7, Intel integrated chip

**Issue description:**
I'm dynamically loading a scene, but when using duplicate the returned PackedScene returns false when calling can_instance and instancing it fails with a node count==0.

**Steps to reproduce:**
Create a simple scene with some nodes, in another scene preload and duplicate it.

**Minimal reproduction project:**
[InstanceProblem.zip](https://github.com/godotengine/godot/files/2171998/InstanceProblem.zip)

**Comment by Calinou** [comment] 2020-06-07 20:51
I can't reproduce this in 3.2.2beta4, closing.

In `Spatial.gd`, adding the following snippet prints `True` every time the project is started:

```gdscript
var cs = _cube_factory.duplicate()
print(cs.can_instance())
```

**Closed by Calinou** 2020-06-07 20:51 UTC
Labels: bug, topic:core
