### ISSUE TITLE
Problems exporting to android on gitlab

### ISSUE THREAD

**Issue by dbrova15** [godotengine/godot#40056] opened 2020-07-02 13:35 UTC
I want to configure a custom build for android on gitlab. My docker image is at https://github.com/dbrova15/godot-ci-android-bakz
An error occurs during assembly
![image](https://user-images.githubusercontent.com/20703983/86365307-01c9e380-bc82-11ea-9100-3b9caa49c76b.png)

A project with no problem is exported to my computer. I move the android folder to the docker unchanged.

Tell me what am I doing wrong?

**Comment by Calinou** [comment] 2020-07-02 13:42
Duplicate of https://github.com/godotengine/godot/issues/29385 and possibly others.

**Closed by Calinou** 2020-07-02 13:42 UTC
