### ISSUE TITLE
Repeated function call on nonlooping animation

### ISSUE THREAD

**Issue by scottkunkel** [godotengine/godot#27306] opened 2019-03-22 00:12 UTC
**Godot version:**

69ea7da

**OS/device including version:**

win 10

**Issue description:**

Animation function call in AnimationTree gets triggered multiple time.
This happens reproducible when the application window is being maximize but also due to other, unknown, reasons

**Steps to reproduce:**
attached project:
play scene
maximize window
return window to normal state
ani gets printed twice, which means eventcalled is called more than once
[AniTest.zip](https://github.com/godotengine/godot/files/2994408/AniTest.zip)

**Minimal reproduction project:**

**Comment by akien-mga** [comment] 2020-01-15 11:18
I can't reproduce the issue in any Godot version that I tried: `master` HEAD, `3.1` HEAD, `3.1-stable`, on Linux.

Can you still reproduce it?

**Comment by tom-jk** [comment] 2020-07-19 10:39
Can't reproduce in 3.2.2.stable on linux mint 18.3.

Often doing things like minimize, maximize or interacting with other windows while a godot game is running causes a momentary freeze/stutter, so I tried doing these aggressively to see if that somehow played a part, but no dice.

**Comment by Calinou** [comment] 2020-07-19 12:11
I can't reproduce this either on Godot 3.2.2, closing.

**Closed by Calinou** 2020-07-19 12:11 UTC
Labels: bug, topic:core
