### ISSUE TITLE
broken viewport when the WorldEnvironment background mode is canvas

### ISSUE THREAD

**Issue by yzn-h** [godotengine/godot#57590] opened 2022-02-03 16:19 UTC
### Godot version

4.0.dev

### System information

Linux pop os 21.10 and Windows, i7-8550U, Vulkan

### Issue description

when we change the WorldEnvironment node background mode to canvas the UI broke and all shapes become gray

https://user-images.githubusercontent.com/63852512/152383036-91c56d04-0bd4-4fb8-b521-69b0291c4f00.mp4

### Steps to reproduce

1 - add a WorldEnvironment node
2 - in WorldEnvironment change the background mode to canvas

**Comment by Calinou** [comment] 2022-02-03 17:04
Duplicate of https://github.com/godotengine/godot/issues/52467.

**Closed by Calinou** 2022-02-03 17:04 UTC
Labels: bug, archived, topic:rendering, regression, topic:gui, topic:2d
