### ISSUE TITLE
Sampling depth texture in GLES2 breaks sampling screen texture

### ISSUE THREAD

**Issue by sdfgeoff** [godotengine/godot#49900] opened 2021-06-25 01:36 UTC
### Godot version

3.3.2 Stable (from website)

### System information

Archlinux (intel), Android (Go)

### Issue description

I have a project using GLES 2.0 so that it can run decently on Android phones.

As part of this project I want a screen-space shader to sample both depth texture and color texture, so I use:
```
	color = texture(SCREEN_TEXTURE, SCREEN_UV).rgb;
	depth = texture(DEPTH_TEXTURE, SCREEN_UV).r;
```

Unfortunately, sampling the depth texture results in `color = vec3(1.0)` as per the gif below:
![Peek 2021-06-25 13-35](https://user-images.githubusercontent.com/13490050/123355662-3da83800-d5ba-11eb-9807-77232bd75095.gif)

### Steps to reproduce

See the example project. Comment and uncomment the depth texture sample

### Minimal reproduction project

[GLES2Bug.zip](https://github.com/godotengine/godot/files/6712924/GLES2Bug.zip)

**Comment by clayjohn** [comment] 2021-06-25 06:19
Duplicate of https://github.com/godotengine/godot/issues/47179

**Closed by clayjohn** 2021-06-25 06:19 UTC
