### ISSUE TITLE
Cannot create brackets, symbols in godot  Script Editor

### ISSUE THREAD

**Issue by mastermarkus** [godotengine/godot#9576] opened 2017-07-09 12:59 UTC
**Operating system or device - Godot version:**
Operating system: Windows 10 Home
Godot Version : 2.1.3 stable

### Issue Description:
I have Estonian (EST) keyboard and usually i can create brackets like this [ ], by pressing Ctrl+Alt+8, Ctrl+Alt+9, When i tried to create array , it just didn't create any symbol when holdingCtrl+alt and any number it doesn't recognize. I also saw built in function Array(), do i have to use brackets to create array or, i can use built in Array() function?

**Comment by MarianoGnu** [comment] 2017-07-09 13:38
you can create arrays like
    var a = Array()
and pupulate it with
    a.push_pack(1)
    a.push_back(2)
but using brakets is much easier
    var a = [1,2,3,4,5,6]

i'm not sure on how easy would this bug be fixed without actual hardware to try out...

**Comment by akien-mga** [comment] 2017-07-09 13:42
Can you input brackets with AltGr (Right Alt) + 8 or 9?

**Comment by mastermarkus** [comment] 2017-07-09 20:04
Oh yes im able to create brackets with AltGr + 8 and 9 on the right side of keyboard thanks, but i guess it's still bug that could be fixed.

**Comment by vnen** [comment] 2017-07-09 20:15
This is a duplicate of #6851 then, I guess.

**Comment by akien-mga** [comment] 2017-07-10 08:35
Indeed.

**Closed by akien-mga** 2017-07-10 08:35 UTC
Labels: bug, platform:windows, topic:porting
