### ISSUE TITLE
[AudioServer] Changing global fx volume doesn't affect the reverb of SamplePlayers

### ISSUE THREAD

**Issue by janmarcano** [godotengine/godot#2304] opened 2015-07-26 00:42 UTC
When using a SamplePlayer that has ReverbSend, using the function:
_AudioServer.set_fx_global_volume_scale(0)_
will reduce the volume of the sample that is played, but the sound will still be sent to the reverb and only the 'echo' will be heard.

[Sample project](https://dl.dropboxusercontent.com/u/43859429/ReverbBug.zip)

**Comment by freemanfromgodotengine** [comment] 2015-07-27 23:35
I can confirm that on stable 1.1.
But actually I like the way it works. From my perspective it gives more flexibility to what’s possible with sound. What other way would be to hear reverb set to “pre fade” in the mix? It can be desired sound fx for some people in some situations. The way it works now is not really intuitive, but I think it would be good to be able to set pre or post fade in fx section of the SamplePlayer in the future.

That was already on the list of my requests of what could be added/corrected in Godot’s audio area, that I plan to post and discuss at some point, but since you mentioned it...

**Comment by akien-mga** [comment] 2015-11-10 22:03
I cqn reproduce it too in the current master branch (61c4c57) thanks to the nice sample project provided. It's quite weird indeed that everything is mute but you can still hear the echo (and not only the echo of a sample played before the mute as I thought initially when reading the report).

**Comment by reduz** [comment] 2016-01-02 12:43
the audio subsystem will eventually be rewritten in 2.1, so for now, sitting on this issue

**Comment by vnen** [comment] 2016-05-29 18:41
This is still valid in master. @reduz do you still plan to do this for 2.1?

**Comment by neikeq** [comment] 2016-06-03 19:45
@vnen We discussed it on irc today. 2.2 will be focused on the new audio system and higher level networking.

**Comment by bojidar-bg** [comment] 2017-04-24 14:43
Was this fixed in 3.0 with the audio busses?

**Comment by akien-mga** [comment] 2017-09-18 11:21
Assumed fixed in 3.0, feel free to reopen/comment/open a new issue if it's not the case.

**Closed by akien-mga** 2017-09-18 11:21 UTC
Labels: bug, confirmed, topic:audio
