### ISSUE TITLE
Project Manager window spawns in location where it can't be reached.

### ISSUE THREAD

**Issue by PucklaMotzer09** [godotengine/godot#37491] opened 2020-04-01 11:20 UTC
**Godot version:** 4.0.dev.custom_build.f7b8d0c68

**OS/device including version:** Windows 10; AMD Radeon R9 380

**Issue description:**
When I start Godot the window spawns in the top left corner where I can't reach the title bar. Which means that I can't move the window. When I resize the window I can see the title bar and move it normally. The same thing happens when I run a game from the project manager. If I start a game inside the editor the window spawns in the same location at first but then gets relocated to the middle of the screen.
In Godot 3.2 the window spawned in the middle of the screen.

**Comment by Anutrix** [comment] 2020-04-01 11:46
Duplicate of https://github.com/godotengine/godot/issues/37323.

**Closed** 2020-04-01 12:15 UTC
