### ISSUE TITLE
[WebGL2] Particles2D not being rendered on Firefox

### ISSUE THREAD

**Issue by belen-albeza** [godotengine/godot#19344] opened 2018-06-03 14:18 UTC
**Godot version:** 3.0.2 stable official

**OS/device including version:**
- Firefox 60, 61 and 62 on Mac OS X (computer is a 2017 iMac)
- Chrome 66 on Mac OS X

**Issue description:**
On Firefox, sometimes Particles2D systems are not visible. On Chrome, in addition to the particles not being visible, the screen shakes quite hard  and freezes (this last bit probably is the same as https://github.com/godotengine/godot/issues/16281 )

**Steps to reproduce:**
I made a game that showcases this. Go to https://belen-albeza.github.io/space-shooter-godot/ and shoot with the spacebar. Enemies should explode on contact, but on Firefox most of the times the particles are not visible / created (sometimes they do).

Source code is available at https://github.com/belen-albeza/space-shooter-godot

**Comment by akien-mga** [comment] 2018-06-05 06:48
Confirmed on Firefox Nightly 62.0a1 (2018-06-02) (64-bit).

**Comment by kidandcat** [comment] 2018-08-09 09:11
Same with Godot Engine v3.0.6 on Chrome 69.0.3497.23 Linux

**Comment by danilw** [comment] 2019-05-01 14:48
sorry for up
Particles2D(GPU) still does not work in Godot 3.1 for WebGL

reason is https://www.khronos.org/registry/webgl/specs/latest/2.0/#5.1

**Comment by clayjohn** [comment] 2019-12-18 06:35
We are no longer working on the WebGL2 backend due to poor driver support on most systems. We recommend you use the GLES2/WebGL backend instead. 

Unfortunately, that means this bug just isn't going to be fixed in GLES3/WebGL2, sorry.

**Closed by clayjohn** 2019-12-18 06:35 UTC
Labels: bug, confirmed, platform:html5, topic:porting, topic:rendering
