### ISSUE TITLE
Editing @export var which is Array[Type] causes editor to crash

### ISSUE THREAD

**Issue by ezietsman** [godotengine/godot#78678] opened 2023-06-25 17:15 UTC
### Godot version

v4.1.beta3.official [ada712e06]

### System information

Godot v4.1.beta3 - macOS 13.4.1 - Vulkan (Forward+) - dedicated AMD Radeon Pro 5300M - Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 Threads)

### Issue description

I added an export variable which is Array[Vector3] (also tested with Array[Vector2]. Click Add Element in the inspector, then edit the Vector, adding a number to x works, but tabbing, or clicking on y field causes the editor to crash.

### Steps to reproduce

- Add `@export var x : Array[Vector2]`.
- click on x in inspector.
- click add element
- click x and type in a number
- hit Tab, or click on y

### Minimal reproduction project

[minimal.zip](https://github.com/godotengine/godot/files/11860343/minimal.zip)

**Comment by AThousandShips** [comment] 2023-06-25 17:50
* Duplicate of: #78578

**Closed by AThousandShips** 2023-06-25 17:50 UTC
