### ISSUE TITLE
VariableSet Defaults to Nil in visual scripts

### ISSUE THREAD

**Issue by Capital-EX** [godotengine/godot#19609] opened 2018-06-17 06:15 UTC
**Godot version:**
3.0.3 [Steam]

**OS/device including version:**
Ubuntu 16.01 LTS

**Issue description:**
VariableSet node can (with no visual feedback) set the target variable to Nil.  This happens when using the default value provided.  In my case I was using a `variable` of type float.  The VariableSet node will default to setting `variable` to zero. However, it instead sets`variable` to Nil.

**Steps to reproduce:**
1. Create a new `variable` assigned some value.
2. Create a VariableSet node that assigns a default value (note: do not click on the entry box).
4. After that VariableSet node is ran, `variable` is now null.  Any attempt to use it with a VisualScriptOperator will result in an Invalid argument error.

**Comment by fire** [comment] 2018-09-12 18:30
Investigating the issue.

**Comment by fire** [comment] 2018-09-13 11:08
I cannot reproduce on 6c20c3a5345f6eefdbcbb1288bd874c4f3670a1b

[godot_19609.zip](https://github.com/godotengine/godot/files/2378996/godot_19609.zip)

**Comment by akien-mga** [comment] 2018-09-13 11:11
Assuming fixed, please comment if you can still reproduce it.

**Comment by haizhou37** [comment] 2018-12-04 03:31
I have a similar problem in the latest version of godot master（9：00，3/12/2018）.
In visual scripts, variables cannot be set to the default value of zero, which is always null。
![2018-12-04 11-30-35](https://user-images.githubusercontent.com/33272474/49417284-17caa600-f7b8-11e8-8145-73366316cefa.png)

**Comment by fire** [comment] 2018-12-04 07:49
Can you make a simple test project?

**Comment by haizhou37** [comment] 2018-12-04 13:53
> Can you make a simple test project?

[test2.zip](https://github.com/godotengine/godot/files/2644204/test2.zip)

**Comment by bojidar-bg** [comment] 2018-12-04 16:33
Can confirm. Until changing something, it will remain null, after changing the value it will all work well.

**Comment by Chaosus** [comment] 2019-01-10 18:39
Still exist in 3.1 beta

![image](https://user-images.githubusercontent.com/3036176/50989341-1e1f1100-1520-11e9-832a-e226333f00d7.png)

**Comment by bojidar-bg** [comment] 2019-03-06 20:51
This might have been fixed with #26604, can you confirm?

**Comment by Capital-EX** [comment] 2019-03-07 23:44
Patch works on Windows Beta 11 build!

![image](https://user-images.githubusercontent.com/13488718/53997106-f3f56400-4108-11e9-8199-425f0a093e57.png)

**Comment by Chaosus** [comment] 2019-03-08 04:10
Yeah its fixed !

**Closed by Chaosus** 2019-03-08 04:10 UTC
Labels: bug, confirmed, topic:visualscript
