### ISSUE TITLE
AnimationTree nodes cannot be connected until the editor is restarted

### ISSUE THREAD

**Issue by ViktorEvil** [godotengine/godot#65988] opened 2022-09-17 14:45 UTC
___

***Bugsquad note:** This issue has been confirmed several times already. No need to confirm it further.*

___

### Godot version

4.0 beta1

### System information

macOS Monterey 12.5.1, M1 MacBook Pro

### Issue description

I am not able to connect nodes in the AnimationTree. I select the connection arrow icon  and left click from one node and drag to another node until the arrow snaps but upon releasing the button the arrow disappears.

![AnimTree Nodes](https://user-images.githubusercontent.com/4403212/190862720-75f451b0-89ab-4495-8a59-b16b08bb2a51.gif)

### Steps to reproduce

add blend space 2d nodes to the AnimationTree and try and connect the nodes together using the connection arrows.

**Comment by TokageItLab** [comment] 2022-09-21 11:07
I can't reproduce. Please send minimal reproduction project. Perhaps #63249 is related, but the issue description lacks details.

**Comment by xrthat** [comment] 2022-09-24 02:38
@TokageItLab Here is an MRP where the issue described in the OP is happening.

- create Animation Player and Tree on CharacterBody2d
- set tree root to 'AnimationNodeStateMachine' and attach 'AnimationPlayer'
- create a single BlendSpace2d node and attempt to create a transition from the 'Start' node to the created node.
- The transition arrows do not snap and connect to to the created BlendSpace2d node

[blendspace2dbug65988.zip](https://github.com/godotengine/godot/files/9637738/blendspace2dbug65988.zip)

**Comment by TrayserCassa** [comment] 2022-09-25 16:21
I've the same issue. I converted my game from 3.5 to 4.
So the AnimationTree was created at 3.5. After I deleted the AnimationTree and recreated it, the issue was still there. And after a restart it worked.

The git diff was also showing more diffs as it should. So I guessed it is the converter.

Anyway I find out that there was a really strange behaviour. I wanted to post the git diff and maybe this would help for the converter tool. But after I hard resetted the working AnimationTree it worked also for the old AnimationTree. So I guess this might be a Editor caching thing? I hard resetted the complete Project and also closed it. 

If someone want more debug infos I can try to help :)

**Comment by mattkanwisher** [comment] 2022-09-28 18:20
I am able to reproduce same problem on windows in godot 4 beta 1

**Comment by Fish1** [comment] 2022-10-08 18:07
I am also experiencing this issue.

**Comment by Erveon** [comment] 2022-10-11 11:40
Had the same issue after creating a new project in 4.0 Beta 2. After a restart, I was able to connect them.

**Comment by mjohnson159** [comment] 2022-10-19 00:30
One more instance for running into this. Version 4.0.beta1.mono. My project is purely Godot 4.0, no conversion of an old project. A restart of Godot fixed the issue.

**Comment by Miautawn** [comment] 2022-11-04 18:13
Just experienced this Godot 4.0 beta3. Also a fresh 4.0 project. As noticed previously, restarting the editor helps.

OS: Linux, Arch
Kernel Version 5.19.13-arch1-1

**Comment by EricDoherty** [comment] 2022-11-05 18:21
I just had this issue with Godot 4 Beta 4, brand new project, I was following the tutorial (Godot 4 Crash Course for Beginners - GameDev 2D Top Down Tutorial from the 23:00 to 31:00 timeframe for the exact steps I took)

Restarting Godot also fixed it for me.

OS: Windows 10
Version 10.0.19045 Build 19045

**Comment by mapleroyal** [comment] 2022-11-27 22:15
Encountered this bug. Same issue as everyone else. I was also following the same guide--in the same section--as @EricDoherty.

New project, purely godot 4 beta 6. Running vanilla arch linux.

**Comment by fsoft72** [comment] 2022-12-12 15:07
godot 4.0 beta 8, the same error on Linux

**Comment by rluders** [comment] 2022-12-13 09:04
Same here.

Godot 4 Beta 8
OS: MacOS 13.0.1

**Comment by wmf508** [comment] 2022-12-17 13:25
Had the same issue, restart no helps. 
but don't rename the node before connect helps me.

Godot 4 Beta 8, OS: MacOS

**Comment by TokageItLab** [comment] 2022-12-18 22:27
I found a way to reproduce this 100%. "After renaming a Node in a StateMachine, connecting no longer works." Is this correct?

**Comment by Flynsarmy** [comment] 2023-01-26 07:52
This issue can be reopened. Just experienced in Beta 15 (after compiling from source with the AnimationTree fix). I also had renamed a node in a StateMachine before attempting to connect nodes.

**Comment by Zireael07** [comment] 2023-01-26 07:56
The crash in Beta 15 has a completely different reason, is reported elsewhere

**Comment by Flynsarmy** [comment] 2023-01-26 07:59
You misread my comment. I compiled the crash fix to get AnomationTree working. 

My comment stated I'm getting the node connection issue mentioned in Ops post (and by all other commenters in this thread) in the current build of Godot after renaming a node in a StateMachine. My comment is about this issue, not the separate AnimationTree one.

**Comment by TokageItLab** [comment] 2023-01-26 13:14
@Flynsarmy I cannot reproduce. This bug is definitely fixed. If it still recurs, please send us a video recording showing the steps to reproduce it.

**Closed by TokageItLab** 2023-01-26 13:14 UTC
Labels: bug, topic:editor, confirmed, usability, regression, topic:animation
