### ISSUE TITLE
Raycast2D not casting to the right position when casting the ray in code

### ISSUE THREAD

**Issue by mkhoi-dude** [godotengine/godot#47167] opened 2021-03-19 15:15 UTC
**Godot version:**

3.2.3

**OS/device including version:**

Windows 10

**Issue description:**

Casting a raycast2D to a position using code doesn't cast the ray to the right position.

Like this example where i cast the ray onto the mouse's global position but the ray doesn't cast to the correct position:
![gif](https://user-images.githubusercontent.com/58685036/111802556-b6835e00-8900-11eb-810d-f5966771fd47.gif)

**Steps to reproduce:**
In code, just cast a ray into the position of any object and the ray won't cast to the exact location of the object.

**Minimal reproduction project:**

[RaycastIssue.zip](https://github.com/godotengine/godot/files/6172258/RaycastIssue.zip)

**Comment by Calinou** [comment] 2021-03-19 15:24
This is due to mouse coordinates, not the raycast preview. 
Duplicate of https://github.com/godotengine/godot/issues/34805 and possibly others.

**Closed by Calinou** 2021-03-19 15:24 UTC
