### ISSUE TITLE
Case mismatch warning when launching VS Code

### ISSUE THREAD

**Issue by KellyThomas** [godotengine/godot#19825] opened 2018-06-28 14:48 UTC
**Godot version:**
25275de

**OS/device including version:**
Windows

**Issue description:**
Windows usually treats file systems as case insensitive, however other many other OSs are case sensitive.

To help catch potential errors at design time we have a handy check built into the editor to warn if the casing used in a file path differs form the casing in the file system. (This is great, much easier that trouble shooting bugs after export!).

Unfortunately this goes a little bit haywire and gives a couple of technically correct but pretty useless warning messages when we launch VS Code to edit a C# file.

```
drivers\windows\file_access_windows.cpp:102 - Case mismatch opening requested file 'code.CMD',
stored as 'code.cmd' in the filesystem. This file will not open when exported to other
case-sensitive platforms.
```

```
WARNING: FileAccessWindows::_open: Case mismatch opening requested file 'code.CM
D', stored as 'code.cmd' in the filesystem. This file will not open when exporte
d to other case-sensitive platforms.
```

**Steps to reproduce:**
 1. Select VS Code at `Editor Settings` - `Mono` - `Editor` - `External Editor`
 2. Add C# script to a node
 3. Click on the script icon for that node in the Scene panel.

**Further Information**

We can see here that `GodotSharpEditor::open_in_external_editor()` is passing the basename "code" to `path_which()`:

https://github.com/godotengine/godot/blob/eeab3502d5eec68dbce2d7b7ff822a14e6a3599c/modules/mono/editor/godotsharp_editor.cpp#L197-L199

And we can see that `path_which()` is now iterating through the extensions listed in the `PATHEXT` environment variable searching for a match.

https://github.com/godotengine/godot/blob/eeab3502d5eec68dbce2d7b7ff822a14e6a3599c/modules/mono/utils/path_utils.cpp#L47-L74

Note that these are usually listed in upper case e.g.

```
PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.PY;.RB;.RBW
```

Then further downstream this incorrectly cased path triggers this check in `FileAccessWindows::_open()`:

https://github.com/godotengine/godot/blob/eeab3502d5eec68dbce2d7b7ff822a14e6a3599c/drivers/windows/file_access_windows.cpp#L88-L108

**Comment by akien-mga** [comment] 2019-01-28 12:10
Duplicate of #25368, fixed by #25370.

**Closed by akien-mga** 2019-01-28 12:10 UTC
