### ISSUE TITLE
Some opacity values for polygon color produce the wrong color

### ISSUE THREAD

**Issue by ficoos** [godotengine/godot#12570] opened 2017-11-01 20:59 UTC
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
SO: Linux (Fedora 27)
Version:a4ea63737 (HEAD -> master, origin/master, origin/HEAD) Ability to shrink 3D viewport by half
GPU: 01:00.0 VGA compatible controller: NVIDIA Corporation GK106 [GeForce GTX 660] (rev a1)

**Issue description:**
Tried to tween the opacity of a polygon and colors interpolated oddly
Example video.
https://youtu.be/nQClIimpnGo

**Steps to reproduce:**
Create a polygon and try and change the opacity.

**Link to minimal example project:**

**Comment by reduz** [comment] 2017-12-06 00:06
if anyone wants to check polygon.cpp, may be relatively simple

**Comment by t17dr** [comment] 2017-12-09 01:14
This also happens with colors for Line2D, CanvasModulate and probably more and only in editor, changing the alpha value in a script ingame works fine.

Changing [https://github.com/godotengine/godot/blob/2c6af835a1fa5518e95d874559bdcd90ce5cb24e/drivers/gles3/rasterizer_storage_gles3.cpp#L5975](https://github.com/godotengine/godot/blob/2c6af835a1fa5518e95d874559bdcd90ce5cb24e/drivers/gles3/rasterizer_storage_gles3.cpp#L5975) to `GL_RGBA8` "fixes" it, but I'm not sure how to properly fix it, this is above my skill level. It looks that maybe `RENDER_TARGET_TRANSPARENT` needs to be set somewhere?

Also this issue happens in https://github.com/godotengine/godot/commit/b38378dd6c963d71d0c1ad40c53b29588e581757 but not in the commit before that, so it's been reoccurring since this issue was posted.

**Comment by akien-mga** [comment] 2018-01-05 15:35
Related to #14964.

**Comment by reduz** [comment] 2018-01-12 20:36
I am confident i fixed the bug causing this yesterday via e3f02b1a1b20441b5eef3b5e2491450b1cb64377, so closing this one unless someone can reproduce it again.

**Closed by reduz** 2018-01-12 20:36 UTC
Labels: bug, hero wanted!, topic:rendering
