### ISSUE TITLE
CollisionShape3D appears to initially spawn at origin, causing a body_entered() signal to be emitted

### ISSUE THREAD

**Issue by megalobyte** [godotengine/godot#58132] opened 2022-02-15 06:57 UTC
### Godot version

d02db6306e

### System information

Arch, Vukan, X11, NVIDIA GeForce GTX 1070/PCIe/SSE2

### Issue description

Currently trying to go through the First 3D Game tutorial. Whenever a mob spawns it triggers a `body_entered` signal and cause the player to "die," even though the player is at the origin.  

This can be worked around by moving the scene away from the origin, but this broke a lot of the logic in the scripts. 

Might be related to #45598 or #45638? 

### Steps to reproduce

Run the main scene in the attached project. I've added a print statement for when the mobs collide with the player and a cylinder to indicate the origin. 

### Minimal reproduction project

[minimal_project.zip](https://github.com/godotengine/godot/files/8066382/minimal_project.zip)

**Comment by Zireael07** [comment] 2022-02-15 09:17
Duplicate of another issue (although that other IIRC mentioned mostly 2D)

**Comment by TheDuriel** [comment] 2022-02-15 13:30
@megalobyte Can you try setting the position of your enemies, then adding them to the tree afterwards. If you are not already.

**Comment by megalobyte** [comment] 2022-02-15 14:46
@TheDuriel Setting the position before adding the node to the tree did fix the problem, so this does appear to be an duplication of the issues I linked. That being said, is there an existing bug for using `set_position` prior to adding a node to the tree? I would have thought 
```
set_position(start_position)
look_at(player_position, Vector3.UP)
```
would have been equivalent to `look_at_from_position(start_position, player_position, Vector3.UP)`. Instead, using `set_position` doesn't move the node, causing the mob to spawn at the origin. Or am I just doing something wrong?

**Comment by TheDuriel** [comment] 2022-02-15 14:54
When you add a node, then change its position. The node "moves" through space. This should trigger two updates, first the node appearing at 000, then the node moving to your position.

When you set a position before adding the node, the 000 step is skipped and the node simply appears where it should be.

In this sense the behavior is correct, and as desired. Since the alternative is basically to add a whole frame of delay to the first time we check physics for a node.

**Comment by Zireael07** [comment] 2022-02-15 15:12
Whoa, you CAN set a position before adding to tree? I never realized. This should definitely be better documented.

**Comment by megalobyte** [comment] 2022-02-15 15:56
Sorry, I don't think I worded my question well. My question was more about the issues I had with setting the position of the node, prior to adding it to the tree. In my minimal project, if I use: 
```
func initialize(start_position, player_position):
    mob.set_position(start_position)
    mob.look_at(player_position, Vector3.UP)
    add_child(mob)
```
the code fails to set the mob position and it spawns at the origin, but if I use:
```
func initialize(start_position, player_position):
    mob.look_at_from_position(start_position, player_position, Vector3.UP)
    add_child(mob)
```
it successfully sets the mob position. Is this a bug with `set_position` or am I misusing it? As a novice, these two code snippets look like they should perform the same task.

**Comment by akien-mga** [comment] 2022-02-15 16:54
@megalobyte Reading the code, I'm pretty sure you should be seeing an error in the console with the `look_at` version. `look_at` calls `get_global_transform` internally, which fails if the node is not inside the scene tree. `look_at_from_position` shortcuts this so it works.

I'd say that's a bug in `look_at`, maybe it could fall back to using the local transform when not inside tree.

**Comment by megalobyte** [comment] 2022-02-15 17:56
Would it make sense to have `get_global_transform` return the local transform if not inside the tree? Or would that cause a lot of downstream issues? I'm just wondering about the use case of someone procedurally making physics objects, but not using `look_at` to set their rotation

**Comment by megalobyte** [comment] 2022-02-16 14:27
After looking at it again, this does appear to be an issue exclusive to look at. I think I'll publish a PR for consideration.

**Comment by rburing** [comment] 2022-03-13 14:57
In my view this is a documentation issue of the type described in https://github.com/godotengine/godot/issues/45638. In order for the physics server to do its job normally (not requiring a workaround), the mob node's transform should be set to a reasonable value *before* adding the mob node to the scene tree. Having the mob's position set to the origin (the default) when adding it to the scene tree is not reasonable here because that's where the player starts, hence causing collision issues in the physics server (as reported). So, the tutorial should be updated.

The question becomes: who is responsible for setting the mob's transform? It can be done entirely in the spawner, or the spawner can call a method on the mob (before adding the mob to the scene tree) which sets the transform, or it can be a mixture of both.

The minimal change to the tutorial would be to swap the last two lines in the `_on_MobTimer_timeout` method, making them:
```
    mob.initialize(mob_spawn_location.translation, player_position)
    add_child(mob)
```
and replacing the first two lines of the mob's `initialize` method with
```
    look_at_from_position(start_pos, player_pos)
```
as suggested by @megalobyte. The importance of initializing before adding to the scene tree could be stressed in the tutorial.

In general (outside the current tutorial), spawning may sometimes be more complicated. One may have to deal with more transformations between coordinate systems (can be done e.g. using `to_local` / `to_global` in the spawner code) to set the initial transform correctly, and one may have to deal with more possible collisions. Already in the tutorial project one can see the other possible issue: setting the mob's speed too low compared to the wait time of the mob timer will cause the spawner to spawn mobs on top of each other, again resulting in collision issues.

**Closed** 2022-04-29 09:47 UTC
Labels: bug, topic:physics, topic:3d
