### ISSUE TITLE
If a Node2D is enclosed in a bigger Sprite rect it's not possible to select it

### ISSUE THREAD

**Issue by mrcdk** [godotengine/godot#18203] opened 2018-04-14 19:44 UTC
**Godot version:**

Godot master e7445c3

**OS/device including version:**

Win 10

**Issue description:**

If a Node2D is enclosed in a bigger sprite rect it's not possible to select it if the sprite is selected. It's possible if you try to select it in the transparent areas of the bigger sprite. The tree order doesn't seem to matter.

**Steps to reproduce:**
![https://i.imgur.com/4G5HCU1.gifv](https://i.imgur.com/4G5HCU1.gif)

https://i.imgur.com/e6lwiay.gifv (github doesn't let me inline it)

**Comment by groud** [comment] 2018-04-15 07:48
Probably a duplicate of #18128

**Comment by groud** [comment] 2018-04-15 09:49
> Probably a duplicate of #18128 

Checking again on my PC, yes, it is a duplicate.

**Closed by groud** 2018-04-15 09:49 UTC
