### ISSUE TITLE
The mouse gets locked when dragging a number field

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#9890] opened 2017-07-26 23:16 UTC
Godot 3.0 alpha1 official
Windows 10 64 bits

I dragged the bloom intensity property, and my mouse got immediately stuck at the middle of the screen. It started to warp there showing a red icon, then it disappeared when I released the button. I tabbed out of Godot, then focused it again, and I could see my mouse warping at the center everytime I try to move it.
Then I was able to get back the mouse by clicking again.

Note 1: dragging didn't affect the property at all, it took the first "pixel" of movement (going from 1.0 to 1.1) but not more.

Note 2: it seems it doen't happen all the time.

Looks like another occurence of #7098.

**Comment by reduz** [comment] 2017-11-06 15:12
First, not sure if this still happens and can be reproduced.
In case it stil happens, this is the range drag function, all logic is here:
https://github.com/godotengine/godot/blob/master/scene/gui/tree.cpp#L2401

**Comment by NathanWarden** [comment] 2017-11-09 23:46
@paezao I can't reproduce it here, but so you can also check, the Bloom slider is in an environment resource, which you can get by adding one to a spatial Camera. Open up and enable the Glow setting, the bloom slider is under there.

Steps:
Add a spatial Camera
Create an environment resource on it
Unfold the Glow settings
Check Enabled
Bloom slider is under there :)

**Comment by passeride** [comment] 2017-12-07 19:10
Managed to reproduce if alt-tab(to fullscreen so mouse-drop does not take focus back to Godot) while dragging.  
Had this issue come up during use earlier.

**Comment by akien-mga** [comment] 2018-01-09 16:23
We have now entered release freeze for Godot 3.0 and want to focus only on release critical issues for that milestone. Therefore, we're moving this issue to the 3.1 milestone, though a fix may be made available for a 3.0.x maintenance release after it has been tested in the master branch during 3.1 development. If you consider that this issue is critical enough to warrant blocking the 3.0 release until fixed, please comment so that we can assess it more in-depth.

**Comment by guilhermefelipecgs** [comment] 2018-01-15 12:52
This bug also occurs if you press middle mouse button to start rotating the 3d camera of the viewport and then pressing the right mouse button. You can use the same steps with drag button, pressing left button, start dragging and then press the right button.

**Comment by Zylann** [comment] 2018-01-15 13:01
@guilhermefelipecgs this is a different issue #14373, it's because freelook triggers but doesn't stops because Godot doesn't sends mouse button release events

**Comment by guilhermefelipecgs** [comment] 2018-01-15 13:07
@Zylann cool, I hadn't seen this PR.

**Comment by P1llus** [comment] 2018-03-02 19:59
Confirmed this still happens on the newest release for this date. This happen when dragging and dropping assets (pngs) unto SpriteFrame window. Though it happens on drag n drop in general.

**Comment by guilhermefelipecgs** [comment] 2018-06-05 20:12
I found a way to reproduce this.
Demo: [demo_grab_bug.zip](https://github.com/godotengine/godot/files/2073823/demo_grab_bug.zip)
Click in ScrollContainer and grab margin.
Tested with: 4ea88aab4d3ac29f13a9ca9a36a23b5bc8434a2f
![out mp4](https://user-images.githubusercontent.com/1387165/41000087-3ec76676-68e3-11e8-8884-ccd20be770f9.gif)

**Comment by guilhermefelipecgs** [comment] 2018-06-08 22:10
I realized now that I've already fixed the problem I reported https://github.com/godotengine/godot/issues/9890#issuecomment-394844248 unintentionally on this pr #19351.

**Closed** 2018-07-05 01:50 UTC
Labels: bug, hero wanted!, topic:core, topic:editor
