### ISSUE TITLE
Missing resource file types

### ISSUE THREAD

**Issue by vonflyhighace2** [godotengine/godot#21175] opened 2018-08-19 04:29 UTC
**Godot version:**
Godot 3.0.6

**OS/device including version:**
Windows 10 x64

**Issue description:**
some resource types are missing when trying to load certain files.

**Steps to reproduce:**
have an array property on a script that is exported and can be populated. then got to array -> indices->object->load, and in the supported file types that popups up, .tscn is not on the list. there might be others as well. I also believe .tex is still used even though .texture is what is proposed...or am I missing something here?

**Minimal reproduction project:**

**Comment by clayjohn** [comment] 2019-04-20 05:21
Can this be reproduced in 3.1?

**Comment by KoBeWi** [comment] 2020-07-16 16:07
Duplicate of #7278

**Closed by KoBeWi** 2020-07-16 16:07 UTC
Labels: bug, topic:editor
