### ISSUE TITLE
VisualScript Property Selector sometimes oversize's the EditorHelpBit

### ISSUE THREAD

**Issue by Gallilus** [godotengine/godot#60296] opened 2022-04-16 09:22 UTC
### Godot version

4.0.dev

### System information

Windows 10

### Issue description

As seen below the help text oversizes and is not implementing a scrollbar.

![oversized_EditorHelpBit](https://user-images.githubusercontent.com/20573784/163669116-a1dab4cf-10a9-41c2-b02f-7b3a3e81993d.gif)

https://github.com/godotengine/godot/blob/50bb1846d0f16fae929b2ae99824dbf90be25c92/modules/visual_script/editor/visual_script_property_selector.h#L97

https://github.com/godotengine/godot/blob/50bb1846d0f16fae929b2ae99824dbf90be25c92/modules/visual_script/editor/visual_script_property_selector.cpp#L522-L524

It looks like a good first issue.
1 Wy is `EditorHelpBit` witch is a `RichTextLabel` not giving a scrollbar?
2 Also maybe play with the min, max higt of the `results_tree` and `help_bit`.

### Steps to reproduce

Open any VisualScipt that extends Node (Change Base Type)
RMB click anywhere in the VS script editor search get_node

**Comment by Calinou** [comment] 2022-04-16 11:00
>  1 Wy is EditorHelpBit witch is a RichTextLabel not giving a scrollbar?

EditorHelpBit is designed to be used in tooltips, which cannot be scrolled by design.

**Comment by derammo** [comment] 2022-05-17 15:00
@Calinou I believe this is dupe of #58121, which I have fixed by adding a scroller around it in #61113 ?

**Comment by akien-mga** [comment] 2022-05-17 20:00
Duplicate of #58121.

**Closed by akien-mga** 2022-05-17 20:00 UTC
Labels: bug, topic:editor, topic:visualscript
