### ISSUE TITLE
Vulkan: engine crash when assigning CanvasTexture to Light2D

### ISSUE THREAD

**Issue by bitbrain** [godotengine/godot#70703] opened 2022-12-29 12:05 UTC
### Godot version

4.0beta 10

### System information

MacOS, Vulkan Forward, Metal GPUFamily Apple 7

### Issue description

Godot crashes when I attempt to assign a `CanvasTexture` to a `Light2D` (Vulkan)
```
================================================================
handle_crash: Program crashed with signal 11
Engine version: Godot Engine v4.0.beta.custom_build (7e1bd3f95a10acf60e07a8a6518cc80bfee6fbbf)
Dumping the backtrace. Please include this when reporting the bug to the project developer.
[1] 1   libsystem_platform.dylib            0x00007ff80d0dedfd _sigtramp + 29
[2] 2   libsystem_malloc.dylib              0x00007ff84e7fc000 virtual_default_zone + 0
[3] 3   libsystem_c.dylib                   0x00007ff80cfa5b57 __sflush + 98
[4] 4   libsystem_c.dylib                   0x00007ff80cfa7df7 __xvprintf + 392
[5] 5   ???                                 0x0000000400000000 0x0 + 17179869184
[6] 6   ???                                 0x0000000314cc0638 0x0 + 13233817144
-- END OF BACKTRACE --
================================================================
```
[crash.txt](https://github.com/godotengine/godot/files/10319352/crash.txt)

### Steps to reproduce

1. create `Light2D`
2. assign `CanvasTexture`

### Minimal reproduction project

[light-crash.zip](https://github.com/godotengine/godot/files/10319346/light-crash.zip)

**Comment by XReaper95** [comment] 2023-01-02 19:04
This is the same problem I reported here #69692

**Comment by Calinou** [comment] 2023-01-02 19:19
Duplicate of https://github.com/godotengine/godot/issues/69692.

**Closed by Calinou** 2023-01-02 19:19 UTC
Labels: bug, topic:rendering, crash, topic:2d
