### ISSUE TITLE
Nodes get duplicated when saving a scene with PackedScene.pack() that has the option editable children activated

### ISSUE THREAD

**Issue by MrBSmith** [godotengine/godot#51956] opened 2021-08-21 17:16 UTC
### Godot version

3.3.stable

### System information

Windows 10

### Issue description

I'm working on an in game map editor, and I have a scene map where is another scene called Layer that has multiple Tilemap nodes as children and has the option editable children activated.

it looks like that:
![image](https://user-images.githubusercontent.com/34774144/130328625-e16a18e7-d2c6-4626-b657-2c73586e736e.png)

When I Save the map scene at its original location using PackedScene.pack() then ResourceSaver.save(); I get all the children of my Layer node duplicated.

And then it looks like that
![image](https://user-images.githubusercontent.com/34774144/130328613-c48f52cf-06a1-4bc5-a662-2d2b8e2cd57c.png)

### Steps to reproduce

- Create a scene called Map with an instance of an other scene called Layer in it that as a tilemap as a child.
- Activate editable_children on the instance of the Layer scene in the map
- Save the map scene at runtime using: PackedScene.pack() then ResourceSaver.save()
- Close the game, load the scene in the editor: it sould have two tilemaps as a child

### Minimal reproduction project

Launch the game from the editor, press enter to save the scene, then leave the game: the bug should appear in the editor.

[TestEditableChildren.zip](https://github.com/godotengine/godot/files/7025902/TestEditableChildren.zip)

**Comment by Calinou** [comment] 2021-08-21 19:44
Duplicate of https://github.com/godotengine/godot/issues/49660.

**Closed by Calinou** 2021-08-21 19:44 UTC
