### ISSUE TITLE
user:// doesn't work in exported game

### ISSUE THREAD

**Issue by kowww** [godotengine/godot#16120] opened 2018-01-27 19:30 UTC
**Godot version:**
Godot 3rc3

**OS/device including version:**
Windows 8.1

**Issue description:**
Using `user://` in a path with an exported game doesn't do anything, with both writing and reading.
I suspect this has to to with the `res://user/` path used in the editor.
Using `OS.get_user_data_dir()` works only in the exported game, and not in the editor.

**Steps to reproduce:**
- Create a `_File` in the `ready()` function;
- Open the file with a path that starts with `user://`;
- Write the file;
- Export the game;
- Look at the folder, or try reading the file.

**Minimal reproduction project:**
[user_bug_minimal.zip](https://github.com/godotengine/godot/files/1670450/user_bug_minimal.zip)

**Comment by vnen** [comment] 2018-01-27 19:43
Works fine for me on Windows. The file is where it should be, and it's read and written without issues.

![user_path_2018-01-27_17-41-55](https://user-images.githubusercontent.com/5599796/35475661-843b1e24-0389-11e8-8e2d-427333d78355.png)

**Comment by Sslaxx** [comment] 2018-01-28 00:15
@vnen - Win10?

`~/.local/share/godot/app_userdata/user\ bug\ minimal/test.txt` exists here (Linux).

There had been issues with user:// reported quite a while back (2.0 days I believe?) that (I had thought) is fixed now. It was to do with linking. #6047 - this doesn't appear to be that issue, as no symlinks are involved, though it may be related.

What does `print (OS.get_user_data_dir())` give you?

**Comment by kowww** [comment] 2018-01-28 13:16
`print(OS.get_user_data_dir())` gives me the correct directory, `C:/Users/USERNAME/AppData/Roaming/Godot/app_userdata/PROJECT NAME` if I'm not using the custom user dir and `C:/Users/USERNAME/AppData/Roaming/PROJECT NAME` if I'm using it.
I tried doing the same thing for different projects and I noticed that some create a `res://user` folder while in the editor and some don't. The problem is present only in those that do.
I think the problem is that the game tries to go the `res://user` folder, but since the game is exported, it can't write there. `OS.get_user_data_dir()` always points at the correct path.

**Comment by Sslaxx** [comment] 2018-01-28 13:24
It's creating `res://user/`? Should that not be just `user://`? Or am I misunderstanding something.

**Comment by Zireael07** [comment] 2018-01-28 13:28
@Sslaxx: I understood that the search for user:// fails if he has a res://user folder (i.e. if he has a user folder in his project)

**Comment by kowww** [comment] 2018-01-29 11:25
I'm sorry for being unclear.

What I meant is that some projects create a `res://user/` folder and use that instead of the normal path for `user://` (`C:/Users/USERNAME/AppData/Roaming/` in Windows).
Deleting the folder only causes it to be recreated and reused.
I don't know what is determining whether the folder is created and used or not.

I think the cause of the issue is that the game tries to look at the `res://user/` folder even when the game is exported, but since everything is packed, it fails.
This, of course, doesn't happen for the projects that work properly and use the regular `user://` path.

**Comment by vnen** [comment] 2018-01-29 14:30
Tagging as bug for now, but still can't reproduce with the sample project. @kowww Does it happen to you with this sample or only with your project? Maybe some of your `user://` paths has typo (e.g. you typed `user//` instead).

>  Also, try running Godot with admin privileges and see what happens

**Comment by Ranoller** [comment] 2018-02-19 12:42
This make my headache, but i probably find the "root" of the problem. If you see OS_windows.cpp:

`String OS_Windows::get_user_data_dir() const {

	String appname = get_safe_dir_name(ProjectSettings::get_singleton()->get("application/config/name"));
	if (appname != "") {
		bool use_custom_dir = ProjectSettings::get_singleton()->get("application/config/use_custom_user_dir");
		if (use_custom_dir) {
			String custom_dir = get_safe_dir_name(ProjectSettings::get_singleton()->get("application/config/custom_user_dir_name"), true);
			if (custom_dir == "") {
				custom_dir = appname;
			}
			return get_data_path().plus_file(custom_dir).replace("\\", "/");
		} else {
			return get_data_path().plus_file(get_godot_dir_name()).plus_file("app_userdata").plus_file(appname).replace("\\", "/");
		}
	}

	return ProjectSettings::get_singleton()->get_resource_path();`

It search for project name. If project doesn´t have name, this method uses res:// like user:// (In my opinion a mistake, but....). So probably your problem is solved giving name to the project.

This should be very very very good documented. Because this can be a recurrent problem. (Or godot can   do a default folder with the original folder name like do in 2.1

But i suspice of a bug here:
`String OS_Windows::get_godot_dir_name() const {

	return String(VERSION_SHORT_NAME).capitalize();
}
`
It seems strange, it ask for the dir name and return a constant with version. I don´t know c++ nor godot internals, but i see that rare...

**Comment by Ranoller** [comment] 2018-02-19 12:45
So for confirm bug it should be tested in projects without name... (I can confirm bug, not in demos because has name)

**Comment by akien-mga** [comment] 2018-02-19 12:49
Well that's not a bug, if your project has no name, there's no way to create a `user://` folder for it. What should it be?

>  It seems strange, it ask for the dir name and return a constant with version. I don´t know c++ nor godot internals, but i see that rare...

That's not a bug, it returns "Godot" (`VERSION_SHORT_NAME` is `godot`). `get_data_path().plus_file(get_godot_dir_name())` thus allows to get `%APPDATA%/Godot` on Windows and `~/.local/share/godot` on Linux.

**Comment by akien-mga** [comment] 2018-02-19 12:52
> So for confirm bug it should be tested in projects without name... 

And actually that's not what this bug here is about, as the attached project has:
```
config/name="user bug minimal"
```

**Comment by Ranoller** [comment] 2018-02-19 13:04
Thanks for the clarifications.... I can´t reproduce with attached project in Windows 7 32 bit. I try export in release and release_debug. Both creates folder in user:// and make the file. OS.get_user_data_dir() works in editor (if project have name). So probably windows 8.1 especific thing (or fixed in newer releases). I´m using Godot 3 compiled at 18/02.

**Comment by akien-mga** [comment] 2018-02-19 13:09
But @Ranoller linked the correct logic that determines the `user://` location, but it can't explain the symptom we have here (`user://` in `res://user`)..

@kowww Can you reproduce the issue with the project you attached in the OP? If not, can you attach another project that does reproduce it?

It would be interesting to know:
- The output of `OS.get_user_data_dir()`
- The actual `user://something` string that you are using
- The output of `ProjectSettings.globalize_path()` on that string
- Try with project names not starting with `"user ", as it's needlessly complicating debugging, since we don't know if that `res://user` comes from a bad globalization of `user://`, or comes from a bad creation of a `"res://user bug minimal"` folder.

**Comment by Calinou** [comment] 2020-06-01 10:15
Closing in favor of #36781, which has more information about the issue at hand.

**Closed by Calinou** 2020-06-01 10:15 UTC
Labels: bug, topic:core
