### ISSUE TITLE
Project Manager issue

### ISSUE THREAD

**Issue by 0nepixel** [godotengine/godot#21986] opened 2018-09-11 19:59 UTC
If you change something on Editor's settings, like the Display Scale, you have to restart Godot, nothing wrong whit that, but when Godot get restarted the project manager is restarted too, so you have to import all your projects again, i dunno if this is a bug or what, but is annoying .
1- Go to editor settings, change something and restart Godot

O.S Windows 7 64 bits
Godot 3.1 alpha 
Edit: After all this has nothing to do with the Editor Settings, if you close and open Godot, the editor maganer will not save your projects dirs -_-

**Comment by romlok** [comment] 2018-09-11 22:28
This sounds like the same issue as #21823, a fix for which was recently merged into the master branch with #21927.
You can try compiling the latest master if you want to make sure.

**Comment by akien-mga** [comment] 2018-09-11 23:34
Duplicate of #21823.

**Closed by akien-mga** 2018-09-11 23:34 UTC
