### ISSUE TITLE
Allow to search in built-in scripts

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#20692] opened 2018-08-03 15:28 UTC
So there's this new Find in files option (probably introduced in 3.1, didn't see it before).
![image](https://user-images.githubusercontent.com/2223172/43651149-e37960fc-9741-11e8-8aa0-3d1d269df77f.png)
However, it's missing one thing. It doesn't allow to search in built-in scripts. I know they are embedded in scene files, so it should be enough to just add .tscn extension to the list of filters. Or if the list would be somehow configurable, it could work as general purpose grep e.g. for .txt and .json files.

But at least simply adding .tscn filter would be enough and appreciated.

**Comment by akien-mga** [comment] 2018-08-13 10:56
CC @Zylann

**Comment by Zylann** [comment] 2018-08-13 11:33
I thought of that already, and the problem is, even if I added `.tscn` in filters, it would be very difficult to find out if the matched text actually is in a script, and then open the script properly without slowing the search down. There can be multiple ones in the scene and to find it out it requires parsing the `.tscn` partially to go back up to the resource ID declaration, load the scene and figure out somehow where it is.

A variant of this would be: if an occurence happens in a `.tscn`, load it, then parse it entirely by looking only at built-in scripts and then open them.

**Comment by Jummit** [comment] 2019-04-30 16:42
Any update on this? It hasn't been assigned to a milestone, which makes me wonder if it is ever gonna be implemented.

**Comment by Zylann** [comment] 2019-04-30 17:15
This could be doable like I specified above, but I think it would need to be optional because searching all text resources (.tscn and .tres) in addition to all scripts will make it a lot slower.
And if you use `.scn` and `.res` (which are not text-based), the search will be even more slower because it will have to LOAD all scenes and resources of the project to perform the search.

**Comment by Jummit** [comment] 2019-04-30 20:24
How about only searching in the files opened in the script editor sidebar? Sure, it wouldn't be as usefull (for example, if I have a stray print somewhere and can't find it), but it would be a step forward,

**Comment by KoBeWi** [comment] 2019-04-30 20:34
For me, adding a .tscn extension as possible filter would be enough (I actually said that in OP...). Yeah, it's a bit inconvenient that you search inside whole scene file not just the script, but if you know what you are looking for, it's not really a problem and still helps.

Oh and as for

> As for extending it for txt or json, it's doable, but we need the script editor to be able to open them to be a complete feature.

it's already possible since then, AFAIK.

**Comment by Zylann** [comment] 2019-04-30 20:40
@KoBeWi so you are suggesting the search feature to consider `.tscn` as regular text files? That could work to show them in the results, but that would be it. Clicking on those results would either give you that file as raw text in the script editor which is a bit ugly (if supported?), or won't do anything at all. And it would not recognize which match was actually part of a script, as it could contain a lot of other things (or even multiple scripts).

**Comment by KoBeWi** [comment] 2019-04-30 20:46
Well, my motivation is that when I'm searching in multiple built-in scripts, I'm using an external editor just for that purpose and then open related scene when I find it. Having this option inside Godot, so I don't need to open external editor, would be better than nothing.

Actually @Jummit's option doesn't sound that bad too. With my proposal, you could just find related scene and when you know which scene it is, it's easy to open contained scripts manually. And with opened scripts you have more options to work with them.

**Comment by sparkart** [comment] 2019-08-05 11:18
#25440 seems to be a duplicate of this, which has been closed by #25647

**Comment by KoBeWi** [comment] 2019-08-06 17:07
Yeah, seems like it could close it, but it would be nice if clicking a .tscn file opened the scene >_>
![image](https://user-images.githubusercontent.com/2223172/62560462-55b72700-b87d-11e9-9d01-6d5ed88d5cce.png)
Right now it produces an error.

**Closed** 2019-08-07 09:56 UTC
Labels: enhancement, topic:editor, usability

**Comment by gnat** [comment] 2026-05-07 10:28
Solution: This is how you enable it, built-in script enjoyers rejoice.

<img width="979" height="846" alt="Image" src="https://github.com/user-attachments/assets/c36793ac-b6e1-47bf-924f-608d9aafd62c" />
