### ISSUE TITLE
Particle2D showing full texture and not region specified

### ISSUE THREAD

**Issue by chucklepie** [godotengine/godot#64671] opened 2022-08-20 21:45 UTC
### Godot version

3.4.4

### System information

PopOS

### Issue description

I have a sprite map/atlas and for a Particle2D texture I have set a region as shown below.
![image](https://user-images.githubusercontent.com/12863685/185766946-6aa58b58-5625-437f-a1ea-f4e9cc0a5487.png)

However, when the particle is emitted, it shows the full texture
![image](https://user-images.githubusercontent.com/12863685/185766937-08b4b4f6-75d1-4806-8e6b-6a7a9fcf77fe.png)

I did search for an existing one, apologies if already a bug.

### Steps to reproduce

Exactly as above really

**Comment by chucklepie** [comment] 2022-08-20 21:50
I've just checked the documentation and it says this:
Note: Unlike [CPUParticles2D](https://docs.godotengine.org/en/stable/classes/class_cpuparticles2d.html#class-cpuparticles2d), Particles2D currently ignore the texture region defined in [AtlasTexture](https://docs.godotengine.org/en/stable/classes/class_atlastexture.html#class-atlastexture)s.

So is this why? If so, two questions:

1. Why is the setting still in the properties and no hint given when it's known it is a particle2D and not a cpu particle?
2. Is this a limitation of OGL or just a bug/feature not implemented in Godot?

**Comment by KoBeWi** [comment] 2022-08-20 22:34
Duplicate of #13923
> Is this a limitation of OGL or just a bug/feature not implemented in Godot?

AtlasTexture is just a wrapper for the texture on GPU. Most nodes draw textures using the regular texture draw function, which handles AtlasTexture in a specific way, but GPU particles work differently. You e.g. need a special material to use animations, so not sure if handling atlases in particles is possible. It would need to be done explicitly in the shader.

**Closed by KoBeWi** 2022-08-20 22:34 UTC

**Comment by chucklepie** [comment] 2022-08-21 18:29
@KoBeWi 
Ok (sorry, I replied by email, maybe it didn't arrive). If this doesn't work as expected how come the IDE lets you happily do it and the hints provide no indication either. Should this facility be disabled or at a least a tooltip hint provided (there is none) that at least tells people atlas textures don't work for particle2D?

**Comment by KoBeWi** [comment] 2022-08-21 18:55
> Should this facility be disabled or at a least a tooltip hint provided (there is none) that at least tells people atlas textures don't work for particle2D?

Makes sense.

**Comment by chucklepie** [comment] 2022-10-11 08:24
Ok, thanks. So why does Godot allow us normal folk to believe it's all fine
to use them and no help shown in the gui. Could this be added?
