### ISSUE TITLE
SkeletonIK does not work with scaled object

### ISSUE THREAD

**Issue by MrCrowley2** [godotengine/godot#25544] opened 2019-02-01 13:22 UTC
**Godot version:**
3.1 Beta 3

**OS/device including version:**
Kubuntu 18.04

**Issue description:**
When I scale my Scene that contains the rigged mesh, IK_Target and SkeletonIK nodes, the IK chain is not working properly anymore

**Steps to reproduce:**
- create working SkeletonIK model
- scale parent node down
- the tip of the IK scene will get scaled twice, once from the parent node and once from the Position3D that is scaled by the parent node
- the location data of the Position3D target doesn't seem affected by the scale. I have to move it where it would have been in the unscaled scene to get the proper orientation of the IK chain

edit: this also happens when only the armature is scaled and the Target is outside of the scaled armature. Position of the IK chain is still wrong, even though the tip of the chain remains unscaled this time.

**Minimal reproduction project:**
[SkeletonIK_scale_bug.zip](https://github.com/godotengine/godot/files/2821691/SkeletonIK_scale_bug.zip)

using the model from 3d in 2d demo
- when the scene is loaded, select SkeletonIK and Press play IK
- the foot will get scaled down to a very tiny size
- leg/foot won't point to the Position3D, you have to make very big movements to animate it

- reset scaling of root Spatial node from 0.1 to 1
- IK chain works as expected

**Comment by Zireael07** [comment] 2019-05-21 17:48
Just ran into the same issue in Godot 3.1.1.

**Comment by Zireael07** [comment] 2019-05-22 14:44
@AndreaCatania

**Comment by akien-mga** [comment] 2020-01-13 12:43
Is this still reproducible in the current master branch / latest 3.2 builds?

I'm not very familiar with SkeletonIK to assess the issue in OP, but the provided project seems to run the same regardless of the scale for me.

**Comment by Zireael07** [comment] 2020-01-13 12:49
Not OP and can't check because I rescaled the model to 1,1,1 (and don't have Godot installed atm)

**Comment by FrenchKrab** [comment] 2020-02-06 09:58
The bug is still easily reproducible, I think any setup with a SkeletonIK node will glitch if the armature is rescaled.
It seems that the SkeletonIK doesn't take the Skeleton size in its calculations and always assume it is scaled with a 1.0 size.
Using the (strange) example provided by the OP, I setup the position to bend the leg this way (the foot is at the same position as the Position3D, as desired) :
![Godot_v3 2-rc3_win64_61yPdCI8ON](https://user-images.githubusercontent.com/14005967/73925692-b7108f00-48ce-11ea-8a18-55e2b9f33794.png)

Now if I rescale the armature to (0.1, 0.1, 0.1), the IK does not adapt. It acts as if the armature still was (1.0, 1.0, 1.0) and keep the same position:
![Godot_v3 2-rc3_win64_2pm7CfGBbK](https://user-images.githubusercontent.com/14005967/73925699-baa41600-48ce-11ea-9bcc-e1fbb9e487f0.png)

In this case the target (Position3D) is in the top left corner of the screen, the leg should be fully extend and pointing toward the target.

**Comment by barbaros83** [comment] 2020-06-23 17:30
this is still a problem in 3.2.1 and 3.2.2 beta's

**Comment by barbaros83** [comment] 2020-06-23 17:33
as soon as anything in the scene gets scaled, the skeletonIK bugs out, the tip looks like it scales and is doesnt go towards the target position, when the scaling is larger then 1 it makes the tip bigger and when its smaller makes the tip smaller, could probly be an issue with the transform that the skeletonIK sets for the bones, wich should apply a scaling to it, but it does

**Comment by TwistedTwigleg** [comment] 2020-06-23 19:29
I can probably fix this. It *should* just be matter of taking the scale of the Skeleton into account when solving the FABRIK chain. I'll try to take a look soon :+1:

**Comment by akien-mga** [comment] 2020-07-06 14:17
Fixed by #39803.

**Closed by akien-mga** 2020-07-06 14:17 UTC
Labels: bug, topic:core
