### ISSUE TITLE
2D IK chain doesn't work any more

### ISSUE THREAD

**Issue by razvanc-r** [godotengine/godot#10767] opened 2017-08-29 19:24 UTC
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Ubuntu 17.04 - Godot v3.0.alpha.custom_build.3ae1cff

IK chains seem not to function any longer. Check project

[godot-dbg.zip](https://github.com/godotengine/godot/files/1261483/godot-dbg.zip)

**Comment by novemberist** [comment] 2017-08-29 20:29
I think we will have to wait until 3.1 for IK to make a comeback as stated in: https://github.com/godotengine/godot/commit/56195873b6f6e84fdaa1c0e98ab9abaee72be9ac

**Comment by razvanc-r** [comment] 2017-08-29 21:02
Alright, makes sense.

**Comment by groud** [comment] 2017-08-29 21:07
no no keep this open !

**Comment by groud** [comment] 2017-08-29 21:34
Oh ok, I probably did not break anything then ^^

**Comment by reduz** [comment] 2017-08-29 21:48
No, that was for 3d. If this is not working it's a bug..

**Comment by groud** [comment] 2017-08-29 21:49
Are we talking about 2d or 3d here then ?

**Comment by novemberist** [comment] 2017-08-29 23:24
2D, so this issue should probably be re-opened

**Comment by toby3d** [comment] 2017-08-30 18:56
I think this looks same as #9548 issue.

**Comment by reduz** [comment] 2017-09-07 01:53
@groud Did you have any time to look at this? Otherwise let me know and I could give it a try

**Comment by groud** [comment] 2017-09-07 08:08
@reduz Unfortunatly no. I just had a look to my commits into master, it doesn't look like I introduced the issue. The issue might be old then.

**Comment by groud** [comment] 2017-10-05 09:22
@reduz: seems like someone overtook you: #11846 ;)

**Comment by groud** [comment] 2017-10-05 10:23
I close this one as a duplicate of #9548.

**Closed by groud** 2017-10-05 10:23 UTC
Labels: bug, topic:physics
