### ISSUE TITLE
Reopen all scenes that were open last run

### ISSUE THREAD

**Issue by captainwasabi** [godotengine/godot#4220] opened 2016-04-03 15:26 UTC
**Operating system or device:**

**Issue description** (what happened, and what was expected):
When opening a project it would be nice if the editor re-opened all the scenes that were open previously.  It only opens the $main_scene.

**Steps to reproduce:**

**Link to minimal example project** (optional but very welcome):

**Comment by neikeq** [comment] 2016-04-03 15:33
@akien-mga This request is included in #3333, but IMO it's better as a separated issue.

**Comment by AlexHolly** [comment] 2016-04-04 14:59
#2385

**Comment by neikeq** [comment] 2016-04-04 15:12
Closing it then, as it's a duplicate of #2385

**Closed by neikeq** 2016-04-04 15:12 UTC
Labels: feature proposal, topic:editor
