### ISSUE TITLE
Canvas editor steals alt and ctrl+f action from script editor

### ISSUE THREAD

**Issue by SleepProgger** [godotengine/godot#34500] opened 2019-12-21 00:37 UTC
**Godot version:**
3.1.2.stable.official

**OS/device including version:**
Manjaro with kernel 5.4.2 and XFCE

**Issue description:**
When the code editor AND the shader editor are open pressing `alt` to move lines or `ctrl+f` to search are running in the shader editor window. 
Even when the code editor has the focus.

**Steps to reproduce:**
Open script tab and a non visual shader.
Click into script editor to give it focus.
Press `ctrl+f`.

**Comment by KoBeWi** [comment] 2019-12-21 01:22
Duplicate of #21592

**Closed by KoBeWi** 2019-12-21 01:22 UTC
