### ISSUE TITLE
Will Godot open plain text files with the script editor?

### ISSUE THREAD

**Issue by vmpajares** [godotengine/godot#8284] opened 2017-04-06 11:21 UTC
**Operating system or device - Godot version:** 
Windows 7 and LinuxMint Debian Edition. Godot 2.1.2

**Issue description:**
If you try to open a plain text file in Godot script Editor, it can't. Doesn't show any error message, but if you open Godot from the terminal, it says: 

> ERROR: load: No loader found for resource: res://scenes/intro-game/bad_bamboo.esc
>    At: core/io/resource_loader.cpp:218.

Searching about the issue, I found this in the official documentation (http://docs.godotengine.org/en/stable/tutorials/making_plugins.html): 

> Godot is not able (yet) to open text files besides scripts, so this must be done in an external editor.

Is this going to be supported in the future?
My main problem with this is that I want to edit Escoria ESC files inside Godot, so I don't need to go to a different editor, search routes to save/open, etc... And if I'm going to work in a syntax highlighting for ESC files, putting it in the internal godot editor looks like the best option.

**Comment by bojidar-bg** [comment] 2017-04-06 11:35
Duplicate of #1390.

(and to avoid 8254 type of scenarios, yes, it would be supported in the future, hopefully 3.0)

**Closed by bojidar-bg** 2017-04-06 11:35 UTC

**Comment by vmpajares** [comment] 2017-04-06 12:05
Thanks :)
