### ISSUE TITLE
Gdscript function names broken for android build

### ISSUE THREAD

**Issue by theblockhouse** [godotengine/godot#30015] opened 2019-06-23 21:14 UTC
Godot 3.1 stable and Godot 3.1.1 maintenance build.

Not sure if my project is somehow corrupt, but GDScript functions have different names for android than in the editor. For example using random_range(a,b) from the editor works and once exported to android I get this error:

var rand = rand_range(0,2)

**SCRIPT ERROR**: Parse Error: Too many arguments for 'deg2rad' intrinsic function.

and it has no real order to it if I change it to deg2rad it will be some other GDScript function name, so basically the names are broken for my export templates. They also change from time to time where functions that I'm substituting no longer work after making changes to the game.

I'm using Google Play Games Services and Admob.

**Comment by KoBeWi** [comment] 2019-06-23 21:30
Any simple reproduction project?

**Comment by bruvzg** [comment] 2019-06-23 21:51
Make sure you are using export template and editor built form the same version of the source code, compiled GDScript is binary incompatible between versions and there's no proper check of bytecode version ([there is some kind of check](https://github.com/godotengine/godot/blob/3.1.1-stable/modules/gdscript/gdscript_tokenizer.cpp#L1166), but it should be exact match instead and no one bother to update bytecode version when making breaking changes to GDScript).

Try exporting with plain text GDScript (Change `GDScript export mode` to `Text` in the `Scipt` tab of `Export` dialog), if this error persists it's probably not related to bytecode version.

**Comment by theblockhouse** [comment] 2019-06-23 21:59
I'm pretty sure I clicked "runnable" off then back on and now it's working fine can't think of anything else I changed.

**Comment by Calinou** [comment] 2019-11-14 16:37
Closing, since it seems the issue has been resolved by OP. Please comment if you can still reproduce this on 3.2beta1 or later.

**Closed by Calinou** 2019-11-14 16:37 UTC
Labels: bug, platform:android, topic:porting
