### ISSUE TITLE
"Remove missing" button - removes all projects instead only the projects with missing dependencies

### ISSUE THREAD

**Issue by Chaosus** [godotengine/godot#28562] opened 2019-05-01 10:17 UTC
**Godot version:**
f3eafcec1a2eae021114fa12bd304668b9198af5

**OS/device including version:**
Win10

**Issue description:**
Also, the button is visible and clickable even when there is no projects with missing dependencies exist

**Comment by akien-mga** [comment] 2019-05-01 10:23
Follow-up to #25713, CC @qarmin.

**Comment by qarmin** [comment] 2019-05-01 10:24
Can't reproduce on Ubuntu 19.
Did you have a projects with name which show "Unicode error" to terminal? If yes, this may be duplicate of this issue #28445
Will something be removed if you press this button?

**Comment by Chaosus** [comment] 2019-05-01 10:28
![bug](https://user-images.githubusercontent.com/3036176/57013612-01b0fc80-6c15-11e9-8296-cd3dfe32b337.gif)

**Comment by Chaosus** [comment] 2019-05-01 10:31
> Can't reproduce on Ubuntu 19.

Then it's probably a Windows10 issue

**Closed** 2019-05-01 13:08 UTC
Labels: bug, platform:windows, topic:editor
