### ISSUE TITLE
Mapping both button and axis inputs to an action causes erratic behaviour with the action

### ISSUE THREAD

**Issue by mellodoot** [godotengine/godot#72255] opened 2023-01-28 14:31 UTC
### Godot version

4.0.beta16

### System information

Windows 10

### Issue description

in my input map, I have five main actions defined- up, down, left, right, and jump.

all but jump are bound to my WASD keys, and joypad axis 0 and 1 (left joystick horizontal and vertical). jump is bound to space and joypad button 0.

any actions (such as jump) exclusively bound to button inputs work as intended, but actions that mix button and axis inputs behave unpredictably and erratically. i.e., sometimes my move inputs only trigger as if I held down the key in a text input, sometimes they just won't register at all, and joystick inputs (when they do work) don't react as expected (full-right records as ~0.7 in input vectors, full-left records at ~-0.1)

actions return to full stability after removing either the button or axis inputs, effectively meaning I cannot simultaneously use analog controller and keyboard input without creating new actions for each category.

### Steps to reproduce

1. define an action of some sort (in my case, one for each movement axis)
2. bind this action to a keyboard button input and a joypad axis input (i.e., W and joypad axis 1 -)
3. pull this action in a script using something like `Input.get_vector()` or `Input.get_axis()`
4. run the project
5. see if it works??

### Minimal reproduction project

the following project features a simple 3d scene and a pill character on a plane. I use the template CharacterBody3D movement script, modified to "respawn" the player if they fall out of the map.

[input_bug_demo.zip](https://github.com/godotengine/godot/files/10527467/input_bug_demo.zip)

**Comment by Zireael07** [comment] 2023-01-28 14:45
duplicate of #45628

**Closed** 2023-01-28 15:06 UTC
