### ISSUE TITLE
MultiplayerPeerExtension is missing required virtual function declarations in 4.0.3 RC 1

### ISSUE THREAD

**Issue by Nosliwnayr** [godotengine/godot#76937] opened 2023-05-11 04:22 UTC
### Godot version

4.0.3 RC1

### System information

Fedora Linux, NVidia 1650

### Issue description

I'm working on using godot-cpp to hook up a different networking library by overriding MultiplayerPeerExtension. After extending the class and overriding all the available virtual functions, I got an error saying that I was missing required virtual function overrides for _get_packet_channel and _get_packet_mode, but those functions don't exist in the generated headers so I can't override them.
I noticed that the 4.1 dev 2 build doesn't have this problem, and I _think_ that this change https://github.com/godotengine/godot/commit/4d13be3c5eab71b04f6d7a0ed9d7e8679b377494 is the only difference between those branches relating to MultiplayerPeerExtension. I don't know enough about how the `godot source -> JSON -> godot-cpp header` pipeline works to know if this is an error in a different step, but my guess is the changes adding the GDVIRTUAL_BINDs	for those functions in that change is what fixed it.

### Steps to reproduce

1. Generate the extension API json with 4.0.3 RC1 build
2. Using Godot-cpp generate headers
3. Build a C++ class that extends from MultiplayerPeerExtension
4. Load that as an extension
5. When godot goes to poll that connection it will throw an error saying that the virtual functions _get_packet_channel and _get_packet_mode aren't overridden

### Minimal reproduction project

I don't know enough about GDExtension to know if there's another way to test this but I assume the minimal reproduction project would require my built C++ extension and I assume people don't want to run arbitrary libraries I upload here? Please let me know if that's what is needed though.

**Comment by akien-mga** [comment] 2023-05-11 10:31
Duplicate of #74628.

**Closed by akien-mga** 2023-05-11 10:31 UTC
Labels: bug, topic:multiplayer
