### ISSUE TITLE
Copy and paste shortcuts don't work in Visual Script editor

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#41156] opened 2020-08-09 23:36 UTC
**Godot version:**

3.2.3 rc3

**Issue description:**

When in Visual Script editor, you can't use Copy and Paste shortcuts. You need to select them from the Edit menu. All other shortcuts seem to work (including Cut and the unlisted Duplicate shortcut...)

**Comment by Kartik1397** [comment] 2020-09-03 13:34
Can I work on this issue?

**Comment by KoBeWi** [comment] 2020-09-03 13:38
Yeah, no need to ask btw.

**Comment by Kartik1397** [comment] 2020-09-03 20:42
Is title of this issue correct?

**Comment by KoBeWi** [comment] 2020-09-03 20:44
Sorry it wasn't, it's about Visual Script not Visual Shader.

**Comment by Kartik1397** [comment] 2020-09-04 20:49
Are `KEY_C` and `KEY_V` handled specially? because if I change `KEY_C` to `KEY_I` and `KEY_V` to `KEY_K` it's start working properly. 
Also if I change focus to some other panel then all shortcut are working as expected.

**Comment by EricEzaM** [comment] 2020-09-15 06:23
I have not looked into this in detail but it sounds very much like it is related to #39039 and the issues that it mentions. 

The ctrl c and ctrl V commands are jousting being 'stolen' by other editor. 

The way shortcuts are handled in the editor and GUI in general needs a big rethink - something I have been pondering on for quite some time but have no solution yet.

**Comment by EricEzaM** [comment] 2020-09-16 05:19
Ok, actually the problem is pretty simple.

Graph edit has it's own keybindings set internally which cannot be changed.

https://github.com/godotengine/godot/blob/6f4384f2063dc892b751eda750e120d72119644a/scene/gui/graph_edit.cpp#L1036-L1056

Because this happens on `_gui_input()` and the event is marked as handled, the event does not propagate any more. As you can see, `GraphEdit` emit's signals showing that dupe, copy, paste and delete was requested. However, in `VisualScriptEditor` this signal is never connected to - only duplicate and delete are.

https://github.com/godotengine/godot/blob/6f4384f2063dc892b751eda750e120d72119644a/modules/visual_script/visual_script_editor.cpp#L4767-L4781

So to fix the issue the signals just need to be connected. It is very weird to have these baked-in shortcuts, and they cause many issue like this I think.

**Closed** 2021-11-03 20:50 UTC
Labels: bug, topic:editor, usability, topic:visualscript

**Comment by matthew-j-wolf** [comment] 2025-01-16 21:52
Why does it say closed. It still works in 4.4

**Comment by KoBeWi** [comment] 2025-01-16 22:06
It was fixed by #54564
Do you mean the bug still exists?
