### ISSUE TITLE
Improvement in CurveTexture.

### ISSUE THREAD

**Issue by sezit** [godotengine/godot#11017] opened 2017-09-06 14:52 UTC
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Windows 10 Build from 04.09.2017

**Issue description:**
If in curve texture change max value and move point upper, then lower back point move out of graph. Point must scale position in proportion. Its give more "clean" feeling.
![curve texture](https://user-images.githubusercontent.com/6241034/30118840-b364d5fa-932c-11e7-9ac4-3e96f304c7a8.png)

P.S. If add curve to adjustments in WorldEnvironment it give only red color. Its bug or not, i dont know :3

**Comment by Zylann** [comment] 2017-09-06 17:22
If I remember this question popped up while I implemented this, but I don't remember exactly what was the intention.
@reduz what would you recommend?

**Comment by sezit** [comment] 2017-09-06 18:46
Hmm... I thinking about usability awhile, before post this issue. Maybe only scale down without scale up.

**Comment by akien-mga** [comment] 2018-01-15 10:46
Is this still reproducible in Godot 3.0 RC1?

**Comment by sezit** [comment] 2018-01-15 12:35
Yes.

**Comment by Zylann** [comment] 2018-01-15 12:52
In fact, the min and max values are only used for displaying the graph, they don't have any impact on the points data, it was done by design (see my comment above).

**Comment by sezit** [comment] 2018-01-15 13:09
If you want, you can close this issue. I dont have problem with this.

**Comment by akien-mga** [comment] 2018-01-15 13:11
Well I'd say this is confusing to say the least, I would also expect "Min Value" and "Max Value" to actually clamp the values the graph can reach.

**Comment by Zylann** [comment] 2018-01-15 13:36
@akien-mga if so, how can this be implemented in a way that loading the points before the range doesn't clamp them to default range? (it's about loading order of the resource properties).
Also means undoing range changes needs to also undo their clamping effect.

**Comment by akien-mga** [comment] 2018-01-15 13:41
I'm not familiar with this resource and I don't have a solution, just saying that it is confusing :)

**Comment by Calinou** [comment] 2020-06-14 14:54
The curve editor has been moved to the inspector in 3.1, making this proposal no longer relevant. Closing.

**Closed by Calinou** 2020-06-14 14:54 UTC
Labels: confirmed, enhancement, topic:editor
