### ISSUE TITLE
Nodes with scripts do not update their icon when the type changes

### ISSUE THREAD

**Issue by jotson** [godotengine/godot#80733] opened 2023-08-17 19:18 UTC
### Godot version

4.1.1.stable

### System information

Ubuntu Linux 22.04, Nvidia

### Issue description

When a node has a script, and you change the type of the node, the node icon does not change to reflect the new type.

The node icon seems to be based on the base type that the script is extending (e.g. `extends Node2D`)

But even in that case, changing the extends line also does not change the icon until the scene is closed and reopened

I expected the icon to change when I change the type

https://github.com/godotengine/godot/assets/1168026/e40b82cd-2d8a-430a-a13c-485a8378d5c7

### Steps to reproduce

1. Create a node
2. Add a script
3. Change the type of the node

### Minimal reproduction project

None

**Comment by Sauermann** [comment] 2023-08-17 20:27
related to #79979

**Comment by hsandt** [comment] 2023-08-20 11:32
Reproduced it today, I also tried to change the type written after `extends` to the new type before and after the Change Type, to no avail. Also had to restart editor.

**Comment by ershn** [comment] 2023-11-05 15:05
I can't reproduce the bug as in the video above on 4.1.3 (had experienced it before on 4.1.1).
So this bug was likely fixed by https://github.com/godotengine/godot/pull/81336 which was cherry-picked for 4.1.2.

I think it's safe to close this issue.

**Comment by YuriSizov** [comment] 2023-11-06 14:08
Indeed, this is a duplicate of https://github.com/godotengine/godot/issues/76983, fixed by https://github.com/godotengine/godot/pull/79203.

**Closed by YuriSizov** 2023-11-06 14:08 UTC
Labels: bug, topic:gdscript, topic:editor
