### ISSUE TITLE
GDScript 2.0: functions can't be multiplied

### ISSUE THREAD

**Issue by golddotasksquestions** [godotengine/godot#69986] opened 2022-12-12 21:45 UTC
### Godot version

4.0 Beta8

### System information

Win 10 Nvidea 765M

### Issue description

I would expect this to print "xyz" ten times:

```
func _ready():
	do() * 10

func do():
	print("xyz")
```

Error: `Invalid operands 'Nil' and 'int' in operator '*'.`

--------------------------------

This does not work either:

```
var callable = func(x): print(x)

func _ready():
	callable.call("xyz") * 10
```

Error: `Invalid operands 'Nil' and 'int' in operator '*'.`

```
var callable = func(): print("xyz")

func _ready():
	callable * 10
```

Error: `Invalid operands 'Callable' and 'int' in operator '*'.`

--------------------------------------------

Is this a bug, or just not a feature of GDScript 2.0?

### Steps to reproduce

Run the above minimal script.

### Minimal reproduction project

N/A

**Comment by akien-mga** [comment] 2022-12-12 22:23
That's not a feature, so not a bug.
And that's a pretty surprising proposal for new syntactic sugar. Is there any language that works like this?

The examples with function/callable calls definitely cannot be expected to work in any programming language.

If you expand this:
```gdscript
func _ready():
	do() * 10

func do():
	print("xyz")
```
It's the same as:
```gdscript
func _ready():
	print("xyz") * 10
```
`print()` is a function with no return value (`void`) so it can't be multiplied.

Change `do()` to `return 5` and the code will correctly calculate `50`.

A function call is (roughly) equivalent to copying the contents of that function in place, with the arguments expanded.

As for the `callable * 10` syntax, I've never seen this kind of syntax with callables and wouldn't know what to expect. `callable` by itself doesn't do anything, it's a variable that encapsulates a Callable - it can be passed around or called. Multiplying it would be like `node.set_name * 10` or `_ready * 10`, it doesn't make much sense and I wouldn't expect it to cause the callable to be called 10 times.

**Comment by YuriSizov** [comment] 2022-12-12 23:09
I think Clay forgot to close it...

**Closed by YuriSizov** 2022-12-12 23:09 UTC
Labels: feature proposal, archived

**Comment by golddotasksquestions** [comment] 2022-12-12 23:32
Thanks for the feedback and explanation @akien-mga !
