### ISSUE TITLE
Godot 4: a click on an animation name can paste name of animation previously renamed on SpriteFrames

### ISSUE THREAD

**Issue by gustavi** [godotengine/godot#55769] opened 2021-12-09 21:14 UTC
### Godot version

v4.0.dev.calinou [4f298237b]

### System information

Windows 10 64bit - Vulkan API 1.2.141 - GeForce GTX 1660 SUPER

### Issue description

A video is better than words:

https://user-images.githubusercontent.com/2736557/145475667-801433e3-da17-419c-b772-ee86010ec23e.mp4

Note: I only use mouse to perform this bug (I'm not pasting anything with my keyboard).

Godot 3.4 and 3.4.1-rc2 **are not** affected by this bug. All [official builds](https://downloads.tuxfamily.org/godotengine/testing/4.0/) are affected.

### Steps to reproduce

1. Go to `SpriteFrames` menu
2. Create an animation named "a"
3. Create an animation named "b"
4. Double click on "a" for editing the name
5. Click on "b"
6. "b" should be renamed "a 1"

### Minimal reproduction project

[bug-click-animation-name.zip](https://github.com/godotengine/godot/files/7688434/bug-click-animation-name.zip)

**Comment by jmb462** [comment] 2022-02-13 14:45
The bug concerns Tree node itself (not only SpriteFrames)
![bug](https://user-images.githubusercontent.com/3649998/153758442-5e6fb986-7d80-49c9-ad3a-9e76884535f0.gif)

**Comment by KoBeWi** [comment] 2022-05-02 17:50
Looks like #42419, except the "tree" in SpriteFrames editor is an ItemList.

**Comment by Rindbee** [comment] 2022-06-12 11:15
I think I already know about the cause of this problem. Similar to #60842.
https://github.com/godotengine/godot/blob/296c8b74f22172225946b4cd100f818234e8aa35/editor/plugins/sprite_frames_editor_plugin.cpp#L894
In this method, the entire tree is rebuilt. And this method may be called for a small change.

**Comment by anvilfolk** [comment] 2022-11-15 20:32
Cannot reproduce on master. Seems to have been fixed somewhere?

https://user-images.githubusercontent.com/1133892/202018119-8f23cd05-ef63-40a8-a447-043464777ff0.mp4

**Comment by akien-mga** [comment] 2022-11-15 21:27
Thanks for testing! Closing.

**Comment by Rindbee** [comment] 2022-11-15 22:54
Sorry, this issue doesn't seem to be resolved yet.

https://user-images.githubusercontent.com/30386067/202041870-67d0bf11-c6ad-48ab-96c1-a31b85f1cb19.mp4

**Comment by anvilfolk** [comment] 2022-11-15 23:05
I'm recompiling right now to test again, but it looks like you may have double-click selected the name and dragged it onto the other animation name?

**Comment by anvilfolk** [comment] 2022-11-15 23:16
Ok, here are some more details.

If you select a node, enter rename mode, then click some other node after a bit of time has passed, the bug does not occur.

If you double-click a node and *immediately* after click another node, the second node will become "selected". You can see it because it becomes highlighted. In that situation, clicking again _anywhere_ will rename the last node selected.

**Comment by Rindbee** [comment] 2022-11-15 23:40
It seems that the results returned by `Tree::get_edited()` and `Tree::get_selected()` are inconsistent.

**Closed** 2022-12-10 09:44 UTC
Labels: bug, topic:editor, regression, topic:animation
