### ISSUE TITLE
Exported variables are reset after saving an invalid script

### ISSUE THREAD

**Issue by rszibele** [godotengine/godot#25073] opened 2019-01-17 19:25 UTC
**Godot version:**
Godot 3.1 beta 1

**OS/device including version:**
Kubuntu 18.10

**Issue description:**
I finally managed to track down why my exported variables were "sometimes" reset on all instances. After saving an invalid script (type errors etc.), all exported variables are reset on all instances for that script.

**Steps to reproduce:**
1. Open the minimal reproduction project, open Main.tscn and click on the `Main` node.
2. Observe that the exported `variable1` has the value `123` in the inspector.
3. Now open `Script.gd`.
4. Uncomment line 6., Godot should indicate an error after a short period.
5. Save the file with `Ctrl+S`.
6. Comment out line 6. again and save with `Ctrl+S`.
7. In the node tree, click on the node `Main`.
8. Observe that `variable1` has been reset and now has the value `0`.

**Minimal reproduction project:**
[ExportedVarBug.zip](https://github.com/godotengine/godot/files/2770248/ExportedVarBug.zip)

**Comment by somnivore** [comment] 2019-01-17 20:03
I think this was fixed already on master https://github.com/godotengine/godot/commit/ea85ff0dc2a04e695d396f62ce5949f4e04254e4

**Comment by akien-mga** [comment] 2019-01-18 08:14
Indeed, that seems like a duplicate of #24280 that will be fixed in 3.1 beta 2. Please comment if you can still reproduce it on a recent build.

**Closed by akien-mga** 2019-01-18 08:14 UTC
