### ISSUE TITLE
KinematicBody2D can't handle moving platform with one way collision when moving up

### ISSUE THREAD

**Issue by damarindra** [godotengine/godot#9614] opened 2017-07-12 03:06 UTC
**Operating system or device - Godot version:**
Godot 3.0

**Issue description:**
KinematicBody2D can't handle when one way collision moving platform is moving up. The controlled KinematicBody2D always falling.

**Steps to reproduce:**
Download example project, and run TestScene
[Platformer.zip](https://github.com/godotengine/godot/files/1140777/Platformer.zip)

**Comment by eon-s** [comment] 2017-07-12 12:27
Duplicate of #9399 , this has an example and explicit mention of KB on the title, though.

**Closed** 2017-07-12 12:46 UTC
Labels: archived, bug, topic:physics
