### ISSUE TITLE
Godot 3.2.4 beta 4 can't export large projects from console

### ISSUE THREAD

**Issue by kzerot** [godotengine/godot#44403] opened 2020-12-15 18:34 UTC
**Godot version:**
Godot 3.2.4 beta 4

**OS/device including version:**
Any linux, can't test on other OS

**Issue description:**
Tried to export project from command line, like 
`../GodotRC/Godot_v3.2.4-beta4_x11.64 --export "HTML5"`
Have an warning:
WARNING: _notification: Scan thread aborted...
   At: editor/editor_file_system.cpp:1130.
  
  Godot 3.2.4 beta 3 and earlier runs perfect
   
Also export works fine then I exporting project from editor UI. 

**Steps to reproduce:**
Bug appears on my big project with 3000+ files and complex structure. 
Also this bug  run in new project with 20k files :) 

**Project with bug**
[TestFailedToBuild.zip](https://github.com/godotengine/godot/files/5697823/TestFailedToBuild.zip)

**Screenshot  console output**
![image](https://user-images.githubusercontent.com/4415061/102270674-52cb4c80-3f2f-11eb-8d63-d0beae473dfa.png)

**Comment by akien-mga** [comment] 2020-12-15 19:45
Are you sure that it fails?

#43948 made it stop displaying a window while exporting, but it should still work as previously. If it's a huge project, it might be taking a while to export.

**Comment by kzerot** [comment] 2020-12-15 19:48
Yep, no any other output, no files in directory for export.
Also, as I said, 3.2.4 beta 3 works fine with same parameters on same project. 
Also I checked - no godot processes in top

**Comment by kzerot** [comment] 2020-12-15 19:53
Same bug with headless version in machine without X11.

**Comment by Calinou** [comment] 2020-12-15 21:30
@kzerot Can you paste the output when exporting the project with the `--verbose` command line argument?

**Comment by kzerot** [comment] 2020-12-16 06:13
Sure thing

`[murre@Devabatta TestFailedToBuild]$ ../GodotRC/Godot_v3.2.4-beta4_x11.64 --export "HTML5" --verbose
Godot Engine v3.2.4.beta4.official - https://godotengine.org
XInput: Refreshing devices.
XInput: No touch devices found.
Detecting GPUs, set DRI_PRIME in the environment to override GPU detection logic.
Only one GPU found, using default.
Failed loading custom cursor: X_cursor
Using GLES3 video driver
OpenGL ES 3.0 Renderer: GeForce GTX 1060 3GB/PCIe/SSE2
OpenGL ES Batching: ON
        OPTIONS
        max_join_item_commands 16
        colored_vertex_format_threshold 0.25
        batch_buffer_size 16384
        light_scissor_area_threshold 1
        item_reordering_lookahead 4
        light_max_join_items 32
        single_rect_fallback False
        debug_flash False
        diagnose_frame False
PulseAudio: detected 2 channels
PulseAudio: audio buffer frames: 512 calculated latency: 11ms
 
CORE API HASH: 8232688261707287575
EDITOR API HASH: 13775767554423660220
Loading resource: res://default_env.tres
Construct gdnative interface

Destruct gdnative interface

Class 'BulletPhysicsDirectBodyState' is not exposed, skipping.
Class 'BulletPhysicsDirectSpaceState' is not exposed, skipping.
Class 'BulletPhysicsServer' is not exposed, skipping.
Class 'GDScriptNativeClass' is not exposed, skipping.
Class 'IP_Unix' is not exposed, skipping.
Class 'InputDefault' is not exposed, skipping.
Class 'Physics2DDirectBodyStateSW' is not exposed, skipping.
Class 'Physics2DDirectSpaceStateSW' is not exposed, skipping.
Class 'Physics2DServerSW' is not exposed, skipping.
Class 'ResourceImporterMP3' is not exposed, skipping.
Class 'ResourceImporterOGGVorbis' is not exposed, skipping.
Loading resource: /home/murre/.config/godot/editor_settings-3.tres
EditorSettings: Load OK!
Loaded builtin certs
Socket error: 98
Failed to bind socket.
EditorSettings: Save OK!
WARNING: _notification: Scan thread aborted...
   At: editor/editor_file_system.cpp:1130.
EditorSettings: Save OK!
`

**Comment by Calinou** [comment] 2020-12-16 13:41
After looking at the verbose log, I don't know what could be causing this.

PS: I edited your comment to use triple backticks (```) since it's a multiline code block.

**Comment by akien-mga** [comment] 2020-12-16 13:50
I can reproduce the issue too with 3.2.4 beta 4. Probably a regression from #43948, I'll look into it.

**Comment by akien-mga** [comment] 2020-12-16 14:31
Fixed by #44428.

**Closed by akien-mga** 2020-12-16 14:31 UTC
Labels: bug, confirmed, regression, topic:editor
