### ISSUE TITLE
set_text can not accept str(number)  REF.#268

### ISSUE THREAD

**Issue by fgoo** [godotengine/godot#5593] opened 2016-07-08 13:02 UTC
Hello,

**Operating system or device - Godot version:**
Windows 7 32b or Windows 10 64b
Godot_v2.0.3_stable_win32

**Issue description** (what happened, and what was expected):
Function get_node("label").set_text(str(10)) doenst work.
When Exporting to Windows Desktop or Android (Works on F5)

**DEBUG Error**
Cannot convert Argument 1 from Bool to String

**Steps to reproduce:**
this can not work:
get_node("label").set_text(str(10))

this can not work:
texto = str(10)
get_node("label").set_text(texto)

this can work:
get_node("label").set_text("10")

this can work:
texto = "10"
get_node("label").set_text(texto)

Regards,

**Comment by fgoo** [comment] 2016-07-09 12:58
Hi, 
Its working in this unofficial version 64bit (July 9, 2016 at 09:23)
from 
http://fixnum.org/godot/#latest_complete

Regards,

**Comment by vnen** [comment] 2016-07-16 15:31
I cannot reproduce this on 2.0.4.1 nor on master. If there were a bug, it's fixed by now.

**Closed by vnen** 2016-07-16 15:31 UTC
Labels: bug, topic:core
