### ISSUE TITLE
POT Generation not detecting exported variables

### ISSUE THREAD

**Issue by cashew-olddew** [godotengine/godot#90053] opened 2024-03-30 20:38 UTC
### Tested versions

- Reproductible in 4.2.stable

### System information

Windows 10 - Godot v4.2.1.stable Forward+

### Issue description

Generating a POT file from `Project > Project Settings > Localization > POT Generation` creates a template file which only includes text written for built-in nodes.

I would expect that any node which has an exported text property to be considered for POT Generation.

### Steps to reproduce

1. Create a Label and set its text to 'EXAMPLE'
2. Create a node2D which has a script that exports a String variable: `@export var text: String = ""`. Instantiate that node and set its exported variable text to 'OTHER_EXAMPLE'
3. Go to `Project > Project Settings > Localization > POT Generation`. Add the main scene and click `Generate POT`
4. The generated template does not contain 'OTHER_EXAMPLE':
```pot
# LANGUAGE translation for LocalizationMRP for the following files:
# res://main.tscn
#
# FIRST AUTHOR <EMAIL@ADDRESS>, YEAR.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: LocalizationMRP\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8-bit\n"

#: main.tscn
msgid "EXAMPLE"
msgstr ""

```

### Minimal reproduction project (MRP)

[LocalizationMRP.zip](https://github.com/godotengine/godot/files/14813281/LocalizationMRP.zip)

**Comment by dalexeev** [comment] 2024-03-30 21:18
> * Reproductible in 4.2.stable

Can't reproduce in 4.3 dev (current `master`). Probably fixed by #89286.

<details>
<summary>template.pot</summary>

```pot
# LANGUAGE translation for LocalizationMRP for the following files:
# res://main.tscn
# res://Node2D.gd
#
# FIRST AUTHOR <EMAIL@ADDRESS>, YEAR.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: LocalizationMRP\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8-bit\n"

#: main.tscn
msgid "EXAMPLE"
msgstr ""

#: main.tscn
msgid "OTHER_EXAMPLE"
msgstr ""
```

</details>

**Comment by Kiisu-Master** [comment] 2024-03-31 11:39
I think this was fixed when the node type check was removed by #87530. Before it would only include `Control `or `Window `nodes.

My PR fixed parsing of instanced scenes, and it made the included properties more dynamic. It will try to include all properties with a name that ends with `_text`. 
https://github.com/godotengine/godot/blob/29b3d9e9e538f0aa8effc8ad8bf19a2915292a89/editor/plugins/packed_scene_translation_parser_plugin.cpp#L196-L207

This issue shouldn't be closed yet. Included and excluded node types and properties should be configurable to the user so they can decide themselves what should be included. I already have wanted to implement this, as i said in my PR, but im missing the motivation to figure out how to add project settings and start compiling Godot again (it takes like 3 hours).

**Comment by AThousandShips** [comment] 2024-03-31 11:45
> Included and excluded node types and properties should be configurable to the user so they can decide themselves what should be included.

This sounds like something that should be a proposal, it's far outside the scope of this report

**Comment by AThousandShips** [comment] 2024-07-29 15:46
Closing as fixed, please open a proposal for any additional features

**Closed by AThousandShips** 2024-07-29 15:46 UTC
Labels: bug, topic:editor, needs testing, topic:gui
