### ISSUE TITLE
Can't apply StandardMaterial3D as material

### ISSUE THREAD

**Issue by enenbee** [godotengine/godot#66724] opened 2022-10-01 20:12 UTC
### Godot version

4.0.beta2

### System information

Windows 10

### Issue description

I was trying to load a StandardMaterial3D resource as the material for a CSGCylinder, but it wasn't allowing me to because it wasn't a BaseMaterial3D or a ShaderMaterial. I feel like I should be able to load a material which extends BaseMaterial3D

### Steps to reproduce

Add a GeometryInstance3D node to the scene
Make a StandardMaterial3D resource or a ORMMaterial3D resource
Try to load the material as the material for the GeometryInstance3D

**Comment by enenbee** [comment] 2022-10-01 20:20
After checking more, I can't even load a BaseMaterial3D or a ShaderMaterial

**Comment by Calinou** [comment] 2022-10-01 22:12
Duplicate of https://github.com/godotengine/godot/issues/66700.

**Closed by Calinou** 2022-10-01 22:12 UTC
