### ISSUE TITLE
The marks do not disappear when it becomes invisible

### ISSUE THREAD

**Issue by Torguen** [godotengine/godot#59384] opened 2022-03-21 10:12 UTC
### Godot version

v3.5.beta2.official [7a4f9dfb1]

### System information

w10 64

### Issue description

The anchors/pivots do not disappear when the CollisionShape2D becomes invisible.
![gif gif](https://user-images.githubusercontent.com/19652075/159241105-ccb44654-19a2-438a-babd-992c84db0e2d.gif)

### Steps to reproduce

see the gif

### Minimal reproduction project

...

**Comment by timothyqiu** [comment] 2022-03-21 11:00
Strange, I could not reproduce this on beta2 or current 3.x (39ad3a02be).

**Comment by KoBeWi** [comment] 2022-03-21 11:15
This should've been fixed by #57984, including in 3.5.

**Comment by Torguen** [comment] 2022-07-29 07:24
Seems solved in v3.5.rc8.official [516d6b6ba]
It doesn't happen in this version.

**Comment by akien-mga** [comment] 2022-07-29 07:51
Duplicate of #57924.

**Closed** 2022-07-29 07:51 UTC
Labels: topic:editor, topic:2d
