### ISSUE TITLE
Cannot compile for Android on Windows with NDK in a path with spaces

### ISSUE THREAD

**Issue by WalasPrime** [godotengine/godot#6586] opened 2016-09-22 13:49 UTC
Windows 10 64bit, trying to compile current master

Basically I've stumbled upon something similar to #1403 where os_android.os wouldn't get created, but ending with a different message: "The system could not find the path specified".
The solution was to rename `C:\Program Files (x86)\Android\android-ndk-r12b\toolchains\arm-linux-androideabi-4.9\prebuilt\windows` to `(...)\windows-x86_64`.

Indeed I've downloaded the 32bit NDK, but appearantly the buldsystem only expects the 64bit NDK (on a 64bit system) no matter what. Probably should be fixed (couldn't compile for Android on Windows otherwise).

**Comment by WalasPrime** [comment] 2016-09-22 14:00
Actually, after doing that at some point I get the following error:
```
C:\Program Files (x86)\Android\android-ndk-r12b/toolchains/arm-linux-androideabi-4.9/prebuilt//windows-x86_64/bin/arm-linux-androideabi-ar rc drivers\libdrivers1.android.opt.armv7.neon.a
[a big *.o file list]
scons: *** [drivers\libdrivers1.android.opt.armv7.neon.a] The parameter is incorrect
scons: building terminated because of errors.
```
I'll try switching to 64bit NDK to see if it fixes this.

**Comment by vnen** [comment] 2016-09-23 01:24
I would guess the problem is that you have a space in the path to the NDK. Move it something like `C:\android-ndk`.

**Comment by WalasPrime** [comment] 2016-09-23 07:45
Yup, that was it. I remember having this problem in so many other projects too... Makes you wish Microsoft just named that damn directory "program_files" or something 😄 

So I guess the buildsystem needs a fix to support spaces in the path. Should I make another issue or just leave this as it is?

**Comment by vnen** [comment] 2016-09-23 11:41
Well, it's not the first time I've seen someone struggling with this, so making the buildsystem work with paths with spaces might be good. We need at least to properly document it.

**Comment by Noshyaar** [comment] 2018-04-06 11:29
First of all thank you for your report and sorry for the delay.

We released Godot 3.0 in January 2018 after 18 months of work, fixing many old issues either directly, or by obsoleting/replacing the features they were referring to.

We still have hundreds of issues whose relevance/reproducibility needs to be checked against the [current stable version](https://godotengine.org/download), and that's where you can help us.
**Could you check if the issue that you described initially is still relevant/reproducible in Godot 3.0 or any newer version, and comment about it here?**

For bug reports, please also make sure that the issue contains detailed steps to reproduce the bug and, if possible, a zipped project that can be used to reproduce it right away. This greatly speeds up debugging and bugfixing tasks for our contributors.

Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

Thanks in advance.

*Note: This message is being copy-pasted to many "stale" issues (90+ days without activity). It might happen that it is not meaningful for this specific issue or appears oblivious of the issue's context, if so please comment to notify the Bugsquad about it.*

**Comment by akien-mga** [comment] 2018-11-22 10:14
Should be easy to fix if someone wants to dig into `platform/android/detect.py`.

**Comment by Calinou** [comment] 2018-12-09 17:32
I spent some time debugging this, but I really don't know what's going on anymore. [Quoting the path](https://github.com/Calinou/godot/commit/c1a0061e18b7b429fab7dafddc470632bdbb7e1e) solves the issue on Linux, but causes Windows to throw an error of type *"The filename or extension is too long"* when linking. I tried again with the `master` branch and it works as-is, even if the SDK and NDK paths contains spaces. (I tested this on Windows 10 build 17134.)

**Comment by Anutrix** [comment] 2019-11-27 19:59
@WalasPrime Are you still able to reproduce the issue with latest master?

**Comment by Calinou** [comment] 2020-04-29 07:54
@WalasPrime Bump :slightly_smiling_face: See Anutrix's question above.

**Comment by WalasPrime** [comment] 2020-04-29 18:08
I'm having major issues trying to set up Android tools according to the docs. It's most likely unrelated to Godot itself. I think that someone else should attempt testing this.

**Comment by Calinou** [comment] 2020-06-18 09:08
Closing, as nobody has been able to reproduce this recently. Please comment if you can still reproduce this issue.

**Closed by Calinou** 2020-06-18 09:08 UTC
Labels: documentation, enhancement, junior job, platform:android, platform:windows, topic:buildsystem
