### ISSUE TITLE
Ability to directly save nodes in their current state

### ISSUE THREAD

**Issue by Reneator** [godotengine/godot#31229] opened 2019-08-09 06:50 UTC
**Godot version:**
official 3.1.1-stable_win64

**OS/device including version:**
windows 10 64 bit

**Issue description:**

My goal is it, to save nodes/objects in exactly the state they are currently in (including sub-objects etc.) by just calling one method, without having to manually define a save-method in every sub-object inside the node etc.

I know about the ability to save nodes and vars via inst2dict dict2inst and var2bytes and bytes2var and with the documentation tutorial of manually creating a dict that you use after loading to set up all the values inside the object and then separately dict2inst them on load and put the values.

My situation is, that my nodes has objects in vars in its script, which values get lost on load. Either via the values that get set in the _init of the objects or they dont get set at all (although they for example exist in the dictionary that gets produced by inst2dict). But this can get kind of solved by having inst2dict be done separately for every object inside of vars in the script.

So my requirement would be to be able to direclty save nodes in their current state and then successfully load them into the game again.

The thing is, i would be able to add load() and save() functions to those objects, but i actually plan on having a lot of children of one of my objects (Skill) and every object could have completely different behaviour, so i would have to define a lot of those load() and save() functions by hand. And i would prefer/expect there to be an easier way.

Does there currently exist a feature that could fulfil this requirement? If not, i would like to request the ability to directly save an Object/Node with all its sub-objects included into a file and successfully loading it in the exact state (including all sub-Objects inside it) at a later point.

Thank you for your time!

**Steps to reproduce:**
in the reproduction project just start the "Main.tscn" scene and click Spacebar to save and Escape to load. 

My expectation would be, that on load it prints into the console: "I am now posting some stuff: 15" because i set it in the main-scene.

Then if you load an error should appear. This error can be fixed by adding the "Sub_Script.gd" into the _init() of the Player_node.gd but then the value would be reset (set to Null).

**Minimal reproduction project:**
[Save_Test.zip](https://github.com/godotengine/godot/files/3485079/Save_Test.zip)

**Comment by mrcdk** [comment] 2019-08-09 07:36
This is already possible although I wouldn't recommend it. You can save any branch of your scene tree as a scene at runtime which will save all the state of that branch and then load that scene and swap it from the original branch you had. That's simplifying it a bit but it does work. To save the scene you need to set all the children `owner` property to the "root" node you want to save. An example of saving a branch of a running scene:
```gdscript
func _ready():
	var scene = PackedScene.new()
	var scene_root = $Player
	_set_owner(scene_root, scene_root)
	scene.pack(scene_root)
	ResourceSaver.save('user://SavedPlayer.tscn', scene) # or .scn to avoid people messing with it
	
func _set_owner(node, root):
	if node != root:
		node.owner = root
	for child in node.get_children():
		_set_owner(child, root)
```

Then you would load that scene `var loaded_player = load("user://SavedScene.tscn").instance()`, remove the old node you want to swap `remove_child($Player)` and add your loaded player `add_child(loaded_player)` (You can also check [`InstancePlaceholder`](https://docs.godotengine.org/en/3.1/classes/class_instanceplaceholder.html) to streamline that process)

I wouldn't recommend it because it removes some control over what to save and you'll save stuff that you may not want to be saved.

**Comment by Ronnyator** [comment] 2019-08-09 07:51
@mrcdk Thank you for the indepth explanation! I personally touched on the PackedScene way once, but it seemed to complicated and i didnt understood it fully. Your explanation makes it very clear to me!

Will try it out, but i would still prefer a simpler way to just save an object/node in a file. Something that i actually expected inst2dict and var2bytes to already do. But the instantiation behaviour of their respective methods `dict2inst` and `bytes2var` prevents it to work as expected IMO.

In java you would be able to properly do the serializing and deserializing with not big hassle too :/

I will give the packed-scenes a try (i have need of this only for one small part in my game, all the other systems already work properly with either defining a save_dict or inst2dict).
The reason i would want to save its state is: Its a skill-system that has skills as children (so they can _progress(delta) on their own) and i wanted to save if a skill was active/on cooldown when the game is being saved.

Alternatively i could just have him reset all the skills on load (reset cooldown, reset active, or just reset active). 

Anyway: Thank you a lot for your help!

**Comment by Xrayez** [comment] 2019-08-09 11:15
I provided some related info in #31045 (with some possible solution) and #6533 for more use cases on this.

**Comment by dioptryk** [comment] 2019-08-09 15:07
Serialization can be a really non-trivial topic. Assuming that dict2inst/inst2dict should deal with everything "magically" is misguided IMO. What if you have objects with circular references to each other? What if some of your scenes are instanced, you serialize them with all properties, then in the next version of your game you'll change some of the Scene values and then loading the serialized ones will overwrite everything (since all the property dictionary was saved)? What about references to resources like Textures - perhaps you generate _some_ of them in the game itself (like avatar face with equipped helmet) and would like to save _some_ of them to disk, but not others? Etc, etc.

In my opinion, for any non-trivial software, full control over serialization is absolutely necessary. Some of your objects you will fully serialize, some (like an RPG skill learned by your character) you'll serialize only with skill scene path and skill level (for example). I think, no matter how universal of an serialization solution will be provided by the engine, you will always have some special cases. It actually is harder in games than in some business software because of all the graphic resources attached to objects.

Start with PackedScene and consider all of your objects case by case; try to simplify them, do not try to create super-universal solution, as it may very well complicate rather than simplify your game.

**Comment by Reneator** [comment] 2019-08-09 17:21
@dioptryk Thank you for that perspective, i didnt think of many of those corner cases yet.

But I didnt mean to imply that serialization is trivial. I meant that my expectations  would be that the situation (sub-objects) im in would be easy to solve (nearly trivial)

**Comment by KoBeWi** [comment] 2020-05-26 17:43
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!

**Closed by KoBeWi** 2020-05-26 17:43 UTC
Labels: discussion, feature proposal, topic:core

**Comment by Railwanderer** [comment] 2021-04-23 16:26
I also stumbled across this while building an electric solving game, where the player builds an electric circuit by his needs and my algorithms solve the currents. I use directed and non-directed graphs(circular references), cables wand modules on cables, which have two nodes at their ends, which are connected to other nodes again. The order they were created and combines matters for me, although it is lost in the current state of the circuit, meaning you can t reproduce the order, including deleted nodes and cables, when only looking at the state. So for this reason it is important for me to save the state as is it. I tried many approaches, also setting the owners recursively which makes Godot crash with no error (guess because of the cyclic references) with no success. I have inherited scene instances, and also instances in instances (both instanced programmatically). It would be a pain to save every property of such a graph, including the sprites position and so on. Further it is still not obvious for me why a state stored in RAM can't be saved and reloaded as an entire tree with all the references in singletons. This would always be my first thought on saving, rather than trying to write some kind of encoding, which will try to reproduce the state upon loading. Can someone point it out for me why many languages solve it using this parsing method, I really don't know why it would not work and am having a hard try on giving up this approach.

**Comment by Razzlegames** [comment] 2021-04-23 21:32
>  Can someone point out for me why many languages solve it using this parsing method. 

I'm assuming you may mean `encoding` serialization?

There are many reasons.

- Constrain the problem to domain to only what you care about

This means you only serialize the needed data to persist and read your specific use case.  Saving all the object data (some very likely not influencing your state) is unnecessary.   Leading to...

- The serialized saved scene data is much later than is needed

- Domain of the saved data and the runtime state are actually two different views of the system

Many times we want to segregate these domains and keep coupling low.  This allows you to even do things like send this data to other applications from this distinctly different and constrained domain, without it having to understand many underlying things it doesn't perhaps care about. This is why there are so many object mapping solutions out there by the way.


For your use case, maybe try having each object understand how to serialize itself in a way specific to its used case.  Placing in a `Dictionary` and serializing to `JSON` seems to be the easiest case for me in Godot.  If every object of interest,  in your application, has this ability, you can simply walk the tree to call this `serializeToDicitonary` method and build up the structure along the way for all the sub parts.  Maybe each JSON substructure can track it's type of object if needed etc?  Then you can serialize the `Dictionary` to JSON fairly easily.

I know it's a pain compared to other languages.  But even those alternatives typically map to a simplified Object that's specific for the serialization purpose (API object for network, DBA object for persistence etc), before utilizing some auto serialization solution (`ObjectMapper` etc)

**Comment by Railwanderer** [comment] 2021-04-24 09:29
Thanks for this fast and detailed answer! I was messing around last night a bit and it seems like the best way to go for is indeed using the Json serialization, although it is quite some work to do. I will try to save everything in a readable format first, which disguised a bug already that I fixed. Once I am certain about everything reloading again I will try out this approach:
https://www.youtube.com/watch?v=ldKFOGRQDzo&t=386s
to store the created dictionary in a resource, and then save it in binary format later.


> * Domain of the saved data and the runtime state are actually two different views of the system
> 
> Many times we want to segregate these domains and keep coupling low. This allows you to even do things like send this data to other applications from this distinctly different and constrained domain, without it having to understand many underlying things it doesn't perhaps care about. This is why there are so many object mapping solutions out there by the way.

This really made sense to me :)

**Comment by Razzlegames** [comment] 2021-04-24 23:24
No problem @Railwanderer . Glad I made sense with all my typos lol.  Looking forward to the solution you come up with.

**Comment by Calinou** [comment] 2021-04-25 13:22
>  to go for is indeed using the Json serialization, although it is quite some work to do

If you don't need interoperability with third-party software, using ConfigFile is likely a better approach as it can serialize any Godot datatype and is strongly typed (i.e. it has a proper integer type).

**Comment by Razzlegames** [comment] 2021-04-25 17:43
@Calinou Good idea!  One thing that might be missing though, would be hierarchical relationships, available in JSON/dictionary serialization.  Is there a streamlined way to achieve this using `ConfigFile`?  I'd assume you'd just have one `ConfigFile` point to another with a Path `String` attribute etc.

**Comment by Calinou** [comment] 2021-04-25 19:46
> @Calinou Good idea! One thing that might be missing though, would be hierarchical relationships, available in JSON/dictionary serialization. Is there a streamlined way to achieve this using `ConfigFile`? I'd assume you'd just have one `ConfigFile` point to another with a Path `String` attribute etc.

ConfigFile can store arrays and dictionaries just fine, but it's not like JSON has a standardized way to include other documents anyway (unlike YAML).

**Comment by Reneator** [comment] 2022-08-07 21:42
Just as a note if someone might stumble on this issue/thread:

I currently do this by having two methods on every node i want to save/load:

"save_state" which returns the values i want to save in a dict which can contain save-dicts from it's children as well.
"load_state" which accepts a dict which contains the save-state of the node and it's children. Here i can do the logic of initializing the object by hand, potentially also add load-failsave methods (if it cant load do X instead) for improved version compatability.

I am currently do most of the code of both methods by hand, so i have more control over it, but its possible to reduce the complexity and automate more of it to mere settings/configs.

I can also use the "load_state" function for the instantiation of a new node, currently also using this for duplicating a preexisting node, as the default duplicate might not go deep enough or not duplicate some nodes which would then remain empty.
