### ISSUE TITLE
Script editor opening scripts in existing tab with wrong name

### ISSUE THREAD

**Issue by PistolSkin** [godotengine/godot#97117] opened 2024-09-17 13:37 UTC
### Tested versions

Reproducible in v4.2.1.stable.official [b09f793f5] and v4.3.stable.official [77dcf97d8]

### System information

Godot v4.3.stable - Windows 10.0.22631 - GLES3 (Compatibility) - NVIDIA GeForce RTX 4090 (NVIDIA; 32.0.15.6094) - 13th Gen Intel(R) Core(TM) i9-13900K (32 Threads)

### Issue description

Double clicking on script (.gd) in the Scene or FileSystem tabs causes the Script editor to open the script in the existing, open tab and does not change the tab name.

### Steps to reproduce

- Open a script associated with a scene by double clicking on the .gd filename in the FileSystem or Scene tab. It will open in the script editor with a tab name associated with that script.
- Open a script not associated with a scene by double on the .gd filename in the FileSystem or Scene tab. It will open in the same tab as the script above replacing the contents. The tab will still have the name of the previous script.

### Minimal reproduction project (MRP)

The issue is not project dependent but i have included a simple project.

To reproduce in the attached simple project:

- Double click on main.gd in the FileSystem tab. It will open as tab called main in the Script editor.
- Double click on "not_main.gd" in the FileSystem tab. It will open in the existing a called main in the Script editor. It should open in a new tab called "not_main".

[project.zip](https://github.com/user-attachments/files/17028974/project.zip)

**Comment by AThousandShips** [comment] 2024-09-17 13:38
By tabs do you mean at the top? Or to the left of the scripts? If at the top then that's not a bug, those are scene tabs, not script tabs, it just looks like it is because you have the same name as the scene

**Comment by PistolSkin** [comment] 2024-09-17 13:52
Sorry, I am confused by the icon after the tab name which I thought was the icon for a script (looks a bit like a white scroll)? This is very confusing if there are supposed to be Scene names.

![Screenshot 2024-09-17 144855](https://github.com/user-attachments/assets/5e0d9dcf-05af-4ca2-81f0-d87bf136e180)

**Comment by AThousandShips** [comment] 2024-09-17 13:57
Look to the left of it, it has a node icon, the script part means it's got a script, but those are scene tabs, the script tabs are to the left

For more context see:
* https://github.com/godotengine/godot-proposals/issues/5461
* https://github.com/godotengine/godot-proposals/issues/512
* https://github.com/godotengine/godot-proposals/issues/7838

And a few other proposals

Closing as this is not a bug, but thank you for reporting

**Comment by PistolSkin** [comment] 2024-09-17 13:57
Thanks for you prompt response. Appreciate it.

**Closed by AThousandShips** 2024-09-17 13:57 UTC
Labels: topic:editor, needs testing

**Comment by AThousandShips** [comment] 2024-09-17 13:58
You're not alone in being confused by this, and there's some ideas for improving this, add your upvoats to those if you like them!
