### ISSUE TITLE
Run system command [GDScript]

### ISSUE THREAD

**Issue by Allespro** [godotengine/godot#21881] opened 2018-09-08 21:43 UTC
**Hi. Can someone help me?**
I need run system command in game, for example "ping example.com"
How can I do that?

_In c++ I can use "cstdlib" library and function "system"_

**Comment by AlexHolly** [comment] 2018-09-08 21:53
`OS.execute` ?

**Comment by eon-s** [comment] 2018-09-08 23:02
For questions like this go to any of the community channels (the recommended are the Q&A and Discord)
https://godotengine.org/community

This place is for engine development (bug report, proposals, etc.).

**Comment by groud** [comment] 2018-09-09 10:10
Closing as not a bug.

**Closed by groud** 2018-09-09 10:10 UTC
