### ISSUE TITLE
Stutter,Jitter

### ISSUE THREAD

**Issue by SradnickDev** [godotengine/godot#25404] opened 2019-01-28 09:14 UTC
**Godot version:**
3.0.6 stable official

**OS/device including version:**
Windows 10 64bit
AMD FX 4300 Quad-Core 3.80 Ghz
8GB Ram
GForce GTX 750
(Also reproduced on multiple PC's)

**Issue description:**
The Player stutters, jitter while moving with constant 60FPS.
After some restart of Godot, the jitter/stutter is sometimes less sometimes heaveier.

**Steps to reproduce:**
3D Scene with Kinematicbody

https://streamable.com/3jg4v
**Minimal reproduction project:**

**Comment by Zireael07** [comment] 2019-01-28 09:21
How many issues do we have on this already?

BTW did you read the documentation on it? https://docs.godotengine.org/en/latest/tutorials/misc/jitter_stutter.html?highlight=jitter

**Comment by groud** [comment] 2019-01-28 10:04
Duplicate of #25162

**Comment by groud** [comment] 2019-01-28 10:32
> because of that i opend the 1000# Stutter/Jitter Report

That's not how it works. Just comment on the appropriate issue if you have the same problem.
We have limited time, the more we spend triaging issues and explaining people how to use the bug tracker, the less we solve bugs.

**Closed by groud** 2019-01-28 10:32 UTC
Labels: archived
