### ISSUE TITLE
Vulkan: Shaders reading from screen/depth texture on the Forward Mobile backend with MSAA enabled cause the graphics to break

### ISSUE THREAD

**Issue by Saenoe** [godotengine/godot#60255] opened 2022-04-14 23:08 UTC
### Godot version

4.0.dev 12cb05b304

### System information

Windows 11, Vulkan, NVidia GTX 1070 driver version 496.49

### Issue description

When using the Vulkan Forward Mobile rendering back end with MSAA enabled, if any shader that reads from SCREEN_TEXTURE or DEPTH_TEXTURE (this includes StandardMaterial3D with refraction enabled) is visible on-screen, the entire screen turns into a mess of GPU... stuff. The original image is still vaguely legible underneath, albeit with tons of smearing/ghosting of previous frames. The only parts of the screen that remain intact are the objects the screen-reading shader is applied to, and seemingly the right and bottom edge of the screen.
Here's some images. The first one has MSAA set to 2x, and the 2nd one has it disabled. The screenshots are taken from the editor, but the result is the same when running the game.

![image](https://user-images.githubusercontent.com/87696194/163490521-31f44860-2ccf-4dd9-a4f5-253681ed8ffd.png)

![image](https://user-images.githubusercontent.com/87696194/163490544-83a9056a-15ee-4070-bc17-007b24257d7e.png)

### Steps to reproduce

In the project settings, set the Vulkan rendering back end to Forward Mobile, and set MSAA to anything other than Disabled. Then create a Mesh with either a ShaderMaterial3D that reads from SCREEN_TEXTURE or DEPTH_TEXTURE, or a Standard/ORMMaterial3D with Refraction enabled, and put it on a MeshInstance3D.

### Minimal reproduction project

[screen texture read.zip](https://github.com/godotengine/godot/files/8492773/screen.texture.read.zip)

**Comment by Calinou** [comment] 2022-04-15 00:25
cc @BastiaanOlij

**Comment by BastiaanOlij** [comment] 2022-04-17 03:15
auch, that looks like either the resolve of the MSAA into the backup buffer is failing or we've missed something. I'll find some time this week to look at it but please ping me if I forget.

**Comment by Saenoe** [comment] 2022-04-28 04:46
@BastiaanOlij
Just to add some more info, the issue doesn't seem to be there on my Arch Linux system, but it's still there on Windows. Same hardware, both using the most recent NVidia proprietary drivers (510.60 on Linux, 512.59 on Windows), both compiled from Godot commit 504708ae21 (the latest as of now), and both running the minimal reproduction project.

**Comment by clayjohn** [comment] 2023-02-23 18:03
I can't reproduce this issue on RC3. Closing as this has been fixed

**Closed by clayjohn** 2023-02-23 18:03 UTC
Labels: bug, topic:rendering, topic:3d
