### ISSUE TITLE
Cast to integer produces different results when vectors are involved

### ISSUE THREAD

**Issue by th1z** [godotengine/godot#30426] opened 2019-07-08 10:18 UTC
**Godot version:**
3.1.1 & 3.2

**OS/device including version:**
Windows x64

**Issue description:**
Cast to integer produces different results when vectors are involved

**Steps to reproduce:**
```
print("1: ", int(1.0/0.1))

var vec := Vector2(1.0, 0.1)
print("2: ", int(vec.x/vec.y))

var x:float = vec.x
var y:float = vec.y  
print("3: ", int(x/y))

var x1:float = 1.0
var y1:float = 0.1  
print("4: ", int(x1/y1)
```
Results in:
1: 10
2: 9
3: 9
4: 10

**Comment by lawnjelly** [comment] 2019-07-08 10:31
In this situation you probably want to use round() to convert from float to int. If due to floating point error a result is minutely below 10.0, it will when converted to int give the value 9. This is the inherent nature of floats, and why you have to be so careful converting them and comparing them.

There is probably some minor difference in the calculations used, e.g. one is using 32 bit float and one 64 bit.

https://en.wikipedia.org/wiki/Floating-point_arithmetic#Accuracy_problems

**Comment by th1z** [comment] 2019-07-08 10:51
Yeah, i know about floating point arithmetic but i think there should at least be a warning in the documentation that simply storing a floating point value in a vector will alter the value of the number.

```
var x := 0.1
var vec := Vector2()
vec.x = x
print(vec.x == x) # False
```

**Comment by lawnjelly** [comment] 2019-07-08 11:13
Just a little test .. 1.0 seems to be accurately represented.

However with 32 bit float 0.1f evaluates (in QT creator, I don't know how accurate its debug window is) to 0.100000001
and 64 bit double 0.1 evaluates to 0.10000000149011612

So the result of 9 is not surprising. In fact the result of 10 is more surprising! :smile: And god only knows what goes on during a divide hehe.

There could be a benefit to a section on use of floating point in general. For instance afaik comparisons of the form (a == b) is pretty much something you should never do, because it's almost guaranteed to fail. Epsilons etc are normally needed. I always found it strange that some beginner languages only allow float numbers, because they are subject to so many special cases that integers are not.

**Comment by th1z** [comment] 2019-07-08 13:26
> comparisons of the form (a == b) is pretty much something you should never do

I disagree. One should be very careful with floating point number comparison **after** calculations/operations have been carried.
However the following should always work:
```
var x:float = 1.0;
var y:float = x;
x == y # True
```

In case of the vector the documentation states that the (x, y, z) properties are also floats, so i expect them to work in the same way as any other float variable. 
The problem is that an assignment (eg. vec.x = 0.1) already performs an internal operation (converts to a different data type). 

This should be mentioned in the Vector class documentation because it deviates from normal/expected behavior.

**Comment by lawnjelly** [comment] 2019-07-09 07:14
I had another little look because I was amazed that 1.0 / 0.1 was producing the correct result in two of your cases, given the representation of 0.1 in float or double.

I haven't looked at the gdscript compiler, but I now suspect the compiler is optimizing these values out at compile time (i.e. replacing anything trivially calculable at compile time with constants). If this is the case it may be able to do this with floats but not complex types like Vectors.

This expression:
```
var vec := Vector2(1.0, 0.1)
print (((vec.y * 10.0) - 1.0) * 1000000)
```
gives 0.014901 (which is consistent with a double in my c++ test)
however this expression:
```
var y1:float = 0.1
print (((y1 * 10.0) - 1.0) * 1000000)
```
gives 0

**Comment by KoBeWi** [comment] 2020-09-25 01:00
Still valid in 215fa6e85
https://github.com/godotengine/godot-proposals/issues/892 could be related.

**Comment by aaronfranke** [comment] 2020-10-19 06:45
This happens because `Vector2(0.1, 0.1).x != 0.1`. GDScript floats are double-precision, while vectors use single-precision.

A similar issue can be found at #17971, and like that issue, this is a duplicate of https://github.com/godotengine/godot-proposals/issues/892

**Closed by aaronfranke** 2020-10-19 06:45 UTC
Labels: bug, confirmed, discussion, topic:core
