### ISSUE TITLE
Shader with default uniform values triggers segfault

### ISSUE THREAD

**Issue by razcore-art** [godotengine/godot#19753] opened 2018-06-24 19:35 UTC
25275de
I've managed to kill godot playing with shaders
```
type is: canvas_item
ERROR: complete: Failed to parse shader
   At: servers/visual/shader_language.cpp:4128.
ERROR: _code_complete_script: Shaderlang complete failed
   At: editor/plugins/shader_editor_plugin.cpp:196.
ERROR: operator[]: FATAL: Index p_index=1 out of size (size()=1)
   At: core/vector.h:147.
handle_crash: Program crashed with signal 4
Dumping the backtrace. Please include this when reporting the bug on https://github.com/godotengine/godot/issues
[1] /lib/x86_64-linux-gnu/libc.so.6(+0x3ef20) [0x7f7390a76f20] (??:0)
[2] Vector<ShaderLanguage::ConstantNode::Value>::operator[](int) const (??:0)
[3] /home/razvan/Documents/projects/dev/github-godot/bin/godot.x11.tools.64(+0x15a10f3) [0x55f6293d80f3] (??:0)
[4] RasterizerStorageGLES3::_update_material(RasterizerStorageGLES3::Material*) (??:0)
[5] RasterizerStorageGLES3::update_dirty_materials() (??:0)
[6] RasterizerStorageGLES3::update_dirty_resources() (??:0)
[7] RasterizerGLES3::begin_frame() (??:0)
[8] VisualServerRaster::draw(bool) (??:0)
[9] VisualServerWrapMT::draw(bool) (??:0)
[10] Main::iteration() (??:0)
[11] OS_X11::run() (??:0)
[12] /home/razvan/Documents/projects/dev/github-godot/bin/godot.x11.tools.64(main+0xd5) [0x55f628ba806f] (??:0)
[13] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xe7) [0x7f7390a59b97] (??:0)
[14] /home/razvan/Documents/projects/dev/github-godot/bin/godot.x11.tools.64(_start+0x2a) [0x55f628ba7eba] (??:0)
-- END OF BACKTRACE --
```
It corrupts the project so it's not possible to open again. Shader in question:
```c
shader_type canvas_item;

uniform vec4 color: hint_color = vec4(1.0);

void fragment() {
	COLOR = color;
}
```
[godot-dbg.zip](https://github.com/godotengine/godot/files/2131147/godot-dbg.zip)

*edit*
good thing godot uses a simple text format for .tscn files otherwise I'd be screwed :)

**Comment by JFonS** [comment] 2018-06-25 13:41
I can confirm this issue.

Seems to be related to the way default values are stored, I will take a deeper look at it.

**Comment by stur86** [comment] 2018-06-27 19:48
Can confirm this just happened to me too.

**Comment by Bauxitedev** [comment] 2018-06-28 11:58
I think this is a duplicate of #15166.

**Comment by akien-mga** [comment] 2018-08-13 20:35
Duplicate of #15166 indeed.

**Closed by akien-mga** 2018-08-13 20:35 UTC
Labels: bug, topic:core, topic:rendering
