### ISSUE TITLE
Nothing appears when drawing vertexes on the ImmediateGeometry node

### ISSUE THREAD

**Issue by Mudley** [godotengine/godot#9753] opened 2017-07-21 17:56 UTC
**Ubuntu 17.04 - Godot version: Godot 3 - Build: 0962871**

**Issue description:**
The ImmediateGeometry node doesn't seem to be drawing any vertexes that have been set.

**Comment by TwistedTwigleg** [comment] 2017-07-22 00:28
Probably Related to #9596

**Comment by kubecz3k** [comment] 2017-07-23 15:47
Closing as a duplicate of https://github.com/godotengine/godot/issues/9596

**Closed by kubecz3k** 2017-07-23 15:47 UTC
Labels: archived
