### ISSUE TITLE
GDScript 2.0: Function return type `enum` error (Trying to return value of type "int" from a function which the return type is "Dictionary")

### ISSUE THREAD

**Issue by stmSi** [godotengine/godot#57966] opened 2022-02-11 10:57 UTC
### Godot version

v4.0.alpha2.official [79077e6c1]

### System information

5.13.19-2-MANJARO XFCE, Nvidia 2060

### Issue description

Work fine in alpha 1 (v4.0.alpha1.official  @[31a7ddbf8])

Error exists in alpha 2 (v4.0.alpha2.official [79077e6c1])

Also Auto-Completion does not show the error.

### Steps to reproduce

```
enum State {
	Idle,
	Run,
	Attack,
}


func _ready() -> void:
	getEnum()

func getEnum() -> State:
	return State.Run
```

error: `Trying to return value of type "int" from a function which the return type is "Dictionary".`

**Comment by Mickeon** [comment] 2022-02-11 11:12
Could it have been caused by https://github.com/godotengine/godot/pull/57591 ?

**Comment by stmSi** [comment] 2022-02-11 11:45
> Could it have been caused by #57591 ?

Yes. I saw multiple comments there stating this error issue.

**Comment by jmb462** [comment] 2022-02-11 12:16
I confirm that it is caused by ceafdf347e5ecc050629fd4eac93030dabb0d0e9

**Comment by jmb462** [comment] 2023-01-07 12:20
I confirm that this issue still occurs in current master branch. (and in beta 10)

**Comment by adamscott** [comment] 2023-01-08 17:55
CC @anvilfolk

**Comment by anvilfolk** [comment] 2023-01-08 20:48
Also fixed by #69590 :)

Thanks @adamscott!

**Closed** 2023-01-09 22:11 UTC
Labels: bug, topic:gdscript, confirmed, regression
