### ISSUE TITLE
JPEG images with width of 1 cause crash

### ISSUE THREAD

**Issue by ShatReal** [godotengine/godot#46434] opened 2021-02-26 01:23 UTC
**Godot version:**

3.2.4-rc3 (crashes 3.2.3 as well)

**OS/device including version:**

Windows 10

**Issue description:**

Godot attempts to import the image and then crashes.

**Steps to reproduce:**
1. Add jpeg image with width of 1 to project
2. Crash

**Minimal reproduction project:**

[test.zip](https://github.com/godotengine/godot/files/6046824/test.zip)
Here is a test image:
![crash](https://user-images.githubusercontent.com/69117768/109241411-326d0900-778e-11eb-88d8-f218dcb8d076.jpg)

**Comment by qarmin** [comment] 2021-02-26 06:12
Message in terminal 
```
godots: thirdparty/jpeg-compressor/jpgd.h:278: int jpgd::jpeg_decoder::check_sample_buf_ofs(int) const: Assertion `ofs >= 0' failed.
```

**Comment by Riteo** [comment] 2021-02-26 09:40
This looks exactly like #42363. I guess it was supposed to be fixed, but from the looks of it this isn't the case.

**Comment by AndyBarcia** [comment] 2021-02-26 10:24
> This looks exactly like #42363. I guess it was supposed to be fixed, but from the looks of it this isn't the case.

Sorry if I'm being mistaken. But I think that it does solve the problem. But the pull request wasn't cherrypicked to 3.2.4

In the jpgd.cpp file you can see that in master the line is:

`const int half_image_x_size = (m_image_x_size == 1) ? 0 : (m_image_x_size >> 1) - 1;`

while in 3.2 the line is:

`const int half_image_x_size = (m_image_x_size >> 1) - 1;`

**Comment by akien-mga** [comment] 2021-02-26 10:35
Indeed, seems like I missed my cherry-pick of #43441 last time. Now fixed.
So closing as duplicate of #42363.

**Closed by akien-mga** 2021-02-26 10:35 UTC
Labels: bug, confirmed, crash, junior job, topic:import
