### ISSUE TITLE
Texture.set_flag() doesn't work on newly created textures

### ISSUE THREAD

**Issue by Yazir** [godotengine/godot#23844] opened 2018-11-20 12:51 UTC
**Godot version:**
3.1 Alpha 2

**Issue description:**
Changing flags of texture after creating it doesn't change anything visually.
![image](https://user-images.githubusercontent.com/8749862/48774741-526a1400-eccb-11e8-9e50-447c560ef4e9.png)
The red "blood" is blurred on 2D scale mode.
![image](https://user-images.githubusercontent.com/8749862/48774765-6877d480-eccb-11e8-9c86-11f6ee12be4f.png)

**Steps to reproduce:**
1. create sprite, imagetexture and image.
2. set flags to mipmaps (which doesn't really do anything)
3. add sprite as a child
4. draw couple pixels with set_pixel on image and create imagetexture from image

**Minimal reproduction project:**
[project.zip](https://github.com/godotengine/godot/files/2599770/project.zip)

This code is used
```
func _ready():
	var sprite = Sprite.new()
	var texture = ImageTexture.new()
	var img = Image.new()
	
	texture.set_flags(Texture.FLAG_MIPMAPS)
	
	add_child(sprite)
	sprite.texture = texture
	sprite.centered = false

	img.create(32,32, true, Image.FORMAT_RGBA8)
	img.lock()
	#img.fill(Color(randf(),randf(),randf(),randf()+0.5))
	#img.fill(Color(0,1,0,1))
	img.set_pixel(5,5,Color(0,1,0))
	img.set_pixel(6,5,Color(0,1,0))
	img.set_pixel(8,5,Color(0,1,0))
	img.set_pixel(9,6,Color(0,1,0))
	img.unlock()
	texture.create_from_image(img)
```

**Comment by bojidar-bg** [comment] 2018-11-20 14:41
Don't you mean FLAG_FILTER instead of FLAG_MIPMAPS? Mipmaps are useful when downscaling only.

**Comment by Yazir** [comment] 2018-11-20 16:59
I want to turn off Filter flag. I don't want the blur. Is there any other reason this would come out blurry?

**Comment by bojidar-bg** [comment] 2018-11-20 17:57
`create_from_image` takes two parameters: [`create_from_image(image, flags=7)`](http://docs.godotengine.org/en/3.0/classes/class_imagetexture.html#class-imagetexture-create-from-image).
That means it will likely ignore flags set earlier.

Try either `texture.create_from_image(img, 0)` or moving the `set_flags` after `create_from_image`.

**Comment by Yazir** [comment] 2018-11-20 18:18
I've tried both and couple more combinations but they don't seem to affect the outcome.

**Comment by clayjohn** [comment] 2019-04-18 20:21
Is this in GLES2 or GLES3? And is it reproducible in 3.1?

**Comment by raphael10241024** [comment] 2019-07-10 12:10
Can't reproduce it with both GLES2 and GLES3, using texture.create_from_image(img, 0) works fine now.

**Comment by akien-mga** [comment] 2019-07-10 12:33
Thanks, closing as fixed.

**Closed by akien-mga** 2019-07-10 12:33 UTC
Labels: bug, topic:core, topic:rendering
