### ISSUE TITLE
Importing glb with Octahedral Compression distorts normals for blend shape with 50% weight

### ISSUE THREAD

**Issue by tobymckoi** [godotengine/godot#55633] opened 2021-12-05 02:36 UTC
### Godot version

3.4-stable

### System information

Windows 10, NVIDIA GTX 1060, GLES3

### Issue description

I discovered this issue while debugging a visual problem with an animation. Screenshots below show a single mesh duplicated 3 times and with 0%, 50% and 100% blend shape weight applied, with a normal map shader.

When importing the .glb **with** octahedral compression (the default):
![godot_octa_bug_01](https://user-images.githubusercontent.com/707519/144730719-b0a04d80-a3ea-402d-a0ed-5a1c12fbd9a3.jpg)

When importing the .glb **without** octahedral compression:
![godot_octa_bug_02](https://user-images.githubusercontent.com/707519/144730762-35a56c9a-4247-494f-ae57-943ef53226d3.png)

### Steps to reproduce

Import the .glb file provided in the project with Octahedral Compression enabled. Play with the Blend Shape slider to see the visual artifact. You may need to rotate the object because the normals appear to be calculated correctly on one side. Also find a Godot scene that demonstrates the visual error in the .zip.

### Minimal reproduction project

Minimal Project: [godot_octanormal_issue.zip](https://github.com/godotengine/godot/files/7655094/godot_octanormal_issue.zip)

**Comment by Calinou** [comment] 2021-12-05 13:59
cc @The-O-King

**Comment by mbrlabs** [comment] 2021-12-05 14:15
Maybe related: https://github.com/godotengine/godot/issues/54763  
Looks similar, but only occurs on certain Android devices.

**Comment by The-O-King** [comment] 2021-12-22 00:41
I've gotten a chance to finally take a look at this and I think the issue is that the transform feedback loop used to generate the final blend shape does not take into account the different vertex attribute layout used when using octahedral compression - I'm currently working on a fix for this, i'll update once I have it done!

**Comment by akien-mga** [comment] 2022-01-04 13:10
Fixed by #56161.

**Closed by akien-mga** 2022-01-04 13:10 UTC
Labels: bug, topic:import, regression, topic:3d
