### ISSUE TITLE
Godot 3.0.2 C# _Input(Input Event) single key press problem

### ISSUE THREAD

**Issue by alexbosquin** [godotengine/godot#17283] opened 2018-03-05 16:32 UTC
**Godot version:**
3.0.2

**OS/device including version:**
Windows 10 64 bit
Nvidia Geforece GTX 760

**Issue description:**
When the user press the key "F" the selection must change, due to a input event issue
it calls the method 2 times each key press, you can see onoutput the results

**Minimal reproduction project:**
[godot-topdown-base.zip](https://github.com/godotengine/godot/files/1781721/godot-topdown-base.zip)

**Comment by neikeq** [comment] 2018-03-05 17:09
I cannot reproduce this. It only print `pressed N` once per key press. I tested with GDScript as well and the output was the same.

**Comment by alexbosquin** [comment] 2018-03-05 17:16
The actual output on my computer:

```python
4
changed to: 2
pressed 1
changed to: 4
changed to: 0
pressed 3
changed to: 2
pressed 4
changed to: 4
changed to: 0
pressed 6
```

the expected output would be:
```python
4
changed to: 1
pressed 1
changed to: 2
pressed 2
changed to: 3
pressed 3
changed to: 4
pressed 4
....
```

which one you got?

**Comment by neikeq** [comment] 2018-03-05 17:47
The first key press I get the following:

```
GDScript: changed to: 2
GDScript: pressed 1
changed to: 2
pressed 1
```

The next key press produces an ArgumentOutOfRangeException and the equivalent error in GDScript, in the `controlling = players[actual]` right after the _"changed to"_ print statement.

**Comment by neikeq** [comment] 2018-03-05 17:53
Forgot to mention I'm on Ubuntu. I can't test on Windows right now, but I would be surprised if the result wasn't the same.

Here is my modified version with the GDScript equivalent:
[godot-topdown-base.zip](https://github.com/godotengine/godot/files/1781997/godot-topdown-base.zip)

I had to add a `if selection != null and controlling != null` check to `_process` both for C# and GDScript to avoid null reference exceptions.

**Comment by alexbosquin** [comment] 2018-03-05 18:06
the null reference occurs because qhen you press a key and the actual turns to 4 , the player list count is 3, this problem is ocurring due to the key press problem wich makes the actual var increase by 2 and not by 1!

**Comment by neikeq** [comment] 2018-03-05 18:16
The reason it's increasing by 2 is because you are using `actual++` in the condition, and later you increment it again with `actual += 1`:

```
if (actual++ >= players.Count)
{
    actual = 0;
}
else
{
    actual += 1;
}
GD.Print("changed to: ", actual);
```

**Comment by alexbosquin** [comment] 2018-03-05 20:29
HAHA i found this, thanks dude!!!!

**Comment by groud** [comment] 2018-03-06 09:05
Since the problem looks solved close the issue :)

**Closed by groud** 2018-03-06 09:05 UTC
Labels: archived
