### ISSUE TITLE
Incorrect transparency of ViewportTexture

### ISSUE THREAD

**Issue by versenyi98** [godotengine/godot#49502] opened 2021-06-11 06:38 UTC
### Godot version

4.0.dev (9539e4e39e)

### System information

Ubuntu 18.04, Vulkan

### Issue description

I'm trying to display a ViewportTexture to a MeshInstance. The viewport has transparent background enabled, and the MeshInstance material's transparency is set to Alpha.

**Expected result:**
The texture's background is transparent.
**Actual result:**
The texture's background is black.

Setting the blend mode to 'Add' sets the background to transparent, but the rest of the texture also gets slightly transparent. My assumption is that the ViewportTexture's alpha channel is not set correctly - even though the background is set to transparent - , which would explain why it the background is only transparent with additive blend mode.

![image](https://user-images.githubusercontent.com/31245230/121641932-1ddc2480-ca90-11eb-96f7-a939c62d2955.png)

### Steps to reproduce

1. Create a PlaneMesh
2. Create a SubViewport
3. Set transparent background to the viewport
3. Add a 3D scene as child to the viewport
4. Set the albedo texture of the plane's material override to the viewport's texture

### Minimal reproduction project

[minimal.zip](https://github.com/godotengine/godot/files/6636316/minimal.zip)

**Comment by Calinou** [comment] 2021-06-11 07:50
Duplicate of https://github.com/godotengine/godot/issues/40651.

**Closed by Calinou** 2021-06-11 07:50 UTC
