### ISSUE TITLE
Godot freeze using "Show In File Manager"

### ISSUE THREAD

**Issue by git2013vb** [godotengine/godot#23371] opened 2018-10-29 10:39 UTC
**Godot version:**

![image](https://user-images.githubusercontent.com/13235119/47644565-72903280-db66-11e8-8c4c-e8db330bfdb5.png)

**OS/device including version:**
Win7-64 utimate

![image](https://user-images.githubusercontent.com/13235119/47644613-88055c80-db66-11e8-8ca7-d12d0f141a60.png)

**Issue description:**
I right-click to any item here
![image](https://user-images.githubusercontent.com/13235119/47644680-b7b46480-db66-11e8-8815-4af8a7e1c73a.png)
 and I choose 
![image](https://user-images.githubusercontent.com/13235119/47644707-cbf86180-db66-11e8-83d3-63cfcc16d46a.png)
 Then Godot freeze. 

I have to kill the instance form process manager.

**Steps to reproduce:**
See before

**Minimal reproduction project:**
Any

**Comment by akien-mga** [comment] 2018-10-29 10:54
CC @groud

**Comment by qarmin** [comment] 2018-10-29 11:46
Can't reproduce with Windows 10 with same commit.

First time when I clicked at "Show In File Manager" godot freeze by 0,5s/1s but now it works almost immediately

**Comment by Calinou** [comment] 2018-10-29 13:05
I can't reproduce this with ee858d0 on Windows 10 either (tested in both list and icons view).

**Comment by akien-mga** [comment] 2019-01-24 14:20
Can anyone reproduce this in the current master branch?

**Comment by akien-mga** [comment] 2020-01-08 13:40
Nobody could reproduce, so closing.

**Closed by akien-mga** 2020-01-08 13:40 UTC
Labels: bug, topic:editor
