### ISSUE TITLE
modules/mono/mono_gd/gd_mono_utils.cpp:371 - System.ArgumentException: Illegal characters in path.

### ISSUE THREAD

**Issue by dancroote** [godotengine/godot#41259] opened 2020-08-14 15:40 UTC
I am having precisely this issue, which the original person has closed since they cannot replicate it.
I am receiving the same errors as described in the console every time Godot is opened.

https://github.com/godotengine/godot/issues/39432

**Comment by Calinou** [comment] 2020-08-14 16:48
Duplicate of #39432. (Please be more patient when requesting issues to be reopened.)

**Closed by Calinou** 2020-08-14 16:48 UTC

**Comment by dancroote** [comment] 2020-08-14 17:22
Apologies, and thanks.
