### ISSUE TITLE
Turning on Windows calculator prevents user from typing using certain keys in editor until restart

### ISSUE THREAD

**Issue by 2404133455** [godotengine/godot#75708] opened 2023-04-05 19:00 UTC
### Godot version

Godot 4.0.1 Mono

### System information

Windows 10, Radeon R9 200 Series, 31.0.12027.7000

### Issue description

Upon turning on the Windows calculator, selecting the editor window and then pressing certain keys in the script menu doesn't do anything.

Turning off the calculator does not solve the issue (the keys still don't do anything), but turning Godot off and then on seems to do the trick.

I seem to be unable to reproduce the issue without using the Run utility in Windows.

Its occurence is rather inconsistent - sometimes the keys stop working the first time I turn it on, sometimes it takes multiple tries.

It doesn't just apply to the script editor, though it seems to be the easiest to notice the problem there.
For example, trying to edit a node name will have this bug occur. Trying to draw a rectangle using hotkeys with a TileMap node, though, will not.

Keys that don't work:
- Backspace
- Return
- Tab
- Arrow keys
- Del
- Alt
- Ctrl (I found it out while trying to save my project)

As a side note, I would like to add this has never happened to me in Godot 3 before (I frequently Win + R to turn on the calculator).

### Steps to reproduce

Start editing a script.

Launch calc using Windows + R.

Attempt to press any of the keys listed above in the script editor.

### Minimal reproduction project

N/A

**Comment by Calinou** [comment] 2023-04-05 19:27
- Duplicate of https://github.com/godotengine/godot/issues/74957 (fixed in 4.0.2).

**Closed by Calinou** 2023-04-05 19:27 UTC

**Comment by 2404133455** [comment] 2023-04-06 09:50
Ah, I understand, my bad. I tried searching for this before, but couldn't find anything, and then 4.0.2 dropped a day before I made the report.
