### ISSUE TITLE
Loading 3.2.3 project in 3.3, I have "project assembly not loaded" across several scenes

### ISSUE THREAD

**Issue by git2013vb** [godotengine/godot#48267] opened 2021-04-28 12:38 UTC
**Godot version:**

3.3 mono stable

**OS/device including version:**

Debian 10

**Issue description:**

this is the error:
```
E 0:00:00.757   can_instance: Cannot instance script because the project assembly is not loaded. Script: 'res://src/levels/Level01.cs'.
  <C++ Error>   Method failed. Returning: __null
  <C++ Source>  modules/mono/csharp_script.cpp:2902 @ can_instance()

```
and 
```
E 0:00:00.762   can_instance: Cannot instance script because the project assembly is not loaded. Script: 'res://prefabs/ui/FourBadgeButton.cs'.
  <C++ Error>   Method failed. Returning: __null
  <C++ Source>  modules/mono/csharp_script.cpp:2902 @ can_instance()

```
Te mentioned script is this one:
```
using Godot;
namespace DesertEdge
{
    public class FourBadgeButton : Button
    {
        public override void _Ready()
        {
        }
        public override void _Process(float delta)
        {
        }
        public void _on_Button_pressed()
        {
            // Log.Print(Log.DEBUG, "button pressed ", GetParent().Name, " fired:", Text);
            Signals.node.EmitSignal(nameof(Signals.AbilityFired), GetParent().Name, Text);
        }
    }
}

```

This issue don't allow me to run the project 
**Steps to reproduce:**
I run a scene that was fine in 3.2.3

**Minimal reproduction project:**

NA

**Comment by git2013vb** [comment] 2021-04-28 13:24
I found the problem:
When I rename the Project Name in Project Settings 
![image](https://user-images.githubusercontent.com/13235119/116410453-168cee80-a835-11eb-8b3e-1651df57fa55.png)

Godot don't update all the occurrence cross the project eg: 
- name of:  .csproj , .sln
- <RootNamespace> and <AssemblyName> in .csproj
- Project name and reference csproj in .sln file

consequently it will not show msbuild in editor and come up with already mentioned errors

**Comment by akien-mga** [comment] 2021-04-28 13:28
Duplicate of #27030.

**Closed by akien-mga** 2021-04-28 13:28 UTC
Labels: topic:mono
