### ISSUE TITLE
Performance Regression Godot 4 beta7+

### ISSUE THREAD

**Issue by delinx32** [godotengine/godot#70380] opened 2022-12-20 23:54 UTC
### Godot version

Godot 4 beta 7+

### System information

Windows 11, 3070ti GLES3
Vulkan API 1.2.0 - Using Vulkan Device #0: NVIDIA - NVIDIA GeForce RTX 3070 Ti Laptop GPU
### Issue description

Performace of code is 2x as slow in beta7+ than beta6.  The attached project contains code that dynamically creates a mesharray/meshinstance3d.  Performance in beta7 is greatly reduced.

### Steps to reproduce

Run the attached project in beta6, console should report the duration of the method (~.04 on my pc)

Run again in beta7, observe the output duration increasing (~.9 on my pc)

 

### Minimal reproduction project

[Repro.zip](https://github.com/godotengine/godot/files/10273414/Repro.zip)

**Comment by Calinou** [comment] 2022-12-21 00:24
If you can [compile the engine from source](https://docs.godotengine.org/en/stable/development/compiling/index.html), you could look into [bisecting the regression](https://docs.godotengine.org/en/stable/community/contributing/bisecting_regressions.html) to greatly speed up troubleshooting.

**Comment by delinx32** [comment] 2022-12-21 00:37
> If you can [compile the engine from source](https://docs.godotengine.org/en/stable/development/compiling/index.html), you could look into [bisecting the regression](https://docs.godotengine.org/en/stable/community/contributing/bisecting_regressions.html) to greatly speed up troubleshooting.
> 
> * 4.0.beta6's commit hash (`good`) is `7f8ecffa56834dce3ccbd736738b613d51133dea`.
> * 4.0.beta7's commit hash (`bad`) is `0ff8742919af72c7412e63ef0f646cb4e7bd7d8f`.

My c++ skills are sadly 20 years out of date, but I can give it a go.  I've been looking into the beta7 commits and my gut tells me it's something to do with this (purely speculation at this point).  The CreateFrom methods seem to create dynamic types.  I'm not sure yet what the old method was doing, but on the surface it seems like the new method may be generating some garbage?  

https://github.com/godotengine/godot/pull/68310/commits/3f645f980c5d7894f98075c29d1c65319be62be7

My code is doing this or code like this a few times:

                var vertices = mk.Arrays[(int)Mesh.ArrayType.Vertex].AsVector3Array();
                
I haven't yet followed the call chain to see if this leads into those methods or not.  I can probably optimize this out of my code by computing it per mesh ahead of time.  I'll give that a go later and see if it changes the execution time or not.

**Comment by Maran23** [comment] 2022-12-21 00:49
> My c++ skills are sadly 20 years out of date, but I can give it a go. I've been looking into the beta7 commits and my gut tells me it's something to do with this (purely speculation at this point). The CreateFrom methods seem to create dynamic types. I'm not sure yet what the old method was doing, but on the surface it seems like the new method may be generating some garbage?

Compiling the engine is actually very straightforward and no in-depth skills are required.
If you want you can check out the documentation here: https://docs.godotengine.org/en/latest/development/compiling/index.html

**Comment by delinx32** [comment] 2022-12-21 02:10
> > My c++ skills are sadly 20 years out of date, but I can give it a go. I've been looking into the beta7 commits and my gut tells me it's something to do with this (purely speculation at this point). The CreateFrom methods seem to create dynamic types. I'm not sure yet what the old method was doing, but on the surface it seems like the new method may be generating some garbage?
> 
> Compiling the engine is actually very straightforward and no in-depth skills are required. If you want you can check out the documentation here: https://docs.godotengine.org/en/latest/development/compiling/index.html

So, I don't know what the issue is, but I was able to fix (and get even better than beta6 performance) by changing all of the references to Godot.Collections.Array<> to List<> instead.  From my own debugging, it seems like the Array<>.Add method is what has gotten considerably slower.

**Comment by clayjohn** [comment] 2022-12-21 07:03
It sounds like this may be a dotnet specific issue

cc @raulsntos @neikeq

**Comment by lewiji** [comment] 2022-12-21 13:32
In general, using C# system collections, generic collections, and native arrays are faster (respectively) when doing lots of computation than using Godot arrays. Godot arrays are necessary when transferring data through the API, but they exist in the Godot native side of the code and that means operations on them have to be marshalled, doing that in large iterations can be a bottleneck.

Rule of thumb: any processing or manipulation of data that you want to do quickly purely in C#, use a C# collection. Any data you want to pass into godot through the API to update some node, resource or object, use a Godot collection. And be careful with multiple enumeration while iterating, ie, converting collections to other collections as this will also be slow regardless of which type of collection you use.

**Comment by delinx32** [comment] 2022-12-21 22:18
> In general, using C# system collections, generic collections, and native arrays are faster (respectively) when doing lots of computation than using Godot arrays. Godot arrays are necessary when transferring data through the API, but they exist in the Godot native side of the code and that means operations on them have to be marshalled, doing that in large iterations can be a bottleneck.
> 
> Rule of thumb: any processing or manipulation of data that you want to do quickly purely in C#, use a C# collection. Any data you want to pass into godot through the API to update some node, resource or object, use a Godot collection. And be careful with multiple enumeration while iterating, ie, converting collections to other collections as this will also be slow regardless of which type of collection you use.

I'm not sure why I was using godot arrays, other than maybe that's what was in the example I was looking at.  I'm good now, but there is still probably an issue.  I would think that anything that does use the godot collections would still exhibit this problem, even if it will no longer affect me directly.

**Comment by neikeq** [comment] 2022-12-21 22:22
This may be a regression from #68310. Perhaps the JIT is not optimizing the method as we expect.

**Comment by raulsntos** [comment] 2024-06-10 15:33
The MRP seems broken, I get this error:

> ERROR: Resource file not found: res://basicTerrain.blend (expected type: )

However, since the only function being measured (`AddRoom`) doesn't seem to require this resource, I tried removing all the unrelated code.

I was unable to see any performance degradation comparing `v4.2.2.stable.mono.official.15073afe3` with `v4.0.beta6.mono.official.7f8ecffa5`. If anyone is still able to reproduce this issue in Godot 4.2.2 or greater, please open a new issue and provide a working MRP.

**Closed by raulsntos** 2024-06-10 15:33 UTC
Labels: topic:core, needs testing, topic:dotnet, regression, topic:3d, performance
