### ISSUE TITLE
First Parallax Layer in node order bugs itself, second Parallax Layer, and first texture unrelated to parallax layers

### ISSUE THREAD

**Issue by krisaliis** [godotengine/godot#71871] opened 2023-01-22 17:50 UTC
### Godot version

4.0 Beta 14

### System information

Windows 11, RenderingDevice, Intel(R) UHD Graphics (26.20.100.7926)

### Issue description

I'm a beginner and attempted using parallax background for the first time on Godot 4.0's latest beta, but it appears to not work correctly, at least with the specifics I provided. When setting up parallex layers in a project and giving them mirroring, the first two's textures don't work properly, in a manner I'm not sure I can explain properly; plus, the first texture outside of the parallax background node seems to also bug out. Both of these happen both in the editor and in the project itself.

In the image below, the two parallax layers are set to the same x mirroring motion value, being the width of the two textures, yet the first parallax layer's texture does not actually extend past its original size. Plus, while the two Sprite2Ds have the same x value, the first one in the scene's node order for some reason shifts all the way to the right, for a distance that seems to be the exact value of the second parallax layer's x mirroring value, and changes along with it. Swapping the two background sprites, or the two Godot icons between each other, confirms the bug is related to their nodes' position in the scene, rather than the nodes themselves.
![image](https://user-images.githubusercontent.com/94058362/213929960-6340293c-acc5-4d15-8893-390c474e09ad.png)

And if one were to attempt to disable the first parallax layer's visibility, or its sprite's, the mirror version of the second parallax layer's sprite disappears with it
![image](https://user-images.githubusercontent.com/94058362/213930174-20b7f5d1-6574-4075-b854-4a64d1784731.png)

If the second parallax layer's x mirroring value is set to 0 (or really high values, whose lowest possible value that causes this seems to not be consistent), its sprite's texture disappears, but not its mirrored version, whose position is still dependant on the first parallax layer's x mirroring value.
If a third parallax layer is added as a child to the parallax background node, it will seemingly behave correctly, but if the first parallax layer is hidden in the editor, then the second and third will behave in the exact manner as the first and second parallax layer in the above examples.
The first texture unrelated to parallax layers keeps being bugged even if its node is positioned above the parallax background's in the scene node order.
Did not thoroughly test other y mirroring values, seem to also be bugged in a similar manner.
Hope I did not forget to mention anything

### Steps to reproduce

Create a new project using either the Forward+ or Mobile renderer options
Add a 2D node
Add a parallax background node as its child
Add two parallax layer nodes as its children
Add two sprite nodes, each as a parallax layer's child
Add a texture to the two sprite nodes
Set the first parallax layer's x mirroring value as anything other than 0 (bigger values' effects are more noticeable)
Optional: Set the second parallax layer's x mirroring value as anything other than 0 (makes its original texture appear)

For the bug regarding textures unrelated to parallax layers:
Add a sprite node as child of main 2D node (haven't tested with other nodes that utilize textures, but the main project I encountered this bug on had one of its tilemap node's tile textures bugged in a similar way)
Add a texture to sprite node
Set the second parallax layer's x mirroring value as anything other than 0 (bigger values' effects are more noticeable)

### Minimal reproduction project

[parallax_bug_speedrun.zip](https://github.com/godotengine/godot/files/10475063/parallax_bug_speedrun.zip)

**Comment by alberto-mco** [comment] 2023-01-23 07:55
I reported this behavior and other bug also here #67120

**Comment by Calinou** [comment] 2023-01-23 09:10
Duplicate of https://github.com/godotengine/godot/issues/67120.

**Closed by Calinou** 2023-01-23 09:10 UTC
