### ISSUE TITLE
MacBook M1 Max crashing

### ISSUE THREAD

**Issue by BliznyukNM** [godotengine/godot#66843] opened 2022-10-03 19:21 UTC
### Godot version

4.0.b2 and master (321251a133)

### System information

MacOS M1 Max, Vulkan

### Issue description

A lot of crashing causes AnimationTree.
When you run game, close it, clicking on AnimationTree will crash the editor. (not every time)
Crashing when trying to change animation node name in AnimationTree. (100%)
Here's the report after crashing:

```
-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               Godot [44169]
Path:                  /Users/USER/*/Godot 4.x.app/Contents/MacOS/Godot
Identifier:            org.godotengine.godot
Version:               4.0 (4.0)
Code Type:             ARM-64 (Native)
Parent Process:        launchd [1]
User ID:               501

Date/Time:             2022-10-03 21:05:00.3316 +0200
OS Version:            macOS 12.6 (21G115)
Report Version:        12
Anonymous UUID:        DEE261C8-FBB8-29A9-BFC6-3E6EECFDDE48

Sleep/Wake UUID:       82CA0253-81BF-4A78-898C-2C583CE4C9CE

Time Awake Since Boot: 440000 seconds
Time Since Wake:       345 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGABRT)
Exception Codes:       KERN_INVALID_ADDRESS at 0xfffffffffffffff0
Exception Codes:       0x0000000000000001, 0xfffffffffffffff0
Exception Note:        EXC_CORPSE_NOTIFY

VM Region Info: 0xfffffffffffffff0 is not in any region.  Bytes after previous region: 18446638519519543281  
      REGION TYPE                    START - END         [ VSIZE] PRT/MAX SHRMOD  REGION DETAIL
      MALLOC_NANO              600038000000-600040000000 [128.0M] rw-/rwx SM=PRV  
--->  
      UNUSED SPACE AT END

Application Specific Information:
abort() called


Thread 0 Crashed::  Dispatch queue: com.apple.main-thread
0   libsystem_kernel.dylib        	       0x18325ad98 __pthread_kill + 8
1   libsystem_pthread.dylib       	       0x18328fee0 pthread_kill + 288
2   libsystem_c.dylib             	       0x1831ca340 abort + 168
3   Godot                         	       0x1010ccef4 handle_crash(int) + 1188
4   libsystem_platform.dylib      	       0x1832a74a4 _sigtramp + 56
5   Godot                         	       0x10281fe60 void call_with_variant_args_helper<AnimationNodeBlendTreeEditor, Node*, Ref<AnimationNode>, 0ul, 1ul>(AnimationNodeBlendTreeEditor*, void (AnimationNodeBlendTreeEditor::*)(Node*, Ref<AnimationNode>), Variant const**, Callable::CallError&, IndexSequence<0ul, 1ul>) + 136
6   Godot                         	       0x10281fe60 void call_with_variant_args_helper<AnimationNodeBlendTreeEditor, Node*, Ref<AnimationNode>, 0ul, 1ul>(AnimationNodeBlendTreeEditor*, void (AnimationNodeBlendTreeEditor::*)(Node*, Ref<AnimationNode>), Variant const**, Callable::CallError&, IndexSequence<0ul, 1ul>) + 136
7   Godot                         	       0x104df3bb8 CallableCustomBind::call(Variant const**, int, Variant&, Callable::CallError&) const + 452
8   Godot                         	       0x105164f14 MessageQueue::_call_function(Callable const&, Variant const*, int, bool) + 324
9   Godot                         	       0x10516528c MessageQueue::flush() + 276
10  Godot                         	       0x103043820 SceneTree::physics_process(double) + 456
11  Godot                         	       0x10111c078 Main::iteration() + 520
12  Godot                         	       0x1010ca050 OS_MacOS::run() + 136
13  Godot                         	       0x1010f0e28 main + 404
14  dyld                          	       0x108d5d08c start + 520

Thread 1:
0   libsystem_pthread.dylib       	       0x18328b078 start_wqthread + 0

Thread 2:
0   libsystem_pthread.dylib       	       0x18328b078 start_wqthread + 0

Thread 3:
0   libsystem_pthread.dylib       	       0x18328b078 start_wqthread + 0

Thread 4:
0   libsystem_pthread.dylib       	       0x18328b078 start_wqthread + 0

Thread 5:
0   libsystem_kernel.dylib        	       0x183256270 __psynch_cvwait + 8
1   libsystem_pthread.dylib       	       0x18329083c _pthread_cond_wait + 1236
2   libc++.1.dylib                	       0x1831df284 std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&) + 28
3   Godot                         	       0x104ca2908 _IP_ResolverPrivate::_thread_function(void*) + 160
4   Godot                         	       0x104b77e8c Thread::callback(Thread*, Thread::Settings const&, void (*)(void*), void*) + 148
5   Godot                         	       0x104b783f8 void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void (*)(Thread*, Thread::Settings const&, void (*)(void*), void*), Thread*, Thread::Settings, void (*)(void*), void*> >(void*) + 52
6   libsystem_pthread.dylib       	       0x18329026c _pthread_start + 148
7   libsystem_pthread.dylib       	       0x18328b08c thread_start + 8

Thread 6:
0   libsystem_kernel.dylib        	       0x183256270 __psynch_cvwait + 8
1   libsystem_pthread.dylib       	       0x18329083c _pthread_cond_wait + 1236
2   libc++.1.dylib                	       0x1831df284 std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&) + 28
3   Godot                         	       0x1051c6bd4 WorkerThreadPool::_thread_function(void*) + 84
4   Godot                         	       0x104b77e8c Thread::callback(Thread*, Thread::Settings const&, void (*)(void*), void*) + 148
5   Godot                         	       0x104b783f8 void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void (*)(Thread*, Thread::Settings const&, void (*)(void*), void*), Thread*, Thread::Settings, void (*)(void*), void*> >(void*) + 52
6   libsystem_pthread.dylib       	       0x18329026c _pthread_start + 148
7   libsystem_pthread.dylib       	       0x18328b08c thread_start + 8

Thread 7:
0   libsystem_kernel.dylib        	       0x183256270 __psynch_cvwait + 8
1   libsystem_pthread.dylib       	       0x18329083c _pthread_cond_wait + 1236
2   libc++.1.dylib                	       0x1831df284 std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&) + 28
3   Godot                         	       0x1051c6bd4 WorkerThreadPool::_thread_function(void*) + 84
4   Godot                         	       0x104b77e8c Thread::callback(Thread*, Thread::Settings const&, void (*)(void*), void*) + 148
5   Godot                         	       0x104b783f8 void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void (*)(Thread*, Thread::Settings const&, void (*)(void*), void*), Thread*, Thread::Settings, void (*)(void*), void*> >(void*) + 52
6   libsystem_pthread.dylib       	       0x18329026c _pthread_start + 148
7   libsystem_pthread.dylib       	       0x18328b08c thread_start + 8

Thread 8:
0   libsystem_kernel.dylib        	       0x183256270 __psynch_cvwait + 8
1   libsystem_pthread.dylib       	       0x18329083c _pthread_cond_wait + 1236
2   libc++.1.dylib                	       0x1831df284 std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&) + 28
3   Godot                         	       0x1051c6bd4 WorkerThreadPool::_thread_function(void*) + 84
4   Godot                         	       0x104b77e8c Thread::callback(Thread*, Thread::Settings const&, void (*)(void*), void*) + 148
5   Godot                         	       0x104b783f8 void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void (*)(Thread*, Thread::Settings const&, void (*)(void*), void*), Thread*, Thread::Settings, void (*)(void*), void*> >(void*) + 52
6   libsystem_pthread.dylib       	       0x18329026c _pthread_start + 148
7   libsystem_pthread.dylib       	       0x18328b08c thread_start + 8

Thread 9:
0   libsystem_kernel.dylib        	       0x183256270 __psynch_cvwait + 8
1   libsystem_pthread.dylib       	       0x18329083c _pthread_cond_wait + 1236
2   libc++.1.dylib                	       0x1831df284 std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&) + 28
3   Godot                         	       0x1051c6bd4 WorkerThreadPool::_thread_function(void*) + 84
4   Godot                         	       0x104b77e8c Thread::callback(Thread*, Thread::Settings const&, void (*)(void*), void*) + 148
5   Godot                         	       0x104b783f8 void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void (*)(Thread*, Thread::Settings const&, void (*)(void*), void*), Thread*, Thread::Settings, void (*)(void*), void*> >(void*) + 52
6   libsystem_pthread.dylib       	       0x18329026c _pthread_start + 148
7   libsystem_pthread.dylib       	       0x18328b08c thread_start + 8

Thread 10:
0   libsystem_kernel.dylib        	       0x183256270 __psynch_cvwait + 8
1   libsystem_pthread.dylib       	       0x18329083c _pthread_cond_wait + 1236
2   libc++.1.dylib                	       0x1831df284 std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&) + 28
3   Godot                         	       0x1051c6bd4 WorkerThreadPool::_thread_function(void*) + 84
4   Godot                         	       0x104b77e8c Thread::callback(Thread*, Thread::Settings const&, void (*)(void*), void*) + 148
5   Godot                         	       0x104b783f8 void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void (*)(Thread*, Thread::Settings const&, void (*)(void*), void*), Thread*, Thread::Settings, void (*)(void*), void*> >(void*) + 52
6   libsystem_pthread.dylib       	       0x18329026c _pthread_start + 148
7   libsystem_pthread.dylib       	       0x18328b08c thread_start + 8

Thread 11:
0   libsystem_kernel.dylib        	       0x183256270 __psynch_cvwait + 8
1   libsystem_pthread.dylib       	       0x18329083c _pthread_cond_wait + 1236
2   libc++.1.dylib                	       0x1831df284 std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&) + 28
3   Godot                         	       0x1051c6bd4 WorkerThreadPool::_thread_function(void*) + 84
4   Godot                         	       0x104b77e8c Thread::callback(Thread*, Thread::Settings const&, void (*)(void*), void*) + 148
5   Godot                         	       0x104b783f8 void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void (*)(Thread*, Thread::Settings const&, void (*)(void*), void*), Thread*, Thread::Settings, void (*)(void*), void*> >(void*) + 52
6   libsystem_pthread.dylib       	       0x18329026c _pthread_start + 148
7   libsystem_pthread.dylib       	       0x18328b08c thread_start + 8

Thread 12:
0   libsystem_kernel.dylib        	       0x183256270 __psynch_cvwait + 8
1   libsystem_pthread.dylib       	       0x18329083c _pthread_cond_wait + 1236
2   libc++.1.dylib                	       0x1831df284 std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&) + 28
3   Godot                         	       0x1051c6bd4 WorkerThreadPool::_thread_function(void*) + 84
4   Godot                         	       0x104b77e8c Thread::callback(Thread*, Thread::Settings const&, void (*)(void*), void*) + 148
5   Godot                         	       0x104b783f8 void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void (*)(Thread*, Thread::Settings const&, void (*)(void*), void*), Thread*, Thread::Settings, void (*)(void*), void*> >(void*) + 52
6   libsystem_pthread.dylib       	       0x18329026c _pthread_start + 148
7   libsystem_pthread.dylib       	       0x18328b08c thread_start + 8

Thread 13:
0   libsystem_kernel.dylib        	       0x183256270 __psynch_cvwait + 8
1   libsystem_pthread.dylib       	       0x18329083c _pthread_cond_wait + 1236
2   libc++.1.dylib                	       0x1831df284 std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&) + 28
3   Godot                         	       0x1051c6bd4 WorkerThreadPool::_thread_function(void*) + 84
4   Godot                         	       0x104b77e8c Thread::callback(Thread*, Thread::Settings const&, void (*)(void*), void*) + 148
5   Godot                         	       0x104b783f8 void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void (*)(Thread*, Thread::Settings const&, void (*)(void*), void*), Thread*, Thread::Settings, void (*)(void*), void*> >(void*) + 52
6   libsystem_pthread.dylib       	       0x18329026c _pthread_start + 148
7   libsystem_pthread.dylib       	       0x18328b08c thread_start + 8

Thread 14:
0   libsystem_kernel.dylib        	       0x183256270 __psynch_cvwait + 8
1   libsystem_pthread.dylib       	       0x18329083c _pthread_cond_wait + 1236
2   libc++.1.dylib                	       0x1831df284 std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&) + 28
3   Godot                         	       0x1051c6bd4 WorkerThreadPool::_thread_function(void*) + 84
4   Godot                         	       0x104b77e8c Thread::callback(Thread*, Thread::Settings const&, void (*)(void*), void*) + 148
5   Godot                         	       0x104b783f8 void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void (*)(Thread*, Thread::Settings const&, void (*)(void*), void*), Thread*, Thread::Settings, void (*)(void*), void*> >(void*) + 52
6   libsystem_pthread.dylib       	       0x18329026c _pthread_start + 148
7   libsystem_pthread.dylib       	       0x18328b08c thread_start + 8

Thread 15:
0   libsystem_kernel.dylib        	       0x183256270 __psynch_cvwait + 8
1   libsystem_pthread.dylib       	       0x18329083c _pthread_cond_wait + 1236
2   libc++.1.dylib                	       0x1831df284 std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&) + 28
3   Godot                         	       0x1051c6bd4 WorkerThreadPool::_thread_function(void*) + 84
4   Godot                         	       0x104b77e8c Thread::callback(Thread*, Thread::Settings const&, void (*)(void*), void*) + 148
5   Godot                         	       0x104b783f8 void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void (*)(Thread*, Thread::Settings const&, void (*)(void*), void*), Thread*, Thread::Settings, void (*)(void*), void*> >(void*) + 52
6   libsystem_pthread.dylib       	       0x18329026c _pthread_start + 148
7   libsystem_pthread.dylib       	       0x18328b08c thread_start + 8

Thread 16:: AMCP Logging Spool
0   libsystem_kernel.dylib        	       0x1832528ec semaphore_wait_trap + 8
1   caulk                         	       0x18bd05a2c caulk::mach::semaphore::wait_or_error() + 28
2   caulk                         	       0x18bce97ac caulk::concurrent::details::worker_thread::run() + 56
3   caulk                         	       0x18bce93cc void* caulk::thread_proxy<std::__1::tuple<caulk::thread::attributes, void (caulk::concurrent::details::worker_thread::*)(), std::__1::tuple<caulk::concurrent::details::worker_thread*> > >(void*) + 96
4   libsystem_pthread.dylib       	       0x18329026c _pthread_start + 148
5   libsystem_pthread.dylib       	       0x18328b08c thread_start + 8

Thread 17:: com.apple.audio.IOThread.client
0   libsystem_kernel.dylib        	       0x1832528b0 mach_msg_trap + 8
1   libsystem_kernel.dylib        	       0x183252d20 mach_msg + 76
2   CoreAudio                     	       0x184fa26a0 HALB_MachPort::SendSimpleMessageWithSimpleReply(unsigned int, unsigned int, int, int&, bool, unsigned int) + 104
3   CoreAudio                     	       0x184e2fbb0 HALC_ProxyIOContext::IOWorkLoop() + 3336
4   CoreAudio                     	       0x184e2e8b0 invocation function for block in HALC_ProxyIOContext::HALC_ProxyIOContext(unsigned int, unsigned int) + 100
5   CoreAudio                     	       0x184ffaab0 HALB_IOThread::Entry(void*) + 88
6   libsystem_pthread.dylib       	       0x18329026c _pthread_start + 148
7   libsystem_pthread.dylib       	       0x18328b08c thread_start + 8

Thread 18:
0   libsystem_kernel.dylib        	       0x183256270 __psynch_cvwait + 8
1   libsystem_pthread.dylib       	       0x18329083c _pthread_cond_wait + 1236
2   libc++.1.dylib                	       0x1831df284 std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&) + 28
3   Godot                         	       0x1019139d8 tvg::TaskQueue::pop(tvg::Task**) + 80
4   Godot                         	       0x101913860 tvg::TaskSchedulerImpl::run(unsigned int) + 72
5   Godot                         	       0x1019137b8 void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, tvg::TaskSchedulerImpl::TaskSchedulerImpl(unsigned int)::'lambda'()> >(void*) + 48
6   libsystem_pthread.dylib       	       0x18329026c _pthread_start + 148
7   libsystem_pthread.dylib       	       0x18328b08c thread_start + 8

Thread 19:
0   libsystem_kernel.dylib        	       0x18325606c __semwait_signal + 8
1   libsystem_c.dylib             	       0x18315efc8 nanosleep + 220
2   Godot                         	       0x101c26fa0 OS_Unix::delay_usec(unsigned int) const + 64
3   Godot                         	       0x101d63e40 EditorExportPlatformAndroid::_check_for_changes_poll_thread(void*) + 8448
4   Godot                         	       0x104b77e8c Thread::callback(Thread*, Thread::Settings const&, void (*)(void*), void*) + 148
5   Godot                         	       0x104b783f8 void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void (*)(Thread*, Thread::Settings const&, void (*)(void*), void*), Thread*, Thread::Settings, void (*)(void*), void*> >(void*) + 52
6   libsystem_pthread.dylib       	       0x18329026c _pthread_start + 148
7   libsystem_pthread.dylib       	       0x18328b08c thread_start + 8

Thread 20:
0   libsystem_kernel.dylib        	       0x18325606c __semwait_signal + 8
1   libsystem_c.dylib             	       0x18315efc8 nanosleep + 220
2   Godot                         	       0x101c26fa0 OS_Unix::delay_usec(unsigned int) const + 64
3   Godot                         	       0x101de3478 EditorExportPlatformIOS::_check_for_changes_poll_thread(void*) + 496
4   Godot                         	       0x104b77e8c Thread::callback(Thread*, Thread::Settings const&, void (*)(void*), void*) + 148
5   Godot                         	       0x104b783f8 void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void (*)(Thread*, Thread::Settings const&, void (*)(void*), void*), Thread*, Thread::Settings, void (*)(void*), void*> >(void*) + 52
6   libsystem_pthread.dylib       	       0x18329026c _pthread_start + 148
7   libsystem_pthread.dylib       	       0x18328b08c thread_start + 8

Thread 21:
0   libsystem_kernel.dylib        	       0x18325606c __semwait_signal + 8
1   libsystem_c.dylib             	       0x18315efc8 nanosleep + 220
2   Godot                         	       0x101c26fa0 OS_Unix::delay_usec(unsigned int) const + 64
3   Godot                         	       0x101e9174c EditorExportPlatformWeb::_server_thread_poll(void*) + 48
4   Godot                         	       0x104b77e8c Thread::callback(Thread*, Thread::Settings const&, void (*)(void*), void*) + 148
5   Godot                         	       0x104b783f8 void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void (*)(Thread*, Thread::Settings const&, void (*)(void*), void*), Thread*, Thread::Settings, void (*)(void*), void*> >(void*) + 52
6   libsystem_pthread.dylib       	       0x18329026c _pthread_start + 148
7   libsystem_pthread.dylib       	       0x18328b08c thread_start + 8

Thread 22:
0   libsystem_kernel.dylib        	       0x18325606c __semwait_signal + 8
1   libsystem_c.dylib             	       0x18315efc8 nanosleep + 220
2   Godot                         	       0x101c26fa0 OS_Unix::delay_usec(unsigned int) const + 64
3   Godot                         	       0x1026c485c EditorFileServer::_thread_start(void*) + 600
4   Godot                         	       0x104b77e8c Thread::callback(Thread*, Thread::Settings const&, void (*)(void*), void*) + 148
5   Godot                         	       0x104b783f8 void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void (*)(Thread*, Thread::Settings const&, void (*)(void*), void*), Thread*, Thread::Settings, void (*)(void*), void*> >(void*) + 52
6   libsystem_pthread.dylib       	       0x18329026c _pthread_start + 148
7   libsystem_pthread.dylib       	       0x18328b08c thread_start + 8

Thread 23:
0   libsystem_kernel.dylib        	       0x183256270 __psynch_cvwait + 8
1   libsystem_pthread.dylib       	       0x18329083c _pthread_cond_wait + 1236
2   libc++.1.dylib                	       0x1831df284 std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&) + 28
3   Godot                         	       0x102eeb3e8 TilesEditorPlugin::_thread() + 260
4   Godot                         	       0x104b77e8c Thread::callback(Thread*, Thread::Settings const&, void (*)(void*), void*) + 148
5   Godot                         	       0x104b783f8 void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void (*)(Thread*, Thread::Settings const&, void (*)(void*), void*), Thread*, Thread::Settings, void (*)(void*), void*> >(void*) + 52
6   libsystem_pthread.dylib       	       0x18329026c _pthread_start + 148
7   libsystem_pthread.dylib       	       0x18328b08c thread_start + 8

Thread 24:: com.apple.NSEventThread
0   libsystem_kernel.dylib        	       0x1832528b0 mach_msg_trap + 8
1   libsystem_kernel.dylib        	       0x183252d20 mach_msg + 76
2   CoreFoundation                	       0x18335d210 __CFRunLoopServiceMachPort + 372
3   CoreFoundation                	       0x18335b6c0 __CFRunLoopRun + 1180
4   CoreFoundation                	       0x18335aa84 CFRunLoopRunSpecific + 600
5   AppKit                        	       0x18602f100 _NSEventThread + 196
6   libsystem_pthread.dylib       	       0x18329026c _pthread_start + 148
7   libsystem_pthread.dylib       	       0x18328b08c thread_start + 8

Thread 25:
0   libsystem_kernel.dylib        	       0x183256270 __psynch_cvwait + 8
1   libsystem_pthread.dylib       	       0x18329083c _pthread_cond_wait + 1236
2   libc++.1.dylib                	       0x1831df284 std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&) + 28
3   Godot                         	       0x1022fc130 EditorResourcePreview::_thread() + 136
4   Godot                         	       0x104b77e8c Thread::callback(Thread*, Thread::Settings const&, void (*)(void*), void*) + 148
5   Godot                         	       0x104b783f8 void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void (*)(Thread*, Thread::Settings const&, void (*)(void*), void*), Thread*, Thread::Settings, void (*)(void*), void*> >(void*) + 52
6   libsystem_pthread.dylib       	       0x18329026c _pthread_start + 148
7   libsystem_pthread.dylib       	       0x18328b08c thread_start + 8


Thread 0 crashed with ARM Thread State (64-bit):
    x0: 0x0000000000000000   x1: 0x0000000000000000   x2: 0x0000000000000000   x3: 0x0000000000000000
    x4: 0x0000000101ac58c8   x5: 0x000000016f0f8ab0   x6: 0x000000012c1a01e8   x7: 0x000000016f0f8b30
    x8: 0xe990f76a0234c298   x9: 0xe990f76b0ae9c718  x10: 0x0000000000000002  x11: 0x00000000fffffffd
   x12: 0x0000010000000000  x13: 0x0000000000000000  x14: 0x0000000000000000  x15: 0x0000000000000000
   x16: 0x0000000000000148  x17: 0x00000001dd3b3680  x18: 0x0000000000000000  x19: 0x0000000000000006
   x20: 0x0000000108dd0580  x21: 0x0000000000000103  x22: 0x0000000108dd0660  x23: 0x000000000000000c
   x24: 0x0000000106e0346b  x25: 0x000000016f0f91c8  x26: 0x00000001010cb0ac  x27: 0x00000000ffffffff
   x28: 0x0000000000000000   fp: 0x000000016f0f8cc0   lr: 0x000000018328fee0
    sp: 0x000000016f0f8ca0   pc: 0x000000018325ad98 cpsr: 0x40001000
   far: 0x00000001d949a4f0  esr: 0x56000080  Address size fault

```

### Steps to reproduce

Create AnimationNodeBlendTree in AnimationTree. Add Animation node inside. Enter a new name for Animation node. Click 'Enter'.

**Comment by Calinou** [comment] 2022-10-03 21:08
Duplicate of https://github.com/godotengine/godot/issues/40368.

**Closed by Calinou** 2022-10-03 21:08 UTC
Labels: bug, platform:macos, topic:core, needs testing, crash
