### ISSUE TITLE
Duplicate GDScript file when  copy scene from another project

### ISSUE THREAD

**Issue by git2013vb** [godotengine/godot#35204] opened 2020-01-16 15:02 UTC
**Godot version:**
3.2.beta6.mono
**OS/device including version:**
Debian 10
**Issue description:**
![image](https://user-images.githubusercontent.com/13235119/72535535-9bd2d680-3870-11ea-8d16-4d63edaddbeb.png)
The script related a scene is duplicated, If I do some changes in one the other one remain without that modification. As they are 2 different scripts
I file manager I see 1 script only
![image](https://user-images.githubusercontent.com/13235119/72535782-07b53f00-3871-11ea-9526-f4bc6f0c1292.png)

but after copy I have another file in res:// 
![image](https://user-images.githubusercontent.com/13235119/72536443-28ca5f80-3872-11ea-80d3-d81415ea2bcc.png)

The .tscn scene point to the file  placed n root project not the one  in his folder.

There are no any inner script in .tscn file
Then if I try to close the project is not work. I have to kill the process/close the terminal

**Steps to reproduce:**
I copied a scene from another project and his script. 

**Minimal reproduction project:**
NA

**Comment by Calinou** [comment] 2020-01-16 18:37
@git2013vb Please upload a minimal reproduction project to make this easier to reproduce.

**Comment by git2013vb** [comment] 2020-01-17 12:05
> @git2013vb Please upload a minimal reproduction project to make this easier to reproduce.

Mostly of these issues happen once a time.  For a different situations that is difficult to replicate even because I get them when I have already done some steps that I did't keep in mind. Also in other cases it will be useful to have a clear error message instead "error x=null" ;)

**Comment by KoBeWi** [comment] 2020-12-16 01:09
The issue is too vague. I tried the steps and nothing wrong happened, as expected.

Closing. Comment if you have more detailed steps and a minimal reproduction project. (also make sure to try the newest stable release)

**Closed by KoBeWi** 2020-12-16 01:09 UTC
Labels: bug, topic:editor
