### ISSUE TITLE
_get() only gets triggered in a tool script when you reselect its node. 

### ISSUE THREAD

**Issue by jtaart** [godotengine/godot#12620] opened 2017-11-03 23:55 UTC
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Windows 8.1
Godot_v2.1.4-stable_win64

**Issue description:**
To trigger _get() when a resource is updated you have to un-select the node with the tool script than re-select it.

**Steps to reproduce:**
Video: [https://youtu.be/lHn9Wnb5HY4](https://youtu.be/lHn9Wnb5HY4)

**Comment by akien-mga** [comment] 2018-01-15 11:06
Is this still reproducible in Godot 3.0 RC1?

**Comment by jtaart** [comment] 2018-01-15 22:33
You still have to switch nodes to signal _get() in Godot 3.0 RC1 when it comes to a resource like Curve.

[https://i.imgur.com/MwaQ9VV.gifv](https://i.imgur.com/MwaQ9VV.gifv)

```
func _get(property):
    if property == "curve" and is_ready:
        setupChain()
```

**Comment by Calinou** [comment] 2020-06-14 14:53
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!

**Closed by Calinou** 2020-06-14 14:53 UTC
Labels: enhancement, topic:editor

**Comment by jtaart** [comment] 2020-06-14 17:45
This seems more like a bug to me. I don't think, other properties do this, maybe I'm mistaken.

**Comment by KoBeWi** [comment] 2020-06-14 18:24
This is not a bug. When you click a node, the inspector is updated with the values from the node, so it uses `_get()` to fetch these values. Relying on it to update something is a wrong use.

The missing feature I see is lack of `curve_changed` signal in Path2D (it exists in Path). For a workaround, you can add `_process()` function to your script and manually check if the path changes. It sounds costly, but you do it only in the editor anyways.

**Comment by jtaart** [comment] 2020-06-14 19:09
@KoBeWi thanks for the info.
