### ISSUE TITLE
Evaluate expression inside script editor

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#24074] opened 2018-11-30 00:07 UTC
Basically this (from VS Code):
![screen_recorder_plus_video_2018_30_11_01_01_54](https://user-images.githubusercontent.com/2223172/49259973-c5962780-f43b-11e8-92aa-c07d5c7aa7fe.gif)

Evaluate an expression with keyboard shortcut (something that's somewhat already in inspector's number input boxes) Allows for quick maths, so you don't need to leave some weird expressions in the code like `node.position += 131 + 34` or fire up a calculator each time you need this.

**Comment by Chaosus** [comment] 2018-11-30 11:09
Looks like a duplicate of https://github.com/godotengine/godot/issues/18932 but that issue was closed, for whatever reason.. Its still not fixed at all

**Comment by piratesephiroth** [comment] 2018-11-30 13:01
@Chaosus, yeah it seems very fixed. Expressions in fields are solved when we hit Enter.

**Comment by KoBeWi** [comment] 2018-11-30 13:04
Uh, that's totally different issue. I just mentioned that we can do that in the inspector, but I'm proposing adding this functionality for script editor, so you can evaluate simple expressions when writing a script.

**Comment by eon-s** [comment] 2018-12-02 00:53
Only if optional +off by default, it is common to do many operations before seeing a pattern and automatic solving will make things harder.

I wonder if the code editor can get plugins for things like this (I remember that somebody made a `Color()` picker for Godot 2).

**Comment by KoBeWi** [comment] 2018-12-02 00:59
> +1 for this, but only if it's optionable. my head will explode if it's a default feature ty

> Only if optional +off by default, it is common to do many operations before seeing a pattern and automatic solving will make things harder.

But I said that it should be done with keyboard shortcut, so not sure what's your problem >_>

**Closed** 2019-08-12 09:19 UTC
Labels: feature proposal, topic:editor
