### ISSUE TITLE
Godot freezes when the AssetLib tab is opened due to RichTextLabel bug

### ISSUE THREAD

**Issue by gabe00122** [godotengine/godot#16072] opened 2018-01-25 22:54 UTC
**Godot version:**

3.0-rc3

**OS/device including version:**

Windows 10 x64

When I open the AssetLib tab from inside an empty project Godot's main window freezes.

The following error is written to the console in a infinite loop:
ERROR: RichTextLabel::_process_line: Index line=0 out of size (l.offset_caches.size()=0)
   At: scene\gui\rich_text_label.cpp:117

I'm haven't unfortunately been able to consistently reproduce this error, but it's happened to me twice on two separate windows machines. In both cases it was the first time I have run Godot on that machine. Both of the projects were empty. 

I hope this was helpful.

**Comment by akien-mga** [comment] 2018-01-25 22:58
CC @bojidar-bg

**Comment by bojidar-bg** [comment] 2018-02-05 11:28
Can't confirm on my machine (Arch Linux) using self-contained mode.

**Comment by vnen** [comment] 2018-02-05 14:04
It doesn't freeze for me but it stutters. Don't know if it's caused by the connection poll or by the large amount of prints to the console.

**Comment by akien-mga** [comment] 2019-01-26 11:12
Can anyone reproduce this issue in the current master branch?

**Comment by Faless** [comment] 2019-01-27 09:43
> Can anyone reproduce this issue in the current master branch?

I remember encountering this months ago, both as described by the OP and @paul-dosenbrot .
I haven't seen it again for a while now.

**Comment by menip** [comment] 2019-06-03 03:28
Potentially related: On linux, with empty project and slow internet connection switching quickly between asset lib and another "tab" causes editor to freeze up. From what I can tell, it's when asset lib initially load until asset lib is completely loaded

**Comment by menip** [comment] 2019-06-03 03:29
Can someone still reproduce the original issue?

**Comment by winston-yallow** [comment] 2019-06-11 22:28
I was able to reproduce what menip mentioned. I was not able to reproduce the original issue on linux. I will try to reproduce the original issue on Windows 10 tomorrow, but I think I did not experience this in the last time (thought I do not use Godot on Windows often).

**Comment by winston-yallow** [comment] 2019-06-17 14:09
I could not reproduce this on windows 10 anymore (even with very slow internet), seems to be fixed for me.

**Comment by vnen** [comment] 2019-11-01 19:19
Seems like this is already solved them. We can reopen if someone can reproduce it.

**Comment by Arech** [comment] 2020-05-16 15:46
@vnen The root cause of freezing is still unsolved. I'm having it too in latest 3.2.1.stable (in a different context though, but I don't think it matters). Please, check my comment in neighbouring issue https://github.com/godotengine/godot/issues/17815#issuecomment-629664152 , I may have specified correct direct cause of freezing there (but I have no idea, how the engine comes into a state when the issue fires)

**Comment by Faless** [comment] 2020-05-18 01:33
@Calinou the user reports the error not to happen with the asset lib, but with the one click deploy/debug options (see the linked comment and follow-up).
Closing, let's discuss this in only once place: #17815 .

**Closed by Faless** 2020-05-18 01:33 UTC
Labels: bug, hero wanted!, needs testing, platform:windows, topic:assetlib
