### ISSUE TITLE
The HTTPRequest only downloads 15kb for each file on Windows 11

### ISSUE THREAD

**Issue by NonoIceOff** [godotengine/godot#55061] opened 2021-11-17 17:13 UTC
### Godot version

3.4.stable

### System information

Windows 11

### Issue description

I created a launcher which downloads files for my game (you can choose the version, and click on the button to download it, and press the button again to play it if already downloaded).
For that I use the HTTPRequest, which looks in a pastebin (I use a parse with these characters "---" to differentiate the name of the versions and the two download links of the game)
On Windows 10 it worked pretty well, but on Winsows 11 it doesn't work anymore because the HTTPRequest only downloads 15kb max for each file. I would like to point out that my download link is a lot more than 15kb

```
func _on_Button_PM_pressed():
	var dir = Directory.new()
	if dir.dir_exists("user://"+VarGlobales.VersionName) == false: ## for download the files of the game version selected
		disabled = true
		dir.open("user://")
		dir.make_dir(VarGlobales.VersionName)
		$HTTPRequest.set_download_file("user://"+str(VarGlobales.VersionName)+"/Platform Master.exe")
		$HTTPRequest.request(VarGlobales.Versionlink)
	
	pass # Replace with function body.
```

VarGlobales.VersionName is the variable who contains the name of the version selected.
VarGlobales.Versionlink it is a variable which contains the download link in a string

### Steps to reproduce

To be more understandable, I created a project specifically for you to remake this bug very simply: 
[Windows11DownloadingGodotBug.zip](https://github.com/godotengine/godot/files/7556592/Windows11DownloadingGodotBug.zip)

- Click on the download button
- Go to the project folder then in the Version folder and you will find the downloaded file
Here is.

### Minimal reproduction project

I created a much simpler version of the project for you to show you this bug.
[Windows11DownloadingGodotBug.zip](https://github.com/godotengine/godot/files/7556572/Windows11DownloadingGodotBug.zip)

**Comment by Calinou** [comment] 2021-11-17 17:30
Can you reproduce this if you modify the download chunk size *before* starting the download? You can do this using the `download_chunk_size` property in HTTPRequest. Try a small value (4096 = 4 KB) then a larger value (262144 = 256 KB).

**Comment by NonoIceOff** [comment] 2021-11-18 16:35
I tested with the 2 values, it still does not work

**Comment by NonoIceOff** [comment] 2021-12-29 16:19
No other solutions?

**Comment by mhilbrunner** [comment] 2021-12-29 16:48
Hey! Does this issue occur on earlier Godot versions?
Thanks for providing a MVP, I'll check this out.
Sorry it took a bit to get a response on this, end of year business and all :)

**Comment by NonoIceOff** [comment] 2021-12-29 18:38
Yes, I even had to update Godot just for that but it doesn't work.

**Comment by NonoIceOff** [comment] 2022-01-12 14:57
it also does not work even when I put an image to download, it gives an incomplete image of 15kb

**Comment by mhilbrunner** [comment] 2022-01-13 18:40
I had no success trying to reproduce this yet, neither on Win11 nor on Win10.
HTTP downloads seem to work fine for me.
Aside: the MVP contains some invalid code and a download URL that isn't available anymore. But using my own downloads, everything seems fine so far.

Hope someone else can reproduce this or maybe someone else encounters this on Windows 11, so far I haven't seen other reports. Maybe https://github.com/godotengine/godot/issues/54310 could be relevant, nto sure.

**Comment by akien-mga** [comment] 2022-05-04 21:38
@NonoIceOff Are you still able to reproduce this issue in 3.4.4 or 3.5 beta 5 or later?

**Comment by akien-mga** [comment] 2022-06-10 09:39
No answer, and Max couldn't reproduce it with the provided project, so closing.

**Closed by akien-mga** 2022-06-10 09:39 UTC
Labels: bug, platform:windows, needs testing, topic:network
