### ISSUE TITLE
Unable to change Node Type to Node3D in Advanced Import settings

### ISSUE THREAD

**Issue by mikest** [godotengine/godot#83302] opened 2023-10-14 01:24 UTC
### Godot version

4.1.2

### System information

Godot v4.1.2.stable - Windows 10.0.22621 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 4090 (NVIDIA; 31.0.15.3598) - 13th Gen Intel(R) Core(TM) i9-13900K (32 Threads)

### Issue description

I have run into an issue while Re-importing gltf models after changing the root node type from Node3D to RigidBody3D. I can no longer change back to Node3D. The changes don't stick on subsequent re-imports

This would be on 4.1.2

Seems related to Issue #78140

### Steps to reproduce

I'm using "kaykit_halloween_bits" asset pack.

1. Import a gltf object by dragging it into the editor window
2. Double click on the asset to open "advanced import"
3. Change the Node Type to `RigidBody3D`
4. Import
5. Change the Node Type back to `Node3D`
6. Reimport
7. Notice that the node type for the newly imported node is still RigidBody3D

### Minimal reproduction project

N/A

**Comment by mikest** [comment] 2023-10-14 01:29
I have found a workaround. By using the Import *Tab* (instead of the import *Dialog*), selecting the gltf, and then editing the node_type and using Reimport(*) I was able to get the reimported node to revert back to the Node3D type.

**Comment by aaronfranke** [comment] 2023-10-14 02:17
This should be fixed in Godot 4.2 or later. Please test with the recently released [Godot 4.2 beta 1](https://godotengine.org/article/dev-snapshot-godot-4-2-beta-1/).

**Comment by AThousandShips** [comment] 2023-10-14 12:12
Duplicate of #78140

**Closed by AThousandShips** 2023-10-14 12:12 UTC
