### ISSUE TITLE
Rotating a DirectionalLight3D uses huge amounts of GPU time

### ISSUE THREAD

**Issue by tavurth** [godotengine/godot#58068] opened 2022-02-13 22:22 UTC
### Godot version

v4.0.alpha.calinou [26b21dc0c]

### System information

Mac OSX (Intel 2019)

### Issue description

When rotating a light 3D a large amount of GPU time is used.

My GPU usage spikes to above 80% and all the fans turn on.

I ran a CPU profile but seems there's not much there, so it must be in the shader code.

Forward mobile driver:
<img width="1440" alt="Screenshot 2022-02-14 at 01 20 04" src="https://user-images.githubusercontent.com/100964/153777685-fbf3d42f-4b83-4da8-bf40-c7a44efc0271.png">

On the forward composite driver the GPU is still maxed out, but it is considerably smoother.

### Steps to reproduce

1. Add directional light
2. Rotate directional light

**Comment by Calinou** [comment] 2022-02-13 23:25
Duplicate of https://github.com/godotengine/godot/issues/53969.

**Closed by Calinou** 2022-02-13 23:25 UTC
