### ISSUE TITLE
Dollar sign don't highlight on Text Edit syntax highlighting

### ISSUE THREAD

**Issue by Thedupy** [godotengine/godot#50426] opened 2021-07-13 15:12 UTC
### Godot version

3.3.stable

### System information

Windows 10, Nvidia 2080 Super, GLES3

### Issue description

I try to add the dollar sign ($) to the syntax highlighting of a TextEdit Node.
But when I write in the text edit, the dollar sign is not highlighted, but it work with other currency symbol (€, £)

### Steps to reproduce

Create a Text Edit Node
Activate "Syntax Highlighting" in the inspector
In a script, use "add_keyword_color("$", Color(0.78432, 0.040009, 0.914063))
Launch the scene, and write a dollar sign

### Minimal reproduction project

[TextEditDollarBug.zip](https://github.com/godotengine/godot/files/6808639/TextEditDollarBug.zip)

**Comment by Paulb23** [comment] 2021-07-13 16:30
Duplicate of #30586

**Closed by Paulb23** 2021-07-13 16:30 UTC
Labels: bug, topic:gui
