### ISSUE TITLE
autocompletion fails for variables initialized from onready

### ISSUE THREAD

**Issue by SandyVoidez** [godotengine/godot#54632] opened 2021-11-05 15:12 UTC
### Godot version

3.3.4 stable

### System information

Windows 10, GLES 3, Intel HD Graphics 620

### Issue description

I have several problems with inconsistent autocompletion.
I want to init my variables in _ready func, because that way all my initialization code will be in same place.
so i have created automatic variable 
var animationPlayerUntyped  = null
and made an attempt to initialize it in the _ready func & use it in _physics_process

in that case editor won't give me any autocompletion hints.

it seems that autocompletion fully works only for (check comments in the code examples for more info)
onready var animationPlayerOnready = $AnimationPlayer

### Steps to reproduce

add an AnimationPlayer node with two animations
add script to the root node (it was an KinematicBody2d in my case)
paste following code into the script

```GdScript
var animationPlayerUntyped  = null
var animationPlayerTyped: AnimationPlayer = null
onready var animationPlayerOnready = $AnimationPlayer

func _ready():
	animationPlayerTyped = $AnimationPlayer
	animationPlayerUntyped = $AnimationPlayer

func _physics_process(delta):
	#no autocompletion at all
	animationPlayerUntyped.
	#autocompletion lists method names but can't offer anything for animations
	animationPlayerTyped.play()
	#works as intended: list of methods was visible, and it offers several animations as possible function args
	animationPlayerOnready.play("IdleDown")
```

**Comment by Calinou** [comment] 2021-11-05 15:47
Duplicate of https://github.com/godotengine/godot/issues/39228.

**Closed by Calinou** 2021-11-05 15:47 UTC
Labels: bug, topic:gdscript, topic:editor
