### ISSUE TITLE
Viewport doesn't update when ViewportContainer is Hidden

### ISSUE THREAD

**Issue by starcin** [godotengine/godot#57901] opened 2022-02-10 09:30 UTC
### Godot version

3.4.2.stable

### System information

Windows 10, GLES3

### Issue description

I've tried this in a 3D scene with a Control scene as a child (acting as overlay GUI).

Control scene has a TabContainer and one of the tabs has a ViewportContainer. ViewportContainer has a Viewport and the Viewport has a Camera (3D Camera).

The purpose is having a topview window in that tab.

I tried accessing the viewport.get_texture() in the main scene and saw that if I am showing another tab (ViewportContainer is not visible), the texture is not updated.

A simpler test I did was simply adding a ViewportContainer to my 3D scene and adding a sprite with ViewportTexture.
While running the game, if I hide the ViewportContainer in editor, the texture on the sprite stops updating.

I verified the Viewport render_target_update_mode is "Always" on both cases.

### Steps to reproduce

Add a ViewportContainer with a viewport and camera to a 3D scene with some movement going on.
Add a sprite with ViewportTexture and show the viewport as target.
While running the game, hide the ViewportContainer in editor, you'll see the texture on the sprite stops updating.

### Minimal reproduction project

EDIT: Created this issue at work and wasn't allowed to upload anything to internet there. Now the minimal project is added (after reminded by @akien-mga, so thanks :)  )
[minimal-viewport-update.zip](https://github.com/godotengine/godot/files/8047542/minimal-viewport-update.zip)

**Comment by akien-mga** [comment] 2022-02-10 17:30
A minimal reproduction project would be good so that we can test and see if it's a bug or a misconfiguration.

**Comment by starcin** [comment] 2022-02-11 09:45
Added the project to the original post. Thanks for reminding me. I was at work and wasn't allowed to upload anything.

**Comment by BastiaanOlij** [comment] 2023-10-30 10:47
If I recall correctly a viewport container always overrules the update mode of the subviewport, this was done because many people left the subviewport set to rendering even when the container was hidden.

If you want to use the subviewport both shown as is, and as a texture on a 3D model, best not to use a subviewport but just display it on a textureRect.

**Comment by KoBeWi** [comment] 2023-10-30 10:47
Closing as duplicate of #56502
I have a PR that resolves this issue.

**Closed by KoBeWi** 2023-10-30 10:47 UTC
Labels: topic:core
