### ISSUE TITLE
Different number of leading zeros in scientific notation exponent recorded in TSCN file in Windows versus Linux

### ISSUE THREAD

**Issue by puzzud** [godotengine/godot#24137] opened 2018-12-03 16:36 UTC
**Godot version:**
v3.0.6.stable.official.8314054 for Windows
Same-ish v3.0.6 build for Linux

**Issue description:**
Opening and resaving a scene file with values containing scientific notation have equivalent numeric values written slightly different (two digits places instead of three).

**Linux:**
transform = Transform( 1, -1.12852e-06, 9.19296e-14, 9.19296e-14, 1.62921e-07, 1, -1.12852e-06, -1, 1.62921e-07, 0, 45, 0 )

**Windows:**
transform = Transform( 1, -1.12852e-006, 9.19296e-014, 9.19296e-014, 1.62921e-007, 1, -1.12852e-006, -1, 1.62921e-007, 0, 45, 0 )

It's expected that these values written as strings should be equivalent with string comparisons, as not to trigger unnecessary file changes in a version control system.

**Steps to reproduce:**
 - Launch Godot Editor and a project in Linux.
 - Add nodes to scene, adjusting their translation and rotation until their corresponding transform in that scene's TSCN file contains components written with scientific notation. Should probably see "e-00n" with two zeros or total of three digit places.
 - Save scene. Close Godot Editor.
 - Open Godot Editor in Windows.
 - Open previous project.
 - Move a component that has a transform with components written with scientific notation.
 - Undo that movement.
 - Save scene.
 - Observe that the components written with scientific notation have two digit places instead of three.

**Comment by bojidar-bg** [comment] 2018-12-04 16:14
Can you confirm that the same commit is used on both windows and linux? "Same-ish" might mean "just after it was fixed".

**Comment by puzzud** [comment] 2018-12-04 19:06
@bojidar-bg, I'm new to Godot and I downloaded it for both of my machines within days of each other. But I see what you mean; I will double check and ensure I'm using the same version builds. I just happened to have filed from my Windows machine while my Linux machine was unavailable.

**Comment by akien-mga** [comment] 2018-12-04 20:08
I can reproduce the bug with 3.1 alpha 2 (Linux 64-bit and Windows 64-bit via WINE), and I don't remember any fix for such an issue, so it's safe to assume that it's still valid.

**Comment by puzzud** [comment] 2018-12-04 20:12
Searching online, I found this stackoverflow:
https://stackoverflow.com/questions/31331723/how-to-control-the-number-of-exponent-digits-after-e-in-c-printf-e

It suggests that printf behavior varies between compiler environment implementations of C libraries, eg gcc versus Visual Studio. I'm guessing the Windows version of Godot that is shipped is built with Visual Studio.

https://en.wikipedia.org/wiki/Printf_format_string

It looks like using a preprocessor check for Visual Studio to use _set_output_format to change the leading zero count to two.

**Comment by akien-mga** [comment] 2018-12-04 20:23
The relevant code is here a priori: https://github.com/godotengine/godot/blob/aa311320d92b2982dd4606156882686cc354e551/core/ustring.cpp#L1311-L1331

Official Windows binaries are actually built with MinGW (GCC) since 3.0.3 IIRC, so similar to Linux binaries.

**Comment by puzzud** [comment] 2018-12-04 22:23
Some more Googling:
http://www.cplusplus.com/forum/general/35207/

That thread indicates people noticed this discrepancy when building with MinGW in Windows versus GCC in Linux.

**Comment by puzzud** [comment] 2018-12-04 22:42
I apologize for perhaps polluting this issue with comments.

Is the reason String::num exists but is just a fallback to the implementation of String::num_scientific because its not as performant as sprintf (besides that as far as I've spent looking at it, it doesn't actually support scientific notation)?

It seems to me that a check to see if buf has an 'e' character could kick off another check to ensure the substring after the 'e' has an appropriate number of digits. In which case it doesn't, that substring could be adjusted and then a new buf could be assembled from the two 'e' separated substrings.

This process seems to me to be junior job applicable. I understand it does incur some small amount of technical debt. It may likely be more doable than the process of getting updated MinGW C libraries that are more compliant with more recent C standards.

**Comment by akien-mga** [comment] 2018-12-04 22:52
`String::num` is used all over the engine, not just as fallback for `String::num_scientific`. It being used as fallback just means that if you build Godot with support for the standard library, you won't have scientific notation (it will be output with a plain old decimal notation).

> It seems to me that a check to see if buf has an 'e' character could kick off another check to ensure the substring after the 'e' has an appropriate number of digits. In which case it doesn't, that substring could be adjusted and then a new buf could be assembled from the two 'e' separated substrings.

Sounds overkill for what is at stake here, especially given the computational cost that such an implementation would have. String methods need to be as fast as possible as they are used extensively.

**Comment by puzzud** [comment] 2018-12-04 23:40
Some information on the C library shipping with MinGW:
http://www.mingw.org/wiki/C99

**Comment by jamie-pate** [comment] 2019-11-05 22:54
It looks to be fixed by simply removing `_snprintf_s()` in `num_scientific` ? This problem is _killing_ me (though I can create a new build of the editor, the https://godotengine.org supplied build _should_ be fixed.

**Comment by jamie-pate** [comment] 2019-11-05 22:57
```C++
#include <stdio.h>
#include <stdlib.h>

int main() {
    double num = -4.37114e-08;
    char buff[256] = {0};
    printf("%lg\n", num);
    snprintf(buff, 255, "%lg", num);
    printf("%s\n", buff);
#ifdef _snprintf_s
    _snprintf_s(buff, 255, "%lg", num);
    printf("%s\n", buff);
#endif
_set_output_format(_TWO_DIGIT_EXPONENT);
    printf("%lg\n", num);
    snprintf(buff, 255, "%lg", num);
    printf("%s\n", buff);
#ifdef _snprintf_s
    _snprintf_s(buff, 255, "%lg", num);
    printf("%s\n", buff);
#endif
}
```
This also works

**Closed** 2019-11-08 08:42 UTC
Labels: bug, confirmed, platform:windows, topic:core
