### ISSUE TITLE
GD.PrintRaw doesn't work

### ISSUE THREAD

**Issue by NitayGitHub** [godotengine/godot#85993] opened 2023-12-10 09:32 UTC
### Tested versions

v4.2.stable.mono.official [46dc27791]

### System information

Windows 10 - Godot.4.2

### Issue description

I use C# and GD.PrintRaw didn't work for me in the new build.

### Steps to reproduce

Use GD.PrintRaw to print to the console.

### Minimal reproduction project (MRP)

Use GD.PrintRaw to print to the console.

**Comment by bs-mwoerner** [comment] 2023-12-10 16:19
According to the docs, `GD.PrintRaw()` isn't supposed to print to the "console" (which I suppose in this context is different from the "OS terminal"), so you might argue that's working as advertised. I think the idea is: If you want messages to also appear in the Editor's "Output" window, use `GD.Print()`. If you're only printing to the OS terminal, `GD.PrintRaw()` is enough.

**Comment by AThousandShips** [comment] 2023-12-10 16:22
Duplicate of https://github.com/godotengine/godot/issues/33255

**Closed by AThousandShips** 2023-12-10 16:22 UTC
Labels: bug, topic:dotnet
