### ISSUE TITLE
A Confusing Error on Animation

### ISSUE THREAD

**Issue by GoldenPig686** [godotengine/godot#97846] opened 2024-10-05 13:15 UTC
### Tested versions

- Reproducible in: v4.4.dev3 [f4af8201b], 4.3.stable, 4.3.dev1 and later 4.3 snapshots. - Not reproducible in: 4.2.2.stable.

### System information

Godot v4.3.stable - Windows 10.0.22631 - Vulkan (Forward+) - integrated Intel(R) UHD Graphics 730 (Intel Corporation; 32.0.101.5542) - 12th Gen Intel(R) Core(TM) i5-12400 (12 Threads)

### Issue description

The Output panel shows the error below:
```
This function in this node (/root/@EditorNode@16886/@Panel@13/@VBoxContainer@14/DockHSplitLeftL/DockHSplitLeftR/DockHSplitMain/@VBoxContainer@25/DockVSplitCenter/@EditorBottomPanel@6653/@VBoxContainer@6642/@AnimationTreeEditor@12207) can only be accessed from either the main thread or a thread group. Use call_deferred() instead.
```

### Steps to reproduce

Click the AnimationTree Node in the scene after opening the project. Then unfold the Animation panel. Finally, run the scene and you will reproduce the error. But maybe the error fails to be reproduced for the first import of the project, so please reload the project after you open the project for the first time.

### Minimal reproduction project (MRP)

[confusing-error-report.zip](https://github.com/user-attachments/files/17266313/confusing-error-report.zip)

**Comment by fire** [comment] 2024-10-05 17:21
We'll have to find the two github godot revisions and run https://stackoverflow.com/questions/4713088/how-do-i-use-git-bisect to find the exact change that broke the code.

**Comment by TokageItLab** [comment] 2024-10-05 17:26
Dupe of https://github.com/godotengine/godot/issues/85456#issuecomment-2395012719

**Closed by TokageItLab** 2024-10-05 17:26 UTC

**Comment by GoldenPig686** [comment] 2024-10-06 07:20
@TokageItLab 

First, thank you for your comment on my issue.

After carefully reading #85456, I realize that it is indeed the same situation as mine. However, **having ever tried turn off the "Active" property in the "AnimationPlayer" node, the issue still exists**. Could you please help me solve the problem thoroughly?

Thanks again.
