### ISSUE TITLE
Strange performance issue on Android using GLES2

### ISSUE THREAD

**Issue by RodrigoMedeirosRS** [godotengine/godot#24990] opened 2019-01-14 20:59 UTC
**Godot version:** 3.1 Beta 1
**OS version:** Android Oreo
**Device:** Xiaomi Redmi Note 5, 4Ram, 64gb ROM 
**GPU:** Snapdragon 636

**Issue description:**
Hello people, my problem is related to GLES2 performance. When i use the GLES2 my fps on mobile drops to lower than 12, but when i use the GLES3 he have the full performance. It's so curious because into my Moto G2  occour's exactly the inverse (GLES3 have low  performance and GLES2 have full performance).

**Steps to reproduce:**
Build an 2d game into android and run into one Xiaomi Redmi Note 5, in both versions (GLES2 and GLES3).

**Comment by volzhs** [comment] 2019-01-14 21:01
it's a duplicate of #24466 and fixed by #24987 on master

**Closed by volzhs** 2019-01-14 21:01 UTC
