### ISSUE TITLE
Volumetric Fog shows artifacts at camera edge at certain angles inside Fog Volumes

### ISSUE THREAD

**Issue by Lippanon** [godotengine/godot#74790] opened 2023-03-11 19:58 UTC
### Godot version

v4.0.stable.official [92bee43ad]

### System information

Windows 10, Vulkan

### Issue description

Closer to the edges of Fog Volumes (but still at reasonable distance) certain camera angles will display very noticeable artifacts that cover part of the camera. None of the project settings related to Volumetric Fog or Environment settings seem to alleviate the problem. Camera's near plane value also doesn't seem to help.

Keep in mind, the camera is still clearly inside the fog volume. The problem occurs in all axes.

### Steps to reproduce

It's visible in the editor in the MRP, position the camera near the edge of the FogVolume and look around as shown.

### Minimal reproduction project

[volfog bug.zip](https://github.com/godotengine/godot/files/10949332/volfog.bug.zip)

Posting video at bottom because anything after seems to get eaten by github for some reason.

<video src="https://user-images.githubusercontent.com/115422160/224508971-761a49d5-b2a5-4c54-8adc-85a2dfa93b71.webm">

**Comment by clayjohn** [comment] 2023-03-11 20:41
Looks like a culling issue to me . I wonder if the FogVolume is getting culled when it is still intersecting the camera's frustum.

**Comment by Lippanon** [comment] 2023-06-20 13:41
> Looks like a culling issue to me . I wonder if the FogVolume is getting culled when it is still intersecting the camera's frustum.
I wasn't sure how to test this, but I tried editing:
- `get_aabb()` in /scene/3d/fog_volume.cpp
- `fog_volume_get_aabb(RID p_fog_volume)` in /servers/rendering/renderer_rd/environment/fog.cpp
Doubling the AABB volume didn't seem to affect it.

**Comment by idchlife** [comment] 2023-08-19 08:36
This is a very severe issue IMO.

I have this as well and I don't know any workarounds.

Slight look left/right/up/down cuts fog like in video provided by @Lippanon 

Basically FogVolume is unusable for now. I can't add it to a long corridor because of this issue.

Any idea how to overcome this?

**Comment by Lippanon** [comment] 2023-08-19 11:59
I would also appreciate any tips on where in the codebase to make changes to narrow the source of the bug.

**Comment by clayjohn** [comment] 2023-08-21 12:44
You can look here for the shape in the shader

**Comment by idchlife** [comment] 2023-08-21 14:26
I can also mention that this bug occurs even with shader material instead of fog material.

**Comment by viksl** [comment] 2023-08-25 14:00
Hi, would you mind making a screenshot and putting it here, the video is down, or put the video on youtube perhaps?

**Comment by viksl** [comment] 2023-08-25 15:03
Here's a video I just made showing maybe similar issue: https://youtu.be/DZNzFiMljVk ?

**Comment by viksl** [comment] 2023-08-25 20:45
@clayjohn I'm trying to check the file you mentioned `volumetric_fog.glsl` but I'm not that great at this stuff. I noticed that there's `float density = 0.0;` definied it isn't changed anywhere until this line `density *= cull_mask;` and then used as `if (abs(density) > 0.001`. If you don't mind, how does this exactly work please?
It seems the density itself isn't changed anywhere?
(https://github.com/godotengine/godot/blob/master/servers/rendering/renderer_rd/shaders/environment/volumetric_fog.glsl#L160-L223)
But as mentioned I'm not very experienced with this so I might as well be missing something obvious.

**Comment by viksl** [comment] 2023-08-28 16:37
The problem with this it's not related to the cutting the fog off. So if someone uses fog volumes this will be happening to them too even without the negative density. When you move your camera in a certain way (not difficult) and then move into the fog the fog will be disappearing until it's almost all gone unfortunately :'/.

**Comment by Mervius** [comment] 2023-08-28 16:40
> The problem with this it's not related to the cutting the fog off. So if someone uses fog volumes this will be happening to them too even without the negative density. When you move your camera in a certain way (not difficult) and then move into the fog the fog will be disappearing until it's almost all gone unfortunately :'/.

Yes, it doesn't seem to happen with the global shape, so you can essentially cut off that shape in the shapebyou originally wanted

**Comment by Calinou** [comment] 2023-08-28 16:47
I can confirm this on 4.2.dev 6758a7f8c (Linux, GeForce RTX 4090 with NVIDIA 535.98).

Note that disabling temporal reprojection doesn't fix the issue. Here are videos with volume size and depth both set to 512, to make it clearer:

https://github.com/godotengine/godot/assets/180032/e980bf3f-f35f-49d6-97c1-5d42655cd4e1

https://github.com/godotengine/godot/assets/180032/728853c5-ca74-4733-bea7-f9037216195b

**Comment by viksl** [comment] 2023-08-28 17:07
Here's the full issues I was describing, notice you don't need two fog volumes to cut off one, also notice how the fog gets completely cut of around camera edges: https://youtu.be/PlpQ7BNlEz4

**Comment by viksl** [comment] 2023-09-14 07:48
Just want to ping everyone to check something out, if you switch the lines:
```
min = Vector3i(int32_t(fog->width) - 1, int32_t(fog->height) - 1, int32_t(fog->depth) - 1);
max = Vector3i(1, 1, 1);
```
For these:
```
min = Vector3i(0, 0, 0);
max = Vector3i(int32_t(fog->width) - 1, int32_t(fog->height) - 1, int32_t(fog->depth) - 1);
```

The issues go away for me. This is likely not the solution but it might help you figure out where to look at. The froxelization function might be the first candidate to check as Clay mentioned above.

**Comment by SA-Lowell** [comment] 2023-11-18 06:30
Definitely hoping this gets fixed soon. I'm working on a small teaser for my game and this is becoming very glaring. I'll likely use the provided codebase workaround in the meantime for any stuff I want to show off.

**Comment by ecmjohnson** [comment] 2023-12-12 02:14
I believe the culling behaviour is incorrect as @clayjohn mentioned: it is not sufficient to consider the fog volume's corners when determining the range of froxel cells to run compute on. I think this particular failure case is illustrated in the below diagram:

![PXL_20231212_013904800](https://github.com/godotengine/godot/assets/6766142/d64adb4b-3539-4bc9-8805-28cb68827e23)

When fog corner A is clamped to the view frustum corner C, the minimum value from the visible far fog volume corner results in a portion of the fog volume being ignored. You can see this in-engine because the boundary of the artifact is inline with the far fog corners (see below). Slightly rotating the camera can result in fog corner A suddenly clamping to frustum corner B and then things work as expected since this gives a minimum value of 0.

![issue_clarification](https://github.com/godotengine/godot/assets/6766142/d46e1af8-a99b-475e-ac3c-4124a7aa94a0)

I'm still not sure what the solution is, but I should be able to come up with a proposal soon

**Comment by ScarfKat** [comment] 2024-10-17 02:59
Any chance the relevant PR will make it into 4.4? It seems to have missed its chance with 4.2 and 4.3, and would be super helpful if it was merged.

**Closed** 2024-10-24 18:29 UTC
Labels: bug, topic:rendering, confirmed, topic:3d
