### ISSUE TITLE
Rectangular selection doesn't work on 3D models

### ISSUE THREAD

**Issue by samvila** [godotengine/godot#19658] opened 2018-06-19 20:24 UTC
**Godot version:**
Godot 3.0.3 Stable, Win64

**OS/device including version:**
Windows 10, 64 bit

**Issue description:**
The rectangular selection tool doesn't select the 3D objects on the viewport

**Steps to reproduce:**
Create a bunch of 3D mesh instances, for example some cubes. Then try to use the rectangular selection tool to select all of them drawing a rectangular around the viewport. The result is than no objects gets selected using this selection tool.

**Comment by JFonS** [comment] 2018-09-02 20:42
This should work fine on current master.

**Comment by samvila** [comment] 2018-09-02 21:16
Closing this ticket, you're right @JFonS , on Godot 3.1 Alpha 1 this has been fixed. So happy :-)

**Comment by JFonS** [comment] 2018-09-04 22:49
I guess you are talking about instanced scenes. In that case #21707 should fix your issue, but it hasn't been merged yet.

**Comment by samvila** [comment] 2018-09-04 23:07
Oh I see, should I close this ticket then @JFonS ?

**Comment by JFonS** [comment] 2018-09-04 23:15
@samvila Yes, since this is basically a duplicate of #21649

**Closed** 2018-09-04 23:16 UTC
Labels: bug, topic:editor, usability
