### ISSUE TITLE
Incorrect `NavigationPolygon.add_outline()` calculation

### ISSUE THREAD

**Issue by spikeyarmaku** [godotengine/godot#80430] opened 2023-08-08 19:34 UTC
### Godot version

v4.1.1.stable.official [bd6af8e0e]

### System information

Godot v4.1.1.stable - Windows 10.0.19045 - Vulkan (Mobile) - dedicated Radeon RX Vega (Advanced Micro Devices, Inc.; 31.0.12027.9001) - AMD Ryzen 5 3600 6-Core Processor (12 Threads)

### Issue description

`NavigationPolygon.add_outline()` produces incorrect result with specific values. However, if I nudge the first point by a tiny amount (the uncommented line in the gif), it works correctly.
![navpoly_bug](https://github.com/godotengine/godot/assets/8467908/e268a66c-491c-4557-a19f-571a52cad184)

### Steps to reproduce

- Open the supplied project
- Select `Debug` -> `Visible Navigation`
- Either comment or uncomment the first line in `_ready()`
- Run the project

If the first line in `_ready()` is commented out (which nudges the first point on the X axis), the issue crops up. If it is uncommented, the issue goes away. Nudging any other point doesn't have an effect on the result.

### Minimal reproduction project

[polygon2d bug.zip](https://github.com/godotengine/godot/files/12295191/polygon2d.bug.zip)

**Comment by smix8** [comment] 2023-08-09 13:45
Closing as a duplicate of https://github.com/godotengine/godot/issues/70823.

**Closed by smix8** 2023-08-09 13:45 UTC
Labels: bug, needs testing, topic:navigation, topic:2d
