### ISSUE TITLE
Can't open "Find in files" without opened script

### ISSUE THREAD

**Issue by boruok** [godotengine/godot#70048] opened 2022-12-14 08:20 UTC
### Godot version

v4.0.beta.custom_build [db6976eed]

### System information

Ubuntu 22.10 LTS, GTX1060 Vulkan

### Issue description

Found bug with opening in "find in files" window with hotkey Ctrl+Shift+F

### Steps to reproduce

1. open scripts editor
2. make sure that you didn't opened any script (close all of em)
3. press `Ctrl+Shift+F` combination to open "Find in Files" window

notes:
1. looks like that window requires that at least one script must be opened
2. can't reproduce it on `3.x` branch  
3. "replace in files" also doesn't popup with hotkeys

### Minimal reproduction project

reproducible with any project with scripts

**Comment by MewPurPur** [comment] 2022-12-14 13:12
Duplicate of https://github.com/godotengine/godot/issues/64117

**Closed** 2022-12-14 13:14 UTC
Labels: bug, topic:editor, regression
