### ISSUE TITLE
Animation player looping still broken

### ISSUE THREAD

**Issue by StalfFromValenwood** [godotengine/godot#42886] opened 2020-10-18 14:08 UTC
I am currently using Godot 3.2, but the issue appears to have not been fixed since, according to the change logs.

The double arrow in the AnimationPlayer node does not seem to work properly. The animation would loop in the editor's viewport, but is not saved when the game is played, or when the project/editor is shut down and reopened.

I know I can add "-loop" at the end of every animation's name that requires to loop, or I can even tell which animation I want to loop by code, but it seems silly to have a useless button in the editor, which is supposed to save some writing and allow to quickly change whether or not an animation is looping.

This is not a new issue either :
https://github.com/godotengine/godot/issues/22083
https://github.com/godotengine/godot/issues/10999

You may want to reproduce this issue by importing any 3D model with at least one animation, and set it to loop in the AnimationPlayer node.

[character.zip](https://github.com/godotengine/godot/files/5397595/character.zip)

My computer runs on Windows 10 pro 64 bits version 18363.1139.
My GPU is a RTX 2060, driver version : 452.06 (as seen in Geforce Experience).

**Comment by Calinou** [comment] 2020-10-18 14:16
Duplicate of https://github.com/godotengine/godot/issues/25245.

**Closed by Calinou** 2020-10-18 14:16 UTC
