### ISSUE TITLE
Path2D causes Godot Editor to misbehave

### ISSUE THREAD

**Issue by lucas1993** [godotengine/godot#97248] opened 2024-09-20 19:52 UTC
### Tested versions

- Reproducible in v4.3.stable.official [77dcf97d8]

### System information

Godot v4.3.stable - Ubuntu 23.10 23.10 - X11 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1650 (nvidia; 535.171.04) - Intel(R) Core(TM) i5-3340 CPU @ 3.10GHz (4 Threads)

### Issue description

Trying to do anything with Path2D causes the editor starts misbehaving, eg.: Can't add or delete nodes (`Condition "!p_node->is_inside_tree()" is true` shows in the console) and can't edit properties in the inspector (it immediately resets the value). Restarting Godot fixes this temporarily. 

### Steps to reproduce

-  Create a new project
-  Add a new scene (Tried with 2d scene and ui scene)
-  Add a Path2D as a child
-  Add points to the path, add some curvature (eg.: 4 points)
-  Try to add a new node to the scene

### Minimal reproduction project (MRP)

N/A

**Comment by matheusmdx** [comment] 2024-09-20 20:19
Duplicate of #96081 that was already fixed by #96237

**Closed** 2024-09-20 20:23 UTC
