### ISSUE TITLE
Incorrect margin values result in AtlasTexture preview image errors

### ISSUE THREAD

**Issue by CodeLazier** [godotengine/godot#74810] opened 2023-03-12 07:38 UTC
### Godot version

4.0 release

### System information

win11 vulkan

### Issue description

Editing the y value of the Margin in an atlas texture seems to cause preview image glitches, indicating that the correct clipping is not being applied. However, if the value is negative, the clipping is applied correctly.

![bug](https://user-images.githubusercontent.com/14953625/224531015-40c06d35-f7e6-4e88-8ec3-a1bd09034860.gif)

### Steps to reproduce

To make changes, simply edit the atlas texture resource by modifying the y value.

### Minimal reproduction project

N/A

**Comment by kleonc** [comment] 2024-08-02 16:55
This is a duplicate of #51802 (fixed by #93828 / #93857).

**Closed by kleonc** 2024-08-02 16:55 UTC
Labels: bug, topic:editor
