### ISSUE TITLE
AnimationTree breaks Sprite2D regions

### ISSUE THREAD

**Issue by dthomason** [godotengine/godot#71973] opened 2023-01-24 13:42 UTC
### Godot version

4.0 Beta 14

### System information

OSX 12.8.1

### Issue description

Seen on 4.0 beta 10 and 14.  Is not present on beta 1
<img width="1356" alt="Screen Shot 2023-01-22 at 9 23 00 PM" src="https://user-images.githubusercontent.com/8356638/214302161-f3f732fa-839a-4307-b79a-e8679abce264.png">

### Steps to reproduce

1. add a couple Sprite2D nodes and attach the same spritesheet to them
2. enable regions and select the portions of your choosing
3. add an AnimationPlayer and create a simple animation with your sprites
4. add an AnimationTree and attach accordingly, set to active
5. click a Sprite2D node and choose "Edit Region". 
6. notice it's a blank

### Minimal reproduction project

[bug_example.zip](https://github.com/godotengine/godot/files/10490487/bug_example.zip)

**Comment by dthomason** [comment] 2023-01-24 16:00
ok, I may have found a workaround, by removing the AnimationTree, then just re-adding the sprite to one of the Sprite2D's it the edit regions starts working for all sprites again.  I then added the AnimationTree back in and everything is still working.  Maybe it's the initial setup that breaks it, I'm not sure.  But I at least found a way around it for now.

**Comment by kleonc** [comment] 2023-01-24 20:45
It has nothing to do with the animations. The issue is the `TextureRegionEditor` being unable to edit `CanvasTexture` because:
- `CanvasTexture` can't reference another `CanvasTexture`,
- `TextureRegionEditor` is creating it's own `CanvasTexture` for the texture preview and it's trying to assign the edited `CanvasTexture` as a `diffuse_texture` of its preview.

Will look into fixing this.

**Comment by kleonc** [comment] 2023-10-17 12:44
Already fixed in v4.2.beta1.official [b1371806a], likely by #80435.

**Closed by kleonc** 2023-10-17 12:44 UTC
Labels: bug, topic:editor, confirmed, topic:2d
