### ISSUE TITLE
wireframe debug mode doesnt work

### ISSUE THREAD

**Issue by Gibbz** [godotengine/godot#15149] opened 2017-12-29 09:30 UTC
Wireframe debug doesnt work on 32d8b99
get_viewport().set_debug_draw(Viewport.DEBUG_DRAW_WIREFRAME);

**Comment by CCODE05B** [comment] 2017-12-29 11:17
Yes it's not working on : Godot 3.0 Beta x64

`get_viewport().debug_draw = get_viewport().DEBUG_DRAW_WIREFRAME;`

**Comment by brainsick** [comment] 2018-01-04 02:50
If you manually call `VisualServer.set_debug_generate_wireframes(true)` it works.

```
todd@todd-ab28d3:~/repos/remote/brainsick-godot-tests/tests/qa$ cat issues/15149-3d.gd 
extends SceneTree

func _initialize():
	var viewport = get_root()
	VisualServer.set_debug_generate_wireframes(true) # this
	viewport.debug_draw = Viewport.DEBUG_DRAW_WIREFRAME
	
	var camera = Camera.new()
	
	var mesh_instance = MeshInstance.new()
	mesh_instance.mesh = CubeMesh.new()
	mesh_instance.transform.origin.z = -5
	mesh_instance.translation.z = -5
	
	camera.add_child(mesh_instance)
	
	viewport.add_child(camera)

# main test body
func _iteration(delta):
	test_viewport_wireframe()
	
	quit()

func test_viewport_wireframe():
	# how could we test this?  before/after image?
	assert(true)
todd@todd-ab28d3:~/repos/remote/brainsick-godot-tests/tests/qa$ time ~/Downloads/Godot3.0Beta2/Godot_v3.0-beta2_x11.64 -s issues/15149-3d.gd 
No touch devices found
OpenGL ES 3.0 Renderer: AMD Radeon (TM) R9 Fury Series (AMD FIJI / DRM 3.18.0 / 4.13.0-21-generic, LLVM 5.0.0)
GLES3: max ubo light: 409
GLES3: max ubo reflections: 455, ubo size: 144
ARVR: Registered interface: Native mobile

real	0m1.108s
user	0m0.166s
sys	0m0.025s
```

![screenshot from 2018-01-03 20-47-05](https://user-images.githubusercontent.com/1111573/34548434-ba67a6d6-f0c7-11e7-8f6a-6407b7a68a4f.png)

**Comment by reduz** [comment] 2018-09-06 16:14
This is not a bug, wireframe only works on editor because it generates special line geometry for triangle models.
During the game, this is not supported because it's extra bloat.

This is because OpenGL no longer supports wireframe rendering.

Closing as this is not a bug.

**Closed by reduz** 2018-09-06 16:14 UTC
Labels: bug, topic:rendering

**Comment by Zylann** [comment] 2019-09-13 18:12
I wish this could work when running the game using an editor build. It is just as useful as debug collision shapes. Thanks for the workaround @kb173 :)

**Comment by Calinou** [comment] 2019-09-13 18:30
I don't see an issue with exposing the wireframe mode either, as long as it doesn't cause the binary size to increase significantly (which it probably won't).

**Comment by clayjohn** [comment] 2019-09-13 23:13
It requires the engine to generate wireframe models for every mesh on load. Which would be a pretty significant issue for any project.

**Comment by Zylann** [comment] 2019-09-13 23:50
@clayjohn generating meshes to see every collision shape is also a significant load, but that's really not the point I was making. The point is the ability to switch to wireframe mode while you are debugging your game from the editor.

**Comment by kb173** [comment] 2019-09-14 08:45
I agree, why not just leave the `VisualServer.set_debug_generate_wireframes(true)` functionality as it is, but document it properly? I think a performance hit like that is only an issue when the user isn't aware of it. Perhaps it could be disabled for non-debug-builds?

In our project, having wireframes in the debug run of our game was a huge help. We work with a lot of GIS data which is procedurally fetched and updated while the game is running, so visualizing what's actually going on there at runtime (especially with the terrain) was great. Before finding this 'hidden' option, we were even thinking of manually writing a wireframe renderer.

**Comment by gitcatrat** [comment] 2020-01-27 16:50
`VisualServer.set_debug_generate_wireframes(true)` doesn't work if you play the scene. 

Is it not suppose to work in play mode or is it a bug? Also tried to hard-code `true`.

```gdscript
func _toggled(pressed: bool) -> void:
	VisualServer.set_debug_generate_wireframes(pressed)
```
