### ISSUE TITLE
Small Deploy with Network in iOS untethered

### ISSUE THREAD

**Issue by lexum0** [godotengine/godot#9276] opened 2017-06-19 21:05 UTC
**Operating system or device - Godot version:**
macOS Sierra & iOS 10 - Godot 2.1.3

**Issue description:**
Using Small Deploy with Network requires launching from Xcode with "Arguments passed on Launch". This is a slow process because it requires Xcode open, the iOS Device connected, Xcode installs the app every time it runs, checks signatures, a lot of work and you cannot use it without the device connected to a Mac

Instead, it would be better to add the "-rfs <IP>" argument in the Info.plist file rather than or besides the Arguments passed on launch option, this way you can just tap the app icon in the device and launch into this mode instantly, speeding up testing and being able to use it untethered

Labels:
Enhancement, Usability

**Comment by punto-** [comment] 2017-06-20 10:00
This might help
https://kb.froglogic.com/display/KB/Article+-+iOS+automation+through+USB+cable+connection

**Comment by lexum0** [comment] 2017-06-20 21:04
Seems interesting, but the point is to not need the iDevice connected through USB

Also, right now it requires to run from Xcode, which requires Xcode open and Xcode profiling the app (CPU usage, Memory, Network, Disk I/O) and all of this hogs resources that you could be using in Godot. At the same time slows down the App's performance because it needs to profile performance and report to Xcode in real time

Its a process that drains and requires a lot of resources both in the iDevice and the Mac. 
Simply adding the "-rfs" argument in the Info.plist file solves all of this

**Comment by lexum0** [comment] 2017-06-20 21:11
I was doing some further research and discovered a "main_run_args" property in the project settings but seems it isn't implemented. Also there's a "Command Line Extra Args" property in the Android Export Settings

Both of these could be the solution, especially the former one, which would be a clean, easy, and universal solution

**Comment by kubecz3k** [comment] 2018-04-03 11:49
First of all thank you for your report and sorry for the delay.

We released Godot 3.0 in January 2018 after 18 months of work, fixing many old issues either directly, or by obsoleting/replacing the features they were referring to.

We still have hundreds of issues whose relevance/reproducibility needs to be checked against the [current stable version](https://godotengine.org/download), and that's where you can help us.
**Could you check if the issue that you described initially is still relevant/reproducible in Godot 3.0 or any newer version, and comment about its current status here?**

For bug reports, please also make sure that the issue contains detailed steps to reproduce the bug and, if possible, a zipped project that can be used to reproduce it right away. This greatly speeds up debugging and bugfixing tasks for our contributors.

Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

Thanks in advance.

*Note: This message is being copy-pasted to many "stale" issues (90+ days without activity). It might happen that it is not meaningful for this specific issue or appears oblivious of the issue's context, if so please comment to notify the Bugsquad about it.*

**Comment by akien-mga** [comment] 2018-05-29 08:43
> Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

As there was no update since the previous post, we close this issue.

If it is still relevant in the way it was described and discussed above, please comment to ask for it to be reevaluated. If it is only partly relevant, or if the original issue has changed, it would be better to open a new issue (potentially referring to this one) focused on the current state.

**Closed by akien-mga** 2018-05-29 08:43 UTC
Labels: discussion, feature proposal, platform:ios, topic:network, topic:porting, usability

**Comment by lexum0** [comment] 2018-06-06 20:52
I'm waiting for the following issue so I can implement this feature myself. It's pretty easy and simple, a couple of lines but I need some Objective-C code that I can't currently execute:

https://github.com/godotengine/godot/issues/10263
