### ISSUE TITLE
Unable to change position correctly in inspector if multiple node selected

### ISSUE THREAD

**Issue by xdeadmonkx** [godotengine/godot#9519] opened 2017-07-05 17:57 UTC
**Operating system or device - Godot version:**
Windows 8.1 - 3.0 alpha

**Steps to reproduce:**
Select two different nodes with different X position,
change Y to some value
now two nodes are merged in first node's X and new Y

**Expected:**
Nodes are in different X and new Y

![image](https://user-images.githubusercontent.com/4668980/27877726-750e58ce-61c4-11e7-950e-e4d2fe400833.png)

![image](https://user-images.githubusercontent.com/4668980/27877744-8c32046a-61c4-11e7-8414-b0740fd2f634.png)

**Comment by quinnyo** [comment] 2017-07-06 00:21
You may know, but you can drag 2D nodes while holding shift to change one axis only (similar to Photoshop and friends/enemies). (click-drag, then shift)

I think this is the expected behaviour (at least for me) as position is a single property and when you change Y, you are setting the whole property. I think it would be impractical to treat each axis independently as there are a lot of other properties that would then have to be changed, or not, leading to inconsistencies. You could expose the X and Y as separate properties but that's a bit weird too.

But I think it should be easier to e.g. "move +1.25 on Y", without mouse drag and/or setting up snapping for one-offs. The mouse/drag transform tools could have some extra features. _Ideally with Blender-style numeric entry and axis selection of course._

**Comment by xdeadmonkx** [comment] 2017-07-07 07:34
I think if it is impossible to treat each axis in position property separately then we can make edit boxes for move tool

**Comment by akien-mga** [comment] 2017-07-25 13:11
For what you want to do, you can press Shift+Return IIRC to apply the new value to all selected nodes and not just the first one.

**Comment by RandomShaper** [comment] 2017-07-25 13:16
Yeah, Shift + Enter "commits" only the focused field to all the selected nodes.

**Comment by vnen** [comment] 2017-07-25 13:59
I didn't even know about that. Should be something more clear, since discoverability is a priority.

**Comment by RandomShaper** [comment] 2017-07-25 17:43
I'm opening an issue for discussing how to add discoverability to multi-node single-field edits.

If @xdeadmonkx confirms that at least it works for him now he is aware of it, this one could be closed in favor of the other.

**Comment by RandomShaper** [comment] 2017-07-25 17:45
Or shall we discuss that right here instead?

**Comment by xdeadmonkx** [comment] 2017-07-29 20:25
Yes, SHIFT + ENTER works for me!

**Closed** 2017-07-29 20:35 UTC
Labels: discussion, topic:editor, usability
