### ISSUE TITLE
Editor GUI not updating

### ISSUE THREAD

**Issue by maidnaut** [godotengine/godot#8667] opened 2017-05-06 07:56 UTC
**Operating system or device - Godot version:**
Windows 10, 2.1.3 recent stable version

**Issue description:**
Godot's gui won't update unless I alt+tab. My drivers are up to date but I'm running on a laptop with integrated intel graphics (Intel HD 520), but from what I read intel bugs were fixed in 2.0

thanks for any help you can give me c:

**Comment by organicpencil** [comment] 2018-01-29 18:39
My friend also has this issue. Present in Godot 2.1.4 and Godot 3 RC3.
Windows 10 with Intel HD 4400, driver version 20.19.15.4531

But  my machine works fine. Windows 10 with Intel HD 4000, driver version 10.18.10.4276
Gonna install updates and see what breaks. But on my connection it'll take like a month.

**Comment by organicpencil** [comment] 2018-01-29 19:47
Alright, for us the issue only appears when using a high-contrast theme @maidnaut

**Comment by akien-mga** [comment] 2018-09-17 13:57
Is this still reproducible in the current master branch / 3.1-alpha?

**Comment by aaronfranke** [comment] 2020-01-15 20:46
Can you please test if this occurs with the latest version of Godot ([3.2 beta 6](https://godotengine.org/article/dev-snapshot-godot-3-2-beta-6) or newer)?

**Comment by KoBeWi** [comment] 2020-11-25 00:46
Closing due to lack of update. Please comment if you can still reproduce this issue in the latest stable version of Godot.

**Closed by KoBeWi** 2020-11-25 00:46 UTC
Labels: bug, platform:windows, topic:editor
