### ISSUE TITLE
Rename project popup, does not grab keyboard focus.

### ISSUE THREAD

**Issue by avencherus** [godotengine/godot#26339] opened 2019-02-27 07:16 UTC
**Godot version:**

22ee7ba

**OS/device including version:**

Win10 64bit

**Issue description:**

When renaming a project, the Rename button doesn't get the control focus, instead it remains on the project selection in the window behind the popup (Seen in the screenshot as the highlighted row).  If you hit enter, it will fail to rename, and open the project instead.

The expectation in typical UI is that this would complete the rename and go back up the UI stack.

I keep tripping up on this one.

![image](https://user-images.githubusercontent.com/13004169/53472219-bb51ec80-3a6f-11e9-93be-ae1bb13b4055.png)

**Steps to reproduce:**
1. Open Godot editor to the project selection window.
2. Select a project and click Rename.
3. Type a new name and hit enter.

**Comment by akien-mga** [comment] 2019-02-27 08:28
Duplicate of #17620.

**Closed by akien-mga** 2019-02-27 08:28 UTC
