### ISSUE TITLE
Bad address index error at @implicit_new

### ISSUE THREAD

**Issue by TheSecondReal0** [godotengine/godot#75502] opened 2023-03-30 17:51 UTC
### Godot version

4.0.1

### System information

Windows 10, RTX 2060, Vulkan

### Issue description

I'm currently working on a game with a lot of class inheritance where each child class adds more instance variables on top of its parent. It seems that once the inheritance tree gets complex enough Godot starts throwing errors on variable declarations while instancing objects. Here is a screenshot of an error that occurs when a resource is loaded from a file:
![image](https://user-images.githubusercontent.com/66881186/228921133-86a48cd9-7e6a-445d-ad0c-be516e9a81b9.png)

This seems to happen somewhat randomly, sometimes it has no issue instancing an object and other times it throws an error (seems to only happen on the most complex objects/the ones with the deepest inheritance trees). Tool scripts and whether or not a variable is exported makes no difference.

### Steps to reproduce

I think this error is caused by Godot not handling large projects with deep inheritance trees very well. I can't pinpoint exactly what causes it, but it seems to have something to do with the amount of variables/identifiers a class has.

### Minimal reproduction project

I wasn't able to reproduce this in a test project when I copied all of my class code and deleted all functions. It seems to require a fairly complex codebase to reproduce, and for multiple reasons I don't want to post my entire game.

**Comment by AThousandShips** [comment] 2023-03-30 18:13
It's from here:
https://github.com/godotengine/godot/blob/dbf1a7277f70c63b2012e40d6850bc45e67fb35f/modules/gdscript/gdscript_vm.cpp#L633

Not sure what causes it though

**Comment by AThousandShips** [comment] 2023-03-30 18:19
Related: #74253

**Comment by TheSecondReal0** [comment] 2023-03-30 22:42
With more testing I think this error is caused by a indirect loops in class references. Seems like the error message could use some work or the parser could be improved to handle these kinds of loops.

**Comment by Calinou** [comment] 2023-04-01 17:07
- Duplicate of https://github.com/godotengine/godot/issues/74253.

**Closed by Calinou** 2023-04-01 17:07 UTC
