### ISSUE TITLE
@warning_ignore is not working

### ISSUE THREAD

**Issue by filantus** [godotengine/godot#62147] opened 2022-06-17 15:51 UTC
### Godot version

v4.0.alpha10.official [4bbe7f0b9]

### System information

Windows 10, GLES3

### Issue description

If try to define variable with name max or min there is appears warning like this:
`[Ignore]Line 4 (SHADOWED_GLOBAL_IDENTIFIER):The variable 'min' has the same name as a built-in function.`

If click on [Ignore] button, it creates @warning_ignore annotaion, but warning still remains and also still brings up at runtime.

The application by itself is works fine, but how to suppress theese warnings?
<img width="1280" alt="2022-06-17_18-36-25" src="https://user-images.githubusercontent.com/13046849/174333029-90de3a70-ce6d-4d07-b706-d2de5b104d34.png">

### Steps to reproduce

Code:
```
extends Node

@warning_ignore(shadowed_global_identifier)
var min

@warning_ignore(shadowed_global_identifier)
var max
```

### Minimal reproduction project

[test.zip](https://github.com/godotengine/godot/files/8928943/test.zip)

**Comment by Chaosus** [comment] 2022-06-17 16:15
![image](https://user-images.githubusercontent.com/3036176/174336911-864898c4-fbe5-468e-ab2d-3c04dd8adf6a.png)

**Comment by filantus** [comment] 2022-06-17 16:57
But what then @warning_ignore does?
  
And what if i want to see all another shadowed_global_identifier warnings (just except those what excplictly marked with @warning_ignore) ?

**Comment by Calinou** [comment] 2022-06-17 17:12
Duplicate of https://github.com/godotengine/godot/issues/56592.

**Closed by Calinou** 2022-06-17 17:12 UTC
