### ISSUE TITLE
No seamless looping possible in videoplayer

### ISSUE THREAD

**Issue by Galileo53** [godotengine/godot#25216] opened 2019-01-22 10:22 UTC
This is probably an addition to #6179.
I am opening a new issue because I don't see this as an enhancement. For me it is more or less a bug because there is no "working" workaround. Please don't be angry if it is not OK.

**Godot version:**
V3.0, V3.1

**OS/device including version:**
Windows 7

**Issue description:**
Looping within VideoPlayer is not natively supported. This leads to missing frames between any two sequences of the video. See also #6179

**Steps to reproduce:**
Since there is no "loop" command at the VideoPlayer, it is recommended to use:

func _process(delta):
  if not video_player.is_playing():
    video_player.play()

or similar.
Anyway, this will not solve the problem. Currently, when the first run of the "looping" video has finished, VideoPlayer stops playing, no longer drawing any pixels to the screen. Because the video_player.play() takes some time to start again (probably because the video stream must be decoded first) the background behind the video is shown (or black in case there is none).
Imho, the only solution is to implement a "Loop" command at the VideoPlayer that will not just stop and re-start, but will avoid that the decoding buffer will run empty at the end and will seamless refill the buffer from the beginning.

**Comment by Calinou** [comment] 2019-11-18 13:01
Duplicate of #6179.

**Closed by Calinou** 2019-11-18 13:01 UTC
Labels: bug, topic:core, topic:rendering
