### ISSUE TITLE
Godot doesn´t compile for win x86

### ISSUE THREAD

**Issue by Ranoller** [godotengine/godot#28949] opened 2019-05-17 01:23 UTC
**Godot version:**

66937c1e8298c3fb03a048818a0633561217641f

**OS/device including version:**

win 7 64 
VS2017 and VS2015
Python 2.7.13
Scons 2.5.1 
(That config work in a build a month ago)

**Issue description:**

Godot doesn´t compile 32 bit version
No -j option used
No previous build, fresh repository download.
![GodotCompileBug](https://user-images.githubusercontent.com/11712737/57896853-187d6300-7853-11e9-9e62-ef97269f3c41.png)

message are: object allocated on the heap may not be aligned 16 and formal parameter with requested alignment of 16 won´t be aligned.
flags: scons platform=windows target=release_debug tools=yes
I try to module_bullet_enabled=no but instead bullet, other module fails with same message.
Win 64 bit compiles without problem.

Edit:
At this point fails: e56f5d5c910f076fd93af71ada7550f441207f45 (10Apr2019)
At this point too: 9ba67387194ffbe130bdd325d069b853bc99b841 (27Mar2019)
It´s strange, i can´t compile from a fresh download in points that i compiled in the repository that i used to actualize.

**Comment by akien-mga** [comment] 2019-05-17 09:24
Seems to be an alignment issue in the bullet module, cc @AndreaCatania.

**Comment by Ranoller** [comment] 2019-06-16 11:00
Well, i doubt that this issue is only referenced to bullet module, other parts of the code fails at compile with the same error (16 bit alignment related). I did more test and i can compile 32 bit version with vs2019. 2017 and 2015 fails. So probably we are using some code that is not fully compatible with some of the older compilers from microsoft. I try to get a common patern for the fail and the unique file that is common in all the headers of the failing files is assert.h... probably coincidence, but let's say that is not only bullet module failing.

Since i need the 32b version i will follow this issue, but for me in enought to compile with 2019. I know that probably other people using 32 bit version are using official builds (i need compile because modules), so is possible that this issue is too specific for my use case (to valorate effort-results).

**Comment by Ranoller** [comment] 2019-06-16 11:38
Info. Versions of compiler tested:
VS2015: 19.00.23506
VS2017: 19.10.25019
VS2019: 19.20.27508.1

**Comment by akien-mga** [comment] 2020-01-15 14:39
Is this still reproducible in the current master branch?

**Comment by Ranoller** [comment] 2020-01-15 22:54
I has to delete vs2015 and vs2017 because are oversized to my ssd, so i can´t test. In VS2019 for me is not reproducible. But @willnationsdev has the same issue (https://github.com/godotengine/godot/issues/32080) and closed that to maintain opened only one (this). I don´t know if he is having problems now. There are more problems related with 32 bit editor, like the case warnings, i think there are all related, because the bug "born" dates, but i can´t proof that, so i delegate de close button to the project manager:

--------
| close |
--------

**Comment by akien-mga** [comment] 2020-01-16 08:49
I just noticed that you were using SCons 2.5.1, which is relatively old.
The buildsystem for Windows has been updated a couple of years ago to rely on new features on SCons 3.0, and it's advised to use the latest stable SCons release to compile Godot.
Not sure if that would have fixed the issue you ran into, but it's possible.

@willnationsdev Can you still reproduce this issue on an `x86` build?

**Comment by Ranoller** [comment] 2020-01-16 09:34
i will actualize scons, thanks

**Comment by akien-mga** [comment] 2020-07-26 20:27
Can anyone still reproduce it on VS 2017 or VS 2019 in the current `master` branch or `3.2` branch?

**Comment by Ranoller** [comment] 2020-07-26 21:22
In 2019 works, can't test in 2017... last time that i try not... i delegate close button to @willnationsdev

**Comment by willnationsdev** [comment] 2020-07-28 00:27
@Ranoller I only have a 2019 version of Visual Studio, and it compiled the `debug Win32` version just fine for me. I'm guessing that's enough to close this issue?

**Comment by akien-mga** [comment] 2020-07-28 07:21
Alright, I also don't have VS 2017 to test do let's close. Either it got fixed in Godot or in VS.

**Closed by akien-mga** 2020-07-28 07:21 UTC
Labels: bug, topic:buildsystem, topic:physics
