### ISSUE TITLE
Moving *.cs file in external editor causes the editor to throw error

### ISSUE THREAD

**Issue by pradeepbyju5** [godotengine/godot#36553] opened 2020-02-26 09:59 UTC
**Godot version: v3.2.stable.mono.official **

**OS/device including version: Mac OS 10.14.6 / Godot Editor**

**Issue description:**
If you move an existing *.cs file to a different directory in an external editor. Godot
throws "CSC(0,0): Source File "xxxx" could not be found.

**Steps to reproduce:**
1. Create a C# script in godot editor
2. Open script in an external editor like vscode
3. Create a directory in vscode
4. Move the script to the new dir inside vscode
5. Switch back to godot
6. Mono Build Project
7. You will see the error

**Minimal reproduction project:**
[scratch.zip](https://github.com/godotengine/godot/files/4254811/scratch.zip)

**Comment by WizzardMaker** [comment] 2020-02-26 12:59
That's a problem with the .csproj file. It keeps a reference to the old file
You can delete the old entry yourself in the mean time

**Comment by Chaosus** [comment] 2020-02-26 13:51
Duplicate of https://github.com/godotengine/godot/issues/35252

**Closed by Chaosus** 2020-02-26 13:51 UTC
