### ISSUE TITLE
Installation fails early on Vista 32bit, what are the prerequisits?

### ISSUE THREAD

**Issue by GameCy** [godotengine/godot#1189] opened 2015-01-12 13:57 UTC
I download the latest version and run as admin ..
allI get in the console is this:
EXEC PATHP: C:\Users\Play\Downloads\godot_win32-1.0stable.exe
EXEC PATHP: C:\Users\Play\Downloads\godot_win32-1.0stable.exe
opening pack C:\Users\Play\Downloads\godot_win32-1.0stable.exe, -1, -1
opening pack C:/Users/Play/Downloads/data.pck, -1, -1

a bug window appears and says: "godot_win32-1.0stable.exe has stopped  working ... please close the application"
is there an install.log somewhere?  what are the prerequisits before running instalation?

**Comment by reduz** [comment] 2015-01-12 14:21
no proper opengl 2.1 support

**Comment by GameCy** [comment] 2015-01-12 17:58
thanks, 

I suppose this or an analytical list of opengl caps wont help. Only a new video card will.


===================================[ System / CPU ]
- CPU Name: Intel(R) Core(TM)2 Duo CPU     E7400  @ 2.80GHz
- CPU Core Speed: 2793 MHz
- CPU logical cores: 2
- Family: 6 - Model: 7 - Stepping: 10
- Physical Memory Size: 4096 MB
- Operating System: Windows Vista 32-bit build 6002 [Service Pack 2]
- PhysX Version: drivers not installed


===================================[ Graphics Adapters / GPUs ]
- Current Display Mode: 1920x1200 @ 59 Hz - 32 bpp
- Num GPUs: 1

- GPU 1
  - Name: Intel(R) G41 Express Chipset
  - GPU codename: GMA X4500
  - Device ID: 8086-2E32
  - Subdevice ID: 17AA-3052
  - Driver: 8.15.10.2869 (10-4-2012) - GL:ig4icd32.dll
  - Bus Id: -1
  - Shader cores: 10
  - BIOS version: Intel Video BIOS
  - Memory size: 1294MB
  - Memory type: 
  - Memory bus width: 0-bit


===================================[ OpenGL GPU Capabilities ]
- OpenGL vendor: Intel
- OpenGL renderer: Intel(R) G41 Express Chipset
- OpenGL Version: 2.1.0 - Build 8.15.10.2869
- GLSL (OpenGL Shading Language) Version: 1.20  - Intel Build 8.15.10.2869
- ARB Texture Units: 8
- Vertex Shader Texture Units: 16
- Pixel Shader Texture Units: 16
- Geometry Shader Texture Units: 0
- Max Texture Size: 4096x4096
- Max Anisotropic Filtering Value: X2.0
- Max Point Sprite Size: 255.0
- Max Dynamic Lights: 16
- Max Viewport Size: 4096x4096
- Max Vertex Uniform Components: 512
- Max Fragment Uniform Components: 1024
- Max Geometry Uniform Components: 0
- Max Varying Float: 41
- Max Vertex Bindable Uniforms: 0
- Max Fragment Bindable Uniforms: 0
- Max Geometry Bindable Uniforms: 0
- Frame Buffer Objects (FBO) Support:[yes]
- Multiple Render Targets / Max draw buffers: 8
- Pixel Buffer Objects (PBO) Support:[yes]
- S3TC Texture Compression Support:[yes]
- ATI 3Dc Texture Compression Support:[no]
- Texture Rectangle Support:[yes]
- Floating Point Textures Support:[no]

**Comment by reduz** [comment] 2015-01-12 18:12
yeah some older intel cards say they support OpenGL but lack some
functions, which is really unfortunate, because it ends up crashing. I
don't have this hardware atm to test why it crashes (likely a missing
function)

**Comment by UsernameIsAReservedWord** [comment] 2015-01-12 18:27
maybe it would be helpfull to the godot reputation to display a warning message when an intel gpu is displayed, just in case this gpu is too old or too bugged ....

**Comment by akien-mga** [comment] 2015-11-06 10:16
Duplicate of #156, related to #1162.

**Closed by akien-mga** 2015-11-06 10:16 UTC
