### ISSUE TITLE
Godot overwrites `.import` settings with defaults if detect_3d=true

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#24220] opened 2018-12-08 00:12 UTC
Godot 3.0.6
Godot 3.1 alpha2

I've been having this problem for a long time with my terrain plugin.
I generate textures for which the default import settings are particularly unfit, and even have a tendency to bring the editor to its knees for trying to deal with them (https://github.com/Zylann/godot_heightmap_native_plugin/issues/16).
Although this resource usage should be fixed in the editor, I also want my generated textures to have different import settings than the defaults, *without forcing the user to set them by hand*.

So here is what I did in my plugin to workaround this, and how the problem occurs:

1) When I save a PNG, I also write a `.import` file next to it with intentionally omitted params, only with the parameters I want. Something like:
```
[remap]

importer="texture"
type="StreamTexture"

[deps]

source_file="res://tests/terrain6/terrain6.hterrain_data/normal.png"

[params]

compress/mode=0
compress/hdr_mode=0
compress/normal_map=0
flags/mipmaps=false
flags/filter=true
process/fix_alpha_border=false
```

2) When I unfocus/refocus the editor, Godot recognizes the new PNG and appears to run an importing operation on it, which results in completing the file with the missing params. Looking at the file, all is good so far, the workaround seems to have worked.

3) I closed the editor, and opened it again with my test scene, where the texture was used on a mesh: suddenly, Godot reimports my generated textures, my CPU and RAM have a bad time doing so, and when it's done I find my terrain quality is ruined by lossy compression. When I look at the `.import` files again, I find my parameters were overwritten with the defaults.

**Comment by Zylann** [comment] 2018-12-08 00:57
I added `detect_3d=false` to my generated `.import` and that solved it, however I find it quite strange  `detect_3d=true` (the default) would overwrite other parameters with defaults Oo

**Comment by akien-mga** [comment] 2020-01-09 09:28
Relevant code:

https://github.com/godotengine/godot/blob/28655e16d65ba8e5e281dd1be65d21b6630559c3/editor/import/resource_importer_texture.cpp#L93-L127

Solving the issue would be easy, but the question whether this is intended or should be changed remains open.

**Comment by KoBeWi** [comment] 2020-12-08 21:05
Can anyone still reproduce this bug in Godot 3.2.3 or any later release?

**Comment by KoBeWi** [comment] 2021-08-14 20:14
Closing due to lack of update. Please comment if you can still reproduce this issue in the latest stable version of Godot.

I use similar workaround for importing (I create a texture and add .import saying it's Image) and it works fine.

**Closed by KoBeWi** 2021-08-14 20:14 UTC
Labels: bug, discussion, topic:import
