### ISSUE TITLE
Assigned Animation Libraries can't be removed from Animation Players

### ISSUE THREAD

**Issue by Ansraer** [godotengine/godot#62346] opened 2022-06-23 11:16 UTC
### Godot version

4.10 alpha

### System information

Windows 10, amd 6900xt, vulkan clustered

### Issue description

Animation libraries that have been added to an animation player can't be removed.

### Steps to reproduce

1. Add an animation library to an animation player using the `Animation > Manage Animations...` windows.
2. Try to delete the animation library by clicking on the trash can symbol.

### Minimal reproduction project

Try to remove the "rotate" animation from the animation player in the Example Scene:
[AnimationBugReports.zip](https://github.com/godotengine/godot/files/8966705/AnimationBugReports.zip)

**Comment by timothyqiu** [comment] 2022-06-24 02:35
Duplicate of #61422
Fixed by #62151

**Closed by timothyqiu** 2022-06-24 02:35 UTC
Labels: bug, topic:editor, topic:animation
