### ISSUE TITLE
Hitting enter in the "Rename Project" window launches the project instead of applying the rename

### ISSUE THREAD

**Issue by MennoMax** [godotengine/godot#32554] opened 2019-10-04 18:50 UTC
**Godot version:**
3.2.alpha.custom_build.7e9c1041a, also present in 3.1.1

**OS/device including version:**
Linux Mint 19.2

**Issue description:**
Hitting enter while trying to rename a project launches the project instead of applying the rename. 

**Steps to reproduce:**
1. Select a project in the project list
2. Click on the "Rename" button
3. Enter a new name and hit enter

**Minimal reproduction project:**
-

**Comment by KoBeWi** [comment] 2019-10-04 19:19
Duplicate of #17620

**Closed by KoBeWi** 2019-10-04 19:19 UTC
