### ISSUE TITLE
Previously saved navigation mesh will always display the mesh in the editor.

### ISSUE THREAD

**Issue by hidemat** [godotengine/godot#64497] opened 2022-08-16 13:35 UTC
### Godot version

Godot 4 alpha 14

### System information

Windows 10 NVIDIA GeForce GTX 1050

### Issue description

Opening a previously saved scene containing a navigation mesh will cause the editor to always display the navigation mesh polygons regardless of the gizmo settings.
![image](https://user-images.githubusercontent.com/6559151/184892300-483c96cc-ef6e-4192-8e9b-0e748c0c4ed2.png)

### Steps to reproduce

Make a scene with a navigation region, bake the mesh, save, and exit. When you open the project again the mesh will be permanently visible in the editor.

### Minimal reproduction project

[NavigationPoylygonBug.zip](https://github.com/godotengine/godot/files/9351473/NavigationPoylygonBug.zip)

**Comment by smix8** [comment] 2022-08-16 15:13
This is already fixed in master as I cannot reproduce the issue there.
I assume Godot 4 alpha 14 didn't include the fix from #64147

**Comment by akien-mga** [comment] 2022-08-29 15:52
Indeed, that PR was merged right after the alpha 14 commit.

**Closed by akien-mga** 2022-08-29 15:52 UTC
Labels: bug, topic:editor, topic:navigation, topic:3d
