### ISSUE TITLE
Texture altas not crop when use as albedo texture in spatial material

### ISSUE THREAD

**Issue by firecloud888** [godotengine/godot#47993] opened 2021-04-18 02:04 UTC
**Godot 3.2.3 stable and latest RC version:**

**OS/device including version:**
windows 10 professional

**Issue description:**
Spatial material not crop the atlas texture region, it show the whole atlas, and it will not update the material when you use atlas texture, it just stuck there, you need to reopen the file, and seems godot not save material change if it use a atlas texture too. It will be a big problem when you make a large scene. I make a game which has a 3d parallax environment and a 2d collision, so use atlas texture can make some performance optimize in level drawing I guess.

**Steps to reproduce:**
Make a spatial material and apply to a mesh, simply add a  texture atlas(create a new atlas then drag a texture or use a godot gererate atlas)
![image](https://user-images.githubusercontent.com/9168814/115131775-3817fa00-a02d-11eb-88f2-b8d6ef9b3aeb.png)
**Minimal reproduction project:**
[SpatialAtlasTexBug.zip](https://github.com/godotengine/godot/files/6330363/SpatialAtlasTexBug.zip)

**Comment by Calinou** [comment] 2021-04-18 02:15
Duplicate of https://github.com/godotengine/godot-proposals/issues/1708.

**Closed by Calinou** 2021-04-18 02:15 UTC
