### ISSUE TITLE
Create multiple variables like a list | GDScript

### ISSUE THREAD

**Issue by CornerLord** [godotengine/godot#18657] opened 2018-05-06 15:09 UTC
Maybe I'm bad when it comes to searching, but this request doesn't seem to be asked yet.

In most of the coding languages you can do for example
`var money, xp, health`
as a list without having to write variable in this case multiple times. In GDScript you must define the type every time
`var money
var xp
var health`
That is not a big problem, but I don't see a reason why it couldn't be implemented in GDScript. The code would also look cleaner. :)

First time posting an issue, please tell me if I'm doing something wrong.

**Comment by Xrayez** [comment] 2018-05-07 08:40
Good suggestion. In some cases this might create confusion though (when adding or removing variables in the list):
```gdscript
export var money, xp, health setget set_health, get_health
```

**Comment by bojidar-bg** [comment] 2018-05-07 14:13
Note: this issue is a duplicate of #4863, but because of the complicated situation with #3504, it was semi-forgotten. I propose to keep this one, as it has attracted a lots of :+1:-s and some comments
<hr>

Some more corner-case problems with exports and setgets:
```gdscript
# Different export hints: looks odd, since we cannot do `var export(..) x`
export(int) var money, export(String) name
# Different setgets: they use commas too, and functions are ommitable when defaults are used:
var money setget set_money, get_money, name setget set_name, get_name
var money setget set_money,, name setget set_name,
# Potentially, `;` can be used instead of `,` in this case, but it can be done already:
var money setget set_money, get_money; name setget set_name, get_name # No need
var money setget set_money, get_money; var name setget set_name, get_name # Works
```

I think such a feature should be limited to only variables with same export hints and without setgets. Here is an example script:
```gdscript
export(NodePath) var player_a, player_b
onready var player_a_node = get_node(player_a), player_b_node = get_node(player_b)
var i = 0, j = 0 # var i, j = 0 will leave i uninitialized
```

**Comment by vnen** [comment] 2018-05-07 16:33
Considering how much stuff can be set to a class variable (`setget`, `export`, `onready`, `master`, `slave`, `sync`, `remote`), this should not be allowed. It makes everything hard to understand once you go adding qualifiers and initialization.

At most allow this only for local variables.

**Comment by KoBeWi** [comment] 2019-04-25 05:53
If annotations get added, the problem with class variable clutter might be gone and chained declaration could also allow to apply the same set of annotations to multiple variables.

**Comment by athal24** [comment] 2019-08-26 10:18
I just wanted to say that I also would love to have this feature. I still don't understand Github very well and it is not clear to me if this is going to be done or not as there seem to be many duplicates of this same proposition.

**Comment by Calinou** [comment] 2020-05-26 08:22
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!

**Closed by Calinou** 2020-05-26 08:22 UTC
Labels: feature proposal, topic:gdscript
