### ISSUE TITLE
ERROR: Class 'VisualScriptEditor' already exists

### ISSUE THREAD

**Issue by Gallilus** [godotengine/godot#51894] opened 2021-08-19 18:08 UTC
### Godot version

4.0.dev 19-08-2021

### System information

Windows 10

### Issue description

Can not open old project's and a new project gives this error when opening a .vs file

![image](https://user-images.githubusercontent.com/20573784/130120998-570950b0-5334-466e-938c-b6e8c14b0c52.png)

### Steps to reproduce

Open a new project and open a VisualScript

### Minimal reproduction project

[Temppppp.zip](https://github.com/godotengine/godot/files/7016888/Temppppp.zip)

**Comment by fire** [comment] 2021-08-19 19:19
@aaronfranke

**Comment by aaronfranke** [comment] 2021-08-19 19:26
Not sure why you pinged me. @mhilbrunner

**Comment by mhilbrunner** [comment] 2021-08-19 19:47
Yeah, https://github.com/godotengine/godot/pull/51627 may be the cause of this, will investigate. Thanks for reporting!

**Comment by mhilbrunner** [comment] 2021-08-19 23:23
I can confirm this doesn't happen with the commit prior to the above mentioned PR, but does with it, so it seems to be the cause.

**Comment by mhilbrunner** [comment] 2021-08-20 01:54
After some debugging, first thoughts:

This happens because both `VisualScriptEditor` and `_VisualScriptEditor` (now `vs_bind::VisualScriptEditor`) are exposed to GDScript.

Now after the above PR, both try to register as `VisualScriptEditor`, which collides and fails. This isn't an issue for all other underscored classes, as only one was ever exposed (e.g. `_OS` was exposed, not the wrapped `OS`).

Both are marked with `GDCLASS`, but only `_VisualScriptEditor` is registered via `GDREGISTER_CLASS`.

`VisualScriptEditor` isn't registered via `GDREGISTER_CLASS`, so it only gets registered and exposed at runtime when the first instance is created because of `GDCLASS`, which eventually calls `initialize_class` on construction, wich calls `ClassDB_add_class`.

As this only happens on runtime once a VS is opened, this wasn't caught during build time, CI or manual testing.

It seems a bug or maybe unintentional that both VisualScriptEditor classes are exposed. The latter (the `_VisualScriptEditor` one) also gets registered as a singleton under the name `VisualScriptEditor`, confusing things even further. It seems it just allows to add custom nodes.

We could solve this by renaming `_VisualScriptEditor`/`vs_bind::VisualScriptEditor`, as having a `VisualScriptEditor` singleton that just has the following methods:
```
create_node_custom(name)
add_custom_node(name, category,cript)
remove_custom_node(name, category)
```
... and doesn't have anything to do with the proper `VisualScriptEditor` seems a little werid. It doesn't even itself interact with the VS script editor directly.

Maybe we could just rename it `VisualScriptCustomNodes`, and keep the singleton named `VisualScriptEditor`. Or should we rename the singleton to `VisualScript`?

**Comment by Gallilus** [comment] 2021-08-20 04:39
create_node_custom(name)?

**Comment by fire** [comment] 2021-08-20 08:06
@Gallilus 

Does VisualScript.add_custom_node() make sense to you?

**Comment by Gallilus** [comment] 2021-08-20 09:01
What would VisualScript.add_custom_node() do? Create custom node from Gdscript?

**Comment by mhilbrunner** [comment] 2021-08-20 11:35
This was fixed in https://github.com/godotengine/godot/pull/51916 by un-exposing the internal editor class.

Please let us know if you still run into this issue with current master. Thanks again for reporting!

**Comment by Gallilus** [comment] 2021-08-20 14:30
@mhilbrunner 

Now I am able to open the editor. But it is not usable.
The only node I'm able to add is using rmb-click

And the menu is all phunky

![image](https://user-images.githubusercontent.com/20573784/130248735-8916df99-f4a6-4664-9ed6-c3da53371377.png)

**Comment by mhilbrunner** [comment] 2021-08-21 00:54
Thats... unfun. Thanks for the feedback, will check tomorrow.

**Comment by mhilbrunner** [comment] 2021-08-23 16:20
@Gallilus Thanks again for taking the time with this. Would you be willing to build and test it with this PR?
https://github.com/godotengine/godot/pull/52023

It hopefully should be a better fix :)

**Comment by fire** [comment] 2021-08-23 16:38
Can confirm these operations:

1. Can spawn new node
2. Left sidebar showing functions and variables work
3. Dragging a new now can now open the auto complete.

**Closed** 2021-08-25 12:41 UTC
Labels: bug, topic:editor, topic:visualscript, regression
