### ISSUE TITLE
Editor corrupt scenes by saving null values for unexisting exports

### ISSUE THREAD

**Issue by Gnumaru** [godotengine/godot#73937] opened 2023-02-25 17:14 UTC
### Godot version

4.0.rc5

### System information

windows 10

### Issue description

On RC5 (this wasn't happening on RC4), whenever a tool script inherits from another and tries to use in the body of a function a property that is defined in the base script, the inspector shows a nameless export property with null value. If the scene is saved, the editor saves several 'exported properties' without name with a null value, which leads to a corrupt scene file.

![image](https://user-images.githubusercontent.com/5783414/221370558-a650a3e9-4f39-4d88-9893-b79b21aa1d8e.png)

### Steps to reproduce

https://user-images.githubusercontent.com/5783414/221370337-751a4777-65e2-4800-b0ee-f72042d65f45.mp4

### Minimal reproduction project

[DerivedToolUsingBasePropertyProblemRC5.zip](https://github.com/godotengine/godot/files/10831809/DerivedToolUsingBasePropertyProblemRC5.zip)

**Comment by KoBeWi** [comment] 2023-02-25 18:37
Duplicate of #73905

**Closed by KoBeWi** 2023-02-25 18:37 UTC
