### ISSUE TITLE
Toggle Comment has unexpected behavior in gdscript

### ISSUE THREAD

**Issue by doman412** [godotengine/godot#68542] opened 2022-11-11 20:44 UTC
### Godot version

v4.0.beta4.official [e6751549c]

### System information

macOS Version 13.0 (22A380)

### Issue description

When toggling a comment in gdscript, the `#` for the comment is placed at the start of the line regardless of indentation. Attempting to uncomment a line where the `#` is not at the start of the line leads to a double comment and not an uncomment.

I'd expect the behavior to be similar to other editors like vscode where a line that becomes a comment starts at the correct indentation, not at the start of the line.

video of behavior:

https://user-images.githubusercontent.com/3157204/201427397-a9a2c1e9-4de2-4c9c-b956-f15513bf020e.mov

### Steps to reproduce

Attempt to toggle a line of code into a comment that is indented.

**Comment by Calinou** [comment] 2022-11-11 21:21
Duplicate of https://github.com/godotengine/godot-proposals/issues/110.

**Closed by Calinou** 2022-11-11 21:21 UTC
