### ISSUE TITLE
10 % Android crash report

### ISSUE THREAD

**Issue by anisc** [godotengine/godot#46768] opened 2021-03-07 18:33 UTC
10 % of my downloads on the Play store are reporting this. Just released the app so we are talking about 200DL.

signal 11 (SIGSEGV), code 1 (SEGV_MAPERR)

*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
pid: 0, tid: 0 >>> com.blabla.mygame <<<

backtrace:
  #00  pc 0000000000015d90  /vendor/lib64/egl/libGLESv2_mtk.so
  #00  pc 000000000001598c  /vendor/lib64/egl/libGLESv2_mtk.so (glBlitFramebuffer+5320)
  #00  pc 000000000059a960  /data/app/com.blabla.mygame-Xolq8R***********mvNqlgg==/lib/arm64/libgodot_android.so
  #00  pc 0000000000e3b9d4  /data/app/com.blabla.mygame-Xolq8R***********mvNqlgg==/lib/arm64/libgodot_android.so
  #00  pc 0000000000e1a040  /data/app/com.blabla.mygame-Xolq8R***********mvNqlgg==/lib/arm64/libgodot_android.so
  #00  pc 0000000000183ab8  /data/app/com.blabla.mygame-Xolq8************mvNqlgg==/lib/arm64/libgodot_android.so
  #00  pc 0000000000155434  /data/app/com.blabla.mygame-Xolq8************mvNqlgg==/lib/arm64/libgodot_android.so (Java_org_godotengine_godot_GodotLib_step+184)
  #00  pc 000000000003d1d0  /data/app/com.blabla.mygame-Xolq8R***********mvNqlgg==/oat/arm64/base.odex (offset 0x3d000) (org.godotengine.godot.GodotLib.audio [DEDUPED]+144)
  #00  pc 0000000000002298  /dev/ashmem/dalvik-jit-code-cache (deleted)

**Godot version:**
3.2.3 

**OS/device including version:**
Oppo A1k  Android 9 (SDK 28)
Huawei Honor 8A Android 9 (SDK 28)

**Issue description:**
NA

**Steps to reproduce:**
Not sure but the app contain one particle system and uses GLES3

**Minimal reproduction project:**
NA

**Comment by Calinou** [comment] 2021-03-07 18:37
> Not sure but the app contain one particle system and uses GLES3

Use the GLES2 renderer and CPUParticles on Android. Lots of Android devices have poor support for the current GLES3 renderer.

I'll close this since we can't do anything without a minimal reproduction project. The backtrace isn't useful as it doesn't contain debug symbols.

**Closed by Calinou** 2021-03-07 18:37 UTC

**Comment by anisc** [comment] 2021-03-07 18:42
ok I will switch to GLES 2 and report back thank you so much for the prompt reply !!!
