### ISSUE TITLE
Collision Algorithm of RigidBody2D

### ISSUE THREAD

**Issue by liryu1973** [godotengine/godot#39493] opened 2020-06-13 01:52 UTC
Godot version:3.2.1

OS/device including version:
Windows10, gtx1050, GLES3

Issue description:
See the gif movie first.
During the second collision, RigidBody2D has a significant overlap.
Essentially, overlap in a collision should not be drawn.
If an overlap is detected, you can push it back and then draw it so that it won't be drawn on the screen at all.
Perhaps the order of the process is reversed?
If collision processing is performed after drawing, the pushback will be drawn in the next frame, causing overlap in the current frame.

![collision](https://user-images.githubusercontent.com/64412290/84556663-e3498a00-ad5e-11ea-95a1-df88a523f13c.gif)

[RB2D_Test.zip](https://github.com/godotengine/godot/files/4773808/RB2D_Test.zip)

Postscript:
Changing Physics fps or Continuous Cd will not improve the overlap.

**Comment by Ev1lbl0w** [comment] 2020-06-13 11:31
In my setup *(Linux, GeForce MX110, GLES3)*, only the first collision shows this "bounce" behaviour; after that, no matter how fast I hit, it doesn't overlap.

**Comment by Calinou** [comment] 2020-06-13 11:32
I think this issue is a duplicate of another one, but I can't find the other issue in question right now.

**Comment by liryu1973** [comment] 2020-06-13 12:38
> In my setup _(Linux, GeForce MX110, GLES3)_, only the first collision shows this "bounce" behaviour; after that, no matter how fast I hit, it doesn't overlap.

I thought so too at first.
It seems that overlap is less likely to occur after the second time than the first time.
But that doesn't mean it doesn't happen at all.
If you change the y position and make it collide again The overlap happens again.
The second time in the video is a fluke. In my environment, it happens when it happens a number of times.

I've heard that Godot is currently undergoing a major refactoring.
Please fix this together.

**Comment by avencherus** [comment] 2020-06-13 17:18
RigidBody2Ds do have long standing issues with interpenetration during the frame, and I've never known the CCD from the node property to alleviate this or even work at high speed.  When it passes into other bodies is also inconsistent.

I once used them for characters, and most the time jumping and landing was fine, but every dozen landings the character might dig into the surface and halt their velocity.

**Comment by abhinav4987** [comment] 2020-07-03 14:42
is this issue open?

**Comment by Zireael07** [comment] 2020-07-03 14:57
CCD has been broken for several years :(

**Comment by abhinav4987** [comment] 2020-07-03 14:59
> CCD has been broken for several years :(

so is it open?

**Comment by Zireael07** [comment] 2020-07-03 15:01
Yes, there's an open issue somewhere about it.

**Comment by avencherus** [comment] 2020-07-03 16:51
Possibly related: https://github.com/godotengine/godot/issues/34215

**Comment by Exxion** [comment] 2020-12-18 19:01
This is because, by default, the objects are only moved each frame 0.3 times the distance it would take to completely separate them. I'm guessing this is to make collisions involving multiple objects more stable, but I don't really know. You can change the custom solver bias variable on the collision shapes involved to change this behavior, including setting it all the way to 1 to make collisions perfectly rigid. Again, this probably causes some instability, though.

**Comment by Calinou** [comment] 2020-12-18 20:36
Duplicate of https://github.com/godotengine/godot/issues/34215.

**Closed by Calinou** 2020-12-18 20:36 UTC
Labels: bug, topic:physics
