### ISSUE TITLE
LineEdit, TextEdit nodes problem. Incorrect text editing on android

### ISSUE THREAD

**Issue by Anynak** [godotengine/godot#32794] opened 2019-10-13 14:11 UTC
**Godot version:**
Godot 3, Godot 3.1.1, Godot 3.2 alpha2
**OS/device including version:**
Android 7.0
**Issue description:**
LineEdit, TextEdit nodes bug. Incorrect text editing on android.
If you move the caret to the middle of the text, when you type the keyboard copies a section of the text.
**Steps to reproduce:**
If you type
aaaaabbbbcccc|
move the caret inbetween the a and b
aaaaa|bbbbcccc
and type d, you get
aaaaabbbbccccd|bbbbcccc
instead of the expected
aaaaad|bbbbcccc

there is also a bug when deleting text.
If you type
aabb|
move the caret inbetween the a and b
aa|bb
and press backspace on virtual keybord, you get
aab|bb
instead of the expected
a|bb

The problem is noticed on an android with Google keyboard. No problem editing text on PC.
also there are no problems with editing numbers

**Minimal reproduction project:**
just a LineEdit ore TextEdit node compiled for android

**Comment by allkhor** [comment] 2019-10-13 15:03
Duplicate of #27065 ?

**Comment by Anynak** [comment] 2019-10-13 15:07
> 
> 
> Duplicate of #27065 ?

with some additions

**Comment by allkhor** [comment] 2019-10-13 15:11
You can always include additional information to the opened issue.

**Comment by Calinou** [comment] 2020-04-12 13:45
Duplicate of #27065.

**Closed by Calinou** 2020-04-12 13:45 UTC
Labels: bug, platform:android, topic:porting
