### ISSUE TITLE
ScriptEditor grabs editor shortcuts when it is opened

### ISSUE THREAD

**Issue by me2beats** [godotengine/godot#46678] opened 2021-03-04 23:48 UTC
**Godot version:**

tested on 3.2.3 and 3.2.4rc3

**OS/device including version:**

Linux

**Issue description:**

Editor shortcuts for example `Ctrl+Z` don't work if `ScriptEditor` is opened. The problem is it may not be focused, just opened; the caret is not blinking. This is confusing.

**Steps to reproduce:**
1. Create new Godot project
2. Create a script and open it in Godot ScriptEditor
3. do any change in `Inspector` - change some parameter value. 
ScriptEditor should be opened.
When you change the property in Inspector, note that ScriptEditor caret disappeared (this should mean that ScriptEditor is not active now)
4. Press `Ctrl+Z` (to undo changing the property in 3).
As you can see the property is not changed back.

**Minimal reproduction project:**

**Comment by Calinou** [comment] 2021-03-05 18:12
cc @EricEzaM 

I know this has been fixed in the `master` branch, but we probably need to figure out a way to fix this for 3.2.5.

**Comment by fenixn0909** [comment] 2021-03-25 00:27
If you try Command + Shift + C to copy file path with code editor opened, the code editor will move to next line and copy nothing from the file.

MacOX 10.15.7 
Godot 3.2.4 rc5

**Comment by EricEzaM** [comment] 2021-09-20 07:41
This is an input related issue in 3.X due to the fact that there is no "context" for shortcuts. Duplicate of #52861, please direct discussion there.

**Closed by EricEzaM** 2021-09-20 07:41 UTC
Labels: bug, topic:editor, topic:input
