### ISSUE TITLE
Ridiculous Physics CPU Spike with multiple CharacterBody3D colliding with each other

### ISSUE THREAD

**Issue by MagickPanda** [godotengine/godot#78895] opened 2023-07-01 05:40 UTC
### Godot version

4.1 rc2

### System information

Godot v4.1.rc2 - Windows 10.0.19043 - Vulkan (Mobile) - dedicated NVIDIA GeForce GTX 1060 6GB (NVIDIA; 31.0.15.1694) - AMD Ryzen 7 1700 Eight-Core Processor (16 Threads)

### Issue description

I found this problem when testing the possiblity of using CharacterBody3D directly as my game object's physics.

I was attempting to make 4 objects with 'CharacterBody3D' as root and a simple convex collision3d shape generated from in-game model preview(view-> generate simple convex blahblah) convex generation function, I made them all move towards to a fixed Vector3 point in game space, after a few seconds of moving, they finally run into each other and begin to collide, then the physics frame uses up all CPU time and take like 300-500ms per process, which is ridiculous with only 4 objects.

Also I tried with a simple CharacterBody3D and the terrain as convex Static3D object, it randomly spikes too, but it's not as 100% reproducible as the one with 4 CharacterBody3D objects I just posted. So I only posted this one.

Here is a video recording the problem and the profiler view:
https://github.com/godotengine/godot/assets/35385424/cfed1528-5b35-41ed-88a5-10e7eff5e96f

Tried changing the CharacterBody3D's inspector setting from Grounded to Floating, and tried to turn on the 'Run Physics on a separated thread' option, but neither worked, it will end up like 1-2FPS with 500ms physics time eventually upon collisions.

Tried searching a bit but didn't find a similiar issue, lemme know if this is already reported, and please close this one if it's known issue/being fixed.
Thanks.

### Steps to reproduce

Just run the minimal project in the attachment and click 'Run' button.

Check Debugger->Profiler->Start to see the physics frame time sky-rocket ing from 10ms to 500ms -.-

### Minimal reproduction project

[physics-spike.zip](https://github.com/godotengine/godot/files/11924607/physics-spike.zip)

**Comment by Zireael07** [comment] 2023-07-01 07:22
Convex shapes generated by that function are NOT simple, can have thousands of vertices! Use a sphere or a box instead

**Comment by AThousandShips** [comment] 2023-07-01 07:33
* Duplicate of: https://github.com/godotengine/godot/issues/48587

**Comment by AThousandShips** [comment] 2023-07-01 10:32
My bad, looked through your code and saw ridiculously large collision shapes but running the project those weren't used, reopening

**Comment by AThousandShips** [comment] 2023-07-01 10:50
Since you tested with simpler shapes as well I assume this is actually related to using `move_and_slide` like this, I'm not sure how safe it is to have multiple bodies do this against each other constantly, might just be something that is very non-performant to do

**Comment by Calinou** [comment] 2023-07-01 10:50
This is still a duplicate of https://github.com/godotengine/godot/issues/48587, as the underlying cause is the same. The other issue's title should be changed as it doesn't just affect complex convex shapes, but any convex shape really.

**Comment by AThousandShips** [comment] 2023-07-01 10:53
Gotcha! Didn't see any mention of this simple shapes (28 points) on that one

**Closed** 2023-07-01 11:14 UTC
Labels: bug, topic:physics, needs testing, topic:3d, performance
