### ISSUE TITLE
Launching the game from the Android editor has no way to quit it

### ISSUE THREAD

**Issue by QbieShay** [godotengine/godot#73088] opened 2023-02-11 10:55 UTC
### Godot version

4 RC1

### System information

Android 13, Samsung Galaxy 7 FE

### Issue description

I tried launching my godot project on android, but i didn't find a way to quit it. The applications overview has one single entry for godot and if i close that i close both the launched application and the editor

### Steps to reproduce

download android editor, make an empty scene, launch, ~~get vim experience~~ be stuck

### Minimal reproduction project

see above

**Comment by m4gr3d** [comment] 2023-03-22 02:27
@QbieShay Is this still an issue? You should be able to close the game by pressing the back button.

**Comment by m4gr3d** [comment] 2023-05-30 00:02
Closing as the issue is no longer reproducible.

**Closed by m4gr3d** 2023-05-30 00:02 UTC
Labels: enhancement, platform:android, topic:editor
