### ISSUE TITLE
SIGSEGV crash when importing images.

### ISSUE THREAD

**Issue by fafner** [godotengine/godot#33765] opened 2019-11-20 13:58 UTC
**Godot version:**

v3.1.1.stable.mono.official

**OS/device including version:**

macOS Catalina 10.15.1

**Issue description:**

Editor crashes with SIGSEGV when trying to import images (both by drag-and-drop into the FileSystem panel and by adding the images to the appropriate folder in Finder).

**Steps to reproduce:**

- Create new project
- Create new folder under 'res://' called Textures
- Drag image into the new Textures folder
- Editor now hangs indefinitely.

**Complete stack trace**

```
ERROR: alloc_static: Condition ' !mem ' is true. returned: __null
   At: core/os/memory.cpp:87.

=================================================================
        Native Crash Reporting
=================================================================
Got a SIGSEGV while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries 
used by your application.
=================================================================

=================================================================
        Basic Fault Adddress Reporting
=================================================================
Memory around native instruction pointer (0x10c3465f0):0x10c3465e0  ff be 03 00 00 00 eb 23 0f 1f 84 00 00 00 00 00  .......#........
0x10c3465f0  8b 03 88 44 11 02 88 64 11 01 89 c6 c1 ee 10 40  ...D...d.......@
0x10c346600  88 34 11 c1 e8 18 be 04 00 00 00 88 44 11 03 48  .4..........D..H
0x10c346610  83 c2 04 48 01 f3 ff cf 75 a6 4d 01 c7 41 ff c1  ...H....u.M..A..

=================================================================
        Native stacktrace:
=================================================================
        0x10c09a6e4 - /Applications/Godot_mono.app/Contents/MacOS/Godot : mono_dump_native_crash_info
        0x10c08e5c5 - /Applications/Godot_mono.app/Contents/MacOS/Godot : mono_handle_native_crash
        0x10c0a13e9 - /Applications/Godot_mono.app/Contents/MacOS/Godot : mono_sigsegv_signal_handler
        0x7fff6856cb1d - /usr/lib/system/libsystem_platform.dylib : _sigtramp
        0x0 - Unknown
        0x10c346a1d - /Applications/Godot_mono.app/Contents/MacOS/Godot : _ZN14ImageLoaderBMP10load_imageE3RefI5ImageEP10FileAccessbf
        0x10e822257 - /Applications/Godot_mono.app/Contents/MacOS/Godot : _ZN11ImageLoader10load_imageE6String3RefI5ImageEP10FileAccessbf
        0x10d35cda6 - /Applications/Godot_mono.app/Contents/MacOS/Godot : _ZN23ResourceImporterTexture6importERK6StringS2_RK3MapI10StringName7Variant10ComparatorIS4_E16DefaultAllocatorEP4ListIS0_S8_ESE_PS5_
        0x10cee5a30 - /Applications/Godot_mono.app/Contents/MacOS/Godot : _ZN16EditorFileSystem14_reimport_fileERK6String
        0x10cedd32a - /Applications/Godot_mono.app/Contents/MacOS/Godot : _ZN16EditorFileSystem14reimport_filesERK6VectorI6StringE
        0x10cedbd4b - /Applications/Godot_mono.app/Contents/MacOS/Godot : _ZN16EditorFileSystem20_update_scan_actionsEv
        0x10cee1a5f - /Applications/Godot_mono.app/Contents/MacOS/Godot : _ZN16EditorFileSystem13_notificationEi
        0x10ceeb2ec - /Applications/Godot_mono.app/Contents/MacOS/Godot : _ZN16EditorFileSystem14_notificationvEib
        0x10e61c8c3 - /Applications/Godot_mono.app/Contents/MacOS/Godot : _ZN6Object12notificationEib
        0x10d743338 - /Applications/Godot_mono.app/Contents/MacOS/Godot : _ZN9SceneTree19_notify_group_pauseERK10StringNamei
        0x10d743818 - /Applications/Godot_mono.app/Contents/MacOS/Godot : _ZN9SceneTree4idleEf
        0x10c30072f - /Applications/Godot_mono.app/Contents/MacOS/Godot : _ZN4Main9iterationEv
        0x10c2d5677 - /Applications/Godot_mono.app/Contents/MacOS/Godot : _ZN6OS_OSX3runEv
        0x10c2d82bb - /Applications/Godot_mono.app/Contents/MacOS/Godot : main
        0x7fff6836b2e5 - /usr/lib/system/libdyld.dylib : start

=================================================================
        Telemetry Dumper:
=================================================================
Pkilling 0x700006abb000 from 0x11af2ddc0
Entering thread summarizer pause from 0x11af2ddc0
Finished thread summarizer pause from 0x11af2ddc0.

Waiting for dumping threads to resume

Debug info from gdb:


=================================================================
        External Debugger Dump:
=================================================================
(lldb) command source -s 0 '/tmp/mono-gdb-commands.626'
Executing commands in '/tmp/mono-gdb-commands.626'.
(lldb) process attach --pid 626
```

**Comment by fafner** [comment] 2019-11-23 13:18
I've not been able to reproduce this in 3.2 beta 2.

**Comment by KoBeWi** [comment] 2019-11-28 12:49
I can't reproduce it. Maybe it's OS specific?
Is it important to fix for 3.1, if 3.2 already works?

**Comment by KoBeWi** [comment] 2019-12-13 21:26
@fafner Does it happen in 3.1.2?

**Comment by fire** [comment] 2020-10-27 03:52
Closing due to lack of update. Please comment if you can still reproduce this issue in the latest stable version of Godot.

**Closed by fire** 2020-10-27 03:52 UTC
Labels: bug, crash, topic:editor, topic:import
