### ISSUE TITLE
Vulkan: Visible banding on untextured materials

### ISSUE THREAD

**Issue by Altair1234** [godotengine/godot#59168] opened 2022-03-15 14:55 UTC
### Godot version

Godot 4 Alpha 3

### System information

Win 10, 3060

### Issue description

![Occult Prototyping (DEBUG) 15-03-2022 08_18_19 PM](https://user-images.githubusercontent.com/28735504/158405585-5547df9a-3153-4405-a75f-0678b3825fcd.png)
![Occult Prototyping (DEBUG) 15-03-2022 08_18_30 PM](https://user-images.githubusercontent.com/28735504/158405688-f0ff197e-5b2a-49c2-90b8-8dcca79b818f.png)

Look at the black road and the launchpad.

### Steps to reproduce

Not sure, see this banding at multiple places.

**Comment by Calinou** [comment] 2022-03-15 17:31
@Altair1234 Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

**Comment by mrjustaguy** [comment] 2022-03-15 17:58
some of it looks like shadow acne to me...

**Comment by Altair1234** [comment] 2022-03-16 06:44
Normal Bias isn't working, I'll upload a minimal reproduction project right away.

**Comment by Altair1234** [comment] 2022-03-16 06:51
[CharacterBody3dTest.zip](https://github.com/godotengine/godot/files/8259545/CharacterBody3dTest.zip)

Much more subtle in this project but it is there. While a Normal Bias of 2 makes the effect *extremely* subtle in this project, in my project it is just as visible.

**Comment by mrjustaguy** [comment] 2022-03-16 10:24
What you are dealing with is not banding, it's shadow acne. This is because of too low shadow resolution for the respective splits, playing around with the bias settings can help mitigate the issue, and so can increasing the effective shadow resolution by tweaking the splits and shadow distance and/or increasing the resolution in project settings

**Comment by Calinou** [comment] 2022-03-16 17:21
Closing per @mrjustaguy's comment. See also https://github.com/godotengine/godot/pull/55757 which would 
alleviate this issue in most scenes.

**Closed by Calinou** 2022-03-16 17:21 UTC
Labels: bug, topic:rendering, needs testing, topic:3d
