### ISSUE TITLE
Godot engine doesn't start for some Windows 10 users

### ISSUE THREAD

**Issue by Jabbschy** [godotengine/godot#17695] opened 2018-03-22 12:54 UTC
**Godot version:**

3.0.1 and 3.0.2

**OS/device including version:**

Windows 10 Build 10.0.10586

**Issue description:**

When I start the Godot engine, only the console opens and it doesn't show any error, the only message it shows is this one
> **OpenGL ES 3.0 Renderer: Intel(R) HD Graphics 530**

It worked a few days ago.

**Comment by Zireael07** [comment] 2018-03-22 13:09
Did you update Windows 10 or video card drivers in the meantime?

**Comment by Jabbschy** [comment] 2018-03-22 13:39
@Zireael07 No, I didn't.

**Comment by BearDooks** [comment] 2018-04-10 02:50
I have the same issue on my machine.

Running Windows 10 Pro 1709 build 16299.309
GeForce GTX 1060 (driver version 23.21.13.9135)
Both Godot 3.0.1 and 3.0.2

When I open Godot I see the following

> OpenGL ES 3.0 Renderer: GeForce GTX 1060 3GB/PCIe/SSE2

If I wait a few minutes it will open the project selection page. Once I select something the same issue happens. If I do get into the editor, trying to run the project will produce the same results. The project will take a few minutes to load, but will work fine.

**Comment by reduz** [comment] 2018-09-07 00:48
I have no idea what this bug is, but as I cannot reproduce it, anyone who can test it, reproduce it and find th reason is welcome.

**Comment by BearDooks** [comment] 2018-09-07 01:13
Is there a log or something I can pull when this happens so I can see what is going on?

**Comment by Byteron** [comment] 2018-09-09 10:00
I have the same issue on my PC, running Windows 10.
This issue occured with 3.0.6, 3.1 and even 2.1.5, always hanging up on the drivers line
"OpenGL ES 3.0 Renderer: GeForce GTX 1060 6GB/PCIe/SSE2" for about one minute, then in continues normally. This also happens every time when I run "F5" a project, which makes working with it a bit of a pain. 
I have a second OS (Linux Manjaro, same machine) on which everything works perfectly fine.

I thought it might have been a driver update causing this, but after rolling back the driver to a version where it worked before, this issue still occured, so it seems to be related to a recent Windows 10 update, as Godot on other OS' seem to work fine.

**Comment by BearDooks** [comment] 2018-09-09 23:30
I have other Windows 10 machines around that it works fine on. The only difference is they are laptops without a video card in the PCIe slot. 

This also worked before when I was using my GTX460, seems to be when I upgraded to the new video card the issue started. I did a full rebuild of the OS and I am still having the issue.

**Comment by Byteron** [comment] 2018-09-11 07:27
On my laptop, Windows 10 as well, it works fine and I do have a GTX 950m in there.
Though it seems Godot initializes with the Intel graphics instead of the dedicated nvidia gpu.

**Comment by DualMatrix** [comment] 2018-09-18 23:05
I have this issue too sometimes. You can just press enter in the console to make it advance again. Win10 as well BTW

**Comment by Jabbschy** [comment] 2018-11-12 11:44
For the reason that some people have this problem, my solution was restarting the computer. I wasn't able to reproduce the error, and it didn't happen again.

**Comment by BearDooks** [comment] 2018-11-12 13:34
> For the reason that some people have this problem, my solution was restarting the computer. I wasn't able to reproduce the error, and it didn't happen again.

I can do this as well but the issue comes back. I have also restarted the video driver with Win Key + CTRL + SHIFT + B but this does not solve the issue. I have noticed I can reproduce the issue if sometimes if I edit the code and save it while the game is running.

**Comment by Byteron** [comment] 2018-11-12 13:39
@BearDooks sounds exactly like what I was experiencing.

**Comment by BearDooks** [comment] 2018-11-12 13:42
@Byteron I know I asked this before but no one seemed to answer me. Is there a way to get some debug info from Godot itself. Windows event viewer, or running Godot with a switch on the end of it. This is my only machine, so it really makes trying to work in Godot hard if not impossible at times.

**Comment by Calinou** [comment] 2018-11-12 13:51
> Is there a way to get some debug info from Godot itself.

You can run Godot using the Visual Studio debugger or the standalone [WinDbg](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/debugger-download-tools). Note that the output will be more useful if you build Godot from source so that you have debugging symbols available.

**Comment by akien-mga** [comment] 2019-01-22 08:18
> I have this issue too sometimes. You can just press enter in the console to make it advance again. Win10 as well BTW

That's likely unrelated, it sounds like you focused the terminal, which pauses the execution of its child process until you press Enter. The same happens with any application started from cmd.exe.

**Comment by akien-mga** [comment] 2019-12-14 00:08
There hasn't been any such reports in many months, so I assume this was a Windows update issue that eventually got fixed (either system update or drivers). Closing, but feel free to comment if you can still reproduce it.

**Closed by akien-mga** 2019-12-14 00:08 UTC
Labels: bug, hero wanted!, topic:thirdparty

**Comment by Aninuscsalas** [comment] 2020-07-24 10:09
i have this problem in win 7

**Comment by Calinou** [comment] 2020-07-24 10:30
@Aninuscsalas Please open a new issue for this. Make sure to state your hardware in the issue.
