### ISSUE TITLE
Starting 5 May, you must let us know why your app requires broad storage access (message from google play store)

### ISSUE THREAD

**Issue by anisc** [godotengine/godot#48003] opened 2021-04-18 16:58 UTC
**Godot version:**
3.2.3

**OS/device including version:**
Android

**Issue description:**
I recieved a message from GooglePlay that I need to provide a reason why app contains the 'request Legacy External Storage" flag.

But it doesn't.

The only permission I have selected for export is "Internet".
What can cause this? and where can I find the "requestLegacyExternalStorage" flag ?

**The full message from google play store:**
`We've detected that your app contains the requestLegacyExternalStorage flag in the manifest file of one or more of your app bundles or APKs.

Developers with apps on devices running Android 11+ must use scoped storage to give users better access control over their device storage. To release your app on Android 11 or newer after 5 May, you must either:

    Update your app to use more privacy-friendly best practices, such as the storage access framework or Media Store API
    Update your app to declare the All files access (MANAGE_EXTERNAL_STORAGE) permission in the manifest file, and complete the All files access permission declaration in Play Console from 5 May
    Remove the All files access permission from your app entirely

For apps targeting Android 11, the requestLegacyExternalStorage flag will be ignored. You must use the All files access permission to retain broad access.

Apps requesting access to the All files access permission without a permitted use will be removed from Google Play, and you won't be able to publish updates.`

**Comment by mortarroad** [comment] 2021-04-18 17:12
Duplicate of #47910. This should already be fixed.

**Comment by anisc** [comment] 2021-04-18 17:17
@mortarroad is there a way to fix this with 3.2.3 ?
This seems to be fixed with 3.3

**Comment by mortarroad** [comment] 2021-04-18 18:19
None that I know of.
The release of 3.3 will be very soon, and it should be backward compatible.
You can already try the release candidate: https://godotengine.org/article/release-candidate-godot-3-3-rc-9

**Comment by madmiraal** [comment] 2021-06-08 12:37
Closing as duplicate of #47910 and fixed in 3.3.

**Closed by madmiraal** 2021-06-08 12:37 UTC
Labels: platform:android, topic:porting
