### ISSUE TITLE
Auto-complete not working with autoload scripts

### ISSUE THREAD

**Issue by Joseph22Jct** [godotengine/godot#75519] opened 2023-03-31 02:52 UTC
### Godot version

4.0.1

### System information

Windows 10

### Issue description

When I write a variable on a Autoload Script (such as Globals.gd), with a class_name and making use of Static typing, it does not autocomplete any function from the class like it should, instead it only autocompletes functions and properties of a basic node.
![SOShelp](https://user-images.githubusercontent.com/66181369/229010295-ced1306f-9837-44b1-9ea3-149678691ef9.gif)

### Steps to reproduce

Make an auto-load script file, and a secondary file, attach the secondary file to a node and give it a class_name, and have the auto-load script get_node and instantiate it as the class_name you gave the secondary file, then try to reference the variable that stores the secondary file in the autoload script, it wont show any custom functions or properties.

### Minimal reproduction project

N/A

**Comment by Calinou** [comment] 2023-04-01 17:04
- Duplicate of https://github.com/godotengine/godot/issues/71296.

**Closed by Calinou** 2023-04-01 17:04 UTC
