### ISSUE TITLE
OmniLight: Shadow doesn't update when MeshInstance disappears

### ISSUE THREAD

**Issue by JupiterRider** [godotengine/godot#41539] opened 2020-08-26 12:10 UTC
**Godot version:**

Godot_v3.2.2-stable_mono_x11_64 
GLES2

**OS/device including version:**

Archlinux

**Issue description:**

![Peek 2020-08-26 14-05](https://user-images.githubusercontent.com/60042618/91301719-a9a4ee80-e7a5-11ea-9eda-8c2a27ba0a2f.gif)

**Steps to reproduce:**
- Add a MeshInstance
- Add a OmniLight
- Enable Shadow of the light
- Hide and/or show the MeshInstance

**Minimal reproduction project:**

**Comment by Calinou** [comment] 2020-08-26 12:35
Duplicate of https://github.com/godotengine/godot/issues/29856. As a workaround, move your light very slightly every frame in `_process()`.

**Closed** 2020-08-26 12:35 UTC
