### ISSUE TITLE
Exports with compiled GDScript produce parse errors when using global classes.

### ISSUE THREAD

**Issue by drwhut** [godotengine/godot#41378] opened 2020-08-19 18:09 UTC
**Godot version:**
3.2.3-rc3

**OS/device including version:**
Linux Mint 20

**Issue description:**
When using a global class (a class that has been defined with a `class_name`), it will work normally in the editor. However, in exports of the project where the GDScript isn't in plain text (e.g. compiled), the engine will produce a script error saying the class name identifier has not been declared in the current scope.

Here's an example output from the minimal project:
```
Godot Engine v3.2.3.rc3.official - https://godotengine.org
OpenGL ES 3.0 Renderer: GeForce RTX 2070 SUPER/PCIe/SSE2
 
SCRIPT ERROR: GDScript::load_byte_code: Parse Error: The identifier "HelloLabel" isn't declared in the current scope.
   At: res://Scene.gdc:5.
ERROR: load_byte_code: Method failed. Returning: ERR_PARSE_ERROR
   At: modules/gdscript/gdscript.cpp:801.
ERROR: load: Cannot load byte code from file 'res://Scene.gdc'.
   At: modules/gdscript/gdscript.cpp:2282.
ERROR: _load: Failed loading resource: res://Scene.gdc.
   At: core/io/resource_loader.cpp:278.
ERROR: poll: res://Scene.tscn:3 - Parse Error: [ext_resource] referenced nonexistent resource at: res://Scene.gd
   At: scene/resources/resource_format_text.cpp:440.
ERROR: load: Failed to load resource 'res://Scene.tscn'.
   At: core/io/resource_loader.cpp:208.
ERROR: _load: Failed loading resource: res://Scene.tscn.
   At: core/io/resource_loader.cpp:278.
ERROR: start: Failed loading scene: res://Scene.tscn
   At: main/main.cpp:1944.
WARNING: cleanup: ObjectDB instances leaked at exit (run with --verbose for details).
   At: core/object.cpp:2135.
ERROR: clear: Resources still in use at exit (run with --verbose for details).
   At: core/resource.cpp:477.
```

**Steps to reproduce:**
1. Create a project.
2. Create a GDScript with a custom class name.
3. Create another script that uses the previous class, e.g. it initializes it, and use it in the main scene.
4. Export the project with compiled GDScript.
5. Run the export.

**Minimal reproduction project:**
[MinimalProject.zip](https://github.com/godotengine/godot/files/5098426/MinimalProject.zip)

**Comment by Calinou** [comment] 2020-08-19 18:14
Duplicate of https://github.com/godotengine/godot/issues/40991.

**Closed by Calinou** 2020-08-19 18:14 UTC
