### ISSUE TITLE
Feature Request - restructuring assignment for dictionaries/arrays/tuples

### ISSUE THREAD

**Issue by greenbas** [godotengine/godot#27032] opened 2019-03-14 00:50 UTC
Reference: https://riptutorial.com/python/example/14981/destructuring-assignment

This is an incredibly useful tool when working with packed variables that have an expected form, where individual items within the pack can be referenced by an easily readable local variable. I think GDScripr should emulate this feature, it doesn't appear to be in the documentation

**Comment by greenbas** [comment] 2019-03-14 00:51
The title should be "destructuring assignment". Autocorrect decided to mess with me, I can't seem to change the title.

**Comment by williamd1k0** [comment] 2019-03-14 02:13
Duplicate of #7584

**Closed** 2019-03-14 08:46 UTC
