### ISSUE TITLE
(Is it bug or normal behaviour?) PoolIntArray.resize method does not work if array is owned an inner class or a separate class file

### ISSUE THREAD

**Issue by zantyru** [godotengine/godot#34267] opened 2019-12-11 13:16 UTC
**Godot version:**
v3.1.2.stable.official (64-bit)
v3.2.beta3.official (64-bit)

**OS/device including version:**
```
Distributor ID:	LinuxMint
Description:	Linux Mint 19.2 Tina
Release:	19.2
Codename:	tina

Linux 4.15.0-72-generic #81-Ubuntu SMP Tue Nov 26 12:20:02 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

**Issue description:**
The code like `inner_class_instance.pool_int_array_variable.resize(2)` does not worked as expected: the array size does not changing.

I has been know that `PoolIntArray` type is passed by value and not by reference, so this behaviour may be correct.

**Steps to reproduce:**
1. Create a scene with alone node `Node`.
2. Attach to the node this script:
```
extends Node


class Inner:
    var pool := PoolIntArray([1, 2, 3, 4, 5])
    func resize_by_method(n: int) -> void:
        pool.resize(n)


var pool := PoolIntArray([0, 9, 8, 7, 6])


func _ready() -> void:
    
    var inner := Inner.new()
    print("\nBEFORE")
    print("\tinner.pool = ", inner.pool)
    print("\tpool = ", pool)
    
    inner.pool.resize(2) # it is not worked as expected
    pool.resize(2)
    print("\nAFTER direct access (.resize(2))")
    print("\tinner.pool = ", inner.pool)
    print("\tpool = ", pool)
    
    inner.resize_by_method(10) # it is worked
    print("\nAFTER applying method")
    print("\tinner.pool = ", inner.pool)

```

**Minimal reproduction project:**
[TEST PoolIntArray resize.zip](https://github.com/godotengine/godot/files/3950467/TEST.PoolIntArray.resize.zip)
This is more complex example.

**Comment by vnen** [comment] 2019-12-11 16:01
This is a consequence of Pool Arrays being passed by reference, and the GDScript getter doesn't take this into account.

Closing as a duplicate of #8409

**Closed by vnen** 2019-12-11 16:01 UTC
