### ISSUE TITLE
The Shadow Quality Changes, When Using Different Viewport Sizes

### ISSUE THREAD

**Issue by RaTcHeT302** [godotengine/godot#34231] opened 2019-12-09 20:27 UTC
Godot 3.1.2
1. create a new project
2. add a 3d node scene (spatial or whatever it's called)
3. place a bunch of cubes down (a meshistance, then you select the node, and you should have an option here to select a basic shape https://i.imgur.com/Ajm1PLp.png)
4. add a DirectionalLight
5. resize the editor's viewport

![](https://i.imgur.com/zboYwRZ.png)
![](https://i.imgur.com/VbLBM5G.png)

big viewport (worse quality)
![wtf 2](https://user-images.githubusercontent.com/43797325/70470139-128eee00-1ad3-11ea-9d8e-a8554b7c5fc4.png)

small viewport (better quality)
![wat 1](https://user-images.githubusercontent.com/43797325/70470126-0a36b300-1ad3-11ea-9526-369c668c015a.png)

wtf

this is driving me insane and it makes testing the shadows impossible, this has to be fixed, i cannot ship a whole game with such a critical bug

:(

**Comment by clayjohn** [comment] 2019-12-09 20:34
Duplicate of https://github.com/godotengine/godot/issues/23603

Thank you for the report though :)

**Closed by clayjohn** 2019-12-09 20:34 UTC

**Comment by RaTcHeT302** [comment] 2019-12-09 21:03
its ok i didn't know what to search for anyway
