### ISSUE TITLE
4 beta, Editor Settings, Shortcuts tab, a misaligned border

### ISSUE THREAD

**Issue by duianto** [godotengine/godot#71213] opened 2023-01-11 11:16 UTC
### Godot version

v4.0.beta11.official [91713ced8]

### System information

Windows 10 22H2, Compatibility, GeForce GTX 550 Ti

### Issue description

There is a misaligned border on the `Editors Settings...`, `Shortcuts` tab.
When un/folding a shortcuts header.

https://user-images.githubusercontent.com/13420573/211791273-ee589c3d-ff2c-4dbb-9523-94a61f18388c.mp4

### Steps to reproduce

- start Godot
- create a new project
- from the top menu, open: `Editor > Editor Settings...`
- click on the tab: `Shortcuts`
- at the top right, click on: `Filter by event...`
- press: `Space`
- near the top left, click on the header name: `Common` to fold/hide the two shortcuts

### Expected
A misaligned border shouldn't appear in front of the header text: `Canvas Item Editor`

### Observed
A white border appears around the key bindings area.

But when the mouse pointer is held still for a second, then a tooltip appears: `Common`
Now the white border changes color to blue, and a second blue inner border appears.

The top of the inner border appears in front of the next header: `Canvas Item Editor`
and the right side of the border is slightly offset by a couple of pixels from the shortcut areas right side.

- click on the header `Common` to unfold/show the two shortcuts

Now, the inner border appears near the center of the shortcuts area,
and the inner borders', right side, is offset to the left more than before.

### Minimal reproduction project

N/A

**Comment by EricEzaM** [comment] 2023-01-11 13:27
Can't reproduce - looks like something is rendering incorrectly rather than a bug with the shortcuts editor itself.

**Comment by duianto** [comment] 2023-01-13 22:38
You are correct, it isn't limited to the shortcuts' editor.
It also happens in the `Edit Animation Libraries` window.
v4.0.beta12.official [3c9bf4bc2]

![Godot_v4 0-beta12_win64_tLnyI6YVjy](https://user-images.githubusercontent.com/13420573/212431657-4ed57487-627e-4f86-bb13-3c3e58436749.png)

**Comment by KoBeWi** [comment] 2023-02-03 23:51
Also can't reproduce, tested in beta 17.

**Comment by duianto** [comment] 2023-02-04 00:51
I'm still able to reproduce it in: v4.0.beta17.official [c40020513]

I found another place where it happens for me. In the `Node` panels, `Groups` section.

After clicking in the `Groups` section and moving the mouse to the viewport.
And then clicking in the `Groups` section again, now the "misaligned border" changes,
when one keeps left mouse button clicking, but nothing happens on one of the clicks.

And the "misaligned border" disappears and appears when,
the mouse pointer is moved over the panel divider (between the viewport and the `Node` panel),
and back to the `Groups` section.

https://user-images.githubusercontent.com/13420573/216735486-23763301-3728-4722-a71d-b40b67d5e328.mp4

Here's a project so that we are testing the same thing.
It was created using the `Compaitibility` renderer.
And it just contains a single node: `Node2D`
[issue, misaligned border.zip](https://github.com/godotengine/godot/files/10593514/issue.misaligned.border.zip)

It would be helpful if anyone that tests this lists their graphics card.
In case it only occurs on older cards. My card doesn't support vulkan: `GeForce GTX 550 Ti`

**Comment by KoBeWi** [comment] 2023-02-04 02:03
Ah I missed that you use compatibility renderer. I can reproduce with it too.

**Comment by git2013vb** [comment] 2023-02-21 06:41
I noticed it too in 
- Project->Project Settings->Input Map
- Project->Project Settings->Localization
- Project->Project Settings->Plugins

v4.0.rc2.official [d2699dc7a]
Debian 11
Compatibility mode

**Comment by duianto** [comment] 2023-06-29 08:26
[According to Calinou, the issue is caused by:](https://github.com/godotengine/godot/issues/74115#issuecomment-1487082149)
>This is not a rendering issue, but an issue with the GUI system. This is the IME (input method editor) having its focus outline visible at all times.

That comment is written in this issue:
Draw issue with focus in UI elements #74115

If an issue should have only one open thread, then either this or that thread should be closed as a duplicate.
If this thread is kept open, then the title could be updated, since the issue isn't limited to the editor settings, shortcuts tab.

### The issue is reproducible in:
Godot v4.1.rc1 - Windows 10.0.19045 - Vulkan (Compatibility) - GeForce GTX 550 Ti () - Intel(R) Core(TM) i3-2100 CPU @ 3.10GHz (4 Threads)

![Godot_v4 1-rc1_win64_EtVYaHj56K](https://github.com/godotengine/godot/assets/13420573/4df0e3e7-d481-4267-8753-9b00d3b106db)

**Comment by dalexeev** [comment] 2023-07-20 17:10
* Duplicate of #74115. Actually the opposite, but the other issue seems to have more cross-references, sorry. :slightly_smiling_face: I noted in a comment that there is a discussion here that might be useful.

**Closed by dalexeev** 2023-07-20 17:10 UTC
Labels: bug, topic:rendering, topic:editor, confirmed
