### ISSUE TITLE
REDUNDANT_AWAIT warning occurs despite the await having proper syntax.

### ISSUE THREAD

**Issue by Dan-Gamin** [godotengine/godot#59058] opened 2022-03-12 07:33 UTC
### Godot version

v4.0.alpha4.official [f47097973]

### System information

Windows 10 64-bit, GPU: NVIDIA Geforce GTX 1650 Ti, CPU: AMD Ryzen 7 4800H

### Issue description

REDUNDANT_AWAIT warning occurs despite the await having proper syntax.
 ```
W 0:00:02:0019   "await" keyword not needed in this case, because the expression isn't a coroutine nor a signal.
  <C++ Error>    REDUNDANT_AWAIT
  <Source>       scene_mgr.gd:21
```
Here's a look at my code:
```gdscript
	if transition:
		# Fade in the black
		_transition_plr.play("fade_in_anim")
		# Wait for the animation to finish
		## REDUNDANT_AWAIT
		await _transition_plr.animation_finished 
```
The `animation_finished` signal is a part of AnimationPlayer. But Godot doesn't recognize that. There is no autocomplete for the signal. Even though I used static typing for the `_transition_plr` declaration.
```gdscript
var _transition_plr: AnimationPlayer # This is set later.
````
That's what causes this issue. Godot doesn't recognize that the signal exists.. It's only a warning. But it's still annoying.

### Steps to reproduce

1. Make a new script
2. Put it in a Timer
3. Paste in the following code:
```gdscript
extends Timer

func _ready():
	self.wait_time = 5
	self.start()
	print("START")
	await self.timeout
	print("END")
```
4. Run the game, you should see the REDUNDANT_AWAIT warning. And of course, the code works as intended. (A part from the warning)

**Comment by Chaosus** [comment] 2022-03-12 08:12
Duplicate of https://github.com/godotengine/godot/issues/54589

**Closed by Chaosus** 2022-03-12 08:12 UTC
