### ISSUE TITLE
C# Signal connect does not work with variable number of parameters

### ISSUE THREAD

**Issue by powertomato** [godotengine/godot#32109] opened 2019-09-12 21:38 UTC
I'm trying to connect a signal to a method with a variable number of parameters. However this doesn't seem to work.

Here is the class I'm trying to connect to:
```c#
private class Handler: Object {
  public void Callback(params object[] a) {
...
  }
}
```

And how I connect to it (using a timer)
```c#
var array = new Array();
array.Add("hello");
timer.Connect("timeout", target, nameof(Handler.Callback),array);
```

**Expected result**
`Handler.Callback` gets called

**Actual result**
The method can't be found:
```
ERROR: emit_signal: Error calling method from signal 'timeout': 'Object::Callback': Method not found.
   At: core/object.cpp:1238
```

**Workaround**
Using overloads like:

```c#
 public void Callback(object a) {
...
 }

 public void Callback(object a, object b) {
...
 }
```

**System**
OS: Win10 X86_64
Godot-Version: 3.1.1
MSBuild-Version: 16.2.37902+b5aaefc9f
C# Compiler: 3.2.1-beta4-19408-03 (2fc6a049)

PS: On a side note I'm using "object"-types as I'm actually trying to wrap the signal with an awaitable Task so I can use them in asynchronous code and for that I need the code to be generic, in order to not repeat the same code for all the different numbers of arguments.

**Comment by neikeq** [comment] 2019-09-14 16:29
Duplicate of #29775

**Closed by neikeq** 2019-09-14 16:29 UTC
Labels: bug, topic:mono
