### ISSUE TITLE
Unexpected lines on GUI elements

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#10459] opened 2017-08-19 19:52 UTC
Godot 3.0 master
Windows 10 64 bits

Many UI elements have an unexpected line:

![image](https://user-images.githubusercontent.com/1311555/29489766-b234b4dc-8528-11e7-8b97-edfc08ca94c4.png)

![image](https://user-images.githubusercontent.com/1311555/29489778-f214583c-8528-11e7-996e-044eee9d7e43.png)

**Comment by toger5** [comment] 2017-08-20 01:16
definitely caused by the new style boxes...

I could not reproduce it myself yet. but I also didn't compile master in like 9 hours...
why do your background tabs look so different in the second screensho?

**Comment by toger5** [comment] 2017-08-20 01:18
#10461
this is referencing he same issue I think. So it might be caused but the combination of the new style boxes + the new poly anti aliasing.

**Comment by akien-mga** [comment] 2017-08-20 19:10
Marking as duplicate of #10461 which has more debugging info about the source of the problem.

**Closed by akien-mga** 2017-08-20 19:10 UTC
Labels: bug, topic:editor
