### ISSUE TITLE
FileDialog works differently in Editor and Compiled Versions

### ISSUE THREAD

**Issue by michaelpbl** [godotengine/godot#46299] opened 2021-02-21 20:39 UTC
Godot Version 3.2.1.Stable.Official

Windows 10, latest version

This is the FileDialog as edited in the Godot Editor. It's set to Mode is set to Open File, there is one filter *standings*, and the current Directory is set to res://saves. The FileDialog itself has been made visible in the editor and shows as I would expect with the Path: set to res://saves and the top file is selected and may be seen in the inspector under Current File
![FileDialogAsEdited](https://user-images.githubusercontent.com/63122053/108637058-82cd2980-7463-11eb-9220-6394fbfaa011.png)

Now here it is as running in my game. Again it looks just as expected. Path: is still set to res://saves. A standings file has already been selected and it's name transferred to the Last Standings File edit box.
![FileDialogRunInEditor](https://user-images.githubusercontent.com/63122053/108637286-a04ec300-7464-11eb-91a8-97bad0c5e782.png)

Now, after compiling the game, we get this instead. Path: has been reduced to just res:// Worse, the only folders shown are the standard Godot ones. res://saves is completely missing! As a result, there is no way to access any of my standings files.
![FileDialogRunCompiled](https://user-images.githubusercontent.com/63122053/108637424-22d78280-7465-11eb-9601-88d1fabb00f1.png)

Here's the code. The game itself and the file containing this particular piece of code are complex, but the code is simplicity itself. You can even see where I reset the Path: to just res:// in the inspector then tried to change to the saves director when the FileDialog pops up. That didn't work either. (BTW, the hide() and show() pieces were added because, contrary to expectations, the file dialog does not popup above sprites that I have with Z levels higher than 0. So the workaround is to disappear the world while the menu is up)
![FileDialogCode](https://user-images.githubusercontent.com/63122053/108637934-7054ef00-7467-11eb-92ae-720ffbdf0ce7.png)

**Minimal reproduction project:**

**Comment by Calinou** [comment] 2021-02-21 20:46
@michaelpbl Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

**Comment by michaelpbl** [comment] 2021-02-21 21:23
Here it is. I also just reproduced the behaviour on a Macbook Air M1
[FileDialog.zip](https://github.com/godotengine/godot/files/6018540/FileDialog.zip)

**Comment by bruvzg** [comment] 2021-02-21 21:41
This is expected behavior. In the exported project `res:\\` file system represents contents of the `PCK` file.
- It contains only imported resources, scenes, scripts e.t.c. Unknown file types (e.g. `.txt`) or source files of imported resources (e.g. `.png`) are not included by default. To include them you have to add filter under `Export -> Resources -> Filters to export non-resource files/folders`.
- It's read only filesystem and not suitable for "saves", there's `user://` filesystem for this.

**Comment by KoBeWi** [comment] 2021-02-21 22:02
Closing as per above comment.

**Closed by KoBeWi** 2021-02-21 22:02 UTC
Labels: needs testing, topic:gui

**Comment by michaelpbl** [comment] 2021-02-22 01:03
(a) It is NOT a read-only file system. I have been using it for saves for many weeks. The compiled version saves quite happily to the saves folder. I want it as part of the project as I'm saving files to use to automate testing of all the system code.
(b) If it is expected, it should behave the same way when running under editor control or after compilation. Also, if it is expected it should be documented as such.

**Comment by KoBeWi** [comment] 2021-02-22 01:08
> It is NOT a read-only file system. I have been using it for saves for many weeks. The compiled version saves quite happily to the saves folder.

You mean it saves inside pck file?

**Comment by michaelpbl** [comment] 2021-02-22 01:17
No. I mean it saves to the saves and testhands folders which are in the game folder and it finds the files and writes and reads to them using "res://saves" and "res://testhands" as the paths. I can also use the Directory class to read all the testhand files from the testhands folder and run them through my game one at a time and compare the result I get when they are run to the original result. I just can't reach out when running the game and pick a particular file (in this case to get the data from the previous game to use as a starting point for the current one).
![social_pokerInExplorer](https://user-images.githubusercontent.com/63122053/108645612-fd12a380-748d-11eb-9d1a-590543459fa2.png)

**Comment by KoBeWi** [comment] 2021-02-22 02:38
Then maybe change the `access` property to file system and set current directory to the game's executable directory? The files exported with game aren't meant to be modified, you have to keep them externally (i.e. outside pck file).

**Comment by bruvzg** [comment] 2021-02-22 06:24
> It is NOT a read-only file system. I have been using it for saves for many weeks. The compiled version saves quite happily to the saves folder. I want it as part of the project as I'm saving files to use to automate testing of all the system code.

It's using host filesystem (project root folder) as fallback, but it's not an intended way to use it, just a side effect of the editor using exactly the same engine.

https://docs.godotengine.org/en/stable/getting_started/step_by_step/filesystem.html#resource-path
https://docs.godotengine.org/en/stable/tutorials/io/data_paths.html

> I'll try using the user://filesystem for this though, even if it works, I doubt it will be portable in the sense that, were I to move the entire project folder, I suspect I will have to alter the code so it knows where the new location is.

It's not, on Windows it's pointing to `%APPDATA%/App_Name`.

To write to the project folder, you can use host fileystem (`access == ACCESS_FILESYSTEM`) and get path to the folder with `OS.get_executable_path().get_base_dir()`.

**Comment by michaelpbl** [comment] 2021-02-22 07:44
First of all, I want to give a huge thank-you to both of you for the time and effort you have put into answering this question. I find it truly extraordinary that people with such expertise can find the time to engage with users like me.

bruzvg: I will follow up on your suggestions. It might take a little time. My poker group meets once a week on Wednesdays, so I have to have whatever I'm working on ready to go by then. So Thursday through Sunday is my time to develop, Monday - Wednesday my time to consolidate.

Your first url is unequivocal: "This file system is read-write only when running the project locally from the editor. When exported **or** when running on different devices (such as phones or consoles, **or** running from DVD), the file system will become read-only and writing will no longer be permitted."

Unhappily, the proviso against writing **when exported** is not respected, which is how newcomers like me get led down the garden path. I would suggest that it be respected or (my preference) that FileDialog be allowed to look at all folders inside res: I don't mean that they should be included in the .pkg file, rather that FileDialog be allowed to see whatever is there on whatever system it is running on.

Your second url is also unequivocal. At the end of the day ,trying to get something like FileDialog working on five different operating systems is rather mind-boggling and I can only respect how well the Godot team has done. So, in my next cycle I will switch my attention to the user:// space.

Again, my thanks for all your help.

**Comment by michaelpbl** [comment] 2021-02-22 14:43
I know this has been closed, but in the interests of helping others with the same problem, I did as you suggested and now have a very viable solution.  In exploring how FileDialog worked I eventually created three separate FileDialog each with a different path. One of the big problems in trying to work with it is that the results are so different in editor-run vs compiled versions.  So here's the code, the print output (same in both versions) and a pair of snapshots for each one, the first under editor, the second compiled.

```
extends Control

onready var lastStandingsFileDialog1 = $LastStandings/FileDialog1
onready var lastStandingsFileDialog2 = $LastStandings/FileDialog2
onready var lastStandingsFileDialog3 = $LastStandings/FileDialog3
onready var lastStandingsFile = $LastStandings/StandingsFile

onready var path1
onready var path2
onready var path3

func _ready():
	path1 = OS.get_executable_path().get_base_dir()
	print(path1)
	path2 = path1 + "/FileDialog"
	print(path2)
	path2 = path1 + "\\FileDialog"
	print(path2)
	path3 = path1 + "\\FileDialog\\saves"
	print(path3)
	lastStandingsFileDialog1.set_current_path(path1)
	lastStandingsFileDialog2.set_current_path(path2)
	lastStandingsFileDialog3.set_current_path(path3)


func _on_OpenFileButton1_pressed():
	lastStandingsFileDialog1.popup()

func _on_OpenFileButton2_pressed():
	lastStandingsFileDialog2.popup()

func _on_OpenFileButton3_pressed():
	lastStandingsFileDialog3.popup()

```

func _on_FileDialog_file_selected(path):
	lastStandingsFile.text = path

And here's the output from the four print statements:

```
C:\Program Files\Godot
C:\Program Files\Godot/FileDialog
C:\Program Files\Godot\FileDialog
C:\Program Files\Godot\FileDialog\saves
```

1. Under editor control,  OS.get_executable_path().get_base_dir() displays the path to the godot engine folder. The compiled version displays the path to my Godot projects folder.
![path1Result](https://user-images.githubusercontent.com/63122053/108715537-93c67b00-74f5-11eb-9434-7c3e3ceb8f95.png)
![path1Compiled](https://user-images.githubusercontent.com/63122053/108721187-4bf72200-74fc-11eb-97f2-e4ffed674e75.png)

2. As the two versions of path2 in the code make clear, the string returned in code is in native windows mode. The FileDialog widget running under editor control ignores the FileDialog part of the path completely but does advance down inside the Godot folder simply contains the Godot engine executable. The compiled widget  goes inside the FileDialog project folder as expected.
![path2Result](https://user-images.githubusercontent.com/63122053/108715713-cb352780-74f5-11eb-9d5e-d8c0a920909b.png)
![path2Compiled](https://user-images.githubusercontent.com/63122053/108722741-0dfafd80-74fe-11eb-8f2d-8a183f15b548.png)


3. Somehow,  when adding the saves folder, the editor generated widget magically switches over and gives the identical result to the compiled widget.
![path3Result](https://user-images.githubusercontent.com/63122053/108715858-f7e93f00-74f5-11eb-8176-4d5ce8edb936.png)
![path3Compiled](https://user-images.githubusercontent.com/63122053/108721368-7fd24780-74fc-11eb-8cc3-0234a11c4d53.png)

So, thank-you, I have what I want, but it certainly seems FileDialog is a little quirky to say the least.
For anyone following in my footsteps, make sure you compile at every step. It would be nice if the two versions did the same thing but if you check OS.get_name() you'll see that it currently has to work with 9 different flavours of operating system.

Finally, I may have to add a match  on OS.get_name() to handle paths on the MAC

**Comment by Calinou** [comment] 2021-02-22 17:55
PS: When you a export project, Godot doesn't compile a binary. It copies precompiled export templates and packs a PCK file (with scripts and data) will be placed next to the binary.

**Comment by michaelpbl** [comment] 2021-02-23 11:08
Inasmuch as it's a scripting language, that makes sense, though I was not aware of the details. Good to know. Thanks. again.
