### ISSUE TITLE
GDScript 2.0: `@onready var` not initialized if inherited from base class

### ISSUE THREAD

**Issue by derammo** [godotengine/godot#63118] opened 2022-07-17 17:26 UTC
### Godot version

v4.0.alpha.custom_build [4173a4735]

### System information

Windows  10

### Issue description

@onready var from a base class is not initialized before _ready() is called in the descendant class

### Steps to reproduce

Extend Node to a named class
- declare an @onready var in this class

Extend this custom class in a script attached to the scene
- when _ready() is called, the base variable is not set

MRP below

### Minimal reproduction project

[onready_63118.zip](https://github.com/godotengine/godot/files/9128209/onready_63118.zip)

**Comment by derammo** [comment] 2022-07-17 17:28
This is a regression from 3.4 to 4.0.  I have included a project for 3.4 showing it working and one for 4.0 showing it failing.

**Comment by jtnicholl** [comment] 2022-07-17 17:49
> ### Godot version
> 
> [4173a47](https://github.com/godotengine/godot/commit/4173a4735eb1690132d30430f88fb7d2681c5727)

That version is nearly two months old, this was fixed in #62255, over three weeks ago. I can't reproduce this from your MRP on latest master.
Also, you seem to be confusing `RegEx.is_valid()` for `is_instance_valid()`. If `is_valid()` returns true on a brand new RegEx that sounds like a bug in 3.x.

**Comment by KoBeWi** [comment] 2022-07-17 22:11
Yeah this was fixed, update your build.

**Closed by KoBeWi** 2022-07-17 22:11 UTC
Labels: bug, topic:gdscript, regression

**Comment by derammo** [comment] 2022-07-18 00:10
@jtnicholl it returns false as intended on 3.4.  I was just calling a random method on an object to have it crash.

Sorry for wasting people's time.  I must have been in the wrong copy of the repo.
