### ISSUE TITLE
Single 97 KB texture loaded once results in 83 copies of the texture and 163 MB total memory usage in the debugger "Video RAM" tab

### ISSUE THREAD

**Issue by radishes** [godotengine/godot#77185] opened 2023-05-17 23:25 UTC
### Godot version

4.0.2

### System information

Windows 10

### Issue description

Loading a texture causes dozens of copies of the texture to appear in the Video RAM tab in the debugger. The total reported Video RAM usage of 163 MB is 1600x the size of the 97 KB texture file.

![image](https://github.com/godotengine/godot/assets/1106565/ccfef8c3-a685-4fbb-a794-4f5b4f1c5d8c)

Commenting out the `preload()` line in the repro project reduces the total Video RAM usage to 1.5 MB.

### Steps to reproduce

1. Load a png resource
2. Run project and look at Debugger > Video RAM

### Minimal reproduction project

[texture-video-ram-usage-repro.zip](https://github.com/godotengine/godot/files/11503045/texture-video-ram-usage-repro.zip)

**Comment by Calinou** [comment] 2023-05-17 23:45
- Duplicate of https://github.com/godotengine/godot/issues/76110 (this is fixed in 4.1.dev3 and 4.0.3.rc1).

**Closed by Calinou** 2023-05-17 23:45 UTC
