### ISSUE TITLE
Array issue

### ISSUE THREAD

**Issue by Setherino** [godotengine/godot#35771] opened 2020-01-31 07:27 UTC
**Godot version: 3.1.2 stable**

**OS/device including version:**
Windows 10, tested on both my desktop and laptop.

**Issue description:**
When creating multiple arrays with : Array, it treats them all as the same array when I append a value. For example, after running this code:

var test1 : Array
var test2 : Array
func _ready():
test1.append(value)

array **test2** will also contain the value appended to the **test1** array
I have a video [here](https://www.youtube.com/watch?v=d2hps5MW29g)

**Steps to reproduce:**
I was able to recreate this bug by:
1. Creating a project with an autoload script, with no scene attached
2. Creating two arrays and appending a value to them, like is shown above
**Minimal reproduction project:**
a .gd (with no scene attached) set to autoload & an empty scene.

**Note:**
I cannot get it to work on Ubuntu, so this may only be a windows issue. I don't have a mac, so I can't test it there.

**Comment by qarmin** [comment] 2020-01-31 07:36
Duplicate of #24134 and fixed in 3.2.
You should always initialize variables at the beginning
```
var test1 : Array = []
var test2 : Array = []
func _ready():
    test1.append(value)
```

**Closed by qarmin** 2020-01-31 07:36 UTC
