### ISSUE TITLE
Fail to Initialize at Launch

### ISSUE THREAD

**Issue by 9BitStrider** [godotengine/godot#26883] opened 2019-03-10 20:30 UTC
**Godot version:**
3.1 RC-1 Win32

**OS/device including version:**
OS: Windows 7 Professional
CPU: Intel Core i5-2320 32 Bit
GPU: Intel HD Graphics 9.17.10.4229

**Issue description:**
Godot will not load. I receive an error: 
Unable to Initialize Video Driver
Your video card driver does not support any of the supported OpenGL versions.
Please update your drivers or if you have an old or integrated GPU upgrade it.

**Steps to reproduce:**
Start app.

![image](https://user-images.githubusercontent.com/23580375/54091063-5f2d7900-4349-11e9-8b9b-53a831e0b56e.png)

**Minimal reproduction project:**

**Comment by qarmin** [comment] 2019-03-10 20:54
You need to wait for Godot 3.1 RC 2 because it is fixed in master

**Comment by 9BitStrider** [comment] 2019-03-10 20:55
Okay. Thank you.

**Comment by akien-mga** [comment] 2019-03-10 22:01
Duplicate of #26806.

**Closed by akien-mga** 2019-03-10 22:01 UTC
