### ISSUE TITLE
c# scripts cannot be deleted - compilation error (HTML5)

### ISSUE THREAD

**Issue by hheimerd** [godotengine/godot#53212] opened 2021-09-29 13:15 UTC
### Godot version

3.3.3 stable

### System information

Windows 10, GLES2

### Issue description

After removing C# script exporting was broken. In *.csproj no reference to this script, in scene no reference, I foud one in scripts_metadata.editor_player, but in is not repeat in new project. Problem probably related to Rider, when i remove .idea fron the project something changed, but the project still doesn't build for HTML.
Something like "ERROR: Unable to start HTTP server. At: platform/javascript/export/export.cpp:699"

### Steps to reproduce

create a node
add a script to it
delete the script from the file system
delete the script from the object
run it in the BROWSER mode

### Minimal reproduction project

[Platformer.zip](https://github.com/godotengine/godot/files/7252062/Platformer.zip)
![image](https://user-images.githubusercontent.com/38163258/135274324-c2018262-5ea1-4c78-b519-9f84d8ba77b9.png)

**Comment by raulsntos** [comment] 2022-01-13 18:54
Seems to be a duplicate of #56758, this one is older but as the other one seems to be a bit more detailed I'll close this one.

As a workaround, if you don't have any C# scripts in your project deleting the `.csproj` and `.sln` files should make exporting work.

**Closed by raulsntos** 2022-01-13 18:54 UTC
Labels: bug, platform:html5, topic:porting, topic:mono
