### ISSUE TITLE
Asset library in-editor fails to load

### ISSUE THREAD

**Issue by EricEzaM** [godotengine/godot#39913] opened 2020-06-28 09:01 UTC
**Godot version:**
3.2.2 stable

**OS/device including version:**
WIN 10

**Issue description:**
Asset Library does not load any assets, error below is printed to console.
` editor/plugins/asset_library_editor_plugin.cpp:1212 - Condition "!category_map.has(r["category_id"])" is true.
`

**Steps to reproduce:**
Open asset library and attempt to refresh.

**Comment by Calinou** [comment] 2020-09-29 10:20
Duplicate of https://github.com/godotengine/godot/issues/30642.

**Closed by Calinou** 2020-09-29 10:20 UTC
Labels: bug, topic:assetlib, topic:editor
