### ISSUE TITLE
Yield causes different Internal Script Errors when Syncing Scene Changes

### ISSUE THREAD

**Issue by DleanJeans** [godotengine/godot#30193] opened 2019-06-29 17:48 UTC
**Godot version:** 3.1

**OS/device including version:** Windows 10

**Issue description:**

I use this code to display a simple FPS label without using a `Timer`:

```
func _ready():
	_update_fps()

func _update_fps():
	while true:
		$Label.text = 'FPS: %s' % Engine.get_frames_per_second()
		yield(get_tree().create_timer(1), 'timeout')
```

Doesn't happen all the time but frequent enough.

Some opcodes encountered: `#0 #1 #3  #5 #21 #22 #30`
Occasionally, socket errors and Project List window when run.
```
 drivers/unix/net_socket_posix.cpp:190 - Socket error: 10054
```

This is funny: as I was zipping the min repro project, I decided to delete the `default_env.tres` and it stopped happenning anymore. So there must be something to do with the `WorldEnvironment`.
(which might explain why that script used to work fine in my 2D projects until I work on a 3D one).

**Steps to reproduce:**
Change anything in the editor while running the game and save it (add new nodes, change the scirpt, change properties in the Inspector...).

**Steps to _unreproduce_:**
Remove `Rendering > Environment > Default Environment` in the `Project Settings`.

**Minimal reproduction project:**

[YieldOpcode.zip](https://github.com/godotengine/godot/files/3342148/YieldOpcode.zip)

**Comment by Calinou** [comment] 2020-03-12 08:36
Duplicate of #24684.

**Closed by Calinou** 2020-03-12 08:36 UTC
Labels: bug, topic:core, topic:editor
