### ISSUE TITLE
PopupMenu - Items list and button disappears after selecting AtlasTexture as icon

### ISSUE THREAD

**Issue by finalwarp** [godotengine/godot#45039] opened 2021-01-09 03:58 UTC
**Godot version:** 3.2.3

**OS/device including version:**

**Issue description:**

After adding an Item in the Items List Editor and selecting "AtlasTexture" as an icon, all the items in the editor disappear and I can no longer open the window after closing it. I had to modify the scene in a text editor to fix it. This doesn't happen with the other textures in the list

**Steps to reproduce:**
![popupmenu](https://user-images.githubusercontent.com/49965612/104082514-c7c73480-5204-11eb-80fd-70e4776aa4ef.gif)

**Minimal reproduction project:** I hope the gif is enough

**Comment by KoBeWi** [comment] 2021-01-09 12:40
Duplicate of #28211

**Closed by KoBeWi** 2021-01-09 12:40 UTC
Labels: bug, confirmed, topic:editor
