### ISSUE TITLE
Godot 4: Navigation Agent causes continuous increase in physics_process() miliseconds at runtime

### ISSUE THREAD

**Issue by macryc** [godotengine/godot#60068] opened 2022-04-09 15:29 UTC
### Godot version

4.0 alpha 6

### System information

Win10, GLES3, RTX 2070 mobile

### Issue description

When using NavigationAgent3d with NavigationRegion3d, physics tick gradually consumes more and more time.
After about 20 mins of the game running, FPS drops to 1 and the the game crashes.

### Steps to reproduce

Open the minimum repro project below. 
Run the game and let it run for 5 mins.
Look at the Monitor and notice how physics_process() milliseconds nearly tripled by 5 mins versus the 1st minute, even though nothing is changing in the scene.
There is no cap to this either. If you let the game run for 10 mins, physics milliseconds would increase 6fold. 
And so on until you have 1 FPS...

### Minimal reproduction project

[4 navi bug.zip](https://github.com/godotengine/godot/files/8457237/4.navi.bug.zip)

**Comment by Zireael07** [comment] 2022-04-09 16:20
Did you do a search before posting a new issue? It's literally in top 5 if you search for "navigation agent"

Dupe of #56838

**Comment by Calinou** [comment] 2022-04-09 16:27
Duplicate of #56838.

**Closed by Calinou** 2022-04-09 16:27 UTC
Labels: bug, archived, topic:navigation, performance
