### ISSUE TITLE
Can't drag and drop nodes where i want into Scene tree editor.

### ISSUE THREAD

**Issue by SuperUserNameMan** [godotengine/godot#5924] opened 2016-07-26 19:23 UTC
**Operating system or device - Godot version:**
2.1rc1 official, win64

**Issue description** (what happened, and what was expected):

Look at the two screenshot below.
It is not possible to drag and drog the "NODE" node at these places :
- between A and B ( NODE will end up into A after Y or before X depending wether A is expanded or not )
- after B ( NODE will end up into B after or before Z depending wether B is expanded or not)

indeed, here, the workaround is to drap and drog A before NODE, or to drop NODE over Root.

But it is strange and unexpected behavior, more even since the red line takes two different length when you drag NODE between Y and B on the first screenshot. 

**Steps to reproduce:**

**Link to minimal example project** (optional but very welcome):
![dragndrop_00](https://cloud.githubusercontent.com/assets/9801802/17151984/21debf16-5376-11e6-95d2-50cadf76b36e.png)
![dragndrop_01](https://cloud.githubusercontent.com/assets/9801802/17151985/23fb1092-5376-11e6-8292-61a5111a17ee.png)

**Comment by bojidar-bg** [comment] 2016-07-27 09:09
Can confirm.

**Comment by agameraaron** [comment] 2016-08-01 06:00
Confirmed on my end.

To me the expected behavior is that if you're going to drop it on top of the node you want it to be a child. If you drop it between it means you want it to be a sibling to the nodes, but I cannot get it to do so even when the line appears equal to their scope.

**Comment by reduz** [comment] 2016-08-02 22:05
I checked how Unity does this, and it's the exact same thing. 
If you want to drop a node between A and B, just fold A

**Comment by agameraaron** [comment] 2016-08-03 04:15
I think I've identified my problem is that the line extends out when a child node is being dragged next to a node in the scope above (parent or otherwise). The problem is that it does the same thing as when it's not extended. It would seem the line should not do this as it confuses the end user into thinking they will have different results, as if they can make it a sibling to the parent.

**Comment by volzhs** [comment] 2017-02-12 21:11
Tested with 2.1.2 official release.

I can move `Node` to between `A` and `B` while `A` is expanded or not.
I can't move `Node` to below `B` (as sibling) while `B` is expanded.
But can position it by dropping to `Root` or folding `B`

**Comment by bojidar-bg** [comment] 2017-02-13 13:39
I think this might have been fixed in 2.2, as I haven't observed it there lately (_but I'm probably wrong_)

**Comment by agameraaron** [comment] 2017-02-19 21:35
This all seems to work for me as expected since 2.1.2!

**Comment by akien-mga** [comment] 2017-08-08 11:42
Closing as fixed then. Feel free to comment if it's still valid in the master branch.

**Closed by akien-mga** 2017-08-08 11:42 UTC
Labels: bug, confirmed, topic:editor, usability
