### ISSUE TITLE
Godot.Collections Dictionary results in existing keys but null values for C# object

### ISSUE THREAD

**Issue by marcel-b-roodt** [godotengine/godot#73728] opened 2023-02-22 02:52 UTC
### Godot version

3.5.1 stable mono official

### System information

Windows 10, Intel i7 7700HQ, GTX1070 Mobile

### Issue description

I am getting a simple bug which appears to be the difference between the Dictionary in `Godot.Collections` and the Dictionary in `System.Collections.Generic`.

I think there is an issue where the value of a C# wrapper object is possibly being cleaned up.
I have added objects which hold a Godot `AudioStream` reference to a Dictionary.
The key exists in the Dictionary but fetching the values results in `null` values all the time.

I have written down my example in the `Steps to reproduce` section.

### Steps to reproduce

1. When setting up a Godot.Dictionary like this:
```
public const string MySound = "res://Resources/Sounds/mySound.wav";

private static Dictionary<string, AudioStream> resources = new Dictionary<string, AudioStream>
{
		{ nameof(MySound), ResourceLoader.Load<AudioStream>(MySound)},
}
```
2. Fetching the value works.
```
MyAudioStream.Stream = resources[nameof(MySound)] //All good
```

However, when setting up the Dictionary like this:
```
public const string MySound = "res://Resources/Sounds/mySound.wav";

private static Dictionary<string, SoundFile> resources = new Dictionary<string, SoundFile>
{
		{ nameof(MySound), new SoundFile(MySound)},
}
```
4. Using a C# object as a wrapper:
```
public class SoundFile
{
	public AudioStream Stream { get; private set; }

	private SoundFile(string pathToAudioFile)
	{
		Stream = ResourceLoader.Load<AudioStream>(pathToAudioFile); //The value is not null when checking here
	}
}
```
5. The call does not work. The key exists but the result is null:
```
MyAudioStream.Stream = resources[nameof(MySound)] //No good. Object reference error
```

### Minimal reproduction project

[TestGodotDictionary.zip](https://github.com/godotengine/godot/files/10800747/TestGodotDictionary.zip)

**Comment by raulsntos** [comment] 2023-02-22 04:37
Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

But note that `Godot.Collections` only support types compatible with [`Variant`](https://docs.godotengine.org/en/stable/classes/class_variant.html). To know which types are supported you can take a look at the [`Variant.Type`](https://docs.godotengine.org/en/stable/classes/class_%40globalscope.html#enum-globalscope-variant-type) enum.

Given the definition of `SoundFile` that you've shared, it shouldn't be possible to store it in a `Dictionary<string, AudioStream>` since `SoundFile` does not inherit from `AudioStream`.

**Comment by marcel-b-roodt** [comment] 2023-02-22 06:22
My apologies. I'll see if I can quickly make a reproduction project.

Regarding `Godot.Collections` itself, I see. I didn't know about the requirement on objects being a `Variant` type. However, `AudioStream` isn't one either and it worked just fine, so I was wondering why.

>Given the definition of SoundFile that you've shared, it shouldn't be possible to store it in a Dictionary<string, AudioStream> since SoundFile does not inherit from AudioStream.

This was a mistake in my `steps to reproduce`. I corrected it. The Dictionary that produced errors was `Dictionary<string, SoundFile>`. The only difference in this was that the `AudioStream` was now inside another object.

**Comment by marcel-b-roodt** [comment] 2023-02-22 06:43
In my reproducible project `TestGodotDictionary.zip`, there is a `GoodSoundStore` and a `BadSoundStore`.
In `World.cs`, you can switch between which SoundStore is used to trigger the crash.

**Comment by raulsntos** [comment] 2023-02-22 13:58
>  I didn't know about the requirement on objects being a `Variant` type. However, `AudioStream` isn't one either and it worked just fine, so I was wondering why.

A type that is compatible with `Variant` means one of the types mentioned in the [`Variant.Type`](https://docs.godotengine.org/en/stable/classes/class_%40globalscope.html#enum-globalscope-variant-type), so for example `int`, `float`, `Vector2` are all compatible. But also `Godot.Object` or any derived type. In the case of `AudioStream`, the inheritance goes like this: `AudioStream` < `Godot.Resource` < `Godot.Reference` < `Godot.Object` so it's compatible.

If you want `SoundFile` to work it needs to inherit from `Godot.Object`, usually I think users would use `Godot.Resource` in this situation.

```csharp
using Godot;

public class SoundFile : Resource
{
	public AudioStream Stream { get; private set; }

	public SoundFile(string pathToAudioFile)
	{
		Stream = ResourceLoader.Load<AudioStream>(pathToAudioFile);
	}
}
```

Also, note that when using `BadSoundStore` you get errors in the debugger:

![image](https://user-images.githubusercontent.com/3903059/220639559-cb2d9107-c76e-4d18-bef3-0a85b0b646a3.png)

The error `Attempted to convert an unmarshallable managed type to Variant` means that, in order to send the C# type (in this case `SoundFile`) to Godot (which only supports Variants), it needs to be marshalled but the type is not supported.

In 4.0, unsupported types in these scenarios are reported when building the project so you know something is wrong before even running the game.

Since this is expected behavior and not a bug, I'll be closing this issue. 
In case of any doubts please reach for help in the [Community channels](https://godotengine.org/community) (like Q&A / Discord / Reddit etc.).

**Closed by raulsntos** 2023-02-22 13:58 UTC
