### ISSUE TITLE
Can't select first character on wrapped lines in TextEdit

### ISSUE THREAD

**Issue by lostminds** [godotengine/godot#96071] opened 2024-08-25 15:10 UTC
### Tested versions

Reproducible in 4.3.stable

### System information

macOS 14.6.1

### Issue description

If a TextEdit line is long enough to wrap to the next line you can't select the first character on that new line. Doesn't seem to be specific to wrapping mode, but of course in needs to wrap. This affects TextEdits in the Editor (like the output log, or editing field for Label RichText etc) and TextEdits in run projects. 

### Steps to reproduce

The easiest way to see it is just to print out a long enough print log, like `print("Here's a really long comment text that can wrap to multiple lines if the comment areas is small enough")` and resize the window so the word wraps. Or just enter a long text in a RichText text field. Observe that you cant select the first character on wrapped lines.

https://github.com/user-attachments/assets/52925ab4-77e2-40f3-9feb-889975949941

### Minimal reproduction project (MRP)

You can reproduce it in the editor, not project specific.

**Comment by AThousandShips** [comment] 2024-08-25 15:17
Duplicate of (the log is a `RichTextLabel`, not a `TextEdit`):
* https://github.com/godotengine/godot/issues/95297

Should have been fixed by:
* https://github.com/godotengine/godot/pull/95301

**Closed by AThousandShips** 2024-08-25 15:17 UTC
