### ISSUE TITLE
Bottom panel's editor plugin's not getting keyboard signals

### ISSUE THREAD

**Issue by MarianoGnu** [godotengine/godot#3419] opened 2016-01-23 13:24 UTC
Also the same for actions and joybuttons i guess.
I identified the problem but wans't able to solve this: CanvasItemEdiorPlugin and SpatialEditorPlugin are catching the key events and accepting before they reach bottom panel, this is the cause:

The parenting goes like this:
    _center_split
    __top_split
    ___container
    ____scene_tabs
    _____scene_root_parent(Panel)
    _____scene_root_base (Control aparently not in use, duplicate of viewport above)
    _____scene_root (parent of the current edited scene, input is disabled)
    _____viewport (it's a Control, not a viewport)<b>
    ______canvas_item_editor_plugin
    ______spatial_editor_plugin
    ______script_editor_plugin</b>
    ___top_split_other_childs (some editors are aded here like shader editors)
    __bottom_panel
    ___v_container<b>
    ____editors (animation, sprite_frames, sample_library, and many others not catching signals)</b>
    ____h_container
    _____buttons_to_switch_editors

somehow some editors like shader editors are catching the input, but not sprite_frames or sample_library.

**Comment by reduz** [comment] 2016-01-23 13:46
are you sure it's not because they are simply focused? they get focused
when you mouse over them

**Comment by MarianoGnu** [comment] 2016-01-24 04:09
Yes, get get focus when I click them (stylebox focused) but lose focus when a key is pressed, canvas item editor grabs the focus

**Comment by reduz** [comment] 2016-02-01 12:23
works fine for me, remember that canvas and spatial editor steal the focus when you mouseover them

**Comment by reduz** [comment] 2016-02-01 12:24
maybe you moved the mouse there without realizing?

**Comment by reduz** [comment] 2016-02-01 13:34
well, can't reproduce so closing

**Closed by reduz** 2016-02-01 13:34 UTC
Labels: bug, topic:editor, usability
