### ISSUE TITLE
Editor freeze (not responding) after pressing tab few times on the transform/scale 

### ISSUE THREAD

**Issue by starkdesk** [godotengine/godot#34817] opened 2020-01-04 12:04 UTC
**Godot version:**
3.2.beta4
**OS/device including version:**
windows10 64bit 
**Issue description:**
Editor freeze (not responding) when we press tab a few times on transform/scale node (I am not sure about the other nodes) value not update however scale of body changes in the editor. We need to deselect and select that node again value is correctly updated.
**Steps to reproduce:**
create any sprite node and try to increase and decrease size using tab a few times. 
**Minimal reproduction project:**

**Comment by iamrahul404** [comment] 2020-01-19 06:02
I checked in Godot 3.2.rc1 this only happens in Sprite nodes only.

**Comment by tom-jk** [comment] 2020-07-18 16:18
@iamrahul404 can you reproduce this? could you make a video showing it happening? I am unable to reproduce this in godot 3.2.2.stable and I'm not sure I understand the exact problem you are having.

**Comment by mcandries** [comment] 2021-07-16 16:42
hello,
i often have the same issue with Godot 3.3.2 stable on sprite node.
When setting a scale value with keyboard for example, and press TAB, the entire Godot application freeze for somes seconds.
After that the value i entered is buggy (i can't change it anymore)

**Comment by Calinou** [comment] 2021-07-16 19:51
> hello,
> i often have the same issue with Godot 3.3.2 stable on sprite node.
> When setting a scale value with keyboard for example, and press TAB, the entire Godot application freeze for somes seconds.
> After that the value i entered is buggy (i can't change it anymore)

This sounds similar to https://github.com/godotengine/godot/issues/47757.

**Comment by Zylann** [comment] 2021-10-04 20:21
Had this happen on my own voxel terrain plugin which I built off c62399557a71b31f27f230a679b0e2133704ffa7, by tabbing through the transform's `scale` property. It also errored that message queue was full, so it's not just Sprite

**Comment by MagdielM** [comment] 2021-10-13 16:40
> Had this happen on my own voxel terrain plugin which I built off [c623995](https://github.com/godotengine/godot/commit/c62399557a71b31f27f230a679b0e2133704ffa7), by tabbing through the transform's `scale` property. It also errored that message queue was full, so it's not just Sprite. Setting each field individually by clicking on them does not have this problem.

Can confirm, have also had this happen when tabbing through a transform's `scale` property, with the console printing
```
ERROR: Message queue out of memory. Try increasing 'memory/limits/message_queue/max_size_kb' in project settings.
   At: core/message_queue.cpp:55
Failed method: ToolButton:_update_minimum_size target ID: 8700
TOTAL BYTES: 4194288
NULL count: 0
CALL : 174757
CALL _update_callback: 2
CALL show_modal: 1
CALL grab_focus: 1
CALL select_all: 1
```
where `Failed method` may vary between several different methods.

**Closed** 2021-10-15 10:42 UTC
Labels: bug, topic:editor, confirmed, topic:3d
