### ISSUE TITLE
Beta 6 area optimization causes significant collision behavior changes

### ISSUE THREAD

**Issue by cart** [godotengine/godot#26169] opened 2019-02-22 20:24 UTC
This is mainly just an additional datapoint because I know the area optimization commit (b1934cfd0db97646d044b3c3b7c9d1f9d6aa1d07) was reverted, but I don't see any mention of this particular issue.

With the area optimization:
* Players (kinematic bodies) started falling through platforms (move_and_slide against kinematic bodies)
* Area-on-area collision appears to not be registering. I use a "foot area" area (child of the player kinematic body) to detect if a player is "on" a platform by colliding with a "platform area".

Master (which reverts the commit) returns the behavior back to "normal"

I haven't investigated this too much, but I wanted to make it known asap that there are regressions in case the intent is to "fix" the area optimization performance issues and re-add it.

OS:
Arch Linux

Godot Version:
Beta 6

**Comment by substract** [comment] 2019-02-22 20:40
Hello
I can confirm issues with the collision shapes. My collision shapes with on_body_entered signals don't fire.

**Comment by cart** [comment] 2019-02-22 20:46
I (personally) would also consider patching beta 6 or releasing a beta 7 because this will probably break a lot of people.

**Comment by Ace-Dragon** [comment] 2019-02-22 22:35
I reported it yesterday and the commit responsible got reverted.
https://github.com/godotengine/godot/issues/26149#issuecomment-466371683

I'm using daily builds from Calinou's site, so I can stick with a golden build as long as needed if I find one.

**Comment by cart** [comment] 2019-02-22 22:47
Yeah I build from source so I'm not worried about me. I _am_ worried about the thousands(?) of people that will download a broken build.

**Comment by Dogpot** [comment] 2019-02-23 04:13
Can confirm on beta6 x64 build. Area-on-area collisions seem to be completely broken, it's bad enough I have to revert back to beta5.

**Comment by akien-mga** [comment] 2019-02-23 11:11
Duplicate of #26149.

**Closed by akien-mga** 2019-02-23 11:11 UTC
