### ISSUE TITLE
Grandchildren Scenes don't inherit scripts

### ISSUE THREAD

**Issue by RCastroAB** [godotengine/godot#56584] opened 2022-01-07 07:52 UTC
### Godot version

3.4stable

### System information

Ubuntu 20.04

### Issue description

When creating long chains of inherited scenes in Godot, the information of the script attached is lost for grandchildren and beyond.

### Steps to reproduce

Create a scene A, then create an inherited scene B from A. After that create an inherited scene C from B. Now attach a script to A. B will have the script attached but C will not.

Edit: All scenes must be open in the editor.

### Minimal reproduction project

[InheritanceBug.zip](https://github.com/godotengine/godot/files/7827351/InheritanceBug.zip)

**Comment by kleonc** [comment] 2022-01-07 14:01
> ### Steps to reproduce
> 
> Create a scene A, then create an inherited scene B from A. After that create an inherited scene C from B. Now attach a script to A. B will have the script attached but C will not.

Can't reproduce (W7, both in `3.4.2.stable` and `3.4.stable`). C inherts the script just fine.


> ### Minimal reproduction project
> 
> [InheritanceBug.zip](https://github.com/godotengine/godot/files/7827351/InheritanceBug.zip)

For some unknown reason in `Node2D3.tscn` the `script` is overridden to `null`:
```
[gd_scene load_steps=2 format=2]

[ext_resource path="res://Node2D2.tscn" type="PackedScene" id=1]

[node name="Node2D" instance=ExtResource( 1 )]
script = null
```
Such override haven't appear (automatically from nowhere) when I've tried to recreate the issue.

**Comment by RCastroAB** [comment] 2022-01-08 02:31
Thank you for your reply! 

How strange, I just checked and it's generating that line into the file upon running the C scene. Before that, the file is generated as one would expect, and if the line is deleted the script will be attached correctly, but will not update if the script is detached on the parent. I created a new project, this time without running C, so the line shouldn't be there.

[Inheritance Bug.zip](https://github.com/godotengine/godot/files/7832435/Inheritance.Bug.zip)

I also got this confusing error message somewhere along the way.
```
 scene/main/node.cpp:1560 - Condition "!common_parent" is true. Returned: NodePath()
 Cannot get path of node as it is not in a scene tree.
 (Node not found: "" (relative to "").)
 editor/editor_data.cpp:1033 - Condition "!p_node->is_inside_tree()" is true.
```


I have also had a  seemingly unrelated issue with child scenes only updating their inherited scripts if the parent scene is loaded in the editor, but I'm unsure whether I to make another issue.

**Comment by kleonc** [comment] 2022-01-08 14:18
> How strange, I just checked and it's generating that line into the file upon running the C scene. Before that, the file is generated as one would expect, and if the line is deleted the script will be attached correctly, but will not update if the script is detached on the parent. I created a new project, this time without running C, so the line shouldn't be there.
> 
> [Inheritance Bug.zip](https://github.com/godotengine/godot/files/7832435/Inheritance.Bug.zip)

I think I must have been closing the scenes after creating them, and the issue is happening only if that grandchild (inheritance-wise) scene is open in the editor. I've edited my previous comment.

Also it seems to happen for any property, it's not script-specific behavior. Try changing `position` or `pause_mode` in A (when B and C are open as well), then running A, and you'll see the changes being reflected in B but not in C.

> I also got this confusing error message somewhere along the way.
> 
> ```
>  scene/main/node.cpp:1560 - Condition "!common_parent" is true. Returned: NodePath()
>  Cannot get path of node as it is not in a scene tree.
>  (Node not found: "" (relative to "").)
>  editor/editor_data.cpp:1033 - Condition "!p_node->is_inside_tree()" is true.
> ```

I'm not getting any errors so it may be unrelated to this issue. Not sure what could be the cause.

>I have also had a seemingly unrelated issue with child scenes only updating their inherited scripts if the parent scene is loaded in the editor, but I'm unsure whether I to make another issue.

Kinda related, kinda not, hard to tell. [There are many issues for "inherited scene" reported](https://github.com/godotengine/godot/issues?q=is%3Aissue+is%3Aopen+inherited+scene), you can check them out.

Actually just looked briefly at few of these issues and seems like this issue is a duplicate of #55964.

**Comment by RCastroAB** [comment] 2022-01-09 09:17
Nice to know I wasn't the only one. Should I close this issue, since it's a duplicate, or should I wait until the bugs are fixed?

**Comment by Calinou** [comment] 2022-09-01 16:42
Duplicate of https://github.com/godotengine/godot/issues/7984.

**Closed by Calinou** 2022-09-01 16:42 UTC
Labels: bug, topic:core, needs testing
