### ISSUE TITLE
Detect 3D does not affect embedded `.glb` textures, meaning they will not have mipmaps generated or VRAM compression used (regression in 4.0.alpha10)

### ISSUE THREAD

**Issue by plafer** [godotengine/godot#62295] opened 2022-06-22 01:59 UTC
___

***Bugsquad note:** This issue has been confirmed several times already. No need to confirm it further.*

___

### Godot version

4.0.alpha-10

### System information

Ubuntu 20.04, x64, Nvidia GeForce GTX 1050 Ti, driver version 470.129.06, Vulkan backend

### Issue description

[This PBR texture](https://freepbr.com/materials/forest-floor1/) looks "grainy" when made in Blender, and exported to a `.glb` file. The same texture looks just fine when loaded directly on a mesh in Godot, or when imported from a Collada file.

In the attached video, the plane on the left is a `.glb` import, while the one on the left was loaded directly in Godot.

https://user-images.githubusercontent.com/5769562/174925370-0de99b7e-8f16-4d71-ad20-a8ccc373069f.mp4

### Steps to reproduce

1. Download [this PBR texture](https://freepbr.com/materials/forest-floor1/)
2. In Blender 3.1.*, create a plane, and add the PBR material to the plane
3. Export the scene to a `.glb` file (glTF 2.0 format)
4. Import into Godot by drag and dropping into your `res://` folder
5. Add the imported scene to the World, and observe the grainyness.
6. You can also create a new `MeshInstance3D`, add the material (albedo only is necessary), and observe the lack of grainyness.

### Minimal reproduction project

Contains only the grainy texture, due to Github upload file size limits.

[grainy.zip](https://github.com/godotengine/godot/files/8953830/grainy.zip)

**Comment by fire** [comment] 2022-06-22 04:41
The mipmaps are off so there's too much detail and causing a sharpness pattern.

**Comment by Calinou** [comment] 2022-06-22 05:49
Material has its sampling mode correctly: 
![image](https://user-images.githubusercontent.com/180032/174953043-4808efd7-2450-4773-9601-b327c176dae5.png)


However, this does not suffice to have working mipmaps. The texture must have mipmaps enabled in its import options, and this isn't done automatically for embedded textures within a `.glb` file. I assume the whole Detect 3D process should be able to detect and reimport those textures, or even always import embedded textures from `.glb` as if they were used in 3D.

**Comment by plafer** [comment] 2022-06-22 23:23
Not sure if that goes without saying, but I observe the same behavior with `.gltf` files (exporting as "glTF Embedded" in Blender).

**Comment by Calinou** [comment] 2022-06-24 21:08
This was confirmed by @jcostello to be a regression in 4.0.alpha10. 4.0.alpha9 does not have this problem.

**Comment by WickedInsignia** [comment] 2022-07-02 07:57
Just tested myself in 4.0 alpha 9: imported GLTF embedded textures still won't use mipmapping. On Windows 10 GTX1080.
Doesn't seem to be resolved in alpha 11.

**Comment by novemberist** [comment] 2023-02-24 02:02
On a side note: Since there already is a separate option for handling embedded images from gltf-files in the Advanced Import Settings, should "Extract Materials" really embed the texture files inside the material resource again, when you have already selected "Extract Textures"? I think those settings should be synched in a way to avoid duplication and confusion.

**Comment by lyuma** [comment] 2023-04-04 04:21
As of Godot 4.0, by default textures are extracted from .glb models using the project's default texture import settings. This should enable mipmaps as well as VRAM compression (via Detect 3D).

I would like to close this issue as solved. Does that make sense?

@novemberist The problem you hit is a separate bug, as you noted, so we can discuss it there.

**Comment by akien-mga** [comment] 2023-06-22 14:48
Closing based on the above comment.

**Closed by akien-mga** 2023-06-22 14:48 UTC
Labels: bug, confirmed, topic:import, regression, topic:3d
