### ISSUE TITLE
Callables used for RPCs cannot be binded

### ISSUE THREAD

**Issue by TheYellowArchitect** [godotengine/godot#80614] opened 2023-08-14 12:22 UTC
### Godot version

4.1 Stable

### System information

Linux

### Issue description

When a practical scenario requires Callables, that's just excellent, as so much code is cutoff, and so, its easier to maintain.
In my use-case, I had 4 RPC functions which take identical parameters in the exact same order, though ofc they do something else inside. Only 1 of these functions has 1 more parameter, and so I thought I can just bind it. But from what I've tried, that's impossible.

I made a MRP, so it's crystal clear:
![rpc_unable_to_be_bound](https://github.com/godotengine/godot/assets/25630803/5ec82c79-52a1-45e0-9c07-bc1b93131cea)
![nonexistentrpc](https://github.com/godotengine/godot/assets/25630803/bfe459e2-d118-49b3-8fed-39582c3bd207)

Note that `.call()` works perfectly, it's just the `.rpc()` that's problematic.

Ultimately, it turns out that the Callable returned from `.bind() `"forgot" the rpc it had.

### Steps to reproduce

1. Create server/client connection code
2. Create an RPC function with 2 arguments.
3. Create a callable function which is the above RPC function, then bind 1 argument to it.
4. Try to RPC the above callable function

### Minimal reproduction project

[bind_rpc_mrp.zip](https://github.com/godotengine/godot/files/12334523/bind_rpc_mrp.zip)

**Comment by AThousandShips** [comment] 2023-08-14 12:23
Duplicate of #78545

**Closed by AThousandShips** 2023-08-14 12:23 UTC
