### ISSUE TITLE
[WASAPI] Buzzing and distorted low-pitched audio with mono headset

### ISSUE THREAD

**Issue by tcoxon** [godotengine/godot#76504] opened 2023-04-27 11:59 UTC
### Godot version

3.5.1.stable

### System information

Windows, NVIDIA GeForce RTX 2070, AMD Ryzen 5 3400G, 16GB RAM, Headset Earphone (Arctis 7 Chat) 

### Issue description

A Cassette Beasts player reported that all the music and sound effects are low-pitch and accompanied by a buzzing noise. In their log was this:

```
WARNING: WASAPI: Unsupported number of channels: 1
   at: AudioDriverWASAPI::init_render_device (drivers\wasapi\audio_driver_wasapi.cpp:328) - WASAPI: Unsupported number of channels: 1
```

The issue only seems to affect the user's "Arctis 7 Chat" earphones. Switching to a different device resolved the issue.

The user captured an example of the distorted audio here:
https://www.youtube.com/watch?v=34YBpimGIBk

### Steps to reproduce

Not known. Probably:

1. Obtain "Arctis 7 Chat" earphones
2. Try to play audio through the WASAPI driver

### Minimal reproduction project

N/A

**Comment by akien-mga** [comment] 2023-04-27 12:05
The WASAPI driver doesn't seem to implement mono audio indeed. This might just be an oversight.

Relevant code (in `master`, but it's likely similar in `3.x` and `3.5`):

https://github.com/godotengine/godot/blob/352ebe97259622f20b47627b4bf747cdfc79304d/drivers/wasapi/audio_driver_wasapi.cpp#L482-L494

Likewise for macOS's coreaudio driver:

https://github.com/godotengine/godot/blob/352ebe97259622f20b47627b4bf747cdfc79304d/drivers/coreaudio/audio_driver_coreaudio.cpp#L105-L117

While pulseaudio handles mono and other odd channel counts, apparently by just adding + 1:

https://github.com/godotengine/godot/blob/352ebe97259622f20b47627b4bf747cdfc79304d/drivers/pulseaudio/audio_driver_pulseaudio.cpp#L203-L223

**Comment by akien-mga** [comment] 2023-04-27 12:16
CC @EIREXE who has been doing some work on the WASAPI driver in the past.

@tcoxon I'm not too familiar with audio setup on Windows, but it might be possible for you to configure things to run as if your audio device was mono, and thus reproduce (and possibly fix) the issue.

**Comment by KoBeWi** [comment] 2023-04-27 12:50
Duplicate of #25875
Looking at the bottom of that issue, there are multiple reports linking it too.

**Comment by EIREXE** [comment] 2023-04-27 20:08
> CC @EIREXE who has been doing some work on the WASAPI driver in the past.
> 
> @tcoxon I'm not too familiar with audio setup on Windows, but it might be possible for you to configure things to run as if your audio device was mono, and thus reproduce (and possibly fix) the issue - when you get some time after handling the post-release priorities ;)

I don't use godot's built-in audio engine anymore, I switched to miniaudio and I would like to suggest godot to do the same in my opinion

**Comment by Calinou** [comment] 2023-04-27 20:41
- Duplicate of https://github.com/godotengine/godot/issues/25875.

**Closed by Calinou** 2023-04-27 20:41 UTC
Labels: bug, platform:windows, topic:audio
