### ISSUE TITLE
Godot 4.1.1 - Close all tabs (scenes opened in editor) causes crash

### ISSUE THREAD

**Issue by LeandroHPerez** [godotengine/godot#82273] opened 2023-09-24 22:40 UTC
### Godot version

v4.1.1.stable.official [bd6af8e0e] - (without .net) - MacOs version

### System information

Macbook Apple M2 Pro - MacOs  Ventura 13.6

### Issue description

"Right click" in scenes tab and choose "Close all tabs"  causes crash when running Godot 4.1.1 in an MacBook with Apple Silicon

### Steps to reproduce

1 - Open  project with many opened Scenes
2- "Right click" in scenes tab area and choose "Close all tabs" 
3- Now you can see an "immediate crash"

Expected: new tab for new clear scene

Notes: 
- tested in MacOS version of Godot
- Added evidence video file

### Minimal reproduction project

Note: zip with ".godot" because that bug only happened in this version.

[Tappy Plane - bug Close All Tabs.zip](https://github.com/godotengine/godot/files/12709804/Tappy.Plane.-.bug.Close.All.Tabs.zip)

**Comment by YuriSizov** [comment] 2023-09-25 13:49
Thanks for your report. Duplicate of https://github.com/godotengine/godot/issues/79943. Already fixed in 4.2 and 4.1.2.

**Closed by YuriSizov** 2023-09-25 13:49 UTC
