### ISSUE TITLE
Label line spacing can become "corrupted"

### ISSUE THREAD

**Issue by nezvers** [godotengine/godot#77438] opened 2023-05-24 13:15 UTC
### Godot version

4.0.3

### System information

Windows 10, Forward+, Nvidia GTX1060

### Issue description

Label line spacing can become "corrupted". In our project, everything seemed OK running from the editor but in the release build multi-line text had a big line spacing and even setting explicit line spacing to 0 didn't help.
When I created the test project everything worked correctly and then I tried a saved scene from our project, that label didn't work correctly in the release build.
I created a reproduction project with a fresh Label and matched configuration and text. In the `main.tscn` scene file text, there is no difference, yet the corrupted one break in the release build.
Maybe related to #74351 

PS. Converting "Corrupted" Label into RichTextLabel keeps the corrupted state.

### Steps to reproduce

In the reproduction project saved corrupted_label_scene.tscn that contains the label.
Copy that label into a new scene.
Build a release and the label line spacing is not working correctly.

### Minimal reproduction project

[Label Release Line Spacing.zip](https://github.com/godotengine/godot/files/11554969/Label.Release.Line.Spacing.zip)

**Comment by Calinou** [comment] 2023-05-24 14:14
- Duplicate of https://github.com/godotengine/godot/issues/74351 (same cause).

**Closed by Calinou** 2023-05-24 14:14 UTC
