### ISSUE TITLE
Deleting a C# script in Godot does not remove it from the .csproj

### ISSUE THREAD

**Issue by CoreChg** [godotengine/godot#32157] opened 2019-09-15 21:51 UTC
3.1.1-mono (stable)

Windows 10 Home
Version: 1903
OS Build: 18362.356

After I have deleted a C# script from the file system pane, the file is gone from the system, but the build crashes because it is not removed from the .csproj file.
Godot gives the error "Source file [file path] can not be found"

1. Create a C# script and attach it to a node.
2. Delete the script and then clear it from the node

The file below was the .csproj file after deleting the script "PlayerController.cs" from the FileSystem view. Notice at line 56 where it tells C# to compile the file anyway.

[GravTest.csproj](https://github.com/godotengine/godot/files/3614319/GravTest.csproj.txt)

**Comment by KoBeWi** [comment] 2019-09-15 22:38
Related: #12917

**Comment by CoreChg** [comment] 2019-09-16 01:17
Ah, well if people are all ready on it, should I simply close the topic? Sorry to be a bother.

**Comment by KoBeWi** [comment] 2019-09-16 03:54
It's not exactly the same, so you could leave this one if you want. The fix will probably close both anyways.

**Comment by akien-mga** [comment] 2020-03-18 08:55
Duplicate of #12917.

**Closed by akien-mga** 2020-03-18 08:55 UTC
Labels: bug, topic:mono
