### ISSUE TITLE
Using own name in class file is not allowed

### ISSUE THREAD

**Issue by Remixful** [godotengine/godot#53346] opened 2021-10-03 05:30 UTC
### Godot version

3.3.4 stable

### System information

Windows 10

### Issue description

I have a class. This class has a **static** function that returns a new instance of itself (it's like an alternate constructor).
I am getting the error "Using own name in class file is not allowed" though. I am not sure how this would create problems with this being called from a static function. Obviously, the workaround is to make another class that specifically builds an instance of this class, but just wanted to let this be known.

### Steps to reproduce

Create class, name it whatever
Create a static function that returns whatever.new(), get an error

**Comment by Calinou** [comment] 2021-10-03 14:57
Duplicate of https://github.com/godotengine/godot/issues/27491 (fixed in `master`).

**Closed by Calinou** 2021-10-03 14:57 UTC
