### ISSUE TITLE
UWP fails Windows Store App Certification

### ISSUE THREAD

**Issue by nunodonato** [godotengine/godot#9213] opened 2017-06-16 14:01 UTC
**Operating system or device - Godot version:** UWP, Godot 2.2

**Issue description:**
After packaging my app for windows store (using Visual Studio because I'm still not able to do it from Godot export), I ran the windows store app certification program. Everything seems to work except for this one API call:

![apifail](https://user-images.githubusercontent.com/1642015/27229736-a5e3cfd0-52a4-11e7-8a39-93cb97638208.PNG)

**Comment by vnen** [comment] 2017-06-16 14:11
I was able to pass the Cert Kit. I wonder if something changed.

**Comment by nunodonato** [comment] 2017-06-16 14:26
@vnen did you try with 2.2 or 2.1?

**Comment by vnen** [comment] 2017-06-16 14:33
Both, actually. Maybe it's something on the game?

**Comment by nunodonato** [comment] 2017-06-16 14:46
I tried now with a simple demo, it fails in the same way.

**Comment by nunodonato** [comment] 2017-06-16 14:47
in case it matters:
target platform: 10.0.10240.0

**Comment by vnen** [comment] 2017-06-16 18:08
It passes for me with 2.2. 
![chrome_2017-06-16_15-06-48](https://user-images.githubusercontent.com/5599796/27239030-ab2e154e-52a5-11e7-8f41-39e8ce384a29.png)

**Comment by nunodonato** [comment] 2017-06-16 18:31
Strange... It fails with both on my side :/

**Comment by punto-** [comment] 2017-06-16 21:46
Are you using any extra modules? That function sounds like it's
thread-related, I remember using the STL stuff for the threads originally,
that should be standard..

**Comment by nunodonato** [comment] 2017-06-16 22:06
@punto- no, like I said, I tried a simple demo project and it also failed

**Comment by akien-mga** [comment] 2017-06-16 22:37
Could be either a difference in your ANGLE versions, or in the way you export to UWP?

**Comment by nunodonato** [comment] 2017-06-18 20:14
tried now with my own ANGLE build, still failed :(

**Comment by nunodonato** [comment] 2017-06-24 11:59
Can we expect to have official export templates for WinRT in the next 2.1.4? In that case there's no need to worry as the official one will pass certification... I guess... unless the problem is not in the godot executable, but should be, right?

**Comment by nunodonato** [comment] 2017-06-27 18:51
tried now with the beta 2.1.4 templates, still fail validation on my side. Does it pass with you  @vnen ?

**Comment by vnen** [comment] 2017-06-27 20:48
@nunodonato I got a pass here with a simple project. I'll try later with your project. Note that I'm using the debug exports because the release still don't run (haven't figured out the solution yet).

**Comment by vnen** [comment] 2017-07-12 02:31
Oh, I'm really stupid. This is caused by libpng use of `ExitProcess()` and I added a workaround to it but mistakenly put it under the x86 conditional. It was passing for me because I was building for x86, but now that I tested with x64 I got the same result.

**Comment by vnen** [comment] 2017-07-12 04:36
Fixed in master (f55fff3) and 2.1 (55a3e07).

**Closed by vnen** 2017-07-12 04:36 UTC
Labels: bug, platform:uwp, topic:core
