### ISSUE TITLE
Ability to start multiple game clients when we press "run" (F5)

### ISSUE THREAD

**Issue by elieobeid7** [godotengine/godot#30780] opened 2019-07-23 19:06 UTC
I'm developing a multiplayer game, each time I write new code and want to test it for both players (clients), I have to export the project, and the editor built-in player would be the second player. I do that so many times per day.

If when we press we have an option to create multiple clients at once, that be awesome for developing and debugging multiplayer games fast

**Comment by akien-mga** [comment] 2019-07-23 19:43
Duplicate of #7008 (and to some extent #20020).

**Closed by akien-mga** 2019-07-23 19:43 UTC
