### ISSUE TITLE
Project/Editor Settings contents displayed weirdly depending on the scroll position (regression from #32959)

### ISSUE THREAD

**Issue by YeldhamDev** [godotengine/godot#36087] opened 2020-02-10 21:07 UTC
**Godot version:**
78074fe

**Issue description:**
Depending on the position of scroll, the contents of both Project and Editor Settings dialogs display weirdly. This doesn't happen in 3.2:
![Screenshot_20200210_174114](https://user-images.githubusercontent.com/30739239/74189852-0fd28580-4c49-11ea-8628-a802ace7785b.png)

**Comment by akien-mga** [comment] 2020-02-11 09:34
Confirmed, I've seen that today too.

**Comment by akien-mga** [comment] 2020-02-11 10:26
Bisected, that's a regression from #32959 (@georgwacker @groud).
However I don't get the bug in dfb7d46a2aaf9bef2c7dd067e699e70291062fb6 itself (the original commit of the PR, pre-3.2), so it seems to be the merge which triggers the bug due to an intermediate change.

**Comment by georgwacker** [comment] 2020-02-11 15:15
> Depending on the position of scroll

What does position of scroll mean exactly, do you have to do something to trigger the glitch?

I don't see this bug in my build of 3e3f8a476, if I just open the project settings for example and scroll in one of the view containers. I also tested this with a fresh Godot profile in Windows.

**Comment by akien-mga** [comment] 2020-02-22 11:06
> What does position of scroll mean exactly, do you have to do something to trigger the glitch?

Reduce the size of the Editor Settings dialog to have a long enough scrollable section, and scroll down. At some specific scroll values (likely non-integer ones), the bug is triggered.

**Comment by akien-mga** [comment] 2020-02-26 16:10
Also seems to affect game controls. I think we'd better revert for now (including the cherry pick in 3.2.1 RC 1).

**Comment by georgwacker** [comment] 2020-02-26 18:41
I had a hard time reproducing this bug on my machine, I took another look with master and finally saw a similar one pixel line cutoff, but nothing like the above. 

It seems we need another solution for control node animation after all.

Looking at the code again, it seems like the control nodes currently rely on the `xform[2].round()` that gets called by scrolling and thus calling `NOTIFICATION_DRAW`. This must mean that without the rounding, all the control nodes in the editor somehow have non-integer transforms? 
The workaround isn't that old, I wonder which other change made this rounding necessary.

Anyways, until a better solution is found, the old workaround should be restored. Sorry for the regression.

**Comment by georgwacker** [comment] 2020-02-26 19:29
![image](https://user-images.githubusercontent.com/13589801/75379433-a9e72e80-58d5-11ea-95d3-b7bf2bfaa3c2.png)

This is the output of control node positions in the project settings after scrolling and before the rounding. They have integer positions when drawing initially and have fractions after scrolling.

**Comment by georgwacker** [comment] 2020-02-27 11:32
I tracked this down to ScrollContainer, where `scroll` is directly used for the `Rect2D` to reposition the children.
https://github.com/godotengine/godot/blob/e437bcbccf0df046a67685e840e9c2d98a6e3c03/scene/gui/scroll_container.cpp#L302

Now the question is if we just round the x/y components of `scroll` before using it as a position for child nodes OR round the scrolling data in gui_input?
https://github.com/godotengine/godot/blob/e437bcbccf0df046a67685e840e9c2d98a6e3c03/scene/gui/scroll_container.cpp#L90

**Comment by bojidar-bg** [comment] 2020-02-27 12:06
I would suggest rounding the scroll, since the input event value is divided by 8 and multiplied by some OS-defined factor at https://github.com/godotengine/godot/blob/e437bcbccf0df046a67685e840e9c2d98a6e3c03/scene/gui/scroll_container.cpp#L104

**Comment by georgwacker** [comment] 2020-02-27 12:39
Your answer could be interpreted both ways :-)

I guess you mean to round all the calculations in gui_input, including the one you linked on Line 104? Since in the context of the ScrollContainer, all control nodes should be spaced with integer numbers, always?

**Comment by akien-mga** [comment] 2020-03-02 15:36
Reverted the cherry-pick from the `3.2` branch for now until we find a fix for the regression. I did not revert from the `master` branch though so we can still experience and fix the bug there first.

**Comment by akien-mga** [comment] 2021-01-06 14:42
I'm not sure if this is still reproducible, I couldn't see the issue in Project Settings anymore in a recent `master` build.

There's now a similar issue in popup menus (e.g. Scene menu), but it might be a different cause, as it doesn't seem to be caused by #32959 unlike what was debugged here back in March.

**Comment by georgwacker** [comment] 2021-01-06 14:55
I’ll take a look at the original jitter problem and the fix I have for the ScrollContainer. As mentioned above it seems to be a rounding issue.

**Comment by georgwacker** [comment] 2021-02-02 12:12
In master the workaround in scene/gui/control.cpp is removed and  https://github.com/godotengine/godot/blob/ae6b2d6edc76de347ccb11c4608b6e8174e1884f/scene/gui/scroll_container.cpp#L321 flooring the position fixes the regression when scrolling. 

I tested these two changes on the 3.2 branch and they work as expected. As of my original findings, the position based on the scroll value should always be an integer.

**Comment by georgwacker** [comment] 2021-03-03 11:14
This is fixed with #46409

**Closed** 2021-03-03 12:36 UTC
Labels: bug, confirmed, regression, topic:editor, topic:gui
