### ISSUE TITLE
NavigationRegion2d Drawing polygons in editor is bugged - cant subtract or sometimes edit shapes

### ISSUE THREAD

**Issue by OddlifeDev** [godotengine/godot#72761] opened 2023-02-05 15:22 UTC
### Godot version

4.0 Beta 16 & 17

### System information

Mac os X 11.6.7

### Issue description

I can create a polygon in NavigationRegion2d - and sometimes it will let me subtract another polygon from it. 

However sometimes i will not let me do that - and it actually stops updating the polygon as i move other points around. I tried in beta 16 & 17 - 17 started crashing on me and then 16 could not open the .tscn for that stage anymore - so i reverted to 16.

Same issue persists though. - See attached gif of issue.

![2023-02-05 15-01-31](https://user-images.githubusercontent.com/119736831/216828040-daa773e9-ced3-47ef-92e5-85fbe9ec83bc.gif)

### Steps to reproduce

create a NavigationRegion2D and add a polygon. Click the add polygon button and try subtract some more. (sometimes it works sometimes not) when its not working try modify some of the points and it will not update.

### Minimal reproduction project

[navregion_polygon.zip](https://github.com/godotengine/godot/files/10611375/navregion_polygon.zip)

**Comment by OddlifeDev** [comment] 2023-02-05 15:23
Also its very awkward dragging points, sometimes it seems to create new points instead of dragging the point you are 'clicking on'

**Comment by alex-shch** [comment] 2023-02-05 16:12
The same troubles on beta 17
Code with `add_outline` from the issue https://github.com/godotengine/godot/issues/36555 doesn't working

**Comment by alex-shch** [comment] 2023-02-05 17:18
and can be linked to https://github.com/godotengine/godot/issues/41447

**Comment by smix8** [comment] 2023-02-05 19:49
I experience myself regular input bugs with "current" Godot 4 00302860541e9cccc59abd93b930af2a6e6ec360 with all the Editor Plugins that inherite the AbstractPolygon2DEditorPlugin to draw polygons e.g. Polygon2D, CollisionPolygon2D and NavigationRegion2D.

Like duplicated vertices and also not switching properly when selecting another node of the same type still editing the old resource, or if you clear it on the new node, clearing the old node as well. So this is not a navigation specific issue.

**Comment by akien-mga** [comment] 2023-02-05 20:09
CC @KoBeWi

**Comment by KoBeWi** [comment] 2023-02-06 12:22
Can't reproduce the issue in beta 17.
The points in MRP are duplicated 4 times, but when I add points, it always adds 1.

https://user-images.githubusercontent.com/2223172/216970266-654eafa8-2f52-4d33-a233-a9fdbe6e661e.mp4

**Comment by OddlifeDev** [comment] 2023-02-06 22:04
@KoBeWi - I was not talking about the duplicated verts - Looks like from your video that you replicated exactly my issue. The nav polygon is not subtracting the polygons drawn inside and its also not updating as you move points around.

**Comment by OddlifeDev** [comment] 2023-02-06 22:15
Here is a gif of Godot 4.0 Beta 14 - you can see the correct behaviour - which is not reflected in the above video.

![2023-02-06 22-08-42](https://user-images.githubusercontent.com/119736831/217099671-001a7bc9-7a2d-4264-ae04-0d34d9f44e76.gif)

**Comment by KoBeWi** [comment] 2023-02-06 22:22
Then I guess https://github.com/godotengine/godot/issues/72761#issuecomment-1418248997 is unrelated to this issue. Looks like NavigationPolygon2D bug to me.

**Comment by smix8** [comment] 2023-02-07 17:27
@KoBeWi Can't speak for OP but my issues are gone with your last fixes.

**Comment by akien-mga** [comment] 2023-02-07 17:44
Great, assuming fixed by #72796.

**Closed by akien-mga** 2023-02-07 17:44 UTC
Labels: bug, topic:editor, topic:navigation

**Comment by alex-shch** [comment] 2023-02-09 16:10
RC 1 - it works

**Comment by heyitsdoodler** [comment] 2023-12-13 04:24
I'm experiencing this issue once again in Godot 4.2, though it seems to be somewhat arbitrary

<img width="368" alt="Screenshot 2023-12-12 at 11 22 43 PM" src="https://github.com/godotengine/godot/assets/20733898/125d0d69-283a-4f12-bdde-629a3e558338">

You can see that one of them works entirely as expected, these are all on the same NavigationRegion2D
