### ISSUE TITLE
resolve_class_interface: tried to assign unset node without an identifier. & is_type_compatible: Trying to check compatibility of unset value type

### ISSUE THREAD

**Issue by OgGhostJelly** [godotengine/godot#68478] opened 2022-11-10 14:05 UTC
### Godot version

4.0.beta4

### System information

GLES2, linux, thinkpad t430

### Issue description

the code produces these errors:
```
E 0:00:00:0451   resolve_class_interface: Parser bug (please report): tried to assign unset node without an identifier.
  <C++ Source>   modules/gdscript/gdscript_analyzer.cpp:668 @ resolve_class_interface()
```
```
E 0:00:00:0451   is_type_compatible: Parser bug (please report): Trying to check compatibility of unset value type
  <C++ Error>    Condition "!p_source.is_set()" is true. Returning: true
  <C++ Source>   modules/gdscript/gdscript_analyzer.cpp:4098 @ is_type_compatible()
```

### Steps to reproduce

run this code:

```
extends Node


@onready var node: Node = create_node()


func create_node():
	return Node.new()
```

### Minimal reproduction project

[test.zip](https://github.com/godotengine/godot/files/9981388/test.zip)

**Comment by clayjohn** [comment] 2022-11-17 07:37
Duplicate of #58542

**Closed by clayjohn** 2022-11-17 07:37 UTC
