### ISSUE TITLE
[HTML5] ENOENT occured in texture when import compress settings is set to Video RAM and Vram texture compression is set to false

### ISSUE THREAD

**Issue by mrdev023** [godotengine/godot#43169] opened 2020-10-28 22:24 UTC
**Godot version:**
3.2.3

**OS/device including version:**
Windows 2004 / Fedora 32-33
HTML5 Export

**Issue description:**
When i export without vram texture compression and import compress settings to Video RAM.
It can't load file (error ENOENT file_access_unix.cpp#123).

When the settings is uncheck, i'll try to read file uc2jcdgg_8K_AO.jpg-b2b31e35d7cf3a06c518a90cf7d977e8.s3tc.stex but a ENOENT Error is occured (but it exists in .import folder)

The problem is with default option, the mobile option is disabled and the pc option is enabled so when i export the game to HTML5. In pc, it work perfectly but in mobile it doesn't work.

**Steps to reproduce:**
- Create project
- Add texture
- Set import settings to Video RAM
- Set HTML 5 Export Vram Texture Compression option to false
- Export to HTML5 and run

**Minimal reproduction project:**
[test.zip](https://github.com/godotengine/godot/files/5455096/test.zip)

**Comment by lawnjelly** [comment] 2020-10-29 11:00
Related to #32255 . I think Akien is doing a fix for this.

**Comment by mrdev023** [comment] 2020-11-03 16:30
> Related to #32255 . I think Akien is doing a fix for this.

Ok thx

**Comment by akien-mga** [comment] 2020-12-11 11:27
This is actually not a bug but a misunderstanding.

The "Video RAM" Compress option **means** VRAM compressed (VRAM = Video RAM), so if you disable all VRAM compression formats (whether in the Project Settings for import, or in the HTML5 preset for export), then you're effectively asking Godot to import your textures as VRAM compressed, but with no VRAM compressed format configured and none exported. So you end up without textures in your PCK.

**Closed by akien-mga** 2020-12-11 11:27 UTC
Labels: bug, platform:html5, topic:editor
