### ISSUE TITLE
Undo keyboard shortcuts do not work reliably in 3D/2D scene or inspector

### ISSUE THREAD

**Issue by elvisish** [godotengine/godot#54274] opened 2021-10-26 17:16 UTC
### Godot version

3.3.3 stable

### System information

Windows 7 64-bit

### Issue description

When attempting to undo or redo with keyboard shortcuts, Godot almost never works correctly in 3D scene or for inspector changes. It works fine in script or 2D, but breaks most of the time in 3D or when changing inspector values. Scene > Undo and Scene > Redo are for the most part fine, but shortcut keys break, until Scene > Undo or Scene > Redo is used, at which point it may work for a while.

### Steps to reproduce

Create a spatial
Move it a few times
Undo/Redo keys will not work
Press Scene > Undo to get Undo/Redo keys working again
When you undo until past the point of creating the spatial, redo will break again
Press Scene > Redo to get Undo/Redo keys working again

### Minimal reproduction project

I have tried and tried to create a minimal reproduction but it always starts working as soon as I delete a bunch of files, which leads me to believe it has something to do with certain content in a Godot project folder. Once I deleted a vast amount of files, Undo started working but redo still didn't work. It's completely unpredictable and I have no idea where to start diagnosing this issue, other than sending my entire game project to someone privately for analysis.

**Comment by elvisish** [comment] 2021-10-30 18:49
Whoever's an expert with Godot's Undo/Redo, let me know and I'd be happy to share privately my project that has the problem. I've tried cutting it back but it just seems to make Undo/Redo work better the more files I remove. It's definitely broken and is causing me to lose a lot of work trying to diagnose the problem, which I can't do by myself unfortunately.

**Comment by elvisish** [comment] 2021-10-31 19:31
Modifying this as my shortcut keys are broken in 2d mode too, on a reasonably fresh project when I just dragged a sprite into the scene. Undo/Redo menu works fine, shortcut keys totally broken.

**Comment by Calinou** [comment] 2022-01-20 22:50
I've been able to reproduce this a handful of times on both `3.x` 322ba882b and `master` c13319db8.

Could you try to record a video while you're using the editor until this issue occurs, then edit the video to keep only the last 1-2 minutes and upload it here?

**Comment by elvisish** [comment] 2022-04-11 14:45
I think part of the issue is which part of the dock windows are selected, clicking the background of the Scene tab or Inspector tab for instance  seems to switch between the undo stacks which is... completely unorthodox.

**Comment by Calinou** [comment] 2022-04-11 15:49
https://github.com/godotengine/godot/pull/59564 will likely fix this in 4.0, but it's unlikely to be backported to 3.x since it relies on compatibility-breaking UndoRedo changes.

**Comment by elvisish** [comment] 2022-12-09 15:08
Undo is still exactly as broken in 4.0 as in 3.x.

**Comment by Braveo** [comment] 2022-12-25 22:47
I'm still currently having this issue in Godot 4. Godot 3.5 has been much more forgiving with this issue as undoing and redoing has been for the most part consistent, but Godot 4 fails to undo and redo pretty much all the time when I use it, unless reload saved scene for some reason.

**Comment by adrianmg** [comment] 2023-01-07 09:44
I'm having the same issue in Godot `3.5.1`


https://user-images.githubusercontent.com/589285/211144317-8f967b7d-0b2e-4597-9692-e840724ef85d.mp4

**Comment by reduz** [comment] 2023-01-13 18:30
This should be in part fixed by #71328.
@adrianmg your video does not show a bug. Some controls have their own undo/redo stack (like code editor and line edit) that override the global undo/redo (which is now also per scene), so this is expected.
I feel in general this issue needs more information in order to have something actionable, else at this point it should probably be closed.

**Comment by elvisish** [comment] 2023-01-13 18:46
> This should be in part fixed by #71328. @adrianmg your video does not show a bug. Some controls have their own undo/redo stack (like code editor and line edit) that override the global undo/redo (which is now also per scene), so this is expected. I feel in general this issue needs more information in order to have something actionable, else at this point it should probably be closed.

Consistently in 3.x3, 3.4, 3.5 and 4.0 I've found that undo-ing is pretty flawless in the code editor (thank goodness) but requires manually clicking the File > Undo or File > Redo button to, I guess, activate the direction(?) of "do". For example, if you place some objects in the scene and press CTRL+Z, nothing might happen until you press File > Undo, then CTRL+Z will work continuously until you click in the scene editor. However, during Undo-ing with CTRL+Z, you might decide to Redo which won't work until File > Redo is clicked, then CTRL+Z will work every time until clicking somewhere else.

I've just gotten used to this way of working, it's very unpleasant but I'm just grateful the code editor never fails me (unless changing tab and trying to undo/redo, which can sometimes break).

**Comment by EricEzaM** [comment] 2023-01-13 23:11
@elvisish sounds like you are talking about #66424, fixed by #71055

**Comment by EricEzaM** [comment] 2023-01-13 23:12
Oh wait this issue just seems like a dupe of #66424, I just read the OP. I think this can be closed.

**Comment by elvisish** [comment] 2023-01-14 00:10
> @elvisish sounds like you are talking about #66424, fixed by #71055

I don't think anything in undo/redo has been fixed yet.

**Closed** 2023-01-14 00:29 UTC
Labels: bug, archived, topic:editor, confirmed, topic:3d
