### ISSUE TITLE
Visual Studio Release x64 doesn't start, Debug Win32 works

### ISSUE THREAD

**Issue by kungfooman** [godotengine/godot#18911] opened 2018-05-15 20:32 UTC
**Godot version:**

https://github.com/godotengine/godot/commit/3b8bd50b41e0197ab3bce653548715872a93ea80

**OS/device including version:**

Windows 10 Version 1709 (Build 16299.431)

**Issue description:**

I can start the Win32 Debug .exe without problems, but the x64 Release .exe is simply doing nothing (instant exiting)

**Steps to reproduce:**

1) Open Visual Studio 2015 devenv console
2) build the solution with: scons vsproj=yes platform=windows
3) switch settings to Win64 / Release
4) build it
5) try to start it, should fail

![](https://i.gyazo.com/d86eebb168f7efa61eba370700148e16.png)

![](https://i.gyazo.com/e846d9a770b2ccdf6b77ca3d31477717.png)

**Comment by Simran-B** [comment] 2019-04-24 13:36
Windows 10 Pro 1809 Build 17763.43 (64-bit)
Visual Studio Community 14.0.25431.01 Update 3

I tried `debug` `Win32` and `x64` configurations in VS. Both resulting executables launch the editor (the 32-bit version has some issue with WASAPI but otherwise everything works superficially).

With `release` `x64` it compiles successfully in VS, but the resulting `godot.windows.opt.64.exe` does not want to start the editor. The following error message pops up:

> Error: Could not load game data at path '.'. Is the .pck file missing?

![error message box](https://user-images.githubusercontent.com/7819991/56661442-053b0580-66a2-11e9-839e-d651e83de170.png)

I also tried to compile on command line (devenv native x64):

    scons -j6 target=release platform=windows

is rejected with:

> Tools can only be built with targets 'debug' and 'release_debug'

    scons -j6 target=release tools=no platform=windows

Above command builds Godot successful but aforementioned error occurs on execution. 

    scons -j6 target=release_debug platform=windows

Above release_debug configuration works, `godot.windows.opt.tools.64.exe` starts the editor successfully.

**Comment by Calinou** [comment] 2019-04-24 16:17
@Simran-B `tools=no` will build an export template, which can't be used to create games, only run them. To compile a release-mode editor, use `scons target=release_debug` (`tools` is `yes` by default).

**Comment by Simran-B** [comment] 2019-04-24 21:02
@Calinou I see... so this is not an issue at all?

- `target=debug` to build the engine and editor
- `target=release_debug` to build the engine and editor with optimizations
- `target=release tools=no` to build the runtime with optimizations
- `target=release` engine with editor: **not supported**

The VS solution is a bit counter-intuitive. `vsproj=yes` doesn't just generate the .sln, but also starts a compilation. The solution does not have a release_debug configuration, and I'm not sure if `tools` can be disabled inside VS. Could this be somehow improved? Maybe the docs could state clearer what tools actually means and that release with tools is not supported.

**Comment by Calinou** [comment] 2019-04-25 17:36
@Simran-B Indeed, it always worked that way :slightly_smiling_face:

I've never used the Visual Studio configuration, but pull requests improving the default setup are welcome.

I've also thought about simplifying the `tools`/`target` combos:

- `tools=yes target=release_debug` would become `tools=yes target=release`,
- `tools=no target=release_debug` would become `tools=no target=debug`,
- `target=release_debug` wouldn't exist anymore.

This is however a breaking change, but it could be considered in the long term.

**Comment by Simran-B** [comment] 2019-04-25 21:50
> This way, any combination will be valid.

Sounds good.

Not sure if the sln should offer the following four configurations: `release`, `release_with_tools`, `debug`, `debug_with_tools`. I think it should just stay as it is: you have to run scons with tools=no if you want to build the runtime from within VS, be it release or debug configuration.

BTW. I think the documentation isn't correct: https://docs.godotengine.org/en/stable/development/compiling/introduction_to_the_buildsystem.html?highlight=Export%20template#target

> release_debug: Build without C++ debugging symbols and optimization, but keep the runtime checks

I think it should be 

> release_debug: Build **with** C++ debugging symbols and with optimization, but keep runtime checks

or am I missing something?

**Comment by KoBeWi** [comment] 2020-07-28 23:31
Can anyone still reproduce this bug in [Godot 3.2.3 rc2](https://godotengine.org/article/release-candidate-godot-3-2-3-rc-2) or any later release?

**Comment by KoBeWi** [comment] 2020-09-28 13:34
Closing due to lack of update. Please comment if you can still reproduce this issue in the latest stable version of Godot.

**Closed by KoBeWi** 2020-09-28 13:34 UTC
Labels: bug, platform:windows, topic:buildsystem
