### ISSUE TITLE
Single quoted text inside the triple quoted block is not string_color highlighted in the script editor 

### ISSUE THREAD

**Issue by goatchurchprime** [godotengine/godot#42961] opened 2020-10-21 14:22 UTC
**Godot version:**
3.2.3-stable

**OS/device including version:**
Windows 10

**Issue description:**

The editor de-colours text that happens to be enclosed in a single quote within the multi-line string, which makes it appear that GDScript does not implement this multi-string feature from Python.
![image](https://user-images.githubusercontent.com/677254/95779956-f5164c00-0cc2-11eb-84fe-9ca366b17b35.png)

**Steps to reproduce:**
As above

**Minimal reproduction project:**
N/A

Issue separated out from a comment on #41361 by request.

**Comment by Paulb23** [comment] 2020-10-21 17:09
Duplicate of #41403, should be fixed by #42535.

**Closed by Paulb23** 2020-10-21 17:09 UTC
Labels: bug, topic:editor, topic:gdscript

**Comment by akien-mga** [comment] 2020-10-21 17:52
That fix should be available in 3.2.4 beta 1 released today.
