### ISSUE TITLE
ESC key does not work sometimes in the script editor.

### ISSUE THREAD

**Issue by Torguen** [godotengine/godot#70049] opened 2022-12-14 09:28 UTC
### Godot version

v3.5.1.stable.official [6fed1ffa3]

### System information

w10 64

### Issue description

Watch the video:
I want to replace a word and open the replacer.
I immediately decide that I won't replace it in the end and close the replacer by pressing ESC.
Again I reopen the replacer determined to replace.
I write the new word and click on "Replace all".
Now I press ESC but ESC doesn't close the replacer, ESC doesn't work now and I have to close the replacer using the mouse.

Conclusion:
The ESC key will not close the replacer when you click the "Replace All" button.

https://user-images.githubusercontent.com/19652075/207557994-2055896a-ffa1-492b-b28f-39720fe1ac87.mp4

### Steps to reproduce

Watch the video and the description.

### Minimal reproduction project

...

**Comment by DissonantVoid** [comment] 2022-12-20 00:19
this is technically not a bug, as you can see in this function inside `code_editor.cpp` which handles the input for the find panel
![g](https://user-images.githubusercontent.com/69814029/208548850-d4ed62cc-a00e-4d29-b565-0449fa7586a8.PNG)
as you expect when pressing the ESC key `_hide_bar()` is called.
the problem is that this function checks for unhandled input which means that an input events will be handled by the UI child that is focused first and up the tree from there.
this is where the issue happens, when you press replace or replace_all (any button that is a part of the panel) the pressed button becomes focused meaning that it gets to handle any input event, and since the button actually handles keyboard events and doesn't ignore them (unlike the line edit where you type what to replace for example). the event doesn't propagate up to the `FindReplaceBar` object so it doesn't get handled

Please keep in mind that this is just my somewhat-educated guess, I don't know too much about how the engine works internally and I could be wrong. one thing that really confused me is that for an event to be handled, you must call `accept_event()` in the function where you handle the input, this way it doesn't propagate further into the next `_unhandled_event()` function. but that is not the case in `base_button.cpp`
![e](https://user-images.githubusercontent.com/69814029/208552044-abcc90a0-fb40-47e2-b569-8f0049375164.PNG)
so either I overlooked something, or the `_gui_input()` function automatically marks events as handled? I'm not so sure..

regardless, this isn't really a bug but rather a design issue.
and to fix it I guess we can either do it the hacky way by connecting the child buttons pressed signal to the panel and listen for the ESC button
or we can.. actually I don't know and I'm running out of time. I hope someone can come up with something from here.
best of luck!

**Comment by stmSi** [comment] 2022-12-24 10:21
creating new `_gui_input()` for `Replace All` button to handle ESC key is too much code for little to gain. 

So I think may be closing/hiding the Bar after pressing the `Replace All` button is more convenient.

**Comment by Torguen** [comment] 2022-12-24 10:36
I wouldn't approve of that solution because you don't know if the user wants to do more replacements.

A future bug would be "replace window closes when I do a replace".

I think the replacement window needs to be closed by the user.

**Comment by stmSi** [comment] 2022-12-24 11:15
ya... you are right..

**Closed** 2023-07-12 13:22 UTC
Labels: bug, topic:editor
