### ISSUE TITLE
Setter on variables that contains an instance are triggered while setting a property of this instance if using a one liner

### ISSUE THREAD

**Issue by Moltenhead** [godotengine/godot#49805] opened 2021-06-21 17:37 UTC
### Godot version

3.3.2 stable

### System information

Win10

### Issue description

I'm having this setup on a game I'm working on, a Singleton CtrlPopulator with :
```gds
[...]

var actual_consumer setget setActual_consumer

[...]

# SET/GET
func _setActual_consumer(consumer):
	print("in actual_consumer setter with %s" % consumer)
	actual_consumer = consumer
	if actual_consumer != null:
		actual_consumer.change_state_to("GoToBar")
```

at some point :
```gds
CtrlPopulator.actual_consumer.given_cocktail = CtrlPlayerController.PlayerCamera._Cocktail.duplicate()
```
is called, this is triggering the setter from the singleton and the print up here will trigger within console on the 8th line after  system and engine description :
```
in actual_consumer setter with [KinematicBody:1770]
[KinematicBody:1770] changing state to GoToBar
transition: IfConsumerAlreadyPresent
transition: IfNearEnough
[KinematicBody:1770] changing state to RequestBeverage
transition: IfReceivedCocktail
transition: IfDiscontent
in actual_consumer setter with [KinematicBody:1770] # << this is not normal
[KinematicBody:1770] changing state to GoToBar
# ...
```

### Steps to reproduce

1. clone this demo : https://github.com/Moltenhead/The-Space-Bar-demo.git
2. launch the game
3. when the little character arrives and have a bubble upon his head press up key (z/w/up arrow)
4. select any ingredient using left, up or right direction + space bar (directions are wasd keys or zqsd or arrows)
5. mash space bar until progress bar is full

The little character will go right. This is due to the bit of code shown up triggering the setter of `actual_consumer` from the singleton `CtrlPopulator.gd`. The console will print the details :
```
in actual_consumer setter with [KinematicBody:1619]
[KinematicBody:1619] changing state to GoToBar
transition: IfConsumerAlreadyPresent
transition: IfNearEnough
[KinematicBody:1619] changing state to RequestBeverage
transition: IfReceivedCocktail
transition: IfDiscontent
in actual_consumer setter with [KinematicBody:1619]
[KinematicBody:1619] changing state to GoToBar
transition: IfConsumerAlreadyPresent
transition: IfNearEnough
[...]
```
The `in actual_consumer setter with [KinematicBody:1619]` is not supposed to trigger on line 8.
Now if you replace the code in :
`res://Assets/Scripts/Controllers/ctrl_PlayerController.tscn`
at line 151 :
```gds
-               CtrlPopulator.actual_consumer.given_cocktail = CtrlPlayerController.PlayerCamera._Cocktail.duplicate()
+               var consumer = CtrlPopulator.actual_consumer
+               consumer.given_cocktail = CtrlPlayerController.PlayerCamera._Cocktail.duplicate()
```
The precedent call to the setter will not happen if you redo the same exact operation in game, and the little character will go back where he came from. The previous print will not appear at the 8th console line.

### Minimal reproduction project

https://github.com/Moltenhead/The-Space-Bar-demo.git

**Comment by Moltenhead** [comment] 2021-06-21 18:24
Don't hesitate to DM me on the godot discord if you need guidance on the code - same nickname.

**Comment by SpaceAceMonkey** [comment] 2021-08-01 04:26
Confirming this issue. I'm seeing the same thing in 3.3.2. Any time I directly set a property on an object to which I have assigned a setter, the setter is called. If I first assign the object to another variable, then set the property, the setter is not triggered.

**Comment by cdemirer** [comment] 2021-12-26 23:50
It sounds similar to the issues mentioned in https://github.com/godotengine/godot/issues/38221#issuecomment-628679879.

**Comment by akien-mga** [comment] 2022-01-13 10:18
Duplicate of #28720 and/or #31245.

**Closed by akien-mga** 2022-01-13 10:18 UTC
Labels: bug, topic:gdscript, confirmed
