### ISSUE TITLE
Font in Visual script in 4.0 is worse than 3.2 . .

### ISSUE THREAD

**Issue by jasperbrooks79** [godotengine/godot#40331] opened 2020-07-13 01:56 UTC
**Godot version:**
I don't know what a commit hash is, I just downloaded Godot 4.0 nightly version, 13-07-2020, and I noticed the font in visual script, on my 4K monitor, is blurry, more unreadable, than 3.2 . . I was hoping we'd get better fonts, in 4.0, so also when zoom function is used, it's still readable . .

**OS/device including version:**
Windows 10, nVidia GTX 1050Ti, 32 GB RAM . .

**Issue description:**
It's more blurry, the font, and looks ' bad ', not sure . .

**Steps to reproduce:**
Open visual script in a 4K monitor, here's screen-shots . .

![2020-07-13 0355](https://user-images.githubusercontent.com/61069740/87263212-bf43aa80-c4bc-11ea-8389-98d07e2f07fa.jpg)

**Minimal reproduction project:**
Added picture, try running visual script on 4K monitor, it looks more unreadable than 3.2, but there are some nice things, in visual script already, in 4.0, that makes it easier . . .

ADD : I hope we finally get nice fonts, in visual scripts, that also work, zoomed out, maybe . . The lines between nodes are less important, they read okay, atm, work well . . .

**Comment by volzhs** [comment] 2020-07-13 03:08
you can find hash on Help > About window.
![image](https://user-images.githubusercontent.com/8281454/87267035-942f7a00-c501-11ea-8551-08a5dcd251b8.png)

**Comment by Calinou** [comment] 2020-07-13 09:02
This is a duplicate of another issue which I can't find right now.

**Comment by Calinou** [comment] 2021-02-25 20:51
For the record, antialiased line rendering in the `master` branch has been fixed by https://github.com/godotengine/godot/pull/43828.

**Comment by rakkarage** [comment] 2022-01-25 04:35
not sure if you noticed but you can set the editor font in settings now... (that is new in 4 right?) one for normal one for bold and one for code. used for visual script too (normal I think)

**Comment by Calinou** [comment] 2024-08-06 15:59
This was fixed by MSDF font rendering, which is used in 4.0 in GraphEdit.

**Closed by Calinou** 2024-08-06 15:59 UTC
Labels: bug, topic:editor
