### ISSUE TITLE
JSON parses integers as floats.

### ISSUE THREAD

**Issue by strellydev** [godotengine/godot#75821] opened 2023-04-08 12:30 UTC
### Godot version

4.0.2

### System information

Windows 10

### Issue description

Hello, I hope you are all having a nice day,

the title says it all, I'll add that this was also an issue in the release candidates I tried and also in Godot 4.0.0 and 4.0.1.

### Steps to reproduce

You can either copy this next script and add it to a node to try it yourself, or you can download the minimal reproduction project provided.
```
extends Node2D

var testArray = []

# Called when the node enters the scene tree for the first time.
func _ready():
	testArray = JSON.parse_string("[0,1,2,3]")
	print("Value of json array[0] is: " + str(testArray[0]))
	print("Type of value of json array[0] is: " + str(typeof(testArray[0])))
	
	print("-----------------------------------")
	
	var testInt = 1
	print("Value of test int is: " + str(testInt))
	print("Type of value of test int is: " + str(typeof(testInt)))
	
	print("-----------------------------------")
	
	var testManualArray = [0,1,2,3]
	print("Value of test manual array[0] is: " + str(testManualArray[0]))
	print("Type of value of test manual array[0] is: " + str(typeof(testManualArray[0])))
```

### Minimal reproduction project

[JSONIssue.zip](https://github.com/godotengine/godot/files/11183259/JSONIssue.zip)

**Comment by dalexeev** [comment] 2023-04-08 15:30
> Note: The JSON specification does not define integer or float types, but only a number type. Therefore, converting a Variant to JSON text will convert all numerical values to float types.

The same applies to JSON parsing.

**Comment by strellydev** [comment] 2023-04-08 16:04
> > Note: The JSON specification does not define integer or float types, but only a number type. Therefore, converting a Variant to JSON text will convert all numerical values to float types.
> 
> The same applies to JSON parsing.

I see, so it was wrong in Godot 3? because there the issue doesn't happen. If so, I'll close this.

Thanks for the info.

**Comment by rsubtil** [comment] 2023-04-08 17:25
> Edit: I was thinking, maybe the issue then is the comparison between ints and floats not working? Because in a game I'm porting I'm checking if a number is in an array using the "in" operand, and that works fine in Godot 3, but Godot 4 returns false even though the number is in the array..

Related: https://github.com/godotengine/godot/issues/71559

**Comment by Calinou** [comment] 2023-04-08 17:29
Closing in favor of https://github.com/godotengine/godot/issues/71559, as this is JSON behavior by design according to its specification. JSON only has a `number` type which is floating-point.

If you want to avoid this (and be able to save Godot's own datatypes without manual conversion), use Godot's ConfigFile class or custom resources for serialization.

**Closed by Calinou** 2023-04-08 17:29 UTC

**Comment by strellydev** [comment] 2023-04-08 19:37
Thank you very much to all of you, if anyone else is interested, you can fix this by casting the JSON arrays into PackedInt32Array when loading them.
