### ISSUE TITLE
[3.x] RichTextLabel issue starting 3.4

### ISSUE THREAD

**Issue by kuhnchris** [godotengine/godot#54764] opened 2021-11-08 15:57 UTC
### Godot version

3.4.stable

### System information

Win10, Linux

### Issue description

After the recent upgrade from 3.3.stable to 3.4.stable the RichTextLabel is behaving weirdly when using conditional positioning in the bbcode.
Example project attached. Just play with the text inside of the bbcode_text block - it looks like it is calculating too little space and, as soon as it is just "1 word" it just breaks into a "new line" forcing the right-aligned text to be left aligned. This happens exclusively to right aligned text.

This is a task open by proxy for Tosek on the German Discord Community Server - I will communications between the parties incase there is a language barrier in place.

To clarify: This issue also happens for me aswell, I tried it on the latest 3.4.stable version on ArchLinux and on Windows.

### Steps to reproduce

Have big font size, have text in RichTextEditor. Have a "[right]text with spaces[/right]" bb-block. Expect proper text alignment, get broken text alignment and weird new line breaks.

### Minimal reproduction project

[RichTextLabelBug.zip](https://github.com/godotengine/godot/files/7498313/RichTextLabelBug.zip)

This contains the "arial" font aswell, incase anyone is concerned about the license.
I tried it with other fonts aswell (Comme Sans), same effect.

**Comment by akien-mga** [comment] 2021-11-08 17:20
CC @godotengine/gui-nodes @timothyqiu

**Comment by timothyqiu** [comment] 2021-11-09 02:56
Not sure if I understand the issue correctly, but I think the behavior is the same between 3.3.stable and 3.4.stable:

| Version | Behavior |
|----|----|
| 3.3 |  ![3 3 stable](https://user-images.githubusercontent.com/372476/140852788-a9c165d1-3d7f-404b-8c1f-2bc95f209b9d.gif)  |
| 3.4 | ![3 4 stable](https://user-images.githubusercontent.com/372476/140853335-b3dae82f-e150-475a-b1fb-feb605ee624d.gif)  |

But yes, the "newline" is an artifact for the space after the word "right" I think.

**Comment by TorstenDamberg** [comment] 2021-11-09 11:25
Well no, in the RichtextLabel of 3.4 the [right] Tag is often ignored, there is something wierd about it, which did not habben in 3.3. The [center] tag seems to works correctly.

**Comment by TorstenDamberg** [comment] 2021-11-09 11:33
Look at the time at the bottom, this is the same project with 3.3
![image](https://user-images.githubusercontent.com/60141899/140916743-73a6a909-eac0-4f55-bd5c-032525294a84.png)

and with 3.4
![image](https://user-images.githubusercontent.com/60141899/140916767-340b79e1-1f10-4970-bcfb-0d605da15152.png)

**Comment by kuhnchris** [comment] 2021-11-09 11:41
> Not sure if I understand the issue correctly, but I think the behavior is the same between 3.3.stable and 3.4.stable:
> Version 	Behavior
> 3.3 	![3 3 stable](https://user-images.githubusercontent.com/372476/140852788-a9c165d1-3d7f-404b-8c1f-2bc95f209b9d.gif)
> 3.4 	![3 4 stable](https://user-images.githubusercontent.com/372476/140853335-b3dae82f-e150-475a-b1fb-feb605ee624d.gif)
> 
> But yes, the "newline" is an artifact for the space after the word "right" I think.

The issue is the other way arround: there is far more than enough space in the box for the text and it seems like it's breaking over. Your use-case would look correct if there wasn't enough space, but here, in our example project, the box has far more than enough space to the left to not require a line break.

**Comment by timothyqiu** [comment] 2021-11-09 12:25
> The issue is the other way arround: there is far more than enough space in the box for the text and it seems like it's breaking over. Your use-case would look correct if there wasn't enough space, but here, in our example project, the box has far more than enough space to the left to not require a line break.

@kuhnchris Those gifs were me resizing the label in your MRP (RichTextLabelBug.zip). I'm afraid that I still can't reproduce the said behavior no matter how large or small I resize the label. Is your MRP supposed to show the wrong behavior once opened, or I have to set the Label to some specific size?

English is not my native language, so maybe I misunderstood your words. Could you take a screenshot of the wrong appearance?

By the way, did you mean 3.3.4 when you say 3.3? If it's exactly 3.3, could you test if it works in 3.3.4?

@TorstenDamberg I tried `[right][b]right aligned text[/b][/right]` briefly and could not reproduce the left alignment either :sweat:  A minimum reproduction project would be appreciated.

**Comment by TorstenDamberg** [comment] 2021-11-09 15:19
[RichTextLabelBug.zip](https://github.com/godotengine/godot/files/7505869/RichTextLabelBug.zip)
Wenn you start this project in the editor. The text is aligned right. When you start the game the text in the RichTextLabel is aligned left using 3.4 stable (Windows 10).

Editor:
![image](https://user-images.githubusercontent.com/60141899/140951786-399e62fd-1681-47fc-9be2-42bbd9713202.png)

And runtime:
![image](https://user-images.githubusercontent.com/60141899/140951889-4f865712-b270-47ed-95be-ce0b61c2a6b6.png)

**Comment by TorstenDamberg** [comment] 2021-11-09 15:20
You see the effect/ bug, when you run the scene

**Comment by timothyqiu** [comment] 2021-11-09 16:06
Thank you for your explanation, I can reproduce this now. Sorry for my carelessness.

**Comment by timothyqiu** [comment] 2021-11-09 16:49
The issue is gone if I revert #52752. I think this may be some float point precision issue?  CC @Listwon

**Comment by TorstenDamberg** [comment] 2021-11-26 15:14
Just tested in 3.4.1 rc1 => still not working

**Comment by kuhnchris** [comment] 2021-11-29 07:52
Would it make sense to have a toggle in the editor to switch between the int and the float version? that would probabbly be the best solution to enable support for both types. There is already a 2nd issue in #54551 apparently connected to this issue. If this would be a desired solution let me know and I'll try to implement it.

**Comment by pycbouh** [comment] 2021-11-29 09:48
@kuhnchris No, this won't be a proper solution, nor is it feasible to do something like that. You would have to duplicate all the related variables, which would make code harder to understand, and you still won't fix the actual problem with the floating point calculations.

**Comment by akien-mga** [comment] 2021-11-29 09:53
I'll probably revert #52752 for 3.4.1 unless someone comes up with a simple fix.

**Comment by akien-mga** [comment] 2021-11-29 13:56
Fixed by #55439.

**Closed by akien-mga** 2021-11-29 13:56 UTC
Labels: bug, regression, topic:gui

**Comment by NewOldMax** [comment] 2021-12-14 09:00
Glad I found this issue 😀
It was crazy to understand why my working project behaves wrong
Waiting for 3.4.1
