### ISSUE TITLE
Vulkan: GPUParticles outlive lifetime

### ISSUE THREAD

**Issue by floppyhammer** [godotengine/godot#58525] opened 2022-02-25 08:27 UTC
### Godot version

v4.0.alpha.custom_build [80baa1386]

### System information

Windows 11, Vulkan

### Issue description

When `one_shot` enabled, `explosiveness` set to 1, and `lifetime` is small, particles go back to their previous status at the end of their lifetime. Same issue occurs to both GPUParticles2D and GPUParticles3D.

![gpu_particles](https://user-images.githubusercontent.com/28705694/155679838-bba0224b-2e8b-4d73-a7dd-4759b8ebfad5.gif)

A bit similar to https://github.com/godotengine/godot/issues/56691, but in that issue the flicker seems to happen at the start of lifetime instead of the end.

### Steps to reproduce

Set `lifetime` 0.5, enable `one_shot`, set `explosiveness` 1, set `fixed_delta` 30. Add some lifetime related properties, e.g. scale curve or color ramp. Click `emitting`.

### Minimal reproduction project

[GPUParticles.zip](https://github.com/godotengine/godot/files/8139573/GPUParticles.zip)

**Comment by greycheeked** [comment] 2023-10-05 07:16
I can't reproduce this issue. (v4.1.1.stable.official [bd6af8e0e])

**Comment by Calinou** [comment] 2023-10-05 16:51
Closing per @greycheeked's comment. Please comment if you can still reproduce this on the latest Godot version.

**Closed by Calinou** 2023-10-05 16:51 UTC
Labels: bug, topic:rendering, regression
