### ISSUE TITLE
Strange AnimatedSprite bug in multiplayer client

### ISSUE THREAD

**Issue by rikedyp** [godotengine/godot#20120] opened 2018-07-12 20:13 UTC
**Godot version:**

3.0.2.stable.official

**OS/device including version:**

Linux Lite 3.8
Linux 4.4.0-130-generic (x86_64)
OpenGL Renderer: AMD ARUBA (DRM 2.43.0)

**Issue description:**

I have preserved the version of my project with the bug here:  
https://github.com/rikedyp/RikedyRacer/tree/animated_sprite_bug  
  
You should be able to open the project in the Godot version specified.  Open two instances so that you can have a host and client open.  
The affecting code is in gd/lobby.gd from line 128 to 161 (and in gamestate.gd)  

When using the buttons to choose a vehicle, the host will play the animated sprite on a loop _**as expected**_. However, the clients will seem to play only the first 2 frames on a weird jittery loop (not expected)

As far as I can tell it is the same code being executed on host and clients, so I don't know why this occurs.  
HOWEVER, I was able to fix (in current master branch) by using a new dedicated animated sprite in the lobby for vehicle selection (instead of in the preserved version, linked above, where I tried to use the vehicle .tscn files that already existed for player sprites).
HENCE, this is not a big priority to be fixed for this game, I just thought it might be a lower level Godot bug and so it might be of interest to developers (or it might be specific to my set up, in which case no worries maybe?)

**Minimal reproduction project:**

https://github.com/rikedyp/RikedyRacer/tree/animated_sprite_bug  for now, I may make a minimal attempt later this week

Anyway thanks for checking this out if it interests you

**Comment by KoBeWi** [comment] 2020-07-20 21:42
Can anyone still reproduce this bug in [Godot 3.2.2](https://godotengine.org/article/maintenance-release-godot-3-2-2) or any later release?

**Comment by KoBeWi** [comment] 2020-09-28 00:25
Closing due to no reply. Please comment if you can still reproduce in 3.2.3+.

**Closed by KoBeWi** 2020-09-28 00:25 UTC
Labels: bug, topic:network, topic:rendering
