### ISSUE TITLE
Right docks move offscreen after switching to script tab

### ISSUE THREAD

**Issue by Superwaitsum** [godotengine/godot#18078] opened 2018-04-09 05:58 UTC
**Godot version:**

https://github.com/godotengine/godot/commit/9e7cee2ceb1a963c1da2c21013adf7d616412d3c

**OS/device including version:**

Windows 8.1 x64
Screen Resolution: 1280x1024 (Maybe related?)

**Issue description:**
Switching to Script tab modifies the position of right side docks and can't be fixed until resizing
Similar to #17412, but with the script tab.

**Steps to reproduce:**
Have to use a build with  #17923 merged (found it after bisecting).

Having the editor in fullscreen, switch to the Script tab, the Scene and inspector docks change their position, being off the screen.
This persist even after changing to 2D or 3D tabs, and only fixed after resizing the godot window while in those modes.

**Minimal reproduction project:**
An image showing it: (notice the right docks' displacement)
![imagen](https://user-images.githubusercontent.com/22568812/38480724-c337fff8-3b8c-11e8-9c1d-0a19a0d9428c.png)

**Comment by akien-mga** [comment] 2018-04-09 19:53
>  Have to use a build with #17923 merged (found it after bisecting).

You mean that it's a regression from #17923? CC @Paulb23

**Comment by Superwaitsum** [comment] 2018-04-10 01:04
Yes, found it testing commit by commit

**Comment by Paulb23** [comment] 2018-04-10 20:07
This is caused by the new drop down menu 'Syntax Highlighter' needing more space thus pushing the right side docks off the screen. I guess it could be shortened to just "Highlighter"? Or hiding it inside another sub menu?

**Comment by eon-s** [comment] 2018-04-11 04:37
In small resolution the whole right part is lost, it should respect the max size and shortening the word may not work.

**Comment by RikazuDev** [comment] 2018-04-13 14:08
I am having the same problem too, tested it all on Godot 3 versions, (3.0.0 ~ 3.0.2);

Before
![before](https://user-images.githubusercontent.com/23402006/38739321-26d22e7a-3f67-11e8-8bf2-54d880c8fe1f.JPG)
 

After
![after](https://user-images.githubusercontent.com/23402006/38739332-2f2041f2-3f67-11e8-8109-193e57264d23.JPG)

**Comment by Paulb23** [comment] 2018-07-15 16:16
Guess this one can be closed now #19166 is merged?

**Comment by akien-mga** [comment] 2018-07-17 11:40
Fixed by #19166.

**Closed by akien-mga** 2018-07-17 11:40 UTC
Labels: bug, topic:editor
