### ISSUE TITLE
Building with `verbose=no` on Windows with Visual Studio duplicates lines in standard output

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot#9033] opened 2017-06-03 12:29 UTC
When building Godot (tested with https://github.com/godotengine/godot/commit/69bec86028f87307e549d7a2f49bbb7e2b1f3771 and Visual Studio 2017, can also be reproduced with VS 2015) with `verbose=no` passed to SCons, each compiled file will appear twice in the log. One of them will be colored and formatted, one of them won't. See below for screenshot.

![quieter_output](https://cloud.githubusercontent.com/assets/180032/26753529/db4047a8-4868-11e7-993e-f89fd0ca1f05.png)

This makes the console output less compact and readable than it ought to be.

**Comment by kubecz3k** [comment] 2018-04-04 15:58
First of all thank you for your report and sorry for the delay.

We released Godot 3.0 in January 2018 after 18 months of work, fixing many old issues either directly, or by obsoleting/replacing the features they were referring to.

We still have hundreds of issues whose relevance/reproducibility needs to be checked against the [current stable version](https://godotengine.org/download), and that's where you can help us.
**Could you check if the issue that you described initially is still relevant/reproducible in Godot 3.0 or any newer version, and comment about its current status here?**

For bug reports, please also make sure that the issue contains detailed steps to reproduce the bug and, if possible, a zipped project that can be used to reproduce it right away. This greatly speeds up debugging and bugfixing tasks for our contributors.

Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

Thanks in advance.

*Note: This message is being copy-pasted to many "stale" issues (90+ days without activity). It might happen that it is not meaningful for this specific issue or appears oblivious of the issue's context, if so please comment to notify the Bugsquad about it.*

**Comment by Calinou** [comment] 2018-04-04 18:25
This issue still occurs with commit https://github.com/godotengine/godot/commit/7ca2e73dea59a2e0683253e73b9b549d749e12f9 on the same configuration as described in OP.

![godot_msvc_duplicate_lines](https://user-images.githubusercontent.com/180032/38326512-44ab23a2-3846-11e8-8b20-da501fc99df1.png)

**Comment by Calinou** [comment] 2018-06-30 10:56
I recently found out thanks to [this article](http://blog.llvm.org/2018/03/clang-is-now-used-to-build-chrome-for.html) that Ninja filters those output messages out of the box: https://github.com/ninja-build/ninja/blob/master/src/clparser.cc#L67

I wonder if it's possible to do the same in SCons. Surely `cl.exe`'s standard output should be redirected to a stream which can then be filtered?

**Comment by KoBeWi** [comment] 2020-06-12 11:32
Still valid in 84abf5a

**Comment by akien-mga** [comment] 2021-04-28 09:44
That seems to be a SCons+`cl.exe` issue then and not something to fix in Godot. Since we haven't managed to work it around in 4 years I doubt it will happen now, so closing. Switching to Meson might solve it ;)

**Closed by akien-mga** 2021-04-28 09:44 UTC
Labels: bug, confirmed, platform:windows, topic:buildsystem
