### ISSUE TITLE
[4.x] Creating New Folder in File System Tab Pops Error in Console (with Project Manager running in GL mode)

### ISSUE THREAD

**Issue by Lazy-Rabbit-2001** [godotengine/godot#76335] opened 2023-04-22 02:55 UTC
### Godot version

4.0.2 till 4.1dev

### System information

Windows 11, GLES3 (with project manager running in gl_compability mode)

### Issue description

![动画](https://user-images.githubusercontent.com/22123964/233758091-2a557fab-a043-4b0b-9b25-efc0b384c519.gif)
As the gif plays, when the folder is on creation, the console popped this:
platform/windows/display_server_windows.cpp:2361 - Condition "!windows.has(p_window)" is true. Returning: Rect2i()
Though it didn't oblige the project from running, its piling would make people annoying and irritate a bit.
I think this should get fixed in some of the future versions.

### Steps to reproduce

1. Open Godot 4 from project manager (must run in gl_compability mode/default rendering mode)
2. Open any project you want or like
3. Create a folder in file system
4. You will see a popped error in console

### Minimal reproduction project

None

**Comment by Calinou** [comment] 2023-04-22 17:43
- Duplicate of https://github.com/godotengine/godot/issues/71612 (same cause).

**Closed by Calinou** 2023-04-22 17:43 UTC
Labels: bug, platform:windows, topic:editor
