### ISSUE TITLE
[Request] modify the behaviour of transform inspector

### ISSUE THREAD

**Issue by cutepig49** [godotengine/godot#9905] opened 2017-07-27 06:38 UTC
When the rotation is set to (45, 45, 0) in inspector, godot and unity have different behavious.(above picture is unity3d, below one is godot)
Don't you think unity's way is more convenient and properly?
![unity](https://user-images.githubusercontent.com/3340057/28657207-8799c436-72d8-11e7-94e2-e4ddeccfaa21.PNG)
![godot](https://user-images.githubusercontent.com/3340057/28657211-8aa0a9a6-72d8-11e7-9b18-0bc2c2a9135d.PNG)

**Comment by groud** [comment] 2017-07-27 06:48
The unity model seems rotated once, not twice. (Its still on the green/red plane, which should no happen with 2 rotations)
Does seem that Godot's behvaiour is normal, while Unity's isn't. ¯\_(ツ)_/¯

**Comment by bojidar-bg** [comment] 2017-07-27 07:06
Related/Dupe of #9782?

**Comment by tagcup** [comment] 2017-07-31 19:00
Unity uses a YXZ convention whereas Godot uses an XYZ convention, you can see this in the respective documentations.

#9782 is about additional Euler angle conventions whereas this one seems to be changing the "default" Euler angles to match Unity's. I don't have a strong opinion about the convention for Euler angles, one way or another. However, it'd be some work (because that's a compatibility breaking change and will break all the scenes), without any substantial gains IMO.

**Comment by kubecz3k** [comment] 2017-08-05 16:46
I don't think there is any bug here. @cutepig49 let us know if you will want to discuss this more.

**Closed by kubecz3k** 2017-08-05 16:46 UTC
