### ISSUE TITLE
Output doesn't scroll with new print messages and hides them sometimes

### ISSUE THREAD

**Issue by Swarkin** [godotengine/godot#78979] opened 2023-07-03 12:17 UTC
### Godot version

v4.1.rc2.official

### System information

Win10

### Issue description

The output stops scrolling to new messages resulting in it being useless:
![image](https://github.com/godotengine/godot/assets/102416174/4358e6ba-e924-42f8-bbd2-67e71d12e9cd)

See video below as well.
This was confirmed by someone on discord too.

### Steps to reproduce

Print a lot, in my case 1 - 2 times per `_process()` call.

https://github.com/godotengine/godot/assets/102416174/39391f0f-c300-4c3b-bb27-afa7df69c776

### Minimal reproduction project

Any

**Comment by YuriSizov** [comment] 2023-07-03 12:21
Thanks for your report, this seems to be a duplicate of https://github.com/godotengine/godot/issues/78899 (which covers two problems, one of which is yours).

**Closed by YuriSizov** 2023-07-03 12:21 UTC
