### ISSUE TITLE
is_connected_to_host  should only work if connection is actually connected to a real tcp server

### ISSUE THREAD

**Issue by ghost** [godotengine/godot#22605] opened 2018-10-02 02:53 UTC
3.1, w10, 64-bit
i don't know if this is the same on linux (if sum1 can plz test, please do!, thanks!)

```
extends Control

var socket = StreamPeerTCP.new()

func _ready():
	if socket.connect_to_host("227.0.0.11", 9305) == OK:
		print("Connected!") # not connected though
	

var c = 0
func _process(delta):
	if c > 0.1:
		print(socket.is_connected_to_host())
		c = 0
	c += delta
```

for example, i'm using a fake ip and fake port (there is no tcp server running) but  the `is_connected_to_host` still prints true.

**Comment by Faless** [comment] 2018-10-07 22:46
Duplicate of #18323 see https://github.com/godotengine/godot/issues/18323#issuecomment-383325914 specifically.

> `is_connected_to_host` returns true also when the status is connecting, if you want to know if the status is connected use `get_status() == StreamPeerTCP.STATUS_CONNECTED`. As said, it could be renamed to `is_active()` for clarity, but documenting it should be enough.

If we want to change that behaviour it's an API breaking change, and should be done after `3.1`.

`connect_to_host` returns `OK` if there was no network error. The fact that there is no listening server on the other end is irrelevant most of the times, unless a TCP packet to that destination generates an ICMP packet in return (e.g. the destination is unreachable during connection, or the remote server has a `REJECT` policy that sends ICMP `Destination Unreachable: RFC-792` when that port is closed).
I think we should at least better explain to **use `get_status()`** and not `is_connected_to_host()` in the docs.

**Comment by Faless** [comment] 2020-01-14 16:23
We might address this in `4.0` when/if we decide to refactor low level networking with breaking changes.

**Comment by akien-mga** [comment] 2022-03-26 12:55
@Faless confirmed on chat that this is still pending and would be good to change.

**Closed** 2022-04-27 11:56 UTC
Labels: enhancement, documentation, topic:network
