### ISSUE TITLE
tool scripts will error if an autoload is referenced.

### ISSUE THREAD

**Issue by leoddd** [godotengine/godot#13332] opened 2017-11-27 02:43 UTC
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Windows 10 x64, Godot 3 Alpha 2

**Issue description:**

If there's any autoload referenced inside a script with the tool keyword at the top, it will not work.
It would of course make sense for it to throw an error if the autoload was actually accessed in the program, but this can be avoided with Engine.is_editor_hint() if it's not directly required for the editor functionality you're looking for.
Could autoloads be added to the script parser's recognized identifiers by default?

```
res://entities/gametext/gametext.gd:1059 - Compile Error: Identifier not found: audio
modules\gdscript\gd_script.cpp:596 - Method/Function Failed, returning: ERR_COMPILATION_FAILED
```

**Steps to reproduce:**
1) Create an autoload script
2) Reference that autoload in any tool script in your project

**Comment by akien-mga** [comment] 2017-11-27 06:49
Thanks for the bug report. It's a duplicate of #4236.

**Closed by akien-mga** 2017-11-27 06:49 UTC
