### ISSUE TITLE
Syntax eror refers to the line that doesn't exist

### ISSUE THREAD

**Issue by agjkqkwgoqwt** [godotengine/godot#87142] opened 2024-01-13 08:10 UTC
### Tested versions

4.2.1. stable

### System information

4.2.1. stable win

### Issue description

Syntax eror refers to line that doesn't exist when the function body is empty. This is an unexpected behavior

![image](https://github.com/godotengine/godot/assets/156133637/8dcf64aa-af21-4123-88ee-666f9e2420c8)

### Steps to reproduce

remove any content in function body

### Minimal reproduction project (MRP)

not requred

**Comment by AThousandShips** [comment] 2024-01-13 09:36
Duplicate of https://github.com/godotengine/godot/issues/81046

**Closed by AThousandShips** 2024-01-13 09:36 UTC
