### ISSUE TITLE
Area2D collision signal being received without having collision layer in mask

### ISSUE THREAD

**Issue by p-brighenti** [godotengine/godot#47556] opened 2021-04-01 22:57 UTC
**Godot version:**
v3.3.rc7.official

**OS/device including version:**
Windows 10 Home 20H2

**Issue description:**
Sorry about the title being confusing but I did not find a better way to summarize it in just a few words.

The issue I'm facing is that I have a node **A** which is a `KinematicBody2d` and has as a child an `Area2D` on layer 1 with, let's say, layer 2 and 4 in its mask. 

The second node, **B**, is itself an `Area2D` which is on layer 3 and has layer 1 on its mask. 

Both of these are monitorable and monitored.

Given this configuration I'm expecting that when **A** and **B**'s areas collide, that **B** will receive a signal but not **A** given that it didn't have layer 3 on it's `Area2D` mask.

Currently **A** is receiving a `body_entered` signal when it collides with **B**'s `Area2D` even though **A**'s mask does not contain the layer **B** is in.

Is this the expected behaviour and is it up to the user to discard the event in it's callback by inspecting the `body`'s argument `collision_layer` field? 

**Steps to reproduce:**

1. Create a `KinematicBody2D` node with a `Area2D` as a child spanning over it.
2. Put the `Area2D` on layer 1 and no layer on it's mask. Make it both monitorable and monitoring
3. Attach a script to the `KinematicBody2D` node.
4. Connect the `on_body_entered` signal of `Area2D`
5. Create a `Area2D` node on layer 2 and with layer 1 on it's mask.
6. Make the `KinematicBody2D` node collide with the `Area2D` node
7. Verify that the signal callback is being called even though the `KinematicBody2D`'s `Area2D` does not have layer 2 on it's mask

I'll make sure to update the issue with the minimal example tomorrow as I just don't have the time to do it today. My apologies.

**Comment by Calinou** [comment] 2021-04-01 23:11
Duplicate of https://github.com/godotengine/godot/issues/7644 ?

**Comment by p-brighenti** [comment] 2021-04-02 15:25
> 
> 
> Duplicate of #7644 ?

Seems like it. If so, it's already being addressed in this PR https://github.com/godotengine/godot/pull/42268 .
Please consider it for 4.0, if you aren't considering it yet. I'll try to check if there's a proposal for this yet.
Thanks!

**Closed** 2021-04-02 15:56 UTC
Labels: bug, topic:physics
