### ISSUE TITLE
scene of a sub-viewport is drawn outside the sub-viewport

### ISSUE THREAD

**Issue by gber** [godotengine/godot#2121] opened 2015-06-19 15:05 UTC
The instanced scene of a sub-viewport is drawn outside the sub-viewport, i.e. the scene is drawn relative to the root viewport and not the sub-viewport. See http://code.guido-berhoerster.org/tmp/BugReproducer2.tar.gz for a minimal project to reproduce the issue.

**Comment by akien-mga** [comment] 2015-11-22 13:41
Hi @gber and sorry for the delay. It looks like your minimal project is not available anymore, could you reupload one?

**Comment by gber** [comment] 2015-11-22 17:35
Github is really annoying for not allowing binary attachments, I've attached the above tarball base64 encoded: [BugReproducer2.tar.gz.txt](https://github.com/godotengine/godot/files/41097/BugReproducer2.tar.gz.txt)

You can extract it e.g. with openssl like this: `openssl enc -base64 -d -in BugReproducer2.tar.gz.txt | gunzip | tar xf -`.

**Comment by akien-mga** [comment] 2015-11-22 17:45
I can reproduce the issue in the current master branch using the file in the above comment.

**Comment by akien-mga** [comment] 2016-03-05 11:00
Potentially related to #1840.

**Comment by KoBeWi** [comment] 2019-09-18 13:01
Could someone upload a decoded repro? >_>

**Comment by clayjohn** [comment] 2020-06-20 22:08
I have a feeling this is no longer relevant in 3.x. Plus there has been no engagement in over 4 years. Closing for now, if anyone can figure this out and reproduce it, I would be happy to re-open.

**Closed by clayjohn** 2020-06-20 22:08 UTC
Labels: archived, bug, confirmed, topic:core, topic:rendering
