### ISSUE TITLE
Black screen when running the project (renders correctly in the editor)

### ISSUE THREAD

**Issue by artvel** [godotengine/godot#85103] opened 2023-11-19 19:05 UTC
### Godot version

4.2.rc1

### System information

Windows 11 and MacOS Sonoma 14.1.1

### Issue description

Screen is black at startup and stays black but the game seem to behave as usual behind the black screen. Meaning that sound and movement seems correctly but its just not visible.

### Steps to reproduce

Run the minimal reproduction project.

### Minimal reproduction project

[Basic_3d_Starter.zip](https://github.com/godotengine/godot/files/13404366/Basic_3d_Starter.zip)

**Comment by Calinou** [comment] 2023-11-20 12:02
I can confirm this on 4.2.beta da0b1eb12 (Linux, GeForce RTX 4090 with NVIDIA 535.129.03). No errors appear in the console or terminal.

Corrupted visuals do appear if you resize the window while it's running:

![image](https://github.com/godotengine/godot/assets/180032/91b5b476-8e10-4307-ac10-88d167f062be)

A Godot splash screen on a black background may appear too if you resize the window quickly after the project starts.

Removing the WorldEnvironment node doesn't fix the black screen. Removing the character node and adding a Camera3D instead doesn't fix the black screen either.

**Comment by YuriSizov** [comment] 2023-11-21 14:55
I can confirm @Calinou's findings. The regression appears to have happened between 4.2 beta 3 and beta 4.

**Comment by YuriSizov** [comment] 2023-11-21 15:16
Bisected to https://github.com/godotengine/godot/commit/425e9435766e0f459e76c1ed10830b2485241733. https://github.com/godotengine/godot/pull/83649 is the cause of this regression.

Which makes it a duplicate of https://github.com/godotengine/godot/issues/84280 I guess.

**Closed** 2023-11-21 15:16 UTC
Labels: bug, topic:rendering, confirmed, topic:3d

**Comment by Ad4moO** [comment] 2023-11-21 18:37
I tried including 2D nodes into my project to see if it makes a difference but the screen was still black. So, I hope your guess is right about this being a duplicate of #84280 .

**Comment by YuriSizov** [comment] 2023-11-21 20:15
@Ad4moO The solution would be to disable MSAA for 2d, rather than add 2d nodes.

**Comment by Ad4moO** [comment] 2023-11-22 12:01
@YuriSizov thanks for your prompt answer correcting me 👍. Setting `rendering/anti_aliasing/quality/msaa_2d` to `disabled` does the trick for now.

**Comment by ivan-resetnikov** [comment] 2024-09-02 14:32
The issue still occurs in Godot v4.2 (stable.official [46dc27791]). The editor view renders fine, but the problem arises when I run the game in the editor.

This issue does not occur when exporting (tested on Windows 11 Pro Education 10.0.22631) or when using any renderer other than Compatibility.

It's worth noting that when creating/opening an empty project or one of smaller scale, it works fine, so there must be some feature causing the problem. However, it will take me a long time to find it since this is my company's game, which has been in development for almost a year.

**Comment by AThousandShips** [comment] 2024-09-02 15:01
Please add your information to:
* #84280 

This is a duplicate and information should be focused on the other issue, not here
