### ISSUE TITLE
packetscene breaks charged scene

### ISSUE THREAD

**Issue by kone9** [godotengine/godot#27839] opened 2019-04-09 10:02 UTC
**Godot version:**
![2019-04-08 21_48_24-Godot Engine - FlappyBird3D - Escena_principal_lista tscn](https://user-images.githubusercontent.com/12847027/55791563-27733780-5a95-11e9-8ba9-86430201e476.jpg)

**OS/device including version:**
windows 7,geforce9800gt,core2quad

**Issue description:**
packetscene breaks charged scene

**Steps to reproduce:**
tenemos una escena con un script. esa escena es la escena que se ejecuta al poner play al motor vendria a ser como el menu princpal.
we have a scene with a script. that scene is the scene that is executed when putting the engine play would be like the main menu.

![2019-04-09 19_05_22-Godot Engine - FlappyBird3D - MenuPrincipal tscn](https://user-images.githubusercontent.com/12847027/55838377-a6e72200-5afa-11e9-9fbd-3955f978dfd7.jpg)

Tiene en el script un export packetscene.
![2019-04-09 19_08_21-Godot Engine - FlappyBird3D - MenuPrincipal tscn (_)](https://user-images.githubusercontent.com/12847027/55838444-e4e44600-5afa-11e9-8d53-d6a220facc8a.jpg)

Ponemos nuevo packetscene.
It has an export packetscene in the script.
![2019-04-09 19_08_58-Godot Engine - FlappyBird3D - MenuPrincipal tscn (_)](https://user-images.githubusercontent.com/12847027/55838474-f88fac80-5afa-11e9-8149-93da5db5f349.jpg)

hacemos click arriba de packetscene y nos aparece una propiedad llamada bundled.
we click above packetscene and a property called bundled appears.
![2019-04-09 19_09_39-Godot Engine - FlappyBird3D - MenuPrincipal tscn (_)](https://user-images.githubusercontent.com/12847027/55838493-0e04d680-5afb-11e9-9e9e-44d61ce4aabd.jpg)

Ahora por error cargue la escena princpal luego de hacer todo lo anterior.
Now by mistake load the main scene after doing all the above.
![2019-04-09 19_10_30-Godot Engine - FlappyBird3D - MenuPrincipal tscn (_)](https://user-images.githubusercontent.com/12847027/55838538-2ffe5900-5afb-11e9-9bad-90adf1d3b5ee.jpg)
![2019-04-09 19_11_09-Godot Engine - FlappyBird3D - MenuPrincipal tscn (_)](https://user-images.githubusercontent.com/12847027/55838583-53290880-5afb-11e9-944c-a2f151f70945.jpg)

Ponemos play al proyecto y tocamos click para pasar a la escena principal de juego,
We put play to the project and we click to go to the main game scene,
![2019-04-09 19_12_07-Godot Engine - FlappyBird3D - MenuPrincipal tscn (_)](https://user-images.githubusercontent.com/12847027/55838621-7489f480-5afb-11e9-9b3e-fdfcde633157.jpg)
![2019-04-09 19_12_25-Godot Engine - FlappyBird3D - MenuPrincipal tscn](https://user-images.githubusercontent.com/12847027/55838643-8370a700-5afb-11e9-9424-0fff97ba6c2f.jpg)

la escena no carga y se corrompe la escena del cargada en el PACKETSCENE.
the scene does not load and the loaded scene in the PACKETSCENE is corrupted.
![2019-04-09 19_14_52-(3) GodotEngine issue packetScene BUG breaks scene - YouTube](https://user-images.githubusercontent.com/12847027/55838733-cdf22380-5afb-11e9-90d9-f645d4eb49fd.jpg)

Si abris la escena con un block de notas y la comparamos con una funcionando vemos lo siguiente...NO TIENE NADA ESCRITO
If you open the scene with a notebook and compare it with a working one we see the following ... IT HAS NOTHING WRITTEN
![56635062_2410956769133706_4526754362998915072_o](https://user-images.githubusercontent.com/12847027/55838786-00038580-5afc-11e9-990b-2dc3c2ac922b.jpg)

Aqui hay un VIdeo:
Here is a VIdeo:
https://www.youtube.com/watch?v=D-L0Y_etPoo&t=33s

El proyecto ahora no tiene el BUG o no lo puedo reproducir,pero pueden descargarlo desde Aquí.
The project now does not have the BUG or I can not reproduce it, but you can download it from Here.
https://github.com/kone9/flappyBird3D-GODOT

english by google translator

**Comment by groud** [comment] 2019-04-09 11:27
Please, I just closed the same issue few minutes ago as a duplicate:  #27829
If you think this is not a duplicate please explain what the problem is and how it differs from the other issue. Else I'll have to close this one too.

Also, a video is no a bug report. Not everyone has the time to review a 2 minutes long video to understand your problem.

**Comment by kone9** [comment] 2019-04-09 21:24
> Please, I just closed the same issue few minutes ago as a duplicate: #27829
> If you think this is not a duplicate please explain what the problem is and how it differs from the other issue. Else I'll have to close this one too.
> 
> Also, a video is no a bug report. Not everyone has the time to review a 2 minutes long video to understand your problem.

there is a bug when loading the scene, but you have 2 minutes to watch a video so do not dedicate yourself to fixing problems ....... Because it took me 30 minutes to report this.

**Comment by kone9** [comment] 2019-04-09 21:39
> Please, I just closed the same issue few minutes ago as a duplicate: #27829
> If you think this is not a duplicate please explain what the problem is and how it differs from the other issue. Else I'll have to close this one too.
> 
> Also, a video is no a bug report. Not everyone has the time to review a 2 minutes long video to understand your problem.

I'm going to edit the post, please do not erase it

**Comment by groud** [comment] 2019-04-09 21:50
No, I don't have two minutes to dedicate to each issue opened everyday. From the dozen of issue opened everyday, we have to close half of them for being duplicates, correctly label the others, and comment when we have to do so. So I cannot afford spending too much time on each issue everyday.

We have an issue template, we ask people to fill it because it helps everyone in the review process, and also allows searching for similar issues. So please, fill in the issue template by explaining:
1) how did the issue happen (don't just drop a video, it's useless if you don't explain what is happening)
2) what happened exactly ("something is broken" is not describing what happens, tells us the errors you got)
3) explain what was expected.

I will try to be honest here. All the time we spend in here asking people to make better feedback is the time we do not spend fixing bug or implementing features, the better you do the job, the better we do ours. Not to mention we have already too much work with the already 4k+ opened issues, so if you don't spend time writing a good bug report, your issue will sadly stayed ignored. And in the end with bad reports, you might waste more of our time than you save us.

**Comment by groud** [comment] 2019-04-09 21:51
> I'm going to edit the post, please do not erase it

Just saw this message after my last comment. Thanks, that's appreciated :)

**Comment by kone9** [comment] 2019-04-09 22:25
> Just saw this message after my last comment. Thanks, that's appreciated :)

A part of the half hour that I take to write it reissue it takes me 1:30 hs plus you erase it and I'll find you until the end of the world to get all your teeth. XD ... Anything ask me ... I am at your disposal. .. I am going to take into account what they tell me ... I can not reproduce it now, do not ask me why, after remaking the whole scene, the BUG did not come out anymore .... But report the step by step with photos and you also have the video if you are interested.
Thank you.

**Comment by groud** [comment] 2019-04-10 05:53
Arf you don't have to put screenshot for each step but that's ok :)
Thanks!

**Comment by Calinou** [comment] 2020-08-18 14:17
@kone9 Can you (or anyone else) still reproduce this bug in [Godot 3.2.2](https://godotengine.org/article/maintenance-release-godot-3-2-2) or any later release?

If yes, please ensure that an up-to-date Minimal Reproduction Project (MRP) is included in this report (a MRP is a zipped Godot project with the minimal elements necessary to reliably trigger the bug). You can upload ZIP files in an issue comment with a drag and drop.

**Comment by Calinou** [comment] 2021-02-14 16:06
Closing in favor of https://github.com/godotengine/godot/issues/45864, which seems closely related and has more information.

**Closed by Calinou** 2021-02-14 16:06 UTC
Labels: bug, topic:core
