### ISSUE TITLE
The Sprite surrounding rect is offset for a 11x10 texture

### ISSUE THREAD

**Issue by MatiasVME** [godotengine/godot#26454] opened 2019-03-01 20:31 UTC
**Godot version:**
Godot.3.1.beta.9.official

**Issue description:**
The sprite frame is not correct. See this video --> [Video](https://youtu.be/QVUSlAwwkuk)

**Steps to reproduce:**
1) Open the minimal example
2) Zoom to sprite
3) See the frame of the sprite

**Minimal reproduction project:**
[Bug1.tar.gz](https://github.com/godotengine/godot/files/2920944/Bug1.tar.gz)

**Comment by bojidar-bg** [comment] 2019-03-01 21:20
Duplicate of #7015.

**Closed by bojidar-bg** 2019-03-01 21:20 UTC
Labels: bug, topic:core
