### ISSUE TITLE
Menu bar freezing the application

### ISSUE THREAD

**Issue by KaruroChori** [godotengine/godot#44115] opened 2020-12-05 09:21 UTC
**Godot version:**

Godot 4.0 14660ee but this behaviour was first observed one week ago. I built the system few weeks ago and this bug was not there, but I am not able to find which commit was exactly as I deleted the build since.
The latest stable version does work as expected instead.

**OS/device including version:**

Linux 80x86 64bit, dual gpu 1660 super and a 2060. The 2060 is the main one. Drivers 450.66

**Issue description:**

The interface (but not the 3d viewport) has considerably more lag than few weeks ago. After I try to open a menu from the top bar the menu is rendered but the application becomes unresponsive and the menu stays split from the window once moved. Also this process does freeze the computer for few seconds.

**Steps to reproduce:**
Open any project, click on an element on the top bar.

**Minimal reproduction project:**

There is no need. I was not able to go past creating an empty project as I cannot even try to save it.

**Comment by Calinou** [comment] 2020-12-05 09:53
Duplicate of https://github.com/godotengine/godot/issues/41614.

**Closed by Calinou** 2020-12-05 09:53 UTC
