### ISSUE TITLE
(GDScript) Mixing tabs and spaces in arrays

### ISSUE THREAD

**Issue by Louis-Simon22** [godotengine/godot#75853] opened 2023-04-09 12:19 UTC
### Godot version

4.0.2.stable

### System information

Ubuntu 22.10

### Issue description

The following gdscript code will produce an error because the line with `1,2,3,4` starts with a tab following by a space. 
Error: `Mixed use of tabs and spaces for identation`
This used to work in gdscript 3

```
var data = [
	 1,  2,  3,  4
	-1, -2, -3, -4
]
```

### Steps to reproduce

Put this code in a godot4 project
```
var gradients2D = [
	 1,  2,  3,  4
	-1, -2, -3, -4
]
```

### Minimal reproduction project

N/A

**Comment by AThousandShips** [comment] 2023-04-09 13:16
Duplicate of #49171

**Closed** 2023-04-09 13:18 UTC
