### ISSUE TITLE
VehicleWheels default direction is inconsistent with Vector3.FORWARD

### ISSUE THREAD

**Issue by Skaruts** [godotengine/godot#69112] opened 2022-11-24 14:07 UTC
### Godot version

Both Godot 3 and Godot 4

### Issue description

VehicleWheels, by default, point (and move) toward positive Z, while Godot's conception of the forward direction is toward negative Z.

**Comment by Calinou** [comment] 2022-11-24 15:08
Duplicate of https://github.com/godotengine/godot/issues/47650.

**Closed by Calinou** 2022-11-24 15:08 UTC
Labels: bug, topic:physics, breaks compat, topic:3d

**Comment by Skaruts** [comment] 2022-11-24 21:33
From the title I thought that was a separate issue.
