### ISSUE TITLE
Errors in  console after just running 3.0.6.stable.official.8314054

### ISSUE THREAD

**Issue by Vikram1323** [godotengine/godot#25608] opened 2019-02-04 13:43 UTC
Godot version:
3.0.6.stable.official.8314054

OS/device including version:
Dell Inspiron 1464, Window 7 64 bit, ATI Mobility Radeon HD 4300 Series

Issue description:
Getting these errors after running the engine. Maybe same as #25607

OpenGL ES 3.0 Renderer: ATI Mobility Radeon HD 4300 Series
ERROR: initialize: Condition ' status != 0x8CD5 ' is true. Continuing..:
   At: drivers/gles3/rasterizer_scene_gles3.cpp:4893
ERROR: initialize: Condition ' status != 0x8CD5 ' is true. Continuing..:
   At: drivers/gles3/rasterizer_scene_gles3.cpp:4893
ERROR: initialize: Condition ' status != 0x8CD5 ' is true. Continuing..:
   At: drivers/gles3/rasterizer_scene_gles3.cpp:4893
ERROR: initialize: Condition ' status != 0x8CD5 ' is true. Continuing..:
   At: drivers/gles3/rasterizer_scene_gles3.cpp:4893
ERROR: initialize: Condition ' status != 0x8CD5 ' is true. Continuing..:
   At: drivers/gles3/rasterizer_scene_gles3.cpp:4893
ERROR: initialize: Condition ' status != 0x8CD5 ' is true. Continuing..:
   At: drivers/gles3/rasterizer_scene_gles3.cpp:4893
ERROR: initialize: Condition ' status != 0x8CD5 ' is true. Continuing..:
   At: drivers/gles3/rasterizer_scene_gles3.cpp:4893
ERROR: initialize: Condition ' status != 0x8CD5 ' is true. Continuing..:
   At: drivers/gles3/rasterizer_scene_gles3.cpp:4893
ERROR: initialize: Condition ' status != 0x8CD5 ' is true. Continuing..:
   At: drivers/gles3/rasterizer_scene_gles3.cpp:4893
ERROR: initialize: Condition ' status != 0x8CD5 ' is true. Continuing..:
   At: drivers/gles3/rasterizer_scene_gles3.cpp:4893
ERROR: initialize: Condition ' status != 0x8CD5 ' is true. Continuing..:
   At: drivers/gles3/rasterizer_scene_gles3.cpp:4893
ERROR: initialize: Condition ' status != 0x8CD5 ' is true. Continuing..:
   At: drivers/gles3/rasterizer_scene_gles3.cpp:4893
ERROR: initialize: Condition ' status != 0x8CD5 ' is true. Continuing..:
   At: drivers/gles3/rasterizer_scene_gles3.cpp:4893
ERROR: initialize: Condition ' status != 0x8CD5 ' is true. Continuing..:
   At: drivers/gles3/rasterizer_scene_gles3.cpp:4893
ERROR: initialize: Condition ' status != 0x8CD5 ' is true. Continuing..:
   At: drivers/gles3/rasterizer_scene_gles3.cpp:4893
ERROR: initialize: Condition ' status != 0x8CD5 ' is true. Continuing..:
   At: drivers/gles3/rasterizer_scene_gles3.cpp:4893
ERROR: initialize: Condition ' status != 0x8CD5 ' is true. Continuing..:
   At: drivers/gles3/rasterizer_scene_gles3.cpp:4893
ERROR: initialize: Condition ' status != 0x8CD5 ' is true. Continuing..:
   At: drivers/gles3/rasterizer_scene_gles3.cpp:4893
ERROR: initialize: Condition ' status != 0x8CD5 ' is true. Continuing..:
   At: drivers/gles3/rasterizer_scene_gles3.cpp:4893
ERROR: initialize: Condition ' status != 0x8CD5 ' is true. Continuing..:
   At: drivers/gles3/rasterizer_scene_gles3.cpp:4893
ERROR: initialize: Condition ' status != 0x8CD5 ' is true. Continuing..:
   At: drivers/gles3/rasterizer_scene_gles3.cpp:4893
ERROR: initialize: Condition ' status != 0x8CD5 ' is true. Continuing..:
   At: drivers/gles3/rasterizer_scene_gles3.cpp:4893
ERROR: initialize: Condition ' status != 0x8CD5 ' is true. Continuing..:
   At: drivers/gles3/rasterizer_scene_gles3.cpp:4893
ERROR: initialize: Condition ' status != 0x8CD5 ' is true. Continuing..:
   At: drivers/gles3/rasterizer_scene_gles3.cpp:4893
ERROR: initialize: Condition ' status != 0x8CD5 ' is true. Continuing..:
   At: drivers/gles3/rasterizer_scene_gles3.cpp:4893
ERROR: initialize: Condition ' status != 0x8CD5 ' is true. Continuing..:
   At: drivers/gles3/rasterizer_scene_gles3.cpp:4893
ERROR: initialize: Condition ' status != 0x8CD5 ' is true. Continuing..:
   At: drivers/gles3/rasterizer_scene_gles3.cpp:4893
ERROR: initialize: Condition ' status != 0x8CD5 ' is true. Continuing..:
   At: drivers/gles3/rasterizer_scene_gles3.cpp:4893
ERROR: initialize: Condition ' status != 0x8CD5 ' is true. Continuing..:
   At: drivers/gles3/rasterizer_scene_gles3.cpp:4893
ERROR: initialize: Condition ' status != 0x8CD5 ' is true. Continuing..:
   At: drivers/gles3/rasterizer_scene_gles3.cpp:4893
ERROR: initialize: Directional shadow framebuffer status invalid
   At: drivers/gles3/rasterizer_scene_gles3.cpp:4918

I can create, run and edit my projects.

Steps to reproduce:
Run Godot 3.0.6

Minimal reproduction project:
Not required

**Comment by akien-mga** [comment] 2019-02-08 16:34
Duplicate of #25607.

**Closed by akien-mga** 2019-02-08 16:34 UTC
