### ISSUE TITLE
Debugger crashes when evaluating too large a composite array

### ISSUE THREAD

**Issue by Banderi** [godotengine/godot#22654] opened 2018-10-02 23:13 UTC
**Godot version:**
3.0.6

**OS/device including version:**
Windows 7 64-bit, GTX 970

**Issue description:**
If a structure (such as an array of arrays) that is large enough is created, the debugger will always crash if stopped inside the parent of said structure, or inside an external function that is trying to evaluate/fetch a value from that node, or (in case the node is a singleton or it's loaded as a variable inside the current function) when clicking on said node from the debugger's list of current loaded variables - thus making debugging very difficult. If undisturbed, the process/game will continue normally, so I assume this is just an issue of the editor not having a large enough memory allowance for displaying big structures such as this.

**Steps to reproduce:**
Create an array of arrays of objects, of size at least 254 by 254, containing at least one key of any size; the debugger will always crash when stopping inside the structure's parent.
If the key is 5-8 characters long, 239 is the maximum array size before crashing. For 9-12 characters, it's 226 - and so on.

**Minimal reproduction project:**
[test.zip](https://github.com/godotengine/godot/files/2440009/test.zip)

**Comment by eon-s** [comment] 2018-10-03 00:56
Probably related to #20258

**Comment by Banderi** [comment] 2018-10-03 01:06
Hmm, possibly. As this is very easy to reproduce, it could help with pinning that problem down too if it's the same cause.

**Comment by Zylann** [comment] 2019-08-11 13:09
Just ran into this as well, with the following code:
```gdscript
extends Node


func _ready():
	var data = PoolByteArray()
	data.resize(4000000)
	assert(false)
```

**Comment by akien-mga** [comment] 2020-01-07 14:58
Closing as duplicate of #20258.

**Closed by akien-mga** 2020-01-07 14:58 UTC
Labels: bug, confirmed, topic:editor
