### ISSUE TITLE
Add zlib (de)compression support to File class

### ISSUE THREAD

**Issue by LikeLakers2** [godotengine/godot#22440] opened 2018-09-26 03:10 UTC
Title. zlib is already packaged within Godot, and [NetworkedMultiplayerENet already has a zlib compression mode](http://docs.godotengine.org/en/latest/classes/class_networkedmultiplayerenet.html#enum-networkedmultiplayerenet-compressionmode), so I wonder why `File` can't have the same.

If it helps, my use case involves `PoolByteArray.decompress()`, which itself uses the compression mode enum from `File` (and thus I presume it uses File somewhere within).

**Comment by akien-mga** [comment] 2018-09-26 06:53
Duplicate of #3701.

**Comment by LikeLakers2** [comment] 2018-09-26 07:41
@akien-mga While I can understand the assessment, I'm not sure I agree with it being a duplicate. My use case involves exposing zlib compression as an option for use with PoolByteArray.decompress.

**Comment by akien-mga** [comment] 2018-09-26 07:45
While I agree it's not strictly speaking the same thing (#3701 was focusing on making Zip archives, while this issue requires Zlib compression), the two are strongly linked with each other and should be implemented together IMO, so it makes sense to have one single issue to keep track of that.

**Comment by LikeLakers2** [comment] 2018-09-26 07:45
Okay, that's fair. Thank you for explaining.

**Comment by akien-mga** [comment] 2018-09-26 07:49
That said, if you can put some details about the Zlib features you'd expect in #3701, that would be good. I renamed the issue to match what I described above, but the comments themselves don't speak much of Zlib yet, so that should be added so that potential contributors willing to work on it take both into account.

**Comment by LikeLakers2** [comment] 2018-09-26 07:51
I'll do that shortly. Thanks.

**Comment by akien-mga** [comment] 2018-09-26 07:57
In second thought, I think I'm wrong in my above assessment. Both topics *are* linked and should likely be handled together, but it still makes sense to have dedicated issues for each.

**Comment by vnen** [comment] 2018-09-27 01:35
zlib is already implemented, `File.COMPRESSION_DEFLATE` means it's using zlib.

**Comment by LikeLakers2** [comment] 2018-09-27 01:39
Then shouldn't it be `File.COMPRESSION_ZLIB` if it's actually zlib? I know Zlib implements Deflate as an option, but deflate isn't necessarily zlib decompression.

**Comment by vnen** [comment] 2018-09-27 01:57
AFAIK the only thing special about zlib is the special header. The compression algorithm is the same (`deflate`).

**Comment by LikeLakers2** [comment] 2018-09-27 03:43
To my knowledge, zlib can use more than deflate. I might be wrong, however, and would appreciate if someone could clarify. https://tools.ietf.org/html/rfc1950

**Comment by LikeLakers2** [comment] 2018-09-27 03:50
One of the bits in the header specifies the compression method (https://tools.ietf.org/html/rfc1950#section-2, see section 2.2, under "CM (Compression method)"). That's why I'm confused.

Either way, it would be nice if the docs cleared up this distinction, or if a alias named `File.COMPRESSION_ZLIB` was added.

**Comment by LikeLakers2** [comment] 2018-09-27 04:06
Somewhat unrelated (except to my use case), but since this is an issue about (de)compression, can I ask why `PoolByteArray.decompress()` requires me to specify the size of the uncompressed data? It just seems really odd that it asks for that...

**Comment by LikeLakers2** [comment] 2018-09-27 04:10
Somewhat unrelated, but since it relates to the use case I described for this issue... `PoolByteArray.decompress()` requires me to specify the maximum size of how big I want the resulting array to be. Why? Wouldn't it sort of be possible to figure out the size automatically?

**Comment by akien-mga** [comment] 2020-05-26 09:14
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!

**Closed by akien-mga** 2020-05-26 09:14 UTC
Labels: documentation, feature proposal, topic:core, topic:thirdparty
