### ISSUE TITLE
Outer click is detected on panel's border

### ISSUE THREAD

**Issue by hydroper** [godotengine/godot#76302] opened 2023-04-20 19:23 UTC
### Godot version

4.0.2

### System information

Windows 11, gl_compatibility

### Issue description

I'm trying to detect click outside of a panel which **DOES NOT** use expand margins but uses a border. The panel I'm referring to is a child instantiated scene which overrides `_input`:

```gdscript
func _input(event):
    if is_open && !_busy && (event is InputEventMouseButton) and event.pressed:
        var ev_local = make_input_local(event)
        if !Rect2(Vector2(0, 0), size).has_point(ev_local.position):
            outer_click.emit()
```

On my previous game project, a click outside of that panel causes it to close or collapse.

Video: [https://streamable.com/j59951](https://streamable.com/j59951)

Note that, for some reason, the reproduction steps don't reproduce the bug I'm talking about. I've attached a minimal reproduction project and it seems to work _entirely_ fine (prints `out click` correctly). I don't know why; therefore I'm leaving a link to my previous project where the panel isn't working properly:

- [https://github.com/hydroper/phantasystar3](https://github.com/hydroper/phantasystar3)

The scene is [gd/screens/game_screen/GameScreen.tscn](https://github.com/hydroper/phantasystar3/tree/master/gd/screens/game_screen). Press <kbd>ESC</kbd> to open the main panel. It may take 3 seconds to start the scene (I don't know why; a bug?) Then try clicking the bottom border, mess with it up and you'll see the bug.

### Steps to reproduce

- Create a `Control` scene
- Add a `PanelContainer` as child of that `Control` scene, filling it up entirely.
- Instantiate that scene as child of another main scene.
- Override `_input` for detecting an outside click, printing `"outer click"`.

Read the issue description as to regards to why these reproduction steps work.

### Minimal reproduction project

Read the issue description as to why this minimal project doesn't reproduce the bug.

[outerclicktest.zip](https://github.com/godotengine/godot/files/11289711/outerclicktest.zip)

**Comment by kleonc** [comment] 2023-04-21 16:18
> Read the issue description as to why this minimal project doesn't reproduce the bug.

> Note that, for some reason, the reproduction steps don't reproduce the bug I'm talking about. I've attached a minimal reproduction project and it seems to work _entirely_ fine (prints `out click` correctly). I don't know why;

So there's no actual explanation on "why this minimal project doesn't reproduce the bug". Also there's no explanation why do you think it's an engine bug and not a user error of some sort. Something doesn't work in your project and you're assuming it's an engine bug, not an error on your side. Even though you can't simply reproduce it.

> therefore I'm leaving a link to my previous project where the panel isn't working properly:
> 
> - https://github.com/hydroper/phantasystar3
> 
> 
> The scene is [gd/screens/game_screen/GameScreen.tscn](https://github.com/hydroper/phantasystar3/tree/master/gd/screens/game_screen). Press ESC to open the main panel. It may take 3 seconds to start the scene (I don't know why; a bug?) Then try clicking the bottom border, mess with it up and you'll see the bug.

So I've added this to `res://gd/ui/components/BaseAnimatedPanel.gd`:
```gdscript
func _draw() -> void:
	draw_rect(Rect2(Vector2(0, 0), size), Color.RED, false, 5.0)
```
and `queue_redraw()` to its `_process` method. It clearly shows the rects you're checking against mismatch the visuals:
![IZnM1sWMmH](https://user-images.githubusercontent.com/9283098/233683029-2f42a8bf-7e99-4dc6-a57c-f895c05ba7f9.gif)

Haven't investigated why exactly (not a simple project provided) but I'd guess the child Container somehow exceeded the parent Control's rect. The parent Control's rect won't be automatically enlarged to ensure it fits the children, that's not how Controls work. You should likely be using a Container instead of a Control. So seeing you modify `self.position`/`self.scale` of such parent Control within the mentioned script I'm assuming it's indeed a user error. Hence closing as not a bug.

But if you'll find it's actually a bug, please provide a proper minimal reproduction project (instead of minimal non-reproduction project) and it could be reopened. :slightly_smiling_face:

**Closed by kleonc** 2023-04-21 16:18 UTC
