### ISSUE TITLE
mouse_exited isn't emitted when mouse exits the game window

### ISSUE THREAD

**Issue by me2beats** [godotengine/godot#43285] opened 2020-11-03 02:45 UTC
**Godot version:**

3.2.3

**OS/device including version:**

Windows

**Issue description:**

`mouse_exited` signal isn't emitted when mouse exits the game window (in cases when the control is full window size for example).

Same for `mouse_entered`.

**Steps to reproduce:**
1. Create a new project with a Control
2. Set the control size to full rect (Layout - Full Rect)
3. Set the following script to the control:
```gdscript
extends Control


func _ready():
	connect("mouse_entered", self, "on_mouse_entered")
	connect("mouse_exited", self, "on_mouse_exited")

func on_mouse_entered():
	print("entered")

func on_mouse_exited():
	print("exited")
```
4. run the scene and **move mouse outside the game window**
as you can see, 'exited' isn't printed (`mouse_exited` signal isn't emitted) 
5. the same goes for 'mouse_entered'

**Minimal reproduction project:**

**Comment by Zylann** [comment] 2020-11-03 03:52
I think you can listen for mouse enter and exits from the OS window by listening to these notifications:

```
func _notification(what):
	if what == NOTIFICATION_WM_MOUSE_ENTER:
		print("Mouse enter")
	if what == NOTIFICATION_WM_MOUSE_EXIT:
		print("Mouse exit")
```

**Comment by me2beats** [comment] 2020-11-03 04:00
> I think you can listen for mouse enter and exits from the OS window by listening to these notifications:
This would work well only if the control is fullsize of the game window.

**Comment by nathanfranke** [comment] 2020-11-05 05:15
Duplicate of https://github.com/godotengine/godot/issues/35185
Will be fixed by https://github.com/godotengine/godot/pull/36925

---

The `mouse_exited` signal should only fire after the mouse re-enters the window though- that is the expected behaviour. See the PR demos.

**Comment by Calinou** [comment] 2020-11-21 14:40
Closing per @nathanfranke's comment.

**Closed by Calinou** 2020-11-21 14:40 UTC

**Comment by nathanfranke** [comment] 2021-03-20 23:36
I have the same behaviour even though #35185 has been resolved. However, the mouse exited signal shouldn't fire here regardless since:

1) The OS doesn't send input updates to windows that aren't under the mouse, so Godot can't know where the mouse really is.
2) It can lead to unexpected behaviour such as #35185.

I can guess that most people wouldn't want this behaviour anyways so to hard code it into the mouse signals would make it almost impossible to work around. I would recommend looking at @Zylann's workaround.

**Comment by Zylann** [comment] 2021-03-21 02:26
> The OS doesn't send input updates to windows that aren't under the mouse, so Godot can't know where the mouse really is.

Godot can't know where the mouse is but it can know it exited whatever it was in. Therefore Godot could reproduce a consistent `mouse_exited` behavior using it, rather than requiring scripts to workaround it.

> It can lead to unexpected behaviour such as #35185.

This is an different situation:
Here a common GUI pattern known as "mouse capture" is used. Dragging operations (such as pressing, holding, moving and releasing) make the target control receive events exclusively, even if the mouse exits the window. I guess using `mouse_exited` in this case does would not actually make sense.
For example open the project manager, and press the list's slider. While holding the slider, move the mouse. The slider remains in the same state. Move outside the window. The slider still remains in the same state, and still responds to mouse events. Release mouse button: the slider unpresses accordingly.

**Comment by nathanfranke** [comment] 2021-03-21 02:32
> Godot can't know where the mouse is but it can know it exited whatever it was in. Therefore Godot could reproduce a consistent `mouse_exited` behavior using it, rather than requiring scripts to workaround it.

Most of your comment makes sense and is agreeable. However one problem with this is it might go against what `mouse_exited` means fundamentally. When the mouse exits the screen, the last known mouse position (The one returned by `get_viewport().get_mouse_position()`) is still on the screen and probably still on the control.

I agree, there probably should be some workaround. This way buttons on the edge of the viewport won't show as hovered over when the mouse exits the viewport. Someone should probably reopen this issue as a proposal.
