### ISSUE TITLE
Godot 4 Mono not working

### ISSUE THREAD

**Issue by M77mdsD** [godotengine/godot#75493] opened 2023-03-30 15:05 UTC
### Godot version

4.0 stable

### System information

Windows 11

### Issue description

I got this issue while trying to run Godot 4 mono:
```
ERROR: hostfxr_initialize_for_runtime_config failed with code: -2147450733
   at: (modules/mono/mono_gd/gd_mono.cpp:201)
ERROR: .NET: Failed to load compatible .NET runtime
   at: (modules/mono/mono_gd/gd_mono.cpp:278)
ERROR: Parameter "godot_plugins_initialize" is null.
   at: initialize (modules/mono/mono_gd/gd_mono.cpp:411)
```

And I have .Net SDK 6 and .Net SDK 7 installed:
```
.NET SDK:
 Version:   7.0.202
 Commit:    6c74320bc3

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22621
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.202\

Host:
  Version:      7.0.4
  Architecture: x64
  Commit:       0a396acafe

.NET SDKs installed:
  6.0.407 [C:\Program Files\dotnet\sdk]
  7.0.202 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.15 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
```

### Steps to reproduce

Open Godot 4 Mono Stable.

### Minimal reproduction project

Open Godot 4 Mono Stable.

**Comment by AThousandShips** [comment] 2023-03-30 15:08
Duplicate of #75152

**Comment by Calinou** [comment] 2023-03-30 17:24
- Duplicate of https://github.com/godotengine/godot/issues/75152.

**Closed by Calinou** 2023-03-30 17:24 UTC
