### ISSUE TITLE
Support autoconverting tab/shift-tab to spaces to allow web code copying

### ISSUE THREAD

**Issue by chucklepie** [godotengine/godot#30494] opened 2019-07-10 14:50 UTC
**Godot version:**
3.1

**OS/device including version:**
Windows

**Issue description:**
Godot uses tab character for indent and it stays as a tab. When you copy any code from the internet, specifically any of the sample code at the Godot tutorial/documentation site you get 4 spaces (html does not support the tab character).

So, when you paste Godot code from the Godot website, then try to add a line of code you get an error and have to fix all of the code you have copied. When multiple levels of nesting occurs, this is self-defeating and you typically give up or spend a long time untabbing then tabbing.

I would suggest the method Visual Studio Code employs where a tab character is automatically converted to 4 spaces, but because it knows what 4 spaces is when you press shift-tab it will automatically go back a full tab space. Thus allowing spaces and tabs to be used together.

At the minute, the editor is not good and copying code fails every single time. As a developer of Godot you probably are unaware of this issue, but for beginners or people copying code from the internet, this is complete fail :(

If not, at least provide a toggle for autoconverting tab to 4 spaces when tab is pressed.

Thanks.

**Comment by KoBeWi** [comment] 2019-07-10 15:00
Duplicate of #19285 (which already has a PR)

**Closed by KoBeWi** 2019-07-10 15:00 UTC

**Comment by chucklepie** [comment] 2019-07-10 15:09
Ok.
