### ISSUE TITLE
File duplicate window closes too quickly

### ISSUE THREAD

**Issue by Janglee123** [godotengine/godot#37821] opened 2020-04-12 07:02 UTC
**Godot version:** master 9dc19f7619633dc55bcebc4270d54fddc03bc97f

**OS/device including version:** Solus

**Issue description:** ~~Duplicating a file in the file system dock doesn't work either with `ctrl+D` or from the right-click menu.~~

**Steps to reproduce:**
N/A
**Minimal reproduction project:**
N/A

**Comment by developedby** [comment] 2020-04-12 15:17
Can't reproduce. Are you sure you are giving the new file a different name?

**Comment by KoBeWi** [comment] 2020-04-12 15:54
Can't reproduce in d160644c8

**Comment by Calinou** [comment] 2020-04-12 18:05
Maybe the script editor's <kbd>Ctrl + D</kbd> shortcut takes precedence if you have it open? See also #37807.

**Comment by KoBeWi** [comment] 2020-04-12 19:53
Yeah, but OP mentions right-click menu. The shortcut issue is irrelevant.

**Comment by Janglee123** [comment] 2020-04-13 09:21
It seems to be a bug with the X11 display server on Linux. A small window appears and disappears too quickly. It also happens with rename and move-to.
![Peek 2020-04-13 14-46](https://user-images.githubusercontent.com/29702428/79109280-a7616b00-7d95-11ea-9cce-842596ddc0a2.gif)

**Comment by qarmin** [comment] 2020-04-13 13:16
For me windows closing randomly on Ubuntu 19.10 and it seems to only happens when using mouse.
![jfile](https://user-images.githubusercontent.com/41945903/79122402-d8db3600-7d97-11ea-9d0a-69f40e203af6.gif)

**Comment by EzraT** [comment] 2020-06-28 14:08
> For me windows closing randomly on Ubuntu 19.10 and it seems to only happens when using mouse.

Can confirm, same thing happens for me running Linux Mint 19.3 Cinnamon

**Comment by neikeq** [comment] 2020-07-05 12:17
Looks the same as #38931
Can you still reproduce this?

**Comment by akien-mga** [comment] 2020-07-06 06:47
Likely fixed by #39993.

**Closed by akien-mga** 2020-07-06 06:47 UTC
Labels: bug, confirmed, platform:linuxbsd, topic:editor
