### ISSUE TITLE
After a static body that adds a convex polygon collision shape collide with a rigid body object, the window is forcibly closed after running for a few seconds.

### ISSUE THREAD

**Issue by haizhou37** [godotengine/godot#22903] opened 2018-10-10 03:22 UTC
**Godot version:**
      3.0.6

**OS/device including version:**
  manjaro gnome x64
 Intel® Core™ i3-2350M CPU @ 2.30GHz × 4 
Intel® Sandybridge Mobile
OpenGL ES 3.0 Renderer: Mesa DRI Intel(R) Sandybridge Mobile 
intel hd 3000
4g ram

**Issue description:**
I created a rigid body (which is a cube) and a static body (which is the plane, **using a convex shape collision**), saves them as a scene, and then runs in the main scene（**let the cube fall on the plane**）. But only for a few seconds, the window closed itself.
I tried other collision shapes (such as cubes, capsules, etc.) and moved the cube position so that it could not collide with the plane, but there is no such problem.No problem with the log.
**Latest test situation:**
Different versions of the situation are not the same. In version 3.0.6, the cube will fall flat on the plane, but after a while the window will close; in version 3.1, the collision seems to be invalid, the cube will fall through the plane; the same version 3.1, if the cube is set to the number of points in the convex shape, the cube will not pass through the plane, nor will it close the window, but it will gradually tilt，just like the effect of the screenshots in my other answers
![_navigator_20181014083759](https://user-images.githubusercontent.com/33272474/46911399-f3f39c80-cf8c-11e8-98db-51f181bd6871.gif)

**Steps to reproduce:**
1.Created a rigid body  and a static body
2.Set the static body collision shape to convex
3.Let the rigid body fall on a static body with a convex collision body
4.Run

**Minimal reproduction project:**
[Test.zip](https://github.com/godotengine/godot/files/2462992/Test.zip)

Is this problem because my computer is outdated and the performance is so bad that it can't bear the collision of the convex shape?

**Comment by groud** [comment] 2018-10-10 09:39
Can you try with Godot 3.1 alpha ?

**Comment by haizhou37** [comment] 2018-10-11 12:42
> Can you try with Godot 3.1 alpha ?

After I ran this project with godot 3.1 alpha, the convex collision failed, and the cube goes through the plane and falls off

**Comment by avencherus** [comment] 2018-10-12 04:04
Gave it a look, it appears that your StaticBody collision shape has no vertices.  When I added some, the box landed just fine.

## Floor StaticBody
![godot_master_2018-10-12_07-02-08](https://user-images.githubusercontent.com/13004169/46847400-dc7dad80-cdec-11e8-9dd0-b85dddc7841e.png)

## No points/vertices defined on your floor collision shape.
![godot_master_2018-10-12_07-01-54](https://user-images.githubusercontent.com/13004169/46847425-eb646000-cdec-11e8-8e54-baab127aefa5.png)

**Comment by avencherus** [comment] 2018-10-12 04:30
I can confirm it on Win10 3.0.6 Stable.  I get this error message:

![cmd_2018-10-12_07-26-10](https://user-images.githubusercontent.com/13004169/46848073-75fa8e80-cdf0-11e8-9baa-e2675f46acd0.png)

Also on one occasion in the alpha, I did get this error, though I don't know if it is related.

![godot_master_2018-10-12_07-26-55](https://user-images.githubusercontent.com/13004169/46848090-8d397c00-cdf0-11e8-9912-011a900e677c.png)

**Comment by haizhou37** [comment] 2018-10-13 02:41
> Gave it a look, wasn't getting the window closing issue. (Win 3.1 alpha [451e5fd](https://github.com/godotengine/godot/commit/451e5fd0511bc2c17a66fc73a0de9a5169109517))
> 
> But it does appears that your StaticBody collision shape has no vertices.
> ## Floor StaticBody
> 
> ![godot_master_2018-10-12_07-02-08](https://user-images.githubusercontent.com/13004169/46847400-dc7dad80-cdec-11e8-9dd0-b85dddc7841e.png)
> ## No points/vertices defined on your floor collision shape.
> 
> ![godot_master_2018-10-12_07-01-54](https://user-images.githubusercontent.com/13004169/46847425-eb646000-cdec-11e8-8e54-baab127aefa5.png)

I followed the steps above to set it up, added some points, and the problem of closing the window before it did disappear. But there is a new problem: the cube falling on the plane will tilt for no reason, what is this?
![2018-10-13 07-47-46](https://user-images.githubusercontent.com/33272474/46900428-7bc9a000-ced4-11e8-8570-ebdaa1d059e7.png)

**Comment by Zireael07** [comment] 2018-10-13 08:12
Since the issue stems from no vertices on the shape, I believe this is a duplicate of an existing issue and I believe the consensus was that there should be a warning for this case (similar to the warning for no shape set)

**Comment by capnm** [comment] 2018-10-13 15:42
> Since the issue stems from no vertices on the shape ...

Looks like the OP issue is, that the godot crashes (or gets out of vram) by zero points in those shapes.
On Linux it seems to work.

> added some points ... the cube falling on the plane will tilt

Does it make sense to create such "gizmos-less" shapes in the inspector UI at all?
(I thought it's here for scripting or mesh importers)

**Comment by KoBeWi** [comment] 2020-12-10 23:24
Tried the project in 3.2.4 beta3, no crash, no tilt, no errors. Looks fixed.

**Closed by KoBeWi** 2020-12-10 23:24 UTC
Labels: bug, topic:physics
