### ISSUE TITLE
macOS build fails with master

### ISSUE THREAD

**Issue by virtualritz** [godotengine/godot#25905] opened 2019-02-15 13:20 UTC
**Godot version:**
Latest/master

It seems that for some reason it looks for Android defaults instead of macOS.

```
$ scons platform=osx
scons: Reading SConscript files ...
YASM is necessary for WebM SIMD optimizations.
WebM SIMD optimizations are disabled. Check if your CPU architecture, CPU bits or platform are supported!
Checking for C header file mntent.h... no
scons: done reading SConscript files.
scons: Building targets ...
[...]
[ 88%] Compiling ==> core/global_defaults.gen.cpp
core/global_defaults.gen.cpp:2:10: fatal error: 'platform/android/globals/global_defaults.h' file not found
#include "platform/android/globals/global_defaults.h"
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
scons: *** [core/global_defaults.gen.osx.tools.64.o] Error 1
scons: building terminated because of errors.
```

**Comment by akien-mga** [comment] 2019-02-15 13:23
Duplicate of #24507.

**Closed by akien-mga** 2019-02-15 13:23 UTC
