### ISSUE TITLE
Low performance in Project Manager

### ISSUE THREAD

**Issue by jaggygames** [godotengine/godot#30794] opened 2019-07-24 12:50 UTC
**Godot version:**
Godot_v3.1.1-stable_win64
Godot_v3.1.1-stable_win32

**OS/device including version:**
Windows 10
Huawei Matebook X Pro (i5 edition)
Intel UHD 620 (Integrated)

**Issue description:**
- Godot takes longer to boot up than expected (and longer than my super low end laptop using linux)
- Clicking on projects in the Project Manager feels unresponsive as the window doesn't seem to update until the cursor moves to another part of the window on the right
- The Rename window slows everything down as `Property not found: rendering/*` errors are shown

Screen capture of the issue: https://youtu.be/VBXbWexai1o

**Steps to reproduce:**
I just run Godot

**Comment by Calinou** [comment] 2019-07-24 12:52
Duplicate of https://github.com/godotengine/godot/issues/23069.

**Closed by Calinou** 2019-07-24 12:52 UTC

**Comment by jaggygames** [comment] 2019-07-24 13:12
Ah sorry. Looks like I might have to roll back my drivers. Cheers!
