### ISSUE TITLE
GraphNode has a wrong left margin in editor plugin only

### ISSUE THREAD

**Issue by yikescloud** [godotengine/godot#67916] opened 2022-10-26 18:51 UTC
### Godot version

3.5.1stable

### System information

windows10

### Issue description

When show graphnode in editor plugin, it has a wrong title position which is different with it runs in games.
In editor plugin:
![image](https://user-images.githubusercontent.com/9168814/198107823-0bd86a53-e1e7-4858-9cc7-b2d2f7255cbc.png)
In normal editor or game:
![image](https://user-images.githubusercontent.com/9168814/198107934-496ebcd4-76cd-4ee7-89f2-008e57ea22e5.png)

 

### Steps to reproduce

Download any addons with a graphnode editor, assign a custom theme with a graphnode frame theme item on it. 

### Minimal reproduction project

[GraphNodePluginBug.zip](https://github.com/godotengine/godot/files/9872905/GraphNodePluginBug.zip)

**Comment by kleonc** [comment] 2022-10-27 16:24
Duplicate of #63256.

**Closed** 2023-01-09 13:45 UTC
Labels: bug, archived, topic:editor, topic:plugin
