### ISSUE TITLE
Compiled from master

### ISSUE THREAD

**Issue by tairony** [godotengine/godot#44591] opened 2020-12-22 11:04 UTC
Hi  i compile godot from master in elementary os 5.1.7, its compile without problems, i think 🤔.
The file output from compile is a godotlnxbsdtool64, i check and allow executable permission.
The executable open as spect, i can create a project, the 3D view port open, but if i select to add a new node, the window of nodes opens, but godot crash, and i need to force quite. I thinking, is missing some in elementary ? 
I checked vulkan and vulkan extras.
My sistem
Intel i74gen 3.6ghz 20gb ddr3
120gb ssd
Gtx 960 2gb
Nvidia driver 455 but the same bug at 450

**Comment by Calinou** [comment] 2020-12-22 15:02
Duplicate of https://github.com/godotengine/godot/issues/41614.

**Closed by Calinou** 2020-12-22 15:02 UTC
