### ISSUE TITLE
Editor crash on save if root node is TextureProgress on win64

### ISSUE THREAD

**Issue by ZippoLag** [godotengine/godot#3856] opened 2016-02-28 07:57 UTC
**Operating system or device:**
Windows 7 x64

Using Godot_v2.0_stable_20160223_win64.exe (not reproducible in same PC if using Godot_v2.0_stable_20160223_win32.exe)

**Issue description** (what happened, and what was expected):
The editor doesn't seem able to save a scene with only a TextureProgress as it's root node.

**Steps to reproduce:**
1. Open editor
2. Create and open new project
3. Add a TextureProgress
4. Attempt to save the scene -> editor crashes

**Comment by akien-mga** [comment] 2016-02-28 12:00
It does not seem to crash on Linux, so that confirms it's probably specific to Win64.

**Comment by ScotFlux** [comment] 2016-02-28 15:05
Using Windows 10 x64. I can reproduce the bug at first attempt with .scn. I also tried to save the scene (contained only TextureProgress node) to .xml .xsn .tscn. But, it's kinda weird. Sometimes it works, sometimes it doens't work and then made a crash.

**Comment by MarianoGnu** [comment] 2016-02-28 16:08
Did someone try to reproduce this bug with 1.1 stable? May be introduced with my lastest changes to texture progress or control/viewport refactor.

**Comment by ScotFlux** [comment] 2016-02-28 16:18
Just test it with Godot 1.1stable. And Yeah, no problem at saving scenes (.scn .xscn was picked as a test format).

**Comment by sanja-sa** [comment] 2016-05-19 19:34
Win 7 x64. It crashed, when you have InitialAngle: "-1.#QNAN". If I choose 0 - 360(corrected value) - it's not crashed. Maybe by default variable InitialAngle have not corrected value in Win x64 and it crashed when calculation.

**Comment by MarianoGnu** [comment] 2016-05-19 20:51
"-1.#QNAN" is an invalid value as far as i know, i had this problem with another scenes when saving this value as positions, i had to revert these values. So, this problem is not related to TextureProgress, but to (maybe) float presition parsing. What formar are you saving to? tscn?
@reduz do you have any idea of what this #QNAN means?

**Comment by MarianoGnu** [comment] 2016-05-29 17:28
there's a new report of this issue on facebook, i'll paste the link to don't lose it
https://www.facebook.com/groups/godotengine/permalink/782149935254936/

I think this issue only happens when building with certain toolchain settings, i can't reproduce it with my own build, but someone said he was having this issue until he builded the editor himself.

**Comment by akien-mga** [comment] 2016-07-27 12:09
Not critical for the upcoming 2.1, so moving to the next milestone.

**Comment by MarianoGnu** [comment] 2016-09-07 23:02
Please test it since i can't reproduce the issue

**Closed** 2016-09-07 23:01 UTC
Labels: bug, platform:windows, topic:editor

**Comment by rluis** [comment] 2016-11-06 05:13
Same problem on 2.1 stable.

**Comment by vnen** [comment] 2016-11-06 15:09
@securas this was fixed after 2.1 stable.

**Comment by securas** [comment] 2016-11-07 01:29
Got it! Thanks!
