### ISSUE TITLE
Interface going offscreen

### ISSUE THREAD

**Issue by Teashrock** [godotengine/godot#31948] opened 2019-09-04 07:15 UTC
**Godot version:**
3.2.alpha.custom_build.75cbcb596

**OS/device including version:**
Linux Mint 19.1 x64

**Issue description:**
Right docks gone offscreen when script window is opened.

**Steps to reproduce:**
1. Just open script editor and see this:
![image](https://i.imgur.com/3cUkcvS.png)

Definitely related to issue https://github.com/godotengine/godot/issues/18078. Please reopen.

**Comment by bojidar-bg** [comment] 2019-09-04 07:56
> Definitely related to issue #18078. Please reopen.

Well, if it is the same issue, you should comment on that issue instead. Since you already opened a new one, though, I think it is better to keep this one instead.

**Comment by groud** [comment] 2019-09-04 08:58
Is "3.2.alpha.custom_build.75cbcb596" the latest master ?

**Comment by KoBeWi** [comment] 2020-08-31 23:43
Can anyone still reproduce this bug in [Godot 3.2.3 rc4](https://godotengine.org/article/release-candidate-godot-3-2-3-rc-4) or any later release?

**Comment by Calinou** [comment] 2020-09-01 12:16
Duplicate of https://github.com/godotengine/godot/issues/31133.

**Closed by Calinou** 2020-09-01 12:16 UTC
Labels: bug, topic:editor
