### ISSUE TITLE
Parser and runtime error with static method accessed as member

### ISSUE THREAD

**Issue by Gnumaru** [godotengine/godot#73282] opened 2023-02-14 12:16 UTC
### Godot version

4.0.rc1

### System information

windows 10

### Issue description

When using a class_name identifier to access a static function, you cannot access it as a member (in order to get a callable or use call_deferred, for example) as if it didn't exist in the target class, you can only directly invoke it:

![Screenshot 2023-02-14 091129](https://user-images.githubusercontent.com/5783414/218735586-3851a940-d9ef-46bb-86e8-05d09902e029.png)

![Screenshot 2023-02-14 091155](https://user-images.githubusercontent.com/5783414/218735638-18be4cd6-14fd-4787-add3-d1f821133e8a.png)

The problem also occurs at runtime when trying to access the method as a member (without directly invoking).

![image](https://user-images.githubusercontent.com/5783414/218743458-c2f2a416-0841-4739-b47c-1877be15b3cf.png)

### Steps to reproduce

Create a new script on any project and put the following code on it:

```gdscript
class MyClass:
	static func myStaticFunc(): return
func test():
	var a = MyClass.myStaticFunc
	MyClass.myStaticFunc.call_deferred()
```

### Minimal reproduction project

N/A

### Remarks

I used a inner class in the example above but it makes no difference if you use a inner class, or a static method from other script, or from the same script (as long as it is accessed from the class_name identifier)

**Comment by akien-mga** [comment] 2023-02-14 12:32
Related to / possibly duplicate of #41919.

I wonder if #71644 would fix those issues @RandomShaper, or if GDScript static methods and C++ static methods are unrelated?

**Comment by dalexeev** [comment] 2023-06-09 06:20
Duplicate of #41919.

**Closed** 2023-06-09 06:48 UTC
Labels: bug, topic:gdscript
