### ISSUE TITLE
Option to open Godot Editor as maximized

### ISSUE THREAD

**Issue by aegarpyke** [godotengine/godot#370] opened 2014-05-05 03:39 UTC
(11:34:35 PM) Aegar: Also, I want Godot to start in maxed window at startup. Is there an option for that?
(11:35:31 PM) reduz: Aegar, hmm not that i know, should probably add support for maximization in the OS api for this
(11:35:57 PM) reduz: Aegar, could you add an issue about this in github? so i don't forget and look it up wheni have time

**Comment by trollworkout** [comment] 2015-07-19 03:15
i second this. i'd even suggest always starting the editor maximized or on osx in full screen (multiple workspaces)

**Comment by akien-mga** [comment] 2015-11-06 12:00
Closing as duplicate of #1218 as the latter has more activity.

**Closed by akien-mga** 2015-11-06 12:00 UTC
Labels: feature request, topic:editor, topic:porting
