### ISSUE TITLE
KinematicBody doesn't wake a sleeping RigidBody after collision

### ISSUE THREAD

**Issue by dam482** [godotengine/godot#25857] opened 2019-02-13 14:57 UTC
**Godot version:**
v3.1.beta4.mono.official

**OS/device including version:**
Windows 10

**Issue description:**
If a KinematicBody collides with a sleeping RigidBody, using the MoveAndSlide method, and the KinematicBody does NOT have infinite inertia, the sleeping RigidBody will never wake up.

Looks like this was already fixed for the case where the KinematicBody DOES have infinite inertia, with https://github.com/godotengine/godot/pull/18138

**Steps to reproduce:**

1. Load attached project into editor and run it.
2. Wait a few seconds for the red box to fall asleep.
3. Use the mouse and WASD keys to collide the player with the red box.
4. Notice the red box doesn't move at all.
5. Exit game and return to the editor, and disable the "CanSleep" property of the "Box" object.
6. Run again, and notice when the player collides with the red box, the box will now move.

**Minimal reproduction project:**
[KinematicBodyTest.zip](https://github.com/godotengine/godot/files/2860792/KinematicBodyTest.zip)

**Comment by Amssat221** [comment] 2019-02-14 23:52
We are a team working on this project for a CS class. Could we get assigned to this issue. Our uusernames are gsegovia2018,mattintriago,cniefit,amssat221

**Comment by raymoo** [comment] 2019-02-15 18:21
@Amssat221 You don't need to be assigned, just submit a pull request with the changes.

**Comment by madmiraal** [comment] 2019-10-29 11:20
This issue is highlighting something different to the one described. It's not that the `RigidBody` doesn't move after it goes to sleep. The issue is that the `RigidBody` shouldn't be moveable before it goes to sleep.

The current documentation for the `KinematicBody` [`move_and_slide()`](https://docs.godotengine.org/en/3.1/classes/class_kinematicbody.html#class-kinematicbody-method-move-and-slide) method states:

> If `infinite_inertia` is `true`, body will be able to push `RigidBody` nodes, but it won’t also detect any collisions with them. If `false` it will interact with `RigidBody` nodes like with `StaticBody`.

By setting `infinite_inertia` to `false`, the `RigidBody` is told to behave like a `StaticBody` when the `KinematicBody` `move_and_slide`s (or `move_and_collide`s) into it. This is the behaviour after the RigidBody goes to sleep. See the [Kinematic to RigidBody Interaction](http://kidscancode.org/godot_recipes/physics/kinematic_to_rigidbody/) tutorial for more information.

So the real question is: why is this `RigidBody` not behaving like a `StaticBody` when a `KinematicBody` using the `MoveAndSlide()` method with `infinite_inertia` set to `false` collides with it?

**Comment by akien-mga** [comment] 2020-01-13 14:22
Closing as duplicate of #31981.

**Closed by akien-mga** 2020-01-13 14:22 UTC
Labels: bug, topic:physics
