### ISSUE TITLE
Using print_rich on a text containing a newline wrapped in the [color] BBcode tag doesn't strip away the closing tag.

### ISSUE THREAD

**Issue by Shiva-Shadowsong** [godotengine/godot#97965] opened 2024-10-08 08:46 UTC
### Tested versions

- Reproducible in Godot v4.3.stable (bce457cec)

### System information

Godot v4.3.stable (bce457cec) - Windows 10.0.22631 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1660 SUPER (NVIDIA; 31.0.15.2802) - AMD Ryzen 5 5600X 6-Core Processor (12 Threads)

### Issue description

When using `print_rich` to print a string that contains a [color] BBcode tag - if the string wrapped in that tag contains a newline ("\n"), the closing `[/color]` tag won't be stripped away, resulting in an output where the color works, but the "[/color]" tag remains as part of the printed string.

### Steps to reproduce

1. Create a string that has a "\n" in it.
2. Wrap it in a color tag like `[color=yellow]`.
3. Output it with print_rich.

### Minimal reproduction project (MRP)

I guess there's no need to upload a whole MRP, this can be tested with 1 line of code, try it out:

```gdscript
func _ready() -> void:
	print_rich("[color=yellow]Test\ncolor tag with newline.[/color]")
```

![image](https://i.imgur.com/zyveuWq.png)

**Comment by dustdfg** [comment] 2024-10-10 07:07
Also reproducible in Godot 4.0.4

I am going to try to fix it

**Comment by dustdfg** [comment] 2024-10-10 07:38
Funny fact. It doesn't strip BBcode if it is printed into Godot Console but it is stripped when it is printed into OS console 
![screen-1728545875](https://github.com/user-attachments/assets/f1a4fe88-0d7e-40b7-bc0a-70cc47763fde)

**Comment by dustdfg** [comment] 2024-10-10 07:51
It is not only not stripped away but also isn't considered as fallback to white text which affects following text...

![screen-1728546548](https://github.com/user-attachments/assets/cc7a4453-2019-4d93-a017-20f893ab9f1b)

The os console still shows correct results:
![screen-1728546564](https://github.com/user-attachments/assets/e375b4bd-f8a0-4158-9c9b-554e733f8759)

**Comment by Calinou** [comment] 2024-10-10 13:01
> Funny fact. It doesn't strip BBcode if it is printed into Godot Console but it is stripped when it is printed into OS console

The editor Output panel uses the BBCode implementation from RichTextLabel to display it, while terminal output uses a custom BBCode-to-ANSI conversion routine that only supports a subset of BBCode and behaves differently. See https://github.com/godotengine/godot/issues/87899.

> The os console still shows correct results:

I wouldn't say it's correct behavior, it's just that the BBCode-to-ANSI conversion routine *always* replaces `[/color]` with a "reset color" tag, even if `[color]` was never opened.

**Comment by elchukc** [comment] 2024-10-10 13:37
> `print_rich()` always resets BBCode tags on every print, so you don't need to add a closing `[/color]` tag. This might be enough to avoid the issue, although we should still see if we can avoid it in the first place (as the auto-close behavior isn't obvious).
> terminal output uses a custom BBCode-to-ANSI conversion routine that only supports a subset of BBCode and behaves differently.

Likely not intended behaviour, the code inside [that custom parser](https://github.com/godotengine/godot/blob/68f053bf82ff811c7a6f870832eb4bc4d09a62e5/core/string/print_string.cpp#L132) explicitly tries to replace `[/color]`.
```
if (p_string_ansi.contains("[color")) {
	p_string_ansi = p_string_ansi.replace("[color=black]", "\u001b[30m");
	...
	p_string_ansi = p_string_ansi.replace("[/color]", "\u001b[39m");	// On this line
}
```

**Comment by dustdfg** [comment] 2024-10-10 14:18
> `print_rich()` always resets BBCode tags on every print, so you don't need to add a closing `[/color]` tag. This might be enough to avoid the issue, although we should still see if we can avoid it in the first place (as the auto-close behavior isn't obvious).

While auto-close behavior is "correct" for single color print, it isn't correct in multi color print like in my example because user will expect to see white printed in white color.

**Comment by dustdfg** [comment] 2024-10-10 14:28
> Likely not intended behaviour, the code inside [that custom parser](https://github.com/godotengine/godot/blob/68f053bf82ff811c7a6f870832eb4bc4d09a62e5/core/string/print_string.cpp#L132) explicitly tries to replace `[/color]`.
> 
> ```
> if (p_string_ansi.contains("[color")) {
> 	p_string_ansi = p_string_ansi.replace("[color=black]", "\u001b[30m");
> 	...
> 	p_string_ansi = p_string_ansi.replace("[/color]", "\u001b[39m");	// On this line
> }
> ```

Looks like it is intended. As I understand the line you pointed resets color to default when sees closing tag so it is likely normal because if color is already default nothing changes

**Comment by elchukc** [comment] 2024-10-10 17:21
> EDIT: Or you meant that it should print closing tag as is if there wasn't opening tag? If yes, I think it is too much effort to conform to the specs for such a small inconsistence

I just meant that it looks like it's trying to replace the closing tag, but somehow the closing tag is still showing in the output.

**Comment by dustdfg** [comment] 2024-10-10 17:32
> > EDIT: Or you meant that it should print closing tag as is if there wasn't opening tag? If yes, I think it is too much effort to conform to the specs for such a small inconsistence
> 
> I just meant that it looks like it's trying to replace the closing tag, but somehow the closing tag is still showing in the output.

The code that prints to os terminal is different from code that prints to godot console. And here you are viewing the code that prints to os terminal. If you will comment the line of code you commented, your is terminal will print the same result as in godot console. `"\u001b[39m"` is an escape code for terminals

**Closed** 2024-12-03 20:47 UTC
Labels: bug, confirmed, topic:gui
