### ISSUE TITLE
Vector3.INF give error

### ISSUE THREAD

**Issue by eec36** [godotengine/godot#65386] opened 2022-09-05 23:13 UTC
### Godot version

4.0 alpha 14 official

### System information

Windows 10, i5-9300H, NVIDIA GeForce GTX 1650 Mobile

### Issue description

I was trying get the code `Vector3.INF` to work for catching logic errors. but it won't.
And I don't why the documentation showing me code that don't work like `Vector3(inf, inf, inf)`.
So I have to manually change to `Vector3(INF, INF, INF)` to get it to work,

![INF](https://user-images.githubusercontent.com/99343051/188518955-63e2c1f5-fcea-4fd8-ae7e-769bc171fb93.png)
![aaa](https://user-images.githubusercontent.com/99343051/188519194-3837ec3e-f3bd-4678-962c-a2a9d7e5c976.png)

### Steps to reproduce

Try to use `Vector3.INF` in any GDScript code and you will get error.
And also `Vector3(inf, inf, inf)`.

**Comment by jgillich** [comment] 2022-09-05 23:42
Duplicate of #45139

**Closed** 2022-09-06 00:02 UTC
