### ISSUE TITLE
AnimationPlayer.play_backwards() calls keyframe methods twice

### ISSUE THREAD

**Issue by paulmiller** [godotengine/godot#88928] opened 2024-02-27 18:22 UTC
### Tested versions

reproduced in 4.2.1.stable
not reproduced in 3.5.3.stable, 4.0.4.stable, 4.1.3.stable

### System information

Godot v4.2.1.stable unknown - Arch Linux #1 SMP PREEMPT_DYNAMIC Fri, 05 Jan 2024 16:20:41 +0000 - Tty - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1070 (nvidia; 545.29.06) - Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 Threads)

### Issue description

Animations with "Call Method" tracks work normally when playing forward, but when playing backwards, a single method keyframe results in 2 method calls.

### Steps to reproduce

Run the attached project. The buttons in the top left call `play()` and `play_backwards()`:

```gdscript
func hello():
  print("hello")

func play():
  print("play")
  $AnimationPlayer.play("blah")

func play_backwards():
  print("play_backwards")
  $AnimationPlayer.play_backwards("blah")
```

The `"blah"` animation spins the sprite and calls `hello()` once. When playing forward, Godot prints:
```
play
hello
```
But backwards:
```
play_backwards
hello
hello
```

### Minimal reproduction project (MRP)

[animation-callback-test.zip](https://github.com/godotengine/godot/files/14423656/animation-callback-test.zip)

**Comment by TokageItLab** [comment] 2024-02-28 10:37
Dupe of #86147, Already fixed by #86227 in 4.2.2.

**Closed by TokageItLab** 2024-02-28 10:37 UTC
