### ISSUE TITLE
Transform2D in conjunction with AnimationPlayer: Flipping X axis flips Y axis instead

### ISSUE THREAD

**Issue by SaffronStreams** [godotengine/godot#34507] opened 2019-12-21 10:58 UTC
I'm using Godot 3.2.beta4 on Windows 10 Home, but opening the project in 3.1 stable seems to give the same problem. I am presuming this is an issue and not expected behavior.

I'm running into a problem in the context of trying out making a cutscene.

I have a KinematicBody2D with an internal AnimationPlayer for animation. In my World node I have another AnimationPlayer where I take the KinematicBody2D node and animate its position, while also calling two functions.

The problem seems to lie in the function that does a Transform2D on the node. Both using the Vectors in the image below 

![3](https://user-images.githubusercontent.com/50481103/71307008-8d67db00-23e8-11ea-9a02-0fac9a47cb25.png)

or the Transform2D.FLIP_X flip my character on the Y axis instead of the X axis. 

![1](https://user-images.githubusercontent.com/50481103/71307016-9c4e8d80-23e8-11ea-953c-4c669c0dc254.png)

When I do not activate this animation, but use player controls to call the Transform, both normally on the X axis. 

![2](https://user-images.githubusercontent.com/50481103/71307040-0cf5aa00-23e9-11ea-8219-de8c117e2f38.png)

**Comment by aaronfranke** [comment] 2019-12-22 08:44
What do you get if you print out the object's Transform2D after it is applied?

**Comment by SaffronStreams** [comment] 2019-12-22 10:54
In both instances a print(str(get_transform)) returns (-0.5, 0) and (0,0.5) for the x and y followed by the offset (230 something, 650 something, as expected).

**Comment by tom-jk** [comment] 2020-07-20 20:39
I'm trying to reproduce this on 3.2.2.stable, 3.1.2.stable or 3.2.stable but I must be missing something or the description is incomplete because everything's behaving.

This project is my best shot, if it's of interest: [34507.zip](https://github.com/godotengine/godot/files/4949972/34507.zip)

@SaffronStreams can you still reproduce this issue, and could you supply a minimal reproduction project if so?

**Comment by akien-mga** [comment] 2021-04-28 13:19
No answer, so closing. Please comment if you can still reproduce the issue in Godot 3.3 or later.

**Closed by akien-mga** 2021-04-28 13:19 UTC
Labels: bug, topic:core
