### ISSUE TITLE
Silent crash when reloading/unloading ParallaxBackground

### ISSUE THREAD

**Issue by cbscribe** [godotengine/godot#72735] opened 2023-02-04 21:27 UTC
### Godot version

4.0 beta 17

### System information

MacOS 12.4, Windows 11

### Issue description

Reloading/unloading scenes containing a ParallaxBackground causes a silent crash.

A previously working project just started crashing regularly after updating to beta 17. It would crash when changing levels (scenes) or when closing the game window. After a bit of troubleshooting, I reduced the game scene down to nothing but the player (with attached camera) and a ParallaxBackground.

No messages appear in the console log when run from the command line. Problem doesn't occur on beta 16.

### Steps to reproduce

Attached is a minimum project with one scene containing a moving Camera2D and a ParallaxBackground. Run the scene and press the Button, which triggers `get_tree().reload_current_scene()`. The game crashes.

If you remove the ParallaxBackground node, pressing the Button reloads the scene with no error.

### Minimal reproduction project

[crash_test.zip](https://github.com/godotengine/godot/files/10609691/crash_test.zip)

**Comment by KoBeWi** [comment] 2023-02-04 21:42
Duplicate of #72610

**Closed by KoBeWi** 2023-02-04 21:42 UTC
