### ISSUE TITLE
Documentation from ## comments are not generating properly in addon

### ISSUE THREAD

**Issue by BenjaTK** [godotengine/godot#94765] opened 2024-07-26 01:26 UTC
### Tested versions

- 4.2.2.stable

### System information

Godot v4.2.2.stable - Pop!_OS 22.04 LTS - X11 - Vulkan (Forward+) - dedicated AMD Radeon RX 6600 (RADV NAVI23) () - Intel(R) Core(TM) i3-9100F CPU @ 3.60GHz (4 Threads)

### Issue description

I have an [addon](https://github.com/BenjaTK/Gaea) in which I've added documentation to scripts by using ## comments. The problem is, these aren't showing up when hovering on properties or searching docs. They used to, but they suddenly stopped working. And it's not only for me, but also other users with the addon.

Sometimes I can get them to appear on a individual class by updating the comments (like removing a character), but other times not only this fixes it.

### Steps to reproduce

- Download mrp.zip and open the project in 4.2.2-stable.
- Open `test_scene.tscn`. Go to the HeightmapGenerator2D node and hover over any properties. You'll see that you can see their documentation.
- Reload the project and try again. They don't work now.

The problem seems to be in .godot/, as removing the folder fixes it until the next reload.

### Minimal reproduction project (MRP)

[mrp.zip](https://github.com/user-attachments/files/16385459/mrp.zip)

**Comment by Gearhartlove** [comment] 2024-07-27 14:07
When you say "they suddenly stopped working", do you mean they stopped working when you switched to 4.2.2-stable? If so what version were you on before. I'm curious if I can spot the regression between versions.

**Comment by dalexeev** [comment] 2024-07-27 15:05
Related to / duplicate of:

* #72406
* #86577

**Comment by BenjaTK** [comment] 2024-07-27 21:18
> When you say "they suddenly stopped working", do you mean they stopped working when you switched to 4.2.2-stable? If so what version were you on before. I'm curious if I can spot the regression between versions.

This happened before 4.2.2-stable, but I'm not so sure when and can't check, sorry. I HAVE noticed a pattern which is resources NEVER have documentation for their parent classes in dropdown menus. 
So for example, let's say I have a Resource called `TestResource`: This resource has a property called `property1`. It has a description.
Then, let's say we have another resource that extends `TestResource` called `SubTestResource`, and this one also has a property of its own called `property2`.
When looking at it from this kind of dropdown menu:
![image](https://github.com/user-attachments/assets/2d03a0f0-2449-49fe-9bc9-8e1113279873)
...after deleting .godot then reloading the project, you can read the documentation for `property2` but not for `property1`. After reloading the project again, you can't read neither.

**Comment by BenjaTK** [comment] 2024-07-27 21:20
The previously mentioned things still happen for custom nodes but after deleting .godot they will show their parent classes properties' description.

**Comment by BenjaTK** [comment] 2024-07-27 21:21
If you want me to copy this information over to #72406 please let me know.

**Comment by dalexeev** [comment] 2024-08-08 14:21
Thanks for reporting the bug, consolidating in #72406 / #86577.

**Closed by dalexeev** 2024-08-08 14:21 UTC
Labels: bug, topic:gdscript, topic:plugin
