### ISSUE TITLE
Steam build of Godot engine will crash if left alone for a long time

### ISSUE THREAD

**Issue by deanrih** [godotengine/godot#79234] opened 2023-07-09 09:08 UTC
### Godot version

Steam (tested on 3.5, 4.0 and 4.1)

### System information

Manjaro Linux - Kernel 6.3.5 - v4.1.stable.official [970459615] - Forward+

### Issue description

The Steam version of Godot has some bug that if I leave it alone (idling) long enough (the Editor itself requires more time but the Project Selection screen only needs around 30 minutes) it will just crash/close itself. It happened both by running through Steam or executing the binary directly. The binary downloaded directly from the website does not have this problem.

When I try to run the Steam build directly from the terminal to see the log, here is what I get, the command is

```sh
/path/to/steam/godot/godot.x11.opt.tools.64 | ts '[%Y-%m-%d %H:%M:%S]'
```
`ts` here is a command from `moreutils` to append/prepend a timestamp to the log output so I know how long Godot is running before it crashes, well, I only get the timestamp when it was executed, luckily I was in front of my computer so I can calculate the difference, here's the log:

```sh
[2023-07-09 15:14:44] Godot Engine v4.1.stable.official.970459615 - https://godotengine.org
[2023-07-09 15:14:45] OpenGL API 3.3.0 NVIDIA 530.41.03 - Compatibility - Using Device: NVIDIA - NVIDIA GeForce RTX 2060
[2023-07-09 15:14:45]
[xcb] Unknown sequence number while processing queue
[xcb] You called XInitThreads, this is not your fault
[xcb] Aborting, sorry about that.
godot.x11.opt.tools.64: xcb_io.c:278: poll_for_event: Assertion `!xcb_xlib_threads_sequence_lost' failed.
zsh: IOT instruction (core dumped)   |
zsh: done                           ts '[%Y-%m-%d %H:%M:%S]'
```

### Steps to reproduce

1. Install Godot from Steam
2. Run Godot
3. Leave the Project Selection and do nothing with it
4. Wait for some time, at least 30 minutes
5. Godot somehow suddenly close itself

### Minimal reproduction project

N/A

**Comment by RedworkDE** [comment] 2023-07-09 09:29
Duplicate of https://github.com/godotengine/godot/issues/75308

**Closed by RedworkDE** 2023-07-09 09:29 UTC
