### ISSUE TITLE
Build command always return code 0 despite failing in linux

### ISSUE THREAD

**Issue by leandro-benedet-garcia** [godotengine/godot#85349] opened 2023-11-25 15:26 UTC
### Godot version

https://godotengine.org/download/archive/4.1.2-stable/

### System information

github actions server, ubuntu image

### Issue description

I noticed that despite the build failing, this command:

```sh
$GODOT_EXECUTABLE --export-release --headless ${build} || die "Failed to create ${build} build"
```
The command `die` never executes, which means the engine is returning code 0, which means success, and that's not what it should happen.

### Steps to reproduce

1. Create a project that should fail on build
2. Execute a command, let's say `$GODOT_EXECUTABLE --export-release --headless "Android"
3. Then execute `echo $?` to display the error code, it will always be `0`

### Minimal reproduction project

N/A

**Comment by akien-mga** [comment] 2023-11-26 12:13
Duplicate of #83042, consolidating there.

**Closed by akien-mga** 2023-11-26 12:13 UTC
