### ISSUE TITLE
GDScript 2.0 - crash when on invalid expression

### ISSUE THREAD

**Issue by fabriceci** [godotengine/godot#51140] opened 2021-08-01 10:29 UTC
### Godot version

v4.0 #20d46c5

### System information

MacOS 11.4

### Issue description

Godot crash when you save an invalid expression expression in the editor

### Steps to reproduce

Enter on of those expressions and save:

```python
print(-)
if not :

```

**Comment by timothyqiu** [comment] 2021-08-01 10:32
I think this is a duplicate of #49628.

**Comment by fabriceci** [comment] 2021-08-01 10:43
@timothyqiu Yes it seems but the stack trace is different, should I add my examples to the similar issue?

```
[1] 1   libsystem_platform.dylib            0x00007fff204e0d7d _sigtramp + 29
[2] 2   ???                                 0x000000011aa72000 0x0 + 4742127616
[3] GDScriptCompiler::_parse_expression(GDScriptCompiler::CodeGen&, Error&, GDScriptParser::ExpressionNode const*, bool, bool, GDScriptCodeGenerator::Address const&) (in godot.osx.tools.x86_64) (gdscript_compiler.cpp:721)
[4] GDScriptCompiler::_parse_expression(GDScriptCompiler::CodeGen&, Error&, GDScriptParser::ExpressionNode const*, bool, bool, GDScriptCodeGenerator::Address const&) (in godot.osx.tools.x86_64) (gdscript_compiler.cpp:480)
[5] GDScriptCompiler::_parse_block(GDScriptCompiler::CodeGen&, GDScriptParser::SuiteNode const*, bool) (in godot.osx.tools.x86_64) (gdscript_compiler.cpp:1832)
[6] GDScriptCompiler::_parse_block(GDScriptCompiler::CodeGen&, GDScriptParser::SuiteNode const*, bool) (in godot.osx.tools.x86_64) (gdscript_compiler.cpp:1650)
[7] GDScriptCompiler::_parse_function(Error&, GDScript*, GDScriptParser::ClassNode const*, GDScriptParser::FunctionNode const*, bool, bool) (in godot.osx.tools.x86_64) (gdscript_compiler.cpp:1982)
[8] GDScriptCompiler::_parse_class_blocks(GDScript*, GDScriptParser::ClassNode const*, bool) (in godot.osx.tools.x86_64) (gdscript_compiler.cpp:2455)
[9] GDScriptCompiler::compile(GDScriptParser const*, GDScript*, bool) (in godot.osx.tools.x86_64) (gdscript_compiler.cpp:2623)
[10] GDScript::reload(bool) (in godot.osx.tools.x86_64) (gdscript.cpp:846)
```

**Comment by timothyqiu** [comment] 2021-08-01 10:58
@fabriceci I just tested your snippet and the two in #49628, they all crash at the same line.

The line number in their posted stack trace is different from yours maybe because code changed in that file.

But feel free to post your snippet in that issue :)

**Closed** 2021-08-01 10:59 UTC
Labels: bug, crash, topic:gdscript
