### ISSUE TITLE
Suggestion on key frames for sprites

### ISSUE THREAD

**Issue by ondesic** [godotengine/godot#8305] opened 2017-04-07 14:07 UTC
**Operating system or device - Godot version:**
Win 10

**Issue description:**

It took me a while to realize the power of the AnimationPlayer.  The thing that threw me off is that the property "Frame" only has a key with a "+" next to it.  Godot should also have a normal key next to frame. That way you can advance to the frame you want in the inspector and then just add that.

**Steps to reproduce:**

**Link to minimal example project:**

**Comment by bojidar-bg** [comment] 2017-04-07 14:29
Duplicate of #4152?

**Comment by ondesic** [comment] 2017-04-07 14:52
Just noticed that after posting but didn't see any feedback to the idea.  Sorry.

**Comment by bojidar-bg** [comment] 2017-04-07 15:11
Ok, closing as duplicate ( of #4152 ) :smiley:

**Closed by bojidar-bg** 2017-04-07 15:11 UTC
