### ISSUE TITLE
Alsa driver initialization fails on Arch Linux

### ISSUE THREAD

**Issue by anark10n** [godotengine/godot#24972] opened 2019-01-13 19:53 UTC
**Godot version:**
Godot v3.0.6

**OS/device including version:**
Arch Linux 4.20.0-arch1-1-ARCH

**Issue description:**
Distored and scratchy sound when running a project file. Error message:

> ERROR: init_device: Condition ' status < 0 ' is true. returned: ERR_CANT_OPEN
   At: drivers/alsa/audio_driver_alsa.cpp:80.
ERROR: initialize: AudioDriverManager: all drivers failed, falling back to dummy driver
   At: servers/audio_server.cpp:165.

**Steps to reproduce:**
Created a normal project following a tutorial (no longer available)

**Minimal reproduction project:**
[Project link](https://www.dropbox.com/s/8bp63i8eboifxyy/UFO.zip?dl=0)
Just open and run.
[Recording](https://www.dropbox.com/s/y56gwi2xb9sahzm/game_playback.mp4?dl=0) while the game is running.
[Recording](https://www.dropbox.com/s/2kyvpxjqq3k7420/media_player_playback.mp4?dl=0) when played from another media player.

**Comment by bojidar-bg** [comment] 2019-01-14 11:16
Does it also happen with pulseaudio?

**Comment by anark10n** [comment] 2019-01-14 16:07
@bojidar-bg 
Changing the audio driver to pulseaduio returns:
> Invalid Audio Driver: PulseAudio
I'm using the alsa version from the AUR.

**Comment by bojidar-bg** [comment] 2019-01-15 11:19
Why was this closed? If Alsa doesn't work, it should be fixed, not swept under the rug :smiley:

**Comment by anark10n** [comment] 2019-01-16 17:22
Right, my bad.

**Comment by groud** [comment] 2019-01-16 19:13
Did you test with 3.1?

**Comment by anark10n** [comment] 2019-01-20 12:08
Well, now everything is just weird. I uninstalled pulseaudio-alsa and rebuilt godot 3.0.6 with pulseaudio=no, and I didn't get the error anymore. Figured trying this out after running some apps that prevented pulseaudio apps from playing sound. So, i reinstalled pulseaudio-alsa to see if I get the error messages with godot 3.1 with pulseaudio=no, and no error messages any more, as well as for godot 3.0.6. So, now i don't know what to make of this.

**Comment by akien-mga** [comment] 2019-01-21 14:21
It sounds like your Alsa setup was misbehaving somehow, and the various tests you did fixed it. The original error message is expected if there's a problem initializing Alsa, so I guess it works as it should.

**Closed by akien-mga** 2019-01-21 14:21 UTC
Labels: bug, platform:linuxbsd, topic:audio

**Comment by lucassene** [comment] 2021-07-30 15:29
I'm getting the exact same error too. There is no sound when playing the game, everything else works fine.
I'm on Windows and exported to Linux.
Where do I change this setting "pulseaudio"?

**Comment by Calinou** [comment] 2021-07-30 15:47
> I'm getting the exact same error too. There is no sound when playing the game, everything else works fine.
> I'm on Windows and exported to Linux. I'm using 3.3.1 stable.
> Where do I change this setting "pulseaudio"?

Which Linux distribution are you using? Do you use a PulseAudio or ALSA setup on your machine? (PipeWire supports PulseAudio natively, so you don't need to do anything specific if using PipeWire.)

You can override the audio driver used by passing the `--audio-driver PulseAudio`/`--audio-driver ALSA` command line argument to the exported project. Try both and see if either of those work.

**Comment by lucassene** [comment] 2021-07-30 15:57
> 
> Which Linux distribution are you using? Do you use a PulseAudio or ALSA setup on your machine? (PipeWire supports PulseAudio natively, so you don't need to do anything specific if using PipeWire.)
> 
> You can override the audio driver used by passing the `--audio-driver PulseAudio`/`--audio-driver ALSA` command line argument to the exported project. Try both and see if either of those work. Official export templates contain both the PulseAudio and ALSA drivers, with PulseAudio used by default unless the audio driver is set to `ALSA` in the Project Settings.

I'm not using Linux, I'm on Windows, exporting to Linux via official export templates. A friend of mine is testing the game on Linux. He sent me the debug console with the following errors:
[https://i.ibb.co/Hh8G2Yq/ndice.jpg](https://i.ibb.co/Hh8G2Yq/ndice.jpg)

I'll try exporting with those arguments tho.

**Comment by akien-mga** [comment] 2021-07-30 16:02
They're running the game with `sudo`, i.e. as super user / administrator. The administrator typically doesn't have an audio system set up.

They should just run the game as their normal user which has a working audio setup.

**Comment by Calinou** [comment] 2021-07-30 17:28
> They're running the game with sudo, i.e. as super user / administrator. The administrator typically doesn't have an audio system set up.

I'd probably print a warning message if a Godot project/editor was started with `sudo`.

**Comment by lucassene** [comment] 2021-07-31 16:27
> 
> 
> They're running the game with `sudo`, i.e. as super user / administrator. The administrator typically doesn't have an audio system set up.
> 
> They should just run the game as their normal user which has a working audio setup.

That was exactly the cause of the problem. When running as a normal user, the audio worked normally. Thanks!
