### ISSUE TITLE
Import/Re-import 3D scene does not show new changes

### ISSUE THREAD

**Issue by Ace-Dragon** [godotengine/godot#2235] opened 2015-07-04 19:58 UTC
*Bugsquad edit:* Seen in Godot 1.2 June 29 dev. build

Confirmed on a Win64 dev. build done using MingW 64bit on the 29th of June.

To reproduce, open an established 3D scene and try to import a new version of it (or re-import). It will appear as if the importer has done nothing as you will still find the scene and the node tree looking exactly the same.

However, going back to Godot 1.1 official and opening the scene there shows the updated geometry and node tree just fine, which might make sense since the dev. build showed no errors in the console relating to the actual importing.

System; Win7 64 bit with an ATI 7xxx GPU/

**Comment by akien-mga** [comment] 2015-11-11 10:33
I believe this is a duplicate of #2307.

**Closed by akien-mga** 2015-11-11 10:33 UTC
Labels: archived
