### ISSUE TITLE
Poor performance of node finder dialog box?

### ISSUE THREAD

**Issue by Torguen** [godotengine/godot#70895] opened 2023-01-03 20:40 UTC
### Godot version

v3.5.2.rc1.official [f5f0543ae]

### System information

w10 64

### Issue description

I have quite a few custom classes that use "class_name xxx".
It seems that the add node dialog has become very slow and even hard to type a node name. The add node box takes a long time to display the nodes.

Could this be improved to make it more efficient somehow?

In the video you can see that the dialog box that shows the nodes becomes slow and the CPU consumption increases.

Is this normal? Could it be improved?

https://youtu.be/HkPBJnLp1LA

### Steps to reproduce

...

### Minimal reproduction project

...

**Comment by KoBeWi** [comment] 2023-01-03 21:24
Duplicate of #27333

**Closed by KoBeWi** 2023-01-03 21:24 UTC

**Comment by Torguen** [comment] 2023-01-04 11:43
What does it mean that the problem "is not planned"?.
