### ISSUE TITLE
Big list of  animations doesn't scroll down

### ISSUE THREAD

**Issue by heavyathan** [godotengine/godot#76706] opened 2023-05-03 17:47 UTC
### Godot version

3.5.2

### System information

Windows 10, GLES2, GPU [AMD Radeon R7 M260](https://www.techpowerup.com/gpu-specs/radeon-r7-m260.c2591)

### Issue description

Very often (not always), when in AnimationPlayer Editor, if animation list is bigger than the screen, editor doesn't allow to scroll down to the bottom animations. Also, edit properties tab on the right, where current animation can be chosen happens the same.

Happens in 3.5.x and in 3.6 beta1

https://user-images.githubusercontent.com/100681249/235996049-22bd1c38-a3d5-4577-bafc-a990fb2d12dd.mp4

### Steps to reproduce

Load a model with a bunch of animations in different ways (inherit scene, open normally, drag,...) an there is a moment where the animation list stops scrolling.
In attached MRP, 4 of 5 times happen only opening it.

### Minimal reproduction project

[Scrolling.zip](https://github.com/godotengine/godot/files/11388626/Scrolling.zip)

**Comment by heavyathan** [comment] 2023-05-03 18:46
Side notes: 
-Godot 4 stable and 4.1 dev1 works fine.
-version 3.4.x and previous with same example worked fine.
-Rest of scrollable lists work fine.
-Maybe unrelated, but when trying to navigate in the tracks, GPU reach 100% and even the editor FPS fluctuates and down to 3-8 fps.

**Comment by Calinou** [comment] 2023-05-03 18:48
> -Maybe unrelated, but when trying to navigate in the tracks, GPU reach 100% and even the editor FPS fluctuates and fall to 3-8 fps.

You have a lot of tracks visible, which is quite a lot of strain even if it's just 2D rendering on a not-so-fast GPU.

**Comment by KoBeWi** [comment] 2023-05-03 19:03
Duplicate of #76289

**Closed by KoBeWi** 2023-05-03 19:03 UTC
Labels: bug, topic:editor, usability, regression, topic:animation
