### ISSUE TITLE
Enable type hinting on signal signatures

### ISSUE THREAD

**Issue by mauricio-fidalgo** [godotengine/godot#28856] opened 2019-05-13 17:37 UTC
**Godot version:**
3.1

**OS/device including version:**
All

**Issue description:**
Signal signatures should accept type hinting for better reading/usability,
example:

```
signal  something_finished(something: Area2D)
```

**Comment by vnen** [comment] 2019-05-13 23:58
Duplicate of #26045

**Closed by vnen** 2019-05-13 23:58 UTC
