### ISSUE TITLE
2D Sprite Mesh Deform / FFD [FeatureReq]

### ISSUE THREAD

**Issue by meem40** [godotengine/godot#6318] opened 2016-08-28 18:10 UTC
Godot already has good IK bone tool, which is great but most of the new gen mobile games uses FFD to morph bone sprites which gives the animation life like quality. Is there a future plan to add engine feature for 2D FFD for sprites or support for such animator format(json) like DragonBone(Open Source, Great Quality) ?

**Comment by vnen** [comment] 2016-08-28 18:48
Duplicate of #2914. 2D Mesh deform is planned for version 3.0.

**Closed by vnen** 2016-08-28 18:48 UTC

**Comment by RandomShaper** [comment] 2016-08-28 23:49
I'm working on _MessDeform_:
![with_mess_deform](https://cloud.githubusercontent.com/assets/11797174/18037526/14f61058-6d87-11e6-8c79-3eae2703993a.gif)

I've posted the whole announcement at [https://godotengine.org/qa/7487/messdeform-hacky-deformable-mesh-engine-for-godot](Godot Q&A).
