### ISSUE TITLE
obj from blender import to godot get wrong material count

### ISSUE THREAD

**Issue by imdjs** [godotengine/godot#51777] opened 2021-08-17 03:56 UTC
### Godot version

godot 3.2 stable

### System information

nvidia gtx 670

### Issue description

I use blender to export a multi-materail as obj ,which has two materials,  but when I import to godot It gets three  materials slot.
obj file:
[https://1drv.ms/u/s!AsZIVWqD15n6wRXnC1LCgj9Y1fAm?e=EW0cuf](url)
screenshot:
[![godot-error-materials.jpg](https://i.postimg.cc/NMJYY1CF/godot-error-materials.jpg)](https://postimg.cc/8J6xmrSg)

### Steps to reproduce

```
# Blender v2.93.2 Release Candidate OBJ File: ''
# www.blender.org
mtllib export.mtl
o plane
v -11.383945 0.000000 11.383945
v 11.383945 0.000000 11.383945
v -11.383945 0.000000 -11.383945
v 11.383945 0.000000 -11.383945
v -11.383945 10.810699 11.383945
v 11.383945 10.810699 11.383945
v -11.383945 10.810699 -11.383945
v 11.383945 10.810699 -11.383945
vt 0.000000 0.000000
vt 0.000000 1.000000
vt 1.000000 1.000000
vt 1.000000 0.000000
vt 0.000000 0.000000
vt 1.000000 0.000000
vt 1.000000 1.000000
vt 0.000000 1.000000
vn 0.0000 -1.0000 0.0000
vn 0.0000 1.0000 0.0000
vn 0.0000 0.0000 -1.0000
vn 1.0000 0.0000 0.0000
vn -1.0000 0.0000 0.0000
usemtl 2
s off
f 1/1/1 3/2/1 4/3/1 2/4/1
usemtl 1
f 5/5/2 6/6/2 8/7/2 7/8/2
usemtl 2
f 4/3/3 3/2/3 7/8/3 8/7/3
f 2/4/4 4/3/4 8/7/4 6/6/4
f 3/2/5 1/1/5 5/5/5 7/8/5
```

_Bugsquad edit:_ fix formatting

**Comment by timothyqiu** [comment] 2021-08-17 04:42
The "Material" section displays the material for each internal surface. So three entries there means there are three _surfaces_, not three materials.

If you import the `obj` file together with `export.mtl`, only two materials will be created and the three slots will be filled correctly. i.e., the first and the third surface will share material 2.

That section name is indeed quite confusing 😂

**Comment by imdjs** [comment] 2021-08-17 06:10
> 
> 
> The "Material" section displays the material for each internal surface. So three entries there means there are three _surfaces_, not three materials.
> 
> If you import the `obj` file together with `export.mtl`, only two materials will be created and the three slots will be filled correctly. i.e., the first and the third surface will share material 2.
> 
> That section name is indeed quite confusing 😂

most of obj file from web ,don't have .mtl file along with the .obj file.

**Comment by prominentdetail** [comment] 2023-04-19 00:58
Yeah, seems like godot isn't importing .obj files correctly. It creates multiple duplicate surfaces

in the obj format specs it says:


    usemtl material_name
    
    Polygonal and free-form geometry statement.

    Specifies the material name for the element following it. Once a
    material is assigned, it cannot be turned off; it can only be
    changed.

    material_name is the name of the material. If a material name is
    not specified, a white material is used.

So in the following, it should simply define which faces use which material. I don't see why it should define the number of surfaces, but maybe someone knows more? 

```
g Scene
usemtl 0
f 1/1/1 3/2/2 2/3/3
f 1/4/4 4/5/5 3/6/6
usemtl 1
f 5/7/7 6/8/8 7/9/9
f 5/10/10 8/11/11 6/12/12
usemtl 2
f 9/13/13 10/14/14 11/15/15
f 9/16/16 12/17/17 10/18/18
usemtl 3
f 13/19/19 14/20/20 15/21/21
f 13/22/22 16/23/23 14/24/24
usemtl 0
f 17/25/25 18/26/26 19/27/27
f 17/28/28 20/29/29 18/30/30
usemtl 1
f 21/31/31 22/32/32 23/33/33
f 21/34/34 24/35/35 22/36/36
f 25/37/37 26/38/38 27/39/39
f 25/40/40 28/41/41 26/42/42
usemtl 2
f 29/43/43 30/44/44 31/45/45
f 29/46/46 32/47/47 30/48/48
f 33/49/49 34/50/50 35/51/51
f 33/52/52 36/53/53 34/54/54
usemtl 3
f 37/55/55 38/56/56 39/57/57
f 37/58/58 40/59/59 38/60/60
```

If you import this .obj, you can see you get 8 surfaces in the material instead of 4.

[test.zip](https://github.com/godotengine/godot/files/11267407/test.zip)

**Comment by CahootsMalone** [comment] 2024-02-27 03:12
This issue appears to be a duplicate of [Godot making duplicate material slots on OBJ import](https://github.com/godotengine/godot/issues/43956) (or is at least related to it).

**Closed** 2024-02-27 10:07 UTC
Labels: bug, topic:import, topic:3d
