### ISSUE TITLE
Error count in the bottom panel is not always updated

### ISSUE THREAD

**Issue by miv391** [godotengine/godot#58979] opened 2022-03-10 11:21 UTC
### Godot version

v4.0.alpha4.official [f47097973]

### System information

Windows 10

### Issue description

Clearing errors in the Debugger/Errors view does not always clear the error count from the bottom panel's Debugger. This happens only if the game is not running. If the errors are cleared while the game is running, the error count in the bottom panel is updated correctly.

![kuva](https://user-images.githubusercontent.com/49998025/157651098-681c14d3-b9c6-4676-b324-81d7406117b1.png)

### Steps to reproduce

1. Run a game that produces errors.
2. Stop the game.
3. Click the "Clear" button in Debugger/Errors view.
4. Error list is now empty but bottom panel still has an error count.

**Comment by akien-mga** [comment] 2022-03-10 11:47
Duplicate of #54451

**Closed by akien-mga** 2022-03-10 11:47 UTC
