### ISSUE TITLE
Vulkan: Editor freezes when system wakes up from sleep

### ISSUE THREAD

**Issue by hmans** [godotengine/godot#52738] opened 2021-09-16 06:58 UTC
___

***Bugsquad note:** This issue has been confirmed several times already. No need to confirm it further.*

___

### Godot version

4.0.dev (5179124f)

### System information

Linux 5.13.13, Ryzen 5800X, GTX 1060, Vulkan

### Issue description

When my Linux system goes to sleep and later wakes up, any currently running Godot 4.0.dev editors are completely frozen, and I need to `kill -9` their processes.

### Steps to reproduce

- Start the editor with any project
- Put the system to sleep
- Wake the system up from sleep
- Godot editor is now entirely frozen

**Comment by Calinou** [comment] 2021-09-16 07:04
@hmans Can you reproduce this with Godot 3.3.3?

**Comment by hmans** [comment] 2021-09-16 07:15
3.3.3 doesn't freeze, but seems to get confused about materials (the cube that I've added to the scene is completely black.) Closing and re-opening the scene does not fix it, but restarting the editor obviously does.

![image](https://user-images.githubusercontent.com/1061/133566931-2de13e30-0720-4736-a684-c47e73df4292.png)

**Comment by fwsGonzo** [comment] 2021-12-03 09:52
I can confirm that this still happens on latest. I am on Linux Mint with amd64 Linux 5.13.

I don't know why the issue says that the editor freezes when it clearly doesn't. It just fails to render new dialogues.
Other GPU applications do not necessarily have this problem, and it's not a driver issue. It's likely a windowing thing.

**Comment by Calinou** [comment] 2021-12-03 11:02
> I can confirm that this still happens on latest. I am on Linux Mint with amd64 Linux 5.13.

Which version do you refer by "latest"? The `master` branch uses an entirely different windowing system than `3.x` (with multi-window support, unless single window mode is enforced in the Editor Settings).

Does the issue go away if you resize the window?

**Comment by DragonAxe** [comment] 2022-01-26 11:16
I am also experiencing this issue with the recently released godot 4 alpha build:

Godot Engine v4.0.alpha1.official.31a7ddbf8
Linux 5.15.16-1-MANJARO x86_64; GNOME Shell 41.3
Vulkan API 1.2.202 - Using Vulkan Device #0: NVIDIA - NVIDIA GeForce MX150

Godot Engine v3.4.2.stable.official.45eaa2daf does not have the same problem for me and I haven't noticed any material problems like the one @hmans mentioned.

As @fwsGonzo said, the editor still responds to mouse clicks, but the window shows a ghost of the last rendered content.
Also, a project does not need to be opened (stay at project manager window) before sleeping/resuming breaks godot's window rendering.

Running from the terminal shows lots of these errors whenever a re-render event is triggered (such as resizing the window or hovering over components inside):
```
ERROR: Condition "err" is true. Returning: ERR_CANT_CREATE
   at: swap_buffers (drivers/vulkan/vulkan_context.cpp:1956)
ERROR: Vulkan: Did not create swapchain successfully.
   at: prepare_buffers (drivers/vulkan/vulkan_context.cpp:1880)
```

I also saw this error in one of my tests, but it may not be related.
```
ERROR: Condition "!material" is true.
   at: material_set_shader (servers/rendering/renderer_rd/renderer_storage_rd.cpp:1570)
```

Lspci shows:
```
01:00.0 3D controller: NVIDIA Corporation GP108M [GeForce MX150] (rev a1)
        Subsystem: Lenovo ThinkPad T480
        Flags: bus master, fast devsel, latency 0, IRQ 159
        Memory at dc000000 (32-bit, non-prefetchable) [size=16M]
        Memory at 80000000 (64-bit, prefetchable) [size=256M]
        Memory at 90000000 (64-bit, prefetchable) [size=32M]
        I/O ports at d000 [size=128]
        Capabilities: [60] Power Management version 3
        Capabilities: [68] MSI: Enable+ Count=1/1 Maskable- 64bit+
        Capabilities: [78] Express Endpoint, MSI 00
        Capabilities: [100] Virtual Channel
        Capabilities: [250] Latency Tolerance Reporting
        Capabilities: [258] L1 PM Substates
        Capabilities: [128] Power Budgeting <?>
        Capabilities: [420] Advanced Error Reporting
        Capabilities: [600] Vendor Specific Information: ID=0001 Rev=1 Len=024 <?>
        Capabilities: [900] Secondary PCI Express
        Kernel driver in use: nvidia
        Kernel modules: nouveau, nvidia_drm, nvidia
```

**Comment by alex9099** [comment] 2022-04-27 21:26
Can reproduce with 4.0 alpha 6 on a laptop with linux 5.17.3-arch1-1, driver nvidia 510.60.02 with a nvidia geforce gtx 1060

This is a prime setup (nvidia is not the display gpu), not sure if that changes anything

**Comment by mdlsvensson** [comment] 2022-05-08 14:59
Happens to me as well. NVIDIA GeForce GT 1030/PCIe/SSE2. On manjaro linux

**Comment by DragonAxe** [comment] 2022-08-18 05:20
I am no longer experiencing the issue with Godot v4.0.alpha14.official [106b68050].

**Comment by Calinou** [comment] 2022-08-18 13:42
Closing per @DragonAxe's comment. Please comment if you can still reproduce this on the latest 4.0 alpha *and* a recent graphics driver.

**Comment by DragonAxe** [comment] 2022-09-02 19:01
I may have spoke too soon. I am still experiencing this issue on v4.0.alpha15.official [432b25d36]

**Comment by andersmmg** [comment] 2022-09-23 15:26
Confirming this issue on 4.0.beta1 as well

**Comment by DragonAxe** [comment] 2022-10-24 19:13
I just discovered that I can sleep and resume without Godot freezing if it's running on my Intel integrated graphics!

I am running on a Thinkpad T480 laptop with hybrid graphics.
CPU: Intel(R) Core(TM) i5-8350U CPU @ 1.70GHz
iGPU: Intel(R) UHD Graphics 620 (KBL GT2)
GPU: NVIDIA GeForce MX150
Godot version: Godot Engine v4.0.beta.custom_build.39534a7ae (Same commit as Godot 4 beta 3 I think).

Running `godot --verbose` shows me I have two Vulkan devices, one for each of my GPUs:
```
bin/godot.linuxbsd.editor.x86_64.llvm --verbose
TextServer: Added interface "Dummy"
TextServer: Added interface "ICU / HarfBuzz / Graphite (Built-in)"
Godot Engine v4.0.beta.custom_build.39534a7ae - https://godotengine.org
XInput: Refreshing devices.
XInput: No touch devices found.
Text-to-Speech: Speech Dispatcher initialized.
Vulkan devices:
  #0: NVIDIA NVIDIA GeForce MX150 - Supported, Discrete
  #1: Intel Intel(R) UHD Graphics 620 (KBL GT2) - Supported, Integrated
Vulkan API 1.2.0 - Using Vulkan Device #0: NVIDIA - NVIDIA GeForce MX150
- Vulkan Variable Rate Shading not supported
- Vulkan multiview supported:
  max view count: 32
  max instances: 134217727
- Vulkan subgroup:
  size: 32
  stages: STAGE_VERTEX, STAGE_TESSELLATION_CONTROL, STAGE_TESSELLATION_EVALUATION, STAGE_GEOMETRY, STAGE_FRAGMENT, STAGE_COMPUTE
  supported ops: FEATURE_BASIC, FEATURE_VOTE, FEATURE_ARITHMETIC, FEATURE_BALLOT, FEATURE_SHUFFLE, FEATURE_SHUFFLE_RELATIVE, FEATURE_CLUSTERED, FEATURE_QUAD, FEATURE_PARTITIONED_NV
  quad operations in all stages
```

Godot defaults to using Vulkan device 0 which is my dedicated GPU. I can force Godot to use my integrated GPU using the flag `--gpu-index 1`. Godot freezes after sleep when using my NVIDIA GPU, but not when using my Intel iGPU.

**Comment by Calinou** [comment] 2023-01-10 16:31
Regarding NVIDIA GPUs, it seems this is currently a limitation of the driver. There is an experimental option you can enable to copy VRAM to RAM before suspending: https://wiki.archlinux.org/title/NVIDIA/Tips_and_tricks#Preserve_video_memory_after_suspend

**Comment by eikobear** [comment] 2023-03-24 15:44
This definitely seems to be a wider problem than Godot. I booted up Valheim on Pop! OS and put my computer into sleep mode. The Vulkan version of Valheim behaved just like Godot 4 (entire window stopped rendering), whereas OpenGL version of Valheim behaved more like Godot 3 (2D UI continued to render, but 3D meshes were completely black)

Also since I don't think it was mentioned in this thread yet: this problem affects not just the editor but any games made with Godot as well

**Comment by Calinou** [comment] 2023-03-24 17:28
Given how [large sweeping changes](https://github.com/godotengine/godot-proposals/issues/6423) are required to support suspend on Linux, it's fair to document this for now.

**Closed** 2023-05-08 13:40 UTC
Labels: platform:linuxbsd, topic:rendering, topic:editor, confirmed, documentation, topic:thirdparty

**Comment by DeeJayLSP** [comment] 2023-05-08 13:47
This is likely valid for #55389 too
