### ISSUE TITLE
Add cursor shortcuts for editor on Mac

### ISSUE THREAD

**Issue by MRxRadex** [godotengine/godot#22927] opened 2018-10-11 07:44 UTC
**Issue description:**
Please add combinations for the Mac version of the editor like:
**"Cmd + left arrow key"** - move cursor to the start of the line.
**"Cmd + right arrow key"** - move cursor to the end of the line.
**"Cmd + Shift + left arrow key"** - move cursor to the start of the line with selection.
**"Cmd + Shift + right arrow key"** - move cursor to the end of the line with selection.
**"Cmd + Delete"** - delete line.

P.S. Add these not for scripting only, but to the entire engine in menus, etc.

**Comment by DrMoriarty** [comment] 2018-10-11 14:32
I think that more interesting is to make ability to change all hotkeys for script editor view.
I also use mac, but I prefer to use emacs like hotkeys. I worked on this problem at https://github.com/DrMoriarty/godot/tree/emacsify but it has very dirty code so I didn't made PR.

May be anybody has any thoughts about making keys customisation?

**Comment by maho** [comment] 2020-03-15 13:25
From my point of view, I would like to have home/end buttons to behave like in Linux. However, then go to beginning and end of the file, and that's drives me mad. I would love to be able to customize it.

**Comment by sean256** [comment] 2020-03-31 00:47
The issue is that key bindings are hard coded, otherwise you'd be able to map them at an OS level to do just that. https://github.com/godotengine/godot/issues/34129

**Comment by Calinou** [comment] 2020-03-31 09:01
Adding support for customizing TextEdit shortcuts in the editor will probably have to wait for #31739 to be done. (We can't add more editor-only code to it due to #29730.)

**Comment by 40detectives** [comment] 2020-11-29 22:12
For the meantime, I get by using a key remapper software that hooks up the input before handling it to godot. In my case I use bettertouchtool but maybe could make it work with karabiner or you keyboard manufacturer software if any.

**Comment by Paulb23** [comment] 2021-06-18 18:55
Fixed by #43663

**Closed by Paulb23** 2021-06-18 18:55 UTC
Labels: enhancement, platform:macos, topic:editor, usability
