### ISSUE TITLE
A crackle is heard in the playback

### ISSUE THREAD

**Issue by Torguen** [godotengine/godot#43943] opened 2020-11-28 19:44 UTC
**Godot version:**

3.2.4 beta 3 mono

**OS/device including version:**

win10 64 home

**Issue description:**

When two audio files are buffered and played back, a crackle is heard as the first file ends and the second file begins.
The audio files don't have the crunch, I have checked in Audacity.

Can I fix it somehow?

**Steps to reproduce:**
Play the scene in the sample project

**Minimal reproduction project:**

[testFamiStudio.zip](https://github.com/godotengine/godot/files/5611141/testFamiStudio.zip)

![Captura2](https://user-images.githubusercontent.com/19652075/100524684-71ed7e80-31ba-11eb-9811-f2d06fd0d815.PNG)

**Comment by Calinou** [comment] 2020-11-28 20:06
Duplicate of https://github.com/godotengine/godot/issues/22016.

**Closed by Calinou** 2020-11-28 20:06 UTC
