### ISSUE TITLE
Godot 4 C# properties without setter cant be used in gdscript

### ISSUE THREAD

**Issue by ProfRobin2** [godotengine/godot#73380] opened 2023-02-15 17:05 UTC
### Godot version

4.0.rc2

### System information

Linux, Vulkan, AMD RX 6600 XT

### Issue description

If you use properties in C# that don't have a setter but only a getter you can't use them in GDScript.

So for example something like this:

```c#
public int GetterAndSetter { get { return 5; } set { } }
```

can easily be used in GDScript.

On the other hand something like this:

```c#
public int OnlyGetter { get { return 5; } }
```

can't be used in GDScript.

### Steps to reproduce

1. Create a Node A with C#-Code attached
2. Create a property in C# that only has a getter but no setter
3. Create a second Node B with GDScript-Code attached
4. Try to read the value of the property in GDScript
5. You will see an error

### Minimal reproduction project

[property_bug.zip](https://github.com/godotengine/godot/files/10745523/property_bug.zip)

**Comment by raulsntos** [comment] 2023-02-15 17:38
Duplicate of https://github.com/godotengine/godot/issues/67167

**Closed by raulsntos** 2023-02-15 17:38 UTC
