### ISSUE TITLE
Cannot change the value of the rigidity body from 'static' to 'character'.

### ISSUE THREAD

**Issue by DimaKiva** [godotengine/godot#7024] opened 2016-11-03 00:30 UTC
**Operating system or device - Godot version:**
Ubuntu 16.04 - Godot 2.1

**Issue description** (what happened, and what was expected):
After changes rigid body value 'static' to 'character': set_mode(2)  — node behavior not work like it. (Script)

**Steps to reproduce:**
`set_mode(2)`

**Link to minimal example project** (optional but very welcome):
[Bug rigidbody mode.zip](https://github.com/godotengine/godot/files/568011/Bug.rigidbody.mode.zip)

**Comment by eon-s** [comment] 2016-11-03 01:00
If you add a breakpoint on the print line and use the inspector to see the real values of the node, you will see it is Character, maybe the "print" is showing a value before the change is being made to the node.

**Comment by DimaKiva** [comment] 2016-11-03 02:42
After changes rigid body value 'static' to 'character': set_mode(2) Node behavior not work like it.

**Comment by eon-s** [comment] 2016-11-03 03:32
Ok, now I got it (using recent build).

The mode actually changes but from Static to Character or Rigid, stays with a StaticBody behavior(tested with Platformer 3D demo), also keep ignoring `_integrate_forces` after changing the mode.

It does work from Kinematic mode to Character/Rigid, could be a workaround.

ps: I'm sure that I have seen a similar open issue but can't find it.

**Comment by zakkor** [comment] 2017-03-18 15:46
The workaround doesn't seem to work (anymore?)

**Comment by eon-s** [comment] 2017-03-18 16:25
@zakkor on 2.1.2 looks like that workaround fails sometimes, and noticed that collisions "wake up" the locked rigid.

Also tested a zero impulse on `_fixed_process` and seems to work (until a proper fix is found) so this can be added after changing mode:
`apply_impulse(Vector3(),Vector3())`

**Comment by zakkor** [comment] 2017-03-18 17:50
By the way, this issue is present in the 2D version of RigidBody as well

**Comment by akien-mga** [comment] 2017-06-29 09:27
Does not affect the master branch apparently: https://github.com/godotengine/godot/issues/8909#issuecomment-304160800

**Comment by Noshyaar** [comment] 2018-04-07 06:41
First of all thank you for your report and sorry for the delay.

We released Godot 3.0 in January 2018 after 18 months of work, fixing many old issues either directly, or by obsoleting/replacing the features they were referring to.

We still have hundreds of issues whose relevance/reproducibility needs to be checked against the [current stable version](https://godotengine.org/download), and that's where you can help us.
**Could you check if the issue that you described initially is still relevant/reproducible and comment about it here?**

For bug reports, please also make sure that the issue contains detailed steps to reproduce the bug and, if possible, a zipped project that can be used to reproduce it right away. This greatly speeds up debugging and bugfixing tasks for our contributors.

Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

Thanks in advance.

*Note: This message is being copy-pasted to many "stale" issues (90+ days without activity). It might happen that it is not meaningful for this specific issue or appears oblivious of the issue's context, if so please comment to notify the Bugsquad about it.*

**Comment by eon-s** [comment] 2018-04-07 14:57
This issue still affects Godot 2 and Godot 3 with Godot Physics only, seems to be solved in Bullet.

**Comment by akien-mga** [comment] 2018-09-17 13:40
The 2.1 branch is no longer actively worked on by engine developers, unless critical fixes are needed for current games in production. As such we are now closing non-critical bug reports affecting only the 2.1 branch.

Please comment if this was incorrectly triaged and is still relevant in 3.x versions.

**Closed by akien-mga** 2018-09-17 13:40 UTC
Labels: bug, topic:core, topic:physics
