### ISSUE TITLE
C# Export variables resets if parent class of node's script class is re-compiled

### ISSUE THREAD

**Issue by al1-ce** [godotengine/godot#49320] opened 2021-06-04 18:20 UTC
**Godot version:**

3.3.2 Mono

**OS/device including version:**

Windows 10

**Issue description:**

Export fields that was initialised in parent class resets if that class is re-compiled

**Steps to reproduce:**

Create a parent class and add: 
`[Export]
protected int field = 3;`
Create class derived from parent and assign it to node in scene
Change export value in editor
Add changes in parent class without touching export field
Press build button
After re-compiling node's export variable value will reset itself to one that was defined in parent class

**Comment by Calinou** [comment] 2021-06-04 18:41
Duplicate of https://github.com/godotengine/godot/issues/37812.

**Closed by Calinou** 2021-06-04 18:41 UTC
Labels: bug, topic:mono
