### ISSUE TITLE
GPUParticles3D trails anchor themselves to the root of the scene

### ISSUE THREAD

**Issue by Mikeysax** [godotengine/godot#68365] opened 2022-11-07 11:41 UTC
### Godot version

4.0beta4

### System information

PopOS 22.04, 6.0.3-76060003-generic kernel, Ryzen 6800h, Radeon 6700m, amdgpu, Vulkan

### Issue description

When using the GPUParticles3D with trails and correct meshes (ie RibbonTrailMesh) with the correct flags on the material to enable trails, the particles end up anchoring themselves to the root of the scene. This happens even when closing and reopening the scene or project:

https://user-images.githubusercontent.com/15805689/200299712-2e48fb92-4817-40a9-8e1b-4e088f77a0d3.mp4

https://user-images.githubusercontent.com/15805689/200299725-90307957-e541-4ddb-8b80-64e7f1762d6f.mp4

![image](https://user-images.githubusercontent.com/15805689/200299925-76e134db-cf36-44c6-b68c-e7f0949b7ec5.png)

https://user-images.githubusercontent.com/15805689/200301448-2778a3b5-0e7f-441e-94e4-9e783c7ffd29.mp4

### Steps to reproduce

1) Add GPUParticles3D

2) Enable Trails

3) Add ribbon or tube trail mesh

4) Enable particles on attached material

https://user-images.githubusercontent.com/15805689/200301448-2778a3b5-0e7f-441e-94e4-9e783c7ffd29.mp4

### Minimal reproduction project

You can reproduce easily by following above steps.

**Comment by Calinou** [comment] 2022-11-07 19:41
Duplicate of https://github.com/godotengine/godot/issues/55842.

**Closed by Calinou** 2022-11-07 19:41 UTC
