### ISSUE TITLE
Getting Input from Keyboard and Joypad (Axis) using Input.GetVector() and Input.GetAxis() sticks

### ISSUE THREAD

**Issue by Has-if36** [godotengine/godot#85124] opened 2023-11-20 07:11 UTC
### Godot version

4.2.dev.mono

### System information

Godot v4.2.dev4.mono - Windows 10.0.19045 - Vulkan (Mobile) - dedicated NVIDIA GeForce GTX 1650 (NVIDIA; 31.0.15.3114) - Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 Threads)

### Issue description

Using only keyboard alone works just fine. Switch from keyboard to gamepad also seems to work fine. However, when switching gamepad (specifically axis) to keyboard, it behaves a kinda weird. 

For the gamepad, the issue is when I used default value of deadzone, whenever I release the axis input, the input stays as is instead of returning to zero.

It works fine when I used Godot v4.1.2.stable.mono.
Edit: It also works well when on Godot Godot v4.2.rc1.mono

#### Input Map
![image](https://github.com/godotengine/godot/assets/55189926/397b51c0-7212-4960-b486-92ec0b63659b)
I set the deadzone to 0 to test the behavor when switching from joypad to keyboard.

#### Script
```
    protected Vector2 moveInput = Vector2.Zero;
    public override void _Input(InputEvent @event)
    {
        if (Input.IsActionPressed("ui_left") || Input.IsActionPressed("ui_right") || Input.IsActionPressed("ui_up") || Input.IsActionPressed("ui_down"))
        {
            //moveInput = Input.GetVector("ui_left", "ui_right", "ui_up", "ui_down");
            moveInput = new Vector2(Input.GetAxis("ui_left", "ui_right"), Input.GetAxis("ui_up", "ui_down"));
			GD.Print("Input Pressed: " + moveInput);
        } else if (Input.IsActionJustReleased("ui_left") || Input.IsActionJustReleased("ui_right") || Input.IsActionJustReleased("ui_up") || Input.IsActionJustReleased("ui_down"))
        {
            //moveInput = Input.GetVector("ui_left", "ui_right", "ui_up", "ui_down");
            moveInput = new Vector2(Input.GetAxis("ui_left", "ui_right"), Input.GetAxis("ui_up", "ui_down"));
			GD.Print("Input Release: " + moveInput);
        }
    }
```
In this case, I just used Control node and attached this block of code

### Minimal reproduction project

[Test.zip](https://github.com/godotengine/godot/files/13407492/Test.zip)

**Comment by AThousandShips** [comment] 2023-11-20 10:06
Probably a duplicate of https://github.com/godotengine/godot/issues/81164 and was solved by https://github.com/godotengine/godot/pull/81170

**Closed** 2023-11-20 11:26 UTC
Labels: bug, needs testing, topic:input

**Comment by Has-if36** [comment] 2023-11-20 12:01
Ah, sorry about that and thanks for taking a bit of time.
