### ISSUE TITLE
Problem renaming script file in mono

### ISSUE THREAD

**Issue by Torguen** [godotengine/godot#33729] opened 2019-11-19 12:54 UTC
**Godot version:**
3.2 beta 1 mono

**OS/device including version:**
Win10 64 Home

**Issue description:**
Creating a new script that is not associated with any node and then renaming it from the godot editor will make the script no longer recognized.
A compilation error will be created indicating the following:

The source file was not found "and in these quotes the path to the script"

Adapting the class name to the new name of the script file will not solve the problem.

**_The problem is that the file "testScript.csproj" did not update the name of the script._**

**Steps to reproduce:**

1 - Create a new script that is not associated with any node.

![3](https://user-images.githubusercontent.com/19652075/69148027-a9b7e580-0ad3-11ea-9328-92dedd4a7d4c.png)

![4](https://user-images.githubusercontent.com/19652075/69148043-b0465d00-0ad3-11ea-8f09-b8ff949c06f5.png)

2 - I changed the name.

![5](https://user-images.githubusercontent.com/19652075/69148075-c05e3c80-0ad3-11ea-9269-0f7893d4301d.png)

2 - Script file with new name

![7](https://user-images.githubusercontent.com/19652075/69148287-3d89b180-0ad4-11ea-8848-484535f616fd.PNG)

4 - Try to compile and the error will occur.

![6](https://user-images.githubusercontent.com/19652075/69148123-dbc94780-0ad3-11ea-9fba-6f26d2978413.PNG)

**Minimal reproduction project:**
Any empty project will be enough.

**Comment by aaronfranke** [comment] 2019-11-20 01:58
Duplicate of #12917

**Closed** 2019-11-20 06:44 UTC
