### ISSUE TITLE
Input triggered multiple times on SteamDeck

### ISSUE THREAD

**Issue by MindFlayeR57** [godotengine/godot#85933] opened 2023-12-08 18:48 UTC
### Tested versions

4.1.2, 4.1.3, and 4.2 all of them are affected and it would take me forever to test more versions with my download speeds

### System information

SteamOS 3.5.7

### Issue description

is_action_just_pressed() triggers multiple times on SteamDeck when executed under the _input() function.

### Steps to reproduce

1. Export the attached project and run it on SteamDeck
2. Switch to the console window
3. Press A
4. It will print the amount of times it got triggered by a single press (usually 3-4)

### Minimal reproduction project (MRP)

[SteamDeck Bug.zip](https://github.com/godotengine/godot/files/13619520/SteamDeck.Bug.zip)

**Comment by Sauermann** [comment] 2023-12-08 21:54
Please try using

``` gdscript
func _input(event: InputEvent) -> void:
	if event.is_action_pressed("ui_accept"):
		i += 1
		print(i) # prints the amount of times is_action_just_pressed() got triggered despite the documentation saying it only triggers once per button press
```

`Input.is_action_just_pressed("ui_accept")` returns, if in the current frame any event has the "ui_accept" action pressed. So when multiple events are sent in a single frame, each one of them causes an `i += 1` in the same frame.

**Comment by clayjohn** [comment] 2023-12-08 22:07
This sounds eerily similar to the issue fixed by https://github.com/godotengine/godot/pull/76045

**Comment by MindFlayeR57** [comment] 2023-12-08 22:23
> Please try using
> 
> ``` gdscript
> func _input(event: InputEvent) -> void:
> 	if event.is_action_pressed("ui_accept"):
> 		i += 1
> 		print(i) # prints the amount of times is_action_just_pressed() got triggered despite the documentation saying it only triggers once per button press
> ```
> 
> `Input.is_action_just_pressed("ui_accept")` returns, if in the current frame any event has the "ui_accept" action pressed. So when multiple events are sent in a single frame, each one of them causes an `i += 1` in the same frame.

It works! Thank you very much!

**Closed** 2023-12-08 22:25 UTC
Labels: discussion, topic:input

**Comment by akien-mga** [comment] 2023-12-08 23:23
I'm not sure this is fixed? Is it not a bug in the end?

**Comment by Sauermann** [comment] 2023-12-09 08:37
I had a look at the MRP of #76045 and that PR is unrelated to this issue (it has nothing to do with `is_action_just_pressed`).

This bug report looks more like a duplicate of #80158 and is based on using `Input.is_action_just_pressed` in an unintended location. The documentation was adjusted accordingly in #80185.
