### ISSUE TITLE
camera smoothing tilemap jitter

### ISSUE THREAD

**Issue by FlowLightGames** [godotengine/godot#95571] opened 2024-08-15 16:42 UTC
### Tested versions

-reproducible in 4.3
-not reproducible in 4.2.2

### System information

Godot v4.3.stable - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 4080 SUPER (NVIDIA; 31.0.15.5186) - AMD Ryzen 7 7800X3D 8-Core Processor (16 Threads)

### Issue description

when using camera smoothing (and both pixel snapping options, but they dont make a difference for me) it appears the tiles in the tilemap are not snapped correctly? or lagging behind. This was not a problem in 4.2.2 stable. 
4.3:
![Animation](https://github.com/user-attachments/assets/06246762-ba4d-4d59-954d-1eb41343fa10)
4.2.2:
![Animation1](https://github.com/user-attachments/assets/de606a59-ab95-47f4-867f-e6bb4abda1df)

### Steps to reproduce

make a new project, (enable both pixel snap option but they didnt make a difference for me), make a tileset (in this example isometric), move camera and let the position smoothing do its thing.

### Minimal reproduction project (MRP)

[New Compressed (zipped) Folder.zip](https://github.com/user-attachments/files/16627512/New.Compressed.zipped.Folder.zip)
the folder contains a "4.2.2" project and "bugreport" both nearly identical setups, but the bug only happens in the bugreport (4.3) project not in the 4.2.2 stale one. in the projects move the camera with the arrow buttons (then stopping for the position smoothing).

**Comment by arkology** [comment] 2024-08-15 17:22
I think I saw similar effect not only with tilemap.

**Comment by FlowLightGames** [comment] 2024-08-15 18:21
> I think I saw similar effect not only with tilemap. Changing camera offset instead of position solves this jitter.

tried manually tweening camera offset and not using the position smoothing. Same problem.

**Comment by markdibarry** [comment] 2024-08-15 21:08
I looked at your project and it seems you have `Snap 2D Verticies to Pixel` turned on by mistake. If you turn that off, you shouldn't have any issues.

**Comment by FlowLightGames** [comment] 2024-08-16 10:36
> I looked at your project and it seems you have `Snap 2D Verticies to Pixel` turned on by mistake. If you turn that off, you shouldn't have any issues.

yup :O. but the 4.2.2 version also has snap 2d vertices to Pixel enabled and does not have this issue.

**Comment by markdibarry** [comment] 2024-08-16 13:16
Did you see something that recommended you have them both on? We should correct it if so. In both versions you shouldn't have `Snap 2D Vertices to Pixel` turned on at all and definitely not with `Snap 2D Transforms to Pixel` on at the same time. IIRC `Snap 2D Vertices to Pixel` was added very early on in the 4.0 development as a work around while we were trying to figure out pixel snap in general, and will be deprecated in the future... but someone can correct me if I'm mis-remembering.

Either way `Snap 2D Transforms to Pixel` should be all you need!

**Comment by FlowLightGames** [comment] 2024-08-16 13:53
> Did you see something that recommended you have them both on? We should correct it if so. In both versions you shouldn't have `Snap 2D Vertices to Pixel` turned on at all and definitely not with `Snap 2D Transforms to Pixel` on at the same time. IIRC `Snap 2D Vertices to Pixel` was added very early on in the 4.0 development as a work around while we were trying to figure out pixel snap in general, and will be deprecated in the future... but someone can correct me if I'm mis-remembering.
> 
> Either way `Snap 2D Transforms to Pixel` should be all you need!

I tried all permutations of those 2 settings. still there

**Comment by markdibarry** [comment] 2024-08-16 13:57
Oh that's weird. Can you upload an MRP with this issue? I can't reproduce the issue in the MRP you provided. All I did was turn off `Snap 2D Vertices to Pixel` and it's working as expected.

https://github.com/user-attachments/assets/9830da8c-9113-459b-950a-06ec6b70a287

**Comment by FlowLightGames** [comment] 2024-08-16 14:35
> Oh that's weird. Can you upload an MRP with this issue? I can't reproduce the issue in the MRP you provided. All I did was turn off `Snap 2D Vertices to Pixel` and it's working as expected.
> 
>  2024-08-16.09-56-36.mp4


might be hardware dependent or because here (seconds 15-17) its because the movement is not as smooth as in mrp, ill add a mrp with more sudden movements rn:

https://github.com/user-attachments/assets/a23932e4-08aa-4412-a106-df75a507d489

**Comment by markdibarry** [comment] 2024-08-16 14:58
Ah I see! I guess this isn't a regression since the docs warn against using anything except `Snap 2D Transforms to Pixels`, so any combination of the two would result in unsupported behavior. However, I definitely would not expect there to be glitches with just `Snap 2D Transforms to Pixels` enabled, so it's certainly a bug we should check out ASAP. It's hard to tell if this is an issue with tiles or with snapping though, so if you can make a small MRP that can exhibit that we should be able to get to the bottom of it. I see you're using an Nvidia card, and remember there being issues with Nvidia in the past, but luckily I also have an Nvidia card so I should be able to reproduce it if you can. Let us know and we'll try to get this fixed!

**Comment by FlowLightGames** [comment] 2024-08-16 15:13
> Ah I see! I guess this isn't a regression since the docs warn against using anything except `Snap 2D Transforms to Pixels`, so any combination of the two would result in unsupported behavior. However, I definitely would not expect there to be glitches with just `Snap 2D Transforms to Pixels` enabled, so it's certainly a bug we should check out ASAP. It's hard to tell if this is an issue with tiles or with snapping though, so if you can make a small MRP that can exhibit that we should be able to get to the bottom of it. I see you're using an Nvidia card, and remember there being issues with Nvidia in the past, but luckily I also have an Nvidia card so I should be able to reproduce it if you can. Let us know and we'll try to get this fixed! Thanks for your help.

trying to reproduce it I found a stray subviewport that was still using the Snap 2D Vertices to Pixel, causing the issue. Sorry 😳

**Comment by markdibarry** [comment] 2024-08-16 15:16
Oh no worries! If you find anything else, please let us know! We put a lot of love into trying to get pixel-perfect snapping right, so it's important to get to the bottom of these issues as they come up. We really should create a tutorial for different setups too.

**Comment by Mickeon** [comment] 2024-08-16 17:37
To be honest the fact that these two snapping properties are separate and have not been merged into the same enumeration feels weird to me.

**Comment by markdibarry** [comment] 2024-08-19 13:42
@FlowLightGames Is your problem resolved? If so, would you mind closing the ticket?

**Comment by markdibarry** [comment] 2024-09-21 14:31
Similar to 96256, this is fixed by just using `snap_2d_transforms_to_pixel`, but https://github.com/godotengine/godot/pull/97260 also fixed `snap_2d_vertices_to_pixel` as well. Tested with the original MRP and can't reproduce in either case now.

**Closed** 2024-09-21 14:39 UTC
Labels: bug, topic:rendering, regression, topic:2d
