### ISSUE TITLE
File rename does not work if FileSystem widget is out of focus

### ISSUE THREAD

**Issue by Cerno-b** [godotengine/godot#82673] opened 2023-10-02 10:09 UTC
### Godot version

v4.1.1.stable.official [bd6af8e0e]

### System information

Windows 10

### Issue description

Rename file context menu entry does not react when `FileSystem` widget is out of focus

### Steps to reproduce

What works: 

* Click an item in the `FileSystem` widget so the widget gets focus
* Right-click a file
* Select `Rename...`
-> a rename dialog opens

What does not work:
* Click an item in any other main widget (e.g. a node in `Scene`)
* Right-click a file in the `FileSystem` widget (without giving it focus first)
* Select `Rename...`
-> nothing happens

I tried this with other entries in the context menu, but they seem to work. `Rename...` seems to be the odd one out.

### Minimal reproduction project

Should be N/A, I just started a fresh project, added a 3 nodes and it occurred.

I can give a minimal example if not reproducible for anyone else.

### Observations:

* This does not occur for the `Rename...` option in the `Scene` widget, only the one in the `FileSystem` widget
* Both `Rename...` options have the same shortcut (F2) (not sure they should).
* F2 will rename...
** ... a `Scene` node if `Scene` has focus
** ... a `FileSystem` node if `FileSystem` has focus
** ... a `Scene` node if neither has focus (is this intended?)

Idk if this is related to the original issue, but shouldn't hotkeys be global? So shouldn't both rename functions have different hotkeys?

The current behavior leads to an inconsistency:

* Select a node from the `Scene` widget
* Keep working
* Select a node from the `FileSystem`
* Click somewhere on screen or press tab
* press F2

I would think the user would expect the `FileSystem` node to be renamed, but the one in `Scene` will be.

**Comment by bitsawer** [comment] 2023-10-02 10:32
Thanks for the report. Seems like a duplicate of https://github.com/godotengine/godot/issues/78789, already fixed in master. Closing as duplicate.

**Closed by bitsawer** 2023-10-02 10:32 UTC

**Comment by Cerno-b** [comment] 2023-10-02 10:36
@bitsawer Thanks for the quick reply
