### ISSUE TITLE
GLTFDocument can't load blend-shape related parts of models in 4.2 beta 6 and later versions

### ISSUE THREAD

**Issue by meisamsafavi** [godotengine/godot#85960] opened 2023-12-09 12:02 UTC
### Tested versions

Reproducible: 4.2 beta6, 4.2 rc1, 4.2 rc2, 4.2 stable
Not Reproducible: 4.2 beta 5, 4.2 beta 4 and ...

### System information

Widows 10, AMD 5600x, Nvidia RTX3060

### Issue description

Hi,
I had been using the following function in project to load 3D models at runtime, but unfortunately after the 4.2 beta 6 it couldn't load the face of the avatar and gave some blend-shape related errors.

`func load_resource():

	var gltf := GLTFDocument.new()
	var gltf_state := GLTFState.new()
	var path = "res://3D_model/4/4.glb"
	var snd_file = FileAccess.open(path, FileAccess.READ)
	var fileBytes = PackedByteArray()
	fileBytes = snd_file.get_buffer(snd_file.get_length())
	gltf.append_from_buffer(fileBytes, "base_path?", gltf_state)
	var node = gltf.generate_scene(gltf_state)
	add_child(node)`

![1](https://github.com/godotengine/godot/assets/74149722/28904ebb-7e8c-46e8-b9eb-d767d17d2bac)

![3](https://github.com/godotengine/godot/assets/74149722/036087bd-3926-434c-926f-b818993ce832)

Huge thanks.

### Steps to reproduce

Just run the minimal project and press END button on keyboard ;)

### Minimal reproduction project (MRP)

[resource_loader_test.zip](https://github.com/godotengine/godot/files/13623984/resource_loader_test.zip)

**Comment by lyuma** [comment] 2023-12-24 04:06
Duplicate of #86384

That said, we did uncover a workaround this week that you may be able to use until this issue can be resolved at an engine level:
Change your code to this:
```
gltf.append_from_buffer(fileBytes, "base_path?", gltf_state, 8)
```
8 is the constant for `EditorSceneFormatImporter.IMPORT_GENERATE_TANGENT_ARRAYS` : blendshapes without tangents seem to have been broken in 4.2, so this is why it works around the bug.

I know this was technically filed first, but I included additional technical issues in the other issue, so I will close this one. Thanks for reporting and it will be helpful to have an additional testcase.

**Closed by lyuma** 2023-12-24 04:06 UTC
Labels: bug, needs testing, topic:import, regression, topic:3d

**Comment by meisamsafavi** [comment] 2023-12-24 10:56
@lyuma 
Huge thanks for responding.
Tested out and it's working.
