### ISSUE TITLE
Godot accidentally started launching slowly

### ISSUE THREAD

**Issue by DSTGSD** [godotengine/godot#51472] opened 2021-08-10 13:13 UTC
### Godot version

3.3.2 stable

### System information

Windows 10, GLES 3, Intel(R) Core(TM) i5-9400F CPU 2.90 GHz, NVIDIA GeForce GTX 1050 Ti

### Issue description

Accidentally Godot editor and also inspector started launching veeeery slowly, it takes about 30 seconds to launch Godot or launch a really simple project. I already turned "Update Continuously" in editor settings on and my graphical driver is up to date. I have done nothing with my devices or editor recently, i tried reinstalling it on Steam after facing this problem but it still did not help. This problem is used to happed everywhere, even if there is no code in project.

### Steps to reproduce

-

### Minimal reproduction project

-

**Comment by akien-mga** [comment] 2021-08-10 13:15
Probably duplicate of #20566, check your USB peripherals.

**Comment by Calinou** [comment] 2021-09-07 18:32
@DSTGSD Do you use any Corsair peripherals or other gaming-oriented peripherals with complex drivers/software? See the above comment.

**Comment by Calinou** [comment] 2021-09-15 21:49
@DSTGSD Bump :slightly_smiling_face:

**Comment by Calinou** [comment] 2022-08-08 09:45
Closing due to lack of response (likely duplicate of https://github.com/godotengine/godot/issues/20566).

**Closed by Calinou** 2022-08-08 09:45 UTC
Labels: platform:windows, topic:porting, performance
