### ISSUE TITLE
It is impossible to have two different parameters for one tile from TileMapLayer

### ISSUE THREAD

**Issue by miruji** [godotengine/godot#97001] opened 2024-09-14 14:49 UTC
### Tested versions

Godot Engine v4.3.stable.official.77dcf97d8

### System information

Linux

### Issue description

To be honest, I don’t quite understand whether this is a bug or normal behavior of gdscript. However, before that, I spent quite a lot of time searching for a solution and did not find it. I'm working on a 2d project in which to create a landscape map I use 24x24px tiles via TileMapLayer and thereby build a large map from them accordingly. To smooth out the corners, I use Terrain Sets in which I placed one earth-water set. This way I can create rivers, curves and other terrain effects.
![0](https://github.com/user-attachments/assets/637d26ee-5bba-4c91-b609-b169a917d5ff)
But although this works, the main problem is in the creation of biomes. I can create another map for environmental objects, there are many fewer of them, but the same cannot be said about the Land Map described above.
![1](https://github.com/user-attachments/assets/8d2a6e25-2eb4-4ded-8693-9badc81b8943)
As you can see, the map of alternative tiles is very large, the solution would be if I could copy it in the right window and simply replace the texture, but this is not possible. Setting up a dozen of these alternative cards is suicide. Changing the map texture from the player's position is a bad idea for top-down games; it works well in Terraria, but not here.

In this case, I decided to use shaders, with their help you can change the color of an individual tile through the material. But this requires checking the tile position and the array of configured values ​​in the code. Perhaps the solution is much simpler.

### Steps to reproduce

So, having come to terms with the fact that I couldn't do any of the above, I decided to test my idea on a Domain Map to limit the territory of something on the map. To do this, I use 1 gray tile + shader to change its color. The shader works on the tile and makes it red. Next you can use the array and how-then make borders there in a primitive way by designating ownership through an int number.
![2](https://github.com/user-attachments/assets/3a82febd-62ce-48a5-abfe-6daee98c654a)
However, when implementing the drawing function, I am faced with the main problem, it is that the variable for an already installed tile behaves as a reference to the tile map itself, which means that a change in this tile changes it in the TileMapLayer, which essentially should not happen.
```
func _input(event: InputEvent) -> void:
	# paint domain
	if event is InputEventMouseButton and event.pressed:
		var mousePos = get_global_mouse_position()
		var localMousePos = domain.to_local(mousePos)
		var cell = domain.local_to_map(localMousePos)
		paintDomain(cell, 0)

@onready var domain: TileMapLayer = get_node("domain")
func paintDomain(pos: Vector2, state: int) -> void:
	print(pos)
	domain.set_cell(Vector2i(pos.x, pos.y),0,Vector2i(0, 0))
	var tile: TileData = domain.get_cell_tile_data(Vector2i(pos.x, pos.y))
	tile.material = null
```
I tried to solve this by creating unique shaders, materials and who knows what else. And for me this is still a bug, since as a developer I am not obliged to create all these maps myself and in the future there may be many more objects that I cannot foresee. And I still don't understand why I just can't change things individually, or even better, without using all this in code, but simply through different input parameters for the same tile.
![3](https://github.com/user-attachments/assets/f6778ef6-b9b4-4bcb-a506-72a3f6c30c86)

### Minimal reproduction project (MRP)

N/A

**Comment by AThousandShips** [comment] 2024-09-14 14:56
This doesn't very clearly describe what you are having problems with, please provide *clear* reproduction steps and what the problem is

And I'd suggest first asking in the [other channels](https://godotengine.org/community/) to work out what you are needing and ways to do it, and only when you have clear steps to what you think is a bug should you make a bug report

**Comment by miruji** [comment] 2024-09-14 15:05
@AThousandShips 
The main problem: when you change a specific fragment, the entire map changes, not just a single fragment.

I'm not sure if this is intended behavior or a bug, but it does create problems when trying to apply unique shaders or materials to certain tiles. I can't fix this by not having a function to duplicate the current atlas, and I also can't know the exact number of possible Domain Map color combinations, so changing one tile is an extremely important task for me. However, as described above, I cannot apply several different parameters to 1 tile, I just can't even have 1 tile with 2 different colors.

**Comment by AThousandShips** [comment] 2024-09-14 15:11
You mean that you can't assign specific properties to individual tiles in the map? That's a limitation, you have to make the tiles in the TileSet specific, that's pretty much the basic idea of a tilemap format

So this isn't a bug, but you might be looking for a proposal like this one:
* https://github.com/godotengine/godot-proposals/issues/6606

Closing as this is a limitation and not a bug, thank you for your report nonetheless

**Closed by AThousandShips** 2024-09-14 15:11 UTC
Labels: needs testing, topic:2d

**Comment by miruji** [comment] 2024-09-15 17:57
If anyone is interested, then the overlay of what I wrote above is possible as described through the shader, but this requires taking into account the camera position, map size, camera size and also a huge array of cells. In the case of biomes, it is necessary to apply another texture to such a square. But if it were possible to have different parameters for 1 tile, This would greatly simplify everything.
![0](https://github.com/user-attachments/assets/fe5752c4-98ee-43b2-b6fa-b9c159592070)
![1](https://github.com/user-attachments/assets/4103032d-25a0-4e55-b922-aaebc31ec1c2)
