### ISSUE TITLE
No TileMap layer highlight when ysort enabled on TileMap and it's layers

### ISSUE THREAD

**Issue by Dante3085** [godotengine/godot#78153] opened 2023-06-12 18:40 UTC
### Godot version

v4.0.3.stable.mono.official [5222a99f5]

### System information

Windows 11

### Issue description

When ysort is enabled on a TileMap and each of it's layers, the highlighting of the currently selected layer disappears. I am not sure if this is intended behaviour.

No ysort on TileMap: You can see that only the tiles of the selected layer (layer 0) are fully visible.
<img width="451" alt="image" src="https://github.com/godotengine/godot/assets/26558776/98b7347c-9a5f-46e1-81e8-ad3ba2253861">

ysort on TileMap: All tiles of all layers are fully visible => Essentially no layer highlighting anymore.
<img width="446" alt="image" src="https://github.com/godotengine/godot/assets/26558776/e06ed60b-3d12-4505-bb18-fe7a8d3e3201">

### Steps to reproduce

1. Create a TileMap with at least two layers and an arbitrary TileSet, so you can draw something.
2. Enable ysort on all individual layers and the TileMap itself.
3. Make sure "Highlight Selected TileMap Layer" is on (Right next to where you select the layer).
4. Toggle ysort on the TileMap to see that the highlighting of the selected layer disappears when ysort is enabled.

### Minimal reproduction project

[bug_tilemap_no_layer_highlight_when_ysort_enabled.zip](https://github.com/godotengine/godot/files/11726836/bug_tilemap_no_layer_highlight_when_ysort_enabled.zip)

**Comment by KoBeWi** [comment] 2023-06-13 12:26
Can't reproduce in 4.1 beta

https://github.com/godotengine/godot/assets/2223172/488f919a-5b4f-4301-8006-76bebd3fdd57

**Comment by groud** [comment] 2023-06-20 11:49
I'll close that one as it is likely fixed on master. Maybe thanks to https://github.com/godotengine/godot/pull/78134.
If anyone is able to reproduce this bug again, please let us know, I'll reopen.

**Closed by groud** 2023-06-20 11:49 UTC
Labels: topic:editor, needs testing, topic:2d
