### ISSUE TITLE
Negative delta in _process

### ISSUE THREAD

**Issue by mnn** [godotengine/godot#40255] opened 2020-07-10 12:27 UTC
**Godot version:** 3.2.1

**OS/device including version:** Linux 64b (Manjaro), NVidia 2080ti (440.82), GLES3

**Issue description:**

Delta is negative:

<img width="467" alt="2020-07-10_14-15" src="https://user-images.githubusercontent.com/1975567/87154323-55a77e80-c2b9-11ea-8e99-5052ec3c7ab6.png">

**Steps to reproduce:**
The bug only happens in a scene with heavy `AnimatedSprite`s - few instances with hi-resolution (1.2k) quite hi-fps (30) and a lot of frames (~360).

**Comment by Calinou** [comment] 2020-07-10 12:32
Duplicate of #26887.

**Closed by Calinou** 2020-07-10 12:32 UTC
