### ISSUE TITLE
Editor freezes on Linux

### ISSUE THREAD

**Issue by floppyhammer** [godotengine/godot#48661] opened 2021-05-12 03:59 UTC
Godot version:
v4.0.dev.custom_build.de3747fc3

OS/device including version:
Linux, 1080Ti, Vulkan

Issue description:
Editor freezes upon certain operations. One example is selecting the project name text when creating a new project:

![Peek 2021-05-12 11-46](https://user-images.githubusercontent.com/28705694/117915716-734dd600-b318-11eb-9f57-19aaa71fc4b0.gif)

Nothing special came out of the log though:
> Godot Engine v4.0.dev.custom_build.de3747fc3 - https://godotengine.org
> Using "ICU / HarfBuzz / Graphite" text server...
> XInput: Refreshing devices.
> XInput: No touch devices found.
> Vulkan API 1.2.162
> Using Vulkan Device #0: NVIDIA - GeForce GTX 1080 Ti
> - Vulkan multiview supported:
>   max views: 32
>   max instances: 134217727
> - Vulkan subgroup:
>   size: 32
>   stages: STAGE_VERTEX, STAGE_TESSELLATION_CONTROL, STAGE_TESSELLATION_EVALUATION, STAGE_GEOMETRY, STAGE_FRAGMENT, STAGE_COMPUTE, STAGE_RAYGEN_KHR, STAGE_ANY_HIT_KHR, STAGE_CLOSEST_HIT_KHR, STAGE_MISS_KHR, STAGE_INTERSECTION_KHR, STAGE_CALLABLE_KHR
>   supported ops: FEATURE_BASIC, FEATURE_VOTE, FEATURE_ARITHMETIC, FEATURE_BALLOT, FEATURE_SHUFFLE, FEATURE_SHUFFLE_RELATIVE, FEATURE_CLUSTERED, FEATURE_QUAD, FEATURE_PARTITIONED_NV
>   quad operations in all stages
> Using "default" pen tablet driver...
> JoypadLinux: udev enabled and loaded successfully.
> PulseAudio: detected 2 channels
> PulseAudio: audio buffer frames: 512 calculated latency: 11ms
>  
> CORE API HASH: 6553627305753370567
> EDITOR API HASH: 7970682899503148393
> EditorSettings: Load OK!
> Loaded builtin certs
> EditorSettings: Save OK!
> Vulkan: Swapchain is out of date, recreating.

Steps to reproduce:
Create a new project, click on the project name text box, select some text.

Minimal reproduction project:
No need.

**Comment by Calinou** [comment] 2021-05-12 14:16
Duplicate of https://github.com/godotengine/godot/issues/41614.

**Closed by Calinou** 2021-05-12 14:16 UTC
