### ISSUE TITLE
Unable to "Clear" custom resource from custom node with a setter defined

### ISSUE THREAD

**Issue by ObsidianBlk** [godotengine/godot#69767] opened 2022-12-08 16:38 UTC
### Godot version

4.0 Beta 7

### System information

Arch Linux

### Issue description

I have a custom Node (with class_name) with an export variable that takes a custom Resource. The custom node's export variable uses a setter function.
`@export var custom_resource : CustomResourceA = null : set = set_custom_resource`

When I attempt to remove the resource from the inspector using the drop-down on the right of the field, I click the "Clear" option and nothing happens. The resource is still assigned. Using the circular icon on the left *will* clear the resource, but that icon does not always appear (I sometimes find I need to reload the scene or the whole editor).

If I remove the setter method within the custom node, clearing the resource works just fine.

### Steps to reproduce

Create a custom resource...
```
extends Resource
class_name CustomResourceA

@export var some_var : int = 0 : set = set_some_var

func set_some_var(v : int) -> void:
	some_var = v
```

Create a custom node...
```
extends Node
class_name CustomNodeA

@export var custom_resource : CustomResourceA = null : set = set_custom_resource


func set_custom_resource(cr : CustomResourceA) -> void:
	custom_resource = cr
```

Instance the node, assign the resource, then attempt to remove resource from the node.

### Minimal reproduction project

[CRIssue.zip](https://github.com/godotengine/godot/files/10187517/CRIssue.zip)

**Comment by adamscott** [comment] 2022-12-09 01:03
Seems a duplicate or related to #68503.
Please take a look to the workaround mentionned in that issue.

**Comment by akien-mga** [comment] 2022-12-09 06:10
Duplicate of #68503

**Closed by akien-mga** 2022-12-09 06:10 UTC
