### ISSUE TITLE
Script changes outside Godot not recognized by editor scene or tool script.

### ISSUE THREAD

**Issue by avencherus** [godotengine/godot#22144] opened 2018-09-16 10:52 UTC
**Version - 787be50f**

Earlier there was an issue where scripts weren't be refreshed until a hard reset https://github.com/godotengine/godot/issues/21956

Resolved by https://github.com/godotengine/godot/pull/22069, thanks to @scayze.  X)

However, there appears to be another issue.  The things in the edited scene related to script changes aren't recognized, and there seems to be also some issues with tool script, but much harder to verify, since other things can mess up tool scripts just as easily.

For example, editing the name of this export var in this example below.

# GDScript editor correctly reloads.
![45587060-f967b380-b908-11e8-8523-6a55f40ea144](https://user-images.githubusercontent.com/13004169/45595616-5752d480-b9b7-11e8-8c0f-89f2cee6b88a.png)

# Inspector doesn't acknowledge until restart.
![45587061-fb317700-b908-11e8-8cc3-ac047fbdb9a6](https://user-images.githubusercontent.com/13004169/45595617-58840180-b9b7-11e8-8ecf-fac208f8caba.png)

**Comment by PLyczkowski** [comment] 2018-09-18 18:48
Can confirm, exported vars are not updated in the property editor on external script change.

**Comment by avencherus** [comment] 2018-09-21 20:07
Thanks for verifying.  X)

**Comment by grenzionky** [comment] 2019-02-03 18:16
just bumping this cuz i still have this issue in feb 2019

**Comment by KoBeWi** [comment] 2019-04-18 21:22
Related: #20250

**Comment by Calinou** [comment] 2019-12-14 22:41
Duplicate of #17044.

**Closed by Calinou** 2019-12-14 22:41 UTC
Labels: bug, topic:editor
