### ISSUE TITLE
Undo fails to fully restore parenting control to container

### ISSUE THREAD

**Issue by pigigi** [godotengine/godot#44629] opened 2020-12-23 19:24 UTC
**Godot version:**
3.2.1 stable

**OS/device including version:**
Windows 10

**Issue description:**
Undoing an operation that reparents a control to a container undoes the parenting but doesn't undo the modifications that the container applied to the child control's anchors, margins, etc.

**Steps to reproduce:**
- Have some controls set up.
- Add a a container node.
- Reparent control to container.
- Undo -> the re-parented control finds its original place jn the hierarchy but keeps the anchors, margins, position and size the container assigned to it.
- Hope you remember your setup, or reload the scene.

**Minimal reproduction project:**
Trivial.

**Comment by TheSofox** [comment] 2023-11-21 16:04
I've got a solution made for this, even got a Pull Request primed, but I'm hitting one super frustrating problem.

Namely, I can restore Size and Anchors (margins/offsets/position seem to have already been sorted), but when I check the UI, the "Layout Mode" stays at "Positioned" rather than "Anchors". The Control still behaves according to the restored anchors, and if you switch "Layout Mode" from "Positioned" to "Anchors" it'll auto select whatever Anchor settings you've used before, however the GUI is still displaying an incorrect value immediately after the undo.

I've tried fixing it, but all the functions to update Layout Mode (in control.cpp) are private, so I can't make an Undo call to sort it out.

**Comment by TheSofox** [comment] 2023-11-21 16:38
Turns out Layout Mode is more broken than I thought specifically Position mode. (You can set it to Positioned (hiding the Anchor menu) and save scene, but when you reload scene the Anchor menu appears again; You can programmatically change the anchors in a @tool script, but Layout Mode will still say "Position" rather than "Anchors", etc.)

Since there's no point in waiting for all the work that needs to be done to fix the Layout Mode in the GUI, I'm making my pull request to fix the specific issue outline in this bug report, which it effectively fixes.

**Comment by YuriSizov** [comment] 2023-11-21 16:44
@TheSofox Layout mode is just an editor tool, it's not a property that in any way restricts or controls the layout properties. If the anchor menu appears, then the current anchor setup does not map to the top-left config and if the anchors preset is set to custom at the same time, then the setup doesn't map to any config at all.

**Comment by TheSofox** [comment] 2023-11-21 17:00
That's definitely how it should work, but I swear I've managed to get it to defy that behaviour, maybe I should file a separate bug report.

In any event, I've changed the pull request by using _edit_set_state as you've suggested and it now works better than before, including fixing up this issue since it copies across Layout State. So thanks for your help there, this should be all we need to close this bug.

**Comment by YuriSizov** [comment] 2023-11-21 17:02
> maybe I should file a separate bug report.

You just as well might if you can still reproduce it afterwards, because this one is for Godot 3, which didn't have layout mode or any other related changes.

**Comment by TheSofox** [comment] 2023-11-21 17:39
Posted bug report on what I described, complete with example project: #85185 
As for that other bug about reloading scene, I think that was caused by me fiddling with the source code so no worries there.
Thank you again for your help with this. While it is an old issue, I was able to repro it on master, so figured it would be best to fix it and close it.

**Closed** 2023-12-04 22:11 UTC
Labels: bug, topic:editor, topic:gui
