### ISSUE TITLE
Popupmenu reopened instead of closed when the popup button is clicked

### ISSUE THREAD

**Issue by varshard** [godotengine/godot#39158] opened 2020-05-30 03:29 UTC
**Godot version:**
Commit 0f1da724924fc494bfd316c57757e0e1d7b90143

**OS/device including version:**
OS: Windows 10
GPU: Intel Iris
backend: Vulkan

**Issue description:**
When I open a popup menu on an inspector, then click the popup menu button again, the popup menu is reopened instead of closed.

I see that in Godot 3.2, both the selected value and the downward chevron are integrated into a single dropdown button, but Godot 4.0 is separating them into a dropdown button and a dropdown trigger (selected value).

**Steps to reproduce:**
1. Create an Environment node.
1. Click on the Environment popup button on the node's inspector to open a popup menu.
![image](https://user-images.githubusercontent.com/5525345/83318497-b9bd3880-a25f-11ea-9ddf-575dd02c633a.png)
1. Click on the popup button again. The popup menu is closed and then reopen, instead of being closed.

**Minimal reproduction project:**
This is reproducible in any project.

**Comment by varshard** [comment] 2020-05-30 05:28
I would like to try to make a contribution. However, Godot code base pretty big. I would appreciate some guidance 😄 
Hope all is contained in popup_menu.h

**Comment by dreamsComeTrue** [comment] 2020-05-30 08:46
That's how it was working before - 3.2 has the same mechanics when clicking on that arrow? Should it be really altered, what's the benefit in here?

**Comment by HaSa1002** [comment] 2020-05-30 11:41
It is fixed by #38340

**Comment by HaSa1002** [comment] 2020-05-30 11:43
It's a bug, because the MenuButton doesn't respect the visibility when opening the Popup

**Comment by varshard** [comment] 2020-05-30 14:08
> 
> 
> That's how it was working before - 3.2 has the same mechanics when clicking on that arrow. Should it be really altered, what's the benefit in here?

If I opened a dropdown, then decided to not change the value, then instead of just simply click the button again without having to move the cursor, I would have to move the cursor somewhere and click the mouse to close the menu. Well, I can just press Esc, but that's more like a workaround .

**Comment by HaSa1002** [comment] 2020-05-30 14:13
Well turns out I actually broke the button completly. I thought, it's the same button. I have to check that... But I have to touch the PR again anyway

**Comment by varshard** [comment] 2020-05-30 14:24
@HaSa1002 I've tried to understand the codebase and failed to comprehend them. 😆 Guess, I need more time and stronger C++.

**Comment by HaSa1002** [comment] 2020-05-30 14:45
Go for an easy reproducible issue and follow the red line of the callstack. That's the easiest way of finding out what matters. You find the entry point in the platform, btw

**Comment by Calinou** [comment] 2022-11-09 18:23
This appears to be fixed as of 4.0.beta4. Here, I'm single-clicking to open and close the popup at first, then double-clicking to open and close:

https://user-images.githubusercontent.com/180032/200910707-be3b6780-2cb4-4ae2-9c88-50a750e732f4.mp4

**Closed by Calinou** 2022-11-09 18:23 UTC
Labels: bug, topic:editor, topic:gui
