### ISSUE TITLE
varying in light shader

### ISSUE THREAD

**Issue by Mavhod** [godotengine/godot#18460] opened 2018-04-27 06:09 UTC
**Godot version:**
v3.1.dev.costom_build.6faa96f

**OS/device including version:**
Arch linux, Geforce 1050

**Issue description:**
I want to pass value from fragment shader to light shader with varying. But it wrong render when assign vaule in fragment. (In picture below, it show the white bar in front screen.)

https://photos.app.goo.gl/G7pIrNywFBPyKpbr1

![photo](https://lh3.googleusercontent.com/1olDUl0Yyr1e35P3JY5v96FHRmsYFLTwAixAQ_nPaBmtwHwUDWdUrV74lRV-0pYETfJG9piHsqHGUDXNwvEIFc2vAmzeUNYrsaRpbrSnqIcVuhZCRDLv_Q1Wpiq7KLmv0Ss-IrvwuQ=w1284-h812-no)

**Steps to reproduce:**

**Minimal reproduction project:**
https://www.dropbox.com/s/t17vsln1g6ijn9h/testShader.zip?dl=0

**Comment by EIREXE** [comment] 2018-04-29 03:59
I don't think this is a bug, I believe this is intentional. Although someone else should confirm.

**Comment by panzergame** [comment] 2018-04-29 13:00
I think I found a cause of the bug.
Fragment and light functions live in the GLSL fragment shader, varying is translated to in variable on vertex shader and in out variable in fragment shader, but it's illegal to assign something on out variable.

**Comment by Megalomaniak** [comment] 2018-05-08 10:45
Your varying should be defined _before_ `void vertex() {}`

**Comment by Chaosus** [comment] 2018-08-21 07:28
_Varying can only be assigned in vertex shaders. In current master it will print you correspondent error. Its also duplicate of #17349. Closed by bugsquad._

**Comment by Mavhod** [comment] 2018-08-21 11:08
Ok, then how to pass vaule from fragment to light shader. Or it can't?

**Comment by Chaosus** [comment] 2018-08-21 11:36
Not through varyings, light shader is an just an extension of fragment so you can try use some predefined 'out' parameters or uniforms

**Comment by Mavhod** [comment] 2018-08-21 13:55
Some value have to calculate from fragment, such as color from texture in uv map. So it should have passing way from fragment to light shader.

**Comment by Chaosus** [comment] 2018-08-21 14:29
Alright, I leave it opened for other opinions..

**Comment by Megalomaniak** [comment] 2018-11-29 15:06
The lighting pipeline follows the fragment in procedure so I recon you would want to get the light vector pass from previous frame probably, which I do not think is possible(?). Though if you are working on a post process effect it could perhaps work if there was/is a way to get the pass from the framebuffer. This far as I know is only applicable to inferred[1] and deferred[2] renderers where the godot renderer if I'm not mistaken is a forward[3] renderer.

[1: Inferred Lighting](http://www.students.science.uu.nl/~3220516/advancedgraphics/papers/inferred_lighting.pdf)
[2: Deferred rendering](http://http.download.nvidia.com/developer/presentations/2004/6800_Leagues/6800_Leagues_Deferred_Shading.pdf)
[3: Forward+ rendering](https://takahiroharada.files.wordpress.com/2015/04/forward_plus.pdf)

**Comment by fracteed** [comment] 2018-12-01 05:47
thanks @Megalomaniak for the info, that is very useful. I was trying to get the light vector to help with a fake SSS shader I was doing, so I will try to get around this problem some other way.

**Comment by SIsilicon** [comment] 2020-02-06 02:03
If it helps, I could give a suggestion as to how this can be implemented. I'm working on something that's also being affected by this limitation.

So the idea is this.
1. Have a new keyword to define variables used between the `fragment` and `light` functions.
```
lighting vec2 value;
```
2. When converting to glsl code, define these variables before the actual light function.
```
...
vec2 value;
[fragment]
...
```
3. expose these variables in both the `fragment` and `light` function.

That's the gist of it.

**Comment by KoBeWi** [comment] 2020-12-24 16:04
What is the status of this issue on master? (or in 3.2.4, but I doubt something changed)

**Comment by Chaosus** [comment] 2020-12-25 16:42
Yes, nothing changed. Maybe I should try to fix it.

**Comment by Chaosus** [comment] 2020-12-25 16:46
Err, sorry, it was fixed.

**Closed** 2020-12-25 16:46 UTC
Labels: bug, topic:rendering

**Comment by Chaosus** [comment] 2020-12-25 16:51
Varying can only be assigned in vertex shader but can be used in both fragment and light (which currently has)

**Comment by SIsilicon** [comment] 2020-12-25 17:16
You can now pass data from fragment to light shaders?

**Comment by Chaosus** [comment] 2020-12-25 18:14
This code is worked:

```
shader_type spatial;

varying vec3 color;

void vertex() {
	color = COLOR.rgb;
}

void fragment() {
	
}

void light() {
	DIFFUSE_LIGHT = color;
}
```

**Comment by Chaosus** [comment] 2020-12-25 18:23
Damn, this issue causes me confusion - `varying` can be accessed by all vertex/fragment light functions, but this is GLSL mechanism and you cannot set them up in the fragment function to be passed into light function cuz it is possible only through vertex function. I guess there should be another mechanic to pass a local variable to light from fragment

**Comment by Chaosus** [comment] 2020-12-25 19:15
I guess this should remains to be closed since I've already created a proposal for this.
