### ISSUE TITLE
Soft bodies do not work with generated trimesh collision shapes.

### ISSUE THREAD

**Issue by leiget** [godotengine/godot#22438] opened 2018-09-26 00:19 UTC
I've looked for the same issue and haven't found one.

**Godot version:**
8fc92ae

**OS/device including version:**
Xubuntu 16.04

**Issue description:**
Tried using a soft body on a floor that is generated using the "Create Trimesh Static Body" option in the "Mesh" menu in the 3D view with the floor selected. Any vertex that hits the floor gets deleted.

**Steps to reproduce:**
Create a floor. Generate a trimesh static body of the floor. Create a soft body that will touch the floor. The vertices get deleted as they collide with the floor.

**Minimal reproduction project:**
[TriMesh Softbody Issue.zip](https://github.com/godotengine/godot/files/2417529/TriMesh.Softbody.Issue.zip)

**Comment by groud** [comment] 2018-09-28 13:10
cc @AndreaCatania

**Comment by akien-mga** [comment] 2020-01-08 12:35
Is this still reproducible in the latest 3.2 builds?

**Comment by tom-jk** [comment] 2020-07-22 13:17
Testing MRP:
Can reproduce in 3.1.alpha2.
Can't reproduce in 3.1.1.stable, 3.2.2.stable or 3.2.3.beta1

In all three versions that work the softbody goes through the platform as it falls off. I don't know if this is typical/a known issue, or if it signifies an incomplete resolution of this issue (the non-trimesh setup on the left doesn't seem to suffer so bad). video (in 3.2.3.beta1) (length: 0m12s): https://youtu.be/866R2mK4-28

**Comment by akien-mga** [comment] 2020-07-22 13:33
Thanks. I'd suggest that we close this older issue as fixed in 3.1, but you can maybe open a new issue specific to the remaining problem that you identified?

**Closed by akien-mga** 2020-07-22 13:33 UTC
Labels: bug, topic:physics
