### ISSUE TITLE
Antialiasing doesn't work in 2D

### ISSUE THREAD

**Issue by Cube-Logic** [godotengine/godot#64000] opened 2022-08-06 14:13 UTC
### Godot version

3.5-stable

### System information

Windows 10

### Issue description

In short, the MSAA and FXAA in the anti-aliasing menu does not affect 2D games
I know it is a mentioned issue but it has last been posted in 2019 when anti-aliasing worked differently and things have changed since then so I wanted to open this issue again with the relevant info

### Steps to reproduce

Ctrl A - Add any 2D Object
Rotate it, and it'll show jittering lines like the screenshot below
![image](https://user-images.githubusercontent.com/85768334/183252364-f6e48d05-17d4-45e3-8f1f-88ca3bc4afe7.png)

### Minimal reproduction project

[Antialiasing.zip](https://github.com/godotengine/godot/files/9275205/Antialiasing.zip)

**Comment by Calinou** [comment] 2022-08-07 07:18
Duplicate of https://github.com/godotengine/godot-proposals/issues/1297.

**Closed by Calinou** 2022-08-07 07:18 UTC
