### ISSUE TITLE
Anchoring doesnt work on windows + other anchor issues

### ISSUE THREAD

**Issue by Gibbz** [godotengine/godot#7654] opened 2017-01-27 01:12 UTC
**Operating system or device - Godot version:**
ubuntu 16.04
godot 2.2

**Issue description:**
1. Having a popup window anchored to the right side of the screen, so that when the window is resized the panels open up in the right of the screen.
Currently they stay in the same position and ignore anchor option.

2. Also, is there a way to scale the ui to less than the size of 1024x600. When anchoring to the right/bottom, the window when smaller then 1024x600 those elements go off screen. Id like to support 800x600 resolution without this happening...

**Comment by karroffel** [comment] 2017-03-30 18:13
Is this still an issue on master?

**Comment by Gibbz** [comment] 2017-03-31 02:49
yep still an issue in 3.0, anchoring still doesn't work with window dialogs

**Comment by Noshyaar** [comment] 2018-04-10 16:18
First of all thank you for your report and sorry for the delay.

We released Godot 3.0 in January 2018 after 18 months of work, fixing many old issues either directly, or by obsoleting/replacing the features they were referring to.

We still have hundreds of issues whose relevance/reproducibility needs to be checked against the [current stable version](https://godotengine.org/download), and that's where you can help us.
**Could you check if the issue that you described initially is still relevant/reproducible in Godot 3.0 or any newer version, and comment about it here?**

For bug reports, please also make sure that the issue contains detailed steps to reproduce the bug and, if possible, a zipped project that can be used to reproduce it right away. This greatly speeds up debugging and bugfixing tasks for our contributors.

Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

Thanks in advance.

*Note: This message is being copy-pasted to many "stale" issues (90+ days without activity). It might happen that it is not meaningful for this specific issue or appears oblivious of the issue's context, if so please comment to notify the Bugsquad about it.*

**Comment by akien-mga** [comment] 2019-04-15 14:22
> Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

As there was no update since the previous post, we close this issue.

If it is still relevant in the way it was described and discussed above, please comment to ask for it to be reevaluated. If it is only partly relevant, or if the original issue has changed, it would be better to open a new issue (potentially referring to this one) focused on the current state.

**Closed by akien-mga** 2019-04-15 14:22 UTC
Labels: bug, topic:core
