### ISSUE TITLE
mass/weight isn't taken in account when using joints

### ISSUE THREAD

**Issue by razcore-art** [godotengine/godot#10760] opened 2017-08-29 16:59 UTC
Operating system or device, Godot version, GPU Model and driver (if graphics related):
Ubuntu 17.04 - Godot v3.0.alpha.custom_build.3ae1cff

See attached project, there's a light rigidbody (mass = 1) and a heavy one (mass = 500) as you can see they both swing around like they don't care about anything.

[godot-dbg.zip](https://github.com/godotengine/godot/files/1261054/godot-dbg.zip)

**Comment by razvanc-r** [comment] 2017-08-31 12:42
Found that when the rigid body has a child collision shape, then it behaves strangely. See attached project, reds = rigid body has collision shape, green = does not. Problem is without collision shape the rigid body doesn't rotate. Left click = move red, right click move green

[godot-dbg.zip](https://github.com/godotengine/godot/files/1267044/godot-dbg.zip)

**Comment by reduz** [comment] 2017-09-07 01:51
This is not a bug, if a body has no collision shapes there is no way to compute the inertia tensor. As a result it will behave as if it has no mass.

**Comment by razvanc-r** [comment] 2017-09-07 10:57
@reduz, did you check the project? They all have collision shapes. This is a bug.

**Comment by reduz** [comment] 2017-09-07 11:05
ah, I misread the report then, apologies

**Comment by reduz** [comment] 2017-11-06 13:22
Joint code is here. As ar as I can see, mass is respected (apply_impulse is affected by mass)., so anyone willing to understand this and take a look would be welcome.
https://github.com/godotengine/godot/blob/master/servers/physics_2d/joints_2d_sw.cpp

**Comment by dherring** [comment] 2017-12-10 16:27
I don't think the Aug 29 godot-dbg.zip demonstrates a mass-dependent bug.

Although the pendulum masses are different, the StaticMove is forcing a velocity independent of mass.  Thus the force it must apply to each pendulum is proportional to the mass of the pendulum.  As a result, both masses would be expected to move similarly, as shown in the sample project.

Neither pendulum swings in a particularly convincing fashion.  I suspect a thorough review of the entire 2D physics engine could fix this.  Do people want "realistic physics", or does the current engine provide good "game physics"?

**Comment by akien-mga** [comment] 2018-01-08 12:12
We have now entered release freeze for Godot 3.0 and want to focus only on release critical issues for that milestone. Therefore, we're moving this issue to the 3.1 milestone, though a fix may be made available for a 3.0.x maintenance release after it has been tested in the master branch during 3.1 development. If you consider that this issue is critical enough to warrant blocking the 3.0 release until fixed, please comment so that we can assess it more in-depth.

**Comment by reduz** [comment] 2018-09-05 20:50
I will close this as its probably not a bug. This is more or less expected due to how physics engines work, so I am not sure much can be done.

**Closed by reduz** 2018-09-05 20:50 UTC
Labels: bug, hero wanted!, topic:physics
