### ISSUE TITLE
When I say play it doesn't run.

### ISSUE THREAD

**Issue by frkntlr** [godotengine/godot#47474] opened 2021-03-29 22:32 UTC
![image](https://user-images.githubusercontent.com/14142761/112907813-2232ab80-90f7-11eb-8038-82b75a720fcd.png)

**Godot version:**
4.0

**OS/device including version:**
Linux/Gnu/Pop Os

**Problem Description:**
When I press the play button with Godot, it stays black. It does not give an error. Even if I wait for 5 minutes, it still keeps it the same. When I close it gives this error;
```
ERROR: Tried to release invalid id: 9161165242371
   at: _free_internal (drivers / vulkan / rendering_device_vulkan.cpp: 7478)
ERROR: Attempted to release invalid ID: 9186935046150
   at: _free_internal (drivers / vulkan / rendering_device_vulkan.cpp: 7478)
ERROR: Tried to release invalid id: 9169755176964
   at: _free_internal (drivers / vulkan / rendering_device_vulkan.cpp: 7478)
ERROR: Attempted to release invalid ID: 9195524980743
   at: _free_internal (drivers / vulkan / rendering_device_vulkan.cpp: 7478)
ERROR: Tried to release invalid id: 9174050144261
   at: _free_internal (drivers / vulkan / rendering_device_vulkan.cpp: 7478)
ERROR: Attempted to release invalid ID: 9199819948040
   at: _free_internal (drivers / vulkan / rendering_device_vulkan.cpp: 7478)
```

![image](https://user-images.githubusercontent.com/14142761/112908215-ccaace80-90f7-11eb-830e-974c32595149.png)

**Reproductive steps:**

**Minimal breeding project:**

**Comment by pycbouh** [comment] 2021-03-29 22:45
When reporting issues with a master branch build please provide the commit that you've compiled. There is no single 4.0 release so it's impossible to tell which version you are on.

**Comment by Calinou** [comment] 2021-03-29 22:59
@frkntlr Which graphics card model and driver are you using?

**Comment by omggomb** [comment] 2021-03-30 12:03
Make sure to add a light setup to the scene as the preview light and environment is not used in the game. That caused me quite some headache.

**Comment by frkntlr** [comment] 2021-03-30 16:42
@pycbouh ,Sorry. I still haven't been able to master the rules in such a community. Because I don't know exactly on Github.Full version, Godot Engine v4.0.dev.calinou.02471ba44. The build I downloaded from hugo.pro.

@Calinou nvidia gtx 1050ti ,driver 460.56

@omggomb  Yes, when you add light and environment to the scene. He ran. But it doesn't work unless we add it to the stage.

**Comment by mrjustaguy** [comment] 2021-03-30 17:29
Is it possible that you didn't Add an environment and/or light to the tree? 
it's probably Pitch black because there is no light and environment (resulting in no lights, and default env is pitch black), and the preview can give the wrong impression that the scene is lit.

**Comment by frkntlr** [comment] 2021-03-30 18:58
> Is it possible that you didn't Add an environment and/or light to the tree?
> it's probably Pitch black because there is no light and environment (resulting in no lights, and default env is pitch black), and the preview can give the wrong impression that the scene is lit.
> 
> You can add the environment and light that are in the editor by clicking at the sun and globe and clicking add directional light/environment buttons (resulting in the in-editor look) or you can add a Directional Light & Environment to the tree and configure it yourself.
> 
> If that works and you get what you expected, this can be Closed as it's not a bug (aside from the error, which probably doesn't have anything to do with the issue at hand).

Yes, it worked when he added it to the stage. But this way may cause confusion to godot users. But I liked it very much. This is a very practical method.

**Comment by Calinou** [comment] 2021-03-31 09:26
Closing, as this is not a bug but an usability issue (see https://github.com/godotengine/godot-proposals/issues/348).

**Closed by Calinou** 2021-03-31 09:26 UTC
Labels: bug, topic:rendering
