### ISSUE TITLE
There has a bug with AnimationPlayer copy/paste.

### ISSUE THREAD

**Issue by zszen** [godotengine/godot#30137] opened 2019-06-27 20:04 UTC
**Godot version:**
3.1.1

**OS/device including version:**
mac10.14

**Issue description:**
do copy an animation then paste. It will create a new animation. But it is not a new one. If I change eather two it always be change to same. The right way is duplicate the animation.(It should be forbid use copy/paste dup)

![image](https://user-images.githubusercontent.com/1890538/60296671-32818980-9959-11e9-93ca-5cc60ae176a4.png)

**Comment by avencherus** [comment] 2019-06-28 06:49
Might you also be wondering about this?  https://github.com/godotengine/godot/issues/24950

I feel like copy/duplicates creating new resources should be the default behavior, and an extra option for reference copies should be available.

I feel it would also be less mysterious to have clear indications in the UI that the Animation resource is pointing somewhere else.

**Comment by KoBeWi** [comment] 2019-06-28 11:21
Closing as duplicate of #24950

**Closed by KoBeWi** 2019-06-28 11:21 UTC
