### ISSUE TITLE
Why drag and drop an image to the Inspector to set a texture is not available in 3.0?

### ISSUE THREAD

**Issue by alexzheng** [godotengine/godot#9414] opened 2017-06-27 12:17 UTC
**Operating system or device - Godot version:**
3.0

**Issue description:**

It's a vey handy feature to set a texture property for nodes such as Sprite, TextureButton.

**Steps to reproduce:**

**Link to minimal example project:**

**Comment by reduz** [comment] 2017-06-27 12:20
i think it broke

**Comment by akien-mga** [comment] 2017-06-27 13:00
Duplicate of #8676.

**Closed by akien-mga** 2017-06-27 13:00 UTC
Labels: bug, confirmed, topic:editor, usability
