### ISSUE TITLE
Particles2D weird behaviour with scale randomisation and curve

### ISSUE THREAD

**Issue by vybr** [godotengine/godot#15497] opened 2018-01-08 18:21 UTC
**Godot version:** fe841fe

**OS/device including version:** Windows 7 - HD 6950

**Issue description:**
Particles will not scale down to the correct size if I use a curve along with a random value.
It seems as though the curve is ignoring the random part.

**Steps to reproduce:**

1. Create a particle object with a particle material.
2. Set scale random to any non-zero value (I used 1).
3. Create a scale curve, going from 1 to 0.
4. See that some particle sizes do not fully reach 0.

**Comment by pwab** [comment] 2018-01-10 16:02
I adapted my Particles2D testproject to reproduce this issue. You can see this behaviour in the provided images:

**Download project:**
[issue-15497.zip](https://github.com/godotengine/godot/files/1619512/issue-15497.zip)

![litte_guys_1](https://user-images.githubusercontent.com/19271185/34781965-8f8f13b2-f627-11e7-9da4-c4bdf2648afb.png)

![litte_guys_2](https://user-images.githubusercontent.com/19271185/34781971-92509fe4-f627-11e7-83b9-84ea4cde3825.png)

**Comment by reduz** [comment] 2018-09-06 16:47
This can be checked in:
https://github.com/godotengine/godot/blob/master/scene/resources/particles_material.cpp
https://github.com/godotengine/godot/blob/master/scene/2d/cpu_particles_2d.cpp
https://github.com/godotengine/godot/blob/master/scene/3d/cpu_particles.cpp

will probably need fixing in those places

**Comment by pgruenbacher** [comment] 2018-09-15 01:39
![image](https://user-images.githubusercontent.com/3332598/45581040-eb148b80-b865-11e8-8fc1-fa88c0636ced.png)

I'm not sure what the issue is. I'm seeing the particles all approach zero at the end.

**Comment by pgruenbacher** [comment] 2018-09-15 01:41
@pwab is the behavior in the gif different from what you saw?

**Comment by pgruenbacher** [comment] 2018-09-18 14:31
Hmm... I still don't see a "bug" per se. Seems to me that if a particle starts from scale 20 to 0 over lifetime 8 it'll give a fading effect to the human eye. If a particle starts from scale 1 to 0 over lifetime 8, it'll fluctuate at the small scale for awhile and just dissapear at the end. I'm guessing scale=0 doesn't play well in general and it's gonna fluctuate the pixel too with the small floats. Maybe there needs to be an alpha curve too that logarithmic ally fades when approaching zero.

**Comment by pwab** [comment] 2018-09-21 12:03
I can see your point but the fact that particles at scale 1 will

>   fluctuate at the small scale for awhile and just dissapear at the end

in contrast to particles at scale 20 could lead to confusion for the users. The question for me is: Why won't the scale 20 particles disappear at the end all at once (and instead create this fading away effect)?

Or maybe I ask in another way: How to achieve the fading effect with a randomized scale curve? An alpha or color curve would be interesting here but then the small particles will fade away all at once at the end which is different from the effect seen in the last gif (particles reach their size 0 at different times).

**Closed** 2019-09-24 16:05 UTC
Labels: bug, hero wanted!, topic:rendering
