### ISSUE TITLE
Viewports show nothing

### ISSUE THREAD

**Issue by RandomErivanHaub** [godotengine/godot#14515] opened 2017-12-10 16:22 UTC
OS: Fedora 22 64-bit
Godot Version: 3 Beta 1

Viewports do not display their children. The children still function in that they execute code (you can make them print messages, for example) and can be accessed by other nodes.
Importantly, Viewports work fine in Version 2.4.1-Stable.

To reproduce, simply create a Viewport Node and assign children like Panels and MeshInstances.

**Comment by vnen** [comment] 2017-12-10 16:26
I think this intended. If you want to show the contents of a Viewport, you need to add a ViewportContainer node.

**Comment by Web-eWorks** [comment] 2017-12-10 18:10
Viewports perform indirect rendering, and to display them you need either a viewport texture attached to a mesh (for 3d) or a viewport container node (for 2d).

**Comment by RandomErivanHaub** [comment] 2017-12-10 19:07
And then you have to manually set the Viewport size.
It works now, thanks!
The Viewport needing to be a child of the ViewportContainer to render should probably be mentioned in the Viewport description, though.

**Comment by matrem** [comment] 2017-12-10 21:53
https://github.com/godotengine/godot/issues/13271

**Comment by akien-mga** [comment] 2017-12-10 22:03
Closing as duplicate of #13271.

**Closed by akien-mga** 2017-12-10 22:03 UTC
