### ISSUE TITLE
No way to determine which tile in a tilemap has collided with an area2d

### ISSUE THREAD

**Issue by chucklepie** [godotengine/godot#43558] opened 2020-11-15 13:23 UTC
**Godot version:**
3.2.2

**OS/device including version:**
linux

**Issue description:**
I have a tilemap (32x32 tiles), it has a collision layer set.

I fire at a tile and get the result via its area2d collision:
```
func _on_AbstractProjectile_body_entered(body: Node) -> void:
```

In order to find the tile it hit I do the following:
```
var pos=map.world_to_map(position)
var id=map.get_cellv(pos)
```

However, even when not moving and firing at the same tile I get a different, wrong, result.
Example:

![image](https://user-images.githubusercontent.com/12863685/99186118-f1546a00-2745-11eb-8dfb-dc642c22e0de.png)

The tile you can see being hit by the bullet is at location 114,109. This translates to:
min x: 3648
max x: 3680

The debugger stopped at this point saying 3650.735, 3493.999
Giving me 114,109. Which is exactly the tile you see being hit

I then fire again without moving

![image](https://user-images.githubusercontent.com/12863685/99185903-a8e87c80-2744-11eb-8fd2-4ec4c4723e0d.png)

and the position reported is: 3647.91,3493.999

It now reports 113,109 which is the empty tile, i.e. the position is out because world_to_map is transforming 3647.91 to 3647, which is 113. 

The problem is unlike every other node that can interact with a body or area2d, you cannot get the actual thing colliding with you, just the entire tilemap. So even though it is a specific tile reporting the collision you cannot get it.

If your body has a collision shape (or shapes) that are different to the size of the body and it is not centre, there is no way to calculate the actual tile being collided with. This is just a simple collision 2d, but if my body had complex shapes, there is no way to actually find the tile. If the shape_id/area_id returned, say, the tile id then it would be fine, but it doesn't.

**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by chucklepie** [comment] 2020-11-15 13:46
I guess the problem is because you cannot get a collider from an area2d collision you have to use your body's position, which is typically the centre point. Surely there's a better way of having to know a direction and a size of an area2d and apply offsets based on this, in order to get the thing you're actually colliding with...

**Comment by chucklepie** [comment] 2020-11-15 15:04
I didn't mean to close it....

The problem, as I see it, is unlike any other node, you cannot get a position from an area2d collision because there is no 'position' for a map and you cannot get a tile position.

**Comment by Calinou** [comment] 2021-05-20 00:30
Duplicate of https://github.com/godotengine/godot/issues/24739.

**Closed by Calinou** 2021-05-20 00:30 UTC
Labels: topic:core
