### ISSUE TITLE
Unicode error: invalid skip when using the "Build" button

### ISSUE THREAD

**Issue by AndreSacilotto** [godotengine/godot#59299] opened 2022-03-18 22:18 UTC
### Godot version

3.4.3 - 64 bits

### System information

Windows 10, AMD Ryzen 5 1600

### Issue description

When click the build button in a mono project it outputs a error "Unicode error: invalid skip". I don't know what causes it, but i don't like to see a error showing up every time I need to re-build the solution.

![Capturar](https://user-images.githubusercontent.com/66838864/159091105-1c34be48-eedc-4031-befd-7add96629951.JPG)

The strange part is that it's only appears when using that button, if I simply hit play the error don't appear.
I also tested in the version 3.3 and the error is also there.

### Steps to reproduce

1. Create a new Mono Project
2. Create a new C# script (this is only for creating the solution)
3. Click the "Build" button at top right
4. Look at the Output you should have a "Unicode error: invalid skip"

### Minimal reproduction project

[New Unicode.zip](https://github.com/godotengine/godot/files/8307762/New.Unicode.zip)

**Comment by Calinou** [comment] 2022-03-18 22:22
Duplicate of https://github.com/godotengine/godot/issues/40576.

**Closed by Calinou** 2022-03-18 22:22 UTC
