### ISSUE TITLE
viewport.set_input_as_handled() doesn't work as expected for collisionobjects

### ISSUE THREAD

**Issue by kilojool** [godotengine/godot#70474] opened 2022-12-23 11:03 UTC
### Godot version

v4.0.beta9.mono.official [e780dc332]

### System information

Windows 10

### Issue description

Using the input_event signal on two overlapping CollisionObject2D, both signals are called, which seems reasonable. Calling viewport.set_input_as_handled() does not seem to prevent the input event from spreading however. I assume this isn't the intended behavior?

### Steps to reproduce

Create two CollisionObject2D such as Area2D and give them each an overlapping CollisionShape. Connecting the input_event signal on both of them, you'll see that calling viewport.set_input_as_handled() does not seem to help.

In the test project, just try clicking the overlapping area.

### Minimal reproduction project

[PickableTest.zip](https://github.com/godotengine/godot/files/10294524/PickableTest.zip)

**Comment by KoBeWi** [comment] 2022-12-23 12:12
Duplicate of #48788

**Closed by KoBeWi** 2022-12-23 12:12 UTC
