### ISSUE TITLE
Godot game crashes upon resizing/toggling fullscreen if multi-threaded rendering is enabled

### ISSUE THREAD

**Issue by OctagonIsAnAmazingShape** [godotengine/godot#75344] opened 2023-03-26 03:44 UTC
### Godot version

v4.0.1.stable.official [cacf49999]

### System information

Windows 11, Vulkan API 1.3.237 - Forward+ - AMD Radeon RX 6600 (Driver version 23.3.1)

### Issue description

Godot crashes when changing window size or going fullscreen if `rendering/driver/threads/thread_model` is set to multi-threaded. Single-threaded works perfectly. It only crashes the player, not the editor. In some cases, it causes a driver reset due to a timeout. I use an AMD RX 6600 (Driver version 23.3.1) with Vulkan API 1.3.237. 

I get these errors in particular:

E 0:00:01:0289   swap_buffers: Error code: **VK_ERROR_DEVICE_LOST**
  <C++ Error>    Condition "err" is true. Returning: ERR_CANT_CREATE
  <C++ Source>   drivers/vulkan/vulkan_context.cpp:2504 @ swap_buffers()

E 0:00:04:0296   _update_swap_chain: Condition "err" is true. Returning: **ERR_CANT_CREATE**
  <C++ Source>   drivers/vulkan/vulkan_context.cpp:1970 @ _update_swap_chain()

E 0:00:04:0329   Environment.gd:9 @ _input(): Condition "err" is true. Returning: **ERR_CANT_CREATE**
  <C++ Source>   drivers/vulkan/vulkan_context.cpp:1970 @ _update_swap_chain()
  <Stack Trace>  Environment.gd:9 @ _input()

E 0:00:04:0335   _update_swap_chain: Condition "err" is true. Returning: **ERR_CANT_CREATE**
  <C++ Source>   drivers/vulkan/vulkan_context.cpp:1970 @ _update_swap_chain()

E 0:00:04:0335   swap_buffers: Vulkan: Cannot submit graphics queue. Error code: **VK_ERROR_DEVICE_LOST**
  <C++ Error>    Condition "err" is true. Returning: ERR_CANT_CREATE
  <C++ Source>   drivers/vulkan/vulkan_context.cpp:2357 @ swap_buffers()

E 0:00:04:0336   _update_swap_chain: Condition "err" is true. Returning: **ERR_CANT_CREATE**
  <C++ Source>   drivers/vulkan/vulkan_context.cpp:1970 @ _update_swap_chain()

This does NOT occur on my laptop (Intel UHD 605), so it's a system issue, despite being able to resize other vulkan games just fine.

### Steps to reproduce

1. Create a project and set up a test scene
2. Set `rendering/driver/threads/thread_model` in settings to multi-threaded
3. Resize the window or toggle fullscreen using this script:
4. 
```
func _input(event):
	if event is InputEventKey and event.is_pressed():
		match event.keycode:
			KEY_ESCAPE:
				get_tree().quit()
			KEY_F11:
				if get_window().mode == Window.MODE_WINDOWED:
					get_window().mode = Window.MODE_FULLSCREEN
				else:
					get_window().mode = Window.MODE_WINDOWED
```

### Minimal reproduction project

[Crash.zip](https://github.com/godotengine/godot/files/11070723/Crash.zip)

**Comment by Calinou** [comment] 2023-03-26 17:19
- Duplicate of https://github.com/godotengine/godot/issues/64766.

**Closed by Calinou** 2023-03-26 17:19 UTC
