### ISSUE TITLE
Boot splash cannot be transparent

### ISSUE THREAD

**Issue by FireCatMagic** [godotengine/godot#100541] opened 2024-12-18 03:10 UTC
### Tested versions

4.4-dev6

### System information

Godot v4.4.dev6 - Windows 10.0.19045 - Single-window, 1 monitor - OpenGL 3 (Compatibility) - NVIDIA GeForce RTX 4050 Laptop GPU (NVIDIA; 32.0.15.6070) - 13th Gen Intel(R) Core(TM) i5-13500HX (20 threads)

### Issue description

![Image](https://github.com/user-attachments/assets/5e83feb1-fa19-46d2-a5d4-3f7396e6c975)
Docs say you can use a transparent splash screen, but...

As you can see, it makes a solid black boot instead of being transparent.
![Image](https://github.com/user-attachments/assets/35fd25c3-d0a9-416e-ac5e-473f792910ea)

### Steps to reproduce

Make a transparent splash screen, notice it isn't transparent

### Minimal reproduction project (MRP)

[New Compressed (zipped) Folder.zip](https://github.com/user-attachments/files/18174235/New.Compressed.zipped.Folder.zip)

**Comment by tetrapod00** [comment] 2024-12-18 05:48
Duplicate of https://github.com/godotengine/godot/issues/91543 I think

**Comment by Chaosus** [comment] 2024-12-18 10:24
Duplicate of https://github.com/godotengine/godot/issues/91543

**Closed by Chaosus** 2024-12-18 10:24 UTC
