### ISSUE TITLE
RichTextLabel size not adjusted by (HBox/VBox/Grid)Container

### ISSUE THREAD

**Issue by WalasPrime** [godotengine/godot#4055] opened 2016-03-14 18:04 UTC
Windows 10 64bit, Godot 2.0.1-stable

RichTextEditor sets size to 0 in HBoxContainer, VBoxContainer and GridContainer. The control size is not properly adjusted to the container.

**Steps to reproduce:**
1. Create new scene
2. Insert a main node (Node2D or Control)
3. Insert a HBoxContainer, a VBoxContainer, a GridContainer and a RichTextEditor
4. Insert a RichTextEditor to every container (3, there should be 4 RichTextEditors)
5. Enable BBCode in each RichTextEditor, enter some content
6. Optional, add a control to every container as a space filler (buttons, labels, whatever)
7. Start the scene

**Result**
RichTextEditors in the containers are not visible (the one outside works just fine). Additionaly, if you try to resize them in the editor:
VBoxContainer RTE snaps the size to 0 if the height exceeds one line,
HBoxContainer RTE can be resized, but the size is ignored,
GridContainer RTE same as VBoxContainer

**Updates**
Appearantly Containers use the MinSize value as the size (which is 0,0 by default). Setting MinSize makes the element visible, but it's still not adjusted to the text.

**Comment by bojidar-bg** [comment] 2016-03-15 08:27
Looks like a min-size issue to me...

**Comment by WalasPrime** [comment] 2016-03-15 10:38
@bojidar-bg just checked, setting the min size fixes this (values higher than 0)
So I guess the containers just use the MinSize, does RichTextEditor lack the ability to determine it's size?

**Comment by bojidar-bg** [comment] 2016-03-15 11:03
@WalasPrime ~ Well, Label, Button and all other control classes would set some internal min size, and would then pick the maximum of the two min sizes. Also, do you mean that just having a min size would make it resize to the text's length?

**Comment by WalasPrime** [comment] 2016-03-15 11:18
Oh it doesn't fix it in a sense that the control is adjusted, it's just visible now. I'll fix the previous posts.

**Comment by azurvii** [comment] 2016-05-10 18:18
I think this may be a more general issue, not just affecting RTE (not sure if the title could be changed). I have a similar issue with ConfirmationDialog, which also has a 0 size when inserted into a container. Manually setting the min size was able to get it visible properly.

But indeed, auto-sensing its min size should be needed.

**Comment by reduz** [comment] 2016-06-26 20:11
Godot does not provide a width4height implementation to better adjust these kind of controls, so for now the only way is setting a minimum size.

**Comment by akien-mga** [comment] 2018-11-23 15:07
For the reference, the behaviour described in the OP is still the same in the current master branch. Here's the scene resulting from the given steps to reproduce:
[RTLinContainers.tscn.zip](https://github.com/godotengine/godot/files/2611123/RTLinContainers.tscn.zip)

**Comment by Calinou** [comment] 2020-05-19 07:35
Closing in favor of #18260, as it contains more information about the issue at hand.

**Closed by Calinou** 2020-05-19 07:35 UTC
Labels: enhancement, topic:gui
