### ISSUE TITLE
loop_offset of AudioStreamOGGVorbis not precise enough in editor

### ISSUE THREAD

**Issue by wareya** [godotengine/godot#41333] opened 2020-08-17 16:41 UTC
**Godot version:**

3.2.1 stable

**Issue description:**

Setting the loop_offset of an ogg audio resource in the editor's import panel causes it to be clamped to the nearest millisecond. This is not precise enough for seamless looping on standard 44.1/48khz audio, and can cause audible clicking when the audio loops, especially if the audio has loud upper bass/low mids.

Instead, it should have at least a hundredth of a millisecond of precision. At least then it would be possible to tweak it until it's pointing at the right sample for standard 44.1/48khz audio.

If other importable audio stream source types have the same problem they should be fixed too.

If the code that controls looping for OGG streams isn't precise enough for this rounding to matter then that would have to get fixed too.

**Comment by Calinou** [comment] 2020-08-17 18:45
Duplicate of https://github.com/godotengine/godot-proposals/issues/84.

**Closed by Calinou** 2020-08-17 18:45 UTC
