### ISSUE TITLE
Node add in animationTree just mix and no add.

### ISSUE THREAD

**Issue by Vicmas21** [godotengine/godot#35474] opened 2020-01-23 15:16 UTC
Godot version: 3.2 rc2

OS/device including version: Window 7 Ultimate Intel HD Graphic 3th generation

Issue description: The Node add in animationTree just mix positions, rotations and scales and no add this

Steps to reproduce: use the animationTree and change between add and blend states for test the node that do samething

Minimal reproduction project:
[Add is Equal to Mix.zip](https://github.com/godotengine/godot/files/4104834/Add.is.Equal.to.Mix.zip)

When try add a animation to other animation just do a interpolation between this...
![sc4](https://user-images.githubusercontent.com/57515508/72996791-aaba0b80-3dd1-11ea-9926-089422e66139.png)
![sc2](https://user-images.githubusercontent.com/57515508/72996794-aaba0b80-3dd1-11ea-9a17-f5ec404056c6.png)
![sc1](https://user-images.githubusercontent.com/57515508/72996795-ab52a200-3dd1-11ea-8fdd-a832e796b8de.png)
![sc3](https://user-images.githubusercontent.com/57515508/72996796-ab52a200-3dd1-11ea-8737-9e3ec6c1df4a.png)

**Comment by groud** [comment] 2020-01-23 16:39
Please fill in the issue template instead of removing it.
I will reopen when this is done.

**Comment by Vicmas21** [comment] 2020-01-23 18:39
Thanks you for say me, is that I am try of add a animation of look around to animation of walk and just blend this...

**Comment by Vicmas21** [comment] 2020-01-23 18:43
Please, reopen this

**Comment by KoBeWi** [comment] 2020-12-12 23:55
Can anyone still reproduce this bug in Godot 3.2.3 or any later release?

**Comment by Calinou** [comment] 2020-12-13 00:24
Duplicate of https://github.com/godotengine/godot/issues/37661.

**Closed by Calinou** 2020-12-13 00:24 UTC
Labels: bug, topic:core
