### ISSUE TITLE
Navigation agents causing 45 millisecond spikes in idle time

### ISSUE THREAD

**Issue by victfv** [godotengine/godot#59363] opened 2022-03-21 00:19 UTC
### Godot version

3.5 Beta 2

### System information

Windows 10, Ryzen 5 3600

### Issue description

Adding a NavigationAgent node as child of a Navigation node causes visible stutter. The frame time graph shows periodic spikes of ~45 milliseconds in idle time.
![image](https://user-images.githubusercontent.com/25274301/159192290-8094d117-dea6-46ab-bfad-600ac3d73d3f.png)

### Steps to reproduce

- Create a scene 
- Add a Navigation node
- Add a NavigationAgent node as a child of the Navigation node
- Start the profiler
- Play

### Minimal reproduction project

[NavAgentStutter.zip](https://github.com/godotengine/godot/files/8312465/NavAgentStutter.zip)

**Comment by Calinou** [comment] 2022-03-21 00:24
Duplicate of https://github.com/godotengine/godot/issues/56838.

**Closed by Calinou** 2022-03-21 00:24 UTC
