### ISSUE TITLE
Creating collision shape for editable instanced scene doesn't work correctly

### ISSUE THREAD

**Issue by AgentSmith0** [godotengine/godot#54706] opened 2021-11-07 09:43 UTC
### Godot version

3.3.4

### System information

Linux, GLES3

### Issue description

The created collision shape node for a editable instanced scene isn't accessible. Only when you reopen the root scene it becomes accessible.

In Godot 3.4 the created CollisionShape will be vanished after reopening the root scene.

### Steps to reproduce

1. Create a new 3d scene, add a MeshInstance node with any shape and save it
2. Create another 3d scene, add the first created scene to it as a child and mark it as editable
3. Then on the MeshInstance that has become editable, create for it any CollisionShape from the Mesh menu on the top right
4. You will see that the generated CollisionShape node won't be accessible

**Comment by AgentSmith0** [comment] 2021-11-08 14:24
Can anybody confirm this issue?

**Comment by Calinou** [comment] 2021-11-08 18:04
Duplicate of https://github.com/godotengine/godot/issues/39494.

**Closed by Calinou** 2021-11-08 18:04 UTC
