### ISSUE TITLE
Low FPS with 3D, and crashes.

### ISSUE THREAD

**Issue by DriNeo** [godotengine/godot#1869] opened 2015-05-08 17:45 UTC
My laptop: Intel(R) Core(TM)2 Duo CPU P8700 @ 2.53GHz, 
                  RAM: 4.00 GB
                  GPU: ATI Mobility Radeon HD 3400 Series 128mb
                  Windows 7 pro
Godot version: 1.1rc2

All 3D demos can't reach 20 fps in editor and needs a lot of CPU percentage. The .exe frequently crashes.

**Comment by Calinou** [comment] 2015-05-08 18:30
This is a very old and low-end card. AMD no longer supports it since 2012, for instance.

**Comment by okamstudio** [comment] 2015-05-08 18:43
these old radeon cards also have horrible opengl support, are you using the
latest drivers anyway?

On Fri, May 8, 2015 at 3:30 PM, Calinou <notifications@github.com> wrote:

> This is a very old and low-end card. AMD no longer supports it since 2012,
> for instance.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/okamstudio/godot/issues/1869#issuecomment-100321119>.
>



-- 

*OkamStudio*

**Comment by DriNeo** [comment] 2015-05-08 18:45
Some precisions : the first Far Cry game runs smootly on this laptop. (Don't know how many fps but my processor level is lower than the kinematic 3D demo). The kinematic 3D demo only displays some cubes !
Perhaps it's an issue with GLES2 ?
I suggest to give your performances in this thread if you want.
http://www.godotengine.org/forum/viewtopic.php?f=9&t=1970

**Comment by silverkorn** [comment] 2015-05-08 20:33
> Perhaps the hardware have a poor compatibility with GLES2 ?

GLES2 is for mobile and embedded devices (ARM / MIPS), your laptop (x86 / x86_64 / x64) is either using DirectX or OpenGL 2.0+.

Just a thought, the issue #1796 says it might not handle properly the kinematic 3D demo either and it literally shutdown. This one is also using an older laptop/hardware... He might also be using an old "deprecated" Radeon video card... 

@reduz, Is it possible that Godot 1.1 will need a higher minimal amount of MB for the GPU or any other similar specs?

**Comment by reduz** [comment] 2015-05-09 16:14
The problem is mainly due to the card having bad OpenGL (which is what Godot uses). This is a card from a time when GPU vendors only cared for Direct3D, so OpenGL support is just bad.

**Comment by DriNeo** [comment] 2015-05-09 16:30
OK. I'm waiting for Windows 10 release to change my PC. 
Good luck to Godot team and Okam !

**Comment by silverkorn** [comment] 2015-05-11 14:25
> This is a card from a time when GPU vendors only cared for Direct3D, so OpenGL support is just bad.

Yeah, I have an old laptop with similar issues, but as mentionned by @DriNeo and @GungnirInd in issue #1796, dismissing realtime shadow could be a workaround for old hardware. 

So an option for old hardware in a custom project disabling this could keep some "legacy" support?
Sorry to insist, I tend to do my best to support people stuck with old PCs and laptops... It's not everyone (or organizations) who's fortunate enough to get our good hardware. :(

**Comment by DriNeo** [comment] 2015-05-11 19:59
It seems baking system may contain shadows. 
Probably with the layers it is possible to have real shadows on the moving objects only, but I'm never tested this. Sorry if I'm write badly, I hope that my post is understandable.

**Comment by kubecz3k** [comment] 2015-11-13 10:50
It looks that this bug was cased because of insufficient gpu. Moving to archive.

**Closed by kubecz3k** 2015-11-13 10:50 UTC
Labels: archived
