### ISSUE TITLE
GDScript: crash in Dictionary validated_set after adding type annotations

### ISSUE THREAD

**Issue by lyuma** [godotengine/godot#47041] opened 2021-03-15 23:35 UTC
**Godot version:**
4.0.dev 8e293bac4e4c75179c0691f358fd8ef57a2bcf93

**OS/device including version:**
Windows 10.0.19041.804

**Issue description:**
EDIT: Made a much simpler test project.

GDScript crashes during in response to some dictionary operation when a dictionary is declared as :Dictionary without an initializer value.

```
CrashHandlerException: Program crashed
Dumping the backtrace. Please include this when reporting the bug on https://github.com/godotengine/godot/issues
[0] OrderedHashMap<Variant,Variant,VariantHasher,VariantComparator,3,8>::find (S:\repo\godot-pr\core\templates\ordered_hash_map.h:197)
[1] OrderedHashMap<Variant,Variant,VariantHasher,VariantComparator,3,8>::operator[] (S:\repo\godot-pr\core\templates\ordered_hash_map.h:245)
[2] VariantKeyedSetGetDictionary::set (S:\repo\godot-pr\core\variant\variant_setget.cpp:1136)
[3] GDScriptFunction::call (S:\repo\godot-pr\modules\gdscript\gdscript_vm.cpp:741)
[4] GDScriptInstance::call (S:\repo\godot-pr\modules\gdscript\gdscript.cpp:1550)
[5] ScriptInstance::call (S:\repo\godot-pr\core\object\script_language.cpp:322)
[6] Node::_propagate_enter_tree (S:\repo\godot-pr\scene\main\node.cpp:217)
[7] Node::_set_tree (S:\repo\godot-pr\scene\main\node.cpp:2520)
[8] Node::add_child (S:\repo\godot-pr\scene\main\node.cpp:1250)
[9] EditorNode::add_editor_plugin (S:\repo\godot-pr\editor\editor_node.cpp:3061)
[10] EditorNode::set_addon_plugin_enabled (S:\repo\godot-pr\editor\editor_node.cpp:3190)
[11] EditorNode::_notification (S:\repo\godot-pr\editor\editor_node.cpp:577)
[12] EditorNode::_notificationv (S:\repo\godot-pr\editor\editor_node.h:93)
[13] Object::notification (S:\repo\godot-pr\core\object\object.cpp:795)
[14] Node::_propagate_ready (S:\repo\godot-pr\scene\main\node.cpp:189)
[15] Node::_propagate_ready (S:\repo\godot-pr\scene\main\node.cpp:179)
[16] Node::_set_tree (S:\repo\godot-pr\scene\main\node.cpp:2524)
[17] SceneTree::initialize (S:\repo\godot-pr\scene\main\scene_tree.cpp:394)
[18] OS_Windows::run (S:\repo\godot-pr\platform\windows\os_windows.cpp:620)
[19] widechar_main (S:\repo\godot-pr\platform\windows\godot_windows.cpp:163)
[20] _main (S:\repo\godot-pr\platform\windows\godot_windows.cpp:187)
[21] main (S:\repo\godot-pr\platform\windows\godot_windows.cpp:199)
[22] __scrt_common_main_seh (D:\agent\_work\9\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288)
[23] BaseThreadInitThunk
-- END OF BACKTRACE --
```

**Steps to reproduce:**
1. Open the project in editor (.../godot.windows.tools.64.exe -e)
2. It will crash
3. Using an external text editor, modify `addons/crashy/plugin.gd` and remove the `: Dictionary` type annotation in the class on line 5
4. Open the project in editor again.
5. It will not crash,

**Minimal reproduction project:**
[TestNullSet.zip](https://github.com/godotengine/godot/files/6145188/TestNullSet.zip)

**Comment by lyuma** [comment] 2021-03-16 00:12
Just updated the description with a much simpler test project now that I know the cause of the crash: a member variable declared as :Dictionary but without an initializer.

**Comment by KoBeWi** [comment] 2021-03-16 00:14
Duplicate of #44442

**Closed by KoBeWi** 2021-03-16 00:14 UTC
