### ISSUE TITLE
CPUParticles2D don't render textures on iOS

### ISSUE THREAD

**Issue by klimi15** [godotengine/godot#34637] opened 2019-12-27 15:15 UTC
**Godot version:**
3.1.2 & 3.2beta4
**OS/device including version:**
iOS / iPad Pro
**Issue description:**
You can assign a shader material to the CPUParticle2D note and will see the particles. But using any Textures, in shader or on the Node will make them not render.
**Steps to reproduce:**
Add CPUParticles2D to scene, add texture.

**Comment by volzhs** [comment] 2019-12-27 15:50
probably same with #32837?

**Comment by KoBeWi** [comment] 2019-12-27 15:51
Seems to be duplicate of #34585

Not sure if https://github.com/godotengine/godot/issues/34585#issuecomment-568762425 is intended

**Comment by klimi15** [comment] 2019-12-27 16:16
i thought i fixed it for me in that, but it is only a strange workaround which seems to be very inconsistent. The Core bug is still there. And it does not render, even if there is no NinePatchRect.

**Comment by klimi15** [comment] 2019-12-28 10:20
There is a constant GLError 500 , when particles are supposed to be drawn. But the Xcode GPU frame debugger (OPEN GL debugger) has be bugged for month and i can't trace the problem.

**Comment by akien-mga** [comment] 2020-01-03 11:25
@klimi15 Are you using `NinePatchRect` as described in #32837?

**Comment by klimi15** [comment] 2020-01-03 16:20
I have traced down the Bug a little more. Since I had no NinePatchRect , it also effects Panels,Buttons,Progress Bars. Not Canvas Items in generell though with Labels in the scene it works.

When those are in the Scene, the GLBindTexture does not seem to work. I have no idea why though.

**Comment by akien-mga** [comment] 2020-01-03 16:32
Thanks for testing! I'll close as duplicate of #32837 then since it's the same issue, and add your comment there as it broadens its scope.

**Closed by akien-mga** 2020-01-03 16:32 UTC
Labels: bug, platform:ios, topic:rendering
