### ISSUE TITLE
Error when (de)capitalizing letter in folder

### ISSUE THREAD

**Issue by MaaaxiKing** [godotengine/godot#38737] opened 2020-05-14 13:05 UTC
**Godot version:**
3.2.1
**OS/device including version:**
Windows 10 Home 1909
**Issue description:**
An error occures when you (de)capitalize any letter of an existing folder. It doesn't even have to have objects in it.
**Steps to reproduce:**
Create a folder named "test". Rename it to "Test".
**Minimal reproduction project:**

**Comment by Calinou** [comment] 2020-05-14 14:34
Duplicate of #19592.

**Closed by Calinou** 2020-05-14 14:34 UTC
