### ISSUE TITLE
Improve Node Selection via Plugin Script

### ISSUE THREAD

**Issue by remorse107** [godotengine/godot#23913] opened 2018-11-22 22:11 UTC
Currently working on a plugin that will be a Node2D type because I want the custom draw and nothing else.  I can see plugins wanting to do this, but the plug-in support for node selection from the canvas feels "second class" compared to the other built-in types.

Requesting a feature to support improved selection in the editor from within the plugin script. 

![godot](https://user-images.githubusercontent.com/7462993/48922988-305dc680-ee70-11e8-9165-d9964feba9a9.gif)

**Comment by Calinou** [comment] 2021-09-01 17:55
Duplicate of https://github.com/godotengine/godot/issues/15599.

**Closed by Calinou** 2021-09-01 17:55 UTC
Labels: enhancement, topic:editor
