### ISSUE TITLE
Pressing F8 stops the project even if the shortcut has been changed in the editor settings

### ISSUE THREAD

**Issue by NikeYoungFr** [godotengine/godot#23929] opened 2018-11-23 16:20 UTC
**Godot version:** 3.0.2 stable

**OS/device including version:** Windows 10

**Issue description:** By default, F8 stops the running application. Since I wanted to use this key in my game, I disabled the shortcut (set it to "None") in the editor setup window... Despite this, pressing F8 still interrupts the game! 

Do I need to change something else, or is this a bug?

**Comment by Zylann** [comment] 2018-11-23 16:58
Isn't this a shortcut of the debugger? If it is, it can be changed in editor settings

**Comment by NikeYoungFr** [comment] 2018-11-23 17:18
I disabled it in editor settings but it keeps closing my game when I press
it!

**Comment by aaronfranke** [comment] 2018-11-24 08:00
Confirmed.

Before changing any settings, config says F8 closes project. pressing F8 closes project.

After changing to F9, config says F9 closes project. pressing F9 does nothing, pressing F8 closes project.

**Comment by akien-mga** [comment] 2018-11-29 09:57
<kbd>F8</kbd> is hardcoded in `SceneTree` as a way to force close the application when running with the debugger: https://github.com/godotengine/godot/blob/80a90ca824b3dd82ced0b047877949bb2f076a3e/scene/main/scene_tree.cpp#L420-L426

**Comment by aaronfranke** [comment] 2018-11-29 17:10
Still doesn't explain why rebinding the close key to F9 means that F9 doesn't work.

**Comment by KoBeWi** [comment] 2019-06-17 19:00
Sooo, the shortcut is defined, but never used in the code. And seems like it might be impossible to use it, because we'd have to access editor's shortcuts from inside the game (it's perfectly possible in the editor tho).

**Comment by NikeYoungFr** [comment] 2019-06-17 20:09
Might we, at least, disable this fonction from SceneTree ?

SceneTree.disableExitWhenF8isPressed() !? :-)

**Comment by NikeYoungFr** [comment] 2019-06-17 21:25
...or, even better :

SceneTree.setExitKey(scancode)

where a special value would inhibit the function...

-----Message d'origine-----
De : "Tomek" <notifications@github.com>
Envoyé : ‎17/‎06/‎2019 21:01
À : "godotengine/godot" <godot@noreply.github.com>
Cc : "NikeYoungFr" <nlejeune@gmail.com>; "Author" <author@noreply.github.com>
Objet : Re: [godotengine/godot] Pressing F8 stops the application even ifthis shortcut has been disabled? (#23929)

Sooo, the shortcut is defined, but never used in the code. And seems like it might be impossible to use it, because we'd have to access editor's shortcuts from inside the game (it's perfectly possible in the editor tho).

**Comment by KoBeWi** [comment] 2020-07-22 11:18
Still valid in 1ab0644

The code looks slightly different now:
https://github.com/godotengine/godot/blob/e196b8127c9e3f937011da1790a02160a3473ab5/scene/main/window.cpp#L887-L893

Probably the best solution would be passing the shortcut using debugger.

**Comment by jitspoe** [comment] 2021-04-09 03:38
Just ran into this myself -- screen-to-gif uses F8 to stop recording, so I wanted to make it so godot doesn't exit the game when I stop recording, but changing the key binding does nothing.

**Comment by Avtem** [comment] 2022-08-14 05:44
Maybe if devs do not plan to fix this bug and leave F8 hardcoded, then remove this option from the "Shortcuts" window to not confuse users?

**Comment by KoBeWi** [comment] 2022-08-14 10:30
There is a fix for this issue already, but it's awaiting a review 🙃
Also the shortcut if functional in the editor.

**Comment by Avtem** [comment] 2022-08-14 13:10
Oh, that is so great! Although it might be worth to try it fix myself first)

**Closed** 2022-08-30 17:29 UTC
Labels: bug, topic:editor, confirmed, usability
