### ISSUE TITLE
.OGG files are played back with rolled-off high frequencies (low-pass)

### ISSUE THREAD

**Issue by nicolasGab** [godotengine/godot#49131] opened 2021-05-27 08:02 UTC
**Godot version:** 

3.3 MONO

**OS/device including version:**

MacOS 10.13.4
Windows 10

**Issue description:**

When playing game audio from `.ogg` files, high frequencies (notably above 10kHz) are attenuated. Upon measuring frequency levels for a single track, I found a 10dB difference around 15kHz between the original (`.ogg`) audio and the game playback (see following graphs). This does not happen when using `.wav` files.

In the following graphs I've zoomed in on the high frequency range, 5kHz-22kHz, as the rest of the spectrum appears rather unaltered.

_DAW audio (OGG) maximum frequency levels (average between left and right channels)_
![DAW audio avg 5k-22k](https://user-images.githubusercontent.com/28801257/119785326-652eb680-becf-11eb-882c-b6d77c17135c.png)

_Game audio loopback (OGG) maximum frequency levels (average between left and right channels)_
![Game audio avg 5k-22k](https://user-images.githubusercontent.com/28801257/119785633-acb54280-becf-11eb-9fe1-3a897d3c5080.png)

The `.ogg` file used in this example has a sample rate of 44.1kHz.
Tests were executed on MacOS 10.13.4 with Reaper DAW; game audio was routed to the DAW with "Loopback" software from [Rogue Amoeba](https://rogueamoeba.com/loopback/) and analysed using Blue Cat's FreqAnalyst VST.
Audio playback with VLC media player was also recorded through "Loopback" and analysed. While there is a difference between VLC loopback and DAW playback, it is mostly after 18 or 20kHz, this may or may not be caused by the "Loopback" software. Frequency levels between 10kHz and 15kHz remain similar to the original audio.

_VLC audio loopback (OGG) maximum frequency levels (average between left and right channels)_
![VLC audio avg 5-22](https://user-images.githubusercontent.com/28801257/119788099-22baa900-bed2-11eb-9a50-4d3c040732fd.png)

**Steps to reproduce:**
- Open an empty Godot (mono v3.3) project
- Add an *AudioStreamPlayer* node with an OGG audio file set to autoplay.
- Launch the scene to trigger audio playback
- Hear or measure the HF dip

This issue was confirmed by another *Godot Engine* Discord server user on Windows 10.

**Comment by Calinou** [comment] 2021-05-27 08:30
Related to https://github.com/godotengine/godot/issues/23544#issuecomment-779589051 (possible duplicate)?

**Comment by nicolasGab** [comment] 2021-05-27 09:21
There seems to be a similar issue with MP3s, both audibly and measured:

_DAW audio (MP3) maximum frequency levels (average between left and right channels)_
![DAW mp3 crop](https://user-images.githubusercontent.com/28801257/119800930-83031800-bedd-11eb-8795-835faa6cf3b9.png)


_Game audio loopback (MP3) maximum frequency levels (average between left and right channels)_
![Game mp3](https://user-images.githubusercontent.com/28801257/119800950-86969f00-bedd-11eb-905d-5c4e20cb84a9.png)

We see the same -10dB around 15kHz

**Comment by nicolasGab** [comment] 2021-05-27 09:30
Just to specify the issue: the music sounds like it's going through a (very wide) low-pass filter, it does not sound like bad compression artifacts

**Comment by Calinou** [comment] 2021-05-27 09:44
@nicolasGab Can you reproduce this in 3.2.3 to check whether this is a regression from Godot 3.3?

**Comment by nicolasGab** [comment] 2021-05-27 13:57
@Calinou Indeed the sound is much better in v3.2.3 (still using a `.ogg` file). It looks very close to the original audio.


_v3.2.3 game audio loopback (OGG) maximum frequency levels (average between left and right channels)_
![v3 2 3 OGG avg](https://user-images.githubusercontent.com/28801257/119838974-1bac8e80-bf04-11eb-956c-8c05e3af3d51.png)

**Comment by nicolasGab** [comment] 2021-05-27 14:13
Godot standard version 3.3.2 has the same problem as 3.3 Mono

v3.3.2 standard game audio loopback (OGG) maximum frequency levels (average between left and right channels)
![Standard v3 3 2 OGG](https://user-images.githubusercontent.com/28801257/119841786-67f8ce00-bf06-11eb-8eec-285de10d990c.png)

**Comment by Calinou** [comment] 2021-05-27 19:10
@ellenhp Any idea what could be causing this? Thanks in advance :slightly_smiling_face:

**Comment by ellenhp** [comment] 2021-05-27 20:02
Weird, this could be an artifact of the resampling changes I made in #46086. From what I read in [the paper](http://yehar.com/blog/wp-content/uploads/2009/08/deip.pdf) I based the changes on it didn't seem like this was likely to happen, and I didn't notice anything like this but my ears are garbage. The ringing from the previous resampling algorithm was pretty awful though, and I'm hesitant to suggest we immediately revert #46086 to fix this.

The easiest way to isolate this issue is to show a difference between playback of OGGs that require runtime resampling and OGGs that do not require runtime resampling, both in Godot 3.3. Any discernible difference is a bug in the resampling algorithm.

@nicolasGab could you try comparing two different OGG files? One that matches your system's sample rate and one that doesn't? 44.1k and 48k, for example, unless your system is using some exotic sample rate. If you need to resample to generate these files, use software you trust and play them both back using an audio player you also trust using good speakers/headphones and/or a spectrogram like you did for the original report (thank you for being so scientific btw!). This is just to verify that the files sound identical using known-good playback software.

Then play them both in Godot. If you have the time I'd love see results from 3.2.3 and 3.3, each with matching/non-matching sample rate oggs. My expectation is:

- 3.2.3 non-matching sample rate: highs will *not* be attenuated, and may actually be sharper than the ground truth especially for clips that have a lot of bass.
- 3.2.3 matching sample rate: audio will will be identical to ground truth, since it won't have to pass through the resampling algorithm at all.
- 3.3 non-matching sample rate: audio will be identical to ground truth
- 3.3 matching sample rate: audio will will be identical to ground truth

This is what I observed while testing #46086, but obviously one or both of the last two statements isn't true on your system. The most compelling thing that you could observe while doing this is that matching and non-matching sample rate OGGs don't even match *each other* in 3.3. That would be alarming.

@ tag me if you gather this data so I don't miss it. I'm not actively following godot development anymore but I do want to make sure this gets fixed.

**Comment by nicolasGab** [comment] 2021-05-28 10:26
@ellenhp 

I made a 48kHz `.ogg` version based on the 44.1kHz `.ogg` (probably should have based it on the original `.wav`...), double checked the sample rate with another software and ran the tests:

- _3.2.3 matching sample rate_ & _3.3 matching sample rate_ have been measured in the previous comments
- _3.3 non-matching sample rate_ has slightly more top end but still exhibits the **-10db** around 15kHz
- _3.2.3 non-matching sample rate_ is a bit different in the high end but is close enough to the ground truth at 10kHz and 15kHz

_v3.3 game audio loopback (OGG) track @ 48kHz, system @ 44.1kHz_
![3 3 OGG 48khz](https://user-images.githubusercontent.com/28801257/119969871-63d4bb00-bfaf-11eb-9843-b60f59a676d8.png)


_v3.2.3 game audio loopback (OGG) track @ 48kHz, system @ 44.1kHz_
![v3 2 3 OGG 48kHz full](https://user-images.githubusercontent.com/28801257/119970092-9da5c180-bfaf-11eb-95cc-89e8a3ba523d.png)


OGG file at 48kHz sample rate
Godot audio settings at 44.1kHz
System audio settings at 44.1kHz

**Comment by ellenhp** [comment] 2021-05-29 16:37
I'm not sure what to do here. All resampling algorithms are pretty much opaque to me so if it is the algorithm I don't think I can fix it. And maybe I'm the only one but I think I'd prefer a 10db low pass compared to this awful ringing: https://zylannprods.fr/dl/godot/GodotLowFrequencySound.mp4

At least with a low pass there's a workaround. :(

It's really interesting to me though that you're seeing this even when the resampling algorithm itself should be a no-op. Perhaps this isn't a resampling bug? Or perhaps the algorithm I picked isn't suitable for this use-case.

**Comment by Calinou** [comment] 2021-05-29 16:38
I wonder if this is similar to what I proposed here: https://github.com/godotengine/godot-proposals/issues/2298

In short, resampling algorithms are a tradeoff. There is no algorithm that will *always* sound better in all situations, and some algorithms are more demanding on the CPU than others.

**Comment by ellenhp** [comment] 2021-05-29 16:43
Yeah. Looking at it now, I think I have a vague sense of why we might be seeing this. The resampling algorithm operates on a window of 4 samples. The challenge for any resampling algorithm is how to take the window of samples it's looking at and correctly interpolate. I'm guessing that the algorithm I picked introduces a low pass filter during interpolation. Imagine for instance if your "interpolation" code just took the mean of the 4 sample window. That would result in an extremely aggressive low-pass. I bet this algorithm unintentionally does something more subtle than that, which is a shame because it got rid of the ringing reported in #23544 completely.

**Comment by ellenhp** [comment] 2021-05-29 16:54
I'm not really an audio person. When I went through and fixed a rash of audio bugs earlier this year it was because I was evaluating Godot for an audio game my friend and I were thinking about making, but we ended up doing other things and I've moved on to other projects. Still, I'd really prefer we not just completely revert #46086 because it would be a shame to have that ringing back for extremely bass-heavy sounds. I really want Godot to succeed on an ideological level even if I'm not actively using it, and major audio bugs make that less likely. But at the same time, 10db attenuation at the high end is a lot. This might also be a major audio bug. :(

**Comment by nicolasGab** [comment] 2021-05-30 10:47
@ellenhp quickly going over the paper you mentioned, I see a lot of comments on compensation, such as (p.17):
```
The second thing to note is that the passband of an interpolator is not flat and this must be compensated for through filtering, possibly in the oversampling stage.
```
I didn't actually read the whole paper, so this might be bad lead, but if we get away with this using a simple EQ boost... it would be a very easy solution.

I'll make a few measurements with white noise to see what kind of attenuation is really going on.

**Comment by nicolasGab** [comment] 2021-06-01 16:07
Hi there @ellenhp @Calinou I managed to generate white noise and feed it into Godot 3.3. The effect is very clear now, below you'll find the original frequency response, then the 48kHz and 44.1kHz game audio and finally an EQ'd version. The game engine and my system are set to 44.1kHz.

_White noise OGG_
![white noise original OGG 44 1kHz](https://user-images.githubusercontent.com/28801257/120350144-ff8f5f80-c2fe-11eb-91e0-df1bca104eee.png)
This white noise lives around -63dB and gives a rough reference to analyze the resampling system.

_v3.3 game audio loopback 48kHz_
![white noise 3 3 OGG 48kHz](https://user-images.githubusercontent.com/28801257/120350425-44b39180-c2ff-11eb-99ce-85443cd2219d.png)
A 48kHz OGG is generated and fed into Godot.

_v3.3 game audio loopback 44.1kHz_
![white noise 3 3 OGG 44 1kHz](https://user-images.githubusercontent.com/28801257/120350661-79bfe400-c2ff-11eb-8e75-b62a0a6c65e5.png)
The same is done with a 44.1kHz OGG file.

The HF dip is much steeper in the 44.1kHz version. We read roughly -7dB @ 15kHz compared to the reference. If we compensate the with an EQ, we can fall back on a track that sound similar to the original file.

_Compensated game audio 44.1kHz_
![white noise compensated 44 1kHz](https://user-images.githubusercontent.com/28801257/120350944-b7247180-c2ff-11eb-95a5-d6ff7e2d2948.png)

A 7dB boost is applied at 15kHz with a Q of 1, as shown in the graphical representation below.

_EQ curve_
![7dB boost at 15kHz, Q=1](https://user-images.githubusercontent.com/28801257/120351065-d28f7c80-c2ff-11eb-9d11-6c3e013e326b.png)

This is obviously not an ideal solution...

These tests were done with a -34dB LUFS white noise track. -70dB vs. -63dB @15kHz is an 11% difference (-7dB).
With a -15dB LUFS white noise track, I observed around -52dB vs. -44dB @15kHz which is an 18% difference (-8dB).

**Comment by ellenhp** [comment] 2021-06-01 16:34
Not sure what to do about this one. The architecture of the audio system doesn't make adding an EQ to compensate for this a simple endeavor from what I remember. The audio effect system is designed to be configurable by the user so I don't know how to hide something like an EQ from the user and do it unconditionally for this type of audio player.

As an aside, @nicolasGab just to unblock your project I wanted to mention that you can move all of your OGG and MP3 players from their current audio bus (call it n) to a new audio bus (call it n+1), and then I forget what the terminology is but you can set that new bus's "master" or "parent" to be the audio bus that you had those players on before (or master if you only had one audio bus). That way the old effect chain is maintained, but you can insert an EQ effect immediately before it. Hopefully the engine has a good enough EQ effect to compensate. Godot's audio documentation isn't quite as good as the docs for the rest of the engine so I wanted to make sure you knew that there is a workaround for this.

The other option to work around this while it's being fixed is just boosting the highs on your actual audio files. Both of these should also work in a fairly cross-platform way since I think the frequency response of this new resampling filter is fairly consistent whether it's actually resampling or not (unlike the old one).

Also I'd like reduz's opinion on how to solve this before I go and build something, I know he's busy but he'll be the one reviewing the code so I think it's reasonable to get him involved early so I don't waste time pursuing dead ends. Perhaps he'll just want to revert #46086 for example.

**Comment by nicolasGab** [comment] 2021-06-02 07:42
Thanks for the tip, I think I can live with rolled-off highs for a few months or more knowing that the issue is taken into consideration. I don't think EQ'ing the original tracks is the way to go, especially if this is fixed in a future release. Thank you for your help!

**Comment by Benedani** [comment] 2021-06-20 16:02
Confirmed on Linux, I guess.

**Comment by troy-lamerton** [comment] 2021-07-06 07:01
To summarize:

- .wav works
- .ogg has strange behaviour at high frequencies

WAV is raw audio (not compressed). OGG is compressed, so godot must decode the audio data before playback.

The cause could be:

A. the .ogg file is invalid/corrupt
B. godot reads the .ogg file incorrectly
C. godot audio playback code messes with the audio of .ogg files

Note that the Opus format is better than OGG, but godot does not support Opus yet.
See: https://github.com/godotengine/godot-proposals/issues/870

**Comment by nicolasGab** [comment] 2021-07-06 08:25
Hi @troy-lamerton, I believe the cause of the problem has already been identified as a side-effect of the resampling algorithm (even when sample rates match). It is detailed in the paper mentioned by Ellen. The high-frequency behavior isn't really strange, it's just a low pass filter.

**Comment by ellenhp** [comment] 2021-07-06 23:30
Just want to reiterate that I'm willing to do the work to fix this but I would like reduz to weigh in on how. I have some ideas but none of them are great.

I noticed in #49759 that there was a complaint about audio quality of the new filter but I really do think that it's preferable to have the frequency response of the audio stream player be near-identical regardless of whether it's resampling or not. As a developer I can't control whether the engine will have to resample a given audio file on any particular user's system, since I don't know the details of their system. I'd prefer to know what the game will sound like when I build it, rather than deal with sound quality issues that only appear on certain systems. Still, it would be nice if we could get those highs boosted back up to a reasonable level.

**Comment by troy-lamerton** [comment] 2021-07-24 13:20
> When playing game audio from `.ogg` files, high frequencies (notably above 10kHz) are attenuated. Upon measuring frequency levels for a single track, I found a 10dB difference around 15kHz between the original (`.ogg`) audio and the game playback (see following graphs). This does not happen when using `.wav` files.

Just checking if the reported issue is already fixed. Because this issue is a deal-breaker for me, I cannot use an engine that has unreliable audio.

So I can build a project with compressed audio files (like .ogg), so nice small build, and they will play correctly?

**Comment by ellenhp** [comment] 2021-07-24 14:53
@troy-lamerton As far as I know this issue has not been fixed, but there are several things you can do to mitigate it, the easiest of which is putting all your mp3s/oggs on a different audio bus and adding an EQ effect to it and boosting the highs yourself. https://github.com/godotengine/godot/issues/49131#issuecomment-852267579

I might go and make a fix but without input from the reviewers upfront I don't expect it'll be merged without some difficulty. I guess I'll just boost the highs of all `AudioStreamPlaybackResampled` streams using the EQ10 code? I think that in this case it is appropriate to just do a straight copy of the audio filter code because reusing it in a one-off way invisible to the user would involve breaking some abstractions that make the design of the audio system really nice.

Adding a separate EQ to each audio stream would make `AudioStreamPlaybackResampled` players scale poorly which I can evaluate on my hardware and report back the results of, if I do come up with a fix. It's no secret that WAV files scale to many simultaneously playing sounds the best, but I think in a lot of cases there are still valid reasons to play many MP3s/OGGs at the same time so it would be good to at least know the performance impact of this before merging.

**Comment by reduz** [comment] 2021-07-24 15:38
My view on this is that, having written plenty of synthesizers and trackers in the past, for such a small amount of resampling (say 44k to 48khz) to hear ringing with cubic interpolation is difficult to understand for me. In my experience, aliasing is heard when there is information loss (from higher to lower hz), but I know some people are very sensitive to those things and my ears are not great (I have high freq tinnitus). I would advise

**Comment by ellenhp** [comment] 2021-07-24 15:42
Sounds good. I agree that cubic *should* be good enough, but the ringing is definitely there. I'll send a PR to revert to cubic and keep digging, maybe the root cause of #23544 is a bug in the resampling algorithm that only exists in the mp3/ogg code. wavs are resampled using cubic resampling as well, but don't display the same ringing

The first post of #23544 has a really egregious example if you want to look at it, by the way. Thanks for weighing in btw! I know you're busy with 4.0 stuff and I appreciate you taking some time for this :)

**Comment by troy-lamerton** [comment] 2021-07-30 18:27
@ellenhp Can you point me to the code that reads the OGG file?

Its easy to misread media metadata, such as the sample rate which is usually in the file header.

I'm familiar with media file specifications and how to read/write audio bytes.

It's also possible that we're seeing another buffer offset bug, similar to the ones that Ellen already fixed.

**Comment by ellenhp** [comment] 2021-07-30 18:49
`modules/stb_vorbis/audio_stream_ogg_vorbis.cpp` is where most of the action happens, and you can follow the code from there into the `thirdparty/libvorbis` code if you're interested. Full disclosure I have a lot of stuff going on in my life right now so my capacity is limited, but I haven't completely given up on this one yet. You're obviously welcome to help though, I'd love more people to take an interest in godot audio. :)

This morning I did the git revert to roll back the PR I made that introduced this lowpass bug then I took a nice walk and now I'm going to try and do take 2 of isolating the ringing described in #23544. I have some suspicions but we'll see if I end up being able to find it.

**Comment by ellenhp** [comment] 2021-07-30 20:14
Reduz was right about cubic resampling sounding great. It turns out that Godot didn't use cubic interpolation though. It used [some polynomial interpolation from stackoverflow that wasn't implemented correctly at all](https://stackoverflow.com/a/1126113). Other folks have commented on how bad that algorithm sounds, which is what #23544 was all about. PR incoming to roll back the change that caused this issue and implement proper cubic resampling.

@nicolasGab could I enlist your help to test the fix? I want to make sure that this is the last resampling PR I need to do, and I don't want to cause any more bugs! :)

Will link the PR in this issue once it's up. I'd love other people to test it too.

**Closed** 2021-08-06 09:27 UTC
Labels: bug, topic:audio, regression

**Comment by nicolasGab** [comment] 2021-09-15 13:17
Hi all, I finally came around to testing this. It looks good, the frequency dip after 10Khz is no more.
@ellenhp 

![white noise gd 34](https://user-images.githubusercontent.com/28801257/133440075-958b4231-43ca-4e74-94cf-9dc16d034bad.png)
