### ISSUE TITLE
Editor window title is flickering when using popups/menu with single window mode off (DisplayServer regression)

### ISSUE THREAD

**Issue by jmb462** [godotengine/godot#53187] opened 2021-09-28 16:54 UTC
### Godot version

Master branch (84b11fbaa674b6e2341de534e93a981378a307ad)

### System information

Windows10 , Linux Ubuntu 21.04

### Issue description

The main editor window loose focus when using menus or popup in multi window mode.
That cause the title flickering between faded state and normal state which is particulary visible using the main editor menu.

![focus](https://user-images.githubusercontent.com/3649998/135131374-6d7e227f-03f3-4d15-b720-b88d580b744d.gif)

![menu_focus_linux](https://user-images.githubusercontent.com/3649998/135676280-3cd46f58-344a-4f41-91ff-397e4359ce5a.gif)
May be related to #44997

### Steps to reproduce

Use main editor menu when single window mode is disabled in editor properties as in the gif below.

### Minimal reproduction project

Not needed.

**Comment by akien-mga** [comment] 2022-02-08 09:02
Is this still reproducible in the current `master` branch?

**Comment by bruvzg** [comment] 2022-02-08 09:14
Popup windows are set to grab focus, since focus change is used to auto hide it when parent is refocused.

There's a window flag to prevent popups from taking focus, but auto hide behavior (which were introduced in #41456) should be completely redesigned to make it work.

I guess we probably should use any mouse press event from the parent to trigger auto hide instead.

**Comment by bruvzg** [comment] 2022-02-08 11:34
Seems like this will be pretty hard to fix, non-focusable windows behave differently on different platforms.
- On Linux FLAG_NO_FOCUS seems to be broken.
- On Windows, FLAG_NO_FOCUS windows are ignoring all input.
- On macOS, FLAG_NO_FOCUS windows are handling input and keyboard focus like any other window.

It might require some sort of global input event handling for the popups to work and be non-focusable.

**Comment by Zylann** [comment] 2022-02-19 20:01
This still happens in 3b3916f4f0eafcd65f7d97bd0ef974766741da37.

On Windows, it's not only the title flickering, but the menu also spawns a taskbar window:
![image](https://user-images.githubusercontent.com/1311555/154817106-dd5a04b6-2c8c-4ab5-a5cf-1a6cdec8106a.png)
So the taskbar wiggles around each time one of these opens, which is quite disturbing

**Comment by bruvzg** [comment] 2022-02-23 14:16
I have been working on this, and as I suspected it won't be easy to fix, but I think I have an outline for a solution.

1. Set `FLAG_NO_FOCUS` for the window (working on macOS, on Linux flag setter/getter is missing, when added it's working fine, on Windows it's also missing some code to properly work, both fixed by #58461).
2. A non-focusable window will not receive keyboard input, so we'll need to track "active" menu window and redirect keyboard input from the parent window.
3. It's non-focusable, so the parent window will retain focus, and we won't receive any event when the user clicks outside a menu. Looks like the only way is it to set up global mouse event hook, to get all mouse event from all windows (other projects, e.g. Firefox seems to use this approach), this can be done on Windows and macOS, but I have no idea if it's possible with X11.
3. On Windows, a non-focusable window also is not receiving MouseMotion events, so these will need to be redirected from the global mouse input hook.

**Closed** 2022-02-25 22:02 UTC
Labels: bug, topic:editor, topic:porting, regression
