### ISSUE TITLE
LMB+RMB in Spinbox during mouse capture refuses to release capture

### ISSUE THREAD

**Issue by nobuyukinyuu** [godotengine/godot#18647] opened 2018-05-06 01:02 UTC
**Godot version:**

3.0.2, master  (At least 3.0.3 rc1)

**OS/device including version:**

Windows 10

**Issue description:**

When using a Spinbox in the runtime, during a dragging event which activates mouse capture (invisible cursor etc), if one accidentally presses the right mouse button during the drag, the cursor will be stuck in a captured and invisible state while the window is in focus.

This likely affects other controls which have similar behavior; though I haven't been able to reproduce it reliably with ColorPicker, this can wreck havoc in the editor when altering an int or float value with constrained bounds in the property inspector, requiring a restart of the editor.

**Comment by Zylann** [comment] 2018-05-06 02:50
Duplicate of https://github.com/godotengine/godot/issues/17891

**Closed** 2018-05-08 07:30 UTC
