### ISSUE TITLE
Crash with Rigid Body Setup

### ISSUE THREAD

**Issue by turtletooth** [godotengine/godot#16157] opened 2018-01-29 05:23 UTC
**Godot version:**
Beta 3

**OS/device including version:**
Windows 10 1709

**Issue description:**
Crash on 3D Node Setup

**Steps to reproduce:**
Create a RigidBody root node
Add a child mesh instance using the built in cylinder mesh
Select the mesh
From the mesh menu at the top next to view and transform, choose create convex static body
Move the created collision shape to be a child of the rigid body
Delete the static body
Save the scene
Close the scene
Reopen the scene.

**Comment by vnen** [comment] 2018-01-29 14:49
> Godot version:
Beta 3

Do you mean Godot 3.0 RC 3? There wasn't a third beta for 3.0.

**Comment by turtletooth** [comment] 2018-01-29 15:03
Yes, sorry- RC1

**Comment by akien-mga** [comment] 2018-01-29 15:11
Can you try with http://op.godotengine.org:81/downloads/3.0/internal3/ ?

**Comment by turtletooth** [comment] 2018-01-29 15:19
I tested it and I still get the crash, but only on cylinder shapes.

**Comment by AndreaCatania** [comment] 2018-09-19 17:14
I tested it, and it seems fixed, can you plaese re-check it?

**Comment by AndreaCatania** [comment] 2018-09-22 08:51
I'm closing it because I can't reproduce it anymore. And it's likely to be fixed.

**Closed by AndreaCatania** 2018-09-22 08:51 UTC
Labels: bug, confirmed, topic:editor
