### ISSUE TITLE
VisualScript: the Load Resource dialog does not contain `.tscn`.

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#26137] opened 2019-02-21 20:48 UTC
Godot 3.1 beta5

I wanted to preload an existing scene in VisualScript, so I used a `Preload` item, and selected `Load` from its `resource` property. However, the dialog does not show scene resources, even though `All Recognized Types` is selected. TSCN is not in the list of specific types, so the only way to make them show up is to go down and select `All Files`, then `.tscn` files can be selected.

**Comment by akien-mga** [comment] 2020-01-14 13:08
Duplicate of #7278.

**Closed by akien-mga** 2020-01-14 13:08 UTC
Labels: bug, topic:editor, topic:visualscript
