### ISSUE TITLE
ERROR: GDScript::_create_instance: Condition ' r_error.error != Variant::CallError::CALL_OK ' is true. returned: 0    At: modules\gdscript\gdscript.cpp:128

### ISSUE THREAD

**Issue by jaykyburz** [godotengine/godot#13440] opened 2017-12-01 09:06 UTC
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Godot 3 Beta 1 (Without Mono)
Was also seeing it in the last Alpha
Windows 10

**Issue description:**

The following error appears in the console, however the game works as I expect.

    ERROR: GDScript::_create_instance: Condition ' r_error.error != Variant::CallError::CALL_OK ' is true. returned: 0
   At: modules\gdscript\gdscript.cpp:128

I'm instantiating a scene that is just one node which is the BBText control. 

I might be doing something dumb, but just wanted to log and issue right away to see if it jumps out to anybody as something obvious. 

I'm new to Godot and Programming. 

If you guys think this is a genuine bug that needs investigating, please let me know and I will do some more work on it to try and work out what is going wrong.

**Comment by JuanDidNothingWrong2** [comment] 2017-12-01 22:40
(Since Noshyaar keeps closing this, I am going to continue to post it until one thread remains visible for discussion, no need to censor)

![](https://i.gyazo.com/364f1b11bc57924374d0a8c81df1eeab.png)

Lead developer sent this message after a user was giving his honest feedback via this [reddit thread](https://www.reddit.com/r/gamedev/comments/7gmtxl/godot_30_beta_1_is_there_right_in_time_for_ludum/dqk9nel/).

They also said (I kid you not) -- giving feedback is "**bullying**",  a "**professional whiner**", and "**ranting**". Reduz's passive aggressive tone and insulting behavior is rampant there.  I already terminated my patreon account because of this, and not saying you should either (FLOSS projects) are great, however, for the lead developer to act like this towards people giving feedback.. is not okay!

Let me re-iterate, not saying that you should stop giving feedback, but I just want this message to be seen across github and reach as far as possible. Because this kind of communication and how the lead developer treats a regular Godot developer is not right at all. I've never seen this behavior from a FLOSS project lead developer.  It's a shame, because the guy giving feedback is just a random person anyway, and the way the project managers and lead developers took it so personally like it was an attack (when it wasn't), means the lead developers/contributors are possibly not viewing your issues with the right mindset.  

Also, after reading the last paragraph from [this post by akien](https://www.reddit.com/r/gamedev/comments/7gmtxl/godot_30_beta_1_is_there_right_in_time_for_ludum/dqlqj2v/)
> From here on, we will avoid responding to xxx's threads on the various Godot communities, and focus instead on the huge amount of constructive feedback and bug reports that we get from other users. This will likely overlap with some of the issues mentioned above, which will thus be fixed eventually, but we won't accept being bullied into working on them now when we have different priorities. Users are free to disagree with our priorities, but in the end the contributors are the ones making the call.

He's saying they will now favor/prioritize issues based on the user reporting it, and not the issue itself. (Extreme prejudice), which will not be good for the project because the issue should be irrelevant to the user reporting it. Just because if a user who has a snotty attitude that is reporting a huge client crash error, doesn't mean that client crash error should not be taken lightly.



He's also stating that anyone giving hard feedback is now "bullying" them. Which is not true whatsoever.

Just wanting to post this to get the word out there, hopefully some things change. @reduz @akien-mga  This is just unbelievable :(

**Comment by bojidar-bg** [comment] 2018-06-06 11:10
Sorry to bother you after so much time... Is this issue still present? If so, can you submit a simple example project so we might look into it? :)

**Comment by djiamnot** [comment] 2018-06-20 23:54
I just run into this issue. This was in the context of creating a plugin with a custom dock. The `EditorPlugin` instantiates a scene which has a `Control`at its root. Adding a script with _tool_ keyword generates the reported error. I can give it a shot to slim my project down to bare elements, if that is helpful. I'm not that far in.

**Comment by djiamnot** [comment] 2018-06-21 12:20
So, no, I cannot reproduce this problem with a project stripped to minimum. I will come back if I run into it again.

**Comment by cobrapitz** [comment] 2019-04-16 11:55
This happened to me. 
When:
- Node as scene root with script attached
- script contains _ready() and _init(), where _init 
```gdscript
extends Node
var value = 1.0

func _ready():
	print("here") # not getting printed and the error appears

func _init(value):
	self.value = value
```
E 0:00:01:0465   Condition ' r_error.error != Variant::CallError::CALL_OK ' is true. returned: __null
  <C Source>     modules/gdscript/gdscript.cpp:129 @ _create_instance()

(bad) workaround:
- create custom init function.

**Comment by Jeto143** [comment] 2019-06-04 20:47
Can confirm. This is somewhat paraphrasing what @cobrapitz said, but in order to simply reproduce this error, just:

1. Create a new project
2. Add a (base) Node as root
3. Attach a script to it containing:

```
extends Node

func _init(foo):
	pass
```

4. Run.

Note that some people could argue that using a non-standard `_init` signature in a node isn't supposed to be done (at least it may not be). I personally like using the scene tab to hold a hierarchy of "script nodes" representing custom objects, as it makes them easier to view/access at any given time. They don't act as nodes in that case, `_ready` / `_process` aren't called, etc, which is actually convenient.

I could obviously just store them as pure scripts and not have to extend Node (and forget about the scene tree hierarchy thing), but before that at least someone can confirm if that's desired behavior or not.

**Comment by CarlGustavAlbertDwarfsteinYung** [comment] 2020-04-16 20:03
I just got this issue without a script attached to the root. In my case the script is on a RigidBody but the  root is a Node. If I change the root to any other node type is still not working. In fact I cannot use any scripts in this project due to this bug.

**Comment by SirRamEsq** [comment] 2020-07-17 01:02
Just faced this issue myself.

I had to have a parameter-less `_init` method in my class. I assume this this is the case because Godot instantiates an object then loads the saved export variables into the instantiated object.

Changed my code from
```
func _init(_begin: float, _end: float):
```

To:
```
func _init(_begin: float = 0.0, _end: float = 0.0):
```

One thing that helped me was the answer given by "Zylann" in this [post](https://godotengine.org/qa/56388/when-can-i-override-_init-with-non-optional-arguments)

Quoted here in case the link ever dies:
> If your script instance is going to be saved/loaded inside a scene, it must have a parameterless constructor, or a constructor with all arguments optional. The reason is, the "state" of the script instance comes from the scene file (variables with export or the STORAGE hint), it's not really building a new one.
> Otherwise it's fine to have arguments in _init, for cases where you are calling it with new in your scripts.

**Comment by songangel72** [comment] 2020-09-09 22:05
Sorry but this is still an issue in Godot 3.2.2 and took me forever to figure out why my custom type wasn't doing anything.  The _init function gets called but called a method of the class does absolutely nothing.

**Comment by CarlGustavAlbertDwarfsteinYung** [comment] 2020-09-10 00:36
To fix this do not use custom _init() functions

**Comment by songangel72** [comment] 2020-09-10 13:06
That is not a fix.  I understand if this cannot be supported but the ability to pass arguments to a "constructor" is an important feature that is currently broken.  At a minimum, an error message that makes sense should be displayed rather than just halting execution of the script.

**Comment by lonegamedev** [comment] 2020-10-05 12:08
The solution is to have default values for every param in _init()
bad:
`func _init(x:int, y:int, z:int, size:float):`
good:
`func _init(x:int = 0, y:int = 0, z:int = 0, size:float = 0.0):`

**Comment by DriNeo** [comment] 2021-08-20 17:57
I fixed the error by removing the nodes with paramtrized _inits from the editor scenetree and I instance them by scripting only.

**Comment by Calinou** [comment] 2022-02-19 18:03
Duplicate of https://github.com/godotengine/godot/issues/15866.

**Closed by Calinou** 2022-02-19 18:03 UTC
Labels: bug, topic:gdscript
