### ISSUE TITLE
Shader material resources not exported in Android APK

### ISSUE THREAD

**Issue by ygingras** [godotengine/godot#88977] opened 2024-02-28 18:50 UTC
### Tested versions

- Reproducible on Godot 4.2.1 with published packages and with self compiled editor

### System information

Linux Ubuntu 23.10 on Wayland with Godot 4.2.1

### Issue description

Shader Material resources are not included inside an exported APK package for Android.

The editor correctly produces and caches those sub resources, but godot in headless mode fails to produce and include them in the exported APK package. When running in an automated CI/CD, such as the F-Droid build pipeline, it's not always possible to start the editor before generating the APK package.

### Steps to reproduce
``` bash
git clone https://gitlab.com/ygingras/godot-shader-res-repro.git
# open the project in the editor, install android export templates, close editor
cd godot-shader-res-repro
rm -rf .godot
godot --headless --export-release 'Android' repro.apk
apksigner sign --ks path/to/dev-keystore repro.apk

# connect an android device via USB
adb install repro.apk
# launch the apk on the mobile device
# the screen is plain grey or greyish blue rather than animated water
``` 

### Minimal reproduction project (MRP)

https://gitlab.com/ygingras/godot-shader-res-repro

The Sprite2D uses a water material that includes a shader and two noise textures. Those display correctly to produce an animated water look when running inside the editor.

**Comment by ygingras** [comment] 2024-02-28 18:58
To see if the problem is present without installing on a device, we can look at `assets/.godot/exported/133200997/export-c4c4fea8197baf42b15b4e3ed1b00e5a-water_material.res` (or similar name) inside the unzipped APK. If `.godot` is not removed after opening the project in the editor, the `.res` files contains the noise textures, but they are absent when exporting without the `.godot` directory.

**Comment by clayjohn** [comment] 2024-02-28 19:37
This sounds like a duplicate of https://github.com/godotengine/godot/issues/66842 or possible https://github.com/godotengine/godot/issues/88187 which have both been fixed in 4.3. We should have a dev4 release ready soon that you can test to confirm

**Comment by ygingras** [comment] 2024-02-28 21:30
That's great! I'm looking forward to try the next dev release.

**Comment by ygingras** [comment] 2024-03-06 01:02
The minimal repro project exports with the required material textures on 4.3-dev4. Nice!

**Comment by clayjohn** [comment] 2024-03-06 03:44
Amazing! Thanks for testing again

**Closed by clayjohn** 2024-03-06 03:44 UTC
Labels: bug, platform:android, topic:export
