### ISSUE TITLE
Godot quits whenever I try to insert a tile

### ISSUE THREAD

**Issue by mrbig033** [godotengine/godot#27587] opened 2019-04-02 07:39 UTC
**Godot version:**

3.1.stable.official

**OS/device including version:** 
MX-Linux 18
OpenGL ES 3.0 Renderer: Mesa DRI Intel(R) HD Graphics 520 (Skylake GT2)

**Issue description:**

Every time I try to insert a tile on the editor, Godot quit.

**Steps to reproduce:**

Try to insert a tile file such as `tile.res` in the editor.

**Minimal reproduction project:**

[ex1.zip](https://github.com/godotengine/godot/files/3032786/ex1.zip)

**Backtrace:**

```
$ ERROR: get: FATAL: Index p_index=0 out of size (size()=0)
At: ./core/cowdata.h:151.
handle_crash: Program crashed with signal 4
Dumping the backtrace. Please include this when reporting the bug on https://github.com/godotengine/godot/issues
[1] /lib/x86_64-linux-gnu/libc.so.6(+0x33060) [0x7f41f1d5d060] (??:0)
[2] /home/programs/godot/Godot_v3.1-stable_x11.64() [0x1494657] (<artificial>:?)
[3] /home/programs/godot/Godot_v3.1-stable_x11.64() [0xa414e9] (??:?)
[4] /home/programs/godot/Godot_v3.1-stable_x11.64() [0x2174733] (??:?)
[5] /home/programs/godot/Godot_v3.1-stable_x11.64() [0x21e4e02] (??:?)
[6] /home/programs/godot/Godot_v3.1-stable_x11.64() [0x21e5e40] (??:?)
[7] /home/programs/godot/Godot_v3.1-stable_x11.64() [0x18dcfb4] (<artificial>:?)
[8] /home/programs/godot/Godot_v3.1-stable_x11.64() [0xa414e9] (??:?)
[9] /home/programs/godot/Godot_v3.1-stable_x11.64() [0x2174733] (??:?)
[10] /home/programs/godot/Godot_v3.1-stable_x11.64() [0x2512a7d] (??:?)
[11] /home/programs/godot/Godot_v3.1-stable_x11.64() [0x21eed3f] (??:?)
[12] /home/programs/godot/Godot_v3.1-stable_x11.64() [0x169af89] (??:?)
[13] /home/programs/godot/Godot_v3.1-stable_x11.64() [0xaf1075] (??:?)
[14] /home/programs/godot/Godot_v3.1-stable_x11.64() [0x7b28ed] (??:?)
[15] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf1) [0x7f41f1d4a2e1] (??:0)
[16] /home/large/godot/Godot_v3.1-stable_x11.64() [0x7bfc4e] (??:?)
-- END OF BACKTRACE --
```

**Comment by CptPotato** [comment] 2019-04-02 08:50
I think this is related to #27360

**Comment by akien-mga** [comment] 2019-04-02 09:41
It's not crashing for me with the provided project on Linux with either 3.1-stable (official build) or 29a1202 (debug build). I used those steps to try to reproduce it:
- Open main.tscn
- Add TileMap node
- Drag and drop tile.res to the TileSet slot in the inspector
- Place tiles on the TileMap

But it does seem to be a duplicate of #27360 indeed, so I'll close it and we can discuss further there.

**Closed by akien-mga** 2019-04-02 09:41 UTC
