### ISSUE TITLE
A log file is generated in the project root directory every time it starts

### ISSUE THREAD

**Issue by skyatgit** [godotengine/godot#79098] opened 2023-07-06 12:32 UTC
### Godot version

Godot_v4.1-stable_win64

### System information

windows11-Godot_v4.1-stable_win64

### Issue description

Every time the project starts, a log file is generated in the project root directory, and when I hover my mouse over the latest log file, it can cause the project to unexpectedly exit
![image](https://github.com/godotengine/godot/assets/42607334/7042a5aa-1664-4353-a7b1-bcfafb311098)

### Steps to reproduce

This will occur when the project starts

### Minimal reproduction project

This includes the log file
[Demo.zip](https://github.com/godotengine/godot/files/11968196/Demo.zip)

**Comment by skyatgit** [comment] 2023-07-06 13:12
This issue will not occur when I start godot as an administrator，I don't know if this issue is related to the project location，I only have C drive, and my project location is C:\Users\12189\Documents\GodotProjects\Demo

**Comment by AThousandShips** [comment] 2023-09-05 15:37
I can't replicate the issue so no clue, and I'm on Windows 11

**Comment by FcAYH** [comment] 2023-09-19 15:25
I have meet the same problem! I have the same situlation as you, both only have C drive. And after I use administrator model to launch godot, this issue will not occur.
I'm confused as to why this log file is a binary file. This makes it impossible for me to get any information out of it.

**Comment by AThousandShips** [comment] 2023-09-19 15:27
Please confirm if the details on https://github.com/godotengine/godot/issues/81652 matches this, seems to be the same error

**Comment by AThousandShips** [comment] 2023-09-19 15:39
Duplicate of #81652

**Closed by AThousandShips** 2023-09-19 15:39 UTC
Labels: bug, topic:editor, needs testing
