### ISSUE TITLE
Mono: Removing/renaming a script from the file explorer corrupts the game

### ISSUE THREAD

**Issue by zaksnet** [godotengine/godot#33494] opened 2019-11-09 18:38 UTC
**Godot version:**
3.2 Beta 1 Mono
**OS/device including version:**
Windows 10 1903
**Issue description:**
If you remove/rename a script from the Filesystem tab then you will get an error that the file is missing whenever you start the game. The only way to prevent this is either by starting visual studio with the provided `.sln` and removing the dependency from there or removing it directly from the assembly file. I would be more than glad to fix this if someone was kind enough to point me at the right files, then maybe i can figure it out.

**Comment by KoBeWi** [comment] 2019-11-09 19:21
Duplicate of #12917

**Closed by KoBeWi** 2019-11-09 19:21 UTC
