### ISSUE TITLE
Node tree node movement bug.

### ISSUE THREAD

**Issue by leiget** [godotengine/godot#6467] opened 2016-09-12 17:56 UTC
**Operating system or device - Godot version:**
Xubuntu Linux 16.04, v2.2.alpha.custom_build, compiled from source.

**Issue description** (what happened, and what was expected):
Say there is a project, and in that project there is a node tree that is in the root tree. If move a node to under that tree, but not _in_ that tree, it becomes apart of that tree, anyway, even if I do not put it in that tree. 
Watch this (starts video at 1:29 with this link): https://youtu.be/uFPI2GcmXrQ?t=89

**Steps to reproduce:**
Please watch link above.

**Link to minimal example project** (optional but very welcome):
Any project will do this.

**Comment by akien-mga** [comment] 2016-09-12 17:59
Please explain the bug with words. A video is great, but words are necessary too, we can't manage 1270 issues if they're all only in video format :)

**Comment by leiget** [comment] 2016-09-12 18:25
Ok, I'll change the text here in a bit.

**Comment by vnen** [comment] 2016-09-12 20:05
If I understood correctly this is a duplicate of #5924.

**Comment by leiget** [comment] 2016-09-12 22:05
Yes, you're correct, vnen. I'm sorry, I'll be sure to look a little better next time.

**Comment by akien-mga** [comment] 2016-09-13 05:37
Closing then (and don't worry, it's fine to make duplicates, we don't expect everyone to have more than a thousand issues in mind when opening a new one).

**Closed by akien-mga** 2016-09-13 05:37 UTC
