### ISSUE TITLE
Tree::create_item does not append item to root if parent is not given

### ISSUE THREAD

**Issue by RayKoopa** [godotengine/godot#14660] opened 2017-12-14 16:09 UTC
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
master

**Issue description:**
Noticed this when adding a new parameter to specify insertion index. From the documentation:
`TreeItem create_item ( TreeItem parent=NULL )`
"Create an item in the tree and add it as the last child of parent. If parent is not given, it will be added as the last child of the root, or it’ll the be the root itself if the tree is empty."

This is wrong, if a root exists, and another item is created without a parent specified, it becomes the new root.
![image](https://user-images.githubusercontent.com/9631152/34006855-1b8f2074-e100-11e7-8e46-d8f317c8e0ec.png)

The if branch handling a NULL parent also invalidates the documentation:
```cpp
if (root)
	ti->childs = root;
root = ti;
```

While I'm at it, should I fix it to behave as mentioned in the documentation? Rerooting the tree doesn't make much sense to me. Then again I wonder if this breaks existing code everywhere.

**Comment by akien-mga** [comment] 2017-12-16 13:53
Duplicate of #12118 I think.

**Closed by akien-mga** 2017-12-16 13:53 UTC

**Comment by reduz** [comment] 2017-12-16 14:02
I would probably just throw an error if you want to create an item without passing a parent and a root already exists, any other behavior seems counterintuitive
