### ISSUE TITLE
Export PoolRealArray saving scene revert to default

### ISSUE THREAD

**Issue by lainv0hndyrec** [godotengine/godot#27575] opened 2019-04-01 12:47 UTC
**Godot version:** 
3.1

**OS/device including version:**
PC

**Issue description:**
creating an export variable of static typed PoolRealArray does not save the changed value in inspector when saving

**Steps to reproduce:**
1. create a scene
2. attach a script
3. type export var Test : PoolRealArray = [10,0,0,0]
4. in the inspector try to change Test[0] in to any float number
5. save the game
6. watch as it reverts back to Test[0] = 10

even if u change the type of the array in the inspector, same results as long as u static type PoolRealArray

for now possible work arround is just declare it as Array instead of PoolRealArray
then in the inspector make each entries float 1 by 1.

**Comment by Zireael07** [comment] 2019-04-01 13:05
Duplicate of #26066?

**Comment by lainv0hndyrec** [comment] 2019-04-01 21:07
yup I saw this yesterday, but I dont know how to open a closed issue as well as its from a beta state, but this time it only happens in PoolRealArray and in 3.1

also in the inspector it is named PoolFloatArray which could be the problem for maybe PoolRealArray is written as PoolFloatArray in the next update of godot 3.0

**Comment by akien-mga** [comment] 2019-04-09 09:45
CC @bojidar-bg

**Comment by bojidar-bg** [comment] 2019-04-09 10:36
Does it work with this code?
```
export var Test : PoolRealArray = PoolRealArray([10,0,0,0])
```

**Comment by akien-mga** [comment] 2020-01-15 11:56
> Does it work with this code?
> 
> ```
> export var Test : PoolRealArray = PoolRealArray([10,0,0,0])
> ```

Yes. `export var Test : PoolRealArray = [10,0,0,0]` fails but the above works.

**Comment by bojidar-bg** [comment] 2020-01-16 13:15
Cannot reproduce on master; found a few other problems, so I opened #35198 nonetheless.

**Comment by akien-mga** [comment] 2020-01-16 13:20
@bojidar-bg I can still reproduce it, the bug happens when you save the scene.
```
export var Test1 : PoolRealArray = [10,0,0,0]
export var Test2 : PoolRealArray = PoolRealArray([10,0,0,0])
```
Set both values to e.g. `[15, 8, 0, 0]` in the inspector.
Save. First one reverts.

Before save:
![Screenshot_20200116_142010](https://user-images.githubusercontent.com/4701338/72528437-4f38cc80-386b-11ea-839c-d41510014418.png)
After save:
![Screenshot_20200116_142026](https://user-images.githubusercontent.com/4701338/72528469-5bbd2500-386b-11ea-89e6-006e2113c921.png)

#35198 sounds like it'd fix it, I'll try it.

**Comment by bojidar-bg** [comment] 2020-01-16 13:38
@akien-mga Oof. I need a reminder to not test problems related to export variables using `tool` scripts...

**Closed** 2020-01-16 13:58 UTC
Labels: bug, topic:gdscript
