### ISSUE TITLE
Resizing the inspector doesn't look good

### ISSUE THREAD

**Issue by char0xff** [godotengine/godot#22054] opened 2018-09-13 22:12 UTC
**Godot version:**
3.0 and master

**Issue description:**
Resizing the inspector currently looks unprofessional and wastes space for the input boxes. The proposed behavior (on the right) makes it more comfortable to type strings, useful for controls and exported string variables.

**How to do it in practice:**
There could be a maximum width for the left part, which if really needed could be overridden by means of a movable vertical separator.

**Picture:**
![inspector](https://user-images.githubusercontent.com/10872697/45518420-bfd06480-b7b1-11e8-9209-8e08ee1ec2da.png)

**Comment by akien-mga** [comment] 2018-09-14 07:58
Duplicate of #7133.

**Closed by akien-mga** 2018-09-14 07:58 UTC
Labels: enhancement, topic:editor, usability
