### ISSUE TITLE
Playing animations at 60 fps in editor

### ISSUE THREAD

**Issue by jay3d** [godotengine/godot#12832] opened 2017-11-11 04:29 UTC
Playing animations clips at 60 fps in editor is not as smooth without turning on "Update Always"

**Comment by Zylann** [comment] 2017-11-11 14:31
Related to https://github.com/godotengine/godot/issues/11030

**Comment by Calinou** [comment] 2020-02-27 10:08
Duplicate of #11030.

**Closed by Calinou** 2020-02-27 10:08 UTC
Labels: bug, topic:editor
