### ISSUE TITLE
Weird shadow-like artifacts when MSAA turned on

### ISSUE THREAD

**Issue by komodor1** [godotengine/godot#25619] opened 2019-02-05 00:01 UTC
**Godot version:**
3.0.6

**OS/device including version:**
Linux Mint 19 Cinnamon, kernel 4.15.0-43-generic, Nvidia GeForce 9500GT, Nvidia 940.107 driver

**Issue description:**
When turning on MSAA, wierd shadow like artifacts show up. The problem only happens on MSAA x2, x4, x8. When disabled, or on x16 there's no problem.
MSAA disabled:
![msaa disabled](https://user-images.githubusercontent.com/34841309/52245314-69d79700-28e1-11e9-9acd-f26bb3e50c77.png)
MSAA x4:
![msaax4](https://user-images.githubusercontent.com/34841309/52245315-6c39f100-28e1-11e9-9b46-a48051eec827.png)
MSAA x16:
![msaax16](https://user-images.githubusercontent.com/34841309/52245306-66441000-28e1-11e9-8ddd-d9505648d40c.png)

**Project archive:**
[Godot-Block.tar.gz](https://github.com/godotengine/godot/files/2833812/Godot-Block.tar.gz)

**Comment by Ace-Dragon** [comment] 2019-02-05 14:43
I don't know about Linux, but on Windows it has been many years since Nvidia's last driver release for the GeForce 9xxx series.

Just to note anyway, I also don't know what the policy is by the Godot team regarding unsupported cards.

**Comment by komodor1** [comment] 2019-02-05 20:41
@Ace-Dragon Last linux nvidia driver update was 6th June 2018, so it's "fresh" i can say.

@Calinou I don't think so it's needed, but i'm gonna upload it for couple of minutes.

**Comment by Calinou** [comment] 2019-02-05 21:12
I can reproduce this on https://github.com/godotengine/godot/commit/16d402147b9057c9f7d43ef9b46eb8654e5483cc (OS: Fedora 29, GPU: GeForce GTX 1080 with NVIDIA 410.78).

This is caused by the DirectionalLight's contact shadow and can only be seen with MSAA levels from 2× to 8⋅. As a workaround, you can set its value to 0 to disable it.

**Comment by clayjohn** [comment] 2020-01-10 06:13
Bumping to 4.0, there were lots of issues with contact shadows that appear difficult to fix without moving to Vulkan.

**Comment by Calinou** [comment] 2020-04-27 08:21
I'll close this, as contact shadows are no longer available in the `master` branch (they were replaced by shadow pancaking, which does a similar job better).

**Closed by Calinou** 2020-04-27 08:21 UTC
Labels: bug, confirmed, topic:rendering
