### ISSUE TITLE
Godot 3.2.1 Official - Template Library 'Failes sha256 hash check' on All

### ISSUE THREAD

**Issue by nazgulsenpai** [godotengine/godot#37516] opened 2020-04-02 12:53 UTC
**Godot version:**
3.2.1.stable.official
**OS/device including version:**
Windows 10 64-bit 1909
**Issue description:**
~~The Steam version~~ The Steam and website download version of Godot encounters an sha256 hash check failure on every template downloaded from the Templates tab of the Project Manager window. Deleting the "demos" folder in the installation folder (..../steamapps/common/Godot Engine/demos) or %appdata%/Godot/demos has no effect and the issue persists.
**Steps to reproduce:**
Download Godot Engine ~~from Steam~~ from Steam or from godotengine.org. Attempt to download a Template from the Project Manager.
**Minimal reproduction project:**
![image](https://user-images.githubusercontent.com/31775906/78251433-f0bcdb00-74b6-11ea-9a6c-778b88c3ccba.png)

**Comment by akien-mga** [comment] 2020-04-02 12:58
Duplicate of godotengine/godot-asset-library#207.

**Closed by akien-mga** 2020-04-02 12:58 UTC

**Comment by nazgulsenpai** [comment] 2020-04-02 12:59
I checked when I started the issue :) Will follow the existing, thanks!
