### ISSUE TITLE
List display bug in the "About" menu of the Project Manager

### ISSUE THREAD

**Issue by Logharaa** [godotengine/godot#48179] opened 2021-04-25 11:40 UTC
**Godot version:**
v4.0.dev.custom_build.15a85fe97

**OS/device including version:**
Windows 10, Vulkan API 1.2.162

**Issue description:**
When scrolling through the authors and donors lists (in the "About" menu of the Project Manager), some of the lines sometimes appear on top of the list container, when they should not :

![godot_list_display_bug](https://user-images.githubusercontent.com/38374449/115991981-8435e200-a5cb-11eb-9a96-d6e18b3360c3.gif)

The resolution of my screen is 2560x1440 and Windows display scaling is 125%.

**Steps to reproduce:**
Compile godot on the latest version of master branch, open "About" menu of the Project Manager, scroll through authors and donors lists.

**Comment by pycbouh** [comment] 2021-04-25 11:44
I think there is some general issue with `ScrollContainer` and occlusion of controls in 4.0, as I’ve had the same problem in another part of the editor UI when working on a PR.

**Comment by Calinou** [comment] 2021-04-25 13:52
Duplicate of https://github.com/godotengine/godot/issues/36164.

**Closed by Calinou** 2021-04-25 13:52 UTC
Labels: bug, confirmed, topic:editor, topic:gui
