### ISSUE TITLE
Inheritance tree on auto-generated documents break under certain conditions

### ISSUE THREAD

**Issue by ydipeepo** [godotengine/godot#66407] opened 2022-09-25 16:08 UTC
### Godot version

v4.0.beta1.official [20d667284]

### System information

It's not system specific error.

### Issue description

Inheritance relationship is not reflected in the document if the types that have inheritance relationship across .gd files refer to each other.

##### `Derived` class (in Derived.gd) inherits from `Base` class (in Base.gd), and Base.gd contains reference to a Derived class:
![attachment_01](https://user-images.githubusercontent.com/79189798/192152789-db3faa49-fc6f-4612-bf87-fa294fbbcdeb.png)
![attachment_02](https://user-images.githubusercontent.com/79189798/192152793-094c5a57-bb38-40e3-bb16-9f7f215a298c.png)

### Steps to reproduce

1. Create two GDScript files.
2. Create a place where types in an inheritance relationship cross-reference each other like below:

##### Base.gd
```GDScript
class_name Base

func this_func_makes_cyclic_type_reference() -> Derived:
	return null
```

##### Derived.gd
```GDScript
class_name Derived extends Base
```

**Comment by bitbrain** [comment] 2022-09-26 13:59
This one might be resolved with https://github.com/godotengine/godot/pull/65752 as it comes with a lot of fixes to the way inheritance works.

**Comment by adamscott** [comment] 2022-10-02 07:49
No, #65752 does not fix this issue unfortunately.

**Comment by YuriSizov** [comment] 2023-06-22 11:56
This is still reproduceable. May be something that we can address with @AThousandShips and the improvements to the index for the class documentation. Or perhaps something for @anvilfolk to look into on the GDScript side of things 🙃

**Comment by AThousandShips** [comment] 2023-06-22 18:01
Will be taking a new look at my documentation improvements once 4.1 is released!

**Comment by AThousandShips** [comment] 2023-07-13 14:42
Seems to be more on the GDScript side, as it affects how the inherits variable is assigned when the classes are broken or cyclic

**Comment by anvilfolk** [comment] 2023-07-13 16:11
Is the documentation builder able to realize when a type/class hasn't been fully analyzed?

My first thought is that GDScript already supports cyclic references in quite a few places, so maybe instead of deferring things, it might make the most sense to either extract docgen out of `GDScript::reload()` and allow the editor to allow on-demand compilation/docgen'ing of dependencies!

In fact, I think my PR already added a little bit of on-demand generation, that might be able to be reused!

**Comment by dalexeev** [comment] 2024-07-24 21:14
Can't reproduce in 4.3 rc 1, looks like this was fixed at some point:

![](https://github.com/user-attachments/assets/708a0af7-ac46-44aa-a17a-13e7ccbbb101)
![](https://github.com/user-attachments/assets/a4ddf514-21f1-49d0-b62c-c24389d5d24f)

See also #72406 / #86577, after restarting the editor, some documentation may not be available until you re-save the script, this is another bug.

Note that this type of class relationship is generally considered bad style. The base class should not know the implementation details of specific descendant classes, and ideally not even know about their existence.

**Closed by dalexeev** 2024-07-24 21:14 UTC
Labels: bug, topic:gdscript, topic:editor
