### ISSUE TITLE
[4.0a1] Not receiving InputEventMouseMotion in autoload [Linux, XFCE]

### ISSUE THREAD

**Issue by Jimmio92** [godotengine/godot#57294] opened 2022-01-27 03:01 UTC
### Godot version

4.0.alpha1

### System information

Fedora Linux 35 XFCE; Vulkan 1.2.189 AMD RADV POLARIS10 (PowerColor Radeon RX590) X11

### Issue description

I am not receiving mouse motion events so I am unable to setup my first person player scene. I do receive other input events just fine (including InputEventMouseButton), but not mouse motion.

### Steps to reproduce

```gdscript
func _input(ev):
    print(ev)
    if ev is InputEventMouseMotion:
        print("I never happen :(")
```
fails to print InputEventMouseMotion ever.

I have tried getting this data in both an autoloaded script and on a script attached to a RigidDynamicsBody3D in my scene. I have tried explicitly enabling input processing for the script(s). I have tried disabling input buffering. I have tried capturing the mouse. There doesn't seem to be any other settings that would affect this.

**Comment by akien-mga** [comment] 2022-01-27 09:13
I can't reproduce the issue with the given steps in 4.0 alpha 1 on Mageia Linux (KDE/X11).

Could you provide a minimal reproduction project?

**Comment by Jimmio92** [comment] 2022-01-27 18:13
I did a build from master branch and the problem is still there. Engine only takes 3 minutes to build on my rig but three hours figuring out why scons wouldn't work.... but I digress..

I guess this is XFCE specific? I don't see how it could be... it's all coming from X11.

Thanks for figuring it works after the window moves @mieldepoche . Moving the window in code doesn't workaround the problem. Additionally, DisplayServer.window_get_position() is way off and/or treats each monitor separately even though Linux treats the entire desktop as one area.

**Comment by aembur** [comment] 2022-01-28 22:53
I can reproduce this in EndeavourOS XFCE. Additionally, printing `get_global_mouse_position()` every frame shows that it's stuck at `(-256, -162)`. Manually moving the window or switching focus does make it function properly, but as @Jimmio92 mentioned, moving the window in code doesn't workaround the issue.

**Comment by Sauermann** [comment] 2022-01-30 16:42
Looks like a duplicate of #53894.

**Closed** 2022-01-30 18:26 UTC
Labels: bug, platform:linuxbsd, confirmed, topic:input

**Comment by SpyrexDE** [comment] 2022-09-18 17:04
I have this exact issue with v4.0.alpha16.official [86dd3f312] **on Windows 10**

**Comment by mieldepoche** [comment] 2022-09-18 19:20
@SpyrexDE what about 4.0 beta 1? I just tested and the problem does not occur on my end anymore (linux with xfce).
