### ISSUE TITLE
Script window closes the help window

### ISSUE THREAD

**Issue by DimaKiva** [godotengine/godot#7396] opened 2016-12-30 22:51 UTC
**Operating system or device - Godot version:**
Godot 2.1.1 - Ubuntu 16.04

**Steps to reproduce:**
1. If a scroll appears in the Script window
2. At this time, click Help Topics
3. Help window will appear outside the script

**Link to minimal example project** (optional but very welcome):
![2016-12-31 05-39-42](https://cloud.githubusercontent.com/assets/11325733/21573916/64878688-cf25-11e6-9f7d-32738bf68057.png)

**Comment by Zylann** [comment] 2016-12-31 01:58
Duplicate of https://github.com/godotengine/godot/issues/7333, https://github.com/godotengine/godot/issues/7187, https://github.com/godotengine/godot/issues/7156, https://github.com/godotengine/godot/issues/7140 and https://github.com/godotengine/godot/issues/6769

**Comment by bojidar-bg** [comment] 2016-12-31 09:26
Duplicate indeed....

**Closed** 2016-12-31 09:26 UTC
