### ISSUE TITLE
Can't set values of Construct nodes in VS

### ISSUE THREAD

**Issue by ghost** [godotengine/godot#6311] opened 2016-08-28 14:50 UTC
Latest master branch commit (6c67437), build on Linux.

Can't set values on all of the recently added Construct nodes, pressing enter key after typing a value does nothing:

![recorded](https://cloud.githubusercontent.com/assets/1072168/18034518/cfba96f6-6d47-11e6-9f58-27b10c86bac6.gif)

**Comment by procedural** [comment] 2016-08-28 15:03
I see "Change Input Value" logged on pressing enter key in the output window, but the value doesn't change on the graph and if I run the application it crashes with these errors: 
![image](https://cloud.githubusercontent.com/assets/1072168/18034591/9bdd0f38-6d49-11e6-9dae-1b7eaf8c7546.png)

**Comment by procedural** [comment] 2016-08-28 15:27
Current workaround: connect a constant to all the ports, even to ones with default values: 
![image](https://cloud.githubusercontent.com/assets/1072168/18034720/fbe46220-6d4c-11e6-981b-025e22ec0261.png)

**Comment by procedural** [comment] 2016-08-31 12:01
Commit 0281718: the bug still present

**Comment by procedural** [comment] 2016-09-08 01:04
Commit 462c171: the first issue is solved, you can set values now, but if you won't for a default constructor, the debugger will still return an error until you set coordinates in vector 3 constructor, for example, to 0 manually

**Comment by Calinou** [comment] 2018-04-11 16:42
First of all thank you for your report and sorry for the delay.

We released Godot 3.0 in January 2018 after 18 months of work, fixing many old issues either directly, or by obsoleting/replacing the features they were referring to.

We still have hundreds of issues whose relevance/reproducibility needs to be checked against the [current stable version](https://godotengine.org/download), and that's where you can help us.
**Could you check if the issue that you described initially is still relevant/reproducible in Godot 3.0 or any newer version, and comment about it here?**

For bug reports, please also make sure that the issue contains detailed steps to reproduce the bug and, if possible, a zipped project that can be used to reproduce it right away. This greatly speeds up debugging and bugfixing tasks for our contributors.

Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

Thanks in advance.

*Note: This message is being copy-pasted to many "stale" issues (90+ days without activity). It might happen that it is not meaningful for this specific issue or appears oblivious of the issue's context, if so please comment to notify the Bugsquad about it.*

**Comment by Chaosus** [comment] 2018-09-18 10:35
It still exist in 3.1 in their Construct nodes..

**Comment by fire** [comment] 2018-10-11 21:50
Is fixed by #22944

**Comment by fire** [comment] 2018-10-11 21:55
Duplicate of #21840. Closing this one because it's older.

**Closed by fire** 2018-10-11 21:55 UTC
Labels: bug, topic:visualscript
