### ISSUE TITLE
text editor - autocompleting method inside another method removes one of the parentheses

### ISSUE THREAD

**Issue by nathanfranke** [godotengine/godot#60744] opened 2022-05-04 04:22 UTC
### Godot version

1b2992799b324479b3fba9e05ae6226a46cb4143
Not reproducible on 3.4.4

### System information

Arch on 5.15.37-1-lts

### Issue description

![issue reproduction gif](https://user-images.githubusercontent.com/14253836/166622576-9d6e0d63-9dcb-4b3b-8429-9a74b89a3997.gif)

```diff
- print(Vector2.from_angle()
+ print(Vector2.from_angle())
```

### Steps to reproduce

1) Type something like `print(Vector2.from` and let it autocomplete.

**Comment by veryprofessionaldodo** [comment] 2022-05-13 14:08
Interesting. I'm going to look into this now, see if I can discover the root cause

**Comment by veryprofessionaldodo** [comment] 2022-05-13 17:44
Fixed on my end. Checking to see if there aren't any regressions or unwanted behaviour, and if everything's okay I'll create a PR.

**Comment by Frostings** [comment] 2022-10-06 19:17
autocomplete removes the entire right side of the current line, not just one parenthesis, but only when you press tab to do it (on 4.0.beta2)

**Closed** 2022-12-19 15:29 UTC
Labels: bug, topic:editor, confirmed, topic:gui
