### ISSUE TITLE
GPUParticles2D incorrect particle position when `locol_coords` disabled

### ISSUE THREAD

**Issue by h0lley** [godotengine/godot#58724] opened 2022-03-04 00:16 UTC
### Godot version

4.0.alpha3

### System information

Ubuntu, Nvidia

### Issue description

https://user-images.githubusercontent.com/23386940/156674293-ad56f7dc-90f6-4290-8a57-c7ff3071ba71.mp4

### Steps to reproduce

1. Create a blank project
2. Create Node2D scene
3. Add a GPUParticles2D and add a ParticlesMaterial, perhaps crank its scale_min up for better visibility
4. Disable `local_coords`
5. Move the GPUParticles2D node away from 0, 0 and observe erroneous offset appearing between the node position and the particles

**Comment by KoBeWi** [comment] 2022-03-04 00:23
Duplicate of #56892

**Closed by KoBeWi** 2022-03-04 00:23 UTC
