### ISSUE TITLE
PoolVector3Array's append and push_back doesnt work

### ISSUE THREAD

**Issue by nonunknown** [godotengine/godot#35271] opened 2020-01-18 11:37 UTC
**Godot version:**
3.2 beta 5
**OS/device including version:**
ubuntu 18.04
**Issue description:** / **Steps to reproduce:** / **Minimal reproduction project:**

When working with poolvector3array the methods  append and push_back doesnt work (didnt tested other ones)   if its called from another script than its origin:

Project.gd
```
extends Node
class_name Project

var desired_pos:PoolVector3Array = []
```

Example.gd
```
onready var project:Project = Project.new()

func _ready():
   project.desired_pos.append(Vector3.UP) #doesnt work
   print(project.desired_pos) #outputs [] expected [(0,1,0)]
```

There is a workaround? yes there is

Project.gd
```
extends Node
class_name Project

var desired_pos:PoolVector3Array = []

func append_desired_pos(pos):
   desired_pos.append(pos)
```

Example.gd
```
onready var project:Project = Project.new()

func _ready():
   project.append_desired_pos(Vector3.UP) #works fine
   print(project.desired_pos) #outputs [(0,1,0)] expected [(0,1,0)]
```

maybe this same problem could involve #35250

**Comment by qarmin** [comment] 2020-01-18 12:56
Look at https://github.com/godotengine/godot/issues/29047

**Comment by akien-mga** [comment] 2020-01-18 14:21
Duplicate of #15265.

**Closed by akien-mga** 2020-01-18 14:21 UTC
