### ISSUE TITLE
Editor does not always emit `NOTIFICATION_WM_FOCUS_IN` when refocusing the editor window (Save On Focus Loss + DisplayServer regression)

### ISSUE THREAD

**Issue by Scarm2** [godotengine/godot#53256] opened 2021-09-30 14:16 UTC
### Godot version

v4.0.dev.custom_build.2fc31fdfc

### System information

Windows 10 Pro Build 19042, NVIDIA GeForce RTX 2060 SUPER, Vulkan API 1.2.170

### Issue description

If Save on Focus Loss is enabled in Editor Settings, once the user Alt-Tabs out of the window or clicks on something outside the window, Godot's taskbar icon shows the Orange warning animation, and if going back to Godot, the editor heavily lags until manually saving with Ctrl+S or clicking on one of the dropdown menus in the editor.

Setting enabled to cause this issue:
![image](https://user-images.githubusercontent.com/82760388/135470374-ce7cc97f-c04e-43aa-99db-cb65637c6ebe.png)

Issue in action:
![editor died](https://user-images.githubusercontent.com/82760388/135471319-d41bcd48-81b0-4ec6-8f7e-e0834db723bb.gif)

This issue can be avoided by not enabling the option. I just thought it'd be nice to report it in case it goes unnoticed.
Searched for duplicates, nobody reported this issue.

### Steps to reproduce

1. Open Godot 4.0 and open the Editor Settings.
2. Enable Save on Focus Loss.
3. Test if the Editor FPS is normal.
4. Alt+Tab out/Go to a different window.
5. Go back to Godot and check the FPS. If it's very choppy then the reproduction is successful.

### Minimal reproduction project

The issue is Project-Independent. This means it can be done in any project.

**Comment by Calinou** [comment] 2021-09-30 14:17
Can you reproduce this in 3.3.3? Also, can you reproduce this in `master` if single-window mode is enabled in the Editor Settings?

**Comment by Scarm2** [comment] 2021-09-30 14:25
It doesn't happen anymore but if you minimze Godot the editor and reopen it hangs then crashes. This doesn't happen if Save on Focus Loss is disabled.

Also the issue is not present on Godot 3.x

**Comment by KoBeWi** [comment] 2022-06-04 16:28
@Scarm2 Can you still reproduce this in the newest alpha?

**Comment by coppolaemilio** [comment] 2023-01-25 13:14
I can't reproduce 🤔 It's been a long time since the report and @Scarm2 didn't say anything else. Maybe we should close it?

**Closed** 2023-01-25 13:25 UTC
Labels: bug, platform:windows, topic:editor, regression
