### ISSUE TITLE
Embedded tool script vanishing at the scene opening in the editor if it contains an init method awaiting arguments

### ISSUE THREAD

**Issue by TheMoye** [godotengine/godot#40817] opened 2020-07-29 07:20 UTC
**Godot version:**

V3.2.2.stable.official

**OS/device including version:**

Debian 10 Buster Cinnamon

**Issue description:**

When I open a scene in the editor to which the following (minimal) embedded script is attached, it disappears : 

```
tool
extends Control

func _init(value : int) -> void:
	pass
```

The following error appears in the output : 

`modules/gdscript/gdscript.cpp:127 - Condition "r_error.error != Variant::CallError::CALL_OK" is true. Returned: __null`

**Steps to reproduce:**

Simply add the content given above to an embedded script and open it in the editor.

**Minimal reproduction project:**

**Comment by KoBeWi** [comment] 2022-11-25 16:34
Duplicate of #28986

**Closed by KoBeWi** 2022-11-25 16:34 UTC
Labels: bug, topic:gdscript, topic:editor
