### ISSUE TITLE
Many Control Buttons with custom styles (StyleBoxFlat) slowing Android exports. (Less than 15fps).

### ISSUE THREAD

**Issue by TIBI4** [godotengine/godot#40189] opened 2020-07-07 20:14 UTC
**Godot version (tested in both):**
- Godot_v3.2.2 stable win64.
- Godot v3.2 beta2 official win64.

**OS/device including version:**
- Tested on Xiaomi Mi A1 and Xiaomi Redmi 4A.
- GLES2. (GLES3 tested too).

**Issue description:**
- Huge perfomance issues when using StyleBoxFlat.
- (Debugging trough USB).

**Image 1:**
Those steps are from creating a new row (on Android).
![image](https://user-images.githubusercontent.com/25259582/86833842-146c6000-c068-11ea-974d-58a0fb4ae612.png)
![hkvSlLursW](https://user-images.githubusercontent.com/25259582/86836103-053ae180-c06b-11ea-94b3-555d65b6479e.gif)

**Image 2:**
Those hidden nodes are replicated in the Android phone.
![t05AkDBKsV](https://user-images.githubusercontent.com/25259582/86835366-f99aeb00-c069-11ea-9a69-5301c812a774.gif)
![iM9MsshrQj](https://user-images.githubusercontent.com/25259582/86835585-54ccdd80-c06a-11ea-89a9-3ed98cae4284.gif)

**Steps to reproduce:**
- Add many node buttons with custom StyleBoxFlat.

**Minimal reproduction project:**
[Test.zip](https://github.com/godotengine/godot/files/4886942/Test.zip)

**Comment by Calinou** [comment] 2020-07-07 20:30
Duplicate of https://github.com/godotengine/godot/issues/19943 (the underlying cause is the same). As a workaround, decrease the corner detail of StyleBoxFlat or avoid using rounded corners altogether. (You could use StyleBoxTexture with pre-made nine-patch textures instead.)

**Closed by Calinou** 2020-07-07 20:30 UTC

**Comment by TIBI4** [comment] 2020-07-07 21:21
@Calinou
> As a workaround, decrease the corner detail of StyleBoxFlat or avoid using rounded corners altogether. (You could use StyleBoxTexture with pre-made nine-patch textures instead.)

Making pre-made textures worked for me earlier. But I wanted to use what Godot provided to me.

Anyways. I share this, as decreasing corner details, avoiding using rounded corners, or both at the same time didn't help.

**_Minimal corner detail._**
![RFDuAjEkkH](https://user-images.githubusercontent.com/25259582/86844128-94e58d80-c075-11ea-9325-902dc5c3c658.gif)

**_Border radius = 0._**
![w2mVRw8tIh](https://user-images.githubusercontent.com/25259582/86844135-98791480-c075-11ea-9803-888d1b6e499d.gif)

_**Both at the same time.**_
![Godot_v3 2-beta2_win64_rioZW4AtwK](https://user-images.githubusercontent.com/25259582/86844139-9a42d800-c075-11ea-90bc-33c130e9af1f.png)
