### ISSUE TITLE
CSG Hole

### ISSUE THREAD

**Issue by ardune** [godotengine/godot#75862] opened 2023-04-09 18:13 UTC
### Godot version

v4.0.1.stable.mono.official [cacf49999]

### System information

Windows, Vulkan

### Issue description

Adding (or subtraction) two meshes with CSG seems to erase verts from the mesh incorrectly

![image](https://user-images.githubusercontent.com/403261/230789335-686aeee9-e7d5-4c87-8bde-2d4d5f6c60ec.png)

### Steps to reproduce

Create some mesh and use CSG to add/subtract - if you align a vertex _just_ right it seems to cause this issue.
I can "avoid" it by bumping the location by a fraction but I'm really trying to have a perfect alignment of element for the game I'm working on.

It seems like it happens more easily if your vertex coords are integers 

### Minimal reproduction project

[HoleMissing.zip](https://github.com/godotengine/godot/files/11186053/HoleMissing.zip)

**Comment by Calinou** [comment] 2023-04-10 18:33
Duplicate of https://github.com/godotengine/godot/issues/58637.

**Closed by Calinou** 2023-04-10 18:33 UTC

**Comment by akien-mga** [comment] 2023-04-27 15:07
> Duplicate of #58637.

Actually consolidating this in #43755 now, since #58637 was fixed but that didn't solve the MRPs in these two issues.
