### ISSUE TITLE
SpriteFrames that appear in both 2D and 3D have a blown out saturation in 2D

### ISSUE THREAD

**Issue by ztc0611** [godotengine/godot#64697] opened 2022-08-21 16:52 UTC
### Godot version

3.3.stable, 3.4.stable, 3.5.stable

### System information

macOS Monterey 12.5.1, GLES3, Apple M1

### Issue description

If the same set of sprite frames is used on both an AnimatedSprite3D and an AnimatedSprite, the AnimatedSprite has blown out colors for any frame that appears in 3D. This continues to persist if you show different frames and animations in 3D while the project is running, and then switch to 2D. Any frames that have been displayed in 3D in the editor or runtime have this blown out saturation. If you never open/view a 3D scene, this color issue never occurs on the 2D sprite.

<img width="1610" alt="image" src="https://user-images.githubusercontent.com/28269330/185802110-d299ec0c-baa9-4407-8625-e598fc398a51.png">
<img width="1610" alt="image" src="https://user-images.githubusercontent.com/28269330/185802116-127f24f8-f738-4987-9c8a-f01afc1923e4.png">

### Steps to reproduce

Create Project. Create a Node2D and a Spatial Scene. Put an AnimatedSprite in one, and an AnimatedSprite3D in the other. Then assign a SpriteFrames in one, save it as a resource, and load that into the other. Now switch between the two scenes, the 2D one will have blown out saturation. This will appear both in the editor and when running the project.

### Minimal reproduction project

[3DColorGlitch.zip](https://github.com/godotengine/godot/files/9389600/3DColorGlitch.zip)

**Comment by Calinou** [comment] 2022-08-21 19:59
Duplicate of https://github.com/godotengine/godot/issues/18941. This can't be fixed in 3.x, but you can make two copies of the texture on the filesystem (so that one can be imported with sRGB, and one without).

**Closed by Calinou** 2022-08-21 19:59 UTC

**Comment by ztc0611** [comment] 2022-08-21 22:08
The duplicating texture problem would be a massive headache because as of now 64 sprites in my game are affected, and it likely will balloon to nearly 500 by the time it's all over. I'm staring down the barrel of either making a shell script to duplicate them all into folders every time I modify them and bake those into .tres SpriteFrame files, or updating to the 4.0 alphas (which, of course, is not recommended). I'd have to spend a bunch of time on this workaround linking system, just to pull it back apart when 4.0 becomes stable enough to swap to.

How would I go about doing the shader thing? That seems like it could be the least busted temporary fix, but I'm basically clueless about shaders.

**Comment by Calinou** [comment] 2022-08-22 00:09
Unfortunately, the SpatialMaterial flag can't be used as 2D rendering can't be resolved without a custom shader: https://github.com/godotengine/godot/issues/31759

Here's a project using a custom shader for 2D rendering, and SpatialMaterial for 3D: [custom_shader_2d_3d_srgb.zip](https://github.com/godotengine/godot/files/9390256/custom_shader_2d_3d_srgb.zip)

Remember to assign the sprite texture to both the Sprite node's `texture` property and the `sprite` shader parameter.
