### ISSUE TITLE
PoolByteArray returning 0 from InputEventKey

### ISSUE THREAD

**Issue by schneediener** [godotengine/godot#59033] opened 2022-03-11 15:09 UTC
### Godot version

3.5.beta1.official

### System information

Windows 10 64-bit

### Issue description

When I hit a key on my keyboard (such as the letter B) I am expecting a printed result in my Output showing what Key I have pressed (so in this example, "B") by using get_string_from_utf8() on the PoolByteArray results of the InputEventKey

But instead, I am getting a blank/null result. If I remove .get_String_from_utf8() and just look at the result of the PoolByteArray, it is 0, regardless of which key I press:
<img width="395" alt="image" src="https://user-images.githubusercontent.com/100398434/157891428-f5dec682-5186-495b-ab4f-6847fef4c4d2.png">

I am not an experienced developer and so am open to my having made a mistake, but after quite a lot of research, I've found that most people running the same code do get a key returned. But I have found another example of a user in a Discord server who has been getting the same problem, and the developer assisting them said to raise it on Github as an issue. I cannot find that they've done that, so I am doing it now.

I feel this might be related to keyboard or keyboard settings, but I have tried OS.set_ime_active(true) in case IME was the issue and it still doesn't work. OS.get_scancode_string(typed_event.scancode) does work as a workaround.

### Steps to reproduce

```func _unhandled_input(event: InputEvent) -> void:

	if event is InputEventKey and not event.is_pressed():
		
		var typed_event = event as InputEventKey 
		var key_typed = PoolByteArray([typed_event]).get_string_from_utf8()
		var pool_array = PoolByteArray([typed_event])
		var scancode = OS.get_scancode_string(typed_event.scancode)
		print (key_typed)
		print (typed_event)
		print (scancode)
		print (pool_array)```

returns when D and F keys pressed:
<img width="129" alt="image" src="https://user-images.githubusercontent.com/100398434/157893532-cb7790c2-ff81-4744-814f-12ccbd80df83.png">


Scancode works, but I don't seem to be sending an InputEventKey that can be processed beyond 0/null by PoolByteArray

### Minimal reproduction project

[PoolByteArray_troubleshooting.zip](https://github.com/godotengine/godot/files/8233070/PoolByteArray_troubleshooting.zip)

**Comment by akien-mga** [comment] 2022-03-11 15:19
Sounds like a duplicate of #56544?

**Comment by schneediener** [comment] 2022-03-11 15:42
Yes! I'm glad to see a much more succinct description of the problem. I was searching for the issue based on poolbytearray but this seems like the problem exactly. I'm away from my machine but I'd be happy to see it closed.

I will send this issue you've given me to the other fellow too. Thank you

Regards,
Sean
________________________________

**Closed** 2022-03-11 15:46 UTC

**Comment by josephmbustamante** [comment] 2022-03-11 16:16
> You even have nearly the same code, is that from a tutorial?

@akien-mga This is from my [typing game tutorial](https://youtu.be/qRPI_c9qI1o). I've had a lot of users with similar issues recently on Windows that I haven't been able to debug/help them with (I have a Mac), so I'm glad to see that changing the code to just be on key down should help. I'll update the video and hopefully prevent similar issues from popping up. Thanks!
