### ISSUE TITLE
Line edit cursor is not visible in popup windows 

### ISSUE THREAD

**Issue by ThakeeNathees** [godotengine/godot#39756] opened 2020-06-22 14:03 UTC
**Godot version:** 2753f0ae8

**OS/device including version:** Windows10

**Issue description:**
Line edit cursor is not visible in popup windows (search help, create new script window, ...) but it'll only drawn only it regain focus (right click to open context menu and click on the line edit again)
![line-edit-cursor](https://user-images.githubusercontent.com/41085900/85296309-d0e9f180-b4be-11ea-83b6-a5c1193a8482.gif)

**Steps to reproduce:**
type something in the line edit of the search help or new script creation window

**Minimal reproduction project:** N/A

**Comment by KoBeWi** [comment] 2020-07-06 09:28
Duplicate of #37748

**Closed by KoBeWi** 2020-07-06 09:28 UTC
