### ISSUE TITLE
 Another resource is loaded from path xxx (possible cyclic resource inclusion).

### ISSUE THREAD

**Issue by L2750558108** [godotengine/godot#70577] opened 2022-12-26 05:07 UTC
### Godot version

3.5.1mono

### System information

windows10

### Issue description

Reloading the script after the external editor changes the script,and get an error message like
Another resource is loaded from path 'script path' (possible cyclic resource inclusion).

### Steps to reproduce

Create a C# script
Open it with the Built-in text editor
Use VSCode to change it
Back to Godot and click "Reload"
![image](https://user-images.githubusercontent.com/119792950/209503243-cbadcc68-3034-487b-a19d-c607199fb63d.png)
And get error message " Another resource is loaded from path 'xxx' (possible cyclic resource inclusion)."

### Minimal reproduction project

An empty project

**Comment by lesleyrs** [comment] 2022-12-26 07:35
I get this error with gdscript Godot 4 beta 10 when running html debug while having a sub resource that I didn't save as a tres. In my case it was a style box.

**Comment by L2750558108** [comment] 2022-12-31 12:58
So will anyone come to slove this problem?

**Comment by L2750558108** [comment] 2022-12-31 12:58
So will anyone come to slove this problem?

**Comment by raulsntos** [comment] 2023-01-01 18:17
Duplicate of https://github.com/godotengine/godot/issues/57211

**Closed by raulsntos** 2023-01-01 18:17 UTC
