### ISSUE TITLE
The method add_stylebox_override of Control calls NOTIFICATION_THEME_CHANGED to itself, resulting in an infinite loop and a StackOverflow when the method is called in _notification

### ISSUE THREAD

**Issue by ClemensOlivae** [godotengine/godot#42802] opened 2020-10-14 18:43 UTC
**Godot version:**
3.2.3, mono + standard

**OS/device including version:**
Windows, but probably not OS-specific

**Issue description:**
It is often useful to react to a theme change by overriding a Control's stylebox using _add_stylebox_override_.
Doing so cleanly (I think?) would be by using the _notification method, and react to a NOTIFICATION_THEME_CHANGED notification.
However, the  _add_stylebox_override_ method calls NOTIFICATION_THEME_CHANGED to itself : this leads to an infinite loop and a StackOverflow exception.
I didn't test it but this is also probably an issue for the shader/font/color overrides.

The issue is located line 1764 in control.cpp :
```
void Control::add_theme_style_override(const StringName &p_name, const Ref<StyleBox> &p_style) {
	if (data.style_override.has(p_name)) {
		data.style_override[p_name]->disconnect("changed", callable_mp(this, &Control::_override_changed));
	}

	// clear if "null" is passed instead of a style
	if (p_style.is_null()) {
		data.style_override.erase(p_name);
	} else {
		data.style_override[p_name] = p_style;
		if (data.style_override[p_name].is_valid()) {
			data.style_override[p_name]->connect("changed", callable_mp(this, &Control::_override_changed), Vector<Variant>(), CONNECT_REFERENCE_COUNTED);
		}
	}
	notification(NOTIFICATION_THEME_CHANGED);
```

Maybe NOTIFICATION_THEME_CHANGED could be notified to the Control's children instead of the control itself?

**Steps to reproduce:**
![NotificationStackOverflow](https://user-images.githubusercontent.com/64355481/96030455-4efe4980-0e5c-11eb-8933-e3333424fb56.jpg)
Control notifies Panel.
Panel overrides its stylebox when notified.
By overriding its stylebox Panel call the notification.
Panel overrides its stylebox when notified.
Etc...

**Minimal reproduction project:**

[NotificationStackOverflow.zip](https://github.com/godotengine/godot/files/5380202/NotificationStackOverflow.zip)

**Comment by pycbouh** [comment] 2021-06-20 01:02
Well, for that control theme did indeed change, as the subsequent call for `get_theme_stylebox("panel")` here will now return the override value. So this is by design, and not a bug. The control needs to react on the new stylebox value and do whatever it does with it (update local theme cache, render, etc). To avoid infinite loops you would need to connect to the notification in the parent node and add overrides to the child from there.

I'm going to close this as this is not a bug, but I can see that this can be a problem. If there are ideas on how to address this better and improve our implementation, feel free to open a [proposal](https://github.com/godotengine/godot-proposals/issues).

**Closed by pycbouh** 2021-06-20 01:02 UTC
Labels: bug, topic:gui
