### ISSUE TITLE
Incorrect positioning of axes and standard grid lines in 3D scenes

### ISSUE THREAD

**Issue by 648trindade** [godotengine/godot#10214] opened 2017-08-10 05:12 UTC
**Operating system or device - Godot version:**
Debian Buster/Testing 64 bits up-to-date
Godot versions < 3 (not present on v3 alpha)
CPU: Intel i5 4210u
GPU: Intel HD 4400 (Haswell) (i915 kernel driver)

Present in both the official release and the compiled version of branch 2.1

Compiled with `scons platform=x11 builtin_openssl=yes`

**Issue description:**
When an empty 3D scene is created, some lines in the grid of the XZ plane are positioned incorrectly, as are the lines representing the axes. The following pictures speak for themselves:

![captura de tela de 2017-08-10 01-46-58](https://user-images.githubusercontent.com/4951094/29155066-b1d913fe-7d6f-11e7-80cd-7f4856da4d81.png)
![captura de tela de 2017-08-10 01-46-46](https://user-images.githubusercontent.com/4951094/29155067-b1da4a9e-7d6f-11e7-9117-970a059a5514.png)

The bug may have been due to some update of the video module, because a few months ago it did not happen. However, I believe it is important because in v3 alpha it is not present.

**Steps to reproduce:**
* Open an 3D view on an empty scene (actually I haven't tested with non-empty 3D scenes because I usually do not make 3D projects)

**Comment by ZX-WT** [comment] 2017-08-10 06:39
probably related to #6003

**Comment by bojidar-bg** [comment] 2017-08-10 07:09
Not just related, but an exact duplicate of #6003.

**Closed by bojidar-bg** 2017-08-10 07:09 UTC
