### ISSUE TITLE
AnimatedSprite distort pixels

### ISSUE THREAD

**Issue by Phenomen** [godotengine/godot#11688] opened 2017-09-29 11:50 UTC
![2017-09-29_15-48-22](https://user-images.githubusercontent.com/138311/31014779-d385f810-a52d-11e7-892c-64c9f847b72a.png)

Left is Sprite and right is AnimatedSprite. Both use same source file and 1,1 scale.

**Comment by Zylann** [comment] 2017-09-29 12:28
Are they exactly placed at integer positions?

**Comment by groud** [comment] 2017-09-29 14:47
I think this is a duplicate but I can't find the previous issue.

**Comment by Turbito** [comment] 2017-10-03 14:34
Similar happens for me in https://github.com/godotengine/godot/issues/11417

**Comment by groud** [comment] 2017-10-03 14:36
> Similar happens for me in #11417

That's the one I was looking for ^^

**Comment by akien-mga** [comment] 2017-10-12 15:03
Closing as duplicate of #11417 then.

**Closed by akien-mga** 2017-10-12 15:03 UTC
Labels: bug, topic:rendering
