### ISSUE TITLE
Editor crash when importing TPS Demo

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#31887] opened 2019-09-02 07:30 UTC
**Godot version:**
3.2.alpha.custom_build. aa06f515e

**OS/device including version:**
Ubuntu 19.04

**Issue description:**
Backtrace
```
X Error of failed request:  BadWindow (invalid Window parameter)
  Major opcode of failed request:  25 (X_SendEvent)
  Resource id in failed request:  0x3400115
  Serial number of failed request:  368
  Current serial number in output stream:  368
core/io/resource_importer.cpp:414:39: runtime error: member access within null pointer of type 'const struct ResourceImporter'
handle_crash: Program crashed with signal 11
Dumping the backtrace. Please include this when reporting the bug on https://github.com/godotengine/godot/issues
[1] godots() [0x13de2b0] (/home/rafal/Pulpit/godot/platform/x11/crash_handler_x11.cpp:54)
[2] /lib/x86_64-linux-gnu/libc.so.6(+0x43f60) [0x7f3f3ca10f60] (??:0)
platform/android/export/export.cpp:243:53: runtime error: member access within null pointer of type 'struct EditorSettings'
core/object.cpp:483:6: runtime error: member access within null pointer of type 'const struct Object'
handle_crash: Program crashed with signal 11
Dumping the backtrace. Please include this when reporting the bug on https://github.com/godotengine/godot/issues
[3] ResourceFormatImporter::are_import_settings_valid(String const&) const (/home/rafal/Pulpit/godot/core/io/resource_importer.cpp:414 (discriminator 1))
[1] godots() [0x13de2b0] (/home/rafal/Pulpit/godot/platform/x11/crash_handler_x11.cpp:54)
[2] /lib/x86_64-linux-gnu/libc.so.6(+0x43f60) [0x7f3f3ca10f60] (??:0)
[4] EditorFileSystem::_test_for_reimport(String const&, bool) (/home/rafal/Pulpit/godot/editor/editor_file_system.cpp:353)
[5] EditorFileSystem::_scan_fs_changes(EditorFileSystemDirectory*, EditorFileSystem::ScanProgress const&) (/home/rafal/Pulpit/godot/editor/editor_file_system.cpp:986)
[3] Object::get(StringName const&, bool*) const (/home/rafal/Pulpit/godot/core/object.cpp:483)
[6] EditorFileSystem::_scan_fs_changes(EditorFileSystemDirectory*, EditorFileSystem::ScanProgress const&) (/home/rafal/Pulpit/godot/editor/editor_file_system.cpp:1016 (discriminator 3))
[4] EditorExportPlatformAndroid::_device_poll_thread(void*) (/home/rafal/Pulpit/godot/platform/android/export/export.cpp:243 (discriminator 3))
[7] EditorFileSystem::_scan_fs_changes(EditorFileSystemDirectory*, EditorFileSystem::ScanProgress const&) (/home/rafal/Pulpit/godot/editor/editor_file_system.cpp:1016 (discriminator 3))
[5] ThreadPosix::thread_callback(void*) (/home/rafal/Pulpit/godot/drivers/unix/thread_posix.cpp:76)
[6] /lib/x86_64-linux-gnu/libpthread.so.0(+0x9182) [0x7f3f3d87b182] (??:0)
[7] /lib/x86_64-linux-gnu/libc.so.6(clone+0x3f) [0x7f3f3caeab1f] (??:0)


```
**Minimal reproduction project:**
https://github.com/godotengine/tps-demo

**Comment by KoBeWi** [comment] 2020-09-12 21:34
Can't reproduce in 3.2.3 rc6 on Windows 10
@qarmin Does it still happen to you?

**Comment by fire** [comment] 2020-10-27 03:45
Closing due to lack of update. Please comment if you can still reproduce this issue in the latest stable version of Godot.

**Closed by fire** 2020-10-27 03:45 UTC
Labels: bug, crash, topic:editor, topic:import
