### ISSUE TITLE
Cannot save animation libraries 

### ISSUE THREAD

**Issue by tdaven** [godotengine/godot#62149] opened 2022-06-17 16:12 UTC
### Godot version

4.0.dev (15740c37a3)

### System information

Linux, 64-bit, Fedora 36, AMD RX 590, Vulkan

### Issue description

Trying to save an animation libraries fails, reporting _button_pressed called expected 3 arguments but was called with 4.

### Steps to reproduce

Try to save an animation library by clicking the save button in the the tree column.  The popup that allows you to select the message is never shown and an error is printed out.

**Comment by and-rad** [comment] 2022-06-18 06:04
Duplicate of #61422. There's already a PR, too.

**Closed** 2022-06-18 09:00 UTC
Labels: bug, topic:editor, topic:animation
