### ISSUE TITLE
Can't input the (") key

### ISSUE THREAD

**Issue by seththefirst** [godotengine/godot#4589] opened 2016-05-08 22:53 UTC
**Operating system or device - Godot version:**
OS X El Capitan
Keyboard PRO ( with the numpad ) with config PT-BR
Godot Engine v2.0.2

**Issue description** (what happened, and what was expected):
When coding scripts, when I press the key ( " ), nothing appears in the editor.
Because of that, the only way to "create" strings is copying and paste the symbol (")

**Steps to reproduce:**
Setup the keyboard layout to "Brazilian - PRO"
Open Godot and edit a script.
Try to input the key (")

**Link to minimal example project** (optional but very welcome):

**Comment by akien-mga** [comment] 2016-05-09 13:40
Duplicate of #4403.

**Closed by akien-mga** 2016-05-09 13:40 UTC
Labels: bug, platform:osx, topic:core
