### ISSUE TITLE
Failed to compile for iOS

### ISSUE THREAD

**Issue by lhinuz** [godotengine/godot#27664] opened 2019-04-04 02:08 UTC
**Godot version:**

Godot latest

**OS/device including version:**

osx Mojave 10.14.4/macbookpro

**Issue description:**

Build Godot for iOS failed, the log is:
thirdparty/opus/celt/arm/fixed_armv5e.h:124:20: error: unrecognized instruction mnemonic [12]
       "#MULT16_16\n\t"
                    ^
<inline asm>:2:2: note: instantiated into assembly here
        smulbb x0, x0, x0;
         ^
In file included from thirdparty/opus/opus_decoder.c:41:
In file included from thirdparty/opus/celt/celt.h:41:
In file included from thirdparty/opus/celt/entenc.h:31:
In file included from thirdparty/opus/celt/entcode.h:35:
In file included from thirdparty/opus/celt/ecintrin.h:32:
In file included from thirdparty/opus/celt/arch.h:133:
thirdparty/opus/celt/arm/fixed_armv5e.h:124:20: error: unrecognized instruction mnemonic [12]
       "#MULT16_16\n\t"
                    ^
<inline asm>:2:2: note: instantiated into assembly here
        smulbb x1, x0, x1;
         ^
In file included from thirdparty/opus/opus_decoder.c:41:
In file included from thirdparty/opus/celt/celt.h:41:
In file included from thirdparty/opus/celt/entenc.h:31:
In file included from thirdparty/opus/celt/entcode.h:35:
In file included from thirdparty/opus/celt/ecintrin.h:32:
In file included from thirdparty/opus/celt/arch.h:133:
thirdparty/opus/celt/arm/fixed_armv5e.h:109:19: error: unrecognized instruction mnemonic [12]
       "#MAC16_16\n\t"
                   ^
<inline asm>:2:2: note: instantiated into assembly here
        smlabb x0, x0, x2, x1;
         ^
In file included from thirdparty/opus/opus_decoder.c:41:
In file included from thirdparty/opus/celt/celt.h:41:
In file included from thirdparty/opus/celt/entenc.h:31:
In file included from thirdparty/opus/celt/entcode.h:35:
In file included from thirdparty/opus/celt/ecintrin.h:32:
In file included from thirdparty/opus/celt/arch.h:133:
thirdparty/opus/celt/arm/fixed_armv5e.h:124:20: error: unrecognized instruction mnemonic [12]
       "#MULT16_16\n\t"
                    ^
<inline asm>:2:2: note: instantiated into assembly here
        smulbb x0, x0, x0;
         ^
In file included from thirdparty/opus/opus_decoder.c:41:
In file included from thirdparty/opus/celt/celt.h:41:
In file included from thirdparty/opus/celt/entenc.h:31:
In file included from thirdparty/opus/celt/entcode.h:35:
In file included from thirdparty/opus/celt/ecintrin.h:32:
In file included from thirdparty/opus/celt/arch.h:133:
thirdparty/opus/celt/arm/fixed_armv5e.h:124:20: error: unrecognized instruction mnemonic [12]
       "#MULT16_16\n\t"
                    ^
<inline asm>:2:2: note: instantiated into assembly here
        smulbb x1, x0, x1;
         ^
In file included from thirdparty/opus/opus_decoder.c:41:
In file included from thirdparty/opus/celt/celt.h:41:
In file included from thirdparty/opus/celt/entenc.h:31:
In file included from thirdparty/opus/celt/entcode.h:35:
In file included from thirdparty/opus/celt/ecintrin.h:32:
In file included from thirdparty/opus/celt/arch.h:133:
thirdparty/opus/celt/arm/fixed_armv5e.h:109:19: error: unrecognized instruction mnemonic [12]
       "#MAC16_16\n\t"
                   ^
<inline asm>:2:2: note: instantiated into assembly here
        smlabb x0, x0, x2, x1;
         ^
In file included from thirdparty/opus/opus_decoder.c:41:
In file included from thirdparty/opus/celt/celt.h:41:
In file included from thirdparty/opus/celt/entenc.h:31:
In file included from thirdparty/opus/celt/entcode.h:35:
In file included from thirdparty/opus/celt/ecintrin.h:32:
In file included from thirdparty/opus/celt/arch.h:133:
thirdparty/opus/celt/arm/fixed_armv5e.h:124:20: error: unrecognized instruction mnemonic [12]
       "#MULT16_16\n\t"
                    ^
<inline asm>:2:2: note: instantiated into assembly here
        smulbb x17, x17, x17;
         ^
In file included from thirdparty/opus/opus_decoder.c:41:
In file included from thirdparty/opus/celt/celt.h:41:
In file included from thirdparty/opus/celt/entenc.h:31:
In file included from thirdparty/opus/celt/entcode.h:35:
In file included from thirdparty/opus/celt/ecintrin.h:32:
In file included from thirdparty/opus/celt/arch.h:133:
thirdparty/opus/celt/arm/fixed_armv5e.h:124:20: error: unrecognized instruction mnemonic [12]
       "#MULT16_16\n\t"
                    ^
<inline asm>:2:2: note: instantiated into assembly here
        smulbb x0, x17, x0;
         ^
In file included from thirdparty/opus/opus_decoder.c:41:
In file included from thirdparty/opus/celt/celt.h:41:
In file included from thirdparty/opus/celt/entenc.h:31:
In file included from thirdparty/opus/celt/entcode.h:35:
In file included from thirdparty/opus/celt/ecintrin.h:32:
In file included from thirdparty/opus/celt/arch.h:133:
thirdparty/opus/celt/arm/fixed_armv5e.h:109:19: error: unrecognized instruction mnemonic [12]
       "#MAC16_16\n\t"
                   ^
<inline asm>:2:2: note: instantiated into assembly here
        smlabb x17, x17, x1, x0;
         ^
In file included from thirdparty/opus/opus_decoder.c:41:
In file included from thirdparty/opus/celt/celt.h:41:
In file included from thirdparty/opus/celt/entenc.h:31:
In file included from thirdparty/opus/celt/entcode.h:35:
In file included from thirdparty/opus/celt/ecintrin.h:32:
In file included from thirdparty/opus/celt/arch.h:133:
thirdparty/opus/celt/arm/fixed_armv5e.h:124:20: error: unrecognized instruction mnemonic [12]
       "#MULT16_16\n\t"
                    ^
<inline asm>:2:2: note: instantiated into assembly here
        smulbb x0, x0, x0;
         ^
In file included from thirdparty/opus/opus_decoder.c:41:
In file included from thirdparty/opus/celt/celt.h:41:
In file included from thirdparty/opus/celt/entenc.h:31:
In file included from thirdparty/opus/celt/entcode.h:35:
In file included from thirdparty/opus/celt/ecintrin.h:32:
In file included from thirdparty/opus/celt/arch.h:133:
thirdparty/opus/celt/arm/fixed_armv5e.h:124:20: error: unrecognized instruction mnemonic [12]
       "#MULT16_16\n\t"
                    ^
<inline asm>:2:2: note: instantiated into assembly here
        smulbb x1, x0, x1;
         ^
In file included from thirdparty/opus/opus_decoder.c:41:
In file included from thirdparty/opus/celt/celt.h:41:
In file included from thirdparty/opus/celt/entenc.h:31:
In file included from thirdparty/opus/celt/entcode.h:35:
In file included from thirdparty/opus/celt/ecintrin.h:32:
In file included from thirdparty/opus/celt/arch.h:133:
thirdparty/opus/celt/arm/fixed_armv5e.h:109:19: error: unrecognized instruction mnemonic [12]
       "#MAC16_16\n\t"
                   ^
<inline asm>:2:2: note: instantiated into assembly here
        smlabb x0, x0, x2, x1;
         ^
In file included from thirdparty/opus/opus_decoder.c:41:
In file included from thirdparty/opus/celt/celt.h:41:
In file included from thirdparty/opus/celt/entenc.h:31:
In file included from thirdparty/opus/celt/entcode.h:35:
In file included from thirdparty/opus/celt/ecintrin.h:32:
In file included from thirdparty/opus/celt/arch.h:133:
thirdparty/opus/celt/arm/fixed_armv5e.h:124:20: error: unrecognized instruction mnemonic [12]
       "#MULT16_16\n\t"
                    ^
<inline asm>:2:2: note: instantiated into assembly here
        smulbb x8, x9, x8;
         ^
In file included from thirdparty/opus/opus_decoder.c:41:
In file included from thirdparty/opus/celt/celt.h:41:
In file included from thirdparty/opus/celt/entenc.h:31:
In file included from thirdparty/opus/celt/entcode.h:35:
In file included from thirdparty/opus/celt/ecintrin.h:32:
In file included from thirdparty/opus/celt/arch.h:133:
thirdparty/opus/celt/arm/fixed_armv5e.h:124:20: error: unrecognized instruction mnemonic [12]
       "#MULT16_16\n\t"
                    ^
<inline asm>:2:2: note: instantiated into assembly here
        smulbb x10, x10, x8;
         ^
In file included from thirdparty/opus/opus_decoder.c:41:
In file included from thirdparty/opus/celt/celt.h:41:
In file included from thirdparty/opus/celt/entenc.h:31:
In file included from thirdparty/opus/celt/entcode.h:35:
In file included from thirdparty/opus/celt/ecintrin.h:32:
In file included from thirdparty/opus/celt/arch.h:133:
thirdparty/opus/celt/arm/fixed_armv5e.h:124:20: error: unrecognized instruction mnemonic [12]
       "#MULT16_16\n\t"
                    ^
<inline asm>:2:2: note: instantiated into assembly here
        smulbb x10, x8, x10;
         ^
In file included from thirdparty/opus/opus_decoder.c:41:
In file included from thirdparty/opus/celt/celt.h:41:
In file included from thirdparty/opus/celt/entenc.h:31:
In file included from thirdparty/opus/celt/entcode.h:35:
In file included from thirdparty/opus/celt/ecintrin.h:32:
In file included from thirdparty/opus/celt/arch.h:133:
thirdparty/opus/celt/arm/fixed_armv5e.h:124:20: error: unrecognized instruction mnemonic [12]
       "#MULT16_16\n\t"
                    ^
<inline asm>:2:2: note: instantiated into assembly here
        smulbb x8, x8, x10;
         ^
16 errors generated.
scons: *** [thirdparty/opus/opus_decoder.iphone.opt.arm64.o] Error 1
In file included from thirdparty/opus/opus_multistream_encoder.c:34:
In file included from thirdparty/opus/opus_private.h:32:
In file included from thirdparty/opus/celt/arch.h:133:
thirdparty/opus/celt/arm/fixed_armv5e.h:124:20: error: unrecognized instruction mnemonic [12]
       "#MULT16_16\n\t"
                    ^
<inline asm>:2:2: note: instantiated into assembly here
        smulbb x10, x10, x12;
         ^
In file included from thirdparty/opus/opus_multistream_encoder.c:34:
In file included from thirdparty/opus/opus_private.h:32:
In file included from thirdparty/opus/celt/arch.h:133:
thirdparty/opus/celt/arm/fixed_armv5e.h:124:20: error: unrecognized instruction mnemonic [12]
       "#MULT16_16\n\t"
                    ^
<inline asm>:2:2: note: instantiated into assembly here
        smulbb x11, x11, x12;
         ^
In file included from thirdparty/opus/opus_multistream_encoder.c:34:
In file included from thirdparty/opus/opus_private.h:32:
In file included from thirdparty/opus/celt/arch.h:133:
thirdparty/opus/celt/arm/fixed_armv5e.h:124:20: error: unrecognized instruction mnemonic [12]
       "#MULT16_16\n\t"
                    ^
<inline asm>:2:2: note: instantiated into assembly here
        smulbb x10, x10, x11;
         ^
In file included from thirdparty/opus/opus_multistream_encoder.c:34:
In file included from thirdparty/opus/opus_private.h:32:
In file included from thirdparty/opus/celt/arch.h:133:
thirdparty/opus/celt/arm/fixed_armv5e.h:124:20: error: unrecognized instruction mnemonic [12]
       "#MULT16_16\n\t"
                    ^
<inline asm>:2:2: note: instantiated into assembly here
        smulbb x10, x10, x11;
         ^
In file included from thirdparty/opus/opus_multistream_encoder.c:34:
In file included from thirdparty/opus/opus_private.h:32:
In file included from thirdparty/opus/celt/arch.h:133:
thirdparty/opus/celt/arm/fixed_armv5e.h:124:20: error: unrecognized instruction mnemonic [12]
       "#MULT16_16\n\t"
                    ^
<inline asm>:2:2: note: instantiated into assembly here
        smulbb x9, x8, x9;
         ^
In file included from thirdparty/opus/opus_multistream_encoder.c:34:
In file included from thirdparty/opus/opus_private.h:32:
In file included from thirdparty/opus/celt/arch.h:133:
thirdparty/opus/celt/arm/fixed_armv5e.h:124:20: error: unrecognized instruction mnemonic [12]
       "#MULT16_16\n\t"
                    ^
<inline asm>:2:2: note: instantiated into assembly here
        smulbb x9, x8, x9;
         ^
In file included from thirdparty/opus/opus_multistream_encoder.c:34:
In file included from thirdparty/opus/opus_private.h:32:
In file included from thirdparty/opus/celt/arch.h:133:
thirdparty/opus/celt/arm/fixed_armv5e.h:124:20: error: unrecognized instruction mnemonic [12]
       "#MULT16_16\n\t"
                    ^
<inline asm>:2:2: note: instantiated into assembly here
        smulbb x9, x8, x9;
         ^
In file included from thirdparty/opus/opus_multistream_encoder.c:34:
In file included from thirdparty/opus/opus_private.h:32:
In file included from thirdparty/opus/celt/arch.h:133:
thirdparty/opus/celt/arm/fixed_armv5e.h:124:20: error: unrecognized instruction mnemonic [12]
       "#MULT16_16\n\t"
                    ^
<inline asm>:2:2: note: instantiated into assembly here
        smulbb x8, x8, x9;
         ^
8 errors generated.
scons: *** [thirdparty/opus/opus_multistream_encoder.iphone.opt.arm64.o] Error 1
In file included from thirdparty/opus/opus_encoder.c:33:
In file included from thirdparty/opus/celt/celt.h:41:
In file included from thirdparty/opus/celt/entenc.h:31:
In file included from thirdparty/opus/celt/entcode.h:35:
In file included from thirdparty/opus/celt/ecintrin.h:32:
In file included from thirdparty/opus/celt/arch.h:133:
thirdparty/opus/celt/arm/fixed_armv5e.h:124:20: error: unrecognized instruction mnemonic [12]
       "#MULT16_16\n\t"
                    ^
<inline asm>:2:2: note: instantiated into assembly here
        smulbb x8, x8, x9;
         ^
In file included from thirdparty/opus/opus_encoder.c:33:
In file included from thirdparty/opus/celt/celt.h:41:
In file included from thirdparty/opus/celt/entenc.h:31:
In file included from thirdparty/opus/celt/entcode.h:35:
In file included from thirdparty/opus/celt/ecintrin.h:32:
In file included from thirdparty/opus/celt/arch.h:133:
thirdparty/opus/celt/arm/fixed_armv5e.h:124:20: error: unrecognized instruction mnemonic [12]
       "#MULT16_16\n\t"
                    ^
<inline asm>:2:2: note: instantiated into assembly here
        smulbb x17, x15, x15;
         ^
In file included from thirdparty/opus/opus_encoder.c:33:
In file included from thirdparty/opus/celt/celt.h:41:
In file included from thirdparty/opus/celt/entenc.h:31:
In file included from thirdparty/opus/celt/entcode.h:35:
In file included from thirdparty/opus/celt/ecintrin.h:32:
In file included from thirdparty/opus/celt/arch.h:133:
thirdparty/opus/celt/arm/fixed_armv5e.h:124:20: error: unrecognized instruction mnemonic [12]
       "#MULT16_16\n\t"
                    ^
<inline asm>:2:2: note: instantiated into assembly here
        smulbb x15, x15, x16;
         ^
In file included from thirdparty/opus/opus_encoder.c:33:
In file included from thirdparty/opus/celt/celt.h:41:
In file included from thirdparty/opus/celt/entenc.h:31:
In file included from thirdparty/opus/celt/entcode.h:35:
In file included from thirdparty/opus/celt/ecintrin.h:32:
In file included from thirdparty/opus/celt/arch.h:133:
thirdparty/opus/celt/arm/fixed_armv5e.h:124:20: error: unrecognized instruction mnemonic [12]
       "#MULT16_16\n\t"
                    ^
<inline asm>:2:2: note: instantiated into assembly here
        smulbb x1, x0, x0;
         ^
In file included from thirdparty/opus/opus_encoder.c:33:
In file included from thirdparty/opus/celt/celt.h:41:
In file included from thirdparty/opus/celt/entenc.h:31:
In file included from thirdparty/opus/celt/entcode.h:35:
In file included from thirdparty/opus/celt/ecintrin.h:32:
In file included from thirdparty/opus/celt/arch.h:133:
thirdparty/opus/celt/arm/fixed_armv5e.h:124:20: error: unrecognized instruction mnemonic [12]
       "#MULT16_16\n\t"
                    ^
<inline asm>:2:2: note: instantiated into assembly here
        smulbb x0, x0, x1;
         ^
In file included from thirdparty/opus/opus_encoder.c:33:
In file included from thirdparty/opus/celt/celt.h:41:
In file included from thirdparty/opus/celt/entenc.h:31:
In file included from thirdparty/opus/celt/entcode.h:35:
In file included from thirdparty/opus/celt/ecintrin.h:32:
In file included from thirdparty/opus/celt/arch.h:133:
thirdparty/opus/celt/arm/fixed_armv5e.h:124:20: error: unrecognized instruction mnemonic [12]
       "#MULT16_16\n\t"
                    ^
<inline asm>:2:2: note: instantiated into assembly here
        smulbb x16, x16, x16;
         ^
In file included from thirdparty/opus/opus_encoder.c:33:
In file included from thirdparty/opus/celt/celt.h:41:
In file included from thirdparty/opus/celt/entenc.h:31:
In file included from thirdparty/opus/celt/entcode.h:35:
In file included from thirdparty/opus/celt/ecintrin.h:32:
In file included from thirdparty/opus/celt/arch.h:133:
thirdparty/opus/celt/arm/fixed_armv5e.h:124:20: error: unrecognized instruction mnemonic [12]
       "#MULT16_16\n\t"
                    ^
<inline asm>:2:2: note: instantiated into assembly here
        smulbb x0, x1, x1;
         ^
In file included from thirdparty/opus/opus_encoder.c:33:
In file included from thirdparty/opus/celt/celt.h:41:
In file included from thirdparty/opus/celt/entenc.h:31:
In file included from thirdparty/opus/celt/entcode.h:35:
In file included from thirdparty/opus/celt/ecintrin.h:32:
In file included from thirdparty/opus/celt/arch.h:133:
thirdparty/opus/celt/arm/fixed_armv5e.h:124:20: error: unrecognized instruction mnemonic [12]
       "#MULT16_16\n\t"
                    ^
<inline asm>:2:2: note: instantiated into assembly here
        smulbb x2, x0, x0;
         ^
In file included from thirdparty/opus/opus_encoder.c:33:
In file included from thirdparty/opus/celt/celt.h:41:
In file included from thirdparty/opus/celt/entenc.h:31:
In file included from thirdparty/opus/celt/entcode.h:35:
In file included from thirdparty/opus/celt/ecintrin.h:32:
In file included from thirdparty/opus/celt/arch.h:133:
thirdparty/opus/celt/arm/fixed_armv5e.h:124:20: error: unrecognized instruction mnemonic [12]
       "#MULT16_16\n\t"
                    ^
<inline asm>:2:2: note: instantiated into assembly here
        smulbb x0, x0, x1;
         ^
In file included from thirdparty/opus/opus_encoder.c:33:
In file included from thirdparty/opus/celt/celt.h:41:
In file included from thirdparty/opus/celt/entenc.h:31:
In file included from thirdparty/opus/celt/entcode.h:35:
In file included from thirdparty/opus/celt/ecintrin.h:32:
In file included from thirdparty/opus/celt/arch.h:133:
thirdparty/opus/celt/arm/fixed_armv5e.h:124:20: error: unrecognized instruction mnemonic [12]
       "#MULT16_16\n\t"
                    ^
<inline asm>:2:2: note: instantiated into assembly here
        smulbb x0, x1, x1;
         ^
In file included from thirdparty/opus/opus_encoder.c:33:
In file included from thirdparty/opus/celt/celt.h:41:
In file included from thirdparty/opus/celt/entenc.h:31:
In file included from thirdparty/opus/celt/entcode.h:35:
In file included from thirdparty/opus/celt/ecintrin.h:32:
In file included from thirdparty/opus/celt/arch.h:133:
thirdparty/opus/celt/arm/fixed_armv5e.h:124:20: error: unrecognized instruction mnemonic [12]
       "#MULT16_16\n\t"
                    ^
<inline asm>:2:2: note: instantiated into assembly here
        smulbb x2, x0, x0;
         ^
In file included from thirdparty/opus/opus_encoder.c:33:
In file included from thirdparty/opus/celt/celt.h:41:
In file included from thirdparty/opus/celt/entenc.h:31:
In file included from thirdparty/opus/celt/entcode.h:35:
In file included from thirdparty/opus/celt/ecintrin.h:32:
In file included from thirdparty/opus/celt/arch.h:133:
thirdparty/opus/celt/arm/fixed_armv5e.h:124:20: error: unrecognized instruction mnemonic [12]
       "#MULT16_16\n\t"
                    ^
<inline asm>:2:2: note: instantiated into assembly here
        smulbb x0, x0, x1;
         ^
In file included from thirdparty/opus/opus_encoder.c:33:
In file included from thirdparty/opus/celt/celt.h:41:
In file included from thirdparty/opus/celt/entenc.h:31:
In file included from thirdparty/opus/celt/entcode.h:35:
In file included from thirdparty/opus/celt/ecintrin.h:32:
In file included from thirdparty/opus/celt/arch.h:133:
thirdparty/opus/celt/arm/fixed_armv5e.h:124:20: error: unrecognized instruction mnemonic [12]
       "#MULT16_16\n\t"
                    ^
<inline asm>:2:2: note: instantiated into assembly here
        smulbb x0, x1, x1;
         ^
In file included from thirdparty/opus/opus_encoder.c:33:
In file included from thirdparty/opus/celt/celt.h:41:
In file included from thirdparty/opus/celt/entenc.h:31:
In file included from thirdparty/opus/celt/entcode.h:35:
In file included from thirdparty/opus/celt/ecintrin.h:32:
In file included from thirdparty/opus/celt/arch.h:133:
thirdparty/opus/celt/arm/fixed_armv5e.h:57:24: error: unrecognized instruction mnemonic [12]
       "#MULT16_32_Q15\n\t"
                        ^
<inline asm>:2:2: note: instantiated into assembly here
        smulwb x11, x11, x8
         ^
In file included from thirdparty/opus/opus_encoder.c:33:
In file included from thirdparty/opus/celt/celt.h:41:
In file included from thirdparty/opus/celt/entenc.h:31:
In file included from thirdparty/opus/celt/entcode.h:35:
In file included from thirdparty/opus/celt/ecintrin.h:32:
In file included from thirdparty/opus/celt/arch.h:133:
thirdparty/opus/celt/arm/fixed_armv5e.h:57:24: error: unrecognized instruction mnemonic [12]
       "#MULT16_32_Q15\n\t"
                        ^
<inline asm>:2:2: note: instantiated into assembly here
        smulwb x10, x10, x8
         ^
In file included from thirdparty/opus/opus_encoder.c:33:
In file included from thirdparty/opus/celt/celt.h:41:
In file included from thirdparty/opus/celt/entenc.h:31:
In file included from thirdparty/opus/celt/entcode.h:35:
In file included from thirdparty/opus/celt/ecintrin.h:32:
In file included from thirdparty/opus/celt/arch.h:133:
thirdparty/opus/celt/arm/fixed_armv5e.h:57:24: error: unrecognized instruction mnemonic [12]
       "#MULT16_32_Q15\n\t"
                        ^
<inline asm>:2:2: note: instantiated into assembly here
        smulwb x8, x9, x8
         ^
In file included from thirdparty/opus/opus_encoder.c:33:
In file included from thirdparty/opus/celt/celt.h:41:
In file included from thirdparty/opus/celt/entenc.h:31:
In file included from thirdparty/opus/celt/entcode.h:35:
In file included from thirdparty/opus/celt/ecintrin.h:32:
In file included from thirdparty/opus/celt/arch.h:133:
thirdparty/opus/celt/arm/fixed_armv5e.h:124:20: error: unrecognized instruction mnemonic [12]
       "#MULT16_16\n\t"
                    ^
<inline asm>:2:2: note: instantiated into assembly here
        smulbb x8, x20, x21;
         ^
In file included from thirdparty/opus/opus_encoder.c:33:
In file included from thirdparty/opus/celt/celt.h:41:
In file included from thirdparty/opus/celt/entenc.h:31:
In file included from thirdparty/opus/celt/entcode.h:35:
In file included from thirdparty/opus/celt/ecintrin.h:32:
In file included from thirdparty/opus/celt/arch.h:133:
thirdparty/opus/celt/arm/fixed_armv5e.h:124:20: error: unrecognized instruction mnemonic [12]
       "#MULT16_16\n\t"
                    ^
<inline asm>:2:2: note: instantiated into assembly here
        smulbb x11, x12, x11;
         ^
In file included from thirdparty/opus/opus_encoder.c:33:
In file included from thirdparty/opus/celt/celt.h:41:
In file included from thirdparty/opus/celt/entenc.h:31:
In file included from thirdparty/opus/celt/entcode.h:35:
In file included from thirdparty/opus/celt/ecintrin.h:32:
In file included from thirdparty/opus/celt/arch.h:133:
thirdparty/opus/celt/arm/fixed_armv5e.h:124:20: error: unrecognized instruction mnemonic [12]
       "#MULT16_16\n\t"
                    ^
<inline asm>:2:2: note: instantiated into assembly here
        smulbb x8, x8, x8;
         ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
scons: *** [thirdparty/opus/opus_encoder.iphone.opt.arm64.o] Error 1
scons: building terminated because of errors.

**Steps to reproduce:**
run following commands:
scons -j4 p=iphone tools=no bits=32 target=release arch=arm
scons -j4 p=iphone tools=no bits=64 target=release arch=arm64

**Minimal reproduction project:**

**Comment by akien-mga** [comment] 2019-04-04 08:03
Duplicate of #27658.

**Closed by akien-mga** 2019-04-04 08:03 UTC
Labels: bug, platform:ios, topic:buildsystem
