### ISSUE TITLE
Error when using a node with AnimationPlayer as a Singleton [Godot 4.0]

### ISSUE THREAD

**Issue by rarysson** [godotengine/godot#69177] opened 2022-11-25 18:43 UTC
### Godot version

4.0.beta-6

### System information

Windows 11

### Issue description

I was trying to make a scene transitioner to animate between scenes, so to make it easier to use, I've added the node as a singleton, but when I tried to run the project I get these errors:

![error](https://user-images.githubusercontent.com/22689195/204040560-bfe68c5d-6f9e-4b0c-80e8-ca5bd44378bc.png)

Is this expected when using a node with AnimationPlayer as a singleton?

### Steps to reproduce

1. Create any node.
2. Add an AnimationPlayer to the node you've created.
3. Go to the AutoLoad setting and add your node.
4. Try to use your singleton.

### Minimal reproduction project

[MVP.zip](https://github.com/godotengine/godot/files/10094684/MVP.zip)

**Comment by adamscott** [comment] 2022-11-25 19:36
Could not reproduce. Duplicate/relates to #69073. Was fixed by #69079.

**Closed** 2022-11-25 19:58 UTC
Labels: bug, topic:gdscript, topic:editor, needs testing, topic:animation
