### ISSUE TITLE
Vulkan: Rendering issues with MeshInstance3Ds sharing a scene with a NavigationRegion3D

### ISSUE THREAD

**Issue by DigitalJokerMan** [godotengine/godot#57557] opened 2022-02-02 17:48 UTC
### Godot version

4.0.alpha1.official (31a7ddbf8)

### System information

macOS 12.2 Beta, 2020 M1 Macbook Air (MacBookAir10,1), Vulkan (Forward Clustered & Forward Mobile)

### Issue description

In a scene that has a very basic navigation setup and a linked player scene, what I supposed is the lighting doesn't work as expected. From what I have observed, if the NavMesh is baked, any separate MeshInstances will render incorrectly.

Vulkan Forward Clustered:
<img width="1159" alt="Screen Shot 2022-02-02 at 10 29 00" src="https://user-images.githubusercontent.com/15147319/152205843-9ee3cddc-1870-40d2-bf0f-be9e7241e6d8.png">
The mesh is rendered with a black color & no shading.

Vulkan Forward Mobile:
<img width="1159" alt="Screen Shot 2022-02-02 at 10 31 29" src="https://user-images.githubusercontent.com/15147319/152206251-f451210c-237c-4290-a364-2ca6c858911c.png">
The mesh fails to render entirely.

It's also worth noting the significant amount of errors printed to the console upon loading the scene.
<img width="1148" alt="Screen Shot 2022-02-02 at 10 44 41" src="https://user-images.githubusercontent.com/15147319/152208434-c01a2eba-a4db-42fc-a8f3-c96eb50d6876.png">

### Steps to reproduce

The sample project I uploaded should easily demonstrate the issue that's occurring. It's very simplistic, you can play around with the materials.

If you disable the NavigationRegion3D (or switch away to the player scene), you can observe the issue no longer occurring. 
If you assign a material to the single static mesh inside the NavigationRegion3D, the issue stops occurring yet again.

### Minimal reproduction project

[NavigationLightingBug.zip](https://github.com/godotengine/godot/files/7988850/NavigationLightingBug.zip)

**Comment by Calinou** [comment] 2022-02-02 18:51
Duplicate of https://github.com/godotengine/godot/issues/51898 (same cause).

**Closed by Calinou** 2022-02-02 18:51 UTC
Labels: bug, topic:rendering, regression, topic:3d
