### ISSUE TITLE
Going for enums in the docs will just put you at the top of the page

### ISSUE THREAD

**Issue by YeldhamDev** [godotengine/godot#16285] opened 2018-02-01 14:59 UTC
**Godot version:**
2459eeb

**Issue description:**
Be by searching for them or clicking in a shortcut in another doc, going for any enum (e. g. the ones in the GlobalScope) will just place you at the top of the page.

**Comment by Falke117** [comment] 2018-04-04 08:52
Hi. I just found out this issue during searching for existing issues when opening new issues.
This issue is partially closed via issue #17396, and the remaining use cases are now separate into issue #17957 and issue #17958. 

(Issues, man, they are everywhere!.)

**Comment by akien-mga** [comment] 2018-04-04 08:54
Indeed, closing as duplicate of #17396 and follow-ups #17957 and #17958.

**Closed by akien-mga** 2018-04-04 08:54 UTC
Labels: bug, topic:editor, usability
