### ISSUE TITLE
Control+Up or Down on Scene dock does not move selected node

### ISSUE THREAD

**Issue by volzhs** [godotengine/godot#17633] opened 2018-03-19 14:36 UTC
**Godot version:**

godot 3.0 master 201d2d722

**OS/device including version:**

**Issue description:**

<kbd>Control</kbd> + <kbd>Up</kbd> or <kbd>Down</kbd> on Scene dock does not move selected node to up or down **when Scene dock is focused**.
3.0.2 official works.

**Steps to reproduce:**
1. select a node in Scene dock and stay mouse pointer in Scene dock
2. try <kbd>Control</kbd> + <kbd>Up</kbd> or <kbd>Down</kbd>  // does not work
3. move mouse pointer to viewport
4. try <kbd>Control</kbd> + <kbd>Up</kbd> or <kbd>Down</kbd>  // works

**Minimal reproduction project:**

**Comment by reduz** [comment] 2018-09-07 00:26
This received by SceneTreeDock, but for some reason something must be grabbing it before..
https://github.com/godotengine/godot/blob/master/editor/scene_tree_dock.cpp#L92
I suggest doing a git bisect against the 3.0 release to see when it stopped working.

**Comment by DualMatrix** [comment] 2018-09-16 16:12
Duplicate of #7736

**Closed** 2018-09-16 16:16 UTC
Labels: bug, hero wanted!, topic:editor, usability
