### ISSUE TITLE
Can't assign CanvasItem materials through code

### ISSUE THREAD

**Issue by DeeJayLSP** [godotengine/godot#53055] opened 2021-09-25 13:48 UTC
### Godot version

v4.0.dev.20210924.official [5e4a71200]

### System information

Kubuntu 21.04

### Issue description

I don't know if this is a bug or not, but it seems like one, since it worked normally on version 3 and shouldn't be that different.

While attempting to give a value to CanvasItem's Material through `.new()` it generates an error.

If this is not a bug, please tell how to do it correctly.

### Steps to reproduce

1 - Make any CanvasItem node

2 - Attach a script to it

3 - Type as it follows:

```GDScript
extends AnyCanvasItemNode #Ofc not an actual node

func _ready():
	material = CanvasItemMaterial.new()
        #OR
        material = ShaderMaterial.new()
```

4 - It generates the following error:
```
Error at (4,38): Cannot assign a value of type "CanvasItemMaterial" to a target of type "CanvasItemMaterial,ShaderMaterial".
```

### Minimal reproduction project

[Material error.zip](https://github.com/godotengine/godot/files/7229833/Material.error.zip)

**Comment by akien-mga** [comment] 2021-09-25 13:58
Duplicate of #42280.

**Closed by akien-mga** 2021-09-25 13:58 UTC
