### ISSUE TITLE
Search Help fails to jump to function if class isn’t open

### ISSUE THREAD

**Issue by Jayman2000** [godotengine/godot#59878] opened 2022-04-04 15:33 UTC
### Godot version

v4.0.alpha5.official [d7d528c15]

### System information

Arch Linux (I don’t know how to give a version for this), AMD Ryzen 5 3600 (x86_64), AMD Radeon RX 580 Series, Vulkan Clustered.

### Issue description

When you search the editor’s built-in documentation for a function, it tries to open the appropriate docs page and jump to the part that talks about that function. If the docs page wasn’t already open in the editor, then it won’t jump to the correct location.

### Steps to reproduce

1. Open any project.
2. Open the script workspace.
3. If `@GlobalScope` is open, then right click on it and choose “Close”.
4. Go to Help > Search Help.
5. Type in “print”.
6. Double click on the `print` function. `@GlobalScope` will open, but `print` won’t be at the top of the viewing area.
7. Search for “print” again. Now, `print` will be at the top of the viewing area.

**Comment by KoBeWi** [comment] 2022-04-04 18:25
Likely same cause as #59820

**Comment by Chaosus** [comment] 2022-04-05 06:37
Duplicate of https://github.com/godotengine/godot/issues/59820

**Closed by Chaosus** 2022-04-05 06:37 UTC
Labels: bug, topic:editor, usability
