### ISSUE TITLE
Visual Script Noodles Misalign if you zoom in our out of script

### ISSUE THREAD

**Issue by liquidape** [godotengine/godot#6645] opened 2016-09-29 16:11 UTC
**Operating system or device - Godot version:**
Windows 10 64 bit - Godot Alpha Buildv2.2 custom 9/29/2016

**Issue description** (what happened, and what was expected):
Visual Script Zooming is Broken

**Steps to reproduce:**
1.  Open a visual script (Like the "Pong Visual Script")
2.  Look at the script
3.  Press the zoom buttons in the top left corner of the zoom window
4.  Note the connections to all the the nodes now are misaligned.

![godot windows tools 64_2016-09-29_12-09-52](https://cloud.githubusercontent.com/assets/4421587/18962165/aba85258-863d-11e6-9fe4-ff6110e982c2.png)

**Comment by akien-mga** [comment] 2016-09-29 16:16
Thought it had already been reported, but I can't find a duplicate in the end :)

**Comment by liquidape** [comment] 2016-09-29 16:28
I searched too and did not see it.  Seemed like low hanging fruit bug.

**Comment by Hinsbart** [comment] 2016-09-29 20:12
It's a duplicate of #6342.
But good job on the noodle reference, made my day :)

**Closed** 2016-09-29 20:17 UTC
Labels: bug, topic:editor, topic:visualscript

**Comment by vnen** [comment] 2016-09-29 21:23
We found a name for Godot's visual scripting language: Noodles 😆

**Comment by liquidape** [comment] 2016-09-30 00:18
Haha, I just picked up the term from how Blender devs refer to them.
