### ISSUE TITLE
AtlasTexture uses Atlas's UV in canvas_item shader

### ISSUE THREAD

**Issue by qustrolabe** [godotengine/godot#61563] opened 2022-05-31 13:13 UTC
### Godot version

3.4.4.stable.arch_linux

### System information

Arch Linux, OpenGL ES 3.0 Renderer: AMD TURKS

### Issue description

I created TextureRect, put AtlasTexture on it, created material and tried to create canvas_item shader.
I meant to use UV in fragment() function, but noticed that UV.x > 0.5 reffers to not "right part of AtlasTexture", but "right part of AtlasTexture's Atlas, and UV equals to (1,1) at Atlas's bottom-right corner (expected at AtlasTexture's region bottom-right corner).

I understand that this is probably caused by how Atlas's texture stored on videocard, but still expected to have workaround to get local fragrament coords in my shader.

### Steps to reproduce

1. Create TextureRect or Sprite.
2. Add AtlasTexture resource to it.
3. Set AtlasTexture's Atlas to some image, and set region on that Atlas
4. Create material and shader resources for your Sprite
5. Example shader code:
```c
shader_type canvas_item;

void fragment() {
	float test = 0.0;
	if( (UV.x > 0.5) ) test = 1.0; // Left part of sprite expected to be black, and right - white

	COLOR = vec4(test,test,0,1);
	COLOR.rgb += test;	
}
```
Result:
Instead of separating left and right side at region center it separtes them at Atlas's center
(AtlasTexture with region Rect(0,0,30,30) from 40x40 Atlas will be separated at x = 20 instead of 15)

**Comment by arkology** [comment] 2022-05-31 14:47
This is duplicate of several existing issues (can't find them right now).
Actually this is expected behaviour

**Comment by belzecue** [comment] 2022-12-27 12:29
I added a simple repro to #57401 showing that UVs for regioned sprites get calculated from the atlas UVs instead of the region.

**Comment by Calinou** [comment] 2022-12-27 15:27
Duplicate of https://github.com/godotengine/godot/issues/57401.

**Closed by Calinou** 2022-12-27 15:27 UTC
Labels: bug, topic:shaders, topic:2d
