### ISSUE TITLE
Option to suppress errors in "Errors" tab from JSON.parse

### ISSUE THREAD

**Issue by mnn** [godotengine/godot#43429] opened 2020-11-10 08:33 UTC
**Godot version:** 3.2.3 stable official

**OS/device including version:** Linux 64b

 
**Issue description:**

I am expecting an invalid JSON (in tests), yet I found no way of suppressing errors from `JSON.parse`. I check the return value, I don't want it to spam the errors tab with meaningless (handled) errors.

**Steps to reproduce:**
```gdscript
extends Node

func _ready():
	var res = JSON.parse("not a JSON")
	if res.error != OK: print("handled error")
	get_tree().quit()
```
See in errors tab:
```
E 0:00:00.263   parse: Error parsing JSON at line 0: Expected 'true','false' or 'null', got 'not'.
  <C++ Source>  core/bind/core_bind.cpp:3284 @ parse()
  <Stack Trace> 03.gd:4 @ _ready()
```

**Comment by Calinou** [comment] 2021-03-04 17:34
I suppose we should expose `ERR_PRINT_OFF;` and `ERR_PRINT_ON;` to GDScript to solve this (and document the caveats of using this property).

cc @Xrayez

**Comment by Xrayez** [comment] 2021-03-04 17:42
Related to #35537.

To summarize, it's OK to revert to previous behavior, but then there are people who'd like to have those parse errors to be caught in the editor's debugger as well...

Therefore, I think adding utility function to control error output would be a good compromise, what you ask for is probably described in godotengine/godot-proposals#1763.

**Comment by JotaFaD** [comment] 2021-03-21 06:06
IMO, parse errors should not be printed to the debbuger, if people want them, just check if `JSONParseResult.error != Error.OK"` and print `JSONParseResult.error_string` manually.

I'll use the project I'm working on as an example (the reason I found this issue). In my project I have a data field that sometimes is a simple string and sometimes is a string encoding a json file.

If it's a simple string I emit signal 1, otherwise, if it's a json I emit signal 2. By applying `JSON.parse` and checking for an error I know which signal needs to be called. The problem is, even though the code works perfectly in both cases, each time a simple string is sent as data, Godot will print the parse error to the console. And there's no way I can disable that.

If parse errors were not printed to the console, this would not be a problem and people that want the message could get it using two lines of code. Disabling error outputs just because your codes is already handling error cases and godot continues to print the messages is just a lot more effort.

**Comment by Xrayez** [comment] 2021-03-21 11:39
> If it's a simple string I emit signal 1, otherwise, if it's a json I emit signal 2. By applying `JSON.parse` and checking for an error I know which signal needs to be called. The problem is, even though the code works perfectly in both cases, each time a simple string is sent as data, Godot will print the parse error to the console. And there's no way I can disable that.

I don't understand the use case of comparing string vs JSON, could you elaborate why you need this?

Some cases which lead to a parse error may as well reveal internal JSON parser bugs, and they can be potentially resolved to minimize those errors.

But yeah I totally understand that there may be erroneous data which is out of control of a project itself, since that may be an external data.

I think it would be OK to revert #33201, someone may think otherwise though: #33169.

Another thing which can be done is to add `quiet = true` argument for the parse method.

**Comment by JotaFaD** [comment] 2021-03-21 18:54
> I don't understand the use case of comparing string vs JSON, could you elaborate why you need this?

Sure, I'm using Godot to communicate with an Arduino using a Serial port and the JSONs allow me to set variables in Godot's nodes from within my Arduino code. In the future I want to use this to create virtual labs or simulate control systems. For ease of usability though, I want to be able to send simple strings to the serial port, like you do in the arduino serial monitor. I could embed them inside a JSON, but it would defeat the usability criteria.

Like I said in the previous reply, I already handled both cases in the code, but every time a simple string is sent, the parser will throw an error in the debugger.

> Another thing which can be done is to add quiet = true argument for the parse method.

This would be a good solution in my opinion.

**Comment by Xrayez** [comment] 2021-03-21 19:06
> For ease of usability though, I want to be able to send simple strings to the serial port, like you do in the arduino serial monitor. I could embed them inside a JSON, but it would defeat the usability criteria.

It makes me think that perhaps you handle a wrong kind of string for JSON. For instance, this works fine:
```gdscript
var result = JSON.parse('"my_string"').result
print(result)  # Prints my_string
```
while this produces an error:
```gdscript
var result = JSON.parse("my_string").result
print(result)
```

![image](https://user-images.githubusercontent.com/17108460/111917501-02610f00-8a89-11eb-9c78-ce243953fe1a.png)

That said, if you have control over how you encode those messages, then the approach above may work for your case I think.

**Comment by JotaFaD** [comment] 2021-03-21 19:17
> It makes me think that perhaps you handle a wrong kind of string for JSON.

That is indeed the error I'm getting, I'll add the extra strings to solve it, thanks for the tip.

**Comment by Calinou** [comment] 2021-05-01 21:13
Duplicate of https://github.com/godotengine/godot/issues/35537.

**Closed by Calinou** 2021-05-01 21:13 UTC
Labels: enhancement, topic:core
