### ISSUE TITLE
Spawning Particles creates a green visual fragment bug.

### ISSUE THREAD

**Issue by ParasiteSt** [godotengine/godot#75745] opened 2023-04-06 11:30 UTC
### Godot version

4.0.2

### System information

Windows 11, Vulkan

### Issue description

The particle system when re-spawning particles and rotating a camera to make them visible can create a green visual bug in the scene. 

### Steps to reproduce

The bug is not easy to replicate that I could see, from what I know it comes from possibly the material used for the mesh the particle system is using, but that could not be the case. I cannot share my project directly, but was able to recreate the same effect relatively to the same results. 

### Minimal reproduction project

This is a very minimal project, but while the bug is very easy to make happen in this project, recreating it on your own project may not be as simple. (for that reason I did not try to add steps to reproduce as I am not sure where this issue is coming from directly)
[GreenBlinkBug.zip](https://github.com/godotengine/godot/files/11170030/GreenBlinkBug.zip)

- To create the visual bug you should only need to launch the project
- Click play to start the runtime of the project
- Your mouse should get captured on the screen and allow you to rotate a camera in a 360 degree rotation
- The visual bug will not show up right away, let the particles spawn and they should de-spawn and start to spawn over again, after a few times of them re-spawning if you spin the camera slowly the green artifact should appear and will continue doing so as long as you do not shut down the runtime and continue spinning the camera when more particles spawn out of view.

**Comment by Calinou** [comment] 2023-04-06 17:23
- Duplicate of https://github.com/godotengine/godot/issues/71935.

**Closed by Calinou** 2023-04-06 17:23 UTC
