### ISSUE TITLE
AnimatedTexture does not update in the editor unless the user scrolls/pans accross in the workspace

### ISSUE THREAD

**Issue by adarshcat** [godotengine/godot#83921] opened 2023-10-25 06:00 UTC
### Godot version

v4.2.beta2.mono.official [f8818f85e]

### System information

Windows 11 - Godot v4.2.beta2.mono - Forward Mobile - .NET 7

### Issue description

When using AnimatedTexture resource on a TextureRect, the texture doesnt animate unless we pan across in the workspace. It does work fine once the game is running though.

https://github.com/godotengine/godot/assets/72686802/b96791e0-fcc1-49fa-bea7-44bc5da92033

### Steps to reproduce

- Add a AnimatedTexture resource to a TextureRect
- Texture doesnt update unless panning

### Minimal reproduction project

N/A

**Comment by Rindbee** [comment] 2023-10-25 11:27
Duplicate of #77415.

**Comment by AThousandShips** [comment] 2023-10-25 12:08
Duplicate of #77415

**Closed by AThousandShips** 2023-10-25 12:08 UTC

**Comment by KoBeWi** [comment] 2023-10-25 15:57
As a workaround you can assign it a shader that uses TIME.
