### ISSUE TITLE
Using multimesh floods log with color issues slowing down the interface

### ISSUE THREAD

**Issue by BastiaanOlij** [godotengine/godot#21389] opened 2018-08-24 23:48 UTC
**Godot version:**
Master commit 34e58fd831172bad1eebb748c97238c28864423a

**OS/device including version:**
Windows

**Issue description:**
I'm using a multimesh in my scene (see vehicle demo project) and the log gets filled with entries when positioning the meshes:

```
 At: drivers\gles3\rasterizer_storage_gles3.cpp:4355
ERROR: RasterizerStorageGLES3::multimesh_instance_get_color: Condition ' multimesh->color_format == VisualServer::MULTIMESH_COLOR_NONE ' is true. returned: Color()
   At: drivers\gles3\rasterizer_storage_gles3.cpp:4355
ERROR: RasterizerStorageGLES3::multimesh_instance_get_color: Condition ' multimesh->color_format == VisualServer::MULTIMESH_COLOR_NONE ' is true. returned: Color()
   At: drivers\gles3\rasterizer_storage_gles3.cpp:4355
ERROR: RasterizerStorageGLES3::multimesh_instance_get_color: Condition ' multimesh->color_format == VisualServer::MULTIMESH_COLOR_NONE ' is true. returned: Color()
   At: drivers\gles3\rasterizer_storage_gles3.cpp:4355
ERROR: RasterizerStorageGLES3::multimesh_instance_get_color: Condition ' multimesh->color_format == VisualServer::MULTIMESH_COLOR_NONE ' is true. returned: Color()
   At: drivers\gles3\rasterizer_storage_gles3.cpp:4355
ERROR: RasterizerStorageGLES3::multimesh_instance_get_color: Condition ' multimesh->color_format == VisualServer::MULTIMESH_COLOR_NONE ' is true. returned: Color()
   At: drivers\gles3\rasterizer_storage_gles3.cpp:4355
ERROR: RasterizerStorageGLES3::multimesh_instance_get_color: Condition ' multimesh->color_format == VisualServer::MULTIMESH_COLOR_NONE ' is true. returned: Color()
   At: drivers\gles3\rasterizer_storage_gles3.cpp:4355
ERROR: RasterizerStorageGLES3::multimesh_instance_get_color: Condition ' multimesh->color_format == VisualServer::MULTIMESH_COLOR_NONE ' is true. returned: Color()
   At: drivers\gles3\rasterizer_storage_gles3.cpp:4355
ERROR: RasterizerStorageGLES3::multimesh_instance_get_color: Condition ' multimesh->color_format == VisualServer::MULTIMESH_COLOR_NONE ' is true. returned: Color()
```
Now I get that I indeed have my multimesh set to color none but it's not a really useful message :)

**Steps to reproduce:**
Easiest is to grab a copy of my vehicle demo project and just adjust the track width to kick off the logic that updates the multimesh

**Minimal reproduction project:**
https://github.com/BastiaanOlij/vehicle-demo

**Comment by eon-s** [comment] 2018-08-25 01:32
About the way errors are presented, may be good to have a counter when the exact same error is presented more than once between frames to prevent flooding.

**Comment by reduz** [comment] 2018-09-07 23:04
I fixed this some days ago, but test it again please

**Comment by akien-mga** [comment] 2018-09-10 15:35
Duplicate of #17850.

**Closed by akien-mga** 2018-09-10 15:35 UTC
Labels: bug, topic:rendering
