### ISSUE TITLE
Setting a new mesh to MeshInstance3D breaks shader instance uniforms

### ISSUE THREAD

**Issue by JohanAR** [godotengine/godot#66997] opened 2022-10-06 18:26 UTC
### Godot version

v4.0.beta.custom_build [61021c08f]

### System information

Fedora 36 KDE, RTX 3080

### Issue description

Creating a MeshInstance3D, assigning a mesh and a material, and setting instance uniforms works as expected. However if the mesh is set again, the instance uniforms stop working until the scene is reloaded.

Does not seem to matter if the material is assigned to the Mesh material, MeshInstance3D material override or the GeometryInstance3D material override.

### Steps to reproduce

1) Load reproduction project with node_3d.tscn
2) Change the MeshInstance3D's shader uniform "My Uniform" and verify that the shader material modifies the mesh.
3) Click the root Node3d and increase the "dummy" variable. This is a @tool script so this will trigger the test code that sets a new mesh on the MeshInstance3D node.
4) Observe that the mesh becomes flat, and the "My Uniform" no longer has any effect on the mesh.
5) Save the scene, close it, and open it again.
6) Observe that "My Uniform" works again.

### Minimal reproduction project

[SetUniformOverrideTest.zip](https://github.com/godotengine/godot/files/9727524/SetUniformOverrideTest.zip)

**Comment by JohanAR** [comment] 2023-01-24 08:56
I tried fixing this myself, but I couldn't find the issue as I don't have enough knowledge about the inner workings of Godot rendering.

**Comment by lostminds** [comment] 2023-02-02 12:50
Looks like this may be the same issue: https://github.com/godotengine/godot/issues/58113 ?

**Comment by JohanAR** [comment] 2023-02-02 14:39
Looks like the same! Did not find it when searching prior to opening a new issue.

**Comment by Calinou** [comment] 2023-02-02 14:43
Duplicate of https://github.com/godotengine/godot/issues/58113.

**Closed by Calinou** 2023-02-02 14:43 UTC
Labels: bug, topic:editor, confirmed, topic:3d
