### ISSUE TITLE
GUI bug when changing movement speed in viewport with right click pressed

### ISSUE THREAD

**Issue by Zekiah-A** [godotengine/godot#59103] opened 2022-03-13 13:38 UTC
### Godot version

v4.0.alpha4.official [f47097973]

### System information

Arch Linux, Vulkan, x86_64, 1920*1080 Display

### Issue description

When zooming in and out in the view port, a magnifier usually appears:
![image](https://user-images.githubusercontent.com/73035340/158062051-24ebfe2f-096d-4b21-957e-66f4fb7753bd.png)

However, when right click is held (to look around / free look), and you scroll to zoom, instead a small few pixel bug appears under the bar that shows the speed 
![image](https://user-images.githubusercontent.com/73035340/158062001-65a363bd-8920-4fa1-bd7d-1c8ac4aad406.png)

### Steps to reproduce

Hold down right click to free look, and then use the scroll wheel to change the movement speed in the view port, and it will appear.

**Comment by Calinou** [comment] 2022-03-13 17:30
This is a duplicate of another issue, but I can't find it right now. This is due to the same cause as https://github.com/godotengine/godot/issues/57129, but I remember seeing a dedicated issue for the freelook speed icon specifically.

For reference, this different indicator is the freelook speed indicator, but the icon is too small following the switch from nanosvg to ThorVG for editor icon rendering.

**Comment by akien-mga** [comment] 2022-03-13 17:36
Duplicate of https://github.com/godotengine/godot/issues/58434

**Closed by akien-mga** 2022-03-13 17:36 UTC
Labels: bug, topic:editor, regression, topic:3d
