### ISSUE TITLE
ERROR: RasterizerGLES::canvas_light_shadow_buffer_create

### ISSUE THREAD

**Issue by twinpigs** [godotengine/godot#7767] opened 2017-02-09 06:48 UTC
**Operating system or device - Godot version:**
Laptop, Intel HD Graphics 3000, Windows 7 and 10 - Godot version: 2.1.2

**Issue description:**
When just  starts Godot, before any project open, there is error in console appears:

> ERROR: RasterizerGLES::canvas_light_shadow_buffer_create: Condition ' status != 0x8CD5 ' is true. returner: RID()
> At: drivers\gles2\rasterizer_gles2.cpp:8856

The same error appears in Godot debugger when project starts playing. Some big sprites are disappeared in playing project.

**On the same (dual boot) machine running Linux there is no error, and all sprites are in places.**

**Steps to reproduce:**
Just run Godot under Windows, I think it's enough.

![2017-02-08 13 18 23](https://cloud.githubusercontent.com/assets/1871642/22772034/c0c5cbaa-eeb3-11e6-922f-35294495a071.png)

**Comment by bojidar-bg** [comment] 2017-02-09 07:43
Duplicate of #5392 actually, ops.

**Closed by bojidar-bg** 2017-02-09 07:43 UTC
Labels: bug, discussion, platform:windows
