### ISSUE TITLE
Sun preview disappears in weird circumstances

### ISSUE THREAD

**Issue by andersmmg** [godotengine/godot#57218] opened 2022-01-25 18:08 UTC
### Godot version

v4.0.alpha1.official [31a7ddbf8]

### System information

Manjaro Linux, GTX 1650

### Issue description

I'm not sure where else this happens, but when I expand the mesh options section in the editor, the sun preview disappears and reappears as I toggle it. No idea if this could be part of something worse, but so far this seems to be the only symptom.

https://user-images.githubusercontent.com/16022203/151034042-e85758a5-555e-4308-a0c0-acb6660f7165.mp4

Note: this is in an empty scene with only a MeshInstance3D, also happens on a scene with a bunch of 3D nodes in it.

### Steps to reproduce

Create a node with a mesh, create the mesh and toggle the dropdown while looking at the sun.

**Comment by Calinou** [comment] 2022-01-25 18:16
This is a duplicate of another issue, but I can't find it right now.

**Comment by ceLoFaN** [comment] 2022-01-25 18:21
https://github.com/godotengine/godot/issues/47912 ?

**Closed** 2022-01-25 18:47 UTC
Labels: bug, topic:rendering, topic:3d
