### ISSUE TITLE
Old editor layout sizes are wrong

### ISSUE THREAD

**Issue by YeldhamDev** [godotengine/godot#23284] opened 2018-10-25 16:39 UTC
**Godot version:**
 d47cec4

**Issue description:**
Did the way that editor layout sizes are handled changed? The default and that have been created before have their docks squished to the sides, but newly created ones are fine.

**Comment by akien-mga** [comment] 2018-10-25 16:43
That code was changed in #23114 yeah.

**Comment by groud** [comment] 2018-10-25 16:49
I think I cannot do anything about that.
Unless if we version-control the editor layout properties and make a converter, there is no way to solve the problem. I think we can consider this as a "wont fix".

**Comment by groud** [comment] 2018-10-25 16:51
I think I cannot do anything about that.
Unless if we version-control the editor layout properties and make a converter, there is no way to solve the problem. I think we can consider this as a "wont fix".

**Comment by YeldhamDev** [comment] 2018-10-25 16:59
@groud Then the default layout should be fixed at least.

**Comment by groud** [comment] 2018-10-25 17:01
> Then the default layout should be fixed at least.

Well, it is. When you create a new project it opens fine, does it ?

**Comment by YeldhamDev** [comment] 2018-10-25 17:06
No, it doesn't, nor setting "Default" in the layout menu.

**Comment by groud** [comment] 2018-10-25 17:12
I don't get why you say :

> but newly created ones are fine

then.

Do you have a screenshot ?
Can anyone reproduce the bug ?

**Comment by YeldhamDev** [comment] 2018-10-25 17:19
Here are the dock sizes in 3.0.*:
![3_0](https://user-images.githubusercontent.com/30739239/47518023-3ad07480-d860-11e8-98d0-c5ab37d36ddf.png)

Here are they now in 3.1:
![3_1](https://user-images.githubusercontent.com/30739239/47518029-3d32ce80-d860-11e8-9ea5-2db2e0350fec.png)

**Comment by YeldhamDev** [comment] 2018-10-25 17:35
Yes, I have created new projects for each version (even if it doesn't matter to the problem at hand).

**Comment by groud** [comment] 2018-10-25 18:07
Ah, so it only shrinked a little bit. What is the problem with the new layout but the fact it is a little bit smaller ?

Do two large thumbnails fit in the column or not ? (on my version it does)

**Comment by groud** [comment] 2018-10-25 18:10
Maybe there is something kept  stored but editor wise for the default layout, I don't know... It looks OK on my side so I find that weird.

Maybe there is a way to define the default layout but I don't know where it is made.

**Comment by YeldhamDev** [comment] 2018-10-25 18:59
> Ah, so it only shrinked a little bit. What is the problem with the new layout but the fact it is a little bit smaller?

The problem is that this was caused by something completely unrelated.

> Maybe there is a way to define the default layout but I don't know where it is made.

https://github.com/godotengine/godot/blob/master/editor/editor_node.cpp#L5505

> The per-project layout settings are stored outside the project folder and I am not sure they get deleted when you delete a project.

**This doesn't matter here!**

**Comment by groud** [comment] 2018-10-25 19:56
Well, sorry, I cannot help. I cannot reproduce the bug. :/

**Closed** 2018-10-25 21:19 UTC
Labels: bug, topic:editor, usability
