### ISSUE TITLE
Animation editor requires a mouse with a physical scroll wheel to work

### ISSUE THREAD

**Issue by PabloNeirotti** [godotengine/godot#71278] opened 2023-01-12 17:58 UTC
### Godot version

v4.0.beta11.official [91713ced8]

### System information

macOS Ventura 13.1 (22C65)

### Issue description

I'm guessing the issue is on Godot for Mac, and it's about the Animation editor:

<img width="1766" alt="Screenshot 2023-01-12 at 6 52 45 PM" src="https://user-images.githubusercontent.com/905216/212142216-3918b6ba-1d4a-46d2-90fe-9153d6405262.png">

Using the trackpad or the magic mouse, I cannot scroll nor resize the value scale of the editor.

I was fortunate enough to have a mouse with a physical wheel laying around. I connected it in and was able to scroll and resize the value scale. But it would be huge if this part of the editor took any kind of scroll to work as well, not just physical scroll wheels.

Thanks!

### Steps to reproduce

Launch the Animation editor on a Mac, and use the Magic Trackpad or Magic Mouse to scroll. It won't.

### Minimal reproduction project

N/A

**Comment by Calinou** [comment] 2023-01-12 20:27
Duplicate of https://github.com/godotengine/godot/issues/38237.

**Closed by Calinou** 2023-01-12 20:27 UTC
