### ISSUE TITLE
color HSV constructor 

### ISSUE THREAD

**Issue by BlenderNPR** [godotengine/godot#15782] opened 2018-01-16 15:01 UTC
There are hsv member variables in Color type, yet there is no constructor to put hsv into use.
Facing this problem:
color(1,1,1,1) << in rgba 
color(1,1,1,1) << in hsva?

Need hsv constructor, please. Thank 😁

HSV is more intuitive compared to RGB.

**Comment by groud** [comment] 2018-01-16 16:15
You already have a set_hsv() function, we cannot define two constructors with the same signature.

**Comment by vnen** [comment] 2018-01-16 16:24
> color(1,1,1,1) << in rgba
> color(1,1,1,1) << in hsva?

The problem is how to differentiate between the two? It's impossible to use the same constructor. Though we have `Color8` and `ColorN` constructors, maybe we can have `ColorHSV`?

**Comment by akien-mga** [comment] 2018-01-16 16:39
The problem with `Color8`, `ColorN` and `ColorHSV` is that they're hacky GDScript-specific methods. It would be better to have proper static constructors like `Color Color.from_hsv(h, s, v)` and `Color Color(String name, float alpha=1.0)`. See also #15435 and #14704.

**Comment by vnen** [comment] 2018-01-16 16:55
> It would be better to have proper static constructors like `Color Color.from_hsv(h, s, v)` and `Color Color(String name, float alpha=1.0)`.

I agree. The problem is more fundamental because built-in types don't have static functions. I'm not sure if there's a hard limitation for that, but that's what happens currently.

**Comment by akien-mga** [comment] 2018-02-19 20:51
Fixed by #15852.

**Closed by akien-mga** 2018-02-19 20:51 UTC
Labels: enhancement, topic:core
