### ISSUE TITLE
Gamepad vibration not working on Nintendo controllers

### ISSUE THREAD

**Issue by lentsius-bark** [godotengine/godot#56121] opened 2021-12-21 09:15 UTC
### Godot version

3.x branch

### System information

Windows 11, gforce 1060

### Issue description

using the input singleton function to trigger a vibration event on a gamepad:
```
Input.start_joy_vibration(0, 1.0, 1.0, 1.00)
```

does not make the controller vibrate, it does work for playstatioin and xbox ones though.

Tested on the nintendo switch pro controller and the little joycons

### Steps to reproduce

run a project and call the start_joy_vibration function of the input singleton

```Input.start_joy_vibration(0, 1.0, 1.0, 1.00)```

**Comment by Calinou** [comment] 2021-12-21 16:40
Related to https://github.com/godotengine/godot/issues/14634.

**Comment by madmiraal** [comment] 2021-12-27 11:51
It's a duplicate of #14634.

**Closed** 2021-12-27 15:56 UTC
Labels: bug, topic:porting, topic:input
