### ISSUE TITLE
Interface screw when any language with long name selected in script creating dialog

### ISSUE THREAD

**Issue by Teashrock** [godotengine/godot#32768] opened 2019-10-12 08:53 UTC
**Godot version:**
3cc94b2c0

**OS/device including version:**
Windows 10 x64

**Issue description:**
![image](https://i.imgur.com/ptxxRr4.png)

**Steps to reproduce:**
1. Open script creating window.
2. Select VisualScript.
3. See the bug.

**Minimal reproduction project:**
Not needed.

**Comment by Teashrock** [comment] 2019-10-12 09:56
@akien-mga @groud @YeldhamDev 
UPDETO! Looks like it's not with only "VisualScript", but all aside "C#".  I suspect that interface self-adjusting to contained string's length is to blame.

**Comment by YeldhamDev** [comment] 2019-10-12 12:17
I'm unable to reproduce this.

**Comment by Teashrock** [comment] 2019-10-12 13:05
@YeldhamDev 
Not appeared for me too in random second attempt. Don't know, what's this.

**Comment by YeldhamDev** [comment] 2019-10-12 13:09
Did you change the editor's scale when this happened?

**Comment by Teashrock** [comment] 2019-10-12 13:14
@YeldhamDev
No, not at all. Fullscreen and that's it.

**Comment by fire** [comment] 2019-11-07 16:53
It looks somewhat similiar to https://github.com/godotengine/godot/issues/32790

**Comment by YeldhamDev** [comment] 2020-01-08 20:21
@Teashrock Can you still reproduce this?

**Comment by Teashrock** [comment] 2020-01-10 06:32
@YeldhamDev 
Not tried intentionally, but didn't see it either.

**Comment by YeldhamDev** [comment] 2020-01-10 12:00
I will close this for now, give me a heads-up if you see it again.

**Closed by YeldhamDev** 2020-01-10 12:00 UTC
Labels: bug, topic:editor
