### ISSUE TITLE
Godot tries to load .cs file even thoug no node needs it anymore 3.1.2 mono

### ISSUE THREAD

**Issue by ComLarsic** [godotengine/godot#35481] opened 2020-01-23 17:24 UTC
I am using Godot mono 3.1.2

i moved a C# script to a different folder and connected the node to it. however now it doesn't build any more because it is trying to load the script from the other location even though its unused.

**Comment by JupiterRider** [comment] 2020-01-23 20:03
I Can confirm that behaviour. As workaround, you can edit the csproj-File in your Project by Hand:
```
  <ItemGroup>
    <Compile Include="Properties\AssemblyInfo.cs" /> 
    <Compile Include="scripts\*.cs" /> 
  </ItemGroup>
```
Mine looks like that. 
You need specify the path to new moved cs-Skript or use a wildcard like me.

**Comment by FeatherAntennae** [comment] 2020-01-23 21:00
It's a known issue and a limitation of the current C# implementation.

https://docs.godotengine.org/en/latest/getting_started/scripting/c_sharp/c_sharp_basics.html#current-gotchas-and-known-issues

https://github.com/godotengine/godot/issues/12917

**Comment by ComLarsic** [comment] 2020-01-25 13:41
> I Can confirm that behaviour. As workaround, you can edit the csproj-File in your Project by Hand:
> 
> ```
>   <ItemGroup>
>     <Compile Include="Properties\AssemblyInfo.cs" /> 
>     <Compile Include="scripts\*.cs" /> 
>   </ItemGroup>
> ```
> 
> Mine looks like that.
> You need specify the path to new moved cs-Skript or use a wildcard like me.

@JupiterRider Thanks man! that seemed to work!

**Comment by Calinou** [comment] 2020-01-25 15:21
Duplicate of #12917 – the underlying cause is the same.

**Closed by Calinou** 2020-01-25 15:21 UTC
