### ISSUE TITLE
Duplicate node in inherited scene after rename

### ISSUE THREAD

**Issue by rcorre** [godotengine/godot#34738] opened 2020-01-02 02:01 UTC
**Godot version:**

3.1.2.stable.custom_build

**OS/device including version:**

Linux 5.4.6-arch1-1 x86_64 GNU/Linux

**Issue description:**

Renaming a node in a scene can create a duplicate node in an inherited scene.

**Steps to reproduce:**

1. Create a scene:
    - Spatial
        - Spatial
2. Save as `Spatial.tscn`
3. Create an inherited scene from the prior scene
4. Add a child `Spatial2`:
    - Spatial
        - Spatial
        - Spatial2
5. Attach a script to `Spatial2`
6. Save this new scene as `Spatial2.tscn`
7. Close `Spatial2.tscn`
8. Open `Spatial.tscn`, rename the child to `Spatial2`, and save again:
    - Spatial
        - Spatial2
9. Open `Spatial2.tscn` again, note that the node `Spatial2` is listed twice
10. Click on one `Spatial2` node, both are selected

**Minimal reproduction project:**
![1577926065](https://user-images.githubusercontent.com/2496231/71649097-cb62da00-2cd9-11ea-8025-999772e166b9.png)
[example.zip](https://github.com/godotengine/godot/files/4014776/example.zip)

**Comment by rcorre** [comment] 2020-01-02 02:07
I was able to resolve this in my project by manually editing the .tscn file and deleting the duplicate nodes.

**Comment by Zylann** [comment] 2020-01-02 02:18
So everytime someone renames a node, we must parse the entire project for scenes that could inherit from this one and see if the name is free? That sounds quite bad...
Or do the check when the inheriting scene is instanced? Will be a bit late.

**Comment by rcorre** [comment] 2020-01-02 02:35
Yeah, this is a tricky one. Even if we can identify that there's a clash, I don't know how to handle it. Auto-rename seems as likely to cause harm as good (which one even gets to keep the original name?).

Maybe just print an error to the console, maybe flag the node with one of those warning signs?

It would also be an improvement if I could delete the duplicate node from the instanced scene, rather than having to perform `.tscn` surgery (though thankfully text-based resources at least make this reasonable).

**Comment by bojidar-bg** [comment] 2020-01-02 08:44
Duplicate of #28133. Something similar was fixed in 200c6cf630aa56b98310b3e747439795f8abbab8.

**Closed by bojidar-bg** 2020-01-02 08:44 UTC
Labels: bug, topic:editor
