### ISSUE TITLE
Property manager types right to left

### ISSUE THREAD

**Issue by BastiaanOlij** [godotengine/godot#21106] opened 2018-08-17 08:58 UTC
**Godot version:**
Master commit 68676c774d4f3b7bfad8866a08546acf5a594cdf

**OS/device including version:**
Windows

**Issue description:**
Typing in the name of a checkbox in the property inspector, I'm trying right to left:
![image](https://user-images.githubusercontent.com/1945449/44257440-5bbc8e00-a24f-11e8-9342-d147f48382f9.png)
(seems to be the same with other controls to)

**Steps to reproduce:**
Add a node to a scene, start typing in the text property or name property

**Comment by akien-mga** [comment] 2018-08-17 09:00
Duplicate of #21061.

**Closed by akien-mga** 2018-08-17 09:00 UTC
