### ISSUE TITLE
WASAPI endless error messages.

### ISSUE THREAD

**Issue by avencherus** [godotengine/godot#26841] opened 2019-03-09 16:13 UTC
**Godot version:**

60d910b

**OS/device including version:**

Win10 64-bit

**Issue description:**

While testing out plugging and re-plugging controls for these issues:  https://github.com/godotengine/godot/issues/26836 and https://github.com/godotengine/godot/issues/17566, I encountered an endless stream of WASAPI errors.

Unclear if it could possibly be related, or was caused by something else coincidentally.

The game running via editor (tools 64bit debug build) suddenly started giving these error messages.  Not sure yet how to reproduce.

![ezgif-2-545404a6cc7a](https://user-images.githubusercontent.com/13004169/54073966-c38f0080-4295-11e9-9d73-6fe919c234ae.gif)

A sample of those messages:

> 
> ERROR: WASAPI: Initialize failed with error 0ExfRRffOfffR: ff800WASAPI:70001
> lize faile d with e  Arrort:  0xffffffff80070001
> drivers\wasapi\audio_driver_wasapi.cpp:300
>    At: drivers\wasapi\audio_driver_wasapi.cpp:300
> ERROR: AudEiRRoDriverWASAPI::thread_func: OR: AudioDriverWASAPI::thread_func: WASAPI: GetCurrentPadding erroWASAPI: GetCurrentPadding error
> r
>    At:    At: drivers\wasapi\audio_driver_wasapi.cpp:646
> drivers\wasapi\audio_driver_wasapi.cpp:646
> ERROR: AudioDriverWASAPI::thread_func: ERROR: AudioDriverWASAPI::thread_func: WASAPI: GetCurrentPadding error
> WASAPI: GetCu rrentPaddi  At: ng errodrr
> iver s \ wAasta:p i\auddriiov_edrrs\wasapi\audio_driveiver_wasapi.cpp:646
> r_wasapi.cpp:646
> ERROR: AudioDriverWASAPI::thread_func: WASAPI: GetCurrentPadding error
> ERROR: Audio   At: DriverWASAPI::dtrhirveears\wasapdi\audio_drive_r_wasafunc: pi.cpp:646
> WASAPI: GetCurrentPadding error
>    At: ERRdOrR: AuidivoeDrrs\wasiveraWpAi\audio_dSAPrIi:v:ethrr_wasapi.cpp:6ead46
> _func: WASAPI: GetCurrentPadding error
>  E R RAOt:R : AudioDrivedrWASAPI::thrrievaedr_func:s \wasaWpi\audio_driver_wasapi.cpp:64A6
> SAPI: GetCurrentPadding error
>  ERROR: AudioD  At: riverWASAPdriverI::thread_func:s\wasapi\ audio_driWASAPI: GetCver_wasapi.urrentPadding error
> cpp:646
>    At: drivers\wasapi\audio_driver_wasapi.cpp:646
> ERROR: AudioDriverWASAPI::thread_func: ERROR: AudioDriverWASAPI::thread_func: WASAPI: GetCurrentPadding error
> WAS   At: API: GdrivetCurrentPadding error
> ers\wasap   At: i\adriverus\wdio_driasverapi\a_wasapudio_di.cpripver_wasapi.cpp:646
> :646
> ERROR: AudioDriverWASAPI::thread_func: WASAPI: GetCurrentPadding error
>  E R RAOtR::  AudidorDirvievresr\WwAaSsAaPpIi:\:atuhredad_fuinoc: _driver_wasapi.cpp:646
> WASAPI: GetCurrentPadding error
>    At: drivers\wasapi\audio_driverERROR: A_uwdasapi.ioDricveprWp:646
> ASAPI::thread_func: WASAPI: GetCurrentPadding errorERROR: AudioDrive
> rWA   At: SAPI::thread_func: drivers\wasapi\audio_driver_wasapi.cppWASAPI: GetCu:r6r4e6n
> tPadding error
>    At: drivers\wasapi\audio_driERROR: vAudioDriverWASAPI::ther_wasapi.cpp:re6a4d6_f
> unc: WASAPI: GetCurrentPadding error
> E   At: RROR: AudiodDrriivveerrsW\AwSasapi\audio_driver_wasapi.cpp:646
> API::thread_func: ERROR: AudioDriverWASAPI::thread_func: WASAPI: GetCurrentPadding error
> WASAPI: Ge tCu r Arte:n tPadddriinvge resrro\r
> wasa   pi\audio_driver_wasapi.cpp:646
> At: drivers\wasapi\audio_driver_wasapi.cpp:646
> ERROR: AudioDriverWASAPI::thread_func: WASAPI: GetCurrentPadding error
> ERRO R :  AAtu:d ioDrdriveirs\wasapi\audio_vedrriver_wasWapi.cpp:646
> ASAPI::thread_func: WASAPI: GetCurrentPadding error
>   ERR OAR:t AudioDriverWASAPI: ::thrdriveead_furs\nc: wasapi\aWASudiAPIo_: GedrivtCurrenter_Paddiwasapng erroi.rc
> pp: 6 4 6A
> t: drivers\wasapi\audio_driver_wasapi.cpp:646
> ERROR: AudioDErRiRvOR:er WAAuSdAiPoI:D:rtihverWreaASAPd_If:u:ntch:r ead_WfAuSnAcP:I : GetWCAurSrAePnIt:P aGdedtiCnugr reernrtoPra
> ddin g   eArtr:o r
> dri v e rAst\:w asapdir\iavuedriso\_wdarsiavpei\audio_rdriver_wasap_wasi.acpp:pi.6c4pp:6466
> 
> ERERRORR:O RA:u dAiuodDiriovDerriWvAerSWAAPSIA:P:It:h:rtehareadd_f_funcun: c: WASAPWASI: GetCuAPIrren: tPadding eGetCurrrror
> entPadding error
>    At   : At: dridvreirvse\rs\wasapi\awudasiapi\o_driver_wasapi.cpp:646
> audio_driver_wasapi.cpp:646
> ERROR: AudioDriverWASAPI::thread_func: WASAPI: GetCurrentPadding error
> E R R OARt::  AudidorDirvieverWrASs\APwaI::sthapread_func:i\au dio_drWAiver_wasapi.cpp:S64API:6
>  GetCurrentPadding error
>  ERROR  A: At: udioDridverWArivSAPers\I::wathsapi\audio_rderaid_func: ver_wWASAPI: GetCurreasapi.cpp:ntPad646
> ding error
> ERROR: AudioDriverWASAPI::thread_func:    At: WASAPI: GetCurrentPadding error
> driv e  At: rs\wdrivearssa\wapsiapi\\aauuddio_idrivoe_drrive_rw_awsapi.capsapp:i.6cpp:64466
> 
> EERRRROR: AuOR:di AuodioDriverWDriASAPI::tverWhreadAS_fuAPnc: I::threWAadSAPI:_func: GetCurrentPadding  error
> WASAPI: GetCurrentPa  d At: ding drivers\wasapi\audio_driver_wasapi.cpp:646
> error
>    At: ERRdORr:iver Audios\waDrisaverWpi\ASAPI::thread_func: audio_dWASAPI: GetCurrerntPadding ievrreor
> r_was   At: apidrivers.cpp:646
> \wasapi\audio_driver_wasapi.cpp:646
> ERROR: AudioDriverWASAPERIR:O:Rt:h rAeuadido_Dfruinvce:r WASWAPAIS::AtPhIr:e aGetCd_func: urrentWPAaSdAPdIi:n gG eetrCruorr
> rentPadding error
>      At :A t: drivers\wdraisapvie\audior_dsr\iver_waswasapapi\audio_driver_wais.apci.cpppp::6646
> 46
> ERROR: AudioDriverWASAPI::thread_func: WASAERRORPI: A: GetCurrentPaudddiing erroro
> Drive   At: rWASAPI::thread_fundrivers\wasc: api\aWudio_driver_AwasSapAPIi: .cpp:Get6C46u
> rrentPadding error
>    At: ERRdOrRi: verAsud\ioDrivwearsWaApi\auSdio_AdPI::thrreiavedr__wasfauncp: i.cpp:6WASA4PI6:
>  GetCurrentPadding error
>    At:ER ROR: dAurdiioDrviveerrWs\wasAapiSA\aPudiIo:_dri:vtehrr_wasapi.cpp:646
> ead_func: WASAPI: GetCurrentPadding error
>    At: ERROR:d rAiudiovDriverWASAerPI::thrs\wead_func: asapi\WaudioA_SdArPiI: GetvCeurr_rweanstaPpaid.cdipnpg: 6e4r6r
> or
>    At: drivers\wasapi\audio_driver_wasapi.cpp:646
> ERROR: AudioDriverWASAPI::thread_func: WASAPI: GetCurrentPadEdRROR:ing error
>  Aud i oDri At: verWAdSrAiPvIe:r:tsh\rweaasda_pfiu\anc:u dio_dWrAiSvAePr_wasapi.cpp:646
> I: GetCurrentPadding error
>    AEtR:R OR: AdruidvieoDrrives\wrasWapiA\SaAuPdIio_driver_wasapi.cpp:646
> ::thread_func: WASAPI: GetCurrentPadding error
>    At: ERROR: AudioDdrirvivers\weasrapWi\AaSudio_driAvPeIr:_:thwreadas_func: api.cpp:64W6
> ASAPI: GetCurrentPadding error
>    AEtRR: OR: AudridveiroDrives\rwWasaApSi\auAdPiI::tho_rderaived_furn_cw:a sapi.WcApSpA:P6I4: Get6C
> urrentPadding error
>    At: drivers\EwRasaRpOiR:\a udAiuo_dioDrivedrWriAveSAPI::thread_funcr_wa:s api.cpp:646W
> ASAPI: GetCurrentPadding error
>  ERROR  At: : AudioDdrriivevreWArs\SwAPasapIi::thr\audio_edariver_d_fuwasapinc: .cpp:646
> WASAPI: GetCurrentPadding error
>   ER At: ROR:d rAiuvdeioDrrsi\vewrWaAsSAaPpIi:\:atudhread_func: io_driver_waWASAPI: Gsapi.cpp:64e6t
> CurrentPadding error
>    EARtROR:: A udioDdrrivievrersW\ASAPI::thwraesad_fuanpic:\ audio_drWiASAPI: Gveetr_wCausrrapein.ctpPaddinp:646
> g error
> ERRO  R : AudioDriverWASAPI::thread_func: At: WASAPdIrivers\was:a pGeit\Cauudriroe_ndtriPvaedr_wdiansga eprir.ocr
> pp:646

**Comment by avencherus** [comment] 2019-03-09 16:19
Seems to have straightened its formatting out some over time, and is being generated from within the Editor.  It now loops with this message:

> ERROR: AudioDriverWASAPI::thread_func: WASAPI: GetCurrentPadding error
>    At: drivers\wasapi\audio_driver_wasapi.cpp:646
> 

Got this while launching:

> ERROR:OpenGL E AudioDriveS rWA3.0 ReSAPInd::threerader_f: uncG: eForWcAeSA P9I600 : GeGT/PtCCIurrene/tPaSdSE2di
> ng error

**Comment by akien-mga** [comment] 2019-03-09 17:14
I don't know was causes this, but regarding the mangled error messages, it seems similar to the old #6252 (fixed by #7558).

**Comment by marcelofg55** [comment] 2019-03-09 18:12
Are you running some other app like Netflix or something that is requesting exclusive mode on the audio device?

**Comment by avencherus** [comment] 2019-03-09 20:00
@marcelofg55 Was all text editors, folders, and Godot at that time.  Don't recall if I had a browser open from a reference search.  Would another instance of the Godot editor be included?

**Comment by marcelofg55** [comment] 2019-03-10 01:45
> @marcelofg55 Was all text editors, folders, and Godot at that time. Don't recall if I had a browser open from a reference search. Would another instance of the Godot editor be included?

No, Godot uses WASAPI in Shared mode so it is safe to have multiple instances of Godot using WASAPI.
Has it occurred many times or just once? Is the error log you pasted the start of the errors?

**Comment by avencherus** [comment] 2019-03-10 07:02
@marcelofg55 Once so far, but only began doing this specific kind of testing last night, and had only a little time to work on it.  The errors I cut from the top and down a little ways.

I'll let you know if it continues when I resume work there tonight.

**Comment by avencherus** [comment] 2019-03-20 09:17
Haven't encountered this in the last several days of use.  Very well may of been something in the background as suggested.

**Comment by akien-mga** [comment] 2019-04-03 08:05
Closing for now. Please comment if you can reproduce it and identify what causes the conflict.

**Closed by akien-mga** 2019-04-03 08:05 UTC
Labels: bug, platform:windows, topic:audio

**Comment by jitspoe** [comment] 2019-07-31 09:13
Looks like a duplicate or at least similar to https://github.com/godotengine/godot/issues/18732 (linking to a live issue for people who ended up on this one first, like I did).

**Comment by aurorum999** [comment] 2020-06-30 18:48
i also experienced the endless wasapi related error in 3.2.2. when i tried to reply to this forum and signup i had to do an audio prompt. i noticed then that my audio wasn't playing and bingo, turns out i opened task manager and seen windows audio endpoint builder was using a lot of constant resources on cpu. i clicked on the audio icon on taskbar to change devices and it was resetting and blinking constantly. i stopped windows audio services, uninstalled my third party audio drivers (realtek), restarted the computer and enabled the services and ran godot 3.2.2 (not admin) and no errors. it leads me to believe this is not an error of godot, but an affect of windows audio endpoint builder in relation to drivers (windows likes it's own drivers i guess). 

mobo is ax370-gaming k7 and related audio drivers. i was using a newer version of the realtek drivers from gigabytes site rather than those on the driver cd that came with the mobo (never had audio problems from the cd provided drivers), but then again im using a newer version of win10 x64 than usual too.

**Comment by jitspoe** [comment] 2020-07-01 05:25
The error I get repros 100% for me if I open Sony Vegas (now Magix Vegas) or SoundForge.  I think they try to take exclusive access to the sound card.  Most other applications well have a sound hitch and resume, but godot get stuck in an infinite loop of errors.  Probably needs to release and reacquire the device when this happens or something of that nature.  Can eat up a lot of CPU if you're not paying attention and have godot open in the background while you work on other stuff.

**Comment by Jimmio92** [comment] 2021-02-08 16:13
Can wholly confirm this still happens, but I have always had audio driver issues with this motherboard (ASUS Prime X570 Pro; namely every time the microphone is used it resets the gain). I second the release and reacquire that jitspoe suggested.

**Comment by jitspoe** [comment] 2021-02-09 13:39
What's interesting is this does not happen on my new computer with a different sound card.  (Sadly, I couldn't bring my nice sound card over because I wasn't paying attention and didn't realize the new motherboard had no PCI-E slot).

**Comment by dcarrawa** [comment] 2021-04-08 06:06
I get something similar when using my laptop's built in audio array -- an endless spew of

ERROR: AudioDriverWASAPI::thread_func: WASAPI: unsupported channel count in microphone!
   At: drivers\wasapi\audio_driver_wasapi.cpp:714

Looks like the audio array is 4 channels which Godot doesn't seem to like.

**Comment by kidskunai** [comment] 2021-07-09 07:22
Yeah I have also still it seems had this issue, I have had no previous issues at all, worked on maybe 4 projects on my brand new build, cards are all new, good low usage, but still, out of nowhere, Godoy just spewed that at me, and never ever again, and this was after launching the application, with no other apps open, no other audio source, I closed it down and re opened the editor after a fresh restart of the pc, never had it again, then had it happen 4 times over, but totally random instances, nothing taxing outside the program, nothing sharing any audio output or input, no apps, then again, after a close of the application and a re open, this time no restart of the pc, no issue, no issue since. I have no idea what the hell the deal is with it, when I run the editor and or project my audio is fine, my everything works great, it just would spew that code at me and ten I save and shut it down, re open, all good. I would love to know if this is a personal issue with a pc to Godoy relationship or is this a editor bug? Seems like a non problematic bug for me at least but still kinda sad that it wouldn’t have been patched by 3.3.2, since this thread alone is a open case from 2019 but I digress I know it’s gotta be hard to do what they do for us in this editor, and I am just a simpleton. But I now after typing this realize that this all happened for me after the 3.3.2 update so may that’s what did it for me who knows, drivers are all good so idk man hahahahaha

**Comment by MetsalIlnris** [comment] 2023-12-10 12:44
我今天也遇到了这个问题，关掉占用电脑音频输出的软件就解决了。
I meet this bug today and fortunately I solve it by simply turn off the DAW software. That's because the DAW take over the computer audio channel.

**Comment by stef663k** [comment] 2023-12-13 14:12
Saw the bug today too
![godot42](https://github.com/godotengine/godot/assets/100563394/aebd4ebb-55a2-4076-b5a0-8c156e46d00d)

**Comment by chrisheld2** [comment] 2024-03-08 14:52
Just started seeing it too:

v4.2.1.stable.mono.official [b09f793f5]

**Comment by finepointcgi** [comment] 2024-03-16 00:10
I also have ran into this with v4.2 Mono
![image](https://github.com/godotengine/godot/assets/12012300/ddb75124-887b-49e1-ac8e-95527084fff8)

**Comment by TattlingJam4231** [comment] 2024-03-19 23:01
![image](https://github.com/godotengine/godot/assets/41134508/70361187-dc95-47ec-b044-d5951eb60415)
I get this error spam with voicemeeter running. I use to be able to run voicemeeter without this issue, not sure exactly when it started.

**Comment by expilu** [comment] 2024-04-06 14:36
I use Voicemeter software in my computer and seeing the same error stream while voicemeter is running.

**Comment by finepointcgi** [comment] 2024-04-06 15:08
I've also noticed that if I have Godot running and something uses the audio
driver eg playing Rocksmith or just unplugging my audio interface/resetting
the driver this error starts appearing.

**Comment by PythonCircuit** [comment] 2024-04-11 14:35
Experiencing this error in v4.2.1 stable

**Comment by Cryfi** [comment] 2024-04-16 06:59
> I also have ran into this with v4.2 Mono ![image](https://private-user-images.githubusercontent.com/12012300/313358910-ddb75124-887b-49e1-ac8e-95527084fff8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMyNTAyNDUsIm5iZiI6MTcxMzI0OTk0NSwicGF0aCI6Ii8xMjAxMjMwMC8zMTMzNTg5MTAtZGRiNzUxMjQtODg3Yi00OWUxLWFjOGUtOTU1MjcwODRmZmY4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE2VDA2NDU0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZjNmFhNWYwZWQ2ZTI1OGYxZmE1YzNkM2M5OWI3NjdlYWQwYjNiMTUxNjlkMTA4NDBkZmRhNzQ2NGYwY2YzODkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PCF1oRgz4EnaIJisB5o68IxmV7X_o2LvB8NkObudTys) It only happens once I hit play while talking into the microphone.

A few days ago I had the same problems with some audio software.  What I found out so far is that the audio software I was using grabbed the "exclusive" audio rights and the error appeared. 

I did some more tests and the result was the same, in my case I was able to remove  the "exclusive" rights, from the audio software. 
After restarting Godot and the audio software everything was fine. 

Perhaps the issues are related. If the microphone gets some kind of exclusive rights and takes them away from Godot and iff Godot needs this kind exclusive acces to the audio driver the error will occure.

the error points to line: drivers/wasapi/audio_driver_wasapi.cpp:808 

It's just an idea and my humble opinion. 
Cheers

**Comment by jitspoe** [comment] 2024-04-16 10:07
Yeah, this happens when software grabs exclusive access to the sound driver.  See this issue: https://github.com/godotengine/godot/issues/18732

Any further discussion should probably be put there unless you've managed to get this without something grabbing exclusive access.
