### ISSUE TITLE
Very bad FPS stability.

### ISSUE THREAD

**Issue by simpleyo** [godotengine/godot#27211] opened 2019-03-18 17:21 UTC
Godot version:
Godot_v3.1-rc3_win64
Godot_v3.1-stable_win64

OS/device including version:
Windows 7 Ultimate x64
Ryzen 7 1700.
Radeon RX 550 with newest drivers.
Benq 2460HM connected with HDMI cable.

Issue description:
Running a simple project (like TestFPS) in the editor (or exported for windows desktop debug or release), the fps fluctuate persistently between 50 and 60. This makes the sprite (which moves one pixel horizontally per frame) not move smoothly. If the window is minimized the fps reach the value of 125 and remain fixed there. If the window is completely covered, but not minimized, the fps reach the value of 60 and remain fixed there.

Minimal reproduction project:
[TestFPS.zip](https://github.com/godotengine/godot/files/2979357/TestFPS.zip)

![test](https://user-images.githubusercontent.com/29863675/54557169-ce931080-49ba-11e9-8567-286283c7486a.jpg)

**Comment by qarmin** [comment] 2019-03-18 17:47
I have almost always stable 60 fps on Linux Mint 19 HD 3000

Can you try to update Godot version to stable and if it is any difference?
Which graphics card do you have? Try to install the newest possible graphics driver.

**Comment by simpleyo** [comment] 2019-03-18 17:57
I have tried with Godot_v3.1-rc3_win64 and the same thing happens.
I have a Radeon RX 550 with newest drivers.

**Comment by girng** [comment] 2019-03-18 18:38
gtx 950, windows 10 here. stable 144 fps, can't reproduce

**Comment by rogeriodec** [comment] 2019-03-18 18:45
I've tried with 3.1 official in a Windows 10 x64 / NVIDIA GeForce GTX 1060 6GB, I got 60 fps almost all the time.
But the visual is not completely smooth.

**Comment by simpleyo** [comment] 2019-03-18 18:46
> 
> 
> gtx 950, windows 10 here. stable 144 fps, can't reproduce
> 
> what is your CPU?

Ryzen 7 1700.

**Comment by girng** [comment] 2019-03-18 18:54
try `speed * delta`

**Comment by simpleyo** [comment] 2019-03-18 19:03
> 
> 
> try `speed * delta` (for smoothness)

**The problem is the instability of the FPS.** Trying to put solution to the lack of smoothness of the sprite does not solve the instability of the fps.

It is not reasonable that with such a simple project the fps fluctuate so much.

**Comment by Calinou** [comment] 2019-03-18 20:25
See [Fixing jitter and stutter](https://docs.godotengine.org/en/latest/tutorials/misc/jitter_stutter.html) in the documentation. This is expected on Windows if the project runs in a window, but should be much less apparent when running the project in fullscreen.

**Comment by simpleyo** [comment] 2019-03-18 22:56
I have been testing and FPS instability do not happens using GLES2 renderer (with Radeon RX550).
I have also tried to change the graphic card (HD5770) and FPS instability do not happens.

**Comment by simpleyo** [comment] 2019-03-18 23:12
> 
> 
> See [Fixing jitter and stutter](https://docs.godotengine.org/en/latest/tutorials/misc/jitter_stutter.html) in the documentation. This is expected on Windows if the project runs in a window, but should be much less apparent when running the project in fullscreen.

I do not agree with that. It is not reasonable that, with such a simple project, fps fluctuate so much. What information do you rely on to be able to say that it is expected on Windows if the project runs in a window?

**Comment by girng** [comment] 2019-03-18 23:20
> I have been testing and FPS instability do not happens using GLES2 renderer (with Radeon RX550).
I have also tried to change the graphic card (HD5770) and FPS instability do not happens (using GLES3 or GLES2). The trinity GLES3, RX550, godot is what seems to be failing somewhere.

imo, most likely  an edge case with those specific drivers, for that card..

**Comment by Akira1San** [comment] 2019-03-19 00:53
Tested it, got 75 stable in window and fullscreen. But if i change the settings to: render - threads to Multi-Threaded and i see jumpings and the fps is not stable..

**Comment by Zireael07** [comment] 2019-03-19 08:02
@simpleyo are you using multi-threaded?

**Comment by simpleyo** [comment] 2019-03-19 09:32
No

> 
> 
> @simpleyo are you using multi-threaded?

No.

**Comment by simpleyo** [comment] 2019-03-19 11:37
I have done a test to check if it is Godot that is causing the fluctuations of the fps. What I have done has been to modify the sample Hello_Triangle.c available at https://github.com/danginsburg/opengles3-book to move the triangle in each frame. The result is that the triangle moves smoothly and the fps are always at 60.

**Comment by Zylann** [comment] 2019-03-19 13:56
What happens if you add the following scene as child of your root?

[emitter.zip](https://github.com/godotengine/godot/files/2983682/emitter.zip)

Also, did you try with Godot 3.1 stable?

**Comment by simpleyo** [comment] 2019-03-19 14:06
> 
> 
> Wild guess: what happens if you add the following scene as child of your root? (nevermind what it does, check your fps)
> [emitter.zip](https://github.com/godotengine/godot/files/2983692/emitter.zip)
> 
> Also, did you try with Godot 3.1 stable?

I just tried it (with Godot_v3.1-rc3_win64 and Godot_v3.1-stable_win64.exe) and the fluctuations are still there.

**Comment by simpleyo** [comment] 2019-03-19 16:58
I tried it in Linux (Ubuntu 18.04.1) and there is no FPS instability (GLES2 and GLES3). Using the Zylann project, particles are not showing when using GLES2.

**Comment by Zylann** [comment] 2019-03-19 18:27
@simpleyo I was trying to see if you were affected by driver shenanigans such as those I found in a similar existing issue. It's ok if those particles don't show in GLES2 because they are GPU ones, GLES2 doesn't implement them.

**Comment by simpleyo** [comment] 2019-03-19 19:01
> There are various open issues about FPS instability and reactivity that are due to OS-specific graphics 
> drivers themselves, or compositing performed by the windowing system, so it's problems that pops up 
> often to almost never be resolved...
> 
> I assume turning v-sync off makes the fluctuation go away?

Yes, the problem appears when v-sync on.

**Comment by simpleyo** [comment] 2019-03-19 21:29
I've tried it with Windows 10 and there's no instability of the fps. The problem happens with Windows 7, RX550 and GLES3.

**Comment by Megalomaniak** [comment] 2019-03-20 14:40
Have you made sure that Radeon chill and any other variable frame rate controlling settings in AMD's Radeon Settings are off?

**Comment by simpleyo** [comment] 2019-03-20 21:34
> 
> 
> Have you made sure that Radeon chill and any other variable frame rate controlling settings in AMD's Radeon Settings are off? Note that you should be able to add the game engine and runtime as specific applications to control each individually. Downside is you would likely have to create a new profile for each exported game.

I was trying several combinations and the result was always the same.

**Comment by Megalomaniak** [comment] 2019-03-25 17:12
Couldn't replicate on Ryzen 5 1600 and RX 470. Using Radeon's adrenalin-2019-edition-19.2.3-feb25 driver.

**Comment by girng** [comment] 2019-03-25 17:40
@Megalomaniak OS, Windows 10 I assume?

**Comment by Megalomaniak** [comment] 2019-03-25 17:58
I'm also running windows 7.

**Comment by girng** [comment] 2019-03-25 18:19
@Megalomaniak Oh really? Hmm...

**Comment by Megalomaniak** [comment] 2019-03-29 14:15
Maybe a monitor difference?

**Comment by TerminalJack** [comment] 2019-10-26 17:31
This might be the same problem discussed over in [this](https://github.com/godotengine/godot/issues/19783) thread.  See [this](https://github.com/godotengine/godot/issues/19783#issuecomment-546616081) comment for a possible solution.

I tried your project with both the latest alpha build (3.2 alpha2) and with a test build that has a fix for syncing via the Windows compositor and I could see an improvement with the test build.  The project running under the alpha build would jitter slightly and the frame rate could be disturbed simply by moving the mouse around.  The frame rate with the test build was very stable.

**Comment by Calinou** [comment] 2019-11-30 18:56
I'll close this issue as it appears to be a duplicate of #19783. Please test the builds containing @TerminalJack's pull request: https://github.com/godotengine/godot/pull/33414

**Closed by Calinou** 2019-11-30 18:56 UTC
Labels: discussion, topic:rendering
