### ISSUE TITLE
Replace Tween interpolaters by properly maintained library of easing equations

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot#22513] opened 2018-09-28 14:19 UTC
**Godot version:**
Master branch (82f2674e)

**OS/device including version:**
Any.

**Issue description:**
The `Tween` implementation initially contributed in #628 came with a stealth copy of https://github.com/jesusgollonet/ofpennereasing in the file `scene/animation/tween_interpolaters.cpp`, since renamed to `thirdparty/misc/easing_equations.cpp` for clarity.

It's heavily modified to use Godot types like `real_t` and hook into the `Tween` API, and eventually passed through our `clang-format` before we knew that it was thirdparty code, so it's now difficult to sync with upstream. "Luckily", upstream is inactive and there are bad unresolved issues in that code which range from unreadable code to [undefined behaviour](https://github.com/jesusgollonet/ofpennereasing/issues/1).

To anyone interested, I would suggest to:
- Either find a replacement library that implements similar functionality in a cleaner way. The library should be small (ideally one header) and have good code quality. It could be another, better maintained implementation of Penner's equations.
- Or refactor the current file to fix the various issues in it (which are not simply a matter of renaming variables like in #21608, there's actual bad code in there beyond the name of its variables). If so we can maybe move it back to `scene/animation/`, but at any case I'd like the `Tween` glue in this file to be moved back to `tween.cpp`, and the `easing_equations.cpp` turned into a header.

References:
- Original code by Robert Penner, and implementations in various languages: http://robertpenner.com/easing/
- C++ implementation we used so far: https://github.com/jesusgollonet/ofpennereasing
- Better take on Penner's equations not using ugly stuff like `t /= d` in the middle of an assignment

**Comment by spongeboburu** [comment] 2018-09-30 04:57
Hi! :)

Since we were talking about it the other day, my suggestion would be to just write our own class and integrate it like a core type of Godot.

All of Penner's functions are well described (here for instance http://www.gizma.com/easing/), so it shouldn't be more than a quick copy paste with a few improvements.

Since interpolation is both generic and common providing Penner's functions along with a few other useful ones (such as bezier) should be enough for all scenarios, if not we can provide a "custom" function (as is done already).

The interpolation type could replace the code in both Tween and Curve, have it's own editor plugin and be available in the script languages. Maybe it also contain the "fire and forget", possibly integrating it into Timer.

**Comment by KoBeWi** [comment] 2021-07-03 23:12
I thought about giving a shot at finally closing this issue, but I have some questions.

The bugged behavior is mostly caused by in-equation assignments. This should be very easy to fix by doing general refactoring to make the code clean™, but is it enough to resolve the issue? I mean, does refactored third-party code count as original code or does it need to be rewritten completely? (I don't know how it could be, if we are implementing the same equations)

Another thing is the code organisation. It uses namespaces with static methods and then stores method pointers in array. It's extremely performant, but if we were to move it out of thirdparty, can this be preserved? We don't use namespaces anywhere (I think) and the whole structure doesn't look like typical Godot code. IMO it's not wrong, but I'm just not sure if it has right to exist outside third-party xd It could be changed, maybe even in a way that allows for easy custom interpolaters, but then it might be less performant.

**Closed** 2021-09-24 12:28 UTC
Labels: enhancement, topic:core, topic:thirdparty
