### ISSUE TITLE
Selected tile name accepts keystrokes in reverse in inpsector

### ISSUE THREAD

**Issue by pchasco** [godotengine/godot#44880] opened 2021-01-02 19:04 UTC
**Godot version:**
3.2

**OS/device including version:**
Windows 10

**Issue description:**
Tileset editor selected tile name reverses keystroke input. Copy/paste into editor does not reverse what is copied in.

**Steps to reproduce:**
1. Create a new tileset
2. Add an image to the tileset
3. Select image
4. Click New Single Tile
5. Click the image to create a tile region
6. In the inspector, focus the Selected Tile \ Name box
7. Type something

![image](https://user-images.githubusercontent.com/2642944/103464619-d68c8380-4cfa-11eb-83d8-78a87216e0ae.png)

**Minimal reproduction project:**

**Comment by KoBeWi** [comment] 2021-01-02 22:08
Duplicate of #44854

**Closed by KoBeWi** 2021-01-02 22:08 UTC
