### ISSUE TITLE
Visual scripts editor cannot be zoomed using CTRL+mouse wheel combo

### ISSUE THREAD

**Issue by Chaosus** [godotengine/godot#12076] opened 2017-10-13 15:59 UTC
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
all

**Issue description:**
Please make CTRL+mouse wheel combo possible in Visual Scripts editor.. I looked through code myself but didnt find where I can change it and PR..

**Comment by noxarivis** [comment] 2017-10-13 16:07
1+
would be awesome

**Comment by Noshyaar** [comment] 2017-10-13 16:13
Actually, this is not yet implemented to GraphEdit node, not related to VisualScript. (VisualScript uses GraphEdit for its interface.)

https://github.com/godotengine/godot/blob/master/scene/gui/graph_edit.cpp

**Comment by Chaosus** [comment] 2017-10-13 16:14
Ah, and Im looked to editor folder... :)

**Comment by Noshyaar** [comment] 2017-10-13 16:18
Btw, VisualScript stuff is in modules/visual_script folder as it is an editor's module.

**Comment by vnen** [comment] 2017-10-13 17:25
Almost the same as #6168

**Comment by Noshyaar** [comment] 2017-10-13 17:27
Then it's disabled on purpose: #6317

**Comment by Noshyaar** [comment] 2017-10-13 17:31
Closing as duplicate of #6168

**Closed by Noshyaar** 2017-10-13 17:31 UTC
Labels: enhancement, topic:core, usability
