### ISSUE TITLE
Save & Restart off the Editor from themes section doesn't ask to save the empty scene.

### ISSUE THREAD

**Issue by swarnimarun** [godotengine/godot#22696] opened 2018-10-03 20:19 UTC
**Godot version:**
Godot 3.1 build caa141a1ac630144e441f89689baa1a74bb3bae5

**OS/device including version:**
Manjaro 64 bit

**Issue description:**
Save & Restart off the Editor from themes section doesn't ask to save the empty scene.
![image](https://user-images.githubusercontent.com/19930870/46436868-9b93f200-c777-11e8-9656-3d61f009fbf0.png)

**Steps to reproduce:**
- Create a empty scene and add somethings don't save it yet.
- Goto the Editor themes and change something and save & restart.

**Comment by Calinou** [comment] 2022-08-31 15:22
Duplicate of https://github.com/godotengine/godot/issues/43302. The original issue is still present – any project/editor settings that require an editor restart can result in losing unsaved changes if you're not careful.

**Closed by Calinou** 2022-08-31 15:22 UTC
Labels: enhancement, topic:editor, usability
