### ISSUE TITLE
ItemList.set_icon_scale() is making all icons the same size, prior to scaling them

### ISSUE THREAD

**Issue by blurymind** [godotengine/godot#7925] opened 2017-03-02 17:45 UTC
Consider that you have created item list with items with different size icons. You want to resize them all - relative to their original size.

Expected behavior- They get scaled relative to their actual size when item was added - their original size

Current behavior:
**ItemList.set_icon_scale()** is making all icons the same size, but it should be making each relative to it's original size when item was added? It should NOT be fixing their size to the same value prior to scaling them.

**Comment by akien-mga** [comment] 2017-03-02 17:59
No need to put if it's a bug or a feature in the title, we use labels for that.

**Comment by blurymind** [comment] 2017-03-03 01:34
@akien-mga  sorry about this. An old habit :) 
I will avoid doing it again. Thank you for adding the appropriate labels!

**Comment by Hinsbart** [comment] 2017-03-03 05:59
I think this was how that function originally worked, but it didn't look nice with the Tileset palette of `TileMapEditorPlugin`...
Maybe we could let the user choose via a flag (or another method), which "scaling mode" he wants to use?

**Comment by blurymind** [comment] 2017-03-03 11:38
@Hinsbart if we have it as a flag - it would be great to be able to toggle it on and off during runtime :D 
I will appreciate getting this functionality back for the sake of flexibility

**Comment by kubecz3k** [comment] 2018-04-10 17:17
First of all thank you for your report and sorry for the delay.

We released Godot 3.0 in January 2018 after 18 months of work, fixing many old issues either directly, or by obsoleting/replacing the features they were referring to.

We still have hundreds of issues whose relevance/reproducibility needs to be checked against the [current stable version](https://godotengine.org/download), and that's where you can help us.
**Could you check if the issue that you described initially is still relevant/reproducible in Godot 3.0 or any newer version, and comment about its current status here?**

For bug reports, please also make sure that the issue contains detailed steps to reproduce the bug and, if possible, a zipped project that can be used to reproduce it right away. This greatly speeds up debugging and bugfixing tasks for our contributors.

Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

Thanks in advance.

*Note: This message is being copy-pasted to many "stale" issues (90+ days without activity). It might happen that it is not meaningful for this specific issue or appears oblivious of the issue's context, if so please comment to notify the Bugsquad about it.*

**Comment by akien-mga** [comment] 2019-04-15 14:24
> Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

As there was no update since the previous post, we close this issue.

If it is still relevant in the way it was described and discussed above, please comment to ask for it to be reevaluated. If it is only partly relevant, or if the original issue has changed, it would be better to open a new issue (potentially referring to this one) focused on the current state.

**Closed by akien-mga** 2019-04-15 14:24 UTC
Labels: bug, topic:core
