### ISSUE TITLE
Project list launches instead of the game/current scene

### ISSUE THREAD

**Issue by xR3alx** [godotengine/godot#25066] opened 2019-01-17 15:30 UTC
**Godot version:**
3.1 beta 1

**OS/device including version:**
Win 7 x64

**Issue description:**
When running the game/current scene the project list opens instead of the expected scene/game.
EDIT: In my converted project from 3.0 after having this issue once it won't go away for a while

**Steps to reproduce:**
1. Create a new project or use an existing
2. Have a shader saved as .shader file
3. Change from 2D view to script with any script open
4. Double click the .shader file to open the editor
5. Click inside the shader editor
6. Run the game

This does sometimes work and sometimes it doesn't. Just try it several times.

**Minimal reproduction project:**
Happens with a newly created project.

**Comment by creikey** [comment] 2019-01-18 05:44
I was unable to reproduce your issue given a slightly modified steps list. I
1. Created a new project, named it `Project List Launching`
2. Clicked "New Scene" and saved the default `Node2D` to `Node2D.tscn`
3. Created a new text file, named it `test.shader`
4. Clicked inside of the text edit window
5. Hit the run game button in the upper right
6. Selected `Node2D.tscn` as the default scene to run
And it successfully launched the game. A list that has a more in-depth description of a project with the issue or a zip file that contains it is needed for further development.

**Comment by QbieShay** [comment] 2019-01-18 06:43
I have observed this issue on windows for a while but it has been gone now. As far as I know it is a problem with Windows locking files. Are you able to run for bisect?

**Comment by xR3alx** [comment] 2019-01-18 15:59
> I was unable to reproduce your issue given a slightly modified steps list. I
> 
> 1. Created a new project, named it `Project List Launching`
> 2. Clicked "New Scene" and saved the default `Node2D` to `Node2D.tscn`
> 3. Created a new text file, named it `test.shader`
> 4. Clicked inside of the text edit window
> 5. Hit the run game button in the upper right
> 6. Selected `Node2D.tscn` as the default scene to run
>    And it successfully launched the game. A list that has a more in-depth description of a project with the issue or a zip file that contains it is needed for further development.

The problem is, even I cannot reproduce it 100% everytime but with my steps it is reproducible sometimes.
Try it several times and it may happen.

**Comment by triptych** [comment] 2019-01-18 17:14
I saw another bug similar to this where if you compile Godot on windows that version has issues where if you try to open a scene while the files are still being written to, it blocks write access and bails. Like a race condition.

**Comment by xR3alx** [comment] 2019-01-22 16:54
Happens everytime I work with a shader. Hadn't the problem for a few days and when I edited my shader again the problem is back.

**Comment by akien-mga** [comment] 2020-06-20 21:17
Duplicate of #28036.

**Closed by akien-mga** 2020-06-20 21:17 UTC
Labels: bug, topic:editor
