### ISSUE TITLE
Godot 3.2.2 breaks passing List<int> from C# to GDScript

### ISSUE THREAD

**Issue by timothyparez** [godotengine/godot#42292] opened 2020-09-24 03:49 UTC
**Godot version:**
 - 3.2.2
 - 3.2.3

**OS/device including version:**
Ubuntu 20.04.1 LTS

**Issue description:**
Trying to pass an instance of a class (which derives from Node) with a List<int> property
from GDScript to C#.

In Godot 3.2.1 this works perfectly. GDScript is able to iterate over the integers.
In Godot 3.2.2 The instance is passed to GDScript but the List<T> property is NULL
Also tested this in Godot 3.2.3

**Steps to reproduce:**

Imagine the following class:

```csharp
public class SomeData : Node
{
    public string Name {get; set;}
    public List<int> Ids {get; set;} = new List<int>();
}
```

Then create an instance of it and pass it to a GDScript:

```csharp
var instance = new SomeData() { Name = "Godot" };
instance.Ids.Add(10);
instance.Ids.Add(20);

subNode.Call("foo", instance);
```

The GDScript defines a function like this:

```gdscript
func foo(instance):	
	print(instance.Name)
	for id in instance.Ids:
		print(id)	
```

In 3.2.1 this will output:

```
Godot
10
20
```

In 3.2.2 `Godot` is printed and then it crashes because `Ids` is `null`

**Minimal reproduction project:**

[issue-sample.zip](https://github.com/godotengine/godot/files/5273292/issue-sample.zip)

The attached zip file contains a sample project with a branch for 3.2.1, 3.2.2 and 3.2.3.

**Comment by Calinou** [comment] 2020-09-24 03:56
cc @neikeq

**Comment by akien-mga** [comment] 2020-09-24 08:00
Duplicate of #40023 (same root cause).

**Closed by akien-mga** 2020-09-24 08:00 UTC
Labels: bug, regression, topic:mono
