### ISSUE TITLE
Screen 'resizes' when editing a tileset

### ISSUE THREAD

**Issue by libaniol** [godotengine/godot#35660] opened 2020-01-28 13:24 UTC
**Godot version:**
3.2rc4

**OS/device including version:**
Windows 10

**Issue description:**
When you cick to edit a tile in tileset editor the screen just resizes and the inspector is partialy hidden.

**Steps to reproduce:**

- Open a project in Godot 3.2 Release Candidate 4;
- Open a tileset resource in tileset editor;
- Select a tileset;
- Click in any tile in your tileset

**Result:**
![image](https://user-images.githubusercontent.com/56133700/73267612-2ba14a80-41b8-11ea-9024-40642627875c.png)

**More information:**
The bug is not a regression, I've seen this in 3.2rc3 too;
The issue can be seen only if you are not using the default layout, with a layout like mine it's likely to happen;
Sorry for my bad English.

**Comment by Calinou** [comment] 2020-01-28 16:04
Duplicate of #31133.

**Closed by Calinou** 2020-01-28 16:04 UTC
