### ISSUE TITLE
Area2D fires off "body entered" signal when scene is added back to scene tree

### ISSUE THREAD

**Issue by golddotasksquestions** [godotengine/godot#38293] opened 2020-04-28 12:57 UTC
**Godot version:** 3.2.1

**OS/device including version:** Win64

**Issue description:**
![area2d_remove_bug](https://user-images.githubusercontent.com/47016402/80490388-8d14b900-8961-11ea-900e-c2da30dd6460.gif)

I have 3 scenes. A main Scene that has the a level as child and manages the adding and removing of levels, and two levels: a red level and a green level. The red_level gets removed and re-added every time, the green_level(s) gets instanced, added and then queued free.

The weird thing is whenever the red_level gets added back to the SceneTree, the Area2D detects the player body, even though I have set the position of the player body away from the Area before even removing the red_level scene. 

This is a bit difficult to explain, best to look at [the minimal project](https://github.com/godotengine/godot/files/4545816/Area2D_enter_on_remove_bug.zip).

If makes no difference if the signal_next_level is call_deferred() or not.

```
func _on_AnimationPlayer_animation_finished(_anim_name):
	$player.position = Vector2(128, 256)
	stage_number += 1
	$Label.text = str("stage ", stage_number)
	$Area2D/ColorRect.modulate.a = 1.0
	call_deferred("emit_signal","signal_next_level")
```

What does make a difference though, is to yield timeout before the signal is emitted, but only if the timeout is long enough as user "sushi" on Discord figured out:

```
func _on_AnimationPlayer_animation_finished(_anim_name):
	$player.position = Vector2(128, 256)
	stage_number += 1
	$Label.text = str("stage ", stage_number)
	$Area2D/ColorRect.modulate.a = 1.0
	yield(get_tree().create_timer(0.1), "timeout") #0.01 would have no effect
	call_deferred("emit_signal","signal_next_level")
```
Possibly related issue:
https://github.com/godotengine/godot/issues/34085
also possibly related: https://github.com/godotengine/godot/issues/27441#issuecomment-580842668

**Steps to reproduce:**
Walk the player into the area in the middle.

**Minimal reproduction project:**
[Area2D_enter_on_remove_bug.zip](https://github.com/godotengine/godot/files/4545816/Area2D_enter_on_remove_bug.zip)

**Comment by Zireael07** [comment] 2020-04-28 13:00
IIRC we had a related issue for 3D and the problem was the things are instanced at origin for a fraction of a second...

**Comment by golddotasksquestions** [comment] 2020-04-28 13:06
@Zireael07 What do you mean by "things"? The Area too? This seems like really unclean and unrelible behavior to me.

**Comment by t-karcher** [comment] 2020-04-28 16:50
I'm pretty sure that's a duplicate of #14578 .

**Comment by Calinou** [comment] 2020-04-28 17:13
Duplicate of #14578.

**Closed by Calinou** 2020-04-28 17:13 UTC
Labels: bug
