### ISSUE TITLE
Adding/referencing F# project causes assembly/file not found error and scripts not being found

### ISSUE THREAD

**Issue by Beliaar** [godotengine/godot#66151] opened 2022-09-20 08:36 UTC
### Godot version

godot-4-0-beta-1

### System information

Windows 10

### Issue description

When I have a project that uses dotnet 6 and I have added an F# project to the dotnet solution I will get an error about the projects assembly not being able to be loaded either after some rebuilds or when I reload the godot project.
Also godot reports not being able to find the C# script files after that.

Note that calling fsharp code generally works, but it bugs out after a while.

Would be needed for godotengine/godot-proposals#191

### Steps to reproduce

1. Create a new godot project with dotnet 6
2. Add an F# project to the solution and add an reference to it from the created main C# project
3. Call some method/function of the F#  project in the main C# project (Could be optional)
4. Rebuild or reload the godot project a few times until the error appears in the log

**Comment by Beliaar** [comment] 2022-09-20 08:39
I have typed this mostly from memory. I remember the stack trace referring to some file in the glue that tries to find assemblies with godot scripts.

I can provide the exact error message and a reproduction project once I am at my own Computer again, if needed.

**Comment by raulsntos** [comment] 2022-09-20 09:24
I was unable to reproduce with the steps provided, can you upload a MRP and the error message you get?

**Comment by Beliaar** [comment] 2022-09-20 19:42
Hmm. For some strange reason I can't reproduce it with new projects any more. 
It does seem to be related to setting the Project SDK to "Godot.NET.Sdk/4.0.0-beta1", since changing it to the original value in one of the projects that had this error, made the problem go away (and changing it to "Godot.NET.Sdk/4.0.0-beta1" made it reappear), and it seems to work otherwise. Even with that value, though, I could not reproduce it with a new project.

Just for completeness, the error is:
`System.IO.FileNotFoundException: Could not load file or assembly 'StrategyFSharp, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. Das System kann die angegebene Datei nicht finden.
File name: 'StrategyFSharp, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'
   at System.Reflection.CustomAttribute._CreateCaObject(RuntimeModule pModule, RuntimeType type, IRuntimeMethodInfo pCtor, Byte** ppBlob, Byte* pEndBlob, Int32* pcNamedArgs)
   at System.Reflection.CustomAttribute.AddCustomAttributes(ListBuilder`1& attributes, RuntimeModule decoratedModule, Int32 decoratedMetadataToken, RuntimeType attributeFilterType, Boolean mustBeInheritable, ListBuilder`1 derivedAttributes)
   at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeModule decoratedModule, Int32 decoratedMetadataToken, Int32 pcaCount, RuntimeType attributeFilterType)
   at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeAssembly assembly, RuntimeType caType)
   at System.Reflection.RuntimeAssembly.GetCustomAttributes(Boolean inherit)
   at Godot.Bridge.ScriptManagerBridge.LookupScriptsInAssembly(Assembly assembly) in /root/godot/modules/mono/glue/GodotSharp/GodotSharp/Core/Bridge/ScriptManagerBridge.cs:line 283
   at GodotPlugins.Main.LoadProjectAssembly(Char* nAssemblyPath, godot_string* outLoadedAssemblyPath) in /root/godot/modules/mono/glue/GodotSharp/GodotPlugins/Main.cs:line 136
.NET: Failed to load project assembly.`

If it reappears I will come back to you but for now I would say that just not changing the SDK for the F# project - and just adding the necessary nuget packages - will fix keep that problem away.

I will leave whether to close this issue to you.

**Comment by raulsntos** [comment] 2022-09-22 10:51
Closing per the above comment. Please comment if you manage to reproduce it again.

**Closed by raulsntos** 2022-09-22 10:51 UTC
Labels: bug, topic:dotnet
