### ISSUE TITLE
One-frame flash after splash screen when running game in fullscreen

### ISSUE THREAD

**Issue by MinusKube** [godotengine/godot#51262] opened 2021-08-05 02:40 UTC
### Godot version

3.3.2.stable

### System information

Windows 10, GeForce GTX 970

### Issue description

When the game launches, whether it's from the editor or from a Windows Desktop export, if the game is set to launch in fullscreen, a black screen which lasts one frame shows right after the Godot splash screen, then the scene shows up.

It's hard to capture it in video since it's very short, but here is what's happening when launching the executable:
- The Godot splash screen directly shows up and lasts ~0.5s
- A black screen appears during ~0.01s
- The game scene shows up

### Steps to reproduce

- Create a new project
- Create an empty scene
- Enable "Fullscreen" in Project Settings > Display > Window
- Run the game

**Comment by Calinou** [comment] 2021-08-05 15:55
This is likely due to how fullscreen is handled on Windows.

Can you reproduce this if you enable **Borderless** in the Project Settings?

**Comment by MinusKube** [comment] 2021-08-05 16:23
When Fullscreen **and** Borderless are enabled, it still happens.
When only Borderless is enabled, it only happens if the window size is exactly the same as the screen size.

**Comment by Calinou** [comment] 2022-04-30 16:40
Closing in favor of https://github.com/godotengine/godot/issues/60665, as this is the same underlying cause.

**Closed by Calinou** 2022-04-30 16:40 UTC
Labels: bug, platform:windows, topic:rendering, topic:porting, needs testing
