### ISSUE TITLE
Replacing a node with another also wipes out animation tracks referencing them

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#23809] opened 2018-11-18 18:26 UTC
Godot 3.0.6
Godot 3.1 alpha2

I wanted to replace two nodes by instances of an existing scene, so basically I had to delete them both, instance the scene twice and give them the same name.
However, as I did that, the `AnimationPlayer` that was referencing them had its tracks wiped out, in all animations.
Could there be a way for this to not happen? I have to redo all animations now :(

Workaround:
rename all nodes, add the replacements, give them the wanted names, rename paths in every animation, and then delete the old nodes

**Comment by KoBeWi** [comment] 2020-06-30 23:46
This is not a bug actually, but it's sure annoying. What happens is that when you delete a node, any animation track for that node will be deleted. Closing in favor of a proposal: https://github.com/godotengine/godot-proposals/issues/1148

**Closed by KoBeWi** 2020-06-30 23:46 UTC
Labels: bug, topic:editor, usability
