### ISSUE TITLE
Editor crashes when drag & drop 3D models into the Scene

### ISSUE THREAD

**Issue by daredloco** [godotengine/godot#77918] opened 2023-06-06 15:48 UTC
### Godot version

v4.1.dev4.mono.official [5c2295ff5]

### System information

Godot v4.1.dev4.mono - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3050 Laptop GPU (NVIDIA; 31.0.15.3179) - 11th Gen Intel(R) Core(TM) i5-11400H @ 2.70GHz (12 Threads)

### Issue description

The Editor crashes when trying to add a 3D model. 

When I run it from the console I get the following errors:
```
----- AT PROJECT STARTUP -----
ERROR: Condition "skeleton->size == 0" is true. Returning: RID()
   at: skeleton_get_3d_uniform_set (./servers/rendering/renderer_rd/storage_rd/mesh_storage.h:693)
ERROR: Condition "skeleton->size == 0" is true. Returning: RID()
   at: skeleton_get_3d_uniform_set (./servers/rendering/renderer_rd/storage_rd/mesh_storage.h:693)

----- AT THE MOMENT OF THE CRASH -----
ERROR: Can't add child '@Node3D@17955' to '@SubViewport@9228', already has a parent '@SubViewport@9228'.
   at: (scene/main/node.cpp:1385)
ERROR: Children name does not match parent name in hashtable, this is a bug.
   at: (scene/main/node.cpp:1434)
ERROR: Condition "p_child->data.parent != this" is true.
   at: remove_child (scene/main/node.cpp:1411)
ERROR: Index p_index = 0 is out of bounds ((int)data.children_cache.size() = 0).
   at: get_child (scene/main/node.cpp:1497)
```

### Steps to reproduce

1) Open reproduction project
2) Drag & Drop an object from the folder res://assets/prefabs to the 3D Scene

### Minimal reproduction project

[SpaceLife.zip](https://github.com/godotengine/godot/files/11666600/SpaceLife.zip)

**Comment by YuriSizov** [comment] 2023-06-06 15:56
Thanks for opening a report! This is a duplicate of https://github.com/godotengine/godot/issues/77742, it's already fixed in `master` and will be fixed in the next published pre-release.

**Closed by YuriSizov** 2023-06-06 15:56 UTC
