### ISSUE TITLE
Plugin path should be configurable in project settings

### ISSUE THREAD

**Issue by slapin** [godotengine/godot#2537] opened 2015-09-26 13:14 UTC
plugin path should be configurable in project settings.
I should be able to add extra directories as plugin paths.
Some plugins are made as part of project development (like map editors,
various game data editore) which don't make sence in generic godot installation
and just clutter the interface.

**Comment by philiplb** [comment] 2015-09-27 09:12
This would be nice as it would have the effect, that you can just clone a project including needed plugins and you are ready to go. Else, you had to go through a setup manual telling you what plugins have to be installed. And it would have the benefit that different projects could use different versions of the same plugins without conflicts.

**Comment by akien-mga** [comment] 2016-05-20 12:07
Is this still needed now that plugins are project-specific? In this regard, it's now more or less a duplicate of #4279 (or the other way around).

**Comment by neikeq** [comment] 2016-05-20 12:27
I think @reduz mentioned months ago re-enabling global editor plugins but with less features than project-specific plugins. I don't know if he still considers doing so.

**Comment by akien-mga** [comment] 2016-05-20 12:29
I do think having support for global editor plugins could be nice, for plugins that have no impact on a specific project but increase a specific user's workflow (e.g. a "Display random xkcd strip" dock :D).

**Comment by vnen** [comment] 2016-05-20 16:02
There are already [really cool plugins](https://github.com/Calinou/awesome-godot#plugins-and-scripts) and some of them make more sense as global editor, such as the [Tiled Importer](https://github.com/MrGreenTea/GodotTiledImporter).

**Comment by neikeq** [comment] 2016-05-20 16:25
I agree with @akien-mga  and @vnen. There are items that you expect to use with every project. Adding them to every project would be annoying :P

**Comment by avril-gh** [comment] 2016-06-15 15:32
i agree with @neikeq , 
Its very usefull to have general use custom tools not related to any certain project.
Adding them (or removing before distribution) to every project would be a hassle.

Imho, **there should be both editor and project plugins tab's available**.
(and plugins meant for general use should be in "/godot/plugins" while project dependent / related might be in project folder)

**To avoid confusion of end user - add to engine.cfg file of plugin - flag "editorplugin" or  "projectplugin" and make godot check this flag**.
If user will download plugin separately and will try to use it different way than it was designed for (eg. place project dependent plugin in "/godot/plugins") then godot will not run it, (because it have "projectplugin" flag set in its engine.cfg) then might show error like "XYZ - this plugin is designed for use with editor. Please put it to /godot/plugins folder and try again." or "XYZ - this plugin is designed for use with project. Please put it to project folder and try again."

Just a simple flag in engine.cfg file of plugin and simple check by godot, solves whole confusion.
The rest is on plugin developer, but he know what he should do or not depending on what plugin it is and where its placed. Theres no need for any other limitations or checks.

**Comment by reduz** [comment] 2016-06-15 15:43
I understand the wish for global plugins, but please consider the following:

1) Many types of plugins that may seem to be global need to be local. The main use case for this is importers for different types of external content. The reason for this is that Godot will re-import on external file changes. Having this global instead of per-project would mean the project can't be distributed. Same applies to custom engine types (ie, a heightmap).  In the end, not that many plugins really need to be global.

2) The plugin API is VERY far from being final or complete, it will need a lot of feedback. I prefer we make it work first and ensure we have a good API. Once we are certain of this (likely after a long time of users making plugins), we should consider which parts of the API might be valid for a global plugin and which one does not make sense.  Doing this now would be getting very ahead of our current needs.

**Comment by slapin** [comment] 2016-06-15 15:51
I think addung custom plugin path (several lookup dirs) in project prefs
would
solve most problems and is simple enough to implement. This path would be
additional
dirs too look for plugins except for project dir. That would allow to
implement a family of projects
(i.e. development aid for the game) to have the same set of plugins and
have a set of project-
specific ones. I think this is sufficient at this stage to make everyone
happy and doesn't
affect API at all.

**Comment by reduz** [comment] 2016-06-15 16:15
@slapin as mentioned before, this is not the moment to discuss this. Once plugins are working and their API is relatively stable (likely in a year or so) we can talk again about how global plugins will be implemented. There are more important things to focus our efforts now.

**Comment by akien-mga** [comment] 2020-05-25 18:45
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!

**Closed by akien-mga** 2020-05-25 18:45 UTC
Labels: feature proposal, topic:editor, usability
