### ISSUE TITLE
gltf/glb/dae models do not update until we open the inherited scene or relaunch Godot

### ISSUE THREAD

**Issue by Linko-3D** [godotengine/godot#27409] opened 2019-03-25 15:38 UTC
Godot 3.1

If I export my model in gltf, glb or dae inside Godot and add it in the viewport, it will instance it as a scene and the model will be displayed correctly. But if I edit the model in Blender and overwrite the file, the model won't be refreshed until I open it as new inherited scene.
If I keep the tab open the model is always updated when I overwrite the file.

For example if I export Suzanne in .gltf in Godot the model is displayed:

![fine](https://user-images.githubusercontent.com/30020215/54932661-765c9100-4f1b-11e9-9612-7aedd1f9c6de.png)

Then if I edit the model in Blender and export it, the texture are updated and loaded but not the model and UVs, I get that:

![wrong model](https://user-images.githubusercontent.com/30020215/54932860-df440900-4f1b-11e9-8a33-8a8bdff16429.png)

I need to open the model in an inherited scene to update it. I keep a tab open to update the model or to close Godot and relaunch it to update everything.

![model in tab](https://user-images.githubusercontent.com/30020215/54933064-3c3fbf00-4f1c-11e9-8211-663ff44b1080.png)

**Comment by capnm** [comment] 2019-03-25 21:51
Is a duplicate of issue https://github.com/godotengine/godot/issues/25243
I'm reporting this so far unsuccessfully since January :-/

And additionally the .escn exported models (from godot blender exporter)
do not update until you delete the .import folder and restart Godot …

**Comment by fire** [comment] 2020-01-09 20:57
Close as a duplicate of https://github.com/godotengine/godot/issues/27409. Keeping the older issue.

**Comment by asheraryam** [comment] 2020-01-10 12:17
@fire you linked the same issue number, couldn't follow it :b

**Comment by fire** [comment] 2020-01-10 14:14
Sorry this is the older issue. Reopening.

**Comment by BrandonClapp** [comment] 2020-02-22 21:57
I'm also having the same issue. Exporting and overwriting a gltf from Blender does not yield an update in the Godot editor after the re-import happens.

![gltf-updating](https://user-images.githubusercontent.com/2096746/75099818-c27cdf00-558b-11ea-9d95-c309bdc811f8.png)

**Comment by KoBeWi** [comment] 2020-12-24 15:13
Can anyone still reproduce this bug in Godot 3.2.3 or any later release?

If yes, please ensure that an up-to-date Minimal Reproduction Project (MRP) is included in this report (a MRP is a zipped Godot project with the minimal elements necessary to reliably trigger the bug). You can upload ZIP files in an issue comment with a drag and drop.

**Comment by Calinou** [comment] 2020-12-24 16:22
This is likely a duplicate of https://github.com/godotengine/godot/issues/38853.

**Comment by Calinou** [comment] 2021-11-28 21:31
Duplicate of https://github.com/godotengine/godot/issues/38853.

**Closed by Calinou** 2021-11-28 21:31 UTC
Labels: bug, topic:editor, confirmed, topic:import
