### ISSUE TITLE
External editor crash.

### ISSUE THREAD

**Issue by hazarek** [godotengine/godot#41056] opened 2020-08-05 21:08 UTC
**Issue description:**

**What happened**;
When I click on the script icon it crashes. godot keeps running, only warning dialog pops up. Doesn't open with vscode.

![a](https://user-images.githubusercontent.com/36481442/89462663-7064fa00-d776-11ea-9bc0-bd18a8561f32.gif)

**What was expected;**
When the icon is pressed, it should be opened with vscode.

**Steps to reproduce:**
1. Set Vscode as external editor.
2. Open Godot
3. Open VScode
4. Click Script icon

macos crash log, It contains system and version information.;
https://gist.github.com/hazarek/cca2d59dc6dd717d5239aa2c045d57df

My external editor settings screenshot;
<img width="525" alt="cap 2" src="https://user-images.githubusercontent.com/36481442/89463400-8921df80-d777-11ea-83e3-d42945ea19f7.png">
Vscode connected to the language server.
<img width="511" alt="cap" src="https://user-images.githubusercontent.com/36481442/89463772-0e0cf900-d778-11ea-86e6-52b952aeb2f6.png">

Edit:
I found the reason of the crash. Because the full path name is not written
`Exec Path: code `- > it will crash
`Exec Path: /usr/local/bin/code` -> it won't crash

**Comment by groud** [comment] 2020-08-06 09:21
Please fill in the issue template. It asks for the Godot version you are using...

**Comment by hazarek** [comment] 2020-08-06 13:25
> Please fill in the issue template. It asks for the Godot version you are using...

I shared above. godot 3.2.2 macos 10.15.6

macos crash log, It contains system and version information.;
https://gist.github.com/hazarek/cca2d59dc6dd717d5239aa2c045d57df

**Comment by hazarek** [comment] 2020-08-09 21:38
I found the reason for the crash. Because the full path name is not written
`Exec Path: code` - > it will crash
`Exec Path: /usr/local/bin/code` ->  it won't crash

**Comment by akien-mga** [comment] 2020-08-11 14:20
Duplicate of #17615.

**Closed by akien-mga** 2020-08-11 14:20 UTC
Labels: bug, crash, topic:editor
