### ISSUE TITLE
Incorrect display of Vector2,3 in the debugger

### ISSUE THREAD

**Issue by lekoder** [godotengine/godot#22528] opened 2018-09-29 08:32 UTC
**Godot version:**
3.1.alpha a2b6be2

**OS/device including version:**
Windows 10

**Issue description:**
When debugger is showing contents of `Vector2`, the values are capped to [-65535,65535]. Also affects `Vector3`.

**Steps to reproduce:**
Run code with brakpoint:
```
	var v = Vector2(0,1000000)
	var vy = v.y
	print("%s %f %f" % [ v, v.x, v.y ])
```
![godot-vector-truncated-3](https://user-images.githubusercontent.com/1224527/46243252-78adba80-c3d2-11e8-9a2b-ea5b2cda44cf.png)
Console output is as expected:
```
(0, 1000000) 0.000000 1000000.000000
```

**Comment by Sslaxx** [comment] 2018-09-29 08:58
This sounds like a regression; it's similar to #6083.

**Comment by groud** [comment] 2018-09-29 13:14
This is more or less a duplicate of #5867 but for vectors.

**Comment by DualMatrix** [comment] 2018-09-29 13:35
This does not seem to be related to the debugger, just even in the regularl inspector values above 65535 will be displayed incorrectly. I suspect this is an issue with ranges.

**Comment by JFonS** [comment] 2018-09-29 13:52
65535 is 0xFFFF in hexa, maybe the editor uses an uint16 and can't handle values higher than that?

**Closed** 2018-12-07 22:15 UTC
Labels: bug, topic:editor
