### ISSUE TITLE
"A file or folder with this name already exists" errors when renaming folder to a different name

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot#82543] opened 2023-09-29 19:16 UTC
### Godot version

Godot v4.2.dev (44e399ed5)

### System information

Mageia 9 - X11 - GLES3 (Compatibility) - AMD Radeon RX Vega M GL Graphics (vegam, LLVM 15.0.6, DRM 3.52, 6.4.9-desktop-4.mga9) () - Intel(R) Core(TM) i7-8705G CPU @ 3.10GHz (8 Threads)

### Issue description

I have this simple setup, using **Split Mode**:
![image](https://github.com/godotengine/godot/assets/4701338/971fff17-5751-4e1b-9b2b-21cf94f02c3b)

If I try to rename a folder (e.g. `player`) in the thumbnails view, a number of bugs occur:

Start renaming with F2 or Right click > Rename

- Keep the same name, and click in the FileSystem dock: no change, no error, as expected
- Keep the same name, and click outside the FileSystem dock:
  * If clicking in the Scene tree (positioned in the same column for me), no change, no error
  * If clicking in the Inspector, or 3D viewport, an error is shown that it can't be renamed as the name is taken

![image](https://github.com/godotengine/godot/assets/4701338/b40ed63b-162c-4375-819b-70635f5cdc6a)

And a transient window elusive child error from that popup.

- Change the name to something unique (e.g. `player2`), then confirm the change with the mouse:
  * If clicking in the FileSystem dock, the rename works sometimes, and the folder is entered automatically, which seems weird to me. The selection is also out of sync between the tree view and the thumbnails view:

![image](https://github.com/godotengine/godot/assets/4701338/2293b813-6eca-48e2-b6b3-8f76fae25cef)

  * But in other times with the same steps, it fails with the error about a file name conflict. Not sure how to reproduce reliably, it seems to happen maybe 10% of the time for me.
  * If clicking in the Scene tree, same behavior as above.
  * If clicking in the Inspector, or 3D viewport, same file conflict error as above.

- Change the name to something unique (e.g. `player2`), then confirm the change with the <kbd>Enter</kbd>:
  * Same behavior as with mouse click.

Some of these bugs seem specific to the Split Mode, but others seem to also happen in Tree view. It feels very buggy overall, it needs a thorough fixup pass.

Seems to be a regression which happened between 4.2-dev1 and 4.2-dev3. 4.2-dev2 is outright crashing on start so I can't test further. In dev1, I don't get the dialog about file name conflicts. I do get the weird behavior that editing a folder name enters the folder, and makes the selection out of sync in Split Mode, so that's a pre-existing and different bug.

### Steps to reproduce

See above.

### Minimal reproduction project

Reproducible in a brand new project.

**Comment by akien-mga** [comment] 2023-09-29 19:18
#75137 sounds like a potential culprit, but I didn't test a local revert to confirm.

CC @KoBeWi @nongvantinh

**Comment by nongvantinh** [comment] 2023-09-29 20:47
I pulled the latest code from master, reverted the #75137, and built the project. The bug still occurs, so #75137 is not causing this issue. However, I will take some time to bisect it.

**Comment by nongvantinh** [comment] 2023-09-30 22:11
The actual commit that causes the issue is 1c3c17c608df7f05ba27a95f4a5ceb5e67f935d7 by @Sauermann. Unfortunately, I don't have more time to think about why it causes the bug. But after a while of bisecting, it actually causes the bug. I leave the further work for you @akien-mga.

**Comment by akien-mga** [comment] 2023-10-01 21:21
> * If clicking in the FileSystem dock, the rename works sometimes, and the folder is entered automatically, which seems weird to me. The selection is also out of sync between the tree view and the thumbnails view:

This part seems to be this pre-existing bug report: #80940.

**Comment by Sauermann** [comment] 2023-10-02 17:30
> Start renaming with F2 or Right click > Rename
> 
> * Keep the same name, and click outside the FileSystem dock:
>   * If clicking in the Inspector, or 3D viewport, an error is shown that it can't be renamed as the name is taken

I have tested this behavior (in a newly created project) and I was able to replicate this bug in v4.2.dev1.official [0c2144da9] on Debian X11 Linux.
So this seems also to be a preexisting issue before 1c3c17c608df7f05ba27a95f4a5ceb5e67f935d7.

#75137 got merged after dev1, so it is likely, that it isn't the cause of the problem.

I did check this bug with previous versions and I found, that it got introduced between v4.1.dev4.official [5c2295ff5] and v4.1.beta1.official [828ec2c5d]

**Comment by nongvantinh** [comment] 2023-10-02 18:22
Weird, I just downloaded https://github.com/godotengine/godot-builds/releases/download/4.2-dev1/Godot_v4.2-dev1_win64.exe.zip and tested it on my Windows 10, and the bug definitely did not occur. However, when I was bisecting the commit range from 4.2-dev1 to 4.2-dev5, https://github.com/godotengine/godot/commit/1c3c17c608df7f05ba27a95f4a5ceb5e67f935d7 turned out to be the last bad commit. I took the time to revert it, fixed some compile-time errors, and then tested the code again before coming to a conclusion.

**Comment by Sauermann** [comment] 2023-10-02 18:40
I find it also confusing, that we come to different conclusions.
After doing more tests, I found, that the setting "single window mode" affects the bug.

If "single window mode" is on, then the bug starts appearing between v4.1-dev4 and v4.1-beta1
If "single window mode" is off, then the bug starts appearing in 1c3c17c608df7f05ba27a95f4a5ceb5e67f935d7

So I can confirm your bisection.

**Comment by akien-mga** [comment] 2023-10-06 16:22
More weirdness with the FileSystem dock that might be related to this.

With the following setup:
```
icon.svg
node2d.tscn
```

- Select `icon.png`
- Navigation to `node2d.tscn` with <kbd>Down</kbd>

![image](https://github.com/godotengine/godot/assets/4701338/b9e6b8bd-1725-4fcb-9e2a-2ac560406932)

- Press F2 to rename. The rename box appears to be changing the focused item (as it should, and it works well in 4.1), but it actually highlights a section of the name that matches the size of `icon` (4 chars).

![image](https://github.com/godotengine/godot/assets/4701338/d6e68f3f-e4e7-4b7d-99e3-7e6c905dda7d)

- Losing focus triggers the bug described above, and actually renames the file to `icon.svg`, so both files end up having the same name:

![image](https://github.com/godotengine/godot/assets/4701338/325923e0-9a44-445c-aee5-ddb229546c1f)

- But it's actually a lie, it's `icon.svg` which got renamed to its existing name. Double clicking `res://` to force a refresh shows that the `node2d.tscn` file wasn't renamed:

![image](https://github.com/godotengine/godot/assets/4701338/c784c42f-744c-4745-99ff-c313b0f71c7c)

- If I repeat the first steps, and actually rename what seems to be `node2d.tscn`, it renames `icon.svg`, breaking it because it changing the extension:

![image](https://github.com/godotengine/godot/assets/4701338/12124b43-c2d5-4b4b-b951-3d67e08209ef)

![image](https://github.com/godotengine/godot/assets/4701338/aa8a8966-b324-42c5-9c03-586c0f334892)

**Comment by nongvantinh** [comment] 2023-10-06 18:23
The new mouse signal causes the following check to be ignored because none of them has `focus()
`
https://github.com/godotengine/godot/blob/6916349697a4339216469e9bf5899b983d78db07/editor/filesystem_dock.cpp#L1731-L1739

**Comment by Sauermann** [comment] 2023-10-07 01:21
When renaming a file, a `LineEdit` Control-node opens and grabs focus from the `FileSystemTree` or from the `FileSystemList`, since they are in the same Window:

https://github.com/godotengine/godot/blob/6916349697a4339216469e9bf5899b983d78db07/editor/filesystem_dock.cpp#L131

So the `FileSystemList` doesn't have focus.

**Closed** 2023-10-09 21:29 UTC
Labels: bug, topic:editor, regression

**Comment by JosephCatrambone** [comment] 2024-05-07 19:06
I'm seeing this pop up again in the latest 4.3 dev 6 [89850d553].  It's 100% reproducible on Windows 10 Pro.

**Comment by KoBeWi** [comment] 2024-05-07 19:12
It was likely fixed by #91112, which was merged today.
