### ISSUE TITLE
Enviroment Background's mode Canvas break some UI elements

### ISSUE THREAD

**Issue by Taiseibutsu** [godotengine/godot#66146] opened 2022-09-20 07:56 UTC
### Godot version

4.0 beta 1

### System information

Windows 10

### Issue description

Viewport stop being redraw and text desciptions are not being displayed when Canvas mode is seleceted from World enviroment's backgorund

![Canvas_test](https://user-images.githubusercontent.com/84092569/191201236-762fa06b-fd5a-4470-affa-5a16e720a795.gif)

### Steps to reproduce

-Create an Enviroment
-Select Background mode to Canvas.
-Hover the mouse on any property in order to get a description

### Minimal reproduction project

[Uploading Canvas_World_Enviroment_Windows.7z…]()

**Comment by Zireael07** [comment] 2022-09-20 07:59
Duplicate of... lotta other issues... seriously, searching for background canvas shows a lot

**Comment by Zireael07** [comment] 2022-09-20 08:04
double click?

**Comment by Taiseibutsu** [comment] 2022-09-20 08:06
https://github.com/godotengine/godot/issues/52467#issue-990157976

**Closed** 2022-09-20 08:06 UTC
