### ISSUE TITLE
Problem with creating C# project with latest custom mono and godot build

### ISSUE THREAD

**Issue by ghost** [godotengine/godot#24361] opened 2018-12-14 22:36 UTC
**Godot version:**
Godot latest build from Github ( 3.1 Alpha 3 / custombuild )

**OS/device including version:**
Ubuntu 18.04 and Mono 5.23.0 latest build from github.
OpenGL ES 3.0 Renderer: AMD Radeon (TM) RX 480 Graphics
Editing project: /home/sourceskyboxer/TestCS_Alpha3_1 (::home::sourceskyboxer::TestCS_Alpha3_1)
OpenGL ES 3.0 Renderer: AMD Radeon (TM) RX 480 Graphics

**Issue description:**
"Failed to create C# project" If I use copy_mono_runtime=yes
It looks can't resolve

**Steps to reproduce:**
Create new project and mono -> create C# solution than it throws alert "Failed to create C# project!"

**Minimal reproduction project:**
Same Step to reproduce

**History of compilation and testing**
I download mono from github
./autogen.sh --prefix=/usr --enable-big-arrays --enable-large-heap=yes
make -j32
sudo make install

and download godot from github
scons p=x11 tools=yes module_mono_enabled=yes mono_glue=no copy_mono_root=yes -j 32
bin/godot.x11.tools.64.mono --generate-mono-glue modules/mono/glue
Here is my output:
https://gist.github.com/SourceSkyBoxer/64222696be7b0af0b9ea932d2f003786

And I build it:
scons p=x11 target=release_debug tools=yes module_mono_enabled=yes copy_mono_root=yes -j 32
And open it than I create new project and select mono -> create C# solution
It throws 
![image](https://user-images.githubusercontent.com/44162204/50033410-a4673680-fff8-11e8-99ee-b9ba3e7ee997.png)

// EDIT - I add for open with existing project
Open with existing projects than godot crashed
https://gist.github.com/SourceSkyBoxer/1c5f8223056dcf1bece7fd85676d5d73
// 

That is proof - why do I not get solution. I can't believe that. Is it buggy or I should roll back with Mono runtime version?

But I have installed MonoDevelop here and my own C# development works fine with latest version of Mono runtime.

**Comment by hpvb** [comment] 2018-12-15 00:03
do you have a working msbuild?

**Comment by hpvb** [comment] 2018-12-15 00:05
Also can you try running with TERM=linux godot.x11 ... ?

**Comment by SourceSkyBoxer** [comment] 2018-12-15 03:00
Hello @hpvb  Thanks funny monkey,

Yes I am using msbuild from Mono 5.18.0 ( Mono custom build was critical because it has problem like runtime is not stable. but mkbundle works fine.)
I have compiled mkbundle from custom mono and copy into Mono 5.18

Godot 3.0.6 + Mono 5.18 = no problem and no any issues = COMPLETED SUCCESSFULLY 
Godot 3.1 Alpha 3 / custom version + Mono 5.18 = If I create C# solution = It happens it looks crazy :(

Bonus Fix: Godot 3.0.6 and Mono 5.18 with custom mkbundle version from mono latest build = It sis successfully.

So sad for latest version sometime not works....

**Comment by exts** [comment] 2018-12-15 03:07
Are you using the same project? Can you test by creating a completely new empty project if you haven't.

**Comment by SourceSkyBoxer** [comment] 2018-12-15 03:18
Yeah I have create new project from Godot 3.06 + Mono 5.18 = No problem 

Godot latest + 5.18 = no work for creating project and opening exited project = No success and it throws errors

That is why existing project or new creating project looks like don't work yet. Please check Godot -> #csharp from Discord Server My name is Jens Eckervogt.

**Comment by hpvb** [comment] 2018-12-15 10:14
copy_mono_root doesn't do anything on 3.0.6 it is a new feature. I'm still really not clear on what you're trying to do or what the problem is. 

Can you give us the console output of when you get the 'cannot create C# project' error?

**Comment by SourceSkyBoxer** [comment] 2018-12-15 11:16
Oh @hpvb Oh sorry my bad English. I explain easy Godot 3.0.6 with Mono 5.18.0 and it works fine.
I will show you video like this.
https://www.youtube.com/watch?v=Y-YdmT9_NzM

I show you with latest Godot + Mono 5.18.0 = Error and criticality
https://www.youtube.com/watch?v=KE8DJmlbQy0

That is proof because 2 different ways stable Godot and latest Godot. And thanks! Please fix critical issue for latest Godot build

**Comment by Calinou** [comment] 2021-05-06 17:59
The C# build system and solution architecture has changed significantly since 3.1alpha3. These issues are likely no longer present in 3.3 (or in a different form), closing. To avoid opening a duplicate, please search for other related `topic:mono` 
issues before opening a new issue.

**Closed by Calinou** 2021-05-06 17:59 UTC
Labels: bug, topic:mono
