### ISSUE TITLE
[Godot 4.X / .NET] Duplicating and Copy/Pasting a node or packed-scene in scene-tree will "just copy" all node paths, not adapting them!

### ISSUE THREAD

**Issue by MostWanted38** [godotengine/godot#84146] opened 2023-10-29 15:42 UTC
### Godot version

4.2-beta3.mono, 4.2-beta2.mono, 4.2-beta1.mono, 4.1.2.stable.mono, 4.1.1.stable.mono, 4.1.0.stable.mono, 4.0.stable.mono

### System information

Godot v4.2.beta3.mono - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3080 (NVIDIA; 31.0.15.3623) - AMD Ryzen 7 3800X 8-Core Processor (16 Threads)

### Issue description

Take the following hierachy
![image](https://github.com/godotengine/godot/assets/45302427/43125e26-7c4c-45ec-8c2c-c47d047a6177)

In Godot 4.X (with .NET) -> if you duplicate a Node "Node1" that has a script attached with a reference to its child node "Node1Child1" the NodePath will just get copied to the newly instantiated Node(-Tree) "Node2". Even if you rename the child of "Node2" to "Node2Child1", the node "Node2" will have a reference with path "Node1/Node1Child1". This behaviour exists both on duplicated nodes with scripts as well as on duplicated packed-scenes (making level design with duplicated objects a pain)
![image](https://github.com/godotengine/godot/assets/45302427/b849dc69-7708-48d3-aacd-c192540098c3)
![image](https://github.com/godotengine/godot/assets/45302427/9f284ac2-06df-41c9-965b-e2c68a851681)

**How its supposed to work:**
In Godot 4.X (with GDScript) -> if you copy a Node "Node1" that has a script attached with a reference to its child node "Node1Child1" the NodePaths will be adjusted to the children of the newly instantiated and inserted Node(-Tree) "Node2"
So the NodePath of the reference from "Node2" will become "Node2/Node1Child1" instead of "Node1/Node1Child1" 

So only the C#/.NET version is broken with this behaviour. Even trying it out with the [Tool] attribute added doesnt make a change.

**Assumption:** 
As my previous issue #84016 also had a problem where NodePaths become null on packed-scene creation due to a exception found in the pull-request #84092 this problem could also be sitting inside the way Nodes and NodePaths work
[node.cpp](https://github.com/godotengine/godot/blob/0b62b52becb2b5367300dd0918108ce2f1875176/scene/main/node.cpp)
[node_path.cpp](https://github.com/godotengine/godot/blob/0b62b52becb2b5367300dd0918108ce2f1875176/core/string/node_path.cpp)

### Steps to reproduce

0) Use the .NET Version of any Godot 4.X version and create a test-project
1) Create a new Scene (Other Node) and name the Root Node "Root"
2) Add a Child Node below "Root" and name it "Node1"
3) Add a Child Node below "Node1" and name it "Node1Child1"
![image](https://github.com/godotengine/godot/assets/45302427/e73dcaa9-bcf4-4d4d-ad51-46a70e11aeb5)
4) Create both a new GDScript and C#Script that inherits from Node and name it "NodePathTest.gd" and "NodePathTest.cs"
5) Insert the following codes:
```gdscript
extends Node
class_name NodePathTest

@export var childNode : Node;
```
```cs
using Godot;

[GlobalClass]
public partial class NodePathTest : Node
{
    [Export] public Node childNode;
}
```
6) To see the problem yourself, assign the C#Script to "Node1" and set "Node1Child1" as reference for "childNode"
![image](https://github.com/godotengine/godot/assets/45302427/f9548ce5-8fc9-4b79-a7bb-ce02327561ba)
7) In Scene Tree, Select "Node1" and duplicate it (Ctrl+D) and rename the child of the instantiated "Node2" to "Node2Child1"
8) Select "Node2" and take a look at the inspector
![image](https://github.com/godotengine/godot/assets/45302427/cf3be609-eab6-4112-8c93-fa363d215f2a)
9) Select "Node1" and hit Ctrl+C (Copy), Select the "Root" node, hit Ctrl+V and renamed the child of "Node3" to "Node3Child1"
Same problem!
![image](https://github.com/godotengine/godot/assets/45302427/5765fffe-6fb8-407f-b47b-d8cbc5c4b818)
10) if you right-click "Node1" and select "Save Branch As Scene" (node1.tscn) you'll experience my other issue #84016, having to re-assign  the node-reference again both in packed scene as well as in-scene.
![image](https://github.com/godotengine/godot/assets/45302427/35f6ce66-be7a-42ba-9f1e-120796921059)
![image](https://github.com/godotengine/godot/assets/45302427/d83ff85d-1f61-498a-98b6-22292ceb33dd)
11) if you duplicate the packed-scene you'll get "Node4" with a wrong reference
![image](https://github.com/godotengine/godot/assets/45302427/76ac9d4a-b97b-4373-b35c-0678d78e0c62)
12) Hitting the "Back Arrow" next to "childNode" on "Node4" fixes the reference to its actual child node
![image](https://github.com/godotengine/godot/assets/45302427/b92fae92-c798-433a-8742-7df98b53fea8)

Assume you made like 20 duplications... then you can do Step12 on all of them.. So time consuming

### Minimal reproduction project

This setup should be performed by yourself to see it in action.
Sending a project with a previously created packed-scene doesnt make sense

**Comment by AThousandShips** [comment] 2023-10-29 15:43
Duplicate of https://github.com/godotengine/godot/issues/78060

**Closed by AThousandShips** 2023-10-29 15:43 UTC
