### ISSUE TITLE
gles3 branch: Editor crashes on Windows

### ISSUE THREAD

**Issue by sezit** [godotengine/godot#7356] opened 2016-12-23 09:23 UTC
**Operating system or device - Godot version:**
Windows 10 AMD - 2.2 GLES3 

**Issue description** (what happened, and what was expected):
When the editor is run, it immediately generates an error. Yes the engine is still in early access, but maybe its useful.
UPD. 25.12.2016
Now i have new error :З

**Steps to reproduce:**
Compile from last source.

![error](https://cloud.githubusercontent.com/assets/6241034/21450739/88985c44-c90a-11e6-8012-fea37b18d2d9.png)
![1](https://cloud.githubusercontent.com/assets/6241034/21472772/f814c300-caf9-11e6-9292-b881bb8410e7.png)

**Comment by Calinou** [comment] 2016-12-23 09:26
The engine compiles on Windows but does not run, I can also reproduce this. There's currently no known fix, and @reduz is trying to work on it.

**Comment by chanon** [comment] 2016-12-26 08:47
I've been compiling from master branch and find that the debug build (compiled by selecting debug in Visual Studio) works fine and is what I've been developing on.

However, release build does not work at all. I don't even get a console window or error popup. Just nothing happens.

Is this issue the same thing?

**Comment by avril-gh** [comment] 2016-12-26 11:45
> master branch works fine on Windows 10 currently

also on windows 7 32bit

**Comment by bojidar-bg** [comment] 2016-12-27 12:02
@chanon @avril-gh This issue is about the `gles3` branch, not the master branch.

**Comment by plucian** [comment] 2017-01-03 10:59
editor compiles but crashes on start.. win8 on 64 bit.
I'll post picture when I get home.

**Comment by plucian** [comment] 2017-01-04 11:45
seems was just a driver issue, changing the video card got rid of the Can't create rendering context. The editor started and I wanted to create a new project, and only after trying to launch the new project the editor crashed. I know it's early and bugs are to be expected. I'm just trying to help not to be annoying :)

**Comment by RebelliousX** [comment] 2017-01-20 09:55
I know this branch is unstable, but to help identify the problem faster since main devs are using linux.
Here is the log of [Godot](http://pastebin.com/rdbJG4xL). It is funny that godot keeps running even after "closing" it from Debug/Close message from Windows, and the log gets spammed with OpenGL errors after that, so most of the errors in the log happen after it crashes.

**Comment by reduz** [comment] 2017-08-05 18:26
long since fixed

**Closed by reduz** 2017-08-05 18:26 UTC
Labels: bug, confirmed, platform:windows, topic:rendering
