### ISSUE TITLE
Leaving the selection on the default string in an enum export variable yields a blank string in GDScript

### ISSUE THREAD

**Issue by lukenomics** [godotengine/godot#54779] opened 2021-11-08 19:46 UTC
### Godot version

v3.4.stable.official [206ba70f4]

### System information

Windows 10, GLES3

### Issue description

Creating an export string variable with defined choices, if you leave the selection on the first choice in the editor, accessing that variable in GDScript will give you an empty "" string, rather than the first option.

With the following example from GDScript documentation:

export(String, "Warrior", "Magician", "Thief") var character_class

Leaving the variable selection as the default "Warrior" in the editor, and then accessing the character_class variable in code will give you "" as the string value.

"Warrior" will not appear as the value for this variable unless you select a different value and then select the first one again.

### Steps to reproduce

- In GDScript, define an export variable string with defined values like 'export(String, "string1", "string2", "string3") var variableName'
- Do not change the selection for this variable in the editor (it will default to "string1")
- In code, run print(variableName) and it will print a blank string.

### Minimal reproduction project

[Error Demo Enum Strings.zip](https://github.com/godotengine/godot/files/7499681/Error.Demo.Enum.Strings.zip)

**Comment by Calinou** [comment] 2021-11-08 20:28
Duplicate of https://github.com/godotengine/godot/issues/33914.

**Closed by Calinou** 2021-11-08 20:28 UTC
Labels: bug, topic:editor
