### ISSUE TITLE
Incorrect results of Shape2D.collide_and_get_contacts

### ISSUE THREAD

**Issue by eon-s** [godotengine/godot#19618] opened 2018-06-17 21:49 UTC
**Godot version:** 3.0.x and 2.1.x

**Issue description:**
`Shape2D.collide_and_get_contacts` do not report the correct contact points, also adds some null contact points to the reported list.
Tested with `RectangleShape2D` and `CircleShape2D`.

![shapecollisionbug](https://user-images.githubusercontent.com/10215987/41512422-6d7adac8-725e-11e8-984e-18835248df5c.png)
In the image, the contact points are shown with a dot (except the null ones), the bug has the same behavior on Godot 2.1 and 3.0.

**Steps to reproduce:**
Use `collide_and_get_contacts` and check the result.

**Minimal reproduction project:**
The example project has a script with tool mode to check the reported points, just move the position nodes to test.
[shape_collision.zip](https://github.com/godotengine/godot/files/2109435/shape_collision.zip)

**Comment by reduz** [comment] 2018-09-07 18:13
These functions will not work properly in tool mode, as physics engine is disabled. Maybe this should be documented.

**Comment by eon-s** [comment] 2018-09-08 00:06
@reduz that image is at runtime, not tool mode, is just showing the positions of the detected contacts (check the example project), is an old bug that is there since 2.0 at least.

This makes impossible to use shape for manual collision checks.

**Comment by nanoquack** [comment] 2018-11-06 23:31
Will this be fixed in 3.1? Or is there at least some workaround? I have exactly the same problem and would really need to collide shapes manually (context: my ai would use it to calculate its next move)

**Comment by eon-s** [comment] 2018-11-08 00:00
@nanoquack for a workaround you can try doing many segment shape casts instead of a single closed polygon, quite complex and probably slow if you are using detailed circle shapes but there are no many options I guess.

**Comment by nanoquack** [comment] 2018-11-08 18:29
Thanks for the suggestion! I've now decided to implement a collision detection that uses the same interface as godot's collision methods (calculates collisions between Shape2D-Classes and returns a Vector2-Array) and will just replace it with the godot implementation when the issue is resolved.

If the issue stays open longer and I find the time I will probably implement collision for all Shape2D Types (for the moment I just quickly needed SegmentShape2D and CircleShape2D) and post it here for others who might have the same problem

**Comment by eon-s** [comment] 2018-12-30 19:31
This still happens on a 3.1 build ( fb9085a ).

![collide_and_get_contacts_bug](https://user-images.githubusercontent.com/10215987/50550466-4e2d0100-0c50-11e9-8f96-a4c611c981bb.gif)

**Closed** 2019-01-17 15:02 UTC
Labels: bug, topic:core
