### ISSUE TITLE
Call to Signal.get_object() evaluates to bool in if condition (GDScript 2/Godot 4.02)

### ISSUE THREAD

**Issue by jhlothamer** [godotengine/godot#75660] opened 2023-04-04 21:38 UTC
### Godot version

4.02

### System information

Ubuntu 22.10/Windows 11

### Issue description

When checking that a signal's object is a valid instance and that that object is a Node in an if condition, for some reason the call to get_object() evaluates to a boolean and not an object.  Once this happens, the call to Signal.get_object() continues to evaluate to a boolean.  

However, if the code is changed slightly, it works as expected.  I will list edits from the reproducing code that make the issue go away.

### Steps to reproduce

In a scene with a button, access the pressed signal and then check if it's object is a valid instance and is a Node.

```
extends Control

var _signal: Signal

func _ready():
	_signal = $Button.pressed
	if is_instance_valid(_signal.get_object()) and (_signal.get_object() is Node):
		print("issue not reproduced")
	else:
		# output parts of the if expression and do some sanity checks
		print("issue reproduce (expected)")
		print("is_instance_valid(_signal.get_object()) evalutes to %s" % is_instance_valid(_signal.get_object()))
		print("_signal.get_object() is Node evalutes to %s" % _signal.get_object() is Node)
		print("_signal.get_object() evalutes to %s" % _signal.get_object())
		print("typeof(_signal.get_object()) == TYPE_BOOL ?? %s" % (typeof(_signal.get_object()) == TYPE_BOOL))
```
Some edits that make the issue go away:

- If instead of a member variable for the signal, the $Button.pressed signal is directly referenced, the issue goes away.
- If instead of a member variable for the signal, a local variable is used, the issue goes away.
- If instead of making the call to _signal.get_object() in the if condition, a local variable is created and set to _signal.get_object(), the issue goes away.

### Minimal reproduction project

[godot4_gdscript_issue_signal_get_object_bool-main.zip](https://github.com/godotengine/godot/files/11153461/godot4_gdscript_issue_signal_get_object_bool-main.zip)

Or see [the repo](https://github.com/jhlothamer/godot4_gdscript_issue_signal_get_object_bool)

**Comment by AThousandShips** [comment] 2023-04-04 21:52
Duplicate of #73998

**Closed** 2023-04-04 23:27 UTC
