### ISSUE TITLE
Matrix tab doesnt update in real-time at editor!

### ISSUE THREAD

**Issue by nonunknown** [godotengine/godot#45134] opened 2021-01-12 17:08 UTC
**Godot version:**
3.2.4 beta5 mono

**OS/device including version:**
Windows 10 x64

**Issue description:**
![image](https://user-images.githubusercontent.com/58845030/104347434-60003a80-54df-11eb-92af-a86cb557fa3c.png)
Sometimes only Translation and Scaling updates in real-time other not, rotation never updates.

In order to update the user has to click other node and select the target again.

**Steps to reproduce:**
*Create a cube
* Rotate/Scale/Translate
* Note that Matrix tab doesnt update (sometimes only for Scale/Translate)

**Minimal reproduction project:**
N/A

**Comment by Calinou** [comment] 2021-01-12 17:21
Duplicate of https://github.com/godotengine/godot/issues/20850.

**Closed by Calinou** 2021-01-12 17:21 UTC
