### ISSUE TITLE
MenuButton dropdown popup doesn't scale/inherit his parents scale

### ISSUE THREAD

**Issue by Rebell10n** [godotengine/godot#82335] opened 2023-09-25 21:44 UTC
### Godot version

v4.1.1.stable.official [bd6af8e0e]

### System information

Windows 7, yeah I know that old, but not relevant imo, CPU : Intel i-5-4200H, 2.80GHz, GPU : GeForce 840M DDR3 2 Go

### Issue description

![CapturedD](https://github.com/godotengine/godot/assets/43638454/353d2a9a-58f7-44b3-9843-56ec4849f8a2)

Well the title and screen talk by themselves. I tried many ways to fix it by myself, but unless I rescale afterwards for each dropdown, no way to make it inherit from the parents nodes, so really annoying if I end up making a lot of theses.

The thing that surprised me is that there bug report of the same thing... years ago : 
https://github.com/godotengine/godot/issues/19451
https://github.com/godotengine/godot/pull/28334

### Steps to reproduce

Idk if it works with every menu dropdown or every dropdown like this right now.
But the way I got it was while I was adjusting (and fixing) the Waste No Space GUI from Hoonius :
https://hoonius.itch.io/waste-no-space-gui
and scaled the top-parent node by 2. The rest followed, but not the dropdown, not any dropdown btw.

### Minimal reproduction project

N/A I think ? Well kinda easy to reproduce. If that really needed I can build up something real fast, but don't think that really needed ?

**Comment by Sauermann** [comment] 2023-09-25 23:22
Without checking the project, this is likely a duplicate of #69171 or #69749

**Comment by Rebell10n** [comment] 2023-09-25 23:38
Well I checked each issues you linked, and it seems I don't need the condition of either a SubViewportContainer node parent or to uncheck "Embed Subwindows" to have this bug.

**Comment by rsubtil** [comment] 2023-09-26 12:32
What are your viewport stretch settings?
![image](https://github.com/godotengine/godot/assets/6501975/0b5e24d9-c1ef-40c5-b0fd-645a11f29338)

**Comment by Calinou** [comment] 2023-09-26 15:08
> and scaled the top-parent node by 2.

This isn't the correct way to do UI scaling, as it will break in a lot of situations. Control node scaling should only be used for animation purposes.

See the [Multiple resolutions](https://docs.godotengine.org/en/stable/tutorials/rendering/multiple_resolutions.html) documentation instead.

**Comment by Rebell10n** [comment] 2023-09-26 21:00
Well rsubtil I didn't change it at first, even throught I've seen it, I didn't understood how it worked first even while trying to medle with it. The screenshot were taken while with the "default" settings of viewport strech.
But thanks to Calinou, seems I was doing it the bad way, cuz now... it "works", it scaled. Honestly small suggestions, but the editor should put a warning while you scale an UI, to not let you do this error again lol, since it not the intended way to do it.

Well it "works" is a big approximation honestly, now it scale... not well : 
![CapturedD](https://github.com/godotengine/godot/assets/43638454/2f4dec93-28b7-4535-95ea-2e55fffa10ca)


The font seemly tripled in size, cuz the text in the Popup is supposed to be 16, while the rest has the default size of 12 (and yes it's the same font)
So is that another issue/bug, or did I just missed something again lul ?

**Comment by Calinou** [comment] 2023-09-26 23:26
> The font seemly tripled in size, cuz the text in the Popup is supposed to be 16, while the rest has the default size of 12 (and yes it's the same font)

That issue is bei
ng tracked in https://github.com/godotengine/godot/issues/54030, so I'll close this accordingly.

**Closed by Calinou** 2023-09-26 23:26 UTC
Labels: bug, topic:gui

**Comment by Rebell10n** [comment] 2023-09-26 23:36
Ooow, seems the issue already posted, awesome then, thanks for everything ^^
