### ISSUE TITLE
Autogenerated C# code is placed out of scope

### ISSUE THREAD

**Issue by Enbeam** [godotengine/godot#85065] opened 2023-11-18 17:31 UTC
### Godot version

4.1.3 stable

### System information

Godot v4.1.3.stable.mono - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 2070 SUPER (NVIDIA; 31.0.15.3758) - Intel(R) Core(TM) i7-9700 CPU @ 3.00GHz (8 Threads)

### Issue description

When generating C# Code for example using signals, the autogenerated code of the function is placed outside of the class scope thus making the code not compilable.
![image](https://github.com/godotengine/godot/assets/86499049/1f0033c2-1060-436b-9aee-dc36d2360c9f)
In the image, the scope is marked in red, clearly showing that the function _on_start_timer_timeout() is placed outside of the scope.
Please disregard _on_mob_timer_timeout as i corrected that functions placement manually.

### Steps to reproduce

Inside a C# Project create two nodes.
One (Main) is a Node, the other can be any type of node (in the example screenshot above a timer is used).
Add the secondary node as a child of Main.
Attach a C# script to Main, creating the class body for Main.
Then go to secondary node switch to the "Node" tab in the Inspector, doubleclick a signla to connect it to a method.
Choose Main and press connect.

Result: The generated Receiver Method is placed out of scope

### Minimal reproduction project

[BugReportScope.zip](https://github.com/godotengine/godot/files/13401050/BugReportScope.zip)

**Comment by raulsntos** [comment] 2023-11-18 18:04
Duplicate of https://github.com/godotengine/godot/issues/18721

**Closed by raulsntos** 2023-11-18 18:04 UTC
