### ISSUE TITLE
Vulkan: Canvas Environment background mode makes all CanvasItems invisible

### ISSUE THREAD

**Issue by EIREXE** [godotengine/godot#49246] opened 2021-06-01 21:01 UTC
**Godot version:**
9990f28d8414e27843eb0626fbf7f0277e6c9130

**OS/device including version:**
Vega 56, Arch

**Issue description:**
Canvas mode is supposed to work, could it be that it's not yet implemented?

**Steps to reproduce:**
Add a worldenvironment, add an einvronment, set the background to canvas.

**Minimal reproduction project:**

![imagen](https://user-images.githubusercontent.com/3101690/120389801-311f1f80-c32d-11eb-80b3-4facb708cb81.png)

![imagen](https://user-images.githubusercontent.com/3101690/120389811-354b3d00-c32d-11eb-8b3b-4348a54aa253.png)

**Comment by jsmnbom** [comment] 2022-02-02 12:38
Duplicate of #52467 i think?

**Comment by Calinou** [comment] 2022-02-02 17:08
Closing in favor of https://github.com/godotengine/godot/issues/52467, which has more information about the issue at hand.

**Closed by Calinou** 2022-02-02 17:08 UTC
Labels: bug, archived, topic:rendering, regression, topic:2d
