### ISSUE TITLE
Tween interpolate_property(...) property is NodePath

### ISSUE THREAD

**Issue by Gallilus** [godotengine/godot#52814] opened 2021-09-18 08:32 UTC
### Godot version

3.4.beta4

### System information

Windows 10

### Issue description

The variable 'property' in Tween.interpolate_property(...) is of type NodePath.
![image](https://user-images.githubusercontent.com/20573784/133881617-0d47fab8-f8ff-4b55-b1d0-372d311c85b5.png)

For visual script users, this gives a usability error because the editor is not able to provide the required property selector.
![image](https://user-images.githubusercontent.com/20573784/133881727-886aa40e-45f3-4dfc-be55-cff0427a2db9.png)

The current workaround is constructing a Nodepath.
![image](https://user-images.githubusercontent.com/20573784/133881810-168a47bd-8d0c-471e-bdf3-a2a5b6e61062.png)

It seems to go all the way down to PropertyTweener.
Maybe someone still knows why it is not using string?
![image](https://user-images.githubusercontent.com/20573784/133882000-d6a95b15-20dc-481e-b6a0-79417bd28c66.png)

### Steps to reproduce

1 Create a scene using VisualScript and a Tween Node.
2 Drag tween node in the script and select interpolate_property
3 Edit property

**Comment by rxlecky** [comment] 2021-10-02 14:44
The reason why it's using `NodePath` instead of `String` is very simple: `NodePath` is data type made specifically for storing paths to nodes and their properties and subresources. So the problem isn't that the function is using `NodePath`, it's that there's no property selector editor provided for that data type.

**Comment by KoBeWi** [comment] 2022-01-30 21:56
Duplicate of #45565

**Closed by KoBeWi** 2022-01-30 21:56 UTC
Labels: bug, topic:visualscript
