### ISSUE TITLE
Camera smoothing makes sprites jitter 

### ISSUE THREAD

**Issue by ArcFutahito** [godotengine/godot#7725] opened 2017-02-04 23:17 UTC
Godot 2.1 official, linux x64

When camera eases out of movement with smoothing enabled (speed 5, camera drag) you can clearly see static sprites jitter. Issue does not affect tilemaps.

**Comment by bojidar-bg** [comment] 2017-02-05 10:01
Duplicate of #2667.

**Closed by bojidar-bg** 2017-02-05 10:01 UTC
