### ISSUE TITLE
Import of gltf model with -convcolonly suffix broken since using bundled VHACD library

### ISSUE THREAD

**Issue by timower** [godotengine/godot#48942] opened 2021-05-21 20:47 UTC
**Godot version:**
Since version 3.2 stable
Broken by commit 5823b5d77d47339c3c981953ca8178e7ef14b6d

**OS/device including version:**
X11/linux

**Issue description:**
When importing a gltf scene with some collision shapes I was getting invalid results since version 3.2. The resulting collision object had only 4 vertices instead of 24 in Godot 3.1. I git bisected the engine to get the commit that causes it.
It seems that moving from QuickHull to VHACD broke it. though this is strange as the shapes are marked convex, so it shouldn't need to be decomposed.

**Steps to reproduce:**
Load the attached project and re-import garage.gltf. The collision shapes attached to ground will have four vertices when they should have 24.

**Minimal reproduction project:**
https://drive.google.com/file/d/1kMw9I5UNrFKsFPi9HHoojlEJ4qPf7fGD/view?usp=sharing

**Comment by Calinou** [comment] 2021-05-21 21:32
> It seems that moving from QuickHull to VHACD broke it. though this is strange as the shapes are marked convex, so it shouldn't need to be decomposed.

`-convcol` will create multiple collision shapes instead of just one, so it has to use VHACD. There's currently no way to force creating only one convex collision shape using QuickHull.

**Comment by timower** [comment] 2021-05-22 10:50
This is indeed a duplicate of #29971 I suspect.

**Comment by Calinou** [comment] 2021-05-22 16:46
Duplicate of #29971.

**Closed by Calinou** 2021-05-22 16:46 UTC
Labels: topic:3d, topic:import
