### ISSUE TITLE
Loss of variable when assigning to null

### ISSUE THREAD

**Issue by DimaKiva** [godotengine/godot#16729] opened 2018-02-15 22:16 UTC
**Godot version:**
3.0

**Steps to reproduce:**
```
ProjectSettings.set('test', null)
print(ProjectSettings.get('test'))
```

WARNING: not found: test

**Comment by akien-mga** [comment] 2018-02-15 22:23
Well, that's a feature no? Otherwise there would be no way to remove variables.

**Comment by groud** [comment] 2018-02-15 22:41
Looks like a normal behaviour, yes.

**Comment by DimaKiva** [comment] 2018-02-16 09:21
In Godot 2x of this there was no

**Comment by DimaKiva** [comment] 2018-02-16 09:30
In simple variables works as expected

```
var test = null
print(test)
```
Null

**Comment by groud** [comment] 2018-02-16 09:32
Yeah, well it's ProjetSettings.get() that displays a warning. Not because, the returned value is bad.

**Comment by Zylann** [comment] 2018-02-17 13:58
That's wether we want to consider `null` as an actual value, rather than the absence of property.
For example, if you have a nullable `Texture` property, setting it to `null` should NOT remove the property, just make it null.
If setting to null removes the property then I would say it's a problem.

**Comment by Zylann** [comment] 2018-02-17 14:04
To clarify: it would be a problem if setting to null makes the property disappear from the ProjectSettings UI.

**Comment by groud** [comment] 2018-02-17 14:38
The problem is that it would require to add a check to verify if the value exist. Instead of allowing nullable values I would just encourage people to define another boolean property to choose whether the texture should be used or not.

**Comment by Zylann** [comment] 2018-02-17 14:46
@groud so... what would be the default value of such properties? How would you even display a Texture property to the user if the editor doesn't show the property at all when null?
Currently the only workaround is to expose a path to a file, because it allows you to set an empty string as default (This sounds a lot like Lua tables, which I personally don't like for this)

**Comment by DimaKiva** [comment] 2018-02-17 16:15
>isn't ProjectSettings.set() calling the Object.set method?

**Comment by groud** [comment] 2018-02-17 16:27
I think we can't manage objects in the project properties. because if you create an object without a dedicated file, how can you edit it ? The project properties are linked to the inspector, so there would be not way to do so. So I guess limiting the properties to basic types and paths is ok.

**Comment by Zylann** [comment] 2018-02-17 16:29
@DimaKiva I'm asking this because the API says you can use `set_setting`. When using `set` you just hope that the ProjectSettings class itself will have such property, unless it overrides _get and _set to re-route the call to `set_setting`.

**Comment by vnen** [comment] 2018-02-17 18:06
@Zylann `set_setting()` is just an alias to `set()`, so it doesn't make difference in this case (and the `_set()` method is overridden to add settings if they don't exist).

Since ProjectSettings replaced the old Globals, it might be desirable to have objects there and make them `null` when not set. I think we could allow `null` as a regular value and add a `remove_setting()` method. Currently it's just a hard check anyway: https://github.com/godotengine/godot/blob/df522cf4e1ee26798359b538f0ad5d0c3116af47/core/project_settings.cpp#L135-L136

**Comment by DimaKiva** [comment] 2018-02-17 19:17
>I think we could allow null

the `none` would look good too :)

**Comment by Calinou** [comment] 2020-08-28 14:41
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!

**Closed by Calinou** 2020-08-28 14:41 UTC
Labels: discussion, topic:core
