### ISSUE TITLE
Warning in output when opening projects: "Attempting to access theme items too early; prefer NOTIFICATION_POSTINITIALIZE and NOTIFICATION_THEME_CHANGED"

### ISSUE THREAD

**Issue by Araraura** [godotengine/godot#80696] opened 2023-08-16 18:50 UTC
### Godot version

4.1.1.stable

### System information

Godot v4.1.1.stable - Windows 10.0.22621 - Vulkan (Compatibility) - AMD Radeon RX 7900 XTX (Advanced Micro Devices, Inc.; 31.0.21023.2010) - AMD Ryzen 9 7950X3D 16-Core Processor (32 Threads)

### Issue description

When opening projects from the project list, the output in the editor will print the following warning:

```
scene/gui/control.cpp:2522 - Attempting to access theme items too early; prefer NOTIFICATION_POSTINITIALIZE and NOTIFICATION_THEME_CHANGED
```

I could not get this to replicate when creating completely brand new projects, but every other existing project that I have on my disk prints out that warning, regardless of the renderer.

![image](https://github.com/godotengine/godot/assets/25017422/e4442777-45e1-49c3-882f-2faa22edca54)

### Steps to reproduce

1. Download the reproduction project and unzip it
2. Open the project in 4.1.1
3. Open the output menu

### Minimal reproduction project

[Kenney2023Game.zip](https://github.com/godotengine/godot/files/12362579/Kenney2023Game.zip)

**Comment by sydist** [comment] 2023-09-23 06:36
Seems to happen only when opening Tilemap nodes or tileset resources

**Comment by Araraura** [comment] 2023-09-23 11:19
> Seems to happen only when opening Tilemap nodes or tileset resources

That seems to be it. I had a tileset scene open and after closing it and restarting the project, the warning no longer appears

**Comment by YuriSizov** [comment] 2023-09-30 18:26
I can confirm this in 4.1.1 and 4.1.2.rc1, but doesn't seem to happen in 4.2. Since this is a minor issue, we can consider it closed as fixed in the next minor release.

**Closed by YuriSizov** 2023-09-30 18:26 UTC
Labels: bug, topic:gui
