### ISSUE TITLE
Viewportreading on Gradient in Editor

### ISSUE THREAD

**Issue by MiroloTech** [godotengine/godot#72668] opened 2023-02-03 15:26 UTC
### Godot version

4.0.16

### System information

Windows 10 ; Nvidea RTX 360 Ti

### Issue description

While editing my project I encountered glitching of the Gradient2D component in my project, where it just read part of the screan into the gradient
![BugGodot4](https://user-images.githubusercontent.com/119061230/216641423-b21aabfc-55d3-441f-a10f-3cb002763b4c.png)

### Steps to reproduce

i don't know, it just happened,

### Minimal reproduction project

Editor issue, so...

**Comment by Calinou** [comment] 2023-02-03 15:30
@MiroloTech Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

**Comment by MiroloTech** [comment] 2023-02-04 16:27
Hi

I deem a minimal reproduction project not useful since it would require
more time and resources to send that, than to recreate the issue. I did
however manage to find the steps to recreate this bug:

1. Add 'TextureRect' to a new Control scene and set the layout to 'Full
Rect'
2. set 'TextureRect' filtermode to 'linear mipmap'
3. Add new 'GradientTexture2D' as texture
4. set texture fillmode to radial
5. remove 'gradient' from 'GradientTexture2D'
6. click on the texture of 'TextureRect' to close gradient control panel

Now everytime a hover popup appears, the texture goes from white to black.
Also this seems to be inconsistent but sometimes when you, as a 7th step,
click on the root 'Control node' every popup will appear as the texture of
the 'TextureRect'.

I hope that this addition is enough to remove this bug and that this was
helpful.

**Comment by AThousandShips** [comment] 2024-07-29 17:29
Closing due to lack of MRP, if you upload one this can be reopened

**Closed by AThousandShips** 2024-07-29 17:29 UTC
Labels: bug, topic:rendering, needs testing, topic:2d
