### ISSUE TITLE
Change pressed value in Button via script with Toggle Mode enabled, triggering toggled signal

### ISSUE THREAD

**Issue by artemtech** [godotengine/godot#36041] opened 2020-02-09 01:17 UTC
**Godot version: 3.2-stable**

**OS/device including version: ArchLinux**

**Issue description:**
Just working with pressed value, my Button with enabled toggle mode, it emitting toggled signal when i change the pressed value. I don't know whether it is a bug or not, but it only happen in 3.2-stable, in previous version of Godot i'm not facing this issue. 
when user click my toggle button, it will save the data to database that current level is marked, then go to the next scene. when instancing scene, i check the instanced scene whether it has a gamedata or not, if present set the pressed value to true, otherwise set it to false. BUT, when setting pressed value, the button also emitting signal :(

SO, if it is not a bug, how i can set ONLY pressed value of Toggled Button from a script WITHOUT emitting its signal ?

**Steps to reproduce:**
just run my sample below, or you can make your own scene with:
- Make 2 buttons, 
  - first button (Button1) as `Button` with `Toggle Mode` enabled and connect its toggled signal. 
  - Second button (Button2) as `Button` for switching pressed value of (Button1) from script 
- Run in 3.2 then compare it with 3.1.2

**Minimal reproduction project:**
`SEE Level.gd on Line 29-36`
[ToggleButtonBug.zip](https://github.com/godotengine/godot/files/4176308/ToggleButtonBug.zip)
Expected result in minimal reproduction project: 
when set pressed value, the toggled and marked signals shouldn't emitted like in 3.1.2

**Comment by Keetz** [comment] 2020-02-18 09:46
I am facing the same problem here.
I also have a case where I just want to set the toggle mode of a button without actually registering it as a click, but in 3.2 this doesn't seem possible.

I think it is a good think that it actually emits the signal now, it makes a lot of sense, and makes it possible to actually press a button from script.

At the same time I could really use a way of setting the pressed property without any signals are emitted, and I can't find a way to do that any more.

**Comment by KoBeWi** [comment] 2020-03-19 01:36
Duplicate of #33422

**Closed by KoBeWi** 2020-03-19 01:36 UTC
