### ISSUE TITLE
Cannot assign a custom color to a label after assigning it a theme

### ISSUE THREAD

**Issue by radicaled** [godotengine/godot#7001] opened 2016-10-31 19:30 UTC
**Operating system or device - Godot version:**
Linux, Godot 2.1

**Issue description** (what happened, and what was expected):
I assigned a label a custom theme, and then clicked away from the node in the editor. When I came back to the node, the "custom color" section in the inspector was gone. **However, any animations I set up that changed custom color still worked fine**, even though I couldn't see custom color in the inspector anymore.

**Steps to reproduce:**

Make a scene structure like this:
```
Node2D
  Label
```

1.) Create a new theme for Label via inspector
2.) Select another node
3.) Select "label" again -- custom color, etc, unavailable.

Encountered when I tried replicating an arcadey color cycle effect for using AnimationPlayer + a Label's custom color field.

**Comment by puppetmaster-** [comment] 2016-10-31 20:41
I don't know if it's a feature or a bug, but when you remove the theme the color is available.
When you set the theme on parent then you get both.

**Comment by bojidar-bg** [comment] 2016-11-01 11:12
I would rather tag is as a usability "bug", since it is pretty backwards sometimes (especially when you set a theme just so that child nodes have the same font).

**Comment by Noshyaar** [comment] 2018-04-07 06:10
First of all thank you for your report and sorry for the delay.

We released Godot 3.0 in January 2018 after 18 months of work, fixing many old issues either directly, or by obsoleting/replacing the features they were referring to.

We still have hundreds of issues whose relevance/reproducibility needs to be checked against the [current stable version](https://godotengine.org/download), and that's where you can help us.
**Could you check if the issue that you described initially is still relevant/reproducible in Godot 3.0 or any newer version, and comment about it here?**

For bug reports, please also make sure that the issue contains detailed steps to reproduce the bug and, if possible, a zipped project that can be used to reproduce it right away. This greatly speeds up debugging and bugfixing tasks for our contributors.

Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

Thanks in advance.

*Note: This message is being copy-pasted to many "stale" issues (90+ days without activity). It might happen that it is not meaningful for this specific issue or appears oblivious of the issue's context, if so please comment to notify the Bugsquad about it.*

**Comment by akien-mga** [comment] 2018-11-14 19:57
Fixed by 88bfb27a.

**Closed by akien-mga** 2018-11-14 19:57 UTC
Labels: bug, junior job, topic:editor, usability
