### ISSUE TITLE
Cannot compile successfully on 4.2-dev6 on MacOS

### ISSUE THREAD

**Issue by cyberpsyche** [godotengine/godot#82835] opened 2023-10-05 08:14 UTC
### Godot version

Godot 4.2 dev6

### System information

MacOS 10.15.7 (19H2) Intel Iris Graphics 6100 1536 MB

### Issue description

When compile dev6 code, I got this error message:

```
platform/macos/display_server_macos.mm:193:93: error: multiple methods named 'layer' found with mismatched result, parameter type or attributes
                        Error err = gl_manager_angle->window_create(window_id_counter, nullptr, (__bridge void *)[wd.window_view layer], p_rect.size.width...
                                                                                                                 ^~~~~~~~~~~~~~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk/System/Library/Frameworks/AppKit.framework/Headers/NSView.h:255:39: note: 
      one possibility
@property (nullable, strong) CALayer *layer API_AVAILABLE(macos(10.5));
                                      ^~~~~
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk/System/Library/Frameworks/QuartzCore.framework/Headers/CAMetalLayer.h:37:35: note: 
      also found
@property(readonly) CAMetalLayer *layer;
                                  ^~~~~
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk/System/Library/Frameworks/AVFoundation.framework/Headers/AVMovieTrack.h:180:33: note: 
      also found
@property (nonatomic) NSInteger layer;
                                ^~~~~
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk/System/Library/Frameworks/QuartzCore.framework/Headers/CARemoteLayerClient.h:39:38: note: 
      also found
@property(nullable, strong) CALayer *layer;
                                     ^~~~~
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk/System/Library/Frameworks/QuartzCore.framework/Headers/CARenderer.h:68:38: note: 
      also found
@property(nullable, strong) CALayer *layer;
                                     ^~~~~

```

Hot to resolve it ?

### Steps to reproduce

no content here

### Minimal reproduction project

no content here

**Comment by bruvzg** [comment] 2023-10-05 08:32
Can't reproduce with Xcode 15, likely an issue with old Xcode/SDK.

Probably can be fixed by replacing this line with:
```obj-c++
CALayer *layer = [(NSView *)wd.window_view layer];
Error err = gl_manager_angle->window_create(window_id_counter, nullptr, (__bridge void *)layer, p_rect.size.width, p_rect.size.height);
```

**Comment by cyberpsyche** [comment] 2023-10-05 14:26
@bruvzg Your code works. Thank you~

**Comment by fire** [comment] 2023-10-05 19:09
Can you close if this fixes your issue?

**Closed** 2023-10-05 21:05 UTC
Labels: bug, platform:macos, topic:buildsystem
