### ISSUE TITLE
Godot_v3.2-rc3 -> Crash Video Driver on Edit/Run a GLES3 Project!

### ISSUE THREAD

**Issue by TheNeedJedi** [godotengine/godot#35528] opened 2020-01-24 17:38 UTC
**Godot version:**godot_v3.2-rc3_win32

**OS/device including version:**Windows_7 32 bits AMD VISION 

**Issue description:** When creating or editing a project in GLES3, the video driver reports an error giving temporary problems on the screen such as distortion and black screen. Soon the engine stops working and never comes back

**Steps to reproduce:**Open Engine ...rc3 > Edit/Create a project in GLES3 > Wait Splash Screen

**Minimal reproduction project:**

**Comment by clayjohn** [comment] 2020-01-24 17:49
It sounds like your video card may not properly support Open GL 3.3 (which is what GLES3 uses). 

Did you have this same issue on earlier version of Godot e.g. 3.1.2?

**Comment by TheNeedJedi** [comment] 2020-01-24 18:18
no

**Comment by clayjohn** [comment] 2020-01-24 18:24
Could you post what hardware you are using. Specifically your CPU and GPU?

**Comment by TheNeedJedi** [comment] 2020-01-24 18:25
can you tell me where i get this information from?

**Comment by clayjohn** [comment] 2020-01-24 18:28
It is your hardware information. Should be under "system properties" or something similarly named.

**Comment by clayjohn** [comment] 2020-01-24 18:29
Ah, just noticed this is a duplicate of your bug report from 4 days ago (https://github.com/godotengine/godot/issues/35366). Please do not open multiple bug reports for the same issue.

**Closed by clayjohn** 2020-01-24 18:29 UTC
Labels: bug, crash, topic:rendering

**Comment by TheNeedJedi** [comment] 2020-01-24 18:30
OK

**Comment by TheNeedJedi** [comment] 2020-01-24 18:35
![2020-01-24-15-34-02](https://user-images.githubusercontent.com/53179496/73094305-1332e680-3ebf-11ea-992f-d7bed993206d.png)
