### ISSUE TITLE
16-bit textures are not displayed correctly

### ISSUE THREAD

**Issue by VitaZheltyakov** [godotengine/godot#40451] opened 2020-07-16 18:27 UTC
**Godot version:**
Godot 3.2.2

**OS/device including version:**
Windows, GLES2, GLES3

**Issue description:**
Any 16-bit textures are displayed incorrectly - look blown out.
Below are two textures. The left texture is 8-bit. The right texture is 16-bit. The difference is obvious.
![Снимок](https://user-images.githubusercontent.com/5693437/87707406-1ba31480-c7b2-11ea-9622-26661fcd9c58.JPG)

**Steps to reproduce:**
Use any 16-bit texture in your project.

**Minimal reproduction project:**
[Test.zip](https://github.com/godotengine/godot/files/4933369/Test.zip)

**Comment by Gerarama** [comment] 2020-07-16 18:29
Try changing the tonemap to filmic and see if the problem still.

![Annotation 2020-07-16 192951](https://user-images.githubusercontent.com/61591052/87708445-0a9ed700-c7a3-11ea-8157-eb5868568627.png)

**Comment by JohanAR** [comment] 2020-07-17 07:26
When you say "any 16-bit texture", did you use only 16-bit PNGs or did you try other file formats too? Because Godot would assume 16-bit PNG were in linear color space and try to convert them to sRGB on import.

Probably duplicate of #37220, they talk about normal maps but if it's about 16-bit PNG then it is the same issue. Fixed on git but not available in any release yet.

**Comment by Calinou** [comment] 2020-07-30 08:29
The image in the MRP is indeed a 16-bit PNG
```
❯ identify *.png
16-bit.png PNG 100x94 100x94+0+0 16-bit sRGB 17.7KB 0.000u 0:00.000
8-bit.png[1] PNG 100x94 100x94+0+0 8-bit sRGB 15.4KB 0.000u 0:00.000
...
```

Closing as a duplicate of https://github.com/godotengine/godot/issues/37220, which was fixed by https://github.com/godotengine/godot/pull/40242.

**Closed by Calinou** 2020-07-30 08:29 UTC
