### ISSUE TITLE
Default values on exported properties do not work

### ISSUE THREAD

**Issue by Ev01** [godotengine/godot#74342] opened 2023-03-04 07:05 UTC
### Godot version

4.0

### System information

Windows 10

### Issue description

When I set a default value on an exported property, the default value shows up in the inspector as expected, but when you run the game it defaults to 0.
```
# Default value in inspector is 5
var _foo: int
@export var foo: int = 5:
  get:
    return _foo
  set(value):
    _foo = foo


func _ready():
  # prints 0
  print(foo)
```

However, if I initialize the backing field instead, the default value works in-game, but it defaults to 0 in the inspector:
```
# Default value in the inspector is 0
var _foo: int = 5
@export var foo: int:
  get:
    return _foo
  set(value):
    _foo = foo


func _ready():
  # prints 5
  print(foo)
```

The only way for both the default in-game value and the default inspector value to work is to initialize both of them to the same value, but this seems very error-prone because it would produce unexpected results if you accidentally set them to different values.

### Steps to reproduce

See above.

### Minimal reproduction project

[PropertyBug.zip](https://github.com/godotengine/godot/files/10887677/PropertyBug.zip)

**Comment by dalexeev** [comment] 2023-03-04 07:56
This is expected. Without `@tool`, the script is not executed, so only constant initializers will show up in the Inspector. You can use a constant if you want to avoid duplicate the value:

```gdscript
const FOO_INIT_VALUE = 5
var _foo: int = FOO_INIT_VALUE
@export var foo: int = FOO_INIT_VALUE:
    get:
        return _foo
    set(value):
        _foo = foo
```

Duplicate of #71091.

**Comment by Calinou** [comment] 2023-03-21 18:41
- Duplicate of https://github.com/godotengine/godot/issues/71091.

**Closed by Calinou** 2023-03-21 18:41 UTC
