### ISSUE TITLE
Game crash when minimizing a sub-window on Windows (crash in VulkanContext::prepare_buffers) (DisplayServer regression)

### ISSUE THREAD

**Issue by Xwdit** [godotengine/godot#56901] opened 2022-01-18 13:42 UTC
### Godot version

4.0.dev(366d3930ac)

### System information

Windows11, Nvidia RTX 2060, Vulkan

### Issue description

Same issue with #37327, but this happened when minimizing a sub-window created by a game in windows.

Swapchain is indeed NULL before the call to fpAcquireNextImageKHR just like what happened in this discussion:
https://github.com/godotengine/godot/issues/37327#issuecomment-655322717

### Steps to reproduce

1. Run a game which create a sub-windows
2. Minimize the sub-windows
3. Game crash

**Comment by TechnoPorg** [comment] 2022-01-26 16:53
I think this is a duplicate of #51537. It happens at the same location, on the same platform.

**Closed** 2022-01-26 17:04 UTC
Labels: bug, platform:windows, topic:porting, confirmed, crash, regression
