### ISSUE TITLE
Ctrl+D doesn't duplicates objects, but duplicating from right click menu works but Ctrl+D is faster

### ISSUE THREAD

**Issue by ScintillationGamesOfficial** [godotengine/godot#45500] opened 2021-01-27 12:27 UTC
**Godot version:**
3.2.3 stable.mono

**OS/device including version:**
Windows10/OpenGLES3

**Issue description:**
I can't duplicate with Ctrl+D. Maybe I am doing wrong

**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by KoBeWi** [comment] 2021-01-27 12:31
Any more information? Is Ctrl+D correctly assigned in editor settings? How it doesn't work? It does nothing or is there an error? Does it happen in empty scenes/projects? (e.g. shader editor might hijack the shortcut)

**Comment by BeayemX** [comment] 2021-01-30 03:12
Ctrl+D will be hijacked from the script editor if it is visible and the current line will be duplicated instead.

This affects the scene-tree view and the file system tree.

Happens with current 3.2 master 19ff78c52881012b076622dbee04f3dc645ccc03

**Comment by KoBeWi** [comment] 2021-01-30 15:07
This is fixed on master, make sure you have scene tree dock focused when duplicating nodes.

Also if this is what the issue is about then it's duplicate of #43976

**Comment by ScintillationGamesOfficial** [comment] 2021-01-31 05:02
I click on the object i want to duplicate but doesn't do i may show you my recording but github isn't providing the option to upload it

**Comment by KoBeWi** [comment] 2021-01-31 09:02
>  click on the object i want to duplicate but doesn't do

But do you have the shader editor open? If yes, that it's a known issue and can be closed. Also I said it's fixed in 4.0 ([you can get a nightly build here](https://hugo.pro/projects/godot-builds/)).

> github isn't providing the option to upload it

It tells you under comment box how to upload.

**Comment by KoBeWi** [comment] 2021-03-07 21:43
Closing due to lack of update. Please comment if you can still reproduce this issue in Godot 3.2.4 (rc) or newer.

**Closed by KoBeWi** 2021-03-07 21:43 UTC
Labels: topic:editor, usability
