### ISSUE TITLE
Blured text in Dock

### ISSUE THREAD

**Issue by Janglee123** [godotengine/godot#37275] opened 2020-03-24 11:59 UTC
**Godot version:** 20edf69f96160fcf7c0ea2449f4daf50f572ce99

**OS/device including version:** Linux, Intel 620

**Issue description:**
Scroll down dock and text becomes blurred. Text looks fine if the scrollbar is on top or bottom.  
![Screenshot from 2020-03-24 17-23-31](https://user-images.githubusercontent.com/29702428/77423101-a8395980-6df4-11ea-8291-b708a996896d.png)

**Steps to reproduce:**
1. Open the editor  
2. select node
3. scroll inspector dock 

**Minimal reproduction project:**
NA

**Comment by Ev1lbl0w** [comment] 2020-03-24 13:57
Never happened to me, that's odd. Can you give us more info? *(such as graphics card and driver, resolution, does anything similar happen with other applications, does it also happen on godot stable, etc...)*

**Comment by bojidar-bg** [comment] 2020-03-24 14:14
Duplicate of #36087?

**Comment by Calinou** [comment] 2020-03-24 14:15
This is a duplicate of #36087 indeed.

**Closed by Calinou** 2020-03-24 14:15 UTC
