### ISSUE TITLE
GDScript 2.0: Call `class_name` script constructor only inside `Built-in script` cause `Nonexistent function 'new' in base 'GDScript'`

### ISSUE THREAD

**Issue by sent44** [godotengine/godot#59601] opened 2022-03-27 21:39 UTC
### Godot version

4.0 alpha 5

### System information

Windows 10

### Issue description

If call `.new()` of the `class_name` script inside node built-in script, the error `Nonexistent function 'new' in base 'GDScript'.` will be produce. But if also call it in non built-in script, that error is somehow gone.

### Steps to reproduce

- Create a file script and give it a `class_name`.
- Attach script as built-in script to node.
- Call the file script constructor (`.new()`) in built-in script.
- Run the game.

\*Don't call the class constructor inside other file script (that attach to node) or the issue will somehow not reproduce.\*

### Minimal reproduction project

[ClassName.zip](https://github.com/godotengine/godot/files/8358530/ClassName.zip)

**Comment by Calinou** [comment] 2022-03-27 21:51
Duplicate of https://github.com/godotengine/godot/issues/51538.

**Closed by Calinou** 2022-03-27 21:51 UTC
Labels: bug, topic:gdscript, regression
