### ISSUE TITLE
Android Godot version bug

### ISSUE THREAD

**Issue by Raffa064** [godotengine/godot#67363] opened 2022-10-13 18:49 UTC
### Godot version

3.5.1.stable

### System information

Android 10, 64bits

### Issue description

The godot version for aandroid have a error that crash or simply exit when you try to back to the editor after runned the project.

I haven't a computer and I depend of these type of app to code...

Other problem that i have encontred is the size of the red dot of the editor to resize collision boxes, is very small to a android device.

### Steps to reproduce

I think that the crash/exit problem after run project can be easyly solved be puttiing a Try-catch, or maybe a onBackButtonPressed callback of the android API to prevent the unexpected exits when user try to back to editor

**Comment by Calinou** [comment] 2022-10-13 20:31
Duplicate of https://github.com/godotengine/godot/issues/61611.

**Closed by Calinou** 2022-10-13 20:31 UTC
