### ISSUE TITLE
[C# 4.0 beta 16] Referencing GPU Particles2D node returns exception and null value (Regression)

### ISSUE THREAD

**Issue by SeventySixx** [godotengine/godot#72306] opened 2023-01-29 12:09 UTC
### Godot version

v4.0.beta16.mono.official [518b9e580]

### System information

Windows 10

### Issue description

Hello,

From 4.0 beta 16, in C# the name of the class GPUParticle2D has been refactored to  GpuParticle2D. Not sure if this is the cause of the issue.

Now when  I reference the GpuParticle2D node, a null value and an exception are returned.

**Scene Structure:**
![image](https://user-images.githubusercontent.com/83183868/215324240-0c37022a-6629-451e-aa7d-0271b99bf372.png)

**Code:**
![image](https://user-images.githubusercontent.com/83183868/215324337-8533632c-c739-41fa-8f03-b278e20a9b55.png)

**Returned Exception:**
`
ERROR: System.InvalidOperationException: Wrapper class not found for type: GPUParticles2D
   at Godot.Bridge.ScriptManagerBridge.CreateManagedForGodotObjectBinding(godot_string_name* nativeTypeName, IntPtr godotObject) in /root/godot/modules/mono/glue/GodotSharp/GodotSharp/Core/Bridge/ScriptManagerBridge.cs:line 101
   at: godotsharp_pusherror (modules/mono/glue/runtime_interop.cpp:1219)
ERROR: Parameter "strong_gchandle.value" is null.
   at: setup_csharp_script_binding (modules/mono/csharp_script.cpp:1229)
ERROR: Condition "!script_binding.inited" is true. Returning: { nullptr }
   at: godotsharp_internal_unmanaged_get_instance_binding_managed (modules/mono/glue/runtime_interop.cpp:234)
ERROR: System.InvalidOperationException: Wrapper class not found for type: GPUParticles2D
   at Godot.Bridge.ScriptManagerBridge.CreateManagedForGodotObjectBinding(godot_string_name* nativeTypeName, IntPtr godotObject) in /root/godot/modules/mono/glue/GodotSharp/GodotSharp/Core/Bridge/ScriptManagerBridge.cs:line 101
   at: godotsharp_pusherror (modules/mono/glue/runtime_interop.cpp:1219)
ERROR: Parameter "strong_gchandle.value" is null.
   at: setup_csharp_script_binding (modules/mono/csharp_script.cpp:1229)
ERROR: Condition "!script_binding.inited" is true. Returning: { nullptr }
   at: godotsharp_internal_unmanaged_instance_binding_create_managed (modules/mono/glue/runtime_interop.cpp:247)
ERROR: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
`

### Steps to reproduce

Add a GpuParticles2D Node in a scene and get the reference to it from code

### Minimal reproduction project

N/A

**Comment by wamfish** [comment] 2023-01-30 01:38
I have the same type of error with GPUParticles3D as well.

**Comment by RedworkDE** [comment] 2023-01-31 16:54
Duplicate of https://github.com/godotengine/godot/issues/72203
Already fixed by https://github.com/godotengine/godot/pull/72205

**Closed** 2023-01-31 18:02 UTC
