### ISSUE TITLE
Godot 4 on Android crashes when returning / Doesn't do anything when running faulty code

### ISSUE THREAD

**Issue by Liquidful** [godotengine/godot#65966] opened 2022-09-17 05:55 UTC
### Godot version

4.0 beta

### System information

Android 11, Adreno 640, Vulkan mobile

### Issue description

As title says, Godot crashes when trying to return from the testing phase:

https://user-images.githubusercontent.com/34092413/190842530-de04f0fd-73d7-4f6f-99aa-153bc5a82cf2.mp4

And it doesn't quit the testing phase when faulty code is inserted:

https://user-images.githubusercontent.com/34092413/190842569-0cebcc0e-397b-4071-8d2c-7182a16af0fc.mp4

The expected behaviour would be:

- The program would continue to run after returning
- The program quits the testing phase when faulty code is inserted, with an error in the logs as it is with the desktop version

### Steps to reproduce

- Make a project, set it to use Vulkan mobile
- Write some functioning code and some faulty code
- Try to return

### Minimal reproduction project

[MinimalReproductionProject.zip](https://github.com/godotengine/godot/files/9591035/MinimalReproductionProject.zip)

**Comment by randyyaj** [comment] 2022-11-24 13:53
I am also experiencing this issue on a Samsung s8+ tablet. Whenever the back button is pressed during the test window or the test window is closed via samsung dex. The whole Godot editor is also closed and would have to be reopen.

**Comment by Calinou** [comment] 2022-11-24 15:09
Duplicate of https://github.com/godotengine/godot/issues/61611.

**Closed by Calinou** 2022-11-24 15:09 UTC
Labels: bug, platform:android, topic:editor, crash
