### ISSUE TITLE
Scene dock shortcuts not working.

### ISSUE THREAD

**Issue by avencherus** [godotengine/godot#21171] opened 2018-08-19 00:29 UTC
Using Win10 and a 64-bit build I did earlier tonight from the master branch, I noticed I can't move nodes around in the tree using Ctrl + UP / DOWN.

It appears they're working fine in 3.0.6, so maybe this is a regression from:  https://github.com/godotengine/godot/issues/17633

My bindings appear to be intact, and haven't yet run across other shortcuts that aren't working.

![godot 64_8_18_2018-08-19_03-18-29](https://user-images.githubusercontent.com/13004169/44304262-a75e5d00-a35f-11e8-9a9a-098d59afbf26.png)

**Comment by reduz** [comment] 2018-09-07 22:39
duplicate of #17633

**Closed by reduz** 2018-09-07 22:39 UTC
Labels: bug, topic:editor
