### ISSUE TITLE
Can't save and load .glb/.dae at runtime

### ISSUE THREAD

**Issue by DominicSina** [godotengine/godot#17337] opened 2018-03-07 14:47 UTC
**Godot version:**
Godot 3.0.2-stable

**OS/device including version:**
OS: Windows 10 Home (64-bit)

**Issue description:**
I am getting a scene file (.glb/.dae) through an http request, save it and then load it. I get this error though when I try switch to this new scene. 
 
`**ERROR**: No loader found for resource: res://CopyScene.glb`

It works for .tscn scenes but for the sake of simplifying the workflow it makes sense that this should also work for files directly exported from Blender. Something like what is outlined for .png files [here](https://github.com/godotengine/godot/issues/4024) might be very nice for scenes as well.

**Steps to reproduce:**
It may a feature that's mostly required when receiving external scene files at runtime through e.g. the web but to get the error above it's enough to copy an existing scene file and then try to load it at runtime.
The reproduction project does exactly that, simply run it in the editor. The error will not stop the program but it can be found in the error list in the debugger.

The second time you run it, that error will not show up since the copied scene file was created in the previous run. Delete it before rerunning to get the error again.

**Minimal reproduction project:**

[OnTheFlyImport.zip](https://github.com/godotengine/godot/files/1789492/OnTheFlyImport.zip)

**Comment by vnen** [comment] 2018-03-07 16:07
Those files need to be imported before being loaded and the importer is only available in the editor, so it won't work on the exported game.

**Comment by hpvb** [comment] 2018-03-08 12:39
I'm closing this as it is not a bug but a design decision.

**Closed by hpvb** 2018-03-08 12:39 UTC
Labels: archived, feature proposal

**Comment by wotori** [comment] 2022-03-10 10:27
> Those files need to be imported before being loaded and the importer is only available in the editor, so it won't work on the exported game.

So It is impossible to create an APP where user can load dinamical updated 3D models from server at runtime?
there is such a feature as a [plugin](https://www.unrealengine.com/marketplace/en-US/product/runtimemeshimportexport) for UE4

**Comment by fire** [comment] 2023-04-20 22:00
I suspect that both UE4 and Unity's gltffast were inspired by the earlier ability of Godot Engine to runtime import/export scenes.

https://github.com/godotengine/godot-docs/issues/6385
