### ISSUE TITLE
Node naming conflict when adding node to base scene with name that is already used in inherited scene

### ISSUE THREAD

**Issue by BeayemX** [godotengine/godot#35032] opened 2020-01-12 02:01 UTC
**Godot version:**
b563de702c7a0dbb5bbf9507c684e3deadc95134

**Issue description** / **Steps to reproduce:**
You have two scenes: `Base.tscn` and `Inherited.tscn` that look like this
![image](https://user-images.githubusercontent.com/3453076/72212952-f5d94200-34e6-11ea-9c67-70cc07d78d59.png)

![image](https://user-images.githubusercontent.com/3453076/72212956-0093d700-34e7-11ea-892c-ea0164d508f3.png)

When adding a node to the base scene with a name that is already used in the inherited scene, and saving the project. The node will be added to the inherited scene. Which will lead to two nodes having the same name. It will look like this:

![image](https://user-images.githubusercontent.com/3453076/72212962-11444d00-34e7-11ea-9bac-29fcf6b16054.png)

![image](https://user-images.githubusercontent.com/3453076/72212966-1acdb500-34e7-11ea-8c59-1cc11732b641.png)

When selecting one of the duplicate nodes, both will be selected

**Comment by volzhs** [comment] 2020-01-12 02:08
looks duplicate of #26390

**Comment by KoBeWi** [comment] 2020-01-12 02:33
Duplicate of #26390

**Closed by KoBeWi** 2020-01-12 02:33 UTC
