### ISSUE TITLE
Dragging files in the filesystem docker scrolls the filesystem docker as well

### ISSUE THREAD

**Issue by QbieShay** [godotengine/godot#44343] opened 2020-12-13 13:45 UTC
**Godot version:**
4.0 12/12/2020 `0762484473c1330c5d524d5cc3644d5e2b2e557c`

**OS/device including version:**
Linux 5.9.13-arch1-1
i3 window manager
If someone can point me to the pieces of code that handle scroll, I can try and fix it myself :D

**Issue description:**
When dragging a file in the filesystem docker, the docker scrolls, making it possible to release files in a different location only by using the mouse wheel and a bit of good reflexes.
Additionally, when releasing the drag, the docker keeps scrolling.

**Steps to reproduce:**
1. have enough items in the filesystem docker to have a scrollbar
2. drag a file

https://gfycat.com/vainmistygoosefish

**Comment by EricEzaM** [comment] 2020-12-13 14:30
This is an issue present in all `Tree` controls. See the InputMapEditor for example. Somehow the tree control is treating all mouse click+drag input as wanting to scroll the container.

Unfortunately `tree.cpp` is a bit hard to decipher so I haven't been able to see quick fix, but I haven't given a lot of time to this issue.

**Comment by YeldhamDev** [comment] 2021-02-11 23:02
Duplicate of #38665.

**Closed by YeldhamDev** 2021-02-11 23:02 UTC
Labels: bug, topic:editor, topic:gui
