### ISSUE TITLE
Random crash on tooltip in editor settings

### ISSUE THREAD

**Issue by RedMser** [godotengine/godot#63553] opened 2022-07-27 19:23 UTC
### Godot version

4.0.dev (222e489d)

### System information

Windows 10, single-window mode

### Issue description

I was editing Editor Settings (Text Editor -> Theme) when I got this crash:

```
================================================================      
CrashHandlerException: Program crashed
Engine version: Godot Engine v4.0.alpha.custom_build (222e489dfdafedff2f003142e268611ff12c0643)
Dumping the backtrace. Please include this when reporting the bug to the project developer.
[0] mtx_do_lock (d:\agent\_work\4\s\src\vctools\crt\github\stl\src\mutex.cpp:91)
[1] mtx_do_lock (d:\agent\_work\4\s\src\vctools\crt\github\stl\src\mutex.cpp:91)
[2] std::_Mutex_base::lock (C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30037\include\mutex:51)       
[3] MutexImpl<std::recursive_mutex>::lock (D:\Sources\godot\core\os\mutex.h:48)
[4] MutexLock<MutexImpl<std::recursive_mutex> >::MutexLock<MutexImpl<std::recursive_mutex> > (D:\Sources\godot\core\os\mutex.h:67)
[5] SceneTree::queue_delete (D:\Sources\godot\scene\main\scene_tree.cpp:1075)
[6] Node::queue_delete (D:\Sources\godot\scene\main\node.cpp:2638)    
[7] Viewport::_gui_cancel_tooltip (D:\Sources\godot\scene\main\viewport.cpp:1128)
[8] Viewport::_gui_input_event (D:\Sources\godot\scene\main\viewport.cpp:1661)
[9] Viewport::push_input (D:\Sources\godot\scene\main\viewport.cpp:2721)
[10] Window::_window_input (D:\Sources\godot\scene\main\window.cpp:1021)
[11] Viewport::_sub_windows_forward_input (D:\Sources\godot\scene\main\viewport.cpp:2683)
[12] Viewport::push_input (D:\Sources\godot\scene\main\viewport.cpp:2706)
[13] Window::_window_input (D:\Sources\godot\scene\main\window.cpp:1021)
[14] call_with_variant_args_helper<Window,Ref<InputEvent> const &,0> (D:\Sources\godot\core\variant\binder_common.h:262)
[15] call_with_variant_args<Window,Ref<InputEvent> const &> (D:\Sources\godot\core\variant\binder_common.h:377)
[16] CallableCustomMethodPointer<Window,Ref<InputEvent> const &>::call (D:\Sources\godot\core\object\callable_method_pointer.h:105)
[17] Callable::call (D:\Sources\godot\core\variant\callable.cpp:51)   
[18] DisplayServerWindows::_dispatch_input_event (D:\Sources\godot\platform\windows\display_server_windows.cpp:2079)
[19] DisplayServerWindows::_dispatch_input_events (D:\Sources\godot\platform\windows\display_server_windows.cpp:2044)
[20] Input::_parse_input_event_impl (D:\Sources\godot\core\input\input.cpp:663)
[21] Input::flush_buffered_events (D:\Sources\godot\core\input\input.cpp:889)
[22] DisplayServerWindows::process_events (D:\Sources\godot\platform\windows\display_server_windows.cpp:1786)
[23] OS_Windows::run (D:\Sources\godot\platform\windows\os_windows.cpp:777)
[24] widechar_main (D:\Sources\godot\platform\windows\godot_windows.cpp:179)
[25] _main (D:\Sources\godot\platform\windows\godot_windows.cpp:201)
[26] main (D:\Sources\godot\platform\windows\godot_windows.cpp:215)
[27] WinMain (D:\Sources\godot\platform\windows\godot_windows.cpp:229)[28] __scrt_common_main_seh (d:\agent\_work\4\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288)[29] BaseThreadInitThunk
-- END OF BACKTRACE --
================================================================
```

Since I can't reproduce, I hope the backtrace is enough to give an idea on what happened.

### Steps to reproduce

I don't have exact reproduction steps :(
I believe what I did to make it crash involved:

- In debug build, the editor can freeze for a few seconds when trying to edit a color setting.
- I scrolled with mouse wheel around the time that it crashed.
- Not sure if I opened or closed a color selector at that time, but it was either of these.

**Comment by Calinou** [comment] 2022-07-27 19:50
Duplicate of https://github.com/godotengine/godot/issues/59798.

**Closed by Calinou** 2022-07-27 19:50 UTC
Labels: bug, topic:editor, confirmed, crash, topic:gui
