### ISSUE TITLE
Separate collision layers and collision masks for RayCast2D

### ISSUE THREAD

**Issue by davidbejlej** [godotengine/godot#19219] opened 2018-05-28 13:21 UTC
Godot version: 3.0.2

OS: Windows 10

Sorry if it doesn't fit here, I'll try to keep it short.
2D platformer shooter. I use RayCast2D in bullet scene so I can get collision point (to instance animation in place where bullet the hits) but if I shoot few bullets at once (shotgun weapon) RayCasts detect each other. I set meta for bullet scene and use "has_meta" so bullets don't react to each other, but if they overlap and one of them is being freed (queue_free) I get "Attempt to call function "has_meta" in base "null instance" on a null instance".

Anyway, the point is - I think it would be useful if RayCast2D had separate collision layers and collision masks like Area2D for example.

**Steps to reproduce:**
Bullet scene with RayCast2D hitting KinematicBody2D.
Bullets have to overlap other bullets.
Bullets need to have meta set to "Bullet"
Bullets have to use "has_meta("Bullet")
Bullets call queue_free() on KinematicBody2D if colliding.

The project is a mess but maybe it'll help. Just shoot on the enemies on the right using left mouse button and see what happens (the bullets fly very slowly so you can see clearly).
[Shooter.zip](https://github.com/godotengine/godot/files/2045222/Shooter.zip)

**Comment by henriiquecampos** [comment] 2018-05-28 16:49
`Raycasts` already have a `collision_mask` property:

```
int collision_maskset_collision_mask(value) setterget_collision_mask() getter
The ray's collision mask. Only objects in at least one collision layer enabled in the mask will be detected.
```

**Comment by kubecz3k** [comment] 2018-06-03 11:32
I tried to reproduce the described behavior of raycast vs raycast collision but I was unable to in Godot 3.0.3 rc2.
[RaycastVsRaycastCollision.zip](https://github.com/godotengine/godot/files/2065902/RaycastVsRaycastCollision.zip)

**Comment by KoBeWi** [comment] 2019-04-24 10:06
The reason RaycastShapes2D don't have collision layer is that they only detect collision, not can be collided with. So the bug in original project either was fixed (as tested by kubecz3k) or was caused by something else.

**Comment by akien-mga** [comment] 2019-04-25 06:56
Thanks, closing then.

**Closed by akien-mga** 2019-04-25 06:56 UTC
Labels: discussion, feature proposal, topic:physics
