### ISSUE TITLE
GLES3 Resizing 3D viewport to tiny widths crash the game

### ISSUE THREAD

**Issue by FlamyAT** [godotengine/godot#23158] opened 2018-10-19 19:23 UTC
**Godot version:** cf7a661

**OS/device including version:** Ubuntu 18.04.1

**Issue description:**
If the Stretch Mode is set to `Viewport` and the Stretch Aspect is set to `Expand`, the game will crash when the window is resized to a very small width and 3D environment is visible.
When recreating the issue without a 3D camera this error is emitted.
```
E 0:00:02:0983   Condition ' status != 0x8CD5 ' is true.
  <C Source>     drivers/gles3/rasterizer_storage_gles3.cpp:6598 @ _render_target_allocate()
```

**Steps to reproduce:** 
Create a project. Create a spatial node with a camera.
Set the Stretch Mode to `Viewport` and Stretch Aspect to `Expand`.
Run the project. Resize the window to a width of one or zero.
When resizing again a strange artifact (image below) will be visible, regardless of that, the game crashes shortly after.

![screenshot from 2018-10-19 21-22-06](https://user-images.githubusercontent.com/8056898/47239311-3a118b80-d3e5-11e8-9996-09da090c80c2.png)

**Comment by akien-mga** [comment] 2018-10-19 19:40
Thanks for the report! I think it's a duplicate of #19628.

**Closed by akien-mga** 2018-10-19 19:40 UTC
