### ISSUE TITLE
[C#] Instances of custom Resource classes that inherit other custom resource classes with tool attribute lose values of their properties when rebuilding the project

### ISSUE THREAD

**Issue by pikol93** [godotengine/godot#48042] opened 2021-04-20 09:52 UTC
**Godot version:**
3.2.3.stable.mono

**Issue description:**
Instance of a class marked with the `[Tool]` attribute that inherits a custom resource clears the properties of inherited class every time the project is built. The solution needs to be modified somewhere in order to invoke the issue. The modified part does not have to be related in any way to the resource classes. Here's a few screenshots that showcase the issue:

Here I set some value to a property defined by a resource class. I am able to save the resource object and the properties remain intact even when relaunching the editor.
![pre-build](https://user-images.githubusercontent.com/40030490/115374659-57e62400-a1cd-11eb-862a-059184371757.PNG)

This is what happens when I change contents of some .cs script and rebuild the project. Notice how the Base Class Field is resetted to it's default value.
![issue2](https://user-images.githubusercontent.com/40030490/115375014-a8f61800-a1cd-11eb-974a-9cb6e62d7f06.PNG)

I was unable to reproduce this issue in GDScript. I would appreciate someone trying once again as my knowledge of GDScript is very brief and I might have missed something important.

**Steps to reproduce:**
1. Create two classes. Let the first one inherit from Resource (or any of it's descendants) and the second one inherit from the second one.
2. Add the [Tool] attribute to the sub-class
3. Export properties in the base class and set some values in the editor
4. Make a change in the script files and rebuild the project (the change can be located in any file, it doesn't have to be related to the resources themselves)
5. The exported property should reset at this point

**Minimal reproduction project:**
[ResourceInheritanceIssue.zip](https://github.com/godotengine/godot/files/6342496/ResourceInheritanceIssue.zip)

**Comment by Phischermen** [comment] 2021-04-20 21:37
Duplicate of #37812. Also, it seems this issue isn't exclusive to just resources. It extends to all C# scripts with the [Tool] attribute.

**Comment by Calinou** [comment] 2021-04-20 22:27
Duplicate of https://github.com/godotengine/godot/issues/37812.

**Closed by Calinou** 2021-04-20 22:27 UTC
Labels: bug, topic:mono
