### ISSUE TITLE
Control opacity causing some kind of "burn-in" effect

### ISSUE THREAD

**Issue by coelhucas** [godotengine/godot#71370] opened 2023-01-13 23:17 UTC
### Godot version

3.5.1 stable

### System information

Windows 11, GLES 3

### Issue description

When having two control nodes on top of each other and "interpolating" the topmost one's opacity, for a few frames it does a "burn-in" effect where the lighter content behind appears darker on top of it.

### Steps to reproduce

- Make two `PanelContainer`s with white text inside overlapping each other
- Run a tween updating the inner one's `modulate:a`

**Note:** Only happens when _increasing_ `modulate.a`. Doesn't happen when decreasing it.

Before | During | After
 -- | -- | -- 
![image](https://user-images.githubusercontent.com/28108272/212435811-04220adf-562c-475c-9d89-e929add7e05b.png) | ![image](https://user-images.githubusercontent.com/28108272/212435767-3163b725-9686-4a17-a189-c707613921bd.png) | ![image](https://user-images.githubusercontent.com/28108272/212435855-1e443470-d366-411f-b1b7-04ddbc0e959d.png)

### Closer look on the visual issues
![image](https://user-images.githubusercontent.com/28108272/212436267-5d09d62a-c40c-4e7e-85d5-f1f1f20eab06.png)

### Minimal reproduction project

N/A

Working on it.
**EDIT:** I couldn't replicate in a separate project, but from ours we could observe that:
- If we instance the scene and _then_ run the Tween, it's ok;
- If we just toggle its `visible` field and then run the Tween, this happens

**Comment by Calinou** [comment] 2023-01-13 23:20
@coelhucas Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

**Comment by AThousandShips** [comment] 2024-07-29 17:25
Closing due to the lack of replication, if you can still replicate this on a current version, please upload an MRP and this can be reopened

**Closed by AThousandShips** 2024-07-29 17:25 UTC
Labels: needs testing, topic:gui
