### ISSUE TITLE
Unable to pause individual nodes, only tree

### ISSUE THREAD

**Issue by mateusak** [godotengine/godot#15993] opened 2018-01-23 02:27 UTC
**Godot version:**
Godot 3 RC 2

**OS/device including version:**
Windows 10

**Issue description:**
Setting pause mode on editor or by script does nothing. Using `get_tree().paused = true` works, though.

**Comment by Noshyaar** [comment] 2018-01-23 02:48
I think this is by design. For now, you can't pause individual node. You may pause the whole tree and whitelist some node branch using PAUSE_MODE_PROCESS.

**Comment by mateusak** [comment] 2018-01-23 02:58
...like it always has? This is a regression.

**Comment by Noshyaar** [comment] 2018-01-23 03:19
Not a regression. docs.godotengine.org/en/stable/learning/features/misc/pausing_games.html

**Comment by mateusak** [comment] 2018-01-23 03:37
So you're saying that the sole purpose of STOP is to stop a node if the tree is paused and its parent is in PROCESS, but it doesn't have any effect on anything if the tree is not paused.

https://youtu.be/PEZWYXPvmS8?t=1s

It's surprising because one would think it's more work to implement it like this. Enhancement it is then.

**Comment by vnen** [comment] 2018-01-23 03:54
You can call `set_process(false)` and `set_process_internal(false)` (and all the other processing functions if needed which makes this a bit cumbersome). I think this doesn't affect the node's children though.

**Comment by Noshyaar** [comment] 2018-01-23 04:08
Maybe we can have PAUSE_MODE_FORCE or something to pause node regardless of the SceneTree pausing status.

**Comment by eon-s** [comment] 2018-01-24 03:18
A Godot user was experimenting with "pause masks" and seems to work, would be cool to have that in the engine, is better, more useful and organized than the single full tree pause.

https://twitter.com/williamd1k0/status/954885606999543809

**Comment by emmetoneillpdx** [comment] 2018-12-05 21:32
I just wanted to stop by and say that I also think that the _ability to pause any branch_ of nodes would be a great improvement over Godot's current system (pausing the SceneTree globally with the option of exempting certain nodes).

I'm still pretty new to Godot's codebase, so maybe there are some roadblocks that I'm underestimating here, but from a distance it seems like if each node had something like a `_run_state` that could be set to `RUNNING`, `PAUSED`, or `INHERIT` we could set the run state of any node in the tree, which would (by default) be inherited by its children. 

This would be pretty similar to what we have right now, and setting the root node to `PAUSED` while  some other branch of nodes is set to `RUNNING` would be effectively the same as telling the SceneTree to pause while setting a branch to `PAUSE_MODE_PROCESS`. _However, this would also allow you to do the opposite - allowing users to pause any branch of nodes even when the rest of the SceneTree (including the root node) is `RUNNING` - something that I don't think is very easy to do right now._

Generally, while I think Godot's current system is a good start and with some work-arounds you can probably get the results that you want, I think a slightly more flexible pausing system would just give people more control over their games.

**Comment by Lucrecious** [comment] 2019-02-22 22:15
+1 on pausing node branches.

It'd be nice, in order to reduce processing power, to pause individual node branches instead of the entire scene tree (which is how I thought it worked originally, and thought this was a bug like OP).

There are times, like in fighting games, where you might want to pause a fighter for like .1 seconds whenever they get hit for the sake of "impact". It'd be nice to just access the animation player node or character node and just `.pause()` or `.unpause()`.

In my scenario, I have a node (an enemy) that I do not want to process at all but I want to still be seen in the game. It's an enemy that dies, but stays in the Scene instead of being removed. Enemies in my project have a lot of children nodes working "concurrent".

I either have to:
1. have the root node pause mode as `PROCESS` and the enemy nodes' pause mode as `STOP` or
2. programmatically stop the processes of every child node under my enemy node

(1) is inconvenient because putting it means I can't pause the entire game without messing with pause modes and (2) doesn't scale well (and could potentially get expensive).

The only workaround I can muster is doing something like this:
```
func my_pause(node : Node) -> void:
    node.set_physics_process(false)
    node.set_process(false)
    # disable input processes
    # disable physics somehow
    for c in get_children():
        my_pause(c)
```

Anyways, those are my 2 cents.

**Comment by aaronfranke** [comment] 2019-05-05 18:47
It's quite confusing to have a pause state mode that's separate from the pause mode enum. What I would expect is that I could pause any node, not just the root of the tree. As the system currently stands `PAUSE_MODE_STOP` does not work as I would expect it to. Godot has a great node and scene system, and it's weird that the root node breaks the simplicity here.

My proposal: 

* Get rid of the `paused` boolean entirely. 

* Make the paused state entirely determined by the enum, such that Process is always running, Stop is always not running, and Inherit inherits. 

* Either don't allow the root node to be Inherit, or make Inherit behave like Process.

That is a simpler system that allows pausing any node and behaves as I'd expect. 

We can mostly preserve compatibility by making `paused` a boolean property that sets the pause mode to Stop for true and Process (or Inherit?) for false. Also, while I don't see why you would want it, the old behavior of a Stop child on a Process parent can be emulated in this system by manually setting that child node's pause mode when you pause.

**Comment by svendixon** [comment] 2019-12-18 22:33
I hope this gets looked at some more. It's very common to do something like a "hitpause" or "healpause" in games and still be able to pause the game during those pauses. Lucrecious's workaround is the only viable solution currently.
```
func freeze_node(node, freeze):
	node.set_process(!freeze)
	node.set_physics_process(!freeze)
	node.set_process_input(!freeze)
	node.set_process_internal(!freeze)
	node.set_process_unhandled_input(!freeze)
	node.set_process_unhandled_key_input(!freeze)

func freeze_scene(node, freeze):
	freeze_node(node, freeze)
	for c in node.get_children():
		freeze_scene(c, freeze)
```
I use something like this to freeze my main game world node while also allowing for a pause game. However if I have nodes set to false, this will blanket set them to true when the freeze finishes. So I have to do some extra checks in those instances. Also this doesn't affect particles.

It would be great if Godot had a better built in hierarchical pause system.

**Comment by Calinou** [comment] 2020-05-26 08:05
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!

**Closed by Calinou** 2020-05-26 08:05 UTC
Labels: feature proposal, topic:core

**Comment by southalan** [comment] 2023-04-17 01:45
I don't know if it is too late to comment on this, but I had the same issue and I couldn't find a fix online and I solved it like this: 

The root node is set as follows: 
![image](https://user-images.githubusercontent.com/80550822/232358510-5da3be3d-06f3-47b8-850a-d0ac30d9854f.png)
Then in the code, you just simply modify the status of the nodes you need paused.
![image](https://user-images.githubusercontent.com/80550822/232358621-f5626f9d-5522-4e4e-bf46-b1df1ac848f2.png)
Then, whenever you use "get_tree().paused" it will only affect the nodes that you specifically set to "Stop / Off"

Currently on Godot 3.5.2, I have seen that the 4.x.x has different methods.
