### ISSUE TITLE
Skeleton3D Nodes render the first launch, but not subsequent launches on Android

### ISSUE THREAD

**Issue by CorwinJV** [godotengine/godot#83356] opened 2023-10-15 00:04 UTC
### Godot version

4.2.beta1-mono

### System information

Engine: Windows 10, 4.2.beta1-mono, Runtime: Android 13 - Pixel 7 Pro 

### Issue description

Skeleton3D nodes don't render on Android after the first time you run the game, unless you clear the app's storage or uninstall / reinstall the apk.

When I hit F5 to run the project or export to desktop; then everything renders fine, but if I export to my Android device everything renders except the skeletal meshes in my scene. Until I clear the app's storage and relaunch it, then they start rendering. 

### Steps to reproduce

* Load the minimal reproduction project
* Install android export templates
* export to desktop
* verify that skeletal meshes render
* close & reopen exported app, verify it still works
* export to android
* launch app
* observe that skeletal mesh renders only if it's the first time the app has been launched
* on stock android: long tap the app icon -> app info -> storage & cache -> clear storage & cache
* observe skeletal meshes render once more after clearing storage for the app

### Minimal reproduction project

[TestingSkeletonMeshGdScript2.zip](https://github.com/godotengine/godot/files/12908254/TestingSkeletonMeshGdScript2.zip)

**Comment by bitsawer** [comment] 2023-10-15 00:30
Thanks for the report. This looks like a duplicate of https://github.com/godotengine/godot/issues/82419, so closing to keep discussion in one place.

The current workaround is to disable shader cache, see https://github.com/godotengine/godot/issues/82419#issuecomment-1736617963. Feel free to comment or re-open this issue if that did not help.

**Closed by bitsawer** 2023-10-15 00:30 UTC
