### ISSUE TITLE
3.0.6 upgrade causes compilation failure when using Dictionary in C#

### ISSUE THREAD

**Issue by TheCodeNinja** [godotengine/godot#20575] opened 2018-07-29 15:41 UTC
**Godot version:**
3.0.6 - C#

**OS/device including version:**
Windows 10 Desktop

**Issue description:**
Upgrade from 3.0.5 to 3.0.6 no longer compiles a project using Dictionary:
`'Dictionary<,>' is an ambiguous reference between 'Godot.Dictionary<TKey, TValue>' and 'System.Collections.Generic.Dictionary<TKey, TValue>`

Simple enough for a user to solve, but it is a break in backwards compatibility that will have you unable to compile your project.

**Steps to reproduce:**
Make a project in 3.0.5, where you are using both the Godot and System.Collections.Generic namespaces in the same script. Have a Dictionary defined in the script. Project will compile and run. Open the same project with 3.0.6 and attempt to run. Compile errors should happen.

**Minimal reproduction project:**

[repro.zip](https://github.com/godotengine/godot/files/2238902/repro.zip)

**Comment by akien-mga** [comment] 2018-08-13 06:36
CC @neikeq @hpvb

**Comment by mysticfall** [comment] 2018-08-13 06:39
It seems to be a duplicate of #20610.

**Comment by aaronfranke** [comment] 2018-08-26 02:41
C# is currently considered incomplete and most changes are being backported to 3.0.x releases even if they are breaking changes. Nearly every point release has broken something in C# so far (and replaced it with better things).

So basically, the fact that this is happening is a bug (duplicate of https://github.com/godotengine/godot/issues/20610), but the fact that this is happening in a point release is not really a concern right now, and won't be until maybe 3.2.x.

**Comment by KellyThomas** [comment] 2018-09-01 13:53
This should be fixed by https://github.com/godotengine/godot/pull/21423

**Comment by akien-mga** [comment] 2018-09-01 14:36
Fixed by #21423.

**Closed by akien-mga** 2018-09-01 14:36 UTC
Labels: bug, topic:mono
