### ISSUE TITLE
Assigning `PackedStringArray.reverse()` (`void` function) to a variable doesn't error and makes it an `int` or `bool`

### ISSUE THREAD

**Issue by thebardsrc** [godotengine/godot#65064] opened 2022-08-29 23:45 UTC
### Godot version

v4.0.alpha14.official [106b68050]

### System information

Windows 10

### Issue description

Calling .reverse() on a `PackedStringArray`, created from a String.split(), causes it to return an `int` type, unless the variable has been cast as a `PackedStringArray` at declaration

### Steps to reproduce

The following three-line block of code reproduces. 
```
var path_breakdown = path.split("/")
path_breakdown = path_breakdown.reverse()		
$ItemList.add_item("->".join(path_breakdown))
```
Third line will throw the following error: `Invalid type in function 'join' in base 'String'. Cannot convert argument 1 from int to PackedStringArray.`
Stepping through each line with breakpoints will show that in the Stack, it has changed from a PackedStringArray, to the length of the array after the second line
![image](https://user-images.githubusercontent.com/2214793/187317461-0a9f1b51-b8bc-4cdc-9714-ca977e024384.png)
![image](https://user-images.githubusercontent.com/2214793/187317501-dc3f81b7-d148-4461-a0b8-755e3ba1b703.png)

Changing the first line to read:
`var path_breakdown:PackedStringArray = path.split("/")`
allows the second line to run properly, and path_breakdown becomes a new PackedStringArray with the items reversed as expected

**Comment by thebardsrc** [comment] 2022-08-30 01:08
To add another reply onto this, another time running through it gave me an error of a different sort: `Trying to assign value of type 'bool' to a variable of type 'PackedStringArray'.`
![image](https://user-images.githubusercontent.com/2214793/187324597-1ef135ca-c6d1-42af-a67e-ede0ae83fad6.png)
![image](https://user-images.githubusercontent.com/2214793/187324626-b19fab37-8804-42d1-bba9-9e07b466dae7.png)

Turning the cast back off again, continuing on its showing as just bool:
![image](https://user-images.githubusercontent.com/2214793/187324795-14c8fa3c-b43d-4bad-94fc-cc14c9d884d6.png)

A loop of adding these without cast shows every reverse() is a bool now:
![image](https://user-images.githubusercontent.com/2214793/187325477-d9e58c4d-da9f-4a85-9da5-9dbb8fe20726.png)
![image](https://user-images.githubusercontent.com/2214793/187325551-c4f5e875-def2-45f9-bbf7-c4543b62484a.png)

**Comment by Atlinx** [comment] 2022-08-30 01:43
@thebardsrc I'm testing with this code
```
extends Node

@export var stringArray := PackedStringArray()

# Called when the node enters the scene tree for the first time.
func _ready():
	for i in 50:
		var path = "test/path"
		var path_breakdown = path.split("/")
		path_breakdown = path_breakdown.reverse()		
		stringArray.append("->".join(path_breakdown))
	print(stringArray)
```

And I can't seem to reproduce your error. Could you upload a minimum reproduction project/script?

**Comment by thebardsrc** [comment] 2022-08-30 03:09
Reproduction included. The actual project I'm working with I'm reversing file paths for some lookup indexing, so this reproduction will just build an array of all of res:// to then do the reversing. So itll also need some other folders and files in it too so it can build multiple directory levels. 

[reproduction.zip](https://github.com/godotengine/godot/files/9449273/reproduction.zip)

**Comment by Atlinx** [comment] 2022-08-30 03:51
> Reproduction included. The actual project I'm working with I'm reversing file paths for some lookup indexing, so this reproduction will just build an array of all of res:// to then do the reversing. So itll also need some other folders and files in it too so it can build multiple directory levels.
> 
> [reproduction.zip](https://github.com/godotengine/godot/files/9449273/reproduction.zip)
> 
> Crash will happen on line 24, as the array will either randomly change to an int or change to a bool from the reverse on 22

Thanks for uploading a project! I ran it on version 18159a6574e40c36c1aed0d1cae1dc8a32879efa but I couldn't get any errors. Do you get this error with the latest version of Godot 4.0? I noticed your report is from an older version. If you're still getting an error then this might be a platform dependent issue (though that seems really weird, because I'm on Windows 11, which is still Windows).

**Comment by thebardsrc** [comment] 2022-08-30 04:42
well what I'm running is the official Alpha 14 build linked from https://godotengine.org/article/dev-snapshot-godot-4-0-alpha-14, I  don't see a newer official alpha then 14? 

But I also have a newer nightly build from 24-Aug, v4.0.alpha.calinou [6e390fa9a], and that version's getting the error as well.

**Comment by Atlinx** [comment] 2022-08-30 05:10
Ah, you're right! Actually it turns out the versions didn't matter -- I ran some tests again and I realized I didn't have a folder structure big enough to trigger the bug. I've added a few nested folders and I'm able to reproduce it (including on latest master branch).

**Comment by akien-mga** [comment] 2022-08-30 07:46
> I ran some tests again and I realized I didn't have a folder structure big enough to trigger the bug. I've added a few nested folders and I'm able to reproduce it

Confirmed that I had to add some folders to trigger the bug. Here's an update MRP that should trigger it without any change:
[reproduction.zip](https://github.com/godotengine/godot/files/9450803/reproduction.zip)

**Comment by akien-mga** [comment] 2022-08-30 07:52
As some pointed out on the Godot chat, `reverse()` is a `void` function, it mutates the array directly. So you shouldn't be assigning its result to the variable, you should just call `path_breakdown.reverse()` on its own statement.

Now there's still a bug IMO that:
- No error is raised when assigning the result of a `void` function to a variable.
- Even if the above is allowed, the variable should be `null`, not randomly reassigned to an int or a bool.

**Comment by thebardsrc** [comment] 2022-08-30 23:01
alright, I can work with that change `void`, although that does make it it a little awkward to use, since for example cant do like `data['key'] = string.split().reverse()` to store it as one step in another variable, has to one step saving it then another step of just reverse()

**Closed** 2023-01-03 11:56 UTC
Labels: bug, topic:core, topic:gdscript, confirmed
