### ISSUE TITLE
Volumetric Fog stops working when enabling shadows for omnilight or spotlight

### ISSUE THREAD

**Issue by jcostello** [godotengine/godot#50330] opened 2021-07-10 00:30 UTC
### Godot version

v4.0.dev.calinou [5db1f8b1a]

### System information

Mx Linux (Debian Based)

### Issue description

When enabling shadows for an omnilight or spotlight, volumetric fog stops working.

### Steps to reproduce

Add environment
Enable Volumetric Fog
Add Omni Light (Make sure that its contributes to the Volumetric Fog)
Enable Omni Light Shadow
Fog stops working (or at least the light stops contributing)

https://user-images.githubusercontent.com/1168582/125146568-ce276200-e0fc-11eb-8bda-d60e87cba1d5.mp4

### Minimal reproduction project

There is no reason to add minimal project since once the light's shadow is enabled it never contributes to the fog again even if the shadow is disabled. So all steps must be done to reproduce the issue.

**Comment by Calinou** [comment] 2021-07-10 00:36
I couldn't reproduce this with OmniLights yesterday, but I couldn't get SpotLights to display in volumetric fog (even though there were no error messages).

**Comment by mrjustaguy** [comment] 2021-07-10 06:19
I can confirm the issue on both OmniLights and SpotLights on v4.0.dev.custom_build [e3744d2fe]
Note - SpotLights are much more difficult to see the effect of Volumetric Fog, try to view them with black sky (custom color) that might help, unless it's a bug.

Also Shadows cannot be turned off for both of those, not sure for directional, I'm not sure if this is a Known issue atm.

**Comment by Calinou** [comment] 2021-07-10 11:49
> Also Shadows cannot be turned off for both of those, not sure for directional, I'm not sure if this is a Known issue atm.

Disabling shadows for point lights will only apply once you reload the scene. I think this has been reported elsewhere already.

**Comment by jcostello** [comment] 2021-07-11 14:27
@Calinou I can confirm this for Point Lights but not for Spot Lights. For some reason the fog still broken even if I reload the scene

**Comment by clayjohn** [comment] 2021-12-01 20:21
This may have been fixed by https://github.com/godotengine/godot/pull/53353

**Comment by Calinou** [comment] 2022-02-06 19:19
I can't reproduce this on commit 9d1626b4d. However, I can reproduce a similar issue but only for SpotLight3D (and not OmniLight3D): https://github.com/godotengine/godot/issues/57722

**Closed by Calinou** 2022-02-06 19:19 UTC
Labels: bug, topic:rendering, confirmed, topic:3d

**Comment by AThousandShips** [comment] 2023-10-20 15:52
Please open a new bug report as this is a separate issue, it causing the same problem means it's a new issue having the same effect

**Comment by Calinou** [comment] 2023-10-20 22:40
https://github.com/godotengine/godot/issues/83685
