### ISSUE TITLE
New Scene Error

### ISSUE THREAD

**Issue by drmar** [godotengine/godot#44119] opened 2020-12-05 13:38 UTC
**Godot version:**

3.2.4.beta3

**OS/device including version:**

MacBookPro11,1 - macOS Catalina 10.15.7; GLES2

**Issue description:**

When a new scene is created, this error appears in the Output window:

<img width="1280" alt="Screenshot 2020-12-05 at 15 33 03" src="https://user-images.githubusercontent.com/13488692/101244522-b4114580-370f-11eb-9ff1-42f6dc110cb4.png">

**Steps to reproduce:**
1) Create a new project
2) Create a new scene

**Minimal reproduction project:**

**Comment by Calinou** [comment] 2020-12-05 13:43
Duplicate of https://github.com/godotengine/godot/issues/43764.

**Closed by Calinou** 2020-12-05 13:43 UTC
