### ISSUE TITLE
problem with changing Screen resolution in Full screen mode

### ISSUE THREAD

**Issue by ghost** [godotengine/godot#18120] opened 2018-04-11 10:59 UTC
**Godot version:**
Godot 3.0.2

**OS/device including version:**
GTX 980 
i7 4790k
8GB Ram
Windows 7 x64

**Issue description:**
Unable to stretch the screen and change Screen resolution in Full screen mode 

```
OS.set_window_size(Vector2(1024,768))
get_viewport().set_size(Vector2(1024,768))
get_tree().set_screen_stretch(SceneTree.STRETCH_MODE_VIEWPORT,SceneTree.STRETCH_ASPECT_EXPAND,Vector2(1024,768))
OS.set_window_fullscreen(true)
```

+ changing the parameters in Project settings 
no matter what ... the screen cannot be stretched when change the resolution in Full screen mode

**Comment by Calinou** [comment] 2020-06-07 20:58
Since OP deleted their GitHub account and nobody else has been able to reproduce this so far, I'll close this. Please comment if you can still reproduce this bug in Godot 3.2.1 or [3.2.2beta4](https://godotengine.org/article/dev-snapshot-godot-3-2-2-beta-4).

**Closed by Calinou** 2020-06-07 20:58 UTC
Labels: bug, topic:rendering
