### ISSUE TITLE
Run Error

### ISSUE THREAD

**Issue by Zane65022** [godotengine/godot#48723] opened 2021-05-14 21:48 UTC
Whenever I try to run my game, I get this error:

E 0:00:00.934   can_instance: Cannot instance script because the project assembly is not loaded. Script: 'res://Player.cs'.
  <C++ Error>   Method failed. Returning: __null
  <C++ Source>  modules/mono/csharp_script.cpp:2902 @ can_instance()

I tried just closing the editor and reopening it, but it still comes up with this error
Can anyone help? Thanks

**Comment by Calinou** [comment] 2021-05-14 22:35
@Zane65022 Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

Also, which Godot version are you using?

**Comment by Zane65022** [comment] 2021-05-15 05:21
@Calinou I'm just trying to do the basic project that is on Godot's site(zip below). I'm using version 3.3
[NewGame - Copy.zip](https://github.com/godotengine/godot/files/6482414/NewGame.-.Copy.zip)

**Comment by LightningAA** [comment] 2021-05-21 16:41
You're missing a C# solution, you can generate one with `Project > Tools > C# > Generate C# Solution`

**Comment by Zane65022** [comment] 2021-05-22 05:19
So that helped a little bit, but now the error is saying:
The SDK resolver type "DotNetMSBuildSdkResolver" failed to load. The type initializer for 'Microsoft.DotNet.MSBuildSdkResolver.VSSettings' threw an exception.

**Comment by Zane65022** [comment] 2021-05-22 05:20
@LightningAA

**Comment by LightningAA** [comment] 2021-05-22 05:34
Can you upload an updated minimal reproduction project?

**Comment by Zane65022** [comment] 2021-05-23 01:25
This is the project below. I didn't do a minimal version since it's the basic game that can be made from Godot's website
[NewGame - Copy.zip](https://github.com/godotengine/godot/files/6527386/NewGame.-.Copy.zip)

**Comment by raulsntos** [comment] 2021-10-30 19:17
Duplicate of #41734

Also, not following the [issue template](https://github.com/godotengine/godot/blob/master/.github/ISSUE_TEMPLATE/bug_report.md) so I don't know what OS the author of the issue is using, but their issue is most likely a bad .NET SDK installation (maybe missing something or an outdated version).

I suggest to try using `dotnet CLI` as build tool (`Editor > Editor Settings... > Mono > Builds > Build Tool`) since it seems `MSBuild (Mono)` often causes issues to some.

**Closed** 2021-11-01 14:12 UTC
Labels: topic:editor, needs testing, topic:mono
