### ISSUE TITLE
[gles3] errors

### ISSUE THREAD

**Issue by alabd14313** [godotengine/godot#7171] opened 2016-11-22 07:41 UTC
Hello!
I tested gles3 branch and have some errors in terminal:

> max ubo light: 409

> max ubo reflections: 455  ubo size: 144
> mesege
> ERROR: _gl_debug_print: GL ERROR: Source: OpenGL        Type: Error     ID: 1286       Severity: High   Message: GL_INVALID_FRAMEBUFFER_OPERATION error generated. Operation is not valid because a bound framebuffer is not framebuffer complete.
>    At: drivers/gles3/rasterizer_gles3.cpp:65.
> 
> 
> mesege
> ERROR: _gl_debug_print: GL ERROR: Source: OpenGL        Type: Performance       ID: 131218      Severity: Medium        Message: Program/shader state performance warning: Fragment Shader is going to be recompiled because the shader key based on GL state mismatches.
>    At: drivers/gles3/rasterizer_gles3.cpp:65.
> 
> ERROR: get: Condition ' !id_map.has(p_rid.get_data()) ' is true. returned: __null
>    At: core/rid.h:166.
> 
> ERROR: material_remove_instance_owner: Condition ' !material ' is true.
>    At: drivers/gles3/rasterizer_storage_gles3.cpp:1719.
> 
> ERROR: get: Condition ' !id_map.has(p_rid.get_data()) ' is true. returned: __null
>    At: core/rid.h:166.
> 
> ERROR: material_remove_instance_owner: Condition ' !material ' is true.
>    At: drivers/gles3/rasterizer_storage_gles3.cpp:1719.

I have this error in a gpu with OpenGL 3.3 and GLES 2 (GLSL ES 1.00) support. Do this branch need complete GLES 3 support for desktop, or only OpenGL 3.3 is sufficient?

**Comment by alabd14313** [comment] 2016-11-22 07:53
Here is glxinfo:
[glxinfo.txt](https://github.com/godotengine/godot/files/605767/glxinfo.txt)

**Comment by vnen** [comment] 2016-11-22 10:04
the `gles3` branch is still in development (that's why it's in another branch, not in `master`). It is bound to have a lot of errors until it is completed.

**Comment by TheoXD** [comment] 2016-11-22 21:45
You're out of luck, from wikipedia "OpenGL 4.3 provides full compatibility with OpenGL ES 3.0."  I heard gles2 will be rewamped so that older hardware can still be supported, so don't try compiling gles3 branch, it simply wont work on your hardware.

**Comment by TheoXD** [comment] 2016-11-22 22:02
Turns out gles3 is a subset of gl3 and gles3.1 is a subset of opengl4.x, so I guess Juan is using gles3.1 features that makes it incompatible on your hardware.

**Comment by TheoXD** [comment] 2016-11-22 22:51
Now that I think about it the issue regarding GL_INVALID_FRAMEBUFFER_OPERATION can have different causes, including driver bugs. It's best to give it time.

**Comment by alabd14313** [comment] 2016-11-23 10:00
@reduz, please notify us about hardware specification and essentials.

**Comment by akien-mga** [comment] 2016-11-23 10:02
Please wait for the branch to be stable before trying to narrow down hardware requirements.

**Comment by reduz** [comment] 2016-11-23 10:17
OpenGL 3.3 will be sufficient, but it's not ready for you to use yet,
expect a lot of errors

**Comment by alabd14313** [comment] 2016-11-23 12:19
Thanks a lot!

**Comment by bojidar-bg** [comment] 2017-01-30 13:37
Given that the `master` branch is now stablish 3.0, can we get a confirmation?

**Comment by volzhs** [comment] 2017-01-30 14:26
I still have similar errors.

**Comment by reduz** [comment] 2017-01-30 14:37
Still undergoing surgery.. will not start stabilizing for a few more weeks

On Jan 30, 2017 11:26 AM, "volzhs" <notifications@github.com> wrote:

I still have similar errors.

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/godotengine/godot/issues/7171#issuecomment-276075229>,
or mute the thread

**Comment by YeldhamDev** [comment] 2017-09-03 16:43
> ERROR: _gl_debug_print: GL ERROR: Source: OpenGL Type: Performance ID: 131218 Severity: Medium Message: Program/shader state performance warning: Fragment Shader is going to be recompiled because the shader key based on GL state mismatches.
> At: drivers/gles3/rasterizer_gles3.cpp:65.

This one shows up everytime I run a project.
Ubuntu 17.04 - GeForce 820M - 340.102

**Comment by Zylann** [comment] 2017-10-31 21:40
I get these errors immediately as I just run the project manager in 3.0 alpha 2:
```
ERROR: _gl_debug_print: GL ERROR: Source: OpenGL        Type: Performance       ID: 131218      Severity: Medium
Message: Program/shader state performance warning: Vertex shader in program 1 is being recompiled based on GL state.
   At: drivers\gles3\rasterizer_gles3.cpp:122
```

**Comment by akien-mga** [comment] 2017-10-31 22:10
Me too, so I think it might be worth closing this issue and opening a new one - same symptom but 9 months later it might be a very different bug, and the above old history makes it less visible.

**Comment by reduz** [comment] 2017-10-31 22:11
It's not a bug, but more like an annoying warning that should not be shown..
I need to get those shut off unless running with debug

**Closed** 2017-11-13 17:01 UTC
Labels: bug, topic:rendering
