### ISSUE TITLE
godot project in macOS add tag "index=0"

### ISSUE THREAD

**Issue by salvob41** [godotengine/godot#17691] opened 2018-03-22 10:31 UTC
macOS adds always a tag `index="0"` in the nodes. While Windows and Ubuntu systems removes it. 

**Godot version:**
godot 3.0.2

**OS/device including version:**
macOS High Sierra 10.13.3

**Issue description:**
Everytime I open a scene into the editor, It adds `index="0"`

**Steps to reproduce:**
If you open a scene in Godot and save it.

**Comment by Zireael07** [comment] 2018-03-22 10:54
Duplicate of #17562 (and it's not Mac-only, I'm experiencing it on Windows)

**Comment by groud** [comment] 2018-03-22 11:01
Closing as a duplicate of #17562

**Closed by groud** 2018-03-22 11:01 UTC
