### ISSUE TITLE
rogue / zombie files appearing in .import

### ISSUE THREAD

**Issue by girng** [godotengine/godot#18314] opened 2018-04-20 07:37 UTC
if you download a image via the `HTTPRequest` node, and  set =`http_request.download_file = "test.png" `, it will appear in your godot directory.
```
var http_request = HTTPRequest.new()
add_child(http_request)
http_request.request("https://i.stack.imgur.com/kS9Kf.png", PoolStringArray(), false)
http_request.download_file = "test.png"
yield(http_request, "request_completed")
print("download complete: %s" % http_request.download_file)
```
which is good / perfectly normal. and it creates a `test.png-f3b52ed15cef619621ce03c016295639.md5` inside `.import`, which is normal.

except, **now..** when you delete that test.png (**using the `FileSystem` tab**). that `test.png` is now lingering in `.import`. it does not get removed.  

i did a compile about 5 days ago on godot-master. was there any changes/issues surrounding this should i try on a newer version?

**Comment by groud** [comment] 2018-04-20 07:54
Duplicate of #17733

**Closed by groud** 2018-04-20 07:54 UTC
