### ISSUE TITLE
AnimationPlayer duplication issue

### ISSUE THREAD

**Issue by marcelofg55** [godotengine/godot#6255] opened 2016-08-23 12:47 UTC
**Operating system or device - Godot version:**
Latest godot v2.2 on github

**Issue description** (what happened, and what was expected):
Whenever you duplicate an AnimationPlayer node it doesn't duplicates as well its animations and they stay linked in both nodes, I was expecting that the animations get duplicated as well so that if I change the animations on the duplicated node it won't change the animations on the original one.

**Steps to reproduce:**
Duplicate any AnimationPlayer node.

**Link to minimal example project** (optional but very welcome):
I can provide one if needed but I guess it's not.

**Comment by vnen** [comment] 2016-08-23 15:16
This is not a bug. When you duplicate a node all the resources are shared. If you do not want this behavior, select the new node and on the gear icon on Inspector dock select "Make Sub-Resources Unique".

**Comment by vnen** [comment] 2016-08-23 15:19
For adding a duplicate function that also makes the resources unique there's #1213. Closing as not a bug.

**Closed by vnen** 2016-08-23 15:19 UTC

**Comment by marcelofg55** [comment] 2016-08-23 15:31
Thanks for the clarification vnen, I wasn't aware of that "Make Sub-Resources Unique". Is it possible to know on the editor if the sub-resources are unique or not? (I mean I can look at the .tscn file but on the gui I don't see any way to realize this)

**Comment by vnen** [comment] 2016-08-23 15:44
@marcelofg55 no, I don't think there's anyway to know using the GUI. If you want to propose the feature then you can open a new issue.
