### ISSUE TITLE
If marking text in script-editor while scrolling down/up with mousewheel, it stops marking text

### ISSUE THREAD

**Issue by Paradisebird** [godotengine/godot#3123] opened 2015-12-23 08:05 UTC
Whenever i want to mark a lot of code while scrolling up/down with mousewheel, it stops marking the code. 
I know, it itsn't a real bug, but for me, it would be more comfortable to work if i could mark code this way.

**Comment by kubecz3k** [comment] 2015-12-23 10:08
Hmm I'm unable to reproduce with 1bc91848e3cee91eccaf2150a74deaf1cd84be13 commit on Linux (Ubuntu 15.10). Maybe it's os related issue? On what version of Godot and on what system are you experiencing the issue?

**Comment by neikeq** [comment] 2015-12-23 11:16
Do you mean the selection stops after scrolling? If so, then you are probably using an older version of Godot. It should be fixed by 51fa997.

**Comment by reduz** [comment] 2016-01-10 23:21
i can't reproduce this either, must be a 1.1 bug, closing

**Closed by reduz** 2016-01-10 23:21 UTC
Labels: bug, topic:editor
