### ISSUE TITLE
Please Sign the Godot release executables for Windows

### ISSUE THREAD

**Issue by Logmytech** [godotengine/godot#20755] opened 2018-08-06 04:55 UTC
I have multiple Whitelist softwares running and all of them try to contain or block Godot.

Then I noticed that Godot executables are not signed.

Now a days even small FOSS devs seem to be able to get certificates for signing.

I don't know the disadvantages of signing. Other than certificate being stolen. (A hardware wallet with encryption is good I guess)

Do other people think signing is a good idea? Please reply.

If we need the same for Linux we could use PGP.

Maybe PGP in addition or instead of normal signatures in Windows.

**Comment by Logmytech** [comment] 2018-08-06 06:40
@Zireael07 

Then atleast PGP signing?

**Comment by Calinou** [comment] 2018-08-06 10:28
Duplicate of https://github.com/godotengine/godot/issues/11984.

Unfortunately, GPG signatures won't prevent Windows SmartScreen from blocking those executables since Microsoft only recognizes its own code signing system.

**Closed by Calinou** 2018-08-06 10:28 UTC
Labels: discussion, platform:windows, topic:buildsystem

**Comment by Logmytech** [comment] 2018-08-06 12:55
@Calinou But since it is free it will be good at least for Linux users and users who are paranoid and check for GPG signature.

Morever even hashes are not shown in the website IIRC.

1) Show hashes like Sha256.
2) Maybe PGP sign if possible. 
The concern I was having about this was that the signature can be stolen and USB hardware has to be used which might be a hassle, but then I realized if the PC of the person compiling software is compromized, the Godot executables are gonna backdoored too.

**Comment by Calinou** [comment] 2018-08-06 13:07
Adding SHA-256 hashes could be done, please open an issue on the [godot-website repository](https://github.com/godotengine/godot-website) about that.
