### ISSUE TITLE
[Feature Request] Array shuffle and reflect function

### ISSUE THREAD

**Issue by GlaDOSik** [godotengine/godot#1735] opened 2015-04-25 13:26 UTC
Vector Operator node in visual shader editor doesn't have reflect function.

Built-in shuffle function for array would be useful. Something like this:

func ShuffleArray(array):
for i in array:
var index = randi() % (i+1)
var a = array[index]
array[index] = array[i]
array[i] = a

**Comment by akien-mga** [comment] 2015-11-05 09:37
The shuffle part is a duplicate of #2576 which has more input from the devs.

Please open a separate issue for the reflect function if you still think it's needed and if there isn't an issue about it already.

**Closed by akien-mga** 2015-11-05 09:37 UTC
Labels: archived
