### ISSUE TITLE
connecting a signal in the editor does not create the function(c#)

### ISSUE THREAD

**Issue by theBSH** [godotengine/godot#84365] opened 2023-11-02 13:34 UTC
### Godot version

4.1.2

### System information

Godot v4.1.2.stable.mono - Windows 10.0.22621 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3060 (NVIDIA; 31.0.15.3742) - 11th Gen Intel(R) Core(TM) i5-11600K @ 3.90GHz (12 Threads)

### Issue description

when you connect a signal, it should drop the function in the script but does not, I'm using c#. the editor opens (vs code) but the function is not there.

### Steps to reproduce

on the nodes tap => signals => right click on a signal then connect

### Minimal reproduction project

N/A

**Comment by philippilievski** [comment] 2023-11-03 20:54
Hey there are already three open issues related to this (as far as i know - there could be more) -> #41283 #23208 #18721 .
These seem to be existing for quite a while now. Also noted that the tutorial doesn't explicitly state this issue.

**Comment by theBSH** [comment] 2023-11-04 14:45
seems like it was like this for a while i don't understand why tho.

**Comment by akien-mga** [comment] 2023-11-10 09:00
- Duplicate of #41283

**Closed by akien-mga** 2023-11-10 09:00 UTC
Labels: topic:editor, needs testing, topic:dotnet
