### ISSUE TITLE
Basis from GetGlobalTransfrom/get_global_transfrom are different in C# and GDScript. 

### ISSUE THREAD

**Issue by alexwbc** [godotengine/godot#25527] opened 2019-01-31 21:16 UTC
**Godot version:**

**OS/device including version:**
Lubuntu 18.04, Intel HD Graphics
Godot v3.1-beta3 mono

**Issue description:**
Problem form:
#11901
#18886
is returned in Godot 3.1-beta3

**Steps to reproduce:**
Try to get the relative direction of the input using the basis of a Camera in both GDScript and C#:
```GDScript
	var cam_xform = $yaw/cam.get_global_transform().basis
	dir += (Input.get_action_strength("move_backward") - Input.get_action_strength("move_forward"))*cam_xform[2]
	dir += (Input.get_action_strength("move_right") - Input.get_action_strength("move_left"))*cam_xform[0]

```

```C#
	dir = new Vector3();
	var cam_xform = cam.GetGlobalTransform().basis;
	dir += (Input.GetActionStrength("move_backward") - Input.GetActionStrength("move_forward"))*cam_xform[2];
	dir += (Input.GetActionStrength("move_right") - Input.GetActionStrength("move_left"))*cam_xform[0];
```

**Minimal reproduction project:**
This is the project I am using to learn C# in Godot
https://gitlab.com/alexwbc/tpsharp
Press [enter] to switch between the two codes. Only these lines changes: the whole logic for the player node is handled by c#

Binary exported with Godot 3.1-beta3 export templates [TPC.tar.gz](https://we.tl/t-4zSGw08aH8)

**Comment by reduz** [comment] 2019-02-12 09:34
@neikeq This is most likely a bug in the Mono bindings (did we not discuss it before?), which is using row order instead of column order.  In C++ it's done this way for performance and taking advantage of the autovectorization (and APIs that use this instead use the set_axis / get_axis when needed), but in C# it will just make it confusing. Columns/rows need to be swapped.

**Comment by reduz** [comment] 2019-02-12 09:35
It also seems @karroffel did the same mistake in GDNative C++.

**Comment by reduz** [comment] 2019-02-12 09:36
Same issue for GDNative C++ - #14553

**Comment by neikeq** [comment] 2019-02-13 02:29
So this is a duplicate of #14553, which is still valid for C#. Correct?

**Comment by reduz** [comment] 2019-02-14 14:26
@neikeq It's not really a duplicate because the bug is different code for each. We just discussed with @karroffel and believe the best way to go is the following:

Make operator[] in Basis return the same as GetAxis() (there is not much of a point in getting transposed vectors from the bassis), and in Godot 4.0 we remove the GetAxis binding, so we don't break compat.

**Comment by neikeq** [comment] 2019-02-14 14:30
That issue was initially tagged C# as well but it was (wrongly) marked as fixed.

**Closed** 2019-02-23 19:53 UTC
Labels: bug, topic:core, topic:mono
