### ISSUE TITLE
[3.2.4-rc5]Mouse drag control size error

### ISSUE THREAD

**Issue by wupingli2021** [godotengine/godot#47021] opened 2021-03-15 11:07 UTC
**Godot version:**
3.2.4-rc5

**OS/device including version:**
win10

**Issue description:**
Mouse drag control size error

**Steps to reproduce:**
3.2.4-rc5  
![111](https://user-images.githubusercontent.com/80683955/111143928-5cf9f700-85c1-11eb-85a2-c0cdd4b8580c.gif)

Last version 3.2.4-rc4
![222](https://user-images.githubusercontent.com/80683955/111144067-86b31e00-85c1-11eb-9815-977925862f92.gif)

**Comment by Sslaxx** [comment] 2021-03-15 11:08
See https://github.com/godotengine/godot/issues/46979

**Comment by akien-mga** [comment] 2021-03-15 11:16
Duplicate of #46979, it's fixed for the next build :+1:

**Closed by akien-mga** 2021-03-15 11:16 UTC
