### ISSUE TITLE
Direct manipulation of Polygon2D polygon array elements possible in GDScript but not in CSharp.

### ISSUE THREAD

**Issue by timosperisen** [godotengine/godot#85198] opened 2023-11-21 22:51 UTC
### Godot version

v4.1.3.stable.mono.official [f06b6836a]

### System information

Godot v4.1.3.stable.mono - Windows 10.0.22621 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3060 (NVIDIA; 31.0.15.4601) - 11th Gen Intel(R) Core(TM) i5-11400F @ 2.60GHz (12 Threads)

### Issue description

When creating a Polygon2D Node (with 4 points in the polygon array) and manipulating the points via code it seems that this is only possible in GDScript directly. In C# it seems only to be possible by replacing the whole Vector2 array (named Polygon).

### Steps to reproduce

See minimal reproduction project for a full example with GDScript & C#
- create a Polygon2D node
- Set some points for the polygon 
- attach a script to the node which manipulates one or more points in code
- if manipulating points directly in the polygon array it will only work in GDScript but not via C# 

### Minimal reproduction project

See attached a Minimal reproduction project.

It contains two Polygon2D Nodes. The left one has a GDScript attached. 
The right one has a C# Script attached. The code should be "equal".

Both have two exposed variables: directUpdate and debugPointsToConsole which can be used to control the program flow.

The top left point (point 0 ) of both polygons will move up and down.

By switching directUpdate On/Off (True/False) the script will use the UpdateDirect() or UpdateIndirect() functions to update one points in the polygon. UpdateDirect manipulates the array directly, In UpdateIndirect the change is made to a copy of the array which is then copied back.

As you will see in C# the direct manipulation of the Polygon array seems not to work. 

I am aware of the note on the https://docs.godotengine.org/en/stable/classes/class_polygon2d.html page:
`Note: This returns a copy of the [PackedVector2Array](https://docs.godotengine.org/en/stable/classes/class_packedvector2array.html#class-packedvector2array) rather than a reference.`

If my way to trying to manipulate a point directly in C# is wrong, is there any way to do it there besides replacing the whole array? 

Thanks for any responses.
[Polygon2DTest.zip](https://github.com/godotengine/godot/files/13431809/Polygon2DTest.zip)

Edit: replaced archive. Removed unnecessary files.

**Comment by AThousandShips** [comment] 2023-11-22 10:07
This is not a bug, and is clearly documented, you cannot manipulate it directly, as the documentation states

You do need to copy it, update it, and assign it back

So other than the discussion over if more details on how to do this efficiently should be added there's nothing more needed here

**Comment by AThousandShips** [comment] 2023-11-22 10:13
A good note is available on `CollisionPolygon3D` will apply it here as well

**Comment by timosperisen** [comment] 2023-11-22 10:44
Okay, thanks for the clarification.

**Closed** 2024-04-08 12:11 UTC
Labels: documentation, topic:2d
