### ISSUE TITLE
Camera produce !is_inside_tree() error

### ISSUE THREAD

**Issue by hickop** [godotengine/godot#14975] opened 2017-12-23 10:52 UTC
**Godot version:**
3.0 5463b5e3489ab2c43279447b66d22b4b35f92e9b

**OS/device including version:**
linux x64

**Issue description:**
Simply adding a Camera outputs in debug:
```
ERROR: get_global_transform: Condition ' !is_inside_tree() ' is true. returned: Transform()
   At: scene/3d/spatial.cpp:265.
ERROR: get_global_transform: Condition ' !is_inside_tree() ' is true. returned: Transform()
   At: scene/3d/spatial.cpp:265.
```

**Steps to reproduce:**
- Create Spatial
- Add Camera
- Run

**Comment by AlmightyScientist** [comment] 2017-12-23 11:38
The problem is `_set_tree` isn't called for Camera.

I'm on it.

**Comment by SIsilicon** [comment] 2017-12-24 15:45
I get that bug too on my
Windows 7 64-bit.

**Comment by volzhs** [comment] 2017-12-24 16:40
pushed PR #14977 for this issue.

**Comment by reduz** [comment] 2017-12-26 14:53
fixed via #14977

**Closed by reduz** 2017-12-26 14:53 UTC
Labels: bug, topic:core
