### ISSUE TITLE
Beta16 @export_category and @export_group not appearing in inspector (regression)

### ISSUE THREAD

**Issue by cosmoddd** [godotengine/godot#72256] opened 2023-01-28 15:21 UTC
### Godot version

4.0 Beta16

### System information

Windows 11

### Issue description

![2023-01-28 10_15_20-Vars tscn - Tales From Off-Peak City RPG - Godot Engine](https://user-images.githubusercontent.com/9627628/215274514-d85e3950-a707-45bf-96af-f61583a18d12.png)
![2023-01-28 10_15_25-Vars tscn - Tales From Off-Peak City RPG - Godot Engine](https://user-images.githubusercontent.com/9627628/215274516-0ac42d08-9035-4101-af44-adcc55597dd0.png)

### Steps to reproduce

Create a script that publicly exposes variables and add @export_category and @export_group headers.  

See that they don't appear in the inspector.

### Minimal reproduction project

This should be immediately apparent on any project.

**Comment by akien-mga** [comment] 2023-01-28 16:05
Duplicate of #72151

**Closed by akien-mga** 2023-01-28 16:05 UTC
