### ISSUE TITLE
AudioEffectRecord returns all zero samples on iOS

### ISSUE THREAD

**Issue by ArdaE** [godotengine/godot#30308] opened 2019-07-04 05:36 UTC
**Godot version:**
3.1

**OS/device including version:**
iOS 12.3.1, iPhone 6s Plus
(code exported via macOS 10.14.5)

**Issue description:**
Audio recorded via the AudioEffectRecord effect contains all zero samples. While the number of samples seem to relate to the length of the recording, all samples are zero.

**Steps to reproduce:**
Try exporting the official microphone recording demo (see "Minimal reproduction project below") to iOS. Note that it doesn't function as it does on other platforms. Further, if you scan the recorded audio samples for non-zero values, you'll find that no non-zero value exists (the recorded samples can be accessed via the `data` variable in the `_on_PlayButton_pressed` function.

**Minimal reproduction project:**
https://github.com/godotengine/godot-demo-projects/tree/master/audio/mic_record

**Related issues/pull requests:**
https://github.com/godotengine/godot/pull/19106

**Comment by akien-mga** [comment] 2019-07-04 06:22
CC @marcelofg55

**Comment by ArdaE** [comment] 2019-07-04 06:33
Forgot to add: Either #30307 must be fixed or `NSMicrophoneUsageDescription` must be manually added to the app's `x-Info.plist` before this issue can be addressed. While one cannot expect microphone recording to work on iOS without `NSMicrophoneUsageDescription`, the problem I describe in this entry exists even after `NSMicrophoneUsageDescription` is added and the permission to use the microphone is granted by the user.

**Comment by DomsterKB** [comment] 2019-08-25 00:33
I can confirm this is happening on Android as well.  All the data in AudioStreamSample are zeros.  Should I open a separate issue?

**Comment by akien-mga** [comment] 2020-01-19 18:18
Closing as duplicate of #33885 which has some additional debugging info.
Note that the permission issue is fixed in 3.2 RC 1, but as mentioned above it doesn't seem sufficient.

**Closed by akien-mga** 2020-01-19 18:18 UTC
Labels: bug, platform:ios, topic:audio, topic:porting

**Comment by audiosdev** [comment] 2022-06-08 12:42
I  developed a Godot iOS plugin that solves the Godot audio recording issue and playback issue in iOS devices. Please see the GitHub repo:

https://github.com/audiosdev/AudiosPlugin-Godot-iOS-Audio-Plugin/

Thanks!
