### ISSUE TITLE
Saving branch as a scene doesn't work in remote scene tree.

### ISSUE THREAD

**Issue by SilencedPerson** [godotengine/godot#55025] opened 2021-11-16 14:20 UTC
### Godot version

3.4 stable

### System information

This issue is present both on windows and linux

### Issue description

It seems to be impossible to save branch in remote scene tree as scene, despite there being an option to do so in right click context menu.

I attempted to generate 3D world inside godot and then save it.

### Steps to reproduce

1. in the editor, make a new scene or pick preexisting one.
2. run the game
3. in the editor, inside the scene tree tab, switch from local to remote scene tree.
4. right click a branch
5. in the context menu that appears, select the "save branch as a scene"
6. save a file pop-up window appears
7. name the file and then click the save button
8. the file is not created

**Comment by Calinou** [comment] 2021-11-16 14:26
Duplicate of https://github.com/godotengine/godot/issues/23132.

**Closed by Calinou** 2021-11-16 14:26 UTC
