### ISSUE TITLE
Cannot create Sprite2D by dragging `Texture`

### ISSUE THREAD

**Issue by zaevi** [godotengine/godot#57953] opened 2022-02-11 02:44 UTC
### Godot version

4.0.alpha2

### System information

Win10

### Issue description

![drag](https://user-images.githubusercontent.com/12966814/153529766-f1792ec4-5123-4b49-84ff-e091d75df621.gif)

Cannot drag `Texture` from FileSystem dock. It works in alpha1.
Dragging other types like `tscn` still works in alpha2.

### Steps to reproduce

/

**Comment by KoBeWi** [comment] 2022-02-11 02:47
Duplicate of #57883, already fixed.

**Closed by KoBeWi** 2022-02-11 02:47 UTC
