### ISSUE TITLE
Unable to type some special characters using the Option Key under macOS

### ISSUE THREAD

**Issue by NoFr1ends** [godotengine/godot#56319] opened 2021-12-29 16:40 UTC
### Godot version

v4.0.dev.custom_build [9f058674a]

### System information

macOS 12.1 arm64/M1 Max

### Issue description

In the latest master build typing all characters which needs the Option key is currently blocked.
That affects the German keyboard especially because key like these are only accessible using the Option key:
```
[
]
{
}
@
```

### Steps to reproduce

1. Use German keyboard layout
2. Try to type the @ sign in the editor (Option + L)

**Comment by NoFr1ends** [comment] 2021-12-29 22:13
It happens in every input element, also happening when running a project and trying to enter characters which requires the Option modifier in a LineEdit.

**Comment by thomashempel** [comment] 2022-01-11 06:36
Having the same issue

**Comment by bruvzg** [comment] 2022-01-11 11:45
Duplicate of #54303 and #6851, this was fixed (#37769) and reverted (#44935) because of conflicts with editor shortcuts.

There's open PR which should fix it - #52452, it needs rebase, but changes are minimal. I do not think we require #43888 for this, at least on macOS both Alt/Option keys act the same, and should input a special character.

The only issues with it is:
> Note that if a shortcut consists of Ctrl + Alt + [some key used for a special character], the character input is handled AND the command associated to the shortcut is executed.

It might be better to check for all existing actions and shortcuts and allow input only if there's no conflicting shortcut (VSCode do it in this way for example), I'll try implementing it in this way.

**Comment by bruvzg** [comment] 2022-01-11 12:14
> It might be better to check for all existing actions and shortcuts and allow input only if there's no conflicting shortcut (VSCode do it in this way for example), I'll try implementing it in this way.

No, this won't work, at least not in the straightforward way. There'r many single letter shortcuts.

**Comment by bruvzg** [comment] 2022-01-11 14:28
> It might be better to check for all existing actions and shortcuts and allow input only if there's no conflicting shortcut (VSCode do it in this way for example), I'll try implementing it in this way.

An alternative fix than is working in this way - #56695, just a bit more complex.

**Comment by Calinou** [comment] 2022-01-25 21:56
Duplicate of https://github.com/godotengine/godot/issues/54303.

**Closed by Calinou** 2022-01-25 21:56 UTC
Labels: bug, platform:macos, topic:input
