### ISSUE TITLE
Android keyboard always writes text at the beginning of the script, regardless of caret position

### ISSUE THREAD

**Issue by thunderstorms-plus** [godotengine/godot#81831] opened 2023-09-17 21:54 UTC
### Godot version

4.1.1, 4.2 dev4

### System information

Android 13

### Issue description

https://github.com/godotengine/godot/assets/30003442/ce7cb952-6834-4023-b0c7-3e054cd6bba2

The problem occurs when I create a script, if I click, start writing code or a space, or back, then what happens is not clear, something changes and the space itself 

### Steps to reproduce

above example video behavior 

### Minimal reproduction project

It’s enough to start a project from scratch and create a script and there’s a video there

**Comment by thunderstorms-plus** [comment] 2023-09-17 23:13
By the way, if you have a physical keyboard, then the same thing...

**Comment by thunderstorms-plus** [comment] 2024-03-10 11:50
Hello, I found out what the problems were and it turned out to be text corrections and she was standing in English, which will affect this
[
![Screenshot_20240310_144200_Samsung Keyboard](https://github.com/godotengine/godot/assets/30003442/97c50316-84d1-49c9-81a1-d2375bbfe47f)
](url)

**Comment by thunderstorms-plus** [comment] 2024-03-10 11:51
but just in case, I’ll test it to make sure it’s really it, the screenshot showed that I removed it and it works fine so far

**Comment by m4gr3d** [comment] 2024-06-23 23:08
Duplicate of https://github.com/godotengine/godot/issues/70751

**Closed by m4gr3d** 2024-06-23 23:08 UTC
Labels: bug, platform:android, topic:editor, topic:porting, topic:input
