### ISSUE TITLE
Momentum cap for Kinematic vs Rigid collision

### ISSUE THREAD

**Issue by slapin** [godotengine/godot#28324] opened 2019-04-23 08:11 UTC
When KinematicBody hits RigidBody it always moves it regardless of its mass. This is not always a right thing, i.e. character can push cars or heavy crates. It would be nice if KinematicBody could have a cap on momentum it transfers to other body and move only in case that other body moves. So behave like Rigid vs Rigid but not recieve any momentum from other body.
Otherwise it is very complicated to set up proper collisions vs heavy objects like cars.

**Comment by MunWolf** [comment] 2019-04-23 10:00
if you use move_and_collide or move_and_slide you do not transfer momentum as all of the momentum calculations etc need to be done by you, if you are able to move rigidbodies with a KinematicBody and you are not manually adding forces to them then you are setting the position directly which is outside the physics system.

When you do that and move the kinematic body inside another one the physics system has to resolve it so that no body is intersecting / inside another one so the move the body.

This means there is no reason for a momentum cap because no momentum is applied.

**Comment by slapin** [comment] 2019-04-23 14:35
Well, I use move_and_slide and my character controller is basically the same as tps-demo character controller.

**Comment by KoBeWi** [comment] 2020-08-16 23:35
Can anyone still reproduce this bug in [Godot 3.2.3 rc3](https://godotengine.org/article/release-candidate-3-2-3-rc-3) or any later release?

If yes, please ensure that an up-to-date Minimal Reproduction Project (MRP) is included in this report (a MRP is a zipped Godot project with the minimal elements necessary to reliably trigger the bug). You can upload ZIP files in an issue comment with a drag and drop.

**Comment by KoBeWi** [comment] 2020-09-28 22:34
Closing due to lack of update. Please comment if you can still reproduce this issue in the latest stable version of Godot.

**Closed by KoBeWi** 2020-09-28 22:34 UTC
Labels: bug, topic:physics
