### ISSUE TITLE
Inspector can't show 3rd level of nesting for runtime dictionaries/arrays (fixed in `master`)

### ISSUE THREAD

**Issue by hilfazer** [godotengine/godot#25375] opened 2019-01-27 12:25 UTC
**Godot version:**

Godot_v3.1-beta2_win64

**OS/device including version:**

Windows 7 x64 SP1

**Issue description:**

When i try to expand doubly nested array or dictionary in Inspector it expands for a very brief time and then collapses. Sometimes it doesn't even expand at all.
Debugger expands just fine.

It happens only for runtime variables (from nodes in the Remote Scene). Thnx to pycbouh for spotting this.

Video:
https://www.dropbox.com/s/i07zsgpbpecqeie/GodotInspectorNestingCollapse.avi?dl=0

**Steps to reproduce:**
Place a breakpoint in _ready() function
Run the project
Try to fully expand "dict" variable in Inspector 

**Minimal reproduction project:**

 Dlownload link: https://downgit.github.io/#/home?url=https://github.com/hilfazer/Projects/tree/master/Godot/EngineIssues/InspectorDictionaryCollapse

Github location: https://github.com/hilfazer/Projects/tree/master/Godot/EngineIssues/InspectorDictionaryCollapse

**Comment by TicklesTheBrain** [comment] 2019-03-17 13:33
Just wanted to confirm this is still happening on 3.1 stable on Windows 10.

**Comment by menip** [comment] 2019-05-29 22:09
Can confirm this is an issue:
![NestedDictBug](https://user-images.githubusercontent.com/22862244/58594826-a11cdb80-8223-11e9-915f-052d920d964b.gif)

**Comment by hilfazer** [comment] 2019-06-03 17:55
If only arrays are in play bug doesn't surface
![5LevelsNestedArray](https://user-images.githubusercontent.com/29497869/58823198-6ce95680-8639-11e9-9c8a-6c45bb3231ce.png)

So it's all Dictionary's fault!

**Comment by akien-mga** [comment] 2019-11-19 10:14
Still valid in the current master branch (8450658fa).

**Comment by DoubleCakes** [comment] 2019-12-09 19:11
I'm having this problem too

Steam version 3.1.2

**Comment by pycbouh** [comment] 2020-05-19 10:19
So I've debugged it a bit and here's what happens.

First of all, the issue only appears in the Inspector for the remote debugger. Nested dictionaries fold and unfold without a problem when checking them in the editor without a running scene (values must be set manually or via a tool script).

Secondly, the issue has nothing to do with folding. The problem is that the inspector node for a dictionary property is perpetually updated. Which causes it to redraw on each frame and as a result folding to appear broken. Same does not happen with arrays. You can put a breakpoint into `EditorPropertyArray::update_property()`, and it will only trigger if you actually change something (this includes folding).

With `EditorPropertyDictionary::update_property()` the situation is different. It gets triggered constantly. If you go up the call stack you'll see that this is because on each frame there is a chain of signals that gets triggered informing the Inspector that the property has changed, when in fact nothing has changed.

Problem seems to sparkle from `EditorDebuggerInspector::add_object`. [This check](https://github.com/godotengine/godot/blob/dee8f8db745e58caedbf49bbc13a2fdcc8fb1da4/editor/debugger/editor_debugger_inspector.cpp#L186-L189) does not pass and the value is overridden, the `changed` set is updated, and signals are then sent.

https://github.com/godotengine/godot/blob/dee8f8db745e58caedbf49bbc13a2fdcc8fb1da4/editor/debugger/editor_debugger_inspector.cpp#L186-L189

While at the moment of the assignment the `var` variable contains a correct reference to the Dictionary in question, the `debugObj->prop_values[pinfo.name]` seems to always contain `NULL`. It looks like the value is destroyed somewhere after the assignment and thus the debug reference is constantly empty and requires to be updated while the value itself stays the same.

Any ideas where to look for that destruction?

**Comment by pycbouh** [comment] 2020-05-19 11:54
It turned out, I was reading the debugger wrong. The old value is still there, it just can't be properly compared to the new one.

![image](https://user-images.githubusercontent.com/11782833/82323255-74d40f00-99e0-11ea-8300-bfd39ddbffd9.png)

Seems to be related to #29222 (thanks @bojidar-bg).

**Comment by TicklesTheBrain** [comment] 2020-10-28 12:37
Since #29222 is closed and #35816 is being debated, this issue is still in need of a temporary fix, especially something that could be applied to 3.2

**Comment by svendixon** [comment] 2021-08-07 00:34
Any progress on this? I'm in 3.3.2 stable on Windows 10 and this still exists. The only work around I see, is to drop a breakpoint in the code and use the debugger just to see the nested dictionary... pretty annoying.

**Comment by Calinou** [comment] 2021-08-07 13:03
> Any progress on this? I'm in 3.3.2 stable on Windows 10 and this still exists. The only work around I see, is to drop a breakpoint in the code and use the debugger just to see the nested dictionary... pretty annoying.

As far as I know, nobody knows how to resolve this bug yet.

**Comment by pycbouh** [comment] 2021-08-07 13:15
I don't think that we have a way to compare arrays by value yet, even in master.

**Comment by MrOutsider** [comment] 2021-09-06 20:44
Glad I found others have this problem. I independently replicated this bug.
I am on Godot v3.3.3.stable.official

**Comment by akien-mga** [comment] 2021-11-09 12:51
Fixed by #35816.
![Screenshot_20211109_135105](https://user-images.githubusercontent.com/4701338/140927428-aff28a23-e463-4f82-8fa9-762728f7e28d.png)

**Comment by dalexeev** [comment] 2021-12-27 17:06
Reproduced in 3.4.2. Looks like this fix hasn't been backported from master?

**Comment by Calinou** [comment] 2021-12-27 17:10
> Reproduced in 3.4.2. Looks like this fix hasn't been backported from master?

Reimplementing https://github.com/godotengine/godot/pull/35816 for `3.x` would break compatibility with existing projects, not to mention there is no way to get the old behavior back: https://github.com/godotengine/godot/pull/35816#issuecomment-964115214

**Comment by Calinou** [comment] 2022-01-04 20:43
Reopening, as this still needs a fix in `3.x`.

**Comment by akien-mga** [comment] 2022-01-04 21:17
Well I don't think this will ever be fixed in 3.x, which is why I closed it as fixed in 4.0.
We can keep it open if users want but I wouldn't give false hopes, this is not easy to fix and probably not worth it for 3.x.

**Comment by akien-mga** [comment] 2022-05-04 06:22
Fixed in 3.5 by #60737.

**Closed by akien-mga** 2022-05-04 06:22 UTC
Labels: bug, topic:editor, confirmed
