### ISSUE TITLE
move_and_collide() does not work if there is a wall left and right

### ISSUE THREAD

**Issue by golddotasksquestions** [godotengine/godot#38321] opened 2020-04-29 10:58 UTC
**Godot version:** 3.2.1 stable

**OS/device including version:** Win64

**Issue description:**
![move_and_collide_grid_bug](https://user-images.githubusercontent.com/47016402/80588597-edb2fd00-8a18-11ea-8b79-6fc760f364b2.gif)

The Player would collide as expected when moving head on against a Tilemap collisionshape, but does not collide with the same collisionshape head on, if there is also another collisionshape reft and right from the direction the player is moving to

**Code:**
```
extends KinematicBody2D

var gridsize = 16
var inputs = {
	"ui_up": Vector2.UP,
	"ui_down": Vector2.DOWN,
	"ui_left": Vector2.LEFT,
	"ui_right": Vector2.RIGHT
}

func _unhandled_input(event):
	for dir in inputs.keys():
		if event.is_action_pressed(dir):
			var velocity = inputs[dir] * gridsize
			move(velocity)

func move(velocity):
	var collision = move_and_collide(velocity, true, true, true)
	if collision:
		print("colliding with ", collision.get_collider().name)
	collision = move_and_collide(velocity)
	print(collision)
```

Related:
https://github.com/godotengine/godot/issues/36432

**Minimal reproduction project:**
[Grid_Movement_issue.zip](https://github.com/godotengine/godot/files/4551229/Grid_Movement_issue.zip)

**Comment by KoBeWi** [comment] 2020-04-30 18:10
Duplicate of #37798 actually...

**Closed by KoBeWi** 2020-04-30 18:10 UTC
Labels: bug, topic:physics
