### ISSUE TITLE
Transparent BG on main viewport is no longer can pass through mouse event.

### ISSUE THREAD

**Issue by AureaFUNSoft** [godotengine/godot#42105] opened 2020-09-16 02:57 UTC
**Godot version:**

3.2.2.stable
3.2.3.rc6

**OS/device including version:**

Windows 10

**Issue description:**

This is follow up of this [my post](https://godotforums.org/discussion/23996/transparent-bg-on-main-viewport-no-longer-pass-through-mouse-event) on godot forum.

To better understand what I mean please watch [this video](https://www.youtube.com/watch?v=LCy-FwDXNkw).

See that I can interact with windows behind the game. This was possible in Godot 3.2.1. Then recently I open the same project with Godot 3,2,2 (also 3.2.3.rc6) it didn't work anymore.

**Steps to reproduce:**
Open with Godot 3.2.1 it can.
Open with Godot 3.2.2+ it can't.

**Minimal reproduction project:**

[Creep.zip](https://github.com/godotengine/godot/files/5229322/Creep.zip)

**Comment by dankan1890** [comment] 2020-09-16 06:58
regression (change of behavior) between 3.2.2.beta2 and 3.2.2.beta3

**Comment by akien-mga** [comment] 2020-09-16 07:06
Duplicate of #39914.

This was an intentional change to improve performance and to make things behave the same on all platforms (this "clickthrough" feature was not intentional and only worked on Windows).

See #39944 for a follow-up PR that aims to implement the feature properly for all platforms.

**Closed by akien-mga** 2020-09-16 07:06 UTC
