### ISSUE TITLE
Copypasting StaticBody2D with shape in scene doesn't make copy of collision shape. 

### ISSUE THREAD

**Issue by RedwanFox** [godotengine/godot#64664] opened 2022-08-20 17:51 UTC
### Godot version

4.0dev 0c5f25495

### System information

Windows 11

### Issue description

Copypasted StaticBody2D in scene share CollisionShape2D shape. All collision shapes will reference same subresource.

### Steps to reproduce

1. Create 2D scene
2. Create StaticBody2D, give it CollisionShape2D with defined shape resource
3. Copy StaticBody2D subtree several times in scene
4. Try to resize collision shape - all collision shapes will resize

**Comment by Zireael07** [comment] 2022-08-20 17:52
That's because resources (and shapes are resources) are shared by default for performance reasons.

A couple of proposals have been made to rectify that because esp. for collision shapes this catches people unawares.

**Comment by Calinou** [comment] 2022-08-20 20:30
Duplicate of https://github.com/godotengine/godot/issues/40887 and/or https://github.com/godotengine/godot/issues/28246 (same cause).

**Closed by Calinou** 2022-08-20 20:30 UTC
