### ISSUE TITLE
Select frames window shows misaligned grid at certain zoom levels

### ISSUE THREAD

**Issue by berarma** [godotengine/godot#52745] opened 2021-09-16 14:02 UTC
### Godot version

v3.4.beta4.official.6a058cbf3

### System information

Debian GNU/Linux 11

### Issue description

When using the zoom controls in the "Select frames" window (AnimatedSprite node), the grid gets misaligned with the sprites at some zoom levels. It's really easy to see with wide sprite sheets because the error adds up for every sprite in the horizontal direction. At zoom level 1 it looks aligned, and I think that for every integer scale value too, but other values misalign the grid and the sprites.

### Steps to reproduce

Take a wide sprite sheet (I've used one with 20 sprites, 16 bytes wide each) so the grid positioning error is more evident. Set the horizontal and vertical counts correctly for the sprite sheet and zoom in. You'll see the grid misalining towards the right side of the sprite sheet.

**Comment by kleonc** [comment] 2021-09-16 16:40
I've fixed it lately, check out #52461 (it's not merged yet though).

**Comment by berarma** [comment] 2021-09-16 18:18
> I've fixed it lately, check out #52461 (it's not merged yet though).

Thanks! I couldn't find it in the issues list and didn't think to search for it in the PR. I'll try it as soon as it's merged and released.

**Comment by Calinou** [comment] 2021-09-16 19:56
Duplicate of https://github.com/godotengine/godot/issues/52099.

**Closed by Calinou** 2021-09-16 19:56 UTC
