### ISSUE TITLE
Android build crashes after adding AudioStream due to audio filename containing non-ASCII characters

### ISSUE THREAD

**Issue by tshrpl** [godotengine/godot#56406] opened 2022-01-01 18:32 UTC
### Godot version

Godot Engine v3.4.2.stable.official.45eaa2daf, Export Templates 3.4.2.stable

### System information

Windows 10 GLES3 AMD Radeon (TM) R5 M330, Xiaomi Redmi 8

### Issue description

game crashes after adding an audio stream
this is the error i get
```
Installing to device (please wait...): Xiaomi Redmi 8
--- Device API >= 21; debugging over USB ---
--- DEVICE API >= 21; DEBUGGING OVER USB ---
Reverse result: 0
--- Debugging process started ---
--- Debugging process stopped ---
 platform/windows/os_windows.cpp:2886 - Condition "!process_map->has(p_pid)" is true. Returned: FAILED
```

### Steps to reproduce

i have attached a minimal project below
- set the main scene to "with_audio"
- run the game in debug mode

### Minimal reproduction project

https://drive.google.com/file/d/1Sx2gVNNzM5OSNPW2vx-o3LwFEQYaXSL7/view?usp=sharing

**Comment by Calinou** [comment] 2022-01-01 20:06
@tshrpl Does it crash when you run the project on Windows (before and after exporting)?

**Comment by tshrpl** [comment] 2022-01-01 20:38
yes, renaming the music files to only include non-ascii characters solves this issue

**Comment by Calinou** [comment] 2022-01-01 22:19
Duplicate of https://github.com/godotengine/godot/issues/18222.

**Closed by Calinou** 2022-01-01 22:19 UTC
Labels: bug, platform:android, needs testing, topic:audio, crash
