### ISSUE TITLE
Fix exporting .csv file when specified in the filter

### ISSUE THREAD

**Issue by alexis-evelyn** [godotengine/godot#31749] opened 2019-08-28 22:51 UTC
**Godot version:**
3.2-dev

**OS/device including version:**
Mac OSX Mojave

**Issue description:**
In order to work around [this issue](https://github.com/godotengine/godot/issues/31703) of being able to load a translation on the fly without switching the game's locale, I decided to parse the translations myself.

The problem is, I cannot make heads or tails on the format of the .translation files (even after looking at Godot's source), so I decided to parse the csv file (that generated them), directly. That goes well and I have translating on the fly.

I am thinking, cool, let's export this and make sure the exported executable works too (knowing about how resources aren't exported if they aren't standard resources). I add *.csv to the export filter to ensure the csv file is exported. It wasn't.

After debugging and looking through the exported files, I have found that even with the filter, the csv file isn't exported. To make sure I was setting everything up correctly, I copied the csv file and changed its extension to .txt. This works fine.

Now, I have no plans on copying the csv file every time I make a change, so I decided to symlink the csv file using the command `ln -s default.csv default.txt`. Now, I have my problem solved.

I decided to file an issue on the tracker as the .csv file should be exported if the developer specifies for it to (especially since not all csv files are locale translations).

**Steps to reproduce:**
1. Add csv file to project
2. Add *.csv to export filter
3. Export game and find that the csv file is missing.

**Minimal reproduction project:**
None Provided

**Comment by merumelu** [comment] 2019-08-29 15:32
Just a note about your original problem: there is no need to parse the translation files yourself. They are resources so you can just do
```gdscript
var translation = load("res://path/to/your.translation")`
```
and Godot will give you a [Translation](https://docs.godotengine.org/en/3.1/classes/class_translation.html) resource.

**Comment by alex-evelyn** [comment] 2019-08-30 01:30
Thanks @merumelu! This helps a lot!

**Comment by burstina** [comment] 2019-09-08 14:34
I experienced the same problem with .csv files in 3.1.1: exporting the project using Windows Desktop  template does not gather .csv , so they have to follow arout with .exe and .pck

**Comment by GreenBeakCrow** [comment] 2019-12-16 20:40
Being curious I have looked into the code and found that `.csv` files are generally not included in exports because, as far as I understand it, they have a matching `.import` file but don't actually import anything into `./.import` and thus get skipped during export (in `EditorExportPlatform::export_project_files`).

I have made a fix, though as I'm not familiar with Godot's architecture I don't know if this fix fits well. Also there are other ways around. Tried to minimise the impact. As I didn't talk to any Godot developer as the contribution guidelines say, I didn't open a pull request yet. So if anyone who is a Godot developer might take a look, please [see here](https://github.com/godotengine/godot/commit/39388059f58a79c5e9ea484f6075d2ad2b838feb). In case that's not the Godot way I'd be happy to get some suggestions on what to change instead.

**Comment by mhilbrunner** [comment] 2020-05-28 15:45
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!

**Comment by Zireael07** [comment] 2020-05-28 15:47
I think it's a bug and not an enhancement. The export filter is exactly for exporting files which are not resources in Godot....

**Comment by mhilbrunner** [comment] 2020-05-28 17:39
I agree.

**Comment by akien-mga** [comment] 2021-03-24 08:29
Duplicate of #38957, fixed by #47268.
Use the new "Keep" import option to prevent importing `.csv` files as `.translation` resources if they are meant to be parse manually and exported.

**Closed by akien-mga** 2021-03-24 08:29 UTC
Labels: bug, topic:editor, topic:porting
