### ISSUE TITLE
Wrong warning message for STATIC_CALLED_ON_INSTANCE

### ISSUE THREAD

**Issue by pkowal1982** [godotengine/godot#84843] opened 2023-11-13 13:13 UTC
### Godot version

4.2.beta5

### System information

Ubuntu 22

### Issue description

STATIC_CALLED_ON_INSTANCE has wrong warning message.
Running this code:
```
extends Node2D


func _ready() -> void:
	WrongMessage.static_function()


class WrongMessage:


	func function() -> void:
		static_function()


	static func static_function() -> void:
		pass
```
shows warning:
`The function "static_function()" is a static function but was called from an instance. Instead it should be directly called from the type "RefCounted.static_function()".`

But:
1. It was not called from an instace.
2. It's not part of RefCounted.

### Steps to reproduce

Run minimal reproduction project.

### Minimal reproduction project

[Project saved in Godot4.2beta5](https://github.com/godotengine/godot/files/13335069/wrongmessage.zip)

**Comment by AThousandShips** [comment] 2023-11-13 13:20
And the warning is actually for line 4? And not for 9?

`WrongMessage` *is* `RefCounted`

**Comment by pkowal1982** [comment] 2023-11-13 17:42
Yeah, looks like duplicate.

**Comment by AThousandShips** [comment] 2023-11-13 17:43
Duplicate of https://github.com/godotengine/godot/issues/74397

**Closed by AThousandShips** 2023-11-13 17:43 UTC
Labels: topic:gdscript, needs testing
