### ISSUE TITLE
Bone2D fail deform when another instance is present in scene

### ISSUE THREAD

**Issue by marcosbitetti** [godotengine/godot#20040] opened 2018-07-08 12:49 UTC
**Godot version:**
3.1.dev.custom_build.e6734a2

**OS/device including version:**
Ubuntu Studio

**Issue description:**
Bone2D fail deform when another instance is present in scene

**Steps to reproduce:**
Make a 2d skeletal deform as the tutorial
Make a second skeletal deform in another poligon2d.

Video from the issue

[https://youtu.be/ZI45MTLXkT8](youtube)

**Comment by Ranoller** [comment] 2018-07-08 13:29
Not only that, if you make a skeleton2D child of a Node2D and you resize that Node2D, the skeletal deform fails.

**Comment by marcosbitetti** [comment] 2019-01-22 08:10
New updates:
now, a vertex assigned to any bone is hide from scene! (3.1 custom release from january/2019)

**Comment by reduz** [comment] 2019-01-26 19:35
I would reaaally appreciate reproduction projects for this, as-is there is not much I can do.

**Comment by reduz** [comment] 2019-02-13 19:33
I just can't reproduce this. Maybe you duplicated and forgot to re-assign skeleton?

**Comment by reduz** [comment] 2019-02-14 15:18
Please reopen if enough information can be provided for reproduction, Closing in the meantime.

**Closed by reduz** 2019-02-14 15:18 UTC
Labels: bug, topic:physics
