### ISSUE TITLE
Input.parse_input_event() mouse coordinates broken if using viewport scaling

### ISSUE THREAD

**Issue by elvisish** [godotengine/godot#85931] opened 2023-12-08 18:01 UTC
### Tested versions

Reproducible in 4.1.1, 4.1.3, 4.2 stable.

### System information

Windows 10

### Issue description

When simulating a mouse click to control UI elements (such as buttons, sliders or check boxes) the position of the simulated clicks are incorrect if using viewport scaling. It works if setting the aspect to "keep height" or "expand" but doesn't work on any of the others. HiDPI doesn't seem to affect it either way.

### Steps to reproduce

- Create a simulated click:

```swift
if Input.is_action_just_pressed("gp_use"):
		var evt := InputEventMouseButton.new()
		evt.button_index = MOUSE_BUTTON_LEFT
		evt.position = get_viewport().get_mouse_position()
		evt.pressed = true
		Input.parse_input_event(evt)
		
	if Input.is_action_just_released("gp_use"):
		var evt := InputEventMouseButton.new()
		evt.button_index = MOUSE_BUTTON_LEFT
		evt.position = get_viewport().get_mouse_position()
		evt.pressed = false
		Input.parse_input_event(evt)
```

- Toggle the viewport scale settings:
![image](https://github.com/godotengine/godot/assets/16231628/fb9908e5-40bb-41d9-aa86-c9f7c27a0864)

### Minimal reproduction project (MRP)

[test_input_viewport_scaling.zip](https://github.com/godotengine/godot/files/13619442/test_input_viewport_scaling.zip)

**Comment by elvisish** [comment] 2023-12-08 18:05
> 4.1.3

Just tried 4.1.3 and it's still broken.

**Comment by Sauermann** [comment] 2023-12-08 21:30
Please be aware, that you are mixing different coordinate systems and the behavior, that you describe is expected.

- `Input.parse_input_event` expects the event in screen coordinates.
- `get_viewport().get_mouse_position()` returns viewport coordinates.

You can find more details about the different coordinate systems at:
https://docs.godotengine.org/en/latest/contributing/development/core_and_modules/2d_coordinate_systems.html

Try
``` gdscript
    evt.position = Input.get_mouse_position()
```

**Comment by elvisish** [comment] 2023-12-08 21:39
> Please be aware, that you are mixing different coordinate systems and the behavior, that you describe is expected.
> 
> * `Input.parse_input_event` expects the event in screen coordinates.
> * `get_viewport().get_mouse_position()` returns viewport coordinates.
> 
> You can find more details about the different coordinate systems at:
> 
> * https://docs.godotengine.org/en/latest/tutorials/2d/2d_transforms.html
> * https://docs.godotengine.org/en/latest/contributing/development/core_and_modules/2d_coordinate_systems.html
> 
> Try
> 
> ```gdscript
>     evt.position = Input.get_mouse_position()
> ```

Thanks, I tried that but I get: `Static function "get_mouse_position()" not found in base "GDScriptNativeClass".`

**Comment by Sauermann** [comment] 2023-12-08 21:48
Right, that function isn't exposed. Sorry for that.
Please try the following as indicated in the first linked documentation page:
``` gdscript
    evt.position = get_viewport().get_screen_transform() * get_viewport().get_mouse_position()
```

**Comment by elvisish** [comment] 2023-12-08 21:55
> Right, that function isn't exposed. Sorry for that. Please try the following as indicated in the first linked documentation page:
> 
> ```gdscript
>     evt.position = get_viewport().get_screen_transform() * get_viewport().get_mouse_position()
> ```

Thanks, that's perfect!

**Comment by Sauermann** [comment] 2023-12-11 19:17
Closing this issue based on the comment above, that the issue is resolved.

**Closed by Sauermann** 2023-12-11 19:17 UTC
Labels: discussion, topic:input
