### ISSUE TITLE
Restore Scenes on Load fails to draw CSG

### ISSUE THREAD

**Issue by lexum0** [godotengine/godot#59041] opened 2022-03-11 18:59 UTC
### Godot version

3.4.3, 3.4.4.rc1

### System information

macOS

### Issue description

Reopening a project will 'restore' the open scenes, but will fail to draw CSG nodes until the scene is closed and reopened

### Steps to reproduce

This uses Editor Settings > Interface > Scene Tabs > Restore Scenes on Load = ON

1. Open a scene that has CSG nodes. Change the tab to another scene and close the project. 

https://user-images.githubusercontent.com/2546522/157934032-a720074c-721e-4979-8752-e17f2e7815fd.mov

2. Open the project, go to the scene with CSG nodes and they will not be drawn

https://user-images.githubusercontent.com/2546522/157934049-db6edfdf-0057-4ce1-89cb-b5b9a61ccf2d.mov

3. Close the scene and reopen it for it to work again

https://user-images.githubusercontent.com/2546522/157934062-a0f8bae2-675a-4dd4-ab05-02a64297f486.mov

### Minimal reproduction project

[CCD.zip](https://github.com/godotengine/godot/files/8234688/CCD.zip)

**Comment by Calinou** [comment] 2022-03-11 19:02
Duplicate of https://github.com/godotengine/godot/issues/54445 (fixed by https://github.com/godotengine/godot/issues/54445, will be in 3.4.4rc2).

**Closed by Calinou** 2022-03-11 19:02 UTC
