### ISSUE TITLE
WebRTC extension in webrtc_signaling example crashes editor

### ISSUE THREAD

**Issue by benpm** [godotengine/godot#68850] opened 2022-11-18 19:16 UTC
### Godot version

4.0 beta 5

### System information

Pop!_OS 22.04 LTS

### Issue description

  I'm attempting to use the [WebRTC GDNative Extension](https://github.com/godotengine/webrtc-native/releases) with the [webrtc_signaling](https://github.com/godotengine/godot-demo-projects/tree/master/networking/webrtc_signaling) example with Godot 4.0 beta 5.
  
  At first, I could open the project but the extension wouldn't load, citing that the object files included with the extension were missing from `~/.local/share/lib/`. After copying the files included in `godot-extension-webrtc/lib` into that directory and closing the editor, I can no longer open the project at all. Instead, I get this error:
  
  ```
  
  ================================================================
  handle_crash: Program crashed with signal 11
  Engine version: Godot Engine v4.0.beta5.official (89a33d28f00fec579184fb7193790d40aa09b45b)
  Dumping the backtrace. Please include this when reporting the bug on: https://github.com/godotengine/godot/issues
  [1] /lib/x86_64-linux-gnu/libc.so.6(+0x42520) [0x7f150ea42520] (??:0)
  [2] /home/ben/.local/share/applications/Godot_v4.0-beta5_linux.x86_64() [0x429d7e8] (??:0)
  [3] /home/ben/.local/share/applications/Godot_v4.0-beta5_linux.x86_64() [0x43e433b] (??:0)
  [4] godot::String::init_bindings() (??:0)
  [5] godot::Variant::init_bindings() (??:0)
  [6] godot::GDExtensionBinding::init(GDNativeInterface const*, void*, GDNativeInitialization*) (??:0)
  [7] /home/ben/.local/share/applications/../lib/libwebrtc_native.linux.template_debug.x86_64.so(webrtc_extension_init+0x5d) [0x7f1508be4e3d] (??:0)
  [8] /home/ben/.local/share/applications/Godot_v4.0-beta5_linux.x86_64() [0x42b69b1] (??:0)
  [9] /home/ben/.local/share/applications/Godot_v4.0-beta5_linux.x86_64() [0x431a436] (??:0)
  [10] /home/ben/.local/share/applications/Godot_v4.0-beta5_linux.x86_64() [0x402f792] (??:0)
  [11] /home/ben/.local/share/applications/Godot_v4.0-beta5_linux.x86_64() [0x4042599] (??:0)
  [12] /home/ben/.local/share/applications/Godot_v4.0-beta5_linux.x86_64() [0x408f11f] (??:0)
  [13] /home/ben/.local/share/applications/Godot_v4.0-beta5_linux.x86_64() [0x4318146] (??:0)
  [14] /home/ben/.local/share/applications/Godot_v4.0-beta5_linux.x86_64() [0xd9dd29] (??:0)
  [15] /lib/x86_64-linux-gnu/libc.so.6(+0x29d90) [0x7f150ea29d90] (??:0)
  [16] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0x80) [0x7f150ea29e40] (??:0)
  [17] /home/ben/.local/share/applications/Godot_v4.0-beta5_linux.x86_64() [0xdbe18e] (??:0)
  -- END OF BACKTRACE --
  ================================================================
  [1]    30336 IOT instruction (core dumped)  ~/.local/share/applications/Godot_v4.0-beta5_linux.x86_64 project.godot
  ```

I'm posting this here because it looks like some sort of unhandled error on the editor's side of things, although [I've created an issue on the extension's page](https://github.com/godotengine/webrtc-native/issues/69) as well.

### Steps to reproduce

1. Unzip the provided project files
2. Copy contents of godot-extension-webrtc/lib to ~/.local/share/lib
3. Attempt to open project with Godot 4.0 beta 5

### Minimal reproduction project

[webrtc_signaling_w_extension.zip](https://drive.google.com/file/d/1yxfGDh9a7LrE-svAwIMWlNqK5cEAwSCH/view?usp=share_link)

**Comment by akien-mga** [comment] 2022-11-18 22:33
Duplicate of https://github.com/godotengine/webrtc-native/issues/69.

**Closed by akien-mga** 2022-11-18 22:33 UTC
Labels: bug, topic:gdextension, topic:network, crash
