### ISSUE TITLE
impossible to open a project from 3.1-beta4 to 3.1.1-stable

### ISSUE THREAD

**Issue by lastrodamo** [godotengine/godot#30418] opened 2019-07-07 23:22 UTC
**Godot version:**

3.1.1.stable.official

**OS/device including version:**

OpenGL ES 3.0 Renderer: GeForce GTX 980/PCIe/SSE2
410.93 nvidia driver

**Issue description:**

I open my project and edit him (or double clic on) and the godot software directly crash !
If i launch the project it's working but there is a console error :
WARNING: _notification: AnimationTreePlayer has been deprecated. Use AnimationTree instead.
   At: scene/animation/animation_tree_player.cpp:405.

**Steps to reproduce:**
Download this project [http://3dminfographie.com/images/godot/interface.zip](url)
Open godot_3.1.1-stable
Scan the project
Edit it !

**Minimal reproduction project:**

**Comment by KoBeWi** [comment] 2019-07-07 23:49
The project opens and runs for me just fine. Maybe try removing the .import directory and project cache from %appdata%/Godot and %temp%/Godot?

**Comment by lastrodamo** [comment] 2019-07-08 00:09
Where is %appdata%/Godot and %temp%/Godot ?
Is it ~/.cache/godot ?
In /tmp/ no files are on it !...

**Comment by lastrodamo** [comment] 2019-07-08 00:13
I have this errors when i launch it
ERROR: _load: No loader found for resource: res://textures/background.png
   At: core/io/resource_loader.cpp:285.
ERROR: poll: res://main.tscn:4 - Parse Error: [ext_resource] referenced nonexistent resource at: res://textures/background.png
   At: scene/resources/resource_format_text.cpp:440.
ERROR: load: Condition ' err != OK ' is true. returned: RES()
   At: core/io/resource_loader.cpp:208.
ERROR: _load: Failed loading resource: res://main.tscn
   At: core/io/resource_loader.cpp:285.
ERROR: start: Failed loading scene: res://main.tscn
   At: main/main.cpp:1739.
WARNING: cleanup: ObjectDB Instances still exist!
   At: core/object.cpp:2095.
ERROR: clear: Resources Still in use at Exit!
   At: core/resource.cpp:425.

**Comment by KoBeWi** [comment] 2019-07-08 00:30
> Where is %appdata%/Godot and %temp%/Godot ?

Ah, your are not on Windows. Maybe it's some system-specific issue...

**Comment by lawnjelly** [comment] 2019-07-08 08:40
I had a look, quite a large minimal reproduction project :smile: but I understand. It crashed on mine also with 3.1.1 stable. So I compiled my latest master and it also goes down when debugging, I think I've tracked it down:

In scripts/MeshInstance.gd
You have the line:
`extends "res://scripts/MeshInstance.gd"`
This appears to be going into a recursive loop and crashing. I tried fixing this in this script and the same circular reference occurred in scripts/TextureButton_fullscreen.gd.

I *think* this is the problem, I have not too much time to spend on it. You can fix it in the script by making sure scripts do not inherit from themselves, but really there should be a check for this condition in Godot and flag an error message if this occurs.

**Comment by lastrodamo** [comment] 2019-07-09 10:30
Thanks a lot lawnjelly

I'm a completly noob with gdscript
i had generate a loop!

**Comment by lawnjelly** [comment] 2019-07-09 11:23
No problem! It was still well worth reporting and a valid issue, because the engine should be able to flag this as an error rather than crash. If it has happened to you it will happen to others too. :+1:

**Comment by lastrodamo** [comment] 2019-07-09 14:57
lawnjelly
I clean my code a little bit with bugs on 3.1.1-stable
I had made this project 1 years ago
You can download a binary app here [http://4d-illusion.com/en/interactive/view/?id=1](url) 

ps : I'm try to compile this app whithout pulseaudio and i can't cause godot can't compile whithout pulse

**Comment by lawnjelly** [comment] 2019-07-09 17:34
> ps : I'm try to compile this app whithout pulseaudio and i can't cause godot can't compile whithout pulse

You should really post this as a separate issue (or ask first maybe on https://godotengine.org/qa/ ?). Putting more than one issue in a single thread makes it too confusing to keep track of.. :hushed:

**Comment by akien-mga** [comment] 2019-11-26 08:19
Closing as duplicate of #9609.

**Closed by akien-mga** 2019-11-26 08:19 UTC
Labels: bug, crash, topic:gdscript
