### ISSUE TITLE
Editor crash when typing a string or int into an autoload function

### ISSUE THREAD

**Issue by JHDev2006** [godotengine/godot#96696] opened 2024-09-07 21:08 UTC
### Tested versions

- happens only in 4.4 dev-1

### System information

Godot v4.4.dev1 - Windows 10.0.22631 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3070 Ti (NVIDIA; 31.0.15.4592) - AMD Ryzen 7 5800X 8-Core Processor (16 Threads)

### Issue description

when you try and type in a string on int, into an autoload function, the editor immediately crashes. when either "" or any number has been typed.

### Steps to reproduce

Create an autoload, with a function that takes either a string or int as an argument. 
go into another script and try to call the function, while attempting to use any string, or any int, as an argument.
observe how the engine just crashes, yay!

### Minimal reproduction project (MRP)

[crash-check.zip](https://github.com/user-attachments/files/16919923/crash-check.zip)

**Comment by matheusmdx** [comment] 2024-09-07 21:34
Tested on latest mater v4.4.dev.custom_build [05d9854] and the crash doesn't happen, probably a duplicate of #96239 so is already fixed in master and will come on dev2.

**Closed** 2024-09-07 22:21 UTC
