### ISSUE TITLE
godot -e with wrong filename results with segfault on OS X 10.10.1 (lldb output)

### ISSUE THREAD

**Issue by Marqin** [godotengine/godot#972] opened 2014-12-13 23:36 UTC
bin/godot.osx.tools.32 -e SOME_RANDOM_TEXT

Result (from lldb):
http://pastebin.com/nQP6HDJ2

**Comment by akien-mga** [comment] 2015-11-05 08:48
Is this still valid in the current master branch?

**Comment by Marqin** [comment] 2015-11-05 13:38
I'll check it and answer here.

2015-11-05 9:48 GMT+01:00 Rémi Verschelde <notifications@github.com>:

**Comment by akien-mga** [comment] 2016-03-24 09:40
> I'll check it and answer here.

What's the answer? :D

**Comment by Marqin** [comment] 2016-03-24 10:53
```
 ~/Library/Application Support/Steam/SteamApps/common/Godot Engine  ./godot.osx.opt.tools.32 -e SOME_RANDOM_TEXT
ERROR: create: Condition ' !create_func ' is true. returned: 0
   At: core/os/mutex.cpp:39.
nscreen count 1
added screen 1
ERROR: load: No loader found for resource: res://SOME_RANDOM_TEXT
   At: core/io/resource_loader.cpp:218.
ERROR: start: Failed loading scene: res://SOME_RANDOM_TEXT
   At: main/main.cpp:1428.
ERROR: free: Attempt to free invalid ID
   At: servers/spatial_sound/spatial_sound_server_sw.cpp:598.
ERROR: free: Attempt to free invalid ID
   At: servers/spatial_sound_2d/spatial_sound_2d_server_sw.cpp:612.
WARNING: cleanup: ObjectDB Instances still exist!
   At: core/object.cpp:1904.
```

**Comment by akien-mga** [comment] 2016-03-24 11:02
I'll see if I can reproduce on Linux, I guess the main.cpp should have a cleaner exit procedure after ``ERROR: load: No loader found for resource: res://SOME_RANDOM_TEXT``.

**Comment by akien-mga** [comment] 2016-04-21 20:39
There does not seem to be a crash on Linux, it seems to just close down. At least running it through gdb I did not get any backtrace.

**Comment by Marqin** [comment] 2016-04-22 09:03
Then it should print some proper message, and not:

"ERROR: create: Condition ' !create_func ' is true. returned: 0
   At: core/os/mutex.cpp:39.
nscreen count 1
added screen 1
ERROR: load: No loader found for resource: res://SOME_RANDOM_TEXT
   At: core/io/resource_loader.cpp:218.
ERROR: start: Failed loading scene: res://SOME_RANDOM_TEXT
   At: main/main.cpp:1428.
ERROR: free: Attempt to free invalid ID
   At: servers/spatial_sound/spatial_sound_server_sw.cpp:598.
ERROR: free: Attempt to free invalid ID
   At: servers/spatial_sound_2d/spatial_sound_2d_server_sw.cpp:612.
WARNING: cleanup: ObjectDB Instances still exist!
   At: core/object.cpp:1904."

2016-04-21 22:40 GMT+02:00 Rémi Verschelde <notifications@github.com>:

**Comment by neikeq** [comment] 2016-06-03 14:31
If it crashes, then the backtrace would be very welcome.

**Comment by Marqin** [comment] 2016-06-03 15:17
@neikeq it's in comment https://github.com/godotengine/godot/issues/972#issuecomment-200786383

**Comment by neikeq** [comment] 2016-06-03 15:20
@Marqin I don't see any backtrace in that comment :(

**Comment by volzhs** [comment] 2016-06-03 16:02
in my short test,
``godot.windows.tools.64.exe -e RANDOM_TEXT`` > crash
``godot.windows.tools.64.exe -editor RANDOM_TEXT`` > crash
``godot.windows.tools.64.exe -editor -path RANDOM_TEXT`` > Project manager is opened.
what should be done without ``-path``?

**Comment by akien-mga** [comment] 2016-06-03 16:28
>  what should be done without `-path`?
I guess we could try to ignore `RANDOM_TEXT` and thus open the editor in the PWD. The current behaviour that exits with an error is OK, but it shouldn't crash, so we still need to find a proper fix for this OSX bug (and then maybe improve the behaviour for every platform).

**Comment by volzhs** [comment] 2016-06-03 16:38
@akien-mga sadly, I don't have a Mac. :(

**Comment by akien-mga** [comment] 2016-07-15 08:03
Not critical for the upcoming 2.1, so moving to the next milestone.

**Comment by akien-mga** [comment] 2017-06-28 13:29
Sneaky poke @BastiaanOlij.

**Comment by BastiaanOlij** [comment] 2017-06-28 22:50
I'll have a look next week @akien-mga , I had a bit of a crazy week with sick kids and too much work :)

**Comment by hpvb** [comment] 2017-09-09 21:17
There's a guard in this function that should prevent memdelete(main_loop) from being called if main_loop is NULL. The backtrace suggests that that is what's going on, according to git blame that NULL check has been in place since 2015.

Unless this is some kind of threading error, or the reporter made local changes, I don't see how this can even happen.

```c
void OS_OSX::delete_main_loop() {

	if (!main_loop)
		return;
	memdelete(main_loop);
	main_loop = NULL;
}
```

**Comment by hpvb** [comment] 2017-09-09 21:18
From the stacktrace:
```
   1019 void OS_OSX::delete_main_loop() {
   1020
-> 1021         memdelete(main_loop);
   1022         main_loop=NULL;
   1023 }
```

This code hasn't existed for a while. I have no idea what's going on.

**Comment by akien-mga** [comment] 2017-09-13 12:53
Well the last time we had an actual *crash* was in the OP in 2014. Everything afterwards was just confusion about the editor closing normally, while spouting some unhelpful errors. Nothing macOS-specific there.

**Closed by akien-mga** 2017-09-13 12:53 UTC
Labels: bug, junior job, needs testing, platform:osx, topic:core
