### ISSUE TITLE
Editor crash while importing a material exported from material maker

### ISSUE THREAD

**Issue by yahiaetman** [godotengine/godot#85214] opened 2023-11-22 13:09 UTC
### Godot version

v4.2-rc1_mono_win64

### System information

Window 11 - Godot v4.2-rc1 mono win64 - Forward+

### Issue description

While loading a certain material exported from material maker, the editor always crashes.

The material in question is included in the reproduction project.

The same material works fine in Godot 4.1.1 (mono - win64).

### Steps to reproduce

1. Create a new project in Godot v4.2-rc1_mono_win64.
2. Drag and drop the material (included in the reproduction project) into the project.
3. The editor crashes.

### Minimal reproduction project

[GoldImportBug.zip](https://github.com/godotengine/godot/files/13439624/GoldImportBug.zip)

**Comment by akien-mga** [comment] 2023-11-22 13:13
I can't seem to reproduce the issue on Linux, but it may be a Windows specific bug.

I have a hunch it might be threading related and thus similar to #85105.

Could you test the build linked in https://github.com/godotengine/godot/pull/85039#issuecomment-1821055056 and confirm if that solves the issue?

**Comment by yahiaetman** [comment] 2023-11-22 13:18
Yes, it works fine in the build you've linked. The material was imported without any problems.

**Comment by akien-mga** [comment] 2023-11-22 13:34
Great! Closing as duplicate of #85105 then, the next 4.2-rc2 build will have that fix.

**Closed by akien-mga** 2023-11-22 13:34 UTC
Labels: bug, needs testing, topic:import, crash
