### ISSUE TITLE
Internal Script Error - opcode 38

### ISSUE THREAD

**Issue by nonunknown** [godotengine/godot#43281] opened 2020-11-02 20:40 UTC
**Godot version:**
3.2.4 beta 1

**OS/device including version:**
KaOS Linux

**Issue description:**
I'm just reporting this cuz, the error says that, I think its related to declaring a variable inside a for loop which is the variable itself as can be seen below.

**Steps to reproduce:**
![image](https://user-images.githubusercontent.com/58845030/97916908-6b422780-1d32-11eb-9468-19107ca53740.png)

**Comment by Calinou** [comment] 2020-11-02 23:15
Duplicate of https://github.com/godotengine/godot/issues/43042 (will be fixed in 3.2.4beta2).

**Closed by Calinou** 2020-11-02 23:15 UTC
Labels: archived, bug, topic:gdscript
