### ISSUE TITLE
Regression: Warnings in C# project appear as errors in the Mono tab of the editor

### ISSUE THREAD

**Issue by redxdev** [godotengine/godot#15768] opened 2018-01-16 03:55 UTC
**Godot version:**
This is a regression. The commit that caused this seems to be 2cde466ebdb6237b6f72ef78614dc05f2ffb551b. The commit seems unrelated, but this is the first commit I found that causes the issue. 

**OS/device including version:**
Windows 10 1709

**Issue description:**
When the editor builds a C# solution (including GodotSharp) any warnings will appear as errors within the editor, though they will not otherwise affect the build process (builds still succeed).

How it should look:

![screenshot](https://i.imgur.com/QOefKAr.png)

How it currently looks:

![screenshot](https://i.imgur.com/6f3IEnX.png)

**Comment by paulloz** [comment] 2018-01-16 12:17
They're actually not appearing as errors : on my screen below, the top one is an error and the bottom one is a warning.
![image](https://user-images.githubusercontent.com/437025/34988405-e6a9e302-fabe-11e7-8e24-56ba4705fa6f.png)

**Comment by redxdev** [comment] 2018-01-21 01:15
I'm now very confused. Errors are appearing as yellow dots now:

![screenshot](https://i.imgur.com/Fv5TaUD.png)

I'm on 8f8b032eede264f2958998ccd038e0c61abdf75e

**Comment by akien-mga** [comment] 2018-01-21 20:21
CC @volzhs @djrm

**Comment by akien-mga** [comment] 2018-09-10 08:14
There were several changes to how warnings are displayed in the editor, especially after GDScript warnings were merged. I don't think they intended to change how C# warnings are treated, but if they use the same pipeline then they would be fixed too.

Closing as per the above comment, if someone can still reproduce it, please comment here and we'll reopen.

**Closed by akien-mga** 2018-09-10 08:14 UTC
Labels: bug, topic:editor, usability
