### ISSUE TITLE
Logs are flooded with repeating errors

### ISSUE THREAD

**Issue by PonasKovas** [godotengine/godot#30612] opened 2019-07-16 07:12 UTC
**Godot version:**
Godot 3.1

**Issue description:**
Because of Godo't design to just try to keep going and not crash when an error is encountered, the logs sometimes are flooded really fast with the same, repeating error, which is caused, for example by code in a `_process(delta)` method. This is quite irritating, and I suggest having a Project Setting `repeat_errors`, which if enabled, would print errors the same way as it is doing now, and if disabled, would only print an error 1 time, and then if it repeats just add `(2)` at the end of the error, and then just increment the number as the errors happen.

So for example, CLI output with `repeat_errors` enabled:

```
Error: "something" object does not have a property "name".
Error: "something" object does not have a property "name".
Error: "something" object does not have a property "name".
Error: "something" object does not have a property "name".
```
 And with `repeat_errors` disabled:

```
Error: "something" object does not have a property "name". (4)
```

**Comment by akien-mga** [comment] 2019-07-16 07:16
Duplicate of #19121.

**Closed by akien-mga** 2019-07-16 07:16 UTC
