### ISSUE TITLE
High editor CPU usage / spinner indicates constant redraw

### ISSUE THREAD

**Issue by bertiebaggio** [godotengine/godot#424] opened 2014-05-15 14:03 UTC
A few folk have indicated issues with the editor using high amount of CPU or at least having the window repaint spinner continuously turning. The cause of the redraw / updates is not clear and may not be consistent from user to user.

For me, the problem appeared sometime shortly after exporting a project for the first time. Deleting the created export.cfg file fixed the issue: I have git commits before and after with the only change being the deletion, and one exhibits the behaviour while the other does not.

**Comment by jeremyjh** [comment] 2016-09-12 00:56
Not fixed. I saw this same issue on the 2.1 Linux 64 release build. Deleting export.cfg resolved it.

**Comment by fliar** [comment] 2017-07-21 08:58
same here on Mac 2.1.3 stable, removing export.cfg works

**Comment by stubbsy345** [comment] 2017-09-16 16:07
@fliar My game runs very well from the editor and indeed runs well in html5 export. However, in the html5 export about 20% - 30% on average more cpu is used. I have `OS.set_low_processor_usage_mode(true)` in my singleton code but doesn't seem to be improving the export. I also have enable_run in my export unchecked. Any advice on how to improve performance. It doesn't look very good if someone plays the game and their fan starts whirring like crazy, haha.

**Comment by toger5** [comment] 2017-09-17 00:25
I think this is also the case a with 3d viewport chooses. (fand guarantee though that adaptive brightnes in the environment was turned of... I think that Forces redraw)

**Comment by fliar** [comment] 2017-09-17 13:53
@stubbsy345 I guess this is another case and have no relationship to this issue ?  we can discuss this somewhere else

**Comment by stubbsy345** [comment] 2017-09-17 14:16
Okay i've opened a seperate issue https://github.com/godotengine/godot/issues/11358

**Comment by adamrej** [comment] 2017-10-20 18:26
Hi Folks, I'm having this problem as well.  Constant redraw that is. 2.13 stable osx 10.12.6.  I can't find the export.cfg file referred to in some of the comments above.  In fact I don't even have the export templates installed.  Could that be the problem?

**Comment by DuskKittyIsHotAF** [comment] 2018-02-12 12:12
very tolerant and nice commnuity imo. run by great leadership skills, you should be proud juan and akien for leading this great floss project!
![](https://i.gyazo.com/2fd0c035013b3c1bb0652552d35fde92.png)
![](https://i.gyazo.com/e0acd22258872330f342d5d189564f1e.png)
![](https://i.gyazo.com/81b238ce283aa55126e3a2f608583837.png)

**Comment by mhilbrunner** [comment] 2018-04-10 18:51
Closing this, as it seems quite old and outdated now. If it still happens, let us know here so we can reopen. In that case, please state what Godot version you're using, what the issue is and what the expected behaviour would be. Thank you!

**Closed by mhilbrunner** 2018-04-10 18:51 UTC
Labels: bug, topic:editor
