### ISSUE TITLE
Light2D "Add" Mode does not work as expected

### ISSUE THREAD

**Issue by BrownShapiro** [godotengine/godot#35328] opened 2020-01-19 19:57 UTC
**Godot version:**
Godot Engine v3.1.2.stable.official

**OS/device including version:**
Windows 10 Home Version 1903

**Issue description:**
The "Add" Mode on Light2D nodes (and possibly 3D Light nodes as well, I haven't tested) seems to multiply the RGB values of pixels underneath it (rather than simply adding the values, like it says in the documentation). This means that if a colour has an RGB component of 0.0, that component will never reach 1.0 no matter how high the Energy is. EDIT: This applies to both GLES2 and GLES3.

**Steps to reproduce:**
I have put together a small demonstration project below, consisting of a Main.tscn with a single Sprite displaying 8 different colours and their RGB components (from 0-255) as well as a Light2D with a pure white texture that is the same size as the sprite. Reproduce the effect by tweaking the Energy parameter of the Light2D node, and notice how the different colours start to differentiate based on their RGB values.

**Minimal reproduction project:**
[Light bug.zip](https://github.com/godotengine/godot/files/4083441/Light.bug.zip)

**Screenshots (using GLES3)**
Energy - 0.01
![bild](https://user-images.githubusercontent.com/43519017/72687435-f7fe5a80-3afd-11ea-9558-a207a89e7011.png)
Energy - 1.0
![bild](https://user-images.githubusercontent.com/43519017/72687444-0c425780-3afe-11ea-9abd-4ac22afd9a39.png)
Energy - 12.0
![bild](https://user-images.githubusercontent.com/43519017/72687453-1fedbe00-3afe-11ea-806b-481df4ed8c53.png)
Energy - 100.0
![bild](https://user-images.githubusercontent.com/43519017/72687461-401d7d00-3afe-11ea-8680-fd5a0c7ed2bc.png)

**Comment by clayjohn** [comment] 2020-01-19 20:00
Are the results the same for GLES3 and GLES2?

**Comment by Xrayez** [comment] 2020-01-19 20:26
@clayjohn in GLES2 it only affects red squares, without modulating color like with the `12.0` energy sample. Using 3.2rc1.

**Comment by Xrayez** [comment] 2020-01-19 20:30
It's also different when mode is set to `Sub`:

GLES2:
![godot-light-sub-gles2](https://user-images.githubusercontent.com/17108460/72687920-3f3f1800-3b0b-11ea-9599-6a0b4734dc7a.png)

GLES3:
![godot-light-sub-gles3](https://user-images.githubusercontent.com/17108460/72687921-40704500-3b0b-11ea-9029-88d553e90f12.png)

**Comment by KoBeWi** [comment] 2020-12-14 01:49
Duplicate of #19153

**Closed by KoBeWi** 2020-12-14 01:49 UTC
Labels: bug, topic:rendering
