### ISSUE TITLE
(C#) using Godot.Collections leads to build failure on exported fields

### ISSUE THREAD

**Issue by wizcas** [godotengine/godot#66118] opened 2022-09-19 16:27 UTC
### Godot version

v4.0.beta1.mono.official [4ba934bf3]

### System information

Windows 11

### Issue description

Godot.Collection types can only be refered to by the full name on `[Export]` fields. Trying to shorten them with `using` statement will cause a build failure:

```
K:\gamework\gates\game4\Godot.SourceGenerators\Godot.SourceGenerators.ScriptPropertyDefValGenerator\PlayerAttack_ScriptPropertyDefVal_Generated.cs(11,82): 

The type or namespace name 'Array<>' could not be found (are you missing a using directive or an assembly reference?)
```

### Steps to reproduce

1. Declare a field in a C# script
   ```c#
   using Godot.Collections;
   ...
   [Export] public Array<Node> nodes = new Array<Node>();
   ```
2. Build the project and it failes.
3. Change the code to
    ```c#
    [Export] public Godot.Collections.Array<Node> nodes = new Godot.Collections.Array<Node>();
    ```
4. Rebuild and it passes this time. But it will print error
    ```c#
     modules/mono/glue/runtime_interop.cpp:1233 - Attempted to convert an unmarshallable managed type to Variant. Name: 'Godot.Collections.Array`1[[Godot.Node, GodotSharp, Version=4.0.0.0, Culture=neutral, PublicKeyToken=null]].
    ```

**Only the non-generic `Godot.Collections.Array` (in full name) works fine**

### Minimal reproduction project

[export-array-bug.zip](https://github.com/godotengine/godot/files/9600739/export-array-bug.zip)

**Comment by raulsntos** [comment] 2022-09-19 17:08
Duplicate of https://github.com/godotengine/godot/issues/65883

**Closed by raulsntos** 2022-09-19 17:08 UTC
Labels: bug, topic:dotnet
