### ISSUE TITLE
import / building loading window missing borders

### ISSUE THREAD

**Issue by Byteron** [godotengine/godot#48994] opened 2021-05-23 13:19 UTC
**Godot version:**
4.0 master

**OS/device including version:**
Windows 10

**Issue description:**
the window that pops up when importing assets or when building/running the scene is missing borders and thus is hard to see in some instances.
![image](https://user-images.githubusercontent.com/24433899/119262034-11c01e00-bbda-11eb-8f89-46842be9f4dc.png)

**Comment by Calinou** [comment] 2021-05-23 13:20
This is because it's declared as a popup, which means it doesn't get OS window borders or shadows.

**Comment by Byteron** [comment] 2021-05-23 13:28
I figured it is not a full blown window. It doesn't have to be but I still think it should have borders of some kind.

**Comment by KoBeWi** [comment] 2022-05-07 01:41
The issue is only apparent when the popup appears on a single-colored background that happens to have the same color as editor UI. I think the popup has some stylebox if we decide to fix this, but not sure if it's worth it.

**Comment by Calinou** [comment] 2022-05-07 01:59
Closing in favor of https://github.com/godotengine/godot/issues/60047, which has more information about the problem at hand.

**Closed by Calinou** 2022-05-07 01:59 UTC
Labels: bug, topic:editor
