### ISSUE TITLE
GDScript is no longer guessing my expressions

### ISSUE THREAD

**Issue by IronBrandon** [godotengine/godot#37413] opened 2020-03-29 18:03 UTC
**Godot version:** v3.2.1.stable.official

**OS/device including version:** Windows 10 (18363.720)

**Issue description:** Keeps giving me this error " Maximum _guess_expression_type depth limit reached. Please file a bugreport." and no longer guesses what I'm about to type, I can live without it guessing, but this error comes on my screen 3 times when I type anything!

**Steps to reproduce:** I was copying a script from my notepad and this happened for no reason

**Minimal reproduction project:** ???

![editor_screenshot_2020-03-29T120234-0700](https://user-images.githubusercontent.com/42562727/77856570-48a4ca80-71b5-11ea-9d75-a941c73d6902.png)

**Comment by Calinou** [comment] 2020-03-29 18:13
Please upload a minimal reproduction project to make this easier to troubleshoot.

**Comment by Jimmio92** [comment] 2020-03-29 22:54
Could this be because of pasting non-unix-line-ending text into the editor I wonder? notepad.exe is great for that \r\n goodness that usually trips up unix tools.

**Comment by Calinou** [comment] 2020-04-23 07:16
I'll close this issue as no [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) was provided in time. This issue can be reopened if someone uploads a minimal reproduction project.

@Jimmio92 I tried this locally and couldn't reproduce it with mixed line endings (or a file using only CRLF line endings).

**Comment by ScorpioneOrzion** [comment] 2021-05-18 09:58
Got the same issue, with only a single Scene, a single Script
[Dungeon.zip](https://github.com/godotengine/godot/files/6500296/Dungeon.zip)

Computer Info
Windows 10
Godot Engine v3.3.stable.official

Steps to reproduce, any script just writing code, it will happen at random times, but once it happens it will happen whenever you type more, and i don't know what is causing it.

**Comment by Calinou** [comment] 2022-11-04 22:03
@IronBrandon @ScorpioneOrzion Can you (or anyone else) still reproduce this bug in [Godot 3.5.1](https://godotengine.org/article/maintenance-release-godot-3-5-1) or any later release?

If yes, please ensure that an up-to-date Minimal Reproduction Project (MRP) is included in this report (a MRP is a zipped Godot project with the minimal elements necessary to reliably trigger the bug). You can upload ZIP files in an issue comment with a drag and drop.

PS: Remember that in Godot 3.x, autocompletion is disabling if you have any errors in your script. This is fixed in 4.0.

**Comment by Calinou** [comment] 2022-11-25 19:18
Closing due to lack of response. Please comment if you can still reproduce this bug.

**Closed by Calinou** 2022-11-25 19:18 UTC
Labels: bug, topic:gdscript, needs testing

**Comment by atyuii** [comment] 2023-01-10 07:21
extends Node2D

var width = 300
var height = 300

var numFluids = 10

class fluid:
	var density: float
	var velocity: Vector2

func gaussSeidel(fluid, k, depth):
	if depth == 0:
		return fluid
	for i in range(len(fluid)):
		for j in range(len(fluid[i])):
			var a = fluid[min(i + 1, len(fluid) - 1)][j].density
			var b = fluid[max(i - 1, 0)][j].density
			var c = fluid[i][min(j + 1, len(fluid) - 1)].density
			var d = fluid[i][max(j - 1, 0)].density
			fluid[i][j].density = (fluid[i][j].density + k * (a + b + c + d) / 4) / (k + 1)
	return gaussSeidel(fluid, k, depth - 1)

var fluids = []
func _ready():
	for i in range(numFluids):
		var row = []
		for j in range(numFluids):
			var fld = fluid.new()
			fld.density = 0.5
			row.append(fld)
		fluids.append(row)
	fluids = gaussSeidel(fluids, 0.1, 10)
	print(fluids[0][0].density)
	
	
func _physics_process(delta):
	
	pass



--------------------------
when I type 
fluids.(anything)
the output says  Maximum _guess_expression_type depth limit reached. Please file a bugreport
this only happened when I put the fluids. the line before or after print(fluids[0][0].density)

**Comment by Zireael07** [comment] 2023-01-10 08:26
Open a new bug report then
