### ISSUE TITLE
Playing Animation backward does not play the last frame first

### ISSUE THREAD

**Issue by sgervais333** [godotengine/godot#100592] opened 2024-12-19 05:14 UTC
### Tested versions

- Reproducible in: Godot 4.3.stable, Godot_v4.4-dev6

### System information

Windows 10 Godot4.3.stable Vulkan (Forward Mobile) - NVIDIA GeForce RTX 3080 Ti

### Issue description

I try to play a animation backward with a AnimationPlayer but is seems the last frame is not played when played backward.

When I play the animation normally, the last frame rotate the image:
![Image](https://github.com/user-attachments/assets/aa9db90a-999f-4811-86d2-b6ddf39af675)

But, When I play the animation backward, the first frame does not play:
![Image](https://github.com/user-attachments/assets/62f88d31-de5d-4a94-a70b-3ec0cf711ba1)

It happen in-game to, when launch with the "play_backwards" method.

I really don't know if this a bug or not. Maybe there is something I didn't understand.
Thanks for your help.

### Steps to reproduce

- Create a AnimationPlayer
- Add a Sprite2D
- Make a simple animation with one key a the start and one key a the end with different value, in my case, i use the Rotation. (Be sure to put the track in Discrete Mode, because the problem is easier to see this way)
- If you click the "Play selected animation from start.", everything is fine
- Than click "Play selected animation backwards from end.", everything seems fine, but then, if you re-click "Play selected animation backwards from end.", nothing happen.
- I expect the last key to be played when backward.

### Minimal reproduction project (MRP)

This is a minimal reproduction project with only the rotation in the animation, but it seems to "bug" for many properties to (Position, Scale.) 
[issue.zip](https://github.com/user-attachments/files/18192786/issue.zip)

**Comment by TokageItLab** [comment] 2024-12-19 19:22
Dupe of https://github.com/godotengine/godot/issues/98214

**Closed by TokageItLab** 2024-12-19 19:22 UTC
Labels: bug, topic:animation
