### ISSUE TITLE
export vars are lost/reset upon saving a script with a syntax error

### ISSUE THREAD

**Issue by DimaKiva** [godotengine/godot#5603] opened 2016-07-09 00:59 UTC
**Operating system or device - Godot version:**

Ubuntu 16.04

**Issue description** (what happened, and what was expected):

If you restart the project with an error in the script, then the reset value of the variable in the Inspector.

**Steps to reproduce:**
1. `export var test = 'a'`
2. The inspector 'a' change to 'b'
3. Add a string to simulate errors.
4. `export var test = 'a'
x`
5. Save the project and restart the project.
![2016-07-09 07-55-39](https://cloud.githubusercontent.com/assets/11325733/16705122/5bca1d54-45b3-11e6-879e-6936091d7d53.png)

**Comment by akien-mga** [comment] 2016-07-09 08:29
I can confirm the bug. If you save a script with a syntax error (be it at the global scope as shown by @DimaKiva, or within a function such as e.g. `get_node(` in `_ready()`), the export vars are removed, and thus their values are lost from the scene.

**Comment by DualMatrix** [comment] 2018-09-16 20:01
Still relevant in master.

**Comment by vnen** [comment] 2018-09-16 21:02
Hm, I thought #20583 would fix this, but apparently it didn't.

**Comment by TheRadMatt** [comment] 2018-11-04 09:58
Please fix this issue. Making any changes to a tool node is basically impossible in a more complicated game, because the values reset in every single instance.

**Comment by neikeq** [comment] 2018-11-04 15:57
This should have been fixed by #20583. I will have a look.

**Closed** 2018-11-10 20:33 UTC
Labels: bug, confirmed, topic:editor, usability

**Comment by DualMatrix** [comment] 2018-11-28 22:58
I'm still encountering this issue on the current master :(

**Comment by neikeq** [comment] 2018-11-28 23:08
@DualMatrix Can you open a new issue with the steps to reproduce it?

**Comment by pouleyKetchoupp** [comment] 2018-11-29 14:43
@neikeq I'm able to reproduce this issue on master, with the exact same steps, except you need to save the project 2 times in a row in step 5. Do I need to open a new issue?
