### ISSUE TITLE
Input.is_action_pressed not working on Export

### ISSUE THREAD

**Issue by benwolf** [godotengine/godot#9616] opened 2017-07-12 10:05 UTC
**Operating system or device - Godot version:**
Windows 8.1 64bit (also Windows 10 64bit) - Godot 3.0  Master Branch

**Issue description:**
After exporting game any Input.is_action_pressed doesn't work. However, it does work for versions run from editor. Also Input.is_key_pressed also works (both in editor and exported).

**Steps to reproduce:**
Build current Export template.
Export project that has a input check using the is_action_pressed.
Try the input.

**Link to minimal example project:**
Fastest way to test is to use the Pong example in https://github.com/godotengine/godot-demo-projects/tree/master

**Comment by hickop** [comment] 2017-07-12 11:26
Probably related to #9250

**Comment by vnen** [comment] 2017-07-12 13:51
Yes, it's a duplicate of #9250.

**Closed by vnen** 2017-07-12 13:51 UTC
