### ISSUE TITLE
i lost 5 months of works, after moving script to another folder

### ISSUE THREAD

**Issue by Intervel** [godotengine/godot#70292] opened 2022-12-19 09:14 UTC
### Godot version

4.0 beta 8

### System information

Windows 11,  Rtx 3090

### Issue description

https://user-images.githubusercontent.com/86478025/208388439-4fbf4760-3321-442e-a41a-90c4e039324a.mp4

i cant open gui.tscn anymore, after moving loading.gd script to another folder

this GUI.tscn contains loading.gd script

here is what happens :

- i tried to organized my script by moving loading.gd script from autoload/script folder to ui/script folder

![2](https://user-images.githubusercontent.com/86478025/208389390-d382aaca-28f0-4a31-acf6-c98faed78c0f.png)

- after that i can't open gui.tscn anymore.

![1](https://user-images.githubusercontent.com/86478025/208389167-a70d2212-9ddf-44a4-b87d-227ef418149a.png)

here is the output :

  scene/resources/resource_format_text.cpp:514 - res://autoload/gui.tscn:66 - Parse Error: Expected '['
  Failed loading resource: res://autoload/gui.tscn. Make sure resources have been imported by opening the project in the editor at least once.
  scene/resources/resource_format_text.cpp:514 - res://autoload/gui.tscn:66 - Parse Error: Expected '['
  Failed loading resource: res://autoload/gui.tscn. Make sure resources have been imported by opening the project in the editor at least once.
  Another resource is loaded from path 'res://ui/scripts/loading.gd' (possible cyclic resource inclusion).
  scene/resources/resource_format_text.cpp:514 - res://autoload/gui.tscn:66 - Parse Error: Expected '['
  Failed loading resource: res://autoload/gui.tscn. Make sure resources have been imported by opening the project in the editor at least once.

please help me, i dont know what to do :(

### Steps to reproduce

:(

### Minimal reproduction project

:(

**Comment by akien-mga** [comment] 2022-12-19 09:22
That's a duplicate of #69794, fixed in beta 9 which will be released soon.

There's sadly no way to recover the lost contents of that file if you do not use version control or make backups.
It's an absolute requirement when using beta software (or software in general) to use version control/backups to prevent losing work if the software misbehaves. Beta means that there _are_ bugs and some of these bugs can lead to data corruption like here.

**Closed by akien-mga** 2022-12-19 09:22 UTC

**Comment by Zireael07** [comment] 2022-12-19 11:06
IIRC all beta announcements told users to make copies of projects before opening them in the beta version, just in case.

Version control/backups is a VERY GOOD idea even if you do not use beta software. I've had random failures and even a SSD failure...
