### ISSUE TITLE
`EditorPlugin._handles` still invoke twice. 

### ISSUE THREAD

**Issue by RickyYCheng** [godotengine/godot#92300] opened 2024-05-24 03:16 UTC
### Tested versions

Godot v4.3.dev6.mono
Godot v4.2.2.stable.mono

### System information

Windows 10.0.22631 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3050 Laptop GPU (NVIDIA; 31.0.15.2698) - AMD Ryzen 7 5800U with Radeon Graphics (16 Threads)

### Issue description

See: #55798 . When choosing a node on the tree, the `_handles` function will invoke twice. 

This is kind annoying, I use this func to decide whether to add a child node or not. 
This makes the node name changes. 

### Steps to reproduce

1. Create a project;  

2. Create a new plugin;  

3. add a `_handles` function like this: 
```gdscript
@tool
extends EditorPlugin

func _handles(object: Object) -> bool:
	print(object)
	return true

func _enter_tree() -> void:
	# Initialization of the plugin goes here.
	pass


func _exit_tree() -> void:
	# Clean-up of the plugin goes here.
	pass

```

4. add a scene with a node. Deselect it and clear console. Then try clicking the node to select it and you will see the console print double times. 

### Minimal reproduction project (MRP)

4.2.2-mono
[Editor-4_2_2_stable_mono.zip](https://github.com/godotengine/godot/files/15427019/Editor-4_2_2_stable_mono.zip)
4.3-dev-mono
[editor-4_3_dev6_mono.zip](https://github.com/godotengine/godot/files/15427020/editor-4_3_dev6_mono.zip)
(no C# code inside)

**Comment by KoBeWi** [comment] 2024-05-24 11:17
Can't reproduce

https://github.com/godotengine/godot/assets/2223172/fd577121-a947-45da-9c73-51dec1b47039

**Comment by KoBeWi** [comment] 2024-05-24 11:19
It happens in dev6, but it's fixed on master.

**Closed by KoBeWi** 2024-05-24 11:19 UTC
Labels: bug, topic:editor, topic:plugin
