### ISSUE TITLE
Godot 3.1 Beta 4-6 Parse Error caught only at release build

### ISSUE THREAD

**Issue by ArchangelZeero** [godotengine/godot#26234] opened 2019-02-24 14:09 UTC
**Godot version:**
3.1-Beta-4 and Beta-6 (These are the only I tested)

**OS/device including version:**
Windows 10

**Issue description:**
Parse Error caught only at release build, caught by Log

`**SCRIPT ERROR**: Parse Error: Cannot assign a new value to a constant.`

**Steps to reproduce:**
This particular case occured by doing something like this:

**for** numerical_string **in** ["0","1","2"]:
`        `numerical_string=**int**(numerical_string)

**Comment by akien-mga** [comment] 2019-02-25 17:12
Duplicate of #25334.

**Closed by akien-mga** 2019-02-25 17:12 UTC
Labels: bug, topic:gdscript
