### ISSUE TITLE
GPUParticles2D color ramp doesn't work if GradientTexture1D is used

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#61618] opened 2022-06-01 22:17 UTC
### Godot version

d9daf38

### System information

Windows 10 x64

### Issue description

When you use GradientTexture1D as color ramp in 2D particles, it will have no effect. You can't assign any other texture type, but you can convert the material to ShaderMaterial and assign e.g. GradientTexture2D and it will work correctly. Interestingly, you can't assign GradientTexture1D in ShaderMaterial; the field will be empty.
![godot windows tools 64_c4oal6SnWl](https://user-images.githubusercontent.com/2223172/171510981-414b4f48-cb68-450a-ba27-fc3648193119.gif)

EDIT:
Seems like it works after reloading the scene...

### Steps to reproduce

1. Add GPUParticles2D
2. Try adding GradientTexture1D as color ramp

**Comment by clayjohn** [comment] 2022-12-15 19:48
Duplicate of https://github.com/godotengine/godot/issues/57471

**Closed by clayjohn** 2022-12-15 19:48 UTC
Labels: bug, regression, topic:2d, topic:particles
