### ISSUE TITLE
XOR

### ISSUE THREAD

**Issue by lukostello** [godotengine/godot#34455] opened 2019-12-19 05:47 UTC
Super simple make XOR like ^^ to fit in with || and && how is this not among the first things included?

**Comment by timothyqiu** [comment] 2019-12-19 06:59
As a workaround, you can use `a != b`.

**Comment by groud** [comment] 2019-12-19 07:07
Duplicate of #22740

**Comment by lukostello** [comment] 2019-12-19 07:44
> Duplicate of #22740 and #18816. If you really need more than != please precise your issue.

While != works in my scenario I don't think ^^ is equal to !=. I tend to think of != and == as having lower priority than && and ||. The way I am thinking about it they always occur last. 
```false || true ^^ false && false``` would evaluate to true, while
```false || true != false && false``` would evaluate to false
because ```false || true != false && false``` would equal ```(false || true) ^^ (false && false)``
They also have different connotations which make it more readable to use one over the other in certain scenarios as mentioned in previous posts.

**Comment by dalexeev** [comment] 2019-12-19 08:23
See also https://github.com/godotengine/godot-proposals/issues/230.

**Comment by groud** [comment] 2019-12-19 08:31
Ah yes, this one is still open, so please continue the discussion there.

**Closed** 2019-12-19 08:31 UTC
