### ISSUE TITLE
If the editor's window is too small changing to the script tab will cutoff part of the editor's right side

### ISSUE THREAD

**Issue by mrcdk** [godotengine/godot#12687] opened 2017-11-05 22:28 UTC
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Godot 3.0 master https://github.com/godotengine/godot/commit/9a78efc7c270211e49fd7b2f071b61c706febffc

**Issue description:**

![https://i.imgur.com/5Bycz27.gifv](https://i.imgur.com/5Bycz27.gif)

Not sure if this should be fixed or not... it also happens if there isn't enough space in the editor in any tab so I guess the script tab needs more space than the other tabs:
![https://i.imgur.com/CdaFxLS.gifv](https://i.imgur.com/CdaFxLS.gif)

Maybe the script contents should have the same minimum size?

**Comment by Calinou** [comment] 2020-06-14 14:13
Duplicate of #31133.

**Closed by Calinou** 2020-06-14 14:13 UTC
Labels: enhancement, topic:editor, usability
