### ISSUE TITLE
"Property not found" warnings when renaming project in Project Manager

### ISSUE THREAD

**Issue by rumpfc** [godotengine/godot#35786] opened 2020-01-31 15:38 UTC
**Godot version:**
3.2 stable

**OS/device including version:**
WIndows 10 x64

**Issue description:** 
Many warnings in console when trying to rename a project in Project Manager. After that, the warnings keep popping up at each mouse-over list item.

```
WARNING: _get: Property not found: rendering/limits/time/time_rollover_secs
     At: core/project_settings.cpp:209
WARNING: _get: Property not found: rendering/quality/shadows/filter_mode
     At: core/project_settings.cpp:209
WARNING: _get: Property not found: rendering/quality/subsurface_scattering/follow_surface
     At: core/project_settings.cpp:209
WARNING: _get: Property not found: rendering/quality/subsurface_scattering/weight_samples
     At: core/project_settings.cpp:209
WARNING: _get: Property not found: rendering/quality/subsurface_scattering/quality
     At: core/project_settings.cpp:209
WARNING: _get: Property not found: rendering/quality/subsurface_scattering/scale
     At: core/project_settings.cpp:209
WARNING: _get: Property not found: rendering/quality/voxel_cone_tracing/high_quality
     At: core/project_settings.cpp:209
```

**Steps to reproduce:**

- Open Godot application
- Select a Project in "Project Manager" window
- Click "Rename" button

**Comment by Calinou** [comment] 2020-01-31 15:55
Duplicate of #25661.

**Closed by Calinou** 2020-01-31 15:55 UTC
