### ISSUE TITLE
HTTPRequest error and missing progress UI reopening Export template manager while downloading

### ISSUE THREAD

**Issue by lostminds** [godotengine/godot#91448] opened 2024-05-02 08:42 UTC
### Tested versions

4.3.dev6

### System information

macOS 14.4.1

### Issue description

While downloading an export template using the Export template manager you can close the window and the download will continue and finish in the background. However, if you try to re-open the export template manager again while the download is in progress there are a couple of issues:

You get the following error:
 ```
scene/main/http_request.cpp:536 - Condition "get_http_client_status() != HTTPClient::STATUS_DISCONNECTED" is true.
  scene/main/http_request.cpp:507 - Condition "get_http_client_status() != HTTPClient::STATUS_DISCONNECTED" is true.
  HTTPRequest is processing a request. Wait for completion or cancel it before attempting a new one.
```

And instead of showing the download progress UI for the ongoing download the dialogue is shown with the progress section missing. The download/install buttons are also removed, but the warning about no installed matching template is still shown.

![Screenshot 2024-05-02 at 10 26 40](https://github.com/godotengine/godot/assets/17763524/93b253ac-ffd1-4217-816d-8fbf801c6a3a)

However, if you try closing the window again you'll get the warning explaining that the download will continue. And if you leave it open as it finishes it will update correcting itself showing the newly installed template.

### Steps to reproduce

- Open the Export template manager
- Start a download
- Close the template manager
- Open the template manager again while download is in progress

### Minimal reproduction project (MRP)

Not project specific

**Comment by akien-mga** [comment] 2024-06-14 13:04
Duplicate of https://github.com/godotengine/godot/issues/93121.

**Closed by akien-mga** 2024-06-14 13:04 UTC
Labels: bug, topic:editor
