### ISSUE TITLE
texture(SCREEN_TEXTURE, SCREEN_UV) shader bug in 4.0 dev for Vulkan

### ISSUE THREAD

**Issue by SheilaWarren** [godotengine/godot#55097] opened 2021-11-18 16:02 UTC
### Godot version

4.0dev

### System information

Mac OSX 11.1

### Issue description

Trying to grab the screen contents in a shader using texture or textureLod causes thousands of errors in the debugger. Using Vulkan 1.2.182.0 or 1.2.189.0 on MacOS X 11.1.

Repeating error list:

E 0:00:01:0292   texture_create: Height must be equal or greater than 1 for 2D and 3D textures
  <C++ Error>    Condition "p_format.height < 1" is true. Returning: RID()
  <C++ Source>   drivers/vulkan/rendering_device_vulkan.cpp:1756 @ texture_create()
E 0:00:01:0292   compute_list_bind_compute_pipeline: Condition "!pipeline" is true.
  <C++ Source>   drivers/vulkan/rendering_device_vulkan.cpp:7814 @ compute_list_bind_compute_pipeline()
E 0:00:01:0292   version_get_shader: Index p_variant = 0 is out of bounds (variant_defines.size() = 0).
  <C++ Source>   ./servers/rendering/renderer_rd/shader_rd.h:141 @ version_get_shader()
E 0:00:01:0292   uniform_set_create: Condition "!shader" is true. Returning: RID()
  <C++ Source>   drivers/vulkan/rendering_device_vulkan.cpp:5498 @ uniform_set_create()
E 0:00:01:0292   compute_list_bind_uniform_set: Condition "!uniform_set" is true.
  <C++ Source>   drivers/vulkan/rendering_device_vulkan.cpp:7887 @ compute_list_bind_uniform_set()
E 0:00:01:0292   version_get_shader: Index p_variant = 0 is out of bounds (variant_defines.size() = 0).
  <C++ Source>   ./servers/rendering/renderer_rd/shader_rd.h:141 @ version_get_shader()

...

repeats indefinitely.

### Steps to reproduce

Add a ColorRect to the scene. Add canvas shader. set the COLOR = texture(SCREEN_TEXTURE, SCREEN_UV);

```
shader_type canvas_item;

void fragment() {
	COLOR = texture(SCREEN_TEXTURE, SCREEN_UV);
}
```

### Minimal reproduction project

[SCREEN_TEXTURE_Bug.zip](https://github.com/godotengine/godot/files/7564114/SCREEN_TEXTURE_Bug.zip)

**Comment by Calinou** [comment] 2021-11-18 17:52
Duplicate of https://github.com/godotengine/godot/issues/50976.

**Closed by Calinou** 2021-11-18 17:52 UTC
