### ISSUE TITLE
The CollisionObject2D in the Child Window node does not respond to any _input_event signals.

### ISSUE THREAD

**Issue by Yanxiyimengya** [godotengine/godot#91667] opened 2024-05-07 16:46 UTC
### Tested versions

v4.2.2.stable.official [15073afe3]

### System information

Godot v4.2.stable - Windows 10.0.19045 - GLES3 (Compatibility) - AMD Radeon(TM) Graphics (Advanced Micro Devices, Inc.; 30.0.13014.10001) - AMD Ryzen 5 5500U with Radeon Graphics (12 Threads)

### Issue description

After creating a Window node, I put an Area2D with CollisionShape2D under the child node of the Window, but Area2D does not trigger _input_event, mouse_entered, etc
Area2D's input_pickable is still false, and Button inside WindowViewport will still trigger the "pressed" signal normally
Area2D has a handle_input_locally property of true and has a default collision level.

### Steps to reproduce

MainScene Script:
```gdscript
extends Node2D

const AREA : PackedScene = preload("res://Area.tscn");
func _ready():
	
	get_viewport().gui_embed_subwindows = false;
	
	var window : Window = Window.new();
	self.add_child(window);
	window.position = Vector2(get_window().position);
	
	window.add_child(AREA.instantiate());
	
	pass;
```

res://Area.tscn : 
```gdscript
extends Area2D;

func _on_mouse_entered():
	print("test")
```

The console doesn't output anything, is this a bug???

### Minimal reproduction project (MRP)

[Demo.zip](https://github.com/godotengine/godot/files/15239119/Demo.zip)

**Comment by AThousandShips** [comment] 2024-05-07 16:55
You deselected the field while it was still uploading, please edit your post and upload the MRP again, making sure you leave it open until it's fully uploaded

**Comment by Sauermann** [comment] 2024-05-07 17:02
Have you set [physics_object_picking](https://docs.godotengine.org/en/latest/classes/class_viewport.html#class-viewport-property-physics-object-picking) = true?

**Comment by Yanxiyimengya** [comment] 2024-05-07 17:46
> 您是否设置了 [physics_object_picking](https://docs.godotengine.org/en/latest/classes/class_viewport.html#class-viewport-property-physics-object-picking) = true？

Yes. They aways keep it in its default state.

**Comment by Sauermann** [comment] 2024-05-07 20:55
Please note, that `pyhsics_object_picking` has a default value of `false`.

I have tested your MRP and I was able to make it work by enabling physics object picking in the newly created window like this:

``` gdscript
func _ready():
	
	get_viewport().gui_embed_subwindows = false;
	
	var window : Window = Window.new();
	self.add_child(window);
	window.position = Vector2(get_window().position);
	window.physics_object_picking = true
	window.add_child(AREA.instantiate());
```

Does this solve your problem?

**Comment by Yanxiyimengya** [comment] 2024-06-03 03:40
> 请注意，其默认值为 。`pyhsics_object_picking``false`
> 
> 我已经测试了您的 MRP，并且能够通过在新创建的窗口中启用物理对象拾取来使其工作，如下所示：
> 
> ```gdscript
> func _ready():
> 	
> 	get_viewport().gui_embed_subwindows = false;
> 	
> 	var window : Window = Window.new();
> 	self.add_child(window);
> 	window.position = Vector2(get_window().position);
> 	window.physics_object_picking = true
> 	window.add_child(AREA.instantiate());
> ```
> 
> 这能解决您的问题吗？

Thank you, it was really my mistake, thanks for the answer

**Comment by AThousandShips** [comment] 2024-06-03 13:28
Closing as per above as this was not a bug, thank you for your report

**Closed by AThousandShips** 2024-06-03 13:28 UTC
Labels: discussion, topic:input
