### ISSUE TITLE
[4.0] "'await' keyword not needed" is too peremptory.

### ISSUE THREAD

**Issue by Vaasref** [godotengine/godot#57178] opened 2022-01-25 02:42 UTC
### Godot version

4.0.alpha1

### System information

Windows 10

### Issue description

```
W 0:00:00:0992   "await" keyword not needed in this case, because the expression isn't a coroutine nor a signal.
  <C++ Error>    REDUNDANT_AWAIT
  <Source>       UpdateButton.gd:9
```
The warning message is peremptory as it asserts that the expression is not something it can be.

Since that warning is only thrown once when running, it cannot take into account all possibilities.

At first I was surprised that there weren't a warning each time `await`'s expression wasn't a signal or coroutine. So I guess that this use case is not discouraged. 
Since I might not be the only one with that same excpectation, maybe this `REDUNDANT_AWAIT` could trigger each time an `await` has its expression without coroutine or signal.

If the trigger of that warning stays the same I think that the message should be changed to a more correct :
`"await" keyword might not needed in this case, because the expression might not be a coroutine or a signal.`

### Steps to reproduce

```
extends Button

@export_node_path(VSlider) var slider_path:NodePath
@onready var slider:VSlider = get_node(slider_path)


func slider_over_50():
	while slider.value < 50:
		await slider.value_changed

func _pressed():
	print("Awaiting slider value over 50")
	await slider_over_50()
	print("The value is over 50")
```

Here I use a while-await loop to wait until the slider value is over 50 without needing to wait if it is already.

The warning message states that the function `slider_over_50()` is not a coroutine while it can be one depending of the value of the slider.

**Comment by KoBeWi** [comment] 2022-01-25 03:18
Duplicate of #56265

**Closed by KoBeWi** 2022-01-25 03:18 UTC
