### ISSUE TITLE
export on command line broken

### ISSUE THREAD

**Issue by romulox-x** [godotengine/godot#2843] opened 2015-11-20 02:04 UTC
I can export fine through the editor interface, but when I try running

/path/to/godot.x11.tools.64 -export "Windows Desktop" -path /path/to/my/game

it shows me

"Error in Add rsrc Section : Error in open file."

the first time.  Every time after that, it segfaults.  I was only able to get it to reset to showing me the error without crashing by pulling new code and building again.  I've tried exporting to X11 and Windows, with the same result.

**Comment by akien-mga** [comment] 2015-11-20 06:37
I can confirm the bug on Linux X11 64bit. The export starts fine, but ends with an error dialog as described above, and then segfaults.

**Comment by bojidar-bg** [comment] 2015-11-20 09:53
I searched the repo, and found those lines:
````cpp
$ git grep -n -A 2 -B 2 "Error In Add rsrc Section"
tools/pe_bliss/pe_bliss_godot.cpp-113-          return String();
tools/pe_bliss/pe_bliss_godot.cpp-114-  } catch(const pe_exception& e) {
tools/pe_bliss/pe_bliss_godot.cpp:115:          String ret("Error In Add rsrc Section : ");
tools/pe_bliss/pe_bliss_godot.cpp-116-          return ret + String(e.what());
tools/pe_bliss/pe_bliss_godot.cpp-117-  }
$ git grep -n -A 2 -B 2 "Error in open file"
tools/pe_bliss/pe_factory.cpp-37-       if(!pe_file)
tools/pe_bliss/pe_factory.cpp-38-       {
tools/pe_bliss/pe_factory.cpp:39:               throw pe_exception("Error in open file.", pe_exception::stream_is_bad);
tools/pe_bliss/pe_factory.cpp-40-       }
tools/pe_bliss/pe_factory.cpp-41-       return pe_factory::create_pe(pe_file,read_debug_raw_data);
--
tools/pe_bliss/pe_rebuilder.cpp-206-    if(!pe_file)
tools/pe_bliss/pe_rebuilder.cpp-207-    {
tools/pe_bliss/pe_rebuilder.cpp:208:            throw pe_exception("Error in open file.", pe_exception::stream_is_bad);
tools/pe_bliss/pe_rebuilder.cpp-209-    }
tools/pe_bliss/pe_rebuilder.cpp-210-    rebuild_pe(pe, pe_file, strip_dos_header, change_size_of_headers, save_bound_import);
````
It seems like the problem lies somewhere within pe_bliss or the use of it.

**Comment by est31** [comment] 2015-11-25 11:36
A stacktrace can be found [here](ttps://gist.github.com/anonymous/c0a2642a0eb95cc42687).

I have done some research. [Here is what I've found out](https://gist.github.com/est31/955602848238c26e7972). I doubt however its required.

I don't think this is a regression. Its just bad behaviour: if you do 

```
bin/godot.x11.tools.64 -export "Linux X11" -path /path/to/game /path/to/destination/executable
```
You can't reproduce the bug with the console.
If you do
```
bin/godot.x11.tools.64 -export "Linux X11" -path /path/to/game
```
you can reproduce the reported behaviour.
The second command will create a file at the path `/path/to/game/data.pck`, and that pck file will then cause the segfault even if you try the first version. If you remove the file, everything is fine.

So, yes, there is a difference, if there is a data.pck file, the GUI way will still work, but the console way will be broken.

Did it work before to export via command line without a path?

**Comment by est31** [comment] 2015-11-26 17:01
I have same behaviour on master than on ed85339bcb42c11789b8d595a4338654c5cf5e89 . So if this is a regression, its older than that commit.

**Comment by akien-mga** [comment] 2015-11-26 17:12
With master HEAD: ```bin/godot.x11.tools.64 -export "Linux X11" -path /path/to/game``` gives me no error, but also no result. For me it does _not_ produce data.pck in the $pwd nor the provided path, it just stops after the export and nothing has happened.

With 1.1stable: ```bin/godot.x11.tools.64 -export "Linux X11" -path /path/to/game``` does the same as above, but also creates data.pck in the provided path.

In both cases it should just error out before the export, saying that the syntax is wrong IMO.

**Comment by akien-mga** [comment] 2015-11-26 17:15
Correction: with master HEAD I also get a data.pck generated, but for some weird reason it is put in the scenes/ folder of my project...

**Comment by est31** [comment] 2015-11-26 21:10
@romulox-x I've created #2921 , is that enough to close this issue? Do you think it should behave differently?

**Closed** 2015-11-26 22:06 UTC
Labels: bug, confirmed, high priority, topic:editor, topic:porting
