### ISSUE TITLE
Issues with non english keyboards in the editor

### ISSUE THREAD

**Issue by philiplb** [godotengine/godot#1106] opened 2015-01-03 15:48 UTC
I'm using a german keyboard and for undoing something, I have to hit Meta+Y instead of Meta-Z.
Y is on the german keyboard where Z is on the english one.

Also, I can't type [ and ]. They are here on alt+5 and alt+6

Operating System: OS X 10.10

**Comment by okamstudio** [comment] 2015-01-03 15:52
for some reason this is broken in OSX, I don't have an mac at this moment
so i'm unable to fix it, so help is appreciated.


On Sat, Jan 3, 2015 at 12:48 PM, philiplb <notifications@github.com> wrote:

> I'm using a german keyboard and for undoing something, I have to hit
> Meta+Y instead of Meta-Z.
> Y is on the german keyboard where Z is on the english one.
>
> Also, I can't type [ and ]. They are here on alt+5 and alt+6
>
> Operating System: OS X 10.10
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/okamstudio/godot/issues/1106>.
>



-- 

*OkamStudio*

**Comment by philiplb** [comment] 2015-01-04 13:08
Alright, this might be a good opportunity to dig into the Godot-codebase.
Could you give me some general directions where to look for this one?

**Comment by reduz** [comment] 2015-01-04 14:17
That would be highly appreciated, my current lack of an mac computer makes
it really difficult to fix or improve the experience there.
Most of the OSX code is in platforms/osx/os_osx.mm . I'm not really sure
what to do to fix thi issue, because scancodes seem to be hardware
specific, but unicode is only sent on keydown events. I have no idea how
remapping of scancodes is supposed to work

**Comment by okamstudio** [comment] 2015-01-04 14:33
on further research, it seems the best way to do this cross-platform is to
get  keyboard layout and perform adequate remaps,
so i guess an API for getting the keyboard layout in OS needs to be added.

On Sun, Jan 4, 2015 at 11:17 AM, Juan Linietsky <notifications@github.com>
wrote:

> That would be highly appreciated, my current lack of an mac computer makes
> it really difficult to fix or improve the experience there.
> Most of the OSX code is in platforms/osx/os_osx.mm . I'm not really sure
> what to do to fix thi issue, because scancodes seem to be hardware
> specific, but unicode is only sent on keydown events. I have no idea how
> remapping of scancodes is supposed to work
>
>
>
> On Sun, Jan 4, 2015 at 10:09 AM, philiplb <notifications@github.com>
> wrote:
>
> > Alright, this might be a good opportunity to dig into the
> Godot-codebase.
> > Could you give me some general directions where to look for this one?
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/okamstudio/godot/issues/1106#issuecomment-68632308>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/okamstudio/godot/issues/1106#issuecomment-68634249>.
>



-- 

*OkamStudio*

**Comment by rraallvv** [comment] 2015-01-04 14:45
The file is in `core/os/keyboard.h`

	KEY_Y=0x0059,
	KEY_Z=0x005A,

[This](http://en.wikipedia.org/wiki/QWERTZ) the or [this](http://stackoverflow.com/questions/781777/cocoa-learn-currently-selected-keyboard-layout-input-language) could be useful too.

**Comment by reduz** [comment] 2015-01-04 14:48
this isn't really that much of a problem, but the layout needs to be
detected for proper remapping

**Comment by rraallvv** [comment] 2015-01-04 14:55
I see, then it seems that this function is the one to modify

static int translateKey(unsigned int key)
	{
		// Keyboard symbol translation table
		static const unsigned int table[128] =
		{
			//...

			/* 06 */ KEY_Z,

			//...

			/* 10 */ KEY_Y,

			//
		};

		//---------- this
		if (detect_layout() == QWERTZ) {
			int key = table[6];
			table[6] = table[10];
			table[10] = key;
		}
		//----------

		if (key >= 128)
			return KEY_UNKNOWN;
		
		return table[key];
	}

**Comment by rraallvv** [comment] 2015-01-04 15:07
Since table is constant you' have  to move the table and the code to remap the keys to a separate function that do the remains only at launch

**Comment by reduz** [comment] 2015-01-04 15:25
yeah, the difficult part is the detect_layout() function :P I'm going to be
working on that function today on Linux, so when i'm done will push to
github so you can help me out with the windows and OSX versions

**Comment by reduz** [comment] 2015-01-05 01:23
just realizing how much a bad idea is to assume that alt+keycode alone can
be used for shorcuts in general, as other keyboard layouts use them for
other stuff

**Comment by okamstudio** [comment] 2015-01-05 01:42
OK, I added this virtual function in OS:

https://github.com/okamstudio/godot/blob/master/core/os/os.h#L362

if you can implement it in OSX, your keyboard should work correctly. I will
try to do at least the X11 implementation

I also fixed some situations where characters that you write with
alt+number do not work, do you think you could try that?





On Sun, Jan 4, 2015 at 10:23 PM, Juan Linietsky <notifications@github.com>
wrote:

> just realizing how much a bad idea is to assume that alt+keycode alone can
> be used for shorcuts in general, as other keyboard layouts use them for
> other stuff
>
> On Sun, Jan 4, 2015 at 11:47 AM, Juan Linietsky <reduzio@gmail.com>
> wrote:
>
> > this isn't really that much of a problem, but the layout needs to be
> > detected for proper remapping
> >
> > On Sun, Jan 4, 2015 at 11:45 AM, rraallvv <notifications@github.com>
> > wrote:
> >
> >> The file is in core/os/keyboard.h
> >>
> >> KEY_Y=0x0059,
> >> KEY_Z=0x005A,
> >>
> >> This <http://en.wikipedia.org/wiki/QWERTZ> the or this
> >> <
> http://stackoverflow.com/questions/781777/cocoa-learn-currently-selected-keyboard-layout-input-language>
>
> >> could be useful too.
> >>
> >> —
> >> Reply to this email directly or view it on GitHub
> >> <https://github.com/okamstudio/godot/issues/1106#issuecomment-68635114>.
>
> >>
> >
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/okamstudio/godot/issues/1106#issuecomment-68658900>.
>



-- 

*OkamStudio*

**Comment by rraallvv** [comment] 2015-01-05 06:14
I'm on it

**Comment by rraallvv** [comment] 2015-01-07 20:50
So, this is what I've got so far, so that others can test and make suggestions

***platform/osx/os_osx.h***

	class OS_OSX : public OS_Unix {
		//...
		virtual LatinKeyboardVariant get_latin_keyboard_variant() const;
		//...
	};



***platform/osx/os_osx.mm***

	// Returns string representation of key, if it is printable.
	//
	static NSString *createStringForKeys(const CGKeyCode *keyCode, int length)
	{
		NSMutableString *output = [[NSMutableString alloc] init];

		TISInputSourceRef currentKeyboard = TISCopyCurrentKeyboardInputSource();
		CFDataRef layoutData = (CFDataRef)TISGetInputSourceProperty(currentKeyboard, kTISPropertyUnicodeKeyLayoutData);
		const UCKeyboardLayout *keyboardLayout = (const UCKeyboardLayout *)CFDataGetBytePtr(layoutData);

		for (int i=0; i<length; ++i) {

			UInt32 keysDown = 0;
			UniChar chars[4];
			UniCharCount realLength;

			UCKeyTranslate(keyboardLayout,
						   keyCode[i],
						   kUCKeyActionDisplay,
						   0,
						   LMGetKbdType(),
						   kUCKeyTranslateNoDeadKeysBit,
						   &keysDown,
						   sizeof(chars) / sizeof(chars[0]),
						   &realLength,
						   chars);

			CFStringRef chararter = CFStringCreateWithCharacters(kCFAllocatorDefault, chars, 1);
			[output appendString:(NSString *)chararter];
			CFRelease(chararter);
		}

		CFRelease(currentKeyboard);

		return output;
	}
	OS::LatinKeyboardVariant OS_OSX::get_latin_keyboard_variant() const {

		static keyboard_layout_dirty = true;
		static LatinKeyboardVariant layout = LATIN_KEYBOARD_QWERTY;

		if (keyboard_layout_dirty) {

			layout = LATIN_KEYBOARD_QWERTY;

			CGKeyCode keys[] = {kVK_ANSI_Q, kVK_ANSI_W, kVK_ANSI_E, kVK_ANSI_R, kVK_ANSI_T, kVK_ANSI_Y};
			NSString *test = createStringForKeys(keys, 6);

			if ([test isEqualToString:@"QWERTZ"]) {
				layout = LATIN_KEYBOARD_QWERTZ;
			} else if ([test isEqualToString:@"AZERTY"]) {
				layout = LATIN_KEYBOARD_AZERTY;
			} else if ([test isEqualToString:@"QZERTY"]) {
				layout = LATIN_KEYBOARD_QZERTY;
			} else if ([test isEqualToString:@"',.PYF"]) {
				layout = LATIN_KEYBOARD_DVORAK;
			} else if ([test isEqualToString:@"XVLCWK"]) {
				layout = LATIN_KEYBOARD_NEO;
			}

			[test release];

			keyboard_layout_dirty = false;
			return layout;
		}
		
		return layout;
	}


`keyboard_layout_dirty` could be updated on keyboard notification changes.

I've tested this with the latest additions, that support the `alt+key`, and it's working ok. However, I couldn't test the `alt+NumKeys` support because I don't have numeric keypad

**Comment by okamstudio** [comment] 2015-01-08 03:48
awesome, do you think you could make a PR? I can't compile to test so i
would rather merge it working

On Wed, Jan 7, 2015 at 5:50 PM, rraallvv <notifications@github.com> wrote:

> So, this is what I've got so far, so that others can test and make
> suggestions
>
> *platform/osx/os_osx.h*
>
> class OS_OSX : public OS_Unix {
>     //...
>     virtual LatinKeyboardVariant get_latin_keyboard_variant() const;
>     //...
> };
>
> *platform/osx/os_osx.mm <http://os_osx.mm>*
>
> // Returns string representation of key, if it is printable.
> //
> static NSString *createStringForKeys(const CGKeyCode *keyCode, int length)
> {
>     NSMutableString *output = [[NSMutableString alloc] init];
>
>     TISInputSourceRef currentKeyboard = TISCopyCurrentKeyboardInputSource();
>     CFDataRef layoutData = (CFDataRef)TISGetInputSourceProperty(currentKeyboard, kTISPropertyUnicodeKeyLayoutData);
>     const UCKeyboardLayout *keyboardLayout = (const UCKeyboardLayout *)CFDataGetBytePtr(layoutData);
>
>     for (int i=0; i<length; ++i) {
>
>         UInt32 keysDown = 0;
>         UniChar chars[4];
>         UniCharCount realLength;
>
>         UCKeyTranslate(keyboardLayout,
>                        keyCode[i],
>                        kUCKeyActionDisplay,
>                        0,
>                        LMGetKbdType(),
>                        kUCKeyTranslateNoDeadKeysBit,
>                        &keysDown,
>                        sizeof(chars) / sizeof(chars[0]),
>                        &realLength,
>                        chars);
>
>         CFStringRef chararter = CFStringCreateWithCharacters(kCFAllocatorDefault, chars, 1);
>         [output appendString:(NSString *)chararter];
>         CFRelease(chararter);
>     }
>
>     CFRelease(currentKeyboard);
>
>     return output;
> }
> OS::LatinKeyboardVariant OS_OSX::get_latin_keyboard_variant() const {
>
>     static keyboard_layout_dirty = true;
>     static LatinKeyboardVariant layout = LATIN_KEYBOARD_QWERTY;
>
>     if (keyboard_layout_dirty) {
>
>         layout = LATIN_KEYBOARD_QWERTY;
>
>         CGKeyCode keys[] = {kVK_ANSI_Q, kVK_ANSI_W, kVK_ANSI_E, kVK_ANSI_R, kVK_ANSI_T, kVK_ANSI_Y};
>         NSString *test = createStringForKeys(keys, 6);
>
>         if ([test isEqualToString:@"QWERTZ"]) {
>             layout = LATIN_KEYBOARD_QWERTZ;
>         } else if ([test isEqualToString:@"AZERTY"]) {
>             layout = LATIN_KEYBOARD_AZERTY;
>         } else if ([test isEqualToString:@"QZERTY"]) {
>             layout = LATIN_KEYBOARD_QZERTY;
>         } else if ([test isEqualToString:@"',.PYF"]) {
>             layout = LATIN_KEYBOARD_DVORAK;
>         } else if ([test isEqualToString:@"XVLCWK"]) {
>             layout = LATIN_KEYBOARD_NEO;
>         }
>
>         [test release];
>
>         keyboard_layout_dirty = false;
>         return layout;
>     }
>
>     return layout;
> }
>
> keyboard_layout_dirty could be updated on keyboard notification changes.
>
> I've tested this with the latest additions, that support the alt+key, and
> it's working ok. However, I couldn't test the alt+NumKeys support because
> I don't have numeric keypad
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/okamstudio/godot/issues/1106#issuecomment-69089554>.
>



-- 

*OkamStudio*

**Comment by rraallvv** [comment] 2015-01-08 07:43
Here you go, this also fix the OS X build by removing the compiler flag `LIBYUV_NEON`, as can be seen [here](https://github.com/okamstudio/godot/blob/master/drivers/theoraplayer/src/YUV/libyuv/include/libyuv/scale_row.h#L28) this flag is not needed for OS X, and the iOS build already defines `_ARM_NEON_`

I tested the patch for US, Spanish, German and French, it works ok, also added better error checking

**Comment by rraallvv** [comment] 2015-01-08 15:38
Now that we are a it, the flag `LIBYUV_NEON` is to enable NEON separately on each individual ARM platform, but it's better not to add it, since we can control that using `__ARM_NEON__` instead, which would enable NEON for all libraries that support that feature

On i386 and x64 platforms, there is nothing to be added, unless we are targeting very old hardware, in that case the flag to be added is `LIBYUV_DISABLE_X86`, because the theora player assumes SIMD by default on everything.

For Android, I can't say for sure whether it's ok to add LIBYUV_NEON, it seems to me that its better not to add it, because NEON would be automatically enabled with __ARM_NEON__

**Comment by vnen** [comment] 2015-10-29 22:15
As #1151 was merged, closing this as fixed.

**Closed by vnen** 2015-10-29 22:15 UTC
Labels: bug, platform:osx, topic:editor

**Comment by icnikerazah** [comment] 2018-01-22 13:21
https://stackoverflow.com/questions/21597804/determine-os-x-keyboard-layout-input-source-in-the-terminal-a-script
<img width="768" alt="ekran resmi 2018-01-22 16 12 26" src="https://user-images.githubusercontent.com/33985414/35222616-94bda080-ff8f-11e7-99ff-ca6ab67a9ab5.png">

**Comment by vnen** [comment] 2018-01-22 13:35
@icnikerazah please stop spamming every ticket with this link. Just put it once on a relevant issue and if someone can fix it they'll see it. If you found a solution you can open a pull request. This issue here was closed over two years ago, posting anything here is totally pointless.

**Comment by icnikerazah** [comment] 2018-01-22 15:34
i am not spammer . i am trying help you. all are revelant issue.  i am not c++ programmer. this is your job and do it right.

**Comment by rraallvv** [comment] 2018-01-22 23:44
@vnen I searched in the Cocoa and even the Carbon API but there is nothing that allows to get the keyboard layout. The answer in the link is a workaround that won't work for all cases, because the value in `AppleCurrentKeyboardLayoutInputSourceID` needs to be mapped to [`LatinKeyboardVariant`](https://github.com/godotengine/godot/blob/34c988cfa92f19c232b65990704816ba1c7d2622/core/os/os.h#L419), and with values like `Turkish-QUERTY` is seems an easy task but not all names have the type of keyboard layout included in it. Also, I don't think there are two different keyboard layouts with the same six letters in the first row. What needs to be done is to add the new value `LATIN_KEYBOARD_COLEMAK` to the detection code.

**Comment by rraallvv** [comment] 2018-01-22 23:45
@icnikerazah & @vnen I searched in the Cocoa and even the Carbon API but there is nothing that allows to get the keyboard layout. The answer in the link is a workaround that won't work for all cases, because the value in `AppleCurrentKeyboardLayoutInputSourceID` needs to be mapped to [`LatinKeyboardVariant`](https://github.com/godotengine/godot/blob/34c988cfa92f19c232b65990704816ba1c7d2622/core/os/os.h#L419). With values like `Turkish-QUERTY` is seems an easy task but not all names have the type of keyboard layout included in it. Also, I don't think there are two different keyboard layouts with the same six letters in the first row. What needs to be done is to update to detect the new value `LATIN_KEYBOARD_COLEMAK`.

**Comment by rraallvv** [comment] 2018-01-23 00:01
@vnen never mind, it's already been done.

**Comment by rraallvv** [comment] 2018-01-23 13:25
@icnikerazah could you please post what keys have the wrong characters on them, or maybe a picture of the piece of hardware with the layout clearly visible?

**Comment by Zireael07** [comment] 2018-01-23 13:31
He posted elsewhere that he needs to press Control + dotless i (which is where the normal i usually is) for Control + I function (forgot which function it was) instead of Control + i (which is where ' is on our keyboards).

**Comment by hubbyist** [comment] 2018-01-23 14:52
I think problem is https://en.wikipedia.org/wiki/Dotted_and_dotless_I .

In php I use a workaround wrapper as below sometimes

	mb_convert_case(str_replace(['i', 'I'], ['İ', 'ı'], $text), $case);

AFAIK there is no solution for ascii character mapping.

**Comment by hubbyist** [comment] 2018-01-23 14:54
> Most Unicode software uppercases ı to I and lowercases İ to i, but, unless specifically configured for Turkish, it lowercases I to i and uppercases i to I. Thus uppercasing then lowercasing, or vice versa, changes the letters.

**Comment by rraallvv** [comment] 2018-01-23 17:54
I've tried a few things with Godot 2.1 and it seems the issue could be partly solved, for Gogot 3 [this line](https://github.com/godotengine/godot/blob/34c988cfa92f19c232b65990704816ba1c7d2622/editor/project_settings_editor.cpp#L362) would need to be changed as follows:

	String str = keycode_get_string(keycode_has_unicode(k->get_scancode()) ? k->get_unicode() : k->get_scancode()).capitalize();

I think there are maybe half a dozen more calls to `keycode_get_string` where the change might  need to be applied, although I haven't checked them all. 

There is still the issue with the capital letter for *i* and **dot-less i**, I haven't tried what @hubbyist suggested though.

**Comment by icnikerazah** [comment] 2018-01-23 20:53
@rraallvv The problem is not related to upper or lower case. examine the above GIF. completely different keyboard layout.

only visible ones (without shift/alt)

USA QWERTY | Turkish - QWERTY PC
--------------| ----------------------
 §  |  " 
 ~~-~~  |  *
 =  |  -
 i  |  ı
 [  |  ğ
 ]  |  ü
; | ş
' | i
\ | ,
` | <
, | ö
. | ç
/ | .

![ekran resmi 2018-01-23 23 29 08](https://user-images.githubusercontent.com/33985414/35300083-7b882b3a-0098-11e8-87e0-5e2c3ec8bf85.png)

Shift +

![ekran resmi 2018-01-23 23 28 46](https://user-images.githubusercontent.com/33985414/35300098-8771a908-0098-11e8-8fe2-aa43f7766a46.png)

Alt +

![ekran resmi 2018-01-23 23 28 16](https://user-images.githubusercontent.com/33985414/35300089-813185d6-0098-11e8-8687-563363aa9a07.png)
