### ISSUE TITLE
Problem with tiles and two monitors

### ISSUE THREAD

**Issue by Torguen** [godotengine/godot#34003] opened 2019-11-29 20:38 UTC
**Godot version:**
3.2 beta 1 mono

**OS/device including version:**
win10 64 home

**Issue description:**
With a tilemap object selected and two monitors, the click on the alternative monitor is processed by Godot.

**Steps to reproduce:**
With two monitors.
Click the mouse outside the editor on the other monitor.
Then paint a tile in the editor and you will see that a straight line has been drawn automatically between some starting point and the point where I painted the tile in the editor.

In this GIF you can see that the mouse is moved to another monitor where Chrome is open, there is clicked and then the cursor clicks again in the editor, then a straight line is created (My monitors are not of the same resolution).

![GIF](https://user-images.githubusercontent.com/19652075/69885698-b233cb80-12de-11ea-8ee7-eef65ebb7a63.gif)

**Minimal reproduction project:**
[testTiles.zip](https://github.com/godotengine/godot/files/3906355/testTiles.zip)

**Comment by KoBeWi** [comment] 2019-11-29 20:48
Duplicate of #10949

**Closed by KoBeWi** 2019-11-29 20:48 UTC
