### ISSUE TITLE
Very low Fps at godot 4.2

### ISSUE THREAD

**Issue by Marshmellow-G** [godotengine/godot#93220] opened 2024-06-16 07:42 UTC
### Tested versions

it's happens on only godot 4.not in 3.

### System information

windows 11,godot 4.2.2,opengl

### Issue description

I can run godot engine at 300 fps with shadows.and in gameplay there is a solid 60 fps.But,Sometimes it just runs on 12-16 fps.my pc is a good pc.i guess it's a Bug*

### Steps to reproduce

i don't know.

### Minimal reproduction project (MRP)

here is  a screenshot
![fpsbug](https://github.com/godotengine/godot/assets/172928790/7ee0b30f-d013-44f2-9658-c51f672a0779)

**Comment by AThousandShips** [comment] 2024-06-16 08:24
This is unfortunately not enough information, we need some examples of the scenes you're running to be able to investigate this

So please upload a minimum reproduction project to allow this to be tested:
- A small Godot project which reproduces the issue, with no unnecessary files included. Be sure to not include the `.godot` folder in the archive (but keep `project.godot`).
- Having an MRP is very important for contributors to be able to reproduce the bug in the same way that you are experiencing it. When testing a potential fix for the issue, contributors will use the MRP to validate that the fix is working as intended.
- Drag and drop a ZIP archive to upload it (max 10 MB). **Do not select another field until the project is done uploading.**
- **Note for C# users:** If your issue is *not* C#-specific, please upload a minimal reproduction project written in GDScript. This will make it easier for contributors to reproduce the issue locally as not everyone has a .NET setup available.

**Comment by Marshmellow-G** [comment] 2024-06-16 09:03
@Athousandships.i guess it causes for my device high temperature .can you rate this art sytle

**Comment by AThousandShips** [comment] 2024-06-16 09:06
Rate? I can't tell anything about the performance demands of your game just based on a single screenshot

I'd suggest asking on the [forums](https://forum.godotengine.org/) if you want feedback on performance and game design, this is for bug reporting and we'd need something that was broken in the engine for it to be the right place for it, it sounds like your computer simply isn't powerful enough to run your game, either because it's just too expensive or because your game isn't optimized and you need to change the way the project is done to make it faster, but that's something to get help for at the forums

**Comment by Zireael07** [comment] 2024-06-16 09:24
Just as a FYI, I had similar drops in 3.x too. They turned out to be a combo of 1) GPU heating up 2) GPU not liking certain environment node settings 3) physics in Godot generally can cause occasional drops

**Comment by Marshmellow-G** [comment] 2024-06-16 10:10
Zireael07.You are right.i power off my pc for an hour and now it runs smoothly .Thanks

**Comment by Calinou** [comment] 2024-06-16 19:15
Closing per the above comment.

If you're using a laptop, make sure to clean it to remove dust (this might require tearing it apart), and elevate it a little so it gets better airflow.

**Closed by Calinou** 2024-06-16 19:15 UTC
Labels: needs testing, performance

**Comment by Marshmellow-G** [comment] 2024-06-17 01:38
Okay,thanks for the help guys!
