### ISSUE TITLE
VIEWPORT_SIZE doesn’t seem to give the viewport size in pixels

### ISSUE THREAD

**Issue by kelvin13** [godotengine/godot#19900] opened 2018-07-02 01:24 UTC
**Godot version:** 3.0.2

**OS/device including version:** Ubuntu 17.10

**Issue description:** The [documentation](http://docs.godotengine.org/en/3.0/tutorials/shading/shading_language.html#vertex-built-ins) says the `VIEWPORT_SIZE` uniform contains the size of the viewport in pixels, but its actual value seems to be an aspect ratio. For example, resizing the window in the vertical direction should not affect `VIEWPORT_SIZE.x`, but it does.

**Steps to reproduce:** Create any shader material that uses `VIEWPORT_SIZE`

**Minimal reproduction project:** [viewport.zip](https://github.com/godotengine/godot/files/2153433/viewport.zip)

**Comment by CarlGustavAlbertDwarfsteinYung** [comment] 2019-10-28 08:12
I confirm this is an issue still in 3.2 alpha 3. Supposedly GLES2 works just GLES3 does not.

**Comment by CarlGustavAlbertDwarfsteinYung** [comment] 2019-10-31 02:59
I have been investigating this issue and it seems the issue is that sizes are never passed but rather some kind of mipmap effect for reflection purposes only
https://github.com/godotengine/godot/blob/d482a1d8e8b4e68f2f386ba618cd091c79c20424/drivers/gles3/rasterizer_scene_gles3.cpp#L3560

**Comment by clayjohn** [comment] 2019-10-31 04:38
Viewport size is defined here:

https://github.com/godotengine/godot/blob/7d710a745e3eecbde482349fff78f0a4e14f6371/drivers/gles3/rasterizer_scene_gles3.cpp#L4177

**Comment by lawnjelly** [comment] 2020-01-22 14:47
In GLES3 viewport size seems to be transferred as part of the state.ubo_data:

https://github.com/godotengine/godot/blob/7d710a745e3eecbde482349fff78f0a4e14f6371/drivers/gles3/rasterizer_scene_gles3.cpp#L2693

apart from the possible banditing for reflection.

It is actually currently initialized to half the viewport extents, which is (I think, haven't double checked this) half the width and height in world units at the near clipping plane. I was looking to see whether I should change this to be the full width and height, but looks like the width and height in pixels is desired rather than anything derived from the camera matrix.

What exactly is this used for currently? I'm presuming it is there for custom shaders. I can't see it used in the glsl files aside from the screen space reflection code. If so would it be safe for me to change it to viewport width and height in pixels (as described in the docs)?

**Comment by clayjohn** [comment] 2020-01-22 15:17
@lawnjelly, I think it is only there for ``VIEWPORT_SIZE`` which should be width and height in pixels.

**Closed** 2020-01-22 21:02 UTC
Labels: bug, topic:rendering

**Comment by grahamoverby** [comment] 2020-10-13 04:00
Unless I'm missing something super obvious, VIEWPORT_SIZE  not working seems to still be a problem in 3.2.2.
![Screenshot 2020-10-12 225933](https://user-images.githubusercontent.com/69185131/95813951-babaa800-0cde-11eb-96c1-be89fa982c43.png)

**Comment by CarlGustavAlbertDwarfsteinYung** [comment] 2020-10-13 05:18
@grahamoverby  I don't know if is available in fragment shader. You might have to set it in vertex and use it in fragment.

**Comment by lawnjelly** [comment] 2020-10-13 07:23
If this is the case this should be opened as an issue, either the code or the docs might be wrong, as the docs say VIEWPORT_SIZE should be available in fragment shaders.

**Comment by CarlGustavAlbertDwarfsteinYung** [comment] 2020-10-13 07:25
I don't know if this is indeed the case but there is an issue already opened that talks about certain built in variables not useable in all types of shaders https://github.com/godotengine/godot/issues/14904

**Comment by akien-mga** [comment] 2020-10-13 07:30
This issue was about fixing the behavior of `VIEWPORT_SIZE` where it is defined, not whether it's defined everywhere.

`VIEWPORT_SIZE` is defined for `vertex`, `fragment` and `light` **spatial** shaders, as described in the docs: https://docs.godotengine.org/en/stable/tutorials/shading/shading_reference/spatial_shader.html?highlight=VIEWPORT_SIZE
If you're trying to use it in a **canvas_item** shader, it's not defined.

**Comment by lawnjelly** [comment] 2020-10-13 07:31
Ah good catch! :smile:

**Comment by grahamoverby** [comment] 2020-10-13 15:36
Thank you @akien-mga , and sorry about that, my mistake. Read the docs end to end and still missed that!
