### ISSUE TITLE
Textures are looks abnormal in Android export. 

### ISSUE THREAD

**Issue by sohamgamedev** [godotengine/godot#67784] opened 2022-10-23 07:24 UTC
### Godot version

4.0 beta 3

### System information

Zorin OS,GLES3, intel i3 5005U

### Issue description

In editor which I assign textures are looks good in editor and pc export but when i export for Android so it's look abnormal. 

### Steps to reproduce

i have tried to change the render settings of Android as pc render settings but that's not work, so please if you are reading this and you have solution so send me as soon as possible. 

### Minimal reproduction project

3d runner game

**Comment by alcomposer** [comment] 2022-10-23 07:42
Have you tried setting compression mode to `Lossless` in import settings? At this point that is the only mode that works on the Quest 2 (Android)

![Screenshot from 2022-10-23 18-11-31](https://user-images.githubusercontent.com/12004932/197380363-1a4ee909-e08f-416c-a026-ad9c5e19d4f4.png)

**Comment by Calinou** [comment] 2022-10-23 16:03
@sohamgamedev or @alcomposer Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

**Comment by alcomposer** [comment] 2022-11-13 04:05
*update*
Swizzling the texture of VRAM-Compressed with `bgr` fixes the color issue in Quest 2 builds. But obviously shows the wrong color in game Godot editor.
![Screenshot from 2022-11-13 14-33-47](https://user-images.githubusercontent.com/12004932/201505131-c11f7c2d-0ed0-42b3-aba3-cc327b034a96.png)

**Comment by Calinou** [comment] 2022-11-13 19:46
Duplicate of https://github.com/godotengine/godot/issues/65127.

**Closed by Calinou** 2022-11-13 19:46 UTC
Labels: bug, platform:android, topic:rendering, needs testing, topic:3d
