### ISSUE TITLE
Importing assets use only one processor core

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#22886] opened 2018-10-09 16:00 UTC
**Godot version:**
3.1 745ae39

**OS/device including version:**
Ubuntu 18.04 i7 4770k(4 cores 8 threads) GTX 970  driver 396.54 and 128GB SSD

**Issue description:**
When loading big project, Godot must at first import all assets, but even on powerful machine it takes a lot of time. I think that could and should be paralleled because importing assets doesn't seems depend on each other. 

**Steps to reproduce:**
1. Import game with a lot of assets

Video with usage of processor: https://streamable.com/xbezj

**Minimal reproduction project:**
https://github.com/godotengine/tps-demo

**Comment by menip** [comment] 2019-04-11 17:55
Agreed. Much slower than expected on my 8 core 16 thread processor.

**Comment by akien-mga** [comment] 2019-11-14 13:18
Related to #10583.

**Comment by akien-mga** [comment] 2019-11-14 13:20
Actually duplicate of #23252.

**Closed by akien-mga** 2019-11-14 13:20 UTC
Labels: feature proposal, topic:editor
