### ISSUE TITLE
PoolVector2Array cannot be inverted in a dictionary

### ISSUE THREAD

**Issue by steambap** [godotengine/godot#42299] opened 2020-09-24 07:41 UTC
**Godot version:**

v3.2.3

**OS/device including version:**

MacOS GLES3

**Issue description:**

When PoolVector2Array is assigned to a dictionary, call invert() on it has no effect.
I expect PoolVector2Array to work like normal Array and can be invert() in a dictionary.

**Steps to reproduce:**
```
var dict = {}
var arr = PoolVector2Array()
arr.append(Vector2(1,2))
arr.append(Vector2(3,4))
dict["pool"] = arr
dict["pool"].invert()
print(dict["pool"])
# Will print [(1, 2), (3, 4)]
```

**Minimal reproduction project:**

Copy the above code to any project.

**Comment by akien-mga** [comment] 2020-09-24 08:22
Duplicate of #8409, this is fixed in `master` for 4.0 but won't be changed in the `3.2` branch.

The workaround is to use an intermediate variabel:
```
var tmp_arr = dict["pool"]
tmp_arr.invert()
dict["pool"] = tmp_arr
```

**Closed by akien-mga** 2020-09-24 08:22 UTC
