### ISSUE TITLE
Relative mouse motion is unreliable at scale ratios != 1:1 (rounding errors)

### ISSUE THREAD

**Issue by arturjpv** [godotengine/godot#5907] opened 2016-07-25 19:30 UTC
_Bugsquad edit:_ Changed the issue to address the root cause of the symptoms that are described hereafter.

The problem is that the relative mouse motion is limited to integers, and thus unreliable as soon as the scale is different from (1,1). E.g. at a scale of (2,2), only mouse motion deltas of multiples of 2px will be detected; 1px delta will be seen as 0, 3px as 1.

Reproducer: [mousemotion_relative.zip](https://github.com/godotengine/godot/files/384518/mousemotion_relative.zip)
Use the LineEdit to change the scale, and experiment a bit with moving the mouse. Left mouse click resets the "drag origin" value.

---

Mac OSX El Capitan - Godot 2.1 RC.

Shader graphs nodes only are displaced correctly when scale factor is 1:1. Otherwise, when moving a node, they move less distance than the mouse moved distance. Seems like a factor is needed to compensate the scale and translate the real movement to shader graph units.

To reproduce:
- Open a shader graph with some nodes
- Move a node with 1:1 zoom
- Increase or decrease the zoom level
- Move the node -> Moved distances does not match the mouse moved distance

**Comment by akien-mga** [comment] 2016-07-26 11:57
That one is for @MarianoGnu I think :D

**Comment by MarianoGnu** [comment] 2016-07-26 12:07
Dude, you do a couple lines of code in a class and instantly every issue related is yours (?)

**Comment by akien-mga** [comment] 2016-07-26 12:13
I didn't mean to force this on you, it just happens that you're one of the active devs who already had a look at the shader graph editor, and you know your way around input management and usability issues, so I thought you might be interested. If you're not, sorry about the not, the issue is likely easy to fix anyway so I might have a look myself.

**Comment by MarianoGnu** [comment] 2016-07-26 14:20
Just joking, but maybe i wont have time before 2.1-rc2

**Comment by akien-mga** [comment] 2016-07-26 17:33
Well I've looked into this a while and it's harder than I initially thought. The GraphEdit dragging happens here: https://github.com/godotengine/godot/blob/454b210/scene/gui/graph_edit.cpp#L548-L557
I tweaked the logic a bit, thinking that it might be a rounding issue (especially as dragging fast shows no offset, but dragging slowly shows an increasing offset), to no avail.

It actually see like `drag_accum`, which is the accumulation of `Vector2(p_ev.mouse_motion.relative_x,p_ev.mouse_motion.relative_y)` for all events, seems not to be modified for super-small drag events (1px) when zoomed (both zoomed in and zoomed out).

So I guess the rounding issue is to search directly at the Input level..

**Comment by akien-mga** [comment] 2016-07-26 17:50
Alright it's a bug with how relative mouse motion events are computed on scaled nodes.

**Comment by akien-mga** [comment] 2016-07-26 18:38
I re-purposed the issue edited the OP, also linking a minimal project that exhibits the issue.
A potential solution for this bug would be to change relative mouse motions to report floats instead of integers.

**Comment by akien-mga** [comment] 2016-07-26 19:03
This issue will be properly fixed by making InputEvent use floats in 3.0; in the meantime, I have an idea on how to hack GraphEdit to fix the bug initially reported (basically by using the local mouse pos, which is a float, and keeping track of the delta with a new variable).

**Comment by akien-mga** [comment] 2016-07-26 21:21
Well, sorry about hijacking this issue :p I proposed a workaround that should fix the initial problem: #5926.

**Comment by akien-mga** [comment] 2017-03-16 23:14
> The problem is that the relative mouse motion is limited to integers, and thus unreliable as soon as the scale is different from (1,1). E.g. at a scale of (2,2), only mouse motion deltas of multiples of 2px will be detected; 1px delta will be seen as 0, 3px as 1.

@reduz We planned to fix this (and some other input related issues) for 3.0 as it breaks compatibility. Is it still on the agenda?

**Comment by reduz** [comment] 2017-08-05 13:00
in 3.0 the mouse motion is now float, so this problem should be solved

**Closed by reduz** 2017-08-05 13:00 UTC
Labels: bug, confirmed, topic:editor, usability
