### ISSUE TITLE
C# Casting Node to VBoxContainer fails  (also GetNode() returns null on a valid path, fails to cast internally)

### ISSUE THREAD

**Issue by LordBrkica** [godotengine/godot#39373] opened 2020-06-07 18:09 UTC
**Godot version:**

Godot Engine v3.2.1.stable.mono.official 

**OS/device including version:**

Windows10 ,OpenGL ES 2.0 Renderer: Radeon RX 570 Serie

**Issue description:**

Take a good look at this:
![image](https://user-images.githubusercontent.com/51578785/83976435-1c66a200-a8fa-11ea-974e-42deff2be6a1.png)

First I though I have a problem with _GetNode()_ as I can use _GetNode()_ to retrieve a button _mahButton_. But when I try to use _GetNode()_ to retrieve its grandparent _UnitTools_ I get a null.

It seems that the actual problem is in casting a Node to VBoxContiner.
`        var checkClass = aContainerNode.GetClass();   //this returns VBoxContainer indicating that aContainerNode should be a VBoxContainer`

But in the screenshot you can see that the value of:
`VBoxContainer castedBox = aContainerNode as VBoxContainer;` 
equals `null`

Also note - everything works, in the editor my _aContainerNode_  is the VBoxContainer, the UI also behavies as if the `aContainerNode ` is a _VBoxContainer_. 

So on one hand everythign works as if this node is normal, on the other I cannot retrieve it and casting it returns null....
**Steps to reproduce:**
Cannot reproduce it yet outside my own project, but I will let you know when I am able to. I wanted to report this ASAP becuase this strange behaviour has been driving me nuts the entire day, so maybe it will help someone else.

I tried changing the Node type (and back) in editor (to somehow "refresh" the scene), but that didnt help.

**Minimal reproduction project:**

Cannot reproduce it yet outside my own project, but I will let you know when I am able to.

Possibly the same problem as described here:
https://github.com/godotengine/godot/issues/38497#issue-613033642

**Comment by PoirotovBrk** [comment] 2020-06-07 19:19
So, here is the snippet of my project tree:
![image](https://user-images.githubusercontent.com/51578785/83977730-24770f80-a903-11ea-8787-1947213eb777.png)

Here is the summary of the problem:
```
        //this works as expected and returns the button
        Button mybutton= GetNode(PathToButton) as Button;
        //this unexpectedly returns null
        VBoxContainer UnitTools = GetNode(PathToUnitTools) as VBoxContainer;

        //this will return the base node 
        Node aNode = GetNode<Node>(PathToUnitTools);

        //casting aNode to VBox fails
        VBoxContainer UnitTools2 = aNode as VBoxContainer; //fails

        //casting aNode to Godot.VBoxContainer works
        Godot.VBoxContainer aContainerNode = aNode as VBoxContainer;

        //calling GetNode<Godot.VBoxContainer>(PathToUnitTools)  also works
```
So the problem I am experiencing seems to be exactly **the same** as the problem described [here](https://github.com/godotengine/godot/issues/38497#issue-613033642).

VBoxContainer doesnt work but Godot.VBoxContainer does.

**Comment by clayjohn** [comment] 2020-06-17 23:29
If the problem is exactly the same as #38497, then I will close this issue in favour of #38497. We don't need to have two issues open to track the same problem.

**Closed by clayjohn** 2020-06-17 23:29 UTC
Labels: bug, topic:mono
