### ISSUE TITLE
ColorPicker Hex entry

### ISSUE THREAD

**Issue by Zentropic** [godotengine/godot#76800] opened 2023-05-07 05:59 UTC
### Godot version

v4.0.2.stable.official [7a0977ce2]

### System information

Windows 11, AMD Ryzen 5 3500U with Radeon Vega Mobile Gfx     2.10 GHz

### Issue description

  Typing in a value/pasting a value that cannot be interpreted as hex in a ColorPicker control issues an error in the debugging console:

E 0:00:08:0494   html: Invalid color code: red.
  <C++ Error>    Condition "r < 0.0f" is true. Returning: Color()
  <C++ Source>   core/math/color.cpp:366 @ html()

  The problem seems to be that checking against valid hex characters isn't occurring and no "text_submitted" or "focus_exited" signal handler for the LineEdit control is reverting invalid text to a previously known valid value.  The selected color then becomes black!

### Steps to reproduce

  Open up a ColorPicker control and type in an invalid hex string into the hex LineEdit control.

### Minimal reproduction project

N/A

**Comment by MewPurPur** [comment] 2023-05-07 14:35
Fixed by #75905

**Comment by Calinou** [comment] 2023-05-07 14:58
- Duplicate of https://github.com/godotengine/godot/issues/75897.

**Closed by Calinou** 2023-05-07 14:58 UTC
