### ISSUE TITLE
Clicking to add node in Curve2D causes error when 'undo' is pressed, corrupts curve, can cause crashes.

### ISSUE THREAD

**Issue by Proggle** [godotengine/godot#99578] opened 2024-11-23 08:12 UTC
### Tested versions

v4.3.stable.official [77dcf97d8]

### System information

Godot v4.3.stable - Windows 10.0.22631 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3080 (NVIDIA; 32.0.15.6081) - 12th Gen Intel(R) Core(TM) i9-12900 (24 Threads)

### Issue description

Using 'undo' on a new point in a curve2d corrupts the curve data and can cause the editor to crash.
Possibly the same as ( https://github.com/godotengine/godot/issues/96636 ) but per the thread that one doesn't cause problems using Control+Z (only the history bar).

### Steps to reproduce

Create a new point on a path2d by clicking on it.  Attempt to remove this new point by pressing control+Z.  An error pops up.
https://github.com/user-attachments/assets/e146a08f-d0e3-414d-924c-3e86072d4aa9

The editor is now in a glitched state where the curve2d no longer responds properly.  No point in the curve can be edited, and the curve2d cannot be removed from the path2d.  In addition, continuing work with this corrupted curve can result in the editor crashing, though am not sure of exact trigger conditions.  Windows game bar does not record submenus, but clicking on the curve2d and selecting 'clear' fails to remove it from the path2d.

![Image](https://github.com/user-attachments/assets/a5284821-bbe3-4bb3-aa09-26ed8e35322b)

https://github.com/user-attachments/assets/081a80bb-33fc-42b3-ba1a-0b5f513eb60d

### Minimal reproduction project (MRP)

Can be done in a blank project by just adding a path2d and creating a curve.

**Comment by Wolve-3DTech** [comment] 2024-11-23 10:44
Got quite the same issue. Moreover, when i create some points on my curve, and try to delete them, nothing happens. So that force me to reload my whole project.

**Comment by matheusmdx** [comment] 2024-11-23 13:55
@AThousandShips I don't think this is different from #96636 or #96081, in all the cases the bug starts with a Path2D being splited, the erros are the same and the crash can't be reproduced easily like the bug per se, and even if this can trigger a crash, the root cause that starts the bug was already solved by #96237 anyways. IMO this issue and #96636 can be closed as solved.

**Comment by AThousandShips** [comment] 2024-11-23 13:59
Closing as per the above, if anyone can confirm this in [4.4.dev5](https://godotengine.org/article/dev-snapshot-godot-4-4-dev-5/) or later please comment and this can be reopened

**Closed by AThousandShips** 2024-11-23 13:59 UTC
Labels: bug, topic:editor, crash, topic:2d
