### ISSUE TITLE
Can't create folders. 2.1

### ISSUE THREAD

**Issue by n-pigeon** [godotengine/godot#5517] opened 2016-07-01 19:41 UTC
**Operating system or device - Godot version:**
Windows 7 64bit Godot 2.1

**Steps to reproduce:**
Try to create new folder when for example saving scene.

**Comment by vnen** [comment] 2016-07-01 19:53
Duplicate of #5323. It was fixed yesterday.

**Closed by vnen** 2016-07-01 19:53 UTC
