### ISSUE TITLE
Using 16-bit PNG normal maps causes incorrect lighting

### ISSUE THREAD

**Issue by mss1451** [godotengine/godot#37220] opened 2020-03-22 02:21 UTC
**Godot version:**
v3.2.1.stable.official

**OS/device including version:**
Manjaro Linux 19.0.2

**Issue description:**
16-bit PNG file used as a normal map causes uneven lighting on the model. This doesn't happen with 8-bit PNG files.

In the following picture, there is a cylinder with a normal map attached. There is a lighting discontinuity along the UV seam with 16-bit PNG normal map.
![normal_discont](https://user-images.githubusercontent.com/42681517/77240575-af941380-6bf8-11ea-8f28-d21cc93dfac1.png)

Everything is the same but this time with an 8-bit PNG normal map:
![normal_corr](https://user-images.githubusercontent.com/42681517/77240659-5d072700-6bf9-11ea-99ba-18b71d8bbb60.png)

**Minimal reproduction project:**
[png_16bit_normal_map.zip](https://github.com/godotengine/godot/files/4364544/png_16bit_normal_map.zip)

**Comment by Calinou** [comment] 2020-03-22 15:48
I can confirm this on 3.2.1. In the cylinder using the 16-bit normal map, I can also notice slight "cracks" in the dark area (click to view the full size):

![image](https://user-images.githubusercontent.com/180032/77253751-a9378300-6c5c-11ea-9dac-a990ef2a29f7.png)

The 16-bit normal map appears to be significantly brighter in the FileSystem dock previews:

![image](https://user-images.githubusercontent.com/180032/77253759-bc4a5300-6c5c-11ea-98ea-9096a4c22ef9.png)

Playing with the **Compress Mode**, **Hdr Mode**, **Normal Map** or **Hdr As Srgb** options in the Import tab doesn't solve the issue.

**Comment by jluini** [comment] 2020-04-19 08:07
According to 3.2 docs ([https://docs.godotengine.org/en/3.2/getting_started/workflow/assets/importing_images.html#supported-image-formats](https://docs.godotengine.org/en/3.2/getting_started/workflow/assets/importing_images.html#supported-image-formats)) only 8-bit png are supported:


Supported image formats
Godot can import the following image formats:

BMP (.bmp)
DirectDraw Surface (.dds) - If mipmaps are present in the texture, they will be loaded directly. This can be used to achieve effects using custom mipmaps.
OpenEXR (.exr) - Supports HDR (highly recommended for panorama skies).
Radiance HDR (.hdr) - Supports HDR (highly recommended for panorama skies).
JPEG (.jpg, .jpeg) - Doesn’t support transparency per the format’s limitations.
**PNG (.png) - Precision is limited to 8 bits per channel upon importing (no HDR images).**
Truevision Targa (.tga)
SVG (.svg, .svgz) - SVGs are rasterized using NanoSVG when importing them. Support is limited; complex vectors may not render correctly. For complex vectors, rendering them to PNGs using Inkscape is often a better solution. This can be automated thanks to its command-line interface.
WebP (.webp)

**Comment by JohanAR** [comment] 2020-07-09 10:41
I dug a little bit in this since I also ran into this problem.

> Precision is limited to 8 bits per channel upon importing (no HDR images).

This means that 16-bit png images will be converted to 8-bit when you import them. It doesn't mean that 16-bit png files aren't supported.

The problem seems to be related to color profiles, and possibly this flag:

>    PNG_IMAGE_FLAG_16BIT_sRGB == 0x04
>    On read if the image is a 16-bit per component image and there is no gAMA
>    or sRGB chunk assume that the components are sRGB encoded.  Notice that
>    images output by the simplified API always have gamma information; setting
>    this flag only affects the interpretation of 16-bit images from an
>    external source.  It is recommended that the application expose this flag
>    to the user; the user can normally easily recognize the difference between
>    linear and sRGB encoding.  This flag has no effect on write - the data
>    passed to the write APIs must have the correct encoding (as defined
>    above.)
>
>    **If the flag is not set (the default) input 16-bit per component data is assumed to be linear.**

In my case (#40214) the png files did not have any color information, so libpng assumed the 16-bit file was linear.
In this case the png file has an embedded ICC profile, but it is up to the application (i.e. Godot) to handle those.

There are currently a few workarounds:
* Reimport the file with "Srgb = enable"  (defaults to "detect" which appears to have the same effect as disable)
* Save your png-16 file with gamma information. This can be done in GIMP's export dialog for example.
* Convert your png-16 to png-8 or other format

I think this should be fixed though, because right now 8-bit and 16-bit pngs appear to be handle in different ways. It is also inconsistent with all other image viewers/editors that I have tried. Setting PNG_IMAGE_FLAG_16BIT_sRGB solves the problem for all the files I have tested, but I haven't been able to find a png with sRGB chunk to test with. It is also possible that this behaves differently on different platforms, but I think I'll submit a PR and see what they say.

**Comment by Calinou** [comment] 2020-07-09 11:58
> Reimport the file with "Srgb = enable" (defaults to "detect" which appears to have the same effect as disable)

When using **Detect**, Godot enables sRGB if the texture is detected to be used in a 3D context, and disables it otherwise. The detection may not be 100% reliable though.

**Comment by JohanAR** [comment] 2020-07-09 12:39
> When using **Detect**, Godot enables sRGB if the texture is detected to be used in a 3D context, and disables it otherwise. The detection may not be 100% reliable though.

So if I've understood this correctly, this flag tells Godot to perform linear to sRGB conversion, and Godot expects all textures to be in sRGB format?

The flag could also be interpreted as "this image is in sRGB format", but I don't get that to make any sense with the expected behaviour (because the too bright 16-bit png should have been loaded as linear 8-bit data).

I've always thought color profiling is extremely confusing.. I mean I get the basic theory behind it, but to actually get it working in practice is another story..

**Comment by JohanAR** [comment] 2020-07-09 19:22
A few test images I created. These have had the embedded ICC profiles stripped, so without the gamma value (present in 2 of the files) there is no way for any program to know the correct color space - assuming I've understood the PNG format - so it's a test for default behaviour.

16-bit linear color space
![test_16_linear_strip](https://user-images.githubusercontent.com/4918549/87080764-87bcd000-c228-11ea-9fc8-c824a7dfae5b.png)

16-bit linear color space with gAMA chunk (gamma information stored in PNG file)
![test_16_linear_gamma](https://user-images.githubusercontent.com/4918549/87081409-9d7ec500-c229-11ea-948c-41594766072b.png)

16-bit sRGB color space
![test_16_srgb_strip](https://user-images.githubusercontent.com/4918549/87080769-88556680-c228-11ea-9756-ae54a1d07dfc.png)

16-bit sRGB color space with gAMA chunk
![test_16_srgb_gamma_strip](https://user-images.githubusercontent.com/4918549/87080767-88556680-c228-11ea-942a-051e0c068caa.png)

In all programs I have except Godot the two sRGB images look correct, while the linear ones appears darker. GIMP handles all images except "linear without gamma" correctly, it appears too dark because it assumes it is sRGB data.

**Closed** 2020-07-09 21:26 UTC
Labels: bug, confirmed, topic:import, topic:rendering
