### ISSUE TITLE
Bug tô export APK html

### ISSUE THREAD

**Issue by jpplayerBR** [godotengine/godot#77811] opened 2023-06-03 16:59 UTC
### Godot version

4.0

### System information

Android

### Issue description

there is a bug in godot on mobile when i make a project in godot mobile when i export in apk or html the export option is out of scale and the bug has not been resolved i would like to solve this long bug so i can export my projects i hope that be resolved long and thank you

### Steps to reproduce

Export APK html without out of scale

### Minimal reproduction project

Simulator hand spinned in godot

**Comment by AThousandShips** [comment] 2023-06-03 17:02
> out of scale

What does this mean? Is it outside of the window? Then this is a duplicate of #73130

> the bug has not been resolved

Have you reported it? Has anyone? If it is not the bug above, why would it have been solved by itself?

**Comment by jpplayerBR** [comment] 2023-06-03 17:04
Em sáb., 3 de jun. de 2023 14:02, A Thousand Ships ***@***.***>
escreveu:

**Comment by AThousandShips** [comment] 2023-06-03 17:09
Did you mean to send an empty reply?

**Comment by Calinou** [comment] 2023-06-09 18:53
- Duplicate of https://github.com/godotengine/godot/issues/73130.

**Closed by Calinou** 2023-06-09 18:53 UTC
