### ISSUE TITLE
Node get processed when pausemode is stop

### ISSUE THREAD

**Issue by qian2501** [godotengine/godot#73767] opened 2023-02-22 15:58 UTC
### Godot version

3.5.1

### System information

WIndows 10, GLES3, Quadro P2000

### Issue description

Issue as title says, it's causing unexpected behaviour and crash.
I tried something like this in my project:
```
public void override _Process(float delta)
{
    GD.Print(PauseMode);
}
```
and it writes "Stop" in the console, which does not make sense.

I isolated this part of logic in the attachment.

### Steps to reproduce

just run

### Minimal reproduction project

[test.zip](https://github.com/godotengine/godot/files/10805775/test.zip)

**Comment by Yagich** [comment] 2023-02-22 16:29
You're not pausing the tree anywhere in the MRP. [See the doc page on pausing](https://docs.godotengine.org/en/stable/tutorials/scripting/pausing_games.html).

**Comment by qian2501** [comment] 2023-02-22 16:36
> You're not pausing the tree anywhere in the MRP. [See the doc page on pausing](https://docs.godotengine.org/en/stable/tutorials/scripting/pausing_games.html).

I know this page, it says 

> Stop the node no matter what

So you mean, it actually means “ Stop the node when paused”, Instead of “no matter what“?

**Comment by Yagich** [comment] 2023-02-22 16:39
Yes. The "no matter what" part refers to pause mode inheritance in this case.

**Comment by qian2501** [comment] 2023-02-22 16:44
Okay…I thought it provides a more flexible pause mechanism. I’ll stick with my implementation then.
Thanks for the clarification~

**Comment by Calinou** [comment] 2023-02-22 17:55
Closing as this is intended behavior in 3.x. The pausing system in 4.x is more flexible on this regard.

**Closed by Calinou** 2023-02-22 17:55 UTC

**Comment by Zireael07** [comment] 2023-02-22 19:24
Stop the node no matter what should probably be rewritten to make it clear that it needs to be paused in the first place.

Remember, many Godot users aren't native English speakers, heck, even the authors aren't.

**Comment by Calinou** [comment] 2023-02-22 20:33
> Stop the node no matter what should probably be rewritten to make it clear that it needs to be paused in the first place.
> 
> Remember, many Godot users aren't native English speakers, heck, even the authors aren't.

Done: https://github.com/godotengine/godot-docs/pull/6805
