### ISSUE TITLE
Engine freezes when typing a node path

### ISSUE THREAD

**Issue by serb2331** [godotengine/godot#80987] opened 2023-08-25 10:18 UTC
### Godot version

v4.1.stable.official [970459615]

### System information

Godot v4.1.stable - Windows 10.0.19045 - Vulkan (Compatibility) - NVIDIA GeForce RTX 3060 Laptop GPU (NVIDIA; 31.0.15.3623) - AMD Ryzen 7 6800H with Radeon Graphics (16 Threads)

### Issue description

When typing a node path in either the get_node() function or via "$", the engine freezes when the autocomplete hint is supposed to pop up. I have tested this and seen that this occurs when the scene tree contains a lot of nodes with lengthy names.

### Steps to reproduce

To reproduce the freeze, download the provided project which has 2 similar scenes("_broken_scene_" and "_normal_scene_") which contain either only **AspectRatioContainer** nodes or only **Control** nodes, then, by writing out a node path in the attached scripts, not copying a path directly, you will experience the freeze only in the _broken_scene_script_ and not in the _normal_scene_script_.

Example:
- Complete the provided lines of code like this:

```
@onready var node_path = get_node("AspectRatioContainer/AspectRatioContainer/AspectRatioContainer")
```
```
@onready var node_path = $Control/Control/Control/Control
```

### Minimal reproduction project

[EngineFreezeBugTest.zip](https://github.com/godotengine/godot/files/12437839/EngineFreezeBugTest.zip)

**Comment by KoBeWi** [comment] 2023-08-25 12:21
It's a duplicate of an issue that was fixed recently, but I can't find it right now.

**Comment by jsjtxietian** [comment] 2023-08-25 16:55
> It's a duplicate of an issue that was fixed recently, but I can't find it right now.

I guess this one ? https://github.com/godotengine/godot/issues/79894 But it is not fixed, and I can not reproduce the bug.

**Comment by KoBeWi** [comment] 2023-08-25 17:11
No it was another issue, but now I see it was unrelated.
Closing as duplicate of #79894 though.

**Closed by KoBeWi** 2023-08-25 17:11 UTC
