### ISSUE TITLE
Godot is unable to switch processes when Windows Terminal is the default console host

### ISSUE THREAD

**Issue by yiays** [godotengine/godot#54754] opened 2021-11-08 09:13 UTC
### Godot version

3.4

### System information

Windows 11 Insider Preview build 22489

### Issue description

Godot is unable to switch processes from the Project Manager to the Editor be it by creating a new project or loading an existing one as long as Windows Terminal is the console host rather than cmd.exe.
Launching Godot through Powershell in Windows Terminal works fine, however.
I'm not sure what the cause is, I don't see any sign of an error message, Godot just silently fails to open the editor and closes.
This bug may be important in the future as it's quite possible Windows Terminal will eventually completely replace cmd.exe. Though this might be an issue with Windows Terminal and not Godot.

### Steps to reproduce

Install Windows Terminal from the Microsoft Store, open Windows Terminal, open settings (Ctrl + ,), change the default terminal from Windows Console Host to Windows Terminal.

**Comment by akien-mga** [comment] 2021-11-08 09:17
Duplicate of #54076

**Closed by akien-mga** 2021-11-08 09:17 UTC
