### ISSUE TITLE
Simple geometric objects

### ISSUE THREAD

**Issue by seadra** [godotengine/godot#861] opened 2014-11-05 16:40 UTC
(from the [forum discussion](http://www.godotengine.org/forum/viewtopic.php?f=11&t=1059))

Unity and similar engines have simple objects such as plane/cube/cyclinder/sphere while godot currently lacks them.

Not only it is a huge convenience, but another one up-side is, one can make a 100% 3D godot tutorial similar to [this Unity tutorial](http://unity3d.com/learn/tutorials/projects/roll-a-ball).

**Comment by punto-** [comment] 2015-02-05 10:41
A tileset with all these shapes for the 3d gridmap would be nice for some fast prototyping too

**Comment by bojidar-bg** [comment] 2016-04-12 09:21
Isn't this similar to #1381 ?

**Comment by akien-mga** [comment] 2016-04-12 09:26
Indeed, closing as duplicate of #1381.

**Closed by akien-mga** 2016-04-12 09:26 UTC
Labels: feature proposal, topic:editor
