### ISSUE TITLE
Signals don't work in C#

### ISSUE THREAD

**Issue by isfardx** [godotengine/godot#68155] opened 2022-11-02 06:39 UTC
### Godot version

4.0 beta3

### System information

Windows11 RTX3060Laptop 516.94 Vulkan

### Issue description

While I try to connect signals to my C# scripts, The code just generate outside the whole class part. When I move it into the certain position and run the project, Godot will warn me that cannot find that method with signal.
 

### Steps to reproduce

Create an empty project in C#, and create a node with a c# script, then connect a signal to the script. And run the game.

then move the method with signal to right position, write something to trigger the signal and run the game to trigger the signal

**Comment by akien-mga** [comment] 2022-11-02 07:09
Duplicate of https://github.com/godotengine/godot/issues/18721.

> then move the method with signal to right position, write something to trigger the signal and run the game to trigger the signal

Please share that code, otherwise we can't know if it's a user error or if the signature is wrong.

**Comment by isfardx** [comment] 2022-11-03 02:06
![Snipaste_2022-11-03_10-05-13](https://user-images.githubusercontent.com/105959352/199635184-56c86551-d1ff-489f-8b48-b744cf543a9c.png)
I can;t upload the zip to github so i upload it to mediafire

**Comment by isfardx** [comment] 2022-11-03 02:08
https://www.mediafire.com/file/hyd7xqgw2gxdcwr/bugreport.zip/file heres the link

**Comment by Calinou** [comment] 2022-11-04 19:56
Closing per Akien's comment

**Comment by raulsntos** [comment] 2022-11-04 21:36
From the MRP it seems this is more of a duplicate of https://github.com/godotengine/godot/issues/67009

**Comment by RedworkDE** [comment] 2023-03-21 19:26
As far as I can tell there is no engine issue with the MRP:
1. The Vector components got renamed since
2. The callback has a non-marshallable argument of type `object`. Changing that to `Variant` fixes the project
3. This leaves the error message as kinda confusing but that is tracked in https://github.com/godotengine/godot/issues/35910

**Comment by Calinou** [comment] 2023-03-21 23:58
Closing in favor of https://github.com/godotengine/godot/issues/35910.

**Closed by Calinou** 2023-03-21 23:58 UTC
Labels: bug, needs testing, topic:dotnet
