### ISSUE TITLE
TabContainer creating Orphaned TabBar's for no reason

### ISSUE THREAD

**Issue by decryptedchaos** [godotengine/godot#93937] opened 2024-07-04 14:32 UTC
### Tested versions

Tested in: 4.3.beta2 and the current master..   

### System information

Godot v4.3.beta2 - Oynx 24.04 LTS 24.04 - X11 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1080 (nvidia; 535.183.01) - AMD Ryzen 5 1600X Six-Core Processor (12 Threads)

### Issue description

So,  What appears to be happening is that TabContainer is adding arbatrary TabBars to the tree,   i discovered this while creating a save system for my game because that is when it becomes most apparent as you will see  in the MRP  

However,  the issue is still there its just not noticeable even without saving if you switch to the Remote tab durring runtime you will see that it has added the extra TabBar called  @TabBar@2 already  so it's just sitting in the tree for no reason that i can see,  and then when you save the game.   it gets saved  with it  then you go to reload that save and it gets reloaded with it now the UI is broken because of it.. 

Just as interesting,  if you now save that already broken scene and then reload it again, you'll see the issue gets componded,  there are now duplicates of duplicates  and so on..  

### Steps to reproduce

Prepaired for you in the MRP  but it should be as simple as adding a basic UI with 

TabContainer - > TabBar -> HBox -> Buttons   etc 

### Minimal reproduction project (MRP)

[test.zip](https://github.com/user-attachments/files/16100287/test.zip)

Best i can do because of the filesize limit

**Comment by AThousandShips** [comment] 2024-07-04 14:32
Please remove the `.godot` folder and try again, if your MRP is still too big it's not really an MRP

**Comment by decryptedchaos** [comment] 2024-07-04 14:54
>Please remove the .godot folder and try again, if your MRP is still too big it's not really an MRP

the best i could do is compress it to  17MB  that's as small as i can get it the .godot folder wasa already gone..  

P.S  I find this complaint a little offensive to be honest,  the MRP is a courstsey to the volentiers and the devs to lighten the load, severe filesize limits are just another reason not to provide them, more over when a alternate download link is provided and still generates a complaint that is also further reason to reconsider providing them. because i'm spending my time to make it easier on the person whom reviews it, but if it gets appreicated like that  why should I. 

I don't know who you are,  for all i know you could be a great person and you seem to be a contributiter so there's that..  

But i find your statement to be a little rude.. as if i am incapable of comprehending what MRP means..  
The project had  one .gd file and one 2-3 assets used to test..  that constittues MRP by my definition, and i would think most resonable definitions..

**Comment by AThousandShips** [comment] 2024-07-04 14:57
> P.S I find this complaint a little offensive to be honest

I'm sorry that it comes across like that, but I made no implications of what you understood or not, I've rarely seen any issues which hit the limit *except* projects that are just someone's working project they uploaded directly (and the project includes 3D assets, which aren't really relevant to a UI project, so it's not very minimal IMO)

Please do not assume bad intent

**Comment by decryptedchaos** [comment] 2024-07-04 15:17
>Please do not assume bad intent, you are reading things into what I said that simply aren't there

Maybe you didn't have bad intent, that i can't say,  which is the inherent problem with the internet as a whole. 

But when describing something offensive, to one person,  it isn't about tangable proveable docterine,  its about their preception,  without it one would have no free will and things such as offense wouldn't exist anyway..  

Like i say,  you are probably a great person,  and i don't really want to exaserbate this into a debate it's too early for that,  but to say that they "simply arent there"  is a little passive,  because if i was offended and offense is preditcated on perceception then something i precieved was there..  it didn't matter if if was fact or not  it was how i precieved it. That is my only thing  

Like i say this doesn't matter  and i don't want to debate about it,  i've just had nothing but experiance with people being passive agressive to try to look like they are in the right all my life  so thats my default lense to begin with,  and i do get a little flustered about word choices sometimes. that may not be completely merrited in some cases.

**Comment by KoBeWi** [comment] 2024-07-04 15:51
I checked your project and your TabContainer has a TabBar child.
The other TabBar is internal to TabContainer. You don't need to add your own TabBar, as there is one already.

**Comment by decryptedchaos** [comment] 2024-07-04 15:56
> I checked your project and your TabContainer has a TabBar child. The other TabBar is internal to TabContainer. You don't need to add your own TabBar, as there is one already.

Okay, that seems a little counter intunitive,   but even if thats how its designed,   if you remove the TabBar and just have the HBox it still creates duplicate TabBars in the tree  i just tested to confirm in the test project

**Comment by KoBeWi** [comment] 2024-07-04 16:03
Looks like it's problem with `find_children()`. Most methods, like `get_children()`, have an argument for excluding internal nodes. But since you use find children method, it just returns everything and you are saving and re-adding the TabBar. TabContainer will always create a TabBar, so if it has extra, it appears as duplicate. You should exclude the TabBar from saving.

We could add `include_internal` argument to `find_children()`, but since that's not a bugfix, it should go to a proposal. Alternatively you can consider using a different method for saving, or leave the `owned` argument of `find_children()` as true (which solves the issue, but forces you to assign owners).

**Comment by AThousandShips** [comment] 2024-07-04 16:06
That's tracked in:
* https://github.com/godotengine/godot-proposals/issues/9561

**Comment by decryptedchaos** [comment] 2024-07-04 16:07
Interesting,  hmm,  the find_childrend() setup was done to make saving work in the fist place if i don't set all childrend to be owned by what would be C0 in the test project they don't get saved at all as if they aren't there   so  the solution was to use  find_children("*", "Node",true, false)   i couldn't find any other variant of true/false false/true or otherwise that would make it save the scene   is there another way that we've missed?   because that function took 3 days to troubleshoot with community help

**Comment by decryptedchaos** [comment] 2024-07-04 16:57
UPDATE:  I solved the problem by setting the owned argument to true for find_childrend()   and setting the owner for the instatantiated items at the time they spawn which took some troubleshooting,  its unclear why setting the owner at spawn or at save should be any different??   but never the less it works if i set the owner on the instances at spawn vs at save.  

I still think there should be some proposal / workaround to some of these problems as that was quite a detour to get to a solution that really should have been straightforward 

Thanks for the help as well

**Comment by KoBeWi** [comment] 2024-07-04 18:12
Looks like this is resolved, so closing.

**Closed by KoBeWi** 2024-07-04 18:12 UTC
Labels: bug, needs testing, topic:gui
