### ISSUE TITLE
Scrolling in output window not working as intended

### ISSUE THREAD

**Issue by SamDevelopsCode** [godotengine/godot#79975] opened 2023-07-28 02:02 UTC
### Godot version

v4.1.1- Stable

### System information

Godot v4.1.1.stable - Linux Mint 21.1 (Vera) - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3060 Laptop GPU () - Intel(R) Core(TM) i5-10500H CPU @ 2.50GHz (12 Threads)

### Issue description

When printing information to the Output window, the scrolling behavior does not work properly. Normally the output window should show the newest prints, meaning the scrollbar stays at the bottom automatically. This is not happening however. The scrollbar stays (or is forced) to the top of the output window. If I try to scroll down to the bottom, it will force the scrollbar back up, rendering seeing the newest prints very difficult.

![scrollbehavior](https://github.com/godotengine/godot/assets/122749374/a7db18c1-eccf-42af-85ef-1a1472f30c73)

### Steps to reproduce

Create new project. 
Add a basic node to scene.
Add a script to node.
Add the following code:
```
var number := 0

func _process(delta: float) -> void:
	number += 1
	print(number)
```
Save the scene and click play.
Watch Output window.

### Minimal reproduction project

N/A

**Comment by Sauermann** [comment] 2023-07-28 05:39
Looks like a duplicate of #78434

**Comment by SamDevelopsCode** [comment] 2023-07-28 16:01
> Looks like a duplicate of #78434

Ah I read that one before posting, I was thrown off by the richtextlabel aspect. Thanks for the update. What should I do with this bug report? Close it?

**Closed** 2023-07-28 16:07 UTC
Labels: bug, topic:editor, needs testing
