### ISSUE TITLE
Can not reorder autoload(global)

### ISSUE THREAD

**Issue by volzhs** [godotengine/godot#3110] opened 2015-12-21 14:58 UTC
so, I can't change the loading order of autoload(global). a1142225bf513e4afe0527ca604486d3988449cc

**Comment by kubecz3k** [comment] 2015-12-21 16:57
Can't confirm right now because of https://github.com/godotengine/godot/issues/3111 but if this is true then this should be definitely fixed for 2.0 release.

**Comment by volzhs** [comment] 2015-12-22 02:41
It's my bad. I found it. :(.

**Comment by kubecz3k** [comment] 2015-12-22 11:23
The issue is real. I'm able to confirm it in 1bc91848e3cee91eccaf2150a74deaf1cd84be13 commit:
![autoload_order_brooken](https://cloud.githubusercontent.com/assets/6129594/11954163/a313c052-a8a6-11e5-9520-1ba9582d9a15.gif)

**Comment by volzhs** [comment] 2015-12-22 13:09
Oh. I just saw the UI, not tried to reorder. my bad again :(

**Comment by akien-mga** [comment] 2015-12-28 21:23
Likely fixed by 496cb49.

**Closed by akien-mga** 2015-12-28 21:23 UTC
Labels: bug, confirmed, topic:editor
