### ISSUE TITLE
KinematicBody2D collision pairs count error

### ISSUE THREAD

**Issue by miblooming** [godotengine/godot#30681] opened 2019-07-18 15:21 UTC
**Godot version:**

3.1.1

**OS/device including version:**

Microsoft Windows 10.0.17134.885
Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
8.0 GB 2133 MHz
NVIDIA GeForce MX150

**Issue description:**

Two kinematicBody2D nodes with mask none, should have no collision pair.
![KinematicBody2D_bug](https://user-images.githubusercontent.com/2108904/61469799-73961800-a9b2-11e9-8ed1-27f2340d328f.png)

**Steps to reproduce:**

**Minimal reproduction project:**

[KinematicBody2D_bug.zip](https://github.com/godotengine/godot/files/3407207/KinematicBody2D_bug.zip)

**Comment by groud** [comment] 2019-07-18 17:18
Duplicate of #28460

**Closed by groud** 2019-07-18 17:18 UTC
Labels: bug, topic:physics
