### ISSUE TITLE
Certain text fields are now entering text input backwards.

### ISSUE THREAD

**Issue by avencherus** [godotengine/godot#44854] opened 2021-01-01 15:35 UTC
**Godot version:**

adfc646f8cb497d520ea2238482ab674fe90d43a

**OS/device including version:**

Win10 64-bit

**Issue description:**

Did a rebase and rebuild today, and have noticed when setting up an OptionButton the text inputs are going in reverse.  The item list editor was also affected on this field.

Appears to be a recent regression, works fine in 3.2.4-beta4.

![godot windows tools 64_EsugZnSq85](https://user-images.githubusercontent.com/13004169/103441248-421c1580-4c55-11eb-9b9a-8d4aae4f6afb.png)

![godot windows tools 64_EOmrRpGzvQ](https://user-images.githubusercontent.com/13004169/103441247-40525200-4c55-11eb-9b79-65926d950cff.png)

Label text field appears fine.
![godot windows tools 64_Mac8R0G23b](https://user-images.githubusercontent.com/13004169/103441250-434d4280-4c55-11eb-9416-1f31e9fb49ca.png)

**Steps to reproduce:**
Enter text into these fields of these controls.

**Minimal reproduction project:**

[Option Button Issue.zip](https://github.com/godotengine/godot/files/5759091/Option.Button.Issue.zip)

**Comment by akien-mga** [comment] 2021-01-01 15:46
Likely a regression from cherry-picking #44326 (with 9a3cd08122cbf8a2071812efa73981cdc720f825), CC @AndreaCatania.

**Comment by Xrayez** [comment] 2021-01-02 23:40
Stumbled upon this today as well, but also wanted to say that it does fix #43238, but of course the editor inspector becomes unusable due to this, so if #44326 gets reverted, then #43238 should be re-opened.

**Comment by AndreaCatania** [comment] 2021-01-02 23:53
By the way, not all fields are affected. Maybe some event reset the cursor position, on the input line used on the inspector?

**Comment by Xrayez** [comment] 2021-01-03 00:01
This issue is quite similar to #42488, so yeah it may be possible to hit two birds with one stone. 🙂

Perhaps updating the property editor deferred is all which is needed to solve *this* issue at least?

**Comment by akien-mga** [comment] 2021-01-05 12:36
I reverted the `3.2` cherry-pick, but the PR is still merged in `master`, where this issue is also reproducible.

I confirm that it seems to affect `LineEdit` and not `TextEdit` (CC @Paulb23 @bruvzg).

**Comment by pouleyKetchoupp** [comment] 2021-01-06 04:08
I've opened #44954 to fix this issue and #42488. I don't know if it's the best option to fix it, but I didn't find a more elegant way :)

**Closed** 2021-01-07 09:33 UTC
Labels: bug, regression, topic:editor
