### ISSUE TITLE
"Page" option in Inspector in debug cannot open remote 2nd-level dictionary

### ISSUE THREAD

**Issue by BevanFindlay** [godotengine/godot#47143] opened 2021-03-18 21:32 UTC
I've been using some fairly large arrays/dictionaries (often nested) but having issues with accessing them in the debugger.

**Godot version:**
3.2.3

**OS/device including version:**
Windows 10 20H2

**Issue description:**
If an array of dictionaries (and I think also a dictionary with nested dictionary), I cannot get to the second page of the second-level dictionary.  Clicking the page number arrows goes from 0 to 1 for less than a second before it flicks back to 0.

I also sometimes have trouble opening 2nd-level Dictionaries, where clicking on an entry in the Inspector doesn't seem to register the click, or delays a lot before registering (usually resulting in me clicking again to try to get it to work and having it flick open then closed again), but haven't been able to nail this down to something I can reliably recreate.

May be related to https://github.com/godotengine/godot/issues/25375 ?

**Steps to reproduce:**
Create an array of dictionaries, with both at least 10 items in size (i.e. >9 so it requires changing Page to get to some of the data).
Run the project, with a breakpoint somewhere after the creation of this.
Get to Remote viewing of the data in the Inspector.
Click the array to open it.
Click one of the nested dictionaries.
Attempt to change the Page of that second-level dictionary.

**Minimal reproduction project:**
Attached.  Set a breakpoint on the "print" statement.

**Comment by BevanFindlay** [comment] 2021-03-18 21:33
[Array Test.zip](https://github.com/godotengine/godot/files/6167338/Array.Test.zip)

**Comment by pycbouh** [comment] 2021-03-18 22:36
Yes, it's a duplicate of #25375, as the cause is the same.

**Closed by pycbouh** 2021-03-18 22:36 UTC
