### ISSUE TITLE
GDScript permits constants to be reassigned

### ISSUE THREAD

**Issue by wlycdgrfromflatiron** [godotengine/godot#20179] opened 2018-07-15 19:44 UTC
Env:
Godot Engine v.3.0.5.stable.official.6a88e22, downloaded from Godot website
Windows 10 Pro Version 1803 OS Build 17134.165

Issue:
I assigned another value to a constant after initialization, expecting the compiler to complain. But it worked: 

```
# Save this as a script and attach to any node in a scene

extends Node

const A = 0

func _ready(): 
	print(A) # prints 0 as expected
	
	A = 1 # Godot does not object, as expected, that a constant is being assigned a new value
	
	print (A) # prints 1
	
func _process(delta):
	print(A) # still prints 1
```

If this is expected behavior, the documentation at http://docs.godotengine.org/en/3.0/getting_started/scripting/gdscript/gdscript_basics.html#classes-as-resources should make this clear, since it's at odds with the intuitive interpretation of 'constant'.

**Comment by vnen** [comment] 2018-07-15 21:56
Duplicate of #6221

**Closed by vnen** 2018-07-15 21:56 UTC

**Comment by wlycdgrfromflatiron** [comment] 2018-07-15 22:36
My bad. I searched the issue history but not seeing anything from this year figured it hadn't been reported as figured it would have been addressed. Thank you.
