### ISSUE TITLE
Application crashes (without any error) if node connected to PinJoint2D is being destroyed

### ISSUE THREAD

**Issue by Footurist** [godotengine/godot#16730] opened 2018-02-15 23:32 UTC
Just spent a while figuring out this was the reason my application crashed. If this is intended and can't be changed, I'll keep my mouth shut. Otherwise, would it be possible to implement PinJoint2Ds recognizing what's going on and just cutting the connection?

**Comment by hpvb** [comment] 2018-02-15 23:45
Could you perhaps provide us with a minimal example of this crash? We can probably fix it but with a little more information this would be a lot easier and faster for us to do.

**Comment by Footurist** [comment] 2018-02-16 00:58
Sure:

```
# set up the joint connection
var rigid1 = RigidBody2D.new()
rigid1.name = "Rigid1"
add_child(rigid1)
var rigid2 = RigidBody2D.new()
rigid2.name = "Rigid2"
add_child(rigid2)
var joint = PinJoint2D.new()
var joint.name = "Joint"
$Rigid1.add_child(joint)
$Rigid1/Joint.node_a = ".."
$Rigid1/Joint.node_b = "../../Rigid2"
```

```
# cause the error
$Rigid2.queue_free()
```

This will crash.

**Comment by reduz** [comment] 2018-09-06 19:56
This code is here: 
https://github.com/godotengine/godot/blob/master/scene/2d/physics_body_2d.cpp
and
https://github.com/godotengine/godot/blob/master/scene/2d/joints_2d.cpp

something fishy must be going on, and bug may exist in 3D too?

**Comment by DualMatrix** [comment] 2018-09-08 22:48
I can't reproduce with the above script as of 4b6846a

**Comment by akien-mga** [comment] 2018-09-10 17:02
Assuming fixed in the current master branch.

If you can still reproduce it, please comment and attach a project that triggers the bug.

**Closed by akien-mga** 2018-09-10 17:02 UTC
Labels: bug, hero wanted!, topic:core
