### ISSUE TITLE
TypeError: can only concatenate deque (not "list") to deque

### ISSUE THREAD

**Issue by HK-SHAO** [godotengine/godot#75307] opened 2023-03-25 07:05 UTC
### Godot version

0291fcd7b66bcb315a49c44de8031e5596de4216

### System information

Windows 11, Intel 13900H, Godot Engine v4.1.dev.custom_build.0291fcd7b - https://godotengine.org OpenGL API 3.3.0 NVIDIA 531.41 - Compatibility - Using Device: NVIDIA Corporation - NVIDIA GeForce RTX 4070 LaU

### Issue description

When I generate a Visual Studio solution from the source code, a python 3.10.10 error occurs.

### Steps to reproduce

When running the command  from [godot docs](https://docs.godotengine.org/en/latest/contributing/development/configuring_an_ide/visual_studio.html#doc-configuring-an-ide-vs)
```bash
scons platform=windows vsproj=yes
```
to generate the Visual Studio solution, Python 3.10 reports an error:

```shell
scons: Reading SConscript files ...
Auto-detected 20 CPU cores available for build parallelism. Using 19 cores by default. You can override it with the -j argument.
Found MSVC version 14.3, arch x86_64
Building for platform "windows", architecture "x86_64", target "editor".
TypeError: can only concatenate deque (not "list") to deque:
  File "C:\MYD\GitClone\godot\SConstruct", line 927:
    methods.generate_vs_project(env, GetOption("num_jobs"), env["vsproj_name"])
  File "C:\MYD\GitClone\godot\methods.py", line 859:
    module_configs = ModuleConfigs()
  File "C:\MYD\GitClone\godot\methods.py", line 763:
    self.add_mode()  # default
  File "C:\MYD\GitClone\godot\methods.py", line 786:
    self.arg_dict["cppdefines"] += ModuleConfigs.for_every_variant(env["CPPDEFINES"] + defines)
```

### Minimal reproduction project

When I generate a Visual Studio solution from the source code, an error occurs and there is no Godot project.

**Comment by RedworkDE** [comment] 2023-03-25 10:53
Duplicate of https://github.com/godotengine/godot/issues/74725

**Comment by YuriSizov** [comment] 2023-03-25 12:28
Thanks, closing as a duplicate.

**Closed by YuriSizov** 2023-03-25 12:28 UTC
