### ISSUE TITLE
shadow behaves like reflection

### ISSUE THREAD

**Issue by curly-brace** [godotengine/godot#8555] opened 2017-04-27 07:10 UTC
previously i've noticed strange shadows and investigation lead to skybox render issue https://github.com/godotengine/godot/issues/8050

but now i've returned to godot and looked at a big shadow and saw there a reflection of a skybox!
![](https://images-ext-2.discordapp.net/eyJ1cmwiOiJodHRwczovL2FwaS5tb25vc25hcC5jb20vcnBjL2ZpbGUvZG93bmxvYWQ_aWQ9NTJidU5TUkJuV3FPNkttWTN4bzFGSUFnc041SGkzIn0.j2LrLAe1Ilyr4sIVlk9sncRonTA?width=813&height=603)
this is just a default diffuse material. there is nothing special except added skybox (and directional light with enabled shadows)
actually now i think that all that defected shading is caused by skybox being reflected. and skybox itself has that defected gradients (issue above)

**Comment by Calinou** [comment] 2017-04-29 18:21
I can confirm this, metallic/specular materials (rough or less rough) tend to be very reflective in dark areas.

**Comment by bojidar-bg** [comment] 2017-09-11 14:18
Is this still the case on the current master branch?

**Comment by reduz** [comment] 2017-09-11 14:45
This should no longer be the case since the switch to Metallic model.

**Comment by Calinou** [comment] 2017-10-30 11:11
Can anyone still reproduce this with the current `master` branch? If not, I'll close this.

**Comment by kubecz3k** [comment] 2018-04-19 19:18
According to reduz comment this should be fixed now, plus also I never noticed this in 3.0 stable. If someone still encounter this bug please open new issue or leave a comment in this one.

**Closed by kubecz3k** 2018-04-19 19:18 UTC
Labels: discussion, topic:rendering
