### ISSUE TITLE
Problem opening a project 3.2 beta 2 mono

### ISSUE THREAD

**Issue by Torguen** [godotengine/godot#33846] opened 2019-11-23 20:36 UTC
**Godot version:**
3.2 beta 2 mono

**OS/device including version:**
win10 64 home

**Issue description:**
Problem opening any project
The editor closes automatically when you try to open a project.

![1](https://user-images.githubusercontent.com/19652075/69484947-3e567680-0e39-11ea-9ff1-4e6d4cc2300d.png)

I have the 6.6.0 version of mono installed and the last build tools version: https://visualstudio.microsoft.com/es/thank-you-downloading-visual-studio/?sku=BuildTools&rel=16

**Steps to reproduce:**
Open some 3.2 beta 1 project

**Minimal reproduction project:**

**Comment by akien-mga** [comment] 2019-11-23 22:29
Duplicate of #33822

**Closed by akien-mga** 2019-11-23 22:29 UTC
