### ISSUE TITLE
C# -- Setting any value to Node3D.GlobalRotation also resets Scale to (1,1,1)

### ISSUE THREAD

**Issue by architeer** [godotengine/godot#83668] opened 2023-10-20 11:12 UTC
### Godot version

v4.2.beta1.mono.official [b1371806a]

### System information

Godot v4.2.beta1.mono - Windows 10.0.19045 - GLES3 (Compatibility) - Quadro 2000M () - Intel(R) Core(TM) i7-2860QM CPU @ 2.50GHz (8 Threads)

### Issue description

In C#, for Node3D, setting any new value to a node3D.GlobalRotation or node3D.GlobalRotationDegrees will also reset the node's scale to (1,1,1)

Both the node3D.Rotation and node3D.RotationDegrees works fine

### Steps to reproduce

1. Add a new Node3D to scene
2. Give the new Node3D a scale of (3,3,3)
3. Create C# script
4. In the C# script, in _Ready(), for the newly added node, assign any value to node3D.GlobalRotation
5. Run the project
6. After assigning the new value to the 'GlobalRotation', it automatically resets the node's scale to (1,1,1)
7. Assigning any new value to node3D.GlobalRotationDegrees also resets the scale to (1,1,1)

### Minimal reproduction project

N/A

**Comment by AThousandShips** [comment] 2023-10-20 11:14
Duplicate of #74162

**Closed** 2023-10-20 11:15 UTC
Labels: archived
