### ISSUE TITLE
Cannot use Tween after using a Timer

### ISSUE THREAD

**Issue by cO2unsmart** [godotengine/godot#75557] opened 2023-04-01 09:25 UTC
### Godot version

4.0.1 stable

### System information

Windows 10

### Issue description

It's not moving

### Steps to reproduce

```gdscript
@onready var tween = get_tree().create_tween()

func ready():
    await get_tree().create_timer(1).timeout
    tween.tween_property($Sprite2D, "position", Vector2(0,0), 1)
```

### Minimal reproduction project

N/A

**Comment by KoBeWi** [comment] 2023-04-01 12:23
You should be getting errors that the Tween is invalid.
Create the Tween when you want to tween a property, not *some time* before that.

**Comment by Efra-EMX** [comment] 2023-04-01 13:57
As far as my understanding goes, you need to call create_tween() and tween_property() on the same thread. So in this case, you have to call create_tween() in the _ready() function like this
```gdscript
var tween

func ready():
	tween = create_tween()
	tween.tween_property($Sprite2D, "position", Vector2(0,0), 1)
``` 
Correct me if I'm wrong. Currently I have no time to test it out

**Comment by Calinou** [comment] 2023-04-01 17:00
PS: Code blocks should use triple backticks like this (with an optional language name for syntax highlighting):

\`\`\`gdscript
code here
\`\`\`

I edited your post accordingly, but remember to do this in the future :slightly_smiling_face:

**Comment by timothyqiu** [comment] 2023-04-02 15:25
I think the main problem is that your function is named `ready` instead of `_ready`. So it's never called :P

The secondary problem is explained above: Tweens are not supposed to be used like this. To delay a tween, you can add a `tween_interval()` tweener, or call `set_delay()` on the tweener.

**Comment by YuriSizov** [comment] 2023-04-03 13:28
Closing the report because the issue is in the user code as mentioned above. Please see the recommendations about the Tween usage in the preceding discussion.

**Closed by YuriSizov** 2023-04-03 13:28 UTC
Labels: needs testing, topic:animation
