### ISSUE TITLE
Editor does not support double precision on GDScript exported var

### ISSUE THREAD

**Issue by Skyfish1** [godotengine/godot#24693] opened 2019-01-01 14:16 UTC
**Godot version:**
3.0.6-stable

**OS/device including version:**
Windows 10

**Issue description:**
Background:
As I understand Godot 3 now supports double precision floats which is what I need. I need very large numbers for a 1,000,000,000,000,000,000 km to 1 m scale simulation. I need these numbers as drawing coordinates (with camera scale applied), in Vector math etc.
Issue:
When I try to export a float for use in Godot Editor

`export(float) var Radius = 1.0 setget set_radius`
`func set_radius(radius): Radius = radius`

and enter a large number for example: 7 500 000 000 km the editor clips this value to 16 777 216.

![image](https://user-images.githubusercontent.com/25827515/50573555-4ac38200-0dd6-11e9-9203-cafee16f4a10.png)

**Steps to reproduce:**
Just make node with GDScript with the export line above. Try to enter large number in exported field.

**Minimal reproduction project:**
See above (just one line of code)

**Comment by akien-mga** [comment] 2019-01-01 15:30
Godot 3 does not support doubles yet. Duplicate of #288.

**Closed by akien-mga** 2019-01-01 15:30 UTC

**Comment by Skyfish1** [comment] 2019-01-02 11:49
Ok. thx. I thought it would because i tested it in code with my version 3.0.6. I can assign a 

`var z = 7500000000.0
`
and do some Math: 

```
	var r = 7500000000.0
	print(r / 2.0)
	var v = Vector2(r,r)
	print(a.rotated(sqrt(3)))
```
which also prints large numbers (just with some precision issues):
```
3750000000
(-7499999232, -7500001280)
```
The only thing not accepting big numbers was the Editor which should not get forgotten :)

**Comment by aaronfranke** [comment] 2019-01-27 11:41
Support for double-precision floats probably won't happen any earlier than 2020. But I assure you, it is being worked on (myself + maybe fire + maybe reduz).

**Comment by Skyfish1** [comment] 2019-01-28 08:46
Thanks for the information. I think you are right even double would not be enough to scientifically simulate the universe with enough precision. Fortunately my game is not a scientific universe simulation more a 2d space exploration and economy simulation and does not need to be physically correct on this scale. My problem was that I have a map where you can zoom out from your space ship all the way to the whole galaxy to give you a sense of scale. My current approach is to use 3 cameras in 3 layered map zoom levels (Galaxy/Starsystem/Local) which is also more resource-friendly as I only have to populate the visible objects in each map. But its more work on the programming side. I have to align the maps to mousecursor und switch between them at correct zoom levels while ease/lerp animating the zoom. It took me a while to get this working. It still has some issues.
