### ISSUE TITLE
Internal script error! Opcode: 0

### ISSUE THREAD

**Issue by octglam** [godotengine/godot#75550] opened 2023-04-01 04:16 UTC
### Godot version

4.0.1.stable

### System information

Windows 11, GLES3, AMD Ryzen 5000 SERIES, AMD Radeon Graphics

### Issue description

Creating and testing a Gui project with Godot Engine, suddenly 'Internal script error! Opcode: 0 (please report).' There was an error. I reported it, but I don't know why it happened.

![오류](https://user-images.githubusercontent.com/72848677/229265068-d661b6ad-c08e-4e2a-8481-6163f9ca3fda.png)

### Steps to reproduce

This code is applicable code.

```gdscript
class_name Game
extends Resource

enum GameType {
	RUNNABLE, GAMEBOY
}

@export var game_file: String
@export var game_type: GameType

```

### Minimal reproduction project

N/A

**Comment by clemens-tolboom** [comment] 2023-05-31 15:05
**v4.0.3.stable.official [5222a99f5]**

I get the error `Internal script error! Opcode: 0 (please report).` when running the game then edit the active scene file and save.

```
GDScript: Reloading all scripts
GDScript: Found: res://src/utils.gd
GDScript: Found: res://colored_cell.gd
GDScript: Found: res://grid.gd                       <== I changed this script and saved it
GDScript: Found: res://autoload/log4gd.gd
GDScript: Reloading: res://src/utils.gd
GDScript: Reloading: res://colored_cell.gd
GDScript: Reloading: res://grid.gd
GDScript: Reloading: res://autoload/log4gd.gd
  editor/debugger/debug_adapter/debug_adapter_types.h:70 - Condition "path.is_empty()" is true.
EditorSettings: Save OK!
```

My game has a Dictionary with Callables.

```
var actions:Dictionary  = {
	'reset': func(): reset_cells(),
	'select-player' : func(): select_player(), 
	'mark-player' : func(): mark_player(),
	'mark-targets' : func(): mark_targets(),
	'mark-target' : func(): select_target(),
	'throw-dice': func(): roll_dice()
}
```

and I changed the `func select_player():` code saved it and then activate `actions['select-player'].call()`by pressing a button.

```
E 0:00:36:0622   grid.gd:179 @ (): Condition ' (ip + 5) > _code_size ' is true. Breaking..:
  <C++ Source>   modules/gdscript/gdscript_vm.cpp:697 @ call()
  <Stack Trace>  grid.gd:179 @ ()
                 grid.gd:188 @ do_action()
                 grid.gd:206 @ do_player()
                 grid.gd:221 @ _on_player_button_up()
```

![image](https://github.com/godotengine/godot/assets/371014/9750f266-0cad-4d9b-b612-276c75d2172e)

@octglam what is your stack trace `<C++ Source>`?

**Comment by florton** [comment] 2023-06-12 03:27
Internal script error! Opcode: 0 (please report)

```
E 0:01:36:0838   main.gd:21 @ _process(): Condition ' (ip + 5) > _code_size ' is true. Breaking..:
  <C++ Source>   modules/gdscript/gdscript_vm.cpp:697 @ call()
  <Stack Trace>  main.gd:21 @ _process()
```

**Comment by dalexeev** [comment] 2023-06-15 08:01
> and I changed the `func select_player():` code saved it and then activate `actions['select-player'].call()`by pressing a button.

I understand correctly that you edited the script while the project was running? Or the error occurred without any actions with the code? Hot reload is buggy in 4.0, this is a known issue. See #72825.

**Comment by clemens-tolboom** [comment] 2023-06-15 19:12
It was a hot reload/script edit while running ... I do that a lot but thought my anonymous functions caused it.

Issue https://github.com/godotengine/godot/issues/72825 is only mentioning **external editor** ... this issue seems all to have **internal editor**.

**Comment by dalexeev** [comment] 2023-10-11 15:18
* See also #62769.

> Creating and testing a Gui project with Godot Engine, suddenly 'Internal script error! Opcode: 0 (please report).' There was an error. I reported it, but I don't know why it happened.

Since there is no detailed information, it is impossible to identify the source of the bug. So let's close this in favor of other issues. Please write here or open a new issue if you find additional information.

> It was a hot reload/script edit while running ... I do that a lot but thought my anonymous functions caused it.

I'm pretty sure this is a duplicate of the lambda hot reloading bug that has been reported several times. This can cause any effect depending on the offset. Also please check #81628, which should fix the bug.

**Closed by dalexeev** 2023-10-11 15:18 UTC
Labels: bug, topic:gdscript
