### ISSUE TITLE
Some blurry text in Editor Help

### ISSUE THREAD

**Issue by MewPurPur** [godotengine/godot#82966] opened 2023-10-07 14:07 UTC
### Godot version

Godot v4.2.dev6 - Pop!_OS 22.04 LTS - X11 - Vulkan (Forward+) - integrated Intel(R) Graphics (ADL GT2) () - 12th Gen Intel(R) Core(TM) i5-1235U (12 Threads)

### System information

Godot v4.2.dev6 - Pop!_OS 22.04 LTS - X11 - Vulkan (Forward+) - integrated Intel(R) Graphics (ADL GT2) () - 12th Gen Intel(R) Core(TM) i5-1235U (12 Threads)

### Issue description

![image](https://github.com/godotengine/godot/assets/85438892/a1da947b-3c6d-4ea4-a7e1-97118a48338f)

The text here is blurry.

### Steps to reproduce

I noticed this in ProjectSettings' documentation

### Minimal reproduction project

N/A

**Comment by Calinou** [comment] 2023-10-07 14:19
cc @bruvzg

**Comment by k0T0z** [comment] 2023-10-07 15:04
@MewPurPur I can't reproduce it! This (part)[https://docs.godotengine.org/en/stable/classes/class_projectsettings.html#class-projectsettings-property-display-window-size-viewport-height] u mean. Can you provide more details?

**Comment by MewPurPur** [comment] 2023-10-07 15:39
@k0T0z We are in the Godot repository, so this is about the built-in documentation, to be sure. It's probably somehow related to my system; I can reproduce this in all my projects, so it's not related to project settings.

**Comment by k0T0z** [comment] 2023-10-07 16:09
@MewPurPur I see now. I am a new contributor here so didn't know about that built-in documentation.

**Comment by Calinou** [comment] 2023-12-26 15:11
I can't reproduce this on 4.3.dev 13a0d6e9b (Linux, 100% editor scale and default font size settings).

Can you reproduce this if you change the **Font Hinting** editor setting to **Normal**? Also try setting **Font Antialiasing** to **None** and see if the issue persists.

Also, does the issue always occur on this given description, or does it depend on *how* you access the setting description (i.e. by searching for the ProjectSettings class then manually scrolling down, as opposed to searching for `viewport_height` directly).

**Comment by MewPurPur** [comment] 2023-12-26 19:35
I cannot reproduce it in 4.2 anymore in any way. I haven't changed the two settings you mentioned, the issue was probably fixed separately. I remember I also had issues with carets being blurry in a similar way, but not anymore.

**Comment by Calinou** [comment] 2024-01-01 18:26
Closing per the above comment.

**Closed by Calinou** 2024-01-01 18:26 UTC
Labels: bug, topic:editor, needs testing, topic:gui
