### ISSUE TITLE
Vulkan Driver doesn't work  windows 11 nvidia 1650

### ISSUE THREAD

**Issue by abderman** [godotengine/godot#74276] opened 2023-03-03 07:44 UTC
### Godot version

4.0 stable

### System information

Windows 11

### Issue description

on my laptop
Assus TUF ganing fx 505 dt
nvidia 1650 GTX 8gb 
![Clipboard06](https://user-images.githubusercontent.com/5955262/222660687-78bd78f5-8062-43ed-8fd4-2b31f26b5bbe.jpg)
driver 531.18
 can play Valheim using Vulkan but cant use Godot 4.0 forward+
![Clipboard04](https://user-images.githubusercontent.com/5955262/222660673-21cbfff5-683e-41d5-a271-b3c010019463.jpg)
![Clipboard05](https://user-images.githubusercontent.com/5955262/222660679-1d0bf47b-ca84-4569-93f0-69a69a5e4434.jpg)

### Steps to reproduce

run godot 4.0 on  laptop asus tuf gaming nvidia gtx, create project forward+ 
![Clipboard01](https://user-images.githubusercontent.com/5955262/222660656-3831cafe-b4cc-461d-bd63-31bd2c26e9bd.jpg)
![Clipboard02](https://user-images.githubusercontent.com/5955262/222660664-84122f5f-bbbe-448c-850c-e0244bf280e5.jpg)
![Clipboard03](https://user-images.githubusercontent.com/5955262/222660670-529c6837-dd9e-4593-86f0-9c2db0cdb5f6.jpg)

### Minimal reproduction project

; Engine configuration file.
; It's best edited using the editor UI and not directly,
; since the parameters that go here are not all obvious.
;
; Format:
;   [section] ; section goes between []
;   param=value ; assign values to parameters

config_version=5

[application]

config/name="tstvulkan"
config/features=PackedStringArray("4.0", "Forward Plus")
config/icon="res://icon.svg"

[rendering]

renderer/rendering_method="forward_plus"

**Comment by saierXP** [comment] 2023-03-03 07:58
If you have AMD integrated + NVIDIA dedicated GPU
Related to #73450.

**Comment by Calinou** [comment] 2023-03-03 08:56
- Duplicate of https://github.com/godotengine/godot/issues/57708 (this laptop model has an AMD CPU).

Try updating your AMD graphics drivers (which are used by integrated graphics).

**Closed by Calinou** 2023-03-03 08:56 UTC
