### ISSUE TITLE
Shader uniform vec4 array does not accept C# Vector4 array when setting

### ISSUE THREAD

**Issue by BirdmanTunes** [godotengine/godot#83106] opened 2023-10-10 13:47 UTC
### Godot version

v4.1.2.stable.mono.official [399c9dc39]

### System information

Windows 10 Enterprise LTSC

### Issue description

I'm reopening issue https://github.com/godotengine/godot/issues/75033# since this is still not fixed.

### Steps to reproduce

Just make a Vector4 array and try to set it to a vec4 array in the shader.

`
var blocks = new Vector4[1] {new Vector4(0, 0, 0, 0) };
((ShaderMaterial)Material).SetShaderParameter("test_array", blocks);`

And in the shader:

```uniform vec4 test_array[4096];```

Error in IDE saying "Godot.Vector4[] is not assignable to Godot.Variant"

### Minimal reproduction project

[Issue75033.zip](https://github.com/godotengine/godot/files/12857926/Issue75033.zip)

**Comment by AThousandShips** [comment] 2023-10-10 13:52
Is this specific to C#? If not please provide a GDScript MRP

**Comment by AThousandShips** [comment] 2023-10-10 14:00
This is not the same bug as #75033 as it's not a global shader parameter, and it's passing an array not a single value

**Comment by AThousandShips** [comment] 2023-10-10 14:13
The issue here is that you can't pass an array of this type to Godot, there's no equivalent, you need to be able to store it in a Variant

You can instead use `Color[]`

**Comment by bitsawer** [comment] 2023-10-10 14:32
Looks like there is some confusion between issues here, as AThousandShips already noted. https://github.com/godotengine/godot/issues/75033 was fixed and seem to still be fixed, both for GDScript and C#. Also, that issue was about global shader uniform, this issue is about normal shader uniform arrays. So the issues are different and title is somewhat incorrect.

In the MRP you are trying to use a native C# array of Vector4's. C# doesn't seem to be able to cast it into a Variant. This might be by design, try to use `Godot.Collections.Array<T>`, where T should probably be Vector4 and see if that works. Alternatively, you could try `Color[]` or a flattened `float[]` as AThousandShips suggested.

Vector4 is a bit of a special case as it doesn't have a PackedVector4Array of its own (unlike for example Vector2, Vector3 or Color), so there is no [C# array auto-conversion](https://docs.godotengine.org/en/stable/tutorials/scripting/c_sharp/c_sharp_collections.html#packedarray) for that one.

See also https://docs.godotengine.org/en/stable/tutorials/scripting/c_sharp/c_sharp_collections.html

> Does your collection need to interact with the Godot engine? (e.g.: the type of an exported property, calling a Godot method).
>         If yes, since Godot only supports Variant-compatible types, use a Godot collection.
>         If not, consider choosing an appropriate .NET collection.

I don't think this is a bug, just a limitation (that has been documented). Adding a PackedVector4Array type to Godot would probably also fix this case with C# native Vector4 arrays.

**Comment by BirdmanTunes** [comment] 2023-10-10 14:44
Alright, it seems i have misunderstood the difference between uniform and global parameter, in my case it's a uniform parameter.

As far as the issue, it seems that Color is indeed the right array to pass to a vec4 shader array(though this is quite confusing and should probably be changed or addressed? since for vec2 or vec3, you pass a Vector2, and Vector3 accordingly) 

Though here is an updated project for the gdscript version as well.

If Color is really the right array for vec4 then this should be closed.

[Issue75033_2.zip](https://github.com/godotengine/godot/files/12858550/Issue75033_2.zip)

**Comment by AThousandShips** [comment] 2023-10-10 14:47
As explained above it's because there's no `PackedVector4Array`

**Comment by bitsawer** [comment] 2023-10-11 10:29
Looks like we reached a satisfactory conclusion here, so I'm closing this issue. As mentioned, this is documented limitation and can be worked around easily by using Godot container classes like `Godot.Collections.Array<T>` or other types like PackedColorArray. You can actually see what types are valid for each uniform type in https://docs.godotengine.org/en/latest/tutorials/shaders/shader_reference/shading_language.html#uniforms. `vec4` accepts `Vector4, Color, Rect2, Plane, Quaternion`. Color is often used in Godot instead of Vector4 because of historical reasons (Vector4 was added much later, only last year) and because Color always uses 32-bit floats (Godot can be built to use 64-bit doubles, in which case Vector4 will also use doubles instead of floats).

Also, there is a proposal for adding `PackedVector4Array`: https://github.com/godotengine/godot-proposals/issues/6129 which would fix this specific issue.

**Closed by bitsawer** 2023-10-11 10:29 UTC
Labels: bug, needs testing, topic:dotnet, topic:shaders
