### ISSUE TITLE
@ character is dropped when setting the `name` property of Nodes

### ISSUE THREAD

**Issue by dilettante54** [godotengine/godot#47392] opened 2021-03-26 14:52 UTC
**Godot version:**
3.2.3

**OS/device including version:**
Windows 10

**Issue description:**
If you add a new node via `add_child()`, unless `legible_unique_name` is true, the new node has a few `@` characters in the name.
If you then store the `name` property of the node in a variable, then set the node's `name` from the variable, Godot drops the `@`.
As far as I could tell, this isn't mentioned in the documentation. I ran into this issue when saving / loading scenes with children added on the fly and trying to reparent children to the proper parent nodes when loading.

**Steps to reproduce:**
As above.

**Minimal reproduction project:**
[NameTest.zip](https://github.com/godotengine/godot/files/6212536/NameTest.zip)

**Comment by Calinou** [comment] 2021-03-26 14:54
Duplicate of https://github.com/godotengine/godot/issues/27608.

**Closed by Calinou** 2021-03-26 14:54 UTC
