### ISSUE TITLE
Change select area of node

### ISSUE THREAD

**Issue by Lucrecious** [godotengine/godot#28238] opened 2019-04-20 16:14 UTC
**Godot version:**
3.1

**Issue description:**
So I've been creating more and more tools in Godot, because it's awesome to have an embedded custom level editor with the engine.

Anyways, I created a custom sprite node (essentially) but the selectable area is only a point, I'd like to change the point to a rectangle that surrounds my sprite.

I don't know how this is possible, and I've tried searching for it.

Here's someone who's had the issue #4255, apparently it's been "fixed" with https://github.com/godotengine/godot/pull/17502, but I can't figure out how to change the selectable area.

If this is possible but not documented, maybe have it more obviously documented somewhere?

**Comment by Calinou** [comment] 2021-09-01 17:58
Duplicate of https://github.com/godotengine/godot/issues/15599.

**Closed by Calinou** 2021-09-01 17:58 UTC
Labels: discussion, topic:core
