### ISSUE TITLE
Godot Mono freezes when drag and dropping image into editor (import)

### ISSUE THREAD

**Issue by ManetBoi** [godotengine/godot#72632] opened 2023-02-02 23:30 UTC
### Godot version

4.0

### System information

Windows 11, Geforce RTX 2060, intel 10th gen

### Issue description

(beta 17) I imported a 8x8 png file and the import window froze and the program froze. When reloading, the file was here. It is also my first time importing in GD 4 and the first time opening a project in GD4 Mono.

### Steps to reproduce

Drag and drop .png file into editor (while selecting subfolder, not sure if it is the problem).

### Minimal reproduction project

Empty godot project with folders (Maps, Prefabs, Resources, Scripts, Sprites). Also had an unsaved scene with a CharacterBody2D as root with an empty Sprite2D and a CollisionShape2D with RectangleShape. Imported file :
![Square](https://user-images.githubusercontent.com/124316713/216474489-8c1b9af7-aa8e-4518-b201-f6ed27ae5eb3.png)

**Comment by Zireael07** [comment] 2023-02-03 08:21
Most likely duplicate of  #69911

BTW 4.0 doesn't tell us anything - which beta, which commit if you built from source?

**Comment by ManetBoi** [comment] 2023-02-03 22:50
> Most likely duplicate of #69911
> 
> BTW 4.0 doesn't tell us anything - which beta, which commit if you built from source?

beta 17

**Comment by saierXP** [comment] 2023-02-04 10:21
Maybe the single-window mode(interface/editor/single_window_mode) can solve this problem. I tested b15-16-17. The issue only happens in b17 with multi-window mode.

**Comment by hmturnbull** [comment] 2023-02-08 03:05
I've had this problem in the Standard build, so it's not unique to Mono.

The problem only seems to happen when dragging into the FileSystem dialogue.  Dragging the file into the directory using File Explorer seems to work, though, so that's a workaround for now.

I think #72839 provides a more accurate description of the problem, so I think this should be closed in favour of #72839.

**Comment by akien-mga** [comment] 2023-02-08 07:34
Duplicate of #72839

**Closed by akien-mga** 2023-02-08 07:34 UTC
