### ISSUE TITLE
Volumetric fog with VoxelGI weird behavior depending on camera position

### ISSUE THREAD

**Issue by Defwentz** [godotengine/godot#85765] opened 2023-12-04 22:36 UTC
### Tested versions

- Reproducible in: 4.2.stable

### System information

Windows 10 - Godot v4.2.stable - Vulkan (Forward+) - Dedicated

### Issue description

In a scene with global volumetric fog and 2 VoxelGI nodes. When running the scene, if camera start out looking at one VoxelGI node but not another, the unseen node will get overwritten by the seen node. If camera start out looking at neither, both will become white. If camera can see both, both will look normal.
![屏幕截图(473)](https://github.com/godotengine/godot/assets/8059644/c7821d85-8f91-4724-a7dc-8b451e780e9c)
![屏幕截图(474)](https://github.com/godotengine/godot/assets/8059644/f189d1a5-10c4-4342-9e5a-42cafbafbe6a)
![屏幕截图(475)](https://github.com/godotengine/godot/assets/8059644/9e0bdebe-95b3-4189-aaec-6fb2b43d3560)

issue brought up by @Rytelier in https://github.com/godotengine/godot/issues/85642#issuecomment-1837609425_

### Steps to reproduce

In the minimal reproduction project, hold right mouse button to control camera. By default the camera is looking downward, not seeing any VoxelGI node.

1. Run light.tscn and rotate camera upward then around to see both VoxelGI nodes are foggy and white.
2. In editor, reset camera rotation, run scene again. The red emissive is normal, but turning the camera around, the other VoxelGI node is also red.
3. While looking at one VoxelGI node, maximize the window to trigger a (redraw?). The currently seeing node will update to normal. Turn the camera around, the other VoxelGI color is now overwritten.

### Minimal reproduction project (MRP)

[voxelgi_volfog_bug2.zip](https://github.com/godotengine/godot/files/13552147/voxelgi_volfog_bug2.zip)

**Comment by bitsawer** [comment] 2023-12-04 23:31
I can confirm the odd behavior when camera is initially turned away from VoxelGI nodes.

Additionally, there seems to be some other rendering issues with the fog and VoxelGI. When the red cube is out of camera view, the light color is faded away to default white Albedo as shown in the video:

https://github.com/godotengine/godot/assets/22456603/e82fc005-1647-4cef-92bc-7f925e3b16c0

The editor view seems to also have some issues, but at least it seems like the volume fog can apply to at least two VoxelGI volumes at the same time if they and the editor camera are positioned in a very specific way:

https://github.com/godotengine/godot/assets/22456603/3be8dbad-2e4c-4ecd-b7e4-f925fc6aa5cb

**Comment by Lippanon** [comment] 2023-12-05 11:24
Could this be related to VolumetricFog's culling issue demonstrated in https://github.com/godotengine/godot/issues/74790 or is VoxelGI not affected by culling?

**Comment by Defwentz** [comment] 2023-12-07 22:45
This first video's fading color https://github.com/godotengine/godot/issues/85765#issuecomment-1839720066 does look a lot of like the culling artifact in that issue. Both artifacts I can see a visible shape.

**Comment by akien-mga** [comment] 2024-01-25 09:17
Why close this? Is it fixed?
I see a pending PR aiming to fix it but it's not merged yet, so the bug should stay open.

**Comment by Defwentz** [comment] 2024-01-26 01:22
I see, merge is the indicatior. Thanks, I wasn't completely sure about it.

**Closed** 2024-03-01 14:02 UTC
Labels: bug, topic:rendering, topic:3d
