### ISSUE TITLE
Error when playing sound

### ISSUE THREAD

**Issue by RaXaR** [godotengine/godot#12660] opened 2017-11-05 15:49 UTC
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Windows 7 x64
Godot 3.0 alpha 2

**Issue description:**
Whenever i play a sound with the AudioStreamPlayer  (or 2D variant) then an error is thrown
in the debugger 'Errors' tab:
```
0:00:01:0929 Condition '!active' is true
```
The call looks like this:
```
get_node("SoundHit").play()
```
Not sure if it helps, but I'm playing an OGG sample.

**Comment by reduz** [comment] 2017-12-07 21:28
closing because i can't reproduce.. please add more context if you can still reproduce on latest godot

**Comment by RaXaR** [comment] 2017-12-08 04:17
Yip, the error still exists. I've attached a sample project.

It looks like the error occurs when I either uncheck the loop checkbox on the Import tab OR if I set it via GDScript to not loop.

[SoundError.zip](https://github.com/godotengine/godot/files/1541361/SoundError.zip)

**Comment by akien-mga** [comment] 2018-01-05 15:22
Can you still reproduce it in the current master branch?

**Comment by akien-mga** [comment] 2018-01-06 22:21
I can't reproduce it in the current master branch using the provided project. There were recent fixes to audio looping so that likely fixed that one too.

**Closed by akien-mga** 2018-01-06 22:21 UTC
Labels: bug, topic:audio

**Comment by RaXaR** [comment] 2018-03-28 22:11
Sorry was away for a bit. I tested just now and the error is gone.
