### ISSUE TITLE
@export-ing a const preload() crashes Godot.

### ISSUE THREAD

**Issue by Psychpsyo** [godotengine/godot#71078] opened 2023-01-08 17:29 UTC
### Godot version

v4.0.beta4.mono.official [e6751549c]

### System information

Linux Mint 21.1

### Issue description

When in the Godot code editor, the entire program will instantly crash when writing a `const foo = preload("res://someScript.gd")`, followed by an `@export` statement for a variable of the just preloaded type.

### Steps to reproduce

1. Create a new Godot project.
2. Create foo.gd like this:
```
extends Node
```
3. Create another script like this:
```
extends Node

const Foo = preload("res://foo.gd")

@export
var foo: Foo
```
4. Godot should have become unresponsive, then closed itself on step 3.

### Minimal reproduction project

Note: This project is missing the second `o` in `Foo` in exporter.gd since, as soon as I type it, the engine crashes without saving.
[GodotBug#71078.zip](https://github.com/godotengine/godot/files/10369044/GodotBug.71078.zip)

**Comment by adamscott** [comment] 2023-01-08 18:50
@Psychpsyo Please test on the latest beta to see if the issue is still present before creating an issue.

Just tested on master (fcba87e) and I couldn't reproduce.

**Comment by adamscott** [comment] 2023-01-08 18:53
I confirm the crash on beta 4, [but we're at beta 10 already](https://godotengine.org/article/dev-snapshot-godot-4-0-beta-10), and it's already fixed.
@akien-mga We can close this issue.

**Closed** 2023-01-08 22:49 UTC
