### ISSUE TITLE
macOS window resize draws everything black while resizing

### ISSUE THREAD

**Issue by lexum0** [godotengine/godot#9546] opened 2017-07-08 04:12 UTC
**Operating system or device - Godot version:**
macOS - Godot 2.1.3

**Issue description:**
When resizing the window, everything is drawn black, when you finish it goes back to normal. This makes it hard to resize since you can't see anything.

In Windows this works as expected and draws correctly during the window resize

**Steps to reproduce:**
Run the game and resize the window by dragging the edges or corners.

**Comment by tavurth** [comment] 2018-08-22 19:49
Tested on `Godot 3.06` `OSX 10.12` mid 2014 macbook air, could not reproduce.

Tested resizing the Godot engine window, no black screen. Resizes as normal.
Tested resizing a Godot game window, no black screen. Resizes as normal.

Propose closure.

@lexum0

**Comment by akien-mga** [comment] 2018-08-22 20:33
Would be fixed in the 2.1 branch too now with #9836, so closing indeed.

**Closed by akien-mga** 2018-08-22 20:33 UTC
Labels: bug, platform:osx, topic:rendering
