### ISSUE TITLE
Shader uniforms cannot be keyframed into an animation

### ISSUE THREAD

**Issue by sicienss** [godotengine/godot#24690] opened 2019-01-01 04:08 UTC
**Godot version:**
3.1 alpha 4 (downloaded from [here](https://hugo.pro/projects/godot-builds/))

**OS/device including version:**
Windows 8, Toshiba Satellite

**Issue description:**
Clicking the keyframe icon next to a shader parameter in the inspector does not keyframe the current value into the animation. It doesn't do anything.

It appears you cannot keyframe the `shader` itself or the `render_priority` either.

**Steps to reproduce:**
1. Create a scene consisting of a `Sprite` with an `AnimationPlayer` child.
2. Add a shader to the `Sprite` with some uniform.
3. Try to key frame values of the uniform into an animation via the inspector.
4. Observe that nothing happens when you click the keyframe icon next to the shader parameter.

**Minimal reproduction project:**
[TestProject.zip](https://github.com/godotengine/godot/files/2719110/TestProject.zip)

**Comment by Zylann** [comment] 2019-01-01 04:32
I just tried for `ShaderMaterial` in 3.0.6, and there is a twist:
if you just setup the shader, the default value in `ShaderMaterial` is `null`, and can't be keyframed either. But, if you manually click that property, and enter any value, it gets set to a non-null value, and it CAN be keyframed.

This also happens in 3.1 alpha4, even though the inspector appears to show a default value. If you have a `vec3` parameter, just set it to `(1, 0, 0)` for example, and then you'll see Godot will allow you to keyframe it.
It's very strange, could be related to https://github.com/godotengine/godot/issues/24488

**Comment by sicienss** [comment] 2019-01-01 04:36
Yeah, I noticed that in 3.0.6 as well. In 3.1, I have a float uniform that I just can't seem to get keyframed, even if I manually change the value from the default in the inspector.

I'm using hint_range(0, 1), wonder if that has something to do with it. I'll keep experimenting.

**Comment by danielpcs** [comment] 2019-01-14 15:40
I am also facing that issue when trying to keyframe some settings in a ProceduralSky inside a WorldEnvironment node. A current workaround is to change the track name to what you need, in my case "**WorldEnvironment:environment:background_sky:sky_top_color**", it should work as intended after that.

I believe it might be related to how the new UI is set up, it might not be providing the correct values for the keyframe button, so anything that is not a direct property of the node or has more than one level (e.g. resource properties) won't work.

**Comment by KoBeWi** [comment] 2021-05-22 19:59
Reopening, the issue seems still present in 3.3.

1. Add a shader
2. Add a uniform with hint range
3. Try keying it

Here's minimal project:
[Shaderbug.zip](https://github.com/godotengine/godot/files/6527051/Shaderbug.zip)
You get the same error as in second comment here. You can fix this by using the slider to set some value before animating it.

**Comment by DIPANJAN01** [comment] 2024-03-20 10:07
This bug still exits in `v4.2.1`
I think we SHOULD be able to animate uniform shader parameters.

**Comment by KoBeWi** [comment] 2024-03-20 12:12
I can't reproduce it in 4.3 with my previous attached project.
Do you have an up-to-date MRP for this bug?
Also based on my previous comment, it's only happening if the value is uninitialized (related #44454). Normally it is possible to animate shader parameters.

**Comment by aftrosrs** [comment] 2024-06-18 06:56
This is in 4.2.2, so maybe 4.3 fixes the issue? i attached my shader code and the error below

```
 editor/animation_track_editor.cpp:4120 - Could not determine track hint for '.:material:shader_parameter/blur' because its base property is null.
  editor/animation_track_editor.cpp:4120 - Could not determine track hint for '.:material:shader_parameter/brightness' because its base property is null.
```


```
shader_type canvas_item;

uniform float blur: hint_range(0.1, 2.5);
uniform float brightness: hint_range(0.0, 1.0);
uniform sampler2D screen_texture: hint_screen_texture;
uniform vec2 blur_size;

void fragment() {
	vec4 color = vec4(0.0);
	int count = 0;
	for(int i=-2; i<=2; i++){
		for(int j=-2; j<=2; j++){
			color += texture(screen_texture, SCREEN_UV + vec2(float(i),float(j))*blur_size);
			count++;
		}
	}
	COLOR = color/float(count);
	COLOR.rgb *= brightness;
}
```

**Comment by KoBeWi** [comment] 2024-06-18 11:07
Yeah fixed in 4.3

**Closed by KoBeWi** 2024-06-18 11:07 UTC
Labels: bug, topic:editor, topic:animation

**Comment by banoffeejoe** [comment] 2024-07-26 03:43
i'm encountering this issue. i was able to key in animation. then suddenly right now float value cannot be adjusted once you key in  the value.

**Comment by banoffeejoe** [comment] 2024-07-29 16:30
> i'm encountering this issue. i was able to key in animation. then suddenly right now float value cannot be adjusted once you key in the value.

turns out AnimationTree is what made me not key shaders. no issues.
