### ISSUE TITLE
Sprite3D disappear in the editor view

### ISSUE THREAD

**Issue by AlexanderO88** [godotengine/godot#2061] opened 2015-06-10 06:10 UTC
Hey guys,

I found a big sprite3D bug in Godot 1.1 stable. If I create a new sprite3D, add a texture (see picture 1) and translate, rotate or scale it, the sprite3D disappear in the editor view (see picture 2). Sometimes it disappear very fast, sometimes it takes a little time. If you play the project the sprite3D is back in the play view but not in the editor view.

I could reproduce the bug on my pc with Kubuntu 14.04 and an Nvidia graphic card and on my laptop with Windows 7 and an Intel graphic card.

P.S. In Godot 1.0 stable everything works fine.

![sprite3d1](https://cloud.githubusercontent.com/assets/11014216/8075042/5c302e14-0f3b-11e5-8314-3c2ced1a430e.JPG)
![sprite3d2](https://cloud.githubusercontent.com/assets/11014216/8075043/5d741fb0-0f3b-11e5-9a23-df4f3b57cad1.JPG)

**Comment by akien-mga** [comment] 2015-11-12 14:29
Hi @AlexanderO88 and sorry for the delay. Can you still reproduce this issue in the current master branch/nightly builds?

**Comment by AlexanderO88** [comment] 2015-11-15 11:44
Hi @akien-mga no, I can't reproduce the bug in the latest nightly build, but my issue #1366 is still active.

**Comment by akien-mga** [comment] 2015-11-15 14:15
Thanks, closing this one then.

**Comment by AlexanderO88** [comment] 2015-12-12 05:18
Hi @akien-mga, unfortunately I have bad news. A few minutes ago I could reproduce the bug in the latest nightly build. When my Sprite3D disappear I get always the error 

"ERROR: move: Condition ' e.octant_owners.front()==__null ' is true.
At: core/math/octree.h:942."

in the terminal.

**Comment by trollworkout** [comment] 2016-01-30 00:40
I can confirm same issue  trying to move rigidbodies with translate and billboard sprites.

**Comment by bojidar-bg** [comment] 2017-03-21 11:49
Ahem. Can someone try to reproduce this after #3746 (in 2.1.2)? @trollworkout @AlexanderO88

**Comment by reduz** [comment] 2017-08-04 16:46
does this still happen in 3.0? I can't reproduce

**Comment by AlexanderO88** [comment] 2017-08-05 09:12
I can't reproduce the bug with 3.0 alpha 1 because #9596

**Comment by reduz** [comment] 2017-08-07 21:41
#9596 is fixed, so please try again

**Closed** 2017-08-08 20:25 UTC
Labels: bug, needs testing, topic:editor, topic:rendering
