### ISSUE TITLE
Type casting to String is not working

### ISSUE THREAD

**Issue by TokageItLab** [godotengine/godot#50694] opened 2021-07-21 11:15 UTC
### Godot version

4.0.dev (88bf6e1c6d3e711976304bb16ac51719e8e82f72)

### System information

MacOS 11.4

### Issue description

<img width="615" alt="スクリーンショット 2021-07-21 20 14 07" src="https://user-images.githubusercontent.com/61938263/126480046-f7b880ca-02d2-444c-9777-301091bbd257.png">

Also, the function suggestions for all classes are broken, so the built-in class declarations may be broken.

### Steps to reproduce

Try to do a `String(AnyType)` on GDScript.

### Minimal reproduction project

[AsString.zip](https://github.com/godotengine/godot/files/6855140/AsString.zip)

**Comment by Calinou** [comment] 2021-07-21 11:43
In GDScript, casting to String is generally done with `str()` rather via `String()`.

**Comment by vnen** [comment] 2022-04-18 14:17
Not sure if that's a bug, we might not need `String()` constructors for every possible type. As said, you can use `str()` in GDScript if you want the conversion.

 We could potentially add a suggestion to use `str()` in the error message.

**Comment by Calinou** [comment] 2022-06-18 17:43
That reminds me, why do we have different constructors for `str()` and `String()`

**Comment by TokageItLab** [comment] 2022-06-18 18:29
I agree that this is problematic in terms of maintainability, since every time some classes are added, conversion methods are needed in the String class. However, I still think there are few base classes that are compatible with String.

**Comment by akien-mga** [comment] 2022-06-29 13:54
Duplicate of #44407

**Closed by akien-mga** 2022-06-29 13:54 UTC
Labels: bug, topic:gdscript, regression
