### ISSUE TITLE
Previous/Next tab shortcuts do not work

### ISSUE THREAD

**Issue by letheed** [godotengine/godot#13843] opened 2017-12-02 22:56 UTC
Current shortcuts `Ctrl+Tab` and `Ctrl+Shift+Tab` for Next/Previous tab do not work. They change the element/dock in focus instead. Either that should be fixed or another pair of shortcuts should be used. I'd suggest `Ctrl+PageUp`/`Ctrl+PageDown`, which is very common.

**Comment by NilsIrl** [comment] 2019-07-20 17:55
Working on it

**Comment by NilsIrl** [comment] 2019-07-20 17:56
Seems to be a duplicate of #8799

**Comment by akien-mga** [comment] 2019-07-20 18:08
Thanks, closing as duplicate.

**Closed** 2019-07-20 18:08 UTC
Labels: bug, topic:editor
