### ISSUE TITLE
Viewport preview for 3D scene is upside-down

### ISSUE THREAD

**Issue by rick551a** [godotengine/godot#55824] opened 2021-12-11 15:25 UTC
### Godot version

Godot_v3.4-stable_mono_win64

### System information

Windows 10, NVidia

### Issue description

A viewport containing a 3D scene will display the preview in the inspector upside-down

### Steps to reproduce

Create a Viewport

Add a 3D spatial scene

Populate it with some 3D objects

Oberve that the inspector's viewport preview is upside down

### Minimal reproduction project

Small project showing it:

https://ufile.io/2c7gde16

Note the location of the environment sun in the inspector preview (it's on floor)

**Comment by Chaosus** [comment] 2021-12-11 15:45
You could turn VFlip property in the inspector to "fix" it. Not sure it's a bug, seems like the intended behavior for OpenGL viewports.

**Comment by Calinou** [comment] 2021-12-11 15:54
This is expected in `3.x` per @Chaosus' comment. Enabling **Render Target > V Flip** is no longer required in `master` as viewports are drawn in the right orientation there.

**Comment by zaevi** [comment] 2021-12-11 16:20
If enable viewport's `v_flip`, the `ViewportContainer` will flip again. Shouldn't flip the viewport directly.

Since the preview control uses a `TextureRect` with `ViewportTexture`, flip the TextureRect could be better.

![image](https://user-images.githubusercontent.com/12966814/145683450-32143b6e-941b-4096-b406-da09db3b141e.png)

**Comment by akien-mga** [comment] 2021-12-12 20:03
Fixed by #55830.

**Closed by akien-mga** 2021-12-12 20:03 UTC
Labels: bug, topic:editor
