### ISSUE TITLE
2.1.3 stuttering problem and solution

### ISSUE THREAD

**Issue by ArisKallergis** [godotengine/godot#8800] opened 2017-05-17 20:41 UTC
**Operating system or device - Godot version:**
Windows 8.1 , Godot 2.1.3

**Issue description:**
Even in the simplest of projects, I experienced stuttering.
So I played with the vsync setting in project settings, and found out that if I keep the leftmost checkbox ticked and the right one unticked, the stuttering disappears. No other combination works. 
Also tested it in another really simple project, where I had the same problem, and it works.

**Steps to reproduce:**
I don't really know. This existed before tinkering with the vsync settings.

**Link to minimal example project:**
[KidsCanCodeAlien.zip](https://github.com/godotengine/godot/files/1009061/KidsCanCodeAlien.zip)

**Comment by volzhs** [comment] 2017-05-17 20:58
Can't run example project.
zip contains only one `player.tscn` so I set it as main scene and run project.
then... it just close game.
```
running: /mnt/2TB/Godot/Godot 2/godot.tools.64 -path /home/volzhs/Downloads/KidsCanCodeAlien -rdebug localhost:6007 -epid 13246 -p 0x0 res://player.tscn
ERROR: load_image: Error opening file: res://Player/alienGreen_front.png
   At: core/io/image_loader.cpp:53.
ERROR: load: Failed loading image: res://Player/alienGreen_front.png
   At: scene/io/resource_format_image.cpp:116.
ERROR: load: Failed loading resource: res://Player/alienGreen_front.png
   At: core/io/resource_loader.cpp:210.
ERROR: poll: res://player.tscn:4 - Parse Error: [ext_resource] referenced nonexistent resource at: res://Player/alienGreen_front.png
   At: scene/resources/scene_format_text.cpp:231.
ERROR: load: Condition ' err != OK ' is true. returned: RES()
   At: core/io/resource_loader.cpp:137.
ERROR: load: Failed loading resource: res://player.tscn
   At: core/io/resource_loader.cpp:210.
ERROR: start: Failed loading scene: res://player.tscn
   At: main/main.cpp:1401.
shit?: Connection reset by peer
ERROR: read: Server disconnected!
```

**Comment by ArisKallergis** [comment] 2017-05-17 21:21
[KidsCanCodeAlien.zip](https://github.com/godotengine/godot/files/1009147/KidsCanCodeAlien.zip)

I hadn't set the main scene, sorry. Maybe this zip works?

There is a checkbox to the left of vsync (for enabling and disabling vsync) and a checkbox for turning it on or off. The stuttering stops only when vsync is enabled, but turned off.

**Comment by eon-s** [comment] 2017-05-17 22:17
This may be duplicate of #2043

**Comment by ArisKallergis** [comment] 2017-05-17 23:00
I just read it. There is a person called JustDevs that provides a solution just like mine. Maybe it is just that our computers have similar settings? I believe it is worth investigating this, because the problem is solved only when the checkbox for vsync to persist is on, but vsync itself is turned off. Maybe there is a clue in there.

**Comment by eon-s** [comment] 2017-05-18 04:35
@ArisKallergis  Maybe turning on and off vsync leaves the driver in an optimal state, with your character I got the stuttering sometimes at that speed (less faster, none lower), no matter the settings, got almost nothing with pixel snap enabled.

**Comment by kubecz3k** [comment] 2017-05-18 14:29
It's a very clear duplicate of https://github.com/godotengine/godot/issues/2043 @ArisKallergis please share your findings in https://github.com/godotengine/godot/issues/2043 if you can! I will close this one as a duplicate. Thanks!

**Closed by kubecz3k** 2017-05-18 14:29 UTC
