### ISSUE TITLE
Godot 3.1 - AnimationTree

### ISSUE THREAD

**Issue by Tommel1234** [godotengine/godot#23664] opened 2018-11-12 09:31 UTC
**Godot version:**
3.1 alpha 2 mono

**OS/device including version:**
Windows 10 - Geforce GTX 1070

**Issue description:**
I got some problems with the AnimationTree there is more than one instance of the scene using the same AnimationTree. The animations seem accelerated. For example, I got a scene with a player and 1 enemy.. Everything work fine.. but if I duplicate the enemy scenes. the enemies animation are super fast !

I had the same problem with my player because it was using the same AnimationTree.. I had to make the "Tree root" unique to fix my player animations speed

I recorded the issue
[](https://youtu.be/4t1vj8V7T7w)
https://youtu.be/4t1vj8V7T7w

It may not be a bug.. but i have not find how to fix it on different instance of the same scene.

**Comment by akien-mga** [comment] 2018-11-12 09:37
Duplicate of #22887, fixed already in the master branch.

**Closed by akien-mga** 2018-11-12 09:37 UTC
