### ISSUE TITLE
Animated resource made up of tres files does not animate and shows wrong texture and/or breakd tilemaps

### ISSUE THREAD

**Issue by chucklepie** [godotengine/godot#57699] opened 2022-02-06 11:00 UTC
### Godot version

3.4.2

### System information

PopOS

### Issue description

Observe the image. This is an animated resource file made up of the blue textures you can see. The frames you can see are themselves .tres files from a large spritesheet.

Instead of showing the animation, the animated resource is simply showing the whole texture and in the tilemap you can see the highlighted images are where the tile should be, but instead these are the first image of the spritesheet, i.e. the tilemap is showing the first 32x32 portion of the sprite. In fact if you look at the animated image, it thinks it really is a 32x32 texture but it's a texture 1400x1400 pixels ;-)

So, there's probably a bug in the .tres rather than tilemap. Is there any solution to this? tbh, every single step I go with using .tres and/or sprite sheets something fails badly in Godot, I dunno if it needs properly looking at...

Using normal .png files for the individual parts of the animated sprite work fine as can be seen by the blue vertical conveyer to the left of the highlighted failed one.

![image](https://user-images.githubusercontent.com/12863685/152677646-befc6bbf-692a-4428-9bb7-26e70eee7565.png)

### Steps to reproduce

As description. I can create a small sample, but the problem is indicated clearly by the description.

**Comment by Calinou** [comment] 2022-02-06 11:19
@chucklepie Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

**Comment by timothyqiu** [comment] 2022-02-06 13:48
Possible duplicate of #30295. `AtlasTexture` in `AnimatedTexture` is currently not well-supported.

@chucklepie Maybe this is also the same issue as your #57658?

**Comment by Calinou** [comment] 2022-02-06 13:54
Duplicate of https://github.com/godotengine/godot/issues/30295.

**Closed by Calinou** 2022-02-06 13:54 UTC
Labels: bug, topic:editor, needs testing, topic:2d

**Comment by chucklepie** [comment] 2022-02-06 16:00
@Calinou thanks. I saw no obvious answers or roadmap in that duplicate and it's been open since over 2 years. I guess this mean it'll never be fixed and I can't use spritesheets in animated resources?

**Comment by Calinou** [comment] 2022-02-06 16:40
> I guess this and the comments mean it'll never be fixed and I can't use spritesheets in animated resources?

No contributor knows how to implement this, so it's unlikely that it will ever be done. This is especially the case as atlases don't save much memory when used for tilemaps compared to seaprate images.

**Comment by chucklepie** [comment] 2022-02-06 16:45
ok, perhaps if it'll never work, something should be done at the front end to stop it...?
