### ISSUE TITLE
C# Mono [Export] not working in heirs if value is default

### ISSUE THREAD

**Issue by wmigor** [godotengine/godot#37581] opened 2020-04-04 13:59 UTC
**Godot version:** Godot_v3.2.1-stable_mono_x11.64

**OS/device including version:** Linux mint

**Issue description:** 
I have two classes
Unit:
```
using Godot;

public class Unit : Node2D
{
    [Export] 
    public int Health;
    
    public override void _Ready()
    {
        GD.Print("Health: " + Health);
    }
} 
```
and Player:
```
public class Player : Unit
{
}
```

Two scenes
Unit.tscn:
```
[gd_scene load_steps=2 format=2]

[ext_resource path="res://Unit.cs" type="Script" id=1]

[node name="Unit" type="Node2D"]
script = ExtResource( 1 )
Health = 50
```

and Player.tscn inherited from Unit.tscn:
```
[gd_scene load_steps=3 format=2]

[ext_resource path="res://Unit.tscn" type="PackedScene" id=1]
[ext_resource path="res://Player.cs" type="Script" id=2]

[node name="Player" instance=ExtResource( 1 )]
script = ExtResource( 2 )
```

Player.tscn prints "Health: 0". But the value must be taken from the parent.
If you change Health in Player.tscn, it works correctly.

**Minimal reproduction project:** [cstest.zip](https://github.com/godotengine/godot/files/4431504/cstest.zip)

**Comment by aaronfranke** [comment] 2020-04-04 15:20
How did you even make this? If you instance the `Unit` scene and try to set it as root, Godot gives back a message of "Instantiated scenes can't become root".

I can confirm the behavior is weird, but also, it really seems like you're not supposed to do this...

**Comment by wmigor** [comment] 2020-04-04 17:03
in gdscript player.tscn prints 50

**Comment by kgene1** [comment] 2020-05-05 11:17
I think this is a duplicate of [#36480](https://github.com/godotengine/godot/issues/36480)

**Closed** 2020-05-11 08:19 UTC
Labels: topic:mono
