### ISSUE TITLE
Can't assign Nodes to Array[Node]

### ISSUE THREAD

**Issue by coelhucas** [godotengine/godot#68416] opened 2022-11-08 17:53 UTC
### Godot version

v4.0.beta4.official [e6751549c]

### System information

macOS Monterey 2,3 GHz Intel Core i9 8-Core AMD Radeon Pro 5500M 4 GB Intel UHD Graphics 630 1536 MB

### Issue description

When exporting an array of nodes I'm not able to assign a Node to each index.

### Steps to reproduce

```gdscript
extends Node
class_name MyNode

@export var something: Array[MyNode] # assigning doesn't have any effect
@export var something: MyNode # works fine
```
For a "single" entity works | For an array it doesn't get assigned
-- | --
![image](https://user-images.githubusercontent.com/28108272/200639246-bc489781-7183-42b5-8e88-1069f1aed3b3.png) | ![image](https://user-images.githubusercontent.com/28108272/200639287-1e08a699-1f00-4d0d-b22e-ad2b37b4f5da.png)

**Comment by kleonc** [comment] 2022-11-08 18:02
Duplicate of  #62916.

**Closed by kleonc** 2022-11-08 18:02 UTC
