### ISSUE TITLE
Cannot cross-compile Windows D3D12 with LLVM MinGW

### ISSUE THREAD

**Issue by MBCX** [godotengine/godot#87748] opened 2024-01-30 17:58 UTC
### Tested versions

I've encountered this trying to build [cae759949], did not occur with [0bcc0e92b] (the version I built)

### System information

Debian 13 - v4.3.dev.custom_build [cae759949]

### Issue description

I use [mstorsjo's LLVM MinGW](https://github.com/mstorsjo/llvm-mingw) to cross compile Godot for Windows with D3D12, but now it seems to not compile with the recent changes.

### Steps to reproduce

With this build command:
```
scons -j4 target="editor" platform="windows" d3d12="yes" dxc_path="$HOME/Documents/d3d12/dxc" mesa_libs="$HOME/Documents/nir/win" agility_sdk_path="$HOME/Documents/d3d12/agilitysdk" pix_path="$HOME/Documents/d3d12/pix" angle_libs="$HOME/Documents/angle/win/x86_64" use_mingw="yes" use_llvm="yes" agility_sdk_multi_arch="yes" production="yes" lto="none" use_pix="yes"
```
I get this error:
```
platform/windows/display_server_windows.cpp:251:4: error: non-constant-expression cannot be narrowed from type 'DWORD' (aka 'unsigned long') to 'int' in initializer list [-Wc++11-narrowing]
  251 |                         QITABENT(FileDialogEventHandler, IFileDialogControlEvents),
```

### Minimal reproduction project (MRP)

N/A

**Comment by MBCX** [comment] 2024-01-30 18:00
OK. Using GCC MinGW does compile with no problems, so it seems to be a LLVM/Clang issue.

**Comment by bruvzg** [comment] 2024-01-30 18:02
See https://github.com/godotengine/godot/pull/87720 (issue is not directly related to D3D). You can also add `werror=no` to the build command to ignore this warning.

**Comment by akien-mga** [comment] 2024-01-30 18:06
Duplicate of #87720.

**Closed by akien-mga** 2024-01-30 18:06 UTC
Labels: bug, platform:windows, platform:linuxbsd, topic:buildsystem
