### ISSUE TITLE
`gdnative-generate-json-api` doesn't work

### ISSUE THREAD

**Issue by MednauN** [godotengine/godot#10708] opened 2017-08-28 05:02 UTC
**Operating system or device, Godot version:**
OS: Windows 10 x64
Godot version: 3.0 (8fce79aaeef3788bed170f07fc728e25f66e4a20)

**Issue description:**
Launching godot executable with "--gdnative-generate-json-api api.json" doesn't produce json file with api.
Output:
```
>godot.windows.tools.64.exe --gdnative-generate-json-api api.json

Activated GL 3.3 contextOpenGL ES 3.0 Renderer: Intel(R) HD Graphics 4600
GLES3: max ubo light: 409
GLES3: max ubo reflections: 455, ubo size: 144
ERROR: No loader found for resource: res://api.json
   At: core\io\resource_loader.cpp:223
ERROR: Failed loading scene: res://api.json
   At: main\main.cpp:1456
WARNING: ObjectDB::cleanup: ObjectDB Instances still exist!
     At: core\object.cpp:1996
```

Issue seems to appear after commits 3d1c03187132677800b7f6bc609eeef8fe51f315 and 36e0a72c77348d4a1f2195937dff8dba88f7e044.
Before these two commits (at 21d53f29f392f4a33095de75c478da345a362555) everything worked fine.

**Comment by bojidar-bg** [comment] 2017-08-28 06:39
Duplicate of #10412, even though the cause here is that 36e0a72c77348d4a1f2195937dff8dba88f7e044 disabled the gdnative module temporary.

**Closed by bojidar-bg** 2017-08-28 06:39 UTC
