### ISSUE TITLE
Exported project doesn't use correct app icon and title in Windows Task Bar context menu

### ISSUE THREAD

**Issue by AgentSmith0** [godotengine/godot#54713] opened 2021-11-07 12:21 UTC
### Godot version

3.4-stable

### System information

Linux, GLES3

### Issue description

The Windows Task Bar context menu uses the default Godot icon and the text "Godot Engine" instead of custom app icon and title.

EDIT: I use embedded PCK for export.

### Steps to reproduce

Export a project with custom icon and title for Windows and launch the program. When you right click on the app in the task bar you will see that it uses the wrong app icon and title.

**Comment by bruvzg** [comment] 2021-11-07 12:31
> Export a project with custom icon

Check if your custom ICO file have all required size (16×16, 32×32, 48×48, 64×64, 128×128 and 256×256)?
See [Changing application icon for Windows](https://docs.godotengine.org/en/stable/getting_started/workflow/export/changing_application_icon_for_windows.html) for more info.

Also check if path to the [`rcedit`](https://github.com/electron/rcedit) utility is correctly specified in the editor settings, it's required to change icon and app info on export.

**Comment by AgentSmith0** [comment] 2021-11-07 13:03
I used ImageMagick to generate the required .ico file. But it looks like I am missing rcedit. Does rcedit also work on Linux?

**Comment by bruvzg** [comment] 2021-11-07 13:05
> Does rcedit also work on Linux?

There's no native `rcedit` but it should work under Wine (there are Editor settings to specify both wine executable and rcedit).

**Comment by AgentSmith0** [comment] 2021-11-07 13:06
Is it enough to just enter wine in the field or do I need to specify the full path?

**Comment by bruvzg** [comment] 2021-11-07 13:09
If it's in the PATH and named `wine`, you can leave the option empty and only set path to rcedit. Otherwise, only full path will work.

**Comment by AgentSmith0** [comment] 2021-11-07 13:35
Now I specified the path for wine and rcedit correctly, but the application still uses the default icon in the File Explorer and in the context menu. Unfortunately there was no change.

**Comment by AgentSmith0** [comment] 2021-11-07 13:59
I specified a path for both wine and rcedit, but it still uses the default icon in the File Explorer and in the context menu. Nothing has changed.

**Comment by AgentSmith0** [comment] 2021-11-07 16:48
Maybe a duplicate of https://github.com/godotengine/godot/issues/36629 or https://github.com/godotengine/godot/issues/47240

**Comment by Calinou** [comment] 2021-11-07 18:26
> EDIT: I use embedded PCK for export.

That's why it broke; this is a duplicate of https://github.com/godotengine/godot/issues/33466.

**Closed by Calinou** 2021-11-07 18:26 UTC

**Comment by AgentSmith0** [comment] 2021-11-07 18:36
I tested it with a real Windows 10 OS. Wine displays all icons correctly, but I think this hasn't much to do with this problem. Anyway, thank you!
