### ISSUE TITLE
Looping animation with collision:shape:radius/height causes Area2D not trigger

### ISSUE THREAD

**Issue by ivanskodje** [godotengine/godot#8325] opened 2017-04-08 20:34 UTC
**Operating system or device - Godot version:**
Linux Mint 64x
![image](https://cloud.githubusercontent.com/assets/6776092/24832088/4974d460-1ca8-11e7-9794-f9c74204a74a.png)

**Issue description:**
If you play a looping animation from the AnimationPlayer
![image](https://cloud.githubusercontent.com/assets/6776092/24832099/7387cd16-1ca8-11e7-9ec9-2de484e170b0.png)
![image](https://cloud.githubusercontent.com/assets/6776092/24832100/7e4a5912-1ca8-11e7-9936-182a42fb82ae.png)

Area2D does not register the player when it enters.
![image](https://cloud.githubusercontent.com/assets/6776092/24832119/b6ecc2dc-1ca8-11e7-9dbc-40e6fcd4f5e5.png)
![image](https://cloud.githubusercontent.com/assets/6776092/24832132/df710e98-1ca8-11e7-9757-5987fb9b2f11.png)

According to a test, it appears when you set either the (CapsuleShape) collision shape radius or height as a looping animation (or if it just runs on a long animation) Area2D does not register the body.
![image](https://cloud.githubusercontent.com/assets/6776092/24832173/f20ee736-1ca9-11e7-9878-ec2078da59db.png)

If I try to add the Shape itself, there is no problems. Only the radius and height appears to make the body invisible to the Area2D.

**Steps to reproduce:**
Create a similar scene:
![image](https://cloud.githubusercontent.com/assets/6776092/24832213/ead2bac8-1caa-11e7-90e3-905e29e284f4.png)

Create a script on Area2D and setup the signal.
![image](https://cloud.githubusercontent.com/assets/6776092/24832218/01b5ad5e-1cab-11e7-829a-c440076e425f.png)
![image](https://cloud.githubusercontent.com/assets/6776092/24832233/40e85878-1cab-11e7-9c83-aa85e847a799.png)

Create an animation that loops and autoruns:
![image](https://cloud.githubusercontent.com/assets/6776092/24832225/207631d2-1cab-11e7-89d4-fa70f43c047e.png)

Notice that the Area2D does **not** register the RigidBody2D as it passes.

**Comment by eon-s** [comment] 2017-04-08 21:20
You are animating the collision shape? remember that the CS is a helper and the CollisionObject has its own shape.

If you want to animate the real shape, you may need to export some variable to animate and change the shape value with the setter (you can update the CollisionShape at the same time).

Still not sure if detection will work, smoothly at least.

**Comment by bojidar-bg** [comment] 2017-04-15 07:00
Does it work if you use fixed-mode AnimationPlayer?

Also, note that the shape would be shared between all instances of the scene, since it is a Resource. Maybe it would start working if you duplicate it in _ready, or if you have only one instance?

**Comment by eon-s** [comment] 2017-04-15 16:13
@bojidar-bg using fixed happens too, and the effect manipulating the shape (using another variable) is the same, the new shape won't be used until you update the area position.

Adding a new track with the position, even without moving it, makes the area detect with the new shape size (like using set_pos).

Also happens using Tween.

**Comment by eon-s** [comment] 2018-03-09 23:32
Still affects Godot 3.0.2

The workaround in this case is to do `position = position` on the area when shape changes so the physics server becomes aware of the new shape.

I think shape changes should notify the owner, and the body set as "changed" to be checked again for collisions, this may solve many shape resizing bugs.

**Comment by vandalk** [comment] 2018-04-05 19:12
Thanks! I was struggling with this for almost two hours before I found this answer!

I'm still on Godot 2.1.4, and I was animating a ColisionShape2d inside an Area2d. It's a player projectile, a Laser that would cross the screen and stay active for around 2 seconds.

Its behavior was all over the place, as it killed the enemies half the time and half not. After I added `set_pos(get_pos()) ` to the "fixed_process" of the laser, it seems to be working 100% of the time now.

**Comment by eon-s** [comment] 2018-04-06 02:05
@vandalk on Godot 2, CollisionShape nodes are just editor helpers and you should not use them in game but modify the shape resource instead (on 3 are more active nodes).

The position change should be done on the CollisionObject (Area2D in this case).

**Comment by jackwilsdon** [comment] 2018-12-26 01:08
I can confirm this is still an issue in 3.0.6, but @eon-s's workaround seems to work reliably for me when using `_physics_process`;

```GDScript
func _physics_process():
	position = position
```

**Comment by akien-mga** [comment] 2020-01-16 22:02
Fixed by #33615.

**Closed by akien-mga** 2020-01-16 22:02 UTC
Labels: bug, topic:core, topic:physics

**Comment by securas** [comment] 2020-02-09 09:37
still seems to happen in 3.1.2

**Comment by bojidar-bg** [comment] 2020-02-09 10:46
It was never cherrypicked there. It should be fixed in 3.2.x, however.
