### ISSUE TITLE
PanoramaSky without a texture triggers error

### ISSUE THREAD

**Issue by oOo0oOo** [godotengine/godot#10541] opened 2017-08-22 12:25 UTC
**Operating system or device, Godot version:**

Ubuntu 14.04, current master branch (01d4ffd)

**Issue description:**

PanoramaSky without a loaded panorama texture displays an error in the editor.

**Steps to reproduce:**

1) Create new: WorldEnvironment & Environment
2) Background Mode: Sky
3) Create new: PanoramaSky

Error is displayed in editor console until a Panorama texture is selected / loaded (tested with .png):

`drivers/gles3/rasterizer_scene_gles3.cpp:2331 - Condition ' !tex ' is true.`

Error is displayed again if the texture is cleared later on.

**Comment by RodeoMcCabe** [comment] 2017-10-16 02:22
I can confirm this bug is still present.

**Comment by Jerome67000** [comment] 2017-10-25 18:20
I can confirm this bug too. I will try to make a fix :)

**Comment by Jerome67000** [comment] 2017-10-29 11:58
Hi,

Following the discussion in the PR, the texture associated with the `PanoramaSky` should never be null, mean the fix would be to prevent having a `PanoramaSky` without a texture.

What do you preffer to fix this problem ?
* Associate an empty `ImageTexture` to the `PanoramaSky` ?

**Comment by Jerome67000** [comment] 2017-10-29 12:02
Hi,

Following the discussion in the PR, the texture associated with the `PanoramaSky` should never be null, mean the fix would be to prevent having a `PanoramaSky` without a texture.

What do you preffer to fix this problem ?
* Associate an empty `ImageTexture` to the `PanoramaSky` ?
* Associate an `ImageTexture` with the default icon.png to the `PanoramaSky` ?
* Associate an `GradientTexture` to the `PanoramaSky` ?
* Other solutions are welcome

**Comment by akien-mga** [comment] 2017-10-29 12:04
Display an in-editor configuration warning as long as the PanoramaSky lacks a texture. See how it's done in collision objects which will show a warning as long as you don't have a collision shape; or popup dialogs which show a warning when made visible in the editor.

**Comment by matrem** [comment] 2017-11-26 14:46
As PanoramaSky is not a node but a resource, the shape is not a good example for warning, is there other example with resources with this configuration_warning mechanism?

**Comment by Jerome67000** [comment] 2017-12-23 10:03
Yeah good question, I'm still motivate to fix it if you show me the way...

**Comment by brainsick** [comment] 2018-01-06 18:31
Please don't use icon.png as a default ImageTexture; I'd rather not have the dependency in this use case:

```
extends SceneTree

func _initialize(): # MainLoop
	var viewport = get_root()
	
	var environment = Environment.new()
	environment.background_mode = Environment.BG_SKY
	
	# nice symmetry
	#environment.background_sky = ProceduralSky.new()
	#environment.background_sky = PanoramaSky.new()
	
	# but if a texture is required, then a texture is required
	var panorama_sky = PanoramaSky.new()
	panorama_sky.panorama = ImageTexture.new() # being discussed
	
	environment.background_sky = panorama_sky
	
	viewport.world.environment = environment
	
	var camera = Camera.new()
	
	var mesh_instance = MeshInstance.new()
	mesh_instance.mesh = CubeMesh.new()
	mesh_instance.transform.origin.z = -5
	
	camera.add_child(mesh_instance)
	
	viewport.add_child(camera)

# main test body
func _iteration(delta): # MainLoop
	quit()
todd@todd-ab28d3:~/repos/remote/brainsick-godot-tests/tests/qa$ time ~/Downloads/Godot3.0Beta2/Godot_v3.0-beta2_x11.64 -s issues/10541.gd 
No touch devices found
OpenGL ES 3.0 Renderer: AMD Radeon (TM) R9 Fury Series (AMD FIJI / DRM 3.18.0 / 4.13.0-21-generic, LLVM 5.0.0)
GLES3: max ubo light: 409
GLES3: max ubo reflections: 455, ubo size: 144
ARVR: Registered interface: Native mobile

real	0m1.124s
user	0m0.159s
sys	0m0.033s
```

**Comment by akien-mga** [comment] 2018-01-08 12:47
We have now entered release freeze for Godot 3.0 and want to focus only on release critical issues for that milestone. Therefore, we're moving this issue to the 3.1 milestone, though a fix may be made available for a 3.0.x maintenance release after it has been tested in the master branch during 3.1 development. If you consider that this issue is critical enough to warrant blocking the 3.0 release until fixed, please comment so that we can assess it more in-depth.

**Comment by brainsick** [comment] 2018-01-18 19:32
I recently had cause to revisit this for a project.  I'm glad that the current behavior is classified as a bug because errors should be reserved for unrecoverable situations.

In terms of a default, I am still in favor of some kind of gradient texture.  If you take the naive approach of setting the `PanoramaSky` panorama property to a `GradientTexture`, then set the `GradientTexture` gradient property to a `Gradient` you end up with a huge seam running along an edge of the scene.

For a default panorama sky gradient you would still want a sense of up and down so the gradient should run vertical instead of horizontal.  I couldn't figure out a way to rotate the texture while just gluing objects together in the Editor.  Of course you could rotate it with a shader, but at that point you might as well just create the gradient there too.

If we create such a gradient as an asset, I'd imagine it should look something like this:

![texture-panorama_gradient-4096x2048](https://user-images.githubusercontent.com/1111573/35117012-d1957b76-fc52-11e7-810f-402323aa8144.jpg)

Add a little texture and I think it pops a little more:

![texture-panorama_gradient_clouds-4096x2048](https://user-images.githubusercontent.com/1111573/35117022-db55d7dc-fc52-11e7-9e5b-dab5671d7c05.jpg)

For a Godot default, I'd imagine that blue would be more appropriate.

[panorama_gradient.xcf.zip](https://github.com/godotengine/godot/files/1644161/panorama_gradient.xcf.zip)

https://youtu.be/9NYABHYUsK0

**Comment by vnen** [comment] 2018-01-18 21:23
IMO a PanoramaSky without a texture should just not draw at all (not even attempt to). I find strange to add an arbitrary default, it stops looking like an actual problem. If it's just a placeholder, one can use a ProceduralSky instead.

**Comment by akien-mga** [comment] 2018-01-18 21:32
As I mentioned above:

> Display an in-editor configuration warning as long as the PanoramaSky lacks a texture.

That's all. We should not do any kind of magic. No Texture == misconfiguration, that's all.

**Comment by Einlander** [comment] 2018-02-06 08:59
This bug might have actually got worse. It will now infinitely print the error in the console. It will not stop until there is a panorama image selected or it is removed.

[panorama_bug.zip](https://github.com/godotengine/godot/files/1698379/panorama_bug.zip)

**Closed** 2018-02-24 00:25 UTC
Labels: bug, junior job, topic:rendering
