### ISSUE TITLE
Atlas texture displays whole index when read by a shader

### ISSUE THREAD

**Issue by bionick7** [godotengine/godot#70604] opened 2022-12-26 22:39 UTC
### Godot version

4.0 beta 10

### System information

Windows 10 RTX 2060

### Issue description

When read by a StandardMaterial3D or ShaderMaterial, AtlasTextures will display the whole atlas instead of their render regions. This happens in 3D and 2D.

### Steps to reproduce

- Create Sprite3D
- set the main texture to icon.svg or placeholder texture
- set override material the StandardMaterial and albedo_texture to an AtlasTexture

### Minimal reproduction project

[AtlasTextureBugMRP.zip](https://github.com/godotengine/godot/files/10304929/AtlasTextureBugMRP.zip)

**Comment by Calinou** [comment] 2022-12-26 22:55
Duplicate of https://github.com/godotengine/godot/issues/25895.

**Closed by Calinou** 2022-12-26 22:55 UTC

**Comment by bionick7** [comment] 2022-12-27 09:58
I am aware of #25895, but the reproduction steps don't work in 3.x, which is what that issue refers to, so there's something more going on here
