### ISSUE TITLE
Godot C# Class Inheritance Bug

### ISSUE THREAD

**Issue by JupiterRider** [godotengine/godot#38783] opened 2020-05-16 15:40 UTC
**Godot version:**
Godot_v3.2.2-beta2_mono_x11_64

**OS/device including version:**
OS: 5.6.13-arch1-1
Mono: 6.4.0.198-1
msbuild: 16.5.xamarinxplat.2020.02.20.11.54-1

**Issue description:**
If your class has the same name like a Godot node / Godot class, your game probably won't work correctly.

F.e.: `public class Spatial : Godot.Spatial`

**Minimal reproduction project:**
https://github.com/JupiterRider/ClassInheritanceBug

**Comment by TheDuriel** [comment] 2020-05-17 20:35
That seems obvious no?
Is your IDE not telling you that the name is illegal?

**Comment by neikeq** [comment] 2020-05-17 20:50
>your game probably won't work correctly.

What does this mean? Is there a particular error as a result of this?

**Comment by raymoo** [comment] 2020-05-20 10:19
>Is your IDE not telling you that the name is illegal?

I don't think it would, in C# you're allowed to have classes with the same name if they are in different namespaces.

**Comment by JupiterRider** [comment] 2020-05-21 14:22
> > your game probably won't work correctly.
> 
> What does this mean? Is there a particular error as a result of this?

Game starts, but infinite loading screen.

**Comment by JupiterRider** [comment] 2020-05-21 14:24
> That seems obvious no?
> Is your IDE not telling you that the name is illegal?

No. I created that class in Godot, by right clicking the node and adding a script.

**Comment by raulsntos** [comment] 2022-08-26 15:46
The MRP link is broken (the repo must've been removed) and I'm not able to reproduce this issue in v3.5.stable.mono.official [991bb6ac7].

Using the name of a Godot's class as your script class' name is valid in C# as long as they are in different namespaces, although it is discouraged.

I'll close this issue since I can't reproduce it, if anyone is able to reproduce this issue please open a new issue with a minimal reproduction project attached.

**Closed by raulsntos** 2022-08-26 15:46 UTC
Labels: bug, topic:dotnet
