### ISSUE TITLE
Memory Leak with Onion Skin On Windows

### ISSUE THREAD

**Issue by AinaSG** [godotengine/godot#20057] opened 2018-07-09 07:44 UTC
**Godot version:**

Replicated in both 3.0 and 3.0.4

**OS/device including version:**

Only replicated on Windows. @JFonS tried to do it on Linux and could not replicate

**Issue description:**

When using onion skin for animations, the memory used by Godot increases until taking all the memory available.

This may be gone with the refactored animation system.

**Steps to reproduce:**
1- Have an animationPlayer node animating an Sprite.
2- Activate Onion Skin Both For Past and Future.

With the task administrator, at this point, it can be seen Godot taking more and more memory.

**Minimal reproduction project:**

**Comment by akien-mga** [comment] 2018-07-22 16:02
CC @RandomShaper

**Comment by RandomShaper** [comment] 2018-07-22 18:18
I'll have a look.

**Comment by RandomShaper** [comment] 2018-07-23 10:36
I've tested on 3.0.5, not being able to reproduce the issue.

@AinaSG, would you try on 3.0.5? If you still get the issue, here I'd need your exact reproduction project.

**Comment by AinaSG** [comment] 2018-07-30 08:58
Ok, I'll try ASAP

**Comment by Calinou** [comment] 2020-06-07 20:56
Closing, as nobody has been able to reproduce this issue since 3.0.5. Please comment you can still reproduce this bug in Godot 3.2.1 or [3.2.2beta4](https://godotengine.org/article/dev-snapshot-godot-3-2-2-beta-4).

**Closed by Calinou** 2020-06-07 20:56 UTC
Labels: bug, topic:editor
