### ISSUE TITLE
CheckFeatureSupport on d3d12 requests DXGI_FORMAT_UNKNOWN instead of R8G8B8A8_UNORM

### ISSUE THREAD

**Issue by EIREXE** [godotengine/godot#87529] opened 2024-01-24 14:11 UTC
### Tested versions

current master

### System information

Current master, Linux, Proton

### Issue description

On vkd3d-proton when running the engine with the d3d12 renderer it seems to request DXGI_FORMAT_UNKNOWN, when in fact it wants to request R8G8B8A8_UNORM. I am not familiar with d3d12 but the issue is supposedly here:

> "https://github.com/godotengine/godot/blob/master/drivers/d3d12/rendering_device_driver_d3d12.cpp#L1592 it fails here, because dsv_support.Format is DXGI_FORMAT_UNKNOWN when querying for format R8G8B8A8_Unorm"

(shoutouts to @pixelcluster for the info)

### Steps to reproduce

Run the engine on vkd3d-proton with dx12 support enabled

### Minimal reproduction project (MRP)

Reproducible in the project manager

**Comment by Calinou** [comment] 2024-01-24 18:29
cc @RandomShaper

**Comment by clayjohn** [comment] 2024-01-24 18:37
Maybe it comes from this line https://github.com/godotengine/godot/blob/c6316bff65c92d4a9a4b06ca801082d431b35b37/drivers/d3d12/d3d12_context.cpp#L794

The swapchain is initialized to DXGI_FORMAT_R8G8B8A8_UNORM above:
https://github.com/godotengine/godot/blob/c6316bff65c92d4a9a4b06ca801082d431b35b37/drivers/d3d12/d3d12_context.cpp#L769

**Comment by RandomShaper** [comment] 2024-01-25 09:20
I haven't been able to find the relevant code in vkd3d-proton, but, working with the hypothesis it disallows checking for a null format, I've made #87570.

**Comment by pixelcluster** [comment] 2024-01-25 10:00
vkd3d-proton erroring out when getting a `CheckFeatureSupport` with `DXGI_FORMAT_UNKNOWN` is one thing, that is going to be fixed on the vkd3d-proton side already.

My original point was that it seemed like the format shouldn't be `DXGI_FORMAT_UNKNOWN` in the first place (because `texture_get_usages_supported_by_format` was called with `DATA_FORMAT_R8G8B8A8_UNORM`, at least if I read the logs correctly.)

**Comment by RandomShaper** [comment] 2024-01-25 11:00
> vkd3d-proton erroring out when getting a `CheckFeatureSupport` with `DXGI_FORMAT_UNKNOWN` is one thing, that is going to be fixed on the vkd3d-proton side already.

🆗

> My original point was that it seemed like the format shouldn't be `DXGI_FORMAT_UNKNOWN` in the first place (because `texture_get_usages_supported_by_format` was called with `DATA_FORMAT_R8G8B8A8_UNORM`, at least if I read the logs correctly.)

The problem is that the function maps a Godot `RenderingDevice` format to two DX formats: one for general usage and one for depth-stencil, and queries feature support for both. The call that fails is the second one, when it has mapped the format to its depth-stencil counterpart, which, for a regular format, turns out to be `DXGI_FORMAT_UNKNOWN`.

**Closed** 2024-02-12 12:48 UTC
Labels: bug, topic:rendering
