### ISSUE TITLE
Normal maps in tilemaps

### ISSUE THREAD

**Issue by Cube-Logic** [godotengine/godot#79791] opened 2023-07-22 14:29 UTC
### Godot version

4.1

### System information

Windows 11, RTX 4070 Ti, Forward+

### Issue description

The example below shows 2 identical textures affected by a directional light
Both have diffuse, normal, and specular maps
The top one (Sprite2D) is working properly
The bottom one (Tilemap) is not affected by any of the maps
![image](https://github.com/godotengine/godot/assets/85768334/df65978d-8064-4751-bb6d-cf3daea722aa)

### Steps to reproduce

Add a tilemap with a CanvasTexture and drop all of the relevant maps

### Minimal reproduction project

[Tilemap.zip](https://github.com/godotengine/godot/files/12136670/Tilemap.zip)

**Comment by Cube-Logic** [comment] 2023-07-22 14:30
Sorry, wrong screenshot
![Godot](https://github.com/godotengine/godot/assets/85768334/b2da73b0-ec4f-43fe-ace4-6a9e861c87d3)

**Comment by kleonc** [comment] 2023-07-22 16:16
Duplicate of #61832. Currently [CanvasTexture doesn't work with texture padding](https://github.com/godotengine/godot/issues/61832#issuecomment-1296140322).

**Closed by kleonc** 2023-07-22 16:16 UTC
