### ISSUE TITLE
Says class is not being used in script when it is

### ISSUE THREAD

**Issue by lincolnpepper** [godotengine/godot#25885] opened 2019-02-14 17:44 UTC
**Godot version:**
Godot 3.1 beta 1

**OS/device including version:**
Windows 10

**Issue description:**
I made a new project to test out classes (since somehow i had no idea classes were a thing in godot up until this point). I made a new class and made an array of that type of class in a script and ran a for loop to display parameters of the class which worked fine. But i got an error saying that i loaded the class but never used it, when i clearly did use it.
image: https://imgur.com/a/LalbAsM
Also, when looking to see if this was already an issue i found this: https://github.com/godotengine/godot/issues/23207 but i wasn't sure if it was the same problem or not, especially since people said that the error was supposed to be there, when in this case it's clearly not.
I think this is a problem any time you use the classes in an array or dictionary, but i'm not sure cause iv'e honestly not used them enough yet.

**Steps to reproduce:**
Create a new project
Create a new script class
Create a new scene with a script with a variable that loads the class
Create an array in _ready() with elements being new versions of that class

**Minimal reproduction project:**
[classes testing.zip](https://github.com/godotengine/godot/files/2866184/classes.testing.zip)

**Comment by akien-mga** [comment] 2019-02-14 18:21
Can you test with 3.1 beta 4?

**Comment by KoBeWi** [comment] 2019-04-01 18:22
Still happens on stable.

**Comment by isaacremnant** [comment] 2019-09-04 00:23
Looks like this was fixed on master, I can no longer reproduce the error with the attached project.

**Comment by KoBeWi** [comment] 2019-09-04 00:54
Yep, this no longer happens.

**Closed by KoBeWi** 2019-09-04 00:54 UTC
Labels: bug, topic:gdscript
