### ISSUE TITLE
RFC: split GDScript into dedicated repository, and as an individual project.

### ISSUE THREAD

**Issue by netroby** [godotengine/godot#34290] opened 2019-12-12 02:10 UTC
The most part of godot engine what i like, was the GDScript engine.

It similar python, which easy to read, easy to write. easy to maintain.

Is it possible to split it as an individual project? with it's own repository.

May it be use for embed in other place, not only inside the godotengine.

I read the core code of GDScript, look lean and clear, very impressive.

**Comment by groud** [comment] 2019-12-12 08:10
GDscript does make sense only in the scope of Godot, it's language feature are tightly linked to the engine. There is no point in splitting it from the Godot project.

**Comment by netroby** [comment] 2019-12-12 08:16
Seems it as an embed script language, Google bazel build also has one starlark language.

but GDScript looks better

**Comment by bojidar-bg** [comment] 2019-12-12 09:26
Duplicate of #7598?

**Comment by groud** [comment] 2019-12-12 09:33
> Duplicate of #7598?

Ah yes, this was already addressed. If you want to bring new arguments, please do it in #7598.

**Closed by groud** 2019-12-12 09:33 UTC
Labels: discussion, topic:gdscript
