### ISSUE TITLE
Exported custom Resource can be assigned any res type - no warning, and broken at runtime

### ISSUE THREAD

**Issue by Flavelius** [godotengine/godot#39499] opened 2020-06-13 08:10 UTC
**Godot version:**
3.2.1.stable.mono.official

**Issue description:**
Defined a custom Resource:
```
public class MyResource: Resource
{
  [Export] int testInt;
  public int TestInt => testInt;
}
```
then exported that resource in another class
```
public class MyNode: Node
{
  [Export] MyResource res;
}
```
it is possible to assign any resource type in the inspector.
No warning is printed and more importantly the resource can still be used at runtime acting like the declared type but dangerously and silently failing.
```
_Ready()
{
  GD.print(res.TestInt);
}
```
will print some random data
**Steps to reproduce:**
Run attached project

**Minimal reproduction project:**
[ResBug.zip](https://github.com/godotengine/godot/files/4774269/ResBug.zip)

**Comment by Ev1lbl0w** [comment] 2020-06-13 11:12
This is well known, take a look at #6763 and #26162

**Comment by Flavelius** [comment] 2020-06-13 15:02
The first two ones are a bit different. The last one seems to want to address the problem. 
The problem is not exporting the variables, that works somewhat, but that there's an underlying problem that the engine creates fake types that seem to randomly read memory

**Comment by Ev1lbl0w** [comment] 2020-06-13 18:18
I noticed now you're exporting a custom class. I don't think that's supposed to be possible ATM, at least in GDScript is not.

My advice for now would be to just use the base `Resource` for all export fields, and cast it to your custom type, until this feature is implemented. It's not pretty, but you're not alone in wanting this implemented, so it shouldn't be long before that happens.

I also found [this](#27470), which I think is also happening in your project.

**Comment by Flavelius** [comment] 2020-06-13 18:50
Yes, thanks. When looking into it i read that this is the recommended way for now. But i still think this should be looked into, as filtering the dropdown is only a partial solution covering up that underlying issue which should not be happening in the first place (there must be some error prone _magic_ going on behind the scenes)

**Comment by clayjohn** [comment] 2020-06-18 00:10
As @Ev1lbl0w pointed out, this is a duplicate of #6763 and #26162 and https://github.com/godotengine/godot-proposals/issues/18 please continue the discussion there. 

I am closing this issue in favour of https://github.com/godotengine/godot-proposals/issues/18. I am not dismissing your issue, you have pointed out a very annoying problem, but it is best for us to keep all discussions on a topic centralized.

**Closed by clayjohn** 2020-06-18 00:10 UTC

**Comment by Flavelius** [comment] 2021-03-13 18:50
I just wanted to keep this comment, that the issue is that there's no warning, no error and that it seems read some memory its not supposed to. I don't think it's in any way related to be able to export custom resources.
