### ISSUE TITLE
Fixed color picker crashes the engine on Linux

### ISSUE THREAD

**Issue by lonesurvivor** [godotengine/godot#7434] opened 2017-01-05 12:08 UTC
**Operating system or device - Godot version:**
Arch Linux 64 - Latest build, master branch

**Issue description** (what happened, and what was expected):
The fixed color picker (from pull request #7431) crashes the engine when being used:

> ERROR: get_child: Index p_index out of size (data.children.size()).
>    At: scene/main/node.cpp:1521.

This also happens immediately when I try to open an old project. A new empty poject can be opened, but it crashes as soon as I try to use the color picker (in project settings, for example). 

I reverted that commit, recompiled and it worked again. So it is definitely caused by it.

**Steps to reproduce:**
Create empty project. Open it. Go to project settings/Render. Click on the default background color to pick a new one.

**Link to minimal example project** (optional but very welcome):

**Comment by lonesurvivor** [comment] 2017-01-10 09:51
It seems to work now (no crash anymore). However, the color picker doesn't look like it should:

![Color Picker](http://i.imgur.com/kR88wEH.png)

And the crosshairs don't move at all when I'm clicking.

**Comment by MarianoGnu** [comment] 2017-01-15 00:27
Yep, i have been testing this and want to fix it, but for some reason drawing colored polygons (non textured) is not working at all so it's a different issue, not sure if i can fix it.

**Comment by nunodonato** [comment] 2017-04-12 11:04
I can't reproduce this crash (Linux, Godot 3.0 master), but I opened a new issue for the color picker glitch #8372

**Comment by MarianoGnu** [comment] 2017-04-16 17:45
I'm closing this issue since the glitch has moved to #8372

**Closed by MarianoGnu** 2017-04-16 17:45 UTC
Labels: bug, topic:core
