### ISSUE TITLE
Offline Debugging/Inspector

### ISSUE THREAD

**Issue by vonflyhighace2** [godotengine/godot#8064] opened 2017-03-18 02:00 UTC
**Operating system or device - Godot version:**
Windows 10 x64

**Issue description:**

No remote inspector support when offline. Not very helpful when your not connected.

**Steps to reproduce:**
turn of internet connection.

**Link to minimal example project:**

**Comment by bojidar-bg** [comment] 2017-03-18 08:09
@vonflyhighace2 Can you mention your Godot version?

**Comment by eon-s** [comment] 2017-03-18 12:37
Remote inspector works fine here, at least on 2.1.2, Win 10 x64.

Maybe your firewall is blocking Godot?

**Comment by Zylann** [comment] 2017-03-18 16:14
Maybe similar to #5828?

**Comment by vonflyhighace2** [comment] 2017-03-18 18:00
@bojidar-bg I'm on 2.1.2 official. Without a Internet connection I can never get the debugger to work. Is the remote debugger online only? Be weird if it was.

**Comment by efornara** [comment] 2017-03-27 23:56
See #7544 and #8179

**Comment by akien-mga** [comment] 2017-03-30 08:32
Duplicate of #7544.

**Closed by akien-mga** 2017-03-30 08:32 UTC
Labels: bug, needs testing, platform:windows, topic:editor
