### ISSUE TITLE
`Object::cast_to` works incorrectly for GDExtension custom classes

### ISSUE THREAD

**Issue by VanessB** [godotengine/godot#71332] opened 2023-01-13 14:38 UTC
### Godot version

v4.0.beta11.official

### System information

Debian GNU/Linux 11 (bullseye), Intel Core i3-8130U CPU, Mesa Intel UHD Graphics 620 (KBL GT2)

### Issue description

`Object::cast_to` does not work properly in case of custom GDExtension classes. For example, a `nullptr` is NOT returned in some cases where an object can not be casted to the desired type:

(Let `TestNode` inherit from `Node2D`, `some_node_2d` be of type `Node2D`)
```cpp
godot::Node::cast_to<TestNode>(some_node_2d) != nullptr;  // true, must be false, as Node2D can not be casted to TestNode.
```

From my experience, it seems that `cast_to` works with custom classes as if they are their base classes, as (in this example) I can cast all the classes inherited from `Node2D` to `TestNode`, and can not cast any other type (see steps to reproduce and reproduction project).

The GDScript, although, works fine with casting of custom classes, see example. C++ code for casting in-engine types also seems to work fine.

### Steps to reproduce

1. Create a custom GDExtension class (for example, `TestNode` inherited from `Node2D`).
2. Add the following code to its `_ready()` function:
```cpp
godot::UtilityFunctions::print("Casting children in GDExtension:");

godot::TypedArray<Node> children = get_children();
for (int64_t index = 0; index < children.size(); ++index)
{
    godot::UtilityFunctions::print("Next child:");
    godot::UtilityFunctions::print(children[index]);

    TestNode *child_as_test_node = godot::Node::cast_to<TestNode>(children[index]);

    godot::UtilityFunctions::print(child_as_test_node);

    godot::UtilityFunctions::print("");
}
```
3. Add an instance of `TestNode` to the tree.
4. Add some children of different types to it.
5. Run the project and see the results in the console.
6. Compare to the following GDScript:
```gdscript
extends Node2D

func _ready() -> void:
    print("Casting children in GDScript:")

    var children := get_children()
    for child in children:
        print("Next child:")
        print(child)
        print(child as TestNode)
        print()
```
7. The results are different.
```
Casting children in GDExtension:
Next child:
Node:<Node#26508001706>
<Object#null>

Next child:
Node2D:<Node2D#26524778921>
Node2D:<Node2D#26524778921>

Next child:
Node3D:<Node3D#26541556136>
<Object#null>

Next child:
Sprite2D:<Sprite2D#26558333351>
Sprite2D:<Sprite2D#26558333351>

Casting children in GDScript:
Next child:
Node:<Node#26591887781>
<null>

Next child:
Node2D:<Node2D#26608664996>
<null>

Next child:
Node3D:<Node3D#26625442211>
<null>

Next child:
Sprite2D:<Sprite2D#26642219375>
<null>
```

### Minimal reproduction project

[test_project.zip](https://github.com/godotengine/godot/files/10412377/test_project.zip)

**Comment by dsnopek** [comment] 2023-02-11 22:50
I've also encountered this in trying to port SG Physics 2D.

I can see why it's failing. In Object.hpp in godot-cpp, it's implemented like this:

```
template <class T>
T *Object::cast_to(Object *p_object) {
	if (p_object == nullptr) {
		return nullptr;
	}
	StringName class_name = T::get_class_static();
	GDExtensionObjectPtr casted = internal::gde_interface->object_cast_to(p_object->_owner, internal::gde_interface->classdb_get_class_tag(class_name._native_ptr()));
	if (casted == nullptr) {
		return nullptr;
	}
	return reinterpret_cast<T *>(internal::gde_interface->object_get_instance_binding(casted, internal::token, &T::___binding_callbacks));
```

The 2nd argument passed to `gde_interface->object_cast_to()` is the "class pointer" (ie. the return value of `::get_class_ptr_static()` for the class in the Godot engine. So, if you made a `TestNode` class in GDExtension that descends from `Node2D` (like in the description) this is the result of `Node2D::get_class_ptr_static()`.

Then over in `gdextension_interface.cpp` there's:

```
static GDExtensionObjectPtr gdextension_object_cast_to(GDExtensionConstObjectPtr p_object, void *p_class_tag) {
	if (!p_object) {
		return nullptr;
	}
	Object *o = (Object *)p_object;

	return o->is_class_ptr(p_class_tag) ? (GDExtensionObjectPtr)o : (GDExtensionObjectPtr) nullptr;
}
```

So, it's only checking if the object is the parent class - it's not checking anything about the specific class we're trying to cast to.

But I'm not sure on the right fix... We could add something like this to `Object::cast_to<T>()` in godot-cpp:

```
	if (!p_object->is_class(class_name)) {
		return nullptr;
	}
```

But this is (a) a much slower check and (b) makes the `gdextension_object_cast_to()` completely unnecessary, and would beg the question: why have that function at all?

Would it be better to try and fix `gdextension_object_cast_to()` to do all the necessary checks? But to do that, we'd have to pass some more data to `gdextension_object_cast_to()` which would mean breaking the ABI, and I'm not sure that's something we'll be able to do?

**Comment by akien-mga** [comment] 2023-02-11 22:54
GDExtension is still experimental, we can break the ABI if needed to make it work properly.

**Comment by dsnopek** [comment] 2023-02-11 23:32
> GDExtension is still experimental, we can break the ABI if needed to make it work properly.

That is really great to hear!

However, I did end up coming up with a (hopefully) decent solution entirely in godot-cpp:

https://github.com/godotengine/godot-cpp/pull/1037

**Comment by akien-mga** [comment] 2023-02-16 13:07
Duplicate of https://github.com/godotengine/godot-cpp/issues/995.

**Closed by akien-mga** 2023-02-16 13:07 UTC
Labels: bug, topic:gdextension
