### ISSUE TITLE
Importing assets from command line does not work with -e -q

### ISSUE THREAD

**Issue by mzoeller** [godotengine/godot#42746] opened 2020-10-12 16:36 UTC
**Godot version:**
3.2.3

**OS/device including version:**
Linux

**Issue description:** 
When running Godot from the command line with "-e -q" the editor quits before it has imported assets. This is required when using Godot in a CI environment where git repository does not contain .import folder.

**Steps to reproduce:**
Enter a godot project with missing ".import" folder and run "godot -e -q".

**Comment by jkb0o** [comment] 2020-10-12 16:58
Just tested with the headless editor (server build) for OSX and got the same result. The quick-fix solution is to create lightweight export preset with, for example, a single icon resource, name it `lightweight` and call `godot -e --export-pack lightweight ./lightweight.pck`. The editor will start, import all resources, export a lightweight pack, and exit.

**Comment by Calinou** [comment] 2020-10-12 16:58
Duplicate of https://github.com/godotengine/godot-proposals/issues/1362.

**Closed by Calinou** 2020-10-12 16:58 UTC

**Comment by mzoeller** [comment] 2020-10-12 18:25
Sorry, didn't find the pr. Thanks for the quick-fix solution @jkb0o.
