### ISSUE TITLE
Node objects that do not have viewable child in a gltf file are not imported

### ISSUE THREAD

**Issue by TheMoye** [godotengine/godot#34066] opened 2019-12-02 18:32 UTC
**Godot version:**
Godot 3.1.1

**OS/device including version:**
Windows 10 64bits

**Issue description:**
I'm looking to import a gltf file exported from Blender containing only Emptys.
The position and rotation of these emptys will be used to place the instances of a MultiMesh object.
Godot seems to import the resource, but when I want to open it it returns an error message : 
`Error when loading "ressource.gltf"`

This message appears in the Windows console : 
`ERROR: Failed loading resource: res://assets/3d_models/gltf/dummy_lambrissoll.gltf
   At: core/io/resource_loader.cpp:285`

**Steps to reproduce:**
Export a gltf file containing only an empty
Try to open it in Godot

**Minimal reproduction project:**

**Comment by FeralBytes** [comment] 2019-12-03 03:31
Possible duplicate of Issue #32363.

**Comment by TheMoye** [comment] 2019-12-03 06:31
> 
> 
> Possible duplicate of Issue #32363.

Hi FeralBytes,

The jeffres issue has nothing in common with mine : 
In his case the Empty is well taken into account (proof that the parser must read them well, even without children) but added to the scene in a bad way.
In mine, emptys are not added to the scene at all, whereas that's exactly what I expected : a Spatial node addition (only transformations interest me).

**Comment by fire** [comment] 2020-01-09 20:42
[this_is_an_empty_with_cube.glb.zip](https://github.com/godotengine/godot/files/4042408/this_is_an_empty_with_cube.glb.zip)
[this_is_an_empty.glb.zip](https://github.com/godotengine/godot/files/4042409/this_is_an_empty.glb.zip)

I've created test cases.

One is three empties which does not import.

The other is the same except with a cube mesh.

**Closed** 2021-01-14 18:48 UTC
Labels: bug, confirmed, topic:import
