### ISSUE TITLE
Sprite "crunch" when placed in certain positions on screen

### ISSUE THREAD

**Issue by Araraura** [godotengine/godot#84632] opened 2023-11-08 20:24 UTC
### Godot version

v4.2.beta5.official [4c96e9676]

### System information

Godot v4.2.beta5 - Windows 10.0.22621 - Vulkan (Forward+) - dedicated AMD Radeon RX 7900 XTX (Advanced Micro Devices, Inc.; 31.0.22023.1014) - AMD Ryzen 9 7950X3D 16-Core Processor (32 Threads)

### Issue description

In 4.2, there is an issue mostly visible on pixel art games with small resolutions that scale up to larger screens. While the game is running, moving sprites to certain places in the screen will cause the sprites to appear uneven or "crunched", and it's usually more noticeable if the sprite is animated.

![example](https://github.com/godotengine/godot/assets/25017422/2f7876e9-4391-454c-a995-a7b936104c76)

Window settings:
![image](https://github.com/godotengine/godot/assets/25017422/b48644b3-4766-4442-8182-d490a93e815f)

This seems to happen when moving the position of the sprite to X.5.
This happens in all 3 renderers.
This issue does not occur in Godot 4.1.3.
This issue occurs as early as 4.2 dev1.

Note: I'm using a 4K monitor with Windows scaled up to 175%.

### Steps to reproduce

1. Download the reproduction project
2. Open the project
3. Run the game
4. If the issue doesn't immediately show itself, slightly moving the character to the left/right a few times should trigger it.

### Minimal reproduction project

[SpriteCrunchIssue.zip](https://github.com/godotengine/godot/files/13301032/SpriteCrunchIssue.zip)

**Comment by AThousandShips** [comment] 2023-11-08 20:29
This is due to sampling issues and non-pixel positions, does this go away if you enable `rendering/2d/snap/snap_2d_transforms_to_pixel`?

**Comment by Araraura** [comment] 2023-11-08 22:28
> > This seems to happen when moving the position of the sprite to X.5
> 
> This is due to sampling issues and non-pixel positions, does this go away if you enable `rendering/2d/snap/snap_2d_transforms_to_pixel`?
> 
> I'd say this is largely hard to avoid due to rendering and sampling

This specific issue disappears with this setting, but it also introduces a lot of different ones.
In this project specifically the character sprite will hover above the ground, movement looks choppy, etc.

**Comment by Calinou** [comment] 2023-11-10 11:05
- Related to https://github.com/godotengine/godot-proposals/issues/6389.

Can you try following the same steps on previous 4.2 dev/betas? You can download them [here](https://downloads.tuxfamily.org/godotengine/4.2/).

**Comment by pinghetto** [comment] 2023-11-15 10:36
I managed to fix your issue simply changing Project Settings/Display/Window/Stretch/Mode from "viewport" to "canvas_item", take a try. 😉

**Comment by Araraura** [comment] 2023-11-15 11:44
> I managed to fix your issue simply changing Project Settings/Display/Window/Stretch/Mode from "viewport" to "canvas_item", take a try. 😉 PS: I fixed using Godot 4.2b6

This doesn't seem to be a complete fix. At certain locations, the pixels of the sprite wobble:
![gif](https://github.com/godotengine/godot/assets/25017422/8f6c8477-585f-4d14-b039-0512ed192df6)

**Comment by Gnumaru** [comment] 2023-11-26 08:03
@Araraura Try this: Ensure that your spritesheet texture has even dimensions (like 48x16 instead of 49x17) and that each frame of animation also has even dimensions (like each frame having 16x16 instead of 16.333.x17). As a last resort, you could set the centered property to false and see if it makes any difference.

**Comment by adamscott** [comment] 2023-12-20 19:08
I could reproduce the "issue" on Godot 3.x, when the camera is at 1x and when I deactivate `rendering/2d/snapping/use_gpu_pixel_snap`.

[Capture vidéo du 2023-12-20 13-58-23.webm](https://github.com/godotengine/godot/assets/270928/f855648b-8338-4807-b6ac-f2d07bd7fd13)

[SpriteCrunchIssueGodot3.zip](https://github.com/godotengine/godot/files/13731209/SpriteCrunchIssueGodot3.zip)

@AThousandShips is pretty spot on with the issue at hand:

> > This seems to happen when moving the position of the sprite to X.5
> 
> This is due to sampling issues and non-pixel positions, does this go away if you enable `rendering/2d/snap/snap_2d_transforms_to_pixel`?
> 
> I'd say this is largely hard to avoid due to rendering and sampling

The only difference here between Godot 3.x and Godot 4.x, it seems, is the order of operations. It appears like that Godot 3 scales from `(0,0)`, then applies the correctly scaled sprite into the canvas, offsetting it by half a pixel.

Godot 4 instead positions the sprite first at half a pixel, then scales the result. Hence the weird sprite state.

@clayjohn, does something ring you a bell?

**Comment by akien-mga** [comment] 2024-02-15 17:59
Fixed by #87297.

**Closed by akien-mga** 2024-02-15 17:59 UTC
Labels: discussion, topic:rendering, needs testing, topic:2d
