### ISSUE TITLE
Theme Editor default preview bleeding out with "Expand Margin"

### ISSUE THREAD

**Issue by shafnaz** [godotengine/godot#60155] opened 2022-04-11 20:20 UTC
### Godot version

3.4.4

### System information

Windows 10

### Issue description

Hi Guys,

The Godot theme has this issue when using the "Expand Margin" in a style box

![image](https://user-images.githubusercontent.com/37254287/162824874-e2469c56-9b35-468a-b6a3-f589fd3c6b09.png)
![image](https://user-images.githubusercontent.com/37254287/162824558-605051be-1762-4ebc-a383-7ddd33bfe9d8.png)

![image](https://user-images.githubusercontent.com/37254287/162824951-141efada-07ba-4d16-b40a-347bc3982941.png)
![image](https://user-images.githubusercontent.com/37254287/162824973-ab610550-25e7-402a-a22f-41a5bc2adb62.png)

### Steps to reproduce

New theme. jump into the theme editor
create a button style, add a style box to that button
Adjust the "Expand Margin"

**Comment by Calinou** [comment] 2022-04-11 21:37
I think this is by design. Expand Margin does not affect the *space* taken by a control (or its clickable area). It's only a visual change which acts as a padding for the StyleBoxFlat.

**Comment by shafnaz** [comment] 2022-04-12 01:10
Alright, but shouldn't the elements around it move, just like "Content Margin"?

**Comment by fire-forge** [comment] 2022-04-12 01:21
This is exactly what Expand Margin is supposed to do. It's even stated in the docs for the 4 `expand_margin_` properties. Content Margin is what you're looking for if you want the nodes to increase size with the StyleBox.

**Comment by YuriSizov** [comment] 2022-08-04 16:17
I guess this should be closed as not a bug then.

**Closed by YuriSizov** 2022-08-04 16:17 UTC
Labels: topic:gui
