### ISSUE TITLE
GDScript 2.0: Error "Nonexistent function in base" only on iOS exports 

### ISSUE THREAD

**Issue by keeganstothert** [godotengine/godot#63089] opened 2022-07-16 23:30 UTC
### Godot version

4.0.dev ( 2c11e6d9e)

### System information

Mac os 12.4, xcode 13.4.1, Apple silicon m1 max

### Issue description

I get the following error emitting a signal from a singleton in a callback.

Invalid call. Nonexistent function 'emit_signal' in base 'Node ()'.

```
func _ready():
    button_up.connect(func(): UISignals.emit_signal("transition_scene_to", navigate_to))
```

### Steps to reproduce

Attempt to emit a signal from a singleton inside a callback. Works in editor but fails on ios build

### Minimal reproduction project

[game.zip](https://github.com/godotengine/godot/files/9126780/game.zip)

**Comment by Calinou** [comment] 2022-07-16 23:45
Does it work when exporting the project to macOS?

**Comment by DavidMag** [comment] 2022-08-19 10:20
Probably same issue I'm as this https://github.com/godotengine/godot/issues/64508

I got the same issue but were able to work around the specific case of `connect()` by instead using this `my_object.my_signal.connect(my_method)` instead of `my_object.connect("my_signal", my_method)`

**Comment by DavidMag** [comment] 2022-08-23 21:47
Did some testing and the issue seems to be introduced between alpha 6 and 7 and my hypothesis that it's only base classes in some regards seems to be correct.

Remade the test scene to this, and when broken the label which checks "is Object" doesn't work at all in alpha 7 and newer.
<img width="624" alt="image" src="https://user-images.githubusercontent.com/22000931/186272267-ab86f6c5-a696-42a5-878d-d098b5200722.png">

The issue should be somewhere in here 
https://github.com/godotengine/godot/compare/e4f0fc50f79336cf76beec40e5e8e5164b288714...3e9ead05f2e87e46b5982cc9a140e172ee98c227

**Comment by michaldev** [comment] 2022-09-13 22:36
I have the same problem on android. On desktop works good. I have custom signals, connected to methods by Godot editor gui.

I tried to recreate this on a clean design but unfortunately it works fine.

**Comment by michaldev** [comment] 2022-09-26 13:32
When I changed from load and preload to ResourceLoader.load - works good on all platforms.

**Comment by ualac** [comment] 2022-10-29 06:12
I was hitting a similar issue with iOS exports with the Godot 4.0betas, and have found a code workaround, but I'm not clued up enough with the engine to know why this is only a problem in the iOS exported code, versus all the other platforms. 

I believe this all stems from the string table not being initialized before it's attempting to be used, since the first issues that appear when an iOS build is run are errors thrown from StringName about it not being configured. 

```
USER ERROR: Condition "!configured" is true.
    at: StringName (core/string/string_name.cpp:327)
```
If it got past that it would also throw warnings about Classes already having methods with some name, or not being able to obtain parent classes such as RefCounted etc.  

The first of these errors comes from within the OS singleton initialization (I guess it's OS_IOS in the iOS case.) So as a test I made a call to configure the StringName table prior to Main calling the initialization.

so in https://github.com/godotengine/godot/blob/master/main/main.cpp#L431 adding a call to `StringName::setup();` before the call to `OS::get_singleton()->initialize();` makes all these class related issues disappear when running as iOS builds. 

I've tested exports with a custom godot build with that one change and it seemed to address all the issues I had come across, the repro cases included on this issue, and https://github.com/godotengine/godot/issues/64508 and https://github.com/godotengine/godot/issues/64509

**Comment by DavidMag** [comment] 2022-11-04 18:10
@ualac 
Hi, nice work!
So this is not my call by any means but if you think that you have a viable solution I think you should open a PR with the fix. 🙌 🌟

**Comment by ualac** [comment] 2022-11-28 01:28
I meant to follow up with this with some more information, and I was reminded to do that given it's still an issue with the lastest beta6. 

The cause of this problem appears to be the call to `set_user_data_dir()` here https://github.com/godotengine/godot/blob/4a82d71d7345d0dde4da2816fd489da1c303f580/platform/ios/os_ios.mm#L134
The issue is due to that function making use of DirAccess which was made reference counted a few months back. When this call is made in the `OS_IOS::initialize_core` function none of the supporting things needed for ref counting appear to be setup eg. StringName etc., since that happens later during `Main::setup`, after this OS initialization has been done.  https://github.com/godotengine/godot/blob/4a82d71d7345d0dde4da2816fd489da1c303f580/main/main.cpp#L637

It appears someone was aware of this problem as there's an older comment in the OS_IOS constructor: 
`	// can't call set_data_dir from here, since it requires DirAccess
	// which is initialized in initialize_core
	user_data_dir = p_data_dir;`
but that has not been adhered to, or more likely the author of the ref counting changes with DirAccess was not aware this was being called so early in this platform's initialization. 

I've just tested removing the `set_user_data_dir()` line and exports to iOS are now working correctly, and not throwing the RefCounted and StringName errors that beta6 exports do, but I suspect there's likely a good reason for this call to be here.

**Comment by DavidMag** [comment] 2022-11-28 07:24
Found this PR, seems related. Could it be solved by this?
https://github.com/godotengine/godot/pull/68740

**Comment by bruvzg** [comment] 2022-11-29 08:46
I can't reproduce it with the current master (checked both debug and release templates).

**Comment by vnen** [comment] 2022-12-30 17:52
I cannot reproduce this either, it was likely fixed in the meantime.

**Closed by vnen** 2022-12-30 17:52 UTC
Labels: bug, platform:ios, topic:gdscript, topic:export
