### ISSUE TITLE
Godot 3.3.3 crashes with ERR_PARSE_ERROR when editing GDScript from VS Code

### ISSUE THREAD

**Issue by paul-marechal** [godotengine/godot#53096] opened 2021-09-26 17:57 UTC
### Godot version

3.3.3

### System information

Windows 10

### Issue description

Godot 3.3.3 crashes with ERR_PARSE_ERROR when editing GDScript from VS Code.

The crash happens when you are editing a line and are not done typing it fully.

### Steps to reproduce

Create node in a scene an attach the following script.

Then open the script in VS Code and make sure it is connected to Godot.

Adding a character on line 3 will crash Godot.

```gdscript
extends Node

export(NodePath) |<-- # Put cursor here in VS Code and type any character, Godot will crash

# Called when the node enters the scene tree for the first time.
func _ready():
    pass # Replace with function body.


# Called every frame. 'delta' is the elapsed time since the previous frame.
#func _process(delta):
#    pass
```

### Minimal reproduction project

[godot_3.3.3_parse_error.zip](https://github.com/godotengine/godot/files/7231930/godot_3.3.3_parse_error.zip)

**Comment by pycbouh** [comment] 2021-09-27 13:43
Duplicate of https://github.com/godotengine/godot/issues/51923

**Closed by pycbouh** 2021-09-27 13:43 UTC
