### ISSUE TITLE
mouse_entered and mouse_exited signals on Window do not work for embedded windows

### ISSUE THREAD

**Issue by CombustibleLemonade** [godotengine/godot#75856] opened 2023-04-09 15:50 UTC
### Godot version

stable-4.0 - 4.0.x stable branch (steam version)

### System information

Ubuntu 22.04.2 LTS 

### Issue description

mouse_entered and mouse_exited do not emit when the window is an embedded window. 

The issue seems to be specific to embedded windows. For native windows, the signal did emit and call the function it was connected to.

### Steps to reproduce

Create a scene with an embedded window that does not cover the entire screen. Create a script that connects the signals mouse_entered and mouse_exited to a function which prints something. Run the scene, and move the mouse in and out of the window area. Nothing is printed. 

### Minimal reproduction project

[WindowSignalBugReproduction.zip](https://github.com/godotengine/godot/files/11185789/WindowSignalBugReproduction.zip)

**Comment by Sauermann** [comment] 2023-04-10 20:03
Duplicate of #66293
Is addressed by #67791

**Comment by KoBeWi** [comment] 2023-05-25 21:36
Closing as duplicate.

**Closed by KoBeWi** 2023-05-25 21:36 UTC
