### ISSUE TITLE
overloaded functions bindings to gdScript

### ISSUE THREAD

**Issue by toger5** [godotengine/godot#8987] opened 2017-05-29 19:07 UTC
overloaded functions would be nice for the GDScript api.

**how it currently works**
If I bind multiple function with the same name and different parameter footprints, I just overwrite the previous binding.
 
use case example: #8981

**Comment by karroffel** [comment] 2017-05-29 19:08
I think that will be very hard as GDScript is dynamically typed.

**Comment by toger5** [comment] 2017-05-29 19:10
Okay I see. Very hard or almost impossible (if so you can close it. It would just be a fancy (aka not important) thing to have anyways)

**Comment by toger5** [comment] 2017-05-29 19:13
Oh I wasn't even aware that overloaded functions are not supported in gdScript itself (I though just bindings don't work)
And I also wouldn't know how it should work with being dynamically typed.

**Comment by raymoo** [comment] 2017-05-30 03:02
You could dispatch based on the arity of the function. You could also make it so that functions can declare the types they take as parameters and dispatch based on that.

**Comment by vnen** [comment] 2017-05-31 00:42
An arity check could work, since GDSscript is quite strict about it when calling a function (except for a few built-in functions which accepts any number of arguments).

However, type-checking for the dispatch would likely cause many cases of unexpected behavior. Also, how would you choose if the actual type does not match any of the declarations?

**Comment by raymoo** [comment] 2017-05-31 01:37
You could have a "generic" function to fall back to (when it makes sense to have one), or just give an error if nothing matches.

**Comment by hubbyist** [comment] 2017-05-31 06:39
If implemented default behaviour must be giving error about "function name defined but no matching argument list found" I think. Otherwise finding bugs will not be easy.

Since fallback functions are functions anyway trying to supply them by default for each function will make things complex (Which one is the base and which ones are the overrides?), so developer must be responsible to decide if it is acceptable to supply one, IMO.

**Comment by raymoo** [comment] 2017-05-31 08:37
There is actually only one sensible way to decide which functions is the fallback: a function is a fallback of another one if each parameter is either the same type as the non-fallback function, or is an unspecified type. Also at least one parameter that has its type specified in the non-fallback function should be unspecified in the fallback.

You can guarantee that the most specific function will be used if you sort the overloaded functions by number of parameter types and then check each one for a match, starting with the one with the most specified types and ending with the one with the least. A "fallback" function will always have less defined parameter types than the functions it is a fallback for, so will be checked later.

**Comment by raymoo** [comment] 2017-05-31 08:39
I spoke too soon actually, I thought of an ambiguous case. If you have func(int, string), both func(unspecified, string) and func(int, unspecified) would be valid fallbacks, and it's ambiguous which should be chosen since neither is a generalization of the other.

**Comment by toger5** [comment] 2017-05-31 09:17
How much additional work would it be to add typehints. So dwvelopers can make overloaded fucntions more specific by defining the type of each parameter.
I think errors when no function is found is the best solution.

**Comment by kubecz3k** [comment] 2018-04-19 17:48
I'm closing this one since there was no new interest in the discussion for 11 months... 
In 3.1 we should have optional static typing, let's see first how it will be implemented and improve from that point.

**Closed by kubecz3k** 2018-04-19 17:48 UTC
Labels: discussion, feature proposal, topic:gdscript

**Comment by aaronfranke** [comment] 2018-08-24 00:56
@vnen Would function overloading be feasible to have in GDScript? Might be worth re-evalutating now that you've done all that work on Typed GDScript and warnings.

**Comment by vnen** [comment] 2018-08-24 01:57
@aaronfranke the problem is that typing is optional, so it's not always possible to detect which function to call at compile time. Using a runtime dispatch would be quite bad for performance and could lead to ambiguities as discussed previously. Again, it's feasible if the distinction is only in arity and not in types, but I don't think it's worth it

If it needs to work with bindings as well (which was the original topic), it would need a big change in the core, then it would be even less worthy.

**Comment by ivanskodje** [comment] 2021-04-05 20:43
@akien-mga 

Hello from 2021! 💯 
Can we do something about this now that we have static typing support in GDScript? :) 
I am dying to reuse function names with different parameters `func uri(var uri: String)`, `func uri(var uriBuilder: UriBuilder)`

**Comment by Calinou** [comment] 2021-04-05 21:42
> Can we do something about this now that we have static typing support in GDScript? :)
> I am dying to reuse function names with different parameters `func uri(var uri: String)`, `func uri(var uriBuilder: UriBuilder)`

As far as I know, there are still no plans.

PS: Please don't ping project maintainers without a good reason – their inbox is chock-full already :slightly_smiling_face:

**Comment by raymoo** [comment] 2021-04-09 04:21
By the way, Common Lisp has had this feature forever (as multiple dispatch methods), so anyone looking into implementing this could check what CL implementations do to improve performance.
