### ISSUE TITLE
CSGSpheres have lighting issues even with Smooth Faces turned on

### ISSUE THREAD

**Issue by LikeLakers2** [godotengine/godot#21645] opened 2018-09-01 05:49 UTC
**Godot version:**
v3.1.dev.calinou.5df9109 (from https://hugo.pro/projects/godot-builds/)

**OS/device including version:**
Windows 10 Home v1803 (April 2018 update) x64
Nvidia GTX 1060 6GB (Driver 399.07)

**Issue description:**
Even with the Smooth Faces option turned on, a CSGSphere has issues with shadows cropping up at the bottom of various vertexes. (It's especially noticable on the bottom half of the sphere -- look for the slight discolorations) 

<details><summary>Example: Radius of 5, Radial Segments at 32, and Rings at 16</summary>

![image](https://user-images.githubusercontent.com/1008889/44942548-f5bd2400-ad81-11e8-8234-ebe78e6a9db1.png)
</details>
<details><summary>Example: Radius of 5, Radial Segments at 64, and Rings at 32</summary>

![image](https://user-images.githubusercontent.com/1008889/44942534-5c8e0d80-ad81-11e8-98b2-495e1770e35c.png)
</details>

<br/>This occurs on all sides of a CSGSphere, and the problem only worsens with a light source, such as a OmniLight (Notice how the light does not look smooth at all, especially along the edges):
<details><summary>CSGSphere (Radial Segments 32/Rings 16) with an OmniLight shining on it</summary>

![image](https://user-images.githubusercontent.com/1008889/44942595-484b1000-ad83-11e8-9ee5-c41c1cd08edf.png)
</details>
<details><summary>CSGSphere (Radial Segments 64/Rings 32) with an OmniLight shining on it</summary>

![image](https://user-images.githubusercontent.com/1008889/44942630-7c730080-ad84-11e8-811e-1d2f8b240911.png)
</details>

<br/>Neither of these lighting problems occur with a SphereMesh under a MeshInstance:
<details><summary>SphereMesh (Radius 5, Height 10, Radial Segments 64, Rings 32) with that same OmniLight</summary>

![image](https://user-images.githubusercontent.com/1008889/44942639-94e31b00-ad84-11e8-9516-0a85e0d9895a.png)
</details>

<br/>

**Steps to reproduce:**
1. Create a CSGSphere.
2. (Optional, but makes it easier to see the issue) Set Radius to 5, Radial Segments to 32, and Rings to 16
3. Notice the many shaded parts of the sphere.

OR

1. Open the minimal reproduction project below
2. Toggle the visibilities on SphereMesh, CSGSphere32-16, or CSGSphere64-32 (the numbers represent the Radial Segments and Rings settings, respectively) to see what happens with each sphere -- notice that the CSGSpheres are affected but not the SphereMesh
3. The OmniLight and Camera nodes are provided so you can replicate for yourself the images included with this issue

**Minimal reproduction project:**
[CSG Lighting Issues.zip](https://github.com/godotengine/godot/files/2342095/CSG.Lighting.Issues.zip)

**Comment by LikeLakers2** [comment] 2018-09-01 09:00
@Chaosus Any particular reason for the enhancement tag? It seems more like a rendering bug to me.

**Comment by LikeLakers2** [comment] 2018-09-01 21:10
Adding a blank Environment to a WorldEnvironment node got me these, which help to demonstrate how the issue worsens with a light source, in this case an OmniLight:

<details><summary>Dark CSGSphere32-16 with OmniLight</summary>

![image](https://user-images.githubusercontent.com/1008889/44949935-bf2aec00-ae09-11e8-8c87-a49d5620fe30.png)
</details>
<details><summary>Dark CSGSphere64-32 with OmniLight</summary>

![image](https://user-images.githubusercontent.com/1008889/44949938-d1a52580-ae09-11e8-9570-aee93e7989c0.png)
</details>
<details><summary>Dark SphereMesh with OmniLight</summary>

![image](https://user-images.githubusercontent.com/1008889/44949942-eda8c700-ae09-11e8-8a64-09f438e76c5b.png)
</details>

**Comment by reduz** [comment] 2019-01-17 20:15
Not urgent for 3.1, kicking back.

**Comment by clayjohn** [comment] 2019-12-15 17:55
Looks like this was fixed sometime in the last year. Cant reproduce in 3.2 beta. So closing.

**Closed by clayjohn** 2019-12-15 17:55 UTC
Labels: bug, topic:rendering
