### ISSUE TITLE
Unforseen Subsurf Scatter issue

### ISSUE THREAD

**Issue by NoGodDamnName** [godotengine/godot#10728] opened 2017-08-28 16:43 UTC
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Manjaro Linux 64-bit on Nvidia GTX 660 Ti (3GB VRAM) using Godot 3.0 latest pull request.

**Issue description:**
Ever since reduz's subsurf scatter fixes in  b3ff7ca , everytime i try fire up the material tester demo to check on the cheese the editor's entire viewport turns white.

**Steps to reproduce:**
I don't know if it's just me, but try looking at the cheese.

**Link to minimal example project:**
![deepinscreenshot_select-area_20170828123513](https://user-images.githubusercontent.com/28677151/29783418-564b695a-8bee-11e7-8975-ebf59ed7cb24.png)

**Comment by djrm** [comment] 2017-08-28 16:44
duplicate of #10696

**Comment by NoGodDamnName** [comment] 2017-08-28 16:47
You can purge this issue then.

**Closed** 2017-08-28 16:58 UTC
