### ISSUE TITLE
GDScript 2.0: Enums do not allow bitshifted values.

### ISSUE THREAD

**Issue by DarkKilauea** [godotengine/godot#41184] opened 2020-08-11 05:12 UTC
**Godot version:**
Godot Engine v4.0.dev.custom_build.a32b427f9

**OS/device including version:**
Windows 10 (64-bit)

**Issue description:**
Enumerations do not allow bitshifted values to be assigned to members.  This was something that could be done in version 3.2.2.

``` gdscript

extends Node

enum Test {
	None = 0,
	First = 1 << 0, #Error is shown here
	Second = 1 << 1,
	Third = 1 << 2
}

# Called when the node enters the scene tree for the first time.
func _ready():
	pass # Replace with function body.

```

The error shown is; `error(5,15): Expected closing "}" for enum.`

**Steps to reproduce:**
Added the above script to a project.

**Minimal reproduction project:**
[TestGDScript2_enum_bitshift.zip](https://github.com/godotengine/godot/files/5054856/TestGDScript2_enum_bitshift.zip)

**Comment by ThakeeNathees** [comment] 2020-08-11 08:00
duplicate of #41017 and not only bitshifted values everything other than integer literals.

**Closed** 2020-08-11 09:33 UTC
Labels: bug, regression, topic:gdscript
