### ISSUE TITLE
Saving any scene causes crash

### ISSUE THREAD

**Issue by zer0problem** [godotengine/godot#8988] opened 2017-05-29 19:07 UTC
Windows 8 - Godot version: Master b3c6d99

Crash when attempting to save a scene.

1) Start any project
2) change or create a scene
3) try to save it (this is followed by the windows prompt "Godot Engine Editor has stopped working")

https://hastebin.com/xeyofubaqi.css <- stack callback

**Comment by MrMaidx** [comment] 2017-05-29 19:15
I can confirm this on Manjaro 17.0.1 - kernel 4.11.

**Comment by karroffel** [comment] 2017-05-29 19:24
Can confirm this too on Antergos.

**Comment by groud** [comment] 2017-05-29 19:32
Also on Archlinux 4.9.11-1

**Comment by groud** [comment] 2017-05-29 19:38
Got this log too when crashing:
ERROR: environment_set_tonemap: Condition ' !env ' is true.
   At: drivers/gles3/rasterizer_scene_gles3.cpp:923.
ERROR: _load: Invalid tag in doc file: InputEvent
   At: editor/doc/doc_data.cpp:880.
ERROR: move_child: Invalid new child position: 2
   At: scene/main/node.cpp:318.
ERROR: get_edited_scene_root: Index current_edited_scene out of size (edited_scene.size()).
   At: editor/editor_data.cpp:600.
ERROR: environment_set_tonemap: Condition ' !env ' is true.
   At: drivers/gles3/rasterizer_scene_gles3.cpp:923.
ERROR: move_child: Invalid new child position: 2
   At: scene/main/node.cpp:318.
ERROR: environment_set_tonemap: Condition ' !env ' is true.
   At: drivers/gles3/rasterizer_scene_gles3.cpp:923.

**Comment by Hinsbart** [comment] 2017-05-29 20:03
Seems to be because `get_scene_root()->get_world()` is a null pointer here: https://github.com/godotengine/godot/blob/master/editor/editor_node.cpp#L1383

**Comment by groud** [comment] 2017-05-29 20:19
Works when get_world() is replaced by find_world(), seems ok to me from the following code.
I'll create a PR for that.

**Comment by ficoos** [comment] 2017-05-29 20:41
#8993 fixes it for me

**Comment by groud** [comment] 2017-05-29 20:46
I guess @reduz (the modifying commit author) should have a look to it. :)

**Comment by suptoasty** [comment] 2017-05-29 21:07
Problem on Linux Mint 18.1 kernel 4.10.0-14-generic as well.

**Comment by reduz** [comment] 2017-05-29 21:29
fixed, wait a bit until i commit what i'm working on, apologies

**Comment by groud** [comment] 2017-05-30 14:32
It seems like the problem is fixed since your last commit. Can others confirm ?

**Comment by nunodonato** [comment] 2017-05-30 14:44
yes

**Comment by groud** [comment] 2017-05-30 14:47
Well, I guess we can close this issue, #8993 and #8991. :)

**Closed** 2017-05-30 14:51 UTC
Labels: bug, confirmed, topic:core
