### ISSUE TITLE
Add an option to open files with exported games

### ISSUE THREAD

**Issue by MattUV** [godotengine/godot#23744] opened 2018-11-16 12:10 UTC
**Feature request**

**OS I use : Windows 10**
Hello,
When you export a game, you cannot open files with it
![bug open](https://user-images.githubusercontent.com/13215043/48620332-0dc73b80-e9a0-11e8-86f8-af9d684fd25a.png)

When you use a file path as an argument, godot tries to load the file,  and if it is not a *.tscn or a "project.godot", it throws this error  
<pre>ERROR: No loader found for resource: C:/Users/matth/Documents/Anglais/file.txt
   At: core/io/resource_loader.cpp:186</pre>
Then it quits without even loading the code

The problem is that Godot has an API to be used by command line
<pre>Usage: C:\Users\matth\Documents\Anglais\Cloze 0.2.exe [options] [path to scene or 'project.godot' file]</pre>

That is convenient to be used in the editor, but not so much for an exported project...
As the program closes, you don't have the opportunity to use `OS.get_cmdline_args()`

I think it might be a good thing to be able to override a little bit the command line API for exported projects.

**Comment by MattUV** [comment] 2018-11-16 15:05
Well, you can indeed send arguments to the game with the command line or by making a link (on windows at least).
You can get them by code with ```OS.get_cmdline_args()```

![raccourci](https://user-images.githubusercontent.com/13215043/48628423-648c3f80-e9b7-11e8-9e42-62dadfb81a6d.png)

Sadly this is not user-friendly...

**Comment by Calinou** [comment] 2019-08-27 16:38
This issue seems to be a duplicate of #8721 (the underlying cause is the same), so I'll close it. Thanks for reporting it :slightly_smiling_face:

**Closed by Calinou** 2019-08-27 16:38 UTC
Labels: discussion, enhancement, topic:core
