### ISSUE TITLE
Godot crash on start in Mac OS X 10.10.3

### ISSUE THREAD

**Issue by almindor** [godotengine/godot#2301] opened 2015-07-24 16:22 UTC
SIGSEGV right on start with official 1.1 app.

ERROR: create: Condition ' !create_func ' is true. returned: 0
   At: core/os/mutex.cpp:39.
Segmentation fault: 11

**Comment by tyoc213** [comment] 2015-08-07 20:16
Same here

**Comment by d3v0x** [comment] 2015-08-08 04:14
If you're using multiple monitors, drag the application (focus) to the main monitor before starting. This works for me (starting from command line but it should work with the launcher as well)

**Comment by tyoc213** [comment] 2015-08-08 14:06
Yes, at less I'm with 2 monitors I was launching it on the second one.

**Comment by d3v0x** [comment] 2015-08-08 14:09
So I think it's the same like https://github.com/okamstudio/godot/issues/2216

**Comment by tyoc213** [comment] 2015-08-08 14:20
Yes, it is, after do that I get

```
$ bin/godot.osx.tools.32 
ERROR: create: Condition ' !create_func ' is true. returned: 0
   At: core/os/mutex.cpp:39.
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
nscreen count 2
added screen 1
added screen 2
```

**Comment by vnen** [comment] 2015-10-29 16:40
Closing this as duplicate of #2216.

**Closed by vnen** 2015-10-29 16:40 UTC
Labels: archived, bug
