### ISSUE TITLE
Mouse Wheel Up and Down not working in Input Map

### ISSUE THREAD

**Issue by MRcodino07** [godotengine/godot#62398] opened 2022-06-25 12:52 UTC
### Godot version

4.0 alpha 10

### System information

Linux (Ubuntu)

### Issue description

If Mouse Wheel Up or Down is added to an Action in the Input Map, it will not be considered.

### Steps to reproduce

1. Add Mouse Wheel Up or Down to an Action "swap_gadget_up" / "swap_gadget_down" in the Input Map
2. Print something if "swap_gadget_up" / "swap_gadget_down" is triggered
3. nothing will be triggered, unless you add a physical button to the action, and you press that instead of using the mouse wheel

**Comment by MRcodino07** [comment] 2022-06-25 16:09
Here's a minimal reprodution project, forgot to add it in
[Mouse Wheel.zip](https://github.com/godotengine/godot/files/8985165/Mouse.Wheel.zip)
.

**Comment by Calinou** [comment] 2022-06-25 18:15
Does it work in 3.4.4?

Note that mouse wheel up/down are the only actions that are *always* pressed and released on the same frame.

**Comment by Chaosus** [comment] 2022-06-25 20:08
Mouse wheel buttons are activated only on release events. Its very old issue, and pretty sure it was already reported...

**Comment by gotnospirit** [comment] 2022-06-26 05:16
Tried replacing the "is_action_just_pressed" by "is_action_just_released" and the action is printed without problem. Maybe just a documentation problem?

**Comment by Chaosus** [comment] 2022-06-26 05:48
Duplicate of https://github.com/godotengine/godot/issues/36322

**Closed by Chaosus** 2022-06-26 05:48 UTC
Labels: topic:input

**Comment by MRcodino07** [comment] 2022-06-26 09:57
> Tried replacing the "is_action_just_pressed" by "is_action_just_released" and the action is printed without problem. Maybe just a documentation problem?

Thanks for the help (and sorry if I made a duplicate issue, but i think seems a bit strange triggering a ScrollWheel action with an on_release function. Maybe it is intended this way)
