### ISSUE TITLE
If an error happens during ClassDB binding, the Mono module crashes the engine

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#35740] opened 2020-01-30 13:02 UTC
Godot 3.2 master

Source:
https://github.com/Zylann/godot_voxel/issues/81#issuecomment-580206325

Basically, something went wrong during the registration of a property while my module is registered, which normally would have passed with an `ERR_FAIL_COND`. However, the error handler goes through the retrieval of the current script stack trace, which goes through all languages, including Mono, which at the time doesnt seem to be fully initialized... then crashes.

**Comment by KoBeWi** [comment] 2020-12-12 23:44
Can anyone still reproduce this bug in Godot 3.2.3 or any later release?

If yes, please ensure that an up-to-date Minimal Reproduction Project (MRP) is included in this report (a MRP is a zipped Godot project with the minimal elements necessary to reliably trigger the bug). You can upload ZIP files in an issue comment with a drag and drop.

**Comment by Zylann** [comment] 2020-12-12 23:49
There is no possible MRP here, it needs a manual try with the Godot source itself with Mono. The problem occurs if an error gets raised during the binding of a class of a module (as shown in the stack trace of the linked comment), where it seems the C# module did not initialize yet because modules appear to initialize in quite a random order. I dont have a setup to test this atm.

**Comment by Zylann** [comment] 2022-11-22 19:00
Apparently someone had a similar issue in 4.0 as well.

**Comment by Beliar83** [comment] 2022-11-22 19:38
Yeah, the problem is at https://github.com/godotengine/godot/blob/master/modules/mono/csharp_script.cpp#L585.

Specifically, this could can be reached after the constructor was called, but before init() which means at that time gdmono still has the default value (nullptr).

**Comment by akien-mga** [comment] 2023-03-06 11:39
Fixed by #74128.

**Closed by akien-mga** 2023-03-06 11:39 UTC
Labels: bug, confirmed, topic:dotnet
