### ISSUE TITLE
No implementation found for double_tap (Android)

### ISSUE THREAD

**Issue by fenix-hub** [godotengine/godot#35225] opened 2020-01-16 22:45 UTC
**Godot version:**
v3.2beta6

**OS/device including version:**
Android

**Issue description:**
I'm correctly exporting my project for Android and testing it, but when I double tap the apps crashes.
For the Windows version there isn't any issue, and the project is running fine.
Currently I'm not handling inputs in any particular way other than with the _input() function and using the same MouseButton events for Android input events.
When I attach adb logcat during Android testing, this is the error message that is appearing before the crash:
<img width="663" alt="Cattura" src="https://user-images.githubusercontent.com/45271396/72568130-b7150480-38b7-11ea-805d-22fcdb22c279.PNG">

I'm using the export template downloaded via HTTPS within Godot Engine's editor.
I also tried exporting my project with Godot Envine v3.1.2-stable, but I'm not encountering this issue and the project just works fine both on Windows and on Android without any error.

**Steps to reproduce:**
1. Download the apk
3. Double tap any moment running on Android

**Minimal reproduction project:**
[imrpg.zip](https://github.com/godotengine/godot/files/4074108/imrpg.zip)

Thank you very much.

**Comment by akien-mga** [comment] 2020-01-16 22:50
Duplicate of #35049.

**Closed by akien-mga** 2020-01-16 22:50 UTC

**Comment by fenix-hub** [comment] 2020-01-17 10:35
Sorry for the duplicate, thank you very much!
