### ISSUE TITLE
Error compiling the godot last build in Yosemite 

### ISSUE THREAD

**Issue by Zeta-Balam** [godotengine/godot#2367] opened 2015-08-13 17:57 UTC
`g++ -o drivers/unix/os_unix.osx.tools.32.o -c -g3 -Wall -DDEBUG_ENABLED -DDEBUG_MEMORY_ENABLED -DFREETYPE_ENABLED -arch i386 -DDEBUG_MEMORY_ALLOC -DSCI_NAMESPACE -DAPPLE_STYLE_KEYS -DUNIX_ENABLED -DGLES2_ENABLED -DGLEW_ENABLED -DOSX_ENABLED -DMUSEPACK_ENABLED -DSQUISH_ENABLED -DVORBIS_ENABLED -DTHEORA_ENABLED -DPNG_ENABLED -DDDS_ENABLED -DPVR_ENABLED -DJPG_ENABLED -DWEBP_ENABLED -DSPEEX_ENABLED -DTOOLS_ENABLED -DGDSCRIPT_ENABLED -DMINIZIP_ENABLED -DXML_ENABLED -DETC1_ENABLED -Icore -Icore/math -Itools -Idrivers -I. -Iplatform/osx -Itools/freetype -Itools/freetype/freetype/include -Idrivers/unix/vorbis drivers/unix/os_unix.cpp
drivers/unix/os_unix.cpp:229:2: error: no matching function for call to
      'localtime'
        localtime(&tv_now.tv_usec);
        ^~~~~~~~~
/usr/include/time.h:112:12: note: candidate function not viable: no known
      conversion from '__darwin_suseconds_t *' (aka 'int *') to 'const time_t *'
      (aka 'const long *') for 1st argument
struct tm *localtime(const time_t *);
           ^
1 error generated.
scons: *** [drivers/unix/os_unix.osx.tools.32.o] Error 1
scons: building terminated because of errors.
`

**Comment by neikeq** [comment] 2015-08-13 18:25
Looks like duplicate of #2346

**Closed** 2015-11-09 14:05 UTC
Labels: archived
