### ISSUE TITLE
Cannot load image after export

### ISSUE THREAD

**Issue by Applemann** [godotengine/godot#18638] opened 2018-05-05 17:37 UTC
**Godot version:**

v3.0.2.stable.official

**OS/device including version:**

Computer: Ubuntu 16.04.3 LTS
Mobile: Android 8.1.0

**Issue description:**

I am exporting this Godot project for Android: https://github.com/Applemann/Godot-TestLoadSprite
And I am trying in Game.gd script load sprite during run game. I was inspirated by [this](http://docs.godotengine.org/en/3.0/getting_started/step_by_step/scripting_continued.html#creating-nodes)

When I run it in Godot, it works fine, but in Android sprite image is not showing..
I tried various image loading:
```
image.load("res://icon.png")   # works
image.load("res://images/icon.png")   # don't works
image.load("res://game_over.png")    # don't works
```

When I am loading "res://icon.png" so it works and image also show in Android.
But when I am loading "res://images/icon.png" it is same image but in 'images' directory, it is not show in Android or Ubuntu after export. 
And when I load another my image from "res://game_over.png" so it don't work in Android or Ubuntu after export.

But all works when I click Play (F5) in Godot!!

**Steps to reproduce:**
Clone my github repository: https://github.com/Applemann/Godot-TestLoadSprite
Open it in Godot, edit Game.gd script for what image you want show and export game into Linux or Android. 
Run exported app.

**Comment by Applemann** [comment] 2018-05-05 18:11
Now I discovered that when I export this game for linux into different directory, I must run it when I am in Godot root directory for right running..
For example:
```
martin at martin-pc Godot-TestLoadSprite >>> ls                                      
default_env.tres    exports  game_over.png         Game.tscn  icon.png.import  project.godot
export_presets.cfg  Game.gd  game_over.png.import  icon.png   images
martin at martin-pc Godot-TestLoadSprite >>> ./exports/TestLoadSprite2.x86_64              ## Run it right
OpenGL ES 3.0 Renderer: Mesa DRI Intel(R) Haswell Mobile
martin at martin-pc Godot-TestLoadSprite >>> cd exports                                   
martin at martin-pc exports >>> ./TestLoadSprite2.x86_64                                   ## Run it wrong    
```

**Comment by Applemann** [comment] 2018-05-05 20:00
I have there also setuped filters for '*.png' in export for Android and linux:
![screenshot from 2018-05-05 21-55-18](https://user-images.githubusercontent.com/2686906/39667126-94fb75ce-50af-11e8-9702-a015a8bc88c4.png)

**Comment by vnen** [comment] 2018-05-05 20:17
The problem is the same as #15380: essentially all imported files goes to the `.import` folder and are not present in their original location anymore, so you can't reference them directly.

Is there any reason you want to create an image directly though? In you sample you could simply do: `sprite.texture = load("res://game_over.png")`. This will use the ResourceLoader which is aware of the location changes so it'll work fine.

**Comment by Applemann** [comment] 2018-05-05 21:01
@vnen Thank you, now it is working ;) I didn't know that I can load it so easy..
I thought that image.load() and load() is same or similar function..

**Comment by vnen** [comment] 2018-05-06 00:03
> I thought that image.load() and load() is same or similar function..

No, `load()` is equivalent to `ResourceLoader.load()` and will create a resource based on the file source (in this case it'll be a `StreamTexture`). You only need an `Image` if you want to manipulate pixel data (read or write), so `Image.load()` will load image data from the file directly, without using the ResourceLoader API.

Since your particular issue is solved and the general problem is already tracked in another ticket, I'll close this one.

**Closed by vnen** 2018-05-06 00:03 UTC

**Comment by arcticmatt** [comment] 2019-08-10 18:21
Hey @vnen, is there a way to make this work with `Image.load()`. I want to manipulate pixel data. Left some more details here https://godotengine.org/qa/50031/image-fails-export-warning-loading-resource-image-will-export

**Comment by hanzhihua1** [comment] 2020-02-18 03:09
Had this error when I was exporting my game, it works if you just take out the `res://` under Icon in Export. So `res;//icon.png` would be `icon.png`.

**Comment by Conundroy** [comment] 2023-07-05 08:59
The images aren't visible inside their parent folder for some reason but instead the .import files are. I found a workaround by removing the ".import" in the file path then load from this truncated string.

**Comment by Zireael07** [comment] 2023-07-05 09:11
@Conundroy your issue is a duplicate of another issue
