### ISSUE TITLE
float 0 is not always false

### ISSUE THREAD

**Issue by alexzheng** [godotengine/godot#44763] opened 2020-12-28 17:01 UTC
**Godot version:**

3.2.3

**OS/device including version:**

**Issue description:**

```gdscript
func _ready():
	var vec = Vector2.RIGHT
	
	if vec.y:
		printt("vec.y", true)
		
	vec = vec.rotated(PI * 1.5)
	
	printt(vec)
	
	if vec.x:
		printt("vec.x", vec.x, "is",  true)
```

the output is:

```
(0, -1)
vec.x	0	is	True
```

**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by Calinou** [comment] 2020-12-28 17:44
Use `is_equal_approx()` or `is_zero_approx()` for float comparisons. This is not done automatically for performance reasons.

**Comment by mrjustaguy** [comment] 2020-12-28 17:45
That is because of Floating Point error, not every float 0 is actually 0.. there are zeros that are equal 0.00000X that show as "0"

**Comment by alexzheng** [comment] 2020-12-29 02:22
But a vector (1, 0) rotate 90 or 270 degrees, the x of the result is expected exactly equals 0

**Comment by Demindiro** [comment] 2020-12-29 02:37
> But a vector (1, 0) rotate 90 or 270 degrees, the x of the result is expected exactly equals 0

No it's not, FP numbers have a limited amount of precision.

```gdscript
extends MainLoop

func _idle(_d):
	var v := Vector2(1, 0).rotated(PI / 2)
	print(var2str(v.x))
	return true
```

Output:

```
-4.37114e-08
```

As you can see, it isn't quite 0.

**Comment by akien-mga** [comment] 2020-12-29 08:28
Closing as it's not a bug, that's how floating point calculations work.

The only thing which we can and might do in Godot is stop displaying small numbers with a limited precision, so that your print actually shows you the error instead of rounding to `0`.

**Closed by akien-mga** 2020-12-29 08:28 UTC

**Comment by aaronfranke** [comment] 2021-08-18 14:25
> @alexzheng But a vector (1, 0) rotate 90 or 270 degrees, the x of the result is expected exactly equals 0

To be clear, the problem is that when one does `var v := Vector2(1, 0).rotated(PI / 2)`, the `PI` part is where the error is introduced, it's an irrational number that can't be represented perfectly in binary.

If you want to rotate a vector by a multiple of 90 degrees, which can be done precisely, you can just do so manually:

```gdscript
var start := Vector2(1, 0)
var v := Vector2(-start.y, start.x)
```

Or, alternatively, you can use a transformation matrix.
