### ISSUE TITLE
GLES3: glBufferSubData very slow on Mali GPU for Immediate Geometry

### ISSUE THREAD

**Issue by kosz78** [godotengine/godot#25400] opened 2019-01-28 04:18 UTC
**Godot version:**
Godot 3.1 commit ab9bbce31

**OS/device including version:**
Meizu M6 (Mali-T860) Android 7.0

**Issue description:**
Draw of simple immediate geometry very slow on Mali GPU using GLES3 mode
![image](https://user-images.githubusercontent.com/3992195/51814556-6b57fc80-22ee-11e9-8763-4fa79707180f.png)
I found some discussion about the same problem at https://community.amd.com/thread/169646

**Comment by kosz78** [comment] 2019-01-28 04:43
This affected only if two or more immediate geometry, the first immediate geometry draw fast

**Comment by clayjohn** [comment] 2019-01-28 04:58
Do you mind clarifying what the Godot related bug is here? This looks like more of a driver/hardware issue.

For a little context, ImmediateGeometry is not meant as a fast way to draw complex objects, but as a simple way to prototype drawing simple objects.

**Comment by kosz78** [comment] 2019-01-28 05:39
I found workaround when I change `rendering/limits/buffers/immediate_buffer_size_kb` from `2048` to `64`
performance is increased in 5x times
@clayjohn we use ImmediateGeometry for 3D trail realization

**Comment by ZodmanPerth** [comment] 2019-09-11 11:51
I am having this exact issue on my RNE-L21 (Mali-T830) Android 8.0.  If I do more than 2 `draw_colored_polygon` calls in the `_draw` function of a Node2D on Android the performance drops to 7 FPS.  The `_draw` is only called once.

However, changing the immediate buffer size does not work for me.   I was able to get a marginal boost in performance by lowering the Canvas Polygon Index Buffer Size to 64, but I'm still nowhere near getting 60fps for something so trivial.

I need a definitive answer; is this an issue with Godot or the driver?  This issue could kill my entire project.  ☹

I'm happy to provide sample projects and do whatever it takes to help diagnose the issue.

**Comment by ZodmanPerth** [comment] 2019-11-03 22:24
Fortunately I've been able to switch to drawing with 2D meshes and cleared myself a way to progress forward.

**Comment by KoBeWi** [comment] 2020-11-06 22:17
Can anyone still reproduce this bug in Godot 3.2.3 or any later release?

**Comment by ZodmanPerth** [comment] 2020-11-09 08:25
I've progress past this issue using my workaround and can't go back.  Sorry for being no help at reproducing here.

**Comment by KoBeWi** [comment] 2020-11-09 11:28
Closing as resolved then.

**Closed by KoBeWi** 2020-11-09 11:28 UTC
Labels: bug, platform:android, topic:rendering
