### ISSUE TITLE
Crash on project open after latest Windows 11 updates, works starting from terminal

### ISSUE THREAD

**Issue by Tyler-Osborne** [godotengine/godot#53485] opened 2021-10-06 16:54 UTC
### Godot version

3.3.4

### System information

Windows 11

### Issue description

This issue only started after updating to 3.3.4. This occurs whether or not the engine is the mono version. Unless I start godot from an open terminal, the editor crashes on project load.

### Steps to reproduce

-Run Godot any way but through an already open terminal.\
-Creare/Open project from list.
-Instacrash

**Comment by akien-mga** [comment] 2021-10-06 19:14
If you use 3.3.3 again, does it now crash too?
If so, did you just happen to upgrade to Windows 11?

**Comment by Tyler-Osborne** [comment] 2021-10-07 14:54
Ok so did some testing. This is since the latest dev channel update. 3.3.3 has the same issue.
But, yes, it works fine if started from an open terminal. I made a batch file on my desktop that I run in an open term and it works fine that way and only that way

**Comment by cybereality** [comment] 2021-11-03 09:27
I believe the issue is using the Windows Terminal as your default terminal application. If you set it to Windows Console Host it should work.

**Comment by akien-mga** [comment] 2021-11-03 09:37
Duplicate of #54076

**Closed by akien-mga** 2021-11-03 09:37 UTC
Labels: bug, platform:windows, topic:editor, confirmed, crash
