### ISSUE TITLE
UI-Elements aren't accessible due to big menu.

### ISSUE THREAD

**Issue by Schmetzler** [godotengine/godot#7178] opened 2016-11-23 20:29 UTC
Arch-Linux 64-Bit, Godot v.2.1.stable (xfce-desktop if it matters) resolution: 1366x768

I have an isssue that bothers me for quite a while now. If the menu over the editor gets to big the whole UI stretches even if there isn't enough space on the screen, resulting in inaccessibility of the panes on the right (Where usually the Inspector resides). I am also not able to resize the editor space in the left direction. To get to see the Inspector again I need to click on something that makes the menu smaller and afterwards let the window redraw (by making it small and big again). It's a hassle.

I have an image that shows the issue (this is my fullscreen, as you can see the right side is not visible)
![image](https://cloud.githubusercontent.com/assets/12082018/20577371/3f8472a4-b1c2-11e6-9543-2a2d86fbdf79.png)

To reproduce this you just have click on a tilemap on small screen.

It would be nice if there would be some solution for the menu do go in an expander if there are to many items (or like it was done for tabs).

Thanks in advance.

**Comment by bojidar-bg** [comment] 2016-11-24 09:52
Duplicate of #6461 I think

**Closed by bojidar-bg** 2016-11-24 09:52 UTC
