### ISSUE TITLE
Filesystem messed up after creating a res directory

### ISSUE THREAD

**Issue by ShrewdSpirit** [godotengine/godot#5895] opened 2016-07-24 15:42 UTC
**Operating system or device - Godot version:**
OS: Windows 10 x64
Godot commit c83aa5f86383bf89871f0a41752f5c6eeb148950

**Issue description** (what happened, and what was expected):
I created a directory under res:// and named that directory to 'res' then the filesystem tree messed up and displayed tons of repeating res:// copies. 
![ScreenShot](http://up.vbiran.ir/uploads/6818146937616632452_Untitled.png)

**Steps to reproduce:**
Create a directory named res under res:// and include/import a resource from there into your project. I don't know if the same thing might happen if you create a res directory under another directory

**Comment by bojidar-bg** [comment] 2016-07-24 17:49
Yet another duplicate of #3662....

**Closed by bojidar-bg** 2016-07-24 17:49 UTC
Labels: bug, topic:editor
