### ISSUE TITLE
Transition between different dpi screens on Mac

### ISSUE THREAD

**Issue by Sposito** [godotengine/godot#6835] opened 2016-10-15 17:46 UTC
**Mackbook Pro Retina 13" early 2015, macOS Sierra - Godot version: 2.1 release**

**Issue description** (what happened, and what was expected):
When I drag Godot editor from MacBook Pro retina screen to my secondary monitor (full hd) it becomes weird, it gets very large and because of it cropped inside the window area, when I bring it back to retina screen its background becomes white going back  to normal after rescaling window.

**Steps to reproduce:**
Just launch Godot on a dual monitor setup as described above and drag the editor from retina to the secondary screen

**Comment by Hinsbart** [comment] 2016-10-15 18:10
Looks like a duplicate of #5688, so closing.

**Closed by Hinsbart** 2016-10-15 18:10 UTC
