### ISSUE TITLE
Renaming .wav file causes crash on subsequent reimport.

### ISSUE THREAD

**Issue by TheDuriel** [godotengine/godot#40917] opened 2020-07-31 12:44 UTC
**Godot version:**

3.2 Stable

**OS/device including version:**

Windows 10

**Issue description:**

When renaming a .wav file using the Editors File Dock, the Engine crashes without logging an error on the subsequent reimport. It also appears that more than just the .wav file are getting re-imported.

**Steps to reproduce:**
Renaming a .wav file. 

**Minimal reproduction project:**

Project is for work, so I cant share it here. (I can provide a copy to a Godot dev under confidence.)

**Comment by akien-mga** [comment] 2020-07-31 12:55
Can you try 3.2.2-stable or 3.2.3 RC 1 or 2 (I messed up RC 2 so it's basically the same as RC 1 :))?

**Comment by akien-mga** [comment] 2020-07-31 12:56
> Project is for work, so I cant share it here. (I can provide a copy to a Godot dev under confidence.)

If the step to reproduce is "rename a .wav file", I assume you should be able to make a new minimal project that triggers it? Or is it specific to that work project and not reproducible outside it?

**Comment by TheDuriel** [comment] 2020-07-31 13:00
I'll try the RC build.

The issue currently only appears in this one project, though I recall similar rename related crashes in the past.

**Comment by TheDuriel** [comment] 2020-07-31 13:08
I can reliably recreate the crash on RC2.

**Comment by Mast3rGenius** [comment] 2021-03-02 23:47
Also crashes when moving a .wav file to a different folder and then after it re-imports or renaming the current folder it is in and then after it re-imports. 3.2.3

**Comment by Calinou** [comment] 2021-03-03 00:16
> Also crashes when moving a .wav file to a different folder and then after it re-imports or renaming the current folder it is in and then after it re-imports. 3.2.3

Can you reproduce this in a brand new project, or does this only occur in a specific project?

**Comment by Mast3rGenius** [comment] 2021-03-20 21:39
> > Also crashes when moving a .wav file to a different folder and then after it re-imports or renaming the current folder it is in and then after it re-imports. 3.2.3
> 
> Can you reproduce this in a brand new project, or does this only occur in a specific project?

Yes, I was able to reproduce this in a brand new project.

**Comment by JestemStefan** [comment] 2021-09-05 20:36
I can't reproduce it in 3.3.3.
When renaming file or moving it to different folder I just got an error, but no crash 
![obraz](https://user-images.githubusercontent.com/37214990/132140739-bcb36a8b-57ab-4d54-b4b4-d8fcf72409d5.png)

**Comment by Calinou** [comment] 2023-02-02 14:29
@TheDuriel Can you (or anyone else) still reproduce this bug in [Godot 3.5.1](https://godotengine.org/article/maintenance-release-godot-3-5-1) or any later release?

If yes, please ensure that an up-to-date Minimal Reproduction Project (MRP) is included in this report (a MRP is a zipped Godot project with the minimal elements necessary to reliably trigger the bug). You can upload ZIP files in an issue comment with a drag and drop.

**Comment by Calinou** [comment] 2023-02-02 14:44
Alright, closing then.

**Closed** 2023-02-02 14:44 UTC
Labels: bug, topic:audio, topic:import, crash
