### ISSUE TITLE
Editor freezes when selecting text in the system console due to Windows limitation

### ISSUE THREAD

**Issue by DamKoVosh** [godotengine/godot#34200] opened 2019-12-08 15:35 UTC
**Godot version:**
3.1.1.stable.official

**OS/device including version:**
Windows 10

**Issue description:**
Secting output in the terminal window of the Godot Enginge console causes the Enginge to crash on Scene run.

**Steps to reproduce:**
1. Create new project
2. Add Node2d
4. Select Text in the Console
3. Run The Node

**Minimal reproduction project:**
Empty 2D Node suffices

**Comment by Calinou** [comment] 2019-12-08 16:39
By "console", do you mean the command prompt that appears when the Godot editor opens, or the editor's  Output panel?

**Comment by DamKoVosh** [comment] 2019-12-08 16:59
command prompt (separate window, thats normally in the back)

**Comment by KoBeWi** [comment] 2019-12-08 17:28
I can confirm this in 3.2 beta3. The editor freezes because console is paused when something is selected (probably). Although it doesn't crash, you can unselect text and press any key in the console and the game runs correctly.

**Comment by Zylann** [comment] 2019-12-08 17:49
I think this is a normal behavior on Windows.

**Comment by NoFr1ends** [comment] 2019-12-08 18:38
Can confirm. Also this is the normal behavior of Windows.

**Comment by Calinou** [comment] 2019-12-08 18:52
Is there a way to fix this at all? Hiding the command prompt by window would make this harder to trigger by accident, but it will still be an issue for those who manually toggle it.

**Comment by NoFr1ends** [comment] 2019-12-08 22:13
We could disable the quick edit option by default, which would prevent the user from selecting in the console. Using https://docs.microsoft.com/en-us/windows/console/setconsolemode and not setting ``ENABLE_QUICK_EDIT_MODE``.

I’m not sure but it is also possible that Godot somewhere waits for the console buffers, that would explain why it’s only a problem when starting the project and not all the times.

**Comment by RaTcHeT302** [comment] 2019-12-09 12:13
nah don't turn off text selection, that's not a real fix, that's just hiding the problem away, and what if i ever need to copy some text from the command prompt window? having to type it all by hand would be so tedious

**Comment by Zylann** [comment] 2019-12-09 12:21
I think turning off quick edit doesn't prevent you from selecting text, it just means you have to explicitely open the console menu by clicking on the top-left icon, and choose "Select".
But I wish it didnt need to be turned off too.

**Comment by NoFr1ends** [comment] 2019-12-09 15:37
I will look where we wait for the buffer later.

**Comment by NoFr1ends** [comment] 2019-12-11 06:41
As far as I see it the reason for the freeze is that Godot starts a new process for running the project. And as long the console is frozen because the user made a selection the the new process don’t start. 
I don’t see an easy fix without changing the behavior how Godot starts the game.

**Comment by DamKoVosh** [comment] 2019-12-16 12:02
Well i didn't know thats a standard behavour of windows consoles, and since deselecting and pressing a key really does work, its not that big of a problem.

**Comment by akien-mga** [comment] 2022-01-17 12:27
After #56012 opening a console is no longer the default behavior, so this should be less prominent.

But as mentioned above, it's actually a "feature" of Windows and not something that we can fix, so closing.

**Closed by akien-mga** 2022-01-17 12:27 UTC
Labels: bug, platform:windows, topic:editor, confirmed, usability

**Comment by KoBeWi** [comment] 2022-01-17 12:34
I can't reproduce this bug anymore btw. Selecting text in console doesn't pause anything.
