### ISSUE TITLE
3 to 4 upgrade incorrect replace strings and comments in GDScript

### ISSUE THREAD

**Issue by edisonlee55** [godotengine/godot#72126] opened 2023-01-26 16:48 UTC
### Godot version

v4.0.beta15.official [4fa6edc88]

### System information

Windows 11

### Issue description

When I upgrade my project from 3 to 4. My strings and comments in GDScript files are being replaced incorrectly.

Minimal reproducible script:
```gdscript
# print Hello on World!
func _ready():
	print("Hello on World!")
```

After upgrade to 4:
```gdscript
# print Hello checked World3D!
func _ready():
	print("Hello checked World3D!")
```

### Steps to reproduce

1. Create a Godot 3 project with a minimal reproducible script in it
2. Upgrade the project from 3 to 4
3. Issue reproduced

### Minimal reproduction project

A Godot 3 project with the above minimal reproducible script is enough to reproduce the bug.

**Comment by AThousandShips** [comment] 2023-01-26 16:52
Duplicate of #70983

**Closed** 2023-01-26 16:52 UTC
