### ISSUE TITLE
[.Net] A Script is always marked `out of sync` when inheriting an external `Node` type

### ISSUE THREAD

**Issue by Delsin-Yu** [godotengine/godot#97408] opened 2024-09-24 12:50 UTC
### Tested versions

v4.3.stable.mono.official [77dcf97d8]

### System information

Godot v4.3.stable.mono - Windows 10.0.17763 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 4060 Ti (NVIDIA; 32.0.15.6109) - AMD Ryzen 9 5900X 12-Core Processor (24 Threads)

### Issue description

The Godot editor always marks a C# script `out of sync` when it inherits a custom Node type from a Nuget package or a separate C# project.

[![image](https://github.com/user-attachments/assets/af64abb6-81f1-427b-94b9-bdc08d73442b)](https://github.com/user-attachments/assets/291cc0db-0cc0-4ada-86ab-b0d64b822cc7)

### Steps to reproduce

1. Download and extract the MRP
2. Open the `./GodotProject` with Godot 4.3 mono
3. Build the project with Godot Editor

### Minimal reproduction project (MRP)

[MRP_Script_Path.zip](https://github.com/user-attachments/files/17113697/MRP_Script_Path.zip)

**Comment by raulsntos** [comment] 2024-09-24 13:30
Duplicate of https://github.com/godotengine/godot/issues/88536

**Closed by raulsntos** 2024-09-24 13:30 UTC

**Comment by Delsin-Yu** [comment] 2024-09-24 13:36
Oh, I forgot, sorry...
