### ISSUE TITLE
EditorPlugin.forward_canvas_gui_input(event) is only called with mouse events.

### ISSUE THREAD

**Issue by leoddd** [godotengine/godot#15350] opened 2018-01-04 21:47 UTC
**Godot version:**

7d0212f4e

**OS/device including version:**

Ubuntu 16.04

**Issue description:**

`EditorPlugin`'s `forward_canvas_gui_input(event)` method is only called for mouse input events, not for keyboard events.
If this is intended, disregard this issue but I don't feel like it's supposed to, since it processed keyboard events fine in Godot 2.

**Steps to reproduce:**
Create a new EditorPlugin, print something in its `forward_canvas_gui_input(event)` method and focus a node in the 2D editor, then move your mouse around, click mouse buttons and press keyboard keys. The latter will not produce the print, while the former will.

Example project: open `test.tscn`, enable the test plugin if it isn't already and do the above. Watch the output.
[Minimal EditorPlugin.zip](https://github.com/godotengine/godot/files/1604794/Minimal.EditorPlugin.zip)

- [x] I searched the existing [GitHub issues](https://github.com/godotengine/godot/issues?utf8=%E2%9C%93&q=is%3Aissue+) for potential duplicates.

**Comment by groud** [comment] 2018-01-05 07:26
Probably a duplicate of #12505

**Comment by groud** [comment] 2018-01-05 08:59
Reading again, yes, it a duplicate. Closing.

**Closed by groud** 2018-01-05 08:59 UTC
