### ISSUE TITLE
ShaderGraph nodes position reset when deleting connected nodes

### ISSUE THREAD

**Issue by ArcFutahito** [godotengine/godot#4869] opened 2016-05-29 09:20 UTC
When making a shader with ShaderGraph and deleting a node that's already connected to the chain, sometimes all other nodes reset their position and "stick" to the cursor (often fail to do so). 
For example, after deleting one of the nodes here, RGB operator stuck to the cursor and moves with a pointer, but it's position is way too far from the pointer. 
These little glitches are not consistent but occur way too often and ruin the whole structure sometimes. 
![clearcolor10](https://cloud.githubusercontent.com/assets/10696955/15632356/8fa96a76-2597-11e6-806a-1ceb08ff87fc.png)

**Comment by akien-mga** [comment] 2016-08-08 08:24
Closing as duplicate of #4433.

**Closed by akien-mga** 2016-08-08 08:24 UTC
Labels: bug, confirmed, topic:editor, usability
