### ISSUE TITLE
Animations with awkward lengths (more than 2-3 decimal places) ignore keys on the last frame

### ISSUE THREAD

**Issue by LakshayaG73** [godotengine/godot#66631] opened 2022-09-29 23:39 UTC
### Godot version

4.0 beta

### System information

Win 11

### Issue description

Animations that have slightly awkward lengths have issues where the keys on the last frame are not executed. 

These keys can belong to value tracks, or even function tracks in my experience. 

I'm not certain that this only pertains to animations with specific lengths, but this is the only pattern I have found. As I don't see this issue in all animations. 

The workaround is to increase the length of the animation slightly, shift the key slightly on the track, or delete the track and add it again (in some cases). 

### Steps to reproduce

Create animation in Animation Player
Set an awkward length -> 5 frames at 24 fps
Add some keys on different tracks on the last frame.
Check if (all) the keys are executed

**Comment by Calinou** [comment] 2022-09-30 00:35
This is likely a floating-point precision issue, or a frame pacing issue (60 FPS only has 16 ms resolution). Can you reproduce this with V-Sync disabled and a small window size (to reach high FPS)?

Also, please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

**Comment by TokageItLab** [comment] 2022-09-30 21:27
May be related by #64644.

**Comment by Calinou** [comment] 2022-10-29 19:57
Duplicate of https://github.com/godotengine/godot/issues/64644.

**Closed by Calinou** 2022-10-29 19:57 UTC
Labels: bug, needs testing, topic:animation

**Comment by TokageItLab** [comment] 2022-11-16 21:25
Maybe this is related to #59784 instead of #64644, but I can't determine since MRP and details are lacking on this issue.
