### ISSUE TITLE
Godot 3.0 beta performance issues, when duplicating a scene node (3D area with nested geometry nodes)

### ISSUE THREAD

**Issue by dynamite-ready** [godotengine/godot#14617] opened 2017-12-13 09:24 UTC
I'm based on a Windows 8 laptop with an Nvidia 960m GPU, running the Godot 3 beta.

I have a simple 2 scene setup (both 3D). The first scene is the project root and the main stage.
The second scene is a 3D 'tile' containing 150+ cubes, which I translate/animate (in the _process function) along the X axis towards the camera. When this tile moves off screen, I duplicate it, place the duplicate at the top of the screen, and remove the instance that just moved of screen.

This should produce a smooth scrolling effect (60fps), and it works fairly well. 
Indeed, I've used the same scheme in a Godot 2.* project, and it works well enough.

On the 3.* beta however, there appears to be a 1-2 frame pause, every time a duplicate is created.
I had a brief discussion with a few others on the Godot IRC, and they agree it sounds suspicious...

Is this something you guys are aware of?

**Comment by Ranoller** [comment] 2017-12-13 14:43
This frame pause wil be because of remote tree activated, but was fixed turning off remote scene tree by default. Try to click in scene tree/local when playing and see if this fixes your issue.

**Comment by dynamite-ready** [comment] 2017-12-14 11:18
I've tried you suggestion, but it did not appear to make a difference. Is there anything else I need to look out for?

**Comment by Calinou** [comment] 2019-12-24 10:00
Duplicate of #13954 (according to the description).

**Closed by Calinou** 2019-12-24 10:00 UTC
Labels: discussion, topic:physics, topic:rendering
