### ISSUE TITLE
Cannot change language back to English in Project Manager. Clicking on Language Button auto-selects option.

### ISSUE THREAD

**Issue by sps1112** [godotengine/godot#46182] opened 2021-02-18 19:27 UTC
**Godot version:**

310496a

**OS/device including version:**

Ubuntu 20.04

**Issue description:**

If language is changed in the Project Manager to any other language than English, it cannot be changed back to English. Also clicking on the Change language button auto selects the option from the opened list based on cursor position.

**Steps to reproduce:**
1. Compile for Linux as ```scons -j4 platform=linuxbsd```.Now open the Editor build.
2. Change language to any language other than English.
3. Now try to change the Language back to English.

**Minimal reproduction project:**

No project required

Below are some screenshots to better explain the issue.(Note- The cursor is not visible in the screenshots and is thus replaced  by a red dot)

 ![Screenshot from 2021-02-19 00-53-02](https://user-images.githubusercontent.com/62471966/108410275-37d9c900-724d-11eb-86ad-7f3632db8dae.png)

Selecting any other language highlights it and is Clickable.
![Screenshot from 2021-02-19 00-46-42](https://user-images.githubusercontent.com/62471966/108409742-99e5fe80-724c-11eb-9d77-ddb8f412e575.png)
Selecting English does NOT highlight it and is not Clickable.
![Screenshot from 2021-02-19 00-46-36](https://user-images.githubusercontent.com/62471966/108409761-9eaab280-724c-11eb-95c1-3b4e67cfc8b4.png)

Also deleting and recompiling the code in some other folder does not fix the problem and language is still the new one. This setting must have been saved as some form of cache.

**Comment by Calinou** [comment] 2021-02-18 21:08
Duplicate of https://github.com/godotengine/godot/issues/44230 (same cause).

To reset the language to English, remove `$HOME/.config/godot/editor_settings-4.tres`.

**Closed by Calinou** 2021-02-18 21:09 UTC
