### ISSUE TITLE
WorldEnvironment in Canvas in 2D glitches preview and editor UI

### ISSUE THREAD

**Issue by julhe** [godotengine/godot#63090] opened 2022-07-16 23:56 UTC
### Godot version

4.0dev (ae5668f81e)

### System information

Windows 10, AMD Radeon 6800 XT (22.3.1), Vulkan

### Issue description

When trying to do post-proccessing via the WorldEnvironment node in 2D, choosing "Canvas" as the background mode will glitch the preview screen and the editor UI. 

Before:
![grafik](https://user-images.githubusercontent.com/18037091/179375412-0465408e-7de9-4d18-990a-d5ab4b6fc783.png)
After:
![grafik](https://user-images.githubusercontent.com/18037091/179375416-f96f6d6c-f8c6-4699-b0af-600f3fd9ebe0.png)

### Steps to reproduce

Switch the background mode to "Canvas" and observe.

### Minimal reproduction project

[Godot4_WorldEnvironment2D_Bug.zip](https://github.com/godotengine/godot/files/9126806/Godot4_WorldEnvironment2D_Bug.zip)

**Comment by Calinou** [comment] 2022-07-17 00:02
Duplicate of https://github.com/godotengine/godot/issues/52467.

**Closed by Calinou** 2022-07-17 00:02 UTC
