### ISSUE TITLE
Texture resource_name is blank

### ISSUE THREAD

**Issue by wyattbiker** [godotengine/godot#22414] opened 2018-09-24 20:26 UTC
**Godot version:**
3.1 alpha
Mac OS X, High Sierra

**Issue description:**
Add a Sprite and load a texture. Edit texture resource and add a Name to it.  Connect ready script to Sprite and run the scene. Values printed is empty
```
extends Sprite
func _on_Sprite_ready():
	print("Name:", self.texture.resource_name)
	print("Path: ",self.texture.resource_path)
```

**Comment by ni-code** [comment] 2018-09-25 21:46
I think this affect other resources other tan just textures.
As far as I can tell, saved resources such as shaders, physics mats have their name blank in the inspector. I reproduced it without any code needed, just save a resource like a shader and assign it. The label in the inspector doesn't display the name.
![screenshot from 2018-09-25 22-34-30](https://user-images.githubusercontent.com/10292929/46045140-afef4380-c114-11e8-84a3-3ccdd05724f0.png)

**Comment by ni-code** [comment] 2018-09-26 00:01
Actually the easiest way to reproduce this, is by just drag and drop an image into a TextureRect node.
master brach #22427 

Note that the name label stays blank instead of displaying the texture name.

![peek 2018-09-26 00-55](https://user-images.githubusercontent.com/10292929/46049663-7c69e480-c127-11e8-9764-0828af0e27cd.gif)

**Comment by ni-code** [comment] 2018-09-26 00:07
OMG, I feel dumb now. I think the issue I'm reporting isn't related with what op reported. Shame on me, Shall I reopen other issue?

**Comment by akien-mga** [comment] 2018-09-26 06:44
Duplicate of #13358.

**Closed by akien-mga** 2018-09-26 06:44 UTC
