### ISSUE TITLE
Godot 4 fails to start

### ISSUE THREAD

**Issue by RogerLevy** [godotengine/godot#66680] opened 2022-09-30 20:08 UTC
### Godot version

4.0 beta 2

### System information

Windows 10, AMD Ryzen 7 4800H, GeForce GTX 1660 Ti

### Issue description

I downloaded the 64-bit exe version, unzipped it, and it won't start.  I see a black window for a split second which then closes.  Running on a Legion 5.

### Steps to reproduce

Just start the executable.

**Comment by Redwarx008** [comment] 2022-09-30 20:37
Seme here, 4800hs GTX1660Ti Maxq 
>  ERROR: GENERAL - Message Id Number: 0 | Message Id Name: Loader Message
        setup_loader_tramp_phys_devs:  Failed during dispatch call of 'vkEnumeratePhysicalDevices' to lower layers or loader to get count.
        Objects - 1
                Object[0] - VK_OBJECT_TYPE_INSTANCE, Handle 2459284939024
   at: _debug_messenger_callback (drivers/vulkan/vulkan_context.cpp:171)
ERROR: vkEnumeratePhysicalDevices reported zero accessible devices.
Do you have a compatible Vulkan installable client driver (ICD) installed?
vkEnumeratePhysicalDevices Failure
   at: (drivers/vulkan/vulkan_context.cpp:864)
ERROR: Condition "err != OK" is true. Returning: ERR_CANT_CREATE
   at: _window_create (drivers/vulkan/vulkan_context.cpp:1462)

**Comment by Calinou** [comment] 2022-09-30 20:55
Duplicate of https://github.com/godotengine/godot/issues/57708.

**Closed by Calinou** 2022-09-30 20:55 UTC
