### ISSUE TITLE
Running godot on Linux via bumblebee is broken

### ISSUE THREAD

**Issue by ghost** [godotengine/godot#67] opened 2014-02-14 06:51 UTC
For those who don't know what optirun is, it is a program on linux that allows you to run other programs on an alternate graphics card (Namely on nVidia Optimus systems).

This is very important for those of us with somewhat older laptops (mine is a 2010), due to the fact that the Intel cards have a tendency to render faces on the wrong side of an object.  Using optirun, we can run the program with a better GPU, eliminating those glitches.

Results of running `optirun ./godot_x11.64` and attempting to edit a project:

```
opening pack (CURRENT WORKING DIR)/godot_x11.64, -1, -1
opening pack (CURRENT WORKING DIR)/data.pck, -1, -1
opening pack (CURRENT WORKING DIR)/data.pcz, -1, 0
opening pack (CURRENT WORKING DIR)../data.pck, -1, -1
opening pack (CURRENT WORKING DIR)../data.pcz, -1, 0
opening pack (CURRENT WORKING DIR)../..data.pck, -1, -1
opening pack (CURRENT WORKING DIR)../..data.pcz, -1, 0
opening pack (CURRENT WORKING DIR)../../../data.pck, -1, -1
opening pack (CURRENT WORKING DIR)../../../data.pcz, -1, 0
opening pack //data.pck, -1, -1
opening pack //data.pcz, -1, 0
ERROR: set_custom_property_info: Condition ' !props.has(p_prop) ' is true.
   At: core/globals.cpp:1317.
***** SET ICON ***** 128  128
ERROR: set_font: Condition ' p_font.is_null() ' is true.
   At: scene/resources/theme.cpp:302.
ERROR: set_stylebox: Condition ' p_style.is_null() ' is true.
   At: scene/resources/theme.cpp:251.
editor: 0
list diring on: (CURRENT WORKING DIR)../../../godot/plugins
ERROR: _load_recent_projects: Condition ' err!=OK ' is true. Continuing..:
   At: tools/editor/project_manager.cpp:393.
ERROR: _load_recent_projects: Condition ' err!=OK ' is true. Continuing..:
   At: tools/editor/project_manager.cpp:393.
ERROR: _load_recent_projects: Condition ' err!=OK ' is true. Continuing..:
   At: tools/editor/project_manager.cpp:393.
ERROR: _load_recent_projects: Condition ' err!=OK ' is true. Continuing..:
   At: tools/editor/project_manager.cpp:393.
OPENING: (CURRENT WORKING DIR)/TestProj (::CWD::TestProj)
ERROR: cleanup: ObjectDB Instances still exist!
   At: core/object.cpp:1656.
ERROR: set_custom_property_info: Condition ' !props.has(p_prop) ' is true.
   At: core/globals.cpp:1317.
~/$ CREATING RENDER THREAD
XIO:  fatal IO error 2 (No such file or directory) on X server ":8"
      after 41 requests (41 known processed) with 0 events remaining.
```

The project selector comes up, and running the projects runs them on the correct graphics card (without rendering glitches), but the edit button causes the crash mentioned above.  The same crash occurs if you optirun an exported project. (Linux 64-bit)

I'm not sure what causes this or how to fix it, as I've never had a problem with programs on optirun until now. (Sorry, I can't compile godot, I do not have administrator rights to my machine and therefore have a hard time installing deps)

**Comment by akien-mga** [comment] 2015-10-29 10:32
I'll check if I can reproduce this in the current master branch.

**Comment by StraToN** [comment] 2015-10-29 10:42
Confirmed. Here is my command line result with both optirun and primusrun.
```
$ optirun ./godot.x11.tools.64 -e /home/julian/godot/3dproject-test/
BOOT SPLASH: 
BOOT SPLASH IS : 
ERROR: load: No loader found for resource: res://3dproject-test
   At: core/io/resource_loader.cpp:218.
ERROR: start: Failed loading scene: res://3dproject-test
   At: main/main.cpp:1353.
ERROR: free: Attempt to free invalid ID
   At: servers/spatial_sound/spatial_sound_server_sw.cpp:598.
ERROR: free: Attempt to free invalid ID
   At: servers/spatial_sound_2d/spatial_sound_2d_server_sw.cpp:612.
freed code id 1
ERROR: cleanup: ObjectDB Instances still exist!
   At: core/object.cpp:1853.


$ primusrun ./godot.x11.tools.64 -e /home/julian/godot/3dproject-test/
BOOT SPLASH: 
BOOT SPLASH IS : 
ERROR: load: No loader found for resource: res://3dproject-test
   At: core/io/resource_loader.cpp:218.
ERROR: start: Failed loading scene: res://3dproject-test
   At: main/main.cpp:1353.
ERROR: free: Attempt to free invalid ID
   At: servers/spatial_sound/spatial_sound_server_sw.cpp:598.
ERROR: free: Attempt to free invalid ID
   At: servers/spatial_sound_2d/spatial_sound_2d_server_sw.cpp:612.
freed code id 1
ERROR: cleanup: ObjectDB Instances still exist!
   At: core/object.cpp:1853.
```

**Comment by razvanc-r** [comment] 2016-06-24 09:51
Are people still using bublebee / primus? I thought they're integrated in the OS in newer distributions of Linux. I mean, I have performance settings in the NVIDIA configuration tool and so I don't need to use bumblebee any longer (Ubuntu 16.04, but I think it was present in 15.10 as well). Don't know about AMD tho.

**Comment by akien-mga** [comment] 2016-06-24 10:20
Yeah bumblebee is still used even though it's not really maintained upstream. Ubuntu has a built-in feature for Optimus, but not all distros do, and it's a pile of Ubuntu-specific scripts, so it's hard to port to other distros (I tried :P).

Nowadays the open source nouveau driver is making some huge progress on this field, and can already give similar or better performance than the nvidia driver using DRI_PRIME; so hopefully in a year or so we'll be able to let bumblebee become a relic of the past.

**Comment by Calinou** [comment] 2016-06-24 10:41
I have no issues with Bumblebee (`primusrun`) here on Arch Linux, with nvidia 367.27.

**Comment by akien-mga** [comment] 2016-07-19 08:57
Can other users still reproduce it? @StraToN?

**Comment by StraToN** [comment] 2016-07-19 17:29
@akien-mga No more problem for me.

**Comment by akien-mga** [comment] 2016-07-19 17:31
Thanks. So two users who couldn't reproduce, we'll assume it got fixed somehow. Not sure how, but well :)

**Comment by akien-mga** [comment] 2017-08-31 05:32
Reopening as it can still be reproduced in 2.1.3 by @skarmiglione:
```
optirun ./Godot_v2.1.3-stable_x11.64
WARNING: initialize: Could not find cursor theme
At: platform/x11/os_x11.cpp:346.
ERROR: load_image: Error opening file: /home/cmkat/cosmogatokat/Herramientas/creacion_de_juegos/godot/juegos godot 2.1/projectleek-master/icon.png
At: core/io/image_loader.cpp:53.
ERROR: load_image: Error opening file: /home/cmkat/cosmogatokat/Herramientas/creacion_de_juegos/godot/juegos hecho con godot 2.0/marine_treasure_hunter-master/icon.png
At: core/io/image_loader.cpp:53.
WARNING: _png_warn_function: iCCP: known incorrect sRGB profile
At: drivers/png/image_loader_png.cpp:66.
WARNING: _png_warn_function: iCCP: known incorrect sRGB profile
At: drivers/png/image_loader_png.cpp:66.
WARNING: _png_warn_function: iCCP: known incorrect sRGB profile
At: drivers/png/image_loader_png.cpp:66.
WARNING: _png_warn_function: iCCP: known incorrect sRGB profile
At: drivers/png/image_loader_png.cpp:66.
WARNING: _png_warn_function: iCCP: known incorrect sRGB profile
At: drivers/png/image_loader_png.cpp:66.
OPENING: /home/cmkat/cosmogatokat/2d/balloon fight (::home::cmkat::cosmogatokat::2d::balloon fight)
WARNING: initialize: Could not find cursor theme
At: platform/x11/os_x11.cpp:346.
cmkat@saturnikx ~/cosmogatokat/Herramientas/creacion_de_juegos/godot $ XIO: fatal IO error 2 (No such file or directory) on X server ":8"
after 53 requests (53 known processed) with 0 events remaining
```

Can you try the Primus backend? VirtualGL (the default one when using `optirun` without specifying `-b primus`) is notoriously buggy.

**Comment by akien-mga** [comment] 2017-08-31 05:34
Also, another workaround seems to be to run the project directly without going through the project manager, so:
```
cd "/home/cmkat/cosmogatokat/2d/balloon fight"
~/cosmogatokat/Herramientas/creacion_de_juegos/godot -e
```

**Comment by DuskKittyIsHotAF** [comment] 2018-02-12 12:12
very tolerant and nice commnuity imo. run by great leadership skills, you should be proud juan and akien for leading this great floss project!
![](https://i.gyazo.com/2fd0c035013b3c1bb0652552d35fde92.png)
![](https://i.gyazo.com/e0acd22258872330f342d5d189564f1e.png)
![](https://i.gyazo.com/81b238ce283aa55126e3a2f608583837.png)

**Comment by Chaosus** [comment] 2018-09-14 19:07
what is bumblebee ?

**Comment by akien-mga** [comment] 2018-09-14 19:09
> what is bumblebee ?

It's described in the OP :) It's basically support for discrete Nvidia GPU (Optimus) on Linux via a command line switch: https://www.bumblebee-project.org/

**Comment by akien-mga** [comment] 2018-09-14 19:17
BTW, at least https://github.com/godotengine/godot/issues/67#issuecomment-64061628 and https://github.com/godotengine/godot/issues/67#issuecomment-152143428 are bad confirmations of the bug, as they're using the wrong command line instructions to call Godot.

I suspect that others are having similar issues where they can run the project manager with bumblebee, but then it fails when loading a project as it forks a new instance and does not run it through bumblebee. Running a game with the *correct* command line should work fine, i.e. `primusrun godot --path /path/to/game/folder` (additionally with `-e` if you want to run the editor).

Eventually it's the same issue as debuggers losing their grip on Godot when you open a project (new process) from the project manager, or Steam losing track of time spent in the editor. I may have a go at improving this situation eventually, but not specifically with Bumblebee in mind, which is also a dead project upstream and struggling today to maybe one day get Vulkan support... so closing.

**Closed by akien-mga** 2018-09-14 19:17 UTC
Labels: bug, confirmed, platform:linuxbsd, topic:core
