### ISSUE TITLE
HBox container no longer populates when entries are instanced in Beta8

### ISSUE THREAD

**Issue by c7borg** [godotengine/godot#70059] opened 2022-12-14 14:55 UTC
### Godot version

4.0.beta8

### System information

mac OS ver 12.5 Monterey

### Issue description

The below is in a for loop and populates a list of characters in a HBox, this works fine upto Beta7 but not on Beta8 no error or warning is given. To confirm the output the print statement prints as expected. I have included a mini project reproducing the issue. 
```
...
@onready var characterInList = load("res://character_for_list.tscn")
...
# THE BELOW IS WITHIN A FUNCTION
for _character in npcTeam:
		var _chr_ref = npcTeam[_character]["chr"]
		var _chr_points = TeamPicker.characters_dict['data'][_chr_ref].points
		var _chr_name = TeamPicker.characters_dict['data'][_chr_ref].name
		print ("Character: ", _chr_ref, " name: ", _chr_name, "points: ",  _chr_points)
		# ADD EACH CHR TO CONATAINER
		var _instance = characterInList.instantiate()
		_instance.get_node("HBoxContainer/CharacterName").text = _chr_name
		_instance.get_node("HBoxContainer/Points").text = _chr_points
		$Camera2D/Control/MarginContainer/HBoxContainer/MarginDefenders/Defenders/MarginChrList/ScrollContainer/CharactersList.add_child(_instance)
...
```

### Steps to reproduce

This is reproduced by clicking pick team button, in Beta7 and below it will print characters names 1 through to 10 and populate the HBox container but in Beta8 it still prints the characters names but no longer populates the HBox container

### Minimal reproduction project

[Bug1.zip](https://github.com/godotengine/godot/files/10228841/Bug1.zip)

**Comment by kleonc** [comment] 2022-12-15 13:00
Tested MRP both in beta7 and beta8. In both cases the `VBoxContainer`: `Map/Camera2D/Control/MarginContainer/HBoxContainer/MarginYourTeam/Yourteam/MarginChrList` is getting populated. The issue is it's not expanding within its parent container:
![6qJKNGFYdT](https://user-images.githubusercontent.com/9283098/207863933-3380f10a-2c72-4c62-8ba2-e71f2acefda8.png)

Don't see a bug in here, closing.

**Closed by kleonc** 2022-12-15 13:00 UTC
