### ISSUE TITLE
Vulkan: WorldEnvironment node leaks 2.85GB of render target VRAM when used (due to high sky radiance size)

### ISSUE THREAD

**Issue by Griefchief** [godotengine/godot#64677] opened 2022-08-21 02:20 UTC
### Godot version

master ( 29492f90843c29e2f258d0167199592c2045f5e4 )  godot 4 alpha13

### System information

Windows 10, RX 590 and probably 2080 TI confirmed, Vulkan, AMD Driver 22.5.1

### Issue description

VRAM ussage of Render Targets balloons to 2.85GB VRAM in editor or in game until the scene is closed. Causes VRAM into Shared RAM into hard drive related stutters-blocking of framerate under ideal conditions. Might be related to procedural sky settings, does not seem related to SDFGI or other settings.

![Clipboard - August 20, 2022 7 03 AM](https://user-images.githubusercontent.com/5757704/185772372-86347c9a-f754-44a9-b3e2-9a7e24ebb59e.png)
.

### Steps to reproduce

1) Add WorldEnvironment Node to an empty scene
2) Create a parametric sky, and or other settings that might trigger this leak as in image. SSAO, SDFGI etc can be turned off.
3) Simply opening the scene in editor will cause the VRAM leak, closing it will resolve the leak. Can be monitored via Win 10s Task Manager Performance Tab/Graphics card.

![image](https://user-images.githubusercontent.com/5757704/185772452-23c69b3e-f5ac-4c49-a3a9-c76df958d6b5.png)

![image](https://user-images.githubusercontent.com/5757704/185772485-adec834e-1416-49ec-96d1-431631209b61.png)

### Minimal reproduction project

[WorldEnvVRAMIssue.zip](https://github.com/godotengine/godot/files/9388300/WorldEnvVRAMIssue.zip)

**Comment by Griefchief** [comment] 2022-08-21 02:50
Directly related to radiance size 2048 in settings for the sky radiance... Any other setting reduces it significantly.

![image](https://user-images.githubusercontent.com/5757704/185773216-d83518df-f675-4e03-9b0b-40a8e8271ba0.png)

**Comment by Griefchief** [comment] 2022-08-21 02:59
P.S. Maybe it's not a bug, but this setting is dangerous. This setting should be guarded somehow if possible.

**Comment by huisedenanhai** [comment] 2022-08-21 08:04
It seems to be a configuration issue. The sky creates a giant texture cube array based on user supplied radiance size, which eats 2GB VRAM in your case (RGBA16F, 2048x2048x8x6, with full mipmap).

<img width="977" alt="Screen Shot 2022-08-21 at 14 51 56" src="https://user-images.githubusercontent.com/22026948/185779374-d4b59dca-3e8b-41b5-8576-b2ed9c54b64f.png">

I don't think the sky radiance cache need such high resolution in practice. The content generally has very low frequency, and the aliasing closing to horizon can be fixed with smart uv remapping according to a newer [paper](https://sebh.github.io/publications/egsr2020.pdf), section 5.3. I'm not sure if godot supports such custom uv remapping for sky lut size optimization.

I haven't dig into godot's sky implementation, but the radiance cache looks unnecessarily large to me. I feel it's fine for most cases with one sky panorama for high quality background drawing, and a single layer cubemap with 5 mipmaps for IBL, each mip stores prefilterred irradiance with different roughness.

**Comment by Zireael07** [comment] 2022-08-21 08:07
Whoa, why do you need 2048 radiance size? (And why isn't it capped lower, I seem to recall many discussions about IGPUs freezing even with 1024 or 512)

**Comment by Griefchief** [comment] 2022-08-21 08:54
I was playing with Sky settings and set it randomly, for who knows what reason, maybe I saw low resolution in SDFGI or SSAO or whatever. Ah, right, building windows look slightly nicer with 2048, as they happen to be reflective in the original .gtlf/blender shader and it translates into .gtlf file.

**Comment by Griefchief** [comment] 2022-08-21 09:00
It doesn't advertise eating 2.85 GB VRAM, 2048 feels like it should take 16mb or 64 at worst.

**Comment by Griefchief** [comment] 2022-08-21 09:01
And yes, I saw the tooltip, and either ignored it, or never saw it when setting it. At least i did not see an issue when setting it...

**Comment by Griefchief** [comment] 2022-08-21 09:04
We need to measure this differently, or with an additional number in the setting mentioning VRAM size, i feel.

**Comment by Calinou** [comment] 2022-08-21 20:42
Radiance sizes above 512 should probably not be exposed, like in 3.x. It's very unlikely that radiance sizes above 512 will make any meaningful visual difference. If you need very sharp reflections, chances are that you'll be using ReflectionProbes anyway.

**Comment by clayjohn** [comment] 2023-01-14 02:15
Duplicate of https://github.com/godotengine/godot/issues/64683 For clarity, a radiance size of 2048 is expected to take multiple GBs of VRAM, the future work here is to communicate that effectively to users and see if we can shrink the default memory usage to something more palatable.

**Closed by clayjohn** 2023-01-14 02:15 UTC
Labels: bug, topic:rendering, regression, topic:3d, performance
