### ISSUE TITLE
Object::emit_signal needs to check for @tool

### ISSUE THREAD

**Issue by Gallilus** [godotengine/godot#82493] opened 2023-09-28 18:34 UTC
### Godot version

v4.1.beta

### System information

Windows 10

### Issue description

[here](https://github.com/godotengine/godot/blob/fbe611e45eebe48e2fdf4065fc70acad1cca2e0e/core/object/object.cpp#L1128-L1131) an error is generated like this [example](https://ask.godotengine.org/83674/why-cant-godot-find-and-call-this-method)

This is solved by adding the `@tool` keyword is it possible to check if the Editor is running [this](https://github.com/godotengine/godot/blob/fbe611e45eebe48e2fdf4065fc70acad1cca2e0e/core/object/object.cpp#L1117) line?

If so error text may suggest the tool keyword.

### Steps to reproduce

```
tool
extends EditorPlugin

var dialogue_editor_window_path = "res://addons/DialogueEditor/DialogueEditorWindow.tscn"

func _enter_tree():
    InputMap.add_action("open_dialogue_editor")
    var new_input_event = InputEventKey.new()
    new_input_event.set_scancode(KEY_Q)
    InputMap.action_add_event("open_dialogue_editor", new_input_event)

func _exit_tree():
    InputMap.erase_action("open_dialogue_editor")

func _input(event):
    if event.is_action_pressed("open_dialogue_editor"):
        var dialogue_editor_window = load(dialogue_editor_window_path).instance()
        dialogue_editor_window.get_node("Button").connect("pressed",dialogue_editor_window,"_on_button_pressed")
        add_child(dialogue_editor_window)
```

```
extends Panel

func _on_button_pressed():
    queue_free()
```

### Minimal reproduction project

not available

**Comment by dalexeev** [comment] 2023-09-28 20:32
We could make a list of classes that should be used with `@tool` and generate a warning if it is missing. I had this thought while working on #78178.

**Comment by KoBeWi** [comment] 2024-11-07 19:58
Was this resolved by #94511?

**Comment by dalexeev** [comment] 2024-11-07 21:07
Looks like it. Then we should close this as a duplicate of #36592. I misunderstood this issue last time.

**Comment by KoBeWi** [comment] 2024-11-08 10:34
Closing per above comment.

**Closed by KoBeWi** 2024-11-08 10:34 UTC
Labels: discussion, topic:core, topic:gdscript
