### ISSUE TITLE
weird behaviour of ClassDB when using C++ templates

### ISSUE THREAD

**Issue by frankiezafe** [godotengine/godot#28921] opened 2019-05-15 18:00 UTC
**Godot version:**

5e837b3f13ab1e3b31bb8d705e87820fa4eff21e

**OS/device including version:**

Linux Mint 18.2 64-bit kernel 4.8.0-53-generic

**Issue description:**

When binding methods of a daughter class, the documentation appears in the mother class.

![image4144](https://user-images.githubusercontent.com/3447074/57797046-dae0e300-7749-11e9-91f6-27039b0de0d1.png)

The class structure is a bit complex:
- SkinGroup extends Object
  GDCLASS(SkinGroup, Object)
  - SkinGList\<T\> extends SkinGroup
    - SkinGListEdge\<T\> extends SkinGList
      - SkinGroupEdge extends SkinGListEdge\<SkinEdge\>
      GDCLASS(SkinGroupEdge, SkinGroup)
      - SkinGroupFiber extends SkinGListEdge\<SkinFiber\>
      GDCLASS(SkinGroupFiber, SkinGroup)
      - SkinGroupLigament extends SkinGListEdge\<SkinLigament\>
      GDCLASS(SkinGroupLigament, SkinGroup)

SkinGroup::_bind_methods() is doing this (everything is fine there)

```c++
ClassDB::bind_method(D_METHOD("set_name", "name"), &SkinGroup::set_name);  

ClassDB::bind_method(D_METHOD("get_name"), &SkinGroup::get_name);
```

but when binding the methods of SkinGListEdge in SkinGroupEdge, SkinGroupFiber or SkinGroupLigament like this:

```c++

// from SkinGList
ClassDB::bind_method(D_METHOD("size"), &SkinGroupEdge::size);

// from SkinGList
ClassDB::bind_method(D_METHOD("empty"), &SkinGroupEdge::empty);

// from SkinGListEdge
ClassDB::bind_method(D_METHOD("set_stiffness", "stiffness"), &SkinGroupEdge::set_stiffness);

// from SkinGListEdge
ClassDB::bind_method(D_METHOD("get_stiffness"), &SkinGroupEdge::get_stiffness);
```

the generated documentation of the three classes stays empty and all methods are documented in SkinGroup...

method **static void _bind_methods();** is present in .h for all classes

**Steps to reproduce:**

- clone the repo https://gitlab.com/frankiezafe/SoftSkin/tags/issue_classdb in modules, 
- compile, 
- launch godot,
- go to script and
- search for SkinGroup, SkinGroupEdge, SkinGroupFiber and SkinGroupLigament

**Minimal reproduction project:**

no need to have a specific project as it is a issue with class registration in the DB

**Comment by frankiezafe** [comment] 2019-05-15 18:04
[update] same issue when using:

```c++
GDCLASS(SkinGroupEdge, Object)
```
issue is still there

**Comment by akien-mga** [comment] 2019-05-16 06:38
Is the issue only with the generated documentation, or also with the scripting API? (e.g. can you call `size()` on a `SkinGroup`, or does it fail compiling?

**Comment by frankiezafe** [comment] 2019-05-16 11:14
i will test this today and report it asap

**Comment by frankiezafe** [comment] 2019-05-16 16:43
the gdscript access is working fine! all methods are accessible on SkinGroupEdge, SkinGroupFiber and SkinGroupLigament (the leaves of the class hierarchy)

when starting godot, i get a lot of errors:

```
ERROR: bind_methodfi: Class SkinGroup already has a method size
   At: core/class_db.cpp:1216.
ERROR: bind_methodfi: Class SkinGroup already has a method empty
   At: core/class_db.cpp:1216.
ERROR: bind_methodfi: Class SkinGroup already has a method set_stiffness
   At: core/class_db.cpp:1216.
ERROR: bind_methodfi: Class SkinGroup already has a method get_stiffness
   At: core/class_db.cpp:1216.
ERROR: bind_methodfi: Class SkinGroup already has a method set_shrink
   At: core/class_db.cpp:1216.
ERROR: bind_methodfi: Class SkinGroup already has a method get_shrink
   At: core/class_db.cpp:1216.
ERROR: bind_methodfi: Class SkinGroup already has a method set_muscle_frequency
   At: core/class_db.cpp:1216.
ERROR: bind_methodfi: Class SkinGroup already has a method get_muscle_frequency
   At: core/class_db.cpp:1216.
ERROR: bind_methodfi: Class SkinGroup already has a method set_muscle_min
   At: core/class_db.cpp:1216.
ERROR: bind_methodfi: Class SkinGroup already has a method get_muscle_min
   At: core/class_db.cpp:1216.
ERROR: bind_methodfi: Class SkinGroup already has a method set_muscle_max
   At: core/class_db.cpp:1216.
ERROR: bind_methodfi: Class SkinGroup already has a method get_muscle_max
   At: core/class_db.cpp:1216.
ERROR: bind_methodfi: Class SkinGroup already has a method size
   At: core/class_db.cpp:1216.
ERROR: bind_methodfi: Class SkinGroup already has a method empty
   At: core/class_db.cpp:1216.
ERROR: bind_methodfi: Class SkinGroup already has a method set_stiffness
   At: core/class_db.cpp:1216.
ERROR: bind_methodfi: Class SkinGroup already has a method get_stiffness
   At: core/class_db.cpp:1216.
ERROR: bind_methodfi: Class SkinGroup already has a method set_shrink
   At: core/class_db.cpp:1216.
ERROR: bind_methodfi: Class SkinGroup already has a method get_shrink
   At: core/class_db.cpp:1216.
ERROR: bind_methodfi: Class SkinGroup already has a method set_muscle_frequency
   At: core/class_db.cpp:1216.
ERROR: bind_methodfi: Class SkinGroup already has a method get_muscle_frequency
   At: core/class_db.cpp:1216.
ERROR: bind_methodfi: Class SkinGroup already has a method set_muscle_min
   At: core/class_db.cpp:1216.
ERROR: bind_methodfi: Class SkinGroup already has a method get_muscle_min
   At: core/class_db.cpp:1216.
ERROR: bind_methodfi: Class SkinGroup already has a method set_muscle_max
   At: core/class_db.cpp:1216.
ERROR: bind_methodfi: Class SkinGroup already has a method get_muscle_max
   At: core/class_db.cpp:1216.
```
as the methods are not available in SkinGroupEdge, SkinGroupFiber and SkinGroupLigament, it seems that the classdb is registering them in the first known ancestor, SkinGroup in this case. Just to be clear, the methods are declared in the 2 templates between SkinGroup and SkinGroupEdge.

i have made an attempt to register methods in each template:

```c++

template< class T >
class SkinGList : public SkinGroup {
    GDCLASS(SkinGList<T>, SkinGroup);
// some code
protected:
    void _bind_methods() {
        ClassDB::bind_method(D_METHOD("size"), &SkinGList<T>::size);
        ClassDB::bind_method(D_METHOD("empty"), &SkinGList<T>::empty);
    }
};

template< class T >
class SkinGListEdge : public SkinGList< T > {
    GDCLASS(SkinGListEdge<T>, SkinGList<T>);
// some code
protected:

    void _bind_methods() {
        ClassDB::bind_method(D_METHOD("set_stiffness", "stiffness"), &SkinGListEdge<T>::set_stiffness);
        // other bindings
};

// and eventually

class SkinGroupEdge : public SkinGListEdge<SkinEdge> {
    GDCLASS(SkinGroupEdge, SkinGListEdge<SkinEdge>);
// some code
};

```

this is returning tons of errors (partial print)

```
                 from modules/softskin/register_types.cpp:48:
modules/softskin/skingroup.h: In static member function 'static String SkinGListEdge<T>::get_category_static()':
./core/object.h:276:7: error: '_get_category' was not declared in this scope
   if (_get_category != m_inherits::_get_category) {                                                                  
       ^
modules/softskin/skingroup.h:120:5: note: in expansion of macro 'GDCLASS'
     GDCLASS(SkinGListEdge<T>, SkinGList<T>);
     ^
modules/softskin/skingroup.h: In member function 'virtual bool SkinGListEdge<T>::_getv(const StringName&, Variant&) const':
./core/object.h:324:26: error: there are no arguments to '_get' that depend on a template parameter, so a declaration of '_get' must be available [-fpermissive]
    if (_get(p_name, r_ret))                                                                                          
                          ^
modules/softskin/skingroup.h:120:5: note: in expansion of macro 'GDCLASS'
     GDCLASS(SkinGListEdge<T>, SkinGList<T>);

```

and so on for _set, _is_gpl_reversed, _get_property_list...

i can not see any other way to bind these methods properly, and as the c++ is compiling & running smoothly, i think there is something to fix in the ClassDB::bind_method mechanism...

good luck for the fix, i can update and make some test on commit related to this topic!

**Comment by ptrojahn** [comment] 2019-07-02 15:04
I think the problem is that you try to bind methods of another class. For example when binding SkinGroupEdge::size your are actually binding SkinGList::size. ClassDB::bind_method now tries to get the type of SkinGList by calling get_class_static, which doesn't exist, because it's not a  GDCLASS, so the get_class_static function of the parent SkinGroup is called. This is a limitation of how bind_method extracts the class from the function pointer and I don't think this can be fixed without changing the binding API. Easiest way to solve this would probably be to add and bind proxy functions that call the real functions internally to all leaves or find a way to restructure SkinGList to work without templates. #30188 might be interesting for this.

**Comment by KoBeWi** [comment] 2020-09-27 22:44
Can anyone still reproduce this bug in Godot 3.2.3 or any later release?

**Comment by akien-mga** [comment] 2020-12-10 23:04
No answer, so closing.

**Closed by akien-mga** 2020-12-10 23:04 UTC
Labels: bug, topic:core
