### ISSUE TITLE
Floating script editor losing focus on save

### ISSUE THREAD

**Issue by DonutWrecker** [godotengine/godot#79027] opened 2023-07-04 14:28 UTC
### Godot version

v4.1.rc3

### System information

Godot v4.1.rc3 - Windows 10.0.19045 - Vulkan (Compatibility) - NVIDIA GeForce GTX 1650 (NVIDIA; 31.0.15.3640) - AMD Ryzen 3 3100 4-Core Processor (8 Threads)

### Issue description

When writing on a floating script editor on a secondary display, saving the script file via ctrl+s causes the floating editor window to lose focus, making the primary Godot window focused, requiring manually switching to the floating window again.

### Steps to reproduce

Make the script editor window floating, and move it to another display. Write a trivial script file, and hit ctrl+s.

### Minimal reproduction project

N/A

**Comment by aryyya** [comment] 2023-07-08 02:23
This also happens for me on macOS Ventura and v4.1.stable.official.

I have both the main editor window and the floating code editor window on a single monitor, both maximized.

When I use Cmd+S to save the script, the main editor window immediately steals focus and covers the floating code editor window.

**Comment by quinnyo** [comment] 2023-07-08 06:09
Duplicate of #78672 ?

**Closed** 2023-07-08 07:04 UTC
Labels: bug, topic:editor, topic:porting
