### ISSUE TITLE
Basis' GetEuler function returns wrong angles under certain conditions

### ISSUE THREAD

**Issue by Maveyyl** [godotengine/godot#66268] opened 2022-09-22 16:56 UTC
### Godot version

4.0-beta1_mono_win64

### System information

Windows 10

### Issue description

While lerping a basis and getting its euler angle I got results that visually were wrong and also seemed wrong in numbers.

Basis : [X: (0, 0,040403813, 0,9991835), Y: (1, 1,1920929E-07, 0), Z: (-1,1920929E-07, 0,9991835, -0,040403843)]
Euler: (-1,5303826,    -3,1415896,    1,5707934)

Next frame:

Basis:  [X: (0, 0, 1), Y: (1, 0, 0), Z: (0, 1, 0)]
Euler: (-1,5707964,    1,5707964,     0)

The basis are very close, but by getting the euler of the second one I expect a value more like (-1.57, 0, 1.57...).

Out of the 24 rotations I'm working with only 4 to 8 seem to be affected by this issue.

## Code:

```C#
Basis basis1 = new Basis( new Vector3(0, 0.040403813f, 0.9991835f),  new Vector3(1, 0, 0), new Vector3(0, 0.9991835f, -0.040403843f));
Basis basis2 = new Basis(  new Vector3(0, 0, 1),  new Vector3(1, 0, 0),  new Vector3(0, 1, 0) );
GD.Print("basis1:");
GD.Print( basis1 );
GD.Print("basis1.GetEuler():");
GD.Print(basis1.GetEuler());
GD.Print("basis2:");
GD.Print( basis2 );
GD.Print("basis2.GetEuler():");
GD.Print(basis2.GetEuler());
```

## Prints:

basis1:
[X: (0, 0,040403813, 0,9991835), Y: (1, 0, 0), Z: (0, 0,9991835, -0,040403843)]

basis1.GetEuler():
(-1,5303826, 3,1415927, 1,5707964)

basis2:
[X: (0, 0, 1), Y: (1, 0, 0), Z: (0, 1, 0)]

basis2.GetEuler():
(-1,5707964, 1,5707964, 0)

**Comment by fire** [comment] 2022-09-22 17:51
Just for fun can you try cubic interpolate with? We did more work there.

**Comment by kleonc** [comment] 2022-09-22 18:53
> While lerping a basis and getting its euler angle I got results that visually were wrong and also seemed wrong in numbers.
> 
> Basis : [X: (0, 0,040403813, 0,9991835), Y: (1, 1,1920929E-07, 0), Z: (-1,1920929E-07, 0,9991835, -0,040403843)] Euler: (-1,5303826, -3,1415896, 1,5707934)
> 
> Next frame:
> 
> Basis: [X: (0, 0, 1), Y: (1, 0, 0), Z: (0, 1, 0)] Euler: (-1,5707964, 1,5707964, 0)
> 
> The basis are very close, but by getting the euler of the second one I expect a value more like (-1.57, 0, 1.57...).

It should rather result in something like (-1.57, -1.57, 0).

- Close to the first basis ((-1,5303826, -3,1415896, 1,5707934) ~= (-PI / 2, -PI, PI / 2)):
![ICLZNtoi52](https://user-images.githubusercontent.com/9283098/191825475-57f722b1-68a8-4983-b446-ca5cdecd2f6c.png)
- The incorrect result ((-1,5707964, 1,5707964, 0) ~= (-PI / 2, PI / 2, 0)):
![6PMYLCam8x](https://user-images.githubusercontent.com/9283098/191825982-c29bbe0b-1b13-43e1-8001-5ea0687b0660.png)
- Your suggested result ( (-1.57, 0, 1.57) ~= (-PI / 2, 0, PI / 2)):
![GxKUt5Vvpa](https://user-images.githubusercontent.com/9283098/191826211-02fbfab0-f8a6-4014-ba94-e34d90e41462.png)
- Would-be-proper result ((-1.57, -1.57, 0) ~= (-PI / 2, -PI / 2, 0)):
![i4wpDnjKCO](https://user-images.githubusercontent.com/9283098/191826318-41e88400-1440-4dac-a7f9-98dceaec561c.png)


In GDScript `get_euler` seems to work fine. This:
```gdscript
@tool
extends EditorScript

func _run():
	var basis1 := Basis(Vector3(0, 0.040403813, 0.9991835), Vector3(1, 0, 0),Vector3(0, 0.9991835, -0.040403843))
	var basis2 := Basis(Vector3(0, 0, 1), Vector3(1, 0, 0), Vector3(0, 1, 0) )
	print("basis1:")
	print( basis1 )
	print("basis1.get_euler():")
	print(basis1.get_euler())
	print("basis2:")
	print( basis2 )
	print("basis2.get_euler():")
	print(basis2.get_euler())
```
Outputs (by default `get_euler()` returns YXZ Euler angles so these are the same as above):
```
basis1:
[X: (0, 0.040404, 0.999183), Y: (1, 0, 0), Z: (0, 0.999183, -0.040404)]
basis1.get_euler():
(-1.530383, 3.141593, 1.570796)
basis2:
[X: (0, 0, 1), Y: (1, 0, 0), Z: (0, 1, 0)]
basis2.get_euler():
(-1.570796, -1.570796, 0)
```

---

Seems different Euler angles conventions were not ported to dotnet/mono, its `GetEuler` takes no parameter and is claimed to work in YXZ convention (but as proven above it's not even working properly):
https://github.com/godotengine/godot/blob/62792eeb9fac4f44272f59f95ec8eb3abc0432a7/modules/mono/glue/GodotSharp/GodotSharp/Core/Basis.cs#L246-L286

Porting `Basis` changes from #54084 to dotnet/mono should probably fix these issues.

Not sure if there's anything wrong with some interpolation, haven't checked none of these.

**Comment by Maveyyl** [comment] 2022-09-22 19:24
Woops my bad I sometimes wrongly think pi is a whole turn when it's just half.

The interpolation part is indeed irrelevant, it is just extra context to show where I noticed the weird behavior. Thanks for confirming the problem!

**Comment by aaronfranke** [comment] 2022-09-22 19:36
> Woops my bad I sometimes wrongly think pi is a whole turn when it's just half.

I find it much easier to think and write expressions in terms of TAU (which is supported in Godot in both GDScript and C#)

**Comment by Maveyyl** [comment] 2022-09-22 19:52
Oh that's perfect! Thank you :D

**Comment by fire** [comment] 2022-09-23 19:05
Was lerping a basis and getting its euler angle incorrect caused by Godot Engine? Can I close?

**Comment by kleonc** [comment] 2022-09-23 21:43
> Was lerping a basis and getting its euler angle incorrect caused by Godot Engine?

According to @Maveyyl's comment lerping/interpolating is irrelevant, it was just when they spotted the issue. And yes, getting incorrect euler angles from a basis is caused by the Godot Engine, check my previous comment for more details.

>Can I close?

Yes, after it will be fixed (so not yet). :slightly_smiling_face:

What needs to be done? I'll quote myself:

> Porting `Basis` changes from #54084 to dotnet/mono should probably fix these issues.
> `Basis.GetEuler` needs to be fixed in `3.x` as well.

To be clear: it seems to be (C#/dotnet/mono)-only issue.

**Closed** 2022-10-03 07:33 UTC
Labels: bug, confirmed, topic:dotnet
