### ISSUE TITLE
when enable physics/common/physics_interpolation, the behavior of the game becomes very strange.

### ISSUE THREAD

**Issue by gnenux** [godotengine/godot#93620] opened 2024-06-26 08:03 UTC
### Tested versions

- Reproducible in: 4.3-beta2

### System information

Godot v4.3.beta2.mono - Windows 10.0.22631 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 4070 Ti (NVIDIA; 31.0.15.5244) - Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz (12 Threads)

#### not enable physics/common/physics_interpolation

https://github.com/godotengine/godot/assets/14236891/949e3ac8-1746-4d5f-b1c5-552cc85f71cd

#### enable physics/common/physics_interpolation
![屏幕截图 2024-06-26 155414](https://github.com/godotengine/godot/assets/14236891/bdd7453d-af4e-4940-8807-bf461b8dcaa9)

https://github.com/godotengine/godot/assets/14236891/d3662cae-db9f-4808-97f3-affc148c6c03

### Steps to reproduce

please refer to the attachment's project file.

- Player.cs
- Weapon.cs
- Projectile.cs

### Minimal reproduction project (MRP)

[physicsinterpolation.zip](https://github.com/user-attachments/files/15984308/physicsinterpolation.zip)

**Comment by 4X3L82** [comment] 2024-06-26 15:02
This might be a duplicate of #93586?

**Comment by cosparks** [comment] 2024-07-02 04:22
Can confirm that this issue is fixed by the changes I'm working on for #93586.

Here is an even more minimal mrp for anyone who is curious: [physics_interp_rotation_bug.zip](https://github.com/user-attachments/files/16061628/physics_interp_rotation_bug.zip). I modified it to use gdscript instead of c#, and also updated it so the rotating sprite's transform is set in `_physics_process` instead of `_process`.

**Comment by cosparks** [comment] 2024-07-03 02:30
@akien-mga this can be closed as it was fixed by the changes I proposed yesterday in #93586 which were merged in #93852

**Closed** 2024-07-07 13:48 UTC
Labels: bug, topic:physics, needs testing
