### ISSUE TITLE
StyleBoxFlat aliasing looks blurry (regression between 3.2beta5 and 3.2beta6)

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#35279] opened 2020-01-18 13:36 UTC
Godot 3.2 beta5

Same stylebox, two versions.
Godot 3.2, beta5, worked fine:

![image](https://user-images.githubusercontent.com/1311555/72664623-0c582f80-39f8-11ea-8cc8-d819adfce932.png)

Godot 3.2, beta6 and rc1:

![image](https://user-images.githubusercontent.com/1311555/72664641-30b40c00-39f8-11ea-85bb-bdf43f904dc8.png)

Now it is blurry and has a line at the bottom.
Turning off antialiasing "fixes" it, but it looks worse than before.

Project:
[TabContainerTheme.zip](https://github.com/godotengine/godot/files/4080739/TabContainerTheme.zip)

It might have been broken in https://github.com/godotengine/godot/issues/34830, but if you look closely at the screenshots, only the inner parts were lacking anti-alias, while the outline parts were fine all along.

**Comment by akien-mga** [comment] 2020-01-18 14:25
CC @pouleyKetchoupp

**Comment by pouleyKetchoupp** [comment] 2020-01-18 16:17
@Zylann I think this use case can be fixed easily by adjusting the expand margin on either the tab itself or the panel. Although, in the current version it's limited because values are rounded to integers. So I've made a little fix in PR #35286 to allow finer tuning. It seems to look fine with this change after tweaking the following value in your script:
`tab_panel.set_expand_margin_all(3.5)`

Note: Border anti-aliasing size has slightly changed several times since 3.2 Beta 3 in order to fix some inconsistencies. This case with no border on one side wasn't working at all prior to 3.2 (see PR #34488), so there's no retro-compatibility issue here.

**Comment by Zylann** [comment] 2020-01-18 18:07
Is there any way to make this more straightforward? Having to use a decimal number isn't obvious for the expected effect. On the contrary, I would have thought decimal numbers would cause that issue, not fix it (although as a coder I get that somehow, this is not true antialiasing and compromises were made...).

With your fix and decimal expand margins, it fixes the horizontal line, but it still looks bad:
![image](https://user-images.githubusercontent.com/1311555/72668318-6b7c6b00-3a1d-11ea-9dbd-5ea213acb386.png)

**Comment by pouleyKetchoupp** [comment] 2020-01-19 09:15
Did you set anything in particular in order to get all the details, like a scale? I don't get the same results when rendering on my computer.

Here's how it renders with
`tab_panel.set_expand_margin_individual(3, 3.5, 3, 3)`
![image](https://user-images.githubusercontent.com/1075032/72677965-ebe4af80-3aa1-11ea-8463-dee29fe6fd0d.png)

And can you try with these settings as well?
`tab_fg.set_expand_margin_individual(0, 2, 0, -0.55)`
`tab_panel.set_expand_margin_individual(3, 3.2, 3, 3)`
![image](https://user-images.githubusercontent.com/1075032/72678105-00757780-3aa3-11ea-8730-08756112ab4d.png)

I feel like this is good enough. If you need to use larger size UI, you can try increasing the anti-aliasing size too.

**Comment by Zylann** [comment] 2020-01-19 15:54
I did not scale anything. I only upscaled the screenshots in an image editor using nearest-neighbor quality just so you don't have to squint to see the details.

Your screenshots look all blurry Oo

**Comment by pouleyKetchoupp** [comment] 2020-01-23 14:44
@Zylann I'm not sure what is causing this difference in our screenshots when zoomed in, but let's focus on the different artefacts and how to solve them.

- Pixels on the left corner: could you try the two other sets of values I gave you in my last examples? I'd like to know if you're able to get rid of the issue. Also, could it be due to the nearest neighbor zoom in you do in your image editor?

- Thinner right border: from your screenshot, it seems it might be due to the next tab header slightly overlapping with the left one. Can you double check that by removing the other tab and see if the glitch is still present?

In general, I don't really understand what the problem is with decimal values to adjust UI settings (it just seems like it allows more control to me). But if we want to be able to setup everything with integer values only, then we'll need a deeper rework of how this stylebox aa works.

**Comment by Zylann** [comment] 2020-01-23 19:23
> Pixels on the left corner: could you try the two other sets of values I gave you in my last examples? I'd like to know if you're able to get rid of the issue. 

With `tab_panel.set_expand_margin_individual(3, 3.5, 3, 3)`
Line disappeared and the top of the panel becomes solid, but its sides are blurry.
![image](https://user-images.githubusercontent.com/1311555/73015060-3a33de80-3e13-11ea-9d7b-be912bb413f4.png)

With
```
tab_fg.set_expand_margin_individual(0, 2, 0, -0.55)
tab_panel.set_expand_margin_individual(3, 3.2, 3, 3)
```
Line disappeared but the rest is still blurry.
![image](https://user-images.githubusercontent.com/1311555/73015065-3e5ffc00-3e13-11ea-806f-af50a04ecf49.png)

> Also, could it be due to the nearest neighbor zoom in you do in your image editor?

No, I scaled by 2x (integer amount) and keeping ratio. 
You can check the theme from the editor: [theme.zip](https://github.com/godotengine/godot/files/4104952/theme.zip)

> Thinner right border: from your screenshot, it seems it might be due to the next tab header slightly overlapping with the left one. Can you double check that by removing the other tab and see if the glitch is still present?

Yeah, I'm pretty sure it's the neighbor tab. Increasing margin does that.

> In general, I don't really understand what the problem is with decimal values to adjust UI settings (it just seems like it allows more control to me).

I don't have a problem with decimal values, but the fact it becomes necessary to enter half-way numbers to obtain a non-blurry result. It's not intuitive, as I would have expected the opposite to happen: integer values should surely line up, half-way values should produce blurry pixel lines.

After fiddling around, this is the best I could get:
```
tab_fg.set_expand_margin_individual(0.5, 2, -0.5, -0.55)
tab_panel.set_expand_margin_individual(3.4, 3.5, 3.4, 3)
```
![image](https://user-images.githubusercontent.com/1311555/73016195-4c168100-3e15-11ea-992e-e2e41c9823a0.png)

> if we want to be able to setup everything with integer values only, then we'll need a deeper rework of how this stylebox aa works.

As said above I'm not against decimals, but I feel we need true AA or a rework of the way it's done (if faked?). It takes time to fiddle around precise decimals until they all line up properly.

**Comment by pouleyKetchoupp** [comment] 2020-01-24 10:26
Ok, I think I understand now what you're trying to achieve. You would like border sides to be solid lines and only corners to use aa, right?

What you call blurry is actually the expected behavior from the way aa is implemented right now. It adds some alpha inside and outside all along the border to make things consistent in different cases (it's faked aa as you guessed).

In some cases, you get solid lines and I'm not sure why. Maybe the decimal values cause a one pixel line of alpha to be skipped depending on the resolution.

Also I've figured out why the rendering was blurry for me. My screen is high DPI, so I have to check the project option "Allow HighDpi" if I want to keep the high resolution. It makes UI very small instead of the blurry scale up I had before.

So here's my result with your latest settings on my screen:
(I'm scaling it up by 2x in an external editor like you did)
![image](https://user-images.githubusercontent.com/1075032/73060740-cfc58180-3e98-11ea-9d0f-f6cfb4483238.png)

What I can propose is to look again at the aa code and see if I can make it so border sides would be solid like you expect. I think it does make sense since we probably need only the corners to be anti-aliased. But there are lots of different combinations to handle, I'm not sure what other problems I might hit. I'll let you know.

Note: The missing sliders for decimal values are addressed in PR #35287.

**Comment by Calinou** [comment] 2020-10-10 19:00
What's the status on this as of 3.2.3?

**Comment by Zylann** [comment] 2020-12-13 15:35
Yes it's still there.

**Comment by Calinou** [comment] 2021-08-02 16:46
I can still reproduce this in 4.0.dev.custom_build [b5b633ff5].

**Comment by Nuciloco** [comment] 2021-08-02 23:18
I think the issue with AA should be fixed rather than trying to bypass the issue. Either that or there should be new properties that allow certain sides of borders to be blurry and sharp.

**Comment by Calinou** [comment] 2021-08-02 23:51
> I think the issue with AA should be fixed rather than trying to bypass the issue. Either that or there should be new properties that allow certain sides of borders to be blurry and sharp.

One way to fix this would be to change StyleBoxFlat's antialiased property to use an enum instead, with three possible values:

- Disabled
- Crisp (what we had in 3.1.x)
- Smooth (what we have now)

**Comment by pouleyKetchoupp** [comment] 2021-08-02 23:58
@Calinou That sounds like a great idea! We could do that for 3.x since proper antialiasing will be probably supported only in 4.x.

**Comment by Calinou** [comment] 2021-08-03 00:00
> @Calinou That sounds like a great idea! We could do that for 3.x since proper antialiasing will be probably supported only in 4.x.

Switching to an enum will break compatibility, so we'll have to add a second boolean property in `3.x` instead.

**Comment by pouleyKetchoupp** [comment] 2021-08-03 04:03
> Switching to an enum for the `antialiased` property will break compatibility with existing projects, so we'll have to add a second boolean property in `3.x` instead.

@Calinou Couldn't we handle compatibility in 3.x by overriding the property `_set` function and set a specific value when `antialiased` is true? And then if it's still needed on master it can be done with compatibility breaking to make the code cleaner.

**Closed** 2021-08-11 05:35 UTC
Labels: bug, confirmed, regression, topic:gui
