### ISSUE TITLE
Area2D detects incorrect collisions when using Camera2D

### ISSUE THREAD

**Issue by rainbowism** [godotengine/godot#21457] opened 2018-08-26 20:16 UTC
**Godot version:**
5df9109

**OS/device including version:**
Windows 7 Ultimate 64-bit

**Issue description:**
Area2D's collision doesn't follow it around when you move it using Camera2D. Results in collisions based on coordinates relative to the top left of the viewport rather than game world. The same behaviour doesn't happen in 3.0.6.

**Steps to reproduce:**
Create an Area2D, and a KinematicBody2D with a Camera2D attached to it. Enable `current` to see the issue.

**Minimal reproduction project:**
[Area2DTest.zip](https://github.com/godotengine/godot/files/2321875/Area2DTest.zip)

**Comment by nobuyukinyuu** [comment] 2018-08-27 03:48
dupe of #21289 , I noticed that several people are reporting this issue with 5df9109, possibly because calinou's buildserver hasn't produced a new build since the 22nd and this has been the build being served up since then.

**Comment by rainbowism** [comment] 2018-08-27 04:04
Yeah, seems to be the case. I made a build on master and all is good now.

**Closed** 2018-08-27 04:39 UTC
