### ISSUE TITLE
Editor Places C# signal connections outside class definition

### ISSUE THREAD

**Issue by silenuz** [godotengine/godot#73232] opened 2023-02-13 16:11 UTC
### Godot version

v4.0.rc1.mono.official [8843d9ad3]

### System information

Windows 10

### Issue description

When using the editor to connect signals in C# the signal method is placed outside the class definition.

I have the following scene layout:

![Scenelayout](https://user-images.githubusercontent.com/13521146/218509010-3d388c98-ca01-4614-aa68-3c614791f22c.png)

Here's the initial generated class:

![inititialScript](https://user-images.githubusercontent.com/13521146/218508311-439f3a4c-78ea-4cf9-9cfd-2ab558f0a588.png)

Here's what it looks like after selecting the button and connecting the pressed signal:

![afterconnectingSignal](https://user-images.githubusercontent.com/13521146/218508508-28a46f2c-6b3c-419b-84a1-4e04c51c36eb.png)

### Steps to reproduce

1. Create a project
2. Add a node, in my case a panel
3. Add button to panel
4. Choose signals for the button
5. Select pressed or any other signal
6. Click connect
7. Keep defaults in dialog, and click connect
8. View the C# class file the signal is outside the class

### Minimal reproduction project

[testone.zip](https://github.com/godotengine/godot/files/10724000/testone.zip)

**Comment by akien-mga** [comment] 2023-02-13 17:22
Duplicate of #18721

**Closed by akien-mga** 2023-02-13 17:22 UTC
