### ISSUE TITLE
Crash (exit with code 0) when opening any project on my laptop

### ISSUE THREAD

**Issue by balintmaci** [godotengine/godot#55380] opened 2021-11-27 10:41 UTC
### Godot version

v3.4.stable.official.206ba70f4

### System information

Windows 11, Surface Pro 6, Intel(R) UHD Graphics 620, GLES2/3

### Issue description

I've been working on a project on a desktop PC running Windows 10 and everything works fine there. I wanted to look at something in the project from my laptop so I installed the latest stable Godot version using scoop package manager (same as on desktop), cloned my repository, and tried to open it on the laptop. Process exits with code 0. I tried to create new projects with both GLES2 and 3 renderers and the same thing happens.
Terminal output (in Windows Terminal)
```
Godot Engine v3.4.stable.official.206ba70f4 - https://godotengine.org
OpenGL ES 3.0 Renderer: Intel(R) UHD Graphics 620
OpenGL ES Batching: ON

Editing project: <path to project on my pc> (<path to project on my pc>)
Godot Engine v3.4.stable.official.206ba70f4 - https://godotengine.org
OpenGL ES 2.0 Renderer: Intel(R) UHD Graphics 620
OpenGL ES Batching: ON

[process exited with code 0]
```

### Steps to reproduce

Open a project on a Surface Pro 6 running Windows 11? Not so sure

**Comment by akien-mga** [comment] 2021-11-27 11:31
Duplicate of https://github.com/godotengine/godot/issues/54076

**Closed by akien-mga** 2021-11-27 11:31 UTC
