### ISSUE TITLE
Windows desktop export: Rcedit failed to change exe info & icon when creating the exe file 

### ISSUE THREAD

**Issue by Yuki001** [godotengine/godot#21360] opened 2018-08-24 11:09 UTC
**Godot version:**

Godot 3.0.6
Rcedit 1.1.0

**OS/device including version:**

Win10 64bit

**Issue description:**

When export exe file for windows desktop, the rcedit failed to change the exe file's infomation 
It outputs:
 "Fatal error: Unable to commit changes".
If the exe file exists, the rcedit works correctly. the issue only happen when the exe file create first time.
May be the exporter should wait some time between "create the exe" and "call rcedit" to solve this issue.

**Comment by akien-mga** [comment] 2019-01-23 14:18
Is this still reproducible in the current master branch?

**Comment by Xrayez** [comment] 2019-01-23 14:47
Works alright with Rcedit 1.1.1/1.1.0 in master, both creating and replacing an executable on export, assuming correct steps taken from the [docs](https://docs.godotengine.org/en/latest/getting_started/workflow/export/changing_application_icon_for_windows.html) and as decribed in #21347.

@exts the issue with icon not updating in file explorer might be due to the fact that it's cached there, a reboot solved it in my case.

**Comment by akien-mga** [comment] 2019-01-23 14:56
Thanks, closing then. If documentation changes are needed, please open an issue on https://github.com/godotengine/godot-docs.

**Closed by akien-mga** 2019-01-23 14:56 UTC
Labels: bug, platform:windows, topic:editor

**Comment by Wolfyxon** [comment] 2024-03-12 17:41
I'm facing this issue in Godot 4.2.1 on Arch Linux.
rcedit suddenly stopped working for all projects (with default settings too).

![image](https://github.com/godotengine/godot/assets/58263600/a78bf0d8-2f33-4e20-b83d-839e43be9048)

wine-9.3
Rcedit v2.0.0

**Comment by Wolfyxon** [comment] 2024-03-12 18:34
Seems to be an issue with Wine.
I used lutris-GE-Proton8-25-x86_64 which I had laying around and it worked.
