### ISSUE TITLE
Program crashed with signal 4

### ISSUE THREAD

**Issue by axvemi** [godotengine/godot#75193] opened 2023-03-21 19:17 UTC
### Godot version

Godot_v4.0-stable_mono

### System information

Linux (EndeavourOS)

### Issue description

So, working with Godot, the editor is crashing, and I'm getting the following stacktrace. I cannot provide much information since I don't know what may be causing it. I did attach the project so you could reproduce it.

```
[axel@Endeavour-OS logs]$ godot4_mono --editor /home/drives/HDD_STORAGE/WORK/AXVEMI/GodotProjects/Worlds-Godot/
Godot Engine v4.0.stable.mono.official.92bee43ad - https://godotengine.org
libspeechd.so.2: cannot open shared object file: No such file or directory
OpenGL API 3.3.0 NVIDIA 525.89.02 - Compatibility - Using Device: NVIDIA Corporation - NVIDIA GeForce RTX 2060
 
Editing project: /home/drives/HDD_STORAGE/WORK/AXVEMI/GodotProjects/Worlds-Godot
Godot Engine v4.0.stable.mono.official.92bee43ad - https://godotengine.org
libspeechd.so.2: cannot open shared object file: No such file or directory
Vulkan API 1.3.224 - Forward+ - Using Vulkan Device #0: NVIDIA - NVIDIA GeForce RTX 2060
 
[axel@Endeavour-OS logs]$ WARNING: Blend file import is enabled in the project settings, but no Blender path is configured in the editor settings. Blend files will not be imported.
     at: _editor_init (modules/gltf/register_types.cpp:70)
ERROR: FATAL: Condition "!match" is true.
   at: ~CSharpInstance (modules/mono/csharp_script.cpp:2022)

================================================================
handle_crash: Program crashed with signal 4
Engine version: Godot Engine v4.0.stable.mono.official (92bee43adba8d2401ef40e2480e53087bcb1eaf1)
Dumping the backtrace. Please include this when reporting the bug to the project developer.
[1] /usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.3/libcoreclr.so(+0x4a899e) [0x7fc8a46a899e] (??:0)
[2] /usr/lib/libc.so.6(+0x38f50) [0x7fc8cbcecf50] (??:0)
[3] /usr/local/bin/Godot_v4.0_mono/Godot_v4.0-stable_mono_linux.x86_64() [0x1589f68] (??:0)
[4] /usr/local/bin/Godot_v4.0_mono/Godot_v4.0-stable_mono_linux.x86_64() [0x464be71] (??:0)
[5] /usr/local/bin/Godot_v4.0_mono/Godot_v4.0-stable_mono_linux.x86_64() [0xee3b50] (??:0)
[6] [0x7fc8285e010d] (??:0)
-- END OF BACKTRACE --
================================================================

```

### Steps to reproduce

Open the attached project
Open scenes => WorldGenerator.tscn
In the scene tree, inspect Node. It should have the WorldManager script attached.
Play with the settings (Grid Width and Grid Height) and click on Refresh to try it. It usually crashes when changing from 2x2 to 10x10 or like that. Not always.

### Minimal reproduction project

[Worlds-Godot.zip](https://github.com/godotengine/godot/files/11032723/Worlds-Godot.zip)

**Comment by RedworkDE** [comment] 2023-03-21 19:59
Duplicate of https://github.com/godotengine/godot/issues/70449

**Comment by Calinou** [comment] 2023-03-22 00:23
Duplicate of https://github.com/godotengine/godot/issues/70449.

**Closed by Calinou** 2023-03-22 00:23 UTC
