### ISSUE TITLE
3.2.1 GraphEdit Node - Zoom Bug

### ISSUE THREAD

**Issue by nonunknown** [godotengine/godot#37110] opened 2020-03-17 11:36 UTC
**Godot version:**
3.2.1 mono
**OS/device including version:**
ubuntu 19.10
**Issue description:**
* When zooming the GE Node the connections does not match the zoom
* Trying to connect GN with zoom out on max does not works too

![state](https://user-images.githubusercontent.com/58845030/76852676-98d17380-682a-11ea-87f5-5a999e35ac16.gif)

**Steps to reproduce:**

*Download MRP below
*Open GraphController.scn
*Press F6
*Reproduce what was made on the gif

**Minimal reproduction project:**
[asm.zip](https://github.com/godotengine/godot/files/4343218/asm.zip)

**Improvements Suggestions:**
https://github.com/godotengine/godot-proposals/issues/593

**Comment by fire** [comment] 2020-03-17 13:40
Here's my zoom pr, it's a bit old. I didn't have much time.

It has performance problems, and the GraphNode header has a mismatch bug.

https://github.com/godotengine/godot/pull/29091

**Comment by nonunknown** [comment] 2020-03-17 13:56
@fire thanks for that dude!

**Comment by akien-mga** [comment] 2021-03-19 08:18
Duplicate of #46425, fixed recently.

**Closed by akien-mga** 2021-03-19 08:18 UTC
Labels: bug, topic:gui
