### ISSUE TITLE
Resource import errors & unusable editor upon opening any project

### ISSUE THREAD

**Issue by syskrank** [godotengine/godot#26342] opened 2019-02-27 08:42 UTC
**Godot version:**
Godot 3.1 beta custom caa4266
**OS/device including version:**
Windows 10 x64

**Issue description:**
Upon opening the project there are tons of resource import errors.
In some cases the editor freezes & crashes.
Anyways, each alt+tab renders project unusable due to the error messages popping up ( due to additional or timer-based resources refresh ? )

![image](https://user-images.githubusercontent.com/11526664/53476617-e3e3e180-3a83-11e9-9ca2-f164a7a8011b.png)

**Steps to reproduce:**
Download [screen_space_shaders](https://github.com/godotengine/godot-demo-projects/tree/master/2d/screen_space_shaders) demo, import & edit.

Other projects behave in the same way.

**Comment by syskrank** [comment] 2019-02-27 09:02
Confirming the same issue on 8889089
Win10 x64

**Comment by akien-mga** [comment] 2019-02-27 09:04
Likely a regression from caa42667.

**Comment by syskrank** [comment] 2019-02-27 09:23
The issue is present on b1c221d

**Comment by syskrank** [comment] 2019-02-27 09:41
Checked out right to the 3b0f301, everything is fine there.

**Comment by akien-mga** [comment] 2019-02-27 09:46
If you can run `git bisect` between 3b0f301 (`git bisect good`) and b1c221d (`git bisect bad`), that would be great. The culprit is likely one of @reduz's ETC fixes, or #26331 potentially if the fixes to texture constructors would trigger some reimport loop somehow.

**Comment by hpvb** [comment] 2019-02-27 12:14
I can't reproduce this on current master on Win 10 home

**Comment by hpvb** [comment] 2019-02-27 12:20
Can you please try on this build: https://tmm.cx/nextcloud/s/9riMKz9iHNZYGqJ

**Comment by reduz** [comment] 2019-02-27 12:37
This bug was only apparent on Windows because of how file locking works in there. It's fixed now.

**Closed** 2019-02-27 12:41 UTC
Labels: bug, high priority, platform:windows, topic:editor
