### ISSUE TITLE
Fullscreen and borderless just remove window decorations in X11

### ISSUE THREAD

**Issue by warriormaster12** [godotengine/godot#63156] opened 2022-07-18 16:21 UTC
### Godot version

4.0-alpha 12

### System information

Manjaro KDE Plasma 5.24.5,kwin compositor, i5-4570, Gtx 1060 6gb (515.57), 16 gb ddr3, Vulkan

### Issue description

![image](https://user-images.githubusercontent.com/33091666/179556419-ba409a82-e0f7-447a-8d60-bf4f7a28064f.png)

Basically, instead of filling the whole screen with the game, it just removes the window decoration and that's it. Same thing happens when you override the window size from og(1280x720) to monitors full size (1920x1080). this happens when fullscreen is turned on, when borderless is turned on or when both settings are turned on.

### Steps to reproduce

1. Project Settings->Window
2. select fullscreen, borderless or both 
3. result in the screenshot

### Minimal reproduction project

Noticed a bug when creating a gmtk game jam game. Source code can be downloaded by selecting Diceanetor.tar.gz

[Link to the game](https://warriormaster12.itch.io/th)

**Comment by akien-mga** [comment] 2022-07-18 19:26
Duplicate of #54065

**Closed by akien-mga** 2022-07-18 19:26 UTC
Labels: bug, platform:linuxbsd, topic:porting, confirmed
