### ISSUE TITLE
Viewport textures not being drawn/applied when exported

### ISSUE THREAD

**Issue by Eorlanas** [godotengine/godot#75275] opened 2023-03-23 21:33 UTC
### Godot version

4.0.1

### System information

Windows 10

### Issue description

I'm 90% sure this is a bug, do scream at me if this isn't the case. Much of my project is based upon VideoStreamPlayer and ProgressBar nodes that are children of viewport nodes, and I then use that viewport as a texture for numerous Sprite3D nodes. When starting the project through the editor, this works fine (picture 1, the tv "screens" and the white rectangle around the bottom textbox). However, once I export it through the standard template, these textures simply don't show up (picture 2). I've tried using both Debug and Release versions of the template, to no success in either case.
![image](https://user-images.githubusercontent.com/114264403/227367241-7d48927e-d495-4f80-b1bf-4bf634a810b2.png)
![image](https://user-images.githubusercontent.com/114264403/227368320-63ad7695-3296-4cc3-afeb-8c6a0c6d3899.png)

### Steps to reproduce

- Apply Viewport texture that renders a control node to a Sprite3D node
- Export the project through the windows template 

### Minimal reproduction project

N/A

**Comment by Calinou** [comment] 2023-03-23 22:14
- Duplicate of https://github.com/godotengine/godot/issues/73868.

**Closed by Calinou** 2023-03-23 22:14 UTC
