### ISSUE TITLE
Materials Not Honoring Local to Scene

### ISSUE THREAD

**Issue by SoapSpangledGames** [godotengine/godot#71406] opened 2023-01-14 16:14 UTC
### Godot version

4.0 Beta 10

### System information

Kubuntu 18.04, Forward+, NVIDIA GeForce GTX 1660

### Issue description

I have a model created via Blender, exported from Blender as a GLTF file, and imported into Godot as a local copy.

There is a set of materials in the mesh, with each material intended to display a different texture, and each material in the set is flagged as "Local to Scene".

I create multiple instances of this mesh, and set each material set to a different set of textures. Setting the individual textures within the mesh works fine, but each instance of the mesh displays the same set of textures. This shouldn't happen with each material set as "Local to Scene". Each instance should display a different set of textures.

### Steps to reproduce

I've added an MRP to demonstrate the issue. Each flattened cube has two materials, which each material flagged as "Local to Scene". Each instance of the cube shows the exact same textures, though all instances are given unique textures. What is displayed is the set of textures assigned to the last cube instance.

### Minimal reproduction project

[materials.zip](https://github.com/godotengine/godot/files/10418153/materials.zip)

**Comment by RedMser** [comment] 2023-01-17 18:37
Duplicate of #71243, since a mesh's surface information is stored in an array `_surfaces[*].material`.

As a workaround, you can use:

```gdscript
func setText(nIndex : int,image):
	var mat : StandardMaterial3D = m_mesh.get_active_material(nIndex).duplicate()
	m_mesh.set_surface_override_material(nIndex, mat)
	mat.albedo_texture = ImageTexture.create_from_image(image)
```

**Comment by Calinou** [comment] 2023-01-17 19:05
Duplicate of https://github.com/godotengine/godot/issues/71243.

**Closed by Calinou** 2023-01-17 19:05 UTC
Labels: bug, archived, topic:core

**Comment by SoapSpangledGames** [comment] 2023-01-17 23:16
Thank you. That works beautifully!
