### ISSUE TITLE
Godot sporadically hangs during saving scenes

### ISSUE THREAD

**Issue by jpVm5jYYRE1VIKL** [godotengine/godot#29337] opened 2019-05-31 09:45 UTC
**Godot version:**
3.1.1
**OS/device including version:**
Windows 10.
**Issue description:**
Godot sporadically (not often) hangs in moment scene save. Message saving scene never disappear.
Issue happens at least on 2 different computers.
![hangs](https://user-images.githubusercontent.com/22169129/58697223-76ed2a00-8399-11e9-8688-2496571d1cfe.jpg)

After it hangs possible only to end godot task and restart it again.

**Steps to reproduce:**
It is random. 

**Minimal reproduction project:**
In current moment i not sure that this is project related.

**Comment by mhilbrunner** [comment] 2019-05-31 11:20
Happens for me too, on Windows 10. Even with small and simple projects.

**Comment by KoBeWi** [comment] 2020-07-31 20:09
Can anyone still reproduce this bug in [Godot 3.2.3 rc3](https://godotengine.org/article/release-candidate-3-2-3-rc-3) or any later release?

**Comment by KoBeWi** [comment] 2020-09-28 16:40
Closing due to lack of update. Please comment if you can still reproduce this issue in the latest stable version of Godot.

**Comment by itsybitesyspider** [comment] 2021-02-17 19:08
I've been seeing this frequently, but not consistently. It may be relevant that I'm using the gdnative bindings for rust, and have the project open in both VS code (including rust-analyzer) and Godot. I could use guidance on how to collect more useful information.

**Comment by KoBeWi** [comment] 2021-02-17 19:24
Do you have any minimal reproduction project? Otherwise it will be difficult to diagnose this issue.

**Comment by itsybitesyspider** [comment] 2021-02-17 19:32
The project I have is not particularly large, and I would not object to giving you access if it will improve Godot.

I would also not object to trying to build Godot with more logging on my machine. My C/C++ is a little stale but I should be able to follow most instructions.

**Comment by itsybitesyspider** [comment] 2021-02-17 19:40
But to properly answer your question, if I am able to arrive at a minimal example, I will certainly provide it.

**Comment by KoBeWi** [comment] 2021-02-17 23:14
> The project I have is not particularly large, and I would not object to giving you access if it will improve Godot.

I think it would be better to try reproducing it in a fresh project. Or at least strip your project from stuff unnecessary to reproduce the issue.

**Comment by jpVm5jYYRE1VIKL** [comment] 2021-02-18 09:39
I have a question do you have some kind of cvs(not git)?  I have theory that it possible be binded with filesystem locks.

**Comment by itsybitesyspider** [comment] 2021-02-18 11:51
I'm using git. However my suspicion about file system locking is also super elevated as this is only happening after I run "cargo build" (and cargo and rust-analyzer are constantly file locking each other, but handle it gracefully.) I am not even editing the scene in Godot - only changing the rust source files and rebuilding the dll. However, so far I have not put any of this together into any kind of useful conclusion. In particular I do not understand why it has become wildly worse for me in the last 24 hours.

I suppose we could try to replicate the issue consistently by intentionally locking some files in a controlled way.

**Comment by RestartMV** [comment] 2021-08-14 22:52
I got this error while following the 'make an action rpg' tutorial series from youtube, so I know exactly which steps were taken in this project.  Unfortunately, since other people managed to get past it, the bug seems to be sporadic.

Specifically, I was at this step - I had just added rectangle colliders to all my tiles, saved, and was trying to run a playtest.
https://youtu.be/RPgTlxb7Bno?t=578

Here are screenshots of both windows:
https://i.imgur.com/PkQz0N0.jpg
https://i.imgur.com/DRtriXR.jpg

I do not have any kind of cvs set up.

**Comment by RestartMV** [comment] 2021-08-14 22:55
Oh and I'm on Godot 3.3.2-stable_win64, running on windows 10.

**Comment by shpyr** [comment] 2021-09-18 02:41
I am also seeing this with a variety of projects (some with git, some without). I'm running godot 3.3.3 on Fedora 34:
``` 
$ rpm -qi godot
Name        : godot
Version     : 3.3.3
Release     : 1.fc34
Architecture: x86_64
...
```

**Comment by Calinou** [comment] 2022-11-04 21:31
@jpVm5jYYRE1VIKL @itsybitesyspider @shpyr Can you (or anyone else) still reproduce this bug in [Godot 3.5.1](https://godotengine.org/article/maintenance-release-godot-3-5-1) or any later release?

If yes, please ensure that an up-to-date Minimal Reproduction Project (MRP) is included in this report (a MRP is a zipped Godot project with the minimal elements necessary to reliably trigger the bug). You can upload ZIP files in an issue comment with a drag and drop.

**Comment by Calinou** [comment] 2022-11-25 19:08
Closing due to lack of response. Please comment if you can still reproduce this bug.

PS: Since no [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) was included in the original bug report, please upload one as well to ease troubleshooting.

**Closed by Calinou** 2022-11-25 19:08 UTC
Labels: bug, topic:editor, needs testing
