### ISSUE TITLE
Doc link clicking not working correctly

### ISSUE THREAD

**Issue by YeldhamDev** [godotengine/godot#27983] opened 2019-04-13 13:56 UTC
**Godot version:**
b7cf4c2

**Issue description:**
I don't know if this is just a problem in the docs or with the `RichTextLabel` node in general, but when hovering the links in the docs, the cursor will not turn into the "pointing hand" shape, and sometimes, clicking them will result in nothing.

**Comment by akien-mga** [comment] 2019-04-23 13:39
Also affects 3.1.1-rc1, likely a regression from #26788.

**Comment by akien-mga** [comment] 2019-04-23 13:52
Tried a local revert, it seems only partly caused by #26788, namely the pointing hand issue. The fact that hyperlinks don't work is not fixed by reverting #26788.

**Comment by akien-mga** [comment] 2019-04-23 14:12
Actually reverting #26788 seems to fix both regression (broken cursor and links not working).

It's still possible to get links not working as expected in some situations, usually solved by re-clicking the link which didn't work. That issue is also in 3.1-stable so it existed before this regression.

**Comment by YeldhamDev** [comment] 2019-04-23 21:56
Nope, this doesn't fix it at all...

**Comment by Ranoller** [comment] 2019-04-24 03:54
https://github.com/godotengine/godot/issues/27384

**Comment by akien-mga** [comment] 2019-04-24 10:17
> Nope, this doesn't fix it at all...

Can you be more explicit?

> when hovering the links in the docs, the cursor will not turn into the "pointing hand" shape

This is definitely fixed for me in master, and was fixed by #26788.

>  sometimes, clicking them will result in nothing.

This would be a duplicate of #27384 which has detailed debugging information, so closing again.

**Closed by akien-mga** 2019-04-24 10:17 UTC
Labels: bug, junior job, topic:editor
