### ISSUE TITLE
Make Unique on a material causes excessive (40 seconds) scene save times

### ISSUE THREAD

**Issue by kheptagon** [godotengine/godot#61913] opened 2022-06-10 20:12 UTC
### Godot version

3.4.4.stable

### System information

Windows 10

### Issue description

Setting "Make Unique" for an imported material causes saving a scene to hang for a long time.

In [this video showing the bug](https://www.youtube.com/watch?v=OOJa3iRpjQs), you can see that making the mesh unique works, but making the material unique causes the problem. 

### Steps to reproduce

Import a gltf file, click Make Unique on the material, and save the scene as a tscn. [Demonstration video](https://www.youtube.com/watch?v=OOJa3iRpjQs)

The gltf file used in the video is [here](https://ln5.sync.com/dl/e624f5620/tgr5mvdg-u8ayppnd-4v5uin6j-k497794b/view/default/5690917500009), 7.1 MB, gotten from the tutorial series by BornCG.

### Minimal reproduction project

https://drive.google.com/file/d/1g_WWK8UQ_fII-XqeKD1r9TGtgVEGnmEe/view?usp=sharing

**Comment by KoBeWi** [comment] 2022-06-10 20:19
This is expected. When you make material unique, all data is saved inside the scene. You can make it faster if you save it in `scn` format, so that the data is binary instead of text.

**Comment by Calinou** [comment] 2022-06-10 21:00
Duplicate of https://github.com/godotengine/godot/issues/34641.

**Closed by Calinou** 2022-06-10 21:00 UTC
