### ISSUE TITLE
Triplanar mapping is stretched if mesh has no uvs 

### ISSUE THREAD

**Issue by fracteed** [godotengine/godot#88999] opened 2024-02-29 05:55 UTC
### Tested versions

- works in 4.1.3
- doesn't work in 4.2.1 and later versions

### System information

win10 960m + win11 3050

### Issue description

This is an issue I noticed upon moving a 4.1.3 project over to 4.2.1. Triplanar mapping will exhibit stretching along the z axis if using it on a mesh with no uvs. Versions 4.1 and earlier had no issue with this.

As can be seen in this image, the blender exported cube on the left has uvs, and the one on the right has no uvs. Both exported as obj, but the same issue also happens if gtlf is exported (I did include a gltf cube in the project file).

![triplanar_1](https://github.com/godotengine/godot/assets/7741669/f7b7a7d3-56a5-42d8-857c-acd9da32c415)

 I noticed that reimporting the no uv cube with the "force disable mesh compression" turned on will fix the issue. You can cover this up by putting in a high value in the triplanar sharpness such as 5, but this is not a good solution for many meshes.

![triplanar_2](https://github.com/godotengine/godot/assets/7741669/bf25218a-be95-45b1-b52a-feb2675645cd)

A possibly related issue is that if you open this sample project, the non uv cube may have no material in the slot, even though it was there when saved. This happens to me about 50 percent of the time.  Sometime the material will disappear from the slot, but the material still shows in the viewport. Not sure if this is related, but always seems to happen to the non uv mesh?

@clayjohn I initially thought this might have been due to the changes in the recent triplanar code, but I think it is due to the mesh format changes in 4.2. If I export a no uv mesh from 4.1 in .mesh format and import into 4.2 it does not exhibit this issue. Does the tangent generation in 4.2 rely upon the mesh having uvs?

### Steps to reproduce

- Export the default cube from blender without uvs
- create a basic triplanar material in godot and put on the imported cube
- note the stretching compared to a cube with uv's

### Minimal reproduction project (MRP)

[triplanar_bug_4-2.zip](https://github.com/godotengine/godot/files/14443398/triplanar_bug_4-2.zip)

**Comment by clayjohn** [comment] 2024-02-29 07:10
Hmmm, this is very interesting. Before 4.2, UVs were always needed for tangent generation. 4.2 made a change that allowed Tangents to be generated without UVs actually. In 4.1 though we used a default tangent value when a tangent array wasn't provided (1,0,0,1) IIRC. 

I think the issue comes from the UV compression code and isn't related to tangents. With compressed meshes we scale UVs into the 0-1 range so that we can store them in 16 bits instead of 32. This tends to work really well in most cases and saves a ton of bandwidth. In this case, since UVs are read in the shader, dummy UVs will be passed in. I believe the unscaling code will still apply to them. So this might just be a matter of passing in different scaling values when UVs aren't present. I can investigate more tomorrow

**Comment by fracteed** [comment] 2024-02-29 08:37
thanks @clayjohn for looking at this. I am finding a few other odd shading issues with meshes in 4.2. Here is an example that uses face weighted normals and has uv's but they are not proper uv's. 

![mesh_shading_error](https://github.com/godotengine/godot/assets/7741669/d7889922-9730-40b6-8ed0-01a60869fde3)

Notice the dark shading error on the edge of the pipe. The issue goes away if I reimport the gltf with the force disable mesh compression., as seen on the right. I can also get rid of the error if I either don't triangulate from blender or I do a proper uv layout before exporting.

Seems like uv's are having an effect on normals or tangents. Not sure why turning off the triangulate modifier in blender before exporting would help though. I almost always use a combination of weighted normals and triangulate in the blender stack and it hasn't given issues before 4.2. 

I have included the blend file and 4.2 godot file in the zip.

[face_weighting_bug.zip](https://github.com/godotengine/godot/files/14445136/face_weighting_bug.zip)

**Comment by clayjohn** [comment] 2024-02-29 20:18
Looks like the issue comes from the normal itself, not the UVs.

Testing locally I can confirm the issue using 4.2.1. I can also confirm that it has already been fixed in master! 

I am fairly certain it was fixed by https://github.com/godotengine/godot/pull/88738 which (among other things) avoids a singularity that can occur when a normal is exactly (0,1,0).

**Comment by clayjohn** [comment] 2024-02-29 20:19
Oops, I had this issue overnight so your response didn't appear until after I closed this. Re-opening until I investigate your new MRP

**Comment by clayjohn** [comment] 2024-02-29 20:33
Okay, I ran the new MRP and confirmed that the other issue is present in 4.2.1, but also fixed in 4.3. Its also most likely fixed by https://github.com/godotengine/godot/pull/88738

In 4.2.1 the mesh compression technique falls over with meshes that have invalid UVs the reason is a bit complex:
1. Mesh compression requires tangents to compress normals. 
2. If UVs are present, we can use them to generate good tangents for use with normal mapping.
3. If UVs are not present then we can generate tangents that are fine for compression, but are not good for normal mapping. 
4. If the UVs are present but are not legitimate, then the resulting tangents are totally bogus and can't be used for normal mapping or compression. 

In 4.2.1 we assume that UVs are legitimate whenever they are present leading to many cases like this. In https://github.com/godotengine/godot/pull/88738 I added a check for this situation that can automatically detect this issue and disable compression. 

As a summary of this issue as a whole:

The original MRP was an issue with how we generate fallback tangents in the situation where the mesh does not have UVs. It was a particular issue with generating tangents to align with a normal that points straight up. The reason UVs mattered is because we use a different path to generate tangents when UVs are present and that path worked fine for that mesh. 

The second MRP is an issue with the path that generates tangents from UVs. In general, that path is better (we use an external library to get proper mikkt-space tangents), but it assumes that the UVs are legitimate. When the UVs are not legitimate, it produces bad tangents. 

In both cases, the issue is that mesh compression needs good tangents to compress normals. https://github.com/godotengine/godot/pull/88738 fixes both issues and should be backported to 4.2.2 soon :)

**Closed by clayjohn** 2024-02-29 20:33 UTC
Labels: bug, topic:rendering, topic:import, regression, topic:3d

**Comment by clayjohn** [comment] 2024-02-29 22:44
To clarify, once https://github.com/godotengine/godot/pull/88738 is cherry picked for 4.2.2, you won't have to worry about this. The perceived dependency between UVs and tangents/normals is a temporary bug that has already been fixed. 

Godot shouldn't override tangents if they are provided in the glTF file. I can take another look at the MRP and see what's going on. It could be the case that Blender isn't exporting the tangents. There are a few cases where blender will silently ignore tangents and export without them (IIRC the big one is if the mesh isn't triangulated)

In the future, no, you don't need to worry about UVs if you are exporting with tangents from blender. UVs are needed in two cases:
1. You use a normal map and didn't export with tangents for some reason
2. You need the UVs for reading from a texture (i.e. you are using non-triplanar texture mapping)

**Comment by fracteed** [comment] 2024-02-29 22:59
Thanks, that is good to hear. The original MRP was just a default blender cube exported as gltf with tangents and uv's . The exported obj did not have tangents since blender can't do this. Sounds like this should all be resolved now anyway. I will do more testing when the next 4.2.2 rc is released and report back if there is anything amiss.
