### ISSUE TITLE
[Editor] File System 

### ISSUE THREAD

**Issue by carlosmarti** [godotengine/godot#3717] opened 2016-02-15 18:09 UTC
It looks like when you create a new folder in godot it messes up the file system in the editor. It seems to duplicate the directories under other folders as seen on the image below.

Reproduce:
- save a new scene
- at the top right click on create new folder
- create your folder
- save your scene inside of the new folder
- look at the file system section
![bug](https://cloud.githubusercontent.com/assets/5507549/13056763/5a1422b0-d3e5-11e5-897d-ece4281fc235.PNG)

**Comment by carlosmarti** [comment] 2016-02-15 18:11
It doesn't actually create the thous duplicate folders in the directory. It just shows up this way on the editor.

**Comment by neikeq** [comment] 2016-02-15 18:33
Could this be related to (or a duplicate of) #3662?

**Comment by carlosmarti** [comment] 2016-02-15 18:37
That does look like the same issue. Maybe should close this issue?

**Comment by nunodonato** [comment] 2016-02-15 18:57
yes its the same, you can safely close it.
always good to search before adding a new issue ;)

**Closed** 2016-02-15 19:05 UTC
Labels: archived
