### ISSUE TITLE
HMD mode fails for Meta Quest 3 with custom builds

### ISSUE THREAD

**Issue by fire** [godotengine/godot#97907] opened 2024-10-07 00:08 UTC
### Tested versions

- Reproducible https://github.com/godotengine/godot/commit/db66bd35af704fe0d83ba9348b8c50a48e51b2ba
- Not reproducible in Meta Store Godot Engine (4.4?)

### System information

Meta Quest 3

### Issue description

Error: OpenXR was requested but failed to start. Please Check if your hmd is connected. Godot will start in normal mode.

![com oculus metacam-20241006-165641](https://github.com/user-attachments/assets/6001187a-af43-417d-8d59-0f6b2a597d19)

### Steps to reproduce

1. Download the `android-editor` from the github actions on https://github.com/godotengine/godot/commit/db66bd35af704fe0d83ba9348b8c50a48e51b2ba
2. Use the horizon os apk. 
![image](https://github.com/user-attachments/assets/3b2406a7-46ad-40fd-b3cc-ef6bca11bb26)
3. Use sidequest to load apk onto the Quest 3 (assumed partnership agreement with Meta)
4. Launch project from downloaded folder
  * To launch on the left side of the app browser select "other" applications to find non appstore apps.
5. Click play.

### Minimal reproduction project (MRP)

[demo-bug.zip](https://github.com/user-attachments/files/17271320/demo-bug.zip)

**Comment by m4gr3d** [comment] 2024-10-07 01:06
@fire does the project you are running works with the store version of the editor (version 4.4-dev3)?

**Comment by fire** [comment] 2024-10-07 01:45
As far as I know it should play in the xr with the store version. The result is that the HMD is placed into the scene with the physical sky with no controllers.

> Not reproducible in Meta Store Godot Engine (4.4?)

**Comment by fire** [comment] 2024-10-07 02:01
Here's a video with the store version of the editor.

https://github.com/user-attachments/assets/80ac4447-449c-46b5-968c-3e277b4b04f7

**Comment by dsnopek** [comment] 2024-10-08 14:36
Unfortunately, I'm not able to reproduce this.

I tried both the artifacts from GitHub actions on PR https://github.com/godotengine/godot/pull/97820 (which is where https://github.com/godotengine/godot/commit/db66bd35af704fe0d83ba9348b8c50a48e51b2ba is from) and building latest `master` (currently 842f98239713fd10cfd648cd6aa3781895f289eb), and both were able to correctly run a simple immersive project.

I'm not sure what could be different between your setup and mine?

**Comment by fire** [comment] 2024-10-08 16:17
How are you loading the apk? Maybe sidequest tinkers with the upload.

**Comment by dsnopek** [comment] 2024-10-08 17:03
> How are you loading the apk? Maybe sidequest tinkers with the upload.

Just `adb install android_editor-horizonos-debug.apk` in a terminal

**Comment by fire** [comment] 2024-10-08 18:02
I'll try that.

**Comment by fire** [comment] 2024-10-08 21:47
Using a custom build also works now for me on the Meta Quest 3.

I suspect that the Godot Engine is loaded as a 2d app and when the custom editor build works it reuses the manifests from the Meta App store app but that makes no sense.

To test this theory I used the htc xr elite which has no store app and the same message of Openxr failed to start in XR mode.

**Comment by fire** [comment] 2024-10-08 21:51
I suspect that I may have accidently installed `android_editor-android-debug.apk` because `android_editor-horizonos-debug.apk` seems to work.

**Comment by dsnopek** [comment] 2024-10-08 23:19
> To test this theory I used the htc xr elite which has no store app and the same message of Openxr failed to start in XR mode.

Using it with the HTC headset will also have issues because it has the wrong OpenXR loader.

**Comment by BastiaanOlij** [comment] 2024-10-09 08:27
> > To test this theory I used the htc xr elite which has no store app and the same message of Openxr failed to start in XR mode.
> 
> Using it with the HTC headset will also have issues because it has the wrong OpenXR loader.

Also HTC requires different manifest entries, though from all the headset HTC is the least difficult as all features are purely to steer the store entry and have no impact on whether an app runs or not. There is one HTC specific manifest entry required to tell the OS that it is a VR app or it will run it as a normal Android app.

**Comment by fire** [comment] 2024-10-09 21:09
Do you know what the exact definition of that HTC specific manifest to enable VR app.

**Comment by fire** [comment] 2024-10-13 17:00
I'll close soon as I was able to test the feature and it works.

The HTC specific manifest entry is a different issue / feature request.

**Comment by m4gr3d** [comment] 2024-10-14 04:01
@fire were you able to test that the issue is resolved on the Quest 3?
For HTC devices, we should create a separate issue and close this one.

**Comment by fire** [comment] 2024-10-14 07:09
it is resolved

**Closed** 2024-10-14 08:05 UTC
Labels: platform:android, topic:xr

**Comment by sopdevv** [comment] 2024-11-14 18:18
my quest 2 does the same, how did you fix it ??
