### ISSUE TITLE
Can't pan to the top-left in a 2D scene, causing inability to view all of a sprite

### ISSUE THREAD

**Issue by Zephilinox** [godotengine/godot#20309] opened 2018-07-20 14:55 UTC
**Godot version:** @Calinou's build from today, though it's not a new issue

**OS/device including version:**
W10

**Issue description:**
The sprite extends further but I can't pan to view it, the only way to view the sprite is to move it.

**Steps to reproduce:**
Place a big sprite at 0, 0 in a 2D scene

![godot pan](https://user-images.githubusercontent.com/2060863/43009341-4a657110-8c35-11e8-84a4-ac5cb9dc2a77.gif)

**Comment by eon-s** [comment] 2018-07-20 19:35
This seems duplicate of #18738 and probably related to some general scrollbar issues.

**Comment by akien-mga** [comment] 2018-07-20 19:55
Indeed, it seems to be the same as #18738.

**Closed by akien-mga** 2018-07-20 19:55 UTC
