### ISSUE TITLE
Start-up godot console error message

### ISSUE THREAD

**Issue by lucapgls** [godotengine/godot#83180] opened 2023-10-12 05:02 UTC
### Godot version

3.5.3.stable, 4.1.2.stable

### System information

Godot v4.1.2.stable - Windows 10.0.22621 - Vulkan (Compatibility) - NVIDIA GeForce GTX 1060 6GB (NVIDIA; 31.0.15.3758) - Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz (6 Threads)

### Issue description

I have recently reinstalled windows in my pc and every time i open godot, regardless of the version im on or the project working on, the same thing happens. Two error messages in the godot console appear just after i open a godot project (in v3.5.3.stable shows the message one time). 

`Godot Engine v4.1.2.stable.official (c) 2007-present Juan Linietsky, Ariel Manzur & Godot Contributors.
  platform/windows/os_windows.cpp:1607 - Condition "res != ((HRESULT)0x00000000)" is true. Returning: String()
--- Debug adapter server started ---
--- GDScript language server started ---
  platform/windows/os_windows.cpp:1607 - Condition "res != ((HRESULT)0x00000000)" is true. Returning: String()`

![image](https://github.com/godotengine/godot/assets/73355604/0fbeaa41-bd06-40d5-8aee-1cf7956b2098)

### Steps to reproduce

Just reinstall windows 11 to its lastest stable version and open a godot project.

### Minimal reproduction project

N/A

**Comment by bruvzg** [comment] 2023-10-12 06:21
The error seems to be from `OS.get_system_dir(OS.SYSTEM_DIR_DOCUMENTS)` call used by the editor to get the path to the Documents folder. Do you have Documents folder moved to an unusual location or missing?

**Comment by akien-mga** [comment] 2023-10-12 06:43
- Duplicate of https://github.com/godotengine/godot/issues/76420

**Closed by akien-mga** 2023-10-12 06:43 UTC
