### ISSUE TITLE
Add support for mobile advertising

### ISSUE THREAD

**Issue by DDru** [godotengine/godot#25559] opened 2019-02-01 22:16 UTC
**Godot version:**
3.1

**OS/device including version:**
Android

Please add ad support (admob, unityAds) for Android.
Godot is a good engine, but he does not have some important functions.

**Comment by BastiaanOlij** [comment] 2019-02-02 00:19
@DDru Godot is an open source engine, it can't embed functionality into its core that has a license model that is incompatible with MIT. 
If I understand correctly admob (don't know about unityads) has a license model that makes including it into the core impossible.
Google "Godot admob" and you'll find various plugins, I have no advise on which one is good nor what the impact is on the licensing of your game.

**Comment by volzhs** [comment] 2019-02-02 04:51
did you check on android device?

**Comment by DDru** [comment] 2019-02-02 09:54
@volzhs on the device it works. In the docs, nothing about it. After other engines, I expected some changes in the editor.

But earlier it did not work on the device. A small test showed that the original GodotAds has some problems.

Thanks.

**Comment by ca3games** [comment] 2019-02-02 19:41
> @DDru Godot is an open source engine, it can't embed functionality into its core that has a license model that is incompatible with MIT.
> If I understand correctly admob (don't know about unityads) has a license model that makes including it into the core impossible.
> Google "Godot admob" and you'll find various plugins, I have no advise on which one is good nor what the impact is on the licensing of your game.

Still godot could be designed as to allow an easy way to implement third party solutions, maybe just clicking some button to integrate as a simple third party plugin.

**Comment by DDru** [comment] 2019-02-03 01:13
Does the license apply only to libraries? What if an API is created to interact with popular advertisements, and the user downloads and adds the library to the project in the libs folder?

**Comment by LikeLakers2** [comment] 2019-02-03 06:11
> [@ca3games] Still godot could be designed as to allow an easy way to implement third party solutions, maybe just clicking some button to integrate as a simple third party plugin.

There are already several ways to do this: [Engine modules](https://docs.godotengine.org/en/latest/development/cpp/custom_modules_in_cpp.html) (functionality added into the engine's source -- for example, GDscript is technically a module), [GDnative](https://godotengine.org/article/dlscript-here) (shared libraries), and [asset library stuff](https://docs.godotengine.org/en/latest/tutorials/assetlib/what_is_assetlib.html) -- assuming you can't just add that functionality using GDScript.

> [@DDru] What if an API is created to interact with popular advertisements, and the user downloads and adds the library to the project in the libs folder?

Personally, I am against any sort of "ads API" being added to vanilla Godot. I would prefer this sort of thing be kept to plugins/addons.

**Comment by Calinou** [comment] 2019-02-03 12:46
There are plans to rework Android exporting to make using third-party modules easier, see #18865.

**Comment by ventr1x** [comment] 2019-07-04 08:00
It's not only not beginner friendly but also not pro friendly. 
As a developer the first thing I look for is a platforms eco system. 
For mobile, Godot is simply bad. It doesn't support any mobile functionality, no third party is supporting godot at all (no mediation platform, tracking service and so on).

To get such support, we'd #1 need support from main Godot devs and #2 statistics about Godot usage. With that people could go to third parties and get them to create plugins for it.
I have contact to several big mediation platforms which I could cooperate with and get e.g. IronSource to create a plugin. But with things like "Nope, not interested. But you could build a plugin" there is no way ever to get any third party to support Godot. Such support is always in some kind sponsored, be it financially or through cooperation. 

You simply can't expect all the little indie devs to compile engines, white c++ plugins for it and bend it even more, without having proper documentation to it in the first place. That goes beyond the scope of any small dev, and paying for Unity is faster, easier and way more cost efficient. It's sad to see (not only here) the very desinterested stand to Godot's eco system.

**Comment by freemanfromgodotengine** [comment] 2019-07-23 02:19
For some people asking for easier ads support is almost like asking Godot to support cancer. :)

**Comment by VitaZheltyakov** [comment] 2019-08-02 18:52
The problem is that the modules are quite difficult to connect.

**Comment by kristiannotari** [comment] 2020-03-28 16:14
I think they're right about not supporting anything like ads directly inside the engine, as it would change the license specifications and philosophy around the project. Instead they're trying to add simpler ways to add modules/plugins whatever in order to have everything functional. And this is great.

Things like ads should be something that you add to the project. I don't know about the current set of features available in Godot in order to use and communicate with the mobile platform specific features (3D Touch, sensors, AR etc). I think they should be added since they're part of the platforms they target to, not something one could add to a platform (like ads). But, if doing so breaks some license rules then these features could be developed as "Godot official third party" plugins, they would just not ship with the engine directly and warns you if you add them as an official plugin.

**Comment by ksvslk** [comment] 2020-04-27 14:37
> It's not only not beginner friendly but also not pro friendly.
> As a developer the first thing I look for is a platforms eco system.
> For mobile, Godot is simply bad. It doesn't support any mobile functionality, no third party is supporting godot at all (no mediation platform, tracking service and so on).
> 
> To get such support, we'd need support from main Godot devs and statistics about Godot usage. With that people could go to third parties and get them to create plugins for it.
> I have contact to several big mediation platforms which I could cooperate with and get e.g. IronSource to create a plugin. But with things like "Nope, not interested. But you could build a plugin" there is no way ever to get any third party to support Godot. Such support is always in some kind sponsored, be it financially or through cooperation.
> 
> You simply can't expect all the little indie devs to compile engines, white c++ plugins for it and bend it even more, without having proper documentation to it in the first place. That goes beyond the scope of any small dev, and paying for Unity is faster, easier and way more cost efficient. It's sad to see (not only here) the very desinterested stand to Godot's eco system.

There is an Android plugin for Godot now: https://github.com/ksvslk/godot-ironsource-android

**Comment by clayjohn** [comment] 2020-05-27 05:30
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!

**Closed by clayjohn** 2020-05-27 05:30 UTC
Labels: feature proposal, topic:plugin
