### ISSUE TITLE
randomly crash after rendering text.

### ISSUE THREAD

**Issue by ippan** [godotengine/godot#20633] opened 2018-07-31 13:31 UTC
**Godot version:**

Master, after commit: 0e29f79
(not happen before 5421e46)

**OS/device including version:**

OS: OSX
GPU: 755M

**Issue description:**

after rendering many Chinese text, it will randomly crash.

here is the C++ call stack when crash:

cowdata.h                 line 121     return *size;
vector.h                     line 87     _FORCE_INLINE_ int size() const { return _cowdata.size(); }
vector.h                     line 55     CRASH_BAD_INDEX(p_index, _parent.size());
dynamic_font.cpp    line 550    tex.offsets.write[k] = tex_pos.y + mh;
dynamic_font.cpp    line 639    character = _bitmap_to_character(slot->bitmap, slot->bitmap_top, slot->bitmap_left, slot->advance.x / 64.0);
dynamic_font.cpp    line 296    const_cast<DynamicFontAtSize *>(this)->_update_char(p_char);
dynamic_font.cpp    line 862    Size2 ret = data_at_size->get_char_size(p_char, p_next, fallback_data_at_size);
rich_text_label.cpp   line 352    int cw = font->get_char_size(c[end], c[end + 1]).width;
rich_text_label.cpp   line 1269   _process_line(p_frame, text_rect.get_position(), y, text_rect.get_size().width - scroll_w, i, PROCESS_CACHE, base_font, Color(), font_color_shadow, use_outline, shadow_ofs);
rich_text_label.cpp   line 798    _validate_line_caches(main);

**Steps to reproduce:**
can not reproduce in a new project.

**Minimal reproduction project:**

**Comment by volzhs** [comment] 2018-07-31 17:27
duplicate of #20475

**Closed by volzhs** 2018-07-31 17:27 UTC

**Comment by volzhs** [comment] 2018-07-31 17:28
and there is a pending PR for fixing this. #20573
