### ISSUE TITLE
Godot Crashing

### ISSUE THREAD

**Issue by BryanTheOverlord** [godotengine/godot#74260] opened 2023-03-02 23:26 UTC
### Godot version

4.0 stable forward+

### System information

Windows 11

### Issue description

when I copy/past/duplicate a 3d object that is size 10 or above on any of the scales x, y, z there's about a 45% chance Godot well crash and when I edit tile maps when I delete 100+ tiles at once or place 100+ tiles at once there is about a 30% chance Godot well crash

### Steps to reproduce

when I copy/past/duplicate a 3d object that is size 10 or above on any of the scales x, y, z there's about a 45% chance Godot well crash and when I edit tile maps when I delete 100+ tiles at once or place 100+ tiles at once there is about a 30% chance Godot well crash

### Minimal reproduction project

[Bryans MultiPlayer Test - Copy.zip](https://github.com/godotengine/godot/files/10876652/Bryans.MultiPlayer.Test.-.Copy.zip)

**Comment by BryanTheOverlord** [comment] 2023-03-02 23:26
same thing here

**Comment by Calinou** [comment] 2023-03-02 23:36
The CSG issue is already tracked in https://github.com/godotengine/godot/issues/73927.

**Comment by YuriSizov** [comment] 2023-03-08 20:50
Indeed, the CSG issue is likely a duplicate of https://github.com/godotengine/godot/issues/73927, judging by description.

As for tilemaps, your MRP doesn't have any, so it's hard to say for sure if it's a match for any existing report or something new. There are a few other reports regarding the tile editor, including crashes and performance issues. So you might be experiencing one of those. But again, hard to say for certain, because your report doesn't have a reproduction project.

So, please open a new bug report with a reproduction project that demonstrates the tilemap issue. In future, please open separate reports for separate issues, and provide minimal scenes that demonstrate the problem. It helps us pinpoint the issue a lot. Thanks.

**Closed by YuriSizov** 2023-03-08 20:50 UTC
Labels: bug, topic:editor, needs testing, crash
