### ISSUE TITLE
deselecting a Polygon2D does not disable the point UI / red outline

### ISSUE THREAD

**Issue by thmasn** [godotengine/godot#43095] opened 2020-10-26 15:21 UTC
**Godot version:**
3.2.3.stable.mono

**OS/device including version:**
Windows 10

**Issue description:**
When creating and editing a Polygon2D, the edit handles & the red outline are visible.
however, when deselecting the polygon2D by clicking outisde of the object, the handles remain visible.
only when selecting another object, the handles disappear.

this makes the iteration of creating / editing multiple of these shapes slower, as is takes longer to see the final result (without outlines)

especiialy, since common drawing apps always hide the handles when deselecting an object, this behaviour is very unconventional and irritates people coming from other software.

**Steps to reproduce:**

- create polygon2D object
![Screenshot 2020-10-26 162055](https://user-images.githubusercontent.com/20150151/97191521-420c1f00-17a7-11eb-80eb-6ec5f2b55a16.png)
- start creating new path with the green icon
![Screenshot 2020-10-26 161735](https://user-images.githubusercontent.com/20150151/97191241-f8bbcf80-17a6-11eb-99b9-81411764af65.png)
- click the path, and close it
![Screenshot 2020-10-26 161754](https://user-images.githubusercontent.com/20150151/97191239-f8bbcf80-17a6-11eb-8625-6e3b31bef409.png)
- the object is selected
![Screenshot 2020-10-26 161817](https://user-images.githubusercontent.com/20150151/97191236-f8bbcf80-17a6-11eb-8fd0-a522edbfd8b2.png)
- click outside of the path (or an empty spot in the scene tab) to deselect
![Screenshot 2020-10-26 161829](https://user-images.githubusercontent.com/20150151/97191234-f78aa280-17a6-11eb-9b74-54777836c502.png)
-> outline and handles are still visible

- select another object
![Screenshot 2020-10-26 161843](https://user-images.githubusercontent.com/20150151/97191243-f9546600-17a6-11eb-8e51-221eb1f0e0cc.png)
-> handles will be hidden

**note**

one could guess that this would be affected by the "poly editor"/ "show previous outline" setting, but it has no impact:
![Screenshot 2020-10-26 163648](https://user-images.githubusercontent.com/20150151/97193712-957f6c80-17a9-11eb-8006-fda803d5fd2a.png)

**Comment by Calinou** [comment] 2020-10-26 15:39
This is a duplicate of another issue (related to all editor gizmo plugins in general, in both 2D and 3D) but I can't find it right now.

**Comment by KoBeWi** [comment] 2021-02-13 19:08
Duplicate of #35989

**Closed by KoBeWi** 2021-02-13 19:08 UTC
Labels: bug, topic:editor
