### ISSUE TITLE
Texture Importing issue

### ISSUE THREAD

**Issue by curly-brace** [godotengine/godot#10880] opened 2017-09-02 07:38 UTC
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
windows, nvidia, f9eec5c 

**Issue description:**
godot imports textures very slowly. when you put like 4 textures in the folder and go back to the editor, it will import them like 5 minutes (other tools and editors on my PC do it much quicker)

and when i tried using 8x4k texture it imported it (very slowly) fine. it even generated a thumbnail for it. but when i assigned it to a shader, editor started reimport (for 3d i assume) and crashed.

this is not caused by the shader, because it may be just a single uniform declaration and nothing else.
it is caused by reimport for 3d

UPD: as soon as i select the texture, it appears on the mesh (when using standard shader for example) but after this, editor starts reimport and crashes. seems strange now, after i've noticed that texture is applyed to the mesh first.

UPD2: tried to reimport the texture with '3D' preset manually. editor just does not respond forever after displaying '(Re)Importing' dialog.

UPD3: downscaled texture in image editor to 4x2k and it works, but reimporting on assigning to shader takes much more then initial import.

**Comment by Zireael07** [comment] 2017-09-02 10:12
Have you tried unticking etc2 in project settings? You don't need it if you're not making stuff for mobile platforms...

**Comment by hpvb** [comment] 2017-09-02 10:16
Would it be possible for you to run with a debugger and supply us with a backtrace of the crash?

**Comment by curly-brace** [comment] 2017-09-02 12:28
@Zireael07 yeah it helped. is it unfinished feature? but it is enabled bu default in new projects.

**Comment by Zireael07** [comment] 2017-09-02 13:48
It is finished, and I don't know why it's enabled by default, given that 3.0 is unlikely to be used on mobile platforms since it's OpenGL 3.0...

**Comment by Zylann** [comment] 2017-09-02 13:51
Sounds like mobile dev will neef to cope with this in 3.0... but @reduz planned to do this reimport in a thread

**Comment by reduz** [comment] 2017-09-02 14:17
Yeah, reimport needs to be moved to a thread.. but for now it needs general
testing. Just disable etc2 in the importer for now if not doing mobile

**Comment by akien-mga** [comment] 2018-01-15 10:31
Closing as duplicate of #10583.

**Closed by akien-mga** 2018-01-15 10:31 UTC
