### ISSUE TITLE
Incorrect margin display in 2D editor viewport

### ISSUE THREAD

**Issue by zicklag** [godotengine/godot#8690] opened 2017-05-08 03:47 UTC
**Godot Engine v3.0.alpha.custom_build:**

Margins for controls will display incorrectly in the 2D editor viewport. They will run as designed when the game is run, the only problem is in the editor.

**Steps to reproduce:**

1. Create an empty project and create a new scene.
2. Make the root node a Panel and set it's anchor to "Full Rect"
3. Set the margin for each side of the panel to 0

You should be able to see that, in the display, the panel will not go all of the way to the sides of the camera box but will form a shape in the same aspect ratio of the 2D viewport. Changing the shape of the viewport, by showing or hiding the output panel for example, will change the aspect ratio of the panel in the viewport. Running the game displays the panel as expected.

**Link to minimal example project:**
[IncorrectMargins.zip](https://github.com/godotengine/godot/files/982312/ImproperMargins.zip)

**Comment by djrm** [comment] 2017-08-11 00:46
im unable to reproduce this.

**Comment by bojidar-bg** [comment] 2017-08-11 06:18
I could reproduce this once, but it seems to have been fixed indeed.
Closing as fixed.

**Closed by bojidar-bg** 2017-08-11 06:18 UTC
Labels: bug, topic:editor
