### ISSUE TITLE
C# Script Properties source generation fails for escaped reserved keyword exports

### ISSUE THREAD

**Issue by Neonalig** [godotengine/godot#93188] opened 2024-06-15 10:36 UTC
### Tested versions

- Reproducible in: v4.2.2.stable.mono.official [15073afe3]

### System information

Godot v4.2.2.stable.mono - Windows 10.0.22631 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 4070 (NVIDIA; 31.0.15.5123) - 12th Gen Intel(R) Core(TM) i9-12900 (24 Threads)

### Issue description

Using reserved keywords escaped with `@` for exported variable names in a C# Resource/Node class results in invalid generated source from `Godot.SourceGenerators.ScriptPropertiesGenerator`

### Steps to reproduce

- Create a C# partial class inheriting either `Node` or `Resource
- Add an `[Export]` field using a reserved name (you can escape reserved names with the `@` symbol, i.e. `@operator`, `@class`, `@interface`, etc.)
- Build the project, and see the compilation errors (since the generated source code does not escape the reserved keywords, so the resultant code is invalid)

Example code:
```cs
namespace FailureReservedKeywords;

public sealed partial class MinimalRecreation : Resource
{
    [Export] private int @operator = 0;
}
```

Resultant compilation errors:
```
0>FailureReservedKeywords.MinimalRecreation_ScriptProperties.generated.cs(16,70): Error CS0106 : The modifier 'new' is not valid for this item
0>FailureReservedKeywords.MinimalRecreation_ScriptProperties.generated.cs(16,70): Error CS0106 : The modifier 'readonly' is not valid for this item
0>FailureReservedKeywords.MinimalRecreation_ScriptProperties.generated.cs(16,70): Error CS0501 : 'MinimalRecreation.PropertyName.operator +()' must declare a body because it is not marked abstract, extern, or partial
```

![image](https://github.com/godotengine/godot/assets/16698604/5a144a10-3d4e-494f-bc6c-7bdbf3319e20)

### Minimal reproduction project (MRP)

N/A (see above example code, as this is enough to recreate the issue in any project). This error is C#-specific.

**Comment by raulsntos** [comment] 2024-06-15 15:35
Duplicate of https://github.com/godotengine/godot/issues/74839

**Closed by raulsntos** 2024-06-15 15:35 UTC
Labels: topic:dotnet
