### ISSUE TITLE
Editor used GBK/GB18030 instead of UTF-8 to load log in Simplified Chinese

### ISSUE THREAD

**Issue by SheepYhangCN** [godotengine/godot#74046] opened 2023-02-27 13:17 UTC
### Godot version

v4.0.rc6.mono.official

### System information

Windows 11 Pro 22H2, System Language: English, Godot Editor Language: Simplified Chinese

### Issue description

When the language was set to Simplified Chinese

Godot Editor Save Log File with UTF-8
![image](https://user-images.githubusercontent.com/44539204/221572664-5b2f4538-848d-41c4-86e9-b9ea530bf165.png)

But Editor load the log with GBK(or GB18030)
![image](https://user-images.githubusercontent.com/44539204/221572851-b0305f83-cce2-4197-b415-aca37a7314ae.png)
![image](https://user-images.githubusercontent.com/44539204/221572807-da3335ba-2f7e-4f17-a348-02bf9fdbcb19.png)

So it can't show the log correctly

To be honest, it should always be load in UTF-8 whatever any language, it is the most standard way to do

### Steps to reproduce

Change Godot Editor's language to Simplified Chinese
Write some code that will make game show error
Run the game
Go to the logs
And there it is

### Minimal reproduction project

N/A

**Comment by RedworkDE** [comment] 2023-02-27 13:48
Fixed by https://github.com/godotengine/godot/pull/73865
Workaround: https://superuser.com/a/1435645

**Comment by akien-mga** [comment] 2023-02-27 13:52
Duplicate of #71326

**Closed by akien-mga** 2023-02-27 13:52 UTC
