### ISSUE TITLE
Script inheriting script issues in editor

### ISSUE THREAD

**Issue by mikica1986vee** [godotengine/godot#914] opened 2014-12-02 23:21 UTC
When adding script (that is derived from other script) to node, editor will only show derived exported variables and on scene save will revert them to default values.
Example project:
https://www.dropbox.com/sh/w7439y35k0frmo5/AAAibSE7MsJIFzPAb4zlaNYaa?dl=0

**Comment by akien-mga** [comment] 2015-10-31 09:36
Actually a duplicate of #582.

**Closed by akien-mga** 2015-10-31 09:36 UTC
Labels: archived
