### ISSUE TITLE
Unicode characters on WindowDialog and its subclasses are displayed as blank in editor plugins.

### ISSUE THREAD

**Issue by rambda** [godotengine/godot#51661] opened 2021-08-14 10:53 UTC
### Godot version

3.3.2-stable

### System information

Windows10

### Issue description

If the editor language is set to a non-ASCII language (CJKV, Russian... etc.), any text of `WindowDialog` and any node that inherits from it will become the corresponding language. 
However, since the default font of Godot project is a Bitmap font that does not contain Unicode characters, all these characters will be blank. 

---

The usual way to fix it is that users manually set project settings' `gui/theme/custom_font` to a dynamic CJK font or some font with a CJK font as fallbacks. But it will be weird for every editor plugin in asset library to ask users to set their project setting.

The other way is to use get_ok(), get_cancel(), get_line_edit(), get_vbox()... to get all controls and force them to use english... which is stupid.

---

If the editor plugin is considered part of the editor, then the most logical solution is to have the plugin's font Fallback to the editor's font (which contains all the required characters).

However, some editor plugins are designed to work in-game as well, imagine a plugin that opens a FileDialog in-game ......

### Steps to reproduce

1. Set editor language to zh_CN.
2. Install https://github.com/VP-GAMES/LocalizationEditor.
3. Click the folder/directory icon with "open csv" tooltip.
![图片](https://user-images.githubusercontent.com/23667522/129443448-337c28e4-c0c6-453f-8a5e-aa330c0f6664.png)
4. Texts are blank.
![图片](https://user-images.githubusercontent.com/23667522/129443597-a3c3dacd-4f99-43e4-89c6-3381fd0511ec.png)
5. Set project settings' `gui/theme/custom_font` to a dynamic CJK font, like SourceHanSans. Texts are displayed correctly.

### Minimal reproduction project

https://github.com/VP-GAMES/LocalizationEditor/archive/8185d2d5e69c8e29605f11fd3f0bff75ca58cabd.zip

**Comment by Calinou** [comment] 2021-08-14 15:55
This is partially fixed by https://github.com/godotengine/godot/pull/51159, but CJK languages will remain a problem because the default project font can't include those characters to keep file sizes low.

**Comment by akien-mga** [comment] 2021-08-14 16:01
> If the editor plugin is considered part of the editor, then the most logical solution is to have the plugin's font Fallback to the editor's font (which contains all the required characters).
>
> However, some editor plugins are designed to work in-game as well, imagine a plugin that opens a FileDialog in-game ......

That seems to be the real question here, as indeed editor plugins should use the editor font and would thus not have this issue.

And a plugin meant to be used in-game with a locale that requires better Unicode support, should also mean that the game itself needs such a font that has support for the relevant characters anyway, no? So e.g. projects localized in Chinese using your plugin *would* already use a custom font that supports Chinese characters.

So it's not clear to me in which scenario what is described above is really an issue. (On phone so I haven't checked the reproduction project, will do after the weekend.)

**Comment by pycbouh** [comment] 2021-08-14 16:28
Indeed, unless the plugin overrides its fonts for some reason, this should not be an issue in 4.0, as controls automatically use the font available from their parent control's theme. (So editor font in the editor, game's fonts in when a part of the game).

**Comment by pycbouh** [comment] 2021-08-14 17:20
> In the screenshot provided the file dialog UI uses the default theme, not the editor theme. So my guess is that it's not added to the editor UI properly.

And indeed this is the case. You add your dialog to the root of the editor tree, which is not a branch of the editor node tree that contains the UI and therefore has the theme applied. See lines 76-78 in the `LocalizationEditor.gd` script:

https://github.com/VP-GAMES/LocalizationEditor/blob/main/addons/localization_editor/LocalizationEditor.gd#L76-L78

You should only add controls within the base control of the `EditorInterface`. But in this case you can just add the popup to your scene normally, as a node. You don't need to add the popup to the scene dynamically, popups are hidden by default and can be popped in the same way at any time. Popups also do not need to be added to the root to function properly, they can be anywhere in the tree, as they have a flag set that makes them appear on top of everything regardless.

So this is not an issue, it's a misuse of control nodes. I think it's fair to close it as a non-issue.

**Closed by pycbouh** 2021-08-14 17:20 UTC
Labels: bug, topic:editor, topic:plugin, topic:gui
