### ISSUE TITLE
Port collision layer/mask system from 2D to 3D to improve collision filtering

### ISSUE THREAD

**Issue by Biliogadafr** [godotengine/godot#1759] opened 2015-04-28 19:55 UTC
**Bugsquad edit:** This feature was added to the 2D engine as stated below, but not yet to the 3D engine.

   Sometimes it is necessary to make objects of the same type that don't collide with each other but collide with other objects in a world. For example bullets or enemies that should collide with player but should not collide with each other. Right now it is difficult to achieve such behaviour in godot.
   It would be handy to have collision masks to specify with what layers object can collide, like it is done for example in Box2d or Bullet,

   http://bulletphysics.org/mediawiki-1.5.8/index.php/Collision_Filtering  (example a bit outdated, see notes on the page)
   www.box2d.org/manual.html#_Toc258082972   (scroll down a bit to see 'Filtering' section). 

   Both engines allow collisions only when Object1 allows collision with Object2 and Object2 allows collision with Object1. 
if ((layerA & maskB) != 0 && (layerB & maskA) != 0) { ...collision... }

**Comment by Biliogadafr** [comment] 2015-04-28 19:55
....by the way both engines have possibility to specify collision filtering callback for custom filtering logic. (See "9.5 Contact Filtering" in box2d manual  for example, link above). I like an example with door that can collide only with specific characters. But I'm not sure that it is a good idea to analyze all collisions from scripts for performance reasons(I guess). Maybe this could work for some not physics intense games... Maybe it would be better to add possibility to register such callback only for certain objects to script some specific cases... So this callback override default filtering logic with masks (if both objects have callback - they collide only if both callbacks return true)  Not sure about all this callbacks... just notes to think.

**Comment by reduz** [comment] 2015-05-04 04:07
this was added to 2D engine, if all is well and works as intended, will be ported to 3D

**Comment by eska014** [comment] 2015-10-28 19:19
Since I merged some issues into this, a summary for clarity:
 -  3D Areas lack both collision layers and masks
 -  Remaining 3D CollisionObjects lack masks
 -  3D RayCasts lack layer selection
 -  For 3D Area and RayCast, the following change should be adjusted once Areas have layer and mask selection: https://github.com/godotengine/godot/pull/2587#issuecomment-147017681

**Comment by akien-mga** [comment] 2016-01-26 10:04
Since we're reaching feature freeze for 2.0, moving this to the next milestone.

**Comment by soloparatolos** [comment] 2016-02-22 14:34
Can this long delayed features be on the roadmap for the next 2.1? I think It's quite relevant.

**Comment by zendorf** [comment] 2016-02-24 01:36
Indeed, I am running into all sorts of issues with the collision layers in 3d, and think the whole system needs a rethink! The majority of the time, you want all objects to be collideable by each other . The layer system would be clearer if it was based around which objects are the exceptions(ie the masked ones).

For a start, it would be very useful if there was a toggle on each object to "not collide with instances of itself" (for example with bullets). Then if each physics object had a properties field for a meta tag collision group(or doing it with code) for example tagging all enemies as "enemy". Get rid of the layer boxes and instead have a property field called "avoid collisions with" and typing in the meta tagged groups to avoid (maybe comma separated?) like "enemy, wall, tree". Or, of course, allowing this to be done via code.

**Comment by soloparatolos** [comment] 2016-02-24 07:44
I think the system planed to implement, that is the equivalent of the 2d side, its near perfect. 
For example, I dont want my objects interact with certain other objects and I need to raycast to certain ones. I have hundreds of objects, and as you said, without the "layer blocks", you are obliged to create groups for all objects only for the sake of avoid them. 

You're idea is ok for simple scenes but no for complex setups in my opinion.

The system in the 2d side works very well and its consistent with the visualization layers in the 3dcamera and the light mask.

**Closed** 2016-04-12 11:17 UTC
Labels: feature proposal, topic:core
