### ISSUE TITLE
Import Crash Loop

### ISSUE THREAD

**Issue by daziki** [godotengine/godot#74272] opened 2023-03-03 05:22 UTC
### Godot version

4.0

### System information

Windows 10

### Issue description

Attempted to drag a bunch of files to my FileSystem, unaware I was importing an FBX file; this prompted a window to download FPX2glTF. Clicking cancel will begin the import process in which it has crashed every time. I imported multiple types of 3D file formats, and it seems to crash at random. Closing the program and opening it immediately starts the prompt over again, thus unable to get out of the crash loop. 

### Steps to reproduce

Drag and drop multiple folders. Seems to be fine when one folder is imported but crashes on multiple.

### Minimal reproduction project

N/A

**Comment by akien-mga** [comment] 2023-03-03 10:57
Duplicate of #73319

**Closed by akien-mga** 2023-03-03 10:57 UTC
