### ISSUE TITLE
Animated Texture not working with Atlas Texture

### ISSUE THREAD

**Issue by codewing** [godotengine/godot#37977] opened 2020-04-17 23:41 UTC
**Godot version:** 3.2

**OS/device including version:** Manjaro Linux 5.5.16-1 

**Issue description:**
Creating an Animated Texture and using an Atlas Texture for the sub-images only displays one frozen frame.

**Steps to reproduce:**
- Create a Texture Button
- Select Animated Texture for the Normal Texture
- Set Frames to 2
- First Frame -> Atlas Texture -> Drag in image -> Adjust Region
- Second Frame -> Atlas Texture -> Drag in image -> Adjust Region (different than 1)
- Press play (no animation and full atlas texture is shown)

![image](https://user-images.githubusercontent.com/12066466/79621670-80e45c80-8114-11ea-9a86-57c34bb9df13.png)

**Minimal reproduction project:** 
Open the scene in here: Two frames assigned but full shown,
[minimal_anim_tex_atlas_bug.zip](https://github.com/godotengine/godot/files/4495683/minimal_anim_tex_atlas_bug.zip)

**Comment by KoBeWi** [comment] 2020-04-18 01:24
Duplicate of #37860 (literally the same title; use search next time .-. )

**Closed by KoBeWi** 2020-04-18 01:24 UTC
