### ISSUE TITLE
Reparenting crashes editor in release_debug build (GCC 6)

### ISSUE THREAD

**Issue by her001** [godotengine/godot#4614] opened 2016-05-10 23:11 UTC
**Operating system or device - Godot version:**
Arch Linux 64 bit - Godot master branch (98bff2f) **only** with target=release_debug
git bisect reveals that the issue should effect everything after (and including) 84f96eb

**Issue description**:
Clicking the reparent button in the scene tree pane always crashes the editor, with every node type I have tried.

I tested with target=release_debug and target=debug. Not sure what other options there are that include the editor, but the plain debug build did not have the issue.

**Comment by Calinou** [comment] 2016-05-15 11:29
I can confirm this with Godot Git being installed through AUR. Reparenting a node will always cause an editor crash.

**Comment by bojidar-bg** [comment] 2016-05-15 11:49
@her001 @Calinou ~ BTW, is there any chance this is related to GCC 6 as well?

**Comment by Calinou** [comment] 2016-05-15 11:53
> BTW, is there any chance this is related to GCC 6 as well?

I'm using GCC 6.1, so it may be related.

**Comment by slapin** [comment] 2016-05-15 12:17
Look at that bug for a workaround

**Comment by Hinsbart** [comment] 2016-05-15 12:33
Can confirm it's not crashing for release_debug build with clang (3.7) .

**Comment by neikeq** [comment] 2016-05-15 13:36
No crash here with GCC 4.9.3

**Comment by zaps166** [comment] 2016-05-19 10:48
Crashes on `__cxxabiv1::__dynamic_cast` (`NULL` pointer), so this bug report is the same as #4673 - the same patch fixes this crash.

**Comment by akien-mga** [comment] 2016-05-19 12:03
Closing as duplicate of #4673 then.

**Closed by akien-mga** 2016-05-19 12:03 UTC
Labels: bug, confirmed, topic:editor
