### ISSUE TITLE
putting editor along with game data and running the editor runs the game instead

### ISSUE THREAD

**Issue by Ahmed0425** [godotengine/godot#9020] opened 2017-06-02 13:43 UTC
**Operating system or device - Godot version:**
Windows 10 - Godot Engine 2.1.3 & 2.2 Legacy (not tested with 3.0)

**Issue description:**

Discovered the bug accidentally
game ware exported in the same folder as the editor and when I tried to run the editor, it runs the game instead

**Steps to reproduce:**

1. Put the editor in the same folder as your game
2. run the editor

**Link to minimal example project:**

no need

**Comment by akien-mga** [comment] 2017-06-02 13:44
That's a feature.

**Comment by Ahmed0425** [comment] 2017-06-02 13:52
I've thought that's the template's mission not the editor
any way this is (somehow) expected as godot games executables are just source code runners
could this feature be disabled when compiling with tools=yes parameter?

**Comment by bojidar-bg** [comment] 2017-06-02 14:44
Check related discussion in #7764.

Specifically this comment: https://github.com/godotengine/godot/issues/7764#issuecomment-278892552
> @bojidar-bg Any thoughts on opening the editor by default rather than running the project with a 'tools' build? I'd rather see a '-r ' rather than make '-e ' the exceptional case.

Potentially fixed by #7780, but the later needs to be updated to recent changes.

**Comment by akien-mga** [comment] 2017-06-29 09:44
Closing as duplicate of #7764.

**Closed by akien-mga** 2017-06-29 09:44 UTC
