### ISSUE TITLE
Add LoD hysteresis

### ISSUE THREAD

**Issue by samuncle** [godotengine/godot#6375] opened 2016-09-02 17:28 UTC
Hi, after posting on [the forum](https://godotdevelopers.org/forum/discussion/comment/17817) people suggested me to post here.

Here is my suggestion for an implementation of the first part in Godot Engine (I will do another ticket for the smooth transition)

1) Add an hysteresis, which means when you trigger a LoD change, to trigger it back to it's previous state you must go to a bigger distance
For instance if we have a sphere that appears at 10 unit, to make it disappears, the player must go at ~13 units. This reduce the number of unwanted change.
That could be done automatically with a fixed constant directly in the engine (something like 5 or 3) or with an option in the global project setting. Putting this on a per node basis would be IMHO a vast of time and potentially confusing (if offsets aren't the same across all mesh of the same object it can cause problems).

In the global editor setting there would be simply an option LoD Hysteresis: and by default it would be at 0 (= no effect).

If devs are interested I can try to submit a patch :)

Sam

**Comment by reduz** [comment] 2016-09-02 17:35
ah nice, lets take note of this for 3.0

**Comment by Zylann** [comment] 2016-09-02 17:57
Does Godot handle LoD at all currently?

**Comment by SuperUserNameMan** [comment] 2016-09-02 18:19
@Zylann : through GeometryInstance.set_draw_range_begin/end()

**Comment by Zylann** [comment] 2016-09-02 18:27
Oh. That means you need to create a MeshInstance for every LoD or a mesh for example? 

I am still wondering how a chunked terrain node would perform with this, as the LoD in use depends on the LoD of neighbor chunks to avoid seams (but maybe it's a different issue).

Also, please consider multi-camera (split-screen, mirrors...) and VR when implementing LoD with hysteresis, as it may required to render different LoDs.

**Comment by nunodonato** [comment] 2017-03-27 13:22
I see the hysteresis properties in the current master. Is it safe to close this?

**Comment by reduz** [comment] 2017-08-05 13:19
this feature is a ton more difficult to implement than I initially thought, specially if your scene is being rendered by multiple cameras. if you can think of an algorithm to get it to work in that situation, let me know

**Comment by reduz** [comment] 2017-08-08 16:55
will kick to 3.1 for now, will properly implement all the lod systems there

**Comment by Zireael07** [comment] 2017-08-08 17:00
So why have the hysteresis property displayed in editor if it's not used?

**Comment by reduz** [comment] 2017-08-08 18:18
@Zireael07 because the API is exposed, but the implementation is not written. Might be a good idea to hide it for the time being. Also it might probably be implemented different at some point

**Comment by volzhs** [comment] 2017-12-26 17:15
@reduz probably should hide `Hysteresis` before RC1?

**Comment by Noshyaar** [comment] 2018-04-06 10:06
Still reproducible/relevant in 3.1 master 9ad1800 : VSScene::instance_geometry_set_draw_range does nothing. (Apparently it's planned for 3.1 but I think it's crucial to put in the docs that it's not yet implemented)

**Comment by akien-mga** [comment] 2018-09-15 10:49
Moving to the next milestone as 3.1 is now feature frozen.

**Comment by MysteryGM** [comment] 2018-09-18 19:34
Hi. The LOD system in Godot doesn't work at all, unless I am maybe doing something wrong?
I considered making the LOD system myself, that way I can also batch lower LODs etc, maybe I will do Hysteresis but I am not too good with shaders.

So what I am wondering is how far is the developers with the LOD system?
If I make the LOD system using GDscript will the Godot engine developers be able to integrate it into the engine?

Is GDscript slower than integration? Because if it isn't I could always make it as an addon.

**Comment by akien-mga** [comment] 2020-05-26 10:55
Superseded by godotengine/godot-proposals#692.

**Closed by akien-mga** 2020-05-26 10:55 UTC
Labels: feature proposal, topic:core, topic:rendering

**Comment by Norrox** [comment] 2023-11-21 17:15
Is this an issue again? It's visible in the editor

**Comment by AThousandShips** [comment] 2023-11-21 17:19
Please open a new issue and provide the details as well as a reproduction project

**Comment by Calinou** [comment] 2023-11-22 17:28
This is already implemented in 4.x: https://docs.godotengine.org/en/latest/tutorials/3d/visibility_ranges.html

For 3.x, see https://github.com/godotengine/godot/pull/53778.
