### ISSUE TITLE
Screen space reflection reflecting sky + banding (3.x)

### ISSUE THREAD

**Issue by puchik** [godotengine/godot#38953] opened 2020-05-22 08:06 UTC
**Godot version:**
3.2.2 beta 8cf450c16
**OS/device including version:**
Windows 10 1909
**Issue description:**
The SSR in 3.2 currently reflects the sky which can result in banding on some angles and unnatural stretching of the sky material when starting to look down.

Banding in the reflection
![image](https://user-images.githubusercontent.com/48544263/82645018-13ba6000-9bc7-11ea-9af6-a5b4cbcf54b9.png)

A lot more noticeable when adding even slight roughness
![image](https://user-images.githubusercontent.com/48544263/82645375-a0fdb480-9bc7-11ea-891e-79f7103d490c.png)

Jarring transition from screen space to environment reflection
![image](https://user-images.githubusercontent.com/48544263/82645098-32b8f200-9bc7-11ea-8522-64224d4b3f81.png)

**Steps to reproduce:**
1. Make a new project. Add a shiny flat surface (floor or wall).
1.2. Optionally add an environment that makes the effect more obvious.
2. Observe how at lower angles there's banding + if you have a sky texture set there is a jarring transition when switching from screen space to environment reflection (especially if radiance size for sky is low).

**Minimal reproduction project:**
[ssr-sky-artifacts.zip](https://github.com/godotengine/godot/files/4666792/ssr-sky-artifacts.zip)

**Comment by Zireael07** [comment] 2020-05-22 08:26
A-ha, judging by the pics this should close my ancient issue with artifacts in SSR (will try to link later)

Nicely explains why I couldn't find rhyme nor reason for those, with the amount of geometry in my levels the sky would've been literally the LAST thing I would've suspected!

**Comment by puchik** [comment] 2020-05-22 08:31
This one #18395 ?

**Comment by Zireael07** [comment] 2020-05-22 08:37
Yep. Forgot I already closed it thinking it a dupe of another issue.

**Comment by puchik** [comment] 2020-05-22 20:52
Yeah there was an issue about general SSR artifacting and broken roughness but it all seems to fit under the far clip and pre-blurred mip map issues... this should hopefully at least take care of the far clip/banding one.

**Comment by akien-mga** [comment] 2020-10-18 18:50
Fixed by #38954.

**Closed by akien-mga** 2020-10-18 18:50 UTC
Labels: bug, topic:rendering
