### ISSUE TITLE
VisibleOnScreenNotifier2D screen_enterd signal does not work.

### ISSUE THREAD

**Issue by theBSH** [godotengine/godot#86254] opened 2023-12-17 10:49 UTC
### Tested versions

4.2 mono

### System information

Godot v4.2.stable.mono - Windows 10.0.22621 - GLES3 (Compatibility) - NVIDIA GeForce RTX 3060 (NVIDIA; 31.0.15.3742) - 11th Gen Intel(R) Core(TM) i5-11600K @ 3.90GHz (12 Threads)

### Issue description

VisibleOnScreenNotifier2D screen_enterd does not emit when sprite is on screen but screen_exsited works fine . i tryed forward+ too but the same issue

### Steps to reproduce

add a sprite with VisibleOnScreenNotifier2D as its child
connect the screen_enterd with a function that sets visible to true
connect the screen_exsited with function that sets visible to false
now walk away from the sprite and when you come back its still not visble

### Minimal reproduction project (MRP)

[visiblenotif_bug.zip](https://github.com/godotengine/godot/files/13695743/visiblenotif_bug.zip)

**Comment by AThousandShips** [comment] 2023-12-17 10:52
Duplicate of https://github.com/godotengine/godot/issues/83971

**Closed by AThousandShips** 2023-12-17 10:52 UTC
