### ISSUE TITLE
HW accelarated video playback

### ISSUE THREAD

**Issue by kirgene** [godotengine/godot#24975] opened 2019-01-14 05:31 UTC
Currently Godot's VideoPlayer doesn't support H.264 format and so no hw acceleration on most platforms.
On most mobile platforms video playback it will lead to frame drops.
It would be great if Godot could handle more playback options via ffmpeg or gstreamer.

**Comment by bruvzg** [comment] 2019-01-14 10:05
Both `ffmpeg` and `gstreamer` are LGPL licensed (can't be statically linked, incompatible with mobile platform marketplaces).

H.264 is patented and require license from MPEG LA in the countries where software patents are implemented. But there's [OpenH264](http://www.openh264.org/) library licensed under two clause BSD and with all royalties paid by Cisco as long as you use Cisco's precompiled binaries.

**Comment by eon-s** [comment] 2019-01-14 10:52
Duplicate of #12362

**Comment by volzhs** [comment] 2019-01-14 10:56
closing as it's a duplicate of #12362

**Closed by volzhs** 2019-01-14 10:56 UTC
Labels: feature proposal, topic:rendering
