### ISSUE TITLE
3.5 beta 2 windows don't recognize signature

### ISSUE THREAD

**Issue by Torguen** [godotengine/godot#59189] opened 2022-03-16 08:49 UTC
### Godot version

3.5 beta 2

### System information

w10 64

### Issue description

This appear when execute
![Captura](https://user-images.githubusercontent.com/19652075/158551941-e12e005d-0dfd-4e04-9dce-ee50032719dc.PNG)

Windows protected your pc

Microsoft Defender SmartScreen prevented an unknown application from starting. If you run this application, you could put your PC at risk.

### Steps to reproduce

...

### Minimal reproduction project

...

**Comment by akien-mga** [comment] 2022-03-16 08:52
This is explained in the release post: https://godotengine.org/article/dev-snapshot-godot-3-5-beta-2

> The Windows builds are signed, but the certificate expired recently. The next builds should be signed with a new certificate.

Duplicate of #58545

**Closed by akien-mga** 2022-03-16 08:52 UTC
