### ISSUE TITLE
Can't create new Image in ImageTexture

### ISSUE THREAD

**Issue by Shadowblitz16** [godotengine/godot#43842] opened 2020-11-25 05:28 UTC
**Godot version:**

3.2.3

**OS/device including version:**

Zorin OS 15.3 Nvidia GTX 650 450 proprietary driver 

**Issue description:**

I can't seem to create a new image in the editor for a ImageTexture specificity on the TextureRect node

**Steps to reproduce:**
- Create a new TextureRect node
- Assign a ImageTexture in the texture slot
- Expand it and try to add a new Image in the image slot
- See that it fails

```
 drivers/gles2/rasterizer_storage_gles2.cpp:814 - Condition "texture->data_size == 0 && !texture->render_target" is true. Returned: Ref<Image>()


**Minimal reproduction project:**
<!-- A small Godot project which reproduces the issue. Drag and drop a zip archive to upload it. -->
[TextureRectImageTextureImageBug.zip](https://github.com/godotengine/godot/files/5594594/TextureRectImageTextureImageBug.zip)

**Comment by clayjohn** [comment] 2020-11-25 05:33
Duplicate of https://github.com/godotengine/godot/issues/38112

**Closed by clayjohn** 2020-11-25 05:33 UTC
