### ISSUE TITLE
2.1.6 build error

### ISSUE THREAD

**Issue by alexzheng** [godotengine/godot#32883] opened 2019-10-17 01:20 UTC
**Godot version:**
2.1.6

**OS/device including version:**
Mac OS 10.14.6
**Issue description:**
error: cannot find -lc++
**Steps to reproduce:**
build use the command:
scons platform=android target=release
**Minimal reproduction project:**

**Comment by alexzheng** [comment] 2019-10-17 01:24
also 2.1.5 has the same error.
However, I can build 2.1.5 successfully on the same device months ago.
Maybe Some updates on my device broke the build.

**Comment by alexzheng** [comment] 2019-10-18 13:59
the 3.1.1 source code can build on my MacBook Pro.
What's the problem of the 2.1.6 source code?

**Comment by alexzheng** [comment] 2019-10-25 06:37
the code on the GitHub can build.
only the 2.1.6 has error.

**Comment by akien-mga** [comment] 2019-10-25 06:42
Duplicate of #30688.

**Closed by akien-mga** 2019-10-25 06:42 UTC
Labels: discussion, topic:buildsystem
