### ISSUE TITLE
OS.get_system_time_msecs output is wrong

### ISSUE THREAD

**Issue by PopeRigby** [godotengine/godot#44533] opened 2020-12-19 22:48 UTC
**Godot version:** 

3.2.3

**OS/device including version:**

OS: Arch Linux

**Issue description:**

When running `OS.get_system_time_msecs()` in `_physics_process()`, it seems to be counting incorrectly. The last three numbers will stay the same for multiple lines before flipping even though they're supposed to be milliseconds. It's hard to describe, so here's a video of it happening: 

https://user-images.githubusercontent.com/20866468/102701162-f440ef80-4208-11eb-9b7e-c9ca06ec1b32.mp4

Also, I'm not positive, but I think this might be causing some serious network sync latency issues, because my solution uses this function to sync the world state.

**Steps to reproduce:**
Put `print(OS.get_system_time_msecs())` in `_physics_process()`

**Minimal reproduction project:**

[SystemTimeTest.zip](https://github.com/godotengine/godot/files/5720229/SystemTimeTest.zip)

**Comment by Demindiro** [comment] 2020-12-19 23:12
I'm unable to reproduce this on Debian 10.7 (`Linux pc 4.19.0-12-amd64 #1 SMP Debian 4.19.152-1 (2020-10-18) x86_64 GNU/Linux`). Milliseconds are counting up just fine.

**Comment by PopeRigby** [comment] 2020-12-19 23:16
I don't think it's an issue with my system clock. This bash script seems to be counting just fine:
```
#!/bin/bash
while true
do
    date +"%T.%3N"
done
```

**Comment by PopeRigby** [comment] 2020-12-19 23:30
> Out of curiosity, what do you get if you run date +%s.%3N multiple times?

This: 

https://user-images.githubusercontent.com/20866468/102701743-ebebb300-420e-11eb-92ed-4424929f364b.mp4

**Comment by qarmin** [comment] 2020-12-20 14:44
I also can't reproduce but with Ubuntu 20.04
Are you sure, that you don't set physics fps in project settings to 1?

**Comment by PopeRigby** [comment] 2020-12-20 22:49
Yes I'm sure. I didn't change any project settings, you can check in the project I uploaded.

**Comment by PopeRigby** [comment] 2020-12-21 19:37
I ran a test on my laptop (also running Arch Linux) and got this result:

https://user-images.githubusercontent.com/20866468/102815211-deeed100-4380-11eb-8136-63453a30b2bd.mp4

Does this look right?

**Comment by Faless** [comment] 2020-12-23 15:27
This is fixed by: #39189 . Also, [don't use `OS.get_*_time*`](https://github.com/godotengine/godot/pull/44341) functions for precision timing, use `OS.get_ticks_*` instead.

**Comment by PopeRigby** [comment] 2020-12-23 20:30
How does that pull request fix it not updating correctly?

**Comment by Faless** [comment] 2020-12-24 10:47
> How does that pull request fix it not updating correctly?

Oh, my bad I didn't read the description well, and thought you were on Windows (which had a broken `get_system_time_msecs`).


> Replacing the `OS.get_system_time_msecs()` with `OS.get_ticks_msecs()` in the above problem yields the same broken results.

This is really weird, `get_ticks_msec`/`get_ticks_usec` use a completely different clock source (and that one is monotonic). What if you use `get_ticks_usec`? Even two consecutive calls to `OS.get_ticks_usec()` usually return different values.

**Comment by PopeRigby** [comment] 2020-12-24 20:35
> What if you use get_ticks_usec?

https://user-images.githubusercontent.com/20866468/103105736-7a33b080-45e4-11eb-8302-3e661adb2365.mp4

**Comment by Demindiro** [comment] 2020-12-24 22:13
So it just occurred to me that roughly the same output is printed exactly 8 times per iteration, which reminded me of this particular piece of code:

https://github.com/godotengine/godot/blob/31d0f8ad8d5cf50a310ee7e8ada4dcdb4510690b/main/main.cpp#L2064-L2068

I then managed to reproduce a similar output by executing the following snippet with `godot --frame-delay 1000 -s main.gd`

```gdscript
# main.gd
extends MainLoop


func _iteration(delta: float) -> bool:
	print(OS.get_system_time_msecs())
	return false
```

Output:

```
1608847883988
1608847883988
1608847883988
1608847883988
1608847883988
1608847883988
1608847883988
1608847883988
1608847884988
1608847884988
1608847884988
1608847884988
1608847884988
1608847884988
1608847884988
1608847884988
1608847885988
1608847885988
1608847885988
1608847885988
1608847885988
1608847885988
1608847885988
1608847885988
```

So the question now is: what is limiting the FPS?

**Comment by PopeRigby** [comment] 2020-12-25 01:18
Interesting. Have any ideas of what I can test to figure it out?

**Comment by Faless** [comment] 2020-12-25 11:37
why do you keep using `get_system_time_msecs` while I explicitly told you that's a bad idea.
It's useless to post the result of `get_system_time_msecs` instead of `get_ticks_usec`.

**Comment by PopeRigby** [comment] 2020-12-26 00:46
What are you talking about? The last output I posted was from `get_ticks_usec`.

**Comment by Faless** [comment] 2020-12-26 15:59
I was referring to @Demindiro 's last test.

Anyway, as @Demindiro mentioned, what you are seeing might be the side effect of the way `_physics_process`  happens (see also #17353), i.e. the fact that the `delta` there does not directly represent the time passed since the last function call, but only the time this step should care about.
Although, this should only be relevant when your FPSs (`Main::iteration`) is lower than the physics FPS (which needs to be constant if you want the simulation to be stable).
@PopeRigby can you provide some info on your system (CPU/GPU/Monitor refresh rate)?
Can you check if you end up having a higher physics FPS then rendering FPS?
`Engine.get_frames_per_second()` should be `60` or greater/equal to the value you set in `physics/common/physics_fps` project settings.
`float(Engine.get_idle_frames()) / max(1, float(Engine.get_physics_frames()))` should stabilize to be `>= 1`.
That said, I don't see how the minimal reproduction project you provided could end up doing less then 60 FPS unless there's some (driver?) issue which you should notice anyway when running any project :confused:  .

**Comment by PopeRigby** [comment] 2020-12-27 00:03
>  @PopeRigby can you provide some info on your system (CPU/GPU/Monitor refresh rate)?

Sure.
CPU: Ryzen 5 3700X
GPU: RX 5700XT
Refresh Rate: 60Hz

> Can you check if you end up having a higher physics FPS then rendering FPS?

I'm getting some really bizarre numbers if I print `Engine.get_frames_per_second()` within `physics_process`. It starts out at around 44, then it drops down to 13, and then finally it drops to 1 and stays there.

**Comment by Faless** [comment] 2020-12-27 12:54
> I'm getting some really bizarre numbers if I print `Engine.get_frames_per_second()` within `physics_process`. It starts out at around 44, then it drops down to 13, and then finally it drops to 1 and stays there.

@PopeRigby this likely confirms you have some driver issues, with those specs, you definitively should not have problems reaching 60FPS in an empty scene.

One thing you can try is disabling vsync and see if that's an issue with your setup (`OS.vsync_enabled = false`), but you should also make sure that your drivers are working correctly and can run GL applications well (refer to Arch documentation for that).
In any case, I think you should open a new issue since this one has gone quite off-target, explaining the low FPS in an empty scene with your setup, detailing your hardware and software (OS version, kernel version, mesa version, etc) and reporting `glxinfo` and `glxgears` results.

**Comment by PopeRigby** [comment] 2020-12-28 02:10
> One thing you can try is disabling vsync and see if that's an issue with your setup (OS.vsync_enabled = false)

After disabling v-sync, my FPS starts out at one and climbs to 5 digits. 

> but you should also make sure that your drivers are working correctly and can run GL applications well

I can run GL applications well. I can even run Godot applications very well.

Also, in that game, unfocusing the game window made it drop down to 1, but refocusing it made it climb back up to 60. I'm starting to think that it has something to do with unfocusing the window. That's what my new issue will be about.

**Comment by Faless** [comment] 2020-12-29 08:14
Closing, as the discussion will move over to #44741.

**Closed by Faless** 2020-12-29 08:14 UTC
Labels: bug, needs testing, platform:linuxbsd, topic:core
