### ISSUE TITLE
Open simplex noise only updates when restarting editor 3.2.4 RC4

### ISSUE THREAD

**Issue by dogchamp** [godotengine/godot#46924] opened 2021-03-12 07:01 UTC
**Summary:**
Open simplex noise doesn't appear when added as the noise resource of a noise texture; it simply appears black. This goes for creating a new instance of open simplex noise, as well as for loading a saved instance.

While the texture does appear on restarting the editor, any changes to the noise parameters (seed, period, etc.) don't show until closing and opening the project again. The texture is essentially frozen.

The noise parameters don't produce visible changes if changed via script when running the game either.

**Steps to reproduce:**
1. Add a noise texture to anything, e.g. a texture rect or as a uniform shader param
2. Create a new open simplex noise instance or load an existing one
3. Both the preview window in the inspector and the texture in the viewport will appear black.
4. Save and restart the project - the noise should now appear
5. Try to edit any noise parameters - they should have no effect

**Version and Device:**
I was previously using RC1 where this wasn't an issue. From testing I've found the bug wasn't present in RC2 either, but affects both RC3 and RC4.

OS: MacOS Catalina 10.15.7
Device: Macbook Pro 16"
Graphics: AMD Radeon Pro 5500M 8 GB, Intel UHD Graphics 630 1536 MB

**Comment by akien-mga** [comment] 2021-03-12 07:11
Duplicate of #46907, will be fixed in RC 5.

**Closed by akien-mga** 2021-03-12 07:11 UTC
