### ISSUE TITLE
Output does not print()

### ISSUE THREAD

**Issue by Fredlyb** [godotengine/godot#22723] opened 2018-10-04 17:07 UTC
**Godot version: 3.05 / 3.06**

**OS/device including version: Windows 7**

**Issue description:** tried to print and it didn't. Tried in function _ready(): print("a"), tried in _process, just no printing. Print appears in console, but not in output. Other actions are unaffected.

**Minimal reproduction project:** https://we.tl/t-zQV7GCe84d

**Comment by qarmin** [comment] 2018-10-04 17:27
Works with Godot 3.0.6 and 3.1 on Ubuntu 18.04

Try to rename/delete C:/Users/%USERNAME%/%APPDATA%/roaming/godot/projects

**Comment by DavidSichma** [comment] 2018-10-04 19:07
This also happened to me. It turned out to be the workstation.

I don't know how they messed it up that badly but basically every socket gets blocked. No application is able to communicate, not even with `localhost`. Because of this, many applications fail to work properly. Godot for example can't listen to anything you try to print.

IIRC Godot now shows an error in console if something is wrong with setting up the sockets. So try starting up your game and look for anything regarding "sockets". You may also try other applications like the Java Debugger, which doesn't even start with broken sockets.

If you are working on such a bad workstation: good luck getting them to fix that.

**Comment by Fredlyb** [comment] 2018-10-04 20:27
> This also happened to me. It turned out to be the workstation.
> 
> I don't know how they messed it up that badly but basically every socket gets blocked. No application is able to communicate, not even with `localhost`. Because of this, many applications fail to work properly. Godot for example can't listen to anything you try to print.
> 
> IIRC Godot now shows an error in console if something is wrong with setting up the sockets. So try starting up your game and look for anything regarding "sockets". You may also try other applications like the Java Debugger, which doesn't even start with broken sockets.
> 
> If you are working on such a bad workstation: good luck getting them to fix that.

Unfortunately, this is my own computer and I have no idea what "sockets" are...

**Comment by Fredlyb** [comment] 2018-10-04 20:29
> Works with Godot 3.0.6 and 3.1 on Ubuntu 18.04
> 
> Try to rename C:/Users/%USERNAME%/%APPDATA%/roaming/godot/projects

This had no effect on the issue.

**Comment by qarmin** [comment] 2018-10-05 06:10
Have you tried to disable firewall and antivirus?
I had similar problem with Eset, which blocked this app.

**Comment by qarmin** [comment] 2018-10-07 17:28
Maybe you something changed in editor settings(output or similar)

Try rename whole Godoc data folder - C:/Users/%USERNAME%/%APPDATA%/roaming/godot and try to check if this problem is still occur.

**Comment by Fredlyb** [comment] 2018-10-07 18:00
> Maybe you something changed in editor settings(output or similar)
> 
> Try rename whole Godoc data folder - C:/Users/%USERNAME%/%APPDATA%/roaming/godot and try to check if this problem is still occur.

This was tried, with a whole new project file. Unfortunately with no more result.

**Comment by Calinou** [comment] 2020-06-06 12:25
@Fredlyb Can you still reproduce this in Godot 3.2.1 or 3.2.2beta4?

**Comment by lfzinho** [comment] 2020-06-16 18:48
Hey, I'm not him but I'm having the exact same problem in Godot 3.2.1.
Tried with older versions and it worked, reinstalled v3.2.1 and the problem keeps.

**Comment by Calinou** [comment] 2020-06-17 07:23
@lfzinho Do you see anything in the console output that could indicate an error somewhere? If so, please paste it here. (By "console", I mean the command window/terminal, not the Godot editor's Output panel.)

**Comment by lfzinho** [comment] 2020-06-17 11:19
No, I don't see anything, just the print output.

**Comment by h4de5** [comment] 2020-08-12 20:13
we have the same problem - on one computer, all the output is sent to the command window, but not to the godot output.

no indications about not being able to setup sockets. firewall, AV disabled, new project, reset all editor/projects settings.
my guess is, that godot can not grep the logs from 127.0.0.1:6007 - but gives no information about why.

godot v3.2.2 and v3.2.

**Comment by Calinou** [comment] 2022-11-04 21:28
@Fredlyb @h4de5 Can you (or anyone else) still reproduce this bug in [Godot 3.5.1](https://godotengine.org/article/maintenance-release-godot-3-5-1) or any later release?

If yes, please ensure that an up-to-date Minimal Reproduction Project (MRP) is included in this report (a MRP is a zipped Godot project with the minimal elements necessary to reliably trigger the bug). You can upload ZIP files in an issue comment with a drag and drop.

**Comment by Calinou** [comment] 2022-12-10 21:49
> I believe that this issue is still open. I cannot print out anything to the output window. I am using a Mac and Godot version 3.5.1

I can't reproduce this on 3.5.1 on Linux (or 4.0.beta7):

![image](https://user-images.githubusercontent.com/180032/206876525-b012e58d-a95e-46e7-b9a3-95e3bbc06092.png)

**Comment by KoshakiDev** [comment] 2022-12-11 05:59
> > I believe that this issue is still open. I cannot print out anything to the output window. I am using a Mac and Godot version 3.5.1
> 
> I can't reproduce this with the linked project on 3.5.1 on Linux (or 4.0.beta7):
> 
> ![image](https://user-images.githubusercontent.com/180032/206876525-b012e58d-a95e-46e7-b9a3-95e3bbc06092.png)
> 
> Do you have any firewall software other than the one that comes with stock macOS?

No, I don't think I have any firewall software other than the one that comes with stock macOS. The stock macOS firewall is turned off in my settings

**Comment by KoshakiDev** [comment] 2022-12-11 06:06
Nevermind, the issue was fixed by restarting my computer. It now prints properly

**Comment by and-rad** [comment] 2023-04-17 12:43
Is this still an issue for anyone? I tested it with current 3.5.2, 4.0.2, and master on Windows 10, Arch Linux, and MacOS High Sierra and so far can't reproduce on any of them.

**Comment by Calinou** [comment] 2023-04-17 17:07
Closing as resolved (OP hasn't responded to my ping a while ago). Please comment if you can still reproduce this on the latest Godot version.

**Closed by Calinou** 2023-04-17 17:07 UTC
Labels: bug, platform:windows, topic:core, needs testing
