### ISSUE TITLE
Crash on viewport display menu: View/Settings

### ISSUE THREAD

**Issue by braedenf** [godotengine/godot#8950] opened 2017-05-27 04:53 UTC
**Operating system or device - Godot version:**
Operating system: Mac OS Sierra 10.12.1
Godot Version: Latest master build

**Issue description:**

On the top menu bar of the viewport under View/Settings Godot crashes. 

![screen shot 2017-05-27 at 4 44 54 pm](https://cloud.githubusercontent.com/assets/7875817/26518104/ddd15f6e-42fc-11e7-833c-081c1d6799b2.png)

**Comment by nunodonato** [comment] 2017-05-27 07:10
Safe to close, this is a duplicate of #8489

**Comment by bojidar-bg** [comment] 2017-05-27 07:50
Yeah, closing as dupe of #8489.

**Closed by bojidar-bg** 2017-05-27 07:50 UTC
