### ISSUE TITLE
Control _gui_input inconsistent behavior with InputEventScreenTouch

### ISSUE THREAD

**Issue by DevinPentecost** [godotengine/godot#29525] opened 2019-06-06 05:12 UTC
**Godot version:**
3.1.1 (Live Steam version)

**OS/device including version:**
Windows, deploying to Android

**Issue description:**
When trying to respond to InputEventScreenTouched events on multiple buttons using multiple fingers, I am unable to get consistent events to the actual input events. One button will respond as expected, the other only responds to touch press, not touch released.

Instead, all buttons should get the appropriate touch events for pressed and released, instead of it being inconsistent.

**Steps to reproduce:**
Create two buttons with a simple script that prints messages for InputEventScreenTouch, the event ID, and whether it was pressed. Deploy this to Android with remote debugging. Use two fingers to press the buttons, first by pressing them individually. Then press the two buttons at once and release the left button while pressing down on the right. Then press the right button while holding down on the left.
In the given example, the left button will print out messages for touch DOWN and UP, the right button will only get the event for DOWN.

**Minimal reproduction project:**
[MultiTouch Input Button.zip](https://github.com/godotengine/godot/files/3260074/MultiTouch.Input.Button.zip)
You can use the given APK if you trust random files on the internet, otherwise export it yourself (remember to use remote debugging!)

**Notes**
Overall I'm a little disappointed in Godot's multitouch/mobile support for this input. The regular button does not have standard hooks for these inputs and there are no subclasses that could handle it either. Writing custom code for every button seems overkill when I simply want to fire on relevant touch/drag/press/release events that aren't strictly 'mouse like'. I noticed a Node2D button but it's not obvious what it's for, how to use it, and how to tie it in to an established Control-based GUI.

Thanks!
-Devin

**Comment by DevinPentecost** [comment] 2019-06-06 05:27
Additional Info:
While messing around with the provided project, I was even able to find cases where *neither* button responded to released events. If I first pressed the right button, then tapped the left button, it would only print DOWN events...

It's not consistent, and it should be expected to work for both 100% of the time, but here is what I was able to test out (hopefully it helps with debugging...)

- Single finger tap on either button
    - Get expected DOWN and UP events for either button
- Fingers pressed off the buttons
    - No events, as expected
- Fingers start in middle, slide to a button, and release
    - No DOWN or UP events
    - I'm not sure how to determine if a DRAG event is also released while in the button if it didn't start there
- Single finger on either button, drag off, and release
    - Get a touch released event, this could be checked against the Control's bounding box if needed
- Press right button first, then tap left button, then release right button
    - Sometimes it would respond, other times it wouldn't. Typically though I'd only get DOWN for both buttons, but **never** for the left button!
- Press left button first, then tap right button, then release left button
    - Left button *always* gets DOWN and UP events. Right button *ONLY* gets DOWN events. Unusable

As far as I can tell, this appears to be tied to the `InputEventScreenTouch` `index`. When a button responds to DOWN, it can have *any* `index`. When a button responds to UP, it ***only*** responds when the `index`  is 0! I verified this by trying all of the combinations above with several fingers on both buttons. The only time I would get an 'UP' message is when the `index` was 0!

Obviously since we do not have control over the event indices, that means we cannot correct this in our scripts no matter how clever... unless we constantly polled for ScreenTouch events on every relevant control and looked to see if any disappear and assumed it was an UP event. That shouldn't have to be done at the User Script layer...

Thanks!
-Devin

**Comment by NoFr1ends** [comment] 2019-12-14 22:37
I experienced this issue too. I had a deep dive into the engine afterwards.
Right now it is explicitly programmed to only send the  `InputEventScreenTouch` to `_gui_input` when it is pressed or it has an `index` of 0. The main problem I see why we can't change it easily is because godot currently only keep track of the last focused gui element for events with index 0. We had to extend it for implementing that.

CC @akien-mga

**Comment by NoFr1ends** [comment] 2019-12-15 00:38
More observations:
`InputEventScreenDrag` goes to the focused UI control (or if no control was stored as focused it use the one under the current position). 
` InputEventScreenTouch` pressed go to the correct UI control.
` InputEventScreenTouch` released go to the last focused ui control and not where the touch originally was pressed.

In my opinion we should keep track about where a touch started and send those follow up events (e.g released or drag) to those controls instead of messing the multiple touches up together. This would help to implement proper multi touch controls with using `_gui_input` and without having to implement keeping track of the different touches on its own with `_input`.
If that changes are okay I might be able to create a PR implementing this but it would need really good testing on all platforms with and without using touch.

**Comment by NoFr1ends** [comment] 2019-12-16 17:38
Could reproduce that on iOS too.

**Comment by autofool** [comment] 2021-09-24 15:13
Is there a workaround this? Currently I can not use "Emulate mouse from touch". Because of that I can not use "Button down/up" "pressed" signals on touchscreen. Is there a way to mimic "gui_event" to detect if touch was over button node?

**Comment by Calinou** [comment] 2021-09-24 15:14
> Currently I can not use "Emulate mouse from touch".

Out of curiosity, why can't you use it?

**Comment by autofool** [comment] 2021-09-24 15:22
In one scene, I have camera controlled with gestures of single drag (also with left click drag) to rotate, two finger drag to pan (right click and left click drag), and two finger pinch to zoom in and out (mouse wheel). My problem comes with two finger drag and pinch. I think when I use two finger drag it also sends first touch as emulated mouse drag at the same time. So when I pinch and swipe my (left click drag also gets activated). Now simplest solution is just to disable mouse function when using touch screen device. However I have a casual game that I also want to host on website. It is possible that user might have a laptop with touch screen and mouse or running and android system on PC. So I don't want to disable any input sources as long as I can.

**Comment by CsloudX** [comment] 2022-02-24 05:13
Oh, I experienced this issue too in Godot 4.

**Comment by NoFr1ends** [comment] 2022-02-24 09:21
@CsloudX Feel free to try out PR #49215 and report if that helps.

**Comment by Atem1995** [comment] 2022-03-18 01:37
even v3.4.3 stable still got problem in GUI multiTouch.

**Comment by Sauermann** [comment] 2022-12-04 22:36
I believe, that this was fixed by #68632 and #68630

**Closed** 2022-12-04 22:44 UTC
Labels: bug, confirmed, topic:input, topic:gui
