### ISSUE TITLE
ERROR: Condition "slot >= slot_max" is true. Returning: nullptr

### ISSUE THREAD

**Issue by catafest** [godotengine/godot#80820] opened 2023-08-20 14:36 UTC
### Godot version

Godot Engine v4.1.1.stable.mono.official.bd6af8e0e

### System information

Windows 10 , NVIDIA GeForce GTX 950

### Issue description

I have this video card: NVIDIA GeForce GTX 950
I think the error doesn't come from the video card.
I received this output on my Godot mono console:
```
Godot Engine v4.1.1.stable.mono.official.bd6af8e0e - https://godotengine.org
OpenGL API 3.3.0 NVIDIA 536.23 - Compatibility - Using Device: NVIDIA - NVIDIA GeForce GTX 950

Editing project: C:/GodotProjects/Godot4MainMenu001
Godot Engine v4.1.1.stable.mono.official.bd6af8e0e - https://godotengine.org
OpenGL API 3.3.0 NVIDIA 536.23 - Compatibility - Using Device: NVIDIA - NVIDIA GeForce GTX 950

WARNING: 2D MSAA is not yet supported for GLES3.
     at: render_target_set_msaa (drivers/gles3/storage/texture_storage.cpp:2214)
ERROR: Condition "!texture_allocs_cache.has(p_id)" is true.
   at: texture_free_data (drivers/gles3/storage/utilities.h:111)
ERROR: Cubemap Arrays are not supported in the GL Compatibility backend.
   at: (drivers/gles3/storage/texture_storage.cpp:763)
ERROR: Attempting to use an uninitialized RID
   at: (./core/templates/rid_owner.h:199)
ERROR: Condition "!t" is true.
   at: texture_free (drivers/gles3/storage/texture_storage.cpp:705)
WARNING: 2D MSAA is not yet supported for GLES3.
     at: render_target_set_msaa (drivers/gles3/storage/texture_storage.cpp:2214)
WARNING: Blend file import is enabled in the project settings, but no Blender path is configured in the editor settings. Blend files will not be imported.
     at: _editor_init (modules/gltf/register_types.cpp:73)
WARNING: 2D MSAA is not yet supported for GLES3.
     at: render_target_set_msaa (drivers/gles3/storage/texture_storage.cpp:2214)
ERROR: Condition "slot >= slot_max" is true. Returning: nullptr
   at: get_instance (./core/object/object.h:986)
ERROR: Condition "slot >= slot_max" is true. Returning: nullptr
   at: get_instance (./core/object/object.h:986)
ERROR: Condition "plugins_list.has(p_plugin)" is true.
   at: add_plugin (editor/editor_node.cpp:8195)
ERROR: Condition "slot >= slot_max" is true. Returning: nullptr
   at: get_instance (./core/object/object.h:986)
ERROR: Condition "slot >= slot_max" is true. Returning: nullptr
   at: get_instance (./core/object/object.h:986)
ERROR: Condition "plugins_list.has(p_plugin)" is true.
   at: add_plugin (editor/editor_node.cpp:8195)
ERROR: Condition "slot >= slot_max" is true. Returning: nullptr
   at: get_instance (./core/object/object.h:986)
ERROR: Condition "slot >= slot_max" is true. Returning: nullptr
   at: get_instance (./core/object/object.h:986)
ERROR: Condition "plugins_list.has(p_plugin)" is true.
   at: add_plugin (editor/editor_node.cpp:8195)
ERROR: Condition "slot >= slot_max" is true. Returning: nullptr
   at: get_instance (./core/object/object.h:986)
ERROR: Condition "slot >= slot_max" is true. Returning: nullptr
   at: get_instance (./core/object/object.h:986)
ERROR: Condition "slot >= slot_max" is true. Returning: nullptr
   at: get_instance (./core/object/object.h:986)
ERROR: Condition "plugins_list.has(p_plugin)" is true.
   at: add_plugin (editor/editor_node.cpp:8195)
ERROR: Condition "slot >= slot_max" is true. Returning: nullptr
   at: get_instance (./core/object/object.h:986)
ERROR: Condition "slot >= slot_max" is true. Returning: nullptr
   at: get_instance (./core/object/object.h:986)
ERROR: Condition "slot >= slot_max" is true. Returning: nullptr
   at: get_instance (./core/object/object.h:986)
ERROR: Condition "plugins_list.has(p_plugin)" is true.
   at: add_plugin (editor/editor_node.cpp:8195)
```

### Steps to reproduce

Install Godot Engine v4.1.1.stable.mono.official.bd6af8e0e
Create a project with scenes and link some buttons with pressed signal in one script to the main menu scene.

### Minimal reproduction project

Create a project with scenes and link some buttons with pressed signal in one script to the main menu scene.

**Comment by AThousandShips** [comment] 2023-08-20 14:40
Looks like the same cause as #75568

**Comment by Chaosus** [comment] 2023-08-20 16:18
Duplicate of https://github.com/godotengine/godot/issues/70910

**Closed by Chaosus** 2023-08-20 16:18 UTC
