### ISSUE TITLE
Gamepad's Joystick not working on Android

### ISSUE THREAD

**Issue by NoctisLXV** [godotengine/godot#46489] opened 2021-02-27 21:18 UTC
**Godot version:**
Version 3.2.3 stable official

**OS/device including version:**
Samsung Galaxy A70 - Android 10

**Issue description:**
I was creating my plataform game for Android and I decided to test with a controller to see if the character was good to control. First, I went to the Input Map tab in the Project Settings and assigned each direction of the left stick (up, down, left, right) to their respective actions (ui_up, ui_down, ui_left_, ui_right). Then I played the game in the PC via the editor and worked wonderfully. But, when I exported the game to my Android phone, the moment I touched the Left Stick to move my character to the right, my character started to walk to the left and any other direction didn't. He only stopped when I pressed Left in my directional buttons. After that, I tried to move with the analog stick again, but the game didn't respond to any direction I tried, only the directional buttons.

Later, I tried with the right analog stick and the same thing happened, so I created a little demo to show what happens.

**Steps to reproduce:**
Assign one of the Analog Sticks of a controller to any action in the Input Map tab.
Export the project to Android.
Try to move the analog stick.

**Minimal reproduction project:**
[Controller Test.zip](https://github.com/godotengine/godot/files/6055411/Controller.Test.zip)

**Comment by NoctisLXV** [comment] 2021-02-27 21:34
Oh, and I forgot, I tested both analog sticks and the buttons and only the Analog Sticks doesn't work right. (The only buttons that I don't know If they work or not is The R2 and L2 buttons. I don't tested them and because they are analog and work in Axis like the Analog Sticks, there is a chance they do not work as well.)

**Comment by Calinou** [comment] 2021-02-27 21:49
Duplicate of https://github.com/godotengine/godot/issues/38048.

Also, which controller model are you using?

**Closed by Calinou** 2021-02-27 21:49 UTC

**Comment by NoctisLXV** [comment] 2021-02-27 22:04
I use the Ípega Bluetooth Controller PG-9021.

**Comment by NoctisLXV** [comment] 2021-02-27 22:09
Sorry for creating a duplicate, but there is any solution for this problem?

**Comment by Calinou** [comment] 2021-02-27 22:15
> Sorry for creating a duplicate, but there is any solution for this problem?

You may be able to create a fixed controller mapping, compile an Android export template and use this custom template but testing the mapping will be a long and tedious process if the controller can only be used on Android.

**Comment by NoctisLXV** [comment] 2021-02-27 22:24
Ok, Thank you so much ❤️
