### ISSUE TITLE
Tooltips are bugged when *not* in single window mode

### ISSUE THREAD

**Issue by Karthik-Dulam** [godotengine/godot#62565] opened 2022-06-30 19:08 UTC
### Godot version

v4.0.alpha11.official [d631ee330]

### System information

Arch Linux x86_64

### Issue description

![pic-full-220701-0033-49](https://user-images.githubusercontent.com/59601648/176757819-3bd551aa-0eb9-4135-bf9f-a9fa5f9ef007.png)
![image](https://user-images.githubusercontent.com/59601648/176757904-13f6be40-60ce-476f-942b-5f30f2e8a29a.png)

Any tooltip more than two lines is hardly readable. And the glitched out tooltip persists.

### Steps to reproduce

Install Godot 4 and hover over any field name in the inspector when not in single window mode.

System Information: Archlinux + DWM

**Comment by Calinou** [comment] 2022-06-30 20:06
Duplicate of https://github.com/godotengine/godot/issues/62496.

**Closed by Calinou** 2022-06-30 20:06 UTC
