### ISSUE TITLE
MeshLibrary changes need editor restart

### ISSUE THREAD

**Issue by capnm** [godotengine/godot#26775] opened 2019-03-07 22:50 UTC
**Godot version:**

9af7fa193f65f2caf206b079397fa810d012d803

**OS/device including version:**
Linux

**Issue description:**
Merging items seems to work, but modifying / overwriting does not. The grid map shows the old items unchanged, clearing and reloading the mesh library does not help. The inspector shows the old content until the editor is restarted.

Seems to be a similar caching problem as #25243.

**Repro**
* Open "GM3Test.tscn", in the Scene dock select the "GridMap" node. See the 3 GM library items.
* Open  "GM3Lib2.tscn" and select the "Scene -> Convert to -> MeshLibrary" menu.
* In the "Export Mesh Library" dialogue box set "Merge With Existing" to OFF.
* Select "GM3lib.tres", press "Save". Confirm the "Overwrite" box that appears with OK.
The problems are explained in the pictures and the description.

![image](https://user-images.githubusercontent.com/4047289/53992635-a0494180-412d-11e9-8592-b69e8c5fb0db.png)

![image](https://user-images.githubusercontent.com/4047289/53994409-8bbb7800-4132-11e9-893c-f7e90ace8aab.png)

**Minimal reproduction project:**

[iXXXX-gridmap-editor.zip](https://github.com/godotengine/godot/files/2943685/iXXXX-gridmap-editor.zip)

**Comment by slapin** [comment] 2019-08-06 10:46
I totally confirm this if anybody cares. Also in GridMap selection the view is messed up.

**Comment by capnm** [comment] 2019-08-26 07:57
> I totally confirm this if anybody cares. Also in GridMap selection the view is messed up.

I think everybody gets screwed by this, but nobody is able to fix the thread hell (tm) :-/

**Comment by slapin** [comment] 2019-08-26 14:18
If that is caused by threads, I think a few carefully placed locks should
fix any thread hell...

**Comment by capnm** [comment] 2019-09-02 14:38
> If that is caused by threads, I think a few carefully placed locks should
fix any thread hell...

No idea. The update process runs in different threads and I lose myself when I try to trace the issue back.

**Comment by EzraT** [comment] 2019-09-22 14:19
I can confirm this issue also, tested on a fresh master build:

![image](https://user-images.githubusercontent.com/781121/65389244-42d8b300-dd54-11e9-826d-db0f88b345bf.png)

After updating a MeshLibrary in use by a GridMap, the list of meshes just goes blank until you restart the editor.

**Comment by Alastor01** [comment] 2019-10-21 08:30
> I can confirm this issue also, tested on a fresh master build:
> 
> ![image](https://user-images.githubusercontent.com/781121/65389244-42d8b300-dd54-11e9-826d-db0f88b345bf.png)
> 
> After updating a MeshLibrary in use by a GridMap, the list of meshes just goes blank until you restart the editor.
> Closing and re-opening the scene in question does not help either.
> No errors reported whatsoever.

I think this is a different issue, similar to what I have experienced:
https://github.com/godotengine/godot/issues/32925

**Comment by slapin** [comment] 2019-10-21 21:20
Something tells me it might be related to the same caching issue

**Comment by KoBeWi** [comment] 2020-12-04 00:54
Still valid in 3.2.4 beta3
You don't need to restart editor, just reload the scene. The problem is that MeshLibrary resource doesn't reload until it's unloaded (so all references to it disappear, typical for resources).

Related to https://github.com/godotengine/godot-proposals/issues/1400
Force-reloading the MeshLib when it detects modification would help, not sure if it's possible currently.

**Comment by slapin** [comment] 2020-12-06 18:08
Well, scene reloading did not help me due to caching, had to restart.

On Friday, December 4, 2020, Tomek <notifications@github.com> wrote:
> Still valid in 3.2.4 beta3
> You don't need to restart editor, just reload the scene. The problem is
that MeshLibrary resource doesn't reload until it's unloaded (so all
references to it disappear, typical for resources).
>
> Force-reloading the MeshLib when it detects modification would help, not
sure if it's possible currently.

**Comment by firecloud888** [comment] 2021-02-14 06:20
I hope this issue can be fixed quickly, most 3d game level design really need a great mesh library function

**Comment by Calinou** [comment] 2021-02-14 13:31
@firecloud888 Please don't bump issues without contributing significant new information. Use the :+1: reaction button on the first post instead.

**Comment by KoBeWi** [comment] 2022-05-06 14:16
Fixed in 4.0

**Comment by solusipse** [comment] 2023-05-31 21:11
Unfortunately I'm seeing this in 4.0.3 [5222a99f5].

**Comment by KoBeWi** [comment] 2023-05-31 21:31
Yeah, idk why, but the issue re-appeared.

**Closed** 2023-06-12 09:58 UTC
Labels: bug, topic:editor, confirmed, topic:3d

**Comment by capnm** [comment] 2023-06-13 13:19
@akien-mga I can't see that this is fixed in Godot 3.x. I tested it again today with the official Linux versions v3.5.2.stable and v3.6.beta2.

Nothing seems to have changed, to see the mesh-lib change you still have to restart the editor (or use the menu option to do so). Bugs printed on the console (3.6.beta2):
```
ERROR: Signal "cell_size_changed" from "GridMap:[GridMap:28921]" is already connected to given method "_draw_grids" in "@@16624:[GridMapEditor:27558]".
   at: connect (core/object.cpp:1480)
ERROR: Signal "cell_size_changed" from "GridMap:[GridMap:28921]" is already connected to given method "_draw_grids" in "@@16624:[GridMapEditor:27558]".
   at: connect (core/object.cpp:1480)
ERROR: Signal "cell_size_changed" from "GridMap:[GridMap:28921]" is already connected to given method "_draw_grids" in "@@16624:[GridMapEditor:27558]".
   at: connect (core/object.cpp:1480)
ERROR: Signal "cell_size_changed" from "GridMap:[GridMap:28921]" is already connected to given method "_draw_grids" in "@@16624:[GridMapEditor:27558]".
   at: connect (core/object.cpp:1480)
```

**Comment by akien-mga** [comment] 2023-06-13 13:22
![Screenshot_20230613_152202](https://github.com/godotengine/godot/assets/4701338/71d5ccd4-d4e1-4420-b294-7ce3c4b24ec7)

This means that it was fixed yesterday, in the `master` branch (4.1). So it's expected that it wouldn't be fixed in 3.5.2.stable and 3.6.beta2 which were both released before yesterday (and the fix hasn't been backported to `3.x` anyway).

**Comment by capnm** [comment] 2023-06-13 13:34
Sorry, I was wondering why you closed issue that I wrote about 3.x. Thanks.

**Comment by Schwegg** [comment] 2024-10-14 22:25
still seems to be an issue in 4.3.stable, at least from what I bumped into in my project.

**Comment by KoBeWi** [comment] 2024-10-15 10:08
Can't reproduce in 4.3. Please open a new issue, as it might be something else.

**Comment by j3du** [comment] 2025-02-19 00:09
THE FIX for updating MeshLibrary for Gridmap (tested with 4.3 & Blender .glb file)

- Create inherited scene from .glb
- **Keeps this .tscn scene open on the screen**
- Go to Scene > Export as > MeshLibrary > save however you want with it
- Gridmap will update any changes you made to that .tscn (eg. changing of colors, textures)

*You don't even need to save that .tscn, just make sure it's on the screen when you make the meshLibrary

Not sure if this was already intended way to do it but it took me forever to find out 😄

**Comment by KoBeWi** [comment] 2025-02-19 10:06
Exporting to MeshLibrary exports the current scene, so yes, you need to have it open. The MeshLibrary won't update automatically, you need to re-export the scene to update it.

This issue was about a problem where it also required editor restart, but it's not needed anymore.
