### ISSUE TITLE
Inspector steals focus when editing the script which is attached to the inspected node/resource

### ISSUE THREAD

**Issue by somnivore** [godotengine/godot#22305] opened 2018-09-21 07:16 UTC
**Godot version:**

d9e88bccbea11189b9ea1437d4a48266b69aaf27

**OS/device including version:**

Linux

**Issue description:**

Focus moves from the Script editor to the Inspector panel whenever the script is saved or autosaves, and when the script is on the node or resource being inspected.

By inspecting anything else, or by never selecting anything in the Inspector panel before hand, the problem goes away.

Ideally, focus will not jump to the Inspector panel upon saving.

**Steps to reproduce:**
1. Create a new scene
2. Add a script to the root of that scene
3. Ensure the node with the script is opened in the Inspector
4. Select anything on that node in the inspector
5. Edit the script in any way and save it, the inspector should reclaim focus

**Minimal reproduction project:**

[FocusStealing.zip](https://github.com/godotengine/godot/files/2404262/FocusStealing.zip)

**Comment by olejr** [comment] 2019-01-03 00:44
Another example:

![focuserror](https://user-images.githubusercontent.com/6444415/50619134-be10e500-0ef7-11e9-82e1-07a0fe354d57.png)

Create a Project like above, then edit something in the inspector (Mode/Mass/Gravity Scale).
When commenting/uncommenting 'pass' to get/remove the error text (Indented block expected), focus jump to the place you edited in the inspetor.

**Comment by akien-mga** [comment] 2019-01-23 19:35
Duplicate of #24979, fixed by c70c43c.

**Closed by akien-mga** 2019-01-23 19:35 UTC
Labels: bug, topic:editor, usability
