### ISSUE TITLE
Memory leak and Orphan StringNames on shutdown

### ISSUE THREAD

**Issue by nathanjwtx** [godotengine/godot#41205] opened 2020-08-12 12:49 UTC
Possibly related to:
[https://github.com/godotengine/godot/issues/34954](url)

**Godot version:**
3.2.2 Mono 64-bit
using c#

**OS/device including version:**
Windows 10
NVidia GTX1050
GLES 3.0

**Issue description:**
I have been seeing a memory leak warning on exiting my game. Using `--verbose` as recommended shows that I am getting a bunch of Orphan Stringnames.

```
WARNING: cleanup: ObjectDB instances leaked at exit (run with -
-verbose for details).
     At: core/object.cpp:2135
Leaked instance: Node:1179 - Node name:
Hint: Leaked instances typically happen when nodes are removed
from the scene tree (with `remove_child()`) but not freed (with
 `free()` or `queue_free()`).
Orphan StringName: TileClicked
Orphan StringName: ShuffleTiles
Orphan StringName: Node
Orphan StringName: Invoke
StringName: 4 unclaimed string names at exit.
```

`TileClicked` and `ShuffleTiles` are custom signals in my autoload Singleton file. `Node` could well be anything and I have no idea where `Invoke` is coming from; there is no visible `Invoke` in my project.

I created a sample project with just a button, 2 scenes and a custom signal and get the same result of `Orphan StringName` on shutdown. See attached.

That being said, I don't know if these orphans are related to the memory leak or not. In the test project attached there is no leak.

**Steps to reproduce:**
Run the below project using `--verbose` to see output.

**Minimal reproduction project:**
[MemoryLeakTest.zip](https://github.com/godotengine/godot/files/5062728/MemoryLeakTest.zip)

**Comment by akien-mga** [comment] 2020-08-13 08:27
It seems signals get leaked in C# indeed.

**Comment by paulloz** [comment] 2020-08-29 08:40
Duplicate #39577.

**Comment by Calinou** [comment] 2020-08-29 13:48
Duplicate of https://github.com/godotengine/godot/issues/39577.

**Closed by Calinou** 2020-08-29 13:48 UTC
Labels: bug, topic:mono
