### ISSUE TITLE
Setting Full Rect to Control Nodes Under Node2D does not work

### ISSUE THREAD

**Issue by kidando** [godotengine/godot#28752] opened 2019-05-08 04:18 UTC
**Godot version:**

v 3.1.1 Stable Win64

**OS/device including version:**

Win10

**Issue description:**

When I added a control node to a Node2D node, I was expecting to get the control node stretch to fit the full rect when I clicked the full rect. Instead, that did not happen. It collapsed to the pivot point. 0,0.

But this works when you use the default Node node

**Steps to reproduce:**
1, Create a Node2D node.
2. Add a Control Node
3. Set layout to Full Rect
4. Add ColorRect
5. Set Layout To Full Rect

**Minimal reproduction project:**

**Comment by clayjohn** [comment] 2019-05-08 14:54
When a control is a child of a Node2D, "full rect" makes it expand to the size of the Node2D, which in this case is likely (0,0). While a Node does not have a size, so it likely expands to fill the entire Viewport.

**Comment by volzhs** [comment] 2019-05-08 15:13
duplicate of #18166?

**Comment by clayjohn** [comment] 2019-05-08 15:51
You are right. Closing as duplicate of #18166

**Closed by clayjohn** 2019-05-08 15:51 UTC
Labels: topic:core
