### ISSUE TITLE
set_collision_layer_bit() and set_collision_mask_bit() set the whole bitmask from the passed integer, rather than an individual bit.

### ISSUE THREAD

**Issue by Rodeo-McCabe** [godotengine/godot#45395] opened 2021-01-23 19:11 UTC
**Godot version:**
3.2.3

**Issue description:**
The documentation states the following for the two methods: "Set/clear individual bits on the layer mask. This simplifies editing this Area's layers." However, passing integer 5 to set bit 5 will actually set bits 0 and 2 (the binary representation of 5). Since it is already possible to use a bitmask to set the `collision_mask` and `collision_layer` properties, I'd call this a bug rather than a documentation issue.

The stated goal of the methods is to simplify editing the layers/masks in code, so passing integer 5 should simply set bit 5 of the bitmask.

Edit: this was tested only on Area2D. Since these methods don't seem to be inherited from CollisionObject this issue may not affect other physics bodies.

**Comment by KoBeWi** [comment] 2021-01-23 20:19
Any reproduction project?

I tried with this code
```
func _ready() -> void:
	$Area2D.set_collision_layer_bit(5, true)
	print($Area2D.collision_layer)
```
And the result is 33 as expected. Also the implementation of this method is correct.

**Comment by Rodeo-McCabe** [comment] 2021-01-23 20:47
It should be 32, no? Unless in the editor you already had bit 0 enabled.

Coming back to it after a break it looks like the last bit is being set, rather than bitmasking happening. I'll work on a reproduction project but honestly looks like I might have been out to lunch on this one.

**Comment by KoBeWi** [comment] 2021-01-23 21:04
> It should be 32, no? Unless in the editor you already had bit 0 enabled.

I tested with default values, which have first bit enabled.

**Comment by pouleyKetchoupp** [comment] 2021-02-01 16:34
@Rodeo-McCabe Have you had a chance to test again? Looking at the code, things look correct as `set_collision_layer(5)` does what you describe by design (it uses the value as a bitmask and sets bits 0 and 2) while `set_collision_layer_bit(5, true)` sets bit 5, leaving other bits untouched. Maybe that last part is what caused confusion?

**Comment by pouleyKetchoupp** [comment] 2021-02-19 19:52
I'm closing this issue for now. Feel free to re-open if you can reproduce an issue with the way bits are set.

**Closed by pouleyKetchoupp** 2021-02-19 19:52 UTC
Labels: topic:physics

**Comment by Rodeo-McCabe** [comment] 2021-02-22 01:52
Finally getting back to this, and yes the functions work as expected. Sorry, my mistake.
