### ISSUE TITLE
modified member data from instanced scenes is lost when saving a packedscene

### ISSUE THREAD

**Issue by Gnumaru** [godotengine/godot#32179] opened 2019-09-17 15:13 UTC
**Godot version:**
tag 3.1.1-stable

**OS/device including version:**
windows 10 1903 X64

**Issue description:**
I'm trying to modify data from a node tree instanced from another saved scene and save a new scene containing this instanced scene as a child modified scene, without making the scene data local (that is, still keep the reference to the scene from where the node was instanced) but I can't find a way to keep the changes uppong saving.

**Steps to reproduce:**
I'm using a new, empty project for this example. I created a scene called "a.tscn" which has only two nodes in it, the root node, a Node2d, and a child to the root node, another Node2D. None of them have any scripts attached.

I have also created a scene called "main.tscn", which has only one node in it, the root node, which is a Node2D. This node has a script attached with the folowing code

```
extends Node2D
func _ready():
	var a_packed_scene = load('res://a.tscn')
	var a_node_2d = a_packed_scene.instance(1) # 1 stands for GEN_EDIT_STATE_INSTANCE  in the PackedScene.GenEditState enum
	self.add_child(a_node_2d)
	a_node_2d.owner = self
	a_node_2d.get_child(0).position = Vector2(9,9)
	var new_packed_scene = PackedScene.new()
	new_packed_scene.pack(self)
	ResourceSaver.save('res://b.tscn', new_packed_scene)
```

when running the scene "main.tscn" I expected that the scene saved on "b.tscn" would contain a single child which would be an editable instance for "a.tscn" but instead I get a normal, non editable instance of "a.tscn" and the changes I made to the instance child (in the example, the instance child position) is lost.

I tryed to debug the loading, instancing and packing logics. I have debugged the editor code on scene/main/node.cpp, scene/resources/packed_scene.cpp and scene/resources/resource_format_text.cpp but I could not yet tell exactly what the problem is.

I have seen that the "editable children" context menu item in the editor calls 
	SceneTreeDock::_toggle_editable_children
which calls
	EditorNode::get_singleton()->get_edited_scene()->set_editable_instance(node, editable);
which calls
	data.editable_instances[p] = true;

efectively marking the instance as editable for that scene (since data.editable_instances is this context is an attribute of the edited scene)

Following this logic, in my previous example, there should be some way to set 'a_node_2d' as and editable_instance on its owner (and parent). Since PackedScene has that argument on the instance method I thought somewhere in the pack method would see that 'a_node_2d' is a instance that should be saved as editable and then set it in the editable_instances for the owner data. But while debugging SceneState::pack I could not find the place where this should happen.

Am I missing something here? If the argument for the PackedScene::instance is not meant for this purpose, for what purpose it is? And if this should not be the right way to achieve what I'm trying to do, then what should I do to achieve it on the gdscript side only?

I also searched something similar in the github issues, both open and closed, but could not yet find anything related to my problem.

**Minimal reproduction project:**
[NewGameProject2.zip](https://github.com/godotengine/godot/files/3622089/NewGameProject2.zip)

**Comment by KoBeWi** [comment] 2019-09-17 15:28
When you save a packed scene, it serializes only nodes with owner set to that scene. So when you set owner on your new instance, you need to do it recursively for all children of that instance.

**Comment by Gnumaru** [comment] 2019-09-17 15:58
Thanks for the comment, but unfortunately thats not the issue at hand.

Recursively setting the owner of every children in the instanced node tree is the way to create nodes really owned by that scene, not to make a foreign scene instace editable.

I have to set the instace owner because otherwise the instace whould not be saved, but if I set the owner of some child of the instanced tree it would be equivalent to adding a new childrent to the instance, not making the instance editable.

If one opens the attached project and adds the folowing line before packing
a_node_2d.get_child(0).owner = self
and afterwards run main.tscn and after that opens b.tscn, one will see that a/Node2D is not marked as editable, that is, it does not have its children exposed with a different color in the scene tree. It just shows a new children a/Node2D/Node2D2 as if one had manually added a child node to the non-editable node instance using the editor

**Comment by Gnumaru** [comment] 2020-01-30 12:04
I want to submit a pull request for fixing this issue but before that I would like some hear some thoughts and opinions from other devs that already have some knowledge in godot's codebase (since I currently have none).

It seems that messing with PackedScene::instance was not the right way to tackle this issue because who keeps the info on what node instance is editable or not is it's owner. But when you instance a packedscene it has no owner unless you set one yourself.

What I did was expose to gdscript the Node::set_editable_instance and Node::is_editable_instance methods so that, after instancing the packedscene, I can set explicitly that node as editable before saving into another packedscene. This is a very simple change, only adding two lines of code to Node::_bind_methods
```
ClassDB::bind_method(D_METHOD("set_editable_instance", "p_node", "p_editable"), &Node::set_editable_instance);
ClassDB::bind_method(D_METHOD("is_editable_instance", "p_node"), &Node::is_editable_instance);
```

But it creates the possible problem of exposing functions that maybe should better not be exposed to the user. An alternative solution would be creating two new methods for is_editable and set_editable wich would be called on the instance instead of the owner. Those methods would check if the instace has an owner and only then call is_editable and set_editable on the owner. This approach involves creating two new method signatures in the node.h and two new method implementations in node.cpp beyond adding two new binds to Node::_bind_methods.

**Comment by KoBeWi** [comment] 2020-12-19 09:35
So this is basically duplicate of #20292 based on the last comment.

**Closed by KoBeWi** 2020-12-19 09:35 UTC
Labels: bug, topic:core
