### ISSUE TITLE
blend_rect() not working on android

### ISSUE THREAD

**Issue by ondesic** [godotengine/godot#21429] opened 2018-08-26 04:42 UTC
**Godot version:**
3.06

**OS/device including version:**
Windows 10

**Issue description:**
I am using Image.blend_rect() to merge two images and assign it to a texture/sprite.  It works perfectly on the desktop, however, on the Android it refuses to draw the blended image.

On the desktop here is the result:
![test1](https://user-images.githubusercontent.com/26915986/44624855-24855700-a8b7-11e8-85dc-fe90cb293c72.png)

The white circle shows up fine.  On the Android, it is simply a green image with no white circle.  Here is the entire project.
[Test.zip](https://github.com/godotengine/godot/files/2321243/Test.zip)

Could someone please look at this.  This bug brakes my entire game on the Android.  Thanks!

**Comment by ondesic** [comment] 2018-08-30 04:48
I've been working on this feverishly.  Interestingly, if I swap the whitehole64.png with the icon.png that comes with Godot, it draws fine on the Android.  I have looked at every detail of these 2 images.  All of the attributes of whitehole64.png and icon.png are the same yet godot accepts the icon.png on the Android, but not the whitehole.png

What's going on I wonder?  What's different with these two?

**Comment by KoBeWi** [comment] 2020-06-22 17:04
Can anyone still reproduce this bug in Godot 3.2.1 or any later release (e.g. [3.2.2-rc3](https://godotengine.org/article/release-candidate-godot-3-2-2-rc-3))?

There's a chance it works better in GLES2 which was introduced back in 3.1.

**Comment by KoBeWi** [comment] 2020-09-28 16:24
Closing due to lack of update. Please comment if you can still reproduce this issue in the latest stable version of Godot.

**Closed by KoBeWi** 2020-09-28 16:24 UTC
Labels: bug, platform:android, topic:rendering
