### ISSUE TITLE
Unwanted text-copy-paste in Tree (Control Node) 

### ISSUE THREAD

**Issue by alazifk** [godotengine/godot#60400] opened 2022-04-20 20:32 UTC
### Godot version

4.0 Alpha 6

### System information

Win 10

### Issue description

When you click on various texts in a Tree node and they are set to editable, the last text selected gets copied to the newly selected TreeItem.

### Steps to reproduce

Attach this to a tree node and click on the texts:

```gdscript
extends Tree

# Called when the node enters the scene tree for the first time.
func _ready():
	var a = create_item()
	a.set_text(0,"a")
	a.set_editable(0,true)
	var b = a.create_child()
	b.set_text(0,"b")
	b.set_editable(0,true)
```

**Comment by Calinou** [comment] 2022-04-20 21:49
@alazifk Can you reproduce this on 3.4.4? The Tree node had significant changes in `master`.

**Comment by KoBeWi** [comment] 2022-04-20 21:52
Duplicate of #42419

**Closed by KoBeWi** 2022-04-20 21:52 UTC
Labels: bug, topic:gui
