### ISSUE TITLE
[C#] Network ID size inconsistency

### ISSUE THREAD

**Issue by ryze312** [godotengine/godot#70221] opened 2022-12-17 21:22 UTC
### Godot version

4.0.beta8.official

### System information

Arch Linux X11

### Issue description

PeerConnectedEventHandler and PeerDisconnectedEventHandler delegates require id to be long type, while other MultiplayerAPI methods use int. Is this intentional?

### Steps to reproduce

N/A

### Minimal reproduction project

N/A

**Comment by raulsntos** [comment] 2022-12-18 01:15
From what I can see the C++ code that emits the signal always uses `int32_t` so it should be fine to cast to `int` in C#, unfortunately ClassDB doesn't contain metadata in signals to know if the integer type is meant to be 32-bit or 64-bit so we always generate the bindings assuming 64-bit to be safe. You can read a bit more about this in https://github.com/godotengine/godot/issues/65749#issuecomment-1245819887.

I'm closing as duplicate of https://github.com/godotengine/godot/issues/65749 because it's essentially the same issue despite mentioning a different API.

**Closed by raulsntos** 2022-12-18 01:15 UTC
