### ISSUE TITLE
GDScript 2.0: Cannot override methods when extending ConfigFile built-in class

### ISSUE THREAD

**Issue by tx350z** [godotengine/godot#70839] opened 2023-01-02 14:41 UTC
### Godot version

v4.0.beta10.mono.official [d0398f62f]

### System information

Windows 11 Home OS build 22621.963

### Issue description

Not sure if this is a regression bug or a documentation issue since I've not tried this in 3.5.1.

Attempting to override ConfigFile built-in class methods to include features such as "is_saved" and emitting signals when config values change.

The override methods in the descendent class are not called. I'm assuming the methods are `const` however the docs (https://docs.godotengine.org/en/latest/classes/class_configfile.html) indicate only selected methods are `const`.

### Steps to reproduce

Create a new class called EnhancedConfigFile extending ConfigFile. Add an override method such as `set_value()` in the example below. Instantiate EnhancedConfigFile and call `set_value()`. None of the logic in the override method is executed. Tried setting a breakpoint and it was not triggered.

```
class_name EnhancedConfigFile
extends ConfigFile

enum ACTION {
	VALUE_CHANGED,
	KEY_ERASED,
	SECTION_ERASED,
	PARSE_LOAD,
	LOADED,
	SAVED,
}
signal changed(action:ACTION,section:String,key:String,old_value,new_value);

## Overrides ConfigFile.set_value().
## Adds logic to set saved state and and emit changed signal.
func set_value(section:String, key:String, new_value)->void:
	# check for a value change
	print("EnhancedConfigFile.set_value(%s,%s,%s)"%[section,key,new_value]);
	var old_value;
	if has_section(section) and has_section_key(section,key):
		old_value = get_value(section,key);
	
	if new_value != old_value:
		super.set_value(section,key,new_value);
		changed.emit(ACTION.VALUE_CHANGED,section,key,old_value,new_value,OK);
		_is_unsaved = true;
	return;

```
  

### Minimal reproduction project

See example above.

**Comment by AThousandShips** [comment] 2023-01-02 14:50
`set_value` isn't a virtual function so it's not possible to override it, as far as I know.

**Comment by tx350z** [comment] 2023-01-02 20:31
Just verified is works as expected in in 3.5.1 so it appears to be a regression.

**Comment by AThousandShips** [comment] 2023-01-02 20:33
If you check the issue I referenced you will see the debate on it

**Comment by tx350z** [comment] 2023-01-02 20:54
I've read the issue but it is unrelated as it addresses explicitly set() and get(), which are special cases.

The case I'm referencing is the general ability of a descendent class to override an ancestor method. It's no different than creating a custom class A then extending it with custom class B. Class B should be able to override or "shadow" methods defined in class A. There should be nothing special if class A happens to be a built-in class.

The simple question is whether the capability present in 3.5.1 and missing from 4.0 is intentional or not. If not intentional, it's a regression bug. If intentional, then it's a (poorly conceived) feature.

**Comment by AThousandShips** [comment] 2023-01-02 21:09
No, it's debated there so best take it there, not just those specific functions, it's not a regression

**Comment by YuriSizov** [comment] 2023-01-03 11:03
Duplicate of https://github.com/godotengine/godot/issues/55024.

**Closed** 2023-01-03 11:03 UTC
