### ISSUE TITLE
It shouldn't be possible to (easily) create script named ".gd" 

### ISSUE THREAD

**Issue by Maykeye** [godotengine/godot#21430] opened 2018-08-26 05:44 UTC
**Godot version:**
3.0.6, master as of 8c435a343e9739f30cb2e347df95835c91c1ff1a

**OS/device including version:**
Linux

**Issue description:**
if you choose to a create new gdscript file  in the script  editor, by default it will be named ".gd"  (dot G D)
When you press Ctrl-S after that, it will be saved as (unsurprisingly) ".gd" at which point you'll have to find the script in filesystem dock and rename it to something sensible.

**Expected behaviour:**
Editor should either refuse to create a new script until its name is given(right now it doesn't even show a warning), 

or ask for the name when Ctrl-S is pressed (as most text editors do)

**Steps to reproduce:**
In script editor File->New, click Create without changing anything, Press Ctrl-S

**Comment by akien-mga** [comment] 2018-09-12 09:50
I can't reproduce it in the master branch (c7fc3dcab):
![screenshot_20180912_115006](https://user-images.githubusercontent.com/4701338/45417255-09219680-b682-11e8-880a-1567eb97d178.png)

**Comment by akien-mga** [comment] 2018-09-12 09:53
It was fixed by 69c09ab2fdcfcc9de42ddcb3b7580c118b2182a3, which closed #13965 (which this issue duplicates). I'll push a fixup though as it's still possible to name a script `    .gd`.

**Closed by akien-mga** 2018-09-12 09:53 UTC
Labels: bug, junior job, topic:editor, usability
