### ISSUE TITLE
HTML5 engine is not able to download/save data from web

### ISSUE THREAD

**Issue by alexwbc** [godotengine/godot#40247] opened 2020-07-09 21:26 UTC
**Godot version:**
3.2.3 custom build

**OS/device including version:**
Lubuntu 20.04, Gles3

**Issue description:**
HTTPRequest node is request to store a file (webp in demo test provided) in user:// folder
- in editor works
-in linux binary works
- in HTML5/webassembly doesn't  

**Steps to reproduce:**
+ request a file from web with HTTPRequest
+ try to access to the downloaded file
= works on anything else but on webassembly

**Minimal reproduction project:**
demo simply download tux clipart from web and replace Godot's mascot sprite icon ASAP
[test-src.zip](https://github.com/godotengine/godot/files/4899577/test-src.zip) (bare source)
[test-lin.zip](https://github.com/godotengine/godot/files/4899579/test-lin.zip) (include linux binary engine)
[test-web.zip](https://gofile.io/d/tzwSIP) (include webassembly project (doesn't work)

**Comment by Calinou** [comment] 2020-07-09 21:40
Do you see any errors in the browser inspector console when making the HTTP request?

**Comment by alexwbc** [comment] 2020-07-10 07:02
`Godot Engine v3.2.3.beta.custom_build.6fd712c87 - https://godotengine.org tmp_js_export.js:2582:16
OpenGL ES 3.0 Renderer: Mozilla tmp_js_export.js:2582:16
 tmp_js_export.js:2582:16
**ERROR**: HTTPClient blocking mode is not supported for the HTML5 platform. tmp_js_export.js:2594:16
   At: platform/javascript/http_client_javascript.cpp:201:set_blocking_mode() - Condition "p_enable" is true. tmp_js_export.js:2594:16`


This error appear only in HTML5, I don't know how disable HTTPClient blocking mode; but online guide reference says it's default to false.

**Comment by akien-mga** [comment] 2020-07-10 07:18
Looking at your code, it seems that blocking mode is not enabled manually indeed.
```gdscript
# main.gd
        _request=$HTTPRequest
        _request.connect("request_completed", self, "_on_request_completed")
        _request.set_download_file(str("user://",namefile))
```
```ini
# main.tscn
[node name="HTTPRequest" type="HTTPRequest" parent="."]
use_threads = true
```

On the other hand you enabled threads, which are not supported on HTML5 yet, so maybe that's the problem?

That wouldn't explain why you get an error about blocking mode though, so this should be looked into. And you should be getting an error about threads if they are the problem.

**Comment by alexwbc** [comment] 2020-07-10 11:48
I have activated `use_threads` while testing various options to make it work (then forgot it enabled).
The actual error that block the download of external data seems to be this:
`Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://www.phoca.cz/phocacartdemo/images/phocagallery/Webp/thumbs/phoca_thumb_l_2_A-WEBP.webp. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).`
[reference link](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS/Errors/CORSMissingAllowOrigin) given.

It seems like I've to enable _Access-Control-Allow-Origin: \*_
I've tried to rename index.html into index.php and add this line:
_<?php header("Access-Control-Allow-Origin: *")?>_
(yes, local server with php enabled, not the one from Godot)

But the error seems to come from the file index.js

![image](https://user-images.githubusercontent.com/42388967/87151392-0874de00-c2b4-11ea-9c04-e225a55c3edb.png)

**Comment by Calinou** [comment] 2020-07-10 11:56
There's a `Image.load_webp_from_buffer()` method you can use to load a WebP file without saving it to the filesystem. Try to use it and see if solves the issue.

**Comment by alexwbc** [comment] 2020-07-10 13:02
adjusted with `Image.load_webp_from_buffer()` only
[test.zip](https://github.com/godotengine/godot/files/4903203/test.zip)
Runs fine from editor, same error in browser:
![image](https://user-images.githubusercontent.com/42388967/87156952-c94b8a80-c2bd-11ea-8b9c-6d3331509f2a.png)

**Comment by Calinou** [comment] 2020-07-10 13:09
@alexwbc The CORS request is still blocked, so the file can't be downloaded. You need to ask the host to allow CORS, set up a proxy that allows CORS or use a browser add-on to bypass CORS (for development purposes only).

**Comment by alexwbc** [comment] 2020-07-10 13:28
With addon to pass CORS it works with no error:
![image](https://user-images.githubusercontent.com/42388967/87159675-01ed6300-c2c2-11ea-8664-0828e0d45025.png)
it's the buffer one, but I do suppose the storage does work properly too

**Comment by Faless** [comment] 2020-07-20 13:04
Caused by browser restrictions on CORS. Nothing we can do about it. Closing.

**Closed by Faless** 2020-07-20 13:04 UTC
Labels: platform:html5, topic:porting
