### ISSUE TITLE
Android export uses Vulkan even when gl_compatibility selected

### ISSUE THREAD

**Issue by jamaggs** [godotengine/godot#68048] opened 2022-10-30 11:06 UTC
### Godot version

4.0 beta 3

### System information

Xubuntu 22.04 for editing, LineageOS 14.1 for testing

### Issue description

Hello

When exporting to Android using Godot 4.0 beta 3 official build, I have selected Rendering Method.mobile to be gl_compatibility but after installing on a phone that doesn't support Vulcan, an error message comes up when I run on the phone saying "Unable to initialize Video driver. Your video card driver does not support any of the supported Vulcan versions.".

By contrast, when exporting for Linux if gl_compatibility is selected it does seem to run on opengl rather than Vulcan.

Many thanks for your help

### Steps to reproduce

With any project, choose gl_compatibility as renderer in project options under mobile then export for Android.

**Comment by autofool** [comment] 2022-11-08 14:26
I can confirm this issue on beta4 with same error. Project actually works with Vulkan driver in my device. Even if Godot is trying to run with Vulkan instead of OpenGL, it should not throw that error but then again, maybe project is modified for OpenGL but expecting Vulkan driver?

**Comment by akien-mga** [comment] 2022-11-17 13:42
I can confirm the issue, tested with a build from the current `master` branch (0b27173919b583fdebee5eeca8ef4144b5a08011).

Given the bug in #67034 I checked if the other usage of `getGlobal` might also be wrong here, but it seems fine, including handling the `.mobile` or `.android` overrides:

https://github.com/godotengine/godot/blob/0b27173919b583fdebee5eeca8ef4144b5a08011/platform/android/java/lib/src/org/godotengine/godot/Godot.java#L277-L282

So the problem must be with the init in `GodotGLRenderView`, even though it misleadingly reports that the device "doesn't support any of the supported Vulkan versions".

**Comment by clayjohn** [comment] 2022-11-17 16:48
The problem is in display_server_android. When the display server is created it forces the rendering driver to "vulkan" regardless of what was selected. This is in place because OpenGL initialization hasn't been implemented for Android yet.

**Comment by m4gr3d** [comment] 2022-11-30 18:58
Should be fixed by https://github.com/godotengine/godot/pull/69355

**Closed by m4gr3d** 2022-11-30 18:58 UTC
Labels: bug, platform:android, topic:rendering, confirmed, topic:export
