### ISSUE TITLE
get_mesh_arrays() generates nonsensical ARRAY_INDEX values

### ISSUE THREAD

**Issue by UQuark** [godotengine/godot#79114] opened 2023-07-06 16:16 UTC
### Godot version

4.0, 4.1 stable

### System information

Godot v4.1.stable - Arch Linux #1 ZEN SMP PREEMPT_DYNAMIC Tue, 04 Jul 2023 08:39:22 +0000 - Vulkan (Mobile) - dedicated AMD Radeon RX 6700 XT (RADV NAVI22) () - AMD Ryzen 5 5600X 6-Core Processor (12 Threads)

### Issue description

I'm trying to modify PlaneMesh geometry with code (via MeshDataTool).
To do that, I construct ArrayMesh and copy PlaneMesh's arrays to it (obtained with get_mesh_arrays()).
It works perfectly on PC, but failed on Android.
The error was:
```
E 0:00:01:0300   Soil.gd:23 @ _fill_grass(): Index r[i] = 16256 is out of bounds (vcount = 144).
  <C++ Source>   scene/resources/mesh_data_tool.cpp:72 @ create_from_surface()
  <Stack Trace>  Soil.gd:23 @ _fill_grass()
                 Soil.gd:15 @ _ready()
```
After some debugging I found out that arrays 12th array (ARRAY_INDEX as is declared [here](https://github.com/godotengine/godot/blob/970459615f6b2b4151742ec6d7ef8559f87fd5c5/scene/resources/mesh.h#L105)) is full of seemingly leftover uninitialized junk.

PC values:
![Screenshot from 2023-07-06 19-03-42](https://github.com/godotengine/godot/assets/20577158/09911df1-d681-495c-8965-69e2d154687a)
Android values:
![Screenshot from 2023-07-06 19-03-24](https://github.com/godotengine/godot/assets/20577158/6e43428c-7b96-4116-8337-d1454d336140)

### Steps to reproduce

1. Create a new project
2. Add a node, attach a script
3. Put
```	
        var pm = PlaneMesh.new()
	var arrays = pm.get_mesh_arrays()
```
4. Set a breakpoint
5. Run with remote debug on an Android device
6. Observe arrays 12th element going nuts in Stack Variables

### Minimal reproduction project

[test.zip](https://github.com/godotengine/godot/files/11970176/test.zip)

**Comment by AThousandShips** [comment] 2023-07-06 16:18
* Duplicate of: #75599

Thank you for reporting

**Closed by AThousandShips** 2023-07-06 16:18 UTC
