### ISSUE TITLE
SSAO Banding and Lagging Severly

### ISSUE THREAD

**Issue by BlueCannonBall** [godotengine/godot#34624] opened 2019-12-26 23:21 UTC
**Godot version: 3.1.1 Stable**

**OS/device including version:** Lenovo Ideapad 320 laptop, Intel UHD Graphics 620, Intel CORE i7 8th Gen, Windows 10

**Issue description:** Whenever I add the SSAO (Screen Space Ambient Occlusion) effect to my environment in 3D, the scene starts lagging beyond usability. (20-30 FPS in editor, 1-30 FPS in game.) Also, severe banding and artifacts appear especially when FPS is high and the camera is near meshes. Overall, this makes SSAO unusable. Plus, the effect looks really bad with lots of dots even without taking the artifacts into assessment. Unity works just fine.

**Steps to reproduce:**

1.  Create a 3D scene.
2. Add a directional light, tilt it at a natural angle, and turn on shadows.
3. Add a few meshes occluding at sharp angles in shadow.
4. Add a WorldEnvironment node to the scene and turn on SSAO. The settings don't matter.
5. To increase the unwanted artifacts, up the Intensity properties.
6. Use a fly camera or orbit controls to view the artifacts, which are most visible in motion.

**Video I took**
[Google Drive Link](https://drive.google.com/file/d/19WirJv0J3aNtVoOAC58tCNjOYJ4DNpqi/view?usp=sharing)

**Comment by Calinou** [comment] 2019-12-26 23:47
Duplicate of #17568 and #34580.

**Closed by Calinou** 2019-12-26 23:47 UTC

**Comment by BlueCannonBall** [comment] 2019-12-27 00:28
Why do other engines do such a good job? In Unity, as long as I limit the vegetation, I could run SSAO at 60 FPS with little to no hitches, even on slightly lesser hardware. Godot dosen't even have vegetation. Also, Unity is pretty much artifact free, and light baking actually works on any mesh, so SSAO isn't even necessary. On Godot, only MeshInstances actually bake, and they are filled with artifacts. No baking for CSG stuff, or for plugins that generate mesh. Plus, the BakedLightmap node causes a crash on bake most of the time, and GIprobes are too slow for use in game, no matter the settings. Lastly, I can't even unwrap most mesh's UV2s, as the option often dosen't present its self.

**Comment by BlueCannonBall** [comment] 2019-12-27 00:29
Why do other engines do such a good job? In Unity, as long as I limit the vegetation, I could run SSAO at 60 FPS with little to no hitches, even on slightly lesser hardware. Godot dosen't even have vegetation. Also, Unity is pretty much artifact free, and light baking actually works on any mesh, so SSAO isn't even necessary. On Godot, only MeshInstances actually bake, and they are filled with artifacts. No baking for CSG stuff, or for plugins that generate mesh. Plus, the BakedLightmap node causes a crash on bake most of the time, and GIprobes are too slow for use in game, no matter the settings. Lastly, I can't even unwrap most mesh's UV2s, as the option often dosen't present its self.

**Comment by Calinou** [comment] 2019-12-27 15:25
@BlueCannonBall SSAO will be reimplemented in the Vulkan renderer (which will be in 4.0). It'll hopefully be more efficient there.

**Comment by BlueCannonBall** [comment] 2020-01-29 23:26
Yay! New lightmapper! Was really looking forward to that.
