### ISSUE TITLE
Local to Scene on Resource Fails to Create New Instance for Nested Scenes

### ISSUE THREAD

**Issue by Luzzotica** [godotengine/godot#77380] opened 2023-05-23 00:37 UTC
### Godot version

4.0.3

### System information

MacOS

### Issue description

Given the following structure:

Parent (PackedScene)
- Child (PackedScene, non-local)

Where the child exposes a resource (Shape, Material, etc.)

If you set the resource to be local to scene, and you instantiate the Parent, the resource will not be duplicated per scene.

This can be worked around my making scenes "local", but this detaches the node and isn't maintainable.

### Steps to reproduce

Create a PackedScene test node, we will call it `Swag`
Add a child CollisionShape2D, save it as a scene.
Add a shape to the CollisionShape2D, and set the resource to be Local to Scene.

Write some code to create two Swags and print out the shape resource of each CollisionShape2D child.
They will both be the same.

### Minimal reproduction project

[ResourcePackedScene.zip](https://github.com/godotengine/godot/files/11538015/ResourcePackedScene.zip)

**Comment by jerryjrowe** [comment] 2023-05-24 22:57
This is happening to me too.

I am running Godot 4.0.3
My system is running Linux (Ubuntu 22.04)

Worse, this is happening any time there resource are nested within other resources.

I'm not sure if this is a separate issue or not, though, or just "more of this issue."

If you make a new scene, and have an exposed resource (A),  that also has another exposed resource (B), the nested resources (B) will still be shared, even if `resource_local_to_scene == true` at every possible step. Even when you check with print(), it will say that `resource_local_to_scene==true` but....they are still definitely being shared.

This is a big problem when my Characters (A) have Spells (B).  While all the Characters are able to be unique / truly local to scene, the Spells are shared.

Let me know if I need to open a new issue!

**Comment by jerryjrowe** [comment] 2023-06-06 00:10
I am still experiencing this error and it is hugely frustrating. I cannot figure out a workaround other than to stop using arrays and dictionaries, and that feels...untenable. 

I think that this may just be another instance of an existing error, though?
https://github.com/godotengine/godot/issues/71243

**Comment by RedMser** [comment] 2023-10-20 11:34
Can confirm that this is a duplicate of #71243
Trying the MRP with #71578 applied fixes the problem.

**Comment by KoBeWi** [comment] 2023-10-20 12:00
Actually seems already fixed in 4.2 beta2. I get this result:
```

Nested
<Resource#-9223372007528200979>
Shape
<CircleShape2D#-9223372007494646545>
```
Can someone confirm?

**Comment by RedMser** [comment] 2023-10-20 12:18
I tested it. You have to click the button multiple times, and see if the RIDs change between each print.

**Comment by KoBeWi** [comment] 2023-10-20 12:23
They are different each time.

**Comment by RedMser** [comment] 2023-10-20 12:37
Ahh my bad, I tested with 4.1.1 🤦‍♂️
Can confirm the same, RIDs changing each time on 4.2b2.

**Comment by AThousandShips** [comment] 2023-10-20 12:38
Those are object IDs, not RIDs

**Comment by AThousandShips** [comment] 2023-10-20 12:42
What's the status on 4.1.2?

**Comment by RedMser** [comment] 2023-10-20 12:46
Also fixed on 4.1.2

**Comment by RedMser** [comment] 2023-10-20 12:46
Same print each time on 4.1.2 stable, so not fixed

**Comment by KoBeWi** [comment] 2023-10-20 14:42
If it's fixed in the newest version it can be closed.
We could possibly cherry-pick if someone determines the exact commit.

**Closed by KoBeWi** 2023-10-20 14:42 UTC
Labels: bug, topic:core
