### ISSUE TITLE
Scale, global_position bug

### ISSUE THREAD

**Issue by AlexHolly** [godotengine/godot#9464] opened 2017-07-01 19:37 UTC
Scale with 2> like Vector2(3,3) or Vector2(20,20) produces a wrong global_position.

![image](https://user-images.githubusercontent.com/4741886/27764889-d0896f22-5ea4-11e7-80bc-697ca338daa9.png)

**Comment by bojidar-bg** [comment] 2017-07-01 19:44
This happens because Control nodes have only integer position/size, not floating-point as Node2D. Thus, a duplicate of #6540.

**Closed by bojidar-bg** 2017-07-01 19:44 UTC
