### ISSUE TITLE
Saving with `Ctrl + S` brings the main editor window to front regardless of the window the shortcut was pressed in

### ISSUE THREAD

**Issue by mieldepoche** [godotengine/godot#81422] opened 2023-09-07 15:51 UTC
### Godot version

4.1.1

### System information

linux

### Issue description

[simplescreenrecorder-2023-09-07_17.48.09.webm](https://github.com/godotengine/godot/assets/71937306/41ecb3ee-6ca4-4bbe-b393-8b43a198ee86)

as seen in the video, pressing `Ctrl + S` (in a poped out shader editor, script editor, or even a dock like the FileSystem or Inspector) raises the main editor window.

### Steps to reproduce

1. separate a window 
2. hide the main editor behind another window
3. give focus to floating window and press `Ctrl + S`

### Minimal reproduction project

any

**Comment by Sauermann** [comment] 2023-09-07 17:10
Looks like a duplicate of #78672

**Closed** 2023-09-08 01:06 UTC
