### ISSUE TITLE
POT Generation ignores `instantiated` nodes in `.tscn`

### ISSUE THREAD

**Issue by ghost** [godotengine/godot#79442] opened 2023-07-13 21:17 UTC
### Godot version

v4.0.3.stable.official [5222a99f5]

### System information

N/A

### Issue description

The **POT Generation** ignores instantiated scenes.

Investigating the source code, it's probably because of this check:

https://github.com/godotengine/godot/blob/5222a99f5d38cd5346254cefed8f65315bca4fcb/editor/plugins/packed_scene_translation_parser_plugin.cpp#L55-L58

Because **instantiated** nodes returns empty for the `type` here:
https://github.com/godotengine/godot/blob/5222a99f5d38cd5346254cefed8f65315bca4fcb/scene/resources/packed_scene.cpp#L1417-L1421

### Steps to reproduce

1. Open the MRP;
2. Trigger the **POT Generation** in the `ProjectSettings`;
3. Open the generated **.pot** and note that the **instantiated** node `text` wasn't serialized, but the local node was.

### Minimal reproduction project

[pot_generation_fails_for_instanced_nodes.zip](https://github.com/godotengine/godot/files/12044461/pot_generation_fails_for_instanced_nodes.zip)

**Comment by Okxa** [comment] 2023-10-30 10:14
Reported previously here: https://github.com/godotengine/godot/issues/74194

**Comment by AThousandShips** [comment] 2023-10-30 13:08
Duplicate of https://github.com/godotengine/godot/issues/74194

**Closed by AThousandShips** 2023-10-30 13:08 UTC
Labels: bug, topic:core, topic:editor
