### ISSUE TITLE
StyleBoxFlat shadows can exit editor preview

### ISSUE THREAD

**Issue by droc101** [godotengine/godot#41657] opened 2020-08-31 20:37 UTC
**Godot version:**
3.1.1

**OS/device including version:**

MacOS 10.14.6 with NVIDIA GeForce 9400M (GLES3)

**Issue description:**
When I was messing with panel styles, I made a size 1000 shadow, and it overlapped some of the editor controls.

**Steps to reproduce:**
Make a StyleBoxFlat
Set shadow size to 1000

**Minimal reproduction project:**
just make a project and use a control node to do the above steps.

**Screenshot**
![image](https://user-images.githubusercontent.com/37421449/91766168-c07d8380-eb9f-11ea-8738-2d3aca0e0920.png)

**Comment by Calinou** [comment] 2020-08-31 20:50
This can probably be fixed by enforcing a more reasonable maximum size for the shadow. Since the shadow uses a not very natural-looking falloff, it's probably fine to restrict its maximum size to 100 in the property hint.

**Comment by nathanfranke** [comment] 2020-09-01 20:32
I can't reproduce this in `3.2.2 stable` or 23ce1dbfd
![image](https://user-images.githubusercontent.com/14253836/91902984-1f0e3480-ec68-11ea-8776-4b736f8a02c8.png)
![image](https://user-images.githubusercontent.com/14253836/91903129-5250c380-ec68-11ea-970f-8a376631cb28.png)

**Comment by EricEzaM** [comment] 2020-09-04 07:58
I can't repro on 3.2.2 stable or 5c0fabd either. Since this is a) not on either version and b) a very minor bug in 3.1, I think this can be closed?

**Comment by akien-mga** [comment] 2020-09-04 08:05
Yes, closing as fixed in 3.2.

**Closed by akien-mga** 2020-09-04 08:05 UTC
Labels: bug, topic:editor
