### ISSUE TITLE
Editor crash after adding a point by intersecting the Curve2D line and undoing the change from the history.

### ISSUE THREAD

**Issue by WhalesState** [godotengine/godot#96636] opened 2024-09-06 03:58 UTC
### Tested versions

4.3 stable

### System information

Windows 10

### Issue description

N/A

### Steps to reproduce

https://github.com/user-attachments/assets/e970196d-b0a4-47ff-8d4b-1b20a9de6830

### Minimal reproduction project (MRP)

N/A

**Comment by blam23** [comment] 2024-09-06 16:35
I can't seem to get this to crash, I get two errors though:

> core/object/undo_redo.cpp:471 - Condition "action_level > 0" is true. Returning: ""
> core/object/undo_redo.cpp:426 - Condition "action_level > 0" is true. Returning: false

Version: v4.3.stable.official [77dcf97d8]

https://github.com/user-attachments/assets/26870273-a1a0-4ead-b87c-9109f193d325

**Comment by blam23** [comment] 2024-09-06 16:47
Ok, it crashes if you use the history sidebar, but not if you use ctrl+z:


https://github.com/user-attachments/assets/21a792d4-4bdf-4415-b235-fa1d9e795173

**Comment by blam23** [comment] 2024-09-06 17:12
The editor gets stuck in a loop here: 

https://github.com/godotengine/godot/blob/05d985496c73577fb0b44291345da5f2dbe09844/editor/history_dock.cpp#L184-L194

Because the undo fails, this loop never reaches it's exit condition.

Obviously this is a side effect of the point insertion not being properly tracked in the history, but there should also be a safeguard here (such as `if (!ur_manager->undo()) { report error and break }`) to prevent the editor freezing if there are ever any other similar bugs in the future

**Comment by matheusmdx** [comment] 2024-09-08 09:15
Tested on master v4.4.dev.custom_build [05d985496] and this issue is already fixed, probably is the same problem from #96081 and was fixed by #96237

**Comment by blam23** [comment] 2024-09-08 11:37
The underlying bug that broke the history is fixed, but I'd say it's still worth adding a check to stop the infinite loop (as per https://github.com/godotengine/godot/issues/96636#issuecomment-2334490172) and reporting an error if the `undo()` fails again in the future.

**Comment by matheusmdx** [comment] 2024-09-08 11:49
@blam23 I don't think this is necessary because even if you handle this error the UndoRedo will keep broken, also this bug wasn't caused by a edge case that could be valid in some circumstance.

**Comment by Proggle** [comment] 2024-11-23 08:16
> Ok, it crashes if you use the history sidebar, but not if you use ctrl+z:
> 
>  crash.mp4

I had a very similar issue that causes crashes if you press control + z ( https://github.com/godotengine/godot/issues/99578 ) .

**Comment by AThousandShips** [comment] 2024-11-23 14:00
Closing as per the above, if anyone can confirm this in [4.4.dev5](https://godotengine.org/article/dev-snapshot-godot-4-4-dev-5/) or later please comment and this can be reopened

**Closed by AThousandShips** 2024-11-23 14:00 UTC
Labels: bug, topic:editor, crash
