### ISSUE TITLE
Mac OS X, Cannot quit. Need to Force Quit

### ISSUE THREAD

**Issue by wyattbiker** [godotengine/godot#22172] opened 2018-09-16 22:22 UTC
**Godot version:**
3.1 alpha
Mac OS X, High Sierra

**Issue description:**
I click from both Mac Godot Menu and Scene Menu to quit. I get the prompt to confirm and click Quit. Nothing happens. I need to Force Quit.

Happens intermittently. No way to reproduce. I need to Force Quit Godot. Maybe there is a Log file someplace to explain what is happening.

**Comment by slapin** [comment] 2018-09-17 07:40
Same on Linux. Requires ^C in terminal to quit.

**Comment by capnm** [comment] 2018-09-18 13:37
I've seen this on Linux puppet leader f148e8eedeb1ff2dcf74d6843d1314d7c6db12a7

88              _logger->log_error(p_function, p_file, p_line, p_code, p_rationale, p_type);


Thread 1 "godot3" received signal SIGSEGV, Segmentation fault.
OS::print_error (this=0x0, p_function=0x5555587308e0 <SelfList<DynamicFont>::List::~List()::__FUNCTION__> "~List",
    p_file=0x555557cd61c5 "./core/self_list.h", p_line=111,
    p_code=0x555557cd5c38 "Condition ' _first != __null ' is true.", p_rationale=0x555557d29a38 "",
    p_type=Logger::ERR_ERROR) at core/os/os.cpp:88
88              _logger->log_error(p_function, p_file, p_line, p_code, p_rationale, p_type);
Continuing.

Thread 1 "godot3" received signal SIGSEGV, Segmentation fault.
OS::print_error (this=0x0, p_function=0x5555587308e0 <SelfList<DynamicFont>::List::~List()::__FUNCTION__> "~List",
    p_file=0x555557cd61c5 "./core/self_list.h", p_line=111,
    p_code=0x555557cd5c38 "Condition ' _first != __null ' is true.", p_rationale=0x555557d29a38 "",
    p_type=Logger::ERR_ERROR) at core/os/os.cpp:88
88              _logger->log_error(p_function, p_file, p_line, p_code, p_rationale, p_type);
Continuing.

Thread 1 "godot3" received signal SIGSEGV, Segmentation fault.
OS::print_error (**this=0x0**&#x1F34E;, p_function=0x5555587308e0 <SelfList<DynamicFont>::List::~List()::__FUNCTION__> "~List",
    p_file=0x555557cd61c5 "./core/self_list.h", p_line=111,
    p_code=0x555557cd5c38 "Condition ' _first != __null ' is true.", p_rationale=0x555557d29a38 "",
    p_type=Logger::ERR_ERROR) at core/os/os.cpp:88

**Comment by akien-mga** [comment] 2018-09-18 13:46
Might be a duplicate of #21060.

**Comment by capnm** [comment] 2018-09-18 15:42
Looks very similar. Here it enters an endless loop trying to log the error
`SelfList::List::~List()::FUNCTION> "~List"  Condition ' _first != __null ' is true.`
on a `_logger` that's already gone. Something like this fixes the endless loop:
```diff
diff --git a/core/os/os.cpp b/core/os/os.cpp
index 7547b6a04..633d172d9 100644
--- a/core/os/os.cpp
+++ b/core/os/os.cpp
@@ -85,7 +85,9 @@ void OS::add_logger(Logger *p_logger) {
 
 void OS::print_error(const char *p_function, const char *p_file, int p_line, const char *p_code, const char *p_rationale, Logger::ErrorType p_type) {
 
-       _logger->log_error(p_function, p_file, p_line, p_code, p_rationale, p_type);
+       if (_logger) {
+               _logger->log_error(p_function, p_file, p_line, p_code, p_rationale, p_type);
+       }
 }
 
 void OS::print(const char *p_format, ...) {
```

**Comment by akien-mga** [comment] 2018-09-23 13:14
Closing as duplicate of #18429.

**Closed by akien-mga** 2018-09-23 13:14 UTC
Labels: bug, topic:editor
