### ISSUE TITLE
"Alert! Could not start subprocess!"

### ISSUE THREAD

**Issue by Cobradabest** [godotengine/godot#33398] opened 2019-11-06 18:20 UTC
**Godot version:**
3.1.1 - Problem occurs in Regular, Steam and Itch binaries

**OS/device including version:**
Ubuntu 18.04 LTS

**Issue description:**
I get the following error when I try to test a project on Godot after I modify something:
https://i.imgur.com/kOT2oMF.png

**Steps to reproduce:**
Start Godot in Ubuntu 18.04, move the camera around, make a few changes, then try to run it.

Here's the terminal output when this happens:
`Running: /home/cobradabest/Downloads/Godot_v3.1.1-stable_x11.64 --path /media/cobradabest/1EA416F2A416CBE1/Users/Cobradabest/Documents/Pinkeye/project --remote-debug 127.0.0.1:6007 --allow_focus_steal_pid 20623 --position 448,240 res://levels/level2/level2.tscn
ERROR: execute: Condition ' pid < 0 ' is true. returned: ERR_CANT_FORK
   At: drivers/unix/os_unix.cpp:336.
ERROR: run: Condition ' err ' is true. returned: err
   At: editor/editor_run.cpp:189.
`

**Comment by theitsloth** [comment] 2020-01-07 16:28
I, too, am experiencing this, sometimes. I am using the version from steam on Ubuntu 18.04. It typically occurs after I wake up the machine from sleep mode.

**Comment by jjmontes** [comment] 2020-12-28 12:26
I have the same issue on Godot 3.2.2 downloaded from the website on Ubuntu 18.04.5 LTS

When i run some projects in terminal i see:

>  drivers/unix/os_unix.cpp:326 - Condition "pid < 0" is true. Returned: ERR_CANT_FORK
>  editor/editor_run.cpp:192 - Condition "err" is true. Returned: err

**Comment by Calinou** [comment] 2020-12-28 15:36
> ADD: This occurs when VirtualBox is running a virtual machine with 10 GB (Host has 16 GB)

Running Godot in non-headless mode in VirtualBox isn't officially supported.

**Comment by jjmontes** [comment] 2020-12-29 09:15
> > ADD: This occurs when VirtualBox is running a virtual machine with 10 GB (Host has 16 GB)
> 
> Running Godot in non-headless mode in VirtualBox isn't officially supported due to frequent bugs with graphics drivers – VirtualBox's 3D acceleration isn't actively maintained.

I am not running Godot inside a VirtualBox, the problem occurs when running Godot at the same time as VirtualBox. It occurs to me that the problem occurs due to a RAM memory limit, since the Godot project that I run when it fails is heavy and the virtual machine that I run at that time occupies 10 GB of RAM

**Comment by Calinou** [comment] 2020-12-29 10:43
> I am not running Godot inside a VirtualBox, the problem occurs when running Godot at the same time as VirtualBox. It occurs to me that the problem occurs due to a RAM memory limit, since the Godot project that I run when it fails is heavy and the virtual machine that I run at that time occupies 10 GB of RAM

I think it's kind of expected in this case. By default, Linux doesn't have good memory management in low-memory situations; it's why third-party daemons such as EarlyOOM were created. They've only been enabled by default in Linux distributions since very recently, and Ubuntu 18.04 does not come with such a daemon enabled by default.

**Comment by jjmontes** [comment] 2020-12-29 12:28
> I think it's kind of expected in this case. By default, Linux doesn't have good memory management in low-memory situations. It's why third-party daemons such as EarlyOOM were created. They've only been enabled by default in Linux distributions since very recently, and Ubuntu 18.04 does not come with such a daemon enabled by default.

**GOOGLE TRANSLATE**:
I completely agree, it is expected.
I was only clarifying it because I noticed that this occurred under this situation ... if you notice, the incidents reported by @Cobradabest and @lbfalvy report using Ubuntu 18.04. Maybe they (along with @hsandt) also have little memory available to run the project and the error is that.

In this case, if the problem could be detected as being out of memory and reporting an error message that says something like "Out of memory", an error would no longer be reported, because it would be something easy to understand.

---------------------------------------------------

**ESPAÑOL ORIGINAL**:
Estoy completamente de acuerdo, es algo esperado.
Solo lo aclaraba porque noté que esto ocurría bajo esta situación... si te fijás, los incidentes reportados por @Cobradabest y @lbfalvy informan que usan Ubuntu 18.04. Quizás ellos (junto con @hsandt) también tienen poca memoria disponible para ejecutar el proyecto y el error es ese.

En este caso, si se pudiera detectar que el problema es la falta de memoria e informar con un mensaje de error que diga algo como "Memoria insuficiente" ya no se reportaría un error, porque sería algo fácil de entender.

**Comment by Calinou** [comment] 2020-12-29 18:32
> In this case, if the problem could be detected as being out of memory and reporting an error message that says something like "Out of memory", an error would no longer be reported, because it would be something easy to understand.

I'm not sure if Linux will even signal you that in a nice way to catch it from the application.

**Comment by Calinou** [comment] 2022-11-04 21:42
@Cobradabest @lbfalvy @hsandt @jjmontes Can you (or anyone else) still reproduce this bug in [Godot 3.5.1](https://godotengine.org/article/maintenance-release-godot-3-5-1) or any later release?

If yes, please ensure that an up-to-date Minimal Reproduction Project (MRP) is included in this report (a MRP is a zipped Godot project with the minimal elements necessary to reliably trigger the bug). You can upload ZIP files in an issue comment with a drag and drop.

**Comment by hsandt** [comment] 2022-11-13 16:47
Could not repro in v3.4.1 even when Steam is open and running from the terminal until a project is open.

**Comment by Calinou** [comment] 2022-11-25 19:15
Closing per @hsandt's comment.

**Closed by Calinou** 2022-11-25 19:15 UTC
Labels: bug, platform:linuxbsd, topic:editor, needs testing

**Comment by ahmedosama94** [comment] 2024-08-18 23:50
Happened again on Godot Engine v4.3.stable.official [77dcf97d8].

However, simply restarting Godot fixed it.
