### ISSUE TITLE
SubViewportContainer devouring click events

### ISSUE THREAD

**Issue by aiaimimi0920** [godotengine/godot#94754] opened 2024-07-25 19:46 UTC
### Tested versions

- Godot v4.3.rc1

### System information

Godot v4.3.rc1 - Windows 10.0.22631 - GLES3 (Compatibility) - NVIDIA GeForce RTX 2080 Ti (NVIDIA; 31.0.15.4633) - 12th Gen Intel(R) Core(TM) i5-12400F (12 Threads)

### Issue description

When the subviewports in the SubViewportContainer do not handle input events, I hope the input events can continue to propagate to other nodes in the node tree.

The current version of SubViewportContainer will consume all input events within the region

### Steps to reproduce

![image](https://github.com/user-attachments/assets/e4c694be-ec7c-4a05-8743-c209da3ad892)

When you click on the left half of button2, button2 cannot accept click events because the input event are consumed by SubViewportContainer1.

When you click on the right half of button2, the button can be clicked because this area is not within the range of SubViewportContainer1.

https://github.com/user-attachments/assets/b622a23c-3eff-4b49-8b23-036b12de9cd0

### Minimal reproduction project (MRP)

[subviewportcontainer.zip](https://github.com/user-attachments/files/16383033/subviewportcontainer.zip)

**Comment by AThousandShips** [comment] 2024-07-26 14:37
Sounds like:
* https://github.com/godotengine/godot/issues/93272

**Comment by aiaimimi0920** [comment] 2024-07-26 19:44
Thank you for your help, it is indeed because of this issue #93272

If the current behavior is expected, what can I do to achieve my goal? I hope that when events are not processed inside the SubViewportContainer, they will continue to pass through the node tree

**Comment by AThousandShips** [comment] 2024-07-27 08:43
Closing as a duplicate of that issue, see there for more details, specifically https://github.com/godotengine/godot/issues/55432

**Closed by AThousandShips** 2024-07-27 08:43 UTC
Labels: needs testing, topic:input
