### ISSUE TITLE
Label moving around on window resize

### ISSUE THREAD

**Issue by graydwarf** [godotengine/godot#46562] opened 2021-03-01 15:04 UTC
Didn't see an existing issue but I'm also pretty new to godot so I may not be looking for the right thing.

Project Settings -> General -> Display -> Window
Mode: 2d
Aspect: keep_width

**Godot version:**
v3.2.3.stable.official

**OS/device including version:**
Windows 10 Pro - Version	10.0.18363 Build 18363

**Issue description:**
Label moves around on screen when the window is resized. 

**Steps to reproduce:**
- Create new 2d project
- Project Settings -> General -> Display -> Window
  - Width: 576
  - Height: 800
  - Mode: 2d
  - Aspect: keep_width
- Add Node2d as root
- Add Label as child node
- Update Label Properties:
  - Text: 000
  - Align: Center
  - Font: Use Dynamic Kenney Future Narrow.ttf set Size to 32.
- Run the game
- Resize by grabbing the bottom of the window and collapsing the window height to 0 and repeat in an up and down motion a few times to ensure repro. Effectively scaling the label to a height of 0.

Expected:
- The label should scale up and down but it should not move at any point.

Actual:
- The label works its way to the the right typically and eventually off screen. Depending on font size or slight scenario differences, you might see it jump around and back to it's original position if you keep resizing.

**Minimal reproduction project:**
[bug.zip](https://github.com/godotengine/godot/files/6062503/bug.zip)

**Available on the godot discord:**
Video Repro: https://discordapp.com/channels/212250894228652034/610347507222052867/815951859415384064

**Side Notes:**
- Changing the font may result in no repro (someone found)
- Changing the alignment to left or fill will not repro.
- Changing the mode or aspect may also prevent repro.
- Several other people were able to repro with the project I provided.

**Comment by josuraki** [comment] 2021-03-02 11:21
Can reproduce on linux with your repro project
on multiple aspects and on alignment "right" as well

your video link is not publicly accessible btw.

**Comment by graydwarf** [comment] 2021-03-02 13:09
> Can reproduce on linux with your repro project
> on multiple aspects and on alignment "right" as well
> 
> your video link is not publicly accessible btw. (you can drag and drop the actual videofile into your post)

I tried to attach the video but it was too large even though it's only a few mb. It's on the godot discord though.

**Comment by Calinou** [comment] 2021-03-02 13:51
Duplicate of https://github.com/godotengine/godot/issues/42257 (same cause).

**Closed by Calinou** 2021-03-02 13:51 UTC

**Comment by graydwarf** [comment] 2021-03-03 12:18
Disabling 'Use Oversampling' seems to fix the issue. Thanks.
