### ISSUE TITLE
Bug with Find and Replace script editor tools

### ISSUE THREAD

**Issue by vonflyhighace2** [godotengine/godot#6471] opened 2016-09-13 01:06 UTC
**Operating system or device - Godot version:**
Windows 10 pro x64. 
Godot 2.1 stable

**Issue description** (what happened, and what was expected):
pasting text into the 'Find' and or 'Replace' feature in the script editor does not yield a search for the required field. 

**Steps to reproduce:**
have a script with a word or phrase you wish to find or replace. paste, not type, the word or phrase into the context field.

**Link to minimal example project** (optional but very welcome):

**Comment by gau-veldt** [comment] 2016-09-15 17:41
Not sure if this is separate issue but I get a bug where there's two search menus?!?!?
(see the screenshot).  Vanilla 2.2a editor,no plugins.
![screenshot](https://cloud.githubusercontent.com/assets/1862162/18560284/c972dca4-7b2f-11e6-87c7-c302ffd65ccc.png)

**Comment by neikeq** [comment] 2016-09-15 18:10
This is weird. Doesn't paste emits `text_changed`? Any way, I am going to check it this week.

@gau-veldt I don't think the issues are related.

**Comment by bojidar-bg** [comment] 2017-02-15 07:40
Ping-pong. Has anything changed about this issue on master?

**Comment by Faless** [comment] 2017-02-15 12:18
> Ping-pong. Has anything changed about this issue on master?

I can't seem to reproduce any longer neither on master nor on 2.1.3 . I think this was caused by #6505 and fixed with it.

There is another bug causing two scripts to be closed at once instead of one when pressing `ctrl+w`. I'm looking if there is another issue for it, I'll open a new one otherwise.

**Comment by bojidar-bg** [comment] 2017-02-15 13:53
> There is another bug causing two scripts to be closed at once instead of one when pressing ctrl+w. I'm looking if there is another issue for it, I'll open a new one otherwise.

-- Totally offtopic, yet I can confirm :wink:

Anyway, closing as fixed, notify us if it isn't (so it can be reopened).

**Closed by bojidar-bg** 2017-02-15 13:53 UTC
Labels: bug, junior job, topic:editor
