### ISSUE TITLE
i faced issue when build windows export template on linux mint 18

### ISSUE THREAD

**Issue by ahmedyounis75** [godotengine/godot#21901] opened 2018-09-09 16:29 UTC
i get this errors - im search more to solve my export issue for windows and android 
but i want to solve export to windows first
my godot version is 3.1
---------------------------------------------------------------
~/godot.3.1 $ scons p=windows -j 8
scons: Reading SConscript files ...
Configuring for Windows: target=debug, bits=default
Using Mingw
YASM is necessary for WebM SIMD optimizations.
WebM SIMD optimizations are disabled. Check if your CPU architecture, CPU bits or platform are supported!
Checking for C header file mntent.h... (cached) no
scons: done reading SConscript files.
scons: Building targets ...
[ 19%] Compiling ==> thirdparty/etc2comp/EtcImage.cpp
[ 21%] Compiling ==> modules/gdnative/net/register_types.cpp
[ 21%] Compiling ==> modules/gdnative/arvr/arvr_interface_gdnative.cpp
[ 21%] Compiling ==> modules/gdnative/arvr/register_types.cpp
[ 21%] Compiling ==> modules/gdnative/pluginscript/pluginscript_loader.cpp
[ 21%] Compiling ==> modules/gdnative/pluginscript/pluginscript_language.cpp
[ 21%] Compiling ==> modules/gdnative/pluginscript/pluginscript_script.cpp
[ 21%] Compiling ==> modules/gdnative/pluginscript/pluginscript_instance.cpp
[ 21%] Compiling ==> modules/gdnative/pluginscript/register_types.cpp
[ 21%] Compiling ==> modules/gdnative/gdnative_api_struct.gen.cpp
[ 21%] Compiling ==> modules/gdscript/gdscript_compiler.cpp
[ 21%] Compiling ==> modules/gdscript/gdscript_parser.cpp
[ 21%] Compiling ==> modules/gdscript/gdscript_tokenizer.cpp
[ 21%] Compiling ==> modules/gdscript/gdscript_function.cpp
[ 21%] Compiling ==> modules/gdscript/gdscript_editor.cpp
[ 21%] Compiling ==> modules/gdscript/gdscript_functions.cpp
[ 21%] Compiling ==> modules/gdscript/gdscript.cpp
[ 21%] Compiling ==> modules/gdscript/register_types.cpp
[ 21%] Compiling ==> modules/gdscript/editor/gdscript_highlighter.cpp
thirdparty/etc2comp/EtcImage.cpp: In member function 'Etc::Image::EncodingStatus Etc::Image::Encode(Etc::Image::Format, Etc::ErrorMetric, float, unsigned int, unsigned int)':
thirdparty/etc2comp/EtcImage.cpp:259:64: error: invalid use of incomplete type 'class std::future<void>'
   std::future<void> *handle = new std::future<void>[a_uiMaxJobs];
                                                                ^
In file included from thirdparty/etc2comp/EtcImage.cpp:40:0:
/usr/lib/gcc/x86_64-w64-mingw32/6.3-win32/include/c++/future:115:11: note: declaration of 'class std::future<void>'
     class future;
           ^~~~~~
thirdparty/etc2comp/EtcImage.cpp:268:12: error: invalid use of incomplete type 'class std::future<void>'
    handle[i] = async(std::launch::async, &Image::RunFirstPass, this, i, uiNumThreadsNeeded);
            ^
In file included from thirdparty/etc2comp/EtcImage.cpp:40:0:
/usr/lib/gcc/x86_64-w64-mingw32/6.3-win32/include/c++/future:115:11: note: declaration of 'class std::future<void>'
     class future;
           ^~~~~~
thirdparty/etc2comp/EtcImage.cpp:268:91: error: invalid use of incomplete type 'class std::future<void>'
 = async(std::launch::async, &Image::RunFirstPass, this, i, uiNumThreadsNeeded);
                                                                              ^
In file included from thirdparty/etc2comp/EtcImage.cpp:40:0:
/usr/lib/gcc/x86_64-w64-mingw32/6.3-win32/include/c++/future:115:11: note: declaration of 'class std::future<void>'
     class future;
           ^~~~~~
thirdparty/etc2comp/EtcImage.cpp:275:12: error: invalid use of incomplete type 'class std::future<void>'
    handle[i].get();
            ^
In file included from thirdparty/etc2comp/EtcImage.cpp:40:0:
/usr/lib/gcc/x86_64-w64-mingw32/6.3-win32/include/c++/future:115:11: note: declaration of 'class std::future<void>'
     class future;
           ^~~~~~
thirdparty/etc2comp/EtcImage.cpp:275:13: error: invalid use of incomplete type 'class std::future<void>'
    handle[i].get();
             ^
In file included from thirdparty/etc2comp/EtcImage.cpp:40:0:
/usr/lib/gcc/x86_64-w64-mingw32/6.3-win32/include/c++/future:115:11: note: declaration of 'class std::future<void>'
     class future;
           ^~~~~~
thirdparty/etc2comp/EtcImage.cpp:330:107: error: invalid use of incomplete type 'class std::future<unsigned int>'
 > *handleToBlockEncoders = new std::future<unsigned int>[uiNumThreadsNeeded-1];
                                                                              ^
In file included from thirdparty/etc2comp/EtcImage.cpp:40:0:
/usr/lib/gcc/x86_64-w64-mingw32/6.3-win32/include/c++/future:115:11: note: declaration of 'class std::future<unsigned int>'
     class future;
           ^~~~~~
thirdparty/etc2comp/EtcImage.cpp:334:30: error: invalid use of incomplete type 'class std::future<unsigned int>'
       handleToBlockEncoders[i] = async(std::launch::async, &Image::IterateThroughWorstBlocks, this, blocksToIterateThisPass, i, uiNumThreadsNeeded);
                              ^
In file included from thirdparty/etc2comp/EtcImage.cpp:40:0:
/usr/lib/gcc/x86_64-w64-mingw32/6.3-win32/include/c++/future:115:11: note: declaration of 'class std::future<unsigned int>'
     class future;
           ^~~~~~
thirdparty/etc2comp/EtcImage.cpp:334:147: error: invalid use of incomplete type 'class std::future<unsigned int>'
 erateThroughWorstBlocks, this, blocksToIterateThisPass, i, uiNumThreadsNeeded);
                                                                              ^
In file included from thirdparty/etc2comp/EtcImage.cpp:40:0:
/usr/lib/gcc/x86_64-w64-mingw32/6.3-win32/include/c++/future:115:11: note: declaration of 'class std::future<unsigned int>'
     class future;
           ^~~~~~
thirdparty/etc2comp/EtcImage.cpp:340:50: error: invalid use of incomplete type 'class std::future<unsigned int>'
       uiIteratedBlocks += handleToBlockEncoders[i].get();
                                                  ^
In file included from thirdparty/etc2comp/EtcImage.cpp:40:0:
/usr/lib/gcc/x86_64-w64-mingw32/6.3-win32/include/c++/future:115:11: note: declaration of 'class std::future<unsigned int>'
     class future;
           ^~~~~~
thirdparty/etc2comp/EtcImage.cpp:340:51: error: invalid use of incomplete type 'class std::future<unsigned int>'
       uiIteratedBlocks += handleToBlockEncoders[i].get();
                                                   ^
In file included from thirdparty/etc2comp/EtcImage.cpp:40:0:
/usr/lib/gcc/x86_64-w64-mingw32/6.3-win32/include/c++/future:115:11: note: declaration of 'class std::future<unsigned int>'
     class future;
           ^~~~~~
thirdparty/etc2comp/EtcImage.cpp:356:12: error: invalid use of incomplete type 'class std::future<void>'
    handle[i] = async(std::launch::async, &Image::SetEncodingBits, this, i, a_uiJobs);
            ^
In file included from thirdparty/etc2comp/EtcImage.cpp:40:0:
/usr/lib/gcc/x86_64-w64-mingw32/6.3-win32/include/c++/future:115:11: note: declaration of 'class std::future<void>'
     class future;
           ^~~~~~
thirdparty/etc2comp/EtcImage.cpp:356:84: error: invalid use of incomplete type 'class std::future<void>'
 dle[i] = async(std::launch::async, &Image::SetEncodingBits, this, i, a_uiJobs);
                                                                              ^
In file included from thirdparty/etc2comp/EtcImage.cpp:40:0:
/usr/lib/gcc/x86_64-w64-mingw32/6.3-win32/include/c++/future:115:11: note: declaration of 'class std::future<void>'
     class future;
           ^~~~~~
thirdparty/etc2comp/EtcImage.cpp:362:12: error: invalid use of incomplete type 'class std::future<void>'
    handle[i].get();
            ^
In file included from thirdparty/etc2comp/EtcImage.cpp:40:0:
/usr/lib/gcc/x86_64-w64-mingw32/6.3-win32/include/c++/future:115:11: note: declaration of 'class std::future<void>'
     class future;
           ^~~~~~
thirdparty/etc2comp/EtcImage.cpp:362:13: error: invalid use of incomplete type 'class std::future<void>'
    handle[i].get();
             ^
In file included from thirdparty/etc2comp/EtcImage.cpp:40:0:
/usr/lib/gcc/x86_64-w64-mingw32/6.3-win32/include/c++/future:115:11: note: declaration of 'class std::future<void>'
     class future;
           ^~~~~~
[ 22%] scons: *** [thirdparty/etc2comp/EtcImage.windows.tools.64.o] Error 1
Compiling ==> modules/gridmap/grid_map.cpp
scons: building terminated because of errors.
---------------------------------------------------------------

thanks in advance

**Comment by bruvzg** [comment] 2018-09-09 16:39
Duplicate of #20405, #12417 and #9258, make sure your MinGW installation is using posix threads (check [compiling_for_windows.html#troubleshooting](https://godot.readthedocs.io/en/latest/development/compiling/compiling_for_windows.html#troubleshooting) for instructions).

**Closed** 2018-09-10 21:27 UTC
Labels: archived
