### ISSUE TITLE
Native mobile VR: Procedural sky sphere rendered incorrectly

### ISSUE THREAD

**Issue by tcrass** [godotengine/godot#28378] opened 2019-04-24 07:51 UTC
**Godot version:**
Official 3.1.1-RC1

**OS/device including version:**

- Development:
  - Hardware: OpenGL ES 2.0 Renderer: Gallium 0.4 on AMD POLARIS11 (DRM 3.27.0 / 4.19.0-0.bpo.2-amd64, LLVM 3.9.1)
  - OS: Debian Stretch
  - uname -a: Linux caladan 4.19.0-0.bpo.2-amd64 #1 SMP Debian 4.19.16-1~bpo9+1 (2019-02-07) x86_64 GNU/Linux

- Deployment: 
  - Hardware: Samsung Galaxy S9
  - OS: LineageOS 15.1 (= Android 8.1)

**Issue description:**
When deploying the attached test project to my Android device, the procedureale sky doesn't get rendered correctly, in spite of https://docs.godotengine.org/en/3.1/tutorials/misc/gles2_gles3_differences.html explicitly saying "[...] in GLES2 environments you can only set:    Sky (_including procedural sky_) [...]"
- GLES2: There's no gradient visible on the sky sphere; rather, when looking above the horizon, the sky gets rendered as uniform blue and when looking down it suddenly switches to being completely gray.
- GLES3: The sky looks just blue, no matter where I look.

**Steps to reproduce:**
Deploy the attached test project to an Android device and see for yourself.

**Minimal reproduction project:**
[vrtest.zip](https://github.com/godotengine/godot/files/3111159/vrtest.zip)

**Comment by groud** [comment] 2019-04-24 11:25
Duplicate of #27335

**Closed by groud** 2019-04-24 11:25 UTC
