### ISSUE TITLE
Low processor mode causes extreme screen flickering and glitching on Android

### ISSUE THREAD

**Issue by PonasKovas** [godotengine/godot#30417] opened 2019-07-07 20:12 UTC
**Godot version:**
3.1.1 Stable

**Issue description:**
When Low Processor mode is enabled, and I launch my game on Android, everything starts flickering and glitching, the game is unplayable.

**Comment by Calinou** [comment] 2019-07-07 20:45
While this should be fixed, note that low-processor usage mode isn't meant to be used in games as stated in the [ProjectSettings class documentation](https://docs.godotengine.org/en/latest/classes/class_projectsettings.html#class-projectsettings-property-application-run-low-processor-mode).

**Comment by Ramh5** [comment] 2020-03-13 07:12
I have this problem as well, it does not seem fixed. It works flawlessly on Windows but not on mobile. I read the project settings class documentation you linked and I understand that it is not intended for mobile unfortunately. But it does not mention it in the [OS documentation](http://docs.godotengine.org/en/stable/classes/class_os.html#class-os-property-low-processor-usage-mode). It is unfortunate because I am making a strategy game with lots of idle screen time while the player is just looking at the screen and this option works perfectly on windows.

**Comment by Calinou** [comment] 2020-03-13 08:33
@Ramh5 I'd open a pull request to change its documentation, but since the method isn't even implemented in the current `master` branch due to the Vulkan rewrite, it would have to be different between the `3.2` and `master` branches.

**Comment by Calinou** [comment] 2020-08-02 20:06
Duplicate of #19304.

**Closed by Calinou** 2020-08-02 20:06 UTC
Labels: bug, confirmed, platform:android, topic:porting, topic:rendering
