### ISSUE TITLE
Godot completely hangs when 

### ISSUE THREAD

**Issue by Ovnuniarchos** [godotengine/godot#41863] opened 2020-09-07 19:56 UTC
**Godot version:**
5c879e6d7daf6028669998d76057d3704a7f14c8

**OS/device including version:**
Debian SID

**Issue description:**
When interacting with any dropdown or text field **in the editor**, Godot freezes, and makes the X server very unresponsive.
This does not happen while in the project manager.
Running Godot with -v does not show any error message, just the usual ones about window creation.

**Steps to reproduce:**
Create a blank project.
Try to use any dropdown, or create a node and try to edit any parameter.

**Comment by Calinou** [comment] 2020-09-07 20:01
Which graphics card model and driver are you using? There's a known regression with the NVIDIA 450.66 drivers which causes system freezes when using Godot's `master` branch (I can reproduce it too).

**Comment by Ovnuniarchos** [comment] 2020-09-08 18:05
Nvidia Gt750ti. Drivers are (IIRC) 450.66.

Welp. Seems I'll have to wait until next driver version.

**Comment by Calinou** [comment] 2020-09-08 18:16
Duplicate of https://github.com/godotengine/godot/issues/41574.

**Closed by Calinou** 2020-09-08 18:16 UTC
Labels: bug, platform:linuxbsd, topic:editor
