### ISSUE TITLE
Runtime generated shapes in Area2D won't overlap or enter.

### ISSUE THREAD

**Issue by slapslash** [godotengine/godot#3685] opened 2016-02-12 10:21 UTC
Somehow, an Area2D won't recognize other Area2D that get their shapes during runtime.
I've added an example (godot 2.0 rc1) with different tries to get it work.

[area_collision_shapes_test.zip](https://github.com/godotengine/godot/files/127796/area_collision_shapes_test.zip)

**Comment by argent0** [comment] 2017-08-01 22:51
This is still present in: 2.1.3:

Script for an Area2D scene:

```{gdscript}
extends Area2D

func _ready():
	var area2d = Area2D.new()
	var collision_shape = CollisionShape2D.new()
	var circle_shape = CircleShape2D.new()
	circle_shape.set_radius(4)
	collision_shape.set_shape(circle_shape)
	area2d.add_child(collision_shape)
	add_child(area2d)
	var oa = get_overlapping_areas()
	assert(oa.size() == 1) #fails
```

**Comment by eon-s** [comment] 2017-08-02 02:16
@argent0 I don't think "get_overlapping_areas" will give you any reliable output before a physics frame (and outside fixed process).
Also that code is not adding the shape to the Area, just the helper child (you need to add_shape the circle).
For overpapping tests on creation, Physics2DDirectSpaceState and Shape api have a couple of methods.

------------------

The OP example has some issues, like trying to detect overlapping areas in the same frame as they were added (not processed yet) and adding a CollisionShape without adding a shape (I think this works on Godot 3). 
The enter signal works and is the best way to work with areas (if there is no problem to wait a few frames).

**Comment by argent0** [comment] 2017-08-02 18:08
@eon-s Thanks for the answer. Does `get_overlapping_areas` only work reliably inside fiexd process? If so, I think it should be clarified in the (docs)[http://docs.godotengine.org/en/stable/classes/class_area2d.html#class-area2d-get-overlapping-areas]. Along with functions that work that in the same fashion.

**Comment by eon-s** [comment] 2017-08-02 23:16
@argent0 Since all CollisionObjects are managed by the physics server, changes on areas will be updated on next physics frame. 

The same happens with RayCast2D but that class has a "force update" that can update state on same frame, could be nice to have something like that on areas too.

**Comment by RandomShaper** [comment] 2017-08-03 07:42
Disclaimer: just a raw idea.

It may be possible to call some method(s) from the `PhysicsServer` to make it process a step.

If anything, that actually defeats the purpose of having separate fixed and idle realms. When dealing with physics it's probably best to stick to the fixed frame logic.

What is your exact use case for having to check area overlapping from idle time?

**Comment by KoBeWi** [comment] 2019-06-26 14:13
I tested it in 3.1.
For whatever reason, `get_overlapping_areas()` doesn't report the runtime-added shape inside `_process`. Like, not at all, even when ran each frame. Moving it to `_physics_process` solves the problem (almost) completely. Almost, because it's still not reported immediately after adding the shape.

Maybe this should just be documented.

**Comment by eon-s** [comment] 2019-06-26 17:35
Probably needs to wait for a fixed frame for the update to take place, again, manually forcing update like raycast may solve the problem.

An extra flag for CollisionObjects for update on ready/enter tree can be another option.

**Comment by akien-mga** [comment] 2020-01-16 22:04
Is this still reproducible in the current master branch?

**Comment by eon-s** [comment] 2020-01-17 02:21
Yes, but this is probably the expected behavior, unless there is a way to force physics updates on special situations like with raycasts.

**Comment by KoBeWi** [comment] 2020-12-19 10:14
Still valid in 3.2.4 beta4

Here's a repro for 3.x
[area_collision_shapes_test.zip](https://github.com/godotengine/godot/files/5719182/area_collision_shapes_test.zip)

**Comment by Anutrix** [comment] 2023-10-01 04:53
What about 4.x? I tried to convert that 3.x project but it just broke partially.

**Comment by Patchcoat** [comment] 2023-10-29 23:32
I think I know why the generated shape isn't colliding in the 4.2 example project.

![image](https://github.com/godotengine/godot/assets/5828713/983f34e5-ba24-4646-bbbe-05ea71332689)

I change set_a vector to (0, 0) so it intersects the circle and said disk starts detecting collisions with the generated shape.

**Comment by KoBeWi** [comment] 2024-03-20 23:05
Yep, seems fixed.

**Closed by KoBeWi** 2024-03-20 23:05 UTC
Labels: bug, topic:core, confirmed
