### ISSUE TITLE
Cannot open project in Windows 11

### ISSUE THREAD

**Issue by Dustray** [godotengine/godot#54693] opened 2021-11-07 02:36 UTC
### Godot version

from Godot_v3.3.3-stable_mono_win64 TO v3.4stable

### System information

Windows 11 Enterprise Release Latest(22000.282)

### Issue description

Godot flashback  when I double click to open project or create a new project in Project Manager. Last normal use was a few days ago, also win11. But I try the v3.4 today, all version doesn't work.

### Steps to reproduce

1. donwload v3.4 Godot and unzip;
2. just cover the v3.3.4 Godot;
3. then it happened, and I deleted all files and reunzip, still...

**Comment by robpc** [comment] 2021-11-07 04:14
I'm having a similar issue too. It opens the launcher just fine, but when I click on any project it exists immediately. No logs in `%HOME%/AppData/Roaming/Godot` or anything else I can find. Oddly it works fine from the command line. I go to the project directly and do 
```
'D:\Program Files (x86)\Godot\Godot_v3.4-stable_win64.exe' .\project.godot
```
And it loads with no errors. 

A second odd observation. I had tried 3.4 rc2 when it was new and had not seen this issue. I just tried it again and it has the same issue now. I am wondering if that means it is something in a Windows update that's changed.

Previous version that is working for me is 3.3.2. I have not tried 3.3.3 yet.

**Comment by robpc** [comment] 2021-11-07 04:33
I tried 3.3.3, 3.3.4 and then being suspicious tried 3.3.2 again... They all have the issue now, so definitely feels like an Windows update or something like that. I tried restarting and then updating to the latest windows update and no change.

**Comment by Chaosus** [comment] 2021-11-07 07:13
It may be a duplicate of https://github.com/godotengine/godot/issues/54076, try changing default terminal application settings.

**Comment by Dustray** [comment] 2021-11-07 09:46
> It may be for the same reason as in #54076, try changing default terminal application settings.

Yeah it is, think you.

**Comment by akien-mga** [comment] 2021-11-07 09:53
Duplicate of #54076

**Closed by akien-mga** 2021-11-07 09:53 UTC
Labels: bug, platform:windows, topic:porting
