### ISSUE TITLE
`FileSystem->New Scene...` doesn't create a new scene

### ISSUE THREAD

**Issue by LightningAA** [godotengine/godot#49478] opened 2021-06-10 04:06 UTC
### Godot version

3.3.2

### System information

Windows 10

### Issue description

In the Editor, the `FileSystem->New Scene...` dialog just opens a new empty tab in the scenes tabs. The dialog should probably just be removed since I think it's redundant.

### Steps to reproduce

See above.

**Comment by LightningAA** [comment] 2021-06-10 04:12
Never mind, apparently it does work, but the FileSystem dock doesn't update to show the new scene until you save the scene, and the tab still calls it `[empty]` until you save.

**Comment by timothyqiu** [comment] 2021-06-10 07:47
There is no scene created on the disk so FileSystem dock has nothing to update. The name is automatically used when that empty scene is used. See #34524.

**Comment by pycbouh** [comment] 2021-06-10 08:40
It would be possible to create a scene as soon as you confirm on the create dialog if https://github.com/godotengine/godot-proposals/issues/679 is implemented.

**Comment by KoBeWi** [comment] 2021-06-10 10:25
Closing as duplicate of #34524

**Closed by KoBeWi** 2021-06-10 10:25 UTC

**Comment by LightningAA** [comment] 2021-06-10 15:13
Thanks, I did search for duplicates but couldn't easily find any.
