### ISSUE TITLE
Some containers resets input of Labels to zero in the inspector

### ISSUE THREAD

**Issue by Chaosus** [godotengine/godot#19349] opened 2018-06-03 20:40 UTC
**Godot version:**
2a9253a

**OS/device including version:**
Win10

**Issue description:**
Thats really irritating bug I found in Godot. It resets input focus to zero every time you press new symbol to inspector Label text property

**Steps to reproduce:**
-Create scene with Node as root
-Add VContainer, HBoxContainer or GridContainer
-Add Label to this container and try modify its Text value - it will resets to zero every time you input character and you need to manual focus it to the end..

![image](https://user-images.githubusercontent.com/3036176/40891007-646015f2-6787-11e8-84a8-99f00719467e.png)

**Minimal reproduction project:**
[Bug.zip](https://github.com/godotengine/godot/files/2066328/Bug.zip)
note - I've added HBox/VBox/Grid(bad behavior) and simple Container(good behavior) as reference

sorry if this issue is already well known..

**Comment by vnen** [comment] 2018-06-03 22:35
Duplicate of #19008

**Closed by vnen** 2018-06-03 22:35 UTC
