### ISSUE TITLE
SkeletonIK3D "play IK" doesn't stay in played state when selecting other nodes

### ISSUE THREAD

**Issue by Maveyyl** [godotengine/godot#78491] opened 2023-06-20 21:50 UTC
### Godot version

4.1-beta2_mono_win64

### System information

Windows 11

### Issue description

I expect that I can play an IK and move the target around to see how the bones behave.

However when I click the button "play IK" when SkeletonIK3D is selected, and then click on the target to move it, the IK doesn't play anymore.

I'm not sure if this is the normal behavior or not. But I saw in videos that in 4.0 when Skeleton node was in charge of IKs it'd work in real time.

### Steps to reproduce

N/A

### Minimal reproduction project

N/A

**Comment by bitsawer** [comment] 2023-06-20 21:54
Looks like a duplicate of https://github.com/godotengine/godot/issues/72945

**Comment by Maveyyl** [comment] 2023-06-20 21:57
Indeed, my apologies. Worst part is I searched and found that thread but saw 4.0-rc1 and thought it was too early for SkeletonIK3D to be implemented.

**Closed** 2023-06-20 22:39 UTC

**Comment by Wallaguiar** [comment] 2024-03-08 00:30
SkeletonIK3D "play IK" doesn't stay in played state when selecting other nodes, 
![Captura de Tela (2769)](https://github.com/godotengine/godot/assets/145673147/50fa3fed-13f3-4600-8b10-5928dd42284a)
![Captura de Tela (2770)](https://github.com/godotengine/godot/assets/145673147/573f64f6-9fa4-4e4c-aafc-b042bbeebb12)
![Captura de Tela (2772)](https://github.com/godotengine/godot/assets/145673147/b147dc9d-46c4-407f-9aae-01a8d35082fe)
