### ISSUE TITLE
ViewportTexture doesn't work within PointLight2D

### ISSUE THREAD

**Issue by conradhappeliv** [godotengine/godot#75868] opened 2023-04-09 19:45 UTC
### Godot version

v4.1.dev.custom_build [c1128e911]

### System information

Windows 11, Nvidia 3070, any renderer

### Issue description

I want to use a ViewportTexture as a PointLight2D's [texture](https://docs.godotengine.org/en/stable/classes/class_pointlight2d.html#class-pointlight2d-property-texture), so I can create dynamic lights, but in most scenarios, the texture won't show at all.

Scenario 1: immediately after ViewportTexture added as PointLight2D texture (works fine in editor)

![image](https://user-images.githubusercontent.com/4420888/230793225-6b9ac440-ae4e-4b3f-b3bf-88c9f39903ca.png)

Scenario 2: project reloaded (light texture disappears)

![image](https://user-images.githubusercontent.com/4420888/230793242-e2237482-858b-43bc-bc6d-8b3d16e2964b.png)

Scenario 3: in-game (no light texture shown)

![image](https://user-images.githubusercontent.com/4420888/230793256-c0740e5c-69cd-4d3e-afe8-8dc6d08dd2f8.png)

### Steps to reproduce

1. Create a SubViewport with anything in it (e.g. a simple Sprite2D)
2. Create a PointLight2D
3. Add a ViewportTexture (referencing the SubViewport created in step 1) as the PointLight2D's texture
4. Try running the game (nothing shows for the light)
5. (optional) try adding an identical ViewportTexture as a texture on another node (e.g. Sprite2D) - it works fine.

### Minimal reproduction project

[viewportlight2d.zip](https://github.com/godotengine/godot/files/11186180/viewportlight2d.zip)

**Comment by clayjohn** [comment] 2023-04-11 18:30
This is the same core issue as https://github.com/godotengine/godot/issues/74352 https://github.com/godotengine/godot/issues/73400

PointLight2D copies texture to an atlas so that multiple lights can be used within the same draw call. The downside is that updating the textures requires a copy to the atlas each time the texture is updated. We avoided implementing that as it would be really bad for performance in most cases, but from the other issues you can see that it is very demanded. So we may have to support updating PointLight2D textures dynamically eventually and let users decide if the performance hit is worth it.

**Comment by RomanDietenmeier** [comment] 2023-04-23 22:04
I used git bisect and the commit that broke the ViewportTexture for PointLight2Ds is: [84d734da0e4dc4f0076c61a7178d8ad7b9f3b616](https://github.com/godotengine/godot/commit/84d734da0e4dc4f0076c61a7178d8ad7b9f3b616)
I also need dynamic lights and would welcome a solution to this problem.

**Comment by RomanDietenmeier** [comment] 2023-04-27 01:13
I got a workaround working as long as only one PointLight2D uses the ViewportTexture. 
```
# Called every frame. 'delta' is the elapsed time since the previous frame.
func _process(delta):
	texture=null
	texture=subViewport.get_texture()
	pass
```

As soon as you try to use the same trick on a second light, both lights will stop working.
You can try it out with this Godot 4.0.2 example project:
[WorkaroundLightPoint2DViewportTexture.zip](https://github.com/godotengine/godot/files/11338587/WorkaroundLightPoint2DViewportTexture.zip)

**Comment by iamcal** [comment] 2024-02-14 22:25
When behavior like this is purposefully broken, it would be *hugely* helpful to show at least a hint in the editor when setting a viewport texture that it wont work. Like others that have posted into the various bug threads before me, I've wasted hours trying to understand why this didn't work.

**Comment by DigitalTableTops** [comment] 2024-05-08 21:27
> When behavior like this is purposefully broken, it would be _hugely_ helpful to show at least a hint in the editor when setting a viewport texture that it wont work. Like others that have posted into the various bug threads before me, I've wasted hours trying to understand why this didn't work.

Yes agreed. I spent quite a lot of time before stumbling across this. to be clear: you cannot update PointLight2D textures once they've been loaded into this atlas. Adding a note about in the docs would be great:

https://docs.godotengine.org/en/stable/classes/class_pointlight2d.html#class-pointlight2d-property-texture

I'd do it myself but am afraid I would mess up the terminology or details.

My fix was to change the texture, duplicate my PointLight2D node, then remove the old node. Seems to be working well. As this is something that only happens occasionally in my project.

**Comment by AThousandShips** [comment] 2024-05-31 18:55
Closing in favor of:
* https://github.com/godotengine/godot-proposals/issues/9855

As this is a feature not a bug, thank you for reporting

**Closed by AThousandShips** 2024-05-31 18:55 UTC
Labels: enhancement, discussion, topic:rendering, documentation, topic:2d

**Comment by MelPeslier** [comment] 2024-06-04 14:32
> I got a workaround working as long as only one PointLight2D uses the ViewportTexture.
> 
> ```
> # Called every frame. 'delta' is the elapsed time since the previous frame.
> func _process(delta):
> 	texture=null
> 	texture=subViewport.get_texture()
> 	pass
> ```
> 
> As soon as you try to use the same trick on a second light, both lights will stop working. You can try it out with this Godot 4.0.2 example project: [WorkaroundLightPoint2DViewportTexture.zip](https://github.com/godotengine/godot/files/11338587/WorkaroundLightPoint2DViewportTexture.zip)

You can do that to have it in multiple ones :
`	await RenderingServer.frame_post_draw
	var viewport_texture : ViewportTexture = get_texture()
	var image: Image = viewport_texture.get_image()
	var image_texture := ImageTexture.create_from_image(image)`

And her you use image_texture where you want

**Comment by AThousandShips** [comment] 2024-06-04 14:38
Please comment on the issue above this has been closed in favour of it and the focus should be on:
* https://github.com/godotengine/godot-proposals/issues/9855
