### ISSUE TITLE
Wrong behaviour on copying texts with accented characters on linux.

### ISSUE THREAD

**Issue by lorenzobeccaro** [godotengine/godot#3889] opened 2016-03-01 09:50 UTC
I can reproduce it on Linux (Xubuntu 14.04) but not in windows 10.

Copying a text with characters like à è é ì ò ù (in Italian they're very common) and pasting in the engine will paste only the text before the first occurence of one of them.

**Comment by bojidar-bg** [comment] 2016-03-01 10:18
I can't reproduce on Linux (Arch, KDE, 64-bit) on 210d332defffb5528da6c6aff3b28fb8732bf007. (tested by copying the above issue's text into both the script editor and the text property of a `Label`)

Maybe give us more details about your system?

**Comment by akien-mga** [comment] 2016-03-01 10:18
I believe it's the same bug as #871.

**Comment by lorenzobeccaro** [comment] 2016-03-01 14:34
Maybe it's related to system language?

**Comment by AlexHolly** [comment] 2016-03-03 22:11
+1
Ubuntu 64-bit

German keyboard
ö,ä,ü

cursor stops on first non ascii char on copy&paste.

This happens when I copy the text from a folder or from irc(Smuxi).
But it works when I copy from skype or from this "text box Github Comment".

   "|" shows the cursor position
   spaces can be ignored

Input:
   dfgdg ö dfgdfg
Output:
   dfgdg |


If there is no text after the ö I get this behavior. Spaces after ö don't change the result.

Input:
   asd ö
Output:
   |

**Comment by akien-mga** [comment] 2016-06-18 20:51
Closing as duplicate of #871, which was fixed a few weeks ago \o/

Don't hesitate to reopen or comment if it's not the case for you.

**Closed by akien-mga** 2016-06-18 20:51 UTC
Labels: bug, platform:linux, topic:editor, usability
