### ISSUE TITLE
Tool script doesn't see user defined actions when run in editor 

### ISSUE THREAD

**Issue by miv391** [godotengine/godot#82685] opened 2023-10-02 16:13 UTC
### Godot version

v4.2.dev5.official [e3e2528ba]

### System information

Godot v4.2.dev5 - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1060 6GB (NVIDIA; 31.0.15.3640) - Intel(R) Core(TM) i5-3570K CPU @ 3.40GHz (4 Threads)

### Issue description

The example project has a tool script which defines MyToolNode which exports a string variable. When the string is changed, the tool script tries to access the actions from InputMap. However, only the built-in actions are seen. User defined action is not seen. Tool script:

```gdscript
@tool
extends Node
class_name MyToolNode

@export var change_me: String = "": set = _set_value

func _set_value(new_value: String) -> void:
	change_me = new_value
	print("tool script:")
	print("has action ui_select: ", InputMap.has_action("ui_select"))
	print("has action my_action: ", InputMap.has_action("my_action"))
```

Output when exported variable is changed:

```
Set change_me
tool script:
has action ui_select: true
has action my_action: false
```

Output when the project is run:

```
Godot Engine v4.2.dev5.official.e3e2528ba - https://godotengine.org
Vulkan API 1.3.242 - Forward+ - Using Vulkan Device #0: NVIDIA - NVIDIA GeForce GTX 1060 6GB
 
tool script:
has action ui_select: true
has action my_action: true
game started:
has action ui_select: true
has action my_action: true
```

### Steps to reproduce

1. Open the example project
2. Select MyToolNode from scene tree 
3. Use Inspector to change node's "Change Me" property
-> "my_action" is not found

### Minimal reproduction project

[g42_tool_script.zip](https://github.com/godotengine/godot/files/12784387/g42_tool_script.zip)

**Comment by KoBeWi** [comment] 2023-10-02 16:51
InputMap from the editor contains the editor actions, not project's.
Duplicate of #71613 and similar issues.

**Closed by KoBeWi** 2023-10-02 16:51 UTC
