### ISSUE TITLE
Tool script doesn't work if built-in script

### ISSUE THREAD

**Issue by Oranjoose** [godotengine/godot#22055] opened 2018-09-13 22:14 UTC
**Godot version:**
Godot 3.1 alpha 1 64-bit

**OS/device including version:**
Windows 10 x64, i7 6770HQ NVIDIA GTX 1060

**Issue description:**
A simple tool script on KinematicBody2D does not update the node in the editor, but works when the game is run. The same script works for Sprite though.

Sprite tool script does work:
```
tool
extends Sprite

export (Vector2) var MyScale = Vector2(1, 1) setget _change_scale

func _change_scale(value):
	MyScale = value
	self.scale = value
	update()
```

KinematicBody2D tool script doesn't work:
```
tool
extends KinematicBody2D

export (Vector2) var CollisionBounds = Vector2(1, 1) setget _set_collision_bounds

func _set_collision_bounds(value):
	CollisionBounds = value
	self.scale = value
	update()
```
Even making changes entirely separate from the node's properties don't work, such as with a simple _draw() function:

This _draw() function updates in the editor for Sprite, but not for KinematicBody2D
```
func _draw():
	var rect = Rect2(0, 0, 200, 300)
	draw_rect(rect, Color(randf(), randf(), randf()))
```
Do tool scripts entirely not work to update in the editor for KinematicBody2D nodes? Is this by design?

**Comment by Oranjoose** [comment] 2018-09-14 15:29
I was able to narrow down the issue more.

The KinematicBody2D was using a built-in script. As soon as I made the script a separate gdscript file, the KinematicBody2D started to update inside of the editor. Do built-in scripts not work as tool scripts? Or is that a different bug.

PS: Whoa! The KinematicBody2D is updating in real-time in the editor, as in falling and moving around with user input. That's more `tool` than I need. Heck, I can't even drag and drop the node anymore, since it is overriding the drag and drop with the _physics_process position updating.

**Comment by DualMatrix** [comment] 2018-09-16 00:34
You can prevent the whole too much tool issue by checking wether you are in the editor or in game in the KinematicBody script using Engine.editor_hint

**Comment by KoBeWi** [comment] 2019-12-20 22:49
So I just discovered that built-in tool scripts DO work in the editor, but it's a bit unreliable, i.e. it's a hassle to update and reload the script.

**Comment by nathanwfranke** [comment] 2020-01-20 23:01
I can reproduce this in RC 2

**Comment by akien-mga** [comment] 2020-01-22 08:13
Duplicate of #15406.

**Closed by akien-mga** 2020-01-22 08:13 UTC
Labels: bug, topic:editor
