### ISSUE TITLE
Scripts and Signals disconnects in project startup

### ISSUE THREAD

**Issue by GorEldeen** [godotengine/godot#75297] opened 2023-03-24 18:48 UTC
### Godot version

4.0

### System information

 Xubuntu, GLES3, Nvidia quadro 2000m

### Issue description

I made a 2D project in godot 4.0, Everything seem fine as i keep working on it
But some times when i close the project and then open it, Bunch of loading errors happens, The player in the main scene would be missing, The signals of Area2d has to be reconnected to work, As so as some scripts disconnect completly from the nodes

### Steps to reproduce

I cannot really write the whole thing, But i can give the project files so you can check it :
https://github.com/GorEldeen/GetOut

(For readers): You can use this project for your own creations as long as you mention the link for it 

### Minimal reproduction project

[GET OUT (copy 1).zip](https://github.com/godotengine/godot/files/11065537/GET.OUT.copy.1.zip)

**Comment by Calinou** [comment] 2023-03-24 20:19
- Duplicate of https://github.com/godotengine/godot/issues/75039.

**Closed by Calinou** 2023-03-24 20:19 UTC
Labels: bug, topic:editor, needs testing
