### ISSUE TITLE
There is a small chance that the editor settings will be reset when you quit to the project list or exit godot

### ISSUE THREAD

**Issue by CodeLazier** [godotengine/godot#75064] opened 2023-03-18 13:46 UTC
### Godot version

4.0,4.0.1 rc2

### System information

Win11

### Issue description

I'm not sure if it's my local machine environment issue, but this happened 2 or 3 times and I had to copy the backup editor_settings-4.tres file in case the whole editor settings were reset. Currently I can't reproduce the bug, just a low probability of it happening.

### Steps to reproduce

quit to the project list or exit Godot and rerun Godot.

### Minimal reproduction project

I can't reproduce the bug, sorry!

**Comment by Zireael07** [comment] 2023-03-18 14:54
Just a heads-up: when I had a similar issue, the disk (SSD) failed several months later

**Comment by CodeLazier** [comment] 2023-03-18 15:21
> Just a heads-up: when I had a similar issue, the disk (SSD) failed several months later
That should cause random problems with anything, including other software or OS. But anything is possible. Who knows. Thanks for the reminder, I'll keep an eye out

**Comment by Calinou** [comment] 2023-03-19 02:55
Duplicate of https://github.com/godotengine/godot/issues/40968.

**Closed by Calinou** 2023-03-19 02:55 UTC
