### ISSUE TITLE
Implement automatic word wrap based on Line Lenght Guideline

### ISSUE THREAD

**Issue by rogeriodec** [godotengine/godot#27072] opened 2019-03-14 22:41 UTC
**Godot version:**
3.1

**OS/device including version:**
Windows 10 x64

**Issue description:**
The current Word Wrap option _(Editor > Editor Settings > Text Editor > Line Numbers > Word Wrap)_ is currently wrapping only based on the text editor window size.
It would be useful if there is an option to wrap based on the Line Lenght Guideline Column option  _(Editor > Editor Settings > Text Editor > Line Numbers > Lenght Guideline Column)_

![](https://media.discordapp.net/attachments/212250894228652034/555863184901144580/unknown.png)

**Comment by KoBeWi** [comment] 2019-03-15 16:35
But why? The purpose of word wrap is to make long lines fully visible. Why make that space even smaller? Especially since you are not supposed to go past guideline column at all.

**Comment by rogeriodec** [comment] 2019-03-15 17:41
If I want to ensure that my text never exceeds 80 columns, it would be useful to break the line on the Guideline length.
See this behavior in PyCharm:
![c](https://user-images.githubusercontent.com/11199752/54450924-574a4c00-4730-11e9-9b4d-2bf996111262.gif)

**Comment by KoBeWi** [comment] 2019-03-15 18:21
Then it's not a standard word wrap, because word wrap is only visual. Doing automatic line breaking is more difficult, because you can't start a newline anywhere.

**Comment by bojidar-bg** [comment] 2019-03-15 18:23
@KoBeWi The issue is asking for word wrap on the line length guideline, similar to the one made for end-of-line. It is not asking for automatic insertion of newlines.

**Comment by rogeriodec** [comment] 2019-03-15 18:34
In fact, the example was not good. 
The idea is **just the visual break**, you do not need to create a new line.
The main purpose is to **have the entire line visible within the max column limit defined by the Guideline.**

**Comment by KoBeWi** [comment] 2019-03-15 18:52
But you see when your text crosses the line :/
And if it's only visual then you'd have to break the line yourself if you don't want to exceed the limit.

Anyways, IMO it's only limiting the available space, because you are loosing what is between the line and editor width. I just don't see how could that be useful.

**Comment by rogeriodec** [comment] 2019-03-15 19:42
So let's back. In the Pycharm example above, the line was automatically broken based on these parameters:

![image](https://user-images.githubusercontent.com/11199752/54457748-0858e280-4741-11e9-8182-0d2e8bde6e04.png)

My proposal is to let the user decide if he wants to break the line manually or automatically, based on these parameters.

**Comment by clayjohn** [comment] 2020-05-26 05:27
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!

**Closed by clayjohn** 2020-05-26 05:27 UTC
Labels: feature proposal, topic:editor, usability
