### ISSUE TITLE
Editor Settings page does not show property hints

### ISSUE THREAD

**Issue by rcorre** [godotengine/godot#37396] opened 2020-03-29 00:34 UTC
**Godot version:**

3.2.1.stable.custom_build.f0a489cf4

and 

3.2.1.stable.custom_build.f0a489cf4

**OS/device including version:**

Linux 5.5.13-arch1-1

**Issue description:**

The tooltips in the `Editor Settings` dialog, just show the fully-qualified setting name but not any additional hints.
It would be useful to show additional details about what the setting does.
For example, it would be useful to know that `text_editor/external/exec_flags` uses substitutions like `{file}` and `{line}`.

It seems like we add these details to the editor hints [like so]("text_editor/external/exec_flags"):

```
EDITOR_DEF("text_editor/external/exec_flags", "{file}");
EditorSettings::get_singleton()->add_property_hint(PropertyInfo(Variant::STRING, "text_editor/external/exec_flags", PROPERTY_HINT_PLACEHOLDER_TEXT, "Call flags with placeholders: {project}, {file}, {col}, {line}."));
```

But they aren't actually visible

**Steps to reproduce:**

**Minimal reproduction project:**
![1585441141](https://user-images.githubusercontent.com/2496231/77837137-895bff80-7133-11ea-9759-60f52887bf67.png)

**Comment by dankan1890** [comment] 2020-03-29 05:25
Placeholder text is for input field of property, not in tooltip:
https://docs.godotengine.org/en/latest/classes/class_@globalscope.html#enum-globalscope-propertyhint

**Comment by Calinou** [comment] 2020-03-29 12:10
Duplicate of #29694.

**Closed by Calinou** 2020-03-29 12:10 UTC
