### ISSUE TITLE
Fovy field value not updated when changing it by mouse

### ISSUE THREAD

**Issue by sebastien-prudhomme** [godotengine/godot#6448] opened 2016-09-10 16:03 UTC
**Operating system or device - Godot version:**

Linux Mint 18 / Gogot 2.1 64 bits

**Issue description** (what happened, and what was expected):

When changing the field of view of a 3d camera by draging the red circle, the corresponding "fovy" field is not updated in real-time.

You need to select another object and reselect the camera to have the correct value displayed.

**Steps to reproduce:**

**Link to minimal example project** (optional but very welcome):

**Comment by lordadamson** [comment] 2016-10-02 11:30
@akien-mga I'd like to fix this bug but I need help since I'm not familiar with the code base (aka noob), could you please tell me what files would you be looking at if you were to fix this bug?

**Comment by damon-myers** [comment] 2016-10-28 03:10
@lordadamson Did a search on the codebase and it looks like ./core/math.camera_matrix.cpp and ./scene/3d/camera.cpp would be a good place to start looking. 

I'll let you know if I get a better idea of exactly where it's handled!

**Comment by bojidar-bg** [comment] 2016-10-28 08:22
I'd guess it is the [`tools/editor/plugins/camera_editor_plugin.cpp`](https://github.com/godotengine/godot/blob/master/tools/editor/plugins/camera_editor_plugin.cpp) file that is responsible instead, but I can't be really sure.

**Comment by nunodonato** [comment] 2017-06-02 14:59
this seems to no longer be an issue in v3. perhaps tag to 2.1?

**Comment by Noshyaar** [comment] 2018-04-06 10:33
First of all thank you for your report and sorry for the delay.

We released Godot 3.0 in January 2018 after 18 months of work, fixing many old issues either directly, or by obsoleting/replacing the features they were referring to.

We still have hundreds of issues whose relevance/reproducibility needs to be checked against the [current stable version](https://godotengine.org/download), and that's where you can help us.
**Could you check if the issue that you described initially is still relevant/reproducible and comment about it here?**

For bug reports, please also make sure that the issue contains detailed steps to reproduce the bug and, if possible, a zipped project that can be used to reproduce it right away. This greatly speeds up debugging and bugfixing tasks for our contributors.

Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

Thanks in advance.

*Note: This message is being copy-pasted to many "stale" issues (90+ days without activity). It might happen that it is not meaningful for this specific issue or appears oblivious of the issue's context, if so please comment to notify the Bugsquad about it.*

**Comment by Calinou** [comment] 2018-08-31 22:08
This is still occurring as of commit https://github.com/godotengine/godot/commit/29f2571662da0ee93ea2a632ec3b60aa26246563.

**Comment by Calinou** [comment] 2018-09-06 19:54
This was fixed in commit https://github.com/godotengine/godot/commit/39e8aca1b77c6cba8f7fa22cc277441e5e86cd16, closing.

**Closed by Calinou** 2018-09-06 19:54 UTC
Labels: bug, junior job, topic:editor
