### ISSUE TITLE
Reloading/Re-Importing .dae, .obj, .gltf only works one time in a scene

### ISSUE THREAD

**Issue by Rabocop** [godotengine/godot#12181] opened 2017-10-17 13:58 UTC
Windows, Linux

I saw in #8000 that this problem was fixed and closed, but the fact is that still there. What I noticed is that the reloading only works for the first changes, then you have to close and reopen all the scenes.

I tried with dae, obj and gltf formats with the same results , either in Windows and Linux.
-Export a mesh or scene
- Instance the scene to watch it or tweak it
- Make some change
-Export Again
-It works
-Make another change, and export again
-Now you have to close the scene and reopen it again if you want to get the changes.

![issue_reimporting](https://user-images.githubusercontent.com/7796648/31668961-8d70358a-b34b-11e7-8923-05a7bbf521ed.gif)

**Comment by Rabocop** [comment] 2017-10-17 14:16
I noticed also something that can help to solve this:
-Mesh only gets updated in the instanced scene when the original .dae is opened
-The Level in which you want to instance those objects only gets updated when the instanced scene from the original is saved, which breaks the workflow totally.
![issue_reimporting2](https://user-images.githubusercontent.com/7796648/31669837-18d335da-b34e-11e7-8b7f-9155f18777ee.gif)

**Comment by Ace-Dragon** [comment] 2017-10-17 19:13
A decent alternative for now is to create a new empty scene, where you add a spatial node and then instance the .dae file as a child scene. You can then expand it via 'show editable children' to do things like assign new materials.

In my case, not only does it work a lot better (worse case, you close the scene after saving, re-open it, and it updates without losing data), but it's also potentially more useful as you often might need to add certain things like rays, joints, and area shapes for game logic purposes (even large changes to the scene file won't get rid of your extra nodes).

However, updating scene files on re-import should just work if possible.

**Comment by djrm** [comment] 2017-11-11 19:57
duplicate of #10119

**Closed** 2017-11-12 19:52 UTC
Labels: bug, topic:editor
