### ISSUE TITLE
Crash when removing some shortcuts from Editor Settings

### ISSUE THREAD

**Issue by jmb462** [godotengine/godot#51794] opened 2021-08-17 13:08 UTC
### Godot version

Master ca6c5cf7e6252558d8791d41b8b757929ac3819c

### System information

Windows 10

### Issue description

Removing some shortcuts from Editor Settings crash the editor.

Removing ``Shift + Delete`` for ``ui_cut`` crashes all the time if ``CTRL +X`` has already been deleted.
Removing ``CTRL + X`` never crash.

Backtrace  : 
![backtrace](https://user-images.githubusercontent.com/3649998/129730450-2a9fb435-e9c1-409f-b8ab-98f0af7a8767.jpg)

### Investigation : 
Problem occurs in editor_settings.cpp line 1616
```	// Update the shortcut (if it is used somewhere in the editor) to be the first event of the new list.
	if (shortcuts.has(p_name)) {
		shortcuts[p_name]->set_event(event_list.front()->get());
	}
```

The crash happens when even_list.front() seems to return False.
The ->get() throw an exception.

Didn't manage to go further.

### Steps to reproduce

Go in Editor Settings / Shortcuts
1°) Remove CTRL+X shortcuts from ui_cut
2°) Remove Shift + Delete from ui_cut action. => Crash

(Other shortcuts also crash but not all.)

### Minimal reproduction project

Empty project is enough to reproduce bug.

**Comment by requizm** [comment] 2021-08-17 17:15
I can't reproduce on 4.0 dev https://github.com/godotengine/godot/commit/6cea7ebae4721e05ea7013c6159a751f7498ea85

![ui_cut_shortcut_del_test](https://user-images.githubusercontent.com/12533045/129768029-9dc820a2-89c2-4663-9f77-173879a12276.gif)

**Comment by jmb462** [comment] 2021-08-17 18:58
Removing ``editor_settings-4.tres`` from AppData/Roaming/Godot solved the issue.

Something was wrong with this configuration file.
Going to do some tests to find what before closing this issue.

**Comment by jmb462** [comment] 2021-08-17 19:20
@requizm Thanks, I found that the crash occurs when : 
- deleting the Ctrl + X shorcut
- then deleting the Shift+Delete.

Didn't realize that at first. Updating step to reproduice.

**Comment by ThreeRhinosInAnElephantCostume** [comment] 2021-08-17 20:52
I was able to reproduce this on the latest master, also happens for ui_paste in a very similar way. Perhaps it only happens for shortcuts containing shift? Still looking into it.

**Comment by jmb462** [comment] 2021-08-17 21:05
Ctrl+Insert cause the bug too.  (without shift)

**Comment by ThreeRhinosInAnElephantCostume** [comment] 2021-08-17 21:23
Looks to be caused by deleting the last keybind from a shortcut that has multiple keybinds assigned to it by default.

**Comment by jmb462** [comment] 2021-08-18 07:48
OK, I solved it.
I will propose a PR this evening.

**Comment by EricEzaM** [comment] 2022-03-10 13:42
I can't reproduce on v4.0.alpha.custom_build [862a88e90]

Can you please check that this still happens? It may have been inadvertently fixed since being reported.

**Comment by jmb462** [comment] 2022-03-10 17:34
Yes, we can close this issue.
Not reproductible anymore.

**Closed** 2022-03-10 17:34 UTC
Labels: bug, topic:editor, crash
