### ISSUE TITLE
godot -e -q hangs instead of quitting

### ISSUE THREAD

**Issue by allexks** [godotengine/godot#42839] opened 2020-10-15 20:37 UTC
**Godot version:** 3.2.3 stable

**OS/device including version:** Ubuntu 20.04, GitHub Actions runner

**Issue description:**
Used `-q` option of the godot command line executable to quit it after opening but it hangs most of the time.

**Steps to reproduce:**
1. Create a GitHub repo with a Godot project in it
2. Create a GitHub action which involves a step in which the `godot -e -q` command is executed

**Expected results:**
The command iterates over the project and quits execution

**Actual results:**
Most of the times it hangs and never quits.

**Minimal reproduction project:**
Any project I guess.
Also probably it hangs on other operating systems and conditions, I have just not tested it

**Comment by Calinou** [comment] 2020-10-15 20:49
Duplicate of https://github.com/godotengine/godot-proposals/issues/1362.

**Closed by Calinou** 2020-10-15 20:49 UTC
