### ISSUE TITLE
DOF enabled disables glow/bloom effect

### ISSUE THREAD

**Issue by Gibbz** [godotengine/godot#8827] opened 2017-05-19 05:55 UTC
**Operating system or device - Godot version:**
Ubuntu + arch

**Issue description:**
Enable DOF in the world env and notice the bloom dissapears

**Comment by akien-mga** [comment] 2017-06-29 09:03
Is this still valid in the current master branch?

**Comment by sketchyfun** [comment] 2017-07-21 20:47
possibly related? #9756

**Comment by djrm** [comment] 2017-08-07 19:27
i think this was fixed, unable to reproduce

**Comment by reduz** [comment] 2017-08-07 19:29
ah yeah, it's fixed, closing

**Closed by reduz** 2017-08-07 19:29 UTC
Labels: bug, topic:rendering
