### ISSUE TITLE
Icons disappearing in material inspector view.

### ISSUE THREAD

**Issue by snailrhymer** [godotengine/godot#55945] opened 2021-12-15 00:30 UTC
### Godot version

4.0-dev.20211210

### System information

Windows 10, Vulkan, GPU:  NVIDIA - GeForce GTX 1660 Ti

### Issue description

The shape selection and lighting selection icons in the material preview window in the inspector disappear instead of greying out. Only the top icon of each set (sphere and light 1, respectively) disappear; the lower two behave as expected.

Console output from loading the project to clicking the icon:
```
Godot Engine v4.0.dev.20211210.official.21b81998b - https://godotengine.org
WARNING: GENERAL - Message Id Number: 0 | Message Id Name: Loader Message
        ReadDataFilesInRegistry: Registry lookup failed to get layer manifest files.
        Objects - 1
                Object[0] - VK_OBJECT_TYPE_INSTANCE, Handle 127898672
     at: _debug_messenger_callback (drivers/vulkan/vulkan_context.cpp:154)
Vulkan API 1.2.162 - Using Vulkan Device #0: NVIDIA - GeForce GTX 1660 Ti

Editing project: C:/Users/harry/OneDrive/Desktop/godot4 (C:::Users::harry::OneDrive::Desktop::godot4)
Godot Engine v4.0.dev.20211210.official.21b81998b - https://godotengine.org
WARNING: GENERAL - Message Id Number: 0 | Message Id Name: Loader Message
        ReadDataFilesInRegistry: Registry lookup failed to get layer manifest files.
        Objects - 1
                Object[0] - VK_OBJECT_TYPE_INSTANCE, Handle 1604464
     at: _debug_messenger_callback (drivers/vulkan/vulkan_context.cpp:154)
Vulkan API 1.2.162 - Using Vulkan Device #0: NVIDIA - GeForce GTX 1660 Ti

ERROR: Storage buffer supplied (binding: 0) is invalid.
   at: (drivers/vulkan/rendering_device_vulkan.cpp:5851)
```

### Steps to reproduce

Create a new project and set the default scene as a Node3D. Add a MeshInstance3D as a child and give it e.g. a new SphereMesh. Navigate to mesh/material in the inspector, set the material as a new StandardMaterial3D (ORMMaterial has the same results).

Change the material preview by clicking on the cube icon; the sphere icon should disappear. Clicking where it was will make it reappear, and the cube icon will lose its highlight. Similarly, toggling the top light on and off will cause that icon to disappear and reappear.

**Comment by jmb462** [comment] 2022-02-12 11:09
@snailrhymer  Cannot reproduce anymore.

I think it has been fixed by https://github.com/godotengine/godot/pull/57326

**Comment by akien-mga** [comment] 2022-02-12 11:16
Indeed, duplicate of #57088.

**Closed by akien-mga** 2022-02-12 11:16 UTC
Labels: bug, topic:editor, regression
