### ISSUE TITLE
Game crashing during startup when played in Editor because of PackedScene export variables

### ISSUE THREAD

**Issue by chandujr** [godotengine/godot#55409] opened 2021-11-28 11:04 UTC
### Godot version

v3.4.stable.official

### System information

Windows 10

### Issue description

If 2 scenes refer to each other in script export variables as PackedScene resource, then running either scene will crash the game during startup.

Here's the screenshot of the errors
![Capture1](https://user-images.githubusercontent.com/14921501/143764708-b326f8bd-ebb2-4a1b-ad5f-f9721560326e.PNG)
:

Please note that I'm not using the scene instances in any way.

### Steps to reproduce

1. Create a new project (GLES3/GLES2)
2. Create a new scene (**Scene1**) and attach a script to it
3. Create an export variable for a PackedScene resource
```gdscript
export(PackedScene) var scene2
```
4. Create another scene (**Scene2**) and attach script to it
5. Create an export variable for PackedScene in this scene too
```gdscript
export(PackedScene) var scene1
```
6. Assign **Scene2.tscn** for `scene2` variable and **Scene1.tscn** for `scene1` variable
7. Play any one of the scene, game crashes with errors

### Minimal reproduction project

[SceneReference.zip](https://github.com/godotengine/godot/files/7613379/SceneReference.zip)

**Comment by Calinou** [comment] 2021-11-28 17:22
This is due to a cyclic reference, which I doubt can be fixed. Detecting it and printing an error may be possible, but it's not trivial.

**Comment by chandujr** [comment] 2021-11-29 10:24
I thought this might be a pretty common scenario. Is there a better way I could handle scene export variables? Consider a game where I have a Home scene from which I can navigate to the GamePlay scene and then when I quit, I'm navigated back to Home scene. Godot will crash in this case if I use PackedScene export variables. (maybe I should use direct string paths to the scene instead of exporting it?)

**Comment by Amatrelan** [comment] 2021-11-29 11:52
One way to fix this is create scene manager who handles all scene switching, with this there is no cyclic dependencies. 
- Create new scene (for ex: Global.tscn) with script to manage scene switching (for example load_scene(scene_name) function in it)
- On main menu call Global.load_scene(game_scene)
- On game you can Global.load_scene(main_menu)

**Comment by Rindbee** [comment] 2022-08-31 12:03
Seems to be a duplicate of #24146.

**Closed** 2022-08-31 13:08 UTC
Labels: bug, topic:core, crash
