### ISSUE TITLE
CharacterBody3D with Capsule/Sphere gets stuck in the simplest possible Trimesh collider.

### ISSUE THREAD

**Issue by idchlife** [godotengine/godot#77485] opened 2023-05-25 19:05 UTC
### Godot version

v4.0.3.stable.official [5222a99f5]

### System information

macOS Ventura 13.0

### Issue description

I created Trimesh from cavern model I made and I noticed that it's almost impossible to freely navigate through the floor.

https://imgur.com/TQXgWt4

Then I recreated in Blender simpler mesh for collider specifically. In Godot 4 I created trimesh out of it, and result is like this:

https://imgur.com/Bc6eKsQ

Here is video with debug collision shapes and camera from afar:

https://imgur.com/lllt6HJ

### Steps to reproduce

1. Create 3D mesh with "wavey" floor.
2. Add CharacterBody3D with basic controls
3. Walk, notices that it gets often stuck.
4. Notice that sometimes it moves faster and sometimes slower and the gets stuck

### Minimal reproduction project

[character-body-3d-stuck-repro.zip](https://github.com/godotengine/godot/files/11568429/character-body-3d-stuck-repro.zip)

**Comment by Calinou** [comment] 2023-05-25 22:20
- Duplicate of https://github.com/godotengine/godot/issues/46712.

Try inverting the mesh's normals before generating collision from it.

**Closed by Calinou** 2023-05-25 22:20 UTC

**Comment by idchlife** [comment] 2023-05-25 22:23
> 

@Calinou hey! Thanks for the answer.

In terms of cave-like structures with inverted normals... How one can do that? Wouldn't it create trimesh that has collisions outside cave, but not inside?
