### ISSUE TITLE
Actions not working on exported game on Godot-master and Godot-3.0-alpha1

### ISSUE THREAD

**Issue by alimalkhalifa** [godotengine/godot#10210] opened 2017-08-09 20:15 UTC
## Version
Godot 3.0-alpha1 and master on Windows 10 Desktop

## Issue
After exporting a project from Godot 3.0 master or alpha 1, actions are not being recognized

## Suspected cause
Binary is not able to read actions from project.binary.  Once you throw the project.godot file in the same directory, it works.

**Comment by djrm** [comment] 2017-08-09 20:41
duplicate of #9472

**Closed** 2017-08-10 00:15 UTC
Labels: archived
