### ISSUE TITLE
 bug with Light2D and LightOccluder2D on Mobile Intel 4 Series Express Family Chipset

### ISSUE THREAD

**Issue by NatanielBR** [godotengine/godot#29977] opened 2019-06-22 11:12 UTC
Searching, I discovered that this bug has already been opened and solved, although this is still happening with me. [Post](https://github.com/godotengine/godot/issues/24750)

**Godot version:** 3.1.1.stable.official

**OS/device including version:** Windows 7 Ultimate | Mobile Intel(R) 4 Series Express Chipset Family

**Issue description:**
The bug happens in Viewport and in-game. The image represents well what happens: [Image](https://i.imgur.com/FuZ9h8E.png)

**Steps to reproduce:**
 Create a new project using OpenGL ES 2.0 (My pc does not run 3.0).
- Add a sprite and a background.
- In the sprite, add LightOccluder2D.
- Add Light2D to the scene and place a light texture.
- Activate Shadow on Light2D.

It is possible that the bug does not happen first and everything happens as expected but when moving the viewport or running the scene if you notice the bug. If you run the scene or switch to another scene, the background of the Light (the first scene) will turn black.

**Minimal reproduction project:**
[teste bug.zip](https://github.com/godotengine/godot/files/3316764/teste.bug.zip)

**Comment by clayjohn** [comment] 2019-06-22 16:48
You have not actually said what the bug is, and I cannot tell from the picture. The LightOccluder appears to be functioning properly.

**Comment by KoBeWi** [comment] 2019-06-23 13:46
I can't reproduce it with NVidia GTX 1060.

> You have not actually said what the bug is, and I cannot tell from the picture.

Look around the occluder what happened to the background.

**Comment by KoBeWi** [comment] 2020-08-03 20:48
Can anyone still reproduce this bug in [Godot 3.2.3 rc3](https://godotengine.org/article/release-candidate-3-2-3-rc-3) or any later release?

**Comment by akien-mga** [comment] 2020-09-03 15:00
No answer, so closing.

Please comment if you can still reproduce it, and this issue can be reopened. Or open a new issue with a MRP if this would be better suited.

**Closed by akien-mga** 2020-09-03 15:00 UTC
Labels: bug, topic:rendering
