### ISSUE TITLE
Viewport's render target update mode "When Visible" doesn't work

### ISSUE THREAD

**Issue by rarsp** [godotengine/godot#66245] opened 2022-09-22 07:11 UTC
### Godot version

4.0 beta 1 mono

### System information

Windows 10

### Issue description

Viewport's render target update mode "When Visible" doesn't work at all at as it works in 3.5

### Steps to reproduce

Just create viewport and try render it to some texture.

**Comment by Rindbee** [comment] 2022-09-22 11:55
Probably a duplicate of #55471.

**Comment by kleonc** [comment] 2022-09-22 19:15
Given the lack of detailed info in here, it indeed seems like a duplicate of #55471. Hence closing.

@rarsp If you have some relevant info not mentioned in #55471, please add a comment in there. If you think you're facing a different/separate issue than #55471, please provide some more explanation/details in here and in such case this issue could be reopened.

**Closed** 2022-09-22 19:15 UTC
