### ISSUE TITLE
Godot 4.0 Crash if i use the dedicated gpu on a laptop

### ISSUE THREAD

**Issue by Mikadini** [godotengine/godot#56164] opened 2021-12-22 16:30 UTC
### Godot version

v4.0.dev.20211210.official.21b81998b

### System information

Winwos 10, Ryzen 9 5900hx, 32gb ram, 1tb m2 3.0, 3080 max-q 115w

### Issue description

If i connect an external monitor or if i use the 3080 on my laptop, godot doesn't start and crash with this error: "vkEnumeratePhysicalDevices reported zero accessible devices.".

The only way to use godot 4.0 on my laptop is when i use it only with the internal monitor and with the integrated gpu (vega).

### Steps to reproduce

Simply start godot 4.0 on a notebook without using the integrated gpu.

**Comment by Calinou** [comment] 2021-12-22 17:28
Related to https://github.com/godotengine/godot/issues/54962. This may be fixed by https://github.com/godotengine/godot/pull/55020 – could you build https://github.com/bruvzg/godot/tree/vlk_device_surface_check from source to test it? See compiling instructions here: https://docs.godotengine.org/en/latest/development/compiling/index.html

**Comment by Mikadini** [comment] 2021-12-24 18:59
> Related to #54962. This may be fixed by #55020 – could you build https://github.com/bruvzg/godot/tree/vlk_device_surface_check from source to test it? See compiling instructions here: https://docs.godotengine.org/en/latest/development/compiling/index.html

sry now i have only the office pc and i can't install too many things on it ):

**Comment by Mikadini** [comment] 2021-12-25 00:51
> Related to #54962. This may be fixed by #55020 – could you build https://github.com/bruvzg/godot/tree/vlk_device_surface_check from source to test it? See compiling instructions here: https://docs.godotengine.org/en/latest/development/compiling/index.html

In any 

> > Related to #54962. This may be fixed by #55020 – could you build https://github.com/bruvzg/godot/tree/vlk_device_surface_check from source to test it? See compiling instructions here: https://docs.godotengine.org/en/latest/development/compiling/index.html
> 
> sry at this moment, i have only the office pc and i can't install too many things on it ):

in any case i will try every new godot 4.0 version i will found on this link: https://downloads.tuxfamily.org/godotengine/testing/4.0/ and if sometime the bug will fix i will close and update this issue

**Comment by nabfrew** [comment] 2022-01-16 20:18
I'm having the same issue, but it doesn't work on the laptop's internal monitor. I don't know how to set what GPU it should use, but I can try to tinker with that if it helps.

It worked yesterday fine. Looks like there were some automatic updates today, probably has something to do with it? 

![RecentUpdates](https://user-images.githubusercontent.com/23554500/149676457-f81e2ef3-4318-4dc3-b91a-a67ee819cdc0.PNG)

Godot version v4.0.dev.20220105.official.8f6cba3a4
Windows 10, AMD Ryzen 7 4800H with Radeon Graphics, 16,0 GB (15,4 GB usable)

**Comment by nabfrew** [comment] 2022-01-22 20:17
Update: Building from source, or the latest build, `Godot_v4.0-dev.20220118_win64`, I get this:
![Capture](https://user-images.githubusercontent.com/23554500/150654054-4fdd8c19-fbc8-4236-9218-af7f85b05b9c.PNG)

I can't find any GPU setting that makes it work. I don't know what I'm doing with this, but these are the options I've tinkered with, I've tried everything...

![image](https://user-images.githubusercontent.com/23554500/150654132-6d96c97d-4059-46c5-9cc7-0dea81edd123.png)
 
Also, if it's relevant, when I go back to earlier 4.0 versions (e.g. from December) I get the same result.

**Comment by nabfrew** [comment] 2022-01-22 20:24
...and another update:

This workaround worked for me: https://github.com/godotengine/godot/issues/45104#issuecomment-857516908

**Comment by bruvzg** [comment] 2022-02-16 17:34
Are integrated [GPU drivers](https://www.amd.com/en/support/apu/amd-ryzen-processors/amd-ryzen-9-mobile-processors-radeon-graphics/amd-ryzen-9-5900hx) up to date? It might be related to this driver bug: https://github.com/GPUOpen-Drivers/AMDVLK/issues/195, https://github.com/KhronosGroup/Vulkan-Loader/issues/552

**Comment by Mikadini** [comment] 2022-04-04 15:17
I have try to update all driver, i always set the dedicated gpu to be the use for godot, and i always have the same error. i try all the alpha version. i will continue to try all new versions and if the problem will be solved i will instantly update this tread.

**Comment by Calinou** [comment] 2022-04-04 18:48
@Mikadini Try switching the graphics adapter in the Windows control panel, *not* the NVIDIA Control Panel. Apparently, the NVIDIA Control Panel's graphics adapter switch is ignored on recent Windows 10 versions and Windows 11.

**Comment by ChristianB84** [comment] 2022-04-11 19:42
This looks very similar to issue #57708.

**Comment by Calinou** [comment] 2022-04-11 19:46
Looking at OP's hardware configuration, this is surely a duplicate of https://github.com/godotengine/godot/issues/57708.

**Closed by Calinou** 2022-04-11 19:46 UTC
Labels: bug, platform:windows, topic:rendering, confirmed, crash
