### ISSUE TITLE
draw_rect issue

### ISSUE THREAD

**Issue by tuga3d** [godotengine/godot#10869] opened 2017-09-01 18:53 UTC
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Linux 64bits, Godot [6fa6149](https://github.com/godotengine/godot/commit/6fa6149517b974fccd97e41f6b0a6466c83473fcl)

**Issue description:**

When drawing a rectangle with the fill option, the end coords are wrong.
I've added a simple project, just hit run, the unfilled rectangle draws correctly but the fill one only seems to go in positive values.

here is a little gif to demonstrate:
![godot-issue](https://user-images.githubusercontent.com/410751/29983725-1a940cfa-8f4f-11e7-908e-f670fd668227.gif)

**Steps to reproduce:**

**Link to minimal example project:**

[godot-issue.zip](https://github.com/godotengine/godot/files/1271226/godot-issue.zip)

**Comment by akien-mga** [comment] 2017-09-01 19:24
Duplicate of #10849.

**Closed** 2017-09-01 19:23 UTC
