### ISSUE TITLE
Editor changes lines of code around in two .tscn files on every play.

### ISSUE THREAD

**Issue by ScepticDope** [godotengine/godot#28346] opened 2019-04-23 18:39 UTC
**Godot version:**
3.1.1 RC1 with Mono

**Issue description:**
There are two .tscn files in my project that Godot likes to change on every play in the editor. It just changes the order of the lines of code in the file for no apparent reason. The two .tscn's are very similar I don't think that is causing it but it might help in finding out why this happens.

**Steps to reproduce:**
I have no idea how to reproduce this but I can give source of my project to dev team if need be.

**Comment by KoBeWi** [comment] 2019-04-23 19:19
Does it happen only for this project? What if you make a new project and copy these .tscn files there? (and if it still happens, attaching here the new project along with scenes would be helpful)

**Comment by akien-mga** [comment] 2019-04-23 21:21
Ia it only reproducible in 3.1.1 RC1, or also in 3.1 stable?

**Comment by ScepticDope** [comment] 2019-04-24 09:07
@KoBeWi it's mostly changing the lines of sprites around. Simply moving the .tscn without all the other stuff would give a completely other setup after one play and probably not produce the same bug. I won't post the source here but I will share it with someone from the Godot team if asked.

Also I found that sometime it does not change it on every play but when I restart the editor it does change the files every time again. See a .gif below showing two versions of the .tscn file created after play both vs the original. _(That original is just a version created with this bug, I committed the files twice in a row before realizing its a bug loop.)_

@akien-mga my project crashes 3.1 so I can't test that sorry.

![cap](https://user-images.githubusercontent.com/46745973/56647065-1a536c80-6681-11e9-9f5b-10fedd1b18cf.gif)

**Comment by ScepticDope** [comment] 2019-04-24 10:41
Just noticed this only happens when I have the scene with the bug open as a tab in the editor. If the tab is in focus does not matter. When the tab is closed and I run play it's file does not get changed.

**Comment by KoBeWi** [comment] 2019-12-15 23:07
@ScepticDope Can you test if it still happens in 3.2? It should be fixed.

**Comment by ScepticDope** [comment] 2019-12-19 14:38
@KoBeWi tested it on `Godot_v3.2-beta4_mono_win64`. Still has the same bug but not for these sort of lines `[ext_resource path` anymore.

Only inside here: `[sub_resource type="SpriteFrames" id=2]
animations = [ { ...all lines between this are fair game....} ]` and possibly also for other stuff that is just not in my specific .tscn file. Still reproducible on every restart of engine and running the game.

**Comment by KoBeWi** [comment] 2019-12-19 16:23
This might be the same case as #33411

**Comment by akien-mga** [comment] 2020-01-15 14:03
Duplicate of #22226.

**Closed by akien-mga** 2020-01-15 14:03 UTC
Labels: bug, topic:core, topic:editor
