### ISSUE TITLE
Text field operators missing on Godot 3.0

### ISSUE THREAD

**Issue by samvila** [godotengine/godot#10174] opened 2017-08-08 18:05 UTC
**Operating system or device - Godot version:**
Godot 3.0 Alpha 1

**Issue description:**

On Godot 2.1.x you could use operators on text fields, for example on the display size you could type 1920/2 and you get 960. This functionality is missing on Godot 3.0, also it would be nice if we could use the tab key and the shift+tab to go to the next field or the previous without having to press enter to confirm the value and select the next one using the mouse.

**Steps to reproduce:**

**Link to minimal example project:**

**Comment by vnen** [comment] 2017-08-08 19:55
Duplicate of  #9500.

**Closed by vnen** 2017-08-08 19:55 UTC
