### ISSUE TITLE
[4.0] "Cannot assign a new value to a constant" referring to a variable in another script

### ISSUE THREAD

**Issue by Sslaxx** [godotengine/godot#41618] opened 2020-08-30 10:33 UTC
**Godot version:** Godot Engine v4.0.dev.custom_build. db5ea78b7

**OS/device including version:** N/A for this issue

**Issue description:** After correcting the issues causing the crashes in #41597 the project was able to be imported into Godot 4.

However, attempting to run the project causes a `Cannot assign a new value to a constant` error message in scn_preload, line 12: `helper_functions._whocares = helper_functions.change_scene ("res://Scenes/testing_world.tscn")`

`_whocares` is defined in `helper_functions.gd`.

I'm uncertain if this is a bug or an intended change.

(Uncertain if this is related, but I've also noticed Godot giving `SCRIPT ERROR: Parse Error: Cannot get member "bus_index" from "[AudioStreamPlayer:144871264621]"` in `jingle_player.gd` line 43; probably similar errors with `music_player.gd` and `sound_player.gd`.)

**Steps to reproduce:** Import and try to run the project.

**Minimal reproduction project:** 
[41618_Demonstrator.zip](https://github.com/godotengine/godot/files/5146650/41618_Demonstrator.zip)

**Comment by vnen** [comment] 2020-09-01 12:53
I could not reproduce this, it might have been fixed in the latest batch.

**Closed by vnen** 2020-09-01 12:53 UTC
Labels: bug, topic:gdscript
