### ISSUE TITLE
Passing to or creating an image in C# breaks it

### ISSUE THREAD

**Issue by zaywolfe** [godotengine/godot#14820] opened 2017-12-19 07:16 UTC
**Godot version:**
3.0 beta 1

**OS/device including version:**
Linux Ubuntu 17.10

**Issue description:**
When you create an image in C# Godot spits out this error:
`Condition 'p_image.is_null()' is true`

Here's the code:

gdscript
```
func _ready():
        var worldView = get_node("Sprite");
        var img = map.get_texture();
	
	var tx = ImageTexture.new();
	tx.create_from_image(img, 16);
	worldView.set_texture(tx);
```
C#
```
      public Image get_texture() {
		Image img = new Image ();
		img.Create (width, height, false, 4);
		img.Lock ();
		
		for (int i = 0; i < width * height; i++) {
			float point = (float)get (i);
			Vector2 pos = i_to_xy (i);
			
			img.SetPixel ((int)pos.x, (int)pos.y, new Color (point, point, point));
		}

		img.Unlock ();
		return img;
        }
```
Additionally, creating an Image in gdscript  and just passing it to C# and back (without doing anything to it) also breaks it.

**Steps to reproduce:**

1. Make a script in gdscript that calls a C# method that creates and returns an image. 
2. Try to make an ImageTexture with it.
OR
1. Make a script in gdscript that creates an image and passes it to a C# method that simply returns it without modifying it.
2. Try to make an ImageTexture with it.

**Comment by akien-mga** [comment] 2018-01-18 09:23
Not critical for the upcoming 3.0 release, so moving to the next milestone. A fix can still be cherry-picked for 3.0.x maintenance releases once available in the master branch.

**Comment by akien-mga** [comment] 2019-01-19 11:36
Is this still reproducible in the current master branch?

CC @neikeq

**Comment by akien-mga** [comment] 2019-02-27 10:06
Tested on 3.1 beta 8, seems to work fine. For future reports, please provide a minimal project that can reproduce the bug, the code in the OP is not usable.

Here's the code I used:

`mynode.cs`, root node
```
using Godot;
using System;

public class MyNode : Node
{
      public Image get_image() {
        Image img = new Image();
        img.Create(16, 16, false, (Godot.Image.Format)5);
        img.Lock();
        img.SetPixel(3, 2, new Color(1.0f, 0.0f, 0.0f, 1.0f));
        img.Unlock();
        return img;
    }
}
```

`mychild.gd` child node
```
extends Node

func _ready():
	var spr = Sprite.new()
	var tx = ImageTexture.new()
	tx.create_from_image(get_parent().get_image(), 16)
	spr.texture = tx
	add_child(spr)
```

Works well, I see the texture with a single red dot.

**Comment by akien-mga** [comment] 2019-02-27 10:06
> `(Godot.Image.Format)5`

BTW I used that because I have no clue how to use Godot enums from C# :)

**Closed by akien-mga** 2019-02-27 10:06 UTC
Labels: bug, topic:mono
