### ISSUE TITLE
Cannot obtain PhysicsDirectSpaceState in GDNative

### ISSUE THREAD

**Issue by Cygon** [godotengine/godot#28574] opened 2019-05-01 15:21 UTC
**Godot version:** 3.1.1 (custom build from commit f3eafcec1a2eae021114fa12bd304668b9198af5)

**OS/device including version:** Gentoo Linux 4.19.27, KDE 5 Plasma, NVidia proprietary drivers 418.43

**Issue description:**
I am trying to do a simple raycast in C++. But whatever path I take to obtain a PhysicsDirectSpaceState, it always results in a crash here:

https://github.com/godotengine/godot/blob/master/modules/gdnative/nativescript/nativescript.cpp#L1348

Assume I had a valid, non-null `Ref<World> world` in GDNative C++:

**Attempt #1**
Segfaults at above location in `nativescript.cpp`
```
godot::PhysicsDirectSpaceState *state = world->get_direct_space_state();
```

**Attempt #2**
Segfaults at above location in `nativescript.cpp`
```
godot::RID spaceId = world->get_space();
godot::PhysicsDirectSpaceState *state = (
  godot::PhysicsServer::get_singleton()->space_get_direct_state(spaceId)
);
```

**Attempt #3**
Segfaults at above location in `nativescript.cpp`
```
const static godot::String GetDirectSpaceStateMethodName = "get_direct_space_state";
if(world->has_method(GetDirectSpaceStateMethodName)) {
  godot::Variant spaceStateAsVariant = world->call(
    GetDirectSpaceStateMethodName
  );

  // Curious: the space state reports having no method "intersect_ray"
  bool isFalse = spaceStateAsVariant.has_method("intersect_ray");

  // Triggers segfault in nativescript.cpp
  godot::Object *spaceState = godot::Object::___get_from_variant(spaceStateAsVariant);
}
```

**Comment by Cygon** [comment] 2019-05-01 15:21
I've debugged into `nativescript.cpp` and the segfault happens in the `HashMap<StringName, const void *>::get()` method:

```
TData &get(const TKey &p_key) {
  TData *res = getptr(p_key);
  ERR_FAIL_COND_V(!res, *res); // <---- This segfaults
  return *res;
}
```

So it seems that the hash table simply doesn't have the key. Is `ERR_FAIL_COND_V` supposed to segfault instead of asset when its condition fails?

**Comment by slapin** [comment] 2019-05-01 15:30
It should not segfault but the expression written there will. because you have non-null invalid pointer.
Print the value (of pointer) there, I think this is one of many GDNative bugs. Also if you do not plan to share the code I suggest just write internal engine module, it is much more predictable.

**Comment by Cygon** [comment] 2019-05-01 15:52
In `hash_map.h`, it is hitting the `return NULL` here in the `getptr()` method
https://github.com/godotengine/godot/blob/master/core/hash_map.h#L325

Then `ERR_FAIL_COND_V` segfaults with a plain `nullptr`.

That `this` pointer of 0x7fffffffcd70 for the `HashMap<StringName, const void *>` instance looks a bit suspicious, but It survives the `getptr()` call. Maybe it's segfaulting on the return, not the check...

**Comment by slapin** [comment] 2019-05-01 16:07
are you sure it is not getptr which segfaults? try adding print of res value just agter getptr line, this will work as barrier for debugger, so it will not optimize value out, so you will know if it is getptr() or macro.
Also try to print ```!res``` and ```*res``` expressions before macro to make sure it is macro and not just plain ```*res ``` segfaults.

**Comment by Cygon** [comment] 2019-05-01 16:46
It is `*res` that segfaults - inside the macro. Because it's trying to print the value in its assert message. Maybe `ERR_FAIL_NULL_V` ought to be used instead of `ERR_FAIL_COND_V` here.

![godot-segfault-hashmap](https://user-images.githubusercontent.com/3613175/57028981-d0e6bc80-6c40-11e9-8705-03f3b00bd528.png)

I think there more interesting question here is: why isn't the key (`L"BulletPhysicsDirectSpaceState"`) in the `HashMap`. And is that `0x7fffffffcd70` `this` pointer an indication that this might only be a follow-up issue and the real bug lies somewhere else? :)

**Comment by bojidar-bg** [comment] 2019-05-01 16:46
Curious: `PhysicsDirectSpaceState` is registered in ClassDB, but `PhysicsDirectSpaceStateSW` and `BulletPhysicsDirectSpaceState` aren't.

**Comment by Cygon** [comment] 2019-05-01 18:25
Still working backwards from the crash, I can get it to crash with this code, not involving `PhysicsDirectSpaceState`:

```
void ThirdPersonCameraController::process(float deltaSeconds) {
  godot::Node *cameraAsNode = get_node(this->CameraNodePath);

  godot::String class_name = cameraAsNode->get_class();
  godot::Godot::print(class_name);

  godot::Spatial *cameraAsSpatial = cast_to<godot::Spatial>(cameraAsSpatial);
  godot::Ref<godot::World> world = cameraAsSpatial->get_world();
}
```

The callstack is this:
```
Camera
handle_crash: Program crashed with signal 11
Dumping the backtrace. Please include this when reporting the bug on https://github.com/godotengine/godot/issues
[1] /lib64/libc.so.6(+0x38450) [0x7f4321d3c450] (??:0)
[2] Object::get_script_instance() const (/opt/godot-git/./core/object.h:687)
[3] /opt/godot-git/bin/godot.x11.tools.64(godot_nativescript_get_type_tag+0x2f) [0x1b401a3] (/opt/godot-git/modules/gdnative/nativescript/godot_nativescript.cpp:341)
[4] godot::Spatial* godot::Object::cast_to<godot::Spatial>(godot::Object const*) (??:0)
[5] Nuclex::CppExample::Cameras::ThirdPersonCameraController::process(float) (??:0)
```

I'm beginning to shift my suspicion to the `cast_to<>()` method, but as it essentially does nothing (both `cameraAsNode` and `cameraAsSpatial` point to the same address) it's not easy to figure out what exactly is going wrong here. I've eliminated all code except for the posted snippet in `process()`.

**Comment by karroffel** [comment] 2019-05-02 06:44
Duplicate of #28195, related PR #27936

**Comment by akien-mga** [comment] 2020-01-15 13:06
Duplicate of #28195, which is fixed.

**Closed by akien-mga** 2020-01-15 13:06 UTC
Labels: bug, topic:gdnative
