### ISSUE TITLE
Glow is not rendered when getting the viewport texture

### ISSUE THREAD

**Issue by fossegutten** [godotengine/godot#36829] opened 2020-03-05 19:10 UTC
**Godot version:**
3.2.1 RC2
GLES3 driver.

**OS/device including version:**
Windows 10
Geforce GTX 1650

**Issue description:**
Using a viewport as a render target: The cube rendered to a viewport, then to a ViewportContainer is not glowing, while the other one is. Even if HDR is enabled on the viewport, and glow is enabled on environment. Both cubes have emissive materials.

![Godot_v3 2 1-rc2_win64_r4egfvPe4B](https://user-images.githubusercontent.com/15088582/76016423-13da8600-5f1d-11ea-8348-98edc740595e.png)

**Minimal reproduction project:**
[GlowViewport.zip](https://github.com/godotengine/godot/files/4294630/GlowViewport.zip)

**Comment by clayjohn** [comment] 2020-03-05 19:43
What Tonemapping are you using?

**Comment by fossegutten** [comment] 2020-03-05 19:54
So it's not a bug? Been working on a workaround with orthographic 3D camera and rendering onto QuadMesh instead of rendering to canvaslayers. Not sure what is the best way to have several viewports with glow.

**Comment by clayjohn** [comment] 2020-03-05 20:07
Its not a bug. 

Everything you want to glow must be rendered into the 3D world. I don't know the reason you need a viewport for what your doing, so I can't tell you the best option for achieving your desired effect.

**Comment by fossegutten** [comment] 2020-03-05 20:09
Using different viewports because of drawing my game in 3 layers, and i want glow on all of them. 
FPS game where i draw weapon on top, then rest of player view, then some background stuff ontop of the Sky.

**Comment by clayjohn** [comment] 2020-03-05 20:30
Sounds like you will want to use screen aligned quads then. This tutorial should be helpful http://docs.godotengine.org/en/latest/tutorials/shading/advanced_postprocessing.html

**Comment by pwnorbitals** [comment] 2020-09-27 01:04
It looks like this issue isn’t a bug, can it be closed ? @fossegutten, did the tutorial solve the case ?

**Comment by clayjohn** [comment] 2020-09-27 01:08
Screen aligned quads should work. So I'll close this. 

If users are having trouble with the suggested approach, please ask for help on one of the community channels! :)

**Closed by clayjohn** 2020-09-27 01:08 UTC
Labels: discussion, topic:rendering
