### ISSUE TITLE
GDScript: property setters do not work with curried lambda functions

### ISSUE THREAD

**Issue by simast** [godotengine/godot#70448] opened 2022-12-22 15:41 UTC
### Godot version

v4.0.beta9.official [e780dc332]

### System information

Windows 11

### Issue description

As per the docs we can assign a function directly to a property setter:

```gdscript
var my_prop := 1.0:
	set = my_setter
```

Also the docs suggest that this can be used to "share the code across multiple properties". However this does not work with currying and lambda functions (see example in Steps to reproduce).

The reported error is:

> Parse Error: Expected end of statement after property declaration, found "(" instead.

### Steps to reproduce

Example code with the issue:

```gdscript
var prop: float:
	set = set_float_prop(&"prop")


func set_float_prop(param: StringName):
	return func (value: float):
		self[param] = value

```

### Minimal reproduction project

N/A

**Comment by KoBeWi** [comment] 2022-12-23 15:12
> share the code across multiple properties

This just means that you can assign the same function to multiple properties (although not sure how does that work).

Looks like setter expects a method identifier, not a true callable. Which means you can't use `Callable(...)` either.

**Comment by dalexeev** [comment] 2023-06-22 17:14
> Also the docs suggest that this can be used to "share the code across multiple properties".

The sentence in the docs is a bit confusing. At the moment, you can share the same setter/getter between multiple properties, but have no way of distinguishing which property it's being called on. See:

* godotengine/godot-proposals#6750
* #76665

As for argument binding, this is difficult to implement, see https://github.com/godotengine/godot-proposals/issues/6750#issuecomment-1528480656:

> Binding arbitrary arguments sounds useful, but it's probably complex to implement. Functions are not Callables, they just create Callables at runtime when referenced. So to properly call the setter/getter with binds those would need to be stored in the script and passed as arguments at runtime. If you want non-constant values it becomes more difficult because it would need to store expressions to be executed when calling. I don't think this is worth the hassle.

I suggest closing the issue, as this is not a bug, but an intentional limitation for performance reasons. There are already several proposals related to the problem.

**Closed** 2023-06-22 18:55 UTC
Labels: discussion, topic:gdscript
