### ISSUE TITLE
AnimatedSprite pixel snap issue

### ISSUE THREAD

**Issue by hedin-hiervard** [godotengine/godot#24612] opened 2018-12-26 18:50 UTC
**Godot version:**

3.1 alpha 2

**OS/device including version:**

**Issue description:**

A pixel art project using pixel snap to avoid all sorts of glitches due to floating point coords. This gives this strange and somehow unexpected behavior when using AnimatedSprites. Please see the Gif attached:
https://imgur.com/a/o77qCUG

Notice subtle sub-pixel movement of individual pixels. 

If I turn **off** pixel snap in the project settings, this fixes the issue. But this is obviously not the solution because it introduces more severe problems.

**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by KoBeWi** [comment] 2020-06-23 19:28
Can anyone still reproduce this bug in Godot 3.2.1 or any later release (e.g. [3.2.2-rc3](https://godotengine.org/article/release-candidate-godot-3-2-2-rc-3))?

If yes, please ensure that an up-to-date Minimal Reproduction Project (MRP) is included in this report (a MRP is a zipped Godot project with the minimal elements necessary to reliably trigger the bug). You can upload ZIP files in an issue comment with a drag and drop.

**Comment by KoBeWi** [comment] 2020-09-28 16:41
Closing due to lack of update. Please comment if you can still reproduce this issue in the latest stable version of Godot.

**Closed by KoBeWi** 2020-09-28 16:41 UTC
Labels: bug, topic:core
