### ISSUE TITLE
Dynamic font uninitialized

### ISSUE THREAD

**Issue by zaksnet** [godotengine/godot#57926] opened 2022-02-10 17:42 UTC
### Godot version

3.4.2.stable.mono

### System information

Windows 11

### Issue description

Fonts loaded through the new theme editor seem to be giving Dynamic font uninitialized error:
![image](https://user-images.githubusercontent.com/1850856/153464534-96f86595-4715-4705-824a-7134c3ec761b.png)
![image](https://user-images.githubusercontent.com/1850856/153464747-3f9b8c18-a8b3-43ee-8ea7-66c137b8cf59.png)
Would be nice if we could see which control the error is coming from :).
Right now the best way to resolve this is by running in verbose mode and see what loaded before the error.

### Steps to reproduce

Add a font through the new theme editor (I have only tested button so far).

**Comment by KoBeWi** [comment] 2022-04-08 17:23
Can't reproduce in 3.5. You sure your font is a valid resource? Any minimal project?

**Comment by akien-mga** [comment] 2022-04-13 10:47
I tested a bit in 3.4.2 as the OP and couldn't reproduce either with the given steps to reproduce. I tried to fiddle a bit more with things, making sure the Theme resource is actually used by a Button in the edited scene, and even when it had either an empty or an invalid DynamicFont defined, it didn't raise errors.

So closing for now as this can't be reproduced.

**Closed by akien-mga** 2022-04-13 10:47 UTC
Labels: bug, topic:editor, topic:gui

**Comment by rohanrhu** [comment] 2022-06-22 09:53
This issue is happening for my theme that is exported from Godot editor.

![image](https://user-images.githubusercontent.com/1125150/174999434-66dd6f19-939a-43de-b697-b78dd4bfe510.png)

I debugged Godot for the issue and this is where it is happening for in my theme (exported from Godot editor):
```gdresource
[sub_resource type="DynamicFontData" id=2757]
hinting = 1

[sub_resource type="DynamicFontData" id=2758]
hinting = 1

[sub_resource type="DynamicFontData" id=2759]
hinting = 1

[sub_resource type="DynamicFontData" id=2760]
hinting = 1

[sub_resource type="DynamicFontData" id=2761]
hinting = 1

[sub_resource type="DynamicFontData" id=2762]
hinting = 1

[sub_resource type="DynamicFontData" id=2763]  <-- When I debug Godot, I see it is happening for here...
hinting = 1

[sub_resource type="DynamicFont" id=2764]
size = 14
use_mipmaps = true
use_filter = true
extra_spacing_top = -1
extra_spacing_bottom = -1
font_data = SubResource( 2763 )
fallback/0 = SubResource( 2757 )
fallback/1 = SubResource( 2758 )
fallback/2 = SubResource( 2759 )
fallback/3 = SubResource( 2760 )
fallback/4 = SubResource( 2761 )
fallback/5 = SubResource( 2762 )
```

**Comment by Calinou** [comment] 2022-06-22 10:10
@rohanrhu Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

**Comment by rohanrhu** [comment] 2022-06-22 10:22
> @rohanrhu Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

Hiiiii @Calinou uploaded. Just did "Select With Data", imported Godot editor theme and saved. When I use that theme, I get this error.

[FontIssue.zip](https://github.com/godotengine/godot/files/8956693/FontIssue.zip)

I think this issue is something like "editor theme is not compatible to Godot games".

**Comment by clement-or** [comment] 2023-02-05 16:04
For anyone stumbling upon this issue in the future:

When you copy the whole editor theme, in order to avoid this error, simply delete or replace the **EditorFonts** item in the theme editor, as well as the **title_font** property in the **WindowDialog** item.

Either replace them by your own fonts or simply delete them.
This works for Godot 3.5.x
