### ISSUE TITLE
Editor docs not scrolling to correct position on search or ctrl+click of a term

### ISSUE THREAD

**Issue by donn-xx** [godotengine/godot#96515] opened 2024-09-03 08:32 UTC
### Tested versions

Noticed this since early 4.x. Still happening in latest 4.4 dev.

### System information

Godot v4.4.dev (61598c5c8) - Ubuntu 22.04.4 LTS 22.04 - X11 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 2060 (nvidia; 535.183.01) - Intel(R) Core(TM) i5-9400F CPU @ 2.90GHz (6 Threads)

### Issue description

When you ctrl+click a function in gdscript, the docs open but the help text is at the wrong position. Meaning, the function is often not even on the screen of text you get and you have to scroll or Ctrl+F to locate it. 

The same happens when one searches using F1 (or Alt+F1).

This does not happen all the time. It's hard to pin down.

### Steps to reproduce

Just play with help and watch.

### Minimal reproduction project (MRP)

None

**Comment by AdriaandeJongh** [comment] 2024-09-03 11:26
I’m also annoyed by this bug **regularly**. What does seem to help is going back to the original script and ctrl clicking the variable or method again, after which it will always scroll to the right position. So perhaps this has something to do with the script not being open yet.

**Comment by kitbdev** [comment] 2024-09-04 19:01
- looks like a duplicate of https://github.com/godotengine/godot/issues/96448

**Comment by AdriaandeJongh** [comment] 2024-09-05 08:28
> * looks like a duplicate of [Jumping to editor help does not scroll correctly sometimes #96448](https://github.com/godotengine/godot/issues/96448)

That report seems to be related to a fix introduced between 4.2 and 4.3. I've experienced the bug described in this report throughout 4.2.

**Comment by donn-xx** [comment] 2024-09-07 05:33
Just compiled from main. Opened a project, ctrl+clicked `intersect_ray` and it's a few lines into the func:
![It's off by several lines](https://github.com/user-attachments/assets/a93a91f0-c690-4fb6-bcb2-aa9b28074074)

Going back to the code, and doing it again gets it right.

I wonder if this isn't a font/line-spacing/linuxy kind of problem?

**Comment by Maran23** [comment] 2024-09-07 09:21
No it was just wrong code in Godot that is fixed in https://github.com/godotengine/godot/pull/96449.

**Comment by donn-xx** [comment] 2024-09-08 08:26
I see it's pending a review. Thanks for the fix and I'll keep en eye out to test it.

**Comment by anvilfolk** [comment] 2024-09-27 18:08
If folks from here can download the PR build artifacts and test that this fixes it w/o regressions, it's simple enough that it's likely to get merged soon! I can't replicate it or I'd test it myself!

**Comment by donn-xx** [comment] 2024-09-28 11:47
Am on v4.3.stable.official [77dcf97d8] and it's working well again. I even forgot about this issue!

**Comment by Maran23** [comment] 2024-10-18 19:18
For anyone who wants to test this, rebased the branch to master, you can download it here: https://github.com/godotengine/godot/pull/96449/checks

**Closed** 2024-11-29 21:56 UTC
Labels: bug, topic:editor
