### ISSUE TITLE
Unpredictable Behavior of MeshInstance's Generated CollisionShape

### ISSUE THREAD

**Issue by ghost** [godotengine/godot#11832] opened 2017-10-04 14:34 UTC
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Antergos x86_64 / Godot master ef08228

**Issue description:**

Situation:
- A Spatial root
    - StaticBody with MeshInstance with CubeMesh
        - CollisionShape
            A. Manually created with BoxShape 
            B. Generated by 'Create Trimesh Collision Sibling'
            C. Generated by 'Create Convex Collision Sibling'
    - RigidBody with MeshInstance with SphereMesh, positioned above the StaticBody and tilted
        - CollisionShape
            A. Manually created with SphereShape 
            B. Generated by 'Create Trimesh Collision Sibling'
            C. Generated by 'Create Convex Collision Sibling'

Expected: all collide without a drop in framerate
Happened:

Sphere\\Box|A|B|C
-|-|-|-
A|Collide as expected|Collide with expected inaccuracy|Collide as expected
B|Collide with expected inaccuracy|**No collision**|A drop in framerate for split second but collide with expected inaccuracy 
C|Framerate drop to 1\*|Framerate drop to 1\*|Framerate drop to 1\*

\* Somewhat understandable due to high number of vertices, but why is this not the case with concave shape?

**Link to minimal example project:**
[collisionshape.zip](https://github.com/godotengine/godot/files/1356135/collisionshape.zip)

**Comment by Noshyaar** [comment] 2017-11-05 09:48
Partially fixed by #12641. Using Bullet: No noticable framerate drops. But the B-B case still has no collision.

**Comment by AndreaCatania** [comment] 2017-11-05 11:15
Found it just for a case, I'll check it soon

**Comment by AndreaCatania** [comment] 2017-12-14 10:29
can you please try it now?

**Comment by raymoo** [comment] 2017-12-14 11:10
@AndreaCatania It appears the issue-opener has left

**Comment by AndreaCatania** [comment] 2017-12-14 11:28
@raymoo Thanks you! @Noshyaar can you please close it?

**Comment by Noshyaar** [comment] 2017-12-14 13:04
I was the issue opener. :P Will test soon.

**Comment by Noshyaar** [comment] 2017-12-15 06:49
Reproducible on e3fd61b, concave shapes don't collide.

**Comment by AndreaCatania** [comment] 2017-12-15 08:21
@Noshyaar The concave can be used only for static body, and doesn't work on rigid. Can you describe your scene?

**Comment by Noshyaar** [comment] 2017-12-15 08:28
If that's the case then it's solved. Hopefully it's documented somewhere.

(It's the same scene file in the description. One is rigid, another is static.)

**Comment by AndreaCatania** [comment] 2017-12-22 22:39
@Noshyaar As I said before the concave shape is not meant to be moved around either with Bullet and Godot physics, so the B-B collision never should occur.

(Even If the concave shape is moving and collide with other shapes types it's not intended to work and could have wrong behavior, also move a concave shape is an heavy process.)

If you need a moving concave shape you should build it using primitive shapes

**Comment by akien-mga** [comment] 2018-01-16 10:27
Closing as per the above (if some part of this issue still needs to be fixed, it might be better to split it into a new one).

**Closed by akien-mga** 2018-01-16 10:27 UTC
Labels: bug, topic:physics
