### ISSUE TITLE
Double-clicking identifier will select $

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#56402] opened 2022-01-01 17:02 UTC
### Godot version

bc2445d

### System information

W10

### Issue description

3.x
![wdqWW1XpxN](https://user-images.githubusercontent.com/2223172/147855826-284e9cd1-612b-45da-82ad-cc688963689f.gif)
4.0
![R7RkERCQXP](https://user-images.githubusercontent.com/2223172/147855829-70708d10-aa76-4139-a831-1dd8704bc900.gif)

### Steps to reproduce

1. Add some node path using $
2. Double click it

**Comment by Calinou** [comment] 2022-01-01 17:53
This may be done by design, but I'm not 100% sure. [The list of non-word characters used for word breaking is now configurable in the Editor Settings.](https://github.com/godotengine/godot/pull/46721)

**Comment by KoBeWi** [comment] 2022-01-01 18:07
Then the defaults should be changed probably.

**Comment by akien-mga** [comment] 2022-01-05 13:36
To me both behaviors make sense here. If you want to replace the node name not selecting `$` is useful, but if you want to copy/move the actual "reference to a node" which `$Test` is, it's convenient that it's fully selected.

This might also have been done by design for the `$` operator specifically, as this behavior doesn't reproduce in a string:

![image](https://user-images.githubusercontent.com/4701338/148226334-6d88aaeb-95b9-4c6d-856d-5588de7ab8a6.png)

CC @Paulb23 @bruvzg @vnen

**Comment by KoBeWi** [comment] 2022-06-09 00:55
The newly added `%` syntax doesn't have this issue, creating an inconsistency.

**Comment by kitbdev** [comment] 2024-06-30 17:06
- Fixed by https://github.com/godotengine/godot/pull/93656

**Closed** 2024-06-30 17:18 UTC
Labels: bug, topic:gdscript, topic:editor, usability, regression
