### ISSUE TITLE
Globals not cleared properly on game quit

### ISSUE THREAD

**Issue by Algorithmus** [godotengine/godot#4332] opened 2016-04-15 21:09 UTC
**Operating system or device:**
OSX, Windows, Linux (any really)

**Issue description** (what happened, and what was expected):
Close game by clicking OS appropriate "X" button or calling the quit signal. Expected: Game closes normally
What happened: Game crashes; malloc errors appear in the console

**Steps to reproduce:**
Put preload assets (or in an array or dictionary that contains them) in a Globals variable

For some reason, the Globals destructor is not removing these objects properly. I've seen this happen with ImageTexture and Rectangle Shape 2D objects. I had to workaround this by manually removing these objects from Global on the quit notification. Then again, I'm not sure if I'm supposed to be putting those kinds of objects in a Globals variable?

**Comment by vnen** [comment] 2016-06-09 20:24
I'm not able to reproduce this. Game closes normally without crahsing on Windows. Can someone else confirm?

**Comment by akien-mga** [comment] 2016-06-15 05:31
I was able to reproduce the crash with @Algorithmus' game, though it could be that the issue itself is not properly diagnosed yet.

This commit reproduced the bug for me on Linux X11: https://github.com/Algorithmus/CastlevaniaClone/commit/9b29eda9f2b5f28db94cb35a6bbdadad9ebac445
And it was then fixed in https://github.com/Algorithmus/CastlevaniaClone/commit/53dd7fb36f5e9916bd7ad24a8b1f26c540087092 when we identified the issue with @Algorithmus.

**Comment by Calinou** [comment] 2018-04-04 21:51
First of all thank you for your report and sorry for the delay.

We released Godot 3.0 in January 2018 after 18 months of work, fixing many old issues either directly, or by obsoleting/replacing the features they were referring to.

We still have hundreds of issues whose relevance/reproducibility needs to be checked against the [current stable version](https://godotengine.org/download), and that's where you can help us.
**Could you check if the issue that you described initially is still relevant/reproducible in Godot 3.0 or any newer version, and comment about it here?**

For bug reports, please also make sure that the issue contains detailed steps to reproduce the bug and, if possible, a zipped project that can be used to reproduce it right away. This greatly speeds up debugging and bugfixing tasks for our contributors.

Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

Thanks in advance.

*Note: This message is being copy-pasted to many "stale" issues (90+ days without activity). It might happen that it is not meaningful for this specific issue or appears oblivious of the issue's context, if so please comment to notify the Bugsquad about it.*

**Comment by Algorithmus** [comment] 2018-04-11 19:38
I don't appear to be getting this error anymore in Godot 3 on Linux.

**Closed** 2018-04-11 19:57 UTC
Labels: bug, topic:core
