### ISSUE TITLE
Renaming project cause errors and somethimes crash

### ISSUE THREAD

**Issue by Norrox** [godotengine/godot#56453] opened 2022-01-03 00:01 UTC
### Godot version

3.4.2.stable

### System information

Windows 10, GTX 1080 Ti

### Issue description

When i try to rename project a bunch of errors popping up, sometime it crashes the launcher for me.

![Skärmbild 2022-01-03 010003](https://user-images.githubusercontent.com/13393087/147892731-91b42beb-a0e2-4c6c-a820-b2c65d5a691e.png)
![Skärmbild 2022-01-03 005845](https://user-images.githubusercontent.com/13393087/147892733-e5c97792-2684-47ca-9b54-131df555ef5b.png)

### Steps to reproduce

just rename project

**Comment by Calinou** [comment] 2022-01-03 00:25
Duplicate of https://github.com/godotengine/godot/issues/25661.

**Closed by Calinou** 2022-01-03 00:25 UTC

**Comment by Norrox** [comment] 2022-01-03 01:07
Oh my, why can't i ever find these issues when i search for them -.- well well sorry for the extra work :S
