### ISSUE TITLE
Can't assign members to an exported array (of Node3D) in inspector

### ISSUE THREAD

**Issue by Jamsers** [godotengine/godot#70086] opened 2022-12-15 02:08 UTC
### Godot version

4.0.beta8.official

### System information

Windows 11 22H2, GTX 1650 Mobile, NVIDIA Driver 527.37, Vulkan

### Issue description

I exported an array of Node3D in my script and expected to be able to assign their members in the inspector.

![image](https://user-images.githubusercontent.com/39361911/207754984-5811d16a-64d9-4644-aaf1-d79e6a967df2.png)

But I cannot. I've tried drag and dropping, and I've tried clicking on the assign button and selecting a Node3D in the popup, neither works. The array elements stay empty in the inspector, and I've confirmed the array itself is also empty at runtime.

### Steps to reproduce

Export a typed array in script (Preferably some built in object class like Node3D).
Try to assign the members of the array in the inspector.

### Minimal reproduction project

[TypedArrayExport.zip](https://github.com/godotengine/godot/files/10233105/TypedArrayExport.zip)

**Comment by Calinou** [comment] 2022-12-15 03:14
Duplicate of https://github.com/godotengine/godot/issues/62916.

**Closed by Calinou** 2022-12-15 03:14 UTC
