### ISSUE TITLE
Polygon UV strange behaviour

### ISSUE THREAD

**Issue by HeartoLazor** [godotengine/godot#2552] opened 2015-09-29 06:22 UTC
Hey I'm playing a bit with polygon uv and I'm trying to do something this:
![Image](http://i.imgur.com/ygNo6pO.png)
So I setup a texture on repeat mode and the uv like this
![Image](http://i.imgur.com/hugxwAn.png)
and on scene I shifted the two bot/top mid points and the result is this:
![Image](http://i.imgur.com/rAbfCfC.png)
That is a weird result, On my head I expect something like the first image, So this is a bug?

For what could be useful the fix if this is a bug:
Roads, Lasers and maybe plasma beams/water beams if the engine let to shift uv from code

**Comment by bojidar-bg** [comment] 2015-09-29 08:38
The thing which happens is that the polygon is triangulated (so it will be sent to GPU), and one of the triangles doesn't look too good.

The best thing you can do is subdivide all sides, so triangles are correct.

**Comment by bojidar-bg** [comment] 2015-09-29 08:43
But still... it is very hard to get the needed result, as triangulation does all kinds of abrupt things... Maybe custom triangulation is the only way to go ...

**Comment by guilhermefelipecgs** [comment] 2015-09-29 12:57
With visual edit it's very hard to achieve this (because we can edit UV), but if you code you can generate the correct UV for this.
look at this code made by @LeonardMeagher2
https://github.com/LeonardMeagher2/Godot-Assets/blob/master/Scenes/2DTrail.gd
he made a trail that is exactly effect you want.

**Comment by HeartoLazor** [comment] 2015-09-29 20:40
Oh nice that scene could be what I'm looking for, I will look at it.
On reality the effect I want to achieve is an animated plasma beam with curves for homming plasma beam.
The animated beams on this video, but with curves:
https://gfycat.com/GlaringExaltedEthiopianwolf

So my first approach is to implement something like a algorithm for roads based on polygons and shift the uv for the beam effect.
I don't know if i could achieve that effect with another tool or plugin on godot, so if the polygon 2d with shifting uv isn't enough, my next approach is to create a module or a new node2d directly on godot for roads.

**Comment by guilhermefelipecgs** [comment] 2015-09-29 21:42
Clarifying a bit more for those interested.
What you want:
![target](https://cloud.githubusercontent.com/assets/1387165/10178946/4a7f4858-66d9-11e5-942a-d1efb1a3e002.png)
What Godot generated:
![get](https://cloud.githubusercontent.com/assets/1387165/10178944/47cc3ee0-66d9-11e5-837e-3c7102e7fc78.png)

**Comment by HeartoLazor** [comment] 2015-10-10 01:53
I got it working.
Looking at example on top the trick is make quads from two triangles and not a quad directly, so if somebody want the solution for this problem, here is an example for drawing a texture of 32x8 correctly on polygon without distortion:
first triangle:
0:   0,0
1:   0,8
2: 32,0
second one:
3:   0,8
4: 32,8
5: 32,0
and apply to uv and vertices from your polygon.
This is the result of my first approach:
connected points on space from a bezier + polygon + texture on repeat mode
https://gfycat.com/BrownShorttermKiwi
I don't know if exist another more optimal approach for achieve that on 2d with raycast collision on the whole laser, this one is somewhat slow.
Something like: https://wiki.unrealengine.com/Beam_Particle_(Tutorial)

**Comment by MarianoGnu** [comment] 2015-10-11 20:56
@reduz this is what you meant by implementing tessellation right?

**Comment by reduz** [comment] 2015-10-11 22:28
Tesselation already works. What I meamt is adding internal edge hints to
male tesselation work as intended

**Comment by HeartoLazor** [comment] 2015-10-11 22:49
So tessellation is related or not with the best solution for what I'm trying to do?

**Comment by reduz** [comment] 2015-10-11 23:22
What is missing is tesselation hints, to ensurr polygons are always
generated the way you intend them

**Comment by HeartoLazor** [comment] 2015-10-11 23:46
If I'm understanding you. Somewhere on godot c++ source code, there is a draw routine without flags like TESSELLATION_XXX_ON and with that I could create the example from top with quads (4 points) directly vs two triangles (6 points)?
As you see on the first attempt I finished an implementation of what I'm looking for, but is somewhat slow (< 60 fps with app 25 plasma nodes with 10 divisions and raycast collision, all uv/polygon mapping is calculated on ready only one time)
So I'm still unsure if this is the fastest approach on godot for homing plasma beams with variable size and shape + collision.

**Comment by MarianoGnu** [comment] 2015-10-12 13:45
What is missing is a way tu subdivide the polygon in the UV editor to make Godot draw sub-polygons instead.
The real reason to implement these hints is to implement polygon deformation using a 2D Skeleton, but i think this should solve you problem too.

**Comment by MarianoGnu** [comment] 2015-10-12 14:12
@HeartoLazor take a look to how Spine solves it in the "meshes" overview:

http://es.esotericsoftware.com/spine-in-depth

**Comment by akien-mga** [comment] 2018-11-23 13:19
Is this still reproducible in the current master branch? If so a test project would be convenient.

**Comment by akien-mga** [comment] 2020-07-26 22:48
No answer, so closing.

**Closed by akien-mga** 2020-07-26 22:48 UTC
Labels: enhancement, topic:editor
