### ISSUE TITLE
WorldEnvironment node completely breaks Android apps

### ISSUE THREAD

**Issue by jonchoo** [godotengine/godot#21064] opened 2018-08-16 06:36 UTC
**Godot version:**
3.0.6.stable

**OS/device including version:**
Android Device : Motorola MotoE2

**Issue description:**
App runs fine until a WorldEnvironment node is added. Have tried placing the node in different parts of the tree. The Android app crashes in different ways depending on what options are enabled in the WorldEnvironment node (eg. glow).

**Steps to reproduce:**
Add a WorldEnvironment node to a scene and attempt to run on an Android device.

**Minimal reproduction project:**
[WorldEnvironment Android bug.zip](https://github.com/godotengine/godot/files/2292610/WorldEnvironment.Android.bug.zip)

**Comment by bojidar-bg** [comment] 2018-08-16 06:58
This is probably the result of poor OpenGLES 3 support, which would probably be resolved by the GLES2 renderer comming for 3.1.

Would be nice to get someone test it on different devices, to confirm it is not a bug in the GLES3 renderer.

**Comment by bojidar-bg** [comment] 2018-08-20 11:52
Ok, then.. a logcat output would be useful (especially the backtrace).

**Comment by KoBeWi** [comment] 2020-06-18 20:52
Sooo the GLES2 support is already added, so this is probably resolved.

**Closed by KoBeWi** 2020-06-18 20:52 UTC
Labels: bug, needs testing, platform:android
