### ISSUE TITLE
Cartesian coordinate system - choosing 3d axes for project

### ISSUE THREAD

**Issue by Yazir** [godotengine/godot#8946] opened 2017-05-27 00:27 UTC
It would be great to be able to change axes for the whole scene.

Currently 3d axes are
x, z - position on cartesian plane
z - height

In game development it is more common to see xyz order than the current xzy one. It would make working on vectors easier and making it changeable would make it compatible with previous projects.

The con is that coordinate based scripts won't work without changes after copying code to project with different cartesian coordinate axis order.

**Comment by toger5** [comment] 2017-05-27 03:07
I also prefer xy and z for height.
Especially because blender will be used a lot in combination with godot....
I thibk maiing it changable is bad. Just leads to confusion. But also changing it migt be to mich work for a personla preferences topic.

**Comment by n-pigeon** [comment] 2017-05-27 09:45
I can already tell you that this is not likely to happen.
It would conflict with API Godot internals and so on.

Best practice is to get used to that sometimes Z and Y in 3D applications are swapped and learn to memorize that AppA is Zup, AppB is Yup :)
Life is easier then... I'm speaking from experience.......

**Comment by Yazir** [comment] 2017-05-27 11:56
I use both vector2 and vector3 so it leads to confusion when constructing vector3(x,z,z2), but I uderstand what it would take to change it.

**Comment by kubecz3k** [comment] 2018-04-04 16:25
First of all thank you for your report and sorry for the delay.

We released Godot 3.0 in January 2018 after 18 months of work, fixing many old issues either directly, or by obsoleting/replacing the features they were referring to.

We still have hundreds of issues whose relevance/reproducibility needs to be checked against the [current stable version](https://godotengine.org/download), and that's where you can help us.
**Could you check if the issue that you described initially is still relevant/reproducible in Godot 3.0 or any newer version, and comment about its current status here?**

For bug reports, please also make sure that the issue contains detailed steps to reproduce the bug and, if possible, a zipped project that can be used to reproduce it right away. This greatly speeds up debugging and bugfixing tasks for our contributors.

Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

Thanks in advance.

*Note: This message is being copy-pasted to many "stale" issues (90+ days without activity). It might happen that it is not meaningful for this specific issue or appears oblivious of the issue's context, if so please comment to notify the Bugsquad about it.*

**Comment by toger5** [comment] 2018-04-05 13:15
I think the main reason to initially use y up, is that this is the open gl api standart (as far as i know).

If the renderer gets recoded using vulcan, would it be possible to also change the coordinate system?

**Comment by Noshyaar** [comment] 2018-04-05 13:31
According to reduz, the coordinate system is not going to be changed, and it's not worth it to make it an option. Since it's too unlikely to happen, we're closing the issue.

```
<reduz> not going to change, one has to stick to those decisions until the end.. look at Unreal, which uses the least standard system of all (Tim Sweeney actually apologized :P )
<reduz> and making it configurable is too much hassle for no benefit
```

https://github.com/godotengine/godot/issues/17872#issuecomment-377691846

**Closed by Noshyaar** 2018-04-05 13:31 UTC
Labels: discussion, feature proposal, topic:rendering
