### ISSUE TITLE
area_exited signal is emitted before the body is erased from overlapping_areas array

### ISSUE THREAD

**Issue by IndieQuest** [godotengine/godot#43036] opened 2020-10-23 13:26 UTC
Godot version:**
Godot version 3.2.2

**OS/device including version:**
Windows, Nvidia GeForce 1070, driver version: 456.71, GLES3

**Issue description:**
When I print/test the return value of `get_overlapping_areas()` function of an `Area` node right when the `area_exited` signal is called
the body that just left the area is still in the `overlapping_areas` array. Important note, adding a manual pause before the print/test solves the problem. I went to the `Area` implementation in the repository and it seems that the signal [can not be emitted](https://github.com/godotengine/godot/blob/master/scene/3d/area_3d.cpp#L370) before the [area is erased](area_map.erase(E);). I will be happy to dive deeper with some guidance about how to tackle the event system. 

**Steps to reproduce:**
Connect the `area_exited` signal of an `Area` node to a function that prints the results of `get_overlapping_areas()`

**Minimal reproduction project:**
[Godot RTS.zip](https://github.com/godotengine/godot/files/5429633/Godot.RTS.zip)

****

**Comment by madmiraal** [comment] 2020-10-26 10:08
Duplicate of #42494, fixed in #42513 and in 3.2 with #42514, so included in [3.2.4.beta1](https://godotengine.org/article/dev-snapshot-godot-3-2-4-beta-1).

**Closed by madmiraal** 2020-10-26 10:08 UTC
Labels: bug, topic:physics
