### ISSUE TITLE
Handling isometric-cartesian coordinates maths.

### ISSUE THREAD

**Issue by thomasbaijot** [godotengine/godot#7094] opened 2016-11-11 08:32 UTC
Lot of people wants to make iso games but get lost with maths to switch cartesians/isometrics coordinates.
Could next Godot release handle this with functions like CartToIso() IsoToCart() ?
Resource for this request : https://gamedevelopment.tutsplus.com/tutorials/creating-isometric-worlds-a-primer-for-game-developers--gamedev-6511
Thanks for the answer. 😊

**Comment by bojidar-bg** [comment] 2016-11-11 09:37
There are many, many isometric projections in existence -- godot cannot possibly handle all of them with "just one function". (See https://commons.wikimedia.org/wiki/File:Graphical_projection_comparison.png)

This being said, it isn't too hard to make a Matrix32/Transform with would map said coordinates to and fro.

Here is an example (disregards height (z-value) completely):
```
onready var iso_to_cart = Matrix32().scaled(Vector2(1, 0.5)) * Matrix32(PI/4, Vector2())
# Scale a transformation then rotate it (or maybe rotate then scale, not sure how it worked exactly..)
onready var cart_to_iso = tile_to_world.affine_inverse()
# Inverse

# Usage
func mouse_to_tile():
  return cart_to_iso * get_global_mouse_pos()
```

**Comment by Noshyaar** [comment] 2018-04-08 03:09
First of all thank you for your report and sorry for the delay.

We released Godot 3.0 in January 2018 after 18 months of work, fixing many old issues either directly, or by obsoleting/replacing the features they were referring to.

We still have hundreds of issues whose relevance/reproducibility needs to be checked against the [current stable version](https://godotengine.org/download), and that's where you can help us.
**Could you check if the issue that you described initially is still relevant/reproducible in Godot 3.0 or any newer version, and comment about it here?**

For bug reports, please also make sure that the issue contains detailed steps to reproduce the bug and, if possible, a zipped project that can be used to reproduce it right away. This greatly speeds up debugging and bugfixing tasks for our contributors.

Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

Thanks in advance.

*Note: This message is being copy-pasted to many "stale" issues (90+ days without activity). It might happen that it is not meaningful for this specific issue or appears oblivious of the issue's context, if so please comment to notify the Bugsquad about it.*

**Comment by aaronfranke** [comment] 2018-08-25 00:36
Would anyone else be interested in this feature? It would be engine bloat to add it if only one person wanted it.

@bojidar-bg If it were up to me, I'd implement "Dimetric Axonometric" which seems to be a more general form of "Isometric Axonometric" that lets people choose the viewing angle.

**Comment by Zireael07** [comment] 2018-08-25 07:50
A generic transform function that would allow choosing the viewing angle would be the way to go I believe.

Yes, Godot has isometric mode for tilemap (aside: how does it transform? maybe reuse it's functions?) and an ability to angle an orthographic camera, but some people will still want to implement isometry the oldfashioned way.

**Comment by AaronCRobinson** [comment] 2019-01-14 20:34
I am interested in this feature. I `world_to_map` and `map_to_world` seem incomplete in that they lack this functionality while the tilemap can be set to isometric or even custom. As such these methods fail at providing correct data when the TileMap is configured in fairly standard ways (e.g. a non-custom stetting).

**Comment by pcvonz** [comment] 2019-02-05 02:08
I agree with @AaronCRobinson. `map_to_world` and `world_to_map` are a little misleading if you're trying to get the size of an Isometric Tilemap.

**Comment by akien-mga** [comment] 2020-05-26 11:22
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!

**Closed by akien-mga** 2020-05-26 11:22 UTC
Labels: discussion, feature proposal, topic:core
