### ISSUE TITLE
Thread.new() returns null, start() not working

### ISSUE THREAD

**Issue by Hannyson** [godotengine/godot#50860] opened 2021-07-25 16:20 UTC
### Godot version

4.0-dev

### System information

Arch Linux

### Issue description

I got this error when I try to start a thread after a Thread.new()

E 0:00:00:0840   is_type_compatible: Parser bug (please report): Trying to check compatibility of unset value type
  <Erreur C++>   Condition "!p_source.is_set()" is true. Returning: true
  <Source C++>   modules/gdscript/gdscript_analyzer.cpp:3459 @ is_type_compatible()

### Steps to reproduce

Declare a new Thread with Thread.new(), launch a start()

**Comment by Calinou** [comment] 2021-07-25 18:13
Duplicate of https://github.com/godotengine/godot/issues/44375.

**Closed by Calinou** 2021-07-25 18:13 UTC
Labels: bug, topic:core
