### ISSUE TITLE
y-axis flickers

### ISSUE THREAD

**Issue by gitscher** [godotengine/godot#65969] opened 2022-09-17 07:33 UTC
### Godot version

4.0 beta 1  Vulkan

### System information

Windows 10 64bit, i7-7700k, RTX 3080

### Issue description

y-axis flickers in standard settings when camera is moved
![y-axis flickers1](https://user-images.githubusercontent.com/94169968/190845809-ea191d18-2dd2-4fe5-98b7-332e717895ab.png)
![y-axis flickers2](https://user-images.githubusercontent.com/94169968/190845811-1570bf35-d429-4982-afdc-70464d91396e.png)

### Steps to reproduce

start and move the camera in the viewport
all 4.0 alphas and beta

### Minimal reproduction project

default settings

**Comment by Zireael07** [comment] 2022-09-17 08:18
Already reported. IIRC it only flickers when viewport is odd sized

**Comment by groud** [comment] 2022-09-17 12:08
Duplicate of https://github.com/godotengine/godot/issues/37016

**Closed** 2022-09-17 12:08 UTC
