### ISSUE TITLE
Somewhat wrong looking C# warning at startup.

### ISSUE THREAD

**Issue by LATRio** [godotengine/godot#21933] opened 2018-09-10 12:30 UTC
**Godot version:** 3.1 -df39a03

**OS/device including version:** Windows 10 x64

**Issue description:**

![default](https://user-images.githubusercontent.com/7885573/45297432-4da51900-b540-11e8-92c2-fb46e9973a48.png)

**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by Zireael07** [comment] 2018-09-10 12:46
Good to have the issue officially reported (I saw the screenshot in a comment to another issue)

**Comment by neikeq** [comment] 2018-09-10 21:55
That C# warning dialog at startup is a new feature and is considered a work in progress.

**Comment by akien-mga** [comment] 2018-09-11 08:56
It can likely be fixed for that dialog by setting a minsize, but since it worked fine previously, it hints at a regression in AcceptDialog code.

**Comment by akien-mga** [comment] 2018-09-11 15:19
This is likely the same bug as #21975 which is more generic, so closing as duplicate.

**Comment by piratesephiroth** [comment] 2018-09-18 18:01
That happens because  `Control::SIZE_EXPAND_FILL` ignores `set_autowrap`.
It's resizing the control height properly according to the original strings.

Look what happens if I comment out the `set_autowrap `line

![bug](https://i.imgur.com/w0ruLQq.png)

**Comment by akien-mga** [comment] 2018-09-19 06:29
Reopening as it might not be exactly the same as #21975.

Again, this is a *regression*, it used to work fine when this dialog was implemented and up until 2 or 3 weeks ago. Bisecting would be more helpful than hiding the issue with additional min size or manual wrapping.

**Comment by akien-mga** [comment] 2018-09-19 13:00
> Again, this is a *regression*, it used to work fine when this dialog was implemented and up until 2 or 3 weeks ago.

Well my "2-3 weeks" estimate was misguided, I'm currently down to a mid-July commit which still exhibits the bug. I can confirm however that Godot 3.0.6 does not have the bug, so some regression happened in the master branch.

**Comment by akien-mga** [comment] 2018-09-19 15:07
Bisectedn b2e78e11 caused the regression.
```
b2e78e117ca5560f5b9290b2f333d054b9756a3e is the first bad commit
commit b2e78e117ca5560f5b9290b2f333d054b9756a3e
Author: Guilherme Felipe <guilhermefelipecgs@gmail.com>
Date:   Sat Jun 30 21:36:54 2018 -0300

    Fix performance for godot's interface

:040000 040000 360dc00c3391e9d14a5fdd1d01ce78cd58d2f382 d5f5c8f9387f87843e63ee54e8cd9ab8c6216855 M      scene
```
CC @guilhermefelipecgs

**Closed** 2018-09-19 18:04 UTC
Labels: bug, topic:core
