### ISSUE TITLE
AudioStreamPlayer3D pops when sound is played rapidly

### ISSUE THREAD

**Issue by sketchyfun** [godotengine/godot#58901] opened 2022-03-08 13:27 UTC
### Godot version

3.5.beta.custom_build [721d408cc]

### System information

Windows 10, Ubuntu 18.04

### Issue description

When playing a sound effect in rapid succession (every 0.2 seconds, for example), a popping noise can be heard at the beginning of the playback. If a regular AudioStreamPlayer is used, everything is fine, so it doesn't appear to be an issue with the sound file itself.

I've seen some previous tickets about this issue, but they were closed as the issue was supposedly fixed, but if you try the attached example project, you'll see that the issue still persists.

### Steps to reproduce

Download the attached project and run the main scene to hear the repeating audio clip and the popping that occurs.

### Minimal reproduction project

[audio_pop.zip](https://github.com/godotengine/godot/files/8206533/audio_pop.zip)

**Comment by Calinou** [comment] 2022-03-08 15:12
Duplicate of https://github.com/godotengine/godot/issues/22016. I reopened that issue.

**Closed by Calinou** 2022-03-08 15:12 UTC
Labels: bug, topic:audio, topic:3d
