### ISSUE TITLE
WASM export not processing network events when tab loses focus

### ISSUE THREAD

**Issue by BoomerDev** [godotengine/godot#55886] opened 2021-12-12 23:17 UTC
### Godot version

3.3.2.stable

### System information

Windows 10, GLES2, GeForce RTX 2060

### Issue description

I am creating a 2D top-down shooter in Godot 3.3 for the web, and I noticed that when a client switches tabs (or when the tab loses focus) the engine is no longer processing RPCs. This completely messes up the game as it's a real-time shooter. Please help :(

### Steps to reproduce

None

**Comment by Calinou** [comment] 2021-12-13 00:06
Duplicate of https://github.com/godotengine/godot/issues/37031.

**Closed by Calinou** 2021-12-13 00:06 UTC

**Comment by BoomerDev** [comment] 2021-12-13 00:29
@Calinou has it been solved though?

**Comment by Calinou** [comment] 2021-12-13 00:30
> @Calinou has it been solved though?

No, it's a known limitation that currently has no workaround.
