### ISSUE TITLE
Cannot rename folder,scene,script,resource when only changing to lower/upper case

### ISSUE THREAD

**Issue by AnJ95** [godotengine/godot#41508] opened 2020-08-25 14:19 UTC
**Godot version:**
3.2 stable

**OS/device including version:**
macOS Catalina 10.15.5

**Issue description:**
Possibly related to [19592](https://github.com/godotengine/godot/issues/19592), but renaming any file by only changing the character case is not possible. It says, the file already exists.
I don't think this is OS related, but i'm not sure.

**Steps to reproduce:**
Create any folder, scene, script or resource, right click, rename then change one character to upper/lower case.

**Comment by akien-mga** [comment] 2020-08-25 16:34
Duplicate of #19592.

**Closed by akien-mga** 2020-08-25 16:34 UTC
