### ISSUE TITLE
Layout widget is not displayed if Control is a child of a Viewport node

### ISSUE THREAD

**Issue by kubecz3k** [godotengine/godot#3572] opened 2016-02-03 13:50 UTC
If we put Control node as a child of 'Viewport' node then helper widget with predefined 'Anchor' properties is not displayed.
video: https://youtu.be/gwzitLsVCAY

**Comment by DualMatrix** [comment] 2018-09-16 14:49
Still relevant in master. "Anchor" has changed to "Layout", but it still won't appear.

**Comment by KoBeWi** [comment] 2020-07-08 00:38
Still valid in d0e0a19

Might be related to #20619 somehow

**Comment by KoBeWi** [comment] 2020-09-29 11:13
I investigated this issue a bit and the cause is this:
https://github.com/godotengine/godot/blob/aed16c8f84b67626b9a989ef24284fb92d569814/editor/plugins/canvas_item_editor_plugin.cpp#L830-L838
Particularly this part:
```
canvas_item->get_viewport() == EditorNode::get_singleton()->get_scene_root()
```
The editor checks if all selected CanvasItems are controls and shows the widget, but if the nodes are in sub-viewport, they aren't listed in the selection. I removed this condition, which resulted in this:
![image](https://user-images.githubusercontent.com/2223172/94550916-d345af80-0254-11eb-8c83-c854c200e940.png)
You can select the nodes now in the Scene Tree and the selection appears in the editor, but since the nodes are in another viewport, they aren't visible. You can move them, but you can't see them nor select by clicking. This makes the Layout widget useless.

IMO even it if looks like a bug, it can't be solved properly until #20619 is resolved. I will just close this issue and leave a note in the other one.

**Closed by KoBeWi** 2020-09-29 11:13 UTC
Labels: bug, confirmed, topic:editor

**Comment by elvisish** [comment] 2021-10-09 22:13
Is this fixed yet?

**Comment by KoBeWi** [comment] 2021-10-09 22:18
No.
