### ISSUE TITLE
Engine hangs when trying to preload a resource from script starting with OS reserved names

### ISSUE THREAD

**Issue by Xrayez** [godotengine/godot#20110] opened 2018-07-12 10:02 UTC
**Godot version:**
3.0+, 4.0+

**OS/device including version:**
Windows 10 1803 build 17134.165

**Issue description:**
I have tried to preload a script `condition.gd` using relative path:

![gif](https://user-images.githubusercontent.com/17108460/42625785-519f87dc-85d1-11e8-9044-95b308646102.gif)

```gdscript
const Condition = preload("con 
# engine hangs after `con` is typed
```

After that the engine hangs (no crash), with the following output (master, in official just hangs the engine)
```
WARNING: _open: Case mismatch opening requested file 'con.remap', stored as 'con' in the filesystem. This file will not open when exported to other case-sensitive platforms.
     At: drivers/windows/file_access_windows.cpp:102
```
The issue is most likely related to the fact that parser tries to manipulate OS [reserved names](https://docs.microsoft.com/en-us/windows/desktop/fileio/naming-a-file) as pointed by [KellyThomas](https://github.com/godotengine/godot/issues/20110#issuecomment-404477478)

**Workaround:**
![gif2](https://user-images.githubusercontent.com/17108460/42626542-46d7d1c2-85d3-11e8-89e7-693439532a4f.gif)

😄

**Minimal reproduction project:**
[con-preload-hang.zip](https://github.com/godotengine/godot/files/2188067/con-preload-hang.zip)

**Comment by KellyThomas** [comment] 2018-07-12 11:13
Probably related to:

> Do not use the following reserved names for the name of a file:

> CON, PRN, AUX, NUL, COM1, COM2, COM3, COM4, COM5, COM6, COM7, COM8, COM9, LPT1, LPT2, LPT3, LPT4, LPT5, LPT6, LPT7, LPT8, and LPT9. Also avoid these names followed immediately by an extension; for example, NUL.txt is not recommended.

https://docs.microsoft.com/en-us/windows/desktop/fileio/naming-a-file

**Comment by Xrayez** [comment] 2018-07-12 12:11
@KellyThomas seems like it, tested on names like `com1`, `aux` ... same hang.

**Comment by akien-mga** [comment] 2018-07-18 13:48
So how should we fix this, blacklist all filenames starting with those strings in FileAccess? I fear it may hurt performance if each file access requires comparing to 20 strings or so.

**Comment by eon-s** [comment] 2018-07-18 15:58
But why completion fires the issue? Is really weird.
Maybe on load/preload and on windows, it can avoid trying to autocomplete the first 3 characters if starts with those combinations.

**Comment by reduz** [comment] 2018-09-07 19:21
this kinda sucks, i wonder where should we avoid this

**Comment by dragmz** [comment] 2019-02-11 07:38
Also hangs for names like "con.txt" and "con "

**Comment by hpvb** [comment] 2019-02-12 21:38
We can explicitly tell the Win32 apis we want files by prefixing all types with '\\?\'. This will let a particular string straight through to the windows file apis without going through the other namespaces so \\?\c:\con is fine.

**Comment by akien-mga** [comment] 2019-02-12 21:50
@hpvb That sounds like an interesting option.

Whatever fix we choose, we must ensure that it doesn't make cross-platform dev and export more cumbersome. The proposed fix in #25805 would imply that some names can't be used while on Windows, but you can use them while on Linux and export a broken Windows build, which isn't good.

**Comment by hpvb** [comment] 2019-02-12 21:53
@akien-mga if we use the explicit 'file namespace' prefix in Windows you *can* use names like 'con' just fine.

**Comment by dragmz** [comment] 2019-02-13 06:51
@hpvb Sure that's another alternative however using explicit namespace to create files with reserved names on windows (e.g. "\\.\c:\con.txt") makes them hard to manage (e.g. Windows Explorer cannot move or delete such files) so it has its own cons.

**Comment by hpvb** [comment] 2019-02-18 16:04
In my opinion the issue is that of the typeahead prediction. There are other programs that let you create unfortunate names. Short of testing all filenames saved against a blacklist there's not a lot that can be done. And this is a separate issue in my opinion.

**Comment by akien-mga** [comment] 2019-05-29 14:16
So how should we proceed with this issue?

It sounds like #25805 will not be merged, so should we close it? And if so, what solution should be favored?

IMO we can try @hpvb's proposal, or have a list of forbidden names for cross-platform support... but that feels pretty hacky.

**Comment by eon-s** [comment] 2019-05-29 20:22
The fix do not need to be cross platform because is a platform specific bug, the `\\` solution seems simple enough for windows.

**Comment by akien-mga** [comment] 2019-05-30 05:10
Well Godot's behaviour does need to be the same cross platform. Currently you can create a "con" file on Linux, then switch to Windows and get problems (either you or a fellow Dev via VCS). So if one platform has filename limitations, the other platforms which can create files need to take it into account.

But if we lift the limitation with @hpvb's proposal, it should be ok.

**Comment by Grandro** [comment] 2022-03-22 12:30
I wanted to mention the same thing happens for 'Con' when using extends with a file path, couldn't reproduce it with any other reserved name tho. Is that worth opening a new issue?

**Comment by mhilbrunner** [comment] 2022-03-22 12:35
> We can explicitly tell the Win32 apis we want files by prefixing all types with `\\?\`. This will let a particular string straight through to the windows file apis without going through the other namespaces so `\\?\c:\con` is fine.

Doesn't this in effect result in Godot creating files that are problematic to handle with other, non-prefix-aware programs?

**Comment by KoBeWi** [comment] 2022-04-25 00:53
Tested in e80aedb (4.0 alpha 6+) and it doesn't seem to freeze anymore.
Can someone confirm it's fixed?

**Comment by akien-mga** [comment] 2022-04-25 14:28
CC @godotengine/windows. I don't remember us doing any specific fixes for this but maybe resource loading changes in a way that prevents this issue (or maybe Windows 10 became more clever).

**Closed** 2023-01-21 10:35 UTC
Labels: bug, platform:windows, topic:core, topic:gdscript, topic:editor, confirmed
