### ISSUE TITLE
The right side of the interface extends beyond the screen when there are a lot of editors below

### ISSUE THREAD

**Issue by JekSun97** [godotengine/godot#97161] opened 2024-09-18 20:19 UTC
### Tested versions

4.3 stable, 4.4 dev2

### System information

Godot v4.3.stable - Windows 10.0.19045 - Vulkan (Forward+) - dedicated Radeon RX 560 Series (Advanced Micro Devices, Inc.; 31.0.14001.45012) - Intel(R) Core(TM) i5-4570 CPU @ 3.20GHz (4 Threads)

### Issue description

When I have a lot of elements at the bottom of the editor, the whole interface of the right side of the editor together with the inspector goes off the screen, maybe we should add a tab switcher with left and right arrows?

I can also see errors in the output:
`
  Can't add child 'Control' to '@VBoxContainer@6642', already has a parent '@VBoxContainer@6642'.`

Screen resolution: 1600x900

![err](https://github.com/user-attachments/assets/ac21de0c-f0f6-464a-8625-4d5c848f232c)

### Steps to reproduce

1. Open MRP
2. Enable the plugin and restart the project
3. Errors, as well as the right side of the screen goes beyond the screen if your screen is not wide enough

### Minimal reproduction project (MRP)

[mrp.zip](https://github.com/user-attachments/files/17049918/mrp.zip)

**Comment by tetrapod00** [comment] 2024-09-18 20:36
Duplicate of https://github.com/godotengine/godot/issues/95681. But your MRP may be better than the one I made since it represents a realistic use case of many small names rather than few large ones.

**Comment by WhalesState** [comment] 2024-09-18 21:02
We can use a `TabBar` which i don't think will be ideal for fixing this.

Or a `ScrollContainer` and hiding it's horizontal scroll bar while also allowing focusing the buttons to enable `ScrollContainer` follow focus.

Or an `OptionButton` like how blender deals with docks.

Or an `HFlowContainer` which also may not be ideal since it will keep increasing it's vertical size when we resize down the window width.

**Comment by tetrapod00** [comment] 2024-09-18 21:08
@WhalesState This will probably be consolidated into the older issue, so your comment might get lost in this issue

**Comment by AThousandShips** [comment] 2024-09-20 15:49
Thank you for your report, consolidating in:
* https://github.com/godotengine/godot/issues/95681

Please add your MRP there for more details

**Closed by AThousandShips** 2024-09-20 15:49 UTC
