### ISSUE TITLE
Editor becomes unresponsive when using TileSet with many tiles

### ISSUE THREAD

**Issue by Krumelur** [godotengine/godot#24789] opened 2019-01-05 15:38 UTC
**Godot version:**
Godot 3.1 Alpha 4

**OS/device including version:**
macOS Mojave

**Issue description:**
Mac is a 6-core i7 with 32GB of RAM and SSD.

Please see video for details on the process:
https://www.youtube.com/watch?v=ORoup29SUcc

I'm using a tile set with 363 individual tiles (PNG, 16x16 pixels).
The tiles were added to a scene and the scene imported into the TileSet editor (by the way: notice how the tiles are not displayed correctly - they are stretched?).
The editor adds them without issues.
However, when opening the editor the next time, it gets stuck to a point where the UI is only partially functional. It's not that it is _slow_, it is _broken_. 

**Steps to reproduce:**
Create a big tile set :-)
Actually, using 230 tiles still works but with 240 the UI becomes unresponsive.

**Minimal reproduction project:**
https://github.com/Krumelur/GodotTesting/tree/godot31_issue_24789

**Comment by qarmin** [comment] 2019-01-05 18:16
On Linux Mint 19 with Intel HD 3000 I have this never ending errors in terminal:
```TOTAL BYTES: 1048560
NULL count: 11
CALL _update_callback: 28709
CALL _update_minimum_size: 240
CALL _sort_children: 14717
CALL _update_script_names: 1
CALL _test_update_tree: 9
CALL _select_file: 1
CALL _update_bone_list: 1
ERROR: push_call: Message queue out of memory. Try increasing 'message_queue_size_kb' in project settings.
   At: core/message_queue.cpp:56.
Failed method: PopupMenu:_update_callback target ID: 92544
Object was deleted while awaiting a callback
```
Here is full terminal output: [tres.txt](https://github.com/godotengine/godot/files/2729745/tres.txt)

With increased message_queue_size to 50MB, editor just freeze for 30s and then unfreeze with only this errors
```
SCRIPT ERROR: GDScript::reload: Parse Error: Error parsing expression, misplaced: '.'
   At: res://scenes/Player/Player.gd:27.
ERROR: reload: Method/Function Failed, returning: ERR_PARSE_ERROR
   At: modules/gdscript/gdscript.cpp:580.
ERROR: open: Unrecognized binary resource file: res://Helpers/LevelConverter/ferris_level.res
   At: core/io/resource_format_binary.cpp:854.
```

**Comment by akien-mga** [comment] 2019-01-14 11:15
@qarmin That script error seems due to a bug/ellipsis in https://github.com/Krumelur/GodotTesting/blob/godot31_issue_24789/TileTest/scenes/Player/Player.gd#L27

**Comment by Krumelur** [comment] 2019-01-14 11:17
Yeah, just remove that line. Sorry should not be in there and has nothing to do with the root issue.

**Comment by MikeMnD** [comment] 2019-12-23 23:43
![image](https://user-images.githubusercontent.com/186191/71385196-95916780-25ee-11ea-8b6e-570702f2d249.png)

I set this to 100MB and the editor successfully loaded tileset imported from Tiled with 528 tiles.

![image](https://user-images.githubusercontent.com/186191/71385233-c8d3f680-25ee-11ea-986a-48d6e6281a6a.png)

**Comment by akien-mga** [comment] 2020-01-28 07:45
Duplicate of #29238.

**Closed by akien-mga** 2020-01-28 07:45 UTC
Labels: bug, topic:editor
