### ISSUE TITLE
Alignment and column size problem in the inspector

### ISSUE THREAD

**Issue by jsena42** [godotengine/godot#27990] opened 2019-04-13 18:16 UTC
**Godot version:** 3.1-stable

**OS/device including version:** Ubuntu 18.04

**Issue description:** When I expose arrays (of any kind) I have only a little room to see the field and the left side gets wasted. Think this is something that should be fixed for better UX.
![Screenshot_20190413_151054](https://user-images.githubusercontent.com/24941270/56083685-d0f05b00-5dfe-11e9-84ef-394cbd358a19.png)

**Steps to reproduce:** Expose an array of any kind and check the Inspector.

**Comment by akien-mga** [comment] 2019-04-15 10:18
Duplicate of #7133.

**Closed by akien-mga** 2019-04-15 10:18 UTC
Labels: enhancement, topic:editor
