### ISSUE TITLE
ResourceLoader can't find uid of packed scenes in exported builds

### ISSUE THREAD

**Issue by bodonkerhoderos** [godotengine/godot#79009] opened 2023-07-04 05:45 UTC
### Godot version

v4.0.2.stable.arch_linux

### System information

Manjaro Linux

### Issue description

`ResourceLoader.get_resource_uid` returns -1 (not found) when provided a `res://` path to a packed scene during runtime in exported builds that are not run in the original project directory. i expect it to return the uid of packed scenes at runtime.

it returns a uid for icon.svg even on exports. it returns a uid for packed scenes when run in the original project directory. it fails to find a uid when exported to linux, android, and web platforms (likely all platforms). it also fails to find it when the pck is embedded.

### Steps to reproduce

1. call `ResourceLoader.get_resource_uid` with the `res://` path of a packed scene.
2. export to any platform
3. run exported project anywhere else

### Minimal reproduction project

[resource_uid_not_found.zip](https://github.com/godotengine/godot/files/11944838/resource_uid_not_found.zip)

**Comment by AThousandShips** [comment] 2023-07-04 07:32
While supporting UIDs is a good idea probably they're normally intended for the editor, and not for export, their main purpose is to handle renaming of files in the editor

**Comment by AThousandShips** [comment] 2023-07-04 07:33
Would say this is handled in this:
* https://github.com/godotengine/godot-proposals/issues/7181

**Comment by AThousandShips** [comment] 2023-07-04 12:46
Duplicate of: #75617

**Closed by AThousandShips** 2023-07-04 12:46 UTC
Labels: discussion, topic:core
