### ISSUE TITLE
(3.0) editor control move doesn't affect rect_pos(ition)

### ISSUE THREAD

**Issue by spusnei-pbsc** [godotengine/godot#8197] opened 2017-03-29 15:35 UTC
**Operating system or device - Godot version:**
Ubuntu 16.04, GoDot master 3.0

**Issue description:**
Dragging a control in the editor doesn't affect rect_pos(ition), but if you click on the value opened inputs are updated.

**Steps to reproduce:**
- open editor
- add any control element (e.g. Label)
- drag it
- observe no change in rect.pos properties (defect)
- click on Pos values, they are updated (good)

**Comment by kubecz3k** [comment] 2018-04-10 16:45
I'm not able to reproduce in 3.0.2 so I think it's fixed now

**Closed by kubecz3k** 2018-04-10 16:45 UTC
Labels: bug, topic:editor
