### ISSUE TITLE
error Expected Shader_type

### ISSUE THREAD

**Issue by NewSpark311** [godotengine/godot#16238] opened 2018-01-31 14:30 UTC
Godot 3.0 stable
Windows10
AMD Radeon R7 Series
CPU: AMD A8 7600 

its worth mentioning that i don't get the message on godot 3.0 RC3

```
0:00:01:0712 - Expected 'shader_type' at the beginning of shader.
----------
Type:Error
Description: 
Time: 0:00:01:0712
C Error: Expected 'shader_type' at the beginning of shader.
C Source: :1
C Function: 

0:00:01:0721 - Condition ' err != OK ' is true.
----------
Type:Error
Description: 
Time: 0:00:01:0721
C Error: Condition ' err != OK ' is true.
C Source: drivers\gles3\rasterizer_storage_gles3.cpp:1697
C Function: RasterizerStorageGLES3::_update_shader
```

**Steps to reproduce:**

**Comment by Zylann** [comment] 2018-02-01 13:37
This error is normal if you create a shader without specifying `shader_type` as the very first line.
What is your repro? Example project?

**Comment by RonanZe** [comment] 2018-02-11 22:51
I have those error messages with Godot 3.0 / Windows with SpatialMaterial + multiple "0" print in the Output. Those "0" seems linked to those SpatialMaterial problems.

With an empty ShaderMaterial, the error disappear

**Comment by Zylann** [comment] 2018-02-11 23:14
Can you provide an example project?

**Comment by RonanZe** [comment] 2018-02-13 13:58
Ok! I think I have spotted the problem.
The warnings appear when I switch the Thread Model in the Project Settings from "Single-Safe" to "Multi-Threaded"

I have 98 errors like this:
0:00:03:0461 - Expected 'shader_type' at the beginning of shader.
----------
Type:Error
Description: 
Time: 0:00:03:0461
C Error: Expected 'shader_type' at the beginning of shader.
C Source: :1
C Function: 

0:00:03:0464 - Condition ' err != OK ' is true.
----------
Type:Error
Description: 
Time: 0:00:03:0464
C Error: Condition ' err != OK ' is true.
C Source: drivers\gles3\rasterizer_storage_gles3.cpp:1697
C Function: RasterizerStorageGLES3::_update_shader

I'll send you a simplified project latter if needed

**Comment by NewSpark311** [comment] 2018-02-16 03:22
well, the project is a 2D project I don't think I'm using shaders at all, not that I know of.

**Comment by D3m0n92** [comment] 2018-03-02 01:28
Same problem...

**Comment by leiget** [comment] 2018-03-05 21:24
I have the same problem. I don't have any custom shaders at all. Maybe the SpatialMaterials aren't being written correctly in "material.cpp"?

**Comment by jvdnbus** [comment] 2018-03-12 18:03
Same issue here. Any SpatialMaterial with Thread Model set to 'Multi-Threaded' produces these errors once you run the project.

I'm using Windows build 3.0.2 stable.

[SpatialMatTest.zip](https://github.com/godotengine/godot/files/1803943/SpatialMatTest.zip)

**Comment by Zylann** [comment] 2018-03-18 20:26
I am getting this too.
I only have two scenes open with just controls with no scripts and no shaders (though I did open a shader earlier in the session but closed it since).

I created a script, which currently has the default code in it. The error happens everytime si save that script (only the script, not the scene). It's almost like the shader editor receives this event too and tries to save an empty shader maybe?

**Comment by pracedru** [comment] 2018-03-28 02:57
I have this issue on Windows but not on Linux.

**Comment by MrMaidx** [comment] 2018-05-29 22:44
I have this annoying issue as well on Antergos Linux (Intel GPU, Mesa 18.0.4).  As Zylann wrote every time I save this message popups in the Output:
`drivers/gles3/rasterizer_storage_gles3.cpp:835 - Condition ' !texture->active ' is true. returned: Ref<Image>()`
And also more than hundred of these errors without any description are shown in the debugger every time I run the game from the editor:
```
0:00:01:0064 - Expected 'shader_type' at the beginning of shader.
----------
Type:Error
Description: 
Time: 0:00:01:0064
C Error: Expected 'shader_type' at the beginning of shader.
C Source: :1
C Function: 
```
I have only one simple shader in my project and I'm pretty sure shader_type is defined.

**Comment by Overblob** [comment] 2018-07-16 14:10
Duplicate of #15998

**Closed** 2018-07-17 09:09 UTC
Labels: bug
