### ISSUE TITLE
Window Show Then Crashes On An Intel 4000

### ISSUE THREAD

**Issue by oliver20033549** [godotengine/godot#69326] opened 2022-11-29 04:00 UTC
### Godot version

4.0 beta 6

### System information

Window 10, Opengl4, Intel HD Graphics 4000

### Issue description

When I Open Godot With The Comand --rendering-method gl_compatibility Window Show Then Automaticly Crash Without Any Error, I Am Using A Intel HD Graphics 4000 With Opengl4 Support

### Steps to reproduce

Launching Godot

### Minimal reproduction project

No response

**Comment by clayjohn** [comment] 2022-11-29 04:40
Have you tried updating your GPU drivers? Intel HD 4000 should have no problem with the OpenGL backend. 

Also can you please post what is printed out in the command line when the engine crashes?

**Comment by clayjohn** [comment] 2022-12-23 03:01
This is fixed now in beta 9 right?

**Comment by Calinou** [comment] 2023-01-12 17:26
Closing due to lack of response. Please comment if you can still reproduce this bug on the latest Godot version.

**Closed by Calinou** 2023-01-12 17:26 UTC
Labels: bug, topic:rendering, crash
