### ISSUE TITLE
Crash when building from source and launching new project on Ubuntu

### ISSUE THREAD

**Issue by Mivekk** [godotengine/godot#86887] opened 2024-01-06 16:01 UTC
### Tested versions

- Reproducible in 4.2.stable, 4.3.dev

### System information

Godot v4.2.2.rc (d5064a7d4) - Ubuntu 22.04.3 LTS 22.04 - Wayland - GLES3 (Compatibility) - SVGA3D; build: RELEASE;  LLVM; () - Intel(R) Core(TM) i9-10850K CPU @ 3.60GHz (10 Threads)

### Issue description

I've tried to build godot from source using: ```scons platform=linuxbsd use_llvm=yes linker=lld```. After creating a new project with renderers Forward+ or Mobile, I always got the same error: 

```
Godot Engine v4.2.2.rc.custom_build.d5064a7d4 - https://godotengine.org
Vulkan API 1.3.238 - Forward Mobile - Using Vulkan Device #0: Unknown - llvmpipe (LLVM 15.0.7, 128 bits)

WARNING: Blend file import is enabled in the project settings, but no Blender path is configured in the editor settings. Blend files will not be imported.
     at: _editor_init (modules/gltf/register_types.cpp:63)
ERROR: Caller thread can't call this function in this node (/root). Use call_deferred() or call_thread_group() instead.
   at: propagate_notification (scene/main/node.cpp:2236)

================================================================
handle_crash: Program crashed with signal 11
Engine version: Godot Engine v4.2.2.rc.custom_build (d5064a7d443d4b335169c0d02e822ee720abcc5d)
Dumping the backtrace. Please include this when reporting the bug to the project developer.
[1] /lib/x86_64-linux-gnu/libc.so.6(+0x42520) [0x7f59bc242520] (??:0)
[2] llvm::CmpInst::Create(llvm::Instruction::OtherOps, llvm::CmpInst::Predicate, llvm::Value*, llvm::Value*, llvm::Twine const&, llvm::BasicBlock*) (??:0)
-- END OF BACKTRACE --
================================================================
```

On the other hand compatibility renderer works fine. I used many different scons arguments such as: 
```scons platform=linuxbsd```
```scons platform=linuxbsd debug_symbols=yes```
```scons platform=linuxbsd use_llvm=yes linker=lld dev_build=yes```

Error message remained unchanged despite change in the arguments. I also deleted folders ~/.config/godot and ~/.local/share/godot before new builds to achieve clean build.

### Steps to reproduce

1. Build godot using `scons platform=linuxbsd`
2. Run godot with ./godot/bin/godot.linuxbsd.editor.x86_64
3. Create new project with renderer Forward+ or Mobile

### Minimal reproduction project (MRP)

N/A

**Comment by TheReaperKing** [comment] 2024-02-03 16:30
What happens if you try adding --rendering-driver opengl3 to your launch command?  For example mine is ./Godot_v4.2.1-stable_linux.x86_64 --rendering-driver opengl3

Mine would crash with a similar message using Forward, but I didn't try Mobile.  After I tried that launch parameter it worked.

**Comment by akien-mga** [comment] 2024-02-03 23:59
> ### System information
> 
> Godot v4.2.2.rc ([d5064a7](https://github.com/godotengine/godot/commit/d5064a7d443d4b335169c0d02e822ee720abcc5d)) - Ubuntu 22.04.3 LTS 22.04 - Wayland - GLES3 (Compatibility) - SVGA3D; build: RELEASE; LLVM; () - Intel(R) Core(TM) i9-10850K CPU @ 3.60GHz (10 Threads)

SVGA3D is the software rasterizer used by VMWare. Please mention the fact you're trying to run Godot in a virtual machine, it's very relevant :)

And in that case it's a duplicate of https://github.com/godotengine/godot/issues/82435

The stackteace is a crash in the SVGA3D driver itself. Could be worth reporting to VMWare.

**Closed by akien-mga** 2024-02-03 23:59 UTC
Labels: bug, platform:linuxbsd, needs testing, crash

**Comment by TheReaperKing** [comment] 2024-02-04 01:17
Just for the record I personally was having the similar crashes using the Linux binary.  I of course can't say what the OP was using.

**Comment by akien-mga** [comment] 2024-02-04 09:01
@TheReaperKing Were you getting the same stacktrace pointing at `llvm::CmpInst::Create`? If not, and you're not using llvmpipe on an older Linux distro, it's unlikely to be the same crash.

The medium post you linked to seems to be a different issue too, from not having Vulkan drivers at all.

**Comment by TheReaperKing** [comment] 2024-02-04 09:20
My apologies.  Maybe I didn't look close enough but it seemed like a very similar error.  I did notice the signal is different.  And I will freely admit I am just getting started with Godot.  This was my error:

```
WARNING: Blend file import is enabled in the project settings, but no Blender path is configured in the editor settings. Blend files will not be imported.
     at: _editor_init (modules/gltf/register_types.cpp:63)
ERROR: Caller thread can't call this function in this node (/root). Use call_deferred() or call_thread_group() instead.
   at: propagate_notification (scene/main/node.cpp:2236)

================================================================
handle_crash: Program crashed with signal 4
Engine version: Godot Engine v4.2.1.stable.official (b09f793f564a6c95dc76acc654b390e68441bd01)
Dumping the backtrace. Please include this when reporting the bug to the project developer.
[1] /lib/x86_64-linux-gnu/libc.so.6(+0x3c050) [0x7f2b850a5050] (??:0)
[2] llvm::CmpInst::Create(llvm::Instruction::OtherOps, llvm::CmpInst::Predicate, llvm::Value*, llvm::Value*, llvm::Twine const&, llvm::BasicBlock*) (??:0)
-- END OF BACKTRACE --
================================================================
```

Thank you so much for your clarification, I have a lot to learn!

**Comment by akien-mga** [comment] 2024-02-04 09:46
That does seem similar. What OS are you on and what Vulkan drivers are you using? The first line of the Godot log should make it clear.
