### ISSUE TITLE
[Godot 4] Replace words in files (ctrl + shift + f -> replace all) is working erratically

### ISSUE THREAD

**Issue by AttackButton** [godotengine/godot#63441] opened 2022-07-25 15:27 UTC
### Godot version

v4.0.alpha.custom_build [79463aa5d]

### System information

Windows 8 and 11

### Issue description

`Ctrl + shift + f`, `find in files -> replace all` is not working as expected. The correct behaviour should be to change all the matches.

Sometimes it works but only for a few files and it only updates if you restart godot.

### Steps to reproduce

Try using `ctrl + shift + f`, `find in files -> replace` -> `replace all` and check that matches will not always be replaced in files.

### Minimal reproduction project

[replace_issue.zip](https://github.com/godotengine/godot/files/9182528/replace_issue.zip)

**Comment by Calinou** [comment] 2022-07-25 17:04
Do you have some of the scripts open in the script editor while using Replace All? If so, it's possible that the script editor is overwriting the files with the newly replaced words with old versions.

**Comment by AttackButton** [comment] 2022-07-25 17:45
> Do you have some of the scripts open in the script editor while using Replace All? If so, it's possible that the script editor is overwriting the files with the newly replaced words with old versions.
> 
> Also, can you reproduce this when following the same steps in 3.x?
I tested it with both open and closed files, and the problem is still happening.

This happens only in the 4.x `replace` feature, in 3.x it works perfectly. This problem has been around for a long time in 4.x, I'm just reporting it now.

**Comment by joemicmc** [comment] 2022-07-28 23:45
@Calinou I think this a duplicate of https://github.com/godotengine/godot/issues/57870

**Comment by Calinou** [comment] 2022-07-28 23:53
Duplicate of https://github.com/godotengine/godot/issues/57870.

**Closed by Calinou** 2022-07-28 23:53 UTC
Labels: bug, topic:editor, needs testing, regression
