### ISSUE TITLE
[CSG] Adjacent brushes glitch

### ISSUE THREAD

**Issue by drequivalent** [godotengine/godot#38742] opened 2020-05-14 21:39 UTC
**Godot version:** 3.2.1.stable.official

**OS/device including version:** Manjaro Gnome, current @ 15 May 2020

**Issue description:** Adjacent CSG Add brushes start losing triangles when under the same combiner

**Steps to reproduce:** 
1. Start a new scene
2. Add a Spatial node
3. Add a CSG combiner
4. Add a CSG box under a CSG combiner
5. Add a CSG box under a CSG combiner
6. Make them adjacent

As seen in this video https://www.youtube.com/watch?v=KPlKCBz2s38&feature=youtu.be

**Minimal reproduction project:** Two CSG boxes and a combiner

![Screenshot from 2020-05-15 00-59-05](https://user-images.githubusercontent.com/1463277/81990234-6cc64900-9647-11ea-86a3-1b303307dc10.png)

**Comment by akien-mga** [comment] 2020-05-15 05:17
Can you try 3.2.2 beta 2? It has CSG fixes.

**Comment by madmiraal** [comment] 2020-05-15 08:36
Duplicate of #21125 which was fixed in 3.2 with #38011.

**Closed** 2020-05-15 08:55 UTC
Labels: bug, topic:core

**Comment by drequivalent** [comment] 2020-05-16 00:24
@akien-mga Cool. Fixed.
