### ISSUE TITLE
Search, Edit and Go To menus disappeared from script editor??

### ISSUE THREAD

**Issue by pigigi** [godotengine/godot#44643] opened 2020-12-24 03:50 UTC
**Godot version:**
3.2.1 stable

**OS/device including version:**
Win 10 Lenovo 2-in-1 (physical-keyboard-less tablet mode)

**Issue description:**
I noticed that the Edit, Search and Go To menus had disappeared from the script editor as I was trying to repro what I thought was a "ctrl+f doesn't move focus to text input" bug - but at that moment the editor had no option/handler for ctrl+f altogether! Clicking around a little, to another tab and back brought the missing menus back. I could actually see them pop into existence as I returned to the faulty script window.

So, not that big of a deal, but weird!

**Steps to reproduce:**
Sorry, none as of yet. I just reckoned that the oddity deserved an entry in case someone else runs into it.

Oh, just remembered: I had just done "close other tabs" a short while before. Related?

**Minimal reproduction project:**
Any.

**Comment by Calinou** [comment] 2020-12-24 14:15
Duplicate of https://github.com/godotengine/godot/issues/38837.

**Closed by Calinou** 2020-12-24 14:15 UTC
