### ISSUE TITLE
Weird Texture Glitch in Godot 

### ISSUE THREAD

**Issue by nawillcodes** [godotengine/godot#56144] opened 2021-12-21 22:17 UTC
### Godot version

3.4.1

### System information

MacBook Pro (13-inch, 2020) Apple M1 16GB, Big Sur 11.2

### Issue description

Does anyone know what this weird glitch is in Godot, where all of my textures are getting misplaced? I've tried both GLES2 and GLES3 in case that was the issue. If anyone can tell me how to fix this, it would be much appreciated. I'm sure others are having the same problem.

<img width="1440" alt="Screen Shot 2021-12-21 at 4 34 40 PM" src="https://user-images.githubusercontent.com/57769775/147004851-bb8c9b68-b2c9-4abc-822c-ef4329e43412.png">
<img width="1440" alt="Screen Shot 2021-12-21 at 4 34 47 PM" src="https://user-images.githubusercontent.com/57769775/147004854-79beca13-8274-4b01-9c38-35c72303c720.png">

### Steps to reproduce

Just tilemaps with saved tilesets and texture atlases it seems like any texture I add glitches out.

### Minimal reproduction project

It didn't matter what project I was running.

**Comment by Calinou** [comment] 2021-12-21 22:58
Duplicate of https://github.com/godotengine/godot/issues/56055.

**Closed by Calinou** 2021-12-21 22:58 UTC
