### ISSUE TITLE
Physic Body Instanced scene doesn't use CollisionShapes

### ISSUE THREAD

**Issue by FEDE0D** [godotengine/godot#2314] opened 2015-07-28 21:12 UTC
When instancing a PhysicBody2D node (don't know if this is true for 3d as well) the new CollisionShape or CollisionPolygon nodes added as childs of the instanced scene are not used for the collisions.

This is the hierachy:

```
main_node
    - other nodes
    - instanced RigidBody2D
        - ... (other child nodes saved inside RigidBody2D)
        - CollisionShape2D (new node added to the instanced scene, does not work)
```

I think this is useful in a lot of ways, but it also follows the whole idea of "instanced scenes". Besides if it works with other nodes, why not with collision shapes?

Here's a test project: https://dl.dropboxusercontent.com/u/274954519/instance_scene_collision_test.zip

**Comment by zhagsenkk** [comment] 2015-07-30 06:22
And if we replace the CollisionShape2D to Camera2D, Camera2D cant be it should be.

**Comment by slapin** [comment] 2015-07-30 15:00
This problem is due to how godot handles collision shapes.
CollisionShape is just helper node which does add_shape your shapes (resources you create in 
CollisionShape) and CollisionShape doesn't exist during runtime.
The problem is that CollisionShape node will add shapes to their ascender on the current scene tree,
and if none, they will be just removed.
To make this work, just add your shapes by hand to the collision body.
Or setup collision body and CollisionShapes children of it in the same scene.

**Comment by FEDE0D** [comment] 2015-07-30 18:26
That still doesn't solve the issue. The collision shape should be process and added to the parent.

**Comment by kubecz3k** [comment] 2015-08-03 09:34
@FEDE0D I also had similar problems and fortunately I have found a workaround for this. Basically I'm adding proper shape during runtime in ready with an add_shape function. Here is your sample project with this workaround: https://dl.dropboxusercontent.com/u/168251/godot/some/samples/instance_scene_collision_test_workaround.7z

**Comment by eska014** [comment] 2015-10-31 00:16
This issue persists with new instancing system (422929e87fbe91be1efedf1fe3a9a71d61e58b40).

**Comment by reduz** [comment] 2016-01-02 12:39
will not be fixed until 3.0 because it needs compatibility breakage for it to be made to work properly :(

**Comment by kubecz3k** [comment] 2016-01-02 13:35
@reduz can't it be fixed just by adding check in "ready" equivalent of c++ core code of CollisionSphere?
CollisionSphere could automatically check if it's registered in parent and if not then add self to the parent. 
In GD script it would be something like (pseudocode written from head):
```
func ready():
   var need2RegisterInParent = isShapeInParent(self);
   if(need2RegisterInParent):
      get_parent().add_shape(get_shape());

func isShapeInParent(inShape2Check):
   var parentShapeCount = get_parent().get_count();
   for idx in range(parentShapeCount):
      var currentShape = get_parent().get_shape(idx);
      if(currentShape==inShape2Check):
         return true;
   return false;
```

**Comment by eska014** [comment] 2016-04-17 17:55
As noted in #4348, this concerns all CollisionObjects, not just PhysicsBodies

**Comment by bojidar-bg** [comment] 2016-11-19 15:12
Ahah, finally was able to workaround this in a game of mine:

```gdscript
extends CollisionObject2D

func _ready():
	for shape in get_children():
		if shape.has_meta("__registered") and shape.get_meta("__registered"):
			continue
		
		get_tree().set_editor_hint(true)
		
		remove_child(shape) # Make it pick up the editor hint
		add_child(shape)
		
		get_tree().set_editor_hint(false) # Unset quickly
		
		if shape extends CollisionShape2D: # Now update parent is working, so just change the shape
			shape.set_shape(shape.get_shape())
		elif shape extends CollisionPolygon2D:
			shape.set_polygon(shape.get_polygon())
		
		remove_child(shape) # Reset its editor hint cache, just in case it was needed.. (you might drop this part if it bottlenecks)
		add_child(shape)
		
		shape.set_meta("__registered", true)
```

**Comment by slapin** [comment] 2016-11-19 15:53
Well, this is really heavy hack I'd say... I think it is better to patch
engine than do this...

**Comment by bojidar-bg** [comment] 2016-11-19 21:30
@slapin You think its heavy? No, it's relatively lightweight, but it would all be better if there aren't hacks for this.

**Comment by bkeys** [comment] 2016-12-29 00:58
I would like to report that this is also happening with vehicle wheels so this is likely an issue for more than just collision shapes

**Comment by radishes** [comment] 2017-03-05 23:29
I believe I am encountering this with an instanced Area2D, where the Area2D is defined in a parent scene, and the CollisionShape2D is defined in a scene which derives from the parent scene. I've created a sample project that reproduces the issue. 
[Area2D-instance-bug.zip](https://github.com/godotengine/godot/files/819850/Area2D-instance-bug.zip)
I'm not certain this is the same issue, but it looks like it is, so I will refrain from filing a new bug unless requested to do so. Thanks!

**Comment by xphere** [comment] 2017-04-12 06:34
Just got bitten by this bug too, thanks @bojidar-bg for the workaround, though it only works for a single shape. When multiple shapes are defined, only the first is detected. Any idea why?

**Comment by bojidar-bg** [comment] 2017-04-12 09:18
@xphere Sounds strange, though you should probably try to tweak the workaround yourself -- AFAIR it might not always work with CollisionShape2D nodes (unlike CollisionPolygon2D nodes)

**Comment by xphere** [comment] 2017-04-13 06:15
Thanks, @bojidar-bg

For some reason, when dealing with multiple shapes, the workaround fails to add the last one.
Moving the calls to `set_editor_hint` out of the loop fixes this.
I've created a test project to test this, code can be found [here](https://gist.github.com/xphere/a7b9e401925020afee7612a562e700cf).

I hope this will be fixed in core so we don't need ugly workarounds.

**Comment by kubecz3k** [comment] 2017-08-02 18:28
I think this should be fixed now. Can you recheck?

**Comment by reduz** [comment] 2017-08-04 16:52
this is definitely fixed now, so closing

**Closed by reduz** 2017-08-04 16:52 UTC
Labels: bug, confirmed, topic:physics
