### ISSUE TITLE
Using System.TimeZoneInfo will crash on iOS devices (not in the simulator) #40757

### ISSUE THREAD

**Issue by andy-noisyduck** [godotengine/godot#40767] opened 2020-07-27 16:36 UTC
**Godot version:**
3.2.2 Mono w/ Mono 6.10 stable

**OS/device including version:**
Build w/ OSX Catalina, tested on various iPhones w/ iOS 13
As with the similar issues, I've tested using Mono 6.10 and 6.8

**Issue description:**
App will crash when trying to fetch information about the local timezone from the device. This only happens on real devices. The simulator works fine.

You can use TimeZoneInfo directly to trigger this, or the more common use-case of `dateTime.ToUniversalTime()`, which will call it internally to do the conversion.

```
xamarin_timezone_get_data
  at System.TimeZoneInfo.GetMonoTouchData (System.String name, System.Boolean throw_on_error)
  at System.TimeZoneInfo.CreateLocal ()
  at System.TimeZoneInfo.get_Local ()
  at System.TimeZoneInfo.ConvertTimeToUtc (System.DateTime dateTime, System.TimeZoneInfoOptions flags)
  at System.DateTime.ToUniversalTime ()
```

Interestingly calling `DateTime.UtcNow` works correctly and does not crash. I'm not sure what that property does internally to avoid this issue.

As before, unsure if this is Mono issue, or the way we are linking with it. Probably related to the other similar issue's I've opened.

**Steps to reproduce:**
1. Convert a local time to UTC, e.g. `DateTime.Now.ToUniversalTime();`

**Minimal reproduction project:**
[Test-MonoDateIOS.zip](https://github.com/godotengine/godot/files/4983205/Test-MonoDateIOS.zip)

**Comment by andy-noisyduck** [comment] 2020-07-27 16:37
PS: Sorry for the (maybe related) issue spam this week. Just trying to log them as I find them.

(They are also pretty painful to track down each time, as it's real device only, and aren't normally written to the crash logs)

**Comment by neikeq** [comment] 2021-05-16 18:01
I'll confirm later, but this is probably the same as #40757.

**Comment by neikeq** [comment] 2021-06-01 23:16
Confirmed. Closing as duplicate of #40757.

**Closed by neikeq** 2021-06-01 23:16 UTC
Labels: bug, platform:ios, topic:mono
