### ISSUE TITLE
Vulkan: Editor constantly uses 1-2% CPU while doing nothing on empty project due to Vulkan lacking 2D batching

### ISSUE THREAD

**Issue by tustin2121** [godotengine/godot#71084] opened 2023-01-08 19:13 UTC
### Godot version

v4.0.beta10.mono.official [d0398f62f]

### System information

MacOS Catilina 10.15.6, MacBook Air 

### Issue description

I just downloaded 4.0 beta 10 and started a new project, and simply sitting and staring at the empty project screen causes my mac's fan to spin up and stay spinning on high. The editor isn't doing anything, but it apparently just can't sit still? The CPU usage is always at at least 1% or 2%, and it apparently wakes the processor at least 150 times per second. 

I would expect simply staring at the editor with *nothing* on screen would leave the CPU alone. If I swipe away to another screen or minimize the editor, I would expect the CPU usage to fall as well, but the editor still uses 1-2% constantly. There's no way I can use Godot if it is going to eat my laptop's battery just doing literally nothing...

<img width="828" alt="image" src="https://user-images.githubusercontent.com/794812/211212302-c0ea0ec8-5cec-47df-b6fa-3c8d34378080.png">

### Steps to reproduce

Open a new project and just sit and wait. Going to the AssetLib tab seems to speed up the process, but it's not required.

### Minimal reproduction project

N/A

**Comment by Zireael07** [comment] 2023-01-08 19:20
I suspect this is the audio system?

**Comment by Calinou** [comment] 2023-01-08 19:35
Duplicate of https://github.com/godotengine/godot/issues/38154.

**Comment by tustin2121** [comment] 2023-01-08 20:52
`coreaudiod` was using a high percentage of CPU when Godot was open. I changed the audio system to "Dummy" in the project settings and restarted the editor, and now that usage in `coreaudiod` is gone, but the editor itself is still using the same amount of CPU. So it's either something other than the audio system, or I guess the audio system is still outputting dummy sound data to the dummy driver?

<img width="828" alt="image" src="https://user-images.githubusercontent.com/794812/211218248-4beb3913-9d15-46c1-8299-2ccd0260afc3.png">

**Comment by Calinou** [comment] 2023-01-08 21:27
Can you reproduce this on 3.5.1?

**Comment by tustin2121** [comment] 2023-01-08 21:40
Downloaded 3.5.1, opened a blank project in it, modified the Project Settings to make it use the Dummy audio driver. The numbers in the process monitor seem worse, but my computer is not heating up and spinning up the fan to high. Whatever is making 4.b10 eat my batteries and turn my macbook into an airplane is not happening in 3.5.1.

<img width="823" alt="image" src="https://user-images.githubusercontent.com/794812/211220378-59ceb3cf-eaa0-4f4a-9752-2ed26192dc2e.png">

**Comment by Calinou** [comment] 2023-01-08 21:44
> Whatever is making 4.b10 eat my batteries and turn my macbook into an airplane is not happening in 3.5.1.

Can you reproduce in 4.0.beta10 after switching the rendering method to Forward Mobile? Also try GL Compatibility.

**Comment by tustin2121** [comment] 2023-01-08 22:07
The 4.0.b10 project I've been testing on has been using the mobile renderer. Switching to gl_compatability makes the fan calm down:

<img width="825" alt="image" src="https://user-images.githubusercontent.com/794812/211221009-0574bc14-68c4-4a9f-9f9e-082843830601.png">

Switching to the forward_plus renderer makes the fan spin up again after a while: 

<img width="817" alt="image" src="https://user-images.githubusercontent.com/794812/211221216-78df40fd-ba4f-4ee9-9a9d-047e7dcda708.png">

I guess I'll be using the gl_compatibility renderer for a while.

**Comment by Calinou** [comment] 2023-01-08 22:17
This is likely because the editor is much slower to render when using Vulkan due to lack of 2D batching.

**Comment by clayjohn** [comment] 2023-01-08 23:31
To me this sounds like vsync may not be working in on the macOS builds.

**Comment by Calinou** [comment] 2023-01-08 23:42
> To me this sounds like vsync may not be working in on the macOS builds.

This should be fixed in macOS Ventura, but you'll need to upgrade as this is an upstream issue.

**Closed** 2024-09-11 19:56 UTC
Labels: enhancement, platform:macos, topic:rendering, topic:editor, confirmed, topic:2d, performance
