### ISSUE TITLE
Document the unavailable folder names, when creating new project.

### ISSUE THREAD

**Issue by anderlli0053** [godotengine/godot#38540] opened 2020-05-07 15:07 UTC
There need to be more documentation available, when the user wants to create new project via clicking on "New Project" and then naming the folder, where the project files will be generated.

I tried it on Windows 10 Home, once or twice it froze and i had to kill it with task manager via process kill. When i 've ran it the third time, it just wrote the alert that the folder couldn't be created, but did not mention why. Some of us know that there are some illegal or better said forbiden names, for naming folders/files on Windows, especially on Desktop, but the beginners and some people doesn't know that. It is simply not enough, just to say that folder cannot be created, without explaining why and how to fix it.

**

> List of reserved file names on Windows 10:
> The following are (case insensitive) reserved names which cannot be assigned to a directory or file in Windows 10 :
> 
> CON
> PRN
> AUX
> NUL
> COM1, COM2, COM3, COM4, COM5, COM6, COM7, COM8, COM9, COM0
> LPT1, LPT2, LPT3, LPT4, LPT5, LPT6, LPT7, LPT8, LPT9, LPT0

**

src --> https://kizu514.com/blog/forbidden-file-names-on-windows-10/

![1](https://user-images.githubusercontent.com/22171451/81310905-ff357e00-9084-11ea-8f99-1416b9fbe44f.png)

![2](https://user-images.githubusercontent.com/22171451/81310901-fe045100-9084-11ea-8b5c-92c327840607.png)

**Comment by Calinou** [comment] 2020-05-07 19:51
Duplicate of #20110 and #38198.

**Closed by Calinou** 2020-05-07 19:51 UTC
