### ISSUE TITLE
In remote mode, two script sections appear

### ISSUE THREAD

**Issue by Torguen** [godotengine/godot#55465] opened 2021-11-30 09:31 UTC
### Godot version

3.4.1 rc1 mono

### System information

w10 64

### Issue description

When running and viewing in remote mode, the script field appears duplicate.
![Captura](https://user-images.githubusercontent.com/19652075/144021502-335cbe8f-aa8e-40e0-bf45-25531cabd7ae.PNG)

### Steps to reproduce

...

### Minimal reproduction project

...

**Comment by akien-mga** [comment] 2021-11-30 09:55
Duplicate of #51077

**Closed by akien-mga** 2021-11-30 09:55 UTC
