### ISSUE TITLE
Clicking on Animation Player issue

### ISSUE THREAD

**Issue by gamecoder-nz** [godotengine/godot#57233] opened 2022-01-25 23:10 UTC
### Godot version

3.4.2

### System information

Windows 11

### Issue description

Clicking on the animation player will play the first frame of the currently selected animation but the properties the animation changed remain even if the game runs

### Steps to reproduce

Create a scene with a sprite and an animation player.  Create an animation that sets the opacity of the sprite from 0 to 255.  Click on the animation player and the opacity will change to 0.  Play the game and the opacity will still be 0.  The opacity has to be manually changed back.

**Comment by Calinou** [comment] 2022-01-25 23:19
Duplicate of https://github.com/godotengine/godot-proposals/issues/3829. This is expected behavior and can be remedited by ensuring all tracks have a corresponding RESET track created. Godot 3.4 and later will automatically create a RESET track if you use the keyframe icon next to each property in the inspector (but only for tracks created after upgrading to Godot 3.4).

**Closed by Calinou** 2022-01-25 23:19 UTC
