### ISSUE TITLE
Vulkan: SubViewports not functioning unless update mode is set to "Always"

### ISSUE THREAD

**Issue by Leakbang** [godotengine/godot#55471] opened 2021-11-30 14:08 UTC
___

***Bugsquad note:** This issue has been confirmed several times already. No need to confirm it further.*

___

### Godot version

v4.0.dev.calinou [cf67f18ce]

### System information

Linux KDE Neon, Vulkan, NVIDIA GeForce GTX 1050 Ti, Driver Version: 470.63.01

### Issue description

I cannot seem to make Subviewports work in any shape or form. The error message `Uniforms were never supplied for set (3) at the time of drawing, which are required by the pipeline` is continuously popping up. I have tried with both 2D and 3D objects in the viewports, however none seem to work.
Are others able to reproduce this effect?

### Steps to reproduce

1. Setup a basic 3D scene
2. Add a SubViewport node
3. Set nodes as its children (Camera, UI control, or others)
The viewport display is black and rendering the viewport as a texture will also not work.

**Comment by spindlebink** [comment] 2021-11-30 19:00
Same here. I initially figured they just weren't implemented yet, but good to hear others are having the same issue.

**Comment by Calinou** [comment] 2021-12-01 02:34
Other people have gotten SubViewports to work on `master`, such as in https://github.com/godotengine/godot/issues/40651 and https://github.com/godotengine/godot/issues/54122.

**Comment by navy-cap-echo** [comment] 2021-12-01 08:35
@Leakbang I had the same problem (black display) until i switch the "update mode" in the "Render target" of the SubViewport to "Always". I'm not sure this fixes your problem, but maybe give it a try.

**Comment by Leakbang** [comment] 2021-12-01 13:40
I did try setting the "update mode" to "Always" but it didn't make any difference for me.

**Comment by Leakbang** [comment] 2021-12-16 10:16
I retried this on `v4.0.dev.calinou [e31138958]`, and setting the update mode to Always does not fix the issue.

**Comment by KoBeWi** [comment] 2021-12-19 23:13
I just discovered the existence of `UPDATE_WHEN_PARENT_VISIBLE`. This should be the default option in SubViewport probably. `UPDATE_WHEN_VISIBLE` makes sense only for Window viewports and won't work as expected for typical usage.

**Comment by KoBeWi** [comment] 2021-12-25 09:56
Actually no, `UPDATE_WHEN_VISIBLE` uses `render_target_was_used()` method, which never returns true. `UPDATE_WHEN_PARENT_VISIBLE` checks parent Viewport actually.

**Comment by Duroxxigar** [comment] 2021-12-30 02:32
Just wanted to chime in here as well - setting the update mode to Always doesn't fix the issue for me either. #28174d531b

**Comment by Zireael07** [comment] 2022-02-02 12:25
In alpha 1, 2D subviewports seem to work, but **3D** don't. The resulting texture is either all black or all magenta

**Comment by CrezyDud** [comment] 2022-02-07 14:45
> In alpha 1, 2D subviewports seem to work, but **3D** don't. The resulting texture is either all black or all magenta

not for me

**Comment by kicknbrit** [comment] 2022-03-17 07:10
Is setting size_2d_override_stretch making it work for anyone else?

**Comment by sboron** [comment] 2022-03-19 16:17
Same issue by me, but render target mode is always. 3d is still not working.

Node tree
![image](https://user-images.githubusercontent.com/76991284/159129232-250a3592-079e-4c8b-8fe4-dd10065f8972.png)
Output
![image](https://user-images.githubusercontent.com/76991284/159129240-153ee28f-6918-473c-95df-d5e11cdae126.png)


When i move it an split controller and change the offset of the split controllers it works.
U can see here:
![image](https://user-images.githubusercontent.com/76991284/159129260-088e4e3f-3d8d-4de9-8566-80349ed6e1a1.png)

**Comment by Zireael07** [comment] 2022-03-19 18:07
Hm, so it seems forcing an update/resize might do the trick? Thanks for the tip...

**Comment by sboron** [comment] 2022-03-19 20:07
Yeah its looks like that the subviewport size are not setted right by the viewport container. if u do it manualy it works.

**Comment by sboron** [comment] 2022-03-19 20:09
Small hack which fix the issue:

   `ublic override void _EnterTree()
        {

            var origSize = this.GetParent<SubViewportContainer>().Size;
            this.Size = new Vector2i((int)origSize.x, (int)origSize.y);
   }`

**Comment by sboron** [comment] 2022-03-19 20:11
I think the issues comes inside the code. The SubViewportContainer is set the size of the SubViewport (Vector2 to Vector2i) -> something here is broken

**Comment by seocwen** [comment] 2022-04-30 16:47
The following line seems to do nothing:
render_target_clear_mode = SubViewport.CLEAR_MODE_NEVER

I've been trying to draw on top of my last frame to no avail. As a minimal test, I have a subviewpoint set to clearMode NEVER, with a single colorRect with the following script:

func _process(delta):	
	color = $"../../../resources".random_color()
	color.a = randf()
	position = Vector2(randi() % 384, randi() % 256)
	size = Vector2(randi() % 64, randi() % 64)
	update()
	
The result is a new rectangle every frame, rather than a rectangle being added to the render target every frame.

**Comment by IriaSomobu** [comment] 2022-05-03 11:40
I wanted to place output of secondary Camera3D onto MeshInstance3D (PlaneMesh).

<details>
<summary>Scene layout is really simple</summary>

![image](https://user-images.githubusercontent.com/17745136/166444271-bbad8926-7fcd-4636-a6b9-0b490336bf93.png)

</details>

<details>
<summary>I wrote simple shader that maps input texture onto plane based on screen UV.</summary>

```glsl
shader_type spatial;
render_mode unshaded;

uniform sampler2D viewport_texture : hint_albedo;

void fragment() {
	vec4 n_out4p0 = texture(viewport_texture, SCREEN_UV);
	ALBEDO = vec3(n_out4p0.xyz);
}
```
</details>

And then I assigned this shader to `OutputPlane` as a `ShaderMaterial` and set that single shader param as a `ViewportTexture` pointing to my `SubViewport`.

<details>
<summary>But all I've got it is a pink texture both in editor and in-game</summary>

![image](https://user-images.githubusercontent.com/17745136/166444819-e5e4c00f-17c1-4a67-a7c0-be10f57a27ed.png)

![image](https://user-images.githubusercontent.com/17745136/166444862-b3de15b9-35df-43f5-97e9-00d4e43631ef.png)

</details>

As of `4.0.alpha.calinou.ce4326df7`, I've managed to make it work, but it requires all conditions to be met:

1. SubViewport must have both `size` and `size_2d_override` to be set;
2. SubViewport must be `render_target_update_mode = ALWAYS`;
3. OutputPlane's `viewport_texture` must be grabbed with `viewport.get_texture()` directly from viewport (done via script attached to plane).

<details>
<summary>This is how viewport texture is assigned</summary>

```gdscript
extends MeshInstance3D

@export var viewport: NodePath;
@onready var _viewport = get_node(viewport)

func _ready():
	var m: ShaderMaterial = mesh.surface_get_material(0);
	m.set_shader_param("viewport_texture", _viewport.get_texture())

```

</details>

Note: w/o 3rd workaround (i.e. when shader's `viewport_texture` assigned from editor) shader works properly in editor, but still shows pink color in-game. Also 3rd workaround is not required when `SubViewport` is placed in `SubViewportContainer`.

**Comment by Zireael07** [comment] 2022-05-03 15:34
Thanks for the workaround, I'll try it, as I still have the pink issue on my mirror mesh.

**Comment by thoced** [comment] 2022-05-08 20:49
IriaSomobu's solution works for me

**Comment by Zireael07** [comment] 2022-05-09 18:47
Confirming the workaround works.

**Comment by darrylryan** [comment] 2022-06-29 13:03
Just to update this - I'm still seeing weirdness with pink output like @sboron in the latest master as of time of posting. Setting update / clear modes doesn't seem to help.

**Comment by Rindbee** [comment] 2022-07-09 12:26
I noticed that if I change the `size` property of the `SubViewport`, I won't have this problem. So it may be that the necessary steps in setting the `size` were not performed. Maybe we should set the size in the constructor of `SubViewport`.

**Comment by arcanis** [comment] 2022-10-16 14:53
Expanding on @Rindbee's comment, the following seemed to work:

```
extends SubViewport

func _ready():
	set_size(size)
```

**Comment by joshua-maros** [comment] 2022-12-02 20:35
For me what ended up working was deleting the shader and material off the filesystem, re-saving the scene I was working on, and ticking 'local to scene' on those same resources. Then I could assign a new viewporttexture (which was automatically local to the scene) in the shader's parameters and it worked!

**Comment by clayjohn** [comment] 2022-12-15 20:53
Update on this issue, it appears that the resize workaround is no longer needed since https://github.com/godotengine/godot/pull/68358 The only issue that remains here is that the update mode "When Visible" is not working. I'm looking into this now. All other update modes are working.

**Closed** 2022-12-17 11:33 UTC
Labels: bug, topic:rendering, confirmed, regression

**Comment by nukeop** [comment] 2023-05-15 23:52
I'm still getting tih sbug in v4.0.2. Fiddling with the settings as proposed previously in this thread didn't help.

**Comment by nvanfleet** [comment] 2023-05-25 23:57
I am seeing this on Mac OS Arm64 4.0.3 version of Godot. It looks like setting the texture programmatically makes it work for me actually.

```
self.plane1.mesh.material.set_shader_parameter("portal_texture", viewport2.get_texture())
```

**Comment by RisingThumb** [comment] 2024-01-20 22:59
> I am seeing this on Mac OS Arm64 4.0.3 version of Godot. It looks like setting the texture programmatically makes it work for me actually.
> 
> ```
> self.plane1.mesh.material.set_shader_parameter("portal_texture", viewport2.get_texture())
> ```

Just adding that I am seeing this in Godot v4.2.1 stable version of Godot, on Arch Linux using the official binaries. What nvanfleet wrote seems to be a workaround for this, so it looks like the issue is something to do with using viewport textures from the scene compared to when it's programmatically added 🤷

**Comment by HeyNinety** [comment] 2024-01-21 04:41
I'm getting this issue as well. Godot v4.2.1 stable. Using Debian 12 KDE X11.

**Comment by lunarcloud** [comment] 2024-02-04 18:32
> I am seeing this on Mac OS Arm64 4.0.3 version of Godot. It looks like setting the texture programmatically makes it work for me actually.
> 
> ```
> self.plane1.mesh.material.set_shader_parameter("portal_texture", viewport2.get_texture())
> ```

Can you provide the full script example? I put this blindly into a script on the subviewport and it clearly needs more setup to work...

**Comment by RisingThumb** [comment] 2024-02-06 23:13
> > I am seeing this on Mac OS Arm64 4.0.3 version of Godot. It looks like setting the texture programmatically makes it work for me actually.
> > ```
> > self.plane1.mesh.material.set_shader_parameter("portal_texture", viewport2.get_texture())
> > ```
> 
> Can you provide the full script example? I put this blindly into a script on the subviewport and it clearly needs more setup to work...

Your mesh should have a material. That material should be a shader. That shader should have a uniform sampler2D with the name "portal_texture". The issue described here, is that setting it in the Engine GUI doesn't work(I.E. clicking the material and clicking the subviewporttexture youw ant), but if you pass it programmatically it does work. I haven't had the time(or a use case) to look into whether this affects other things you can pass a viewport texture to.

This line of code needs to be adapted to get the correct material, and set the correct shader parameter and get the viewport texture. More information needed to point out what you're doing wrong

**Comment by titangrovestudios** [comment] 2024-02-23 09:06
I'm getting this issue as well. Godot v4.2.1 stable. Using Fedora 39 Gnome, none of the above suggestions are working for me.
