### ISSUE TITLE
[3.x] Long scene saving time

### ISSUE THREAD

**Issue by Dadaskis** [godotengine/godot#87665] opened 2024-01-28 08:38 UTC
### Tested versions

- Reproducible in: 3.5.3.stable.

### System information

Windows 11 - Godot v3.5.3.stable - GLES3 - Nvidia Geforce GT1030

### Issue description

![image](https://github.com/godotengine/godot/assets/37717199/e58f4ae7-ec85-4c2e-8d7e-9a387f8aec8b)

Nearly ago i started to have an issue with scene saving. It started to take up to 10 minutes in average (90% spent on "100%" like on image above). I'm not sure what exactly could affect it, but here is what i have:
- A scene itself that usually has quite a bunch of nodes, 300 nodes is minimum that i have in many scenes. All of them are using .tscn format. File size of these varies from 2 MB to 10 MB.
- External resources, such as meshes, materials, LOD meshes, LOD materials and potentially some other things. All of them are saved in .tres format.

I suspect it to be connected to an amount of external resources that i use to lower file size of the scene.

[m_day1_3.tscn.txt](https://github.com/godotengine/godot/files/14075414/m_day1_3.tscn.txt)

I'm going to upload a scene file here to provide a bit more clear understanding what kind of scenes i'm working on. Sorry if it is a bit junky!

### Steps to reproduce

I'm not sure about this one, but:
1. Work on the project that heavily uses external resources and nodes in scenes
2. Save a scene
3. Witness a case similar to an image above

### Minimal reproduction project (MRP)

I'm not really sure what exactly affects the saving times and if it can be fixed on my own. I'll make an MRP later, if you don't mind

**Comment by lawnjelly** [comment] 2024-01-28 11:34
I had a look at the tscn file, but ideally it would be good to profile the project during saving, this can help identify what is the bottleneck (it might be something obvious). We don't get a lot of _huge_ projects for testing so often performance problems with large projects can slip by.

I do have an old PR #70254 which may significantly increase speed, but possibly not for writing (a while since I did this), depending on what is involved during scene saving.

As sending a large project can be difficult (both in terms of size, and sensitivity if a closed source project), then an alternative is for you to compile Godot locally on your machine and profile yourself.

https://docs.godotengine.org/en/3.6/development/compiling/compiling_for_windows.html
https://docs.godotengine.org/en/3.6/tutorials/performance/cpu_optimization.html#cpu-profilers

Alternatively @Calinou has some pre-made debug builds which may be ok for profiling:
https://github.com/Calinou/godot-debug-builds/releases/tag/v3.5.1

The debug build will run slower than release build but might help pin down what is taking the time for you in conjunction with a simple profiler such as `VerySleepy`.

Another option (which some devs use) is if you have the project in a private project on github then temporarily give myself or another maintainer access so we can profile for you.

If you have large numbers of text assets (tscn), especially meshes, then saving some as binary may speed things up too. It's a while since I did this but it may be as simple as saving as `.scn` (there may be caveats as to how editable this might be in future, so you might need to research this / get confirmed before making large changes to your project).

**Comment by Calinou** [comment] 2024-01-28 13:50
You probably have binary resources serialized in one of the `.tscn`/`.tres` files, causing it to be converted to text which is *very* slow and takes a lot of space. Save this binary resource to a separate `.res` file (not `.tres`).

See https://github.com/godotengine/godot/pull/53679.

**Comment by Dadaskis** [comment] 2024-01-28 17:30
@lawnjelly
Thanks for suggestion to profile this project, i hope it is going to be useful for both of us! I temporarily give you access to the private repository of this project. It is quite huge to download as a whole thing, plus the main branch of this project is just a failed attempt to switch over Godot 4, so to save your own time:
```
git clone -b game_purger_3x https://github.com/Dadaskis/IndexProject --depth=1
```

Basically, what you do...
1. Open the project
2. Wait for importing because `.import` is added to `.gitignore`. Sorry!
3. Open `locations/scenes/m_day1_3.tscn` file, that was the last one i could replicate this bug on, but it occurs in each `LocationBase` scene
4. Try placing nodes, maybe try placing props through "PropKit", etc
5. There is also one more heavy thing to try: Press on `LocationBase` scene root node itself, it has a variable named "Resave Meshes", it is a boolean variable that works as a button, so try pressing on it and wait for accomplishment (it is writing logs at output tab). This thing is forcing the mesh instances (in terms of this game level - props and blockout meshes) to take over path of their `Mesh`es as external resources, plus baking "LOD" variants of the said meshes too, which includes materials with embedded `ImageTexture`s

I may have questions beyond this case, also regarding the performance, but this one is making the development itself much harder and i hope it's just my own oversight and misuse of the Godot's system, as it is doing heavy use of external resources in a way it may force them all to resave even if there is no need to

@Calinou 
Damn, gotta find these all. As i mentioned above, there is a button that saves these as external meshes, but i bet it may be some editor-only nodes that use `MeshInstance` are doing that. However, i have one thing to notice... It's weird, but in earlier versions of this project, i saved a lot of meshes inside of a scene file, that resulted in them having a file size more of than 100 MB which made it impossible to store inside of GitHub repository. What is weird for me in this case is that saving of such scene didn't take that long, maybe it was 1-2 minutes, which is surely still long, but less than current case. 
... But i'm going to get rid of these anyway! Gotta keep scene files clean. Thanks for informing

**Comment by lawnjelly** [comment] 2024-01-29 09:55
Have managed to clone it, it's 33Gb uncompressed (without .import folder!). :grinning: 
That's pretty impressive, largest project I've seen to date, I'm not surprised it takes 10 mins to save.
Will try to profile! :+1:

**Comment by lawnjelly** [comment] 2024-01-29 10:59
![profile](https://github.com/godotengine/godot/assets/21999379/3cc21aec-91e9-4a4d-875a-090a3134eef9)

This is profiling saving `m_day1_2.tscn`, during the 100% slow section.

As expected the time is mostly spent with text saving, likely due to many of the scenes being text rather than binary.

**Comment by Calinou** [comment] 2024-01-29 14:11
Closing in favor of https://github.com/godotengine/godot/issues/29381 and https://github.com/godotengine/godot/issues/33379, as this is due to the same cause.

**Closed by Calinou** 2024-01-29 14:11 UTC
Labels: discussion, topic:editor, performance

**Comment by Dadaskis** [comment] 2024-01-29 19:32
@lawnjelly thanks! Gonna try to convert all files related to case (.tscn/.tres of meshes, materials, LOD meshes/materials, physics data) to binary formats, i'm going to report if it will improve the speed over here.

> largest project I've seen to date
Wait, really? .-.
It's impressive for me to hear it from you because you are working on this engine from pretty early days. Also, is it going to be helpful for you to use this project for that kind of testing purposes?

**Comment by lawnjelly** [comment] 2024-01-29 19:44
> Also, is it going to be helpful for you to use this project for that kind of testing purposes?

Yes, definitely, larger projects are great for profiling and finding bottlenecks and problems that don't occur with smaller game jam type games. :+1:

**Comment by Dadaskis** [comment] 2024-01-29 19:52
> Yes, definitely, larger projects are great for profiling and finding bottlenecks and problems that don't occur with smaller game jam type games. 👍

That's great then, i'm going to keep your access for now

**Comment by Dadaskis** [comment] 2024-01-30 02:39
I'm going to write a little report over here as i promised. Honestly, i thought that project won't be able to impress me with that kind of stuff anymore, but yeah, that is definitely the dumbest design flaw that i had yet, and somewhat i love it.

@lawnjelly i highly recommend checking it out on your own, maybe you'll find it interesting

So, what earlier took 10 minutes to save, now takes for about 20-40 seconds to save. I'm going to clarify, what is actually happening during a simple scene saving. When you save a game level in this project, you are not only saving the scene itself, but also external resources, such as:
- Meshes that are used in LocationProp, LocationBlockoutMesh and LocationMeshCombiner
- LOD variants of mentioned meshes, which also includes "LOD material" that represents a simple "bake" of all PBR materials to one simple diffuse material that is shown far away
- Physics data. This project doesn't utilize scenes for game level geometry as i found it very impractical way back when i used Unity somewhere at 2019. Physics data is a way to "cache" the physical collisions that took quite a while to initialize earlier

When i pressed Ctrl + S - that also saved that data, depending on case. Some of these are saved using `ResourceSaver.save` function, but when it is not very fitting in terms of speed, i'm using `Resource.take_over_path`, that is probably forcing it to save resources when i save the scene. I'm still not sure if i have clear understanding of how does saving of resources work in this engine, but that's what i did

What i found more fascinating about this change is that binary formats generally have much lower file size. If you are looking for optimization of file size in your game - that is a way to go. Sorry for russian!
![image](https://github.com/godotengine/godot/assets/37717199/a10a71c0-8c65-428f-bbdb-33498c47b7f4)
![image](https://github.com/godotengine/godot/assets/37717199/9d4b7a0b-5ca3-4249-8b45-2ebf588d99f3)
![image](https://github.com/godotengine/godot/assets/37717199/1934085e-7b5a-4887-be04-1c8c098b78f2)
![image](https://github.com/godotengine/godot/assets/37717199/e1fe9c9c-e276-4dde-884f-3829ec7480e6)
![image](https://github.com/godotengine/godot/assets/37717199/eafb973b-68e8-4b5f-8ee4-0b0001918c6a)

Positive effects after switching over binary formats for location scenes and most of the related external resources:
- Scene saving is much faster. Not instant, but, come on, much better than waiting for 10 minutes each time!
- Opening a scene became faster too
- Lower file size, even if i still didn't fix that problem with meshes stored inside of the scene

@Calinou @lawnjelly - thank you both for helping me out in this case. I'm genuinely interested to know how much of similar problems does this project have. Still feeling like i'm a newbie in this engine

Besides that, i wanted to say that if you need access to that project to test performance in terms of that kind of project, i would like to provide it to anyone that is trustworthy and is willing to keep the data of this project secure and private. It is going to be a commercial release, however, i would love to support the development of this engine at least this way, because probably that is going to be beneficial for everyone. For this project, for the engine development and for the community of Godot. That is probably not the best suggestion as Godot 4.x branch is the main focus of development, while this project is still utilizing Godot 3.x, but i think it is better to suggest it either way
