### ISSUE TITLE
PackedScene circular reference crashes with no warnings or debugging information

### ISSUE THREAD

**Issue by SirLich** [godotengine/godot#74262] opened 2023-03-02 23:44 UTC
### Godot version

4.0.stable

### System information

Windows 10

### Issue description

In brief, circular reference errors are causing the simulated game to crash, with no warnings, errors, logs, or debug information. Breakpoints are not hit either. 

This is the only information available:
![image](https://user-images.githubusercontent.com/18729296/222589600-3f4e92f0-6303-4002-94db-f74058c5bd67.png)

### Steps to reproduce

1. Create a `SceneOne`
2. Create a `SceneTwo`
3. Place `SceneTwo` inside of `SceneOne` (this is setting up our circular reference issue)
4. Add a script to `SceneTwo`, and add the following code: `@export var reference_issue_example : PackedScene`
5. Use the inspector in `SceneTwo` to select `SceneOne` as the value for `reference_issue_example`
6. Simulate `SceneOne` in editor

In this case, I would expect some error like "Circular Reference detected in .... x". Instead the simulation window just closes. No log, no warning, no error. Placing a breakpoint in the `SceneTwo` script is not hit.

### Minimal reproduction project

[test_circular.zip](https://github.com/godotengine/godot/files/10876723/test_circular.zip)

**Comment by AnidemDex** [comment] 2023-03-02 23:50
Related to https://github.com/godotengine/godot/issues/24146 ?

**Comment by Calinou** [comment] 2023-03-03 00:13
Duplicate of https://github.com/godotengine/godot/issues/24146.

**Closed by Calinou** 2023-03-03 00:13 UTC
