### ISSUE TITLE
New mesh materials don't show up in run time, only the imported ones.

### ISSUE THREAD

**Issue by RichardR01** [godotengine/godot#35254] opened 2020-01-17 21:43 UTC
**Godot version:**
3.1.2 stable

**OS/device including version:**
Windows 10 Home version: 1909
GPU Geforce RTX 2080ti driver version: 441.87
CPU AMD Ryzen 7 2700X 3.7GHz
RAM 16GB 3200MHz

**Issue description:**
Complex mesh object loses it's internal shading materials on run time. Shows correctly in editor though.

**Steps to reproduce:**
Create new GLS 3.0 project
Create new 3d scene
Add Child Node under Spatial as Mesh Instance
With the MeshInstance selected, Drag N Drop untitled.obj to the mesh field on the right.
Click on the mesh icon on the right to drop down mesh related fields and options.
Click on Surface1 to drop it down. Do the same for Surface 2.
On Surface1, click on the down arrow "v" to the right of the shader icon and select clear. Do the same for the shader on Surface 2.
On Surface1, click on the down arrow "v" and create a new Spatial Material. Do the same for Surface2.
Make any changes on each of the materials you want but set the albedo colors differently.
Save the scene as TestObj.scn (or whatever you want).
Add a new child to Spatial as a Camera Object. Move and rotate it so it is looking at the 3d object.
Save the scene then press F6 to run it.
You will notice the colors of the mesh object have reverted to the grey materials it once had.

I managed to fix this by removing those materials and putting them on the Material 0 and 1 outside of the mesh options. But I thought I should report this nonetheless.

Also note that when calling $MeshInstance.mesh.Get_Spatial_Material(0) or (1) that it affected the whole material as if both were linked (as they were in the beginning). Calling Get_Spatial_Material without .mesh works as long as the materials are on the outside of the mesh options.

**Minimal reproduction project:**
[TestProject.zip](https://github.com/godotengine/godot/files/4079191/TestProject.zip)

**Comment by Calinou** [comment] 2020-02-02 18:18
Duplicate of #27556.

**Closed by Calinou** 2020-02-02 18:18 UTC
