### ISSUE TITLE
Gamepad analog stick causes OptionButton to scroll continuously on each axis value change

### ISSUE THREAD

**Issue by Iakobs** [godotengine/godot#71918] opened 2023-01-23 15:45 UTC
### Godot version

v3.5.1.stable.official [6fed1ffa3]

### System information

Windows 10, GLES3

### Issue description

Option Button's popup menu doesn't seem to work properly when using an axis (such as a joypad from a controller) to move through the elements of the menu. The movement is triggered during the whole range of movement of the axis

### Steps to reproduce

1. Open the project
2. Connect a joypad (I used an XBOX one via USB)
3. Run the project
4. Try to select an item from the Option Button's popup menu with the left joystick

### Minimal reproduction project

[option_menu_thumbstick_bug.zip](https://github.com/godotengine/godot/files/10481262/option_menu_thumbstick_bug.zip)

**Comment by Calinou** [comment] 2023-01-23 16:12
Can you reproduce this on [4.0.beta14](https://godotengine.org/article/dev-snapshot-godot-4-0-beta-14/)?

**Comment by Iakobs** [comment] 2023-01-23 16:19
> Can you reproduce this on [4.0.beta14](https://godotengine.org/article/dev-snapshot-godot-4-0-beta-14/)?

I'm sorry, are you asking me if I would mind trying to reproduce it in that version or if I have already tried? If it's the latter, I haven't tried. Do you want me to test it there?

Thanks

**Comment by Calinou** [comment] 2023-01-23 16:36
> I'm sorry, are you asking me if I would mind trying to reproduce it in that version or if I have already tried? If it's the latter, I haven't tried. Do you want me to test it there?

Can you try it there? Thanks in advance :slightly_smiling_face:

**Comment by middlepattern** [comment] 2023-01-30 16:11
having same issue. this was apparently happening with general menu items [before](https://github.com/godotengine/godot/pull/59575). this issue effects only the option button it seems.

**Comment by Calinou** [comment] 2023-01-30 16:18
cc @univeous

**Comment by univeous** [comment] 2023-01-30 17:01
Well, I do have some clue. Maybe I'll do a PR tomorrow.

**Comment by univeous** [comment] 2023-01-31 05:49
This issue occurs with other control nodes like Tree, Slider(#62932), ScrollBar, etc. They are all the same problem.
This issue itself also might be a duplicate of #35751.
I could do a quick fix for all of these nodes, but I think the right way to solve this problem is to implement #godot-proposals/4911.
Maybe @Levrault could adjust #63168 to fix all these nodes?

**Comment by Levrault** [comment] 2023-01-31 12:12
Hi @univeous I will re-work on my PR and applied the same fix on all mentionned nodes in https://github.com/godotengine/godot/pull/63168

**Comment by BlooRabbit** [comment] 2023-02-03 21:22
An is_echo() function for gamepads would solve this issue in a great way. Right now I am doing this in GDscript with timers all over the place, which is an ugly hack. Having this functionality built into the engine would avoid this unnecessary hack and provide control over when to use it and when not. Finally it would make it consistent with keyboard input.

**Comment by Calinou** [comment] 2023-02-13 19:17
Duplicate of https://github.com/godotengine/godot/issues/35751.

**Closed by Calinou** 2023-02-13 19:17 UTC
Labels: bug, confirmed, topic:input, topic:gui

**Comment by anthonyjb** [comment] 2024-10-19 21:29
For anyone who finds this and is still using Godot 3 (I'm on 3.6) this is my workaround. I have a Control parent the OptionButton with the following script attached to it (could probably be added to the control directly as well):

```
extends Control


# Private members

# The last joypad motion direction used
var _last_direction = -1


# Lifecycle method

func _input(event):

    if not $'OptionButton'.get_popup().visible:
        return

    if event is InputEventJoypadMotion and event.axis == JOY_ANALOG_LY:

        var direction = 0
        if event.axis_value > 0.5:
            direction = 1
        elif event.axis_value < -0.5:
            direction = -1

        if direction == self._last_direction:
            get_tree().set_input_as_handled()

        self._last_direction = direction
```
