### ISSUE TITLE
Can't set looping mode on AudioStreamPlayer in the Inspector

### ISSUE THREAD

**Issue by hpvb** [godotengine/godot#11231] opened 2017-09-13 09:48 UTC
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Unknown but some 3.0 version, reported through Facebook

**Issue description:**
From the FaceBook post:

> There is no option to set audio looping in AudioStreamPlayer in Godot3.
> Anyone knows a solution?
>  I set using .get_stream().set_loop(false), but there is no option in the editor's inspector to set it.

**Steps to reproduce:**

**Link to minimal example project:**

**Comment by akien-mga** [comment] 2017-09-13 11:39
See https://github.com/godotengine/godot/issues/9928#issuecomment-318718969, loop is an import option.

**Comment by hpvb** [comment] 2017-09-13 11:48
But is the problem we're not exposing 'loop' as an editor option? I'm actually not sure if this a bug or not. But if you can set_loop(false) from GDScript I'd kind of expect an editor field for it too.

**Comment by razvanc-r** [comment] 2017-09-15 06:32
This is a duplicate of #10726

@akien, you marked that as a bug, what changed? :D

**Comment by akien-mga** [comment] 2017-09-16 18:03
As far as I understand #10726 is about not being able to set loop on import for OGG Stream, while it's apparently possible for WAV, so it sounds like an inconsistency/a bug.

This issue here is about not being able to set the loop in the player, but having to define it as import, which is apparently the desired behaviour as described in #9928, hence the "discussion" tag :)

**Comment by hpvb** [comment] 2017-09-18 21:20
I don't think it's bad that it's an import option, but I do think it's bad that the property is accessible through gdscript to change later. If it's exposed as a property it would be less surprising if it's also available in the editor.

If not we should probably make it read-only from GDScript, but that seems wrong also.

**Comment by reduz** [comment] 2017-09-18 21:35
It should be accessible in AudioStreamOGGVorbis...

**Comment by akien-mga** [comment] 2018-01-08 10:57
We have now entered release freeze for Godot 3.0 and want to focus only on release critical issues for that milestone. Therefore, we're moving this issue to the 3.1 milestone, though a fix may be made available for a 3.0.x maintenance release after it has been tested in the master branch during 3.1 development. If you consider that this issue is critical enough to warrant blocking the 3.0 release until fixed, please comment so that we can assess it more in-depth.

**Closed** 2019-11-11 15:07 UTC
Labels: bug, discussion, enhancement, topic:audio
