### ISSUE TITLE
Direct changes of member variables trigger parent's setter

### ISSUE THREAD

**Issue by ichbindu** [godotengine/godot#46864] opened 2021-03-10 11:11 UTC
**Godot version: 3.2.3 stable**

**OS/device including version: macOS 11.2.1**

**Issue description:**

I just came across the following issue and judging by the documentation and other discussions, this doesn't seem like expected behavior. Basically changing a member variable of an object -- which is stored in a member variable of another object with a setter defined -- will trigger the parent object's setter. 

_Setget_test.gd:_
```
extends Spatial

var an_object_script = preload("An_object.gd")
var some_object setget set_some_object

func _ready():
	self.some_object = self.an_object_script.new() # -> triggers set_some_object as expected
	self.some_object.some_member_variable = 1 # -> unexpectedly also triggers set_some_object

func set_some_object(o):
	some_object = o
	print("setter triggered")
```

_An_object.gd:_
```
extends Node

var some_member_variable = 0
```

_Output_:
```
setter triggered
setter triggered
```

**Minimal reproduction project:**
[Setget_test.zip](https://github.com/godotengine/godot/files/6115244/Setget_test.zip)

**Comment by KoBeWi** [comment] 2021-03-10 11:36
Duplicate of #28720

**Closed by KoBeWi** 2021-03-10 11:36 UTC
