### ISSUE TITLE
Viewport Scaling breaks local input (mouse position)

### ISSUE THREAD

**Issue by michael-nischt** [godotengine/godot#60925] opened 2022-05-10 14:48 UTC
### Godot version

v3.4.4.stable.official [419e713a2]

### System information

Arch Linux, NVIDIA GeForce RTX™ 3080 Laptop GPU, GLES3

### Issue description

The [viewport.get_mouse_position()](https://docs.godotengine.org/en/stable/classes/class_viewport.html#class-viewport-method-get-mouse-position) isn't in local space if its inside a _ViewportCotainer_ with stretch enabled.

The prevents the [3D Viewport Scaling](https://godotengine.org/asset-library/asset/586) demo's approach from being actually useful with mouse inputs.

Further, I believe there's an issue with the _ViewportCotainer_ disabling the child _Viewports_ "handle inputs locally" property setting **when the project is (re-loaded)**. Aftewards you can enable it but to no effect. It stays enabled in the UI (even play/stop) but the coordinates are still global. Every project reload sets it back to `false` though. Which is super confusing as the issue only gets noticed on reloading the whole project (or maybe scene?).

**UPDATE:** If in the the project settings the test width & height are different than the actual width & height it further distorts the mouse position.

### Steps to reproduce

Run the minimal project, press SPACE until resolution is set to 25%. Then left click close in the center of the window with the mouse and see that lowres viewports mouse position is reported in the resolution of the root viewort.

```
print("%s / %s | %s" % [get_viewport().get_mouse_position(), get_viewport().size, get_viewport().get_path()])
```
E.g.:

```
(528, 316) / (256, 150) | /root/HUD/ViewportContainer/Viewport
```

### Minimal reproduction project

[vpscale.zip](https://github.com/godotengine/godot/files/8662512/vpscale.zip)

It's the [3D Viewport Scaling](https://godotengine.org/asset-library/asset/586) demo with a minimal script attached to the Cubes.tscn root object:

```GDscript
extends Spatial

func _process(delta):
	if Input.is_action_just_released("action"):
		print("%s / %s | %s" % [get_viewport().get_mouse_position(), get_viewport().size, get_viewport().get_path()])
```

**Comment by Calinou** [comment] 2022-05-10 15:40
Duplicate of https://github.com/godotengine/godot/issues/34805.

**Closed by Calinou** 2022-05-10 15:40 UTC
