### ISSUE TITLE
Fonts look blurry on high-resolution screens

### ISSUE THREAD

**Issue by anunknowperson** [godotengine/godot#51135] opened 2021-08-01 06:18 UTC
### Godot version

4.0.dev (007b877cb)

### System information

Windows 10, Vulkan Clustered, RTX 3060 Ti / GTX 1650 ti

### Issue description

On screen with 2560x1440 resolution and 125% display size fonts on master branch looks blurry
![Screenshot_10](https://user-images.githubusercontent.com/54563399/127761352-8536b21e-d3d8-4653-9231-ee6127db728c.png)
![Screenshot_11](https://user-images.githubusercontent.com/54563399/127761353-de843637-7151-4a46-8d03-40b43d79c984.png)

4.0 vs 3.3
![Screenshot_11](https://user-images.githubusercontent.com/54563399/127761460-fb967d24-aa50-455e-9648-c50de9bf13c1.png)

try zooming in.

### Steps to reproduce

Open editor on 2560x1440 screen and set 125% display size.

**Comment by Calinou** [comment] 2021-08-01 14:25
Duplicate of https://github.com/godotengine/godot/issues/44431.

**Closed by Calinou** 2021-08-01 14:25 UTC
