### ISSUE TITLE
Adding operators to make animation relative to the current state

### ISSUE THREAD

**Issue by ticnew** [godotengine/godot#31035] opened 2019-08-02 15:02 UTC
so basically this is feature request, i'm working on a game currently and i have character that i wanted him to be pushed back when he got a hit relative to the current location without touching the code, because this push is part of the animation, so it will be handy if there are operators can be add to the value field or drop down option appear beside the key frames like "relative add" or "relative substrate" or like operators += -= *= /= %= to each field that is single value or vector

**Comment by KoBeWi** [comment] 2019-08-02 15:04
Duplicate of #4263

**Closed by KoBeWi** 2019-08-02 15:04 UTC
