### ISSUE TITLE
[3.2.4 rc1] Engine crashes on export when having Android custom build in the project folder

### ISSUE THREAD

**Issue by floppyhammer** [godotengine/godot#45600] opened 2021-01-31 08:56 UTC
Godot version:
3.2.4 rc1

OS/device including version:
Windows 10

Issue description:
Engine crashes on export (no matter to which platform) when having Android custom build in the project folder. Nothing special shows on the system console when it crashes. Have to delete the "android" folder to get it work. This only happens after several successful exports using the custom build and can be avoided by reinstalling the custom build template. I had not experienced this until I started using 3.2.4 rc1.

Steps to reproduce:
This issue is quite hard to reproduce. I only encountered it twice when working on my project. But considering the the release date of rc1 is not very long ago, I doubt it is just an individual case. I report this in case others also bump into a similar issue.

**Comment by mbrlabs** [comment] 2021-01-31 14:59
It didn't crash for me, i just had lot's of errors to relsove because some Gradle scripts and the Android Manifest changed. `GodotApp.java` also changed. Once i got it working i ran into #45606 though, which i can even reproduce with a simple empty project.

**Comment by floppyhammer** [comment] 2021-02-01 14:11
I have no problem getting my game signed (with debug key) and running on Android except for this irregular issue. And I found this issue appears more frequently when I use Deploy with Remote Debug instead of manually copying and installing the exported APK on my mobile. I switched back to beta6 to see if this is a regression issue.

**Comment by m4gr3d** [comment] 2021-02-02 08:38
@floppyhammer Thanks for reporting the issue. I'll take a look and attempt to reproduce it.

**Comment by floppyhammer** [comment] 2021-02-03 04:15
This also happens to 3.2.4.beta6.
![screen-record](https://user-images.githubusercontent.com/28705694/106697243-528b2b80-6619-11eb-98f3-e8f396304728.gif)

**Comment by m4gr3d** [comment] 2021-02-09 07:33
@floppyhammer There seems to be error logs in the output console in your recording. Can you provide these logs.

Also grab the following files:
- `manifest-merger*report` files from the `android/build/build/outputs/logs` directory
- `lint-results-*` files in the `android/build/build/reports` directory

**Comment by floppyhammer** [comment] 2021-02-09 08:15
@m4gr3d I don't see the `android/build/build/reports` directory.

The only errors in the Godot log file are related to Nakama.
[godot.log](https://github.com/godotengine/godot/files/5949787/godot.log)

There's only one file in the `android/build/build/outputs/logs` directory.
[manifest-merger-debug-report.txt](https://github.com/godotengine/godot/files/5949789/manifest-merger-debug-report.txt)

**Comment by m4gr3d** [comment] 2021-02-09 08:28
@floppyhammer Can you see if you can reproduce the issue in `3.2.3` stable. I'm trying to confirm whether this is a regression or whether it's a bug that had escaped our notice.

**Comment by floppyhammer** [comment] 2021-02-09 10:07
@m4gr3d Yes, I will.

**Comment by floppyhammer** [comment] 2021-02-13 03:53
@m4gr3d I don't think this issue is reproducible in `3.2.3.stable`. I switched back to stable and haven't met the issue yet developing on the same project.

**Comment by m4gr3d** [comment] 2021-02-17 20:06
@floppyhammer I've a [pull request](https://github.com/godotengine/godot/pull/46136) in flight to add more logging which should help with troubleshooting the issue.

If you're able to, can you patch PR #46136, enable verbose logging, and provide the resulting output logs.
If you don't know how to build the Godot editor from source, let me know and I can try to provide a generated binary.

**Comment by floppyhammer** [comment] 2021-02-18 01:44
@m4gr3d Yes, I know how to do it. But I have a question. If I build the editor from the current 3.2 branch, can I use it with the previously released rc2 export templates?

**Comment by m4gr3d** [comment] 2021-02-18 03:01
@floppyhammer You can but your built version will look for the templates in a `3.2.4.rc` directory whereas the rc2 export templates will be in a `3.2.4.rc2` directory.
You can easily fix that by copying the files from the `3.2.4.rc2` directory into the `3.2.4.rc` one.

**Comment by floppyhammer** [comment] 2021-02-18 14:33
@m4gr3d I did as you said, and the templates are now working. I will try to reproduce the issue.

**Comment by floppyhammer** [comment] 2021-02-18 14:50
@m4gr3d This is what it says when the engine crashes:
![image](https://user-images.githubusercontent.com/28705694/108374121-91d19300-723b-11eb-96da-d7afdcb2084a.png)

**Comment by m4gr3d** [comment] 2021-02-18 17:54
@floppyhammer Can you provide the full logs from the beginning of the build; it should start with `Exporting for Android...`.

**Comment by m4gr3d** [comment] 2021-02-18 17:58
@floppyhammer Also does this occur when you deploy with `remote debug` or for any export?
Do you have any `gradle.conf` or `AndroidManifest.conf` files in your project?

**Comment by floppyhammer** [comment] 2021-02-19 00:57
@m4gr3d Godot's file log got truncated somehow, but I managed to copy console content before it shut down.
[godot.log](https://github.com/godotengine/godot/files/6006803/godot.log)
[console-output.txt](https://github.com/godotengine/godot/files/6006814/console-output.txt)

It occurs as long as I use Android custom build. But it seems using `remote debug` increases the probability of occurrence. And once it occurs, it would crash the engine no matter which export I use or whether the `use_custom_build` option in Android export settings is enabled. The only solution is to delete the custom build or reinstall it.

No, I don't have those two files in my project. The `Android` folder is automatically generated in my project when installing Android custom build, and I didn't add any other Android related file besides that.

Console output for Windows export:
[console-output-windows.txt](https://github.com/godotengine/godot/files/6006844/console-output-windows.txt)

Console output for Android export when `use_custom_build` is disabled:
[console-output-android.txt](https://github.com/godotengine/godot/files/6006848/console-output-android.txt)

**Comment by m4gr3d** [comment] 2021-02-19 03:22
@floppyhammer I've noticed this line in your log:
```
TODO_Manager: There was an error at: res://android/build/build/intermediates/compressed_assets/debug/out/assets/android/build/build/intermediates/merged_assets/debug/out/android/build/build/intermediates/merged_res_blame_folder/debug/out/multi-v2
```

This sounds similar to issue #42982. Can you remove the `android` folder once more, export a couple of times and provides the logs.
It seems the engine is somehow parsing the `android` folder as well when it shouldn't. The logs from successful exports should allow me to track down why the `android` folder is being included.

**Comment by floppyhammer** [comment] 2021-02-19 03:47
@m4gr3d 
[console-output-without-android-folder.txt](https://github.com/godotengine/godot/files/6007561/console-output-without-android-folder.txt)

**Comment by m4gr3d** [comment] 2021-02-19 03:55
@floppyhammer Sorry I meant to reinstall the `android` folder then run a couple of times with custom build enabled.

**Comment by floppyhammer** [comment] 2021-02-19 04:13
@m4gr3d It's okay. Here.
[console-output-successful-exports.txt](https://github.com/godotengine/godot/files/6007624/console-output-successful-exports.txt)

**Comment by m4gr3d** [comment] 2021-02-19 04:31
@floppyhammer Thanks for the updated logs, they're showing where the issue starts!
On the second run, you can see in the logs that the engine starts processing some of the files generated by the first build:
```
Saving project files from res://android/build/build/intermediates/annotation_processor_list/debug/annotationProcessors.json into res://android/build/assets/android/build/build/intermediates/annotation_processor_list/debug/annotationProcessors.json
```

@akien-mga @Calinou Any idea why this could occur? There's a `.gdignore` file in the `android/build` folder so in theory it shouldn't be processed by the engine.

**Comment by m4gr3d** [comment] 2021-02-22 05:45
@floppyhammer @HEAVYPOLY Can you cherry-pick https://github.com/m4gr3d/godot/commit/78dacb7e489928c25797cc39ac0ba9de2253111c into your local Godot builds.

Once you have a build, reinstall the `android` folder by reinstalling the Android build template, then perform an export a couple of times with custom build enabled in order to generate the relevant logs.

@floppyhammer This is similar to what you did before; with the extra logs I'm hoping to be able to track down where the Android directories and files are being added. As mentioned in the previous comment, in theory, the `.gdignore` should prevent that from happening, so there may a bug preventing that from happening.

**Comment by floppyhammer** [comment] 2021-02-22 07:52
@m4gr3d Let me know if you need more info.
[console-output.txt](https://github.com/godotengine/godot/files/6020300/console-output.txt)

**Comment by m4gr3d** [comment] 2021-02-22 18:45
@floppyhammer Thanks for the logs! It doesn't look like the `android` directory is being added as part of the indexing logic, so I'm struggling to see how it's added to the build process.. 

@floppyhammer Can you cherry-pick https://github.com/m4gr3d/godot/commit/8df3d5d01901afae5539a99b850b104b9fbf58b5 and perform the same steps as above. 
This commit attempts to fix the issue by hardcoding a filter for the `android` directory. This is only a workaround, but it should resolve the issue for the time being.

@akien-mga We may have to move the `android` directory outside of the `res://` directory to mitigate any future issues. Likely candidate could be the `data/settings` directory. Thoughts?

**Comment by m4gr3d** [comment] 2021-02-22 21:56
@floppyhammer @HEAVYPOLY I'm able to reproduce the issue if I add in the export `include` section a file extension or filename contained in the `android` directory (e.g: `*.json`, `*.png`).

Do you have anything listed in the `include` section for your Android exports?

**Comment by floppyhammer** [comment] 2021-02-23 00:03
@m4gr3d Yes, I have `*.json` in the filters.

**Comment by m4gr3d** [comment] 2021-02-23 00:08
> @m4gr3d Yes, I have `*.json` in the filters.

That confirms the source of the issue then! The filter include logic disregards the `.gdignore` file and walk down the directory tree to fetch resources to be included. I'm preparing a pull request to update that so that it respects the `.gdignore` file.

**Comment by HEAVYPOLY** [comment] 2021-02-23 00:13
I have .import and the entire android folder in the exclude filters. 
<img width="419" alt="image" src="https://user-images.githubusercontent.com/24432677/108786643-e4a39700-7528-11eb-8524-491773547460.png">

**Comment by m4gr3d** [comment] 2021-02-23 00:24
> I think there were errors related to .import files in android custom build.

@HEAVYPOLY For these errors, can you double-check the `.gdignore` file is in the `res://android/build` directory.
If it's, can you delete and reinstall the `android` directory and see if you can recreate the issue.

**Comment by m4gr3d** [comment] 2021-02-23 04:24
@floppyhammer @HEAVYPOLY Can you test #46336 and see if it addresses the issue you were seeing.

**Comment by floppyhammer** [comment] 2021-02-23 06:19
@m4gr3d I failed to cherry-pick #46336 as there were conflicts. Will it work if I just build from that branch?

![image](https://user-images.githubusercontent.com/28705694/108808562-dd8c8f80-75e1-11eb-99d9-c2a23cdb06ce.png)

**Comment by m4gr3d** [comment] 2021-02-23 06:34
> Will it work if I just build from that branch?

@floppyhammer Yes, that will work.

**Comment by akien-mga** [comment] 2021-02-23 10:26
> I have .import and the entire android folder in the exclude filters

Side note, but be aware that the `.import/` folder is meant to be included in the exported PCK, that's where all imported resources reside that your project actually needs. As long as you don't use *any* imported resource (PNG, WAV, etc.) like I think you do in Heavypaint it should be fine, but at the same time it's likely not necessary to exclude `.import/` as it shouldn't contain much (aside from `icon.png` maybe).

**Comment by floppyhammer** [comment] 2021-02-23 10:59
@m4gr3d As I exported dozens of times and haven't experienced a crash yet, I say you nailed it!

**Comment by m4gr3d** [comment] 2021-02-24 14:57
@floppyhammer Great to hear!

Can you also double-check in the logs that the export process doesn't attempt to save any files from the `android/build` directory.

**Comment by floppyhammer** [comment] 2021-02-25 01:24
@m4gr3d I can confirm it doesn't.

**Closed** 2021-02-25 13:14 UTC
Labels: bug, crash, platform:android, regression, topic:editor
