### ISSUE TITLE
Editor doesn't detect external scene changes and silently overwrites file

### ISSUE THREAD

**Issue by DjPale** [godotengine/godot#8615] opened 2017-05-01 18:11 UTC
**Operating system or device - Godot version:**
Mac OS X 10.11.6, Windows 10
Godot version v2.1.3.stable.offical

**Issue description:**
When updating a scene outside the Godot instance, it is overwritten without any warnings / messages etc.

This means that in practice - you have to close down a scene before doing things like for example git sync. One could discuss the practice of editing the same scene at once, but a least a warning or an indicator or similar would have been beneficial. Other parts of Godot handle automatic reloading and many editors warn you about file changes outside the disk. We discovered this during LD and it became hard to  patch stuff up.

**Steps to reproduce:**
1. Start an empty project
2. Add a root node of any type
3. Add 2 children of the root node of any type
4. Save the instance as .tscn
5. In another Godot instance or a plain text editor, remove the second child and save the file
6. Return to the first Godot instance and Run the scene 
7. If you inspect the .tscn, you see that the second child has returned (like a creepy horror movie)

**Link to minimal example project:**
Not needed

**Comment by puppetmaster-** [comment] 2017-05-02 12:04
Need some testing but we got message (file has change) when scene is open in editor and markt as changed(*) and "sometimes" it doesn't overwrite when scene isn't open in editor.

**Comment by nbcks** [comment] 2017-07-30 12:00
I'm getting the same issue here - would be nice to have a referesh button that would resync the scene with the file .tscn or to have it automatically detect a change.

**Comment by Zylann** [comment] 2017-09-05 12:38
That can be problematic for client/server where you need to have two Godots open for simultaneous debugging

**Comment by neikeq** [comment] 2017-09-11 15:30
Just wondering, is there any error message in the console?

**Comment by kubecz3k** [comment] 2018-04-19 18:16
First of all thank you for your report and sorry for the delay.

We released Godot 3.0 in January 2018 after 18 months of work, fixing many old issues either directly, or by obsoleting/replacing the features they were referring to.

We still have hundreds of issues whose relevance/reproducibility needs to be checked against the [current stable version](https://godotengine.org/download), and that's where you can help us.
**Could you check if the issue that you described initially is still relevant/reproducible in Godot 3.0 or any newer version, and comment about its current status here?**

For bug reports, please also make sure that the issue contains detailed steps to reproduce the bug and, if possible, a zipped project that can be used to reproduce it right away. This greatly speeds up debugging and bugfixing tasks for our contributors.

Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

Thanks in advance.

*Note: This message is being copy-pasted to many "stale" issues (90+ days without activity). It might happen that it is not meaningful for this specific issue or appears oblivious of the issue's context, if so please comment to notify the Bugsquad about it.*

**Comment by Calinou** [comment] 2018-05-16 19:13
Closing as a duplicate of #11803, which has more information about the issue.

**Closed by Calinou** 2018-05-16 19:13 UTC
Labels: enhancement, topic:editor, usability

**Comment by dognew** [comment] 2018-05-16 20:47
Tested in Godot v3.0.stable.official

Godot not identify modified file edited externally.
