### ISSUE TITLE
For a scene inherited from a model, when I change the root node's type, the scene loses its reference to ext_resource

### ISSUE THREAD

**Issue by MadIcecream** [godotengine/godot#11172] opened 2017-09-11 16:58 UTC
And the mesh becomes a built-in resource.

**Comment by Noshyaar** [comment] 2017-09-11 18:22
Version?

**Comment by cutepig49** [comment] 2017-09-12 04:47
What I used is calinou's build, I don't know the exactly version.
https://bintray.com/calinou/godot/editor/2017-09-08.519b933

**Comment by bojidar-bg** [comment] 2017-09-12 05:59
Duplicate of #6215?

**Comment by mhilbrunner** [comment] 2018-04-10 19:11
Closing as a duplicate of #6215.

**Closed by mhilbrunner** 2018-04-10 19:11 UTC
Labels: bug, topic:core
