### ISSUE TITLE
Wrong lightness of textures with alpha channel and translucent pixels on Android

### ISSUE THREAD

**Issue by Ralf12358** [godotengine/godot#40541] opened 2020-07-20 13:14 UTC
**Godot version:**
Head on Branch 3.2: 89f57ae12244f3269c9e3fe4684e16ec1fd2c989
Reproduced on 3.2.3beta1, too. Probably older version are affected, too

**OS/device including version:**
GLES2, Android. Tested with Galaxy S7 Edge and Amazon Fire HD 8

**Issue description:**
Please read carefully. Issue description may sound strange, but it's an annoying and often subtle bug. Attached is a sample project to easily reproduce the problem on Android.
When adding a textured quad mesh with an alpha channel where at least on pixel has an alpha != 1.0 to a 3D scene. The quads on Android are rendered too dark (see screenshots below).

The "funny" part is:

- If the quads are scaled from 1.0 to 2.0 the problem nearly disappears (This has caused me some headaches).
- The problem is independently if "Transparent" is enabled in the spatial material or disabled.
- If the png file of the texure has an alpha channel with all pixels completely opaque the problem disapears (The png may still have an alpha channel)

The problem is probably unrelated to the quad mesh and more related to dealing with textures on Andoird in general.

The screenshots below contain two pngs: One completely opaque, but with alpha channel. One with some transparent pixels.

Android Small (**Here** the problem is visible):
![AndroidSmall](https://user-images.githubusercontent.com/34693046/87939332-37e7cf80-ca98-11ea-90ee-4a0fec68cf5b.jpeg)

Linux Small:
![LinuxSmall](https://user-images.githubusercontent.com/34693046/87939359-42a26480-ca98-11ea-9e48-32b394e1f52e.jpeg)

Android Large:
![AndroidLarge](https://user-images.githubusercontent.com/34693046/87940463-eccebc00-ca99-11ea-92bc-8196376e47b6.jpeg)

Linux Large:
![LinuxLarge](https://user-images.githubusercontent.com/34693046/87940482-f35d3380-ca99-11ea-9a14-d4874b9e3074.jpeg)

**Steps to reproduce:**
Best use attached sample project.
Create new 3D scene. Add camera. Add Light. Add two quad meshes. In on mesh use a texture with alpha channel and some transparent pixels in the other mesh us a texture completely opaque with alpha channel, too. Quads have to be the correct size (usually relative small) to  reproduce the bug. On Android the two quad will have different lightness. On Linux and browser both quad will have the same lightness.

**Minimal reproduction project:**
[GodotAlphaBug.zip](https://github.com/godotengine/godot/files/4947845/GodotAlphaBug.zip)

**Comment by Ralf12358** [comment] 2020-07-21 10:05
I forget: This problems occurs, even if the materials are declared **Unshaded** (!!!).

=> This seems a pure texture problem unrelated to the lightning

Attached is another screenshot from Android with materials set to "Unshaded". If you look closely you will recognize it is different to the other Android screenshot with shading enabled, but the problem persists, anyway: All textures should have the same lighness.

![AlphaBug_Android_Unshaded](https://user-images.githubusercontent.com/34693046/88041013-0deee580-cb4a-11ea-8880-dca864165dda.jpeg)

**Comment by Calinou** [comment] 2020-07-21 10:07
@Ralf12358 Double-check that the textures is imported with sRGB enabled. Also, does this occur if you change its compression mode to Uncompressed or Lossless in the Import dock?

**Comment by Ralf12358** [comment] 2020-07-21 11:13
@Calinou: That's it! I set the Compress mode manually to "Uncompressed" and the problem is, gone! Thank's. I think you can close the issue. It might be worth considering to automatically import textures with alpha pixels != 1.0 as uncompressed on GLES2, but that's up to you.

Thank's again.

**Comment by Calinou** [comment] 2020-07-21 11:54
@Ralf12358 Alright, I'll close this as a duplicate of #26211 then.

**Closed by Calinou** 2020-07-21 11:54 UTC
Labels: bug, platform:android, topic:rendering
