### ISSUE TITLE
Immersive mode OFF for Android still doesn't show the status bar

### ISSUE THREAD

**Issue by andrea-calligaris** [godotengine/godot#48811] opened 2021-05-18 14:12 UTC
**Godot version:**
3.3

**Issue description:**
When trying to make an app for Android.
Godot → Project → Export → Android → Options → Screen → Immersive mode OFF
This should show the status bar (top of the screen) and the navigation bar (bottom of the screen), however it only shows the navigation bar, both in the virtual machine and on actual smartphone after installing the APK; no status bar, which is available only when swiping down.
Some workarounds on the internet says to change "AndroidManifest.xml" but it gives me errors because they're outdated articles.
I would appreciate an updated workaround, while waiting for a bugfix.
Thanks.

**Comment by Calinou** [comment] 2021-05-18 15:24
@char0xff Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

Also, did you export the project using the APK-based workflow or the new [custom build](https://docs.godotengine.org/en/stable/getting_started/workflow/export/android_custom_build.html) workflow?

**Comment by char0xff** [comment] 2021-05-18 15:58
The minimal reproduction project is just an empty project.

>Also, did you export the project using the APK-based workflow or the new custom build workflow?

I tried both.

>See also #19835.

That's what I was talking in OP. "@android:style/Theme.NoTitleBar.Fullscreen" is not recognized anymore and so it throws an error, we need an updated workaround. I'll try again though, just to be sure.

**Comment by char0xff** [comment] 2021-05-18 18:36
Ok, I got no error but still no status bar.
I changed "AndroidManifest.xml" like this:
```
<activity
            [...]
            android:theme="@android:style/Theme.Black.NoTitleBar"
```

**Comment by char0xff** [comment] 2021-05-18 19:40
Ok, I solved by going to "android/build/res/values/themes.xml" and changing
`<style name="GodotAppMainTheme" parent="@android:style/Theme.Black.NoTitleBar.Fullscreen"/>`
to
`<style name="GodotAppMainTheme" parent="@android:style/Theme.Black.NoTitleBar"/>`

Of course I'm leaving this open because it's just a workaround. If you disable "Immersive mode" this should be automatic and you shouldn't be required to do a custom build.

**Comment by char0xff** [comment] 2021-06-19 19:56
Ok, so, this is fixed in 3.3.2.stable for some reason.

**Comment by char0xff** [comment] 2021-07-21 15:44
Ok, it's not actually fixed: it works on some phones on the emulator, but not on my RL phone.
So the only way to actually show the status bar in all phones is the workaround as in my comment https://github.com/godotengine/godot/issues/48811#issuecomment-843493334
Also see #19835, which correctly suggests that this should be done automatically when you've chose "Immersive mode OFF".

**Comment by blurrred** [comment] 2021-08-14 03:59
I tried your workaround and it didn't work for me.
Using a Galaxy S8.

**Comment by char0xff** [comment] 2021-08-16 13:13
> I tried your workaround and it didn't work for me.
> Using a Galaxy S8.

Just to be sure, did you edit the file _"android/build/res/values/themes.xml"_ and **not** _"AndroidManifest.xml"_?

**Comment by blurrred** [comment] 2021-08-31 19:55
> Just to be sure, did you edit the file _"android/build/res/values/themes.xml"_ and **not** _"AndroidManifest.xml"_?

Yes

**Comment by blurrred** [comment] 2021-09-19 20:05
I had to migrate my project to a new computer. I tried implementing your workaround again and this time it worked.
Not sure what the issue was before, but I'm glad it's working now. Thank you.

**Comment by char0xff** [comment] 2021-09-20 08:42
@blurrred Nice.
For the next time I would just try to delete certain Android SDK folders:
```
".cache/Android Open Source Project/"
".config/Android Open Source Project/"
".cache/Google/AndroidStudio4.2/"
".config/Google/AndroidStudio4.2/"
".gradle/"
".local/share/Android Open Source Project
".local/share/Google"
```
And if it still doesn't work, remove Android Studio:
```
"android-studio/"
"Android/"
".android/"
```
and reinstall it.

**Comment by MiqueiasDevGames** [comment] 2022-03-01 21:07
@Calinou 

What changes when I activate or deactivate the immersive mode when exporting?

It's the AndroidManifest.xml
android:immersive="true" ?

**Comment by Calinou** [comment] 2022-03-01 23:17
@MiqueiasDevGames [Enabling the immersive mode export option enables the `--immersive-mode` option](https://github.com/godotengine/godot/blob/62765fb7ca7cca7ae0c56be99cc99d9b3b0bd040/platform/android/export/export_plugin.cpp#L2296-L2299) [when the Android Java layer is run](https://github.com/godotengine/godot/blob/62765fb7ca7cca7ae0c56be99cc99d9b3b0bd040/platform/android/java/lib/src/org/godotengine/godot/Godot.java#L510-L521).

**Comment by MiqueiasDevGames** [comment] 2022-03-14 21:15
Android 12 SplashScreen Godot


[https://github.com/MiqueiasDevGames/Godot-SplashScreen-Android-12](https://github.com/MiqueiasDevGames/Godot-SplashScreen-Android-12)

**Closed** 2022-05-31 10:39 UTC
Labels: bug, platform:android, topic:porting, topic:export
