### ISSUE TITLE
Vector2(position) constructor causes an error

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#24001] opened 2018-11-26 23:43 UTC
Godot 3.1 alpha2

I get an error when I try to construct a `Vector2` from another one:
```gdscript
extends Node2D


func _draw():
	var pos = self.position
	var angle = PI
	draw_set_transform(Vector2(pos), angle, Vector2(1,1))
```

Causes an error at the last line:
```
SCRIPT ERROR: GDScript::reload: Parse Error: No constructor of 'Vector2' matches the signature 'Vector2(var)'.
          At: built-in:7
```

This code worked in Godot 3.0.6, although I have to admit it can be fairly simplified :p
The same happens with Vector3.

**Comment by aaronfranke** [comment] 2018-11-27 06:33
Are you sure that it worked in 3.0.6? I didn't think that this feature existed before.

I added this (and a few other things) here: https://github.com/godotengine/godot/pull/21348

**Comment by Zylann** [comment] 2018-11-27 11:20
It worked before because I tested it :) it was part of my codebase for a long time as well

**Comment by Gramps** [comment] 2019-03-06 23:40
Yeah, I am getting this same error in 3.1 on code that ran fine in 3.0.6; passing a position variable that is created on the fly causes it.  Game won't even run now because of it.

**Comment by aaronfranke** [comment] 2019-07-20 19:13
I did some regression testing using git bisect, this is caused by https://github.com/godotengine/godot/pull/19264

@vnen The fix for this seems pretty simple, but the concern that @akien-mga had was that it would be hiding a deeper bug. Would you mind looking into it?

**Comment by vnen** [comment] 2020-01-09 12:10
Sorry for the delay on this. It seems the fix wasn't very difficult, I just hadn't the time.

**Closed** 2020-01-09 12:42 UTC
Labels: bug, topic:gdscript
