### ISSUE TITLE
AnimatedSprite can be convert to the tilemap?

### ISSUE THREAD

**Issue by sersoong** [godotengine/godot#11225] opened 2017-09-13 04:13 UTC
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
win7 64

**Proposal:**
Stationary tilemap looks not good enough.
May be the AnimatedSprite  can be convert to a tileset,and tilemap can use it?

**Comment by bojidar-bg** [comment] 2017-09-13 05:33
Duplicate of #9179.

**Closed by bojidar-bg** 2017-09-13 05:33 UTC
