### ISSUE TITLE
AnimatedSprite animation_finished() signal triggers both in game and in the editor, returns an error in editor

### ISSUE THREAD

**Issue by coppolaemilio** [godotengine/godot#19826] opened 2018-06-28 15:24 UTC
**Godot version:**
v.3.0.4.stable.official.d916135

**OS/device including version:**
Windows 10

**Issue description:**
When you create an animated sprite and try to do something with the animation_finished signal you get an error:
```
core/object.cpp:1202 - Error calling method from signal 'animation_finished': 'Node(Node.gd)::_on_AnimatedSprite_animation_finished': Method not found.
```
This makes the function to sometimes not work. It is working on the example but the error message is still present.

**Minimal example project:**

[Example Project.zip](https://github.com/godotengine/godot/files/2145875/Example.Project.zip)

**Comment by Alexander-Alekseev** [comment] 2018-07-03 07:49
> This makes the function to sometimes not work. It is working on the example but the error message is still present.

It works in a game, correct. But if you see something like -

>  core\object.cpp:1202 - Error calling method from signal 'animation_finished': 'Node(Node.gd)::_on_AnimatedSprite_animation_finished': Method not found.
Hello World!
 core\object.cpp:1202 - Error calling method from signal 'animation_finished': 'Node(Node.gd)::_on_AnimatedSprite_animation_finished': Method not found.
Hello World!
 core\object.cpp:1202 - Error calling method from signal 'animation_finished': 'Node(Node.gd)::_on_AnimatedSprite_animation_finished': Method not found.
Hello World!

it means that _editor_ spams errors, but _game_ prints "Hello World!". So it doesn't mean that function "works sometimes".

If you are not in a game, editor continuously spams -

>  core\object.cpp:1202 - Error calling method from signal 'animation_finished': 'Node(Node.gd)::_on_AnimatedSprite_animation_finished': Method not found.
 core\object.cpp:1202 - Error calling method from signal 'animation_finished': 'Node(Node.gd)::_on_AnimatedSprite_animation_finished': Method not found.
 core\object.cpp:1202 - Error calling method from signal 'animation_finished': 'Node(Node.gd)::_on_AnimatedSprite_animation_finished': Method not found.
 core\object.cpp:1202 - Error calling method from signal 'animation_finished': 'Node(Node.gd)::_on_AnimatedSprite_animation_finished': Method not found.

For someone who wants to continue investigation:
https://github.com/godotengine/godot/blob/7fc2367508c41cfab86eaf7d84e04cd122978fdb/core/object.cpp#L893
`script_instance` object is an instance of `PlaceHolderScriptInstance` class in _editor_, but it is an instance of `GDScriptInstance` class in a _game_.

**Comment by coppolaemilio** [comment] 2018-07-03 12:34
I discovered this when I was working on my jam entry and could not do anything animation related with that signal so I had to make a timer to trigger and change the animations, it was pretty terrible.

**Comment by akien-mga** [comment] 2018-07-03 13:19
Just checked and it's reproducible in 3.0.2 and 3.0, so not a recent regression.

**Comment by akien-mga** [comment] 2018-07-03 13:30
It's a duplicate of #13070, apart from the "sometimes doesn't trigger" part. I can't reproduce this, could you be more specific?

**Comment by coppolaemilio** [comment] 2018-07-03 14:42
I created this example with the first time I encountered the issue. I have the `AnimatedSprite` node trying to have a `default` animation that doesn't loops and when it ends it goes to the `stay` animation. It just doesn't work as expected at all, the animation doesn't play or anything.
[Uploading minimal-animation.zip…]()

**Comment by akien-mga** [comment] 2018-07-03 15:11
> I created this example with the first time I encountered the issue. I have the AnimatedSprite node trying to have a default animation that doesn't loops and when it ends it goes to the stay animation. It just doesn't work as expected at all, the animation doesn't play or anything.
minimal-animation.zip

Well the signal works fine in game, the issue is that since the animation autoplays in the editor when you set the frame to 0, the default animation will bring it directly to 17 and end the animation (and *there*, in the editor, the signal doesn't work). Then if you run the game, the default animation is ended already so there's no signal to trigger.

If you disable autoplay, set frame to 0, and add `func _ready(): $AnimatedSprite.play('default')`, it works fine in game.

**Comment by coppolaemilio** [comment] 2018-07-03 15:17
Then it was my mistake. I still find weird that the editor will modify how the things will behave in-game but I should get used to it. Thanks for your help.

**Comment by akien-mga** [comment] 2018-07-03 15:56
Closing as duplicate of #13070, I'll add the example project there though as it's useful for debugging.

**Closed by akien-mga** 2018-07-03 15:56 UTC
Labels: bug, confirmed, topic:core
