### ISSUE TITLE
"Use Debanding" option on iOS causes rendering issue

### ISSUE THREAD

**Issue by victorbstan** [godotengine/godot#56443] opened 2022-01-02 18:22 UTC
### Godot version

v3.4.2.stable.official [45eaa2daf]

### System information

MacBook Air M1

### Issue description

When turning on "Genera > Render > Quality > Use Debanding" option to ON, and exporting game to iOS (iPhone 12 Pro Max) the screen is covered in black mostly, with only a small bottom left corner properly rendered.  It is expected that the entire screen should be rendered and no black area should cover it.

Problem screenshot:
![Screenshot 2022-01-02 at 1 15 52 PM](https://user-images.githubusercontent.com/315297/147885514-70706b2f-49fa-4495-9178-382e883a9214.png)

Option to test with:
<img width="899" alt="Screen Shot 2022-01-02 at 1 14 42 PM" src="https://user-images.githubusercontent.com/315297/147885526-dc5d508d-2e4b-494e-bb2b-dc07f60afd09.png">

### Steps to reproduce

Turn on "Use Debanding" option, export to iOS device. See rendering problem.

**Comment by Calinou** [comment] 2022-01-02 18:28
Duplicate of https://github.com/godotengine/godot/issues/45366.

**Closed by Calinou** 2022-01-02 18:28 UTC
