### ISSUE TITLE
Only 8 SpotLights or OmniLights can be displayed on a given object

### ISSUE THREAD

**Issue by Eagle-Faulkner** [godotengine/godot#15651] opened 2018-01-13 05:28 UTC
**Godot version:**
3 Beta 2

**OS/device including version:**
Windows 10 64-bit with NVIDIA GEFORCE 940M

**Issue description:**
I have 9 SpotLights all aimed at a MeshInstance, but both in-editor and in-game only 8 of them produce light

**Steps to reproduce:**
create a scene with a mesh instance large enough for several spotlights to hit it, and create 9 spotlights that all shine on their own spots on the meshinstance

**Comment by Noshyaar** [comment] 2018-01-13 06:36
Confirmed on Antergos x86_64 | OpenGL ES 3.0 Renderer: Mesa DRI Intel(R) Haswell

![image](https://user-images.githubusercontent.com/26753932/34903558-823ff94c-f866-11e7-88ca-142a78dad93a.png)

[Spatial.tscn](https://github.com/godotengine/godot/files/1628125/Spatial.txt)

**Comment by akien-mga** [comment] 2018-01-13 19:46
> \<reduz\> known limitation, will be lifted in 3.1 with clustering

**Comment by reduz** [comment] 2018-01-13 20:31
Limitation is per object, though.. you can have as many as you want if
different objects are affected..

On Jan 13, 2018 4:46 PM, "Rémi Verschelde" <notifications@github.com> wrote:

<reduz> known limitation, will be lifted in 3.1 with clustering

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/godotengine/godot/issues/15651#issuecomment-357460911>,
or mute the thread

**Comment by reduz** [comment] 2018-09-06 16:59
Kicking to 3.2, won't be solved in 3.1

**Comment by Calinou** [comment] 2020-03-12 09:12
This limitation should now be lifted as of commit ee1e89f, closing.

**Closed by Calinou** 2020-03-12 09:12 UTC
Labels: bug, confirmed, topic:rendering

**Comment by akien-mga** [comment] 2020-11-17 15:22
Note that this limitation was also lifted in the `3.2` branch (for Godot 3.2.4) with #43606.
The default number of lights per object is now 32, and you can configure it further.
