### ISSUE TITLE
Vulkan: SDFGI does not take GridMap into account for baking

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot#56031] opened 2021-12-17 18:09 UTC
*Related to https://github.com/godotengine/godot/issues/56030, which is about LightmapGI not working with GridMaps.*

### Godot version

 4.0.dev (1cbf3947d)

### System information

Fedora 34, GeForce GTX 1080 (NVIDIA 470.74)

### Issue description

SDFGI does not take GridMaps into account for baking. On the left, you can clearly notice the indirect lighting, but it's completely missing on the right:

![2021-12-17_18 33 24](https://user-images.githubusercontent.com/180032/146588173-032e0811-c57b-45ba-b9bf-36c165f52d8b.png)

SDFGI Cascades debug draw mode:

![2021-12-17_18 33 47](https://user-images.githubusercontent.com/180032/146588168-6782d45c-d06f-4af6-9bbe-6cd7db8a1693.png)

In comparison, VoxelGI works:

![2021-12-17_18 32 33](https://user-images.githubusercontent.com/180032/146587924-83ea7540-f17f-4d4f-a628-d8a39c71c3ee.png)

VoxelGI lighting debug draw mode:

![2021-12-17_18 34 02](https://user-images.githubusercontent.com/180032/146587939-a0edf7e9-8450-4484-abed-305a2a46cfad.png)

### Steps to reproduce

- Add a MeshInstance node with a BoxMesh to act as a floor. Resize it so it can fit several objects on top. Set the global illumination mode to **Baked** in the inspector.
- Add a GridMap node. Use the GridMap menu at the top of the 3D editor to create a new item. Load in the mesh resource in the inspector. Place a few GridMap tiles at varying heights (<kbd>Shift</kbd> + Mouse wheel).
- Add a WorldEnvironment node, select it, edit its Environment resource and enable **Sdfgi**.

### Minimal reproduction project

[test_sdfgi_gridmap.zip](https://github.com/godotengine/godot/files/7736935/test_sdfgi_gridmap.zip)

**Comment by mieldepoche** [comment] 2021-12-17 23:44
I think this is a duplicate of #40617, which is referenced in the tracker already (1st "bugs" entry).

**Closed** 2021-12-18 01:38 UTC
Labels: bug, archived, topic:rendering, topic:3d
