### ISSUE TITLE
Memory leak in C# using GetViewport().GetTexture().GetData();

### ISSUE THREAD

**Issue by Ythundyth** [godotengine/godot#36649] opened 2020-02-28 17:22 UTC
**Godot version:** 3.2 Mono version

**OS/device including version:** Ubuntu 18.04

**Issue description:** The problem is the GetViewport().GetTexture().GetData(); part, it causes a memory leak, eventually crashing the game. This does not happen in GDScript.

**Steps to reproduce:** 
using Godot;
using System;

public class Node2D : Godot.Node2D
{
    public override void _Process(float delta)
    {
        var image = GetViewport().GetTexture().GetData();
    }
}

**Minimal reproduction project:**
Just copy the steps to reproduce into a C# script and attach it to a node.

**Comment by Tobi-Mob** [comment] 2021-09-13 10:13
I thought the GC would handle this, but strangle he does not completely.
This example fills my ram until something crashes.

But, if I modify the code to stop after 1000 iterations and force a GC, everything is freed:
![grafik](https://user-images.githubusercontent.com/69400800/133065065-314d06e9-1732-4109-b251-3cfb2a3a4b6a.png)

![grafik](https://user-images.githubusercontent.com/69400800/133064317-d2e4f24f-382f-4788-80bf-035c80e49401.png)

If the code stops after 1000 iterations but no GC is enforced, the ram stays high, which puzzles me a lot.
(Since +50% RAM usage should be enough to trigger a collection)

![grafik](https://user-images.githubusercontent.com/69400800/133066180-75348b31-fda5-4d7f-9677-0e9d85c29b34.png)

![grafik](https://user-images.githubusercontent.com/69400800/133066093-abd90c62-0471-4411-abd2-d3ab5cb8a735.png)

Maybe someone has a idea, what the reason for this could be.

**Comment by Tobi-Mob** [comment] 2021-09-13 19:49
manually requesting a GC from time to time causes everything to collect as expected.

```
    private static async Task Worker()
    {
        while (true)
        {
            GC.Collect(1, GCCollectionMode.Optimized, false);
            await Task.Delay(5000);
        }
    }
```

![grafik](https://user-images.githubusercontent.com/69400800/133146292-089f802e-5198-4034-a010-d695115ecbe7.png)

If the GC is NOT called manually, `GC.CollectionCount()` always returns "0", which means that the GC is not run for any generation. 

I am still not sure why the GC does not trigger on its own, even if the RAM is filling up.

**Comment by Tobi-Mob** [comment] 2021-09-14 08:12
This could be the reason:
https://docs.microsoft.com/en-us/dotnet/api/system.gc.addmemorypressure?view=net-5.0#remarks

>In determining when to schedule garbage collection, the runtime takes into account how much **managed memory** is allocated. **If a small managed object allocates a large amount of unmanaged memory, the runtime takes into account only the managed memory**, and thus underestimates the urgency of scheduling garbage collection.

The solution would be to use GC.AddMemoryPressure and GC.RemoveMemoryPressure.
BUT...:

https://github.com/mono/mono/blob/bdd772531d379b4e78593587d15113c37edd4a64/mono/metadata/boehm-gc.c#L315-L318

    void mono_gc_add_memory_pressure (gint64 value)
    {
    }

https://github.com/mono/mono/blob/78c2b8da29881eccda4c27ca7b2b7e9ed451c55f/mono/metadata/sgen-mono.c#L2918-L2922

    void mono_gc_add_memory_pressure (gint64 value)
    {
    }

https://www.mono-project.com/docs/advanced/pinvoke/#properly-disposing-of-resources
https://github.com/mono/website/issues/94#issue-54683360

>At the the time of this writing (January 2015), this approach will not work on Mono, as System.GC.AddMemoryPressure(long) and System.GC.RemoveMemoryPressure(long) **are implemented as no-ops**

So, it sound like this will not work with mono.

The options I see:

1) manually call dispose
2) manually trigger the GC (see example above)
3) Just work normally. If the project is running normally and some garbage is generated the GC will run on its own. It will just not trigger from Godot-Objects alone

**Comment by Tobi-Mob** [comment] 2021-09-14 08:21
Or wait for .net core in Godot and 

add GC.AddMemoryPressure here https://github.com/godotengine/godot/blob/18c0f0b3ba46caf3f6dda401362bc5993eaf7f8d/modules/mono/glue/GodotSharp/GodotSharp/Core/Object.base.cs#L18-L23

add GC.RemoveMemoryPressure here:
https://github.com/godotengine/godot/blob/18c0f0b3ba46caf3f6dda401362bc5993eaf7f8d/modules/mono/glue/GodotSharp/GodotSharp/Core/Object.base.cs#L71-L76

**Comment by Calinou** [comment] 2022-09-06 02:20
Can anyone check if this issue still occurs in 4.0.alpha with .NET 6?

**Comment by eswartz** [comment] 2024-06-07 17:25
> Can anyone check if this issue still occurs in 4.0.alpha with .NET 6?

Yes. It still happens, even post Godot 4.3beta 1.

from https://github.com/godotengine/godot/issues/36649#issuecomment-918522245:
> GC.Collect(1, GCCollectionMode.Optimized, false);

This workaround doesn't work for this case. I needed to use `GC.Collect()` directly to reclaim the memory as described. (I didn't try much more -- just ran into a similar issue and found this report.)

This repro has the original user's case plus the task to clean up memory, with the `GC.Collect()` call used instead:

[memleak36649.zip](https://github.com/user-attachments/files/15743021/memleak36649.zip)

**Comment by raulsntos** [comment] 2024-06-07 17:52
If `GC.Collect()` solves your issue, then it's not a memory leak. The GC doesn't release allocated memory immediately, it triggers when the allocated memory surpasses a threshold.

The original author also mentions crashing, does your game crash if you don't manually trigger a collection?

**Comment by eswartz** [comment] 2024-06-07 21:11
Thanks for taking a look. I didn't mean to waste anyone's time (I see there is probably a lot of noise around this subject). 

I was posting specifically to answer Calinou's question about reproducibility of **this issue** alone -- and to note that the "gentle" GC.Collect(...) call suggested originally doesn't do the trick either anymore. 

> The original author also mentions crashing, does your game crash if you don't manually trigger a collection?

I did indeed run into issues like this in my own project but worked around them. The MRP I posted is  the code in this ticket's summary and comments, not my own project.

The "crashing" is that the OS kills the process because it consumes all available memory and swap. ("Un"fortunately my system has enough RAM and swap space to make this take a very long time. I ran the MRP without GC.Collect, and it got up 89 GiB before that happened.)

> If `GC.Collect()` solves your issue, then it's not a memory leak.

I agree and understand. I didn't intend to continue misnaming the issue (that's what the OP called it and I incorrectly named my attachment with the same term).

>  The GC doesn't release allocated memory immediately, it triggers when the allocated memory surpasses a threshold. See [#82112 (comment)](https://github.com/godotengine/godot/issues/82112#issuecomment-1731342696).

I read #82112 and the dotnet linked reference, did some more digging and think I see why this particular case might be happening.

After adding this to `_Process`:
```
 Console.WriteLine($"Dotnet thinks {GC.GetTotalMemory(false)} is in use, Godot sees {Performance.Singleton.GetMonitor(Performance.Monitor.MemoryStatic)}");
```
It consistently reports that dotnet governs much less memory than the Godot process:

```
Dotnet thinks 917776 is in use, Godot sees 1272379537
....
Dotnet thinks 1524080 is in use, Godot sees 4435111037
```

So it would appear that for the case in this ticket, dotnet wouldn't trigger GC because its own heap doesn't contain the large image data buffer, which is owned in unmanaged memory on the Godot side. 

Since dotnet doesn't see any problem on its side, no GC is performed in time (or ever, apparently) to release the small amount of C# objects that in turn own the much larger unmanaged memory.

Adding `GC.AddMemoryPressure` around the call seems to do the trick, though:
```
public override void _Process(double delta)
	{
        Console.WriteLine($"Dotnet thinks {GC.GetTotalMemory(false)} is in use, Godot sees {Performance.Singleton.GetMonitor(Performance.Monitor.MemoryStatic)}");

        GC.AddMemoryPressure(1280 * 1024 * 4);
	var image = GetViewport().GetTexture().GetImage();

        GC.RemoveMemoryPressure(1280 * 1024 * 4);
	}
```
That alone seems to trigger GC as expected:

```
Dotnet thinks 424000 is in use, Godot sees 68388533
Dotnet thinks 424000 is in use, Godot sees 68388533
Dotnet thinks 424000 is in use, Godot sees 68388533
....
```

And of course `image.Dispose()` does the trick directly without any of this. Again, I was just following the original OP's usage scenario.

Would it make sense for Godot to trigger GC.AddMemoryPressure/RemoveMemoryPressure calls around the lifetime of any C# object that is indirectly referencing a potentially large buffer? That might trigger dotnet GC to actually occur once in a while ;)

**Comment by raulsntos** [comment] 2024-06-08 02:54
No need to apologize, I appreciate you taking the time to triage this issue. Thanks for the detailed response!

> Would it make sense for Godot to trigger GC.AddMemoryPressure/RemoveMemoryPressure calls around the lifetime of any C# object that is indirectly referencing a potentially large buffer?

I don't think so, according to the [`GC.AddMemoryPressure`](https://learn.microsoft.com/en-us/dotnet/api/system.gc.addmemorypressure) documentation. These methods should only be used for types that depend exclusively on the finalizer to release unmanaged resources, but in our case we follow the dispose pattern so finalizers are only used to clean up as a fallback. And since the native memory is handled by Godot (not our C# bindings), it's possible that the native memory is released and we could end up with incorrect accounting of GC pressure which would result in degraded performance.

The recommendation here would be to call [`Dispose()`](https://learn.microsoft.com/en-us/dotnet/api/system.idisposable.dispose) or use an [`using` statement](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/statements/using). And from your response it seems this is working as intended, so I'll be closing this issue. Thanks.

**Closed by raulsntos** 2024-06-08 02:54 UTC
Labels: bug, topic:dotnet
