### ISSUE TITLE
TextureRect gets blank sometimes (when editing)

### ISSUE THREAD

**Issue by hydroper** [godotengine/godot#71555] opened 2023-01-17 12:58 UTC
### Godot version

4.0dev beta12

### System information

Windows 11
Renderer: `gl_compatibility`

### Issue description

Any texture I add, whether PNG, SVG or something else, gets blank (white or sometimes invisible) while in the editor. It shows right at first; then when I browse the Inspector, the texture gets blank or invisible. It does keep working though when I launch the project. When I restart the Godot Engine editor, it returns to normal.

I don't see anything at _Output_; it only shows a warning of unused parameter (unused code).

https://streamable.com/nj4g4i

### Steps to reproduce

- 1. Create a 2D scene.
- 2. Add a `TextureRect` and load a PNG or SVG
- 3. Browse the Inspector

### Minimal reproduction project

N/A

**Comment by hydroper** [comment] 2023-01-26 19:46
Have you tracked this bug? I updated the post with a demo video.

**Comment by KoBeWi** [comment] 2023-01-29 16:34
Can't reproduce in beta 16 on Windows 10
What is your graphic card?

**Comment by hydroper** [comment] 2023-01-29 16:39
@KoBeWi I've tried the `forward_plus` renderer instead of `gl_compatibility` and it works! So the bug is within `gl_compatibility`.

My graphics card: Intel UHD Graphics 610

**Comment by hydroper** [comment] 2023-01-29 16:39
So there is already beta 16? I'm gonna have to download it then...

**Comment by hydroper** [comment] 2023-01-29 16:43
I tried beta 16 with `gl_compatibility` renderer and I still get the same issue.

**Comment by clayjohn** [comment] 2023-01-30 22:57
Seems like a duplicate of https://github.com/godotengine/godot/issues/71951

**Closed** 2023-01-30 22:59 UTC
Labels: bug, topic:rendering, needs testing, topic:gui
