### ISSUE TITLE
Hiding Script Tab prevents External Editor from working

### ISSUE THREAD

**Issue by JohnnyUrosevic** [godotengine/godot#66085] opened 2022-09-19 02:41 UTC
### Godot version

4.0.beta1

### System information

Windows 10

### Issue description

I am using Visual Studio Code as an external editor. This worked as expected. However, when I changed the project settings to hide the internal script tab, double clicking scripts or creating new scripts no longer opens the external editor.

### Steps to reproduce

- Create a new project
- Set the editor to open an external editor
![image](https://user-images.githubusercontent.com/6700341/190941791-40cf40ff-1ffd-43d8-b0ba-0f312af4c44e.png)
- Create a new "Manage editor features" profile
- Disable the script feature
![image](https://user-images.githubusercontent.com/6700341/190941892-f1d942f5-30af-4765-8445-fe795b5f18c7.png)
- Double click a script file

### Minimal reproduction project
[external-editor-bug.zip](https://github.com/godotengine/godot/files/9595909/external-editor-bug.zip)

**Comment by Paulb23** [comment] 2022-09-19 10:32
Duplicate of #59758

**Closed by Paulb23** 2022-09-19 10:32 UTC
