### ISSUE TITLE
Cutting folded region restricts scrolling after cut and after undo

### ISSUE THREAD

**Issue by Cigam-HFden** [godotengine/godot#97595] opened 2024-09-28 19:00 UTC
### Tested versions

v4.4.dev2.official [97ef3c837]

### System information

Godot v4.4.dev2 - Windows 10.0.19045 - OpenGL 3 (Compatibility) - NVIDIA GeForce RTX 3070 (NVIDIA; 32.0.15.6109) - 11th Gen Intel(R) Core(TM) i9-11900K @ 3.50GHz (16 Threads)

### Issue description

Cutting a folded region restricts the scrolling, making the bottom of the code unreachable. Undoing the cut still restricts the scroll.

### Steps to reproduce

Have code in a region, and code below it.
Collapse the region and cut, then check scroll
Undo cut and check scroll

### Minimal reproduction project (MRP)

MRP:
[mrp_restricted_region_scroll.zip](https://github.com/user-attachments/files/17175902/mrp_restricted_region_scroll.zip)

Video:
https://github.com/user-attachments/assets/bfc4394d-0714-49c4-88b7-0cf6f8d2508a

**Comment by kitbdev** [comment] 2024-09-29 00:14
- possibly caused by the cache changes in https://github.com/godotengine/godot/pull/92865

**Comment by arkology** [comment] 2024-09-29 08:09
I can reproduce it an also want to add that this happens not only with region folding but with any lines folding (like folded comments and functions).

**Comment by kitbdev** [comment] 2024-11-12 18:39
- fixed by https://github.com/godotengine/godot/pull/98678

**Closed** 2024-11-13 11:55 UTC
Labels: bug, topic:editor, usability
