### ISSUE TITLE
Specular light gets disabled at zero roughness

### ISSUE THREAD

**Issue by ghost** [godotengine/godot#12404] opened 2017-10-25 16:27 UTC
(Opening an issue for this such that we don't forget about this.)

Setting a value of 0 for roughness currently disables *all variants* of the specular light (GGX G function and some other specular modes lead to 0/0 or 0^0).

Taking proper limit, we do get 0 for GGX but that should be checked for other specular models (after including the normalization factor [most likely depends on roughness] which also needs to be done).

Another way to look at this is: we should ensure that all other non-PBR specular models converge to 0 as roughness approaches to 0.

**Comment by reduz** [comment] 2017-12-06 14:28
as far as I understand, this is expected and not a bug. closing.

**Closed by reduz** 2017-12-06 14:28 UTC
Labels: enhancement, topic:rendering
