### ISSUE TITLE
Tilemap editor width is too big on 1366x768 with 100% scaling, Inspector gets cropped

### ISSUE THREAD

**Issue by FreegleBarr** [godotengine/godot#57483] opened 2022-01-31 14:54 UTC
### Godot version

4.0.alpha1

### System information

Ubuntu 20.04

### Issue description

The new tilemap editor stretches a bit to the sides in my setup with 100% scale and 1366x768 resolution, which causes the inspector dock to be slightly off-screen. 

![image](https://user-images.githubusercontent.com/97912854/151814595-83fb39b3-a746-45a1-8613-13b2c22a695a.png)

### Steps to reproduce

* Change your resolution to 1366x768 if not default.
* Open the TileMap editor plugin.

**Comment by akien-mga** [comment] 2022-01-31 15:25
That's technically a duplicate of #31133, but like often this can be worked around by reducing the minimum width of the dock.
Here for example the following elements all take way too much width:

- "Place Random Tile" checkbox (would be even worse for some translations)
- "Scattering:" + its spinbox
- Layer #0 drop down

**Comment by groud** [comment] 2022-01-31 15:40
@akien-mga or, if it works, we may replace the HBoxContainer of the toolbar by the brand new FlowContainter. That could help on small screens.

**Closed** 2022-05-01 20:53 UTC
Labels: bug, topic:editor, usability
