### ISSUE TITLE
inconsistent behavior when set  the layer of CanvasLayer to 0 

### ISSUE THREAD

**Issue by alexzheng** [godotengine/godot#23133] opened 2018-10-19 09:32 UTC
**Godot version: 3.0.6

**OS/device including version:**

**Issue description:**

I set the layer property of CanvasLayer to 0 by mistake, it can work on desktop, but on iOS and Android the canvas layer is not visible but the buttons in the layer can still accept events.

**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by KoBeWi** [comment] 2020-06-27 23:32
Can anyone still reproduce this bug in [Godot 3.2.2](https://godotengine.org/article/maintenance-release-godot-3-2-2) or any later release?

If yes, please ensure that an up-to-date Minimal Reproduction Project (MRP) is included in this report (a MRP is a zipped Godot project with the minimal elements necessary to reliably trigger the bug). You can upload ZIP files in an issue comment with a drag and drop.

**Comment by KoBeWi** [comment] 2020-09-28 19:45
Closing due to lack of update. Please comment if you can still reproduce this issue in the latest stable version of Godot.

**Closed by KoBeWi** 2020-09-28 19:45 UTC
Labels: bug, platform:android, platform:ios, topic:porting
