### ISSUE TITLE
Emulated InputEventMouseMotion has device id >= 0

### ISSUE THREAD

**Issue by maiself** [godotengine/godot#71650] opened 2023-01-18 23:05 UTC
### Godot version

d93b66ad4d6b1dae42cc318c16224d03bd1a1472

### System information

arch linux, asus zenbook duo ux481 (dual touchscreen laptop)
goggle pixel 6

### Issue description

Emulated `InputEventMouseButton` events (generated while `emulate_mouse_from_touch = true`) can be ignored by code that handles touch and mouse differently by detecting `event.device == -1`.

Currently broken in master is `InputEventMouseMotion`, which has `device == 0` for all events, including emulated.

### Steps to reproduce

Ensure `emulate_mouse_from_touch = true` in project settings.
Observe event stream for event type and `event.device` on a touch capable device.

```gdscript
func _input(event):
	prints(event.device, event)
```

### Minimal reproduction project

none

**Comment by akien-mga** [comment] 2023-01-19 08:18
That's interesting because the code shows that both `MouseButton` and `MouseMotion` events emulated from touch/drag should be created with `DEVICE_ID_TOUCH_MOUSE`:

https://github.com/godotengine/godot/blob/d93b66ad4d6b1dae42cc318c16224d03bd1a1472/core/input/input.cpp#L552-L625

I suggest starting debugging there if you're interested.

**Comment by Sauermann** [comment] 2023-01-19 09:26
I have tested this on Windows 10 (Touchscreen-Laptop) with the reproduction steps from above and the emulated `InputEventMouseMotion` and `InputEventMouseButton` have device ID `-1`.

**Comment by maiself** [comment] 2023-01-19 09:49
I found this function seems to create a fake event without setting the device:

https://github.com/godotengine/godot/blob/d93b66ad4d6b1dae42cc318c16224d03bd1a1472/core/input/input.cpp#L847

I also wonder if this could be platform related.

For me the relevant bits could be: Arch Linux, Wayland, XWayland, Gnome Shell.

I don't have another system to test on, I'll see if tomorrow I can create a minimal project that demonstrates the issue, and dig deeper into `input.cpp` for any clues.

**Comment by Sauermann** [comment] 2023-01-19 09:55
I have an open PR #69318 to set the device ID in the `set_default_cursor_shape` function. But I am not convinced, that this is the problem, you are facing.

**Comment by maiself** [comment] 2023-01-20 06:53
Working on narrowing this down...

I've discovered that this is only happening when `Input.mouse_mode` is not `Input.MOUSE_MODE_VISIBLE`.

Also that both emulated `InputEventMouseMotion` and `InputEventMouseButton` occasionally report `device` as `0`.

`set_default_cursor_shape` is also a problem when the cursor shape changes, it does look like #69318 fixes that part of this issue.

**Comment by Sauermann** [comment] 2023-02-08 21:51
@maiself wanted to let you know, that several locations, that didn't set device id's previously now use `DEVICE_ID_INTERNAL` or `DEVICE_ID_EMULATED`. See #72740. Can you please recheck, if you still experience the described issue?

**Comment by Calinou** [comment] 2024-08-08 00:31
Closing per Sauermann's above comment. Please comment if you can still reproduce this on the latest Godot version.

**Closed by Calinou** 2024-08-08 00:31 UTC
Labels: bug, topic:input
