### ISSUE TITLE
Signals connected from code are not received/emitted in exported projects without the "Export with Debug" check

### ISSUE THREAD

**Issue by IvanIG3** [godotengine/godot#56243] opened 2021-12-25 19:43 UTC
### Godot version

3.4.2.stable

### System information

Windows 10

### Issue description

Connecting a signal manually from code won't be received in projects exported without the check "Export with Debug". It works as intented with the check activated, or debugging with the Editor. Signal connected from the Editor works fine too.

### Steps to reproduce

In the attached project, TestNode emits the signal "signal_test". There are 2 TestNode as children of Main scene. One of them is connected manually to the Main scene, the other is connected from the Editor menu. The steps are:

1. Execute the project and press Enter. 2 messages are displayed from the 2 TestNode.
2. Project -> Export... -> Export Project -> Set "Export with Debug" to false -> Save.
3. Execute the exported project and press Enter. Only 1 message is displayed, from the TestNode connected from the Editor.

### Minimal reproduction project

[GodotSignalTest.zip](https://github.com/godotengine/godot/files/7776209/GodotSignalTest.zip)

*Bugsquad edit (keywords for easier searching): release*

**Comment by kleonc** [comment] 2021-12-25 22:12
You're connecting in the `assert`:
> assert(testnode1.connect("signal_test", self, "_on_signal_test") == OK)

so it's not being executed in the release build. From [`assert` docs](https://docs.godotengine.org/en/stable/classes/class_@gdscript.html#class-gdscript-method-assert):
>Note: For performance reasons, the code inside assert is only executed in debug builds or when running the project from the editor. Don't include code that has side effects in an assert call. Otherwise, the project will behave differently when exported in release mode.

It works as intended.

**Comment by Calinou** [comment] 2021-12-25 23:09
Closing per @kleonc's comment. See also https://github.com/godotengine/godot-proposals/issues/502.

**Closed** 2021-12-26 00:57 UTC
Labels: archived, topic:core, topic:export
