### ISSUE TITLE
Godot crashes when you run a scene after selecting text in the output window

### ISSUE THREAD

**Issue by fdmcv** [godotengine/godot#51934] opened 2021-08-21 00:46 UTC
### Godot version

3.3.2 and 3.3.3 stable win64 standard version

### System information

Windows 10 

### Issue description

I print data in the output window to analyze the behavior of the player over time (position velocity, state, etc). I usually click on the window while I'm analyzing the data and I eventually select and copy data from it (not from the output console in the editor, but from the output window itself). 

In case I leave some text selected in the window, Godot crashes the next time I run a scene. Godot freezes as soon as the "saving scenes" progress bar reaches 100%. In case there is no text selected in the window, Godot doesn't crash.

The issue can be avoided by just not leaving any text selected in the output window. It's not a blocking issue, but something goes wrong. 

### Steps to reproduce

1. Open a project.
2. Go to the output window.
3. Select any text with the mouse and leave it selected.
4. Go back to the editor and Run a scene.

At least on my side I'm able to reproduce the issue always with these steps.

**Comment by Rubonnek** [comment] 2021-08-21 01:25
I'm unable to reproduce with either version. Could you provide a minimal reproduction project? Or perhaps a backtrace?

**Comment by fdmcv** [comment] 2021-08-22 21:50
The issue happens even with a brand new and empty project.

I could reproduce the issue on a second computer with an older version of Godot (3.2.3). You can see it in the attached video:
- First, I open the a project and immediately run it without any issue
- Then, I select a text from the output window, and Godot freezes when I try to run the project.

I can send you the project if you want, but it's just an empty new project. Just let me know if you need it.

Link to the video:

https://user-images.githubusercontent.com/67808941/130370861-5670f5c7-bc06-49fa-9c53-96b8dfe7f263.mp4

**Comment by Calinou** [comment] 2021-08-22 23:51
Do you use any third-party software (e.g. from Stardock) that affects desktop behavior on your PC?

**Comment by Rubonnek** [comment] 2021-08-23 00:41
@fdmcv that is normal Command Prompt/Powershell behavior on Windows. [Disabling the "Quick Edit" setting on the that window](https://stackoverflow.com/questions/60583915/avoid-pausing-tasks-when-select-something-on-powershell-and-command-prompt), which in turn  disables text selection, prevents that issue from happening.

Godot is not crashing -- it's simply paused. If you click again on the Command Prompt, the scene should run normally.

**Comment by Calinou** [comment] 2021-08-23 00:49
Closing per @Rubonnek's comment.

**Closed by Calinou** 2021-08-23 00:49 UTC
Labels: topic:editor
