### ISSUE TITLE
Can't switch monitors in fullscreen mode.

### ISSUE THREAD

**Issue by ghost** [godotengine/godot#21746] opened 2018-09-04 08:08 UTC
**Godot version:**
**3.2** f50dd68

**OS/device including version:**
Win10 64-bit / Ubuntu 18.04.1 LTS 64-bit

**Issue description:**
While in full screen mode, changing the monitor number will not switch monitors.

In Windows, I have to turn off fullscreen, switch the monitor, and turn fullscreen back on.

For Linux it seems to require at least 2 frames of delay before the window size variables have settled.  This involves turning fullscreen off, idling two frames, switch the monitor, idle for another two frames, then turn fullscreen back on.

Uknown what the behavior is for OSX.

**Steps to reproduce:**

Set the window to full screen, and attempt to switch monitors.

**Minimal reproduction project:**

 [Full Screen Montior Switching.zip](https://github.com/godotengine/godot/files/2348060/Full.Screen.Montior.Switching.zip)

The project includes the work around method I'm currently using.

**Comment by Chaosus** [comment] 2018-09-08 06:41
Im not sure - is it a duplicate of #20618 ?

**Comment by avencherus** [comment] 2018-09-08 09:44
Hard to say.  The description of actions could be better worded, but at least the first part sounds like it might be similar.

**Comment by Calinou** [comment] 2019-10-08 13:40
As per the issues linked above, this bug is what causes the editor to not respect the Game Window Placement monitor setting if the project is set to use fullscreen by default.

**Comment by avencherus** [comment] 2019-10-09 07:51
Updated the issue's formatting to follow the bug report template.

**Comment by KoBeWi** [comment] 2020-12-09 12:59
The MRP doesn't work on master. Also fullscreen seems to be bugged in general right now (cf62289), so it's difficult to test.

**Comment by avencherus** [comment] 2020-12-09 15:55
> The MRP doesn't work on master. Also fullscreen seems to be bugged in general right now ([cf62289](https://github.com/godotengine/godot/commit/cf62289d24ff4a71513e55940011864e929e7bf8)), so it's difficult to test.

It was a 3.2 issue, I'm not sure the state of affairs of with the displays in master at the moment.  Of the handful of opportunities where I had time to fiddle with it in the past, the editor either crashed or had other impassable bugs.

If you're investigating it, the only two lines of interest are just these:

```
OS.window_fullscreen = true
OS.current_screen = ID # Choose some other monitor while in full screen.
```

**Comment by akien-mga** [comment] 2022-07-19 08:03
Duplicate of #14620

**Closed by akien-mga** 2022-07-19 08:03 UTC
Labels: bug, topic:porting
