### ISSUE TITLE
[Linux] Trackpad Gestures Pinch and Pan broken in 2D and 3D workspace (everything just Zooms)

### ISSUE THREAD

**Issue by leogott** [godotengine/godot#73371] opened 2023-02-15 15:20 UTC
### Godot version

4.0 rc2 (and 3.5.1)

### System information

Fedora 36 on a thinkpad with Trackpad

### Issue description

Now I'm not entirely sure if this is even implemented, but the changelog for RC2 contained the line 

> Editor: Fix panning via InputEventPanGesture (notably for macOS) ([GH-72884](https://github.com/godotengine/godot/pull/72884)).

and it appears as the Trackpad is supposed to be able to pan and Tilt like in Blender. (It doesn't)

Mayhaps Related: #72414

### Steps to reproduce

Click in the 3D Workspace, put two Fingers on the Trackpad and move them sideways

|2 Finger Gesture |Expected | Actual|
|-|-|-|
| Slide horizontally | Pan|nothing |
| Slide vertically | Tilt|Zoom |
| Pinch | Zoom|nothing |
|Rotate | nothing| nothing |

And for the 2D Workspace
|2 Finger Gesture |Expected | Actual|
|-|-|-|
| Slide horizontally | Scroll left/right |Zoom  and erratically Scroll left/right|
| Slide vertically | Scroll up/down |Zoom and erratic Scroll up/down|
| Pinch | Zoom|nothing |
|Rotate | nothing| nothing |

The erratic Scrolling in the 2D workspace can't be observed in the RC1 build or a 3.5.1 build,
and seems to be more likely when several gestures are combined and done quickly.

### Minimal reproduction project

N/A

**Comment by bruvzg** [comment] 2023-02-15 17:00
> Now I'm not entirely sure if this is even implemented, but the changelog for RC2 contained the line

`InputEventPanGesture` and `InputEventMagnifyGesture` are supported only on macOS and Android.

**Comment by Proggle** [comment] 2023-03-15 18:40
On my acer windows 10 laptop, the 'pinch to zoom' and 'two buttons to scroll' are reversed in Godot - if I pinch to zoom it scrolls, if I try to scroll it zooms.

**Comment by stevenctl** [comment] 2023-05-27 20:05
Is there a tracking issue to support them on windows and/or linux?

**Comment by Calinou** [comment] 2023-05-27 20:08
- Duplicate of https://github.com/godotengine/godot/issues/13139.

The 2D editor issue is most likely due to https://github.com/godotengine/godot/issues/77212.

**Closed by Calinou** 2023-05-27 20:08 UTC
Labels: bug, topic:editor, topic:input, regression

**Comment by eobet** [comment] 2024-06-29 16:15
@Calinou  Could you please re-open this issue. It's still a problem in 4.3 beta2 and #85473 does not fix it.

I'd say this a major issue since it breaks the convention which literally every other app uses. But perhaps Linux laptop users are a very small minority and thus not prioritized...
