### ISSUE TITLE
[3.0] Axis invisible when light is too bright

### ISSUE THREAD

**Issue by Andev08** [godotengine/godot#11203] opened 2017-09-12 19:00 UTC
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Godot 3.0

**Issue description:**
If you set the brightness of a light to 16, the movement axis for an object get drowned out by the glare
http://i.imgur.com/WuD7H7T.png

The expected behavior would be that the axis are layered on top at full brightness. So the only circumstance you couldn't see them would be if the object underneath was the same color

**Steps to reproduce:**
Create an object (such as a cylinder)
Create a directional light
Set the energy to 16
Select the object
Turn the camera so you are looking at the illuminated face
The axis will disappear behind the glare.

**Comment by DualMatrix** [comment] 2018-09-19 20:42
Still relevant in master

**Comment by KoBeWi** [comment] 2020-06-13 14:16
Still happening in 84abf5a

I wonder if it's just a matter of making gizmos unshaded (if they aren't already).

**Comment by Calinou** [comment] 2020-06-13 18:12
@KoBeWi I think they're already unshaded, but since they're translucent, the overbright colors of the lit material will cause the translucent gizmos to be invisible.

I'll close this as a duplicate of #16154, since it's almost the same issue.

**Closed by Calinou** 2020-06-13 18:12 UTC
Labels: bug, confirmed, topic:rendering, usability
