### ISSUE TITLE
No collision detection with static body

### ISSUE THREAD

**Issue by grusad** [godotengine/godot#28332] opened 2019-04-23 14:24 UTC
**Godot version:**

3.1 stable
**OS/device including version:**

windows/macOS

**Issue description:**

No collision detection on an Area from a static body containing a collisionshape created on the mesh using the Mesh -> Create Trimesh COllision Sibling. See structure in the picture. 
![Skärmklipp](https://user-images.githubusercontent.com/23147905/56588605-fbeb6380-65e3-11e9-88af-8b1323b9f512.PNG)

Collision with other bodies works fine, but not with an Area for some reason. Do i create a collision on the static body with Mesh ->Create Convex Collision Sibling, everything works just fine.

**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by bojidar-bg** [comment] 2019-04-23 17:21
Duplicate of #27970.

**Closed by bojidar-bg** 2019-04-23 17:21 UTC
Labels: bug, topic:physics
