### ISSUE TITLE
[Bullet] KinematicBody3D with move_and_slide() does unreliable is_on_floor() detection when nearly on platform's edge

### ISSUE THREAD

**Issue by kreaninw** [godotengine/godot#45219] opened 2021-01-15 20:16 UTC
**Godot version:**

- Godot 3.2.4 beta 5

**OS/device including version:**

- Windows 10 Home 64-bit, Version 20H2, OS build 19042.746
- Intel® UHD Graphics 620, Version 27.20.100.9126

**Issue description:**

Since GodotPhysics has an issue #45060 that causes the KinematicBody3D to move bumpy/jittering on a flat surface, as a solution, I put the _is_on_floor()_ condition to only apply the gravity when the body is not on the floor. 

However, when the body is nearly on the edge of the platform, the _is_on_floor()_ **flickeringly returns true and false** even though the body is always on the floor, as shown in the screen recording below (from 0:17 onward):

https://user-images.githubusercontent.com/1403194/104773983-a6120400-5754-11eb-8978-8388fa90679a.mp4

**Steps to reproduce:**

1. Open the reproduction project.
2. Run the scene.
3. See the print results in the output window.

**Minimal reproduction project:**

[test.zip](https://github.com/godotengine/godot/files/5822723/test.zip)

**Comment by kreaninw** [comment] 2021-01-16 03:12
For anyone who's still finding a way to work around this bug, you can use the **RayCast** node instead. My working setup as shown below:

![Screenshot 2021-01-16 000359](https://user-images.githubusercontent.com/1403194/104795742-70d6d780-578f-11eb-8157-6a9bbabaa177.jpg)

**Comment by pouleyKetchoupp** [comment] 2021-01-20 17:13
Confirmed in 3.2.4 beta 6.
Godot Physics: `is_on_floor` becomes inconsistent near the end of the platform.
Bullet: `is_on_floor` is inconsistent all along and the body jitters.

**Comment by Sv1nnet** [comment] 2021-02-06 15:24
Btw I noticed that C# script handles InOnFloor more correctly than GDScript.
Here are 2 project in C# and GDScript that demonstrate the different result of the same movement logic.

**Godot version:**
- v3.2.4.beta6.mono.official

1) Just move any player along the whole ground - in C# IsOnFloor detects the floor correctly, but GDScript doesn't;
2) But then move a player between blocks;
3) Let him just stand there;
4) Have the second player standing on another one and you see that IsOnFloor doesn't work correctly in both C# and GDScript;

C# - [IsOnFloor_bug_cs.zip](https://github.com/godotengine/godot/files/5937072/IsOnFloor_bug_cs.zip)
GDScript - [IsOnFloor_bug_gscript.zip](https://github.com/godotengine/godot/files/5937074/IsOnFloor_bug_gscript.zip)

**Comment by pouleyKetchoupp** [comment] 2021-06-25 02:13
In 3.3.2, I can't reproduce this issue with Godot Physics (tested with the original MRP and in 2D with the test from https://github.com/godotengine/godot/issues/45219#issuecomment-774493521).

Please confirm so this issue can be marked as Bullet-only.

**Comment by kreaninw** [comment] 2021-06-25 04:34
> In 3.3.2, I can't reproduce this issue with Godot Physics (tested with the original MRP and in 2D with the test from [#45219 (comment)](https://github.com/godotengine/godot/issues/45219#issuecomment-774493521)).
> 
> Please confirm so this issue can be marked as Bullet-only.

I also can't reproduce this issue in 3.3.2 as shown in the screen recording below:


https://user-images.githubusercontent.com/1403194/123370040-e4ee8600-d54c-11eb-86f1-65b4642059e8.mp4

**Comment by akien-mga** [comment] 2022-05-19 11:26
So it seems the GodotPhysics bug was fixed in 3.3.2 or earlier (maybe 3.3).

The Bullet specific issue is a duplicate of https://github.com/godotengine/godot/issues/45058.

**Closed by akien-mga** 2022-05-19 11:26 UTC
Labels: bug, confirmed, topic:physics
