### ISSUE TITLE
A warning is triggered by AudioStreamPlayer when using play(seek in position) in an ogg audio track

### ISSUE THREAD

**Issue by conest** [godotengine/godot#75762] opened 2023-04-06 17:41 UTC
### Godot version

4.0.2 stable

### System information

Apple M2 Pro; Vulkan API 1.2.231 - Forward+

### Issue description

This warning will be triggered when using play(certain position) from an AudioStreamPlayer loaded with ogg file.
The warning was not always occurred, only some certain seeking positions will trigger it.

```
W 0:00:11:0687   audio.gd:47 @ changeBGM(): Burning negative samples doesn't make sense. Check seek algorithm.
  <C++ Source>   modules/vorbis/audio_stream_ogg_vorbis.cpp:332 @ seek()
  <Stack Trace>  audio.gd:47 @ changeBGM()
                 audio.gd:65 @ _on_button_3_pressed()
```

### Steps to reproduce

By pressing buttons for switching audios in the same position. Some positions will trigger the warning.
Toggle the CheckButton to true, and pressing the buttons will play the audio in a fixed position, which will trigger the warning every time for certain audios.

### Minimal reproduction project

[Archive.zip](https://github.com/godotengine/godot/files/11173023/Archive.zip)

**Comment by ellenhp** [comment] 2023-04-07 02:06
I talked a bit about this here [1]. I have my hands full with other stuff so I don't anticipate working on this any time soon. If anyone wants to take a shot at it, that would be much appreciated.

[1] https://github.com/godotengine/godot/issues/64775#issuecomment-1427145947

**Comment by MJacred** [comment] 2023-08-24 16:37
This seems like a duplicate of #59348 (has same warning plus more).

**Closed** 2023-10-13 20:46 UTC
Labels: bug, topic:audio
