### ISSUE TITLE
Game crashed when c# project is runing.

### ISSUE THREAD

**Issue by 111ukasz111** [godotengine/godot#31275] opened 2019-08-10 17:08 UTC
**Godot version:**
godot 3.1.1 mono

**OS/device including version:**
windows 10

nvidia geforce 920m
**Issue description:**

when i run project with c# script engine crash

**Steps to reproduce:**
when i run project with c# script engine crash

**Minimal reproduction project:**

Thats c# project 
[Rakieta.zip](https://github.com/godotengine/godot/files/3489130/Rakieta.zip)

**Comment by KoBeWi** [comment] 2019-08-10 17:26
It shows me an error that `GD.print` is not found. It should be `GD.Print` (C# naming and stuff). It this the problem?

**Comment by neikeq** [comment] 2019-08-11 01:38
Does OP actually experience a crash or a build error?

**Comment by ZainlessBrombie** [comment] 2019-08-11 07:56
I thiiink his problem may be that the engine crashes instead of reporting the error

**Comment by 111ukasz111** [comment] 2019-08-11 09:32
I can't see error because engine crash.

**Comment by joleeee** [comment] 2019-08-11 18:48
The title would imply you cannot run any C# project. Is it the case that the game and the editor crashes when you run ex. an empty project? If nothing crashes when you run an empty project then the problem likely some function you are calling and it would be a lot easier to fix the bug if what triggers the bug is known.

**Comment by nathanwfranke** [comment] 2019-08-12 02:35
![image](https://user-images.githubusercontent.com/14253836/62843508-e461e480-bc7f-11e9-937d-0619eed81a2b.png)
Version 3.1.1 Stable Mono
Project correctly reports the error.

**Comment by 111ukasz111** [comment] 2019-08-13 18:38
But on my computer game and engine  just crash. I don't know where is the problem.

**Comment by nathanwfranke** [comment] 2019-08-13 20:16
Can you run the editor in Verbose mode, inside a command prompt, and let us know if there is a crash message?

**Comment by 111ukasz111** [comment] 2019-09-16 17:37
But how to do it in windows 10?

**Comment by akien-mga** [comment] 2020-01-19 21:18
Is this still reproducible with the latest 3.2 builds?

**Comment by exts** [comment] 2020-01-21 15:51
Cannot reproduce on 3.1.1 Stable or 3.2 RC2. @akien-mga @neikeq. I say close this for now and have them reopen it if the issue comes back.

**Closed** 2020-01-21 16:22 UTC
Labels: bug, topic:mono
