### ISSUE TITLE
Exporting a .gd script in pck changes the script to .gdc and .gd.remap

### ISSUE THREAD

**Issue by nightrobin** [godotengine/godot#42507] opened 2020-10-02 13:21 UTC
**Godot version:**
3.2.2

**OS/device including version:**
Windows 10 - 64 Bit

**Issue description:**
I'm using the 3.2.2 export template (vanilla version from godotengine.org site)
Windows Desktop Template Export - .gd script in pck changes the script to .gdc and .gd.remap

Errors:
`
E 0:00:02.747   load_byte_code: Method failed. Returning: ERR_PARSE_ERROR
  <C++ Source>  modules/gdscript/gdscript.cpp:801 @ load_byte_code()
  <Stack Trace> Router.gd:26 @ route_request()
                WebSocketManager.gd:60 @ on_data_received()
                WebSocketManager.gd:64 @ _process()

E 0:00:02.751   load: Cannot load byte code from file 'res://Client/Packs/MainPack/Scripts/MapsLocalManager.gdc'.
  <C++ Error>   Condition "err != OK" is true. Returned: RES()
  <C++ Source>  modules/gdscript/gdscript.cpp:2281 @ load()
  <Stack Trace> Router.gd:26 @ route_request()
                WebSocketManager.gd:60 @ on_data_received()
                WebSocketManager.gd:64 @ _process()

E 0:00:02.756   _load: Failed loading resource: res://Client/Packs/MainPack/Scripts/MapsLocalManager.gdc.
  <C++ Error>   Condition "found" is true. Returned: RES()
  <C++ Source>  core/io/resource_loader.cpp:278 @ _load()
  <Stack Trace> Router.gd:26 @ route_request()
                WebSocketManager.gd:60 @ on_data_received()
                WebSocketManager.gd:64 @ _process()
`

**Steps to reproduce:**
In export window, choose a .gd script and export in a pck.
Load the pck in-game,
List the files inside the folder where the loaded pck's script resides.

**Minimal reproduction project:**
N/A

**Comment by Calinou** [comment] 2020-10-02 14:01
This is because the GDScript file is meant to be compiled to bytecode, hence the `.gdc` extension.

**Comment by nightrobin** [comment] 2020-10-02 14:07
I exported a script that has code that is only usable to a separate Client App.

The script's code is not usable and is reporting missing variables in my Server App.

When I put "pass" in the script's functions it is now readable to the Client.

Closing this issue now. Have to find another way for my implementation.

Thanks Calinou

**Comment by tinmanjuggernaut** [comment] 2021-04-23 19:04
For posterity, If you're attempting to manually `load()` a .gd, you'll run into this problem when you export the game.

Upon export, all the *.gd files are replaced with *.gdc and *.gd.remap

With a game running through the editor, you can load `yourfile.gd`. However, in an exported game you cannot. If you try it complains about `yourfile.gd.remap`. You can however load `yourfile.gdc`. So you have to test to see if you have a .gd or a .gdc, and load whichever is there. 

e.g.
```
# Load and instance all .gd or .gdc files in a directory and store in an array:
for file_name in dir:
	if file_name.matchn("*.gd") or file_name.matchn("*.gdc"):
		if ResourceLoader.exists(task_dir + file_name):
			print_debug("Loading: ", task_dir + file_name)
			tasks.push_back( load(task_dir + file_name).new() )
```

**Comment by FeralBytes** [comment] 2021-04-23 22:03
I found I had to work around this bug with the following code:
```gdscript
var files = []
    var dir = Directory.new()
    dir.open("res://Logic/ProgramManager/MainScreens/")
    dir.list_dir_begin()
    while true:
        var file = dir.get_next()
        if file == "":
            break
        elif not file.begins_with("."):
            print(file)
            if file.matchn("*.gd.remap"):
                file = file.replace(".gd.remap", ".gd")
            elif file.matchn("*.gdc"):
                file = file.replace(".gdc", ".gd")
            States.append(load("res://Logic/ProgramManager/MainScreens/" + file).new())
    dir.list_dir_end()
```
@Calinou I do believe this to be a bug, since it is something that Godot causes and does not help you fix. Additionally you only find out about this issue by using ADB, the editor told me nothing.

```
04-23 13:23:31.559 16823 16837 I godot   : BluetoothStatus.gd.remap
04-23 13:23:31.559 16823 16837 E godot   : **ERROR**: No loader found for resource: res://Logic/ProgramManager/MainScreens/BluetoothStatus.gd.remap.
04-23 13:23:31.559 16823 16837 E godot   :    At: core/io/resource_loader.cpp:286:_load() - Method failed. Returning: RES()
04-23 13:23:31.559 16823 16837 E godot   : **SCRIPT ERROR**: Attempt to call function 'new' in base 'null instance' on a null instance.
04-23 13:23:31.559 16823 16837 E godot   :    At: res://Logic/ProgramManager/ProgramManager.gdc:71:load_all_states() - Attempt to call function 'new' in base 'null instance' on a null instance.
```

So can we open this back up as a bug. One that I think Godot needs to be solving so that people can simply export to Android without having to create workarounds. If you need a workaround that usually indicates it is a bug.
What are you thoughts @Calinou ?

**Comment by Calinou** [comment] 2021-04-24 00:17
This is an issue with pretty much any resource whose format gets converted during export. I don't think this can actually be fixed without lying about the file extensions present in the PCK (which is possibly dangerous), or dropping custom extensions for converted files altogether (which can be misleading).

**Comment by FeralBytes** [comment] 2021-04-24 01:04
You would know more about the feasibility of this, so I am throwing out an idea.

What about detecting load() in the gdscript compiler for android export and having it auto convert the statement to work?
Although what I do not understand is how we need to call the original name "*.gd" even though the real file name is now something else "*.gd.remap"? If you have the time to explain perhaps we can come up with a better solution.

**Comment by tinmanjuggernaut** [comment] 2021-04-24 01:19
Why can't manually loaded *.gd files automatically get translated to *.gdc? Why have different behavior in the editor vs an exported game? This behavior caused my debug exported game to not function properly, with errors, and my release exported game to segfault with an access violation without logged errors.

**Comment by boruok** [comment] 2021-05-29 06:49
got this issue when tried to load scripts when game starts, because scripts are renamed into .gd.remap and .gdc format(dunno wich are actual script)
```gdscript
data = {
	1 : {"name": "Lake Water",  "script": "terrain_lake_tile.gd", "rect": Rect2(0, 96, 48, 32),  "frames": 3, "speed": 0.2},
	5 : {"name": "Lake Poison", "script": "terrain_lake_tile.gd", "rect": Rect2(48, 96, 48, 32), "frames": 3, "speed": 0.2},
	2 : {"name": "Plato Hill",  "script": "terrain_plato_tile.gd"},
	3 : {"name": "Plato Rock",  "script": "terrain_plato_tile.gd"},
}
```

however, looks like scripts loaded when you specify loading in variable, example:
```gdscript
data = {
	1 : {"name": "Lake Water",  "script": load("terrain_lake_tile.gd"), "rect": Rect2(0, 96, 48, 32),  "frames": 3, "speed": 0.2},
	5 : {"name": "Lake Poison", "script": load("terrain_lake_tile.gd"), "rect": Rect2(48, 96, 48, 32), "frames": 3, "speed": 0.2},
	2 : {"name": "Plato Hill",  "script": load("terrain_plato_tile.gd")},
	3 : {"name": "Plato Rock",  "script": load("terrain_plato_tile.gd")},
}
```

**Comment by KoBeWi** [comment] 2022-03-17 12:59
Seems related to #25672
Loading a gd file *does* work in export if you use `load()` method, as remap's purpose is to ensure that.

**Comment by tinmanjuggernaut** [comment] 2022-03-17 13:12
@KoBeWi It is related. 

As I and others have noted, `load()` does not work on export with dynamically created file names. 

The key issue in both is that the behavior in the editor is different in exported games. Filenames are renamed, and if you hard code paths, they are renamed as well. But if you get directory listing and dynamically create filenames, you must take special care to find your files. 

Exporting raw text files is not a _good_ option. The fundamental issue remains.

**Comment by KoBeWi** [comment] 2022-03-17 13:26
Can you provide a minimal project that displays the issue? Not sure what you mean by dynamically created file names.

**Comment by tinmanjuggernaut** [comment] 2022-03-17 13:43
`load(task_dir + file_name)` as documented above. 

The fundamental issue on these tickets is that the behavior in the editor is different from an exported game, on a game breaking level. 

Yes, we have workarounds, but that is not a good solution when each individual game developer has to stumble over this issue while exporting their game for publishing, then must come across these issues, or create their own, then rewrite their resource loading scripts to accommodate for the quirk in the engine. I've gone through this twice, for resources and scripts, with different workarounds. 

The better solution is to just incorporate the alternate names in `load()`, or display loadable resources (the other ticket) automatically. Load knows the names when we call it, so the engine has the information. We're all doing it in gdscript, so there's no reason it can't be done by the engine itself.

**Comment by KoBeWi** [comment] 2022-03-17 14:25
> load(task_dir + file_name) as documented above.

Cool, except it does work.
[ScriptTest.zip](https://github.com/godotengine/godot/files/8287213/ScriptTest.zip)
Here's an actual test project, with this script:
```GDScript
extends Node

func _ready() -> void:
	var dir := Directory.new()
	dir.open("res://")
	dir.list_dir_begin(true, true)
	
	var file := dir.get_next()
	while not file.empty():
		print(file)
		file = dir.get_next()
	
	print(" === ")

func _physics_process(delta: float) -> void:
	var node = Node.new()
	node.set_script(load("res://Test" + str(randi() % 3) + ".gd"))
	add_child(node)
```
And the output is
```
ScriptTest.tscn
Test0.gd.remap
Test0.gdc
Test1.gd.remap
Test1.gdc
Test2.gd.remap
Test2.gdc
project.binary
 ===
Test2.gd
Test0.gd
Test0.gd
Test0.gd
Test1.gd
...
```
So the scripts are loaded correctly. Closing as duplicate of #25672, as it's basically the same issue.

**Closed by KoBeWi** 2022-03-17 14:25 UTC
Labels: topic:gdscript, confirmed, documentation, topic:export
