### ISSUE TITLE
Selection indicator in 3D needs improvement

### ISSUE THREAD

**Issue by n-pigeon** [godotengine/godot#4446] opened 2016-04-25 22:04 UTC
**Issue description** (what happened, and what was expected):
Current way of indicating which objects are selected is not very useful, the bounding box corners are not very noticeable (actually not visible in light scenes) and it's often hard to see if I selected mesh or lamp even.
Would suggest some sort of coloured outline around mesh objects and maybe sprite display change for lamps and stuff.
Additional benefit from outline is when working with stacked, intersecting meshes. User can then see borders of the object he manipulates and it's easier for him to see what he is doing.

**Comment by vnen** [comment] 2018-08-13 00:54
Is this still an issue in the current master?

**Comment by homer666** [comment] 2018-08-13 10:44
Yeah. It's very similar to #18465 though. If you're looking to clean up old issues, maybe it's worth closing this in favour of that one?

**Comment by Calinou** [comment] 2020-11-06 19:08
Duplicate of https://github.com/godotengine/godot/issues/18465.

**Closed by Calinou** 2020-11-06 19:08 UTC
Labels: enhancement, topic:editor, usability
