### ISSUE TITLE
Mobile VR Interface broken in 4.0

### ISSUE THREAD

**Issue by Avogine** [godotengine/godot#73561] opened 2023-02-18 17:37 UTC
### Godot version

4.0 RC2

### System information

Android 13, Adreno 730

### Issue description

The Mobile VR Interface used for Cardboard-Like mobile VR games seems to be broken in Godot 4.
The Camera updates based on rotation, but does so only to about 10 degrees (rendering the Interface unusable). On top of that, the rotation is not stable, and flickers a lot when rotating the phone.

Desired operation (here on Godot 3.x):
https://workupload.com/file/sQXUbpXePEz

Broken (Godot 4.0 RC2):
https://workupload.com/file/nTbheT83PyE
https://workupload.com/file/ZBpTvsqTtMu

### Steps to reproduce

1. Create empty project, enable XR Shader compilation in Project Settings.
2. Add XROrigin3D and XRCamera Nodes to an empty Node3D.
3. Add script initializing XR based on [https://docs.godotengine.org/en/latest/classes/class_mobilevrinterface.html](url) (little bit outdated, some variable names are changed).
4. (Add Default Environment to see changes in orientation.)
5. (Enable ATSC Compression for Android.)
6. Export to android and run.

### Minimal reproduction project

Project ZIP: 
[MVR_Test.zip](https://github.com/godotengine/godot/files/10774830/MVR_Test.zip)

APK File: 
[MVR_Test_APK.zip](https://github.com/godotengine/godot/files/10774828/MVR_Test_APK.zip)

**Comment by BastiaanOlij** [comment] 2023-02-22 06:40
I did fix a rendering issue on compatibility this week, I need to find time to look into the sensor logic. We've probably changed things around the orientation handling. For VR purposes the automatic orientation should be turned off, the app needs to be fixed in a rotation.

**Comment by jeisoncp** [comment] 2023-07-03 20:36
In my project, I turned off automatic orientation, fixing in "Landscape" mode. But the issue persists. There is any other workaround?

**Comment by leandrodreamer** [comment] 2023-09-09 23:00
This seems to still happen in the latest 4.2 dev build. Is there any way to disable godot's tracking so it's possible to overwrite the camera rotation manually?

**Comment by metalx1000** [comment] 2023-11-01 20:46
I can confirm that rotation is very limited.

**Comment by octavioCuatrochio** [comment] 2024-02-17 02:49
Can confirm on Samsung A32.
Nearly no range of rotation.

There is a workaround for it?

**Comment by Razboinicul** [comment] 2024-02-18 09:11
Can confirm on Samsung J5.
Can you do something like using an alternative to the current rotation?

**Comment by Schrolli97** [comment] 2024-05-13 14:20
Can confirm on Pixel 7 Pro with Godot 4.2.2, but seems to be fixed in 4.3 Dev 6.

**Comment by akien-mga** [comment] 2024-05-13 14:45
Indeed, this issue is a duplicate of #89755, which was partially fixed by https://github.com/godotengine/godot/pull/91305 (the rotation issue was solved).

**Closed by akien-mga** 2024-05-13 14:45 UTC
Labels: bug, platform:android, topic:rendering, confirmed, topic:xr, regression, topic:3d
