### ISSUE TITLE
RigidBody interpolation

### ISSUE THREAD

**Issue by Smellyhobo101** [godotengine/godot#8253] opened 2017-04-04 06:31 UTC
Like in Unity:

https://docs.unity3d.com/ScriptReference/Rigidbody-interpolation.html
https://docs.unity3d.com/ScriptReference/Rigidbody2D-interpolation.html

My game looks so much smoother if I change the physics framerate to 144fps, but that's a bit overkill considering most people don't have 144hz monitors. Rigidbody interpolation would be a nice alternative.

**Comment by bojidar-bg** [comment] 2017-04-04 08:34
Note: fixed frame interpolation was discussed in https://github.com/godotengine/godot/issues/2043#issuecomment-115000788

**Comment by kubecz3k** [comment] 2018-04-07 11:07
Closing as a duplicate of https://github.com/godotengine/godot/issues/10388

**Closed by kubecz3k** 2018-04-07 11:07 UTC
Labels: feature proposal, topic:core, topic:physics
