### ISSUE TITLE
Cannot load any video in VideoPlayer

### ISSUE THREAD

**Issue by NathanLovato** [godotengine/godot#12772] opened 2017-11-09 12:17 UTC
**Issue description:**

In both alpha 2 and yesterday's master build (11/08) the VideoPlayer node doesn't accept any video. I tried with both .ogg and .ogv, encoded with libtheora, and @Calinou tried with .webm. Drag and drop or loading a video in the stream property doesn't work.

![image](https://user-images.githubusercontent.com/12694995/32605031-1de413aa-c550-11e7-8f39-60f575db9def.png)

**Steps to reproduce:**

Drag and drop a valid video file on the Stream property of a VideoPlayer node
or
1. Click the property
2. Click Load
3. Select all file formats
4. Open a *.ogg or *.ogv file

Nothing happens, the property stays empty.

**Comment by akien-mga** [comment] 2017-11-09 13:19
Duplicate of #10031.

**Closed by akien-mga** 2017-11-09 13:19 UTC
Labels: bug
