### ISSUE TITLE
Error compiling android release in variant_call.cpp

### ISSUE THREAD

**Issue by yonni12** [godotengine/godot#6041] opened 2016-08-04 17:44 UTC
**Operating system or device - Godot version:**
Ubuntu 16.04 64bit
Latest godot master branch

**Issue description** (what happened, and what was expected):
Compiling with `scons platform=x11` works fine.

Compiling with `scons platform=android target=debug` works fine if the visual scripting module is removed. Otherwise exits with
```
modules/visual_script/visual_script_editor.cpp: In member function 'void VisualScriptEditor::_member_edited()':
modules/visual_script/visual_script_editor.cpp:686:84: error: invalid cast to function type 'String()'
   EditorNode::get_singleton()->show_warning(TTR("Name is not a valid identifier:")+" "+new_name);
                                                                                    ^
modules/visual_script/visual_script_editor.cpp:696:100: error: invalid cast to function type 'String()'
   EditorNode::get_singleton()->show_warning(TTR("Name already in use by another func/var/signal:")+" "+new_name);
                                                                                                    ^
modules/visual_script/visual_script_editor.cpp: In member function 'void VisualScriptEditor::_member_button(Object*, int, int)':
modules/visual_script/visual_script_editor.cpp:998:62: error: invalid cast to function type 'String()'
     edit_variable_dialog->set_title(TTR("Editing Variable:")+" "+name);
                                                              ^
modules/visual_script/visual_script_editor.cpp:1024:58: error: invalid cast to function type 'String()'
     edit_signal_dialog->set_title(TTR("Editing Signal:")+" "+name);
                                                          ^
modules/visual_script/visual_script_editor.cpp: In member function 'void VisualScriptEditor::drop_data_fw(const Point2&, const Variant&, Control*)':
modules/visual_script/visual_script_editor.cpp:1542:45: error: 'class SceneTree' has no member named 'get_edited_scene_root'
    Node* sn = _find_script_node(get_tree()->get_edited_scene_root(),get_tree()->get_edited_scene_root(),script);
                                             ^
modules/visual_script/visual_script_editor.cpp:1542:81: error: 'class SceneTree' has no member named 'get_edited_scene_root'
    Node* sn = _find_script_node(get_tree()->get_edited_scene_root(),get_tree()->get_edited_scene_root(),script);
                                                                                 ^
modules/visual_script/visual_script_editor.cpp:1542:111: error: '_find_script_node' was not declared in this scope
    Node* sn = _find_script_node(get_tree()->get_edited_scene_root(),get_tree()->get_edited_scene_root(),script);
                                                                                                               ^
modules/visual_script/visual_script_editor.cpp:1589:45: error: 'class SceneTree' has no member named 'get_edited_scene_root'
    Node* sn = _find_script_node(get_tree()->get_edited_scene_root(),get_tree()->get_edited_scene_root(),script);
                                             ^
modules/visual_script/visual_script_editor.cpp:1589:81: error: 'class SceneTree' has no member named 'get_edited_scene_root'
    Node* sn = _find_script_node(get_tree()->get_edited_scene_root(),get_tree()->get_edited_scene_root(),script);
                                                                                 ^
modules/visual_script/visual_script_editor.cpp:1589:111: error: '_find_script_node' was not declared in this scope
    Node* sn = _find_script_node(get_tree()->get_edited_scene_root(),get_tree()->get_edited_scene_root(),script);
                                                                                                               ^
scons: *** [modules/visual_script/visual_script_editor.android.debug.armv7.neon.o] Error 1
scons: building terminated because of errors.
```

Compiling (without the visual scripting module for the above reason) with `scons platform=android target=release` exits with error:
```
core/variant_call.cpp: In static member function 'static Vector<StringName> Variant::get_method_argument_names(Variant::Type, const StringName&)':
core/variant_call.cpp:1196:18: error: 'const struct _VariantCall::FuncData' has no member named 'arg_names'
  return E->get().arg_names;
                  ^
core/variant_call.cpp: In static member function 'static Variant::Type Variant::get_method_return_type(Variant::Type, const StringName&, bool*)':
core/variant_call.cpp:1209:26: error: 'const struct _VariantCall::FuncData' has no member named 'return_type'
   *r_has_return=E->get().return_type;
                          ^
core/variant_call.cpp:1211:18: error: 'const struct _VariantCall::FuncData' has no member named 'return_type'
  return E->get().return_type;
                  ^
scons: *** [core/variant_call.android.opt.armv7.neon.o] Error 1
scons: building terminated because of errors.
```

**Comment by yonni12** [comment] 2016-08-04 18:28
Compiles fine by removing the #ifdef on lin 59 
https://github.com/godotengine/godot/blob/master/core/variant_call.cpp

**Comment by vnen** [comment] 2016-08-05 01:57
Travis builds are failing: https://travis-ci.org/godotengine/godot/jobs/149842842

**Comment by bojidar-bg** [comment] 2016-08-05 06:24
Dupe of #6022

**Closed by bojidar-bg** 2016-08-05 06:24 UTC
Labels: bug, topic:buildsystem
