### ISSUE TITLE
Exported property got reset after any code change

### ISSUE THREAD

**Issue by khachatrian1995** [godotengine/godot#49098] opened 2021-05-26 08:01 UTC
**Godot version:**
v3.3.2.stable.mono.official

**OS/device including version:**
macOS Big Sur (version 11.1)

**Issue description:**
I have a base C# class with the exported property. After attaching the inherited [Tool] class to some node, the property got reset every time either base or derived class is changed. Even adding space or comment causes the issue.

**Steps to reproduce:**
1. Open and build the project attached
2. Go to main.tscn
3. Select Spatial node and set some value to property 'prop'
4. Add any changes either to Base.cs or Inherited.cs
5. Build the project
6. Watch property 'prop' got reset to its default

**Minimal reproduction project:**
[issue_mono_exported_property_reset.zip](https://github.com/godotengine/godot/files/6544850/issue_mono_exported_property_reset.zip)

**Comment by Chaosus** [comment] 2021-05-26 08:47
> v3.2.2.stable.mono.official

it's an old version and no longer supported, check if this bug exists on 3.3.2?

**Comment by khachatrian1995** [comment] 2021-05-26 09:11
Sorry, there is a typo in the description . Actually this bug is on the latest stable version 3.3.2

**Comment by KoBeWi** [comment] 2021-05-26 23:38
Duplicate of #5969/#37812

**Closed by KoBeWi** 2021-05-26 23:38 UTC
Labels: bug, topic:mono
