### ISSUE TITLE
File.new().file_exists() behaves differently in iOS for some file types.

### ISSUE THREAD

**Issue by zaddok** [godotengine/godot#69425] opened 2022-12-01 01:25 UTC
### Godot version

3.5.1

### System information

Xcode 14.1

### Issue description

When you embed files inside a project, and export them to android, all of the files "exist". When you export to iOS, the mp3 files go missing. It is not clear if the files are missing from the exported package, or if the code in iOS can't "find" the file inside the package.

I am adding the following filters to export `*.mp3, Files/*.mp3, *.txt`

### Steps to reproduce

Here is a sample project, that contains a few MP3 files, and a text file. And a simple `_ready` function that checks the existence of each file.

When you run this project inside 3.5.1 it works and all of the files are detected.

When you export to Xcode 14.1, only the text file is marked as detected.

Here is a screenshot showing what is shown when this test project is run on my iPhone 10. It reports the .mp3 files as missing. Even though when I run on desktop, it reports the mp3 files as existing, and it can load them.

![Screenshot 2022-12-01 at 9 23 09 am](https://user-images.githubusercontent.com/20467896/204943552-c6a4e184-4901-44ff-a14e-c767bccda157.jpeg)

### Minimal reproduction project

[TestFilenameProject.zip](https://github.com/godotengine/godot/files/10128476/TestFilenameProject.zip)

**Comment by zaddok** [comment] 2022-12-01 01:35
The strangest part of all this, is that this used to work for me. So it is super strange that it no longer works. I have versions of this iOS project where the mp3 files load. But now they don't. I was using a 3.5 RC longer than I should have been, so I wonder if it is because I got around to updating to 3.5.1 proper, but I am really not sure.

**Comment by zaddok** [comment] 2022-12-01 01:56
It seems like I am not the first person to have tripped up on this one:

https://godotengine.org/qa/109102/array-of-audio-files-working-in-editor-but-not-when-exported

**Comment by zaddok** [comment] 2022-12-01 02:03
More time poking around the documentation and I discovered `ResourceLoader.exists`, and it lead me to being able to create the following function, that works around the problem.

```
func check_exists(f:String):
	var found = ResourceLoader.exists(f)
	if found:
		return found
	return File.new().file_exists(f)
```

I think I know enough about the problem to be able to describe the bug:

> `File.new().file_exists(f)` can correctly detect if an `mp3` or `txt` file exists when run on desktop. But when run on iOS it only detects if a txt file exists, and will report that the mp3 does not exist.  This difference in behavior results in confusion because code that runs during development will not run when deployed onto a phone.

**Comment by KoBeWi** [comment] 2022-12-01 12:24
Duplicate of #25672

**Closed by KoBeWi** 2022-12-01 12:24 UTC
