### ISSUE TITLE
Error when using static typing on exported property

### ISSUE THREAD

**Issue by paulloz** [godotengine/godot#25232] opened 2019-01-22 16:45 UTC
**Godot version:** 3.1-beta2
**OS:** Windows 10 Family

**Issue description:**  
Static typed exported properties don't have their default values and can't get reset.

**Steps to reproduce:**  
Create a scene and attach this script to a `Node`.  
```gdscript
extends Node

export var foo : int = 10
```
You'll see that the exported property value is `0` and not the one set in the script.
![image](https://user-images.githubusercontent.com/437025/51550734-420e1b00-1e6d-11e9-904f-a35cf64c0c5e.png)
If you change this value in the inspector and then click the reset button, this error will be raised.  
```
 core/object.cpp:1241 - Error calling method from signal 'property_changed': 'EditorInspector::_property_changed': Method expected 2 arguments, but called with 1.
```

Everything works fine if you remove the static type.

**Comment by vnen** [comment] 2019-01-23 20:54
Duplicate of #22124

**Closed by vnen** 2019-01-23 20:54 UTC
Labels: bug, topic:gdscript

**Comment by paulloz** [comment] 2019-01-23 20:57
Oops, didn't see this one when I searched for a duplicate. Sorry.

-- 

Paul Joannon - http://pauljoannon.com - @pauljoannon
hello@pauljoannon.com 0x128B663C - +33 6 24 57 50 53
