### ISSUE TITLE
Apple rejection

### ISSUE THREAD

**Issue by FabiGjuzi** [godotengine/godot#7211] opened 2016-11-30 09:58 UTC
I am having an issue with apple about ipv6(they say). I dont have any log in form on my game but the only moment when access user internet is the moment when he want to buy something from the store and I am using godot in app purchase. Any idea what should I do for this issue??
I am attaching screenshots from apple response.

T
![screen shot 2016-11-30 at 10 56 39 am](https://cloud.githubusercontent.com/assets/12370622/20747835/ea20435e-b6eb-11e6-88b9-4b14fa43d322.png)
![screen shot 2016-11-30 at 10 56 30 am](https://cloud.githubusercontent.com/assets/12370622/20747836/ea23a29c-b6eb-11e6-868f-6b2d06430d90.png)
![screen shot 2016-11-30 at 10 56 08 am](https://cloud.githubusercontent.com/assets/12370622/20747837/ea257d56-b6eb-11e6-9f10-2aa741bf6d35.png)

Thank you!!

**Comment by akien-mga** [comment] 2016-11-30 10:02
I assume this is with Godot 2.1.1?

**Comment by FabiGjuzi** [comment] 2016-11-30 10:04
no godot 2.1

**Comment by akien-mga** [comment] 2016-11-30 10:09
This should be fixed in 2.1.2 once we merge the IPv6 support in the stable branch.

**Comment by FabiGjuzi** [comment] 2016-11-30 10:12
When is 2.1.2 supposed to be released?

**Comment by akien-mga** [comment] 2016-11-30 10:14
Once the IPv6 support is ready :)

**Comment by punto-** [comment] 2016-11-30 10:16
Can you attach the screenshot that they reference to in the error? I don't
think it's related to ipv6, it says they're unable to purchase something,
that's all in the apple libraries.

**Comment by FabiGjuzi** [comment] 2016-11-30 10:16
I have attached the screenshots already

**Comment by punto-** [comment] 2016-11-30 10:19
I'm talking about the file "Screenshot 1129 143647.png", where the error is
supposed to be

**Comment by FabiGjuzi** [comment] 2016-11-30 10:20
it is just a game screenshot not an error screenshot
<img width="1024" alt="attachment-3719993386302574759screenshot_1129_143647 1" src="https://cloud.githubusercontent.com/assets/12370622/20748571/fc827bcc-b6ee-11e6-9c3c-3980cd2ac7a5.png">

**Comment by FabiGjuzi** [comment] 2016-11-30 10:22
if the user can not purchase the item this pop up shows up. If the user finalizes with success the buy another pop up with success message show up

**Comment by FabiGjuzi** [comment] 2016-11-30 10:27
any idea when the 2.1.2 version could be released?

**Comment by punto-** [comment] 2016-11-30 10:28
it doesn't look like it's related to the ipv6 code.. Can you reproduce
this? and check what the error is in the response from the StoreKit code?
Are you giving apple the right sandbox user to test the IAP stuff? (I don't
remember if that was necessary)

**Comment by akien-mga** [comment] 2016-11-30 10:30
> any idea when the 2.1.2 version could be released?

I answered you already.

**Comment by FabiGjuzi** [comment] 2016-11-30 10:31
@akien-mga I mean a date or a period of time

**Comment by akien-mga** [comment] 2016-11-30 10:34
Sometime in 2016 probably. But as @punto- mentioned, your problem might not be IPv6 support anyway.

**Comment by punto-** [comment] 2016-11-30 10:36
don't worry about 2.1.2, if you're not using the network for anything, this
isn't an ipv6 problem, it's a problem with the StoreKit code, or the
configuration on your game, maybe the apple testers are hitting a condition
that you didn't test for

**Comment by FabiGjuzi** [comment] 2016-11-30 10:39
@punto-  ok thank you!!!

**Comment by akien-mga** [comment] 2017-02-14 13:12
What's the status on this issue? Does it work better with 2.1.2?

**Comment by kubecz3k** [comment] 2017-03-17 15:05
I assume the problem was related somehow to the game itself (in app purchases api or something), will archive this issue.

**Closed by kubecz3k** 2017-03-17 15:05 UTC
Labels: bug, platform:ios, topic:core
