### ISSUE TITLE
Vulkan: GPUParticles3D angular velocity has jumps

### ISSUE THREAD

**Issue by QbieShay** [godotengine/godot#49767] opened 2021-06-20 17:40 UTC
### Godot version

v4.0.dev.custom_build [1acc76fec]

### System information

Linux Arch, Radeon RX 590

### Issue description

Enabling angular velocity  results in the particle angle to abruptly jump during the particle lifetime

https://gfycat.com/difficultweebrontosaurus

### Steps to reproduce

- Create a 3D scene with a particle node
- Assign quad material with particle billboard
- Enable angular velocity

**Comment by Calinou** [comment] 2022-05-29 10:18
@QbieShay Can you still reproduce this on 4.0.alpha8? Also, can you reproduce this after setting **Fixed FPS** to 0 on the GPUParticles3D? If not, this might be due to the same cause as https://github.com/godotengine/godot/issues/55357.

**Comment by QbieShay** [comment] 2023-02-22 15:57
Still observing strange jumps as of RC2. `unfa` in rocket chat had a way to repro the issue.

**Comment by akien-mga** [comment] 2023-02-22 16:21
CC @unfa. Moving to 4.x for now as it's unlikely to be fixed this week.

**Comment by Calinou** [comment] 2023-02-22 17:48
I can't reproduce this on 4.0.rc3 when using angular velocity + particle billboard in 3D. (It should be noted that angular velocity does nothing if not using Particle Billboard, which I find a bit surprising.)

**Minimal reproduction project:** [test_particle_angular_velocity.zip](https://github.com/godotengine/godot/files/10806815/test_particle_angular_velocity.zip)

### 2D

https://user-images.githubusercontent.com/180032/220712278-9f8e3563-4be8-4dab-b2dd-3a312d504d78.mp4

### 3D

https://user-images.githubusercontent.com/180032/220712290-4c22a254-8c76-4a8b-9f48-f3a46518fe34.mp4

**Comment by unfa** [comment] 2023-02-23 01:22
I am not sure if this is the same bug, or a different one, but it's been affecting me since the beginning of Godot 4:

[SSR-2023-02-23_02.19.57.webm](https://user-images.githubusercontent.com/491704/220801191-c669a040-8397-46e6-a165-8bca1ac1a4aa.webm)

[Particle Rotation Jolt.zip](https://github.com/godotengine/godot/files/10809550/Particle.Rotation.Jolt.zip)

**Comment by QbieShay** [comment] 2023-03-26 18:47
I have the same with random angle. I feel like there's some strange stuff happening between the moment a particle dies and the moment it is respawned after. I took a video of what I was experiencing (and i could fix it by fading in the particle later).

I am not sure what it is. I have tried making changes to the particle shader (for example angle is not taking into account the lifetime, but it takes directly CUSTOM.y which ignores random lifetime) but even fixing that doesn't fix the issue of the angle. I think it's a discrepancy on how particle data is handled. It doesn't even look like it's an issue with particle index because even when using a constant number for the random, it still shows.

https://user-images.githubusercontent.com/7917475/227797287-3208b7bd-d4bd-4a10-9249-9a1e30de46dc.mp4

**Comment by QbieShay** [comment] 2023-03-27 12:50
This is in 4.0 stable ^

**Comment by clayjohn** [comment] 2023-04-12 18:17
Taking a look into this. 

The base angle is stored in ``CUSTOM.x`` in the ``start()`` function:
https://github.com/godotengine/godot/blob/d4dad2b2f88968ff329145f3dab5290478bae886/scene/resources/particle_process_material.cpp#L473-L474

Then it is updated in the ``process()`` function:
https://github.com/godotengine/godot/blob/d4dad2b2f88968ff329145f3dab5290478bae886/scene/resources/particle_process_material.cpp#L740-L742

Note how ``angle_rand`` is used the first time, but the second time a new random amount is generated

**Comment by QbieShay** [comment] 2023-04-13 10:28
Thank you Clay!

**Closed** 2023-04-14 11:14 UTC
Labels: bug, topic:rendering, topic:3d, topic:particles
