### ISSUE TITLE
Editable Children Flag Turns Off Due to Node Path Change

### ISSUE THREAD

**Issue by Lucrecious** [godotengine/godot#27064] opened 2019-03-14 19:58 UTC
**Godot version:**
3.1

**OS/device including version:**
OSX Latest

**Issue description:**
I changed the node path of a node that has `Editable Children` enabled, and it disabled `Editable Children`. The edits made to the children do not change, but the child nodes are not accessible anymore. If I turn `Editable Children` back on, everything seems to go back to normal since the children node states are somehow preserved.

For example, if I enable `Editable Children` on a node, and I edit one of the children, the edit is preserved despite `Editable Children` being disabled from changing the path.

**Steps to reproduce:**
1. Open a Godot file
2. Make a new scene, say `Scene A`
3. Make new scene, say `Scene B`, and instance A in it
4. Enable `Editable Children` for the `Instance A` in `Scene B`
5. Change the name of `Instance A` in `Scene B`.
6. (Alternative to 5) Change the name of a parent node for the `Instance A` in `Scene B`

Expected: The name changes and that's it
Actual: The name changes, but `Editable Children` gets disabled

Edit:
As a side note, I'm having a hard time finding documentation for what `Editable Children` actually does. The inspector properties are all red, I don't know what that means. I don't know the limitations to `Editable Children` either.

**Comment by Zylann** [comment] 2019-12-06 23:31
Still happens in Godot 3.2 beta2

**Comment by KoBeWi** [comment] 2020-11-20 16:19
Duplicate of #20409

**Closed by KoBeWi** 2020-11-20 16:19 UTC
Labels: bug, confirmed, topic:editor, usability
