### ISSUE TITLE
Font antialiasing value is not stored in scene

### ISSUE THREAD

**Issue by p10tr3k** [godotengine/godot#28537] opened 2019-04-30 18:45 UTC
Godot version: 3.1.1

![godotbugwithfontantialiasing](https://user-images.githubusercontent.com/11059246/56985397-87d33180-6b88-11e9-9939-30d9aeb849cd.gif)

Also changing this value does not refreshes it state

**Comment by KoBeWi** [comment] 2019-05-23 16:12
Seems like Antialiasing/Hinting is a property of .ttf resource and there isn't any way to legitimately edit them (?).

**Comment by pgoral** [comment] 2019-05-23 16:56
I just want to notice that when I make font "dynamic" I was able to disable antialiasing

**Comment by volzhs** [comment] 2019-05-23 17:35
you mean on and off it while running game?

**Comment by Calinou** [comment] 2019-05-23 18:03
> Seems like Antialiasing/Hinting is a property of .ttf resource and there isn't any way to legitimately edit them (?).

You can, but you will need to save the DynamicFontData (not DynamicFont!) as a resource (`.tscn`). The file will only reference the TTF/OTF font file, so it will remain VCS-friendly.

**Comment by KoBeWi** [comment] 2019-05-23 18:14
> You can, but you will need to save the DynamicFontData resource (not DynamicFont!) to a .tres file.

Wow, this is possible? IMO it should be some import option. It's obscure, inconsistent with every other resource (like, it stores path to .ttf file inside .tres, even if technically it's the same resource) and doesn't make sense :/

**Comment by akien-mga** [comment] 2020-06-22 09:52
> As for changes not being displayed immediately in the 2D view, this is already reported in #27106. As a workaround, you can change an unrelated parameter in DynamicFont to cause the font to refresh.

The "bug" part is thus a duplicate of #27106.

Keeping the issue for the other UX issue with DynamicFont/DynamicFontData.

**Comment by Calinou** [comment] 2021-03-16 00:50
Duplicate of https://github.com/godotengine/godot/issues/25626.

**Closed by Calinou** 2021-03-16 00:50 UTC
Labels: discussion, documentation, topic:editor, topic:gui, usability
