### ISSUE TITLE
Game project in godot 4 editor crashes

### ISSUE THREAD

**Issue by fire** [godotengine/godot#61699] opened 2022-06-04 18:29 UTC
### Godot version

https://github.com/godotengine/godot/commit/ecde7ce8345a54becf65c166e1c9efc640e37837

### System information

OSX, amd external gpu rx580

### Issue description

Launching our game editor crashes.

https://github.com/godotengine/godot/blob/ecde7ce8345a54becf65c166e1c9efc640e37837/editor/scene_tree_editor.cpp#L582

Put a null check here on `p_parent`.

### Steps to reproduce

1. Compile godot @ version
2. Open game project
3. Crash

### Minimal reproduction project

https://github.com/V-Sekai-fire/SCENE_morning_in_a_cafe

**Comment by KoBeWi** [comment] 2022-06-04 18:57
Duplicate of #61654

**Closed by KoBeWi** 2022-06-04 18:57 UTC
