### ISSUE TITLE
Order of shader uniform properties is alphabetical, not in shader-code order

### ISSUE THREAD

**Issue by paddy-exe** [godotengine/godot#63035] opened 2022-07-15 13:08 UTC
### Godot version

v4.0.alpha12.official [2c11e6d9e]

### System information

Win10

### Issue description

The shader uniform properties are being structured in an alphabetical order instead of the actual written order in the shader code.

The actual desired effect (shown here with GDScript):
![image](https://user-images.githubusercontent.com/38077837/179227780-667f3ba6-3314-434e-ba96-eceb6fa788f7.png)

What instead happens:
![image](https://user-images.githubusercontent.com/38077837/179228199-2dd4d7a6-ca48-43cd-81b6-e5179567116e.png)

@Chaosus mentioned here already that this is due to the Shader Uniforms being stored in a HashMap instead of a Vector: https://github.com/godotengine/godot/pull/62972#issuecomment-1183026786

### Steps to reproduce

* Create a new shader in a new project or open up the minimal reproduction project
* create a uniform that starts with a letter like "W"
* create another uniform that starts with a letter like "A" that comes in the alphabet before the above letter in the next line
* look at the inspector and the order of the uniforms 

### Minimal reproduction project

[Godot4Alpha12Test.zip](https://github.com/godotengine/godot/files/9120970/Godot4Alpha12Test.zip)

**Comment by akien-mga** [comment] 2023-02-02 17:33
Duplicate of https://github.com/godotengine/godot/issues/69949

**Closed by akien-mga** 2023-02-02 17:33 UTC
Labels: enhancement, topic:editor, usability, topic:shaders
