### ISSUE TITLE
debugger errors list does not display errors into the list

### ISSUE THREAD

**Issue by SuperUserNameMan** [godotengine/godot#4805] opened 2016-05-25 11:36 UTC
**Operating system or device - Godot version:**
Official 2.0.3stable win64

**Issue description** (what happened, and what was expected):
The list of errors into the debugger does not display any information about the errors.
To see information about each error, I have to hover them one after each other to read the hint box.

![bug_debugger_errors_box](https://cloud.githubusercontent.com/assets/9801802/15538618/a23c13d6-227d-11e6-9303-86764bda5cb9.png)

**Steps to reproduce:**

**Link to minimal example project** (optional but very welcome):

**Comment by akien-mga** [comment] 2016-05-25 11:38
Marking as confirmed as I've seen it quite often too (usually those are errors that get printed to the terminal, but it would be nice to have them shown in the debugger without a need for hover indeed).

**Comment by neikeq** [comment] 2016-05-25 21:02
I wouldn't call it a bug. The error list show the error description, which is not always provided.

**Comment by vnen** [comment] 2016-05-25 21:20
But why some errors do not have a description? Shouldn't they all have one?

**Comment by akien-mga** [comment] 2016-05-25 21:38
Well what I would call a bug here is the way things are presented. It's not user friendly to have a list of timestamps ending with a ``-``. The timestamps themselves don't give any info, and the ``-`` hints that there should be a description afterwards. If those are meant to only provide info on tooltip, we should probably rethink the way it's shown visually in the debugger, as right now it feels like a usability bug.

**Comment by neikeq** [comment] 2016-05-26 11:14
Damn, labels will kill me :P
@vnen Well, I guess there are many situations where a description adds nothing useful to the actual error message. In any case, I've seen many errors that should have a description but they don't have it.

**Comment by vnen** [comment] 2016-05-26 16:43
@neikeq I can see that some descriptions could be redundant. But in the OP's screenshot the C error is "Index p_y out of size (h)." which is not much helpful. You'd have to look at the C++ source to get an idea of what it means.

**Comment by neikeq** [comment] 2016-05-26 18:11
If #4814 is merged, the error message will be displayed if there is no description. From there, we could search for `ERR_*` macros usages and add an `ERR_EXPLAIN(description)` with a description where relevant.

**Closed** 2016-05-29 16:32 UTC
Labels: bug, confirmed, topic:editor, usability

**Comment by neikeq** [comment] 2016-05-29 16:48
Should we re-open since there are errors that could have a description? or perhaps open another issue.

**Comment by akien-mga** [comment] 2016-05-29 16:49
I think another issue would be better suited.
