### ISSUE TITLE
[FBX][3.2.4 beta2][by design: compatibility] Additional RootNode added to scene, inside of the actual root node.

### ISSUE THREAD

**Issue by lyuma** [godotengine/godot#43824] opened 2020-11-24 15:36 UTC
**Godot version:**
3.2.4 beta2

**OS/device including version:**
Windows 10.0.19041.630
NVidia GeForce RTX 2080 Ti 452.06

**Issue description:**
Because Godot scenes *are* already rooted at a node, the extra level RootNode is pointless and may break paths for no reason.

If an argument is made about transforms of top level objects in the FBX file, I would like to make a counter-argument that glTF and other formats dealt with this issue fine and do not need an extra root node.

![image](https://user-images.githubusercontent.com/39946030/100115104-fb055e00-2e26-11eb-8154-17b3cbf568af.png)

**Steps to reproduce:**
1. Open the attached project.
2. Click Bunny_Farmer.fbx and click Reimport in the import panel.
3. Open the imported scene.
4. Notice that an extra RootNode was created and sits between the actual root node of the scene (named Bunny_Farmer) and the contents of the scene.

**Minimal reproduction project:**
[fbx_issues.zip](https://github.com/godotengine/godot/files/5590831/fbx_issues.zip)

**Comment by RevoluPowered** [comment] 2020-11-26 13:33
This is to prevent compatibility breaking from assimp to the new fbx importer. for 4.0 it's planned to be removed, this is not a bug this is by design since the old importer created this node it could not just be removed as all inherited subscenes would be broken.

**Comment by RevoluPowered** [comment] 2020-11-26 13:46
So since this is for 4.0 as it entirely breaks compatibility with inherited subscenes this can't be done for 3.2 beta.

**Comment by RevoluPowered** [comment] 2020-11-26 13:47
To keep any compatiblity with existing user scenes this must remain in the importer until 4.0 I will move this to 4.0.

**Comment by RevoluPowered** [comment] 2020-11-26 13:56
for 4.0 the goal would be: remove /RootNode/ compatibility since Reduz is working on replacing the Importer / inherited subscene to be unable to cause this problem.

**Comment by metinc** [comment] 2021-09-17 11:38
I just ran into this using Godot 3.3.3-stable. I used to import an FBX as instanced Sub-Scenes. But now I get a single scene called RootNode.scn making me unable to proceed work on my project. I think this was already pointed out by @RevoluPowered but I don't understand what 3.3.3 users are supposed to do now. Is the option "instanced Sub-Scenes" (for now) useless and is there a workaround or should I just export all meshes from Blender as seperate FBX files?

**Comment by lyuma** [comment] 2021-09-21 07:57
I see you are using Blender.  If you are using Blender in your pipeline, you may benefit by switching to glTF 2.0 now. Plus, if you play your cards right, you may be able to re-export as glTF, and setup your gltf document to generate instanced subscenes, and perhaps it will work as fbx used to! (I even suspect that the references will automatically match up with your old FBX version from 3.2, and you won't break compatibility)

generally speaking, Blender FBX currently have some breaking bugs which Revolu knows about but hasn't fixed yet. So I'd expect more breaking changes in the future once blender support is made official. That's another reason to try glTF.

About this issue...
I filed this issue originally because the change to the new FBX importer broke compatibility (namely, the RootNode was not there before).

I believe the RootNode is a mistake, and I'm looking forward to improvements in the FBX importer that get rid of it.

The argument about backwards compatibility is well past moot at this point. The backwards compatibility boat sailed a long time ago when 3.3 was released, so Godot should focus on fixing bugs and moving forward. Maybe an import option to remove the top-level node would solve this pretty cleanly. (And it can double-up as a compatibility setting.)

**Comment by metinc** [comment] 2021-09-21 20:40
Thanks, I can confirm using glTF 2.0 works as workaround!

**Comment by akien-mga** [comment] 2022-04-06 22:22
This is probably fixed with the new FBX importer using [FBX2glTF](https://github.com/V-Sekai/FBX2glTF/releases).
You can test it in Godot 4.0 alpha 6: https://godotengine.org/article/dev-snapshot-godot-4-0-alpha-6
This new importer might also be backported for the `3.x` branch eventually.

If you still find issues with these models using the new importer, we suggest opening a new issue with details about the problems in Godot 4.0 alpha 6 or later.

**Closed by akien-mga** 2022-04-06 22:22 UTC
Labels: enhancement, confirmed, topic:import, topic:3d
