### ISSUE TITLE
RefCounted reference count error

### ISSUE THREAD

**Issue by Geequlim** [godotengine/godot#64791] opened 2022-08-23 16:03 UTC
### Godot version

4.0 alpha11

### System information

Linux

### Issue description

Call unreference to a dead refrenece object it will relive.

As the the type of `RefCounted::refcount` is `SafeRefCount`

### Steps to reproduce

Make a `RefCounted` object and call `unreference` twice.
The object will be *dead* after first call and relive after second call.

![2022-08-23 23-50-31屏幕截图](https://user-images.githubusercontent.com/6964556/186211191-50a3d449-7a01-476b-a0ca-abbf30cc317d.png)

Change the reference count from `uint32_t` to `int32_t` to solve the problem ?

**Comment by reduz** [comment] 2023-01-06 21:44
These functions should not be called manually, we are discussing removing them from the exposed API. Is there a specific reason why you need to call them directly?

**Comment by akien-mga** [comment] 2023-01-09 13:36
Fixed by #64795 which raises an error when misusing this API.

**Closed by akien-mga** 2023-01-09 13:36 UTC
Labels: bug, topic:core

**Comment by dalexeev** [comment] 2023-01-11 18:15
> These functions should not be called manually, we are discussing removing them from the exposed API. Is there a specific reason why you need to call them directly?

@reduz Here is an example:

```gdscript
class A extends RefCounted:
    # `A` exclusively owns `B`, 1-to-1 relationship.
    var b := B.new(self)

class B extends RefCounted:
    var _a: A

    # `B` is never instantiated directly, only via `A`.
    func _init(a: A) -> void:
        _a = a
        _a.unreference() # `_a` holds a strong reference, not `WeakRef`.
```

**Comment by kleonc** [comment] 2023-01-11 18:49
> ```gdscript
> class A extends RefCounted:
>     # `A` exclusively owns `B`, 1-to-1 relationship.
>     var b := B.new(self)
> 
> class B extends RefCounted:
>     var _a: A
> 
>     # `B` is never instantiated directly, only via `A`.
>     func _init(a: A) -> void:
>         _a = a
>         _a.unreference() # `_a` holds a strong reference, not `WeakRef`.
> ```

@dalexeev You can use [`weakref`](https://docs.godotengine.org/en/latest/classes/class_%40globalscope.html#class-globalscope-method-weakref). The issue is it doesn't preserve static typing of the argument (like many other methods working with Variants). So you'd need to use e.g. `as` for specifying the type (so the assignment won't fail):
```gdscript
class A extends RefCounted:
    # `A` exclusively owns `B`, 1-to-1 relationship.
    var b := B.new(self)

class B extends RefCounted:
    var _a: A

    # `B` is never instantiated directly, only via `A`.
    func _init(a: A) -> void:
        _a = weakref(a) as A
```

**Comment by dalexeev** [comment] 2023-01-11 19:29
@kleonc I don't think your code will work. The following option will work, but it introduces overhead:

```gdscript
class A extends RefCounted:
    # `A` exclusively owns `B`, 1-to-1 relationship.
    var b := B.new(self)

class B extends RefCounted:
    var _a_weakref: WeakRef

    var _a: A:
        get: return _a_weakref.get_ref()

    # `B` is never instantiated directly, only via `A`.
    func _init(a: A) -> void:
        _a_weakref = weakref(a)
```

**Comment by kleonc** [comment] 2023-01-11 19:58
@dalexeev Oh, you're absolutely right. I somehow made myself believe it has changed somehow in 4.0, the `weakref(a) as A` form my code indeed fails / returns null.

**Comment by dalexeev** [comment] 2023-01-11 20:13
By the way, the `weakref` function signature actually changed:

![](https://user-images.githubusercontent.com/47700418/211906592-a5516aed-3155-4f07-8999-5f1bc9263b70.png)

although `WeakRef` is always returned:

```gdscript
print(weakref(RefCounted.new())) # <WeakRef#...>
print(weakref(Node.new())) # <WeakRef#...>
print(weakref(null)) # <WeakRef#...>
print(weakref(42)) # Invalid type in utility function 'weakref'. Cannot convert argument 1 from int to Object.
```

See https://github.com/godotengine/godot/blob/master/core/variant/variant_utility.cpp.
