### ISSUE TITLE
Sky Visually Bugs When Auto Exposure Very High

### ISSUE THREAD

**Issue by WickedInsignia** [godotengine/godot#75129] opened 2023-03-20 02:05 UTC
### Godot version

4.0 Stable

### System information

Windows 11, Nvidia RTX4070ti, AMD Ryzen7700x

### Issue description

Procedural and Physical sky environments will show visual bugs when set to a low exposure (around 1000 nits) and Camera Attributes Physical/Practical Auto Exposure is turned on. This does not occur when using the ISO expsoure slider to bring the exposure up to a similar level.

![SkyExposureBug](https://user-images.githubusercontent.com/70243134/226229741-698be24c-6bd9-40c8-b86b-9b4a8ea5e3c4.jpg)

### Steps to reproduce

- Add a physical/procedural sky
- Set the exposure very low in physical units (1000 nits or so)
- Set Camera Attributes Practical/Physical to Auto Exposure and attach this resource to the World Environment

Scene with all appropriate values already provided in the MPR.

### Minimal reproduction project

[SkyExposureBug.zip](https://github.com/godotengine/godot/files/11013094/SkyExposureBug.zip)

**Comment by mrjustaguy** [comment] 2023-03-20 08:54
Turn off Debanding in the Sky Shaders, the Sky Shader Debanding isn't taking Exposure into account (aside from maybe the static value given) afaik.

**Comment by WickedInsignia** [comment] 2023-03-20 10:12
Ah yeah, turning debanding off does the trick. Of course you then have pulsating banding artifacts as the exposure changes, but nice to have a fallback option in the meantime. Thanks!

**Comment by Calinou** [comment] 2023-03-20 16:41
Duplicate of https://github.com/godotengine/godot/issues/74140.

**Closed by Calinou** 2023-03-20 16:41 UTC
