### ISSUE TITLE
Navigating an Itemlist with keyboard results in strange behavior

### ISSUE THREAD

**Issue by gusthe** [godotengine/godot#3673] opened 2016-02-11 19:49 UTC
When navigating through an itemlist with the keyboard the selected item becomes hidden.

For example in this item list with 14 test items navigating down to item 10 with the down key results in the following correct behavior.
![1_003](https://cloud.githubusercontent.com/assets/11148529/12987919/489dd452-d0cc-11e5-8570-e06f3d620f10.png)

If I try to go down one more item this happens
![1_004](https://cloud.githubusercontent.com/assets/11148529/12987983/a0e39214-d0cc-11e5-86c2-2857f0eac060.png)
In the above picture item 11 is selected but is not visible due to the itemlist not scrolling down enough. If I continue to go down the selected item is always hidden. Here I've navigated down to 14 using the down key.
![1_005](https://cloud.githubusercontent.com/assets/11148529/12988020/dd26a810-d0cc-11e5-8c7d-7cb02837030f.png)

Navigating up results in the same behavior. Here I moved back up to item 1 but it is hidden.
![1_006](https://cloud.githubusercontent.com/assets/11148529/12988069/09da8e3a-d0cd-11e5-8b8b-00feb589c0ee.png)

**Comment by Zephilinox** [comment] 2017-09-14 13:35
Seems to be fixed, can't reproduce using a build from about a week ago

![3673](https://user-images.githubusercontent.com/2060863/30432544-e29770a2-9959-11e7-865b-42d6b51ce275.gif)

**Comment by bojidar-bg** [comment] 2017-09-14 13:46
What about 2.1.x, does it still happen there?

**Comment by Zephilinox** [comment] 2017-09-14 14:03
Tested it with 2.1.4 32-bit windows and it's fixed on there

**Comment by bojidar-bg** [comment] 2017-09-14 19:12
Ok, closing as fixed, would reopen if it is still an issue.

**Closed by bojidar-bg** 2017-09-14 19:12 UTC
Labels: bug, topic:editor, usability
