### ISSUE TITLE
[Bullet] Running project gives recover from penetration error.

### ISSUE THREAD

**Issue by ca3games** [godotengine/godot#50628] opened 2021-07-20 01:55 UTC
### Godot version

3.3.2 (stable official)

### System information

Kubuntu 21.04 (Hirsute) GLES 3 renderer.

### Issue description

After compiling a project without issues and compiling without error, after 2 minutes on average I get this error:

E 0:00:05.563   recover_from_penetration: Condition "shape_idx < 0 || shape_idx >= cs->getNumChildShapes()" is true. Returned: false
  <Fuente C++>  modules/bullet/space_bullet.cpp:1294 @ recover_from_penetration()
  <Stack Trace> WALK.gd:41 @ Physics()
                FSM.gd:29 @ _physics_process()

The WALK.gd:41 line is:
FSM.Root.move_and_collide(Vector3(dir.x, 0, dir.y), false)

Not sure what causes it, but the project runs without error around 1-2 minutes just fine and then spit that error.

### Steps to reproduce

It happens after 1-2 minutes of playing the game.

![error](https://user-images.githubusercontent.com/19626687/126250316-2d24b689-19a2-406a-bd24-3621282a893d.png)

### Minimal reproduction project

[Flor Game.tar.gz](https://github.com/godotengine/godot/files/6844927/Flor.Game.tar.gz)

**Comment by pwab** [comment] 2021-08-31 10:09
I can confirm the error on my system (Windows 10, Ryzen 5, RX 570). But I already get it when pushing one arrow-key once (so not time depended). After receiving the error I just waited a few seconds and got another one which then floods the console log:

```
E 0:00:12.303   get_quat: Basis must be normalized in order to be casted to a Quaternion. Use get_rotation_quat() or call orthonormalized() instead.
  <C++ Error>   Condition "!is_rotation()" is true. Returned: Quat()
  <C++ Source>  core/math/basis.cpp:791 @ get_quat()
  <Stack Trace> FSM.gd:25 @ _process()
```

This error seems to be time depended because I wasn't able to directly reproduce it.
The errors are pointing at

```gdscript
func Physics(delta):  # <- called on _physics_process
	var dir = FSM.direction * FSM.vel * delta
	FSM.Root.move_and_collide(Vector3(dir.x, 0, dir.y), false)
```

and

```gdscript
func _process(delta):
	current.Update(delta)
	var target_point = Root.translation + Vector3(-direction.x, 0, -direction.y)
	var old_basis = Root.transform.basis
	Root.look_at(target_point, Vector3.UP)
	var target_basis = Root.transform.basis
	Root.transform.basis = old_basis.slerp(target_basis, delta * 10.0)
```

**Comment by rburing** [comment] 2022-06-18 16:38
Fixed by https://github.com/godotengine/godot/pull/59864.

**Comment by fabriceci** [comment] 2022-06-18 16:54
I tried with the mrp and the error is gone as @rburing said.

**Closed by fabriceci** 2022-06-18 16:54 UTC
Labels: bug, topic:physics, topic:3d
