### ISSUE TITLE
Particles2D and Particles resets when changing Amount parameter

### ISSUE THREAD

**Issue by Boothand** [godotengine/godot#16352] opened 2018-02-03 14:22 UTC
**Godot version:**
3.0

**OS/device including version:**

Win 10

**Issue description:**

When changing the Amount parameter, the particle system resets the simulation. Expected to just start emitting the new amount without deleting the already emitted particles. Intention: Changing it from code so that it emits more or less under certain circumstances.

**Steps to reproduce:**
Make Particles2D, drag the Amount slider.

**Comment by nical** [comment] 2018-02-05 18:41
By the look of the code, the gles3 renderer sets a bunch of parameters and the entire simulation is run on the GPU in the vertex shader (I suppose using transform feedbacks the result of the simulation). Because resizing causes godot to allocate new buffers for the particle data, the previous buffer ends up lost.

The editor could expose a maximum number of particles and allocate a buffer of that size so that the data is not lost. That's probably straightforward to implement.
The rendering engine could also support reallocating buffers without losing the content of the previous buffer. shrinking the buffer doesn't require much work (just sample from the previous frame's buffer with new frame's particle count), growing it would require a draw call to do the simulation with the number of particles from the previous frame and another draw call to take care of the new particles (maybe a bit more fiddly).

**Comment by QbieShay** [comment] 2018-06-16 18:17
@akien-mga  I don't think this issue should be labeled as enhancement, i think it's a bug: it makes it impossible to use particles for effects with a varying amount (in my case, i needed to modify the drops of water from a shower depending on how much the valves were open)

**Comment by OvermindDL1** [comment] 2018-06-18 15:22
Should probably just have a 'current' amount and a 'max' amount?

**Comment by voithos** [comment] 2018-07-05 18:16
I recently ran into this as well. It's not perfect, but I was able to somewhat work around it by having multiple `Particles2D` nodes at the same position, making only one of them visible initially, and controlling the modulate (transparency) to "merge" the other particle systems in as the effect animates (in my case, I was trying to get a flame effect, so having semi-transparent particles was fine).

**Comment by 0nepixel** [comment] 2019-01-10 03:49
Same in Godot 3.1 alpha 5.0, the bug persist :/

**Comment by lukaskotik** [comment] 2019-02-13 11:21
Also CPUParticles2D are affected by this behaviour.

**Comment by JFonS** [comment] 2019-02-13 11:35
It's not a bug, so far it's expected behaviour. I agree it should be improved, but I'm not sure it can slip into 3.1

**Comment by emarod** [comment] 2019-03-15 13:20
Try hiding the particles first, change the amount and make them show then

**Comment by voithos** [comment] 2019-03-16 04:54
@emarod Won't that effectively do the same thing? "Reset" the existing particle system's emissions?

**Comment by Thource** [comment] 2019-04-09 18:45
This also affects Particles (the 3D equivalent), I believe the shader posted above is for Particles2D, so if anyone has a 3D equivalent of that shader I'd massively appreciate it :)

**Comment by CJCarns** [comment] 2020-01-12 18:23
I believe if you set the "preprocess" value on the particles you can get something a little better, although not perfect. It works well enough for fire and such.

**Comment by fooff** [comment] 2020-05-18 15:16
still present on 3.2.1 (3D particle)

**Comment by Toemsel** [comment] 2020-12-11 00:19
Why did you remove the "bug" label @Calinou? This is clearly not an expected behaviour. If I do change the particle amount with the documented property (.set_amount(value)) then one does expect to see the corresponding result.

**Comment by Calinou** [comment] 2020-12-11 00:25
> Why did you remove the "bug" label @Calinou? This is clearly not an expected behaviour. If I do change the particle amount with the documented property (.set_amount(value)) then one does expect to see the corresponding result.

The current particle system in 3.2.x will likely remain as-is until Godot 4.0 is released. It's better to document the limitation first :slightly_smiling_face:

**Comment by Toemsel** [comment] 2020-12-11 00:28
@Calinou agree on that. But doesn't removing the label may cause confusion within the community + bug-fixing developers?

**Comment by kobligo** [comment] 2021-04-13 13:52
Am I seeing this right? It's been over three years since this was reported, and it still hasn't been taken care of?
I ran into this issue on my very first day of learning this engine, and basically had to cancel my project as a result, so I'd say it's a pretty serious bug.

**Comment by Calinou** [comment] 2021-04-13 14:05
> Am I seeing this right? It's been over three years since this was reported, and it still hasn't been taken care of?

Unfortunately, fixing this issue isn't trivial, so it will take a while to be fixed.

**Comment by kobligo** [comment] 2021-04-13 14:39
> but not before 3.4.
I see. Thank you for letting me know.
Switching to a different engine. Here's hoping Godot will be able to sort out its teething troubles within the next couple of years at least.

**Comment by esaytee2** [comment] 2021-05-23 09:17
Hello everybody, I have a similar experience now. I'm working on the charging particle effect. The goal is to start with a very small amount of particles and then continuously increase the amount over time as charging is proceeding to the "highest level" to achieve the tension.

It would be great if somebody can fix this as it seems like a bug. I am referring to the statement: "Animate everything!" as a feature of the engine animation system. Well, it is possible to animate the value but it is resetting the whole system - an undesired result.

My only solution now would be to have animated texture to increase the number of "particles", which is not optimal. Unless the increased amount of texture is performance cheaper than the number of particles, which I doubt.

**Comment by Calinou** [comment] 2021-05-23 12:28
> My only solution now would be to have animated texture to increase the number of "particles", which is not optimal. Unless the increased amount of texture is performance cheaper than the number of particles, which I doubt.

You can duplicate the particle node and keep it at the same position to increase the number of particles, and free some particle nodes to reduce the number of particles.

**Comment by dmitriy-shmilo** [comment] 2021-12-05 10:47
In Godot 3.4 on Windows changing amount parameter for the first couple of times also causes some graphical artifacts.

**Comment by Calinou** [comment] 2021-12-05 13:43
> In Godot 3.4 on Windows changing amount parameter for the first couple of times also causes some graphical artifacts.

Please open a new issue with a minimal reproduction project attached, as this is an unrelated bug.

**Comment by Samwalton9** [comment] 2022-11-16 11:49
Ugh, yes, I really want this. Is it too late to expect this to make it into 4.0?

**Comment by chrisb123** [comment] 2022-12-15 12:10
I have made proposal for this and have made a fix for it
https://github.com/godotengine/godot-proposals/issues/5939

**Comment by Calinou** [comment] 2023-08-03 23:02
Closing in favor of https://github.com/godotengine/godot-proposals/issues/5939, as feature proposals are now tracked on the Godot proposals repository.

**Closed by Calinou** 2023-08-03 23:02 UTC
Labels: enhancement, topic:rendering, confirmed, topic:particles
