### ISSUE TITLE
2D Select outline not visible when Popup as root scene

### ISSUE THREAD

**Issue by Drarch** [godotengine/godot#74510] opened 2023-03-06 20:47 UTC
### Godot version

4.0 .Net

### System information

Windows 10

### Issue description

No visible outline of selected control node when Window, or any derivative class, is scene root.
![image](https://user-images.githubusercontent.com/1110321/223226120-01790f1c-81c7-47d4-8d5a-84841a7d774b.png)

### Steps to reproduce

1. Create scene with window or popup as root.
2. Add any control
3. Select created control
4. See that ther is no outline of selected control in viewport

### Minimal reproduction project

[NoOultineBug.zip](https://github.com/godotengine/godot/files/10902648/NoOultineBug.zip)

**Comment by ShatReal** [comment] 2023-03-06 21:09
See #20619 ?

**Comment by Drarch** [comment] 2023-03-06 21:12
No. You can move, edit and everything.
You just can't see what is selected.

**Comment by ShatReal** [comment] 2023-03-07 00:55
> When you place node (e.g. Sprite) inside a Viewport, it can't be moved in the editor - you need to manually change position in inspector.
This is because you can't see what is selected. It's implied.

**Comment by Calinou** [comment] 2023-03-21 18:22
- Duplicate of https://github.com/godotengine/godot/issues/20619 (same cause).

**Closed by Calinou** 2023-03-21 18:22 UTC
