### ISSUE TITLE
4.0: Additional layers properties not reflected in editor or in running game

### ISSUE THREAD

**Issue by Racinettee** [godotengine/godot#52619] opened 2021-09-12 22:46 UTC
### Godot version

4.0.dev 5f69218edc

### System information

Kubuntu 21.04 - Lenovo Ideapad S145

### Issue description

When using a tilemap in godot 4 if I add a new layer & paint tiles into the layer:
- The tiles aren't rendered in the running game
- The layer data is saved in the tscn file if i look at it in a text editor, but if I close and re-load the scene in the godot editor, neither the layer properties nore the previously painted tiles are displayed

### Steps to reproduce

Using the minimal reproduction project:

1. Open Node2D.tscn
2. Select the TileMap node
3. Drop down Layers in the property inspector
4. Click add element
5. In the tiles window change to `layer #1`
6. Paint tiles from the second atlas anywhere they'd be visible
7. Run the project
   - The tiles are not rendered
8. Observe in the tscn file that layer_1 is defined
9. Close and re-open Node2D.tscn
10. Drop down layers in the TileMap again, observe that the layer properties are gone and it will also not be an option to switch to from the tiles sub-window
11. Saving at this point, gets rid of the properties from the tscn from the previous time

### Minimal reproduction project

[TileMapLayers.zip](https://github.com/godotengine/godot/files/7150421/TileMapLayers.zip)

**Comment by Calinou** [comment] 2021-09-12 23:18
cc @groud

**Comment by groud** [comment] 2021-09-28 09:11
Closing as very likely fixed by https://github.com/godotengine/godot/pull/53100. 
Please let us know if the issue is still here.

**Closed by groud** 2021-09-28 09:11 UTC
Labels: bug, topic:editor, topic:2d
