### ISSUE TITLE
GDScript Bug: Compiler doesn't send error, but you can't give values to an array with 'for' in this way

### ISSUE THREAD

**Issue by thottee** [godotengine/godot#75058] opened 2023-03-18 10:08 UTC
### Godot version

4.0.stable

### System information

Windows 10, Vulkan, AMD Ryzen 4650G APU

### Issue description

- In GDScript the compiler doesn't send error, but it's not Work:
When you want to give a value to the array elements with 'for' in this way:

```
for element in name_of_array:
	element = value
```

### Steps to reproduce

-

### Minimal reproduction project

```
var asd = [0,0,0]

# Called when the node enters the scene tree for the first time.
func _ready() -> void:
	print(asd)
	for a in asd:
		a = 1
	print(asd)
```

**Comment by dalexeev** [comment] 2023-03-18 10:32
```gdscript
for element in name_of_array:
    element = value
```

Here, `element` is not a reference, it's a local variable and changing it will not change the array, if the value is not passed by reference (object, dictionary, or array). There are no pointers/references at all in GDScript.

Use index if you want to change the array:

```gdscript
for i in name_of_array.size():
    name_of_array[i] = value
```
Please ask for technical support on the community channels first if you're unsure if a behavior is a bug or not.

**Comment by thottee** [comment] 2023-03-18 14:12
I know this solution, and I replaced the other one with this one, but the compiler accepted that solution too, what I tried before this, and that's why I didn't think it was wrong. My logic of code was good, but writing the array didn't work like reading it, and I have not read anywhere that it is not a reference, not even in the godot documentation.

**Comment by dalexeev** [comment] 2023-03-18 14:59
This matches the behavior of other scripting languages (Python, JavaScript, PHP if no `&`).

There is no compiler error/warning, because it is not an error, the loop variable is essentially the same local variable as all the others (including function parameters), it is not read-only.

You can think of

```gdscript
for x in array:
    # loop body
```

as equivalent to

```gdscript
var _internal_index = 0
while _internal_index < array.size():
    var x = array[_internal_index]
    # loop body
    _internal_index += 1
```

**Comment by adamscott** [comment] 2023-03-18 19:58
Would close this issue as this is not a bug, as (very well) explained by @dalexeev.

**Closed** 2023-03-19 10:12 UTC
