### ISSUE TITLE
When a project is exported, any exported Array-typed variables on resources are empty.

### ISSUE THREAD

**Issue by TLowe248** [godotengine/godot#98495] opened 2024-10-24 17:51 UTC
### Tested versions

- Reproducible in 4.4 dev2 and later
- Not reproducible in 4.4 dev1 or earlier

### System information

Godot v4.4.dev3 - Windows 10.0.22631 - Multi-window, 1 monitor - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 4060 Laptop GPU (NVIDIA; 32.0.15.5599) - AMD Ryzen 7 7435HS (16 threads)

### Issue description

When a resource has an exported array, the exported array is properly set in the editor. However, when the project is exported, the array is not set properly, instead being empty.

### Steps to reproduce

Run the project in a 4.4dev3 or 4.4dev2 editor and see that the color of the icon is set correctly due to a resource that contains an exported array, then export the project in that same editor, seeing that the icon is a different color due to the array being empty.

### Minimal reproduction project (MRP)

[test-zone.zip](https://github.com/user-attachments/files/17510870/test-zone.zip)

**Comment by AThousandShips** [comment] 2024-10-24 18:01
Sounds like:
* https://github.com/godotengine/godot/issues/96872

Which was fixed in:
* https://github.com/godotengine/godot/pull/97817

Will confirm with the MRP soon

**Comment by AThousandShips** [comment] 2024-10-24 18:07
In my testing it seems to be solved, it's a bit hard to tell because of the description in the report what is supposed to be different, but this seems fixed, if you can [build from source](https://docs.godotengine.org/en/latest/contributing/development/compiling/compiling_for_windows.html) you can confirm as well, otherwise you can confirm it when dev4 is released

**Comment by matheusmdx** [comment] 2024-10-24 18:14
@AThousandShips I also believe that is a duplicate of #96872. The simplest way to check is print the array in `_ready` function (like here #97782)

**Comment by glenfarrugia031** [comment] 2024-10-27 16:51
I'm experiencing the same issue in Godot 4.4 dev 3 where a resource script containing an array does not retain its data in the exported version of the game.

Steps to Reproduce:
I have a custom resource script that holds an array (an array of inventory slots).
In the editor, I create a resource from this script, set the array size in the editor
It works perfectly in the editor — the array keeps its size/data as expected.
However, when I export the game (Windows Desktop), the array becomes empty. Debugging the exported version shows the array has a size of 0.

Downgrading to Godot 4.3: The issue does not occur in 4.3; the array retains its data in the exported game.

Any help or suggestions would be greatly appreciated!

**Comment by matheusmdx** [comment] 2024-10-27 16:54
@glenfarrugia031 Stay in 4.4 dev 1 until 4.4 dev 4 arrives with the fix.

**Comment by MarkoGrbec** [comment] 2024-11-09 08:14
my issue is fixed:
I think it's related
[#98693](https://github.com/godotengine/godot/issues/98693)

**Comment by glenfarrugia031** [comment] 2024-11-09 08:22
Issue fixed. Thanks!

**Closed** 2024-11-09 08:50 UTC
Labels: bug, topic:core, regression
