### ISSUE TITLE
ViewportTextures do not update and draw

### ISSUE THREAD

**Issue by ismslv** [godotengine/godot#83682] opened 2023-10-20 15:34 UTC
### Godot version

4.1.2 stable

### System information

MacOS Sonoma 14.0

### The problem

![illustration](https://i.ibb.co/yNkyRzw/Screenshot-2023-10-20-at-17-22-12.png)

Similar issue has already been mentioned here by others: https://github.com/godotengine/godot/issues/74353, https://github.com/godotengine/godot/issues/73400, https://github.com/godotengine/godot/issues/74352

The behaviour of ViewportTextures is broken. It does not work at all when used with lights or decals, but works when used a mesh texture.

- Yes, I understand that always updating a texture can be too expensive. But in these cases, it does not update even once. It would be Ideal to be able to update it manually, so that if I've changed text shown on a decal (as in example project), I would update it once, but if I want to have a literal projector that shows an animation, I would just call it each frame.
- Even stranger, as a texture for mesh, it is updating each frame. Sonsidering this, I doubt that the same thing for light or decal would be much more expensive. It's literally the same texture.
- In editor, this works without problem, but breaks in game.
- The worst part is that even manual workarounds barely work or do not work at all. If the Viewport is "always" updating and it is visible on the mesh, and the texture on light does nort update itself, I could understand it as an optimisation measure. But when I forcefully do the following:
```gdscript
var t = ViewportTexture.new()
t.viewport_path = $SubViewport.get_path()
$SpotLight3D.light_projector = t
```
or this:
```gdscript
var i = $SubViewport.get_texture().get_image()
$CSGBox3D/SpotLight3D.light_projector = i
```
it **must** create a new texture with a new image in it, no questions asked. And as viewport itself is being updated (we can see it on the mesh), there is no reason why this new texture would not contain a new image. It seems like the engine does some shady optimisation behind the scene, along the lines of "this already exists, so I will not recreate it from zero and just feed an old one into". Which is an **extremely bad practice** in my opinion.

### Why do we need it at all?

- There are various applications that can be seen in existing games. For example, various puzzles where you have to align a projector to other objects to get a clue. Literal projector with camera feed or images, especially when you can change slides and there is an animation of slides being moved behind the lens. Decals can be changed depending on various veriables during the game process.
- It is just inconsistent in the engine. If there is **this** type of texture, one would expect it to work anywhere, if this "anywhere" supports textures at all. Again, it works for meshes.
- I don't know how does it work on the source side, but if it is too expensive to rewrite a texture, there must be another way to store it. Viewports are very important, because it is the only way to incorporate 3d objects into 2d space, which is extremely common in games, for example: map interface, puzzle close-up, item inspection, inventory etc. And unlike decals, these must be updated as fast as a man view, be interactable and of the high quality.

### Are there workarounds?

- If you have a mesh with the same texture, you can get a texture from it. But it won't update normally either. For this, I found that I must set light's texture to null beforehand.
- Sometimes it works with a certain timer between updating a viewport image and setting a texture, sometimes don't
- If update property of a viewport is set to "never", you can trigger a one-time update by setting it to "once" in the code. This does not work in a stable manner either and also needs a timer.
- `RenderingServer.force_draw()` seems to help some people, but did nothing for me.

### What should be done?

- There needs to be some method to get an actual image of a viewport and set it to any texture, be it mesh, light, decal or 2d element. Update type "Manual" should be added to Viewport settings, or maybe "On change".
- Inconsistensy in editor must be eliminated. If it works in editor, it must work in game. If it works for mesh, it must work for light/decal, or must not work for both, or light/decal must have some other "type" of texture so that viewport texture cannot be asigned to it.

### Steps to reproduce

- Create a SubViewport
- Create a light
- Add a corresponding ViewportTexture as a light_projector
- Try different update methods of a viewport
- It will not be drawn or updated as expected

### Minimal reproduction project

[test_subviewport.zip](https://github.com/godotengine/godot/files/13055473/test_subviewport.zip)

**Comment by AThousandShips** [comment] 2023-10-20 15:34
Can you please try on a supported version? Like 4.1.2?

**Comment by ismslv** [comment] 2023-10-20 15:42
> Can you please try on a supported version? Like 4.1.2?

Sorry, it _was_ 4.1.2

**Comment by ismslv** [comment] 2023-10-20 15:43
@clayjohn Why don't you consider it a "bug"? Only a part of my message talks about enchancements, but the main problem is clearly a bug.

**Comment by clayjohn** [comment] 2023-10-20 15:44
This is a duplicate of https://github.com/godotengine/godot/issues/73400 and https://github.com/godotengine/godot/issues/74352

I understand that this is a frustrating issue as it feels like things should "just work".

Lights Projectors/Decals work totally differently from meshes, so it is not trivial to make this work for them. 

The problem here is not with the Viewport or the ViewportTexture. The Viewport _is_ updating, what isn't updating is the Decal atlas which is where decals and projectors source their textures from. 

What makes resolving this expensive is that we would have to connect the Viewport to the atlas and update the atlas every time that the Viewport updates. While possible, it will be quite complex and very expensive for the end user. So we need to figure out a way to do it efficiently and intuitively. 

Since this is a duplicate, I will be closing it in favour of the original posted issues.

**Closed by clayjohn** 2023-10-20 15:44 UTC
Labels: enhancement, topic:rendering, topic:3d

**Comment by AThousandShips** [comment] 2023-10-20 15:49
To clarify here, we consider something a "bug" when it's something that *should* work and doesn't, something that is supported, and an "enhancement" when it's something that would be nice *if* it worked. Sometimes the lines are blurred between the two, but in this case it's something that isn't currently supported, and will take figuring out and deciding how to do it if at all, so it's considered an enhancement, and not a bug.
