### ISSUE TITLE
Godot 4 crashes when changing from animation tree to animation player

### ISSUE THREAD

**Issue by samangol** [godotengine/godot#72140] opened 2023-01-26 21:12 UTC
### Godot version

v4.0.beta15.official [4fa6edc88]

### System information

windows11,vulkan,gtx 3050 laptop, amd ryzen 6800 cpu

### Issue description

Godot 4 crashes when changing from animation tree to animation player

### Steps to reproduce

click on animation tree to open animation tree windows. then click on the animation player to open animation player window. this causes to crash the engine. i tested this in various projects and a new project.

### Minimal reproduction project

[bug test project.zip](https://github.com/godotengine/godot/files/10513403/bug.test.project.zip)

**Comment by Calinou** [comment] 2023-01-26 22:17
Duplicate of https://github.com/godotengine/godot/issues/72044.

**Closed by Calinou** 2023-01-26 22:17 UTC
