### ISSUE TITLE
[4.0dev] GDScript - Mixed tabs and spaces not allowed in multiline declarations

### ISSUE THREAD

**Issue by nobuyukinyuu** [godotengine/godot#49171] opened 2021-05-28 17:45 UTC
**Godot version:**

364ea7f280a3f074795e542b16b1d0ec76cf6ce2

**OS/device including version:**

Windows 10 (20H2) x64

**Issue description:**

This issue is similar to the issue in #30937, except it might not be considered a regression as the language has had some fundamental changes between 3.x and 4.x.  Multiline declarations such as arrays and dicts do not support the same multiline syntax as in 3.x,  popping up an error about mixed tabs and spaces when writing these declarations in a way to align them to a user's screen.  See example in next section, and the related issue for examples which still produce the issue in the new version of GDScript.

**Steps to reproduce:**
![image](https://user-images.githubusercontent.com/1023003/119928199-b925b380-bf40-11eb-9a80-3717355480ef.png)

**Comment by fcole90** [comment] 2021-05-30 13:15
I think this issue could actually be much mitigated on the text-editor. Let's say that the indentation is set to 4 spaces, pressing tab could actually add 4 spaces. In this way it keeps the comfort of adding such spaces in a quick way, but the error is much less likely to happen, as you would really need to copy/past a `\t`. Most modern editors such as VS Code and PyCharm do exactly that when writing in Python.

**Comment by Calinou** [comment] 2021-05-30 13:31
@fcole90 The above report uses tabs for indentation but spaces for alignemnt. This is a common pattern to format code in programming.

**Comment by fcole90** [comment] 2021-05-30 13:52
@Calinou I know tabs take less effort, and that's why I was looking for a solution that achieves exactly that level of comfort. With my workaround, pressing TAB inserts 4 spaces, so you can just press TAB as you used to do, but 4 spaces will appear, hence keeping the same effect as proper tabs. I too use spaces to complete alignment, especially with dictionaries, lists or functions with many parameters, and this workaround really helped me into that. I have no tabs at all in my Python code but I achieve the same effect. I think, indeed, that Python forbids entirely mixing tabs and spaces in the same file (except for docstrings).

I would recommend revising the GDScript style guide then, as using just spaces in such a way could really improve everything.

Python3 indentation guidelines: https://docs.python.org/3/reference/lexical_analysis.html#indentation

**Comment by name-here** [comment] 2021-05-30 21:37
But many people will want to use tabs, and have actual tab characters show up in their source files and.  Removing the ability to use actual tabs would be annoying.  It's not just about tabs being easier to type or something.

**Comment by fcole90** [comment] 2021-05-30 21:41
Yes, my suggestion here is just a workaround, I never suggested tabs being removed from the language. At most I suggested spaces being the default :wink:

**Comment by nobuyukinyuu** [comment] 2023-03-04 23:52
Just downloaded new 4.0 and see this is still an issue but appears to no longer have an explicit timeline for addressing it.  Is the discussion tag for deciding if this is still considered a regression?  (I'm encountering it again when migrating projects)

**Comment by vnen** [comment] 2023-03-06 12:56
I don't think this needs more discussion. It is a bug since the contents of a multiline expression should not consider indentation and it's a regression because it worked in 3.x.

Regarding the time to fix, there's only so much we can do in a certain time frame, some fixes will have to be postponed. I didn't even notice it was assigned to me until now TBH.

**Comment by MystMagus** [comment] 2023-03-23 17:58
Changing the `if (mixed) {` around line 1100 in modules/gdscript/gdscript_tokenizer.cpp to `if (mixed && !(line_continuation || multiline_mode)) {` seems to be enough to solve it.

**Comment by MystMagus** [comment] 2023-04-20 10:17
Hope that's correct, have not contributed before.

**Closed** 2023-04-20 16:09 UTC
Labels: bug, topic:gdscript, regression
