### ISSUE TITLE
intersect_point only works if Collision Polygon uses build_mode: solids

### ISSUE THREAD

**Issue by wetbadger** [godotengine/godot#58213] opened 2022-02-16 23:25 UTC
### Godot version

3.4.2.stable.official

### System information

Linux Mint 20.2 Uma

### Issue description

The following code should check if the center point of the object is inside of an Area2D, but does not work properly unless build_mode is set to solids.

```
func _physics_process(delta):
	MovementLoop(delta)
	var player_pos = get_global_position()
	
	#this only works with collision polygons with BUILD_MODE == Solids
	var intersections = get_world_2d().direct_space_state.intersect_point(
		player_pos, 32, [self], 0x7FFFFFFF, true, true) 
		
	if len(intersections) == 0: #will be zero even when inside area 2d with build_mode Segments
		get_parent().get_node("RichTextLabel").visible = false
	else:
		#show red text (only shows up if polygon uses build_mode Solids)
		get_parent().get_node("RichTextLabel").visible = true
```

[Video of the issue](https://youtu.be/hDebZ3rGPpc)

See also:
CollisionPolygon2D build_mode https://docs.godotengine.org/en/stable/classes/class_collisionpolygon2d.html#enumerations

intersect_point() https://docs.godotengine.org/en/3.0/classes/class_physics2ddirectspacestate.html

### Steps to reproduce

Make some kind of object that can move around.

Detect point collisions by using get_world_2d().direct_space_state.intersect_point(player_pos, 32, [self], 0x7FFFFFFF, true, true) 

Set an Area2d or body to use a CollisionPolygon2D and set build_mode to segments.

### Minimal reproduction project

[Test.tar.gz](https://github.com/godotengine/godot/files/8084299/Test.tar.gz)

**Comment by Xrayez** [comment] 2022-02-17 00:33
This is expected behavior. Documentation states that:

> BUILD_SEGMENTS = 1 --- Collisions will only include the polygon edges.

Therefore, collisions will only occur with polygon segments (as in segment vs. segment intersection test). I think there's no way around this other than using `BUILD_SOLIDS` mode if you do need to check point intersection.

**Comment by Calinou** [comment] 2022-02-17 00:40
Duplicate of https://github.com/godotengine/godot/issues/58038.

**Closed by Calinou** 2022-02-17 00:40 UTC

**Comment by wetbadger** [comment] 2022-02-17 02:51
Thanks for helping me understand better. I fixed it by changing the polygon to Segments when the object enters, and changing it back to Solids when the object leaves. A raycast detects the leaving part. I'll check out the Geometry solution.
