### ISSUE TITLE
Sampler2D repeat_enable not working in Compatibility renderer

### ISSUE THREAD

**Issue by anaanook** [godotengine/godot#81353] opened 2023-09-05 17:54 UTC
### Godot version

v4.1.1.stable.official

### System information

Godot v4.1.1.stable - Windows 10.0.19045 - Vulkan (Compatibility) - NVIDIA GeForce GTX 1060 (NVIDIA; 31.0.15.3598) - Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 Threads)

### Issue description

Texture repeat mode seems to be ignored in Compatibility mode when rendered inside of a SubViewport. Switching to forward+ or mobile fixes the issue.

Here's my shader from the MRP:
```
shader_type spatial;
uniform sampler2D tex: filter_nearest, repeat_enable;
void fragment() {
    vec2 uv = vec2(UV.x, UV.y);
    ALBEDO  = texture(tex, uv).rgb;
}
```

Expected:
![Godot_v4 1 1-stable_win64_QNrbFYjeej](https://github.com/godotengine/godot/assets/8476492/cfa55c0f-73c5-4430-bfe9-f4ad1913b79c)

Result:
![Godot_v4 1 1-stable_win64_HiKwdsoh1X](https://github.com/godotengine/godot/assets/8476492/040de579-fa6b-48ab-be0b-3081136f52ed)

### Steps to reproduce

- Open the attached project
- Run project

### Minimal reproduction project

[MRP_Bug.zip](https://github.com/godotengine/godot/files/12526698/MRP_Bug.zip)

**Comment by AThousandShips** [comment] 2023-09-06 08:24
Duplicate?
* https://github.com/godotengine/godot/issues/79315

Can you test on [4.2-dev4](https://godotengine.org/article/dev-snapshot-godot-4-2-dev-4/)? Will be in 4.1.2

**Comment by jsjtxietian** [comment] 2023-09-06 08:25
I test it with Godot v4.2.dev (f7c48cf80) - Windows 10.0.19045 - GLES3 (Compatibility) - NVIDIA GeForce RTX 3060 (NVIDIA; 31.0.15.3619) - 11th Gen Intel(R) Core(TM) i7-11700K @ 3.60GHz (16 Threads)

It worked as expected. But why the system info has `Vulkan (Compatibility)`, I thought the Compatibility rendering method uses OpenGL.

**Comment by clayjohn** [comment] 2023-09-06 11:23
> It worked as expected. But why the system info has `Vulkan (Compatibility)`, I thought the Compatibility rendering method uses OpenGL.

Its a bug in the editor code that prints the information. The bug is fixed in the dev releases

**Comment by clayjohn** [comment] 2023-09-06 11:24
Duplicate of https://github.com/godotengine/godot/issues/79315

Fixed by https://github.com/godotengine/godot/pull/79685

**Closed by clayjohn** 2023-09-06 11:24 UTC
Labels: bug, topic:rendering
