### ISSUE TITLE
Directory.open error 31's when passed user:// path with /home being a symlink

### ISSUE THREAD

**Issue by gau-veldt** [godotengine/godot#6047] opened 2016-08-05 11:41 UTC
**Operating system or device - Godot version:**
Athlon FX8320 (8-core) x64 16 GB RAM **linux/X11** Godot v2.1.beta (HEAD at 6d5d23fa8de8673f4a2b312c05588fd4e7195543)

**Issue description** (what happened, and what was expected):

``` GDScript
extends Node

func _ready():
    var loc="user://"
    var dir=Directory.new()
    var err=dir.open(loc)
    if err==OK:
        dir.list_dir_begin()
        var name=dir.get_next()
        while name!="":
            print(name)
            name=dir.get_next()
    else:
            print("Failed to list ",loc," due to: ",err)
```

gives output like:
`Failed to list user:// due to 31`
(ERR_INVALID_PARAMETER)
The output should perhaps be the contents at user://

If _loc_ is changed to something like `OS.get_data_dir()` it starts working and properly outputs a listing at user:// (OS.get_data_dir() yields the absolute path of user://)

This could be rather troublesome in games that want to have multiple saves and provide a custom dialog to select a save game to continue from (since it'll get res:// on the above code rather than the saves) and wishes to peek into the saved games to show character, level, etc. like many console RPGs do.

**Steps to reproduce:**
see above.

**Link to minimal example project** (optional but very welcome):
~~Edit: I ended up making a small project to show the problem is not a project having no name: [Project file link](https://github.com/godotengine/godot/files/403760/test.tar.gz)~~
That project is out of date.  Please see the above code.

**Comment by gau-veldt** [comment] 2016-08-05 11:44
PS: Please see #6016 it sounds like a related problem (Directory accessing something under user:// not working as expected)

**Comment by gau-veldt** [comment] 2016-08-05 11:51
PS: It doesn't matter where I try to specify on user:// (eg: user://some/save/dir) and it still outputs the contents at res:// instead!

**Comment by reduz** [comment] 2016-08-05 12:04
did you set a project name? if not, then user:// will have the same place
as res://

**Comment by gau-veldt** [comment] 2016-08-05 12:25
@reduz will that only affect Directory or would File be using res:// too in that case?  Since in my case File works properly and uses the dotdir off of ~ when specified user:// paths

**Comment by gau-veldt** [comment] 2016-08-05 12:29
PSS: Still does this with 6d5d23fa8de8673f4a2b312c05588fd4e7195543 (which is HEAD as of writing this).

**Comment by gau-veldt** [comment] 2016-08-05 12:50
Here's a small project to show the problem.  Application/name in Project Settings is "DirUserTest"
[test.tar.gz](https://github.com/godotengine/godot/files/403760/test.tar.gz)
Output I get is:
```
** Debug Process Started **
Listing user://
  name=icon.png.flags
  name=icon.png
  name=engine.cfg
  name=.
  name=..
  name=test.gd
  name=test.tscn
** Debug Process Stopped **
```

**Comment by volzhs** [comment] 2016-08-05 13:47
I think ``while dir.open("user://")!=null:`` should be ``while dir.open("user://")==OK:``
``Directory.open`` returns ``Error`` enum.

**Comment by gau-veldt** [comment] 2016-08-06 03:40
```

extends Node

func _ready():
	var loc="user://"
	var dir=Directory.new()
	var err=dir.open(loc)
	if err==OK:
		dir.list_dir_begin()
		print("Listing ",loc)
		var name=dir.get_next()
		while name!="":
			print("  name=",name)
			name=dir.get_next()
	else:
		print("Didn't access ",loc," (",err,")")
```
** Debug Process Started **
Didn't access user:// (31)
** Debug Process Stopped **

31==ERR_INVALID_PARAMETER?!?
Do I need to use OS.shell("ls") to get a directory under user:// ?

**Comment by Sslaxx** [comment] 2016-08-06 09:20
Does get_data_dir return "res://", "user://" or something else?

**Comment by gau-veldt** [comment] 2016-08-06 14:51
@Sslaxx 
dir.open("user://") gives me error 31
dir.open(OS.get_data_dir()) gives me the directory of "~/.godot/app-data/XXX/"  (where XXX is Application/name in the General tab of Project Settings) which is the absolute path of user://

**Comment by akien-mga** [comment] 2016-08-08 09:43
This one and bug #6016 are among the last blocking bugs for 2.1 IMO. I'll have to check but I'm pretty sure they are regressions, and having an erratic `user://` path would be pretty bad for the stable release.
It could be that those bugs are Linux X11 or Unix-specific, so if some of us can test on Windows and Mac OSX to confirm, it would be great.

**Comment by Sslaxx** [comment] 2016-08-08 11:54
Just tested on Windows 10, can confirm this to be a Linux related issue.

**Comment by akien-mga** [comment] 2016-08-08 12:11
Assuming it affects OSX too as I think the bug is in `drivers/unix`.

**Comment by reduz** [comment] 2016-08-08 20:50
I can't seem to reproduce, I wonder if there is anything else involved

**Comment by akien-mga** [comment] 2016-08-08 21:09
Just tested on Mageia 6 x64 with a fresh build from the 2.1 branch, I can't reproduce either.

**Comment by Sslaxx** [comment] 2016-08-08 23:05
Same root issue as #6016 then, maybe?

**Comment by gau-veldt** [comment] 2016-08-09 03:06
System is Athlon FX8320 (8-core) 16-GB RAM
`01:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Cayman LE GL [FirePro V5900]`

Operating system: X11 in Linux Mint 17.2 (etc/sources.list) `#deb cdrom:[Linux Mint 17.2 _Rafaela_ - Release amd64 20150627]/ trusty contrib main non-free`

git log -n 1 on my godot build reports: 6671c6bdc78864bbe1d27c508ec9528f3b683ca2
```
commit 6671c6bdc78864bbe1d27c508ec9528f3b683ca2
Author: Juan Linietsky <reduzio@gmail.com>
Date:   Sat Aug 6 22:11:03 2016 -0300

    Added yield() signal smart autocompletion.
```
Fresh copy of the project I use to get the bug: [test.tar.gz](https://github.com/godotengine/godot/files/408112/test.tar.gz)

Screenshot or it didn't happen (TM): ![error31](https://cloud.githubusercontent.com/assets/1862162/17503039/7dfbaeaa-5da1-11e6-92b5-7807405223d5.png)

same deal as before if create a blank file in the userdir `touch ~/.godot/app-data/DirUserTest/foo` and change line 5 to `var loc=OS.get_data_dir()` this is the output:
```
** Debug Process Started **
Listing /home/gau/.godot/app_userdata/DirUserTest
  name=.
  name=..
  name=foo
** Debug Process Stopped **
```

What am I missing for folks to reproduce this?

**Comment by akien-mga** [comment] 2016-08-09 05:41
Thanks for the screenshot and test project, that makes it very clear that there is a bug :) Sadly I still can't reproduce it on Mageia 6 x64, kernel 4.7.0.

Do you still reproduce the bug with the official 2.1 RC2 binaries and/or if you build the latest 2.1 branch?

**Comment by bojidar-bg** [comment] 2016-08-09 07:11
Can't reproduce on Arch Linux :/
````
Listing user://
  name=.
  name=..
````

**Comment by gau-veldt** [comment] 2016-08-09 07:40
@akien-mga My last post was based on commit 6671c6bdc78864bbe1d27c508ec9528f3b683ca2 which is in master (2.2).

Changing branch to 2.1 and using 569966f3bbe82d768baf3fd26680462df22d29ad to scons-n-test:
I still get `Didn't access user:// (31)` when setting line 05 to `var loc="user://"` and lists the data dir (shows the foo I touched into the directory for testing to know I got that dir) properly when line 05 is `var loc=OS.get_data_dir()`

**Comment by gau-veldt** [comment] 2016-08-09 07:55
The only other thing I can think of is that my /home is a symlink (since you cannot hardlink to another drive).  The main / only has room for the OS (10 GB or so) so copied /home to the other drive with much more room (>100GB) and made a /home symlink.  Might be tripping up Directory.open("user://") since it accesses /home.  But it works with OS.get_data_dir() and File.open("user://") works as it should (or I'd be getting a TON of problems everywhere).

**Comment by akien-mga** [comment] 2016-08-09 08:13
The symlink is likely to be the root of the issue yes. There might be a bug in DirAccess that makes it not resolve symlinks for `user://` I guess.

Unrelated to the issue, but not that instead of making your `/home` a symlink, you could make it a real partition and mount it as `/home`. That's a common practice on Linux.

**Comment by bojidar-bg** [comment] 2016-08-09 08:33
I'm using home as a partition BTW, and I can't reporo with them (as stated above). So it should be simlinks :smile: .

**Comment by gau-veldt** [comment] 2016-08-09 10:00
@akien-mga That drive already has data and no spare room to make a new partition to use for /home.

**Comment by gau-veldt** [comment] 2016-08-09 11:12
I've got the bug so I'll see if I can probe a bit dir_access_unix.cpp and see if I can backtrack the error 31 to what's not as expected.

**Comment by gau-veldt** [comment] 2016-08-09 11:53
Looks like the symlinks are being expanded by `getcwd()` and then the base no longer matches up, failing the `new_dir.begins_with(base)` check:
![error31_src](https://cloud.githubusercontent.com/assets/1862162/17515279/441ff146-5dec-11e6-9123-6b715ca5cb7b.png)

**Comment by Calinou** [comment] 2019-11-16 21:11
Can anyone still reproduce this on 3.2beta1 or later?

**Comment by akien-mga** [comment] 2020-07-26 22:23
No answer, so closing.

Please comment if you can still reproduce the issue, and ensure that an up-to-date minimal reproduction project is attached here.

**Closed by akien-mga** 2020-07-26 22:23 UTC
Labels: bug, platform:linuxbsd, platform:macos, topic:core

**Comment by desarrolladorldpf** [comment] 2022-07-21 22:02
I have this issue in Godot 3.4.4

**Comment by Calinou** [comment] 2022-07-22 00:39
@desarrolladorldpf Please open a new issue with a minimal reproduction project attached.
