### ISSUE TITLE
Setter called when value assigned to sub-member

### ISSUE THREAD

**Issue by AnJ95** [godotengine/godot#38221] opened 2020-04-26 11:02 UTC
**Godot version:**
v3.2.stable.official

**OS/device including version:**
macOS Mojave v10.14.6

**Issue description:**
Assigning a value to a member variable to a Node, which is itself a member variable with setter calls the setter.
This only happens when setting the variable through the reference that has the setter (see comments in reproduction steps below).

This behavior is not explained in the [GDScript basics page](https://docs.godotengine.org/en/3.2/getting_started/scripting/gdscript/gdscript_basics.html?):
> Whenever the value of variable is modified by an external source (i.e. not from local usage in the class), the setter function (setterfunc above) will be called

**Steps to reproduce:**
Create any Node and attach a script with a member and an associated setter function
```gdscript
extends Node2D

var member setget _set_member

func _set_member(v):
    print("setter called")
    member = v
```

Add any child Node to the Node, and attach the following script:
```gdscript
extends Node2D

func _ready():
    # calls setter as intended
    get_parent().member = Vector2()
    
    # calls setter
    get_parent().member.x = 1
    
    # Does not call setter
    var member = get_parent().member
    member.x = 1
```

The fact that `get_parent().member.x = 1` calls the setter of `member` is highly irritating, since the behavior is unexpected and also inconsistent with `var member = get_parent().member; member.x = 1` not calling the setter.

**Minimal reproduction project:**
[bugreport.zip](https://github.com/godotengine/godot/files/4535164/bugreport.zip)

**Comment by Calinou** [comment] 2020-04-26 11:23
cc @vnen

**Comment by samdze** [comment] 2020-04-26 12:33
That's expected behaviour, when you do:

`var member = get_parent().member`

you're making a copy of the `member` Vector2, you're not getting a reference, so no setter should be called afterwards.

**Comment by AnJ95** [comment] 2020-04-26 12:48
> That's expected behaviour, when you do:
> 
> `var member = get_parent().member`
> 
> you're making a copy of the `member` Vector2, you're not getting a reference, so no setter should be called afterwards.

I get that no setter is supposed to be called in that situation.
My issue is the fact that `get_parent().member.x = 1` _does_ call the setter.

By the way, the example in the above behaves exactly the same when replacing the copy-on-assign Vector2 by a reference-on-assign variable. In my case it was a script extending `Node` created with `new`. I noticed that calling `get_slot_at(x,y).block.bitmask = calc_bitmask_at(x,y)` called the setter of `block` in `Slot`

**Comment by ThakeeNathees** [comment] 2020-04-27 10:25
`get_parent().member` calling setter for member
`get_parent().member.x` calling setter for x never calls setter for member

1. what's the expected behavior for this ?
2. if any one have experience with C#, how it handles the situation?

**Comment by matzebond** [comment] 2020-04-30 15:35
just to clarify I think the problem/confusion is that
```
get_parent().member.x = 1
```
calls the setter of member. I don't know if there is an alternative but it certainly is a bit counter intuitive and should be represented in the docs.

**Comment by vnen** [comment] 2020-05-14 14:40
This is the same issue as #28720 and #31245.

The main problem (as @samdze summed up) is that when you do: `$Sprite.position.x = 10` it needs to set the `position` back into `$Sprite` because otherwise it only changed a copy of the value (since Vector2 is a primitive and only passed by copy). By setting the `position` with this copy it actually does what's expected.

This is valid both for native engine setters and user-defined script setters.

This needs to be fixed in the compiler but it's not trivial to do. Hopefully I'll be able to fix this when I get to rewrite the compiler.

I'm closing this as duplicate, since the bug is already tracked in the aforementioned issues.

**Closed by vnen** 2020-05-14 14:40 UTC
Labels: bug, discussion, topic:gdscript
