### ISSUE TITLE
Adding Autoload/singleton in Runtime from script

### ISSUE THREAD

**Issue by ripperdave** [godotengine/godot#52055] opened 2021-08-24 09:15 UTC
### Godot version

3.3.3

### System information

Windows 10

### Issue description

I am working on a game collection launcher. I have 10 existing games with Autoloaded singletons. I plan to add more in future.
I import existing games through .pck (ProjectSettings.load_resource_pack(...)), but imported games need their own singletons.

1, How can I add autoload singletons after the game (collection launcher) started?
Adding nodes to root won't make the node visible in global scope variables. (cannot access the singleton by its name)
2, Is there any way to add global scope variables?

No details about this in documents:
(https://docs.godotengine.org/en/stable/getting_started/workflow/export/exporting_pcks.html?#summary)
https://docs.godotengine.org/en/stable/getting_started/step_by_step/singletons_autoload.html

Thanks.

### Steps to reproduce

Try to add autoload singleton after the game is started.

**Comment by Calinou** [comment] 2021-08-24 09:19
Duplicate of https://github.com/godotengine/godot/issues/48563.

Please don't ask support questions here, as this issue tracker is meant to be used for bug reports only. Use one of the other [community channels](https://godotengine.org/community) instead.

**Closed by Calinou** 2021-08-24 09:19 UTC
