### ISSUE TITLE
Key release event not sent if the key is released too quickly

### ISSUE THREAD

**Issue by unfa** [godotengine/godot#4137] opened 2016-03-24 16:11 UTC
**Issue description** (what happened, and what was expected):
If you press and release a key quickly enough, Godot will never send the release event, making the game believe that you're still pressing the key, even though that's not true. The action needed to trigger this is not too common to perform in any game, but a nervous player can trigger this experiencing a bad, annoying glitch. They keys needs to be pressed and released again, so the game finally sends a release event for that key.

Video proof:
https://www.youtube.com/watch?v=5v_IRHfDg90

**Steps to reproduce:**
1. Run the Godot's demo "Platformer" game
2. Tap the right arrow key to get the character going right, however tap it as quickly and swiftly as you can, just bounce off that key, putting minimal weight on it, putting all your effort into speed, not force. More like you'd tap on a djembe drum membrane than type on a keyboard.
3. Watch the character lock on walking right, like the key is still being held.

**Comment by neikeq** [comment] 2016-03-24 16:23
Cannot reproduce the issue on master branch, Ubuntu 15.10 64bits.

**Comment by bojidar-bg** [comment] 2016-03-25 15:27
@unfa Are you on linux? Which godot version are you using?

**Comment by unfa** [comment] 2016-03-25 15:31
@bojidar-bg Yes. I'm running Linux, Godot 2.0.1 stable.

**Comment by reduz** [comment] 2016-06-21 01:59
Can't reproduce, what desktop environment are you using?

**Comment by bojidar-bg** [comment] 2016-06-21 12:30
BTW, I've seen this issue rarely in other games a while ago, but not recently. Might be related to the hardware, who knows...

**Comment by DualMatrix** [comment] 2018-09-16 14:56
Could not reproduce in godot 3.1alpha on Windows 10

**Comment by Chaosus** [comment] 2018-09-16 15:04
Then this should be closed, thanks.

**Comment by akien-mga** [comment] 2018-09-17 09:18
Noone could ever reproduce it, so closing.

**Closed by akien-mga** 2018-09-17 09:18 UTC
Labels: bug, topic:core
