### ISSUE TITLE
Editor crash on clearing Tileset's cell collision shape in inspector

### ISSUE THREAD

**Issue by StraToN** [godotengine/godot#24253] opened 2018-12-10 10:32 UTC
**Godot version:**
master

**OS/device including version:**
Mageia 6

**Issue description:**
Editor crash

```
[1] /lib64/libc.so.6(+0x338a0) [0x7f41630ec8a0] (??:0)
[2] Set<Object*, Comparator<Object*>, DefaultAllocator>::_find(Object* const&) const (/home/julian/Programming/godot/godot/master/./core/set.h:228)
[3] Set<Object*, Comparator<Object*>, DefaultAllocator>::find(Object* const&) (/home/julian/Programming/godot/godot/master/./core/set.h:522)
[4] Set<Object*, Comparator<Object*>, DefaultAllocator>::erase(Object* const&) (/home/julian/Programming/godot/godot/master/./core/set.h:558)
[5] Object::remove_change_receptor(Object*) (/home/julian/Programming/godot/godot/master/core/object.cpp:973)
[6] EditorInspector::edit(Object*) (/home/julian/Programming/godot/godot/master/editor/editor_inspector.cpp:1768)
[7] EditorInspector::_notification(int) (/home/julian/Programming/godot/godot/master/editor/editor_inspector.cpp:2118)
[8] EditorInspector::_notificationv(int, bool) (/home/julian/Programming/godot/godot/master/editor/editor_inspector.h:249 (discriminator 14))
[9] Object::notification(int, bool) (/home/julian/Programming/godot/godot/master/core/object.cpp:957)
[10] Node::_propagate_exit_tree() (/home/julian/Programming/godot/godot/master/scene/main/node.cpp:293 (discriminator 10))
[11] Node::_propagate_exit_tree() (/home/julian/Programming/godot/godot/master/scene/main/node.cpp:279 (discriminator 2))
[12] Node::_set_tree(SceneTree*) (/home/julian/Programming/godot/godot/master/scene/main/node.cpp:2508)
[13] Node::remove_child(Node*) (/home/julian/Programming/godot/godot/master/scene/main/node.cpp:1236 (discriminator 2))
[14] Node::_notification(int) (/home/julian/Programming/godot/godot/master/scene/main/node.cpp:158)
[15] Node::_notificationv(int, bool) (/home/julian/Programming/godot/godot/master/./scene/main/node.h:46 (discriminator 14))
[16] CanvasItem::_notificationv(int, bool) (/home/julian/Programming/godot/godot/master/./scene/2d/canvas_item.h:166)
[17] Control::_notificationv(int, bool) (/home/julian/Programming/godot/godot/master/./scene/gui/control.h:51)
[18] Container::_notificationv(int, bool) (/home/julian/Programming/godot/godot/master/./scene/gui/container.h:38)
[19] BoxContainer::_notificationv(int, bool) (/home/julian/Programming/godot/godot/master/./scene/gui/box_container.h:38)
[20] VBoxContainer::_notificationv(int, bool) (/home/julian/Programming/godot/godot/master/./scene/gui/box_container.h:81)
[21] Object::notification(int, bool) (/home/julian/Programming/godot/godot/master/core/object.cpp:957)
[22] Object::_predelete() (/home/julian/Programming/godot/godot/master/core/object.cpp:387)
[23] predelete_handler(Object*) (/home/julian/Programming/godot/godot/master/core/object.cpp:2000)
[24] void memdelete<VBoxContainer>(VBoxContainer*) (/home/julian/Programming/godot/godot/master/./core/os/memory.h:117)
[25] EditorPropertyResource::update_property() (/home/julian/Programming/godot/godot/master/editor/editor_properties.cpp:2458)
[26] EditorPropertyResource::_menu_option(int) (/home/julian/Programming/godot/godot/master/editor/editor_properties.cpp:2025 (discriminator 24))
[27] MethodBind1<int>::call(Object*, Variant const**, int, Variant::CallError&) (/home/julian/Programming/godot/godot/master/./core/method_bind.gen.inc:729 (discriminator 12))
[28] Object::call(StringName const&, Variant const**, int, Variant::CallError&) (/home/julian/Programming/godot/godot/master/core/object.cpp:945 (discriminator 1))
[29] Object::emit_signal(StringName const&, Variant const**, int) (/home/julian/Programming/godot/godot/master/core/object.cpp:1231 (discriminator 1))
[30] Object::emit_signal(StringName const&, Variant const&, Variant const&, Variant const&, Variant const&, Variant const&) (/home/julian/Programming/godot/godot/master/core/object.cpp:1288)
[31] PopupMenu::activate_item(int) (/home/julian/Programming/godot/godot/master/scene/gui/popup_menu.cpp:1102 (discriminator 4))
[32] PopupMenu::_gui_input(Ref<InputEvent> const&) (/home/julian/Programming/godot/godot/master/scene/gui/popup_menu.cpp:330)
[33] MethodBind1<Ref<InputEvent> const&>::call(Object*, Variant const**, int, Variant::CallError&) (/home/julian/Programming/godot/godot/master/./core/method_bind.gen.inc:729 (discriminator 12))
[34] Object::call_multilevel(StringName const&, Variant const**, int) (/home/julian/Programming/godot/godot/master/core/object.cpp:779 (discriminator 1))
[35] Object::call_multilevel(StringName const&, Variant const&, Variant const&, Variant const&, Variant const&, Variant const&) (/home/julian/Programming/godot/godot/master/core/object.cpp:886)
[36] Viewport::_gui_call_input(Control*, Ref<InputEvent> const&) (/home/julian/Programming/godot/godot/master/scene/main/viewport.cpp:1514 (discriminator 2))
[37] Viewport::_gui_input_event(Ref<InputEvent>) (/home/julian/Programming/godot/godot/master/scene/main/viewport.cpp:1854 (discriminator 3))
[38] Viewport::input(Ref<InputEvent> const&) (/home/julian/Programming/godot/godot/master/scene/main/viewport.cpp:2603 (discriminator 2))
[39] Viewport::_vp_input(Ref<InputEvent> const&) (/home/julian/Programming/godot/godot/master/scene/main/viewport.cpp:1291)
[40] MethodBind1<Ref<InputEvent> const&>::call(Object*, Variant const**, int, Variant::CallError&) (/home/julian/Programming/godot/godot/master/./core/method_bind.gen.inc:729 (discriminator 12))
[41] Object::call(StringName const&, Variant const**, int, Variant::CallError&) (/home/julian/Programming/godot/godot/master/core/object.cpp:945 (discriminator 1))
[42] Object::call(StringName const&, Variant const&, Variant const&, Variant const&, Variant const&, Variant const&) (/home/julian/Programming/godot/godot/master/core/object.cpp:870)
[43] SceneTree::call_group_flags(unsigned int, StringName const&, StringName const&, Variant const&, Variant const&, Variant const&, Variant const&, Variant const&) (/home/julian/Programming/godot/godot/master/scene/main/scene_tree.cpp:262)
[44] SceneTree::input_event(Ref<InputEvent> const&) (/home/julian/Programming/godot/godot/master/scene/main/scene_tree.cpp:418 (discriminator 6))
[45] InputDefault::_parse_input_event_impl(Ref<InputEvent> const&, bool) (/home/julian/Programming/godot/godot/master/main/input_default.cpp:414)
[46] InputDefault::parse_input_event(Ref<InputEvent> const&) (/home/julian/Programming/godot/godot/master/main/input_default.cpp:260)
[47] OS_X11::process_xevents() (/home/julian/Programming/godot/godot/master/platform/x11/os_x11.cpp:1997 (discriminator 3))
[48] OS_X11::run() (/home/julian/Programming/godot/godot/master/platform/x11/os_x11.cpp:2819)
[49] /home/julian/Programming/godot/godot/master/bin/godot.x11.tools.64(main+0xb9) [0x113d84f] (/home/julian/Programming/godot/godot/master/platform/x11/godot_x11.cpp:56)
[50] /lib64/libc.so.6(__libc_start_main+0xf0) [0x7f41630d9600] (??:0)
[51] /home/julian/Programming/godot/godot/master/bin/godot.x11.tools.64(_start+0x29) [0x113d6c9] (/home/iurt/rpmbuild/BUILD/glibc-2.22/csu/../sysdeps/x86_64/start.S:121)
-- END OF BACKTRACE --
```

**Steps to reproduce:**
Download: [Falldown.zip](https://github.com/godotengine/godot/files/2662720/Falldown.zip)
Load the project
Open Map.tscn
Select the Tilemap node
Click on the tileset in the inspector and expand element 0 in it
Search for the Shape entry (should be RectangleShape2D) and clear it using the dropdown (see capture)
![image](https://user-images.githubusercontent.com/1289207/49726926-658b5680-fc6f-11e8-89a1-340efd267d8e.png)

<crash>

**Minimal reproduction project:**
[Falldown.zip](https://github.com/godotengine/godot/files/2662720/Falldown.zip)

**Comment by akien-mga** [comment] 2019-01-25 23:50
Couldn't reproduce in the current master branch (6e60070), so I assume it might have been fixed in the meantime. Please reopen if you can still reproduce it.

**Closed by akien-mga** 2019-01-25 23:50 UTC
Labels: bug, topic:core, topic:editor
