### ISSUE TITLE
PoolArray types not passed by reference in case of function call?

### ISSUE THREAD

**Issue by ghost** [godotengine/godot#17526] opened 2018-03-15 11:14 UTC
**Godot version:**
Godot 3.0.2 stable

**OS/device including version:**
Windows 8.1, 64 Bit

**Issue description:**
The GDScript documentation states that only base types (int, float, string and the vector types) are passed by value. All other types should be passed by reference. For the built-in Array type this works as expected. But when it comes to Pool#Array types this does not work anymore. The '#' in Pool#Array could be replaced with Int, Byte, Vector2, Vector3, Color, String and Real. In all these cases the resulting Pool#Array is passed by value. 
If this is the way it's meant to be then there should be more information within the documentation. 

**Steps to reproduce:**
Section A:
1.) Create a new Godot 3.0.2 Project
2.) Add a node of type 'Node' to the scene
3.) Create the script given below in Section B
4.) Attach the script to the 'Node' node and run the project

Section B:
```
    extends Node

    func _ready():
        var test_array = [1, 2, 3]
	var pool_array = PoolIntArray()
	pool_array.push_back(1);
	pool_array.push_back(2);
	pool_array.push_back(3);
	
	print("[test_array] Before function call: " + str(test_array[0]) + " | " + str(test_array[1]) + " | " + str(test_array[2]))
	test_function(test_array)
	print("[test_array] After  function call: " + str(test_array[0]) + " | " + str(test_array[1]) + " | " + str(test_array[2]))
	
	print("[pool_array] Before function call: " + str(pool_array[0]) + " | " + str(pool_array[1]) + " | " + str(pool_array[2]))
	test_function(pool_array)
	print("[pool_array] After  function call: " + str(pool_array[0]) + " | " + str(pool_array[1]) + " | " + str(pool_array[2]))

    func test_function(arr):
        arr[0] = 4
	arr[1] = 5
	arr[2] = 6
```
Section C:
With the above script I get the following output:
```
[test_array] Before function call: 1 | 2 | 3
[test_array] After  function call: 4 | 5 | 6
[pool_array] Before function call: 1 | 2 | 3
[pool_array] After  function call: 1 | 2 | 3

```

**Minimal reproduction project:**

**Comment by bojidar-bg** [comment] 2018-03-15 11:23
Yes, currently PoolXArrays are passed by value, not by reference (actually, they are still by reference, but with copy-on-write functionality).
It is a feature, which, as said by reduz, "works this way to avoid having difficult to trace bugs when sending and retrieving data from servers".

Related/Duplicate: #15265

**Comment by Zylann** [comment] 2018-03-15 17:55
Is that behavior specific to GDScript? In the example above I see no reason why COW would happen, since there is only one thread writing to the array and nothing else locks it.

**Comment by seichter** [comment] 2018-03-25 21:05
Like to second that what @Zylann said. I am trying to get an image via GDNative into a texture. I can make it work but at the cost of leaking the old PoolByteArray at each frame (described [here - Godot QA](https://godotengine.org/qa/26256/changing-pixels-in-a-texture-or-image-via-gdnative) which is obviously a nogo.

**Comment by akien-mga** [comment] 2020-01-18 14:20
Duplicate of #15265.

**Closed by akien-mga** 2020-01-18 14:20 UTC
Labels: discussion, topic:core
