### ISSUE TITLE
Animation error message shows wrong track name

### ISSUE THREAD

**Issue by tofuhead** [godotengine/godot#19363] opened 2018-06-04 19:48 UTC
**Godot version:**
godot git master compiled today

**OS/device including version:**
Kubuntu 17.10

**Issue description:**
I am updating some older code to current Godot version and some things have changed. so animation wasn't correct on my character, and got this on debug error window:

0:00:12:0147 - Failed setting key at time 0.171352 in Animation 'jarru.R' at Node '/root/Node/Player/anim', Track 'Sprite:frame'. Check if property exists or the type of key is right for the property

but in fact, the error was on other track I had there: "Sprite:rotation_deg", which nowadays should be called "Sprite:rotation_degrees".. so after I fixed that, errors went away.

.b

**Comment by akien-mga** [comment] 2018-06-05 08:00
Duplicate of #17718.

**Closed by akien-mga** 2018-06-05 08:00 UTC
Labels: bug, topic:core
