### ISSUE TITLE
export(MyEnum) var foo = MyEnum.name will set the variable to Null

### ISSUE THREAD

**Issue by char0xff** [godotengine/godot#21135] opened 2018-08-18 06:30 UTC
**Godot version:**
v3.0.5 stable on GNU/Linux

**Issue description:**
Serious. The value of an exported variable is set to **null** when its default value is retrieved from an **enum**.
This is reflected in the inspector, which is in fact showing the first enum value instead of the assigned default.

**Steps to reproduce:**
Open the example project.
Select _Node2D_.
Load _"Script.gd"_
Open a scene and close it to refresh the inspector (another bug, will open another issue).
Notice that _Foo_ is _First_ and Bar is _Third_.
Have a look at the script and see that _foo_ was actually set to _MyEnum.third_, but it's ignored by Godot, like it's not able to parse the enum and so it leaves the value to _null_.
Run the scene.
See that the output is printing that _Foo_ is _Null_.

**Minimal reproduction project:**
[export_var_enum_bug.zip](https://github.com/godotengine/godot/files/2299192/export_var_enum_bug.zip)

**Comment by Noshyaar** [comment] 2018-08-18 07:01
Can confirm this happens in 3.0.6 and is fixed in latest master.

**Comment by akien-mga** [comment] 2018-08-19 08:29
Closing as duplicate of #15585 then. I've tagged #19635 for cherry-picking, if deemed safe enough it might make it in the 3.0 branch.

**Closed by akien-mga** 2018-08-19 08:29 UTC
Labels: bug, topic:gdscript
