### ISSUE TITLE
area_entered and area_exited emitted multiple times while still overlapping

### ISSUE THREAD

**Issue by shafy** [godotengine/godot#35595] opened 2020-01-26 16:56 UTC
**Godot version:**
3.2rc1

**OS/device including version:**
MacOS 10.14.3 (Mojave) build running on Oculus Quest.

**Issue description:**
`area_entered` and `area_exited` signals are emitted all the time when one area is moved even though areas are still overlapping (for 3D). This only happens when the CollisionShapes are sufficiently small.

**Steps to reproduce:**
- Create two Spatial Areas with small CollisionsShapes (e.g. Extents (0.015, 0.009, 0.015))
- Overlap them and move one area slightly. Check for `area_entered` which is emitted even though the areas never stop overlapping.
- Try the same with bigger CollisionShapes and it works as expected

**Minimum reproduction project**:
Not sure how much it helps since you need a Quest to run it: https://github.com/shafy/blocks-kosmos-school/

Grab one of the blocks on the table and hold one of the small six Areas into another block's to see what I mean.

**Comment by Calinou** [comment] 2020-01-26 18:33
Please upload a minimal reproduction project to make this easier to troubleshoot. Thanks in advance :slightly_smiling_face:

**Comment by shafy** [comment] 2020-01-26 18:49
Thanks @Calinou, I updated the comment. Not sure how much it will help since it's a Quest app :-)

**Comment by creikey** [comment] 2020-01-27 03:16
When collisionshapes are especially small the physics engine ( bullet ) will start to have problems unless you adjust the `margin` property of the collision shape.

**Comment by shafy** [comment] 2020-02-24 15:16
You mean I need to increase the margin?

**Comment by creikey** [comment] 2020-02-25 20:14
@shafy yes

**Comment by shafy** [comment] 2020-03-10 16:41
Ok, but this is then the same as just increasing the volume of the collision shape. So it doesn't really solve the problem then. But I guess there's nothing we can do about it if it's beause of Bullet?

**Comment by pouleyKetchoupp** [comment] 2021-01-15 22:51
Does it work as expected if you switch the physics engine to Godot Physics?
`Project Settings > Physics > 3D > Physics Engine > Godot Physics`

**Comment by shafy** [comment] 2021-01-16 12:34
Thanks @pouleyKetchoupp. I'm currently not working on that project anymore and so won't be able to test this any time soon. But I'll let you know once I can. Or maybe someone else who has a similar problem can check it?

**Comment by pouleyKetchoupp** [comment] 2021-01-16 18:38
Alright. If anyone can reproduce a similar issue, please test with Godot Physics and share a minimal project to help investigate.

**Comment by SoapSpangledGames** [comment] 2021-09-28 12:40
I don't have a minimal project, but my larger project exhibited similar behavior with Godot 3.2 and 3.3.2 official builds. In my case, area_exited fired twice for each object. My issue involves collisions with a small box [extents (0.507,0.532,0.612), margin 0.04] and a cylinder (radius 1, height 2, margin 0.04). This happens under Godot Physics and Bullet physics.

After struggling with this for days, I ended up making the cylinder longer (height 5.07). This fixed the problem for me under both physics engines.

**Comment by pouleyKetchoupp** [comment] 2021-09-28 16:29
@SoapSpangledGames Thanks for info! Would you be able to check if your issue still occurs in [3.4 beta](https://godotengine.org/article/dev-snapshot-godot-3-4-beta-5) by any chance?

**Comment by SoapSpangledGames** [comment] 2021-09-29 01:38
I am unable to reproduce my problem in 3.4 beta 5. I was mistaken about the signal I was using. I was using body_exited, not area_exited. But the issue was correct, and I'm unable to reproduce it now. It seems to be fixed in 3.5 beta 5.

**Comment by pouleyKetchoupp** [comment] 2021-09-29 02:38
Closing for now since it seems fixed in 3.4.

@shafy Feel free to re-open if you can still reproduce the issue when you get to test this project again.

**Closed by pouleyKetchoupp** 2021-09-29 02:38 UTC
Labels: bug, topic:physics, topic:3d

**Comment by jeudy-ua** [comment] 2022-03-15 22:41
I'm still experiencing this bug in Godot Godot_v3.4.2-stable_x11 (Linux).

https://www.youtube.com/watch?v=DkIIWZ8fbmk

As you can see, when the ship enters the area of the electric barrier, a "Deactivate" button appears on the left. This is triggered by area_entered. 

On the other hand, area_exit triggers the button disappearance. If I move the ship, even if all its area is contained in the larger area, the event is still triggered.

**Comment by Calinou** [comment] 2022-03-16 00:06
@jeudy-ua Please open a new issue with a minimal reproduction project attached.
