### ISSUE TITLE
AnimationPlayer calls a method twice from a Call Method Track when playing the animation backwards

### ISSUE THREAD

**Issue by ysylya** [godotengine/godot#86648] opened 2023-12-30 18:10 UTC
### Tested versions

The bug exists in:
4.2.1.stable
4.3.dev1

Does not exist in:
4.1.3

### System information

Godot v4.2.1.stable - Linux

### Issue description

When an animation is played backwards, and there is a Call Method Track in it with a method, that method is called twice. This doesn't happen when the animation is played forwards.

### Steps to reproduce

Create a Node3D, add an AnimationPlayer as a child. Attach a script to the Node3D, implement the _ready() method and create an other method called "foo()". The script should look like this:

```
extends Node3D

@onready var animation_player: AnimationPlayer = $AnimationPlayer

func _ready() -> void:
    animation_player.play("bar")

func foo() -> void:
    print("foo")
```

Create a new animation called "bar", add a new Call Method Track, and in it call the foo() method.
If you run the scene, observe that the foo method is called once.
Now change the _ready method to this:

```
func _ready() -> void:
    animation_player.play("bar", -1, -1.0, true)
```

Run the scene again, and observe that foo is being called twice.

### Minimal reproduction project (MRP)

[AnimationPlayerMethodCallBug.zip](https://github.com/godotengine/godot/files/13798887/AnimationPlayerMethodCallBug.zip)

**Comment by TokageItLab** [comment] 2023-12-31 00:23
Dupe of https://github.com/godotengine/godot/issues/86147

**Closed by TokageItLab** 2023-12-31 00:23 UTC
Labels: bug, needs testing, topic:animation
