### ISSUE TITLE
Wrong position in SubViewport (Object Picking) for scaled viewport

### ISSUE THREAD

**Issue by MrJustreborn** [godotengine/godot#64893] opened 2022-08-25 17:24 UTC
### Godot version

v4.0.alpha.custom_build [cfcdd576d]

### System information

Manjaro

### Issue description

If the subviewport is scaled, the input picking does not reflect the position on the screen for the object

### Steps to reproduce

```
var factor = 1.0;
func _on_button_pressed():
	if factor < 1.0:
		#get_tree().root.set_content_scale_factor(1.0);
		factor = 1.0
	else:
		#get_tree().root.set_content_scale_factor(2);
		factor = .75;
	
	$SubViewportContainer/SubViewport.size = get_viewport().size * factor;
	
	$Button.text = "Change scaling - cur: " + str(factor)
```

- to scale the subviewport for a 3D-scene
- on a StaticBody listen for the _on_static_body_3d_input_event
- if the subviewport has a sacling-factor of 1 everything is fine
- if the subviewport has a scaling-factor of 0.75 the mouse-cursor triggers the input_event NOT on the object but with an offset to the top left

### Minimal reproduction project

[testProject.zip](https://github.com/godotengine/godot/files/9426962/testProject.zip)

**Comment by Calinou** [comment] 2022-08-25 17:44
Duplicate of https://github.com/godotengine/godot/issues/34805 (same cause).

**Closed by Calinou** 2022-08-25 17:44 UTC
