### ISSUE TITLE
Godot 4 UV mapping kinda weird

### ISSUE THREAD

**Issue by Intervel** [godotengine/godot#78041] opened 2023-06-09 10:28 UTC
### Godot version

4.1 beta 1

### System information

Windows 11,  Rtx 3090

### Issue description

![Blender 6_9_2023 5_26_01 PM](https://github.com/godotengine/godot/assets/86478025/b2257fb1-dfa8-4608-8f66-7cabded9255c)
![Blender 6_9_2023 5_26_13 PM](https://github.com/godotengine/godot/assets/86478025/57cf9b35-f302-4c62-9c84-79e018ae1796)
![plane_45 tscn - CRPG - Godot Engine 6_9_2023 5_28_35 PM](https://github.com/godotengine/godot/assets/86478025/dea8a624-8b80-4e9f-bb9d-a7a8b8effa6f)
![lobby tscn - CRPG - Godot Engine 6_9_2023 5_26_26 PM](https://github.com/godotengine/godot/assets/86478025/fb585c45-3cda-41ec-9b8d-b5c40ac69afc)

what happens here? why does Godot behave differently?

### Steps to reproduce

texture is copyright

### Minimal reproduction project

texture is copyright

**Comment by AThousandShips** [comment] 2023-06-09 10:30
What are your import settings?

**Comment by Intervel** [comment] 2023-06-09 10:32
![1](https://github.com/godotengine/godot/assets/86478025/3ac20f89-0315-4549-a6cf-c383b81b6528)
![2](https://github.com/godotengine/godot/assets/86478025/14a62780-e6a0-44e9-b8d8-23767a7ad058)

**Comment by AThousandShips** [comment] 2023-06-09 10:33
* Possible duplicate of #76377

**Comment by Intervel** [comment] 2023-06-09 10:40
thanks! fixed the issues! what does generate lod supposed to do?

**Comment by AThousandShips** [comment] 2023-06-09 10:45
It generates lower detail versions of the mesh that can be used when far away, this is possibly a bug in the import though, but hard to tell without more details, lets keep it open for now and see if we can identify a bug in the import here

**Comment by Calinou** [comment] 2023-06-09 13:38
- Duplicate of https://github.com/godotengine/godot/issues/71141 (same cause).

**Closed by Calinou** 2023-06-09 13:38 UTC
