### ISSUE TITLE
Multiple "orphan StringName" with class names on game shutdown

### ISSUE THREAD

**Issue by AlexKhayrullin** [godotengine/godot#73554] opened 2023-02-18 13:38 UTC
### Godot version

4.0-rc2

### System information

Ubuntu

### Issue description

On exiting a game that uses a GDExtension module, it appears that at least every C++ class involved produces an "Oprhan StringName" on exit, including the classes from the GDExtension module.

### Steps to reproduce

- Compile the C++ in the reproduction project
- Run the project in CLI (by CDing into the project folder and running the Godot binary)
- Since the project itself contains two nodes that do nothing, a gray window will appear. Close it.
- Examine the CLI output.

On Ubuntu running RC2, the output contains this: 
```
Orphan StringName: SceneMultiplayer
Orphan StringName: FileAccess
Orphan StringName: Node2D
Orphan StringName: MyGameObject
Orphan StringName: AbstractGameNode2D
```
`MyGameObject` extends `AbstractGameNode2D` which itself extends `Node2D`, the project contains a `Node2D` which has a `MyGameObject` child. 
`FileAccess` and `SceneMultiplayer` have not been explicitly called by the project.

### Minimal reproduction project

Edit the `SConstruct` file so that `env = SConscript("../../CPP/godot-cpp/SConstruct")` points to the `SConstruct` file from https://github.com/godotengine/godot-cpp. Make sure the revisions match.

Compile with the C++ code using the command `scons target=template_debug`

Project: [cppexample.zip](https://github.com/godotengine/godot/files/10774353/cppexample.zip)

**Comment by AlexKhayrullin** [comment] 2023-02-21 22:08
It is worse with 4.0-rc3 and C++ bindings updated to `master`, as orphaned StringNames now also seem to include key codes and other constants, placing the orphaned StringName count at above 600.

**Comment by Gnumaru** [comment] 2023-04-11 19:08
I got the same problem by just opening and closing the editor on a project I'm working on, which does not use any gdextensions.

![image](https://user-images.githubusercontent.com/5783414/231264253-47a99f92-7511-4014-a24a-cd2a4c59e0e4.png)

The main issue for me is not the seemingly innocuous error messages in a moment where errors or warnings usually are not so important (that is, when closing the application), but the fact that it seems that the time needed to shut down the editor or the game increases greatly when this happens.

Whereas in an empty project it closes the editor almost instantaneously, in my project, when closing right after opening the project, having an empty scene as the main scene, it takes about 18 seconds to close the editor.

I'm not really sure if this increase in exit time is related to the orphaned strignames, but I'm inclined to guess that it may be at least partially related.

**Comment by Gnumaru** [comment] 2023-06-07 11:48
This is still occurring on 4.0.3.stable (at least on the windows build). I also noticed it occurs even when closing the project manager, but only when running with --verbose.

**Comment by Gnumaru** [comment] 2023-06-07 15:29
> Do you have **Verbose Stdout** enabled in the Project Settings? This also affects the editor itself in the project it's enabled.

I do not have verbose stdout enabled in my project settings, But I always start godot from the command line using --verbose which is the same.

Even though the OP opened this issue because of a game build, not the editor itself

> On exiting a game that uses a GDExtension (...)

My comments where about the editor itself (the non-mono version) while not using any gdextension. I commented in this issue instead of creating a new one because I think they are the same problem even though the OP related the error to game builds (instead of the editor) and gdextensions. But we could just open a new issue if needed although I think that's not necessary.

**Comment by clemens-tolboom** [comment] 2023-06-11 07:51
I run
```
/Applications/Godot_v4.0.3-stable_macos.universal.app/Contents/MacOS/Godot --editor --verbose
```

which prints on the last lines

> ...
Orphan StringName: MEMORY_POOL
Orphan StringName: extractor6
Orphan StringName: extractor7
Orphan StringName: extractor8
Orphan StringName: extractor9
Orphan StringName: skip_test_suites
Orphan StringName: KEY_BRACELEFT
Orphan StringName: PROPERTY_HINT_PLACEHOLDER_TEXT
StringName: 2398 unclaimed string names at exit.
ERROR: Pages in use exist at exit in PagedAllocator: N7Variant5Pools12BucketMediumE
   at: ~PagedAllocator (./core/templates/paged_allocator.h:140)
ERROR: Pages in use exist at exit in PagedAllocator: N7Variant5Pools11BucketSmallE
   at: ~PagedAllocator (./core/templates/paged_allocator.h:140)

**Comment by rcorre** [comment] 2023-07-04 14:21
I can repro this in godot 4.0.3 with a nearly empty project with no GDExtensions, as well as by opening/closing the project manager.

**Comment by nezvers** [comment] 2023-07-12 13:05
In my tests, it happens when the Windows X button closes the application.

**Comment by jeroenheijmans** [comment] 2023-07-13 19:24
Adding some additional reproducible scenarios, should it help in testing a potential fix in the future:

- Cross-post on [gamedev.stackexchange.com](https://gamedev.stackexchange.com/questions/206388/godot-4-games-exiting-with-orphan-stringname-messages-for-production-builds) where there's a handful of steps to create an extremely minimal repro (project with just one scene with a Control node, exported for Windows _without_ "Debug" enabled, run with `--verbose`) - gives a little under 700 Orphan StringName messages
- Clone [my open source game](https://github.com/pincrediball/pincrediball), open in Godot 4.0.x, export it _without_ Debug, and run with `--verbose` - gives a few thousand Orphan StringName messages

**Comment by WhalesState** [comment] 2023-07-14 06:59
same thing happens on windows 10 when exiting the application using the close button, am just adding the last few lines.

```
Orphan StringName: TYPE_NIL
Orphan StringName: HorizontalAlignment
Orphan StringName: KEY_KEYBOARD
Orphan StringName: GuiRadioChecked
Orphan StringName: string_to_latin1_chars
Orphan StringName: KEY_PERCENT
Orphan StringName: Key
Orphan StringName: KEY_BRACELEFT
Orphan StringName: PROPERTY_HINT_PLACEHOLDER_TEXT
StringName: 725 unclaimed string names at exit.
```

**Comment by jacogasp** [comment] 2023-07-17 09:59
Hello, same here.
It happens with 4.0.3 and just tried with 4.1: 600+ orphans at exit.
I tried with GDExtension/godot-cpp for 4.1.
My orphans are pretty much the same as the ones described in previous comments.

I tried to put a `print_orphans_nodes()` during the destruction of my main scene and this is a little bit of the output, dunno if can help

```
...
2074569931716 - Stray Node: root/@EditorNode@17640/@Control@697/@Panel@698/@VBoxContainer@706/@HSplitContainer@709/@HSplitContainer@717/@HSplitContainer@725/@VBoxContainer@726/@VSplitContainer@728/@VSplitContainer@754/@VBoxContainer@755/@PanelContainer@800/MainScreen/@WindowWrapper@11398/@ScriptEditor@11397/@VBoxContainer@10640/@HSplitContainer@10643/@VBoxContainer@10665/@TabContainer@10667/@TextEditor@21823/@GotoLineDialog@21822/@Panel@21811 (Type: Panel)
2074603486150 - Stray Node: root/@EditorNode@17640/@Control@697/@Panel@698/@VBoxContainer@706/@HSplitContainer@709/@HSplitContainer@717/@HSplitContainer@725/@VBoxContainer@726/@VSplitContainer@728/@VSplitContainer@754/@VBoxContainer@755/@PanelContainer@800/MainScreen/@WindowWrapper@11398/@ScriptEditor@11397/@VBoxContainer@10640/@HSplitContainer@10643/@VBoxContainer@10665/@TabContainer@10667/@TextEditor@21823/@GotoLineDialog@21822/@HBoxContainer@21813 (Type: HBoxContainer)
2074637040584 - Stray Node: root/@EditorNode@17640/@Control@697/@Panel@698/@VBoxContainer@706/@HSplitContainer@709/@HSplitContainer@717/@HSplitContainer@725/@VBoxContainer@726/@VSplitContainer@728/@VSplitContainer@754/@VBoxContainer@755/@PanelContainer@800/MainScreen/@WindowWrapper@11398/@ScriptEditor@11397/@VBoxContainer@10640/@HSplitContainer@10643/@VBoxContainer@10665/@TabContainer@10667/@TextEditor@21823/@GotoLineDialog@21822/@Label@21812 (Type: Label)
2074670595018 - Stray Node: root/@EditorNode@17640/@Control@697/@Panel@698/@VBoxContainer@706/@HSplitContainer@709/@HSplitContainer@717/@HSplitContainer@725/@VBoxContainer@726/@VSplitContainer@728/@VSplitContainer@754/@VBoxContainer@755/@PanelContainer@800/MainScreen/@WindowWrapper@11398/@ScriptEditor@11397/@VBoxContainer@10640/@HSplitContainer@10643/@VBoxContainer@10665/@TabContainer@10667/@TextEditor@21823/@GotoLineDialog@21822/@HBoxContainer@21813/@Control@21814 (Type: Control)
2074704149452 - Stray Node: root/@EditorNode@17640/@Control@697/@Panel@698/@VBoxContainer@706/@HSplitContainer@709/@HSplitContainer@717/@HSplitContainer@725/@VBoxContainer@726/@VSplitContainer@728/@VSplitContainer@754/@VBoxContainer@755/@PanelContainer@800/MainScreen/@WindowWrapper@11398/@ScriptEditor@11397/@VBoxContainer@10640/@HSplitContainer@10643/@VBoxContainer@10665/@TabContainer@10667/@TextEditor@21823/@GotoLineDialog@21822/@HBoxContainer@21813/@Button@21815 (Type: Button)
2074754481103 - Stray Node: root/@EditorNode@17640/@Control@697/@Panel@698/@VBoxContainer@706/@HSplitContainer@709/@HSplitContainer@717/@HSplitContainer@725/@VBoxContainer@726/@VSplitContainer@728/@VSplitContainer@754/@VBoxContainer@755/@PanelContainer@800/MainScreen/@WindowWrapper@11398/@ScriptEditor@11397/@VBoxContainer@10640/@HSplitContainer@10643/@VBoxContainer@10665/@TabContainer@10667/@TextEditor@21823/@GotoLineDialog@21822/@HBoxContainer@21813/@Control@21816 (Type: Control)
2074788035537 - Stray Node: root/@EditorNode@17640/@Control@697/@Panel@698/@VBoxContainer@706/@HSplitContainer@709/@HSplitContainer@717/@HSplitContainer@725/@VBoxContainer@726/@VSplitContainer@728/@VSplitContainer@754/@VBoxContainer@755/@PanelContainer@800/MainScreen/@WindowWrapper@11398/@ScriptEditor@11397/@VBoxContainer@10640/@HSplitContainer@10643/@VBoxContainer@10665/@TabContainer@10667/@TextEditor@21823/@GotoLineDialog@21822/@HBoxContainer@21813/@Button@21817 (Type: Button)
2074838367188 - Stray Node: root/@EditorNode@17640/@Control@697/@Panel@698/@VBoxContainer@706/@HSplitContainer@709/@HSplitContainer@717/@HSplitContainer@725/@VBoxContainer@726/@VSplitContainer@728/@VSplitContainer@754/@VBoxContainer@755/@PanelContainer@800/MainScreen/@WindowWrapper@11398/@ScriptEditor@11397/@VBoxContainer@10640/@HSplitContainer@10643/@VBoxContainer@10665/@TabContainer@10667/@TextEditor@21823/@GotoLineDialog@21822/@HBoxContainer@21813/@Control@21818 (Type: Control)
2074871921622 - Stray Node: root/@EditorNode@17640/@Control@697/@Panel@698/@VBoxContainer@706/@HSplitContainer@709/@HSplitContainer@717/@HSplitContainer@725/@VBoxContainer@726/@VSplitContainer@728/@VSplitContainer@754/@VBoxContainer@755/@PanelContainer@800/MainScreen/@WindowWrapper@11398/@ScriptEditor@11397/@VBoxContainer@10640/@HSplitContainer@10643/@VBoxContainer@10665/@TabContainer@10667/@TextEditor@21823/@GotoLineDialog@21822/@VBoxContainer@21819 (Type: VBoxContainer)
2074905476056 - Stray Node: root/@EditorNode@17640/@Control@697/@Panel@698/@VBoxContainer@706/@HSplitContainer@709/@HSplitContainer@717/@HSplitContainer@725/@VBoxContainer@726/@VSplitContainer@728/@VSplitContainer@754/@VBoxContainer@755/@PanelContainer@800/MainScreen/@WindowWrapper@11398/@ScriptEditor@11397/@VBoxContainer@10640/@HSplitContainer@10643/@VBoxContainer@10665/@TabContainer@10667/@TextEditor@21823/@GotoLineDialog@21822/@VBoxContainer@21819/@Label@21820 (Type: Label)
2074939030490 - Stray Node: root/@EditorNode@17640/@Control@697/@Panel@698/@VBoxContainer@706/@HSplitContainer@709/@HSplitContainer@717/@HSplitContainer@725/@VBoxContainer@726/@VSplitContainer@728/@VSplitContainer@754/@VBoxContainer@755/@PanelContainer@800/MainScreen/@WindowWrapper@11398/@ScriptEditor@11397/@VBoxContainer@10640/@HSplitContainer@10643/@VBoxContainer@10665/@TabContainer@10667/@TextEditor@21823/@GotoLineDialog@21822/@VBoxContainer@21819/@LineEdit@21821 (Type: LineEdit)
...
```
They seem all related to some EditorNode

**Closed** 2023-10-18 22:09 UTC
Labels: bug, topic:core, confirmed, topic:gdextension
