### ISSUE TITLE
Environment bg_mode Canvas + Glow doesn't work on Android [GLES3]

### ISSUE THREAD

**Issue by grenzionky** [godotengine/godot#28776] opened 2019-05-08 23:21 UTC
**Godot version:**
3.1

**OS/device including version:**
Computer:
OS: Manjaro 18.0.4 Illyria
Kernel: x86_64 Linux 5.0.9-2-MANJARO
DE: KDE 5.57.0 / Plasma 5.15.4
WM: KWin

Phone:
Nexus 5X
Android 8.1.0

**Issue description:**
world environment canvas glow doesn't work on android

**Steps to reproduce:**
enable world environment canvas glow, observe that it works on the computer. export it for android, and it doesn't work on my phone.

**Minimal reproduction project:**
https://mega.nz/#!6t5DCSgY!vssu8eIcfpTVmO_nZ2UiNNojQsKuL0fiTJsl4OEzo_0

**Comment by YeldhamDev** [comment] 2019-05-09 05:38
Could you provide more details about the phone itself? Model, Android version, etc.

**Comment by bojidar-bg** [comment] 2019-05-09 08:41
Does it happen when forcing GLES2 via project settings / command line, and running on desktop?

**Comment by Calinou** [comment] 2019-05-09 09:41
@bojidar-bg As far as I know, glow isn't implemented in the GLES2 renderer.

**Comment by grenzionky** [comment] 2019-05-09 10:23
@YeldhamDev I updated the question

**Comment by grenzionky** [comment] 2019-05-09 10:23
Gles2 doesn't give a glow option to begin with

**Comment by akien-mga** [comment] 2019-10-01 07:34
I can confirm that using GLES3 + Enviroment Background Mode "Canvas", glow doesn't work on Android.

Glow is now implemented in GLES2, but bg_mode Canvas is outright broken on GLES2, so this issue is specific to GLES3.

**Comment by clayjohn** [comment] 2019-12-15 18:41
This is likely because Android defaults to "3D-no effects". You need to change the render setting Frambuffer_allocation.mobile to "3D".
http://docs.godotengine.org/en/latest/classes/class_projectsettings.html#class-projectsettings-property-rendering-quality-intended-usage-framebuffer-allocation-mobile

**Comment by akien-mga** [comment] 2019-12-16 07:11
@clayjohn I just tried and that doesn't seem to be the case.

- On Linux desktop with "3D Without Effects", 2D glow still works fine in GLES3.
- On a GLES3-compatible Android device (Xiaomi Pocophone F1) with "3D", 2D glow still doesn't work.

BTW, even if it doesn't seem to be the full explanation here, it might still be a relevant factor. I feel we might need clearer documentation in a prominent place (and `note::` references in other related places) to the framebuffer allocation options and their different default values on desktop and mobile.

**Comment by fossegutten** [comment] 2020-03-04 14:05
I want to add this: With Godot 3.2 on Windows:
If i turn on Background Mode "Canvas" in GLES3, the other viewports (used for foreground) fail to render transparency, and renders black instead, even if "Transparent Bg" is enabled.

**Comment by gamergamesz** [comment] 2020-05-26 15:50
I am having this problem basically for be glow is working on gles3 (2d canvas mode) but while using addictive blend mode it is getting weird flickers and is getting a blueish cast on the whole screen

**Comment by lambferatu** [comment] 2022-02-23 06:05
I was having this issue in the 3.x branch, however doing [this](https://godotengine.org/qa/30051/glowing-doesnt-work-on-android) made it work on a Huawei Nova 5T with Android 10 and the Android Studio emulators

**Comment by akien-mga** [comment] 2022-02-23 18:00
Fixed by #58470.

**Closed by akien-mga** 2022-02-23 18:00 UTC
Labels: platform:android, topic:rendering, documentation, topic:3d
