### ISSUE TITLE
Text garbling happens when the editor's language is set to Japanese

### ISSUE THREAD

**Issue by azul372** [godotengine/godot#65180] opened 2022-09-01 06:31 UTC
### Godot version

4.0alpha15

### System information

Windows 10, Vulkan,  NVIDIA Quadro P2000

### Issue description

When the editor's language is set to Japanese, some characters are garbled in certain windows, such as:

1. FileDialog
![image](https://user-images.githubusercontent.com/80684394/187841843-a30ac712-e639-46f1-b9a1-76e13d1c4ff3.png)[
The FileDialog window looks like this in the editor view as well as when you use a FileDialog node in `@tool` scripts. It doesn't seem to happen when you actually *run* the scene containing a FileDialog node.

2. Docs
![image](https://user-images.githubusercontent.com/80684394/187842236-8ded08c2-3d6f-4ad1-9acc-941e00dfec61.png)

It's probably due to the font used in these cases not supporting Japanese characters. Also, the issue didn't happen in the older versions.
Perhaps this occurs in some other languages, especially those that use CJK characters, although I haven't tested yet.

### Steps to reproduce

1. Set the editor's language to Japanese and restart the engine
2. Create a scene, add FileDialog node and see how it looks

**Comment by akien-mga** [comment] 2022-09-01 06:47
That's a partial duplicate of https://github.com/godotengine/godot/issues/65114 and I think another issue for FileDialog. We have various theme propagation bugs which are being worked on.

**Closed** 2022-09-02 12:06 UTC
Labels: bug, topic:editor, regression

**Comment by azul372** [comment] 2022-09-16 06:26
#65210 said it will likely fix this issue, but I can still reproduce the FIleDialog issue in 4.0beta1.
