### ISSUE TITLE
Delayed Audio in WASM/HTML export

### ISSUE THREAD

**Issue by Nolkaloid** [godotengine/godot#16259] opened 2018-01-31 21:02 UTC
**Godot version:**
3.0 Stable

**OS/device including version:**
Ubuntu 16.04/Linux
Firefox 57

**Issue description:**
Projects exported to html have delayed sounds.

**Steps to reproduce:**
Load up a project that has some sound playing in it (the plat-former demo for example) and export it to HTML. Notice that the sounds are delayed.

**Comment by reduz** [comment] 2018-01-31 21:41
Unfortunately nothing much can be done about this due to the problem of
WebAssembly not supporting threads.
This forces audio to be used on the main thread, and it needs to be mixed
with some delay to avoid stuttering. Maybe we could decrease delay a bit
and see how well it works.
This will be solved very soon, as next WebAssembly version will support
threads.

**Comment by Nobelix** [comment] 2018-01-31 22:00
Yaaaay, but anyways I don't know if it's just my project/ really bad code but in general WASM is pretty much broken for me. :pensive:

**Comment by justinluk** [comment] 2019-02-22 18:01
I'm also experiencing this same problem. Audio is very delayed.

**Comment by BenjaminNavarro** [comment] 2019-07-29 07:24
I just noticed it also with Firefox but it works just fine with Chromium (Linux). So in the meantime, you can instruct your players to switch browser

**Comment by belen-albeza** [comment] 2019-09-07 18:28
> This will be solved very soon, as next WebAssembly version will support
threads.

Hi @reduz are there any updates about this? Thanks!

**Comment by Silvea12** [comment] 2019-11-10 10:07
Any updates on this?

**Comment by Calinou** [comment] 2019-11-10 15:55
WebAssembly threads are supported since Chrome 74 and recent Firefox versions. What about Safari and Edge though? (In other words, will we have to keep a fallback once we implement WebAssembly threads in the HTML5 export?)

**Comment by Silvea12** [comment] 2019-11-10 22:52
I'd say it'd be a good idea to keep a fallback for now - at least if you want to work by "web standards" where having fallbacks for compat + JS-based feature detection is the norm.
-------- Original Message --------

**Comment by Calinou** [comment] 2019-11-11 09:51
@Silvea12 On the other hand, we have to balance this with the file size (as keeping a fallback will likely increase the `.wasm` payload size).

**Comment by Silvea12** [comment] 2019-11-11 10:11
The standard way to handle that is multiple modules that you can download and pick between, with a preloader that can decide which to download based on feature set. But then that may increase engine complexity a good amount - or at least, the build process.

**Comment by Silvea12** [comment] 2019-11-11 10:11
@Calinou The standard way to handle that is multiple modules that you can download and pick between, with a preloader that can decide which to download based on feature set. But then that may increase engine complexity a good amount - or at least, the build process. So it may not be worth doing.

**Comment by belen-albeza** [comment] 2019-12-02 17:02
In the meantime, is there a workaround for this? Delayed audio kind of breaks the player's experience.

**Comment by stdio2016** [comment] 2020-02-27 07:49
I found a workaround
Add this program in AutoLoad singleton:
```GDScript
func _ready():
	# XXX: workaround godot web audio latency issue by recreating script processor
	var jsCode = """
		setTimeout(function () {
			var channelCount = _audioDriver_audioContext.destination.channelCount;
			var bufferSize = _audioDriver_scriptNode.bufferSize;
			var process = _audioDriver_scriptNode.onaudioprocess;
			_audioDriver_scriptNode.disconnect();
			_audioDriver_scriptNode = _audioDriver_audioContext.createScriptProcessor(bufferSize, 2, channelCount);
			_audioDriver_scriptNode.onaudioprocess = process;
			_audioDriver_scriptNode.connect(_audioDriver_audioContext.destination);
		}, 0);
	"""
	if OS.get_name() == 'HTML5':
		JavaScript.eval(jsCode)
```
Tested on Godot 3.2
The latency can still be as large as 0.1 second (4096/44100Hz) because audio is generated from ScriptProcessorNode, whose buffer size is decided by browser heuristics.
On my computer, Firefox creates ScriptProcessorNode with buffer size 4096, where Chrome creates one with buffer size 2048.

**Comment by belen-albeza** [comment] 2020-07-16 09:02
> Unfortunately nothing much can be done about this due to the problem of WebAssembly not supporting threads.

It looks like thread support was added in this commit https://github.com/godotengine/godot/commit/21c9f37757d564009e9e400142b3b4c70af237d3 Does it provide a way to fix this bug?

If not, would it be feasible to make @stdio2016 workaround to be added automatically to the HTML export?

Thanks!

**Comment by Faless** [comment] 2020-07-27 09:14
The buffer size is now (`3.2.2`) configurable using the `audio/output_latency` project setting (which was ignored for HTML5 exports in previous releases).
In `3.2.3` the default output latency for web will be 50ms (which seems to be a good trade off on many devices).
See #38816 and #40052
Further improvements might come when we implement audio mixing in threads (browser support seems still limited for this feature).

I'm closing this issue as fixed, since the delay is no longer browser dependent, and can be configured (like on other platforms) but feel free to comment if you think this should be reopen.

**Closed by Faless** 2020-07-27 09:14 UTC
Labels: bug, confirmed, platform:html5, topic:audio

**Comment by nightblade9** [comment] 2022-07-17 16:04
As of writing, with Godot 3.4.4, the issue is still there; setting the export type to `Threads` resolved the issue for me. :tada: 

![image](https://user-images.githubusercontent.com/31222662/179409646-4364e6a9-82f6-4c17-bc92-b0caf813c926.png)

(Sorry to necro an old issue; this is the top DuckDuckGo search result for this issue.)

**Comment by Calinou** [comment] 2022-07-17 17:00
After exporting with threads enabled, remember that you **must** configure the web server to allow SharedArrayBuffer to be usable: https://docs.godotengine.org/en/latest/tutorials/export/exporting_for_web.html#threads

This is unfortunately not possible on itch.io or GitHub Pages.

**Comment by nightblade9** [comment] 2022-07-17 21:53
> As of July 2022, this is unfortunately not possible on itch.io or GitHub Pages.

Ouch, I didn't know that; I was planning to host it on Itch or GitHub Pages. Is there an alternative solution or workaround?

**Comment by Calinou** [comment] 2022-07-17 22:28
> Ouch, I didn't know that; I was planning to host it on Itch or GitHub Pages. Is there an alternative solution or workaround?

Other than using your own server to host the project, I'm afraid not.

It's technically possible to build a server that sends the required headers and proxies files from GitHub Pages, but this will likely require CORS trickery to bypass the usual security policies.

**Comment by nightblade9** [comment] 2022-07-18 03:47
Thanks for the quick replies @Calinou , I really appreciate it.

FYI, Itch officially supports (experimental) SharedArrayBuffer support; there seems to be an announcement here: https://itch.io/t/2025776/experimental-sharedarraybuffer-support

As of writing, this doesn't seem to work on Firefox with a Godot 3.4.4; I need to investigate more (sounds like Chrome works), so YMMV.
