### ISSUE TITLE
In editor, Animation Frames displayed on SpriteFrames do not respect filtering settings

### ISSUE THREAD

**Issue by Proggle** [godotengine/godot#67159] opened 2022-10-09 22:18 UTC
### Godot version

v4.0.beta2.official [f8745f2f7]

### System information

Windows 10

### Issue description

In the Spriteframes object, displayed animation frames do not respect filtering settings in the editor.  This can result in the preview showing bleed from edges which is not present in the actual sprites, even if 'fix alpha border' is enabled.

![image](https://user-images.githubusercontent.com/89282845/194781953-d5cce862-4d96-42e8-b31e-0efc8753d339.png)

### Steps to reproduce

Import a texture for an animated sprite, look at it in the editor.

### Minimal reproduction project

[sprite_frames_v4b2.zip](https://github.com/godotengine/godot/files/9742673/sprite_frames_v4b2.zip)

**Comment by Calinou** [comment] 2022-10-09 23:15
Duplicate of https://github.com/godotengine/godot/issues/57550.

**Closed by Calinou** 2022-10-09 23:15 UTC
