### ISSUE TITLE
Rename texture corrupts scene

### ISSUE THREAD

**Issue by lufog** [godotengine/godot#69615] opened 2022-12-05 16:29 UTC
### Godot version

v4.0.beta.custom_build [d759210f5]

### System information

Windows 11, Forward, Geforce 1660 (526.98)

### Issue description

https://user-images.githubusercontent.com/10379487/205687024-69162df7-ab87-488d-90cf-809b8145d56d.mp4

This behavior repeats regardless of which node (`TextureRect`, `Sprite2D`, `TileMap`) uses the texture. Sometimes at the moment of renaming, Godot crashes.

### Steps to reproduce

- open main.tscn
- rename texture

### Minimal reproduction project

[scene_content_corruption_test.zip](https://github.com/godotengine/godot/files/10155883/scene_content_corruption_test.zip)

**Comment by KoBeWi** [comment] 2022-12-05 16:34
Duplicate of #69260 (same cause)

**Closed by KoBeWi** 2022-12-05 16:34 UTC
