### ISSUE TITLE
Editor crashes when changing scene

### ISSUE THREAD

**Issue by yedpodtrzitko** [godotengine/godot#69251] opened 2022-11-27 12:36 UTC
### Godot version

- crash on 4.0.beta5.official up to 690199b7dddd784b435e6ce71365256b29285fe8

- **no crash** on 4.0.beta4.official 

### System information

MacOS 13, MB Air M1

### Issue description

- traceback is from custom build ( 690199b7dddd784b435e6ce71365256b29285fe8 )

```
ERROR: Condition "r[0] != 'R' || r[1] != 'I' || r[2] != 'F' || r[3] != 'F' || r[8] != 'W' || r[9] != 'E' || r[10] != 'B' || r[11] != 'P'" is true. Returning: Ref<Image>()
   at: _webp_unpack (modules/webp/webp_common.cpp:125)
ERROR: Condition "img.is_null() || img->is_empty()" is true. Returning: Ref<Image>()
   at: load_image_from_file (scene/resources/texture.cpp:690)
ERROR: Failed loading resource: res://.godot/imported/icon.png-487276ed1e3a0c39cad0279d744ee560.ctex. Make sure resources have been imported by opening the project in the editor at least once.
   at: _load (core/io/resource_loader.cpp:215)
ERROR: Failed loading resource: res://icon.png. Make sure resources have been imported by opening the project in the editor at least once.
   at: _load (core/io/resource_loader.cpp:215)

================================================================
handle_crash: Program crashed with signal 11
Engine version: Godot Engine v4.0.beta.custom_build (690199b7dddd784b435e6ce71365256b29285fe8)
Dumping the backtrace. Please include this when reporting the bug to the project developer.
[1] 1   libsystem_platform.dylib            0x0000000192be82a4 _sigtramp + 56
[2] SceneTree::call_group_flagsp(unsigned int, StringName const&, StringName const&, Variant const**, int) (in godot.macos.editor.arm64) + 1296
[3] SceneTree::_call_group(Variant const**, int, Callable::CallError&) (in godot.macos.editor.arm64) + 132
[4] MethodBindVarArgT<SceneTree>::call(Object*, Variant const**, int, Callable::CallError&) (in godot.macos.editor.arm64) + 52
[5] Object::callp(StringName const&, Variant const**, int, Callable::CallError&) (in godot.macos.editor.arm64) + 448
[6] Callable::callp(Variant const**, int, Variant&, Callable::CallError&) const (in godot.macos.editor.arm64) + 176
[7] MessageQueue::_call_function(Callable const&, Variant const*, int, bool) (in godot.macos.editor.arm64) + 336
[8] MessageQueue::flush() (in godot.macos.editor.arm64) + 276
[9] SceneTree::physics_process(double) (in godot.macos.editor.arm64) + 456
[10] Main::iteration() (in godot.macos.editor.arm64) + 528
[11] OS_MacOS::run() (in godot.macos.editor.arm64) + 116
[12] main (in godot.macos.editor.arm64) + 404
[13] 13  dyld                                0x000000019288fe50 start + 2544
-- END OF BACKTRACE --
================================================================
```

### Steps to reproduce

- cant reproduce this deterministically, I just hope the traceback is sufficient.
- `icon.png` seems completely fine

### Minimal reproduction project

The instructions say `Be sure to not include the .godot folder` but the crash does not happen without the folder in the minimal project 🤔

**Comment by akien-mga** [comment] 2022-11-27 12:49
Duplicate of #69159

>The instructions say Be sure to not include the .godot folder but the crash does not happen without the folder in the minimal project 🤔

Well those are general instructions, obviously if the problem depends on that folder you should include it :)

**Closed by akien-mga** 2022-11-27 12:49 UTC
