### ISSUE TITLE
[4.3 Dev 3] Undo in Script Editor is dangerously dysfunctional (OK in 4.2)

### ISSUE THREAD

**Issue by daviesaz** [godotengine/godot#89060] opened 2024-03-01 19:10 UTC
### Tested versions

- Reproducible in 4.3 Dev 3, not in 4.3

### System information

Mac OS Sonoma 14.2.1, Intel processor

### Issue description

Undo at least sometimes undoes something back in history other than the most recent change.  It seems to ignore text changes and go back to a recent structural change.

### Steps to reproduce

In the editor, create a Node2D.  Add a script to the Node2D and, in the script editor, type in a second "pass" operation on the _ready method.  Hit Cmd-Z.

In earlier versions, the second "pass" is deleted.  In 4.3 Dev 3, the whole script is deleted from the Node2D

### Minimal reproduction project (MRP)

N/A

**Comment by akien-mga** [comment] 2024-03-02 13:44
Please test 4.3-dev4, I've seen report of such an issue fixed in that snapshot.

**Comment by daviesaz** [comment] 2024-03-02 23:15
Yes.

**Comment by luevano** [comment] 2024-03-07 05:15
@akien-mga just tested in `4.3-dev4`, can't reproduce.

**Comment by akien-mga** [comment] 2024-03-07 13:38
Closed as fixed in 4.3-dev4. @daviesaz Please let us know if you still reproduce the issue in that version or later ones.

**Closed by akien-mga** 2024-03-07 13:38 UTC
Labels: bug, topic:editor, regression

**Comment by caimantilla** [comment] 2024-03-17 04:09
I've got no clue what was going on here, but both dev5 and master have been very problematic for me. I can't get the script editor to undo, nor can I even close the current script. Even if I remap the Close Scene shortcut (why was it changed??) all that CMD+W does is stop inspecting the current resource. Very unfortunate, I'm liking the other GUI changes that I've noticed in 4.3, but there's something seriously wrong with the script editor.

**Comment by caimantilla** [comment] 2024-03-17 04:16
> Closed as fixed in 4.3-dev4. @daviesaz Please let us know if you still reproduce the issue in that version or later ones.

I just tried 4.3-dev4, and everything works as expected with it. Even 4.3-dev3 has better behavior than 4.3-dev5, as at least I can close the script in that version, but it's otherwise the same deal as 4.3-dev3. There must have been some regression between 4.3-dev4 and 4.3-dev5.

**Comment by kitbdev** [comment] 2024-03-17 15:53
@caimantilla It looks like the Close Scene shortcut was changed in https://github.com/godotengine/godot/pull/88913
The undo problem sounds like it is different and a new issue can be opened for it. It seems to work fine for me on windows, and it may be related to https://github.com/godotengine/godot/pull/85325.

**Comment by caimantilla** [comment] 2024-03-17 16:39
> @caimantilla It looks like the Close Scene shortcut was changed in #88913 The undo problem sounds like it is different and a new issue can be opened for it. It seems to work fine for me on windows, and it may be related to #85325.

From what I remember, close script didn't even work after I changed the close scene keybind back to the old one. Just think the script editor isn't receiving shortcuts at all

**Comment by lostminds** [comment] 2024-03-18 08:23
Also seeing this, the bug from 4.3dev3 where undo in the script editor instead undid changes in open scenes was fixed in 4.3dev4, but is now back again in 4.3dev5. Interestingly it seems specific to undo/redo. Other keyboard shortcuts like copy/paste correctly target the active script editor.

**Comment by daviesaz** [comment] 2024-03-19 04:42
Confirmed. In a fresh project, create a Node2D and then a child Node2D.  Add an internal script to the child.  Duplicate the pass command in the _ready method.  Hit Cmd-Z (on a Mac) to undo. The effect is to remove the child rather than the text just typed.

**Comment by caimantilla** [comment] 2024-04-02 03:02
...And now it seems to be fixed.

**Comment by kitbdev** [comment] 2024-04-02 03:36
> ...And now it seems to be fixed.

It looks like it was mentioned on another issue and then fixed.
- fixed in https://github.com/godotengine/godot/pull/89953
