### ISSUE TITLE
Editor suggested OS enums contain an underscore which is incorrect

### ISSUE THREAD

**Issue by madmiraal** [godotengine/godot#49691] opened 2021-06-17 15:30 UTC
### Godot version

3.3.2.stable

### System information

Ubuntu 21.04

### Issue description

When using the functions `OS.get_system_dir()`, `OS.get_native_handle()` or `OS.get_video_driver_name()`, the suggested valid enum values all begin with `_OS.*`:
![OS enum prompt](https://user-images.githubusercontent.com/9253928/122423809-1df38d00-cf86-11eb-95ab-b7a8c9e79f58.png)

However, when using one of these, you get a `Parser Error: Identifier not found: _OS` error when running the project.

### Steps to reproduce

In a script, type  `OS.get_system_dir(`, `OS.get_native_handle(` or `OS.get_video_driver_name(`, and select one of the suggested values. Run the project.

### Minimal reproduction project

N/A: This is an editor issue. A project is easily fixed by removing the underscore.

**Comment by kleonc** [comment] 2021-06-17 19:21
Duplicate of #35469, #37184.

**Comment by Calinou** [comment] 2021-06-17 20:44
Closing per @kleonc's comment.

**Closed by Calinou** 2021-06-17 20:44 UTC
Labels: bug, topic:editor, topic:gdscript
