### ISSUE TITLE
X11: crash when using multithreaded 2d physics

### ISSUE THREAD

**Issue by Hinsbart** [godotengine/godot#5095] opened 2016-06-07 20:42 UTC
**Operating system or device - Godot version:**
Arch Linux 64bit, Intel gpu - 5cd7611 (fix x11 vsync)

**Issue description**:
After 5cd7611, the engine crashes when `physics_2d/thread_model` is set to multi-threaded.
Crash is happening in the call to `glXSwapInterval` in `context_gl_x11.cpp (ContextGL_X11::set_use_vsync())`.

**Comment by reduz** [comment] 2016-06-10 01:26
i can't reproduce.. how did you trigger it?

**Comment by FabiGjuzi** [comment] 2016-09-24 09:17
I am having the same issue on Ubuntu.When try to open my project it says : 
OPENING: /home/programues/Documents/godot_projects/NetIt (::home::programues::Documents::godot_projects::NetIt)
CREATING PHYSICS 2D THREAD
STARTING PHYISICS 2D THREAD
DONE PHYSICS 2D THREAD
 and then it crashes immediately

**Comment by bojidar-bg** [comment] 2016-09-24 10:14
@FabiGjuzi Can you get a GDB backtrace? :)

**Comment by Calinou** [comment] 2018-04-11 08:32
First of all thank you for your report and sorry for the delay.

We released Godot 3.0 in January 2018 after 18 months of work, fixing many old issues either directly, or by obsoleting/replacing the features they were referring to.

We still have hundreds of issues whose relevance/reproducibility needs to be checked against the [current stable version](https://godotengine.org/download), and that's where you can help us.
**Could you check if the issue that you described initially is still relevant/reproducible in Godot 3.0 or any newer version, and comment about it here?**

For bug reports, please also make sure that the issue contains detailed steps to reproduce the bug and, if possible, a zipped project that can be used to reproduce it right away. This greatly speeds up debugging and bugfixing tasks for our contributors.

Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

Thanks in advance.

*Note: This message is being copy-pasted to many "stale" issues (90+ days without activity). It might happen that it is not meaningful for this specific issue or appears oblivious of the issue's context, if so please comment to notify the Bugsquad about it.*

**Comment by Hinsbart** [comment] 2018-04-11 18:09
I haven't been able to reproduce it since. Might have been project specific :/

**Comment by akien-mga** [comment] 2018-04-11 19:15
Closing for now then, we can reopen if someone comments with steps to reproduce (otherwise a new issue could be opened).

**Closed by akien-mga** 2018-04-11 19:15 UTC
Labels: bug, platform:linuxbsd, topic:porting, topic:rendering
