### ISSUE TITLE
godot 3.1 alpha2 tilemap Low frame rate on android

### ISSUE THREAD

**Issue by myhalibobo** [godotengine/godot#24033] opened 2018-11-28 12:49 UTC
Operating system or device - Godot version:
Honor 8 Lite
godot 3.1 alpha2
I looked at other related ones and I didn't get a solution. This is a screenshot of me running on android,fps 46-49。
![screenshot_20181128-203609](https://user-images.githubusercontent.com/8662169/49152298-517d5600-f34d-11e8-8f9e-776baeb220af.jpg)
![godot_tile_project](https://user-images.githubusercontent.com/8662169/49152740-bb4a2f80-f34e-11e8-8506-83ec2ba09ad2.png)
Link to minimal example project:
[tilemap.zip](https://github.com/godotengine/godot/files/2624516/tilemap.zip)

**Comment by usbhell** [comment] 2019-01-08 13:41
I'm seeing the same with 3.1 Beta 1. 180 of the same 64x64 tile brings the fps down to single figures on the two devices I tried it on.

**Comment by bojidar-bg** [comment] 2019-01-08 13:56
Duplicate of #24466?

**Comment by volzhs** [comment] 2019-01-08 14:03
guess so

**Comment by akien-mga** [comment] 2019-01-08 16:58
The OP predates the commit referenced in #24466 though IINM (alpha 2). But @usbhell's comment might be due to #24466 yes.

**Comment by underdoeg** [comment] 2019-01-09 10:43
I see the same issue when rendering a lot of text on an older samsung kitkat device. I guess this is related to sprite rendering?

**Comment by Zireael07** [comment] 2019-01-09 13:31
@underdoeg: Related to the fact every letter is a draw call.

**Comment by akien-mga** [comment] 2019-01-25 23:31
Could you try again with 3.1 beta 2 (or 3.1 beta 3 which we'll publish tomorrow and might perform slightly better)?

**Comment by akien-mga** [comment] 2019-01-29 14:14
Thanks for testing. Let's close as it seems at least @usbhell and @underdoeg's reports were related to #24466 as @bojidar-bg mentioned. @myhalibobo's report predates that, but there were many changes since alpha 2 so performance might be better too.

If you can still reproduce the original issue on 3.1 beta 3 or later, it might be worth opening a new report to avoid the confusion with the alpha 5 - beta 2 performance drop.

**Closed by akien-mga** 2019-01-29 14:14 UTC
Labels: bug, platform:android, topic:rendering

**Comment by myhalibobo** [comment] 2019-02-16 11:55
@akien-mga I downloaded the test again, and my phone is still low framerate,It is 44 FPS,The phone model is hua honor 8 lite and godot 3.1 alpha4 
![screenshot_20190216-195212](https://user-images.githubusercontent.com/8662169/52899413-d24d3f00-3224-11e9-9132-07be484cc98b.jpg)

**Comment by volzhs** [comment] 2019-02-16 13:01
alpha 4?
we have a beta 3 now. should be with it.

**Comment by myhalibobo** [comment] 2019-02-16 13:04
@volzhs yes,I didn't test bata3,I wrote it wrong. I tested bata4

**Comment by myhalibobo** [comment] 2019-02-16 13:05
![image](https://user-images.githubusercontent.com/8662169/52900243-91f2be80-322e-11e9-99a3-d7329a3f607f.png)
this
