### ISSUE TITLE
3d camera preview zoom 

### ISSUE THREAD

**Issue by tofuhead** [godotengine/godot#11016] opened 2017-09-06 14:48 UTC
would it be possible to add zooming to 3d camera preview window, so that you could see the whole framing? as it is now, it never seems to quite fit to it so you don't know exactly what you are getting.

.b

**Comment by akien-mga** [comment] 2018-01-15 10:45
Is this still reproducible in Godot 3.0 RC1?

**Comment by tofuhead** [comment] 2018-01-16 21:10
yes.. it seems like the yellowish frameline is always stretched 100% height of the view.. but if you resize the the panels on left and right thus shrinking the preview view, you don't see any change on aspect ratio of the frame.. so you don't really know if it's right..  
so it was just an idea to add the ability to "lock" frame to correct aspect ratio, so that the insides of the frame is what you actually will always be getting when you launch the game.. and then around that there could be a passepartout that one could adjust with mousewheel.. it's a bit hard to explain, but it's how Blender does camera previews in similar kind of tiling UI that Godot has..
maybe a screenshot helps..

.b
![bcams](https://user-images.githubusercontent.com/8156935/35012441-6f182656-fb12-11e7-9479-4faf26b3e8a2.jpg)

**Comment by Calinou** [comment] 2020-06-18 12:45
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!

**Closed by Calinou** 2020-06-18 12:45 UTC
Labels: enhancement, topic:editor, usability

**Comment by tomellwood-github** [comment] 2023-10-25 06:57
Was this added to Godot Improvement Proposals?

**Comment by Calinou** [comment] 2023-10-25 19:25
> Was this added to Godot Improvement Proposals?

I believe this proposal is already implemented as of 4.2.beta2, and even in previous versions like 3.x. It seems OP was misguided because the aspect ratio of the preview frame *does* shrink to always fit within your window. (This aspect ratio is defined by the viewport base width and height project settings, which default to 1152×648 = 16:9).
