### ISSUE TITLE
MacOS M1 Pro missing lighting on some squares

### ISSUE THREAD

**Issue by avesanen** [godotengine/godot#66822] opened 2022-10-03 15:07 UTC
### Godot version

4.0.beta2

### System information

MacOS 12.6, M1 Pro

### Issue description

When using Forward+ (and previously Vulkan Clustered) renderer, omnilight and spotlights are sometimes not rendered in small square shaped areas. Doesn't happen with Mobile renderer or in windows.

This has been the case with all Godot 4 builds I've tried. Don't have access to another laptop with same processor to verify it isn't hardware issue.

### Steps to reproduce

- Create new project with Forward + renderer.
- Create a cube mesh.
- Put light next to the mesh.
- Move camera or light, some frames show dark squares.

![IMAGE 2022-10-03 18:05:40](https://user-images.githubusercontent.com/1142321/193611204-1d7e4ca4-8bbd-4c8d-aa93-d3cf4733cae4.jpg)

**Comment by Calinou** [comment] 2022-10-03 15:33
Duplicate of https://github.com/godotengine/godot/issues/61108.

**Closed by Calinou** 2022-10-03 15:33 UTC
