### ISSUE TITLE
 Condition "!id_map.has(p_rid.get_data())" is true. Returned: __null

### ISSUE THREAD

**Issue by nice9uy** [godotengine/godot#42952] opened 2020-10-21 04:03 UTC
**Godot version:**
 v3.2.3.stable.mono.official

**OS/device including version:**
OS Windows 10
OpenGL ES 3.0 Renderer: GeForce GTX 950M/PCIe/SSE2

**Issue description:**
I Got an error when i run my game

![123](https://user-images.githubusercontent.com/25494182/96671772-d8e27100-138c-11eb-9ac9-c19a825ab867.PNG)

Can you help me, Please...

**Comment by volzhs** [comment] 2020-10-21 04:06
there are many similar reports already with providing detail condition.
https://github.com/godotengine/godot/issues?q=is%3Aissue+is%3Aopen+%21id_map.has%28p_rid.get_data%28%29%29

**Comment by Calinou** [comment] 2020-10-21 11:47
Duplicate of #38229 and possibly others.

**Closed by Calinou** 2020-10-21 11:47 UTC
