### ISSUE TITLE
PascalCase node naming does not respect class names with numbers

### ISSUE THREAD

**Issue by Yagich** [godotengine/godot#66431] opened 2022-09-26 10:03 UTC
### Godot version

4.0b1

### System information

Linux/Manjaro

### Issue description

in 3.x, when creating a new Node in a scene with the ProjectSetting `node/name_casing` set to `PascalCase`, classes with numbers, for example `Node2D` would be named exactly as the class, eg `Node2D`. Now, with the equivalent ProjectSetting `editor/node_naming/name_num_separator` set to `PascalCase`, creating a `Node2D` would be named `Node2d`, which is invalid PascalCase.

### Steps to reproduce

Add a node to a scene that has a number followed by letters in its class (eg `Node2D`)

**Comment by Zireael07** [comment] 2022-09-26 10:07
I'm sure it was already reported (and probably fixed too) but I can't find the issue #

**Comment by akien-mga** [comment] 2022-09-26 11:23
Duplicate of #65803

**Closed by akien-mga** 2022-09-26 11:23 UTC
Labels: bug, topic:core, confirmed
