### ISSUE TITLE
Tabbing between input fields sometimes does not move input focus to next field

### ISSUE THREAD

**Issue by derkork** [godotengine/godot#67438] opened 2022-10-15 10:08 UTC
### Godot version

v4.0.beta3.mono.official [01ae26d31]

### System information

Windows 10

### Issue description

When i am in an input field that has focus and press TAB, the switching to the next field sometimes doesn't work properly. The next field gets the focus marker, but the old field is  still keeping its focus marker and still receives input.

https://user-images.githubusercontent.com/327257/195980637-02a068c1-6514-423e-9c6d-4abf2773148e.mp4

### Steps to reproduce

Select the middle field of any vector3 edit such that it is editable, then press tab. Sometimes it works correctly sometimes it doesn't.

**Comment by KoBeWi** [comment] 2022-10-15 10:20
Duplicate of #37723

**Closed by KoBeWi** 2022-10-15 10:20 UTC
