### ISSUE TITLE
Opening nested array property in remote inspector does not work.

### ISSUE THREAD

**Issue by 01271** [godotengine/godot#42706] opened 2020-10-10 22:49 UTC
**Godot version:**
3.2.2.stable.mono.official

**OS/device including version:**
OSX 10.14.6
GLE3

**Issue description:**
https://i.gyazo.com/0746cd6416d05e3cacc500dcb8a4eeb0.mp4
Attempting to open a dictionary past 1 key deep fails to do so, it flashes open and closes itself.

**Steps to reproduce:**
Create a scene with a variable that's a dictionary several layers deep. Launch the game. Attempt to inspect into the values in that dict.

**Minimal reproduction project:**
[bugreport.zip](https://github.com/godotengine/godot/files/5360374/bugreport.zip)

**Comment by pycbouh** [comment] 2020-10-11 07:26
A duplicate of https://github.com/godotengine/godot/issues/25375.

**Comment by Calinou** [comment] 2020-10-11 12:45
Duplicate of #25375.

**Closed by Calinou** 2020-10-11 12:45 UTC
