### ISSUE TITLE
PinJoint2D created and joined in code seem to be behaving incorrectly.

### ISSUE THREAD

**Issue by ledocool** [godotengine/godot#37387] opened 2020-03-28 19:38 UTC
**Godot version:**
I'm using 3.2.stable.official.

**OS/device including version:**
Windows 10

**Issue description:**
I'm making a chain of rigid bodies sewn together with Pinjoint2D. My idea is to create a "wire" out of those elements and have player interact with it. Problem is, when I create a node structure in the editor everything works as intended. If I try to repeat same node structure with script I get wire pieces flying around the game space and physics engine freaking out.

**Steps to reproduce:**
Create a chain of rigid body with code, add pin joints. Rigid bodies at both ends of the chain should be pinned to static bodies. Static bodies have same parent as rigid bodies and pin joints. In case one of the ends of the chain is not pinned chain links appear one on top of the other as if they're pinned to each other at (0,0).

Then any physics interaction makes the chain links fly around the screen.

**Minimal reproduction project:**
https://www.dropbox.com/s/09hfqtoem19i1p9/space_shooter.zip?dl=0

I tried to strip as much as possible from my current project.
Use right mouse button to propel the ship. The ship will go in direction of your mouse cursor. (it will automatically drag at certain velocity, so don't run too fast)

On the left there's a wire created in the editor. On the right it is created by the code. Try running over them with your ship. Left one strums while the right one goes places.

**Comment by ledocool** [comment] 2020-09-14 02:13
https://github.com/ledocool/godot_pin_joint_bug_demo
I've noticed I removed the file from dropbox, so instead I made a repository with project to reproduce bug.

**Comment by pouleyKetchoupp** [comment] 2020-12-24 00:38
Closing as a duplicate of #30191.

As a workaround, you can set the body positions before adding them to the scene and the joints will work.
```
func _addPiece(parent, piece, coord: Vector2 = Vector2(0, 0), rotation = 0):
	if(parent == null):
		return

	piece.set_rotation(deg2rad(rotation))
	piece.set_position(coord) # set position before adding to scene
	parent.add_child(piece)
	
	return piece
```

**Closed by pouleyKetchoupp** 2020-12-24 00:38 UTC
Labels: bug, topic:physics
