### ISSUE TITLE
Crash in editor when clicking on scene tab

### ISSUE THREAD

**Issue by mitchcurtis** [godotengine/godot#28228] opened 2019-04-20 09:03 UTC
**Godot version:**
v3.1

**OS/device including version:**
MacBook Pro
macOS 10.14.4

**Issue description:**
I had just saved the script file I was working with and then clicked on a scene tab. It wouldn't switch so I clicked a bunch more times and then it crashed.

I doubt this will be reproducible, but a crash is a crash:

```
Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGABRT)
Exception Codes:       EXC_I386_GPFLT
Exception Note:        EXC_CORPSE_NOTIFY

Application Specific Information:
abort() called

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   libsystem_kernel.dylib        	0x00007fff5bfa22c6 __pthread_kill + 10
1   libsystem_pthread.dylib       	0x00007fff5c057bf1 pthread_kill + 284
2   libsystem_c.dylib             	0x00007fff5bf0c6a6 abort + 127
3   org.godotengine.godot         	0x000000010daa7e02 handle_crash(int) + 2898
4   libsystem_platform.dylib      	0x00007fff5c04cb5d _sigtramp + 29
5   ???                           	000000000000000000 0 + 0
6   org.godotengine.godot         	0x000000010e564aa7 EditorSelection::add_node(Node*) + 631
7   org.godotengine.godot         	0x000000010e56472b EditorData::restore_edited_scene_state(EditorSelection*, EditorHistory*) + 251
8   org.godotengine.godot         	0x000000010e64d4a7 EditorNode::set_current_scene(int) + 647
9   org.godotengine.godot         	0x000000010fe52467 MethodBind1<int>::call(Object*, Variant const**, int, Variant::CallError&) + 295
10  org.godotengine.godot         	0x000000010fcd0f63 Object::call(StringName const&, Variant const**, int, Variant::CallError&) + 355
11  org.godotengine.godot         	0x000000010fd59449 UndoRedo::_process_operation_list(List<UndoRedo::Operation, DefaultAllocator>::Element*) + 585
12  org.godotengine.godot         	0x000000010fd5918a UndoRedo::redo() + 170
13  org.godotengine.godot         	0x000000010fd59069 UndoRedo::commit_action() + 57
14  org.godotengine.godot         	0x000000010e62465b EditorNode::_scene_tab_changed(int) + 1739
15  org.godotengine.godot         	0x000000010fe52467 MethodBind1<int>::call(Object*, Variant const**, int, Variant::CallError&) + 295
16  org.godotengine.godot         	0x000000010fcd0f63 Object::call(StringName const&, Variant const**, int, Variant::CallError&) + 355
17  org.godotengine.godot         	0x000000010fcd2e40 Object::emit_signal(StringName const&, Variant const**, int) + 2016
18  org.godotengine.godot         	0x000000010fcd1602 Object::emit_signal(StringName const&, Variant const&, Variant const&, Variant const&, Variant const&, Variant const&) + 114
19  org.godotengine.godot         	0x000000010efbf4f7 Tabs::set_current_tab(int) + 327
20  org.godotengine.godot         	0x000000010efbe903 Tabs::_gui_input(Ref<InputEvent> const&) + 2227
21  org.godotengine.godot         	0x000000010fe37ef0 MethodBind1<Ref<InputEvent> const&>::call(Object*, Variant const**, int, Variant::CallError&) + 304
22  org.godotengine.godot         	0x000000010fccf9a8 Object::call_multilevel(StringName const&, Variant const**, int) + 232
23  org.godotengine.godot         	0x000000010fcd0de3 Object::call_multilevel(StringName const&, Variant const&, Variant const&, Variant const&, Variant const&, Variant const&) + 115
24  org.godotengine.godot         	0x000000010ee337c4 Viewport::_gui_call_input(Control*, Ref<InputEvent> const&) + 756
25  org.godotengine.godot         	0x000000010ee34c78 Viewport::_gui_input_event(Ref<InputEvent>) + 2200
26  org.godotengine.godot         	0x000000010ee324e6 Viewport::input(Ref<InputEvent> const&) + 294
27  org.godotengine.godot         	0x000000010ee322ca Viewport::_vp_input(Ref<InputEvent> const&) + 234
28  org.godotengine.godot         	0x000000010fe37ef0 MethodBind1<Ref<InputEvent> const&>::call(Object*, Variant const**, int, Variant::CallError&) + 304
29  org.godotengine.godot         	0x000000010fcd0f63 Object::call(StringName const&, Variant const**, int, Variant::CallError&) + 355
30  org.godotengine.godot         	0x000000010fcd0d48 Object::call(StringName const&, Variant const&, Variant const&, Variant const&, Variant const&, Variant const&) + 136
31  org.godotengine.godot         	0x000000010ee00ec9 SceneTree::call_group_flags(unsigned int, StringName const&, StringName const&, Variant const&, Variant const&, Variant const&, Variant const&, Variant const&) + 1337
32  org.godotengine.godot         	0x000000010ee025c0 SceneTree::input_event(Ref<InputEvent> const&) + 384
33  org.godotengine.godot         	0x000000010dabc53d InputDefault::_parse_input_event_impl(Ref<InputEvent> const&, bool) + 3165
34  org.godotengine.godot         	0x000000010dabe269 InputDefault::flush_accumulated_events() + 41
35  org.godotengine.godot         	0x000000010dab23f6 OS_OSX::run() + 614
36  org.godotengine.godot         	0x000000010dab513b main + 811
37  libdyld.dylib                 	0x00007fff5be673d5 start + 1

Thread 1:
0   libsystem_kernel.dylib        	0x00007fff5bf9def2 read + 10
1   org.godotengine.godot         	0x000000010dab52e9 SemaphoreOSX::wait() + 25
2   org.godotengine.godot         	0x000000010fed10ec _IP_ResolverPrivate::_thread_function(void*) + 60
3   org.godotengine.godot         	0x000000010e2a38a5 ThreadPosix::thread_callback(void*) + 85
4   libsystem_pthread.dylib       	0x00007fff5c0552eb _pthread_body + 126
5   libsystem_pthread.dylib       	0x00007fff5c058249 _pthread_start + 66
6   libsystem_pthread.dylib       	0x00007fff5c05440d thread_start + 13

Thread 2:
0   libsystem_kernel.dylib        	0x00007fff5bf9def2 read + 10
1   org.godotengine.godot         	0x000000010dab52e9 SemaphoreOSX::wait() + 25
2   org.godotengine.godot         	0x000000010fb0170d VisualServerScene::_gi_probe_bake_thread() + 29
3   org.godotengine.godot         	0x000000010e2a38a5 ThreadPosix::thread_callback(void*) + 85
4   libsystem_pthread.dylib       	0x00007fff5c0552eb _pthread_body + 126
5   libsystem_pthread.dylib       	0x00007fff5c058249 _pthread_start + 66
6   libsystem_pthread.dylib       	0x00007fff5c05440d thread_start + 13

Thread 3:: com.apple.audio.IOThread.client
0   libsystem_kernel.dylib        	0x00007fff5bf9c22a mach_msg_trap + 10
1   libsystem_kernel.dylib        	0x00007fff5bf9c76c mach_msg + 60
2   com.apple.audio.CoreAudio     	0x00007fff2f469eda HALB_MachPort::SendMessageWithReply(unsigned int, unsigned int, unsigned int, unsigned int, mach_msg_header_t*, bool, unsigned int) + 122
3   com.apple.audio.CoreAudio     	0x00007fff2f469e4f HALB_MachPort::SendSimpleMessageWithSimpleReply(unsigned int, unsigned int, int, int&, bool, unsigned int) + 45
4   com.apple.audio.CoreAudio     	0x00007fff2f46639f HALC_ProxyIOContext::IOWorkLoop() + 1017
5   com.apple.audio.CoreAudio     	0x00007fff2f465df4 HALC_ProxyIOContext::IOThreadEntry(void*) + 122
6   com.apple.audio.CoreAudio     	0x00007fff2f465956 HALB_IOThread::Entry(void*) + 72
7   libsystem_pthread.dylib       	0x00007fff5c0552eb _pthread_body + 126
8   libsystem_pthread.dylib       	0x00007fff5c058249 _pthread_start + 66
9   libsystem_pthread.dylib       	0x00007fff5c05440d thread_start + 13

Thread 4:
0   libsystem_kernel.dylib        	0x00007fff5bf9ff32 __semwait_signal + 10
1   libsystem_c.dylib             	0x00007fff5bf2b914 nanosleep + 199
2   org.godotengine.godot         	0x000000010e2a004b OS_Unix::delay_usec(unsigned int) const + 59
3   org.godotengine.godot         	0x000000010e3e8adf EditorExportPlatformAndroid::_device_poll_thread(void*) + 8543
4   org.godotengine.godot         	0x000000010e2a38a5 ThreadPosix::thread_callback(void*) + 85
5   libsystem_pthread.dylib       	0x00007fff5c0552eb _pthread_body + 126
6   libsystem_pthread.dylib       	0x00007fff5c058249 _pthread_start + 66
7   libsystem_pthread.dylib       	0x00007fff5c05440d thread_start + 13

Thread 5:
0   libsystem_kernel.dylib        	0x00007fff5bf9ff32 __semwait_signal + 10
1   libsystem_c.dylib             	0x00007fff5bf2b914 nanosleep + 199
2   org.godotengine.godot         	0x000000010e2a004b OS_Unix::delay_usec(unsigned int) const + 59
3   org.godotengine.godot         	0x000000010e9a3934 EditorFileServer::_thread_start(void*) + 884
4   org.godotengine.godot         	0x000000010e2a38a5 ThreadPosix::thread_callback(void*) + 85
5   libsystem_pthread.dylib       	0x00007fff5c0552eb _pthread_body + 126
6   libsystem_pthread.dylib       	0x00007fff5c058249 _pthread_start + 66
7   libsystem_pthread.dylib       	0x00007fff5c05440d thread_start + 13

Thread 6:: CVDisplayLink
0   libsystem_kernel.dylib        	0x00007fff5bf9f86a __psynch_cvwait + 10
1   libsystem_pthread.dylib       	0x00007fff5c0585a1 _pthread_cond_wait + 773
2   com.apple.CoreVideo           	0x00007fff31758a4b CVDisplayLink::waitUntil(unsigned long long) + 229
3   com.apple.CoreVideo           	0x00007fff31757ffa CVDisplayLink::runIOThread() + 482
4   libsystem_pthread.dylib       	0x00007fff5c0552eb _pthread_body + 126
5   libsystem_pthread.dylib       	0x00007fff5c058249 _pthread_start + 66
6   libsystem_pthread.dylib       	0x00007fff5c05440d thread_start + 13

Thread 7:: com.apple.NSEventThread
0   libsystem_kernel.dylib        	0x00007fff5bf9c22a mach_msg_trap + 10
1   libsystem_kernel.dylib        	0x00007fff5bf9c76c mach_msg + 60
2   com.apple.CoreFoundation      	0x00007fff2f9f013e __CFRunLoopServiceMachPort + 328
3   com.apple.CoreFoundation      	0x00007fff2f9ef6ac __CFRunLoopRun + 1612
4   com.apple.CoreFoundation      	0x00007fff2f9eee0e CFRunLoopRunSpecific + 455
5   com.apple.AppKit              	0x00007fff2d07dd1a _NSEventThread + 175
6   libsystem_pthread.dylib       	0x00007fff5c0552eb _pthread_body + 126
7   libsystem_pthread.dylib       	0x00007fff5c058249 _pthread_start + 66
8   libsystem_pthread.dylib       	0x00007fff5c05440d thread_start + 13

Thread 8:
0   libsystem_kernel.dylib        	0x00007fff5bf9def2 read + 10
1   org.godotengine.godot         	0x000000010dab52e9 SemaphoreOSX::wait() + 25
2   org.godotengine.godot         	0x000000010e70775d EditorResourcePreview::_thread() + 109
3   org.godotengine.godot         	0x000000010e2a38a5 ThreadPosix::thread_callback(void*) + 85
4   libsystem_pthread.dylib       	0x00007fff5c0552eb _pthread_body + 126
5   libsystem_pthread.dylib       	0x00007fff5c058249 _pthread_start + 66
6   libsystem_pthread.dylib       	0x00007fff5c05440d thread_start + 13

Thread 9:
0   libsystem_pthread.dylib       	0x00007fff5c0543f0 start_wqthread + 0

Thread 10:
0   libsystem_pthread.dylib       	0x00007fff5c0543f0 start_wqthread + 0

Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0x0000000000000000  rbx: 0x00000001164c85c0  rcx: 0x00007ffee2156db8  rdx: 0x0000000000000000
  rdi: 0x0000000000000307  rsi: 0x0000000000000006  rbp: 0x00007ffee2156df0  rsp: 0x00007ffee2156db8
   r8: 0x00000000000130a8   r9: 0x00007fff8ee61048  r10: 0x0000000000000000  r11: 0x0000000000000206
  r12: 0x0000000000000307  r13: 0x0000000000000023  r14: 0x0000000000000006  r15: 0x000000000000002d
  rip: 0x00007fff5bfa22c6  rfl: 0x0000000000000206  cr2: 0x00007fff8ee5f188
  
Logical CPU:     0
Error Code:      0x02000148
Trap Number:     133
```

**Comment by mitchcurtis** [comment] 2019-04-20 09:05
Aaaand I just realised that it deleted a bunch of my nodes. Great.

**Comment by Calinou** [comment] 2020-07-19 19:54
@mitchcurtis  Can you (or anyone else) still reproduce this bug in Godot 3.2.2 or any later release?

If yes, please ensure that an up-to-date Minimal Reproduction Project (MRP) is included in this report (a MRP is a zipped Godot project with the minimal elements necessary to reliably trigger the bug). You can upload ZIP files in an issue comment with a drag and drop.

**Comment by KoBeWi** [comment] 2020-10-18 12:09
Closing due to lack of update. Please comment if you can still reproduce this issue in the latest stable version of Godot.

**Closed by KoBeWi** 2020-10-18 12:09 UTC
Labels: bug, crash, topic:editor
