### ISSUE TITLE
Exported arrays and dictionaries which are initialized are not displaying initialized values in inspector

### ISSUE THREAD

**Issue by yhwhey** [godotengine/godot#64602] opened 2022-08-19 03:43 UTC
### Godot version

4.0.alpha14

### System information

MacOS Monterey

### Issue description

Context:

Creating a custom resource type with an exported member of array or dictionary type
Initializing exported member of either of those types with a value
e.g. 
@export
var exported_array : Array[int] = [1, 2, 3, 4]

Issue:

Initialized value are not being displayed in inspector for a resource of that custom type.
Confirmed that variable is being initialized properly. It's just not displaying in the inspector

### Steps to reproduce

See attached project

### Minimal reproduction project

[export_issue.zip](https://github.com/godotengine/godot/files/9379031/export_issue.zip)

**Comment by Calinou** [comment] 2022-08-19 14:35
Duplicate of https://github.com/godotengine/godot/issues/62753.

**Closed by Calinou** 2022-08-19 14:35 UTC
Labels: bug, topic:gdscript, topic:editor
