### ISSUE TITLE
Make certain views deattachable to a separate window for multiple displays

### ISSUE THREAD

**Issue by wingedadventurer** [godotengine/godot#21082] opened 2018-08-16 14:34 UTC
I am using 2 monitors and the potential of second monitor is wasted because all Godot's views are in one window only.

I believe adding an ability to detach certain views and make them separate windows would solve this problem.

Some use cases:

- Script view on display A, 2D/3D view on display B (removes the need to switch between main views) (**see example image below**)
- Scene A on display A, scene B on display B (removes the need to switch between scenes)
- Scripts on display A, documentation on display B (removes the need to switch between scripts and documentation pages)

![godot-displays](https://user-images.githubusercontent.com/26509794/44215823-bf718900-a173-11e8-8df7-99e724f28756.png)

**Comment by akien-mga** [comment] 2018-08-16 14:52
Duplicate of #9059, not possible for now as Godot does not support multiple windows.

**Closed by akien-mga** 2018-08-16 14:52 UTC
