### ISSUE TITLE
parse_json() doesn't support Rect2 saved from to_json()

### ISSUE THREAD

**Issue by nobuyukinyuu** [godotengine/godot#20752] opened 2018-08-06 01:59 UTC
**Godot version:**
3.0.6 stable

**Issue description:**
What it says in the title.  When saving Rect2s using to_json(), the output value format appears as follows:
`"(x,y,w,h)"`

However, when re-importing, the de-serializing function doesn't check the string to see if it conforms to this data format and convert back to Rect2 natively.  It imports as a simple string.  This may affect other built-in data structures;  I haven't tried them all.

Possible Workaround so as to not break compatibility:  Add a constructor to Rect2 that takes a string in this format.

**Comment by bojidar-bg** [comment] 2018-08-06 06:32
Duplicate of #11866.

**Closed by bojidar-bg** 2018-08-06 06:32 UTC
