### ISSUE TITLE
Godot will not startup from project manager if the default terminal application is set to Windows Terminal in Windows 11

### ISSUE THREAD

**Issue by Xwdit** [godotengine/godot#54076] opened 2021-10-21 16:02 UTC
___

***Bugsquad note:** This issue has been confirmed several times already. No need to confirm it further.*

___

### Godot version

4.0.dev(fad7034e8b)

### System information

Windows 11

### Issue description

Godot will not startup from project manager if set the default terminal software to Windows Terminal in Windows 11, it will close immediately

### Steps to reproduce

1. Change the default terminal application from cmd to Windows Terminal in Windows Terminal Settings.
2. Try to open a project in Godot's project manager
3. Godot window close immediately like a crash

**Comment by Calinou** [comment] 2021-10-21 16:13
As a workaround, compile Godot with `windows_subsystem=gui` on the SCons command line. This will disable the console entirely (which means you won't be able to toggle it back on).

**Comment by cybereality** [comment] 2021-11-03 09:19
I am able to reproduce this consistently on 2 machines with Windows 11. The setting that messes it up is this:

![image](https://user-images.githubusercontent.com/3398643/140033589-5d27930c-a0b8-4af3-9ffd-75501fcbe7bb.png)
****

While "Windows Console Host" is the default, if you change the "Default terminal application" to "Windows Terminal" (which Microsoft prompts you to do, so may be a common issue). Then Godot immediately closes once opening a project. Note, this happens even on the latest stable build 3.3.4 as well. 

Interestingly, it only happens when opening Godot by double-clicking the exe in the file explorer, or by clicking a shortcut (for example, if you have an icon on your taskbar, which I imagine is common for Windows users). If you manually open a command prompt or the Windows Terminal, and launch Godot from there, then it works fine.

If I had to guess, Godot isn't crashing. Maybe the default behavior of the Windows Terminal closes early (when whatever Godot does to switch from project manager mode to editor mode) and it is the terminal closure that is causing Godot to exit (which is why it works fine with a manually opened terminal).

**Comment by MarioLiebisch** [comment] 2021-11-05 18:52
Just wanted to mention that while I can observe the very same issue on the 3.4 stable (Steam install) I don't get the issue with latest 4.0 compiled from scratch, using the Terminal Preview from Microsoft Store. I actually don't remember 4.0 ever showing this behavior since switching to Windows 11 (and Terminal Preview as the default) a month ago.

However, there's a different thing going on:
When I open 4.0 from Explorer, I'll get a terminal window and the Project Manager (as expected). Now if I open a project, the project opens fine, but the terminal window will close, showing no console output for the editor (the setting to hide the console window is off).

**Comment by robpc** [comment] 2021-11-07 11:39
I this issue and changing the setting back to `Windows Console Host` fixes it. The odd thing is that I have has `Windows Terminal` set as the default for a year-ish but this issue only came up in the last few days. I also have this issue with `3.3.2`, `3.3.3` and `3.3.4`, as well as `3.4`.

**Comment by MarioLiebisch** [comment] 2021-11-07 12:54
> The odd thing is that I have has `Windows Terminal` set as the default for a year-ish but this issue only came up in the last few days.
Think you're confusing something here. As far as I know, this functionality is rather new (it arrived in the Terminal's stable branch just recently (after Windows 11's launch). Before it was in the preview branch for a month or two I think.

**Comment by robpc** [comment] 2021-11-07 13:07
> Think you're confusing something here. As far as I know, this functionality is rather new (it arrived in the Terminal's stable branch just recently (after Windows 11's launch). Before it was in the preview branch for a month or two I think.

Ahh, perhaps. I have been using it as my default terminal for a long time so maybe that was an assumption about the setting. On the other hand, I haven't touched the settings in months. Was an update for that pushed out in the last three days that turned it on by default? (I would believe it lol)

**Comment by MarioLiebisch** [comment] 2021-11-07 13:10
Windows Terminal (the non-preview version) was updated on 28th October for me. I think it's the first non-preview version actually supporting to become the system default.

**Comment by robpc** [comment] 2021-11-07 13:13
Mine was modified 10/31. Probably been broken since then... that seems possible based on my recent Godot usage.

**Comment by Fr0sk** [comment] 2021-11-08 11:24
If I run it as an admin it seems to work fine. So, as a quick(er) workaround, you could check "Run this program as an administrator" and keep the Windows Terminal as the default terminal.

**Comment by Netito77** [comment] 2021-11-09 18:19
> If I run it as an admin it seems to work fine. So, as a quick(er) workaround, you could check "Run this program as an administrator" and keep the Windows Terminal as the default terminal.

I tried to run as an administrator, but the program ended up closing anyway. No results. :\

**Comment by marekadamczyk** [comment] 2021-11-14 13:28
If anyone would still like to use the Windows Terminal below batch script is working as a workaround till version 4.0 will be released:

@echo off
taskkill /im openconsole.exe > NUL
Godot_v3.4-stable_win64.exe
set /p GODOT=

**Comment by Listwon** [comment] 2021-11-26 10:19
I don't have much time to experiment right now, but one thing that is worth testing, would be to use `CreateProcessW()` instead of `_wpopen()` in `OS_Windows::execute()`. Because there are some caveats of using `_wpopen` as we can read in the documentation
https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/popen-wpopen?view=msvc-170
https://docs.microsoft.com/en-us/windows/win32/api/processthreadsapi/nf-processthreadsapi-createprocessw

I confirm the issue on my side too. Windows Terminal set as default terminal application. If I start the Godot binary from the Terminal itself, it opens projects properly.

**Comment by JohnCWakley** [comment] 2021-11-26 23:25
> 

When I try to use that compile option, I get the following:

$ scons -j16 platform=windows target=release_debug windows_subsystem=gui
scons: Reading SConscript files ...
WARNING: Unknown SCons variables were passed and will be ignored:
    windows_subsystem=gui
Configuring for Windows: target=release_debug, bits=default
Found MSVC version 14.2, arch amd64, bits=64
Checking for C header file mntent.h... (cached) no
scons: done reading SConscript files.
scons: Building targets ...

**Comment by MarioLiebisch** [comment] 2021-11-26 23:39
> one thing that is worth testing, would be to use `CreateProcessW()` instead of `_wpopen()` in `OS_Windows::execute()`.

Had a bit of time earlier today, so removed the whole section using `_wpopen()` and added the pipe handling to the `CreateProcessW()` section, but it's still failing/exiting (with stdout being properly redirected), so it's most likely not the function call or it's something related to the pipes themselves. Or I made some mistake, but it's closing properly without any issues or crashing.

```
Godot Engine v4.0.dev.custom_build.8f0c6ce72 - https://godotengine.org
Vulkan API 1.2.189 - Using Vulkan Device #0: NVIDIA - NVIDIA GeForce GTX 1080

Editing project: Project/Path (Project::Path)
Godot Engine v4.0.dev.custom_build.8f0c6ce72 - https://godotengine.org
Vulkan API 1.2.189 - Using Vulkan Device #0: NVIDIA - NVIDIA GeForce GTX 1080

[Verarbeitung des Prozesses mit Code 0 (0x00000000) beendet]
```

**Comment by Irido-nyto** [comment] 2021-12-12 10:11
I hava found a solution, add CREATE_NEW_CONSOLE flag to [here](https://github.com/godotengine/godot/blob/092a2861277e7df87aec10516d713d0bf4adba79/platform/windows/os_windows.cpp#L483)

Here's a Microsoft document that explains the problem:
    [Creation of a console](https://docs.microsoft.com/en-us/windows/console/creation-of-a-console)

Please note this sentence in parentheses:

> By default, a console process inherits its parent's console, and there is no guarantee that input is received by the process for which it was intended.

The reason for the issue is obvious, the editor process created by the project manager inherits the console of project manager, but the consle process exited after the project manager was quited, so the editor process was closed along with the consle process.

**Comment by bruvzg** [comment] 2021-12-12 10:33
> I hava found a solution, add CREATE_NEW_CONSOLE flag to here

Or add `DETACHED_PROCESS`, but neither is a good solution, `CREATE_NEW_CONSOLE` will open a new console window for every started process (including tools used during the export and running on the background, like `adb`), and `DETACHED_PROCESS` will disable console for the editor.

Probably the best we can do is to force `windows_subsystem=gui` and open a new console for the editor instances only, using `AllocConsole`.

> but the consle process exited after the project manager was quited, so the editor process was closed along with the consle process.

Exiting project manager is the reason, but it should not happen, it's a new terminal bug. The console should stay opened until the last attached process is terminated. 

https://docs.microsoft.com/en-us/windows/console/closing-a-console

> ... If other processes share the console, the console is not destroyed, ...
> ... A console is closed when the last process attached to it terminates or calls FreeConsole.

**Closed** 2021-12-14 14:44 UTC
Labels: bug, platform:windows, topic:porting, confirmed

**Comment by mhilbrunner** [comment] 2021-12-15 03:32
> Exiting project manager is the reason, but it should not happen, it's a new terminal bug. The console should stay opened until the last attached process is terminated.

Seems they changed that in Windows Terminal, it only tracks the first attached process and exits once that exits:
https://github.com/microsoft/terminal/issues/10501

**Comment by trevorwinser** [comment] 2024-06-15 23:21
Has anyone found a stable solution for this via the terminal?

**Comment by MarioLiebisch** [comment] 2024-06-16 06:04
Whatever your issue is, I don't think this is related. This issue has been fixed long time ago (and I even forgot it existed).

**Comment by Pjdn98** [comment] 2024-10-10 02:21
Estou tendo esse tipo de problema no Godot 4
