### ISSUE TITLE
C# Can't add elements to exported list

### ISSUE THREAD

**Issue by Polyfish0** [godotengine/godot#73379] opened 2023-02-15 17:03 UTC
### Godot version

4.0.dev (d2699dc7a)

### System information

Windows 10 22H2 (Build 19045.2604), RTX 2070 Super (528.49 Game Ready Driver)

### Issue description

In the video I showed my problem. When I export in C# a Node2D Array and then want to fill it from the editor, the only thing that works is to set the array size. But I can not put any elements into it.
https://user-images.githubusercontent.com/38872139/219101398-caa456ba-149c-476c-a80b-3318e469bd57.mp4
Because the upload do not work for me (just a black video) I uploaded it to YouTube: https://youtu.be/m3EO0xoCHhU

### Steps to reproduce

```
    using Godot;

    public partial class NarutoEnemy : Node2D
    {
        [Export] private Node2D[] _waypoints;
        // Called when the node enters the scene tree for the first time.
        public override void _Ready()
        {
            foreach (Node2D node in _waypoints)
            {
                GD.Print(node == null);
            }
        }
    
        // Called every frame. 'delta' is the elapsed time since the previous frame.
        public override void _Process(double delta)
        {
        }
    }
```

### Minimal reproduction project

N/A

**Comment by Polyfish0** [comment] 2023-02-15 17:16
btw I had the console on my second screen open and I got no traceback

**Comment by raulsntos** [comment] 2023-02-15 17:36
Duplicate of https://github.com/godotengine/godot/issues/62916

**Closed by raulsntos** 2023-02-15 17:36 UTC
