### ISSUE TITLE
`MeshInstance3D` disappears at runtime if its skeleton is not a direct parent

### ISSUE THREAD

**Issue by MajorMcDoom** [godotengine/godot#97459] opened 2024-09-25 16:30 UTC
### Tested versions

Reproducible in 4.3.stable and 4.4.dev2
**NOT** reproducible in 4.2.stable

### System information

Godot v4.3.stable - Windows 10.0.22631 - GLES3 (Compatibility) - NVIDIA GeForce GTX 1660 SUPER (NVIDIA; 32.0.15.6109) - Intel(R) Core(TM) i7-10700F CPU @ 2.90GHz (16 Threads)

### Issue description

When a `MeshInstance3D`'s skeleton is not a direct parent, it works fine in editor, but at runtime, the mesh disappears. This worked previously in `4.2`. In the attached video, the red fish has the skeleton under the mesh, the green fish has the mesh under the skeleton, and the blue fish has skeleton and mesh as siblings. When you run the game, the red fish and the blue fish disappear.

https://github.com/user-attachments/assets/d515c724-bc86-4996-bcf8-04696d870107

### Steps to reproduce

- Open `test.tscn` in the attached project
- Run the game
- Observe that only the green fish remains

### Minimal reproduction project (MRP)

[bug-report.zip](https://github.com/user-attachments/files/17134814/bug-report.zip)

**Comment by akien-mga** [comment] 2024-09-25 16:53
CC @TokageItLab

**Comment by fire** [comment] 2024-09-25 18:18
Wait a second, is the root node a Node, will that cause trouble compared to a Node3D? I remember something didn't act well without a path that is Node3D.

**Comment by MajorMcDoom** [comment] 2024-09-25 19:47
> Wait a second, is the root node a Node, will that cause trouble compared to a Node3D? I remember something didn't act well without a path that is Node3D.

The bug appears regardless.
But in any case, this was working fine in 4.2, and I have been using it all over the place in my project, so I'm not sure what changed.

**Comment by fire** [comment] 2024-09-25 22:34
I have no idea. The standard procedure for debugging a regression is to run git-bisect until godot starts working again.

**Comment by TokageItLab** [comment] 2024-09-26 02:31
If the Skeleton change is having an effect, it may be because the SkeletonModifier implementation has reduced unnecessary duplicated Skin updates in the Skeleton and only does it once in the deferred process. However, I think this should not be reverted back to the old Skin updating way from a performance standpoint.

One thing I noticed is that when the Mesh and Skeleton are siblings, like the blue fish, the rendering works when the Skeleton is first. However, changing ProcessPriority has no effect. (I assume this is because the Deferred process does not affect ProcessPriority)

So I think the right direction would be to make some call to Skin in `RenderingServer::skeleton_bone_set_transform()`, or do it in Skeleton before `rs->skeleton_bone_set_transform()` line.

However, in my opinion, MeshInstance not being a child of a Skeleton is a pretty niche case, and I think it's not so worth to deal with that case by reducing the performance. Probably the ability to assign any non-ancestor Skeleton to a MeshInstance should be discontinued, although it breaks compatibility. How do you think about it? @reduz

**Comment by TokageItLab** [comment] 2024-09-26 02:45
Or the problem may be that Skin is discarded by the rendering server before the deferred process. If so, making it retain it might solve everything, but I am not familiar with rendering servers so I am not sure. Do you have any ideas? @clayjohn

**Comment by clayjohn** [comment] 2024-09-26 02:54
> Or the problem may be that Skin is discarded by the rendering server before the deferred process. If so, making it retain it might solve everything, but I am not familiar with rendering servers so I am not sure. Do you have any ideas? @clayjohn

I don't think anything has changed in the rendering server that would impact this. Note, the RenderingServer has no concept of Skin, it just takes the list of bones from the skeleton and uses it to transform the mesh, nothing in the node hierarchy should impact the RenderingServer either as it doesn't reference the node hierarchy anywhere

**Comment by clayjohn** [comment] 2024-09-26 03:35
> @clayjohn My thinking is that the MeshInstance is rendered without the skeleton, so when the MeshInstance is iterated by SceneTree, the mesh is registered with the rendering server and drawn.
> 
> Then, I expected that if the skeleton is first, the result of applying the skeleton's bone transformation will be rendered, but if the skeleton is later and the process is deferred, the MeshInstance has already been rendered, and if the skeleton's bone transformation is newly passed to it and the past drawing of the MeshInstance would disappear, is that not the case?

No, the renderer doesn't work that way. The entire scene system executes before rendering even starts. The calls to the RenderingServer just register resources with the RenderingServer, then at the end of the frame, the RenderingServer takes all the resources and draws them. 

Even if you defer an update of the skeleton, the update will happen before anything is drawn. The order in the scene tree has no impact on drawing

**Comment by TokageItLab** [comment] 2024-09-26 04:34
If the Deferred process and its order in the scene tree is not directly related to the render server, then this issue is quite mysterious.

We know that it is Skeleton that has _process, and found that the order of Mesh and Skeleton in the scene tree has an effect, but Process Priority does not, so it is doubtful that it is even a process order issue.

If we can confirm that somewhere in the process of passing Skin and Bone information to the render server in Skeleton changes depending on the order in the scene tree, it may help to solve the problem, but we will have to investigate in detail.

**Comment by MajorMcDoom** [comment] 2024-09-26 04:46
> If the Deferred process and its order in the scene tree is not directly related to the render server, then this issue is quite mysterious.
> 
> We know that it is Skeleton that has _process, and found that the order of Mesh and Skeleton in the scene tree has an effect, but Process Priority does not, so it is doubtful that it is even a process order issue.
> 
> If we can confirm that somewhere in the process of passing Skin and Bone information to the render server in Skeleton changes depending on the order in the scene tree, it may help to solve the problem, but we will have to investigate in detail.
> 
> For now, the workaround I can say at this point is, if the Skeleton and MeshInstance are siblings, always put the Skeleton above the MeshInstance in the SceneTree. If the Skeleton is a child of the MeshInstance, the structure must be changed.

If it helps at all, I have some other MI3D in my game with skeleton children that ARE working properly, though I have no idea what the differentiating factor is. Every time I try to repro a working case from scratch, it just ends up not working.

**Comment by TokageItLab** [comment] 2024-09-26 05:07
If there is a difference in the project, it could be the Skin importing way and where it is stored, since only the runtime has problems, it is feasible that the init process is being affected by them. For example, depending on the order of Skeleton and Mesh declarations, the Skin may be shrinking oddly in the init process.

**Comment by MajorMcDoom** [comment] 2024-09-26 05:14
> If there is a difference in the project, it could be the Skin importing way and where it is stored, since only the runtime has problems, it is feasible that the init process is being affected by them. For example, depending on the order of Skeleton and Mesh declarations, the Skin possibly be shrinking oddly in the init process.

Interesting. Is there a rule of thumb for where I should be storing the skin to avoid this? I honestly don't know much about how all these pieces come together, the documentation is pretty sparse.

**Comment by TokageItLab** [comment] 2024-09-26 05:56
In my experience, there have been cases where some CSG software has bound a Skin with an oddly small scale to a seemingly correct bone, but this is probably not the case with MRP.

One case I can think of where a mesh would be invisible is when a Skeleton is specified in the MeshInstance and a new Skin is assigned to it. Possibly the init process does not handle the Skin binding information correctly and this is causing such a situation.

**Closed** 2024-09-27 11:55 UTC
Labels: bug, regression, topic:animation, topic:3d
