### ISSUE TITLE
`LineEdit` prevents itself from entering text after pressing enter.

### ISSUE THREAD

**Issue by MataKrow** [godotengine/godot#97088] opened 2024-09-16 18:46 UTC
### Tested versions

Reproducible in: v4.4.dev.custom_build [6681f2563]
Not Reproducible in: v4.4.dev2.official [97ef3c837]

### System information

Windows 10 - Godot v4.4.dev.custom_build [6681f2563] - OpenGL (Compatibility) - Integrated

### Issue description

After [#87674](https://github.com/godotengine/godot/pull/87674), `LineEdit` needs to be pressed twice with enter before text could be entered again. 

This impacts usability with a developer console addon I've been using and there's no available function or variable now to toggle into edit mode from the instanced `LineEdit`.

### Steps to reproduce

Play the MRP
Input Text
Submit by pressing enter
`LineEdit` is now unresponsive until enter is pressed for a second time.

### Minimal reproduction project (MRP)

[lineedit_console.zip](https://github.com/user-attachments/files/17017814/lineedit_console.zip)

**Comment by WhalesState** [comment] 2024-09-16 20:45
I have found a workaround to this.

Inside consolde.gd

```gdscript
func on_text_entered(new_text : String) -> void:
	line_edit.release_focus()
	line_edit.grab_focus.call_deferred()
```

I also can change this to the old behavior optionally by not allowing the `LineEdit` to exist edit mode by pressing enter, but this will require pressing Escape after submitting text to easily navigate to other `LineEdit` properties in Editor.

The best way is to add `LineEdit.keep_editing_on_text_submit` and it will be false by default, to avoid changing all the editor cpp scripts that are using the `LineEdit`.

**Comment by WhalesState** [comment] 2024-09-16 20:54
I Just don't understand why this was marked as a release blocker.

Is The `LineEdit` meant to be used for such console input by default? This is a rare case that can even be fixed in gdscript :).

The Godot Editor is heavely using the `LineEdit` for "Search", "Properties" and "Event Listeners" with no issues.

**Comment by AThousandShips** [comment] 2024-09-16 20:57
It's a regression, with unexpected changes in behavior, unless this specific behavior was intentional (can't see anything in your PR that says this explicit behavior was intended) then that's an issue

**Comment by WhalesState** [comment] 2024-09-16 21:12
This can be solved by:

1- Revert the old behavior for text submitting with `Enter` key.

2- Add `keep_editing_on_text_submit`:
- default = false ? This will not require any modification for Godot Editor.
- default = true ? This will result in an extra line for all the editor scripts that uses the `LineEdit`.

3- Expose `_edit()` and `_unedit` to gdscript as functions `LineEdit.edit`, `LineEdit.unedit` and we enhance the document.

You can choose how this should be fixed.

**Comment by WhalesState** [comment] 2024-09-16 23:04
https://github.com/godotengine/godot/pull/97094 will allow you to use `edit.call_deferred()` after text submitting, instead of using `release_focus()` and `grab_focus.call_deferred()`.

**Comment by Lippanon** [comment] 2024-09-16 23:11
Using v4.4.dev.custom_build [6681f2563], likely the same problem: when searching for text in the text editor (ctrl+f by default), advancing to the next match with Enter now requires two key presses. To be clear, I'm reffering to this:
![image](https://github.com/user-attachments/assets/f30ad417-fdeb-4478-98d4-9d0ee80665f7)
If it's not related, I can open a new issue tomorrow.

**Comment by WhalesState** [comment] 2024-09-16 23:59
> likely the same problem: when searching for text in the text editor (ctrl+f by default), advancing to the next match with Enter now requires two key presses.

Good catch, I already have fixed it, I will test it locally and then will create a pull request.

**Comment by WhalesState** [comment] 2024-09-17 00:32
Both issues was fixed.

**Closed** 2024-10-04 15:23 UTC
Labels: bug, regression, topic:gui
