### ISSUE TITLE
Bad separation of KinematicBody2D move against LineShape2D

### ISSUE THREAD

**Issue by eon-s** [godotengine/godot#9332] opened 2017-06-23 12:07 UTC
**Godot version: 2.1.3**

**Issue description:**
Moving a KinematicBody2D (as in `move`) against a solid body with a LineShape2D, seems to not separate the body correctly leading to continuous collisions.
![badkb-line](https://user-images.githubusercontent.com/10215987/27481388-b74d838a-57f2-11e7-9994-73c8b17a5a56.gif)

**Steps to reproduce:**
Move a KinematicBody2D against a line and try to move it again in the opposite direction.
Forcing a separation (with `set_pos`) lead to the correct behaviour.

**Link to minimal example project:**
[kb2dbadlineseparation.zip](https://github.com/godotengine/godot/files/1097690/kb2dbadlineseparation.zip)

Probably related to this #7920 ?

**Comment by eon-s** [comment] 2017-11-13 00:15
Affects master too.

Example for godot 3:
[kbbadlineseparationv3.zip](https://github.com/godotengine/godot/files/1465230/kbbadlineseparationv3.zip)

**Comment by kubecz3k** [comment] 2018-04-03 11:30
First of all thank you for your report and sorry for the delay.

We released Godot 3.0 in January 2018 after 18 months of work, fixing many old issues either directly, or by obsoleting/replacing the features they were referring to.

We still have hundreds of issues whose relevance/reproducibility needs to be checked against the [current stable version](https://godotengine.org/download), and that's where you can help us.
**Could you check if the issue that you described initially is still relevant/reproducible in Godot 3.0 or any newer version, and comment about its current status here?**

For bug reports, please also make sure that the issue contains detailed steps to reproduce the bug and, if possible, a zipped project that can be used to reproduce it right away. This greatly speeds up debugging and bugfixing tasks for our contributors.

Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

Thanks in advance.

*Note: This message is being copy-pasted to many "stale" issues (90+ days without activity). It might happen that it is not meaningful for this specific issue or appears oblivious of the issue's context, if so please comment to notify the Bugsquad about it.*

**Comment by eon-s** [comment] 2018-04-03 12:28
This issue is still valid for 3.0.2 and current master builds.

**Comment by eon-s** [comment] 2018-09-08 22:43
This _may_ be a similar case to `PlaneShape` shapes on spatials (where planes cannot be used for bodies), in that case this needs to be documented and a (runtime) warning can be added if the `PhysicsBody2D` notices that is using a `LineShape2D` instead of a `SegmentShape2D`.

**Comment by reduz** [comment] 2018-11-02 20:05
PlaneShape will be removed in the next compatibility breakage (and likely LineShape too) due to how difficult it is to make it work in other physics engines, so kicking to 3.2/4.0 where it will most likely be removed.

**Comment by eon-s** [comment] 2018-11-05 12:44
@reduz maybe a deprecation warning could be added when using this kind of shapes, so projects and docs/tutorials start avoiding their use

**Comment by madmiraal** [comment] 2020-10-03 14:14
Fixed in 3.1. I'm able to reproduce the problem in 3.0.6-stable, but not with 3.1-stable.

**Closed by madmiraal** 2020-10-03 14:14 UTC
Labels: bug, confirmed, topic:physics
