### ISSUE TITLE
 weird normal map when set by shader

### ISSUE THREAD

**Issue by zoiba** [godotengine/godot#2991] opened 2015-12-04 18:52 UTC
here two copy of the same model sharing the same normal map with the only exception of how it is assigned to them. There is a directional light, set to 45 degree, who is lighting the scene.
Normal map on the left model is set by using built-in fixed material while the normal map on the right model is set by using a shader material like this:
uniform texture normal_map;
NORMALMAP = tex(normal_map, UV).xyz;
NORMALMAP_DEPTH = 1;

as you can notice the model with fixed material looks natural while it is revolving while the model with shader material shows a weird shading artefact, a bit like if the light was moving vertically.

here the test case project: http://ffxrunner2.ffx.it/godot_testcases/normalMap_testcase.zip

and here a video showing the issue: https://youtu.be/J2-jXHsTvI4

**Comment by Ace-Dragon** [comment] 2015-12-05 21:37
Right now, you can string the normal map through a couple of nodes to get a pretty close approximation to a proper normal map
![godot_normals](https://cloud.githubusercontent.com/assets/10081256/11610342/cc5cc3b2-9b65-11e5-9d12-ee3c06d21e74.jpg)

Though I do agree it would be nice to simply plug the map into the input and see it looking nice and correct (would make things a bit easier for most people).

**Comment by nunodonato** [comment] 2017-03-13 13:30
is this still valid?

I can't test the project because the file is no longer available, but in my recent projects I never encountered this

**Comment by zoiba** [comment] 2017-03-13 21:33
sorry, there was a mistake in writing link url. the file is still there http://ffxrunner2.ffx.it/godot_testcases/normalMap_testcase.zip

**Comment by nunodonato** [comment] 2017-03-26 20:16
Confirmed in current 2.1.2, there are differences both in editor and in-game.

**Comment by akien-mga** [comment] 2018-09-17 13:31
The 2.1 branch is no longer actively worked by engine developers, unless critical fixes are needed for current games in production. As such we are now closing non-critical bug reports affecting only the 2.1 branch.

Please comment if this was incorrectly triaged and is still relevant in 3.x versions.

**Closed by akien-mga** 2018-09-17 13:31 UTC
Labels: bug, confirmed, topic:core
