### ISSUE TITLE
Info Box Hide & Show Over And Over Again

### ISSUE THREAD

**Issue by johanessurya** [godotengine/godot#2436] opened 2015-09-06 17:01 UTC
When I want to move order node list. Info box is hide & show over and over again. Here the screenshot that I mean:
![godot-hover-menu-box](https://cloud.githubusercontent.com/assets/2444537/9705587/70cde8ea-54f3-11e5-8d9f-0666bcb06c95.jpg)

What I mean 'Info Box' is text in the box 'Reparent Selected Node(s)'. It hide & show when I hover on it.

**Comment by AlexHolly** [comment] 2015-09-06 19:01
Is it version 1.1 stable?
https://github.com/okamstudio/godot/issues/1959

**Comment by johanessurya** [comment] 2015-09-06 19:53
Yes, 1.1 stable 64bit. 

I use
Windows 7 Pro 64bit

**Comment by akien-mga** [comment] 2015-11-09 12:48
Duplicate of #1959.

**Closed by akien-mga** 2015-11-09 12:48 UTC
Labels: archived
