### ISSUE TITLE
Reference to class (or inner class) is not considered a constant expression

### ISSUE THREAD

**Issue by dsnopek** [godotengine/godot#61636] opened 2022-06-02 15:20 UTC
### Godot version

v4.0.alpha9.official.fc18891db

### System information

Linux, Vulkan, 1070M

### Issue description

I've been working on porting the Nakama client to Godot 4. In Godot 3, it uses this pattern where there's a bunch of "namespaces" (*.gd scripts with lots of inner classes - they are automatically generated from Swagger definitions).

When working with a project like this, it can be helpful to "alias" a class into the local "namespace" using `const`, for example like:

```gdscript
const InnerClass1 = MyNamespace.InnerClass1
```

This works fine in Godot 3.x, but in Godot 4.x, I get this error in the editor (and at runtime):

```
Initializer for a constant must be a constant expression.
```

However, this doesn't just apply to inner classes, or classes registered with `class_name`, but all classes!

### Steps to reproduce

I've included a minimal reproduction project below, but here is the key code (from the Main.gd in the project) to illustrate the problem:

```gdscript
extends Node2D

class Class1:
	pass

# All of these work in Godot 3.x, but not Godot 4.x!
const Class1Alias = Class1
const MyNamespaceAlias = MyNamespace
const InnerClass1 = MyNamespace.InnerClass1
```

### Minimal reproduction project

[godot-4-const-class-bug.zip](https://github.com/godotengine/godot/files/8825227/godot-4-const-class-bug.zip)

**Comment by mashumafi** [comment] 2023-02-21 03:44
I was not able to reproduce this issue. I created a test to prevent future regression.

**Comment by akien-mga** [comment] 2023-02-21 06:29
Closing as fixed.

**Closed by akien-mga** 2023-02-21 06:29 UTC
Labels: bug, topic:gdscript, regression
