### ISSUE TITLE
Bullet: Bumpy RigidBody to static trimesh collisions

### ISSUE THREAD

**Issue by cosmicchipsocket** [godotengine/godot#21341] opened 2018-08-24 02:40 UTC
**Godot version:**
2db494267b2924989900e968bdb898d8ab50c8f5

**OS/device including version:**
Arch Linux (rolling release)

**Issue description:**
Collisions between basic Bullet primitives and trimesh collision shapes generated from an imported model cause sliding objects to pop into the air whenever they cross triangle boundaries. I would expect the object to slide smoothly over the mesh. Until this is fixed I can't really work on my game any further.

![bumpytrimeshcollision](https://user-images.githubusercontent.com/34800072/44561977-58c90e00-a725-11e8-8704-c2b729abbf17.gif)
(This GIF shows the puck falling through the floor. I know this is already covered by #20408, but I am experiencing problems beyond that issue's scope)

I tried changing the margin on both the puck and the trimesh, but this only made problems worse.

**Steps to reproduce:**
Download example project, hold Space for a bit, then release

**Minimal reproduction project:**
[bumpy_trimesh_collision.zip](https://github.com/godotengine/godot/files/2316822/bumpy_trimesh_collision.zip)

**Comment by AndreaCatania** [comment] 2018-08-26 10:28
Can you try to split all parts, and make a smaller one to avoid precision error?

Also when you have this kind of trimesh shape you have to increase the physics frames from 60 to 240 or so to make it more stable

**Comment by cosmicchipsocket** [comment] 2018-08-26 15:11
Splitting all parts will just make the object pop into the air upon crossing the seams, even with primitives like cubes (I've observed this in my own game). I also shouldn't need to increase the physics framerate to resolve this - the physics engine should simply make crossing over the individual triangles smooth. Not to mention, increasing it to 240 doesn't completely solve the issue, it just makes it less severe.

A few pages related to the issue elsewhere:
https://github.com/bulletphysics/bullet3/issues/288
https://pybullet.org/Bullet/phpBB3/viewtopic.php?t=2611

**Comment by erwincoumans** [comment] 2018-08-31 03:09
Yes, you need to use the 
~~~~~~~~~~
#include "BulletCollision/CollisionDispatch/btInternalEdgeUtility.h"
btTriangleInfoMap* triangleInfoMap = new btTriangleInfoMap();
btGenerateInternalEdgeInfo(trimesh, triangleInfoMap);

gContactAddedCallback = MyContactAddedCallback;//or add it to an existing callback

bool MyContactAddedCallback(btManifoldPoint& cp,	const btCollisionObjectWrapper* colObj0Wrap,int partId0,int index0,const btCollisionObjectWrapper* colObj1Wrap,int partId1,int index1)
{
	btAdjustInternalEdgeContacts(cp, colObj1Wrap, colObj0Wrap, partId1,index1);
	return true;
}
~~~~~~~~~~

**Comment by AndreaCatania** [comment] 2018-08-31 07:44
@erwincoumans There is a bug in the btAdjustInternalEdgeContacts.

Here the implementation: 
https://github.com/godotengine/godot/pull/21618

The bug is that I use a compound shape and the function take the compound shape and cast it to a trimesh.

**Comment by erwincoumans** [comment] 2018-08-31 16:17
Do you mind providing a small patch? Add a check for the collision shape type before casting, and dealing with the btCompoundShape case (or avoid wrapping a triangle mesh with a btCompoundShape).

**Comment by AndreaCatania** [comment] 2018-08-31 19:01
I can't avoid use a compound due to Godot requirements, but I can write a patch to support that case

**Comment by erwincoumans** [comment] 2018-08-31 19:17
Why is it a requirement? Do you need a transform or is it required to have multiple shapes? We could add a btTransformShape (better performance as btCompoundShape).

**Comment by AndreaCatania** [comment] 2018-08-31 20:57
It's required to have multiple shapes, I could use the btTransformShape
when only one shape is used but support compound is necessary anyway

**Comment by cosmicchipsocket** [comment] 2018-08-31 22:06
Some more background, at least from a Godot user perspective:

In Godot, objects are placed within a scene tree. For a physics object, you create a RigidBody or StaticBody (or similar) object. These objects do not contain shapes by themselves. Instead, you add one or more CollisionShape objects as children. These shapes are used together to form the compound shape. This means it's possible to do something like have a trimesh shape and a cube shape be part of the same object. It's not exactly ideal from the perspective of Bullet, but it is something that the user can do.

An easy fix would probably be to show a warning in the tree when a user has multiple CollisionShapes with one being a trimesh shape, since we already show a warning when there are no CollisionShapes. But if the Godot project wants to keep options open, the fix should probably be within Bullet, assuming there are no major performance concerns.

**Comment by AndreaCatania** [comment] 2018-09-05 10:40
@erwincoumans I've created the function `godotContactAddedCallback` and added to contact callback

	gContactAddedCallback = &godotContactAddedCallback;

This function is called with colObj1Wrap that wraps a `btTriangleShape` and not `btScaledBvhTriangleMeshShape` or compund as I expected.

When I create a trimesh shape I use `btScaledBvhTriangleMeshShape`. Do you know why it happens?

**Comment by erwincoumans** [comment] 2018-09-05 22:33
This is expected: during the dispatch, there will be temporary collision shapes generated (btTriangleShape) that get passed to the narrowphase and contact callbacks. You can still access the original collision shape, if you want to do filtering.

The btCollisionObjectWrapper colObj1Wrap->m_shape may point to btTriangleShape,
but the colObj1Wrap->m_collisionObject->getCollisionShape still points to the original shape.

Can you double-check?

**Comment by AndreaCatania** [comment] 2018-09-06 05:39
oh ok, so can you please confirm that this function is called 1 time (for each step) per body even if it has more then 1 shape? (I want to avoid multiples useless update) Thanks you!

**Comment by AndreaCatania** [comment] 2018-09-06 14:43
Ok I can optimize that case

**Comment by AndreaCatania** [comment] 2018-09-06 16:38
Optimized following the advice of erwin, and also implemented the use of function: btAdjustInternalEdgeContacts

but doesn't solve the problem #21808

**Comment by AndreaCatania** [comment] 2018-09-06 16:50
would be interesting test it inside PyBullet...

**Comment by erwincoumans** [comment] 2018-09-06 17:40
Did you generate the internal edge information?

Do you have the trimesh as an .obj file? If so, it is easy to reproduce.

**Comment by AndreaCatania** [comment] 2018-09-06 17:48
Yes I do it. Could be due by the fact that I use btTriangleMesh to generate btBvhTriangleMeshShape?

@cosmicchipsocket Do you have the blender file of  this trimesh shape?

**Comment by AndreaCatania** [comment] 2018-09-08 07:40
@erwincoumans I know that you don't have time to support us but I really don't know why this happen.. 
Also another issue: #21409 say that this bug appeared after the margin pull request was merged.

Do you know if margin could introduce this behaviour? also increasing timestep from 60 to 120 make the problem completely disappear.

**Comment by AndreaCatania** [comment] 2018-09-08 07:53
I've checked if the problem was introduced by #e5bfa98d0fa6a1acb1d385534c51b8006ef64142, but that PR just increased that problem...
Is like that the primitive shape is not able to correctly depenetrate the trimesh surface.

**Comment by AndreaCatania** [comment] 2018-09-08 08:26
Change margin of trimesh shape to 0 seems to reduce drastically this problem, but I'm wandering if the normal (so the order of vertices in the triangle) is a significant information for bullet...

Could be that the margin is applied toward the triangle face direction?
Should I use margin in ConcaveShape?

**Comment by cosmicchipsocket** [comment] 2018-09-10 23:03
I was hoping that #21808 would fix the issue but now it seems to have gotten worse. Nine times out of ten I can't even make it to the half-pipe without being flung off to the side.

**Comment by cosmicchipsocket** [comment] 2018-09-11 02:56
Here's the Blender file

[TestTerrain.zip](https://github.com/godotengine/godot/files/2369166/TestTerrain.zip)

**Comment by SneakyMax** [comment] 2018-10-05 13:50
That's awesome @AndreaCatania - when would we want `smooth_trimesh_collision` to be set to false?

**Comment by AndreaCatania** [comment] 2018-10-05 13:58
When you don't need to walk on a trimesh, or if you don't have any problem walking on it with that parameter set to false.

**Closed** 2018-10-07 09:01 UTC
Labels: bug, topic:physics

**Comment by cosmicchipsocket** [comment] 2018-10-07 17:04
It's not 100% solved but much improved. Half-pipe feels right but the puck still catches on a couple triangle edges in the first part. Setting physics FPS to 120 mostly eliminates these issues.

**Comment by cosmicchipsocket** [comment] 2018-10-07 17:35
Wanted to share this clip. Thank you for your hard work improving the physics.

![quarterpipecropped](https://user-images.githubusercontent.com/34800072/46584795-cca14a80-ca35-11e8-9651-dad6a69f4938.gif)

**Comment by AndreaCatania** [comment] 2018-10-07 19:03
I'm glad to see this clip, and also thanks you 😁

**Comment by Zylann** [comment] 2020-07-24 12:12
Can we document `physics/3d/smooth_trimesh_collision`? Someone asked about it on my repo, it's nowhere to be found in docs and I have no idea what it is.

**Comment by AndreaCatania** [comment] 2020-07-27 08:56
Imagine a triangle mesh with two big triangles. Your object (a box) is on a triangle - sliding toward the other triangle. When it touch the edge of the other triangle it generates a normal that doesn't follows the surface `(0,1,0)` but follows the edge direction `(0.5, 0.5, 0).normalize()` making the object jump a little bit.

The `physics/3d/smooth_trimesh_collision` make sure to fix the collision normal in that case.

Note that, to fully use this feature, also the trimeshshape COM must be 0,0,0.

**Comment by jes** [comment] 2020-07-27 15:11
I think I am running into the same problem here.

I have enabled `physics/3d/smooth_trimesh_collision` but I still hit an invisible bump at the join between 2 triangles: https://www.youtube.com/watch?v=NzZOowfcAAw

**Comment by AndreaCatania** [comment] 2020-09-19 13:22
@Zylann 
> Can we document `physics/3d/smooth_trimesh_collision`? Someone asked about it on my repo, it's nowhere to be found in docs and I have no idea what it is.

https://github.com/godotengine/godot-docs/pull/4040

**Comment by AndreaCatania** [comment] 2020-09-19 13:23
> I think I am running into the same problem here, in 3.2.stable from Ubuntu 20.04.
> 
> I have enabled `physics/3d/smooth_trimesh_collision` but I still hit an invisible bump at the join between 2 triangles: https://www.youtube.com/watch?v=NzZOowfcAAw

If that still the case, try to open a new issue with a sample project.

**Comment by meigel** [comment] 2020-09-19 18:39
> @Zylann
> 
> > Can we document `physics/3d/smooth_trimesh_collision`? Someone asked about it on my repo, it's nowhere to be found in docs and I have no idea what it is.
> 
> [godotengine/godot-docs#4040](https://github.com/godotengine/godot-docs/pull/4040)

Very nice! Where do I find the page `tutorials/physics/collision_shapes_3d.rst` in the online documentation?

**Comment by Paavs-Git** [comment] 2020-09-19 20:03
> Very nice! Where do I find the page `tutorials/physics/collision_shapes_3d.rst` in the online documentation?

That Pull Request has not been merged yet, so it's not yet in the online documentation.

**Comment by braydenplumb** [comment] 2021-02-22 10:09
I am starting to see this exact issue pop up again in Godot v3.2.3. I am trying to use a rigid body with a sphere collision, and a concave polygon tri-mesh collision for a racing game, but every time the sphere car controller hits an edge in the collision, it just keeps jumping up. It's very similar to both @jes and @cosmicchipsocket video. I've tried both Bullet and GodotPhysics with the smooth_trimesh_collision option selected, and the collision margins dropped to .001 with no success so far.

https://user-images.githubusercontent.com/60860773/108693599-ddda3d00-74b2-11eb-85b4-17a8d625da89.mp4

**Comment by jes** [comment] 2021-02-22 10:12
I seem to recall that my problem was at least partly down to having a really low mass for the vehicle. What's your vehicle mass set to? You might find the problem gets better if you increase it by 10x or 100x.

**Comment by braydenplumb** [comment] 2021-02-22 10:14
It's set to a mass of 1500, which I feel like should be more than high enough, if not too high. I've tried setting it higher and it only slightly helps, but is still very prominent unfortunately.

**Comment by braydenplumb** [comment] 2021-02-22 10:18
I'm thinking that the smooth_trimesh_collision may have just been a temporary solution, and something in the 3.2.3 update caused it to break. It might be worth me trying out the project in an earlier version of Godot to see if it's still there.

**Comment by wissem-cood** [comment] 2021-05-19 08:56
@cosmicchipsocket 

Hey !

Hope you're doing fine, i'm having the same issue that you got ( 5 years ago hahah )
I'm actually using ammo.js, a javascript library based on a bullet compilation..
Unfortunately, there's no info about this issue, and i'm stuck, can't go further and it's so frustrating, because i really don't know how i'll solve this problem !

I did this 

```btTriangleInfoMap* triangleInfoMap = new btTriangleInfoMap();
btGenerateInternalEdgeInfo(trimesh, triangleInfoMap);

gContactAddedCallback = MyContactAddedCallback;//or add it to an existing callback

bool MyContactAddedCallback(btManifoldPoint& cp,	const btCollisionObjectWrapper* colObj0Wrap,int partId0,int index0,const btCollisionObjectWrapper* colObj1Wrap,int partId1,int index1)
{
	btAdjustInternalEdgeContacts(cp, colObj1Wrap, colObj0Wrap, partId1,index1);
	return true;
}
```

But in javascript so it looks like this :

```
const triangleInfoMap = new Ammo.btTriangleInfoMap();
Ammo.btGenerateInternalEdgeInfo(this.shape, triangleInfoMap);

//Ammo.addFunction gives me back a pointer
const gContactCallback = Ammo.addFunction((cp, colObj0Wrap, partId0, index0, colObj1Wrap, partId1, index1) => {
	Ammo.btAdjustInternalEdgeContacts(cp, colObj1Wrap, colObj0Wrap, partId1,index1);
	return true;
})
```

the thing is, i don't know where to set my callback, is it on the physicsworld.setContactProcessedCallback ??
i already tried with physicsworld.setContactProcessedCallback, but it's doesn't seem to work 😢 

I would love to talk with you and maybe you can share with me your experience and solutions for this!
Thanks a lot in advance ❤️

**Comment by Saitodepaula** [comment] 2021-07-14 18:32
> I'm thinking that the smooth_trimesh_collision may have just been a temporary solution, and something in the 3.2.3 update caused it to break. It might be worth me trying out the project in an earlier version of Godot to see if it's still there.

I'm also making a 3D racing game, and I'm facing the same issue. I've teste my game on 3.1, 3.2 and 3.3, and the results were all the same (bumpy ride).

I think for the specific case of rigid bodies spinning very fast (your case is a sphere, mine I'm using cyllinders for the wheels), `smooth_trimesh_collision` doesn't work. It looks it works only for sliding rigid bodies.

**Comment by wissem-cood** [comment] 2021-07-15 08:40
@Saitodepaula Hey 🙋 !

We managed to fix it by modifying the bullet build directly ( Edited cpp files )
Here's the issue and how we fixed it ▶️ [Solution](https://github.com/kripken/ammo.js/issues/367#event-5023925066) ◀️ 

Feel free to comment if you didn't understand something, we will reply ASAP ! 🤗 
Hope it helps ❤️

**Comment by AndreaCatania** [comment] 2021-07-15 09:19
Nice, I didn't verify if changing the margin would solve the issue at that time.

However, `smooth_trimesh_collision` should be the proper way to fix the issue, since it smooth out the `normal` obtained from the trimesh. So, when the hit occurs, on the edge of the triangle there is an additional algorithm that recomputes the hit to also consider the adjacent triangles and adjust the normal and the response to it.

**Comment by Saitodepaula** [comment] 2021-07-15 15:04
> @Saitodepaula Hey 🙋 !
> 
> We managed to fix it by modifying the bullet build directly ( Edited cpp files )
> Here's the issue and how we fixed it ▶️ [Solution](https://github.com/kripken/ammo.js/issues/367#event-5023925066) ◀️
> 
> Feel free to comment if you didn't understand something, we will reply ASAP ! 🤗
> Hope it helps ❤️

Hi @wissem-cood , I didn't know this project, looks great, I've had some fun with the examples!

Were you able to integrate this with Godot? It would be necessary to build Godot with Ammo.js in place of Bullet?

**Comment by AndreaCatania** [comment] 2021-07-22 09:07
Hey @Saitodepaula you can already modify margin and friction, to do so:
- On the Rigid body add a new physics material and set the desired friction.
- Select the child shape node, set the margin you desire.

The above is enough to do what suggested by the above solution. In combination to this, make sure to also use `smooth_trimesh_collision`. Please post any result, will be interesting to know.

**Comment by Saitodepaula** [comment] 2021-07-22 11:29
> Hey @Saitodepaula you can already modify margin and friction, in this way:
> 
> * On the Rigid body add a new physics material and set the desired friction.
> * Select the child shape node, set the margin you desire.
> 
> The above is enough to do what suggested by the above solution. In combination to this, make sure to also use `smooth_trimesh_collision`. Please post any result, will be interesting to know.

Hum, so I think I misunderstood the solution by @wissem-cood , I thought they were able to fix the bumpy behaviour.

Anyway, if you want to take a look at #50463, I've described the bumpy behaviour (both with Bullet and Godot Physics) and made a minimal project.
