### ISSUE TITLE
Popup Menu has additional padding regardless of stylebox used.

### ISSUE THREAD

**Issue by Skullfurious** [godotengine/godot#43069] opened 2020-10-25 04:29 UTC
**Your Godot version:**
3.2.2 stable

**Issue description:**

Popupmenus have some strange display bug that adds padding that ignores the active stylebox. Looks to be about 1-2 pixels in size.

https://dl.dropboxusercontent.com/s/3alpqgo76cuqcda/4IfWWSmWBq.mp4

I examined the CPP file for popupmenu but couldn't figure out where the exact issue is. 

https://github.com/godotengine/godot/blob/0c449aefa2732fbf16161e8b9a9dddca84a36cd0/scene/gui/popup_menu.cpp
**URL to the documentation page:**

**Comment by Anutrix** [comment] 2020-10-25 10:38
A minimum reproduction project would be helpful.

**Comment by Skullfurious** [comment] 2020-10-25 20:14
https://dl.dropboxusercontent.com/s/v4oga6ly6qeilkh/popupmenu.7z

Here you go. Github wouldn't let me upload a .zip or a .7z file for whatever reason.

**Comment by ShadyChibinko** [comment] 2022-02-25 18:41
Still relevant in 3.4.2.stable.

The root of the problem seems to be `custom_constants/hseparation` as increasing or decreasing that value, directly affects how much padding there is. Set it to something like 30 and the problem immediately becomes apparent. I looked over the CPP file and the only two places it's used are in get_minimum_size() and NOTIFICATION_DRAW. The latter is what's actually drawing the hover stylebox, so I'd assume the issue is with this line:

https://github.com/godotengine/godot/blob/45eaa2daf1e3d2571a9f31a3421911262ec82f51/scene/gui/popup_menu.cpp#L540

**Comment by akien-mga** [comment] 2022-05-27 23:13
Fixed by #61479.

**Closed by akien-mga** 2022-05-27 23:13 UTC
Labels: bug, topic:gui
