### ISSUE TITLE
Referencing the current class name causes memory leaks / errors on exit

### ISSUE THREAD

**Issue by Jeto143** [godotengine/godot#38765] opened 2020-05-15 20:27 UTC
**Godot version:**

3.2.1-stable

**Steps to reproduce:**

Create a script with the following code and attach it to a node:

```gdscript
extends Node
class_name Foo

var foo: Foo
```

Then exit the game and check the console output. The following errors are reported:

> ERROR: ~List: Condition "_first != __null" is true.
>    At: ./core/self_list.h:112
> ERROR: ~List: Condition "_first != __null" is true.
>    At: ./core/self_list.h:112
> WARNING: cleanup: ObjectDB Instances still exist!
>      At: core/object.cpp:2071
> ERROR: clear: Resources Still in use at Exit!
>    At: core/resource.cpp:476

This may be related to #21461 to some degree, but this executes perfectly fine otherwise (before exiting, that is).

**Comment by qarmin** [comment] 2020-05-15 20:45
Duplicate of https://github.com/godotengine/godot/issues/30668 (title is a little misleading)

**Closed by qarmin** 2020-05-15 20:45 UTC
Labels: archived
