### ISSUE TITLE
Javascript

### ISSUE THREAD

**Issue by Hamed2012-dr** [godotengine/godot#37393] opened 2020-03-28 22:05 UTC
Hello. Please add javascript programming language API to the Engine ...

**Comment by ThakeeNathees** [comment] 2020-03-28 22:17
@Hamed2012-dr This repository no longer accepts feature / enhancement requests. your proposals should be created on https://github.com/godotengine/godot-proposals with more details

**Comment by akien-mga** [comment] 2020-03-28 22:43
More importantly, we don't have time for such low efforts proposals, either here or on godot-proposals.

There's no plan for JavaScript support officially. There's a community effort that you can use though.

Duplicate of #19294 and #937.

**Closed by akien-mga** 2020-03-28 22:43 UTC
