### ISSUE TITLE
[Android] ``OS.get_window_safe_area()`` doesn't adjust to non-immersive display modes

### ISSUE THREAD

**Issue by Sosasees** [godotengine/godot#62976] opened 2022-07-13 11:30 UTC
### Godot version

3.5.rc6.official [f05cecdc4]

### System information

PC: Linux | Phone: Samsung Android 11

### Issue description

an Android app exported from Godot 3.5 supports Pop-up and Split view display modes (finally!).

but the Window Safe Area is only correct if the app is run full-screen in Immersive Mode.
in any other situation, the Safe Area is wrong and causes content to get cut off:
- if Immersive Mode is disabled
- if the app is opened in a Pop-up window
- if the app is opened in Split view

### Steps to reproduce

- Export and Run the reproduction project on an Android device
   - Play around with Pop-up and Split view mode.
     notice how most of the content gets cut off
   - Play around with toggling Immersive Mode.
     notice how in Fullscreen mode the bottom of the app gets cut off if not in Immersive Mode

### Minimal reproduction project

[safe-area-test.zip](https://github.com/godotengine/godot/files/9101599/safe-area-test.zip)

**Comment by Calinou** [comment] 2022-07-13 17:09
cc @madmiraal 

I'm not sure if the pop-up/split safe areas can be fixed though. Is the app aware of *where* it is placed on the screen?

**Comment by madmiraal** [comment] 2022-07-13 17:11
Duplicate of #61467.

**Comment by Sosasees** [comment] 2022-07-13 18:24
to fix the incorrect safe area rectangle in fullscreen non-immersive mode, i suggest
1. enabling overdraw so that content is drawn over the Status Bar and Navigation Bar
2. now we can make a safe-area rectangle that accounts for the Status Bar and the Navigation Bar but is otherwise the same as in Immersive Mode

this has benefits:
- it might be easier to implement
- the developer can make custom backgrounds for the System Bars that match the rest of the app.
  this can be used to color the bars in the same color/pattern as the toolbars above/below by extending the ColorRect/TextureRect beyond the safe area.
here's [a demo of how i would do this](https://github.com/godotengine/godot/files/9104875/ui-design-with-overdraw-demo.zip)
- it's easier to transition in and out of immersive mode,
  which i find useful for my current game:
  i want immersive mode for the gameplay but non-immersive mode for the menus

**Comment by Calinou** [comment] 2022-07-13 21:27
Closing in favor of https://github.com/godotengine/godot/issues/61467. Please continue the discussion there.

**Closed by Calinou** 2022-07-13 21:27 UTC
Labels: bug, platform:android, topic:porting
