### ISSUE TITLE
Opening script from Godot into VS Code un-maximizes VS Code

### ISSUE THREAD

**Issue by Tuckertcs** [godotengine/godot#73731] opened 2023-02-22 04:03 UTC
### Godot version

4.0 RC 2

### System information

Linux Mint 20.3 (Cinnamon)

### Issue description

I've set Godot to open scripts in VS Code, since I'm using C#. When I open a script through Godot, it pulls it up in VS Code. However, VS Code will no longer be maximized, and instead pops the window to be square, in the center of the screen (every time).

### Steps to reproduce

1. Create a Godot project that uses C# scripts.
2. Set Godot to use VS Code as the script editor.
3. Create a C# script in Godot.
4. Open the script (in Godot) and watch VS Code open up.
5. Maximize VS Code.
6. Switch back to Godot.
7. Open the script (in Godot) again, and watch VS Code open up, again.
8. Notice that VS Code is no longer maximized, and is now a free-floating window again.

### Minimal reproduction project

[pokemon-like-4-cs.zip](https://github.com/godotengine/godot/files/10799903/pokemon-like-4-cs.zip)

**Comment by raulsntos** [comment] 2023-02-26 02:07
I can't reproduce, it sounds more like an issue with VSCode than Godot. Can you take a look at your settings? Maybe check `window.openFilesInNewWindow`, `window.openFoldersInNewWindow`, and `window.newWindowDimensions`.

**Comment by Calinou** [comment] 2023-02-27 16:57
Closing per the above comment.

**Closed by Calinou** 2023-02-27 16:57 UTC
