### ISSUE TITLE
In-engine documentation is shown incorrectly (text has limited width)

### ISSUE THREAD

**Issue by ClarkThyLord** [godotengine/godot#78453] opened 2023-06-20 02:18 UTC
### Godot version

v4.1.beta2.official [a2575cba4]

### System information

Windows 10

### Issue description

When you open any in-engine documentation the text is shown to be limited, creating very long documentation, as seen below:
![image](https://github.com/godotengine/godot/assets/17155529/6b2bc72a-5fd1-4d3e-83f9-7de8e77cb070)

Issue can be resolved by resizing the window:
![image](https://github.com/godotengine/godot/assets/17155529/0db2b4b5-cc60-4cac-9781-d55847b7a040)

### Steps to reproduce

1. Open any in-engine documentation
2. Documentation is displayed incorrectly

### Minimal reproduction project

Issue can be seen in any existing or new project.

**Comment by Chaosus** [comment] 2023-06-20 04:36
Looks like a duplicate of https://github.com/godotengine/godot/issues/75087?

**Comment by akien-mga** [comment] 2023-06-20 05:50
- Duplicate of #77558, fixed in upcoming 4.1 beta 3

**Closed by akien-mga** 2023-06-20 05:50 UTC
Labels: bug, topic:editor, topic:gui
