### ISSUE TITLE
Directory make_dir and make_dir_recursive should not CD

### ISSUE THREAD

**Issue by TheDuriel** [godotengine/godot#30957] opened 2019-07-30 10:40 UTC
**Godot version:**

3.1

**OS/device including version:**

Windows 7

**Issue description:**

Currently when you make_dir or make_dir_resursive the Directory class will also open the new directory. This is not in line with how terminal commands function, and can lead to unexpected behavior. It also means you are forced to open the parent directory each time you want to add a sub folder.

**Steps to reproduce:**
Call make_dir, then call it again. You should now have nested folders, instead of siblings.

**Minimal reproduction project:**

**Comment by KoBeWi** [comment] 2019-08-06 13:38
I can't reproduce it on Windows 10. Looking at the implementation, this is done via some OS methods, so probably every system does this a bit differently.

**Comment by KoBeWi** [comment] 2020-09-25 00:11
Can anyone still reproduce this bug in Godot 3.2.3 or any later release?

If yes, please ensure that an up-to-date Minimal Reproduction Project (MRP) is included in this report (a MRP is a zipped Godot project with the minimal elements necessary to reliably trigger the bug). You can upload ZIP files in an issue comment with a drag and drop.

**Comment by codecustard** [comment] 2021-04-08 05:16
Cannot reproduce it using Godot version 3.2.3 stable on MacOS Catalina 10.15.7

Took a look at the implementation in both master branch as well as 3.1 branch and wasn't able to see anything that would cause this issue.

**Comment by KoBeWi** [comment] 2021-04-08 06:09
Closing. Please comment if you can reproduce in 3.3.

**Closed by KoBeWi** 2021-04-08 06:09 UTC
Labels: bug, topic:core
