### ISSUE TITLE
AudioStreamPlayer `playing` animation tracks constantly firing if played via an AnimationTree

### ISSUE THREAD

**Issue by RobTheFiveNine** [godotengine/godot#95701] opened 2024-08-17 16:15 UTC
### Tested versions

- Reproducible in v4.3.stable.official [77dcf97d8]
- Not reproducible in v4.2.1.stable.official [b09f793f5]

### System information

Godot v4.3.stable - Ubuntu 24.04 LTS 24.04 - X11 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3070 Ti (nvidia; 535.183.01) - 12th Gen Intel(R) Core(TM) i9-12900F (24 Threads)

### Issue description

When adding an animation track for the `playing` property of an `AudioStreamPlayer`, the animation works as intended (e.g. if the `playing` property is set to true in the animation track, it will begin playing the audio resource.

If, however, that animation is used inside an `AnimationTree`, it creates an audio bug which sounds like it is the file being repeatedly played over and over in quick succession without it having finished.

The issue happens both inside the editor and when running a build.

### Steps to reproduce

1. Open the MRP and play the `test` animation in `AnimationPlayer` (either in the editor or enabling the auto play option and running the build) to see the audio is played at `0.1` and `0.4` seconds without issue
2. Disable autoplay on `AnimationPlayer` if used to test in step 1, and now enable the `active` property of `AnimationTree` to hear in the editor and when running the build that there is a constant audio artifact that sounds as if the audio file is being constantly played / restarted

### Minimal reproduction project (MRP)

[godot-audio-animation-bug-mrp.zip](https://github.com/user-attachments/files/16645543/godot-audio-animation-bug-mrp.zip)

**Comment by akien-mga** [comment] 2024-08-17 17:41
Related to / possible duplicate of #95684.

**Comment by TokageItLab** [comment] 2024-08-17 18:04
Dupe of https://github.com/godotengine/godot/issues/95701, not bug.

**Closed by TokageItLab** 2024-08-17 18:04 UTC
Labels: bug, topic:audio, regression, topic:animation
