### ISSUE TITLE
building godot fails on ssl include problems

### ISSUE THREAD

**Issue by CowboyTim** [godotengine/godot#7703] opened 2017-02-01 22:48 UTC
Building godot from source stops with an error, both with llvm or gcc-6.3 (which is not supported anyway). The errors seem to be with libssl includes for BIO.

debian SID 64-bit.
libssl-dev:amd64                                                          1.1.0d-2

```
~/godot (2.1.2-stable)$ g++ --version
g++ (Debian 6.3.0-3) 6.3.0 20170118
Copyright (C) 2016 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

~/godot (2.1.2-stable)$ clang --version
clang version 3.8.1-17 (tags/RELEASE_381/final)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
```

To reproduce:
```
~/godot (2.1.2-stable)$ git status
On branch 2.1.2-stable
nothing to commit, working tree clean
:~/godot (2.1.2-stable)$ scons platform=x11 use_llvm=yes
...

~/godot (2.1.2-stable)$ clang++ -o modules/openssl/stream_peer_openssl.x11.tools.64.llvm.o -c -g2 -Wall -DDEBUG_ENABLED -DDEBUG_MEMORY_ENABLED -DDEBUG_MEMORY_ALLOC -DSCI_NAMESPACE -DENABLE_DEPRECATED -DTYPED_METHOD_BIND -DOPENGL_ENABLED -DALSA_ENABLED -DJOYDEV_ENABLED -DPULSEAUDIO_ENABLED -DX11_ENABLED -DUNIX_ENABLED -DGLES2_ENABLED -DGLES_OVER_GL -DTOOLS_ENABLED -DGDSCRIPT_ENABLED -DMINIZIP_ENABLED -DXML_ENABLED -DGLEW_STATIC -DGLEW_ENABLED -DMODULE_SPEEX_ENABLED -DMODULE_GRIDMAP_ENABLED -DMODULE_DDS_ENABLED -DMODULE_VORBIS_ENABLED -DMODULE_CHIBI_ENABLED -DMODULE_OGG_ENABLED -DMODULE_OPUS_ENABLED -DMODULE_PVR_ENABLED -DMODULE_IK_ENABLED -DMODULE_GDSCRIPT_ENABLED -DMODULE_ENET_ENABLED -DMODULE_MPC_ENABLED -DMODULE_REGEX_ENABLED -DMODULE_JPG_ENABLED -DMODULE_VISUAL_SCRIPT_ENABLED -DMODULE_THEORA_ENABLED -DMODULE_ETC1_ENABLED -DMODULE_SQUISH_ENABLED -DMODULE_OPENSSL_ENABLED -D_REENTRANT -Icore -Icore/math -Itools -Idrivers -I. -Iplatform/x11 -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/alsa -Ithirdparty/glew modules/openssl/stream_peer_openssl.cpp
modules/openssl/stream_peer_openssl.cpp:64:29: warning: 'ASN1_STRING_data' is deprecated [-Wdeprecated-declarations]
        common_name_str = (char *) ASN1_STRING_data(common_name_asn1);
                                   ^
/usr/include/openssl/asn1.h:553:35: note: 'ASN1_STRING_data' has been explicitly marked deprecated here
DEPRECATEDIN_1_1_0(unsigned char *ASN1_STRING_data(ASN1_STRING *x))
                                  ^
modules/openssl/stream_peer_openssl.cpp:105:30: warning: 'ASN1_STRING_data' is deprecated [-Wdeprecated-declarations]
                        char *dns_name = (char *) ASN1_STRING_data(current_name->d.dNSName);
                                                  ^
/usr/include/openssl/asn1.h:553:35: note: 'ASN1_STRING_data' has been explicitly marked deprecated here
DEPRECATEDIN_1_1_0(unsigned char *ASN1_STRING_data(ASN1_STRING *x))
                                  ^
modules/openssl/stream_peer_openssl.cpp:176:3: error: member access into incomplete type 'BIO' (aka 'bio_st')
        b->init = 1;

```
...

**Comment by CowboyTim** [comment] 2017-02-02 21:23
I've just tested this with openssl-1.0.2j and this works. Now I'm looking on documentation for scons on how to temporarily change an include path to verify that the rest of the building works.

**Comment by bojidar-bg** [comment] 2017-05-02 08:10
Bump, what's the status on this issue?

**Comment by akien-mga** [comment] 2017-05-02 08:11
Well it's simple, Godot's openssl module does not support OpenSSL 1.1.0+, so you need to build against 1.0.x or against the bundled source.

**Comment by akien-mga** [comment] 2017-05-02 08:14
Duplicate of #7085.

**Closed by akien-mga** 2017-05-02 08:14 UTC
Labels: bug, platform:linux, topic:buildsystem
