### ISSUE TITLE
CanvasLayer not matching with first child control

### ISSUE THREAD

**Issue by AbnormalAleks** [godotengine/godot#81514] opened 2023-09-10 13:53 UTC
### Godot version

v4.1.1.stable.official [bd6af8e0e]

### System information

Godot v4.1.1.stable - Windows 10.0.18363 - Vulkan (Mobile) - integrated Intel(R) HD Graphics 520 (Intel Corporation; 27.20.100.9416) - Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz (4 Threads)

### Issue description

When instantiating a CanvasLayer scene with a control node and inside the node something like a Label, TextureRect, Button, etc. that exact node if its the first in the scene inside the control node will follow the viewport instead of the CanvasLayer. Basically means that the first node of the CanvasLayer scene will detach from the scene and "become" part of the other scene, where the CanvasLayer is instantiated. This is best shown in the editor when transforming the instantiated CanvasLayer (recommended transform - rotating, scaling). I already mentioned this later in the issue but it is absolutely necessary to switch the rendering to either Forward+ or Mobile.

### Steps to reproduce

Main Scene
1. Create Node2D as main scene
2. Create another Node2D inside the main scene
3. Create a Camera2D inside the second Node2D

CanvasLayer
1. Create CanvasLayer as the UI scene
2. Create a Control node inside the UI scene
3. Create atleast 2 UI nodes like Label, TextureRect, Button. etc
- Positioning/Anchoring of the UI elements don't matter that much, but its easier if they are apart from each other
- As far as i know, Label's first letter of its text follows the viewport instead of the whole node doing it. Some other nodes could do that
- Its best to switch the orders of the nodes from 3rd step

Final
1. Instantiate CanvasLayer scene in main scene
2. Transform the scene in editor in any way (like rotation, position)
3. (This is necessary)Switch the rendering to either Forward+ or Mobile, not Compatibility

### Minimal reproduction project

I hope i did everything right for preparing this reproduction project
[CanvasLayerBug.zip](https://github.com/godotengine/godot/files/12568328/CanvasLayerBug.zip)

**Comment by arkology** [comment] 2023-09-10 14:41
Hooray, another variation of https://github.com/godotengine/godot/issues/58314

**Comment by AbnormalAleks** [comment] 2023-09-10 16:18
accidentally closed the issue, altho this is a duplicate im just gonna leave it as it was

**Comment by AThousandShips** [comment] 2023-09-10 16:20
Duplicate of #58314

**Closed by AThousandShips** 2023-09-10 16:20 UTC

**Comment by AbnormalAleks** [comment] 2023-09-10 16:21
alr thx
