### ISSUE TITLE
Full screen mode crashes OSX application built with v2.1.4

### ISSUE THREAD

**Issue by rokasv** [godotengine/godot#15626] opened 2018-01-12 14:48 UTC
Enabling the full-screen from either the settings or dynamically on MacOS 10.12.6 when building using Godot v2.1.4 stable crashes the application.

This does not happen with v2.1.3.stable

**Comment by tavurth** [comment] 2018-08-22 19:54
Tested on Godot 3.06 OSX 10.12 mid 2014 macbook air, could not reproduce.

Tested fullscreen from project settings : working
Tested fullscreen from project input : working

![image](https://user-images.githubusercontent.com/100964/44487183-489a2b80-a65e-11e8-86c1-af976cacd4e1.png)

Propose closure.

**Comment by rokasv** [comment] 2018-08-22 19:57
Close 2.1 issue because you couldn't reproduce it on 3.0? 🤔

**Comment by akien-mga** [comment] 2018-08-22 20:34
Is it reproducible in 2.1.5-stable?

**Comment by akien-mga** [comment] 2018-09-18 09:34
> Is it reproducible in 2.1.5-stable?

Bump.

**Comment by rokasv** [comment] 2018-09-18 13:48
> Is it reproducible in 2.1.5-stable?

Will test either later today or tomorrow.

**Comment by rokasv** [comment] 2018-09-18 23:16
Confirming that this no longer appears to be an issue.  Although the Mac used is not on 10.13.4 OS version.

**Comment by akien-mga** [comment] 2018-09-19 07:04
Thanks for testing. I *think* it should behave similarly on 10.12 and 10.13, so closing.

Please comment if you even happen to reproduce it again and we'll reopen it.

**Closed by akien-mga** 2018-09-19 07:04 UTC
Labels: bug, platform:osx, topic:core
