### ISSUE TITLE
Improve deprecation message for `BaseButton.set_enabled_focus_mode`

### ISSUE THREAD

**Issue by zinnschlag** [godotengine/godot#48160] opened 2021-04-24 14:33 UTC
**Godot version:**

Godot Engine v3.3.stable.official

**OS/device including version:**

Ubuntu

**Issue description:**

On loading an existing project into Godot 3.3 the editor produced the following warning:

> WARNING: set_enabled_focus_mode: BaseButton's Enabled Focus Mode property has been deprecated due to redundancy and will be removed in Godot 4.0. Please use Control.set_focus_mode instead.
   At: scene/gui/base_button.cpp:329.

This is a problem, because this error message does not indicate where the problem can be found.

I did find the problem eventually within the inspector panel of a button node, but only because I remembered that I could do a git grep. From a usability standpoint this is rather bad and should be considered a bug IMO.

Note that the same problem does not occur, if enabled_focus_mode is set via GDScript instead. In this case the editor does point towards the script.

**Steps to reproduce:**

Just load the attached project and run it.

**Minimal reproduction project:**
[test.zip](https://github.com/godotengine/godot/files/6369769/test.zip)

**Comment by Calinou** [comment] 2021-04-24 16:01
> From a usability standpoint this is rather bad and should be considered a bug IMO.

That's not how we triage things here :slightly_smiling_face:

Anyway, I'll look into printing the node's path in the deprecation message.

**Comment by komputerboy** [comment] 2021-04-27 03:49
just change `Enable Focus` to `All` and `Focus -> Mode` to `None`
after that double check it again
![Untitled](https://user-images.githubusercontent.com/42455711/116182190-09dd9d00-a746-11eb-9356-e2843b25d095.png)

**Comment by zinnschlag** [comment] 2021-04-27 05:45
@komputerboy Yes, that fix is obvious. The problem was not fixing the button. The problem was finding the button.

@Calinou That is rather unfortunate. This problem is likely not unique to set_enabled_focus_mode. If there ever has to be a property in a node to be deprecated again, we will likely see the same issue.

Maybe it would make sense to amend the documentation in some way (or even the warning message?), pointing the user towards a search on file level (with VCS or system tools).

**Comment by sjharb** [comment] 2021-06-05 22:32
For me this caused the release build to fail, but did not show any warning in the 'Debugger' and the game ran fine until exported as release or debug (both failed).  The error for the button deprecation does show in the console and the error logs when using verbose on the release exe.  But it seems that the default 'enabled_focus_mode' should now be 'None' for Buttons so that the editor and tscn files show that I am using 'focus_mode' that is not default (none).

I have lots of buttons but finding them and modifying them is still on-going since I have to manually check each one.

You can find all of the buttons you use in your project by searching *.tscn files (in notepad++) for text : 'type="Button"'.

You can also search the *.tscn files for 'focus_mode' and 'enabled_focus_mode', but as I said above the search will not show unless the default was 'none' which it is currently 'all' so the tscn file doesn't find 'focus_mode = x' unless you modified the value.

Thanks for the info and picture above, that helped me alot, but the deprecated error message did not initially make sense to me either.
-Shaun

**Comment by hsandt** [comment] 2021-07-11 19:40
OK, I'm switching all my Enabled Focus Mode to None, but I see the Revert icon appearing every time I do this. This means the default is still All, and new users will keep getting the warning!

Surely, if values other than None are deprecated, the new default should be None?

**Comment by TheDuckCow** [comment] 2021-08-09 05:23
I was trying to search how to remove this setting as well. I only had one button in my project, and it seemed no matter what settings I changed in the UI, it was still throwing the warning. I ended up having to edit the scene file in a text editor to just remove the lines entirely. In this specific issue, I guess the issue is that the first time the property is edited, it adds that line of code/config to the scene file, but even if you reset it, it doesn't remove the line in the scene file, it just assigns the (0) default. Which is technically accurate from a setting standpoint, but means you can't actually revert back to state to before you had ever used the feature. Right now, even with those default settings applied, it makes sense that the warning still appears because the line of code/config is still in the file (and presumedly some future version of Godot will fail when trying to read that property).

I think a niche solution here could be to detect if the user is attempting to reset a value to its default, and if so, intentionally remove the line of code/config from the saved scene file, vs just updating to be assigned the default value as it does now. Maybe it would be a special case that only needs to be done for these deprecated parameters, as perhaps other people depend on saved properties (even if default values) to be saved in the scene files?

**Comment by akien-mga** [comment] 2021-08-09 06:44
> I think a niche solution here could be to detect if the user is attempting to reset a value to its default, and if so, intentionally remove the line of code/config from the saved scene file, vs just updating to be assigned the default value as it does now. 

That's actually how things work currently. If you got a default value serialized in a scene, that's a bug. Unless it's an inherited scene and the base scene has a non-default value (so the inherited scene needs to keep track of its difference with the base scene).

**Comment by Zylann** [comment] 2021-08-22 16:50
I had this problem in my plugin too and I ended up having to fire up a debug version of Godot, just so I could breakpoint and see what was setting that property. Not fun.

In my case, it happened because a few TSCN scenes of my plugins were created in the time where Godot used to save all properties, even those left to defaults. That included deprecated properties, hence the warning getting triggered. If the editor was able to trace that so context is given in that type of error (without having to enable some option somewhere), it would have saved time.

**Comment by YeldhamDev** [comment] 2021-08-23 01:08
Closed by #51993

**Closed by YeldhamDev** 2021-08-23 01:08 UTC
Labels: enhancement, usability, topic:gui
