### ISSUE TITLE
Unnamed Script Deletion bug

### ISSUE THREAD

**Issue by gocs** [godotengine/godot#15027] opened 2017-12-25 04:50 UTC
tl;dr
> first created a script
> named to `.gd`
> I saved it
> I deleted the file but it's still on the scene

- [ ] I searched the existing [GitHub issues](https://github.com/godotengine/godot/issues?utf8=%E2%9C%93&q=is%3Aissue+) for potential duplicates.

![image](https://user-images.githubusercontent.com/27877342/34333007-72e45310-e972-11e7-9537-de3af9e008a9.png)

Edit:
After deleting the file
It was the `Scene` < `Edit` < `Soft Reload Script` making it unnamed

**Comment by volzhs** [comment] 2017-12-25 07:11
delete a file from file manger or file system dock in godot editor?

**Comment by aaaaeinai** [comment] 2017-12-25 07:33
Yes above that `Pung.gd`
Apparently, it'll disappear if Godot is restarted.
It did cause `not responding` though

**Comment by volzhs** [comment] 2017-12-25 07:54
"Yes" means that you deleted `Pung.gd` from FileSystem dock in editor?

**Comment by aaaaeinai** [comment] 2017-12-25 08:14
Yes

**Comment by volzhs** [comment] 2017-12-25 08:29
how did you "first created a script"?

a. attach script window on node?
b. create a file from File > New from script editor?

**Comment by aaaaeinai** [comment] 2017-12-25 08:30
b.

**Comment by volzhs** [comment] 2017-12-25 08:43
your godot version?

I followed these steps.

1. create a `.gd` file from File > New from script editor
2. save it
3. delete `.gd` from FileSystem dock

editor is still stable to use, nothing happen. restart editor also.
tested with d91464f2173f14a9ab14c7f92a9619ae5551ca36 on Ubuntu 17.10
I can't reproduce it and specify if it's only windows issue or fixed.

**Comment by aaaaeinai** [comment] 2017-12-25 11:00
If the deleted file is named '(*)'
         Editor > Soft Reload

That was my case
My pc is only windows, godot 2.1.4 is downloaded from steam

**Comment by aaaaeinai** [comment] 2017-12-25 14:06
If the file is named `(*) `
Here's what I did:
    Editor > Soft Reload Script

**Comment by akien-mga** [comment] 2018-09-18 09:32
The 2.1 branch is no longer actively worked on by engine developers, unless critical fixes are needed for current games in production. As such we are now closing non-critical bug reports affecting only the 2.1 branch.

Please comment if this was incorrectly triaged and is still relevant in 3.x versions.

**Closed by akien-mga** 2018-09-18 09:32 UTC
Labels: bug, topic:editor
