### ISSUE TITLE
Internationalization does not work on tr(message)  if  Locale->Test is empty in project settings

### ISSUE THREAD

**Issue by 1Googol** [godotengine/godot#80985] opened 2023-08-25 08:53 UTC
### Godot version

v4.1.1.stable.official [bd6af8e0e]

### System information

Godot v4.1.1.stable - Windows 10.0.22000 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3060 (NVIDIA; 30.0.14.7212) - Intel(R) Core(TM) i5-10400F CPU @ 2.90GHz (12 Threads)

### Issue description

- I am using gettext

- In my scene, button `简体中文` and  `English`  are both Localization disabled,  so ignore the lanuages they use in below images.

-  See one image below,  button `按钮` and `按钮2` should be show in English, but they are not, for now I only add a *.po file in `Localization->Translations`  and did nothing in `General` setting.
![image](https://github.com/godotengine/godot/assets/72542400/39eebc78-90eb-45d7-9d9a-8ec36dc2309a)

- Then I pressed button `English`  which will set locale to "en",  only `Button2` is in English as the image shows below. The diffrent between two buttons is `按钮` is set by `_button.text = tr("Button")`, and `Button2` is set in inspector. Check minimal reproduction project for  more details.
![image](https://github.com/godotengine/godot/assets/72542400/9f4fbeba-d954-476d-9669-fffcefae092d)

- But if you set any value in `General->Internationalization->Locale->Test`, everything will works fine like images show below.
![image](https://github.com/godotengine/godot/assets/72542400/c3d44395-27f3-455a-b5b5-17a2cb107029)
**It starts with default setting which is "en", and you can switch between `简体中文` and `English` correctly.**
![image](https://github.com/godotengine/godot/assets/72542400/d84ef927-aa15-4dcb-9838-a7704aee00dc)

![image](https://github.com/godotengine/godot/assets/72542400/f9dfc255-d704-4890-9a3c-d4ab9d8ef5a3)

![image](https://github.com/godotengine/godot/assets/72542400/f77b0312-fdfa-4b59-adce-77d3b03a18f5)

### Steps to reproduce

- Run Minimal reproduction project, you will see two buttons in center that shows `按钮` and `按钮2`  which is wrong, they should be in Englilsh.
- Press button `English` on top-left, you will see only `按钮2` changes from Chinese to English.
- Stop the project.
- Set any value to `General->Internationalization->Locale->Test`, then run the project, you will see everything works fine.

### Minimal reproduction project

[godot4.1-minimal-reproduction.zip](https://github.com/godotengine/godot/files/12437384/godot4.1-minimal-reproduction.zip)

**Comment by bruvzg** [comment] 2023-08-29 06:12
> The diffrent between two buttons is 按钮 is set by _button.text = tr("Button"), and Button2 is set in inspector. Check minimal reproduction project for more details.

Not a bug, `_button.text = tr("Button")` will translate text on start and therefore text value of the button will be translated text not an English key string and auto-transalate won't be able to translate it, use `_button.text = "Button"` instead or call `_button.text = tr("Button")` after changing the language again.

**Comment by akien-mga** [comment] 2023-08-29 06:22
And that's why it works with an invalid test locale, as `tr("Button")` then becomes `"Button"` so the value assigned to the text field is the po file msgid and can be translated.

**Closed by akien-mga** 2023-08-29 06:22 UTC
Labels: bug, topic:gui
