### ISSUE TITLE
Godot's Velocity property on CharacterBody2D and 3D does not work with C#'s `with` keyword

### ISSUE THREAD

**Issue by b4ux1t3** [godotengine/godot#86352] opened 2023-12-20 05:13 UTC
### Tested versions

Reproducible in 4.2.1, but not in 4.1.3.

### System information

Windows 10 and MacBook Pro M2

### Issue description

When attempting to change a `CharacterBody2D`'s `Velocity` using the `with` keyword in C#, any properties of the new `Vector2` not explicitly set in the expression will be set to `0` (the default value for a float).

This does not happen with a plain `Vector2`.

What's really interesting is that, when I went to test on Godot 4.1, and then moved back to Godot 4.2, the problem disappeared on my Mac, _even in a new project_. I have included a screenshot of the behavior from before this happened. ~~This also happened [live on a stream](https://www.twitch.tv/videos/2008960149), if more examples are necessary.~~ This was actually a logic bug, which made me try the above process. That's what I get for streaming at midnight. 

I did verify that this wasn't a bug with C# itself; I was unable to produce this either with the existing `System.Numerics.Vector2` nor a custom struct.

![Screenshot 2023-12-19 at 11 18 35 PM](https://github.com/godotengine/godot/assets/5150833/3f5e52bd-8577-4fb2-8f78-887f6e928fe9)

### Steps to reproduce

1. Create a new `CharacterBody2D` or `CharacterBody3D`
2. Set its `Velocity` using some method other than the `with` keyword.
3. Set its `Velocity` using the `with` keyword
4. The new `Velocity` will be missing properties which were not explicitly defined in the `with` expression.

### Minimal reproduction project (MRP)

N/A

**Comment by raulsntos** [comment] 2023-12-20 18:14
I'm unable to reproduce the issue. Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/4c1f11944ebfe1204f21c6ac488c7a2294e1d520/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

**Comment by b4ux1t3** [comment] 2023-12-20 19:44
@raulsntos I've been having trouble reliably getting it to reproduce. I'll upload the project I took the screenshot from, but it's only reproducing sometimes. 

I have a feeling this is an intermittent issue that's caused by some mechanism that's keeping the physics body's state synced between the .NET object and whatever backing object exists in the engine.

If you guys can't reproduce it, feel free to close this as not reproducible. When I opened the issue, I was mistaking it as the source of a rather large problem I was having, but upon further review, I have fixed the problem, and so I'm not sure how often this will actually come up.

[VectorTest.zip](https://github.com/godotengine/godot/files/13731567/VectorTest.zip)

**Comment by raulsntos** [comment] 2024-07-28 03:39
I don't really see how Godot could introduce such a bug, after all we have no control over the `with` keyword and it basically lowers to something like:

```csharp
// Original
Velocity = Velocity with { X = 1 };

// Lowered
Vector2 velocity = Velocity;
velocity.X = 1;
Velocity = velocity;
```

The only thing I can imagine failing here is the `Velocity` getter returning a zero vector, but the getter/setter is just a direct field access:

https://github.com/godotengine/godot/blob/607b230ffe120b2757c56bd3d52a7a0d4e502cfe/scene/2d/physics/character_body_2d.cpp#L425-L431

And I don't think the `velocity` field would be modified while the `_physics_process` callback of the script is executed.

Assuming there's a bug there, then it's not related to the `with` keyword and will likely also affect GDScript. But I was unable to reproduce the bug with the provided MRP. I'll close the issue as per the last comment, but if you are still able to reproduce the issue please comment here and it can be reopened.

**Closed by raulsntos** 2024-07-28 03:39 UTC
Labels: bug, needs testing, topic:dotnet, regression
