### ISSUE TITLE
Problems with NinePatchRect shrinking.

### ISSUE THREAD

**Issue by qq715152910** [godotengine/godot#37028] opened 2020-03-13 16:49 UTC
**Problems with NinePatchRect shrinking.**

**TEST:**

1.Use a 200x200 resolution picture, set the corner borders, and set the stretch to on.
2.Set rect_size to greater than 200x200, corners and borders are normal.
3. Set rect_size to less than 200x200, corners and borders will be reduced,Cocos and Unity will not have such a similar problem.

**ERROR:**
Set rect_size <200x200, corners and borders will be reduced.

**bottleneck:**
This will cause confusion for some 2D developers. If a picture is reduced from 200x200 to 100x100 and the corners and borders remain the same, this is definitely a bottleneck for now.

**Suggest:**
Add an Option to the Control-> NinePatchRect property menu to let developers freely choose whether it is turned on to reduce the size and keep the corner borders unchanged. At present, this will be the demand of many 2D developers.

**Comment by Nate-Wilkins** [comment] 2020-03-13 16:53
Hey thanks for reporting this issue! However, this issue appears to be a duplicate of https://github.com/godotengine/godot/issues/37027 could we close this out? 

Nate

**Comment by Ev1lbl0w** [comment] 2020-03-13 16:58
Can you provide a sample project replicating this? I tried, but I probably didn't understood the issue, and couldn't reproduce it.

**Comment by qq715152910** [comment] 2020-03-13 16:58
> 谢谢您报告此问题！但是，此问题似乎与[＃37027](https://github.com/godotengine/godot/issues/37027)重复，我们可以解决此问题吗？
> 
> 内特

Sorry, my network is not very good, the delay caused the second submission, thank you for your reminder.

**Comment by akien-mga** [comment] 2020-03-13 17:01
Closing as duplicate of #37027.

**Closed by akien-mga** 2020-03-13 17:01 UTC

**Comment by qq715152910** [comment] 2020-03-13 19:47
> 您可以提供一个示例项目来复制吗？我尝试过，但是我可能不理解这个问题，并且无法重现它。
https://github.com/godotengine/godot/issues/37027#issue-580721790

**Comment by qq715152910** [comment] 2020-03-14 07:40
&gt;
When zooming out, the border cannot maintain the original size, and the pixels are completely distorted.
[Demo-Download](https://codeload.github.com/qq715152910/Godot-Bug/zip/master)



Demo reported that the dog problem has been closed in the past?&nbsp; But I didn't receive any response. Can I solve it?


---Original---

**Comment by qq715152910** [comment] 2020-03-14 08:49
> Can you provide a sample project replicating this? I tried, but I probably didn't understood the issue, and couldn't reproduce it.

**Demo:**
[Demo-Download](https://codeload.github.com/qq715152910/Godot-Bug/zip/master)

**Comment by qq715152910** [comment] 2020-03-14 08:51
> 您可以提供一个示例项目来复制吗？我尝试过，但是我可能不理解这个问题，并且无法重现它。

**Demo:**
[Demo-Download](https://codeload.github.com/qq715152910/Godot-Bug/zip/master)
