### ISSUE TITLE
sort_script_by None is not working correctly

### ISSUE THREAD

**Issue by TyTYct** [godotengine/godot#27831] opened 2019-04-09 01:40 UTC
**Godot version:**

v3.1 stable

**OS/device including version:**

Windows 10 64 bit

**Issue description:**

sort_script_by None is not working correctly

**Steps to reproduce:**
Step 1. Set sort_script_by None
![image](https://user-images.githubusercontent.com/8284805/55766846-aa4dbf80-5aa0-11e9-867a-c19129ca83ca.png)

Step 2. Move some script to top
![image](https://user-images.githubusercontent.com/8284805/55766906-e41ec600-5aa0-11e9-882b-0321fbc02b1b.png)

Step 3. Open a help script for updating sorting script
![image](https://user-images.githubusercontent.com/8284805/55766956-14666480-5aa1-11e9-8ab4-628b974cb217.png)

Step 4. Scripts that were moved to top, move to end. I see that the order of these script was reversed.
![image](https://user-images.githubusercontent.com/8284805/55766993-3829aa80-5aa1-11e9-92c8-9b3dac514da8.png)

**Minimal reproduction project:**

**Comment by samH-FIT** [comment] 2019-04-09 16:52
Working on it!

**Comment by Paulb23** [comment] 2019-04-09 19:12
Duplicate of #23455 and #26078

**Closed** 2019-04-09 20:42 UTC
Labels: bug, junior job, topic:editor, usability
