### ISSUE TITLE
Can not close the shader script, even after deleting the shaders it gets recreated

### ISSUE THREAD

**Issue by Ymanawat** [godotengine/godot#82518] opened 2023-09-29 09:16 UTC
### Godot version

v4.1.1 stable,  v4.2.dev (f9004b52f)

### System information

Godot v4.2.dev (f9004b52f) - Windows 10.0.22621 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3050

### Issue description

There is no option to close a shader script. I did open a shader and then removed it also deleted the script. But I can't close the script as there is no option to close it. When I restart the editor that shader file automatically gets created, An empty file. When we close the editor.
b&w.gdshader below 

![Screenshot 2023-09-29 143135](https://github.com/godotengine/godot/assets/81252768/d6220730-f4c9-43d3-8c0f-13148c72d878)
![Screenshot 2023-09-29 143128](https://github.com/godotengine/godot/assets/81252768/314b83cc-dbbd-4eb8-804d-75080f0fb66e)

### Steps to reproduce

1. Create a new shader script and then open it.
2. Detach the shader and close the editor
3. Delete that shader file from explorer
4. Open Godot see that shader file still open but blank
5. Now close the editor and open the same directory file will be there

### Minimal reproduction project

[Shader file Bug.zip](https://github.com/godotengine/godot/files/12762948/Shader.file.Bug.zip)

**Comment by bitsawer** [comment] 2023-09-29 09:28
Thanks for the report. The deleted shader file reappearing issue has been fixed in master by https://github.com/godotengine/godot/pull/80705 and related PR's.

You can close shader files in the editor by middle mouse click or selecting "File -> Close File":

![close](https://github.com/godotengine/godot/assets/22456603/1e8cf231-08f8-4276-8103-ab6717926396)

Closing, as the issue is fixed in current master.

**Closed by bitsawer** 2023-09-29 09:28 UTC
