### ISSUE TITLE
4.2 crashes when renaming input maps in single window mode

### ISSUE THREAD

**Issue by RecruitZer0** [godotengine/godot#86165] opened 2023-12-14 17:36 UTC
### Tested versions

- Reproducible in 4.0+
- Non reproducible in older versions

### System information

Godot v4.2.1.stable - Windows 10.0.19045 - Vulkan (Mobile) - dedicated AMD Radeon RX 580 2048SP (Advanced Micro Devices, Inc.; 31.0.21905.1001) - AMD Ryzen 5 2400G with Radeon Vega Graphics (8 Threads)

### Issue description

In the input map menu, if you rename an action, and instead of pressing enter, you click on another action, the engine crashes. This only happens if you have Single Window Mode enabled, if you click anywhere else other than an action, it works, and pressing enter obviously works as intended. I did some quick tests and this problem only seems to happen in 4.x versions.

### Steps to reproduce

1. Enable Single Window Mode (Editor Settings: interface/editor/single_window_mode) and restart the editor
2. Open the Project Settings and go to the Input Map tab
3. Create 2 actions
4. Click on one of them and change it's name
5. Click on the other one

### Minimal reproduction project (MRP)

[crashing_issue.zip](https://github.com/godotengine/godot/files/13676443/crashing_issue.zip)

**Comment by jsjtxietian** [comment] 2023-12-15 04:40
Confirmed on Godot v4.3.dev (b94eb58d3) - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3060 (NVIDIA; 31.0.15.3619) - 11th Gen Intel(R) Core(TM) i7-11700K @ 3.60GHz (16 Threads)

**Comment by KoBeWi** [comment] 2024-07-25 21:29
Duplicate of #86612

**Closed by KoBeWi** 2024-07-25 21:29 UTC
Labels: bug, topic:editor, needs testing, topic:input, crash
