### ISSUE TITLE
Folded lines in the script editor unfold when Backspace is pressed on the line below it

### ISSUE THREAD

**Issue by metodmiha** [godotengine/godot#95778] opened 2024-08-18 22:03 UTC
### Tested versions

Reproduced in 4.3.stable, 4.2.2.stable, 4.2.stable, 4.1.stable, 4.0.stable, 3.6.rc1, 3.5.stable and 3.0.stable, although it seems it's a bug even further in regression.

### System information

Godot v4.3.stable - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1650 SUPER (NVIDIA; 31.0.15.3623) - Intel(R) Core(TM) i5-9400F CPU @ 2.90GHz (6 Threads)

### Issue description

Folded lines in the GDScript editor will open up when Backspace (but not Delete) is pressed on the line below it (ignores indents). This should not affect the folded line, the same way pressing the Delete key does. This bug makes managing large folded chunks of code (large code in if/elif statements and match statements) more tedious because the large hidden chunk of code in the folded line reopens when editing the next statement in the if/elif or match statement.

https://github.com/user-attachments/assets/055ebd53-13b6-4aa7-86e5-ebb1feee960b

### Steps to reproduce

1. Fold a line in a script.
2. On the line below it, press Backspace.
3. The folded line unfolds.

### Minimal reproduction project (MRP)

[Open the project in the Test.zip and open the a.gd script, then use the steps shown](https://github.com/user-attachments/files/16652417/Test.zip)

**Comment by kitbdev** [comment] 2024-08-19 15:22
- duplicate of https://github.com/godotengine/godot/issues/89522
- fixed by https://github.com/godotengine/godot/pull/89554

**Closed** 2024-08-19 16:34 UTC
Labels: bug, topic:editor, topic:gui
