### ISSUE TITLE
MeshInstances Randomly Disappearing/Reappearing In Scene

### ISSUE THREAD

**Issue by WickedInsignia** [godotengine/godot#50630] opened 2021-07-20 05:27 UTC
### Godot version

3.3.2 Stable

### System information

Windows 10 v20H2, Intel i7 6700, Nvidia GTX1080, 16GB RAM

### Issue description

I am experiencing completely random disappearances of MeshInstances. I primarily work with a "Main Scene", where the meshes are part of an inherited scene (the "Mesh Scene") that is then placed into this main scene.
I have encountered MeshInstances disappearing from both a Main Scene and Mesh Scene many times.

When it occurs the MeshInstance may still be selected, but the mesh is no longer visible and Godot does not recognize an assigned mesh in the Inspector. This happens most when both the Main Scene and Mesh Scene are open, and changes to the Mesh Scene have been saved. When going back to the Main Scene, a completely random meshinstance will no longer be visible. Sometimes it is also vice versa

Closing the scene usually rectifies the issue, but I have had meshes stay invisible upon reopening.
The "invisible" mesh is always different....if I have multiple MeshInstances in a scene, it is a completely random guess which one may disappear.

### Steps to reproduce

This is a very difficult bug to reproduce since it seems to happen only when a scene reaches a certain amount of complexity or has been worked on for a period of time.

I've managed to capture it happening however. Here is the Mesh Scene in this circumstance:
![DisappearingMeshes_Example_01](https://user-images.githubusercontent.com/70243134/126265863-b5728ff2-ee55-4648-9d4b-c4d09fec6007.JPG)

And here is the Main Scene. I had made some material roughness changes to the "room" mesh and upon going back I found one of the other meshes was randomly missing:
![DisappearingMeshes_Example_02](https://user-images.githubusercontent.com/70243134/126265959-95672c09-76aa-4064-b9f1-e3cf3028b022.JPG)

Closing and reopening the project rectified the issue, but I know from experience that once it starts happening it will happen again shortly.

### Minimal reproduction project

In an attempt to reproduce the bug I created a file that reflected the contents of the other projects that in appeared in:
- A "Main Scene" with a "Mesh Scene" placed inside containing all of my MeshInstances for the scene.
- A GIProbe encompassing the meshes.
- A Reflection Probe doing the same.
- A Directional Light.
- Mutiple MeshInstances in the Mesh Scene with different materials.

I played around with the file for a bit until the bug occurred, and captured the screenshots above.
The file I created (packed into a zip as soon as the bug occurred) is available here:
[Disappearing_Mesh_Bug.zip](https://github.com/godotengine/godot/files/6845673/Disappearing_Mesh_Bug.zip)

This file most likely won't exhibit the bug immediately, but playing with the meshes and their materials in the Mesh Scene will coax it out.

**Comment by lawnjelly** [comment] 2021-07-20 16:45
> When it occurs the MeshInstance may still be selected, but the mesh is no longer visible and Godot does not recognize an assigned mesh in the Inspector.

I did try the project just in case it was the culling code, but on reflection I think the problem is unlikely to be there - culling wouldn't cause changes within the inspector.

**Comment by tinmanjuggernaut** [comment] 2021-11-05 23:55
This issue is almost certainly the same as #53374. This report doesn't provide any console errors. Please compare your messages with the ones given in the other issue. You can also try the workaround, and the upcoming PR.

**Comment by akien-mga** [comment] 2021-12-09 21:09
Likely duplicate of #53374 indeed, fixed by #54650.

**Closed by akien-mga** 2021-12-09 21:09 UTC
Labels: bug, topic:editor, needs testing, topic:3d
