### ISSUE TITLE
TileMap Artifacts Android Export

### ISSUE THREAD

**Issue by gravit22** [godotengine/godot#83666] opened 2023-10-20 10:20 UTC
### Godot version

4.1.2

### System information

Godot v4.1.2.stable - Ubuntu 22.04.3 LTS 22.04 - X11 - Vulkan (Compatibility) - NVIDIA GeForce GTX 1060 3GB (nvidia; 525.125.06) - AMD Ryzen 9 3900X 12-Core Processor (24 Threads)

### Issue description

When I export for android projects that use TileMap's terrains, I see artifacts, but only on real mobile phone. I can't see them on Android studio emulator. I tested it on Pixel 6a, but it seems that other phones have the same issue. 
Terrain do not work, and tiles are unpredictably distorted.

### Steps to reproduce

I provided minimal project. 
1. Just export android project
2. Install on mobile phone(emulator might not replicate that issue)
3 compare to android studio emulator variant or run the project on PC

### Minimal reproduction project

[Bug report.zip](https://github.com/godotengine/godot/files/13053116/Bug.report.zip)

**Comment by groud** [comment] 2023-10-20 10:50
Closing as duplicate of https://github.com/godotengine/godot/issues/71020

**Closed by groud** 2023-10-20 10:50 UTC
