### ISSUE TITLE
Issue with Mesh retaining Texture when draging a .Tres file over it in the Workspace

### ISSUE THREAD

**Issue by Minecrft-101** [godotengine/godot#75417] opened 2023-03-28 09:49 UTC
### Godot version

V4.0.1.stable.official.cacf49999

### System information

Windows 11, Forward+, NVIDIA GeForce GTX 1060 Laptop

### Issue description

When I created a texture file for easier future change, and attempted to apply it to a mesh, if I dragged over another mesh in the process, it would lose its already assigned texture. What would be expected  

### Steps to reproduce

Create multiple meshes and drag a .TRES file texture over the mesh but don't end on the mesh

### Minimal reproduction project

N/A

**Comment by Calinou** [comment] 2023-04-01 17:13
- Duplicate of https://github.com/godotengine/godot/issues/74077.

**Closed by Calinou** 2023-04-01 17:13 UTC
Labels: bug, topic:editor, topic:3d
