### ISSUE TITLE
bug? texts cannot be copied

### ISSUE THREAD

**Issue by Torguen** [godotengine/godot#60234] opened 2022-04-14 09:09 UTC
### Godot version

v3.5.beta3.official [3c0d32562]

### System information

win10 64

### Issue description

I'm not sure it's a bug, I think so, that this behavior is not expected by anyone.
You just can't copy the texts.
I select the text, press the right mouse button, a deselection occurs and then the menu appears to copy etc...

https://user-images.githubusercontent.com/19652075/163353074-11aa52fb-3c4d-4e09-ad34-0843137e68fb.mp4

### Steps to reproduce

See the video

### Minimal reproduction project

...

**Comment by ConteZero** [comment] 2022-04-14 13:36
Probably a duplicate of https://github.com/godotengine/godot/issues/59808

**Comment by Calinou** [comment] 2022-04-14 15:41
@Torguen Can you reproduce this on 3.4.4?

**Comment by Torguen** [comment] 2022-04-14 15:48
It works correctly in 3.4.4

https://user-images.githubusercontent.com/19652075/163426457-65c084d9-3c07-4ee7-a309-130a4bad9308.mp4

**Comment by ConteZero** [comment] 2022-04-14 15:49
I've submitted a pull request that is waiting for review https://github.com/godotengine/godot/pull/59827
@Torguen you can try if it solves the problem

**Comment by Calinou** [comment] 2022-04-14 16:29
Duplicate of https://github.com/godotengine/godot/issues/59808.

**Closed by Calinou** 2022-04-14 16:29 UTC
Labels: bug, regression, topic:gui
