### ISSUE TITLE
[C#] Godot 4 .NET 6 takes far too long to `free` custom node extended classes.

### ISSUE THREAD

**Issue by asolux** [godotengine/godot#68375] opened 2022-11-07 13:53 UTC
### Godot version

3.5, 4.0.beta4

### System information

Windows 10, 64bit

### Issue description

I created four test projects:
- GD Script, Godot 3.5
- GD Script, Godot 4 Beta 4
- Mono, Godot 3.5
- .NET 6, Godot 4 Beta 4

In this minimalist projects, 3000 nodes are added to a node as a child and then removed again. 

However, C# under Godot 4 takes a devastatingly long time.
Example output:
```
# Adding and removing 3000 nodes

# Godot 3.5 Mono

elapsed time (Dummy): 0.782 sec 
elapsed time (Node): 0.075 sec

# Godot 4 Beta 4

elapsed time (Dummy): 4.674 sec 
elapsed time (Node): 0.079 sec

# Godot 3.5 GD-Script

elapsed time (Dummy): 0.103 
elapsed time (Node): 0.068

# Godot 4 Beta 4 GD-Script

elapsed time (Dummy): 0.094 
elapsed time (Node): 0.067
```

In another test project, I have about 2300 nodes that do a little more in the background, such as cutting out random parts from the standard icon and arranging them one after the other in a container node.
Here Godot 4 .Net 6 needs about 14 seconds whereas 3.5 Mono only needs about 4 seconds.

### Steps to reproduce

C# example code as used in the 4 sample projects:
```csharp
// public partial class Dummy : Node { }
// _nodeContainer = GetNodeOrNull<Node>("NodeContainer");

//
// Adding a custom class extended from Godot.Node
//

var millisStartDummy = Time.GetTicksMsec();

for (int i = 0; i < 3000; i++)
{
	var node = new Dummy();
	_nodeContainer.AddChild(node);
}

foreach (Node node in _nodeContainer.GetChildren())
{
	if (node.GetParent() != null)
	{
		node.GetParent().RemoveChild(node);
		node.Free();
	}
}

ulong millisEndDummy = Time.GetTicksMsec();
float millisDummy = millisEndDummy - millisStartDummy;

//
// Add Native Godot.Node nodes
//

var millisStartNode = Time.GetTicksMsec();

for (int i = 0; i < 3000; i++)
{
	var node = new Node();
	_nodeContainer.AddChild(node);
}

foreach (Node node in _nodeContainer.GetChildren())
{
	if (node.GetParent() != null)
	{
		node.GetParent().RemoveChild(node);
		node.Free();
	}
}

ulong millisEndNode = Time.GetTicksMsec();
float millisNode = millisEndNode - millisStartNode;

var text = new string[] {
	"elapsed time (Dummy):", (millisDummy / 1000).ToString("#,##0.000 sec."),
	"\nelapsed time (Node):", (millisNode / 1000).ToString("#,##0.000 sec.")
};

GD.PrintS(text);
```

### Minimal reproduction project

[BenchNodeRemoveAdd_GD_Godot3.5.zip](https://github.com/godotengine/godot/files/9952098/BenchNodeRemoveAdd_GD_Godot3.5.zip)
[BenchNodeRemoveAdd_GD_Godot4b4.zip](https://github.com/godotengine/godot/files/9952099/BenchNodeRemoveAdd_GD_Godot4b4.zip)
[BenchNodeRemoveAdd_Godot3.5.zip](https://github.com/godotengine/godot/files/9952100/BenchNodeRemoveAdd_Godot3.5.zip)
[BenchNodeRemoveAdd_Godot4b4.zip](https://github.com/godotengine/godot/files/9952101/BenchNodeRemoveAdd_Godot4b4.zip)

**Comment by Redwarx008** [comment] 2022-11-09 02:01
This seems to be related to adding as child nodes.
I changed to the following code for testing.
``` c#
    private List<Node> _nodeContainer;
    public void OnStart()
    {
        Stopwatch sw = Stopwatch.StartNew();
        sw.Start();
        for (int i = 0; i < ITERATIONS; i++)
        {
            var node = new Dummy();
            _nodeContainer.Add(node);
        }
        sw.Stop();
        Console.WriteLine("create extend nodes cost time:" + sw.ElapsedMilliseconds + "ms");
        sw.Restart();
        foreach (Dummy node in _nodeContainer)
        {
            node.Free();
        }
        sw.Stop();
        Console.WriteLine("delete extend nodes cost time:" + sw.ElapsedMilliseconds + "ms");

        _nodeContainer.Clear();
        sw.Restart();
        for (int i = 0; i < ITERATIONS; i++)
        {
            var node = new Node();
            _nodeContainer.Add(node);
        }
        sw.Stop();
        Console.WriteLine("create nodes cost time:" + sw.ElapsedMilliseconds + "ms");
        sw.Restart();
        foreach (Node node in _nodeContainer)
        {
            node.Free();
        }
        sw.Stop();
        Console.WriteLine("delete nodes cost time:" + sw.ElapsedMilliseconds + "ms");
    }
```
Here are the results
```
create extend nodes cost time:9ms
delete extend nodes cost time:11ms
create nodes cost time:5ms
delete nodes cost time:4ms
```

**Comment by asolux** [comment] 2022-11-09 11:05
One possibility is also to remove the parent node and create it afterwards. It also doesn't slow down the next frame. This variant is the fastest in my tests at only 3 ms.

```csharp
// ...
sw.Start();
_nodeContainer.QueueFree();
_nodeContainer = new Node();
GetTree().Root.AddChild(_nodeContainer);
sw.Stop();
```
Result:
```
delete extend nodes cost time: 0.003 sec.
```

However, 3.5.x was faster when removing nodes in a loop. Maybe there is a possibility that the performance can be improved a bit here. Since GD-Script is faster than anything else here.

**Comment by neikeq** [comment] 2022-11-10 02:37
I'll look into this when I get some time.

> I checked it out in a profiler, and the issue seems to be that InvokeGodotClassMethod is doing a _lot_ of string comparisons.

`InvokeGodotClassMethod` doesn't do string comparisons. It compares string names, which is a pointer comparison.

**Comment by touilleMan** [comment] 2022-11-12 18:57
#67750 has been merged, can you test again to see if the slowdown is still present ?

**Comment by neikeq** [comment] 2022-11-13 07:36
> #67750 has been merged, can you test again to see if the slowdown is still present ?

Nope, C# still doesn't use GDExtension (it's coming this month), and it already uses StringName internally.

**Comment by akien-mga** [comment] 2023-06-23 13:48
Can you still reproduce this in 4.0.3 and 4.1-beta3 or later?

**Comment by pkdawson** [comment] 2023-06-23 16:12
In 4.1-beta3, the benchmark projects still show a significant difference (C# is about 3x slower), but this is a massive improvement from the originally reported ~50x difference.

**Comment by asolux** [comment] 2023-06-23 17:48
It's much better now and appears to have been fixed. I didn't compare it with GD Script or version 3.5, just the  4.x C# versions.
With the same C# code with 3000 nodes that are added and then removed in a loop, I get the following output:

```
Version 4.0 Beta 3
===================

create extend nodes, cost time: 0.068 sec.
delete extend nodes, cost time: 4.637 sec.
create nodes cost time: 0.013 sec.
delete nodes cost time: 0.068 sec.

Version 4.0.0
===================

create extend nodes, cost time: 0.047 sec.
delete extend nodes, cost time: 4.691 sec.
create nodes cost time: 0.014 sec.
delete nodes cost time: 0.070 sec.

Version 4.1 Beta 3
===================

create extend nodes, cost time: 0.049 sec.
delete extend nodes, cost time: 0.043 sec.
create nodes cost time: 0.013 sec.
delete nodes cost time: 0.015 sec.
```

**Comment by akien-mga** [comment] 2023-06-23 18:01
Thanks, closing as fixed then.

**Closed by akien-mga** 2023-06-23 18:01 UTC
Labels: bug, needs testing, topic:dotnet, performance
