### ISSUE TITLE
Visible collision shapes leads to a flood of errors

### ISSUE THREAD

**Issue by Zireael07** [godotengine/godot#62116] opened 2022-06-16 16:09 UTC
### Godot version

4.0 alpha 10

### System information

Linux Manjaro, Vulkan, Intel Kaby Lake

### Issue description

Enabled Visible Collision Shapes and saw a flood of errors (in the thousands). Something something instance_cull()

Goes back to alpha 6 certainly.

### Steps to reproduce

Open a project, enable visible collision shapes.

### Minimal reproduction project

N/A

**Comment by and-rad** [comment] 2022-06-16 16:22
Might be platform-related. Can't reproduce on Win 10, Vulkan Clustered, nVidia RTX 2060.

**Comment by Calinou** [comment] 2022-06-16 16:39
@Zireael07 Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

**Comment by rburing** [comment] 2022-08-03 18:21
Please specify the "something something" error.

Maybe (partly) fixed by https://github.com/godotengine/godot/pull/63692.

**Comment by Zireael07** [comment] 2022-08-03 18:25
Update: experiencing something similar but with alpha 13 and the error is E 0:00:16:0544   instance_set_transform: Condition "!instance" is true.
  <C++ Source>   servers/rendering/renderer_scene_cull.cpp:857 @ instance_set_transform()

(thank whoever implemented copy from output and copy error functions)

**Comment by rburing** [comment] 2022-08-03 18:38
That's https://github.com/godotengine/godot/issues/63577 which was fixed in https://github.com/godotengine/godot/pull/63692, just after 4.0 alpha 13. The fix will be included in the next release :slightly_smiling_face: 

I'll close this for now then; we could reopen if other errors related to visible collision shapes arise.

**Closed by rburing** 2022-08-03 18:38 UTC
Labels: bug, topic:physics, regression, topic:3d
