### ISSUE TITLE
Bad class / editor icons can slow down editor

### ISSUE THREAD

**Issue by bion33** [godotengine/godot#42096] opened 2020-09-15 16:39 UTC
**Godot version:**

3.2.2

**OS/device including version:**

Windows 10, Linux Mint 20

**Issue description:**

Classes which have an icon can slow down the editor tremendously if they are used frequently on nodes in a scene, unless they are optimized exactly according to [this documentation](https://docs.godotengine.org/en/stable/development/editor/creating_icons.html?highlight=editor%20icons). This isn't clear the first time someone comes across [adding icons to classes](https://docs.godotengine.org/en/stable/getting_started/step_by_step/scripting_continued.html?highlight=class_name#register-scripts-as-classes) and can lead to the wrong conclusion that Godot is slow, instead of it being an issue caused by the user.

The impact of unoptimized icons is unexpected, and it is not clear when this is the cause. Perhaps a hint that the icons are too large, not loading them if this is the case, mentioning this clearly in the documentation the first time new users see their use, or some other solution could solve this.

**Steps to reproduce:**
- Take a large SVG or PNG image
- Create a script using class_name and add the image as its icon
- Attach the script to a node in a scene
- Duplicate that node a number of times (depending on how "bad" the icon is, it could be noticeable from anywhere between 10 and 100 times, and have a pretty tremendous impact)
- Notice that the editor becomes noticeably slower (creating nodes, changing order, opening & closing Editor settings,...) 

**Minimal reproduction project:**

[Icon Issue Project.zip](https://github.com/godotengine/godot/files/5226393/Icon.Issue.Project.zip)

**Comment by Calinou** [comment] 2020-09-15 17:43
The solution to this is likely to print a warning message if an icon took a long time to generate.

**Comment by dzil123** [comment] 2022-11-06 14:22
Duplicate of #36981?

**Closed** 2022-11-06 17:26 UTC
Labels: enhancement, topic:editor, performance
