### ISSUE TITLE
OBJ files and DAE (better dae) are not imported correctly. Absent in .import folder.

### ISSUE THREAD

**Issue by n-pigeon** [godotengine/godot#8741] opened 2017-05-13 10:10 UTC
**Ubuntu - Godot 3.0-master (e883cda)**

**Issue description:**
3.0 Obj and DAE are not imported correctly. They are absent in .import folder.
Loading .obj to mesh instance is not working - "not a resource".
Opening DAE also - "Error loading scene".

**Comment by n-pigeon** [comment] 2017-05-13 10:29
I think reopening Editor fixes .dae imports.

**Comment by Gibbz** [comment] 2017-05-13 10:34
You can also re-export the mesh after the initial import, then that seems to fix it also without closing the editor.
May need to delete the mesh first if that doesnt work.

**Comment by reduz** [comment] 2017-05-24 11:31
I can't reproduce this, so any help with more steps to reach this situation are appreciated

**Comment by Gibbz** [comment] 2017-05-24 11:37
So i usually have both blender and godot editor open.
I just export (better collada) directly into my_project/mesh/ directory.
Tab back into the editor, it will "import" but it shows a different icon from the usually dae. (included screenshot of a quick test)
![import](https://cloud.githubusercontent.com/assets/650506/26401402/e7b10816-40c4-11e7-8c3f-4f1b42e4e4f3.jpg)

**Comment by n-pigeon** [comment] 2017-05-24 13:40
@reduz 
I just export .dae to my project.
Then I try to open it as a scene.
Fails. Not much to add.

Restarting editor seems to import them correctly.

**Comment by akien-mga** [comment] 2017-06-15 12:28
Is this still valid now?

**Comment by reduz** [comment] 2017-06-17 18:10
I seriously can't reproduce this, did you maybe switch to godot before the file is done exporting? if so Godot might find it invalid and you will have to reimport manually.. but this is normal behavior.

**Comment by n-pigeon** [comment] 2017-06-17 18:27
Will check it later, sorry can't right now. :B

**Comment by n-pigeon** [comment] 2017-06-17 20:08
@reduz
I've tested it and it works although not entirely.
It creates dae-name.dea.import file.
And when I change original dae file it doesn't update, displaying old data.

**Comment by sketchyfun** [comment] 2017-06-19 00:16
I played around with a 3.0 windows build today (12/13th June build) and I noticed when I updated an OBJ file, godot detected the change and showed the import progress bar, but once it had finished, it was still the old version of the mesh being displayed. Even when I deleted the meshinstance node, re-added it and selected the mesh file again, it was still the old version. The only way I could make it work (didn't try restarting the editor) was to save my OBJ file with a new name so it did a fresh import

**Comment by reduz** [comment] 2017-08-22 12:17
I did many changes to this, would appreciate testing again. The type and resource should definitely be recognized always now..

**Comment by mhilbrunner** [comment] 2017-10-31 01:48
Maybe close this if there are no further updates?

**Closed** 2017-10-31 08:12 UTC
Labels: bug, topic:core
