### ISSUE TITLE
Animation Copy + Paste copies by reference (preserves ExtResource), unlike Duplicate

### ISSUE THREAD

**Issue by hsandt** [godotengine/godot#46518] opened 2021-02-28 16:52 UTC
**Godot version:** 3.2.3

**OS/device including version:** Linux Ubuntu 18.04

**Issue description:**

When copying and pasting an animation in the Animation window (when working on an AnimationPlayer), the new animation is actually a clone by reference of the original animation. This can be verified by inspecting the scene containing the AnimationPlayer. If you copy and paste, then duplicate an animation you will see something like this in the .tscn:

```
[node name="AnimationPlayer" type="AnimationPlayer" parent="."]
anims/ANIM_NonPlayerCharacter_Idle_Left = ExtResource( 7 )
"anims/ANIM_NonPlayerCharacter_Idle_Left 2" = ExtResource( 7 )
"anims/ANIM_NonPlayerCharacter_Idle_Left 2 (copy)" = SubResource( 3 )
```

with the same ExtResource ID for Copy-Pasted animation, but a different one for Duplicated animation (note that the last one is SubResource simply because I didn't save it in an external asset file yet).

**Steps to reproduce:**

1. In a scene, create an animation player
2. In the Animation window, create a first animation ANIM_Original
3. (optional) Add a key point to modify some property of some accessible object. If you have a spritesheet you can select a sprite frame to make differences between animations visible at a glance.
4. Click on Animation > Copy then again Animation > Paste. Default name is ANIM_Original 2 but you can rename it ANIM_Copy for clarity.
5. Either from the original or this copy, click on Animation > Duplicate. Default name is suffixed (copy) but you can rename it ANIM_Duplicate for clarity.
6. Open the scene in a file editor and observe the properties of the animation player. It should contain SubResource with same ID for ANIM_Original and ANIM_Copy, but a different one for ANIM_Duplicate.
7. (optional) If you did 3, modify a key property value on ANIM_Original and see the change occur on ANIM_Copy, but not ANIM_Duplicate.
8. (optional) Now try to Save (not Save as) the animations one by one. Note that ANIM_Duplicate prompts for save location since it's the first time you saved it, while ANIM_Original and ANIM_Copy are the same, therefore only the first one will prompt for save location. This is actually how I discovered the bug, I only checked scene file content later.

Expected: both operations should copy animation by value (deep copy) and generate a different asset.
Of course, if you really want to keep copy by reference then it's possible, but I'd recommend having a different command "Paste by reference". Users probably expect Copy + Paste to be equivalent to Duplicate (excepted for name suffix I guess), and in most cases we want a deep copy, e.g. to make animations for a character turned up, left, right, down.

**Minimal reproduction project:**

Just reproduce it from scratch in a new project, no asset nor project config is needed to reproduce this bug, a dummy spritesheet can just help visualize things.

**Comment by Calinou** [comment] 2021-02-28 17:58
Duplicate of https://github.com/godotengine/godot/issues/30197.

**Closed by Calinou** 2021-02-28 17:58 UTC
