### ISSUE TITLE
Typed variable has wrong type if assigned from untyped function

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#34791] opened 2020-01-03 19:37 UTC
**Godot version:**
71d372a8a

**Issue description:**
This fails:
```
func test():
	return true

func _ready():
	var a: int = test()
	if a == 1:
		print("Ok?")
```
![image](https://user-images.githubusercontent.com/2223172/71744768-8c16c380-2e68-11ea-9ca3-b545ec7bad1d.png)

If the function is typed or you use `var a: int = true`, it will work. I'd expect that a typed variable is properly converted in all cases.

**Comment by bojidar-bg** [comment] 2020-01-04 09:27
I think resolving this might indirectly lessen the effects of #24035.

**Comment by dalexeev** [comment] 2020-01-06 05:01
This is a duplicate of #32905.

The error occurs only when a variable is declared in a certain way:

```gdscript
func test():
    return true

func _ready():
    var a: int = test()
    var b := test() as int
    var c := int(test())
    prints(a is int, b is int, c is int)
    # False True True
```

**Closed** 2020-01-08 16:36 UTC
Labels: bug, topic:gdscript
