### ISSUE TITLE
FATAL: Index p_index = 3 is out of bounds (size() = 3) when deleting Polygon2D nodes (e.g. for Tileset occlusion layer) while moving them

### ISSUE THREAD

**Issue by filpano** [godotengine/godot#86562] opened 2023-12-27 19:40 UTC
### Tested versions

- Reproducible in v4.2.1.stable.official [b09f793f5]

### System information

Linux LT-dev-Ubuntu 6.2.0-37-generic #38~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Thu Nov  2 18:01:13 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

### Issue description

When drawing a 2D polygon, like for example an occlusion layer for a tileset, it is possible to delete a node with right click or delete.
If this is done to a point that it being moved, the following fatal error occurs:

```
ERROR: FATAL: Index p_index = 3 is out of bounds (size() = 3).
   at: get (./core/templates/cowdata.h:158)

================================================================
handle_crash: Program crashed with signal 4
Engine version: Godot Engine v4.2.1.stable.official (b09f793f564a6c95dc76acc654b390e68441bd01)
Dumping the backtrace. Please include this when reporting the bug to the project developer.
[1] /lib/x86_64-linux-gnu/libc.so.6(+0x42520) [0x7fad9ba42520] (??:0)
[2] /home/dev/Desktop/Godot/Godot_v4.2.1-stable_linux.x86_64() [0x1f4d253] (??:0)
[3] /home/dev/Desktop/Godot/Godot_v4.2.1-stable_linux.x86_64() [0x3b92560] (??:0)
[4] /home/dev/Desktop/Godot/Godot_v4.2.1-stable_linux.x86_64() [0x206efad] (??:0)
[5] /home/dev/Desktop/Godot/Godot_v4.2.1-stable_linux.x86_64() [0x401d4cd] (??:0)
[6] /home/dev/Desktop/Godot/Godot_v4.2.1-stable_linux.x86_64() [0x3b8f5dc] (??:0)
[7] /home/dev/Desktop/Godot/Godot_v4.2.1-stable_linux.x86_64() [0x20ebd43] (??:0)
[8] /home/dev/Desktop/Godot/Godot_v4.2.1-stable_linux.x86_64() [0x4f8c3e] (??:0)
[9] /home/dev/Desktop/Godot/Godot_v4.2.1-stable_linux.x86_64() [0x41ed28] (??:0)
[10] /lib/x86_64-linux-gnu/libc.so.6(+0x29d90) [0x7fad9ba29d90] (??:0)
[11] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0x80) [0x7fad9ba29e40] (??:0)
[12] /home/dev/Desktop/Godot/Godot_v4.2.1-stable_linux.x86_64() [0x42aa6a] (??:0)
-- END OF BACKTRACE --
================================================================
```

*This only occurs if there are 3 points*, which should "delete" the polygon. If there are 4 of more points, the error does not occur.

### Steps to reproduce

1. Open a tileset
2. Choose "paint"
3. Select a layer to draw on (e.g. occlusion, physics)
4. Delete points until there are only 3 left
5. Select one randomly 
6. While still moving it, press right-click or delete to delete the node
7. Crash

### Minimal reproduction project (MRP)

[repro.zip](https://github.com/godotengine/godot/files/13780816/repro.zip)

Note: this is from an example project that I'm following on Youtube (https://www.youtube.com/watch?v=nAh_Kx5Zh5Q). It does have *some* extra files (I've reduced it as much as I could), but it should help with reproduction.

As far as I can tell this bug should occur in a brand new project just as well though.

**Comment by AlexOtsuka** [comment] 2023-12-29 19:17
I managed to reproduce the bug and find the cause, https://github.com/godotengine/godot/pull/86615 should fix this.

**Comment by AlexOtsuka** [comment] 2024-04-03 16:42
This has been fixed by https://github.com/godotengine/godot/commit/0ba746380347cc43336ecd077788db24fe95146b.
Feel free to close the issue!

**Comment by AThousandShips** [comment] 2024-04-03 16:44
Thank you for your report, was reported before and fixed there:
* https://github.com/godotengine/godot/issues/83490

**Closed by AThousandShips** 2024-04-03 16:44 UTC
Labels: bug, topic:editor, crash, topic:2d
