### ISSUE TITLE
Redundant error message when using (external) script editor.

### ISSUE THREAD

**Issue by syskrank** [godotengine/godot#26435] opened 2019-03-01 10:08 UTC
**Godot version:**
All 3.1+ versions are affected for the moment.

**OS/device including version:**
Windows 10 x64, Linux Mint 19 x64

**Issue description:**
Each time the script is saved in external editor, the message arriving in the Output pane:
```
core\resource.cpp:79 - Condition ' exists ' is true
```
Which is very misleading and annoying, because it carries no practical information for the engine user yet it is always here, signaling that there are some 'errors' in the project.

Maybe it happens on script re-import step of something, but at the same time nothing is wrong with the project nor with the engine itself. 

Why this message is even there?

**Steps to reproduce:**
Create some script, using for example, VSCode. Make some changes to it, save and Alt-Tab back to the Godot Engine to see the aforementioned message in the 'Output' pane.

**Comment by neikeq** [comment] 2019-03-01 14:30
That's not a redundant message. It failed to load the script. I think there is already an issue about this and external editors.

**Comment by syskrank** [comment] 2019-03-01 14:47
Then I just failed to find the existing issue :) 
Anyways, the text of this particular message is quite confusing and obscure, even if the real issue is behind it. Which appears not to be the case from the first glance - everything is working OK.

**Comment by neikeq** [comment] 2019-03-01 15:40
It looks like a duplicate of #10946

Other possibly related issues: #17044 #21494 #22144

**Comment by Serenitor** [comment] 2019-12-07 02:18
> everything is working OK.
It's really not. The reload of the script file fails when a change has been made in an external editor.
so Life Coding is not usable with external editors.
to me this is a major issue.

regardless, this is a duplicate.

**Comment by Calinou** [comment] 2019-12-07 12:46
Duplicate of #10946.

**Closed by Calinou** 2019-12-07 12:46 UTC
Labels: bug, topic:core
