### ISSUE TITLE
Regression with missing `Skeleton.bones_in_world_transform`

### ISSUE THREAD

**Issue by mysticfall** [godotengine/godot#34347] opened 2019-12-14 05:12 UTC
**Godot version:**
`master` / 3740ec25f7dd

**OS/device including version:**
Manjaro Linux/KDE 18.1.4

**Issue description:**
`Skeleton` class used to provide `bones_in_world_transform` property which was required to make a model imported with Godot(.escn) Exporter to work properly (see #26997).

But upon updating Godot to the latest revision, I found that the property no longer exists so I'm having the same problem as described in #26997.

**Comment by mysticfall** [comment] 2019-12-14 05:22
By the way, the commit which removed the property in question seems to be d81ddaf33ecddab.

**Comment by akien-mga** [comment] 2019-12-14 10:21
Related to #32766 (caused by same commit, likely due to the removal of this feature).

**Comment by reduz** [comment] 2019-12-14 11:53
This requires modifying the .escn exporter, unfortunately. The change in how skeletons were processed was required to significantly improve compatibility with all sorts of models.

**Comment by mysticfall** [comment] 2019-12-15 00:48
Thanks for the info. I opened a separate issue in godotengine/godot-blender-exporter to request necessary changes to the .escn exporter.

**Comment by akien-mga** [comment] 2020-01-22 12:45
Closed as moved to godotengine/godot-blender-exporter#302.

**Closed by akien-mga** 2020-01-22 12:45 UTC
Labels: discussion, regression, topic:core, topic:import
