### ISSUE TITLE
Godot 3.2 C#: failed to build project solution

### ISSUE THREAD

**Issue by zwz** [godotengine/godot#36531] opened 2020-02-25 14:17 UTC
**Godot version:**
Godot 3.2
**OS/device including version:**
macOS Mojave 10.14.5
**Issue description:**
When I click to build/run, a build error modal pops up, saying: failed to build project solution.
**Steps to reproduce:**
I cannot remember the steps, but here is what I did in general:
1. add some builtin meshes
2. playing around spatial and shader materials (during the process, it builds successfully)
3. add a C# script for some object (the script file name is in Chinese, no editing at all)
4. the issue comes
5. delete the script, the issue remains
**Minimal reproduction project:**
[Godot.zip](https://github.com/godotengine/godot/files/4250381/Godot.zip)

**Comment by andy-noisyduck** [comment] 2020-02-25 22:50
I'm not entirely sure how you got your project into the state, but the `csproj` references `wall.cs` which isn't included in your source. This is probably why it isn't compiling for you.

**Comment by zwz** [comment] 2020-02-26 01:55
As I said, 
I created a script (the script file name is in Chinese, no editing at all; and then I rename it in wall.cs)
And then I deleted the script.

All those operations(rename and delete) are done in Godot.

**Comment by andy-noisyduck** [comment] 2020-02-26 02:04
If you did a file rename then it's likely a duplicate of #12917.

I'm afraid Godot is still a little buggy when keeping `csproj` files in sync. I end up editing them manually when I've done a file rename.

**Comment by zwz** [comment] 2020-02-26 03:25
I see.
But now I removed those references of cs script from `csproj` file (by an external editor), it still did not build.

**Comment by aaronfranke** [comment] 2020-02-26 05:06
Does any C# project work on your system, such as the demo projects? Do you have Mono installed?

**Comment by zwz** [comment] 2020-02-26 06:41
@aaronfranke  I just installed godot_mono.

**Comment by akien-mga** [comment] 2020-02-26 07:31
What is the actual build error? It should be shown in the debugger when you over the "callback failed" message.

If it refers to missing .NET Framework 4.7, be sure to install that.

**Comment by aaronfranke** [comment] 2020-02-26 08:14
> If it refers to missing .NET Framework 4.7, be sure to install that.

Well, they're on Mac, so I doubt they could install a Windows-only library.

**Comment by akien-mga** [comment] 2020-02-26 09:01
¯\_(ツ)_/¯
.NET ecosystem naming is a mess.

**Comment by zwz** [comment] 2020-02-28 14:15
@akien-mga No, there is no useful message.
Installing mono solves the issue. 
I thought godot_mono contains mono by itself.
So maybe there should be a note for godot_mono on the downloading page.

**Comment by aaronfranke** [comment] 2020-02-28 20:00
@zwz There is a note:

![Screenshot from 2020-02-28 14-54-24](https://user-images.githubusercontent.com/1646875/75583133-0a43b080-5a3b-11ea-8a13-014e4859b938.png)


However, you are not the only person who has had this issue. I help several people each week on Discord set up Godot with Mono, and the issue is usually because they don't have Mono installed, or they are using and outdated version of Mono. @akien-mga Please check your Discord DMs, this needs to be made more obvious somehow, far too many people are missing the requirements.

**Comment by zwz** [comment] 2020-03-03 03:50
Maybe still an issue.
After I removed all the c# scripts (and references from `csproj` file by an external editor), it should build. Shouldn't it?

**Comment by aaronfranke** [comment] 2020-03-03 05:22
@zwz The minimal reproduction project you posted *does* contain entries in the `csproj` file.

Also, I highly recommend that you use ASCII characters for file names. Your project didn't unzip properly on my system since it changed `地面.tscn` into `å°é¢.tscn`. If you are making a game in another language, consider leaving all of the files and code in ASCII characters and then just having the in-game text in that language.

**Comment by zwz** [comment] 2020-03-05 02:55
Thank you for your file naming suggestion.

What I mean is that after I remove all the references from `csproj` file, it should build even if **mono sdk is not installed**, right?

**Comment by aaronfranke** [comment] 2020-03-05 03:52
If you are using the Mono version of Godot, and the project has a C# solution generated, then you need to have Mono/etc installed in order for it to run. This is expected behavior.

If you don't wish to use C# in your project, you can either delete all of the C# files, or open the project with a non-Mono version of Godot, which will ignore the C# solution file. Really, if you don't wish to have Mono/etc installed, you should just use the non-Mono version since it doesn't require Mono.

I will close this since it's not a Godot bug. It is possible that some things can be made clearer, like on the website, but the Godot developers are already aware of this kind of thing and there's not really any specific actionable proposals listed here.

**Closed by aaronfranke** 2020-03-05 03:52 UTC
Labels: topic:mono
