### ISSUE TITLE
C#: Array.Contains() doesn't work properly with enums

### ISSUE THREAD

**Issue by InkONat** [godotengine/godot#98595] opened 2024-10-27 23:17 UTC
### Tested versions

4.4.dev3

### System information

Windows 11 - Godot 4.4.dev3

### Issue description

I have an enum called `ItemType`, belonging to a custom resource called `ItemManager`:

![image](https://github.com/user-attachments/assets/a1da48c0-b4af-4b3a-b659-aa2a69620f56)

When I try to check if an `Array<ItemType>` contains STATS from this enum, unexpected behavior happens:

![image](https://github.com/user-attachments/assets/136c2d1b-cc6d-4145-96fa-23edaf816d30)

![image](https://github.com/user-attachments/assets/b28a8f31-463b-4340-85e4-b4484fbb5a72)
![image](https://github.com/user-attachments/assets/2aec2951-c252-4b48-8355-8a700025d778)

### Steps to reproduce

- Make a new C# project
- Make a new custom resource on C# with a public enum
- Make a typed Array with that enum, containing one of it's elements
- Check if that element is inside the array

### Minimal reproduction project (MRP)

N/A

**Comment by a-johnston** [comment] 2024-10-28 02:05
I couldn't reproduce this on 61accf060515416da0, potentially it's been fixed between dev3 and that commit.

For that commit, [cs_array_contains.zip](https://github.com/user-attachments/files/17536435/cs_array_contains.zip) has the output:
```
Enum Array: [0, 1, 2]
  Contains MyEnum.A (0): True
  Contains MyEnum.B (1): True
  Contains MyEnum.C (2): True
Int Array: [0, 1, 2]
  Contains MyEnum.A (0): True
  Contains MyEnum.B (1): True
  Contains MyEnum.C (2): True
```

**Comment by InkONat** [comment] 2024-10-28 02:07
> I couldn't reproduce this on 61accf060515416da0, potentially it's been fixed between dev3 and that commit.
> 
> For that commit, [cs_array_contains.zip](https://github.com/user-attachments/files/17536435/cs_array_contains.zip) has the output:
> ```
> Enum Array: [0, 1, 2]
>   Contains MyEnum.A (0): True
>   Contains MyEnum.B (1): True
>   Contains MyEnum.C (2): True
> Int Array: [0, 1, 2]
>   Contains MyEnum.A (0): True
>   Contains MyEnum.B (1): True
>   Contains MyEnum.C (2): True
> ```
> 

Were you able to reproduce it on normap 4.4 dev3 though?

**Comment by a-johnston** [comment] 2024-10-28 02:17
I could not reproduce it on 4.4 dev3 either; the output is the same as the current head. If you're certain this is an engine bug and not a project bug, can you compare your code to the zipped project I linked and make an MRP?

**Comment by raulsntos** [comment] 2024-10-28 03:23
Sounds like a duplicate of https://github.com/godotengine/godot/issues/98309. Make sure the array property is typed when serialized to the scene, it should look like: `Array[int]([0, 1, 2])`

**Comment by a-johnston** [comment] 2024-10-28 04:03
Ah interesting, thanks for linking that. Yeah that seems to trigger specifically for int arrays and the value `0` as when I change the exports (and the int array print, whoops!) in the project above to
```c#
[Export] Array<MyEnum> enumArray = new();
[Export] Array<int> intArray = new()
```
the output changes to
```
Enum Array: [0, 1, 2]
  Contains MyEnum.A (0): True
  Contains MyEnum.B (1): True
  Contains MyEnum.C (2): True
Int Array: [<null>, 1, 2]
  Contains MyEnum.A (0): False
  Contains MyEnum.B (1): True
  Contains MyEnum.C (2): True

```

**Comment by InkONat** [comment] 2024-10-28 21:55
> Sounds like a duplicate of #98309. Make sure the array property is typed when serialized to the scene, it should look like: `Array[int]([0, 1, 2])`

Doing `new Array<int>{0}` did not work
([0]) doesn't work

**Comment by InkONat** [comment] 2024-10-28 22:01
![image](https://github.com/user-attachments/assets/043938d2-bcd0-440f-b9c9-4b3ad1f5a23d)
![image](https://github.com/user-attachments/assets/2bd1a843-da04-46b0-8d38-5d4eaa1739f1)
![image](https://github.com/user-attachments/assets/ff4f7da1-2cf7-456c-b251-724a4a55ed09)
Even if I don't use 0 and use another index like 1, it doesn't work

**Comment by a-johnston** [comment] 2024-10-28 22:46
> > Sounds like a duplicate of #98309. Make sure the array property is typed when serialized to the scene, it should look like: `Array[int]([0, 1, 2])`
> 
> Doing `new Array<int>{0};` did not work ([0]) doesn't work

they're referring to how the array is serialized by the resource/scene. For example, in the example project I linked above, `main.tscn` has these two lines in it (in the case of having a non-null default value):
```
enumArray = Array[int]([0, 1, 2])
intArray = [null, 1, 2]
```

**Comment by InkONat** [comment] 2024-10-28 23:20
> > > Sounds like a duplicate of #98309. Make sure the array property is typed when serialized to the scene, it should look like: `Array[int]([0, 1, 2])`
> > 
> > 
> > Doing `new Array<int>{0};` did not work ([0]) doesn't work
> 
> they're referring to how the array is serialized by the resource/scene. For example, in the example project I linked above, `main.tscn` has these two lines in it (in the case of having a non-null default value):
> 
> ```
> enumArray = Array[int]([0, 1, 2])
> intArray = [null, 1, 2]
> ```

https://github.com/godotengine/godot/issues/98595#issuecomment-2442814590
The array is already set to another value in this function, which is called in an Initialize() function of the ItemManager
In the same node script where the behavior happens:
![image](https://github.com/user-attachments/assets/fde93f9f-08fa-4e44-be65-07680fcb6765)

**Comment by InkONat** [comment] 2024-10-29 21:57
A workaround I found was just using `int[]` instead of `Array<int>`, since Godot thinks of `int[]` as a PackedInt32Array. But the issue persists with normal Arrays.

**Comment by InkONat** [comment] 2024-11-03 15:36
Can someone add the confirmed label?

**Closed** 2024-12-09 20:36 UTC
Labels: bug, confirmed, topic:dotnet
