### ISSUE TITLE
Fonts are malformed

### ISSUE THREAD

**Issue by zaksnet** [godotengine/godot#46850] opened 2021-03-10 03:32 UTC
**Godot version:**
Godot Engine v3.2.4.rc4.mono.official

**OS/device including version:**
Windows 10

**Issue description:**
Fonts are being cut on top in v3.2.4.rc4. This looks like a regression since the fonts look good in RC3. I recall we had a similar issue a while ago, maybe its related?
EDIT: #36567 It was this one but as far as i can tell the editor fonts seems to be working smoothly this time.

Godot Engine v3.2.4.rc4.mono.official **(Malformed!)**:
![RC4](https://user-images.githubusercontent.com/1850856/110572170-33704400-8159-11eb-8a11-da9bbf66aa1f.png)

Godot Engine v3.2.4.rc3.mono.official **(Normal)**:
![RC3](https://user-images.githubusercontent.com/1850856/110572187-3f5c0600-8159-11eb-8df4-74bc1e0191f9.png)

EDIT: It dosn't seem to be related to the fonts. I think controls are being cut also. If you look at closely at the gif, styleboxes seem to be getting malformed when the container size changes:
![FontMalformedDemo](https://user-images.githubusercontent.com/1850856/110573365-6ca9b380-815b-11eb-99d6-4f03f11e0db1.gif)

Demo project:
[Artifacts Demo.zip](https://github.com/godotengine/godot/files/6117086/Artifacts.Demo.zip)

**Comment by akien-mga** [comment] 2021-03-10 08:37
Likely a regression from #46409 or #46495, CC @asheraryam.

**Comment by akien-mga** [comment] 2021-03-10 08:40
See also this Twitter thread which points a related regression from #46409: https://twitter.com/Korluna_/status/1369348776368996355

**Comment by asheraryam** [comment] 2021-03-10 09:45
Thanks looking into it 👍

**Comment by asheraryam** [comment] 2021-03-10 10:42
Yeah my bad it should be using `round()` not `floor()`, will push a fix later today after I do more testing on the big project

**Comment by asheraryam** [comment] 2021-03-10 11:15
Managed to reproduce the issue using a bunch of scroll containers, confirming the issue is from #46409 
![image](https://user-images.githubusercontent.com/43449832/110621289-14020700-81ab-11eb-8bc5-887ab7196fe3.png)
![image](https://user-images.githubusercontent.com/43449832/110621308-19f7e800-81ab-11eb-8426-8e04fa2510c6.png)

**Comment by calumk** [comment] 2021-03-10 11:35
Also experiencing this issue, 
Doesn't seem to be affecting the editor itself, but certainly when running my game I see issues, even with built-in components such as file window

Thought I needed glasses!

**RC3**
![3 2 4_RC3](https://user-images.githubusercontent.com/1183991/110623133-579d4680-8194-11eb-8a98-bb4ee67de426.PNG)

**RC4**
![3 2 4_RC4](https://user-images.githubusercontent.com/1183991/110623131-5704b000-8194-11eb-92f4-4315cff704a3.PNG)

**Comment by asheraryam** [comment] 2021-03-10 13:32
@calumk @zaksnet I made a fix and it seems to work, can you test it please?

Windows EXE: https://github.com/asheraryam/godot/suites/2224402335/artifacts/46074362
Pull Request: 
https://github.com/asheraryam/godot/pull/1748

**Comment by zaksnet** [comment] 2021-03-10 15:35
> @calumk @zaksnet I made a fix and it seems to work, can you test it please?
> 
> Windows EXE: https://github.com/asheraryam/godot/suites/2224402335/artifacts/46074362
> Artifact location: [asheraryam#1748](https://github.com/asheraryam/godot/pull/1748)
> 
> If it's confirmed we can merge the new PR #46869

Nope sorry, it looks the same to me:
![image](https://user-images.githubusercontent.com/1850856/110654655-a19b2200-81be-11eb-8848-f425cb2d6269.png)

**Comment by zaksnet** [comment] 2021-03-10 15:40
![image](https://user-images.githubusercontent.com/1850856/110655362-474e9100-81bf-11eb-92b2-3713926414ca.png)
Left is RC3 and right is the .exe you sent

**Comment by zaksnet** [comment] 2021-03-10 15:45
> @calumk @zaksnet I made a fix and it seems to work, can you test it please?
> 
> Windows EXE: https://github.com/asheraryam/godot/suites/2224402335/artifacts/46074362
> Artifact location: [asheraryam#1748](https://github.com/asheraryam/godot/pull/1748)
> 
> If it's confirmed we can merge the new PR #46869

I've attached a demo project for you in original post 👍

**Comment by calumk** [comment] 2021-03-10 15:48
as @zaksnet said, not working for me either

**Comment by asheraryam** [comment] 2021-03-11 05:42
Turns out https://github.com/godotengine/godot/pull/46869 solves a different issue.

I'll use git-bisect in the weekend to find the exact 3.2 commit that caused this. Thank you @zaksnet for the reproduction project, this is very helpful.

**Comment by asheraryam** [comment] 2021-03-11 07:42
@georgwacker I can confirm that this is a regression from https://github.com/godotengine/godot/pull/46409

I tried the binaries from just before the PR and the issue was not there -- https://github.com/godotengine/godot/actions/runs/614244115 -- but it exists on the PR binaries using the reproduction project.

**Comment by akien-mga** [comment] 2021-03-11 10:59
Fixed by #46891.

Second revert of that attempted fix, but don't despair, it will come back and we'll get it right :muscle:

**Closed by akien-mga** 2021-03-11 10:59 UTC
Labels: bug, confirmed, regression, topic:gui
