### ISSUE TITLE
No C# scripts but project try to build C# Solution. It get stucked building also.

### ISSUE THREAD

**Issue by jcarlosrc** [godotengine/godot#39714] opened 2020-06-20 17:35 UTC
**Godot version:**

Godot 3.2.2 RC 2 Mono for Linux

**OS/device including version:**

Ubuntu 16.04 LTS.

**Issue description:**

After pressing "Build", the project is treated as a C# project even if only gd scripts exist. On top of that, it seems that it won't build. Gets stuck in 0% even for a really simple project.

**Steps to reproduce:**
Run the minimal project. It tries to build like a C# project even if only a Camera.gd script exists in it. In my case, it can't even build it.

**Minimal reproduction project:**
Here it is.

[BugReport.zip](https://github.com/godotengine/godot/files/4808252/BugReport.zip)

**Comment by raulsntos** [comment] 2023-07-12 11:15
Your project contains `.sln` and `.csproj` files which means it's a C# project so Godot will try to build it. You likely added C# scripts to your project at one point which created this files, deleting every C# script doesn't get rid of these files so they need to be deleted manually.
- This part of the issue can be tracked in https://github.com/godotengine/godot/issues/56758.

As for why it gets stuck in 0%, I'm unable to reproduce in Godot 3.5.1 using `dotnet CLI` as build tool.

You are using a very old version of Godot. Are you still able to reproduce this issue in Godot 3.5.2 or any later release? Make sure to use the `dotnet CLI` build tool:
- Select `dotnet CLI` in **Editor > Editor Settings > Mono > Builds**.

**Comment by raulsntos** [comment] 2024-07-28 01:31
Closing as per the above comment. If you are still able to reproduce in a currently supported version of Godot, please comment here and it can be reopened.

**Closed by raulsntos** 2024-07-28 01:31 UTC
Labels: topic:editor, topic:dotnet
