### ISSUE TITLE
The cursor does not go back to the Arrow shape when going outside a resizable dialog window

### ISSUE THREAD

**Issue by groud** [godotengine/godot#9440] opened 2017-06-29 07:42 UTC
**Operating system or device - Godot version:**
Godot 3, Master branch

**Issue description:**
The cursor keeps is resizer shape instead of getting back the arrow one.

**Steps to reproduce:**
Open the editor parameters and cross slowly of one of its borders.
![toto](https://user-images.githubusercontent.com/6093119/27676657-1e9d8f1a-5caf-11e7-89a9-1d152f966de5.gif)

**Comment by akien-mga** [comment] 2017-06-29 07:49
Duplicate of #7622.

**Closed by akien-mga** 2017-06-29 07:49 UTC
