### ISSUE TITLE
Cannot get visual studio code to debug mono

### ISSUE THREAD

**Issue by bkeys** [godotengine/godot#13837] opened 2017-12-02 19:20 UTC
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Fedora 26, master branch

**Issue description:**

I cannot find any documentation on how to integrate Godot's mono capabilities with visual studio code, is there a launch.json I can use for reference somewhere? @neikeq

**Comment by matrem** [comment] 2017-12-02 22:43
Is there already a plugin to debug godot's mono integration?

**Comment by bkeys** [comment] 2017-12-02 23:11
I want to say @Calinou mentioned that @neikeq might have done a debugging session with the default mono plugin for vscode

**Comment by akien-mga** [comment] 2018-01-05 14:09
We have now entered release freeze for Godot 3.0 and want to focus only on release critical issues for that milestone. Therefore, we're moving this issue to the 3.1 milestone, though a fix may be made available for a 3.0.x maintenance release after it has been tested in the master branch during 3.1 development. If you consider that this issue is critical enough to warrant blocking the 3.0 release until fixed, please comment so that we can assess it more in-depth.

**Comment by justStand** [comment] 2018-01-09 16:32
With all of the attention that threads about C# support in Godot garner on Reddit, I'm a bit surprised that mono isn't being treated as a priority.

**Comment by neikeq** [comment] 2018-01-09 17:36
I didn't make any editor extension yet because I'm still thinking how to make them communicate with Godot to be the most user friendly possible.

This is the `launch.json` I use with the default mono extension for VS Code:

``` json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Attach",
            "type": "mono",
            "request": "attach",
            "address": "localhost",
            "port": 23685
        }
    ]
}
```

That's the default port, but you can change it in project settings: `mono/debugger_agent/port`.

**Comment by olsonjeffery** [comment] 2018-01-21 16:36
Hi, I'm using Godot 3.0 RC1 on macOS Sierra. I've got VS Code installed and set up with my launch.json config using what's shown in @neikeq 's comment above. I actually use VS Code for my main development experience and it works fine (w/ intellisense for Godot code or other dependencies I've added to the project via Paket/nuget).

I have the default debugger settings as shown in the project settings (port 23685). While the godot editor process is active, I notice that 23685 is open and I can connect from VS Code or telnet, but there's never any response to anything sent to that port.

When I build/run the project and then try to connect, its the same thing; I can connect in VS code, but no breakpoints are hit and it's unresponsive.

Also I've observed that, if I set the "wait for debugger" option in the project settings, any attempt to run/debug the project will stop immediately after debugging begins.

I understand that any dev work to address this will have to wait until after the 3.0 release, but I wanted to chime in with my experience.

**Comment by maikramer** [comment] 2018-01-30 18:14
Is working perfectly to me, my steps, dont know what is mandatory:
Installed the mono debugger extension in vs code
Checked Install remote debug in godot
In project settings inside godot, i checked Wait for debugger
Set a bigger timeout, like 60000, to dont need to run
Pressed play in godot (the game start to wait for the debugger)
Back to vs code and pressed play debug, perfect
Using with ubuntu 18.04

**Comment by olsonjeffery** [comment] 2018-02-01 14:01
Just attempted this again, on macOS Sierra, with the 3.0 stable release (64bit mono version). Have Mono 5.4.1 installed via brew.

Still the same behavior as I described above [here](https://github.com/godotengine/godot/issues/13837#issuecomment-359261323)

Can anyone confirm/deny remote debugging support w/ Godot+VS Code w/ Mono debugging extension on macOS?

**Comment by PJB3005** [comment] 2018-02-16 13:28
I have definitely debugged C# code successfully with the [Mono Debug](https://marketplace.visualstudio.com/items?itemName=ms-vscode.mono-debug) extension.

Wait for debugger is definitely broken however and there is an issue where the editor occupies the debug port. The latter is actually a problem because you end up debugging the editor which isn't running C# code to debug.

As for the editor port occupation issue: should we make a second config option for an editor port (so you can still debug the editor if editor scripts ever get implemented) or just make the editor not enable the mono debugger.

**Comment by PJB3005** [comment] 2018-02-16 13:31
Actually nevermind on the wait for debugger thing. It works absolutely fine. Probably was fixed since I last tested it.

**Comment by neikeq** [comment] 2018-02-16 14:00
I thought I already made the editor not enable the mono debugger: https://github.com/godotengine/godot/blob/49dc473ff184683485c0e69f4f1d49c63f6be6a7/modules/mono/mono_gd/gd_mono.cpp#L122-L126

I think at some point the editor should be debuggable, but right now there are a few issues with that.

**Comment by PJB3005** [comment] 2018-02-16 14:28
Digging into this: the issue is with the project manager eating port 23685. The `_is_project_manager_requested()` doesn't work if the project manager was opened as a fallback.

**Comment by gattila** [comment] 2018-02-26 06:19
I tested it with windows 10, mono 5.4.0, VS Code and mono debugger extension. I created a launch.json, started the game in godot and attached with the debugger. In VS Code I saw two threads: the thread#1 and the finalizer. I was able to pause the app from VS Code, in this case the Thread#1 was paused, and the game too, and I was able to continue it again, but unfortunately, the breakpoints wasn't hit.

**Comment by gattila** [comment] 2018-02-26 06:19
Ps. I used the latest godot version (3.0.1).

**Comment by neikeq** [comment] 2018-02-26 11:23
@gattila in which method did you put the breakpoint? Is that method async by any chance?

**Comment by gattila** [comment] 2018-02-28 18:58
I simply clicked before the first line of the _Ready() function, and the big red button appeared, and I saw a new breakpoint in VS code in the breakpoints window. The code was executed, but the program was not stopped at the breakpoint. I debugged other .NET programs with VS Code before without any problem.

Maybe the mono 5.4.0 is too old ? I tired to remove the 5.4 mono and install the latest (5.10.0.140), but after the install (and the restart of the computer) the godot crashed if I tired to open a C# based godot application.

**Comment by gattila** [comment] 2018-02-28 19:14
I tried with 5.4.17. The godot not crashing with this version, but it still don't stop on breakpoint.

**Comment by PJB3005** [comment] 2018-02-28 19:18
The Godot builds provided on the website are built against 5.4 and don't
work with any others due to other issues.

The debugger does attach though, right? It just doesn't hit any
breakpoints?

Does the Godot process lock up when you hit pause on the debugger when it's
attached?

**Comment by neikeq** [comment] 2018-02-28 19:45
@gattilla Maybe that code is executed before the debugger is attached? What happens if you enable de option in `Project Settings > Mono > Debugger Agent > Wait For Debugger`? What if you put a breakpoint in a `_Process` method?

**Comment by gattila** [comment] 2018-03-01 07:43
If I set the Wait for Debugger, the running app shows the godot splash screen and wait until I attach with the debugger. But it does not stop on my breakpoints, both on _Ready, _Input, _Process. These functions are executed: if I put a GD.print to these functions, I can see the result in the output window. I see the breakpoint lines in VS code, and the  Thread#1 and Finalizer processes in the Call Stack window. I can play the pause button in VS code and in this case the godot application freezes, and the Thread#1 show Stopped status. If I press the Continue button in VS code the Thread#1 status changes to Running and the game also run as before the pause. All seems Ok, except the fact that the app doesn't stop on breakpoints.

**Comment by PJB3005** [comment] 2018-03-01 20:16
Oh I should've asked this earlier. Are you on Windows? Pretty sure #14822 would break the debugger too since it wouldn't be able to associate line numbers with instructions.

**Comment by Duehok** [comment] 2018-03-20 08:38
i confirmed the same behavior as gattila: on win 8.1 (it seems that I am the last person on earth who still use it), Godot 3.0.2 stable, VSCode + mono debugging integration: the debuggers connect, the threads can be stopped, the breakpoits are not hit.

**Comment by exts** [comment] 2018-03-22 04:09
same issue with jetbrains rider on windows. I get  DWP Connection Failed.

**Comment by neikeq** [comment] 2018-05-25 15:29
Marking this as Windows-only. Let me know if you can also reproduce this in other platforms. Debugging support will be added after 3.1, when we add extensions for some external editors and IDEs.

**Comment by PJB3005** [comment] 2018-05-26 21:06
I'm looking into this.

So far I can confirm that embedded Mono debugging totally works on Windows in a tiny test project:

```cpp
#include "stdafx.h"
#include <iostream>
#include <mono/jit/jit.h>
#include <mono/metadata/assembly.h>
#include <mono/metadata/mono-config.h>
#include <mono/metadata/debug-helpers.h>
#include <mono/metadata/mono-debug.h>

int main()
{
	mono_set_dirs("C:\\Program Files\\Mono\\lib",
		"C:\\Program Files\\Mono\\etc");

	mono_config_parse(NULL);

	mono_debug_init(MONO_DEBUG_FORMAT_MONO);

	const char* options[] = {
		"--soft-breakpoints",
		"--debugger-agent=transport=dt_socket,address=127.0.0.1:3005,embedding=1,server=y,suspend=y,timeout=30000"
	};

	mono_jit_parse_options(2, (char **)options);

	auto domain = mono_jit_init_version("thing.derp", "v4.0.30319");
	auto assembly = mono_domain_assembly_open(domain, "C:\\Users\\absolutelynotmyusername\\Documents\\Visual Studio 2017\\Projects\\mono embed debugging pls\\helloworld\\bin\\Debug\\helloworld.dll");
	auto image = mono_assembly_get_image(assembly);
	auto theclass = mono_class_from_name(image, "helloworld", "Class1");

	auto desc = mono_method_desc_new("Class1:Hello", false);
	auto method = mono_method_desc_search_in_class(desc, theclass);

	mono_runtime_invoke(method, nullptr, nullptr, nullptr);

	return 0;
}
```

and pasting said code into `GDMono::initialize()` does exactly the same thing, so debugging is *something* we're doing wrong with the Mono API I assume.

Not sure how helpful this info is but it's a start.

**Comment by neikeq** [comment] 2018-05-27 14:08
I've been looking into this as well. So far, the debugger seems to be attached correctly. If there are no breakpoints, the applications run normally. If I set a breakpoint, the applications hangs indefinitely.
And no, it doesn't hang because it stopped at the breakpoint. I checked and the method is never called.

I will try removing unnecessary stuff from initialization until it's fixed, to find out what is causing it (if the problem is in the initialization that is).

**Comment by neikeq** [comment] 2018-05-27 15:07
Aha! Found it. Preparing a PR.

**Closed** 2018-05-27 15:19 UTC
Labels: documentation, platform:windows, topic:mono

**Comment by exts** [comment] 2018-05-27 17:04
@neikeq so you half fixed it. I can get vs code on windows 10 to attach to the debugger now without issue. 

- `Project Settings -> Mono -> Debugger Agent -> Wait for Debugger`
- `Run the scene in godot`
- Using the config above (and following these [docs](https://code.visualstudio.com/docs/python/debugging)) -> `Debug Tab -> Select Attach from Dropdown -> Hit Play`

Now the issue is the debugger isn't breaking any points for me. If I let godot project runs without debugging it'll timeout like normal and it'll run when the debugger connects without issue. So close yet so far :(

- Windows 10
- Mono version 5.10.1
- Visual Studio Code (Latest)

Weirdly enough jetbrains rider won't even attach to the debugger.

**Comment by neikeq** [comment] 2018-05-27 20:40
That's weird. It did hit the breakpoint for me...

**Comment by exts** [comment] 2018-05-27 21:06
@neikeq do you have a sample project that I can test to see if I can reproduce it working for you? Going to rebuild shortly to make sure (after i finish setting up ubuntu 18 & godot on my other desktop pc)

**Comment by PJB3005** [comment] 2018-05-27 22:26
Definitely works on my end too. You changed the debug type of your project as instructed [here](https://github.com/godotengine/godot/issues/14822#issuecomment-392094656) right?

**Comment by exts** [comment] 2018-05-27 23:27
@neikeq I just tested with mono 5.12.0 and it works perfectly. 5.10.1 doesn't work at all. 

Maybe we should require 5.12.0 the required version? On their release notes they said this version passes a lot of their tests and improved a bunch of stuff so it only makes sense.

**Comment by neikeq** [comment] 2018-05-28 17:55
I have `Mono version 5.10.0.160` installed.

**Comment by exts** [comment] 2018-05-28 20:28
these mono versions are so weird lol. So 5.10.0 & 5.12.0 works? 5.10.1 doesn't for me.

**Comment by neikeq** [comment] 2018-05-28 21:18
@exts Could you share a minimal example project where you cannot get it to work?

**Comment by exts** [comment] 2018-05-28 21:37
[DebuggaTest.zip](https://github.com/godotengine/godot/files/2046209/DebuggaTest.zip)

Just to clarify: **5.12.0** works fine, 5.10.**1** didn't work, right now I'm building the editor using 5.10.**0** to test if it works with that version. After I finish testing I'm going to redownload 5.10.**1** and rebuild the editor again to confirm if it works or not with that version of mono.

**Comment by neikeq** [comment] 2018-05-29 08:17
You mean compiler errors, or in vscode's editor?

**Comment by exts** [comment] 2018-05-29 12:11
@neikeq correct. For instance, not instantiating a field that requires a instance would compile but throw an error to the Godot output yet the scene would still run. I'm on mobile so hope that helps.

**Comment by neikeq** [comment] 2018-05-29 12:38
Oh, I think you are getting a NullReferenceException. As far as I remember, the mono debug extension for VS Code would not break on unhandled exceptions by default, but you could change that in the settings.

**Comment by exts** [comment] 2018-05-29 14:09
@neikeq nice, just figured out how to do it.

```
    "mono-debug.exceptionOptions": {
        "System.Exception": "never",
        "System.SystemException": "never",
        "System.ArithmeticException": "never",
        "System.ArrayTypeMismatchException": "never",
        "System.DivideByZeroException": "never",
        "System.IndexOutOfRangeException": "never",
        "System.InvalidCastException": "never",
        "System.NullReferenceException": "always",
        "System.OutOfMemoryException": "never",
        "System.OverflowException": "never",
        "System.StackOverflowException": "never",
        "System.TypeInitializationException": "never"
    },
```

Adding this to your vs code user settings will catch said exceptions.
