### ISSUE TITLE
Exported C# Node arrays doesn't accept nodes. 

### ISSUE THREAD

**Issue by Melvin8D** [godotengine/godot#72217] opened 2023-01-28 01:17 UTC
### Godot version

4.0.beta16 mono (Using .Net 7.0)

### System information

Windows 10, Geforce 1050ti, i5 9400f, Vulkan renderer. 

### Issue description

When exporting arrays of nodes, the array in the sidebar will not accept them and remain with the "Assign" button. I have not tested with .net 6 or gdscript.

### Steps to reproduce

In the project, theres a Node with a c# script that has an export array of nodes. Dragging them doesn't work, neither does using the menu to assign them.

### Minimal reproduction project

[ExportNodeBug.zip](https://github.com/godotengine/godot/files/10524235/ExportNodeBug.zip)

**Comment by raulsntos** [comment] 2023-01-28 03:45
Duplicate of https://github.com/godotengine/godot/issues/62916

**Closed by raulsntos** 2023-01-28 03:45 UTC
