### ISSUE TITLE
Trying to display motion vectors in Godot 4.1.3 spits out an error every frame

### ISSUE THREAD

**Issue by usernam666** [godotengine/godot#84647] opened 2023-11-09 04:46 UTC
### Godot version

v4.1.3.stable.official [f06b6836a]

### System information

Godot v4.1.3.stable - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1650 (NVIDIA; 31.0.15.3640) - Intel(R) Core(TM) i3-6100 CPU @ 3.70GHz (4 Threads)

### Issue description

This is the error:

> Texture (binding: 0, index 0) needs the TEXTURE_USAGE_SAMPLING_BIT usage flag set in order to be used as uniform.
> ./servers/rendering/renderer_rd/uniform_set_cache_rd.h:129 - Condition "rid.is_null()" is true. Returning: rid
> drivers/vulkan/rendering_device_vulkan.cpp:7208 - Condition "!uniform_set" is true.
> Uniforms were never supplied for set (0) at the time of drawing, which are required by the pipeline

repeated over and over again.

I should also mention that I'm not using the mono version.

### Steps to reproduce

1. Click the three-dots icon in the top left of the scene view.
2. Go to "Display Advanced" and select "Motion Vectors"

### Minimal reproduction project

N/A

**Comment by YuriSizov** [comment] 2023-11-09 12:48
cc @clayjohn @DarioSamo

**Comment by clayjohn** [comment] 2023-11-09 13:04
This might be fixed in 4.2 already. Would be worth checking if there is something we can cherry pick

**Comment by usernam666** [comment] 2023-11-11 02:22
> This might be fixed in 4.2 already. Would be worth checking if there is something we can cherry pick

I just checked in Godot 4.2 beta 5. This issue isn't fixed yet.

**Comment by clayjohn** [comment] 2023-11-11 11:09
I can't reproduce the issue in 4.2 beta5. Motion vectors look fine and don't report any errors. I tested in a high-complexity 3D scene that is mostly static objects.

Can you please upload an MRP so that we can see if something project-specific is causing the issue?

**Comment by usernam666** [comment] 2023-11-12 22:44
Update: I just created a new project from 4.2 beta5 and, for some reason, the motion vectors seem to work fine. I forgot to mention that the project in which the error is happening was ported over from 4.1.3, so that might be the issue.

It seems that the problem is indeed project specific. Thanks for helping me, you can close this issue if you want.
[MRP.zip](https://github.com/godotengine/godot/files/13329370/MRP.zip)

**Comment by clayjohn** [comment] 2023-11-13 08:34
Closing as no longer reproducible buy the OP

**Closed by clayjohn** 2023-11-13 08:34 UTC
Labels: topic:rendering, topic:editor, needs testing, topic:3d

**Comment by Calinou** [comment] 2023-11-21 14:49
Reopening, as this occurs whenever MSAA is enabled.

**Comment by RandomShaper** [comment] 2023-12-16 10:28
It also happens to me when I try _Display Advanced -> Normals_. I'd say the the `copy_to_fb.glsl` shader needs a multi-sample version, where the `source_color` is declared appropiately. Alternatively, `CopyEffects::copy_to_fb_rect()`, and maybe others, should resolve to a temp buffer before running the shader.
