### ISSUE TITLE
OS.execute Unable To Get Path Contain Space Inside Quotation Mark For Arguments

### ISSUE THREAD

**Issue by CatFlickerRis** [godotengine/godot#42512] opened 2020-10-02 16:01 UTC
**Godot version:**
3.2.3.stable

**OS/device including version:**
GNU/Linux Debian 10

**Issue description:**
in linux terminal , running `mv "$HOME/file" "$HOME/file with space"` rename (or move and rename) the file "file" inside the home directory to "file with space" , using quotation mark for file path

but in godot running `print(OS.execute("mv" , ['\"$HOME/file\"' , '\"$HOME/file with space\"'] , true , output , true))` returns an exit code 1 and output 

> mv: target 'space' is not a directory

seems like it ignores my quotation mark , just like when i wrote `mv $HOME/file $HOME/file with space` in linux terminal

![image](https://user-images.githubusercontent.com/72268539/94943800-7838e480-0502-11eb-9c8e-01b31a3c7458.png)

the only thing that didn't work in the above image is the KEY_2 one , the other returns an exit code 0

**Comment by Faless** [comment] 2020-10-03 12:42
Probably related to #37291 and internal command quoting.

**Comment by CatFlickerRis** [comment] 2021-03-26 07:49
**update**

eventhough its unclear wether its because i updated to 3.3 or its never been a bug before , but it seems like when i use _single quotation mark_ , `'/path with space/as an/argument'` would excecute correctly .

here is the worked code , just let you know that i have tried with `' " quote/inside/a quote " '` and `' \" quote/with/escape sequence \" '` and none of it works .

![os execute workaround](https://user-images.githubusercontent.com/72268539/112598473-3188cf00-8e41-11eb-824f-e15a6e923138.png)

not a big deal , but personally im more of a _double quotation mark_ fan .
its just that this function behaves differently than my expectation .

i dont know its called solved or just a workaround . so its up to you developers to leave it , fix it , or mark it as solved .

**Comment by akien-mga** [comment] 2022-09-30 09:27
Duplicate of #37291 (same cause).

**Closed by akien-mga** 2022-09-30 09:27 UTC
Labels: bug, platform:linuxbsd, topic:porting
