### ISSUE TITLE
Can't rotate the one-way collision on a TileMap tile.

### ISSUE THREAD

**Issue by pizzapim** [godotengine/godot#18493] opened 2018-04-28 19:45 UTC
**Godot version:**
v3.0.2.stable.official

**OS/device including version:**
Linux Mint 18.2 64-bit

I want to have a tile in my TileMap that has a one-way collision, pointing to the right. So I used my usual setup of Sprite>StaticBody2D>CollisionShape2d, and set the rotation_degrees on the collision shape to -90. This way the arrow in the editor is pointed to the right as expected.

However, in-game the collision shape doesn't rotate at all. The one-way collision does work, but it is pointed downwards(because the collision shape hasn't rotated).

**Minimal reproduction project:**
[The Legend of Zelda: Godot's Wrath.zip](https://github.com/godotengine/godot/files/1958120/The.Legend.of.Zelda.Godot.s.Wrath.zip)
The tile in question is the rock. Enable collision debug and you can see the collision shape hasn't rotated. Tileset source is scenes/tileset_source.tscn

**Comment by eon-s** [comment] 2018-04-28 23:06
Rotating the tile also rotates the shape but the one side remains on top down.

**Comment by pizzapim** [comment] 2018-04-29 10:09
I did some more testing and it seems this has nothing to do with the tilemaps. Rotating one-way collision doesn't work on the Sprite>StaticBody2D>CollisionShape2d setup without the tilemap too.
I just read this #12863, it seems like he tried to fix this.

**Comment by akien-mga** [comment] 2018-07-17 07:18
Duplicate of #12791.

**Closed by akien-mga** 2018-07-17 07:18 UTC
Labels: bug, topic:core, topic:editor

**Comment by hsandt** [comment] 2024-01-11 21:12
It is still not possible to rotate the one-way direction for a tilemap tile collision (unlike other collision shapes, which are associated to a node). A feature proposal has been opened for this: https://github.com/godotengine/godot-proposals/issues/7483
