### ISSUE TITLE
Vulkan Clustered: ReflectionProbes have no effect on VisualInstances not in their cull mask layers

### ISSUE THREAD

**Issue by jtnicholl** [godotengine/godot#66389] opened 2022-09-25 05:07 UTC
### Godot version

v4.0.beta.custom_build [f74491fde]

### System information

Linux (Fedora 36)

### Issue description

If a VisualInstance3D is not in any of a ReflectionProbe's cull layers, the probe has no effect on it.
What is supposed to happen is that the visual instance doesn't appear in the probe's reflection, but it is still effected by the probe, both showing its reflections and ambient light settings. This is what happens in 3.x and the forward mobile renderer.
The ball on the left is inside the probe's cull layers, the ball on the right is not. It's even more noticeable with a metallic material.
![refprobe](https://user-images.githubusercontent.com/44414418/192129092-820ee9c5-a613-447d-942b-68d97308046f.png)

### Steps to reproduce

1. Add a reflection probe to a scene with some other nodes
2. Remove a layer from its cull layers
3. Remove some nodes in the scene from the same render layer

### Minimal reproduction project

[RefProbMasks.zip](https://github.com/godotengine/godot/files/9640078/RefProbMasks.zip)
Same scene from the image.

**Comment by mrjustaguy** [comment] 2022-09-25 07:29
See https://github.com/godotengine/godot/pull/50196

**Comment by jtnicholl** [comment] 2022-09-25 17:38
I didn't see that PR or its linked issue while searching. Probably because the title makes it sound like a feature proposal instead of a bug. The description even more so.
So I guess this is technically a duplicate of #50195 but I'm going to leave it open because I think this is a much better description of the bug.

**Comment by clayjohn** [comment] 2022-09-26 04:40
Closing as duplicate of https://github.com/godotengine/godot/issues/50195

Its much better for us to have one issue per bug so that everything can be tracked in one place.

**Closed by clayjohn** 2022-09-26 04:40 UTC
Labels: bug, topic:rendering, topic:3d

**Comment by jtnicholl** [comment] 2022-09-26 05:23
> Its much better for us to have one issue per bug so that everything can be tracked in one place.

I'm aware, I was suggesting to close the other issue instead. It describes a bugfix as a feature proposal and its title doesn't make sense, the latter being why I didn't see it when I searched to check if the bug was already reported.
If you're not going to do that, then at least the other issue should be edited.
