### ISSUE TITLE
Vulkan: GPUParticles create artifacts upon instantiating due to scale interpolation issues

### ISSUE THREAD

**Issue by profjle** [godotengine/godot#59072] opened 2022-03-12 18:20 UTC
### Godot version

4.0 Alpha 4

### System information

Windows 10

### Issue description

So there are some artifacts when spawning GPUParticles3D (not 2D) specifically. I've tried on Alpha 3 and the issue is not present. I also have some CPUParticles3D working along side these and they also do not seem to create this issue. 

[Video 1](https://youtu.be/RkfQXueEab8)
[Video 2](https://youtu.be/RFgyX3qGnPg)

It is only happens a few times during play, and goes away after spawning them in a few times more.

Specs:
i7-9700k
RTX 2060 (Zotac) => Running GeForce Diver Version 511.79

### Steps to reproduce

Instantiate a GPUParticle3D

### Minimal reproduction project

[TestingParticles2.zip](https://github.com/godotengine/godot/files/8238110/TestingParticles2.zip)

**Comment by Whimfoome** [comment] 2022-03-13 11:44
Maybe related to #56691

**Comment by TechnoPorg** [comment] 2022-03-15 01:45
This may also be related to, or even a duplicate of, #54771.

**Comment by lufog** [comment] 2022-03-31 23:37
I have similar problem with GPUParticles2D on Godot v4.0.alpha.custom_build [155a94fab]

https://user-images.githubusercontent.com/10379487/161166373-a5aad234-780f-43ea-bd63-c953f477a306.mp4

Test project: https://github.com/lufog/godot-asteroids

Should I open a new issue, or it's the same problem?

**Comment by Calinou** [comment] 2022-04-01 00:12
> Should I open a new issue, or it's the same problem?

This is likely the same issue – we can consolidate it here.

**Comment by jivvy** [comment] 2022-04-14 09:56
Godot v4.0.alpha.custom_build [12cb05b3]

 - Particles flash again when on an object that was `queue_free()`'d:

https://user-images.githubusercontent.com/24281896/163359442-6740afd8-c9a7-4542-b041-d570e33e90ac.mp4

 - When there are lots of particles, rendering begins flashing. Sometimes it will calm down after a while, as showed in the video, sometimes it will continue a long time.

https://user-images.githubusercontent.com/24281896/163360278-8fbd1e72-de88-4cea-aba3-3970f5a5f41b.mp4


I also noticed particles from a previous run of the game sometimes flashed.

How observed:
1. Set particle color to white, ran the game, observed the flashing described in the first point above
2. Set particle color to red, ran game, and saw white particles flashing at the beginning.

Test project: 
[GD4_GPUParticles2D_Artifacts_Jivvy.zip](https://github.com/godotengine/godot/files/8488218/GD4_GPUParticles2D_Artifacts_Jivvy.zip)

**Comment by JoanPotatoes2021** [comment] 2022-04-19 15:23
Sadly on v4.0.alpha6.official [e4f0fc50f] I am facing the same issue, I tried creating a minimal project to post it but I couldn't reproduce it isolated, however I could capture the bug on screen, tested on a GTX 1050 TI running on win10:

![ParticleFlickerFlash-1](https://user-images.githubusercontent.com/88800565/164037175-f15d5c3c-26d3-405b-9c3c-397ed65db0e4.gif)

This weird scale flicker that grows huge is abnormal and does not have any correlation to the particle parameters or the shader, I have tried a lot of tests on this project to see if I could fix it (chaning all particle parameters and testing the shader the heck out), the only thing that seemd to fix it was to set Vsync on, I don't know if it has something to do with fast frames over 60 fps and delta, on this specific project it's running about 270-360 fps without vsync, it also happens more frequently when I move my character, the camera is also not inside the kinematicbody3D and I am constantly lerping various velocities on the physics process in this project.

**Comment by JoanPotatoes2021** [comment] 2022-04-19 16:05
https://github.com/godotengine/godot/issues/56886#issuecomment-1046007378 Linking similar issue

**Comment by RexTheWho** [comment] 2022-04-21 10:31
Recently experienced this issue (2D and 3D shown already in this issues thread)
I have found a workaround that seems to have stopped the blinding flashes, setting `preprocess` to even 0.01 seems to stop the issue- tho I'm not aware of what issues might come from doing that.

Thought I would mention it in case it's a helpful lead for finding the issue or saves someones eyes in the meantime.

**Comment by Zireael07** [comment] 2022-04-21 10:35
Seeing something similar in my own project, will have to try the tip above because a super-sized spark is not a pleasant sight

**Comment by JoanPotatoes2021** [comment] 2022-04-21 12:35
> Recently experienced this issue (2D and 3D shown already in this issues thread) I have found a workaround that seems to have stopped the blinding flashes, setting `preprocess` to even 0.01 seems to stop the issue- tho I'm not aware of what issues might come from doing that.
> 
> Thought I would mention it in case it's a helpful lead for finding the issue or saves someones eyes in the meantime.

Yea this helps, but I ocassionally still get some flickers,

**Comment by X64X32** [comment] 2022-12-15 10:40
can confirm on 4.0beta8

https://user-images.githubusercontent.com/53514993/207838418-e0a94810-fdf7-45dc-8ae3-4f67d575e2ef.mp4

**Comment by clayjohn** [comment] 2022-12-20 21:20
Tracked this down. It is a regression from https://github.com/godotengine/godot/pull/58491

**Closed** 2022-12-21 23:03 UTC
Labels: bug, confirmed, regression, topic:particles
