### ISSUE TITLE
"ERROR: body_set_shape_disabled" only showing on debug terminal, generic error on editor

### ISSUE THREAD

**Issue by aaforcebox** [godotengine/godot#26452] opened 2019-03-01 18:54 UTC
**Godot version: v3.1.beta9.official**

**OS/device including version: Win10 64bits 1060 gtx**

**Issue description:**
When an Area2D enters a StaticBody2D and triggers the '_on_body_entered' signal, the StaticBody2D throws an error if we try to disable it's CollisionShape2D. 
The "disabled" checkbox in the Inspector (Remote) is checked (at runtime), but the collision still happens.
We can remove the CollisionShape2D node with remove_child($CollisionShape2D) though.

**Steps to reproduce:**
Make an Area2D and a StaticBody2D, assign the signal on the Area2D, make them collide, disable the CollisionShape2D of the StaticBody2D.

**Minimal reproduction project:**
[3.1_beta9_bug_disable_collision.zip](https://github.com/godotengine/godot/files/2920685/3.1_beta9_bug_disable_collision.zip)

![error](https://user-images.githubusercontent.com/35024229/53659498-7a5a0380-3c3a-11e9-8a9d-d0a7f66fde06.PNG)

**Comment by capnm** [comment] 2019-03-02 13:02
Have you tried the solution proposed in the error message `$CollisionShape2D.set_deferred("disabled", true)`?

**Comment by aaforcebox** [comment] 2019-03-02 18:12
> Have you tried the solution proposed in the error message `$CollisionShape2D.set_deferred("disabled", true)`?

Tried now, it works. Why is it different? Also, where is this proposed solution?
I think this is still a bug, right?

**Comment by capnm** [comment] 2019-03-02 19:10
> I think this is still a bug, right?

No you can't change the state in a signal handler. I am not sure if that's documented somewhere in https://docs.godotengine.org/en/latest/index.html ?

> Also, where is this proposed solution?

Oh, I tested your project and the useful part of the error message is only printed on the (linux) terminal window :-/ 
ERROR: body_set_shape_disabled:  Can't change this state while flushing queries. 
**Use call_deferred() or set_deferred() to change monitoring state instead**
   At: servers/physics_2d/physics_2d_server_sw.cpp:737.

this is a bug, possibly a regression brought by recent commits.

**Comment by Zireael07** [comment] 2019-03-02 19:53
> ERROR: body_set_shape_disabled: Can't change this state while flushing queries.
Use call_deferred() or set_deferred() to change monitoring state instead

I believe this was reported recently and is an intended change?

**Comment by capnm** [comment] 2019-03-02 20:09
> I believe this was reported recently and is an intended change?

Sure, i meant printing the error **only inside the terminal** which is invisible for most users is a bug.

**Comment by aaforcebox** [comment] 2019-03-03 02:46
It actually shows in the Terminal, I just didn't use to look there.

> Oh, I tested your project and the useful part of the error message is only printed on the (linux) terminal window

I guess in Linux the suggestion only shows in terminal too? So I'd say everything is working as intended then, but it would be awesome if the error showed in the Editor too...

![terminal](https://user-images.githubusercontent.com/35024229/53690227-62bb7180-3d45-11e9-8b18-1e2a788b5da2.PNG)

**Comment by capnm** [comment] 2019-03-03 05:47
> So I'd say everything is working as intended then, but it would be awesome if the error showed in the Editor too...

Yes. The error tab in the Godot interface is unusable in this case. I think that's bad too and that it should be fixed. Please open this issue again and change the title accordingly.
Thanks.

**Comment by akien-mga** [comment] 2019-03-03 09:50
The bug is a bit more complex than that, it only happens when using Multi-Threaded physics. I'll open a new issue about it with another MRP (as the one in this issue no longer triggers any error after b84b0152).

**Closed by akien-mga** 2019-03-03 09:50 UTC

**Comment by akien-mga** [comment] 2019-03-03 10:04
Moved to #26518.
