### ISSUE TITLE
New Scene Tabs won't close and create new tabs instead with middle mouse click (or double clicking)

### ISSUE THREAD

**Issue by Alriightyman** [godotengine/godot#59400] opened 2022-03-22 00:05 UTC
### Godot version

4.0 alpha 4

### System information

Windows 10; RTX 2060 Super; Vulkan

### Issue description

The 'New Scene' Tabs cannot be closed and create new tabs when double-clicking or middle mouse click.  Also, the right-click context menu options only show 'New Scene' and 'Save All Scenes'.  I've attached a video that shows the bug in action.
As a work around, if this happens, you can slightly drag a tab a bit and let go that will allow access to the right click context menu to close whatever tabs you need - also shown at end of video to clear the created tabs. 

https://user-images.githubusercontent.com/6556309/159381698-9585c623-2db9-4f91-b02f-b42695dd629c.mp4

### Steps to reproduce

I found this by accident when I went to close one of my open scenes by middle mouse button clicking.  It can be hard to repro at times - but with a combination of middle mouse clicking, and double-clicking, you should be able to recreate it. 

### Minimal reproduction project

None needed. Can reproduce with a new empty project.

**Comment by PucklaMotzer09** [comment] 2022-10-08 13:19
I can not reproduce this issue in v4.0.beta.custom_build [bbac8198f], because I can not create multiple empty scenes. In `EditorNode::new_scene` all empty scenes get removed:
https://github.com/godotengine/godot/blob/bbac8198f89c0cbf0da4293201e54aa847947370/editor/editor_node.cpp#L3769-L3778

**Comment by akien-mga** [comment] 2022-10-08 13:43
Thanks for testing. Closing as fixed. Please comment if this is still reproducible.

**Closed by akien-mga** 2022-10-08 13:43 UTC
Labels: bug, topic:editor
