### ISSUE TITLE
Unable to dynamically/realtime add property on MultiplayerSynchronizer

### ISSUE THREAD

**Issue by TheYellowArchitect** [godotengine/godot#71468] opened 2023-01-15 16:35 UTC
### Godot version

4.0 beta12

### System information

Artix Linux (Vulkan)

### Issue description

Using 1 multiplayer synchronizer per node/player, it is said that it's not as optimal as having 1 for all of them
![multiplayer-synchronizer](https://user-images.githubusercontent.com/25630803/212553264-1deca5a3-b2a3-4696-ae56-91caf338c058.png)

So, I went for having a MultiplayerSynchronizer (https://docs.godotengine.org/en/latest/classes/class_multiplayersynchronizer.html) for my entire scene, and adding properties to sync automatically, when a player node is created realtime.

It does not work. Here is the relevant code (which runs exclusively on the server):
```gdscript
var config : SceneReplicationConfig = $MultiplayerSynchronizer.replication_config
config.add_property(str(new_player_character.get_path(), ":position") as NodePath)#same results with ":global_position"
$MultiplayerSynchronizer.replication_config = config
print(config.get_properties())#it prints normally
```

**I do not know if its a bug, or dynamic property sync is just not supported, or I have misunderstood how the synchronizer works or is to be used.** The docs are extremely confusing since there is nothing on 4.0 netcoding, all demos are outdated and by extension don't work, and all tutorial videos start with ready-made projects and go backwards explaining what each thing does :(

### Steps to reproduce

Just run the MRP (Minimal Reproduction Project)

### Minimal reproduction project

[netsync.tar.gz](https://github.com/godotengine/godot/files/10420647/netsync.tar.gz)

**Comment by TheYellowArchitect** [comment] 2023-02-24 18:19
Possibly fixed by https://github.com/godotengine/godot/issues/65725

**Comment by AThousandShips** [comment] 2024-07-29 17:33
Closing as a duplicate of above, if this is still occuring on a supported version please open a new report

**Closed by AThousandShips** 2024-07-29 17:33 UTC
Labels: needs testing, topic:network
