### ISSUE TITLE
Label line spacing settings not working as expected in exported Windows binary due to additional newline being inserted

### ISSUE THREAD

**Issue by FarbrorMartin** [godotengine/godot#74351] opened 2023-03-04 11:05 UTC
### Godot version

4.0-stable

### System information

Windows 10, Forward+, Intel HD 620

### Issue description

In exported Windows binaries, the line spacing setting on the label font settings does not work properly. The line spacing is not like in the editor at all.
It seems like the setting is not applied at all in the exported binary.
In my example I used soft newlines to make multiple lines in the label.

This is the setting:
![image](https://user-images.githubusercontent.com/36861435/222896207-743870c0-0f0f-4f0c-95a9-ce4dc40feed0.png)

Editor:
![image](https://user-images.githubusercontent.com/36861435/222896235-85c1c12d-865a-4983-8c7a-d365569d942b.png)

Running from editor:
![image](https://user-images.githubusercontent.com/36861435/222896304-64b427b2-82b1-4547-b2d8-53bbf8f5670a.png)

Exported game:
![image](https://user-images.githubusercontent.com/36861435/222896254-0b0d157c-885c-4113-b039-628d55cf0c58.png)

### Steps to reproduce

Make a label with multiple lines of text. Set the line spacing to 0.
Compare the look of the label running in the editor and running an exported windows binary.

### Minimal reproduction project

N/A

**Comment by Calinou** [comment] 2023-03-19 03:49
@FarbrorMartin Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

**Comment by conradhappeliv** [comment] 2023-03-19 20:55
This has been happening to me since upgrading to Godot 4 as well. That being said, I just spent all morning trying to create a MRP and could not.

In my main project, I diff'd two `Label`s in a .tscn file (one affected by the bug, and one not) and couldn't find any meaningful difference between the two. Line endings (CRLF vs LF) seemed like a plausible suspect, but my .tscn file only had LFs.

_However,_ in the process, I discovered that I can fix the issue by simply copying the label's text and pasting it back in (in the Godot editor). The wildest part is that git showed no diffs in the .tscn file when I did this, but it very clearly fixed the issue. And now that I've fixed it, I can't seem to bring the issue back...

As far as I can tell, this is ONLY caused by the Label's text content. Changing theme, font, line spacing, LabelSettings, etc had no effect whatsoever.

My suspicion is that this is caused by either:
* git's handling of line endings or
* something in the `.godot` folder (I have these `.gitignore`d, so I'm not sure how my "fix" affected those)

**Comment by FarbrorMartin** [comment] 2023-03-19 21:08
Note that I only experienced the problem in exported binaries (Win 64). In the editor it works as expected for me.
I’ll try to upload an MRP tomorrow.

**Comment by conradhappeliv** [comment] 2023-03-19 21:21
This was happening to me even if I don't set line_spacing (or label_settings) at all, so I think the issue is something different than that setting not being applied. It was happening on `Label`s with everything (except the actual text) set to defaults, which is why I think that it's related to the text content itself.

**Comment by Rindbee** [comment] 2023-04-24 12:37
Probably related to `autowrap_mode` not being `AUTOWRAP_OFF`, similar to #74052.

**Comment by nezvers** [comment] 2023-05-24 15:57
I hoped to workaround with custom drawing a multi-line string, Same problem.
[CustomLabel.gd.zip](https://github.com/godotengine/godot/files/11556620/CustomLabel.gd.zip)

**Comment by EntroPiGames** [comment] 2023-06-02 09:48
I recently also ran into this issue when setting the text of a label from a C# script.

I was using the `System.Environment.NewLine` string instead of `"\n"` and the line spacing was different in the exported project.

I created a small test project to show the difference. 
The left label is using `"\n"`, the right label is using `System.Environment.NewLine`.

**Project run from editor in Windows:**

![image](https://github.com/godotengine/godot/assets/45169553/f13f82b8-3763-458a-8ad1-16e0831934cd)

**Exported Windows project:**

![image](https://github.com/godotengine/godot/assets/45169553/1866ed0a-25a9-478d-92d8-ee0fd5b7cacf)

On Windows `System.Environment.NewLine` is a string containing `\r\n` while on other platforms it is `\n`, so maybe that is why it only seems to affect projects exported for Windows? 
Regardless, it's weird that there's a difference between the editor and exported projects in Windows.

@Calinou I've added a minimal reproduction project: [NewLine.zip](https://github.com/godotengine/godot/files/11634013/NewLine.zip)

It uses the C# build of `4.0.3`.

**Comment by Calinou** [comment] 2023-06-02 10:44
Does this issue disappear if you disable **Editor > Export > Convert Text Resources to Binary** in the Project Settings before exporting?

**Comment by EntroPiGames** [comment] 2023-06-02 11:21
> Does this issue disappear if you disable **Editor > Export > Convert Text Resources to Binary** in the Project Settings before exporting?

No, disabling that option has no effect. 

Here's a screenshot of the exported project with the setting disabled:
![image](https://github.com/godotengine/godot/assets/45169553/0f517c6f-61df-4f22-b589-0d805da3676c)

**Comment by Calinou** [comment] 2023-07-16 02:50
- Duplicate of https://github.com/godotengine/godot/issues/71276.

**Closed by Calinou** 2023-07-16 02:50 UTC
Labels: bug, confirmed, topic:gui, topic:export

**Comment by VincentPoteet** [comment] 2024-03-18 19:28
I know I'm late to the party, but I just wanted to share how I dealt with the issue.
I just put this in a _ready() function or something:
```
text= text.c_escape()
text = text.replace("\\r\\n", "\n")
text = text.c_unescape()
```

Hope this happens to help someone!

-a gamer
