### ISSUE TITLE
Vulkan Mobile: Shader errors when using `textureLod(SCREEN_TEXTURE, ...)`

### ISSUE THREAD

**Issue by berarma** [godotengine/godot#67565] opened 2022-10-18 10:36 UTC
### Godot version

v4.0.beta3.official.01ae26d31

### System information

Debian GNU/Linux 11.5, Nvidia RTX 2070 Super (470.141.03)

### Issue description

I've tried some shaders to make a CRT effect but they don't work. As soon as the shader starts running the console is filled with error messages.

Here's the output.

```
Editing project: /home/berarma/Descargas/godot4/Test
Godot Engine v4.0.beta3.official.01ae26d31 - https://godotengine.org
Vulkan API 1.2.162 - Using Vulkan Device #0: NVIDIA - NVIDIA GeForce RTX 2070 SUPER
 
ERROR: Condition "font.is_null()" is true.
   at: _shape (scene/gui/line_edit.cpp:2202)
ERROR: Condition "font.is_null()" is true.
   at: _shape (scene/gui/line_edit.cpp:2202)
ERROR: Condition "font.is_null()" is true.
   at: _shape (scene/gui/line_edit.cpp:2202)
ERROR: Condition "font.is_null()" is true.
   at: _shape (scene/gui/line_edit.cpp:2202)
WARNING: Blend file import is enabled in the project settings, but no Blender path is configured in the editor settings. Blend files will not be imported.
     at: _editor_init (modules/gltf/register_types.cpp:76)
WARNING: FBX file import is enabled in the project settings, but no FBX2glTF path is configured in the editor settings. FBX files will not be imported.
     at: _editor_init (modules/gltf/register_types.cpp:100)
ERROR: Can't use the compute version of the copy_to_rect shader with the mobile renderer.
   at: copy_to_rect (servers/rendering/renderer_rd/effects/copy_effects.cpp:336)
ERROR: Can't use the compute version of the gaussian blur with the mobile renderer.
   at: gaussian_blur (servers/rendering/renderer_rd/effects/copy_effects.cpp:620)
ERROR: Can't use the compute version of the gaussian blur with the mobile renderer.
   at: gaussian_blur (servers/rendering/renderer_rd/effects/copy_effects.cpp:620)
ERROR: Can't use the compute version of the gaussian blur with the mobile renderer.
   at: gaussian_blur (servers/rendering/renderer_rd/effects/copy_effects.cpp:620)
ERROR: Can't use the compute version of the gaussian blur with the mobile renderer.
   at: gaussian_blur (servers/rendering/renderer_rd/effects/copy_effects.cpp:620)
ERROR: Can't use the compute version of the gaussian blur with the mobile renderer.
   at: gaussian_blur (servers/rendering/renderer_rd/effects/copy_effects.cpp:620)
ERROR: Can't use the compute version of the gaussian blur with the mobile renderer.
   at: gaussian_blur (servers/rendering/renderer_rd/effects/copy_effects.cpp:620)
ERROR: Can't use the compute version of the gaussian blur with the mobile renderer.
   at: gaussian_blur (servers/rendering/renderer_rd/effects/copy_effects.cpp:620)
ERROR: Can't use the compute version of the gaussian blur with the mobile renderer.
   at: gaussian_blur (servers/rendering/renderer_rd/effects/copy_effects.cpp:620)
ERROR: Can't use the compute version of the gaussian blur with the mobile renderer.
   at: gaussian_blur (servers/rendering/renderer_rd/effects/copy_effects.cpp:620)
ERROR: Can't use the compute version of the gaussian blur with the mobile renderer.
   at: gaussian_blur (servers/rendering/renderer_rd/effects/copy_effects.cpp:620)
ERROR: Can't use the compute version of the copy_to_rect shader with the mobile renderer.
   at: copy_to_rect (servers/rendering/renderer_rd/effects/copy_effects.cpp:336)
ERROR: Can't use the compute version of the gaussian blur with the mobile renderer.
   at: gaussian_blur (servers/rendering/renderer_rd/effects/copy_effects.cpp:620)
ERROR: Can't use the compute version of the gaussian blur with the mobile renderer.
   at: gaussian_blur (servers/rendering/renderer_rd/effects/copy_effects.cpp:620)
ERROR: Can't use the compute version of the gaussian blur with the mobile renderer.
   at: gaussian_blur (servers/rendering/renderer_rd/effects/copy_effects.cpp:620)
ERROR: Can't use the compute version of the gaussian blur with the mobile renderer.
   at: gaussian_blur (servers/rendering/renderer_rd/effects/copy_effects.cpp:620)
ERROR: Can't use the compute version of the gaussian blur with the mobile renderer.
   at: gaussian_blur (servers/rendering/renderer_rd/effects/copy_effects.cpp:620)
ERROR: Can't use the compute version of the gaussian blur with the mobile renderer.
   at: gaussian_blur (servers/rendering/renderer_rd/effects/copy_effects.cpp:620)
ERROR: Can't use the compute version of the gaussian blur with the mobile renderer.
   at: gaussian_blur (servers/rendering/renderer_rd/effects/copy_effects.cpp:620)
ERROR: Can't use the compute version of the gaussian blur with the mobile renderer.
   at: gaussian_blur (servers/rendering/renderer_rd/effects/copy_effects.cpp:620)
ERROR: Can't use the compute version of the gaussian blur with the mobile renderer.
   at: gaussian_blur (servers/rendering/renderer_rd/effects/copy_effects.cpp:620)
ERROR: Can't use the compute version of the gaussian blur with the mobile renderer.
   at: gaussian_blur (servers/rendering/renderer_rd/effects/copy_effects.cpp:620)
ERROR: Can't use the compute version of the copy_to_rect shader with the mobile renderer.
   at: copy_to_rect (servers/rendering/renderer_rd/effects/copy_effects.cpp:336)
ERROR: Can't use the compute version of the gaussian blur with the mobile renderer.
   at: gaussian_blur (servers/rendering/renderer_rd/effects/copy_effects.cpp:620)
ERROR: Can't use the compute version of the gaussian blur with the mobile renderer.
   at: gaussian_blur (servers/rendering/renderer_rd/effects/copy_effects.cpp:620)
ERROR: Can't use the compute version of the gaussian blur with the mobile renderer.
   at: gaussian_blur (servers/rendering/renderer_rd/effects/copy_effects.cpp:620)
ERROR: Can't use the compute version of the gaussian blur with the mobile renderer.
   at: gaussian_blur (servers/rendering/renderer_rd/effects/copy_effects.cpp:620)
ERROR: Can't use the compute version of the gaussian blur with the mobile renderer.
   at: gaussian_blur (servers/rendering/renderer_rd/effects/copy_effects.cpp:620)
ERROR: Can't use the compute version of the gaussian blur with the mobile renderer.
   at: gaussian_blur (servers/rendering/renderer_rd/effects/copy_effects.cpp:620)
ERROR: Can't use the compute version of the gaussian blur with the mobile renderer.
   at: gaussian_blur (servers/rendering/renderer_rd/effects/copy_effects.cpp:620)
ERROR: Can't use the compute version of the gaussian blur with the mobile renderer.
   at: gaussian_blur (servers/rendering/renderer_rd/effects/copy_effects.cpp:620)
ERROR: Can't use the compute version of the gaussian blur with the mobile renderer.
   at: gaussian_blur (servers/rendering/renderer_rd/effects/copy_effects.cpp:620)
ERROR: Can't use the compute version of the gaussian blur with the mobile renderer.
   at: gaussian_blur (servers/rendering/renderer_rd/effects/copy_effects.cpp:620)
ERROR: Can't use the compute version of the copy_to_rect shader with the mobile renderer.
   at: copy_to_rect (servers/rendering/renderer_rd/effects/copy_effects.cpp:336)
ERROR: Can't use the compute version of the gaussian blur with the mobile renderer.
   at: gaussian_blur (servers/rendering/renderer_rd/effects/copy_effects.cpp:620)
ERROR: Can't use the compute version of the gaussian blur with the mobile renderer.
   at: gaussian_blur (servers/rendering/renderer_rd/effects/copy_effects.cpp:620)
ERROR: Can't use the compute version of the gaussian blur with the mobile renderer.
   at: gaussian_blur (servers/rendering/renderer_rd/effects/copy_effects.cpp:620)
ERROR: Can't use the compute version of the gaussian blur with the mobile renderer.
   at: gaussian_blur (servers/rendering/renderer_rd/effects/copy_effects.cpp:620)
ERROR: Can't use the compute version of the gaussian blur with the mobile renderer.
   at: gaussian_blur (servers/rendering/renderer_rd/effects/copy_effects.cpp:620)
ERROR: Can't use the compute version of the gaussian blur with the mobile renderer.
   at: gaussian_blur (servers/rendering/renderer_rd/effects/copy_effects.cpp:620)
ERROR: Can't use the compute version of the gaussian blur with the mobile renderer.
   at: gaussian_blur (servers/rendering/renderer_rd/effects/copy_effects.cpp:620)
ERROR: Can't use the compute version of the gaussian blur with the mobile renderer.
   at: gaussian_blur (servers/rendering/renderer_rd/effects/copy_effects.cpp:620)
ERROR: Can't use the compute version of the gaussian blur with the mobile renderer.
   at: gaussian_blur (servers/rendering/renderer_rd/effects/copy_effects.cpp:620)
ERROR: Can't use the compute version of the gaussian blur with the mobile renderer.
   at: gaussian_blur (servers/rendering/renderer_rd/effects/copy_effects.cpp:620)
ERROR: Can't use the compute version of the copy_to_rect shader with the mobile renderer.
   at: copy_to_rect (servers/rendering/renderer_rd/effects/copy_effects.cpp:336)
ERROR: Can't use the compute version of the gaussian blur with the mobile renderer.
   at: gaussian_blur (servers/rendering/renderer_rd/effects/copy_effects.cpp:620)
ERROR: Can't use the compute version of the gaussian blur with the mobile renderer.
   at: gaussian_blur (servers/rendering/renderer_rd/effects/copy_effects.cpp:620)
ERROR: Can't use the compute version of the gaussian blur with the mobile renderer.
   at: gaussian_blur (servers/rendering/renderer_rd/effects/copy_effects.cpp:620)
ERROR: Can't use the compute version of the gaussian blur with the mobile renderer.
   at: gaussian_blur (servers/rendering/renderer_rd/effects/copy_effects.cpp:620)
ERROR: Can't use the compute version of the gaussian blur with the mobile renderer.
   at: gaussian_blur (servers/rendering/renderer_rd/effects/copy_effects.cpp:620)
ERROR: Can't use the compute version of the gaussian blur with the mobile renderer.
   at: gaussian_blur (servers/rendering/renderer_rd/effects/copy_effects.cpp:620)
ERROR: Can't use the compute version of the gaussian blur with the mobile renderer.
   at: gaussian_blur (servers/rendering/renderer_rd/effects/copy_effects.cpp:620)
ERROR: Can't use the compute version of the gaussian blur with the mobile renderer.
   at: gaussian_blur (servers/rendering/renderer_rd/effects/copy_effects.cpp:620)
ERROR: Can't use the compute version of the gaussian blur with the mobile renderer.
   at: gaussian_blur (servers/rendering/renderer_rd/effects/copy_effects.cpp:620)
ERROR: Can't use the compute version of the gaussian blur with the mobile renderer.
   at: gaussian_blur (servers/rendering/renderer_rd/effects/copy_effects.cpp:620)
ERROR: Can't use the compute version of the copy_to_rect shader with the mobile renderer.
   at: copy_to_rect (servers/rendering/renderer_rd/effects/copy_effects.cpp:336)
ERROR: Can't use the compute version of the gaussian blur with the mobile renderer.
   at: gaussian_blur (servers/rendering/renderer_rd/effects/copy_effects.cpp:620)
ERROR: Can't use the compute version of the gaussian blur with the mobile renderer.
   at: gaussian_blur (servers/rendering/renderer_rd/effects/copy_effects.cpp:620)
ERROR: Can't use the compute version of the gaussian blur with the mobile renderer.
   at: gaussian_blur (servers/rendering/renderer_rd/effects/copy_effects.cpp:620)
ERROR: Can't use the compute version of the gaussian blur with the mobile renderer.
   at: gaussian_blur (servers/rendering/renderer_rd/effects/copy_effects.cpp:620)
ERROR: Can't use the compute version of the gaussian blur with the mobile renderer.
   at: gaussian_blur (servers/rendering/renderer_rd/effects/copy_effects.cpp:620)
ERROR: Can't use the compute version of the gaussian blur with the mobile renderer.
   at: gaussian_blur (servers/rendering/renderer_rd/effects/copy_effects.cpp:620)
ERROR: Can't use the compute version of the gaussian blur with the mobile renderer.
   at: gaussian_blur (servers/rendering/renderer_rd/effects/copy_effects.cpp:620)
ERROR: Can't use the compute version of the gaussian blur with the mobile renderer.
   at: gaussian_blur (servers/rendering/renderer_rd/effects/copy_effects.cpp:620)
ERROR: Can't use the compute version of the gaussian blur with the mobile renderer.
   at: gaussian_blur (servers/rendering/renderer_rd/effects/copy_effects.cpp:620)
ERROR: Can't use the compute version of the gaussian blur with the mobile renderer.
   at: gaussian_blur (servers/rendering/renderer_rd/effects/copy_effects.cpp:620)
ERROR: Can't use the compute version of the copy_to_rect shader with the mobile renderer.
   at: copy_to_rect (servers/rendering/renderer_rd/effects/copy_effects.cpp:336)
ERROR: Can't use the compute version of the gaussian blur with the mobile renderer.
   at: gaussian_blur (servers/rendering/renderer_rd/effects/copy_effects.cpp:620)
ERROR: Can't use the compute version of the gaussian blur with the mobile renderer.
   at: gaussian_blur (servers/rendering/renderer_rd/effects/copy_effects.cpp:620)
ERROR: Can't use the compute version of the gaussian blur with the mobile renderer.
   at: gaussian_blur (servers/rendering/renderer_rd/effects/copy_effects.cpp:620)
ERROR: Can't use the compute version of the gaussian blur with the mobile renderer.
   at: gaussian_blur (servers/rendering/renderer_rd/effects/copy_effects.cpp:620)
ERROR: Can't use the compute version of the gaussian blur with the mobile renderer.
   at: gaussian_blur (servers/rendering/renderer_rd/effects/copy_effects.cpp:620)
ERROR: Can't use the compute version of the gaussian blur with the mobile renderer.
   at: gaussian_blur (servers/rendering/renderer_rd/effects/copy_effects.cpp:620)
ERROR: Can't use the compute version of the gaussian blur with the mobile renderer.
   at: gaussian_blur (servers/rendering/renderer_rd/effects/copy_effects.cpp:620)
ERROR: Can't use the compute version of the gaussian blur with the mobile renderer.
   at: gaussian_blur (servers/rendering/renderer_rd/effects/copy_effects.cpp:620)
ERROR: Can't use the compute version of the gaussian blur with the mobile renderer.
   at: gaussian_blur (servers/rendering/renderer_rd/effects/copy_effects.cpp:620)
ERROR: Can't use the compute version of the gaussian blur with the mobile renderer.
   at: gaussian_blur (servers/rendering/renderer_rd/effects/copy_effects.cpp:620)
ERROR: Can't use the compute version of the copy_to_rect shader with the mobile renderer.
   at: copy_to_rect (servers/rendering/renderer_rd/effects/copy_effects.cpp:336)
ERROR: Can't use the compute version of the gaussian blur with the mobile renderer.
   at: gaussian_blur (servers/rendering/renderer_rd/effects/copy_effects.cpp:620)
ERROR: Can't use the compute version of the gaussian blur with the mobile renderer.
   at: gaussian_blur (servers/rendering/renderer_rd/effects/copy_effects.cpp:620)
ERROR: Can't use the compute version of the gaussian blur with the mobile renderer.
   at: gaussian_blur (servers/rendering/renderer_rd/effects/copy_effects.cpp:620)
ERROR: Can't use the compute version of the gaussian blur with the mobile renderer.
   at: gaussian_blur (servers/rendering/renderer_rd/effects/copy_effects.cpp:620)
ERROR: Can't use the compute version of the gaussian blur with the mobile renderer.
   at: gaussian_blur (servers/rendering/renderer_rd/effects/copy_effects.cpp:620)
ERROR: Can't use the compute version of the gaussian blur with the mobile renderer.
   at: gaussian_blur (servers/rendering/renderer_rd/effects/copy_effects.cpp:620)
ERROR: Can't use the compute version of the gaussian blur with the mobile renderer.
   at: gaussian_blur (servers/rendering/renderer_rd/effects/copy_effects.cpp:620)
ERROR: Can't use the compute version of the gaussian blur with the mobile renderer.
   at: gaussian_blur (servers/rendering/renderer_rd/effects/copy_effects.cpp:620)
ERROR: Can't use the compute version of the gaussian blur with the mobile renderer.
   at: gaussian_blur (servers/rendering/renderer_rd/effects/copy_effects.cpp:620)
ERROR: Can't use the compute version of the gaussian blur with the mobile renderer.
   at: gaussian_blur (servers/rendering/renderer_rd/effects/copy_effects.cpp:620)
ERROR: Can't use the compute version of the copy_to_rect shader with the mobile renderer.
   at: copy_to_rect (servers/rendering/renderer_rd/effects/copy_effects.cpp:336)
ERROR: Can't use the compute version of the gaussian blur with the mobile renderer.
   at: gaussian_blur (servers/rendering/renderer_rd/effects/copy_effects.cpp:620)
ERROR: Can't use the compute version of the gaussian blur with the mobile renderer.
   at: gaussian_blur (servers/rendering/renderer_rd/effects/copy_effects.cpp:620)
ERROR: Can't use the compute version of the gaussian blur with the mobile renderer.
   at: gaussian_blur (servers/rendering/renderer_rd/effects/copy_effects.cpp:620)
ERROR: Can't use the compute version of the gaussian blur with the mobile renderer.
   at: gaussian_blur (servers/rendering/renderer_rd/effects/copy_effects.cpp:620)
ERROR: Can't use the compute version of the gaussian blur with the mobile renderer.
   at: gaussian_blur (servers/rendering/renderer_rd/effects/copy_effects.cpp:620)
ERROR: Can't use the compute version of the gaussian blur with the mobile renderer.
   at: gaussian_blur (servers/rendering/renderer_rd/effects/copy_effects.cpp:620)
ERROR: Can't use the compute version of the gaussian blur with the mobile renderer.
   at: gaussian_blur (servers/rendering/renderer_rd/effects/copy_effects.cpp:620)
ERROR: Can't use the compute version of the gaussian blur with the mobile renderer.
   at: gaussian_blur (servers/rendering/renderer_rd/effects/copy_effects.cpp:620)
ERROR: Can't use the compute version of the gaussian blur with the mobile renderer.
   at: gaussian_blur (servers/rendering/renderer_rd/effects/copy_effects.cpp:620)
ERROR: Can't use the compute version of the gaussian blur with the mobile renderer.
   at: gaussian_blur (servers/rendering/renderer_rd/effects/copy_effects.cpp:620)
ERROR: Can't use the compute version of the copy_to_rect shader with the mobile renderer.
   at: copy_to_rect (servers/rendering/renderer_rd/effects/copy_effects.cpp:336)
ERROR: Can't use the compute version of the gaussian blur with the mobile renderer.
   at: gaussian_blur (servers/rendering/renderer_rd/effects/copy_effects.cpp:620)
ERROR: Can't use the compute version of the gaussian blur with the mobile renderer.
   at: gaussian_blur (servers/rendering/renderer_rd/effects/copy_effects.cpp:620)
ERROR: Can't use the compute version of the gaussian blur with the mobile renderer.
   at: gaussian_blur (servers/rendering/renderer_rd/effects/copy_effects.cpp:620)
ERROR: Can't use the compute version of the gaussian blur with the mobile renderer.
   at: gaussian_blur (servers/rendering/renderer_rd/effects/copy_effects.cpp:620)
ERROR: Can't use the compute version of the gaussian blur with the mobile renderer.
   at: gaussian_blur (servers/rendering/renderer_rd/effects/copy_effects.cpp:620)
ERROR: Can't use the compute version of the gaussian blur with the mobile renderer.
   at: gaussian_blur (servers/rendering/renderer_rd/effects/copy_effects.cpp:620)
ERROR: Can't use the compute version of the gaussian blur with the mobile renderer.
   at: gaussian_blur (servers/rendering/renderer_rd/effects/copy_effects.cpp:620)
ERROR: Can't use the compute version of the gaussian blur with the mobile renderer.
   at: gaussian_blur (servers/rendering/renderer_rd/effects/copy_effects.cpp:620)
ERROR: Can't use the compute version of the gaussian blur with the mobile renderer.
   at: gaussian_blur (servers/rendering/renderer_rd/effects/copy_effects.cpp:620)
ERROR: Can't use the compute version of the gaussian blur with the mobile renderer.
   at: gaussian_blur (servers/rendering/renderer_rd/effects/copy_effects.cpp:620)
ERROR: Can't use the compute version of the copy_to_rect shader with the mobile renderer.
   at: copy_to_rect (servers/rendering/renderer_rd/effects/copy_effects.cpp:336)
ERROR: Can't use the compute version of the gaussian blur with the mobile renderer.
   at: gaussian_blur (servers/rendering/renderer_rd/effects/copy_effects.cpp:620)
ERROR: Can't use the compute version of the gaussian blur with the mobile renderer.
   at: gaussian_blur (servers/rendering/renderer_rd/effects/copy_effects.cpp:620)
ERROR: Can't use the compute version of the gaussian blur with the mobile renderer.
   at: gaussian_blur (servers/rendering/renderer_rd/effects/copy_effects.cpp:620)
ERROR: Can't use the compute version of the gaussian blur with the mobile renderer.
   at: gaussian_blur (servers/rendering/renderer_rd/effects/copy_effects.cpp:620)
ERROR: Can't use the compute version of the gaussian blur with the mobile renderer.
   at: gaussian_blur (servers/rendering/renderer_rd/effects/copy_effects.cpp:620)
ERROR: Can't use the compute version of the gaussian blur with the mobile renderer.
   at: gaussian_blur (servers/rendering/renderer_rd/effects/copy_effects.cpp:620)
ERROR: Can't use the compute version of the gaussian blur with the mobile renderer.
   at: gaussian_blur (servers/rendering/renderer_rd/effects/copy_effects.cpp:620)
ERROR: Can't use the compute version of the gaussian blur with the mobile renderer.
   at: gaussian_blur (servers/rendering/renderer_rd/effects/copy_effects.cpp:620)
ERROR: Can't use the compute version of the gaussian blur with the mobile renderer.
   at: gaussian_blur (servers/rendering/renderer_rd/effects/copy_effects.cpp:620)
ERROR: Can't use the compute version of the gaussian blur with the mobile renderer.
   at: gaussian_blur (servers/rendering/renderer_rd/effects/copy_effects.cpp:620)
ERROR: Can't use the compute version of the copy_to_rect shader with the mobile renderer.
   at: copy_to_rect (servers/rendering/renderer_rd/effects/copy_effects.cpp:336)
ERROR: Can't use the compute version of the gaussian blur with the mobile renderer.
   at: gaussian_blur (servers/rendering/renderer_rd/effects/copy_effects.cpp:620)
ERROR: Can't use the compute version of the gaussian blur with the mobile renderer.
   at: gaussian_blur (servers/rendering/renderer_rd/effects/copy_effects.cpp:620)
ERROR: Can't use the compute version of the gaussian blur with the mobile renderer.
   at: gaussian_blur (servers/rendering/renderer_rd/effects/copy_effects.cpp:620)
ERROR: Can't use the compute version of the gaussian blur with the mobile renderer.
   at: gaussian_blur (servers/rendering/renderer_rd/effects/copy_effects.cpp:620)
ERROR: Can't use the compute version of the gaussian blur with the mobile renderer.
   at: gaussian_blur (servers/rendering/renderer_rd/effects/copy_effects.cpp:620)
ERROR: Can't use the compute version of the gaussian blur with the mobile renderer.
   at: gaussian_blur (servers/rendering/renderer_rd/effects/copy_effects.cpp:620)
ERROR: Can't use the compute version of the gaussian blur with the mobile renderer.
   at: gaussian_blur (servers/rendering/renderer_rd/effects/copy_effects.cpp:620)
ERROR: Can't use the compute version of the gaussian blur with the mobile renderer.
   at: gaussian_blur (servers/rendering/renderer_rd/effects/copy_effects.cpp:620)
ERROR: Can't use the compute version of the gaussian blur with the mobile renderer.
   at: gaussian_blur (servers/rendering/renderer_rd/effects/copy_effects.cpp:620)
ERROR: Can't use the compute version of the gaussian blur with the mobile renderer.
   at: gaussian_blur (servers/rendering/renderer_rd/effects/copy_effects.cpp:620)
ERROR: Can't use the compute version of the copy_to_rect shader with the mobile renderer.
   at: copy_to_rect (servers/rendering/renderer_rd/effects/copy_effects.cpp:336)
ERROR: Can't use the compute version of the gaussian blur with the mobile renderer.
   at: gaussian_blur (servers/rendering/renderer_rd/effects/copy_effects.cpp:620)
ERROR: Can't use the compute version of the gaussian blur with the mobile renderer.
   at: gaussian_blur (servers/rendering/renderer_rd/effects/copy_effects.cpp:620)
ERROR: Can't use the compute version of the gaussian blur with the mobile renderer.
   at: gaussian_blur (servers/rendering/renderer_rd/effects/copy_effects.cpp:620)
ERROR: Can't use the compute version of the gaussian blur with the mobile renderer.
   at: gaussian_blur (servers/rendering/renderer_rd/effects/copy_effects.cpp:620)
ERROR: Can't use the compute version of the gaussian blur with the mobile renderer.
   at: gaussian_blur (servers/rendering/renderer_rd/effects/copy_effects.cpp:620)
ERROR: Can't use the compute version of the gaussian blur with the mobile renderer.
   at: gaussian_blur (servers/rendering/renderer_rd/effects/copy_effects.cpp:620)
ERROR: Can't use the compute version of the gaussian blur with the mobile renderer.
   at: gaussian_blur (servers/rendering/renderer_rd/effects/copy_effects.cpp:620)
ERROR: Can't use the compute version of the gaussian blur with the mobile renderer.
   at: gaussian_blur (servers/rendering/renderer_rd/effects/copy_effects.cpp:620)
ERROR: Can't use the compute version of the gaussian blur with the mobile renderer.
   at: gaussian_blur (servers/rendering/renderer_rd/effects/copy_effects.cpp:620)
ERROR: Can't use the compute version of the gaussian blur with the mobile renderer.
   at: gaussian_blur (servers/rendering/renderer_rd/effects/copy_effects.cpp:620)
ERROR: Can't use the compute version of the copy_to_rect shader with the mobile renderer.
   at: copy_to_rect (servers/rendering/renderer_rd/effects/copy_effects.cpp:336)
ERROR: Can't use the compute version of the gaussian blur with the mobile renderer.
   at: gaussian_blur (servers/rendering/renderer_rd/effects/copy_effects.cpp:620)
ERROR: Can't use the compute version of the gaussian blur with the mobile renderer.
   at: gaussian_blur (servers/rendering/renderer_rd/effects/copy_effects.cpp:620)
ERROR: Can't use the compute version of the gaussian blur with the mobile renderer.
   at: gaussian_blur (servers/rendering/renderer_rd/effects/copy_effects.cpp:620)
ERROR: Can't use the compute version of the gaussian blur with the mobile renderer.
   at: gaussian_blur (servers/rendering/renderer_rd/effects/copy_effects.cpp:620)
ERROR: Can't use the compute version of the gaussian blur with the mobile renderer.
   at: gaussian_blur (servers/rendering/renderer_rd/effects/copy_effects.cpp:620)
ERROR: Can't use the compute version of the gaussian blur with the mobile renderer.
   at: gaussian_blur (servers/rendering/renderer_rd/effects/copy_effects.cpp:620)
ERROR: Can't use the compute version of the gaussian blur with the mobile renderer.
   at: gaussian_blur (servers/rendering/renderer_rd/effects/copy_effects.cpp:620)
ERROR: Can't use the compute version of the gaussian blur with the mobile renderer.
   at: gaussian_blur (servers/rendering/renderer_rd/effects/copy_effects.cpp:620)
ERROR: Can't use the compute version of the gaussian blur with the mobile renderer.
   at: gaussian_blur (servers/rendering/renderer_rd/effects/copy_effects.cpp:620)
ERROR: Can't use the compute version of the gaussian blur with the mobile renderer.
   at: gaussian_blur (servers/rendering/renderer_rd/effects/copy_effects.cpp:620)
```

### Steps to reproduce

Selecting the shader node in the editor will throw error messages to the console very fast.

### Minimal reproduction project

[test.zip](https://github.com/godotengine/godot/files/9809431/test.zip)

**Comment by Sauermann** [comment] 2022-10-18 10:42
Duplicate of #67388
Fixed by #67389

**Comment by berarma** [comment] 2022-10-18 11:10
> Duplicate of #67388 Fixed by #67389

I've ignored that error as the release notes say, and also the warnings. Please, look at the other hundred errors about the shader.

**Comment by clayjohn** [comment] 2023-01-14 02:32
Duplicate of https://github.com/godotengine/godot/issues/50976.
Fixed by https://github.com/godotengine/godot/pull/56742

**Closed by clayjohn** 2023-01-14 02:32 UTC
Labels: bug, topic:rendering

**Comment by berarma** [comment] 2023-01-14 06:26
> Duplicate of https://github.com/godotengine/godot/issues/50976.
> Fixed by https://github.com/godotengine/godot/pull/56742
> 
> 

Please, read the comments.
