### ISSUE TITLE
Can't open project just because my GPU doesn't run Vulkan

### ISSUE THREAD

**Issue by mechPenSketch** [godotengine/godot#74217] opened 2023-03-02 08:10 UTC
### Godot version

v4.0.stable.official[92bee43ad]

### System information

Windows 10, AMD FirePro W5100 (15.200.1045.0 / Win10 64)

### Issue description

When I open a project, I get the following message instead:

![vulkan](https://user-images.githubusercontent.com/15977859/222363445-ccc12801-5f18-4d79-b729-33ea4cfb29d3.png)

My graphics does not support Vulkan, but it does with OpenGL. Although the current version of Godot can render with OpenGL, I am unable to open or edit the projects.

The only exception to this is when I create a new project. I am also able to open those new projects just fine.

### Steps to reproduce

Simply open the affected project while your graphics card does not run vulkan.

Projects affected:
* Those previous made in Godot 3.5
* Probable those made by other people (but that really depends on the render settings set onto the project)

### Minimal reproduction project

N/A

**Comment by Zireael07** [comment] 2023-03-02 08:13
duplicate of #57622

**Closed** 2023-03-02 08:16 UTC
