### ISSUE TITLE
ProjectSetting.save_custom("user:://override.cfg") with android plugin will cause USER ERROR: Cannot get class 'JNISingleton'.

### ISSUE THREAD

**Issue by AllenDang** [godotengine/godot#97546] opened 2024-09-27 15:08 UTC
### Tested versions

4.3 stable

### System information

Android

### Issue description

I'm trying to set game resolution at runtime, save it via `ProjectSetting.save_custom` and read it back. And I find no matter how I change the ProjectSetting, when I get the resolution, the value remains as initial.

So I tried to print the content of override.cfg, the new resolution is set, but accidentally, I noticed there is an error popup which might break the loading of override.cfg.

Here is the steps I did.

Add an android plugin to project, set Application/Config/ProjectSettingsOverride to "user://override.cfg", and invoke ProjectSetting.save_custom("user://override.cfg"). Following setction will be added to the top of override.cfg
```
config_version=5
AndroidPlugin=Object(JNISingleton,"script":null)
```

And error occurred states
```
USER ERROR: Cannot get class 'JNISingleton'.
    at: _instantiate_internal (core/object/class_db.cpp:515)
USER ERROR: Error parsing user://override.cfg at line 10: Can't instantiate Object() of type: JNISingleton File might be corrupted.
    at: _load_settings_text (core/config/project_settings.cpp:777)
```

### Steps to reproduce

1. open the MRP project
2. install android build template.
3. plug android phone
4. one click deploy the game to android
5. click Set High Res button
6. quit and kill game
7. restart the game
8. see the log from logcat

### Minimal reproduction project (MRP)

[repo97546.zip](https://github.com/user-attachments/files/17461753/repo97546.zip)

**Comment by AllenDang** [comment] 2024-10-11 08:37
Any response to this issue? or do I have to provide more info or something? This issue blocks our game to use custom project setting to adjust resolution and render quality stuff.

**Comment by syntaxerror247** [comment] 2024-10-12 04:56
@AllenDang I cannot reproduce this issue, i have tried with both v1 and v2 plugin.

**Comment by AllenDang** [comment] 2024-10-21 13:39
@syntaxerror247 I've managed to create a MRP to repo this issue, see attached.

[repo97546.zip](https://github.com/user-attachments/files/17461708/repo97546.zip)

Steps to repo:
1. open the project
2. install android build template.
3. plug android phone
4. one click deploy the game to andoird
5. click Set High Res
6. quit and kill game
7. restart the game
8. see the log from logcat

The error message will popup says 
```
USER ERROR: Cannot get class 'JNISingleton'.
 at: _instantiate_internal (core/object/class_db.cpp:515)
USER ERROR: Error parsing user://override.cfg at line 10: Can't instantiate Object() of type: JNISingleton File might be 
 at: _load_settings_text (core/config/project_settings.cpp:777)
```

**Comment by AllenDang** [comment] 2024-10-23 06:12
any update on this?

**Comment by syntaxerror247** [comment] 2024-10-23 07:43
I can now reproduce this in version 4.3, but it doesn't occur in the master branch. There were some recent updates related to JNISingleton, and it seems the issue has already been fixed. You can check 4.4 dev3 release.
CC @m4gr3d  @dsnopek

**Comment by m4gr3d** [comment] 2024-10-24 16:24
@AllenDang @syntaxerror247 This issue should have been resolved via https://github.com/godotengine/godot/pull/96624/files#diff-cad096f9d4cb422b6efe335ccb4384e14f7892e414e6517d939a61e0b698d980.

We may be able to backport the specific changes to `godot_plugin_jni` to the 4.3 release. Unless @AllenDang you're okay with waiting for the next 4.4 release (scheduled for early next year).

**Comment by AllenDang** [comment] 2024-10-25 02:10
@m4gr3d I can wait for the next 4.4 release, thanks :)

**Closed** 2024-10-25 14:20 UTC
Labels: bug, platform:android, topic:editor
