### ISSUE TITLE
Freezing during shader generation / loading

### ISSUE THREAD

**Issue by turtlewit** [godotengine/godot#24362] opened 2018-12-14 23:04 UTC
**Godot version:**

 3.0.6 and 3.1 alpha 3

**OS/device including version:** 

Arch Linux x86_64, Vega 56, Mesa 18.3

**Issue description:**

Godot freezes for upwards of 30 seconds when viewing an object for the first time or opening a project for the first time since clearing the `mesa_shader_cache` folder on Mesa 18.3.  
I think that the freezes happen when attempting to load or generate a shader for the first time. The freezes only happen once per shader.   
This issue was not present before upgrading to Mesa 18.3.  
There is no unusual output to the terminal when launching with verbose output.

**Steps to reproduce:**

- Move or delete `~/.cache/mesa_shader_cache` (Not required to experience the bug, but will produce the freezes for shaders that are already generated) 
- Open a 3D project.
- For further examples, try to view objects that haven't been viewed before (click on an object to view the translation gizmo, create a new mesh, etc).

**Minimal reproduction project:**

Simply creating a new project will produce the bug.

**Comment by turtlewit** [comment] 2018-12-15 06:35
No, this is unrelated. Shader generation typically takes a negligable amount of time. Specifically after upgrading to Mesa 18.3, the time to generate shaders becomes unreasonably long for me. The whole application locks up and stops responding for upwards of 30 seconds.

**Comment by G392** [comment] 2019-01-01 21:51
Same problem here. I'm using a Ryzen R5 2500U with Vega 8 graphics with Linux Manjaro and mesa-git.
I believe this is a mesa/amdgpu issue. This only seems to happen when using Godot's GLES3 renderer.

**Comment by ProbDenis** [comment] 2019-01-03 22:52
Oh, this seems to be a duplicate of #24340.
We should file a bug report for the mesa package on Arch Linux.

**Comment by akien-mga** [comment] 2019-01-04 13:58
Indeed, this needs to be taken to upstream Arch.

**Closed by akien-mga** 2019-01-04 13:58 UTC
Labels: bug, platform:linuxbsd, topic:editor, topic:rendering
