### ISSUE TITLE
Quickly pressing and releasing keyboard-combo shortcuts causes command to not run, works fine in other apps like VSCode

### ISSUE THREAD

**Issue by ianfitzpatrick** [godotengine/godot#68352] opened 2022-11-07 00:45 UTC
### Godot version

3.5, 4.0 beta4 (affects both)

### System information

Mac OS 12.6

### Issue description

Keyboard shortcuts on Mac OS will sometimes not launch correctly, if you enter and release the input fast enough.

For instance, default shortcut on Mac OS for "Run Scene" is `cmd + r`

If you quickly press `cmd + r` then release *both*, "Run Scene" will not launch. However, if you hold down `cmd` then press `r` then release *only* `r` while continuing to hold down `cmd`, "Run Scene" will execute consistently and correctly.

Here is a screencast with an overlay of inputs pressed using the app Keycastr:

https://user-images.githubusercontent.com/1757912/200209446-292de084-c9c3-4ca5-85f1-ce9d76644795.mp4

At first I issue the key combo at "normal" speeds and it doesn't run. Then, I use "always hold cmd key" method, and it works.

And here is the same key combo working correctly in VSCode, at full speed. I hope this eliminates any idea that this is something specific to my system. I can bring the goto symbol palette up using cmd + r consistently in VScode.

https://user-images.githubusercontent.com/1757912/200209484-edb7f6f0-cb99-4f14-b701-d686ec57879b.mp4

### Steps to reproduce

1. Open minimal project
2. Select scene "Player"
3. Press `cmd` and `r` quickly, then release both quickly
4. Run Scene will not launch

One interesting note is the "Run Scene" icon does change from gray to blue when pressing the keyboard shortcut fast (though the scene is not run). So it seems to be somehow receiving the shortcut in some form.

### Minimal reproduction project

See attached zip file for project, and steps to reproduce for instructions.

[First 2D Godot Game.zip](https://github.com/godotengine/godot/files/9947254/First.2D.Godot.Game.zip)

**Comment by Calinou** [comment] 2022-12-29 19:58
Duplicate of https://github.com/godotengine/godot/issues/45033 (same cause).

**Closed by Calinou** 2022-12-29 19:58 UTC
Labels: bug, platform:macos, usability, topic:input
