### ISSUE TITLE
Runtime TileData modifications are discarded after reparenting

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#88605] opened 2024-02-20 21:05 UTC
### Tested versions

4.3 dev3
4.3 1aab6e9
Does not happen in 4.2.1

### System information

Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1060 (NVIDIA; 30.0.15.1403) - Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 Threads)

### Issue description

When TileMap is reparented, the modifications from `_tile_data_runtime_update()` are discarded, but the method is not called again. Here I'm reparenting the TileMap and the method that disables collisions don't run:

https://github.com/godotengine/godot/assets/2223172/4ea7ab8d-2085-4831-8f46-be21cffc3264

### Steps to reproduce

1. Use `_tile_data_runtime_update()` to change something
2. Reparent the TileMap
3. Notice that your changes are gone

### Minimal reproduction project (MRP)

[TileMapBug.tscn.txt](https://github.com/godotengine/godot/files/14351121/TileMapBug.tscn.txt)

**Comment by matheusmdx** [comment] 2024-05-15 03:22
Bisecting points to #87115 as culprit:

![image](https://github.com/godotengine/godot/assets/44306054/7713ee07-3e2f-4a0a-854a-9a77f3946821)

**Comment by groud** [comment] 2024-05-27 09:24
Tested with latest master, I cannot reproduce the bug with the provided MRP.
Could you confirm it is fixed on master?

**Closed** 2024-05-27 09:28 UTC
Labels: bug, regression, topic:2d
