### ISSUE TITLE
Failed to compile android export templates 

### ISSUE THREAD

**Issue by yuyoDev** [godotengine/godot#12737] opened 2017-11-08 03:35 UTC
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Tested in Mac Mini 2014 and ArchLinux 64Bits, Godot 3.0 last commit #12730.

**Issue description:**
Failed to compile the export templates for android:
[  8%] Compiling ==> main/tests/test_physics.cpp
[  9%] Compiling ==> modules/register_module_types.gen.cpp
[ 10%] Compiling ==> thirdparty/bullet/src/BulletCollision/BroadphaseCollision/btAxisSweep3.cpp
[ 10%] Compiling ==> thirdparty/bullet/src/BulletCollision/BroadphaseCollision/btBroadphaseProxy.cpp
In file included from thirdparty/bullet/src/BulletCollision/BroadphaseCollision/btAxisSweep3.cpp:20:
In file included from thirdparty/bullet/src/BulletCollision/BroadphaseCollision/btAxisSweep3.h:23:
In file included from thirdparty/bullet/src/BulletCollision/BroadphaseCollision/btOverlappingPairCache.h:24:
thirdparty/bullet/src/LinearMath/btAlignedObjectArray.h:39:10: fatal error: 'new' file not found
#include <new> //for placement new
         ^~~~~
1 error generated.
[ 10%] Compiling ==> thirdparty/bullet/src/BulletCollision/BroadphaseCollision/btCollisionAlgorithm.cpp
scons: *** [thirdparty/bullet/src/BulletCollision/BroadphaseCollision/btAxisSweep3.android.opt.armv7.neon.o] Error 1
In file included from thirdparty/bullet/src/BulletCollision/BroadphaseCollision/btCollisionAlgorithm.cpp:16:
In file included from thirdparty/bullet/src/BulletCollision/BroadphaseCollision/btCollisionAlgorithm.h:20:
thirdparty/bullet/src/LinearMath/btAlignedObjectArray.h:39:10: fatal error: 'new' file not found
#include <new> //for placement new
         ^~~~~
1 error generated.
scons: *** [thirdparty/bullet/src/BulletCollision/BroadphaseCollision/btCollisionAlgorithm.android.opt.armv7.neon.o] Error 1
scons: building terminated because of errors.

Simple: just try to build Android export templates

**Comment by akien-mga** [comment] 2017-11-08 09:14
Duplicate of #12347.

**Closed by akien-mga** 2017-11-08 09:14 UTC

**Comment by theblockhouse** [comment] 2018-10-10 04:31
I'm still having this issue when compiling 3.0.6-stable despite compiling fine with 3.1 alpha
