### ISSUE TITLE
Godot 4.3-rc2  new function Label.get_character_bounds(character pos) not working as expected

### ISSUE THREAD

**Issue by DanielJaramillo94** [godotengine/godot#95088] opened 2024-08-03 01:02 UTC
### Tested versions

4.3.rc2

### System information

Windows 11

### Issue description

Function introduced in [PR-84185](https://github.com/godotengine/godot/pull/84185) (`Label.get_character_bounds(character pos)`) is not woking as expected.

Here can be seen that the `Rect2` returned by the function has an offset
![image](https://github.com/user-attachments/assets/870cf0d4-f146-4920-bbc0-aa87d4d269db)

The offset occurs when I nest the `Label` node inside a tree of another nodes, in this case a `MarginContainer`. I was expecting the function return the global position of the character.

### Steps to reproduce

Just open the MRP and run the project 

### Minimal reproduction project (MRP)

[MRP.zip](https://github.com/user-attachments/files/16476969/MRP.zip)

**Comment by kleonc** [comment] 2024-08-03 10:50
> Function introduced in [PR-84185](https://github.com/godotengine/godot/pull/84185) (`Label.get_character_bounds(character pos)`) is not woking as expected.
> 
> Here can be seen that the `Rect2` returned by the function has an offset
> ![image](https://private-user-images.githubusercontent.com/29381519/354775832-870cf0d4-f146-4920-bbc0-aa87d4d269db.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI2Nzg3MTgsIm5iZiI6MTcyMjY3ODQxOCwicGF0aCI6Ii8yOTM4MTUxOS8zNTQ3NzU4MzItODcwY2YwZDQtZjE0Ni00OTIwLWJiYzAtYWE4N2Q0ZDI2OWRiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODAzVDA5NDY1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVmOGViZjQ5MDA0ZWI3NThhMTk4MTAwY2M5Yjk4NTcwM2MxNzRiYWM3YzU5ZjllYzM1NzJmMGM1MWM2MTU5ZWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4nMKAaRSDXiYP4FUd0RdmgUAfonxb9reQdJhOqbzBDE)
> 
> The offset occurs when I nest the `Label` node inside a tree of another nodes, in this case a `MarginContainer`. I was expecting the function return the global position of the character.

It works as intended, it's meant to return the bounding rect of the given character in the Label's local coordinate space. Not sure why would you assume the returned rect is in a coordinate space different than the local one, the docs do not state so:
https://github.com/godotengine/godot/blob/3978628c6cc1227250fc6ed45c8d854d24c30c30/doc/classes/Label.xml#L13-L18

AFAIK it's _"local by default unless stated otherwise"_, and there's nothing special about this method. In the similar manner e.g. `Label.get_line_height(line_index)` returns the local height.

This could of course be clarified / explicitly stated in the docs, similarily like e.g. for `Line2D.points`:
https://github.com/godotengine/godot/blob/3978628c6cc1227250fc6ed45c8d854d24c30c30/doc/classes/Line2D.xml#L85-L87

---

If you want the bounding rect in some other coordinate space (e.g. in canvas (aka global), viewport, screen, or some other CanvasItem's space; see [the docs about different coordinate spaces/systems](https://docs.godotengine.org/en/latest/tutorials/2d/2d_transforms.html)) then you'd need to transform it into such space.

E.g. in the MRP this:
```gdscript
extends Node2D

@onready var label_node: Label = %Label

func _ready() -> void:
	label_node.item_rect_changed.connect(queue_redraw)

func _draw():
	var label_local_to_self_local: Transform2D = get_global_transform_with_canvas().affine_inverse() * label_node.get_global_transform_with_canvas()
	
	var char_rect_label_local: Rect2 = label_node.get_character_bounds(0)
	var char_rect_self_local: Rect2 = label_local_to_self_local * char_rect_label_local
	
	draw_rect(char_rect_self_local, Color.RED, false)
	
	draw_set_transform_matrix(label_local_to_self_local)
	draw_rect(char_rect_label_local, Color.GREEN, false)
```
and rotating the MarginContainer (just for showcasing):
![Godot_v4 3-rc2_win64_69EB1WMtIG](https://github.com/user-attachments/assets/807b7e66-6c39-4a4e-9909-76380afa7e75)
produces:
![Godot_v4 3-rc2_win64_mxrPI98Kpr](https://github.com/user-attachments/assets/9f64a050-c6a4-4242-bab4-d35b1b35f5da)

**Comment by DanielJaramillo94** [comment] 2024-08-03 16:06
Thank you so much for the great explaination and clean example code.

**Comment by lpenguin** [comment] 2024-09-12 15:32
Hi! If would take this issue to implement what should be done in order to close it? Update the documentation?

**Comment by AThousandShips** [comment] 2024-09-12 15:33
That would be the solution yes, here in the file kleonc linked above

**Closed** 2024-09-17 07:21 UTC
Labels: documentation, topic:gui
