### ISSUE TITLE
MSDF has no effect on tooltips

### ISSUE THREAD

**Issue by turqueschultz** [godotengine/godot#77715] opened 2023-05-31 21:44 UTC
### Godot version

4.0.3

### System information

Windows 10

### Issue description

Using a font with multichannel signed distance field enabled has no effect on tooltips:

![tooltip_msdf](https://github.com/godotengine/godot/assets/124798883/abcf3997-4e67-4e62-bef5-c1b87646e15a)

### Steps to reproduce

1 - Add a Label node;
2 - Add text to the "tooltip_text" field;
3 - Set "mouse_filter" to Control.MOUSE_FILTER_STOP;
4 - Add a theme to the Label;
5 - Add the "TooltipLabel" type to the theme;
6 - Set a font with MSDF enabled in the "font" property;
7 - Run the project;
8 - Hover the Label with the mouse.

### Minimal reproduction project

[tooltip_msdf.zip](https://github.com/godotengine/godot/files/11619004/tooltip_msdf.zip)

**Comment by Calinou** [comment] 2023-06-01 08:49
- Duplicate of https://github.com/godotengine/godot/issues/54030.

MSDF works on tooltips (notice the lack of font hinting in the tooltip), but tooltips are rendered at a lower resolution than the rest of the window. Notice how the popup's corners (which are drawn with a polygon-based StyleBoxFlat) are blurry as well.

**Closed by Calinou** 2023-06-01 08:49 UTC
Labels: bug, topic:rendering, topic:2d
