### ISSUE TITLE
SurfaceTool uses wrong color or is rendered incorrectly

### ISSUE THREAD

**Issue by Dr4kzor** [godotengine/godot#62361] opened 2022-06-23 21:14 UTC
### Godot version

Godot Engine v3.4.4.stable.official.419e713a2

### System information

Windows 11 OpenGL ES 3.0 Renderer: NVIDIA GeForce RTX 3060 Laptop GPU/PCIe/SSE2

### Issue description

When using a color to draw with the SurfaceTool we get a color that does not match the same used on a pre-generated MeshInstance..
![ColorBug](https://user-images.githubusercontent.com/51714674/175400593-09aea337-4d11-4c0c-b1b3-ce8ac66ac252.png)

### Steps to reproduce

Create a MeshInstance, pick a dark color for the Albedo and turn on UNSHADED.
Generate a Mesh using SurfaceTool, use the same color as before and set Use vertex colors as Albedo to true and set UNSHADED true.

### Minimal reproduction project

[Bug.zip](https://github.com/godotengine/godot/files/8970976/Bug.zip)

**Comment by Calinou** [comment] 2022-06-23 21:17
Related to https://github.com/godotengine/godot/issues/61892.

This is a sRGB -> linear conversion issue (or the other way around). You need to convert the color from linear to sRGB when passing it to SurfaceTool.

**Comment by Dr4kzor** [comment] 2022-06-24 01:40
The option from SpatialMaterial "vertex_color_is_srgb"  does nothing, but drawing into a viewport with "keep 3d linear" set as true gives the exact expected color as a result.  Is there a built in way to convert the color?

**Comment by clayjohn** [comment] 2022-06-28 16:22
I opened the MRP and tested out. I could reproduce the stated issue locally. However, upon adding the line suggested by Calinou above: ``spatial_mat.vertex_color_is_srgb = true`` the issue was resolved and the cubes appeared identical in color.

Accordingly, this is a duplicate of #61892 . The solution is add more references to the ``vertex_color_is_srgb`` property so that it is easier to find when users are confused about linear/srgb colors not matching up.

**Closed by clayjohn** 2022-06-28 16:22 UTC
Labels: topic:rendering, topic:3d
