### ISSUE TITLE
Exported custom Application Icon not working

### ISSUE THREAD

**Issue by daafu** [godotengine/godot#3852] opened 2016-02-27 17:42 UTC
**Operating system or device:**
Windows 10 host, Windows Desktop export with all variants 32/64/Debug/Release
Export template: Godot_v2.0_stable_20160223_export_templates.tpz

**Issue description** (what happened, and what was expected):
A custom icon was selected, original icon.png was removed from project. The project shows the correct icon in Project Manager window, but when exported the application icon is the default Godot icon.

Update 2/27: This likely relates to #3853 indirectly. It appears that exported Godot applications run as a subprocess of "Godot Engine Editor" process. The application icon that is shown is probably the icon of the parent process. I've noticed that in Windows Task Manager listing the subprocess has the correct icon.

**Steps to reproduce:**
Pick custom icon, export windows project

**Comment by Calinou** [comment] 2016-02-28 18:47
We removed `pe_bliss` from Godot recently, so Windows export executables can no longer have custom icons.

**Comment by Tybobobo** [comment] 2016-03-15 23:53
Same issue here.
Windows 7, 64bit. Steam version as of 16.03.16.
The export process do not produce the set application icon which is found in Project Settings -> Application -> Icon.

**Comment by mateusak** [comment] 2016-04-21 17:56
So... is it going to be fixed?

**Comment by reduz** [comment] 2016-04-21 17:58
Not for now.. executables modified by pe_bliss contained several issues and
would not run, so we had to remove the library.
The only alternatives we have is to use an external tool or use Windows
APIs (as in, running Godot under Windows) to get this to work..

**Comment by akien-mga** [comment] 2016-05-19 09:03
Closing as duplicate of #1211.

> Shouldn't be that hard...

Harder than you'd think.

**Closed by akien-mga** 2016-05-19 09:03 UTC
Labels: bug, platform:windows, topic:core
