### ISSUE TITLE
`BaseButton.pressed` is both a signal and property

### ISSUE THREAD

**Issue by HaSa1002** [godotengine/godot#50324] opened 2021-07-09 20:04 UTC
### Godot version

4.0.dev (a5b2988)

### System information

Windows 10

### Issue description

You can't bind to `BaseButton.pressed`, becasue it is both a signal and a property.

### Steps to reproduce

```
func _ready():
	var btn = Button.new()
	add_child(btn)
	btn.pressed.connect(self.on_button_pressed) # Cannot find property "connect" on base "bool".

func _on_btn_pressed():
	pass
```

**Comment by pycbouh** [comment] 2021-07-09 20:30
I think that has already been reported in the tracker issue and there is a PR but no consensus on the new names.

https://github.com/godotengine/godot/pull/48193

**Comment by KoBeWi** [comment] 2021-07-09 22:42
Duplicate of #38937

**Closed by KoBeWi** 2021-07-09 22:42 UTC
Labels: regression, topic:gui
