### ISSUE TITLE
Export Template Manager download extremely slow

### ISSUE THREAD

**Issue by Keetz** [godotengine/godot#16161] opened 2018-01-29 10:07 UTC
**Godot version:**
Godot RC3

**Issue description:**
Downloading the export templates through the Export Template Manager in the editor takes way longer (same mirror) than downloading them manually.

**Steps to reproduce:**

1. Download export templates through the editor manager and start your favourite Netflix show. Then wait.
2. Try downloading them manually from the same mirror, for example https://downloads.tuxfamily.org/godotengine/3.0/rc3/Godot_v3.0-rc3_export_templates.tpz

**Comment by akien-mga** [comment] 2018-01-29 10:32
Duplicate of #15950.

**Comment by mhilbrunner** [comment] 2018-01-29 10:33
Duplicate of  #15950.

**Closed by akien-mga** 2018-01-29 10:32 UTC

**Comment by akien-mga** [comment] 2018-01-29 10:37
I was faster :P
