### ISSUE TITLE
Shader parameters not persisted in web export when running in headless mode

### ISSUE THREAD

**Issue by HunterNN** [godotengine/godot#88033] opened 2024-02-06 21:13 UTC
### Tested versions

- 4.2.1.stable.arch_linux

### System information

Godot v4.2.1.stable unknown - Manjaro Linux #1 SMP PREEMPT_DYNAMIC Fri Jan  5 17:36:36 UTC 2024 - X11 - Vulkan (Mobile) - dedicated NVIDIA GeForce RTX 4080 (nvidia; 545.29.06) - AMD Ryzen 9 7950X 16-Core Processor (32 Threads)

### Issue description

When using shader parameters in a Godot project, the parameter values are not persisted in the web exported version of the project. This issue occurs even though the shader itself is correctly included in the exported files.

This problem is especially noticeable when using the command line to export a fresh project, as the _.godot_ folder may not be present.

### Steps to reproduce

- Download MRP
- Create a web export with `godot --headless --verbose --export-release "Web" /tmp/web/index.html`
- Run the web export with [serve.py](https://raw.githubusercontent.com/godotengine/godot/master/platform/web/serve.py)
- The Godot icon is not colored blue because the state of the shader parameter _active_ is not being set to true in the exported version. 
- Running the project in the editor, the icon is colored blue.
- There is a script attached to the Godot icon. In this script, you can uncomment a line which will set the _active_ property **again** to true when the node is ready. When this line is uncommented, the icon will appear in blue in the exported version.

### Minimal reproduction project (MRP)

[Shader Test.zip](https://github.com/godotengine/godot/files/14186017/Shader.Test.zip)

**Comment by AThousandShips** [comment] 2024-02-06 21:20
This sounds like a duplicate of:
* https://github.com/godotengine/godot/issues/66842

And isn't web specific, and has been resolved

**Comment by clayjohn** [comment] 2024-03-06 03:43
@HunterNN Can you test again with a recent dev build? https://godotengine.org/article/dev-snapshot-godot-4-3-dev-4/

**Comment by HunterNN** [comment] 2024-03-06 14:10
Looks solved to me
(Tested it with a Laptop Manjaro Linux)

**Comment by akien-mga** [comment] 2024-03-06 14:13
Thanks for the confirmation! Closing as likely duplicate of #66842 then.

**Closed by akien-mga** 2024-03-06 14:13 UTC
Labels: bug, needs testing, topic:shaders, topic:export
