### ISSUE TITLE
Error message taking up screen space

### ISSUE THREAD

**Issue by DleanJeans** [godotengine/godot#25042] opened 2019-01-16 16:53 UTC
**Godot version:** Godot 3.1 Beta 1

**OS/device including version:** Windows 10 64-bit

**Issue description:** **THIS**
![image](https://user-images.githubusercontent.com/12462089/51264680-a4889680-19e9-11e9-8187-65a38347d098.png)

**Comment by eon-s** [comment] 2019-01-16 17:15
Duplicate of #22302

**Closed** 2019-01-16 17:44 UTC
