### ISSUE TITLE
Tool script that has a exported typed array with a setter doesn't load the variable after scene reload

### ISSUE THREAD

**Issue by Evimilly** [godotengine/godot#60807] opened 2022-05-05 22:34 UTC
### Godot version

v4.0.alpha7.official [3e9ead05f]

### System information

Arch Linux, Vulkan

### Issue description

Adding new array elements to a typed array in the inspector, then saving it and then closing the scene and openning it again doesn't save array elements as expected, instead its empty.
It only happens when there is a tool script with an exported variable that has a setter.
Without set, tool, or typed Array like ``Array[int]`` it works as expected.
Here's a code example:
```gdscript
@tool
extends Node
@export var variable: Array[String]:
	get: 
		return variable
	set(value):
		variable = value
```

### Steps to reproduce

https://user-images.githubusercontent.com/28687947/167030214-785a39df-5665-4f46-8fe3-457160432658.mp4

1. Open the project in Godot v4.0.alpha7
2. Open "Bug" scene
3. Click on the "Node"
4. Add elements to the array "variable"
5. Save
6. Close the scene
7. Open it again

### Minimal reproduction project

[tool_export_bug.zip](https://github.com/godotengine/godot/files/8635817/tool_export_bug.zip)

**Comment by Calinou** [comment] 2022-05-05 22:53
Duplicate of https://github.com/godotengine/godot/issues/58285.

**Closed by Calinou** 2022-05-05 22:53 UTC
Labels: bug, topic:gdscript, topic:editor
