### ISSUE TITLE
Play Project Results in Project Selection

### ISSUE THREAD

**Issue by brainsick** [godotengine/godot#13614] opened 2017-12-02 00:06 UTC
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Windows 10, Godot 3.0 Beta 1, AMD R9 Fury

**Issue description:**
When I go to play my project, about 1/10th of the time I get the Godot project selection dialog instead of my project's main scene.

**Steps to reproduce:**
Create a new project, define a scene, set it as the main scene, run your project repeatedly.

**Link to minimal example project:**
https://youtu.be/N8vpZNqvAas

**Comment by vnen** [comment] 2017-12-02 00:37
Thanks for the report. This a duplicate of #11391.

**Closed by vnen** 2017-12-02 00:37 UTC
