### ISSUE TITLE
This shape is not supported to be kinematic (3D)

### ISSUE THREAD

**Issue by swipis** [godotengine/godot#14958] opened 2017-12-22 19:15 UTC
**Godot version:**
Build latest from GitHub (v3.0.beta.custom_build)

**OS/device including version:**
Os: Solus Os 3 (64-bit)
Graphics: GeForce GTX 760
Processor: i7-2600

**Issue description:**
Made model in Blender and exported with Better Collada (used -col), imported into Godot and when run I getting **warning** _**copyAllOwnerShapes: This shape is not supported to be kinematic! At: modules/bullet/rigid_body_bullet.cpp:241**_

Not sure this is a bug or I made something wrong when making model/exporting/importing.

If need I can upload dea file

**Comment by AndreaCatania** [comment] 2018-02-27 06:50
This is not a bug, You can move only primitive shapes and convex shapes

**Comment by rcorre** [comment] 2018-08-06 23:25
The error message isn't very helpful though. I spent a long time trying to figure out how to properly import my model when I finally realized the problem wasn't the model at all, it was the plane collision shape I added to it.

Could we update the error message to "<kind of shape> is not supported to be kinematic!" to aid in debugging?

**Comment by TomWor** [comment] 2018-09-01 21:46
Also I want to note that this issue in my case resulted into a massive frame rate drop.
Once I solved this issue my FPS went up from ~20FPS to ~60FPS. 
Maybe the Plane collision shape node could indicate being falsely assigned by being red or something.

**Comment by reduz** [comment] 2018-09-06 15:59
Closing because this is not a bug. There is a warning already specifying this.

**Closed by reduz** 2018-09-06 15:59 UTC
Labels: bug, discussion, topic:physics
