### ISSUE TITLE
TileMap Editor does not function properly

### ISSUE THREAD

**Issue by gururise** [godotengine/godot#14388] opened 2017-12-07 18:38 UTC
Godot 3.0 - Linux

**Issue description:**
Placing tiles on a Tilemap in the editor is bugged.

**Steps to reproduce:**
1. Create Tileset
2. Create new scene with tilemap, and use the tileset above as the texture.

When placing tiles, after you let go of the mouse button, about half the tiles disappear.  With every subsequent click and release of the left mouse button on the tilemap, more tiles randomly disappear:
![tilemap](https://user-images.githubusercontent.com/4380009/33732239-a6ebed80-db3a-11e7-88df-a942a751156e.gif)

**Comment by vnen** [comment] 2017-12-07 22:13
cc @MarianoGnu

**Comment by MarianoGnu** [comment] 2017-12-08 11:36
holy sh...

**Comment by CyanBlob** [comment] 2017-12-08 20:53
@MarianoGnu I saw this behavior as well a couple of days ago. I'm not sure exactly what caused it, but it wasn't happening last night when I tested it again. I'll see if I can figure out what the cause is tonight, but I don't have much time.
@gururise Does this happen for you all the time, even with different tilesets/tilemaps?

**Comment by PJB3005** [comment] 2017-12-08 20:57
I also think it got fixed very recently, let me check.

**Comment by gururise** [comment] 2017-12-08 21:14
@CyanBlob I just pulled and built a new build today.  I created a brand new tileset and got the same results:
![image](https://user-images.githubusercontent.com/4380009/33785312-4bf014bc-dc19-11e7-8d21-1ec03f2a4f35.png)

I am using tilesizes of 32x32 if it make any difference.  I am also on Linux.

Attached is the sample project.
[tileProject.zip](https://github.com/godotengine/godot/files/1543833/tileProject.zip)

**Comment by PJB3005** [comment] 2017-12-08 21:37
Ok, so I just checked. The bug only seems to happen just after creating the TileMap node. Closing and re-opening the scene seems to fix it permanently.

**Comment by CyanBlob** [comment] 2017-12-09 01:28
I can confirm @PJB3005's comment after some brief testing. After adding a new TileMap node, the bug occurs until the scene is reloaded (I used Scene->Revert Scene to test).
I also occasionally got this error:
    scene/resources/tile_set.cpp:394 - Condition ' !tile_map.has(p_id) ' is true. returned: false
Which is inside the TileSet::tile_get_is_autotile function

**Comment by MarianoGnu** [comment] 2017-12-09 12:13
@PJB3005 @CyanBlob i'm very sure of the cause of this bug is the code i wrote to allow open 2.1 tilemaps.
https://github.com/godotengine/godot/blob/master/scene/2d/tile_map.cpp#L963
https://github.com/godotengine/godot/blob/master/scene/2d/tile_map.cpp#L1012

adding this line to `get_tile_data()` might fix it.
`    format = FORMAT_2_1_5;`
will give it a look if i get some spare time, meanwhile, `hero wanted!`

**Comment by akien-mga** [comment] 2017-12-09 12:33
What are those `2_1_4` and `2_1_5` formats?

**Comment by MarianoGnu** [comment] 2017-12-09 13:11
they are on tile_map.h, i didn't know how to name them but since they are not exposed to gdscript it doesn't matter, they can be renamed anytime.

**Comment by CyanBlob** [comment] 2017-12-09 16:47
Alright, I opened a PR with the change @MarianoGnu suggested and can confirm that it did fix the issue. I also renamed the DataFormat enum members per @akien-mga

**Comment by gururise** [comment] 2017-12-10 01:04
Can also confirm the PR submitted by @CyanBlob fixed the issue.

**Comment by akien-mga** [comment] 2017-12-10 01:06
Fixed by #14454.

**Closed by akien-mga** 2017-12-10 01:06 UTC
Labels: bug, hero wanted!, topic:editor
