### ISSUE TITLE
gltf importer ignoring "-colonly" flags (Blender)

### ISSUE THREAD

**Issue by ligazetom** [godotengine/godot#34841] opened 2020-01-05 17:40 UTC
**Godot version:3.2.beta**

**OS:**
Windows 10 Pro (Version: 1903, Build 18362.535) 

**Issue description:**
gltf importer ignoring "-colonly" flags (all of them)

**Steps to reproduce:**
Create scene in Blender. Name one of the object accordingly. Export .gltf:

**Minimal reproduction project:**
Really no reason.

I've been playing around with export/import pipeline (From armature, animation, shape keys, everything except UV's) and Shape Keys were screwed in 3.1.2 so I tried 3.2 build. There everything works except collision creation.

The thing is, _fix_node method [define here](https://github.com/godotengine/godot/blob/master/editor/import/resource_importer_scene.cpp) which returns pointer to a **Node** creates it just allright.

This is my Blender Setup:
![image](https://user-images.githubusercontent.com/11858829/71783652-2b16f900-2fea-11ea-8cd1-cdecf949d2f8.png)

And this is what I get after import in Godot:
![image](https://user-images.githubusercontent.com/11858829/71783662-471a9a80-2fea-11ea-8920-e2df93df2a0a.png)

As I mentiond, the problem is not in _fix_node method. I iterated over the scene nad printed names of the children and got this:
![image](https://user-images.githubusercontent.com/11858829/71783673-7fba7400-2fea-11ea-9672-af641f133b18.png)

(I did not think it through much, thats why last line does not make sense :D), anyway, the shape is there. I however really do not understand much more than that, since today was my first day looking into the source and most of it I spent by setting up VS Code to be able to debug. If anyone has any ideas, where to look, I can try to work it out myself.

**Comment by Calinou** [comment] 2020-01-05 17:54
I see `-convcolonly` on your screenshot, it's not the same thing as `-colonly` :slightly_smiling_face:

Are both failing, or just `-convcolonly`?

**Comment by ligazetom** [comment] 2020-01-05 17:56
Yes, I thought by saying "flags" it was somehow implicit, sorry. I tried both -colonly and -convcolonly.

However, as I said, it does not have anything to do with this flag. Problem must be somewhere later.

**Comment by ligazetom** [comment] 2020-01-07 08:16
Flags work with .escn and .dae formats. However, they have other issues.

**Comment by fire** [comment] 2020-01-09 20:16
See also https://github.com/godotengine/godot/issues/32363

**Comment by fire** [comment] 2020-01-09 20:29
I'll close this issue as a duplicate of https://github.com/godotengine/godot/issues/32363.

**Closed by fire** 2020-01-09 20:29 UTC
Labels: bug, topic:import

**Comment by ligazetom** [comment] 2020-01-09 20:52
I mean, he said it did not work on empties. This just does not work at all, not mentioning I've already started debugging the issue.

**Comment by jeffres** [comment] 2020-01-09 21:05
Hi,

@fire: I'm indeed not sure this is a duplicate of #32363, which only relates to Blender `empty` objects.

In @ligazetom example, `Collision-covcolonly` seems to be a mesh.

But AFAIK the issue with import hints on meshes was fixed by #32343 and I've been using them in my project since then without any problem. My current build is from Christmas (22782d519c2), so maybe a regression occurred in the meantime. I may have to update to be sure.

@ligazetom: With that said, a minimal reproduction project could be useful nonetheless.

**Comment by fire** [comment] 2020-01-09 21:53
I'm using https://github.com/godotengine/godot/issues/32678 as an overarching issue to track any of the importer not respecting https://docs.godotengine.org/en/latest/getting_started/workflow/assets/importing_scenes.html#animation-loop-loop-cycle 

* Create navigation (-navmesh)
* Create a VehicleBody (-vehicle)
* Create a VehicleWheel (-wheel)
* Rigid Body (-rigid)
* Animation loop (-loop, -cycle)

**Comment by fire** [comment] 2020-01-09 21:58
Please track https://github.com/godotengine/godot/issues/34066 for the empties bug.

**Comment by fire** [comment] 2020-01-10 16:15
@ligazetom 

"Collision-covcolonly" is the wrong suffix.

The docs say https://docs.godotengine.org/en/latest/getting_started/workflow/assets/importing_scenes.html#import-hints Option “-convcolonly” will create a ConvexPolygonShape instead of a ConcavePolygonShape.

You typed "-covcolonly".

**Comment by jeffres** [comment] 2020-01-10 17:39
Oh, my mistake, I got it wrong in my comment but it was indeed "-convcolonly" in @ligazetom's screenshot.

**Comment by fire** [comment] 2020-01-10 23:03
https://github.com/godotengine/godot/pull/34994 https://github.com/godotengine/godot/pull/34997 bugfixes.

**Comment by ligazetom** [comment] 2020-01-11 08:18
I've checked changes in those commits. How exactly those lines helped with these flags? :D All I see is one changed boolean and "cycle" "loop".

**Comment by fire** [comment] 2020-01-11 08:57
Oh it was already fixed by a previous patch, take a look at the blender sample.
