### ISSUE TITLE
[Godot 4.2] Godot crash after adjusting value of `ProgressBar` through dragging

### ISSUE THREAD

**Issue by RechieKho** [godotengine/godot#80465] opened 2023-08-10 00:46 UTC
### Godot version

Godot Engine v4.2.dev.custom_build

### System information

Arch Linux, AMD ATI Radeon Vega Series / Radeon Vega Mobile Series, CPU: AMD Ryzen 3 3200G (4) @ 3.600GHz

### Issue description

Godot crash after release dragging that adjust `value` property of `ProgressBar`

Here is the backtrace:
```
================================================================
handle_crash: Program crashed with signal 4
Engine version: Godot Engine v4.2.dev.custom_build (40bdd3c504ccdd42b5ab321af626b0a737f12afb)
Dumping the backtrace. Please include this when reporting the bug to the project developer.
[1] /usr/lib/libc.so.6(+0x3e710) [0x7fd48843e710] (??:0)
[2] Window::_event_callback(DisplayServer::WindowEvent) (/home/rechie/Documents/cxx_projects/gobread/scene/main/window.cpp:675)
[3] void call_with_variant_args_helper<Window, DisplayServer::WindowEvent, 0ul>(Window*, void (Window::*)(DisplayServer::WindowEvent), Variant const**, Callable::CallError&, IndexSequence<0ul>) (/home/rechie/Documents/cxx_projects/gobread/./core/variant/binder_common.h:308)
[4] void call_with_variant_args<Window, DisplayServer::WindowEvent>(Window*, void (Window::*)(DisplayServer::WindowEvent), Variant const**, int, Callable::CallError&) (/home/rechie/Documents/cxx_projects/gobread/./core/variant/binder_common.h:418)
[5] CallableCustomMethodPointer<Window, DisplayServer::WindowEvent>::call(Variant const**, int, Variant&, Callable::CallError&) const (/home/rechie/Documents/cxx_projects/gobread/./core/object/callable_method_pointer.h:?)
[6] Callable::callp(Variant const**, int, Variant&, Callable::CallError&) const (/home/rechie/Documents/cxx_projects/gobread/core/variant/callable.cpp:51)
[7] DisplayServerX11::_send_window_event(DisplayServerX11::WindowData const&, DisplayServer::WindowEvent) (/home/rechie/Documents/cxx_projects/gobread/platform/linuxbsd/x11/display_server_x11.cpp:3771)
[8] DisplayServerX11::mouse_set_mode(DisplayServer::MouseMode) (/home/rechie/Documents/cxx_projects/gobread/platform/linuxbsd/x11/display_server_x11.cpp:383)
[9] DisplayServer::_input_set_mouse_mode(Input::MouseMode) (/home/rechie/Documents/cxx_projects/gobread/servers/display_server.cpp:944)
[10] Input::set_mouse_mode(Input::MouseMode) (/home/rechie/Documents/cxx_projects/gobread/core/input/input.cpp:90)
[11] EditorSpinSlider::gui_input(Ref<InputEvent> const&) (/home/rechie/Documents/cxx_projects/gobread/editor/gui/editor_spin_slider.cpp:81)
[12] Control::_call_gui_input(Ref<InputEvent> const&) (/home/rechie/Documents/cxx_projects/gobread/scene/gui/control.cpp:?)
[13] Viewport::_gui_call_input(Control*, Ref<InputEvent> const&) (/home/rechie/Documents/cxx_projects/gobread/scene/main/viewport.cpp:1562)
[14] Viewport::_gui_input_event(Ref<InputEvent>) (/home/rechie/Documents/cxx_projects/gobread/scene/main/viewport.cpp:1831)
[15] Viewport::push_input(Ref<InputEvent> const&, bool) (/home/rechie/Documents/cxx_projects/gobread/scene/main/viewport.cpp:3128)
[16] Window::_window_input(Ref<InputEvent> const&) (/home/rechie/Documents/cxx_projects/gobread/scene/main/window.cpp:?)
[17] void call_with_variant_args_helper<Window, Ref<InputEvent> const&, 0ul>(Window*, void (Window::*)(Ref<InputEvent> const&), Variant const**, Callable::CallError&, IndexSequence<0ul>) (/home/rechie/Documents/cxx_projects/gobread/./core/variant/binder_common.h:303)
[18] void call_with_variant_args<Window, Ref<InputEvent> const&>(Window*, void (Window::*)(Ref<InputEvent> const&), Variant const**, int, Callable::CallError&) (/home/rechie/Documents/cxx_projects/gobread/./core/variant/binder_common.h:418)
[19] CallableCustomMethodPointer<Window, Ref<InputEvent> const&>::call(Variant const**, int, Variant&, Callable::CallError&) const (/home/rechie/Documents/cxx_projects/gobread/./core/object/callable_method_pointer.h:?)
[20] Callable::callp(Variant const**, int, Variant&, Callable::CallError&) const (/home/rechie/Documents/cxx_projects/gobread/core/variant/callable.cpp:51)
[21] DisplayServerX11::_dispatch_input_event(Ref<InputEvent> const&) (/home/rechie/Documents/cxx_projects/gobread/platform/linuxbsd/x11/display_server_x11.cpp:3751)
[22] DisplayServerX11::_dispatch_input_events(Ref<InputEvent> const&) (/home/rechie/Documents/cxx_projects/gobread/platform/linuxbsd/x11/display_server_x11.cpp:3723)
[23] Input::_parse_input_event_impl(Ref<InputEvent> const&, bool) (/home/rechie/Documents/cxx_projects/gobread/core/input/input.cpp:721)
[24] Input::flush_buffered_events() (/home/rechie/Documents/cxx_projects/gobread/core/input/input.cpp:979)
[25] DisplayServerX11::process_events() (/home/rechie/Documents/cxx_projects/gobread/platform/linuxbsd/x11/display_server_x11.cpp:4819)
[26] OS_LinuxBSD::run() (/home/rechie/Documents/cxx_projects/gobread/platform/linuxbsd/os_linuxbsd.cpp:908)
[27] /home/rechie/Documents/cxx_projects/gobread/bin/godot.linuxbsd.editor.dev.x86_64.llvm(main+0x22b) [0x55ccc6dcaf8b] (/home/rechie/Documents/cxx_projects/gobread/platform/linuxbsd/godot_linuxbsd.cpp:74)
[28] /usr/lib/libc.so.6(+0x27cd0) [0x7fd488427cd0] (??:0)
[29] /usr/lib/libc.so.6(__libc_start_main+0x8a) [0x7fd488427d8a] (??:0)
[30] /home/rechie/Documents/cxx_projects/gobread/bin/godot.linuxbsd.editor.dev.x86_64.llvm(_start+0x25) [0x55ccc6dcac85] (??:?)
-- END OF BACKTRACE --
================================================================
```

### Steps to reproduce

1. Create a `ProgressBar`
2. Adjust the `value` property of `ProgressBar` by (violently?) dragging it.
3. Release mouse button click to release dragging
4. Godot crash

### Minimal reproduction project

N/A

**Comment by Sauermann** [comment] 2023-08-10 00:51
Please update to current master. This has already been fixed in #80187 / #80279.
Closing as duplicate of #80335 (same cause)

**Closed by Sauermann** 2023-08-10 00:51 UTC
