### ISSUE TITLE
Manually set quaternion rotation values on skeleton animations do not work and throw error

### ISSUE THREAD

**Issue by stryker313** [godotengine/godot#60023] opened 2022-04-08 12:09 UTC
### Godot version

4.0 Alpha 6

### System information

Windows 10 Nvidia GTX 1060 Intel i5 4690k

### Issue description

Relevant : #55864
Animations with quaternion rotation tracks will work in Godot. However, if you manually set a rotation value in a rotation track,

`  The start quaternion must be normalized.
`

As a result, the rotation track does not work for the values you have added
![Desktop Screenshot 2022 04 08 - 08 06 00 44](https://user-images.githubusercontent.com/83078010/162432280-1cfa8afb-9ffb-4195-a064-709ca4b999c3.png)

In the sample project, you can open the test.tscn and play the animation and see the error.

The fix for #55864 allows quaternion values to be entered and saved into rotation tracks, however the rotation tracks once edited can no longer be, I guess "used".

### Steps to reproduce

1. Have any godot animation on a skeleton WITH a rotation track. (OR you can edit any existing rotation track keyframe)
2. Insert a keyframe in the rotation track in a spot that has no keyframes
3. Click on the keyframe
4. Manually update the keyframe in the inspector(Pick a random value, ex. (0,0,0,1) ==> (.2,.3,.1,1)
5. Save
6. Either play the animation, or go through the animation in the animation player
The console will be flooded with the errors as long as it plays

### Minimal reproduction project

[Testt.zip](https://github.com/godotengine/godot/files/8451643/Testt.zip)

**Comment by Calinou** [comment] 2022-04-08 15:57
cc @TokageItLab

**Comment by TokageItLab** [comment] 2022-04-08 18:08
Dupe of #39229. This is a usability issue, not a bug. reduz plans to implement a GUI for quaternions, as mentions in #39229.

**Closed by TokageItLab** 2022-04-08 18:08 UTC
Labels: bug, topic:animation
