### ISSUE TITLE
Raycast stops responding when dealing with parallel collisions

### ISSUE THREAD

**Issue by Einlander** [godotengine/godot#3900] opened 2016-03-02 15:04 UTC
**Operating system or device:**
Windows 7 Pro

**Issue description** (what happened, and what was expected):
The 3d raycast stops responding/functioning when it hits a flat surface from the side.

In my project I use a raycast for the legs. When I attempt to walk over an object with sides parallel to the raycast, the raycast stops responding and I fly off into the sky.

**Steps to reproduce:**
Load project. Try to walk onto the ramp from the side.

**Link to minimal example project** (optional but very welcome):
[project.zip](https://github.com/godotengine/godot/files/155019/project.zip)

**Comment by kubecz3k** [comment] 2016-03-04 11:05
Spent last 30 minutes on trying to debug this project. Unfortunately I don't think this is good sample to demonstrate the issue, while the issue is easy to notice I'm not so sure it's Godot fault. I'm very sorry but, there is quite a lot of logic like for a minimal sample demo, and a lot of things is created and set up manually from inside the code, which make the project little harder to debug (at least for me). 
For example @Einlander  did you know that your kinematic body origin position is always outside and below it's own collision shape?  
In the end I decided it will be a lot faster for me to test the issue on my own proper "minimal issue demo", so I created new project. In the end it turns out I'm unable to reproduce the bug in it (ray hitting flat parallel surface from the side is working fine).
@Einlander if you want you can try to simplify your own sample, or modify my one so we could reproduce/understand the issue nearer of it's core.

**Comment by kubecz3k** [comment] 2016-03-04 11:06
Spent last 30 minutes on trying to debug this project. Unfortunately I don't think this is good sample to demonstrate the issue, while the issue is easy to notice I'm not so sure it's Godot fault. I'm very sorry but, there is quite a lot of logic like for a minimal sample demo, and a lot of things is created and set up manually from inside the code, which make the project little harder to debug (at least for me).
For example @Einlander did you know that your kinematic body origin position is always outside and below it's own collision shape?

In the end I decided it will be a lot faster for me to test the issue on my own proper "minimal issue demo", so I created new project. In the end it turns out I'm unable to reproduce the bug in it (ray hitting flat parallel surface from the side is working fine).
@Einlander if you want you can try to simplify your own sample, or modify my one so we could reproduce/understand the issue nearer of it's core.

Here is my demo: [raycast 3d paraller collision.zip](https://github.com/godotengine/godot/files/158554/raycast.3d.paraller.collision.zip)

**Comment by reduz** [comment] 2016-06-24 14:29
I just can't understand the issue..

**Comment by kubecz3k** [comment] 2016-06-24 15:11
@reduz I think there was no real issue in the end, just bad scene setup. Also think it's save to close this, especially since original author never responded to my messages.

**Closed by kubecz3k** 2016-06-24 15:11 UTC
Labels: archived, bug, topic:core
