### ISSUE TITLE
Godot 4: export variable in Visual Script can't be turned off once turned on

### ISSUE THREAD

**Issue by kreaninw** [godotengine/godot#58072] opened 2022-02-13 23:21 UTC
### Godot version

v4.0.alpha2.official [79077e6c1]

### System information

Windows 11, Vulkan Clustered, Intel UHD Graphics 620 v30.0.101.1340

### Issue description

An export variable in Visual Script can't be turned off once turned on, as shown in the screen recording below:

https://user-images.githubusercontent.com/1403194/153779664-6c829498-1ff3-4ef0-9675-ca4ac52c602b.mp4

This is a regression from Godot 3.4, as shown in the screen recording below:

https://user-images.githubusercontent.com/1403194/153779715-3ad2f7be-42a4-4f09-bccb-164405c71ac3.mp4

I expect the export variable to work as it should be.

### Steps to reproduce

1. Add a variable in Visual Script.
2. Make it an export variable.
3. Turn the export off. You won't be able to turn it off.

**Comment by Calinou** [comment] 2022-02-13 23:26
cc @Gallilus

**Comment by fire** [comment] 2022-02-14 13:51
I'll see if I can make a board to tracking Visual Script issues.

**Comment by Gallilus** [comment] 2022-04-02 07:57
@kreaninw Is this issue still active?

**Comment by kreaninw** [comment] 2022-04-02 17:58
> @kreaninw Is this issue still active?

Yes, as of Godot v4.0.alpha5.official [d7d528c15], as shown in the screen recording below:

https://user-images.githubusercontent.com/1403194/161395447-4d280ac0-e71b-4568-b571-2d5e4f156ad6.mp4

**Comment by Gallilus** [comment] 2022-04-02 20:01
O the toggle work? Then I think it is the same as #58158

**Comment by kreaninw** [comment] 2022-04-02 22:36
> O the toggle work? Then I think it is the same as #58158

Yes, the toggle works as expected but it has no effect in the inspector tab.

**Comment by KoBeWi** [comment] 2022-05-06 13:12
Closing as duplicate of #58158 (the variable is exported even if you don't tick the checkbox)

**Closed by KoBeWi** 2022-05-06 13:12 UTC
Labels: bug, topic:editor, topic:visualscript
