### ISSUE TITLE
Godot 4 Migration: Converting Paths

### ISSUE THREAD

**Issue by rakkarage** [godotengine/godot#67349] opened 2022-10-13 14:56 UTC
### Godot version

v4.0.beta2.official [f8745f2f7]

### System information

Windows 11

### Issue description

    [ext_resource path="res://PixelEffect/Path.png" type="Texture" id=1]

the migration process converts this string which represents a path?

    [ext_resource path="res://PixelEffect/Path3D.png" type="Texture2D" id=1]

I guess cuz called path? I am not sure how this is done yet but maybe there is a way to prevent this? Only convert type not path? Or...

Thanks.

### Steps to reproduce

1. open project in 4
2. convert
3. error

### Minimal reproduction project

https://github.com/rakkarage/PixelEffect

**Comment by Zireael07** [comment] 2022-10-13 15:15
This is because the converter only does a regex.

Duplicate of https://github.com/godotengine/godot/issues/66061. https://github.com/godotengine/godot/pull/66150 will fix

**Comment by KoBeWi** [comment] 2022-10-13 17:25
Closing per above comment.

**Closed by KoBeWi** 2022-10-13 17:25 UTC

**Comment by gotnospirit** [comment] 2022-10-14 04:36
At the moment, this particular project will still be broken, because my PR doesn't deal with "tres" files.
I will make an update for this
