### ISSUE TITLE
[GDScript 2.0] Calling `.append_array` over TypedArrays causes error

### ISSUE THREAD

**Issue by nonunknown** [godotengine/godot#57008] opened 2022-01-20 17:42 UTC
### Godot version

v4.0.dev.custom_build [eacde082a]

### System information

manjaro KDE

### Issue description

When you are working with typed arrays and call `.append_array()` it expects an array, and not the typed array of the declared type, something like: `Array[int]`

### Working example:
```gdscript
var arr:Array = []

func _ready() -> void:
	arr.append_array([1,2,3,4,5,6])
	print(arr)
	for i in range(10):
		print("Result: ", arr[randi() % arr.size()])
```

**output**:
```
 
[1, 2, 3, 4, 5, 6]
Result: 4
Result: 2
Result: 1
Result: 2
Result: 3
Result: 4
Result: 6
Result: 2
Result: 5
Result: 6

```

### Not working example (FREEZE)

```gdscript
var arr:Array[int] = []

func _ready() -> void:
	arr.append_array([1,2,3,4,5,6])
	print(arr)
	for i in range(10):
		print("Result: ", arr[randi() % arr.size()])
```
 NO OUTPUT, BECAUSE IT FREEZES

in a test with PR #57007 an output is provided :

```gdscript

func _ready() -> void:
	arr.append_array([1,2,3,4,5,6])
	print(arr)
	for i in range(10):
		print("Result: ", arr.pick_random())
```
 
**output:**
```
[]
Result: null
Result: null
Result: null
Result: null
Result: null
Result: null
Result: null
Result: null
Result: null
Result: null
```

### Steps to reproduce

Described above

### Minimal reproduction project

N/a

**Comment by cdemirer** [comment] 2022-01-24 20:23
Kind of a duplicate of: #54939

**Closed** 2022-01-24 20:34 UTC
Labels: bug, topic:core, topic:gdscript
