### ISSUE TITLE
Can't rename a file/folder when only changing its case on a case insensitive filesystem (Windows, macOS)

### ISSUE THREAD

**Issue by justinluk** [godotengine/godot#19592] opened 2018-06-16 00:55 UTC
___

***Bugsquad note:** This issue has been confirmed several times already. No need to confirm it further.*

___

**Godot version:**
3.0.3-stable

**OS/device including version:**
Windows 10

**Issue description:**
I was renaming a folder called 'UI' to 'ui' and received a message saying "Error moving: res://ui/". There used to be a similar issue in 3.0

**Steps to reproduce:**
Create a folder called "UI" and try to rename it to "ui".

**Comment by akien-mga** [comment] 2018-06-16 07:32
That's a limitation of Windows, most tools on Windows (including explorer.exe) won't let you rename a folder or file to only change the case (Windows doesn't care about case).

So you'd have to rename it to something else like "UI_" before renaming it to "ui".

Maybe the error message can be improved though.

**Comment by bruvzg** [comment] 2018-06-16 09:38
> Windows doesn't care about case

Starting with Redstone 4 (April 2018 update) Windows 10 should support case-sensitive file system mode, you can enable it on per directory basis using following command:

`fsutil file setcasesensitiveinfo <directory_path> enable`

**Comment by Zireael07** [comment] 2018-06-16 09:45
@bruvzg: Not everyone is on Win10, y'know...

**Comment by akien-mga** [comment] 2018-06-16 10:04
> Starting with Redstone 4 (April 2018 update) Windows 10 should support case-sensitive file system mode, you can enable it on per directory basis using following command:
> 
> `fsutil file setcasesensitiveinfo <directory_path> enable`

That might be interesting to put in the Godot docs (e.g. http://docs.godotengine.org/en/latest/getting_started/workflow/project_setup/project_organization.html ) so that Windows 10 users know about it. Since Godot cares about case, it would be a good practice to use that option for Godot project folders on Windows.

**Comment by hpvb** [comment] 2018-06-16 11:53
I thought I fixed this in master some time ago... Did I forget to cherry pick my own fix? I'll check.

**Comment by KellyThomas** [comment] 2018-06-16 14:20
>So you'd have to rename it to something else like "UI_" before renaming it to "ui".

This sounds like a workaround that could be automated?

**Comment by vnen** [comment] 2018-06-16 18:06
Wasn't this fixed by #15959? It's closed but it was manually merged.

**Comment by akien-mga** [comment] 2018-06-16 18:21
> Wasn't this fixed by #15959? It's closed but it was manually merged.

That commit made it to 3.0.3-stable at any rate, so it seems not to be enough: 000caef6

**Comment by justinluk** [comment] 2018-06-16 19:49
I recall this issue was fixed for a bit but as mentioned is no longer working.

**Comment by UgisBrekis** [comment] 2018-06-19 15:50
It's also present on OSX High Sierra

**Comment by justinluk** [comment] 2018-06-19 15:55
@UgisBrekis sounds like we've got a regression on our hands.

**Comment by bruvzg** [comment] 2018-06-19 15:59
> It's also present on OSX High Sierra

macOS can use both case sensitive and case insensitive HFS+/APFS filesystems, renaming doesn't work on case insensitive volumes and works on case sensitive (tested with master 0a1c1c660). By default system volume is case insensitive.

**Comment by aegent** [comment] 2018-08-14 13:04
Windows 10: I just renamed the folder with an additional space, then go back and take the space out.
Not a big deal. Annoying, but not a big deal.

**Comment by Halogen32** [comment] 2019-05-04 21:26
Renaming a folder's name to a new case is still an issue in Windows 10, as of Godot v3.1.1.stable.official. There are 2 ways to work around this.

1. As mentioned previously, rename the folder in Godot to a new name and then rename back to the previous name under a new case. (ex. "Folder" -> "sprite_folder" -> "folder")
2. As of this date, you can open File Explorer and rename the folder's name case without visible errors.

In both cases, Godot will reimport your assets in the renamed folder(s).

**Comment by Calinou** [comment] 2020-01-23 04:25
According to #35457, this issue may not be limited to Windows. It probably happens on any OS with a case-insensitive filesystem.

**Comment by justinluk** [comment] 2020-01-23 05:18
I can confirm this issue is happening on Windows 10 Version 1909, Godot 3.2-rc2.

**Comment by MaaaxiKing** [comment] 2020-05-14 18:02
Why doesn't this have the bug label?

**Comment by AnJ95** [comment] 2020-08-25 16:48
Not just folders, it's also scripts, scenes, resources.

**Comment by wyattbiker** [comment] 2022-08-25 19:03
On the Mac the behavior of file_exists() is return true whether it is upper or lower cased. But the rename will perform the case flip rename from one to the other. Interesting.

Here is gdscript code for that:
```python
func _ready() -> void:
	var file:File=File.new()
	var dir:Directory = Directory.new()
	
	# Create lower case file if not present
	if !dir.file_exists("res://test.gd"):
		file.open("res://test.gd", File.WRITE)
		file.store_string("contentsomething")
		file.close()
	
	#Rename to upper case
	var err=dir.rename("res://test.gd","res://TEST.gd")
	print(err)
	print("File exists: ",dir.file_exists("res://test.gd"))
	print("File exists: ",dir.file_exists("res://TEST.gd"))
	pass # Replace with function body.
```

**Comment by tbergeron** [comment] 2022-08-28 10:51
This is still happening on latest Mac versions, how should we work around this and why isn't this fixed already? Sounds like a simple issue for a problem that's been reported almost 5 years ago 🤷

**Comment by Calinou** [comment] 2022-08-28 14:35
> This is still happening on latest Mac versions, how should we work around this and why isn't this fixed already? Sounds like a simple issue for a problem that's been reported almost 5 years ago shrug

Contributors fix issues on a best-effort basis, so it can take a while for seemingly simple issues to be resolved if there's not much interest from contributors.

Working around this is easy. For example, if you want to rename `ABC.tscn` to `abc.tscn`:

1. Rename `ABC.tscn` to `abc.tscn_`
2. Rename `abc.tscn_` to `abc.tscn`.

This gives you some hints as to implementing this in the engine code in C++ :slightly_smiling_face:

**Comment by coppolaemilio** [comment] 2022-09-19 11:44
Ran into this one today. Not sure if I can fix it myself but would love to see it fixed 😅

**Comment by luislodosm** [comment] 2022-09-22 20:47
<img width="267" alt="Captura de Pantalla 2022-09-22 a las 21 44 14" src="https://user-images.githubusercontent.com/63356898/191847493-13f9525a-7607-4b7c-a368-88325abf1f82.png">
<img width="266" alt="Captura de Pantalla 2022-09-22 a las 21 45 17" src="https://user-images.githubusercontent.com/63356898/191847612-da3ac7b7-3146-472a-8f1b-af56c712c57f.png">
<img width="324" alt="Captura de Pantalla 2022-09-22 a las 21 44 27" src="https://user-images.githubusercontent.com/63356898/191847512-1f9e61ff-38bb-4587-978e-f29a3d661668.png">
MacOS 12.6

Godot 4.0.beta1 also in Godot 3.5

**Comment by Calinou** [comment] 2022-09-22 21:31
> macOS 12.6
> Godot 4.0.beta1 / Godot 3.5

Recent macOS versions default to a case-insensitive filesystem, so this is expected.

**Closed** 2023-10-13 10:57 UTC
Labels: bug, platform:windows, platform:macos, topic:editor, confirmed, usability

**Comment by SirisX** [comment] 2024-08-01 04:30
Still happens in Godot 4.2.2 using Windows 10.. it's not an error of Windows 10, it's 100% Godot's fault.

**Comment by Calinou** [comment] 2024-08-01 23:29
@SirisX I can't reproduce this on 4.3.rc 3978628c6 on Windows 11 23H2 (on a case-insensitive NTFS filesystem):

https://github.com/user-attachments/assets/46b25dac-dd8a-493f-9916-7138666cd603

What antivirus program do you use? Can you reproduce this on [4.3.rc2](https://godotengine.org/article/release-candidate-godot-4-3-rc-2/)?

**Comment by SirisX** [comment] 2024-08-02 00:11
It was happening to a folder and script within the folder that was defining a class of the same name. I got around it by renaming it to something else entirely.. it may also be a github issue.
