### ISSUE TITLE
3.0 - Scroll container has a display error

### ISSUE THREAD

**Issue by sersoong** [godotengine/godot#12834] opened 2017-11-11 05:35 UTC
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
windows7 x64 godot3.0

**Issue description:**

see image below:
![capture2](https://user-images.githubusercontent.com/24988459/32686696-1e97a7b2-c6e5-11e7-9de4-8f41034f7567.png)
![capture3](https://user-images.githubusercontent.com/24988459/32686697-1ed40126-c6e5-11e7-89f6-829630a4519f.png)

**Steps to reproduce:**
open editor ,
click help menu -> about,
click developer list,
drag scroll bar,
you can see some interest issue.

**Link to minimal example project:**

**Comment by Noshyaar** [comment] 2017-11-11 06:06
Duplicate of #9612

**Closed by Noshyaar** 2017-11-11 06:06 UTC
