### ISSUE TITLE
ERROR: All memory pool allocations are in use.  at: (./core/pool_vector.h:512)

### ISSUE THREAD

**Issue by acgc99** [godotengine/godot#59539] opened 2022-03-26 09:22 UTC
### Godot version

v3.4.stable.official.206ba70f4

### System information

Windows 11. NVIDIA GeForce GTX 1050/PCIe/SSE2

### Issue description

Hi,
I do not have a deep knowledge about the code inside Godot, I'm not sure if I should report this issue here (I also asked in the [Godot Forum](https://godotengine.org/qa/130968/error-all-memory-pool-allocations-are-godot-seems-many-memory)).

So I'm trying to make a voxel based game. Here is an example of a radius 7 "circle":

![l](https://user-images.githubusercontent.com/96864661/160232571-11594719-ecb6-4eff-bd06-e14f70ad1ce5.jpg)

The first algorithm I made returned an `Array` with all the `Vector3` for the voxels translations. I recieved an error when the radius was too big (around 100, 40401 voxels):
```
ERROR: All memory pool allocations are in use.
   at: (./core/pool_vector.h:512)
```
So I thought that the `Array` was too big, so I decided to make some kind of "generator/iterator" so I do not have to save all the `Vector3`. But the problem persists. The project I share contains the new algorithm. Note that the are not overlaped voxels.

A radius 73 (10805 voxels) is allowed, but not for 74. If I remove the `MeshInstance` of the voxels, the limit is bigger. I put here some info in the 73 case:
![kk](https://user-images.githubusercontent.com/96864661/160232782-525fe530-5439-4eb6-92db-65df83886d16.jpg)
![lll](https://user-images.githubusercontent.com/96864661/160232797-91616d63-0d18-4c80-ae0b-0c18367fef61.jpg)

So Godot is not using too much memory.

### Steps to reproduce

Run the code attached.  `r` and `R` at `GameManager` set the inner and outer radius of the "circle". I added a player node so you can move using WASD. Using TAB you can iterate through different movement modes (mouse, keyboard). Add as many voxels as you want.

### Minimal reproduction project

[minumum.zip](https://github.com/godotengine/godot/files/8355063/minumum.zip)

**Comment by lawnjelly** [comment] 2022-03-26 09:54
See #37154 which appears the master issue.
Also see #59444 and linked issues.

**Comment by akien-mga** [comment] 2023-02-26 22:17
Duplicate of #37154

**Closed by akien-mga** 2023-02-26 22:17 UTC
Labels: discussion, topic:core
