### ISSUE TITLE
Rough edges on 2d

### ISSUE THREAD

**Issue by michaldev** [godotengine/godot#57802] opened 2022-02-08 12:50 UTC
### Godot version

3.4.2

### System information

Web browser on Android and Ios, Linux and MacOS - and native on linux.

### Issue description

Hi. Why my game looks bad? I mean that jagged edges. Most on circles (texture) and drawed line 2d (by Line2D without texture), less but still on font.
What settings should I pay attention to? I have already tested everything in "Rendering -> quality"

Game url: [https://michaldev.github.io/godotstate/index.html](https://michaldev.github.io/godotstate/index.html)

I asked on fb group and discord - but without results .

![273006190_3026384537493872_7262071164433619354_n](https://user-images.githubusercontent.com/5132385/152990351-f40f895c-1b2c-4021-9ddd-1a2a362b359d.jpg)
![273433682_3026384550827204_1790073387156125339_n](https://user-images.githubusercontent.com/5132385/152990355-0174b5b7-133e-4f5a-a3f8-9ee6b1294a7a.jpg)

![273440391_3026445754154417_538735417006686009_n](https://user-images.githubusercontent.com/5132385/152990464-d7fbf905-b95c-4723-a7da-3e1f8ec452cb.jpg)
![273360943_3026445887487737_4462029021378442516_n](https://user-images.githubusercontent.com/5132385/152990468-b11674ca-966c-41b2-b88d-f75fcf902bd3.jpg)
![273008231_3026388364160156_4029920521548233991_n](https://user-images.githubusercontent.com/5132385/152990470-210d9016-0ecb-42ea-80d4-2ef20d014ab1.jpg)

### Steps to reproduce

Just add any image or add line by Line2D.

**Comment by groud** [comment] 2022-02-08 13:59
Duplicate of https://github.com/godotengine/godot/issues/38872.

**Comment by michaldev** [comment] 2022-02-08 14:43
Drawing a straight 2d line is one of the basic functions of the engine. I can't find a solution to my problem anywhere and my thread has been closed.

This work very well on unity and defold.

**Comment by groud** [comment] 2022-02-08 23:02
If you are using a texture for the cirlces, then you need to fix the rough edges in the texture itself. Unless I misunderstood and you likely draw your circles with `Canvasitem.draw_polygon`, in which case you should set the antialiased argument to `true`.

It's a similar thing for the Line2D node, which has an `antialiased` property you should set to `true`.

**Comment by michaldev** [comment] 2022-02-09 08:16
Setting anti-aliasing to true doesn't change anything. I noticed that the problem occurs on Linux (natively) and on every system and device in a browser (web).

The problem does not occur on macos. I have not tested on android and ios builds.

**Comment by groud** [comment] 2022-02-09 08:24
Ok, then the issue is likely different. An MRP would be welcome though.

**Comment by michaldev** [comment] 2022-02-09 08:26
Yes. It doesn't work.

![image](https://user-images.githubusercontent.com/5132385/153155378-2a7914a1-6371-496e-b913-816c3484666e.png)

**Comment by michaldev** [comment] 2022-02-09 12:15
Maybe this it the problem:
"Allow Hidpi is only effective on Windows and macOS. It's ignored on all other platforms."

On macos I had a problem with that too until i used hidpi.

**Comment by Calinou** [comment] 2022-02-09 14:46
**Allow Hidpi** is enabled by default in Godot 4.0, but this default setting change can't be backported to Godot 3.x to avoid breaking compatibility with existing projects.

**Closed** 2022-02-10 16:54 UTC
Labels: topic:rendering, topic:2d
