### ISSUE TITLE
Root nodes in scenes inconsistently have or lack an "index" property

### ISSUE THREAD

**Issue by aaronfranke** [godotengine/godot#20651] opened 2018-08-01 05:21 UTC
**Godot version:** Various 3.0.x versions, most recently, 3.0.6. All with Mono.

**OS/device including version:** Ubuntu 18.04 64-bit

**Issue description:** For some reason, the root node in my scenes seems to randomly have the `index="0"` property. Sometimes it is there, sometimes it is not there. It is really annoying especially for Git history, where I have commits constantly changing the file back and forth.

In one commit (this one created pre-3.0.6):

![1](https://user-images.githubusercontent.com/1646875/43502466-a66a16f2-9520-11e8-9fd1-92928d227e29.png)

And in another commit (this one made with 3.0.6):

![2](https://user-images.githubusercontent.com/1646875/43502468-a9482774-9520-11e8-9cf3-3122b463b883.png)

In both commits, this is the only line of the scene file that is changed. This doesn't break the project or anything, but it is quite annoying for users of version control software.

Please, either always include `index`, or always exclude it. I assume the former is better.

**Steps to reproduce:** I have no idea how to reproduce it. It seems fairly random.

**Comment by hilfazer** [comment] 2018-08-01 12:09
Same on Windows 7 Pro SP1 x64. No Mono.

And Godot's supposed to have

> Friendly filesystem usage that works great with version control systems like Git, Subversion, Mercurial, PlasticSCM, Perforce, you name it

:(

**Comment by bojidar-bg** [comment] 2018-08-01 12:38
It is possible that Godot wrote those useless indexes before 3.0.6, but stopped in 3.0.6.

Anyway, duplicate of #17562.

**Closed by bojidar-bg** 2018-08-01 12:38 UTC
