### ISSUE TITLE
Switching from external monitor to laptop monitor causes very, very small text

### ISSUE THREAD

**Issue by drmar** [godotengine/godot#37898] opened 2020-04-15 09:29 UTC
**Godot version:**
3.2.1

**OS/device including version:**
macOS Catalina 10.15.4 / MacBookPro11,1

**Issue description:**
I am running Godot on an external monitor at 1920x1080 resolution and it works fine:
![Screenshot 2020-04-15 at 12 23 45](https://user-images.githubusercontent.com/13488692/79321656-5c219680-7f14-11ea-8d79-943b4b36b638.png)

When I unplug my HDMI cable to continue work on my laptop's screen, at native resolution, the Godot window and all text is very, very small:
<img width="1280" alt="Screenshot 2020-04-15 at 12 24 07" src="https://user-images.githubusercontent.com/13488692/79321780-896e4480-7f14-11ea-907a-2a0e8ced1f54.png">

**Steps to reproduce:**
Run Godot on an external monitor then unplug the HDMI cable. At least this problem happens on MacBook Pro

**Minimal reproduction project:**
Not necessary.

**Comment by Calinou** [comment] 2020-04-15 09:48
Duplicate of #30880.

**Closed by Calinou** 2020-04-15 09:48 UTC
