### ISSUE TITLE
Viewport.set_input_as_handled() causes spurious _mouse_enter(), _mouse_exit() events

### ISSUE THREAD

**Issue by paulmiller** [godotengine/godot#68637] opened 2022-11-14 03:59 UTC
### Godot version

3.5.1.stable, 4.0.beta

### System information

Arch Linux

### Issue description

The attached Godot 3 project has a clickable sphere `Area` with `_input_event()` overridden to call `get_viewport().set_input_as_handled()`. Clicking on the `Area` causes `_input_event()` to be called, followed immediately by calls to `_mouse_exit()` and then `_mouse_enter()`, even though the mouse never left the `Area`.

If you replace `get_viewport().set_input_as_handled()` with `get_tree().set_input_as_handled()`, then `_mouse_exit()` and `_mouse_enter()` are not called.

Godot 4 doesn't have `get_tree().set_input_as_handled()`; it was removed in 8e6960a69e. `get_viewport().set_input_as_handled()` has the same bug in Godot 4.

### Steps to reproduce

run attached project, click the sphere, see spurious mouse exit/enter logged in the console

### Minimal reproduction project

[click-handler.zip](https://github.com/godotengine/godot/files/9999348/click-handler.zip)

**Comment by paulmiller** [comment] 2022-11-14 04:01
(I originally posed this in the form of a [question on r/godot](https://www.reddit.com/r/godot/comments/yuj70s/how_to_detect_clicked_object_while_also_detecting/), but on further thought I suspect it's actually a bug.)

**Comment by Sauermann** [comment] 2022-11-14 05:19
duplicate of #61924
will get fixed by #68019

**Closed** 2022-11-14 13:14 UTC

**Comment by paulmiller** [comment] 2022-11-14 22:03
Verified fix when cherry picked to beta 4. Thanks!
