### ISSUE TITLE
GLES2 and default environment (ProceduralSky) cause a crash on some hardware

### ISSUE THREAD

**Issue by arnoldochavez** [godotengine/godot#21551] opened 2018-08-29 00:04 UTC
**Godot version:**
v3.1.alpha

**OS/device including version:**
Windows 10
Intel HD Graphics - OpenGL ES 2.0

**Issue description:**
When I create a new project and edit it, the explorer freezes and then Godot closes.

**Steps to reproduce:**
Create a New Project and edit it.

**Workaround:**
Go to the project directory, open the file called _project.godot_ and remove this line:
```
[rendering]

environment/default_environment="res://default_env.tres"
```

**Comment by akien-mga** [comment] 2018-08-29 06:47
Can you run it from a terminal and paste the output (there should be error messages)?

**Comment by arnoldochavez** [comment] 2018-08-29 21:53
There it is
```
OpenGL debugging not supported!
OpenGL ES 2.0 Renderer: Intel(R) HD Graphics
Editing project: C:/Users/Usuario/Documents/GodotProjects/Crash (C:::Users::Usuario::Documents::GodotProjects::Crash)
OpenGL debugging not supported!
OpenGL ES 2.0 Renderer: Intel(R) HD Graphics
WARNING: _get: Property not found: _global_script_class_icons
     At: core/project_settings.cpp:194
```

**Comment by akien-mga** [comment] 2018-08-30 06:03
What version of Intel HD graphics do you have? Are you drivers up to date?

**Comment by Zimakili** [comment] 2018-08-31 20:09
@akien-mga  I can confirm that @arnoldochavez problem existed on an old testing laptop I have and his solution worked. The drivers are up to date according to Intel (Version: 15.22.58.2993)

**Comment by zarsystem** [comment] 2018-09-01 05:33
For my work office PCwith "Intel HD Graphics 4400" changing default environment to custom color solves the crash problem.

**Comment by arnoldochavez** [comment] 2018-09-04 03:10
Sorry for the late response @akien-mga, there are the specs:

Report Date:			        9/3/2018
Report Time[hr:mm:ss]:		21:8:45
Driver Version:			        8.15.10.2900
Operating System:		       (6.2.9200)
Default Language:		       English (United States)
DirectX* Version:		       10.1
Physical Memory:		       5941 MB
Minimum Graphics Memory:   32 MB
Maximum Graphics Memory:   1696 MB
Graphics Memory in Use:	        230 MB
Processor:			                Intel64 Family 6 Model 37 Stepping 5
Processor Speed:		        2667 MHz
Vendor ID:			        8086
Device ID:			                0046
Device Revision:		        02

**Comment by ferhand** [comment] 2018-09-05 21:13
HP Elitebook 2560p, core i5, 4Gb RAM, Graphic HD 3000

The same happened to me. The Godot 3.1 start fine, but the graphic card crash when try to start a new proyect or any proyect.

Now I solved comenting the line:

[rendering]
environment/default_environment="res://default_env.tres"

in the file called project.godot.

**Comment by williamd1k0** [comment] 2018-09-08 15:58
I think this issue is a duplicate of #20588, since it was opened after that.
There is also another duplicate: #21643

**Comment by 0nepixel** [comment] 2018-09-24 03:08
If you remove the environment/default_environment="res://default_env.tres" Godot 2D will work just fine, but Godot 3D will stop working currectly, the camera 3D will ignore the enviroment color/light etc, and shows only a black background (in the back of the sprites meshes etc), i find this very strange, because this never happended in Godot 2.1 :/, i tested this with a new compilation (mastre branch) of Godot 3.1
![image](https://user-images.githubusercontent.com/22958303/45936509-cae37b80-bf8d-11e8-999b-b59847dfc391.png)

**Comment by OFTekk** [comment] 2018-11-29 10:51
Exported android app freezes at splash screen (Samsung Galaxy J5 and J3) or white screen with some artifacts is shown (Nvidia Tegra K1 tablet). It seems to be related to ProceduralSky applied in environment (when custom color is used android app runs fine).  (#22656)

**Comment by akien-mga** [comment] 2018-12-02 20:01
From @AlexRixhardson in https://github.com/godotengine/godot/issues/24043#issuecomment-443313482

> Even though removing sky from the default environment doesn't help in my case, I found out that if I delete the default environment, and then create a new environment, everything still works. Adding sky to the brand new environment causes the game to start crashing again.
>
> So I guess removing sky from the default environment that is automatically added to the project still keeps something behind, and that causes the game to crash. Creating brand new environment without the sky however works.

**Comment by jimmyjonezz** [comment] 2018-12-04 10:58
Also in Samsung R528/ Intel G45. And YES, i know use old graphic card.

Create a New Project. Then rename as "-default_env.tres" in project folder. Open a New Project in Godot and again rename "default_env.tres".

And this:
![error](https://user-images.githubusercontent.com/3973191/49437235-11dec000-f7cc-11e8-9c0a-264a66c347bc.png)

**Comment by Zireael07** [comment] 2018-12-18 08:19
A ton of duplicates being reported, as well as, why do we load default_env.tres in 2D projects?

**Comment by reduz** [comment] 2018-12-18 16:03
This is probably fixed now, but just in case give it a test again..

**Comment by volzhs** [comment] 2018-12-18 17:36
with `default_env.tres` I could reproduce the crash at start with my iPhone 4s 100%.
but not anymore. :)

**Comment by Akira1San** [comment] 2019-01-06 18:18
I have a crash with the environment too.
v3.1.alpha 5
OS Win 7,  AMD Radeon hd 6370m

**Comment by arnoldochavez** [comment] 2019-01-12 00:02
Just downloaded the beta and I can confirm it now works fine!

**Comment by Zireael07** [comment] 2019-01-12 10:46
On Radeon 6630M (and Dell's official drivers), I am having this crash in beta 1.

**Comment by akien-mga** [comment] 2019-01-13 11:14
Reopening as it's still not fixed for some hardware.

**Comment by Zireael07** [comment] 2019-01-13 12:37
I will add that, unfortunately, it seems to depend not only on hardware, but also on drivers (for the last year or so, I ran unofficial drivers and did NOT have the issue, but now that I got the computer back from repairs with a new card, I am back to official Dell drivers and I do have the issue now)

**Comment by reduz** [comment] 2019-01-19 01:17
I tried this on a very old Sony Vaio with an hd 6370m and latest drivers (which are quite ancient) and it works fine both with GLES2 and GLES3. I honestly have no idea what else I can do.

**Comment by Vikram1323** [comment] 2019-01-26 10:18
All the things I mentioned in #24962 + When I run Godot 3.1 beta 2
I get this 
OpenGL ES 3.0 Renderer: ATI Mobility Radeon HD 4300 Series
ERROR: initialize: Condition ' status != 0x8CD5 ' is true. Continuing..:
   At: drivers/gles3/rasterizer_scene_gles3.cpp:4965
ERROR: initialize: Condition ' status != 0x8CD5 ' is true. Continuing..:
   At: drivers/gles3/rasterizer_scene_gles3.cpp:4965
ERROR: initialize: Condition ' status != 0x8CD5 ' is true. Continuing..:
   At: drivers/gles3/rasterizer_scene_gles3.cpp:4965
ERROR: initialize: Condition ' status != 0x8CD5 ' is true. Continuing..:
   At: drivers/gles3/rasterizer_scene_gles3.cpp:4965
ERROR: initialize: Condition ' status != 0x8CD5 ' is true. Continuing..:
   At: drivers/gles3/rasterizer_scene_gles3.cpp:4965
ERROR: initialize: Condition ' status != 0x8CD5 ' is true. Continuing..:
   At: drivers/gles3/rasterizer_scene_gles3.cpp:4965
ERROR: initialize: Condition ' status != 0x8CD5 ' is true. Continuing..:
   At: drivers/gles3/rasterizer_scene_gles3.cpp:4965
ERROR: initialize: Condition ' status != 0x8CD5 ' is true. Continuing..:
   At: drivers/gles3/rasterizer_scene_gles3.cpp:4965
ERROR: initialize: Condition ' status != 0x8CD5 ' is true. Continuing..:
   At: drivers/gles3/rasterizer_scene_gles3.cpp:4965
ERROR: initialize: Condition ' status != 0x8CD5 ' is true. Continuing..:
   At: drivers/gles3/rasterizer_scene_gles3.cpp:4965
ERROR: initialize: Condition ' status != 0x8CD5 ' is true. Continuing..:
   At: drivers/gles3/rasterizer_scene_gles3.cpp:4965
ERROR: initialize: Condition ' status != 0x8CD5 ' is true. Continuing..:
   At: drivers/gles3/rasterizer_scene_gles3.cpp:4965
ERROR: initialize: Condition ' status != 0x8CD5 ' is true. Continuing..:
   At: drivers/gles3/rasterizer_scene_gles3.cpp:4965
ERROR: initialize: Condition ' status != 0x8CD5 ' is true. Continuing..:
   At: drivers/gles3/rasterizer_scene_gles3.cpp:4965
ERROR: initialize: Condition ' status != 0x8CD5 ' is true. Continuing..:
   At: drivers/gles3/rasterizer_scene_gles3.cpp:4965
ERROR: initialize: Condition ' status != 0x8CD5 ' is true. Continuing..:
   At: drivers/gles3/rasterizer_scene_gles3.cpp:4965
ERROR: initialize: Condition ' status != 0x8CD5 ' is true. Continuing..:
   At: drivers/gles3/rasterizer_scene_gles3.cpp:4965
ERROR: initialize: Condition ' status != 0x8CD5 ' is true. Continuing..:
   At: drivers/gles3/rasterizer_scene_gles3.cpp:4965
ERROR: initialize: Condition ' status != 0x8CD5 ' is true. Continuing..:
   At: drivers/gles3/rasterizer_scene_gles3.cpp:4965
ERROR: initialize: Condition ' status != 0x8CD5 ' is true. Continuing..:
   At: drivers/gles3/rasterizer_scene_gles3.cpp:4965
ERROR: initialize: Condition ' status != 0x8CD5 ' is true. Continuing..:
   At: drivers/gles3/rasterizer_scene_gles3.cpp:4965
ERROR: initialize: Condition ' status != 0x8CD5 ' is true. Continuing..:
   At: drivers/gles3/rasterizer_scene_gles3.cpp:4965
ERROR: initialize: Condition ' status != 0x8CD5 ' is true. Continuing..:
   At: drivers/gles3/rasterizer_scene_gles3.cpp:4965
ERROR: initialize: Condition ' status != 0x8CD5 ' is true. Continuing..:
   At: drivers/gles3/rasterizer_scene_gles3.cpp:4965
ERROR: initialize: Condition ' status != 0x8CD5 ' is true. Continuing..:
   At: drivers/gles3/rasterizer_scene_gles3.cpp:4965
ERROR: initialize: Condition ' status != 0x8CD5 ' is true. Continuing..:
   At: drivers/gles3/rasterizer_scene_gles3.cpp:4965
ERROR: initialize: Condition ' status != 0x8CD5 ' is true. Continuing..:
   At: drivers/gles3/rasterizer_scene_gles3.cpp:4965
ERROR: initialize: Condition ' status != 0x8CD5 ' is true. Continuing..:
   At: drivers/gles3/rasterizer_scene_gles3.cpp:4965
ERROR: initialize: Condition ' status != 0x8CD5 ' is true. Continuing..:
   At: drivers/gles3/rasterizer_scene_gles3.cpp:4965
ERROR: initialize: Condition ' status != 0x8CD5 ' is true. Continuing..:
   At: drivers/gles3/rasterizer_scene_gles3.cpp:4965
ERROR: initialize: Directional shadow framebuffer status invalid
   At: drivers/gles3/rasterizer_scene_gles3.cpp:4990

and when I run Godot 3.0.6
I get this
OpenGL ES 3.0 Renderer: ATI Mobility Radeon HD 4300 Series
ERROR: initialize: Condition ' status != 0x8CD5 ' is true. Continuing..:
   At: drivers/gles3/rasterizer_scene_gles3.cpp:4893
ERROR: initialize: Condition ' status != 0x8CD5 ' is true. Continuing..:
   At: drivers/gles3/rasterizer_scene_gles3.cpp:4893
ERROR: initialize: Condition ' status != 0x8CD5 ' is true. Continuing..:
   At: drivers/gles3/rasterizer_scene_gles3.cpp:4893
ERROR: initialize: Condition ' status != 0x8CD5 ' is true. Continuing..:
   At: drivers/gles3/rasterizer_scene_gles3.cpp:4893
ERROR: initialize: Condition ' status != 0x8CD5 ' is true. Continuing..:
   At: drivers/gles3/rasterizer_scene_gles3.cpp:4893
ERROR: initialize: Condition ' status != 0x8CD5 ' is true. Continuing..:
   At: drivers/gles3/rasterizer_scene_gles3.cpp:4893
ERROR: initialize: Condition ' status != 0x8CD5 ' is true. Continuing..:
   At: drivers/gles3/rasterizer_scene_gles3.cpp:4893
ERROR: initialize: Condition ' status != 0x8CD5 ' is true. Continuing..:
   At: drivers/gles3/rasterizer_scene_gles3.cpp:4893
ERROR: initialize: Condition ' status != 0x8CD5 ' is true. Continuing..:
   At: drivers/gles3/rasterizer_scene_gles3.cpp:4893
ERROR: initialize: Condition ' status != 0x8CD5 ' is true. Continuing..:
   At: drivers/gles3/rasterizer_scene_gles3.cpp:4893
ERROR: initialize: Condition ' status != 0x8CD5 ' is true. Continuing..:
   At: drivers/gles3/rasterizer_scene_gles3.cpp:4893
ERROR: initialize: Condition ' status != 0x8CD5 ' is true. Continuing..:
   At: drivers/gles3/rasterizer_scene_gles3.cpp:4893
ERROR: initialize: Condition ' status != 0x8CD5 ' is true. Continuing..:
   At: drivers/gles3/rasterizer_scene_gles3.cpp:4893
ERROR: initialize: Condition ' status != 0x8CD5 ' is true. Continuing..:
   At: drivers/gles3/rasterizer_scene_gles3.cpp:4893
ERROR: initialize: Condition ' status != 0x8CD5 ' is true. Continuing..:
   At: drivers/gles3/rasterizer_scene_gles3.cpp:4893
ERROR: initialize: Condition ' status != 0x8CD5 ' is true. Continuing..:
   At: drivers/gles3/rasterizer_scene_gles3.cpp:4893
ERROR: initialize: Condition ' status != 0x8CD5 ' is true. Continuing..:
   At: drivers/gles3/rasterizer_scene_gles3.cpp:4893
ERROR: initialize: Condition ' status != 0x8CD5 ' is true. Continuing..:
   At: drivers/gles3/rasterizer_scene_gles3.cpp:4893
ERROR: initialize: Condition ' status != 0x8CD5 ' is true. Continuing..:
   At: drivers/gles3/rasterizer_scene_gles3.cpp:4893
ERROR: initialize: Condition ' status != 0x8CD5 ' is true. Continuing..:
   At: drivers/gles3/rasterizer_scene_gles3.cpp:4893
ERROR: initialize: Condition ' status != 0x8CD5 ' is true. Continuing..:
   At: drivers/gles3/rasterizer_scene_gles3.cpp:4893
ERROR: initialize: Condition ' status != 0x8CD5 ' is true. Continuing..:
   At: drivers/gles3/rasterizer_scene_gles3.cpp:4893
ERROR: initialize: Condition ' status != 0x8CD5 ' is true. Continuing..:
   At: drivers/gles3/rasterizer_scene_gles3.cpp:4893
ERROR: initialize: Condition ' status != 0x8CD5 ' is true. Continuing..:
   At: drivers/gles3/rasterizer_scene_gles3.cpp:4893
ERROR: initialize: Condition ' status != 0x8CD5 ' is true. Continuing..:
   At: drivers/gles3/rasterizer_scene_gles3.cpp:4893
ERROR: initialize: Condition ' status != 0x8CD5 ' is true. Continuing..:
   At: drivers/gles3/rasterizer_scene_gles3.cpp:4893
ERROR: initialize: Condition ' status != 0x8CD5 ' is true. Continuing..:
   At: drivers/gles3/rasterizer_scene_gles3.cpp:4893
ERROR: initialize: Condition ' status != 0x8CD5 ' is true. Continuing..:
   At: drivers/gles3/rasterizer_scene_gles3.cpp:4893
ERROR: initialize: Condition ' status != 0x8CD5 ' is true. Continuing..:
   At: drivers/gles3/rasterizer_scene_gles3.cpp:4893
ERROR: initialize: Condition ' status != 0x8CD5 ' is true. Continuing..:
   At: drivers/gles3/rasterizer_scene_gles3.cpp:4893
ERROR: initialize: Directional shadow framebuffer status invalid
   At: drivers/gles3/rasterizer_scene_gles3.cpp:4918

**Comment by Zireael07** [comment] 2019-01-26 11:41
@Vikram1323: I get the same errors on my Radeon 6630M currently.

P.S. Those are the drivers I am running: https://www.dell.com/support/home/pl/pl/rc1078552/drivers/driversdetails?driverid=8v6kh

Yes I know, ancient, but this laptop is a switchable graphics laptop so trying to update drivers completely breaks the switchability and/or introduces BSOD at startup.

**Comment by akien-mga** [comment] 2019-01-26 11:47
This issue is about GLES2, not GLES3 driver issues.

**Comment by Zireael07** [comment] 2019-01-26 12:34
@akien-mga: They coincide though, maybe they're related?

**Comment by Vikram1323** [comment] 2019-01-26 14:32
I can create a new issue explaining everything and make a video because it is all related I guess. Just tell me what should I do because I love Godot Engine and I hate this error/ issue/ problem/ bug/ etc etc etc.......

**Comment by reduz** [comment] 2019-01-27 20:05
@akien-mga I think this bug became a mix up of things, the title mentions:

**GLES2 and default environment (ProceduralSky) cause a crash on some hardware**

I actually did fix this bug and should no longer be a problem on mobile.

However, all I see afterwards are reports that GLES3 driver does not work on old-radeons. I think this is an entirely different issue. I would like to know from such people (including @Zireael07, @Akira1San   and @Vikram1323) if this works in GLES2 or the issue is exclusively GLES3 only.

**Comment by Akira1San** [comment] 2019-01-27 23:08
I switch to a desktop pc and can no longer test with the laptop.

**Comment by akien-mga** [comment] 2019-01-30 09:54
As there is some confusion on this issue between GLES3 and GLES2 issues, and the original issue was fixed for many users, I propose to move the remaining cases (@Zireael07, @Akira1San) to @Vikram1323's new issue: #25482.

**Closed by akien-mga** 2019-01-30 09:54 UTC
Labels: bug, high priority, topic:rendering
