### ISSUE TITLE
Resource tree expands every time you run your project

### ISSUE THREAD

**Issue by xyroclast** [godotengine/godot#8697] opened 2017-05-08 22:10 UTC
Godot 2.1.3, Windows 10

If you collapse the subfolders of your res:// directory in the FileSystem section and then run your project, they all pop open.
This is very frustrating if you have a lot of nested folders, and I can't think of any practical/intended reason why this functionality would be present.

**Comment by bojidar-bg** [comment] 2017-05-09 05:59
Duplicate of #7134, which is marked as dupe of #796, and is potentially fixed by #6732 (which isn't merged yet).

Thus, closing.

**Closed by bojidar-bg** 2017-05-09 05:59 UTC

**Comment by xyroclast** [comment] 2017-05-25 18:13
Ah, sorry! Looks like different keywords were used to describe it each time :)
(sorry as well for the extremely late reply) :)
