### ISSUE TITLE
Resource import is very slow

### ISSUE THREAD

**Issue by qq715152910** [godotengine/godot#36834] opened 2020-03-05 20:55 UTC
Godot version:
3.2
Issue description:

I still hope to make some useful updates, such as addressing the slow import of resources, and the performance optimization of GD scripts. At present, it takes about an hour to import 1G resources. If you import 10G resources, you have to sit in front of the computer and sleep for two days. However, the resource editor file system browser of the 700M-1G import is now broken, and nothing will be displayed. File list, this may be the shortcomings of the editor itself, so I think that optimizing and solving the existing problems is the better way for Godot. If I can only import 100-500M resources, then it is destined that Godot cannot develop large games , But my path is now blocked and I cannot move forward. Hope that the next version will solve such problems, I wish Godot better and better!

**Comment by Calinou** [comment] 2020-03-06 08:53
Duplicate of #10059.

**Closed by Calinou** 2020-03-06 08:53 UTC
