### ISSUE TITLE
Horizontal Lines appear on GridMap Elements

### ISSUE THREAD

**Issue by andrevenlibretrend** [godotengine/godot#30259] opened 2019-07-02 16:54 UTC
**Godot version:**
Godot Engine v3.1.1.stable.flathub

**OS/device including version:**
Fedora 30 64 bit
Intel® Core™ i7-8550U CPU @ 1.80GHz × 8 
OpenGL ES 3.0 Renderer: Mesa DRI Intel(R) UHD Graphics 620 (Kabylake GT2) 

MacOs Mojave 10.14.5
Intel® Core™ i7-6700HQ
AMD Radeon Pro 450

**Issue description:**
Some horizontal lines are appearing on the gridmap elements while the camera is moving.
When the camera is not moving there is no problem at all.
Another thing I've noticed is that if I increase the distance to the Character more lines start appearing. 
What could be causing this?

**Minimal reproduction project:**
[horizontal_lines.zip](https://github.com/godotengine/godot/files/3351121/horizontal_lines.zip)

**Comment by Calinou** [comment] 2019-07-02 17:20
Try making each tile "bleed" into the next one slightly (by scaling the floor plane).

**Comment by andrevenlibretrend** [comment] 2019-07-03 08:40
@Calinou Thanks for your answer.
So you're telling me to try and scale it a little bigger so it would cover the area of the next floor pane, is that it?
I will try scaling it a little and mess with the rotations and see if it gets any better.

**Comment by Calinou** [comment] 2019-07-03 08:43
> So you're telling me to try and scale it a little bigger so it would cover the area of the next floor pane, is that it?

Yes :slightly_smiling_face:

**Comment by andrevenlibretrend** [comment] 2019-07-03 08:46
I've set the Scale of all tiles to 1.1 and the Rotation of the GridMap to 0.5 and it worked just fine!

Thanks so much for your help @Calinou :+1: :smile:

**Comment by Calinou** [comment] 2019-07-03 09:00
@andrevenlibretrend No problem! It seems like the issue is resolved, so I'll close this.

**Closed by Calinou** 2019-07-03 09:00 UTC
