### ISSUE TITLE
Crash when loading Panoramic Sky

### ISSUE THREAD

**Issue by Phischermen** [godotengine/godot#35747] opened 2020-01-30 16:58 UTC
**Godot version:**
3.2 stable mono

**OS/device including version:**
Windows
Intel i5
8gb RAM
NVIDIA GeForce GTX 1050

**Issue description:**
Editor crashes when trying to load Panoramic Sky with radiance_size set to 2048. Only happens at level 2048. This didn't happen in the previous version.

**Steps to reproduce:**
Make an Environment with a Panoramic sky
Set the radiance size to 2048
Editor crashes a couple seconds later

**Minimal reproduction project:**
[SkyBug.zip](https://github.com/godotengine/godot/files/4135187/SkyBug.zip)
(project will crash immediately because I edited the default environment)

**Comment by Zireael07** [comment] 2020-01-30 17:25
The warnings about having very high radiance size are there for a reason.
Godot now makes more calculations in the shader to make the radiance maps better, or so I understand.

**Comment by Calinou** [comment] 2020-01-30 18:22
Duplicate of #35552.

**Closed by Calinou** 2020-01-30 18:22 UTC

**Comment by Phischermen** [comment] 2020-01-31 02:37
Got it. Thank you.
