### ISSUE TITLE
Error printed to console on any project with an image

### ISSUE THREAD

**Issue by nathanwfranke** [godotengine/godot#32533] opened 2019-10-03 21:27 UTC
**Godot version:**
Latest 3.2
Latest 3.2 Mono
*Not reproducible in 3.1.1 Mono!* (Regression)

**OS/device including version:**
OS: Ubuntu 18.04 bionic
Kernel: x86_64 Linux 5.0.0-29-generic

**Issue description:**
On the second and all subsequent times you load the project with an image, this error shows up
```
ERROR: bind: Method/Function Failed, returning: ERR_UNAVAILABLE
   At: drivers/unix/net_socket_posix.cpp:367.
```
Happens with any image, and still happens when the `.import/` folder is deleted and even when `test.png.import` is deleted.

**Steps to reproduce:**
- Download reproduction project, or make any project that contains an image (This works on both PNG and JPG)
- Open the project and wait for the import to finish.
- Close and Reopen the project
- Error will be shown in console

**Minimal reproduction project:**
[GodotTestProject.zip](https://github.com/godotengine/godot/files/3688150/GodotTestProject.zip)

**Comment by KoBeWi** [comment] 2019-10-04 00:20
Doesn't seem to happen in 00417675f

Tested on Windows 10 x64

**Comment by qarmin** [comment] 2019-10-04 06:01
This happens for me(on Ubuntu 19.04) when I open 2 or more editors.
This is probably related with GodotLanguageServer:
![Screenshot_20191004_075934](https://user-images.githubusercontent.com/41945903/66184635-22c2c100-e67d-11e9-8dd3-916f09120aa5.png)

**Comment by akien-mga** [comment] 2019-10-04 06:02
CC @Geequlim

**Comment by Geequlim** [comment] 2019-10-04 06:26
@qarmin This problem is caused by the two editors trying to listen to same port `6008`(which is configurable in editor settings.)

**Comment by Geequlim** [comment] 2019-10-04 07:52
@Faless  Seems like the WebsocketServer not really stopped when I call `stop` here when quit to project manager.
https://github.com/godotengine/godot/blob/4da56495202847cf22bca9874593a4ed15da05e6/modules/gdscript/language_server/gdscript_language_protocol.cpp#L155-L157

**Comment by Faless** [comment] 2019-10-04 09:19
@Geequlim weird, Are you sure the problem is there?

 `WebsocketServer::stop` immediately calls `TCP_Server::close`, which in turn calls `NetSocket::close`.

https://github.com/godotengine/godot/blob/bd7b2354c5384527ed73b5d13cee61d85f38fec6/modules/websocket/wsl_server.cpp#L226-L234

https://github.com/godotengine/godot/blob/bd7b2354c5384527ed73b5d13cee61d85f38fec6/core/io/tcp_server.cpp#L115-L120

Did you manage to reproduce the issue?

**Comment by Faless** [comment] 2019-10-04 09:24
BTW, I can't reproduce it.
Of course if I open 2 editors together then the error happens, due to the language server trying to bind to the same port/address.

**Comment by Geequlim** [comment] 2019-10-04 10:29
@Faless I can reproduce this problem when quit the edtor to project list. If I reopen the project from project manager the port is still in using.
If I exit the editor directly without quit to project manager the port is stopped correctly.

**Comment by Faless** [comment] 2019-10-04 12:17
@Geequlim Now I see...
the problem is that sockets are not created with `FD_CLOEXEC`, so if we `fork` before closing them (like we do with the language server when switching to project manager) they will be copied to the new process and thus stay open if we don't close them before forking.

I'll work on adding that option to our sockets, but we might need a `_editor_deinit` callback for better cleanup of editor plugins.

**Comment by wyattbiker** [comment] 2019-10-07 22:18
Hello same problem on Mac OS X Mojave
**Version**
/Applications/Godot 2.app/Contents/MacOS$ ./Godot --version
arguments
0: ./Godot
1: --version
Current path: /Applications/Godot 2.app/Contents/MacOS
3.2.alpha1.official

**Error Message**
Godot Engine v3.2.alpha1.official (c) 2007-2019 Juan Linietsky, Ariel Manzur & Godot Contributors.
 drivers/unix/net_socket_posix.cpp:367 - Method/Function Failed, returning: ERR_UNAVAILABLE
--- GDScript language server started ---
Switch Scene Tab

**Closed** 2019-10-08 05:32 UTC
Labels: bug, regression, topic:core
