### ISSUE TITLE
Godot 3.1 Beta 7 crashes when started

### ISSUE THREAD

**Issue by jimmyjonezz** [godotengine/godot#26268] opened 2019-02-25 10:00 UTC
**Godot version:**
Godot 3.1 Beta 7/GLES2

**OS/device including version:**
Windows 7/Intel G45

**Minimal reproduction project:**
![gif1](https://user-images.githubusercontent.com/3973191/53329309-de0fc400-38fc-11e9-9f71-121ad9622129.gif)

**Comment by volzhs** [comment] 2019-02-25 10:02
#26243

**Comment by akien-mga** [comment] 2019-02-25 10:04
Duplicate of #26243.

**Closed by akien-mga** 2019-02-25 10:04 UTC
