### ISSUE TITLE
TextureButton remains 'hovered' after popup dialog is closed

### ISSUE THREAD

**Issue by drautb** [godotengine/godot#50479] opened 2021-07-15 12:15 UTC
### Godot version

3.3.stable

### System information

* Ubuntu 20.04.2 LTS, GTX 1050 Ti, GLES2 and GLES3
* macOS 11.4, Intel UHD Graphics 630, GLES2 and GLES3

### Issue description

If a `TextureButton` is configured to open a dialog, then when the dialog is closed, the `TextureButton` reverts to the hover texture until the mouse again passes over the button. 

When the dialog is open, the `TextureButton` shows its normal texture. It should continue using the normal texture when the dialog is closed.

Possibly related to https://github.com/godotengine/godot/issues/41487, but different - `get_tree().paused` is `false` in this report.

Demo Video: https://www.youtube.com/watch?v=KqDPx-jdpk8

### Steps to reproduce

1. Click texture button that brings up a dialog - observe that while the dialog is open, the texture button shows its `normal` texture.
2. Close the dialog by clicking Ok - observe that the texture button now shows its `hover` texture, even though the mouse is not over the button.

### Minimal reproduction project

[texture-button-hover.zip](https://github.com/godotengine/godot/files/6822972/texture-button-hover.zip)

**Comment by timothyqiu** [comment] 2021-07-15 12:26
In 4.0, this shows kind of a different issue:

* When the dialog poped up, the texture button's texture remain hovered.
* When the dialog is closed, the texture button's texture won't become normal until the mouse is moved.

**Comment by drautb** [comment] 2021-07-16 01:17
Workaround that i'm using in 3.3:

1. Remove the hover texture when the button is clicked: `$Button.texture_hover = null`
2. Restore the hover texture when the button emits the `mouse_entered` signal.

**Comment by kleonc** [comment] 2022-05-27 22:16
Present in `3.3.4.stable`.

Seems fixed since `3.4.stable`. Fine in the current `3.x` (`3.5.rc2+`), haven't checked `master`.
![xuIRyc1kN2](https://user-images.githubusercontent.com/9283098/170795491-c31afe4f-b0a6-47b8-9765-526ccdb706d3.gif)

**Comment by Calinou** [comment] 2022-05-27 22:24
Closing per @kleonc's comment.

If you can still reproduce a variant of this on 4.0.alpha, please open a separate issue to track that behavior.

**Closed by Calinou** 2022-05-27 22:24 UTC
Labels: bug, topic:gui
