### ISSUE TITLE
StreamPeerTCP compatibility breakage from 2.1.2 to 2.1.4

### ISSUE THREAD

**Issue by oneoh** [godotengine/godot#12648] opened 2017-11-05 01:13 UTC
OS: Tested on Linux Mint and Windows 7, true for both.

Description: the IRC client script in this project https://github.com/Timofffee/GodotIRC works perfectly in 2.1.2 but does not in 2.1.4. Not sure exactly where it's going wrong. The StreamPeerTCP client does seem to connect successfully but beyond that, get_available_bytes() doesn't seem to ever retrieve data. 

Reproduction steps: Download Timofffee's project. Test it in 2.1.2, see it works, rejoice. Test it in 2.1.4, see it does not work, be sad.

I'm not sure what to do? I'd like to use this script in my project which is nearing completion, but reverting to 2.1.2 breaks so much other stuff it's not a viable option.

**Comment by akien-mga** [comment] 2017-11-05 10:40
CC @Faless

**Comment by Faless** [comment] 2017-11-06 12:38
I'm actually unable to reproduce, I tested the project in both 2.1.4 stable and current 2.1 branch, both Linux version and Windows version (wrapped with WINE though) and they both works here.

![works](https://user-images.githubusercontent.com/1687918/32441389-b1375456-c2f7-11e7-830e-6ba5ccbdf814.png)

Can you provide more info? What is your OS? Do you have an IPv6 connection? What error are you getting in 2.1.4?

**Comment by 10bag** [comment] 2017-11-06 13:16
OS: Windows 7 on my desktop, Linux Mint on my old laptop. On both machines this project does not work in 2.1.4 but does work in 2.1.2.
Network: IPv4 only, no IPv6
No error messages are given on either machine when it fails in 2.1.4.

Note that when you "send" a message with this project, it's added to the chat window regardless of if it is actually sent. Here's a successful connection in 2.1.2 side by side with an unsuccessful connection in 2.1.4, with freenode's web client open:
![image](https://user-images.githubusercontent.com/8595739/32442778-7d2b3464-c2f4-11e7-89ae-147fa1d659e9.png)

**Comment by oneoh** [comment] 2017-11-06 13:17
OS: Windows 7 on my desktop, Linux Mint on my old laptop. On both machines this project does not work in 2.1.4 but does work in 2.1.2.
Network: IPv4 only, no IPv6
No error messages are given on either machine when it fails in 2.1.4.

Note that when you "send" a message with this project, it's added to the chat window regardless of if it is actually sent. Here's a successful connection in 2.1.2 side by side with an unsuccessful connection in 2.1.4, with freenode's web client open:

![image](https://user-images.githubusercontent.com/33384010/32442876-e0adecde-c2f4-11e7-99d8-4d047c54384b.png)

**Comment by Faless** [comment] 2017-11-06 15:32
Yes, I can confirm that `put_data` no longer blocks if the TCP stream is not connected.
When sending the data after tcp stream status is STATUS_CONNECTED instead, it works on `2.1.4` too.
Should we should restore the blocking behaviour when the status is not CONNECTED? That might lock the game if the server is not responding.

```
diff --git a/Node.gd b/Node.gd
index 398aa53..d81483c 100644
--- a/Node.gd
+++ b/Node.gd
@@ -11,20 +11,26 @@ var time
 
 var lt = RichTextLabel.new()
 
+var _login_sent = false
+
 func _ready():
 	_on_time_updater_timeout()
 	client = StreamPeerTCP.new()
 	client.connect(ip, 6667)
+	set_fixed_process(true)
+
+func send_login():
+	_login_sent = true
 	if password != "":
 		client.put_data(("JOIN "+ password +"\n").to_utf8())
 	client.put_data(("USER "+ nick +" "+ nick +" "+ nick +" :TEST\n").to_utf8())
 	client.put_data(("NICK "+ nick +"\n").to_utf8())
 	client.put_data(("JOIN "+ channel +"\n").to_utf8())
-	set_fixed_process(true)
 
 func _fixed_process(delta):
-	if client.is_connected() && client.get_available_bytes() >0:
-		
+	if client.get_status() == StreamPeerTCP.STATUS_CONNECTED and not _login_sent:
+		send_login()
+	elif client.is_connected() && client.get_available_bytes() >0:
 		var a = str(client.get_utf8_string(client.get_available_bytes()))
 		a = a.split('\n')
 		for b in a:
```

**Comment by Faless** [comment] 2018-03-16 01:05
`put_data` fails immediately without blocking if the TCP status is not `STATUS_CONNECTED`.
This is to avoid possible deadlocks.
Closing this as `works as intended`

**Closed by Faless** 2018-03-16 01:05 UTC
Labels: bug, topic:network
