### ISSUE TITLE
Cross-exporting to macOS is broken

### ISSUE THREAD

**Issue by YeldhamDev** [godotengine/godot#48076] opened 2021-04-22 02:21 UTC
**Godot version:**
3.3.stable

**OS/device including version:**
Debian 10.9

**Issue description:**
Exporting for macOS from another OS (or at the very least from GNU/Linux) appears to be broken. When opened in a mac, it shows an error that the app is "broken" and can't be run:

<img width="482" alt="Screenshot 2021-04-22 at 03 01 10" src="https://user-images.githubusercontent.com/30739239/115645951-d4355000-a310-11eb-8d68-50ce93660fa5.png">

It can be tested by exporting a completely blank project.

(Thanks @RevoluPowered for helping test this)

**Minimal reproduction project:**
[New Game Project.zip](https://github.com/godotengine/godot/files/6355037/New.Game.Project.zip)

**Comment by bruvzg** [comment] 2021-04-22 05:13
Can't reproduce, apart from Gatekeeper warnings (see https://disable-gatekeeper.github.io/), export done on Ubuntu 20.10 is working fine on macOS 11.2.3.

Can you upload exported project to check what'w wrong with it?
Which architecture (x86_64 or Apple Silicon) and macOS version was used? And which app was used to extract .ZIP on macOS?

**Comment by RevoluPowered** [comment] 2021-04-22 15:01
The Macbook pro in question. Non M1 silicone. RX 5500 PRO GPU

<img width="592" alt="Screenshot 2021-04-22 at 15 54 51" src="https://user-images.githubusercontent.com/748770/115736313-1a2afc00-a383-11eb-9816-2177472d8820.png">

Maybe then the issue is on debian only?

Here is the example binary sent to me:
https://mega.nz/file/x6oHQSCT#EwSNkRDXyltA-HVYjE5e8y2YaqJrumyYX98RaVtUWJg

**Comment by bruvzg** [comment] 2021-04-22 15:14
> Here is the example binary sent to me:
https://mega.nz/file/x6oHQSCT#EwSNkRDXyltA-HVYjE5e8y2YaqJrumyYX98RaVtUWJg

It is giving an error, but after removing the Gatekeeper quarantine flag, it is working fine.

I guess it's expected behavior from a fully unsigned app (if it was not the same in 3.2, it's probably cased by the linker signature present in the M1 part of binary).

When exporting from macOS, it's always possible to ad-hoc sign, but I do not think we can do anything with exports from Linux/Windows, there's no `codesign` equivalent.

**Comment by RevoluPowered** [comment] 2021-04-22 15:28
To me this is broken so we can't recommend users disable this gatekeeper. Would signing the executable on Ubuntu work?

**Comment by RevoluPowered** [comment] 2021-04-22 15:33
Never mind I see the *only* way to sign a MacOS executable is from OSX.

**Comment by bruvzg** [comment] 2021-04-22 15:33
> To me this is broken so we can't recommend users disable this gatekeeper.

There's no need to disable Gatekeeper, just run `xattr -dr com.apple.quarantine AppName.app` command after extracting the app. Some distribution platforms (Steam, MacPorts) do not set the flag, and apps will work without extra steps.

> Would signing the executable on Ubuntu work?

No, AFAIK there is no working signing tools for Linux.

**Comment by RevoluPowered** [comment] 2021-04-22 15:34
> > To me this is broken so we can't recommend users disable this gatekeeper.
> 
> There's no need to disable Gatekeeper, just run `xattr -dr com.apple.quarantine AppName.app` command after extracting the app. Some distribution platforms (Steam, MacPorts) do not set the flag, and apps will work without extra steps.
> 
> > Would signing the executable on Ubuntu work?
> 
> No, AFAIK there is no working signing tools for Linux.

Makes me wonder if we should make a .app file which is tiny which can disable the flag for the user

**Comment by RevoluPowered** [comment] 2021-04-22 15:44
For anyone else experiencing this issue who doesn't have a mac to deploy from:
- if you use github actions you can use it to build your game export and this will run on an OSX builder. I will put some docs here if we do this.
- typically the idea is simple: if you use *any* osx builder which provides an actual apple device for the build you should be able to give the executable without the gatekeeper security enabling because you built the binary on the CI process.

It might take longer to export this way but definitely worth it IMHO

I will update here once i have tested this method out without the macbook.

**Comment by bruvzg** [comment] 2021-04-22 16:12
> Makes me wonder if we should make a .app file which is tiny which can disable the flag for the user

Can be done with simple AppleScript (as is or packed into the App).

```applescript
on run
    do shell script "xattr -dr com.apple.quarantine " & quoted form of the POSIX path of (choose file of type "APP")
end run
```

**Comment by bruvzg** [comment] 2021-04-22 16:23
> You can also ask someone with a macbook to build your binary for you.

Note, that the whole exported bundle need to be signed, signing just an export template executable will result in the same error.

**Comment by RevoluPowered** [comment] 2021-04-22 16:27
> > Makes me wonder if we should make a .app file which is tiny which can disable the flag for the user
> 
> Can be done with simple AppleScript (as is or packed into the App).
> 
> ```applescript
> on run
>     do shell script "xattr -dr com.apple.quarantine " & quoted form of the POSIX path of (choose file of type "APP")
> end run
> ```
> 
> [Remove Quarantine.zip](https://github.com/godotengine/godot/files/6359716/Remove.Quarantine.zip)

This is perfect :) I will try this out.

> > You can also ask someone with a macbook to build your binary for you.
> 
> Note, that the whole exported bundle need to be signed, signing just an export template executable will result in the same error.

I'm guessing the problem then is actually because we sign the export templates at all? I saw another project disabled signing temporarily until they could come up with a better solution.

https://github.com/MacDownApp/macdown/issues/1127

**Comment by bruvzg** [comment] 2021-04-22 16:32
> I'm guessing the problem then is actually because we sign the export templates at all?

We only add "linker-signature" (https://github.com/godotengine/godot-build-scripts/blob/master/build-release.sh#L89-L91),  it is required to run on M1 (even with the gatekeeper fully disabled). Xcode does the same for all executables (we need a separate command because OSXCross does not support it yet).

**Comment by RevoluPowered** [comment] 2021-04-22 16:36
> > I'm guessing the problem then is actually because we sign the export templates at all?
> 
> We only add "linker-signature" (https://github.com/godotengine/godot-build-scripts/blob/master/build-release.sh#L89-L91), it is required to run on M1 (even with the gatekeeper fully disabled). Xcode does the same for all executables (we need a separate command because OSXCross does not support it yet).

Thanks @bruvzg I asked a few people around about this, I had no idea this kind of thing was so painful. I think since we can't do much about this, we should close the issue and I can test out the 'remove quarantine' method, it was only really needed because of the file coming from itch.io from a web page rather than an app.

**Closed** 2021-04-22 16:42 UTC
Labels: platform:linuxbsd, regression, topic:export

**Comment by bruvzg** [comment] 2021-04-22 17:09
A little update - fully removing signature won't help, neither it works with x86-64 only binary or 3.2.3 one. So it's not M1 "linker-signature", but probably a new policy in the macOS 11.2.3 update.

**Comment by RevoluPowered** [comment] 2021-04-22 17:14
> A little update - fully removing signature won't help, neither it works with x86-64 only binary or 3.2.3 one. So it's not M1 "linker-signature", but probably a new policy in the macOS 11.2.3 update.

I wonder if the github binaries for 3.3 would work without *any* codesign arguments and the export templates provided from the CI:

https://github.com/godotengine/godot/runs/2412123803

**Comment by bruvzg** [comment] 2021-04-22 18:12
> >    You can also ask someone with a macbook to build your binary for you.
>
> Note, that the whole exported bundle need to be signed, signing just an export template executable will result in the same error.

I have done some more testing, and actually ad-hoc singing executable only seems to work. But it has to be outside the export template bundle when it's done.

**Comment by bruvzg** [comment] 2021-04-22 18:14
https://github.com/godotengine/godot-build-scripts/blob/master/build-release.sh#L87-L92

So instead of extracting `osx.zip`, and signing export template, it should extract only executable and dylibs and sing them one by one without `--options=linker-signed`.

**Comment by RevoluPowered** [comment] 2021-04-22 18:51
I think one matter that makes it a little harder is we have 2 signings to do. 


- The godot binary, the platform specific export template.
- The executable shipped with the game.

What I suspect is happening when you export a build is that gatekeeper is only triggered because we have some code which is signed incorrectly or unsigned and because the engine runtime is signed the disjoint state triggers gatekeeper.

The reason I think this is the case is because we export from ubuntu the signing key is in the export template already, this export template is signed, the code that we load for the actual game runtime is either unsigned or signed incorrectly. 

Thus MacOS thinks that we are attempting to circumvent security and triggers gatekeeper rather than the untrusted source warning. As if a person was writing a virus and injected code into your app, then they could do this and not sign the code, and put it adjacent to your signed code. It would make no sense if you could do this because it would break the trusted relationship between the executable and the OS.

**Comment by RevoluPowered** [comment] 2021-04-22 18:53
Only way to test this I can think of is to:
1. make a build entirely with signing disabled for ubuntu with a unsigned export template too.
2. make a build of any game try running it, since the runtime and the signing is off
3. run the app on a macbook, gatekeeper will warn instead of mark the file as corrupt.

**Comment by bruvzg** [comment] 2021-04-22 19:00
Redone all tests with renaming app and redownloading in each time from the local server, to prevent caching results:

- Singing executable outside the bundle does not work.
- Removing signature completely works on x86-64, but will completely break it on M1 (removing quarantine flag or disabling Gatekeeper won't help).

**Comment by RevoluPowered** [comment] 2021-04-22 19:02
> Redone all tests with renaming app and redownloading in each time from the local server, to prevent caching results:
> 
> * Singing executable outside the bundle does not work.
> * Removing signature completely works on x86-64, but will completely break it on M1 (removing quarantine flag or disabling Gatekeeper won't help).

Well I guess we know it can be 'fixed' but its a short term solution until M1 is popular.

**Comment by bruvzg** [comment] 2021-04-22 19:33
> I am not exactly sure if this is helpful at all since I had mixed results, but Godot said it signed it as you can see here:

By default, Godot is signing using ad-hoc signature (one without developer identity), you can set Apple issued developer ID in the export settings to use it instead.

> And it was an improvement in that it no longer said the file was corrupt, but it did have the usual "Unsigned developer" message.

Unless app is notarized after the export (with `xcrun altool` command), it will have the same warning and require unlocking it in the security setting (or by selecting "Open" from the context menu two times), there's no workaround for this.

This is the same results as exporting from macOS, so GitHub Actions are working correctly.

**Comment by robpc** [comment] 2021-04-22 19:41
> This is the same results as exporting from macOS, so GitHub Actions are working correctly.

Ahh, ok, so maybe not news. Apologies if this spams the thread and appreciate the additional info on osx exporting.

**Comment by bruvzg** [comment] 2021-08-13 08:28
FYI, a custom implementation of the `codesign` for non-macOS systems is being developed it the PRs #51310 (4.0) and #51550 (3.x), this should allow ad-hoc signing on Linux/Windows. Exported projects will be blocked as "Unidentified developer", but at least they will be valid, and "Right click" → "Open" workaround will work.
