### ISSUE TITLE
When migrating a project from Godot 3.5.1 to Godot 4.0.3 There are problems opening scenes

### ISSUE THREAD

**Issue by pentarix1996** [godotengine/godot#79200] opened 2023-07-08 12:16 UTC
### Godot version

Godot v4.0.3.stable

### System information

Windows 10 - Godot v4.0.3.stable

### Issue description

When migrating a project from Godot 3.5.1 to Godot 4.0.3 There are problems opening scenes.

I had my project in Godot 3.5.1 (stable), but when migrating to version 4.0.3 (stable) following the steps in the official documentation, I run into some problems when opening a scene (the engine closes unexpectedly ). Looking at the console logs, I see the following:

![image](https://github.com/godotengine/godot/assets/56296055/daa0d717-e917-46e0-a109-3ff0fec4f560)

I had a scene with a tile with an Atlas to paint the scene, I see that the problem mainly comes from that point. I see that the automatic migration system has some kind of bug at that point.

### Steps to reproduce

- Create a project in Godot 3.5.1 (stable)

- Create a TileSet to paint a scene

- Migrate the project to Godot 4.0.3 (stable)

- Try to open the scene and see how the engine shuts down unexpectedly

### Minimal reproduction project

"N/A"

**Comment by Zireael07** [comment] 2023-07-08 14:02
Duplicate of already reported issue that I can't find the number of

**Comment by Calinou** [comment] 2023-07-08 14:37
Thanks for the report! Consolidating in https://github.com/godotengine/godot/issues/67556.

**Closed by Calinou** 2023-07-08 14:37 UTC
Labels: bug, topic:editor, topic:2d
