### ISSUE TITLE
`CSharpScript::callp` `!valid` error when creating a new C# script in the editor

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot#84890] opened 2023-11-14 15:06 UTC
### Godot version

4.2.beta6, master (40cdd22d570024d906c9a5795fa079342dce2197)

### System information

Mageia 9 - Vulkan (Forward+) - dedicated AMD Radeon RX Vega M GL Graphics (RADV VEGAM) () - Intel(R) Core(TM) i7-8705G CPU @ 3.10GHz (8 Threads)

### Issue description

In a clean new project, when I add a new C# script using the "Attach Node Script" dialog, the following error is printed each time:
```
ERROR: Condition "!valid" is true. Returning: Variant()
   at: callp (modules/mono/csharp_script.cpp:2612)
```

It also happens when loading an existing script.

Building the script then still works fine and the project can run without further error.

---

That error doesn't happen in 4.1-stable, so it appears to be a regression.

I tested 4.2 beta 4 to beta 6 and latest `master`, they all show the error. I'll test earlier builds now.

### Steps to reproduce

- Create new project with .NET build
- Add node
- Attach C# script to that node

### Minimal reproduction project

n/a

**Comment by raulsntos** [comment] 2023-11-14 15:10
Sounds like a duplicate of https://github.com/godotengine/godot/issues/83351

**Closed** 2023-11-14 15:11 UTC
Labels: bug, topic:dotnet, regression
