### ISSUE TITLE
Input Latency

### ISSUE THREAD

**Issue by LapizGaming7751** [godotengine/godot#33056] opened 2019-10-25 08:00 UTC
**Godot version:**
3.1.1
**OS/device including version:**
Almost any.
**Issue description:**
The letter I type doesn't show up until I start typing my next letter.
**Steps to reproduce:**
Type two letters

**Comment by Zireael07** [comment] 2019-10-25 08:28
We had similar reports in the past, are your devices using Intel integrated graphics?

**Comment by Calinou** [comment] 2019-10-25 12:38
Duplicate of #23069. Try updating your graphics driver to the latest version provided by Intel. Alternatively, start the Godot editor with the `--verbose` command-line argument, which can also mitigate the issue.

**Closed by Calinou** 2019-10-25 12:38 UTC
