### ISSUE TITLE
Autocomplete only shows when pressing CTRL+SPC

### ISSUE THREAD

**Issue by nonunknown** [godotengine/godot#52869] opened 2021-09-20 12:14 UTC
### Godot version

v4.0.dev.20210916.official [104a6191f]

### System information

manjaro Gnome 21, AMD R7 200 series, Intel i3 3.0 GHZ,8GB RAM

### Issue description

See the gif bellow:
![test](https://user-images.githubusercontent.com/58845030/134000335-db6d3ac2-a37d-4b5c-8fa0-3cd3d2919329.gif)

Current behaviour: Doesnt show autocomplete when typing, only when pressing CTRL+SPC

Expected behaviour: Show autocomplete without pressing CTRL+SPC like in 3.x

### Steps to reproduce

* Create a function
* Try to call it
* Autocomplete will not show
* Type a piece of the func name
* press CTRL+SPC
* now Autocomplete show

### Minimal reproduction project

N/a

**Comment by Calinou** [comment] 2021-09-20 14:28
Duplicate of https://github.com/godotengine/godot/issues/51996
.

**Closed by Calinou** 2021-09-20 14:28 UTC
