### ISSUE TITLE
C#: [Signal] attribute does not work in classes with generic type parameters.

### ISSUE THREAD

**Issue by Yeasteroni** [godotengine/godot#54741] opened 2021-11-07 22:23 UTC
### Godot version

3.4 Stable

### System information

Windows 10 Home, GLES3, Intel Core i7-6567U, Intel Iris Graphics 550 (30.0.100.9955), 16GB RAM

### Issue description

Signals declared with the [Signal] attribute in a class deriving from a godot object that has generic type parameters do not register in Godot.

Workaround: Add signals with AddUserSignal().

### Steps to reproduce

Make an object that derives from Object and make a signal declared inside with [Signal]. Try to connect to it.

### Minimal reproduction project

[GenericTest.zip](https://github.com/godotengine/godot/files/7493231/GenericTest.zip)

**Comment by Calinou** [comment] 2021-11-07 22:37
Possible duplicate of <https://github.com/godotengine/godot/issues/47830>?

**Comment by raulsntos** [comment] 2021-11-08 14:48
Yes, it's a duplicate.

**Closed** 2021-11-08 17:42 UTC
Labels: topic:mono
