### ISSUE TITLE
Error and leak on close when running a scene containing a script

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#23468] opened 2018-11-03 02:03 UTC
Godot 3.1 alpha2
Windows 10 64 bits

Reproduction steps:
1) Create a new project
2) Create a new scene with a `Control` node as root
3) Create a new script on the root node. Just leave it untouched.
4) Run the scene, and close the game: notice an error is printed.
```
ERROR: ~List: Condition ' _first != __null ' is true.
   At: ./core/self_list.h:111
ERROR: ~List: Condition ' _first != __null ' is true.
   At: ./core/self_list.h:111
WARNING: cleanup: ObjectDB Instances still exist!
     At: core/object.cpp:2062
```

**Comment by rodolforg** [comment] 2018-11-05 02:09
Here at Debian (testing) it prints
```
ERROR: ~List: Condition ' _first != __null ' is true.
   At: ./core/self_list.h:111.
ERROR: ~List: Condition ' _first != __null ' is true.
   At: ./core/self_list.h:111.
WARNING: cleanup: ObjectDB Instances still exist!
   At: core/object.cpp:2062.
ERROR: clear: Resources Still in use at Exit!
   At: core/resource.cpp:425.
```

At master branch ( df39a034dccbc2c0e78b7345d13224278da7a608 ):
```
WARNING: cleanup: ObjectDB Instances still exist!
   At: core/object.cpp:2081.
```

**Comment by akien-mga** [comment] 2018-11-20 13:57
Duplicate of #23661 (newer, but I did the debugging there).

**Closed by akien-mga** 2018-11-20 13:57 UTC
Labels: bug, topic:core
