### ISSUE TITLE
TextEdit selected font color doesn't seem to work. 

### ISSUE THREAD

**Issue by Shadowblitz16** [godotengine/godot#63053] opened 2022-07-15 21:17 UTC
### Godot version

4.0 alpha 11

### System information

KDE neon 5.25

### Issue description

The selected font color for TextEdit doesn't seem to work like in LineEdit.
I haven't tried it with RichEdit but in LineEdit it seems to work.

### Steps to reproduce

- Create a theme resource
- Add Line Edit
- Add Text Edit
- In both make font_selected_color to bright red
- Use the Default Preview to see that when you selected text in line edit it is red but in text edit it is not.

### Minimal reproduction project

[AstroWars.zip](https://github.com/godotengine/godot/files/9124117/AstroWars.zip)

**Comment by Paulb23** [comment] 2022-07-16 10:17
Duplicate of #45301

**Closed by Paulb23** 2022-07-16 10:17 UTC
Labels: needs testing, topic:gui
