### ISSUE TITLE
Light Mask layers seem to be ignored by Light2D

### ISSUE THREAD

**Issue by wallyfoo** [godotengine/godot#38568] opened 2020-05-08 14:00 UTC
3.2.1 Stable Official

macOS 10.15.4

I have two sprites and two Light2Ds in a scene. Each pair is on a different light mask layer. Only the sprite on Light Mask Layer 1 picks up the Light2D, but both the Light2Ds, regardless of light mask assignment. I was going to use this as a masking trick for two layers of graphics, but hit a brick wall.

Steps to reproduce: Set up a scene as described above. I've not tested every edge case, but a Light2D on any (or no light mask layer) will only be picked up by a Sprite on Light Mask Layer 1. The blending mode doesn't seem to matter, even though my reduction project is specifically testing mix mode.

[Light2d reduction.zip](https://github.com/godotengine/godot/files/4599328/Light2d.reduction.zip)

**Comment by Calinou** [comment] 2020-05-19 08:37
Duplicate of #29612.

**Closed by Calinou** 2020-05-19 08:37 UTC
Labels: bug, topic:rendering
