### ISSUE TITLE
[Workflow] Engine Lets user export game without a Main scene defined

### ISSUE THREAD

**Issue by nonunknown** [godotengine/godot#47323] opened 2021-03-24 14:33 UTC
**Godot version:**
3.3 RC6

**OS/device including version:**
Win 10 x64

**Issue description:**
The Engine lets the user export the project, even when a Main Scene isnt defined, this makes the game non-runable!

**Steps to reproduce:**
* Create a project
* Export Without defining Main Scene

**Comment by Calinou** [comment] 2021-03-24 14:36
Duplicate of https://github.com/godotengine/godot/issues/39984.

**Closed by Calinou** 2021-03-24 14:36 UTC
