### ISSUE TITLE
Adding a C# script to a node with default name => compile error

### ISSUE THREAD

**Issue by Duehok** [godotengine/godot#16577] opened 2018-02-12 08:21 UTC
**Godot version:**
3.0

**OS/device including version:**
Win 8.1, Mono 5.4.1.7

**Issue description:**
A C# script added to a node with its default name does not compile.
Cause: The custom C# class is named after the node and extends the base class of the node. When both have the same name the class extends itself.
Worse is that renaming the node in the editor does not rename the class in the script.
At least there should be an error message and no script creation when creating a script for a node that still has its default name.

**Steps to reproduce:**
In any scene, create any node, add a C# script to it and test the scene.

**Minimal reproduction project:**
[NotCompilingByDefault[1].zip](https://github.com/godotengine/godot/files/1715631/NotCompilingByDefault.1.zip)

**Comment by GDScriptHacker5000LOL** [comment] 2018-02-12 09:49
LOL! fucking #16578 and #16577 in a row. ayyyy @reduz how you liking those game breaking C# issues? definitely worth it eh, lmfao.

**Comment by GDScriptHacker5000LOL** [comment] 2018-02-12 09:55
@neikeq you're a pretty tolerant contributor...

![](https://i.gyazo.com/05a0bce681abeb621a9a401b49d0d66a.png)

**Comment by Hinsbart** [comment] 2018-02-12 10:17
Duplicate of #12483

**Closed by Hinsbart** 2018-02-12 10:17 UTC
