### ISSUE TITLE
DirectionalLight Shadows in orthogonal view don't show

### ISSUE THREAD

**Issue by eastriverlee** [godotengine/godot#69370] opened 2022-11-30 05:06 UTC
### Godot version

4.0beta6

### System information

macOS 13.0.1, Apple M1 Max

### Issue description

Shadows casted by DirectionalLights in orthogonal view don't show.
This used to work in Godot 3.x.
SpotLights and OmniLights work fine.

# 3.5.1 (expected)
<img width="1136" alt="Screenshot 2022-11-30 at 13 40 34" src="https://user-images.githubusercontent.com/43613000/204709707-8b201685-c8c7-482b-830e-667df840d860.png">

# 4.0beta6 (bug)
<img width="1092" alt="Screenshot 2022-11-30 at 13 40 36" src="https://user-images.githubusercontent.com/43613000/204709728-638c5bdd-824c-4337-877d-c74206e6ac9f.png">

# Testing various settings (left: 3.5.1, right: 4.0beta6)

### shadow:
* Orthogonal
* PSSM 2 Splits
* PSSM 4 Splits

### view: 
* Perspective
* Orthogonal

https://user-images.githubusercontent.com/43613000/204710410-763ddbde-893e-4b38-b17d-82d73bd71e07.mov

### Steps to reproduce

1. Add Meshes
2. Add DirectionalLight
3. Render in Orthogonal View

### Minimal reproduction project

[orthogonal_shadow.zip](https://github.com/godotengine/godot/files/10119625/orthogonal_shadow.zip)

**Comment by Calinou** [comment] 2022-11-30 15:57
Duplicate of https://github.com/godotengine/godot/issues/58332.

You need to decrease the camera's Far property (example with the editor camera settings in the **View** menu at the top of the 3D viewport):

![2022-11-30_16 56 57](https://user-images.githubusercontent.com/180032/204846288-c8412e41-f978-4cbd-9af3-f087666ad87a.png)

**Closed** 2023-01-09 13:44 UTC
Labels: bug, archived, topic:rendering, topic:3d
