### ISSUE TITLE
Curve3d get_baked_points() regression

### ISSUE THREAD

**Issue by Bimbam360** [godotengine/godot#69548] opened 2022-12-04 01:56 UTC
### Godot version

4.0 Beta 7

### System information

Windows 11

### Issue description

get_baked_points() returns arbitrarily dense points (seemingly limited between vertex 0 and 1).

Normal behaviour in Beta 6 using Marker3D nodes to highlight baked positions:
![image](https://user-images.githubusercontent.com/11803603/205470351-12873486-9de9-4e39-835d-a3c951113577.png)

Broken behaviour in Beta 7 using Marker3D nodes to highlight baked positions:
![image](https://user-images.githubusercontent.com/11803603/205470095-c3471d8e-912f-4502-8cdd-2cc6099ce7f0.png)

### Steps to reproduce

Setup a Path3D/Curve3D with some amount of points, then try to plot baked points as returned by get_baked_points() 

e.g.
```
var points = $Path3D.curve.get_baked_points()
for pt_idx in range(0, points.size()):
        var marker = Marker3D.new()
        $Node3D.add_child(marker)
        marker.global_transform.origin = points[pt_idx]
        marker.owner = self
```

### Minimal reproduction project

N/A

**Comment by xiongyaohua** [comment] 2022-12-04 06:30
It seems also been solved by https://github.com/godotengine/godot/pull/69239

![image](https://user-images.githubusercontent.com/6020486/205477710-43b1c953-c6e1-4ad1-86de-dba0787648a3.png)

**Comment by akien-mga** [comment] 2022-12-04 09:49
Duplicate of #69220

**Closed by akien-mga** 2022-12-04 09:49 UTC
