### ISSUE TITLE
OpenSymbols font doesn't render its symbols

### ISSUE THREAD

**Issue by razcore-art** [godotengine/godot#6294] opened 2016-08-26 15:58 UTC
**Operating system or device - Godot version:**
Ubuntu 16.04 - v2.1.stable.official

**Issue description** (what happened, and what was expected):
Text on controllers with webdings font doesn't render at all.

**Steps to reproduce:**
Use any controller node and set font to dynamic + webdings.

**Link to minimal example project** (optional but very welcome):
[debug.zip](https://github.com/godotengine/godot/files/439628/debug.zip)

**Comment by Calinou** [comment] 2018-04-05 09:39
First of all thank you for your report and sorry for the delay.

We released Godot 3.0 in January 2018 after 18 months of work, fixing many old issues either directly, or by obsoleting/replacing the features they were referring to.

We still have hundreds of issues whose relevance/reproducibility needs to be checked against the [current stable version](https://godotengine.org/download), and that's where you can help us.
**Could you check if the issue that you described initially is still relevant/reproducible in Godot 3.0 or any newer version, and comment about it here?**

For bug reports, please also make sure that the issue contains detailed steps to reproduce the bug and, if possible, a zipped project that can be used to reproduce it right away. This greatly speeds up debugging and bugfixing tasks for our contributors.

Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

Thanks in advance.

*Note: This message is being copy-pasted to many "stale" issues (90+ days without activity). It might happen that it is not meaningful for this specific issue or appears oblivious of the issue's context, if so please comment to notify the Bugsquad about it.*

**Comment by razcore-art** [comment] 2018-06-23 08:59
Yes, this is still a problem in v3 8bf5b50, in the project `Label2` should display symbols corresponding to `The quick brown fox` but it doesn't render anything.
[godot-dbg.zip](https://github.com/godotengine/godot/files/2129777/godot-dbg.zip)

**Comment by volzhs** [comment] 2018-06-23 12:54
![screenshot_20180623_215148](https://user-images.githubusercontent.com/8281454/41809859-a705ea78-772f-11e8-800e-d82bcb06d501.png)

This is a screenshot for opening `Ubuntu-R.ttf` and `opens___.ttf` on Kubuntu 18.04
does really `opens___.ttf` have corresponding symbols?

**Comment by razcore-art** [comment] 2018-06-23 13:02
@volzhs on my system (Ubuntu 18.04) it does, this is what it should look like
![image](https://user-images.githubusercontent.com/1177508/41809965-6314dd4e-76f6-11e8-9252-b18ee51e0cd6.png)

**Comment by KoBeWi** [comment] 2020-06-11 20:47
Still valid™ in 46e0e13

**Comment by bruvzg** [comment] 2020-06-11 20:54
Looks like some symbol fonts have non-standard encoding, probably we need to do something like this: https://github.com/harfbuzz/harfbuzz/blob/973c47f6c9886cd2a50d29e09c978831b4e355f6/src/hb-ft.cc#L261-L270

**Comment by khaledhosny** [comment] 2020-06-12 02:02
OpenSymbol is an internal font to be used by LibreOffice (or OpenOffice, each has its own version of the font), and it is unusable for any other application as it uses an non-standard and undocumented encoding.

**Comment by akien-mga** [comment] 2021-04-28 09:42
Thanks for the info, closing then as we can't aim to support non-standard fonts.

**Closed by akien-mga** 2021-04-28 09:42 UTC
Labels: bug, confirmed, topic:core
