### ISSUE TITLE
GeometryInstance3D transparency property is broken

### ISSUE THREAD

**Issue by Kuma-Boo** [godotengine/godot#71293] opened 2023-01-12 21:56 UTC
### Godot version

v4.0.beta11.mono.official [91713ced8]

### System information

Windows 10

### Issue description

In previous versions, GeometryInstance3D's transparency property could be used to fade out an object, but now objects are completely visible/invisible, with nothing in between.

### Steps to reproduce

1. Create a MeshInstance3D
2. Add a new BoxMesh in MeshInstance3D/mesh
3. Change GeometryInstance3D/transparency to anything other than 0.

### Minimal reproduction project

N/A

**Comment by Calinou** [comment] 2023-01-12 22:11
Which rendering backend are you using? See https://github.com/godotengine/godot/issues/69877.

**Comment by clayjohn** [comment] 2023-01-12 22:47
Duplicate of https://github.com/godotengine/godot/issues/71249, already fixed in master. The fix will be available in Beta 12

**Closed by clayjohn** 2023-01-12 22:47 UTC
Labels: topic:rendering, topic:3d
