### ISSUE TITLE
Ctrl + A while editing a script wants to add a node too.

### ISSUE THREAD

**Issue by ranmaru90** [godotengine/godot#5402] opened 2016-06-25 05:49 UTC
**Operating system or device - Godot version:**
Windows 10 Pro. Compile latest source from GitHub repo.

**Issue description** (what happened, and what was expected):
When editing a script on a node, Ctrl + A doesn't just select all, it brings up the add node dialog box too.

**Steps to reproduce:**
1. Put a script on a node in a scene. 
2. Edit the script.
3. While editing, press Ctrl + A.

**Comment by neikeq** [comment] 2016-06-25 09:11
Duplicate of #5374

**Closed by neikeq** 2016-06-25 09:11 UTC
