### ISSUE TITLE
("Sticky"?) dropdown menu focus causes erratic mouse (de)select behaviour in editor collision layers (DisplayServer regression)

### ISSUE THREAD

**Issue by ModularNucleus** [godotengine/godot#61773] opened 2022-06-07 10:06 UTC
### Godot version

Godot alpha 4 - alpha 9

### System information

Windows 10, Nvidia RTX3060 Ti, Vulkan Clustered

### Issue description

I have tried to do a search, but have not found a report that seems to describe exactly the same issue, although #61758 may be related. 

It seems that when using a dropdown menu, the focus can become stuck to the dropdown menu and affect subsequent mouse (de)select behaviour - e.g., in collision layer (de)selection.

Note: I have only tested the editor collision layer behaviour, not the actual collision layer behaviour. I assume this is an editor issue.

Video1 below:
With an Aread3D and a CollisionShape3D node - but not yet an actual collision shape - added to the scene, the collision layer (de)selection works as expected. However, after adding the collision shape via the shape dropdown menu, collision layer (de)selection becomes erratic. The issue might affect other editor items as well, but I haven't really checked.

Note: the dropdown menus are not displayed in the videos due to my screen capture software.

https://user-images.githubusercontent.com/91982860/172355726-f592a73f-e41f-4460-8c82-710be939c6d9.mp4

Video2 below:
After reloading the project, the (de)selection again works as expected. However, using the CollisionObject3D "disable" dropdown menu reintroduces the erratic behaviour.

https://user-images.githubusercontent.com/91982860/172355809-e76e533b-358e-4114-9b75-c1d241fc0c93.mp4

I can reproduce this issue in alphas 4-9, but not in alpha 3 nor earlier alphas. The issue thus seems to have been introduced in alpha 4.

### Steps to reproduce

Open the included MRP:
- Change the Area3D's collision layers. Observe that they behave as expected.
- Use the "disable" dropdown menu (e.g., change / change and reset) above the collision layers. Observe that the erratic (de)select behaviour is introduced to the collision layer (de)selection.

### Minimal reproduction project

[Default.zip](https://github.com/godotengine/godot/files/8852103/Default.zip)

**Comment by Calinou** [comment] 2022-06-07 16:28
Can you reproduce this after enabling **Single Window Mode** in the Editor Settings then restarting the editor?

**Comment by KoBeWi** [comment] 2022-06-08 11:49
Can't reproduce on Windows 10.
Does it always happen? Might be the same issue as #58609

**Comment by ModularNucleus** [comment] 2022-06-10 07:59
@Calinou No, I cannot reproduce this with "Single window mode" enabled. Without it, however, the issue is consistent.

**Comment by ModularNucleus** [comment] 2022-06-10 08:09
@KoBeWi Yes, it does always happen when not in "Single Window Mode", but it is fixable by Alt+tabbing, as in the issue you linked, until I use the dropdown menu - then the issue reappears.

**Comment by KoBeWi** [comment] 2022-06-10 13:23
Oooh this is interesting. I can reproduce it reliably and it has all of the symptoms from #58609. I'll close it as duplicate, but this is important finding.

**Closed by KoBeWi** 2022-06-10 13:23 UTC
Labels: bug, topic:editor, regression
