### ISSUE TITLE
iOS not able to detect deleted objects

### ISSUE THREAD

**Issue by HEAVYPOLY** [godotengine/godot#39897] opened 2020-06-27 20:18 UTC
**Godot version:**
3.2.2stable

**OS/device including version:**
iOS 13.1

**Issue description:**
on iOS checking for deleted/freed objects using if object == null:
or is_instance_valid() doesn't work.  It does work on other platforms.

for example print(object) prints [Deleted Object] on MacOS.  On iOS there is no print.

likewise the check 
if object == null:
   print('Object is null')
returns false, doesn't print anything.
**Steps to reproduce:**
delete an object using object.queue_free(), then print(object)

if !is_instance_valid(object):
    print('NOT VALID')
**Minimal reproduction project:**

**Comment by akien-mga** [comment] 2020-06-27 20:23
Is this with a release or debug build? If release, does it work with a debug build?

CC @RandomShaper

**Comment by HEAVYPOLY** [comment] 2020-06-27 20:33
I'm using 3.2.2 Stable from yesterday, not sure if this is release or debug?

**Comment by akien-mga** [comment] 2020-06-27 20:39
When you export to iOS (or any platform), you can either export a debug build ("Export With Debug" checked on), or a release (optimized) build ("Export With Debug" unchecked).

![](https://user-images.githubusercontent.com/4701338/84773585-e2259080-afdc-11ea-936b-3428e3eef8cf.png)

**Comment by HEAVYPOLY** [comment] 2020-06-27 20:41
I'm exporting from Xcode to iPad, is this option in Xcode somewhere?

**Comment by RandomShaper** [comment] 2020-06-27 20:41
**On _release_ builds (even before the dangling `Variant` fix):**
You never expect to get the variable assigned to `null`. I guess that's being the case on iOS (the release template is being used). `is_instance_valid()` will return `true` as long as the original object or any other later created in the same memory address hasn't been freed. Not very robust, if you ask me.

**On _debug/release_debug_ builds:**
The the check against `null` will succeed, because what the dangling protection does is treating variables pointing to freed objects as `null`. `is_instance_valid()` will return `true` only if the variable is still pointing to the original object which hasn't been freed; and `false` otherwise (if the object has been freed, you are effectively checking `is_instance_valid(null)`).

**Comment by HEAVYPOLY** [comment] 2020-06-27 20:44
@RandomShaper this is working as expected on release as well as debug builds for windows and mac.

Is there a better way to do this than what I'm attempting?

**Comment by HEAVYPOLY** [comment] 2020-06-27 20:47
Instead of object.queue_free, should I do object = null?

**Comment by HEAVYPOLY** [comment] 2020-06-27 20:51
object = null seems to do the trick for my check.  Unless there's a better way I'll use this for now.

**Comment by RandomShaper** [comment] 2020-06-27 20:56
Assigning to `null` won't destroy the object, but will let your code know you no longer consider it valid.

But you have to destroy it beforehand with `free()` or `queue_free()` because otherwise it will stay in memory "forever."

Note that applies to objects that are not `Resource`s, because they already have a mechanism of reference counting and they are automatically freed when they are not being referenced anymore. Furthermore, you cannot free them explicitly. In short, with them you don't need to worry much about their lifetime.

But for things like `Node` you should.

The "dangling protection" is there in debug builds to help you catch bugs that would cause bad things to happen on release builds. Therefore, you must still be careful with the lifetime of your objects.

Hope this helps.

**Comment by HEAVYPOLY** [comment] 2020-06-27 20:58
Ah ok, so I should do this?
object.queue_free()
object = null

**Comment by naithar** [comment] 2020-07-05 21:36
I've tested on 3.2.2 stable and got a little different results.

Godot's code:
```
var object = null

func _ready():
	object = Node.new();
	print(object)
	object.queue_free()
	print(object)
	
	if !is_instance_valid(object):
		print('NOT VALID')
	else:
		print('Still valid')
		
func _process(delta):
	if !is_instance_valid(object):
		print('NOT VALID')
	else:
		print('Still valid')
	pass
```

The result:
```
2020-07-06 00:32:58.432590+0300 test app[21618:7528188] [Node:1150]
2020-07-06 00:32:58.432615+0300 test app[21618:7528188] [Node:1150]
2020-07-06 00:32:58.432624+0300 test app[21618:7528188] Still valid
2020-07-06 00:32:58.558998+0300 test app[21618:7528188] NOT VALID
```

Switching `queue_free` to `free` results in:
```
2020-07-06 00:33:51.073598+0300 test app[21627:7528974] [Node:1150]
2020-07-06 00:33:51.073626+0300 test app[21627:7528974] [Deleted Object]
2020-07-06 00:33:51.073635+0300 test app[21627:7528974] NOT VALID
2020-07-06 00:33:51.198720+0300 test app[21627:7528974] NOT VALID
```

Both `release` and `debug` give the same results.

**Comment by akien-mga** [comment] 2020-07-06 06:05
@naithar These results seem correct to me. When using `queue_free()`, the node won't be freed right away so it's still valid in the current frame/function call.

**Comment by HEAVYPOLY** [comment] 2020-07-06 06:18
It turns out I was looping through a group that contained node and their children and queue_free()ing, which I think was causing the crash.  When I removed the children from the group, it deleted properly.  I'm still not sure why it worked on Desktop but crashed on iOS though

**Comment by Calinou** [comment] 2022-08-30 20:18
@HEAVYPOLY Can you (or anyone else) still reproduce this bug in [Godot 3.5](https://godotengine.org/article/godot-3-5-cant-stop-wont-stop) or any later release?

If yes, please ensure that an up-to-date Minimal Reproduction Project (MRP) is included in this report (a MRP is a zipped Godot project with the minimal elements necessary to reliably trigger the bug). You can upload ZIP files in an issue comment with a drag and drop.

**Comment by HEAVYPOLY** [comment] 2022-08-30 20:22
I haven't been seeing this any more with 3.5

**Comment by Calinou** [comment] 2022-09-20 15:19
> I haven't been seeing this any more with 3.5

Thanks for checking :slightly_smiling_face: Closing then.

**Closed by Calinou** 2022-09-20 15:19 UTC
Labels: bug, platform:ios, topic:core
