### ISSUE TITLE
PascalCase default node naming discrepancy between godot 3 and godot 4

### ISSUE THREAD

**Issue by setepenre** [godotengine/godot#66875] opened 2022-10-04 12:25 UTC
### Godot version

4.0.beta2

### System information

linux

### Issue description

godot 3 and godot 4 display different behavior regarding default node naming using PascalCase: godot 3 takes the class name as the default node name while godot 4 transforms the class name using a PascalCase function ; this result in different names for nodes having class name ending in 2D or 3D between godot 3 and godot 4.
For example in godot 3 the default name for a Node3D is Node3D while in godot 4 the default name for a Node3D is Node3d.
Is this a desired result?

### Steps to reproduce

- Create a new node having a class name ending in 2D or 3D

**Comment by Zireael07** [comment] 2022-10-04 12:54
It's a bug, Duplicate of https://github.com/godotengine/godot/issues/65803

**Comment by Chaosus** [comment] 2022-10-04 13:07
Duplicate of #65803

**Closed by Chaosus** 2022-10-04 13:07 UTC
Labels: bug, topic:editor, usability
