### ISSUE TITLE
Godot 4.0 crashes on Linux Mint when selecting "Import"

### ISSUE THREAD

**Issue by AntonioNero** [godotengine/godot#65474] opened 2022-09-07 13:35 UTC
### Godot version

4.0 alpha 15

### System information

Linux Mint 20.3 Cinnamon 64 bit

### Issue description

Testing Godot 4.0 alpha 15 on Linux Mint Cinnamon 64 bit. It crashes after clicking on "Import" option and clicking on "Browse", then the program freezes and then closes. No project selection is possible. It happens with both the 64 bit and 32 bit versions of Godot.

### Steps to reproduce

Clicking "Import" then "Browse".

**Comment by cagibi-dev** [comment] 2022-09-07 15:07
No crash on Linux Mint 20.3 *xfce* 64 bit (both on single- and multiple-window mode), so this looks like a desktop environment issue.

**Comment by AntonioNero** [comment] 2022-09-07 16:23
Thank you for your reply. OK, keeping in account this is my own problem, I'll try to find a solution.

**Comment by Calinou** [comment] 2022-09-07 16:32
Can you reproduce this when using the `--single-window` command line argument?

**Comment by AntonioNero** [comment] 2022-09-07 17:04
System:    Kernel: 5.4.0-125-generic x86_64 bits: 64 compiler: gcc v: 9.4.0 
           Desktop: Cinnamon 5.2.7 wm: muffin dm: LightDM Distro: Linux Mint 20.3 Una 
           base: Ubuntu 20.04 focal 
Machine:   Type: Laptop System: SAMSUNG product: 305V4A/305V5A v: 04PW serial: <filter> Chassis: 
           type: 9 serial: <filter> 
           Mobo: SAMSUNG model: 305V4A/305V4A v: 04PW serial: <filter> BIOS: American Megatrends 
           v: 04PW.ME99.20110908.SKK date: 09/08/2011 
CPU:       Topology: Quad Core model: AMD A6-3410MX APU with Radeon HD Graphics bits: 64 type: MCP 
           arch: Fusion L2 cache: 4096 KiB 
           flags: lm nx pae sse sse2 sse3 sse4a svm bogomips: 12777 
           Speed: 973 MHz min/max: 800/1600 MHz Core speeds (MHz): 1: 981 2: 847 3: 990 4: 987 
Graphics:  Device-1: AMD Sumo [Radeon HD 6520G] vendor: Samsung Co driver: radeon v: kernel 
           bus ID: 00:01.0 chip ID: 1002:9647 
           Device-2: AMD Seymour [Radeon HD 6400M/7400M Series] vendor: Samsung Co driver: radeon 
           v: kernel bus ID: 02:00.0 chip ID: 1002:6760 
           Display: x11 server: X.Org 1.20.13 driver: ati,radeon unloaded: fbdev,modesetting,vesa 
           resolution: 1366x768~60Hz 

***

./Godot_v4.0-alpha15_linux.x86_64
Godot Engine v4.0.alpha15.official.432b25d36 - https://godotengine.org
Vulkan API 1.2.131 - Using Vulkan Device #0: Unknown - llvmpipe (LLVM 12.0.0, 128 bits)
WARNING: lavapipe is not a conformant vulkan implementation, testing use only.
/lib/x86_64-linux-gnu/libasound.so.2: undefined symbol: snd_dlpath
 
Segmentation fault (core dumped)

***

This happens when I try to create a new project without clicking on "Browse":

/lib/x86_64-linux-gnu/libasound.so.2: undefined symbol: snd_dlpath
 
WARNING: Blend file import is enabled in the project settings, but no Blender path is configured in the editor settings. Blend files will not be imported.
     at: _editor_init (modules/gltf/register_types.cpp:75)
WARNING: FBX file import is enabled in the project settings, but no FBX2glTF path is configured in the editor settings. FBX files will not be imported.
     at: _editor_init (modules/gltf/register_types.cpp:99)

***

I hope I gave you some useful info.

**Comment by Calinou** [comment] 2022-10-12 22:54
Duplicate of https://github.com/godotengine/godot/issues/58903. Note that your graphics card has no Vulkan support, so you'll have to use the OpenGL renderer as I explained in https://github.com/godotengine/godot/issues/58903#issuecomment-1276812163.

**Closed by Calinou** 2022-10-12 22:54 UTC
Labels: bug, platform:linuxbsd, topic:editor, needs testing, crash
