### ISSUE TITLE
Unable to set cursor caret to start of a wrapped line using the mouse.

### ISSUE THREAD

**Issue by larry-fuqua** [godotengine/godot#91121] opened 2024-04-24 17:58 UTC
### Tested versions

- Reproducible in: v4.2.1.stable.mono.official [b09f793f5] and v4.3.dev5.mono.official [89f70e98d]
- Not sure if it was not reproducible in any older versions

### System information

Godot v4.3.dev5.mono - Windows 10.0.19045 - Vulkan (Forward+) - dedicated GeForce GTX 870M () - Intel(R) Core(TM) i7-4710HQ CPU @ 2.50GHz (8 Threads)

### Issue description

Can't use the mouse to left-click and position the edit cursor/selection caret at the front of a new line that was formed from wrapping text. Should be able to click to the left of the center of the first character of word wrapped lines to position or selection from the start of the line.

### Steps to reproduce

When working with a TextEdit with word wrap on, and with text that has word-wrapped to multiple lines, try left-clicking with the mouse to position the cursor into the front position of each line.  This should be doable by clicking anywhere to the left side of the starting character on the line.  On the first line, the caret position appropriately sets at the front of the line.  For any subsequent wrapped line, it positions the cursor after the first character.  You can use keyboard arrow keys to move to the correct position.  Also, if you left-click with the mouse at the end of a line that wraps, it will correctly position the caret to the start of the next line.  You just can't directly click there as would be expected.  This also means you can't select from the start of the line in a natural manner.  You have to start selecting from the end of the line above.

### Minimal reproduction project (MRP)

[TextEdit_MouseCursor.zip](https://github.com/godotengine/godot/files/15098496/TextEdit_MouseCursor.zip)

**Comment by AThousandShips** [comment] 2024-04-24 18:30
Can you please try in 4.2.2?

**Comment by kitbdev** [comment] 2024-05-15 01:46
- duplicate of https://github.com/godotengine/godot/issues/88632

**Closed** 2024-05-15 06:37 UTC
Labels: bug, topic:gui
