### ISSUE TITLE
Cannot export to iOS (library not found for -ld_classic)

### ISSUE THREAD

**Issue by vgwyn** [godotengine/godot#83111] opened 2023-10-10 16:02 UTC
### Godot version

4.1.2 Stable

### System information

macOS Monterey 12.7

### Issue description

Every time I try to export an iOS project, even with a barebones project, it fails. I get the following message:

```
ld: library not found for -ld_classic
clang: error: linker command failed with exit code 1 (use -v to see invocation)

** ARCHIVE FAILED **


The following build commands failed:
	Ld /Users/username/Library/Developer/Xcode/DerivedData/projectname-hdphcazbnkplspfhlweigxlryrdb/Build/Intermediates.noindex/ArchiveIntermediates/projectname/InstallationBuildProductsLocation/Applications/projectname.app/projectname normal (in target 'projectname' from project 'projectname')
(1 failure)
```

I'm on an Intel Mac and I'm using Xcode 14.2. 

### Steps to reproduce

1. Start a new Godot project
2. Godot > Project > Export...
3. Create an iOS export
4. Add your App Store Team ID
5. Export Project

### Minimal reproduction project

N/A

**Comment by akien-mga** [comment] 2023-10-10 18:04
- Duplicate of #83085.

For now you would need to either upgrade to Xcode 15, or edit the `project.pbxproj` file in the export template to remove `-ld_classic`.

**Closed by akien-mga** 2023-10-10 18:04 UTC
Labels: bug, platform:ios, needs testing, topic:export
