### ISSUE TITLE
Deleting an opened script crashes the editor.

### ISSUE THREAD

**Issue by rambda** [godotengine/godot#72169] opened 2023-01-27 10:35 UTC
### Godot version

4.0.beta13, 4.0.beta14

### System information

Windows 10, Forward+

### Issue description

Open a GDScript, delete it, the editor crashes. It will also crash if it's a C# script opened with VSCode.
As I remember, it won't crash in 4.0.beta12, but I'm not super sure.

### Steps to reproduce

same as above.

### Minimal reproduction project

N/A. Not related to code. Just create a new project.

**Comment by Chaosus** [comment] 2023-01-27 10:51
Duplicate of https://github.com/godotengine/godot/issues/71713, fixed in beta 15

**Closed by Chaosus** 2023-01-27 10:51 UTC
