### ISSUE TITLE
class_name with same name as "extends" breaks the project

### ISSUE THREAD

**Issue by aliasbody** [godotengine/godot#32312] opened 2019-09-24 16:53 UTC
**Godot version:**
v3.1.1.stable.official

**OS/device including version:**
macOS Mojave v10.14.6

**Issue description:**
When we create a new project with a KinematicBody (I think it doesn't matter the type but this is the one I had at first that created the issue), and we associate a script to it to then set a class_name with the same name as the extended object (in this case, KinematicBody) as soon as we save (CMD + S) the project freezes and never goes from that state, and if we force close it doesn't open again (with the CPU running at 100%)

**Steps to reproduce:**
1. Create a new project
2. Add a new scene (3D Scene for example)
3. Add a node to it (KinematicBody)
4. Add a new script to that node (with the default params)
5. Just below the `extends KinematicBody` line add a new line `class_name KinematicBody`

**Additional notes**
The only way to solve this is by resetting `_global_script_classes` and `_global_script_class_icons` variables in the project.godot file.

**Comment by KoBeWi** [comment] 2019-09-24 17:12
Duplicate of #25339

**Closed by KoBeWi** 2019-09-24 17:12 UTC
