### ISSUE TITLE
interpolate_property's easing is not linear

### ISSUE THREAD

**Issue by girng** [godotengine/godot#21818] opened 2018-09-06 21:31 UTC
latest master 3.1

can't replicate this on 3.06, but does happen on 3.1.
```
tween_node.interpolate_property(hotkey, "value", 100, 0, 1000, 0, 0)
```

will make the transition go super fast right at the end, linear doesn't seem to be working correctly for tweens
```
enum  TransitionType:
TRANS_LINEAR = The animation is interpolated linearly.
```

edit: i tried playback process mode with physics mode, and Idle, still same

**Comment by DualMatrix** [comment] 2018-09-23 17:04
Created a quick test script to test this in the current master:

```
extends ProgressBar

var time = [0,0,0,0,0,0,0,0,0,0]

func _ready():
	$Tween.interpolate_property(self, "value", 100, 0, 1000, 0, 0)
	$Tween.start()

func _physics_process(delta):
	time[floor(value / 10)] += delta

func _on_Tween_tween_completed(object, key):
	print(time)
```

Which gave me 
`[100.033339, 100.016672, 100.033339, 100.016672, 100.033339, 100.016672, 100.033339, 100.016672, 100.016672, 99.983339]` 
As values which doesn't seem to indicate any noticeable speedup near the end.

**Comment by groud** [comment] 2018-09-23 17:09
@girng please provide an example project reproducing the bug.

**Comment by girng** [comment] 2018-09-23 17:47
i already did it's in that other thread.
one sec let me find it plz

**Comment by girng** [comment] 2018-09-23 17:50
@groud  found it
https://github.com/godotengine/godot/issues/21923#issuecomment-421745885

it shows the transition is not linear, and snaps at the end, and glitches out.

**Comment by DualMatrix** [comment] 2018-09-23 18:06
This ended not being a tweening issue. It's still linear.

**Comment by girng** [comment] 2018-09-23 18:07
yeah, @akien-mga can we move to #21923

**Comment by mhilbrunner** [comment] 2018-09-23 18:12
Closing this, as the issue seems to be #21923

**Closed by mhilbrunner** 2018-09-23 18:12 UTC
Labels: bug, topic:core
