### ISSUE TITLE
Downleft corners of font in editor are invisible

### ISSUE THREAD

**Issue by Kasperejros** [godotengine/godot#87647] opened 2024-01-27 15:05 UTC
### Tested versions

- Reproducible in 4.2.1.stable and 4.1.2.stable. Not seen in any of Godot3 versions.

### System information

Windows 11  Godot 4.2.1 Intel UHD620 Intel i5 7th gen. Drivers Intel VGA Driver 21.20.16.4821. Windows is as up to date as possible.

### Issue description

After running Godot 4.2.1 (or 4.1.2) in Windows 11 on Intel UHD620 fonts in editor are cut in half diagonally. Changing renderer to opengl3 via startup line and changing language, resoultion, font zoom and so on in windows is not fixing the issue.

![image](https://github.com/godotengine/godot/assets/9154690/7508472d-dc03-4b9e-be97-0056b8312ad9)

### Steps to reproduce

Run godot 4.2.1 on Lenovo Ideapad 710s on windows11 with Intel VGA Driver 21.20.16.4821 drivers.

### Minimal reproduction project (MRP)

N/A as this starts way before running any projects

**Comment by kleonc** [comment] 2024-01-27 15:41
Closing as duplicate of #79955.

**Closed by kleonc** 2024-01-27 15:41 UTC
