### ISSUE TITLE
Lag when directly setting the position of a sprite in 4.0 with vsync

### ISSUE THREAD

**Issue by RhyminGarfunkle** [godotengine/godot#74875] opened 2023-03-13 18:56 UTC
### Godot version

4.0.stable

### System information

Windows 10

### Issue description

When any form of vsync is enabled, there is a small but noticeable lag when directly setting the position of a sprite. This is greater than the normal lag/latency expected with vsync, and is not present in 3.5 when vsync is enabled, when using physics functions to move nodes in 4.0, or when vsync is disabled in 4.0. Multiple users on different systems have reported this behavior, see the last few posts in [this thread](https://godotforums.org/d/33093-fast-input-and-smooth-graphics/6).

### Steps to reproduce

Load and run the attached project, press space to make the icon jump. Notice the difference in response time when vsync is disabled, vs any form of vsync enabled.

### Minimal reproduction project

[1678525216-38166-jumplag.zip](https://github.com/godotengine/godot/files/10960755/1678525216-38166-jumplag.zip)

**Comment by Calinou** [comment] 2023-03-13 19:08
This may hint at Godot using triple buffered V-Sync in 4.0, but double-buffered V-Sync in 3.x.

**Comment by RhyminGarfunkle** [comment] 2023-05-19 21:48
This issue is still present in 4.0.3.

**Comment by rs-gh-asdf** [comment] 2023-09-25 16:02
I am able to replicate this issue. Is it possible that this is related to #80550? My setup is:

 - Linux 6.2.0
 - X11 (Xfwm with display compositing enabled)
 - Ubuntu 23.04
 - Nvidia drivers 535 (latest)
 - GeForce RTX 4090
 - AMD Ryzen 9 7950X
 - Forward+ renderer
 - Vulkan API 1.3.242
 - Godot 4.1.1

I was able to resolve this issue by either:

 1. Switching to the Compatibility renderer from Forward+
 2. Disabling V-Sync

I was not able to reproduce the issue by:

 1. Exporting a release version of the project (not debug)
 2. Disabling display compositing in my window manager

I ran into this issue while following along to chapter 2 of the Godot book by Chris Bradfield published by packt.

**Comment by rs-gh-asdf** [comment] 2023-09-25 16:28
Forgot to attach my videos:

Uploading debug without vsync-2023-09-25_08.56.10.mp4…

https://github.com/godotengine/godot/assets/105696616/4c6c7427-a0fb-4f56-8dc8-5d4e402448a5

**Comment by Calinou** [comment] 2023-09-25 16:35
> Is it possible that this is related to https://github.com/godotengine/godot/issues/80550?

[Test](https://docs.godotengine.org/en/latest/contributing/workflow/testing_pull_requests.html) https://github.com/godotengine/godot/pull/80566 to make sure :slightly_smiling_face:

**Comment by rs-gh-asdf** [comment] 2023-09-28 14:29
Hello @Calinou, thank you for your response. I am happy to report that #80566 does in fact fix this issue on my machine! I think that this issue can be closed in reference to that pull request.

This is only tangentially related, but for some reason none of the Github Action-built images worked on my system. They complained about either a missing Mono dependency or a missing pck file. However, the manual compilation instructions were very straightforward and worked flawlessly. A huge part of my day-job is compiling random software from Github, and Godot's compilation is one of the best that I have experienced. You guys have really done a great job there.

**Comment by Calinou** [comment] 2023-09-28 16:41
> This is only tangentially related, but for some reason none of the Github Action-built images worked on my system. They complained about either a missing Mono dependency or a missing pck file.

The builds require a .NET installation as we don't have enough CI resources to create both Mono and non-Mono builds at the same time.

**Closed** 2023-09-28 16:42 UTC
Labels: discussion, topic:rendering
