### ISSUE TITLE
[4.0] Tab key does not cycle trought input fields

### ISSUE THREAD

**Issue by Norrox** [godotengine/godot#56401] opened 2022-01-01 15:28 UTC
### Godot version

v4.0.dev.custom_build [91b97dac0]

### System information

Windows 10, 1080 Ti, Vulkan

### Issue description

Tab key does not cycle trought input fields
![Skärmbild 2022-01-01 162945](https://user-images.githubusercontent.com/13393087/147854041-6d4cfee4-52b4-4de4-b1e6-d084d06497dc.png)

### Steps to reproduce

Press tab while in an input field

**Comment by Calinou** [comment] 2022-01-01 17:52
Duplicate of https://github.com/godotengine/godot/issues/54602.

**Closed by Calinou** 2022-01-01 17:52 UTC
