### ISSUE TITLE
Particle ShaderMaterial has double parameters category if many parameters are defined

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#65862] opened 2022-09-16 01:17 UTC
### Godot version

c2babb6

### System information

Windows 10 x64

### Issue description

![godot_DH7huRptgL](https://user-images.githubusercontent.com/2223172/190535605-4ac83342-8e79-414d-93ab-6592ca5bd7d0.gif)
Not sure if related to particular parameters or just parameter count in general.

### Steps to reproduce

1. Add GPUParticles node
2. Add process material (default)
3. Change some properties. In my case it was: emission sphere radius, linear velocity, spread and color ramp
4. Convert it to ShaderMaterial

**Comment by clayjohn** [comment] 2022-09-16 01:20
Duplicate of https://github.com/godotengine/godot/issues/65858 this seems to be an issue with all ShaderMaterials

**Closed by clayjohn** 2022-09-16 01:20 UTC
Labels: bug, topic:editor, topic:shaders
