### ISSUE TITLE
High Frame time

### ISSUE THREAD

**Issue by udit** [godotengine/godot#37455] opened 2020-03-31 06:38 UTC
**Godot version:** 3.2.1

**OS/device including version:** Windows 10

**Issue description:** I am creating a system of planets where each planet is a `RigidBody2D` with a child `Area2D` which exerts gravity on any other planet in its area.

When I have 130 planet nodes, simulation runs smoothly at 60 FPS, but when I add just 10 more nodes, FPS suddenly drops down to 6-7 FPS. Since each planet influences every other planet with it's gravity, I thought physics might be taking too long as adding even a few more planets would exponentially increase the calculations.

But checking the profiler, physics time was averaging at just 21ms, but the frame time was still averaging at 150ms. I am unable to figure what is causing high frame time as it doesn't add up.

![profiler](https://user-images.githubusercontent.com/6249061/77992590-fe058880-7343-11ea-803c-73b60a6785d8.PNG)

**Minimal reproduction project:**
[GravityBug.zip](https://github.com/godotengine/godot/files/4407063/GravityBug.zip)

**Comment by Calinou** [comment] 2020-06-13 10:24
Duplicate of #23715.

**Closed by Calinou** 2020-06-13 10:24 UTC
Labels: bug, needs testing, topic:physics
