### ISSUE TITLE
Large idle times (>95% of frame time) when using Godot's drag-and-drop built-in functions

### ISSUE THREAD

**Issue by zoisus** [godotengine/godot#57039] opened 2022-01-21 15:00 UTC
### Godot version

3.4.2 Stable

### System information

OS: Windows 10,PROCESSOR: 8x Intel(R) Core i7-6700 CPU @3.4GHz, Graphics card: NVIDIA GeForce GTX 1070,

### Issue description

When I drag and drop items using godot's built in functions (get_drag_data, can_drop_data and drop_data), the idle time per frame is too high and results in big lag spikes. At first, it is smooth and the longer I drag an item, the choppier it gets. The dragging should stay smooth all throughout.

For a detailed post, see https://www.reddit.com/r/godot/comments/s981js/huge_idle_times_when_using_godots_builtin/

### Steps to reproduce

Reproducible 100% of the time on my computer.

Create a control node, with 2 textureRect children (one of them is just for the background, the other is an image of whatever)
attach script to the image and use the following code:

```gdscript
extends TextureRect

var non = TextureButton.new()

func get_drag_data(position):
	var data = {}
	data["oui"] = "plop"
	data["ok"] = non
	var drag_texture = TextureRect.new()
	drag_texture.expand = true
	drag_texture.texture = texture
	drag_texture.rect_size = Vector2(100,100)
	var control = Control.new()
	control.add_child(drag_texture)
	drag_texture.rect_position = -0.5 * drag_texture.rect_size
	set_drag_preview(control)
	return data

func can_drop_data(position, data):
	return false

func drop_data(position, data):
	pass
```

Run the project using this scene as the root, and drag the image for a few seconds. The longer you drag, the choppier the preview gets and the mode idle time can be observed in the debugger

### Minimal reproduction project

[drag drop test.zip](https://github.com/godotengine/godot/files/7914586/drag.drop.test.zip)

**Comment by Calinou** [comment] 2022-01-21 16:51
@zoisus Please surround large blocks of text with triple backticks like this:

```
text here
```

This prevents them from taking too much space and also makes sure issue references aren't accidentally created. I edited your comment, but remember to do this next time :slightly_smiling_face:

**Comment by sairam4123** [comment] 2022-01-25 17:45
Can't confirm, tested on 3.4.2 official build.

**Comment by Calinou** [comment] 2022-01-25 18:15
> Can't confirm, tested on 3.4.2 official build.

Which operating system did you test this on? I didn't test this locally yet, but this may be OS-specific.

**Comment by sairam4123** [comment] 2022-01-25 18:22
Tested on Windows 11

**Comment by tufduckhotmailcom** [comment] 2022-07-03 06:59
I'm having the same problem as well in my own project. I'm dragging a PanelContainer around and it's really choppy/jerky/laggy.

I downloaded your test project and can confirm, it happens there as well.

I'm using Godot 3.5 rc4. I'm on Windows 10, nVidia RTX 3070.

**Comment by tufduckhotmailcom** [comment] 2022-07-03 07:26
If it's of any help, I'd like to add that while you are dragging, the mouse cursor is constantly flickering between the regular arrow cursor and the red "drop-not-allowed" icon. This happens for me whether I use set_drag_preview or not.

```
# Insert this into a script attached to whatever control node,
and start dragging that node. Mouse cursor will switch back
and forth between arrow and no parking sign all the time
while you're moving the mouse. 
func get_drag_data(position: Vector2):
	var data = {}
	return data
```

**Comment by tufduckhotmailcom** [comment] 2022-07-03 07:47
I have investigated this a bit more. It's on **Godot version 3.4 the issue has started**. I tried version 3.3.4, 3.3 and 3.2 and the dragging is butter smooth there. And on 3.4, 3.4.1, 3.4.2, 3.4.3, 3.4.4 and 3.5 (I tried them all), the dragging is choppy, just like the OP (and myself) experienced. 

I've scanned through the 3.4 change log in order to see if there's some change according to drag and drop that can be the cause of this, and found this that may or may not be of some help:

`Prevent accidental drags by adding drag distance threshold`

`Removing bounding box calculations from 3D scene drag and drop and collide against physics rather than visual geometry.`

`Fix EditorPropertyEasing capturing drag events originated outside of it`

Any devs looking into this?

**Comment by Calinou** [comment] 2022-07-03 18:16
@tufduckhotmailcom Can you try all 3.4 betas and RCs to give us a more precise idea of when the regression started?

**Comment by tufduckhotmailcom** [comment] 2022-07-03 20:37
@Calinou Sure, no problem! I'm just glad I can be of some help. So, I've done what you said and tried all the versions. Here you go:

3.4 beta 1 = smooth
3.4 beta 2 = smooth
3.4 beta 3 = smooth
3.4 beta 4 = choppy !   <= found it!
3.4 beta 5 = choppy
3.4 beta 6 = choppy
3.4 rc1 = choppy
3.4 rc2 = choppy
3.4 rc3 = choppy

**Comment by akien-mga** [comment] 2022-07-03 22:04
Possibly another consequence of #55037 where input event accumulation was mistakenly turned off.

Could you add `Input.use_accumulated_input = true` in e.g. `_ready()` of your main scene and see if that fixes the issue?

**Comment by akien-mga** [comment] 2022-07-04 20:00
Thanks, closing as duplicate of #55037 then (same cause).

**Closed by akien-mga** 2022-07-04 20:00 UTC
Labels: confirmed, documentation, regression, topic:gui, performance
