### ISSUE TITLE
Editor does not lose keyboard focus on linux X11 (DisplayServer regression)

### ISSUE THREAD

**Issue by Abdul-AZ** [godotengine/godot#68572] opened 2022-11-12 18:12 UTC
### Godot version

4.0 Dev Latest (c17f17eb98)

### System information

Archlinux 6.0.8-arch1-1 kernal, X11, Qtile

### Issue description

I am Unable to type in other windows when the editor is running, keyboard events are consumed by the editor instead of the other (properly) focused window. I would guess that Godot is not dealing with the window focus lost event properly.

I am running an X11 session on arch linux and using the Qtile window manager. This could be a window manager issue but it seems to only happen on Godot 4. Here is the issue displayed in a gif.

![editor_keyboard_focus_bug](https://user-images.githubusercontent.com/30045609/201488256-a9c3ec75-2af1-4c18-9dae-69e961c1c65f.gif)

This happens in the editor also, not just the startup window. I tried reproducing with Godot 3.5.1 and I was not able to I am getting the expected behavior here.
![editor_keyboard_focus_godot3](https://user-images.githubusercontent.com/30045609/201488285-acaf84de-a080-4032-a1a9-8a0cec57c96c.gif)

### Steps to reproduce

Run Godot 4 with a similar setup and try to use your keyboard on other windows when selecting a input field in godot.

**Comment by Calinou** [comment] 2022-11-12 18:23
Can you reproduce this if you start the project manager with the `--single-window` command line argument?

**Comment by Abdul-AZ** [comment] 2022-11-12 18:38
Yea still happens with `--single-window`

**Comment by Abdul-AZ** [comment] 2022-11-12 20:30
I was not able to reproduce this under KDE plasma even after I used the "Focus follows mouse" option (which should treat window focus similar to Qtile). 
I also was not able to reproduce this on the i3 window manager.

Which leads me to think this is a Qtile issue and not a Godot issue and it just happened to work fine with Godot 3 but I am not exactly sure. Any thoughts on this?

**Comment by radlotus** [comment] 2022-11-12 21:10
Just installed Qtile and I am having the exact same issue happening. It is tied to Qtile.

**Comment by gitacrobat** [comment] 2023-01-11 09:28
As I mentioned in the qtile issue I don't think it is a qtile issue, as I am having a similar problem with xmonad, i.e. the godot4 window hijacking input focus.

**Comment by lihop** [comment] 2023-01-14 21:10
I agree with @gitacrobat. This seems similar to issue #68305 that occurs with XMonad.

**Comment by Calinou** [comment] 2023-01-15 19:30
Duplicate of https://github.com/godotengine/godot/issues/68305 (same cause).

**Closed by Calinou** 2023-01-15 19:30 UTC
Labels: bug, platform:linuxbsd, topic:porting, needs testing, regression
