### ISSUE TITLE
Godot crashing upon startup

### ISSUE THREAD

**Issue by m1233** [godotengine/godot#19466] opened 2018-06-09 15:28 UTC
For me, Godot worked fine for 3 days. Since the fourth day everytime i open it, i wait a bit and after that the loading screen fades and Godot crashes. I use Godot version 3.0.2 for windows 10 64 bit and i believe its a shame that i cant use such a great engine :(

Btw i have an intergrated Intel hd 510 graphics card

**Comment by volzhs** [comment] 2018-06-09 15:31
can you share the problematic project?
no one can do much about it without more detail information or reproducible project, I guess.

**Comment by m1233** [comment] 2018-06-09 17:49
I dont have a problematic project. Actually i havent done any projects on it because i didnt have the time but now that i do it doesnt work. I tried to re-install the program but that didnt solve the issue

**Comment by vnen** [comment] 2018-06-09 18:39
So this crashes on the project manager? You can try starting it from the command prompt and see if there's any message. You can also try to delete your settings from `%APPDATA%\Godot`. Maybe you can try running the [3.0.3 release candidate](https://godotengine.org/article/dev-snapshot-godot-3-0-3-rc-3) as well.

**Comment by akien-mga** [comment] 2018-06-09 18:42
You may check that your GPU drivers are still properly installed. Windows 10 likes to break them at every other system update.

**Comment by m1233** [comment] 2018-06-10 16:19
ok without doing anything godot suddenly works just fine. Anyway thanks a lot for the help! I can finnaly start creating some games :)

**Comment by vnen** [comment] 2018-06-10 16:44
Probably some mishap in the system. Closing as it's not a bug.

**Closed by vnen** 2018-06-10 16:44 UTC
