### ISSUE TITLE
Add zoom in tileset->tile selector within TileMap

### ISSUE THREAD

**Issue by olsonjeffery** [godotengine/godot#4647] opened 2016-05-13 11:31 UTC
**Operating system or device - Godot version:**
OSX El Capitan

**Issue description** (what happened, and what was expected):
I'm working with a relatively small tileset (16x16 tiles), so after setting up a tileset as per the "Using tilemaps" tutorial, I found that it was hard to pick correctly my list of tiles if they all look similar (and the naming doesn't help a lot when your tilesheet has 64*64 tiles).

The ability to zoom or change the size of the tile thumbnails would be incredibly helpful for me in this case.

**Steps to reproduce:**
1. Build a tileset from a tilesheet with 16x16 tiles
2. Add that tileset into a TileMap node
3. Have fun distinguishing between various, subtly different wall tiles :)

**Link to minimal example project** (optional but very welcome):
N/A

Here's an idea of the challenge:

![screen shot 2016-05-13 at 6 30 34 am](https://cloud.githubusercontent.com/assets/10408/15246656/3b705264-18d4-11e6-8d94-d25349e5f71d.png)

**Comment by akien-mga** [comment] 2016-05-13 11:50
Duplicate of #4412.

**Closed by akien-mga** 2016-05-13 11:50 UTC
