### ISSUE TITLE
Full screen issue with landscape/portrait dual monitors

### ISSUE THREAD

**Issue by profjle** [godotengine/godot#44028] opened 2020-12-02 03:50 UTC
**Godot version:**
Godot Engine v3.2.3

**OS/device including version:**
Windows 10 Pro

**Issue description:**
Image of issue: https://imgur.com/za6I0DO
![image](https://user-images.githubusercontent.com/8281454/100827116-570f5880-349f-11eb-85a1-d91249704100.png)

I'm enabling the full screen option in project settings and get this when launching the game. I know that the cause is my secondary monitor which is on portrait mode and for some reason it full screens to that res/orientation. I'm not even working on that one which is making it very strange. I'm doing all my Godot work on the main/landscape monitor.

**Steps to reproduce:**
As far as my setup/windows settings go, I have the landscape monitor as my main and the portrait (using portrait flipped option) monitor as my secondary. Portrait monitor is right of the landscape/main monitor. 

Run the game full screen on main/landscape monitor and this will reproduce the issue. This happens on both exports and editor playing of the game. 

**Minimal reproduction project:**
Honestly, only need to turn on full screen with the mentioned above settings and it should happen but I am creating a project just to be safe. I indeed also tested it with this clean project. 
[FullScreenBug.zip](https://github.com/godotengine/godot/files/5626848/FullScreenBug.zip)

_bug squad edit : added image directly on OP_

**Comment by Calinou** [comment] 2020-12-02 14:32
As a workaround, you can control which monitor the project window appears on in **Editor Settings > Game Window Placement**.

**Comment by profjle** [comment] 2020-12-02 17:25
> As a workaround, you can control which monitor the project window appears on in **Editor Settings > Run > Window Placement**. You can also choose the window geometry there (only effective if the project isn't configured to run in fullscreen in the Project Settings).

I just tried this and it works with Rect => Forced Maximum. Though (obviously since it's an editor setting) exporting the project would have the same issue still.

**Comment by Calinou** [comment] 2021-02-01 15:33
Duplicate of https://github.com/godotengine/godot/issues/21674 (same cause).

**Closed by Calinou** 2021-02-01 15:33 UTC
Labels: bug, platform:windows, topic:porting
