### ISSUE TITLE
TileSet Atlas

### ISSUE THREAD

**Issue by jonSP12** [godotengine/godot#61187] opened 2022-05-19 10:17 UTC
### Godot version

3.5 rc1

### System information

windows 10, GLS3

### Issue description

using a TileSet Atlas, turns the tileSheet into a JigSaw puzzle... making it impossible to use.
![tileAtlasJIGSAW](https://user-images.githubusercontent.com/77213594/169270581-6a5ff133-db3a-4d33-85bf-faac2250479e.gif)

#-----------//------------//----------------

![tileAtlas](https://user-images.githubusercontent.com/77213594/169270871-2202ca2a-07a6-4452-aeba-8cd9c9c38af7.png)

### Steps to reproduce

using a tileAtlas

**Comment by KoBeWi** [comment] 2022-05-19 12:43
This is a limitation of the old tile editor. It keeps tiles as a list, without any structure.
It's fixed in the new tile editor in 4.0.

**Comment by jonSP12** [comment] 2022-05-19 14:34
> This is a limitation of the old tile editor. It keeps tiles as a list, without any structure. It's fixed in the new tile editor in 4.0.

I know, but godot 4 still has some unfinished features, making unusable for me at the moment,
Ive been experimenting with 	"Tiled Map Importer for Godot 3", the problem i think is that it creates the same tile.png image multiple times on each difereent tileMap node

![tiled01](https://user-images.githubusercontent.com/77213594/169321807-56c8c46d-c8b5-4b32-8498-f216e10a5db5.png)

-------------//--------------//-

![tiled02](https://user-images.githubusercontent.com/77213594/169321888-1d803735-8e7b-4986-8016-91fb26393547.png)

**Comment by Calinou** [comment] 2022-05-19 20:15
> Ive been experimenting with "Tiled Map Importer for Godot 3", the problem i think is that it creates the same tile.png image multiple times on each difereent tileMap node

Please report issues related to the Tiled importer on its dedicated [repository](https://github.com/vnen/godot-tiled-importer), not here.

**Comment by golddotasksquestions** [comment] 2022-05-20 20:14
@jonSP12 
As a simple workaround, I would recommend to prepare the texture how you like to use it. So if you want the atlas tile panel to be 10 tiles wide, make sure to edit your texture in any graphics software to be only 10 tiles wide.

**Comment by KoBeWi** [comment] 2022-05-22 01:32
This is difficult to resolve properly without breaking compatibility. It can however be mitigated by using some hacks, like a special property in TileSet that forces constant column count. The issue is unlikely to be resolved though.

**Comment by jonSP12** [comment] 2022-05-23 12:27
> This is difficult to resolve properly without breaking compatibility. It can however be mitigated by using some hacks, like a special property in TileSet that forces constant column count. The issue is unlikely to be resolved though.

By compatibility you mean projects using the tileMap node would stop working ?
Couldnt it be done by added a new node tool ? the v4 tileMap, would look on godot 3

![tile2](https://user-images.githubusercontent.com/77213594/169819067-2492db93-d455-4116-8128-92a0a1fb8790.png)

**Comment by KoBeWi** [comment] 2022-05-23 12:47
> By "compatibility" you mean projects using the tileMap node would stop working ?

Yes.

> Couldnt it be done by adding a new node tool ? the v4 tileMap, would look on godot 3

The 4.0 tiles can't be backported, because they rely a lot on rendering changes. Also there is no need to make a separate class.

As I said, we could just add a property that forces constant number of columns in the editor. It's a hacky solution, but wouldn't break compatibility.

**Comment by kleonc** [comment] 2022-05-26 09:34
> This is difficult to resolve properly without breaking compatibility. It can however be mitigated by using some hacks, like a special property in TileSet that forces constant column count. The issue is unlikely to be resolved though.

There's no need to break compatibility anyhow, subtile count (to get the proper column count) can be calculated with already available `TileSet` methods. I think the only problematic part is that `ItemList` (used to show the subtiles in the editor) doesn't support horizontal scrolling. Meaning it would probably need to be nested into a `ScrollContainer` and that `ItemList`'s minimum size would need to be accordingly updated manually so it would have proper number of columns and so it won't show its own vertical scroll. I'll see if it's easily doable.

**Closed** 2024-09-29 19:22 UTC
Labels: enhancement, topic:editor, usability, topic:2d

**Comment by akien-mga** [comment] 2024-09-29 19:29
For the record, I closed this on behalf of the Code of Conduct team, as the OP was banned due to harassing contributors. They're restricted from further interacting so this issue cannot progress. If someone confirms that the issue is still reproducible, you can open a new issue.
