### ISSUE TITLE
Elements of subviewport can draw over editor GUI

### ISSUE THREAD

**Issue by Cybolic** [godotengine/godot#1840] opened 2015-05-06 21:12 UTC
As the title says:
![godot engine - viewportissue - editor_rendering_issue scn_005](https://cloud.githubusercontent.com/assets/1196197/7503744/910b39a2-f44d-11e4-9ca9-d71714dda39b.png)

Minimal project that displays the issue:
https://drive.google.com/file/d/0B2mB5cFTxznfdkJyTURvbzN0UnM/view?usp=sharing

Note: This happens in the current git version as well as for the past week or so - I can't say for before then.

**Comment by WatIsDeze** [comment] 2015-05-08 12:44
I've had this happen once before, but was never able to reproduce the situation myself. (Although as you can see in the screenshot, a small main window size seems related to this.)

**Comment by Cybolic** [comment] 2015-05-08 13:17
The window size in the screenshot was just to not have the image too big - it happens in maximised (1920x1200) as well.

**Comment by reduz** [comment] 2015-05-12 00:37
may it be it only happens when the window is too small?

**Comment by Cybolic** [comment] 2015-05-12 11:40
I think it's a broken state in the project. I haven't been able to reproduce it from scratch, but loading that project triggers it every time, regardless of window size.

**Comment by akien-mga** [comment] 2015-11-17 07:37
I can confirm the bug using the test project above, I guess it could be related to the custom viewport somehow?

**Comment by kopias** [comment] 2016-02-09 09:12
... just ran on this one while checking godot 2.0 rc1
and checking https://github.com/w84death/Tanks-of-Freedom using viewport feature
just open this game 'game.xscn' and zoom in so root node is bigger than 2d viewport to overlap some of editor ui 
![untitled](https://cloud.githubusercontent.com/assets/3462746/12911898/acc32a94-cf15-11e5-999f-a712ffaa50db.png)

**Comment by akien-mga** [comment] 2016-03-05 11:00
Would be nice to see a fix for this one :)

**Comment by trollworkout** [comment] 2016-04-17 19:17
yeah i still broken as of right now  . seems to be a zooming issue. the viewport  is always at default resolution and never zooms in like normal

**Comment by akien-mga** [comment] 2016-07-27 11:58
Not critical for the upcoming 2.1, so moving to the next milestone.

**Comment by akien-mga** [comment] 2016-09-20 03:15
Another example by @Hinsbart, from the Platformer split screen demo:

![viewport_bug](https://cloud.githubusercontent.com/assets/8281916/18650808/7fae7074-7ec7-11e6-9e1d-4fb635b0a66a.gif)

**Comment by razvanc-r** [comment] 2016-12-20 12:29
So this still hasn't been fixed in v2.1.1.1.1.1... but the other problem I'm seeing is that the `Viewport` node only uses the width & height of the parent `Control`, but not the position. So you can't place it anywhere in the scene, it will always be rendered from top left corner. This makes it rather useless. Can anyone give me pointers on where to start looking at the code for a potential fix? It's really annoying. If you want to create mini-views or controls around a `Viewport` area it's impossible because of this bug.

**Comment by reduz** [comment] 2016-12-20 12:33
This is fixed in 3.0

**Comment by razvanc-r** [comment] 2016-12-20 12:59
@reduz sure it is, but 3.0 is still km away, what if we're working on some projects now?... I need this for a mini-map scroll thing. Can the code from 3.0 be integrated in 2.1? I guess not because it's a new renderer?

Sure, there are probably workarounds, but seems that whenever you need a more specific or advanced feature you always end up doing some workaround... work :).

Hope to see less of this in 3.0! Nice works on the new rendering by the way, really looking forward to the new stuff :)

**Comment by reduz** [comment] 2016-12-20 13:02
no.. the problem is how viewport works in 2.0, it's not easy at all to fix

**Comment by razvanc-r** [comment] 2016-12-20 13:03
I see, well, then I suppose I need a workaround. Thanks!

**Comment by akien-mga** [comment] 2017-01-02 11:46
Closing as fixed in 3.0 then, it probably won't be fixed for 2.1.x since the commits can't be cherry-picked from master, the bug was fixed while refactoring it all.

**Closed by akien-mga** 2017-01-02 11:46 UTC
Labels: bug, confirmed, topic:editor, topic:rendering, usability
