### ISSUE TITLE
SDFGI no longer works with baked light.

### ISSUE THREAD

**Issue by yosoyfreeman** [godotengine/godot#88069] opened 2024-02-07 17:25 UTC
### Tested versions

Reproducible in 4.2.1 stable.

I can't remember the exact version in which this worked as intender, but it was around last year.

### System information

Fedora workstation

### Issue description

SDFGI was designed to be able to work with a LightmapGI node. In this case, the light map provides diffuse light while SDFGI provides reflections, specially for metallic objects. This worked extremely well so we built our workflow with it in mind.

Now that i started to test this method later on development again, i noticed that SDFGI no longer works as a reflection source for metallic objects while using baked light. Which results in pitch blacks metallic objects if they have low roughness. This is a hard blocker for us right now.

_**SDFGI**_:

![imagen](https://github.com/godotengine/godot/assets/64601424/f365801b-287b-4cf8-953c-126e25be6d2f)

_**light map with SDFGI**_ (No reflections at all):

![imagen](https://github.com/godotengine/godot/assets/64601424/6f438db5-460e-42f3-9ebd-52fe0ba3683b)

### Steps to reproduce

I sadly can not provide reproduction projects, light maps are heavy and my pc is slow. The illustrated image is a cube with an emissive material on the top. The ball is on the center. Is metallic and has 0 roughness. All objects are static.

Bake the light map and then activate SDFGI. instead of providing the lacking reflection from the lightmap, it remains pitch black.

### Minimal reproduction project (MRP)

My PC is too slow. If really necessary i will make multiple scenes and bake their light maps along the day.

**Comment by AThousandShips** [comment] 2024-02-07 17:27
Duplicate of?
* https://github.com/godotengine/godot/issues/87600

**Comment by Calinou** [comment] 2024-02-07 17:42
Thanks for the report! Consolidating in https://github.com/godotengine/godot/issues/87600 and https://github.com/godotengine/godot-proposals/issues/3012.

**Closed by Calinou** 2024-02-07 17:42 UTC
