### ISSUE TITLE
Project -> Open User Data Folder, disables Godot

### ISSUE THREAD

**Issue by TheYellowArchitect** [godotengine/godot#79245] opened 2023-07-09 16:51 UTC
### Godot version

4.1

### System information

Artix (Arch Linux)

### Issue description

When I click on 'Project -> Open User Data Folder', Godot opens with local file manager, the path [user://](https://docs.godotengine.org/en/latest/tutorials/io/data_paths.html#doc-data-paths)
However, I use dwm, and this somehow locks Godot, it does not reply with any input, mouse or keyboard. However, all the inputs are pressed together once I close the file manager window. So, if I open user data folder via Godot, then focus my window to Godot and press Ctrl+Shift+Q, nothing happens. But if I close the file manager, Godot then quits to project list :)

I use `lf` as my file manager. While my linux build is outdated, I first noticed this bug 2 months ago, but I didn't post it back then as I don't think it's important. I can just open the "user://" path manually with lf, an alias for example.

### Steps to reproduce

With dwm, open user data folder via Godot

**Comment by Calinou** [comment] 2023-07-09 16:58
Can you reproduce this when using another file manager, or another window manager?

**Comment by TheYellowArchitect** [comment] 2023-07-09 17:11
I have screen recording of this bug, but browser video players don't support the codec somehow, even if I ffmpeg convert it to mp4, so I upload the video elsewhere https://files.catbox.moe/1f79mf.mkv

>Can you reproduce this when using another file manager, or another window manager? It's not clear which one is the culprit here.

I cannot try these as I have tinkered a bit too much with my linux build these past weeks, and I cannot even use pacman -S hahaha
But this bug existed before I wrecked my configs and stuff, I guess someone else will have to confirm if its 'dwm' or 'lf'

**Comment by quinnyo** [comment] 2023-07-12 19:43
I think this is a duplicate of #49946.

**Comment by Calinou** [comment] 2023-07-12 19:46
Consolidating with https://github.com/godotengine/godot/issues/49946, as this is due to the same cause.

**Closed by Calinou** 2023-07-12 19:46 UTC
Labels: bug, platform:linuxbsd, topic:porting, needs testing
