### ISSUE TITLE
[WEB] 2D and Controls don't show in Beta 3

### ISSUE THREAD

**Issue by Henrique-Henrique** [godotengine/godot#67470] opened 2022-10-16 03:42 UTC
### Godot version

4.0.beta3

### System information

Web

### Issue description

Node2D and Control don't show on 4.0 beta 3 on the Web.
On windows work normally

Running the same project in both versions:

In Beta 2:
![image](https://user-images.githubusercontent.com/57235054/196016764-b73fa21e-3d03-4b86-a5a6-5958477f2f24.png)

In Beta 3:
![image](https://user-images.githubusercontent.com/57235054/196016770-f1739ae8-db8a-45d1-9733-f24af052d6de.png)

### Steps to reproduce

Just create a project and add some Node2D or Controls

**Comment by rburing** [comment] 2022-10-16 06:53
Duplicate of https://github.com/godotengine/godot/issues/67392, fixed by https://github.com/godotengine/godot/pull/67402, and hence will be fixed in the next beta.

**Closed by rburing** 2022-10-16 06:53 UTC
