### ISSUE TITLE
(Probably linux only) Crash when losing focus with "Save when focus is lost" option activated

### ISSUE THREAD

**Issue by Louis-Simon22** [godotengine/godot#75851] opened 2023-04-09 11:39 UTC
### Godot version

4.0.2.stable

### System information

Ubuntu 22.10

### Issue description

The "Save when focus is lost" option makes the engine crash on my system.

Here's the error
```
ERROR: Task 'save' already exists.
   at: add_task (editor/progress_dialog.cpp:177)
ERROR: Task 'save' already exists.
   at: add_task (editor/progress_dialog.cpp:177)
ERROR: Task 'save' already exists.
   at: add_task (editor/progress_dialog.cpp:177)
ERROR: Task 'save' already exists.
   at: add_task (editor/progress_dialog.cpp:177)
ERROR: Task 'save' already exists.
   at: add_task (editor/progress_dialog.cpp:177)
ERROR: Task 'save' already exists.
   at: add_task (editor/progress_dialog.cpp:177)
ERROR: Task 'save' already exists.

```

### Steps to reproduce

1. Create a new project
2. Creat a scene (so there's something to save)
3. Activate the "Save when focus is lost" setting in the Editor settings
4. Alt-tab to some other application
Engine crashes at this point

### Minimal reproduction project

N/A

**Comment by Rindbee** [comment] 2023-04-29 06:16
It is a duplicate of #73765.

**Comment by Calinou** [comment] 2023-05-21 22:50
- Duplicate of https://github.com/godotengine/godot/issues/73765.

**Closed by Calinou** 2023-05-21 22:50 UTC
