### ISSUE TITLE
Vulkan: Fog with aerial perspective is black

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#62407] opened 2022-06-25 19:50 UTC
### Godot version

21c79d75153733b84533957228d0c267ef340a80 (with float=64)

### System information

Windows 10 64 bits GLES3 GeForce GTX 1060 6GB/PCIe/SSE2

### Issue description

I have a scene with fog in it and also `aerial perspective` set to 1. It used to work fine in an older Godot 4 version, but with the linked commit fog is now black. I'm not sure if this is expected.

![image](https://user-images.githubusercontent.com/1311555/175788501-715e0ab6-48ca-4f4d-b64b-7135f90407c3.png)

It appears to work in Godot 4.0 alpha10 (which is an older version than this commit).

### Steps to reproduce

Create a 3D scene with a WorldEnvironment. Set sky mode to Sky, and add a PhysicalSky. Enable fog, and set aerial perspective to 1.

### Minimal reproduction project

[FogAerial.zip](https://github.com/godotengine/godot/files/8985464/FogAerial.zip)
This project has just a box and a fog setup with high density so we can see it become black quickly.

**Comment by Calinou** [comment] 2022-06-25 20:25
Possible regression from https://github.com/godotengine/godot/pull/61221. cc @BastiaanOlij

**Comment by jtnicholl** [comment] 2022-06-25 21:46
I think this is related to or is the same issue as #62404. I tested the minimal reproduction project with #62133 reverted and it looked fine.
Though with the current master branch on my machine it's much worse than your screenshot, it looks like the screenshot I posted over on that issue. How bad this bug is seems to be hardware dependent.

**Comment by BastiaanOlij** [comment] 2022-06-26 01:52
Hmmm, I'll have a look and see if I can reproduce on my end and see whats going on. That SDFGI might have broken something is possible (or more likely the eye offset change we introduced to fix a number of stereoscopic issues), 62133 however doesn't change any shader logic, it just moves a number of functions into more managable classes.

**Comment by clayjohn** [comment] 2022-06-26 03:12
Fixed by #62420

**Closed by clayjohn** 2022-06-26 03:12 UTC
Labels: bug, topic:rendering, confirmed, topic:3d
