### ISSUE TITLE
WebGL GLES2 accessing DEPTH_TEXTURE disables shader and shows error in browser about feedback loop.

### ISSUE THREAD

**Issue by idchlife** [godotengine/godot#81013] opened 2023-08-26 08:08 UTC
### Godot version

v3.5.2.stable.official [170ba337a]

### System information

macOS/Windows 10 in Chrome

### Issue description

I have project with problem with DEPTH_TEXTURE when exporting to WebGL.

Trying to work with DEPTH_TEXTURE breaks shader in browser.
Tested in Chrome on macOS and Windows 10

Error in browser (macOS/Windows 10 Chrome)

`[.WebGL-0x11c04708e00] GL_INVALID_OPERATION: Feedback loop formed between Framebuffer and active Texture.`

I did not see any warnings or errors in Godot telling me that I can't use DEPTH_TEXTURE in GLES2 (like sampler2DArray error) so I assume it's possible to work with it in browser and it's a bug.

If workaround is possible could anyone tell me about it? Trying to create water shader with DEPTH_TEXTURE for more pleasant look and can't think how to overcome this issue.

### Steps to reproduce

1. Create simple project with several objects
2. Write simple shader and add line where you access DEPTH_TEXTURE, attach it to shadermaterial to one of the objects.
3. Test webgl export by running server from editor
4. See errors in console and that object with shadermaterial is not showing
5. Disable line with accessing DEPTH_TEXTURE
6. See no errors in console

### Minimal reproduction project

[depth_texture_webgl_repro.zip](https://github.com/godotengine/godot/files/12444844/depth_texture_webgl_repro.zip)

**Comment by clayjohn** [comment] 2023-08-26 10:02
Duplicate of https://github.com/godotengine/godot/issues/46883

This was actually fixed recently in https://github.com/godotengine/godot/pull/80481

The fix will be available in the upcoming 3.6 release

**Closed by clayjohn** 2023-08-26 10:02 UTC

**Comment by idchlife** [comment] 2023-08-26 10:53
@clayjohn is there way to obtain 3.6 beta 3 HTML export template? Wanted to check it out.

**Comment by clayjohn** [comment] 2023-08-26 10:58
> @clayjohn is there way to obtain 3.6 beta 3 HTML export template? Wanted to check it out.

You can download the HTML export template from the link provided in the 3.6 beta 3 blog post https://godotengine.org/article/dev-snapshot-godot-3-6-beta-3/#downloads

That being said, the fix was just merged, and so won't be available until we reach beta 4

**Comment by idchlife** [comment] 2023-08-26 11:21
@clayjohn ok, understood. Waiting for beta 4 then. Thanks!
