### ISSUE TITLE
Allowing Visibility Notifier 3D to hide behind bodies?

### ISSUE THREAD

**Issue by Duskitty** [godotengine/godot#7336] opened 2016-12-20 09:46 UTC
Would it be possible to make it so the visibilitynotifier can hide behind objects/bodies? Cause i seem to not be able to do that if that's a thing, otherwise does anybody have an alternative method to doing something similar to this?

**Comment by RebelliousX** [comment] 2016-12-21 22:41
Not really understanding what you want exactly by "hiding"? If you just want to place visibility notifier under its parent object, then you can change its Z-Value to negative number in its property list. If you mean to do this just to make visibility notifier unselectable, then, there are lock/unlock children buttons in the viewport editor that do just that.

**Comment by Duskitty** [comment] 2016-12-21 23:06
No i mean like Hide it behind physical bodies so it registers it as not in the viewport/in the camera because it doesnt seem to recognize when it's covered by things (in 3D)

**Comment by eon-s** [comment] 2016-12-22 22:27
Hidden to the eye, like obstructed by a solid?
The visibility notifiers only says when nodes enter viewport/camera/screen, not when is visible to the human eye.

------------

On 3D you can shot some rays from the camera to the object (talking about CollisionObjects), if no ray hit the object, it is behind something.

You can use the visibility notifier to turn on/off the rays when the object is in the camera range.

------------

On 2D could be more complicated and faking the "hiding" status will depend on the design (checking shapes fully behind another, using rays).

**Comment by bojidar-bg** [comment] 2016-12-23 13:36
@eon-s That's about 3D, 2D can't really be done easily.

**Comment by Noshyaar** [comment] 2018-04-10 15:57
First of all thank you for your report and sorry for the delay.

We released Godot 3.0 in January 2018 after 18 months of work, fixing many old issues either directly, or by obsoleting/replacing the features they were referring to.

We still have hundreds of issues whose relevance/reproducibility needs to be checked against the [current stable version](https://godotengine.org/download), and that's where you can help us.
**Could you check if the issue that you described initially is still relevant/reproducible in Godot 3.0 or any newer version, and comment about it here?**

For bug reports, please also make sure that the issue contains detailed steps to reproduce the bug and, if possible, a zipped project that can be used to reproduce it right away. This greatly speeds up debugging and bugfixing tasks for our contributors.

Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

Thanks in advance.

*Note: This message is being copy-pasted to many "stale" issues (90+ days without activity). It might happen that it is not meaningful for this specific issue or appears oblivious of the issue's context, if so please comment to notify the Bugsquad about it.*

**Comment by akien-mga** [comment] 2019-04-15 14:15
> Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

As there was no update since the previous post, we close this issue.

If it is still relevant in the way it was described and discussed above, please comment to ask for it to be reevaluated. If it is only partly relevant, or if the original issue has changed, it would be better to open a new issue (potentially referring to this one) focused on the current state.

**Closed by akien-mga** 2019-04-15 14:15 UTC
Labels: discussion, feature proposal, topic:core
