### ISSUE TITLE
Text editor layer always on the top when function parameter hints shows up

### ISSUE THREAD

**Issue by fengjiongmax** [godotengine/godot#7333] opened 2016-12-19 14:00 UTC
**Operating system or device - Godot version:**
OS:Windows 10 ,OS X 
Godot Version : v2.1.1.stable.official

**Issue description** (what happened, and what was expected):
As title described.

**Steps to reproduce:**

1. Create a node
2. Add a script to the node just created
3. edit the script and write some function which requires parameter but don't finish it
4. open a new dialog ,like Scene->Project Settings.

And here is the screenshot:
![image](https://cloud.githubusercontent.com/assets/5288733/21314270/11aab0c2-c631-11e6-802a-ad51fab6ae44.png)

**Comment by bojidar-bg** [comment] 2016-12-19 14:34
Duplicate of #7156 -> #6769

**Closed by bojidar-bg** 2016-12-19 14:34 UTC
