### ISSUE TITLE
TileMap and Parallaxbackground don't work in HTML5

### ISSUE THREAD

**Issue by TrickyFatCat** [godotengine/godot#37679] opened 2020-04-08 07:59 UTC
**Godot version:** 3.2

**OS/device including version:** Windows 10

**Issue description:** TileMap and ParallaxBackground nodes don't work in HTML5 version of the game. It seems these nodes don't exist in a level. However, in Windows version of the game, everything works well. It doesn't matter if I use GLES2 or GLES3. I've tested in Brave, Firefox and Edge

**Steps to reproduce:**
* Start HTML5 from the editor
* Or make a build and upload somewhere, e.g. www.itch.io

**Minimal reproduction project:**
* [**Project on git**](https://github.com/TrickyFatCat/HoppyDays)
* [**Fresh HTML5 build on itch.io**](https://tricky-fat-cat.itch.io/test-html-5-project?secret=wvUadHPMEAEitWvCdQKbhDzrs)

**Comment by mrcdk** [comment] 2020-04-08 09:23
It's not loading the resources because in other platforms apart from Windows the path to the resource is case sensitive (webgl being one of them) and, for example, `bg_layer1.png` is inside `res://assets/sprites/Background/bg_layer1.png` but in your scenes it tries to load `res://assets/sprites/background/bg_layer1.png` (notice the `Background` folder case). Godot should have given you a warning about this at some point.

**Comment by TrickyFatCat** [comment] 2020-04-08 09:37
@mrcdk oh, it's started working, thank you! However, there were no warnings at all, as well as answers on the Internet. It's very hard to figure out what went wrong.

**Comment by Calinou** [comment] 2020-04-08 09:50
In this case, this is a duplicate of #24107. Thanks @mrcdk for the answer :slightly_smiling_face:

**Closed by Calinou** 2020-04-08 09:50 UTC
Labels: bug, platform:html5, topic:rendering
