### ISSUE TITLE
The _Init() method doesn't work in C#

### ISSUE THREAD

**Issue by aaronfranke** [godotengine/godot#32295] opened 2019-09-24 02:40 UTC
**Godot version:** 3.1.1 and 30e16fff57cfdeb79f8e9ee6a7516e7d7cd6d376

**OS/device including version:** Ubuntu 18.04 64-bit

**Issue description:** It seems that `_Init` doesn't work at all in C#. @neikeq 

**Steps to reproduce:** Open and run the reproduction project, which contains the following:

    public override void _Init()
    {
        GD.Print("This text is never printed.");
    }

In 3.1.1: The code in `_Init()` isn't executed at all.

In master: `'TestNode._Init()': no suitable method found to override (CS0115)`

**Minimal reproduction project:** [OverrideVoidInit.zip](https://github.com/godotengine/godot/files/3644968/OverrideVoidInit.zip)

**Comment by Zylann** [comment] 2019-09-24 12:33
What would `_init` be for in C# since it has constructors?

**Comment by neikeq** [comment] 2019-09-24 13:23
Duplicate of #22633

`_Init` never did anything in C#, and as I recently [commented](https://github.com/godotengine/godot/issues/22633#issuecomment-495414324):

>I'm removing `_Init` for now in #29140, but I plan to add a working implementation in the future ...

**Closed** 2019-09-24 13:23 UTC
Labels: bug, archived, topic:dotnet

**Comment by NQNStudios** [comment] 2023-02-15 19:17
For API parity, I think _Init() should exist for C#. Or documentation should explain how to replicate the functionality with a C# constructor.
