### ISSUE TITLE
Internal Script Error, opcode #13

### ISSUE THREAD

**Issue by rockgem** [godotengine/godot#54493] opened 2021-11-02 00:28 UTC
### Godot version

3.3.4

### System information

Windows 10, GLES 3.0, Ryzen 5 4500u, 8GB RAM

### Issue description

When I try to load a scene with a script attached to it, it gives me the opcode #13 error, if I remove the script from that scene tho, it works just fine.

### Steps to reproduce

- create scene_1 containing only a Label node
- attach a script to scene_1
- a separate scene (scene_2) with a VBoxContainer (this is where i would put the scene_1 after i loaded it)
- at scene_2 ready() function, load scene_1.tscn using 'var scene_1 = load(...).instance()' function
- at scene_2, $VBoxContainer, add scene_1 by '$VBoxContainer.add_child(scene_1)'

**Comment by rockgem** [comment] 2021-11-02 01:11
A huge mistake on my part, I actually created a custom Resource called 'Engine' and have referenced it inside my scene_1 and it seems to have collided with Godot's built-in Object also called Engine. I renamed my custom Resource type to GameEngine now and worked.

If ever this error occurs to anybody make sure you have not referenced/modified any built-in object

**Comment by Calinou** [comment] 2021-11-02 01:29
Duplicate of https://github.com/godotengine/godot/issues/52893.

**Closed by Calinou** 2021-11-02 01:29 UTC
