### ISSUE TITLE
[Godot 4.0] Exported variables are duplicated in inspector

### ISSUE THREAD

**Issue by Valeboo** [godotengine/godot#64242] opened 2022-08-10 20:48 UTC
### Godot version

v4.0.alpha13.official [59dcddc45]

### System information

Windows 10, Vulkan API 1.2.131 - Intel(R) HD Graphics 630

### Issue description

Exported variables are duplicated in the inspector:
![image](https://user-images.githubusercontent.com/91632939/184015267-4e1b13ed-6e99-4d43-a6eb-9bc5df8b45e8.png)

### Steps to reproduce

1. Add exported variable to node script:
`@export var speed = 200.0`
2. Save (ctrl+s)
3. Switch to another node or scene to refresh the inspector window
4. Switch to the original node or scene
Result: Duplicated "Speed" property in the inspector:
![image](https://user-images.githubusercontent.com/91632939/184015267-4e1b13ed-6e99-4d43-a6eb-9bc5df8b45e8.png)

Note: Sometime, especially when there are other duplicate properties, the issue is reproduced right after Save on step 2.

**Comment by Calinou** [comment] 2022-08-10 21:55
Duplicate of https://github.com/godotengine/godot/issues/63668 (fixed in latest `master` branch).

**Closed by Calinou** 2022-08-10 21:55 UTC
