### ISSUE TITLE
broken mesh deformations when importing armature+mesh from blender

### ISSUE THREAD

**Issue by atornity** [godotengine/godot#75753] opened 2023-04-06 14:23 UTC
### Godot version

4.0.stable

### System information

windows 11

### Issue description

importing a cylinder from blender causes some strange artifacts when rotating the bones in the editor.

blender:
[
![image](https://user-images.githubusercontent.com/29124561/230397667-ba447348-15df-4f03-9530-2941c77c8bb4.png)
](url)
godot:
[
![image](https://user-images.githubusercontent.com/29124561/230397477-326870ca-c3d5-461c-a354-93970acd857e.png)
](url)

I expect the deformation in godot to look the same or similar to blender

blender versions tried: 3.2.0, 3.5.0, 3.6.0

### Steps to reproduce

0. use the mrp or follow the steps
1. add a cylinder to a blender project
2. make sure it's a bit skinny and has a bunch of loop cuts
3. add a armature with 3 bones that matches the cylinder
4. parent the cylinder to the armature with automatic weights
5. save the blend file in a godot project
6. create an inherited scene of the blend file
7. rotate the bones

### Minimal reproduction project

[project.zip](https://github.com/godotengine/godot/files/11171364/project.zip)

**Comment by TokageItLab** [comment] 2023-04-09 06:05
Dupe of #72998

**Closed by TokageItLab** 2023-04-09 06:05 UTC
