### ISSUE TITLE
`BaseButton.set_custom_minimum_size`cause freeze and crashes app

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#60376] opened 2022-04-19 14:57 UTC
### Godot version

4.0.alpha.custom_build. 5974e1432

### System information

Ubuntu 21.10 - Nvidia GTX 970, Gnome shell 40.4 X11

### Issue description

```
	var temp_variable2521 = BaseButton.new()
	add_child(temp_variable2521)
	temp_variable2521.set_custom_minimum_size(Vector2(-NAN, -NAN))
```

```
Failed method: BaseButton::_update_minimum_size

================================================================
handle_crash: Program crashed with signal 11
Engine version: Godot Engine v4.0.alpha.custom_build (690fefe43ee74c0ae3ed5642f3aefbeb711f9d1c)
Dumping the backtrace. Please include this when reporting the bug on https://github.com/godotengine/godot/issues
[1] /lib/x86_64-linux-gnu/libc.so.6(+0x42520) [0x7f22dd63d520] (??:0)
[2] Callable::get_object() const (/home/runner/work/GodotBuilds/GodotBuilds/godot/core/variant/callable.cpp:100)
[3] MessageQueue::statistics() (/home/runner/work/GodotBuilds/GodotBuilds/godot/core/object/message_queue.cpp:154)
[4] MessageQueue::push_callablep(Callable const&, Variant const**, int, bool) (/home/runner/work/GodotBuilds/GodotBuilds/godot/core/object/message_queue.cpp:122)
[5] MessageQueue::push_callp(ObjectID, StringName const&, Variant const**, int, bool) (/home/runner/work/GodotBuilds/GodotBuilds/godot/core/object/message_queue.cpp:45)
[6] MessageQueue::push_callp(Object*, StringName const&, Variant const**, int, bool) (/home/runner/work/GodotBuilds/GodotBuilds/godot/core/object/message_queue.cpp:104)
[7] Error MessageQueue::push_call<>(Object*, StringName const&) (/home/runner/work/GodotBuilds/GodotBuilds/godot/./core/object/message_queue.h:112)
[8] Control::update_minimum_size() (/home/runner/work/GodotBuilds/GodotBuilds/godot/scene/gui/control.cpp:2923 (discriminator 2))
[9] Control::_update_minimum_size_cache() (/home/runner/work/GodotBuilds/GodotBuilds/godot/scene/gui/control.cpp:233)
[10] Control::get_combined_minimum_size() const (/home/runner/work/GodotBuilds/GodotBuilds/godot/scene/gui/control.cpp:239)
[11] Control::_size_changed() (/home/runner/work/GodotBuilds/GodotBuilds/godot/scene/gui/control.cpp:1453)
[12] Control::_update_minimum_size() (/home/runner/work/GodotBuilds/GodotBuilds/godot/scene/gui/control.cpp:332)
[13] void call_with_variant_args_helper<__UnexistingClass>(__UnexistingClass*, void (__UnexistingClass::*)(), Variant const**, Callable::CallError&, IndexSequence<>) (/home/runner/work/GodotBuilds/GodotBuilds/godot/./core/variant/binder_common.h:241 (discriminator 4))
[14] void call_with_variant_args_dv<__UnexistingClass>(__UnexistingClass*, void (__UnexistingClass::*)(), Variant const**, int, Callable::CallError&, Vector<Variant> const&) (/home/runner/work/GodotBuilds/GodotBuilds/godot/./core/variant/binder_common.h:384)
[15] MethodBindT<>::call(Object*, Variant const**, int, Callable::CallError&) (/home/runner/work/GodotBuilds/GodotBuilds/godot/./core/object/method_bind.h:334)
[16] Object::callp(StringName const&, Variant const**, int, Callable::CallError&) (/home/runner/work/GodotBuilds/GodotBuilds/godot/core/object/object.cpp:839 (discriminator 1))
[17] Callable::call(Variant const**, int, Variant&, Callable::CallError&) const (/home/runner/work/GodotBuilds/GodotBuilds/godot/core/variant/callable.cpp:62)
[18] MessageQueue::_call_function(Callable const&, Variant const*, int, bool) (/home/runner/work/GodotBuilds/GodotBuilds/godot/core/object/message_queue.cpp:230)
[19] MessageQueue::flush() (/home/runner/work/GodotBuilds/GodotBuilds/godot/core/object/message_queue.cpp:277)
[20] SceneTree::process(double) (/home/runner/work/GodotBuilds/GodotBuilds/godot/scene/main/scene_tree.cpp:454)
[21] Main::iteration() (/home/runner/work/GodotBuilds/GodotBuilds/godot/main/main.cpp:2722)
[22] OS_LinuxBSD::run() (/home/runner/work/GodotBuilds/GodotBuilds/godot/platform/linuxbsd/os_linuxbsd.cpp:356)
[23] godot4(main+0x16c) [0x2378ab2] (/home/runner/work/GodotBuilds/GodotBuilds/godot/platform/linuxbsd/godot_linuxbsd.cpp:70)
[24] /lib/x86_64-linux-gnu/libc.so.6(+0x29fd0) [0x7f22dd624fd0] (??:0)
[25] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0x7d) [0x7f22dd62507d] (??:0)
[26] godot4(_start+0x2e) [0x237888e] (??:?)
-- END OF BACKTRACE --
================================================================

```

### Steps to reproduce

Above

**Comment by timothyqiu** [comment] 2022-04-20 03:07
This is a duplicate of #60326. It's caused by the NaN minimum control size.

**Closed** 2022-04-27 08:09 UTC
Labels: bug, crash, topic:gui
