### ISSUE TITLE
New AnimationTree API bug or feature?

### ISSUE THREAD

**Issue by DarkMessiah** [godotengine/godot#24537] opened 2018-12-21 19:53 UTC
**Godot version:**
v3.1.alpha.calinou.09623ff

**OS/device including version:**
Windows 10 x64

**Issue description:**
Hello. In previous version of engine, before https://github.com/godotengine/godot/commit/9018e8b132da3d8bc7ecc5e7822676811fc1ffab fix, we can work with AnimationNodeBlendSpace2D and AnimationNodeStateMachine directly. For example, AnimationNodeBlendSpace2D has variable **blend_position** and AnimationNodeStateMachine has method **travel**, now it can only be obtained through parameters of AnimationTree. It's looks like a bug or bad feature. Is this the final version of the API in 3.1?

**Comment by mysticfall** [comment] 2018-12-23 02:20
Probably a duplicate to #21399?

**Comment by reduz** [comment] 2019-01-12 12:13
This has been finally properly documented, so closing this issue. This change was intended:
https://docs.godotengine.org/en/latest/tutorials/animation/animation_tree.html

Now the nodes in the animationtree are actual resources, so this allows to save them and reuse them in different animation trees.  They will also be shared between multiple instances, making AnimtionTree more efficient. 

Many users requested this, as well as the ability to expose state machine conditions and control the tree from an AnimationPlayer. All this was only made possible by the recent changes.

The only downside is that, as mentioned in other posts, this is not type safe. In GDScript this is not a problem, but I can understand for C# or C++. Maybe we can make it error if the wrong type is assigned somehow, or add a special function to set a parameter?

**Closed by reduz** 2019-01-12 12:13 UTC
Labels: discussion, topic:core
