### ISSUE TITLE
"Parser Bug" occurs While assigning a value to @onready variable by custom functions

### ISSUE THREAD

**Issue by Zincles** [godotengine/godot#67472] opened 2022-10-16 04:26 UTC
### Godot version

4.0 beta3

### System information

Arch linux, Forward+

### Issue description

While trying to assign a value by a custom  function to a @onready variable, the Parser bug occurs. I don't know what really happend. The game did not stop, it works fine but errors were print in console.

### Steps to reproduce

create a simple scene, attach a simple script, write a simple function that returns value, like this :

```
extends Node2D

@onready var X = test()

func test():
	return 0;
```

and here's the error:
```
 modules/gdscript/gdscript_analyzer.cpp:668 - Parser bug (please report): tried to assign unset node without an identifier.
```

**Comment by Cykyrios** [comment] 2022-10-16 06:31
Does this also happen if your function returns a `Node`? `@onready` is supposed to only work with `Node`s, as it relates to their `_ready` status.
The error should probably mention this instead of giving a parser error, though.

**Comment by Calinou** [comment] 2022-10-16 18:01
Duplicate of https://github.com/godotengine/godot/issues/67085.

**Closed by Calinou** 2022-10-16 18:01 UTC
