### ISSUE TITLE
GraphEdit line antialiasing is broken in-game

### ISSUE THREAD

**Issue by somnivore** [godotengine/godot#35431] opened 2020-01-22 09:25 UTC
**Godot version:**
3.2 RC2
**OS/device including version:**
ArcoLinux
**Issue description:**
![image](https://user-images.githubusercontent.com/28724859/72879826-4d379900-3cc3-11ea-8593-d5d0eabe409f.png)

Oddly enough, it seems to be fine in VisualScript:
![image](https://user-images.githubusercontent.com/28724859/72881565-9b01d080-3cc6-11ea-973e-2888a73ada01.png)

Tested in a brand new project:
![image](https://user-images.githubusercontent.com/28724859/72881461-7148a980-3cc6-11ea-8e42-00310b64717f.png)

**Comment by mrushyendra** [comment] 2020-06-30 01:12
Related to #17471?

**Comment by Calinou** [comment] 2020-06-30 08:00
Duplicate of #17471 indeed. Thanks for bringing it to my attention :slightly_smiling_face:

**Closed by Calinou** 2020-06-30 08:00 UTC
Labels: bug, topic:gui, topic:rendering
