### ISSUE TITLE
[Bullet] Applying a central impulse with a horizontal vector will result in getting vertical velocity too

### ISSUE THREAD

**Issue by lexum0** [godotengine/godot#58948] opened 2022-03-09 21:13 UTC
### Godot version

3.4.3.stable, 3.4.4.rc1

### System information

macOS, Windows

### Issue description

Using apply_central_impulse with an horizontal vector results in getting vertical velocity in the RigidBody.

https://user-images.githubusercontent.com/2546522/157533819-d50aa610-2575-4423-8826-4dca1e363097.mov

The issue is not present on Godot 4 nor Godot 3 with GodotPhysics. The problem may be in Bullet Physics

My guess is it could be the collisions, since something similar happens when the ball crosses an edge in the collisions shape, maybe it's a diagonal in the CSG geometry collision shape which isn't shown by ```Visible Collision Shapes```

### Steps to reproduce

Open attached project, press 'S'

### Minimal reproduction project

[Physics Bump.zip](https://github.com/godotengine/godot/files/8218225/Physics.Bump.zip)

**Comment by Calinou** [comment] 2022-03-09 21:41
Duplicate of https://github.com/godotengine/godot/issues/46596, as you mentioned:

> My guess is it could be the collisions, since something similar happens when the ball crosses an edge in the collisions shape, maybe it's a diagonal in the CSG geometry collision shape which isn't shown by Visible Collision Shapes

**Closed by Calinou** 2022-03-09 21:41 UTC
Labels: bug, topic:physics, topic:3d

**Comment by lexum0** [comment] 2022-03-09 21:46
@Calinou I said it's a guess, to help speed up resolving it, no one has even confirmed that's the issue so as to mark it as a duplicate

**Comment by Calinou** [comment] 2022-03-09 21:57
> @Calinou I said it's a guess, to help speed up resolving it, no one has even confirmed that's the issue so as to mark it as a duplicate

If you set gravity scale to 0 and remove the StaticBody floor, the RigidBody will most likely not move vertically anymore.

**Comment by lexum0** [comment] 2022-03-09 21:58
Could be related to https://github.com/godotengine/godot/issues/46596

**Comment by lexum0** [comment] 2022-03-09 22:01
> > @Calinou I said it's a guess, to help speed up resolving it, no one has even confirmed that's the issue so as to mark it as a duplicate
> 
> If you set gravity scale to 0 and remove the StaticBody floor, the RigidBody will most likely not move vertically anymore.

Correct, it doesn't happen. The problem is with the collision with CSG
