### ISSUE TITLE
Normal map with unrotated camera will make a quad black

### ISSUE THREAD

**Issue by nunodonato** [godotengine/godot#8004] opened 2017-03-10 19:56 UTC
**Operating system or device - Godot version:** Tested in Godot 2.1.2 and Godot 3. Both display the same issue

**Issue description:**
Setting a normal map on a quad, with the camera facing straight at it, will show only a black quad. In the editor everything looks fine, but the problem appears when running the game.

Rotating the camera even a tiny bit will solve the issue. Which suggests to me that when something is 0, something breaks :p

**Link to minimal example project:**

Reported in Q&A with sample project: https://godotengine.org/qa/13060/cannot-normal-mapping-fixedmaterial-screenshots-project

**Comment by reduz** [comment] 2017-08-06 00:49
this may have been fixed as i solved a normal map bug recently importing collada.. does it still happen?
i can't get the demo project

**Comment by reduz** [comment] 2017-08-15 10:38
Quad node is gone and i can't reproduce this in current master using quad mesh, so closing.

**Closed by reduz** 2017-08-15 10:38 UTC
Labels: bug, topic:rendering
