### ISSUE TITLE
"Reload Current Project" - don't silently discard unsaved editor changes

### ISSUE THREAD

**Issue by belzecue** [godotengine/godot#59909] opened 2022-04-05 10:48 UTC
### Godot version

3.4.4-stable

### System information

Linux Ubuntu 20.04

### Issue description

I always thought of "Reload Current Project" as sort of a "oh dear, the editor's gotten itself in a twist, so let's restart to clear away the cobwebs" thing.

1. Edit the scene tree
2. Project > Reload Current Project

Godot immediately reloads the project from disk.  The unsaved changes from Step 1 are lost.

This may well be the intended purpose of "Reload Current Project", i.e. it is intended to be a "Revert to Saved Version".  But that is not what it is doing.  "Reload Current Project" is ambiguous.  Does "current" mean the project in its current state in the editor, or the project in its state on disk?  If the former, it should offer to SAVE or DISCARD the changes prior to reloading from disk -- i.e. behave the same as "Quit to Project List".

If this menu item is meant to act as a "Revert to Saved Version" then call it that: "Revert Project From Disk" or similar.  Then it will be clear what this function does.

For example, just now I added to my project a new node definition and its icon.  Godot does not recognise icons for newly added node definitions until the editor is restarted.  So this is a good use case for menu item "Reload Current Project".  But if you do not manually save your editor changes before hitting "Reload..." then your changes are discarded immediately and without notice.

There are many other use cases, like when the Editor gets itself into a tangle and prints weird error messages that only go away after an Editor restart, which is easily and quickly accomplished by doing a "Reload Current Project" -- but again you will lose any unsaved changes if you've forgotten to save first.

TLDNR: If "Reload Current Project" is intended to be a "revert to project saved state" then rename it accordingly.  If it is intended to do precisely what it is called then check for unsaved editor changes and give the user the option to save or discard the changes prior to exiting the editor, same as how "Quit to Project List" behaves.

Thanks!

### Steps to reproduce

Simple, as described above.

### Minimal reproduction project

N/A

**Comment by akien-mga** [comment] 2022-04-05 10:59
Duplicate of #52287, this is fixed in 3.5.

**Closed by akien-mga** 2022-04-05 10:59 UTC

**Comment by belzecue** [comment] 2022-04-05 11:00
Apologies. I searched Issues but had the default is:open tag.

**Comment by akien-mga** [comment] 2022-04-05 11:11
No worry. GitHub should have better tooling for this, it's not your fault (and it's also not a problem - we prefer duplicates than not knowing about bugs).
