### ISSUE TITLE
Godot 3d, grid missing when mesh instance is visible.

### ISSUE THREAD

**Issue by AndresBBB** [godotengine/godot#39025] opened 2020-05-25 02:02 UTC
Godot version: 3.2.1

OS/device including version: Windows 10/ asus X441UA

Hi everyone, 

When I create a mesh instance node and it is visible, the grid is lost, and sometimes, the mesh instance turn on black, depending on the angle of view.

I will be grateful to anyone who can help me. Thanks.

![image](https://user-images.githubusercontent.com/46661492/82771240-f5d83f80-9e00-11ea-90b3-3b0725b521b6.png)
![image](https://user-images.githubusercontent.com/46661492/82771243-f8d33000-9e00-11ea-84d8-adce66482dc1.png)
![image](https://user-images.githubusercontent.com/46661492/82771400-7d25b300-9e01-11ea-8c87-7448fb0e268a.png)

**Comment by clayjohn** [comment] 2020-05-25 02:27
Looks like a duplicate of https://github.com/godotengine/godot/issues/30330

Are you on integrated graphics or discrete?

Also GLES2 or GLES3?

**Comment by AndresBBB** [comment] 2020-05-25 15:30
I have integrate graphics Intel hd graphics 520, and I use GLES3 but when I switch for GLES2 the bug disapier.

**Comment by clayjohn** [comment] 2020-05-25 16:42
Thanks for following up. 

It appears it is a duplicate of #30330, so we will track the issue there.

**Closed by clayjohn** 2020-05-25 16:42 UTC
