### ISSUE TITLE
Error when adding brackets in multi-line string

### ISSUE THREAD

**Issue by CitrusWire** [godotengine/godot#44938] opened 2021-01-05 15:08 UTC
**Godot version:**
3.2.3

**OS/device including version:**
Win 7

**Issue description:**
I'm getting these errors in the Output:
```
 modules/gdscript/gdscript_tokenizer.cpp:1129 - Condition "tk_rb[ofs].type != TK_IDENTIFIER" is true. Returned: StringName()

```

**Steps to reproduce:**
* Add this code into any script:
```
"""
Hello World
"""
```

* At the end of either the first line, or the second line, Enter a left bracket: `(`

Doesn't happen if in the middle of the string, only if at the end.

Edit: Also does it if you add the `(` before a ? or !

**Minimal reproduction project:**
n/a

**Comment by Calinou** [comment] 2021-01-05 17:30
Duplicate of https://github.com/godotengine/godot/issues/35994.

**Closed by Calinou** 2021-01-05 17:30 UTC
