### ISSUE TITLE
Assigning F5 Key to "Run Project" resets after restart of Godot  

### ISSUE THREAD

**Issue by DATADEER** [godotengine/godot#70682] opened 2022-12-28 21:35 UTC
### Godot version

v4.0.beta10.official [d0398f62f]

### System information

macOS Monterey, Version 12.6.1 (21G217), Apple M1 Chip

### Issue description

The keyboard shortcut for `"Run Project"` (`Command + B`) doesn't work on my machine on any Godot version that I've tried so far (3.5.x, 4.0beta8,9,10). That's why I wanted to reassign it to `F5` because this key works fine.

But every time I assign `F5` to `"Run Project"` it resets after restarting Godot. 

❌ I could **observe this behaviour** for:
* Name: `"Run Project"` Binding: `F5` -> [Screenrecording](https://share.cleanshot.com/t7tnsDS5)
* Name: `"Search Help"` Binding: `F1`

✅ The key **remains assigned** for the following combinations:
* Name: `"Run Project"` Binding: `F10`
* Name: `"Run Project"` Binding: `Shift + L`
* Name: `"Show Helpers"` Binding: `F5` -> [Screenrecording](https://share.cleanshot.com/JH9dHBfS)

### Steps to reproduce

1. Launch Godot v4.0.beta10 on macOS
2. Open "Editor" -> "Editor Settings"
3. Switch to "Shortcuts" tab
4. Filter by name and search for "Run Project"
5. Assign `F5` key to "Run Project"
6. Close "Editor Settings" window
7. Quit Godot Engine
8. Repeat steps 1 - 4
9. "Run Project" is no longer assigned to `F5` but instead has returned to `Command + B`

https://user-images.githubusercontent.com/11938237/209873062-b4dad0a0-07f7-41ba-afbe-9a686f929469.mp4

### Minimal reproduction project

N/A

**Comment by EricEzaM** [comment] 2023-01-08 06:34
Thanks for the report with detail - looks like a duplicate of https://github.com/godotengine/godot/issues/66428.

Could you please try what I mention in a comment there and reply to that thread?

> You could also open your editor_settings.tres file in VS Code for example, and see if/how it changes as you restart the editor. The customised shortcuts are listed at the bottom.

**Closed by EricEzaM** 2023-01-08 06:34 UTC
Labels: bug, archived, topic:editor, topic:input
