### ISSUE TITLE
Layer/Masks Became Corrupted in Project and No Longer Work

### ISSUE THREAD

**Issue by Mashugana972** [godotengine/godot#46044] opened 2021-02-15 09:34 UTC
**Godot version:**

3.2.3

**OS/device including version:**

Windows 10 Home 
Version 1909
OS Build 18363.1379

IdeaPad S540-15IML
Intel i7-10510U @ 1.86GHz 2.30 Ghz
8.0 Gb Ram

**Issue description:**

Collision layers are not working in my project. In the attached sample project, the Player scene is on Layer 1, with a Mask 2.

The Projectile scene is on Layer 3, with a Mask 4. These two things should have no interaction, but when a projectile is spawned, it bounces off the player's collision layer.

I and a forum member on Reddit suspect the project has somehow become corrupted or there is an engine bug.
[Broken Project.zip](https://github.com/godotengine/godot/files/5980635/Broken.Project.zip)

**Steps to reproduce:**

Press "G" when the cursor is below the player, the projectile bounces off the Player's CollisionShape2D. Disabling this shape allows the projectile to pass through.

The Fireball (right-click) also collides when launched downward.

**Minimal reproduction project:**

[Broken Project.zip](https://github.com/godotengine/godot/files/5980644/Broken.Project.zip)

**Comment by kleonc** [comment] 2021-02-15 13:34
The cause is both player's `collision_mask` and projectile's `collision_layer` have bit 31 set (2<sup>31</sup> = 2147483648).

`Player.tscn`:

> [node name="Player" type="KinematicBody2D"]
position = Vector2( 328.098, 234.759 )
collision_mask = 2147483650
script = ExtResource( 2 )

`Projectile_Template.tscn`:

> [node name="Projectile" type="KinematicBody2D"]
collision_layer = 2147483652
collision_mask = 8
script = ExtResource( 1 )

So it's most likely a duplicate of #41281.

**Comment by Calinou** [comment] 2021-02-15 15:32
Indeed, this is a duplicate of https://github.com/godotengine/godot/issues/41281
.

**Closed by Calinou** 2021-02-15 15:32 UTC
