### ISSUE TITLE
The keyboard and mouse input work one input later in godot 3.1 stable. Surface pro 6.

### ISSUE THREAD

**Issue by Bucham** [godotengine/godot#27321] opened 2019-03-22 11:21 UTC
Note: Hello, excuse my english please, i'm spanish.

Godot version:
Godot 3.1 stable.

OS/device including version:
Surface pro 6. i5, 8gb ram, 128 ssd. Windows 10 whith last drivers and updates.

Issue description:

The problem begins as soon as you open the program. The screen does not pass the presentation until I press on it, and if i expand to full screen it stay black until I also press on it. Once I am in the project editor, when I press a button, it remains marked, but it does not function until I also press an empty point on the screen. The problem continues, for example, when I use the pop-up window to create a new project. When I write a letter it does not appear, but when I write another letter, the first one appears. If I press delete, the letter is not deleted until I press another letter (but the letter does not appear until I again press another letter, space or erase), an so on. It seems that keyboard or mouse inputs are recorded, but do nothing or appear on the screen until there is a new input. Once you are in the normal editor, everything seems to work normally, except the button to close the program, which seems to suffer the same problem and most of the time I must close it from the taskbar.  This problem did not appen with the latest release candidate.

Steps to reproduce:
I think this should appen in all surface pro 6 at  least, since this is a standar surface 6 with nothing special.

**Comment by Bucham** [comment] 2019-03-22 11:28
Excuse me, i forgot to say that this did not appen with the latest release candidate.

**Comment by Calinou** [comment] 2019-03-22 12:02
Duplicate of https://github.com/godotengine/godot/issues/23069. Updating your Intel graphics driver should solve the issue; if it doesn't, follow the workaround described in https://github.com/godotengine/godot/issues/23069#issuecomment-432981553.

**Closed by Calinou** 2019-03-22 12:02 UTC
