### ISSUE TITLE
Theme doesn't work properly with dialogs contents in 2.2

### ISSUE THREAD

**Issue by Geequlim** [godotengine/godot#6443] opened 2016-09-10 03:58 UTC
**Operating system or device - Godot version:**

Godot 2.2 complied with 97cebe1358dbdd6d9dca8b079517e4ff8fb3fbc7

**Issue description** (what happened, and what was expected):
![2016-09-10 11-57-58](https://cloud.githubusercontent.com/assets/6964556/18407803/e42c0fba-774d-11e6-9ce9-235b11c67fe3.png)

It works for Godot 2.1

**Comment by Geequlim** [comment] 2016-09-10 04:04
This is wired that controls add from editor works fine.
![2016-09-10 12-02-30](https://cloud.githubusercontent.com/assets/6964556/18407835/a00d46fe-774e-11e6-8a97-d2e363a16837.png)
![2016-09-10 12-02-13](https://cloud.githubusercontent.com/assets/6964556/18407836/a57c961c-774e-11e6-9964-c7df0cab684b.png)

**Comment by Sslaxx** [comment] 2016-09-10 08:37
Duplicate of #6302?

**Comment by Geequlim** [comment] 2016-09-10 08:39
Well~ yes it is。

**Comment by vnen** [comment] 2016-09-10 14:26
Closing as duplicate of #6302 then.

**Closed by vnen** 2016-09-10 14:26 UTC
