### ISSUE TITLE
Project property unhandled_exception_policy missing

### ISSUE THREAD

**Issue by JakSparro98** [godotengine/godot#76112] opened 2023-04-16 02:22 UTC
### Godot version

4.0.2 mono

### System information

Windows 7

### Issue description

Godot 4 ignores C# runtime errors by default now, on the 3.x branch there is the mono/runtime/unhandled_exception_policy property that allow the game termination if there are exceptions in the script, now it seems to be removed, I didn't even manage to find another property that act in the same way for the 4.x branch.

### Steps to reproduce

N/a

### Minimal reproduction project

N/a

**Comment by raulsntos** [comment] 2023-04-16 10:13
Duplicate of https://github.com/godotengine/godot/issues/73515

**Closed by raulsntos** 2023-04-16 10:13 UTC
