### ISSUE TITLE
Godot 4 - Tilemap zindex issue with children that are instantiated

### ISSUE THREAD

**Issue by ebuchmann** [godotengine/godot#62401] opened 2022-06-25 13:34 UTC
### Godot version

4-alpha10

### System information

Windows 11

### Issue description

I have a tilemap and I'm adding my player as a child of it through code and when doing so the player ends up rendering below the tilemap rather than on top of it. If I add any child to the tilemap in the editor then the player correctly renders on top of the tilemap when it's instantiated in.

### Steps to reproduce

- Run attached project, see that the Player renders below the tilemap tiles
- In the scene editor add anything as a child of the tilemap, such as a blank Node2D
- Run project again, see that the Player node now renders fully on top of the tilemap

### Minimal reproduction project

[tilemap-bug.zip](https://github.com/godotengine/godot/files/8984862/tilemap-bug.zip)

**Comment by KoBeWi** [comment] 2022-06-25 16:53
Duplicate of #53746
As a workaround, set player's z_index to be higher than the TileMap layer you want to be below.

**Closed by KoBeWi** 2022-06-25 16:53 UTC
