### ISSUE TITLE
Gridmap shortcuts not working

### ISSUE THREAD

**Issue by narredev** [godotengine/godot#82003] opened 2023-09-20 19:21 UTC
### Godot version

4.1.1

### System information

Windows 10

### Issue description

I know you can use the ctrl+wheel to do it, but the Q and E shortcuts for changing floors or planes don't work, they get consumed by the Select Mode and Rotation tools. This shortcuts are shown in the top Gridmap button

This could be solved by going to the editor shortcut settings to change them, but to my surprise, there are no shortcut settings for the Gridmap

The W shortcut for resetting cursor rotation also gets consumed by the Move Tool, this one is pretty annoying as there is no alternative shortcut to my knowledge

The A, S, D ones work fine

This problem is also present in 4.0.3

### Steps to reproduce

1. Make a meshlib with a block
2. Add it to a Gridmap
3. Try using the Q and E shortcuts to change floors

### Minimal reproduction project

[gridmap-test.zip](https://github.com/godotengine/godot/files/12676823/gridmap-test.zip)

**Comment by AThousandShips** [comment] 2023-09-20 21:32
Duplicate of https://github.com/godotengine/godot/issues/67497

**Closed by AThousandShips** 2023-09-20 21:32 UTC

**Comment by narredev** [comment] 2023-09-20 21:40
oh my bad. I searched "gridmap" instead of "grid map" 🤦
