### ISSUE TITLE
[MacOS - Godot 4 Alpha 1] Cannot type some characters in the integrated code editor 

### ISSUE THREAD

**Issue by DaSlang** [godotengine/godot#57230] opened 2022-01-25 21:43 UTC
### Godot version

v4.0.alpha1.official v.31a7ddbf8

### System information

MacOS Big Sur 11.6.2

### Issue description

Using an Italian keyboard layout, it seems impossible to type some charachters into the integrated code editor, or in any other part of the application.
To be more specific, none of the characters that requires the ```option``` key - like @,  #, {, ecc... - can be typed.

On the other hand, everything works like a charm in Godot 3.4 stable.

### Steps to reproduce

Using the Italian layout and Godot 4 Alpha:
- Create or open a project;
- Add a new script;
- Type the @ key (or any other key that requires the ```option``` key;

**Comment by bruvzg** [comment] 2022-01-25 21:55
This is an old knows issue, see #6851, #54303, and #56319. And #56695 for a fix.

**Comment by Calinou** [comment] 2022-01-25 21:56
Duplicate of https://github.com/godotengine/godot/issues/54303.

**Closed by Calinou** 2022-01-25 21:56 UTC
Labels: bug, platform:macos, topic:input, regression
