### ISSUE TITLE
Exported Arrays and Dictionaries are displayed as `null` in the editor, regardless of their default value

### ISSUE THREAD

**Issue by stryker313** [godotengine/godot#62753] opened 2022-07-05 22:13 UTC
### Godot version

4.0 Alpha 9

### System information

Windows 10 Nvidia GTX 1060 Intel i5 4690k

### Issue description

When exporting an array of any type, the initial value always defaults to nil, even when you define preset values

![Desktop Screenshot 2022 07 05 - 18 01 59 36](https://user-images.githubusercontent.com/83078010/177425236-f42a4449-39a0-4e8a-b1e2-8f77a26be8ca.png)
![Desktop Screenshot 2022 07 05 - 18 01 50 84](https://user-images.githubusercontent.com/83078010/177425235-17f479d3-0c6c-48f2-8a70-9e1ddb0ce26b.png)
![Desktop Screenshot 2022 07 05 - 18 02 09 94](https://user-images.githubusercontent.com/83078010/177425237-f87c2c69-e619-4e51-a835-9ad5830b65bd.png)

Additionally, trying to do things like assign an animation player's animation list to an exported array also will not work
![Desktop Screenshot 2022 07 05 - 18 03 01 01](https://user-images.githubusercontent.com/83078010/177425238-809f3873-d4f9-4775-9916-e6e63a096def.png)

One thing to note. The values actually exist. You can verify by printing both arrays (the string one, and the animation list)
However, in the inspector, they are incorrect.
![Desktop Screenshot 2022 07 05 - 18 12 19 50](https://user-images.githubusercontent.com/83078010/177425865-15c5c0d9-3fce-4ad2-8b7a-e758e6b2b1c1.png)

### Steps to reproduce

1. Define an exported array of type string (can be any type really)
2. Go into the inspector, and find the initial values null

### Minimal reproduction project

[BrokenArray.zip](https://github.com/godotengine/godot/files/9049962/BrokenArray.zip)

*Bugsquad edit (keywords for easier searching): empty, dictionary*

**Comment by Calinou** [comment] 2022-07-05 22:23
Related to https://github.com/godotengine/godot/issues/39465.

I'm fairly sure this is a duplicate of another issue, but I can't find it right now.

**Comment by nathanfranke** [comment] 2022-07-12 14:18
I also noticed that strings export as the literal text "null". Same issue?

![image](https://user-images.githubusercontent.com/14253836/178512010-a5cd3cb5-6d1f-4d81-b4c5-add9a3d0bd86.png)

**Comment by timovervliet82** [comment] 2022-09-20 02:04
I can verify this issue for Beta 1 - Exported arrays are null on initialisation.

**Comment by Arfilish** [comment] 2022-12-28 22:08
Still relevant for beta 10

**Comment by Myrmidon82** [comment] 2023-01-19 20:56
Still occurs on beta 13

**Comment by ismailgamedev** [comment] 2023-01-24 18:29
Still relevant for beta 14

**Closed** 2023-01-31 10:20 UTC
Labels: bug, topic:gdscript, topic:editor, confirmed
