### ISSUE TITLE
Missing character in Inspector viewing collision layer/mask properties

### ISSUE THREAD

**Issue by cbscribe** [godotengine/godot#20372] opened 2018-07-23 02:25 UTC
**Godot version:**
3.1 4b549fa

**OS/device including version:**
Mac OS 10.12.6

**Issue description:**
See attached screenshot:

![screen shot 2018-07-22 at 7 19 14 pm](https://user-images.githubusercontent.com/3812514/43053979-509bc34e-8de4-11e8-9e64-2b2d6444c761.png)

**Comment by akien-mga** [comment] 2018-07-23 06:30
Duplicate of #20288.

**Closed by akien-mga** 2018-07-23 06:30 UTC
