### ISSUE TITLE
Strange Pixel offset

### ISSUE THREAD

**Issue by vntxx** [godotengine/godot#37262] opened 2020-03-23 21:37 UTC
**Godot version:**
Using 3.2.1

**OS/device including version:**
Windows 10

**Issue description:**
In my particular scenario a pixel shifts to the left and "bleeds" out of its gizmo
When using a sprite with an atlas texure and the offset mode is centered then this happens:
![doesnt_work](https://user-images.githubusercontent.com/38376434/77365281-1e3ab380-6d56-11ea-9ae4-9fb2e9e25505.PNG)
If i turn it off and manually adjust the offset it works:
![does_work](https://user-images.githubusercontent.com/38376434/77365309-2f83c000-6d56-11ea-9aa7-5163503905f7.PNG)
I do have enabled pixel snap in the project settings

This isn't crucial as i have a fix for this already but i feel like this should work nevertheless

**Comment by Calinou** [comment] 2020-03-23 22:42
Related to #15255 maybe?

**Comment by vntxx** [comment] 2020-03-24 00:06
I guess this is a rounding issue since it snaps into the right position (when centered) if i set the offset to something small like 0.0001

**Comment by aaronfranke** [comment] 2020-03-24 05:54
Under Region -> Rect, `x` is set to `7.0` (presumably it has more unseen digits) instead of `7`.

**Comment by JeromeOrtali** [comment] 2020-03-24 09:45
Your coordinate (7,0,17,32) produce this behavior. use power of two like 0,2,4,6,8, etc...

**Comment by bojidar-bg** [comment] 2020-03-24 10:47
Caused by / Duplicate of #7015?

**Comment by vntxx** [comment] 2020-03-24 21:47
I just noticed that if I reload the Project everything works as expected even when tweaking the frame parameter of the animation section in my sprite. Once i touch the region though (for example rect x) it moves to the left by a pixel (or 1 (pixel) unit) and stays that way even if i set the rect offset back to 0. If i now change the frame parameter again it stays that way and glitches out of the gizmo on the left and is inset by 1 unit on the right of it.

**Comment by vntxx** [comment] 2020-03-24 21:53
Also the texture region doesn't update when tweaking the region values in the inspector

**Comment by vntxx** [comment] 2020-03-24 21:55
@aaronfranke i actually had it offset by 7 to show that the texture glitches out at the edge. It also happens when using a value like 0

**Comment by vntxx** [comment] 2020-03-24 21:56
@JeromeOrtali my coordinates normally are (0, 0, 176, 32)

**Comment by aaronfranke** [comment] 2020-03-24 22:20
Please provide a minimal reproduction project.

**Comment by vntxx** [comment] 2020-03-26 16:00
I couldn't reproduce this issue in another Project so i am actually going to provide my full project for this. There may be weird stuff in there. The problem occurs in WorldLoader/Player/Sprite
[GDCS.zip](https://github.com/godotengine/godot/files/4388272/GDCS.zip)

**Comment by Calinou** [comment] 2021-05-15 20:55
Closing in favor of https://github.com/godotengine/godot/issues/7015, which is more isolated to an issue reproducible in every project.

**Closed by Calinou** 2021-05-15 20:55 UTC
Labels: discussion, topic:core
