### ISSUE TITLE
Removing an empty sub-directory having the same name as another higher-level directory causes the entire project to be parsed and shows wrong result

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#33378] opened 2019-11-06 00:17 UTC
Godot 3.2 alpha3

I'm pretty sure I've seen this issue before but I could not find it from a quick search.

- Have a project with several folders under `res://`
- Create a folder as child of any root folder, and give it the same name as one of the root folders
- Delete the folder you just created: notice a loading bar shows up for several seconds (depends on project size), on which you can see all your files being iterated one by one. I guess Godot tries to re-import them which is completely useless.
- Once the loading bar closes, your directory is still there, and it now has the same contents as `res://`.

Here with the `accentor` directory:
![image](https://user-images.githubusercontent.com/1311555/68257096-00c8af80-002a-11ea-8bbb-a43d4e45f2aa.png)

- Unfocus the editor, and refocus it: the file system updates and the folder disappears.

The console is spammed of errors like this:
```
ERROR: Failed to get modified time for: D:/PROJETS/INFO/GODOT/Games/SagaTK/spell_checker/accentor/character_editor/script_data.gd.
   At: drivers/windows/file_access_windows.cpp:344
ERROR: _reimport_file: Error importing 'res://spell_checker/accentor/fonts/icons/icon_load.svg'.
   At: editor/editor_file_system.cpp:1784
```

**Comment by KoBeWi** [comment] 2019-11-06 02:42
I had this happen few times, seemingly randomly. Reproduction steps don't work for me.

**Comment by KoBeWi** [comment] 2019-11-19 15:13
Looks like duplicate of #27526, so closing. Also I might've found more reliable way to reproduce it.

**Closed by KoBeWi** 2019-11-19 15:13 UTC
Labels: bug, needs testing, topic:editor
