### ISSUE TITLE
Custom tooltip blinks when using _make_custom_tooltip(for_text) on certain systems

### ISSUE THREAD

**Issue by Kersoph** [godotengine/godot#59973] opened 2022-04-07 09:02 UTC
### Godot version

3.4.4-stable

### System information

Windows 10 x64, NVidia GTX 970, i7-2600K CPU, GLES3

### Issue description

Custom tooltip turns on and off / blinks when using _make_custom_tooltip(for_text) on some machines:

https://user-images.githubusercontent.com/26461040/162152568-d6d1b80f-0409-40c8-adf4-342ee5f4968e.mp4

The frequency is quite slow around one second.
What could help: The tooltip is behind the the source control for a few frames from time to time (see video in the end).

### Other machines and versions:
Godot_v3.4.3-stable: **same** behaviour with the issue on my machine.
This behaviour **also** occurs when the project is exported on my machine.
Linux Mint 18.3 x64 (i7-2860QM, NVIDIA GF106GLM [Quadro 2000M]): The tooltip is **NOT** blinking (but still is behind other controls for a few frames if that helps)
u/SpeCterMK/ observed the **same** behaviour on Windows 7 on "some old integrated intel gpu".

### Regular tooltip
The normal tooltip (Control: Hint: Tooltip) works as intended.

### Steps to reproduce

I used the example code from https://docs.godotengine.org/de/stable/classes/class_control.html#class-control-method-make-custom-tooltip
1. Create a scene with a button and this script:
```swift
extends Button
func _make_custom_tooltip(for_text):
    var label = Label.new()
    label.text = "Custom Text"
    return label
```

2. Run the scene and hover over the button. Do not move the cursor.

### Minimal reproduction project

[Minimal_Project_Blinki.zip](https://github.com/godotengine/godot/files/8441030/Minimal_Project_Blinki.zip)

**Comment by akien-mga** [comment] 2022-04-07 09:06
Probably a duplicate of #32990 - do you use Stardock Fences, Kakaotalk, or apparently Unity, while this happens?

**Comment by SpeCter** [comment] 2022-04-07 09:24
Just to fill in some information from my side:
Windows 7
Intel i5 4310M
HD Graphics 4600
GLES3

Happens on this machine with all godot related tooltips. None of the before mentioned programs are installed or running.

Funnily enough my main machine which does have Fences installed works without problems though.

**Comment by Kersoph** [comment] 2022-04-07 09:47
> Probably a duplicate of #32990 - do you use Stardock Fences, Kakaotalk, or apparently Unity, while this happens?

I started to strategically go through all programms I use to check the issue. In fact, it was the **Windows Media Player**.
As soon as I stop or close the Windows Media Player the issue vanishes. As soon as I open it the issue starts anew.
It does not occur in VLC Media Player, Audacity or if I play music through Firefox.

Interesting: Normal tooltips always work as intended in terms of this issue when I run the game. Only custom tooltips have this behaviour and the ones in the editor. May be there is a connection this helps with the other linked issue. I will summarise it there as well.

**Comment by Calinou** [comment] 2022-11-04 23:11
Duplicate of https://github.com/godotengine/godot/issues/32990 (same cause).

**Closed by Calinou** 2022-11-04 23:11 UTC
Labels: bug, topic:rendering, topic:gui
