### ISSUE TITLE
Godot crashes during lightmap generation

### ISSUE THREAD

**Issue by Antokolos** [godotengine/godot#30789] opened 2019-07-24 08:30 UTC
**Godot version:**

Godot 3.1.1

**OS/device including version:**

Windows 10

**Issue description:**

When I changed light baking to Gen Lightmaps and pressed Reimport, the lightmap generation process was started, but after some time progress freezed and then Godot crashed.

**Steps to reproduce:**
1) Add floor_2.escn and/or female.escn and/or chest_2.dae to the project, select it in the file manager
2) Switch to the Import tab
3) Select Light Baking == Gen Lightmaps
4) Hit reimport

**Models used:**
[floor_2.zip](https://github.com/godotengine/godot/files/3425722/floor_2.zip)
[female.zip](https://github.com/godotengine/godot/files/3425727/female.zip)
[chest_2.zip](https://github.com/godotengine/godot/files/3425815/chest_2.zip)

P.S.: There was an error in console just before crash:
![image](https://user-images.githubusercontent.com/7196697/61778312-52a14d00-ae20-11e9-8721-e66a94bdbc0d.png)

**Comment by qarmin** [comment] 2019-07-24 08:45
Can't reproduce on Ubuntu 19.04 and 3.2.dev.custom_build. adae2b073
Seems that this issue exists with older version of xatlas.
Maybe a cherrypick of some of commits may fix that without any negative effects

**Comment by Antokolos** [comment] 2019-07-24 08:51
@qarmin , I would be glad if this will work in version 3.2 then, I'll be waiting for it :)
But right now it is a common problem, unfortunately :( I've added another model (chest_2.zip), which crashes in the same way to the issue description.

**Comment by KoBeWi** [comment] 2020-09-25 23:56
Can anyone still reproduce this bug in Godot 3.2.3 or any later release?

If yes, please ensure that an up-to-date Minimal Reproduction Project (MRP) is included in this report (a MRP is a zipped Godot project with the minimal elements necessary to reliably trigger the bug). You can upload ZIP files in an issue comment with a drag and drop.

**Comment by akien-mga** [comment] 2020-12-10 22:49
No answer, so closing.

**Comment by akien-mga** [comment] 2020-12-10 22:50
Actually #40035 says it closes this issue, so the issue is likely still valid.

**Comment by qarmin** [comment] 2021-01-21 10:31
Fixed in #44628

**Closed by qarmin** 2021-01-21 10:31 UTC
Labels: bug, topic:rendering
