### ISSUE TITLE
Game closes when reloading scene while using yields

### ISSUE THREAD

**Issue by EdwardAngeles** [godotengine/godot#4658] opened 2016-05-14 23:25 UTC
Ubuntu Gnome / Linux - Build from source  ([last commint](https://github.com/godotengine/godot/commit/7913e792acd656469b29fb90be1dbb7c06a855ba)).

I have this piece of code running:
![screenshot from 2016-05-14 19-24-04](https://cloud.githubusercontent.com/assets/6760623/15271151/7c1ced1e-1a09-11e6-8542-422a7190da3b.png)

And if I try to reload the current scene (`get_tree().reload_current_scene()`) the game closes without dropping any errors.

I also try with `get_tree().call_deferred("reload_current_scene")`, no luck either.

**sample project is in this comment: https://github.com/godotengine/godot/issues/4658#issuecomment-219407248**

EDIT:
It does the same with the yield waiting for idle_frame.

**Comment by kubecz3k** [comment] 2016-05-16 08:08
It would be great if you could provide some minimal example project, it always saves time of core developers if only thing they need to do to reproduce is to download and run.

**Comment by EdwardAngeles** [comment] 2016-05-16 11:48
Here is a little test: [Test.zip](https://github.com/godotengine/godot/files/266035/Test.zip)

**Comment by vnen** [comment] 2016-06-17 00:43
This is the same as #5247. And since I already posted my thoughts in there, I'll close this one.

**Closed by vnen** 2016-06-17 00:43 UTC
Labels: bug, topic:core, topic:gdscript
