### ISSUE TITLE
Visual Script editor nodes incorrect behavior

### ISSUE THREAD

**Issue by Soarex16** [godotengine/godot#17339] opened 2018-03-07 16:18 UTC
**Godot version:** 3.0.2

**OS/device including version:** Windows 10, gtx 1050 ti

**Issue description:** The size of the nodes increases with dragging (a similar error was with the visual shader editor in versions 2.x.x)
https://youtu.be/D82NekS6XZU

**Steps to reproduce:** open "visual pong demo" and drag nodes in ball.vs

**Minimal reproduction project:**
visual pong demo

**Comment by vnen** [comment] 2018-03-07 16:36
That's an old ~~feature~~ bug. Duplicate of #6381.

**Closed by vnen** 2018-03-07 16:36 UTC
