### ISSUE TITLE
Code Completion suggests everything as strings

### ISSUE THREAD

**Issue by Drejzer** [godotengine/godot#77726] opened 2023-06-01 10:21 UTC
### Godot version

4.0.2.stable

### System information

Manjaro Linux 5.15.113-1-MANJARO

### Issue description

When I was trying to figure out #77725 i stumbled upon this:
![image](https://github.com/godotengine/godot/assets/14893831/364b89ce-00b2-4aef-a85e-f10c16936005)

pressing enter results in 
![image](https://github.com/godotengine/godot/assets/14893831/07d53b82-c919-4635-80e2-e1809b6bb11f)

It looks simmilar to #48436 , but it started happening to every code completion and I have absolutely no clue how it happened.

It happened after I moved(using shift+arrow keys to select, tab to indent and alt+arrow keys to move down)  the three dicts in the picture to within the function and added the dict 4.

### Steps to reproduce

Here's roughly what I did 
(might be slightly inaccurate, I was basically messing around to try and see the scope of $77725 when it happened)

1) create an empty script
2) declare a couple of dictionaries
3) declare a function
4) try out code completion within the function
5) create a lambda within the function and try 4) again
6) move the dictionaries' declaration within the function using keyboard shortcuts and try 4)

### Minimal reproduction project

N/A

**Comment by Drejzer** [comment] 2023-06-01 10:52
Restarting the editor fixed it, and so far I'm unable to reproduce it.
typing in `"` does show up everything in quotes and quickly deleting it does "stick" it until you type in more, but once "completed" the quotation marks don't stay for good.

**Comment by HolonProduction** [comment] 2023-11-05 21:24
A quite consistent way to get this behavior is by typing `extends "res://somescript.gd"`. At the beginning of the script.

Also maybe change the title of the issue to something more descriptive like "Code Completion suggest all options as strings"

**Comment by HolonProduction** [comment] 2023-11-21 21:35
The exact requirements for triggering the issue are entering a string on the first line.

**Comment by HolonProduction** [comment] 2023-11-23 11:22
Duplicate of #75774

**Comment by YuriSizov** [comment] 2023-11-23 11:42
> Duplicate of #75774

I would say it's okay to keep both open, since the issue is triggered differently, but your PR can close both.

**Closed** 2023-12-20 14:14 UTC
Labels: bug, topic:gdscript, topic:editor, needs testing

**Comment by jaymehta-g** [comment] 2024-01-31 17:39
Also happens if you put an empty multi line comment string at the top of the file

**Comment by HolonProduction** [comment] 2024-02-01 08:41
> Also happens if you put an empty multi line comment string at the top of the file

Should be fixed as well. Did you try with 4.3.dev2?
