### ISSUE TITLE
Moving a child scenes in subdirectories will break a parent scene

### ISSUE THREAD

**Issue by maldrasen** [godotengine/godot#70268] opened 2022-12-18 18:27 UTC
### Godot version

v4.0.beta8.mono.official.45cac42c0

### System information

Windows 11

### Issue description

Moving a scene that's the child of another scene will unrecoverably break the parent scene. Doing this with a drag and drop at least gives you a warning, but using the 'Move To...' command from the file context menu just breaks things without warning.

Opening the scene thereafter will give you this error:
```
  scene/resources/resource_format_text.cpp:514 - res://Main.tscn:8 - Parse Error: 
  Failed loading resource: res://Main.tscn. Make sure resources have been imported by opening the project in the editor at least once.
  editor/editor_data.cpp:596 - Index p_idx = 1 is out of bounds (edited_scene.size() = 1).
```

### Steps to reproduce

Create a Main scene.
Create a Child scene in a subdirectory and add it to the main scene
Move the child scene into a different subdirectory with "Move To..." from the file context menu.

Get an error dialog:
<img width="220" alt="Screenshot 2022-12-18 122152" src="https://user-images.githubusercontent.com/296053/208313029-a23216c1-54d4-42ae-ba11-ce1d8adaa10b.png">

The Main.tscn file can no longer be opened

### Minimal reproduction project

Trivial to reproduce.

**Comment by KoBeWi** [comment] 2022-12-18 19:29
Duplicate of #69794

**Closed by KoBeWi** 2022-12-18 19:29 UTC
