### ISSUE TITLE
Errors when just opening the editor.

### ISSUE THREAD

**Issue by vicguedez** [godotengine/godot#8382] opened 2017-04-13 02:11 UTC
**Operating system or device - Godot version:**
Windows 10 x86 - Godot 3.0

**Issue description:**
When I open the editor all this errors print out:

```
Activated GL 3.3 contextgetting extensions
total 317
max ubo light: 409
max ubo reflections: 455  ubo size: 144
EXEC PATHP??: E:\Godot 3\Godot.exe
EditorSettings::_get - Warning, not found: filesytem/file_dialog/show_hidden_files
EditorSettings::_get - Warning, not found: import/pvrtc_texture_tool
EditorSettings::_get - Warning, not found: import/pvrtc_texture_tool
OPENING: E:/Godot 3/Project/Centipides (E:::Godot 3::Project::Centipides)
EXEC PATHP??: E:\Godot 3\Godot.exe
running cmdline: "E:\Godot 3\Godot.exe" "-path" "E:/Godot 3/Project/Centipides" "-editor"
EditorSettings::_get - Warning, not found: import/pvrtc_texture_tool
EditorSettings::_get - Warning, not found: import/pvrtc_texture_tool
erasing atlas
**erasing atlas
ERROR: There are still MemoryPool allocs in use at exit!
   At: core/dvector.cpp:69**
EXEC PATHP??: E:\Godot 3\Godot.exe
DETECTED MONITORS: 1
Activated GL 3.3 contextgetting extensions
total 317
max ubo light: 409
max ubo reflections: 455  ubo size: 144
EXEC PATHP??: E:\Godot 3\Godot.exe
ERROR: get_parent_class: Condition ' !ti ' is true. returned: StringName()
   At: core/class_db.cpp:273
ERROR: get_edited_scene_root: Index current_edited_scene out of size (edited_scene.size()).
   At: editor/editor_data.cpp:600
ERROR: get_parent_class: Condition ' !ti ' is true. returned: StringName()
   At: core/class_db.cpp:273
ERROR: environment_set_tonemap: Condition ' !env ' is true.
   At: drivers/gles3/rasterizer_scene_gles3.cpp:924
ERROR: get_parent_class: Condition ' !ti ' is true. returned: StringName()
   At: core/class_db.cpp:273
ERROR: get_parent_class: Condition ' !ti ' is true. returned: StringName()
   At: core/class_db.cpp:273
ERROR: get_parent_class: Condition ' !ti ' is true. returned: StringName()
   At: core/class_db.cpp:273
ERROR: get_parent_class: Condition ' !ti ' is true. returned: StringName()
   At: core/class_db.cpp:273
ERROR: get_parent_class: Condition ' !ti ' is true. returned: StringName()
   At: core/class_db.cpp:273
ERROR: get_parent_class: Condition ' !ti ' is true. returned: StringName()
   At: core/class_db.cpp:273
ERROR: get_parent_class: Condition ' !ti ' is true. returned: StringName()
   At: core/class_db.cpp:273
ERROR: get_parent_class: Condition ' !ti ' is true. returned: StringName()
   At: core/class_db.cpp:273
ERROR: get_parent_class: Condition ' !ti ' is true. returned: StringName()
   At: core/class_db.cpp:273
ERROR: get_parent_class: Condition ' !ti ' is true. returned: StringName()
   At: core/class_db.cpp:273
ERROR: get_parent_class: Condition ' !ti ' is true. returned: StringName()
   At: core/class_db.cpp:273
ERROR: get_parent_class: Condition ' !ti ' is true. returned: StringName()
   At: core/class_db.cpp:273
ERROR: get_parent_class: Condition ' !ti ' is true. returned: StringName()
   At: core/class_db.cpp:273
ERROR: get_parent_class: Condition ' !ti ' is true. returned: StringName()
   At: core/class_db.cpp:273
ERROR: get_parent_class: Condition ' !ti ' is true. returned: StringName()
   At: core/class_db.cpp:273
ERROR: get_parent_class: Condition ' !ti ' is true. returned: StringName()
   At: core/class_db.cpp:273
ERROR: get_parent_class: Condition ' !ti ' is true. returned: StringName()
   At: core/class_db.cpp:273
ERROR: get_parent_class: Condition ' !ti ' is true. returned: StringName()
   At: core/class_db.cpp:273
ERROR: get_parent_class: Condition ' !ti ' is true. returned: StringName()
   At: core/class_db.cpp:273
ERROR: get_parent_class: Condition ' !ti ' is true. returned: StringName()
   At: core/class_db.cpp:273
ERROR: get_parent_class: Condition ' !ti ' is true. returned: StringName()
   At: core/class_db.cpp:273
ERROR: get_parent_class: Condition ' !ti ' is true. returned: StringName()
   At: core/class_db.cpp:273
ERROR: get_parent_class: Condition ' !ti ' is true. returned: StringName()
   At: core/class_db.cpp:273
ERROR: get_parent_class: Condition ' !ti ' is true. returned: StringName()
   At: core/class_db.cpp:273
ERROR: get_parent_class: Condition ' !ti ' is true. returned: StringName()
   At: core/class_db.cpp:273
ERROR: get_parent_class: Condition ' !ti ' is true. returned: StringName()
   At: core/class_db.cpp:273
ERROR: get_parent_class: Condition ' !ti ' is true. returned: StringName()
   At: core/class_db.cpp:273
ERROR: get_parent_class: Condition ' !ti ' is true. returned: StringName()
   At: core/class_db.cpp:273
ERROR: get_parent_class: Condition ' !ti ' is true. returned: StringName()
   At: core/class_db.cpp:273
WARNING: not found: editor_plugins/enabled
path not recognized
path not recognized
path not recognized
path not recognized
path not recognized
path not recognized
path not recognized
path not recognized
path not recognized
path not recognized
path not recognized
path not recognized
path not recognized
path not recognized
path not recognized
path not recognized
path not recognized
path not recognized
path not recognized
path not recognized
REIMPORT BECAUSE: modified .import time0 vs 1492048858
ERROR: get_parent_class: Condition ' !ti ' is true. returned: StringName()
   At: core/class_db.cpp:273
ERROR: get_parent_class: Condition ' !ti ' is true. returned: StringName()
   At: core/class_db.cpp:273
ERROR: get_parent_class: Condition ' !ti ' is true. returned: StringName()
   At: core/class_db.cpp:273
ERROR: get_parent_class: Condition ' !ti ' is true. returned: StringName()
   At: core/class_db.cpp:273
vertex uses functions: 0
vertex uses functions: 0
vertex uses functions: 0
vertex uses functions: 0
vertex uses functions: 0
vertex uses functions: 0
vertex uses functions: 0
vertex uses functions: 0
vertex uses functions: 0
vertex uses functions: 0
vertex uses functions: 0
vertex uses functions: 0
mesege
ERROR: _gl_debug_print: GL ERROR: Source: OpenGL        Type: Undefined behavior        ID: 131222      Severity: Medium        Message: Program undefined behavior warning: Sampler object 0 has depth compare enabled. It is being used with depth texture 938, by a program that samples it with a regular sampler. This is undefined beahvior.
   At: drivers/gles3/rasterizer_gles3.cpp:123
REIMPORTING: res://icon.png
loading scene DEFERED
EditorSettings::_get - Warning, not found: import/pvrtc_texture_tool
EditorSettings::_get - Warning, not found: import/pvrtc_texture_tool
EditorSettings::_get - Warning, not found: import/pvrtc_texture_tool
EditorSettings::_get - Warning, not found: import/pvrtc_texture_tool
```

**Comment by bojidar-bg** [comment] 2017-04-13 09:04
Duplicate of #8105, even if more recent.

**Closed by bojidar-bg** 2017-04-13 09:04 UTC
