### ISSUE TITLE
[BUG] 2D Platformer bug on Android

### ISSUE THREAD

**Issue by jrimclean** [godotengine/godot#1988] opened 2015-05-26 02:02 UTC
I deployed the bundled 2D platformer demo an Android (4.4.2) phone. Everything went smoothly until I attempted to jump through a ledge to get to the rest of the map. After jumping through the ledge, the screen went all funny and the game was no longer playable. The demo plays perfectly on Linux, so it's probably a platform specific thing. Let me know if you need anymore information to hunt this bug down.

**Comment by jrimclean** [comment] 2015-05-26 02:05
I thought I should clarify that the screen becomes gray, and the user controls are still visible.

**Comment by akien-mga** [comment] 2015-11-15 15:37
Likely a duplicate of #2345.

**Closed by akien-mga** 2015-11-15 15:37 UTC
