### ISSUE TITLE
editor toolbar contextual entry visibility determination is unintuitive

### ISSUE THREAD

**Issue by Flavelius** [godotengine/godot#54437] opened 2021-10-30 21:51 UTC
### Godot version

3.3.4.stable.mono.official

### System information

Windows 10

### Issue description

See this video:

https://user-images.githubusercontent.com/8841352/139559317-df8a5666-0250-405e-a441-c38ddb31b25d.mp4

When a meshinstance is selected the 'Mesh' toolbar entry becomes visible, IF: there's no other panel open (in this case the shader-material subresource in the shader editor), but closing this panel doesn't show it, the object has to be reselected to make it show up, which makes it easy to be mistaken as being bugged in both cases of selecting the meshinstance when it automatically opens the other panel and doesn't show the toolbar entry and when closing the other panel where the entry then doesn't show up.

### Steps to reproduce

Have a meshinstance with a shadermaterial subresource using a shader. Select the meshinstance, if the shader panel opened automatically to, there will be no 'Mesh' entry in the toolbar. If it didn't open automatically there will be.
Open the shader editor panel by selecting the subresource. The 'Mesh' entry will be gone. Close the panel. The entry won't come back.

**Comment by Calinou** [comment] 2021-10-30 21:53
Duplicate of https://github.com/godotengine/godot/issues/28211 (same cause).

**Closed by Calinou** 2021-10-30 21:53 UTC
