### ISSUE TITLE
Sprites using Raw values above 1 with Glow & HDR Threshold at 1, does not have any effect

### ISSUE THREAD

**Issue by bubblemilktea-star** [godotengine/godot#73788] opened 2023-02-22 23:00 UTC
### Godot version

4.0 RC3

### System information

Windows 11 3090TI

### Issue description

In Godot 3.x, when the HDR Threshold is at 1 and a Sprite has Raw values above 1, we would see Glow applied to that Sprite.
In Godot 4.0 RC3, when HDR Threshold is at 1 and a Sprite has Raw values above 1, we see no Glow applied. 
Only when the threshold is lowered below 1 can we see the Glow applied.

### Steps to reproduce

1) Create a 2D scene with a WorldEnvironment & Sprite2D with a texture
2) Set WorldEnvironment mode to Canvas & enable Glow
3) Note the HDR Threshold's value at 1
4) Edit the Sprite2D's modulation to have Raw values above 1
5) Observe that no glow effect appears

### Minimal reproduction project

https://github.com/bubblemilktea-star/godot4-glow-bug

**Comment by Calinou** [comment] 2023-02-22 23:02
Duplicate of https://github.com/godotengine/godot/issues/62110.

**Closed by Calinou** 2023-02-22 23:02 UTC
