### ISSUE TITLE
Duplicate shortcuts on MacOS

### ISSUE THREAD

**Issue by k7771911** [godotengine/godot#61782] opened 2022-06-07 16:37 UTC
### Godot version

4.0.dev

### System information

MacOS

### Issue description

Some of the default shortcuts on MacOS are used for multiple actions causing them to behave unexpectedly or being ignored. So far I have found these:

- Command+B - Used for "Play" and "Go to Next Bookmark"
- Command+Comma - "Editor Settings" and "Go to Previous Breakpoint"

### Steps to reproduce

Press the shortcuts, usually nothing happens.

**Comment by Calinou** [comment] 2022-11-01 16:21
Duplicate of https://github.com/godotengine/godot/issues/61782.

**Closed by Calinou** 2022-11-01 16:21 UTC
Labels: bug, archived, platform:macos, topic:editor
