### ISSUE TITLE
[C#] Getting GetWorld2D().DirectSpaceState reference causes an instance of Physics2DDirectSpaceStateSW to be leaked

### ISSUE THREAD

**Issue by pikol93** [godotengine/godot#43329] opened 2020-11-05 09:29 UTC
**Godot version:**
3.2.3.stable.mono

**OS/device including version:**
Windows 10,
Issue not related to graphics

**Issue description:**
Getting a reference to `Physics2DDirectSpaceState` via `GetWorld2D().DirectSpaceState` causes the engine to leak a `Physics2DDirectSpaceStateSW` instance. Getting the reference multiple times doesn't have any effect as only one instance is still leaked.
It seems that the issue is related to C# as the code equivalent in GDScript causes no leaks and works as intended. I've included both GDScript and C# implementation in the minimal reproduction project.

Here's an example console output
```
WARNING: cleanup: ObjectDB instances leaked at exit (run with --verbose for details).
     At: core/object.cpp:2135
Leaked instance: Physics2DDirectSpaceStateSW:1170
Hint: Leaked instances typically happen when nodes are removed from the scene tree (with `remove_child()`) but not freed (with `free()` or `queue_free()`).
Orphan StringName: Physics2DDirectSpaceStateSW
StringName: 1 unclaimed string names at exit.
```

**Steps to reproduce:**
1. Create a new project
2. Create a Node2D scene
3. Attach a C# script to the node
4. Get a reference to `Physics2DDirectSpaceState`

**Minimal reproduction project:**
[Physics2DLeakedInstance.zip](https://github.com/godotengine/godot/files/5493266/Physics2DLeakedInstance.zip)

**Comment by madmiraal** [comment] 2020-11-05 16:22
Duplicate of #39216.

**Closed by madmiraal** 2020-11-05 16:22 UTC
