### ISSUE TITLE
Fly mode gets stuck when holding both middle and right mouse buttons then releasing rmb

### ISSUE THREAD

**Issue by abaky** [godotengine/godot#14373] opened 2017-12-07 11:51 UTC
Godot 3.0 Beta 1 Win10 64bit

Not sure if this is desirable behavior, but in the 3d viewport if you hold middle mouse button and then right click and at the same time release middle mouse button you can release right mouse button and you are still in the free look mode.

**Comment by Zylann** [comment] 2017-12-07 12:43
I think fly mode should not trigger if you hold another button to use orbit/pan.

**Comment by abaky** [comment] 2017-12-07 12:49
here I was trying to trigger fly mode, and godot makes a a switch from orbit to fly, but it looks like the fly mode looks up, you can relese rmb and still fly thru the scene, only when you click rmb and release it then fly mode deactivates, (maybe my original description was not clear)

**Comment by Calinou** [comment] 2017-12-07 12:52
I can reproduce this on Godot Git https://github.com/godotengine/godot/commit/7d9f14e9e49547fdfca67687b7ddee2c25dbcd9b. I think it's nice if you don't want to hold the right mouse button constantly, and it can be easily exited anyway (by clicking with the right mouse button or pressing <kbd>Escape</kbd>).

**Comment by Zylann** [comment] 2017-12-07 12:59
@Calinou you can already use "toggled" fly mode by pressing Shift+F, right-click is the "held" way and should never linger like this

**Comment by icnikerazah** [comment] 2017-12-07 13:11
My opinion, flight mode should not be triggered by mouse.  Can be [shift+c] or similar.

**Comment by Zylann** [comment] 2017-12-07 13:57
@icnikerazah my opinion is, looking around, orbit and pan are short-lived operations, too short for requiring a double-key shortcut. I believe they all deserve a way to be triggered by mouse, they shouldnt conflict. The main reason why freelook also has a toggle mode is that it can *also* be used to move around as in a game for a longer time than orbit&pan while reducing hand strain. It depends on the user's workflow.

**Comment by icnikerazah** [comment] 2017-12-07 15:24
Lock Camera to View feature is missing. i have trouble controling the 3D camera.

**Comment by Zylann** [comment] 2017-12-10 00:11
This bug happens because the SpatialEditorPlugin doesn't receive any event when RMB is released...

**Comment by akien-mga** [comment] 2017-12-17 19:27
Reopening as #14484 was reverted.

**Comment by akien-mga** [comment] 2018-01-02 10:44
Fixed by #14753.

**Comment by Noshyaar** [comment] 2018-01-04 13:12
Reproducible in da4edf8
1. Hold RMB
2. Click MMB or wheel up/down
3. Release RMB

**Comment by Zylann** [comment] 2018-01-04 13:51
Is the same repro also not calling `gui_input` on the last RMB release?

**Comment by akien-mga** [comment] 2018-01-05 13:48
We have now entered release freeze for Godot 3.0 and want to focus only on release critical issues for that milestone. Therefore, we're moving this issue to the 3.1 milestone, though a fix may be made available for a 3.0.x maintenance release after it has been tested in the master branch during 3.1 development. If you consider that this issue is critical enough to warrant blocking the 3.0 release until fixed, please comment so that we can assess it more in-depth.

**Comment by kubecz3k** [comment] 2018-04-03 12:59
seems to be related to a more wide issue: https://github.com/godotengine/godot/issues/9450
We should check if still valid after closing #9450

**Comment by Zylann** [comment] 2018-05-06 03:03
I believe many recent issues are related to the same shitty GUI behaviour... where extra buttons used while dragging something don't send a release event.
Which causes dragging in inspector to leave the mouse the mouse locked.
The same happens with freelook, which ended up using mouse locking because wrapping doesn't work if you don't hold RMB.
Both end up interfering with each other because locking the mouse warps it above the main viewport, which auto-grabs focus 🤦‍♂️

**Closed** 2018-05-25 10:52 UTC
Labels: bug, topic:editor, usability
