### ISSUE TITLE
PopupMenu visual issues in 3.6 RC1

### ISSUE THREAD

**Issue by Alternalo** [godotengine/godot#96149] opened 2024-08-27 05:51 UTC
### Tested versions

- Reproducible in 3.6 RC1
- Not reproducible in 3.5.2 Stable

### System information

Windows 10

### Issue description

Simply adding a PopupMenu to the scene with some items will result in this look in 3.5.2:
![popupmenu_3 5](https://github.com/user-attachments/assets/6b997b96-bc43-4ed5-b240-8985f6e64bfa)

Doing the same thing in 3.6 RC1 will make it look like this
![popupmenu_3 6](https://github.com/user-attachments/assets/2849ac9b-bd9b-433a-9856-2fde7df4b2ca)

And applying separators on items in 3.6 will make it look like this
![popupmenu_with_separators_3 6](https://github.com/user-attachments/assets/7fd44597-35d4-45f4-9b45-c06359850bcd)

### Steps to reproduce

- Create a new UI scene
- Add a PopupMenu node to the scene
- Add items to the Popupmenu node
- Make the node visible, so you can see the issue

### Minimal reproduction project (MRP)

[PopupIssue.zip](https://github.com/user-attachments/files/16757147/PopupIssue.zip)

**Comment by lawnjelly** [comment] 2024-08-27 08:21
Haven't bisected, but likely related to:
https://github.com/godotengine/godot/pull/66711
@rsubtil

**Comment by akien-mga** [comment] 2024-09-03 15:18
> Haven't bisected, but likely related to: #66711 @rsubtil

Indeed, I've confirmed that reverting that PR (and the follow-ups which fixed regressions from that PR) would solve this issue.

That's one option, but a heavy handed one at this stage, it would be good to at least get the issue debugged a bit to see if the problem is a fundamental one that will require e.g. breaking the behavior again, or an oversight that can be patched easily.

**Comment by rsubtil** [comment] 2024-09-03 18:50
I can have a quick look in the coming days, but if the issue is not simple, I don't think I'll have the availability to fix it. I'll leave any findings if that's the case, maybe someone can pick up from there.

**Comment by timothyqiu** [comment] 2024-09-04 00:30
Moving the four `add_constant_override()` calls to `NOTIFICATION_VISIBILITY_CHANGED` (the same as the original #41640) seems to solve the issue.

https://github.com/godotengine/godot/blob/67d4b7346f90a9dc4c92a766e6b256168906e573/scene/gui/popup_menu.cpp#L646-L655

Note that there is also [a later PR](#87462) that removes the need for a separate MarginContainer on the master branch.

**Comment by lawnjelly** [comment] 2024-09-04 06:23
It looks like the fix #87462 itself may introduce more regressions.
This illustrates the pitfalls of cherry picking from 4.x in areas such as GUI, because of the entangled dependencies.

I guess we must also consider @akien-mga 's test approach of reverting all the popup menu related PRs to 3.5 state.

**Comment by lawnjelly** [comment] 2024-09-04 11:15
Fixed by #96557 .

**Closed by lawnjelly** 2024-09-04 11:15 UTC
Labels: bug, regression, topic:gui
