### ISSUE TITLE
Remove TextureRegion popping when Sprite is Selected

### ISSUE THREAD

**Issue by henriiquecampos** [godotengine/godot#27468] opened 2019-03-27 20:35 UTC
**Godot version:** 3.1-stable

**OS/device including version:** Solus 4.0

**Issue description:**

This is a huge decrease in usability. Every single time you select a Sprite the TextureRegion panel will pop on the screen and take focus, so if you were animating some Sprites, switching from one to another, you would have to switch back the AnimationPlayer every-single-time, the Pin option on AnimationPlayer doesn't seem to make any difference. It gets even worse if you are just trying to to setup the rest position of a character composed on many sprites.

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/10171059/55110207-4eedfb80-50b6-11e9-9240-38d32a053eeb.gif)
  

**Steps to reproduce:**
1. Create a scene
2. Add some Sprite nodes (3+)
3. Add a Texture to the Sprites
4. Set `region_enabled` to `true`
5. Add an AnimationPlayer
6. Try to animate the Sprites without getting super mad about the TextureRegion Panel popping every time

**Comment by arkology** [comment] 2019-04-10 04:42
I agree, it also annoys me very much

**Comment by henriiquecampos** [comment] 2019-11-12 13:48
@akien-mga this is not fixed on Godot 3.2.beta

**Comment by akien-mga** [comment] 2019-11-12 14:34
CC @bojidar-bg

**Comment by bojidar-bg** [comment] 2019-11-13 00:33
@henriiquecampos Would be nice if you could prepare a quick gif, so that I can guess the error faster :smiley:

**Comment by henriiquecampos** [comment] 2019-11-13 00:53
@bojidar-bg here:
![04](https://user-images.githubusercontent.com/10171059/68723184-a7ff9680-0596-11ea-84b3-091e5f679ffd.gif)

A smoother workflow, what we had in 3.0 iirc, is:

1. You click on the AnimationPlayer
2. You click on the Node, e.g. Sprite
3. You key the properties you want

Currently the workflow is

1. You click on the AnimationPlayer
2. You click on the Node
3. If it is a Sprite you lose the Animation context and you are into the TextureRegion context
4. You can either click back on the Animation tab or (what I was doing before I remembered just today that you can change back to the Animation tab) repeat the process and instead of clicking you <kbd>CTRL</kbd>+<kbd>LMB</kbd> on the Node

**Comment by bojidar-bg** [comment] 2019-11-13 09:23
I think the issue might be a bit deeper, since this happens (albeit less obnoxiously) with the Shader editor context tab as well.
Indeed the issue is not present in 3.0, probably because most context tabs do not popup automatically whenever you select a node matching them (and Animation is the exception rather than the norm there).

**Comment by bojidar-bg** [comment] 2019-12-02 19:47
Hm, can you confirm that step 3 does not occur any more after either closing the TextureRegion tab or opening the Animation tab manually from the buttons on the bottom row?

**Comment by henriiquecampos** [comment] 2019-12-03 16:40
@bojidar-bg yep in 3.2.beta2 the workflow is:

1. Click on the AnimationPlayer
2. Click on a Sprite node
3. TextureRect tab will pop
4. Click on the AnimationPlayer tab
5. After that you can select Sprite nodes normally without the TextureRect popping.

**Comment by bojidar-bg** [comment] 2019-12-03 19:13
So it would be working as intended after my last PR. I'm not sure how to handle things better, without changing how bottom docks work. Maybe if TextureRegion never popped up automatically?

**Comment by henriiquecampos** [comment] 2019-12-04 00:45
I think it could pop when you enable the "region_enabled", but like, literally right when it is turned `true`, so that this context is explicit to the user. And it can pop whenever `region_enabled` becomes true.

Otherwise, it doesn't pop, but is there. Wachu think?

**Comment by Hargbratch** [comment] 2019-12-04 06:27
Consider making the tabs draggable, whichever is furthest to the right is active.

**Comment by bojidar-bg** [comment] 2019-12-04 09:12
@henriiquecampos That's a good idea indeed, but while Sprite and Sprite3D have a `region_enabled` property, NinePatchRect, StyleBoxTexture, and AtlasTexture do not.
StyleBoxTexture, and AtlasTexture are resources, so the editor can freely pop up for them (similar as other resource editors).
So, NinePatchRect is odd with this proposal.

**Comment by golddotasksquestions** [comment] 2019-12-04 11:38
Should there not be a variable that remembers the last bottom panel sorted on top?

So if I last had the Animation Panel on top, and I click on a Sprite with Region, it should show the Animation Panel on top.
Elif I had the Region Panel on top last, and click on a Sprite with Region, it should show the Region Panel on top.
Elif the Sprite has no Region, but the Region was the last panel on top, it would show the second last panel that was on top
Elif the second last is also not applicable to the Sprite (maybe the second last Panel on top was a Shader and the Sprite has no material assigned), then the third last panel is shown on top .... and so on.

**Comment by henriiquecampos** [comment] 2019-12-04 14:54
@bojidar-bg I think that with the exception of Sprite (which need the `region_rect_enabled` == true first) all other could pop the TextureRegion every time these classes are selected and `region_rect` == Rect(0, 0, 0, 0).

This comes from the assumption that if `region_rect` == `Rect(0, 0, 0, 0)` the region rect wasn't set yet, the TextureRegion pops as kinda of a "reminder". But once you set it, you don't need it to pop again. If you need to redesign the `region_rect` you can either manually click on the TextureRegion tab and define the `Rect` or you can reset `region_rect` to the default value (Rect(0, 0, 0, 0)) in the later case the TextureRegion tab would pop again.

So the "popping" of the TextureRegion is just a handful reminder that only pops when you need to be reminded that, currently, `rect_region` wasn't defined.

**Comment by bojidar-bg** [comment] 2019-12-04 22:26
@henriiquecampos This sounds like a good suggestion (even for sprite, where it could again pop up only for `Rect(0,0,0,0)`). I will try to implemented one of those days :smiley:

**Comment by securas** [comment] 2019-12-22 13:26
Very dificult to control. If one has a sprite a texture region and a shader at the same time and the editor insists on showing only the shader, there is no way to edit the region.

**Comment by securas** [comment] 2019-12-22 13:31
There are other problems:
1. If the sprite as a region and a shader and the editor insists on showing the shader, there seems to be no way to edit the region
2. If the sprite has a shader, the shortcut keys act on the shader. As an example, to duplicate a sprite, its necessary to close the shader and then press Ctrl+D. Otherwise, the editor duplicates a code line from the shader.

**Comment by henriiquecampos** [comment] 2019-12-27 12:38
> There are other problems:
> 
>     1. If the sprite as a region and a shader and the editor insists on showing the shader, there seems to be no way to edit the region
> 
>     2. If the sprite has a shader, the shortcut keys act on the shader. As an example, to duplicate a sprite, its necessary to close the shader and then press Ctrl+D. Otherwise, the editor duplicates a code line from the shader.

I really think we should just integrate the shader editor in the Script Editor for once.

**Comment by Calinou** [comment] 2019-12-27 19:13
@henriiquecampos This means one wouldn't be able to preview the shader in real-time anymore, though.

**Comment by henriiquecampos** [comment] 2019-12-27 21:06
Hmm that's true, it would need to be saved and to switch to the 3d/2d view, right? 🤔

**Comment by akien-mga** [comment] 2021-03-18 15:45
Might be fixed by #45085 if/when it's merged? (CC @KoBeWi)

If not I'd suggest that this might be worth moving to a proposal on https://github.com/godotengine/godot-proposals as that may be a better location for it to gather community feedback and to discuss a potential fix.

**Comment by KoBeWi** [comment] 2021-03-18 22:26
I checked with #45085 and it somehow fixes the issue. Right now the editor seems to pop up by default, while with my PR you need to open it before it starts appearing.

Also this issue was fixed by #30565. When you click the TextureRegion to close it, it doesn't open automatically anymore. Not sure why was this reopened.

**Comment by KoBeWi** [comment] 2023-01-23 23:14
The TextureRegion tab was replaced by inspector button, so there is nothing to pop anymore.

**Closed by KoBeWi** 2023-01-23 23:14 UTC
Labels: enhancement, discussion, topic:editor, usability
