### ISSUE TITLE
Menudialog freezes godot

### ISSUE THREAD

**Issue by IDDQD69** [godotengine/godot#79106] opened 2023-07-06 13:46 UTC
### Godot version

v4.1.stable.official [970459615]

### System information

Arch linux, kernel 6.4.1, wayland, kde Plasma 5.27.6

### Issue description

Godot editor freezes when any menu dialog is opened.

### Steps to reproduce

Open editor, open project and right click on a node or in a editor. Menu opens, nothing can be selected and whole editor freezes.

### Minimal reproduction project

N/A

**Comment by IDDQD69** [comment] 2023-07-06 13:47
This seems to be issue only with wayland.

**Comment by akien-mga** [comment] 2023-07-06 13:59
- Duplicate of #78487

**Closed by akien-mga** 2023-07-06 13:59 UTC
