### ISSUE TITLE
Cannot create C# script because of name of project

### ISSUE THREAD

**Issue by Marre246810** [godotengine/godot#35810] opened 2020-02-01 02:32 UTC
Version: 3.2.stable.mono.offical

OS: Windows 10 Home

The problem: If you do name a project something like I did with the charechters | or : you will get an error when you try to create a c# script.

Recreation:
1. Start Godot
2. Create a project
3. Name the project name something that contains one of these charecters : |
4. Now choose a random node and create a C# script within it.
5. You will now get an error code with something along the line like "You cannot create a c# script"

**Minimal reproduction project:**
Do not know what this is.

**Comment by LamLamLLC** [comment] 2020-02-01 05:52
> If you do name a project something like I did with the charechters | or : you will get an error when you try to create a c# script.
> 
> Error code:
> 
> ```
>  modules/mono/glue/gd_glue.cpp:250 - System.ArgumentException: Illegal characters in path.
> 
>   at System.IO.Path.Combine (System.String path1, System.String path2) [0x00057] in <40b8b083f8564fad98f2f0a051f8ab78>:0 
> 
>   at GodotTools.ProjectEditor.ProjectGenerator.GenGameProject (System.String dir, System.String name, System.Collections.Generic.IEnumerable`1[T] compileItems) [0x0000c] in <381590fb99574f7f9c373a28c11c9d60>:0 
> 
>   at GodotTools.CsProjOperations.GenerateGameProject (System.String dir, System.String name) [0x00000] in <bbcf9c01d92a48cd847d16a734f5511a>:0 
>  modules/mono/mono_gd/gd_mono_utils.cpp:357 - System.IO.FileNotFoundException: Could not find file "C:\Users\marti\Documents\Godot Projects\123\Gamejam#1-123- 123.csproj"
>  modules/mono/editor/csharp_project.cpp:65 - Method failed.
>  modules/mono/glue/gd_glue.cpp:250 - System.ArgumentException: Illegal characters in path.
> 
>   at System.IO.Path.Combine (System.String path1, System.String path2) [0x00057] in <40b8b083f8564fad98f2f0a051f8ab78>:0 
> 
>   at GodotTools.ProjectEditor.ProjectGenerator.GenGameProject (System.String dir, System.String name, System.Collections.Generic.IEnumerable`1[T] compileItems) [0x0000c] in <381590fb99574f7f9c373a28c11c9d60>:0 
> 
>   at GodotTools.CsProjOperations.GenerateGameProject (System.String dir, System.String name) [0x00000] in <bbcf9c01d92a48cd847d16a734f5511a>:0 
>  modules/mono/mono_gd/gd_mono_utils.cpp:357 - System.IO.FileNotFoundException: Could not find file "C:\Users\USER\...\Gamejam#1-123- 123.csproj"
>  modules/mono/editor/csharp_project.cpp:65 - Method failed.
> ```
> 
> **Solution: Change project name**

**Comment by akien-mga** [comment] 2020-02-01 07:51
Please fill the issue template instead of removing it. We ask for those details for a reason.

**Comment by JupiterRider** [comment] 2020-02-01 11:48
I can reproduce that error if my project name contains special characters like : or | .

**Comment by Marre246810** [comment] 2020-02-01 14:12
Ohh sorry! Wasen't paying attention.
Here you go:

Version: 3.2.stable.mono.offical

OS: Windows 10 Home

The problem: If you do name a project something like I did with the charechters | or : you will get an error when you try to create a c# script.

Recreation:
1. Start Godot
2. Create a project
3. Name the project name something that contains one of these charecters : |
4. Now choose a random node and create a C# script within it.
5. You will now get an error code with something along the line like "You cannot create a c# script"

**Minimal reproduction project:**
Do not know what this is.

**Comment by luizcarlos1405** [comment] 2020-02-01 21:56
@Marre246810 I think it's better if you edit the original issue.

Click the three dots
![image](https://user-images.githubusercontent.com/15899938/73599647-70184780-4524-11ea-805a-52b92e424b58.png)

Then click "Edit"
![image](https://user-images.githubusercontent.com/15899938/73599655-7dcdcd00-4524-11ea-8142-544bf35523b9.png)

**Comment by Marre246810** [comment] 2020-02-02 11:07
Thanks!

**Comment by KoBeWi** [comment] 2020-12-21 00:40
Can anyone still reproduce this bug in Godot 3.2.3 or any later release?

**Comment by Tobi-Mob** [comment] 2021-09-10 19:44
Godot 3.3.3: Builds fine for me.

![grafik](https://user-images.githubusercontent.com/69400800/132907489-1e0fc2bc-432a-49b2-92ec-35c35e2b8fc4.png)

Seems like the characters get replaced in the csproj
![grafik](https://user-images.githubusercontent.com/69400800/132907586-73feb6cc-e550-48fe-84d5-3b8e92aca131.png)

On Ubuntu I am able put the project in a "Bad|Name:3"-Directory
This causes the dotnet build to fail with "csproj not found"

But since the dotnet command looks good, I would guess this is a issue with dotnet instead of Godot
>Running: "/usr/bin/dotnet" msbuild "/home/tobi/projects/Godot/Bad|Name:3/Bad-Name-3.sln"
> [...]
>2>/usr/share/dotnet/sdk/5.0.400/Current/Microsoft.Common.props(63,3): error MSB4019: Das importierte Projekt "/home/tobi/projects/Godot/Bad|Name:3/.mono/temp/obj/Bad-Name-3.csproj.*.props" wurde nicht gefunden. 

![grafik](https://user-images.githubusercontent.com/69400800/132908778-50850d9b-bba4-47c2-aebb-90497733a070.png)

**Comment by akien-mga** [comment] 2021-09-20 12:41
Thanks, closing as fixed.

**Closed by akien-mga** 2021-09-20 12:41 UTC
Labels: bug, topic:editor, topic:mono
