### ISSUE TITLE
GPU Particles in 3.4-Beta 3 not emitting if direction vector set to zero.

### ISSUE THREAD

**Issue by aquietmonk** [godotengine/godot#51352] opened 2021-08-07 06:52 UTC
### Godot version

3.4-beta3

### System information

Window 10

### Issue description

Particles do not emit if x, y and z direction vectors are all set to zero.

### Steps to reproduce

Create a 3d scene in a previous version of Godot (I'm using 3.3.2-stable), add a particles emitter and set it up so you can see particles emitting in the editor and at run-time.  Set the "direction" vectors to zero on x, y and z and the emitter will continue to emit as expected.

Now load this project into 3.4-beta3 and the emitter will not emit in either the editor or at run time.  Set one of the 3 vectors to a number other than zero - for example, I set x to one.  The particles will now start emitting in both the editor and when run.

Honestly, I think this makes sense but I have a big project and because the behaviour changed it took me some time to track down why some of my particles weren't showing when the game was run!

**Comment by akien-mga** [comment] 2021-08-07 07:34
That's a duplicate of https://github.com/godotengine/godot/issues/51043, but indeed you identified the problem correctly. Let's continue discussion there.

**Closed by akien-mga** 2021-08-07 07:34 UTC
