### ISSUE TITLE
Sometimes the Show Desktop button makes the editor crash

### ISSUE THREAD

**Issue by venilark** [godotengine/godot#92510] opened 2024-05-29 11:11 UTC
### Tested versions

4.2.1

### System information

Windows 10

### Issue description

Sometimes when I press the Show Desktop button, the editor crashes. Minimizing seems to work just fine.

### Steps to reproduce

Press the button, retry many times.

### Minimal reproduction project (MRP)

Sorry, I can't upload the project.

**Comment by AThousandShips** [comment] 2024-05-29 11:12
Please try in 4.2.2 to make sure this hasn't already been fixed

**Comment by HerrSersch** [comment] 2024-06-14 10:07
Duplicate of  #76709. I can confirm that it still happens in 4.2.2. I've added a comment with more details to the linked issue.

**Closed** 2024-06-14 10:21 UTC
Labels: platform:windows, needs testing, crash
