### ISSUE TITLE
"Recent Nodes" list doesn't always accurately reference to their matching node.

### ISSUE THREAD

**Issue by avencherus** [godotengine/godot#21888] opened 2018-09-09 05:18 UTC
**Windows 64-bit v3.1 alpha 5307043**

When clicking on a recently used node, it sometimes jumps to an unrelated node.

The problem might have some relation to this: https://github.com/godotengine/godot/issues/21883

![godot_master_2018-09-09_08-13-19](https://user-images.githubusercontent.com/13004169/45261324-95288980-b408-11e8-8737-c46d81a29041.png)

**Comment by avencherus** [comment] 2018-09-09 08:27
@garrom Now that you mention it, yes, that is exactly the node I first noticed it on.  Same thing Button -> TouchScreenButton.

**Comment by DualMatrix** [comment] 2018-09-09 08:44
Duplicate of #6535

**Comment by vnen** [comment] 2018-09-10 18:46
Closing as duplicate of #6535.

**Closed by vnen** 2018-09-10 18:46 UTC
