### ISSUE TITLE
Crash upon creation CollisionShape2D

### ISSUE THREAD

**Issue by Thed13** [godotengine/godot#76543] opened 2023-04-28 13:04 UTC
### Godot version

Godot v4.1.dev.custom_build [240ed2829]

### System information

Windows 10, GLES3, Nvidia GTX 1070 (31.0.15.2849)

### Issue description

When creating a CollisionShape2D with double click, pressing enter, or the create button, the editor crashes.

### Steps to reproduce

1.Create a CharacterBody2D scene
2.Create a Sprite2D scene
3.Try to create a CollisionShape2D scene
4.The editor crashes

### Minimal reproduction project

N/A

**Comment by thiagola92** [comment] 2023-04-28 13:30
### Godot version
Godot v4.0.3.rc1.official [2d74ee0e5]

### System information
Fedora Linux 38, Nvidia GTX 1060

### Issue description
Same

### Steps to reproduce
1. Create a Node2D
2. Create a CollisionShape2D
3. Crash

### Video
https://www.youtube.com/watch?v=26yWipHdQkg

**Comment by thiagola92** [comment] 2023-04-28 13:32
Did not happened when using **Godot v4.1.dev1.official [db1302637]**

**Comment by KoBeWi** [comment] 2023-04-28 14:37
This happens because shape editor is initialized in a wrong state. Until it's fixed in official build, as a workaround you can select an existing CollisionShape2D node before creating new shapes (then the crash will no longer happen until you restart the editor).

**Closed** 2023-04-28 15:09 UTC
Labels: bug, topic:editor, crash, regression, topic:2d
