### ISSUE TITLE
Editor ignoring different "warning anotations"

### ISSUE THREAD

**Issue by p-a-s-a-a** [godotengine/godot#67955] opened 2022-10-27 19:35 UTC
### Godot version

4.0 beta 3

### System information

Windows 11 - Vulkan - ...

### The editor ignores some warning anotations
- The editor ignores "narrowing conversions" warning anotations before conditional checkings with user defined methods
- The editor ignores "unused parameter" warning anotations

### Editor ignoring "narrowing conversion" anotations
https://user-images.githubusercontent.com/94804344/198373138-959e6ec5-d02c-4e7f-8965-9e117a70f5ca.mp4

## Narrowing conversion
- Write a new function that recieves some value
- Add typed instructions to the function, so the editor will validate the types
- Call the function in a condition, passing a valid data type so the engine can downcast it
- When you add the "warning anotation" the editor ignores it

## Unused parameter
- Write a new function that recieves some value
- Don't refference any of the recieved value so de editor can warn you
- When you add the "warning anotation" the editor ignores it

### Minimal reproduction project

[WarningAnotations.zip](https://github.com/godotengine/godot/files/9882613/WarningAnotations.zip)

**Comment by Calinou** [comment] 2022-10-27 19:59
Duplicate of https://github.com/godotengine/godot/issues/56592.

**Closed by Calinou** 2022-10-27 19:59 UTC
