### ISSUE TITLE
Weird behavior when changing scale.x to -1 in _Physics_Process vs _Process

### ISSUE THREAD

**Issue by danielkariv** [godotengine/godot#62663] opened 2022-07-03 09:53 UTC
### Godot version

4.0.alpha11.offical [afdae67cc]

### System information

MacOS 12.3.1, Macbook Pro M1.

### Issue description

There is weird behavior when trying to change scale of CharacterBody2D, on X axis to -1 in _Physics_Process method. When we change the scale in _Prcoess method, it change it to new value and keep it till we change it again. 
But when doing so in _Physics_Process, the scale.x is -1 for one frame and than converted to rotation = 180 and scale.y = -1. 
This is could be an issue because when doing for example if condition that includes only Input.is_action_pressed, it will keep change it to -1 (which in result, keep flipping the CharacterBody2D). 
I am not sure if it is a bug or feature but personally I would expect that changing scale.x to -1 will keep it at the same value and not change it. 

### Steps to reproduce

I have copy character controller from my project to a minimal project so you could test it. 
Script is "CharacterController.gd", and the scale changing is in the bottom of _physics_process function.
Input: Keys A/D or Left/Right for looking both directions. 
There is a printing to console of current Scale.x value.

### Minimal reproduction project

[scaleIssue.zip](https://github.com/godotengine/godot/files/9034464/scaleIssue.zip)

**Comment by KoBeWi** [comment] 2022-07-03 13:35
This is not a bug, see this recent issue: #62544
The weird part is that it happens in `_physics_process()`, but not in `_process()` (although it's expected physics stuff will not function properly in `_process()`).

**Comment by aaronfranke** [comment] 2022-07-28 16:48
This is expected, it's a duplicate of #17405. Due to the way that Godot stores transformations, negative X scales are encoded the same way as negative Y scales and a 180 degree rotation, and there's no way to uniquely decompose these.

**Closed by aaronfranke** 2022-07-28 16:48 UTC
Labels: topic:physics, topic:2d
