### ISSUE TITLE
Default project/editor settings box size is way too large on bigger monitors

### ISSUE THREAD

**Issue by homer666** [godotengine/godot#9948] opened 2017-07-28 13:32 UTC
Godot master - e224528
Linux Mint 18.2 Cinnamon x64

Godot automatically calculates the size of the Project/Editor Settings menus based on the main window size, which results in the box being way too big on larger monitors. It makes it really difficult to match up properties with their values, as they're spread too far apart. There should be a hard limit on its size.

![image](https://user-images.githubusercontent.com/27100585/28719359-06a191d6-73ed-11e7-919e-5fafe3b5d35b.png)

**Comment by RandomShaper** [comment] 2017-07-28 13:43
Possible dupe of #7543, fixed by #7929.

**Comment by homer666** [comment] 2017-07-28 14:00
From what I can tell, that is just a workaround (letting the user resize the windows themselves) and doesn't really address the fact that, by default, they're way too huge. It just looks unprofessional, and should probably start off a lot smaller.

**Comment by bruvzg** [comment] 2017-07-28 20:27
It would be nice to have alternating row background colors to match up values without confusing one row with another.

**Closed** 2018-05-07 15:09 UTC
Labels: enhancement, topic:editor, usability
