### ISSUE TITLE
C# project often fails to run when using a referenced project which relies on the Godot.NET.Sdk

### ISSUE THREAD

**Issue by wihrl** [godotengine/godot#65317] opened 2022-09-04 09:13 UTC
### Godot version

4.0.dev 9142904c2

### System information

Win 11, RTX 3060

### Issue description

Sometimes (50-70% of the time) when trying to run a project that has a `<ProjectReference>` to another project (class library) within the solution, the following exception is thrown:
`Godot.NativeInterop.godot_bool Godot.Bridge.CSharpInstanceBridge.Call(IntPtr , Godot.NativeInterop.godot_string_name* , Godot.NativeInterop.godot_variant** , Int32 , Godot.NativeInterop.godot_variant_call_error* , Godot.NativeInterop.godot_variant* ): System.IO.FileNotFoundException: Could not load file or assembly 'ExternalLibrary, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.`

This only seems to happen for libraries that use the Godot SDK (`<Project Sdk="Godot.NET.Sdk/4.0.0-dev8">`). The exception is thrown on the first use of any type from the referenced library.

The really weird thing about this is that it's really inconsistent - sometimes it actually works fine.
I've included a primitive sample project that reproduces this issue.

### Steps to reproduce

1. Create a new C# godot project.
2. Add a new class library to it.
3. Make the library use `<Project Sdk="Godot.NET.Sdk/4.0.0-dev8">`
4. Use any type from that library within the main godot project.

If it works, try running it again a few times. It will crash eventually.

### Minimal reproduction project

[LibTest.zip](https://github.com/godotengine/godot/files/9484354/LibTest.zip)

**Comment by wihrl** [comment] 2022-09-04 09:52
A workaround is to not use the Godot Sdk but instead add manual references to `GodotSharp.dll` and `GodotSharpEditor.dll`

**Comment by raulsntos** [comment] 2022-11-21 19:34
Duplicate of https://github.com/godotengine/godot/issues/68411

**Closed by raulsntos** 2022-11-21 19:34 UTC
Labels: bug, topic:dotnet
