### ISSUE TITLE
Can't create a project due to error caused by windows network drive

### ISSUE THREAD

**Issue by nihilazo** [godotengine/godot#16022] opened 2018-01-24 11:26 UTC
**Godot version:**
3.0-RC3

**OS/device including version:**
Windows 7, x86_64 PC

**Issue description:**
When trying to start a new project, the editor freezes. I beleve this is due to godot trying to make preferences and config files on the local drive when said local drive is mapped to a place on the windows network.

**Steps to reproduce:**
Try and create a project on the virtual "local drive" of a PC where the local drive is mapped to a network location.

**Reproduction example project:**
I cannot give a reproduction example project as the issue is with creating a new project.

**Comment by reduz** [comment] 2018-09-06 18:09
If anyone wants to give a try to seeing why this may fail, feel welcome

**Comment by starry-abyss** [comment] 2018-09-08 17:03
Creating a new project on WD MyBookLive public directory mapped to Z:, running it from editor and project manager, reopening - all worked fine for me, no crashes or freezes on 3.0.5.stable, didn't try later versions... Running Win7 64 bit too.
Tried after device went to HDD standby mode, Godot still creates the project right away, looks like OS is writing the files asynchronously for me.

**Comment by akien-mga** [comment] 2018-10-22 12:13
See also #21070 and #20946.

I think I remember reports about people not able to run projects on e.g. `D:` while the Godot binary is located on `C:` (so even with local but separate partitions or disks), can anyone confirm that, and is the error then similar to the one with networked drives?

**Comment by akien-mga** [comment] 2019-12-13 23:09
Is this still reproducible in 3.1.2 or later?

**Comment by hoontee** [comment] 2020-01-20 07:16
@akien-mga I can't replicate this bug on 3.2-rc1.

**Comment by akien-mga** [comment] 2020-01-20 07:23
Thanks, closing then.

If anyone can reproduce it, please comment and we can reopen it.

**Closed by akien-mga** 2020-01-20 07:23 UTC
Labels: bug, hero wanted!, platform:windows, topic:editor, topic:network
