### ISSUE TITLE
Texture mapping issue with Android

### ISSUE THREAD

**Issue by BastiaanOlij** [godotengine/godot#26185] opened 2019-02-23 03:39 UTC
**Godot version:**
Commit 7f63b0e8cdc0ef2369d3b623c5943e2b6cd1b1ae
Both GLES2 and GLES3 renderer

**OS/device including version:**
Xiaomi Pocophone F1

**Issue description:**
This is what my cube looks like on the desktop:
![image](https://user-images.githubusercontent.com/1945449/53281189-9102e500-3778-11e9-8172-d16ea643acfa.png)

This is what it looks like on the Android phone:
![image](https://user-images.githubusercontent.com/1945449/53281194-a7a93c00-3778-11e9-8657-bd991253e0b5.png)

**Steps to reproduce:**
Apply a texture map to a cube, then run on an Android phone

**Minimal reproduction project:**
[test_android.zip](https://github.com/godotengine/godot/files/2896447/test_android.zip)

**Comment by BastiaanOlij** [comment] 2019-02-25 09:31
I haven't checked this yet but someone suggested this might be an issue with the size of the texture. Reminded me this probably isn't a power of 2 texture.

If it is indeed that, maybe we should add some form of warning?

**Comment by akien-mga** [comment] 2019-02-25 09:33
@reduz just hacked in support for npo2 textures on mobile: 74d0ed22
So it might work now?

**Comment by BastiaanOlij** [comment] 2019-02-28 10:44
@akien-mga hmmm, I didn't see your message in time. It was still not rendering correctly and I just rebased to master. But changing the size of my texture did fix it.

That said, I may not have re-imported it so it may have been fixed but missing a re-import

**Comment by reduz** [comment] 2019-03-01 17:54
This is not a bug for GLES3, as it runs properly (and supports npot textures). Tested and it's working fine.
This was a bug for GLES2 until recently where it was fixed. Tested to confirm.
Closing.

**Comment by akien-mga** [comment] 2019-03-01 18:38
I can still reproduce it with GLES2 (Samsung S3) and the project in the OP.

**Comment by akien-mga** [comment] 2019-03-01 18:56
> I can still reproduce it with GLES2 (Samsung S3) and the project in the OP.

Tested some more to be thorough, with e47915f7:

- Samsung Galaxy S3:
  * GLES3 not supported.
  * GLES2 glitchy (same as in OP, texture actually flickers all the over cube).
![gles2 flicker](https://user-images.githubusercontent.com/4701338/53659336-9752fe80-3c5b-11e9-99ed-42f5797c000f.png)
![gles2 flicher 2](https://user-images.githubusercontent.com/4701338/53659339-9a4def00-3c5b-11e9-9778-b44523411dd1.png)

- Xiaomi Pocophone F1 (same as @BastiaanOlij):
  * GLES3 works fine (differs from @BastiaanOlij's experience on same phone).
  * GLES2 works fine too apart from a lighting issue. There's a sharp "cut" between direct and ambient lighting on the camera facing cube face while it turns:
![screenshot_2019-03-01-19-54-25-371_com godot testandroid](https://user-images.githubusercontent.com/4701338/53659490-fd3f8600-3c5b-11e9-8bc5-986c5a478af6.png)
![screenshot_2019-03-01-19-54-23-758_com godot testandroid](https://user-images.githubusercontent.com/4701338/53659493-003a7680-3c5c-11e9-9f66-57d57dde3f00.png)
(two different faces but that's just because I can't take screenshots fast enough :P the dark one is about the angle where the light "shuts down").

**Comment by reduz** [comment] 2019-03-01 21:30
@akien-mga please delete .import, reimport and re-test.

**Comment by akien-mga** [comment] 2019-03-01 21:49
Still glitching after reimporting the assets, exported with 834a984b.

**Comment by akien-mga** [comment] 2019-03-01 21:50
I no longer get the super weird glitch from @BastiaanOlij's OP though, and can't reproduce it on the Pocophone either, so I guess it's not as bad as it was initially.

**Comment by BastiaanOlij** [comment] 2019-07-06 06:10
I had no problems once I switched to power of 2 textures. Haven't looked at this since. @akien-mga maybe just close this especially with the rewrite to vulkan it probably won't matter?

**Comment by akien-mga** [comment] 2019-07-06 09:13
Yeah, I agree.

**Closed by akien-mga** 2019-07-06 09:13 UTC
Labels: bug, platform:android, topic:rendering
