### ISSUE TITLE
Incorrect interpolation between 2 animations in BlendTree with BlendSpace

### ISSUE THREAD

**Issue by Jackain** [godotengine/godot#26739] opened 2019-03-07 05:11 UTC
**Godot version:**
3.1 Beta 11

**Issue description:**
Got 2 animations, my scales are locked to the same value (Vector2(1,1)), but i try to use BlendSpace1D (Want to setup a Root Motion in 2D) between the 2 animation the scale goes down to Vector2(0.75, 0.75).
See [Video ](https://streamable.com/c1grk)

**Steps to reproduce:**
Well, on the video you can see the skeleton structure, so the bones are RemoteTransforms, separete by different Node2D (Skeleton as root for AnimationPlayer, Upper contain upper body parts and Lower contains lower body parts) Every Node2D and RemoteTransforms got their pos/rot/scale locked down with keyframe in my animations. I just can't see why th scale drop to 0.75 while interpolating. Maybe i'm missing something?

**Comment by pipepkr** [comment] 2019-03-11 02:13
It's the same issue as #23810 ... but nobody has answered yet, they have not even put a label on it 👎

**Comment by Lozamded** [comment] 2019-03-11 03:41
Same problem =(

**Comment by akien-mga** [comment] 2019-03-11 11:03
Closing as duplicate of #23810.

**Closed by akien-mga** 2019-03-11 11:03 UTC
