### ISSUE TITLE
Input Map UI expands every action when a new action or event is added

### ISSUE THREAD

**Issue by m-irigoyen** [godotengine/godot#20843] opened 2018-08-09 12:41 UTC
**Godot version: 3.0.6**

**OS: Windows 10**

**Issue description:**
When an action (or an event) is added in the Project Settings / Input Map window, every action header expands.
Not sure if its a bug or by design, but its incredibly frustrating when working with a lot of actions.

**Steps to reproduce:**
1. Open Project Settings / Input Map
2. Collapse any action you want.
3. Add a new action (or add a new event to any action)
4. Every action expands

**Minimal reproduction project:**
New project

**Comment by groud** [comment] 2018-08-09 18:11
Duplicate of #8728

**Closed by groud** 2018-08-09 18:11 UTC
