### ISSUE TITLE
Error "editor\export\editor_export.cpp:225 - Condition "!preset.is_valid()" is true. Continuing." every time a project is opened in 4.3 Dev

### ISSUE THREAD

**Issue by chrisl8** [godotengine/godot#89023] opened 2024-02-29 21:37 UTC
### Tested versions

- Reproducible in: v4.3.dev.custom_build [0cce6eb15]
[0cce6eb1505f7dd9c0cece2a825b1509cf23f158](https://github.com/godotengine/godot/commit/0cce6eb1505f7dd9c0cece2a825b1509cf23f158)
 - Reproducible in all subsequent versions as well.

 - Not Reproducible in: v4.3.dev.custom_build [f923b58f8]
[f923b58f88e43c09c45ffd155a71d3eb8349bf22](https://github.com/godotengine/godot/commit/f923b58f88e43c09c45ffd155a71d3eb8349bf22)

### System information

Godot v4.3.dev (0cce6eb15) - Windows 10.0.22621 - GLES3 (Compatibility) - NVIDIA GeForce RTX 3080 Ti (NVIDIA; 31.0.15.5161) - AMD Ryzen 9 5900X 12-Core Processor (24 Threads)

### Issue description

This error is displayed every time some projects are opened in 4.3 starting with https://github.com/godotengine/godot/commit/0cce6eb1505f7dd9c0cece2a825b1509cf23f158 when https://github.com/godotengine/godot/pull/87443 was merged.

`editor\export\editor_export.cpp:225 - Condition "!preset.is_valid()" is true. Continuing.`

v4.3.dev.custom_build [0cce6eb15]
[0cce6eb1505f7dd9c0cece2a825b1509cf23f158](https://github.com/godotengine/godot/commit/0cce6eb1505f7dd9c0cece2a825b1509cf23f158)
![image](https://github.com/godotengine/godot/assets/6188278/56d5d71e-4d93-4a3c-b275-f857b421d92a)

v4.3.dev.custom_build [f923b58f8]
[f923b58f88e43c09c45ffd155a71d3eb8349bf22](https://github.com/godotengine/godot/commit/f923b58f88e43c09c45ffd155a71d3eb8349bf22)
![image](https://github.com/godotengine/godot/assets/6188278/b2d26ae1-6d7d-4c02-9b8c-4f810a701e6c)

### Steps to reproduce

You can demonstrate this issue with the Godot Platformer 3D Demo from here:
https://github.com/godotengine/godot-demo-projects/tree/master/3d/platformer

Open that project with v4.3.dev.custom_build [0cce6eb15] and you will see the error every time.
Open it with an older commit and it does not appear.

### Minimal reproduction project (MRP)

Use the Godot Demo project here:
https://github.com/godotengine/godot-demo-projects/tree/master/3d/platformer

### Quick Fix

Removing the `export_presets.cfg` file appears to stop the error.

**or**

Editing `export_presets.cfg` and changing these lines:
```
name="Linux/X11"
platform="Linux/X11"
```
to
```
name="Linux"
platform="Linux"
```
also seems to fix it, so maybe this is really a complicated duplicate of
https://github.com/godotengine/godot/issues/89012

**Comment by akien-mga** [comment] 2024-02-29 22:37
Yes this is a duplicate of https://github.com/godotengine/godot/issues/89012, consolidating there.

**Closed by akien-mga** 2024-02-29 22:37 UTC
Labels: bug, topic:export

**Comment by idbrii** [comment] 2024-12-21 15:52
This could also occur when export_presets.cfg uses the old "HTML5" platform instead of "Web"

Fix:

```diff
-platform="HTML5"
+platform="Web"
```
