### ISSUE TITLE
Any export variables are reset to its default value when save

### ISSUE THREAD

**Issue by sent44** [godotengine/godot#43324] opened 2020-11-05 04:43 UTC
**Godot version:**

Godot 4, the build grab from [here](https://hugo.pro/projects/godot-builds/). Console report as `Godot Engine v4.0.dev.calinou.e16729a8c`

**OS/device including version:**

Windows 10

**Issue description:**

When save, any modify export variables with annotation `@export` in inspector will be reset set to default.
If modify scene file to set variable directly, value is set until save scene.
I do another test with another annotations, `@export_range` has same problem while `@export_node_path` work as it should be.
This issue relate to #43321 but not same.

**Steps to reproduce:**
- Create scene
- Attend script with variables declare with `@export` annotation
- Save and reload scene(variables is not appear in inspector without reload, might be another bug)
- Modify value in inspector
- Save scene
 --
- Open external editor and edit scene file
- Add `num = 123` or such to force set variable value to inspector
- Save and (re)load scene
- Save scene

**Minimal reproduction project:**

[Here!](https://github.com/godotengine/godot/files/5491950/Bug.zip)

**Comment by KoBeWi** [comment] 2020-11-05 09:53
Duplicate of #41690

**Closed by KoBeWi** 2020-11-05 09:53 UTC
