### ISSUE TITLE
ERROR: Cannot instance script because the associated class could not be found. Script: 'res://InitNode.cs'. Make sure the script exists and contains a class definition with a name that m atches the filename of the script exactly (

### ISSUE THREAD

**Issue by diybl** [godotengine/godot#74146] opened 2023-03-01 06:34 UTC
### Godot version

4.0dev

### System information

windows10

### Issue description

ERROR: Cannot instance script because the associated class could not be found. Script: 'res://InitNode.cs'. Make sure the script exists and contains a class definition with a name that matches the filename of the script exactly 

### Steps to reproduce

when i run the exported pck file(c# project)
var node = importedScene.Instantiate();
the the program show the error...

### Minimal reproduction project

godot4.0 RC6

**Comment by Zireael07** [comment] 2023-03-01 07:46
dupe of #73932

Please search before opening issues, thank you

**Comment by diybl** [comment] 2023-03-01 11:47
> 

not dupe

i have two project 
not one

the second project call the first object which export pck and dll

**Comment by Zireael07** [comment] 2023-03-01 13:04
You need to include such details in the original post, otherwise people will easily assume it's a duplicate

**Comment by diybl** [comment] 2023-03-01 13:18
> You need to include such details in the original post, otherwise people will easily assume it's a duplicate

my problem is the same with:
https://github.com/godotengine/godot/issues/36828

in godot 4.0 the problem not sovled.

https://docs.godotengine.org/en/latest/tutorials/export/exporting_pcks.html
the document's way to load c# project pck is wong.

**Comment by Calinou** [comment] 2023-03-01 17:51
- Duplicate of https://github.com/godotengine/godot/issues/73932 (same cause).

> the document's way to load c# project pck is wong.

It's not wrong, but since C# is a compiled language, the compiled DLL must also be present in the PCK (or must be located outside and loaded at the same time as the PCK). This is what we should aim to fix/improve.

**Closed by Calinou** 2023-03-01 17:51 UTC

**Comment by diybl** [comment] 2023-03-02 01:38
> 

so. the problem you have not solved now?

and  what can I do to temporarily fix this problem?

**Comment by Zireael07** [comment] 2023-03-02 08:07
@diybl I know you're not a native speaker of English, but please watch what you write. The "now" makes it sound like you're expecting the devs to jump and fix the problem immediately, and comes across as demanding/rude

**Comment by diybl** [comment] 2023-03-02 09:38
> @diybl I know you're not a native speaker of English, but please watch what you write. The "now" makes it sound like you're expecting the devs to jump and fix the problem immediately, and comes across as demanding/rude

sorry my english is poor 

i read your message use the chrome translate.

but it does'nt have translater to english 

Sometimes I use simple handwritten English to reply in order to save trouble

**Comment by diybl** [comment] 2023-03-02 09:42
> 

i mean that :
If with out fix the bug, could i use the c# patch method to temporarily solve this problem. If not, then I just have to wait for the bug to be fixed

by the way . i found the google translator translate is also rude
