### ISSUE TITLE
"********* listening on port 6007" message in console everytime scene is run

### ISSUE THREAD

**Issue by freemanfromgodotengine** [godotengine/godot#3563] opened 2016-02-03 00:56 UTC
Everytime scene is run (debug) has a console spit that reads:
```
********* listening on port 6007
OK! 72
has connection!
has connection!
CLOSING CONNECTION
```

**Comment by Algrin6** [comment] 2016-02-04 23:23
I think it's not a bug. Those messages just note you about a successful connection between the editor and your game, which is used to debug your game.

**Comment by neikeq** [comment] 2016-02-05 09:41
I find these messages spammy, specially when implementing an HTTP Server whose clients are mostly using [request](https://github.com/request/request) (which creates a new connection for each request).

**Comment by djrm** [comment] 2016-06-19 00:04
tracker here #5031, may be solved by this #5283

**Comment by djrm** [comment] 2016-06-19 16:22
closed by #5283

**Closed** 2016-06-19 16:27 UTC
Labels: bug, topic:core
