### ISSUE TITLE
get_global_rect() ignores rotation

### ISSUE THREAD

**Issue by yuyubibibobibo** [godotengine/godot#35043] opened 2020-01-12 09:18 UTC
**Godot version:**
3.2 beta6
**OS/device including version:**
windows
**Issue description:**
rotation the texturerect with control.rect_rotation += 90，than control.get_global_rect（） to get rect2，rect2 isnot rotation with control，you can use rect2.has_point（mouse_positon）to get bug，sorry for my english
**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by groud** [comment] 2020-01-12 12:26
Honestly your problem is really hard to understand, please explain things step by step and with a little bit more details.

**Comment by KoBeWi** [comment] 2020-01-12 15:41
Repro:
[ReproductionProject.zip](https://github.com/godotengine/godot/files/4050796/ReproductionProject.zip)

**Comment by yuyubibibobibo** [comment] 2020-01-13 05:06
> [复制](https://github.com/godotengine/godot/files/4050796/ReproductionProject.zip)：
> [ReproductionProject.zip](https://github.com/godotengine/godot/files/4050796/ReproductionProject.zip)
> 
> 尽管这可能是有意的。

rect2d is designed that faster detected...

**Comment by groud** [comment] 2020-01-13 08:49
I am still not sure about what the problem is. But if the problem is the global_get_rect() function doesn't account for rotation, this is an expected behavior. There is no way to compute a meaningful rect when a control is rotated.

**Comment by yuyubibibobibo** [comment] 2020-01-13 09:03
> 我仍然不确定是什么问题。但是，如果问题是glo

> I am still not sure about what the problem is. But if the problem is the global_get_rect() function doesn't account for rotation, this is an expected behavior. There is no way to compute a meaningful rect when a control is rotated.

so i canot overlap test... i need rotated texture to check   overlap...

**Comment by groud** [comment] 2020-01-13 09:07
You should not use `get_global_rect()` then, but instead use the `get_global_transform()` (eventually `get_global_transform() * get_transform()` I am not sure) to transform the position you want to check for to the Control local space, and then use `get_rect()` to check for the position.

**Comment by yuyubibibobibo** [comment] 2020-01-13 09:09
> 您不应该使用`get_global_rect()`，而是使用`get_global_transform()`（最终`get_global_transform() * get_transform()`我不确定）将要检查的位置转换为Control本地空间，然后使用`get_rect()`来检查位置。

my cursor is get_global_mouse_position，so

**Comment by groud** [comment] 2020-01-13 09:11
Then use `get_local_mouse_position()` instead.
Something like `get_rect().has_point(get_local_mouse_position())`

**Comment by yuyubibibobibo** [comment] 2020-01-13 09:15
> 然后`get_local_mouse_position()`改用。
> 就像是`get_rect().has_point(get_local_mouse_position())`

i will try it，thx a lot

**Comment by groud** [comment] 2020-01-13 14:59
Alright, closing this for now then. If you have difficulties using 2D transforms, please use the other community channels for this purpose.

**Closed by groud** 2020-01-13 14:59 UTC
Labels: bug, topic:gui

**Comment by yuyubibibobibo** [comment] 2020-01-13 16:13
> Then use `get_local_mouse_position()` instead.
> Something like `get_rect().has_point(get_local_mouse_position())`

why i donot use get_rect，it is local_rect actually？it is not bug？

**Comment by groud** [comment] 2020-01-13 16:18
Yes, get_rect() returns a rect in the Control's space.
I don't see what would be a bug here.

**Comment by yuyubibibobibo** [comment] 2020-01-13 16:33
> 是的，get_rect（）在控件的空间中返回一个rect。
> 我看不出这里有什么错误。



> Yes, get_rect() returns a rect in the Control's space.
> I don't see what would be a bug here.

canot rotation with control，how can we overlap test...why rect2 donot rotation is expected and designed...

**Comment by yuyubibibobibo** [comment] 2020-01-13 16:46
> **Godot版本：**
> 3.2 beta6
> **OS /设备（包括版本：**
> Windows）
> **问题描述：**
> 使用control.rect_rotation + = 90旋转texturerect，而不是使用control.get_global_rect（）来获得rect2，rect2不随控件旋转，您可以使用rect2.has_point（mouse_positon ）得到错误，很抱歉我的英语
> **步骤重现：**
> 
> **最小复制项目：**



> [复制](https://github.com/godotengine/godot/files/4050796/ReproductionProject.zip)：
> [ReproductionProject.zip](https://github.com/godotengine/godot/files/4050796/ReproductionProject.zip)
> 
> 尽管这可能是有意的。

it is used for overlap testing，if rect2 donot rotate，i think that is bug...

**Comment by groud** [comment] 2020-01-13 16:57
Sorry, but your english is really hard to understand. 
Rect2 is not supposed to rotate, it does not handle rotations and this is by design.
If you need to check whether or not a point is inside a control's rect, you have to use the solution above (use `get_rect().has_point(get_local_mouse_position())` or play with transforms to get the point you want to check in the control's local space)

**Comment by yuyubibibobibo** [comment] 2020-01-13 23:56
> 抱歉，但是您的英语真的很难听。
> Rect2不应旋转，它不能处理旋转，这是设计使然。
> 如果需要检查点是否在控件的矩形内，则必须使用上面的解决方案（使用`get_rect().has_point(get_local_mouse_position())`或玩转变换以获取要在控件的本地空间中检查的点）

why local rect is different with global rect，it confuse me...sorry for my english again

**Comment by yuyubibibobibo** [comment] 2020-01-14 00:48
> 抱歉，但是您的英语真的很难听。
> Rect2不应旋转，它不能处理旋转，这是设计使然。
> 如果需要检查点是否在控件的矩形内，则必须使用上面的解决方案（使用`get_rect().has_point(get_local_mouse_position())`或玩转变换以获取要在控件的本地空间中检查的点）

rect2 in Local coordinates still won't rotate with control ...i donot how to overlap testing to use rect2 when control can rotation

**Comment by yuyubibibobibo** [comment] 2020-01-14 03:39
> 抱歉，但是您的英语真的很难听。
> Rect2不应旋转，它不能处理旋转，这是设计使然。
> 如果需要检查点是否在控件的矩形内，则必须使用上面的解决方案（使用`get_rect().has_point(get_local_mouse_position())`或玩转变换以获取要在控件的本地空间中检查的点）

[ReproductionProject.zip](https://github.com/godotengine/godot/files/4057234/ReproductionProject.zip)

**Comment by groud** [comment] 2020-01-14 06:43
The Rect2 object does not handle scale and rotation at all. So the get_global_rect function cannot return something else than the not rotated version of the global Rect2. That's why you have to do you checks in the control's local spacz, where you can make it so the rotation is ignored.

But anyway, this is not the place to ask questions about how to use the engine, please use the other community channels for this purpose. I am pretty sure other people faced the same problem as you do.

**Comment by groud** [comment] 2020-01-14 08:11
My bad, this is what you should use : `Rect2(Vector2(), rect_size).has_point(get_local_mouse_position())`
