### ISSUE TITLE
AnimationTree: animation not playing when using AnimationTree node

### ISSUE THREAD

**Issue by DSangyy** [godotengine/godot#69290] opened 2022-11-28 10:29 UTC
### Godot version

4.0-beta6

### System information

Debian 11

### Issue description

When using AnimationTree node in Godot 4.0-beta6, the animation won't play in the editor window.
Godot 4.0-beta5 doesn't have this problem with the same project.
![a](https://user-images.githubusercontent.com/94308700/204254684-adcec482-4cc5-4824-b275-9a15c19e41b1.gif)
![b](https://user-images.githubusercontent.com/94308700/204254809-d5336c44-5fc4-4d9f-bbf7-09fbd4fc4f68.gif)

### Steps to reproduce

Adding a AnimationTree node.

### Minimal reproduction project

N/A

**Comment by TokageItLab** [comment] 2022-11-28 13:40
Duplicate of #69066.

**Closed by TokageItLab** 2022-11-28 13:40 UTC

**Comment by AbidAlWassie** [comment] 2022-12-25 09:29
I had the same issue with beta 6. But it works fine with beta 10.
