### ISSUE TITLE
Is `# warning-ignore` removed from Godot 4?

### ISSUE THREAD

**Issue by rarysson** [godotengine/godot#83362] opened 2023-10-15 02:37 UTC
### Godot version

v4.1.1.stable.official [bd6af8e0e]

### System information

Windows 11

### Issue description

I was following the doc to [ignore warnings](https://docs.godotengine.org/en/stable/tutorials/scripting/gdscript/warning_system.html). Still, if I used the special comment to ignore the warning, the warning persisted, only if I used the warning_ignore annotation did the warning disappear.

Was this feature removed from Godot 4?

### Steps to reproduce

```gdscript
func _ready():
    # warning-ignore: unused_variable
    var x = 5 # it shows the warning

    @warning_ignore("unused_variable")
    var y = 5 # it doesn't show the warning
```

### Minimal reproduction project

N/A

**Comment by tetrapod00** [comment] 2023-10-15 04:17
Looks like it was removed, and the incorrect documentation is a [known issue](https://github.com/godotengine/godot-docs/issues/8145).

**Comment by AThousandShips** [comment] 2023-10-15 08:39
Duplicate of https://github.com/godotengine/godot-docs/issues/8145

**Closed by AThousandShips** 2023-10-15 08:39 UTC
