### ISSUE TITLE
Poor performance of the launcher and the general editor in Windows 10 1809

### ISSUE THREAD

**Issue by CharlyHardcode** [godotengine/godot#24727] opened 2019-01-02 22:10 UTC
**Godot version:**

3.0.6

**OS/device including version:**

Windows 10 Ver. 1809
8 GB RAM
Intel Core i5 8300H
Intel UHD Graphics 630 - Drivers: 24.20.100.6223
NVIDIA GTX 1050 4GB - Drivers: 417.35

**Issue description:**

There is a considerable delay in the overall functioning of the project manager launcher and editor, with or without a project.

On the Intel UHD 630 GPU, the Godot launcher starts at 10 seconds, the buttons don't respond until after a few seconds.

In the NVIDIA 1050 GPU, the editor is manageable as well as the launcher, but its performance is not optimal.

**Steps to reproduce:**
Just start godot

**Minimal reproduction project:**

**Comment by Ace-Dragon** [comment] 2019-01-02 22:44
Did the editor perform well _before_ Windows 10 decided to deliver the big upgrade?

If yes, it could be one of the usual regressions that Win10 Home users have to deal with when the big updates roll out. If you don't want to deal with this, then either move to the pro edition or start looking at Linux distros.

**Comment by eon-s** [comment] 2019-01-03 02:03
And if the problem is related to the update, try reinstalling the video and audio drivers because the creators updates use to break these (among other things).

**Comment by girng** [comment] 2019-01-03 09:55
i'm on 1803 and no issues.. so i guess i'll do an update... i'll edit this post once it's done

**Comment by olejr** [comment] 2019-01-04 00:08
I'm on WIndows 10 pro x64 1809, gfx card is gtx 1070.
Can't say I've noticed any slowdown/issues.
And no, there's no beta opt in to get 1809.

**Comment by alexfonseka** [comment] 2019-01-10 11:41
I haven't had any issues on the latest update of Win10. Try reinstalling your drivers maybe?

**Comment by Calinou** [comment] 2019-03-24 20:19
@CharlyHardcode Can you reproduce this issue on 3.1 stable or a [daily build](https://hugo.pro/projects/godot-builds/)?

**Comment by akien-mga** [comment] 2019-04-08 13:54
No answer so far, closing as it seems to be system-specific and not reproducible by others on similar configurations.

**Closed by akien-mga** 2019-04-08 13:54 UTC
Labels: bug, platform:windows, topic:editor
