### ISSUE TITLE
C# Mono build project: Attempted to access a missing method.

### ISSUE THREAD

**Issue by Rinma** [godotengine/godot#17057] opened 2018-02-26 20:32 UTC
**Godot version:**
3.0.1 stable.mono.official

**OS/device including version:**
AntergOS/Arch (Kernel 4.15.3)

**Issue description:**
When I open Godot and click "Build project" on the mono tab I get this error
```
 The build method threw an exception.
System.MissingMethodException: Attempted to access a missing method.
```
Mono is verison `5.4.1.7` and I installed `aur/msbuild-stable 15.4_xamarinxplat.2017.11.27.11.23_0xamarin1_ubuntu1404b1-3` and `community/dotnet-sdk 2.1.4-1`.
I now tried this on two devices and get always the same error.

**Steps to reproduce:**
* Open Godot with C# support
* Create a new Project
* Add a new C# script to a node
* If not happen already build the mono project

**Minimal reproduction project:**
[TestGame.zip](https://github.com/godotengine/godot/files/1760200/TestGame.zip)

**Comment by hpvb** [comment] 2018-02-26 21:25
The problem with that project appears to be that the 'Node object' in the scene tree ends up generating code like this:
```c#
public class Node: Node
```

This causes a circular dependency between the two 'Node' classes. Is this a new problem in 3.0.1?

**Comment by neikeq** [comment] 2018-02-26 21:29
Closing as a duplicate of #16327

**Closed by neikeq** 2018-02-26 21:29 UTC
Labels: topic:mono

**Comment by Rinma** [comment] 2018-02-27 14:37
@neikeq I don't get really what this issue has to do with this one. 
It is a problem on Godot 3.0 and Windows. 
On Godot 3.0 I had a working C# project that could run without problems on all my devices. I have this problem since Godot 3.0.1 and mono didn't update since then. 
On the issue #16327 it says they had a missing .dll file. Did some dll files get removed from Godot 3.0 to 3.0.1? Otherwise I don't get why I am now missing this .dll file when it was there before the update.
