### ISSUE TITLE
Exporting a typed array with an enum as element type prints an error message

### ISSUE THREAD

**Issue by Gnumaru** [godotengine/godot#73449] opened 2023-02-16 17:57 UTC
### Godot version

4.0.rc2

### System information

windows 10

### Issue description

When opening in the editor a scene containing a script which exports a typed array property where the element type is an enum, be it defined in the same script or other script, the seemingly harmless error message ```ERROR: Class names can only be set for type OBJECT at: (core/variant/array.cpp:768)``` will be printed.

This happens only for exported properties and only in the editor (playing the scene will not trigger the error message). It does not appear that the editor behavior or runtime behavior is affected in any way due to the error message, all values assigned to the property, either as default values or in the inspector, remain as they should.

![Screenshot 2023-02-16 103136](https://user-images.githubusercontent.com/5783414/219448540-fded69d4-1ba5-49e6-86a6-ba0ddb9b5ec3.png)

![Screenshot 2023-02-16 103615](https://user-images.githubusercontent.com/5783414/219448548-f72e7fea-2929-49fd-aee2-cbdcc3dad523.png)

![Screenshot 2023-02-16 103659](https://user-images.githubusercontent.com/5783414/219448553-f569a6bb-94de-443a-90cf-0c244b2325ea.png)

### Steps to reproduce

In an empty project, in any script, put the following code
```gdscript
enum MyEnum{a,b,c}
@export var myArrC:Array[MyEnum] = [MyEnum.c]
```

### Minimal reproduction project

[ExportEnumArray.zip](https://github.com/godotengine/godot/files/10759077/ExportEnumArray.zip)

**Comment by dalexeev** [comment] 2023-02-17 02:49
Duplicate of #72909.

**Closed** 2023-02-17 06:57 UTC
