### ISSUE TITLE
Latest dev snapshot not keeping session state

### ISSUE THREAD

**Issue by henriiquecampos** [godotengine/godot#26447] opened 2019-03-01 16:20 UTC
**Godot version:** Godot 3.1beta9official

**OS/device including version:** Linux x64 Solus Gnome

**Issue description:**

When closing the editor and opening again it doesnt keep the layout and previously opened scripts.

**Comment by KoBeWi** [comment] 2019-03-01 16:33
This is already fixed on master branch. The fix just didn't make it into this beta.

**Comment by Calinou** [comment] 2019-03-01 16:41
Duplicate of https://github.com/godotengine/godot/issues/26359.

**Closed by Calinou** 2019-03-01 16:41 UTC

**Comment by henriiquecampos** [comment] 2019-03-01 18:10
My bad, sorry
