### ISSUE TITLE
Importing a low resolution png (for pixel perfect games) as a texture2D in Godot 4.0.alpha1 result in blurry result

### ISSUE THREAD

**Issue by astrale-sharp** [godotengine/godot#57463] opened 2022-01-30 19:28 UTC
### Godot version

4.0.alpha1

### System information

```
 ██████████████████  ████████     astrale@Hubris
 ██████████████████  ████████     OS: Manjaro 21.2.1 Qonos
 ██████████████████  ████████     Kernel: x86_64 Linux 5.10.89-1-MANJARO
 ██████████████████  ████████     Uptime: 3h 39m
 ████████            ████████     Packages: 1461
 ████████  ████████  ████████     Shell: fish 3.3.1
 ████████  ████████  ████████     Resolution: 1920x1080
 ████████  ████████  ████████     DE: KDE 5.89.0 / Plasma 5.23.4
 ████████  ████████  ████████     WM: KWin
 ████████  ████████  ████████     GTK Theme: Breath [GTK2/3]
 ████████  ████████  ████████     Icon Theme: breeze-dark
 ████████  ████████  ████████     Disk: 2,2T / 4,0T (59%)
 ████████  ████████  ████████     CPU: AMD Ryzen 7 4800H with Radeon Graphics @ 16x 2.9GHz
 ████████  ████████  ████████     GPU: AMD/ATI
                                  RAM: 6116MiB / 15462MiB

```
### Issue description

When importing a low resolution png picture in godot and tweaking all the import options, It seems I'm unable to get a clean, pixel perfect result like it was the case in 3.x .

Looks like this with Texture2D filter turned off in godot 3.4 
![image](https://user-images.githubusercontent.com/53686698/151714208-add26e3b-8b1f-4b74-9865-6b0856620d8c.png)

Looks like that in 4.0.alpha :
![image](https://user-images.githubusercontent.com/53686698/151714343-2f88f624-fb1f-44b7-a14c-21ff857177c9.png)

### Steps to reproduce

1. Start a new project in godot 4.0
2. drag and drop a new .png file
3. Try all the import options for Texture2D

### Minimal reproduction project

[bugreport4.0.zip](https://github.com/godotengine/godot/files/7966749/bugreport4.0.zip)

**Comment by seppoday** [comment] 2022-01-30 19:32
You need to use "nearest" under sprite CanvasItem > Texture > Filter. You can also check global settings under Project Settings > Render.

**Comment by markdibarry** [comment] 2022-01-30 20:55
They're still blurry in all the preview windows though, right? There's no setting for that, IIRC.

**Comment by Calinou** [comment] 2022-01-30 21:05
> They're still blurry in all the preview windows though, right? There's no setting for that, IIRC.

Yes, this is something that should be addressed separately: https://github.com/godotengine/godot-proposals/issues/2256

Either way, I'll close this as this is intended behavior in 4.0.

**Closed by Calinou** 2022-01-30 21:05 UTC
