### ISSUE TITLE
Using a shortcut for Expand/Collapse Scene Tree doesn't work properly.

### ISSUE THREAD

**Issue by KC098** [godotengine/godot#51911] opened 2021-08-20 09:30 UTC
### Godot version

3.3.3

### System information

Windows 10, AMD Radeon HD 8700, GLES3

### Issue description

When assigning a shortcut key for "Expand/Collapse Scene Tree" it doesn't work, the only way it works is when the mouse hovers on the 3D viewport window.

### Steps to reproduce

1. Assing an Editor shortcut for "Expand/Collapse Scene Tree"
2. Make a Node with a child on it.
3. Click on the Node parent to Expand/Collapse. (Do not move mouse out of the "Scene" window)
4. Won't work
5. Move mouse to "3D Viewport"
6. Works.

**Comment by Calinou** [comment] 2021-08-20 13:29
This is likely yet another issue with editor shortcut focus handling. It's likely fixed in 4.0 but difficult or impossible to resolve in `3.x`.

**Comment by EricEzaM** [comment] 2021-09-20 07:23
Indeed, cannot reproduce on 4.0. Working as expected.

**Comment by akien-mga** [comment] 2021-09-20 08:21
(Likely) duplicate of #52861.

**Closed by akien-mga** 2021-09-20 08:21 UTC
Labels: bug, topic:editor, topic:input
