### ISSUE TITLE
Godot 4.0 Beta 1 crashes after choosing any option in Please Confirm dialog box

### ISSUE THREAD

**Issue by loudan-arc** [godotengine/godot#66263] opened 2022-09-22 15:46 UTC
### Godot version

4.0dev (20d667284)

### System information

Windows 10 21H2, RX 5700 XT MSI EVOKE, Ryzen 5 3600, B450M ASUS TUF PRO GAMING

### Issue description

Both the 32-bit and 64-bit builds of Godot 4 Beta 1 outright just crashes upon getting the initial screen with the dialog box to confirm whether to choose Open Asset Library or Cancel. Godot 3.5 by comparison does run stable by comparison. Attached herein is the memory dump file.

(EDIT 09/23/2022: I have also tried with 22.9.1 drivers, same behavior) Of note is I am running AMD Adrenalin 22.8.2 drivers on an RX 5700 XT, but I've noticed the same behavior with older drivers with the alpha snapshot as well.

https://user-images.githubusercontent.com/20408760/191787773-b41fd847-db53-4323-83cc-449cbc5d0010.mp4

The error logfile:
[Godot_v4.0-beta1_win64.exe.11484.zip](https://github.com/godotengine/godot/files/9627280/Godot_v4.0-beta1_win64.exe.11484.zip)
``

### Steps to reproduce

1) Download Godot_v4.0-beta1_win64.exe.zip from https://downloads.tuxfamily.org/godotengine/4.0/beta1/Godot_v4.0-beta1_win64.exe.zip
2) Run the executable
3) Choose any option from the Please Confirm dialog box.

**Comment by Calinou** [comment] 2022-09-24 15:12
Duplicate of https://github.com/godotengine/godot/issues/57937. As a workaround, disable RTSS on the Godot executable.

**Closed by Calinou** 2022-09-24 15:12 UTC
