### ISSUE TITLE
@export_enum failed on String

### ISSUE THREAD

**Issue by muenraisi** [godotengine/godot#66578] opened 2022-09-29 03:26 UTC
### Godot version

4.0.beta1

### System information

Win10

### Issue description

I copy the following example from help document to godot editor

`@export_enum("Rebecca", "Mary", "Leah") var character_name: String`

But, the editor report error

> Parse Error: "@export_enum" annotation requires a variable of type "int" but type "String" was given instead.

The error log is contradict with the help description

> Export a **String** or **integer** property as an enumerated list of options. If the property is an integer field, then the index of the value is stored, in the same order the values are provided.

### Steps to reproduce

Type the following line in godot editor

`@export_enum("Rebecca", "Mary", "Leah") var character_name: String`

**Comment by akien-mga** [comment] 2022-09-29 07:24
Duplicate of #54828

**Closed by akien-mga** 2022-09-29 07:24 UTC
Labels: bug, topic:gdscript
