### ISSUE TITLE
No Shadow when material is assigned to Mesh and not Node. v3.2.4-rc3 GLES 2

### ISSUE THREAD

**Issue by AlphaVDP2** [godotengine/godot#46592] opened 2021-03-02 14:47 UTC
**Godot version:**
v3.2.4-rc3_win64 GLES 2

**Issue description:**
No shadow is cast from a mesh when material is assigned to the Mesh instead of the Node.
Issue does not appear in GLES 3 mode.
Appears to be a regression as it worked in v3.2.3 in both GLES 2 and 3 modes.

**Steps to reproduce:**
Assign a material only to the Mesh and not the Node.

![shadow_bug](https://user-images.githubusercontent.com/79685520/109665066-25e31900-7bb1-11eb-81be-c8e469d3d46c.png)

**Minimal reproduction project:**
[Shadow_Bug.zip](https://github.com/godotengine/godot/files/6069397/Shadow_Bug.zip)

**Comment by snougo** [comment] 2021-03-02 17:03
can reproduce this issue on macOS too
![Screen Shot 2021-03-03 at 01 00 43](https://user-images.githubusercontent.com/64188282/109685384-2c2ac280-7bbc-11eb-9441-776141536d18.jpg)

**Comment by Calinou** [comment] 2021-03-02 17:20
Duplicate of https://github.com/godotengine/godot/issues/44255.

**Closed by Calinou** 2021-03-02 17:20 UTC
Labels: bug, regression, topic:rendering
