### ISSUE TITLE
Using enum as keys for dictionary doesn't allow dictionary to be defined as a const

### ISSUE THREAD

**Issue by elvisish** [godotengine/godot#90632] opened 2024-04-13 16:30 UTC
### Tested versions

3.5.3 stable

### System information

Windows 10

### Issue description

When using enum as keys for a dictionary, it isn't possible for the dictionary to be defined as a const:
```swift
const damage_range := {
	w.Melee : [2,20],
	w.Pistol : [5,15],
	w.Shotgun : [35,105],
	w.Chaingun : [5,15],
}
```
Will result in the following error:
`Expected a constant expression`

It works if the enum is replaced with simple numbers:
```swift
const damage_range := {
	0 : [2,20],
	1 : [5,15],
	2 : [35,105],
	3 : [5,15],
}
```

### Steps to reproduce

- Create a dicionary using enums as the keys.

### Minimal reproduction project (MRP)

N/A

**Comment by dalexeev** [comment] 2024-04-14 06:01
Can't reproduce:

![](https://github.com/godotengine/godot/assets/47700418/645d6eb3-3ec7-47bc-98ad-da767382fca9)

**Comment by elvisish** [comment] 2024-04-14 20:26
> Can't reproduce:

Thanks, you made me realize this is actually because I accidentally had the enum below the array. This works:
```swift
enum w {
	Melee,
	Pistol,
	Shotgun,
	Chaingun,
}
const damage_range := {
	w.Melee : [2,20],
	w.Pistol : [5,15],
	w.Shotgun : [35,105],
	w.Chaingun : [5,15],
}
```

This gives that non-descriptive error:
```swift
const damage_range := {
	w.Melee : [2,20],
	w.Pistol : [5,15],
	w.Shotgun : [35,105],
	w.Chaingun : [5,15],
}
enum w {
	Melee,
	Pistol,
	Shotgun,
	Chaingun,
}
```

Should I close this or is it technically a bug?

**Comment by lawnjelly** [comment] 2024-04-16 10:58
> Should I close this or is it technically a bug?

Suspect this isn't a bug, just the error message is a bit cryptic.

I don't know enough about gdscript area to know offhand whether this can be easily improved. It might just be a generic way of saying you've put something invalid / unrecognised in the `const`, and it doesn't actually know at this point what this error is, because it hasn't yet parsed the enum (which could make it tricky to give more help in the error message as it would require two passes I'm guessing).

Pinging @godotengine/gdscript just in case, but if no answer in a few days we could probably close this.

**Comment by dalexeev** [comment] 2024-05-08 19:29
Since stability is a high priority in 3.x and there is a workaround, let's close this issue. "GDScript 2.0" (Godot 4.x) **is** a fix for many of the GDScript limitations in 3.x, including such features as out-of-order member resolution.

Please note that we are **not** against some fixes/improvements, but we are highly conservative about 3.x and expect any change to be reasonable and relatively simple/low risk.

Thanks for the contribution nonetheless!

**Closed by dalexeev** 2024-05-08 19:29 UTC
Labels: enhancement, topic:gdscript
