### ISSUE TITLE
AnimationPlayer unexpectedly toggles visible on calling advance and pause repeatedly

### ISSUE THREAD

**Issue by jackycute** [godotengine/godot#89360] opened 2024-03-10 17:15 UTC
### Tested versions

Godot_v4.3-dev4

### System information

Godot v4.3.dev4 - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 2070 SUPER (NVIDIA; 31.0.15.3713) - Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz (8 Threads)

### Issue description

I used `AnimationPlayer.pause()` to pause the animation when user stop moving the mouse and resume playing from the same frame when user interact again.
It works perfectly with Godot_v4.3-dev3 but in Godot_v4.3-dev4 it flips visible unexpectedly, thus I only can use `speed_scale = 0.0` or `seek` to let it stop in the current playing frame without changing the visible.
(maybe related to discrete tracks?)

### Steps to reproduce

Create an AnimationPlayer with a track that toggle any sprite `visible` back and forth and make sure it doesn't have any track set "Autoplay on Load".
Assign `current_animation` with the track and calling `advance` and `pause` in `_process` to step the animation.
Run the scene and you will find the result animation is different from the animation you see in the editor.

### Minimal reproduction project (MRP)

[animationplayer_pause_issue.zip](https://github.com/godotengine/godot/files/14551100/animationplayer_pause_issue.zip)

**Comment by TokageItLab** [comment] 2024-03-11 06:03
Probably duplicate of https://github.com/godotengine/godot/issues/89322, fixed by #89329

**Comment by TokageItLab** [comment] 2024-03-11 18:03
I confirmed https://github.com/godotengine/godot/pull/89329 fixed this.

However, the behavior of <| play_backward looks strange, but that behavior has been the same since the beginning of 4.0, so it does not seem to be related. It would be possible to make a separate issue about that.

**Closed by TokageItLab** 2024-03-11 18:03 UTC
Labels: bug, topic:editor, regression, topic:animation
