### ISSUE TITLE
The program stop receiving keyboard input aside from characters.

### ISSUE THREAD

**Issue by nkongchatri** [godotengine/godot#75404] opened 2023-03-27 19:13 UTC
### Godot version

4.0.1

### System information

Windows 10

### Issue description

The program itself will stop receiving any input other than characters.
For example, 
- F5 will not run the game.
- Ctrl+A will not create new node.
- Ctrl+S will not save the scene.
- Ctrl+Z will not Undo.
- Backspace will not delete characters.
- Enter will not begin a new line.
- Arrow keys will not move the cursor.

But in tile editor, Ctrl+Shift+drag still works to draw rectangle.

### Steps to reproduce

1. Switch between Desktop with Window key+Tab.
2. Done.

And to fix the issue, just tap Windows key again and go back to Godot's window.

### Minimal reproduction project

N/A

**Comment by AThousandShips** [comment] 2023-03-27 19:14
Duplicate of #75296

**Comment by Calinou** [comment] 2023-03-27 19:51
- Duplicate of https://github.com/godotengine/godot/issues/75296.

**Closed by Calinou** 2023-03-27 19:51 UTC
