### ISSUE TITLE
Putting a node below other node with subnodes automatically makes it a child

### ISSUE THREAD

**Issue by mateusak** [godotengine/godot#7077] opened 2016-11-08 18:07 UTC
The new drag and drop function is awesome, but a thing that can get really annoying really fast is that if you drop Node1 below Node2, which has subnodes, it automatically makes Node1 a child of Node2. That means that when you have a bunch of nodes with subnodes and you want to order them, you either don't use drag and drop or do a complicated tetris game moving the nodes with subnodes first, then the normal nodes, and repeat until you get it just right. 
The normal would be that when you put Node1 above Node2 it would go above, when you put Node1 over Node2 it should make Node1 a child of Node2, and when putting Node1 under Node2, it should go under.

**Comment by bojidar-bg** [comment] 2016-11-08 18:10
Duplicate of #6912

**Closed by bojidar-bg** 2016-11-08 18:10 UTC
