### ISSUE TITLE
Add forward etc properties to Spatial

### ISSUE THREAD

**Issue by somnivore** [godotengine/godot#26371] opened 2019-02-27 20:25 UTC
**Godot version:**

a5370b1b1bed3744941c90b4a05d4516aabd4c67

**OS/device including version:**

Arch Linux

**Issue description:**

While it's possible to get the orientation of a spatial by referring to its `transform.basis`, such as `-transform.basis.z` as a manner of determining the transform's forward direction, I think it would be more intuitive, clear and convenient to have properties represent these values, such as `forward` referring to `-transform.basis.z`, `right` to `transform.basis.x`, and `up` to `transform.basis.y` (and likewise, `global_forward` etc for its `global_transform`.)

It would also be good to be able to assign to these properties, e.g. assigning a vector to `forward` would orient the object to face that direction, similarly to `look_at()`, but also with `up` and `right` for easier ways of, for example, getting an object (such as a Sprite3D or MeshInstance) to align with a floor (e.g. setting `up` to the floor's normal.)  Currently when assigning to an object's basis, the object deforms, which is often not desired; getting an object to orient itself so that its `up` points in a particular direction requires a roundabout method, such as using `look_at()` then rotating around an axis (often requiring trial and error to get correct.)  Being able to just assign `up` to a particular direction (such as by subtracting one position from another) would make this matter much easier.

**Comment by Zylann** [comment] 2019-02-27 21:15
Note that being able to assign the 3 axes from `Spatial` is actually not just simplifying the case, it also brings a bunch of assumptions which limits it more than you think.
Setting `forward` only would basically have no choice but to do some partially default `look_at(direction, Vector3(0, 1, 0))`, which by the way still needs to expect a negative vector because OpenGL convention. Also what about right and up? You can't just set them either without defaulting another axis under the hood to fix all possible cases, which may result in one of the many valid orientations that you might not want (which is what your trial and error is about, finding the axis that YOU want).
If the object deforms when setting `basis`, it might be that you are setting an invalid basis to begin with.

**Comment by KoBeWi** [comment] 2019-04-29 21:32
Seems like duplicate of #17200

**Comment by clayjohn** [comment] 2019-04-29 22:59
@KoBeWi your right, good catch. Closing as duplicate of #17200

**Closed by clayjohn** 2019-04-29 22:59 UTC
Labels: enhancement, topic:core
