### ISSUE TITLE
`ImageTexture` created from thread leaks memory on `Compatibility` renderer

### ISSUE THREAD

**Issue by yukinogatari** [godotengine/godot#92432] opened 2024-05-27 14:31 UTC
### Tested versions

Reproducible in: v4.3.dev3.official [36e943b6b], v4.3.dev4.official [df78c0636], v4.3.dev5.official [89f70e98d], v4.3.dev6.official [89850d553]
Not reproducible in: v4.2.2.stable.official [15073afe3], v4.3.dev1.official [9d1cbab1c], v4.3.dev2.official [352434668]

### System information

Godot v4.3.dev6 - Windows 10.0.19045 - GLES3 (Compatibility) - NVIDIA GeForce RTX 3070 (NVIDIA; 31.0.15.4633) - AMD Ryzen 9 7900X 12-Core Processor (24 Threads)

### Issue description

When creating an `ImageTexture` on a subthread while using the Compatibility renderer, the underlying data isn't properly freed when the resource goes away. As best as I can tell, this issue first appeared in v4.3.dev3 and is still present as of v4.3.dev6.

Additionally, loading the `Image` into memory on the subthread, then creating an `ImageTexture` using it on the main thread does not exhibit the same leaky behavior. (I am aware of the warnings against interacting with the GPU on a subthread, so I know that's probably the "correct" way to do this, but still.)

**Compatibility**:
![image](https://github.com/godotengine/godot/assets/680110/488ce6f1-15bf-4947-bcd2-59eae6c7fac0)

**Forward+**:
![image](https://github.com/godotengine/godot/assets/680110/df039e74-378a-4d6c-aa7f-c3eafa1af7f5)

### Steps to reproduce

1. Run the MRP in v4.3.dev3 or later.
2. Go to the debugger's monitors tab and watch the static memory value slowly climb. Note that video memory and texture memory values do **not** rise with the static memory, suggesting it's the underlying `Image` data that isn't getting freed.
3. Change the renderer from Compatibility to Forward+ and run the project again.
4. Static memory remains constant, as expected.
5. Changing `enable_thread` at the top of `main.gd` to false also causes memory usage to remain flat, as expected.

### Minimal reproduction project (MRP)

[image-memory-leak.zip](https://github.com/godotengine/godot/files/15456759/image-memory-leak.zip)

**Comment by clayjohn** [comment] 2024-05-27 19:06
This is most likely caused by our changes to WorkerThreadPool and resource loading. Thankfully I can report this has already been fixed for beta1. 

I tested on 8e2141eac534f6984bb0bdbcefbd17de27ae0993 and confirm there is no memory leak anymore. Most likely fixed by https://github.com/godotengine/godot/pull/90913 (as this looks like a duplicate of https://github.com/godotengine/godot/issues/89585)

**Closed by clayjohn** 2024-05-27 19:06 UTC
Labels: topic:rendering, regression
