### ISSUE TITLE
Drag and Drop preview is broken on Android

### ISSUE THREAD

**Issue by allkhor** [godotengine/godot#33534] opened 2019-11-11 07:21 UTC
**Godot version:** master 28294b1f

**OS/device including version:**
Android 5, 7, 9

**Issue description:**
When you try to drag object it's preview not update correct.
Regression from 9cc66495cfb6393 CC @jeremyz 
Maybe we can revert this commit while not found a good implementation?
Also maybe related issues: #33470, #33459

**Steps to reproduce:**
1) Export project on Android.
2) Try to drag the color.

**Minimal reproduction project:**
[Gui Drag And Drop Demo.zip](https://github.com/godotengine/godot/files/3830024/Gui.Drag.And.Drop.Demo.zip)

**Comment by akien-mga** [comment] 2019-11-11 07:31
Duplicate of #33428, #33459 and #33470.

**Closed by akien-mga** 2019-11-11 07:31 UTC
