### ISSUE TITLE
Unusual behavior with KinematicBody2D and LineShape2D collisions

### ISSUE THREAD

**Issue by N0hbdy** [godotengine/godot#12393] opened 2017-10-25 05:44 UTC
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Mac OSX, Godot v3.0.alpha.custom_build.bf5a927

**Issue description:**

Set up a room with static collider walls and collision shapes as lines, and set a KinematicBody2D moving towards one.  On colliding with a wall, I set the velocity to the other direction.  I'd expect that it starts moving in the other direction, but instead it just stays stuck to the wall.  I'm either missing something really simple (probable) or I'm tots messing up vectors, but help would definitely (err) help!

**Steps to reproduce:**
Play the example project.  It only works if you set the velocity to be Vector2(100, 0) and then Vector2(-100, 0) (+x direction to -x direction); other directions (-X, +/-Y) don't work.

You can also switch out the `move_and_collide` with `move_and_slide` as I'm getting the same results.

**Link to minimal example project:**

[example.tar.gz](https://github.com/godotengine/godot/files/1413372/example.tar.gz)

**Comment by Dillybob92** [comment] 2017-10-25 09:06
hmm, some of your collision shapes were scaled, but that still did not fix this. I tried to set scales all to 1, 1 but issue is still present

**Comment by cbscribe** [comment] 2017-10-25 17:43
The problem seems to be with LineShape2D. If you change the wall collision shape to any other (RectangleShape2D, SegmentShape2D, CircleShape2D), the bounce works as expected.

I'm going to do some testing with the LineShape2D and see if we perhaps have found a bug.

**Comment by cbscribe** [comment] 2017-10-25 17:49
Possibly related:
#7920

**Comment by MarianoGnu** [comment] 2017-11-26 12:47
line collider prevents moving from one direction to the other, this is probably caused because the kinematic body stops over the line itself, then the collider can't realize what side of the line you are and stop movement on both directions, this means the margin property of kinematic body is not taken in account with line_shape collisions?

**Comment by eon-s** [comment] 2017-11-26 19:02
This seems to be duplicate of #9332 
Line shapes never worked since 2.0 at least.

**Comment by mhilbrunner** [comment] 2018-04-10 16:13
Closing as a duplicate of https://github.com/godotengine/godot/issues/9332.

**Closed by mhilbrunner** 2018-04-10 16:13 UTC
Labels: bug, topic:physics
