### ISSUE TITLE
Nested GUI components reset their position for themselves and parents when a different property is changed

### ISSUE THREAD

**Issue by divmgl** [godotengine/godot#16405] opened 2018-02-05 00:24 UTC
Godot 3.0

![35762959-68815f0a-0856-11e8-9282-6a2dd112b786](https://user-images.githubusercontent.com/5452298/35784120-4543f14c-09c8-11e8-9948-07915833a11e.gif)

**Comment by girng8rgtrhgtrh** [comment] 2018-02-05 05:50
what's your node hierarchy like? for example, some nodes under a margin container for example, will have their position changed

**Comment by divmgl** [comment] 2018-02-05 06:00
@girng8rgtrhgtrh thanks for replying. The node was under a margin container but that margin container was at (0, 0) and its position was reset too. If this is intended functionality, I guess my question is why does it go to (16, 7)?

**Comment by volzhs** [comment] 2018-02-05 06:56
would you make a sample project and exact steps to reproduce?

**Comment by groud** [comment] 2018-02-05 07:07
That's normal. When a control node is within a container, it's the parent which decides the position/margin of the child node.

**Comment by akien-mga** [comment] 2018-02-13 13:05
@groud Since it's not a bug but apparently misleading enough to appear as such, is there any way we could improve the UX? Maybe disable the edition of properties that are overridden by a parent?

**Comment by groud** [comment] 2018-02-13 13:13
@akien-mga That would be a great idea, but I would wait the rewrite of the Inspector before improving that. 
I think the ideal solution would be to let the parent decide which properties a child node should expose to be layouted. For example, the expand / fill flags are present on all control nodes, while they are useful only if they are in a BoxContainer or a Splitcontainer (maybe other ones too). Instead of hardcoding those values in all control nodes, we could find a way to make a child control node retrieve the list of properties it should expose from it's parent.

**Comment by Calinou** [comment] 2021-09-01 20:17
Duplicate of https://github.com/godotengine/godot/issues/38802 (will be addressed by https://github.com/godotengine/godot/pull/30623).

**Closed by Calinou** 2021-09-01 20:17 UTC
Labels: enhancement, topic:gui

**Comment by divmgl** [comment] 2021-09-15 23:51
Wow! Thanks for taking care of this! I can't believe it's been three years already.
