### ISSUE TITLE
Bug with alpha in StandardMaterial3D

### ISSUE THREAD

**Issue by frankiezafe** [godotengine/godot#52261] opened 2021-08-30 16:11 UTC
### Godot version

4.0 dev (61d681cfb9a89f5c32a6c85e8f1cf53360c6eddb)

### System information

Linux Mint 20.1, nvidia-driver-470, 

### Issue description

When enabling alpha + depth_prepass_alpha in a material, the result is a mix with a black copy of the mesh impossible to access via the shader passes (vertex, fragment or light).

When enabling alpha with only depth_draw_opaque, the alpha is correct but there is no shadows.

screenshot: https://gitlab.com/frankiezafe/godot4-alpha-issue/-/raw/master/godot4_alpha_issue.png

### Steps to reproduce

open the project: https://gitlab.com/frankiezafe/godot4-alpha-issue

**Comment by Calinou** [comment] 2021-08-30 16:33
Duplicate of https://github.com/godotengine/godot/issues/39282 and https://github.com/godotengine/godot/issues/50124.

**Closed by Calinou** 2021-08-30 16:33 UTC
