### ISSUE TITLE
Object ID increments (or being created) forever in when calling create_from_image()

### ISSUE THREAD

**Issue by chucklepie** [godotengine/godot#57697] opened 2022-02-06 09:43 UTC
### Godot version

3.4.2

### System information

PopOS

### Issue description

So, the number of objects created in the debugger is not increasing so I think this is more a visual bug than a potential memory overflow error.

With the following two lines of code
```
		var itex = ImageTexture.new()
		itex.create_from_image(tex)
```

In this case 'tex' is an image grabbed from
```
var tex=$AnimatedSprite.frames.get_frame("normal",0).get_data()
```

The debugger is at line 81. Observe the object id once I step the code:

https://user-images.githubusercontent.com/12863685/152675233-67614c7a-03b0-4275-b605-16dbaf74dfd1.mp4

### Steps to reproduce

My code creating the fault is above, I don't know if it's specific to the way the image was created, the texture type, my OS, etc.

**Comment by Calinou** [comment] 2022-02-06 11:09
@chucklepie Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

**Comment by timothyqiu** [comment] 2022-02-06 13:38
I think this is caused by a `ImageTexture` bug. Possible duplicate of #25209.

**Comment by Calinou** [comment] 2022-02-06 13:42
Duplicate of https://github.com/godotengine/godot/issues/25209.

**Closed by Calinou** 2022-02-06 13:42 UTC
Labels: bug, topic:core, needs testing

**Comment by chucklepie** [comment] 2022-02-06 16:04
@Calinou thanks. The reason I didn't create project is it takes a lot of effort sometimes to create from a larger project and if the solution/bug is known or presumed easy to recreate I don't create a project unless it's needed as the answer might be immediately known. Thanks.
