### ISSUE TITLE
Vertical scrollbar is visible in all popup menus when using a custom display scale

### ISSUE THREAD

**Issue by passivestar** [godotengine/godot#89482] opened 2024-03-14 14:42 UTC
### Tested versions

v4.3.dev.custom_build [da945ce62]

Wasn't happening in 4.2.1

### System information

Godot v4.3.dev (da945ce62) - macOS 14.2.1 - Vulkan (Forward+) - integrated Apple M1 Max - Apple M1 Max (10 Threads)

### Issue description

It's like this in every popup menu:

<img width="683" alt="image" src="https://github.com/godotengine/godot/assets/60579014/9a38d946-f1b4-4143-85d2-35e1752ab42f"><br>

**_EDIT: Correction, this has nothing to do with a theme, this is with no theme:_**

<img width="826" alt="image" src="https://github.com/godotengine/godot/assets/60579014/ad5a4c38-3abd-4781-b1c9-520b6c55eabc">

### Steps to reproduce

~~Use [this theme](https://github.com/passivestar/godot-minimal-theme) with 4.3~~

~~This might be mac-specific because I asked another person and found out that it's not happening on windows~~

Open 4.3 and set custom display scale to 1.6

### Minimal reproduction project (MRP)

N/A

**Comment by passivestar** [comment] 2024-03-14 14:55
> Can you test if it's fixed by:
> https://github.com/godotengine/godot/pull/89462

alas, not fixed by that PR

**Comment by kitbdev** [comment] 2024-03-15 21:11
- maybe related https://github.com/godotengine/godot/pull/87462

It might be caused by the content margins on the scroll container's theme.

**Comment by Koyper** [comment] 2024-04-13 17:26
#86553 should fix this issue, as I noticed and fixed it there. It was caused by the changes in #87462 per the comment above. At fractional content scales greater than 1.0, truncation of the menu content height during the minimum size calculation can leave the total control menu height slightly shorter than the content, which causes the scroll container to show the vertical scrollbar.

**Comment by passivestar** [comment] 2024-04-18 15:34
> Fixed by https://github.com/godotengine/godot/pull/86553

I'm afraid not

<img width="600" alt="Screenshot 2024-04-18 at 19 32 01" src="https://github.com/godotengine/godot/assets/60579014/3ebf5b99-5db4-46ca-8a43-3d543be4d413">

**Comment by smnast** [comment] 2024-04-19 01:05
It seems, in fact, to not be fixed by #86553.
```c++
minsize.height += 0.5 * win_scale; // Ensures enough height at fractional content scales to prevent the v_scroll_bar from showing.
```
Adding 0.5 before `set_min_size()` truncates to integers rounds down when the decimal height is less than 0.5, like `round()`. Would it not make more sense to ceil the values instead?

**Comment by passivestar** [comment] 2024-04-22 11:54
@akien-mga should this be reopened?

**Comment by Koyper** [comment] 2024-04-24 15:56
> Adding 0.5 before `set_min_size()` truncates to integers rounds down when the decimal height is less than 0.5, like `round()`. Would it not make more sense to ceil the values instead?

I think you're right about this, and I'm not sure exactly why the rounding down behavior was working correctly (it tested correctly). I changed it so that #91114 uses `ceil()` for consistency with the fix for embedded windows.

**Closed** 2024-04-25 15:50 UTC
Labels: bug, regression, topic:gui
