### ISSUE TITLE
Unwrap on scene import doesn't work on 4.0 beta 3

### ISSUE THREAD

**Issue by elvisish** [godotengine/godot#67596] opened 2022-10-18 22:34 UTC
### Godot version

4.0 beta 3

### System information

Windows 10

### Issue description

According to the baked lightmap docs, setting Light Baking mode to Gen Lightmaps (or Static Lightmaps in 4.0) will automatically unwrap UV2 and generate lightmaps, however when trying this with a glb exported from Blender, I get the error:
![image](https://user-images.githubusercontent.com/16231628/196557688-308a15f4-56fb-4426-b935-d74131f9e773.png)

### Steps to reproduce

- Import a glb with Light Baking mode to Static Lightmaps in the Import tab
- Add a LightmapGI node to the scene
- Click Bake Lightmaps and choose a location

**Comment by Calinou** [comment] 2022-10-19 22:08
@elvisish Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

**Comment by lyuma** [comment] 2023-02-23 11:05
One of the known causes of this issue with using `-col` or `-convcol` is being addressed in #73814.

Since there is no reproduction project and I can't reproduce it exactly, I'm going to close this issue.

@elvisish if you do still encounter this issue with a 4.0 release candidate, please feel free to comment with a small project that reproduces the problem, and I will reopen it so that we can fix it.

**Closed by lyuma** 2023-02-23 11:05 UTC
Labels: needs testing, topic:import, topic:3d
