### ISSUE TITLE
Cannot open use ress// file while on the engine

### ISSUE THREAD

**Issue by Nagodot** [godotengine/godot#65426] opened 2022-09-06 14:56 UTC
### Godot version

3.5 stable

### System information

Android

### Issue description

Dear godot,
I have been using godot on my androis , but i came a acrose a big problem that cause me to block using godot when i first use godot and create a new project everything was fine i can use and open ress// file but ass soon as i quit and moved some asset file on the file i saved for godot when i reopen it everything turns nightmare i can only see ress// file and cannot see whats under it thatswhy i cannot use my asset and im stuck in my project i click everytime on ress// file but i cannot ise it its a bug pls fix it godot this is my last hope pls

### Steps to reproduce

I dont know how to solve it since im a beginner

**Comment by Nagodot** [comment] 2022-09-06 15:46
Its not a exported project i have just started working on it and where is
the user// you will be clear if i just give you pics as you can see i can
open and close favorites file on the docs but there is no option in res://
to open or close but i have on my assets in the file as you can see in the
second pic so if i can not acces my asset how could i make the game and i
cannot find user// any where on the screen pls fix it

**Comment by akien-mga** [comment] 2022-09-06 15:58
Duplicate of #63981, this should be fixed in 3.5.1 RC 1, could you confirm? https://godotengine.org/article/release-candidate-godot-3-5-1-rc-1

**Closed by akien-mga** 2022-09-06 15:58 UTC
