### ISSUE TITLE
[Godot 3.6 beta 1] Crash when using thread

### ISSUE THREAD

**Issue by dqdthanhthanh** [godotengine/godot#76067] opened 2023-04-14 18:55 UTC
### Godot version

3.6 beta 1

### System information

Mac Air M1 2020

### Issue description

[Godot 3.6 beta 1] Crash when using thread

### Steps to reproduce

Convert project from 3.5 to 3.6. Everything works normally. Except for the part that uses thread to process data.
https://imgur.com/a/RAT9P1r

### Minimal reproduction project

[logs.zip](https://github.com/godotengine/godot/files/11236270/logs.zip)

**Comment by clayjohn** [comment] 2023-04-14 19:12
@lawnjelly Looks like the backtrace has a few apparently unrelated things in it, including physics interpolation and some GUI functions.

**Comment by lawnjelly** [comment] 2023-04-16 09:24
The crash logs look to be garbage (not quite sure what causes this, usually when the database doesn't match the program, but I don't know how godot generates these). Will need an MRP to investigate, as there is literally nothing to go on here.

**Comment by lawnjelly** [comment] 2023-08-14 17:47
Closing as there is no minimum reproduction project, and no info to go on here. Can reopen if more info provided.

**Closed by lawnjelly** 2023-08-14 17:47 UTC
Labels: bug, topic:core, crash, regression
