### ISSUE TITLE
Tools and templates for Windows, complied on Linux, can not run

### ISSUE THREAD

**Issue by volzhs** [godotengine/godot#44386] opened 2020-12-15 03:48 UTC
**Godot version:**

3.2.4.beta fd6b3060c1

**OS/device including version:**

Kubuntu 20.10 / Windows 10

**Issue description:**

I complied Windows tools and templates.
```
$ scons -j 14 platform=windows bits=64 verbose=no target=release_debug debug_symbols=no
```

And I got errors below and can not run.
```
$ wine ./godot.tools.64.exe
00f4:err:module:import_dll Library libwinpthread-1.dll (which is needed by L"godot.tools.64.exe") not found
00f4:err:module:import_dll Library libgcc_s_seh-1.dll (which is needed by L"godot.tools.64.exe") not found
00f4:err:module:import_dll Library libstdc++-6.dll (which is needed by L"godot.tools.64.exe") not found
00f4:err:module:LdrInitializeThunk Importing dlls for L"godot.tools.64.exe" failed, status c0000135

$ wine ./windows_64_release.exe
00f4:err:module:import_dll Library libgcc_s_seh-1.dll (which is needed by L"windows_64_release.exe") not found
00f4:err:module:import_dll Library libstdc++-6.dll (which is needed by L"windows_64_release.exe") not found
00f4:err:module:LdrInitializeThunk Importing dlls for L"windows_64_release.exe" failed, status c0000135
```
Tested on Windows 10 natively, and had exact errors.

**Steps to reproduce:**
1. compile tools and templates for windows on linux
2. run it on wine or window.

**Minimal reproduction project:**

**Comment by volzhs** [comment] 2020-12-15 03:49
probably related to #44018?
cc @lyubomirv @akien-mga @bruvzg

**Comment by bruvzg** [comment] 2020-12-15 05:53
Probably the same issue as #44304, but in case of 3.2 Linux `use_static_cpp` option (default to False) is overriding Windows one (order is different since in 3.2 it's `x11`, and in master it's `linuxbsd`).

**Comment by akien-mga** [comment] 2020-12-15 11:49
Yes, duplicate of #44304. You should use `use_static_cpp=yes` to force it on.

**Closed by akien-mga** 2020-12-15 11:49 UTC

**Comment by volzhs** [comment] 2020-12-15 23:18
ok. I thought this option is yes by default according to config.py in windows.
