### ISSUE TITLE
Basics/keywords like "if" and "match" are not in the F4 help

### ISSUE THREAD

**Issue by youreperfect** [godotengine/godot#29193] opened 2019-05-26 13:03 UTC
**Godot version:**
3.1.1-stable-win64

**Issue description:**
Language basics like "if" and "match" are not in the F4 help menu. This is especially important in the case of things like "match" that have unusual (as far as modern languages go) syntax and features.

**Steps to reproduce:**
1) open godot editor
2) press F4
3) type "match"
4) notice the match keyword is not listed

**Comment by KoBeWi** [comment] 2019-05-26 13:06
Duplicate of #18579

**Closed by KoBeWi** 2019-05-26 13:06 UTC
