### ISSUE TITLE
Project manager and splash screen are not redrawed when window is resized

### ISSUE THREAD

**Issue by TeddyDD** [godotengine/godot#12509] opened 2017-10-30 12:06 UTC
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Linux Arch 64bit, DE: i3, Godot 3  c93a3c1bd90c3416048e41328e7d787419828722, NVIDIA Corporation GF117M via `primusrun` 

**Issue description:**
When I resize Godot window when Project manager is open the interface is not redrawing. It works properly when project is open (but redraw is slow)

**Steps to reproduce:**
- open Godot 3 project manager
- resize window

**Workaround**
Usually I switch window to full screen. It seems to force Godot to redraw interface.

**Link to minimal example project:**
https://www.youtube.com/watch?v=5WLZEzB98Bo&feature=youtu.be

**Comment by mhilbrunner** [comment] 2018-04-10 16:00
First of all thank you for your report and sorry for the delay.

We released Godot 3.0 in January 2018 after 18 months of work, fixing many old issues either directly, or by obsoleting/replacing the features they were referring to.

We still have hundreds of issues whose relevance/reproducibility needs to be checked against the [current stable version](https://godotengine.org/download), and that's where you can help us.
**Could you check if the issue that you described initially is still relevant/reproducible in Godot 3.0 or any newer version, and comment about it here?**

For bug reports, please also make sure that the issue contains detailed steps to reproduce the bug and, if possible, a zipped project that can be used to reproduce it right away. This greatly speeds up debugging and bugfixing tasks for our contributors.

Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

Thanks in advance.

*Note: This message is being copy-pasted to many "stale" issues (90+ days without activity). It might happen that it is not meaningful for this specific issue or appears oblivious of the issue's context, if so please comment to notify the Bugsquad about it.*

**Comment by TeddyDD** [comment] 2018-04-10 19:43
This still affects me, both on Arch and Void linux. Godot version: 3.0.2

**Comment by mhilbrunner** [comment] 2018-04-10 20:49
Thanks for confirming that.

**Comment by TeddyDD** [comment] 2018-12-13 12:02
Hard to tell. I test it again with 3.1 alpha on Ubuntu 18.04 (Gnome) with Nvidia and on Void with intel graphics (i3) and let you know.

**Comment by KoBeWi** [comment] 2020-06-13 15:05
Can anyone still reproduce this bug in Godot 3.2.1 or any later release (e.g. [3.2.2-beta4](https://godotengine.org/article/dev-snapshot-godot-3-2-2-beta-4))?

**Comment by pwnorbitals** [comment] 2020-09-26 22:26
This looks like this issue may not apply anymore. @TeddyDD, care to confirm it works for you now ?

**Comment by TeddyDD** [comment] 2020-09-29 18:43
As stated in my previous post I can't reproduce it anymore. Tested again now on
Linux Mint 20 with AMD ATI Radeon HD 8890M.

**Comment by akien-mga** [comment] 2020-09-29 19:11
Thanks, closing then.

**Closed by akien-mga** 2020-09-29 19:11 UTC
Labels: bug, confirmed, topic:editor
