### ISSUE TITLE
Movie Writer gives black output when rendering/viewport/hdr_2d is on

### ISSUE THREAD

**Issue by bitbutter** [godotengine/godot#90666] opened 2024-04-14 14:21 UTC
### Tested versions

v4.3.dev5.official [89f70e98d]

### System information

Godot v4.3.dev5 - Windows 10.0.19045 - GLES3 (Compatibility) - NVIDIA GeForce RTX 2060 (NVIDIA; 31.0.15.5186) - Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 Threads)

### Issue description

When I turn on the rendering/viewport/hdr_2d setting, Movie Writer gives black output frames only, both when rendering an avi or png sequence. Movie Writer works as expected with hdr_2d turned off.

### Steps to reproduce

Start a new project, create a Node2d scene and save it.
Turn on rendering/viewport/hdr_2d.
Set Movie Writer output path and choose png file type.
Enable Movie Maker mode.
Run the scene.
Black frames will be created.

### Minimal reproduction project (MRP)

n/a

**Comment by Calinou** [comment] 2024-07-25 00:10
I can't reproduce this on 4.3.rc ee3de4ca9 (Linux), using a project in Compatibility with HDR 2D enabled.

This was likely fixed by https://github.com/godotengine/godot/pull/94233.

**Comment by akien-mga** [comment] 2024-07-30 20:10
Confirmed fixed.

**Closed by akien-mga** 2024-07-30 20:10 UTC
Labels: bug, topic:rendering
