### ISSUE TITLE
Error when editing viewport size and hitting tab

### ISSUE THREAD

**Issue by puthre** [godotengine/godot#31838] opened 2019-08-31 19:18 UTC
V3.2.dev.custom_build_8ded8830e

Ubuntu 18.04

If you change a viewport size in the inspector and hit tab to go to the next field you the editor stalls for a few seconds and show the following errors the console:

> 
> Failed method: LineEdit:_update_callback target ID: 22481
> Failed method: RichTextLabel:_update_callback target ID: 9723
> TOTAL BYTES: 1048560
> NULL count: 0
> CALL : 43687
> CALL show_modal: 1
> CALL grab_focus: 1
> CALL select_all: 1
> ERROR: push_call: Message queue out of memory. Try increasing 'message_queue_size_kb' in project settings.
>    At: core/message_queue.cpp:55.
> Failed method: ToolButton:_update_callback target ID: 9725
> TOTAL BYTES: 1048560
> NULL count: 0
> CALL : 43687
> CALL show_modal: 1
> CALL grab_focus: 1
> CALL select_all: 1
> ERROR: push_call: Message queue out of memory. Try increasing 'message_queue_size_kb' in project settings.
>    At: core/message_queue.cpp:55.
> Failed method: ToolButton:_update_minimum_size target ID: 9725
> TOTAL BYTES: 1048560
> NULL count: 0
> CALL : 43687
> CALL show_modal: 1
> CALL grab_focus: 1
> CALL select_all: 1
> ERROR: push_call: Message queue out of memory. Try increasing 'message_queue_size_kb' in project settings.
>    At: core/message_queue.cpp:55.
> TOTAL BYTES: 1048560
> NULL count: 0
> CALL : 43687
> CALL show_modal: 1
> CALL grab_focus: 1
> CALL select_all: 1
> ERROR: push_call: Message queue out of memory. Try increasing 'message_queue_size_kb' in project settings.
>    At: core/message_queue.cpp:55.
> Failed method: EditorPropertyVector2:_update_callback target ID: 22471
> TOTAL BYTES: 1048560
> NULL count: 0
> CALL : 43687
> CALL show_modal: 1
> CALL grab_focus: 1
> CALL select_all: 1
> ERROR: push_call: Message queue out of memory. Try increasing 'message_queue_size_kb' in project settings.
>    At: core/message_queue.cpp:55.
> Failed method: EditorSpinSlider:_update_callback target ID: 22479
> TOTAL BYTES: 1048560
> NULL count: 0
> CALL : 43687
> CALL show_modal: 1
> CALL grab_focus: 1
> CALL select_all: 1
> ERROR: push_call: Message queue out of memory. Try increasing 'message_queue_size_kb' in project settings.
>    At: core/message_queue.cpp:55.
> Failed method: LineEdit:show_modal target ID: 22481
> TOTAL BYTES: 1048560
> NULL count: 0
> CALL : 43687
> CALL show_modal: 1
> CALL grab_focus: 1
> CALL select_all: 1

Message ques size is set to 1024

**Comment by jwatte** [comment] 2019-12-24 22:26
I think this may be related to my similar issue, although it also happens when changing other fields, such as "sprite scale," when using tab within the editor.
This happens in a very simple project (5 GUI widgets, one sprite)
Related issue: #34592

**Comment by akien-mga** [comment] 2020-01-28 07:54
Closing as likely duplicate of #35492. See also #35653.

**Closed by akien-mga** 2020-01-28 07:54 UTC
Labels: bug, topic:core, topic:editor
