### ISSUE TITLE
GUI elements doesn't scale

### ISSUE THREAD

**Issue by aarroyoc** [godotengine/godot#18262] opened 2018-04-17 21:30 UTC
**Godot version:** 3.0.2

**OS/device including version:** Linux

**Issue description:**
GUI elements doesn't scale as other Nodes in the 2D view

**Steps to reproduce:**

Add a Button from the editor. In Project Settings -> Display/Window -> Stretch 2d/keep

**Minimal reproduction project:**
![godotguiscale](https://user-images.githubusercontent.com/3681517/38898975-d1060fc4-4296-11e8-80e5-bf2b5c7083a9.png)

As you can see, the border button is blurry, in contrast with the hexagons which scale well. Also the icon (PNG file which comes from a SVG file) doesn't seem to scale well, but I think that's a separate issue.

**Comment by Calinou** [comment] 2018-04-18 10:45
The `2d` scaling mode will scale all GUI elements depending on the window size (which can make them blurry or pixelated), I don't think this is a bug.

Depending on your usecase, you can use a custom GUI theme using StyleBoxFlat which doesn't rely on images and scales nicely to higher resolutions. See #5916 which is about documenting hiDPI support in projects.

**Comment by insomniacUNDERSCORElemon** [comment] 2018-04-18 20:32
@Calinou, is `stretch-mode:disabled` intended to not work with any aspect setting? Because having a fixed aspect ratio and having crisp details seems to be hard to do (especially with 2D). 3D viewports rendered in 2D also seem to not render properly (unlike normal 3D, like the docs mention). Also text is blurry, unless a dynamic font with oversampling is used.

If `stretch-mode:disabled` could be used with aspect settings (particularly keep) I don't think anyone would have need of `stretch-mode:2D` (aside from maybe pixel art, but viewport could be used instead).

----------------

If `stretch-mode` is working as intended, the only real user fix is to this is to properly set up dynamic aspect/scaling with control options and containers. Which is fine for production-level games or even hobby projects, but is undesirable for basic tutorials/beginner tinkering/gamejams etc.

--------------

Somewhat related is that with `stretch-mode:disabled` I'm not really sure how... most things are supposed to be scaled. Even with anchors, size flags, and containers... things like text and sprites just seem to want to stay the size they are! (but I'm just a lurker, so this is just a note, not asking for help).

`stretch-mode:2D` and `aspect:expand`give the desired/expected scaling even though the rendering is significantly worse. Something feels fundamentally broken here.

**Comment by Calinou** [comment] 2018-04-18 23:17
> stretch-mode:2D and aspect:expandgive the desired/expected scaling even though the rendering is significantly worse. Something feels fundamentally broken here.

The rendering can only be so good, the quality depends on the resolution of the GUI images and the font rendering. DynamicFont oversampling should probably be enabled by default, so I'll send a pull request for that.

**Comment by insomniacUNDERSCORElemon** [comment] 2018-04-18 23:26
@Calinou and `stretch-mode:disabled`? Should I create an issue for that?

I'm not really sure what the point of it is (if it's working as-intended in 3.02-1, in Linux if it's relevant) considering it makes scaling+object placement difficult/impossible for multiple resolutions.

**Comment by Calinou** [comment] 2018-04-18 23:29
> @Calinou and stretch-mode:disabled? Should I create an issue for that?

In my experience, the `disabled` stretch mode isn't a good idea for most projects; the `2d` scaling mode is easier to get right, especially thanks to the `expand` aspect scaling mode which was added in 3.0.

We should add a way to restrict scaling to integer values for games with a "pixel art" appearance (for example, by adding a `2d_integer` scaling mode).

**Comment by insomniacUNDERSCORElemon** [comment] 2018-04-19 00:04
@Calinou my problem is that there is no good way to render something as if you had set that as your original window size. This is not an issue of fractional scaling, but simply that the engine is not rendering font/buttons/viewports etc as good as is possible with "native" resolution. The only thing that can properly handle it is true 3D (and, from what I can tell, line2D+polygon2D).

This is likely the issue @aarroyoc is having (I could be wrong, though).

That was my point about `stretch-mode:disabled`, it will render your objects natively (even if your project resolution is set to as low as 1x1) but everything is wacky and you can't control the aspect ratio at all.

**Comment by Calinou** [comment] 2019-04-02 22:44
I'll close this issue in favor of https://github.com/godotengine/godot/issues/20122, as https://github.com/godotengine/godot/issues/20122 is more specific to the issue of easily using hiDPI graphics when needed.

For what it's worth, SVGs are rasterized when imported by Godot, so their scale can't be changed at run-time without becoming blurry. This could be solved by adding the ability to import them as 2D meshes; see the experimental [Godot Vector Graphics](https://github.com/poke1024/godot_vector_graphics) module.

**Closed by Calinou** 2019-04-02 22:44 UTC
Labels: discussion, topic:rendering
