### ISSUE TITLE
Visual anomaly in the editor

### ISSUE THREAD

**Issue by Torguen** [godotengine/godot#33460] opened 2019-11-08 21:51 UTC
**Godot version:**
3.1.1 stable mono

**OS/device including version:**
win10 64

**Issue description:**
The sliding point of the value bars scrolls with the screen if the cusor does not move. If the cursor moves, the point disappears.

**Steps to reproduce:**
Mouse over one of these points, make it visible.
Move the mouse to remove it from the point (the point will still be visible).
Without moving the mouse, use the mouse wheel to scroll up or down.
You will notice that the point is still visible on the screen.
If you now move the mouse, the point will disappear.

**Minimal reproduction project:**
No required.
![GIF](https://user-images.githubusercontent.com/19652075/68513017-3d8ae580-027a-11ea-800b-1aed10d560e5.gif)

**Comment by Calinou** [comment] 2019-11-08 21:55
Duplicate of #27258 (which has been fixed in 3.2beta).

**Closed** 2019-11-08 21:55 UTC
Labels: archived
