### ISSUE TITLE
Playing project (F5) sometimes open a new instance of Godot Editor

### ISSUE THREAD

**Issue by chalcosoma** [godotengine/godot#38964] opened 2020-05-22 18:11 UTC
**Godot version:**
Godot 3.2 stable mono

**OS/device including version:**
Windows 10 Pro x64 1909
GTX 1050 Ti driver version: 441.66

**Issue description:**
Sometimes when I try to play the project it opens a new Godot Editor window (where you can open projects) instead of a game window (where you play the game). A Facebook colleague started the discussion about this bug and posted a video showing how it happens (https://www.facebook.com/groups/godotengine/permalink/1910256099110975/).

**Steps to reproduce:**
I could not find how to reproduce it. It seems random.

**Minimal reproduction project:**
N/A

**Comment by mbrlabs** [comment] 2020-05-22 19:01
Duplicate of https://github.com/godotengine/godot/issues/28036

**Comment by Calinou** [comment] 2020-05-22 19:19
Duplicate of #28036.

**Closed by Calinou** 2020-05-22 19:19 UTC
