### ISSUE TITLE
Creating a class within its own static function causes a cyclic dependency

### ISSUE THREAD

**Issue by FlashDaggerX** [godotengine/godot#38227] opened 2020-04-26 13:52 UTC
**Godot version:** 3.2.1.stable

**OS/device including version:** Debian Sid (kernel 5.5.0-2)

**Issue description:**
Let's say I have the following class:
```gdscript
extends Object
class_name Journal

static func load_path(p_path: String) -> Journal:
    return Journal.new()

var date: Dictionary
var content: Array

func _init() -> void:
    date = OS.get_date()
# ...
```

I'm trying to create a data class, which can load a new instance of itself from a file using the static function `load_path`.

Trying to create the object from within any node causes a cyclic dependency, which is caused in the static function when `Journal` creates a new instance of itself. It's a static function, so there should be no problem creating a new instance of itself, right?

**Steps to reproduce:**

- Create a new object that returns a new instance of itself from a static function belonging to aforementioned object
- Try and create a new instance of the object by invoking `classname.new()` from any node
- Try and run the project

**Minimal reproduction project:**
[MinimalRepro.zip](https://github.com/godotengine/godot/files/4535432/MinimalRepro.zip)

**Comment by Calinou** [comment] 2020-04-26 13:54
Duplicate of #27491?

**Comment by FlashDaggerX** [comment] 2020-04-26 14:32
> Duplicate of #27491?

Looks like it, my bad. 

I just tested this in master (7899b3e73). The bug is still present.

**Closed** 2020-04-26 14:40 UTC

**Comment by eerbin13** [comment] 2021-12-13 21:30
Bug is definitely still present. Just encountered it in Godot v3.4

**Comment by Calinou** [comment] 2021-12-13 22:19
> Bug is definitely still present. Just encountered it in Godot v3.4

This is already reported here: https://github.com/godotengine/godot/issues/27491
