### ISSUE TITLE
Resizing Mesh can crash when switching scenes 

### ISSUE THREAD

**Issue by GiggleHurts** [godotengine/godot#69459] opened 2022-12-01 20:25 UTC
### Godot version

v4.0.beta7.official [0bb1e89fb], v4.0.beta6.official [7f8ecffa5]

### System information

Pop!_OS 22.04 LTS x86_64, Vulkan & Mobile, Radeon RX 590, Latest Mesa drivers

### Issue description

When resizing a mesh in the inspector, and you don't click elsewhere in the current scene to finalize your new value and instead click to change to a different scene, Godot 4 Beta will crash.

On Windows 10 I couldn't replicate it, but on Debian Linux I can successfully crash every time.

P.S. This is my first bug report, please be nice.

### Steps to reproduce

Have a scene, then create new scene.

You can start with MeshInstance3D, or add it as a child to Node3D. (this can also be a CSG, as long as you can add a mesh to resize)

In the Inspector select a mesh, this can be any shape, as long as you can edit size in inspector.

Change size of mesh X, Y, or Z in the inspector, but keep the edited value selected,  don't press ENTER or click off to finalize the change. (Changing the scale under the Transform tab under Node3D in the Inspector doesn't do this, seems to only be resizing meshes, including subdivide, radius)

While size value of the mesh is still selected, click onto a different scene, and BOOM! CRASH! at least for me. 
(But only when the value input can actually apply, eg. putting a subdivide of .2 does not cause issue, but a subdivide of 2 + premature scene change will crash.)

### Minimal reproduction project

N/A

**Comment by clayjohn** [comment] 2022-12-01 20:32
I have a feeling this is a duplicate of https://github.com/godotengine/godot/issues/69454 which seems to have the same issue (crash when resizing mesh), but reports it happening in a GPUParticles3D node. 

Can you confirm that this bug is specific to MeshInstance3D?

**Comment by Sauermann** [comment] 2022-12-01 20:41
This crashes reliably for me:
```
handle_crash: Program crashed with signal 11
Engine version: Godot Engine v4.0.beta.custom_build (1e3919c409fa1f24db8ecde58f723fd59adfeccb)
Dumping the backtrace. Please include this when reporting the bug to the project developer.
[1] /lib/x86_64-linux-gnu/libc.so.6(+0x38d60) [0x7faaa8b9ad60] (??:0)
[2] ./bin/godot.linuxbsd.editor.dev.x86_64.llvm(__dynamic_cast+0x10) [0x89a3910] (??:?)
[3] Node3D* Object::cast_to<Node3D>(Object*) (/srv/docker/data/godot-compile/godot/./core/object/object.h:754)
[4] Node3DEditor::_request_gizmo(Object*) (/srv/docker/data/godot-compile/godot/editor/plugins/node_3d_editor_plugin.cpp:7602)
[5] void call_with_variant_args_helper<__UnexistingClass, Object*, 0ul>(__UnexistingClass*, void (__UnexistingClass::*)(Object*), Variant const**, Callable::CallError&, IndexSequence<0ul>) (/srv/docker/data/godot-compile/godot/./core/variant/binder_common.h:267)
[6] void call_with_variant_args_dv<__UnexistingClass, Object*>(__UnexistingClass*, void (__UnexistingClass::*)(Object*), Variant const**, int, Callable::CallError&, Vector<Variant> const&) (/srv/docker/data/godot-compile/godot/./core/variant/binder_common.h:410)
[7] MethodBindT<Object*>::call(Object*, Variant const**, int, Callable::CallError&) (/srv/docker/data/godot-compile/godot/./core/object/method_bind.h:320)
[8] Object::callp(StringName const&, Variant const**, int, Callable::CallError&) (/srv/docker/data/godot-compile/godot/core/object/object.cpp:733)
[9] Callable::callp(Variant const**, int, Variant&, Callable::CallError&) const (/srv/docker/data/godot-compile/godot/core/variant/callable.cpp:62)
[10] MessageQueue::_call_function(Callable const&, Variant const*, int, bool) (/srv/docker/data/godot-compile/godot/core/object/message_queue.cpp:229)
[11] MessageQueue::flush() (/srv/docker/data/godot-compile/godot/core/object/message_queue.cpp:277)
[12] SceneTree::physics_process(double) (/srv/docker/data/godot-compile/godot/scene/main/scene_tree.cpp:432)
[13] Main::iteration() (/srv/docker/data/godot-compile/godot/main/main.cpp:3158)
[14] OS_LinuxBSD::run() (/srv/docker/data/godot-compile/godot/platform/linuxbsd/os_linuxbsd.cpp:799)
[15] ./bin/godot.linuxbsd.editor.dev.x86_64.llvm(main+0x20f) [0x251c24f] (/srv/docker/data/godot-compile/godot/platform/linuxbsd/godot_linuxbsd.cpp:73)
[16] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xea) [0x7faaa8b85d0a] (??:0)
[17] ./bin/godot.linuxbsd.editor.dev.x86_64.llvm(_start+0x2a) [0x251bf7a] (??:?)
-- END OF BACKTRACE --
```

**Closed** 2022-12-11 10:52 UTC
Labels: bug, topic:rendering, confirmed, crash
