### ISSUE TITLE
Godot debugging is very slow without Internet

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#5828] opened 2016-07-20 21:00 UTC
Tested on Godot 2.0.4, Windows 10 64 bits

For a long amount of time today I had no internet connection (I had WiFi but there was no internet).
When I launch a game with Godot in that case, it takes a lot longer to start. Sometimes I even thought it was frozen, but after waiting between 8 to 30 seconds, my little test game starts. But in the meantime it looks like Godot is stuck.

I don't see a reason why Internet access should slow down the editor. Debugging uses the network for sure but since it's local I didn't expected that slowdown Oo

**Comment by Calinou** [comment] 2016-07-21 11:09
Try using a tool like [Process Hacker](http://processhacker.sourceforge.net/) which can tell you which ports are used for listening. Godot uses the port 6007 by default, I believe you can change this in the Editor Settings. If another application uses it, it can cause a significant delay every time you start your project.

**Comment by SuperUserNameMan** [comment] 2016-07-21 11:46
Cannot replicate with Windows 8.1 64bits and 2.0.4.1.

It might be totally unrelated but, i remember once my game was like frozen because Windows was showing a dialog box in the background asking for me to authorize my game to access to local or public network.

It also happened to me with fullscreen games from steam, where the dialog box is not even visible, and freeze the game till i press [Return] or [Ctrl+Tab] to see the dialog box.

**Comment by Zylann** [comment] 2016-07-21 12:42
@SuperUserNameMan I didn't had this dialog.
The last time I had such an issue was with MinGW or Git: everytime I launched their executable, there was a huge freeze before they start doing something, and the isse was that it tried to access a network drive that didn't exist for some reason. But Godot is built with MSVC on Windows so it could be unrelated to the compiler.

**Comment by punto-** [comment] 2016-07-21 17:20
If the debugger is trying to connect to "localhost" instead of "127.0.0.1",
maybe your hosts file is broken and the host name "localhost" is not being
resolved locally, you should look into that. What happens if you do "ping
localhost" in the command line?

**Comment by Zylann** [comment] 2016-07-21 20:06
I turned off my WiFi then try to ping localhost: no delay. Godot is also fine. But I guess a real test would be to actually have no connection beyond the router, which I cannot easily do...

**Comment by punto-** [comment] 2016-07-21 20:12
Also maybe "localhost" is now on your DNS cache, that's why the editor also
works with no problem.. I'm not sure how to clear it, maybe rebooting?

**Comment by vnen** [comment] 2016-07-21 20:52
The command to clear the DNS cache is: `ipconfig /flushdns`

**Comment by vnen** [comment] 2016-07-21 20:53
And I couldn't reproduce this, BTW.

**Comment by Zylann** [comment] 2016-07-22 00:09
It seems the only times I get a repro is when the WiFi is available but there is no internet. I'm not sure what I should do if it happens again :s

**Comment by vnen** [comment] 2016-07-22 01:45
Do you have access to the router? Try to disconnect the internet cable from it and see what happens. I'll try to do that once I have the opportunity (the people on my house won't be happy if I turn off the internet now...).

**Comment by Zylann** [comment] 2016-07-22 12:37
@vnen I don't own the router, that's the point :'D

**Comment by Zylann** [comment] 2016-07-23 13:45
It happened again, and flushing the DNS cache did not solve the problem.
I shot a video of it https://www.youtube.com/watch?v=Vd_DRA0whUs&feature=youtu.be

**Comment by vnen** [comment] 2016-07-23 15:27
I cannot reproduce this at all :disappointed: I tried using my phone as an access point without internet, but I had no delay to start debugging.

Have you looked at the console to see if it show anything strange?

**Comment by Zylann** [comment] 2016-07-23 15:58
The console doesn't shows anything useful. It seems to me that a function call is hanging forever in Godot. Next time I should eventually launch Godot with a debugger and see where it is blocked...

**Comment by punto-** [comment] 2016-07-23 16:32
flushing the dns cache won't help, it's just to diagnose it.. try
disconnectibg from the wifi, flush dns, then ping localhost on the
console.. the point is you os is unable to resolve localhost for some
reason when there's no internet.. maybe your hosts file is broken?

**Comment by bojidar-bg** [comment] 2017-02-13 13:51
Bump? Getting stale here...

**Comment by Zylann** [comment] 2017-02-13 17:30
I didn' got to repro this recently since my internet is much more stable at the moment.

**Comment by Calinou** [comment] 2018-04-05 11:13
First of all thank you for your report and sorry for the delay.

We released Godot 3.0 in January 2018 after 18 months of work, fixing many old issues either directly, or by obsoleting/replacing the features they were referring to.

We still have hundreds of issues whose relevance/reproducibility needs to be checked against the [current stable version](https://godotengine.org/download), and that's where you can help us.
**Could you check if the issue that you described initially is still relevant/reproducible in Godot 3.0 or any newer version, and comment about it here?**

For bug reports, please also make sure that the issue contains detailed steps to reproduce the bug and, if possible, a zipped project that can be used to reproduce it right away. This greatly speeds up debugging and bugfixing tasks for our contributors.

Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

Thanks in advance.

*Note: This message is being copy-pasted to many "stale" issues (90+ days without activity). It might happen that it is not meaningful for this specific issue or appears oblivious of the issue's context, if so please comment to notify the Bugsquad about it.*

**Comment by Zylann** [comment] 2018-04-05 12:34
I haven't had the chance to try this again, I'll see when I get more disconnections.

**Comment by akien-mga** [comment] 2018-07-02 17:33
This is supposed to have been fixed by #8699.

**Closed by akien-mga** 2018-07-02 17:33 UTC
Labels: bug, topic:editor
