### ISSUE TITLE
parameter Hints in autocompletion preview - to show expected type of variable and other info

### ISSUE THREAD

**Issue by blurymind** [godotengine/godot#4569] opened 2016-05-06 12:04 UTC
1. The editor and gdscript are not consistent with the value type they take for rotations
   A hint about set_rot() type of expected variable would have helped me avoid a bit of confusion here:
   https://github.com/godotengine/godot/issues/4516#issuecomment-217423197
   This is an example of how in some cases your code might parse successfully, but not do what you expect.
2. In order to know the type of variable that is expected in a function or a method, you need to search the class api documentation explicitly.
   In game maker, the auto - completion gives hints like this:
   ![autocomplete_image](https://cloud.githubusercontent.com/assets/6495061/15072365/1fb1f19e-138a-11e6-8419-b19096c5c054.png)
   So no need to search for this, the actual autocompletion is showing you immediately what type of value or syntax it expects!

Godot has no hints whatsoever. 

To make this even more awesome than godot, gamemaker users can write hints for their own functions parameters. Defining a hint is as simple as:
![intelligent-code-completion](https://cloud.githubusercontent.com/assets/6495061/15072382/48fa91e6-138a-11e6-8814-754a1220420d.png)

http://gamemakerblog.com/2014/01/02/how-to-add-intelligent-code-completion-to-scripts/

This is a common feature of many other code editors.
Look at how nice it is in superpowers game engine:
![kii8xad](https://cloud.githubusercontent.com/assets/6495061/15072444/afaa9328-138a-11e6-9c00-c3a073976dec.png)

This makes them easier to learn or transition to!

**Comment by akien-mga** [comment] 2016-05-06 18:51
Well... Godot has autocompletion preview, I'm not sure what you're asking for.

**Comment by akien-mga** [comment] 2016-05-06 20:03
![spectacle a11433](https://cloud.githubusercontent.com/assets/4701338/15084792/2e7f5eb8-13d6-11e6-814e-606d930f0196.png)
![spectacle s11433](https://cloud.githubusercontent.com/assets/4701338/15084817/591b6cac-13d6-11e6-92a1-6e60aa7b0b6d.png)

**Comment by blurymind** [comment] 2016-05-06 20:07
Actually I found out that another user has filed this last year:
https://github.com/godotengine/godot/issues/2378

this is the first thing. Autocompletion hinting is not very obvious. In other environments, the hints are shown in the results. In godot you have to hit enter for the hint to appear. For that reason I wasnt getting the hints and realized it when another user on the issue tracker explained it.

The second thing is showing more information in the actual hint. set_rot () is a good example, because godot's hint does not tell the user that the value needs to be in radiants. 
A bit more information as what it does would be nice too of course. 

:)

But thats about it. I guess you can mark this as a duplicate of https://github.com/godotengine/godot/issues/2378

**Comment by neikeq** [comment] 2016-05-07 11:12
I am not sure what exactly you are asking for, but it looks like a duplicate of #4370.

**Comment by blurymind** [comment] 2017-08-31 09:17
I guess I am asking for the function hints to also show up on autocompletion.
This:
   ![autocomplete_image](https://cloud.githubusercontent.com/assets/6495061/15072365/1fb1f19e-138a-11e6-8419-b19096c5c054.png)
Packs a lot more information than this:
![2e7f5eb8-13d6-11e6-814e-606d930f0196](https://user-images.githubusercontent.com/6495061/29915960-45007c96-8e35-11e7-87e9-27e1f3c51030.png)

The current way only shows hints once you settle for a function/method.
I guess it's not that bad as it is. Maybe I should close this feature request? We don't need it that badly

**Comment by Calinou** [comment] 2019-12-07 16:36
This was implemented by #29744, closing.

![Autocompletion](https://user-images.githubusercontent.com/180032/70377696-aa47dd00-1917-11ea-99e4-62babc4e28bd.png)

**Closed by Calinou** 2019-12-07 16:36 UTC
Labels: enhancement, topic:editor, topic:gdscript, usability
