### ISSUE TITLE
Documentation comments don't appear in tooltips before the script is edited and saved

### ISSUE THREAD

**Issue by ydeltastar** [godotengine/godot#98592] opened 2024-10-27 19:45 UTC
### Tested versions

4.3.1.rc

### System information

Windows 11 - Vulkan (Forward+)

### Issue description

When a script symbol (properties, classes) has documentation comments, the tooltips in the inspector show empty descriptions unless the script is edited and saved. If a script is never edited and saved after the project is loaded, the tooltip will always show empty descriptions.

### Steps to reproduce

* Create a property with a documentation comment and save.
```gdscript
## Create handles!
@export var create_handlers = true
```
* Save. The description will appear in the tooltip.
* Reload project. Hover the property in the inspector without editing and saving the script. The description will be empty.

### Minimal reproduction project (MRP)

N/A

**Comment by syntaxerror247** [comment] 2024-10-28 06:41
> 4.3.1.rc

This version isn't even released yet!

**Comment by dalexeev** [comment] 2024-10-28 07:14
Duplicate of #72406 / #86577. Please test if #95821 fixes this.

Thanks for reporting the bug nonetheless!

**Closed by dalexeev** 2024-10-28 07:14 UTC
