### ISSUE TITLE
Normals artifacting issue on collada exported models

### ISSUE THREAD

**Issue by chrisartguy** [godotengine/godot#9939] opened 2017-07-28 03:47 UTC
First of all, thank you Godot team for your great work. :1st_place_medal: 

**Operating system or device - Godot version:**
Linux Mint (Ubuntu) x64

**Issue description:**
For Godot v3.0 alpha custom build 18e23ad

There are some normal artifacts on a Collada exported .dae model, but the normals are fine on an OBJ exported model. I have exported a model from blender using both the default Collada Exporter and the Better Collada Exporter.

I am not sure if this is related to issue #9562. The dae model only artifacts when Normal mapping is enabled.

**Steps to reproduce:**

*3d workflow:*
1.) Exported FBX model from ZBrush
2.) FBX imported into blender, scaled at 100%
3.) UV and materials finalized. Normals checked.

*Godot importation:*
4.) Exported 2 models from Blender directly into Godot Project folder, using the following methods:
--------->a.) Blender's standard Collada .dae plugin
--------->b.) Godot's Better Collada Exporter  

*In the Godot Engine:*
5.) Created a spacial material for the mesh.
6.) Checked [/] Normal Map in the spacial materials parameters

By enabling Normal Map, both models get the exact same Normals artifacting issues in the same areas.

I'm assuming it's the way collada handles normals?

**Link to minimal example project:**
![artifacting](https://user-images.githubusercontent.com/17959437/28701286-08ec13dc-730a-11e7-9d20-42e633b40121.jpg)
![issue2](https://user-images.githubusercontent.com/17959437/28701878-0f66f99e-730e-11e7-988d-03bff6bb7628.png)

[collada_artifacting_issue.tar.gz](https://github.com/godotengine/godot/files/1181951/collada_artifacting_issue.tar.gz) <- A minimal godot project containing the dae exports.

Thanks!
ChrisP

**Comment by EIREXE** [comment] 2017-07-28 09:15
Can confirm I have the same issue.
![imagen](https://user-images.githubusercontent.com/3101690/28710888-04f8c8ac-7386-11e7-88c4-263d0af97f0a.png)

**Comment by kubecz3k** [comment] 2017-08-02 16:18
Marking as confirmed since in #10043 there were the same artifacts. Also I was able to reproduce with my own model.

**Comment by reduz** [comment] 2017-08-02 17:06
Did you guys tick generate tangents and triangulate on better collada
export?

**Comment by reduz** [comment] 2017-08-02 17:07
There is a bug i just fixed on tangent generation but did not commit it yet

**Comment by phyffer** [comment] 2017-08-02 17:19
Unfortunately no luck :( 

I exported 3 dae models to test:

- w/ Tangent Arrays
- w/ Triangulate
- w/ Tangent Arrays and Triangulate

Although the problem is there, the Tangent Arrays model normal artifacts *slightly* change position
. 
(The artifacts remain in the exact same position with Triangulate.)

The suggestion is excellent though thanks!

**Comment by phyffer** [comment] 2017-08-02 17:25
Triangulate [Same whether on or off]:
![triangles](https://user-images.githubusercontent.com/17959437/28886017-c867ba34-776c-11e7-92f1-a62c4810401d.jpg)

Tangent Arrays:
![tangent_arrays](https://user-images.githubusercontent.com/17959437/28886010-c3493e06-776c-11e7-9b8e-a2c60234f5cd.jpg)

**Comment by reduz** [comment] 2017-08-02 17:37
that looks weird, did you check that the normals are correct (pointing to
the right direction) in Blender??

**Comment by kubecz3k** [comment] 2017-08-02 18:07
@reduz from my side I can tell model/normals are working in substance painter on this model

**Comment by phyffer** [comment] 2017-08-02 18:08
I found something interesting...when I reUV this model (smart project UV), the artifacts change position:
![issue_9939_normalscorrect_uv_issue](https://user-images.githubusercontent.com/17959437/28887557-71e62456-7772-11e7-8184-53f0cfe7a246.jpg)
Noticeable reduction, but this is a smart project UV so it not ideal..

The normals are fine in the affected areas, and I did a recalculate normals and some additional mesh checks to be sure. however artifacts still remain~
ChrisP

**Comment by Keetz** [comment] 2017-08-03 06:50
I experience the same with following specs and versions:
Ubuntu 16.04
Godot_v3.0-alpha1 and Godot master at 57d961a

GPU: GeForce GTX 1050Ti
Driver: 375.66


![selection_038](https://user-images.githubusercontent.com/6707330/28909331-53d7468c-7828-11e7-9e25-62c21da72540.jpg)


@reduz I can also confirm that normals  is correct as it works in substance painter, and a coworker has it working on Windows 10 Godot_v3.0-alpha1 and furthermore as the picture i posted here, doesn't have a normalmap set i just enabled normalmap

**Comment by EIREXE** [comment] 2017-08-03 09:19
On another note: the same model works properly in 2.1

**Comment by kubecz3k** [comment] 2017-08-03 19:52
I checked some old commits and I can tell it's not a fresh bug, I checked commits from June, and it is behaving the same way for me...

**Comment by kubecz3k** [comment] 2017-08-11 14:15
Hmm I'm sorry to tell but the issue don't seems to be fixed yet. Can you guys @phyffer @EIREXE @Keetz confirm so I could reopen the issue?

**Comment by phyffer** [comment] 2017-08-11 20:59
Absolutely @kubecz3k. please stand by as i verify this issue.

**Comment by phyffer** [comment] 2017-08-11 21:32
@kubecz3k I can confirm, normals issue is still there.
Machine : Linux Mint / Ubuntu 16.04
Build : 23f6d3f
Models Tested: Triangulate, Tangent Arrays, Tangent Arrays + Triangulate

Off topic, I took a look at the Godot blog regarding GLTF and it looks quite nice. ;)

**Comment by reduz** [comment] 2017-08-11 21:38
did this start happening at some point? also does it happen with gltf?

**Comment by kubecz3k** [comment] 2017-08-11 21:44
@reduz current blender gltf exporter is to broken for me to check my models with this fileformat. I think it was broken all the time, but I can check tomorrow if https://github.com/godotengine/godot/commit/378b1e6cf0cbcc9c30c61e0cabc7090f70fd380c was fixing this for real.. Also not sure when it happened for the first time, maybe will try to hunt with some bisection... but would be nice to have some starting point on which it was not yet broken (any remarks on that?).

**Comment by phyffer** [comment] 2017-08-11 21:47
@reduz Unfortunately it''s the same error. :( Artifacts appear in the same positions when the normal map box is checked. Just recently, I added an animated collada model and the artifacts are appearing in different locations.

I'm going to catch up a bit on gltf, then export a model and let you know if I'm getting the same errors. brb!

**Comment by phyffer** [comment] 2017-08-11 22:10
@kubecz3k can confirm, gltf exporter seems broken for me when exporting either v1 or v2 :(

**Comment by reduz** [comment] 2017-08-22 01:30
I can't really reproduce.. is there anything I have to do to make it happen?
![image](https://user-images.githubusercontent.com/6265307/29544696-452671b6-86c0-11e7-9d12-366fd4efa3e8.png)

**Comment by reduz** [comment] 2017-08-30 11:29
This is fixed now, closing.

**Closed by reduz** 2017-08-30 11:29 UTC
Labels: bug, confirmed, topic:editor
