### ISSUE TITLE
GODOT hangs when showing/hiding TextureRect with shader where alpha is 0.5

### ISSUE THREAD

**Issue by usbhell** [godotengine/godot#16193] opened 2018-01-30 13:53 UTC
**Godot version:**
V3 stable Official

**OS/device including version:**
OSX El Capitan
iMac (24-inch, Early 2009)
2.66 GHz Intel Core 2 Duo
NVIDIA GeForce 9400 256 MB

**Issue description:**
I'm trying to implement some nice transitioning between scenes. I take a screen capture of the current scene put it in the TextRect and use a shader to do something with it fading the alpha from 1 to 0, thus revealing the new scene behind the TextRect, then hide the TextRect. When the next Scene needs loading I show the TextRect to start the procedure again and GODOT Hangs. By the way this works nicely in version 2. 

**Steps to reproduce:**
if you create a new project with the following Nodes

Control
-TextureRect
-Button
-Button2

attached to the TextureRect is a simple shader

```
shader_type canvas_item;

uniform float progress = 0.5;

void fragment(){
	
	COLOR = vec4(1,1,1,progress
	);
	}
```

attached to the TextureRect is a script and the buttons linked to the script

```
extends TextureRect



func _on_Button_pressed():
	self.hide()
	pass # replace with function body


func _on_Button2_pressed():
	self.show()
	pass # replace with function body
```

Clicking on the first button hides the TextureRect
Clicking on the second button causes GODOT to hang... for me at least

**Minimal reproduction project:**

[New Game Project.zip](https://github.com/godotengine/godot/files/1677869/New.Game.Project.zip)

thanks a lot

**Comment by bruvzg** [comment] 2018-01-30 14:26
Godot d1954f4
macOS 10.13.3 (17D47), AMD FirePro D300 and OSX 10.9.5 (13F1911), Apple Software Renderer 
Can't reproduce.

**Comment by abhaskumarsinha** [comment] 2018-01-30 14:39
@bruvzg its NVIDIA GeForce 9400 256 MB, not software renderer of MAC

**Comment by binbitten** [comment] 2018-01-30 16:25
Godot v3.0-stable
Ubuntu 17.10 and Win7 x64, tested intel hd 4400, nvidia 840m and gtx 970
Can't reproduce with provided project.

**Comment by usbhell** [comment] 2018-01-31 10:32
I tried this on the same machine on Windows 10 32-bit via bootcamp and it works ok, so just the 64-bit OSX version that is not working for me

**Comment by reduz** [comment] 2018-11-14 19:24
I can't reproduce, seems to be OSX only?

**Comment by usbhell** [comment] 2019-01-10 12:52
I retested this with GODOT 3.1 beta1 and Everything was ok on OSX GLES3 & GLES2, so its not a problem for me anymore.

**Comment by akien-mga** [comment] 2019-01-13 13:13
Thanks, closing then.

**Closed by akien-mga** 2019-01-13 13:13 UTC
Labels: bug, platform:osx, topic:core
