### ISSUE TITLE
Third person template crashes radeon rx 5500 XT graphics card

### ISSUE THREAD

**Issue by StoreBoughtRocketGames** [godotengine/godot#68569] opened 2022-11-12 17:33 UTC
### Godot version

Godot 4.0 Beta 4

### System information

Windows 10 x64,  AMD Ryzen 5 2600, radeon rx 5500 XT (driver 31.0.12029.4013)

### Issue description

Walking around the third person template project in Godot 4 Beta 4, everything works fine for a bit, and then I get a timeout error from the graphics card. After I get this graphics card time out Godot doesn't want to open up anymore, and usually freezes, which sometimes requires a restart of my computer to get godot to work again.
![image](https://user-images.githubusercontent.com/110170625/201486730-637ce816-a243-4bec-90f2-1b66aced4294.png)

![image](https://user-images.githubusercontent.com/110170625/201486704-706b801f-db1d-4d7c-a737-15281aa9caf9.png)

### Steps to reproduce

Start the Third person template, walk around the level, and after 10 seconds or so you should get a timeout error on the gpu.

### Minimal reproduction project

https://drive.google.com/drive/folders/1-RbBhkgJX8k_WAwoz-npJpdWffTMmpfy?usp=sharing 

I couldn't seem to upload more than 25MB so I put the third person template on a google drive. I don't know how I can make a smaller example of the issue since it's timing out the driver, and this is a project I basically downloaded straight from the template, made a few api updates to make it work and that was it. 

Edit: This appears to happen to the FPS Shooter template as well. It's not unique to the ThirdPerson Controller template unfortunately.

**Comment by StoreBoughtRocketGames** [comment] 2022-11-12 17:54
I was able to capture the same error with the FPS template from the asset library. I can't get an error print out with the third person character template as it just crashes. But I was able to get one from the FPS template. My best guess is the swap_buffers error is an issue.
![image](https://user-images.githubusercontent.com/110170625/201487822-54f5417e-93a5-4a74-9479-34ebc0922098.png)
[FPS.zip](https://github.com/godotengine/godot/files/9995575/FPS.zip)

**Comment by adamscott** [comment] 2022-11-12 18:43
Could not reproduce the issue in either ot the MRPs on Windows with my Radeon XT Vega 64. Maybe it's because my card is more powerful, overall, than the RX 5500 XT.

**Comment by Jaqueta** [comment] 2022-12-08 05:32
Could reproduce the issue on a RX 5600 XT, Crashed within a couple of minutes after opening the project, inside the editor even. Was having similar issues on my own before finding this thread.

Specs: Windows 11 | R5 3600 | RX 5600 XT (v 2021.11.2) - Godot 4 Beta 7

Turning off SDFGI seems to make the project a bit more stable, even after several minutes the Play Window didn't crashed, the editor however did crash and showed the Driver Timeout window eventually, although it took several minutes than it would when SDFGI was enabled. Not sure if this is related to the issue or just "luck".

**Comment by Jaqueta** [comment] 2023-01-27 20:31
Update: Godot Beta 15, and Updated GPU drivers, the issue still persists. Godot is the only application I've found so far that has this issue.

Driver Version: 22.40.01.10-221213a-386778E-ISV-NDA-AMD-Software-Adrenalin-Edition
Everything else is still the same. It's impossible to use the software for me, if anyone has any solution, please let me know.

**Comment by Calinou** [comment] 2023-01-28 19:18
Do you use any triplanar materials in the project? See https://github.com/godotengine/godot/issues/71841.

**Comment by Jaqueta** [comment] 2023-01-28 23:25
> Do you use any triplanar materials in the project? See #71841.

Yes. Thank you, after disabling all triplanar I was no longer having issues. Been running the engine and build for around an hour now. (Usually it crashes within the first 5 minutes).

I'm glad to know that this will be fixed for the milestone. If the OP can test it as well on their end, this issue can be marked as a duplicate for #71841 .

**Comment by Calinou** [comment] 2023-01-29 11:31
I'll assume this is a duplicate of https://github.com/godotengine/godot/issues/71841. @StoreBoughtRocketGames can reply if this isn't the case.

**Closed by Calinou** 2023-01-29 11:31 UTC
Labels: bug, platform:windows, topic:rendering, topic:thirdparty, needs testing, topic:3d
