### ISSUE TITLE
C# Export of custom typed array is un-assignable

### ISSUE THREAD

**Issue by Validifyed** [godotengine/godot#75066] opened 2023-03-18 14:37 UTC
### Godot version

4.0.1.rc2 & 4.0.0

### System information

Win10, x64, TargetFramework .NET6.0

### Issue description

When you export an array of a custom type in C#, you cannot assign values to the elements in the inspector.

![image](https://user-images.githubusercontent.com/17243178/226112640-fa79aa25-8c73-4cea-95e7-5dbc99a0f728.png)

### Steps to reproduce

```
public partial class NodeType : Node2D
{
}
```

```
public partial class Icon : Sprite2D
{
	[Export]
	NodeType[] Nodes;

	[Export]
	NodeType SingleNode;
}
```

I have 2 Nodes, NODE_A (using script NodeType), NODE_B (using script Icon).

When assigning NODE_A to SingleNode, it works fine. When you assign a NODE_A to an element in the Nodes array, nothing happens, no value is assigned and the value remains as "Assign..." in the inspector.

### Minimal reproduction project

[Godot4test.zip](https://github.com/godotengine/godot/files/11008787/Godot4test.zip)

**Comment by Zireael07** [comment] 2023-03-18 14:52
Dupe of https://github.com/godotengine/godot/issues/74975

@Calinou: Can this issue get pinned so that people don't keep opening umpteenth duplicates?

**Comment by Calinou** [comment] 2023-03-21 22:01
- Duplicate of https://github.com/godotengine/godot/issues/62916.

**Closed by Calinou** 2023-03-21 22:01 UTC
