### ISSUE TITLE
Metadata/Resource slot for Tiles

### ISSUE THREAD

**Issue by xDGameStudios** [godotengine/godot#23374] opened 2018-10-29 12:23 UTC
**Godot version:**
v3.1

**Feature description:**
Right now I don't get the ideia how can I add metadata to tiles. I think this is an important feature, as tiles are suppose to be performant and lightweight (not having builtin functions like nodes)... being able to add metadata (or Resources type containing data that would be even better) would be a very good feature to add. For example in grid based games when tiles have different properties like: friction, damage, terrain effects, movement costs, etc.

Right now this data is very hard to add in a (auto)tile per (auto)tile bases. Even though I can add scripts to Tileset and tileset_script (those seem to be different things) I can't access the data, variables I create within them! The ideia instead of a tile/tile variables would be a custom resource slot inside each tile.. this way we could create a TerrainResource type (for example) with the desired variables, create a TerrainResource instance for each terrain type and then attach the resource to the tile. It's pure data so the performance would be the same (I think), and when the values need to be changed the only place to change is inside the resource and not the tileset itself (it would be cleaner).

**Comment by groud** [comment] 2018-10-29 16:40
Duplicate of #12634

**Closed by groud** 2018-10-29 16:40 UTC
Labels: feature proposal, topic:core
