### ISSUE TITLE
Include libffi

### ISSUE THREAD

**Issue by ghost** [godotengine/godot#3943] opened 2016-03-06 00:09 UTC
libffi is a cross-platform library which allows calling C (C++ can also be called but in many cases name mangling makes it hard) code at runtime.

Foreign function interfaces are implemented by nearly all dynamic languages (Python implements it in the ctypes module, for example).

This would allow writing wrapper plugins in GDScript directly instead of writing modules in C++, which would make it possible to both use dynamic libraries from GDScript in a cross-platform manner  (#3936) and distribute wrappers to libraries directly from the asset store (since a library like GDNet could be written in GDScript instead of C++).

Implementing libffi is extremely trivial, and it could be implemented as a module shipped with Godot by default.

**Comment by punto-** [comment] 2016-03-06 01:02
Can this be used to solve the ABI problem? For example come up with a
protocol to pass variants through the interface? On your module you'd have
to use this to call any methods on an Object that you get from the host
engine.. What APIs would be natively available to the module? Variant?

**Comment by est31** [comment] 2016-03-06 19:23
Yes it can solve the ABI problem, but it doesnt have many advantages over simple C interfaces.

In fact these are all types possible with libffi: http://www.atmark-techno.com/~yashi/libffi.html#Types
Very C-like.

**Comment by paper-pauper** [comment] 2016-03-06 23:52
> Yes it can solve the ABI problem, but it doesnt have many advantages over simple C interfaces.

I would say that being able to write wrappers directly in GDScript (allowing them to be distributed on the asset store) and being able to use thousands of C libraries from GDScript are pretty big advantages over having to recompile Godot each time (as is the case with modules).

**Comment by reduz** [comment] 2016-03-07 00:20
It's C and really low level... but might solve the issue with external
libraries.

Still though, this is GPL licensed, so forget it.

**Comment by reduz** [comment] 2016-03-07 01:07
seems the license changed:

https://sourceware.org/libffi/

**Comment by bojidar-bg** [comment] 2016-03-07 11:23
If the library is <1-2 MB, we might easily include as a core module, since many plugins would benefit from it.

**Comment by est31** [comment] 2016-03-07 11:27
Thats wasted space IMO. what the library does is easily doable with a simple C API as well. C APIs are ABI stable afaik. The problem is just the ++  part :)

**Comment by bojidar-bg** [comment] 2016-03-07 11:33
@est31 ~ Ok, then not so many plugins would benefit from it enough...

**Comment by paper-pauper** [comment] 2016-03-07 11:34
What C API would allow dynamic calls to C code from GDScript in a cross-platform way, and without recompiling the engine?

**Comment by paper-pauper** [comment] 2016-03-07 11:35
Also, libffi is ~65K, way smaller than 1MB.

**Comment by bojidar-bg** [comment] 2016-03-17 13:17
Ok, I read a bit more about it ( http://stackoverflow.com/a/145649/4168713 , above comments, etc. ), and to me it seems like this would be a nice addition indeed, unless we can ( @est31 ) write our own library to do the same.

Also, using Itanium seems like a good idea, but if it is unreasonable for various reasons, we would have to switch to huge `extern "C"` bindings (probably generated automatically)....

**Comment by trollworkout** [comment] 2016-05-30 03:33
bumping this 

This is an easy solution to  implement ABI.  Already there, portable, with compatible license and working.  And it covers everything Godot can export to. 

And here's the thing CPython uses  libffi for C extensions. PyPy decided to make their own (called cffi) instead of using libffi  and their C support is not as good.

Why reinvent the wheel when you already have this lil package, that has been proven to work, ready to go?

**Comment by est31** [comment] 2016-05-30 03:45
> Why reinvent the wheel when you already have this lil package, that has been proven to work, ready to go? 

libffi *only* gives you as much access to writing ABIs as c does. It basically gives other languages the functionality of C to write ABIs.

**Comment by trollworkout** [comment] 2016-05-30 03:48
@est31 According to my research libffi is highly optimized C code.  Is not just writing interfaces in C but exporting them compiling them using certain flags. This is why PyPy's own version lags behind in numerics for example or why CPython's C extension numerics are top notch.

**Comment by akien-mga** [comment] 2018-05-02 08:43
Is this still relevant in GDNative times @karroffel @bojidar-bg?

**Comment by bojidar-bg** [comment] 2019-01-10 15:53
I think this issue might be still relevant, though less relevant than it used to be before GDNative.
libffi (or a suitable replacement) would allow developers to use native functions from GDScript without any prior bindings in GDNative.

**Comment by and3rson** [comment] 2019-01-18 23:58
I agree, having FFI would make it much easier to bind to existing shared libraries like those distributed with SteamWorks.

We're currently building a game for publishing on Steam and we rely a lot on `libsteam_api` library. We had to write our own "intermediate" shared library with GDNative which behaves like a bridge between precompiled proprietary steam library & our game. Having FFI would make it much easier to do this sort of things via foreign function calls directly from GDScript.

**Comment by follower** [comment] 2019-04-14 05:24
> Instead of amalgamating Godot core, we can actually have this as a separate GDNative lib that will use FFI itself under the hood... 

@and3rson Did you happen to try out this approach?

Am interested in FFI in relation to the Epic Online Services SDK which exposes a C APi with Linux/Mac/Win binary libraries.

Had already wondered about taking the approach you suggested so would like to avoid re-inventing the wheel if you've already done it. :)

**Comment by and3rson** [comment] 2019-04-15 17:19
@follower @akien-mga I'm currently writing a proxy library that allows to load shared libraries during runtime. The question is: is it better to do this as a seperate third-party library via GDNative distributed seperately from Godot or would the community want me to write it into the Godot core and contribute as a pull request?

**Comment by and3rson** [comment] 2019-04-15 19:20
Guess I'll proceed with a third-party library then.

So far I was able to do some basic loading via `dlopen` & `dlsym` (will implement the necessary Windows API later as well) and call methods from a Steam shared library with this code (my library's working title is "Foreigner"):

```gdscript
    var foreigner = preload('res://contrib/foreigner/foreigner.gdns').new()
    foreigner.open('libsteam_api.so')
    prints(foreigner.invoke('SteamAPI_Init'))  # Prints 1
    prints(foreigner.invoke_str('SteamAPI_GetSteamInstallPath'))  # Prints .
    prints(foreigner.invoke_bool('SteamAPI_IsSteamRunning'))  # Prints True
```

Of course those `_str` & `_bool` suffixes are just temporary to test things around. I'm switching to ffi integration now which should provide a more robust way of doing this. I'm still thinking about the most readable usage of it from the Godot side. Some ideas are:

```
lib.set_signature("some_fn", [foreigner.INT, foreigner.FLOAT], foreigner.STRING)

# or maybe more Python-ish...
lib.some_fn.argtypes = [foreigner.INT, foreigner.FLOAT]
lib.some_fn.restype = foreigner.STRING

# or just passing them during the call, FFI-style:
lib.invoke("some_fn", foreigner.STRING, [foreigner.INT, foreigner.FLOAT], [34, 42.0])
```

Also I think it would make sense for "open" to actually return a pointer to some other class instance, probably `ForeignLibrary`, and make all functions instances of `ForeignFunction`.

Thoughts are welcome!

**Comment by and3rson** [comment] 2019-04-15 22:21
I've started my development here:

https://github.com/and3rson/foreigner

Your contributions are highly appreciated! (Well, not much to contribute to yet, but an extra pair of hands is always helpful!)

**Comment by and3rson** [comment] 2019-04-16 11:30
Considering the fact that I've already hijacked this thread (sorry), here are some updates:

- Casting between `Variant` & `ffi_type_*` came out to be pretty simple thanks to all the overloaded operators for casting to primitives.
- Pointer support is done via `uint64_t` mode of `Variant` and allows GDScript to pass them between different invocations of foreign functions (Yay!)
- Some memory leaks are still present (like allocated FFI CIF structures), but that's mostly just me forgetting to free memory.

Anyway, the flight is stable.

**Comment by follower** [comment] 2019-04-16 14:54
If only all "thread hijackers" were as productive as you. :D

Thanks for responding to my question...with the best answer: code! :)

A couple of thoughts from reading your issue comments & skimming the code:

* While I think it would be great to have this functionality builtin I think your decision to make it 3rd-party initially is probably the fastest way to making the functionality available at all. Once the code is stabilized and (widely! :) ) used I think it makes it easier to present a compelling case for being builtin (if that still ends up being considered ideal).

* Appreciate you listing potential approaches for specifying the function signatures. I think the FFI-style makes sense initially but a `set_signature()` approach seems like it would be nice so the signature only has to be specified once. (It probably also depends a bit on how people end up "wrapping" libraries on the Godot side.)

I'm keen to try out your code but haven't yet because I'm also trying not to let this distract me from what I need to be doing instead. :)

Anyway, just wanted to give you some positive feedback so you didn't feel like you were typing into the void. :)

Thanks!

**Comment by KoBeWi** [comment] 2020-05-28 16:25
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!

**Closed by KoBeWi** 2020-05-28 16:25 UTC
Labels: feature proposal, topic:core
