### ISSUE TITLE
[4.0, beta 3, Mono] Errors text truncated in both panel and hover popup

### ISSUE THREAD

**Issue by rudidev08** [godotengine/godot#67760] opened 2022-10-22 18:29 UTC
### Godot version

v4.0.beta3.mono.official [01ae26d31]

### System information

macOS Ventura 13.0; MacBook Air M2

### Issue description

Long text in errors panel is hard to read in entirety: in panel, it goes off past the edge, and when using popup hover, it goes past screen boundary.

### Steps to reproduce

Any error or debugger text past panel size (for me, 100% of them) will be affected by this. 

Errors in panel screenshot:
<img width="1469" alt="Screenshot 2022-10-22 at 11 23 16 AM" src="https://user-images.githubusercontent.com/4614775/197357007-7e1324e1-f1f8-418a-a8d8-c887f63b0be4.png">

Errors in hover pop-up screenshot:
<img width="1469" alt="Screenshot 2022-10-22 at 11 23 23 AM" src="https://user-images.githubusercontent.com/4614775/197357009-05e0a0f8-e9a6-43bf-a1a4-6750398b0ad8.png">

**Comment by Calinou** [comment] 2022-10-22 22:32
Duplicate of https://github.com/godotengine/godot/issues/67451.

**Closed by Calinou** 2022-10-22 22:32 UTC
