### ISSUE TITLE
Drag-and-drop asset imports default to the currently selected folder instead of the hovered/dropped-on folder

### ISSUE THREAD

**Issue by appersoncory** [godotengine/godot#99445] opened 2024-11-19 22:12 UTC
### Tested versions

Godot Version Used: 4.3 (official stable build)
Reproducibility: Confirmed in Godot 4.3 stable release.
Other Versions Tested:
4.2 stable: Issue present.
4.0 stable: Issue present.
This behavior does not appear to be a regression; it seems to have existed in earlier versions as well.

### System information

Godot v4.3.stable - Windows 10.0.22631 - GLES3 (Compatibility) - NVIDIA GeForce RTX 4070 Laptop GPU (NVIDIA; 32.0.15.6094) - 13th Gen Intel(R) Core(TM) i7-13700HX (24 Threads)

### Issue description

When importing assets (e.g., textures) into the FileSystem panel via drag-and-drop, the assets are placed into the currently selected folder, regardless of the folder hovered over when the mouse button is released. This behavior is unintuitive and inconsistent with typical drag-and-drop expectations.

Expected Behavior
The asset should be imported into the folder that the user is hovering over when releasing the mouse button during the drag-and-drop operation.
If no folder is hovered over, the asset should default to the currently selected folder.

Observed Behavior
The asset is always imported into the currently selected folder, even if the user is hovering over another folder when releasing the mouse button.

Video example:
https://github.com/user-attachments/assets/267b4999-be37-4142-be6f-e29233f9544f

### Steps to reproduce

Open the Godot Editor and navigate to the FileSystem panel.
Select a folder by clicking on it in the FileSystem panel.
Drag a texture or other asset from your file explorer into the Godot Editor.
Hover over a different folder in the FileSystem panel and release the mouse button.
Observe that the asset is imported into the currently selected folder, not the hovered folder.

### Minimal reproduction project (MRP)

N/A

**Comment by KoBeWi** [comment] 2024-11-22 00:19
Duplicate of #80667

**Closed by KoBeWi** 2024-11-22 00:19 UTC
Labels: enhancement, topic:editor, usability
