### ISSUE TITLE
AnimationTree state machine causes glitchy sound when triggering `playing` of AudioStreamPlayer3D

### ISSUE THREAD

**Issue by DanielKinsman** [godotengine/godot#95684] opened 2024-08-17 06:32 UTC
### Tested versions

Reproducible in 4.3, _not reproducible_ in 4.2

### System information

Godot v4.3.stable unknown - Arch Linux #1 SMP PREEMPT_DYNAMIC Sun, 11 Aug 2024 16:19:06 +0000 - Wayland - GLES3 (Compatibility) - AMD Radeon RX 6800 XT (radeonsi, navi21, LLVM 18.1.8, DRM 3.57, 6.10.4-arch2-1) - AMD Ryzen 7 5800X3D 8-Core Processor (16 Threads)

### Issue description

If you have an AnimationTree with a state machine that triggers the `playing` property on an AudioStreamPlayer3D in a keyframe, the audio becomes glitched, sounding as if it is constantly restarting from the first sample every frame. Just load up the MRP to see it in action; works fine on Godot 4.2, glitches audio in Godot 4.3.

### Steps to reproduce

play the MRP

### Minimal reproduction project (MRP)

[animtree_audio.zip](https://github.com/user-attachments/files/16643723/animtree_audio.zip)

**Comment by matheusmdx** [comment] 2024-08-17 13:55
Bisecting points to #86629 as the culprit:

![image](https://github.com/user-attachments/assets/6a20e646-8531-4ce2-90b9-d30105ed1f13)

**Comment by TokageItLab** [comment] 2024-08-17 18:04
Dupe of https://github.com/godotengine/godot/issues/89730, this is not bug. However, it might be better to have some warning so that users do not use it.

**Comment by DanielKinsman** [comment] 2024-08-17 23:36
The [docs](https://docs.godotengine.org/en/stable/classes/class_animationmixer.html#enum-animationmixer-animationcallbackmodediscrete) state that FORCE_CONTINUOUS does this:

> If a value track has non-numeric type key values, it is internally converted to use [ANIMATION_CALLBACK_MODE_DISCRETE_RECESSIVE](https://docs.godotengine.org/en/stable/classes/class_animationmixer.html#class-animationmixer-constant-animation-callback-mode-discrete-recessive) with [Animation.UPDATE_DISCRETE](https://docs.godotengine.org/en/stable/classes/class_animation.html#class-animation-constant-update-discrete).

I take it this is not true and the docs need to be updated as well? Or is a bool considered a numeric type?

I don't fully understand what is happening under the hood, or all the scenarios like imported animations, but when I add property tracks for bools they automatically get added as discrete, and when I add tracks for floats or vectors they automatically get added as continuous. Treating the _track_'s discrete/continuous mode as the source of truth for blending rather than overriding it seems more intuitive to me. That's assuming a continuous mode track blended with another continuous track mode track will be blended without artifacts, even if recessive/dominant mode is selected?

**Comment by TokageItLab** [comment] 2024-08-17 23:42
It would be more accurate to say that it is un-interpolatable than non-numelic, as the bool is treated internally as a number, as 0 or 1 when blended. Perhaps the documentation could be updated to clarify this.

**Comment by DanielKinsman** [comment] 2024-08-18 00:40
Ok thanks,  that explains what is happening.

I don't understand why FORCE_CONTINUOUS is the new default, the tracks seem to know perfectly well whether they are continuous or discrete already without needing to override it. But I don't have the bigger picture and I don't really know what problem FORCE_CONTINUOUS was trying to solve in the first place, so please feel free to disregard and close this issue.

**Comment by TokageItLab** [comment] 2024-08-18 00:52
> I don't understand why FORCE_CONTINUOUS is the new default,

This is because the default for int values is Discrete, and several issues have been raised in the past about int not being interpolated in AnimationTree, even though it is possible to interpolate it as a float.

Godot 5 absolutely requires that interpolatable values default to Continuous + Nearest instead of Discrete.

**Closed** 2024-08-18 01:49 UTC
Labels: documentation, topic:audio, topic:animation

**Comment by wolcamophone** [comment] 2024-09-01 13:34
Is this a tradeoff that will make more work in-engine to implement animation-timed audio or can the engine be tweaked to better accommodate for more immediate implementation of audio like it had been previously? What steps need to be followed in engine to restore desired behavior?

**Comment by TokageItLab** [comment] 2024-09-01 15:45
@wolcamophone DiscreteMode ignores InterporationType, so Discrete+Nearest makes no sense. Also, I never recommended that anyone set Continuous+Nearest for AudioTrack.

I explained that if you want to use AudioTrack and Discrete, you need to “set CallbackModeDiscrete in AnimationMixer to Ressecive or Dominant”. The PR to add that warning is https://github.com/godotengine/godot/pull/95711 but not yet merged.

**Comment by DanielKinsman** [comment] 2024-09-02 02:23
For others who might see this, the solution I went with for my project was changing to [audio playback tracks](https://docs.godotengine.org/en/stable/tutorials/animation/animation_track_types.html#audio-playback-track) instead of using `.playing` property keyframes.
