### ISSUE TITLE
Will not you make a Japanese document?

### ISSUE THREAD

**Issue by keito940** [godotengine/godot#10499] opened 2017-08-21 09:16 UTC
Those who are familiar with Japanese, or Japanese, thank you.

**Comment by Noshyaar** [comment] 2017-08-21 09:20
http://docs.godotengine.org/en/latest/community/contributing/documentation_guidelines.html#translating-existing-pages

> Translating existing pages
> 
> For the moment, only English documentation is provided. We want to propose localized documentation in the future, but this is not a priority for now. Indeed, since the English documentation is still evolving a lot as the community improves it and make it more professional, we prefer that translators do not spend too much time on it, as their translated documentation might quickly grow out of sync with the original.
> 
> When the English documentation is ready for translations, we will provide tools to simplify the work of translators by tracking changes to the English docs that they should translate on their end.
>

**Comment by akien-mga** [comment] 2017-08-21 09:35
Translating documentation is not possible at the moment, but that's something we'd like to propose in the future, though there is no ETA. A prerequisite would be that the English docs need to be in big part rewritten and improved for 3.0 before translating them would make sense.

Closing as duplicate of https://github.com/godotengine/godot-docs/issues/4.

**Closed by akien-mga** 2017-08-21 09:35 UTC
Labels: documentation
