### ISSUE TITLE
Gamepad mappings are broken in the latest beta

### ISSUE THREAD

**Issue by fossegutten** [godotengine/godot#38585] opened 2020-05-09 08:44 UTC
**Godot version:**
Godot 3.2.2 beta 2

**OS/device including version:**
Windows 10
Xbox One gamepad

**Issue description:**
It seems like face buttons and D-pad are swapped in the latest beta 2 for version 3.2.2. I haven't tried beta 1, but the issue was not present in version 3.2.1 stable

**Steps to reproduce:**
Set up a simple project with some input mappings that use D-pad and some that use face buttons.

**Minimal reproduction project:**

**Comment by Bucham** [comment] 2020-05-09 14:03
Hi. I have exactly the same problem. My gamepad is a generic one from logitech. the buttons and the joystick do not work, or they do it, with a function that does not correspond to them. I use hp laptop with windows 10. As you said, in version 3.2.1 it did not happen. Greetings.

**Comment by akien-mga** [comment] 2020-05-09 14:59
Duplicate of #38554, fixed by #38557.

**Closed by akien-mga** 2020-05-09 14:59 UTC
