### ISSUE TITLE
Hovering over large variable in debugger shows wrong value at best, causes GPU issues at worst

### ISSUE THREAD

**Issue by DissonantVoid** [godotengine/godot#70493] opened 2022-12-23 20:23 UTC
### Godot version

Master https://github.com/godotengine/godot/commit/03694757735d2331b157478f2337b3a87421ac92

### System information

Win10 Gt 1030, (both GL and Vulkan)

### Issue description

When hovering over a large variable in the debugger for example an array with 10_000_000 elements the value shown will be `<null>` instead of the actual array content. the thing is: checking if the array is actually null by doing `print(array == null)` shows that it is not null. I don't know if this is intended (intended to not show the value if the var is too big) but showing `<null>` is not right, instead something like `<too large>` etc.. would make more sense.

also in some cases when the array is big but not too big like 100_000 elements (see reproduction project), hovering over the variable will actually show its value but freeze the whole computer (something to do with the GPU) for a few seconds before displaying anything, this freezing can cause my monitor to temporarily turn off and/or the hovered variable content display to turn into a pure white rectangle. what's annoying is that this issue is not consistent, and I guess it may defer from one GPU to another so it will require testing.

### Steps to reproduce

Create a very large array variable, put a breakpoint and hover over the variable
See reproduction project

### Minimal reproduction project

[large_var_hover_issue.zip](https://github.com/godotengine/godot/files/10297083/large_var_hover_issue.zip)

**Comment by Calinou** [comment] 2023-04-16 15:14
- Duplicate of https://github.com/godotengine/godot/issues/36801 (same cause).

**Closed by Calinou** 2023-04-16 15:14 UTC
Labels: bug, topic:editor, confirmed
