### ISSUE TITLE
文件系统重命名不可用

### ISSUE THREAD

**Issue by yinvoke** [godotengine/godot#82954] opened 2023-10-07 11:02 UTC
### Godot version

4.1.2.stable

### System information

macos 13.5

### Issue description

当focus状态存在于编辑器区域时，文件系统重命名不可用，必须要focus文件系统区域才能使用重命名功能

https://github.com/godotengine/godot/assets/41604578/e67d56fe-c111-4391-8c31-6c8b600228b8

### Steps to reproduce

任一项目

### Minimal reproduction project

任一项目

**Comment by AThousandShips** [comment] 2023-10-07 11:07
The official language of these channels is English, please make any reports or comments in English, if you do not know English please use some translation software or ask for help.

**Comment by theraot** [comment] 2023-10-07 11:18
From the video this seems to be a duplicate of https://github.com/godotengine/godot/issues/78789 and thus fixed by https://github.com/godotengine/godot/pull/80440

**Comment by KoBeWi** [comment] 2023-10-07 18:26
Indeed it's duplicate of #78789

**Closed by KoBeWi** 2023-10-07 18:26 UTC
