### ISSUE TITLE
Add Metadata (or set an script) to Tileset Tiles to determine behaviour on contact with specific tiles (grates, oneway platforms, vertical stairs, grass, etc)

### ISSUE THREAD

**Issue by rubenjavier** [godotengine/godot#2753] opened 2015-11-08 19:37 UTC
Example: when in tileset setup scene and creating a tile StaticBody2D or KinematicBody2D, be able to set an script and set something like:

``` GDScript
# grate.gd
# this is the Tile
extends KinematicBody2D
func _ready():
     set_meta("tile_type", "grate")
```

This way in the character collision event when can so something like this:

``` GDScript
# player.gd
extends KinematicBody2D
func _fixed_process(delta):
     if(is_colliding()):
          if(get_collider().has_meta("tile_type")):
               if(get_collider().get_meta("tile_type") == "grate"):
                    print("you can go through if your character has acquired a mist form")
               if(get_collider().get_meta("tile_type") == "dropdown"):
                    print("you can drop down if you press down+jump")
               if(get_collider().get_meta("tile_type") == "verticalstair"):
                    print("you can climb up if you press up")
               if(get_collider().get_meta("tile_type") == "grass"):
                    print("you can play the sound of walking on grass")

```

Right now this can be done with a separated KinematicBody2D on the scene, but it would be simpler to define this just one time on the Tileset scene and then be reusable as a tile instead of creating many separated objects on the scene and setting each one of them as something different, like a grate, platforms that you can dropdown from, vertical stairs, foolr types to play a different walking sound, etc...

Thanks in advance
Regards

**Comment by volzhs** [comment] 2015-11-09 09:23
I think, this will help to set up stages of block puzzle game also.
:+1:

**Comment by rubenjavier** [comment] 2015-11-09 09:44
Just updated the sample a little to give more examples of possible functionality (this is thinking in a Platformer/Metroidvania case, but I think the possibilities are endless)

**Comment by rubenjavier** [comment] 2015-11-11 05:25
Updated again to demonstrate the idea of different walking sound according to the Tile Meta Data (grass, wood, metal, etc. there are so mny possibilities)

**Comment by Corruptinator** [comment] 2015-11-12 07:00
This is a brilliant idea, the possibilities for this feature is just beyond endless.  : )

**Comment by akien-mga** [comment] 2019-07-19 14:15
Duplicate of #12634 (more recent but it has more visibility).

**Closed by akien-mga** 2019-07-19 14:15 UTC
Labels: feature proposal, topic:core
