### ISSUE TITLE
Errors and Warnings in console when exiting Godot (3.1.dev)

### ISSUE THREAD

**Issue by scorpion81** [godotengine/godot#18927] opened 2018-05-16 12:19 UTC
**Godot version:**
031a445 (3.1.dev.custom_build)

**OS/device including version:**
Ubuntu 18.04 64 bits, OpenGL ES 2.0 Renderer: llvmpipe (LLVM 6.0, 256 bits)
(running in VirtualBox 5.1.38, with 3D Acceleration Enabled)

**Issue description:**
On exiting the editor (Ctrl Q):  
```
ERROR: _get_gl_image_and_format: RGBA float texture not supported
   At: drivers/gles2/rasterizer_storage_gles2.cpp:143.
ERROR: _get_gl_image_and_format: RGBA float texture not supported
   At: drivers/gles2/rasterizer_storage_gles2.cpp:143.
ERROR: _gl_debug_print: GL ERROR: Source: OpenGL	Type: Error	ID: 1	Severity: High	Message: GL_INVALID_ENUM in glTexImage2D(incompatible format = GL_NONE, type = 0x7fff)
   At: drivers/gles2/rasterizer_gles2.cpp:111.
ERROR: ~List: Condition ' _first != __null ' is true.
   At: core/self_list.h:111.
WARNING: cleanup: ObjectDB Instances still exist!
   At: core/object.cpp:1985.
ERROR: cleanup: There are still MemoryPool allocs in use at exit!
   At: core/dvector.cpp:70.
```

**Steps to reproduce:**
Load sample project, exit editor then. Maybe you need to change something so it asks
you to save the project on exit, as well.

**Minimal reproduction project:**
[2DTest.zip](https://github.com/godotengine/godot/files/2009041/2DTest.zip)

**Comment by neikeq** [comment] 2018-05-16 13:02
Can you run the editor in verbose mode with the `-v` command line argument? That should display more details about the leaked instances. Something like this should do: `./godot --path path/to/project -e -v`

**Comment by scorpion81** [comment] 2018-05-16 13:32
Output of the suggested command:
[out.txt](https://github.com/godotengine/godot/files/2009308/out.txt)
(as text file because its rather huge to paste here), additionally the errors mentioned in the original post still appear (not part of the file)

**Comment by groud** [comment] 2018-10-02 09:21
I cannot reproduce on my side. I think we can consider this as fixed on master.

**Closed by groud** 2018-10-02 09:21 UTC
