### ISSUE TITLE
Adding default GUI theme breaks editor

### ISSUE THREAD

**Issue by bogdanaslt** [godotengine/godot#34842] opened 2020-01-05 17:40 UTC
**Godot version:**
3.1.2

**OS/device including version:**
Windows 10
Fedora Linux 31

**Issue description:**
When adding default GUI theme in Project Settings and restarting engine autocomplete in editor stops working. On Fedora in theme editor couldn't add new Class Item (dropdown showed only Items I had already added)

**Steps to reproduce:**

1. Create new GUI theme
2. Go to Project -> Project Settings, under Gui/Theme set newly created theme as "Custom"
3. Restart engine
4. Switch to "Script" tab and start typing some function (`func _process()`) dropdown is not visible, but clicking up and down and then pressing Enter it is posible to choose some function
5. Go to theme editor, click Edit theme -> Add Class Item. Type dropdown shows only items that were added when creating theme

**Minimal reproduction project:**
Don't have at the moment

**Comment by KoBeWi** [comment] 2020-01-05 18:33
Duplicate of #20123, already fixed in 3.2

**Closed by KoBeWi** 2020-01-05 18:33 UTC

**Comment by badunius** [comment] 2022-05-10 01:35
Not fixed
Just reproduced it 3.4.4-stable-win64

**Comment by Calinou** [comment] 2022-05-10 17:49
@badunius Please open a new issue with a minimal reproduction project attached.
