### ISSUE TITLE
"Index p_index out of size" error when no editor_layout.cfg exists

### ISSUE THREAD

**Issue by sersoong** [godotengine/godot#12632] opened 2017-11-04 13:34 UTC
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
windows7 x64 godot2.14 fb9e830 

**Issue description:**
![1](https://user-images.githubusercontent.com/24988459/32405805-151b64a0-c1a7-11e7-963a-75eda52a523c.png)

**Steps to reproduce:**
if C:\Users\user\AppData\Roaming\Godot\config\ has no editor_layout.cfg file,open the Corresponding project will appear this.
The same is true of new projects.
Also import a project.

**Comment by JacobMillward** [comment] 2018-04-24 21:52
Cannot reproduce on Godot3.0.2

Might not be a bug anymore.

**Comment by akien-mga** [comment] 2018-05-01 09:13
Can't reproduce it either in the current 2.1 branch, so closing as fixed.

**Closed by akien-mga** 2018-05-01 09:13 UTC
Labels: bug, junior job, topic:editor
