### ISSUE TITLE
Conversion from 3 to 4 replaces the word "on" by "checked" in GDScript comments

### ISSUE THREAD

**Issue by ttencate** [godotengine/godot#70983] opened 2023-01-06 07:23 UTC
### Godot version

4.0beta10

### System information

Arch Linux

### Issue description

From the diff of my project conversion:

```
-# TODO Set this on the camera far plane
+# TODO Set this checked the camera far plane
 const MAX_VIEW_DISTANCE := 50.0e3
```

### Steps to reproduce

Write this in a `.gd` file in Godot 3:

```
extends Node2D

# If the kettle is on there will be tea.
```

Open the project in Godot 4 and choose full conversion. The comment now reads:

```
# If the kettle is checked there will be tea.
```

... huh? :)

### Minimal reproduction project

[on_checked.zip](https://github.com/godotengine/godot/files/10358118/on_checked.zip)

**Comment by Zireael07** [comment] 2023-01-06 09:58
duplicate of https://github.com/godotengine/godot/issues/66061

**Comment by akien-mga** [comment] 2023-01-06 10:22
Aside from wrongly changing things in comments, I think this rename should be disabled altogether, `on` is a too simple identifier to assume that it's always the one that should be renamed.

**Comment by Maran23** [comment] 2023-01-06 21:10
Maybe we could also try to detect a comment?

**Comment by Calinou** [comment] 2023-01-06 22:32
> Maybe we could also try to detect a comment?

That's being tracked in https://github.com/godotengine/godot/issues/66061.

**Comment by akien-mga** [comment] 2023-03-02 11:59
Duplicate of #73505.

**Closed by akien-mga** 2023-03-02 11:59 UTC
Labels: enhancement, topic:editor, confirmed
