### ISSUE TITLE
caret color is broken

### ISSUE THREAD

**Issue by Elmapul** [godotengine/godot#10203] opened 2017-08-09 11:07 UTC
ubuntu 14.04
godot 3 alpha build 1
the carrot color was normal the last time i used, but now when i openend godot, it was black (and as a result, its almost impossible to see where it is)
the update spiner is turning, so i dont know if there are updates (the help>about stil says build 1)

**Comment by Zylann** [comment] 2017-08-09 12:47
note: the spinner is about ui redrawing itself, not engine updates ;)

**Comment by akien-mga** [comment] 2018-01-15 08:41
Is this still reproducible in Godot 3.0 RC1?

**Comment by Elmapul** [comment] 2018-01-16 10:38
yes and...
no shader is working at all...
i guess its an video card issue on my part (maybe because i'm using ubuntu 14.04)

**Comment by akien-mga** [comment] 2018-01-16 10:44
What's your GPU and drivers version?

**Comment by Elmapul** [comment] 2018-01-17 02:38
Godot 3 rc1.
Ubuntu 14.04
Intel® Core™ i5-3317U CPU @ 1.70GHz × 4
Intel® Ivybridge Mobile
64-bit

**Comment by akien-mga** [comment] 2018-01-17 07:44
Thanks. As mentioned in https://github.com/godotengine/godot-demo-projects/issues/197, the issues are related to your old Mesa version, and should be fixed when upgrading. Since it's hardware and drivers specific, there's not much we can do to fix it, so closing.
Note that things might get better with Godot 3.1 and it's OpenGL ES 2.0 renderer.

**Closed by akien-mga** 2018-01-17 07:44 UTC
Labels: bug, topic:editor, usability

**Comment by jjmontesl** [comment] 2020-08-09 02:47
Sorry to resurrect this, but could this be the same I'm seeing here?
![image](https://user-images.githubusercontent.com/2786867/89723813-67388f00-d9fb-11ea-87b1-09656eb8f44b.png)

**Comment by Calinou** [comment] 2020-08-09 13:58
@jjmontesl Does this occur if you edit a project that uses GLES3?

**Comment by jjmontesl** [comment] 2020-08-09 17:00
> @jjmontesl Does this occur if you edit a project that uses GLES3?

The cursor looks fine (white) if I switch to GLES3.

Also, after switching back to GLES2, the error no longer occurs. I'll report back if it happens again, although the workaround seems a bit risky.

**Comment by Calinou** [comment] 2020-08-09 18:27
> (do you know are there side effects of switching between GLES 2 and 3?)

There shouldn't be any.

**Comment by Elmapul** [comment] 2020-08-12 02:02
> > @jjmontesl Does this occur if you edit a project that uses GLES3?
> 
> The cursor looks fine (white) if I switch to GLES3.
> 
> Also, after switching back to GLES2, the error no longer occurs. I'll report back if it happens again, although the workaround seems a bit risky? (do you know are there side effects of switching between GLES 2 and 3?). Thanks for your support.

if the issue return, use an external editor, such as visual studio to edit your code.

**Comment by jjmontesl** [comment] 2020-08-12 10:51
> if the issue return, use an external editor, such as visual studio to edit your code.

The issue returned. There are other issues with text highlighting in the tree inspector too.

However, suggesting to use another editor may be useful but it's not the way towards fixing Godot. Also, I presume shaders and other texts are edited using the same set of UI components. In any case, avoiding an issue will not fix it, and I prefer not to use an external editor.

**Comment by Calinou** [comment] 2020-08-12 13:13
@jjmontesl Please open a new issue about the bug you're encountering, as it's likely caused by something different by now.

**Comment by hellp** [comment] 2021-11-27 14:56
I’m experiencing this bug as well. I waited until 3.4 before complaining again, so here I am :)

A small addendum: for me it also affects the minimap. It is reproducible after a suspend-to-RAM, but also happens after Godot runs for a while randomly(?). Manjaro/Arch/Linux/nvidia/Xorg/GNOME graphics stack here.

![screenshot](https://user-images.githubusercontent.com/32779/143686387-cf427000-0b48-4b8b-9c88-206e4181ec45.png)

Should I open a new issue?

**Comment by Calinou** [comment] 2021-11-27 14:59
@hellp Please open a new issue as the cause is likely unrelated to the issue originally presented here.
