### ISSUE TITLE
Godot keeps saving script at old location after being moved to another folder

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#6907] opened 2016-10-23 16:12 UTC
Tested on Godot 2.1 official, Windows 10 64 bits

Repro steps:
1) Create a script
2) Save it as a file
3) Move the script to another folder (you can do it either from Godot or from the OS' explorer)
4) Go back to the script editor and save again
5) Notice the script was recreated at its old location, and the other was not updated

Godot is aware of the file being moved, because I can see the FileExplorer dock updates. But concerned resources aren't.

I feel this could have been issued already, but I cannot find it through the search.

**Comment by funabab** [comment] 2016-10-24 13:26
I experience this issue but i dont think see it as a bug IMO, cause i also experience it in some other text editors. Just use the [file > save as] then override the file in it new location and the delete the old one

**Comment by Zylann** [comment] 2016-10-24 17:47
I see it as a bug because:
1) Godot is aware of it but doesn't acts correctly
2) It doesn't warns about the file being moved in the meantime (but that should not even be a thing if 1) is fixed)

**Comment by vnen** [comment] 2016-10-24 18:35
I find this a bug indeed. There's quite a bit of troubles for scripts opened in the editor but changed in the filesystem.

As an example, Notepad++ (when it receives focus) warns if a file was changed (so you can reload or not) or deleted (so you can close it or not).

**Comment by Noshyaar** [comment] 2018-04-07 07:24
First of all thank you for your report and sorry for the delay.

We released Godot 3.0 in January 2018 after 18 months of work, fixing many old issues either directly, or by obsoleting/replacing the features they were referring to.

We still have hundreds of issues whose relevance/reproducibility needs to be checked against the [current stable version](https://godotengine.org/download), and that's where you can help us.
**Could you check if the issue that you described initially is still relevant/reproducible in Godot 3.0 or any newer version, and comment about it here?**

For bug reports, please also make sure that the issue contains detailed steps to reproduce the bug and, if possible, a zipped project that can be used to reproduce it right away. This greatly speeds up debugging and bugfixing tasks for our contributors.

Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

Thanks in advance.

*Note: This message is being copy-pasted to many "stale" issues (90+ days without activity). It might happen that it is not meaningful for this specific issue or appears oblivious of the issue's context, if so please comment to notify the Bugsquad about it.*

**Comment by Zylann** [comment] 2018-04-07 15:58
In 3.0.2, moving a script currently being edited produces this situation:

![image](https://user-images.githubusercontent.com/1311555/38457171-30a4b8c0-3a8d-11e8-98c7-06f894c12adc.png)

Trying to save asks for new location.

**Comment by akien-mga** [comment] 2018-11-22 10:53
Is it also relevant in the current master branch? It might be better to open a new issue specific to the current behaviour, as the bug described in https://github.com/godotengine/godot/issues/6907#issuecomment-379479640 seems quite different from the OP/issue title.

**Comment by KoBeWi** [comment] 2019-06-20 22:15
As of 3.1, if you move the script from FileSystemDock, Godot correctly fixes dependencies and opens the script in new location. However it leaves old script as empty script tab (as reported by Zylann, which is a different issue). Since Godot doesn't support detection of moving resources in OS file explorer, we can consider the original issue fixed.

**Closed by KoBeWi** 2019-06-20 22:15 UTC
Labels: bug, topic:editor
