### ISSUE TITLE
Controller inputs not longer detected after Steam application is launched

### ISSUE THREAD

**Issue by yhwhey** [godotengine/godot#75551] opened 2023-04-01 04:35 UTC
### Godot version

4.0.1

### System information

Windows 10

### Issue description

When a gamepad is connected and is working correctly, launching Steam prevents any further inputs from that gamepad from being detected. Even after Steam is closed the gamepad must be removed in system devices and reconnected for inputs to be detected again.

### Steps to reproduce

1. Connect a gamepad
2. Test that input from gamepad is detected
3. Open Steam application
4. Test again, note that input is no longer detected
5. close Steam
6. Test again and note that input is still not detected

### Minimal reproduction project

[gamepad_input_issue.zip](https://github.com/godotengine/godot/files/11128445/gamepad_input_issue.zip)

**Comment by Calinou** [comment] 2023-04-01 15:41
- Related to https://github.com/godotengine/godot/issues/75480.
 
Can you try disabling Steam Input in the Steam settings?

**Comment by yhwhey** [comment] 2023-04-03 10:24
Confirmed that no events at all are detect from the gamepad in the aforementioned circumstances. I can't see any setting within steam to disable steam input

**Comment by Gramps** [comment] 2023-04-03 20:17
The settings you're looking for are in the main Steam settings under Controller > General Controller Settings.  If you turn off <device> Configuration Support, you should start getting your inputs back.

I happen to be working on controller support for my game right now and can confirm this all.

**Comment by Calinou** [comment] 2023-04-03 20:33
- Duplicate of https://github.com/godotengine/godot/issues/75480.

**Closed by Calinou** 2023-04-03 20:33 UTC
Labels: discussion, topic:thirdparty, topic:input
