### ISSUE TITLE
 body_shape property of body_shape_entered signal always returns 0 regardless of which shape is touched

### ISSUE THREAD

**Issue by TheConceptBoy** [godotengine/godot#48282] opened 2021-04-29 00:07 UTC
**Godot version:**
3.3.0

**Issue description:**
Say I have a rigid body of a door and it has 2 collision shapes, one for the handle and one for the body of the door. I can use an area node to detect if my VR hand controller is touching the door knob and report on that only. I would imagine that the body_shape_entered signal's body_shape property would report on the index of the shape that belongs to the rigid body, which the area has collided with. However when tests, all shapes were reported as 0.

This is not limited to VR
[body_shape_debug.zip](https://github.com/godotengine/godot/files/6395569/body_shape_debug.zip)

***reproduction**
  Rigid Body
  ---collision_shape_1
  ---collision_shape_2
  ---collision_shape_3
  ---collision_shape_4
  

**Minimal reproduction project:**

**Comment by Calinou** [comment] 2021-05-15 16:57
Duplicate of https://github.com/godotengine/godot/issues/19290. As a workaround, switch to the GodotPhysics engine instead of Bullet.

**Closed by Calinou** 2021-05-15 16:57 UTC
Labels: bug, topic:3d, topic:physics

**Comment by TheConceptBoy** [comment] 2021-10-03 16:28
So is this going to be worked on? 
So far the solution to fixing this engine feature problem is to not use the engine feature in the first place, that doesn't seem right. Why bother having the engine in the first place then?

I mean Godot physics works.... alright. I get meshes glitching through the ground when they fall and my world scaling is pretty adequate. With bullet physics my game performance (in VR) goes from 30fps to 70fps. That's a pretty substantial improvement over Godot Physics.
 
The fact that none of the 5DOF joint settings actually do anything makes all that performance gain unobtainable.
