### ISSUE TITLE
C#: Resource Script not Reloaded on Save

### ISSUE THREAD

**Issue by Drommedhar** [godotengine/godot#86662] opened 2023-12-31 10:29 UTC
### Tested versions

Tested in Godot 4.2.1

### System information

Godot v4.2.1.stable.mono - Windows 10.0.22621 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3080 (NVIDIA; 31.0.15.4633) - 13th Gen Intel(R) Core(TM) i7-13700KF (24 Threads)

### Issue description

With GDScript the properties on the resource get updated, as soon as the script has changed. With C# scripts this does not work.

### Steps to reproduce

Create a Resource and a corresponding Resource C# script and add the script to the resource.
If the exported properties are now changed in an external editor, e.g., Visual Studio/Rider, Godot does not reload these properties automatically but I rather need to build the project with the button in the editor. Changed in this context means:

- Add/Remove a property
- Change a property name
- ...

#### Reproduce with MRP ####
Open "Resources/TestItem.tres" and after that, change properties in "Resources/Scripts/RItem.cs"

### Minimal reproduction project (MRP)

[GodotTest.zip](https://github.com/godotengine/godot/files/13800835/GodotTest.zip)

**Comment by AThousandShips** [comment] 2023-12-31 11:00
Duplicate of https://github.com/godotengine/godot/issues/84984

**Closed by AThousandShips** 2023-12-31 11:00 UTC
Labels: discussion, topic:dotnet
