### ISSUE TITLE
godot randomly freezes up on zorin os with gles2 

### ISSUE THREAD

**Issue by Shadowblitz16** [godotengine/godot#43964] opened 2020-11-29 20:48 UTC
**Godot version:**
3.2.3

**OS/device including version:**
OS: Zorin OS 15.3 
GPU: GeForce GTX 650/PCIe/SSE2
Driver: proprietary 450

![image](https://user-images.githubusercontent.com/2453707/100553118-b91e5280-3240-11eb-86a2-c88359e5f65c.png)

**Issue description:**
I am experiencing freezing and lagging in the godot editor when I do random things

**Steps to reproduce:**
Not sure. just try to mess around with godot with my specs and settings
I know I was messing around with the theme when it happened

**Minimal reproduction project:**
Not related it tends to happen in any project

**Comment by Shadowblitz16** [comment] 2020-11-29 21:10
Looks like one of the causes of it is sampling a color accent color from the screen in the editor theme settings
you can reproduce it when sampling a text color

**Comment by Calinou** [comment] 2020-11-29 21:31
@Shadowblitz16 Is it just the Godot editor freezing, or the whole desktop?

Can you check the console output by running Godot from a terminal?

**Comment by Shadowblitz16** [comment] 2020-11-29 22:30
@Calinou Its just the editor also I don't have a terminal when I run godot

**Comment by Calinou** [comment] 2020-11-29 23:03
> Its just the editor also I don't have a terminal when I run godot

Open a terminal, then enter the path to the Godot binary like so: `path/to/godot.x11.tools.64` or `./godot.x11.tools.64` (if the binary is in the home directory).

**Comment by Shadowblitz16** [comment] 2020-11-30 01:16
@Calinou  I installed it through the package manager

**Comment by Janders1800** [comment] 2020-11-30 05:04
Happens to me as well, I got used to it, pressing 'Alt' or 'Alt Gr' unfreezes it. Happens the most in Script window (text editor).

Freezings have no output on terminal, here is all the terminal text:

```OpenGL ES 2.0 Renderer: GeForce GTX 750/PCIe/SSE2
OpenGL ES Batching: ON
 
WARNING: set_enabled_focus_mode: BaseButton's Enabled Focus Mode property has been deprecated due to redundancy and will be removed in Godot 4.0. Please use Control.set_focus_mode instead.
   At: scene/gui/base_button.cpp:329.
EditorSettings: Save OK!
WARNING: cleanup: ObjectDB instances leaked at exit (run with --verbose for details).
   At: core/object.cpp:2132.
Leaked instance: VScrollBar:17987 - Node name: VScrollBar
Leaked instance: TextureButton:17984 - Node name: TextureButton
Leaked instance: RichTextLabel:17986 - Node name: RichTextLabel
Leaked instance: ImageTexture:301 - Resource path: 
Leaked instance: StreamTexture:17988 - Resource path: res://addons/todo/kofi.png
Leaked instance: Image:17990 - Resource path: 
Leaked instance: WindowDialog:17983 - Node name: Control
Leaked instance: MarginContainer:17985 - Node name: MarginContainer
Leaked instance: ImageTexture:304 - Resource path: 
Hint: Leaked instances typically happen when nodes are removed from the scene tree (with `remove_child()`) but not freed (with `free()` or `queue_free()`).
ERROR: clear: Resources still in use at exit (run with --verbose for details).
   At: core/resource.cpp:475.
Resource still in use: res://addons/todo/kofi.png (StreamTexture)
Orphan StringName: ..
Orphan StringName: TextureButton
Orphan StringName: ImageTexture
Orphan StringName: RichTextLabel
Orphan StringName: visibility_changed
Orphan StringName: WindowDialog
Orphan StringName: value_changed
Orphan StringName: VScrollBar
Orphan StringName: minimum_size_changed
Orphan StringName: StreamTexture
Orphan StringName: Control
Orphan StringName: size_flags_changed
Orphan StringName: _closed
Orphan StringName: pressed
Orphan StringName: queue_sort
Orphan StringName: Image
Orphan StringName: root_canvas133
Orphan StringName: _scroll_changed
Orphan StringName: MarginContainer
Orphan StringName: _child_minsize_changed
StringName: 20 unclaimed string names at exit.
ERROR: cleanup: There are still MemoryPool allocs in use at exit!
   At: core/pool_vector.cpp:69.```

**Comment by qarmin** [comment] 2020-11-30 06:37
Looks like duplicate of #41972, try to downgrade drivers to 440

**Comment by akien-mga** [comment] 2020-11-30 08:50
Duplicate of #27669.

**Closed by akien-mga** 2020-11-30 08:50 UTC
Labels: bug, needs testing, platform:linuxbsd, topic:editor, topic:porting
