### ISSUE TITLE
Project list fails to load config and creates a new one every time.

### ISSUE THREAD

**Issue by spongeboburu** [godotengine/godot#21868] opened 2018-09-08 13:50 UTC
**Godot version:**
3.1 master

**OS/device including version:**
Fedora 28, 64-bit

**Issue description:**
Every time godot is started with the project list it will fail to load the config and thus create a new one with defaults, overwriting the already existing one.

**Steps to reproduce:**
Start godot, scan directories. Start a project, change the editor settings back to auto scan the correc dir. Restart godot, config is whiped again.

Output
```
ERROR: instance: Class 'EditorSettings' can only be instantiated by editor.
   At: core/class_db.cpp:518.
ERROR: poll: $HOME/.config/godot/editor_settings-3.tres:159 - Parse Error: Can't create sub resource of type: EditorSettings
   At: scene/resources/scene_format_text.cpp:560.
ERROR: load: Condition ' err != OK ' is true. returned: RES()
   At: core/io/resource_loader.cpp:153.
ERROR: _load: Failed loading resource: $HOME/.config/godot/editor_settings-3.tres
   At: core/io/resource_loader.cpp:190.
WARNING: create: Could not open config file.
   At: editor/editor_settings.cpp:845.
```

**Comment by AlexHolly** [comment] 2018-09-08 15:38
https://github.com/godotengine/godot/issues/21823

**Comment by Chaosus** [comment] 2018-09-09 05:33
Yeah, its a duplicate of #21823.

**Comment by Foxomat** [comment] 2021-11-28 09:57
I am having this issue again. Not very often, but often enough to annoy me a lot. It happens randomly when closing a project. I can't really name a thing I'm doing differently when this error occurs.

**Godot version**:
v3.4.stable.official (steam)

**OS/device including version**:
Windows 10 (Version 10.0.19041)

Error messages in my Godot console window:

```
ERROR: Cannot open file 'res://editor_data/editor_settings-3.tres'.
   at: (scene/resources/resource_format_text.cpp:1183)
ERROR: Failed loading resource: res://editor_data/editor_settings-3.tres. Make sure resources have been imported by opening the project in the editor at least once.
   at: (core/io/resource_loader.cpp:270)
WARNING: Could not open config file.
     at: create (editor/editor_settings.cpp:961)
```

**Comment by Chaosus** [comment] 2021-11-29 06:06
Happens on 4.0 as well.

**Comment by akien-mga** [comment] 2021-11-29 09:15
Please open a new issue. This one was fixed in 2018 (the description mentions "every time", which doesn't seem to be the case here, definitely not in 3.4-stable).

**Closed by akien-mga** 2021-11-29 09:15 UTC
Labels: bug, topic:editor, confirmed
