### ISSUE TITLE
The NavigationAgent does not always move from region to region

### ISSUE THREAD

**Issue by Killfrra** [godotengine/godot#56849] opened 2022-01-16 19:48 UTC
### Godot version

3.5 beta 1

### System information

Ubuntu 20.04

### Issue description

Green dot - `target_location`, blue - `final_location`. There are three regions in the demo, two of which have a cutout for the third one - "rounded". It was expected that the agent would not go around the circle in the center and would be able to freely enter and exit it:

https://user-images.githubusercontent.com/15277964/149674317-fd99098d-9f43-4c0a-9207-72fe8b5e177e.mp4

P.S. The behavior does not change regardless of whether the regions overlap each other or not.

### Steps to reproduce

See _Map_CSG.tscn_

### Minimal reproduction project

[MOBA_3.5_v3.zip](https://github.com/godotengine/godot/files/7877785/MOBA_3.5_v3.zip)

**Comment by smix8** [comment] 2022-05-14 22:52
@Killfrra
The center navigation mesh and the outside navigation meshes have problematic verticies around the circle. The verticies are within `edge_connection_margin` of the navigation_map and the positions are nearly on top of each other but small float errors prevent a proper merge at such close proximity. The individual verticies do not overlap properly or have working angles to other edges. With a rebaked, slightly smaller navmesh and a 0.1-0.2 distance between edges merging happens correctly.

The reason why the agent can sometimes still enter or exit the inner circle is that when close enough the path `get_closest_point` will start the agent already inside the correct navmesh.

**Comment by smix8** [comment] 2022-06-09 07:43
Can be closed as this is not a bug but an issue with the imported navmesh.

The imported navmesh has small float errors for the vertex so it fails the navmesh vertex merge.
The navmesh also does not properly align the edges so it also fails the navmesh edge connections.

Everything else was explained above. When the mesh is fixed navigation works fine.

**Closed** 2022-06-09 07:47 UTC
Labels: bug, topic:navigation
