### ISSUE TITLE
Negative scale particles are not shown

### ISSUE THREAD

**Issue by QbieShay** [godotengine/godot#41587] opened 2020-08-28 19:53 UTC
**Godot version:**
3.2 development - 
6b5102cf907c7c1bae1e866a794bae1cc02d0fae

**OS/device including version:**
OS: Linux 5.8.3-arch1-1
GPU: Radeon 590

**Issue description:**
Negative scale on 2D particle is useful for conveying the impression of particles rotating in 3D.
There are two issues for me:
1. can't set negative scale for 2D particles
2. when using a negative scale curve, particles disappear

**Minimal reproduction project:**
[particle_scale.zip](https://github.com/godotengine/godot/files/5143943/particle_scale.zip)

**Comment by KoBeWi** [comment] 2020-08-29 00:01
You can't set negative scale to particles, the value is clamped at 0. The curve probably tries to set it to negative, but it gets clamped too.

So it's not really a bug, but intended behavior (except the negative curve part). Maybe the restriction could be removed though.

**Comment by Calinou** [comment] 2021-10-15 16:03
I can confirm this on commit 754db65a1 (`3.x` branch).

**Comment by akien-mga** [comment] 2022-08-05 20:35
Fixed by #53852.

**Closed by akien-mga** 2022-08-05 20:35 UTC
Labels: enhancement, topic:rendering, confirmed
