### ISSUE TITLE
Trouble with a Large Model

### ISSUE THREAD

**Issue by OriginalAGP** [godotengine/godot#29990] opened 2019-06-22 17:53 UTC
**Godot version:**
3.1.1 Stable

**OS/device including version:**
Windows 10

**Issue description:**
I have a large city of about 500k triangles that I can't seem to manipulate in Godot. I finally exported it in two OBJs (having tried all other formats as well as exporting in a single OBJ) and I was able to put both into a scene. The first half is for some reason gray, the other fully textured. When I try to manipulate either half, the editor stops responding (but doesn't crash).

**Comment by KoBeWi** [comment] 2019-06-22 20:27
Would be helpful if you provided the model here.

**Comment by KoBeWi** [comment] 2020-07-21 16:04
@OriginalAGP Can you still reproduce this in 3.2.2?

**Comment by fire** [comment] 2020-11-16 19:18
Closing due to lack of reproduction project.

Can reopen if posted.

**Closed by fire** 2020-11-16 19:18 UTC
Labels: bug, topic:import
