### ISSUE TITLE
Scene Thumbnail Generation Error

### ISSUE THREAD

**Issue by TheDuriel** [godotengine/godot#40467] opened 2020-07-17 16:03 UTC
**Godot version:**

3.2 Stable

**OS/device including version:**

Win 10

**Issue description:**

When you save a Scene an error concerning its thumbnail is thrown if:

The Scene contains no visible nodes.

The Scene sizes visible contents exceed 16,384 x 16,384 Pixels area.

**Steps to reproduce:**
See above. Saving a Scene with a simple Node as root should suffice to trigger the message.

**Minimal reproduction project:**

**Comment by akien-mga** [comment] 2020-07-21 13:56
>  See above. Saving a Scene with a simple Node as root should suffice to trigger the message.

Well more info will be needed, as I can't reproduce it.

I zoomed out to 100,000x80,000 and made sure to have Sprites in each corner, but I don't reproduce the issue either in Godot 3.2-stable or 3.2.2-stable. I tried making the canvas size 80,000x50,000 too to be sure (fair warning, it's slow).

![Screenshot_20200721_155618](https://user-images.githubusercontent.com/4701338/88063793-bc0a8780-cb6a-11ea-9f05-aebef0c927d5.png)

**Comment by akien-mga** [comment] 2020-07-22 07:58
Duplicate of #36456 I presume.

**Closed by akien-mga** 2020-07-22 07:58 UTC
Labels: bug, topic:editor
