### ISSUE TITLE
Some interactions with the editor causes rendering artifacts

### ISSUE THREAD

**Issue by NielsVanM** [godotengine/godot#14390] opened 2017-12-07 20:12 UTC
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Windows 10
Godot 3.0 Beta Build 1

**Issue description:**
When defining constants (for example PLAYER_MOVE_SPEED) the shift key is used for extended periods of time. This causes text to be displayed as boxes.
![godot text bug](https://user-images.githubusercontent.com/9862486/33736453-f37c0902-db92-11e7-940f-c3a5e02cee3a.png)

**Steps to reproduce:**
1. Create Script
2. Type for extended period of time with shift engaged.

**Comment by vnen** [comment] 2017-12-07 22:03
Are you sure this is related to the holding of the <kbd>Shift</kbd> key? It seems very odd and I can't reproduce it.

**Comment by NielsVanM** [comment] 2017-12-07 22:07
It might not be directly related to holding shift down. It is as far as I know the only way to reproduce it on my pc.

Any ideas on how to find out what it directly related to is?

**Comment by vnen** [comment] 2017-12-07 22:12
Is there any message in the console window?

**Comment by bruvzg** [comment] 2017-12-08 10:06
Had similar bug once (but only on Quit dialog title bar), don't know how to reproduce it.

**Comment by NielsVanM** [comment] 2017-12-08 11:52
No messages pop up in the console window at the time of the bug. Though it might be useful to have:
`Activated GL 3.3 contextOpenGL ES 3.0 Renderer: GeForce GTX 970/PCIe/SSE2
GLES3: max ubo light: 409
GLES3: max ubo reflections: 455, ubo size: 144
ARVR: Registered interface: Native mobile
OPENING: E:/CloudSync/Programming/Godot/Locked Down Below (E:::CloudSync::Programming::Godot::Locked Down Below)
running cmdline: "C:\Users\user\Desktop\Godot Engine.exe" "--path" "E:/CloudSync/Programming/Godot/Locked Down Below" "--editor"
Activated GL 3.3 contextOpenGL ES 3.0 Renderer: GeForce GTX 970/PCIe/SSE2
GLES3: max ubo light: 409
GLES3: max ubo reflections: 455, ubo size: 144
ARVR: Registered interface: Native mobile
ERROR: EditorData::get_edited_scene_root: Index current_edited_scene=-1 out of size (edited_scene.size()=0)
   At: editor\editor_data.cpp:607
fragment uses function: zero_if_equal`

**Comment by guilhermefelipecgs** [comment] 2017-12-17 16:19
Here's a video of how to reproduce this error.
[youtube link](https://youtu.be/ngpjSdT69wI)

**Comment by vnen** [comment] 2017-12-17 16:28
I've since seen this error once. It is not related to the use of the Shift key at all, there's something else going on.

**Comment by volzhs** [comment] 2017-12-17 16:59
I've faced this issue without any key related.
just moving around with mouse click & drag.

**Comment by guilhermefelipecgs** [comment] 2017-12-17 18:05
Another way to reproduce this bug #14736

**Comment by vnen** [comment] 2017-12-18 01:34
Assuming this all have the same core cause, will use this issue as the main one.

**Comment by RayKoopa** [comment] 2017-12-18 17:46
Just recently had something slightly similar. Didn't hold Shift at all. Was also just a PopupDialog title being as buggy as your whole UI is in the screenshot above. The rest was fine and any following PopupDialog aswell.

**Comment by guilhermefelipecgs** [comment] 2017-12-19 18:51
I think this commit 3ca06e1184e49abd300bce03db1bec0e559c0d03 fix that issue.

**Comment by vnen** [comment] 2017-12-19 21:14
Closing as fixed.

**Closed by vnen** 2017-12-19 21:14 UTC
Labels: bug, topic:editor, topic:rendering
