### ISSUE TITLE
Nodes on the Popup class should be able to steal focus on show for keyboard control

### ISSUE THREAD

**Issue by eon-s** [godotengine/godot#8150] opened 2017-03-25 20:50 UTC
**Ubuntu 16.10 - Godot version: 2.1.2**

**Issue description:**
Popup don't grab focus on show, something really uncommon.
Also, everything loses focus on close, which is not common either.

An optional property to steal focus on show and a path to return it on hide will be good to have on the Popup node branch (or maybe deeper, like in WindowDialog) and may help to solve issues like #8149, also facilitating common key/pad menu navigation on games and other kind of programs.

I know this can be done by the programmer but such a common behavior I think should be there, like the "exclusive" property.

**Steps to reproduce:**
- On the example project, use up and down to enjoy keyboard navigation over the buttons.
- Press enter/return over the buttons that open Popup or FileDialog
- Continue enjoying keyboard navigation over the buttons while it should be somewhere else.

-------------

This can be quickly tested on the Project Manager too:
- Open the project manager and get focus on the buttons to the right.
- Open new, scan or import (with keyboard).
- Press up and down (some windows work almost fine, others not).

**Link to minimal example project:**
[focusissue.zip](https://github.com/godotengine/godot/files/870350/focusissue.zip)

**Comment by mateusfccp** [comment] 2018-12-19 22:57
Is it still an issue on `master` branch?

**Comment by eon-s** [comment] 2018-12-20 00:07
Yes, this still can be seen on the project manager but here is the example ported to Godot 3+
[focusissue-g3.zip](https://github.com/godotengine/godot/files/2696937/focusissue-g3.zip)

**Comment by mateusfccp** [comment] 2018-12-20 00:17
I'm going to try to solve this.

**Comment by mateusfccp** [comment] 2018-12-31 22:40
@eon-s I couldn't reproduce. Both in your zipped project and in project manager, when I pressed [Enter] with focus on one button that would open a Popup, the Popup opens and grab focus. Maybe I'm missing something?

**Comment by eon-s** [comment] 2018-12-31 23:40
@mateusfccp I do not know, In my case, the buttons remain with focus, in the example or the project manager.

![focusissue](https://user-images.githubusercontent.com/10215987/50569081-46e32180-0d3c-11e9-9dff-d1bd66247a36.gif)

**Comment by timoschwarzer** [comment] 2019-01-03 15:01
Can't reproduce in the project manager (as of 200be07).

**Comment by eon-s** [comment] 2019-01-06 16:53
@timoschwarzer the project manager seems to work better but keep pressed the down arrowon the tree and you will see how scrolls on the project list.

In any case, the project manager is just an example and not the subject of the issue.

**Comment by norkn** [comment] 2019-10-29 20:28
The popup nodes grab focus as desired (if they have a focusable component) when activated with popup() instead of show(). When activated that way, focus goes back to the node that had focus before the popup on closing the popup.

**Comment by eon-s** [comment] 2019-10-30 02:15
@norkn thanks, I will check if popup() behaves as I expect now, I may also close this anyway and open the corresponding request on the new request tracker if makes sense.

**Comment by athuyaoo** [comment] 2021-05-26 15:22
@eon-s is this still an issue?

**Comment by eon-s** [comment] 2021-05-26 15:47
@athuyaoo yes, though this looks like a feature request of focus stealing on `show`, you can check that `grab_focus` does not work on things like FileDialog, it seems to be a general problem of Control navigation of neighbors.

**Comment by KoBeWi** [comment] 2021-11-21 23:58
Fixed in 4.0
![k6c1Vhr8zT](https://user-images.githubusercontent.com/2223172/142784293-c46ad358-0c4d-4012-9b03-09c4b3d9729d.gif)

**Closed by KoBeWi** 2021-11-21 23:58 UTC
Labels: enhancement, junior job, usability, topic:gui
