### ISSUE TITLE
godot 4 simple heightmap terrain produces different result in pc and mobile

### ISSUE THREAD

**Issue by TomerconDevelopers** [godotengine/godot#68364] opened 2022-11-07 11:27 UTC
### Godot version

4.0 beta4

### System information

system: windows 10, ryzen 6 3600, rx 590, 16gb RAM, android device: OPPO A57, CPH2387, android version 12

### Issue description

I got different results in pc and mobile, 
pc: 
![image](https://user-images.githubusercontent.com/62302722/200298494-8501aa1d-d894-42d8-8d3d-22801d8e76eb.png)

mobile:
![image](https://user-images.githubusercontent.com/62302722/200298579-e4b5e58b-9964-4d9b-ab50-4c725890be96.png)

both rendered geometry correctly, but colors are different

### Steps to reproduce

node setup:
![image](https://user-images.githubusercontent.com/62302722/200298772-3f489914-9a05-41f8-bbe0-2adfde42bde3.png)

shader code:

```
shader_type spatial;

uniform sampler2D _a;
uniform sampler2D heightmap;
uniform float height_ratio = 1.0f;

void fragment() {
	// Place fragment code here.
	ALBEDO = texture(_a,UV).rgb;
}

void vertex(){
	VERTEX.y += texture(heightmap,UV).r * height_ratio;
}
```

followed tutorial: 
https://www.youtube.com/watch?v=fEG_cnRQ1HI&t=322s

### Minimal reproduction project

[New folder.zip](https://github.com/godotengine/godot/files/9950947/New.folder.zip)

**Comment by TomerconDevelopers** [comment] 2022-11-07 11:28
![image](https://user-images.githubusercontent.com/62302722/200299362-e1db4c3c-4101-444d-8972-4484015a1ea3.png)
editor view

**Comment by arkology** [comment] 2022-11-07 11:34
This may be because of selected image compression

**Comment by TomerconDevelopers** [comment] 2022-11-07 11:46
Renderer:

![image](https://user-images.githubusercontent.com/62302722/200302118-580c8eed-2dc7-485a-8f77-ea596f1e21de.png)

![image](https://user-images.githubusercontent.com/62302722/200302502-23582824-04d6-48b1-ba61-c1592eed8660.png)

**Comment by TomerconDevelopers** [comment] 2022-11-07 11:56
quick apk for testing:

https://drive.google.com/file/d/19Ov6TB_Jp8tRCkMYH0yf38---qfGTFKx/view?usp=sharing

**Comment by arkology** [comment] 2022-11-07 12:27
Select texture -> "Import" tab -> Mode. Change compression mode from "VRAM Compressed" to "Lossless"

**Comment by TomerconDevelopers** [comment] 2022-11-07 12:45
changed settings but still getting same result
![image](https://user-images.githubusercontent.com/62302722/200313711-93f44037-0141-4ae4-82d3-80576ef20de0.png)

**Comment by Chaosus** [comment] 2022-11-07 12:47
@TomerconDevelopers 
![image](https://user-images.githubusercontent.com/3036176/200314182-a55e2ced-4749-4ce7-96df-f33f033e6b3e.png)

**Comment by Calinou** [comment] 2022-11-07 12:54
Duplicate of https://github.com/godotengine/godot/issues/65127 (same cause).

**Closed by Calinou** 2022-11-07 12:54 UTC
