### ISSUE TITLE
Character do not jumping when moving in -x-z direction 

### ISSUE THREAD

**Issue by TorrGest** [godotengine/godot#76704] opened 2023-05-03 17:06 UTC
### Godot version

4.0-stable_win64

### System information

Windows 10, i7-10750H, GTX 1650 Ti

### Issue description

If you create a 3D character and add him a default script with movement, the character can not jump if you move in the direction of -x-z. When moving in any other direction, the character jumps correctly.

### Steps to reproduce

1. create a 3d character, add mesh and collision;
2. create a playng on which the character will move, add mesh and collision;
3. add a camera and light to the scene;
4. create a movement control script for the character which is added automatically;
5. start the game, start moving in the -x-z direction and press the jump button.

### Minimal reproduction project

![Screenshot_7](https://user-images.githubusercontent.com/2189166/235988508-a1c818f6-7579-4120-b2dc-0633d66ca00b.png)
![Screenshot_6](https://user-images.githubusercontent.com/2189166/235988549-9a687061-c8f3-470d-8d34-39baceb313a7.png)
![Screenshot_5](https://user-images.githubusercontent.com/2189166/235988572-d35a87a9-2286-443d-9d16-8a6c332f6fab.png)

**Comment by clayjohn** [comment] 2023-05-03 17:10
Have you asked about this on other channels first? 

The reason I ask is that this seems very likely to be an issue with your code rather than a bug in the engine. In which case it is best to try to figure out the issue with others before opening a bug report.

**Comment by Calinou** [comment] 2023-05-03 18:11
-X-Z direction is most likely holding A and S at the same time, which is a common culprit with keyboard ghosting (especially when holding another key to jump or crouch).

**Comment by TorrGest** [comment] 2023-05-03 18:36
I work on a dell xps 15 laptop

**Comment by TorrGest** [comment] 2023-05-03 18:39
I also use a dual sens gamepad, which surprisingly works fine.

**Comment by AThousandShips** [comment] 2023-05-03 18:47
Then it's likely ghosting

**Comment by Calinou** [comment] 2023-05-03 18:57
Can you reproduce this if you disconnect the controller?

**Comment by TorrGest** [comment] 2023-05-03 19:11
If you disable the gamepad, the problem persists, but it seems to be really ghosting. This keyboard shortcut does not work outside of godot either.

**Comment by Calinou** [comment] 2023-05-03 21:17
Closing, as this is a hardware issue we can't fix.

**Closed by Calinou** 2023-05-03 21:17 UTC
Labels: discussion

**Comment by nadamas2000** [comment] 2023-10-25 09:25
I have the same problem in 4.1.2:
Down + Left: No jump
Down + Right: No jump
Down + Up: No jump
Left + Down: No jump
Left + Up: No jump
-----
Left + Right: Jump
Up + Right: Jump

Issue occurs with a connected keyboard: Trust TKM-250 23977 (HID\VID_145F&PID_02C9&REV_0101&MI_00)
No issues observed with the connected keyboard: HP TPC-C001K 911502-071 (HID\VID_04F2&PID_1469&REV_0211&MI_00)
HP keyboard works perfectly with any combination keys.
Any gamepad connected.

**Comment by AThousandShips** [comment] 2023-10-25 09:26
Please see above, this is a hardware issue, with that specific keyboard
