### ISSUE TITLE
rand_range seems not to work on windows in godot 3.0

### ISSUE THREAD

**Issue by thomas-goerlich** [godotengine/godot#8957] opened 2017-05-27 11:28 UTC
**Operating system or device - Godot version:**
Operating system: Windows 10 (Version 1703 / OS Build 15063.296)
Godot version: 3.0 - master b93fce1c18a58e752c07a634ed11aa8ec199601d

**Issue description:**
rand_range in gdscript doesn't seem to work on windows (tested mac and ubuntu and it did work there)
```
randomize()
var rndtest = rand_range(0.0, 200.0)
print(rndtest)
```
Outputs e.g. -705028414800 while the debugger shows -16777216
randf() didn't work as well while randi() seemed to work fine.
Compiled with vs2015 and vs2017 CE and tried x86 and x64 builds of godot.

**Steps to reproduce:**
Create a new project and add the above code snippet to a node.

**Link to minimal example project:**
Example project: [testproject-x86.zip](https://github.com/godotengine/godot/files/1033513/testproject-x86.zip)

**Comment by tagcup** [comment] 2017-05-28 01:58
Can't reproduce this under Linux.

**Comment by thomas-goerlich** [comment] 2017-05-28 13:39
I started trying to debug the problem a bit and found out that RANDOM_MAX is always -1 in Math::random(double, double). 
So i create an empty c++ console project and added the following code (roughly resembling whats happening in the engines code) and RANDOM_MAX is -1 there as well. Entering the same code e.g. on http://cpp.sh/ works fine. So my guess would be that the VS C++ compiler does something different than other compilers ... maybe?! Sorry i am not that familiar with the engine or c++ or game dev in general but i thought i try to help as much as i can.
```
#include <iostream>
#include <string>

using namespace std;

int main()
{
	enum {
		RANDOM_MAX = 4294967295L
	};
	unsigned int r = 1677218773;
	double res = (double)r / (double)RANDOM_MAX;
	cout << res;
	string tmp;
	getline(cin, tmp);
}
```

**Comment by BastiaanOlij** [comment] 2017-06-02 22:21
I noticed yesterday, and haven't investigated it further, that randf also doesn't behave as it should on Windows.

On Mac it nicely gives a value between 0.0 and 1.0, but on Windows it seems to give some wildly high number.

I'm assuming the cause of the problem is the same and wonder if it is fixed by the same fix.
It makes sense because it is probably handling the number as a signed integer, not an unsigned integer, where we'll indeed end up with a negative value (I remember seeing warnings in the build about the number).

**Closed** 2017-06-03 06:44 UTC
Labels: bug, platform:windows, topic:core
