### ISSUE TITLE
Accessing global enum values or keys causes crash.

### ISSUE THREAD

**Issue by Gyrth** [godotengine/godot#70952] opened 2023-01-05 15:44 UTC
### Godot version

4.0.beta10

### System information

Ubuntu 22.04.1, Vulkan API 1.3.224, NVIDIA GeForce GTX 1060 6GB

### Issue description

When trying to access all the values or the keys of an enum that is stored in an autoload/global script, Godot 4.0 beta 10 will crash.

```
core/variant/variant_call.cpp:1339 - Condition "!method" is true. Returning: false
core/variant/variant_call.cpp:1265 - Condition "!method" is true. Returning: 0
core/variant/variant_call.cpp:1318 - Condition "!method" is true. Returning: Variant::NIL
core/variant/variant_call.cpp:1251 - Condition "!method" is true. Returning: nullptr
core/variant/variant_call.cpp:1339 - Condition "!method" is true. Returning: false
core/variant/variant_call.cpp:1265 - Condition "!method" is true. Returning: 0
core/variant/variant_call.cpp:1318 - Condition "!method" is true. Returning: Variant::NIL
core/variant/variant_call.cpp:1251 - Condition "!method" is true. Returning: nullptr
```

### Steps to reproduce

1. Open minimal reproduction project.
2. Run project.
3. Crash.

### Minimal reproduction project

[BugReport.zip](https://github.com/godotengine/godot/files/10353462/BugReport.zip)

**Comment by Zireael07** [comment] 2023-01-05 17:51
Duplicate of https://github.com/godotengine/godot/issues/70495

**Closed** 2023-01-05 23:39 UTC
