### ISSUE TITLE
TileMap collision issues

### ISSUE THREAD

**Issue by m-decoster** [godotengine/godot#1416] opened 2015-02-22 10:31 UTC
When importing a TileMap into a scene, the collision of the tiles may be off by a few units. This can be fixed by manually looking at the exported XML file and changing all of the values to the correct ones.

Of course, it would be easier if the exporter created the correct collider coordinates by itself.

**Comment by akien-mga** [comment] 2015-11-17 16:21
I never experienced this issue with my TileMaps. Can you still reproduce this in the current master branch / nightly builds?

**Comment by akien-mga** [comment] 2016-04-01 13:33
Closing as I can't reproduce.

**Closed by akien-mga** 2016-04-01 13:33 UTC
Labels: bug, topic:editor
