### ISSUE TITLE
Drag & drop creates function node instead of Set or Get

### ISSUE THREAD

**Issue by sami8github** [godotengine/godot#26717] opened 2019-03-06 17:51 UTC
**Godot version:**
v3.1.dev.calinou.1800664

**OS/device including version:**
windows 10 x64

**Issue description:**
In visual script
when drag & drop from Scene tab to visual script area, it shows a list of properties, after select, it create a function node instead of Get or Set node.
when change the function it shows a list of methods.
https://drive.google.com/open?id=1QgBxuP37_D_dvUatKIo32HT4Ar_IgUKX

the correction :
when drag & drop it will show a list of methods.
properties can be added by drag & drop from inspector, or by holding shift and drag & drop from Scene tab to visual script area, then it will show a list of properties and create a Get or Set node.
https://drive.google.com/open?id=1LRnvQsdJsBr8FcoZDTlFjTNmHzRBZgJI

**Comment by sami8github** [comment] 2019-03-11 13:05
Please can anyone explain why drag & drop from Scene tab to visual script area shows a list of properties ?

**Comment by Chaosus** [comment] 2019-03-16 15:14
Marked as enhancement for now, cc @fire - can you explain this behavior ?

**Comment by fire** [comment] 2019-03-16 15:57
When I last tested this behavior in July, it found an editor node with an internal name.

Maybe we should figure out what the expected behaviour should be like and work towards that.

I'm not able to work on this until I'm back from GDC.

**Comment by fire** [comment] 2019-03-16 15:59
One possible behavior is to get the node path, another is to get the class name of the node and get that class's methods / properties.

**Comment by Jummit** [comment] 2019-04-11 19:56
I think methods and properties is what everybody expects when draging the node into the editor.

**Comment by fire** [comment] 2019-05-02 14:55
@Jummit Can you check the current workflow. You can now control-f and get methods.

**Comment by sami8github** [comment] 2019-06-16 11:31
The current workflow is not clear and not good , the old (3.0.x) was very nice : 
drag & drop shows select method
easy way to create get & set nodes
properties nodes can be dragged from inspector
I hope you guys keep the good things instead of unclear view

**Comment by sami8github** [comment] 2019-06-17 15:29
Now when drag & drop from Scene tab to visual script area , it shows a list of built in functions instead of list of methods
the current (not usable) :
![image](https://user-images.githubusercontent.com/41632592/59616498-72a46900-911c-11e9-96e8-a4a5d8f9137d.png)

what it should show 
![image](https://user-images.githubusercontent.com/41632592/59616533-894ac000-911c-11e9-895c-71302725d844.png)

**Comment by fire** [comment] 2019-09-30 02:12
I dragged the WorldEnvironment from the node tree and it gives this:

![image](https://user-images.githubusercontent.com/32321/65844934-05909a00-e2ed-11e9-9957-5eb6f6aebe79.png)

Is this acceptable?

**Comment by fire** [comment] 2020-07-03 23:55
Can anyone still reproduce this bug in [Godot 3.2.2](https://godotengine.org/article/maintenance-release-godot-3-2-2) or any later release?

**Comment by Jummit** [comment] 2020-07-04 08:08
Can't reproduce in v3.2.2

**Closed** 2021-07-21 09:23 UTC
Labels: enhancement, topic:editor, topic:visualscript
