### ISSUE TITLE
Pressing Ctrl+Enter to edit node names causes weird popup placement sometimes

### ISSUE THREAD

**Issue by Miziziziz** [godotengine/godot#50488] opened 2021-07-15 15:05 UTC
### Godot version

v3.4.beta1.mono.official and v3.3.2.stable.mono

### System information

Windows 10

### Issue description

If you select a node in the Scene tab, use arrows key to highlight a different one, and then press Ctrl+Enter, sometimes a text popup appears in a weird spot

### Steps to reproduce

Create a scene with a few nodes, select one, use up and down arrow keys to change which one is highlighted, press Ctrl+Enter

https://user-images.githubusercontent.com/7292421/125810622-0305c993-e856-4e45-a506-f290b90f459e.mov

**Comment by timothyqiu** [comment] 2021-07-15 16:57
I'm pretty sure this is a duplicate of a long existing issue, but I'm not able to find it currently.

A simple way to reproduce this in 3.3.2.stable:

1. Create an empty 2D scene.
2. Add a `Spatial` node to the scene.
3. Select the root `Node2D` node, and press down arrow key.
    * You can see the selection cursor moves, but it's still the `Node2D` that's highlighted (same situation as in the OP)
4. Press the shortcut of renaming, the text box will be in the top left corner

**Comment by VedatGunel** [comment] 2021-07-15 17:15
Duplicate of #35876, which is fixed in `master`.

**Comment by KoBeWi** [comment] 2021-07-15 23:52
Cherry-picking #35893 would fix this.

**Comment by akien-mga** [comment] 2021-07-20 09:45
> Cherry-picking #35893 would fix this.

Done, should be fixed in 3.4 beta 2.

**Closed by akien-mga** 2021-07-20 09:45 UTC
Labels: bug, topic:editor
