### ISSUE TITLE
Refactor previewing in SpatialEditor to allow non-camera objects

### ISSUE THREAD

**Issue by dodgyville** [godotengine/godot#12083] opened 2017-10-14 01:55 UTC
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
all platforms, godot3.0

**Issue description:**
It would be useful for any 3D object with a pov (eg Camera, DirectionalLight) if the "preview" button was available in the viewport when that object is selected.

Currently when selecting a Camera a "preview" button appears in the viewport, selecting the button changes the view to that of the Camera, allowing game devs to see what the Camera is seeing. 

This functionality would also be very useful for Directional Lights and I assume other objects with a directional element.

At the moment the existing functionality lives in SpatialEditorViewport and SpatialEditor but it is tied to a Camera reference being passed in from CameraEditorPlugin. It would require a small refactor to either become Object independent or to duplicate some functionality for DirectionalLight.

It would really improve workflow.

A similarly useful improvement to this workflow functionality is in #9135, allow the object being previewed in the viewport to be aligned to the viewport.

**Comment by Noshyaar** [comment] 2017-10-14 05:55
Have you tried 'Align selection with view'?

**Comment by dodgyville** [comment] 2017-10-14 06:29
That's very useful, thanks! The editor could still really use a free roam camera/light mode.

**Comment by Calinou** [comment] 2019-12-24 09:49
I'll close this as the aforementioned features (align transform to view, freelook) implemented since Godot 3.0.

**Closed by Calinou** 2019-12-24 09:49 UTC
Labels: enhancement, topic:editor

**Comment by dodgyville** [comment] 2019-12-24 11:00
Yeah, no, this functionality has not been added:
- free roam when in preview mode (described in #9550)
- allowing preview and free roam when in preview mode for objects other than cameras, such as lights

**Comment by Calinou** [comment] 2019-12-24 11:46
@dodgyville Let's consider the remaining points as a duplicate of #9550 then :slightly_smiling_face:

**Comment by dodgyville** [comment] 2019-12-24 11:49
Sure, as long as you are mindful too please. Closing the ticket without consensus is a bit eyebrow raising...
