### ISSUE TITLE
delete a subdirectory, and that will not removed from godot file browser

### ISSUE THREAD

**Issue by thottee** [godotengine/godot#34118] opened 2019-12-05 15:09 UTC
**Godot version:**
3.1.1, 3.1.2, 3.2 beta2
**OS/device including version:**
windows 8.1
**Issue description:**
when delete a subdirectory (empty or not), an unexpected event happening: the godot checking all files, and don't remove the directory from the godot file browser, and copy all project files to this directory ( but not in real. in the os, the directory deleted, but in godot file browser this phenomenon happen, and it is a little bit annoying)
**Steps to reproduce:**
create a subdirectory and delete it, when a project is opened
**Minimal reproduction project:**
new project with some files

**Comment by Whimfoome** [comment] 2019-12-05 16:26
If you close and open Godot again everything will be normal

**Comment by thottee** [comment] 2019-12-05 22:58
it's okay. thanks @Whimfoome . but it's not a real solution. a bug in the file browser is really annoying.
i can't fix it. unfortunatelly i have no skill for that :(

**Comment by KoBeWi** [comment] 2020-11-11 01:25
Duplicate of #27526

**Closed by KoBeWi** 2020-11-11 01:25 UTC
Labels: bug, topic:editor, usability
