### ISSUE TITLE
Inconsistent behavior between OpenGL and Vulkan when passing a Color to a shader uniform

### ISSUE THREAD

**Issue by caimantilla** [godotengine/godot#80639] opened 2023-08-14 22:41 UTC
### Godot version

4.1.1.stable.mono

### System information

Godot v4.1.1.stable.mono - macOS 13.3.1 - Vulkan (Compatibility) - Apple M1 Pro - Apple M1 Pro (10 Threads)

### Issue description

This applies in both GDScript and C#.
I switched my project from Compatibility to Mobile (and then Forward+ to see if it would fix this) but nope.
Basically, the values passed into a vec4 shader uniform with Color *when using Vulkan* are wrong. Perhaps correct for a color, idk what color space conversion magic is going on, but not for anything else.
In my case, a uniform vec4 with vertex heights. All values are wrong in this scenario, and negative values are affected worse... I think. Some kind of wrapping is being done, maybe? The results are more correct when using the heightmap of the tile north of the one in the example a bit further below. Also, the shadow's behavior is different as it modifies the heightmap values to accommodate its own scene position before converting them into a Color.

One thing to note is that using a Color where it's required (MultiMesh.set_instance_color/MultiMesh.set_instance_custom_data, used for the tiles in the example screenshots) works as expected. However, when using ShaderMaterial.set_shader_parameter, correct behavior under Vulkan is only achieved when using Vector4. Whether this is desirable, intentional, or not, I think the behavior should at least be consistent between OpenGL and Vulkan. At the very least, a note in the documentation would be good, especially since it's expected for Color to work fine since it's used in many other areas involving passing a vec4 to a shader, as with the MultiMesh example.

OpenGL (correct result):
![Screenshot 2023-08-14 at 22 31 19](https://github.com/godotengine/godot/assets/103377610/20e72ed3-6bf7-460c-844c-e273360b5cc2)

Vulkan (incorrect result):
![Screenshot 2023-08-14 at 22 31 07](https://github.com/godotengine/godot/assets/103377610/0b6fcc24-ca30-4a47-b665-31d03bb72feb)

### Steps to reproduce

Create a new shader and copy this code:
```glsl
shader_type spatial;
render_mode
unshaded,
vertex_lighting,
specular_disabled,
blend_mix,
cull_disabled,
depth_draw_always;


uniform sampler2D decal_texture: source_color, filter_linear;
uniform vec4 heightmap = vec4(0.0f, 0.0f, 0.0f, 0.0f);


void vertex()
{
	VERTEX.y = heightmap[VERTEX_ID];
}



void fragment()
{
	vec4 color = texture(decal_texture, UV);
	
	SPECULAR = 0.0f;
	METALLIC = 0.0f;
	ROUGHNESS = 1.0f;
	
	ALBEDO = color.rgb;
	ALPHA = color.a;
}
```

Create a test scene with a camera and copy this code:
```gdscript
extends Node


func _ready():
	var material = ShaderMaterial.new()
	material.shader = load("res://shader.gdshader")
#	material.set_shader_parameter("heightmap", Vector4(-2.8, -1.5, -0.1, 0.0))
	material.set_shader_parameter("heightmap", Color(-2.8, -1.5, -0.1, 0.0))
	material.set_shader_parameter("decal_texture", load("res://icon.svg"))
	
	var mesh = PlaneMesh.new()
	mesh.size = Vector2.ONE
	mesh.material = material
	
	var instance = MeshInstance3D.new()
	instance.mesh = mesh
	
	add_child(instance)
```

Observe the difference in behavior when using the Color line using the Compatibility renderer compared to the Mobile and Forward+ renderers.
The Vector4 line behaves the same (ie. correctly) between both.

### Minimal reproduction project

N/A

**Comment by bitsawer** [comment] 2023-08-14 23:24
The behavior is intentional, OpenGL Compatibility renderer generally works in SRGB color space, Vulkan in linear. So if you want to set an actual color value, use Color class which will be always converted to correct color space. In this case you don't actually do any color calculations, so use Vector3 or Vector4. Duplicate of https://github.com/godotengine/godot/issues/70927 and https://github.com/godotengine/godot/issues/61892, see the comments by clayjohn for more info. This is more of a documentation issue, so closed as duplicate.

**Closed by bitsawer** 2023-08-14 23:24 UTC
