### ISSUE TITLE
Color picker doesn't pick any color

### ISSUE THREAD

**Issue by Ysterklou2005** [godotengine/godot#63619] opened 2022-07-29 10:39 UTC
### Godot version

4.0.dev Aplha 13

### System information

Windows 10, Vulkan, Nvidia Geforce GTX 1050, Game Ready (516.40), Intel(R) Core(TM)2 Quad CPU Q8400 @ 2.66GHZ

### Issue description

The color picker in the Godot 4 alpha 13 editor, won't pick any colors. I have yet to test the color picker node.

### Steps to reproduce

__Method 1:__
1. Open any project
2. Go to Editor Settings > Interface > Theme
3. Click on Base Color or Accent Color
4. Try to pick a color using the colorpicker under the `Value` gradient on the right of the new window

__Method 2:__
1. Open any project
2. Create a new `Theme` resource
3. Add any item that has a `StyleBox` property
4. Go to the StyleBox property and set it as a new `StyleBoxFlat`
5. Open the StyleBox settings and follow step 4 from method 1 on the `BG Color` property

**Comment by akien-mga** [comment] 2022-07-29 10:47
Duplicate of #63545

**Closed by akien-mga** 2022-07-29 10:47 UTC
