### ISSUE TITLE
Glow affects gizmos

### ISSUE THREAD

**Issue by suptoasty** [godotengine/godot#8485] opened 2017-04-21 23:49 UTC
**Operating system or device - Godot version:**
Linux Mint 18.1 64bit - Godot engine 3.0 Custom Build 64bit

**Issue description:**

When using the environment node's option for glow, the gizmos bleed along with light and other visual instances.

**Steps to reproduce:**
1) Add a node to the scene
2) add an environment node
3) turn on Dof Near, far, and or both
4) turn on glow
5) turn off Dof (bug occurs more when you do this step)
6) behold
![screenshot at 2017-04-21 18-47-26](https://cloud.githubusercontent.com/assets/16758490/25299295/fc975562-26c2-11e7-940b-8f3a381e36cb.png)

ps: even without Dof you can still see gizmos being effected only it is not as noticeable
BEFORE:
![screenshot at 2017-04-21 18-45-02](https://cloud.githubusercontent.com/assets/16758490/25299273/b2b56ed4-26c2-11e7-9fed-27501534bbac.png)
AFTER:
![screenshot at 2017-04-21 18-40-16](https://cloud.githubusercontent.com/assets/16758490/25299240/7bacf998-26c2-11e7-860a-b438176a8472.png)

**Comment by reduz** [comment] 2017-04-22 06:47
Yeah, glow is a screen space effect, will affect everything in the scene

On Apr 22, 2017 1:49 AM, "suptoasty" <notifications@github.com> wrote:

*Operating system or device - Godot version:*
Linux Mint 18.1 64bit - Godot engine 3.0 Custom Build 64bit

*Issue description:*

When using the environment node's option for glow, the gizmos bleed along
with light and other visual instances.

*Steps to reproduce:*

   1. Add a node to the scene
   2. add an environment node
   3. turn on Dof Near, far, and or both
   4. turn on glow
   5. turn off Dof (bug occurs more when you do this step)
   6. behold
   [image: screenshot at 2017-04-21 18-47-26]
   <https://cloud.githubusercontent.com/assets/16758490/25299295/fc975562-26c2-11e7-940b-8f3a381e36cb.png>

ps: even without Dof you can still see gizmos being effected only it is not
as noticeable
BEFORE:
[image: screenshot at 2017-04-21 18-45-02]
<https://cloud.githubusercontent.com/assets/16758490/25299273/b2b56ed4-26c2-11e7-9fed-27501534bbac.png>
AFTER:
[image: screenshot at 2017-04-21 18-40-16]
<https://cloud.githubusercontent.com/assets/16758490/25299240/7bacf998-26c2-11e7-860a-b438176a8472.png>

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/godotengine/godot/issues/8485>, or mute the thread

**Comment by Zylann** [comment] 2017-04-26 12:34
how about having a way to toggle screen-space effects in the editor viewport? They most often get in the way whem designing levels (depth of field and glow, mostly).

**Comment by nunodonato** [comment] 2017-04-26 18:35
perhaps the View menu could be used for that. A "normal w/o effects" mode :)

**Comment by reduz** [comment] 2017-04-26 18:46
You already have that option

**Comment by reduz** [comment] 2017-04-26 18:47
Already exists

**Comment by Calinou** [comment] 2017-04-26 19:13
I don't think what @Zylann wants is available right now. There are currently four display modes:

* Normal
* Wireframe
* Overdraw
* Shadeless

Shadeless disables shading entirely, which is probably not what @Zylann wants – I think he wants to disable the post-process effects without disabling shading entirely.

**Comment by reduz** [comment] 2017-04-26 20:38
Yes there is.. check the viewport menu, not the view menu

**Comment by Zylann** [comment] 2017-04-26 20:40
Oh... that? Indeed :)
![image](https://cloud.githubusercontent.com/assets/1311555/25455772/3f3d7df8-2ad1-11e7-905a-a8c3504e3496.png)
Almost didn't see it in my current project xD

**Comment by nunodonato** [comment] 2017-04-26 21:03
Today I learnt: there is a viewport menu!!

**Comment by toger5** [comment] 2017-06-07 09:43
I think to have a proper solution gizmos should be drawn separately (on a separate layer) and than overplayed over the rendered image.

**Comment by reduz** [comment] 2017-06-07 09:50
as mentioned before, glow is applied at the last of the last steps, when
the final render is blitted to the OS framebuffer, so it's not really
possible.

**Comment by toger5** [comment] 2017-06-07 09:55
even if the gizmos would just be drawn on another control item laying over the 3d viewport (like the button in the left top corner *perspective/orthographic*)

**Comment by Zylann** [comment] 2017-06-07 20:39
Clear gizmos on blurred DoF isn't helpful either, I just disable environment effects most of the time anyways, they are no help when designing levels.
I doubt that there is absolutely no way of doing HUD overlays though... is the 3D engine that rigid?

**Comment by reduz** [comment] 2017-06-07 20:44
yeah, it's for the sake of performance. Doing final compositing in one pass
is very desirable.

**Comment by Zylann** [comment] 2017-06-07 20:47
I understand... but, if it's needed in a game, can environment effect exist in a subscene overlaid over the 3D one? That's typical in some 3D UIs.

**Comment by reduz** [comment] 2017-06-07 20:49
for a regular game you can use viewports to do this stuff. Also eventually
the plan is to add render layers, so this will be possible

**Comment by reduz** [comment] 2017-06-13 02:19
There is really no fixing to this, you can disable environment now in individual viewports, so closing this.

**Closed by reduz** 2017-06-13 02:19 UTC
Labels: bug, discussion, topic:editor, topic:rendering

**Comment by toger5** [comment] 2017-06-13 02:26
When will render layers be implemented! that would be a really good feature anyways

**Comment by reduz** [comment] 2017-06-13 04:02
not until 3.1 or 3.2
