### ISSUE TITLE
imported shape keys lose smoothness

### ISSUE THREAD

**Issue by slapin** [godotengine/godot#1335] opened 2015-02-04 01:39 UTC
Smooth objects lose smoothness in morphs produced by import of objects with ShapeKeys.
They are smooth-shaded in Blender, but flat-shaded in Godot.

**Comment by mookiexl** [comment] 2015-02-04 16:13
Confirmed. The problem is most likely in Bettercollada, since when you re-import model exported with Bettercollada back to Blender, it's flat-shaded too. 
What's even stranger is that when you use the default exporter, it re-imports back to blender with correct shape keys, but Godot cannot import them.

**Comment by cheece** [comment] 2015-02-23 01:39
the collada importer doesn't load normals (read the comment in editor_import_collada.cpp:1296) it recomputes the normals instead, i guessed that without redundant vertices the computation should generate smooth normals, so i modified the BetterCollada exporter for that end, but it's still generating bad normals as if there're redundant vertices still, i guess that the collada importer is making redundant vertices again,

sorry for my bad english

**Comment by mookiexl** [comment] 2015-05-01 23:37
Seems to be fixed in latest version of bettercollada.

**Comment by reduz** [comment] 2015-05-01 23:39
yup, should be fixed

**Closed** 2015-11-18 09:15 UTC
Labels: bug, topic:editor
