### ISSUE TITLE
CurveTexture doesn't adjust graph when Min/Max Value is set above/below current value

### ISSUE THREAD

**Issue by yosimba2000** [godotengine/godot#78919] opened 2023-07-01 23:00 UTC
### Godot version

4.0.3 and 4.1 RC 2

### System information

Windows 10 x64 22H2

### Issue description

If you make a CurveTexture and adjust the Min/Max Value above/below the graph's current minimum/maximum Y-value, the graph does not adjust the Y-value to fit within the new Min/Max Value. The handles are no longer visible, and the Min/Max Values must be reset to see them again.

### Steps to reproduce

1) Attach any node that uses CurveTexture. I'm going to add a GPUParticles3D node.
2) Under the node, add a new ParticleProcessMaterial under Process Material
3) Expand the ParticleProcessMaterial and select any property that uses CurveTexture. I'll use Angular Velocity
4) Expand Angular Velocity, and add a new CurveTexture to the Velocity Curve property
5) Expand the CurveTexture. You will see Min Value is currently 0, Max Value is currently 1, and the Curve itself plots Y=0
6) Make two points on the Curve, and move one to X=0, and the other to X=1.
7) Adjust both points to Y=1. Now, the Curve's maximum value is 1.
8) Set Max Value to any number below 1. I will use 0.5 .
9) Notice that the Points on the curve are no longer visible and cannot be selected because they still exist at Y=1, and have not been adjusted to fit within the new Max Value of 0.5 .

Same issue seems to occur when setting Min Value above the Curve's Minimum as well.
10) Reset Max Value back to 1.
11) Set both Points to Y=0.
12) Adjust Min Value to anything greater than 0. I will choose 0.5 .
13) Notice that the Points are no longer visible and cannot be selected.

### Minimal reproduction project

N/A

**Comment by Calinou** [comment] 2023-07-02 00:20
> and adjust the Min/Max Value above/below the graph's current minimum/maximum Y-value, the graph does not adjust the Y-value to fit within the new Min/Max Value

This may be done by design to prevent the graph from being accidentally modified when you're just looking to vertically (un)zoom on the graph.

**Comment by yosimba2000** [comment] 2023-07-02 00:43
Can we add a zoom functionality with scrollwheel?

**Comment by Calinou** [comment] 2023-07-02 09:49
Closing, as feature proposals should be discussed on the [Godot proposals](https://github.com/godotengine/godot-proposals) repository. This repository is now used for bug reports only.

Make sure to follow the proposal template when opening a new proposal – don't just copy and paste the text you wrote in this issue.

**Closed by Calinou** 2023-07-02 09:49 UTC
Labels: discussion, topic:editor
