### ISSUE TITLE
Other classes in script not found if parent script is not loaded.

### ISSUE THREAD

**Issue by bitwes** [godotengine/godot#17398] opened 2018-03-10 05:13 UTC
**Godot version:**
3.0

**OS/device including version:**
Macbook pro macOS 10.12.6

**Issue description:**
Inner classes are not found when you load the classes in another script specifically instead of loading the parent script.  It causes a `Debugger Break, Reason: 'Internal Script Error! - opcode #31 (report please).'`This might be the way it _should_ work but it wasn't this way in 2.4 and the error should be handled explicitly if possible.

**Side question** What are these classes called?  Trying to find something to search on was a pain.  Are the classes in `has_classes.gd` below called "inner" classes or something else?

**Steps to reproduce:**
A script with some classes defined.
```
# has_classes.gd

class OuterClass:
	var some_value = 0

class InnerClass:
	var other_value = 0
	var outer_class = null
	
	func _init():
		outer_class = OuterClass.new()
```

In a scene:

```
# Main.tscn

extends Node2D
var InnerClass = load('res://has_classes.gd').InnerClass
var OuterClass = load('res://has_classes.gd').OuterClass

func _ready():
	var inner_class = InnerClass.new()
```
Running this scene will cause an error pointing to the `outer_class = OuterClass.new()` line in `has_classes.gd`.

**Workaround**
If you add in a load to just the base class then it works.  So `Main.tscn` would look like:
```
extends Node2D
var HasClasses = load('res://has_classes.gd')
var InnerClass = load('res://has_classes.gd').InnerClass
var OuterClass = load('res://has_classes.gd').OuterClass

func _ready():
	var inner_class = InnerClass.new()
```
Additionally you can just load `has_classes.gd` and then make instances using that instead of loading each of the "inner" classes.
```
extends Node2D
var HasClasses = load('res://has_classes.gd')
func _ready():
	var inner_class = HasClasses.InnerClass.new()
```

**Minimal reproduction project:**
https://github.com/bitwes/Godot30Scratch/tree/master/TestInnerClasses

**Comment by bojidar-bg** [comment] 2018-03-10 10:41
Duplicate of #5843, but thanks for the effort of documenting it!

This issue occurs because the "parent" class gets freed (no references to it), and the inner classes can't each other through it afterwards.

It might seem that just adding a reference from the inner class to the outer class would fix the problem, but then it makes a cyclical reference, HasClasses <-> InnerClass, and InnerClass <-> OuterClass.

No idea how this can actually be fixed, but there are some pointers to lines of code in the other issue as well.

Re the side question, I typically call them inner classes, as sub-classes means something else.

**Closed by bojidar-bg** 2018-03-10 10:41 UTC
