### ISSUE TITLE
Sky is still reflected when Sky Contribution is 0

### ISSUE THREAD

**Issue by jknightdoeswork** [godotengine/godot#31911] opened 2019-09-02 20:29 UTC
**Godot version:**

Godot 3.1.1

**OS/device including version:**

Intel UHD 620 on Ubuntu 18 LTS

**Issue description:**

When using a Panorama SkyBox, the skybox is reflected, even if the Sky Contribution factor is set to 0.

**Steps to reproduce:**
Create a Panorama Sky with an image that will be easily spotted if reflected, like a picture of stars. Set Sky Contribution in the environment settings to 0.

Create a cube and apply a Spatial Material. Set Albedo to a dark color, set Roughness to 0. Witness the skybox being reflected. Since SkyContribution is 0, the skybox should not be reflected by the material.

**Minimal reproduction project:**

[sky_issue.zip](https://github.com/godotengine/godot/files/3567060/sky_issue.zip)

**Comment by KoBeWi** [comment] 2019-09-02 20:46
Seems like duplicate of #27797

According to https://github.com/godotengine/godot/issues/27797#issuecomment-481935053, this is not a bug.

**Comment by jknightdoeswork** [comment] 2019-09-02 20:57
Specular is set to disabled and set to 0. This is a bug.

**Comment by KoBeWi** [comment] 2019-09-02 21:04
Setting roughness to 1 seems to be fixing it. Not sure what should be the correct behavior.

**Comment by clayjohn** [comment] 2019-09-02 21:54
This is a duplicate of #27797 and it is not a bug. 

``sky_contribution`` only changes how much the sky contributes to ambient light. It doesn't affect reflections.

Setting ``specular`` to 0 does not eliminate specular reflectance nor should it. This is how PBR rendering works, the ``specular`` parameter controls the strength of the specular lobe it does not affect the presence or absence of reflections. 

A ``roughness`` value of 0 should be quite reflective. Since ``metallic`` is also low, it is like a smooth shiny plastic. Because it is reflective it reflects the sky around it. If you want the material to not reflect the sky and take its color from the ambient color (which doesnt include the sky) then ``roughness`` needs to be set to 1, and ``sky_contribution`` should be set to 0.

**Closed by clayjohn** 2019-09-02 21:54 UTC
Labels: discussion, topic:rendering

**Comment by jknightdoeswork** [comment] 2019-09-03 00:28
Thanks for the explanation, Clay.

What about the use case of having a reflective material that ignores the sky?

**Comment by clayjohn** [comment] 2019-09-03 00:50
What would that look like? In PBR the whole difference between a reflective and non reflective material is how much of the sky it reflects.

**Comment by jknightdoeswork** [comment] 2019-09-03 04:20
I was thinking it would reflect nearby lights, but I suppose that is a wholly different system.

**Comment by clayjohn** [comment] 2019-09-03 04:33
If you want specular from lights but not from background you can use the render mode ``disable_ambient_light``. It is found in SpatialMaterial under "flags". The name isn't entirely correct because it also disables specular reflections, but it should do what you want. Also make sure to have a little bit of roughness, with a roughness value of 0 you won't see specular highlights.
