### ISSUE TITLE
GDScript 2.0: Project crash when editing an extended class variable

### ISSUE THREAD

**Issue by stephen-berry** [godotengine/godot#58373] opened 2022-02-20 21:50 UTC
### Godot version

v4.0.alpha.calinou.499eec13a

### System information

Windows 11

### Issue description

Wasn't sure what to call this, but I tried to add a script with 'class_name XXResource' that 'extends Resource' into another script using:
`@export var resource_script: Resource = resource_script as XXResource`  (inside other script)

By trying to reference resource_script variables/methods anywhere, it ends up crashing every time.

I can't write
`@export var resource_script: XXResource`
because I can only export pre defined types in Godot (in this case, Resource)

and if I write
`@export var resource_script: Resource`
then it **won't** crash, but at the expense of 1. not being able to autocomplete for XXResource vars/methods, and 2. not being able to be specific in which type of Resource I infer it to be

@export is not relevant, as it will crash without it (see sample project)

### Steps to reproduce

You only need 2 scripts (if you want, just download the reproduction, as they're already made for you)

```
extends CharacterBody3D

class_name CharacterClass

var running = false
```

and

```
extends Node

var character_class_direct: CharacterClass
var character_class: CharacterBody3D = character_class as CharacterClass

func _test_method():
	character_class_direct.running = true
	
	#trying to type 'character_class.running' results in crash (even just a . will crash)
	character_class
```

### Minimal reproduction project

[Test.zip](https://github.com/godotengine/godot/files/8104975/Test.zip)

**Comment by SaracenOne** [comment] 2022-02-21 21:44
I think I've identified this and should have some fixes inbound. The crash at least seems to be caused by cyclic detection as a result of character_class assigning itself to itself

**Comment by SaracenOne** [comment] 2022-02-21 22:15
So, there's kind of two aspects to this issue, first is the crash caused by assigning variables to itself, and the second seems to be an inability for autocomplete to detect the members of any script class which is not explicitly type declared.

**Comment by SaracenOne** [comment] 2022-02-22 00:08
Hmm, actually disregard the part about the autocomplete, that's something I subsequently broke in my first attempt to fix the cyclic error

**Comment by SaracenOne** [comment] 2022-02-22 01:19
I think I managed to salvage a pretty *okay* fix that addresses everything in this issue, but I'll withhold my feelings on it until others review it

**Comment by stephen-berry** [comment] 2022-02-22 01:24
So out of pure curiosity, is what I was trying to accomplish a safe idea? It sounds like it's not usually something you should be doing, but I also wonder how else I'd be able to refer to a specific subclass this way

**Comment by SaracenOne** [comment] 2022-02-22 03:36
Well, from what I can elsewhere, it *seems* be an acceptable way of handling it. Type inferrance using the 'as' keyword seems fine, and a lot of languages seem to be fine with self-assigning variables. I drew the line at recursive abitrarily ordered assignment of class members, but that really didn't have much to do with your original issue, it's just something I discovered while debugging it which can cause the same crash. Whatever the case, the PR seems to handle this code fine, but we'll see what other people have to say about it.

**Closed** 2022-02-23 11:09 UTC
Labels: bug, topic:gdscript, confirmed, crash, regression
