### ISSUE TITLE
SHADER GLOBALS : Value not write when type is Sampler2D

### ISSUE THREAD

**Issue by thoced** [godotengine/godot#68485] opened 2022-11-10 19:10 UTC
### Godot version

4.0 Beta 04

### System information

Linux UBUNTU

### Issue description

When a Shader Global input is of Sampler2D type, the value is not saved correctly in the Project.godot file

![image](https://user-images.githubusercontent.com/10273261/201183894-0375d4ec-7c61-41b8-a5cc-1d5f7b024010.png)

![image](https://user-images.githubusercontent.com/10273261/201184144-d070af50-4ba2-42ce-b48a-b9eaaf8ec272.png)

The error seems to occur in the material_storage.cpp file:

![image](https://user-images.githubusercontent.com/10273261/201184556-1e57a125-1716-4869-9b2d-f3475f4c6f13.png)

### Steps to reproduce

- Create a empty project
- Add a Global Shader in the Project Parameter
- Test with a Type Boolean -> the value is correctly writing in the Project.godot
- Test with a other Type (Sampler2d) -> the value is no writing in the Project.godot

**Comment by clayjohn** [comment] 2022-11-10 20:17
Duplicate of https://github.com/godotengine/godot/issues/60805

**Closed by clayjohn** 2022-11-10 20:17 UTC
