### ISSUE TITLE
Audio plays incorrectly from a StateMachine (regression 4.3.dev4)

### ISSUE THREAD

**Issue by dandeliondino** [godotengine/godot#89730] opened 2024-03-21 05:08 UTC
### Tested versions

- Reproducible in 4.3.dev4 and 4.3.dev5
- Not reproducible in 4.3.dev3 and 4.2.2-rc2

### System information

Godot v4.3.dev4 - Windows 10.0.22621 - GLES3 (Compatibility) - NVIDIA GeForce RTX 3080 Laptop GPU (NVIDIA; 31.0.15.4633) - 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz (16 Threads)

### Issue description

An AudioStreamPlayer with `playing=true` in a AnimationPlayer animation plays back incorrectly when the animation is played from a StateMachine inside an AnimationTree. It sounds like it may be a buzz of the first milliseconds on repeat.

Videos of the MRP (audio from [Kenney's Music Jingles](https://www.kenney.nl/assets/music-jingles)):

https://github.com/godotengine/godot/assets/68911895/4ce4f9d5-c6da-4b0b-8178-3924e696fd41

https://github.com/godotengine/godot/assets/68911895/337ed607-3a52-4f35-8bed-df38a5c4701c

Things that don't change the outcome:
- Using a different audio file, or encoding as OGG vs WAV
- Setting the animation track, AudioStream and/or the AudioStreamPlayer to loop
- Changing the AudioStreamPlayer to AudioStreamPlayer3D
- Changing the StateMachine transitions
- Whether the AnimationTree is set to `deterministic` 
- Adding the AudioStreamPlayer's track to all animations

Note: This project incidentally triggers the spurious `_transition_to_next_recursive` error from #82935, so I also tested with #89575, and can confirm that PR fixes the error (and, as expected, reproduces this bug).

### Steps to reproduce

- Create an **AudioStreamPlayer** and assign an AudioStream. Note that it plays back correctly in the Inspector.
- Create an **AnimationPlayer**. Create a new animation, add a track for the AudioStreamPlayer's `playing` property and set it to true. Note that it plays back correctly when the animation is played.
- Create an **AnimationTree**. Set the `Anim Player` path to the AnimationPlayer. Create a StateMachine node. Add the animation with the audio track to the state machine. Note that it plays back **incorrectly** when the StateMachine node is played.

### Minimal reproduction project (MRP)

[state-machine-audio.zip](https://github.com/godotengine/godot/files/14684784/state-machine-audio.zip)

**Comment by TokageItLab** [comment] 2024-03-21 08:25
Setting CallbackModeDiscrete to `Dominant` will provide the expected behavior.

![image](https://github.com/godotengine/godot/assets/61938263/85bb6062-1706-459b-bfe6-84dcb52c63f1)

However, this will still cause the audio to be interrupted by changing the stream to play when the state is changed. This is the intended behavior for ValueTrack. So, it is recommended to use AudioTrack for audio playback in the first place. AudioTrack has a `Don't Use Blend` property for that use cases where the playback stream exceeds the animation length.

![image](https://github.com/godotengine/godot/assets/61938263/bc249a03-b6db-4124-b077-e5f3f36f15c9)

**Comment by TokageItLab** [comment] 2024-06-04 23:55
Closed by https://github.com/godotengine/godot-website/pull/851

**Closed by TokageItLab** 2024-06-04 23:55 UTC
Labels: documentation, topic:animation
