### ISSUE TITLE
Vulkan: Occlusion culling incorrectly culls objects which are not completely occluded

### ISSUE THREAD

**Issue by TheWoodenTree** [godotengine/godot#70516] opened 2022-12-24 06:49 UTC
### Godot version

v4.0.beta9.official

### System information

Windows 10, Vulkan, GeForce GTX 1070 driver ver. 512.15

### Issue description

A large object being occluded by another large object will be incorrectly culled with occlusion culling when viewed almost off screen. I would expect that the object be fully occluded before being culled. 

This seems to not happen so long as the face of the occluder that is perpendicular to the object being occluded is not visible. The face colored red below is what I am referring to.

The issue also seems to only happen when the objects cover the whole screen, though this is not entirely the case for the second video I've provided.

![ex](https://user-images.githubusercontent.com/94566175/209424554-5d639d20-eadb-4e35-abd5-6a2ee88ab0c5.png)

Here is a video from a test project:

https://user-images.githubusercontent.com/94566175/209424410-57278a7d-6d34-4346-b6c3-fb0bc4de7313.mp4

Here is a video from a personal project where I first noticed the issue:

https://user-images.githubusercontent.com/94566175/209424430-34b225e1-7007-4f0e-af46-86df5bdd32a2.mp4

### Steps to reproduce

Create two large cube meshes slightly offset from one another
Create Occluder Instance 3D and bake
Approach one of objects closely such that it partially covers the other object 
Slowly move or rotate camera to occlude the other object
The object being occluded will (sometimes) be culled before it should be

### Minimal reproduction project

[Test.zip](https://github.com/godotengine/godot/files/10298113/Test.zip)

**Comment by Chaosus** [comment] 2022-12-24 06:51
Can you reproduce it on 3.x?

**Comment by TheWoodenTree** [comment] 2022-12-24 07:11
I tried this on 3.5.1 stable using an occluder shape and a similar setup; however I could not reproduce it. Forgive me if I am missing something here, I never used occlusion culling in 3.x and I'm not entirely sure if I've set it up here to work as needed.

https://user-images.githubusercontent.com/94566175/209425509-359e5c94-05fa-4e7f-8080-9b297e5419ea.mp4

**Comment by TheWoodenTree** [comment] 2022-12-24 07:31
I can also confirm this is still an issue in 4.0 beta 10.

**Comment by Calinou** [comment] 2022-12-24 16:55
Related to https://github.com/godotengine/godot/issues/63771.

**Comment by clayjohn** [comment] 2023-01-12 22:17
Duplicate of https://github.com/godotengine/godot/issues/53288. Closing in favour of https://github.com/godotengine/godot/issues/53288 so we can track this issue in only one place

**Closed by clayjohn** 2023-01-12 22:17 UTC
Labels: bug, topic:rendering, regression, topic:3d
