### ISSUE TITLE
All sprites are black

### ISSUE THREAD

**Issue by toby3d** [godotengine/godot#8927] opened 2017-05-26 14:04 UTC
**Operating system or device - Godot version:** Build from a75623f commit, Linux Mint Mate 18.1 x86_64
**Issue description:**
ALL sprites are black.
![image](https://cloud.githubusercontent.com/assets/5412322/26497661/ab6f5ede-4245-11e7-95a8-b5e4c2f09f03.png)

In project directory:
![image](https://cloud.githubusercontent.com/assets/5412322/26497739/f9802cf2-4245-11e7-90ae-2a822beab53e.png)

**Comment by akien-mga** [comment] 2017-05-26 14:08
Sync with the current master branch, it is fixed already.

Duplicate of #8801.

**Closed by akien-mga** 2017-05-26 14:08 UTC
