### ISSUE TITLE
script editor saving when should not

### ISSUE THREAD

**Issue by dmaz** [godotengine/godot#68802] opened 2022-11-17 19:08 UTC
### Godot version

v4.0.beta.custom_build [49cc12bf8]

### System information

Windows 10

### Issue description

the script editor saves even when it should not.  this may or may not be related to https://github.com/godotengine/godot/issues/68795 but I've only just noticed it since I started getting that issue.   

Text Editor/ Behavior/ Autosave Interval = 0
Interface/ Editor/ Save On Focus Lost = off
Run/ Auto Save = on

if I make a change to code and then close the editor it will save that change even though it should not.  I don't have an issue with an autosave happening in the background for recovery in the case of crashes.  but it should not write those changes to the actual file.  as of the the most recent build this issue seems to lead to the issue listed above when reopening the file.  and can get even a little more messy when the change wasn't compilable code.

### Steps to reproduce

- open the editor
- make sure auto save settings don't auto save...
- make a code change
- close the editor without saving  ( I generally don't even get prompted to save the code change)
- open the editor and the file... if you don't have a blank file (re issue linked above) you should see the changes you made but did not save

**Comment by Calinou** [comment] 2022-11-17 19:20
This is likely because editor state is preserved across sessions (such as scrolling position), and this includes the file's contents.

cc @Paulb23

**Comment by dmaz** [comment] 2022-11-17 19:44
ah... ok but should it really do that without any kind of notification?  I would expect a prompt asking if you want to save or not.   and isn't that inconsistent with other editors like the scene editor.

it's a quirk I could get used if there were some kind of indicators that there are unsaved changes.  vscode saves the session like that but it also clearly shows which files have unsaved changes  (not to mention it also has gutter diffs vs git.)

actaully that brings up another new issue... horizontal scroll position gets set wrong in the editor sometimes.  sometimes after I reopen the editor a few of my files will have the horizontal scroll in a position other than 0 and other than what it was last at.

**Comment by KoBeWi** [comment] 2022-11-17 22:44
Duplicate of #18010

**Closed by KoBeWi** 2022-11-17 22:44 UTC
Labels: bug, topic:editor
