### ISSUE TITLE
Problem with get_global_mouse_position in multiple Viewports

### ISSUE THREAD

**Issue by Nophlock** [godotengine/godot#31551] opened 2019-08-21 23:39 UTC
**Godot version:** 
3.1.1 - Stable

**OS/device including version:**
Windows 10-64 Bit

**Issue description:**
Hello,

I'm currently trying to implement split-screen in my game and after watching some tutorials I decided to gave this a go. At first everything seems to work fine, but then I stumbled upon the problem, that my topdown-character doesn't want to "look" at the mouse-position anymore. After some more investigation I found out, that the problem seems related to the Stretch-Mode that I have defined(currently "2D" and "keep" for the aspect) because the "lookat" function seemed to kinda work when I maximize the window but not, as soon as I start walking away from the origin with my player. 

The code/function I use to let the player look at the mouse is basically just this:
```
func getLookatDirection() -> float:
	var mpos = self.attached_to.get_global_mouse_position()
	var apos = self.attached_to.global_position 
	var diff = mpos - apos

	return diff.angle()
```
With that everything worked fine, as long as I've got only one player (actually the other player is controlled with an PS4-Controller and only one player is using the PC-Inputs), but with two or more it's basically impossible to aim at anything. Since I have no clue now how to fix this, I decided to create this Issue even though this might not be a bug at all and I just used the wrong function(maybe the get_global_mouse_position isn't just the right function to use in this case even though I expected to take this kind of stuff into account and always give me the correct global position). Regardless of this, it would be pretty nice if someone could help me out with this (basically all I want in relation to the minimal reproduction project is, that the red and blue sprites are aware of the split-screen and depending in which viewport the mouse currently is, the red or blue sprite should perfectly look at the mouse position). 

I hope it was understandable what I mean and I'm looking forward for any help ^^ 

**Steps to reproduce:**
I think the easiest way is to just look at the example project I've provided

**Minimal reproduction project:**
[Multiple_Viewports_Bug.zip](https://github.com/godotengine/godot/files/3527664/Multiple_Viewports_Bug.zip)

**Comment by KoBeWi** [comment] 2019-08-22 01:06
Sounds like #31551 or #30950

**Comment by bojidar-bg** [comment] 2019-08-22 06:52
Definitely sounds like #31551 -- it is the same issue after all..

**Comment by KoBeWi** [comment] 2019-08-22 10:21
Omg ;_;
I meant #30215

**Comment by Nophlock** [comment] 2019-08-22 12:56
Oh wow, I totally overlooked these Issues and yeah I'm pretty sure they are related to mine ... sorry. Anyway if anyone stumbles upon the same problem as I(and to make this issue here at least a bit useful), I found a workaround that's works with window scaling etc.

I simply calculate the mouse position by myself. Here is the function that I have created for this:

```
func getViewportMousePosition() -> Vector2:
	
	var target_window_size	= Vector2(1920, 1080)# the target width and height settings under the project settings
	var global_mouse_pos 	= self.get_viewport().get_mouse_position()#gets the normal window mouse position, cause the normal camera_viewport is still attached to the main viewport
	var viewport_size	= OS.window_size / target_window_size#calculate the scale factor(for the stretch thing)
	var viewport_position	= self.camera.custom_viewport.get_parent().rect_global_position * viewport_size#calculate the position based on the viewport_container
	var viewport_mouse_pos	= global_mouse_pos + self.camera.global_position - (self.camera.custom_viewport.size * viewport_size) * 0.5#shifts the mouse position to the camera/viewport space 
	viewport_mouse_pos	= viewport_mouse_pos - viewport_position #sub the viewport position to get the final position in relation to the custom_viewport

	return viewport_mouse_pos
```
If you want to give this a go, you can simple place this function inside the "LookAtMouse.gd" that I've provided in the "Minimal reproduction project" and use this one instead of the "get_global_mouse_position". After that, it shouldn't be to hard to adapt these codelines to your own project.

Hope this helps someone

**Comment by KoBeWi** [comment] 2019-08-24 21:15
So yeah, this really is about viewports and stretch mode, so closing it as a duplicate of #30950

**Closed by KoBeWi** 2019-08-24 21:15 UTC
