### ISSUE TITLE
AnimationPlayer.stop(true) followed by AnimationPlayer.advance() misbehaving

### ISSUE THREAD

**Issue by AndHalfAFish** [godotengine/godot#59662] opened 2022-03-29 07:27 UTC
### Godot version

3.4.4

### System information

windows 10

### Issue description

At the startup of a project, I expect these 2 options to give me the same result (anim length = 1 sec) :

option 1 :
AnimationPlayer.stop(   false   )  <==
AnimationPlayer.advance(1)         

option 2 :
AnimationPlayer.stop(   true  )  <==
AnimationPlayer.advance(1)

They don't. Option 1 behaves as expected, option 2 doesn't.

### Steps to reproduce

see sample project

### Minimal reproduction project

[bug_animplayer.zip](https://github.com/godotengine/godot/files/8369012/bug_animplayer.zip)

**Comment by golddotasksquestions** [comment] 2022-03-29 13:00
Just to clarify: You did not say what exactly your expected behaviour is. Since `stop(false)` is [actually a pause](https://github.com/godotengine/godot/issues/34125), I assume you would expect the animation to continue to advance form the exact timestamp it was paused at, after `advance()` is called?

At least this is what I would be expecting. Which is indeed not happening. Instead nothing is happening when `advance()` is called

**Comment by Calinou** [comment] 2022-03-29 17:30
Duplicate of https://github.com/godotengine/godot/issues/27499 (same cause).

**Closed by Calinou** 2022-03-29 17:30 UTC
Labels: bug, topic:animation
