### ISSUE TITLE
C# Connecting a signal autogenerates function outside of class

### ISSUE THREAD

**Issue by ArikRahman** [godotengine/godot#70387] opened 2022-12-21 05:55 UTC
### Godot version

3.5.1 stable

### System information

Arch Linux

### Issue description

Connecting a signal autogenerates the function outside the node's class and gives an error that top-level function do not exist yet in Godot

![image](https://user-images.githubusercontent.com/40479733/208831937-61be7921-3c69-49ff-9fe7-693db9397792.png)

### Steps to reproduce

Connect signals in Godot

### Minimal reproduction project

N/A

**Comment by Zireael07** [comment] 2022-12-21 09:18
IIRC already reported

**Comment by raulsntos** [comment] 2022-12-21 13:34
Duplicate of https://github.com/godotengine/godot/issues/18721

**Closed by raulsntos** 2022-12-21 13:34 UTC
