### ISSUE TITLE
Continues Crash on MAC M1

### ISSUE THREAD

**Issue by Alonxx** [godotengine/godot#75571] opened 2023-04-01 17:27 UTC
### Godot version

4.0.1

### System information

macOS 13.2.1 (22D68)

### Issue description

Godot 4 crashes randomly when I want to save the scene (command + s or save from options) It has happened to me with different projects created from scratch, including the tutorial project.

Just after opening and closing several times, it starts to be able to save normally without crashing

It doesn't crash when I run the scene.

This never happened to me with Godot 3.5

[Godot Error Details.txt](https://github.com/godotengine/godot/files/11130171/Godot.Error.Details.txt)

### Steps to reproduce

Save de scene whit command + s or save from options

### Minimal reproduction project

N/A

**Comment by Calinou** [comment] 2023-04-01 19:24
- Duplicate of https://github.com/godotengine/godot/issues/74846.

**Closed by Calinou** 2023-04-01 19:24 UTC
Labels: bug, platform:macos, topic:editor, topic:porting, crash
