### ISSUE TITLE
Code completion not working on references (for me)

### ISSUE THREAD

**Issue by Footurist** [godotengine/godot#16936] opened 2018-02-23 00:58 UTC
Example:

```
extends Node2D

func _ready():
    var anim = Animation.new().(here, the code completion works)
    anim.(here, no completion)
```

Any idea why?

**Comment by vnen** [comment] 2018-02-23 04:24
Please follow the template when filing issues. I don't which Godot version you're using, for instance. Also note that this is not a place for general questions, you can use the [community channels](https://godotengine.org/community) for that.

In any case, this is a duplicate of #16257, so I'll close this.

**Closed by vnen** 2018-02-23 04:24 UTC
