### ISSUE TITLE
Cannot export for Android in CI/CD

### ISSUE THREAD

**Issue by AdrKacz** [godotengine/godot#78412] opened 2023-06-18 16:24 UTC
### Godot version

4.0.3

### System information

MacOS M1

### Issue description

I want to build my game in CI/CD, unfortunately, I didn't manage to solve the `Android build template not installed in the project. Install it from the Project menu.` error.

I initially add these three errors:
```
No export template found at the expected path:
/Users/builder/Library/Application Support/Godot/export_templates/4.0.3.stable/android_source.zip
Android build template not installed in the project. Install it from the Project menu.
A valid Android SDK path is required in Editor Settings.
```

### Steps to reproduce

```
# Install android sdk
cd ~/
curl -LO https://dl.google.com/android/repository/commandlinetools-mac-9477386_latest.zip
unzip commandlinetools-mac-9477386_latest.zip
mkdir android-sdk/ && mv cmdline-tools android-sdk/ && cd android-sdk/cmdline-tools
mkdir -p latest/
mv lib latest/
mv bin latest/
mv NOTICE.txt latest/
mv source.properties latest/
cd ~/clone
yes | /Users/builder/android-sdk/cmdline-tools/latest/bin/sdkmanager \
    --sdk_root=/Users/builder/android-sdk/ \
    "platform-tools" "build-tools;33.0.2" "platforms;android-33" \
    "cmdline-tools;latest" "cmake;3.10.2.4988404" "ndk;23.2.8568313"

# Install godot latest
brew install --cask godot

# Install export templates
cd ~/
GODOT_VERSION=$(godot --version | awk -F '.' '{print $1"."$2"."$3}')
curl -LO https://github.com/godotengine/godot/releases/download/${GODOT_VERSION}-stable/Godot_v${GODOT_VERSION}-stable_export_templates.tpz
unzip Godot_v${GODOT_VERSION}-stable_export_templates.tpz
GODOT_TEMPLATE_DIR="/Users/builder/Library/Application Support/Godot/export_templates/${GODOT_VERSION}.stable/"
mkdir -p $GODOT_TEMPLATE_DIR && mv templates/* $GODOT_TEMPLATE_DIR

# Add secret to export presets
python3 scripts/exports/create-export-preset.py \
    --path $CM_KEYSTORE_PATH \
    --alias $CM_KEY_ALIAS \
    --password $CM_KEY_PASSWORD

# Build first attempt (to generate exports and file in Application Support)
cd mobile-game/
godot --export-release "Android" ../exports/android/scaling-broccoli.aab --headless
cd ~/clone

# Update Android SDK path in Godot Editor with CLI
python3 scripts/exports/update-editor-settings.py \
    --path "/Users/builder/Library/Application Support/Godot/editor_settings-4.tres" \
    --sdk "/Users/builder/android-sdk/"

# Build second attempt (the one that fires an error but shouldn't)
cd mobile-game/
godot --export-release "Android" ../exports/android/scaling-broccoli.aab --headless
cd ~/clone
```

The `godot --export-release "Android" ../exports/android/scaling-broccoli.aab --headless
` command works on my MacBook *(the one I use to develop, so I used the UI to install all the needed tools and dependencies)*.

`scripts/exports/create-export-preset.py` just populate the `export_presents` with secrets, so I don't have to commit them.

`scripts/exports/update-editor-settings.py` simply sets the correct value for `android_sdk_path` in the editor settings.

### Minimal reproduction project

You can clone this project: https://github.com/AdrKacz/scaling-broccoli
But you'll have the same error with any project that exports for Android and don't use the same machine for development and for builds

**Comment by AdrKacz** [comment] 2023-06-19 12:38
Right, thank you for your advice.

Do you have indication how to create the project? I guess not "any" Android project would work? Do Godot has a template somewhere?

If not, will just create the folder structure be enough?

If you don't have answers no worries, I'll sing into Godot source code to understand how it is generating these fields, but there are probably faster answers 😉

**Comment by AThousandShips** [comment] 2023-06-19 12:43
Note that this is for bug reports and not support questions, prefer to turn to the other [community channels](https://godotengine.org/community) for support questions, but someone might still be able to help you, just keep in mind

**Comment by AdrKacz** [comment] 2023-06-19 19:54
Yes I understand. However I consider it more of a bug than a support issue. Indeed, when using a software that let you use the CLI, you would expect, _at least_, to be able to build from any machine. However Godot still have some _options_ that are only accessible via UI (installing the build templates and generating the Android files, I didn't check for other platform).

The community will find a workaround _(as I did in my comment above)_, but workarounds shouldn't be the way to go ([see this one for example](https://github.com/godotengine/godot-proposals/issues/1362#issuecomment-1379140108))

Let me know if I can help to improve the user experience 👍

**Comment by AdrKacz** [comment] 2023-06-19 19:55
Just linking this comment for reference as it gives a path for mitigation: https://github.com/godotengine/godot/issues/35600#issuecomment-898908949

**Comment by Calinou** [comment] 2023-06-19 20:24
Either way, this is a duplicate of https://github.com/godotengine/godot/issues/38327.

**Closed by Calinou** 2023-06-19 20:24 UTC
Labels: platform:android, topic:export

**Comment by AdrKacz** [comment] 2023-06-19 20:59
The method mentioned in https://github.com/godotengine/godot/issues/35600#issuecomment-898908949  or in your comment above doesn't work.

I created an `android` folder within my main folder with the content of `android_source.zip`, I still read the error message:

```
ERROR: Cannot export project with preset "Android" due to configuration errors:
Android build template not installed in the project. Install it from the Project menu.
```

Here is the content of the game folder:
```
$ ls
AutoLoad		Materials		Themes			assets			icon.png
Design			Scenes			UI			default_bus_layout.tres	icon.png.import
ExternalVisuals		Shaders			addons			default_env.tres	project.godot
Game			SplashScreen		android			export_presets.cfg
```

And here is the content of the `android` folder:
```
$ ls android 
AndroidManifest.xml	build.gradle		gradle.properties	libs			src
assetPacks		config.gradle		gradlew			res
assets			gradle			gradlew.bat		settings.gradle
```

Do you have further indications please?

Can you please not close the issue until it is resolved? It will not only benefit myself but also all future users that will encounter this problem and search for an answer (so they won't have to open _another_ issue, again and again).

**Comment by ntngamedev** [comment] 2025-05-15 23:19
Nothing?
