### ISSUE TITLE
Android image to texture bug

### ISSUE THREAD

**Issue by Bethleem** [godotengine/godot#33622] opened 2019-11-14 15:16 UTC
**Godot version:** Godot v3.1.1 stable win32

**OS/device including version:** Windows 7/PC and Android 6.0/ARM

**Issue description:** When use the ImageTexture function create_from_image(), the output texture failed to be recognized in android while it runs ok in desktop.

**Steps to reproduce:**
Create a new Image.
Load a png file in it. 
Resize,colorize or do somenthing with it.
Create new ImageTexture.
Use ImageTexture.create_from_image() with the former Image.
Create new Sprite.
Assign Sprite.texture=ImageTexture

In Windows it works just fine, the sprite shows the modified Image texture. In android, nothing but empty sprites.

**Minimal reproduction project:**

No point, it will be a empty screen.

**Comment by volzhs** [comment] 2019-11-14 16:35
is png file loaded successfully?

**Comment by Bethleem** [comment] 2019-11-16 15:23
Yes. As I said, it works fine in desktop, so the file loads properly.  Same code, failed in android.

**Comment by dankan1890** [comment] 2019-11-17 16:22
It would seem a "path" problem, but without a minimal project to analyze it is difficult to fix.

**Comment by volzhs** [comment] 2019-11-18 07:17
you can't say png is loaded successfully on android because it works on pc.
on windows, a file can be loaded regardless of capital letters with the path.
like `res://image.PNG` can be loaded with `res://image.png`
but not on android or other platforms.

**Comment by Bethleem** [comment] 2019-11-19 11:38
It´s not a path issue, to the extent of my knowledge. Same path loaded into a sprite works fine both in desktop/android. Loaded trought the expalined pipeline Image->ImageTexture->Sprite.texture, failed only in android. I just check again for the thrid time.

**Comment by Zireael07** [comment] 2019-11-19 11:49
Maybe it's a format problem? Do you have ETC/ETC2 ticked in project settings?

**Comment by volzhs** [comment] 2019-11-19 12:38
@Bethleem can you share a reproducible project?

**Comment by KoBeWi** [comment] 2020-10-07 22:45
Closing due to lack of update. Please comment if you can still reproduce this issue in the latest stable version of Godot.

**Closed by KoBeWi** 2020-10-07 22:45 UTC
Labels: bug, platform:android, topic:core
