### ISSUE TITLE
Game crashes when using cpu particles 3D

### ISSUE THREAD

**Issue by CachorroVoador** [godotengine/godot#75364] opened 2023-03-26 17:21 UTC
### Godot version

4.0.1.stable

### System information

Windows 10, Intel i5 650, gt 710, 4gb ram

### Issue description

When placing cpu particles, the game crashed when loading the scene. I tweaked it and found that when the game is using multi-threaded, the game crashes, but on single thread, it runs without any problem

https://user-images.githubusercontent.com/87171245/227792774-2f0966b9-85a8-4899-b2b6-2c419c15f9d5.mp4

### Steps to reproduce

Add CPU Particles to the Scene
Put the game to use multi-thread
play the scene

### Minimal reproduction project

[particle_crash_bug.zip](https://github.com/godotengine/godot/files/11072411/particle_crash_bug.zip)

**Comment by Calinou** [comment] 2023-03-26 17:37
- Duplicate of https://github.com/godotengine/godot/issues/61650.

**Closed by Calinou** 2023-03-26 17:37 UTC
