### ISSUE TITLE
Interesting billboard AnimatedSprite3D shadow behaviour

### ISSUE THREAD

**Issue by lego-engineer** [godotengine/godot#61349] opened 2022-05-24 07:47 UTC
### Godot version

3.4.4.stable.offical [419e713a2]

### System information

Windows 10 (x86), GLES3 & GLES2,  NVIDIA GeForce RTX 3080 (30.0.14.7212)

### Issue description

I was experimenting with shadows, billboard, and AnimatedSprite3D today and encountered some interesting behavior. I am not sure if this is actually a bug or the expected/intended behavior.

Using a rear light source on a billboard enabled AnimatedSprite3D results in a flipped shadow. When using a front light source, the shadow appears normally. When using a rear light source with billboard turned off, shadows appear normally if double sided is turned on (if double sided is off no shadow appears).

I tested the scenario a few times and I am guessing that when billboard is turned on, the sprite is rotated 180 degrees face the light source to generate the shadow. This generates a shadow which is rotated 180 degrees, so it looks flipped. 

Here are some images illustrating the phenomenon:
billboard_off_light_behind
![billboard_off_light_behind](https://user-images.githubusercontent.com/43705065/169973236-c9ca36bd-9f01-4926-a423-70928d63f44b.PNG)
billboard_on_light_behind
![billboard_on_light_behind](https://user-images.githubusercontent.com/43705065/169973248-56dc2418-c48a-4ef7-b6db-ca09b48542cd.PNG)
[billboard_on_light_front
![billboard_on_light_front](https://user-images.githubusercontent.com/43705065/169973252-53c69221-47cd-4960-906c-97d71b0cba98.PNG)
billboard_off_light_front
![billboard_off_light_front](https://user-images.githubusercontent.com/43705065/169973244-85072d96-400e-4c34-ab2b-ad38e60c8ce6.PNG)

### Steps to reproduce

I believe all that is required to reproduce is:
- Generate a AnimatedSprite3D with a non-symmetric sprite (its possible that any SpriteBase3D would work, but I haven't tested)
- Enable shadows and billboard on the AnimatedSprite3D 
- Create a surface upon which to project a shadow (the ground)
- Create a light source behind the AnimatedSprite3D which can cause it to cast a shadow
- Place a camera in front of the AnimatedSprite3D facing the sprite

In my example, you can open the Player scene and access the PlayerAnimatedSprite3D `Billboard = Enabled` and `Billboard = Disabled` and `Double Sided` (boolean) options.  The Camera may be moved from the front to back using Main scene's LightPivot object. I have been modifying the pivots Transform property using `Rotation Degrees.X = 0` or `Rotation Degrees.X = 90`

Moving the light source to the side ( `Rotation Degrees.Y = 90`) is also interesting as it shows a similar effect from a side light source. 

### Minimal reproduction project

[godot.zip](https://github.com/godotengine/godot/files/8760443/godot.zip)

**Comment by clayjohn** [comment] 2022-11-23 02:40
Duplicate of https://github.com/godotengine/godot/issues/41420

Closing this so we can track the issue in one place

**Closed by clayjohn** 2022-11-23 02:40 UTC
Labels: discussion, topic:rendering, topic:3d
