### ISSUE TITLE
Scene Tree view update is very slow with complex scenes when deleting nodes

### ISSUE THREAD

**Issue by kevhayes2010** [godotengine/godot#100284] opened 2024-12-11 16:22 UTC
### Tested versions

v4.4.dev6.official [1f47e4c4e]

### System information

Godot v4.4.dev6 - Windows 10.0.19045 - Multi-window, 2 monitors - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 4090 (NVIDIA; 32.0.15.6603) - AMD Ryzen 9 5950X 16-Core Processor (32 threads)

### Issue description

In a complex scene with 10k+ nodes, deleting a node in the editor takes a long time for the scene to update - 10 to 15 seconds on average. Weirdly undoing the action immediately after deletion is almost instantaneous.

### Steps to reproduce

Create a new scene, use a tool like Proton scatter to mass place thousands of either copies or instances (the net result is the same), manually place one or more instances of a Node3d scene and then delete one of them.

### Minimal reproduction project (MRP)

NA

**Comment by AeioMuch** [comment] 2024-12-11 16:40
Duplicate of https://github.com/godotengine/godot/issues/83460
If you want to play around with the artifact of https://github.com/godotengine/godot/pull/99700 to see how it improves for you and if everything behave as expected or if you find a bug that would be great also !

**Comment by kevhayes2010** [comment] 2024-12-11 16:46
Thankyou for the response @AeioMuch I will give that a try.

**Comment by akien-mga** [comment] 2024-12-11 16:58
Consolidating in https://github.com/godotengine/godot/issues/83460.

**Closed by akien-mga** 2024-12-11 16:58 UTC
