### ISSUE TITLE
Vulkan: Using a lot of different materials spams error message

### ISSUE THREAD

**Issue by nonunknown** [godotengine/godot#59912] opened 2022-04-05 13:14 UTC
### Godot version

v4.0.alpha.mono.custom_build [a647fb3e6]

### System information

manjaro KDE

### Issue description

I'm testing the game a lot, this needs to constantly and frequently open and close the game, but suddenly the engine freezes with the following message:

```
ERROR: Condition "!material" is true.                                                                       ✔ 
   at: material_update_dependency (servers/rendering/renderer_rd/renderer_storage_rd.cpp:462)
ERROR: Condition "!material" is true. Returning: true
   at: material_casts_shadows (servers/rendering/renderer_rd/renderer_storage_rd.cpp:437)
ERROR: Condition "!material" is true. Returning: false
   at: material_is_animated (servers/rendering/renderer_rd/renderer_storage_rd.cpp:424)
ERROR: Condition "!material" is true.
   at: material_get_instance_shader_parameters (servers/rendering/renderer_rd/renderer_storage_rd.cpp:450)
```

### Steps to reproduce

**New way**:
* Close the **engine** by clicking on [X]

**Old way**:
No Idea how to reproduce, but since its related to materials, I'm using particles, so maybe a possibility could be:

* Use a lot of materials
* Close/Open the game a lot of times fast

### Minimal reproduction project

N/a

**Comment by marstaik** [comment] 2022-04-05 17:40
How old is this build? This seems related to https://github.com/godotengine/godot/pull/58491 - My guess would be that the textures allocated are never freed and the engine runs to exhaustion. But that's just my 2 second analysis.

**Comment by nonunknown** [comment] 2022-04-05 19:17
5 days ago, you can simply check by going into `Godot Version` above.

**Comment by marstaik** [comment] 2022-04-05 20:26
Ah my bad, I missed it and I didn't even realize that was a clickable version link 😮

**Comment by nonunknown** [comment] 2022-04-06 17:56
Just updated the post, I found another bug which was `The engine doesnt close via [X]` but I found that what doesnt let the engine close is actually this material bug reported above

**Comment by Zireael07** [comment] 2022-04-07 16:44
Not too sure if it's the same issue (didn't see the output panel) but I had the engine completely freeze and then crash on me. I only had two scenes opened (main, which does use more materials but not in editor, they're preload()'ed for in-game use, and the prefab I was working on, which only used one material.

Before it froze completely, it exhibited symptoms similar to a memleak...

**Comment by nonunknown** [comment] 2022-04-08 11:17
@Zireael07 you can open godot with terminal and use a `-v` argument after the executable name, then when it crashes you can see the output! also I recommend using the `debug` version, the errors will be more detailed!

**Comment by Zylann** [comment] 2022-05-16 20:14
I get the material error too:
```
servers\rendering\renderer_rd\storage_rd\material_storage.cpp:2633 - Condition "!material" is true.
```
It's not freezing for me, but when there are lots of materials it can take a very long time to endure the spamming.

**Comment by nonunknown** [comment] 2022-05-17 10:24
thanks for showing a way to reproduce, for me the engine is almost unusable, I have to close and open again every 5 min :/

**Comment by rcorre** [comment] 2022-08-14 15:18
FWIW, I'm hitting this using voxel_tools. I only have 1 material, and it doesn't freeze the engine, but I get about 4000 of these errors each time I regenerate the terrain.

**Comment by zurrealStudios** [comment] 2022-09-19 08:19
So I started getting this Errors while manipulating a Material of an Object through the "Surface Material Override" and was freeing them with "queue_free()"

My Workaround is to set the Override-Material to null before queueing it free:
```
Char.get_node("Model").set("surface_material_override/0", null)
Char.queue_free()
```

Maybe it has something to do, when something needs to be rendered but is queued free?
Hope this helps a little bit :)

**Comment by nonunknown** [comment] 2022-09-19 10:51
this error is already fixed, I didnt had this issue anymore, also not related to queue_free!

**Comment by Goutte** [comment] 2022-11-01 05:58
I'm seeing the same errors in `beta3` when I `queue_free()` a Node with a surface material override.   Unsetting the material right before `queue_free()`, like @zurrealStudios suggested, makes the error disappear.

Notes (may not be relevant):
- The culprit material is a `StandardMaterial3D`
- The culprit material has `resource_local_to_scene = true`
- The culprit material has a `next_pass`.

**Comment by Lippanon** [comment] 2023-01-22 01:08
Still present in v4.0.beta.custom_build [2ec0da1a7]:
![image](https://user-images.githubusercontent.com/115422160/213895876-8691f304-58e5-43c5-bad8-2a6fa7e4defa.png)
I see these errors when changing scenes or, as mentioned, freeing nodes with active surface_material_override.
A workaround, when applicable, is to use 'material_override' of GeometryInstance3D instead.

**Comment by bianpeng001** [comment] 2023-02-15 10:46
get the same error messages in 4.0rc2

**Comment by lucassene** [comment] 2023-03-12 10:17
I'm getting a bunch of these errors every time I call queue_free() on characters in my game:
![image](https://user-images.githubusercontent.com/16777494/224538265-8af5bc8d-6355-4b6e-bff5-05e558681612.png)

**Comment by clayjohn** [comment] 2023-03-13 21:50
I'm closing this in favour of https://github.com/godotengine/godot/issues/67144 which is more specific about what is causing the issue and includes an MRP. 

Please continue the discussion in https://github.com/godotengine/godot/issues/67144

Duplicate of https://github.com/godotengine/godot/issues/67144

**Closed by clayjohn** 2023-03-13 21:50 UTC
Labels: bug, topic:rendering, needs testing, topic:3d
