### ISSUE TITLE
LIGHT_VEC seems to have no effect

### ISSUE THREAD

**Issue by securas** [godotengine/godot#25581] opened 2019-02-03 15:09 UTC
**Godot version:**
3.1 beta 3

**OS/device including version:**
Windows 10, NVIDIA GTX 1070

**Issue description:**
LIGHT_VEC seems to have no effect with GLES3

**Steps to reproduce:**
Create light 2d with shadow enabled.
Create shader and modify LIGHT_VEC

**Minimal reproduction project:**

**Comment by QbieShay** [comment] 2019-02-03 16:00
Can you please make a reproduction case? Would be very helpful!

**Comment by securas** [comment] 2019-02-03 16:33
Sure... Here you go!

[test_light_vec_shader.zip](https://github.com/godotengine/godot/files/2825714/test_light_vec_shader.zip)

**Comment by QbieShay** [comment] 2019-02-05 19:43
Can confirm, light vec is assigned right after the light function [here](https://github.com/godotengine/godot/blob/master/drivers/gles3/shaders/canvas.glsl#L552)

**Comment by JFonS** [comment] 2019-02-06 16:57
LIGHT_VEC is only used to compute lighting when a normal map is used, and this seems to work fine.

Currently Light2D uses shadow mapping to create the 2D shadows, so it can only cast shadows from the light's pivot point. If you want to change the shadows you have to change the pivot point from a script. 
 
@securas What are you trying to achieve? To produce shadows you need to know the point where light is originated, only setting a light direction doesn't give you enough information to know if a point is lit or in shadow.

**Comment by securas** [comment] 2019-02-06 17:06
That's not the behavior observed in 3.0.6. There, a normal map was not
required to have light_vec.

I want to be able to change the shadow direction as was done in 2.x and 3.0.

**Comment by securas** [comment] 2019-02-06 23:12
@jfons do you mean by this that demos like 2.x's isometric lighting cannot be done in 3.1???

**Comment by JFonS** [comment] 2019-02-08 12:04
@securas you are right, I will take a look at restoring the 3.0 behaviour. 

But I still think, for future versions, LIGHT_VEC shouldn't affect shadows. The way it works in 3.0 doesn't make much sense and we should find a better way to change shadows from a light shader.

**Comment by QbieShay** [comment] 2019-02-08 12:13
@reduz

**Comment by akien-mga** [comment] 2019-02-22 09:06
Reopening as #25779 was reverted in #26125.

I guess what's needed now is better documentation about this intended limitation?

**Comment by securas** [comment] 2019-02-22 09:11
@akien-mga Should I understand that LIGHT_VEC will no longer allow doing what was done previously with shadows?

**Comment by JFonS** [comment] 2019-02-22 09:47
@securas Sadly taking into account `LIGHT_VEC ` breaks shadows for rotated lights, see #25996.

Now that I think about it I could add a new variable `SHADOW_VEC` to enable custom shadows without affecting the rest of light properties, would that be ok with you? I don't think it makes much geometrical sense to modify the shadow vector, but I understand it can have some marginal use cases.

**Comment by securas** [comment] 2019-02-22 09:55
Who am I to complain but I wanted to make a game with top down jrpg-like perspective and modify shadows in a way to have vertical shadows on the walls of buildings. Is that really a marginal case? I did a prototype in 2.1 and wanted to revisit it with 3.1. Is there an alternative to this without this feature?

**Comment by JFonS** [comment] 2019-02-22 10:24
My two main concerns are: 
* The behavior of shadows when modifying the sampling point of the shadow map is very confusing and having it tied to light direction might throw people off.
* Some people might want to change light direction independently of 2D shadows.

I think adding a `SHADOW_VEC` variable would take little effort and would solve both my concerns and your use case.

**Comment by securas** [comment] 2019-03-06 21:42
What was your final decision regarding this point? Will there be a changeable SHADOW_VEC on 3.1 or is this pushed to a later version?

thanks,
Ruben

**Comment by securas** [comment] 2019-03-07 05:48
Sorry... Pushed the wrong button

**Comment by securas** [comment] 2019-03-07 13:05
I see now that this is pushed to 3.2. It's sad that you break compatibility.

**Comment by azagaya** [comment] 2019-07-27 15:09
> What are you trying to achieve? To produce shadows you need to know the point where light is originated, only setting a light direction doesn't give you enough information to know if a point is lit or in shadow.

Hi, i'm having a similar problem. So, how can i get the point where the light is originated in 3.1? I thought i could get that point in screen view y doing FRAGCOORD.xy - LIGHT_VEC but doesn't seem to work.

**Comment by JFonS** [comment] 2019-09-20 08:05
Closing, as it was fixed in 3.2 by #31202.

**Closed** 2019-09-20 08:05 UTC
Labels: documentation, enhancement, topic:rendering
