### ISSUE TITLE
godot scaling error ide

### ISSUE THREAD

**Issue by marianokpo** [godotengine/godot#6629] opened 2016-09-27 10:41 UTC
**Operating system or device - Godot version:**
kubuntu 16.04 X64
core i5
ram 12gb
ati readeon hd 6870
Godot_v2.1-stable_x11.64

**Issue description** (what happened, and what was expected):
ide not scaled correctly, so you can not see the interface.
1920 \* 1080 is correctly
but not in 1360 \* 768

image 
http://postimg.org/gallery/2wz56gdbw/

**Steps to reproduce:**
godot open in a new installation of Kubuntu with the same resolution.

**Link to minimal example project** (optional but very welcome):

**Comment by Hinsbart** [comment] 2016-09-27 11:12
Likely a duplicate of #6096.
Also, the dpi detection has been changed slightly since 2.1. 
So if you could try that on a nightly build, it would be very helpful.

**Comment by marianokpo** [comment] 2016-09-27 16:48
You can fix it.
only change
global/hidpi_mode = 0
X
global/hidpi_mode = 1

**Comment by akien-mga** [comment] 2016-11-18 15:58
Closing as duplicate of #6096.

**Closed by akien-mga** 2016-11-18 15:58 UTC
Labels: bug, platform:linux, topic:editor, usability
