### ISSUE TITLE
FileSystem cache error when importing an OBJ file

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#13978] opened 2017-12-04 20:09 UTC
Godot 3.0 beta 1
Windows 10 64 bits

I opened a project, dropped an OBJ file in it, and I got an error popup telling me that Godot could not write to the filesystem cache.
Then the file showed up in this state:

![image](https://user-images.githubusercontent.com/1311555/33573750-0be7ea00-d937-11e7-914f-8305b7e0390e.png)

And the log:
```
ERROR: _parse_material_library: Condition ' !f ' is true. returned: ERR_CANT_OPEN
   At: editor\import\resource_importer_obj.cpp:47
Warning: Ambient light for material 'None' is ignored in PBR
current material library ship_gridmap_h.mtl has 1
current material None has 1
Added surface :None
current material library ship_gridmap_h.mtl has 1
current material None has 1
Added surface :None
current material library ship_gridmap_h.mtl has 1
current material None has 1
Added surface :None
current material library ship_gridmap_h.mtl has 1
current material None has 1
Added surface :None
current material library ship_gridmap_h.mtl has 1
current material None has 1
Added surface :None
current material library ship_gridmap_h.mtl has 1
current material None has 1
Added surface :None
current material library ship_gridmap_h.mtl has 1
current material None has 1
Added surface :None
current material library ship_gridmap_h.mtl has 1
current material None has 1
Added surface :None
current material library ship_gridmap_h.mtl has 1
current material None has 1
Added surface :None
current material library ship_gridmap_h.mtl has 1
current material None has 1
Added surface :None
ERROR: Node::set_name: Condition ' name == "" ' is true.
   At: scene\main\node.cpp:1142
node: Scene Root
node: MeshInstance
node: Cube.009_Cube.012
node: Cube.008_Cube.011
node: Cube.007_Cube.010
node: Cube.006_Cube.007
node: Cube.005_Cube.006
node: Cube.004_Cube.005
node: Cube.003
node: Cube.002_Cube.004
node: Cube.001_Cube.002
node: Cube_Cube.001
SAVING TO: res://.import/ship_gridmap_h.obj-4a529b2cabbf432dc4cf5b6d82791159.scn
ERROR: FileAccessWindows::close: Condition ' rename_error ' is true.
   At: drivers\windows\file_access_windows.cpp:139
```

The OBJ: 
[ship_gridmap_h.zip](https://github.com/godotengine/godot/files/1528617/ship_gridmap_h.zip)

Reimporting seems to restore a correct state, the OBJ is fine.

**Comment by Overblob** [comment] 2018-08-11 18:25
I got this one too

**Comment by glaforte** [comment] 2018-12-07 00:19
I tried to reproduce this issue on Godot master, unsuccessfully.
I'll find and build a version from December 4th 2017, next..

**Comment by glaforte** [comment] 2018-12-07 12:22
I could not reproduced the issue with about 20-30 attempts at various manipulations, on commit  a31735ad3608c9ec3a93db3ba294a7ad096fe453 (from December 4th 2017).
My hunch is that this issue is related to a Windows service temporarily taking the file after the copy happens? Maybe the anti-virus? Maybe the user's HD has a few weak bits? At this time, though, I'm afraid I'm not sure how to proceed...

**Comment by KoBeWi** [comment] 2020-06-13 12:02
This looks like it happened once and was never reproduced again, so it should be fine to close it (also it's similar to #6393).

**Closed by KoBeWi** 2020-06-13 12:02 UTC
Labels: bug, topic:import
