### ISSUE TITLE
Not null node refference crashes the engine

### ISSUE THREAD

**Issue by p-a-s-a-a** [godotengine/godot#69018] opened 2022-11-22 18:42 UTC
### Godot version

4.0 beta 5

### System information

Windows 11 | RTX 3050 | Vulkan | ...

### Issue description

The editor crashes when trying to access a not null child node data

https://user-images.githubusercontent.com/94804344/203394016-ca7b4125-b70f-4873-8cf6-f40052d14cc4.mp4

Note: it doesn't happen when refferencing an AnimationPlayer or RigidBody2D, I've only tested with Timer2D, Notifier2D and Raycast2D, AnimationPlayer and RigidBody2D.

### Steps to reproduce

- Cache a Node into a typed variable
- Try accessing any of its properties, signals, methods and others (ctrl + space)
- Some nodes will cause the editor to crash while trying to access its data

### Minimal reproduction project

[CrashVarRef.zip](https://github.com/godotengine/godot/files/10070142/CrashVarRef.zip)

**Comment by Sauermann** [comment] 2022-11-22 19:05
I tried to replicate this on Linux with v4.0.beta.custom_build [0aba65989] and godot did not crash, but showed instead a Menu with available properties.

**Comment by KoBeWi** [comment] 2022-11-22 19:15
Seems like duplicate of #68910

**Closed by KoBeWi** 2022-11-22 19:15 UTC
