### ISSUE TITLE
Godot 4.1.1 crashes on project open

### ISSUE THREAD

**Issue by Surfluff** [godotengine/godot#82690] opened 2023-10-02 18:16 UTC
### Godot version

4.1.1

### System information

Windows 11 - Godot 4.1.1 - Vulkan (Forward+) - Intel(R) Iris(R) Xe Graphics

### Issue description

Godot crashes on project open when the project is using Mobile or Forward+. This includes creating new projects as well as exported exe files of the project. Godot 3.5 worked without any problems so this issue confuses me. I have attached the verbose logs for the session of creating a new project.
[verboseLogs.txt](https://github.com/godotengine/godot/files/12785268/verboseLogs.txt)

Edit: The log also contains complete nonsense error and warning text.

### Steps to reproduce

- Open godot 4.1.1
- Open any Mobile or Forward+ project
- Crash

### Minimal reproduction project

N/A

**Comment by Zireael07** [comment] 2023-10-02 19:06
Godot 3.5 does NOT use Vulkan so the issue is most likely related to your computer's Vulkan support.

**Comment by CoolHandAR** [comment] 2023-10-03 19:08
Try using the compatibility mode. Your graphics card probably does not support Vulkan or you need to update your drivers.

**Comment by Chaosus** [comment] 2023-10-04 16:02
Duplicate of https://github.com/godotengine/godot/issues/81846

**Closed by Chaosus** 2023-10-04 16:02 UTC
