### ISSUE TITLE
Script Editor Freeze on Linux

### ISSUE THREAD

**Issue by Iddmeister** [godotengine/godot#36948] opened 2020-03-09 17:29 UTC
Godot version 3.2 RC 2
Linux 18.04.4

I've seen this issue before for Godot 3.1 but I don't think its been fixed

The Script editor randomly freezes regularly when using it. You can unfreeze it by pressing the shift key or the super key.

Not that bad an issue but it does become annoying after a while as it happens regularly

**Comment by Calinou** [comment] 2020-03-09 17:56
Duplicate of #27769.

**Closed by Calinou** 2020-03-09 17:56 UTC

**Comment by Zireael07** [comment] 2020-03-09 18:19
@Calinou: I think you typo'ed the issue number?
