### ISSUE TITLE
Exported enum vars on resources giving null default value

### ISSUE THREAD

**Issue by yhwhey** [godotengine/godot#66579] opened 2022-09-29 03:52 UTC
### Godot version

4.0b1

### System information

MacOS Monterey

### Issue description

When creating a custom resource type with an enum exported variable, any resources created of that type will have a field in the editor showing possible values to select. The first of the enum options will be selected by default in the editor.
However this is not actually representative, the value must be reselected to take effect and will be null when accessing the var by code.

### Steps to reproduce

1. Create custom resource script with enum (with at least two options) and exported var with type of the enum
2. Create resource of that type. Dont not change enum var. By default it shows a first enum option in editor
3. Try access that var by code. See that it is null, not first enum option

See attached project

### Minimal reproduction project

[export_enum_issue.zip](https://github.com/godotengine/godot/files/9670763/export_enum_issue.zip)

**Comment by Calinou** [comment] 2022-09-29 15:40
Related to https://github.com/godotengine/godot/issues/62753.

**Comment by dalexeev** [comment] 2023-02-11 17:57
Duplicate of #54040.

**Closed** 2023-02-11 18:56 UTC
Labels: bug, topic:gdscript, topic:editor
