### ISSUE TITLE
Naming builtin scripts doesn't work

### ISSUE THREAD

**Issue by olejr** [godotengine/godot#24729] opened 2019-01-03 01:04 UTC
Godot 3.1 Alpha 5

Window 10 x64
Nvidia 1070

Naming a buildin script doesn't give the right name.
![naming](https://user-images.githubusercontent.com/6444415/50619769-8ad05500-0efb-11e9-9c11-5f19c343dc96.png)

**Comment by volzhs** [comment] 2019-01-03 01:37
duplicate of #24695

**Closed by volzhs** 2019-01-03 01:37 UTC
