### ISSUE TITLE
Changing visibility of CSG-nodes crashes the editor silently (Godot 4.1.4 RC 2)

### ISSUE THREAD

**Issue by GNSS-Stylist** [godotengine/godot#89640] opened 2024-03-18 11:58 UTC
### Tested versions

- Reproducible in 4.1.4 RC 2
- Not reproducible in 4.1.3 stable
- Not reproducible in 4.3 dev5
- Not reproducible in 4.2.1 stable

### System information

Godot v4.1.4.rc2 - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 2060 (NVIDIA; 31.0.15.5176) - Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz (12 Threads)

### Issue description

Changing the visibility of CSG-shapes (tested with CSGBox3D, though) crashes the editor after a short freeze. No messages are printed into the console. It doesn't make any difference if visibility is changed from the parent node or some of the CSG-nodes. This does not happen in version 4.1.3 stable.
Video:

https://github.com/godotengine/godot/assets/50438441/0cf1bffe-432c-4157-ae5e-f6972fe224d4

Although not seen in the video it doesn't matter which way the visibility is changed or which node's visibility is changed (parent or any CSG-node).

### Steps to reproduce

- Create a CSG-node
- Change CSG-node's visibility. Editor freezes and shuts down after a while.

### Minimal reproduction project (MRP)

[CSGVisibilityChangeCrash.zip](https://github.com/godotengine/godot/files/14635733/CSGVisibilityChangeCrash.zip)

**Comment by AThousandShips** [comment] 2024-03-18 17:41
Sounds like:
* https://github.com/godotengine/godot/issues/84304

Which was caused by something cherry picked for 4.1.4

**Comment by GNSS-Stylist** [comment] 2024-03-18 20:36
Investigated this a bit and it indeed looks like the cherry-picked commit cf61f5e93809c9f80efdea08f733f2615867cb1d (PR https://github.com/godotengine/godot/pull/84174 ) is related to this. Editor doesn't crash after reverting changes by that commit. @jsjtxietian 

Tested also 4.3.dev5 and crash doesn't happen. So the change is somehow incompatible with 4.1? I could investigate this deeper but I don't understand enough of the intricacies in this.

**Comment by jsjtxietian** [comment] 2024-03-19 11:37
Yes looks like the fix (https://github.com/godotengine/godot/pull/84338) should also be cherry-picked?

**Comment by GNSS-Stylist** [comment] 2024-03-19 20:03
Can confirm that cherry-picking the aforementioned PR (https://github.com/godotengine/godot/pull/84338) fixes the editor crash with the project it first manifested in and with the MRP above. (Although I "cherry picked" it by copy-paste).

**Comment by akien-mga** [comment] 2024-04-08 20:05
Should be fixed in 4.1.4 RC 3 and stable.

**Closed by akien-mga** 2024-04-08 20:05 UTC
Labels: bug, topic:editor, crash, regression, topic:3d

**Comment by GNSS-Stylist** [comment] 2024-04-13 05:15
Just confirming: Tried 4.1.4 RC3 with the MRP and the project where this first manifested in and the crash doesn't happen any more.
