### ISSUE TITLE
Unable to build master with Scons 3.0.4 and MSVC 2017

### ISSUE THREAD

**Issue by novhack** [godotengine/godot#26461] opened 2019-03-01 22:34 UTC
**Godot version:**
Godot master, latest commit 78fcbb8

**OS/device including version:**
Windows 10, Python 3.7.2, Scons 3.0.4, MSVC 2017

**Issue description:**
The Windows installer of Scons has been deprecated so the only way to install Scons is through pip.
With `pip install scons` the latest production version 3.0.4 is installed and Godot build script seems not to work with it and prints out this error: 

`scons: Reading SConscript files ...`
`IndexError: list index out of range:`
`  File "C:\GitHub\godot\SConstruct", line 3:`
`    EnsureSConsVersion(0, 98, 1)`
`  File "c:\programs\python3\lib\site-packages\scons\SCons\Script\SConscript.py", line 665:`
`    env = self.factory()`
`  File "c:\programs\python3\lib\site-packages\scons\SCons\Script\SConscript.py", line 645:`
`    default_env = SCons.Defaults.DefaultEnvironment()`
`  File "c:\programs\python3\lib\site-packages\scons\SCons\Defaults.py", line 88:`
`    _default_env = SCons.Environment.Environment(*args, **kw)`
`  File "c:\programs\python3\lib\site-packages\scons\SCons\Environment.py", line 982:`
`    apply_tools(self, tools, toolpath)`
`  File "c:\programs\python3\lib\site-packages\scons\SCons\Environment.py", line 107:`
`    env.Tool(tool)`
`  File "c:\programs\python3\lib\site-packages\scons\SCons\Environment.py", line 1789:`
`    tool(self)`
`  File "c:\programs\python3\lib\site-packages\scons\SCons\Tool\__init__.py", line 296:`
`    self.generate(env, *args, **kw)`
`  File "c:\programs\python3\lib\site-packages\scons\SCons\Tool\default.py", line 40:`
`    for t in SCons.Tool.tool_list(env['PLATFORM'], env):`
`  File "c:\programs\python3\lib\site-packages\scons\SCons\Tool\__init__.py", line 1266:`
`    c_compiler = FindTool(c_compilers, env) or c_compilers[0]`
`  File "c:\programs\python3\lib\site-packages\scons\SCons\Tool\__init__.py", line 1169:`
`    if t.exists(env):`
`  File "c:\programs\python3\lib\site-packages\scons\SCons\Tool\msvc.py", line 292:`
`    return msvc_exists(env)`
`  File "c:\programs\python3\lib\site-packages\scons\SCons\Tool\MSCommon\vc.py", line 759:`
`    vcs = cached_get_installed_vcs(env)`
`  File "c:\programs\python3\lib\site-packages\scons\SCons\Tool\MSCommon\vc.py", line 524:`
`    ret = get_installed_vcs(env)`
`  File "c:\programs\python3\lib\site-packages\scons\SCons\Tool\MSCommon\vc.py", line 535:`
`    VC_DIR = find_vc_pdir(ver)`
`  File "c:\programs\python3\lib\site-packages\scons\SCons\Tool\MSCommon\vc.py", line 344:`
`    comps = find_vc_pdir_vswhere(msvc_version)`
`  File "c:\programs\python3\lib\site-packages\scons\SCons\Tool\MSCommon\vc.py", line 306:`
`    vc_pdir = os.path.join(vsdir[0], 'VC')`

When I install Scons version 3.0.3 (`pip install scons=3.0.3`) Godot builds without any problems.

**Comment by akien-mga** [comment] 2019-03-01 22:42
That's weird, I think many other users are able to build with SCons 3.0.4 and MSVC 2017. What VS 2017 version is it (Community, Professional, Enterprise)?

CC @bdbaddog

**Comment by bdbaddog** [comment] 2019-03-02 03:40
Can you run the following and paste the output:
'C:\\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe' 

Also:
set SCONS_MSCOMMON_DEBUG=SCONS_VSLOG.txt
And then run SCons 
and add that file as an attachment?

**Comment by novhack** [comment] 2019-03-02 18:32
Output of the vswhere.exe is:
`Visual Studio Locator version 2.5.2+gebb9f26a3d [query version 1.18.21.37008]`

The only line in the debug file is:
`DEBUG:SCons.Tool.MSCommon.common:trying to find VC 14.1`

If this issue is due to my configuration I'm sorry to waste your time but I have seen the same error in an issue with MSVC 2019 so I thought that it might be connected.

**Comment by bdbaddog** [comment] 2019-03-02 18:46
try vswhere -product "*" -legacy
Also
vswhere -product "*" -prerelease

**Comment by novhack** [comment] 2019-03-03 01:00
`vswhere -products "*" -legacy` and `vswhere -products "*" -prerelease` print the same output as a bare `vswhere` command.

**Comment by bdbaddog** [comment] 2019-03-03 23:00
how about
vswhere -all -prerelease

**Comment by akien-mga** [comment] 2019-03-15 23:06
Testing on Windows 10 Home with freshly installed Python 3.7.2, SCons 3.0.4 and latest VS 2017 Community.

Before I installed MSVC, I got the same backtrace as OP. I checked with @bdbaddog and this has been fixed in SCons *master*, it now properly reports missing compiler:
```
$ scons --version
SCons by Steven Knight et al.:
        script: v3.0.5.alpha.yyyymmdd.387e1f36f19d7a1e5f06cad4d6e87d84893c3ac2, 2019-03-15 22:17:20, by bdbaddog on Williams-MacBook-Pro
        engine: v3.0.5.alpha.yyyymmdd.387e1f36f19d7a1e5f06cad4d6e87d84893c3ac2, 2019-03-15 22:17:20, by bdbaddog on Williams-MacBook-Pro
        engine path: ['c:\\program files\\python37\\lib\\site-packages\\scons\\SCons']
Copyright (c) 2001 - 2019 The SCons Foundation

$ scons
scons: Reading SConscript files ...

scons: warning: No version of Visual Studio compiler found - C/C++ compilers most likely not set correctly
File "C:\Dev\Godot\godot.git\SConstruct", line 3, in <module>

scons: warning: No version of Visual Studio compiler found - C/C++ compilers most likely not set correctly
File "C:\Dev\Godot\godot.git\SConstruct", line 65, in <module>
No valid target platform selected.
The following platforms were detected:
        windows

Please run SCons again with the argument: platform=<string>
scons: done reading SConscript files.
scons: Building targets ...
scons: `.' is up to date.
scons: done building targets.
```

Now back to 3.0.4 and with MSVC properly installed (with C++ components), I get:
```
$ scons --version
SCons by Steven Knight et al.:
        script: v3.0.4.3a41ed6b288cee8d085373ad7fa02894e1903864, 2019-01-20 22:51:36, by bdeegan on kufra
        engine: v3.0.4.3a41ed6b288cee8d085373ad7fa02894e1903864, 2019-01-20 22:51:36, by bdeegan on kufra
        engine path: ['c:\\program files\\python37\\lib\\site-packages\\scons\\SCons']
Copyright (c) 2001 - 2019 The SCons Foundation

$ scons p=windows
scons: Reading SConscript files ...
Configuring for Windows: target=debug, bits=default

scons: *** SDK version '10.0A' is not supported
File "./platform/windows\detect.py", line 146, in setup_msvc_auto
```

I'll gather the relevant debug output asked above in the next comment.

**Comment by akien-mga** [comment] 2019-03-15 23:16
Note: everything on the previous comment and on this one is from running SCons within git-bash.exe.
I'll check afterwards if things are different in the VS command prompt.

```
$ "C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe"
Visual Studio Locator version 2.5.2+gebb9f26a3d [query version 1.18.21.37008]
Copyright (C) Microsoft Corporation. All rights reserved.

instanceId: a61eae66
installDate: 15/03/2019 14.46.13
installationName: VisualStudio/15.9.9+28307.518
installationPath: C:\Program Files (x86)\Microsoft Visual Studio\2017\Community
installationVersion: 15.9.28307.518
productId: Microsoft.VisualStudio.Product.Community
productPath: C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\devenv.exe
isPrerelease: 0
displayName: Visual Studio Community 2017
description: Free, fully-featured IDE for students, open-source and individual developers
channelId: VisualStudio.15.Release
channelUri: https://aka.ms/vs/15/release/channel
enginePath: C:\Program Files (x86)\Microsoft Visual Studio\Installer\resources\app\ServiceHub\Services\Microsoft.VisualStudio.Setup.Service
releaseNotes: https://go.microsoft.com/fwlink/?LinkId=660692#15.9.9
thirdPartyNotices: https://go.microsoft.com/fwlink/?LinkId=660708
updateDate: 2019-03-15T21:46:13.2020168Z
catalog_buildBranch: d15.9
catalog_buildVersion: 15.9.28307.518
catalog_id: VisualStudio/15.9.9+28307.518
catalog_localBuild: build-lab
catalog_manifestName: VisualStudio
catalog_manifestType: installer
catalog_productDisplayVersion: 15.9.9
catalog_productLine: Dev15
catalog_productLineVersion: 2017
catalog_productMilestone: RTW
catalog_productMilestoneIsPreRelease: False
catalog_productName: Visual Studio
catalog_productPatchVersion: 9
catalog_productPreReleaseMilestoneSuffix: 1.0
catalog_productRelease: RTW
catalog_productSemanticVersion: 15.9.9+28307.518
catalog_requiredEngineVersion: 1.18.1049.33485
properties_campaignId:
properties_channelManifestId: VisualStudio.15.Release/15.9.9+28307.518
properties_nickname:
properties_setupEngineFilePath: C:\Program Files (x86)\Microsoft Visual Studio\Installer\vs_installershell.exe
```

SCons logs with `SCONS_MSCOMMON_DEBUG`: [SCONS_VSLOG.txt](https://github.com/godotengine/godot/files/2973190/SCONS_VSLOG.txt)

```
$ "C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe" -products "*" -legacy
Visual Studio Locator version 2.5.2+gebb9f26a3d [query version 1.18.21.37008]
Copyright (C) Microsoft Corporation. All rights reserved.

instanceId: a61eae66
installDate: 15/03/2019 14.46.13
installationName: VisualStudio/15.9.9+28307.518
installationPath: C:\Program Files (x86)\Microsoft Visual Studio\2017\Community
installationVersion: 15.9.28307.518
productId: Microsoft.VisualStudio.Product.Community
productPath: C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\devenv.exe
isPrerelease: 0
displayName: Visual Studio Community 2017
description: Free, fully-featured IDE for students, open-source and individual developers
channelId: VisualStudio.15.Release
channelUri: https://aka.ms/vs/15/release/channel
enginePath: C:\Program Files (x86)\Microsoft Visual Studio\Installer\resources\app\ServiceHub\Services\Microsoft.VisualStudio.Setup.Service
releaseNotes: https://go.microsoft.com/fwlink/?LinkId=660692#15.9.9
thirdPartyNotices: https://go.microsoft.com/fwlink/?LinkId=660708
updateDate: 2019-03-15T21:46:13.2020168Z
catalog_buildBranch: d15.9
catalog_buildVersion: 15.9.28307.518
catalog_id: VisualStudio/15.9.9+28307.518
catalog_localBuild: build-lab
catalog_manifestName: VisualStudio
catalog_manifestType: installer
catalog_productDisplayVersion: 15.9.9
catalog_productLine: Dev15
catalog_productLineVersion: 2017
catalog_productMilestone: RTW
catalog_productMilestoneIsPreRelease: False
catalog_productName: Visual Studio
catalog_productPatchVersion: 9
catalog_productPreReleaseMilestoneSuffix: 1.0
catalog_productRelease: RTW
catalog_productSemanticVersion: 15.9.9+28307.518
catalog_requiredEngineVersion: 1.18.1049.33485
properties_campaignId:
properties_channelManifestId: VisualStudio.15.Release/15.9.9+28307.518
properties_nickname:
properties_setupEngineFilePath: C:\Program Files (x86)\Microsoft Visual Studio\Installer\vs_installershell.exe
```

```
$ "C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe" -products "*" -prerelease
Visual Studio Locator version 2.5.2+gebb9f26a3d [query version 1.18.21.37008]
Copyright (C) Microsoft Corporation. All rights reserved.

instanceId: a61eae66
installDate: 15/03/2019 14.46.13
installationName: VisualStudio/15.9.9+28307.518
installationPath: C:\Program Files (x86)\Microsoft Visual Studio\2017\Community
installationVersion: 15.9.28307.518
productId: Microsoft.VisualStudio.Product.Community
productPath: C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\devenv.exe
isPrerelease: 0
displayName: Visual Studio Community 2017
description: Free, fully-featured IDE for students, open-source and individual developers
channelId: VisualStudio.15.Release
channelUri: https://aka.ms/vs/15/release/channel
enginePath: C:\Program Files (x86)\Microsoft Visual Studio\Installer\resources\app\ServiceHub\Services\Microsoft.VisualStudio.Setup.Service
releaseNotes: https://go.microsoft.com/fwlink/?LinkId=660692#15.9.9
thirdPartyNotices: https://go.microsoft.com/fwlink/?LinkId=660708
updateDate: 2019-03-15T21:46:13.2020168Z
catalog_buildBranch: d15.9
catalog_buildVersion: 15.9.28307.518
catalog_id: VisualStudio/15.9.9+28307.518
catalog_localBuild: build-lab
catalog_manifestName: VisualStudio
catalog_manifestType: installer
catalog_productDisplayVersion: 15.9.9
catalog_productLine: Dev15
catalog_productLineVersion: 2017
catalog_productMilestone: RTW
catalog_productMilestoneIsPreRelease: False
catalog_productName: Visual Studio
catalog_productPatchVersion: 9
catalog_productPreReleaseMilestoneSuffix: 1.0
catalog_productRelease: RTW
catalog_productSemanticVersion: 15.9.9+28307.518
catalog_requiredEngineVersion: 1.18.1049.33485
properties_campaignId:
properties_channelManifestId: VisualStudio.15.Release/15.9.9+28307.518
properties_nickname:
properties_setupEngineFilePath: C:\Program Files (x86)\Microsoft Visual Studio\Installer\vs_installershell.exe
```

```
$ "C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe" -all -prerelease
Visual Studio Locator version 2.5.2+gebb9f26a3d [query version 1.18.21.37008]
Copyright (C) Microsoft Corporation. All rights reserved.

instanceId: a61eae66
installDate: 15/03/2019 14.46.13
installationName: VisualStudio/15.9.9+28307.518
installationPath: C:\Program Files (x86)\Microsoft Visual Studio\2017\Community
installationVersion: 15.9.28307.518
productId: Microsoft.VisualStudio.Product.Community
productPath: C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\devenv.exe
isPrerelease: 0
displayName: Visual Studio Community 2017
description: Free, fully-featured IDE for students, open-source and individual developers
channelId: VisualStudio.15.Release
channelUri: https://aka.ms/vs/15/release/channel
enginePath: C:\Program Files (x86)\Microsoft Visual Studio\Installer\resources\app\ServiceHub\Services\Microsoft.VisualStudio.Setup.Service
releaseNotes: https://go.microsoft.com/fwlink/?LinkId=660692#15.9.9
thirdPartyNotices: https://go.microsoft.com/fwlink/?LinkId=660708
updateDate: 2019-03-15T21:46:13.2020168Z
catalog_buildBranch: d15.9
catalog_buildVersion: 15.9.28307.518
catalog_id: VisualStudio/15.9.9+28307.518
catalog_localBuild: build-lab
catalog_manifestName: VisualStudio
catalog_manifestType: installer
catalog_productDisplayVersion: 15.9.9
catalog_productLine: Dev15
catalog_productLineVersion: 2017
catalog_productMilestone: RTW
catalog_productMilestoneIsPreRelease: False
catalog_productName: Visual Studio
catalog_productPatchVersion: 9
catalog_productPreReleaseMilestoneSuffix: 1.0
catalog_productRelease: RTW
catalog_productSemanticVersion: 15.9.9+28307.518
catalog_requiredEngineVersion: 1.18.1049.33485
properties_campaignId:
properties_channelManifestId: VisualStudio.15.Release/15.9.9+28307.518
properties_nickname:
properties_setupEngineFilePath: C:\Program Files (x86)\Microsoft Visual Studio\Installer\vs_installershell.exe
```

**Comment by akien-mga** [comment] 2019-03-15 23:28
In "x64 Native Tools Command Prompt for VS 2017", `scons p=windows` works out of the box.

As per https://docs.godotengine.org/en/latest/development/compiling/compiling_for_windows.html#compiling, I think it's actually expected that things don't work out of the box in `cmd.exe` or `git-bash.exe`.

**Comment by akien-mga** [comment] 2019-03-15 23:54
In the end the issue I get in `git-bash.exe` is a duplicate of #26485.

The original backtrace from OP is what happened when MSVC is not found at all, so I assume their was a misconfiguration. With MSVC properly installed, I don't get the backtrace with SCons 3.0.4.

That backtrace issue is now fixed in SCons *master*, so closing.

**Closed by akien-mga** 2019-03-15 23:54 UTC
Labels: bug, platform:windows, topic:buildsystem
