### ISSUE TITLE
Virtual keyboard covers TextEdit

### ISSUE THREAD

**Issue by luchitodev** [godotengine/godot#45768] opened 2021-02-06 16:26 UTC
**Godot version:**
Godot 3..2.3 stable and Godot 3.2.4 RC 1

**OS/device including version:**
Android 8.0.0 and MacOS Catalina 10.15.7

**Issue description:**
The keyboard always covers the TextEdit when the text is being entered, the UI elements do not scroll when the keyboard appears, the canvas is always static.

![photo_2021-02-02 21 19 39](https://user-images.githubusercontent.com/19392344/107123865-bd30a700-6865-11eb-8202-0fff7a66fc00.jpeg)

**Comment by Calinou** [comment] 2021-02-06 17:49
See also https://github.com/godotengine/godot/issues/37190.

**Comment by luchitodev** [comment] 2021-02-06 21:33
Thanks for answer @Calinou but is not the same, my problem is when you focus the TextEdit, keyboard cover it, inputs not are moving top the keyboard... the problems is I can't see what I am typing...

**Comment by Calinou** [comment] 2021-02-06 22:26
> Thanks for answer @Calinou but is not the same, my problem is when you focus the TextEdit, keyboard cover it, inputs not are moving top the keyboard... the problems is I can't see what I am typing...

It's the exact opposite problem, which is why I said it's related :slightly_smiling_face:

**Comment by m4gr3d** [comment] 2021-02-17 20:31
@luchitodev This is a duplicate of #41388.

**Closed by m4gr3d** 2021-02-17 20:31 UTC
Labels: bug, platform:android, topic:gui, topic:porting
