### ISSUE TITLE
[4.3 beta1 mono],  Android remote debug shows black sreen after splash screen if any C# script is attached to node.

### ISSUE THREAD

**Issue by Vielfras** [godotengine/godot#92626] opened 2024-06-01 07:44 UTC
### Tested versions

- Reproducible: 4.3 beta 1 .net

### System information

Ubuntu 22.04.4 LTS, Gnome v42.9, X11, 64bit, 11th Gen Intel® Core™ i3-1115G4 @ 3.00GHz × 4, Mesa Intel® UHD Graphics (TGL GT2) 

**Dotnet versions installed:**
`dotnet --list-sdks`
6.0.128 [/usr/lib/dotnet/sdk]
8.0.105 [/usr/lib/dotnet/sdk]

### Issue description

On android Xiaomi Redmi Note 11 Pro 5g,  remote debug build and installation are completed successfuly but game displays  black screen after the Godot splash screen(default godot logo splash screen).

- Launcher Icon is correctly added and displays correct game art.
- I tried deleting app data/uninstalling manually from mobile with no change.
- Game runs properly through editor on laptop.
- No warrning or errors are raised.

<br>

**Phone information:**
- Name: Xiaomi Redmi Note 11 Pro 5g
- OS version: 1.0.3.0.TKCMIXM
- Android version: 13 TKQ1.221114.001
- CPU: Snapdragon 695, Octa-core Max 2.2GHz 

**Workes correctly on:**
Godot Engine v4.2.2.stable.mono.official.15073afe3 
Vulkan API 1.3.255 - Forward Mobile - Using Vulkan Device #0: Intel - Intel(R) UHD Graphics (TGL GT2)
 
**Problem version:**
Godot Engine v4.3.beta1.official.a4f2ea91a
Vulkan 1.3.255 - Forward Mobile - Using Device #0: Intel - Intel(R) UHD Graphics (TGL GT2)
- Issue persistes on Forward+ and Compatibility options as well.

**<project_name>.csproj**:
```
<Project Sdk="Godot.NET.Sdk/4.3.0-beta.1">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <TargetFramework Condition=" '$(GodotTargetPlatform)' == 'android' ">net7.0</TargetFramework>
    <TargetFramework Condition=" '$(GodotTargetPlatform)' == 'ios' ">net8.0</TargetFramework>
    <EnableDynamicLoading>true</EnableDynamicLoading>
  </PropertyGroup>
</Project>
```

### Steps to reproduce
1. Create new C# project on 4.3 beta 1 mono.
2. Create Node2D main scene.
3. Add Node2D.cs script to Node2D.
4. Install Android build templates.
5. Add Android export option.
6. Remote debug
7. Approve install on phone.
8. Splash screen followed by black screen.

If Node2D.cs script is removed from Node2D, black screen dissapears and the grey default background is displayed after the splash screen.

### Minimal reproduction project (MRP)

N/A

**Comment by 0xnicholasc** [comment] 2024-06-01 22:09
I am experiencing the same issue, regardless of renderer setting, and on a Pixel 8, as well as Samsung  Tab S8+. The project worked fine on 4.2.2

**Comment by raulsntos** [comment] 2024-06-02 15:51
Duplicate of https://github.com/godotengine/godot/issues/92630

**Closed by raulsntos** 2024-06-02 15:51 UTC
Labels: platform:android, needs testing, topic:export
