### ISSUE TITLE
godot crashes when moving an vector2 in an exported array

### ISSUE THREAD

**Issue by dryluggage** [godotengine/godot#57745] opened 2022-02-07 09:30 UTC
### Godot version

3.4.2

### System information

Arch Linux

### Issue description

When you have an exported array  with vector2  in them and you drag one around fast beyond the guis limits it outputs "invalid new child position" with an index and then is unresponsive and crashes

### Steps to reproduce

create a node2d attach a script make an export variable (Array,Vector2) then expand it the inspektor and a few vectors then you drag one of the vectors up down fast and it crashes

**Comment by object71** [comment] 2022-02-08 06:28
On master this doesn't crash but prints out an error instead: ```core\variant\variant.cpp:3328 - Invalid method 'remove' for type 'Array'.``` which is still not the core reason though.

**Comment by object71** [comment] 2022-02-08 12:46
> 

After further testing - fixing the remove method issue (because "remove" is actually called "remove_at") I managed to reproduce the crash on godot 4

**Comment by object71** [comment] 2022-02-09 19:55
Seems that it is caused by passing with the held mouse through the size button at the top of the array while dragging the vector. That makes the array bigger and it crashes when it reaches the second page (because reordering suddenly has no elements to compare with).

**Comment by KoBeWi** [comment] 2022-04-28 22:56
Can't reproduce in 4.0 alpha7, but maybe I'm testing wrongly. Can someone check?

**Comment by salamandars** [comment] 2022-06-23 07:44
Duplicate of #61282

**Closed** 2022-06-23 07:59 UTC
Labels: bug, topic:core, topic:editor
