### ISSUE TITLE
Game window placement centered setting makes window jump from top left to center on Windows

### ISSUE THREAD

**Issue by AlexHolly** [godotengine/godot#2545] opened 2015-09-27 13:50 UTC
My settings:Game Windows Placement -> Rect -> Centered

Game Window(start in godot engine): The game window first starts on top left then jumps to the center location. Is it possible to hide the window and show it after it is centered?
Exported Windows game: location is always(not centering) top left. 

Project selection(godot start): Is showing on top left. How can i set it to center?

Update: Windows 7 64-bit

**Comment by okamstudio** [comment] 2015-09-27 14:14
operating system in question? :)

On Sun, Sep 27, 2015 at 10:50 AM, AlexHolly <notifications@github.com>
wrote:

> My settings:Game Windows Placement -> Rect -> Centered
>
> Game Window: The game window first starts on to left then jumps to the
> center location. Is it possible to hide the window and show it after it is
> centered?
>
> Project selection(godot start): Is showing on top left. How can i set it
> to center?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/okamstudio/godot/issues/2545>.
>



-- 

*OkamStudio*

**Comment by reegankens** [comment] 2016-12-05 03:45
Yes I have problem too. game window show top right. I use osx yosemite and use godot 2.1

**Comment by bojidar-bg** [comment] 2016-12-05 10:08
I have the feeling this was fixed in master or at least made configurable in project settings.

**Comment by reegankens** [comment] 2016-12-05 11:55
How to made configurable in project settings?

**Comment by reegankens** [comment] 2016-12-06 08:40
I  try in os x sierra it's no problem? But when i want try using godot 2.1.1 its cannot, the app not support in yosemite.

**Comment by akien-mga** [comment] 2017-05-24 09:21
> Game Window(start in godot engine): The game window first starts on top left then jumps to the center location. Is it possible to hide the window and show it after it is centered?

Edited title to keep that part. Is it still valid?

> Exported Windows game: location is always(not centering) top left.
Project selection(godot start): Is showing on top left. How can i set it to center?

Duplicate of #4430.

**Comment by akien-mga** [comment] 2017-06-27 18:14
Superseded by #9418.

**Closed by akien-mga** 2017-06-27 18:14 UTC
Labels: bug, platform:windows, topic:porting
