### ISSUE TITLE
GLES3 freezes with Mesa 18.3+ [upstream]

### ISSUE THREAD

**Issue by supagu** [godotengine/godot#24783] opened 2019-01-05 06:28 UTC
Godot has just started locking up at seemingly random recently.

I had it working fine, then did some OS updates (I'm running Manjaro Linux) and now it locks every now and then and gives no indication of what is going on.

I have the latest master branch (as of today 5/01/2018 - Git head: 5e6c6f3bb)

I run through a debugger and broke when the lock up was occurring and the problematic line is this:
`glLinkProgram(v.id);`

in shader_gles3.cpp line 475. 
this line blocks and causes godot to lock up.

this does not occur if i change to GLES2 rendering.

**Comment by akien-mga** [comment] 2019-01-05 10:30
Duplicate of #24362 and #24340, someone should report it to Arch maintainers.

**Comment by supagu** [comment] 2019-01-05 10:47
I've raised the issue on the Manjaro bug tracker and also on the Mesa bug tracker.
https://bugs.freedesktop.org/show_bug.cgi?id=109229

**Comment by akien-mga** [comment] 2019-01-05 13:18
Thanks! Relevant info to provide to Arch/Manjaro dev, as they might be hit by the same issue that Fedora and Debian had with a recent GCC + Mesa update: https://github.com/godotengine/godot/issues/23423#issuecomment-435877238

**Comment by smt923** [comment] 2019-01-11 03:04
Is there any chance this might be caused by something else? I _believe_ arch's gcc and mesa are both patched and built after gcc it's self got an update that fixed the mesa compile issue, yet I'm still getting this issue on arch in both 3.1 beta and 3.0.6

**Comment by supagu** [comment] 2019-01-11 05:10
Zip file attached contining build scripts
and README  on how to repo the issue.

[build.zip](https://github.com/godotengine/godot/files/2748140/build.zip)

contents of README.md:


 
run ./godot_build.sh this will checkout and build godot

either edit shader_gles3.cpp:475 to look like this:

print_line("===== CALLING glLinkProgram");
glLinkProgram(v.id);
print_line("===== FIN glLinkProgram");

or use the file I have supplied.


run ./godot_build.sh to build with these changes

go into Build/godot/bin
run godot.x11.tools.64 in a terminal


you can get sample projects from here:
https://github.com/godotengine/godot-demo-projects

when checked out get godot 

navigate into godot-demo-projects/3d/material_testers/ 

run exe we just built using gdb:
gdb --args /home/fabian/Projects/build/Build/godot/bin/godot.x11.tools.64 --editor

watch the console log.

**Comment by akien-mga** [comment] 2019-01-11 09:23
Reopening for now since it seems not to be the same as the GCC bug that broke Mesa on Fedora/Debian a month ago. It's still a third-party issue, but it's probably worth having a bug report open for affected users to refer to.

**Comment by johannesgunnar** [comment] 2019-01-25 13:07
Can confirm that I seem to be running into this same problem on Ubuntu 18.04 with Mesa 18.3.1 (Padoka Stable PPA). Purging the PPA and downgrading to Mesa 18.0.5 seems to fix the issue.

**Comment by smt923** [comment] 2019-01-29 01:53
[Looks like a nice fix is on it's way to mesa](https://bugs.freedesktop.org/show_bug.cgi?id=109229#c9), compiling mesa seems a bit much for my PC but I'll be able to test whenever an updated mesa hits arch's testing

**Comment by G392** [comment] 2019-01-29 02:52
I've just compiled and installed mesa from source and the problem is fixed here!

**Comment by turtlewit** [comment] 2019-01-29 08:47
I can also confirm that it is fixed on mesa-git.

**Comment by smt923** [comment] 2019-01-29 21:20
Seems like a new build was pushed to the unofficial mesa-git repo and I can confirm it's working good here too :tada:  (` Mesa 19.0.0-devel (git-69edc972fc)`)

**Comment by akien-mga** [comment] 2019-01-30 10:09
The upstream contributor who fixed it mentioned that it should be included in the next 18.3.x release (18.3.3) as well as 19.0.0.

Keeping open for now for others would might experience the issue, we can close it once 18.3.3 is released.

**Comment by akien-mga** [comment] 2019-02-01 07:15
It's now fixed in 18.3.3, good job guys!
https://mesa3d.org/relnotes/18.3.3.html

**Closed by akien-mga** 2019-02-01 07:15 UTC
Labels: bug, platform:linuxbsd, topic:thirdparty
