### ISSUE TITLE
Headless Android export failing with error code 20

### ISSUE THREAD

**Issue by kjav** [godotengine/godot#41721] opened 2020-09-02 19:48 UTC
**Godot version:**
3.2.2.stable.official

**OS/device including version:**
Using the Linux headless 3.2.2.stable.official version to export to GLES2 Android

**Issue description:**
I run an export with the command "Godot_v3.2.2-stable_linux_headless.64 --path <path_to_repo> --export Android <path_to_apk>. After a few seconds, I recieve the error:
`ERROR: _fs_changed: Project export failed with error code 20 for preset 'Android'`

I can't find anywhere in the documentation what this error code means. Another git issue suggests installing the build template manually, but I have done this - the templates are extracted in ~/.local/share/godot/templates/3.2.2.stable, and the android/build directory in the repository has been created by unzipping the 'android_source.zip' file into it. Does anyone know what error code 20 referrs to, and do you have any ideas of what I should do to resolve it?

**Comment by Calinou** [comment] 2020-09-02 20:43
Duplicate of https://github.com/godotengine/godot/issues/29385.

**Closed by Calinou** 2020-09-02 20:43 UTC
