### ISSUE TITLE
GDScript 2.0: using `add_autoload_singleton` in plugin let the editor in a invalid changed state

### ISSUE THREAD

**Issue by MikeSchulze** [godotengine/godot#68285] opened 2022-11-05 11:15 UTC
### Godot version

v4.0.beta4.official [e6751549c]

### System information

Windows 10

### Issue description

I use `add_autoload_singleton` in my plugin to register global events.
After activating the plugin the Editor shows a (*) symbol on the window bar.
![image](https://user-images.githubusercontent.com/347037/200116829-cbad8e81-c056-49d3-94bb-74f223650770.png)

When now try to close the editor a dialog is shown to save modified resources, but i have no scenes/scripts changed:
![image](https://user-images.githubusercontent.com/347037/200116858-98a084e7-c7e4-4b83-a1b0-38dcf6b3d03d.png)

When pressed the  `saven and close` button, the editor is not closed and shows an error in the console.
`editor/editor_data.cpp:598 - Index p_idx = -2 is out of bounds (edited_scene.size() = 1).`

When now deactivate the plugin the next error is shown.
` Trying to remove non-existent autoload.`

### Steps to reproduce

Use the attached project.

- activate the plugin
- check the windows bar
- try to close the editor or switch to project overview

### Minimal reproduction project

[AutoLoadTest.zip](https://github.com/godotengine/godot/files/9943632/AutoLoadTest.zip)

**Comment by RedMser** [comment] 2022-11-06 15:57
Interesting how `ProjectSettings.save()` does not seem to fix this error. I would've assumed it would remove the unsaved indicator.

**Comment by MikeSchulze** [comment] 2022-11-29 10:20
Hi, any update here? This bug blocks me from saving my project

**Comment by dc1248** [comment] 2023-01-25 20:16
I think the problem is that add/remove_autoload_singleton create undo_redo actions assuming the user is toggling them in Project Settings GUI. The script methods were recently added for convenience, and the C++ methods still need modification to skip undo_redo when called this way.

Source links:
https://github.com/godotengine/godot/blob/eaf306e0b15e4283883f06bf903b05711a4dbfe8/editor/editor_plugin.cpp#L417
https://github.com/godotengine/godot/blob/b5f3ac522e16b2d899604e2d0788a86c66476e78/editor/editor_autoload_settings.cpp#L763

**Comment by neth392** [comment] 2024-09-14 22:46
There is a workaround for this issue. Instead of adding the autoload in `_enter_tree()`, add it in `_enable_plugin()`. Then disable it in `_disable_plugin()` instead of `_exit_tree()`.

The autoload will stay there & never be removed as long as the plugin isn't disabled. It will not leave the project in an "unsaved" state.

**Comment by dc1248** [comment] 2024-09-17 12:38
Thanks @neth392, I will try that out for a while.

IF that's the solution, there's a documentation issue.
- Indeed there is an open issue suggesting this change: https://github.com/godotengine/godot-docs/issues/9571 (and various people weighing in for and against it)
- The primary documentation currently says to use _enter_tree(): https://docs.godotengine.org/en/stable/tutorials/plugins/editor/making_plugins.html#registering-autoloads-singletons-in-plugins
- Most plugins seem to use _enter_tree() or require you to manually add/remove the autoload due to this problem.
- There are many related issues and proposals, mostly piecemeal "fixes". Seems like there's a major need for a comprehensive solution.

@Hilderin you've done a deep dive into this aspect of Godot... got any ideas?

**Comment by Hilderin** [comment] 2024-09-20 00:04
Indeed, the best practice should be to use `_enable_plugin` and `_disable_plugin` to add and remove autoloads.

The problem with `_enter_tree` and `_exit_tree` is that they are executed everytime the plugin is added or removed in the scene and that includes when the editor is starting and closing. That's why your project is marked modified when you open the project.

The methods  `_enable_plugin` and `_disable_plugin` are executed only once when the plugin is enabled or disabled by the user.

The methods `_enter_tree` and `_exit_tree` should be used for everything that needs to be executed on every editor startup/closing, for example adding buttons, docks, add the new types, etc...

Note: the error `Index p_idx = -2 is out of bounds` was an error in the scene saving that was fixed since.

I made a PR in the documentation to make to appropriate modifications: https://github.com/godotengine/godot-docs/pull/9979

**Closed** 2024-10-05 11:50 UTC
Labels: topic:plugin
