### ISSUE TITLE
Bad handling of input in Slider when it come from a joystick

### ISSUE THREAD

**Issue by Lendemor** [godotengine/godot#33307] opened 2019-11-03 20:34 UTC
**Godot version:**
3.1.1

**OS/device including version:**
Windows 10 Pro
Version 1607

Reported to me with Xbox One Pdp Controller.
Tested with Xbox One Wireless Controller.

**Issue description:**
When using joystick to change value of a slider, the value of VSlider/HSlider always increase/decrease independently of action used.

The script MonitorInput.gd show that the mapping between the joystickEvent and the action was done correctly, but somehow the result on the slider is wrong. However, if the same action come from D-Pad, it works as intended.

**Steps to reproduce:**
1. Launch one of the two scene (either TestVSlider or TestHSlider) with F6.
2. Change value with D-Pad
3. Change value with joystick
4. New value is wrong. 

**Minimal reproduction project:**
[test_godotslider.zip](https://github.com/godotengine/godot/files/3802081/test_godotslider.zip)

**Comment by KoBeWi** [comment] 2019-11-03 20:42
Duplicate of #30402

**Closed by KoBeWi** 2019-11-03 20:42 UTC
