### ISSUE TITLE
Godot 4.x Tilemap/Tileset conversion creates thousands of tile alternatives, making it unusable

### ISSUE THREAD

**Issue by Poobslag** [godotengine/godot#77769] opened 2023-06-02 12:46 UTC
### Godot version

4.0.3.stable

### System information

Windows 10 - Godot 4.0.3

### Issue description

When converting a project from Godot 3.x to Godot 4.x, Godot makes two grievous assumptions about TileMaps/TileSets

1. The cell size of a tile set is 16x16
2. Your project requires eight alternative tiles for every tile in your tileset

The result of these two assumptions is that a single 2000x2000 texture will create 125,000 tile alternatives, resulting in a giant `.tscn` file several megabytes large which Godot struggles to save, load or work with. It crunches for several minutes trying to navigate the scene tree or often crashes. Because the Godot editor cannot even do things like change the tile dimensions without freezing/crashing, it is impossible to fix the error.

Even assuming it was possible to fix the editor in the editor, deleting 125,000 tile alternatives one at a time will take a human being about 200 hours, and there is no way to accelerate or automate the task through the editor -- users must write their own scripts to do so.

### Steps to reproduce

1. Create a Godot 3.x project with a large TileMap texture (1000x1000 or larger)
2. Import the project into Godot 4.x
3. Open the `.tscn` file containing the TileMap, and examine the tileset. Thousands and thousands of alternative tiles have been created.
4. Save the `.tscn` file. The resulting file is several megabytes large.

### Minimal reproduction project

[big-tilemap-godot3.zip](https://github.com/godotengine/godot/files/11635356/big-tilemap-godot3.zip) (Godot 3 version of the project)

[big-tilemap-godot4.zip](https://github.com/godotengine/godot/files/11635357/big-tilemap-godot4.zip) (Godot 4 version of the project after the auto-conversion project)

**Comment by AThousandShips** [comment] 2023-06-02 12:51
* Duplicate of #71188

**Comment by Zireael07** [comment] 2023-06-02 12:52
This one has a MRP while the other one doesn't, though.

**Comment by AThousandShips** [comment] 2023-06-02 12:55
Sure, but that should just be added as a comment on the other one as it has a lot of relevant discussion

**Comment by Calinou** [comment] 2023-06-02 13:32
Thanks for the report and MRPs! Consolidating in #71188.

**Closed by Calinou** 2023-06-02 13:32 UTC

**Comment by Poobslag** [comment] 2023-06-02 15:22
Thank you -- I did see that issue, but it seemed like it might be distinct

> it has recreated the same 400 tiles I previously had

In the other bug, Godot successfully migrated the tiles (with the correct dimensions!) but created hundreds of entries in the "Tiles" tab.

![image](https://github.com/godotengine/godot/assets/5902413/e7446f58-a4d6-405c-bbe8-d807e5b2be30)

![image](https://github.com/godotengine/godot/assets/5902413/17b2868e-cd47-4c37-9694-e8e15b0f2022)

To me it looks like that bug has been fixed, as you can now see there is only a single "Tiles" entry. But there is a different bug where the dimensions are incorrect, and there are tons of tiles and tons of tile alternatives.

It you want to group them that is fine! But the behavior seemed different enough that I wouldn't have been surprised if the other bug was technically fixed, and if this was a new different bug.
