### ISSUE TITLE
Recently opened scripts temperature hard to read and other theme issues

### ISSUE THREAD

**Issue by kerskuchen** [godotengine/godot#11244] opened 2017-09-13 18:39 UTC
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**

Windows 10 64Bit, current Godot 3.0 master

**Issue description:**
The recently opened scripts are now hard to read
![screenshot 2017-09-13 18 09 34](https://user-images.githubusercontent.com/2393859/30394302-ff4e444c-98c2-11e7-8d82-dad6fe737d4a.png)

Also the console gets spammed with errors (even when opening a fresh new project)
![screenshot 2017-09-13 18 12 19](https://user-images.githubusercontent.com/2393859/30394305-01f2c60a-98c3-11e7-9e02-c93aada1f448.png)

Though both problems have something to do with editor appearence (theme) I don't know if they are really related though.

**Comment by Noshyaar** [comment] 2017-09-13 18:41
Duplicate of #11059 #11095 #11174

**Closed** 2017-09-13 18:42 UTC
Labels: archived

**Comment by kerskuchen** [comment] 2017-09-13 18:44
I should include closed issues when I search for duplicates the next time before I open a new issue sorry! :D

**Comment by Noshyaar** [comment] 2017-09-13 18:46
No worries! :D
