### ISSUE TITLE
LightmapGI: Freeze when trying to bake with custom UV2

### ISSUE THREAD

**Issue by WickedInsignia** [godotengine/godot#63423] opened 2022-07-25 04:08 UTC
### Godot version

4.0 Alpha 12

### System information

Windows 10, GTX1080, i7 6700

### Issue description

Godot will freeze on the following screen while trying to bake a mesh with a pre-unwrapped custom UV2 layout (in this case, 3 meshes in an inherited scene).
Objects were imported as "static", not "static lightmaps" since that setting will overwrite any custom lightmaps.
This works fine in 3.4 with import set to "Light baking: enable".

![DetermingAtlasSizeFreeze](https://user-images.githubusercontent.com/70243134/180697216-95e82cf2-8cfa-444b-af8c-50d9f356c5b4.JPG)

### Steps to reproduce

- Open MRP
- Open Mesh.tscn and check that a pre-unwrapped custom UV2 is used (the map should have minimal padding)
- Open Scene.tscn
- Attempt to bake the scene

### Minimal reproduction project

[CustomLightmapBug.zip](https://github.com/godotengine/godot/files/9177937/CustomLightmapBug.zip)

**Comment by MmAaXx500** [comment] 2022-07-25 13:20
I can confirm this on v4.0.alpha.custom_build [20d7171e8] with the MRP and with my own meshes. Attached a log for the MRP:
[output.log](https://github.com/godotengine/godot/files/9181480/output.log) (it says something about Intel, but the editor is running on an RTX 2080)

**Comment by DarioSamo** [comment] 2023-09-18 17:11
I'm unable to reproduce this on latest commit (e3e2528ba7f6e85ac167d687dd6312b35f558591). The scene is also not lit for some reason despite the directional light being enabled.

![image](https://github.com/godotengine/godot/assets/538504/c03dd10b-21a4-45ff-8d28-964cf4b6e4a2)

Are the normals of the scene broken or something?

![image](https://github.com/godotengine/godot/assets/538504/5e936d4b-fa5c-4bff-b662-6c72039fa3c7)

**Comment by Calinou** [comment] 2024-07-13 02:11
> The scene is also not lit for some reason despite the directional light being enabled. It is able to bake however.

Baking works fine on my end, although there's some visible UV bleeding on the beveled boxes once lightmaps are baked (likely expected given the custom UV2 layout).

**Comment by WickedInsignia** [comment] 2024-07-13 13:47
4.0 to 4.3 project conversion creates some oddities so I rebuilt the project with the same GLB mesh file.
When I change the GLB's Light Baking from Static to Static Lightmaps in this project it freezes at Determining Optimal Atlas Size.
I also have to reload the main scene to see the changes in the lightmap UV. Hitting Bake after this with Static Lightmaps guarantees a stall for me.
If I change from Static Lightmaps to Static and don't reload the main scene, it still stalls.

[customlightmapbugv2.zip](https://github.com/user-attachments/files/16202333/customlightmapbugv2.zip)
To recreate from here simply change Static to Static Lightmaps, reload the main scene and bake lightmaps.

**Comment by WickedInsignia** [comment] 2024-07-14 00:09
Can confirm this still happens on [97b8ad1](https://github.com/godotengine/godot/commit/97b8ad1af0f2b4a216f6f1263bef4fbc69e56c7b).
Just to be sure I rebuilt a similar mesh in Blender and strangely this one doesn't suffer the same issue. Something about the old mesh seems to be the problem. It was taken directly out of the project directory from the first MRP, so maybe had something to do with that.

Updated project file with new mesh:
[customlightmapbugv2.zip](https://github.com/user-attachments/files/16205724/customlightmapbugv2.zip)

**Comment by BlueCube3310** [comment] 2024-07-14 08:59
The freezing is now caused by the atlas not being padded enough after the denoiser range PR, which will be fixed by #94236. Since this issue was reported long before that was a thing though, #94237 ensures that the process will now fail if an image cannot be blit into the atlas.

**Closed** 2024-07-18 08:46 UTC
Labels: bug, topic:rendering, confirmed, topic:3d
