### ISSUE TITLE
TileMap's "Center" tile origin doesn't work as it should

### ISSUE THREAD

**Issue by oreismatheus** [godotengine/godot#13062] opened 2017-11-19 23:25 UTC
![image](https://user-images.githubusercontent.com/31781227/32996866-c0f8aa52-cd6f-11e7-9b09-c7bbbdde7640.png)

![image](https://user-images.githubusercontent.com/31781227/32996870-c7886efc-cd6f-11e7-9033-3fb83eedfcf9.png)

![image](https://user-images.githubusercontent.com/31781227/32996873-cbfc9026-cd6f-11e7-95ae-558b1c33484f.png)

As seen in the screenshots, the "Center" tile origin works just like "Top Left". In this example, the sprite's Y-origin is centered (works properly for top and bottom).

**Comment by akien-mga** [comment] 2017-11-20 12:44
Duplicate of #3209.

**Closed by akien-mga** 2017-11-20 12:44 UTC

**Comment by hoelzl** [comment] 2017-11-21 05:16
Hi @oreismatheus! I'd like to fix some issues with the tile editor, but to do so I need to understand what the desired behavior is. I assume from the screenshots that, in your case, tile origin "Center" should move the green tile exactly on top of the red rhombus. Is that correct?

**Comment by oreismatheus** [comment] 2017-11-21 13:30
Hello @hoelzl! Well, from my understanding, the center-aligned tile should look like this: 

![image](https://user-images.githubusercontent.com/31781227/33073378-e0e5fed8-cea9-11e7-9cbe-9448d4ec7e57.png)

The tile rendering is a bit confusing, to be honest. Will try to explain with screenshots:

![image](https://user-images.githubusercontent.com/31781227/33074677-2f69c18a-ceae-11e7-9046-fe7cd500ddec.png)

![image](https://user-images.githubusercontent.com/31781227/33074712-58a844ea-ceae-11e7-8cd4-cd8e349b5faf.png)

![image](https://user-images.githubusercontent.com/31781227/33074778-81bf3abe-ceae-11e7-8142-bcc8dd703d9a.png)

---

A bit unrelated to the issue itself but to me, the tile placement should be changed a bit. In this gif, the sprite's origin is not centered and is set to (0, 0):

https://i.imgur.com/gqNWhI6.gif

 In the top-left and bottom-left, the origin is (0, 0), as seen. Although, setting a tile sprite to centered doesn't change anything and it's rather confusing, especially when it comes to isometric tilesets, in which the Y position matters for Y-sorting.

To me, in this case, the "Center" alignment with a not centered sprite origin at (0, 0) should draw the sprite there: 

![image](https://user-images.githubusercontent.com/31781227/33074254-a72bb61c-ceac-11e7-95d7-aabb930b4231.png)

Ofc, for this to work well, the following alignments should be added: Top, top-right, left, right, bottom & bottom-right, and drawing the tiles exactly where they should be rendered based on their origin:

![image](https://user-images.githubusercontent.com/31781227/33074391-2a81184a-cead-11e7-894f-4954319e44ce.png)

And the same for iso tiles:

![image](https://user-images.githubusercontent.com/31781227/33074463-6e5a22f0-cead-11e7-8c34-3db418e0dd9e.png)

That'd make things way less confusing and, to me, would be the best way for the tilemaps to work, but maybe this is the case of opening another issue.

**Comment by hoelzl** [comment] 2017-11-21 16:15
Thanks for the detailed reply.
I've posted a proposal to  #3209 this morning, that I think is not too far away from what you would like: I thought about having a Tile Offset that would describe the position of the sprite's origin relative to the upper left corner of the tile. 
If I understand correctly, for a, say 32x32 grid, your Top-Left would be (0,0), Top would be (16,0), Top-Right would be (32,0), Left would be (0,16), Center (16,16), etc.
I'll try to implement something along these lines in the next few days, if I find the time, and get back to you.

**Comment by hoelzl** [comment] 2017-11-23 18:51
Hey @oreismatheus ! I've created PR #13062 with a proposed fix to the issue. I'm not sure whether it solves your immediate problem, since it moves the center to the position you have labeled "Center", and from what I understand you might need the "Left" position.

It would be great if you could try whether it works as you would expect. If you build from Git, you can just cherry pick the commit, otherwise I might be able to create a build with the patch for you (for Windows or Linux at least).

**Comment by oreismatheus** [comment] 2017-11-23 19:17
I've never compiled the engine, if you could it for me, that'd be great (OS is Win10 64bit btw). (: @hoelzl

**Comment by hoelzl** [comment] 2017-11-23 19:37
I've put my current build with PR #13216 at https://www.dropbox.com/s/2phcmimvljx4vwu/Godot3-master-with-pr13216.zip?dl=0 and the project I've used to test the behavior at https://www.dropbox.com/s/yoilp2x6b68atym/TilemapTest2.zip?dl=0

**Comment by oreismatheus** [comment] 2017-11-24 02:51
It's working as it's expected to, which is awesome. Although, the "Centered" sprite property still does not work: 

![image](https://user-images.githubusercontent.com/31781227/33193158-e04a6b8e-d0ad-11e7-8743-016eb8a52f5a.png)

To get a centered origin, I had to set the origin to (-64, -64) since the sprite's size is 128x128. That way, it works perfectly:

https://i.imgur.com/IBMCHq1.gif

If I set it to (0, 0) and Centered (which should be exactly the same thing):

![image](https://user-images.githubusercontent.com/31781227/33193331-fafa7bc6-d0ae-11e7-81ad-6e3d8d75b682.png)

That's what happens:

https://i.imgur.com/szgdYUL.gif

Which means the tile renderer doesn't mind that property (by drawing it as if the offset was (0, 0) from the top-left corner, and not from the center). Fixing this is not what I call indispensable because one can work around it by finding the center offset from the top-left corner, but doing so would make it work flawlessly. 

So that, along with the other offset options (bottom-right, right, top-right, top, bottom, etc...) would make the tiles placement make perfect sense to users. By the way, great work so far, @hoelzl, congratz! Thanks for listening to my suggestion and working on it, will certainly help me a lot, and I'm sure it will make other people's life easier when working with tilemaps as well! 👍

**Comment by hoelzl** [comment] 2017-11-24 08:08
Thanks for the feedback. Glad to hear that what I've done so far works for you. 

I think I have a pretty good idea how to fix the remaining issues now that I've become a bit more familiar with the 2D editor, but it'll probably take me a little while until I can work on it.
