### ISSUE TITLE
OmniLights and SpotLights disappearing from a surface after node visibility is changed (3.2.4 RC2)

### ISSUE THREAD

**Issue by antourenein** [godotengine/godot#45967] opened 2021-02-13 16:37 UTC
**Godot version:**
Godot 3.2.4 RC2 Standard Build

**OS/device including version:**
Windows 10 1909, NVIDIA GTX850M

**Issue description:**
While a OmniLight or SpotLight is emitting on a static surface, if the visibility of the surface is changed (like turned off and then on immediately), the lights on it disappear. (If the surface is moved, the lights come back.)

This causes a problem with the LOD addon by @Calinou, which I use in one of my projects, since it switches mesh visibility according to camera distance, and then when lod0 is loaded again, the static lights on a static mesh disappear.

This did not happen in RC1, so I assume it has something to do with the new feature of optimized transform propagation for hidden 3D objects?

**Steps to reproduce:**
Add a MeshInstance, choose any mesh for it, add a SpotLight or OmniLight that shines on the mesh, turn MeshInstance visibility off and then on again and the lights on it will disappear. It happens both in the editor and ingame.

**Comment by Calinou** [comment] 2021-02-13 16:42
cc @lawn

**Comment by lawnjelly** [comment] 2021-02-13 18:04
I can reproduce it, it actually seems to be the BVH though rather than the optimized transforms. Might be this PR #45576. Will look into it! :+1:

**Comment by akien-mga** [comment] 2021-02-14 10:02
Fixed by #45970.

**Closed by akien-mga** 2021-02-14 10:02 UTC
Labels: bug, regression, topic:rendering
