### ISSUE TITLE
Wrong name in inspector for navigation2d

### ISSUE THREAD

**Issue by ZX-WT** [godotengine/godot#7044] opened 2016-11-05 16:09 UTC
**Operating system or device - Godot version:**Linux mint 17.2, 2.1.1_rc2

**Issue description** (what happened, and what was expected):
The name in the inspector is not same as the node type
It is node2d instead of navigation2d

**Steps to reproduce:**
create navigation2d node in the editor

Screenshot
![2016-11-06 00 04 30](https://cloud.githubusercontent.com/assets/10883749/20031593/00278a3a-a3b5-11e6-95eb-54dfee7b67f2.png)

**Comment by bojidar-bg** [comment] 2016-11-05 16:12
This is not a bug. This happens because the `Navigation2D` node has no properties exposed into the inspector.

If it was still displayed, there would have been an empty category, which looks ugly.

Closing as non-issue.

**Closed by bojidar-bg** 2016-11-05 16:12 UTC
