### ISSUE TITLE
Renaming Input Actions

### ISSUE THREAD

**Issue by Tegu** [godotengine/godot#1010] opened 2014-12-20 15:55 UTC
This is a quite minor issue, but it could be useful to be able to rename the Input Actions in the GUI. With the current GUI you have to remove the action, create a new one with the new name, and assign all the keys again. As a workaround it is probably quicker and easier to rename them in the engine.cfg file.

**Comment by akien-mga** [comment] 2015-11-05 09:16
Duplicate of #517.

**Closed by akien-mga** 2015-11-05 09:16 UTC
Labels: archived
