### ISSUE TITLE
Relative paths are not working in windows version

### ISSUE THREAD

**Issue by steelxtreme** [godotengine/godot#3706] opened 2016-02-13 22:31 UTC
Relative paths failed to load due to missing dependencies.
I have tested this by using differents node that load textures.

how to reproduce:

-Create new project
-Create 2 folders in root( I created  scene and texture folders.
.Create scene,add a node and save it into scene folder.
-put some image into texture folder.
-create sprite node and load texture. save the  scene.
-close project and open it again.
-open scene and godot is unable to load texture.

I have attached an example project.
[test_bug.zip](https://github.com/godotengine/godot/files/129436/test_bug.zip)

**Comment by akien-mga** [comment] 2016-03-01 18:00
Closing as duplicate of #3842 which has slightly more info (I'll copy the link to the test project there though).

**Closed by akien-mga** 2016-03-01 18:00 UTC
Labels: bug, platform:windows, topic:core
