### ISSUE TITLE
Attempt to create C# script crashes editor

### ISSUE THREAD

**Issue by willnationsdev** [godotengine/godot#51160] opened 2021-08-01 22:11 UTC
### Godot version

4.0.dev (f06d201b)

### System information

Windows 10

### Issue description

When attempting to create a C# script, the Editor crashes. It appears to successfully save the actual file to the filesystem, but a .csproj is never made since it crashes soon afterward. Based on the backtrace, it *seems* to be mistakenly loading the script as if it were a tool script (just my guess)?

Here's the backtrace:

```
[0] Object::call (C:\Users\Will\source\repos\godot\core\object\object.cpp:773)
[1] Object::call (C:\Users\Will\source\repos\godot\core\object\object.cpp:773)
[2] CSharpLanguage::reload_tool_script (C:\Users\Will\source\repos\godot\modules\mono\csharp_script.cpp:764)
[3] ResourceFormatSaverCSharpScript::save (C:\Users\Will\source\repos\godot\modules\mono\csharp_script.cpp:3603)
[4] ResourceSaver::save (C:\Users\Will\source\repos\godot\core\io\resource_saver.cpp:117)
[5] ScriptCreateDialog::_create_new (C:\Users\Will\source\repos\godot\editor\script_create_dialog.cpp:321)
[6] ScriptCreateDialog::ok_pressed (C:\Users\Will\source\repos\godot\editor\script_create_dialog.cpp:286)
[7] AcceptDialog::_ok_pressed (C:\Users\Will\source\repos\godot\scene\gui\dialogs.cpp:106)
[8] call_with_variant_args_helper<AcceptDialog> (C:\Users\Will\source\repos\godot\core\variant\binder_common.h:223)
[9] call_with_variant_args<AcceptDialog> (C:\Users\Will\source\repos\godot\core\variant\binder_common.h:333)
[10] CallableCustomMethodPointer<AcceptDialog>::call (C:\Users\Will\source\repos\godot\core\object\callable_method_pointer.h:97)
[11] Callable::call (C:\Users\Will\source\repos\godot\core\variant\callable.cpp:51)
[12] Object::emit_signal (C:\Users\Will\source\repos\godot\core\object\object.cpp:1100)
[13] Object::emit_signal (C:\Users\Will\source\repos\godot\core\object\object.cpp:1155)
[14] BaseButton::_pressed (C:\Users\Will\source\repos\godot\scene\gui\base_button.cpp:128)
[15] BaseButton::on_action_event (C:\Users\Will\source\repos\godot\scene\gui\base_button.cpp:168)
[16] BaseButton::_gui_input (C:\Users\Will\source\repos\godot\scene\gui\base_button.cpp:67)
[17] call_with_variant_args_helper<BaseButton,Ref<InputEvent>,0> (C:\Users\Will\source\repos\godot\core\variant\binder_common.h:223)
[18] call_with_variant_args_dv<BaseButton,Ref<InputEvent> > (C:\Users\Will\source\repos\godot\core\variant\binder_common.h:366)
[19] MethodBindT<BaseButton,Ref<InputEvent> >::call (C:\Users\Will\source\repos\godot\core\object\method_bind.h:287)
[20] Viewport::_gui_call_input (C:\Users\Will\source\repos\godot\scene\main\viewport.cpp:1646)
[21] Viewport::_gui_input_event (C:\Users\Will\source\repos\godot\scene\main\viewport.cpp:1968)
[22] Viewport::input (C:\Users\Will\source\repos\godot\scene\main\viewport.cpp:3095)
[23] Window::_window_input (C:\Users\Will\source\repos\godot\scene\main\window.cpp:922)
[24] call_with_variant_args_helper<Window,Ref<InputEvent> const &,0> (C:\Users\Will\source\repos\godot\core\variant\binder_common.h:218)
[25] call_with_variant_args<Window,Ref<InputEvent> const &> (C:\Users\Will\source\repos\godot\core\variant\binder_common.h:333)
[26] CallableCustomMethodPointer<Window,Ref<InputEvent> const &>::call (C:\Users\Will\source\repos\godot\core\object\callable_method_pointer.h:97)
[27] Callable::call (C:\Users\Will\source\repos\godot\core\variant\callable.cpp:51)
[28] DisplayServerWindows::_dispatch_input_event (C:\Users\Will\source\repos\godot\platform\windows\display_server_windows.cpp:1803)
[29] DisplayServerWindows::_dispatch_input_events (C:\Users\Will\source\repos\godot\platform\windows\display_server_windows.cpp:1777)
[30] Input::_parse_input_event_impl (C:\Users\Will\source\repos\godot\core\input\input.cpp:642)
[31] Input::parse_input_event (C:\Users\Will\source\repos\godot\core\input\input.cpp:465)
[32] Input::flush_accumulated_events (C:\Users\Will\source\repos\godot\core\input\input.cpp:858)
[33] DisplayServerWindows::process_events (C:\Users\Will\source\repos\godot\platform\windows\display_server_windows.cpp:1530)
[34] OS_Windows::run (C:\Users\Will\source\repos\godot\platform\windows\os_windows.cpp:626)
[35] widechar_main (C:\Users\Will\source\repos\godot\platform\windows\godot_windows.cpp:163)
[36] _main (C:\Users\Will\source\repos\godot\platform\windows\godot_windows.cpp:185)
[37] main (C:\Users\Will\source\repos\godot\platform\windows\godot_windows.cpp:199)
[38] __scrt_common_main_seh (D:\agent\_work\9\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288)
[39] BaseThreadInitThunk
-- END OF BACKTRACE --
```

Here's the Mono log file: 
[2021-08-01_16.33.35_13048.log](https://github.com/godotengine/godot/files/6913504/2021-08-01_16.33.35_13048.log)

### Steps to reproduce

Open the project and try to create a `MyCsNode.cs` file in the `ScriptServerTest` subdirectory. This will trigger the crash.

### Minimal reproduction project

[Demo_GP22_4_0_Resources.zip](https://github.com/godotengine/godot/files/6913505/Demo_GP22_4_0_Resources.zip)

**Comment by NeqsTech** [comment] 2021-08-01 22:39
possible duplicate of #50689

**Comment by willnationsdev** [comment] 2021-08-01 22:43
Ah, that would make sense if the fix hasn't been done yet. Gotcha. Should this just be closed then?

**Comment by NeqsTech** [comment] 2021-08-01 22:56
It appears to be the same issue, tho #50689 did not produce a seg fault. I would close this issue and post the backtrace and the mono log in #50689 just in case.

**Closed** 2021-08-01 22:57 UTC
