### ISSUE TITLE
"Change Type" on Dialog is not updating preview

### ISSUE THREAD

**Issue by AlexHolly** [godotengine/godot#17487] opened 2018-03-13 15:32 UTC
Godot Master

1. Create "AcceptDialog".
2. "Change Type" to "ConfirmationDialog".

Result:

![image](https://user-images.githubusercontent.com/4741886/35465909-c93de482-02ff-11e8-951a-26957922ae96.png)

Expected:

![image](https://user-images.githubusercontent.com/4741886/35465927-e2c6849a-02ff-11e8-9be0-ffa22a82e091.png)

**Comment by ShyRed** [comment] 2018-03-13 18:08
Duplicate of #16350

**Closed** 2018-03-13 18:09 UTC
