### ISSUE TITLE
C# SourceGenerators: generated _Notification() method is not called

### ISSUE THREAD

**Issue by jasonswearingen** [godotengine/godot#92285] opened 2024-05-23 15:49 UTC
### Tested versions

- reproduced in `v4.3.dev6.mono.official [89850d553]`
- not tested in other versions

### System information

Godot v4.3.dev6.mono - Windows 10.0.22631 - Vulkan (Forward+) - integrated Intel(R) Iris(R) Xe Graphics (Intel Corporation; 31.0.101.3962) - 13th Gen Intel(R) Core(TM) i7-1360P (16 Threads)

### Issue description

I am having a sourcegenerator problem:  my generated code has this, and it's never being executed by godot

```csharp
   public override void _Notification(int what)
   {
     GD.Print("SORCEGEN: GodotNotifications Notify");
      base._Notification(what);
   }
```
I  am having to override in my "original" class and manually hook into generated helper methods instead.

everything else with sourcegen seems to work so far (providing constructors and helper methods work)
seems like godot doesn't see the override exists so never calls it

### Steps to reproduce

Create source generator using CSharp.

make a source generator that generates a partial class for `Node`

have it output the following method
```csharp
   public override void _Notification(int what)
   {
     GD.Print("SOURCEGEN: GodotNotifications Notify");
      base._Notification(what);
   }
```

the method is not invoked.

### Minimal reproduction project (MRP)

too complex to upload a repro.  You need a functional source generator that emits the `_Notification(int what)` method.

NOTE:   creating a partial class in the same assembly as the primary class won't work (or rather, it will override properly, this bug won't occur).  For the bug to occur it has to be emitted by a sourcegenerator.

**Comment by raulsntos** [comment] 2024-05-23 16:23
The lifecycle callbacks (such as `_Notification` or `_Ready`) are only called if the user overrides them. Godot's source generators add the overridden methods to `GetGodotMethodList` so Godot can keep track of them, but source generators can't consume the output of other generators.

To workaround this, you can use define partial methods in the "original" class:

```csharp
public override partial void _Notification(int what);
```

This way, Godot's source generators will see that this method is overridden and will add it to `GetGodotMethodList`, and you can still generate its implementation.

I'll close this issue as a duplicate of https://github.com/godotengine/godot/issues/66597, to consolidate in a single place. Thanks for the report.

**Closed by raulsntos** 2024-05-23 16:23 UTC

**Comment by jasonswearingen** [comment] 2024-05-23 16:37
thank you so much for the detailed explanation @raulsntos I really appreciate it.
