### ISSUE TITLE
Godot editor 3.0.3 on opensuse tumbleweed linux, crashes after some clicking

### ISSUE THREAD

**Issue by maxim27** [godotengine/godot#19603] opened 2018-06-16 16:50 UTC
Godot version: v3.0.3-stable_x11.64

OS/device including version: openSUSE Tumbleweed Linux

Issue description: Editor starts but after some clicking just crashes

Steps to reproduce: start editor via console (running: ./Godot_v3.0.3-stable_x11.64 in the terminal) one the dialog showing that there are no projects existing select the second option (but clicking abort also works) chose the samples views and click on next page.

Minimal reproduction project: i have none, it is an editor problem

here is some console output:
`OpenGL ES 3.0 Renderer: Mesa DRI Intel(R) HD Graphics 630 (Kaby Lake GT2) 
ERROR: _png_error_function: Not a PNG file
   At: drivers/png/image_loader_png.cpp:62.
libpng error: Not a PNG file
ERROR: _load_image: PNG Corrupted
   At: drivers/png/image_loader_png.cpp:94.
ERROR: _load_mem_png: Condition ' err ' is true. returned: Ref<Image>()
   At: drivers/png/image_loader_png.cpp:252.
ERROR: copy_internals_from: Condition ' p_image.is_null() ' is true.
   At: core/image.h:327.
ERROR: _jpegd_mem_loader_func: Couldn't initialize ImageLoaderJPG with the given resource.
   At: modules/jpg/image_loader_jpegd.cpp:125.
ERROR: _png_error_function: Not a PNG file
   At: drivers/png/image_loader_png.cpp:62.
libpng error: Not a PNG file
ERROR: _load_image: PNG Corrupted
   At: drivers/png/image_loader_png.cpp:94.
ERROR: _load_mem_png: Condition ' err ' is true. returned: Ref<Image>()
   At: drivers/png/image_loader_png.cpp:252.
ERROR: copy_internals_from: Condition ' p_image.is_null() ' is true.
   At: core/image.h:327.
ERROR: _jpegd_mem_loader_func: Couldn't initialize ImageLoaderJPG with the given resource.
   At: modules/jpg/image_loader_jpegd.cpp:125.
ERROR: _png_error_function: Not a PNG file
   At: drivers/png/image_loader_png.cpp:62.
libpng error: Not a PNG file
ERROR: _load_image: PNG Corrupted
   At: drivers/png/image_loader_png.cpp:94.
ERROR: _load_mem_png: Condition ' err ' is true. returned: Ref<Image>()
   At: drivers/png/image_loader_png.cpp:252.
ERROR: copy_internals_from: Condition ' p_image.is_null() ' is true.
   At: core/image.h:327.
ERROR: _jpegd_mem_loader_func: Couldn't initialize ImageLoaderJPG with the given resource.
   At: modules/jpg/image_loader_jpegd.cpp:125.
handle_crash: Program crashed with signal 11
Dumping the backtrace. Please include this when reporting the bug on https://github.com/godotengine/godot/issues
[1] /lib64/libc.so.6(+0x382d0) [0x7fbdca68f2d0] ()
[2] ./Godot_v3.0.3-stable_x11.64() [0x9d5231] ()
[3] ./Godot_v3.0.3-stable_x11.64() [0x9d5c92] ()
[4] ./Godot_v3.0.3-stable_x11.64() [0xa0287c] ()
[5] ./Godot_v3.0.3-stable_x11.64() [0xa030e0] ()
[6] ./Godot_v3.0.3-stable_x11.64() [0xa05648] ()
[7] ./Godot_v3.0.3-stable_x11.64() [0x9fef1d] ()
[8] ./Godot_v3.0.3-stable_x11.64() [0x8cc0eb] ()
[9] ./Godot_v3.0.3-stable_x11.64() [0x198cf54] ()
[10] ./Godot_v3.0.3-stable_x11.64() [0x1012bc5] ()
[11] ./Godot_v3.0.3-stable_x11.64() [0x101478d] ()
[12] ./Godot_v3.0.3-stable_x11.64() [0xbe73a4] ()
[13] /lib64/libpthread.so.0(+0x7554) [0x7fbdc90f6554] ()
[14] /lib64/libc.so.6(clone+0x3f) [0x7fbdca751fdf] ()
-- END OF BACKTRACE --
Abgebrochen (Speicherabzug geschrieben)`

**Comment by vnen** [comment] 2018-06-16 18:10
Duplicate of #19336

**Closed by vnen** 2018-06-16 18:10 UTC
