### ISSUE TITLE
Freeze after suspend/sleep - Godot 4.0 Alpha 2 - Ubuntu 20.04.1, GeForce GTX 1660 Ti, nvidia-driver-470, Vulkan

### ISSUE THREAD

**Issue by julianrotheric** [godotengine/godot#58115] opened 2022-02-14 21:10 UTC
### Godot version

v4.0.alpha.custom_build [79077e6c1]

### System information

Ubuntu 20.04.1, GeForce GTX 1660 Ti, nvidia-driver-470, Vulkan

### Issue description

With a fresh alpha 2 build on Ubuntu 20.04.1, Godot Editor always freezes after putting the system to sleep (suspend) and then logging back in. This is with a new and empty project. Please see the steps to reproduce.
The following error messages came out:
ERROR: Vulkan: Did not create swapchain successfully.
   at: prepare_buffers (drivers/vulkan/vulkan_context.cpp:1880)
ERROR: Condition "err" is true. Returning: ERR_CANT_CREATE
   at: swap_buffers (drivers/vulkan/vulkan_context.cpp:1956)

### Steps to reproduce

To reproduce: Download Godot 4.0 Alpha 2 tarball. Extract and cd into root of contents and run scons -j8 platform=x11. Run Godot editor with a new empty project. Put Ubuntu to sleep (suspend). After logging back in, Godot editor is frozen every time. The godot process must be killed to fix it. 

### Minimal reproduction project

New and empty project.

**Comment by Calinou** [comment] 2022-02-14 21:31
Duplicate of https://github.com/godotengine/godot/issues/52738.

**Closed by Calinou** 2022-02-14 21:31 UTC
