### ISSUE TITLE
Custom shader breaks Modulate

### ISSUE THREAD

**Issue by lufog** [godotengine/godot#60044] opened 2022-04-08 22:01 UTC
### Godot version

v4.0.alpha6.official [e4f0fc50f], v4.0.alpha.custom_build [b0ba818b8]

### System information

Windows 11, Geforce 1660, Vulkan Clustered

### Issue description

Custom shader breaks Modulate

https://user-images.githubusercontent.com/10379487/162537075-b0d8a7d3-d602-443e-a0e5-7193a666467c.mp4

v3.5.beta.custom_build [fa9b77dbe] doesn't have this problem.

### Steps to reproduce

Change the modulation of the sprites and compare their behavior.

### Minimal reproduction project

[CustomShaderModulateTest_G4.zip](https://github.com/godotengine/godot/files/8455499/CustomShaderModulateTest_G4.zip)

**Comment by Calinou** [comment] 2022-04-08 22:02
Duplicate of https://github.com/godotengine/godot/issues/49781.

**Closed by Calinou** 2022-04-08 22:02 UTC
Labels: topic:shaders, topic:2d
