### ISSUE TITLE
Polygon2D is extremely slow compared to Sprite rendering

### ISSUE THREAD

**Issue by bluepandion** [godotengine/godot#19943] opened 2018-07-03 19:51 UTC
**Godot version:**
3.04

**OS/device including version:**
Windows 10 / Surface Pro 4

**Issue description:**
Polygon2D seems alarmingly slow when compared to Sprite or draw_rect().

Here are some results from a small test scene I made:
![godot3_poly2d_performance](https://user-images.githubusercontent.com/8040820/42241241-8ced0604-7f12-11e8-9051-cced1068b495.jpg)

I've had the same results in a game project where I've attempted to create levels from Polygon2D objects. Usually optimized meshes would be very useful for optimizing fillrate, but this performance seems to make it impossible to utilize. I feel like this is going to hurt many graphically demanding 2D-projects.

**Steps to reproduce:**
Comparing between Sprite / Polygon2D and draw_rect() / draw_polygon() seems to give similiar results.

**Minimal reproduction project:**
[polygon2d_performance.zip](https://github.com/godotengine/godot/files/2160787/polygon2d_performance.zip)

**Comment by Zylann** [comment] 2018-07-03 20:18
Note: draw_polygon might require to recompute triangulation everytime, unless the polygon is retained and doesn't change (while sprites are trivial and dont require generic triangulation)

**Comment by bluepandion** [comment] 2018-07-03 20:36
> Note: draw_polygon might require to recompute triangulation everytime, unless the polygon is retained and doesn't change (while sprites are trivial and dont require generic triangulation)

Every time update() is called or every frame?
Still, that shouldn't concern the attached reproduction project since it generates individual nodes instead of using draw_polygon().

**Comment by CptPotato** [comment] 2018-07-04 07:36
I also think for a few 2D sprites this is kind of slow in general. Though, I don't know the specs of OP's device.

**Comment by dragmz** [comment] 2018-07-04 09:14
It's not caused by triangulation in this case. A quick profiling shows that the multiple glBufferSubData and glDrawElements (from RasterizerCanvasGLES3::_draw_polygon) cause the FPS drop here.

**Comment by dragmz** [comment] 2018-07-06 19:12
I'm working on a PR that reduces the number of glBufferSubData calls by splitting canvas_render_items implementation into the following parts:

1. Compute polygon data
2. Send the polygon data to GPU (with a single glBufferSubData call per buffer)
3. Execute render commands but use the already filled in buffers for rendering polygons.

Currently there is a per-polygon glBufferSubData call made and that hurts performance.

**Comment by reduz** [comment] 2018-09-07 18:54
did batching PR get merged in the end?

**Comment by akien-mga** [comment] 2018-09-10 14:57
No, #20965 was merged but was then reverted in #21204.

**Comment by chanon** [comment] 2018-10-09 05:31
I am having a big problem with this now.

What I need to do is to be able to submit triangles as vertices with uvs using `canvas_item_add_triangle_array` many times per frame. (I will have many nodes that each will draw themselves by using `canvas_item_add_triangle_array`.)

However doing so with less than 100 calls on iOS results in 20 fps. 

It is disappointing to see that Godot 3 does not do any automatic batching.

I would actually want to try and fix this .. or maybe at least write a new add_triangle_array call that would batch them, or maybe use something else that doesn't get impacted by the multiple `glBufferSubData` calls. 

However, I would like to ask first ... why is iOS using only GLES3?

I would like to implement this in only GLES2 which I thought was the recommended mobile renderer, however iOS is hardcoded to use GLES3?

**Comment by chanon** [comment] 2018-10-09 08:17
Just looking at #20077 speedup results:
> 
> Core i7-4790K, Intel 4600:
> 
>     480 polygons: 325 vs 60 = 5,42
>     1920 polygons: 185 vs 19 = 9,74
>     7680 polygons: 77 vs 5 = 15,4
>     sprites: no change
> 
> Core i3-2310M, Intel 3000:
> 
>     480 polygons: 60 vs 10 = 6
>     1920 polygons: 24 vs 3 = 8
>     7680 polygons: 7 vs 1 = 7
>     font rendering (using text_rendering.zip project attached below): 140 vs 10 = 14
>     sprites: no change
> 
> Android (Moto C):
> 
>     font rendering: 57 vs 4 = 14,25
> 

That is the difference between 2D polygons being actually useful or not.

**Comment by blurymind** [comment] 2019-03-25 12:13
is the dragonbones runtime outperforming godot's polygon2d node?
https://github.com/sanja-sa/gddragonbones/issues/5

**Comment by kjav** [comment] 2019-06-15 13:40
I can confirm that this is still an issue; adding just 20 polygons was enough to tank my android performance. I managed to work around this problem by rendering the polygons in a viewport once, and using the resulting texture to draw the polygon with a sprite node instead. This entirely solved the problem for me, but wouldn't work if your polygon geometry changed every frame.

**Comment by Xrayez** [comment] 2019-06-24 20:00
I'm not using `Polygon2D` but I think I'm having the same issue with `canvas_item_add_triangle_array`, with many vertices/lots of objects the performance can drop significantly even on desktop. For a moment I thought that was physics drop performance but seems like the real bottleneck is rendering. 🤔

**Comment by clayjohn** [comment] 2019-06-24 20:08
This should be vastly improved with the new Vulkan backend.

**Comment by lucaslcode** [comment] 2019-08-14 10:27
@kjav can you share a bit more details? something like this?:
Node 
-sprite
-viewport
--polygon
on load, draw the polygon, save the viewport texture to the sprite, delete the viewport

**Comment by dekaravanhoc** [comment] 2019-11-25 17:52
I am not quite shure, whether this is part of the same issue... But using Custom StyleBoxFlat Ressources on Control Elements also impacts performance really bad. Just three elements drop the performance to 30-40fps on my S7 Edge. So this is basically unusable on mobile.

**Comment by Calinou** [comment] 2019-11-25 18:02
@dekaravanhoc Can you take screenshots of the StyleBoxFlat properties you've used?

**Comment by dekaravanhoc** [comment] 2019-11-25 18:42
Shure. But I also changed the settings to test, whether transparency or anti-aliasing might be the reason, and neither of it is.
Thats a simple ProgressBar:
![image](https://user-images.githubusercontent.com/50260825/69567986-f9f2e400-0fba-11ea-814e-b2c601f74050.png)
![image](https://user-images.githubusercontent.com/50260825/69568046-1abb3980-0fbb-11ea-92bb-4c8dcd6ad510.png)

Thats a Label:
![image](https://user-images.githubusercontent.com/50260825/69568113-476f5100-0fbb-11ea-8eb8-cca342574345.png)

**Comment by jjgh** [comment] 2019-12-09 21:15
I think I'm facing the same problem. I wrote some code which instantiates about 100 Polygon2D objects from a Polygon2D object scripted to mutate geometry in reaction to mouse movement and it's running incredibly slow...

**Comment by clayjohn** [comment] 2019-12-09 21:22
@jjgh have you tried with 3.2? There was a PR merged that vastly improved polygon rendering. 

Also try reducing rendering/limits/buffers/canvas_polygon_buffer_size_kb and rendering/limits/buffers/canvas_polygon_index_buffer_size_kb in the project settings

**Comment by jjgh** [comment] 2019-12-10 03:34
Thanks for your advice @clayjohn but unfortunately using 3.2 did not make things better. 
After a couple of seconds FPS drops to 8.
In my case, the geometry of those 100 Polygon2D objects is randomly modified at every frame where mouse movement is detected. 
This random alteration often produces bad geometries ("bad polygon") which are not drawn and listed in the debugger. I'm not sure if this impacts on FPS. 
I will try to somehow avoid painting bad geometries and see if it goes better.

**Comment by jjgh** [comment] 2019-12-10 08:19
@clayjohn changed the code to only draw triangles so that bad polygons aren't possible anymore and it now works really fast so I think I can confirm that in my case the slowness was only caused by the debugger activity.

**Comment by DavidJVitale** [comment] 2020-02-04 01:21
> @jjgh have you tried with 3.2? There was a PR merged that vastly improved polygon rendering.
> 
> Also try reducing rendering/limits/buffers/canvas_polygon_buffer_size_kb and rendering/limits/buffers/canvas_polygon_index_buffer_size_kb in the project settings

@clayjohn This worked very well for me! I'm using 3.2 to make a a polygon-heavy game and was stuck at ~25FPS with the default of 128Kb buffer for both values:

![128kb_buffer](https://user-images.githubusercontent.com/18691334/73704422-df6a7480-46a7-11ea-98a6-35518d2335c9.png)

Switching both buffers to 32Kb moved this number up to ~40FPS!

![32kb_buffer](https://user-images.githubusercontent.com/18691334/73704421-df6a7480-46a7-11ea-928d-a342ca8bd646.png)

Thank you for all the work you and the other Godot developers have done. It's great to see such an active community.

**Comment by jshorty** [comment] 2020-04-05 08:32
For my use case, I was still seeing fairly bad performance after 3.2— I am rendering a large number of complex `Polygon2D` with many vertices. Using @kjav's [suggestion above](https://github.com/godotengine/godot/issues/19943#issuecomment-502367886) with @clayjohn's [suggested logic](https://github.com/godotengine/godot/issues/19239) for taking `Viewport` "snapshots" made a huge difference with my frame rate. As the latter mentions, figuring this out felt pretty unintuitive.

Here's a gist that renders an arbitrary polygon as a `Sprite`:
https://gist.github.com/jshorty/4090ba064ca0d3634d040e7a70c4833a

**Comment by clayjohn** [comment] 2020-10-11 05:12
This will be fixed by https://github.com/godotengine/godot/pull/42119.

Running the example project at 1x, polygon 2D was about 75% of the speed of sprites, but at 2x or higher the speed was the exact same (likely because at that range it becomes fill-rate limited).

**Comment by akien-mga** [comment] 2020-10-21 15:14
Fixed by #42119.

**Closed by akien-mga** 2020-10-21 15:14 UTC
Labels: bug, topic:rendering
