### ISSUE TITLE
File.open autocompletes enum from _File

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#41622] opened 2020-08-30 14:06 UTC
**Godot version:**

3.2.3 rc4

**Issue description:**

![DklUxw1kSb](https://user-images.githubusercontent.com/2223172/91661175-9c0ba380-eada-11ea-99fc-6ea525e0fcba.gif)

**Comment by vnen** [comment] 2020-08-31 23:45
Wait, this is in 3.2? @ThakeeNathees maybe this related to one of your changes to code completion?

**Comment by ThakeeNathees** [comment] 2020-09-01 05:54
this is reproducible since 3.2.0-stable. possibly https://github.com/godotengine/godot/pull/26990 will fix this.

**Comment by vnen** [comment] 2020-09-03 11:22
Oh, so it's older. But the namespace change won't be added to 3.2. This needs a workaround like what happens for other cases.

**Comment by me2beats** [comment] 2021-09-27 16:26
Still in 3.4 beta. I can see many newcomers get confused when they see this in completion popup then get the error

**Comment by akien-mga** [comment] 2021-09-27 16:49
This is fixed in 4.0 by using a proper namespace for these core singletons. But a workaround for `3.x` would still be good.

**Comment by HolonProduction** [comment] 2024-09-13 10:31
Not reproducible in v3.6.stable.official [de2f0f147], closing this as completed.

**Closed by HolonProduction** 2024-09-13 10:31 UTC
Labels: bug, topic:gdscript, topic:editor, usability
