### ISSUE TITLE
Editor randomly crashes when creating a plugin script

### ISSUE THREAD

**Issue by nonunknown** [godotengine/godot#51949] opened 2021-08-21 13:19 UTC
### Godot version

Godot Engine v4.0.stern-flowers.712.custom_build 78bf06ea4

### System information

manjaro Gnome 21, AMD R7 200 series, Intel i3 3.0 GHZ,8GB RAM

### Issue description

While creating a plugin, the editor randomly crashed:

```
SCRIPT ERROR: Parse Error: Preload file "" does not exist.
          at: GDScript::reload (built-in:5)
SCRIPT ERROR: Parse Error: Cannot infer the type of "ps_popup" variable because the initial value doesn't have a set type.
          at: GDScript::reload (built-in:5)
ERROR: Method/function failed. Returning: ERR_PARSE_ERROR
   at: reload (modules/gdscript/gdscript.cpp:840)
SCRIPT ERROR: Parse Error: Expected end of statement after variable declaration, found "`" instead.
          at: GDScript::reload (built-in:6)
ERROR: Method/function failed. Returning: ERR_PARSE_ERROR
   at: reload (modules/gdscript/gdscript.cpp:824)
SCRIPT ERROR: Parse Error: Expected expression for variable initial value after "=".
          at: GDScript::reload (built-in:6)
ERROR: Method/function failed. Returning: ERR_PARSE_ERROR
   at: reload (modules/gdscript/gdscript.cpp:824)
SCRIPT ERROR: Parse Error: Identifier "iun" not declared in the current scope.
          at: GDScript::reload (built-in:9)
ERROR: Method/function failed. Returning: ERR_PARSE_ERROR
   at: reload (modules/gdscript/gdscript.cpp:840)
handle_crash: Program crashed with signal 11
Dumping the backtrace. Please include this when reporting the bug on https://github.com/godotengine/godot/issues
[1] /usr/lib/libc.so.6(+0x3cda0) [0x7faa6fa63da0] (??:0)

[nonunknown@gaming-pc 3a1f3657-ce4a-4ffa-8f65-f41e1dfcaf68]$ X connection to :0.0 broken (explicit kill or server shutdown).
ERROR: BUG: Unreferenced static string to 0: hseparator
   at: unref (core/string/string_name.cpp:114)
ERROR: BUG: Unreferenced static string to 0: _update_wrap_at
   at: unref (core/string/string_name.cpp:114)
ERROR: BUG: Unreferenced static string to 0: _update_scrollbars
   at: unref (core/string/string_name.cpp:114)
ERROR: BUG: Unreferenced static string to 0: physics_process
   at: unref (core/string/string_name.cpp:114)
ERROR: BUG: Unreferenced static string to 0: physics_process_internal
   at: unref (core/string/string_name.cpp:114)
ERROR: BUG: Unreferenced static string to 0: _update_script_names
   at: unref (core/string/string_name.cpp:114)
ERROR: BUG: Unreferenced static string to 0: GizmoLightmapGI
   at: unref (core/string/string_name.cpp:114)
ERROR: BUG: Unreferenced static string to 0: GizmoVoxelGI
   at: unref (core/string/string_name.cpp:114)
ERROR: BUG: Unreferenced static string to 0: EditorRect2D
   at: unref (core/string/string_name.cpp:114)
ERROR: BUG: Unreferenced static string to 0: PrevScene
   at: unref (core/string/string_name.cpp:114)
ERROR: BUG: Unreferenced static string to 0: title_button_font_size
   at: unref (core/string/string_name.cpp:114)
ERROR: BUG: Unreferenced static string to 0: physics_frame
   at: unref (core/string/string_name.cpp:116)
ERROR: BUG: Unreferenced static string to 0: process_frame
   at: unref (core/string/string_name.cpp:116)
ERROR: BUG: Unreferenced static string to 0: version_changed
   at: unref (core/string/string_name.cpp:116)
ERROR: BUG: Unreferenced static string to 0: meta_hover_started
   at: unref (core/string/string_name.cpp:116)
ERROR: BUG: Unreferenced static string to 0: meta_hover_ended
   at: unref (core/string/string_name.cpp:116)
ERROR: BUG: Unreferenced static string to 0: main_screen_changed
   at: unref (core/string/string_name.cpp:116)
ERROR: BUG: Unreferenced static string to 0: frame_post_draw
   at: unref (core/string/string_name.cpp:116)
ERROR: BUG: Unreferenced static string to 0: frame_pre_draw
   at: unref (core/string/string_name.cpp:116)
ERROR: BUG: Unreferenced static string to 0: editor_script_changed
   at: unref (core/string/string_name.cpp:116)
ERROR: BUG: Unreferenced static string to 0: interface_added
   at: unref (core/string/string_name.cpp:116)
ERROR: BUG: Unreferenced static string to 0: button_up
   at: unref (core/string/string_name.cpp:116)
ERROR: BUG: Unreferenced static string to 0: settings_changed
   at: unref (core/string/string_name.cpp:116)

```

Code:

```gd
@tool
extends EditorPlugin

var bt:Button = Button.new()
var ps_popup := preload("res://addons/gdext/Popup.tscn")
var instance:Popup = null
func _enter_tree() -> void:
	bt.text = "GDExtension"
	instance = # ---> WHEN I WAS TYPING HERE THE CRASH OCCURED <----
	bt.connect("pressed",on_pressed)
	add_control_to_container(EditorPlugin.CONTAINER_TOOLBAR,bt)
	pass

func on_pressed():
	print("HelloWorld")
	pass

func _exit_tree() -> void:
	remove_control_from_container(EditorPlugin.CONTAINER_TOOLBAR,bt)
	pass

```

### Steps to reproduce

* Create a plugin
* Start editing the main plugin script (the one that has @tool
* It will randomly crash

### Minimal reproduction project

N/a

**Comment by Calinou** [comment] 2021-08-21 19:41
Duplicate of https://github.com/godotengine/godot/issues/51620.

**Closed by Calinou** 2021-08-21 19:41 UTC
Labels: bug, topic:editor, topic:plugin, crash
