### ISSUE TITLE
C# MultiplayerApi PeerConnectedEventHandler and PeerDisconnectedEventHandler 'id' parameter should be 'int' type

### ISSUE THREAD

**Issue by Aitor1405** [godotengine/godot#81192] opened 2023-08-31 12:12 UTC
### Godot version

4.0, 4.1

### System information

N/A

### Issue description

Hi, first of all, thanks for all the work done in this project.

Looking on source and other C# contracts related methods, seems that a multiplayer peer id should be of 'int' type and this contract is not respected on MultiplayerApi `PeerConnectedEventHandler` and `PeerDisconnectedEventHandler` delegates:

```c#
        //
        // Summary:
        //     Represents the method that handles the Godot.MultiplayerApi.PeerConnected event
        //     of a Godot.MultiplayerApi class.
        public delegate void PeerConnectedEventHandler(long id);
        //
        // Summary:
        //     Represents the method that handles the Godot.MultiplayerApi.PeerDisconnected
        //     event of a Godot.MultiplayerApi class.
        public delegate void PeerDisconnectedEventHandler(long id);
``` 

Didn't found information about this specific thing or if it has been done in purpose due to how Godot handles C# delegates internally but I encounter it a bit misleading. Obviously not a major issue but maybe it was a small mistake that can be changed.

### Steps to reproduce

N/A, just look at the MultiplayerApi.cs definition.

### Minimal reproduction project

N/A

**Comment by AThousandShips** [comment] 2023-08-31 13:44
This value is generated automatically, and it matches the built in type which is 64 bits

**Comment by raulsntos** [comment] 2023-08-31 18:08
Duplicate of https://github.com/godotengine/godot/issues/65749

**Closed by raulsntos** 2023-08-31 18:08 UTC
Labels: needs testing, topic:dotnet
