### ISSUE TITLE
Crash when opening scene containing ConvexPolygonShape generated from SphereMesh 

### ISSUE THREAD

**Issue by koopa** [godotengine/godot#17069] opened 2018-02-27 00:45 UTC
**Godot version:**
3.0.1 stable official

**Issue description:**
Editor crashes when trying to open a scene containing a ConvexPolygonShape that has been generated in the editor via "mesh -> create convex collison sibling" on a SphereMesh.

```GDB
#0  0x0000000000eb56c0 in Vector<int>::operator[] (this=0xa1e9030, p_index=2) at core/vector.h:138
#1  0x0000000002a053a8 in QuickHull::build (p_points=..., r_mesh=...) at core/math/quick_hull.cpp:416
#2  0x0000000001cd0abe in CollisionShapeSpatialGizmo::redraw (this=0x9ac05c0) at editor/spatial_editor_gizmos.cpp:2127
#3  0x0000000002144baf in Spatial::set_gizmo (this=0x8c3e160, p_gizmo=...) at scene/3d/spatial.cpp:412
#4  0x0000000001bb581d in SpatialEditor::_request_gizmo (this=0x7da6ba0, p_obj=0x8c3e160) at editor/plugins/spatial_editor_plugin.cpp:4825
#5  0x0000000000f33ba2 in MethodBind1<Object*>::call (this=0x7ea1a00, p_object=0x7da6ba0, p_args=0x7fffffffd550, p_arg_count=1, r_error=...) at core/method_bind.gen.inc:729
#6  0x0000000002940a33 in Object::call (this=0x7da6ba0, p_method=..., p_args=0x7fffffffd550, p_argcount=1, r_error=...) at core/object.cpp:914
#7  0x000000000297bb2f in MessageQueue::_call_function (this=0x3fad8d0, p_target=0x7da6ba0, p_func=..., p_args=0x7ffff7e6b608, p_argcount=1, p_show_error=false) at core/message_queue.cpp:260
#8  0x000000000297bd7f in MessageQueue::flush (this=0x3fad8d0) at core/message_queue.cpp:305
#9  0x0000000001e4430b in SceneTree::iteration (this=0x44098e0, p_time=0.0166666675) at scene/main/scene_tree.cpp:464
#10 0x0000000000ed91c5 in Main::iteration () at main/main.cpp:1754
#11 0x0000000000eb3949 in OS_X11::run (this=0x7fffffffd920) at platform/x11/os_x11.cpp:2438
#12 0x0000000000ea89bc in main (argc=2, argv=0x7fffffffde38) at platform/x11/godot_x11.cpp:55
```

**Steps to reproduce:**
`mv bug.tscn{.txt,} && godot -e bug.tscn`

[bug.tscn.txt](https://github.com/godotengine/godot/files/1760787/bug.tscn.txt)

**Comment by hpvb** [comment] 2018-02-27 02:33
duplicate of #16560 probably.

**Comment by akien-mga** [comment] 2018-02-27 10:14
Indeed, it's the same backtrace.

**Closed by akien-mga** 2018-02-27 10:14 UTC
