### ISSUE TITLE
Outline ctrl+f highlight in docs

### ISSUE THREAD

**Issue by isnt-alice** [godotengine/godot#27492] opened 2019-03-28 14:52 UTC
Outline is present in the script editor.
Lack of outline severely impedes visibility.

**Comment by Calinou** [comment] 2019-03-28 14:57
This should be fixed by https://github.com/godotengine/godot/pull/27469. In the meantime, I'll close this issue as a duplicate of https://github.com/godotengine/godot/issues/22552.

**Closed by Calinou** 2019-03-28 14:57 UTC
