### ISSUE TITLE
Steam: wrong Godot version is referred to when runtime environment is initialized

### ISSUE THREAD

**Issue by TheRealPhotonic** [godotengine/godot#16527] opened 2018-02-10 05:01 UTC
**Godot version:** 

2.1 (Steam)

**OS/device including version:**

Windows 10 (64 bit x86), Intel i3-2330, integrated graphics card

**Issue description:** 

I have Godot 3.0 _and_ Godot 2.1 installed, and so does my fellow programmer. We were testing out the collaboration capabilities of Godot 2.1 after we both installed version 3.0 through Steam as well, but my computer's GPU is outdated and could not run that particular version, so we resorted to 2.1 and called it a day.

Note: As you can see from [this screenshot](https://gyazo.com/30975d8cc110f0372ea77333a73b29b7), my Godot 2.1 installation was nested within my Godot 3.0 folder, though in a separate directory.

I had copied and pasted a modified version of the Rude Goldberg sample project into another folder, specifically one with GitHub support/metadata in it, and I had been successful in moving those files over to my partner's computer. He had opened the project successfully, though right after he opened it, [this error appeared](https://gyazo.com/3b8a20d34a75ca10763fcb4456836766) in the project output. He tried to run the code, but to no avail - the dependencies were broken. Upon fixing these dependencies, the x/y coordinates of all of the objects were set to (0,0) - they ended up inside of each other.

I had further investigated into this issue, and what I concluded to is that in the error shown in the console, specifically on the first line; it reads ". . . \steamapps\common\Godot Engine\godot.windows.opt.tools.64 . . ." **Godot was attempting to initialize the runtime environment from Godot 3.0 instead of the one from 2.1, since that folder is nested inside of the installation of Godot 3.0,** as I have shown above. Godot either never detected that it was in the 3.0 directory, or when the project metadata was created, the version number it was initialized in was stored in the Godot launcher rather than in the project files. After telling my partner to download the Godot 2.1 executable from online and run the project from there (to stay consistent with one installation directory), the project file worked perfectly.

**Steps to reproduce:**

1. With both Godot 3.0 and 2.1 installed through Steam, create a program through Godot 2.1 (assuming it is nested within 3.0's installation files), then push it to GitHub.
2. Pull it on another computer with both Godot 3.0 and 2.1 installed through Steam, and open the project through Godot 2.1. The error should then appear in the console, and your dependencies will break even when all concurrent files are present in the working directory.

**Minimal reproduction project:** [Rude-Goldberg-Modified.zip] 
(https://github.com/godotengine/godot/files/1713020/Rude-Goldberg-Modified.zip) (This was the file we used when we found the bug, though it will probably work with any project.)

If any further clarification is necessary, please ask - I will elaborate. Thanks!

**Comment by akien-mga** [comment] 2018-02-13 21:08
Thanks for the detailed report. At first I don't seem to be able to reproduce this on Linux. I imported your project somewhere in my home directory, ran Godot 2.1 through Steam, imported the project and could edit it and run it just fine:
```
running: /media/data/Jeux/SteamApps/common/Godot Engine/2.1/godot.x11.opt.tools.64 -path /media/data/Jeux/SteamApps/common/Godot%20Engine/2.1/demos/2d/space_shooter -rdebug 127.0.0.1:6096 -allow_focus_steal_pid 16791 -p 448x240 res://main_menu.tscn
```

Where did you put your project exactly, and how did you start Godot 2.1 to run it?

**Comment by akien-mga** [comment] 2018-02-19 11:27
> Where did you put your project exactly, and how did you start Godot 2.1 to run it?

Ping. I really don't understand how this issue could happen so I need more details to reproduce it.

**Comment by akien-mga** [comment] 2018-02-24 00:43
Closing as I can't reproduce it.

**Closed by akien-mga** 2018-02-24 00:43 UTC
Labels: bug
