### ISSUE TITLE
Physics2dDirectBodyState of _integrate_forces refer to a different object after yielding to a Timer / Tween

### ISSUE THREAD

**Issue by mrkdji** [godotengine/godot#52072] opened 2021-08-24 17:10 UTC
### Godot version

3.3.3.stable 3.3.2stable

### System information

Windows 10

### Issue description

The state parameter in a RigidBody2D _integrate_forces refers to a different object after yielding to a timer / tween.
In particular it seems to always refer to the last child added to the scene tree.

### Steps to reproduce

Run the Bug scene and press "up arrow" / w.
The circle should "jump" even if the script is attached to the square rigidbody.
If the square rigidbody node is moved as the last child of the scenetree this behaviour doesn't occur.

### Minimal reproduction project

[RigidBodyIntegrateForcesBug.zip](https://github.com/godotengine/godot/files/7040803/RigidBodyIntegrateForcesBug.zip)

**Comment by pouleyKetchoupp** [comment] 2021-08-24 22:59
Similar to #42877, but this use case might also cause crashes if the body is destroyed in the meantime, so it might need a more specific fix.

**Comment by pouleyKetchoupp** [comment] 2021-08-25 16:21
Closing as duplicate of #42877

**Closed by pouleyKetchoupp** 2021-08-25 16:21 UTC
Labels: bug, confirmed, topic:physics
