### ISSUE TITLE
Editor unusable with multiple screens on OS X

### ISSUE THREAD

**Issue by virtualritz** [godotengine/godot#6102] opened 2016-08-10 12:56 UTC
**Operating system or device - Godot version:**
OS X 10.11.6, Gotot 2.1

**Issue description** (what happened, and what was expected):
2nd screen attached via HDMI. Main screen is Retina MacBookPro screen (13"). Secondary screen is DELL HD (1080p) monitor.
I want to use the 2ndary screen to place the editor window.
The 2ndary screen is not a HI DPI (Retina) screen. But Godot still seems to apply the Retina scale factor. I.e. it doesn't determine that the window was dragged to a screen w/o a scale factor.
 
**Steps to reproduce:**
Open Godot.
Editor opens fine on primary (laptop) Retina screen
Drag window to 2ndary screen. Window turns white.
Window is redrawn after 1-2 seconds. Part of editor is missing (see 1st attached screen shot)
Resize Window to fill full 2ndary screen. Editor is scaled and unusable (see 2nd attached screen shot)
![screen shot 2016-08-10 at 14 53 42 2](https://cloud.githubusercontent.com/assets/387036/17554314/9b2db6ac-5f0a-11e6-8799-4ccce5085f0c.png)
![screen shot 2016-08-10 at 14 53 50 2](https://cloud.githubusercontent.com/assets/387036/17554321/a1302224-5f0a-11e6-8971-10e176b74e5c.png)

**Comment by akien-mga** [comment] 2016-08-10 13:06
I believe this is a duplicate of #5688.

**Closed by akien-mga** 2016-08-10 13:06 UTC

**Comment by virtualritz** [comment] 2016-08-10 13:58
Yes, looks like it. I didn't see #5688. Kindly ignore.
