### ISSUE TITLE
Unable to open dropdowns and other popups.

### ISSUE THREAD

**Issue by nathanfranke** [godotengine/godot#40312] opened 2020-07-12 08:39 UTC
**Godot version:**

Master a474926ac

**OS/device including version:**

Linux Mint 20

**Issue description:**

Popups such as dropdowns are closed when the mouse is released or leaves the button area.

https://www.youtube.com/watch?v=uo5vsD19090

**Steps to reproduce:**
- Click a dropdown and release, it will close.
or
- Click a dropdown and hold, drag outside of the button area. It will close.

**Minimal reproduction project:**

Works in any project through editor settings.
[Test.zip](https://github.com/godotengine/godot/files/4908224/Test.zip)

**Comment by KoBeWi** [comment] 2020-07-12 17:59
Duplicate of #40227

**Closed by KoBeWi** 2020-07-12 17:59 UTC
