### ISSUE TITLE
Suggestion: Engine Setting to select the default format for scene savefiles

### ISSUE THREAD

**Issue by captainwasabi** [godotengine/godot#4582] opened 2016-05-08 11:49 UTC
**Operating system or device - Godot version:**

**Issue description** (what happened, and what was expected):
Artists keep checking in scene files in the default (.scn) format.  It would be nice if I could set the default to .tscn for them so it plays nicely-er with SVN.

**Steps to reproduce:**

**Link to minimal example project** (optional but very welcome):

**Comment by neikeq** [comment] 2016-05-08 12:00
Duplicate of #3996

> I think this should be made optional in the editor settings, or project settings (preferred scene format)
> · reduz

**Closed by neikeq** 2016-05-08 12:00 UTC
