### ISSUE TITLE
stop_on_slopes seems to do nothing.

### ISSUE THREAD

**Issue by yosoyfreeman** [godotengine/godot#42546] opened 2020-10-03 23:49 UTC
**Godot version: 3.2.3 64 bits**

**OS: Linux**

**Issue description:**
When using move_and_slide(), stop_on_slopes is not working. The kinematic body full slides even when stop_on_slopes is true. (only works if there is no lateral movement. Like (0,-x,0))

**Steps to reproduce:**
use move_and_slide to move a kinematic body over a non-horizontal floor with a dow1nforce and horizontal movement. (move_and_slide(Vector3(1,-1,1)) with step on slopes set to true. There is no difference.

**Minimal reproduction project:**
by default there is only pure vertical motion. (working right). if you press "enter", it adds a little lateral motion and start sliding.
[test.zip](https://github.com/godotengine/godot/files/5322430/test.zip)

**Comment by justchen1369** [comment] 2020-10-04 00:29
https://github.com/godotengine/godot/issues/34117

**Comment by yosoyfreeman** [comment] 2020-10-04 01:00
> #34117

i cant see the relation.

**Comment by madmiraal** [comment] 2020-10-04 08:26
Closing as duplicate of #34117.

> (only works if there is no lateral movement. Like (0,-x,0))

As per the documentation:
> If `stop_on_slope` is `true`, body will not slide on slopes when you include gravity in `linear_velocity` and the body is standing still.

**Closed by madmiraal** 2020-10-04 08:26 UTC

**Comment by yosoyfreeman** [comment] 2020-10-04 13:22
Well, this is not a duplicate and should not be archived.  The info on the post you give me is wrong. Also the documentation seems to be wrong now.  Many people has been spending lot of time documenting this kind of issues and your post will confuse many people. Move and slide has been broken for so long, but now is just unusable.   

The thing of "only stop on slopes when "x and z is less than y" is a bug. Have no sense at all. No as a programmer, not as a game dev.  Also, someone should correct the documentation again cause the body should not slide with ANY x and z values (the standing still thing is just... ). 

We put a lot of effort documenting the problems. Now people is confuse again using weird workarounds. 

Also here you have a topic about that (reduzio included): https://www.reddit.com/r/godot/comments/hqhxcm/lets_talk_about_the_actual_approach_for_move_and/
