### ISSUE TITLE
Godot 4.0: Setting a rotation in the sky section of the WorldEnvironment node causes the background to rotate when the editor or in-game camera3D is rotated.

### ISSUE THREAD

**Issue by Nyre221** [godotengine/godot#60534] opened 2022-04-26 15:29 UTC
### Godot version

4.0.alpha6

### System information

Operating System: KDE neon 5.24 KDE Plasma Version: 5.24.3 KDE Frameworks Version: 5.92.0 Qt Version: 5.15.3 Kernel Version: 5.13.0-37-generic (64-bit) Graphics Platform: X11 Processors: 8 × AMD FX(tm)-8350 Eight-Core Processor Memory: 7.5 GiB of RAM Graphics Processor: NVIDIA GeForce GTX 970/PCIe/SSE2

### Issue description

the panoramasky rotates when the camera3d is rotated if the rotation in the sky section of the WorldEnvironment node is greater than 0 on one of the axes.

### Steps to reproduce

1) Create a 3d project and add the WorldEnvironment node
2) Under background select sky mode and add a panoramasky
3) add an image and set the rotation to a value greater than 0.

https://user-images.githubusercontent.com/104171042/165336302-c0a2ecc1-f2bd-42f8-88de-d32857c341cb.mp4

### Minimal reproduction project

[rotation.zip](https://github.com/godotengine/godot/files/8564615/rotation.zip)

**Comment by Calinou** [comment] 2022-04-26 15:36
Duplicate of https://github.com/godotengine/godot/issues/56136.

**Closed by Calinou** 2022-04-26 15:36 UTC
