### ISSUE TITLE
Feature request; Slow parenting

### ISSUE THREAD

**Issue by Ace-Dragon** [godotengine/godot#19508] opened 2018-06-11 15:12 UTC
The reason I bring this up, I've been reading the other thread about Reduz's idea of pushing things out of the engine. However, getting rid of the _Interpolated Camera_ node could cause a number of problems for people because Godot does not yet have the concept of slow parenting.

What slow parenting would do is instead of a child object updating its position instantly based on where the transform of the parent object, it would update in a way that is delayed and on a smooth curve. The amount of delay and the length of this curve meanwhile would depend on a user-defined value (the higher the value, the more delayed and the more smooth the response).

This would be useful for more than just camera systems though, it could be used for any setup where a delayed response is needed (such as a companion object for a character). Another reason for this is because having a perfectly smooth and curved response otherwise can be difficult to do in GDscript unless you are well versed in math concepts such as trigonometry.

Thoughts?

**Comment by isaacremnant** [comment] 2018-06-11 16:03
There's no trig needed for what you're requesting (or what Camera2D currently does), it's just the one-liner
`position += some_speed * (parent.position - position) * delta`

Sure it could be made more complex (varying some_speed with a tween say), but I feel like it depends a lot on the specific application.

**Comment by Ace-Dragon** [comment] 2018-06-11 16:35
The slow parenting ability proposed here would apply for both the 2D and 3D modes for Godot.

It would also be the same for rotations and perhaps even scaling as well (and because it's still related to parenting, the end transform of the child object would always catch up to where it would be under regular parenting if given the chance).

Then you would have the option of slow-parenting at different extents throughout an entire hierarchy of objects (allowing for complex, flowing movements with little to no code). That is not to forget that the delay parameter would be controllable by code as well.

**Comment by groud** [comment] 2018-06-11 17:44
It's not difficult to do, it's more or less the basics of game programming.
As explained by @isaacremnant that's a one-liner in most situation. And for more complex cases, such as camera interpolation, it will stil be available via the asset store.

Also, you've got the tween node to do so, and the brand new capture animation feature.

**Comment by Ace-Dragon** [comment] 2018-06-11 18:07
That one-liner though only covers positional movement in 2D games (I'm pretty sure the 'tween' node is 2D only as well).

It can get more complicated in 3D games (especially if you want to add rotation to it, following it up with variable control of the delay). Besides that, I don't recall people pushing back against making it easier for Godot users to do things like getting an object to look at another or switching to a new scene (we used to not have functions specific to those).

Even the BGE has slow-parenting (and that community is quite aggressive about 'build it yourself' ideology).

**Comment by groud** [comment] 2018-06-11 18:31
> I'm pretty sure the 'tween' node is 2D only as well.

No, it's a generic purpose node.

> It can get more complicated in 3D games (especially if you want to add rotation to it, following it up with variable control of the delay) 

That's handled by the new animation editor. And i'm pretty sure this could be easily achieved with a simple script, there's no need for it to be added to the core. Maybe the tween node can be adpated though, if it's not already possible.

**Comment by Ace-Dragon** [comment] 2018-06-11 19:11
Looked at the 'tween' node and the docs. aren't of any help in terms of actually using it (it would sound like you could use it to interpolate between two values defined in code, but nearly every function is a bool).

I also don't know if the new animation editor would be a solution, a slow parent effect would be something that is ongoing and dependent on object motion and not something prebaked into keyframes.

In all, I really don't get why this should be controversial. If the developers want to remove features on the ground of being a little too 'specific' (converted to assets or worse, taken out of the engine and then sold back to us for a price), then we need features to help recreate whatever effects they provided and more due to being more generic.

**Comment by groud** [comment] 2018-06-11 19:21
When we say moving to the "asset store", it's just moving stuff out of the core. Such plugin will still be completely free & MIT licensed (for things we remove). Most of them will stay "official" by keeping it in a godot organization's repository.

This is controversial since people exporting games on mobile platforms do not want to have a 40Mb executable size for a simple 2D game. That's why most "too specific" assets should be moved out of the core, and made optional. This does not mean they won't be maintained.

**Comment by Ace-Dragon** [comment] 2018-06-11 20:09
Well, I made a quick attempt to rewrite the camera system for my project through use of the 'tween' node rather than the 'interpolated camera' node. I have to say, I had no idea where I was supposed to go.

Not having the interpolated camera behavior nor the slow parenting in the engine would mean a lot of users would end up thinking the same. Considering that Godot is an engine that is said to be making game development easy and fun, doing such a thing would mean the engine doing a huge amount of backpedaling away from that. Is trimming the file-size  a little (barring a strip system) really worth making many common game mechanics much harder to do (especially one in nearly every third-person game in existence)? Then there's the fact that slow-parenting would a generic parameter for all nodes (as it would affect the fundamental relationship between it and its parent), I'm not sure if assets can do that yet (and even if they did, having it built in would likely be faster anyway).

**Comment by groud** [comment] 2018-06-11 20:23
> Well, I made a quick attempt to rewrite the camera system for my project through use of the 'tween' node rather than the 'interpolated camera' node. I have to say, I had no idea where I was supposed to go.

The tween node is for interpolating generic properties, it might not work as is for 3D.


> Is trimming the file-size a little (barring a strip system) really worth making many common game mechanics much harder to do (especially one in nearly every third-person game in existence)?

Donwloading a plugin is not "much harder".

Honestly I have the feeling that's you're talking about a feature you saw elsewhere but did not bother understanding how things works in godot. As said before, interpolation can be done with tween nodes, scripts or animation (on the master branch). It might need some tweaks to work with 3D positioning though. Please read to documentation to understand what it does.

In any case, what you describe is a very specific behaviour that need to be used only on specific kind of nodes, and can be easily workarounded with a single line of script (I'm pretty sure an interpolation function exists for 3D transforms). So, to be honest, there's very little chance that this gets added to the core.

**Comment by groud** [comment] 2018-06-11 20:28
Regarding the one liner, you probably can do something like this:
`
$mynode.transform =  $mynode.transform.interpolate_with($target.transform, 0.1 * delta)`

**Comment by Ace-Dragon** [comment] 2018-06-11 20:46
I'm already beginning to figure it out, thanks.

However, it's definitely more than 1 line of code. At least though, it doesn't appear to be near as complex as I thought (though I'm not using the tween node or the animation).

I still see myself as a proponent of built-in features and node types though (mainly for reasons of performance and the ease-of-use in just having them whenever I download a new build). On performance, try writing a particle system in GDscript compared to just using the node for instance.

**Comment by cosmicchipsocket** [comment] 2018-06-11 22:01
I was faced with a similar issue when I decided to move away from InterpolatedCamera so I could have the movement occur during the physics step, eliminating jitter.

Godot's Transform class has a built-in function for this:
http://docs.godotengine.org/en/3.0/classes/class_transform.html#class-transform-interpolate-with

Example usage:

```
var source_transform = source_obj.get_transform()
var dest_transform = dest_obj.get_transform()
var lerp_transform = source_transform.interpolate_with(dest_transform, 0.25)
source_obj.set_transform(lerp_transform)
```

**Comment by groud** [comment] 2018-06-12 10:12
>In all, it functions about the same as the Interpolated Camera node, but it's definitely more than 1 line of code.

It is one line of code. 

I just tested that: 

```
func _process(delta):
	global_transform = global_transform.interpolate_with($"../target".global_transform, 0.5 * delta)
```

And it works perfectly:

![output](https://user-images.githubusercontent.com/6093119/41284525-d700e722-6e39-11e8-8d7c-f268d42fa7cf.gif)

**Comment by eon-s** [comment] 2018-06-12 10:49
What about an interpolated option to remote transform nodes?

**Comment by kubecz3k** [comment] 2018-06-12 11:50
@eon-s that's a nice idea, as a user of remote transform I must say I sometimes needed to use it together with tween for starting the remote (not such big hassle since we can yield tween completion and then start 'normal' remote following, but still I think it would ease workflow for users)

**Comment by groud** [comment] 2018-06-12 11:56
> What about an interpolated option to remote transform nodes?

I'd say the problem is that there are several ways of interpolating between several values, as the animation editor suggests. I'm not sure if it's worth adding such behavior in the core.
But why not, the RemoteTransform node might benefit from that.

**Comment by aaronfranke** [comment] 2019-02-28 23:30
Why does this need to be in the engine? Can't you accomplish this by just keeping track of the global position, and interpolating that value towards the parent's position?

**Comment by Anutrix** [comment] 2019-07-09 15:44
I use this in my projects. 

`look_at_from_position(transform.origin.linear_interpolate(targetCamPos.get_global_transform().origin, delta * followSpeed),player.transform.origin,Vector3.UP)`

where targetCamPos is a Spatial child of Player at a certain offset and is used as a position where the camera should finally reach after following. Works well with rotation too.

**Comment by Calinou** [comment] 2020-05-26 08:32
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!

**Closed by Calinou** 2020-05-26 08:32 UTC
Labels: feature proposal, topic:core
