### ISSUE TITLE
Game appears washed out | Alpha 8 -> Alpha 9

### ISSUE THREAD

**Issue by Travistyse** [godotengine/godot#61710] opened 2022-06-05 04:42 UTC
### Godot version

4.0 Alpha 9

### System information

Windows 11, Vulkan, RTX 2070

### Issue description

![Regression](https://user-images.githubusercontent.com/14159864/172035207-7d377367-e39d-4143-9d37-1a3cbfe346ba.png)

It's the same project opened in both versions of Godot. 
What's pictured are 3D meshes with albedo textures applied via a material. I'd look into the material but I'm very new to Godot's 3D (compared to Unreal / Unity) and it seems that the materials that I've imported via Blender are completely inaccessible (the textures I can look at as I chose the appropriate option, but the materials not so much).

I'm aware that the issue is likely related to the shader change mentioned in the changelog but I have no clue how to resolve this aside from creating entirely new materials in order to use shaders to convert to sRGB or Linear or whatever makes this look correct.  Which would be.. a lot of work added to each and every textured model I ever import into the project.

### Steps to reproduce

Import a 3D model with a textured material from Blender using .gltf export and it should happen. Like I said, my project looks correct in Alpha 8 and incorrect in Alpha 9 and that's the only difference.

**Comment by fire** [comment] 2022-06-05 13:20
Looks like a color gamma conversion issue, probably related to the unlit extension. Don't have a project to test, so only guessing.

**Comment by Calinou** [comment] 2022-06-05 15:36
Shaders using `hint_color` should be modified to use the new name `source_color` in 4.0.

**Comment by Travistyse** [comment] 2022-06-05 18:57
That's definitely true, but I'll try importing another mesh and see what
happens once I'm at my computer. If that's all this is it's not that bad -
but I'll mention that this wasn't fixed when I hit reimport so it's a
change which will seemingly require anyone affected to mass delete and
reimport their meshes.. which wouldn't sound all that bad except that my
meshes *are* by Godot's very nature already inside of the project
directory. Afaik there isn't an actual "mat-42" floating around that I can
adjust or attach a shader to so I'm of course concerned that moving the
meshes out, directories and all (because they're categorized and pointed to
by scenes) won't cause the materials to reload when I shove the meshes back
in but nonetheless, it's an Alpha (: it's what I signed up for and I'll do
whatever needs to be done. And hey, this could be a rather simple fix.

**Comment by Travistyse** [comment] 2022-06-05 22:29
Okay, final followup: Yes removing and reimporting works and I've also confirmed that simply creating a new material and assigning it to the already imported model fixes it. Considering that I don't like using Blender at all when it comes to applying materials / textures to models, this seems more like a workflow change that I'd have wanted for myself anyway regardless of the bug. 

But it is definitely still a bug. The code wasn't written with the intent to suddenly make every game pastel as can be :)

**Comment by fire** [comment] 2022-06-05 23:14
I don't know how to explain there's three layers of changing materials.

1. the mesh has surfaces with materials
2. the mesh instance has overrides
3. and the mesh instance's base class has one override compared to per surface overrides

**Comment by clayjohn** [comment] 2022-06-07 15:32
This looks like it was caused by the ``hint_color`` -> ``source_color`` rename. I'm not sure that there is anything actionable here. 

Keep in mind, that we are currently in the alpha release stage of 4.0. Alpha means there will be breaking changes and things can and will be renamed. If you are not comfortable with breaking changes between alpha releases, then we recommend that you wait until the later betas or release candidates before porting your project to 4.0.

**Comment by akien-mga** [comment] 2023-02-16 23:27
Closing as per above comment.

**Closed by akien-mga** 2023-02-16 23:27 UTC
Labels: bug, discussion, topic:rendering, topic:3d
