### ISSUE TITLE
Can't edit animation when it's created by copying another animation

### ISSUE THREAD

**Issue by mysticfall** [godotengine/godot#22551] opened 2018-09-30 10:37 UTC
**Godot version:**
`master` / 0de8309b2

**OS/device including version:**
Manjaro Linux 17.1

**Issue description:**
When creating an animation in an `AnimationPlayer` node (tested with a property track) by copying and pasting an existing animation, any edit on either of the animations would be applied to the other one as well, effectively defeating the purpose of copy & paste animations.

Copying and pasting an existing animation should create a new animation with the same tracks and keys which can be edited without affecting the source animation.

**Comment by metaphoricalsasquash** [comment] 2018-09-30 20:02
I was thinking about opening an issue about naming conventions. Right now it's really confusing for newcomers for no reason at all. 
"Duplicate", "Copy and Paste" and "Create Instance" are used interchangeably while they are actually vastly different operations but sometimes do the same and then again different things within Godot. For example if you rightclick and select "Duplicate" a scene in the filebrowser panel, you create a true duplicate of that scene. Whereas if you rightclick and "Duplicate" a Node in the  Scene Panel, you create an instance. One example of many.

**Comment by mysticfall** [comment] 2018-09-30 23:59
@metaphoricalsasquash I agree that it's better to have consistent naming across editor features. But I'm a bit confused as to what it means in the context of this issue.

Do you mean the symptom I described above could be an intended behavior? If so, could you please elaborate some use case for it?

**Comment by metaphoricalsasquash** [comment] 2018-10-01 00:15
Animations are "resources" within Godot, I believe. I think that might be the reason why copy and paste results in an instance of that animation, not a duplicate copy by default. Though I absolutely agree with you: I don't think an instance is the expected result when a user performs a copy and paste operation. 
In my opinion what is currently available should be called "set as instance source" (right now known as copy) and "paste animation instance" (right now known as paste), and then there should also be a proper copy and paste, which does not create an instance/link/reference to an already existing animation, but just copy all keys and values and past them someplace else. Ideally via Ctrl+C, Ctrl+V or right click context menu in addition to the pull down menu.

**Comment by mysticfall** [comment] 2018-10-01 00:35
Oh, now I see why you are suspecting this could be the intended behavior. As to animations in `AnimationPlayer` though, I can't think of any real use case where you want to add the exact same animations under different names which is what the current copy & paste operation results, as you agree that it's not usually what users would expect.

**Comment by metaphoricalsasquash** [comment] 2018-10-01 01:27
Yes, I cannot think of any real usecase either. I can however think of million usecases where I would need real copy and paste functionality inside Godot.
Recently though, I tried to apply the same frame animation to multiple Sprites under one AnimationPlayer. Feel free to check it out: [#22421](https://github.com/godotengine/godot/issues/22421)

**Comment by golddotasksquestions** [comment] 2019-03-08 20:09
"Make unique" is what the rest of the world calls a "copy". 
Please Godot, make this the default, enable select->Ctrl+C->Ctrl+V, give us proper copy and paste!
Those who want so use it as shared reference can still save the animation and use that saved file, which should not be automatically connected to the file it was saved from, elsewhere.

**Comment by KoBeWi** [comment] 2019-10-15 14:44
Closing in favor of #24950, which is more accurate.

**Closed by KoBeWi** 2019-10-15 14:44 UTC
Labels: bug, topic:editor, usability
