### ISSUE TITLE
Why am I getting this error when using ViewportTexture

### ISSUE THREAD

**Issue by shafnaz** [godotengine/godot#60496] opened 2022-04-24 18:53 UTC
### Godot version

3.4.4

### System information

Windows 10

### Issue description

Hello Godot Devs,

I'm Getting these errors.
![image](https://user-images.githubusercontent.com/37254287/164991854-4b13c125-0834-4bbe-909b-69aeca141438.png)

I have another scene setup with ViewportTexure and get no errors.

### Steps to reproduce

Open the tscn file. 
Load your custom font. 
Relink the ViewportTexture path to the Viewport.
Run that scene, and you'll see errors

### Minimal reproduction project

[card.zip](https://github.com/godotengine/godot/files/8550320/card.zip)

**Comment by Calinou** [comment] 2022-04-24 23:00
Duplicate of https://github.com/godotengine/godot/issues/16067 (and possibly others).

**Closed by Calinou** 2022-04-24 23:00 UTC
