### ISSUE TITLE
DampedSpringJoint2D Extends and Teleports Around Like Crazy?

### ISSUE THREAD

**Issue by solarane** [godotengine/godot#16922] opened 2018-02-22 13:43 UTC
**Godot version:** 3.0

**OS/device including version:** OS X 10.12.6 MacBook Air (13-inch, 2017)

**Issue description:** I was trying to create a fake soft body in Godot 3.0. I made some rigidbodies and stuck them together with DampedSpringJoint2D. When I run my game, the bodies that are connected start to jiggle and bounce around like crazy until they eventually disappear off the screen. Probably, I am doing something wrong, but what is it?

**Steps to reproduce:** Turn on Godot 3.0. Put a RigidBody2D, and several more RigidBody2D's around it. Connect the outer RigidBody2d's using DampedSpringJoint2D. Connect each of the outer RigidBody2D's to the inner RigidBody2D using a DampedSpringJoint2D. Run the game to witness chaos and destruction. 

**Minimal reproduction project:** [Soft Bodies 2D.zip](https://github.com/godotengine/godot/files/1748065/Soft.Bodies.2D.zip) << this isn't actually minimal, but it is pretty self-explanatory. If you want, I will provide a truely minimal reproduction project.

Thank you in advance.

**Comment by Calinou** [comment] 2020-06-07 19:19
I'll close this bug as physics have changed a fair bit since Godot 3.0. There are now many other reports about similar issues, such as #34398. Please create a new report if the issue is completely unrelated.

> I was trying to create a fake soft body in Godot 3.0.

Note that Godot 3.1 and later feature soft body support.

**Closed by Calinou** 2020-06-07 19:19 UTC
Labels: bug, topic:physics
