### ISSUE TITLE
Missing project when save path contains special char ']'

### ISSUE THREAD

**Issue by 3lis4** [godotengine/godot#68444] opened 2022-11-09 10:02 UTC
### Godot version

4.0 beta 3

### System information

Windows 10

### Issue description

If you create a project and save it in a path ending with "[Test]/MyProject", it will be marked as missing in the godot launching interface (projects list).
The path in the projects list is broken : "]" and every subsequent chars are missing (the path ends with "[Test"). However, the project was correctly created in the specified path ending with "[Test]/MyProject".

This issue doesn't exist in Godot 3.5.

### Steps to reproduce

1. Create a project in a path ending with "[Test]/MyProject".
2. Save it. 
3. Quit and return to projects list : the project is marked as "missing" and its path is incomplete.

**Comment by akien-mga** [comment] 2023-01-12 20:52
Duplicate of #68444

**Closed by akien-mga** 2023-01-12 20:52 UTC
Labels: bug, topic:editor, regression
