### ISSUE TITLE
Crash when opening a Scene inheriting from a changed super Scene

### ISSUE THREAD

**Issue by mrimvo** [godotengine/godot#55083] opened 2021-11-18 11:20 UTC
### Godot version

Godot Engine v4.0.dev.calinou.ed300d7be

### System information

Ubuntu 18.04

### Issue description

When opening an Inherited Scene, I get a crash with this stack trace.

```
ERROR: Node './Sleeping' was modified from inside an instance, but it has vanished.
   at: instantiate (scene/resources/packed_scene.cpp:173)

================================================================
handle_crash: Program crashed with signal 11
Engine version: Godot Engine v4.0.dev.calinou (ed300d7be536b1ec325ba77521eceee73dd0e5fb)
Dumping the backtrace. Please include this when reporting the bug on https://github.com/godotengine/godot/issues
[1] /lib/x86_64-linux-gnu/libc.so.6(+0x3f040) [0x7f98af1ce040] (??:0)
[2] Dictionary::has(Variant const&) const (??:0)
[3] Object::has_meta(StringName const&) const (??:0)
[4] /home/martin/bin/godot/godot(+0x4e9f624) [0x564bebcf4624] (??:0)
[5] SceneState::instantiate(SceneState::GenEditState) const (??:0)
[6] PackedScene::instantiate(PackedScene::GenEditState) const (??:0)
[7] EditorNode::load_scene(String const&, bool, bool, bool, bool, bool) (??:0)
[8] EditorNode::open_request(String const&) (??:0)
[9] EditorNode::_quick_opened() (??:0)
[10] void call_with_variant_args_helper<EditorNode>(EditorNode*, void (EditorNode::*)(), Variant const**, Callable::CallError&, IndexSequence<>) (??:0)
[11] void call_with_variant_args<EditorNode>(EditorNode*, void (EditorNode::*)(), Variant const**, int, Callable::CallError&) (??:0)
[12] CallableCustomMethodPointer<EditorNode>::call(Variant const**, int, Variant&, Callable::CallError&) const (??:0)
[13] Callable::call(Variant const**, int, Variant&, Callable::CallError&) const (??:0)
[14] Object::emit_signal(StringName const&, Variant const**, int) (??:0)
[15] Object::emit_signal(StringName const&, Variant const&, Variant const&, Variant const&, Variant const&, Variant const&, Variant const&, Variant const&, Variant const&) (??:0)
[16] EditorQuickOpen::_confirmed() (??:0)
[17] void call_with_variant_args_helper<EditorQuickOpen>(EditorQuickOpen*, void (EditorQuickOpen::*)(), Variant const**, Callable::CallError&, IndexSequence<>) (??:0)
[18] void call_with_variant_args<EditorQuickOpen>(EditorQuickOpen*, void (EditorQuickOpen::*)(), Variant const**, int, Callable::CallError&) (??:0)
[19] CallableCustomMethodPointer<EditorQuickOpen>::call(Variant const**, int, Variant&, Callable::CallError&) const (??:0)
[20] Callable::call(Variant const**, int, Variant&, Callable::CallError&) const (??:0)
[21] Object::emit_signal(StringName const&, Variant const**, int) (??:0)
[22] Object::emit_signal(StringName const&, Variant const&, Variant const&, Variant const&, Variant const&, Variant const&, Variant const&, Variant const&, Variant const&) (??:0)
[23] AcceptDialog::_ok_pressed() (??:0)
[24] AcceptDialog::_text_submitted(String const&) (??:0)
[25] void call_with_variant_args_helper<AcceptDialog, String const&, 0ul>(AcceptDialog*, void (AcceptDialog::*)(String const&), Variant const**, Callable::CallError&, IndexSequence<0ul>) (??:0)
[26] void call_with_variant_args<AcceptDialog, String const&>(AcceptDialog*, void (AcceptDialog::*)(String const&), Variant const**, int, Callable::CallError&) (??:0)
[27] CallableCustomMethodPointer<AcceptDialog, String const&>::call(Variant const**, int, Variant&, Callable::CallError&) const (??:0)
[28] Callable::call(Variant const**, int, Variant&, Callable::CallError&) const (??:0)
[29] Object::emit_signal(StringName const&, Variant const**, int) (??:0)
[30] Object::emit_signal(StringName const&, Variant const&, Variant const&, Variant const&, Variant const&, Variant const&, Variant const&, Variant const&, Variant const&) (??:0)
[31] LineEdit::gui_input(Ref<InputEvent> const&) (??:0)
[32] Control::_call_gui_input(Ref<InputEvent> const&) (??:0)
[33] Viewport::_gui_input_event(Ref<InputEvent>) (??:0)
[34] Viewport::push_input(Ref<InputEvent> const&, bool) (??:0)
[35] Window::_window_input(Ref<InputEvent> const&) (??:0)
[36] void call_with_variant_args_helper<Window, Ref<InputEvent> const&, 0ul>(Window*, void (Window::*)(Ref<InputEvent> const&), Variant const**, Callable::CallError&, IndexSequence<0ul>) (??:0)
[37] void call_with_variant_args<Window, Ref<InputEvent> const&>(Window*, void (Window::*)(Ref<InputEvent> const&), Variant const**, int, Callable::CallError&) (??:0)
[38] CallableCustomMethodPointer<Window, Ref<InputEvent> const&>::call(Variant const**, int, Variant&, Callable::CallError&) const (??:0)
[39] Callable::call(Variant const**, int, Variant&, Callable::CallError&) const (??:0)
[40] DisplayServerX11::_dispatch_input_event(Ref<InputEvent> const&) (??:0)
[41] DisplayServerX11::_dispatch_input_events(Ref<InputEvent> const&) (??:0)
[42] Input::_parse_input_event_impl(Ref<InputEvent> const&, bool) (??:0)
[43] Input::flush_buffered_events() (??:0)
[44] DisplayServerX11::process_events() (??:0)
[45] OS_LinuxBSD::run() (??:0)
[46] /home/martin/bin/godot/godot(main+0x168) [0x564be8fc584d] (??:0)
[47] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xe7) [0x7f98af1b0bf7] (??:0)
[48] /home/martin/bin/godot/godot(_start+0x2a) [0x564be8fc562a] (??:0)
```

### Steps to reproduce

1. dowload and open the attached project
2. remove a node from Main.tscn and save
3. open Inherited.tscn

The Editor crashes with the stack trace provided.

### Minimal reproduction project

[Crashing Inherited Scene.zip](https://github.com/godotengine/godot/files/7562333/Crashing.Inherited.Scene.zip)

**Comment by akien-mga** [comment] 2021-11-18 11:39
Duplicate of #55051

**Closed by akien-mga** 2021-11-18 11:39 UTC
Labels: bug, topic:editor, crash
