### ISSUE TITLE
set_hidden function versus the "Visible" inspector item - naming inconsistency.

### ISSUE THREAD

**Issue by Sslaxx** [godotengine/godot#5531] opened 2016-07-03 13:18 UTC
Godot 2.0.3, OS is N/A.

Looking at the inspector for (for example) the pause_panel node in the pause demo, the property for visibility is called (unsurprisingly) "Visible", set to on or off. But the function is set_hidden (as per http://docs.godotengine.org/en/latest/classes/class_canvasitem.html and other places as well). This is an inconsistency. Renaming the function to set_visible, or the inspector property to "Hidden" would be nice.

**Comment by StraToN** [comment] 2016-07-04 09:06
I guess it would be better to rename the inspector property, as changing the function name would cause old GDScript not to work anymore.

**Comment by volzhs** [comment] 2016-07-04 09:23
There is ``show()`` ``hide()`` for visibility.
And ``set_hidden`` added since #2922. see #2194 discussion too.

**Comment by bojidar-bg** [comment] 2016-07-04 09:26
What about having `set_visible` alongside `set_hidden`? :smile:

**Comment by Sslaxx** [comment] 2016-07-04 09:27
As proposed in #2194 by akien and romulox-x?

**Comment by akien-mga** [comment] 2016-07-04 10:22
Check #2194, @reduz said that the lack of `set_visible` is by design. You don't actually set the node visible by turning the visible flag on, but you make it visible **if** its parents are all visible/not hidden. So maybe it should be changed for "Hidden" in the inspector too, as with hidden there is no confusion (whether or not the parents are visible, if the node is hidden, it won't display).

**Comment by vnen** [comment] 2016-07-04 13:38
I prefer to change it in the Inspector. But that'll also break compatibility, since saved scenes would have the old property name and also if someone is using `set("visibility/visible", true)` in code.

**Comment by bojidar-bg** [comment] 2016-07-04 17:20
@vnen well, we can do as we've done before with collision layers in 3D -- add a fallback :smile:

**Comment by akien-mga** [comment] 2017-01-13 17:48
Fixed in 04c749a.

**Closed by akien-mga** 2017-01-13 17:48 UTC
Labels: discussion, feature proposal, topic:core
