### ISSUE TITLE
Unexpected crash of Godot (see description)

### ISSUE THREAD

**Issue by mdziczkowski** [godotengine/godot#75289] opened 2023-03-24 13:40 UTC
### Godot version

4.0.stable (92bee43ad)

### System information

Debian 11

### Issue description

After starting Godot (it opens the project manager), I tryed to:

- edit a imported project
- open an example project (from resource manager)

an in both cases Godot had unexpectally crashed as soon as I did that

Any ideas ?

### Steps to reproduce

1. Start Godot (it should open the project manager)
2. Import a project or try to open some of the examples from the resource library (you need to have enabled the support for the community and testing)
3. Try to edit the item from point 2
4. See Godot crashing

### Minimal reproduction project

n/a

**Comment by Calinou** [comment] 2023-03-24 18:28
What graphics card model do you have? If it doesn't support Vulkan, this is a duplicate of https://github.com/godotengine/godot/issues/58927.

**Comment by Calinou** [comment] 2023-04-29 22:15
> As for the graphic card, it's: ATI Wrestler [Radeon HD 6290]

This GPU is too old to run OpenGL 3.3 correctly. I recommend sticking to Godot 3.x's GLES2 renderer.

**Closed** 2023-04-29 23:41 UTC
Labels: topic:editor, needs testing
