### ISSUE TITLE
When Texture mode is set to Video RAM, Mipmaps setting is not respected

### ISSUE THREAD

**Issue by bfloch** [godotengine/godot#16079] opened 2018-01-26 07:59 UTC
**Godot version:**

3.0 4700f2d79

**OS/device including version:**

Fedora 27
Linux 4.14.14-300.fc27.x86_64
Nvidia Geforce GTX 1050 (mobile) Driver 384.111

**Issue description:**

In a textures import options following is set:
- mode - video ram
- detect 3d - false
- mipmap - false
The resulting texture will always contain a mipmap.

**Is this a limitation of the texture format? Should this be communicated via message?**

![issue_mipmaps](https://user-images.githubusercontent.com/2116566/35430047-9791c91e-0244-11e8-9a93-ea5d33d954e3.gif)

**Steps to reproduce:**
In the test project:
- Select a png.
- In the Import options toggle "Lossles" or "Video Ram"
- Mipmaps should be disabled
- Select any note in the tree (to update the node inspector)
- Double click the png in the file navigator to pop up the texture in the inspector.
- You will find that it always has a mipmap in Video Ram mode, regardless of the Mipmap setting during import

**Minimal reproduction project:**

[issue_vieport_sampling_ok.zip](https://github.com/godotengine/godot/files/1667014/issue_vieport_sampling_ok.zip)

**Comment by Zireael07** [comment] 2018-02-04 18:02
Running into this one as well, I have to use "Uncompressed" to avoid the problem.

**Comment by playster000** [comment] 2018-03-01 19:30
according to the source:
`if (p_mipmaps || p_compress_mode == COMPRESS_VIDEO_RAM) //VRAM always uses mipmaps
		format |= StreamTexture::FORMAT_BIT_HAS_MIPMAPS; //mipmaps bit`
editor\import\resource_importer_texture.cpp line 223

**Comment by Zireael07** [comment] 2018-03-01 19:43
That's really weird...

**Comment by bfloch** [comment] 2018-03-02 06:48
Good find @playster000  I tracked it down to
https://github.com/godotengine/godot/commit/2cd2ca7bbc892eccc635b1c4aea80c956c9b92dc#diff-76b5a5798da421c090ea0b7cc9ebf7ceR87

@reduz could you shed some light on this? Is it still necessary?

**Comment by aaronfranke** [comment] 2018-07-31 03:29
@bfloch @reduz And if it is necessary, the fix is to not allow disabling Mipmap when using VRAM textures.

**Comment by reduz** [comment] 2018-09-06 18:13
Yeah, GLES2/WebGL does not support compression without mipmaps. I can make the option disappear when VRAM is selected I guess?

**Comment by Zireael07** [comment] 2018-09-06 18:28
This is a duplicate of #10221, and if it's a GLES limitation then the mipmap toggle should definitely disappear to avoid confusing people.

**Comment by akien-mga** [comment] 2018-09-10 08:17
Closing as duplicate of #10221.

**Closed by akien-mga** 2018-09-10 08:17 UTC
Labels: bug, topic:editor
