### ISSUE TITLE
GDScript: Cannot call functions of PoolByteArray object when it is stored in a normal array

### ISSUE THREAD

**Issue by puthre** [godotengine/godot#29772] opened 2019-06-14 08:32 UTC
V3.1.1.stable.official

Linux Ubuntu 18.04.2 LTS

The following code should print "1", but it prints "0"

    var b = []
    b.append(PoolByteArray([0,0]))
    b[0].insert(0,1)
    #b[0][0] = 1 #this however works if uncommented
    print(b[0][0])

This does not only happen when calling insert but any other function call to the BoolByteArray object fails silently. 

**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by akien-mga** [comment] 2020-01-18 14:21
Duplicate of #15265.

**Closed by akien-mga** 2020-01-18 14:21 UTC
Labels: bug, topic:core
