### ISSUE TITLE
Animation window not refreshing when new tracks are added.

### ISSUE THREAD

**Issue by bflanagin** [godotengine/godot#26727] opened 2019-03-06 19:41 UTC
**Godot version:**
Godot 3.1 beta 11

**OS/device including version:**
Pop!_OS 18.10 Linux 4.18.0-15-generic
Nvidia (proprietary driver) 410.78

**Issue description:**
When adding a track to an animation via the Inspector the track doesn't appear in the Animation view until you select the AnimationPlayer Node again.

I believe this is a regression in the newest beta as the tracks in the Animation window updated automatically until now.  

**Steps to reproduce:**

Add an AnimationPlayer node 
Add a new animation
Use the inspector to add a track and key of the node and setting you want to be affected in the animation. 
(nothing shows in animation player window)
Click on the animationPlayer Node in the node tree
(now the track appears)

**Minimal reproduction project:**

**Comment by volzhs** [comment] 2019-03-06 19:49
duplicate of #26670 and fixed by 9b5c6f5

**Closed by volzhs** 2019-03-06 19:49 UTC
