### ISSUE TITLE
Chrome version 126 and 127 breaks web exports for version 3.6 beta 5 down to 3.4 beta 5, and Godot 4.3-dev

### ISSUE THREAD

**Issue by Lortemanden** [godotengine/godot#93314] opened 2024-06-18 16:13 UTC
### Tested versions

- Reproduced in 3.6 beta 5 down to 3.4 beta 5
- It works in godot 4.2 and 3.4 beta 4

### System information

Windows 10 godot 3.4 beta 5, chrome 126

### Issue description

When trying to launch the game via a web export it fails to find the pck file even though it gets downloaded, which makes the game crash. This just started to be a problem when the newest version of chrome was launched, version 126, and is only a problem with godot version 3.4 beta 5 and up. 

The video show the error when trying to launch the MRP as a http server, which is shown in the first video.

https://github.com/godotengine/godot/assets/55434783/c54f57eb-89d0-4187-bcfb-c310ddc8c982

The problem also persists when trying to play godot games on the browser with a low-end computer. In the second video I use a virtual machine with 4 gb ram and 2 cpu's to play some godot games on [itch.io](https://itch.io/games/platform-web/tag-godot-engine) but they all give the same error. If I use godot version 3.4 beta 4 to compile a game for my low-end virtual machine to run it works fine even when embedded into a website.I run through the games in the video since it is only allowed to be 10 mb but while they show different error messages, they all print the same error to the console about not being able to load the pck. 

https://github.com/godotengine/godot/assets/55434783/1c70db85-7feb-4fe4-b772-8f4f2e6f9eb1

### Steps to reproduce

1. Set chrome 126 as the browser used for godot when launching remote debug
2. use godot 3.4 beta 5 or higher
3. Click remote debug

### Minimal reproduction project (MRP)

[chrome_test.zip](https://github.com/user-attachments/files/15889485/chrome_test.zip)

**Comment by akien-mga** [comment] 2024-06-18 16:23
Confirmed with a few Godot 3 projects I have uploaded:
- 3.2.3.stable (works): https://fry.itch.io/moon-dragoon
- 3.5.1.stable (broken): https://akien.itch.io/jetpaca
- 3.5.3.stable (broken): https://akien.itch.io/dynadungeons

Weirdly enough, if I try to launch the game while the developer console is enabled, it loads fine... great for debugging.

**Comment by akien-mga** [comment] 2024-06-18 16:28
Actually I can also reproduce the problem with Godot 4.3-dev exports:

- v4.3.dev.custom_build 1da02fa7b (2024-04-24 09:55:55 UTC) (broken): https://bliznyuknm.itch.io/hell-of-mirrors
- Same version (broken): https://akien.itch.io/godog

**Comment by Lortemanden** [comment] 2024-06-18 19:09
If you have the devtools open while reloading the page the problem is gone for some reason

**Comment by adamscott** [comment] 2024-06-18 19:15
I reported the problem on the Chromium Issue tracker: https://issues.chromium.org/issues/347905990

**Comment by akien-mga** [comment] 2024-06-18 19:54
Some more testing on Linux (Fedora 40):

- Reproducible in Chrome 126.0.6478.61 (Official Build) and 126.0.6478.114 (Official Build) (Google RPM `google-chrome-stable-126.0.6478.114-1.x86_64`)
- *Not* reproducible in Chromium 126.0.6478.55 (Fedora RPM `chromium-126.0.6478.55-1.fc40.x86_64`)

On Twitter I'm seeing reports of people with Chrome 126.0.6478.61 on Windows and Chrome 126.0.6478.114 on Ubuntu who do *not* reproduce the bug. Seems pretty hit and miss, might be some race condition.

**Comment by matheusmdx** [comment] 2024-06-18 20:09
I'm using google chrome 126.0.6478.115 and godot web games is working fine on my side

Godot v4.2.2.stable - Windows 10.0.19045 - GLES3 (Compatibility) - AMD Radeon RX 580 2048SP (Advanced Micro Devices, Inc.; 31.0.21912.14) - AMD Ryzen 5 3600 6-Core Processor (12 Threads)


https://github.com/godotengine/godot/assets/44306054/5511d374-a077-4757-ad1e-0a1bad90b453

**Comment by akien-mga** [comment] 2024-06-18 20:49
From the upstream bug report, it seems the bug is caused by an active experiment in the stable branch:

> Can you also try launching chrome with `--disable-features=WebAssemblyTurboshaft` (Note you need to fully quit chrome when setting these command line args).

This solves the issue for both myself and @adamscott.

**Comment by matheusmdx** [comment] 2024-06-18 20:59
I can confirm opening chrome with `--enable-features=WebAssemblyTurboshaft` make the bug happens with me too

**Comment by Lortemanden** [comment] 2024-06-18 21:11
I can also confirm opening chrome with --enable-features=WebAssemblyTurboshaft enables the bug. It works fine when it is disabled.

**Comment by dtapuska** [comment] 2024-06-18 21:23
The experiment was disabled. So you should be able to just relaunch Chrome(might take a little while to propagate).

**Comment by akien-mga** [comment] 2024-06-18 21:48
@dtapuska Thanks for the help debugging and solving the issue upstream!

**Comment by akien-mga** [comment] 2024-06-20 14:03
I confirm it fixed on my end with Google Chrome updates on Fedora 40 and Android.

**Closed by akien-mga** 2024-06-20 14:03 UTC
Labels: bug, platform:web, topic:porting, topic:thirdparty, high priority, regression
