### ISSUE TITLE
Meta+A in a text field of the property inspector opens the "Create New Node" menu

### ISSUE THREAD

**Issue by philiplb** [godotengine/godot#1372] opened 2015-02-15 22:27 UTC
When I edit a button caption or a label text with the property inspector and I hit Meta+A (here on OS X it is CMD+A), the "Create New Node" menu pops up.
What I expected: select all text in the field I currently edit.

**Comment by akien-mga** [comment] 2015-11-18 08:51
Duplicate of #1094 and will be fixed by #2747.

**Closed by akien-mga** 2015-11-18 08:51 UTC
Labels: archived
