### ISSUE TITLE
Broke nvidia drivers on Sponza demo

### ISSUE THREAD

**Issue by CereEnder** [godotengine/godot#16065] opened 2018-01-25 16:51 UTC
When I play the Sponza demo at windowed mode, first play works well. 
But, if I change world environment param as SSAO or reflections, second time froze/break my Nvidia drivers. And I have to force alt+F4 or shutdown the laptop entirely.

Godot 3.0 RC 3 (not mono) 

Win 10 win64

Nvidia 1050 Ti

this is the log I generate:
```
OpenGL ES 3.0 Renderer: GeForce GTX 1050 Ti/PCIe/SSE2
GLES3: max ubo light: 409
GLES3: max ubo reflections: 455, ubo size: 144
ARVR: Registered interface: Native mobile
OPENING: C:/Users/Cere/Downloads/godot-v3.0-win64.exe/godot-sponza-master (C:::Users::Cere::Downloads::godot-v3.0-win64.exe::godot-sponza-master)
running cmdline: "C:\Users\Cere\Downloads\Godot_v3.0-rc2_win64.exe\Godot_v3.0-rc2_win64.exe" "--path" "C:/Users/Cere/Downloads/godot-v3.0-win64.exe/godot-sponza-master" "--editor"
OpenGL ES 3.0 Renderer: GeForce GTX 1050 Ti/PCIe/SSE2
GLES3: max ubo light: 409
GLES3: max ubo reflections: 455, ubo size: 144
ARVR: Registered interface: Native mobile
erasing C:\Users\Cere\AppData\Roaming/Godot/projects/godot-sponza-master-96b19c89119200cf4a549d77932d1aa8/filesystem_update3
Running: C:\Users\Cere\Downloads\Godot_v3.0-rc2_win64.exe\Godot_v3.0-rc2_win64.exe --path C:/Users/Cere/Downloads/godot-v3.0-win64.exe/godot-sponza-master --remote-debug 127.0.0.1:6007 --allow_focus_steal_pid 39284 --position 320,180 res://scenes/sponza.scn
running cmdline: "C:\Users\Cere\Downloads\Godot_v3.0-rc2_win64.exe\Godot_v3.0-rc2_win64.exe" "--path" "C:/Users/Cere/Downloads/godot-v3.0-win64.exe/godot-sponza-master" "--remote-debug" "127.0.0.1:6007" "--allow_focus_steal_pid" "39284" "--position" "320,180" "res://scenes/sponza.scn"
OpenGL ES 3.0 Renderer: GeForce GTX 1050 Ti/PCIe/SSE2
GLES3: max ubo light: 409
GLES3: max ubo reflections: 455, ubo size: 144
ARVR: Registered interface: Native mobile
Running: C:\Users\Cere\Downloads\Godot_v3.0-rc2_win64.exe\Godot_v3.0-rc2_win64.exe --path C:/Users/Cere/Downloads/godot-v3.0-win64.exe/godot-sponza-master --remote-debug 127.0.0.1:6007 --allow_focus_steal_pid 39284 --position 320,180 res://scenes/sponza.scn
running cmdline: "C:\Users\Cere\Downloads\Godot_v3.0-rc2_win64.exe\Godot_v3.0-rc2_win64.exe" "--path" "C:/Users/Cere/Downloads/godot-v3.0-win64.exe/godot-sponza-master" "--remote-debug" "127.0.0.1:6007" "--allow_focus_steal_pid" "39284" "--position" "320,180" "res://scenes/sponza.scn"
OpenGL ES 3.0 Renderer: GeForce GTX 1050 Ti/PCIe/SSE2
GLES3: max ubo light: 409
GLES3: max ubo reflections: 455, ubo size: 144
ARVR: Registered interface: Native mobile
WARNING: ObjectDB::cleanup: ObjectDB Instances still exist!
     At: core\object.cpp:1989


```

**Comment by CereEnder** [comment] 2018-01-30 10:25
Still on stable release

**Comment by reduz** [comment] 2018-09-06 18:11
I am not quite sure what may be the cause, as this is pretty impossible to debug/reproduce.
does it still happen with more recent drivers?

**Comment by CereEnder** [comment] 2018-09-09 08:07
Hello Reduz, sorry for the delay.

Now I didn't have the PC were this error happens anymore.
But I'll try in my new laptop.

Maybe you should close this if is a minor or not quite foundable bug.
Thank you for you work.

**Comment by akien-mga** [comment] 2018-09-10 21:06
Closing for now, but if you can reproduce it again with new hardware, feel free to leave a comment so that it can be reopened.

**Closed by akien-mga** 2018-09-10 21:06 UTC
Labels: bug, topic:core
