### ISSUE TITLE
A TileMap layer with y_sort enabled becomes unmodulated

### ISSUE THREAD

**Issue by Monkstar** [godotengine/godot#73848] opened 2023-02-23 23:00 UTC
### Godot version

4.0 RC3

### System information

Windows 10, Vulkan API 1.3.224 - Forward+ - Using Vulkan Device #0: NVIDIA - NVIDIA GeForce RTX 3060

### Issue description

When I have a modulated TileMap layer (where the TileMap itself also has Y-Sort enabled), and enable y_sort for it, the layer behaves as if it is unmodulated (full non-transparent white).

### Steps to reproduce

Create a TileMap scene
Enable Y-Sort for the TileMap itself
add a TileSet with a tile
place a tile on the TileMap
Modulate the layer containing the tile to some color
enable Y-Sort for that layer, and see how the color of the tile goes back to normal

### Minimal reproduction project

[BugProject.zip](https://github.com/godotengine/godot/files/10819209/BugProject.zip)

**Comment by KoBeWi** [comment] 2023-02-23 23:28
Duplicate of #63994

**Closed by KoBeWi** 2023-02-23 23:28 UTC
