### ISSUE TITLE
Light2D Mask Mode works correctly only when there is one light2d

### ISSUE THREAD

**Issue by zhagsenkk** [godotengine/godot#22981] opened 2018-10-13 11:11 UTC
**Godot version:**
3.1 alpha

**OS/device including version:**
win10,gtx 760

**Issue description:**
Light2D Mask Mode works only when there is one light2d. if there are two light2d, both will not work correctly. 

**Steps to reproduce:**
1.activity both light2d node in the minimal reproduction project.

**Minimal reproduction project:**
[light2d_as_mask.zip](https://github.com/godotengine/godot/files/2475384/light2d_as_mask.zip)

**Comment by avencherus** [comment] 2018-10-13 11:37
Confirmed this on Win10 64-bit 3.1 fe0db6c4797b8094c64e4ad017e29be866288628

**Comment by zhagsenkk** [comment] 2018-10-22 12:13
related to #8685

**Comment by henriiquecampos** [comment] 2019-05-31 17:52
Confirmed on 3.1.1 official.

![bug-report](https://user-images.githubusercontent.com/10171059/58724693-aa3cb280-83b3-11e9-99c1-8db2be447b6c.gif)

**Comment by akien-mga** [comment] 2019-11-26 11:55
Duplicate of #8685.

**Closed by akien-mga** 2019-11-26 11:55 UTC
Labels: bug, topic:rendering
