### ISSUE TITLE
debugger line number broken by """ style comments 

### ISSUE THREAD

**Issue by romulox-x** [godotengine/godot#929] opened 2014-12-06 02:16 UTC
After a block of """ style commented lines, the debugger won't report the correct line number of an error.  Add the number of commented lines to the reported line, and that's the correct line.  If I take out the block, the line is reported correctly.

**Comment by vnen** [comment] 2015-10-29 21:57
I'm closing this, because GDScript does not have multiline comments. The triple-quote token (""") is used for multiline strings.

**Closed by vnen** 2015-10-29 21:57 UTC
Labels: archived

**Comment by akien-mga** [comment] 2015-10-29 22:26
Actually closing as a duplicate of #1320, I'm not entirely convinced that GDScript does not support multiline comments, as they seem to work fine as function description (Python style).
