### ISSUE TITLE
Ability to save visual scripts as text (tvs file)

### ISSUE THREAD

**Issue by MirceaKitsune** [godotengine/godot#16837] opened 2018-02-19 23:15 UTC
When saving a visual script, your only option is the vs extension. This results in a binary file which isn't readable from a text editor. With other resources, you're given the option to choose between text and binary (eg: res vs tres, scn vs tscn). I'd be grateful if the extension tvs could be supported, allowing developers to save VisualScript scripts as text which can be modified using text editors if needed.

**Comment by akien-mga** [comment] 2018-02-19 23:20
Thanks for the proposal - it's a duplicate of #16023, so closing it to keep discussions in the same place.

**Closed by akien-mga** 2018-02-19 23:20 UTC
