### ISSUE TITLE
Unlisted Shortcut Control+Shift+Return

### ISSUE THREAD

**Issue by alexporth** [godotengine/godot#41305] opened 2020-08-16 07:52 UTC
**Godot version:**
3.2.2

**OS/device including version:**
Windows 10 1909

**Issue description:**
I have the habit of hitting Control+Shift+Return from using Jetbrains IDEs, where that is the shortcut for the Auto-Complete line feature. Every time I use this combination in the Godot Script Text Editor, it creates a newline before the line I was editing and moves my cursor to that newly created line. I tried to find the shortcut that does this in the Editor Settings, so I could disable it, but there doesn't seem to be one listed.

**Steps to reproduce:**
Press Control+Shift+Return while in the Script Text Editor.
Look for shortcut in Editor Setting - Shortcuts.

**Minimal reproduction project:**
Any

**Comment by Calinou** [comment] 2020-08-27 14:42
I believe that shortcut is an hardcoded feature in TextEdit.

We could swap the behavior so it behaves like JetBrains IDEs, but I think we chose to follow the current behavior because it matches VS Code's behavior more closely.

**Comment by alexporth** [comment] 2020-08-29 07:32
I don't think that this is a bad shortcut to have. I also understand why this behavior was chosen. I just think that it should be configurable, like all the others. I haven't come across any other shortcuts that aren't configurable, so I don't understand why this is an exception.

**Comment by Calinou** [comment] 2020-08-29 13:28
> I just think that it should be configurable, like all the others. I haven't come across any other shortcuts that aren't configurable, so I don't understand why this is an exception.

Unfortunately, making shortcuts configurable if they're also exposed to exported projects is difficult since [we don't want to add more `editor/` dependencies in `scene/` classes](https://github.com/godotengine/godot/issues/29730).

**Comment by alexporth** [comment] 2020-08-30 07:26
I see, sorry for not understanding what you meant by your first comment. Just started working with Godot. Thanks for clearing things up for me. Should I close the Issue?

**Comment by Calinou** [comment] 2020-08-30 12:22
@alexporth If you think it's still important to support this (for the Godot community at large), you could open a proposal on the [Godot proposals](https://github.com/godotengine/godot-proposals/) repository.

Otherwise, I'll close this issue as it's not a bug per se.

**Comment by EricEzaM** [comment] 2020-09-17 06:04
Ping @Calinou

**Closed** 2020-09-17 09:52 UTC
Labels: confirmed, topic:editor, usability
