### ISSUE TITLE
Clicking on holding the increment/decrement arrows could change the value continuously.

### ISSUE THREAD

**Issue by zhagsenkk** [godotengine/godot#2296] opened 2015-07-23 11:35 UTC
Arrow is the white up/down Arrow behind the variable.Editing the number should be more convenient.
More thing to do,the step of variable's change can be set up.

**Comment by jackmakesthings** [comment] 2015-08-03 21:33
+1. 
And while we're looking at that, it'd be great if the up/down keyboard arrows could be used to increment number fields, as an alternative to using the little white arrows in question. Bonus points if you can then make Shift+arrow key = increment by 10.

**Comment by reduz** [comment] 2015-08-03 22:25
yes, will hopefully work on this soon

**Comment by akien-mga** [comment] 2015-12-16 10:50
I believe this was a duplicate of #868, which has been fixed in #3019.

**Closed by akien-mga** 2015-12-16 10:50 UTC
Labels: enhancement, topic:editor, usability
