### ISSUE TITLE
Curve3d editing is wrong (coordinates are messed) with 'half-resolution' enabled

### ISSUE THREAD

**Issue by eggnot** [godotengine/godot#54624] opened 2021-11-05 09:56 UTC
### Godot version

3.3.4 stable, 3.4-rc3, etc.

### System information

windows 10, Gles2, Gles3, etc.

### Issue description

with `Half Resolution` enabled editing `Path` (Curve3d) in editor makes points appear far off

![curve3d_half_resolution](https://user-images.githubusercontent.com/5466961/140491942-db23395a-e1cb-4f7d-960e-460672343099.jpg)

### Steps to reproduce

- change view to `Half Resolution`
- add `Path` node
- add or edit point

### Minimal reproduction project

[path_wrong_points.zip](https://github.com/godotengine/godot/files/7482124/path_wrong_points.zip)

**Comment by timothyqiu** [comment] 2021-11-05 12:09
Possible duplicate of #41586

**Comment by Calinou** [comment] 2021-11-05 14:52
Duplicate of https://github.com/godotengine/godot/issues/41586 (same cause).

**Closed by Calinou** 2021-11-05 14:52 UTC
Labels: bug, topic:editor
