### ISSUE TITLE
Polymorphism doesn't work on a typed arrays

### ISSUE THREAD

**Issue by GitHubPiotr** [godotengine/godot#93084] opened 2024-06-12 12:17 UTC
### Tested versions

Tested on Godot 4.3beta1

### System information

Windows 10, Forward+

### Issue description

I noticed that polymorphism doesn't work on arrays of a specific type. Example below

### Steps to reproduce

1. Create new scene and attach a script
2. In the script create two new empty classes. Extend the second class by the first class
![t1](https://github.com/godotengine/godot/assets/60047367/e850238c-3846-452f-a1e2-ef3b62e69cb8)
3.  In _ready() function create variable of Array[*Class that extends another class*]
![t3](https://github.com/godotengine/godot/assets/60047367/720f25ae-735a-4588-bb93-f623f05fb2f5)
4.  Create another variable of Array[*Your primary class*] and assign it with variable from step 3
![t4](https://github.com/godotengine/godot/assets/60047367/15bb1559-61d6-4427-8621-af491e3c2738)
5. Done. You getting a compiler error
![t2](https://github.com/godotengine/godot/assets/60047367/75154d48-6856-40c9-bdef-2b89a852e6d2)

### Minimal reproduction project (MRP)

[test.zip](https://github.com/user-attachments/files/15804502/test.zip)

**Comment by AThousandShips** [comment] 2024-06-12 12:20
This is a current limitation, please see:
* https://github.com/godotengine/godot-proposals/discussions/7364

**Comment by dalexeev** [comment] 2024-06-12 16:28
Duplicate of:

* #80586
* #83876
* #89959
* #93063

See:

* [GDScript reference - Typed arrays](https://docs.godotengine.org/en/latest/tutorials/scripting/gdscript/gdscript_basics.html#typed-arrays)
* godotengine/godot-proposals#7364

![](https://github.com/godotengine/godot/assets/47700418/f75cea69-5544-40df-b111-f798cdb32901)

This is not a bug. Arrays are passed by reference; they do not copy the entire content. Otherwise you would get:

```gdscript
var a: Array[Node2D]
var b: Array[Node]
b = a # Now `b` refers to the same array as `a`.
b.append(Label.new()) # Valid, `Label` is a subtype of `Node`.
print(a[0]) # Invalid, `Label` is **not** a subtype of `Node2D`.
```

Probably the only way this would work is if the GDScript supported [`read`/`write` qualifiers](https://github.com/godotengine/godot-proposals/discussions/7364#discussioncomment-6576975). But it's too difficult.

Thanks for the contribution nonetheless!

**Closed by dalexeev** 2024-06-12 16:28 UTC
