### ISSUE TITLE
Godot loses all editor/project manager data when quitting to project.

### ISSUE THREAD

**Issue by IntangibleMatter** [godotengine/godot#61622] opened 2022-06-02 06:28 UTC
### Godot version

3.4.2.stable

### System information

Windows 10

### Issue description

```ERROR: Cannot open file 'C:/Users/Owner/AppData/Roaming/Godot/editor_settings-3.tres'.
   at: (scene/resources/resource_format_text.cpp:1183)
ERROR: Failed loading resource: C:/Users/Owner/AppData/Roaming/Godot/editor_settings-3.tres. Make sure resources have been imported by opening the project in the editor at least once.
   at: (core/io/resource_loader.cpp:270)
WARNING: Could not open config file.
     at: create (editor/editor_settings.cpp:952)
```

This pops up in the Godot terminal windows when quitting to project menu sometimes. It erases all editor settings, game locations, and other data used by the editor. It happens without warning

### Steps to reproduce

Quit to project manager from the godot editor, I guess? This affects me rather inconsistently but it's happened twice this week. Didn't change anything with settings or editor files, just started using the quit to project manager option.

**Comment by Zireael07** [comment] 2022-06-02 06:30
I had a similar issue. Roughly half a year later, my SSD failed.

**Comment by Calinou** [comment] 2022-06-02 14:45
Duplicate of https://github.com/godotengine/godot/issues/40968.

**Closed by Calinou** 2022-06-02 14:45 UTC
