### ISSUE TITLE
OS.window_size Buggy After OS.set_borderless_window(false) in a Borderless Project

### ISSUE THREAD

**Issue by RubrumExPlaneta** [godotengine/godot#18815] opened 2018-05-12 15:18 UTC
**Godot version:** v3.0.2.stable.official

**OS/device including version:** Windows 8.1

**Issue description:**
**What happened:**
1. I set the game to be borderless, to achieve a elegant, borderless splash screen.
2. I set a timer to 0.35 seconds and, on timeout, resized, centered and set borderless to false.
3. OS.window_size is the size of the window including the border.

**What was expected:**
1. I set the game to have a border.
2. I resize the window.
3. OS.window_size is the size of the window including the border.

**Steps to reproduce:**
Open Godot v3.0.2.stable.official. Set it to be borderless. Create a scene and a node. Set the node to run this script:

```python
extends Node

func _ready():
	OS.set_borderless_window(false)
	OS.set_borderless_window(true)
	OS.set_borderless_window(false)
	
	OS.window_size = Vector2(640, 480)
	OS.center_window()
```

Create a ColorRect. Set its size to 640, 680.

Now, run the game and resize the window to see that a part of the ColorRect is outside the initial window frame,

**Minimal reproduction project:** [Test Project.zip](https://github.com/godotengine/godot/files/1997710/Test.Project.zip)

**Comment by guilhermefelipecgs** [comment] 2018-05-23 16:34
Duplicate of #18877.

**Comment by mhilbrunner** [comment] 2018-05-23 16:38
Closing as duplicate of https://github.com/godotengine/godot/issues/18877 and https://github.com/godotengine/godot/issues/19033 - both should be fixedby https://github.com/godotengine/godot/pull/19070 in current master and recent daily builds.

**Closed by mhilbrunner** 2018-05-23 16:38 UTC
