### ISSUE TITLE
Editor regular randomly freezes

### ISSUE THREAD

**Issue by RodrigoMedeirosRS** [godotengine/godot#28704] opened 2019-05-05 14:53 UTC
Godot version: 3.1.1 - Steam Version

OS: Ubuntu  18.04
APU: A10 7890k
GPU: R7 250 (off board)
RAM  16gb
Driver: AMD® Verde

Issue description: 
After i upgrade to 3.1.1, several times when i change some thing (in any kind of change, like code writing, meterial editing, moving things on scene, etc) the editor freezes for few seconds (on rare occasions he staying freezing). 

Steps to reproduce:
The error don't show a pattern, he occour's ramdonly when i change something, with some regularity.

Note: I am using a 3.1.0 upgraded project.

**Comment by Calinou** [comment] 2019-05-05 15:56
Does this occur with other 3D programs such as Blender or games?

**Comment by RodrigoMedeirosRS** [comment] 2019-05-05 16:21
No, only on Godot 3.1.1, and into Godot 3.1.0 or previous versions this bug as never occour.

**Comment by akien-mga** [comment] 2019-05-06 08:51
> No, only on Godot 3.1.1, and into Godot 3.1.0 or previous versions this bug as never occour.

Does it freeze if you go back to using Godot 3.1-stable?
The problem might be related to a system upgrade and only happened around the time you upgraded to Godot 3.1.1, but if it's actually a 3.1.1 regression, that should help narrow down the problematic change.

**Comment by vtaepe** [comment] 2019-05-06 10:17
Not sure if the same thing but script editor freezes for me as well. Very often and I have to kill the process. Occurs for both 3.1 and 3.1.1, 3.0 was fine.

Ubuntu 18.04 x64
Lenovo ideapad 100
Intel Pentium N3540
4 GB RAM

**Comment by leandrodreamer** [comment] 2019-05-06 15:23
"Not sure if the same thing but script editor freezes for me as well. Very often and I have to kill the process. "
That happen to me in 3.1 and 3.1.1 a lot, but it fixes if i press the computer power button to make the shutdown message appear, then i cancel it and godot is back

**Comment by vtaepe** [comment] 2019-05-07 22:09
Thanks, will give it a try next time. Not sure it's something one wants to put in user manual though :)

**Comment by sergiocanram** [comment] 2019-10-01 10:25
Hello, 

This issue is happening to me too, Godot randomly freezes  and I have to close it 

My system is Windows 10 and I am using Godot_v3.1.1-stable_mono_win64 (I'm not sure about the stable part)

I am now a bit paranoid and working with godot has become a continued saving on every minute, 

Does anyone have a solution for this, other than downgrading the Godot version?

**Comment by akien-mga** [comment] 2020-01-03 08:20
Duplicate of #27669.

**Closed by akien-mga** 2020-01-03 08:20 UTC
Labels: bug, topic:editor
