### ISSUE TITLE
In-scene scripts with parse errors do not get saved before scene playing

### ISSUE THREAD

**Issue by WalasPrime** [godotengine/godot#5424] opened 2016-06-26 09:48 UTC
Windows 10  64bit, Godot 2.0.x **except** 2.0.1

Scripts saved in-scene are not saved after a parse error. Issue appeared in 2.0.2.

**Steps to reproduce:**
1. Create a scene, make a node of any kind, attach an in-scene script (Script property)
2. Add some valid code
```
func _ready():
    pass
func somefunc():
    pass
```
3. Press the Play current scene button. No errors should happen.
4. Cause a syntax error in the code (for example remove ```pass``` with the indentation)
5. Press the Play current scene button, a parse error should appear
6. Fix the error (or just ctrl+z)
7. Press the Play current scene button, a parse error appears indicating the script was not saved

**Workaround:**
To force save - press Play current scene in the scene editor (first click on any node to return to the scene view).

Fun fact:
If you create a script with only ```func _ready():``` with no newlines there are no parsing errors.

**Comment by akien-mga** [comment] 2016-06-26 09:54
Could you check if the issue is still valid in the current master branch too, or if it's a regression specific to 2.0.2+?

**Comment by WalasPrime** [comment] 2016-06-26 12:23
Unfortunately latest master is crashing on my system... Checked with official binaries for 2.0.2 2.0.3 and 2.0.4 shared on the fb group, happens there.

**Comment by WalasPrime** [comment] 2016-07-02 08:15
Managed to test this on the newest branch. When trying to press Play after the parse error is fixed a window appears with an error "file access denied" with the scene filename path (same after CTRL+S). My guess is - after a parse error godot does not shut down the executable, therefore current scene is locked for writing, fixes cannot be saved. Workaround: manually stop execution (stop button) and press Play current scene again.

**Comment by reduz** [comment] 2016-07-07 02:53
I can't reproduce this, also your last post seems like a different issue, so if you feel this one is closed, please close it and report a new one with proper steps to reproduce

**Comment by WalasPrime** [comment] 2016-07-07 07:51
Well, the modified script is still not saved, just an error window appears.Checked just now, still can reproduce.
Here's a scene package just in case.
[scriptsave_bug.zip](https://github.com/godotengine/godot/files/351606/scriptsave_bug.zip)

1. Open the project
2. Open the script in the Node2D
3. Notice the syntax error
4. Start the scene with "Play the edited scene" button
5. Obviously there's a runtime error, now fix the syntax error by adding ```pass``` in the right place
6. Press "Play the edited scene" again (now has an arrow icon)
7. (the bug) Old script is still ran on 2.0.2+, on current master additionaly an error window appears saying "file in use, locked or lacking permissions"

**Comment by WalasPrime** [comment] 2016-07-13 10:31
Fixed in 2.1-beta official binaries.

**Closed** 2016-07-13 10:31 UTC
Labels: bug, topic:editor
