### ISSUE TITLE
Latest master won't build under GCC if target "release_debug" is chosen

### ISSUE THREAD

**Issue by lightspot21** [godotengine/godot#39929] opened 2020-06-28 23:11 UTC
**Godot version:**

Git, commit `481151be0`

**OS/device including version:**

Manjaro 20.0.3, Intel® UHD Graphics

**Issue description:**
Attempting to build latest master (as of this issue `481151be0`) under GCC 10.1.0 with `target=release_debug` fails with warnings as errors about possibly uninitialized variables. Errors seem to involve the Vulkan rendering device. Building with `target=debug` doesn't show any errors.

**Steps to reproduce:**
I used the following command to atttempt building:
`scons -j6 platform=linuxbsd tools=yes target=release_debug`

**Minimal reproduction project:**
Not applicable. Compiler error trace follows:
```
[Initial build] Compiling ==> editor/editor_feature_profile.cpp
[Initial build] Compiling ==> editor/editor_file_dialog.cpp
In file included from ./core/ustring.h:35,
                 from ./core/string_name.h:36,
                 from ./core/node_path.h:34,
                 from ./core/hashfuncs.h:36,
                 from ./core/oa_hash_map.h:34,
                 from drivers/vulkan/rendering_device_vulkan.h:34,
                 from drivers/vulkan/rendering_device_vulkan.cpp:31:
./core/cowdata.h: In member function 'VkRenderPass_T* RenderingDeviceVulkan::_render_pass_create(const Vector<RenderingDevice::AttachmentFormat>&, RenderingDevice::InitialAction, RenderingDevice::FinalAction, RenderingDevice::InitialAction, RenderingDevice::FinalAction, int*)':
./core/cowdata.h:141:3: error: '*((void*)& description +32)' may be used uninitialized in this function [-Werror=maybe-uninitialized]
  141 |   _get_data()[p_index] = p_elem;
      |   ^~~~~~~~~
drivers/vulkan/rendering_device_vulkan.cpp:2995:27: note: '*((void*)& description +32)' was declared here
 2995 |   VkAttachmentDescription description;
      |                           ^~~~~~~~~~~
In file included from ./core/ustring.h:35,
                 from ./core/string_name.h:36,
                 from ./core/node_path.h:34,
                 from ./core/hashfuncs.h:36,
                 from ./core/oa_hash_map.h:34,
                 from drivers/vulkan/rendering_device_vulkan.h:34,
                 from drivers/vulkan/rendering_device_vulkan.cpp:31:
./core/cowdata.h:141:3: error: '*((void*)& description +24)' may be used uninitialized in this function [-Werror=maybe-uninitialized]
  141 |   _get_data()[p_index] = p_elem;
      |   ^~~~~~~~~
drivers/vulkan/rendering_device_vulkan.cpp:2995:27: note: '*((void*)& description +24)' was declared here
 2995 |   VkAttachmentDescription description;
      |                           ^~~~~~~~~~~
In file included from ./core/ustring.h:35,
                 from ./core/string_name.h:36,
                 from ./core/node_path.h:34,
                 from ./core/hashfuncs.h:36,
                 from ./core/oa_hash_map.h:34,
                 from drivers/vulkan/rendering_device_vulkan.h:34,
                 from drivers/vulkan/rendering_device_vulkan.cpp:31:
./core/cowdata.h:141:3: error: '*((void*)& description +16)' may be used uninitialized in this function [-Werror=maybe-uninitialized]
  141 |   _get_data()[p_index] = p_elem;
      |   ^~~~~~~~~
drivers/vulkan/rendering_device_vulkan.cpp:2995:27: note: '*((void*)& description +16)' was declared here
 2995 |   VkAttachmentDescription description;
      |                           ^~~~~~~~~~~
[Initial build] Compiling ==> editor/editor_file_system.cpp
[Initial build] Compiling ==> editor/editor_folding.cpp
In file included from ./core/ustring.h:35,
                 from ./core/string_name.h:36,
                 from ./core/node_path.h:34,
                 from ./core/hashfuncs.h:36,
                 from ./core/oa_hash_map.h:34,
                 from drivers/vulkan/rendering_device_vulkan.h:34,
                 from drivers/vulkan/rendering_device_vulkan.cpp:31:
./core/cowdata.h: In member function 'void RenderingDeviceVulkan::_draw_list_insert_clear_region(RenderingDeviceVulkan::DrawList*, RenderingDeviceVulkan::Framebuffer*, Point2i, Point2i, bool, const Vector<Color>&, bool, float, uint32_t)':
./core/cowdata.h:141:3: error: 'clear_at.VkClearAttachment::clearValue.VkClearValue::color.VkClearColorValue::float32[3]' may be used uninitialized in this function [-Werror=maybe-uninitialized]
  141 |   _get_data()[p_index] = p_elem;
      |   ^~~~~~~~~
drivers/vulkan/rendering_device_vulkan.cpp:5647:21: note: 'clear_at.VkClearAttachment::clearValue.VkClearValue::color.VkClearColorValue::float32[3]' was declared here
 5647 |   VkClearAttachment clear_at;
      |                     ^~~~~~~~
In file included from ./core/ustring.h:35,
                 from ./core/string_name.h:36,
                 from ./core/node_path.h:34,
                 from ./core/hashfuncs.h:36,
                 from ./core/oa_hash_map.h:34,
                 from drivers/vulkan/rendering_device_vulkan.h:34,
                 from drivers/vulkan/rendering_device_vulkan.cpp:31:
./core/cowdata.h:141:3: error: 'clear_at.VkClearAttachment::clearValue.VkClearValue::color.VkClearColorValue::float32[2]' may be used uninitialized in this function [-Werror=maybe-uninitialized]
  141 |   _get_data()[p_index] = p_elem;
      |   ^~~~~~~~~
drivers/vulkan/rendering_device_vulkan.cpp:5647:21: note: 'clear_at.VkClearAttachment::clearValue.VkClearValue::color.VkClearColorValue::float32[2]' was declared here
 5647 |   VkClearAttachment clear_at;
      |                     ^~~~~~~~
cc1plus: all warnings being treated as errors
scons: *** [drivers/vulkan/rendering_device_vulkan.linuxbsd.opt.tools.64.o] Error 1
scons: building terminated because of errors.
```

**Comment by clayjohn** [comment] 2020-06-29 06:39
Duplicate of https://github.com/godotengine/godot/issues/38410

Related to #39442, #36565

Thanks for the report! This is a known issue and shod be tracked in one of the already reported issues.

**Closed by clayjohn** 2020-06-29 06:39 UTC
