### ISSUE TITLE
Game crashes without error log

### ISSUE THREAD

**Issue by vicguedez** [godotengine/godot#9615] opened 2017-07-12 03:51 UTC
**Operating system or device - Godot version:**
Debian 9 - Godot 2.1.3/2.1.4

**Issue description:**
So In my game I have a menu on which I do `self.get_tree().change_scene("world_scene_path")` when "start" is pressed, it takes the player the game "world" and then when the player dies it does `self.get_tree().change_scene("menu_scene_path")`...

Everything works fine, but after dying 2 times, when I click "start" the game crashes and only says "Segment Violation", that's all.

What to do?

**Comment by vicguedez** [comment] 2017-07-12 04:00
Ok... I have no idea of how, but moving 4 preloaded scenes out of my "world" scene to a singleton fixed the issue. I guess it has something to do with the resources references.

If someone directs on how to debug this I'll gladly help.

**Comment by Zylann** [comment] 2017-07-13 11:09
Any minimal project reproducing the bug?

**Comment by MarianoGnu** [comment] 2017-07-13 11:26
Is the "Segment Violation" message displayed on Debian's console or in Editor's output console?

**Comment by vicguedez** [comment] 2017-07-13 11:29
It didn't show when using the Editor, I exported the game for linux, and then run it from debian console.

**Comment by MarianoGnu** [comment] 2017-07-13 11:43
hum, i have a similar issue crashing with no message from editor, i'll try exporting and see if i can replicate this.

**Comment by vicguedez** [comment] 2017-07-13 11:50
I will try to replicate it and give a minimal project.

**Comment by vicguedez** [comment] 2017-07-13 12:13
Ok... I'm unable to reproduce this... Really can't tell what happend. All I've done since this is just remove some TouchScreenButtons on the menu scene.

**Comment by akien-mga** [comment] 2017-07-25 12:58
If it can't be reproduced, it will be pretty hard to debug/fix, so closing for now. Feel free to comment/reopen if you find a way to reproduce it.

**Closed by akien-mga** 2017-07-25 12:58 UTC
Labels: bug, topic:core

**Comment by MarianoGnu** [comment] 2017-07-26 10:41
@akien-mga i dont know about his crash, but i could detect and fix mine, this happens when using sort_custom in an array of References (in my case it was a subclass inside a subscript) using a random threshold to sort characters by speed. This happened in this line:
https://github.com/godotengine/godot/blob/master/core/sort.h#L239
for some reason it is trying to compare val with p_array[-1], i did a quick fix and it stopped crashing
![error](https://user-images.githubusercontent.com/1776044/28617193-d4a3788e-71d5-11e7-931e-852a7bd4464d.png)

**Comment by akien-mga** [comment] 2017-07-26 11:06
@MarianoGnu A pull request would be welcome for this :)

**Comment by MarianoGnu** [comment] 2017-07-28 10:55
@akien-mga yeah... i'm not sure since i dont know if this is the best solution, maybe the fix should be locater earlier, but sorting algorythms are a little too advanced for my understanding...

**Comment by robbertzzz** [comment] 2020-05-19 10:31
I'm getting this on 3.2.1 stable on Ubuntu when I call Array.resize(40000). This number was a factor 200 too high for what I needed, but it was after that exact line that my breakpoints weren't triggered anymore. Using a smaller number does not close the game without any errors, so it looks like allocating a large amount of memory doesn't sit well with Godot.
