### ISSUE TITLE
Regression: Containers use significantly more CPU time in Godot 3.1

### ISSUE THREAD

**Issue by ArdaE** [godotengine/godot#29698] opened 2019-06-11 23:04 UTC
**Godot version:**
3.1.1 (since 3.1.0)

**OS/device including version:**
macOS 10.14.5

**Issue description:**
Ever since Godot 3.1.0, selecting a node under any Container type in the scene tree within the editor causes continuous screen updates (judging by the spinning update wheel on the top right corner of Godot) even though nothing is changing on the screen. My notebook heats up rapidly and its fans kick in if I ever forget a child of any Container selected in the scene tree.

**Steps to reproduce:**
1. Create any Container type (Container, VBoxContainer, etc.) in an empty scene
2. Add a Label under the container
3. Select the Label (stay in the 2D view mode)
4. Watch Godot's screen update wheel in the top corner

**Minimal reproduction project:**
I've created the following project in Godot 3.0, so you can see the difference between 3.1 and 3.0. First open in Godot 3.0, select Label in the scene tree, make sure Godot is in the 2D editor mode, and watch the screen update wheel. Then open in Godot 3.1 and do the same. Measure the CPU load in both cases.

[TestGodot3.0.zip](https://github.com/godotengine/godot/files/3278854/TestGodot3.0.zip)

**Additional details:**
The CPU load of the editor on my computer doubles in Godot 3.1 (40% in Godot 3.1 vs. 20% in Godot 3.0, with the same node selected) using the sample project. I haven't done extensive tests on running projects, but running the sample project also seems to load the CPU more in Godot 3.1 while attached to the debugger (%20 in Godot 3.1 vs %15 in Godot 3.0 for the sample project, with the script editor focused in Godot so the 2D editor's overhead due to this issue is eliminated). I haven't tried running the sample project without the debugger, so I don't know if performance is worse in that scenario too.

I have checked if Godot 3.1 calls sort_children more frequently, but that doesn't seem to be the case for the running project. I haven't checked the actual notifications or whether sort_children is called more often by the editor or not.

**Comment by KoBeWi** [comment] 2019-06-12 00:45
Looks like duplicate of #29313, which is already fixed in 3.2-dev.

**Closed by KoBeWi** 2019-06-12 00:45 UTC
