### ISSUE TITLE
Czech special characters fails the whole translations

### ISSUE THREAD

**Issue by IranosMorloy** [godotengine/godot#23298] opened 2018-10-26 09:30 UTC
**Godot version:**
3.0.6 stable official

**OS/device including version:**
Windows 10 Pro x64

**Issue description:**
Wanted to translate my project from english to my native czech language with the special symbols / characters. Added a font that handle the czech characters. But when running the project, there is always shown just the 1st index translation to english and then only the index. Csv file has a format index, english, czech ( ,en,cs).

The debugger shows no error. Sometimes it says "unicode error: invalid skip"

**Minimal reproduction project:**
To track just this issue, I've created a separated test project with the same translation behaviour shared here:
[translations_test.zip](https://github.com/godotengine/godot/files/2518615/translations_test.zip)

**Comment by akien-mga** [comment] 2018-10-26 10:58
>  translations_test.zip

Note for testers: this is actually a RAR file renamed with .zip extension, change extension to unarchive it.

**Comment by akien-mga** [comment] 2018-10-26 11:37
The problem is that you CSV file is in ISO-8859 format, while Godot works with UTF-8 and expects that. Converting the file to UTF-8 with a text editor makes it work properly.

In my case I did (on Linux):
```
iconv -f ISO-8859-1 -t UTF-8 Translations.csv > Translations2.csv
mv -f Translations2.csv Translations.csv
```
That converts it to UTF-8, and the translations are then working in the game:
![screenshot_20181026_133617](https://user-images.githubusercontent.com/4701338/47564085-1dfd7500-d924-11e8-8662-9d492ab242b9.png)
![screenshot_20181026_133633](https://user-images.githubusercontent.com/4701338/47564099-2786dd00-d924-11e8-9b4e-556c3d08d629.png)

The missing letters are due to the font, using a more standard font like DejaVuSans.ttf gives:
![screenshot_20181026_133731](https://user-images.githubusercontent.com/4701338/47564151-4a18f600-d924-11e8-926f-1f2aa4251cf8.png)

I'll see if we can improve the error message/detect wrong encoding.

**Comment by capnm** [comment] 2018-10-26 15:20
> I'll see if we can improve the error message/detect wrong encoding.

FYI the output should be:

něco
přání
Já si přeji


![image](https://user-images.githubusercontent.com/4047289/47574982-3cbe3480-d941-11e8-946b-4109edd4fa94.png)

Also, something else seems to be broken, e.g. it is correct inside the inspector, but not inside the label
(If you use the default font settings):
![image](https://user-images.githubusercontent.com/4047289/47575076-8444c080-d941-11e8-95ed-7c57c5837110.png)

**Comment by IranosMorloy** [comment] 2018-10-26 16:33
I see. I used to encode it in UTF-8 at the first use. It could have changed itself while being updated with more translations. After reencoding to UTF-8, all works fine. Thanks a lot! :-) Is there a way to easily check if the csv file is actually in UTF-8?

**Comment by ni-code** [comment] 2018-10-27 00:36
@IranosMorloy 
For linux and mac, you can use the `file` command:
`file -bi yourfile.csv`. 

For windows, I don't think there's such thing, but according to stack-overflow the best way is to: 

> Open the file in Notepad. Click 'Save As...'. In the 'Encoding:' combo box you will see the current file format.

**Comment by starry-abyss** [comment] 2018-10-27 01:46
One can use e.g. Notepad++, it shows the current the encoding in bottom right corner

**Comment by IranosMorloy** [comment] 2018-10-27 06:14
Alright, thank all of you for your help :-) this seems to be solved now.

**Comment by KoBeWi** [comment] 2020-06-25 11:51
The last comment literally says it's solved, so it should be fine to close this.

**Closed by KoBeWi** 2020-06-25 11:51 UTC
Labels: bug, topic:core
