### ISSUE TITLE
Game crash just after the launch from the editor

### ISSUE THREAD

**Issue by AndreaCatania** [godotengine/godot#28556] opened 2019-05-01 07:28 UTC
Current master branch 

Problem:
When I start the game from the editor it crash instantly without any message, If I start the game from the command line directly it start.

The commit that cause this problem is this one: 419022ea8909f26ac4353cc816c553ca14e0b925

**Comment by akien-mga** [comment] 2019-05-01 07:34
Duplicate of #28538.

**Closed by akien-mga** 2019-05-01 07:34 UTC
Labels: bug
