### ISSUE TITLE
Light2D does not cast shadows if it's not using layer 1

### ISSUE THREAD

**Issue by Winterslice** [godotengine/godot#43629] opened 2020-11-17 22:52 UTC
**Godot version:**
Godot v3.2.3 Standard Windows 64 bit

**OS/device including version:**
Windows 10, GLES 3

**Issue description:**
Light2D nodes ignore LightOccluder2Ds on the same Light/Item Cull Mask layer unless the Light2D is also using layer 1.

**Steps to reproduce:**
Change any Light2D and LightOccluder2D pair to use any layer other than 1.

**Minimal reproduction project:**
The official 2D lighting demo can easily be used for this.

**Comment by lawnjelly** [comment] 2020-11-18 10:53
Duplicate of #25992

I had a look this morning, and put an explanation in that issue. Actually not a bug, afaik.

**Closed** 2020-11-18 10:56 UTC
Labels: bug, topic:rendering
