### ISSUE TITLE
Documentation inside editor is distorted in some sections

### ISSUE THREAD

**Issue by tokengamedev** [godotengine/godot#78317] opened 2023-06-16 07:07 UTC
### Godot version

4.1.beta.2

### System information

Windows 11

### Issue description

Documentation is distorted in some section of some help sections.

![image](https://github.com/godotengine/godot/assets/84369217/8391dea0-db87-464f-9893-850d58650c8a)

This gets corrected if the help window is resized, like closing/opening output window

Noticed Sections:

Node, Line2D, Object, CPUParticles2D, TileMap

### Steps to reproduce

Open Help section by clicking Serach help in the editor.
Search for Node
and open the Node documentation.

**This is not reproducible in 4.1.beta.1**

### Minimal reproduction project

N.A

**Comment by Sauermann** [comment] 2023-06-16 07:31
Looks like a duplicate of #77558

> Godot version
> 4.1.beta.1
> [...]
>This is not reproducible in 4.1.beta.1

Which of these two statements is correct?

**Comment by AThousandShips** [comment] 2023-06-16 07:37
If you are able to test the latest master version please confirm that this is solved, but almost certain this is a duplicate of:
* #77558

Which has been resolved

**Comment by tokengamedev** [comment] 2023-06-16 08:18
apologies, my mistake... I have been working on 4.1 beta2. The issue is in 4.1 beta 2 but not reproducible in 4.1 beta1

**Comment by tokengamedev** [comment] 2023-06-16 08:21
A

> If you are able to test the latest master version please confirm that this is solved, but almost certain this is a duplicate of:
> 
> * [Built in doc's layout is broken when the engine is restarted. #77558](https://github.com/godotengine/godot/issues/77558)
> 
> Which has been resolved in:
> 
> * [[RTL] Fix multithreaded resizing. #78241](https://github.com/godotengine/godot/pull/78241)

I will be able to test on 4.1 beta 3 or RC version of the engine. I do not custom build engine.

**Comment by akien-mga** [comment] 2023-06-16 08:28
Closing as it's very likely a duplicate of #77558. Let us know when 4.1 beta 3 is released if it didn't solve the problem for you.

**Closed by akien-mga** 2023-06-16 08:28 UTC
Labels: bug, topic:editor, needs testing, topic:gui
