### ISSUE TITLE
Wrong alignment of buttons on MacOS version

### ISSUE THREAD

**Issue by ondrowan** [godotengine/godot#24554] opened 2018-12-22 20:10 UTC
**Godot version:** 3.1 alpha 4

**OS/device including version:** MacOS 10.14

**Issue description:**

Buttons are by default shown aligned like this on MacOS (doesn't happen on Windows):

<img width="747" alt="image" src="https://user-images.githubusercontent.com/423776/50378236-8b303c80-062d-11e9-8c60-8e5333e803a2.png">

The lower part of these buttons isn't clickable. Resizing the window aligns the buttons properly and fixes the issue.

**Comment by akien-mga** [comment] 2018-12-27 07:40
CC @Calinou

**Comment by Calinou** [comment] 2018-12-28 22:31
I couldn't reproduce this on https://github.com/godotengine/godot/commit/04c8a43741656814c86923c89f2dd23646751b96 on Linux (with the editor scale set to 200%).

I don't see why this would be OS-specific, but I can't test this on macOS with a hiDPI display anyway.

**Comment by ondrowan** [comment] 2018-12-29 17:42
@Calinou I've just tried today's nightly and it still happens on MacOS 10.14.2.

**Comment by akien-mga** [comment] 2019-02-13 16:13
Might be fixed by #25858.

**Comment by akien-mga** [comment] 2019-02-23 19:50
Assumed fixed by #25858, please comment if you can still reproduce it.

**Closed by akien-mga** 2019-02-23 19:50 UTC
Labels: bug, hero wanted!, platform:osx, topic:editor
