### ISSUE TITLE
Make code suggestions popup menu wider

### ISSUE THREAD

**Issue by iwek7** [godotengine/godot#33848] opened 2019-11-23 21:25 UTC
**Godot version:**
81c6a7e5f

**OS/device including version:**
Ubuntu 19

**Issue description:**
Code suggestions window is too narrow - this creates issues for instance when suggesting long node path. Consider following situation:
![image](https://user-images.githubusercontent.com/9964886/69485421-84163d80-0e3f-11ea-87e4-a355dc370cd2.png)
As you can see node paths are cut and there is plenty of space to scale this window horizontally, I think that it should be auto-scaled to take up to the length of code editor. If this is not ok then I think that we should somehow inform user that not whole entry is visible (for instance add `(...)` at the end). Ideally both options would be implemented.

**Steps to reproduce:**
1. Make any scene structure with long node names or many nodes
2. Ask for context help after `$`

ps. Hard to say for me if it is a feature or a bug, looks a bit more than a bug to me

**Comment by Calinou** [comment] 2019-11-23 21:54
Duplicate of #16542.

**Closed by Calinou** 2019-11-23 21:54 UTC

**Comment by iwek7** [comment] 2019-11-23 22:11
sorry!
