### ISSUE TITLE
Switched LOD not working again 

### ISSUE THREAD

**Issue by DimitriyPS** [godotengine/godot#57185] opened 2022-01-25 09:43 UTC
### Godot version

3.5 b1

### System information

All

### Issue description

I read that Godot 3.5 will support LOD - I was delighted. But apparently this did not apply to switchable LODs. This feature worked in 2.x and already works in 4.x, i can only speculate, perhaps you could have this feature in version 3.5 as well? I humbly ask the development team for this small courtesy, unless of course it will embarrass you and will not be undue impudence on my part.  
![000](https://user-images.githubusercontent.com/11189223/150951878-4f904a00-1cd7-417e-9159-7a0ad961b452.png)

### Steps to reproduce

1. Create an object;
2. Set distances;
3. Rotate the mouse roller.

**Comment by lawnjelly** [comment] 2022-01-25 13:11
There's no LOD in 3.x currently afaik (despite the settings being there).

**Comment by DimitriyPS** [comment] 2022-01-25 13:33
@lawnjelly why "feature proposal"?

I am not suggesting adding something new. It's there, but it doesn't work. If this is not a bug, then what is a bug?

**Comment by lawnjelly** [comment] 2022-01-25 13:50
> I am not suggesting adding something new. It's there, but it doesn't work. If this is not a bug, then what is a bug?

Sorry to be more clear, this may be a language thing:

* There is a setting that you can *see* in the user interface as shown in red on your screenshot. But this setting does nothing, it is probably leftover from Godot 2, or left for future expansion.
* Code in the user interface is like the tip of an iceberg, it is not the functionality. The majority of the iceberg is under the water surface, and in this case, there is nothing under the surface, the other 99% of the code that does something has not been written.

**Comment by akien-mga** [comment] 2022-01-25 13:57
This is a duplicate of #40784. Indeed there's no implementation behind these settings, they're leftovers from 2.x which never got reimplemented (and they're not _easy_ to reimplement).

**Closed by akien-mga** 2022-01-25 13:57 UTC
Labels: feature proposal, topic:rendering

**Comment by DimitriyPS** [comment] 2022-01-25 13:59
I know it doesn't work (I've been waiting for LOD switches since version 3.0 for a very long time). I also understand that the code is not there.

But I checked, this functionality works in Godot 4. Godot 4 is very far from working. Therefore, now when many new developments began to be transferred from 4.x to 3.x, I hoped that this functionality could also be restored. I admit that I can be mistaken, but in theory, switching visibility based on the distance condition is a very simple technology.

**Comment by Zireael07** [comment] 2022-01-25 14:02
> But I checked, this functionality works in Godot 4. Godot 4 is very far from working. 

Not true (unless you're someone whose computer does NOT support Vulkan) - it does have its issues and porting a big project isn't easy, but Godot 4 definitely works.

> Therefore, now when many new developments began to be transferred from 4.x to 3.x, I hoped that this functionality could also be restored. 

If all you wanted to do was request a backport of the LOD from 4.x to 3.x, the issue should have been titled accordingly (the current title suggests a regression, which is not the case as it never worked in the first place)

**Comment by DimitriyPS** [comment] 2022-01-25 14:11
> Not true (unless you're someone whose computer does NOT support Vulkan) - it does have its issues and porting a big project isn't easy, but Godot 4 definitely works.

I did not mean that Godot 4 does not start, I mean that it is too unstable for development using it.

> If all you wanted to do was request a backport of the LOD from 4.x to 3.x, the issue should have been titled accordingly (the current title suggests a regression, which is not the case as it never worked in the first place)

Apparently I do not understand some of the subtleties. I see the same settings in Godot 2.x, 3.x and 4.x. But the technology only works in 2.x and 4.x.

So you are saying that I need to recreate the issue with a different title?

**Comment by akien-mga** [comment] 2022-01-25 14:15
> Apparently I do not understand some of the subtleties. I see the same settings in Godot 2.x, 3.x and 4.x. But the technology only works in 2.x and 4.x.

A setting is not a feature. Here's the implementation of visibility ranges in 4.0: #48847.

This is not trivial to backport, it depends on the **renderer** which is the main part which is **100%** different in 2.x, 3.x, and 4.x. Rewriting the renderer is the main reason why these versions are not compatible with each other. It also mean that renderer-dependent features need to be reimplemented from scratch, and LOD was never reimplemented in 3.x. At this point, it's safe to assume it will not be.

**Comment by DimitriyPS** [comment] 2022-01-25 14:19
It's clear. Thanks for the explanation. It's very unfortunate. This functionality is sorely lacking.

**Comment by akien-mga** [comment] 2022-01-25 14:22
Apparently there's a draft PR which implements the basic LOD functionality that could be expected from these properties: #53778.

So if it can be finalized, this would be merged instead of removing the properties.
