### ISSUE TITLE
Project Settings Physics FPS effects Editor Script Editor Scroll Speed

### ISSUE THREAD

**Issue by FeralBytes** [godotengine/godot#47934] opened 2021-04-15 20:10 UTC
Related to but different than [#39841](https://github.com/godotengine/godot/issues/39841)

**Godot version:**
3.3-rc6-rc9 and likely many prior.

**OS/device including version:**
Linux Mint 20.1 Cinnamon x64 / Desktop
Linux Kernel: 5.4.0-70-generic
GPU: Advanced Micro Devices, Inc. [AMD/ATI] Navi 10 [Radeon RX 5600 OEM/5600 XT / 5700/5700 XT]
CPU: AMD Ryzen 9 3900X 12-Core Processor × 12
GLES 2 or GLES 3

**Issue description:**
In the editor the script editor is slow to scrolling and skips/jumps, like it is running at 1fps. Because the Project Setting: Physics > Common > physics_fps = 1.

**Steps to reproduce:**
In project settings change Physics>Common>Physics_fps = 1 and then save and restart the project, now observe upon editing a script the scroll is extremely sluggish, like 1 fps sluggish. Put it back to 60 and save, then reload the project and all is fixed.

**Minimal reproduction project:**
Any project with a script long enough to scroll will do.

**Comment by FeralBytes** [comment] 2021-04-15 20:15
Suggested Fix: The project settings should not affect the editor. Or at the very least should not affect editor functionality. I really can't think of why the text editor is running on the _physics_process() calls anyways as compared to the _process() method.

**Comment by smix8** [comment] 2021-04-15 21:46
> I really can't think of why the text editor is running on the _physics_process() calls anyways as compared to the _process() method.

I guess because physics tickrate is fixed (to the setting) while process runs with your framerate. If you have a monitor with very high refreshrate or vsync disabled many editor functions would update a few hundred times each second with _process() which is complete overkill.

**Comment by Calinou** [comment] 2021-04-15 21:55
Duplicate of https://github.com/godotengine/godot/issues/28385.

**Closed by Calinou** 2021-04-15 21:55 UTC
