### ISSUE TITLE
Settings windows do not pop up if moved to another screen (DisplayServer regression)

### ISSUE THREAD

**Issue by Vlad-Zumer** [godotengine/godot#74786] opened 2023-03-11 19:09 UTC
### Godot version

v4.0.stable.mono.official [92bee43ad]

### System information

Windows 10 x64; i7-7820HK; 64GB RAM; GTX 1080

### Issue description

This issue forces you terminate the Godot process.

`Project Settings` and `Editor Settings` windows do not pop up properly if they've been moved to another (lower resolution) screen/monitor. Their position gets cached correctly but if the Godot Editor is not on the same monitor, the window will not show up, but does lock up the editor UI.

I am working with a 4k (3840x2160) and a 1080HD (1920x1080) display. 
This problem might be related to UI scaling between them.
Unfortunately I cannot test with 2 1080HD screens at this time.

### Steps to reproduce

1. Open godot editor
2. Move it to the high res monitor
3. Open the `editor settings`/`project settings` dialog
4. Move it to the low res monitor
5. Close the settings dialog
6. Open the same dialog again
    * The dialog does not show up / is off the monitor / the position has moved (depending on the resolution difference)

7. Move the godot editor to the low res monitor
    * The dialog is roughly in the same place it was from step 4.

### Minimal reproduction project

N/A

**Comment by Calinou** [comment] 2023-03-21 20:56
- Duplicate of https://github.com/godotengine/godot/issues/74261.

**Closed by Calinou** 2023-03-21 20:56 UTC
Labels: bug, topic:editor, regression
