### ISSUE TITLE
Dragging the game window lgs on linux when 'Use Vsync' enabled

### ISSUE THREAD

**Issue by akanewf** [godotengine/godot#16867] opened 2018-02-20 19:16 UTC
**Godot version:**

e3be5bb61d7f8850c1d7a43dbc18f37107c2e317

**OS/device including version:**

archlinux xfce4

**Issue description:**

dragging the game window is very lag when 'Use Vsync' enabled.
uncheck the 'Use Vsync' ,issues gone.

**Steps to reproduce:**
1.open a new project
2.run the project
3.drag the running game windows and move around
4.game window responding was very lag

**Minimal reproduction project:**

**Comment by raymoo** [comment] 2018-02-21 01:09
I don't think I get this problem in i3.

**Comment by s22h** [comment] 2019-01-14 15:30
This issue might be caused directly by glXSwapIntervalEXT/eglSwapInterval (at least on GTK-based desktop environments under X11). The issue occurs for me on MATE and XFCE4 both with Godot and GLFW's glfwSwapInterval, both of which call glXSwapIntervalEXT under the hood.

**Comment by KoBeWi** [comment] 2020-06-14 23:17
Can anyone still reproduce this bug in Godot 3.2.1 or any later release (e.g. [3.2.2-beta4](https://godotengine.org/article/dev-snapshot-godot-3-2-2-beta-4))?
(testing in 4.0/master would be useful too)

**Comment by s22h** [comment] 2020-06-16 09:53
I've tried in 3.2.1 and 3.1.2 and can't reproduce the bug in any of those. I've switched from a Geforce 1060 to a Radeon 5700 XT since, though, which might have fixed the problem on my end.

**Comment by akien-mga** [comment] 2020-06-16 10:00
Thanks, we'll close for now then as we haven't had other similar reports in a while, so it might have been a driver bug that (hopefully) got fixed in newer versions.

If anyone still experiences this issue, feel free to comment and we can reopen the issue.

**Closed by akien-mga** 2020-06-16 10:00 UTC
Labels: bug, platform:linuxbsd, topic:core
