### ISSUE TITLE
`Tabs tab_close` signal is emitted when close button is hidden

### ISSUE THREAD

**Issue by me2beats** [godotengine/godot#47795] opened 2021-04-11 12:36 UTC
**Godot version:**

3.2.3

**OS/device including version:**

Linux

**Issue description:**

https://user-images.githubusercontent.com/16458555/114306621-c522f680-9af5-11eb-946f-c34848263032.mp4

When pressing the tab on "close button" area, `tab_close` signal is emitted even  when `Tabs close display policy` is set to `active only`.

**Steps to reproduce:**
see video above

**Minimal reproduction project:**

**Comment by Calinou** [comment] 2021-04-11 12:54
I can reproduce this on 3.2.3. It's the reason I opened https://github.com/RodZill4/material-maker/pull/325.

**Comment by kitbdev** [comment] 2023-10-19 18:19
fixed by #55454

**Closed** 2023-10-19 18:23 UTC
Labels: bug, confirmed, topic:gui
