### ISSUE TITLE
Shader sampler2D uniforms doesn't show up properly on inspector

### ISSUE THREAD

**Issue by khairul169** [godotengine/godot#8753] opened 2017-05-14 03:58 UTC
**Operating system or device - Godot version:**
Ubuntu 16.04
Godot custom build from commit 6d0568d

**Issue description:**
See title

**Steps to reproduce:**
Create shader material that is have two or more sampler2D uniforms, and back to the inspector panel..
![a](https://cloud.githubusercontent.com/assets/10296472/26031181/0f8a7acc-3894-11e7-841b-02418cf59d9c.png)
There should be three sampler2D uniforms, but it doesn't..
![b](https://cloud.githubusercontent.com/assets/10296472/26031180/0bf93600-3894-11e7-9863-7180e39d809b.png)

:cry:

**Comment by nunodonato** [comment] 2017-05-14 09:58
Duplicate of #8353

**Comment by bojidar-bg** [comment] 2017-05-14 17:02
@nunodonato Right, thanks.
Closing as duplicate of #8353, as per comment above.

**Closed by bojidar-bg** 2017-05-14 17:02 UTC
