### ISSUE TITLE
CollisionPolygon2D Issues

### ISSUE THREAD

**Issue by 0nepixel** [godotengine/godot#7466] opened 2017-01-08 09:02 UTC
Windows 7 Godot 2.1/2.2

CollisionPolygon2D/set_polygon() does nothing

**Steps to reproduce:**
1-Get the polygon:
col = get_polygon()

2-Change the CollisionPolygon2D's shapes :
col[1].y=-80
3- set the polygon:
set_polygon(col)
**Link to minimal example project** (optional but very welcome):
https://drive.google.com/open?id=0B3mjAjcuXnKqVjFPanUycHhiaXc

**Comment by 0nepixel** [comment] 2017-01-08 09:04
when you turn on visible collision shapes, you can see the changed polygon, but the collision detect the old polyong instead the new one
http://gph.is/2iqruwX

**Comment by williamd1k0** [comment] 2017-01-08 11:06
I can reproduce this using AnimationPlayer

![collision-polygon](https://t.gyazo.com/teams/thetimetunnel/27504ede323d4f76cc66c67e89ac1693.gif)

**Comment by sezit** [comment] 2017-01-08 12:59
@0nepixel  @williamd1k0  Its not bug. 2Dpolygon help create collision shape, but it not shape itself. You should use this...
![1](https://cloud.githubusercontent.com/assets/6241034/21750047/5b8f8dae-d5bb-11e6-89be-6ab973cea5ce.png)

**Comment by 0nepixel** [comment] 2017-01-08 13:42
thanks

**Comment by 0nepixel** [comment] 2017-01-08 14:04
![bug](https://cloud.githubusercontent.com/assets/22958303/21750448/2cca35d8-d592-11e6-9aee-2788ee094733.gif)

**Comment by eon-s** [comment] 2017-01-08 15:27
@0nepixel you won't see the new shape in "debug" unless you add it to a collisionshape/polygon (confusing, I know) or draw it yourself (with _draw)

**Comment by 0nepixel** [comment] 2017-01-08 15:31
you don't see the problem xD, the shape changes in the collision only

**Comment by sezit** [comment] 2017-01-08 16:17
@0nepixel  Here, but after download close this Issue, because its not forum :З
https://cloud.mail.ru/public/Jip6/NgBAwYVWY

**Comment by bojidar-bg** [comment] 2017-01-08 16:40
You are using the animationplayer in fixed mode, right?

**Comment by 0nepixel** [comment] 2017-01-08 16:51
@sezit thanks bro :) :+1:

**Comment by williamd1k0** [comment] 2017-01-08 17:23
@bojidar-bg I tested AnimationPlayer using idle and fixed mode (same result).

**Comment by Lemony-Andrew** [comment] 2017-05-01 01:53
I'm pretty sure this is by design. The "visible collision shapes" I believe only show the shapes made in the editor, not the shapes inside of the CollisionObject2D's. So, if you update the shape in CollisionObject2D the collisions you'll see won't match up unless you update the CollisionPolygon2D which is basically only useful as an editor class.

Again, don't think this is a bug, this is just by design.

**Comment by neikeq** [comment] 2017-05-01 02:04
This seems to be related to #4260

**Comment by akien-mga** [comment] 2017-05-18 13:47
This is indeed the normal behaviour. It might be made a bit more user-friendly in 3.0, but this is already tracked in various other issues so closing this one.

**Closed by akien-mga** 2017-05-18 13:47 UTC
Labels: bug, confirmed, topic:physics
