### ISSUE TITLE
Regression with selecting (without opening) resources doesn't open import tab

### ISSUE THREAD

**Issue by fire** [godotengine/godot#23057] opened 2018-10-16 18:10 UTC
**Godot version:**
0dbe01483a902c49ecedf4fd36b74353424145a5

**Issue description:**

Regressed with selecting (without opening) resources. They don't open the import tab. Only some resource opened can edit their import tab.

![godot windows opt tools 64_2018-10-16_11-09-27](https://user-images.githubusercontent.com/32321/47037515-fd6b3900-d133-11e8-9d52-283d4986a07a.png)
![godot_v3 1-alpha1_win64_2018-10-16_11-08-29](https://user-images.githubusercontent.com/32321/47037518-fe9c6600-d133-11e8-8184-2971dc55b9d0.png)

**Minimal reproduction project:**
Open any project. Select the logo image vs opening it.

**Comment by groud** [comment] 2018-10-16 18:33
I don't get how are the screenshots related. Why is the About popup opened ?

**Comment by fire** [comment] 2018-10-16 18:47
It shows the version number.

**Comment by fire** [comment] 2018-10-16 18:49
The problem is between 3.1.alpha.official and 0dbe014.

**Comment by groud** [comment] 2018-10-16 18:50
Then this is a duplicate of #23041

**Closed by groud** 2018-10-16 18:50 UTC
