### ISSUE TITLE
Godot Cutom Web Template Compilation Not Working At Least on Godot 3.5, have seen a forum complaining the same about 4.1.2

### ISSUE THREAD

**Issue by yohanneskassa40** [godotengine/godot#84332] opened 2023-11-01 23:58 UTC
### Godot version

3.5.3 stable win 64

### System information

Windows 10 3.5.3 stable win 64

### Issue description

I wanted to make a smaller export template for web since I wanted faster load times for clients (my country's internet speed is subpar compared to others).
Was unable to do that since scons spits out the same message again and again:

`
C:\Godot\Source\godot-3.5>scons platform=javascript tools=no target=release
scons: Reading SConscript files ...
Auto-detected 16 CPU cores available for build parallelism. Using 15 cores by default. You can override it with the -j argument.
use_lto is: True
Couldn't parse CXX environment variable to infer compiler version.
TypeError: 'NoneType' object is not iterable:
  File "C:\Godot\Source\godot-3.5\SConstruct", line 449:
    detect.configure(env)
  File "C:\Godot\Source\godot-3.5\platform/javascript\detect.py", line 189:
    cc_semver = tuple(get_compiler_version(env))
`

Yes, I have msvc, yes I have emscripten set in PATH, tried installing mingw if something changed, failed on all.
Wanted to note that windows custom build works perfectly and without errors.

### Steps to reproduce

Download the source, install all necessary tools as per the doc to compile godot web templates, run:

` scons platform=javascript tools=no target=release `

and see if there are any errors

### Minimal reproduction project

No need, since this involves compiling godot

**Comment by ChildLearningClub** [comment] 2023-11-02 02:49
Having similar issues.

Download source:
```git clone https://github.com/godotengine/godot.git -b 3.5.3-stable```

Copy contents of SCons-4.5.2.zip into the"godot dir

In godot dir:

```
git clone https://github.com/emscripten-core/emsdk.git

cd emsdk

git pull

.\emsdk install 2.0.8
.\emsdk activate 2.0.8

scons platform=list
```

The following platforms are available:

        javascript
        windows

`scons platform=javascript tools=yes threads_enabled=yes target=release_debug`

Prints: 
```
Couldn't parse CXX environment variable to infer compiler version.
TypeError: 'NoneType' object is not iterable:
  File "C:\GodotBuildDelete\godot\SConstruct", line 449:
    detect.configure(env)
  File "C:\GodotBuildDelete\godot\./platform/javascript\detect.py", line 189:
    cc_semver = tuple(get_compiler_version(env))
```

**Comment by ChildLearningClub** [comment] 2023-11-02 03:26
`git clone https://github.com/godotengine/godot.git -b 3.3.4-stable`
with exact same steps above does work.

**Comment by akien-mga** [comment] 2023-11-02 07:45
Thanks for the report!

- Duplicate of #82585

**Closed by akien-mga** 2023-11-02 07:45 UTC

**Comment by yohanneskassa40** [comment] 2023-11-03 06:33
Thank you Mr. Akien, I followed the other thread's workaround and it works! `cc_semver` was getting nonetype from the retrieval function, that's why it was not working for me.

**Comment by surendra019** [comment] 2023-11-21 09:22
@yohanneskassa40 please tell me how it worked for you.

**Comment by betterTisen** [comment] 2024-06-19 15:43
You have to go to `platform/javascript/detect.py` and change the lines
```bash
cc_semver = tuple(get_compiler_version(env))
```
to
```bash
# (3, 1, 49) is your emsdk version. You should be able to get that by running emcc -v
hardcodedcc_semver = (3, 1, 49)
```
