### ISSUE TITLE
Can't add animations from libraries other than "Global" to AnimationTree's StateMachines

### ISSUE THREAD

**Issue by eh-jogos** [godotengine/godot#61640] opened 2022-06-02 18:49 UTC
### Godot version

4.0.alpha9

### System information

Manjaro Linux, Nvidia proprietary drivers, Vulkan Clustered

### Issue description

If I have an AnimationPlayer and it's animations are inside a library other than "Global", their name will be `library_name/animation_name`. Then if I try to add them as States inside a AnimtationTree's StateMachine, it won't work and I'll get the error below:
![image](https://user-images.githubusercontent.com/13070158/171703897-864712f7-1563-4e3d-903f-ae08f6030c4c.png)

### Steps to reproduce

Just create a an animation inside a library and try o add it to an AnimationTree's StateMachine. Or see the MRP

### Minimal reproduction project

The MRP has a simple scene animating Godot's icon. It has four animations, two inside a "icon" library, and two that duplicates of this ones, but saved on the "global" library. The global ones I can add to the AnimationTree's StateMachine, the ones from the "icon" library I can't.
[library_vs_animationtree.zip](https://github.com/godotengine/godot/files/8826697/library_vs_animationtree.zip)

**Comment by eh-jogos** [comment] 2022-06-06 23:43
found this issue today while searching for another error I was having with animation tree #60959 
So this one is most likely a duplicate of it.

**Comment by Calinou** [comment] 2022-07-22 17:25
Duplicate of https://github.com/godotengine/godot/issues/60959.

**Closed by Calinou** 2022-07-22 17:25 UTC
Labels: bug, topic:editor, topic:animation
