### ISSUE TITLE
Editor's Popup overlay not hiding/freeing

### ISSUE THREAD

**Issue by henriiquecampos** [godotengine/godot#33572] opened 2019-11-12 13:35 UTC
**Godot version:**
3.2.beta1

**OS/device including version:**
Solus 4.0 Gnome 3.34.1

**Issue description:**
Some times when closing a popup dialog the overlay (the one that makes the background darker) doesn't disappear and it also consume inputs, making so that is impossible to even save some progress (unless it is saveable through the exiting dialog).

![image of the overlay covering the screen](https://user-images.githubusercontent.com/10171059/68676014-d601be00-0537-11ea-9b83-16af6852f762.png)

**Steps to reproduce:**
- Try to open some pop up dialogs, like moving a file using the dropdown menu.
- Click outside the pop up dialog, or even on cancel, or even confirm it, it happens randomly really

*ps: it may have to do with the usage of tablets (I'm using a wacom tablet) and I thin @NathanLovato had similar issues as well, dunno if he was using a tablet, tho.*

**Comment by akien-mga** [comment] 2019-11-12 14:09
@YeldhamDev Dimming issues never end...

**Comment by YeldhamDev** [comment] 2019-11-12 14:14
Considering that I've been using the master branch in my projects and never encountered this, I am going to assume that indeed this may be related touch inputs. And since I have none to test the editor with, this creates a problem for me to even start debugging it...

**Comment by YeldhamDev** [comment] 2019-11-12 14:23
This is the section that turns dimming on and off. Could you check if those conditionals fire when opening and closing dialogs in your touch device, and if you can reproduce it with a mouse?
https://github.com/godotengine/godot/blob/953f37f49b4d71b064935ff7e910bad829bfd17a/scene/gui/dialogs.cpp#L241-L251

**Comment by henriiquecampos** [comment] 2019-11-12 17:10
@YeldhamDev I don't have a touch device, the tablet I mention is a wacom tablet with pen and stuff...

I just tested and it also happens with mouse. And god...I'm having this non stop every time

**Comment by YeldhamDev** [comment] 2019-11-12 17:14
@henriiquecampos I see. Could you describe the action that makes this occur more frequently? Because I'm completely unable to reproduce this...

**Comment by henriiquecampos** [comment] 2019-11-12 17:48
Everything that pops a dialog, really. Lemme see if I reproduce it consistently. It mostly happen when these dialogues pop from a dropdown menu interaction, but it also happens otherwise.

Here are 3 examples, but honestly I could keep going, there are at least 6 more that I can reproduce consistently:

![01](https://user-images.githubusercontent.com/10171059/68696199-4bcb5100-055b-11ea-98dd-9ce5a71c2300.gif)
1. Try to delete a folder on the Filesystem using the drop down menu
![02](https://user-images.githubusercontent.com/10171059/68696204-4cfc7e00-055b-11ea-844c-7a75e028833e.gif)
1. Try to delete a node in the SceneTree using the drop down menu
![03](https://user-images.githubusercontent.com/10171059/68696205-4e2dab00-055b-11ea-8d44-902b44d96ffa.gif)
1. Try to save a branch scene that is an instance of another scene using the drop down menu

**Comment by YeldhamDev** [comment] 2019-11-12 17:51
I'm sorry, but I can't reproduce any of those. Everything works correctly on my end.

**Comment by nathanwfranke** [comment] 2019-11-12 18:49
I've randomly encountered this also, albeit randomly
`Ubuntu 19.10 eoan`
`x86_64 Linux 5.3.0-19-generic`

**Comment by henriiquecampos** [comment] 2019-11-13 13:28
Something interesting that I noticed: if we delete using <kbd>DELETE</kbd> and pressing <kbd>ENTER</kbd> or <kbd>RETURN</kbd> to confirm the deletion, this bug doesn't happen

**Comment by capnm** [comment] 2019-11-15 16:34
Personally, I think dimming is a terribly implemented 'anti-feature', and now it's not even possible to disable it :-/

(If you build Godot yourself, you can apply our patch that completely disables dimming)
```diff
diff --git a/editor/editor_node.cpp b/editor/editor_node.cpp
index ef382c0a1..1558c1cd5 100644
--- a/editor/editor_node.cpp
+++ b/editor/editor_node.cpp
@@ -5194,6 +5194,12 @@ void EditorNode::_open_imported() {
 }
 
 void EditorNode::dim_editor(bool p_dimming, bool p_force_dim) {
+
+       // disable dimming
+       dimmed = false;
+       gui_base->set_modulate(Color(1, 1, 1));
+       return;
+
        // Dimming can be forced regardless of the editor setting, which is useful when quitting the editor.
        if ((p_force_dim || EditorSettings::get_singleton()->get("interface/editor/dim_editor_on_dialog_popup")) && p_dimming) {
                dimmed = true;
diff --git a/editor/project_manager.cpp b/editor/project_manager.cpp
index ab62a59be..a19144dd8 100644
--- a/editor/project_manager.cpp
+++ b/editor/project_manager.cpp
@@ -1815,6 +1815,9 @@ void ProjectManager::_notification(int p_what) {
 
 void ProjectManager::_dim_window() {
 
+       // disable dimming
+       return;
+
        // This method must be called before calling `get_tree()->quit()`.
        // Otherwise, its effect won't be visible

```

**Comment by Calinou** [comment] 2019-11-15 18:48
@capnm Doesn't disabling **Interface > Editor > Dim Editor On Dialog Popup** do the job? If not, that should be fixed.

I personally like editor dimming as it makes it easier for the user to notice a popup has opened. Back in the Godot 2.x days, I occasionally missed popups due to this.

**Comment by capnm** [comment] 2019-11-15 19:32
> @capnm Doesn't disabling Interface > Editor > Dim Editor On Dialog Popup do the job? If not, that should be fixed.

→ // Dimming can be forced regardless of the editor setting, which is useful when quitting the editor.
Previously, it was possible to completely disable it.

> I personally like editor dimming as it makes it easier for the user to notice a popup has opened …

Maybe the default window frame could be made darker?

Most of the people (including myself) I asked, do not like that. It looks like something went wrong and just scares most of my kids… It's not an essential feature, so I'd rather recommend removing it from the editor (instead of fixing it).

**Comment by Calinou** [comment] 2019-11-15 20:39
> → // Dimming can be forced regardless of the editor setting, which is useful when quitting the editor.
> Previously, it was possible to completely disable it.

This is something entirely different. It's a special case of dimming that's displayed only when quitting the editor (or project manager). I first added it in #29636 so that the editor doesn't feel "stuck" when you close it. (It can take a few seconds to close on a slow machine, but even on a fast machine, it's never really instant.)

**Comment by henriiquecampos** [comment] 2019-11-15 21:43
Dimming is essential for UX, pop ups lose all their weight without dimming the background.

If the setting is not disabling it, it is an issue itself, but removing the dimming isn't going to improve the editor

**Comment by capnm** [comment] 2019-11-15 21:47
> Since the editor is no longer responsive when you start quitting it, I don't see a point in making this kind of dimming toggleable.

The big flicker with overhead projector in a darkened room is I think more annoying,
a few seconds of unresponsive editor does not really bother so much.

> We can't make it too dark without going into "pure black" territory,…

Then maybe a brighter edge or something in the sense that the border becomes more visible?
At the moment it is not easy to see where the dialogue lies:

![Screenshot](https://user-images.githubusercontent.com/4047289/68977747-3a06d980-07f9-11ea-9cfe-dcbf864f7c56.png)


(Advertising :1st_place_medal: I'd be really happy if anyone could spend his energy to fix #27669 That's something I have no idea how to fight against ;-)

**Comment by henriiquecampos** [comment] 2019-11-18 19:16
A quick update on this: I tried to turn off the dimming in the Editor Settings and now the editor freezes on the examples I mentioned...seems like the problem is a bit deeper indeed

**Comment by henriiquecampos** [comment] 2019-11-25 17:46
@akien-mga I just saw we have a beta2, this issue is definitely critical and it as I tested it still happens over and over.

I think there can't be a **stable** release with that bug still around, I really mean it, it's impossible to work, and this is potentially a regression from 3.1.1, which this bug doesn't happen, at least not that frequently (it happen once in a while, but currently it is just impossible to work)

**Comment by akien-mga** [comment] 2020-01-03 08:21
Might be fixed by #34770. Can anyone confirm in the current `master` branch / upcoming 3.2 beta 5?

**Comment by YeldhamDev** [comment] 2020-01-08 20:16
@henriiquecampos Ping.

**Comment by henriiquecampos** [comment] 2020-01-08 20:39
Ohh, sorry. Yeah I've been testing the last 4 days or so and didn't notice it happening, seems pretty much fixed at least for the cases I mentioned, thanks a lot :D

**Closed** 2020-01-08 20:40 UTC
Labels: bug, topic:editor
