### ISSUE TITLE
Renaming 'Blend' nodes and confirming with ENTER crashes editor

### ISSUE THREAD

**Issue by SlothDevLlama** [godotengine/godot#57370] opened 2022-01-28 20:42 UTC
### Godot version

3.5.beta1.mono

### System information

Windows 10

### Issue description

When editing names of any node inside a **BlendTree** and confirming with **ENTER** key the editor _crashes instantly_.
Editing the name and clicking outside works.

### Steps to reproduce

- Create a AnimationTree with a StateMachine
- Add a BlendTree
- Add Nodes which can be renamed
- Rename one of these BlendTree nodes and press ENTER

or use the Project zip file from below to reproduce.

### Minimal reproduction project

- Open Project > Node.tscn
- Select "AnimationTree"
- Edit the BlendTree
- Edit the Name and confirm with Enter -> Editor crashes

![image](https://user-images.githubusercontent.com/1180429/151617920-aa3e7404-8d95-4756-9fd0-35418647b78f.png)
![image](https://user-images.githubusercontent.com/1180429/151618092-e4422e15-983d-4d7c-9052-3c3b28cf2be6.png)
![image](https://user-images.githubusercontent.com/1180429/151617896-6c2da844-cf27-4721-ab93-cbad265334d2.png)
[MinimalProjectCrash.zip](https://github.com/godotengine/godot/files/7961708/MinimalProjectCrash.zip)

**Comment by Calinou** [comment] 2022-01-28 20:57
I can't reproduce this on `3.x` 49df809ca (Linux).

**Comment by lufog** [comment] 2022-01-28 21:49
@Calinou, 3.5.beta1.official [b9b23d222] crashes on my Windows 11.

https://user-images.githubusercontent.com/10379487/151626279-74cc3ee9-7591-4368-89cf-b2b7478d3993.mp4

**Comment by lufog** [comment] 2022-01-28 21:50
4.0.alpha1.official [31a7ddbf8] also crashes.

**Comment by lufog** [comment] 2022-01-28 21:55
But v4.0.alpha.custom_build [d2a2139b1] doesn't have this problem. Maybe already fixed?

**Comment by qarmin** [comment] 2022-01-29 08:15
Duplicate of https://github.com/godotengine/godot/issues/56546
Fixed already in master and backported to unreleased yet 3.4 and 3.5 versions

**Closed by qarmin** 2022-01-29 08:15 UTC
Labels: bug, topic:editor, crash, topic:animation

**Comment by Chevifier** [comment] 2022-02-07 02:00
For me on linux renaming node then pressing ENTER give the node a random name form other node. Workaround is to LEFT CLICK away from the node.
