### ISSUE TITLE
Execution cursor when debugging scripts.

### ISSUE THREAD

**Issue by MunWolf** [godotengine/godot#28081] opened 2019-04-16 08:38 UTC
As I have not seen this feature mentioned anywhere and it bugs me I propose adding an execution cursor to the script debugger so you can see which line will be executed next even if you move around the script while stepping.

I will be working on this and doing a PR for it.

**Comment by bojidar-bg** [comment] 2019-04-16 10:47
I'm pretty sure this is a duplicate of an earlier issue, but I cannot find it.. Anyway, keep up the good work!

**Closed** 2019-04-29 16:38 UTC
Labels: enhancement, topic:editor, topic:gdscript, usability
