### ISSUE TITLE
Shader syntax crashes the editor

### ISSUE THREAD

**Issue by nextdimension** [godotengine/godot#15951] opened 2018-01-21 19:21 UTC
**Godot version:**
Godot 3.0- RC2-custom build-mono-f5234e7-win_64

**issue**
Declare `uniform vec2 offset = vec2(0.5);` crashes the editor.

```
ERROR: Vector<union ShaderLanguage::ConstantNode::Value>::operator []: FATAL: Index p_index=1 out of size (size()=1)
   At: c:\godot\core\vector.h:147
CrashHandlerException: Program crashed
Dumping the backtrace. Please include this when reporting the bug on https://github.com/godotengine/godot/issues
[0] <couldn't map PC to fn name>
[1] <couldn't map PC to fn name>
[2] <couldn't map PC to fn name>
[3] <couldn't map PC to fn name>
[4] <couldn't map PC to fn name>
[5] <couldn't map PC to fn name>
[6] <couldn't map PC to fn name>
[7] <couldn't map PC to fn name>
[8] <couldn't map PC to fn name>
[9] <couldn't map PC to fn name>
[10] <couldn't map PC to fn name>
[11] <couldn't map PC to fn name>
[12] <couldn't map PC to fn name>
[13] BaseThreadInitThunk
-- END OF BACKTRACE --
```

**Steps to reproduce:**
Create a shader and declare `uniform vec2 offset = vec2(0.5);`

**Example**
Under effects, labelled crash. Open the shader and un-comment the line.
https://drive.google.com/open?id=1Vyg6aidyEZXnfKUJplrg8IgDkf0j3mMo

**Comment by brainsick** [comment] 2018-01-21 21:18
Dupe of #15166?

**Comment by nextdimension** [comment] 2018-01-21 21:40
Yep

**Closed** 2018-01-21 21:57 UTC
Labels: bug, topic:editor
