### ISSUE TITLE
Clicking on empty space in `TextEdit` may print error message

### ISSUE THREAD

**Issue by Rindbee** [godotengine/godot#67828] opened 2022-10-24 10:12 UTC
### Godot version

040f49ed6, v4.0.beta3.official [01ae26d31]

### System information

Linux Mint 21, Vulkan API 1.2.0, NVIDIA GeForce GTX 1050 Ti

### Issue description

If the last line is not a blank line, clicking on the blank space that exceeds the number of lines will print the following error message:
```
ERROR: Index p_column = 2 is out of bounds (text[carets[p_caret].selection.selecting_line].length() + 1 = 2).
   at: set_selection_mode (scene/gui/text_edit.cpp:4761)
```

https://user-images.githubusercontent.com/30386067/197503629-acd7e33a-540a-42bb-97c3-3743d7ea39a1.mp4

### Steps to reproduce

1. Add some text in `TextEdit`;
2. Click in the blank space below the text;
3. Observe the output panel.

**Comment by Paulb23** [comment] 2022-11-26 17:52
Closing as a duplicate of #69011 fixed by #69054.

**Closed by Paulb23** 2022-11-26 17:52 UTC
Labels: bug, topic:gui
