### ISSUE TITLE
Selection works always from top-left to bottom-right regardless mouse drag direction

### ISSUE THREAD

**Issue by martys71** [godotengine/godot#24788] opened 2019-01-05 15:32 UTC
**Godot version:**

3.1 alpha 5 x64

**OS/device including version:**

Windows 10 x64

**Issue description:**

**Steps to reproduce:**
Press and hold the LMB over the 2D/3D editor windows then drag in the top-left direction.

**Minimal reproduction project:**

**Comment by Naryosha** [comment] 2019-01-05 16:39
Can't reproduce
![ezgif-2-5b9b43d18132](https://user-images.githubusercontent.com/43379543/50726667-f35d4300-1142-11e9-8194-94964c17ad32.gif)

**Comment by akien-mga** [comment] 2019-01-05 17:11
The bug report is not really explicit about what's the actual behaviour, but if it's the one shown in #24715, it's fixed in the master branch.

**Comment by martys71** [comment] 2019-01-05 20:40
Yes, that was it. Thanks!

 

Regards,

Marcin

**Closed** 2019-01-05 22:00 UTC
Labels: bug, topic:rendering
