### ISSUE TITLE
PackedScene removes resource_path of ref when opened in Editor

### ISSUE THREAD

**Issue by donn-xx** [godotengine/godot#86918] opened 2024-01-07 12:55 UTC
### Tested versions

Reproducible - v4.3.dev1.official [9d1cbab1c]

### System information

Godot v4.3.dev1 - Ubuntu 22.04.3 LTS 22.04 - X11 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 2060 (nvidia; 535.129.03) - Intel(R) Core(TM) i5-9400F CPU @ 2.90GHz (6 Threads)

### Issue description

1. In gdscript (a ``@tool`` script) I have a ref to a PackedScene -> var PS:PackedScene = load("res://foo.tscn")
2. When I open (in the editor) the same scene (foo.tscn), the resource_path of PS becomes empty

I don't know if PS is entirely null or if it's only the resource_path that's gone, but it's no longer a useful ref to the PackedScene.

(Also, if you (as I was doing) ResourceSaver.save PS to *another* resource, it will not be an ExtResource, but instead is placed internally. This is probably a side-effect.)

### Steps to reproduce

1. Ensure sphere_scene.tscn is NOT open in the editor
  To do this in v4.3.dev1.official [9d1cbab1c] you have to:
   a. Close Godot
   b. Open .godot/editor/editor_layout.cfg and edit the open_scenes array
   c. Save that and when you restart Godot, that scene will be closed
2. Save and close Godot
3. Restart the project, open main.tscn.
4. Press "Inspect" (the boolean on the Node2D) - prints resource_path fine
5. Open sphere_scene.tscn
6. Go back to main scene, press Inspect again - resource_path is gone...

Point 6 is the mystery.

### Minimal reproduction project (MRP)

https://gitlab.com/dbat/packed_scene_issue

**Comment by KoBeWi** [comment] 2024-01-07 14:43
Looks like duplicate of #86187

**Comment by donn-xx** [comment] 2024-01-08 06:47
> Looks like duplicate of #86187

You are correct. I hope my example can help reproducibility.

**Comment by akien-mga** [comment] 2024-01-08 07:32
Consolidating in #86187.

**Closed by akien-mga** 2024-01-08 07:32 UTC
