### ISSUE TITLE
Changing blend shapes messes up all normals on glTF objects

### ISSUE THREAD

**Issue by NineAlexT** [godotengine/godot#60080] opened 2022-04-09 20:11 UTC
### Godot version

4.0 Alpha 6

### System information

Kubuntu 20.04, Nvidia GTX 1060, Driver 510, Vulkan

### Issue description

Using blend shapes on objects breaks their normals. The more blend shapes applies the worse it gets. The effect is exactly the same weather I have blender export normals or normals and tangents or neither with blend shapes. The way normals are broken is the same regardless of the blend shape applied. Having one blend shape positive and one negative cancels out the effect on normals.
No blend shapes:
![image](https://user-images.githubusercontent.com/60285548/162589903-085daeeb-20c8-4092-99d3-ec2e8d068c22.png)
Single blend shape:
![image](https://user-images.githubusercontent.com/60285548/162589911-1b832b26-7c5c-4965-a01c-c21fe86386e6.png)
Different single blend shape:
![image](https://user-images.githubusercontent.com/60285548/162589954-18822ada-b5c4-403c-b97a-0671e695e614.png)
Two blend shapes:
![image](https://user-images.githubusercontent.com/60285548/162589964-d977d277-2e39-4067-8560-7762305fc0a3.png)
All:
![image](https://user-images.githubusercontent.com/60285548/162589979-861dffea-b519-4e86-9e4c-0bf9029a210e.png)
Lighting is the same on all the above screenshots.

### Steps to reproduce

Import a glTF with blend shapes, set them from 0 to 1.

### Minimal reproduction project

[BadNormalBlends.zip](https://github.com/godotengine/godot/files/8457680/BadNormalBlends.zip)

**Comment by Calinou** [comment] 2022-04-09 23:17
Duplicate of https://github.com/godotengine/godot/issues/55812;

**Closed by Calinou** 2022-04-09 23:17 UTC
