### ISSUE TITLE
Raycast2D's get_collider returns null when is_colliding returns true

### ISSUE THREAD

**Issue by JarLowrey** [godotengine/godot#18731] opened 2018-05-09 01:56 UTC
**Godot version:**

3.0.2

**OS/device including version:**

Win10

**Issue description:**

When shooting an enemy, I check if Raycast2D `is_colliding` before using `get_collider`. However once I kill the enemy, `is_colliding` remains `true` while `get_collider` now returns null, just once, before is_colliding is set to false.

`is_colliding` is `true` but `get_collider` is `null`. If get_collider is ever null, is_colliding should be true

https://godotengine.org/qa/24987/get_collider-returns-object-freed-later-instance-avoid-script?show=24987#q24987

https://godotengine.org/qa/28264/possible-to-detect-multiple-collisions-with-raycast2d?show=28264#q28264

https://godotengine.org/qa/21861/raycast2d-detecting-collisions-when-it-shouldnt?show=21861#q21861

**Steps to reproduce:**
queue_free an object that is colliding with a RayCast2D. 

**Minimal reproduction project:**

[New Game Project3.zip](https://github.com/godotengine/godot/files/1986121/New.Game.Project3.zip)

**Comment by Zouch** [comment] 2018-05-09 17:03
I cannot reproduce this with your example code (linux compiled version with 3678762).

**Comment by JarLowrey** [comment] 2018-05-09 19:48
What happens? Have you checked the command line debugger? It worked for me yesterday, and when I checked today nothing was printed to console, only the command line debugger

**Comment by Zouch** [comment] 2018-05-09 21:15
I added more debug log to your test case (roughly)

```
func _physics_process(delta):
  if $RayCast2D.is_colliding():
    print($RayCast2D.get_collider())
  else:
    print("No collider")

func timed_out():
  print("timeout")
```

and I get an input like 

```
[Area2D:proper_id]
...
[Area2D:proper_id]
Timeout
No collider
...
```

**Comment by JarLowrey** [comment] 2018-05-09 21:26
Using your code for `_physics_process` I get the following output. 

```
...
[Area2D:962]
[Area2D:962]
[Area2D:962]
[Area2D:962]
[Area2D:962]
[Area2D:962]
[Area2D:962]
[Area2D:962]
[Object:null]
No collider
No collider
...
```

This consistently happens on every run for me. Windows 10, Godot 3.0.2

**Comment by akien-mga** [comment] 2018-08-30 13:49
I can reproduce the issue in 3.0.6. On the other hand, it seems to be fixed in the master branch.

**Comment by akien-mga** [comment] 2018-08-30 14:10
What I *can* reproduce in the master branch is the fact that even after `is_colliding` returns true, you can still get one reference to the collider RID before it's freed. I get it only when using `_process` instead of `_physics_process` That part likely can't be improved further, it's a normal limitation of RayCast2D and of any physics-bound node: any physics related change may take one frame before the actually physics state is updated.

The access to a null object might be for a similar reason, and I'm not sure why it's fixed in the master branch. Could be a happy consequence of fbc61374 / #18118.

Given that the recommended "safe" use case is fixed in the master branch (using `_physics_process` for such calls), I'll close as fixed.

**Closed by akien-mga** 2018-08-30 14:10 UTC
Labels: bug, topic:physics
