### ISSUE TITLE
Godot crashes on opening project manager after system update

### ISSUE THREAD

**Issue by juliohq** [godotengine/godot#70191] opened 2022-12-17 11:07 UTC
### Godot version

3.5.1 and 4.0 beta 8

### System information

Arch Linux, Plasma, i3-2120, RX 560

### Issue description

I get the following output after updating Arch Linux, apparently related to xcb-proto v1.15.2-2:

```
Godot Engine v4.0.beta8.official.45cac42c0 - https://godotengine.org
OpenGL Renderer: AMD Radeon RX 560 Series (polaris11, LLVM 14.0.6, DRM 3.48, 6.0.12-arch1-1)
 
[xcb] Unknown sequence number while processing queue
[xcb] You called XInitThreads, this is not your fault
[xcb] Aborting, sorry about that.
godot4: xcb_io.c:278: poll_for_event: Assertion `!xcb_xlib_threads_sequence_lost' failed.
[1]    29862 IOT instruction (core dumped)  godot4
```

### Steps to reproduce

Just open Godot 4 project manager.

### Minimal reproduction project

Open terminal and type `godot4` if your binary is under `/usr/bin/`.

**Comment by akien-mga** [comment] 2022-12-17 11:10
Duplicate of #69352.

**Closed by akien-mga** 2022-12-17 11:10 UTC
Labels: archived
