### ISSUE TITLE
Wrong input selected when pressing Enter key.

### ISSUE THREAD

**Issue by danielkariv** [godotengine/godot#71605] opened 2023-01-18 10:22 UTC
### Godot version

4.0.beta.13

### System information

MacOS 13, Macbook M1, Vulkan

### Issue description

When i try to edit inputs in inspector, it always jump back to Scene tab when pressing Enter key.
Images to showcase the bug, before:
<img width="1008" alt="image" src="https://user-images.githubusercontent.com/38776931/213144163-bde25dd7-804a-4324-a67d-c2d8e3dd6c92.png">
And after pressing Enter:
<img width="1008" alt="image" src="https://user-images.githubusercontent.com/38776931/213144186-797ae395-7152-49d7-a285-4e2836264a42.png">
It also doesn't save the input I enter, and just jump back to Scene Tab. 
This wasn't a thing before, I think it starts to show up in around beta 11, but have confirm this on beta 13.

### Steps to reproduce

Add elements to scene, and try editing inspector, and see what happens when pressing Enter.

### Minimal reproduction project

N/A

**Comment by Sauermann** [comment] 2023-01-18 10:48
Looks like a duplicate of #69160

**Closed** 2023-01-20 12:47 UTC
Labels: bug, topic:editor, regression
