### ISSUE TITLE
Bug: Cannot Change Root Node Type on New Inherited Scene from Imported .glb file

### ISSUE THREAD

**Issue by zachbugay** [godotengine/godot#94451] opened 2024-07-16 20:46 UTC
### Tested versions

- Reproducible in 4.3-beta3 [b75f0485ba15951b87f1d9a2d8dd0fcd55e178e4]

### System information

Windows 11 - Godot v4.3.beta3.official Vulkan 1.3.278 - Forward+

### Issue description

I've imported some assets from blender, into Godot 4.3-beta3. I imported the .glb files, and then created a new inherited scene. In the new inherited scene, you do not have the option to change the node type.

![image](https://github.com/user-attachments/assets/0d0a1eef-9b66-4dcc-88cd-e30b9494896c)
![image](https://github.com/user-attachments/assets/876a333a-c521-4f38-8763-e487540364d0)

### Steps to reproduce

- Add a .glb file to a brand new project. 
- Right click on it, create new inherited scene. 
- On the root node, right click, there is no option to change the type. But there is in 4.2

### Minimal reproduction project (MRP)

[bugexample.zip](https://github.com/user-attachments/files/16256438/bugexample.zip)

**Comment by Flavelius** [comment] 2024-07-17 08:01
Iirc, then the root node type is defined in the import settings, this might be why

**Comment by AThousandShips** [comment] 2024-07-17 12:03
You can't change the root type of an inherited scene, by design, see:
* https://github.com/godotengine/godot/pull/90536

Closing as this is intended behavior, and communicated via the fact that there's no such menu, see also:
* https://github.com/godotengine/godot/issues/91842

**Closed by AThousandShips** 2024-07-17 12:03 UTC
