### ISSUE TITLE
Flag trim_trailing_whitespace_on_save also remove spaces in empty lines

### ISSUE THREAD

**Issue by AndreevAndrei** [godotengine/godot#77155] opened 2023-05-17 10:47 UTC
### Godot version

3.5 stable, master

### System information

All systems (for example MacBook Pro, 16-inch, 2019, MacOS 13.1 with Intel UHD Graphics 630)

### Issue description

If user turn on flag "**trim_trailing_whitespace_on_save**" and save code like this:
<img width="153" alt="image" src="https://github.com/godotengine/godot/assets/24414592/d8b86852-d9c5-45a4-a55b-61b74b9dbca6">
He will get result like this:
<img width="153" alt="image" src="https://github.com/godotengine/godot/assets/24414592/35b8d566-bb5f-4753-9225-10ae3ed5a54a">
But result should be like this (line 5):
<img width="153" alt="image" src="https://github.com/godotengine/godot/assets/24414592/71425af8-8ed1-4c81-8019-9c3d826260a6">
It becomes very inconvenient when a large nesting of _loops_ or _match_.

### Steps to reproduce

1) Create or open any project.
2) Open project settings and make sure that "trim_trailing_whitespace_on_save" flag is setted.
3) Create or open any script.
4) Add separation-line without positive content (line that contains only whitespaces) in some function.
5) Save the file with new line.

### Minimal reproduction project

N/A

**Comment by AThousandShips** [comment] 2023-05-17 10:47
Duplicate of #74775

**Comment by AThousandShips** [comment] 2023-05-17 10:48
See #6300

**Comment by AndreevAndrei** [comment] 2023-05-17 11:17
I've fix for 3.5 version, but can't push fix as I do it before.
I'll send pull request if solve authorization problems.

**Branch 3.5**:
**godot/editor/code_editor.cpp** (line 945)
```
void CodeTextEditor::trim_trailing_whitespace() {
	bool trimed_whitespace = false;
	String spaces_below = "";
	for (int i = text_editor->get_line_count() - 1; i >= 0; i--) {
		String line = text_editor->get_line(i);
		bool empty_line = false;
		if (line.ends_with(" ") || line.ends_with("\t") || line == "") {
			if (!trimed_whitespace) {
				text_editor->begin_complex_operation();
				trimed_whitespace = true;
			}

			int end = 0;
			for (int j = line.length() - 1; j > -1; j--) {
				if (line[j] != ' ' && line[j] != '\t') {
					end = j + 1;
					break;
				}
			}
			// Lines without content should get same spaces as the line below.
			if (end == 0) {
				text_editor->set_line(i, spaces_below);
				empty_line = true;
			}
			else {
				text_editor->set_line(i, line.substr(0, end));
			}
		}

		// If the string is not empty, it will come in handy for restoring the spaces of the lines above.
		if (!empty_line) {
			for (int k = 0; k < line.length(); k++) {
				if (line[k] != ' ' && line[k] != '\t') {
					spaces_below = line.substr(0, k);
					break;
				}
			}
		}
	}

	if (trimed_whitespace) {
		text_editor->end_complex_operation();
		text_editor->update();
	}
}
```

**Comment by YuriSizov** [comment] 2023-05-17 11:30
Let's keep the discussion to one place. Since this is not a bug but intentional behavior and there is a proposal about extending the logic to cover your case, I'm going to close this issue in favor of https://github.com/godotengine/godot-proposals/issues/6300.

**Closed by YuriSizov** 2023-05-17 11:30 UTC

**Comment by AndreevAndrei** [comment] 2023-05-19 09:59
I've send a [pull request](https://github.com/godotengine/godot/pull/77230), but don't understand how to connect to actual issue (what is godot-proposals?)

**Comment by AndreevAndrei** [comment] 2023-05-19 10:02
I don't understand how could i connect to godot-proposals. For example in the end of commit is use link to this issue #77155. What i should to write in commit, to connect to https://github.com/godotengine/godot-proposals/issues/6300?

**Comment by akien-mga** [comment] 2023-05-19 10:40
```
Fix trimming indentation on empty lines with option to trim trailing whitespace

Fixes https://github.com/godotengine/godot-proposals/issues/6300
```
