### ISSUE TITLE
NavigationAgent target_desired_distance is not working properly 

### ISSUE THREAD

**Issue by Killfrra** [godotengine/godot#56813] opened 2022-01-15 12:09 UTC
### Godot version

3.5 beta 1

### System information

Ubuntu 20.04

### Issue description

In the video, the green dot indicates the position the agent is moving towards. The green zone around is the desired distance. It was assumed that the agent would reach the line (attack radius) and stop, but in reality it stops either too far or too close, depending on the direction of approach:

https://user-images.githubusercontent.com/15277964/149620884-0d4259f1-d292-48be-a890-fae0c304464c.mp4

### Steps to reproduce

Right click on the ground or the first tower to set the target position and distance.

### Minimal reproduction project

[MOBA_3.5.zip](https://github.com/godotengine/godot/files/7874909/MOBA_3.5.zip)

**Comment by Killfrra** [comment] 2022-01-15 19:11
I figured out what the problem is - `final_location` is set to the edge of the NavMesh mesh in front of the tower, because this is the nearest point to the tower center and therefore the desired distance is calculated from it, and not from the `target_location`.

**Comment by Killfrra** [comment] 2022-01-15 19:42
In addition, a situation is possible when the agent goes outside the mesh. In the video, the blue dot is target_location, the green dot is final_location, the green area is target_desired_distance. For clarity, the radius of the agent (in the settings of the mesh and the agent itself) is increased by 4 times compared to the visible one:

https://user-images.githubusercontent.com/15277964/149635573-32b8098e-b637-4641-88f2-c898bd07dec9.mp4

[MOBA_3.5_v2.zip](https://github.com/godotengine/godot/files/7875752/MOBA_3.5_v2.zip)

**Comment by smix8** [comment] 2022-05-19 16:05
@Killfrra 
When the `target_desired_distanceis` is set too large the agent will skip multiple pathpoints that are all withing this distance on each `get_next_location()` update so it is possible that the agent moves through holes in navmesh.

Since no navmesh exists under the target it will always pick the nearest valid navmesh point when you set the target location for the agent. This pick queries navmesh geometry and can be seen as very random when a target is in the very center between multiple valid points. This is why the point sometimes ends up on the agent side and sometimes on the opposite side.

Even if this would be different for your movement to work you need a different movement logic in your script. 

 `NavigationAgent.is_navigation_finished()` will trigger a path update so it will not work as accurate as you expect to stop your agent at the expected distance.

Change your is_navigation_finished() to something like this and your agent will stop where you want it to stop.

``` gdscript
# Calculate the velocity.
var is_at_target_desired_distance : bool = (pos.distance_to(target_position) - navAgent.target_desired_distance) <= 0.0
if is_at_target_desired_distance:
	if target_type == TargetType.Position:
		target_type = TargetType.None
	navAgent.set_velocity(Vector3.ZERO)
else:
	var vel = (loc - pos).normalized() * speed
	navAgent.set_velocity(vel)
```

@Calinou @akien-mga 
Can be closed as this is not a bug but setup / doc issue which we have multiple.

**Closed** 2022-05-19 16:15 UTC
Labels: bug, topic:navigation, topic:3d
