### ISSUE TITLE
`InputEventPanGesture` and `InputEventMagnifyGesture` wrongly interpreted as `InputEventMouseButton` on OSX (HTML5)

### ISSUE THREAD

**Issue by tavurth** [godotengine/godot#57676] opened 2022-02-05 22:07 UTC
### Godot version

v3.4.2.stable.official [45eaa2daf]

### System information

Mac OSX (HTML5 Version)

### Issue description

These input events are wrongly interpreted as `InputEventMouseButton` in `HTML5` exports (and debug) even though they work correctly when running the app normally.

### Steps to reproduce

1. Download the [example repository](https://github.com/tavurth/godot-pan-gesture)
2. Start in web mode to see the incorrect event type
3. Start in normal mode to see the correct event type

### Minimal reproduction project

https://github.com/tavurth/godot-pan-gesture

**Comment by Calinou** [comment] 2022-02-05 23:12
Duplicate of https://github.com/godotengine/godot/issues/13139.

**Closed by Calinou** 2022-02-05 23:12 UTC
