### ISSUE TITLE
WorldEnvironment Canvas Mode affects editor pop-ups and windows

### ISSUE THREAD

**Issue by ettiSurreal** [godotengine/godot#72223] opened 2023-01-28 02:46 UTC
### Godot version

v4.0.beta16.official [518b9e580]

### System information

Windows 11, affects both Vulkan Forward and Mobile.

### Issue description

I think it's better to just show what's happening.

Glow
![image](https://user-images.githubusercontent.com/98223724/215237915-30df1fb3-39d6-4bab-96a8-960f2da0e7d3.png)
Aces Tonemapping
![image](https://user-images.githubusercontent.com/98223724/215238027-b4a8301e-8948-4e46-a2f5-15e4dbbd81da.png)
Oversaturation
![image](https://user-images.githubusercontent.com/98223724/215238081-2ad2fcb4-122d-4412-b4af-66a690a29ff6.png)

This doesn't affect the anything that's a part of the main window, unless it is made floating.

### Steps to reproduce

1. Add a `WorldEnvironment` node.
2. Set `background_mode` in `environment` to `Canvas`
3. Change any of the settings that affect 2D.

### Minimal reproduction project

N/A

**Comment by clayjohn** [comment] 2023-01-28 02:49
Duplicate of https://github.com/godotengine/godot/issues/69122

**Closed by clayjohn** 2023-01-28 02:49 UTC
