### ISSUE TITLE
Web Editor doesn't create Project issue

### ISSUE THREAD

**Issue by ITZProGamerDieYT** [godotengine/godot#45410] opened 2021-01-24 12:57 UTC
**Godot version:**
v3.2.4.beta4.offical.b5e8b48bb

**OS/device including version:**

Windows, PC, Nvidia GTX 1060 3GB, Vulkan

**Issue description:**
"Missing Project" issue

**Steps to reproduce:**
Creating a project 

**Minimal reproduction project:**

![image](https://user-images.githubusercontent.com/42213155/105632237-d182a600-5e5a-11eb-80f8-e3f28a65ca0c.png)

![image](https://user-images.githubusercontent.com/42213155/105630933-6c2bb680-5e54-11eb-8423-aea950887b26.png)

**Comment by Calinou** [comment] 2021-01-24 13:34
@ITZProGamerDieYT Please fill in the [issue template](https://github.com/godotengine/godot/blob/master/.github/ISSUE_TEMPLATE/bug_report.md) instead of replacing it when opening issues.

**Comment by ITZProGamerDieYT** [comment] 2021-01-24 13:35
> @ITZProGamerDieYT Please fill in the [issue template](https://github.com/godotengine/godot/blob/master/.github/ISSUE_TEMPLATE/bug_report.md) instead of replacing it when opening issues.

sure

**Comment by winston-yallow** [comment] 2021-01-24 13:36
So, a workaround to this exists:

1. upload a zip of project, this will lead to "missing project" screen
2. click on "import"
3. "Browser", select the zip and confirm
4. there should now be another "Browse" for the install path
5. go into the `/projects` folder! this part is important
6. create a new folder within the `/projects` folder and confirm
7. complete the import, your project should now be available

I don't think this is intended behaviour and should be fixed. I see two possible solutions:

1. Explain this rather complex workflow to the user
2. Directly extract the zip file to a folder inside `/projects` so that there are no missing projects in the first place

I would prefer approach number 2.

**Comment by Calinou** [comment] 2021-01-24 13:46
> Directly extract the zip file to a folder inside /projects so that there are no missing projects in the first place

This requires https://github.com/godotengine/godot/pull/34444 to be merged.

**Comment by ITZProGamerDieYT** [comment] 2021-01-24 13:50
> > 1. Directly extract the zip file to a folder inside `/projects` so that there are no missing projects in the first place
> 
> This requires #34444 to be merged first.

k

**Comment by Faless** [comment] 2021-01-26 08:17
Duplicate of #44754

**Closed by Faless** 2021-01-26 08:17 UTC
Labels: discussion, platform:html5, topic:editor, usability
