### ISSUE TITLE
Shadows missing in 2.1.1

### ISSUE THREAD

**Issue by BastiaanOlij** [godotengine/godot#7154] opened 2016-11-19 00:13 UTC
**Operating system or device - Godot version:**
Godot 2.1.1, tested this on Mac OS X 10.11, tested after this was mentioned on Facebook

**Issue description** (what happened, and what was expected):
Shadows seem to be missing in 2.1.1 while they still work in 2.1

**Steps to reproduce:**
I created a simple scene with two Testcubes. Enlarged one to become a ground. Added a directional light and spotlight. Turned shadows on. 
In 2.1 I get shadows, in 2.1.1 no shadows. 

**Link to minimal example project** (optional but very welcome):
https://dl.dropboxusercontent.com/u/98707/TestScene.zip

**Comment by akien-mga** [comment] 2016-11-19 00:24
Confirmed, and the regression also affects the master branch.

**Comment by akien-mga** [comment] 2016-11-19 00:28
Regression introduced in the master branch by 0b12ebb (and f63b338 in the 2.1 branch).

**Comment by akien-mga** [comment] 2016-11-19 00:33
@SaracenOne Before I merged #1991 you mentioned that it worked fine for you in a shadow-heavy scene. Could you have a look at what causes the regression here, and whether we should just revert or if you can fix the issue?

**Comment by Ace-Dragon** [comment] 2016-11-19 01:41
From what I see there's no regression, the sunlamp panels have a field titled _Max Distance_ which controls just how far from the camera they can be calculated (anything further will not have shadows).

The issue is that it looks like the default value is 0 (so everything is too far away to receive shadows). It may be just a matter of changing it to some high number just to be safe.

**Comment by BastiaanOlij** [comment] 2016-11-19 08:46
Indeed, the max distance does the trick for me for the directional light.

How about the shadow cast for the spotlight? When I turn the directional light off the spotlight beautifully illuminates the cube in the center, but not the large cube I put in as a ground (unless its determined the entire ground is in shadow).

I can't find (but may be overlooking) the max distance.

I think a default value of zero is going to catch a lot of people unawares, it doesn't stand out much and very often zero is associated with not setting a value at all. It would probably make sense to give it at least some value, even a low conservative one.

**Comment by Sslaxx** [comment] 2016-11-19 11:49
Still counts as a bug, then. What would be a good default value?

**Comment by akien-mga** [comment] 2016-11-19 12:12
I'd be tempted to revert the commit in the 2.1 branch to keep things working as they were in 2.1-stable, and we can work on setting a safer default in the master branch (though this stuff will be obsoleted by the new renderer anyway I think), WDYT?

**Comment by reduz** [comment] 2017-08-05 18:21
this is obsolete now, closing

**Closed by reduz** 2017-08-05 18:21 UTC
Labels: bug, confirmed, topic:core
