### ISSUE TITLE
If an object is loaded with Autoload, configured position is ignored

### ISSUE THREAD

**Issue by BenjaDev** [godotengine/godot#3115] opened 2015-12-22 14:21 UTC
I tried to instance a 2D label with autoload, configured the position in the scene, where the label is created, but when i start the program, the configured position is ignored, same with font-color etc...

**Comment by kubecz3k** [comment] 2015-12-22 15:50
I'm unable to reproduce this bug in 02d6669a3849c55e415f37b23b36b49f23319957 build. Could you provide sample project?

**Comment by Paradisebird** [comment] 2015-12-23 07:57
I'm working with the nightly build from 30.10.15, maybe this bug is fixed now...thx for your answer :)

**Comment by Calinou** [comment] 2015-12-23 09:29
You can get more recent nightly builds from http://fixnum.org/godot/ or http://archive.hugo.pro/godot/.

**Comment by kubecz3k** [comment] 2015-12-23 15:00
@Paradisebird It would be great if you could verify in some free moment if this issue is already fixed in newer Godot or not. The bug seems to be quite serious and it's still possible I'm doing something different than you.

**Comment by Paradisebird** [comment] 2016-01-01 12:10
Okay, i'll make a sample project on monday, sorry for my late answer (christmas, new year, holidays, you know ;) ) Happy new year btw :)

**Comment by bojidar-bg** [comment] 2018-03-14 21:04
Going to close this issue due to the lack of activity and inability to reproduce. It will still be reopened if someone can confirm it.
@BenjaDev If you have some free time on hand, can you try doing it again with newest Godot, and maybe uploading a test project?

**Closed by bojidar-bg** 2018-03-14 21:04 UTC
Labels: bug, topic:editor

**Comment by BenjaDev** [comment] 2018-03-15 18:16
thx for your effort! i'm quite busy at the moment, will have a look at it asap!
