### ISSUE TITLE
Feature request to enable Continuous Collision Detection (CCD) for area (3D)

### ISSUE THREAD

**Issue by fian46** [godotengine/godot#26266] opened 2019-02-25 09:40 UTC
**Godot version:** 3.1

**Issue description:** right now there is no option for enabling ccd for area. why this is needed ? for example i need bullet that move and collide but no contact response. i cannot find any solution with rigid body or kinematic body. if there is any solution please give feedback and we can close this issue.

**Comment by StraToN** [comment] 2019-02-25 12:39
Duplicate of #16113 ?

**Comment by bojidar-bg** [comment] 2019-02-25 12:49
No, not a duplicate. The other issue is about RigidBody, this one is about Area.

**Comment by fian46** [comment] 2019-02-26 09:37
i just read about how ccd works and i think area cannot have ccd, my mistakes. can we make kinematic body or rigid body still detect collision but not give collision feedback ? i think this is more proper way.

**Comment by N8n5h** [comment] 2019-03-03 00:35
Did you find any workaround for this? or are we currently locked without a possibility of "Area CCD" yet?
"Area CCD" it's pretty useful to not be currently in Godot...

**Comment by fian46** [comment] 2019-03-03 00:39
yeah i find work around we can vlose this issue.

**Closed** 2019-03-03 00:43 UTC
Labels: feature proposal, topic:physics

**Comment by N8n5h** [comment] 2019-03-03 01:41
Can you post the workaround? Otherwise I think this feature request should not be closed.

**Comment by fian46** [comment] 2019-03-03 01:48
i use kinematic body move_and_collide instead of move_and_slide. more code but at least it works.

**Comment by N8n5h** [comment] 2019-03-03 01:55
But, how did you manage to get the kinematic body to give no collision feedback to make it work like an 'Area with CCD'?

**Comment by fian46** [comment] 2019-03-03 02:32
yeah it work pretty much as what i imagine it should be. i think i am already achieve the goal, so i don't need the feature any more. my goal is shoot bullet with rigid body, when it hit something it need to remove it self and spawn animation fire like effect. the problem is rigid and kinematic always bounce a little before removing it self and play animation. in my case it look weird to see bullet bounce. i try with area and move the bullet by myself but when it hit thin object it never detect stuff since already pass the frame (this is why i think i need ccd). but hey it worked now with kinematic move_and_collide and i am happy with that.

**Comment by N8n5h** [comment] 2019-03-03 03:02
Ok, cool that you found a solution to your problem. Although, the non availability for an area-like CCD is something that in my opinion could be addressed if there isn't any actual workaround to get that behavior going, so for that I think the issue should remain open.
