### ISSUE TITLE
Godot 4 - Closing Running Game, still shows remote and local tabs

### ISSUE THREAD

**Issue by nonunknown** [godotengine/godot#47643] opened 2021-04-05 12:20 UTC
**Details:**
![image](https://user-images.githubusercontent.com/58845030/113573257-262b6580-95f0-11eb-9c9e-79ef97560638.png)

**Issue description:**
After closing the running game, the editor still thinks that is running:
![image](https://user-images.githubusercontent.com/58845030/113573219-114ed200-95f0-11eb-8998-cc59f2f447f4.png)

**Steps to reproduce:**
* create a simple scene
* run game
* close

**Minimal reproduction project:**
[tt.zip](https://github.com/godotengine/godot/files/6258078/tt.zip)

**Comment by Faless** [comment] 2021-04-06 11:01
I'm unable to reproduce in current master (Linux). Can anyone confirm?

**Comment by sboron** [comment] 2021-04-22 05:35
Can confirm this on windows. I will create a pr for this

**Comment by akien-mga** [comment] 2021-04-23 07:15
Fixed by #48079.

**Closed by akien-mga** 2021-04-23 07:15 UTC
Labels: bug, confirmed, regression, topic:editor
