### ISSUE TITLE
Can't compile from master

### ISSUE THREAD

**Issue by marsmoon** [godotengine/godot#24552] opened 2018-12-22 18:11 UTC
**Godot version:**
404f39422665375e62863c0247768759bb2cd0be

**OS/device including version:**
Debian 9

**Issue description:**
After pulling the newest code, compiling with `scons platform=x11` results in this error:
```
[100%] Compiling ==> core/global_defaults.gen.cpp
core/global_defaults.gen.cpp:2:54: fatal error: platform/android/globals/global_defaults.h: No such file or directory
 #include "platform/android/globals/global_defaults.h"
                                                      ^
compilation terminated.
scons: *** [core/global_defaults.gen.x11.tools.64.o] Error 1
scons: building terminated because of errors.
```

**Steps to reproduce:**
1. Run `scons platform=x11` on master.

**Comment by akien-mga** [comment] 2018-12-22 18:16
Duplicate of #24507.

**Closed by akien-mga** 2018-12-22 18:16 UTC
