### ISSUE TITLE
Play shortcut doesn't work consistently (MacOS)

### ISSUE THREAD

**Issue by codespren** [godotengine/godot#35710] opened 2020-01-29 18:11 UTC
**Godot version:**
3.2
(Was working fine in 3.1)

**OS/device including version:**
MacOS Catalina 10.15.2

**Issue description:**
Pressing Command+B (Shortcut for Play-command in MacOS) doesn't always work. Absolutely nothing happens when shortcut is pressed. Sometimes it takes many attempts before it starts to work. Pressing Play-button with mouse however works every time.

Problems seems to occur every time when project is opened. After a few successful runs the problems occurs less often.

There's no errors in console output if Godot is started from console.

Workaround: Press Play-button with mouse instead.

**Steps to reproduce:**
1. Create new project with root node.
2. Press Command+B to run it

**Minimal reproduction project:**
Occurs with new and old projects.

**Comment by Zireael07** [comment] 2020-01-29 18:29
Duplicate of #35429?

**Comment by codespren** [comment] 2020-01-29 18:35
> Duplicate of #35429?

Yes, it’s same bug. I will close this one.

**Closed** 2020-01-29 18:35 UTC
