### ISSUE TITLE
PointLight2D's additive blend mode not working

### ISSUE THREAD

**Issue by girng** [godotengine/godot#53660] opened 2021-10-11 03:42 UTC
### Godot version

4.0.dev.20211004

### System information

Windows 10, RX 480

### Issue description

GPU version: 27.20.22025 (latest)

I think this might  be a Windows and AMD GPU issue. 
If anyone can test it with an nvidia GPU, that would be great
Apologies if it's been reported, couldn't find anything while searching.
 

### Steps to reproduce

 - Open the example project
 - Notice how the lights are not blended

https://i.gyazo.com/b2a37ba99645e79b4a897f448f1eed1c.mp4

### Minimal reproduction project

[lights_and_shadows.zip](https://github.com/godotengine/godot/files/7319370/lights_and_shadows.zip)

**Comment by Calinou** [comment] 2021-11-18 17:35
Duplicate of https://github.com/godotengine/godot/issues/49922.

**Closed by Calinou** 2021-11-18 17:35 UTC
Labels: bug, topic:rendering
