### ISSUE TITLE
Godot settings reset when exiting to project list

### ISSUE THREAD

**Issue by JamesC01** [godotengine/godot#53007] opened 2021-09-24 11:47 UTC
### Godot version

3.3.3.stable

### System information

Windows 10

### Issue description

This is a rare occurrence, but has been happening since 3.2, I believe. Sometimes, when I exit to project list, I get some errors in the console, and the project list is empty, and my settings have been reset.

Here's the error list:

ERROR: Cannot open file 'C:\Users/James/AppData/Roaming/Godot/editor_settings-3.tres'.
   At: scene/resources/resource_format_text.cpp:1232
ERROR: Failed loading resource: C:\Users/James/AppData/Roaming/Godot/editor_settings-3.tres. Make sure resources have been imported by opening the project in the editor at least once.
   At: core/io/resource_loader.cpp:282
WARNING: create: Could not open config file.
     At: editor/editor_settings.cpp:989
WARNING: cleanup: ObjectDB instances leaked at exit (run with --verbose for details).
     At: core/object.cpp:2132
ERROR: clear: Resources still in use at exit (run with --verbose for details).
   At: core/resource.cpp:450
ERROR: There are still MemoryPool allocs in use at exit!
   At: core/pool_vector.cpp:66

### Steps to reproduce

Can't really reproduce it, this has only happened around 3 times in the past 5 months.

**Comment by Calinou** [comment] 2021-09-24 11:49
Duplicate of https://github.com/godotengine/godot/issues/40968.

**Comment by Zireael07** [comment] 2021-09-24 11:50
Aha, a reoccurrence of my issue: #27124

(Be warned, in my case it was a failing ssd)

**Closed by Calinou** 2021-09-24 11:49 UTC

**Comment by JamesC01** [comment] 2021-09-24 11:52
> Aha, a reoccurrence of my issue: #27124
> 
> (Be warned, in my case it was a failing ssd)

I check crystal disk info, and it says everything is alright. That's scared me into backing up, though, so I'll probably do that soon!
