### ISSUE TITLE
sprite rotate problem !

### ISSUE THREAD

**Issue by GuyHanan** [godotengine/godot#38400] opened 2020-05-01 20:18 UTC
**Godot version:**
Godot_v3.2.1
**OS/device including version:**

**Issue description:**
sprite rotate problem:
image:
![image](https://user-images.githubusercontent.com/30537300/80837806-3973cb00-8c00-11ea-834a-06394c6dea8c.png)

i get this problem with sprite then i change the rotation degrees and i not found any way to fix this
and i not found any answer for this in the internet..

**Steps to reproduce:**
create sprite in the scene and change the rotation degrees to any Positive number then run the game!, 
**Except 0degrees, 90degrees, 180degrees, 360degrees**
(note: you need run the game to see the problem, its not happen in the editor!)

**Minimal reproduction project:**

**Comment by Calinou** [comment] 2020-05-01 20:22
If you're zooming in the 2D editor or using the `viewport` stretch mode, this is expected. You can't render pixels that are smaller than what the viewport size defines.

If this is a problem for you, switch from the `viewport` stretch mode to the `2d` stretch mode in the Project Settings.

**Comment by Cerno-b** [comment] 2022-01-25 06:06
I second what @Calinou said: For people who want pixel-precision in their game, this is pretty much the desired behaviour, because you cannot cleanly rotate a sprite while obeying the pixel grid.

If you don't want pixel perfection (I assume you don't), then there is a setting for that as @Calinou described.

**Comment by Calinou** [comment] 2022-01-25 13:37
Closing, as this is expected behavior when using the `viewport` stretch mode.

**Closed by Calinou** 2022-01-25 13:37 UTC
Labels: discussion, topic:rendering, topic:2d
