### ISSUE TITLE
TextEdit wrapmode not work

### ISSUE THREAD

**Issue by yikescloud** [godotengine/godot#74812] opened 2023-03-12 10:12 UTC
### Godot version

Godot 4.0 statble

### System information

Windows 10

### Issue description

TextEdit boundary wrapmode not works, it only removes the horizontal scrollbar

### Steps to reproduce

Add a textedit in editor, set  the wrap mode to boundary, type something.

### Minimal reproduction project

![image](https://user-images.githubusercontent.com/9168814/224538077-2efb4e67-8976-496e-9223-c460365ecc28.png)
![image](https://user-images.githubusercontent.com/9168814/224538084-af773b86-d73a-4e8b-9b66-a0fb4bde1168.png)

**Comment by AThousandShips** [comment] 2023-03-12 10:12
Duplicate of #74256

Please search for other issues before opening a bug report

**Comment by Chaosus** [comment] 2023-03-12 10:32
Duplicate of https://github.com/godotengine/godot/issues/74256

**Closed by Chaosus** 2023-03-12 10:32 UTC
