### ISSUE TITLE
How could I access gamepad accelerometer data?

### ISSUE THREAD

**Issue by alishir** [godotengine/godot#20703] opened 2018-08-04 02:08 UTC
**Godot version:** 3.0.6

**OS/device including version:** Ubuntu 16.04

**Issue description:** I want to get access to gamepad 3-Axis accelerometer vector, but I couldn't find how should I read that data from gamepad.

**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by madmiraal** [comment] 2021-04-18 12:03
Closing as this is a technical support question not a bug. Technical support questions should be asked on one of the other community channels, not here:
https://godotengine.org/community

**Closed by madmiraal** 2021-04-18 12:03 UTC
Labels: discussion, topic:input
