### ISSUE TITLE
Add the ability to add points on existing segment of polygon in Polygon 2D Editor

### ISSUE THREAD

**Issue by ZX-WT** [godotengine/godot#22826] opened 2018-10-07 13:47 UTC
**Godot version:**

3.1 alpha

**OS/device including version:**

**Issue description:**

You cannot add a point on existing segment of a polygon in the editor, you can only draw a new polygon for to add  a new point which is a terrible design... Please add the ability to add points on existing segment of polygon in Polygon 2D Editor.

**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by avencherus** [comment] 2018-10-09 00:51
> which is a terrible design... 

It probably wasn't by design, so much as overlooked in its first iterations.  X)

I agree though that it should include or match the functionality provided by the polygon canvas toolbar.  It gets clunky when there is a need for switching back and forth.

I know @groud has this editor in his sights.

You might also be interested in one of my issues regarding the tools being out of sync:  https://github.com/godotengine/godot/issues/22280

**Comment by ZX-WT** [comment] 2018-10-09 15:52
yeah, I know that it is rough/no design rather than bad design, it is so bare bone. The editor needs some love X)

**Comment by clayjohn** [comment] 2019-04-20 05:44
Is this issue still present in 3.1?

**Comment by groud** [comment] 2019-04-20 06:45
I think it has been solved

**Comment by akien-mga** [comment] 2019-04-20 08:44
Assuming fixed in 3.1, please comment if you can still reproduce the original issue.

**Closed by akien-mga** 2019-04-20 08:44 UTC
Labels: enhancement, topic:editor
