### ISSUE TITLE
Exporting to android makes Godot UI hang

### ISSUE THREAD

**Issue by blackwolf12333** [godotengine/godot#1321] opened 2015-01-31 12:41 UTC
When exporting to an android device the UI completely freezes. To the point that whenever I switch workspaces it sometimes even won't redraw. (I'm on linux)

I would guess that's because the export happens on some main drawing thread where it probably belongs in a separate thread.

**Comment by akien-mga** [comment] 2015-11-18 09:54
Can you or anyone reproduce this issue in the current master branch / nightly builds? I believe the situation may have evolved since January.

**Comment by akien-mga** [comment] 2016-04-01 09:30
Closing as old, as there was no answer from OP and I haven't seen other similar reports.

**Closed by akien-mga** 2016-04-01 09:30 UTC
Labels: bug, platform:android, topic:editor
