### ISSUE TITLE
Godot Engine crashes when I edit code in VS Code

### ISSUE THREAD

**Issue by morphine-take** [godotengine/godot#52401] opened 2021-09-04 20:27 UTC
### Godot version

v3.3.3.stable.arch_linux

### System information

Manjaro Linux 21.1.1

### Issue description

Every time when I start Godot I can edit source files in VS.Code for an hour or little shorter. Than Godot editor start repeatedly crash every time with same message:
```
╰─○ "/usr/bin/godot" --path "/home/rook/src/GODOT/godot_service_locator" -e
Godot Engine v3.3.3.stable.arch_linux - https://godotengine.org
OpenGL ES 3.0 Renderer: Radeon RX 570 Series (POLARIS10, DRM 3.41.0, 5.13.12-1-MANJARO, LLVM 12.0.1)
OpenGL ES Batching: ON
 
handle_crash: Program crashed with signal 11
Dumping the backtrace. Please include this when reporting the bug on https://github.com/godotengine/godot/issues
[1] /usr/lib/libc.so.6(+0x3cda0) [0x7fb9e6e55da0] (??:0)
[2] /usr/bin/godot(+0x2ad2797) [0x560964c53797] (??:0)
[3] /usr/bin/godot(+0x2a9e7ef) [0x560964c1f7ef] (??:0)
[4] /usr/bin/godot(+0x86456b) [0x5609629e556b] (??:0)
[5] /usr/bin/godot(+0x85823b) [0x5609629d923b] (??:0)
[6] /usr/bin/godot(+0x859286) [0x5609629da286] (??:0)
[7] /usr/bin/godot(+0x2aa11cf) [0x560964c221cf] (??:0)
[8] /usr/bin/godot(+0x2aa2117) [0x560964c23117] (??:0)
[9] /usr/bin/godot(+0x8775a6) [0x5609629f85a6] (??:0)
[10] /usr/bin/godot(+0x877f5c) [0x5609629f8f5c] (??:0)
[11] /usr/bin/godot(+0x83ee5b) [0x5609629bfe5b] (??:0)
[12] /usr/bin/godot(+0x84403a) [0x5609629c503a] (??:0)
[13] /usr/bin/godot(+0x844210) [0x5609629c5210] (??:0)
[14] /usr/bin/godot(+0x2a9ea24) [0x560964c1fa24] (??:0)
[15] /usr/bin/godot(+0x1ac4255) [0x560963c45255] (??:0)
[16] /usr/bin/godot(+0x1acf5ea) [0x560963c505ea] (??:0)
[17] /usr/bin/godot(+0x697801) [0x560962818801] (??:0)
[18] /usr/bin/godot(+0x67af24) [0x5609627fbf24] (??:0)
[19] /usr/bin/godot(+0x665e2f) [0x5609627e6e2f] (??:0)
[20] /usr/lib/libc.so.6(__libc_start_main+0xd5) [0x7fb9e6e40b25] (??:0)
[21] /usr/bin/godot(+0x66a03e) [0x5609627eb03e] (??:0)
-- END OF BACKTRACE --
[1]    16050 abort (core dumped)  "/usr/bin/godot" --path "/home/rook/src/GODOT/godot_service_locator" -e
```
Log file seems not to help
```
Godot Engine v3.3.2.stable.arch_linux - https://godotengine.org
OpenGL ES 3.0 Renderer: Radeon RX 570 Series (POLARIS10, DRM 3.41.0, 5.13.11-1-MANJARO, LLVM 12.0.1)
OpenGL ES Batching: ON
```
Everything works fine with embedded Godot text editor. I attach a screenshot with VS.Code plugin configuration
![screenshot_2021-09-05_02-19-56](https://user-images.githubusercontent.com/83418786/132107107-5c0c9970-2a0a-4f7f-ad44-54738aaf9a45.png)
... and with Godot text editor configuration
![screenshot](https://user-images.githubusercontent.com/83418786/132107180-e63df87f-ee28-4934-85a9-37b61cc26c99.png)
![screenshot2](https://user-images.githubusercontent.com/83418786/132107181-9c08a309-ba97-42c1-95bb-faaaec83b9cc.png)

### Steps to reproduce

It just crashes every time even with a brand new project. I just click on script file than work for a shorter or longer amount of time in VS.Code than Godot Engine application crashes when I edit file.

**Comment by Calinou** [comment] 2021-09-04 20:56
Duplicate of https://github.com/godotengine/godot/issues/51923.

**Closed by Calinou** 2021-09-04 20:56 UTC
