### ISSUE TITLE
curve3d /pathfollow rotation modes not working

### ISSUE THREAD

**Issue by tobiblender** [godotengine/godot#36258] opened 2020-02-16 02:02 UTC
**Godot version:**
3.2
**OS/device including version:**
win8
**Issue description:**
i use a pathFollow to move a obj along a path/curve3d 
i animate the movment by changing the > pathFollow > Unit_offset per gd-script.
i need to rotate it with the path in Y direction.
**PROBLEM 1**
therefore i want to use PathFollow > RotationMode > Y
but the object starts spinning (rotating in Y) if i move it per scipt along the path. why?
i tryed everything... cant get it to follow the path and rotate with it... it spins like a helicopter along the path... so, not usable...
this do not happen if change the offset in the editor... just if i change it per gd.script at runtime
in the editor, however, roation is also buggy... but in another way... (try offset at end of path)

**PROBLEM 2**
so wtf but okay.... i change the PathFollow > RotationMode > to "oriented"
nice - no more spinning helicopter
**BUT**
now the curve (and my obj) tilts along the curve.(to one side only)
and that tilting gets more and more the further i travel along the path. why? whats that?
BTW: the points tilts in $Path.curve.get_baked_tilts() are all 0.
thats also not natural tilting like i read in the docs... it rotates more and more to one side as i travel the path

noting works here... curve / pathfollow and rotation is not usable any way i use it... or i miss a point???? its so simple... i just change the unit_offset per gd-scipt, thats all...
i tryed for weeks now... whats wrong here?

also i cant find nothing about that on the interwebs... strange.... nobody ever used this?

**Steps to reproduce:**
make a (somewhat complex) path/3Dcurve
change the pathFollow unit_offset per gd-scipt
try the PathFollow > RotationModes

**Minimal reproduction project:**

**Comment by Calinou** [comment] 2020-02-18 12:58
Duplicate of #3713 and #27137.

**Closed by Calinou** 2020-02-18 12:58 UTC
