### ISSUE TITLE
Adding a new scene from FileSystem dock can misfire if a Scene has an @export … PackedScene

### ISSUE THREAD

**Issue by inhalt120g** [godotengine/godot#94959] opened 2024-07-30 19:29 UTC
### Tested versions

v4.3.rc1.official [e343dbbcc]

### System information

MacMini M1 with newest MacOS

### Issue description

If there's a Scene that has an
`@export var my_scene : PackedScene`
and I try to drag something from the FileSystem to it as a child, instead of getting added as a child the newly added scene will for some reason get inserted as a my_scene instead.

I understand this might be considered a feature, but then it's not consistent with how a dragged-in scene behaves when it's added to a scene that doesn't have an `@export` … PackedScene bit.

This is super annoying when I have to drag lots of scenes from FileSystem panel into the various game levels and I want to drag them directly into Nodes in specific place in the list, but then I have to first drag them somewhere randomly (wherever there are no "`@export` … PackedScene"s) and then drag them manually to where they have to be.

### Steps to reproduce

In the attached project:
Drag the following scenes to the Scenes in the Scene panel directly from the FileSystem panel:
1. Drag "Expl01" to "model parent". The Expl01 will be added to the bottom of the Scene list.
2. Drag "Expl02" to "N1": "Expl02" will be added as a child of N1.
3. Drag "Expl03" to N3. The Node will not be added to the Scene list! Instead, if you look into the N2's my_scene, it will be assigned there.
4. To make sure everything is in order with drag and dropping, go back to Expl03 and drag it into N1. Expl03 will appear as a child of N1 as expected. (edit: fixed typo)

Here is the video showing it in action (right click and Save As to avoid stuttering):
https://archive.org/download/ShowFlowFleetingWorld/画面収録%202024-07-30%2021.24.43.mov

### Minimal reproduction project (MRP)

[adding-a-new-scene-gets-swallowed.zip](https://github.com/user-attachments/files/16432504/adding-a-new-scene-gets-swallowed.zip)

**Comment by yahkr** [comment] 2024-07-31 11:59
This does seem counterintuitive, however it is consistent with exports pertaining to assets.  So this is just a case of PackedScenes pulling double duty (Can be instantiated by drag and drop, and can be assigned to exports by drag and drop where the latter takes priority in this case).

```gdscript
# Drag and drop from FileSystem populates
@export var my_texture : Texture2D
@export var my_scene : PackedScene

# Drag and drop from Scene adds it as child
@export var my_node : Node
```

**Comment by inhalt120g** [comment] 2024-07-31 15:38
(For the sake of people reading this but not watching the video or downloading the MRP: I did not drag the "Expl03" into the "@export var…" slot in the Inspector. I dragged the Scene into another Scene in the Scene list panel.)

I can't see how this behavior makes sense.

I wondered "But then what would happen if I dragged a Scene from FileSystem into a Scene that has a few "@export var … PackedScene" slots, would Godot just assign the dragged in Scene to the first available slot?"… I tried it, and instead of blindly assigning the dragged in scene to the first slot, Godot offered me a drop down list of all the "@export var … PackedScene" available for that node. So… it is indeed meant to work like that. Really baffling.

But! If I dragged in the same Scene into the upper part of the target Scene name in the Scene panel, for example here:
![image](https://github.com/user-attachments/assets/7aebda97-ffa9-485b-8a8b-2afa7a6b1b3b)
…the target scene would be highlighted but then the dragged in Scene would be added ABOVE the target scene. Basically as if I did this:
![image](https://github.com/user-attachments/assets/4ecc1aa0-a342-4923-a36c-53cb42930ae1)
So the new scene would not appear neither within the target scene (which I'd like), nor in its export (which is meant to happen). What is happening?

So the current behaviors are:

1. if I drag in a Scene into the lower part of the name, the dragged in scene gets added to an export if possible
2. if I drag a scene into the upper part of the same scene the target is missed and the dragged in scene appears elsewhere

Not sure under what circumstances could the current behaviors be considered useful, but I'd like to compose all the enemies in my game using basic enemy "skeletons" and then just add various abilities to each by dragging in and adding various weapons, equipment or "brains" directly from the FileSystem panel, so current behavior is getting in the way big time.

So yes I agree that this seems counterintuitive. But since this is obviously the intended behavior, I will propose (by posting in the Proposals) that the default behavior of this operation works more intuitively, ie that the dragged in Scene ends up where I put it, and if I want to assign something to an export, I'd like to do so myself through Inspector.

**Comment by AeioMuch** [comment] 2024-08-02 18:14
Hello. I could not reproduce it in 4.2.2, I think the regression was introduced since the change on the `_files_dropped` method in `scene_tree_dock.cpp` here : https://github.com/godotengine/godot/pull/92004

cc @timothyqiu

**Comment by timothyqiu** [comment] 2024-08-03 05:26
This is an intended behavior change rather than an regression, see https://github.com/godotengine/godot/pull/92004#issuecomment-2115031374

But I guess we can add a setting to treat `PackedScene` differently.

**Comment by inhalt120g** [comment] 2024-08-03 13:04
@timothyqiu This behavior definitely gets in the way if you want to compose your level by first populating levels with enemies, and then adding various component "modules" to them by dragging them from the FileSystem into each enemy (my case).

In fact I'd argue the current behavior is inconsistent with the basic "add a child to a target scene" operation when drag and dropping a Scene into another Scene within Scene list panel. Right now, if I drag a scene C into scene P within Scene list panel, C will become a child of P as expected. But by the "add it to the export if possible" logic, if I drag a scene C into scene P within Scene tree, instead of C becoming a child of P, C would get plugged in into one of P's exports. Surely the latter behavior would be considered wrong.

Same with copy / pasting a scene into another scene: if we follow the "add it to the export if possible" logic, the pasted scene would end up in one of the target scene exports. I think this would be very impractical.

So even though we're performing the same "adding a child to a scene" operation (by drag and dropping it into another scene), the end result is different depending on where we added the child scene from (FileSystem or Scene list panel).

**Comment by timothyqiu** [comment] 2024-08-03 13:46
We can examine the question of consistency from various perspectives, leading to potentially opposing conclusions, all of which are nonetheless valid :stuck_out_tongue: 

I understand your concerns, so I have submitted a PR to restore the old behavior.

**Comment by inhalt120g** [comment] 2024-08-03 14:13
Yes you are right. Thank you for the PR, it's appreciated!

**Closed** 2024-08-06 10:40 UTC
Labels: bug, topic:editor, regression
