### ISSUE TITLE
ColorPicker doesn't detect when the mouse button is released outside of the window.

### ISSUE THREAD

**Issue by MightyPrinny** [godotengine/godot#35185] opened 2020-01-16 04:41 UTC
**Godot version:**
3.2 beta 5

**OS/device including version:**
MXLinux19 64 bits

**Issue description:**
When the mouse is released outside of the ColorPicker while you're selecting a color and move it back it will not stop selecting colors.

**Steps to reproduce:**
Use a ColorPicker to select a color, release the mouse outside of it and then move the mouse back inside, you'll see that the color picker is still trying to pick a color at the mouse position.

**Comment by gianllucah** [comment] 2020-01-25 16:31
same problem on release 3.1.2rc3

**Comment by MightyPrinny** [comment] 2020-01-26 02:15
I just noticed that this is not true, it only happens when the mouse is released outside of the game window, which can easily happen when the color picker is at the top, because you might release the button with the cursor over the tittle bar of the window while you're trying to pick a color at the top border of the color picker.

**Comment by tobiblender** [comment] 2020-02-08 15:03
theres more to this problem...
- dragging in the color picker > try to select full white > its nearly impossible
- try to hit enter while dragging, to select that color and close the picker - it get totally funky
my dumb question... why this has not been fixed for 3.2 stable?

**Comment by Calinou** [comment] 2020-02-08 15:38
> my dumb question... why this has not been fixed for 3.2 stable?

Nobody has figured out a solution to it so far :slightly_smiling_face:

**Comment by tobiblender** [comment] 2020-02-08 15:45
ok but...  the picking does work in 3.1.2

besides that, theres no good way to close the picker in 3.1 and 3.2   (i would suggest ENTER to do so)

**Comment by Calinou** [comment] 2020-02-08 15:48
@tobiblender If you'd like the bug to be resolved faster, please bisect it so we know when the regression occurred exactly.

> besides that, theres no good way to close the picker in 3.1 and 3.2 (i would suggest ENTER to do so)

Pressing <kbd>Escape</kbd> seems to do this already (while saving the selected color).

**Comment by tobiblender** [comment] 2020-02-08 15:56
thank you, but i am not a coder... at all... ive no clue about bisect and diffs... that not at my level.
i am very busy with making games and tutorials.... bug reports and sample projects is all i can do to help.
however...
i would suggest to use ENTER to confirm the change... and ESC to cancel the change
or - if that is too much to ask... use both keys to confirm the color-change.
but ESC only is very counter-intuitive imo ;)
have a great day

**Comment by Calinou** [comment] 2020-02-08 16:01
@tobiblender You don't need to know C++ to bisect a regression. It just involves [compiling the engine from source](https://docs.godotengine.org/en/latest/development/compiling/index.html) then testing every build to find the regression.

**Comment by nathanfranke** [comment] 2021-03-20 23:20
Cannot reproduce in Godot 3.3 RC 6

**Comment by akien-mga** [comment] 2021-03-20 23:26
Thanks, closing as fixed.

**Closed by akien-mga** 2021-03-20 23:26 UTC
Labels: bug, confirmed, topic:gui, usability
