### ISSUE TITLE
New Project and Open a Directory dialogues don't close until mouse move / click X in corner

### ISSUE THREAD

**Issue by kryptot7** [godotengine/godot#28745] opened 2019-05-07 20:08 UTC
**Godot version:**
Godot 3.1.1-stable x64

**OS/device including version:**
Windows 10 Home 1803, 64-bit
Intel Core i3-7100U
8GB RAM

**Issue description:**
After you press "Cancel" on either the New Project or Open a Directory dialogues in the project manager, they don't actually close until you move the mouse around the screen (to make the editor redraw a lot, maybe?) or click the "X" button in the corner.

**Steps to reproduce:**
Open Godot.
Click New Project.
[Optional: Click Browse.]
Click Cancel.
Do nothing for a bit. Nothing will happen.
Move the mouse quickly around the screen, and the dialogue box will close. Or, just press the X button in the dialogue box's corner, and it will close.

**Minimal reproduction project:**
Not applicable

**Comment by turtletooth** [comment] 2019-05-07 22:32
This is the same issue as your previous issue.  They are both solved by updating the graphics drivers or running Godot with the --verbose flag.

**Comment by Zylann** [comment] 2021-10-30 14:07
I can't reproduce this on Windows 10 64 bits
```
Godot Engine v3.4.rc1.official.90f8cd89a - https://godotengine.org
OpenGL ES 3.0 Renderer: GeForce GTX 1060 6GB/PCIe/SSE2
OpenGL ES Batching: ON
```
Is this issue happening because of an old graphics card?

> running Godot with the --verbose flag.
What
(not the first "What" on that matter tho https://github.com/godotengine/godot/issues/52801)

**Comment by akien-mga** [comment] 2021-11-01 14:33
Duplicate of #23069

**Closed by akien-mga** 2021-11-01 14:33 UTC
Labels: topic:editor
