### ISSUE TITLE
RichTextLabel center does not work correctly all the time

### ISSUE THREAD

**Issue by puthre** [godotengine/godot#40207] opened 2020-07-08 12:49 UTC
Godot V3.2.1 Official

RichTextLabel has some issues displaying centered text. See the attached gif on how it rearranges the text when the rect size is modified.
![center](https://user-images.githubusercontent.com/38382/86920343-8f458180-c121-11ea-8214-6b66705e9e73.gif)

**Comment by akien-mga** [comment] 2020-07-08 12:50
This was fixed in 3.2.2 AFAIK.

**Comment by akien-mga** [comment] 2020-07-08 13:02
And if not, please fill the issue template and provide a reproduction project.

**Comment by pouleyKetchoupp** [comment] 2020-07-08 13:02
For info, this issue should have been fixed with #39164 (it's similar to #38846).

**Comment by puthre** [comment] 2020-07-08 13:04
Well, it seems a lot better in 3.2.2 but I can still make it look like this by dragging the rect margin.
![image](https://user-images.githubusercontent.com/38382/86921868-ba30d500-c123-11ea-9faf-80af271de4cd.png)

**Comment by puthre** [comment] 2020-07-08 13:08
I've attached the reproduction project.
[bbcode-center.tar.gz](https://github.com/godotengine/godot/files/4890801/bbcode-center.tar.gz)

**Comment by pouleyKetchoupp** [comment] 2020-07-09 07:59
CC @theoway in case you're interested in having a look.

**Comment by theoway** [comment] 2020-07-09 11:09
> CC @theoway in case you're interested in having a look.

Looks like there are some cases where it breaks. I thought I had it fixed :(
Anyways, I'll look into it and see what can be done.

**Comment by theoway** [comment] 2020-07-17 17:31
> > CC @theoway in case you're interested in having a look.
> 
> Looks like there are some cases where it breaks. I thought I had it fixed :(
> Anyways, I'll look into it and see what can be done.

Found the bug. Sorry for the delay. Will be making a PR soon.

**Comment by theoway** [comment] 2020-07-27 18:23
> 
> Found the bug. Sorry for the delay. Will be making a PR soon.

While working on it, found another bug with the width offset of wrapped lines, in the center alignment. This might take longer than I thought. God, This is a never ending nightmare. But I'll get it up & working. Bear with me.

**Closed** 2020-08-11 10:58 UTC
Labels: bug, confirmed, topic:gui
