### ISSUE TITLE
Godot 3.1 scripts order when scrollbar visible seems broken

### ISSUE THREAD

**Issue by nazgum** [godotengine/godot#26078] opened 2019-02-20 06:21 UTC
**Godot version:**
3.1 (hugo nightly from feb 15, also on prev versions)

**OS/device including version:**
Ubuntu Linux 18.10

**Issue description:**
In Editor -> Settings -> Text Editor -> Open Scripts the "Sort Scripts By: None".
With this set if you open a bunch of scripts so that the scroll bar appears, things start acting strange.

If you open either another script, or a scene that has a script attached, it will mess up the order of the scripts (sometimes reversing the whole list, sometimes placing them in odd order).  This happens pretty consistently as soon as the scrollbar is there.

With fewer scripts and no scrollbar, there seems to not be an issue.  This does not occur in 3.0 stable.

**Comment by isaacremnant** [comment] 2019-02-21 05:06
Maybe related to #23455 (which still happens in current versions).

**Comment by akien-mga** [comment] 2019-04-09 20:43
Seems a duplicate of #23455 indeed.

**Closed by akien-mga** 2019-04-09 20:43 UTC
Labels: bug, topic:editor
