### ISSUE TITLE
Remote inspector not updated when adding new "navpoly" to "NavigationPolygonInstance"

### ISSUE THREAD

**Issue by TimCarp** [godotengine/godot#40758] opened 2020-07-27 13:54 UTC
**Godot version:**
3.2.2-stable_x11.64

**OS/device including version:**
Linux Mint 20 Cinnamon

**Issue description:**
Creating a Navigation2D system entirely in script, I noticed while debugging that when giving a NavigationPolygonInstance a new "navpoly", the remote inspector is not updated. It still says "[empty]" even after setting the "navpoly" property. UPDATE: The property is correctly set, and works just fine - it just doesn't show up in the inspector.

![navpoly_godot_inspector_issue](https://user-images.githubusercontent.com/68702387/88549580-ff07a780-d00f-11ea-947b-0b73d415bc5a.png)

**Steps to reproduce:**

Try this bit of GDScript in the "_ready()" function in the main node of a new project:

```
# Create a Navigation2D node.
var navigation_2d : Navigation2D  = Navigation2D.new()
navigation_2d.name = "Navigation2D"
add_child(navigation_2d)

# Add a NavigationPolygonInstance to it.
var navigation_polygon_instance : NavigationPolygonInstance = NavigationPolygonInstance.new()
navigation_polygon_instance.name = "NavigationPolygonInstance"
navigation_2d.add_child(navigation_polygon_instance)

# Create a NavigationPolygon inside of the NavigationPolygonInstance.
navigation_polygon_instance.navpoly = NavigationPolygon.new() as NavigationPolygon
```

**Comment by Zireael07** [comment] 2020-07-27 14:07
IIRC several similar issues exist, just with different resource types?

**Comment by Calinou** [comment] 2021-03-25 20:01
Duplicate of https://github.com/godotengine/godot/issues/28353 (same cause).

**Closed** 2021-03-27 18:17 UTC
Labels: archived, bug, topic:editor
