### ISSUE TITLE
Setting Node3D.GlobalRotation will also reset its scale

### ISSUE THREAD

**Issue by guessy42** [godotengine/godot#72054] opened 2023-01-25 16:12 UTC
### Godot version

Godot Engine v4.0.beta14

### System information

Windows 10, Vulkan

### Issue description

Setting a Node3D's GlobalRotation property will also reset its scale to 1,1,1.

While I'm given to believe this is the result of global scale/rotation being combined in the same matrix, the documentation should mention it if this is the intended behaviour.

### Steps to reproduce

1. Have a Node3D with a non-default scale (eg 10,10,10 or something)
2. In code, set its GlobalRotation property
3. Check the new scale

```
Scale = new Vector3(2, 2, 2);
GD.Print("Scale pre-rotation is " + Scale);
GlobalRotation = new Vector3(30, 0, 0);
GD.Print("Scale post-rotation is " + Scale);
```

### Minimal reproduction project

N/A

**Comment by AntonioDell** [comment] 2023-03-24 19:51
This happens on Pop OS! 22.04 too. When setting the global_rotation of a Sprite3D the scale is set to (1,1,1).

Example project:
[rotation_affects_scale.zip](https://github.com/godotengine/godot/files/11066127/rotation_affects_scale.zip)

**Comment by Calinou** [comment] 2023-03-24 20:14
I can confirm this on 4.0.stable (Linux) with the MRP linked above.

**Comment by AThousandShips** [comment] 2023-03-25 08:45
`Node3D` discards scale when setting the global rotation, but I think this might be because it's not straightforward to extract the scale, setting the local scale works differently because the different components are tracked separately

**Comment by AThousandShips** [comment] 2023-03-25 08:51
Also: #74162

**Comment by Calinou** [comment] 2023-03-25 17:11
- Duplicate of https://github.com/godotengine/godot/issues/74162.

**Closed by Calinou** 2023-03-25 17:11 UTC
Labels: bug, topic:core, confirmed
