### ISSUE TITLE
Editor docs are broken

### ISSUE THREAD

**Issue by Chaosus** [godotengine/godot#12564] opened 2017-11-01 17:55 UTC
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
latest master

**Issue description:**
Looks like GDScript doc is broken inside the editor
![image](https://user-images.githubusercontent.com/3036176/32289052-c0a7b9a8-bf46-11e7-9f09-eeb4f95a1a63.png)

**Comment by akien-mga** [comment] 2017-11-01 17:59
Could be a regression from #12025 merged today, cc @leezh

**Comment by Chaosus** [comment] 2017-11-01 18:24
Looks like a Node has this problem too.. 

![image](https://user-images.githubusercontent.com/3036176/32290396-f80be564-bf4a-11e7-979d-da7b6c2754e7.png)

**Comment by djrm** [comment] 2017-11-01 18:26
this used to happen after a multi line code block.

**Comment by NathanWarden** [comment] 2017-11-01 18:31
I think this is a new "condensed documentation" feature 😆

**Comment by PaulTaulborg** [comment] 2017-11-01 19:10
Coincidentally right after people were talking about easier access to doc changes on facebook. Seems to me, like there is a rogue godot dev fucking everything up.  @akien-mga should be more vigilant

**Comment by leezh** [comment] 2017-11-01 19:43
Crap, I didn't test it on multiline code blocks. :/ Sorry for the breakages.

**Comment by leezh** [comment] 2017-11-01 19:51
Undid my commit and confirmed it was my change that did it. Still finding out the root cause, because changing white-space shouldn't do that.

Also, @PaulTaulborg, no, I'm not a rouge dev maliciously doing this.

**Comment by leezh** [comment] 2017-11-01 20:28
Okay, so this is very weird:
![1](https://user-images.githubusercontent.com/185322/32296113-3d26ce12-bf86-11e7-8065-2efd1ac09a75.png)
![2](https://user-images.githubusercontent.com/185322/32296121-44cede66-bf86-11e7-900d-d435ca5fb97c.png)

**Comment by leezh** [comment] 2017-11-01 21:13
So I think while #12025 isn't the cause of the bug, it does very clearly expose it. For now we should replace
https://github.com/godotengine/godot/blob/025f13856138918b13956b085a586a73a584bc04/editor/doc/doc_data.cpp#L620

with a simple `return string.strip_edges();` until we fix this problem.

**Comment by djrm** [comment] 2017-11-01 23:45
@leezh the problem are indeed the double newlines, thats the reason why i removed them, causing the text on block to look a bit indented, but it solved the problem with multiline blocks, i could not figure out what the problem was with them (and also it does not make sense to do such replacement anyway)

**Comment by leezh** [comment] 2017-11-02 00:29
I'm currently digging into the problem. At the moment I can reliably re-create it with any RichTextLabel using `RichTextLabel.newline()`. This isn't a bug isolated to the editor, and it isn't related to the dedent function I added.

And I disagree that padding out newlines with white-space is the solution to this, nor is getting rid of double-newlines in the docs.

RichTextLabel isn't behaving as it should and therefore should be fixed there.

Hopefully once I've fixed this we can back-port it to 2.1 because it seems to be affected there as well.

**Comment by djrm** [comment] 2017-11-02 00:33
@leezh getting rid of double newlines is how it has to behave, if you want to have a double space, then you use double space, there is no point in converting to double newline, thats not how it is supposed to work simple as that, maybe there is a bug, but double newlines are wrong.

**Comment by leezh** [comment] 2017-11-02 00:54
There. Fixed it the proper way rather than sweeping the problem under the rug.

**Comment by djrm** [comment] 2017-11-02 00:57
@leezh still, docs do not need double newlines inserted.

**Comment by leezh** [comment] 2017-11-02 01:01
Is what you're suggesting removing `.replace("\n", "\n\n")` and adding paragraph spacing to the XML docs themselves as appropriate? Because I understand that now.

**Comment by djrm** [comment] 2017-11-02 01:05
@leezh yeah, thats how it works in the web version.

**Comment by leezh** [comment] 2017-11-02 01:08
Okay. Sounds good. Once #12575 merges, would you like me to do it?

**Closed** 2017-11-02 06:56 UTC
Labels: bug, topic:editor

**Comment by leezh** [comment] 2017-11-02 22:08
Oh, also @djrm sorry if I seemed a bit harsh against you.

I was quite upset that people's response to "double-newlines in RichText broke docs" was to work around it (in a silly manner which now needs cleaning up) rather than find and fix the cause of it. It's fine if you need to ship a game within a deadline, but you don't do that in a library.

Anyways, I realised that it was wrong of me to redirect that anger towards you.

**Comment by djrm** [comment] 2017-11-02 22:17
@leezh nah, no problem
