### ISSUE TITLE
Cyclical reference makes Godot unable to open the project

### ISSUE THREAD

**Issue by axo-lotl** [godotengine/godot#56481] opened 2022-01-04 09:44 UTC
### Godot version

4.0.dev (20211210 version)

### System information

Windows 10

### Issue description

It seems that if a project contains typed objects with class_name script that cyclically reference each others' class_names, then the project is unable to open.

This only happens on the 2021/12/10 dev build from what I've seen, I've also tested on 2021/11/08 and the issue doesn't occur.

### Steps to reproduce

There are many variations on how create cyclical references, here's just what I did:
1. Create a new project with at least one scene.
2. Create a script A, extending Node.
3. Create a script B, extending Node.
4. Add a new member variable to script A of type B.
5. Add a new member variable to script B of type A.
6. Save and close the project.
7. Try to reopen the project; it should crash.

### Minimal reproduction project

[Bug_Cyclical_Reference.zip](https://github.com/godotengine/godot/files/7806700/Bug_Cyclical_Reference.zip)

**Comment by NNesh** [comment] 2022-01-06 03:11
I cannot reproduce in the bb4157a build.

**Comment by axo-lotl** [comment] 2022-01-07 23:25
Neither could I, perhaps this should be closed?

**Comment by Calinou** [comment] 2022-01-08 00:03
Closing per @axo-lotl's request.

**Closed by Calinou** 2022-01-08 00:03 UTC
Labels: bug, topic:gdscript, crash, regression
