### ISSUE TITLE
ViewportContainer

### ISSUE THREAD

**Issue by danicrem** [godotengine/godot#38573] opened 2020-05-08 17:32 UTC
Godot_v3.2.1-stable_win64

GLES2

Windows 10

When I add a ViewportContainer to the scene, it comes with a margin of 40 right and bottom. If I revert this to 0, the containers malfunctions.

My project looks like this:
Ad a Node2d. Attach a script with 
func _process(delta):
	var texture = get_node("ViewportContainer/Viewport").get_texture()
	get_node("screen").texture = texture

Project setup:
Ad a sprite (big image as backgroudn). Add another sprite and name it screen.
Add the ViewportContainer. Add a Viewport as child of the container. Then add a Spacial node to the Viewport (a 3d scene. Does not matter how it looks like). Now press play and the 3d scene is in front of the background image.
Now go to the ViewportContainer and change the margins to 0. Now the 3d is not in front of the background sprite anymore.

**Comment by aaronfranke** [comment] 2020-05-08 18:54
Please attach a minimal reproduction project.

**Comment by danicrem** [comment] 2020-05-08 22:09
[test3d.zip](https://github.com/godotengine/godot/files/4601940/test3d.zip)

**Comment by aaronfranke** [comment] 2020-05-08 22:58
The purpose of ViewportContainer is to automatically set the size of its child Viewport. If the ViewportContainer has a size of 0, then so will the Viewport.

In this case, you don't actually need a ViewportContainer, since you're already using the Viewport's texture by assigning it to a Sprite. Here's the project you posted with the ViewportContainer removed: [test3d-fixed.zip](https://github.com/godotengine/godot/files/4602087/test3d-fixed.zip)

By the way, you generally shouldn't mix Control nodes (the green ones) with Node2D (the blue ones).

Closing this issue because I don't think there's any bug with Godot here. It seems that everything is working as intended.

**Closed by aaronfranke** 2020-05-08 22:58 UTC
