### ISSUE TITLE
Extracting a material that contains an embedded texture from a GLTF file generates a huge material

### ISSUE THREAD

**Issue by antourenein** [godotengine/godot#65566] opened 2022-09-09 10:55 UTC
### Godot version

4.0.alpha16

### System information

Windows 10, Vulkan, NVIDIA GTX 850M

### Issue description

When importing a GLTF file and extracting its materials, the specific materials that have an embedded texture are insanely huge in file size, depending on texture resolution.

I assume the textures are somehow being imported as bitmap without any kind of compression. In big scenes this causes an unbearable stutter as the game tries to read these huge textures from disk.

### Steps to reproduce

Get a GLTF file with a material containing a texture (or export one from blender), double-click the file to open the advanced import and extract materials. The extracted material has a huge file size, in relation to what would be expected from the texture resolution.

If you change the texture in the extracted material for one imported separately and save the material, the file size changes to the usual 1KB. The culprit seems to be the imported texture.

### Minimal reproduction project

Simple textured box glb file: 
[texture-box.zip](https://github.com/godotengine/godot/files/9534695/texture-box.zip)

Try importing it and extracting its material.

The glb file has a file size of 537KB, and a material with a 4K texture embedded in it. The extracted material somehow ends up with a file size of 318MB, which is absolutely huge.

**Comment by Calinou** [comment] 2022-09-09 15:54
Duplicate of https://github.com/godotengine/godot/issues/62436.

**Closed by Calinou** 2022-09-09 15:54 UTC
