### ISSUE TITLE
SkeletonModification2DJiggle always give warnings and errors when created

### ISSUE THREAD

**Issue by Zoomulator** [godotengine/godot#75817] opened 2023-04-08 10:26 UTC
### Godot version

4.0.2

### System information

Windows 10

### Issue description

A correctly configured SkeletonModification2DJiggle will give errors about updating caches when the skeleton is instanced.

![image](https://user-images.githubusercontent.com/1069303/230716043-2402ad1a-e157-4524-b9d4-e441d3c20847.png)

### Steps to reproduce

1. Create a scene with a Skeleton2D containing a Bone2D, as well as a Marker2D.
2. Create a Modification Stack for the Skeleton2D
3. Check Enable on the Modification Stack
4. Add a SkeletonModification2DJiggle to the stack
5. Select the Marker2D as Target Nodepath
6. Increase Jiggle Data Chain Length to 1
7. Under Joint Data -> 0, set Bone 2D Node to the Bone2D in the skeleton
8. Start the scene and check the debugger's Errors tab

I've attempted different sorting of the nodes but they all generate the same errors. E.g. putting the marker before, after and even inside the Skeleton2D all results in the same errors.

### Minimal reproduction project

[JiggleBoneNodeCache.zip](https://github.com/godotengine/godot/files/11183000/JiggleBoneNodeCache.zip)

**Comment by Zoomulator** [comment] 2023-04-16 09:51
Seems related to #75022, #73247 and #73168

**Comment by Calinou** [comment] 2023-05-08 17:37
- Duplicate of https://github.com/godotengine/godot/issues/73247 (same cause).

**Closed by Calinou** 2023-05-08 17:37 UTC
