### ISSUE TITLE
Godot crash using shader editor

### ISSUE THREAD

**Issue by JordanMotta** [godotengine/godot#20917] opened 2018-08-11 13:21 UTC
**Godot version:**
v3.0.5.stable.official.6a88e22

**Issue description:**
When i write `uniform vec4 train_color : hint_color = vec4(1.0);`, Godot gets crash.

**Steps to reproduce:**
Just remove `//`.

**Minimal reproduction project:**
[material script.zip](https://github.com/godotengine/godot/files/2280256/material.script.zip)

![scene](https://user-images.githubusercontent.com/11588333/43992121-c8cfd8e2-9d47-11e8-8290-b4b7c3600294.png)

**Comment by ippan** [comment] 2018-08-13 03:26
have same issue on master HEAD (15530ce)

here the call stack:

|File|line|code|
|---|---|---|
|rasterizer_storage_gles3.cpp|2874|_update_material(material);|
|rasterizer_storage_gles3.cpp|7700|update_dirty_materials();|
|visual_server_scene.cpp|3361|VSG::storage->update_dirty_resources();|
|visual_server_scene.cpp|3393|update_dirty_instances();|
|visual_instance.cpp|151|VisualServer::get_singleton()->free(instance);|
|memory.h|118|p_class->~T();|

**Comment by nobuyukinyuu** [comment] 2018-08-13 20:33
dupe of #15166

**Closed** 2018-08-13 20:34 UTC
