### ISSUE TITLE
Tilemap tile flipping shortcuts not working

### ISSUE THREAD

**Issue by SolarLune** [godotengine/godot#15145] opened 2017-12-29 06:19 UTC
**Godot version:** Daily build, 12-28-17

**OS/device including version:** Linux, Solus OS, 3.26.2

**Issue description:** The tooltips for tile flipping in Godot for TileMaps say that A and S can be used to flip a tile, but those shortcuts don't work. S is used to toggle snapping, not rotation of tiles. 

As a side-note, it'd probably be better to have A and S _rotate_ the tile, and have two different, similarly placed shortcuts (like Q and W, or something) _flip_ the tile for maximum efficiency when editing a TileMap.

- [x] I searched the existing [GitHub issues](https://github.com/godotengine/godot/issues?utf8=%E2%9C%93&q=is%3Aissue+) for potential duplicates.

**Comment by bojidar-bg** [comment] 2017-12-29 15:18
Just to mention it, "Select", "Duplicate Selection", and "Erase Selection" tilemap shortcuts seem to not work either.

**Comment by poke1024** [comment] 2018-01-10 20:25
Might be because of https://github.com/godotengine/godot/issues/12505

**Comment by guilhermefelipecgs** [comment] 2018-04-03 19:40
Tested now with 9ad180029876a53747df577d8925a055f6b9687e and it's fixed.

**Comment by akien-mga** [comment] 2018-04-03 20:05
Thanks - is it still valid in 3.0.2?

**Comment by guilhermefelipecgs** [comment] 2018-04-03 20:25
Yes, in 3.0.2 the hotkeys doesn't work yet.

**Comment by akien-mga** [comment] 2018-04-04 07:58
Duplicate of #16293 (newer but broader).

**Closed by akien-mga** 2018-04-04 07:58 UTC
Labels: bug, topic:editor, usability
