### ISSUE TITLE
Wrong elements size after changing default editor font.

### ISSUE THREAD

**Issue by Chtobi** [godotengine/godot#4145] opened 2016-03-26 13:40 UTC
Windows 7 x64
Godot v2.0.1 stable.official

Size of window elements in some dialogs looks wrong after changing default Text Editor font and Global font to Times New Roman, 16 pt.

![bug1](https://cloud.githubusercontent.com/assets/12411232/14060298/de9715c4-f370-11e5-964a-c59fafe3b1aa.png)

Probably, because of this I can't click buttons Find and Cancel in the Search window, though they could be accessable with Tab.

![bug2](https://cloud.githubusercontent.com/assets/12411232/14060304/1c553774-f371-11e5-8020-b7107e15df3f.png)

**Comment by neikeq** [comment] 2016-03-26 15:45
Duplicate of #1893

**Closed** 2016-03-26 15:46 UTC
Labels: bug, topic:editor
