### ISSUE TITLE
Crash on launch: failed init DINPUT: -2147467259

### ISSUE THREAD

**Issue by Duobix** [godotengine/godot#39140] opened 2020-05-29 07:39 UTC
**Godot version:**
3.2.1 x64/x32 Windows exe

**OS/device including version:**
Windows 10.0.18362.836 / OpenGL ES3.0 

**Issue description:**

I launched the version downloaded from itch.io.

**Steps to reproduce:**
Just launch 3.2.1 x64/x32 on my machine, it just outputs:
"
Godot Engine v3.2.1.stable.official - https://godotengine.org
OpenGL ES 3.0 Renderer: GeForce GTX 1060 6GB/PCIe/SSE2
failed init DINPUT: -2147467259
"
and stops working (exits to system)

**Minimal reproduction project:**
3.2.1 just does that on my machine with the log above.

**Comment by Calinou** [comment] 2020-05-29 07:46
Duplicate of #36662.

**Closed by Calinou** 2020-05-29 07:46 UTC
