### ISSUE TITLE
Error opening VS Code as external editor 

### ISSUE THREAD

**Issue by KellyThomas** [godotengine/godot#34723] opened 2020-01-01 06:42 UTC
**Godot version:**
3.2.beta4.mono.offical
**OS/device including version:**
Windows 10
**Issue description:**
When trying to open a C# file in VS Code the application fails to launch and this message is displayed in both the output panel and console window:
```
ERROR: godot_icall_GD_pusherror: Error when trying to run code editor: VSCode. E
xception message: 'ApplicationName='C:\Users\Kelly\AppData\Local\Programs\Micros
oft VS Code\bin\code', CommandLine='d:/projects/NewTestProject/ -g d:/projects/N
ewTestProject/Node.cs:1:0', CurrentDirectory='', Native error= %1 is not a valid
 Win32 application.
```
This PC has VS Code installed and it can be launched by typing either of these on the command line:
```
code
"C:\Users\Kelly\AppData\Local\Programs\Microsoft VS Code\bin\code"
```

**Steps to reproduce:**

1. Using `Editor` > `Editor Settings` > `Mono` > `Editor` > `External Editor` select `Visual Studio Code`.
2. Using the `FileSystem` panel right-click on a .cs file and select `Open`

**Comment by neikeq** [comment] 2020-01-01 14:53
Duplicate of #34434, which was already fixed.

**Closed by neikeq** 2020-01-01 14:53 UTC
Labels: bug, topic:mono

**Comment by KellyThomas** [comment] 2020-01-01 21:58
Sorry, I missed that one when I searched.
