### ISSUE TITLE
Adding an .mp3 while the project is open makes Godot crash

### ISSUE THREAD

**Issue by venilark** [godotengine/godot#71281] opened 2023-01-12 18:36 UTC
### Godot version

4.0 beta 11

### System information

Windows 10

### Issue description

I pasted an .mp3 file in the Windows File manager, after returning to Godot, it crashed although it did create the .import file.
Tried with a picture of similar size, it didn't crash.

### Steps to reproduce

Read above.

### Minimal reproduction project

.

**Comment by Calinou** [comment] 2023-01-12 20:24
Related to https://github.com/godotengine/godot/issues/69983 (although OP was able to import MP3 but not WAV in that issue).

**Comment by venilark** [comment] 2023-01-12 21:10
I did lots of tests and it seems the crash only happens with files larger than 2 or 3 MB, for sure with 5 and above it crashes.
Also tried removing metadata tags and no luck.

**Comment by venilark** [comment] 2023-01-13 19:42
Same in Beta 12.

**Comment by venilark** [comment] 2023-01-19 11:36
Same in Beta 13.

**Comment by akien-mga** [comment] 2023-01-19 21:26
I can't reproduce, imported 20 MP3 files in the 7-15MB range each, no crash.

Could you attach a file that reproduces the issue reliably for you?

Alternatively, are you able to compile Godot from source (with debug symbols, i.e. `scons p=windows target=editor debug_symbols=yes`) to get a stacktrace pointing out at the crashing line?

**Comment by tobeks** [comment] 2023-02-02 00:44
master 0a9e6e478e3183d7bf3c5cb895c706bc6275d3ea

I have similar problem with importing WAV files.

Scenario:
1. Create new project,
2. switch to the windows explorer,
3. copy about 20-30 copies of attached file (extracted)
4. focus on godot window.

Result:
Crash just after importing files with following callstack:

```
godot.windows.editor.x86_64.exe!AudioStreamPlaybackWAV::do_resample<short,1,0>(const short * p_src, AudioFrame * p_dst, __int64 & offset, int & increment, unsigned int amount, AudioStreamPlaybackWAV::IMA_ADPCM_State * ima_adpcm) Line 178
	at C:\godot2\scene\resources\audio_stream_wav.cpp(178)
godot.windows.editor.x86_64.exe!AudioStreamPlaybackWAV::mix(AudioFrame * p_buffer, float p_rate_scale, int p_frames) Line 379
	at C:\godot2\scene\resources\audio_stream_wav.cpp(379)
godot.windows.editor.x86_64.exe!EditorAudioStreamPreviewPlugin::generate(const Ref<Resource> & p_from, const Vector2 & p_size) Line 620
	at C:\godot2\editor\plugins\editor_preview_plugins.cpp(620)
godot.windows.editor.x86_64.exe!EditorResourcePreviewGenerator::generate_from_path(const String & p_path, const Vector2 & p_size) Line 69
	at C:\godot2\editor\editor_resource_preview.cpp(69)
godot.windows.editor.x86_64.exe!EditorResourcePreview::_generate_preview(Ref<ImageTexture> & r_texture, Ref<ImageTexture> & r_small_texture, const EditorResourcePreview::QueueItem & p_item, const String & cache_base) Line 160
	at C:\godot2\editor\editor_resource_preview.cpp(160)
godot.windows.editor.x86_64.exe!EditorResourcePreview::_iterate() Line 250
	at C:\godot2\editor\editor_resource_preview.cpp(250)
godot.windows.editor.x86_64.exe!EditorResourcePreview::_thread() Line 328
	at C:\godot2\editor\editor_resource_preview.cpp(328)
godot.windows.editor.x86_64.exe!EditorResourcePreview::_thread_func(void * ud) Line 100
	at C:\godot2\editor\editor_resource_preview.cpp(100)
godot.windows.editor.x86_64.exe!Thread::callback(Thread * p_self, const Thread::Settings & p_settings, void(*)(void *) p_callback, void * p_userdata) Line 67
	at C:\godot2\core\os\thread.cpp(67)
[External Code]
godot.windows.editor.x86_64.exe!thread_start<unsigned int (__cdecl*)(void *),1>(void * const parameter) Line 97
	at minkernel\crts\ucrt\src\appcrt\startup\thread.cpp(97)
[External Code]
```

From my observations:

- Crash is not triggered with different wav files
- Works only for multiple files being imported

[a2.zip](https://github.com/godotengine/godot/files/10563677/a2.zip)

**Comment by Calinou** [comment] 2023-02-02 14:31
Related to https://github.com/godotengine/godot/issues/40320.

**Comment by venilark** [comment] 2024-01-09 12:38
Godot 4.2.1, imported lots of mp3s at once, of several MBs each, not a single crash. At least with MP3s it seems resolved but don't know if it still happens with .wav

**Comment by Calinou** [comment] 2024-01-09 23:34
Thanks for the update! I'll close this then. There's another open issue related to WAV import: https://github.com/godotengine/godot/issues/40320

**Closed by Calinou** 2024-01-09 23:34 UTC
Labels: bug, confirmed, topic:audio, topic:import, crash
