### ISSUE TITLE
3.5.3 export produces corrupted .pck file

### ISSUE THREAD

**Issue by lekoder** [godotengine/godot#82622] opened 2023-10-01 12:37 UTC
### Godot version

3.5.3-stable

### System information

Windows 10

### Issue description

After upgrading ΔV: Rings of Saturn's engine from Godot 3.5.2 to 3.5.3, the project fails to export. The export produces a corrupted .pck file that doesn't boot at all. Game works just fine from the editor.

![obraz](https://github.com/godotengine/godot/assets/1224527/05d74b24-5ede-414b-84f1-5e5b8d8a897a)
![obraz](https://github.com/godotengine/godot/assets/1224527/52b4e652-518b-478a-b318-7fc5e0c7e689)

During --verbose export with:
```
$ "$GODOT" --verbose --no-window --export "Windows Desktop" $OUTDIR/windows/Delta-V.exe $PROJECT
```

...a bunch of file write errros can be found in the output:

```
        savepack: step 77: Storing File: res://ships/k225-mask-rad.png.import
        savepack: step 77: Storing File: res://.import/k225-mask.png-c3b02e1f7a74549458d12ff3274c9f07.stex
        savepack: step 77: Storing File: res://ships/k225-mask.png.import
(drivers/windows/file_access_windows.cpp:301)
ERROR: Condition "fwrite(p_src, 1, p_length, f) != (size_t)p_length" is true.
   at: store_buffer (drivers/windows/file_access_windows.cpp:301)
ERROR: Condition "fwrite(p_src, 1, p_length, f) != (size_t)p_length" is true.
   at: store_buffer (drivers/windows/file_access_windows.cpp:301)
ERROR: Condition "fwrite(p_src, 1, p_length, f) != (size_t)p_length" is true.
   at: store_buffer (drivers/windows/file_access_windows.cpp:301)
```
Do note that they are cut by the verbose output (stdin/stderr) so there is probably some asynchronous problem going on and they might not relate directly to files listed.

I have tried to remove and reimport the assets (removing the `.import` folder), without any visible change.

This affects both the custom-compiled version of the engine (with GodotSteam and GodotGOG plugins), as well as the official stable build (which also contains additional errors from the lack of required plugins). Attaching full outputs from both tries.

[Output from custom build export](https://github.com/godotengine/godot/files/12777135/godot-3.5.3-export-fsckup-custom.txt)
[Output from the official stable export](https://github.com/godotengine/godot/files/12777136/godot-3.5.3-export-fsckup-official.txt)

### Steps to reproduce

Export my project. It fails to export both from command line and from the editor.

Unfortunately, I was not able to narrow this futher.

### Minimal reproduction project

Unfortunately, I don't even know where to start trying to replicate this in MRP, short of exporting my full game project. Any guidance on what to check would be appreciated.

**Comment by lekoder** [comment] 2023-10-01 12:51
Bisecting the Godot source to find the offending commit, this will probably be useful.

**Comment by lekoder** [comment] 2023-10-01 17:31
I have some very strange results from my bisection, which actually suggest that this is not directly related to the Godot build but rather either my own environment or project files that are not tracked by git (ie. `.import`).

After hours of bisecting and rebuilding the engine (and having my export consistently fail time after time), I came upon a version that worked. The "bad commit", however, looked innocent. I checked the one after it and found it to build successfully. I also checked the exact initial binaries that failed and found them working as intended this time - which is convincing evidence that this is not an issue directly related to the build.

Feel free to close this issue; I'll re-open it if I have evidence that this is something you can do something about.

**Comment by rick551a** [comment] 2023-10-01 18:50
Just tested 3.5.3 mono exporting 'windows desktop' with a few projects with .pck & .,exe and found no probs.

FYI I encountered an error like this a while ago and faintly remember deleting my 'Windows Desktop' template & recreating it again, or re-importing the export templates and this worked.

**Comment by Calinou** [comment] 2023-10-01 20:08
Closing per the above comments. Please comment if you can find definitive reproduction steps.

**Closed by Calinou** 2023-10-01 20:08 UTC
Labels: bug, topic:core, regression

**Comment by Alex-Sand-0** [comment] 2024-04-28 21:08
Hi,
In case it helps I just had a very similar issue; it seems it was caused by *my /c drive being almost full* ; and just fixed itself after I freed some space on this drive.
