### ISSUE TITLE
RichTextLabel get_content_height() doesn't return the correct value on time

### ISSUE THREAD

**Issue by Nobelix** [godotengine/godot#36540] opened 2020-02-25 19:38 UTC
**Godot version:**
3.2 stable
**OS/device including version:**
Manjaro
**Issue description:**
`get_content_height()` in the RichTextLabel doesn't not return the correct value on time.

**Steps to reproduce:**
For example lets say I have one line that makes the content height equal to 40.
Then in a script I change the text to something that will make the content height equal to 80 (2 lines) but if I call `get_content_height()` just after assigning the value it will still return 40.

**Comment by Calinou** [comment] 2020-02-25 21:16
Duplicate of #36381.

**Closed by Calinou** 2020-02-25 21:16 UTC
Labels: bug, topic:gui
