### ISSUE TITLE
Duplicating a Node doesn't duplicate Extra Call Arguments

### ISSUE THREAD

**Issue by sammyf** [godotengine/godot#84402] opened 2023-11-03 10:04 UTC
### Godot version

v4.1.2.stable.arch_linux

### System information

Archlinux, Godot v4.1.2.stable unknown - Arch Linux #1 SMP PREEMPT_DYNAMIC Thu, 26 Oct 2023 00:52:20 +0000 - X11 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3090 (nvidia; 535.113.01) - Intel(R) Core(TM) i7-10700K CPU @ 3.80GHz (16 Threads)

### Issue description

Extra parameters set in the editor for a signal on a node are not duplicated when the node is duplicated

### Steps to reproduce

I have a button node with a signal on button_up()  and an extra parameter

![image](https://github.com/godotengine/godot/assets/42468608/892307a9-b314-45ee-81ac-e5333d32e7a5)

If I duplicate the node  using CTRL+D the signal is duplicated but lacks the parameter.

![image](https://github.com/godotengine/godot/assets/42468608/ada18175-620d-4bb1-b3bd-29bcffea380c)

### Minimal reproduction project

N/A

**Comment by AThousandShips** [comment] 2023-11-03 11:35
Duplicate of https://github.com/godotengine/godot/issues/75105

**Closed by AThousandShips** 2023-11-03 11:35 UTC
