### ISSUE TITLE
Editor binary loads project in subfolder next to the binary instead of project manager

### ISSUE THREAD

**Issue by sam-leo** [godotengine/godot#8585] opened 2017-04-29 21:16 UTC
**Operating system or device - Godot version:**
Linux XUbuntu 16.04.2, Godot 2.1.2

**Issue description:**

I just click in godot editor executable but it opens my last edited game. Before that, godot was opening the project window with the same size of my game (400x680).

**Steps to reproduce:**
I don't konw, I goes open the editor and now it just open my last edited game.
I solved the problem temporally with just deleting the ~/.godot folder, but after close the editor, it reopen my game project, even now without any project list.

**Link to minimal example project:**

**Comment by Zylann** [comment] 2017-04-29 22:19
Is there any godot project at the same location as the Godot executable?

**Comment by sam-leo** [comment] 2017-04-29 23:25
The project is in other folder and that folder is in my desktop, the godot executable is in desktop. This is the first time that occurs. But I just rename the godot's executable  and open a project and now the error not happens.

**Comment by akien-mga** [comment] 2017-06-29 08:24
It's a "feature", if there is a Godot project in a subfolder where the Godot binary is, it will be opened.

That's a default behaviour that confuses many users though, so it might be worth rethinking. #7780 starts some work on this topic.

**Comment by akien-mga** [comment] 2017-06-29 09:44
Closing as duplicate of #7764.

**Closed by akien-mga** 2017-06-29 09:44 UTC
Labels: discussion, enhancement, topic:editor, usability
