### ISSUE TITLE
Exports (built on github actions) not running

### ISSUE THREAD

**Issue by dardanbujupaj** [godotengine/godot#60258] opened 2022-04-15 01:48 UTC
### Godot version

3.5.beta3

### System information

all OS, GLES2

### Issue description

With 3.5.beta2 and 3.5.beta3 my game exports built on Github actions are not running. On all exports (HTML, macos, windows (linux not tested yet, will do that later)) I get error messages in the console when starting the game.

EDIT: The linux export doesn't work either.

I only have the issue when exporting the game on github actions with versions newer than 3.5.beta1. When exported from the editor on Mac or Windows it's fine. Also Github actions build with 3.5.beta1 is fine as well.

### Steps to reproduce

Download  v0.3.2 (Godot 3.5.beta3) and v0.3.4 (Godot 3.5.beta1) from https://github.com/dardanbujupaj/gwj-44/releases. One works one doesn't.

### Minimal reproduction project

https://github.com/dardanbujupaj/gwj-44

**Comment by dardanbujupaj** [comment] 2022-04-15 01:50
Said error messages when starting the game on windows (when built with 3.5.beta3 on github actions):

````
Godot Engine v3.5.beta3.official.3c0d32562 - https://godotengine.org
OpenGL ES 2.0 Renderer: NVIDIA GeForce RTX 2070 SUPER/PCIe/SSE2

SCRIPT ERROR: Parse Error: The assigned value doesn't have a set type; the variable type can't be inferred.
          at: GDScript::load_byte_code (res://settings/Settings.gdc:52)
ERROR: Method failed. Returning: ERR_PARSE_ERROR
   at: load_byte_code (modules/gdscript/gdscript.cpp:782)
ERROR: Cannot load byte code from file 'res://settings/Settings.gdc'.
   at: (modules/gdscript/gdscript.cpp:2205)
ERROR: Failed loading resource: res://settings/Settings.gdc. Make sure resources have been imported by opening the project in the editor at least once.
   at: (core/io/resource_loader.cpp:270)
ERROR: Can't autoload: res://settings/Settings.gd
   at: (main/main.cpp:1895)
SCRIPT ERROR: Parse Error: The assigned value doesn't have a set type; the variable type can't be inferred.
          at: GDScript::load_byte_code (res://Bone.gdc:15)
ERROR: Method failed. Returning: ERR_PARSE_ERROR
   at: load_byte_code (modules/gdscript/gdscript.cpp:782)
ERROR: Cannot load byte code from file 'res://Bone.gdc'.
   at: (modules/gdscript/gdscript.cpp:2205)
ERROR: Failed loading resource: res://Bone.gdc. Make sure resources have been imported by opening the project in the editor at least once.
   at: (core/io/resource_loader.cpp:270)
ERROR: res://Bone.tscn:3 - Parse Error: [ext_resource] referenced nonexistent resource at: res://Bone.gd
   at: poll (scene/resources/resource_format_text.cpp:412)
ERROR: Failed to load resource 'res://Bone.tscn'.
   at: (core/io/resource_loader.cpp:206)
ERROR: Failed loading resource: res://Bone.tscn. Make sure resources have been imported by opening the project in the editor at least once.
   at: (core/io/resource_loader.cpp:270)
SCRIPT ERROR: Parse Error: Can't preload resource at path: res://Bone.tscn
          at: GDScript::load_byte_code (res://scenes/skeleton/Skeleton.gdc:92)
ERROR: Method failed. Returning: ERR_PARSE_ERROR
   at: load_byte_code (modules/gdscript/gdscript.cpp:782)
ERROR: Cannot load byte code from file 'res://scenes/skeleton/Skeleton.gdc'.
   at: (modules/gdscript/gdscript.cpp:2205)
ERROR: Failed loading resource: res://scenes/skeleton/Skeleton.gdc. Make sure resources have been imported by opening the project in the editor at least once.
   at: (core/io/resource_loader.cpp:270)
ERROR: res://scenes/skeleton/Skeleton.tscn:26 - Parse Error: [ext_resource] referenced nonexistent resource at: res://scenes/skeleton/Skeleton.gd
   at: poll (scene/resources/resource_format_text.cpp:412)
ERROR: Failed to load resource 'res://scenes/skeleton/Skeleton.tscn'.
   at: (core/io/resource_loader.cpp:206)
ERROR: Failed loading resource: res://scenes/skeleton/Skeleton.tscn. Make sure resources have been imported by opening the project in the editor at least once.
   at: (core/io/resource_loader.cpp:270)
ERROR: res://scenes/levels/Dungeon01.tscn:4 - Parse Error: [ext_resource] referenced nonexistent resource at: res://scenes/skeleton/Skeleton.tscn
   at: poll (scene/resources/resource_format_text.cpp:412)
ERROR: Failed to load resource 'res://scenes/levels/Dungeon01.tscn'.
   at: (core/io/resource_loader.cpp:206)
ERROR: Failed loading resource: res://scenes/levels/Dungeon01.tscn. Make sure resources have been imported by opening the project in the editor at least once.
   at: (core/io/resource_loader.cpp:270)
ERROR: Failed loading scene: res://scenes/levels/Dungeon01.tscn
   at: (main/main.cpp:2083)
WARNING: ObjectDB instances leaked at exit (run with --verbose for details).
     at: cleanup (core/object.cpp:2064)
ERROR: Resources still in use at exit (run with --verbose for details).
   at: clear (core/resource.cpp:417)
ERROR: There are still MemoryPool allocs in use at exit!
   at: (core/pool_vector.cpp:63)
````

**Comment by Listwon** [comment] 2022-04-15 06:59
It should be fixed by this https://github.com/godotengine/godot/pull/59793 and https://github.com/godotengine/godot/pull/59814

**Comment by Calinou** [comment] 2022-04-15 13:20
Duplicate of https://github.com/godotengine/godot/issues/59723, since it was broken on the same versions.

**Closed by Calinou** 2022-04-15 13:20 UTC

**Comment by dardanbujupaj** [comment] 2022-04-15 15:55
@Listwon Didn't realize this was the same issue. Thanks for the clarification.

@Calinou Thanks for the explenation on why it worked from the editor!
