### ISSUE TITLE
Control nodes do not detect mouse_exit in combination with mouse drag.

### ISSUE THREAD

**Issue by AndHalfAFish** [godotengine/godot#34484] opened 2019-12-20 09:12 UTC
**Godot version:** 
3.2beta4 / 3.1.1.stable

**OS/device including version:**
Windows 10 64-bit

**Issue description:**
Mouse_exit event is not detected in some Control nodes, when combined with mouse drag. 
As a result, a mouse click is registered by the Control, even when the mouse has been dragged outside the Control.
I tested ColorRect and TextureBtn, but this is probably also broken in other relevant controls.
Compare to Area2d node (correct behavior).

**Steps to reproduce:**
See attached project ; contains 2 scenes : 3d scene with Controls (BUG) + 2d scene with Area2d (CORRECT). Behavior is also evident if you look at the mouse icon shape change .
Actions : mouse_over Control > press mouse btn and keep it pressed down > mouse_out > release mouse btn : click event should be canceled, but isn't.
Reverse (drag inside Control) works fine.

**Minimal reproduction project:**
[Control_Bug.zip](https://github.com/godotengine/godot/files/3987530/Control_Bug.zip)

**Comment by KoBeWi** [comment] 2019-12-20 10:13
Duplicate of #20881

**Closed by KoBeWi** 2019-12-20 10:13 UTC
