### ISSUE TITLE
Exported vars gives error in text editor if are initialized by default with a const or variable from an user singleton.... but games executes without problem.

### ISSUE THREAD

**Issue by Ranoller** [godotengine/godot#26537] opened 2019-03-03 18:08 UTC
**Godot version:**

compilation from master 02/03/2019

**OS/device including version:**

wint 7 64 bit

**Issue description:**

![parser_error_that works_in_game](https://user-images.githubusercontent.com/11712737/53699236-7a970200-3de6-11e9-9e20-32dce469c864.png)

I have this error in script editor. The variable is not exported to inspector. The value entered (recursos.TEXT_SPAM_BASIC) is 1. "recursos" is an autoload. **The game executes** (no error in runtime, all syntax errors should stop game from executing). If i delete "export" word and hints, there is no error. Don´t know if this is a bug report or a feature request, but in exported variables you should be allowed to enter a default value from constants or variables in user singletons the same way as you can enter constants from godot singletons (ex: if you enter TYPE_BOOL, error is gone).

Edit: This is basic feature, if you can´t use  a constant from singleton in exported vars, you have to maintain a bunch of repeated constants in every script that uses that funcionality, or use integers losing readability...

**Comment by akien-mga** [comment] 2019-03-04 09:59
Confirmed in 49d82f24:
```
SCRIPT ERROR: GDScript::reload: Parse Error: invalid index 'TEXT_SPAM_BASIC' in constant expression
   At: res://Node2D.gd:3.
ERROR: reload: Method/Function Failed, returning: ERR_PARSE_ERROR
   At: modules/gdscript/gdscript.cpp:580.
```

Interestingly, it actually works fine when you run the game.

MRP: [New Game Project.zip](https://github.com/godotengine/godot/files/2925810/New.Game.Project.zip)

**Comment by akien-mga** [comment] 2019-03-04 22:41
Duplicate of #19704.

**Closed by akien-mga** 2019-03-04 22:41 UTC
Labels: bug, topic:gdscript

**Comment by Ranoller** [comment] 2019-03-04 22:56
Sorry, promise that i search for duplicates....

**Comment by akien-mga** [comment] 2019-03-04 22:58
No worry, it's fine to open duplicates. I didn't see it initially either.
