### ISSUE TITLE
Error exporting a Mono project with an editor plugin

### ISSUE THREAD

**Issue by git2013vb** [godotengine/godot#51784] opened 2021-08-17 06:41 UTC
### Godot version

3.4.beta3 mono

### System information

debian 10

### Issue description

When I try to export I have this error

`addons/editorsettings/plugin.cs(5,23): The type or namespace name 'EditorPlugin' could not be found (are you missing a using directive or an assembly reference?)`

the error screenshot:
![image](https://user-images.githubusercontent.com/13235119/129675904-0ed4d502-826d-47c8-92f0-19adf94d195a.png)

While i can compile and run it without problems.
Here other errors in console:
`addons/editorsettings/plugin.cs(10,26): 'plugin._Ready()': no suitable method found to override`
`addons/editorsettings/plugin.cs(18,26): 'plugin.EnablePlugin()': no suitable method found to override`

### Steps to reproduce

this is my plugin:

```
using Godot;
using DesertEdge.Utils;

[Tool]
public class plugin : EditorPlugin
{
    private const string PORT = "7010";
    private const string REMOTE_PORT = "network/debug/remote_port";

    public override void _Ready()
    {
        Log.Print(Log.DEBUG, "Plugin Editor Settings ready");
        EditorSettings editorSettings = this.GetEditorInterface().GetEditorSettings();
        editorSettings.Set(REMOTE_PORT, PORT);
        Log.Print(Log.DEBUG, editorSettings.Get(REMOTE_PORT));
    }

    public override void EnablePlugin()
    {
        EditorSettings editorSettings = this.GetEditorInterface().GetEditorSettings();
        Log.Print(Log.DEBUG, editorSettings.Get(REMOTE_PORT));
        editorSettings.Set(REMOTE_PORT, PORT);
    }
}
```

### Minimal reproduction project

na

**Comment by Atlinx** [comment] 2021-08-17 23:38
I think EditorPlugins are only supposed to run in the editor. GDScript plugins also have this behavior which leads me to believe that this is intentional.

**Comment by raulsntos** [comment] 2021-08-18 00:46
Yes, access to the editor API must be surrounded with `#if TOOLS` as explained in #41196

**Comment by git2013vb** [comment] 2021-08-18 23:20
> I think EditorPlugins are only supposed to run in the editor. GDScript plugins also have this behavior, which leads me to believe that this is intentional.

It make sense ofc.. But still sometime a EditorPlugin is necessary to run. In my case I use to export and run it outside editor cause make free some resources while working in connected project. Otherwise I have to pretend the project  is finished. If I'm not mistaken there was an issue/discussion where mentioned the editor log port to be related to the project and not to the  game engine.

**Comment by Atlinx** [comment] 2021-08-18 23:43
I'm not really sure what you mean by "hw resources" and "editor log ports" but I normally keep my plugin logic out of editor-related classes such as `EditorPlugin`. Instead, my `EditorPlugin` class contains instances of classes that control the plugin logic. I can then just use those classes directly outside of the editor as well. Maybe you could try something similar to get your plugin working in standalone builds?

**Comment by git2013vb** [comment] 2021-08-19 17:28
> I'm not really sure what you mean by "hw resources" and "editor log ports" but I normally keep my plugin logic out of editor-related classes such as `EditorPlugin`. Instead, my `EditorPlugin` class contains instances of classes that control the plugin logic. I can then just use those classes directly outside of the editor as well. Maybe you could try something similar to get your plugin working in standalone builds?

For "hw"  I mean "hardware" :).. and for "editor log ports" I mean this one (from code before posted) :`private const string REMOTE_PORT = "network/debug/remote_port";`
See #37687 and https://github.com/godotengine/godot-proposals/issues/578
How can your suggestion fit my problem?
Thanks :)

**Comment by raulsntos** [comment] 2024-07-29 03:25
Closing as working as intended. Godot's Editor APIs (such as the `EditorPlugin` type) are not available in exported projects since there's no Editor. Access to Editor APIs must be surrounded with `#if TOOLS` to prevent build errors when exporting the game.

**Closed by raulsntos** 2024-07-29 03:25 UTC
Labels: bug, topic:plugin, topic:dotnet, topic:export
