### ISSUE TITLE
Can't select 3d objects when Half Resolution is enabled

### ISSUE THREAD

**Issue by testarossaaaaa** [godotengine/godot#33372] opened 2019-11-05 21:38 UTC
**Godot version:** v3.1.1.stable.official

**OS/device including version:** macOS Catalina

**Issue description:** Can't select object in 3D Viewport when Half Resolution option is enabled.

**Steps to reproduce:** Create new project. Add some MeshInstance. Enable Half Resolution. Click on Mesh in 3D Viewport.

**Demonstration without Half Resolution**:
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/4533828/68248148-52bf0480-002d-11ea-8332-9cac576e65c5.gif)

**Demonstration with Half Resolution**:
![ezgif com-video-to-gif-2](https://user-images.githubusercontent.com/4533828/68248340-af222400-002d-11ea-97c9-f17cc4157d9c.gif)

**Comment by Calinou** [comment] 2019-11-05 21:47
Duplicate of #13364.

**Closed by Calinou** 2019-11-05 21:47 UTC
