### ISSUE TITLE
GdScript 2.0 - export enum with type String doesn't work

### ISSUE THREAD

**Issue by AttackButton** [godotengine/godot#55176] opened 2021-11-20 22:53 UTC
### Godot version

v4.0.dev.calinou.ba798d585

### System information

Windows 10

### Issue description

Using @export_enum with type String doesn't works as stated in the docs: https://docs.godotengine.org/en/latest/tutorials/scripting/gdscript/gdscript_exports.html?highlight=exporting%20variable#basic-use

This works in godot 3.x (https://docs.godotengine.org/en/3.4/getting_started/scripting/gdscript/gdscript_exports.html?highlight=export#examples).

### Steps to reproduce

Try to use the @export_enum with a variable of type String.

### Minimal reproduction project

Just open a script and use the docs example(https://docs.godotengine.org/en/latest/tutorials/scripting/gdscript/gdscript_exports.html?highlight=exporting%20variable#basic-use):

`@export_enum("Rebecca", "Mary", "Leah") var character_name: String = "Rebecca"`

**Comment by KoBeWi** [comment] 2021-11-21 00:01
Duplicate of #54828

**Closed by KoBeWi** 2021-11-21 00:01 UTC
