### ISSUE TITLE
Performance regression since 4.2-beta1 when calling `TranslationServer.set_locale()` every frame

### ISSUE THREAD

**Issue by Loneliiii** [godotengine/godot#85718] opened 2023-12-03 19:11 UTC
### Godot version

4.2

### System information

Windows 11

### Issue description

I started a project in Godot 4 and updated Godot and ended up with Godot 4.2dev_6 because this was compatible with the modi_player addon and Glow at the same time. Other Versions either had framrate issues (like the main problem i have now) or the addon not working.

After Godot 4.2 stable came out, I tried to work in my game with this Version and get massive framerate issues (5fps) in the forward+ and mobile renderer, even in an empty scene. I tried turning off hdr / glow and changed other project settings, but nothing works. 
When I change to the Compatibility render I get the maximum amount of frames possible.

I have a Asus Rog Flow X13, Ryzen 7, GTX 1650 with Max-Q Design and a AMD Radeon Graphics 

### Steps to reproduce

its only in this project, no else, but here are the stept I did with the Game.
- Started dev. in Godot 4.0
- Updated to Godot 4.1
- Installed Godot4.2_dev 3 for hdr glow (in 2D)
- changed to Godot 4.2dev6 because of the midi player addon
- now used a backup copy of my game to test Godot 4.2 stable

### Minimal reproduction project

I won't upload my game here, because I'm pretty far in developement.

**Comment by clayjohn** [comment] 2023-12-03 19:28
Can you work on creating a minimal reproduction project? Without one we can't really do anything to help. 

The issue is likely some combination of your system, your add on, and your project. Without having access to those things, contributors can't even help you debug. 

If you can't create an MRP, then you should at least try to identify what is causing the slowdown using a profiler. You should be able to identify if the issue comes from Godot, from your scripts, or from the add on you are using.

**Comment by Loneliiii** [comment] 2023-12-03 19:37
I just tried it without the addon. Nothing changes. 
I'm gonna strip down the game to the minimum. to see, where and upload it here. Will take a bit

**Comment by Loneliiii** [comment] 2023-12-03 22:07
I can't upload it here, because its too big 199MB.
I stripped the game down, deleted all objects, most of the sprites/fonts and nothing changes.
In the version I just uploaded I created a scene with a framecounter and a path with a sprite following it.

I hope its okay, when I send the Google Drive link. [https://drive.google.com/file/d/187y1EATuBMvr7RcKAHX1k9FEcgF-uZLp/view?usp=sharing]

**Comment by saierXP** [comment] 2023-12-05 08:14
`TranslationServer.set_locale` has no performance issues in **4.2.dev6**, but has performance issues in **4.2.beta1**.

![Godot_v4 2-beta3_win64_stYEyCvqor](https://github.com/godotengine/godot/assets/45038185/8fb080fd-ce9f-4683-a974-f134420ca53f)

<details><summary>System Details</summary>
<p>

Godot v4.2.dev6 - Windows 10.0.19045 - Vulkan (Forward+) - integrated AMD Radeon(TM) Vega 8 Graphics (Advanced Micro Devices, Inc.; 31.0.14057.5006) - AMD Ryzen 5 2500U with Radeon Vega Mobile Gfx (8 Threads)

</p>
</details>

**Comment by akien-mga** [comment] 2023-12-05 09:38
What locale(s) are you using for your OS, and for Godot?

**Comment by Loneliiii** [comment] 2023-12-05 11:10
You are a haero saierXP. I removed in a test version all of the translation stuff and it works without issues even in forward+.
I remove it from the autoload physics_process and only let the translation change once when starting the game and changing the language. No problem this way so far.

My OS is currently just German and my Godot is also in German currently. The translation of the game is changed in the options menu between german and english currently.

First of, thank you guys for helping me with this! :D 
And maybe hopefully the "problem" can be fixed, so others don't have these performance issues. (And/Or I was just stupid by always loading the set_locale in the physics process)

**Comment by bruvzg** [comment] 2023-12-05 12:39
Setting locale trigger reload of all remapped resources (which was broken before 4.2) and complete reprocessing of all text, this is definitely not a fast thing and should not be done every frame.

**Comment by akien-mga** [comment] 2023-12-05 12:52
Yeah I first thought about my fix to translation remapping #84791, but it was merged in 4.2-beta6, so the timeline doesn't check out with this perceived regression.

I fully agree that resetting locale every frame should not be done, but it would be good to identify why it became much more expensive than it used to be.

**Comment by bruvzg** [comment] 2023-12-05 14:14
I can't reproduce the issue on macOS, but I guess we can add the check if locale is changed and only call updates if necessary.

**Comment by bruvzg** [comment] 2023-12-05 14:22
<img width="1110" alt="Screenshot 2023-12-05 at 16 20 33" src="https://github.com/godotengine/godot/assets/7645683/0f601aa2-1190-460b-9281-3778dffa1b96">

It is triggering title update, so might be related to https://github.com/godotengine/godot/pull/80409

I will check it on Windows tomorrow.

**Comment by Loneliiii** [comment] 2023-12-05 17:00
> It's very strange, I can't reproduce the previous test results and my computer hasn't been restarted.
> Loneliiii can you still reproduce it? Operate `set_local `on every frame.

I will try it later, when I'm back home.
Empty project in 4.2, renderer forward+ and then autoload a script and calling the set_local in the physics_procesd.
That should be all I guess

As a question. You guys say, it is triggering the title update. Do you mean with title the game window title?

**Comment by Loneliiii** [comment] 2023-12-05 17:18
I tried to replicate it on my ROG Ally (Win 11). i can replicate it, by just the steps mentioned before.
here is the project, where I reproduced it
[locale_reproduced.zip](https://github.com/godotengine/godot/files/13565021/locale_reproduced.zip)

**Comment by saierXP** [comment] 2023-12-06 04:55
![Godot_v4 2-stable_win64_ft3RkQgCXi](https://github.com/godotengine/godot/assets/45038185/04bc4d0a-d788-4a5f-9446-492d2d0e4c86)
After several attempts today, I was able to reproduce the bug in forward+ and found that the System's hard disk write is 0.3Mb-0.5Mb, GPU usage is 50%, as well as cpu usage is high, GPU engine shows it is GPU-copy. after commenting out set_locale, System's usage dropped.
It may be related to vulkan, after switching renderer several times, compatibility mode is normal. Mobile has higher framerate than forward+.
I will do git bisect later.

**Comment by saierXP** [comment] 2023-12-06 07:06
> It is triggering title update, so might be related to #80409

72e2e4705942dd01d4befea3380df5d0fe77c363 is the first bad commit

**Comment by akien-mga** [comment] 2023-12-06 07:10
As I mentioned yesterday, this might have been mitigated by https://github.com/godotengine/godot/pull/85542 already. Could you test latest `master`?

**Comment by saierXP** [comment] 2023-12-06 08:43
It didn't fix it. The runtime doesn't go to the `window_id ! = DisplayServer::INVALID_WINDOW_ID` if branch.

**Closed** 2023-12-06 11:36 UTC
Labels: bug, platform:windows, topic:porting, needs testing, regression, performance
