### ISSUE TITLE
Vertex color set to face corner doesn't export correctly

### ISSUE THREAD

**Issue by warcanin** [godotengine/godot#75007] opened 2023-03-16 22:02 UTC
### Godot version

4.0 Stable

### System information

Windows 10

### Issue description

Vertex color set to face corner doesn't export correctly
![image](https://user-images.githubusercontent.com/57159438/225761804-76d39d14-ecd2-48e3-bbe9-489df8645c32.png)
This is a straight import from blend file but there is the same problem with glb export.

### Steps to reproduce

take any mesh in blender add an attribute set to face corner and color and you will see issues

### Minimal reproduction project

N/A

**Comment by AThousandShips** [comment] 2023-03-16 22:09
Duplicate of #73056

**Comment by Calinou** [comment] 2023-03-16 22:14
- Duplicate of https://github.com/godotengine/godot/issues/73056.

**Closed by Calinou** 2023-03-16 22:14 UTC
