### ISSUE TITLE
CharacterBody3D gains extra speed proportional to physics FPS when walking along walls with floor_block_on_wall = true

### ISSUE THREAD

**Issue by Syntaxxor** [godotengine/godot#66249] opened 2022-09-22 08:30 UTC
### Godot version

4.0.beta1

### System information

Windows 10

### Issue description

When a `CharacterBody3D` node moves along a wall at a slight angle, it gains significant extra speed proportional to the physics FPS. I found this because I try to keep my physics FPS around 200, since 60fps jitters significantly when playing on a 144hz monitor. The following is a video of this in the minimal reproduction project.

https://user-images.githubusercontent.com/25652538/191697392-d82ffa2a-772e-4077-8707-ff621d2b6294.mp4

The bodies on the left side have `floor_block_on_wall` set to true, and the ones on the right have it set to false. The inner bodies are moving directly forward, while the ones against the walls are moving slightly into the walls.

### Steps to reproduce

1. Set your physics FPS to an amount over 60fps (I was able to reproduce this slightly even at 75fps)
2. Move a `CharacterBody3D` against the wall at an angle almost perpendicular to the wall's normal. The body will increase in speed upon hitting the wall.
3. Disable `floor_block_on_wall` on the CharacterBody3D and try again. It will not happen.

### Minimal reproduction project

[character_body_bug.zip](https://github.com/godotengine/godot/files/9623879/character_body_bug.zip)

**Comment by Calinou** [comment] 2022-09-24 15:24
> I found this because I try to keep my physics FPS around 200, since 60fps jitters significantly when playing on a 144hz monitor.

This is not a good way to mitigate jitter. Using physics interpolation instead will give you reliable results at any refresh rate. Physics interpolation wasn't ported from 3.5 to 4.0 yet, but you could try modifying [smoothing-addon](https://github.com/lawnjelly/smoothing-addon) to work with 4.0.

**Comment by Syntaxxor** [comment] 2022-09-24 18:25
> > I found this because I try to keep my physics FPS around 200, since 60fps jitters significantly when playing on a 144hz monitor.
> 
> ...you could try modifying [smoothing-addon](https://github.com/lawnjelly/smoothing-addon) to work with 4.0.
Good to know. I see that there's already a 4.x branch on there. I'll see if that works later today.

**Comment by Syntaxxor** [comment] 2022-09-29 22:58
Commenting _definitely later that day_ to say that the 4.x branch does in fact work for smoothing.

**Comment by solitaryurt** [comment] 2022-10-05 19:09
Also experiencing this with 4.x

**Comment by solitaryurt** [comment] 2023-03-20 05:47
Still an issue with 4.0 stable.

**Comment by elvisish** [comment] 2023-10-28 21:10
I'm having this issue with 4.1, I'm rendering at 165 fps, physics fps is at standard 60, but I'm using the Smoother addon. I likewise fixed it by disabling Block On Wall but I'm not sure what issues this will cause along the way.

**Comment by nickyoo919** [comment] 2024-01-21 22:55
this is game breaking, is there any way to solve this issue?

**Comment by elvisish** [comment] 2024-01-22 00:00
> this is game breaking, is there any way to solve this issue?

I just disabled it and ran into no further issues, that seems to be all that's possible for now.

**Comment by nickyoo919** [comment] 2024-01-24 18:05
:\

**Comment by solitaryurt** [comment] 2024-03-20 22:43
Still busted in 4.2 🥴

**Comment by solitaryurt** [comment] 2024-03-23 09:40
So I tried switching to [godot-jolt](https://github.com/godot-jolt/godot-jolt) instead of the default physics engine, and the issue still exists. 

I'm guessing this isn't related to physics, but is related to some code in `CharacterBody3D`.

**Comment by solitaryurt** [comment] 2024-03-23 10:09
Same issue is still in `4.3-dev5`

**Comment by rburing** [comment] 2024-04-18 20:25
I've located the bug. Here the movement resulting from `move_and_collide` is not cancelled (`gt` is not modified):

https://github.com/godotengine/godot/blob/2efbc6bfb3b4f49a6bc75b3d367cfe81eeddbf3a/scene/3d/physics/character_body_3d.cpp#L233-L235

but in the subsequent code `motion` does not get shortened either (in the case of the MRP), and there is a second iteration of `_move_and_slide_grounded` where this `motion` is passed to `move_and_collide` again (and the movement is applied immediately before hitting the wall checks), so effectively the travel is "taken into account" twice, causing a speedup.

I'm not sure how the code was intended to be, so I don't know exactly how this should be fixed. For example doing `motion = result.remainder;` instead in the quoted code gets rid of the speedup, but I don't know if this breaks the assumptions/intention of the subsequent code. At least it is consistent with the other branch:

https://github.com/godotengine/godot/blob/2efbc6bfb3b4f49a6bc75b3d367cfe81eeddbf3a/scene/3d/physics/character_body_3d.cpp#L241-L242

Maybe @fabriceci can check/confirm.

**Closed** 2024-04-25 10:12 UTC
Labels: bug, confirmed, topic:physics, topic:3d
