### ISSUE TITLE
DirectionalLight3D is not working correctly when light is pointing away

### ISSUE THREAD

**Issue by Mikeysax** [godotengine/godot#68143] opened 2022-11-01 23:51 UTC
### Godot version

4.0beta3

### System information

PopOS 22.04, 5.19.0-76051900-generic kernel, Ryzen 6800h, Radeon 6700m, amdgpu, Vulkan

### Issue description

Utilizing DirectionalLight3D and Environment, I'm seeing weird light behavior when the scene should be completely dark. I have a day night cycle and it's producing unexpected results and I'm not sure why:

![image](https://user-images.githubusercontent.com/15805689/199363045-24a90637-da80-4751-87e6-fa6cca7b6c70.png)

Here is a video to demonstrate:

https://user-images.githubusercontent.com/15805689/199366194-12561a51-34ac-44a3-844e-378e3acde89a.mp4

### Steps to reproduce

This is an old project, but it can be reproduced here:

https://github.com/Mikeysax/example-project-for-godot-bug-68143

Here are screenshots of the environment if that helps:

![image](https://user-images.githubusercontent.com/15805689/199363486-260fa6f2-328e-4518-9f3d-7f2f298e5d5d.png)

![image](https://user-images.githubusercontent.com/15805689/199363543-5bbc0c47-8f81-4c7f-8d0b-c7bd2823c6f5.png)

![image](https://user-images.githubusercontent.com/15805689/199363560-ccd7df37-7eb6-4c47-81e4-2b267ca9cf09.png)

### Minimal reproduction project

https://github.com/Mikeysax/example-project-for-godot-bug-68143

**Comment by clayjohn** [comment] 2022-11-02 05:46
This looks like it could be a shadow pancaking issue, but I can't confirm as I can't reproduce locally.

**Comment by tinmanjuggernaut** [comment] 2022-11-02 10:47
Most likely, your meshes are corrupted and this is a duplicate of either upgrading from godot 3 https://github.com/godotengine/godot/issues/63550 or upgrading from an earlier version of godot 4 https://github.com/godotengine/godot/issues/64854.

You can fix it by reimporting all of your meshes in the latest version, or deleting `project/.godot/imported` if all of your scenes are still linked to the import files.

**Comment by Mikeysax** [comment] 2022-11-02 10:52
@clayjohn @tinmanjuggernaut , I've uploaded a new project which should be able to replicate: 

https://github.com/Mikeysax/example-project-for-godot-bug-68143

**Comment by Mikeysax** [comment] 2022-11-02 11:11
It seems as though setting max distance on Directional Shadow to a higher value kinda fixes the issue:

![image](https://user-images.githubusercontent.com/15805689/199475318-e4c6a147-6944-440c-bd48-b6f5299cdfa5.png)

Is this a bug though or intentional?

**Comment by tinmanjuggernaut** [comment] 2022-11-02 11:28
I see, if they are native meshes, then what I wrote does not apply.
I opened up your project. You should learn about .gitignore and exclude `.godot` and `.import`.

Yeah Godot leaks light all over the place. It's not a ray tracer, (though the light baker is). Casting a shadow from a 100x100m object onto 4x1m objects right next to it with a 100 shadow distance is a challenge. Try adjusting the scale of your shadow casters and bring them into the same order of magnitude. Increasing shadow distance to 1000 is costly, though 100 is too short. 256-400 is good for modern and previous generation cards.

You can create mesh boxes and under Geometry mark them as cast shadow cast only. Then you can use them as flags to block light the way a gaffer would shape light on a film set. https://www.youtube.com/watch?v=ShFk1Ao9sBw

**Comment by Mikeysax** [comment] 2022-11-02 12:00
> I see, if they are native meshes, then what I wrote does not apply. I opened up your project. You should learn about .gitignore and exclude `.godot` and `.import`.
> 
> Yeah Godot leaks light all over the place. It's not a ray tracer, (though the light baker is). Casting a shadow from a 100x100m object onto 4x1m objects right next to it with a 100 shadow distance is a challenge. Try adjusting the scale of your shadow casters and bring them into the same order of magnitude. Increasing shadow distance to 1000 is costly, though 100 is too short. 256-400 is good for modern and previous generation cards.
> 
> You can create mesh boxes and under Geometry mark them as cast shadow cast only. Then you can use them as flags to block light the way a gaffer would shape light on a film set. https://www.youtube.com/watch?v=ShFk1Ao9sBw

I see; thank you for the tips and help!

I was aware of .gitignore although I was not used to what should be excluded from a godot project for source control.

**Closed** 2022-11-02 12:17 UTC
Labels: topic:rendering, needs testing, topic:3d
