### ISSUE TITLE
Godot ignores lowercase node names triggering false errors.

### ISSUE THREAD

**Issue by BaconOFBurger** [godotengine/godot#48145] opened 2021-04-23 23:56 UTC
**Godot version:** 3.3

**OS/device including version:**
Windows 10, Version 20H2.
Intel Core i3-3227u, GeForce GT 640 w/ GLES3

**Issue description:**
Godot seems to ignore lowercase node names triggering false errors.

**Steps to reproduce:**
Create a new scene, lets call it "root", "world", "spatial" or whatever
Create a Sprite3D node inside, lets call it "stuff"
Create a Viewport node inside Sprite3D, lets call it "vp"
Create a Node2D inside our Viewport called "nodestuff"
Setup Viewport in Sprite3D then save the scene, godot should be reporting some errors by now that "vp/nodestuff" cannot be found, ViewportTexture: Path to node is invalid.

**Minimal reproduction project:**
[BugHunt.zip](https://github.com/godotengine/godot/files/6368615/BugHunt.zip)

**Comment by pycbouh** [comment] 2021-04-24 00:08
Duplicate of #27790. Also not related to lowercase names.

**Closed by pycbouh** 2021-04-24 00:08 UTC
Labels: archived, bug
