### ISSUE TITLE
Empty control nodes (for example Control) should default to pass the mouse event.

### ISSUE THREAD

**Issue by QbieShay** [godotengine/godot#24083] opened 2018-11-30 13:28 UTC
**Godot version:**
11d77386

**Issue description:**
When creating interfaces, it happened to me quite often to create full screen controls and instantiate other elements inside of this full size controls.
This leads to an unexpected behaviour which is that even an empty control by default stops the mouse.
I would expect this behaviour from a solid Control element(buttons, panels, etc) but not from the 'vanilla' Control node.

This behaviour led me to spend quite some time debugging why some gui functionalities were broken, when it was just the control filtering mouse events

**Proposal:**
All the empty control nodes (so far i can think only of the base control node) should pass mouse events by default.

**Comment by Zylann** [comment] 2018-11-30 13:59
I agree, I went into the same situations. Controls that have no visuals by default should ignore the mouse (`Control` and some of the `Container` nodes).

**Comment by KoBeWi** [comment] 2019-08-17 20:45
Yeah, the problem is that `MOUSE_FILTER_STOP` is inherited by pretty much every Control-derived node and none of them change this. So this should be changed for each of these nodes individually, unless there's some possibility to change it only for base class.

**Comment by akien-mga** [comment] 2022-03-26 00:43
Closing as duplicate of https://github.com/godotengine/godot-proposals/issues/788 since we now have those discussions in the proposal repo.

**Closed by akien-mga** 2022-03-26 00:43 UTC
Labels: enhancement, discussion, for pr meeting, topic:gui
