### ISSUE TITLE
Godot 3.6 Beta 5 does not bake 3D models via merge_meshes

### ISSUE THREAD

**Issue by SkanerSoft** [godotengine/godot#91988] opened 2024-05-15 17:06 UTC
### Tested versions

Godot 3.6 Beta 5

### System information

Ubuntu 22.04

### Issue description

Step 1. Export models from blender in glTF format
![126](https://github.com/godotengine/godot/assets/13809475/df925108-39bf-4b82-b97c-152b489fc26c)
![127](https://github.com/godotengine/godot/assets/13809475/f4eb062a-76bc-4046-81e0-51aba529ad89)

Step 2. Set the import settings so that the content ends up in *.mesh files
![128](https://github.com/godotengine/godot/assets/13809475/a366cb42-2b08-4c24-90c1-0c92afff251f)
![129](https://github.com/godotengine/godot/assets/13809475/51d7c3a7-7bd8-4d1e-94e7-997aa6142e48)

Step 3. Arrange the nodes as you see fit
![132](https://github.com/godotengine/godot/assets/13809475/85631263-ca63-4047-b0db-324ade0e9f3f)

Step 4. Bake in a tool script so that the models are combined into a single mesh
![131](https://github.com/godotengine/godot/assets/13809475/6154f238-ccba-4fab-9593-e36193256231)

Result of this code in 3.5.3
![132](https://github.com/godotengine/godot/assets/13809475/f6e3e602-3e03-4493-b682-b370611f4556)

And this is how it looks in 3.6 Beta 5
![133](https://github.com/godotengine/godot/assets/13809475/903adf88-8bf2-42ed-a322-26d57458fd46)

### Steps to reproduce

Open MRP in Godot 3.6 Beta 5 and try it.

### Minimal reproduction project (MRP)

[GodotGames.zip](https://github.com/godotengine/godot/files/15324720/GodotGames.zip)

**Comment by lawnjelly** [comment] 2024-05-15 17:52
Ah this could be a regression from MergeGroups. I don't think it looks serious, just a check for CPU source mesh which doesn't make sense with the old method.

I should be able to fix this up soon.

**Comment by lawnjelly** [comment] 2024-05-19 07:05
I've done a PR to fix this, essentially the problem was just the new method defaults to creating meshes on CPU only and the `MeshInstance::merge_meshes()` should create GPU meshes for use in the editor and rendering.

There is one additional change to be aware of here since 3.5:
* Mesh merging is now visibility aware, so if hidden meshes are merged, they will be merged to a hidden result.
* This means that in your script you either need to hide the source meshes _after_ merging, or unhide the result mesh after merging.

Also as the merging backend has changed it may be more stringent for requirements for merging (it checks hopefully absolutely everything, so if e.g. a margin is different, then it will not merge).

I'm hoping to add a _verbose_ mode for merging that will print out reasons for not merging (as this could be annoying to work out manually) but this may have to wait till a point release as we are in feature freeze.

**Comment by SkanerSoft** [comment] 2024-05-19 09:39
Thank you very much! If you need testing it, let me know, I will help!

**Comment by lawnjelly** [comment] 2024-05-19 09:51
> Thank you very much! If you need testing it, let me know, I will help!

Hopefully a lot of the jobs you previously did with `MeshInstance::merge_meshes()` can now be automated better with `MergeGroup`, as it essentially does what you were doing in your script, either at runtime or baked in the editor.

Any testing you can give would be greatly appreciated! :grinning: 

https://docs.godotengine.org/en/3.6/tutorials/3d/merge_groups.html

**Comment by lawnjelly** [comment] 2024-07-01 11:40
Fixed by #92105.

**Closed by lawnjelly** 2024-07-01 11:40 UTC
Labels: bug, regression, topic:3d
