### ISSUE TITLE
Control nodes that are children in the Viewport override the entire screen space on which they are located and intercept all input events in this space.

### ISSUE THREAD

**Issue by OlexiyKravchuk** [godotengine/godot#43284] opened 2020-11-02 23:39 UTC
**Godot version:**
Godot_v3.2.3-stable_win64

**OS/device including version:**
W7 x64

**Issue description:**
Control nodes, which are children in the Viewport, override the entire screen space on which they are located and intercept all input events in this space, regardless of the layer where they are passing through any number of scenes, control nodes, and other types of nodes, and even if the parent tab is invisible.

**Steps to reproduce:**
check my example project

**Minimal reproduction project:**
[BUG_IGNORING_ANY_LAYERS_GUI_NESTED_IN_Viewport.zip](https://github.com/godotengine/godot/files/5478612/BUG_IGNORING_ANY_LAYERS_GUI_NESTED_IN_Viewport.zip)

**Comment by Sauermann** [comment] 2022-03-09 20:31
Duplicate of #39666

**Closed** 2022-03-09 20:41 UTC
Labels: bug, topic:input, topic:gui
