### ISSUE TITLE
The color select window ' closes ' automatically for ' after 2 seconds . .

### ISSUE THREAD

**Issue by charlesmlamb** [godotengine/godot#48580] opened 2021-05-09 10:46 UTC
**Godot version:**
Godot 3.3 . .

**OS/device including version:**
Windows . . .

**Issue description:**
When I open the ' color select ' it closes after about 2 seconds, or less . . After re-clicking the color select, it is open, indefinitely . . AFAIK, I don't click in the wrong place, not sure if it's a bug . . .

![2021-05-09 1241](https://user-images.githubusercontent.com/83387915/117569116-54ef9c80-b0c4-11eb-9962-a5b1d32b5f52.gif)

Well, I don't know 'why' it happens, or if it's a bug, I'm too noob, to ' understand ' . . <3

**Steps to reproduce:**

I ' know ' it happens, when trying to select a new color, in ' editor settings ', for the theme, but it's also happened, in ' materials ' . . Maybe, it's my computer :(( :(( Thx . . .

**Minimal reproduction project:**
Like above, it's happened in Godot 3.2 but, I'm not sure if it's a bug, or so on, Thanks . . .

Well, not sure if it's a bug, it's just annoying, when it happens 200 times, while making a ' demo ' . . Thanks . . . . Maybe, there's a good reason for it, I'm quite noob, Thanks . . . ps. Godot is rad, so amazing . . :OO :OO . .

**Comment by Calinou** [comment] 2021-05-09 11:04
Duplicate of https://github.com/godotengine/godot/issues/23626.

**Closed by Calinou** 2021-05-09 11:04 UTC
