### ISSUE TITLE
Regression in physics when using gridmaps in 3.2 (after 3.2.3-stable)

### ISSUE THREAD

**Issue by jamie-pate** [godotengine/godot#42542] opened 2020-10-03 21:24 UTC
**Godot version:**

904773149d0f7ea6b71d532c5332bcf6ba6335b5..28822847954620eabef372a866f8e94522529a39
Godot Engine v3.2.4.beta.custom_build.904773149 - https://godotengine.org
**OS/device including version:**

OpenGL ES 3.0 Renderer: GeForce GTX 1070 with Max-Q Design/PCIe/SSE2
Linux
Pop!_OS 20.04 LTS

**Issue description:**

GridMap collision shapes seem to apply randomly
https://streamable.com/b0rsyw
![physics-regression-2020-10-03_14 12 06-sm-5fps](https://user-images.githubusercontent.com/682658/95001965-128d3c80-0584-11eb-8063-d79d4f3712ca.gif)

**Steps to reproduce:**
Create a scene that has a gridmap that uses collisionshapes inside the gridmap.

**Minimal reproduction project:**

[platformer.zip](https://github.com/godotengine/godot/files/5322318/platformer.zip)

**Comment by akien-mga** [comment] 2020-10-03 21:30
Please try the latest `3.2` commit (fbf5c1cea8337bb2adf0d542a43a797a7414337f), it's a fast moving target :)

**Comment by jamie-pate** [comment] 2020-10-03 21:36
Sorry i should have put in a range, I tried the tip first, i'll double check

**Comment by akien-mga** [comment] 2020-10-03 21:37
Yeah I can reproduce it too in the latest `3.2` (28822847954620eabef372a866f8e94522529a39).

CC @madmiraal

**Comment by madmiraal** [comment] 2020-10-04 08:17
I haven't checked, but it may be a duplicate of #42462, which was fixed with #42500, but hasn't been cherry-picked yet.

**Comment by akien-mga** [comment] 2020-10-04 08:58
Ah yeah I forgot that I haven't cherry-picked it yet. Will do later today.

**Comment by capnm** [comment] 2020-10-04 09:33
I took a quick look at the demo, the tiles template is broken,
the tiles use ConcavePolygonShape so I actually wonder that it works at all ...

![grafik](https://user-images.githubusercontent.com/4047289/95011992-4bd1b500-0635-11eb-9912-a99dbe0a9e70.png)

**Comment by capnm** [comment] 2020-10-04 10:30
I can confirm,  #42500 fixes the CollisionShape transform issue:
![grafik](https://user-images.githubusercontent.com/4047289/95012949-1630ca00-063d-11eb-90c9-fe95bfc24882.png)

**Comment by akien-mga** [comment] 2020-10-04 18:53
Fixed by #42500.

**Closed by akien-mga** 2020-10-04 18:53 UTC
Labels: bug, regression, topic:physics
