### ISSUE TITLE
Accessing keys() dict of an enum defined in a singleton crashes app

### ISSUE THREAD

**Issue by jmb462** [godotengine/godot#70495] opened 2022-12-23 20:39 UTC
### Godot version

beta10

### System information

Windows10

### Issue description

With beta10, when an enum is defined in an autoloaded script, calling the keys() method on the enum crash the app.

Works well if the enum is not defined in a singleton.
Worked well in beta9

### Steps to reproduce

1°) Define an enum in a script and make it as an autoloaded script in your project.
2°) Try to access this enum keys() method from another script
Should work in beta9 but crash in beta10

### Minimal reproduction project

[global_enum_bug.zip](https://github.com/godotengine/godot/files/10297245/global_enum_bug.zip)

**Comment by akien-mga** [comment] 2022-12-23 22:10
CC @adamscott @rune-scape

**Comment by jtnicholl** [comment] 2022-12-24 02:05
I can confirm this, I ran into it in one of my own projects, wasn't sure what in my project was triggering it.
From a git bisect, it was caused by #70220. That PR also causes my project to print a bunch of errors on startup:
```
ERROR: Condition "!method" is true. Returning: false
   at: is_builtin_method_vararg (core/variant/variant_call.cpp:1339)
ERROR: Condition "!method" is true. Returning: 0
   at: get_builtin_method_argument_count (core/variant/variant_call.cpp:1265)
ERROR: Condition "!method" is true. Returning: Variant::NIL
   at: get_builtin_method_return_type (core/variant/variant_call.cpp:1318)
ERROR: Condition "!method" is true. Returning: nullptr
   at: get_validated_builtin_method (core/variant/variant_call.cpp:1251)
ERROR: Condition "!method" is true. Returning: false
   at: is_builtin_method_vararg (core/variant/variant_call.cpp:1339)
ERROR: Condition "!method" is true. Returning: 0
   at: get_builtin_method_argument_count (core/variant/variant_call.cpp:1265)
ERROR: Condition "!method" is true. Returning: Variant::NIL
   at: get_builtin_method_return_type (core/variant/variant_call.cpp:1318)
ERROR: Condition "!method" is true. Returning: nullptr
   at: get_validated_builtin_method (core/variant/variant_call.cpp:1251)
ERROR: Condition "!method" is true. Returning: false
   at: is_builtin_method_vararg (core/variant/variant_call.cpp:1339)
ERROR: Condition "!method" is true. Returning: 0
   at: get_builtin_method_argument_count (core/variant/variant_call.cpp:1265)
ERROR: Condition "!method" is true. Returning: Variant::NIL
   at: get_builtin_method_return_type (core/variant/variant_call.cpp:1318)
ERROR: Condition "!method" is true. Returning: nullptr
   at: get_validated_builtin_method (core/variant/variant_call.cpp:1251)
```
I'd open a separate issue for these errors if I could figure out an MRP.

**Comment by Lippanon** [comment] 2022-12-24 02:15
I've also bisected a crash in my main project caused by https://github.com/godotengine/godot/pull/70220, likely related. Backtrace dump:
![image](https://user-images.githubusercontent.com/115422160/209417811-43f3a410-c023-4b23-a646-874d3da51b0d.png)

**Comment by git2013vb** [comment] 2022-12-24 06:59
Well.. because I have singleton with enums and I use keys() I can suppose I have the same problem too inv 4.0.beta10.official [d0398f62f]

lots of these at start:

``` ERROR: Condition "!method" is true. Returning: Variant::NIL
   at: get_builtin_method_return_type (core/variant/variant_call.cpp:1318)
ERROR: Condition "!method" is true. Returning: nullptr
   at: get_validated_builtin_method (core/variant/variant_call.cpp:1251)
ERROR: Condition "!method" is true. Returning: false
   at: is_builtin_method_vararg (core/variant/variant_call.cpp:1339)
ERROR: Condition "!method" is true. Returning: 0
   at: get_builtin_method_argument_count (core/variant/variant_call.cpp:1265)
ERROR: Condition "!method" is true. Returning: Variant::NIL
   at: get_builtin_method_return_type (core/variant/variant_call.cpp:1318)
ERROR: Condition "!method" is true. Returning: nullptr
   at: get_validated_builtin_method (core/variant/variant_call.cpp:1251)
ERROR: Condition "!method" is true. Returning: false
   at: is_builtin_method_vararg (core/variant/variant_call.cpp:1339)
```

Thanks

**Comment by adamscott** [comment] 2022-12-24 16:29
CC @anvilfolk, the enum specialist.

**Comment by adamscott** [comment] 2022-12-24 17:15
@akien-mga Fortunately, our PR #70246 fixes this issue.

**Comment by dalexeev** [comment] 2022-12-25 10:03
I got the following errors too:

```
ERROR: Condition "!method" is true. Returning: false
   at: is_builtin_method_vararg (core/variant/variant_call.cpp:1339)
ERROR: Condition "!method" is true. Returning: 0
   at: get_builtin_method_argument_count (core/variant/variant_call.cpp:1265)
ERROR: Condition "!method" is true. Returning: Variant::NIL
   at: get_builtin_method_return_type (core/variant/variant_call.cpp:1318)
ERROR: Condition "!method" is true. Returning: nullptr
   at: get_validated_builtin_method (core/variant/variant_call.cpp:1251)
```

And sometimes crash:

```
handle_crash: Program crashed with signal 11
Engine version: Godot Engine v4.0.beta.custom_build (f382a2b59bb9606f958ccaf7be7ac98f45607c9f)
Dumping the backtrace. Please include this when reporting the bug on: https://github.com/godotengine/godot/issues
[1] /lib/x86_64-linux-gnu/libc.so.6(+0x3bcf0) [0x7f633d03bcf0] (??:0)
-- END OF BACKTRACE --
```

**Comment by anvilfolk** [comment] 2022-12-25 14:10
It would be absolutely excellent if someone could provide an MRP for these `ERROR: Condition "!method" is true. Returning: false
   at: is_builtin_method_vararg (core/variant/variant_call.cpp:1339)` errors and link it here. We know there's some serious issues with that right now but it's been hard to pin-point. An MRP would go a long way <3

**Comment by dalexeev** [comment] 2022-12-25 14:48
> It would be absolutely excellent if someone could provide an MRP

Here's the reason:

```gdscript
extends Node

func _ready() -> void:
    print(MyClass.MyEnum.get_size())
```

[issue-70495.zip](https://github.com/godotengine/godot/files/10300157/issue-70495.zip)

**Comment by anvilfolk** [comment] 2022-12-25 15:04
💯 thank you! Will look into it!! :)

**Comment by anvilfolk** [comment] 2022-12-25 22:38
@dalexeev thank you! Found the issue, fixed in #70569 :)

That plus the currently linked PR should fix everything in this thread, I believe!

**Comment by dalexeev** [comment] 2022-12-25 23:00
I think these cases should be added to the tests to reduce the chance of such regressions in the future.

**Comment by anvilfolk** [comment] 2022-12-25 23:04
Oh, perfect call, I'll do that now! Thanks for the reminder, I always forget it for myself :) We're slowly building a bigger and bigger test suite that will hopefully catch a whole lot more.

**Comment by anvilfolk** [comment] 2022-12-25 23:09
So actually, I just realized this doesn't happen when enums are in the same file, so there's something else happening here that's throwing me for a loop and I want to dig a little more, because I might've fixed a symptom and not a cause.

**Closed** 2022-12-30 15:10 UTC
Labels: bug, topic:gdscript, crash, regression
