### ISSUE TITLE
Normalmap Importing (s3tc.stex) not working on certain Normal Map Textures in 3D graphics.

### ISSUE THREAD

**Issue by Corruptinator** [godotengine/godot#9311] opened 2017-06-22 09:36 UTC
**Operating system or device - Godot version:**

3.0 Alpha Source Code Build, Windows 10 Pro, Wacom Cintiq Companion 2

**Issue description:**

I was trying to import a normalmap onto an object to test the PBR shading, but unfortunately, somewhere during the import process, the s3tc.stex didn't import the texture the right way...

This link shows a screenshot with cut pieces attached of what I am talking about
![normal_error_demo](https://user-images.githubusercontent.com/5027750/27427226-0bcd1bb0-56f3-11e7-987e-16efd341db21.png)

The engine somehow hasn't read or imported the normalmap correctly and now the object is completely glitched. In the resource tab the imported normalmap looks glitched in the preview, and the inspector editor isn't loading the normalmap texture.

**Steps to reproduce:**

I've included the albedo, roughness, rim, and normalmap textures so then you can see if you're seeing the same problem. 

1. In an empty scene, create a WorldEnvironment Node and add a panorama .exr or .hdr texture.
2. Add a Mesh Instance Node and create either a cube, cylinder, or etc in the "Mesh" option.
3. Create a SpatialMaterial in the Materials slot, and start adding the attached textures to the object.

Let me know if you're having the same problem, because I think either I did something wrong with the normalmapping or that the import process needs a tweak for normalmapping.

![powerpost_rim](https://user-images.githubusercontent.com/5027750/27427171-e51f9736-56f2-11e7-8c6a-7798633f25bd.png)
![powerpost_roughness](https://user-images.githubusercontent.com/5027750/27427172-e521edec-56f2-11e7-9930-69df4108cf33.png)
![powerpost_albedo](https://user-images.githubusercontent.com/5027750/27427174-e523a6dc-56f2-11e7-8b71-1c8bd24ef475.png)
![powerpost_normal](https://user-images.githubusercontent.com/5027750/27427173-e52328ec-56f2-11e7-8610-d5905bfccddd.png)

**Comment by bojidar-bg** [comment] 2017-06-22 09:42
Isn't this a dupe of #9267?

**Comment by Corruptinator** [comment] 2017-06-22 09:55
Maybe, but this is a different outcome for me. Nonetheless I just wanted to point out what I encountered just so then I hopefully wasn't the only one witnessing this bug.

**Comment by karroffel** [comment] 2017-06-22 10:26
I didn't know there's an alpha build yet 🤔

**Comment by Corruptinator** [comment] 2017-06-22 12:06
It was a source code compilation using scons. Sorry. I should have elaborated on that.

**Comment by Corruptinator** [comment] 2017-07-05 09:36
**UPDATE**, I realized that one of the older 3.0 builds actually managed to load Normals appropriately:

https://github.com/godotengine/godot/tree/47b34bf79be1ba2fe4a99c8931732efac68a0b87

The link to the Tree build where Reduzio released a patch for Intel based computers: "_Remove error spam on Intel, closes #8665_" Allows the engine to read, load, and convert the Normals correctly into the s3tc.stex and other stex files.

With that in mind, was there any difference between this build and the most recent patch update that caused the Normalmaps to be glitched out in s3tc.stex files?

**Comment by bojidar-bg** [comment] 2017-07-05 12:09
`git bisect`, anyone? 😃

**Comment by Corruptinator** [comment] 2017-07-21 00:31
QUICK UPDATE: I have successfully narrowed down where the glitch was occurring using the `git bisect` that @bojidar-bg suggested. According to the narrowed down results, the glitch occurred in this commit:

> [b19225bfce3dab39f8ce6b1ecf610ea0ba650f99] -Fix freezes caused by etccomp2, closes #9183 -Normalmaps are now detected and imported as RGTC, both in S3TC and ETC2, this improves their quality.

Somehow this patch caused the normalmap glitch to occur, can somebody confirm this and that which files are affected?

**Comment by bojidar-bg** [comment] 2017-07-23 08:51
Ping @reduz, @tagcup. I assume this is caused by the "Detect normalmaps" part 😄

**Comment by tagcup** [comment] 2017-07-23 12:36
Oh, I actually had nothing to do with the normal map detection part so best ping @reduz I'll try to take a look too

**Comment by reduz** [comment] 2017-08-07 01:31
this is fixed now, closing

**Closed by reduz** 2017-08-07 01:31 UTC
Labels: bug, topic:rendering
