### ISSUE TITLE
Inconsitent peer id type in C#

### ISSUE THREAD

**Issue by jahu00** [godotengine/godot#75396] opened 2023-03-27 16:05 UTC
### Godot version

4.0.1 stable mono win64

### System information

irrelevant

### Issue description

In multiplayer, sometimes `int` and sometimes `long` is used for peer id. For example `PeerConnected` and `PeerDisconnected` signals from the `MultiplayerApi` class pass peer id as `long`. However `GetUniqueId` from the same class returns `int`. If peer id can reach values outside of what `int` can store, then this is a problem. If the values are all within `int`'s range, this is less of an issue and `long` can probably be replaced by `int` for peer ids used in signals.

### Steps to reproduce

Compare the type used for peer id in `PeerConnected` of `MultiplayerApi` class with type returned by `GetUniqueId` from the same class.

### Minimal reproduction project

N/A

**Comment by Calinou** [comment] 2023-04-01 17:15
cc @raulsntos

**Comment by RedworkDE** [comment] 2023-04-01 18:05
- Duplicate of https://github.com/godotengine/godot/issues/65749

The engine uses 32 bit values for the peer id, so values outside the int range are never valid.
The signal parameters are of the wrong type as tracked by the linked issue.

**Comment by raulsntos** [comment] 2023-04-01 23:06
Duplicate of https://github.com/godotengine/godot/issues/65749

**Closed by raulsntos** 2023-04-01 23:06 UTC
Labels: bug, topic:network, topic:dotnet
