### ISSUE TITLE
Changing the animation speed of an AnimatedSprite2D and switching to another animation, while Animation speed is still in focus will change the speed of the animation you switched to

### ISSUE THREAD

**Issue by HooptyDaDoopty** [godotengine/godot#79634] opened 2023-07-18 19:52 UTC
### Godot version

4.1 [Stable]

### System information

Windows11 Pro, Forward+

### Issue description

I'd expect it to not change the speed of the animation that I switched to

### Steps to reproduce

Add an AnimatedSprite2D node to a Node2D
Create new sprite frames from the inspector.
Add a second, third, forth, etc. etc. animation in the SpriteFrames window.
Select one of the animations you've just created.
Highlight animation speed (says 5 FPS by default, I think)
type in any number and hit enter.
without clicking anywhere else, or pressing any buttons, click on another animation that you've created.
And voila! it set the animation speed for both animations

### Minimal reproduction project

[AnimatedSprite2D_animation_speed_bug_rep.zip](https://github.com/godotengine/godot/files/12088528/AnimatedSprite2D_animation_speed_bug_rep.zip)

**Comment by AThousandShips** [comment] 2023-07-18 19:53
Duplicate of #79445

**Closed by AThousandShips** 2023-07-18 19:53 UTC

**Comment by HooptyDaDoopty** [comment] 2023-07-18 19:55
My honor:D
