### ISSUE TITLE
textureSize function output does not update when the texture is updated programmatically

### ISSUE THREAD

**Issue by RedNicStone** [godotengine/godot#74394] opened 2023-03-04 21:31 UTC
### Godot version

4.0

### System information

Fedora Linux 37, Nvidia 4090, Vulkan 1.3, nv 525.60.11

### Issue description

When using the `textureSize` function in a godot shader the function output is not updated when the texture is updated programmatically using `<material>.set_shader_parameter("<parameter>", <texture>)` in gdscript if the texture was previously undefined.

### Steps to reproduce

Create a shader that uses a texture uniform and messures the texture size using `textureSize`. Make sure to leave the texture parameter undefined. Update the texture uniform at runtime using `<material>.set_shader_parameter("<parameter>", <texture>)`. The textureSize will not be updated.

### Minimal reproduction project

N/A

**Comment by clayjohn** [comment] 2023-03-04 22:47
Can you please upload an MRP? 

As a note, there is nothing distinguishing between ``textureSize`` and the other texture functions. It sounds like the texture is not getting set properly. This could be caused by a number of different issues such as:
1. The texture not being probably loaded on the GDScript side
2. The string parameters containing a typo
3. The wrong material being used. 

An MRP will help us narrow down where the issue is coming from

**Comment by RedNicStone** [comment] 2023-03-05 13:43
Hi, I'm sorry I dident quite test where the issue occurs exactly.
I can confirm that the texture is being loaded in correctly, the right parameter is used and the right material is chosen.
I created a small MRP which demonstrates the issue. As I do in my actual project, I used a viewport texture here (this has to be set dynamically in my project as the viewport is in a different scene than the material).
From a little more testing I could conclude that the issue is probably that setting a texture uniform to a viewport texture resets the size to 0.

The MRP contains a quad with an example shader which displays the resolution of the used texture and the texture itself. I hope this can help to resolve the issue.
[test.tar.gz](https://github.com/godotengine/godot/files/10891929/test.tar.gz)

**Comment by clayjohn** [comment] 2023-03-08 00:05
The MRP appears to be working correctly for me. Here is the output I get:
![image](https://user-images.githubusercontent.com/16521339/223583594-0e4f6963-09e0-4005-9bea-6d610bb092c7.png)

Which is correct because the viewport is 512x512 and the shader is reading from mip level 1. 

I got the same result just running the MRP (which had a texture assigned that got overridden at run time) and by ensuring that there was no texture in the uniform to start.

**Comment by RedNicStone** [comment] 2023-03-08 18:29
For me the MRN produces a different result:
![image](https://user-images.githubusercontent.com/36967667/223802606-fb685dde-f44b-4984-bf00-f38c6c116d30.png)

I'm running Fedora Linux 37 with a  Nvidia 4090 running Vulkan 1.3 driver 525.60.11
My godot version is v4.1.dev.custom_build [553c80459], but I've tested it on the v4.0 release with the same result

**Comment by bitsawer** [comment] 2023-06-10 11:46
I can reproduce the reported issue (NVIDIA GTX 970), but I think it is expected. When the project is run, it uses set_shader_parameter() to set the SubViewport texture instead of a normal texture resource. I believe Viewport textures don't normally have mipmaps. So this line:

`float texture_size = float(textureSize(textureIn, 1).x) + 0.1;`

tries to get the size of a non-existent mip level. Note that levels are zero based, so changing it to

`float texture_size = float(textureSize(textureIn, 0).x) + 0.1;`

works as expected, both in editor and when running the project. If things work on other devices it might be just down to driver/hardware quirks that maybe return the largest valid mipmap size when textureSize() is used on an invalid mipmap level.

**Comment by bitsawer** [comment] 2023-08-15 14:46
Checked the OpenGL spec about `textureSize()` just in case:

```
The value returned is undefined if:

• the texture is not complete;
• the texture is not mipmap complete, and the computed texture level is not level base; or
• the computed texture image level is outside the range [levelbase, q], where q is defined in section 8.14.3.
```

Looks like point at least point 2 applies here, I'll close this issue as not a bug. We could mention this in documentation, but in that case we would have to add a huge amount of similar issues there. At that point, we might as well just link to OpenGL and Vulkan specs instead.

**Closed by bitsawer** 2023-08-15 14:46 UTC
Labels: needs testing
