### ISSUE TITLE
Feature Request - ability to zoom into/out of visual script with mouse wheel.

### ISSUE THREAD

**Issue by liquidape** [godotengine/godot#6647] opened 2016-09-29 16:20 UTC
The ability to be able to zoom into/out of your visual script with the mouse wheel would be very nice - and is probably the first way that people try to navigate the script.

**Comment by eska014** [comment] 2016-09-29 16:39
Duplicate of #6168, please use that issue

**Closed by eska014** 2016-09-29 16:39 UTC
