### ISSUE TITLE
Changing project name disables mono

### ISSUE THREAD

**Issue by ElGatoNinja** [godotengine/godot#46290] opened 2021-02-21 16:28 UTC
**Godot version:**
3.2.3.stable.mono.official

**OS/device including version:**
Windows 10

**Issue description:**
When the project name is changed through **Project Settings -> Config -> Name**, the mono tab and the "build" top right button vanishes. 
It's not a big deal because it is solved just by adding a new c# script. But I was extremely afraid when I saw it, and took me a long time to notice.

**Steps to reproduce:**
First:
**Create a new project** 
**Add a new c# script.**
Now mono tab is visible and you can build the project.
Go to **Project Settings -> Config -> Name** 
**change the name**
Mono tab still there and you can build the project as before.
Last step:
**Close Godot** 
**Open Godot**
Not mono anymore!!!

**EDIT with extra info**
The "workarround" of creating a new script is not really restoring mono but creating a new solution and a new csproj for the new name, the old ones still in the directory unchanged.

**Comment by paulloz** [comment] 2021-03-07 14:23
Related to #15624.

**Comment by akien-mga** [comment] 2021-04-28 13:28
Duplicate of #27030.

**Closed by akien-mga** 2021-04-28 13:28 UTC
Labels: bug, topic:editor, topic:mono
