### ISSUE TITLE
Drag to resize the node in Godot Editor become extremely uncontrollable in 3.2.4 RC5

### ISSUE THREAD

**Issue by alexzheng** [godotengine/godot#47126] opened 2021-03-18 04:42 UTC
**Godot version:**

3.2.4 RC5

**OS/device including version:**

Mac OS

**Issue description:**

In 2D scene editor, when drag an anchor to resize a node, it uncontrollable, it scales very fast.
I had not see this issue before rc5.

**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by akien-mga** [comment] 2021-03-18 07:41
Duplicate of #46979.

**Closed by akien-mga** 2021-03-18 07:41 UTC
